v8::internal::compiler::turboshaft::Type Class Reference
#include <types.h>
Public Types
enum class Kind : uint8_t {
kInvalid
, kNone
, kWord32
, kWord64
,
kFloat32
, kFloat64
, kTuple
, kAny
 }
enum class ResolutionMode { kPreciseOrInvalid
, kOverApproximate
, kGreatestLowerBound
 }
Public Member Functions
Type ()
Kind kind () const
bool IsInvalid () const
bool IsNone () const
bool IsWord32 () const
bool IsWord64 () const
bool IsFloat32 () const
bool IsFloat64 () const
bool IsTuple () const
bool IsAny () const
template<size_t B>
bool IsWord () const
template<size_t B>
bool IsFloat () const
const Word32Type & AsWord32 () const
const Word64Type & AsWord64 () const
const Float32Type & AsFloat32 () const
const Float64Type & AsFloat64 () const
const TupleType & AsTuple () const
template<size_t B>
const auto & AsWord () const
template<size_t B>
const auto & AsFloat () const
bool Equals (const Type &other) const
bool IsSubtypeOf (const Type &other) const
void PrintTo (std::ostream &stream) const
void Print () const
std::string ToString () const
Handle< TurboshaftType > AllocateOnHeap (Factory *factory) const
Static Public Member Functions
static Type Invalid ()
static Type None ()
static Type Any ()
static Type LeastUpperBound (const Type &lhs, const Type &rhs, Zone *zone)
static std::optional< Type > ParseFromString (const std::string_view &str, Zone *zone)
Protected Member Functions
template<typename Payload >
Type (Kind kind, uint8_t sub_kind, uint8_t set_size, uint32_t bitfield, uint8_t reserved, const Payload &payload)
template<typename Payload >
const Payload & get_payload () const
Protected Attributes
xx xx xx xx xx xx xx xx xx
union {
 struct {
  Kind kind_
  uint8_t sub_kind_
  uint8_t set_size_
  uint8_t reserved_
  uint32_t bitfield_
 }
 uint64_t header_
};
Private Member Functions
Type (Kind kind)
Private Attributes
uint64_t payload_ [2]
Friends
struct fast_hash< Type >
Detailed Description
Definition at line 174 of file types.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::Type::Kind : uint8_t [strong]
Enumerator
kInvalid
kNone
kWord32
kWord64
kFloat32
kFloat64
kTuple
kAny
Definition at line 176 of file types.h.
                  : uint8_t {
    kInvalid,
    kNone,
    kWord32,
    kWord64,
    kFloat32,
    kFloat64,
    kTuple,
    kAny,
  };
ResolutionMode
enum v8::internal::compiler::turboshaft::Type::ResolutionMode [strong]
Enumerator
kPreciseOrInvalid
kOverApproximate
kGreatestLowerBound
Definition at line 191 of file types.h.
                            {
    // Return Type::Invalid().
    kPreciseOrInvalid,
    // Return a safe over approximation.
    kOverApproximate,
    // Return the greatest lower bound that can be represented.
    kGreatestLowerBound,
  };
Constructor & Destructor Documentation
Type() [1/3]
v8::internal::compiler::turboshaft::Type::Type () [inline]
Definition at line 200 of file types.h.
: Type(Kind::kInvalid) {}
Type() [2/3]
template<typename Payload >
v8::internal::compiler::turboshaft::Type::Type (Kind kind, uint8_t sub_kind, uint8_t set_size, uint32_t bitfield, uint8_t reserved, const Payload & payload) [inline], [protected]
Definition at line 278 of file types.h.
      : kind_(kind),
        sub_kind_(sub_kind),
        set_size_(set_size),
        reserved_(reserved),
        bitfield_(bitfield) {
    static_assert(sizeof(Payload) <= sizeof(payload_));
    memcpy(&payload_[0], &payload, sizeof(Payload));
    if constexpr (sizeof(Payload) < sizeof(payload_)) {
      memset(reinterpret_cast<uint8_t*>(&payload_[0]) + sizeof(Payload), 0x00,
             sizeof(payload_) - sizeof(Payload));
    }
  }
Type() [3/3]
v8::internal::compiler::turboshaft::Type::Type (Kind kind) [inline], [explicit], [private]
Definition at line 316 of file types.h.
                           : Type(kind, 0, 0, 0, 0, detail::Payload_Empty{}) {
    DCHECK(kind == Kind::kInvalid || kind == Kind::kNone || kind == Kind::kAny);
  }
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{isolate.cc}::kInvalid.
Member Function Documentation
AllocateOnHeap()
Handle<TurboshaftType> v8::internal::compiler::turboshaft::Type::AllocateOnHeap (Factory * factory) const
Any()
static Type v8::internal::compiler::turboshaft::Type::Any () [inline], [static]
Definition at line 205 of file types.h.
{ return Type(Kind::kAny); }
Referenced by v8::internal::compiler::JSGraphAssembler::Allocate(), v8::internal::compiler::WasmGraphAssembler::Allocate(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Atan2(), v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Divide(), v8::internal::compiler::AccessBuilder::ForCellValue(), v8::internal::compiler::AccessBuilder::ForContextCellTaggedValue(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::AccessBuilder::ForContextSlotKnownPointer(), v8::internal::compiler::AccessBuilder::ForExternalIntPtr(), v8::internal::compiler::AccessBuilder::ForFeedbackVectorClosureFeedbackCellArray(), v8::internal::compiler::AccessBuilder::ForFeedbackVectorSlot(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForFixedArraySlot(), v8::internal::compiler::AccessBuilder::ForJSFunctionPrototypeOrInitialMap(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHash(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMapNativeContext(), v8::internal::compiler::AccessBuilder::ForMapPrototype(), v8::internal::compiler::AccessBuilder::ForOrderedHashMapEntryValue(), v8::internal::compiler::AccessBuilder::ForOrderedHashMapOrSetNextTable(), v8::internal::compiler::AccessBuilder::ForPropertyArraySlot(), v8::internal::compiler::AccessBuilder::ForSloppyArgumentsElementsArguments(), v8::internal::compiler::AccessBuilder::ForSloppyArgumentsElementsContext(), v8::internal::compiler::AccessBuilder::ForSloppyArgumentsElementsMappedEntry(), v8::internal::compiler::AccessBuilder::ForWeakFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForWeakFixedArraySlot(), v8::internal::compiler::NodeProperties::GetTypeOrAny(), v8::internal::compiler::anonymous_namespace{operation-typer.cc}::JSType(), v8::internal::compiler::turboshaft::TupleType::LeastUpperBound(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Modulus(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), v8::internal::compiler::RawMachineAssembler::OptimizedAllocate(), v8::internal::compiler::RawMachineAssembler::OptimizedStoreField(), v8::internal::compiler::RawMachineAssembler::OptimizedStoreIndirectPointerField(), v8::internal::compiler::turboshaft::TypeParser::ParseType(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessConstant(), v8::internal::compiler::TypeNarrowingReducer::Reduce(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThan_False(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThanOrEqual_False(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::compiler::turboshaft::Typer::TypeConstant(), v8::internal::compiler::turboshaft::Typer::TypeForRepresentation(), v8::internal::compiler::turboshaft::Typer::TypeProjection(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeSmallIntegerAdditiveOp(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::Widen().
AsFloat()
template<size_t B>
const auto& v8::internal::compiler::turboshaft::Type::AsFloat () const [inline]
Definition at line 249 of file types.h.
                                     {
    static_assert(B == 32 || B == 64);
    if constexpr (B == 32)
      return AsFloat32();
    else
      return AsFloat64();
  }
References v8::internal::B.
AsFloat32()
const Float32Type& v8::internal::compiler::turboshaft::Type::AsFloat32 () const [inline]
Referenced by v8::internal::compiler::turboshaft::Typer::TypeFloat32Comparison().
AsFloat64()
const Float64Type& v8::internal::compiler::turboshaft::Type::AsFloat64 () const [inline]
Referenced by v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineTypes(), and v8::internal::compiler::turboshaft::Typer::TypeFloat64Comparison().
AsTuple()
const TupleType& v8::internal::compiler::turboshaft::Type::AsTuple () const [inline]
Referenced by v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessProjection(), and v8::internal::compiler::turboshaft::Typer::TypeProjection().
AsWord()
template<size_t B>
const auto& v8::internal::compiler::turboshaft::Type::AsWord () const [inline]
Definition at line 241 of file types.h.
                                    {
    static_assert(B == 32 || B == 64);
    if constexpr (B == 32)
      return AsWord32();
    else
      return AsWord64();
  }
References v8::internal::B.
AsWord32()
const Word32Type& v8::internal::compiler::turboshaft::Type::AsWord32 () const [inline]
Referenced by v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineTypes(), v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineWord32Type(), v8::internal::compiler::turboshaft::Typer::TruncateWord32Input(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::Widen().
AsWord64()
const Word64Type& v8::internal::compiler::turboshaft::Type::AsWord64 () const [inline]
Referenced by v8::internal::compiler::turboshaft::Typer::TruncateWord32Input(), v8::internal::compiler::turboshaft::Typer::TypeWord64Add(), v8::internal::compiler::turboshaft::Typer::TypeWord64Comparison(), v8::internal::compiler::turboshaft::Typer::TypeWord64Sub(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::Widen().
Equals()
bool v8::internal::compiler::turboshaft::Type::Equals (const Type & other) const
Referenced by v8::internal::compiler::turboshaft::TupleType::Equals(), v8::internal::compiler::turboshaft::operator!=(), and v8::internal::compiler::turboshaft::operator==().
get_payload()
template<typename Payload >
const Payload& v8::internal::compiler::turboshaft::Type::get_payload () const [inline], [protected]
Definition at line 294 of file types.h.
                                     {
    static_assert(sizeof(Payload) <= sizeof(payload_));
    return *reinterpret_cast<const Payload*>(&payload_[0]);
  }
Invalid()
static Type v8::internal::compiler::turboshaft::Type::Invalid () [inline], [static]
Definition at line 203 of file types.h.
{ return Type(); }
Referenced by v8::internal::compiler::turboshaft::TypeInferenceAnalysis::GetTypeOrInvalid(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetTypeOrInvalid(), v8::internal::compiler::turboshaft::WordType< Bits >::Intersect(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), and v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RemoveLast().
IsAny()
bool v8::internal::compiler::turboshaft::Type::IsAny () const [inline]
Definition at line 216 of file types.h.
{ return kind_ == Kind::kAny; }
Referenced by v8::internal::compiler::turboshaft::Typer::InputIs(), v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineTypes(), v8::internal::compiler::turboshaft::Typer::TruncateWord32Input(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::Widen().
IsFloat()
template<size_t B>
bool v8::internal::compiler::turboshaft::Type::IsFloat () const [inline]
Definition at line 226 of file types.h.
                              {
    static_assert(B == 32 || B == 64);
    if constexpr (B == 32)
      return IsFloat32();
    else
      return IsFloat64();
  }
References v8::internal::B.
IsFloat32()
bool v8::internal::compiler::turboshaft::Type::IsFloat32 () const [inline]
Definition at line 213 of file types.h.
{ return kind_ == Kind::kFloat32; }
IsFloat64()
bool v8::internal::compiler::turboshaft::Type::IsFloat64 () const [inline]
Definition at line 214 of file types.h.
{ return kind_ == Kind::kFloat64; }
IsInvalid()
bool v8::internal::compiler::turboshaft::Type::IsInvalid () const [inline]
Definition at line 209 of file types.h.
{ return kind_ == Kind::kInvalid; }
References v8::internal::anonymous_namespace{isolate.cc}::kInvalid.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceAnalysis::GetType(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::GetTypeOrDefault(), v8::internal::compiler::turboshaft::Typer::InputIs(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessLoopPhi(), v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineTypeFromInputGraph(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::SetType(), v8::internal::compiler::turboshaft::Typer::TruncateWord32Input(), v8::internal::compiler::turboshaft::Typer::TypeFloatBinop(), v8::internal::compiler::turboshaft::Typer::TypeOverflowCheckedBinop(), and v8::internal::compiler::turboshaft::Typer::TypeWordBinop().
IsNone()
bool v8::internal::compiler::turboshaft::Type::IsNone () const [inline]
Definition at line 210 of file types.h.
{ return kind_ == Kind::kNone; }
Referenced by v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessLoopPhi(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessProjection(), v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineTypes(), v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineWord32Type(), v8::internal::compiler::turboshaft::Typer::TruncateWord32Input(), v8::internal::compiler::turboshaft::Typer::TypeComparison(), v8::internal::compiler::turboshaft::Typer::TypeFloat32Comparison(), v8::internal::compiler::turboshaft::Typer::TypeFloat64Comparison(), v8::internal::compiler::turboshaft::Typer::TypeProjection(), v8::internal::compiler::turboshaft::Typer::TypeWord32Add(), v8::internal::compiler::turboshaft::Typer::TypeWord32Comparison(), v8::internal::compiler::turboshaft::Typer::TypeWord32OverflowCheckedAdd(), v8::internal::compiler::turboshaft::Typer::TypeWord32Sub(), v8::internal::compiler::turboshaft::Typer::TypeWord64Add(), v8::internal::compiler::turboshaft::Typer::TypeWord64Comparison(), and v8::internal::compiler::turboshaft::Typer::TypeWord64Sub().
IsSubtypeOf()
bool v8::internal::compiler::turboshaft::Type::IsSubtypeOf (const Type & other) const
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::CheckTurboshaftTypeOf(), v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::compiler::turboshaft::TupleType::IsSubtypeOf(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessCheckTurboshaftTypeOf(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessLoopPhi(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessProjection(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineTypes(), and v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType().
IsTuple()
bool v8::internal::compiler::turboshaft::Type::IsTuple () const [inline]
Definition at line 215 of file types.h.
{ return kind_ == Kind::kTuple; }
Referenced by v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessProjection(), and v8::internal::compiler::turboshaft::Typer::TypeProjection().
IsWord()
template<size_t B>
bool v8::internal::compiler::turboshaft::Type::IsWord () const [inline]
Definition at line 218 of file types.h.
                             {
    static_assert(B == 32 || B == 64);
    if constexpr (B == 32)
      return IsWord32();
    else
      return IsWord64();
  }
References v8::internal::B.
IsWord32()
bool v8::internal::compiler::turboshaft::Type::IsWord32 () const [inline]
Definition at line 211 of file types.h.
{ return kind_ == Kind::kWord32; }
Referenced by v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineWord32Type(), and v8::internal::compiler::turboshaft::Typer::TruncateWord32Input().
IsWord64()
bool v8::internal::compiler::turboshaft::Type::IsWord64 () const [inline]
Definition at line 212 of file types.h.
{ return kind_ == Kind::kWord64; }
Referenced by v8::internal::compiler::turboshaft::Typer::TruncateWord32Input().
kind()
Kind v8::internal::compiler::turboshaft::Type::kind () const [inline]
Definition at line 208 of file types.h.
{ return kind_; }
Referenced by v8::internal::compiler::turboshaft::Typer::InputIs(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::Widen().
LeastUpperBound()
static Type v8::internal::compiler::turboshaft::Type::LeastUpperBound (const Type & lhs, const Type & rhs, Zone * zone) [static]
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ComputeTypeForPhi(), v8::internal::compiler::turboshaft::TupleType::LeastUpperBound(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Phi(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock().
None()
static Type v8::internal::compiler::turboshaft::Type::None () [inline], [static]
Definition at line 204 of file types.h.
{ return Type(Kind::kNone); }
Referenced by v8::internal::compiler::Typer::Visitor::BigIntCompareTyper(), v8::internal::compiler::Typer::Visitor::BinaryNumberOpTyper(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::OperationTyper::CheckBounds(), v8::internal::compiler::CommonOperatorReducer::CommonOperatorReducer(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ComputeTypeForPhi(), v8::internal::compiler::DeadCodeElimination::DeadCodeElimination(), v8::internal::compiler::DeadCodeElimination::DeadValue(), v8::internal::compiler::Typer::Visitor::FalsifyUndefined(), v8::internal::compiler::RepresentationSelector::FeedbackTypeOf(), v8::internal::compiler::RepresentationChanger::GetBitRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat16RawBitsRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), v8::internal::compiler::RepresentationSelector::GetOutputInfoForPhi(), v8::internal::compiler::RepresentationChanger::GetTaggedPointerRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedSignedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::GraphReducer::GraphReducer(), v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint(), v8::internal::compiler::SimplifiedLoweringVerifier::InputType(), v8::internal::compiler::turboshaft::FloatType< Bits >::Intersect(), v8::internal::compiler::turboshaft::WordType< Bits >::Intersect(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Phi(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessProjection(), v8::internal::compiler::DeadCodeElimination::ReduceDeoptimizeOrReturnOrTerminateOrTailCall(), v8::internal::compiler::DeadCodeElimination::ReduceEffectNode(), v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineTypes(), v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineWord32Type(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThan_True(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThanOrEqual_True(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThan_True(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThanOrEqual_False(), v8::internal::compiler::OperationTyper::SameValue(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::SetType(), v8::internal::compiler::Typer::Visitor::TypeBinaryOp(), v8::internal::compiler::turboshaft::Typer::TypeComparison(), v8::internal::compiler::turboshaft::Typer::TypeFloat32Comparison(), v8::internal::compiler::turboshaft::Typer::TypeFloat64Comparison(), v8::internal::compiler::Typer::Visitor::TypeOrNone(), v8::internal::compiler::turboshaft::Typer::TypeProjection(), v8::internal::compiler::Typer::Visitor::TypeUnaryOp(), v8::internal::compiler::turboshaft::Typer::TypeWord32Add(), v8::internal::compiler::turboshaft::Typer::TypeWord32Comparison(), v8::internal::compiler::turboshaft::Typer::TypeWord32OverflowCheckedAdd(), v8::internal::compiler::turboshaft::Typer::TypeWord32Sub(), v8::internal::compiler::turboshaft::Typer::TypeWord64Add(), v8::internal::compiler::turboshaft::Typer::TypeWord64Comparison(), v8::internal::compiler::turboshaft::Typer::TypeWord64Sub(), v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode(), and v8::internal::compiler::RepresentationSelector::VisitNode().
ParseFromString()
static std::optional<Type> v8::internal::compiler::turboshaft::Type::ParseFromString (const std::string_view & str, Zone * zone) [static]
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
Print()
void v8::internal::compiler::turboshaft::Type::Print () const
PrintTo()
void v8::internal::compiler::turboshaft::Type::PrintTo (std::ostream & stream) const
Referenced by v8::internal::compiler::turboshaft::TupleType::PrintTo().
ToString()
std::string v8::internal::compiler::turboshaft::Type::ToString () const [inline]
Definition at line 264 of file types.h.
                             {
    std::stringstream stream;
    PrintTo(stream);
    return stream.str();
  }
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::CheckTurboshaftTypeOf(), v8::internal::compiler::turboshaft::Typer::InputIs(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessCheckTurboshaftTypeOf(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessLoopPhi(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineTypeFromInputGraph(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::SetType(), and v8::internal::compiler::turboshaft::Typer::TruncateWord32Input().
Friends And Related Function Documentation
fast_hash< Type >
friend struct fast_hash< Type > [friend]
Definition at line 313 of file types.h.
Member Data Documentation
union { ... } [protected]
bitfield_
uint32_t v8::internal::compiler::turboshaft::Type::bitfield_
Definition at line 305 of file types.h.
header_
uint64_t v8::internal::compiler::turboshaft::Type::header_
Definition at line 308 of file types.h.
kind_
Kind v8::internal::compiler::turboshaft::Type::kind_
Definition at line 301 of file types.h.
payload_
uint64_t v8::internal::compiler::turboshaft::Type::payload_[2] [private]
Definition at line 313 of file types.h.
reserved_
uint8_t v8::internal::compiler::turboshaft::Type::reserved_
Definition at line 304 of file types.h.
set_size_
uint8_t v8::internal::compiler::turboshaft::Type::set_size_
Definition at line 303 of file types.h.
sub_kind_
uint8_t v8::internal::compiler::turboshaft::Type::sub_kind_
Definition at line 302 of file types.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/types.h