v8::internal::maglev::MaxCallDepthProcessor Class Reference
#include <maglev-pre-regalloc-codegen-processors.h>
Public Member Functions
void PreProcessGraph (Graph *graph)
void PostProcessGraph (Graph *graph)
void PostProcessBasicBlock (BasicBlock *block)
BlockProcessResult PreProcessBasicBlock (BasicBlock *block)
void PostPhiProcessing ()
template<typename NodeT >
ProcessResult Process (NodeT *node, const ProcessingState &state)
Private Member Functions
void UpdateMaxDeoptedStackSize (DeoptInfo *deopt_info)
int ConservativeFrameSize (const DeoptFrame *deopt_frame)
Private Attributes
int max_call_stack_args_ = 0
int max_deopted_stack_size_ = 0
const MaglevCompilationUnit * last_seen_unit_ = nullptr
Detailed Description
Definition at line 56 of file maglev-pre-regalloc-codegen-processors.h.
Member Function Documentation
ConservativeFrameSize()
int v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize (const DeoptFrame * deopt_frame) [inline], [private]
Definition at line 108 of file maglev-pre-regalloc-codegen-processors.h.
                                                           {
    switch (deopt_frame->type()) {
      case DeoptFrame::FrameType::kInterpretedFrame: {
        auto info = UnoptimizedFrameInfo::Conservative(
            deopt_frame->as_interpreted().unit().parameter_count(),
            deopt_frame->as_interpreted().unit().register_count());
        return info.frame_size_in_bytes();
      }
      case DeoptFrame::FrameType::kConstructInvokeStubFrame: {
        return FastConstructStubFrameInfo::Conservative().frame_size_in_bytes();
      }
      case DeoptFrame::FrameType::kInlinedArgumentsFrame: {
        return std::max(
            0,
            static_cast<int>(
                deopt_frame->as_inlined_arguments().arguments().size() -
                deopt_frame->as_inlined_arguments().unit().parameter_count()) *
                kSystemPointerSize);
      }
      case DeoptFrame::FrameType::kBuiltinContinuationFrame: {
        // PC + FP + Closure + Params + Context
        const RegisterConfiguration* config = RegisterConfiguration::Default();
        auto info = BuiltinContinuationFrameInfo::Conservative(
            deopt_frame->as_builtin_continuation().parameters().length(),
            Builtins::CallInterfaceDescriptorFor(
                deopt_frame->as_builtin_continuation().builtin_id()),
            config);
        return info.frame_size_in_bytes();
      }
    }
  }
References v8::internal::maglev::InlinedArgumentsDeoptFrame::arguments(), v8::internal::maglev::DeoptFrame::as_builtin_continuation(), v8::internal::maglev::DeoptFrame::as_inlined_arguments(), v8::internal::maglev::DeoptFrame::as_interpreted(), v8::internal::maglev::BuiltinContinuationDeoptFrame::builtin_id(), v8::internal::Builtins::CallInterfaceDescriptorFor(), v8::internal::FastConstructStubFrameInfo::Conservative(), v8::internal::BuiltinContinuationFrameInfo::Conservative(), v8::internal::UnoptimizedFrameInfo::Conservative(), v8::internal::RegisterConfiguration::Default(), v8::internal::FastConstructStubFrameInfo::frame_size_in_bytes(), v8::internal::maglev::DeoptFrame::kBuiltinContinuationFrame, v8::internal::maglev::DeoptFrame::kConstructInvokeStubFrame, v8::internal::maglev::DeoptFrame::kInlinedArgumentsFrame, v8::internal::maglev::DeoptFrame::kInterpretedFrame, v8::internal::kSystemPointerSize, v8::internal::maglev::MaglevCompilationUnit::parameter_count(), v8::internal::maglev::BuiltinContinuationDeoptFrame::parameters(), v8::internal::maglev::MaglevCompilationUnit::register_count(), v8::internal::maglev::DeoptFrame::type(), v8::internal::maglev::InterpretedDeoptFrame::unit(), and v8::internal::maglev::InlinedArgumentsDeoptFrame::unit().
Referenced by UpdateMaxDeoptedStackSize().
PostPhiProcessing()
void v8::internal::maglev::MaxCallDepthProcessor::PostPhiProcessing () [inline]
Definition at line 67 of file maglev-pre-regalloc-codegen-processors.h.
{}
PostProcessBasicBlock()
void v8::internal::maglev::MaxCallDepthProcessor::PostProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 63 of file maglev-pre-regalloc-codegen-processors.h.
{}
PostProcessGraph()
void v8::internal::maglev::MaxCallDepthProcessor::PostProcessGraph (Graph * graph) [inline]
Definition at line 59 of file maglev-pre-regalloc-codegen-processors.h.
                                      {
    graph->set_max_call_stack_args(max_call_stack_args_);
    graph->set_max_deopted_stack_size(max_deopted_stack_size_);
  }
References graph(), max_call_stack_args_, and max_deopted_stack_size_.
PreProcessBasicBlock()
BlockProcessResult v8::internal::maglev::MaxCallDepthProcessor::PreProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 64 of file maglev-pre-regalloc-codegen-processors.h.
                                                             {
    return BlockProcessResult::kContinue;
  }
References v8::internal::maglev::kContinue.
PreProcessGraph()
void v8::internal::maglev::MaxCallDepthProcessor::PreProcessGraph (Graph * graph) [inline]
Definition at line 58 of file maglev-pre-regalloc-codegen-processors.h.
{}
Process()
template<typename NodeT >
ProcessResult v8::internal::maglev::MaxCallDepthProcessor::Process (NodeT * node, const ProcessingState & state) [inline]
Definition at line 70 of file maglev-pre-regalloc-codegen-processors.h.
                                                                   {
    if constexpr (NodeT::kProperties.is_call() ||
                  NodeT::kProperties.needs_register_snapshot()) {
      int node_stack_args = node->MaxCallStackArgs();
      if constexpr (NodeT::kProperties.needs_register_snapshot()) {
        // Pessimistically assume that we'll push all registers in deferred
        // calls.
        node_stack_args +=
            kAllocatableGeneralRegisterCount + kAllocatableDoubleRegisterCount;
      }
      max_call_stack_args_ = std::max(max_call_stack_args_, node_stack_args);
    }
    if constexpr (NodeT::kProperties.can_eager_deopt()) {
      UpdateMaxDeoptedStackSize(node->eager_deopt_info());
    }
    if constexpr (NodeT::kProperties.can_lazy_deopt()) {
      UpdateMaxDeoptedStackSize(node->lazy_deopt_info());
    }
    return ProcessResult::kContinue;
  }
References v8::internal::maglev::kAllocatableDoubleRegisterCount, v8::internal::maglev::kAllocatableGeneralRegisterCount, v8::internal::maglev::kContinue, max_call_stack_args_, and UpdateMaxDeoptedStackSize().
UpdateMaxDeoptedStackSize()
void v8::internal::maglev::MaxCallDepthProcessor::UpdateMaxDeoptedStackSize (DeoptInfo * deopt_info) [inline], [private]
Definition at line 92 of file maglev-pre-regalloc-codegen-processors.h.
                                                        {
    const DeoptFrame* deopt_frame = &deopt_info->top_frame();
    int frame_size = 0;
    if (deopt_frame->type() == DeoptFrame::FrameType::kInterpretedFrame) {
      if (&deopt_frame->as_interpreted().unit() == last_seen_unit_) return;
      last_seen_unit_ = &deopt_frame->as_interpreted().unit();
      frame_size = deopt_frame->as_interpreted().unit().max_arguments() *
                   kSystemPointerSize;
    }
    do {
      frame_size += ConservativeFrameSize(deopt_frame);
      deopt_frame = deopt_frame->parent();
    } while (deopt_frame != nullptr);
    max_deopted_stack_size_ = std::max(frame_size, max_deopted_stack_size_);
  }
References v8::internal::maglev::DeoptFrame::as_interpreted(), ConservativeFrameSize(), v8::internal::maglev::DeoptFrame::kInterpretedFrame, v8::internal::kSystemPointerSize, last_seen_unit_, v8::internal::maglev::MaglevCompilationUnit::max_arguments(), max_deopted_stack_size_, v8::internal::maglev::DeoptFrame::parent(), v8::internal::maglev::DeoptInfo::top_frame(), v8::internal::maglev::DeoptFrame::type(), and v8::internal::maglev::InterpretedDeoptFrame::unit().
Referenced by Process().
Member Data Documentation
last_seen_unit_
const MaglevCompilationUnit* v8::internal::maglev::MaxCallDepthProcessor::last_seen_unit_ = nullptr [private]
Definition at line 144 of file maglev-pre-regalloc-codegen-processors.h.
Referenced by UpdateMaxDeoptedStackSize().
max_call_stack_args_
int v8::internal::maglev::MaxCallDepthProcessor::max_call_stack_args_ = 0 [private]
Definition at line 140 of file maglev-pre-regalloc-codegen-processors.h.
Referenced by PostProcessGraph(), and Process().
max_deopted_stack_size_
int v8::internal::maglev::MaxCallDepthProcessor::max_deopted_stack_size_ = 0 [private]
Definition at line 141 of file maglev-pre-regalloc-codegen-processors.h.
Referenced by PostProcessGraph(), and UpdateMaxDeoptedStackSize().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-pre-regalloc-codegen-processors.h