v8::internal::SharedToCounterMap Class Reference
Public Types
using Entry = base::TemplateHashMapEntry< Tagged< SharedFunctionInfo >, uint32_t >
Public Member Functions
void Add (Tagged< SharedFunctionInfo > key, uint32_t count)
uint32_t Get (Tagged< SharedFunctionInfo > key)
Static Private Member Functions
static uint32_t Hash (Tagged< SharedFunctionInfo > key)
Additional Inherited Members
Detailed Description
Definition at line 26 of file debug-coverage.cc.
Member Typedef Documentation
Entry
using v8::internal::SharedToCounterMap::Entry = base::TemplateHashMapEntry<Tagged<SharedFunctionInfo>, uint32_t>
Definition at line 31 of file debug-coverage.cc.
Member Function Documentation
Add()
void v8::internal::SharedToCounterMap::Add (Tagged< SharedFunctionInfo > key, uint32_t count) [inline]
Definition at line 33 of file debug-coverage.cc.
                                                                  {
    Entry* entry = LookupOrInsert(key, Hash(key), []() { return 0; });
    uint32_t old_count = entry->value;
    if (UINT32_MAX - count < old_count) {
      entry->value = UINT32_MAX;
    } else {
      entry->value = old_count + count;
    }
  }
References Hash(), v8::internal::key, v8::base::TemplateHashMapImpl< Tagged< SharedFunctionInfo >, uint32_t, base::KeyEqualityMatcher< Tagged< Object > >, base::DefaultAllocationPolicy >::LookupOrInsert(), and v8::base::TemplateHashMapEntry< Key, Value >::value.
Referenced by v8::internal::anonymous_namespace{debug-coverage.cc}::CollectAndMaybeResetCounts().
Get()
uint32_t v8::internal::SharedToCounterMap::Get (Tagged< SharedFunctionInfo > key) [inline]
Definition at line 43 of file debug-coverage.cc.
                                                      {
    Entry* entry = Lookup(key, Hash(key));
    if (entry == nullptr) return 0;
    return entry->value;
  }
References Hash(), v8::internal::key, v8::base::TemplateHashMapImpl< Tagged< SharedFunctionInfo >, uint32_t, base::KeyEqualityMatcher< Tagged< Object > >, base::DefaultAllocationPolicy >::Lookup(), and v8::base::TemplateHashMapEntry< Key, Value >::value.
Referenced by v8::internal::Coverage::Collect(), and v8::internal::anonymous_namespace{debug-coverage.cc}::CollectAndMaybeResetCounts().
Hash()
static uint32_t v8::internal::SharedToCounterMap::Hash (Tagged< SharedFunctionInfo > key) [inline], [static], [private]
Definition at line 50 of file debug-coverage.cc.
                                                       {
    return static_cast<uint32_t>(key.ptr());
  }
References v8::internal::key.
Referenced by Add(), and Get().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-coverage.cc