v8::internal::UnicodeRangeSplitter Class Reference
#include <regexp-compiler.h>
Public Types
using CharacterRangeVector = base::SmallVector< CharacterRange, kInitialSize >
Public Member Functions
V8_EXPORT_PRIVATE UnicodeRangeSplitter (ZoneList< CharacterRange > *base)
const CharacterRangeVector * bmp () const
const CharacterRangeVector * lead_surrogates () const
const CharacterRangeVector * trail_surrogates () const
const CharacterRangeVector * non_bmp () const
Static Public Attributes
static constexpr int kInitialSize = 8
Private Member Functions
void AddRange (CharacterRange range)
Private Attributes
CharacterRangeVector bmp_
CharacterRangeVector lead_surrogates_
CharacterRangeVector trail_surrogates_
CharacterRangeVector non_bmp_
Detailed Description
Definition at line 610 of file regexp-compiler.h.
Member Typedef Documentation
CharacterRangeVector
using v8::internal::UnicodeRangeSplitter::CharacterRangeVector = base::SmallVector<CharacterRange, kInitialSize>
Definition at line 615 of file regexp-compiler.h.
Constructor & Destructor Documentation
UnicodeRangeSplitter()
v8::internal::UnicodeRangeSplitter::UnicodeRangeSplitter (ZoneList< CharacterRange > * base)
Definition at line 134 of file regexp-compiler-tonode.cc.
                                                                         {
  // The unicode range splitter categorizes given character ranges into:
  // - Code points from the BMP representable by one code unit.
  // - Code points outside the BMP that need to be split into
  // surrogate pairs.
  // - Lone lead surrogates.
  // - Lone trail surrogates.
  // Lone surrogates are valid code points, even though no actual characters.
  // They require special matching to make sure we do not split surrogate pairs.
  for (int i = 0; i < base->length(); i++) AddRange(base->at(i));
}
References v8::internal::anonymous_namespace{regexp-compiler.cc}::AddRange(), v8::internal::ZoneList< T >::at(), and v8::internal::ZoneList< T >::length().
Member Function Documentation
AddRange()
void v8::internal::UnicodeRangeSplitter::AddRange (CharacterRange range) [private]
Definition at line 147 of file regexp-compiler-tonode.cc.
                                                        {
  static constexpr base::uc32 kBmp1Start = 0;
  static constexpr base::uc32 kBmp1End = kLeadSurrogateStart - 1;
  static constexpr base::uc32 kBmp2Start = kTrailSurrogateEnd + 1;
  static constexpr base::uc32 kBmp2End = kNonBmpStart - 1;
  // Ends are all inclusive.
  static_assert(kBmp1Start == 0);
  static_assert(kBmp1Start < kBmp1End);
  static_assert(kBmp1End + 1 == kLeadSurrogateStart);
  static_assert(kLeadSurrogateStart < kLeadSurrogateEnd);
  static_assert(kLeadSurrogateEnd + 1 == kTrailSurrogateStart);
  static_assert(kTrailSurrogateStart < kTrailSurrogateEnd);
  static_assert(kTrailSurrogateEnd + 1 == kBmp2Start);
  static_assert(kBmp2Start < kBmp2End);
  static_assert(kBmp2End + 1 == kNonBmpStart);
  static_assert(kNonBmpStart < kNonBmpEnd);
  static constexpr base::uc32 kStarts[] = {
      kBmp1Start, kLeadSurrogateStart, kTrailSurrogateStart,
      kBmp2Start, kNonBmpStart,
  };
  static constexpr base::uc32 kEnds[] = {
      kBmp1End, kLeadSurrogateEnd, kTrailSurrogateEnd, kBmp2End, kNonBmpEnd,
  };
  CharacterRangeVector* const kTargets[] = {
      &bmp_, &lead_surrogates_, &trail_surrogates_, &bmp_, &non_bmp_,
  };
  static constexpr int kCount = arraysize(kStarts);
  static_assert(kCount == arraysize(kEnds));
  static_assert(kCount == arraysize(kTargets));
  for (int i = 0; i < kCount; i++) {
    if (kStarts[i] > range.to()) break;
    const base::uc32 from = std::max(kStarts[i], range.from());
    const base::uc32 to = std::min(kEnds[i], range.to());
    if (from > to) continue;
    kTargets[i]->emplace_back(CharacterRange::Range(from, to));
  }
}
References arraysize, v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::internal::CharacterRange::from(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kLeadSurrogateEnd, v8::internal::kLeadSurrogateStart, v8::internal::kNonBmpEnd, v8::internal::kNonBmpStart, v8::internal::kTrailSurrogateEnd, v8::internal::kTrailSurrogateStart, v8::internal::CharacterRange::Range(), and v8::internal::CharacterRange::to().
bmp()
const CharacterRangeVector* v8::internal::UnicodeRangeSplitter::bmp () const [inline]
Definition at line 617 of file regexp-compiler.h.
{ return &bmp_; }
References bmp_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddBmpCharacters().
lead_surrogates()
const CharacterRangeVector* v8::internal::UnicodeRangeSplitter::lead_surrogates () const [inline]
Definition at line 618 of file regexp-compiler.h.
                                                      {
    return &lead_surrogates_;
  }
References lead_surrogates_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddLoneLeadSurrogates().
non_bmp()
const CharacterRangeVector* v8::internal::UnicodeRangeSplitter::non_bmp () const [inline]
Definition at line 624 of file regexp-compiler.h.
{ return &non_bmp_; }
References non_bmp_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs().
trail_surrogates()
const CharacterRangeVector* v8::internal::UnicodeRangeSplitter::trail_surrogates () const [inline]
Definition at line 621 of file regexp-compiler.h.
                                                       {
    return &trail_surrogates_;
  }
References trail_surrogates_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddLoneTrailSurrogates().
Member Data Documentation
bmp_
CharacterRangeVector v8::internal::UnicodeRangeSplitter::bmp_ [private]
Definition at line 629 of file regexp-compiler.h.
Referenced by bmp().
kInitialSize
constexpr int v8::internal::UnicodeRangeSplitter::kInitialSize = 8 [static], [constexpr]
Definition at line 614 of file regexp-compiler.h.
lead_surrogates_
CharacterRangeVector v8::internal::UnicodeRangeSplitter::lead_surrogates_ [private]
Definition at line 630 of file regexp-compiler.h.
Referenced by lead_surrogates().
non_bmp_
CharacterRangeVector v8::internal::UnicodeRangeSplitter::non_bmp_ [private]
Definition at line 632 of file regexp-compiler.h.
Referenced by non_bmp().
trail_surrogates_
CharacterRangeVector v8::internal::UnicodeRangeSplitter::trail_surrogates_ [private]
Definition at line 631 of file regexp-compiler.h.
Referenced by trail_surrogates().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-compiler.h
/mnt/V8SourceCode/src/regexp/regexp-compiler-tonode.cc