v8::internal::StackFrameInfo Class Reference
#include <debug-objects.h>
Public Types
using BodyDescriptor = StructBodyDescriptor
Public Member Functions
Tagged< Script > script () const
Static Public Member Functions
static int GetSourcePosition (DirectHandle< StackFrameInfo > info)
Detailed Description
Definition at line 210 of file debug-objects.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::StackFrameInfo::BodyDescriptor = StructBodyDescriptor
Definition at line 230 of file debug-objects.h.
Member Function Documentation
GetSourcePosition()
int v8::internal::StackFrameInfo::GetSourcePosition (DirectHandle< StackFrameInfo > info) [static]
Definition at line 407 of file debug-objects.cc.
                                                                       {
  if (IsScript(info->shared_or_script())) {
    return info->bytecode_offset_or_source_position();
  }
  Isolate* isolate = Isolate::Current();
  DirectHandle<SharedFunctionInfo> shared(
      Cast<SharedFunctionInfo>(info->shared_or_script()), isolate);
  SharedFunctionInfo::EnsureSourcePositionsAvailable(isolate, shared);
  int source_position = shared->abstract_code(isolate)->SourcePosition(
      isolate, info->bytecode_offset_or_source_position());
  info->set_shared_or_script(Cast<Script>(shared->script()));
  info->set_bytecode_offset_or_source_position(source_position);
  return source_position;
}
References v8::internal::Isolate::Current(), and v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable().
Referenced by v8::internal::Isolate::ComputeLocationFromDetailedStackTrace(), v8::StackFrame::GetLocation(), and v8::StackFrame::GetSourcePosition().
script()
kBytecodeArrayIndirectPointerTag Tagged< Script > v8::internal::StackFrameInfo::script () const [inline]
Definition at line 68 of file debug-objects-inl.h.
                                            {
  Tagged<HeapObject> object = shared_or_script();
  if (IsSharedFunctionInfo(object)) {
    object = Cast<SharedFunctionInfo>(object)->script();
  }
  return Cast<Script>(object);
}
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/debug-objects.h
/mnt/V8SourceCode/src/objects/debug-objects-inl.h
/mnt/V8SourceCode/src/objects/debug-objects.cc