v8::internal::JSTemporalInstant Class Reference
#include <js-temporal-objects.h>
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalInstant > Constructor (Isolate *isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > epoch_nanoseconds)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalInstant > Now (Isolate *isolate)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalInstant > From (Isolate *isolate, DirectHandle< Object > item)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalInstant > Round (Isolate *isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > round_to)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Number > EpochMilliseconds (Isolate *isolate, DirectHandle< JSTemporalInstant > instant)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< BigInt > EpochNanoseconds (Isolate *isolate, DirectHandle< JSTemporalInstant > instant)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > ToZonedDateTime (Isolate *isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > item)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Oddball > Equals (Isolate *isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > other)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalInstant > Add (Isolate *isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > temporal_duration_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalInstant > Subtract (Isolate *isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > temporal_duration_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToJSON (Isolate *isolate, DirectHandle< JSTemporalInstant > instant)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToLocaleString (Isolate *isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > locales, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToString (Isolate *isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Until (Isolate *isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > other, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Since (Isolate *isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > other, DirectHandle< Object > options)
Detailed Description
Definition at line 166 of file js-temporal-objects.h.
Member Function Documentation
Add()
MaybeDirectHandle< JSTemporalInstant > v8::internal::JSTemporalInstant::Add (Isolate * isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > temporal_duration_like) [static]
Definition at line 3385 of file js-temporal-objects.cc.
                                                 {
  TEMPORAL_ENTER_FUNC();
  const char method_name[] = "Temporal.Duration.prototype.add";
  DirectHandle<JSTemporalDuration> other_duration;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, other_duration,
                             temporal::ToTemporalDuration(
                                 isolate, temporal_duration_like, method_name));
  auto added =
      handle->instant()->raw()->add(*other_duration->duration()->raw());
  return ConstructRustWrappingType<JSTemporalInstant>(
      isolate, CONSTRUCTOR(instant), CONSTRUCTOR(instant), std::move(added));
}
References ASSIGN_RETURN_ON_EXCEPTION, CONSTRUCTOR, v8::internal::handle(), TEMPORAL_ENTER_FUNC, and v8::internal::temporal::ToTemporalDuration().
Constructor()
MaybeDirectHandle< JSTemporalInstant > v8::internal::JSTemporalInstant::Constructor (Isolate * isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > epoch_nanoseconds) [static]
Definition at line 3125 of file js-temporal-objects.cc.
                                                {
  TEMPORAL_ENTER_FUNC();
  // 1. If NewTarget is undefined, then
  if (IsUndefined(*new_target)) {
    // a. Throw a TypeError exception.
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kMethodInvokedOnWrongType,
                                 isolate->factory()->NewStringFromAsciiChecked(
                                     "Temporal.Instant")));
  }
  // 2. Let epochNanoseconds be ? ToBigInt(epochNanoseconds).
  DirectHandle<BigInt> epoch_nanoseconds;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, epoch_nanoseconds,
      BigInt::FromObject(isolate, epoch_nanoseconds_obj));
  return temporal::CreateTemporalInstantWithValidityCheck(
      isolate, target, new_target, epoch_nanoseconds);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::temporal::CreateTemporalInstantWithValidityCheck(), v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), TEMPORAL_ENTER_FUNC, and THROW_NEW_ERROR.
EpochMilliseconds()
MaybeDirectHandle< Number > v8::internal::JSTemporalInstant::EpochMilliseconds (Isolate * isolate, DirectHandle< JSTemporalInstant > instant) [static]
Definition at line 3253 of file js-temporal-objects.cc.
                                                              {
  TEMPORAL_ENTER_FUNC();
  int64_t ms = handle->instant()->raw()->epoch_milliseconds();
  return isolate->factory()->NewNumberFromInt64(ms);
}
References v8::internal::Isolate::factory(), v8::internal::handle(), v8::internal::FactoryBase< Impl >::NewNumberFromInt64(), and TEMPORAL_ENTER_FUNC.
EpochNanoseconds()
MaybeDirectHandle< BigInt > v8::internal::JSTemporalInstant::EpochNanoseconds (Isolate * isolate, DirectHandle< JSTemporalInstant > instant) [static]
Definition at line 3262 of file js-temporal-objects.cc.
                                                              {
  TEMPORAL_ENTER_FUNC();
  temporal_rs::I128Nanoseconds ns =
      handle->instant()->raw()->epoch_nanoseconds();
  uint64_t words[2];
  bool sign_bit;
  if (ns.high < 0) {
    sign_bit = true;
    words[1] = static_cast<uint64_t>(-ns.high);
  } else {
    sign_bit = false;
    words[1] = static_cast<uint64_t>(ns.high);
  }
  words[0] = ns.low;
  return BigInt::FromWords64(isolate, sign_bit, 2, words);
}
References v8::internal::BigInt::FromWords64(), v8::internal::handle(), and TEMPORAL_ENTER_FUNC.
Equals()
MaybeDirectHandle< Oddball > v8::internal::JSTemporalInstant::Equals (Isolate * isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > other) [static]
Definition at line 3161 of file js-temporal-objects.cc.
                                    {
  TEMPORAL_ENTER_FUNC();
  const char method_name[] = "Temporal.Instant.prototype.equals";
  DirectHandle<JSTemporalInstant> other;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, other,
      temporal::ToTemporalInstant(isolate, other_obj, method_name));
  auto this_ns = handle->instant()->raw()->epoch_nanoseconds();
  auto other_ns = other->instant()->raw()->epoch_nanoseconds();
  // equals() isn't exposed over FFI, but it's easy enough to do here
  // in the future we can use https://github.com/boa-dev/temporal/pull/311
  return isolate->factory()->ToBoolean(this_ns.high == other_ns.high &&
                                       this_ns.low == other_ns.low);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::factory(), v8::internal::handle(), TEMPORAL_ENTER_FUNC, v8::internal::FactoryBase< Impl >::ToBoolean(), and v8::internal::temporal::ToTemporalInstant().
From()
MaybeDirectHandle< JSTemporalInstant > v8::internal::JSTemporalInstant::From (Isolate * isolate, DirectHandle< Object > item) [static]
Definition at line 3149 of file js-temporal-objects.cc.
                                                 {
  const char method_name[] = "Temporal.Instant.from";
  DirectHandle<JSTemporalInstant> item_instant;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, item_instant,
      temporal::ToTemporalInstant(isolate, item, method_name));
  return item_instant;
}
References ASSIGN_RETURN_ON_EXCEPTION, and v8::internal::temporal::ToTemporalInstant().
Now()
MaybeDirectHandle< JSTemporalInstant > v8::internal::JSTemporalInstant::Now (Isolate * isolate) [static]
Definition at line 3026 of file js-temporal-objects.cc.
                                                                            {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
Round()
MaybeDirectHandle< JSTemporalInstant > v8::internal::JSTemporalInstant::Round (Isolate * isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > round_to) [static]
Definition at line 3182 of file js-temporal-objects.cc.
                                       {
  TEMPORAL_ENTER_FUNC();
  const char method_name[] = "Temporal.Instant.prototype.round";
  Factory* factory = isolate->factory();
  // 1. Let instant be the this value.
  // 2. Perform ? RequireInternalSlot(instant, [[InitializedTemporalInstant]]).
  // 3. If roundTo is undefined, then
  if (IsUndefined(*round_to_obj)) {
    // a. Throw a TypeError exception.
    THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR());
  }
  DirectHandle<JSReceiver> round_to;
  // 4. If Type(roundTo) is String, then
  if (IsString(*round_to_obj)) {
    // TODO(415359720) This could be done more efficiently, if we had better
    // GetStringOption APIs
    // a. Let paramString be roundTo.
    DirectHandle<String> param_string = Cast<String>(round_to_obj);
    // b. Set roundTo to ! OrdinaryObjectCreate(null).
    round_to = factory->NewJSObjectWithNullProto();
    // c. Perform ! CreateDataPropertyOrThrow(roundTo, "smallestUnit",
    // paramString).
    CHECK(JSReceiver::CreateDataProperty(isolate, round_to,
                                         factory->smallestUnit_string(),
                                         param_string, Just(kThrowOnError))
              .FromJust());
  } else {
    // a. Set roundTo to ? GetOptionsObject(roundTo).
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, round_to,
        GetOptionsObject(isolate, round_to_obj, method_name));
  }
  // 7. Let roundingIncrement be ? GetRoundingIncrementOption(roundTo).
  uint32_t rounding_increment;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, rounding_increment,
      temporal::GetRoundingIncrementOption(isolate, round_to),
      DirectHandle<JSTemporalInstant>());
  // 8. Let roundingMode be ? GetRoundingModeOption(roundTo, half-expand).
  RoundingMode rounding_mode;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, rounding_mode,
      temporal::GetRoundingModeOption(isolate, round_to,
                                      RoundingMode::HalfExpand, method_name),
      DirectHandle<JSTemporalInstant>());
  // 9. Let smallestUnit be ? GetTemporalUnitValuedOption(roundTo,
  // "smallestUnit", time, required
  std::optional<Unit> smallest_unit;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, smallest_unit,
      temporal::GetTemporalUnit(isolate, round_to, "smallestUnit",
                                UnitGroup::kTime, std::nullopt, true,
                                method_name),
      DirectHandle<JSTemporalInstant>());
  auto options = temporal_rs::RoundingOptions{.largest_unit = std::nullopt,
                                              .smallest_unit = smallest_unit,
                                              .rounding_mode = rounding_mode,
                                              .increment = rounding_increment};
  auto rounded = handle->instant()->raw()->round(options);
  return ConstructRustWrappingType<JSTemporalInstant>(
      isolate, CONSTRUCTOR(instant), CONSTRUCTOR(instant), std::move(rounded));
}
References ASSIGN_RETURN_ON_EXCEPTION, CHECK, CONSTRUCTOR, v8::internal::JSReceiver::CreateDataProperty(), v8::internal::Isolate::factory(), v8::internal::GetOptionsObject(), v8::internal::temporal::GetRoundingIncrementOption(), v8::internal::temporal::GetRoundingModeOption(), v8::internal::temporal::GetTemporalUnit(), v8::internal::handle(), v8::Just(), v8::internal::kThrowOnError, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR, v8::internal::Factory::NewJSObjectWithNullProto(), TEMPORAL_ENTER_FUNC, and THROW_NEW_ERROR.
Since()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalInstant::Since (Isolate * isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > other, DirectHandle< Object > options) [static]
Definition at line 3437 of file js-temporal-objects.cc.
                                                                  {
  TEMPORAL_ENTER_FUNC();
  const char method_name[] = "Temporal.Instant.prototype.since";
  return temporal::DifferenceTemporalInstant(
      isolate, temporal::DifferenceOperation::kSince, handle, other_obj,
      options, method_name);
}
References v8::internal::temporal::DifferenceTemporalInstant(), v8::internal::handle(), v8::internal::temporal::kSince, and TEMPORAL_ENTER_FUNC.
Subtract()
MaybeDirectHandle< JSTemporalInstant > v8::internal::JSTemporalInstant::Subtract (Isolate * isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > temporal_duration_like) [static]
Definition at line 3404 of file js-temporal-objects.cc.
                                                 {
  TEMPORAL_ENTER_FUNC();
  const char method_name[] = "Temporal.Duration.prototype.subtract";
  DirectHandle<JSTemporalDuration> other_duration;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, other_duration,
                             temporal::ToTemporalDuration(
                                 isolate, temporal_duration_like, method_name));
  auto subtracted =
      handle->instant()->raw()->subtract(*other_duration->duration()->raw());
  return ConstructRustWrappingType<JSTemporalInstant>(
      isolate, CONSTRUCTOR(instant), CONSTRUCTOR(instant),
      std::move(subtracted));
}
References ASSIGN_RETURN_ON_EXCEPTION, CONSTRUCTOR, v8::internal::handle(), TEMPORAL_ENTER_FUNC, and v8::internal::temporal::ToTemporalDuration().
ToJSON()
MaybeDirectHandle< String > v8::internal::JSTemporalInstant::ToJSON (Isolate * isolate, DirectHandle< JSTemporalInstant > instant) [static]
Definition at line 3291 of file js-temporal-objects.cc.
                                                               {
  TEMPORAL_ENTER_FUNC();
  return temporal::TemporalInstantToString(isolate, instant, nullptr,
                                           std::move(temporal::kToStringAuto));
}
References v8::internal::temporal::kToStringAuto, TEMPORAL_ENTER_FUNC, and v8::internal::temporal::TemporalInstantToString().
ToLocaleString()
MaybeDirectHandle< String > v8::internal::JSTemporalInstant::ToLocaleString (Isolate * isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > locales, DirectHandle< Object > options) [static]
Definition at line 3300 of file js-temporal-objects.cc.
                                                                {
  return temporal::TemporalInstantToString(isolate, instant, nullptr,
                                           std::move(temporal::kToStringAuto));
}
References v8::internal::temporal::kToStringAuto, and v8::internal::temporal::TemporalInstantToString().
ToString()
MaybeDirectHandle< String > v8::internal::JSTemporalInstant::ToString (Isolate * isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > options) [static]
Definition at line 3308 of file js-temporal-objects.cc.
                                      {
  const char method_name[] = "Temporal.Instant.prototype.toString";
  // 3. Set options to ? GetOptionsObject(options).
  DirectHandle<JSReceiver> options;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, options, GetOptionsObject(isolate, options_obj, method_name));
  // 5. Let digits be ?
  // GetTemporalFractionalSecondDigitsOption(resolvedOptions).
  temporal_rs::Precision digits;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, digits,
      temporal::GetTemporalFractionalSecondDigitsOption(isolate, options,
                                                        method_name),
      DirectHandle<String>());
  // 6. Let roundingMode be ? GetRoundingModeOption(resolvedOptions, trunc).
  RoundingMode rounding_mode;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, rounding_mode,
      temporal::GetRoundingModeOption(isolate, options, RoundingMode::Trunc,
                                      method_name),
      DirectHandle<String>());
  // 7. Let smallestUnit be ? GetTemporalUnitValuedOption(resolvedOptions,
  // "smallestUnit", time, unset).
  std::optional<Unit> smallest_unit;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, smallest_unit,
      temporal::GetTemporalUnit(isolate, options, "smallestUnit",
                                UnitGroup::kTime, std::nullopt, false,
                                method_name),
      DirectHandle<String>());
  // 8. If smallestUnit is hour, throw a RangeError exception.
  if (smallest_unit == Unit::Hour) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewRangeError(MessageTemplate::kPropertyValueOutOfRange,
                      isolate->factory()->smallestUnit_string()),
        DirectHandle<String>());
  }
  // 9. Let timeZone be ? Get(resolvedOptions, "timeZone").
  DirectHandle<Object> time_zone;
  // Let val be ? Get(temporalDurationLike, fieldName).
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, time_zone,
      JSReceiver::GetProperty(isolate, options,
                              isolate->factory()->timeZone_string()),
      DirectHandle<String>());
  std::unique_ptr<temporal_rs::TimeZone> rust_time_zone;
  // 10. If timeZone is not undefined, then
  if (!IsUndefined(*time_zone)) {
    // a. Set timeZone to ? ToTemporalTimeZoneIdentifier(timeZone).
    MAYBE_MOVE_RETURN_ON_EXCEPTION_VALUE(
        isolate, rust_time_zone,
        temporal::ToTemporalTimeZoneIdentifier(isolate, time_zone),
        DirectHandle<String>());
  }
  auto rust_options = temporal_rs::ToStringRoundingOptions{
      .precision = digits,
      .smallest_unit = smallest_unit,
      .rounding_mode = rounding_mode,
  };
  return temporal::TemporalInstantToString(
      isolate, instant, rust_time_zone.get(), std::move(rust_options));
}
References ASSIGN_RETURN_ON_EXCEPTION, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Isolate::factory(), v8::internal::GetOptionsObject(), v8::internal::JSReceiver::GetProperty(), v8::internal::temporal::GetRoundingModeOption(), v8::internal::temporal::GetTemporalFractionalSecondDigitsOption(), v8::internal::temporal::GetTemporalUnit(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, MAYBE_MOVE_RETURN_ON_EXCEPTION_VALUE, v8::internal::temporal::TemporalInstantToString(), THROW_NEW_ERROR_RETURN_VALUE, and v8::internal::temporal::ToTemporalTimeZoneIdentifier().
ToZonedDateTime()
MaybeDirectHandle< JSTemporalZonedDateTime > v8::internal::JSTemporalInstant::ToZonedDateTime (Isolate * isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > item) [static]
Definition at line 3281 of file js-temporal-objects.cc.
                                   {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
Until()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalInstant::Until (Isolate * isolate, DirectHandle< JSTemporalInstant > instant, DirectHandle< Object > other, DirectHandle< Object > options) [static]
Definition at line 3425 of file js-temporal-objects.cc.
                                                                  {
  TEMPORAL_ENTER_FUNC();
  const char method_name[] = "Temporal.Instant.prototype.until";
  return temporal::DifferenceTemporalInstant(
      isolate, temporal::DifferenceOperation::kUntil, handle, other_obj,
      options, method_name);
}
References v8::internal::temporal::DifferenceTemporalInstant(), v8::internal::handle(), v8::internal::temporal::kUntil, and TEMPORAL_ENTER_FUNC.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-temporal-objects.h
/mnt/V8SourceCode/src/objects/js-temporal-objects.cc