cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor Class Reference
Public Member Functions
PrepareForSweepVisitor (HeapBase *heap, SpaceStates *space_states, SweepingState *empty_normal_pages, SweepingState *empty_large_pages, CompactableSpaceHandling compactable_space_handling)
void Run (RawHeap &raw_heap)
Protected Member Functions
bool VisitNormalPageSpace (NormalPageSpace &space)
bool VisitLargePageSpace (LargePageSpace &space)
Private Types
using CompactableSpaceHandling = SweepingConfig::CompactableSpaceHandling
Private Attributes
HeapBase *const heap_
SpaceStates *const space_states_
SweepingState *const empty_normal_pages_
SweepingState *const empty_large_pages_
CompactableSpaceHandling compactable_space_handling_
Friends
class HeapVisitor< PrepareForSweepVisitor >
Detailed Description
Definition at line 878 of file sweeper.cc.
Member Typedef Documentation
CompactableSpaceHandling
using cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::CompactableSpaceHandling = SweepingConfig::CompactableSpaceHandling [private]
Definition at line 881 of file sweeper.cc.
Constructor & Destructor Documentation
PrepareForSweepVisitor()
cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::PrepareForSweepVisitor (HeapBase * heap, SpaceStates * space_states, SweepingState * empty_normal_pages, SweepingState * empty_large_pages, CompactableSpaceHandling compactable_space_handling) [inline]
Definition at line 884 of file sweeper.cc.
      : heap_(heap),
        space_states_(space_states),
        empty_normal_pages_(empty_normal_pages),
        empty_large_pages_(empty_large_pages),
        compactable_space_handling_(compactable_space_handling) {}
Member Function Documentation
Run()
void cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::Run (RawHeap & raw_heap) [inline]
Definition at line 894 of file sweeper.cc.
                              {
    *space_states_ = SpaceStates(raw_heap.size());
    Traverse(raw_heap);
  }
References cppgc::internal::RawHeap::size().
VisitLargePageSpace()
bool cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::VisitLargePageSpace (LargePageSpace & space) [inline], [protected]
Definition at line 928 of file sweeper.cc.
                                                  {
#ifdef V8_USE_ADDRESS_SANITIZER
    UnmarkedObjectsPoisoner().Traverse(space);
#endif // V8_USE_ADDRESS_SANITIZER
    BaseSpace::Pages space_pages = space.RemoveAllPages();
    for (BasePage* page : space_pages) {
#ifdef DEBUG
      const auto* header = LargePage::From(page)->ObjectHeader();
      DCHECK_IMPLIES(page->marked_bytes() == 0, !header->IsMarked());
      DCHECK_IMPLIES(page->marked_bytes() != 0, header->IsMarked());
#endif // DEBUG
      if (page->marked_bytes() != 0) {
        MutatorThreadSweeper::SweepLiveLargePage(*LargePage::From(page),
                                                 heap_->sticky_bits());
      } else {
        empty_large_pages_->unswept_pages.Push(page);
      }
    }
    return true;
  }
References DCHECK_IMPLIES, cppgc::internal::LargePage::From(), cppgc::internal::LargePage::ObjectHeader(), and space.
VisitNormalPageSpace()
bool cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::VisitNormalPageSpace (NormalPageSpace & space) [inline], [protected]
Definition at line 900 of file sweeper.cc.
                                                    {
    if ((compactable_space_handling_ == CompactableSpaceHandling::kIgnore) &&
        space.is_compactable()) {
      return true;
    }
    CHECK(!space.linear_allocation_buffer().size());
    space.free_list().Clear();
#ifdef V8_USE_ADDRESS_SANITIZER
    UnmarkedObjectsPoisoner().Traverse(space);
#endif // V8_USE_ADDRESS_SANITIZER
    BaseSpace::Pages space_pages = space.RemoveAllPages();
    std::sort(space_pages.begin(), space_pages.end(),
              [](const BasePage* a, const BasePage* b) {
                return a->marked_bytes() < b->marked_bytes();
              });
    auto first_non_empty_page = std::find_if(
        space_pages.begin(), space_pages.end(),
        [](const BasePage* page) { return page->marked_bytes() != 0; });
    empty_normal_pages_->unswept_pages.Insert(space_pages.begin(),
                                              first_non_empty_page);
    (*space_states_)[space.index()].unswept_pages.Insert(first_non_empty_page,
                                                         space_pages.end());
    return true;
  }
References CHECK, v8::base::sort(), and space.
Friends And Related Function Documentation
HeapVisitor< PrepareForSweepVisitor >
friend class HeapVisitor< PrepareForSweepVisitor > [friend]
Definition at line 864 of file sweeper.cc.
Member Data Documentation
compactable_space_handling_
CompactableSpaceHandling cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::compactable_space_handling_ [private]
Definition at line 956 of file sweeper.cc.
empty_large_pages_
SweepingState* const cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::empty_large_pages_ [private]
Definition at line 955 of file sweeper.cc.
empty_normal_pages_
SweepingState* const cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::empty_normal_pages_ [private]
Definition at line 954 of file sweeper.cc.
heap_
HeapBase* const cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::heap_ [private]
Definition at line 952 of file sweeper.cc.
space_states_
SpaceStates* const cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::space_states_ [private]
Definition at line 953 of file sweeper.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/sweeper.cc