v8::internal::compiler::ScheduleVerifier Class Reference
#include <verifier.h>
Static Public Member Functions
static void Run (Schedule *schedule)
Detailed Description
Definition at line 61 of file verifier.h.
Member Function Documentation
Run()
void v8::internal::compiler::ScheduleVerifier::Run (Schedule * schedule) [static]
Definition at line 2182 of file verifier.cc.
                                             {
  const size_t count = schedule->BasicBlockCount();
  Zone tmp_zone(schedule->zone()->allocator(), ZONE_NAME);
  Zone* zone = &tmp_zone;
  BasicBlock* start = schedule->start();
  BasicBlockVector* rpo_order = schedule->rpo_order();
  // Verify the RPO order contains only blocks from this schedule.
  CHECK_GE(count, rpo_order->size());
  for (BasicBlockVector::iterator b = rpo_order->begin(); b != rpo_order->end();
       ++b) {
    CHECK_EQ((*b), schedule->GetBlockById((*b)->id()));
    // All predecessors and successors should be in rpo and in this schedule.
    for (BasicBlock const* predecessor : (*b)->predecessors()) {
      CHECK_GE(predecessor->rpo_number(), 0);
      CHECK_EQ(predecessor, schedule->GetBlockById(predecessor->id()));
    }
    for (BasicBlock const* successor : (*b)->successors()) {
      CHECK_GE(successor->rpo_number(), 0);
      CHECK_EQ(successor, schedule->GetBlockById(successor->id()));
    }
  }
  // Verify RPO numbers of blocks.
  CHECK_EQ(start, rpo_order->at(0)); // Start should be first.
  for (size_t b = 0; b < rpo_order->size(); b++) {
    BasicBlock* block = rpo_order->at(b);
    CHECK_EQ(static_cast<int>(b), block->rpo_number());
    BasicBlock* dom = block->dominator();
    if (b == 0) {
      // All blocks except start should have a dominator.
      CHECK_NULL(dom);
    } else {
      // Check that the immediate dominator appears somewhere before the block.
      CHECK_NOT_NULL(dom);
      CHECK_LT(dom->rpo_number(), block->rpo_number());
    }
  }
  // Verify that all blocks reachable from start are in the RPO.
  BitVector marked(static_cast<int>(count), zone);
  {
    ZoneQueue<BasicBlock*> queue(zone);
    queue.push(start);
    marked.Add(start->id().ToInt());
    while (!queue.empty()) {
      BasicBlock* block = queue.front();
      queue.pop();
      for (size_t s = 0; s < block->SuccessorCount(); s++) {
        BasicBlock* succ = block->SuccessorAt(s);
        if (!marked.Contains(succ->id().ToInt())) {
          marked.Add(succ->id().ToInt());
          queue.push(succ);
        }
      }
    }
  }
  // Verify marked blocks are in the RPO.
  for (int i = 0; i < static_cast<int>(count); i++) {
    BasicBlock* block = schedule->GetBlockById(BasicBlock::Id::FromInt(i));
    if (marked.Contains(i)) {
      CHECK_GE(block->rpo_number(), 0);
      CHECK_EQ(block, rpo_order->at(block->rpo_number()));
    }
  }
  // Verify RPO blocks are marked.
  for (size_t b = 0; b < rpo_order->size(); b++) {
    CHECK(marked.Contains(rpo_order->at(b)->id().ToInt()));
  }
  {
    // Verify the dominance relation.
    ZoneVector<BitVector*> dominators(zone);
    dominators.resize(count, nullptr);
    // Compute a set of all the nodes that dominate a given node by using
    // a forward fixpoint. O(n^2).
    ZoneQueue<BasicBlock*> queue(zone);
    queue.push(start);
    dominators[start->id().ToSize()] =
        zone->New<BitVector>(static_cast<int>(count), zone);
    while (!queue.empty()) {
      BasicBlock* block = queue.front();
      queue.pop();
      BitVector* block_doms = dominators[block->id().ToSize()];
      BasicBlock* idom = block->dominator();
      if (idom != nullptr && !block_doms->Contains(idom->id().ToInt())) {
        FATAL("Block B%d is not dominated by B%d", block->rpo_number(),
              idom->rpo_number());
      }
      for (size_t s = 0; s < block->SuccessorCount(); s++) {
        BasicBlock* succ = block->SuccessorAt(s);
        BitVector* succ_doms = dominators[succ->id().ToSize()];
        if (succ_doms == nullptr) {
          // First time visiting the node. S.doms = B U B.doms
          succ_doms = zone->New<BitVector>(static_cast<int>(count), zone);
          succ_doms->CopyFrom(*block_doms);
          succ_doms->Add(block->id().ToInt());
          dominators[succ->id().ToSize()] = succ_doms;
          queue.push(succ);
        } else {
          // Nth time visiting the successor. S.doms = S.doms ^ (B U B.doms)
          bool had = succ_doms->Contains(block->id().ToInt());
          if (had) succ_doms->Remove(block->id().ToInt());
          if (succ_doms->IntersectIsChanged(*block_doms)) queue.push(succ);
          if (had) succ_doms->Add(block->id().ToInt());
        }
      }
    }
    // Verify the immediateness of dominators.
    for (BasicBlockVector::iterator b = rpo_order->begin();
         b != rpo_order->end(); ++b) {
      BasicBlock* block = *b;
      BasicBlock* idom = block->dominator();
      if (idom == nullptr) continue;
      BitVector* block_doms = dominators[block->id().ToSize()];
      for (int id : *block_doms) {
        BasicBlock* dom = schedule->GetBlockById(BasicBlock::Id::FromInt(id));
        if (dom != idom &&
            !dominators[idom->id().ToSize()]->Contains(dom->id().ToInt())) {
          FATAL("Block B%d is not immediately dominated by B%d",
                block->rpo_number(), idom->rpo_number());
        }
      }
    }
  }
  // Verify phis are placed in the block of their control input.
  for (BasicBlockVector::iterator b = rpo_order->begin(); b != rpo_order->end();
       ++b) {
    for (BasicBlock::const_iterator i = (*b)->begin(); i != (*b)->end(); ++i) {
      Node* phi = *i;
      if (phi->opcode() != IrOpcode::kPhi) continue;
      // TODO(titzer): Nasty special case. Phis from RawMachineAssembler
      // schedules don't have control inputs.
      if (phi->InputCount() > phi->op()->ValueInputCount()) {
        Node* control = NodeProperties::GetControlInput(phi);
        CHECK(control->opcode() == IrOpcode::kMerge ||
              control->opcode() == IrOpcode::kLoop);
        CHECK_EQ((*b), schedule->block(control));
      }
    }
  }
  // Verify that all uses are dominated by their definitions.
  for (BasicBlockVector::iterator b = rpo_order->begin(); b != rpo_order->end();
       ++b) {
    BasicBlock* block = *b;
    // Check inputs to control for this block.
    Node* control = block->control_input();
    if (control != nullptr) {
      CHECK_EQ(block, schedule->block(control));
      CheckInputsDominate(schedule, block, control,
                          static_cast<int>(block->NodeCount()) - 1);
    }
    // Check inputs for all nodes in the block.
    for (size_t i = 0; i < block->NodeCount(); i++) {
      Node* node = block->NodeAt(i);
      CheckInputsDominate(schedule, block, node, static_cast<int>(i) - 1);
    }
  }
}
References v8::internal::BitVector::Add(), v8::internal::Zone::allocator(), v8::internal::ZoneVector< T >::at(), v8::internal::compiler::Schedule::BasicBlockCount(), v8::internal::ZoneVector< T >::begin(), v8::internal::compiler::Schedule::block(), CHECK, CHECK_EQ, CHECK_GE, CHECK_LT, CHECK_NOT_NULL, CHECK_NULL, v8::internal::compiler::CheckInputsDominate(), v8::internal::BitVector::Contains(), v8::internal::compiler::BasicBlock::control_input(), v8::internal::BitVector::CopyFrom(), v8::internal::compiler::BasicBlock::dominator(), v8::internal::ZoneVector< T >::end(), FATAL, v8::internal::compiler::BasicBlock::Id::FromInt(), v8::internal::compiler::Schedule::GetBlockById(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::BasicBlock::id(), v8::internal::compiler::Node::InputCount(), v8::internal::BitVector::IntersectIsChanged(), v8::internal::Zone::New(), v8::internal::compiler::BasicBlock::NodeAt(), v8::internal::compiler::BasicBlock::NodeCount(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::BasicBlock::predecessors(), v8::internal::BitVector::Remove(), v8::internal::ZoneVector< T >::resize(), v8::internal::compiler::BasicBlock::rpo_number(), v8::internal::compiler::Schedule::rpo_order(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::Schedule::start(), v8::internal::compiler::BasicBlock::SuccessorAt(), v8::internal::compiler::BasicBlock::SuccessorCount(), v8::internal::compiler::BasicBlock::successors(), v8::internal::compiler::BasicBlock::Id::ToInt(), v8::internal::compiler::BasicBlock::Id::ToSize(), v8::internal::compiler::Operator::ValueInputCount(), v8::internal::compiler::Schedule::zone(), and ZONE_NAME.
Referenced by v8::internal::compiler::anonymous_namespace{pipeline.cc}::TraceScheduleAndVerify().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/verifier.h
/mnt/V8SourceCode/src/compiler/verifier.cc