v8::OnMessageFromWorkerTask Class Reference
Public Member Functions
OnMessageFromWorkerTask (v8::Isolate *isolate, v8::Local< v8::Context > context, v8::Local< v8::Value > callback, std::unique_ptr< SerializationData > data)
void Run () override
Private Attributes
v8::Isolate * isolate_
v8::Global< v8::Context > context_
v8::Global< v8::Value > callback_
std::unique_ptr< SerializationData > data_
Detailed Description
Definition at line 3456 of file d8.cc.
Constructor & Destructor Documentation
OnMessageFromWorkerTask()
v8::OnMessageFromWorkerTask::OnMessageFromWorkerTask (v8::Isolate * isolate, v8::Local< v8::Context > context, v8::Local< v8::Value > callback, std::unique_ptr< SerializationData > data) [inline]
Definition at line 3458 of file d8.cc.
      : isolate_(isolate),
        context_(isolate, context),
        callback_(isolate, callback),
        data_(std::move(data)) {}
Member Function Documentation
Run()
void v8::OnMessageFromWorkerTask::Run () [inline], [override], [virtual]
Implements v8::Task.
Definition at line 3466 of file d8.cc.
                      {
    HandleScope scope(isolate_);
    Local<Context> context = context_.Get(isolate_);
    Context::Scope context_scope(context);
    MicrotasksScope microtasks_scope(context,
                                     MicrotasksScope::kDoNotRunMicrotasks);
    Local<Object> global = context->Global();
    // Get the message handler.
    Local<Value> onmessage = callback_.Get(isolate_);
    if (!onmessage->IsFunction()) return;
    Local<Function> onmessage_fun = onmessage.As<Function>();
    v8::TryCatch try_catch(isolate_);
    try_catch.SetVerbose(true);
    Local<Value> value;
    if (Shell::DeserializeValue(isolate_, std::move(data_)).ToLocal(&value)) {
      DCHECK(!isolate_->IsExecutionTerminating());
      Local<Object> event = v8::Object::New(isolate_);
      event
          ->CreateDataProperty(
              context,
              String::NewFromUtf8Literal(isolate_, "data",
                                         NewStringType::kInternalized),
              value)
          .ToChecked();
      Local<Value> argv[] = {event};
      MaybeLocal<Value> result = onmessage_fun->Call(context, global, 1, argv);
      USE(result);
    }
  }
References v8::Local< T >::As(), DCHECK, v8::Shell::DeserializeValue(), v8::Context::Global(), v8::Isolate::IsExecutionTerminating(), v8::PerIsolateData::isolate_, v8::MicrotasksScope::kDoNotRunMicrotasks, v8::kInternalized, v8::Object::New(), v8::String::NewFromUtf8Literal(), v8::base::internal::result, USE, and v8::internal::value.
Member Data Documentation
callback_
v8::Global<v8::Value> v8::OnMessageFromWorkerTask::callback_ [private]
Definition at line 3502 of file d8.cc.
context_
v8::Global<v8::Context> v8::OnMessageFromWorkerTask::context_ [private]
Definition at line 3501 of file d8.cc.
data_
std::unique_ptr<SerializationData> v8::OnMessageFromWorkerTask::data_ [private]
Definition at line 3503 of file d8.cc.
isolate_
v8::Isolate* v8::OnMessageFromWorkerTask::isolate_ [private]
Definition at line 3500 of file d8.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/d8/d8.cc