v8::CTypeInfo Class Reference
#include <v8-fast-api-calls.h>
Public Types
enum class Type : uint8_t {
kVoid
, kBool
, kUint8
, kInt32
,
kUint32
, kInt64
, kUint64
, kFloat32
,
kFloat64
, kPointer
, kV8Value
, kSeqOneByteString
,
kApiObject
, kAny
 }
enum class Flags : uint8_t {
kNone = 0
, kAllowSharedBit = 1 << 0
, kEnforceRangeBit = 1 << 1
, kClampBit = 1 << 2
,
kIsRestrictedBit = 1 << 3
 }
Public Member Functions
constexpr CTypeInfo (Type type, Flags flags=Flags::kNone)
Use CTypeInfo (Type, Flags) instead`) const expr CTypeInfo(Type type
constexpr CTypeInfo (Identifier identifier)
constexpr Identifier GetId () const
constexpr Type GetType () const
Use the constant SequenceType::kScalar constexpr instead SequenceType GetSequenceType () const
constexpr Flags GetFlags () const
Static Public Member Functions
static constexpr bool IsIntegralType (Type type)
static constexpr bool IsFloatingPointType (Type type)
static constexpr bool IsPrimitive (Type type)
Public Attributes
enum There is no special support in V8 anymore there is no need to use a SequenceType SequenceType: uint8_t { kScalar
enum There is no special support in V8 anymore there is no need to use a SequenceType kIsSequence
enum There is no special support in V8 anymore there is no need to use a SequenceType kIsArrayBuffer
Use SequenceType sequence_type
Use SequenceType Flags flags
Static Public Attributes
static constexpr Type kCallbackOptionsType = Type(255)
Private Attributes
Type type_
SequenceType sequence_type_
Flags flags_
Detailed Description
Definition at line 239 of file v8-fast-api-calls.h.
Member Enumeration Documentation
Flags
enum v8::CTypeInfo::Flags : uint8_t [strong]
Enumerator
kNone
kAllowSharedBit
kEnforceRangeBit
kClampBit
kIsRestrictedBit
Definition at line 280 of file v8-fast-api-calls.h.
                   : uint8_t {
    kNone = 0,
    kAllowSharedBit = 1 << 0, // Must be an ArrayBuffer or TypedArray
    kEnforceRangeBit = 1 << 1, // T must be integral
    kClampBit = 1 << 2, // T must be integral
    kIsRestrictedBit = 1 << 3, // T must be float or double
  };
Type
enum v8::CTypeInfo::Type : uint8_t [strong]
Enumerator
kVoid
kBool
kUint8
kInt32
kUint32
kInt64
kUint64
kFloat32
kFloat64
kPointer
kV8Value
kSeqOneByteString
kApiObject
kAny
Definition at line 241 of file v8-fast-api-calls.h.
                  : uint8_t {
    kVoid,
    kBool,
    kUint8,
    kInt32,
    kUint32,
    kInt64,
    kUint64,
    kFloat32,
    kFloat64,
    kPointer,
    kV8Value,
    kSeqOneByteString,
    kApiObject, // This will be deprecated once all users have
                 // migrated from v8::ApiObject to v8::Local<v8::Value>.
    kAny, // This is added to enable untyped representation of fast
                 // call arguments for test purposes. It can represent any of
                 // the other types stored in the same memory as a union
                 // (see AnyCType declared below). This allows for
                 // uniform passing of arguments w.r.t. their location
                 // (in a register or on the stack), independent of their
                 // actual type. It's currently used by the arm64 simulator
                 // and can be added to the other simulators as well when fast
                 // calls having both GP and FP params need to be supported.
  };
Constructor & Destructor Documentation
CTypeInfo() [1/3]
constexpr v8::CTypeInfo::CTypeInfo (Type type, Flags flags = Flags::kNone) [inline], [explicit], [constexpr]
Definition at line 288 of file v8-fast-api-calls.h.
      : type_(type), sequence_type_(SequenceType::kScalar), flags_(flags) {}
CTypeInfo() [2/3]
Use v8::CTypeInfo::CTypeInfo (Type , Flags) const
CTypeInfo() [3/3]
constexpr v8::CTypeInfo::CTypeInfo (Identifier identifier) [inline], [explicit], [constexpr]
Definition at line 297 of file v8-fast-api-calls.h.
      : CTypeInfo(static_cast<Type>(identifier >> 16),
                  static_cast<SequenceType>((identifier >> 8) & 255),
                  static_cast<Flags>(identifier & 255)) {}
Member Function Documentation
GetFlags()
constexpr Flags v8::CTypeInfo::GetFlags () const [inline], [constexpr]
Definition at line 310 of file v8-fast-api-calls.h.
{ return flags_; }
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::AdaptFastCallArgument(), v8::internal::compiler::turboshaft::FastApiCallOp::argument_representation(), v8::internal::compiler::fast_api_call::CanOptimizeFastSignature(), and v8::internal::compiler::fast_api_call::GetFastApiCallTarget().
GetId()
constexpr Identifier v8::CTypeInfo::GetId () const [inline], [constexpr]
Definition at line 301 of file v8-fast-api-calls.h.
                                     {
    return static_cast<uint8_t>(type_) << 16 |
           static_cast<uint8_t>(sequence_type_) << 8 |
           static_cast<uint8_t>(flags_);
  }
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceFastCallback().
GetSequenceType()
Use the constant SequenceType::kScalar constexpr instead SequenceType v8::CTypeInfo::GetSequenceType () const [inline], [constexpr]
Definition at line 309 of file v8-fast-api-calls.h.
{ return sequence_type_; }
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::AdaptFastCallArgument(), v8::internal::compiler::turboshaft::FastApiCallOp::argument_representation(), and v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsSupportedWasmFastApiFunction().
GetType()
constexpr Type v8::CTypeInfo::GetType () const [inline], [constexpr]
Definition at line 307 of file v8-fast-api-calls.h.
{ return type_; }
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::AdaptFastCallArgument(), v8::internal::compiler::turboshaft::FastApiCallOp::argument_representation(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildJSFastApiCallWrapper(), v8::internal::compiler::fast_api_call::CanOptimizeFastSignature(), v8::internal::CFunctionInfoImpl< Representation, RetBuilder, ArgBuilders >::CFunctionInfoImpl(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CompareWithNormalizedCType(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::ConvertReturnValue(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::DefaultReturnValue(), v8::internal::compiler::turboshaft::RegisterRepresentation::FromCTypeInfo(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::GetFunctionSigForFastApiImport(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsSupportedWasmFastApiFunction(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), and v8::internal::compiler::RepresentationSelector::VisitFastApiCall().
IsFloatingPointType()
static constexpr bool v8::CTypeInfo::IsFloatingPointType (Type type) [inline], [static], [constexpr]
Definition at line 318 of file v8-fast-api-calls.h.
                                                       {
    return type == Type::kFloat32 || type == Type::kFloat64;
  }
References v8::internal::tracing::type.
Referenced by v8::CTypeInfoBuilder< T, Flags >::Build(), and v8::internal::EncodedCSignature::EncodedCSignature().
IsIntegralType()
static constexpr bool v8::CTypeInfo::IsIntegralType (Type type) [inline], [static], [constexpr]
Definition at line 312 of file v8-fast-api-calls.h.
                                                  {
    return type == Type::kUint8 || type == Type::kInt32 ||
           type == Type::kUint32 || type == Type::kInt64 ||
           type == Type::kUint64;
  }
References v8::internal::tracing::type.
Referenced by v8::CTypeInfoBuilder< T, Flags >::Build().
IsPrimitive()
static constexpr bool v8::CTypeInfo::IsPrimitive (Type type) [inline], [static], [constexpr]
Definition at line 322 of file v8-fast-api-calls.h.
                                               {
    return IsIntegralType(type) || IsFloatingPointType(type) ||
           type == Type::kBool;
  }
References v8::internal::tracing::type.
Member Data Documentation
flags
Use SequenceType Flags v8::CTypeInfo::flags
Initial value:
= Flags::kNone)
      : type_(type), sequence_type_(sequence_type), flags_(flags) {}
  typedef uint32_t Identifier
Definition at line 293 of file v8-fast-api-calls.h.
flags_
Flags v8::CTypeInfo::flags_ [private]
Definition at line 330 of file v8-fast-api-calls.h.
kCallbackOptionsType
constexpr Type v8::CTypeInfo::kCallbackOptionsType = Type(255) [static], [constexpr]
Definition at line 270 of file v8-fast-api-calls.h.
Referenced by v8::CFunctionInfo::CFunctionInfo(), v8::CFunctionInfo::HasOptions(), and v8::internal::TypeInfoHelper< FastApiCallbackOptions & >::Type().
kIsArrayBuffer
enum There is no special support in V8 anymore there is no need to use a SequenceType v8::CTypeInfo::kIsArrayBuffer
Definition at line 277 of file v8-fast-api-calls.h.
kIsSequence
enum There is no special support in V8 anymore there is no need to use a SequenceType v8::CTypeInfo::kIsSequence
Definition at line 276 of file v8-fast-api-calls.h.
sequence_type
Use SequenceType v8::CTypeInfo::sequence_type
Definition at line 292 of file v8-fast-api-calls.h.
sequence_type_
SequenceType v8::CTypeInfo::sequence_type_ [private]
Definition at line 329 of file v8-fast-api-calls.h.
SequenceType
enum There is no special support in V8 anymore there is no need to use a SequenceType v8::CTypeInfo::SequenceType [strong]
Definition at line 270 of file v8-fast-api-calls.h.
type_
Type v8::CTypeInfo::type_ [private]
Definition at line 328 of file v8-fast-api-calls.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-fast-api-calls.h