v8::internal::ArrayPopulatorAssembler Class Reference
Public Member Functions
ArrayPopulatorAssembler (compiler::CodeAssemblerState *state)
TNode< Object > ConstructArrayLike (TNode< Context > context, TNode< Object > receiver)
TNode< Object > ConstructArrayLike (TNode< Context > context, TNode< Object > receiver, TNode< Number > length)
Additional Inherited Members
Detailed Description
Definition at line 594 of file builtins-array-gen.cc.
Constructor & Destructor Documentation
ArrayPopulatorAssembler()
v8::internal::ArrayPopulatorAssembler::ArrayPopulatorAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 596 of file builtins-array-gen.cc.
      : CodeStubAssembler(state) {}
Member Function Documentation
ConstructArrayLike() [1/2]
TNode<Object> v8::internal::ArrayPopulatorAssembler::ConstructArrayLike (TNode< Context > context, TNode< Object > receiver) [inline]
Definition at line 599 of file builtins-array-gen.cc.
                                                           {
    TVARIABLE(Object, array);
    Label is_constructor(this), is_not_constructor(this), done(this);
    GotoIf(TaggedIsSmi(receiver), &is_not_constructor);
    Branch(IsConstructor(CAST(receiver)), &is_constructor, &is_not_constructor);
    BIND(&is_constructor);
    {
      array = Construct(context, CAST(receiver));
      Goto(&done);
    }
    BIND(&is_not_constructor);
    {
      Label allocate_js_array(this);
      TNode<Map> array_map = CAST(LoadContextElementNoCell(
          context, Context::JS_ARRAY_PACKED_SMI_ELEMENTS_MAP_INDEX));
      TNode<IntPtrT> capacity = IntPtrConstant(0);
      TNode<Smi> length = SmiConstant(0);
      array = AllocateJSArray(PACKED_SMI_ELEMENTS, array_map, capacity, length);
      Goto(&done);
    }
    BIND(&done);
    return array.value();
  }
References v8::internal::CodeStubAssembler::AllocateJSArray(), v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::CodeStubAssembler::Construct(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::is_constructor, v8::internal::CodeStubAssembler::IsConstructor(), v8::internal::length, v8::internal::PACKED_SMI_ELEMENTS, v8::internal::compiler::CodeAssembler::SmiConstant(), and v8::internal::CodeStubAssembler::TaggedIsSmi().
ConstructArrayLike() [2/2]
TNode<Object> v8::internal::ArrayPopulatorAssembler::ConstructArrayLike (TNode< Context > context, TNode< Object > receiver, TNode< Number > length) [inline]
Definition at line 629 of file builtins-array-gen.cc.
                                                         {
    TVARIABLE(Object, array);
    Label is_constructor(this), is_not_constructor(this), done(this);
    CSA_DCHECK(this, IsNumberNormalized(length));
    GotoIf(TaggedIsSmi(receiver), &is_not_constructor);
    Branch(IsConstructor(CAST(receiver)), &is_constructor, &is_not_constructor);
    BIND(&is_constructor);
    {
      array = Construct(context, CAST(receiver), length);
      Goto(&done);
    }
    BIND(&is_not_constructor);
    {
      array = ArrayCreate(context, length);
      Goto(&done);
    }
    BIND(&done);
    return array.value();
  }
References v8::internal::CodeStubAssembler::ArrayCreate(), v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::CodeStubAssembler::Construct(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::is_constructor, v8::internal::CodeStubAssembler::IsConstructor(), v8::internal::CodeStubAssembler::IsNumberNormalized(), v8::internal::length, and v8::internal::CodeStubAssembler::TaggedIsSmi().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-array-gen.cc