v8_inspector::V8HeapProfilerAgentImpl Class Reference
#include <v8-heap-profiler-agent-impl.h>
Classes
struct AsyncCallbacks
class GCTask
struct HeapSnapshotProtocolOptions
class HeapSnapshotTask
Public Member Functions
V8HeapProfilerAgentImpl (V8InspectorSessionImpl *, protocol::FrontendChannel *, protocol::DictionaryValue *state)
~V8HeapProfilerAgentImpl () override
V8HeapProfilerAgentImpl (const V8HeapProfilerAgentImpl &)=delete
V8HeapProfilerAgentImpl & operator= (const V8HeapProfilerAgentImpl &)=delete
void restore ()
void collectGarbage (std::unique_ptr< CollectGarbageCallback > callback) override
Response enable () override
Response startTrackingHeapObjects (std::optional< bool > trackAllocations) override
Response stopTrackingHeapObjects (std::optional< bool > reportProgress, std::optional< bool > treatGlobalObjectsAsRoots, std::optional< bool > captureNumericValue, std::optional< bool > exposeInternals) override
Response disable () override
void takeHeapSnapshot (std::optional< bool > reportProgress, std::optional< bool > treatGlobalObjectsAsRoots, std::optional< bool > captureNumericValue, std::optional< bool > exposeInternals, std::unique_ptr< TakeHeapSnapshotCallback > callback) override
Response getObjectByHeapObjectId (const String16 &heapSnapshotObjectId, std::optional< String16 > objectGroup, std::unique_ptr< protocol::Runtime::RemoteObject > *result) override
Response addInspectedHeapObject (const String16 &inspectedHeapObjectId) override
Response getHeapObjectId (const String16 &objectId, String16 *heapSnapshotObjectId) override
Response startSampling (std::optional< double > samplingInterval, std::optional< bool > includeObjectsCollectedByMajorGC, std::optional< bool > includeObjectsCollectedByMinorGC) override
Response stopSampling (std::unique_ptr< protocol::HeapProfiler::SamplingHeapProfile > *) override
Response getSamplingProfile (std::unique_ptr< protocol::HeapProfiler::SamplingHeapProfile > *) override
void takePendingHeapSnapshots ()
Private Member Functions
Response takeHeapSnapshotNow (const HeapSnapshotProtocolOptions &protocolOptions, cppgc::EmbedderStackState stackState)
void startTrackingHeapObjectsInternal (bool trackAllocations)
void stopTrackingHeapObjectsInternal ()
void requestHeapStatsUpdate ()
void onTimerImpl ()
Static Private Member Functions
static void onTimer (void *)
Private Attributes
V8InspectorSessionImpl * m_session
v8::Isolate * m_isolate
protocol::HeapProfiler::Frontend m_frontend
protocol::DictionaryValue * m_state
bool m_hasTimer
double m_timerDelayInSeconds
std::shared_ptr< AsyncCallbacks > m_asyncCallbacks
Detailed Description
Definition at line 24 of file v8-heap-profiler-agent-impl.h.
Constructor & Destructor Documentation
V8HeapProfilerAgentImpl() [1/2]
v8_inspector::V8HeapProfilerAgentImpl::V8HeapProfilerAgentImpl (V8InspectorSessionImpl * session, protocol::FrontendChannel * frontendChannel, protocol::DictionaryValue * state)
Definition at line 256 of file v8-heap-profiler-agent-impl.cc.
    : m_session(session),
      m_isolate(session->inspector()->isolate()),
      m_frontend(frontendChannel),
      m_state(state),
      m_hasTimer(false),
      m_asyncCallbacks(std::make_shared<AsyncCallbacks>()) {}
 V8HeapProfilerAgentImpl()
v8_inspector::V8HeapProfilerAgentImpl::~V8HeapProfilerAgentImpl () [override]
Definition at line 266 of file v8-heap-profiler-agent-impl.cc.
                                                  {
  v8::base::MutexGuard lock(&m_asyncCallbacks->m_mutex);
  m_asyncCallbacks->m_canceled = true;
  m_asyncCallbacks->m_gcCallbacks.clear();
  m_asyncCallbacks->m_heapSnapshotTasks.clear();
}
References m_asyncCallbacks.
V8HeapProfilerAgentImpl() [2/2]
v8_inspector::V8HeapProfilerAgentImpl::V8HeapProfilerAgentImpl (const V8HeapProfilerAgentImpl &) [delete]
Member Function Documentation
addInspectedHeapObject()
Response v8_inspector::V8HeapProfilerAgentImpl::addInspectedHeapObject (const String16 & inspectedHeapObjectId) [override]
Definition at line 449 of file v8-heap-profiler-agent-impl.cc.
                                           {
  bool ok;
  int id = inspectedHeapObjectId.toInteger(&ok);
  if (!ok) return Response::ServerError("Invalid heap snapshot object id");
  v8::HandleScope handles(m_isolate);
  v8::Local<v8::Object> heapObject = objectByHeapObjectId(m_isolate, id);
  if (heapObject.IsEmpty())
    return Response::ServerError("Object is not available");
  if (!m_session->inspector()->client()->isInspectableHeapObject(heapObject))
    return Response::ServerError("Object is not available");
  m_session->addInspectedObject(
      std::unique_ptr<InspectableHeapObject>(new InspectableHeapObject(id)));
  return Response::Success();
}
References v8_inspector::V8InspectorSessionImpl::addInspectedObject(), v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorSessionImpl::inspector(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8_inspector::V8InspectorClient::isInspectableHeapObject(), m_isolate, m_session, v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::objectByHeapObjectId(), and v8_inspector::String16::toInteger().
collectGarbage()
void v8_inspector::V8HeapProfilerAgentImpl::collectGarbage (std::unique_ptr< CollectGarbageCallback > callback) [override]
Definition at line 295 of file v8-heap-profiler-agent-impl.cc.
                                                    {
  v8::base::MutexGuard lock(&m_asyncCallbacks->m_mutex);
  m_asyncCallbacks->m_gcCallbacks.push_back(std::move(callback));
  v8::debug::GetCurrentPlatform()
      ->GetForegroundTaskRunner(m_isolate)
      ->PostNonNestableTask(
          std::make_unique<GCTask>(m_isolate, m_asyncCallbacks));
}
References v8::debug::GetCurrentPlatform(), v8::Platform::GetForegroundTaskRunner(), m_asyncCallbacks, and m_isolate.
disable()
Response v8_inspector::V8HeapProfilerAgentImpl::disable () [override]
Definition at line 335 of file v8-heap-profiler-agent-impl.cc.
                                          {
  stopTrackingHeapObjectsInternal();
  v8::HeapProfiler* profiler = m_isolate->GetHeapProfiler();
  DCHECK(profiler);
  if (m_state->booleanProperty(
          HeapProfilerAgentState::samplingHeapProfilerEnabled, false)) {
    profiler->StopSamplingHeapProfiler();
  }
  profiler->ClearObjectIds();
  m_state->setBoolean(HeapProfilerAgentState::heapProfilerEnabled, false);
  return Response::Success();
}
References v8::HeapProfiler::ClearObjectIds(), DCHECK, v8::Isolate::GetHeapProfiler(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::heapProfilerEnabled, m_isolate, m_state, v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::samplingHeapProfilerEnabled, v8::HeapProfiler::StopSamplingHeapProfiler(), and stopTrackingHeapObjectsInternal().
enable()
Response v8_inspector::V8HeapProfilerAgentImpl::enable () [override]
Definition at line 330 of file v8-heap-profiler-agent-impl.cc.
                                         {
  m_state->setBoolean(HeapProfilerAgentState::heapProfilerEnabled, true);
  return Response::Success();
}
References v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::heapProfilerEnabled, and m_state.
getHeapObjectId()
Response v8_inspector::V8HeapProfilerAgentImpl::getHeapObjectId (const String16 & objectId, String16 * heapSnapshotObjectId) [override]
Definition at line 467 of file v8-heap-profiler-agent-impl.cc.
                                                              {
  v8::HandleScope handles(m_isolate);
  v8::Local<v8::Value> value;
  v8::Local<v8::Context> context;
  Response response =
      m_session->unwrapObject(objectId, &value, &context, nullptr);
  if (!response.IsSuccess()) return response;
  if (value->IsUndefined()) return Response::InternalError();
  v8::SnapshotObjectId id = m_isolate->GetHeapProfiler()->GetObjectId(value);
  *heapSnapshotObjectId = String16::fromInteger(static_cast<size_t>(id));
  return Response::Success();
}
References v8_inspector::String16::fromInteger(), v8::Isolate::GetHeapProfiler(), v8::HeapProfiler::GetObjectId(), m_isolate, m_session, v8_inspector::V8InspectorSessionImpl::unwrapObject(), and v8::internal::value.
getObjectByHeapObjectId()
Response v8_inspector::V8HeapProfilerAgentImpl::getObjectByHeapObjectId (const String16 & heapSnapshotObjectId, std::optional< String16 > objectGroup, std::unique_ptr< protocol::Runtime::RemoteObject > * result) [override]
Definition at line 416 of file v8-heap-profiler-agent-impl.cc.
                                                        {
  bool ok;
  int id = heapSnapshotObjectId.toInteger(&ok);
  if (!ok) return Response::ServerError("Invalid heap snapshot object id");
  v8::HandleScope handles(m_isolate);
  v8::Local<v8::Object> heapObject = objectByHeapObjectId(m_isolate, id);
  if (heapObject.IsEmpty())
    return Response::ServerError("Object is not available");
  if (!m_session->inspector()->client()->isInspectableHeapObject(heapObject))
    return Response::ServerError("Object is not available");
  v8::Local<v8::Context> creationContext;
  if (!heapObject->GetCreationContext(m_isolate).ToLocal(&creationContext)) {
    return Response::ServerError("Object is not available");
  }
  *result = m_session->wrapObject(creationContext, heapObject,
                                  objectGroup.value_or(""), false);
  if (!*result) return Response::ServerError("Object is not available");
  return Response::Success();
}
References v8_inspector::V8InspectorImpl::client(), v8::Object::GetCreationContext(), v8_inspector::V8InspectorSessionImpl::inspector(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8_inspector::V8InspectorClient::isInspectableHeapObject(), m_isolate, m_session, v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::objectByHeapObjectId(), v8::base::internal::result, v8_inspector::String16::toInteger(), v8::MaybeLocal< T >::ToLocal(), and v8_inspector::V8InspectorSessionImpl::wrapObject().
getSamplingProfile()
Response v8_inspector::V8HeapProfilerAgentImpl::getSamplingProfile (std::unique_ptr< protocol::HeapProfiler::SamplingHeapProfile > * profile) [override]
Definition at line 621 of file v8-heap-profiler-agent-impl.cc.
                                                                     {
  v8::HeapProfiler* profiler = m_isolate->GetHeapProfiler();
  // Need a scope as v8::AllocationProfile contains Local handles.
  v8::HandleScope scope(m_isolate);
  std::unique_ptr<v8::AllocationProfile> v8Profile(
      profiler->GetAllocationProfile());
  if (!v8Profile)
    return Response::ServerError("V8 sampling heap profiler was not started.");
  v8::AllocationProfile::Node* root = v8Profile->GetRootNode();
  auto samples = std::make_unique<
      protocol::Array<protocol::HeapProfiler::SamplingHeapProfileSample>>();
  for (const auto& sample : v8Profile->GetSamples()) {
    samples->emplace_back(
        protocol::HeapProfiler::SamplingHeapProfileSample::create()
            .setSize(sample.size * sample.count)
            .setNodeId(sample.node_id)
            .setOrdinal(static_cast<double>(sample.sample_id))
            .build());
  }
  *profile = protocol::HeapProfiler::SamplingHeapProfile::create()
                 .setHead(buildSampingHeapProfileNode(m_isolate, root))
                 .setSamples(std::move(samples))
                 .build();
  return Response::Success();
}
References v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::buildSampingHeapProfileNode(), v8::HeapProfiler::GetAllocationProfile(), v8::Isolate::GetHeapProfiler(), and m_isolate.
Referenced by stopSampling().
onTimer()
void v8_inspector::V8HeapProfilerAgentImpl::onTimer (void * data) [static], [private]
Definition at line 491 of file v8-heap-profiler-agent-impl.cc.
                                                {
  reinterpret_cast<V8HeapProfilerAgentImpl*>(data)->onTimerImpl();
}
References onTimerImpl().
Referenced by onTimerImpl(), and startTrackingHeapObjectsInternal().
onTimerImpl()
void v8_inspector::V8HeapProfilerAgentImpl::onTimerImpl () [private]
Definition at line 498 of file v8-heap-profiler-agent-impl.cc.
                                          {
  v8::base::TimeTicks start = v8::base::TimeTicks::Now();
  requestHeapStatsUpdate();
  v8::base::TimeDelta elapsed = v8::base::TimeTicks::Now() - start;
  if (m_hasTimer) {
    // requestHeapStatsUpdate can take a long time on large heaps. To ensure
    // that there is still some time for the thread to make progress on running
    // JavaScript or doing other useful work, we'll adjust the timer delay here.
    const v8::base::TimeDelta minAcceptableDelay =
        std::max(elapsed * 2, kDefaultTimerDelay);
    const v8::base::TimeDelta idealDelay =
        std::max(elapsed * 3, kDefaultTimerDelay);
    const v8::base::TimeDelta maxAcceptableDelay =
        std::max(elapsed * 4, kDefaultTimerDelay);
    if (m_timerDelayInSeconds < minAcceptableDelay.InSecondsF() ||
        m_timerDelayInSeconds > maxAcceptableDelay.InSecondsF()) {
      // The existing timer's speed is not very close to ideal, so cancel it and
      // start a new timer.
      m_session->inspector()->client()->cancelTimer(
          reinterpret_cast<void*>(this));
      m_timerDelayInSeconds = idealDelay.InSecondsF();
      m_session->inspector()->client()->startRepeatingTimer(
          m_timerDelayInSeconds, &V8HeapProfilerAgentImpl::onTimer,
          reinterpret_cast<void*>(this));
    }
  }
}
References v8_inspector::V8InspectorClient::cancelTimer(), v8_inspector::V8InspectorImpl::client(), v8::base::TimeDelta::InSecondsF(), v8_inspector::V8InspectorSessionImpl::inspector(), v8_inspector::kDefaultTimerDelay, m_hasTimer, m_session, m_timerDelayInSeconds, v8::base::TimeTicks::Now(), onTimer(), requestHeapStatsUpdate(), and v8_inspector::V8InspectorClient::startRepeatingTimer().
Referenced by onTimer().
operator=()
V8HeapProfilerAgentImpl& v8_inspector::V8HeapProfilerAgentImpl::operator= (const V8HeapProfilerAgentImpl &) [delete]
requestHeapStatsUpdate()
void v8_inspector::V8HeapProfilerAgentImpl::requestHeapStatsUpdate () [private]
Definition at line 482 of file v8-heap-profiler-agent-impl.cc.
                                                     {
  HeapStatsStream stream(&m_frontend);
  v8::SnapshotObjectId lastSeenObjectId =
      m_isolate->GetHeapProfiler()->GetHeapStats(&stream);
  m_frontend.lastSeenObjectId(
      lastSeenObjectId, m_session->inspector()->client()->currentTimeMS());
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorClient::currentTimeMS(), v8::Isolate::GetHeapProfiler(), v8::HeapProfiler::GetHeapStats(), v8_inspector::V8InspectorSessionImpl::inspector(), m_frontend, m_isolate, and m_session.
Referenced by onTimerImpl(), and stopTrackingHeapObjects().
restore()
void v8_inspector::V8HeapProfilerAgentImpl::restore ()
Definition at line 273 of file v8-heap-profiler-agent-impl.cc.
                                      {
  if (m_state->booleanProperty(HeapProfilerAgentState::heapProfilerEnabled,
                               false))
    m_frontend.resetProfiles();
  if (m_state->booleanProperty(
          HeapProfilerAgentState::heapObjectsTrackingEnabled, false))
    startTrackingHeapObjectsInternal(m_state->booleanProperty(
        HeapProfilerAgentState::allocationTrackingEnabled, false));
  if (m_state->booleanProperty(
          HeapProfilerAgentState::samplingHeapProfilerEnabled, false)) {
    double samplingInterval = m_state->doubleProperty(
        HeapProfilerAgentState::samplingHeapProfilerInterval, -1);
    DCHECK_GE(samplingInterval, 0);
    int flags = m_state->integerProperty(
        HeapProfilerAgentState::samplingHeapProfilerFlags, 0);
    startSampling(
        samplingInterval,
        flags & v8::HeapProfiler::kSamplingIncludeObjectsCollectedByMajorGC,
        flags & v8::HeapProfiler::kSamplingIncludeObjectsCollectedByMinorGC);
  }
}
References v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::allocationTrackingEnabled, DCHECK_GE, flags(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::heapObjectsTrackingEnabled, v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::heapProfilerEnabled, v8::HeapProfiler::kSamplingIncludeObjectsCollectedByMajorGC, v8::HeapProfiler::kSamplingIncludeObjectsCollectedByMinorGC, m_frontend, m_state, v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::samplingHeapProfilerEnabled, v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::samplingHeapProfilerFlags, v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::samplingHeapProfilerInterval, v8_inspector::ProfilerAgentState::samplingInterval, startSampling(), and startTrackingHeapObjectsInternal().
startSampling()
Response v8_inspector::V8HeapProfilerAgentImpl::startSampling (std::optional< double > samplingInterval, std::optional< bool > includeObjectsCollectedByMajorGC, std::optional< bool > includeObjectsCollectedByMinorGC) [override]
Definition at line 550 of file v8-heap-profiler-agent-impl.cc.
                                                        {
  v8::HeapProfiler* profiler = m_isolate->GetHeapProfiler();
  DCHECK(profiler);
  const unsigned defaultSamplingInterval = 1 << 15;
  double samplingIntervalValue =
      samplingInterval.value_or(defaultSamplingInterval);
  if (samplingIntervalValue <= 0.0) {
    return Response::ServerError("Invalid sampling interval");
  }
  m_state->setDouble(HeapProfilerAgentState::samplingHeapProfilerInterval,
                     samplingIntervalValue);
  m_state->setBoolean(HeapProfilerAgentState::samplingHeapProfilerEnabled,
                      true);
  int flags = v8::HeapProfiler::kSamplingForceGC;
  if (includeObjectsCollectedByMajorGC.value_or(false)) {
    flags |= v8::HeapProfiler::kSamplingIncludeObjectsCollectedByMajorGC;
  }
  if (includeObjectsCollectedByMinorGC.value_or(false)) {
    flags |= v8::HeapProfiler::kSamplingIncludeObjectsCollectedByMinorGC;
  }
  m_state->setInteger(HeapProfilerAgentState::samplingHeapProfilerFlags, flags);
  profiler->StartSamplingHeapProfiler(
      static_cast<uint64_t>(samplingIntervalValue), 128,
      static_cast<v8::HeapProfiler::SamplingFlags>(flags));
  return Response::Success();
}
References DCHECK, flags(), v8::Isolate::GetHeapProfiler(), v8::HeapProfiler::kSamplingForceGC, v8::HeapProfiler::kSamplingIncludeObjectsCollectedByMajorGC, v8::HeapProfiler::kSamplingIncludeObjectsCollectedByMinorGC, m_isolate, m_state, v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::samplingHeapProfilerEnabled, v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::samplingHeapProfilerFlags, v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::samplingHeapProfilerInterval, v8_inspector::ProfilerAgentState::samplingInterval, and v8::HeapProfiler::StartSamplingHeapProfiler().
Referenced by restore().
startTrackingHeapObjects()
Response v8_inspector::V8HeapProfilerAgentImpl::startTrackingHeapObjects (std::optional< bool > trackAllocations) [override]
Definition at line 305 of file v8-heap-profiler-agent-impl.cc.
                                        {
  m_state->setBoolean(HeapProfilerAgentState::heapObjectsTrackingEnabled, true);
  bool allocationTrackingEnabled = trackAllocations.value_or(false);
  m_state->setBoolean(HeapProfilerAgentState::allocationTrackingEnabled,
                      allocationTrackingEnabled);
  startTrackingHeapObjectsInternal(allocationTrackingEnabled);
  return Response::Success();
}
References v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::allocationTrackingEnabled, v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::heapObjectsTrackingEnabled, m_state, and startTrackingHeapObjectsInternal().
startTrackingHeapObjectsInternal()
void v8_inspector::V8HeapProfilerAgentImpl::startTrackingHeapObjectsInternal (bool trackAllocations) [private]
Definition at line 526 of file v8-heap-profiler-agent-impl.cc.
                           {
  m_isolate->GetHeapProfiler()->StartTrackingHeapObjects(trackAllocations);
  if (!m_hasTimer) {
    m_hasTimer = true;
    m_timerDelayInSeconds = kDefaultTimerDelay.InSecondsF();
    m_session->inspector()->client()->startRepeatingTimer(
        m_timerDelayInSeconds, &V8HeapProfilerAgentImpl::onTimer,
        reinterpret_cast<void*>(this));
  }
}
References v8_inspector::V8InspectorImpl::client(), v8::Isolate::GetHeapProfiler(), v8::base::TimeDelta::InSecondsF(), v8_inspector::V8InspectorSessionImpl::inspector(), v8_inspector::kDefaultTimerDelay, m_hasTimer, m_isolate, m_session, m_timerDelayInSeconds, onTimer(), v8_inspector::V8InspectorClient::startRepeatingTimer(), and v8::HeapProfiler::StartTrackingHeapObjects().
Referenced by restore(), and startTrackingHeapObjects().
stopSampling()
Response v8_inspector::V8HeapProfilerAgentImpl::stopSampling (std::unique_ptr< protocol::HeapProfiler::SamplingHeapProfile > * profile) [override]
Definition at line 610 of file v8-heap-profiler-agent-impl.cc.
                                                                     {
  Response result = getSamplingProfile(profile);
  if (result.IsSuccess()) {
    m_isolate->GetHeapProfiler()->StopSamplingHeapProfiler();
    m_state->setBoolean(HeapProfilerAgentState::samplingHeapProfilerEnabled,
                        false);
  }
  return result;
}
References v8::Isolate::GetHeapProfiler(), getSamplingProfile(), m_isolate, m_state, v8::base::internal::result, v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::samplingHeapProfilerEnabled, and v8::HeapProfiler::StopSamplingHeapProfiler().
stopTrackingHeapObjects()
Response v8_inspector::V8HeapProfilerAgentImpl::stopTrackingHeapObjects (std::optional< bool > reportProgress, std::optional< bool > treatGlobalObjectsAsRoots, std::optional< bool > captureNumericValue, std::optional< bool > exposeInternals) [override]
Definition at line 315 of file v8-heap-profiler-agent-impl.cc.
                                       {
  requestHeapStatsUpdate();
  takeHeapSnapshotNow(
      HeapSnapshotProtocolOptions(
          std::move(reportProgress), std::move(treatGlobalObjectsAsRoots),
          std::move(captureNumericValue), std::move(exposeInternals)),
      cppgc::EmbedderStackState::kMayContainHeapPointers);
  stopTrackingHeapObjectsInternal();
  return Response::Success();
}
References cppgc::kMayContainHeapPointers, requestHeapStatsUpdate(), stopTrackingHeapObjectsInternal(), and takeHeapSnapshotNow().
stopTrackingHeapObjectsInternal()
void v8_inspector::V8HeapProfilerAgentImpl::stopTrackingHeapObjectsInternal () [private]
Definition at line 538 of file v8-heap-profiler-agent-impl.cc.
                                                              {
  if (m_hasTimer) {
    m_session->inspector()->client()->cancelTimer(
        reinterpret_cast<void*>(this));
    m_hasTimer = false;
  }
  m_isolate->GetHeapProfiler()->StopTrackingHeapObjects();
  m_state->setBoolean(HeapProfilerAgentState::heapObjectsTrackingEnabled,
                      false);
  m_state->setBoolean(HeapProfilerAgentState::allocationTrackingEnabled, false);
}
References v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::allocationTrackingEnabled, v8_inspector::V8InspectorClient::cancelTimer(), v8_inspector::V8InspectorImpl::client(), v8::Isolate::GetHeapProfiler(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapProfilerAgentState::heapObjectsTrackingEnabled, v8_inspector::V8InspectorSessionImpl::inspector(), m_hasTimer, m_isolate, m_session, m_state, and v8::HeapProfiler::StopTrackingHeapObjects().
Referenced by disable(), and stopTrackingHeapObjects().
takeHeapSnapshot()
void v8_inspector::V8HeapProfilerAgentImpl::takeHeapSnapshot (std::optional< bool > reportProgress, std::optional< bool > treatGlobalObjectsAsRoots, std::optional< bool > captureNumericValue, std::optional< bool > exposeInternals, std::unique_ptr< TakeHeapSnapshotCallback > callback) [override]
Definition at line 348 of file v8-heap-profiler-agent-impl.cc.
                                                      {
  HeapSnapshotProtocolOptions protocolOptions(
      std::move(reportProgress), std::move(treatGlobalObjectsAsRoots),
      std::move(captureNumericValue), std::move(exposeInternals));
  std::shared_ptr<v8::TaskRunner> task_runner =
      v8::debug::GetCurrentPlatform()->GetForegroundTaskRunner(m_isolate);
  // Heap snapshots can be more accurate if we wait until the stack is empty and
  // run the garbage collector without conservative stack scanning, as done in
  // V8HeapProfilerAgentImpl::collectGarbage. However, heap snapshots can also
  // be requested while paused in the debugger, in which case the snapshot must
  // be taken immediately with conservative stack scanning enabled.
  if (m_session->inspector()->debugger()->isPaused() ||
      !task_runner->NonNestableTasksEnabled()) {
    Response response = takeHeapSnapshotNow(
        protocolOptions, cppgc::EmbedderStackState::kMayContainHeapPointers);
    if (response.IsSuccess()) {
      callback->sendSuccess();
    } else {
      callback->sendFailure(std::move(response));
    }
    return;
  }
  std::unique_ptr<HeapSnapshotTask> task = std::make_unique<HeapSnapshotTask>(
      this, m_asyncCallbacks, protocolOptions, std::move(callback));
  m_asyncCallbacks->m_heapSnapshotTasks.push_back(task.get());
  task_runner->PostNonNestableTask(std::move(task));
}
References v8_inspector::V8InspectorImpl::debugger(), v8::debug::GetCurrentPlatform(), v8::Platform::GetForegroundTaskRunner(), v8_inspector::V8InspectorSessionImpl::inspector(), v8_inspector::V8Debugger::isPaused(), cppgc::kMayContainHeapPointers, m_asyncCallbacks, m_isolate, m_session, and takeHeapSnapshotNow().
takeHeapSnapshotNow()
Response v8_inspector::V8HeapProfilerAgentImpl::takeHeapSnapshotNow (const HeapSnapshotProtocolOptions & protocolOptions, cppgc::EmbedderStackState stackState) [private]
Definition at line 383 of file v8-heap-profiler-agent-impl.cc.
                                        {
  v8::HeapProfiler* profiler = m_isolate->GetHeapProfiler();
  DCHECK(profiler);
  std::unique_ptr<HeapSnapshotProgress> progress;
  if (protocolOptions.m_reportProgress)
    progress.reset(new HeapSnapshotProgress(&m_frontend));
  GlobalObjectNameResolver resolver(m_session);
  v8::HeapProfiler::HeapSnapshotOptions options;
  options.global_object_name_resolver = &resolver;
  options.control = progress.get();
  options.snapshot_mode =
      protocolOptions.m_exposeInternals ||
              // Not treating global objects as roots results into exposing
              // internals.
              !protocolOptions.m_treatGlobalObjectsAsRoots
          ? v8::HeapProfiler::HeapSnapshotMode::kExposeInternals
          : v8::HeapProfiler::HeapSnapshotMode::kRegular;
  options.numerics_mode =
      protocolOptions.m_captureNumericValue
          ? v8::HeapProfiler::NumericsMode::kExposeNumericValues
          : v8::HeapProfiler::NumericsMode::kHideNumericValues;
  options.stack_state = stackState;
  const v8::HeapSnapshot* snapshot = profiler->TakeHeapSnapshot(options);
  if (!snapshot) return Response::ServerError("Failed to take heap snapshot");
  HeapSnapshotOutputStream stream(&m_frontend);
  snapshot->Serialize(&stream);
  const_cast<v8::HeapSnapshot*>(snapshot)->Delete();
  return Response::Success();
}
References v8::HeapProfiler::HeapSnapshotOptions::control, DCHECK, v8::Isolate::GetHeapProfiler(), v8::HeapProfiler::HeapSnapshotOptions::global_object_name_resolver, v8::HeapProfiler::kExposeInternals, v8::HeapProfiler::kExposeNumericValues, v8::HeapProfiler::kHideNumericValues, v8::HeapProfiler::kRegular, v8_inspector::V8HeapProfilerAgentImpl::HeapSnapshotProtocolOptions::m_captureNumericValue, v8_inspector::V8HeapProfilerAgentImpl::HeapSnapshotProtocolOptions::m_exposeInternals, m_frontend, m_isolate, v8_inspector::V8HeapProfilerAgentImpl::HeapSnapshotProtocolOptions::m_reportProgress, m_session, v8_inspector::V8HeapProfilerAgentImpl::HeapSnapshotProtocolOptions::m_treatGlobalObjectsAsRoots, v8::HeapProfiler::HeapSnapshotOptions::numerics_mode, v8::HeapSnapshot::Serialize(), v8::HeapProfiler::HeapSnapshotOptions::snapshot_mode, v8::HeapProfiler::HeapSnapshotOptions::stack_state, and v8::HeapProfiler::TakeHeapSnapshot().
Referenced by v8_inspector::V8HeapProfilerAgentImpl::HeapSnapshotTask::Run(), stopTrackingHeapObjects(), and takeHeapSnapshot().
takePendingHeapSnapshots()
void v8_inspector::V8HeapProfilerAgentImpl::takePendingHeapSnapshots ()
Definition at line 441 of file v8-heap-profiler-agent-impl.cc.
                                                       {
  // Each task will remove itself from m_heapSnapshotTasks.
  while (!m_asyncCallbacks->m_heapSnapshotTasks.empty()) {
    m_asyncCallbacks->m_heapSnapshotTasks.front()->Run(
        cppgc::EmbedderStackState::kMayContainHeapPointers);
  }
}
References cppgc::kMayContainHeapPointers, and m_asyncCallbacks.
Member Data Documentation
m_asyncCallbacks
std::shared_ptr<AsyncCallbacks> v8_inspector::V8HeapProfilerAgentImpl::m_asyncCallbacks [private]
Definition at line 96 of file v8-heap-profiler-agent-impl.h.
Referenced by collectGarbage(), takeHeapSnapshot(), takePendingHeapSnapshots(), and ~V8HeapProfilerAgentImpl().
m_frontend
protocol::HeapProfiler::Frontend v8_inspector::V8HeapProfilerAgentImpl::m_frontend [private]
Definition at line 92 of file v8-heap-profiler-agent-impl.h.
Referenced by requestHeapStatsUpdate(), restore(), and takeHeapSnapshotNow().
m_hasTimer
bool v8_inspector::V8HeapProfilerAgentImpl::m_hasTimer [private]
Definition at line 94 of file v8-heap-profiler-agent-impl.h.
Referenced by onTimerImpl(), startTrackingHeapObjectsInternal(), and stopTrackingHeapObjectsInternal().
m_isolate
v8::Isolate* v8_inspector::V8HeapProfilerAgentImpl::m_isolate [private]
Definition at line 91 of file v8-heap-profiler-agent-impl.h.
Referenced by addInspectedHeapObject(), collectGarbage(), disable(), getHeapObjectId(), getObjectByHeapObjectId(), getSamplingProfile(), requestHeapStatsUpdate(), startSampling(), startTrackingHeapObjectsInternal(), stopSampling(), stopTrackingHeapObjectsInternal(), takeHeapSnapshot(), and takeHeapSnapshotNow().
m_session
V8InspectorSessionImpl* v8_inspector::V8HeapProfilerAgentImpl::m_session [private]
Definition at line 90 of file v8-heap-profiler-agent-impl.h.
Referenced by addInspectedHeapObject(), getHeapObjectId(), getObjectByHeapObjectId(), onTimerImpl(), requestHeapStatsUpdate(), startTrackingHeapObjectsInternal(), stopTrackingHeapObjectsInternal(), takeHeapSnapshot(), and takeHeapSnapshotNow().
m_state
protocol::DictionaryValue* v8_inspector::V8HeapProfilerAgentImpl::m_state [private]
Definition at line 93 of file v8-heap-profiler-agent-impl.h.
Referenced by disable(), enable(), restore(), startSampling(), startTrackingHeapObjects(), stopSampling(), and stopTrackingHeapObjectsInternal().
m_timerDelayInSeconds
double v8_inspector::V8HeapProfilerAgentImpl::m_timerDelayInSeconds [private]
Definition at line 95 of file v8-heap-profiler-agent-impl.h.
Referenced by onTimerImpl(), and startTrackingHeapObjectsInternal().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-heap-profiler-agent-impl.h
/mnt/V8SourceCode/src/inspector/v8-heap-profiler-agent-impl.cc