v8::internal::RegExpAlternative Class Reference
#include <regexp-ast.h>
Public Member Functions
RegExpAlternative (ZoneList< RegExpTree * > *nodes)
DECL_BOILERPLATE (Alternative)
Interval CaptureRegisters () override
bool IsAnchoredAtStart () override
bool IsAnchoredAtEnd () override
int min_match () override
int max_match () override
ZoneList< RegExpTree * > * nodes () const
Private Attributes
ZoneList< RegExpTree * > * nodes_
int min_match_
int max_match_
Additional Inherited Members
Detailed Description
Definition at line 240 of file regexp-ast.h.
Constructor & Destructor Documentation
RegExpAlternative()
v8::internal::RegExpAlternative::RegExpAlternative (ZoneList< RegExpTree * > * nodes) [explicit]
Definition at line 375 of file regexp-ast.cc.
    : nodes_(nodes) {
  DCHECK_LT(1, nodes->length());
  min_match_ = 0;
  max_match_ = 0;
  for (int i = 0; i < nodes->length(); i++) {
    RegExpTree* node = nodes->at(i);
    int node_min_match = node->min_match();
    min_match_ = IncreaseBy(min_match_, node_min_match);
    int node_max_match = node->max_match();
    max_match_ = IncreaseBy(max_match_, node_max_match);
  }
}
References DCHECK_LT, v8::internal::anonymous_namespace{regexp-ast.cc}::IncreaseBy(), v8::internal::RegExpTree::max_match(), max_match_, v8::internal::RegExpTree::min_match(), min_match_, and nodes().
Member Function Documentation
CaptureRegisters()
Interval v8::internal::RegExpAlternative::CaptureRegisters () [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 43 of file regexp-ast.cc.
                                             {
  return ListCaptureRegisters(nodes());
}
References v8::internal::anonymous_namespace{regexp-ast.cc}::ListCaptureRegisters(), and nodes().
DECL_BOILERPLATE()
v8::internal::RegExpAlternative::DECL_BOILERPLATE (Alternative)
IsAnchoredAtEnd()
bool v8::internal::RegExpAlternative::IsAnchoredAtEnd () [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 94 of file regexp-ast.cc.
                                        {
  ZoneList<RegExpTree*>* nodes = this->nodes();
  for (int i = nodes->length() - 1; i >= 0; i--) {
    RegExpTree* node = nodes->at(i);
    if (node->IsAnchoredAtEnd()) {
      return true;
    }
    if (node->max_match() > 0) {
      return false;
    }
  }
  return false;
}
References v8::internal::RegExpTree::IsAnchoredAtEnd(), v8::internal::ZoneList< T >::length(), v8::internal::RegExpTree::max_match(), and nodes().
IsAnchoredAtStart()
bool v8::internal::RegExpAlternative::IsAnchoredAtStart () [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 79 of file regexp-ast.cc.
                                          {
  ZoneList<RegExpTree*>* nodes = this->nodes();
  for (int i = 0; i < nodes->length(); i++) {
    RegExpTree* node = nodes->at(i);
    if (node->IsAnchoredAtStart()) {
      return true;
    }
    if (node->max_match() > 0) {
      return false;
    }
  }
  return false;
}
References v8::internal::RegExpTree::IsAnchoredAtStart(), v8::internal::ZoneList< T >::length(), v8::internal::RegExpTree::max_match(), and nodes().
max_match()
int v8::internal::RegExpAlternative::max_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 250 of file regexp-ast.h.
{ return max_match_; }
References max_match_.
min_match()
int v8::internal::RegExpAlternative::min_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 249 of file regexp-ast.h.
{ return min_match_; }
References min_match_.
nodes()
ZoneList<RegExpTree*>* v8::internal::RegExpAlternative::nodes () const [inline]
Definition at line 251 of file regexp-ast.h.
{ return nodes_; }
References nodes_.
Referenced by CaptureRegisters(), IsAnchoredAtEnd(), IsAnchoredAtStart(), RegExpAlternative(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitAlternative(), v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitAlternative(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitAlternative().
Member Data Documentation
max_match_
int v8::internal::RegExpAlternative::max_match_ [private]
Definition at line 256 of file regexp-ast.h.
Referenced by max_match(), and RegExpAlternative().
min_match_
int v8::internal::RegExpAlternative::min_match_ [private]
Definition at line 255 of file regexp-ast.h.
Referenced by min_match(), and RegExpAlternative().
nodes_
ZoneList<RegExpTree*>* v8::internal::RegExpAlternative::nodes_ [private]
Definition at line 254 of file regexp-ast.h.
Referenced by nodes().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-ast.cc