v8::internal::compiler::JSGlobalObjectRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< JSGlobalObject > object () const
bool IsDetachedFrom (JSGlobalProxyRef proxy) const
OptionalPropertyCellRef GetPropertyCell (JSHeapBroker *broker, NameRef name) const
Detailed Description
Definition at line 1275 of file heap-refs.h.
Member Function Documentation
GetPropertyCell()
OptionalPropertyCellRef v8::internal::compiler::JSGlobalObjectRef::GetPropertyCell (JSHeapBroker * broker, NameRef name) const
Definition at line 2518 of file heap-refs.cc.
                                                                               {
  std::optional<Tagged<PropertyCell>> maybe_cell =
      ConcurrentLookupIterator::TryGetPropertyCell(
          broker->isolate(), broker->local_isolate_or_isolate(),
          broker->target_native_context().global_object(broker).object(),
          name.object());
  if (!maybe_cell.has_value()) return {};
  return TryMakeRef(broker, *maybe_cell);
}
References broker(), v8::internal::name, v8::internal::ConcurrentLookupIterator::TryGetPropertyCell(), and v8::internal::compiler::TryMakeRef().
IsDetachedFrom()
bool v8::internal::compiler::JSGlobalObjectRef::IsDetachedFrom (JSGlobalProxyRef proxy) const
object()
IndirectHandle<JSGlobalObject> v8::internal::compiler::JSGlobalObjectRef::object () const
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc