v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable Class Reference
#include <wasm-load-elimination-reducer.h>
Public Types
enum class EntriesWithOffsets { kInvalidate
, kKeep
 }
using MemoryAddress = WasmMemoryAddress
Public Member Functions
WasmMemoryContentTable (PipelineData *data, Zone *zone, SparseOpIndexSnapshotTable< bool > &non_aliasing_objects, FixedOpIndexSidetable< OpIndex > &replacements, Graph &graph)
void OnNewKey (Key key, OpIndex value)
void OnValueChange (Key key, OpIndex old_value, OpIndex new_value)
bool TypesUnrelated (wasm::ModuleTypeIndex type1, wasm::ModuleTypeIndex type2)
void Invalidate (int offset, wasm::ModuleTypeIndex type_index)
void Invalidate (const StructSetOp &set)
void Invalidate (const StructAtomicRMWOp &rmw_op)
template<EntriesWithOffsets offsets = EntriesWithOffsets::kInvalidate>
void InvalidateMaybeAliasing ()
int field_offset (const wasm::StructType *type, int field_index)
OpIndex Find (const StructGetOp &get)
bool HasValueWithIncorrectMutability (const StructSetOp &set)
OpIndex FindLoadLike (OpIndex op_idx, int offset_sentinel)
OpIndex FindImpl (OpIndex object, int offset, wasm::ModuleTypeIndex type_index, uint8_t size, bool mutability, OptionalOpIndex index=OptionalOpIndex::Nullopt())
void Insert (const StructSetOp &set)
void Insert (const StructGetOp &get, OpIndex get_idx)
void InsertLoadLike (OpIndex base_idx, int offset_sentinel, OpIndex value_idx)
OpIndex ResolveBase (OpIndex base)
void AddKeyInBaseOffsetMaps (Key key)
void RemoveKeyFromBaseOffsetMaps (Key key)
Public Attributes
SparseOpIndexSnapshotTable< bool > & non_aliasing_objects_
FixedOpIndexSidetable< OpIndex > & replacements_
PipelineData * data_
Graph & graph_
const wasm::WasmModule * module_ = data_->wasm_module()
ZoneUnorderedMap< WasmMemoryAddress, Key > all_keys_
ZoneUnorderedMap< OpIndex, BaseData > base_keys_
ZoneUnorderedMap< int, v8::base::DoublyThreadedList< Key, OffsetListTraits > > offset_keys_
Private Member Functions
void Insert (OpIndex base, int32_t offset, wasm::ModuleTypeIndex type_index, uint8_t size, bool mutability, OpIndex value)
Detailed Description
Definition at line 101 of file wasm-load-elimination-reducer.h.
Member Typedef Documentation
MemoryAddress
using v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::MemoryAddress = WasmMemoryAddress
Definition at line 105 of file wasm-load-elimination-reducer.h.
Member Enumeration Documentation
EntriesWithOffsets
enum v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::EntriesWithOffsets [strong]
Enumerator
kInvalidate
kKeep
Definition at line 182 of file wasm-load-elimination-reducer.h.
{ kInvalidate, kKeep };
Constructor & Destructor Documentation
WasmMemoryContentTable()
v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::WasmMemoryContentTable (PipelineData * data, Zone * zone, SparseOpIndexSnapshotTable< bool > & non_aliasing_objects, FixedOpIndexSidetable< OpIndex > & replacements, Graph & graph) [inline], [explicit]
Definition at line 107 of file wasm-load-elimination-reducer.h.
      : ChangeTrackingSnapshotTable(zone),
        non_aliasing_objects_(non_aliasing_objects),
        replacements_(replacements),
        data_(data),
        graph_(graph),
        all_keys_(zone),
        base_keys_(zone),
        offset_keys_(zone) {}
Member Function Documentation
AddKeyInBaseOffsetMaps()
void v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::AddKeyInBaseOffsetMaps (Key key) [inline]
Definition at line 331 of file wasm-load-elimination-reducer.h.
                                       {
    // Inserting in {base_keys_}.
    OpIndex base = key.data().mem.base;
    auto base_keys = base_keys_.find(base);
    if (base_keys != base_keys_.end()) {
      base_keys->second.with_offsets.PushFront(key);
    } else {
      BaseData data;
      data.with_offsets.PushFront(key);
      base_keys_.insert({base, std::move(data)});
    }
    // Inserting in {offset_keys_}.
    int offset = key.data().mem.offset;
    auto offset_keys = offset_keys_.find(offset);
    if (offset_keys != offset_keys_.end()) {
      offset_keys->second.PushFront(key);
    } else {
      v8::base::DoublyThreadedList<Key, OffsetListTraits> list;
      list.PushFront(key);
      offset_keys_.insert({offset, std::move(list)});
    }
  }
References base_keys_, v8::internal::key, offset_keys_, v8::base::DoublyThreadedList< T, DTLTraits >::PushFront(), and v8::internal::compiler::turboshaft::wle::BaseData::with_offsets.
Referenced by OnNewKey(), and OnValueChange().
field_offset()
int v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::field_offset (const wasm::StructType * type, int field_index) [inline]
Definition at line 211 of file wasm-load-elimination-reducer.h.
                                                                {
    return WasmStruct::kHeaderSize + type->field_offset(field_index);
  }
References v8::internal::tracing::type.
Referenced by Find(), HasValueWithIncorrectMutability(), Insert(), and Invalidate().
Find()
OpIndex v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::Find (const StructGetOp & get) [inline]
Definition at line 215 of file wasm-load-elimination-reducer.h.
                                       {
    int32_t offset = field_offset(get.type, get.field_index);
    uint8_t size = get.type->field(get.field_index).value_kind_size();
    bool mutability = get.type->mutability(get.field_index);
    return FindImpl(ResolveBase(get.object()), offset, get.type_index, size,
                    mutability);
  }
References field_offset(), FindImpl(), ResolveBase(), and size().
Referenced by v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStructGet().
FindImpl()
OpIndex v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::FindImpl (OpIndex object, int offset, wasm::ModuleTypeIndex type_index, uint8_t size, bool mutability, OptionalOpIndex index = OptionalOpIndex::Nullopt()) [inline]
Definition at line 238 of file wasm-load-elimination-reducer.h.
                                                                     {
    WasmMemoryAddress mem{object, offset, type_index, size, mutability};
    auto key = all_keys_.find(mem);
    if (key == all_keys_.end()) return OpIndex::Invalid();
    return Get(key->second);
  }
References all_keys_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Get(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::key, and size().
Referenced by Find(), and FindLoadLike().
FindLoadLike()
OpIndex v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::FindLoadLike (OpIndex op_idx, int offset_sentinel) [inline]
Definition at line 232 of file wasm-load-elimination-reducer.h.
                                                            {
    static constexpr bool mutability = false;
    return FindImpl(ResolveBase(op_idx), offset_sentinel, kLoadLikeType,
                    kLoadLikeSize, mutability);
  }
References FindImpl(), v8::internal::compiler::turboshaft::wle::kLoadLikeSize, v8::internal::compiler::turboshaft::wle::kLoadLikeType, and ResolveBase().
Referenced by v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAnyConvertExtern(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessArrayLength(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAssertNotNull(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStringAsWtf16(), and v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStringPrepareForGetCodeUnit().
HasValueWithIncorrectMutability()
bool v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::HasValueWithIncorrectMutability (const StructSetOp & set) [inline]
Definition at line 223 of file wasm-load-elimination-reducer.h.
                                                               {
    int32_t offset = field_offset(set.type, set.field_index);
    uint8_t size = set.type->field(set.field_index).value_kind_size();
    bool mutability = set.type->mutability(set.field_index);
    WasmMemoryAddress mem{ResolveBase(set.object()), offset, set.type_index,
                          size, !mutability};
    return all_keys_.find(mem) != all_keys_.end();
  }
References all_keys_, field_offset(), ResolveBase(), and size().
Referenced by v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStructSet().
Insert() [1/3]
void v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::Insert (const StructGetOp & get, OpIndex get_idx) [inline]
Definition at line 255 of file wasm-load-elimination-reducer.h.
                                                       {
    OpIndex base = ResolveBase(get.object());
    int32_t offset = field_offset(get.type, get.field_index);
    uint8_t size = get.type->field(get.field_index).value_kind_size();
    bool mutability = get.type->mutability(get.field_index);
    Insert(base, offset, get.type_index, size, mutability, get_idx);
  }
References field_offset(), Insert(), ResolveBase(), and size().
Insert() [2/3]
void v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::Insert (const StructSetOp & set) [inline]
Definition at line 247 of file wasm-load-elimination-reducer.h.
                                      {
    OpIndex base = ResolveBase(set.object());
    int32_t offset = field_offset(set.type, set.field_index);
    uint8_t size = set.type->field(set.field_index).value_kind_size();
    bool mutability = set.type->mutability(set.field_index);
    Insert(base, offset, set.type_index, size, mutability, set.value());
  }
References field_offset(), ResolveBase(), and size().
Referenced by Insert(), InsertLoadLike(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStructGet(), and v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStructSet().
Insert() [3/3]
void v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::Insert (OpIndex base, int32_t offset, wasm::ModuleTypeIndex type_index, uint8_t size, bool mutability, OpIndex value) [inline], [private]
Definition at line 284 of file wasm-load-elimination-reducer.h.
                                                            {
    DCHECK_EQ(base, ResolveBase(base));
    WasmMemoryAddress mem{base, offset, type_index, size, mutability};
    auto existing_key = all_keys_.find(mem);
    if (existing_key != all_keys_.end()) {
      if (mutability) {
        Set(existing_key->second, value);
      } else {
        SetNoNotify(existing_key->second, value);
      }
      return;
    }
    // Creating a new key.
    Key key = NewKey({mem});
    all_keys_.insert({mem, key});
    if (mutability) {
      Set(key, value);
    } else {
      // Call `SetNoNotify` to avoid calls to `OnNewKey` and `OnValueChanged`.
      SetNoNotify(key, value);
    }
  }
References all_keys_, DCHECK_EQ, v8::internal::key, v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< WasmMemoryContentTable, OpIndex, KeyData >::NewKey(), ResolveBase(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< WasmMemoryContentTable, OpIndex, KeyData >::Set(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< WasmMemoryContentTable, OpIndex, KeyData >::SetNoNotify(), size(), and v8::internal::value.
InsertLoadLike()
void v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::InsertLoadLike (OpIndex base_idx, int offset_sentinel, OpIndex value_idx) [inline]
Definition at line 263 of file wasm-load-elimination-reducer.h.
                                         {
    OpIndex base = ResolveBase(base_idx);
    static constexpr bool mutability = false;
    Insert(base, offset_sentinel, kLoadLikeType, kLoadLikeSize, mutability,
           value_idx);
  }
References Insert(), v8::internal::compiler::turboshaft::wle::kLoadLikeSize, v8::internal::compiler::turboshaft::wle::kLoadLikeType, and ResolveBase().
Referenced by v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAnyConvertExtern(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessArrayLength(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAssertNotNull(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStringAsWtf16(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStringPrepareForGetCodeUnit(), and v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessWasmAllocateArray().
Invalidate() [1/3]
void v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::Invalidate (const StructAtomicRMWOp & rmw_op) [inline]
Definition at line 176 of file wasm-load-elimination-reducer.h.
                                                   {
    Invalidate(field_offset(rmw_op.type, rmw_op.field_index),
               rmw_op.type_index);
  }
References field_offset(), and Invalidate().
Invalidate() [2/3]
void v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::Invalidate (const StructSetOp & set) [inline]
Definition at line 172 of file wasm-load-elimination-reducer.h.
                                          {
    Invalidate(field_offset(set.type, set.field_index), set.type_index);
  }
References field_offset(), and Invalidate().
Invalidate() [3/3]
void v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::Invalidate (int offset, wasm::ModuleTypeIndex type_index) [inline]
Definition at line 143 of file wasm-load-elimination-reducer.h.
                                                              {
    // This is like LateLoadElimination's {InvalidateAtOffset}, but based
    // on Wasm types instead of tracked JS maps.
    auto offset_keys = offset_keys_.find(offset);
    if (offset_keys == offset_keys_.end()) return;
    for (auto it = offset_keys->second.begin();
         it != offset_keys->second.end();) {
      Key key = *it;
      DCHECK_EQ(offset, key.data().mem.offset);
      OpIndex base = key.data().mem.base;
      // If the base is guaranteed non-aliasing, we don't need to clear any
      // other entries. Any existing entry for this base will be overwritten
      // by {Insert(set)}.
      if (non_aliasing_objects_.Get(base)) {
        ++it;
        continue;
      }
      if (TypesUnrelated(type_index, key.data().mem.type_index)) {
        ++it;
        continue;
      }
      it = offset_keys->second.RemoveAt(it);
      Set(key, OpIndex::Invalid());
    }
  }
References DCHECK_EQ, v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::key, non_aliasing_objects_, offset_keys_, v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< WasmMemoryContentTable, OpIndex, KeyData >::Set(), and TypesUnrelated().
Referenced by Invalidate(), and v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStructSet().
InvalidateMaybeAliasing()
template<EntriesWithOffsets offsets = EntriesWithOffsets::kInvalidate>
void v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::InvalidateMaybeAliasing () [inline]
Definition at line 184 of file wasm-load-elimination-reducer.h.
                                 {
    // We find current active keys through {base_keys_} so that we can bail out
    // for whole buckets non-aliasing buckets (if we had gone through
    // {offset_keys_} instead, then for each key we would've had to check
    // whether it was non-aliasing or not).
    for (auto& base_keys : base_keys_) {
      OpIndex base = base_keys.first;
      if (non_aliasing_objects_.Get(base)) continue;
      if constexpr (offsets == EntriesWithOffsets::kInvalidate) {
        for (auto it = base_keys.second.with_offsets.begin();
             it != base_keys.second.with_offsets.end();) {
          Key key = *it;
          if (key.data().mem.mutability == false) {
            ++it;
            continue;
          }
          // It's important to remove with RemoveAt before Setting the key to
          // invalid, otherwise OnKeyChange will remove {key} from {base_keys},
          // which will invalidate {it}.
          it = base_keys.second.with_offsets.RemoveAt(it);
          Set(key, OpIndex::Invalid());
        }
      }
    }
  }
References base_keys_, v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::key, kInvalidate, non_aliasing_objects_, and v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< WasmMemoryContentTable, OpIndex, KeyData >::Set().
Referenced by v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessCall().
OnNewKey()
void v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::OnNewKey (Key key, OpIndex value) [inline]
Definition at line 120 of file wasm-load-elimination-reducer.h.
                                        {
    if (value.valid()) {
      AddKeyInBaseOffsetMaps(key);
    }
  }
References AddKeyInBaseOffsetMaps(), v8::internal::key, and v8::internal::value.
OnValueChange()
void v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::OnValueChange (Key key, OpIndex old_value, OpIndex new_value) [inline]
Definition at line 126 of file wasm-load-elimination-reducer.h.
                                                                    {
    DCHECK_NE(old_value, new_value);
    if (old_value.valid() && !new_value.valid()) {
      RemoveKeyFromBaseOffsetMaps(key);
    } else if (new_value.valid() && !old_value.valid()) {
      AddKeyInBaseOffsetMaps(key);
    } else {
      DCHECK_EQ(new_value.valid(), old_value.valid());
    }
  }
References AddKeyInBaseOffsetMaps(), DCHECK_EQ, DCHECK_NE, v8::internal::key, RemoveKeyFromBaseOffsetMaps(), and v8::internal::compiler::turboshaft::OpIndex::valid().
RemoveKeyFromBaseOffsetMaps()
void v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::RemoveKeyFromBaseOffsetMaps (Key key) [inline]
Definition at line 355 of file wasm-load-elimination-reducer.h.
                                            {
    // Removing from {base_keys_}.
    v8::base::DoublyThreadedList<Key, BaseListTraits>::Remove(key);
    v8::base::DoublyThreadedList<Key, OffsetListTraits>::Remove(key);
  }
References v8::internal::key, and v8::base::DoublyThreadedList< T, DTLTraits >::Remove().
Referenced by OnValueChange().
ResolveBase()
OpIndex v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::ResolveBase (OpIndex base) [inline]
Definition at line 311 of file wasm-load-elimination-reducer.h.
                                    {
    while (true) {
      if (replacements_[base] != OpIndex::Invalid()) {
        base = replacements_[base];
        continue;
      }
      Operation& op = graph_.Get(base);
      if (AssertNotNullOp* check = op.TryCast<AssertNotNullOp>()) {
        base = check->object();
        continue;
      }
      if (WasmTypeCastOp* cast = op.TryCast<WasmTypeCastOp>()) {
        base = cast->object();
        continue;
      }
      break; // Terminate if nothing happened.
    }
    return base;
  }
References v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::OpIndex::Invalid(), replacements_, and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by Find(), FindLoadLike(), HasValueWithIncorrectMutability(), Insert(), InsertLoadLike(), and v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessPhi().
TypesUnrelated()
bool v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::TypesUnrelated (wasm::ModuleTypeIndex type1, wasm::ModuleTypeIndex type2) [inline]
Definition at line 137 of file wasm-load-elimination-reducer.h.
                                                 {
    return wasm::HeapTypesUnrelated(module_->heap_type(type1),
                                    module_->heap_type(type2), module_);
  }
References v8::internal::wasm::WasmModule::heap_type(), v8::internal::wasm::HeapTypesUnrelated(), and module_.
Referenced by Invalidate().
Member Data Documentation
all_keys_
ZoneUnorderedMap<WasmMemoryAddress, Key> v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::all_keys_
Definition at line 374 of file wasm-load-elimination-reducer.h.
Referenced by FindImpl(), HasValueWithIncorrectMutability(), and Insert().
base_keys_
ZoneUnorderedMap<OpIndex, BaseData> v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::base_keys_
Definition at line 376 of file wasm-load-elimination-reducer.h.
Referenced by AddKeyInBaseOffsetMaps(), and InvalidateMaybeAliasing().
data_
PipelineData* v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::data_
Definition at line 364 of file wasm-load-elimination-reducer.h.
graph_
Graph& v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::graph_
Definition at line 365 of file wasm-load-elimination-reducer.h.
Referenced by ResolveBase().
module_
const wasm::WasmModule* v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::module_ = data_->wasm_module()
Definition at line 367 of file wasm-load-elimination-reducer.h.
Referenced by TypesUnrelated().
non_aliasing_objects_
SparseOpIndexSnapshotTable<bool>& v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::non_aliasing_objects_
Definition at line 361 of file wasm-load-elimination-reducer.h.
Referenced by Invalidate(), and InvalidateMaybeAliasing().
offset_keys_
ZoneUnorderedMap<int, v8::base::DoublyThreadedList<Key, OffsetListTraits> > v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::offset_keys_
Definition at line 379 of file wasm-load-elimination-reducer.h.
Referenced by AddKeyInBaseOffsetMaps(), and Invalidate().
replacements_
FixedOpIndexSidetable<OpIndex>& v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::replacements_
Definition at line 362 of file wasm-load-elimination-reducer.h.
Referenced by ResolveBase().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-load-elimination-reducer.h