v8::internal::wasm::LoadType Class Reference
#include <value-type.h>
Public Types
enum LoadTypeValue : uint8_t
Public Member Functions
constexpr LoadType (LoadTypeValue val)
constexpr LoadTypeValue value () const
constexpr uint8_t size_log_2 () const
constexpr uint8_t size () const
constexpr ValueType value_type () const
constexpr MachineType mem_type () const
Static Public Member Functions
static LoadType ForValueKind (ValueKind kind, bool is_signed=false)
Private Attributes
LoadTypeValue val_
Static Private Attributes
static constexpr uint8_t kLoadSize []
static constexpr uint8_t kLoadSizeLog2 []
static constexpr ValueType kValueType []
static constexpr MachineType kMemType []
Detailed Description
Definition at line 1341 of file value-type.h.
Member Enumeration Documentation
LoadTypeValue
enum v8::internal::wasm::LoadType::LoadTypeValue : uint8_t
Definition at line 1343 of file value-type.h.
                     : uint8_t {
#define DEF_ENUM(type, suffix, ...) k##type##Load##suffix,
    FOREACH_LOAD_TYPE(DEF_ENUM)
#undef DEF_ENUM
  };
Constructor & Destructor Documentation
LoadType()
constexpr v8::internal::wasm::LoadType::LoadType (LoadTypeValue val) [inline], [constexpr]
Definition at line 1351 of file value-type.h.
: val_(val) {}
Member Function Documentation
ForValueKind()
static LoadType v8::internal::wasm::LoadType::ForValueKind (ValueKind kind, bool is_signed = false) [inline], [static]
Definition at line 1359 of file value-type.h.
                                                                       {
    switch (kind) {
      case kI32:
        return kI32Load;
      case kI64:
        return kI64Load;
      case kF32:
        return kF32Load;
      case kF64:
        return kF64Load;
      case kS128:
        return kS128Load;
      case kI8:
        return is_signed ? kI32Load8S : kI32Load8U;
      case kI16:
        return is_signed ? kI32Load16S : kI32Load16U;
      case kF16:
        return kF32LoadF16;
      default:
        UNREACHABLE();
    }
  }
References v8::internal::is_signed(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::kS128, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GlobalGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadAtomicObjectField(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadObjectField().
mem_type()
constexpr MachineType v8::internal::wasm::LoadType::mem_type () const [inline], [constexpr]
Definition at line 1357 of file value-type.h.
{ return kMemType[val_]; }
References kMemType, and val_.
size()
constexpr uint8_t v8::internal::wasm::LoadType::size () const [inline], [constexpr]
Definition at line 1355 of file value-type.h.
{ return kLoadSize[val_]; }
References kLoadSize, and val_.
size_log_2()
constexpr uint8_t v8::internal::wasm::LoadType::size_log_2 () const [inline], [constexpr]
Definition at line 1354 of file value-type.h.
{ return kLoadSizeLog2[val_]; }
References kLoadSizeLog2, and val_.
value()
constexpr LoadTypeValue v8::internal::wasm::LoadType::value () const [inline], [constexpr]
Definition at line 1353 of file value-type.h.
{ return val_; }
References val_.
value_type()
constexpr ValueType v8::internal::wasm::LoadType::value_type () const [inline], [constexpr]
Definition at line 1356 of file value-type.h.
{ return kValueType[val_]; }
References kValueType, and val_.
Member Data Documentation
kLoadSize
constexpr uint8_t v8::internal::wasm::LoadType::kLoadSize[] [static], [constexpr], [private]
Initial value:
= {
  
#define LOAD_SIZE(_, __, memtype)
  }
Definition at line 1385 of file value-type.h.
Referenced by size().
kLoadSizeLog2
constexpr uint8_t v8::internal::wasm::LoadType::kLoadSizeLog2 [static], [constexpr], [private]
Initial value:
= {
  
#define LOAD_SIZE(_, __, memtype)
  }
Definition at line 1394 of file value-type.h.
Referenced by size_log_2().
kMemType
constexpr MachineType v8::internal::wasm::LoadType::kMemType [static], [constexpr], [private]
Initial value:
= {
#define MEMTYPE(_, __, memtype)
  }
Definition at line 1409 of file value-type.h.
Referenced by mem_type().
kValueType
constexpr ValueType v8::internal::wasm::LoadType::kValueType [static], [constexpr], [private]
Initial value:
= {
#define VALUE_TYPE(type, ...)
  }
Definition at line 1403 of file value-type.h.
Referenced by value_type().
val_
LoadTypeValue v8::internal::wasm::LoadType::val_ [private]
Definition at line 1383 of file value-type.h.
Referenced by mem_type(), size(), size_log_2(), value(), and value_type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/value-type.h
/mnt/V8SourceCode/src/wasm/wasm-opcodes.cc