v8::internal::compiler::turboshaft::RegisterRepresentation Class Reference
#include <representations.h>
Public Types
enum class Enum : uint8_t {
kWord32 = static_cast<int>(MaybeRegisterRepresentation::Enum::kWord32)
, kWord64 = static_cast<int>(MaybeRegisterRepresentation::Enum::kWord64)
, kFloat32 = static_cast<int>(MaybeRegisterRepresentation::Enum::kFloat32)
, kFloat64 = static_cast<int>(MaybeRegisterRepresentation::Enum::kFloat64)
,
kTagged = static_cast<int>(MaybeRegisterRepresentation::Enum::kTagged)
, kCompressed
, kSimd128 = static_cast<int>(MaybeRegisterRepresentation::Enum::kSimd128)
, kSimd256 = static_cast<int>(MaybeRegisterRepresentation::Enum::kSimd256)
 }
Public Member Functions
constexpr RegisterRepresentation (Enum value)
RegisterRepresentation ()=default
constexpr RegisterRepresentation (MaybeRegisterRepresentation rep)
constexpr operator Enum () const
constexpr Enum value () const
constexpr bool AllowImplicitRepresentationChangeTo (RegisterRepresentation dst_rep, bool graph_created_from_turbofan) const
constexpr RegisterRepresentation MapTaggedToWord () const
Static Public Member Functions
static constexpr RegisterRepresentation Word32 ()
static constexpr RegisterRepresentation Word64 ()
static constexpr RegisterRepresentation WordPtr ()
static constexpr RegisterRepresentation Float32 ()
static constexpr RegisterRepresentation Float64 ()
static constexpr RegisterRepresentation Tagged ()
static constexpr RegisterRepresentation Compressed ()
static constexpr RegisterRepresentation Simd128 ()
static constexpr RegisterRepresentation Simd256 ()
static constexpr RegisterRepresentation FromMachineRepresentation (MachineRepresentation rep)
static constexpr RegisterRepresentation FromMachineType (MachineType type)
static constexpr RegisterRepresentation FromCTypeInfo (CTypeInfo t, CFunctionInfo::Int64Representation int64_repr)
Detailed Description
Definition at line 210 of file representations.h.
Member Enumeration Documentation
Enum
enum v8::internal::compiler::turboshaft::RegisterRepresentation::Enum : uint8_t [strong]
Enumerator
kWord32
kWord64
kFloat32
kFloat64
kTagged
kCompressed
kSimd128
kSimd256
Definition at line 212 of file representations.h.
                  : uint8_t {
    kWord32 = static_cast<int>(MaybeRegisterRepresentation::Enum::kWord32),
    kWord64 = static_cast<int>(MaybeRegisterRepresentation::Enum::kWord64),
    kFloat32 = static_cast<int>(MaybeRegisterRepresentation::Enum::kFloat32),
    kFloat64 = static_cast<int>(MaybeRegisterRepresentation::Enum::kFloat64),
    kTagged = static_cast<int>(MaybeRegisterRepresentation::Enum::kTagged),
    kCompressed =
        static_cast<int>(MaybeRegisterRepresentation::Enum::kCompressed),
    kSimd128 = static_cast<int>(MaybeRegisterRepresentation::Enum::kSimd128),
    kSimd256 = static_cast<int>(MaybeRegisterRepresentation::Enum::kSimd256),
  };
Constructor & Destructor Documentation
RegisterRepresentation() [1/3]
constexpr v8::internal::compiler::turboshaft::RegisterRepresentation::RegisterRepresentation (Enum value) [inline], [explicit], [constexpr]
Definition at line 224 of file representations.h.
      : MaybeRegisterRepresentation(
            static_cast<MaybeRegisterRepresentation::Enum>(value)) {}
RegisterRepresentation() [2/3]
v8::internal::compiler::turboshaft::RegisterRepresentation::RegisterRepresentation () [default]
Referenced by Compressed(), Float32(), Float64(), Simd128(), Simd256(), Tagged(), Word32(), Word64(), and WordPtr().
RegisterRepresentation() [3/3]
constexpr v8::internal::compiler::turboshaft::RegisterRepresentation::RegisterRepresentation (MaybeRegisterRepresentation rep) [inline], [explicit], [constexpr]
Definition at line 229 of file representations.h.
      : RegisterRepresentation(static_cast<Enum>(rep.value())) {}
Member Function Documentation
AllowImplicitRepresentationChangeTo()
constexpr bool v8::internal::compiler::turboshaft::RegisterRepresentation::AllowImplicitRepresentationChangeTo (RegisterRepresentation dst_rep, bool graph_created_from_turbofan) const [constexpr]
Definition at line 362 of file representations.h.
                                                                            {
  if (*this == dst_rep) {
    return true;
  }
  switch (dst_rep.value()) {
    case RegisterRepresentation::Word32():
      // We allow implicit tagged -> untagged conversions.
      // Even without pointer compression, we use `Word32And` for Smi-checks on
      // tagged values.
      if (*this == any_of(RegisterRepresentation::Tagged(),
                          RegisterRepresentation::Compressed())) {
        return true;
      }
      if (graph_created_from_turbofan &&
          *this == RegisterRepresentation::Word64()) {
        // TODO(12783): Remove this once Turboshaft graphs are not constructed
        // via Turbofan any more. Unfortunately Turbofan has many implicit
        // truncations which are hard to fix. Still, for wasm it is required
        // that truncations in Turboshaft are explicit.
        return true;
      }
      break;
    case RegisterRepresentation::Word64():
      // We allow implicit tagged -> untagged conversions.
      if (kTaggedSize == kInt64Size &&
          *this == RegisterRepresentation::Tagged()) {
        return true;
      }
      break;
    case RegisterRepresentation::Tagged():
      // We allow implicit untagged -> tagged conversions. This is only safe for
      // Smi values.
      if (*this == RegisterRepresentation::WordPtr()) {
        return true;
      }
      break;
    case RegisterRepresentation::Compressed():
      // Compression is a no-op.
      if (*this == any_of(RegisterRepresentation::Tagged(),
                          RegisterRepresentation::WordPtr(),
                          RegisterRepresentation::Word32())) {
        return true;
      }
      break;
    default:
      break;
  }
  return false;
}
References v8::internal::compiler::turboshaft::any_of(), Compressed(), v8::internal::kInt64Size, v8::internal::kTaggedSize, Tagged(), value(), Word32(), Word64(), and WordPtr().
Compressed()
static constexpr RegisterRepresentation v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed () [inline], [static], [constexpr]
Definition at line 262 of file representations.h.
                                                       {
    return RegisterRepresentation(Enum::kCompressed);
  }
References kCompressed, and RegisterRepresentation().
Referenced by AllowImplicitRepresentationChangeTo(), v8::internal::compiler::turboshaft::v_traits< Compressed >::allows_representation(), FromMachineRepresentation(), v8::internal::compiler::turboshaft::MemoryRepresentation::FromRegisterRepresentation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert(), v8::internal::compiler::turboshaft::LoadOp::machine_type(), v8::internal::compiler::turboshaft::ConstantOp::Representation(), v8::internal::compiler::turboshaft::RunDecompressionOptimization(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToRegisterRepresentationForStore(), v8::internal::compiler::turboshaft::Typer::TypeComparison(), v8::internal::compiler::turboshaft::Typer::TypeForRepresentation(), v8::internal::compiler::turboshaft::ComparisonOp::Validate(), v8::internal::compiler::turboshaft::TaggedBitcastOp::Validate(), v8::internal::compiler::turboshaft::LoadOp::Validate(), v8::internal::compiler::turboshaft::FrameStateOp::Validate(), and v8::internal::compiler::turboshaft::VectorForRep().
Float32()
static constexpr RegisterRepresentation v8::internal::compiler::turboshaft::RegisterRepresentation::Float32 () [inline], [static], [constexpr]
Definition at line 249 of file representations.h.
                                                    {
    return RegisterRepresentation(Enum::kFloat32);
  }
References kFloat32, and RegisterRepresentation().
Referenced by v8::internal::compiler::turboshaft::v_traits< Float32 >::allows_representation(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), FromMachineRepresentation(), v8::internal::compiler::turboshaft::MemoryRepresentation::FromRegisterRepresentation(), v8::internal::compiler::turboshaft::GetFlagsCondition(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::turboshaft::CompareSequence::GetOpcode(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsFloat32ConvertedToFloat64(), v8::internal::compiler::turboshaft::ChangeOp::IsReversible(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::RegisterRepresentationForArrayType(), v8::internal::compiler::turboshaft::ConstantOp::Representation(), v8::internal::wasm::WasmGraphBuilderBase::RepresentationFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToRegisterRepresentation(), v8::internal::compiler::turboshaft::Typer::TypeComparison(), v8::internal::compiler::turboshaft::Typer::TypeForRepresentation(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoFloat32ToFloat64Conversion(), v8::internal::compiler::turboshaft::ComparisonOp::Validate(), v8::internal::compiler::turboshaft::SelectOp::Validate(), v8::internal::compiler::turboshaft::VectorForRep(), and v8::internal::compiler::InstructionSelector::VisitWordCompareZero().
Float64()
static constexpr RegisterRepresentation v8::internal::compiler::turboshaft::RegisterRepresentation::Float64 () [inline], [static], [constexpr]
Definition at line 252 of file representations.h.
                                                    {
    return RegisterRepresentation(Enum::kFloat64);
  }
References kFloat64, and RegisterRepresentation().
Referenced by v8::internal::compiler::turboshaft::v_traits< Float64 >::allows_representation(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Change(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertFloat64ToNumber(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertUntaggedToJSPrimitive(), v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::ConvertUntaggedToJSPrimitiveOp(), v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >::DebugPrint(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DebugPrint(), FromCTypeInfo(), FromMachineRepresentation(), v8::internal::compiler::turboshaft::MemoryRepresentation::FromRegisterRepresentation(), v8::internal::compiler::turboshaft::GetFlagsCondition(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::turboshaft::CompareSequence::GetOpcode(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsFloat32ConvertedToFloat64(), v8::internal::compiler::turboshaft::ChangeOp::IsReversible(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineTypes(), v8::internal::compiler::turboshaft::RegisterRepresentationForArrayType(), v8::internal::compiler::turboshaft::ConstantOp::Representation(), v8::internal::wasm::WasmGraphBuilderBase::RepresentationFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToRegisterRepresentation(), v8::internal::compiler::turboshaft::Typer::TypeComparison(), v8::internal::compiler::turboshaft::Typer::TypeForRepresentation(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoFloat32ToFloat64Conversion(), v8::internal::compiler::turboshaft::ComparisonOp::Validate(), v8::internal::compiler::turboshaft::SelectOp::Validate(), v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::Validate(), v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::value_representation(), v8::internal::compiler::turboshaft::VectorForRep(), and v8::internal::compiler::InstructionSelector::VisitWordCompareZero().
FromCTypeInfo()
static constexpr RegisterRepresentation v8::internal::compiler::turboshaft::RegisterRepresentation::FromCTypeInfo (CTypeInfo t, CFunctionInfo::Int64Representation int64_repr) [inline], [static], [constexpr]
Definition at line 318 of file representations.h.
                                                                {
    if (t.GetType() == CTypeInfo::Type::kVoid ||
        t.GetType() == CTypeInfo::Type::kPointer) {
      return RegisterRepresentation::Tagged();
    } else if (t.GetType() == CTypeInfo::Type::kInt64 ||
               t.GetType() == CTypeInfo::Type::kUint64) {
      if (int64_repr == CFunctionInfo::Int64Representation::kBigInt) {
        return RegisterRepresentation::Word64();
      } else {
        DCHECK_EQ(int64_repr, CFunctionInfo::Int64Representation::kNumber);
        return RegisterRepresentation::Float64();
      }
    } else {
      return RegisterRepresentation::FromMachineType(
          MachineType::TypeForCType(t));
    }
  }
References DCHECK_EQ, Float64(), FromMachineType(), v8::CTypeInfo::GetType(), v8::CFunctionInfo::kBigInt, v8::CTypeInfo::kInt64, v8::CFunctionInfo::kNumber, v8::CTypeInfo::kPointer, v8::CTypeInfo::kUint64, v8::CTypeInfo::kVoid, Tagged(), v8::internal::MachineType::TypeForCType(), and Word64().
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
FromMachineRepresentation()
static constexpr RegisterRepresentation v8::internal::compiler::turboshaft::RegisterRepresentation::FromMachineRepresentation (MachineRepresentation rep) [inline], [static], [constexpr]
Definition at line 272 of file representations.h.
                                 {
    switch (rep) {
      case MachineRepresentation::kBit:
      case MachineRepresentation::kWord8:
      case MachineRepresentation::kWord16:
      case MachineRepresentation::kWord32:
        return Word32();
      case MachineRepresentation::kWord64:
        return Word64();
      case MachineRepresentation::kTaggedSigned:
      case MachineRepresentation::kTaggedPointer:
      case MachineRepresentation::kTagged:
      case MachineRepresentation::kProtectedPointer:
        return Tagged();
      case MachineRepresentation::kCompressedPointer:
      case MachineRepresentation::kCompressed:
        return Compressed();
      case MachineRepresentation::kFloat16:
      case MachineRepresentation::kFloat32:
        return Float32();
      case MachineRepresentation::kFloat64:
        return Float64();
      case MachineRepresentation::kSimd128:
        return Simd128();
      case MachineRepresentation::kSimd256:
        return Simd256();
      case MachineRepresentation::kMapWord:
        // Turboshaft does not support map packing.
        DCHECK(!V8_MAP_PACKING_BOOL);
        return RegisterRepresentation::Tagged();
      case MachineRepresentation::kIndirectPointer:
      case MachineRepresentation::kSandboxedPointer:
        // TODO(saelo/jkummerow): This is suspicious: after resolving the
        // indirection, we have a Tagged pointer.
        return WordPtr();
      case MachineRepresentation::kNone:
      case MachineRepresentation::kFloat16RawBits:
        UNREACHABLE();
    }
  }
References Compressed(), v8::internal::DCHECK(), Float32(), Float64(), v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::kProtectedPointer, v8::internal::kSandboxedPointer, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, Simd128(), Simd256(), Tagged(), v8::internal::UNREACHABLE(), V8_MAP_PACKING_BOOL, Word32(), Word64(), and WordPtr().
Referenced by v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), FromMachineType(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::FrameStateOp::state_value_rep(), and v8::internal::compiler::turboshaft::FrameStateOp::Validate().
FromMachineType()
static constexpr RegisterRepresentation v8::internal::compiler::turboshaft::RegisterRepresentation::FromMachineType (MachineType type) [inline], [static], [constexpr]
Definition at line 314 of file representations.h.
                                                                            {
    return FromMachineRepresentation(type.representation());
  }
References FromMachineRepresentation(), and v8::internal::tracing::type.
Referenced by v8::internal::BuiltinsReducer< Next >::EmitBuiltinProlog(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState(), FromCTypeInfo(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
MapTaggedToWord()
constexpr RegisterRepresentation v8::internal::compiler::turboshaft::RegisterRepresentation::MapTaggedToWord () const [inline], [constexpr]
Definition at line 340 of file representations.h.
                                                           {
    if (this->value() == RegisterRepresentation::Tagged()) {
      return COMPRESS_POINTERS_BOOL ? RegisterRepresentation::Word32()
                                    : RegisterRepresentation::WordPtr();
    }
    return *this;
  }
References COMPRESS_POINTERS_BOOL, Tagged(), value(), Word32(), and WordPtr().
Referenced by v8::internal::compiler::turboshaft::CompareSequence::GetOpcode().
operator Enum()
constexpr v8::internal::compiler::turboshaft::RegisterRepresentation::operator Enum () const [inline], [constexpr]
Definition at line 232 of file representations.h.
{ return value(); }
References value().
Simd128()
static constexpr RegisterRepresentation v8::internal::compiler::turboshaft::RegisterRepresentation::Simd128 () [inline], [static], [constexpr]
Definition at line 265 of file representations.h.
                                                    {
    return RegisterRepresentation(Enum::kSimd128);
  }
References kSimd128, and RegisterRepresentation().
Referenced by v8::internal::compiler::turboshaft::v_traits< Simd128 >::allows_representation(), v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::FixLoopPhi(), FromMachineRepresentation(), v8::internal::compiler::turboshaft::MemoryRepresentation::FromRegisterRepresentation(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Phi(), v8::internal::wasm::WasmGraphBuilderBase::RepresentationFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), v8::internal::compiler::turboshaft::WasmShuffleReducer< Next >::Simd128Shuffle(), v8::internal::compiler::turboshaft::Simd128UseMap::Simd128UseMap(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToRegisterRepresentation(), v8::internal::compiler::turboshaft::Typer::TypeComparison(), and v8::internal::compiler::turboshaft::Typer::TypeForRepresentation().
Simd256()
static constexpr RegisterRepresentation v8::internal::compiler::turboshaft::RegisterRepresentation::Simd256 () [inline], [static], [constexpr]
Definition at line 268 of file representations.h.
                                                    {
    return RegisterRepresentation(Enum::kSimd256);
  }
References kSimd256, and RegisterRepresentation().
Referenced by v8::internal::compiler::turboshaft::v_traits< Simd256 >::allows_representation(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::FixLoopPhi(), FromMachineRepresentation(), v8::internal::compiler::turboshaft::MemoryRepresentation::FromRegisterRepresentation(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Phi(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToRegisterRepresentation(), v8::internal::compiler::turboshaft::Typer::TypeComparison(), and v8::internal::compiler::turboshaft::Typer::TypeForRepresentation().
Tagged()
static constexpr RegisterRepresentation v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged () [inline], [static], [constexpr]
Definition at line 257 of file representations.h.
                                                   {
    return RegisterRepresentation(Enum::kTagged);
  }
References kTagged, and RegisterRepresentation().
Referenced by v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Allocate(), AllowImplicitRepresentationChangeTo(), v8::internal::compiler::turboshaft::v_traits< T, std::enable_if_t< is_taggable_v< T > &&!is_union_v< T > > >::allows_representation(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArrayAtomicRMW(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::AtomicRMW(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::BitcastTaggedToWordPtrForTagAndSmiBits(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::compiler::turboshaft::GenericReducerBase< Next >::CatchBlockBegin(), v8::internal::compiler::InstructionSelector::ConsumeEqualZero(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ConvertWord32ToJSBool(), v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >::DebugPrint(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DebugPrint(), FromCTypeInfo(), FromMachineRepresentation(), v8::internal::compiler::turboshaft::MemoryRepresentation::FromRegisterRepresentation(), v8::internal::compiler::turboshaft::GetFlagsCondition(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::turboshaft::StoreOp::inputs_rep(), v8::internal::compiler::turboshaft::StoreTypedElementOp::inputs_rep(), v8::internal::compiler::turboshaft::StoreDataViewElementOp::inputs_rep(), v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::inputs_rep(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert(), v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::Load(), MapTaggedToWord(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessGraph(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::ConstantOp::Representation(), v8::internal::wasm::WasmGraphBuilderBase::RepresentationFor(), v8::internal::compiler::turboshaft::RunDecompressionOptimization(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructAtomicRMW(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TaggedBitcast(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TaggedEqual(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToRegisterRepresentation(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToRegisterRepresentationForStore(), v8::internal::compiler::turboshaft::Typer::TypeComparison(), v8::internal::compiler::turboshaft::Typer::TypeForRepresentation(), v8::internal::compiler::turboshaft::ComparisonOp::Validate(), v8::internal::compiler::turboshaft::ChangeOp::Validate(), v8::internal::compiler::turboshaft::TaggedBitcastOp::Validate(), v8::internal::compiler::turboshaft::AtomicRMWOp::Validate(), v8::internal::compiler::turboshaft::FrameStateOp::Validate(), v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::value_representation(), v8::internal::compiler::turboshaft::ValueNeedsWriteBarrier(), v8::internal::compiler::turboshaft::VectorForRep(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64EqualImpl().
value()
constexpr Enum v8::internal::compiler::turboshaft::RegisterRepresentation::value () const [inline], [constexpr]
Definition at line 234 of file representations.h.
                               {
    return static_cast<Enum>(MaybeRegisterRepresentation::value());
  }
References v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::value().
Referenced by AllowImplicitRepresentationChangeTo(), v8::internal::compiler::turboshaft::MemoryRepresentation::FromRegisterRepresentation(), v8::internal::compiler::turboshaft::CompareSequence::GetOpcode(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert(), v8::internal::compiler::turboshaft::IsValidTypeFor(), MapTaggedToWord(), operator Enum(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::InputsRepFactory::ToMaybeRepPointer(), v8::internal::compiler::turboshaft::Typer::TypeComparison(), v8::internal::compiler::turboshaft::Typer::TypeForRepresentation(), v8::internal::compiler::turboshaft::WordRepresentation::value(), v8::internal::compiler::turboshaft::FloatRepresentation::value(), and v8::internal::compiler::turboshaft::VectorForRep().
Word32()
static constexpr RegisterRepresentation v8::internal::compiler::turboshaft::RegisterRepresentation::Word32 () [inline], [static], [constexpr]
Definition at line 238 of file representations.h.
                                                   {
    return RegisterRepresentation(Enum::kWord32);
  }
References kWord32, and RegisterRepresentation().
Referenced by AllowImplicitRepresentationChangeTo(), v8::internal::compiler::turboshaft::v_traits< Word32 >::allows_representation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicOp(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::AtomicRMW(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Change(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::CheckPairOrPairOp(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ComputeTypeForPhi(), v8::internal::compiler::InstructionSelector::ConsumeEqualZero(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertUntaggedToJSPrimitive(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertUntaggedToJSPrimitiveOrDeopt(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::EmitLoopSinglePredecessorBlock(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FixLoopPhi(), FromMachineRepresentation(), v8::internal::compiler::turboshaft::MemoryRepresentation::FromRegisterRepresentation(), v8::internal::compiler::turboshaft::GetFlagsCondition(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::turboshaft::CompareSequence::GetOpcode(), v8::internal::compiler::turboshaft::ShiftOp::inputs_rep(), v8::internal::compiler::turboshaft::SelectOp::inputs_rep(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::inputs_rep(), v8::internal::compiler::turboshaft::StoreDataViewElementOp::inputs_rep(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert(), v8::internal::compiler::turboshaft::ChangeOp::IsReversible(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Load(), v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::Load(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), MapTaggedToWord(), v8::internal::compiler::turboshaft::OperationMatcher::MatchTruncateWord64ToWord32(), v8::internal::compiler::turboshaft::FastApiCallOp::options(), v8::internal::compiler::turboshaft::Word32PairBinopOp::outputs_rep(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::outputs_rep(), v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::outputs_rep(), v8::internal::compiler::turboshaft::TryChangeOp::outputs_rep(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::outputs_rep(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Parameter(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Phi(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessGraph(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::ExplicitTruncationReducer< Next >::ReduceOperation(), v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineTypes(), v8::internal::compiler::turboshaft::RegisterRepresentationForArrayType(), v8::internal::compiler::turboshaft::ConstantOp::Representation(), v8::internal::wasm::WasmGraphBuilderBase::RepresentationFor(), v8::internal::compiler::turboshaft::RunDecompressionOptimization(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TaggedBitcast(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToRegisterRepresentation(), v8::internal::compiler::turboshaft::Typer::TypeComparison(), v8::internal::compiler::turboshaft::Typer::TypeForRepresentation(), v8::internal::compiler::turboshaft::ComparisonOp::Validate(), v8::internal::compiler::turboshaft::TaggedBitcastOp::Validate(), v8::internal::compiler::turboshaft::SelectOp::Validate(), v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::Validate(), v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::value_representation(), v8::internal::compiler::turboshaft::VectorForRep(), v8::internal::compiler::InstructionSelector::VisitNode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWord32Compare(), and v8::internal::compiler::InstructionSelector::VisitWordCompareZero().
Word64()
static constexpr RegisterRepresentation v8::internal::compiler::turboshaft::RegisterRepresentation::Word64 () [inline], [static], [constexpr]
Definition at line 241 of file representations.h.
                                                   {
    return RegisterRepresentation(Enum::kWord64);
  }
References kWord64, and RegisterRepresentation().
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor(), AllowImplicitRepresentationChangeTo(), v8::internal::compiler::turboshaft::v_traits< Word64 >::allows_representation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicOp(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::AtomicRMW(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Change(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertUntaggedToJSPrimitive(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertUntaggedToJSPrimitiveOrDeopt(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState(), FromCTypeInfo(), FromMachineRepresentation(), v8::internal::compiler::turboshaft::MemoryRepresentation::FromRegisterRepresentation(), v8::internal::compiler::turboshaft::GetFlagsCondition(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::turboshaft::CompareSequence::GetOpcode(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert(), v8::internal::compiler::turboshaft::ChangeOp::IsReversible(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Load(), v8::internal::compiler::turboshaft::OperationMatcher::MatchTruncateWord64ToWord32(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::outputs_rep(), v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::outputs_rep(), v8::internal::compiler::turboshaft::TryChangeOp::outputs_rep(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Parameter(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::PendingLoopPhi(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Phi(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::ExplicitTruncationReducer< Next >::ReduceOperation(), v8::internal::compiler::turboshaft::RegisterRepresentationForArrayType(), v8::internal::compiler::turboshaft::ConstantOp::Representation(), v8::internal::wasm::WasmGraphBuilderBase::RepresentationFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TaggedBitcast(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToRegisterRepresentation(), v8::internal::compiler::turboshaft::Typer::TypeComparison(), v8::internal::compiler::turboshaft::Typer::TypeForRepresentation(), v8::internal::compiler::turboshaft::ComparisonOp::Validate(), v8::internal::compiler::turboshaft::TaggedBitcastOp::Validate(), v8::internal::compiler::turboshaft::SelectOp::Validate(), v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::Validate(), v8::internal::compiler::turboshaft::VectorForRep(), v8::internal::compiler::InstructionSelector::VisitNode(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::WordUnary().
WordPtr()
static constexpr RegisterRepresentation v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr () [inline], [static], [constexpr]
Definition at line 246 of file representations.h.
                                                    {
    return RegisterRepresentation(MaybeRegisterRepresentation::WordPtr());
  }
References RegisterRepresentation(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::WordPtr().
Referenced by AllowImplicitRepresentationChangeTo(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicOp(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::BitcastTaggedToWordPtrForTagAndSmiBits(), v8::internal::wasm::WasmGraphBuilderBase::BuildSetNewStackLimit(), v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >::DebugPrint(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DebugPrint(), FromMachineRepresentation(), v8::internal::compiler::turboshaft::AtomicRMWOp::inputs_rep(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::inputs_rep(), v8::internal::compiler::turboshaft::StoreOp::inputs_rep(), v8::internal::compiler::turboshaft::StoreTypedElementOp::inputs_rep(), v8::internal::compiler::turboshaft::StoreDataViewElementOp::inputs_rep(), v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::inputs_rep(), MapTaggedToWord(), v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessAtomicRMW(), v8::internal::compiler::turboshaft::ConstantOp::Representation(), v8::internal::compiler::turboshaft::RunDecompressionOptimization(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TaggedBitcast(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::top(), v8::internal::compiler::turboshaft::TaggedBitcastOp::Validate(), v8::internal::compiler::turboshaft::AtomicRMWOp::Validate(), and v8::internal::compiler::turboshaft::WordRepresentation::WordPtr().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/representations.h