cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler > Class Template Reference
Public Types
using ResultType = SweepingState::SweptPageState
Public Member Functions
DeferredFinalizationBuilder (BasePage &page, PageAllocator &page_allocator)
void AddFinalizer (HeapObjectHeader *header, size_t size)
void AddFreeListEntry (Address start, size_t size)
ResultType && GetResult (bool is_empty)
Private Attributes
ResultType result_
HeapObjectHeader * current_unfinalized_ = nullptr
bool found_finalizer_ = false
Detailed Description
template<typename FreeHandler>
class cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler >
Definition at line 288 of file sweeper.cc.
Member Typedef Documentation
ResultType
template<typename FreeHandler >
using cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler >::ResultType = SweepingState::SweptPageState
Definition at line 290 of file sweeper.cc.
Constructor & Destructor Documentation
DeferredFinalizationBuilder()
template<typename FreeHandler >
cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler >::DeferredFinalizationBuilder (BasePage & page, PageAllocator & page_allocator) [inline]
Definition at line 292 of file sweeper.cc.
      : FreeHandler(page_allocator, result_.cached_free_list, page) {
    result_.page = &page;
  }
Member Function Documentation
AddFinalizer()
template<typename FreeHandler >
void cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler >::AddFinalizer (HeapObjectHeader * header, size_t size) [inline]
Definition at line 297 of file sweeper.cc.
                                                           {
    if (header->IsFinalizable()) {
#if defined(CPPGC_CAGED_HEAP)
      if (!current_unfinalized_) {
        DCHECK_NULL(result_.unfinalized_objects_head);
        current_unfinalized_ = header;
        result_.unfinalized_objects_head = header;
      } else {
        current_unfinalized_->SetNextUnfinalized(header);
        current_unfinalized_ = header;
      }
#else // !defined(CPPGC_CAGED_HEAP)
      result_.unfinalized_objects.push_back({header});
#endif // !defined(CPPGC_CAGED_HEAP)
      found_finalizer_ = true;
    } else {
      SetMemoryInaccessible(header, size);
    }
  }
References DCHECK_NULL, cppgc::internal::HeapObjectHeader::IsFinalizable(), cppgc::internal::SetMemoryInaccessible(), and size().
AddFreeListEntry()
template<typename FreeHandler >
void cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler >::AddFreeListEntry (Address start, size_t size) [inline]
Definition at line 317 of file sweeper.cc.
                                                    {
    if (found_finalizer_) {
      result_.unfinalized_free_list.push_back({start, size});
    } else {
      FreeHandler::Free({start, size});
    }
    result_.largest_new_free_list_entry =
        std::max(result_.largest_new_free_list_entry, size);
    found_finalizer_ = false;
  }
References v8::base::Free(), and size().
GetResult()
template<typename FreeHandler >
ResultType&& cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler >::GetResult (bool is_empty) [inline]
Definition at line 328 of file sweeper.cc.
                                        {
    result_.is_empty = is_empty;
    return std::move(result_);
  }
References v8::internal::compiler::turboshaft::is_empty(), and cppgc::internal::anonymous_namespace{sweeper.cc}::SweepingState::SweptPageState::is_empty.
Member Data Documentation
current_unfinalized_
template<typename FreeHandler >
HeapObjectHeader* cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler >::current_unfinalized_ = nullptr [private]
Definition at line 335 of file sweeper.cc.
found_finalizer_
template<typename FreeHandler >
bool cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler >::found_finalizer_ = false [private]
Definition at line 336 of file sweeper.cc.
result_
template<typename FreeHandler >
ResultType cppgc::internal::anonymous_namespace{sweeper.cc}::DeferredFinalizationBuilder< FreeHandler >::result_ [private]
Definition at line 334 of file sweeper.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/sweeper.cc