v8::internal::wasm::JumpTableAssembler Class Reference
#include <jump-table-assembler.h>
Public Member Functions
template<typename T >
void emit (T value)
template<typename T >
void emit (T value, RelaxedStoreTag) DISABLE_UBSAN
Static Public Member Functions
static uint32_t SlotOffsetToIndex (uint32_t slot_offset)
static uint32_t JumpSlotIndexToOffset (uint32_t slot_index)
static constexpr uint32_t SizeForNumberOfSlots (uint32_t slot_count)
static uint32_t FarJumpSlotIndexToOffset (uint32_t slot_index)
static uint32_t FarJumpSlotOffsetToIndex (uint32_t offset)
static constexpr uint32_t SizeForNumberOfFarJumpSlots (int num_runtime_slots, int num_function_slots)
static uint32_t LazyCompileSlotIndexToOffset (uint32_t slot_index)
static constexpr uint32_t SizeForNumberOfLazyFunctions (uint32_t slot_count)
static void GenerateLazyCompileTable (Address base, uint32_t num_slots, uint32_t num_imported_functions, Address wasm_compile_lazy_target)
static void InitializeJumpsToLazyCompileTable (Address base, uint32_t num_slots, Address lazy_compile_table_start)
static void GenerateFarJumpTable (WritableJitAllocation &jit_allocation, Address base, Address *stub_targets, int num_runtime_slots, int num_function_slots)
static void PatchJumpTableSlot (WritableJumpTablePair &jump_table_pair, Address jump_table_slot, Address far_jump_table_slot, Address target)
Private Member Functions
JumpTableAssembler (WritableJitAllocation &jit_allocation, Address slot_addr)
void EmitLazyCompileJumpSlot (uint32_t func_index, Address lazy_compile_target)
bool EmitJumpSlot (Address target)
void EmitFarJumpSlot (Address target)
void SkipUntil (int offset)
int pc_offset () const
template<typename V >
void emit (V value)
template<typename V >
void emit (V value, RelaxedStoreTag)
Static Private Member Functions
static void PatchFarJumpSlot (WritableJitAllocation &jit_allocation, Address slot, Address target)
Private Attributes
WritableJitAllocation & jit_allocation_
const Address buffer_start_
Address pc_
Static Private Attributes
static constexpr int kJumpTableSlotsPerLine
Detailed Description
Definition at line 60 of file jump-table-assembler.h.
Constructor & Destructor Documentation
JumpTableAssembler()
v8::internal::wasm::JumpTableAssembler::JumpTableAssembler (WritableJitAllocation & jit_allocation, Address slot_addr) [inline], [explicit], [private]
Definition at line 169 of file jump-table-assembler.h.
      : jit_allocation_(jit_allocation),
        buffer_start_(slot_addr),
        pc_(slot_addr) {}
Member Function Documentation
emit() [1/4]
template<typename T >
void v8::internal::wasm::JumpTableAssembler::emit (T value)
Definition at line 73 of file jump-table-assembler.cc.
                                     {
  jit_allocation_.WriteUnalignedValue(pc_, value);
  pc_ += sizeof(T);
}
References jit_allocation_, pc_, T, v8::internal::value, and v8::internal::WritableJitAllocation::WriteUnalignedValue().
emit() [2/4]
template<typename T >
void v8::internal::wasm::JumpTableAssembler::emit (T value, RelaxedStoreTag)
Definition at line 79 of file jump-table-assembler.cc.
                                                                    {
  // We disable ubsan for these stores since they don't follow the alignment
  // requirements. We instead guarantee in the jump table layout that the writes
  // will still be atomic since they don't cross a qword boundary.
#if V8_TARGET_ARCH_X64
#ifdef DEBUG
  Address write_start = pc_;
  Address write_end = write_start + sizeof(T) - 1;
  // Check that the write doesn't cross a qword boundary.
  DCHECK_EQ(write_start >> kSystemPointerSizeLog2,
            write_end >> kSystemPointerSizeLog2);
#endif
#endif
  jit_allocation_.WriteValue(pc_, value, kRelaxedStore);
  pc_ += sizeof(T);
}
References DCHECK_EQ, v8::kRelaxedStore, v8::internal::kSystemPointerSizeLog2, T, and v8::internal::value.
emit() [3/4]
template<typename V >
void v8::internal::wasm::JumpTableAssembler::emit (V value) [private]
emit() [4/4]
template<typename V >
void v8::internal::wasm::JumpTableAssembler::emit (V value, RelaxedStoreTag) [private]
EmitFarJumpSlot()
void v8::internal::wasm::JumpTableAssembler::EmitFarJumpSlot (Address target) [private]
Referenced by GenerateFarJumpTable().
EmitJumpSlot()
bool v8::internal::wasm::JumpTableAssembler::EmitJumpSlot (Address target) [private]
Referenced by InitializeJumpsToLazyCompileTable(), and PatchJumpTableSlot().
EmitLazyCompileJumpSlot()
void v8::internal::wasm::JumpTableAssembler::EmitLazyCompileJumpSlot (uint32_t func_index, Address lazy_compile_target) [private]
Referenced by GenerateLazyCompileTable().
FarJumpSlotIndexToOffset()
static uint32_t v8::internal::wasm::JumpTableAssembler::FarJumpSlotIndexToOffset (uint32_t slot_index) [inline], [static]
Definition at line 87 of file jump-table-assembler.h.
                                                                {
    return slot_index * kFarJumpTableSlotSize;
  }
Referenced by v8::internal::wasm::NativeModule::GetBuiltinInJumptableSlot(), v8::internal::wasm::NativeModule::GetJumpTableEntryForBuiltin(), v8::internal::wasm::NativeModule::InitializeJumpTableForLazyCompilation(), and v8::internal::wasm::NativeModule::PatchJumpTableLocked().
FarJumpSlotOffsetToIndex()
static uint32_t v8::internal::wasm::JumpTableAssembler::FarJumpSlotOffsetToIndex (uint32_t offset) [inline], [static]
Definition at line 92 of file jump-table-assembler.h.
                                                            {
    DCHECK_EQ(0, offset % kFarJumpTableSlotSize);
    return offset / kFarJumpTableSlotSize;
  }
References DCHECK_EQ.
Referenced by v8::internal::wasm::NativeModule::GetBuiltinInJumptableSlot().
GenerateFarJumpTable()
static void v8::internal::wasm::JumpTableAssembler::GenerateFarJumpTable (WritableJitAllocation & jit_allocation, Address base, Address * stub_targets, int num_runtime_slots, int num_function_slots) [inline], [static]
Definition at line 124 of file jump-table-assembler.h.
                                                           {
    uint32_t table_size =
        SizeForNumberOfFarJumpSlots(num_runtime_slots, num_function_slots);
    // Assume enough space, so the Assembler does not try to grow the buffer.
    JumpTableAssembler jtasm(jit_allocation, base);
    int offset = 0;
    for (int index = 0; index < num_runtime_slots + num_function_slots;
         ++index) {
      DCHECK_EQ(offset, FarJumpSlotIndexToOffset(index));
      // Functions slots initially jump to themselves. They are patched before
      // being used.
      Address target =
          index < num_runtime_slots ? stub_targets[index] : base + offset;
      jtasm.EmitFarJumpSlot(target);
      offset += kFarJumpTableSlotSize;
      DCHECK_EQ(offset, jtasm.pc_offset());
    }
    FlushInstructionCache(base, table_size);
  }
References DCHECK_EQ, EmitFarJumpSlot(), v8::internal::FlushInstructionCache(), v8::internal::index, and pc_offset().
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked().
GenerateLazyCompileTable()
void v8::internal::wasm::JumpTableAssembler::GenerateLazyCompileTable (Address base, uint32_t num_slots, uint32_t num_imported_functions, Address wasm_compile_lazy_target) [static]
Definition at line 15 of file jump-table-assembler.cc.
                                      {
  uint32_t lazy_compile_table_size = num_slots * kLazyCompileTableSlotSize;
  WritableJitAllocation jit_allocation = ThreadIsolation::LookupJitAllocation(
      base, RoundUp<kCodeAlignment>(lazy_compile_table_size),
      ThreadIsolation::JitAllocationType::kWasmLazyCompileTable);
  // Assume enough space, so the Assembler does not try to grow the buffer.
  JumpTableAssembler jtasm(jit_allocation, base);
  for (uint32_t slot_index = 0; slot_index < num_slots; ++slot_index) {
    DCHECK_EQ(slot_index * kLazyCompileTableSlotSize, jtasm.pc_offset());
    jtasm.EmitLazyCompileJumpSlot(slot_index + num_imported_functions,
                                  wasm_compile_lazy_target);
  }
  DCHECK_EQ(lazy_compile_table_size, jtasm.pc_offset());
  FlushInstructionCache(base, lazy_compile_table_size);
}
References DCHECK_EQ, EmitLazyCompileJumpSlot(), v8::internal::FlushInstructionCache(), v8::internal::ThreadIsolation::kWasmLazyCompileTable, v8::internal::ThreadIsolation::LookupJitAllocation(), and pc_offset().
Referenced by v8::internal::wasm::NativeModule::InitializeJumpTableForLazyCompilation().
InitializeJumpsToLazyCompileTable()
void v8::internal::wasm::JumpTableAssembler::InitializeJumpsToLazyCompileTable (Address base, uint32_t num_slots, Address lazy_compile_table_start) [static]
Definition at line 33 of file jump-table-assembler.cc.
                                                                        {
  uint32_t jump_table_size = SizeForNumberOfSlots(num_slots);
  WritableJitAllocation jit_allocation = ThreadIsolation::LookupJitAllocation(
      base, RoundUp<kCodeAlignment>(jump_table_size),
      ThreadIsolation::JitAllocationType::kWasmJumpTable);
  JumpTableAssembler jtasm(jit_allocation, base);
  for (uint32_t slot_index = 0; slot_index < num_slots; ++slot_index) {
    // Make sure we write at the correct offset.
    int slot_offset =
        static_cast<int>(JumpTableAssembler::JumpSlotIndexToOffset(slot_index));
    jtasm.SkipUntil(slot_offset);
    Address target =
        lazy_compile_table_start +
        JumpTableAssembler::LazyCompileSlotIndexToOffset(slot_index);
#ifdef DEBUG
    int offset_before_emit = jtasm.pc_offset();
#endif
    // This function initializes the first jump table with jumps to the lazy
    // compile table. Both get allocated in the constructor of the
    // {NativeModule}, so they both should end up in the initial code space.
    // Jumps within one code space can always be near jumps, so the following
    // call to {EmitJumpSlot} should always succeed. If the call fails, then
    // either the jump table allocation was changed incorrectly so that the lazy
    // compile table was not within near-jump distance of the jump table
    // anymore (e.g. the initial code space was too small to fit both tables),
    // or the code space was allocated larger than the maximum near-jump
    // distance.
    CHECK(jtasm.EmitJumpSlot(target));
    DCHECK_EQ(kJumpTableSlotSize, jtasm.pc_offset() - offset_before_emit);
  }
  FlushInstructionCache(base, jump_table_size);
}
References CHECK, DCHECK_EQ, EmitJumpSlot(), v8::internal::FlushInstructionCache(), JumpSlotIndexToOffset(), v8::internal::ThreadIsolation::kWasmJumpTable, LazyCompileSlotIndexToOffset(), v8::internal::ThreadIsolation::LookupJitAllocation(), pc_offset(), SizeForNumberOfSlots(), and SkipUntil().
Referenced by v8::internal::wasm::NativeModule::InitializeJumpTableForLazyCompilation().
JumpSlotIndexToOffset()
static uint32_t v8::internal::wasm::JumpTableAssembler::JumpSlotIndexToOffset (uint32_t slot_index) [inline], [static]
Definition at line 72 of file jump-table-assembler.h.
                                                             {
    uint32_t line_index = slot_index / kJumpTableSlotsPerLine;
    uint32_t line_offset =
        (slot_index % kJumpTableSlotsPerLine) * kJumpTableSlotSize;
    return line_index * kJumpTableLineSize + line_offset;
  }
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), v8::internal::wasm::NativeModule::GetFunctionIndexFromJumpTableSlot(), InitializeJumpsToLazyCompileTable(), v8::internal::wasm::NativeModule::InitializeJumpTableForLazyCompilation(), v8::internal::wasm::NativeModule::PatchJumpTableLocked(), and v8::internal::wasm::NativeModule::UseLazyStubLocked().
LazyCompileSlotIndexToOffset()
static uint32_t v8::internal::wasm::JumpTableAssembler::LazyCompileSlotIndexToOffset (uint32_t slot_index) [inline], [static]
Definition at line 106 of file jump-table-assembler.h.
                                                                    {
    return slot_index * kLazyCompileTableSlotSize;
  }
Referenced by InitializeJumpsToLazyCompileTable(), and v8::internal::wasm::NativeModule::UseLazyStubLocked().
PatchFarJumpSlot()
static void v8::internal::wasm::JumpTableAssembler::PatchFarJumpSlot (WritableJitAllocation & jit_allocation, Address slot, Address target) [static], [private]
Referenced by PatchJumpTableSlot().
PatchJumpTableSlot()
static void v8::internal::wasm::JumpTableAssembler::PatchJumpTableSlot (WritableJumpTablePair & jump_table_pair, Address jump_table_slot, Address far_jump_table_slot, Address target) [inline], [static]
Definition at line 147 of file jump-table-assembler.h.
                                                                              {
    // First, try to patch the jump table slot.
    JumpTableAssembler jtasm(jump_table_pair.jump_table(), jump_table_slot);
    if (!jtasm.EmitJumpSlot(target)) {
      // If that fails, we need to patch the far jump table slot, and then
      // update the jump table slot to jump to this far jump table slot.
      DCHECK_NE(kNullAddress, far_jump_table_slot);
      JumpTableAssembler::PatchFarJumpSlot(jump_table_pair.far_jump_table(),
                                           far_jump_table_slot, target);
      CHECK(jtasm.EmitJumpSlot(far_jump_table_slot));
    }
    // We write nops here instead of skipping to avoid partial instructions in
    // the jump table. Partial instructions can cause problems for the
    // disassembler.
    DCHECK_EQ(kJumpTableSlotSize, jtasm.pc_offset());
    FlushInstructionCache(jump_table_slot, kJumpTableSlotSize);
  }
References CHECK, DCHECK_EQ, DCHECK_NE, EmitJumpSlot(), v8::internal::FlushInstructionCache(), v8::internal::kNullAddress, PatchFarJumpSlot(), and pc_offset().
Referenced by v8::internal::wasm::NativeModule::PatchJumpTableLocked().
pc_offset()
int v8::internal::wasm::JumpTableAssembler::pc_offset () const [inline], [private]
Definition at line 267 of file jump-table-assembler.h.
{ return static_cast<int>(pc_ - buffer_start_); }
Referenced by GenerateFarJumpTable(), GenerateLazyCompileTable(), InitializeJumpsToLazyCompileTable(), and PatchJumpTableSlot().
SizeForNumberOfFarJumpSlots()
static constexpr uint32_t v8::internal::wasm::JumpTableAssembler::SizeForNumberOfFarJumpSlots (int num_runtime_slots, int num_function_slots) [inline], [static], [constexpr]
Definition at line 99 of file jump-table-assembler.h.
                                                     {
    int num_entries = num_runtime_slots + num_function_slots;
    return num_entries * kFarJumpTableSlotSize;
  }
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), v8::internal::wasm::WasmCodeManager::EstimateNativeModuleMetaDataSize(), and v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::OverheadPerCodeSpace().
SizeForNumberOfLazyFunctions()
static constexpr uint32_t v8::internal::wasm::JumpTableAssembler::SizeForNumberOfLazyFunctions (uint32_t slot_count) [inline], [static], [constexpr]
Definition at line 111 of file jump-table-assembler.h.
                                                                              {
    return slot_count * kLazyCompileTableSlotSize;
  }
Referenced by v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize(), and v8::internal::wasm::NativeModule::InitializeJumpTableForLazyCompilation().
SizeForNumberOfSlots()
static constexpr uint32_t v8::internal::wasm::JumpTableAssembler::SizeForNumberOfSlots (uint32_t slot_count) [inline], [static], [constexpr]
Definition at line 80 of file jump-table-assembler.h.
                                                                      {
    return ((slot_count + kJumpTableSlotsPerLine - 1) /
            kJumpTableSlotsPerLine) *
           kJumpTableLineSize;
  }
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), v8::internal::wasm::WasmCodeManager::EstimateNativeModuleMetaDataSize(), InitializeJumpsToLazyCompileTable(), and v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::OverheadPerCodeSpace().
SkipUntil()
void v8::internal::wasm::JumpTableAssembler::SkipUntil (int offset) [private]
Referenced by InitializeJumpsToLazyCompileTable().
SlotOffsetToIndex()
static uint32_t v8::internal::wasm::JumpTableAssembler::SlotOffsetToIndex (uint32_t slot_offset) [inline], [static]
Definition at line 63 of file jump-table-assembler.h.
                                                          {
    uint32_t line_index = slot_offset / kJumpTableLineSize;
    uint32_t line_offset = slot_offset % kJumpTableLineSize;
    DCHECK_EQ(0, line_offset % kJumpTableSlotSize);
    return line_index * kJumpTableSlotsPerLine +
           line_offset / kJumpTableSlotSize;
  }
References DCHECK_EQ.
Referenced by v8::internal::wasm::NativeModule::GetFunctionIndexFromJumpTableSlot().
Member Data Documentation
buffer_start_
const Address v8::internal::wasm::JumpTableAssembler::buffer_start_ [private]
Definition at line 176 of file jump-table-assembler.h.
jit_allocation_
WritableJitAllocation& v8::internal::wasm::JumpTableAssembler::jit_allocation_ [private]
Definition at line 175 of file jump-table-assembler.h.
Referenced by emit().
kJumpTableSlotsPerLine
constexpr int v8::internal::wasm::JumpTableAssembler::kJumpTableSlotsPerLine [static], [constexpr], [private]
Initial value:
=
      kJumpTableLineSize / kJumpTableSlotSize
Definition at line 247 of file jump-table-assembler.h.
pc_
Address v8::internal::wasm::JumpTableAssembler::pc_ [private]
Definition at line 177 of file jump-table-assembler.h.
Referenced by emit().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/jump-table-assembler.h
/mnt/V8SourceCode/src/wasm/jump-table-assembler.cc