v8::internal::SharedStructTypeRegistry::Data Class Reference
Public Member Functions
Data (int capacity)
Tagged< Object > GetKey (PtrComprCageBase cage_base, InternalIndex index) const
void SetKey (InternalIndex index, Tagged< Object > key)
void Set (InternalIndex index, Tagged< Map > map)
void CopyEntryExcludingKeyInto (PtrComprCageBase cage_base, InternalIndex from_index, Data *to, InternalIndex to_index)
void * operator new (size_t size, int capacity)
void * operator new (size_t size)=delete
void operator delete (void *table)
Static Public Member Functions
static uint32_t Hash (PtrComprCageBase cage_base, Tagged< Object > key)
template<typename IsolateT >
static bool KeyIsMatch (IsolateT *isolate, DirectHandle< String > key, Tagged< Object > obj)
static std::unique_ptr< Data > New (int capacity)
Static Public Attributes
static constexpr int kEntrySize = 1
static constexpr int kMaxEmptyFactor = 4
static constexpr int kMinCapacity = 4
Additional Inherited Members
Detailed Description
Definition at line 310 of file js-struct.cc.
Constructor & Destructor Documentation
Data()
v8::internal::SharedStructTypeRegistry::Data::Data (int capacity) [inline], [explicit]
Definition at line 316 of file js-struct.cc.
: OffHeapHashTableBase<Data>(capacity) {}
Referenced by New(), and operator new().
Member Function Documentation
CopyEntryExcludingKeyInto()
void v8::internal::SharedStructTypeRegistry::Data::CopyEntryExcludingKeyInto (PtrComprCageBase cage_base, InternalIndex from_index, Data * to, InternalIndex to_index) [inline]
Definition at line 348 of file js-struct.cc.
                                                         {
    // Do nothing, since kEntrySize is 1.
  }
GetKey()
Tagged<Object> v8::internal::SharedStructTypeRegistry::Data::GetKey (PtrComprCageBase cage_base, InternalIndex index) const [inline]
Definition at line 338 of file js-struct.cc.
                                                                               {
    return slot(index).load(cage_base);
  }
References v8::internal::index, v8::internal::FullObjectSlot::load(), and v8::internal::OffHeapHashTableBase< Data >::slot().
Hash()
static uint32_t v8::internal::SharedStructTypeRegistry::Data::Hash (PtrComprCageBase cage_base, Tagged< Object > key) [inline], [static]
Definition at line 318 of file js-struct.cc.
                                                                       {
    // Registry keys, if present, store them at the first descriptor. All maps
    // in the registry have registry keys.
    return Cast<String>(
               Cast<Map>(key)->instance_descriptors(cage_base)->GetStrongValue(
                   InternalIndex(0)))
        ->hash();
  }
References v8::internal::instance_descriptors, and v8::internal::key.
KeyIsMatch()
template<typename IsolateT >
static bool v8::internal::SharedStructTypeRegistry::Data::KeyIsMatch (IsolateT * isolate, DirectHandle< String > key, Tagged< Object > obj) [inline], [static]
Definition at line 328 of file js-struct.cc.
                                             {
    DirectHandle<String> existing =
        JSSharedStruct::GetRegistryKey(isolate, Cast<Map>(obj))
            .ToHandleChecked();
    DCHECK(IsInternalizedString(*key));
    DCHECK(IsInternalizedString(*existing));
    return *key == *existing;
  }
References v8::internal::DCHECK(), v8::internal::JSSharedStruct::GetRegistryKey(), v8::internal::InstanceTypeChecker::IsInternalizedString(), and v8::internal::key.
New()
static std::unique_ptr<Data> v8::internal::SharedStructTypeRegistry::Data::New (int capacity) [inline], [static]
Definition at line 354 of file js-struct.cc.
                                               {
    return std::unique_ptr<Data>(new (capacity) Data(capacity));
  }
References v8::internal::OffHeapHashTableBase< Data >::capacity(), and Data().
Referenced by v8::internal::SharedStructTypeRegistry::EnsureCapacity().
operator delete()
void v8::internal::SharedStructTypeRegistry::Data::operator delete (void * table) [inline]
Definition at line 367 of file js-struct.cc.
{ OffHeapHashTableBase<Data>::Free(table); }
References v8::internal::OffHeapHashTableBase< Derived >::Free().
operator new() [1/2]
void* v8::internal::SharedStructTypeRegistry::Data::operator new (size_t size) [delete]
operator new() [2/2]
void* v8::internal::SharedStructTypeRegistry::Data::operator new (size_t size, int capacity) [inline]
Definition at line 358 of file js-struct.cc.
                                                {
    DCHECK_GE(capacity, kMinCapacity);
    DCHECK_EQ(size, sizeof(Data));
    return OffHeapHashTableBase<Data>::Allocate<Data,
                                                offsetof(Data, elements_)>(
        capacity);
  }
References v8::internal::OffHeapHashTableBase< Data >::capacity(), Data(), DCHECK_EQ, DCHECK_GE, v8::internal::OffHeapHashTableBase< Data >::elements_, kMinCapacity, and size().
Set()
void v8::internal::SharedStructTypeRegistry::Data::Set (InternalIndex index, Tagged< Map > map) [inline]
Definition at line 346 of file js-struct.cc.
{ SetKey(index, map); }
References v8::internal::index, and SetKey().
SetKey()
void v8::internal::SharedStructTypeRegistry::Data::SetKey (InternalIndex index, Tagged< Object > key) [inline]
Definition at line 342 of file js-struct.cc.
                                                       {
    DCHECK(IsMap(key));
    slot(index).store(key);
  }
References v8::internal::DCHECK(), v8::internal::index, v8::internal::key, v8::internal::OffHeapHashTableBase< Data >::slot(), and v8::internal::FullObjectSlot::store().
Referenced by Set().
Member Data Documentation
kEntrySize
constexpr int v8::internal::SharedStructTypeRegistry::Data::kEntrySize = 1 [static], [constexpr]
Definition at line 312 of file js-struct.cc.
kMaxEmptyFactor
constexpr int v8::internal::SharedStructTypeRegistry::Data::kMaxEmptyFactor = 4 [static], [constexpr]
Definition at line 313 of file js-struct.cc.
kMinCapacity
constexpr int v8::internal::SharedStructTypeRegistry::Data::kMinCapacity = 4 [static], [constexpr]
Definition at line 314 of file js-struct.cc.
Referenced by operator new().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/js-struct.cc