v8::internal::Descriptor Class Reference
#include <property.h>
Public Member Functions
Descriptor ()
DirectHandle< Name > GetKey () const
MaybeObjectDirectHandle GetValue () const
PropertyDetails GetDetails () const
void SetSortedKeyIndex (int index)
Static Public Member Functions
static Descriptor DataField (Isolate *isolate, DirectHandle< Name > key, int field_index, PropertyAttributes attributes, Representation representation)
static Descriptor DataField (DirectHandle< Name > key, int field_index, PropertyAttributes attributes, PropertyConstness constness, Representation representation, const MaybeObjectDirectHandle &wrapped_field_type)
static Descriptor DataConstant (DirectHandle< Name > key, DirectHandle< Object > value, PropertyAttributes attributes)
static Descriptor DataConstant (Isolate *isolate, DirectHandle< Name > key, int field_index, DirectHandle< Object > value, PropertyAttributes attributes)
static Descriptor AccessorConstant (DirectHandle< Name > key, DirectHandle< Object > foreign, PropertyAttributes attributes)
Protected Member Functions
Descriptor (DirectHandle< Name > key, const MaybeObjectDirectHandle &value, PropertyDetails details)
Descriptor (DirectHandle< Name > key, const MaybeObjectDirectHandle &value, PropertyKind kind, PropertyAttributes attributes, PropertyLocation location, PropertyConstness constness, Representation representation, int field_index)
Private Attributes
DirectHandle< Name > key_
MaybeObjectDirectHandle value_
PropertyDetails details_
Friends
class MapUpdater
Detailed Description
Definition at line 25 of file property.h.
Constructor & Destructor Documentation
Descriptor() [1/3]
v8::internal::Descriptor::Descriptor ()
Definition at line 58 of file property.cc.
: details_(Smi::zero()) {}
Referenced by AccessorConstant(), DataConstant(), and DataField().
Descriptor() [2/3]
v8::internal::Descriptor::Descriptor (DirectHandle< Name > key, const MaybeObjectDirectHandle & value, PropertyDetails details) [protected]
Definition at line 73 of file property.cc.
    : key_(key), value_(value), details_(details) {
  DCHECK(IsUniqueName(*key));
  DCHECK_IMPLIES(key->IsPrivate(), !details_.IsEnumerable());
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, details_, v8::internal::PropertyDetails::IsEnumerable(), v8::internal::IsUniqueName(), and v8::internal::key.
Descriptor() [3/3]
v8::internal::Descriptor::Descriptor (DirectHandle< Name > key, const MaybeObjectDirectHandle & value, PropertyKind kind, PropertyAttributes attributes, PropertyLocation location, PropertyConstness constness, Representation representation, int field_index) [protected]
Definition at line 60 of file property.cc.
    : key_(key),
      value_(value),
      details_(kind, attributes, location, constness, representation,
               field_index) {
  DCHECK(IsUniqueName(*key));
  DCHECK_IMPLIES(key->IsPrivate(), !details_.IsEnumerable());
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, details_, v8::internal::PropertyDetails::IsEnumerable(), v8::internal::IsUniqueName(), and v8::internal::key.
Member Function Documentation
AccessorConstant()
Descriptor v8::internal::Descriptor::AccessorConstant (DirectHandle< Name > key, DirectHandle< Object > foreign, PropertyAttributes attributes) [static]
Definition at line 118 of file property.cc.
                                                                       {
  return Descriptor(key, MaybeObjectDirectHandle(foreign),
                    PropertyKind::kAccessor, attributes,
                    PropertyLocation::kDescriptor, PropertyConstness::kConst,
                    Representation::Tagged(), 0);
}
References Descriptor(), v8::internal::kAccessor, v8::internal::kConst, v8::internal::kDescriptor, v8::internal::key, and v8::internal::Representation::Tagged().
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddConstant(), v8::internal::anonymous_namespace{literal-objects.cc}::AddToDescriptorArrayTemplate(), v8::internal::MapUpdater::BuildDescriptorArray(), v8::internal::Factory::CreateClassFunctionMap(), v8::internal::Genesis::CreateInitialMapForArraySubclass(), v8::internal::Factory::CreateSloppyFunctionMap(), v8::internal::Factory::CreateStrictFunctionMap(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::InstallError(), v8::internal::JSObject::MigrateSlowToFast(), v8::internal::anonymous_namespace{bootstrapper.cc}::ReplaceAccessors(), and v8::internal::Map::TransitionToAccessorProperty().
DataConstant() [1/2]
Descriptor v8::internal::Descriptor::DataConstant (DirectHandle< Name > key, DirectHandle< Object > value, PropertyAttributes attributes) [static]
Definition at line 100 of file property.cc.
                                                                   {
  PtrComprCageBase cage_base = GetPtrComprCageBase(*key);
  return Descriptor(key, MaybeObjectDirectHandle(value), PropertyKind::kData,
                    attributes, PropertyLocation::kDescriptor,
                    PropertyConstness::kConst,
                    Object::OptimalRepresentation(*value, cage_base), 0);
}
References Descriptor(), v8::internal::GetPtrComprCageBase(), v8::internal::kConst, v8::internal::kData, v8::internal::kDescriptor, v8::internal::key, v8::internal::Object::OptimalRepresentation(), and v8::internal::value.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddConstant(), v8::internal::anonymous_namespace{literal-objects.cc}::AddToDescriptorArrayTemplate(), v8::internal::MapUpdater::BuildDescriptorArray(), and v8::internal::JSSharedStruct::CreateInstanceMap().
DataConstant() [2/2]
Descriptor v8::internal::Descriptor::DataConstant (Isolate * isolate, DirectHandle< Name > key, int field_index, DirectHandle< Object > value, PropertyAttributes attributes) [static]
Definition at line 110 of file property.cc.
                                                                   {
  MaybeObjectDirectHandle any_type(FieldType::Any(), isolate);
  return DataField(key, field_index, attributes, PropertyConstness::kConst,
                   Representation::Tagged(), any_type);
}
References v8::internal::FieldType::Any(), DataField(), v8::internal::kConst, v8::internal::key, and v8::internal::Representation::Tagged().
DataField() [1/2]
Descriptor v8::internal::Descriptor::DataField (DirectHandle< Name > key, int field_index, PropertyAttributes attributes, PropertyConstness constness, Representation representation, const MaybeObjectDirectHandle & wrapped_field_type) [static]
Definition at line 89 of file property.cc.
                                                       {
  DCHECK(IsSmi(*wrapped_field_type) || IsWeak(*wrapped_field_type));
  PropertyDetails details(PropertyKind::kData, attributes,
                          PropertyLocation::kField, constness, representation,
                          field_index);
  return Descriptor(key, wrapped_field_type, details);
}
References v8::internal::DCHECK(), Descriptor(), v8::internal::IsSmi(), v8::internal::IsWeak(), v8::internal::kData, v8::internal::key, and v8::internal::kField.
DataField() [2/2]
Descriptor v8::internal::Descriptor::DataField (Isolate * isolate, DirectHandle< Name > key, int field_index, PropertyAttributes attributes, Representation representation) [static]
Definition at line 81 of file property.cc.
                                                                {
  return DataField(key, field_index, attributes, PropertyConstness::kMutable,
                   representation,
                   MaybeObjectDirectHandle(FieldType::Any(isolate)));
}
References v8::internal::FieldType::Any(), v8::internal::key, and v8::internal::kMutable.
Referenced by v8::internal::MapUpdater::BuildDescriptorArray(), v8::internal::Map::CopyWithField(), v8::internal::Genesis::CreateJSProxyMaps(), v8::internal::Heap::CreateLateReadOnlyJSReceiverMaps(), v8::internal::Factory::CreateSloppyFunctionMap(), v8::internal::Factory::CreateStrictFunctionMap(), DataConstant(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::InstallError(), v8::internal::JSObject::MigrateSlowToFast(), v8::internal::WasmValueObject::New(), and v8::internal::MapUpdater::UpdateFieldType().
GetDetails()
PropertyDetails v8::internal::Descriptor::GetDetails () const [inline]
Definition at line 31 of file property.h.
{ return details_; }
Referenced by v8::internal::Map::AppendDescriptor(), v8::internal::MapUpdater::BuildDescriptorArray(), v8::internal::Map::CopyReplaceDescriptor(), v8::internal::JSObject::MigrateSlowToFast(), and v8::internal::DescriptorArray::Set().
GetKey()
DirectHandle<Name> v8::internal::Descriptor::GetKey () const [inline]
Definition at line 29 of file property.h.
{ return key_; }
Referenced by v8::internal::DescriptorArray::Append(), v8::internal::Map::AppendDescriptor(), v8::internal::DescriptorArray::CheckNameCollisionDuringInsertion(), v8::internal::Map::CopyAddDescriptor(), v8::internal::Map::CopyInsertDescriptor(), v8::internal::Map::CopyReplaceDescriptor(), v8::internal::DescriptorArray::Set(), and v8::internal::Map::ShareDescriptor().
GetValue()
MaybeObjectDirectHandle v8::internal::Descriptor::GetValue () const [inline]
Definition at line 30 of file property.h.
{ return value_; }
Referenced by v8::internal::DescriptorArray::Set().
SetSortedKeyIndex()
void v8::internal::Descriptor::SetSortedKeyIndex (int index) [inline]
Definition at line 33 of file property.h.
{ details_ = details_.set_pointer(index); }
References v8::internal::index.
Referenced by v8::internal::anonymous_namespace{literal-objects.cc}::AddToDescriptorArrayTemplate(), and v8::internal::DescriptorArray::Replace().
Friends And Related Function Documentation
MapUpdater
friend class MapUpdater [friend]
Definition at line 70 of file property.h.
Member Data Documentation
details_
PropertyDetails v8::internal::Descriptor::details_ [private]
Definition at line 59 of file property.h.
Referenced by Descriptor().
key_
DirectHandle<Name> v8::internal::Descriptor::key_ [private]
Definition at line 57 of file property.h.
Referenced by v8::internal::MapUpdater::UpdateFieldType().
value_
MaybeObjectDirectHandle v8::internal::Descriptor::value_ [private]
Definition at line 58 of file property.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/property.h
/mnt/V8SourceCode/src/objects/property.cc