v8::internal::anonymous_namespace{profile-data-reader.cc}::ProfileDataFromFileInternal Class Reference
Public Member Functions
bool hash_has_value () const
void set_hash (int hash)
void AddHintToBlock (size_t true_block_id, size_t false_block_id, uint64_t hint)
Private Attributes
bool hash_has_value_ = false
Additional Inherited Members
Detailed Description
Definition at line 20 of file profile-data-reader.cc.
Member Function Documentation
AddHintToBlock()
void v8::internal::anonymous_namespace{profile-data-reader.cc}::ProfileDataFromFileInternal::AddHintToBlock (size_t true_block_id, size_t false_block_id, uint64_t hint) [inline]
Definition at line 29 of file profile-data-reader.cc.
                                     {
    CHECK_LT(hint, 2);
    block_hints_by_id.insert(std::make_pair(
        std::make_pair(true_block_id, false_block_id), hint != 0));
  }
References CHECK_LT.
Referenced by v8::internal::anonymous_namespace{profile-data-reader.cc}::EnsureInitProfileData().
hash_has_value()
bool v8::internal::anonymous_namespace{profile-data-reader.cc}::ProfileDataFromFileInternal::hash_has_value () const [inline]
Definition at line 22 of file profile-data-reader.cc.
{ return hash_has_value_; }
Referenced by v8::internal::anonymous_namespace{profile-data-reader.cc}::EnsureInitProfileData().
set_hash()
void v8::internal::anonymous_namespace{profile-data-reader.cc}::ProfileDataFromFileInternal::set_hash (int hash) [inline]
Definition at line 24 of file profile-data-reader.cc.
                          {
    hash_ = hash;
    hash_has_value_ = true;
  }
Referenced by v8::internal::anonymous_namespace{profile-data-reader.cc}::EnsureInitProfileData().
Member Data Documentation
hash_has_value_
bool v8::internal::anonymous_namespace{profile-data-reader.cc}::ProfileDataFromFileInternal::hash_has_value_ = false [private]
Definition at line 43 of file profile-data-reader.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/profile-data-reader.cc