v8::internal::YoungGenerationMarkingVisitor< marking_mode > Class Template Reference
#include <young-generation-marking-visitor.h>
Public Types
enum class ObjectVisitationMode { kVisitDirectly
, kPushToWorklist
 }
enum class SlotTreatmentMode { kReadOnly
, kReadWrite
 }
using Base = NewSpaceVisitor< YoungGenerationMarkingVisitor< marking_mode > >
Public Member Functions
YoungGenerationMarkingVisitor (Heap *heap, PretenuringHandler::PretenuringFeedbackMap *local_pretenuring_feedback)
~YoungGenerationMarkingVisitor () override
YoungGenerationMarkingVisitor (const YoungGenerationMarkingVisitor &)=delete
YoungGenerationMarkingVisitor & operator= (const YoungGenerationMarkingVisitor &)=delete
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) final
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) final
void VisitPointer (Tagged< HeapObject > host, ObjectSlot p) final
void VisitPointer (Tagged< HeapObject > host, MaybeObjectSlot p) final
size_t VisitJSArrayBuffer (Tagged< Map > map, Tagged< JSArrayBuffer > object, MaybeObjectSize)
template<typename T , typename TBodyDescriptor = typename T::BodyDescriptor>
size_t VisitJSObjectSubclass (Tagged< Map > map, Tagged< T > object, MaybeObjectSize)
size_t VisitEphemeronHashTable (Tagged< Map > map, Tagged< EphemeronHashTable > table, MaybeObjectSize)
void VisitCppHeapPointer (Tagged< HeapObject > host, CppHeapPointerSlot slot) override
template<ObjectVisitationMode visitation_mode, SlotTreatmentMode slot_treatment_mode, typename TSlot >
bool VisitObjectViaSlot (TSlot slot)
template<typename TSlot >
bool VisitObjectViaSlotInRememberedSet (TSlot slot)
MarkingWorklists::Local & marking_worklists_local ()
void IncrementLiveBytesCached (MutablePageMetadata *chunk, intptr_t by)
void PublishWorklists ()
Static Public Member Functions
static constexpr bool EnableConcurrentVisitation ()
static constexpr bool CanEncounterFillerOrFreeSpace ()
Private Member Functions
bool TryMark (Tagged< HeapObject > obj)
template<typename TSlot >
void VisitPointersImpl (Tagged< HeapObject > host, TSlot start, TSlot end)
Private Attributes
std::array< std::pair< MutablePageMetadata *, size_t >, kNumEntries > live_bytes_data_
Isolate *const isolate_
MarkingWorklists::Local marking_worklists_local_
EphemeronRememberedSet::TableList::Local ephemeron_table_list_local_
PretenuringHandler *const pretenuring_handler_
PretenuringHandler::PretenuringFeedbackMap *const local_pretenuring_feedback_
const bool shortcut_strings_
Static Private Attributes
static constexpr size_t kNumEntries = 128
static constexpr size_t kEntriesMask = kNumEntries - 1
Additional Inherited Members
Detailed Description
template<YoungGenerationMarkingVisitationMode marking_mode>
class v8::internal::YoungGenerationMarkingVisitor< marking_mode >
Definition at line 22 of file young-generation-marking-visitor.h.
Member Typedef Documentation
Base
template<YoungGenerationMarkingVisitationMode marking_mode>
using v8::internal::YoungGenerationMarkingVisitor< marking_mode >::Base = NewSpaceVisitor<YoungGenerationMarkingVisitor<marking_mode> >
Definition at line 25 of file young-generation-marking-visitor.h.
Member Enumeration Documentation
ObjectVisitationMode
template<YoungGenerationMarkingVisitationMode marking_mode>
enum v8::internal::YoungGenerationMarkingVisitor::ObjectVisitationMode [strong]
Enumerator
kVisitDirectly
kPushToWorklist
Definition at line 27 of file young-generation-marking-visitor.h.
                                  {
    kVisitDirectly,
    kPushToWorklist,
  };
SlotTreatmentMode
template<YoungGenerationMarkingVisitationMode marking_mode>
enum v8::internal::YoungGenerationMarkingVisitor::SlotTreatmentMode [strong]
Enumerator
kReadOnly
kReadWrite
Definition at line 32 of file young-generation-marking-visitor.h.
                               {
    kReadOnly,
    kReadWrite,
  };
Constructor & Destructor Documentation
YoungGenerationMarkingVisitor() [1/2]
template<YoungGenerationMarkingVisitationMode marking_mode>
v8::internal::YoungGenerationMarkingVisitor< marking_mode >::YoungGenerationMarkingVisitor (Heap * heap, PretenuringHandler::PretenuringFeedbackMap * local_pretenuring_feedback)
Definition at line 25 of file young-generation-marking-visitor-inl.h.
    : Base(heap->isolate()),
      isolate_(heap->isolate()),
      marking_worklists_local_(
          heap->minor_mark_sweep_collector()->marking_worklists(),
          heap->cpp_heap()
              ? CppHeap::From(heap->cpp_heap())->CreateCppMarkingState()
              : MarkingWorklists::Local::kNoCppMarkingState),
      ephemeron_table_list_local_(
          *heap->minor_mark_sweep_collector()->ephemeron_table_list()),
      pretenuring_handler_(heap->pretenuring_handler()),
      local_pretenuring_feedback_(local_pretenuring_feedback),
      shortcut_strings_(heap->CanShortcutStringsDuringGC(
          GarbageCollector::MINOR_MARK_SWEEPER)) {}
References v8::internal::MINOR_MARK_SWEEPER.
 YoungGenerationMarkingVisitor()
template<YoungGenerationMarkingVisitationMode marking_mode>
v8::internal::YoungGenerationMarkingVisitor< marking_mode >::~YoungGenerationMarkingVisitor [override]
Definition at line 43 of file young-generation-marking-visitor-inl.h.
                                                                            {
  PublishWorklists();
  // Flush memory chunk live bytes. Atomics are used for incrementing the live
  // bytes counter of the page, so there is no need to defer flushing to the
  // main thread.
  for (auto& pair : live_bytes_data_) {
    if (pair.first) {
      pair.first->IncrementLiveBytesAtomically(pair.second);
    }
  }
}
YoungGenerationMarkingVisitor() [2/2]
template<YoungGenerationMarkingVisitationMode marking_mode>
v8::internal::YoungGenerationMarkingVisitor< marking_mode >::YoungGenerationMarkingVisitor (const YoungGenerationMarkingVisitor< marking_mode > &) [delete]
Member Function Documentation
CanEncounterFillerOrFreeSpace()
template<YoungGenerationMarkingVisitationMode marking_mode>
static constexpr bool v8::internal::YoungGenerationMarkingVisitor< marking_mode >::CanEncounterFillerOrFreeSpace () [inline], [static], [constexpr]
Definition at line 106 of file young-generation-marking-visitor.h.
                                                                  {
    return false;
  }
EnableConcurrentVisitation()
template<YoungGenerationMarkingVisitationMode marking_mode>
static constexpr bool v8::internal::YoungGenerationMarkingVisitor< marking_mode >::EnableConcurrentVisitation () [inline], [static], [constexpr]
Definition at line 47 of file young-generation-marking-visitor.h.
                                                     {
    return marking_mode == YoungGenerationMarkingVisitationMode::kConcurrent;
  }
References v8::internal::kConcurrent.
IncrementLiveBytesCached()
template<YoungGenerationMarkingVisitationMode marking_mode>
void v8::internal::YoungGenerationMarkingVisitor< marking_mode >::IncrementLiveBytesCached (MutablePageMetadata * chunk, intptr_t by) [inline]
Definition at line 275 of file young-generation-marking-visitor-inl.h.
                                             {
  DCHECK_IMPLIES(V8_COMPRESS_POINTERS_8GB_BOOL,
                 IsAligned(by, kObjectAlignment8GbHeap));
  const size_t hash = base::hash<MutablePageMetadata*>()(chunk) & kEntriesMask;
  auto& entry = live_bytes_data_[hash];
  if (entry.first && entry.first != chunk) {
    entry.first->IncrementLiveBytesAtomically(entry.second);
    entry.first = chunk;
    entry.second = 0;
  } else {
    entry.first = chunk;
  }
  entry.second += by;
}
References DCHECK_IMPLIES, IsAligned(), v8::internal::kObjectAlignment8GbHeap, and V8_COMPRESS_POINTERS_8GB_BOOL.
Referenced by v8::internal::ConcurrentMarking::RunMinorImpl().
marking_worklists_local()
template<YoungGenerationMarkingVisitationMode marking_mode>
MarkingWorklists::Local& v8::internal::YoungGenerationMarkingVisitor< marking_mode >::marking_worklists_local () [inline]
Definition at line 94 of file young-generation-marking-visitor.h.
                                                   {
    return marking_worklists_local_;
  }
References v8::internal::YoungGenerationMarkingVisitor< marking_mode >::marking_worklists_local_.
Referenced by v8::internal::ConcurrentMarking::RunMinorImpl().
operator=()
template<YoungGenerationMarkingVisitationMode marking_mode>
YoungGenerationMarkingVisitor& v8::internal::YoungGenerationMarkingVisitor< marking_mode >::operator= (const YoungGenerationMarkingVisitor< marking_mode > &) [delete]
PublishWorklists()
template<YoungGenerationMarkingVisitationMode marking_mode>
void v8::internal::YoungGenerationMarkingVisitor< marking_mode >::PublishWorklists () [inline]
Definition at line 101 of file young-generation-marking-visitor.h.
                          {
    marking_worklists_local_.Publish();
    ephemeron_table_list_local_.Publish();
  }
References v8::internal::YoungGenerationMarkingVisitor< marking_mode >::ephemeron_table_list_local_, v8::internal::YoungGenerationMarkingVisitor< marking_mode >::marking_worklists_local_, and heap::base::Worklist< EntryType, MinSegmentSize >::Local::Publish().
TryMark()
template<YoungGenerationMarkingVisitationMode marking_mode>
bool v8::internal::YoungGenerationMarkingVisitor< marking_mode >::TryMark (Tagged< HeapObject > obj) [inline], [private]
Definition at line 111 of file young-generation-marking-visitor.h.
                                       {
    return MarkBit::From(obj).Set<AccessMode::ATOMIC>();
  }
References v8::internal::ATOMIC, v8::internal::MarkBit::From(), and v8::internal::MarkBit::Set().
VisitCppHeapPointer()
template<YoungGenerationMarkingVisitationMode marking_mode>
void v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitCppHeapPointer (Tagged< HeapObject > host, CppHeapPointerSlot slot) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 57 of file young-generation-marking-visitor-inl.h.
                                                      {
  if (!marking_worklists_local_.cpp_marking_state()) return;
  // The table is not reclaimed in the young generation, so we only need to mark
  // through to the C++ pointer.
  if (auto cpp_heap_pointer = slot.try_load(isolate_, kAnyCppHeapPointer)) {
    marking_worklists_local_.cpp_marking_state()->MarkAndPush(
        reinterpret_cast<void*>(cpp_heap_pointer));
  }
}
References v8::kAnyCppHeapPointer(), and v8::internal::CppHeapPointerSlot::try_load().
VisitEphemeronHashTable()
template<YoungGenerationMarkingVisitationMode marking_mode>
size_t v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitEphemeronHashTable (Tagged< Map > map, Tagged< EphemeronHashTable > table, MaybeObjectSize) [inline]
Definition at line 91 of file young-generation-marking-visitor-inl.h.
                                                                        {
  // Register table with Minor MC, so it can take care of the weak keys later.
  // This allows to only iterate the tables' values, which are treated as strong
  // independently of whether the key is live.
  ephemeron_table_list_local_.Push(table);
  for (InternalIndex i : table->IterateEntries()) {
    ObjectSlot value_slot =
        table->RawFieldOfElementAt(EphemeronHashTable::EntryToValueIndex(i));
    VisitPointer(table, value_slot);
  }
  return EphemeronHashTable::BodyDescriptor::SizeOf(map, table);
}
References v8::internal::EphemeronHashTable::BodyDescriptor::SizeOf().
VisitJSArrayBuffer()
template<YoungGenerationMarkingVisitationMode marking_mode>
size_t v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitJSArrayBuffer (Tagged< Map > map, Tagged< JSArrayBuffer > object, MaybeObjectSize maybe_object_size) [inline]
Definition at line 71 of file young-generation-marking-visitor-inl.h.
                                       {
  object->YoungMarkExtension();
  return Base::VisitJSArrayBuffer(map, object, maybe_object_size);
}
VisitJSObjectSubclass()
template<YoungGenerationMarkingVisitationMode marking_mode>
template<typename T , typename TBodyDescriptor >
size_t v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitJSObjectSubclass (Tagged< Map > map, Tagged< T > object, MaybeObjectSize maybe_object_size) [inline]
Definition at line 80 of file young-generation-marking-visitor-inl.h.
                                                                          {
  const int object_size =
      static_cast<int>(Base::template VisitJSObjectSubclass<T, TBodyDescriptor>(
          map, object, maybe_object_size));
  PretenuringHandler::UpdateAllocationSite(
      isolate_->heap(), map, object, object_size, local_pretenuring_feedback_);
  return object_size;
}
References v8::internal::PretenuringHandler::UpdateAllocationSite().
VisitObjectViaSlot()
template<YoungGenerationMarkingVisitationMode marking_mode>
template<typename YoungGenerationMarkingVisitor< marking_mode >::ObjectVisitationMode visitation_mode, typename YoungGenerationMarkingVisitor< marking_mode >::SlotTreatmentMode slot_treatment_mode, typename TSlot >
bool v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitObjectViaSlot (TSlot slot) [inline]
Definition at line 173 of file young-generation-marking-visitor-inl.h.
                {
  const std::optional<Tagged<Object>> optional_object =
      this->GetObjectFilterReadOnlyAndSmiFast(slot);
  if (!optional_object) {
    return false;
  }
  typename TSlot::TObject target = *optional_object;
#ifdef V8_ENABLE_DIRECT_HANDLE
  if (target.ptr() == kTaggedNullAddress) return false;
#endif
  Tagged<HeapObject> heap_object;
  // Treat weak references as strong.
  if (!target.GetHeapObject(&heap_object)) {
    return false;
  }
#ifdef THREAD_SANITIZER
  MemoryChunk::FromHeapObject(heap_object)->SynchronizedLoad();
#endif // THREAD_SANITIZER
  if (!HeapLayout::InYoungGeneration(heap_object)) {
    return false;
  }
#ifdef V8_MINORMS_STRING_SHORTCUTTING
  if (slot_treatment_mode == SlotTreatmentMode::kReadWrite &&
      !ShortCutStrings(reinterpret_cast<HeapObjectSlot&>(slot), &heap_object)) {
    return false;
  }
#endif // V8_MINORMS_STRING_SHORTCUTTING
  if (!TryMark(heap_object)) return true;
  // Maps won't change in the atomic pause, so the map can be read without
  // atomics.
  if constexpr (visitation_mode == ObjectVisitationMode::kVisitDirectly) {
    Tagged<Map> map = heap_object->map(isolate_);
    const size_t visited_size = Base::Visit(map, heap_object);
    if (visited_size) {
      IncrementLiveBytesCached(
          MutablePageMetadata::cast(
              MemoryChunkMetadata::FromHeapObject(heap_object)),
          ALIGN_TO_ALLOCATION_ALIGNMENT(visited_size));
    }
    return true;
  }
  // Default case: Visit via worklist.
  marking_worklists_local_.Push(heap_object);
  return true;
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::MutablePageMetadata::cast(), v8::internal::MemoryChunkMetadata::FromHeapObject(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::HeapLayout::InYoungGeneration(), and v8::internal::kTaggedNullAddress.
Referenced by v8::internal::YoungGenerationRootMarkingVisitor::VisitPointersImpl().
VisitObjectViaSlotInRememberedSet()
template<YoungGenerationMarkingVisitationMode marking_mode>
template<typename TSlot >
bool v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitObjectViaSlotInRememberedSet (TSlot slot) [inline]
Definition at line 155 of file young-generation-marking-visitor-inl.h.
                {
  if constexpr (marking_mode ==
                YoungGenerationMarkingVisitationMode::kConcurrent) {
    return VisitObjectViaSlot<ObjectVisitationMode::kPushToWorklist,
                              SlotTreatmentMode::kReadOnly>(slot);
  } else {
    return VisitObjectViaSlot<ObjectVisitationMode::kVisitDirectly,
                              SlotTreatmentMode::kReadWrite>(slot);
  }
}
References v8::internal::kConcurrent.
VisitPointer() [1/2]
template<YoungGenerationMarkingVisitationMode marking_mode>
void v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitPointer (Tagged< HeapObject > host, MaybeObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 62 of file young-generation-marking-visitor.h.
                                                       {
    VisitPointersImpl(host, p, p + 1);
  }
References v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitPointersImpl().
VisitPointer() [2/2]
template<YoungGenerationMarkingVisitationMode marking_mode>
void v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitPointer (Tagged< HeapObject > host, ObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 59 of file young-generation-marking-visitor.h.
                                                                           {
    VisitPointersImpl(host, p, p + 1);
  }
References v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitPointersImpl().
VisitPointers() [1/2]
template<YoungGenerationMarkingVisitationMode marking_mode>
void v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 55 of file young-generation-marking-visitor.h.
                                                          {
    VisitPointersImpl(host, start, end);
  }
References v8::internal::compiler::end(), and v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitPointersImpl().
VisitPointers() [2/2]
template<YoungGenerationMarkingVisitationMode marking_mode>
void v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 51 of file young-generation-marking-visitor.h.
                                                     {
    VisitPointersImpl(host, start, end);
  }
References v8::internal::compiler::end(), and v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitPointersImpl().
VisitPointersImpl()
template<YoungGenerationMarkingVisitationMode marking_mode>
template<typename TSlot >
void v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitPointersImpl (Tagged< HeapObject > host, TSlot start, TSlot end) [inline], [private]
Definition at line 138 of file young-generation-marking-visitor-inl.h.
                                                     {
  for (TSlot slot = start; slot < end; ++slot) {
    if constexpr (marking_mode ==
                  YoungGenerationMarkingVisitationMode::kConcurrent) {
      VisitObjectViaSlot<ObjectVisitationMode::kPushToWorklist,
                         SlotTreatmentMode::kReadOnly>(slot);
    } else {
      VisitObjectViaSlot<ObjectVisitationMode::kPushToWorklist,
                         SlotTreatmentMode::kReadWrite>(slot);
    }
  }
}
References v8::internal::compiler::end(), and v8::internal::kConcurrent.
Referenced by v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitPointer(), and v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitPointers().
Member Data Documentation
ephemeron_table_list_local_
template<YoungGenerationMarkingVisitationMode marking_mode>
EphemeronRememberedSet::TableList::Local v8::internal::YoungGenerationMarkingVisitor< marking_mode >::ephemeron_table_list_local_ [private]
Definition at line 133 of file young-generation-marking-visitor.h.
Referenced by v8::internal::YoungGenerationMarkingVisitor< marking_mode >::PublishWorklists().
isolate_
template<YoungGenerationMarkingVisitationMode marking_mode>
Isolate* const v8::internal::YoungGenerationMarkingVisitor< marking_mode >::isolate_ [private]
Definition at line 131 of file young-generation-marking-visitor.h.
kEntriesMask
template<YoungGenerationMarkingVisitationMode marking_mode>
constexpr size_t v8::internal::YoungGenerationMarkingVisitor< marking_mode >::kEntriesMask = kNumEntries - 1 [static], [constexpr], [private]
Definition at line 125 of file young-generation-marking-visitor.h.
kNumEntries
template<YoungGenerationMarkingVisitationMode marking_mode>
constexpr size_t v8::internal::YoungGenerationMarkingVisitor< marking_mode >::kNumEntries = 128 [static], [constexpr], [private]
Definition at line 124 of file young-generation-marking-visitor.h.
live_bytes_data_
template<YoungGenerationMarkingVisitationMode marking_mode>
std::array<std::pair<MutablePageMetadata*, size_t>, kNumEntries> v8::internal::YoungGenerationMarkingVisitor< marking_mode >::live_bytes_data_ [private]
Definition at line 129 of file young-generation-marking-visitor.h.
local_pretenuring_feedback_
template<YoungGenerationMarkingVisitationMode marking_mode>
PretenuringHandler::PretenuringFeedbackMap* const v8::internal::YoungGenerationMarkingVisitor< marking_mode >::local_pretenuring_feedback_ [private]
Definition at line 135 of file young-generation-marking-visitor.h.
marking_worklists_local_
template<YoungGenerationMarkingVisitationMode marking_mode>
MarkingWorklists::Local v8::internal::YoungGenerationMarkingVisitor< marking_mode >::marking_worklists_local_ [private]
Definition at line 132 of file young-generation-marking-visitor.h.
Referenced by v8::internal::YoungGenerationMarkingVisitor< marking_mode >::marking_worklists_local(), and v8::internal::YoungGenerationMarkingVisitor< marking_mode >::PublishWorklists().
pretenuring_handler_
template<YoungGenerationMarkingVisitationMode marking_mode>
PretenuringHandler* const v8::internal::YoungGenerationMarkingVisitor< marking_mode >::pretenuring_handler_ [private]
Definition at line 134 of file young-generation-marking-visitor.h.
shortcut_strings_
template<YoungGenerationMarkingVisitationMode marking_mode>
const bool v8::internal::YoungGenerationMarkingVisitor< marking_mode >::shortcut_strings_ [private]
Definition at line 136 of file young-generation-marking-visitor.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/young-generation-marking-visitor.h
/mnt/V8SourceCode/src/heap/young-generation-marking-visitor-inl.h