v8::internal::compiler::Reducer Class Reference
#include <graph-reducer.h>
Public Member Functions
virtual ~Reducer ()=default
virtual const char * reducer_name () const =0
Reduction Reduce (Node *node, ObserveNodeManager *observe_node_manager)
virtual void Finalize ()
Static Public Member Functions
static Reduction NoChange ()
static Reduction Replace (Node *node)
static Reduction Changed (Node *node)
Private Member Functions
virtual Reduction Reduce (Node *node)=0
Detailed Description
Definition at line 55 of file graph-reducer.h.
Constructor & Destructor Documentation
 Reducer()
virtual v8::internal::compiler::Reducer::~Reducer () [virtual], [default]
Member Function Documentation
Changed()
static Reduction v8::internal::compiler::Reducer::Changed (Node * node) [inline], [static]
Definition at line 73 of file graph-reducer.h.
{ return Reduction(node); }
Referenced by v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::SelectLowering::LowerSelect(), v8::internal::compiler::GraphReducer::Reduce(), v8::internal::compiler::JSGenericLowering::Reduce(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::WasmEscapeAnalysis::ReduceAllocateRaw(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferIsView(), v8::internal::compiler::JSCallReducer::ReduceArrayConstructor(), v8::internal::compiler::JSCallReducer::ReduceArrayIsArray(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::WasmGCOperatorReducer::ReduceAssertNotNull(), v8::internal::compiler::JSCallReducer::ReduceBigIntConstructor(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceEagerDeoptimize(), v8::internal::compiler::JSCallReducer::ReduceForInsufficientFeedback(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeHasInstance(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), v8::internal::compiler::JSContextSpecialization::ReduceJSGetImportMeta(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToString(), v8::internal::compiler::MemoryLowering::ReduceLoadElement(), v8::internal::compiler::MemoryLowering::ReduceLoadExternalPointerField(), v8::internal::compiler::MemoryLowering::ReduceLoadField(), v8::internal::compiler::MemoryLowering::ReduceLoadFromObject(), v8::internal::compiler::MemoryLowering::ReduceLoadMap(), v8::internal::compiler::JSCallReducer::ReduceNumberConstructor(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSCallReducer::ReduceObjectConstructor(), v8::internal::compiler::JSCallReducer::ReduceObjectCreate(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeIsPrototypeOf(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReducePromiseResolveTrampoline(), v8::internal::compiler::JSCallReducer::ReduceReflectApply(), v8::internal::compiler::JSCallReducer::ReduceReflectConstruct(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::compiler::JSCallReducer::ReduceReflectHas(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberComparison(), v8::internal::compiler::MemoryLowering::ReduceStore(), v8::internal::compiler::MemoryLowering::ReduceStoreElement(), v8::internal::compiler::MemoryLowering::ReduceStoreField(), v8::internal::compiler::MemoryLowering::ReduceStoreToObject(), v8::internal::compiler::JSCallReducer::ReduceStringConstructor(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContextNoCell(), v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::RedundancyElimination::UpdateChecks(), v8::internal::compiler::WasmGCOperatorReducer::UpdateNodeAndAliasesTypes(), and v8::internal::compiler::Typer::Visitor::UpdateType().
Finalize()
void v8::internal::compiler::Reducer::Finalize () [virtual]
Reimplemented in v8::internal::compiler::LateEscapeAnalysis, v8::internal::compiler::anonymous_namespace{pipeline.cc}::NodeOriginsWrapper, v8::internal::compiler::anonymous_namespace{pipeline.cc}::SourcePositionWrapper, v8::internal::compiler::JSInliningHeuristic, and v8::internal::compiler::JSCallReducer.
Definition at line 30 of file graph-reducer.cc.
{}
NoChange()
static Reduction v8::internal::compiler::Reducer::NoChange () [inline], [static]
Definition at line 71 of file graph-reducer.h.
{ return Reduction(); }
Referenced by v8::internal::compiler::MapInference::NoChange(), v8::internal::compiler::GraphReducer::Reduce(), v8::internal::compiler::JSCallReducer::Reduce(), v8::internal::compiler::JSContextSpecialization::Reduce(), v8::internal::compiler::JSGenericLowering::Reduce(), v8::internal::compiler::JSInliningHeuristic::Reduce(), v8::internal::compiler::JSNativeContextSpecialization::Reduce(), v8::internal::compiler::LateEscapeAnalysis::Reduce(), v8::internal::compiler::RedundancyElimination::Reduce(), v8::internal::compiler::SimplifyTFLoops::Reduce(), v8::internal::compiler::WasmEscapeAnalysis::Reduce(), v8::internal::compiler::WasmGCLowering::Reduce(), v8::internal::compiler::WasmGCOperatorReducer::Reduce(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::MemoryLowering::Reduce(), v8::internal::compiler::SelectLowering::Reduce(), v8::internal::compiler::Typer::Visitor::Reduce(), v8::internal::compiler::WasmEscapeAnalysis::ReduceAllocateRaw(), v8::internal::compiler::JSCallReducer::ReduceArrayConstructor(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeAt(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::WasmGCOperatorReducer::ReduceAssertNotNull(), v8::internal::compiler::JSCallReducer::ReduceBigIntAsN(), v8::internal::compiler::JSCallReducer::ReduceBigIntConstructor(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::RedundancyElimination::ReduceCheckNode(), v8::internal::compiler::WasmGCOperatorReducer::ReduceCheckNull(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteration(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeHas(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeSize(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetField(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetTime(), v8::internal::compiler::JSNativeContextSpecialization::ReduceEagerDeoptimize(), v8::internal::compiler::RedundancyElimination::ReduceEffectPhi(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccessOnString(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), v8::internal::compiler::JSCallReducer::ReduceForInsufficientFeedback(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsFinite(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsNaN(), v8::internal::compiler::WasmGCOperatorReducer::ReduceIf(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAdd(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionEnter(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionReject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionResolve(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithSpread(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSDefineKeyedOwnProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSDefineKeyedOwnPropertyInLiteral(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSDefineNamedOwnProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSContextSpecialization::ReduceJSGetImportMeta(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetSuperConstructor(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSHasProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamed(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamedFromSuper(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSPromiseResolve(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSSetKeyedProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSSetNamedProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreInArrayLiteral(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToString(), v8::internal::compiler::JSCallReducer::ReduceMapPrototypeGet(), v8::internal::compiler::JSCallReducer::ReduceMathBinary(), v8::internal::compiler::JSCallReducer::ReduceMathClz32(), v8::internal::compiler::JSCallReducer::ReduceMathImul(), v8::internal::compiler::JSCallReducer::ReduceMathMinMax(), v8::internal::compiler::JSCallReducer::ReduceMathUnary(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::WasmGCOperatorReducer::ReduceMerge(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::JSCallReducer::ReduceObjectConstructor(), v8::internal::compiler::JSCallReducer::ReduceObjectCreate(), v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototype(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeIsPrototypeOf(), v8::internal::compiler::RedundancyElimination::ReduceOtherNode(), v8::internal::compiler::JSContextSpecialization::ReduceParameter(), v8::internal::compiler::JSCallReducer::ReducePromiseConstructor(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), v8::internal::compiler::JSCallReducer::ReducePromiseResolveTrampoline(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberComparison(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberOperation(), v8::internal::compiler::MemoryLowering::ReduceStore(), v8::internal::compiler::JSCallReducer::ReduceStringConstructor(), v8::internal::compiler::JSCallReducer::ReduceStringFromCharCode(), v8::internal::compiler::JSCallReducer::ReduceStringFromCodePoint(), v8::internal::compiler::JSCallReducer::ReduceStringIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeConcat(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIterator(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStartsWith(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCharCodeAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCodePointAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstring(), v8::internal::compiler::WasmGCOperatorReducer::ReduceTypeGuard(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmStructOperation(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContextNoCell(), v8::internal::compiler::RedundancyElimination::TakeChecksFromFirstEffect(), v8::internal::compiler::RedundancyElimination::UpdateChecks(), v8::internal::compiler::WasmGCOperatorReducer::UpdateNodeAndAliasesTypes(), and v8::internal::compiler::Typer::Visitor::UpdateType().
Reduce() [1/2]
virtual Reduction v8::internal::compiler::Reducer::Reduce (Node * node) [private], [pure virtual]
Implemented in v8::internal::compiler::Typer::Visitor, v8::internal::compiler::SelectLowering, v8::internal::compiler::MemoryLowering, v8::internal::compiler::WasmTyper, v8::internal::compiler::WasmGCOperatorReducer, v8::internal::compiler::WasmGCLowering, v8::internal::compiler::WasmEscapeAnalysis, v8::internal::compiler::SimplifyTFLoops, v8::internal::compiler::RedundancyElimination, v8::internal::compiler::anonymous_namespace{pipeline.cc}::NodeOriginsWrapper, v8::internal::compiler::anonymous_namespace{pipeline.cc}::SourcePositionWrapper, v8::internal::compiler::LateEscapeAnalysis, v8::internal::compiler::JSNativeContextSpecialization, v8::internal::compiler::JSInliner, v8::internal::compiler::JSInliningHeuristic, v8::internal::compiler::JSGenericLowering, v8::internal::compiler::JSContextSpecialization, and v8::internal::compiler::JSCallReducer.
Reduce() [2/2]
Reduction v8::internal::compiler::Reducer::Reduce (Node * node, ObserveNodeManager * observe_node_manager)
Definition at line 32 of file graph-reducer.cc.
                                                                    {
  Reduction reduction = Reduce(node);
  if (V8_UNLIKELY(observe_node_manager && reduction.Changed())) {
    observe_node_manager->OnNodeChanged(reducer_name(), node,
                                        reduction.replacement());
  }
  return reduction;
}
References v8::internal::compiler::Reduction::Changed(), v8::internal::compiler::ObserveNodeManager::OnNodeChanged(), reducer_name(), v8::internal::compiler::Reduction::replacement(), and V8_UNLIKELY.
reducer_name()
virtual const char* v8::internal::compiler::Reducer::reducer_name () const [pure virtual]
Implemented in v8::internal::compiler::WasmTyper, v8::internal::compiler::WasmGCOperatorReducer, v8::internal::compiler::WasmGCLowering, v8::internal::compiler::WasmEscapeAnalysis, v8::internal::compiler::SimplifyTFLoops, v8::internal::compiler::Typer::Visitor, v8::internal::compiler::SelectLowering, v8::internal::compiler::RedundancyElimination, v8::internal::compiler::anonymous_namespace{pipeline.cc}::NodeOriginsWrapper, v8::internal::compiler::anonymous_namespace{pipeline.cc}::SourcePositionWrapper, v8::internal::compiler::MemoryLowering, v8::internal::compiler::LateEscapeAnalysis, v8::internal::compiler::JSNativeContextSpecialization, v8::internal::compiler::JSInliner, v8::internal::compiler::JSInliningHeuristic, v8::internal::compiler::JSGenericLowering, v8::internal::compiler::JSContextSpecialization, and v8::internal::compiler::JSCallReducer.
Referenced by Reduce().
Replace()
static Reduction v8::internal::compiler::Reducer::Replace (Node * node) [inline], [static]
Definition at line 72 of file graph-reducer.h.
{ return Reduction(node); }
Referenced by v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::MemoryLowering::ReduceLoadBoundedSize(), v8::internal::compiler::MemoryLowering::ReduceLoadExternalPointerField(), v8::internal::compiler::MemoryLowering::ReduceLoadMap(), and v8::internal::compiler::AdvancedReducer::Replace().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/graph-reducer.h
/mnt/V8SourceCode/src/compiler/graph-reducer.cc