v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxyPrototype Class Reference
Static Public Member Functions
static DirectHandle< JSObject > Create (Isolate *isolate)
Static Private Member Functions
static v8::Local< v8::FunctionTemplate > CreateTemplate (v8::Isolate *isolate)
static MaybeDirectHandle< Object > GetNamedProperty (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< String > name)
static v8::Intercepted NamedGetter (Local< v8::Name > name, const PropertyCallbackInfo< v8::Value > &info)
Detailed Description
Definition at line 559 of file debug-wasm-objects.cc.
Member Function Documentation
Create()
static DirectHandle<JSObject> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxyPrototype::Create (Isolate * isolate) [inline], [static]
Definition at line 561 of file debug-wasm-objects.cc.
                                                         {
    auto object_map =
        GetOrCreateDebugProxyMap(isolate, kContextProxy, &CreateTemplate);
    return isolate->factory()->NewJSObjectFromMap(
        object_map, AllocationType::kYoung,
        DirectHandle<AllocationSite>::null(), NewJSObjectType::kAPIWrapper);
  }
References v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateDebugProxyMap(), v8::internal::kAPIWrapper, v8::internal::anonymous_namespace{debug-wasm-objects.cc}::kContextProxy, v8::internal::kYoung, and v8::internal::Factory::NewJSObjectFromMap().
CreateTemplate()
static v8::Local<v8::FunctionTemplate> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxyPrototype::CreateTemplate (v8::Isolate * isolate) [inline], [static], [private]
Definition at line 570 of file debug-wasm-objects.cc.
                                                                        {
    Local<v8::FunctionTemplate> templ = v8::FunctionTemplate::New(isolate);
    templ->InstanceTemplate()->SetHandler(v8::NamedPropertyHandlerConfiguration(
        &NamedGetter, {}, {}, {}, {}, {}, {}, {},
        static_cast<v8::PropertyHandlerFlags>(
            static_cast<unsigned>(
                v8::PropertyHandlerFlags::kOnlyInterceptStrings) |
            static_cast<unsigned>(
                v8::PropertyHandlerFlags::kHasNoSideEffect))));
    return templ;
  }
References v8::kHasNoSideEffect, v8::kOnlyInterceptStrings, and v8::FunctionTemplate::New().
GetNamedProperty()
static MaybeDirectHandle<Object> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxyPrototype::GetNamedProperty (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< String > name) [inline], [static], [private]
Definition at line 582 of file debug-wasm-objects.cc.
                                 {
    if (name->length() != 0 && name->Get(0) == '$') {
      const char* kDelegateNames[] = {"memories", "locals", "tables",
                                      "functions", "globals"};
      for (auto delegate_name : kDelegateNames) {
        DirectHandle<JSAny> delegate;
        ASSIGN_RETURN_ON_EXCEPTION(isolate, delegate,
                                   Cast<JSAny>(JSObject::GetProperty(
                                       isolate, receiver, delegate_name)));
        if (!IsUndefined(*delegate, isolate)) {
          DirectHandle<Object> value;
          ASSIGN_RETURN_ON_EXCEPTION(
              isolate, value, Object::GetProperty(isolate, delegate, name));
          if (!IsUndefined(*value, isolate)) return value;
        }
      }
    }
    return {};
  }
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Object::GetProperty(), v8::internal::name, and v8::internal::value.
NamedGetter()
static v8::Intercepted v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxyPrototype::NamedGetter (Local< v8::Name > name, const PropertyCallbackInfo< v8::Value > & info) [inline], [static], [private]
Definition at line 604 of file debug-wasm-objects.cc.
                                                                     {
    auto name_string = Cast<String>(Utils::OpenHandle(*name));
    auto isolate = reinterpret_cast<Isolate*>(info.GetIsolate());
    auto receiver = Cast<JSObject>(Utils::OpenHandle(*info.This()));
    DirectHandle<Object> value;
    if (GetNamedProperty(isolate, receiver, name_string).ToHandle(&value)) {
      info.GetReturnValue().Set(Utils::ToLocal(value));
      return v8::Intercepted::kYes;
    }
    return v8::Intercepted::kNo;
  }
References v8::PropertyCallbackInfo< T >::GetIsolate(), v8::PropertyCallbackInfo< T >::GetReturnValue(), v8::kNo, v8::kYes, v8::internal::name, v8::Utils::OpenHandle(), v8::PropertyCallbackInfo< T >::This(), v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-wasm-objects.cc