v8::internal::Factory::CodeBuilder Class Reference
#include <factory.h>
Public Member Functions
CodeBuilder (Isolate *isolate, const CodeDesc &desc, CodeKind kind)
CodeBuilder (LocalIsolate *local_isolate, const CodeDesc &desc, CodeKind kind)
V8_WARN_UNUSED_RESULT Handle< Code > Build ()
V8_WARN_UNUSED_RESULT MaybeHandle< Code > TryBuild ()
CodeBuilder & set_self_reference (Handle< Object > self_reference)
CodeBuilder & set_builtin (Builtin builtin)
CodeBuilder & set_inlined_bytecode_size (uint32_t size)
CodeBuilder & set_osr_offset (BytecodeOffset offset)
CodeBuilder & set_source_position_table (Handle< TrustedByteArray > table)
CodeBuilder & set_empty_source_position_table ()
CodeBuilder & set_bytecode_offset_table (Handle< TrustedByteArray > table)
CodeBuilder & set_deoptimization_data (Handle< DeoptimizationData > deopt_data)
CodeBuilder & set_interpreter_data (Handle< TrustedObject > interpreter_data)
CodeBuilder & set_is_context_specialized ()
CodeBuilder & set_is_turbofanned ()
CodeBuilder & set_stack_slots (int stack_slots)
CodeBuilder & set_parameter_count (uint16_t parameter_count)
CodeBuilder & set_profiler_data (BasicBlockProfilerData *profiler_data)
Private Member Functions
MaybeHandle< Code > BuildInternal (bool retry_allocation_or_fail)
DirectHandle< TrustedByteArray > NewTrustedByteArray (int length)
Tagged< HeapObject > AllocateUninitializedInstructionStream (bool retry_allocation_or_fail)
Handle< Code > NewCode (const NewCodeOptions &options)
Private Attributes
Isolate *const isolate_
LocalIsolate * local_isolate_
const CodeDesc & code_desc_
const CodeKind kind_
MaybeHandle< Object > self_reference_
Builtin builtin_ = Builtin::kNoBuiltinId
uint32_t inlined_bytecode_size_ = 0
BytecodeOffset osr_offset_ = BytecodeOffset::None()
MaybeHandle< TrustedByteArray > bytecode_offset_table_
MaybeHandle< TrustedByteArray > source_position_table_
MaybeHandle< DeoptimizationData > deoptimization_data_
MaybeHandle< TrustedObject > interpreter_data_
BasicBlockProfilerData * profiler_data_ = nullptr
bool is_context_specialized_ = false
bool is_turbofanned_ = false
uint32_t stack_slots_ = 0
uint16_t parameter_count_ = 0
Detailed Description
Definition at line 1156 of file factory.h.
Constructor & Destructor Documentation
CodeBuilder() [1/2]
v8::internal::Factory::CodeBuilder::CodeBuilder (Isolate * isolate, const CodeDesc & desc, CodeKind kind)
Definition at line 105 of file factory.cc.
    : isolate_(isolate),
      local_isolate_(isolate_->main_thread_local_isolate()),
      code_desc_(desc),
      kind_(kind) {}
CodeBuilder() [2/2]
v8::internal::Factory::CodeBuilder::CodeBuilder (LocalIsolate * local_isolate, const CodeDesc & desc, CodeKind kind)
Definition at line 112 of file factory.cc.
    : isolate_(local_isolate->GetMainThreadIsolateUnsafe()),
      local_isolate_(local_isolate),
      code_desc_(desc),
      kind_(kind) {}
Member Function Documentation
AllocateUninitializedInstructionStream()
Tagged< HeapObject > v8::internal::Factory::CodeBuilder::AllocateUninitializedInstructionStream (bool retry_allocation_or_fail) [private]
Definition at line 264 of file factory.cc.
                                   {
  LocalHeap* heap = local_isolate_->heap();
  Tagged<HeapObject> result;
  const int object_size = InstructionStream::SizeFor(code_desc_.body_size());
  if (retry_allocation_or_fail) {
    // Only allowed to do `retry_allocation_or_fail` from the main thread.
    // TODO(leszeks): Remove the retrying allocation, always use TryBuild in
    // the code builder.
    DCHECK(local_isolate_->is_main_thread());
    result =
        heap->heap()->allocator()->AllocateRawWith<HeapAllocator::kRetryOrFail>(
            object_size, AllocationType::kCode, AllocationOrigin::kRuntime);
    CHECK(!result.is_null());
    return result;
  } else {
    // Return null if we cannot allocate the code object.
    return heap->AllocateRawWith<HeapAllocator::kLightRetry>(
        object_size, AllocationType::kCode);
  }
}
References CHECK, v8::internal::DCHECK(), v8::internal::kCode, v8::internal::HeapAllocator::kLightRetry, v8::internal::HeapAllocator::kRetryOrFail, v8::internal::kRuntime, v8::base::internal::result, and v8::internal::InstructionStream::SizeFor().
Build()
Handle< Code > v8::internal::Factory::CodeBuilder::Build ()
Definition at line 290 of file factory.cc.
                                       {
  return BuildInternal(true).ToHandleChecked();
}
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildAdaptor(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildPlaceholder(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler(), v8::internal::Builtins::CreateInterpreterEntryTrampolineForProfiling(), and v8::internal::RegExpMacroAssemblerRISCV::GetCode().
BuildInternal()
MaybeHandle< Code > v8::internal::Factory::CodeBuilder::BuildInternal (bool retry_allocation_or_fail) [private]
Definition at line 128 of file factory.cc.
                                   {
  DirectHandle<TrustedByteArray> reloc_info =
      NewTrustedByteArray(code_desc_.reloc_size);
  // Basic block profiling data for builtins is stored in the JS heap rather
  // than in separately-allocated C++ objects. Allocate that data now if
  // appropriate.
  DirectHandle<OnHeapBasicBlockProfilerData> on_heap_profiler_data;
  if (V8_UNLIKELY(profiler_data_ && isolate_->IsGeneratingEmbeddedBuiltins())) {
    on_heap_profiler_data = profiler_data_->CopyToJSHeap(isolate_);
    // Add the on-heap data to a global list, which keeps it alive and allows
    // iteration.
    DirectHandle<ArrayList> list(isolate_->heap()->basic_block_profiling_data(),
                                 isolate_);
    DirectHandle<ArrayList> new_list = ArrayList::Add(
        isolate_, list, on_heap_profiler_data, AllocationType::kOld);
    isolate_->heap()->SetBasicBlockProfilingData(new_list);
  }
  Tagged<HeapObject> istream_allocation =
      AllocateUninitializedInstructionStream(retry_allocation_or_fail);
  if (istream_allocation.is_null()) {
    return {};
  }
  Handle<InstructionStream> istream;
  {
    // The InstructionStream object has not been fully initialized yet. We
    // rely on the fact that no allocation will happen from this point on.
    DisallowGarbageCollection no_gc;
    Tagged<InstructionStream> raw_istream = InstructionStream::Initialize(
        istream_allocation,
        ReadOnlyRoots(local_isolate_).instruction_stream_map(),
        code_desc_.body_size(), code_desc_.constant_pool_offset, *reloc_info);
    istream = handle(raw_istream, local_isolate_);
    DCHECK(IsAligned(istream->instruction_start(), kCodeAlignment));
    DCHECK_IMPLIES(!local_isolate_->heap()->heap()->code_region().is_empty(),
                   local_isolate_->heap()->heap()->code_region().contains(
                       istream->address()));
  }
  Handle<Code> code;
  {
    static_assert(InstructionStream::kOnHeapBodyIsContiguous);
    NewCodeOptions new_code_options = {
        kind_,
        builtin_,
        is_context_specialized_,
        is_turbofanned_,
        parameter_count_,
        code_desc_.instruction_size(),
        code_desc_.metadata_size(),
        inlined_bytecode_size_,
        osr_offset_,
        code_desc_.handler_table_offset_relative(),
        code_desc_.constant_pool_offset_relative(),
        code_desc_.code_comments_offset_relative(),
        code_desc_.jump_table_info_offset_relative(),
        code_desc_.unwinding_info_offset_relative(),
        interpreter_data_,
        deoptimization_data_,
        bytecode_offset_table_,
        source_position_table_,
        istream,
        /*instruction_start=*/kNullAddress,
    };
    code = NewCode(new_code_options);
    DCHECK_EQ(istream->body_size(), code->body_size());
    {
      DisallowGarbageCollection no_gc;
      Tagged<InstructionStream> raw_istream = *istream;
      // Allow self references to created code object by patching the handle to
      // point to the newly allocated InstructionStream object.
      Handle<Object> self_reference;
      if (self_reference_.ToHandle(&self_reference)) {
        DCHECK_EQ(*self_reference,
                  ReadOnlyRoots(isolate_).self_reference_marker());
        DCHECK_NE(kind_, CodeKind::BASELINE);
        if (isolate_->IsGeneratingEmbeddedBuiltins()) {
          isolate_->builtins_constants_table_builder()->PatchSelfReference(
              self_reference, istream);
        }
        self_reference.PatchValue(raw_istream);
      }
      // Likewise, any references to the basic block counters marker need to be
      // updated to point to the newly-allocated counters array.
      if (V8_UNLIKELY(!on_heap_profiler_data.is_null())) {
        isolate_->builtins_constants_table_builder()
            ->PatchBasicBlockCountersReference(
                handle(on_heap_profiler_data->counts(), isolate_));
      }
      // Migrate generated code.
      // The generated code can contain embedded objects (typically from
      // handles) in a pointer-to-tagged-value format (i.e. with indirection
      // like a handle) that are dereferenced during the copy to point
      // directly to the actual heap objects. These pointers can include
      // references to the code object itself, through the self_reference
      // parameter.
      istream->Finalize(*code, *reloc_info, code_desc_, isolate_->heap());
#ifdef VERIFY_HEAP
      if (v8_flags.verify_heap) {
        HeapObject::VerifyCodePointer(isolate_, raw_istream);
      }
#endif
    }
  }
  // TODO(leszeks): Remove stack_slots_, it's already in the instruction stream.
  DCHECK_EQ(stack_slots_, code->stack_slots());
#ifdef ENABLE_DISASSEMBLER
  if (V8_UNLIKELY(profiler_data_ && v8_flags.turbo_profiling_verbose)) {
    std::ostringstream os;
    code->Disassemble(nullptr, os, isolate_);
    if (!on_heap_profiler_data.is_null()) {
      DirectHandle<String> disassembly =
          local_isolate_->factory()->NewStringFromAsciiChecked(
              os.str().c_str(), AllocationType::kOld);
      on_heap_profiler_data->set_code(*disassembly);
    } else {
      profiler_data_->SetCode(os);
    }
  }
#endif // ENABLE_DISASSEMBLER
  return code;
}
References v8::internal::ArrayList::Add(), v8::internal::HandleBase::address(), code, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NE, v8::internal::handle(), v8::internal::InstructionStream::Initialize(), v8::internal::NewCodeOptions::instruction_size, v8::internal::DirectHandle< T >::is_null(), v8::internal::Tagged< HeapObject >::is_null(), IsAligned(), v8::internal::kCodeAlignment, v8::internal::kNullAddress, v8::internal::kOld, v8::internal::InstructionStream::kOnHeapBodyIsContiguous, v8::internal::FactoryBase< Factory >::NewCode(), v8::internal::FactoryBase< Factory >::NewTrustedByteArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Handle< T >::PatchValue(), v8::internal::v8_flags, and V8_UNLIKELY.
NewCode()
Handle< Code > v8::internal::Factory::CodeBuilder::NewCode (const NewCodeOptions & options) [private]
Definition at line 124 of file factory.cc.
                                                                      {
  return local_isolate_->factory()->NewCode(options);
}
NewTrustedByteArray()
DirectHandle< TrustedByteArray > v8::internal::Factory::CodeBuilder::NewTrustedByteArray (int length) [private]
Definition at line 119 of file factory.cc.
                {
  return local_isolate_->factory()->NewTrustedByteArray(length);
}
References v8::internal::Factory::length.
set_builtin()
CodeBuilder& v8::internal::Factory::CodeBuilder::set_builtin (Builtin builtin) [inline]
Definition at line 1181 of file factory.h.
                                              {
      DCHECK_IMPLIES(builtin != Builtin::kNoBuiltinId,
                     !CodeKindIsJSFunction(kind_));
      builtin_ = builtin;
      return *this;
    }
References v8::internal::CodeKindIsJSFunction(), and DCHECK_IMPLIES.
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildAdaptor(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildPlaceholder(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler(), v8::internal::Builtins::CreateInterpreterEntryTrampolineForProfiling(), and v8::internal::compiler::CodeGenerator::FinalizeCode().
set_bytecode_offset_table()
CodeBuilder& v8::internal::Factory::CodeBuilder::set_bytecode_offset_table (Handle< TrustedByteArray > table) [inline]
Definition at line 1209 of file factory.h.
                                                                           {
      DCHECK_EQ(kind_, CodeKind::BASELINE);
      DCHECK(!table.is_null());
      bytecode_offset_table_ = table;
      return *this;
    }
References DCHECK, DCHECK_EQ, and v8::internal::HandleBase::is_null().
Referenced by v8::internal::baseline::BaselineCompiler::Build().
set_deoptimization_data()
CodeBuilder& v8::internal::Factory::CodeBuilder::set_deoptimization_data (Handle< DeoptimizationData > deopt_data) [inline]
Definition at line 1216 of file factory.h.
                                               {
      DCHECK_NE(kind_, CodeKind::BASELINE);
      DCHECK(!deopt_data.is_null());
      deoptimization_data_ = deopt_data;
      return *this;
    }
References DCHECK, DCHECK_NE, and v8::internal::HandleBase::is_null().
Referenced by v8::internal::compiler::CodeGenerator::FinalizeCode().
set_empty_source_position_table()
Factory::CodeBuilder & v8::internal::Factory::CodeBuilder::set_empty_source_position_table () [inline]
Definition at line 144 of file factory-inl.h.
                                                                        {
  return set_source_position_table(
      isolate_->factory()->empty_trusted_byte_array());
}
References v8::internal::Isolate::factory(), isolate_, and set_source_position_table().
Referenced by v8::internal::RegExpMacroAssemblerRISCV::GetCode().
set_inlined_bytecode_size()
CodeBuilder& v8::internal::Factory::CodeBuilder::set_inlined_bytecode_size (uint32_t size) [inline]
Definition at line 1188 of file factory.h.
                                                          {
      DCHECK_IMPLIES(size != 0, CodeKindIsOptimizedJSFunction(kind_));
      inlined_bytecode_size_ = size;
      return *this;
    }
References v8::internal::CodeKindIsOptimizedJSFunction(), DCHECK_IMPLIES, and size().
Referenced by v8::internal::compiler::CodeGenerator::FinalizeCode().
set_interpreter_data()
Factory::CodeBuilder & v8::internal::Factory::CodeBuilder::set_interpreter_data (Handle< TrustedObject > interpreter_data) [inline]
Definition at line 149 of file factory-inl.h.
                                            {
  // This DCHECK requires this function to be in -inl.h.
  DCHECK(IsInterpreterData(*interpreter_data) ||
         IsBytecodeArray(*interpreter_data));
  interpreter_data_ = interpreter_data;
  return *this;
}
References v8::internal::DCHECK().
Referenced by v8::internal::baseline::BaselineCompiler::Build().
set_is_context_specialized()
CodeBuilder& v8::internal::Factory::CodeBuilder::set_is_context_specialized () [inline]
Definition at line 1227 of file factory.h.
                                              {
      DCHECK(!CodeKindIsUnoptimizedJSFunction(kind_));
      is_context_specialized_ = true;
      return *this;
    }
References v8::internal::CodeKindIsUnoptimizedJSFunction(), and DCHECK.
Referenced by v8::internal::compiler::CodeGenerator::FinalizeCode().
set_is_turbofanned()
CodeBuilder& v8::internal::Factory::CodeBuilder::set_is_turbofanned () [inline]
Definition at line 1233 of file factory.h.
                                      {
      DCHECK(!CodeKindIsUnoptimizedJSFunction(kind_));
      is_turbofanned_ = true;
      return *this;
    }
References v8::internal::CodeKindIsUnoptimizedJSFunction(), and DCHECK.
Referenced by v8::internal::compiler::CodeGenerator::FinalizeCode().
set_osr_offset()
CodeBuilder& v8::internal::Factory::CodeBuilder::set_osr_offset (BytecodeOffset offset) [inline]
Definition at line 1194 of file factory.h.
                                                       {
      DCHECK_IMPLIES(!offset.IsNone(), CodeKindCanOSR(kind_));
      osr_offset_ = offset;
      return *this;
    }
References v8::internal::CodeKindCanOSR(), DCHECK_IMPLIES, and v8::internal::BytecodeOffset::IsNone().
Referenced by v8::internal::compiler::CodeGenerator::FinalizeCode().
set_parameter_count()
CodeBuilder& v8::internal::Factory::CodeBuilder::set_parameter_count (uint16_t parameter_count) [inline]
Definition at line 1244 of file factory.h.
                                                               {
      parameter_count_ = parameter_count;
      return *this;
    }
Referenced by v8::internal::baseline::BaselineCompiler::Build(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildAdaptor(), and v8::internal::compiler::CodeGenerator::FinalizeCode().
set_profiler_data()
CodeBuilder& v8::internal::Factory::CodeBuilder::set_profiler_data (BasicBlockProfilerData * profiler_data) [inline]
Definition at line 1249 of file factory.h.
                                                                          {
      profiler_data_ = profiler_data;
      return *this;
    }
Referenced by v8::internal::compiler::CodeGenerator::FinalizeCode().
set_self_reference()
CodeBuilder& v8::internal::Factory::CodeBuilder::set_self_reference (Handle< Object > self_reference) [inline]
Definition at line 1175 of file factory.h.
                                                                   {
      DCHECK(!self_reference.is_null());
      self_reference_ = self_reference;
      return *this;
    }
References DCHECK, and v8::internal::HandleBase::is_null().
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildAdaptor(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildPlaceholder(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler(), and v8::internal::RegExpMacroAssemblerRISCV::GetCode().
set_source_position_table()
CodeBuilder& v8::internal::Factory::CodeBuilder::set_source_position_table (Handle< TrustedByteArray > table) [inline]
Definition at line 1200 of file factory.h.
                                                                           {
      DCHECK_NE(kind_, CodeKind::BASELINE);
      DCHECK(!table.is_null());
      source_position_table_ = table;
      return *this;
    }
References DCHECK, DCHECK_NE, and v8::internal::HandleBase::is_null().
Referenced by v8::internal::compiler::CodeGenerator::FinalizeCode(), and set_empty_source_position_table().
set_stack_slots()
CodeBuilder& v8::internal::Factory::CodeBuilder::set_stack_slots (int stack_slots) [inline]
Definition at line 1239 of file factory.h.
                                                  {
      stack_slots_ = stack_slots;
      return *this;
    }
Referenced by v8::internal::compiler::CodeGenerator::FinalizeCode().
TryBuild()
MaybeHandle< Code > v8::internal::Factory::CodeBuilder::TryBuild ()
Definition at line 286 of file factory.cc.
                                               {
  return BuildInternal(false);
}
Referenced by v8::internal::baseline::BaselineCompiler::Build(), and v8::internal::compiler::CodeGenerator::FinalizeCode().
Member Data Documentation
builtin_
Builtin v8::internal::Factory::CodeBuilder::builtin_ = Builtin::kNoBuiltinId [private]
Definition at line 1270 of file factory.h.
bytecode_offset_table_
MaybeHandle<TrustedByteArray> v8::internal::Factory::CodeBuilder::bytecode_offset_table_ [private]
Definition at line 1273 of file factory.h.
code_desc_
const CodeDesc& v8::internal::Factory::CodeBuilder::code_desc_ [private]
Definition at line 1266 of file factory.h.
deoptimization_data_
MaybeHandle<DeoptimizationData> v8::internal::Factory::CodeBuilder::deoptimization_data_ [private]
Definition at line 1275 of file factory.h.
inlined_bytecode_size_
uint32_t v8::internal::Factory::CodeBuilder::inlined_bytecode_size_ = 0 [private]
Definition at line 1271 of file factory.h.
interpreter_data_
MaybeHandle<TrustedObject> v8::internal::Factory::CodeBuilder::interpreter_data_ [private]
Definition at line 1276 of file factory.h.
is_context_specialized_
bool v8::internal::Factory::CodeBuilder::is_context_specialized_ = false [private]
Definition at line 1278 of file factory.h.
is_turbofanned_
bool v8::internal::Factory::CodeBuilder::is_turbofanned_ = false [private]
Definition at line 1279 of file factory.h.
isolate_
Isolate* const v8::internal::Factory::CodeBuilder::isolate_ [private]
Definition at line 1264 of file factory.h.
Referenced by set_empty_source_position_table().
kind_
const CodeKind v8::internal::Factory::CodeBuilder::kind_ [private]
Definition at line 1267 of file factory.h.
local_isolate_
LocalIsolate* v8::internal::Factory::CodeBuilder::local_isolate_ [private]
Definition at line 1265 of file factory.h.
osr_offset_
BytecodeOffset v8::internal::Factory::CodeBuilder::osr_offset_ = BytecodeOffset::None() [private]
Definition at line 1272 of file factory.h.
parameter_count_
uint16_t v8::internal::Factory::CodeBuilder::parameter_count_ = 0 [private]
Definition at line 1281 of file factory.h.
profiler_data_
BasicBlockProfilerData* v8::internal::Factory::CodeBuilder::profiler_data_ = nullptr [private]
Definition at line 1277 of file factory.h.
self_reference_
MaybeHandle<Object> v8::internal::Factory::CodeBuilder::self_reference_ [private]
Definition at line 1269 of file factory.h.
source_position_table_
MaybeHandle<TrustedByteArray> v8::internal::Factory::CodeBuilder::source_position_table_ [private]
Definition at line 1274 of file factory.h.
stack_slots_
uint32_t v8::internal::Factory::CodeBuilder::stack_slots_ = 0 [private]
Definition at line 1280 of file factory.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/factory.h
/mnt/V8SourceCode/src/heap/factory-inl.h
/mnt/V8SourceCode/src/heap/factory.cc