v8::internal::maglev::CheckValue Class Reference
#include <maglev-ir.h>
Public Member Functions
CheckValue (uint64_t bitfield, const compiler::HeapObjectRef value, DeoptimizeReason reason)
compiler::HeapObjectRef value () const
Input & target_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::EagerDeopt()
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
static constexpr int kTargetIndex = 0
Private Types
using Base = FixedInputNodeT< 1, CheckValue >
Private Attributes
const compiler::HeapObjectRef value_
Additional Inherited Members
Detailed Description
Definition at line 6898 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CheckValue::Base = FixedInputNodeT<1, CheckValue> [private]
Definition at line 6899 of file maglev-ir.h.
Constructor & Destructor Documentation
CheckValue()
v8::internal::maglev::CheckValue::CheckValue (uint64_t bitfield, const compiler::HeapObjectRef value, DeoptimizeReason reason) [inline], [explicit]
Definition at line 6902 of file maglev-ir.h.
      : Base(bitfield | ReasonField::encode(reason)), value_(value) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::CheckValue::GenerateCode (MaglevAssembler * , const ProcessingState &)
options()
auto v8::internal::maglev::CheckValue::options () const [inline]
Definition at line 6925 of file maglev-ir.h.
{ return std::tuple{value_, deoptimize_reason()}; }
PrintParams()
void v8::internal::maglev::CheckValue::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8089 of file maglev-ir.cc.
                                                                        {
  os << "(" << *value().object() << ", "
     << DeoptimizeReasonToString(deoptimize_reason()) << ")";
}
References v8::internal::DeoptimizeReasonToString(), v8::internal::compiler::HeapObjectRef::object(), and value().
SetValueLocationConstraints()
void v8::internal::maglev::CheckValue::SetValueLocationConstraints ()
target_input()
Input& v8::internal::maglev::CheckValue::target_input () [inline]
Definition at line 6913 of file maglev-ir.h.
{ return input(kTargetIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
value()
compiler::HeapObjectRef v8::internal::maglev::CheckValue::value () const [inline]
Definition at line 6910 of file maglev-ir.h.
{ return value_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::CheckValue::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 6908 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CheckValue::kProperties = OpProperties::EagerDeopt() [static], [constexpr]
Definition at line 6906 of file maglev-ir.h.
kTargetIndex
constexpr int v8::internal::maglev::CheckValue::kTargetIndex = 0 [static], [constexpr]
Definition at line 6912 of file maglev-ir.h.
value_
const compiler::HeapObjectRef v8::internal::maglev::CheckValue::value_ [private]
Definition at line 6930 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc