v8_inspector::TaskInfo Class Reference
Each JS task object created via console.createTask has a corresponding TaskInfo object on the C++ side (in a 1:1 relationship).
#include <v8-console.h>
Public Member Functions
TaskInfo (v8::Isolate *isolate, V8Console *console, v8::Local< v8::Object > task)
void * Id () const
void Cancel ()
Private Attributes
v8::Global< v8::Object > m_task
V8Console * m_console = nullptr
Detailed Description
Each JS task object created via console.createTask has a corresponding TaskInfo object on the C++ side (in a 1:1 relationship).
The TaskInfo holds on weakly to the JS task object. The JS task objects uses a private symbol to store a pointer to the TaskInfo object (via v8::External).
The TaskInfo objects holds all the necessary information we need to properly cancel the corresponding async task then the JS task object gets GC'ed.
Definition at line 240 of file v8-console.h.
Constructor & Destructor Documentation
TaskInfo()
v8_inspector::TaskInfo::TaskInfo (v8::Isolate * isolate, V8Console * console, v8::Local< v8::Object > task)
Definition at line 608 of file v8-console.cc.
    : m_task(isolate, task), m_console(console) {
  task->SetPrivate(isolate->GetCurrentContext(), console->taskInfoKey(),
                   v8::External::New(isolate, this))
      .Check();
  m_task.SetWeak(this, cleanupTaskInfo, v8::WeakCallbackType::kParameter);
}
References v8_inspector::anonymous_namespace{v8-console.cc}::cleanupTaskInfo(), v8::Isolate::GetCurrentContext(), v8::kParameter, m_task, v8::External::New(), v8::Object::SetPrivate(), v8::PersistentBase< T >::SetWeak(), and v8_inspector::V8Console::taskInfoKey().
Member Function Documentation
Cancel()
void v8_inspector::TaskInfo::Cancel () [inline]
Definition at line 253 of file v8-console.h.
{ m_console->cancelConsoleTask(this); }
References v8_inspector::V8Console::cancelConsoleTask(), and m_console.
Referenced by v8_inspector::anonymous_namespace{v8-console.cc}::cleanupTaskInfo().
Id()
void* v8_inspector::TaskInfo::Id () const [inline]
Definition at line 248 of file v8-console.h.
                   {
    return reinterpret_cast<void*>(reinterpret_cast<intptr_t>(this) << 1);
  }
Referenced by v8_inspector::V8Console::cancelConsoleTask().
Member Data Documentation
m_console
V8Console* v8_inspector::TaskInfo::m_console = nullptr [private]
Definition at line 257 of file v8-console.h.
Referenced by Cancel().
m_task
v8::Global<v8::Object> v8_inspector::TaskInfo::m_task [private]
Definition at line 256 of file v8-console.h.
Referenced by TaskInfo().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-console.h
/mnt/V8SourceCode/src/inspector/v8-console.cc