v8::internal::IsolateSafepoint::Barrier Class Reference
Public Member Functions
Barrier ()
void Arm ()
void Disarm ()
void WaitUntilRunningThreadsInSafepoint (const IsolateSafepoint::RunningLocalHeaps &running_threads)
void WaitInSafepoint ()
void WaitInUnpark ()
void NotifyPark ()
Private Member Functions
bool IsArmed ()
Private Attributes
base::Mutex mutex_
base::ConditionVariable cv_resume_
base::ConditionVariable cv_stopped_
bool armed_
size_t stopped_ = 0
Detailed Description
Definition at line 59 of file safepoint.h.
Constructor & Destructor Documentation
Barrier()
v8::internal::IsolateSafepoint::Barrier::Barrier () [inline]
Definition at line 70 of file safepoint.h.
: armed_(false), stopped_(0) {}
Member Function Documentation
Arm()
void v8::internal::IsolateSafepoint::Barrier::Arm ()
Definition at line 231 of file safepoint.cc.
                                  {
  base::MutexGuard guard(&mutex_);
  DCHECK(!IsArmed());
  armed_ = true;
  stopped_ = 0;
}
References armed_, v8::internal::DCHECK(), IsArmed(), mutex_, and stopped_.
Referenced by v8::internal::IsolateSafepoint::EnterLocalSafepointScope(), and v8::internal::IsolateSafepoint::InitiateGlobalSafepointScopeRaw().
Disarm()
void v8::internal::IsolateSafepoint::Barrier::Disarm ()
Definition at line 238 of file safepoint.cc.
                                     {
  base::MutexGuard guard(&mutex_);
  DCHECK(IsArmed());
  armed_ = false;
  stopped_ = 0;
  cv_resume_.NotifyAll();
}
References v8::internal::DCHECK().
Referenced by v8::internal::IsolateSafepoint::LeaveGlobalSafepointScope(), and v8::internal::IsolateSafepoint::LeaveLocalSafepointScope().
IsArmed()
bool v8::internal::IsolateSafepoint::Barrier::IsArmed () [inline], [private]
Definition at line 67 of file safepoint.h.
{ return armed_; }
References armed_.
Referenced by Arm().
NotifyPark()
void v8::internal::IsolateSafepoint::Barrier::NotifyPark ()
Definition at line 266 of file safepoint.cc.
                                         {
  base::MutexGuard guard(&mutex_);
  CHECK(IsArmed());
  stopped_++;
  cv_stopped_.NotifyOne();
}
References CHECK.
Referenced by v8::internal::IsolateSafepoint::NotifyPark().
WaitInSafepoint()
void v8::internal::IsolateSafepoint::Barrier::WaitInSafepoint ()
Definition at line 273 of file safepoint.cc.
                                              {
  const auto scoped_blocking_call =
      V8::GetCurrentPlatform()->CreateBlockingScope(BlockingType::kWillBlock);
  base::MutexGuard guard(&mutex_);
  CHECK(IsArmed());
  stopped_++;
  cv_stopped_.NotifyOne();
  while (IsArmed()) {
    cv_resume_.Wait(&mutex_);
  }
}
References CHECK, v8::Platform::CreateBlockingScope(), v8::internal::V8::GetCurrentPlatform(), and v8::kWillBlock.
Referenced by v8::internal::IsolateSafepoint::WaitInSafepoint().
WaitInUnpark()
void v8::internal::IsolateSafepoint::Barrier::WaitInUnpark ()
Definition at line 286 of file safepoint.cc.
                                           {
  const auto scoped_blocking_call =
      V8::GetCurrentPlatform()->CreateBlockingScope(BlockingType::kWillBlock);
  base::MutexGuard guard(&mutex_);
  while (IsArmed()) {
    cv_resume_.Wait(&mutex_);
  }
}
References v8::Platform::CreateBlockingScope(), v8::internal::V8::GetCurrentPlatform(), and v8::kWillBlock.
Referenced by v8::internal::IsolateSafepoint::WaitInUnpark().
WaitUntilRunningThreadsInSafepoint()
void v8::internal::IsolateSafepoint::Barrier::WaitUntilRunningThreadsInSafepoint (const IsolateSafepoint::RunningLocalHeaps & running_threads)
Definition at line 246 of file safepoint.cc.
                                                                  {
  base::MutexGuard guard(&mutex_);
  DCHECK(IsArmed());
  size_t running_count = running_local_heaps.size();
  while (stopped_ < running_count) {
    cv_stopped_.Wait(&mutex_);
  }
#if V8_OS_DARWIN
  if (v8_flags.safepoint_bump_qos_class) {
    for (auto& running_local_heap : running_local_heaps) {
      CHECK_EQ(
          pthread_override_qos_class_end_np(running_local_heap.qos_override),
          0);
    }
  }
#endif
  DCHECK_EQ(stopped_, running_count);
}
References CHECK_EQ, v8::internal::DCHECK(), DCHECK_EQ, v8::base::SmallVector< T, kSize, Allocator >::size(), and v8::internal::v8_flags.
Referenced by v8::internal::IsolateSafepoint::EnterLocalSafepointScope(), and v8::internal::IsolateSafepoint::WaitUntilRunningThreadsInSafepoint().
Member Data Documentation
armed_
bool v8::internal::IsolateSafepoint::Barrier::armed_ [private]
Definition at line 63 of file safepoint.h.
Referenced by Arm(), and IsArmed().
cv_resume_
base::ConditionVariable v8::internal::IsolateSafepoint::Barrier::cv_resume_ [private]
Definition at line 61 of file safepoint.h.
cv_stopped_
base::ConditionVariable v8::internal::IsolateSafepoint::Barrier::cv_stopped_ [private]
Definition at line 62 of file safepoint.h.
mutex_
base::Mutex v8::internal::IsolateSafepoint::Barrier::mutex_ [private]
Definition at line 60 of file safepoint.h.
Referenced by Arm().
stopped_
size_t v8::internal::IsolateSafepoint::Barrier::stopped_ = 0 [private]
Definition at line 65 of file safepoint.h.
Referenced by Arm().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/safepoint.h
/mnt/V8SourceCode/src/heap/safepoint.cc