v8::internal::RootVisitor Class Reference
#include <visitors.h>
Public Member Functions
virtual ~RootVisitor ()=default
virtual void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end)=0
virtual void VisitRootPointer (Root root, const char *description, FullObjectSlot p)
virtual void VisitRootPointers (Root root, const char *description, OffHeapObjectSlot start, OffHeapObjectSlot end)
virtual void VisitRunningCode (FullObjectSlot code_slot, FullObjectSlot istream_or_smi_zero_slot)
virtual void Synchronize (VisitorSynchronization::SyncTag tag)
virtual GarbageCollector collector () const
Static Public Member Functions
static const char * RootName (Root root)
Detailed Description
Definition at line 65 of file visitors.h.
Constructor & Destructor Documentation
 RootVisitor()
virtual v8::internal::RootVisitor::~RootVisitor () [virtual], [default]
Member Function Documentation
collector()
virtual GarbageCollector v8::internal::RootVisitor::collector () const [inline], [virtual]
Reimplemented in v8::internal::YoungGenerationRootMarkingVisitor.
Definition at line 121 of file visitors.h.
                                             {
    return GarbageCollector::MARK_COMPACTOR;
  }
References v8::internal::MARK_COMPACTOR.
RootName()
const char * v8::internal::RootVisitor::RootName (Root root) [static]
Definition at line 17 of file visitors.cc.
                                           {
  switch (root) {
#define ROOT_CASE(root_id, description) \
  case Root::root_id: \
    return description;
    ROOT_ID_LIST(ROOT_CASE)
#undef ROOT_CASE
    case Root::kNumberOfRoots:
      break;
  }
  UNREACHABLE();
}
References v8::internal::kNumberOfRoots, ROOT_CASE, ROOT_ID_LIST, and v8::internal::UNREACHABLE().
Referenced by v8::internal::HeapSnapshot::AddGcSubrootEntry().
Synchronize()
virtual void v8::internal::RootVisitor::Synchronize (VisitorSynchronization::SyncTag tag) [inline], [virtual]
Reimplemented in v8::internal::RootsSerializer, v8::internal::Deserializer< IsolateT >, v8::internal::Deserializer< LocalIsolate >, v8::internal::Deserializer< Isolate >, v8::internal::ClearStaleLeftTrimmedPointerVisitor, and v8::internal::ClientRootVisitor< Visitor >.
Definition at line 112 of file visitors.h.
{}
Referenced by v8::internal::Bootstrapper::Iterate(), v8::internal::ReadOnlyRoots::Iterate(), v8::internal::Heap::IterateRoots(), v8::internal::Heap::IterateSmiRoots(), and v8::internal::Heap::IterateWeakRoots().
VisitRootPointer()
virtual void v8::internal::RootVisitor::VisitRootPointer (Root root, const char * description, FullObjectSlot p) [inline], [virtual]
Reimplemented in v8::internal::RootsReferencesExtractor, v8::internal::PointersUpdatingVisitor, v8::internal::ClearStaleLeftTrimmedPointerVisitor, v8::internal::RootScavengeVisitor, v8::internal::anonymous_namespace{scavenger.cc}::TreatConservativelyVisitor, v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >, v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< PreciseObjectPinningVisitor >, v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConservativeObjectPinningVisitor >, v8::internal::anonymous_namespace{scavenger.cc}::GlobalHandlesWeakRootsUpdatingVisitor, v8::internal::YoungGenerationRootMarkingVisitor, v8::internal::RootMarkingVisitor, and v8::internal::PrecisePagePinningVisitor.
Definition at line 75 of file visitors.h.
                                                  {
    VisitRootPointers(root, description, p, p + 1);
  }
References VisitRootPointers().
Referenced by v8::internal::SharedHeapSerializer::FinalizeSerialization(), v8::internal::TracedHandles::Iterate(), v8::internal::CompilationCacheEvalOrScript::Iterate(), v8::internal::SourceCodeCache::Iterate(), v8::internal::Debug::Iterate(), v8::internal::Isolate::Iterate(), v8::internal::wasm::StackMemory::Iterate(), v8::internal::GlobalHandles::IterateAllRoots(), v8::internal::GlobalHandles::IterateAllYoungRoots(), v8::internal::TracedHandles::IterateAndMarkYoungRootsWithOldHosts(), v8::internal::Heap::IterateBuiltins(), v8::internal::Code::IterateDeoptimizationLiterals(), v8::internal::anonymous_namespace{serializer-deserializer.cc}::IterateObjectCache(), v8::internal::GlobalHandles::IterateStrongRoots(), v8::internal::GlobalHandles::IterateWeakRoots(), v8::internal::Heap::IterateWeakRoots(), v8::internal::TracedHandles::IterateYoung(), v8::internal::TracedHandles::IterateYoungRoots(), v8::internal::EternalHandles::IterateYoungRoots(), v8::internal::TracedHandles::IterateYoungRootsWithOldHostsForTesting(), v8::internal::GlobalHandles::IterateYoungStrongAndDependentRoots(), v8::internal::GlobalHandles::ProcessWeakYoungObjects(), v8::internal::ContextSerializer::Serialize(), v8::internal::CodeSerializer::SerializeSharedFunctionInfo(), v8::internal::StartupSerializer::SerializeWeakReferencesAndDeferred(), VisitRunningCode(), and v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlot().
VisitRootPointers() [1/2]
virtual void v8::internal::RootVisitor::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [pure virtual]
Implemented in v8::internal::SerializedHandleChecker, v8::internal::Serializer, v8::internal::RootsSerializer, v8::internal::Deserializer< IsolateT >, v8::internal::Deserializer< LocalIsolate >, v8::internal::Deserializer< Isolate >, v8::internal::GlobalObjectsEnumerator, v8::internal::RootsReferencesExtractor, v8::internal::PointersUpdatingVisitor, v8::internal::anonymous_namespace{mark-compact.cc}::SharedStructTypeRegistryCleaner, v8::internal::InternalizedStringTableCleaner, v8::internal::ClearStaleLeftTrimmedPointerVisitor, v8::internal::UnreachableObjectsFilter::MarkingVisitor, v8::internal::CheckHandleCountVisitor, v8::internal::ClientRootVisitor< Visitor >, v8::internal::RootScavengeVisitor, v8::internal::anonymous_namespace{scavenger.cc}::TreatConservativelyVisitor, v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >, v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< PreciseObjectPinningVisitor >, v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConservativeObjectPinningVisitor >, v8::internal::anonymous_namespace{scavenger.cc}::GlobalHandlesWeakRootsUpdatingVisitor, v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor, v8::internal::YoungGenerationRootMarkingVisitor, v8::internal::ExternalStringTableCleanerVisitor< mode >, v8::internal::RootMarkingVisitor, and v8::internal::PrecisePagePinningVisitor.
Referenced by v8::internal::CompilationCacheRegExp::Iterate(), v8::internal::TypedFrame::Iterate(), v8::internal::JavaScriptFrame::Iterate(), v8::internal::MaglevFrame::Iterate(), v8::internal::ConstructFrame::Iterate(), v8::internal::LocalHandles::Iterate(), v8::internal::PersistentHandles::Iterate(), v8::internal::ReadOnlyRoots::Iterate(), v8::internal::Heap::ExternalStringTable::IterateAll(), v8::internal::EternalHandles::IterateAllRoots(), v8::internal::OffHeapHashTableBase< Derived >::IterateElements(), v8::internal::CommonFrame::IterateExpressions(), v8::internal::CustomArguments< T >::IterateInstance(), v8::internal::anonymous_namespace{builtins-api.cc}::RelocatableArguments::IterateInstance(), v8::internal::MicrotaskQueue::IterateMicrotasks(), v8::internal::Heap::IterateRoots(), v8::internal::Heap::IterateSmiRoots(), v8::internal::HandleScopeImplementer::IterateThis(), v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame(), v8::internal::Heap::ExternalStringTable::IterateYoung(), and VisitRootPointer().
VisitRootPointers() [2/2]
virtual void v8::internal::RootVisitor::VisitRootPointers (Root root, const char * description, OffHeapObjectSlot start, OffHeapObjectSlot end) [inline], [virtual]
Reimplemented in v8::internal::GlobalObjectsEnumerator, v8::internal::RootsReferencesExtractor, v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor, v8::internal::PointersUpdatingVisitor, v8::internal::anonymous_namespace{mark-compact.cc}::SharedStructTypeRegistryCleaner, v8::internal::InternalizedStringTableCleaner, v8::internal::UnreachableObjectsFilter::MarkingVisitor, and v8::internal::ClientRootVisitor< Visitor >.
Definition at line 93 of file visitors.h.
                                                        {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitRunningCode()
virtual void v8::internal::RootVisitor::VisitRunningCode (FullObjectSlot code_slot, FullObjectSlot istream_or_smi_zero_slot) [inline], [virtual]
Reimplemented in v8::internal::ClientRootVisitor< Visitor >, v8::internal::ClearStaleLeftTrimmedPointerVisitor, v8::internal::RootsReferencesExtractor, and v8::internal::RootMarkingVisitor.
Definition at line 101 of file visitors.h.
                                                                         {
    // For most visitors, currently running code is no different than any other
    // on-stack pointer.
    VisitRootPointer(Root::kStackRoots, nullptr, istream_or_smi_zero_slot);
    VisitRootPointer(Root::kStackRoots, nullptr, code_slot);
  }
References VisitRootPointer().
Referenced by v8::internal::StackFrame::IteratePc(), and v8::internal::ClearStaleLeftTrimmedPointerVisitor::VisitRunningCode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/visitors.h
/mnt/V8SourceCode/src/objects/visitors.cc