v8::internal::InterpretedFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
int GetBytecodeOffset () const override
void PatchBytecodeOffset (int new_offset)
void PatchBytecodeArray (Tagged< BytecodeArray > bytecode_array)
Static Public Member Functions
static InterpretedFrame * cast (StackFrame *frame)
static const InterpretedFrame * cast (const StackFrame *frame)
Protected Member Functions
InterpretedFrame (StackFrameIteratorBase *iterator)
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 1133 of file frames.h.
Constructor & Destructor Documentation
InterpretedFrame()
v8::internal::InterpretedFrame::InterpretedFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 309 of file frames-inl.h.
    : UnoptimizedJSFrame(iterator) {}
Member Function Documentation
cast() [1/2]
static const InterpretedFrame* v8::internal::InterpretedFrame::cast (const StackFrame * frame) [inline], [static]
Definition at line 1152 of file frames.h.
                                                               {
    DCHECK(frame->is_interpreted());
    return static_cast<const InterpretedFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_interpreted().
cast() [2/2]
static InterpretedFrame* v8::internal::InterpretedFrame::cast (StackFrame * frame) [inline], [static]
Definition at line 1148 of file frames.h.
                                                   {
    DCHECK(frame->is_interpreted());
    return static_cast<InterpretedFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_interpreted().
Referenced by v8::internal::JavaScriptFrame::GetActiveCodeAndOffset(), v8::internal::JavaScriptFrame::Print(), v8::internal::Isolate::UnwindAndFindHandler(), and v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor::VisitThread().
GetBytecodeOffset()
int v8::internal::InterpretedFrame::GetBytecodeOffset () const [override], [virtual]
Implements v8::internal::UnoptimizedJSFrame.
Definition at line 3323 of file frames.cc.
                                              {
  const int index = InterpreterFrameConstants::kBytecodeOffsetExpressionIndex;
  DCHECK_EQ(InterpreterFrameConstants::kBytecodeOffsetFromFp,
            InterpreterFrameConstants::kExpressionsOffset -
                index * kSystemPointerSize);
  int raw_offset = Smi::ToInt(GetExpression(index));
  return raw_offset - BytecodeArray::kHeaderSize + kHeapObjectTag;
}
References DCHECK_EQ, v8::internal::index, v8::internal::InterpreterFrameConstants::kBytecodeOffsetExpressionIndex, v8::internal::InterpreterFrameConstants::kBytecodeOffsetFromFp, v8::internal::UnoptimizedFrameConstants::kExpressionsOffset, v8::internal::ExposedTrustedObject::kHeaderSize, v8::internal::kHeapObjectTag, v8::internal::kSystemPointerSize, and v8::internal::Smi::ToInt().
Referenced by v8::internal::JavaScriptFrame::GetActiveCodeAndOffset(), v8::internal::Debug::PerformSideEffectCheckAtBytecode(), v8::internal::JavaScriptFrame::Print(), and v8::internal::RUNTIME_FUNCTION_RETURN_PAIR().
PatchBytecodeArray()
void v8::internal::InterpretedFrame::PatchBytecodeArray (Tagged< BytecodeArray > bytecode_array)
Definition at line 3341 of file frames.cc.
                                          {
  const int index = InterpreterFrameConstants::kBytecodeArrayExpressionIndex;
  DCHECK_EQ(InterpreterFrameConstants::kBytecodeArrayFromFp,
            InterpreterFrameConstants::kExpressionsOffset -
                index * kSystemPointerSize);
  SetExpression(index, bytecode_array);
}
References DCHECK_EQ, v8::internal::index, v8::internal::UnoptimizedFrameConstants::kBytecodeArrayExpressionIndex, v8::internal::UnoptimizedFrameConstants::kBytecodeArrayFromFp, v8::internal::UnoptimizedFrameConstants::kExpressionsOffset, and v8::internal::kSystemPointerSize.
Referenced by v8::internal::RUNTIME_FUNCTION_RETURN_PAIR(), and v8::internal::RedirectActiveFunctions::VisitThread().
PatchBytecodeOffset()
void v8::internal::InterpretedFrame::PatchBytecodeOffset (int new_offset)
Definition at line 3332 of file frames.cc.
                                                         {
  const int index = InterpreterFrameConstants::kBytecodeOffsetExpressionIndex;
  DCHECK_EQ(InterpreterFrameConstants::kBytecodeOffsetFromFp,
            InterpreterFrameConstants::kExpressionsOffset -
                index * kSystemPointerSize);
  int raw_offset = BytecodeArray::kHeaderSize - kHeapObjectTag + new_offset;
  SetExpression(index, Smi::FromInt(raw_offset));
}
References DCHECK_EQ, v8::internal::Smi::FromInt(), v8::internal::index, v8::internal::InterpreterFrameConstants::kBytecodeOffsetExpressionIndex, v8::internal::InterpreterFrameConstants::kBytecodeOffsetFromFp, v8::internal::UnoptimizedFrameConstants::kExpressionsOffset, v8::internal::ExposedTrustedObject::kHeaderSize, v8::internal::kHeapObjectTag, and v8::internal::kSystemPointerSize.
Referenced by v8::internal::Isolate::UnwindAndFindHandler(), and v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor::VisitThread().
type()
Type v8::internal::InterpretedFrame::type () const [inline], [override], [virtual]
Implements v8::internal::JavaScriptFrame.
Definition at line 1135 of file frames.h.
{ return INTERPRETED; }
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 1161 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc