v8::internal::SafepointTableBuilder::Safepoint Class Reference
#include <safepoint-table.h>
Public Member Functions
void DefineTaggedStackSlot (int index)
void DefineTaggedRegister (int reg_code)
Private Member Functions
Safepoint (EntryBuilder *entry, SafepointTableBuilder *table)
Private Attributes
EntryBuilder *const entry_
SafepointTableBuilder *const table_
Friends
class SafepointTableBuilder
Detailed Description
Definition at line 215 of file safepoint-table.h.
Constructor & Destructor Documentation
Safepoint()
v8::internal::SafepointTableBuilder::Safepoint::Safepoint (EntryBuilder * entry, SafepointTableBuilder * table) [inline], [private]
Definition at line 234 of file safepoint-table.h.
        : entry_(entry), table_(table) {}
Member Function Documentation
DefineTaggedRegister()
void v8::internal::SafepointTableBuilder::Safepoint::DefineTaggedRegister (int reg_code) [inline]
Definition at line 226 of file safepoint-table.h.
                                            {
      DCHECK_LT(reg_code,
                kBitsPerByte * sizeof(EntryBuilder::register_indexes));
      entry_->register_indexes |= 1u << reg_code;
    }
References DCHECK_LT, and v8::internal::kBitsPerByte.
Referenced by v8::internal::wasm::LiftoffAssembler::CacheState::DefineSafepointWithCalleeSavedRegisters().
DefineTaggedStackSlot()
void v8::internal::SafepointTableBuilder::Safepoint::DefineTaggedStackSlot (int index) [inline]
Definition at line 217 of file safepoint-table.h.
                                          {
      // Note it is only valid to specify stack slots here that are *not* in
      // the fixed part of the frame (e.g. argc, target, context, stored rbp,
      // return address). Frame iteration handles the fixed part of the frame
      // with custom code, see Turbofan::Iterate.
      entry_->stack_indexes->Add(index, table_->zone_);
      table_->UpdateMinMaxStackIndex(index);
    }
References v8::internal::index.
Referenced by v8::internal::wasm::LiftoffAssembler::CacheState::DefineSafepoint(), v8::internal::wasm::LiftoffAssembler::CacheState::DefineSafepointWithCalleeSavedRegisters(), v8::internal::compiler::CodeGenerator::RecordSafepoint(), and v8::internal::wasm::LiftoffAssembler::RecordSpillsInSafepoint().
Friends And Related Function Documentation
SafepointTableBuilder
friend class SafepointTableBuilder [friend]
Definition at line 233 of file safepoint-table.h.
Member Data Documentation
entry_
EntryBuilder* const v8::internal::SafepointTableBuilder::Safepoint::entry_ [private]
Definition at line 236 of file safepoint-table.h.
table_
SafepointTableBuilder* const v8::internal::SafepointTableBuilder::Safepoint::table_ [private]
Definition at line 237 of file safepoint-table.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/safepoint-table.h