v8::internal::maglev::AnyUseMarkingProcessor Class Reference
#include <maglev-post-hoc-optimizations-processors.h>
Public Member Functions
void PreProcessGraph (Graph *graph)
void PostProcessBasicBlock (BasicBlock *block)
BlockProcessResult PreProcessBasicBlock (BasicBlock *block)
void PostPhiProcessing ()
template<typename NodeT >
ProcessResult Process (NodeT *node, const ProcessingState &state)
void PostProcessGraph (Graph *graph)
Private Member Functions
void EscapeAllocation (Graph *graph, InlinedAllocation *alloc, Graph::SmallAllocationVector &deps)
void VerifyEscapeAnalysis (Graph *graph)
void RunEscapeAnalysis (Graph *graph)
void DropUseOfValueInStoresToCapturedAllocations ()
void DropInputUses (Input &input)
void DropInputUses (ValueNode *node)
Private Attributes
std::vector< Node * > stores_to_allocations_
Detailed Description
Definition at line 203 of file maglev-post-hoc-optimizations-processors.h.
Member Function Documentation
DropInputUses() [1/2]
void v8::internal::maglev::AnyUseMarkingProcessor::DropInputUses (Input & input) [inline], [private]
Definition at line 310 of file maglev-post-hoc-optimizations-processors.h.
                                   {
    ValueNode* input_node = input.node();
    if (input_node->properties().is_required_when_unused() &&
        !input_node->Is<ArgumentsElements>())
      return;
    input_node->remove_use();
    if (!input_node->is_used() && !input_node->unused_inputs_were_visited()) {
      DropInputUses(input_node);
    }
  }
References v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::OpProperties::is_required_when_unused(), v8::internal::maglev::ValueNode::is_used(), v8::internal::maglev::Input::node(), v8::internal::maglev::NodeBase::properties(), v8::internal::maglev::ValueNode::remove_use(), and v8::internal::maglev::ValueNode::unused_inputs_were_visited().
Referenced by DropInputUses(), DropUseOfValueInStoresToCapturedAllocations(), and Process().
DropInputUses() [2/2]
void v8::internal::maglev::AnyUseMarkingProcessor::DropInputUses (ValueNode * node) [inline], [private]
Definition at line 321 of file maglev-post-hoc-optimizations-processors.h.
                                      {
    for (Input& input : *node) {
      DropInputUses(input);
    }
    DCHECK(!node->properties().can_eager_deopt());
    DCHECK(!node->properties().can_lazy_deopt());
    node->mark_unused_inputs_visited();
  }
References v8::internal::maglev::OpProperties::can_eager_deopt(), v8::internal::maglev::OpProperties::can_lazy_deopt(), v8::internal::DCHECK(), DropInputUses(), v8::internal::maglev::ValueNode::mark_unused_inputs_visited(), and v8::internal::maglev::NodeBase::properties().
DropUseOfValueInStoresToCapturedAllocations()
void v8::internal::maglev::AnyUseMarkingProcessor::DropUseOfValueInStoresToCapturedAllocations () [inline], [private]
Definition at line 295 of file maglev-post-hoc-optimizations-processors.h.
                                                     {
    for (Node* node : stores_to_allocations_) {
      InlinedAllocation* alloc =
          node->input(0).node()->Cast<InlinedAllocation>();
      // Since we don't analyze if allocations will escape until a fixpoint,
      // this could drop an use of an allocation and turn it non-escaping.
      if (alloc->HasBeenElided()) {
        // Skip first input.
        for (int i = 1; i < node->input_count(); i++) {
          DropInputUses(node->input(i));
        }
      }
    }
  }
References DropInputUses(), v8::internal::maglev::InlinedAllocation::HasBeenElided(), and stores_to_allocations_.
Referenced by PostProcessGraph().
EscapeAllocation()
void v8::internal::maglev::AnyUseMarkingProcessor::EscapeAllocation (Graph * graph, InlinedAllocation * alloc, Graph::SmallAllocationVector & deps) [inline], [private]
Definition at line 253 of file maglev-post-hoc-optimizations-processors.h.
                                                          {
    if (alloc->HasBeenAnalysed() && alloc->HasEscaped()) return;
    alloc->SetEscaped();
    for (auto dep : deps) {
      EscapeAllocation(graph, dep,
                       graph->allocations_escape_map().find(dep)->second);
    }
  }
References graph(), v8::internal::maglev::InlinedAllocation::HasBeenAnalysed(), v8::internal::maglev::InlinedAllocation::HasEscaped(), and v8::internal::maglev::InlinedAllocation::SetEscaped().
Referenced by RunEscapeAnalysis().
PostPhiProcessing()
void v8::internal::maglev::AnyUseMarkingProcessor::PostPhiProcessing () [inline]
Definition at line 210 of file maglev-post-hoc-optimizations-processors.h.
{}
PostProcessBasicBlock()
void v8::internal::maglev::AnyUseMarkingProcessor::PostProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 206 of file maglev-post-hoc-optimizations-processors.h.
{}
PostProcessGraph()
void v8::internal::maglev::AnyUseMarkingProcessor::PostProcessGraph (Graph * graph) [inline]
Definition at line 245 of file maglev-post-hoc-optimizations-processors.h.
                                      {
    RunEscapeAnalysis(graph);
    DropUseOfValueInStoresToCapturedAllocations();
  }
References DropUseOfValueInStoresToCapturedAllocations(), graph(), and RunEscapeAnalysis().
PreProcessBasicBlock()
BlockProcessResult v8::internal::maglev::AnyUseMarkingProcessor::PreProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 207 of file maglev-post-hoc-optimizations-processors.h.
                                                             {
    return BlockProcessResult::kContinue;
  }
References v8::internal::maglev::kContinue.
PreProcessGraph()
void v8::internal::maglev::AnyUseMarkingProcessor::PreProcessGraph (Graph * graph) [inline]
Definition at line 205 of file maglev-post-hoc-optimizations-processors.h.
{}
Process()
template<typename NodeT >
ProcessResult v8::internal::maglev::AnyUseMarkingProcessor::Process (NodeT * node, const ProcessingState & state) [inline]
Definition at line 213 of file maglev-post-hoc-optimizations-processors.h.
                                                                   {
    if constexpr (IsValueNode(Node::opcode_of<NodeT>) &&
                  (!NodeT::kProperties.is_required_when_unused() ||
                   std::is_same_v<ArgumentsElements, NodeT>)) {
      if (!node->is_used()) {
        if (!node->unused_inputs_were_visited()) {
          DropInputUses(node);
        }
        return ProcessResult::kRemove;
      }
    }
    if constexpr (CanBeStoreToNonEscapedObject<NodeT>()) {
      if (node->input(0).node()->template Is<InlinedAllocation>()) {
        stores_to_allocations_.push_back(node);
      }
    }
    return ProcessResult::kContinue;
  }
References DropInputUses(), v8::internal::maglev::IsValueNode(), v8::internal::maglev::kContinue, v8::internal::maglev::kRemove, and stores_to_allocations_.
RunEscapeAnalysis()
void v8::internal::maglev::AnyUseMarkingProcessor::RunEscapeAnalysis (Graph * graph) [inline], [private]
Definition at line 277 of file maglev-post-hoc-optimizations-processors.h.
                                       {
    for (auto& it : graph->allocations_escape_map()) {
      auto* alloc = it.first;
      if (alloc->HasBeenAnalysed()) continue;
      // Check if all its uses are non escaping.
      if (alloc->IsEscaping()) {
        // Escape this allocation and all its dependencies.
        EscapeAllocation(graph, alloc, it.second);
      } else {
        // Try to capture the allocation. This can still change if a escaped
        // allocation has this value as one of its dependencies.
        alloc->SetElided();
      }
    }
    // Check that we've reached a fixpoint.
    VerifyEscapeAnalysis(graph);
  }
References EscapeAllocation(), graph(), and VerifyEscapeAnalysis().
Referenced by PostProcessGraph().
VerifyEscapeAnalysis()
void v8::internal::maglev::AnyUseMarkingProcessor::VerifyEscapeAnalysis (Graph * graph) [inline], [private]
Definition at line 263 of file maglev-post-hoc-optimizations-processors.h.
                                          {
#ifdef DEBUG
    for (const auto& it : graph->allocations_escape_map()) {
      auto* alloc = it.first;
      DCHECK(alloc->HasBeenAnalysed());
      if (alloc->HasEscaped()) {
        for (auto* dep : it.second) {
          DCHECK(dep->HasEscaped());
        }
      }
    }
#endif // DEBUG
  }
References v8::internal::DCHECK(), and graph().
Referenced by RunEscapeAnalysis().
Member Data Documentation
stores_to_allocations_
std::vector<Node*> v8::internal::maglev::AnyUseMarkingProcessor::stores_to_allocations_ [private]
Definition at line 251 of file maglev-post-hoc-optimizations-processors.h.
Referenced by DropUseOfValueInStoresToCapturedAllocations(), and Process().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-post-hoc-optimizations-processors.h