v8::internal::CppGraphBuilderImpl Class Reference
Classes
struct MergedNodeItem
class VisitationDoneItem
class VisitationItem
class WorkstackItemBase
Public Member Functions
CppGraphBuilderImpl (CppHeap &cpp_heap, v8::EmbedderGraph &graph, UnorderedCppHeapExternalObjectSet &&cpp_heap_external_objects)
void Run ()
void VisitForVisibility (State *parent, const HeapObjectHeader &)
void VisitForVisibility (State &parent, const TracedReferenceBase &)
void VisitEphemeronForVisibility (const HeapObjectHeader &key, const HeapObjectHeader &value)
void VisitEphemeronWithNonGarbageCollectedValueForVisibility (const HeapObjectHeader &key, const void *value, cppgc::TraceDescriptor value_desc)
void VisitWeakContainerForVisibility (const HeapObjectHeader &)
void VisitRootForGraphBuilding (RootState &, const HeapObjectHeader &, const cppgc::SourceLocation &)
void ProcessPendingObjects ()
void RecordEphemeronKey (const HeapObjectHeader &, const HeapObjectHeader &)
void AddConservativeEphemeronKeyEdgesIfNeeded (const HeapObjectHeader &)
void AddEdgeForCppHeapExternalObject (Tagged< CppHeapExternalObject >)
EmbedderRootNode * AddRootNode (const char *name)
EmbedderNode * AddNode (const HeapObjectHeader &header)
void AddEdge (State &parent, const HeapObjectHeader &header, std::string_view edge_name)
void AddEdge (State &parent, const TracedReferenceBase &ref, std::string_view edge_name)
void AddRootEdge (RootState &root, State &child, std::string edge_name)
Private Attributes
CppHeap & cpp_heap_
v8::EmbedderGraph & graph_
StateStorage states_
std::vector< std::unique_ptr< WorkstackItemBase > > workstack_
UnorderedCppHeapExternalObjectSet cpp_heap_external_objects_
Detailed Description
Definition at line 442 of file cpp-snapshot.cc.
Constructor & Destructor Documentation
CppGraphBuilderImpl()
v8::internal::CppGraphBuilderImpl::CppGraphBuilderImpl (CppHeap & cpp_heap, v8::EmbedderGraph & graph, UnorderedCppHeapExternalObjectSet && cpp_heap_external_objects) [inline]
Definition at line 444 of file cpp-snapshot.cc.
      : cpp_heap_(cpp_heap),
        graph_(graph),
        cpp_heap_external_objects_(std::move(cpp_heap_external_objects)) {}
Member Function Documentation
AddConservativeEphemeronKeyEdgesIfNeeded()
void v8::internal::CppGraphBuilderImpl::AddConservativeEphemeronKeyEdgesIfNeeded (const HeapObjectHeader & header)
Definition at line 923 of file cpp-snapshot.cc.
                                    {
  auto& state = states_.GetExistingState(header);
  if (state.WasVisitedFromStack()) {
    return;
  }
  state.MarkVisitedFromStack();
  state.ForAllEphemeronKeys([this, &state](const HeapObjectHeader& key) {
    DCHECK(state.IsWeakContainer());
    AddEdge(state, key, "");
  });
}
References v8::internal::DCHECK(), and v8::internal::key.
AddEdge() [1/2]
void v8::internal::CppGraphBuilderImpl::AddEdge (State & parent, const HeapObjectHeader & header, std::string_view edge_name) [inline]
Definition at line 487 of file cpp-snapshot.cc.
                                         {
    DCHECK(parent.IsVisibleNotDependent());
    auto& current = states_.GetExistingState(header);
    if (!current.IsVisibleNotDependent()) return;
    // Both states are visible. Create nodes in case this is the first edge
    // created for any of them.
    if (!parent.get_node()) {
      parent.set_node(AddNode(*parent.header()));
    }
    if (!current.get_node()) {
      current.set_node(AddNode(header));
    }
    if (!edge_name.empty()) {
      graph_.AddEdge(parent.get_node(), current.get_node(),
                     parent.get_node()->InternalizeEdgeName(edge_name));
    } else {
      graph_.AddEdge(parent.get_node(), current.get_node());
    }
  }
References v8::internal::DCHECK(), v8::internal::StateBase::get_node(), v8::internal::State::header(), v8::internal::EmbedderNode::InternalizeEdgeName(), v8::internal::StateBase::IsVisibleNotDependent(), and v8::internal::StateBase::set_node().
AddEdge() [2/2]
void v8::internal::CppGraphBuilderImpl::AddEdge (State & parent, const TracedReferenceBase & ref, std::string_view edge_name) [inline]
Definition at line 510 of file cpp-snapshot.cc.
                                         {
    DCHECK(parent.IsVisibleNotDependent());
    v8::Local<v8::Data> v8_data =
        ref.Get(reinterpret_cast<v8::Isolate*>(cpp_heap_.isolate()));
    if (v8_data.IsEmpty()) return;
    if (!parent.get_node()) {
      parent.set_node(AddNode(*parent.header()));
    }
    auto* v8_node = graph_.V8Node(v8_data);
    if (!edge_name.empty()) {
      graph_.AddEdge(parent.get_node(), v8_node,
                     parent.get_node()->InternalizeEdgeName(edge_name));
    } else {
      graph_.AddEdge(parent.get_node(), v8_node);
    }
    // Don't merge nodes if edges have a name.
    if (!edge_name.empty()) return;
    // Try to extract the back reference. If the back reference matches
    // `parent`, then the nodes are merged.
    void* back_reference_object = ExtractEmbedderDataBackref(
        reinterpret_cast<v8::internal::Isolate*>(cpp_heap_.isolate()),
        cpp_heap_, v8_data);
    if (!back_reference_object) return;
    // Only JS objects have back references.
    DCHECK(v8_data->IsValue() && v8_data.As<v8::Value>()->IsObject());
    auto& back_header = HeapObjectHeader::FromObject(back_reference_object);
    auto& back_state = states_.GetExistingState(back_header);
    // If the back reference doesn't point to the same header, just return. In
    // such a case we have stand-alone references to a wrapper.
    if (parent.header() != back_state.header()) return;
    // Back reference points to parents header. In this case, the nodes should
    // be merged and query the detachedness state of the embedder.
    if (!back_state.get_node()) {
      back_state.set_node(AddNode(back_header));
    }
    back_state.get_node()->SetWrapperNode(v8_node);
    auto* profiler = reinterpret_cast<Isolate*>(cpp_heap_.isolate())
                         ->heap()
                         ->heap_profiler();
    if (profiler->HasGetDetachednessCallback()) {
      back_state.get_node()->SetDetachedness(
          profiler->GetDetachedness(v8_data.As<v8::Value>(), 0));
    }
  }
References v8::Local< T >::As(), v8::internal::DCHECK(), v8::internal::ExtractEmbedderDataBackref(), cppgc::internal::HeapObjectHeader::FromObject(), v8::TracedReferenceBase::Get(), v8::internal::StateBase::get_node(), v8::internal::State::header(), heap(), v8::internal::EmbedderNode::InternalizeEdgeName(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::Value::IsObject(), v8::Data::IsValue(), v8::internal::StateBase::IsVisibleNotDependent(), and v8::internal::StateBase::set_node().
AddEdgeForCppHeapExternalObject()
void v8::internal::CppGraphBuilderImpl::AddEdgeForCppHeapExternalObject (Tagged< CppHeapExternalObject > external)
Definition at line 954 of file cpp-snapshot.cc.
                                            {
  void* cpp_object = CppHeapObjectWrapper(*external).GetCppHeapWrappable(
      cpp_heap_.isolate(), kAnyCppHeapPointer);
  State& cpp_object_state =
      states_.GetExistingState(HeapObjectHeader::FromObject(cpp_object));
  if (!cpp_object_state.IsVisibleNotDependent()) return;
  if (!cpp_object_state.get_node()) {
    cpp_object_state.set_node(AddNode(*cpp_object_state.header()));
  }
  auto* v8_node = graph_.V8Node(
      Utils::CppHeapExternalToLocal(handle(external, cpp_heap_.isolate())));
  graph_.AddEdge(v8_node, cpp_object_state.get_node());
}
References cppgc::internal::HeapObjectHeader::FromObject(), v8::internal::StateBase::get_node(), v8::internal::CppHeapObjectWrapper::GetCppHeapWrappable(), v8::internal::handle(), v8::internal::State::header(), v8::internal::StateBase::IsVisibleNotDependent(), v8::kAnyCppHeapPointer(), and v8::internal::StateBase::set_node().
AddNode()
EmbedderNode* v8::internal::CppGraphBuilderImpl::AddNode (const HeapObjectHeader & header) [inline]
Definition at line 475 of file cpp-snapshot.cc.
                                                        {
    size_t size = header.AllocatedSize();
    EmbedderNode* node = static_cast<EmbedderNode*>(
        graph_.AddNode(std::unique_ptr<v8::EmbedderGraph::Node>{
            new EmbedderNode(&header, header.GetName(), size)}));
    size_t node_size = node->SizeInBytes();
    if (size > node_size) {
      graph_.AddNativeSize(size - node_size);
    }
    return node;
  }
References cppgc::internal::HeapObjectHeader::AllocatedSize(), cppgc::internal::HeapObjectHeader::GetName(), size(), and v8::internal::EmbedderNode::SizeInBytes().
AddRootEdge()
void v8::internal::CppGraphBuilderImpl::AddRootEdge (RootState & root, State & child, std::string edge_name) [inline]
Definition at line 563 of file cpp-snapshot.cc.
                                                                       {
    DCHECK(root.IsVisibleNotDependent());
    if (!child.IsVisibleNotDependent()) return;
    // Root states always have a node set.
    DCHECK_NOT_NULL(root.get_node());
    if (!child.get_node()) {
      child.set_node(AddNode(*child.header()));
    }
    if (!edge_name.empty()) {
      graph_.AddEdge(root.get_node(), child.get_node(),
                     root.get_node()->InternalizeEdgeName(edge_name));
      return;
    }
    graph_.AddEdge(root.get_node(), child.get_node());
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::StateBase::get_node(), v8::internal::State::header(), v8::internal::EmbedderNode::InternalizeEdgeName(), v8::internal::StateBase::IsVisibleNotDependent(), and v8::internal::StateBase::set_node().
AddRootNode()
EmbedderRootNode* v8::internal::CppGraphBuilderImpl::AddRootNode (const char * name) [inline]
Definition at line 470 of file cpp-snapshot.cc.
                                                  {
    return static_cast<EmbedderRootNode*>(graph_.AddNode(
        std::unique_ptr<v8::EmbedderGraph::Node>{new EmbedderRootNode(name)}));
  }
References v8::internal::name.
ProcessPendingObjects()
void v8::internal::CppGraphBuilderImpl::ProcessPendingObjects ()
Definition at line 811 of file cpp-snapshot.cc.
                                                {
  while (!workstack_.empty()) {
    std::unique_ptr<WorkstackItemBase> item = std::move(workstack_.back());
    workstack_.pop_back();
    item->Process(*this);
  }
}
RecordEphemeronKey()
void v8::internal::CppGraphBuilderImpl::RecordEphemeronKey (const HeapObjectHeader & container, const HeapObjectHeader & key)
Definition at line 916 of file cpp-snapshot.cc.
                                                                          {
  auto& container_state = states_.GetOrCreateState(container);
  DCHECK(container_state.IsWeakContainer());
  container_state.RecordEphemeronKey(key);
}
References v8::internal::DCHECK(), and v8::internal::key.
Run()
void v8::internal::CppGraphBuilderImpl::Run ()
Definition at line 1021 of file cpp-snapshot.cc.
                              {
  // Sweeping from a previous GC might still be running, in which case not all
  // pages have been returned to spaces yet.
  cpp_heap_.sweeper().FinishIfRunning();
  cppgc::subtle::DisallowGarbageCollectionScope no_gc(
      cpp_heap_.GetHeapHandle());
  // First pass: Figure out which objects should be included in the graph -- see
  // class-level comment on CppGraphBuilder.
  LiveObjectsForVisibilityIterator visitor(*this);
  visitor.Traverse(cpp_heap_.raw_heap());
  // Second pass: Add graph nodes for objects that must be shown.
  states_.ForAllStates([this](StateBase* state_base) {
    // No roots have been created so far, so all StateBase objects are State.
    State& state = *static_cast<State*>(state_base);
    if (!state.IsVisibleNotDependent()) {
      graph_.AddNativeSize(state.header()->AllocatedSize());
      return;
    }
    // Emit no edges for the contents of the weak containers. For both, fully
    // weak and ephemeron containers, the contents should be retained from
    // somewhere else.
    if (state.IsWeakContainer()) return;
    ParentScope parent_scope(state);
    GraphBuildingVisitor object_visitor(*this, parent_scope);
    if (!state.header()->IsInConstruction()) {
      // TODO(mlippautz): Handle in-construction objects.
      state.header()->TraceImpl(&object_visitor);
    }
    state.ForAllEphemeronEdges([this, &state](const HeapObjectHeader& value) {
      AddEdge(state, value, kEphemeronEdgeName);
    });
    object_visitor.set_edge_name(kEphemeronEdgeName);
    state.ForAllEagerEphemeronEdges(
        [&object_visitor](const void* value, cppgc::TraceCallback callback) {
          callback(&object_visitor, value);
        });
  });
  // Add roots.
  {
    ParentScope parent_scope(
        states_.CreateRootState(AddRootNode("C++ Persistent roots")));
    GraphBuildingRootVisitor root_object_visitor(*this, parent_scope);
    cpp_heap_.GetStrongPersistentRegion().Iterate(root_object_visitor);
  }
  {
    ParentScope parent_scope(states_.CreateRootState(
        AddRootNode("C++ CrossThreadPersistent roots")));
    GraphBuildingRootVisitor root_object_visitor(*this, parent_scope);
    cppgc::internal::PersistentRegionLock guard;
    cpp_heap_.GetStrongCrossThreadPersistentRegion().Iterate(
        root_object_visitor);
  }
  // Only add stack roots in case the callback is not run from generating a
  // snapshot without stack. This avoids adding false-positive edges when
  // conservatively scanning the stack.
  if (cpp_heap_.isolate()->heap()->IsGCWithMainThreadStack()) {
    ParentScope parent_scope(
        states_.CreateRootState(AddRootNode("C++ native stack roots")));
    GraphBuildingRootVisitor root_object_visitor(*this, parent_scope);
    GraphBuildingStackVisitor stack_visitor(*this, cpp_heap_,
                                            root_object_visitor);
    cpp_heap_.stack()->IteratePointersUntilMarker(&stack_visitor);
  }
  // Connect each `CppHeapExternalObject` to its corresponding cpp object.
  for (Tagged<CppHeapExternalObject> object : cpp_heap_external_objects_) {
    AddEdgeForCppHeapExternalObject(object);
  }
}
References cppgc::internal::HeapObjectHeader::AllocatedSize(), v8::internal::State::ForAllEagerEphemeronEdges(), v8::internal::State::ForAllEphemeronEdges(), v8::internal::State::header(), cppgc::internal::HeapObjectHeader::IsInConstruction(), v8::internal::StateBase::IsVisibleNotDependent(), v8::internal::State::IsWeakContainer(), v8::internal::anonymous_namespace{cpp-snapshot.cc}::kEphemeronEdgeName, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::GraphBuildingVisitor::set_edge_name(), cppgc::internal::HeapObjectHeader::TraceImpl(), cppgc::internal::HeapVisitor< Derived >::Traverse(), and v8::internal::value.
Referenced by v8::internal::CppGraphBuilder::Run().
VisitEphemeronForVisibility()
void v8::internal::CppGraphBuilderImpl::VisitEphemeronForVisibility (const HeapObjectHeader & key, const HeapObjectHeader & value)
Definition at line 902 of file cpp-snapshot.cc.
                                                                {
  auto& key_state = states_.GetOrCreateState(key);
  VisitForVisibility(&key_state, value);
  key_state.AddEphemeronEdge(value);
}
References v8::internal::key, and v8::internal::value.
VisitEphemeronWithNonGarbageCollectedValueForVisibility()
void v8::internal::CppGraphBuilderImpl::VisitEphemeronWithNonGarbageCollectedValueForVisibility (const HeapObjectHeader & key, const void * value, cppgc::TraceDescriptor value_desc)
Definition at line 889 of file cpp-snapshot.cc.
                                         {
  auto& key_state = states_.GetOrCreateState(key);
  // Eagerly trace the value here, effectively marking key as visible and
  // queuing processing for all reachable values.
  ParentScope parent_scope(key_state);
  VisiblityVisitor visitor(*this, parent_scope);
  value_desc.callback(&visitor, value);
  key_state.AddEagerEphemeronEdge(value, value_desc.callback);
}
References cppgc::TraceDescriptor::callback, v8::internal::key, and v8::internal::value.
VisitForVisibility() [1/2]
void v8::internal::CppGraphBuilderImpl::VisitForVisibility (State & parent, const TracedReferenceBase & ref)
Definition at line 936 of file cpp-snapshot.cc.
                                                                             {
  v8::Local<v8::Data> v8_value =
      ref.Get(reinterpret_cast<v8::Isolate*>(cpp_heap_.isolate()));
  if (!v8_value.IsEmpty()) {
    parent.MarkVisible();
  }
}
References v8::TracedReferenceBase::Get(), v8::api_internal::IndirectHandleBase::IsEmpty(), and v8::internal::State::MarkVisible().
VisitForVisibility() [2/2]
void v8::internal::CppGraphBuilderImpl::VisitForVisibility (State * parent, const HeapObjectHeader & header)
Definition at line 857 of file cpp-snapshot.cc.
                                                                             {
  auto& current = states_.GetOrCreateState(header);
  if (current.IsVisited()) {
    // Avoid traversing into already visited subgraphs and just update the state
    // based on a previous result.
    if (parent) {
      parent->MarkDependentVisibility(&current);
    }
    return;
  }
  current.MarkVisited();
  if (header.GetName().name_was_hidden) {
    current.MarkPending();
    workstack_.push_back(std::unique_ptr<WorkstackItemBase>{
        new VisitationItem(parent, current)});
  } else {
    // No need to mark/unmark pending as the node is immediately processed.
    current.MarkVisible();
    // In case the names are visible, the graph is not traversed in this phase.
    // Explicitly trace one level to handle weak containers.
    WeakVisitor weak_visitor(*this);
    header.TraceImpl(&weak_visitor);
    if (parent) {
      // Eagerly update a parent object as its visibility state is now fixed.
      parent->MarkVisible();
    }
  }
}
References cppgc::internal::HeapObjectHeader::GetName(), v8::internal::State::MarkDependentVisibility(), v8::internal::State::MarkVisible(), cppgc::internal::HeapObjectName::name_was_hidden, and cppgc::internal::HeapObjectHeader::TraceImpl().
VisitRootForGraphBuilding()
void v8::internal::CppGraphBuilderImpl::VisitRootForGraphBuilding (RootState & root, const HeapObjectHeader & header, const cppgc::SourceLocation & loc)
Definition at line 945 of file cpp-snapshot.cc.
                                    {
  State& current = states_.GetExistingState(header);
  if (!current.IsVisibleNotDependent()) return;
  AddRootEdge(root, current, loc.ToString());
}
References v8::internal::StateBase::IsVisibleNotDependent(), v8::internal::loc, and v8::SourceLocation::ToString().
VisitWeakContainerForVisibility()
void v8::internal::CppGraphBuilderImpl::VisitWeakContainerForVisibility (const HeapObjectHeader & container_header)
Definition at line 909 of file cpp-snapshot.cc.
                                              {
  // Mark the container here as weak container to avoid creating any
  // outgoing edges in the second phase.
  states_.GetOrCreateState(container_header).MarkAsWeakContainer();
}
Member Data Documentation
cpp_heap_
CppHeap& v8::internal::CppGraphBuilderImpl::cpp_heap_ [private]
Definition at line 591 of file cpp-snapshot.cc.
cpp_heap_external_objects_
UnorderedCppHeapExternalObjectSet v8::internal::CppGraphBuilderImpl::cpp_heap_external_objects_ [private]
Definition at line 595 of file cpp-snapshot.cc.
graph_
v8::EmbedderGraph& v8::internal::CppGraphBuilderImpl::graph_ [private]
Definition at line 592 of file cpp-snapshot.cc.
states_
StateStorage v8::internal::CppGraphBuilderImpl::states_ [private]
Definition at line 593 of file cpp-snapshot.cc.
workstack_
std::vector<std::unique_ptr<WorkstackItemBase> > v8::internal::CppGraphBuilderImpl::workstack_ [private]
Definition at line 594 of file cpp-snapshot.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc-js/cpp-snapshot.cc