v8::internal::Deoptimizer Class Reference
#include <deoptimizer.h>
Classes
struct DeoptInfo
struct ValueToMaterialize
Public Member Functions
DeoptInfo GetDeoptInfo () const
DirectHandle< JSFunction > function () const
DirectHandle< Code > compiled_code () const
DeoptimizeKind deopt_kind () const
int output_count () const
BytecodeOffset bytecode_offset_in_outermost_frame () const
~Deoptimizer ()
void MaterializeHeapObjects ()
void ProcessDeoptReason (DeoptimizeReason reason)
Isolate * isolate () const
Static Public Member Functions
static bool DeoptExitIsInsideOsrLoop (Isolate *isolate, Tagged< JSFunction > function, BytecodeOffset deopt_exit_offset, BytecodeOffset osr_offset, CodeKind code_kind)
static DeoptInfo GetDeoptInfo (Tagged< Code > code, Address from)
static const char * MessageFor (DeoptimizeKind kind)
static Deoptimizer * New (Address raw_function, DeoptimizeKind kind, Address from, int fp_to_sp_delta, Isolate *isolate)
static Deoptimizer * Grab (Isolate *isolate)
static size_t DeleteForWasm (Isolate *isolate)
static DeoptimizedFrameInfo * DebuggerInspectableFrame (JavaScriptFrame *frame, int jsframe_index, Isolate *isolate)
static void DeoptimizeFunction (Tagged< JSFunction > function, LazyDeoptimizeReason reason, Tagged< Code > code={})
static V8_EXPORT_PRIVATE void DeoptimizeAll (Isolate *isolate)
static void DeoptimizeMarkedCode (Isolate *isolate)
static void DeoptimizeAllOptimizedCodeWithFunction (Isolate *isolate, DirectHandle< SharedFunctionInfo > function)
static Address EnsureValidReturnAddress (Isolate *isolate, Address address)
static void ComputeOutputFrames (Deoptimizer *deoptimizer)
static V8_EXPORT_PRIVATE Builtin GetDeoptimizationEntry (DeoptimizeKind kind)
static int input_offset ()
static int output_count_offset ()
static int output_offset ()
static int caller_frame_top_offset ()
static void TraceMarkForDeoptimization (Isolate *isolate, Tagged< Code > code, LazyDeoptimizeReason reason)
static void TraceEvictFromOptimizedCodeCache (Isolate *isolate, Tagged< SharedFunctionInfo > sfi, const char *reason)
static void PatchToJump (Address pc, Address new_pc)
Static Public Attributes
static constexpr int kMaxNumberOfEntries = 16384
static constexpr unsigned kFixedExitSizeMarker = kMaxUInt32
static V8_EXPORT_PRIVATE const int kEagerDeoptExitSize = 2 * kInstrSize
static V8_EXPORT_PRIVATE const int kLazyDeoptExitSize = 2 * kInstrSize
static V8_EXPORT_PRIVATE const int kAdaptShadowStackOffsetToSubtract = 0
Private Member Functions
void QueueValueForMaterialization (Address output_address, Tagged< Object > obj, const TranslatedFrame::iterator &iterator)
void QueueFeedbackVectorForMaterialization (Address output_address, const TranslatedFrame::iterator &iterator)
Deoptimizer (Isolate *isolate, Tagged< JSFunction > function, DeoptimizeKind kind, Address from, int fp_to_sp_delta)
void DeleteFrameDescriptions ()
void DoComputeOutputFrames ()
void DoComputeUnoptimizedFrame (TranslatedFrame *translated_frame, int frame_index, bool goto_catch_handler)
void DoComputeInlinedExtraArguments (TranslatedFrame *translated_frame, int frame_index)
void DoComputeConstructCreateStubFrame (TranslatedFrame *translated_frame, int frame_index)
void DoComputeConstructInvokeStubFrame (TranslatedFrame *translated_frame, int frame_index)
void DoComputeBuiltinContinuation (TranslatedFrame *translated_frame, int frame_index, BuiltinContinuationMode mode)
unsigned ComputeInputFrameAboveFpFixedSize () const
unsigned ComputeInputFrameSize () const
bool tracing_enabled () const
bool verbose_tracing_enabled () const
CodeTracer::Scope * trace_scope () const
CodeTracer::Scope * verbose_trace_scope () const
void TraceDeoptBegin (int optimization_id, BytecodeOffset bytecode_offset)
void TraceDeoptEnd (double deopt_duration)
bool is_restart_frame () const
Static Private Member Functions
static Builtin TrampolineForBuiltinContinuation (BuiltinContinuationMode mode, bool must_handle_result)
static unsigned ComputeIncomingArgumentSize (Tagged< Code > code)
static void TraceDeoptAll (Isolate *isolate)
Private Attributes
Isolate * isolate_
Tagged< JSFunction > function_
Tagged< Code > compiled_code_
unsigned deopt_exit_index_
BytecodeOffset bytecode_offset_in_outermost_frame_ = BytecodeOffset::None()
DeoptimizeKind deopt_kind_
Address from_
int fp_to_sp_delta_
bool deoptimizing_throw_
int catch_handler_data_
int catch_handler_pc_offset_
int restart_frame_index_
FrameDescription * input_
int output_count_
FrameDescription ** output_
intptr_t caller_frame_top_
intptr_t caller_fp_
intptr_t caller_pc_
intptr_t caller_constant_pool_
int actual_argument_count_
intptr_t stack_fp_
TranslatedState translated_state_
std::vector< ValueToMaterialize > values_to_materialize_
std::vector< ValueToMaterialize > feedback_vector_to_materialize_
CodeTracer::Scope *const trace_scope_
Friends
class DeoptimizedFrameInfo
class FrameDescription
class FrameWriter
Detailed Description
Definition at line 36 of file deoptimizer.h.
Constructor & Destructor Documentation
 Deoptimizer()
v8::internal::Deoptimizer::~Deoptimizer ()
Definition at line 755 of file deoptimizer.cc.
                          {
  DCHECK(input_ == nullptr && output_ == nullptr);
#ifdef V8_ENABLE_CET_SHADOW_STACK
  DCHECK_NULL(shadow_stack_);
#endif
  DCHECK_NULL(disallow_garbage_collection_);
  delete trace_scope_;
}
References v8::internal::DCHECK(), DCHECK_NULL, input_, output_, and trace_scope_.
Deoptimizer()
v8::internal::Deoptimizer::Deoptimizer (Isolate * isolate, Tagged< JSFunction > function, DeoptimizeKind kind, Address from, int fp_to_sp_delta) [private]
Definition at line 602 of file deoptimizer.cc.
    : isolate_(isolate),
      function_(function),
      deopt_exit_index_(kFixedExitSizeMarker),
      deopt_kind_(kind),
      from_(from),
      fp_to_sp_delta_(fp_to_sp_delta),
      deoptimizing_throw_(false),
      catch_handler_data_(-1),
      catch_handler_pc_offset_(-1),
      restart_frame_index_(-1),
      input_(nullptr),
      output_count_(0),
      output_(nullptr),
      caller_frame_top_(0),
      caller_fp_(0),
      caller_pc_(0),
      caller_constant_pool_(0),
      actual_argument_count_(0),
      stack_fp_(0),
      trace_scope_(v8_flags.trace_deopt || v8_flags.log_deopt
                       ? new CodeTracer::Scope(isolate->GetCodeTracer())
                       : nullptr) {
  if (isolate->deoptimizer_lazy_throw()) {
    CHECK_EQ(kind, DeoptimizeKind::kLazy);
    isolate->set_deoptimizer_lazy_throw(false);
    deoptimizing_throw_ = true;
  }
  if (isolate->debug()->IsRestartFrameScheduled()) {
    CHECK(deoptimizing_throw_);
    restart_frame_index_ = isolate->debug()->restart_inline_frame_index();
    CHECK_GE(restart_frame_index_, 0);
    isolate->debug()->clear_restart_frame();
  }
  DCHECK_NE(from, kNullAddress);
#ifdef DEBUG
  DCHECK(AllowGarbageCollection::IsAllowed());
  disallow_garbage_collection_ = new DisallowGarbageCollection();
#endif // DEBUG
#if V8_ENABLE_WEBASSEMBLY
  if (v8_flags.wasm_deopt && function.is_null()) {
    // From now on we should not be accessing any in-sandbox data as all deopt
    // data is trusted and so stored outside the heap.
    no_sandbox_access_during_wasm_deopt_.emplace();
    wasm::WasmCode* code =
        wasm::GetWasmCodeManager()->LookupCode(isolate, from);
    compiled_optimized_wasm_code_ = code;
    DCHECK_NOT_NULL(code);
    CHECK_EQ(code->kind(), wasm::WasmCode::kWasmFunction);
    wasm::WasmDeoptView deopt_view(code->deopt_data());
    const wasm::WasmDeoptData& deopt_data = deopt_view.GetDeoptData();
    DCHECK_NE(deopt_data.translation_array_size, 0);
    CHECK_GE(from, deopt_data.deopt_exit_start_offset);
    Address deopt_exit_offset = from - code->instruction_start();
    // All eager deopt exits are calls "at the end" of the code to the builtin
    // generated by Generate_DeoptimizationEntry_Eager. These calls have a fixed
    // size kEagerDeoptExitsSize and the deopt data contains the offset of the
    // first such call to the beginning of the code, so we can map any PC of
    // such call to a unique index for this deopt point.
    deopt_exit_index_ =
        static_cast<uint32_t>(deopt_exit_offset -
                              deopt_data.deopt_exit_start_offset -
                              kEagerDeoptExitSize) /
        kEagerDeoptExitSize;
    // Note: The parameter stack slots are not really part of the frame.
    // However, the deoptimizer needs access to the incoming parameter values
    // and therefore they need to be included in the FrameDescription. Between
    // the parameters and the actual frame there are 2 pointers (the caller's pc
    // and saved stack pointer) that therefore also need to be included. Both
    // pointers as well as the incoming parameter stack slots are going to be
    // copied into the outgoing FrameDescription which will "push" them back
    // onto the stack. (This is consistent with how JS handles this.)
    const wasm::FunctionSig* sig =
        code->native_module()->module()->functions[code->index()].sig;
    int parameter_stack_slots, return_stack_slots;
    GetWasmStackSlotsCounts(sig, &parameter_stack_slots, &return_stack_slots);
    unsigned input_frame_size = fp_to_sp_delta +
                                parameter_stack_slots * kSystemPointerSize +
                                CommonFrameConstants::kFixedFrameSizeAboveFp;
    input_ = FrameDescription::Create(input_frame_size, parameter_stack_slots,
                                      isolate_);
    return;
  }
#endif
  compiled_code_ = isolate_->heap()->FindCodeForInnerPointer(from);
  DCHECK(!compiled_code_.is_null());
  DCHECK(IsCode(compiled_code_));
  DCHECK(IsJSFunction(function));
  CHECK(CodeKindCanDeoptimize(compiled_code_->kind()));
  {
    HandleScope scope(isolate_);
    PROFILE(isolate_, CodeDeoptEvent(direct_handle(compiled_code_, isolate_),
                                     kind, from_, fp_to_sp_delta_));
  }
  unsigned size = ComputeInputFrameSize();
  const int parameter_count = compiled_code_->parameter_count();
  DCHECK_EQ(
      parameter_count,
      function->shared()->internal_formal_parameter_count_with_receiver());
  input_ = FrameDescription::Create(size, parameter_count, isolate_);
  DCHECK_EQ(deopt_exit_index_, kFixedExitSizeMarker);
  // Calculate the deopt exit index from return address.
  DCHECK_GT(kEagerDeoptExitSize, 0);
  DCHECK_GT(kLazyDeoptExitSize, 0);
  Tagged<DeoptimizationData> deopt_data =
      Cast<DeoptimizationData>(compiled_code_->deoptimization_data());
  Address deopt_start = compiled_code_->instruction_start() +
                        deopt_data->DeoptExitStart().value();
  int eager_deopt_count = deopt_data->EagerDeoptCount().value();
  Address lazy_deopt_start =
      deopt_start + eager_deopt_count * kEagerDeoptExitSize;
  // The deoptimization exits are sorted so that lazy deopt exits appear after
  // eager deopts.
  static_assert(static_cast<int>(DeoptimizeKind::kLazy) ==
                    static_cast<int>(kLastDeoptimizeKind),
                "lazy deopts are expected to be emitted last");
  // from_ is the value of the link register after the call to the
  // deoptimizer, so for the last lazy deopt, from_ points to the first
  // non-lazy deopt, so we use <=, similarly for the last non-lazy deopt and
  // the first deopt with resume entry.
  if (from_ <= lazy_deopt_start) {
    DCHECK_EQ(kind, DeoptimizeKind::kEager);
    int offset = static_cast<int>(from_ - kEagerDeoptExitSize - deopt_start);
    DCHECK_EQ(0, offset % kEagerDeoptExitSize);
    deopt_exit_index_ = offset / kEagerDeoptExitSize;
  } else {
    DCHECK_EQ(kind, DeoptimizeKind::kLazy);
    int offset =
        static_cast<int>(from_ - kLazyDeoptExitSize - lazy_deopt_start);
    DCHECK_EQ(0, offset % kLazyDeoptExitSize);
    deopt_exit_index_ = eager_deopt_count + (offset / kLazyDeoptExitSize);
  }
}
References CHECK, CHECK_EQ, CHECK_GE, v8::internal::Debug::clear_restart_frame(), code, v8::internal::CodeKindCanDeoptimize(), compiled_code_, ComputeInputFrameSize(), v8::internal::FrameDescription::Create(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, DCHECK_NE, DCHECK_NOT_NULL, v8::internal::Isolate::debug(), deopt_exit_index_, v8::internal::wasm::WasmDeoptData::deopt_exit_start_offset, v8::internal::Isolate::deoptimizer_lazy_throw(), deoptimizing_throw_, v8::internal::direct_handle(), v8::internal::Heap::FindCodeForInnerPointer(), fp_to_sp_delta_, from_, function(), v8::internal::wasm::WasmDeoptView::GetDeoptData(), v8::internal::wasm::GetWasmCodeManager(), v8::internal::Isolate::heap(), input_, isolate(), isolate_, v8::internal::Debug::IsRestartFrameScheduled(), v8::internal::kEager, kEagerDeoptExitSize, kFixedExitSizeMarker, v8::internal::CommonFrameConstants::kFixedFrameSizeAboveFp, v8::internal::kLastDeoptimizeKind, v8::internal::kLazy, kLazyDeoptExitSize, v8::internal::kNullAddress, v8::internal::kSystemPointerSize, v8::internal::wasm::WasmCode::kWasmFunction, v8::internal::wasm::WasmCodeManager::LookupCode(), PROFILE, restart_frame_index_, v8::internal::Debug::restart_inline_frame_index(), v8::internal::Isolate::set_deoptimizer_lazy_throw(), v8::internal::sig, size(), v8::internal::wasm::WasmDeoptData::translation_array_size, and v8::internal::v8_flags.
Member Function Documentation
bytecode_offset_in_outermost_frame()
BytecodeOffset v8::internal::Deoptimizer::bytecode_offset_in_outermost_frame () const [inline]
Definition at line 79 of file deoptimizer.h.
                                                            {
    return bytecode_offset_in_outermost_frame_;
  }
References bytecode_offset_in_outermost_frame_.
Referenced by v8::internal::RUNTIME_FUNCTION().
caller_frame_top_offset()
static int v8::internal::Deoptimizer::caller_frame_top_offset () [inline], [static]
Definition at line 142 of file deoptimizer.h.
                                       {
    return offsetof(Deoptimizer, caller_frame_top_);
  }
References caller_frame_top_.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_DeoptimizationEntry().
compiled_code()
DirectHandle< Code > v8::internal::Deoptimizer::compiled_code () const
Definition at line 751 of file deoptimizer.cc.
                                                    {
  return DirectHandle<Code>(compiled_code_, isolate());
}
References compiled_code_, and isolate().
Referenced by v8::internal::RUNTIME_FUNCTION().
ComputeIncomingArgumentSize()
unsigned v8::internal::Deoptimizer::ComputeIncomingArgumentSize (Tagged< Code > code) [static], [private]
Definition at line 3052 of file deoptimizer.cc.
                                                                   {
  int parameter_slots = code->parameter_count();
  return parameter_slots * kSystemPointerSize;
}
References code, and v8::internal::kSystemPointerSize.
Referenced by ComputeInputFrameAboveFpFixedSize().
ComputeInputFrameAboveFpFixedSize()
unsigned v8::internal::Deoptimizer::ComputeInputFrameAboveFpFixedSize () const [private]
Definition at line 2977 of file deoptimizer.cc.
                                                              {
  unsigned fixed_size = CommonFrameConstants::kFixedFrameSizeAboveFp;
  IF_WASM(DCHECK_IMPLIES, function_.is_null(), v8_flags.wasm_deopt);
  DCHECK_IMPLIES(function_.is_null(), compiled_code_->parameter_count() == 0);
  fixed_size += ComputeIncomingArgumentSize(compiled_code_);
  return fixed_size;
}
References compiled_code_, ComputeIncomingArgumentSize(), DCHECK_IMPLIES, function_, IF_WASM, v8::internal::CommonFrameConstants::kFixedFrameSizeAboveFp, and v8::internal::v8_flags.
Referenced by ComputeInputFrameSize(), and DoComputeOutputFrames().
ComputeInputFrameSize()
unsigned v8::internal::Deoptimizer::ComputeInputFrameSize () const [private]
Definition at line 3015 of file deoptimizer.cc.
                                                  {
  // The fp-to-sp delta already takes the context, constant pool pointer and the
  // function into account so we have to avoid double counting them.
  unsigned fixed_size_above_fp = ComputeInputFrameAboveFpFixedSize();
  unsigned result = fixed_size_above_fp + fp_to_sp_delta_;
  DCHECK(CodeKindCanDeoptimize(compiled_code_->kind()));
  unsigned stack_slots = compiled_code_->stack_slots();
  if (compiled_code_->is_maglevved() && !deoptimizing_throw_) {
    // Maglev code can deopt in deferred code which has spilled registers across
    // the call. These will be included in the fp_to_sp_delta, but the expected
    // frame size won't include them, so we need to check for less-equal rather
    // than equal. For deoptimizing throws, these will have already been trimmed
    // off.
    CHECK_LE(fixed_size_above_fp + (stack_slots * kSystemPointerSize) -
                 CommonFrameConstants::kFixedFrameSizeAboveFp,
             result);
    // With slow asserts we can check this exactly, by looking up the safepoint.
    if (v8_flags.enable_slow_asserts) {
      Address deopt_call_pc = GetDeoptCallPCFromReturnPC(from_, compiled_code_);
      MaglevSafepointTable table(isolate_, deopt_call_pc, compiled_code_);
      MaglevSafepointEntry safepoint = table.FindEntry(deopt_call_pc);
      unsigned extra_spills = safepoint.num_extra_spill_slots();
      CHECK_EQ(fixed_size_above_fp + (stack_slots * kSystemPointerSize) -
                   CommonFrameConstants::kFixedFrameSizeAboveFp +
                   extra_spills * kSystemPointerSize,
               result);
    }
  } else {
    unsigned outgoing_size = 0;
    CHECK_EQ(fixed_size_above_fp + (stack_slots * kSystemPointerSize) -
                 CommonFrameConstants::kFixedFrameSizeAboveFp + outgoing_size,
             result);
  }
  return result;
}
References CHECK_EQ, CHECK_LE, v8::internal::CodeKindCanDeoptimize(), compiled_code_, ComputeInputFrameAboveFpFixedSize(), v8::internal::DCHECK(), deoptimizing_throw_, v8::internal::MaglevSafepointTable::FindEntry(), fp_to_sp_delta_, from_, v8::internal::anonymous_namespace{deoptimizer.cc}::GetDeoptCallPCFromReturnPC(), isolate_, v8::internal::CommonFrameConstants::kFixedFrameSizeAboveFp, v8::internal::kSystemPointerSize, v8::internal::MaglevSafepointEntry::num_extra_spill_slots(), v8::base::internal::result, and v8::internal::v8_flags.
Referenced by Deoptimizer().
ComputeOutputFrames()
void v8::internal::Deoptimizer::ComputeOutputFrames (Deoptimizer * deoptimizer) [static]
Definition at line 580 of file deoptimizer.cc.
                                                              {
  deoptimizer->DoComputeOutputFrames();
#if V8_ENABLE_WEBASSEMBLY
  // TODO(mliedtke,415707239): Ideally we'd only reset this when destroying this
  // object, however when calling the WasmLiftoffDeoptFinish builtin, we read
  // from the heap (probably in DEBUG-only code).
  deoptimizer->no_sandbox_access_during_wasm_deopt_.reset();
#endif
}
References DoComputeOutputFrames().
DebuggerInspectableFrame()
DeoptimizedFrameInfo * v8::internal::Deoptimizer::DebuggerInspectableFrame (JavaScriptFrame * frame, int jsframe_index, Isolate * isolate) [static]
Definition at line 297 of file deoptimizer.cc.
                                                                 {
  CHECK(frame->is_optimized_js());
  TranslatedState translated_values(frame);
  translated_values.Prepare(frame->fp());
  TranslatedState::iterator frame_it = translated_values.end();
  int counter = jsframe_index;
  for (auto it = translated_values.begin(); it != translated_values.end();
       it++) {
    if (it->kind() == TranslatedFrame::kUnoptimizedFunction ||
        it->kind() == TranslatedFrame::kJavaScriptBuiltinContinuation ||
        it->kind() ==
            TranslatedFrame::kJavaScriptBuiltinContinuationWithCatch) {
      if (counter == 0) {
        frame_it = it;
        break;
      }
      counter--;
    }
  }
  CHECK(frame_it != translated_values.end());
  // We only include kJavaScriptBuiltinContinuation frames above to get the
  // counting right.
  CHECK_EQ(frame_it->kind(), TranslatedFrame::kUnoptimizedFunction);
  DeoptimizedFrameInfo* info =
      new DeoptimizedFrameInfo(&translated_values, frame_it, isolate);
  return info;
}
References v8::internal::TranslatedState::begin(), CHECK, CHECK_EQ, v8::internal::TranslatedState::end(), v8::internal::StackFrame::fp(), v8::internal::StackFrame::is_optimized_js(), v8::internal::TranslatedFrame::kJavaScriptBuiltinContinuation, v8::internal::TranslatedFrame::kJavaScriptBuiltinContinuationWithCatch, v8::internal::TranslatedFrame::kUnoptimizedFunction, and v8::internal::TranslatedState::Prepare().
Referenced by v8::internal::FrameInspector::FrameInspector().
DeleteForWasm()
size_t v8::internal::Deoptimizer::DeleteForWasm (Isolate * isolate) [static]
Definition at line 286 of file deoptimizer.cc.
                                                  {
  // The deoptimizer disallows garbage collections.
  DCHECK(!AllowGarbageCollection::IsAllowed());
  Deoptimizer* deoptimizer = Deoptimizer::Grab(isolate);
  int output_count = deoptimizer->output_count();
  delete deoptimizer;
  // Now garbage collections are allowed again.
  DCHECK(AllowGarbageCollection::IsAllowed());
  return output_count;
}
References v8::internal::DCHECK(), Grab(), and output_count().
Referenced by v8::internal::RUNTIME_FUNCTION().
DeleteFrameDescriptions()
void v8::internal::Deoptimizer::DeleteFrameDescriptions () [private]
Definition at line 764 of file deoptimizer.cc.
                                          {
  delete input_;
  for (int i = 0; i < output_count_; ++i) {
    if (output_[i] != input_) delete output_[i];
  }
  delete[] output_;
  input_ = nullptr;
  output_ = nullptr;
#ifdef V8_ENABLE_CET_SHADOW_STACK
  if (shadow_stack_ != nullptr) {
    delete[] shadow_stack_;
    shadow_stack_ = nullptr;
  }
#endif // V8_ENABLE_CET_SHADOW_STACK
#ifdef DEBUG
  DCHECK(!AllowGarbageCollection::IsAllowed());
  DCHECK_NOT_NULL(disallow_garbage_collection_);
  delete disallow_garbage_collection_;
  disallow_garbage_collection_ = nullptr;
#endif // DEBUG
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::anonymous_namespace{json-stringifier.cc}::i, input_, output_, and output_count_.
deopt_kind()
DeoptimizeKind v8::internal::Deoptimizer::deopt_kind () const [inline]
Definition at line 73 of file deoptimizer.h.
{ return deopt_kind_; }
References deopt_kind_.
Referenced by v8::internal::RUNTIME_FUNCTION().
DeoptExitIsInsideOsrLoop()
bool v8::internal::Deoptimizer::DeoptExitIsInsideOsrLoop (Isolate * isolate, Tagged< JSFunction > function, BytecodeOffset deopt_exit_offset, BytecodeOffset osr_offset, CodeKind code_kind) [static]
Definition at line 1745 of file deoptimizer.cc.
                                                               {
  DisallowGarbageCollection no_gc;
  HandleScope scope(isolate);
  DCHECK(!deopt_exit_offset.IsNone());
  DCHECK(!osr_offset.IsNone());
  Handle<BytecodeArray> bytecode_array(
      function->shared()->GetBytecodeArray(isolate), isolate);
  DCHECK(interpreter::BytecodeArrayIterator::IsValidOffset(
      bytecode_array, deopt_exit_offset.ToInt()));
  interpreter::BytecodeArrayIterator it(bytecode_array, osr_offset.ToInt());
  CHECK(it.CurrentBytecodeIsValidOSREntry());
  const int osr_loop_nesting_level = it.GetImmediateOperand(1);
  for (; !it.done(); it.Advance()) {
    const int current_offset = it.current_offset();
    // If we've reached the deopt exit, it's contained in the current loop
    // (this is covered by IsInRange below, but this check lets us avoid
    // useless iteration).
    if (current_offset == deopt_exit_offset.ToInt()) return true;
    // We're only interested in loop ranges.
    if (it.current_bytecode() != interpreter::Bytecode::kJumpLoop) continue;
    // Is the deopt exit contained in the current loop?
    if (base::IsInRange(deopt_exit_offset.ToInt(), it.GetJumpTargetOffset(),
                        current_offset)) {
      return true;
    }
    // We've reached nesting level 0, i.e. the current JumpLoop concludes a
    // top-level loop.
    const int loop_nesting_level = it.GetImmediateOperand(1);
    if (loop_nesting_level == 0) return false;
    // Maglev never jumps above the OSR loop.
    if (code_kind == CodeKind::MAGLEV &&
        loop_nesting_level < osr_loop_nesting_level) {
      return false;
    }
  }
  UNREACHABLE();
}
References v8::internal::interpreter::BytecodeArrayIterator::Advance(), CHECK, v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), v8::internal::interpreter::BytecodeArrayIterator::CurrentBytecodeIsValidOSREntry(), v8::internal::DCHECK(), v8::internal::interpreter::BytecodeArrayIterator::done(), function(), v8::internal::interpreter::BytecodeArrayIterator::GetImmediateOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset(), v8::internal::BytecodeOffset::IsNone(), isolate(), v8::internal::interpreter::BytecodeArrayIterator::IsValidOffset(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::BytecodeOffset::ToInt(), and v8::internal::UNREACHABLE().
Referenced by DoComputeOutputFrames().
DeoptimizeAll()
void v8::internal::Deoptimizer::DeoptimizeAll (Isolate * isolate) [static]
Definition at line 454 of file deoptimizer.cc.
                                                {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kDeoptimizeCode);
  TimerEventScope<TimerEventDeoptimizeCode> timer(isolate);
  TRACE_EVENT0("v8", "V8.DeoptimizeCode");
  TraceDeoptAll(isolate);
  isolate->AbortConcurrentOptimization(BlockingBehavior::kBlock);
  // Mark all code, then deoptimize.
  {
    DeoptimizableCodeIterator it(isolate);
    for (Tagged<Code> code = it.Next(); !code.is_null(); code = it.Next()) {
      code->SetMarkedForDeoptimization(isolate,
                                       LazyDeoptimizeReason::kDebugger);
    }
  }
  DeoptimizeMarkedCode(isolate);
}
References v8::internal::Isolate::AbortConcurrentOptimization(), code, v8::internal::kBlock, RCS_SCOPE, and TRACE_EVENT0.
Referenced by v8::D8Testing::DeoptimizeAll(), v8::internal::Debug::PrepareFunctionForDebugExecution(), v8::Shell::RunMain(), and v8::internal::Coverage::SelectMode().
DeoptimizeAllOptimizedCodeWithFunction()
void v8::internal::Deoptimizer::DeoptimizeAllOptimizedCodeWithFunction (Isolate * isolate, DirectHandle< SharedFunctionInfo > function) [static]
Definition at line 501 of file deoptimizer.cc.
                                                                 {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kDeoptimizeCode);
  TimerEventScope<TimerEventDeoptimizeCode> timer(isolate);
  TRACE_EVENT0("v8", "V8.DeoptimizeAllOptimizedCodeWithFunction");
  // Make sure no new code is compiled with the function.
  isolate->AbortConcurrentOptimization(BlockingBehavior::kBlock);
  // Mark all code that inlines this function, then deoptimize.
  bool any_marked = false;
  {
    DeoptimizableCodeIterator it(isolate);
    for (Tagged<Code> code = it.Next(); !code.is_null(); code = it.Next()) {
      if (code->Inlines(*function)) {
        code->SetMarkedForDeoptimization(isolate,
                                         LazyDeoptimizeReason::kDebugger);
        any_marked = true;
      }
    }
  }
  if (any_marked) {
    DeoptimizeMarkedCode(isolate);
  }
}
References v8::internal::Isolate::AbortConcurrentOptimization(), code, v8::internal::kBlock, RCS_SCOPE, and TRACE_EVENT0.
Referenced by v8::internal::Debug::DeoptimizeFunction().
DeoptimizeFunction()
void v8::internal::Deoptimizer::DeoptimizeFunction (Tagged< JSFunction > function, LazyDeoptimizeReason reason, Tagged< Code > code = {}) [static]
Definition at line 474 of file deoptimizer.cc.
                                                        {
  Isolate* isolate = Isolate::Current();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kDeoptimizeCode);
  TimerEventScope<TimerEventDeoptimizeCode> timer(isolate);
  TRACE_EVENT0("v8", "V8.DeoptimizeCode");
  function->ResetIfCodeFlushed(isolate);
  if (code.is_null()) code = function->code(isolate);
  if (CodeKindCanDeoptimize(code->kind())) {
    // Mark the code for deoptimization and unlink any functions that also
    // refer to that code. The code cannot be shared across native contexts,
    // so we only need to search one.
    code->SetMarkedForDeoptimization(isolate, reason);
#ifndef V8_ENABLE_LEAPTIERING_BOOL
    // The code in the function's optimized code feedback vector slot might
    // be different from the code on the function - evict it if necessary.
    function->feedback_vector()->EvictOptimizedCodeMarkedForDeoptimization(
        isolate, function->shared(), "unlinking code marked for deopt");
#endif // !V8_ENABLE_LEAPTIERING_BOOL
    DeoptimizeMarkedCode(isolate);
  }
}
References code, v8::internal::CodeKindCanDeoptimize(), v8::internal::Isolate::Current(), RCS_SCOPE, and TRACE_EVENT0.
Referenced by v8::internal::OptimizedJSFrame::LookupExceptionHandlerInTable(), v8::internal::Debug::PrepareRestartFrame(), v8::internal::Debug::PrepareStep(), v8::internal::Debug::PrepareStepOnThrow(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt().
DeoptimizeMarkedCode()
void v8::internal::Deoptimizer::DeoptimizeMarkedCode (Isolate * isolate) [static]
Definition at line 405 of file deoptimizer.cc.
                                                       {
  DisallowGarbageCollection no_gc;
  Tagged<GcSafeCode> topmost_optimized_code;
  bool safe_to_deopt_topmost_optimized_code = false;
#ifdef DEBUG
  // Make sure all activations of optimized code can deopt at their current PC.
  // The topmost optimized code has special handling because it cannot be
  // deoptimized due to weak object dependency.
  for (StackFrameIterator it(isolate, isolate->thread_local_top()); !it.done();
       it.Advance()) {
    if (it.frame()->is_optimized_js()) {
      Tagged<GcSafeCode> code = it.frame()->GcSafeLookupCode();
      Tagged<JSFunction> function =
          static_cast<OptimizedJSFrame*>(it.frame())->function();
      TraceFoundActivation(isolate, function);
      bool safe_if_deopt_triggered;
      if (code->is_maglevved()) {
        MaglevSafepointEntry safepoint =
            MaglevSafepointTable::FindEntry(isolate, code, it.frame()->pc());
        safe_if_deopt_triggered = safepoint.has_deoptimization_index();
      } else {
        SafepointEntry safepoint = SafepointTable::FindEntry(
            isolate, code, it.frame()->maybe_unauthenticated_pc());
        safe_if_deopt_triggered = safepoint.has_deoptimization_index();
      }
      // Deopt is checked when we are patching addresses on stack.
      bool is_builtin_code = code->kind() == CodeKind::BUILTIN;
      DCHECK(topmost_optimized_code.is_null() || safe_if_deopt_triggered ||
             is_builtin_code);
      if (topmost_optimized_code.is_null()) {
        topmost_optimized_code = code;
        safe_to_deopt_topmost_optimized_code = safe_if_deopt_triggered;
      }
    }
  }
#endif
  ActivationsFinder visitor(topmost_optimized_code,
                            safe_to_deopt_topmost_optimized_code);
  // Iterate over the stack of this thread.
  visitor.VisitThread(isolate, isolate->thread_local_top());
  // In addition to iterate over the stack of this thread, we also
  // need to consider all the other threads as they may also use
  // the code currently beings deoptimized.
  isolate->thread_manager()->IterateArchivedThreads(&visitor);
}
References BUILTIN, code, v8::internal::DCHECK(), v8::internal::StackFrameIteratorBase::done(), v8::internal::MaglevSafepointTable::FindEntry(), v8::internal::SafepointTable::FindEntry(), v8::internal::SafepointEntryBase::has_deoptimization_index(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::ThreadManager::IterateArchivedThreads(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Isolate::thread_local_top(), and v8::internal::Isolate::thread_manager().
Referenced by v8::internal::DependentCode::DeoptimizeDependencyGroups(), v8::internal::Heap::DeoptMarkedAllocationSites(), and v8::internal::MarkCompactCollector::Finish().
DoComputeBuiltinContinuation()
void v8::internal::Deoptimizer::DoComputeBuiltinContinuation (TranslatedFrame * translated_frame, int frame_index, BuiltinContinuationMode mode) [private]
Definition at line 2604 of file deoptimizer.cc.
                                  {
  TranslatedFrame::iterator result_iterator = translated_frame->end();
  bool is_js_to_wasm_builtin_continuation = false;
#if V8_ENABLE_WEBASSEMBLY
  is_js_to_wasm_builtin_continuation =
      translated_frame->kind() == TranslatedFrame::kJSToWasmBuiltinContinuation;
  if (is_js_to_wasm_builtin_continuation) {
    // For JSToWasmBuiltinContinuations, add a TranslatedValue with the result
    // of the Wasm call, extracted from the input FrameDescription.
    // This TranslatedValue will be written in the output frame in place of the
    // hole and we'll use ContinueToCodeStubBuiltin in place of
    // ContinueToCodeStubBuiltinWithResult.
    TranslatedValue result = TranslatedValueForWasmReturnKind(
        translated_frame->wasm_call_return_kind());
    translated_frame->Add(result);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  TranslatedFrame::iterator value_iterator = translated_frame->begin();
  const BytecodeOffset bytecode_offset = translated_frame->bytecode_offset();
  Builtin builtin = Builtins::GetBuiltinFromBytecodeOffset(bytecode_offset);
  CallInterfaceDescriptor continuation_descriptor =
      Builtins::CallInterfaceDescriptorFor(builtin);
  const RegisterConfiguration* config = RegisterConfiguration::Default();
  const bool is_bottommost = (0 == frame_index);
  const bool is_topmost = (output_count_ - 1 == frame_index);
  const int parameters_count = translated_frame->height();
  BuiltinContinuationFrameInfo frame_info =
      BuiltinContinuationFrameInfo::Precise(parameters_count,
                                            continuation_descriptor, config,
                                            is_topmost, deopt_kind_, mode);
  const unsigned output_frame_size = frame_info.frame_size_in_bytes();
  const unsigned output_frame_size_above_fp =
      frame_info.frame_size_in_bytes_above_fp();
  // Validate types of parameters. They must all be tagged except for argc and
  // the dispatch handle for JS builtins.
  bool has_argc = false;
  const int register_parameter_count =
      continuation_descriptor.GetRegisterParameterCount();
  for (int i = 0; i < register_parameter_count; ++i) {
    MachineType type = continuation_descriptor.GetParameterType(i);
    int code = continuation_descriptor.GetRegisterParameter(i).code();
    // Only tagged and int32 arguments are supported, and int32 only for the
    // arguments count and dispatch handle on JavaScript builtins.
    if (type == MachineType::Int32()) {
      CHECK(code == kJavaScriptCallArgCountRegister.code() ||
            code == kJavaScriptCallDispatchHandleRegister.code());
      has_argc = true;
    } else {
      // Any other argument must be a tagged value.
      CHECK(IsAnyTagged(type.representation()));
    }
  }
  CHECK_EQ(BuiltinContinuationModeIsJavaScript(mode), has_argc);
  if (verbose_tracing_enabled()) {
    PrintF(trace_scope()->file(),
           " translating BuiltinContinuation to %s,"
           " => register_param_count=%d,"
           " stack_param_count=%d, frame_size=%d\n",
           Builtins::name(builtin), register_parameter_count,
           frame_info.stack_parameter_count(), output_frame_size);
  }
  FrameDescription* output_frame = FrameDescription::Create(
      output_frame_size, frame_info.stack_parameter_count(), isolate());
  output_[frame_index] = output_frame;
  FrameWriter frame_writer(this, output_frame, verbose_trace_scope());
  // The top address of the frame is computed from the previous frame's top and
  // this frame's size.
  const intptr_t top_address =
      is_bottommost ? caller_frame_top_ - output_frame_size
                    : output_[frame_index - 1]->GetTop() - output_frame_size;
  output_frame->SetTop(top_address);
  // Get the possible JSFunction for the case that this is a
  // JavaScriptBuiltinContinuationFrame, which needs the JSFunction pointer
  // like a normal JavaScriptFrame.
  const intptr_t maybe_function = value_iterator->GetRawValue().ptr();
  ++value_iterator;
  ReadOnlyRoots roots(isolate());
  const int padding = ArgumentPaddingSlots(frame_info.stack_parameter_count());
  for (int i = 0; i < padding; ++i) {
    frame_writer.PushRawObject(roots.the_hole_value(), "padding\n");
  }
  if (mode == BuiltinContinuationMode::STUB) {
    DCHECK_EQ(continuation_descriptor.GetStackArgumentOrder(),
              StackArgumentOrder::kDefault);
    for (uint32_t i = 0; i < frame_info.translated_stack_parameter_count();
         ++i, ++value_iterator) {
      frame_writer.PushTranslatedValue(value_iterator, "stack parameter");
    }
    if (frame_info.frame_has_result_stack_slot()) {
      if (is_js_to_wasm_builtin_continuation) {
        frame_writer.PushTranslatedValue(result_iterator,
                                         "return result on lazy deopt\n");
      } else {
        DCHECK_EQ(result_iterator, translated_frame->end());
        frame_writer.PushRawObject(
            roots.the_hole_value(),
            "placeholder for return result on lazy deopt\n");
      }
    }
  } else {
    // JavaScript builtin.
    if (frame_info.frame_has_result_stack_slot()) {
      frame_writer.PushRawObject(
          roots.the_hole_value(),
          "placeholder for return result on lazy deopt\n");
    }
    switch (mode) {
      case BuiltinContinuationMode::STUB:
        UNREACHABLE();
      case BuiltinContinuationMode::JAVASCRIPT:
        break;
      case BuiltinContinuationMode::JAVASCRIPT_WITH_CATCH: {
        frame_writer.PushRawObject(roots.the_hole_value(),
                                   "placeholder for exception on lazy deopt\n");
      } break;
      case BuiltinContinuationMode::JAVASCRIPT_HANDLE_EXCEPTION: {
        intptr_t accumulator_value =
            input_->GetRegister(kInterpreterAccumulatorRegister.code());
        frame_writer.PushRawObject(Tagged<Object>(accumulator_value),
                                   "exception (from accumulator)\n");
      } break;
    }
    frame_writer.PushStackJSArguments(
        value_iterator, frame_info.translated_stack_parameter_count());
  }
  DCHECK_EQ(output_frame->GetLastArgumentSlotOffset(),
            frame_writer.top_offset());
  std::vector<TranslatedFrame::iterator> register_values;
  int total_registers = config->num_general_registers();
  register_values.resize(total_registers, {value_iterator});
  for (int i = 0; i < register_parameter_count; ++i, ++value_iterator) {
    int code = continuation_descriptor.GetRegisterParameter(i).code();
    register_values[code] = value_iterator;
  }
  // The context register is always implicit in the CallInterfaceDescriptor but
  // its register must be explicitly set when continuing to the builtin. Make
  // sure that it's harvested from the translation and copied into the register
  // set (it was automatically added at the end of the FrameState by the
  // instruction selector).
  Tagged<Object> context = value_iterator->GetRawValue();
  const intptr_t value = context.ptr();
  TranslatedFrame::iterator context_register_value = value_iterator++;
  register_values[kContextRegister.code()] = context_register_value;
  output_frame->SetRegister(kContextRegister.code(), value);
  // Set caller's PC (JSFunction continuation).
  if (is_bottommost) {
    frame_writer.PushBottommostCallerPc(caller_pc_);
  } else {
    frame_writer.PushApprovedCallerPc(output_[frame_index - 1]->GetPc());
  }
  // Read caller's FP from the previous frame, and set this frame's FP.
  const intptr_t caller_fp =
      is_bottommost ? caller_fp_ : output_[frame_index - 1]->GetFp();
  frame_writer.PushCallerFp(caller_fp);
  const intptr_t fp_value = top_address + frame_writer.top_offset();
  output_frame->SetFp(fp_value);
  DCHECK_EQ(output_frame_size_above_fp, frame_writer.top_offset());
  if (V8_EMBEDDED_CONSTANT_POOL_BOOL) {
    // Read the caller's constant pool from the previous frame.
    const intptr_t caller_cp =
        is_bottommost ? caller_constant_pool_
                      : output_[frame_index - 1]->GetConstantPool();
    frame_writer.PushCallerConstantPool(caller_cp);
  }
  // A marker value is used in place of the context.
  const intptr_t marker =
      StackFrame::TypeToMarker(BuiltinContinuationModeToFrameType(mode));
  frame_writer.PushRawValue(marker,
                            "context (builtin continuation sentinel)\n");
  if (BuiltinContinuationModeIsJavaScript(mode)) {
    frame_writer.PushRawValue(maybe_function, "JSFunction\n");
  } else {
    frame_writer.PushRawValue(0, "unused\n");
  }
  // The delta from the SP to the FP; used to reconstruct SP in
  // Isolate::UnwindAndFindHandler.
  frame_writer.PushRawObject(Smi::FromInt(output_frame_size_above_fp),
                             "frame height at deoptimization\n");
  // The context even if this is a stub continuation frame. We can't use the
  // usual context slot, because we must store the frame marker there.
  frame_writer.PushTranslatedValue(context_register_value,
                                   "builtin JavaScript context\n");
  // The builtin to continue to.
  frame_writer.PushRawObject(Smi::FromInt(static_cast<int>(builtin)),
                             "builtin index\n");
  const int allocatable_register_count =
      config->num_allocatable_general_registers();
  for (int i = 0; i < allocatable_register_count; ++i) {
    int code = config->GetAllocatableGeneralCode(i);
    base::ScopedVector<char> str(128);
    if (verbose_tracing_enabled()) {
      if (BuiltinContinuationModeIsJavaScript(mode) &&
          code == kJavaScriptCallArgCountRegister.code()) {
        SNPrintF(
            str,
            "tagged argument count %s (will be untagged by continuation)\n",
            RegisterName(Register::from_code(code)));
      } else {
        SNPrintF(str, "builtin register argument %s\n",
                 RegisterName(Register::from_code(code)));
      }
    }
    frame_writer.PushTranslatedValue(
        register_values[code], verbose_tracing_enabled() ? str.begin() : "");
  }
  // Some architectures must pad the stack frame with extra stack slots
  // to ensure the stack frame is aligned.
  const int padding_slot_count =
      BuiltinContinuationFrameConstants::PaddingSlotCount(
          allocatable_register_count);
  for (int i = 0; i < padding_slot_count; ++i) {
    frame_writer.PushRawObject(roots.the_hole_value(), "padding\n");
  }
  if (is_topmost) {
    for (int i = 0; i < ArgumentPaddingSlots(1); ++i) {
      frame_writer.PushRawObject(roots.the_hole_value(), "padding\n");
    }
    // Ensure the result is restored back when we return to the stub.
    // For JS-to-Wasm builtin continuations the returns are handled differently
    // and we can't push untagged return values onto the stack as they would be
    // visited during a GC and treated as tagged stack slots.
    if (frame_info.frame_has_result_stack_slot() &&
        !is_js_to_wasm_builtin_continuation) {
      Register result_reg = kReturnRegister0;
      frame_writer.PushRawValue(input_->GetRegister(result_reg.code()),
                                "callback result\n");
    } else {
      frame_writer.PushRawObject(roots.undefined_value(), "callback result\n");
    }
  }
  CHECK_EQ(result_iterator, value_iterator);
  CHECK_EQ(0u, frame_writer.top_offset());
  // Clear the context register. The context might be a de-materialized object
  // and will be materialized by {Runtime_NotifyDeoptimized}. For additional
  // safety we use Tagged<Smi>(0) instead of the potential {arguments_marker}
  // here.
  if (is_topmost) {
    intptr_t context_value = static_cast<intptr_t>(Smi::zero().ptr());
    Register context_reg = JavaScriptFrame::context_register();
    output_frame->SetRegister(context_reg.code(), context_value);
  }
  // Ensure the frame pointer register points to the callee's frame. The builtin
  // will build its own frame once we continue to it.
  Register fp_reg = JavaScriptFrame::fp_register();
  output_frame->SetRegister(fp_reg.code(), fp_value);
  // For JSToWasmBuiltinContinuations use ContinueToCodeStubBuiltin, and not
  // ContinueToCodeStubBuiltinWithResult because we don't want to overwrite the
  // return value that we have already set.
  Tagged<Code> continue_to_builtin =
      isolate()->builtins()->code(TrampolineForBuiltinContinuation(
          mode, frame_info.frame_has_result_stack_slot() &&
                    !is_js_to_wasm_builtin_continuation));
  intptr_t pc =
      static_cast<intptr_t>(continue_to_builtin->instruction_start()) +
      isolate()->heap()->deopt_pc_offset_after_adapt_shadow_stack().value();
  if (is_topmost) {
    // Only the pc of the topmost frame needs to be signed since it is
    // authenticated at the end of the DeoptimizationEntry builtin.
    const intptr_t top_most_pc = PointerAuthentication::SignAndCheckPC(
        isolate(), pc, frame_writer.frame()->GetTop());
    output_frame->SetPc(top_most_pc);
  } else {
    output_frame->SetPc(pc);
  }
  Tagged<Code> continuation =
      isolate()->builtins()->code(Builtin::kNotifyDeoptimized);
  output_frame->SetContinuation(
      static_cast<intptr_t>(continuation->instruction_start()));
}
References v8::internal::TranslatedFrame::Add(), v8::internal::ArgumentPaddingSlots(), v8::internal::TranslatedFrame::begin(), v8::base::Vector< T >::begin(), v8::internal::anonymous_namespace{deoptimizer.cc}::BuiltinContinuationModeIsJavaScript(), v8::internal::anonymous_namespace{deoptimizer.cc}::BuiltinContinuationModeToFrameType(), v8::internal::Isolate::builtins(), v8::internal::TranslatedFrame::bytecode_offset(), caller_constant_pool_, caller_fp_, caller_frame_top_, caller_pc_, v8::internal::Builtins::CallInterfaceDescriptorFor(), CHECK, CHECK_EQ, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::Builtins::code(), code, v8::internal::JavaScriptFrame::context_register(), v8::internal::FrameDescription::Create(), DCHECK_EQ, v8::internal::RegisterConfiguration::Default(), deopt_kind_, v8::internal::TranslatedFrame::end(), file(), v8::internal::JavaScriptFrame::fp_register(), v8::internal::FrameWriter::frame(), v8::internal::BuiltinContinuationFrameInfo::frame_has_result_stack_slot(), v8::internal::BuiltinContinuationFrameInfo::frame_size_in_bytes(), v8::internal::BuiltinContinuationFrameInfo::frame_size_in_bytes_above_fp(), v8::internal::Register::from_code(), v8::internal::Smi::FromInt(), v8::internal::RegisterConfiguration::GetAllocatableGeneralCode(), v8::internal::Builtins::GetBuiltinFromBytecodeOffset(), v8::internal::FrameDescription::GetConstantPool(), v8::internal::FrameDescription::GetFp(), v8::internal::FrameDescription::GetLastArgumentSlotOffset(), v8::internal::CallInterfaceDescriptor::GetParameterType(), v8::internal::TranslatedValue::GetRawValue(), v8::internal::FrameDescription::GetRegister(), v8::internal::CallInterfaceDescriptor::GetRegisterParameter(), v8::internal::CallInterfaceDescriptor::GetRegisterParameterCount(), v8::internal::CallInterfaceDescriptor::GetStackArgumentOrder(), v8::internal::FrameDescription::GetTop(), v8::internal::Isolate::heap(), v8::internal::TranslatedFrame::height(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, input_, v8::internal::MachineType::Int32(), v8::internal::IsAnyTagged(), isolate(), v8::internal::JAVASCRIPT, v8::internal::JAVASCRIPT_HANDLE_EXCEPTION, v8::internal::JAVASCRIPT_WITH_CATCH, v8::internal::kContextRegister, v8::internal::kDefault, v8::internal::TranslatedFrame::kind(), v8::internal::kInterpreterAccumulatorRegister, v8::internal::kJavaScriptCallArgCountRegister, v8::internal::kJavaScriptCallDispatchHandleRegister, v8::internal::kReturnRegister0, mode(), v8::internal::Builtins::name(), v8::internal::RegisterConfiguration::num_allocatable_general_registers(), v8::internal::RegisterConfiguration::num_general_registers(), output_, output_count_, v8::internal::BuiltinContinuationFrameConstants::PaddingSlotCount(), v8::internal::BuiltinContinuationFrameInfo::Precise(), v8::internal::PrintF(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::FrameWriter::PushApprovedCallerPc(), v8::internal::FrameWriter::PushBottommostCallerPc(), v8::internal::FrameWriter::PushCallerConstantPool(), v8::internal::FrameWriter::PushCallerFp(), v8::internal::FrameWriter::PushRawObject(), v8::internal::FrameWriter::PushRawValue(), v8::internal::FrameWriter::PushStackJSArguments(), v8::internal::FrameWriter::PushTranslatedValue(), v8::base::internal::result, v8::internal::FrameDescription::SetContinuation(), v8::internal::FrameDescription::SetFp(), v8::internal::FrameDescription::SetPc(), v8::internal::FrameDescription::SetRegister(), v8::internal::FrameDescription::SetTop(), v8::internal::PointerAuthentication::SignAndCheckPC(), v8::base::SNPrintF(), v8::internal::BuiltinContinuationFrameInfo::stack_parameter_count(), v8::internal::STUB, v8::internal::FrameWriter::top_offset(), trace_scope(), TrampolineForBuiltinContinuation(), v8::internal::BuiltinContinuationFrameInfo::translated_stack_parameter_count(), v8::internal::tracing::type, v8::internal::StackFrame::TypeToMarker(), v8::internal::UNREACHABLE(), V8_EMBEDDED_CONSTANT_POOL_BOOL, v8::internal::value, verbose_trace_scope(), verbose_tracing_enabled(), and v8::internal::Smi::zero().
Referenced by DoComputeOutputFrames().
DoComputeConstructCreateStubFrame()
void v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame (TranslatedFrame * translated_frame, int frame_index) [private]
Definition at line 2178 of file deoptimizer.cc.
                                                        {
  TranslatedFrame::iterator value_iterator = translated_frame->begin();
  const bool is_topmost = (output_count_ - 1 == frame_index);
  // The construct frame could become topmost only if we inlined a constructor
  // call which does a tail call (otherwise the tail callee's frame would be
  // the topmost one). So it could only be the DeoptimizeKind::kLazy case.
  CHECK(!is_topmost || deopt_kind_ == DeoptimizeKind::kLazy);
  DCHECK_EQ(translated_frame->kind(), TranslatedFrame::kConstructCreateStub);
  const int parameters_count = translated_frame->height();
  ConstructStubFrameInfo frame_info =
      ConstructStubFrameInfo::Precise(parameters_count, is_topmost);
  const uint32_t output_frame_size = frame_info.frame_size_in_bytes();
  TranslatedFrame::iterator function_iterator = value_iterator++;
  if (verbose_tracing_enabled()) {
    PrintF(trace_scope()->file(),
           " translating construct create stub => variable_frame_size=%d, "
           "frame_size=%d\n",
           frame_info.frame_size_in_bytes_without_fixed(), output_frame_size);
  }
  // Allocate and store the output frame description.
  FrameDescription* output_frame =
      FrameDescription::Create(output_frame_size, parameters_count, isolate());
  FrameWriter frame_writer(this, output_frame, verbose_trace_scope());
  DCHECK(frame_index > 0 && frame_index < output_count_);
  DCHECK_NULL(output_[frame_index]);
  output_[frame_index] = output_frame;
  // The top address of the frame is computed from the previous frame's top and
  // this frame's size.
  const intptr_t top_address =
      output_[frame_index - 1]->GetTop() - output_frame_size;
  output_frame->SetTop(top_address);
  ReadOnlyRoots roots(isolate());
  for (int i = 0; i < ArgumentPaddingSlots(parameters_count); ++i) {
    frame_writer.PushRawObject(roots.the_hole_value(), "padding\n");
  }
  // The allocated receiver of a construct stub frame is passed as the
  // receiver parameter through the translation. It might be encoding
  // a captured object, so we need save it for later.
  TranslatedFrame::iterator receiver_iterator = value_iterator;
  // Compute the incoming parameter translation.
  frame_writer.PushStackJSArguments(value_iterator, parameters_count);
  DCHECK_EQ(output_frame->GetLastArgumentSlotOffset(),
            frame_writer.top_offset());
  // Read caller's PC from the previous frame.
  const intptr_t caller_pc = output_[frame_index - 1]->GetPc();
  frame_writer.PushApprovedCallerPc(caller_pc);
  // Read caller's FP from the previous frame, and set this frame's FP.
  const intptr_t caller_fp = output_[frame_index - 1]->GetFp();
  frame_writer.PushCallerFp(caller_fp);
  const intptr_t fp_value = top_address + frame_writer.top_offset();
  output_frame->SetFp(fp_value);
  if (is_topmost) {
    Register fp_reg = JavaScriptFrame::fp_register();
    output_frame->SetRegister(fp_reg.code(), fp_value);
  }
  if (V8_EMBEDDED_CONSTANT_POOL_BOOL) {
    // Read the caller's constant pool from the previous frame.
    const intptr_t caller_cp = output_[frame_index - 1]->GetConstantPool();
    frame_writer.PushCallerConstantPool(caller_cp);
  }
  // A marker value is used to mark the frame.
  intptr_t marker = StackFrame::TypeToMarker(StackFrame::CONSTRUCT);
  frame_writer.PushRawValue(marker, "context (construct stub sentinel)\n");
  frame_writer.PushTranslatedValue(value_iterator++, "context");
  // Number of incoming arguments.
  const uint32_t argc = parameters_count;
  frame_writer.PushRawValue(argc, "argc\n");
  // The constructor function was mentioned explicitly in the
  // CONSTRUCT_STUB_FRAME.
  frame_writer.PushTranslatedValue(function_iterator, "constructor function\n");
  // The deopt info contains the implicit receiver or the new target at the
  // position of the receiver. Copy it to the top of stack, with the hole value
  // as padding to maintain alignment.
  frame_writer.PushRawObject(roots.the_hole_value(), "padding\n");
  frame_writer.PushTranslatedValue(receiver_iterator, "new target\n");
  if (is_topmost) {
    for (int i = 0; i < ArgumentPaddingSlots(1); ++i) {
      frame_writer.PushRawObject(roots.the_hole_value(), "padding\n");
    }
    // Ensure the result is restored back when we return to the stub.
    Register result_reg = kReturnRegister0;
    intptr_t result = input_->GetRegister(result_reg.code());
    frame_writer.PushRawValue(result, "subcall result\n");
  }
  CHECK_EQ(translated_frame->end(), value_iterator);
  CHECK_EQ(0u, frame_writer.top_offset());
  // Compute this frame's PC.
  Tagged<Code> construct_stub =
      isolate_->builtins()->code(Builtin::kJSConstructStubGeneric);
  Address start = construct_stub->instruction_start();
  const int pc_offset =
      isolate_->heap()->construct_stub_create_deopt_pc_offset().value();
  intptr_t pc_value = static_cast<intptr_t>(start + pc_offset);
  if (is_topmost) {
    // Only the pc of the topmost frame needs to be signed since it is
    // authenticated at the end of the DeoptimizationEntry builtin.
    output_frame->SetPc(PointerAuthentication::SignAndCheckPC(
        isolate(), pc_value, frame_writer.frame()->GetTop()));
  } else {
    output_frame->SetPc(pc_value);
  }
  // Update constant pool.
  if (V8_EMBEDDED_CONSTANT_POOL_BOOL) {
    intptr_t constant_pool_value =
        static_cast<intptr_t>(construct_stub->constant_pool());
    output_frame->SetConstantPool(constant_pool_value);
    if (is_topmost) {
      Register constant_pool_reg =
          JavaScriptFrame::constant_pool_pointer_register();
      output_frame->SetRegister(constant_pool_reg.code(), constant_pool_value);
    }
  }
  // Clear the context register. The context might be a de-materialized object
  // and will be materialized by {Runtime_NotifyDeoptimized}. For additional
  // safety we use Tagged<Smi>(0) instead of the potential {arguments_marker}
  // here.
  if (is_topmost) {
    intptr_t context_value = static_cast<intptr_t>(Smi::zero().ptr());
    Register context_reg = JavaScriptFrame::context_register();
    output_frame->SetRegister(context_reg.code(), context_value);
    // Set the continuation for the topmost frame.
    DCHECK_EQ(DeoptimizeKind::kLazy, deopt_kind_);
    Tagged<Code> continuation =
        isolate_->builtins()->code(Builtin::kNotifyDeoptimized);
    output_frame->SetContinuation(
        static_cast<intptr_t>(continuation->instruction_start()));
  }
}
References v8::internal::ArgumentPaddingSlots(), v8::internal::TranslatedFrame::begin(), v8::internal::Isolate::builtins(), CHECK, CHECK_EQ, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::Builtins::code(), v8::internal::JavaScriptFrame::constant_pool_pointer_register(), v8::internal::JavaScriptFrame::context_register(), v8::internal::FrameDescription::Create(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, deopt_kind_, v8::internal::TranslatedFrame::end(), file(), v8::internal::JavaScriptFrame::fp_register(), v8::internal::FrameWriter::frame(), v8::internal::ConstructStubFrameInfo::frame_size_in_bytes(), v8::internal::ConstructStubFrameInfo::frame_size_in_bytes_without_fixed(), v8::internal::FrameDescription::GetConstantPool(), v8::internal::FrameDescription::GetFp(), v8::internal::FrameDescription::GetLastArgumentSlotOffset(), v8::internal::FrameDescription::GetPc(), v8::internal::FrameDescription::GetRegister(), v8::internal::FrameDescription::GetTop(), v8::internal::Isolate::heap(), v8::internal::TranslatedFrame::height(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, input_, isolate(), isolate_, v8::internal::TranslatedFrame::kConstructCreateStub, v8::internal::TranslatedFrame::kind(), v8::internal::kLazy, v8::internal::kReturnRegister0, output_, output_count_, v8::internal::ConstructStubFrameInfo::Precise(), v8::internal::PrintF(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::FrameWriter::PushApprovedCallerPc(), v8::internal::FrameWriter::PushCallerConstantPool(), v8::internal::FrameWriter::PushCallerFp(), v8::internal::FrameWriter::PushRawObject(), v8::internal::FrameWriter::PushRawValue(), v8::internal::FrameWriter::PushStackJSArguments(), v8::internal::FrameWriter::PushTranslatedValue(), v8::base::internal::result, v8::internal::FrameDescription::SetConstantPool(), v8::internal::FrameDescription::SetContinuation(), v8::internal::FrameDescription::SetFp(), v8::internal::FrameDescription::SetPc(), v8::internal::FrameDescription::SetRegister(), v8::internal::FrameDescription::SetTop(), v8::internal::PointerAuthentication::SignAndCheckPC(), v8::internal::FrameWriter::top_offset(), trace_scope(), v8::internal::StackFrame::TypeToMarker(), V8_EMBEDDED_CONSTANT_POOL_BOOL, verbose_trace_scope(), verbose_tracing_enabled(), and v8::internal::Smi::zero().
Referenced by DoComputeOutputFrames().
DoComputeConstructInvokeStubFrame()
void v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame (TranslatedFrame * translated_frame, int frame_index) [private]
Definition at line 2331 of file deoptimizer.cc.
                                                        {
  TranslatedFrame::iterator value_iterator = translated_frame->begin();
  const bool is_topmost = (output_count_ - 1 == frame_index);
  // The construct frame could become topmost only if we inlined a constructor
  // call which does a tail call (otherwise the tail callee's frame would be
  // the topmost one). So it could only be the DeoptimizeKind::kLazy case.
  CHECK(!is_topmost || deopt_kind_ == DeoptimizeKind::kLazy);
  DCHECK_EQ(translated_frame->kind(), TranslatedFrame::kConstructInvokeStub);
  DCHECK_EQ(translated_frame->height(), 0);
  FastConstructStubFrameInfo frame_info =
      FastConstructStubFrameInfo::Precise(is_topmost);
  const uint32_t output_frame_size = frame_info.frame_size_in_bytes();
  if (verbose_tracing_enabled()) {
    PrintF(trace_scope()->file(),
           " translating construct invoke stub => variable_frame_size=%d, "
           "frame_size=%d\n",
           frame_info.frame_size_in_bytes_without_fixed(), output_frame_size);
  }
  // Allocate and store the output frame description.
  FrameDescription* output_frame =
      FrameDescription::Create(output_frame_size, 0, isolate());
  FrameWriter frame_writer(this, output_frame, verbose_trace_scope());
  DCHECK(frame_index > 0 && frame_index < output_count_);
  DCHECK_NULL(output_[frame_index]);
  output_[frame_index] = output_frame;
  // The top address of the frame is computed from the previous frame's top and
  // this frame's size.
  const intptr_t top_address =
      output_[frame_index - 1]->GetTop() - output_frame_size;
  output_frame->SetTop(top_address);
  // The allocated receiver of a construct stub frame is passed as the
  // receiver parameter through the translation. It might be encoding
  // a captured object, so we need save it for later.
  TranslatedFrame::iterator receiver_iterator = value_iterator;
  value_iterator++;
  // Read caller's PC from the previous frame.
  const intptr_t caller_pc = output_[frame_index - 1]->GetPc();
  frame_writer.PushApprovedCallerPc(caller_pc);
  // Read caller's FP from the previous frame, and set this frame's FP.
  const intptr_t caller_fp = output_[frame_index - 1]->GetFp();
  frame_writer.PushCallerFp(caller_fp);
  const intptr_t fp_value = top_address + frame_writer.top_offset();
  output_frame->SetFp(fp_value);
  if (is_topmost) {
    Register fp_reg = JavaScriptFrame::fp_register();
    output_frame->SetRegister(fp_reg.code(), fp_value);
  }
  if (V8_EMBEDDED_CONSTANT_POOL_BOOL) {
    // Read the caller's constant pool from the previous frame.
    const intptr_t caller_cp = output_[frame_index - 1]->GetConstantPool();
    frame_writer.PushCallerConstantPool(caller_cp);
  }
  intptr_t marker = StackFrame::TypeToMarker(StackFrame::FAST_CONSTRUCT);
  frame_writer.PushRawValue(marker, "fast construct stub sentinel\n");
  frame_writer.PushTranslatedValue(value_iterator++, "context");
  frame_writer.PushTranslatedValue(receiver_iterator, "implicit receiver");
  // The FastConstructFrame needs to be aligned in some architectures.
  ReadOnlyRoots roots(isolate());
  for (int i = 0; i < ArgumentPaddingSlots(1); ++i) {
    frame_writer.PushRawObject(roots.the_hole_value(), "padding\n");
  }
  if (is_topmost) {
    for (int i = 0; i < ArgumentPaddingSlots(1); ++i) {
      frame_writer.PushRawObject(roots.the_hole_value(), "padding\n");
    }
    // Ensure the result is restored back when we return to the stub.
    Register result_reg = kReturnRegister0;
    intptr_t result = input_->GetRegister(result_reg.code());
    frame_writer.PushRawValue(result, "subcall result\n");
  }
  CHECK_EQ(translated_frame->end(), value_iterator);
  CHECK_EQ(0u, frame_writer.top_offset());
  // Compute this frame's PC.
  Tagged<Code> construct_stub = isolate_->builtins()->code(
      Builtin::kInterpreterPushArgsThenFastConstructFunction);
  Address start = construct_stub->instruction_start();
  const int pc_offset =
      isolate_->heap()->construct_stub_invoke_deopt_pc_offset().value();
  intptr_t pc_value = static_cast<intptr_t>(start + pc_offset);
  if (is_topmost) {
    // Only the pc of the topmost frame needs to be signed since it is
    // authenticated at the end of the DeoptimizationEntry builtin.
    output_frame->SetPc(PointerAuthentication::SignAndCheckPC(
        isolate(), pc_value, frame_writer.frame()->GetTop()));
  } else {
    output_frame->SetPc(pc_value);
  }
  // Update constant pool.
  if (V8_EMBEDDED_CONSTANT_POOL_BOOL) {
    intptr_t constant_pool_value =
        static_cast<intptr_t>(construct_stub->constant_pool());
    output_frame->SetConstantPool(constant_pool_value);
    if (is_topmost) {
      Register constant_pool_reg =
          JavaScriptFrame::constant_pool_pointer_register();
      output_frame->SetRegister(constant_pool_reg.code(), constant_pool_value);
    }
  }
  // Clear the context register. The context might be a de-materialized object
  // and will be materialized by {Runtime_NotifyDeoptimized}. For additional
  // safety we use Tagged<Smi>(0) instead of the potential {arguments_marker}
  // here.
  if (is_topmost) {
    intptr_t context_value = static_cast<intptr_t>(Smi::zero().ptr());
    Register context_reg = JavaScriptFrame::context_register();
    output_frame->SetRegister(context_reg.code(), context_value);
    // Set the continuation for the topmost frame.
    DCHECK_EQ(DeoptimizeKind::kLazy, deopt_kind_);
    Tagged<Code> continuation =
        isolate_->builtins()->code(Builtin::kNotifyDeoptimized);
    output_frame->SetContinuation(
        static_cast<intptr_t>(continuation->instruction_start()));
  }
}
References v8::internal::ArgumentPaddingSlots(), v8::internal::TranslatedFrame::begin(), v8::internal::Isolate::builtins(), CHECK, CHECK_EQ, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::Builtins::code(), v8::internal::JavaScriptFrame::constant_pool_pointer_register(), v8::internal::JavaScriptFrame::context_register(), v8::internal::FrameDescription::Create(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, deopt_kind_, v8::internal::TranslatedFrame::end(), file(), v8::internal::JavaScriptFrame::fp_register(), v8::internal::FrameWriter::frame(), v8::internal::FastConstructStubFrameInfo::frame_size_in_bytes(), v8::internal::FastConstructStubFrameInfo::frame_size_in_bytes_without_fixed(), v8::internal::FrameDescription::GetConstantPool(), v8::internal::FrameDescription::GetFp(), v8::internal::FrameDescription::GetPc(), v8::internal::FrameDescription::GetRegister(), v8::internal::FrameDescription::GetTop(), v8::internal::Isolate::heap(), v8::internal::TranslatedFrame::height(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, input_, isolate(), isolate_, v8::internal::TranslatedFrame::kConstructInvokeStub, v8::internal::TranslatedFrame::kind(), v8::internal::kLazy, v8::internal::kReturnRegister0, output_, output_count_, v8::internal::FastConstructStubFrameInfo::Precise(), v8::internal::PrintF(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::FrameWriter::PushApprovedCallerPc(), v8::internal::FrameWriter::PushCallerConstantPool(), v8::internal::FrameWriter::PushCallerFp(), v8::internal::FrameWriter::PushRawObject(), v8::internal::FrameWriter::PushRawValue(), v8::internal::FrameWriter::PushTranslatedValue(), v8::base::internal::result, v8::internal::FrameDescription::SetConstantPool(), v8::internal::FrameDescription::SetContinuation(), v8::internal::FrameDescription::SetFp(), v8::internal::FrameDescription::SetPc(), v8::internal::FrameDescription::SetRegister(), v8::internal::FrameDescription::SetTop(), v8::internal::PointerAuthentication::SignAndCheckPC(), v8::internal::FrameWriter::top_offset(), trace_scope(), v8::internal::StackFrame::TypeToMarker(), V8_EMBEDDED_CONSTANT_POOL_BOOL, verbose_trace_scope(), verbose_tracing_enabled(), and v8::internal::Smi::zero().
Referenced by DoComputeOutputFrames().
DoComputeInlinedExtraArguments()
void v8::internal::Deoptimizer::DoComputeInlinedExtraArguments (TranslatedFrame * translated_frame, int frame_index) [private]
Definition at line 2111 of file deoptimizer.cc.
                                                        {
  // Inlined arguments frame can not be the topmost, nor the bottom most frame.
  CHECK(frame_index < output_count_ - 1);
  CHECK_GT(frame_index, 0);
  CHECK_NULL(output_[frame_index]);
  // During deoptimization we need push the extra arguments of inlined functions
  // (arguments with index greater than the formal parameter count).
  // For more info, see the design document:
  // https://docs.google.com/document/d/150wGaUREaZI6YWqOQFD5l2mWQXaPbbZjcAIJLOFrzMs
  TranslatedFrame::iterator value_iterator = translated_frame->begin();
  const int argument_count_without_receiver = translated_frame->height() - 1;
  const int formal_parameter_count_without_receiver =
      translated_frame->formal_parameter_count() - 1;
  SBXCHECK_GE(formal_parameter_count_without_receiver, 0);
  const int extra_argument_count =
      argument_count_without_receiver - formal_parameter_count_without_receiver;
  // The number of pushed arguments is the maximum of the actual argument count
  // and the formal parameter count + the receiver.
  const int padding =
      ArgumentPaddingSlots(std::max(argument_count_without_receiver,
                                    formal_parameter_count_without_receiver) +
                           1);
  const int output_frame_size =
      (std::max(0, extra_argument_count) + padding) * kSystemPointerSize;
  if (verbose_tracing_enabled()) {
    PrintF(trace_scope_->file(),
           " translating inlined arguments frame => variable_size=%d\n",
           output_frame_size);
  }
  // Allocate and store the output frame description.
  FrameDescription* output_frame = FrameDescription::Create(
      output_frame_size, JSParameterCount(argument_count_without_receiver),
      isolate());
  // The top address of the frame is computed from the previous frame's top and
  // this frame's size.
  const intptr_t top_address =
      output_[frame_index - 1]->GetTop() - output_frame_size;
  output_frame->SetTop(top_address);
  // This is not a real frame, we take PC and FP values from the parent frame.
  output_frame->SetPc(output_[frame_index - 1]->GetPc());
  output_frame->SetFp(output_[frame_index - 1]->GetFp());
  output_[frame_index] = output_frame;
  FrameWriter frame_writer(this, output_frame, verbose_trace_scope());
  ReadOnlyRoots roots(isolate());
  for (int i = 0; i < padding; ++i) {
    frame_writer.PushRawObject(roots.the_hole_value(), "padding\n");
  }
  if (extra_argument_count > 0) {
    // The receiver and arguments with index below the formal parameter
    // count are in the fake adaptor frame, because they are used to create the
    // arguments object. We should however not push them, since the interpreter
    // frame will do that.
    value_iterator++; // Skip function.
    value_iterator++; // Skip receiver.
    for (int i = 0; i < formal_parameter_count_without_receiver; i++)
      value_iterator++;
    frame_writer.PushStackJSArguments(value_iterator, extra_argument_count);
  }
}
References v8::internal::ArgumentPaddingSlots(), v8::internal::TranslatedFrame::begin(), CHECK, CHECK_GT, CHECK_NULL, v8::internal::FrameDescription::Create(), v8::internal::CodeTracer::Scope::file(), v8::internal::TranslatedFrame::formal_parameter_count(), v8::internal::FrameDescription::GetTop(), v8::internal::TranslatedFrame::height(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate(), v8::internal::JSParameterCount(), v8::internal::kSystemPointerSize, output_, output_count_, v8::internal::PrintF(), v8::internal::FrameWriter::PushRawObject(), v8::internal::FrameWriter::PushStackJSArguments(), SBXCHECK_GE, v8::internal::FrameDescription::SetFp(), v8::internal::FrameDescription::SetPc(), v8::internal::FrameDescription::SetTop(), trace_scope_, verbose_trace_scope(), and verbose_tracing_enabled().
Referenced by DoComputeOutputFrames().
DoComputeOutputFrames()
void v8::internal::Deoptimizer::DoComputeOutputFrames () [private]
Definition at line 1499 of file deoptimizer.cc.
                                        {
  // When we call this function, the return address of the previous frame has
  // been removed from the stack by the DeoptimizationEntry builtin, so the
  // stack is not iterable by the StackFrameIteratorForProfiler.
#if V8_TARGET_ARCH_STORES_RETURN_ADDRESS_ON_STACK
  DCHECK_EQ(0, isolate()->isolate_data()->stack_is_iterable());
#endif
  base::ElapsedTimer timer;
#if V8_ENABLE_WEBASSEMBLY
  if (v8_flags.wasm_deopt && function_.is_null()) {
    trap_handler::ClearThreadInWasm();
    DoComputeOutputFramesWasmImpl();
    trap_handler::SetThreadInWasm();
    return;
  }
#endif
  // Determine basic deoptimization information. The optimized frame is
  // described by the input data.
  Tagged<DeoptimizationData> input_data =
      Cast<DeoptimizationData>(compiled_code_->deoptimization_data());
  {
    // Read caller's PC, caller's FP and caller's constant pool values
    // from input frame. Compute caller's frame top address.
    Register fp_reg = JavaScriptFrame::fp_register();
    stack_fp_ = input_->GetRegister(fp_reg.code());
    caller_frame_top_ = stack_fp_ + ComputeInputFrameAboveFpFixedSize();
    Address fp_address = input_->GetFramePointerAddress();
    caller_fp_ = Memory<intptr_t>(fp_address);
    caller_pc_ =
        Memory<intptr_t>(fp_address + CommonFrameConstants::kCallerPCOffset);
    actual_argument_count_ = static_cast<int>(
        Memory<intptr_t>(fp_address + StandardFrameConstants::kArgCOffset));
    if (V8_EMBEDDED_CONSTANT_POOL_BOOL) {
      caller_constant_pool_ = Memory<intptr_t>(
          fp_address + CommonFrameConstants::kConstantPoolOffset);
    }
  }
  StackGuard* const stack_guard = isolate()->stack_guard();
  CHECK_GT(static_cast<uintptr_t>(caller_frame_top_),
           stack_guard->real_jslimit());
  BytecodeOffset bytecode_offset =
      input_data->GetBytecodeOffsetOrBuiltinContinuationId(deopt_exit_index_);
  auto translations = input_data->FrameTranslation();
  unsigned translation_index =
      input_data->TranslationIndex(deopt_exit_index_).value();
  if (tracing_enabled()) {
    timer.Start();
    TraceDeoptBegin(input_data->OptimizationId().value(), bytecode_offset);
  }
  FILE* trace_file =
      verbose_tracing_enabled() ? trace_scope()->file() : nullptr;
  DeoptimizationFrameTranslation::Iterator state_iterator(translations,
                                                          translation_index);
  DeoptimizationLiteralProvider literals(input_data->LiteralArray());
  translated_state_.Init(isolate_, input_->GetFramePointerAddress(), stack_fp_,
                         &state_iterator, input_data->ProtectedLiteralArray(),
                         literals, input_->GetRegisterValues(), trace_file,
                         compiled_code_->parameter_count_without_receiver(),
                         actual_argument_count_ - kJSArgcReceiverSlots);
  bytecode_offset_in_outermost_frame_ =
      translated_state_.frames()[0].bytecode_offset();
  // Do the input frame to output frame(s) translation.
  size_t count = translated_state_.frames().size();
  if (is_restart_frame()) {
    // If the debugger requested to restart a particular frame, only materialize
    // up to that frame.
    count = restart_frame_index_ + 1;
  } else if (deoptimizing_throw_) {
    // If we are supposed to go to the catch handler, find the catching frame
    // for the catch and make sure we only deoptimize up to that frame.
    size_t catch_handler_frame_index = count;
    for (size_t i = count; i-- > 0;) {
      catch_handler_pc_offset_ = LookupCatchHandler(
          isolate(), &(translated_state_.frames()[i]), &catch_handler_data_);
      if (catch_handler_pc_offset_ >= 0) {
        catch_handler_frame_index = i;
        break;
      }
    }
    CHECK_LT(catch_handler_frame_index, count);
    count = catch_handler_frame_index + 1;
  }
  DCHECK_NULL(output_);
  output_ = new FrameDescription* [count] {};
  output_count_ = static_cast<int>(count);
  // Translate each output frame.
  int frame_index = 0;
  size_t total_output_frame_size = 0;
  for (size_t i = 0; i < count; ++i, ++frame_index) {
    TranslatedFrame* translated_frame = &(translated_state_.frames()[i]);
    const bool handle_exception = deoptimizing_throw_ && i == count - 1;
    switch (translated_frame->kind()) {
      case TranslatedFrame::kUnoptimizedFunction:
        DoComputeUnoptimizedFrame(translated_frame, frame_index,
                                  handle_exception);
        break;
      case TranslatedFrame::kInlinedExtraArguments:
        DoComputeInlinedExtraArguments(translated_frame, frame_index);
        break;
      case TranslatedFrame::kConstructCreateStub:
        DoComputeConstructCreateStubFrame(translated_frame, frame_index);
        break;
      case TranslatedFrame::kConstructInvokeStub:
        DoComputeConstructInvokeStubFrame(translated_frame, frame_index);
        break;
      case TranslatedFrame::kBuiltinContinuation:
#if V8_ENABLE_WEBASSEMBLY
      case TranslatedFrame::kJSToWasmBuiltinContinuation:
#endif // V8_ENABLE_WEBASSEMBLY
        DoComputeBuiltinContinuation(translated_frame, frame_index,
                                     BuiltinContinuationMode::STUB);
        break;
      case TranslatedFrame::kJavaScriptBuiltinContinuation:
        DoComputeBuiltinContinuation(translated_frame, frame_index,
                                     BuiltinContinuationMode::JAVASCRIPT);
        break;
      case TranslatedFrame::kJavaScriptBuiltinContinuationWithCatch:
        DoComputeBuiltinContinuation(
            translated_frame, frame_index,
            handle_exception
                ? BuiltinContinuationMode::JAVASCRIPT_HANDLE_EXCEPTION
                : BuiltinContinuationMode::JAVASCRIPT_WITH_CATCH);
        break;
#if V8_ENABLE_WEBASSEMBLY
      case TranslatedFrame::kWasmInlinedIntoJS:
        FATAL("inlined wasm frames may not appear in JS deopts");
      case TranslatedFrame::kLiftoffFunction:
        FATAL("wasm liftoff frames may not appear in JS deopts");
#endif
      case TranslatedFrame::kInvalid:
        FATAL("invalid frame");
    }
    total_output_frame_size += output_[frame_index]->GetFrameSize();
  }
  FrameDescription* topmost = output_[count - 1];
  topmost->GetRegisterValues()->SetRegister(kRootRegister.code(),
                                            isolate()->isolate_root());
#ifdef V8_COMPRESS_POINTERS
  topmost->GetRegisterValues()->SetRegister(kPtrComprCageBaseRegister.code(),
                                            isolate()->cage_base());
#endif
#ifdef V8_ENABLE_CET_SHADOW_STACK
  if (v8_flags.cet_compatible) {
    CHECK_EQ(shadow_stack_count_, 0);
    shadow_stack_ = new intptr_t[count + 1];
    // We should jump to the continuation through AdaptShadowStack to avoid
    // security exception.
    // Clear the continuation so that DeoptimizationEntry does not push the
    // address onto the stack, and push it to the shadow stack instead.
    if (output_[count - 1]->GetContinuation()) {
      shadow_stack_[shadow_stack_count_++] =
          output_[count - 1]->GetContinuation();
      output_[count - 1]->SetContinuation(0);
    }
    // Add topmost frame's pc to the shadow stack.
    shadow_stack_[shadow_stack_count_++] =
        output_[count - 1]->GetPc() -
        Deoptimizer::kAdaptShadowStackOffsetToSubtract;
    // Add return addresses to the shadow stack, except for the bottommost.
    // The bottommost frame's return address already exists in the shadow stack.
    for (int i = static_cast<int>(count) - 1; i > 0; i--) {
      if (!output_[i]->HasCallerPc()) continue;
      shadow_stack_[shadow_stack_count_++] =
          output_[i]->GetCallerPc() -
          Deoptimizer::kAdaptShadowStackOffsetToSubtract;
    }
  }
#endif // V8_ENABLE_CET_SHADOW_STACK
  // Don't reset the tiering state for OSR code since we might reuse OSR code
  // after deopt, and we still want to tier up to non-OSR code even if OSR code
  // deoptimized.
  bool osr_early_exit = Deoptimizer::GetDeoptInfo().deopt_reason ==
                        DeoptimizeReason::kOSREarlyExit;
  // TODO(saelo): We have to use full pointer comparisons here while not all
  // Code objects have been migrated into trusted space.
  static_assert(!kAllCodeObjectsLiveInTrustedSpace);
  if (IsJSFunction(function_) &&
      (compiled_code_->osr_offset().IsNone()
           ? function_->code(isolate()).SafeEquals(compiled_code_)
           : (!osr_early_exit &&
              DeoptExitIsInsideOsrLoop(
                  isolate(), function_, bytecode_offset_in_outermost_frame_,
                  compiled_code_->osr_offset(), compiled_code_->kind())))) {
    if (v8_flags.profile_guided_optimization &&
        function_->shared()->cached_tiering_decision() !=
            CachedTieringDecision::kDelayMaglev) {
      if (DeoptimizedMaglevvedCodeEarly(isolate(), function_, compiled_code_)) {
        function_->shared()->set_cached_tiering_decision(
            CachedTieringDecision::kDelayMaglev);
      } else {
        function_->shared()->set_cached_tiering_decision(
            CachedTieringDecision::kNormal);
      }
    }
    function_->ResetTieringRequests();
    // This allows us to quickly re-spawn a new compilation request even if
    // there is already one running. In particular it helps to squeeze in a
    // maglev compilation when there is a long running turbofan one that was
    // started right before the deopt.
    function_->SetTieringInProgress(isolate_, false);
    function_->SetInterruptBudget(isolate_, BudgetModification::kReset,
                                  CodeKind::INTERPRETED_FUNCTION);
    function_->feedback_vector()->set_was_once_deoptimized();
  }
  // Print some helpful diagnostic information.
  if (verbose_tracing_enabled()) {
    TraceDeoptEnd(timer.Elapsed().InMillisecondsF());
  }
  isolate()->counters()->deopts()->Increment();
  // The following invariant is fairly tricky to guarantee, since the size of
  // an optimized frame and its deoptimized counterparts usually differs. We
  // thus need to consider the case in which deoptimized frames are larger than
  // the optimized frame in stack checks in optimized code. We do this by
  // applying an offset to stack checks (see kArchStackPointerGreaterThan in the
  // code generator).
  // Note that we explicitly allow deopts to exceed the limit by a certain
  // number of slack bytes.
  CHECK_GT(
      static_cast<uintptr_t>(caller_frame_top_) - total_output_frame_size,
      stack_guard->real_jslimit() - kStackLimitSlackForDeoptimizationInBytes);
}
References actual_argument_count_, bytecode_offset_in_outermost_frame_, caller_constant_pool_, caller_fp_, caller_frame_top_, caller_pc_, catch_handler_data_, catch_handler_pc_offset_, CHECK_EQ, CHECK_GT, CHECK_LT, v8::internal::trap_handler::ClearThreadInWasm(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), compiled_code_, ComputeInputFrameAboveFpFixedSize(), v8::internal::Isolate::counters(), DCHECK_EQ, DCHECK_NULL, deopt_exit_index_, v8::internal::Deoptimizer::DeoptInfo::deopt_reason, DeoptExitIsInsideOsrLoop(), v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizedMaglevvedCodeEarly(), deoptimizing_throw_, DoComputeBuiltinContinuation(), DoComputeConstructCreateStubFrame(), DoComputeConstructInvokeStubFrame(), DoComputeInlinedExtraArguments(), DoComputeUnoptimizedFrame(), v8::base::ElapsedTimer::Elapsed(), FATAL, v8::internal::CodeTracer::Scope::file(), v8::internal::JavaScriptFrame::fp_register(), v8::internal::TranslatedState::frames(), function_, v8::internal::FrameDescription::GetCallerPc(), v8::internal::FrameDescription::GetContinuation(), GetDeoptInfo(), v8::internal::FrameDescription::GetFramePointerAddress(), v8::internal::FrameDescription::GetFrameSize(), v8::internal::FrameDescription::GetPc(), v8::internal::FrameDescription::GetRegister(), v8::internal::FrameDescription::GetRegisterValues(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::TranslatedState::Init(), v8::base::TimeDelta::InMillisecondsF(), input_, is_restart_frame(), isolate(), isolate_, v8::internal::JAVASCRIPT, v8::internal::JAVASCRIPT_HANDLE_EXCEPTION, v8::internal::JAVASCRIPT_WITH_CATCH, kAdaptShadowStackOffsetToSubtract, v8::internal::kAllCodeObjectsLiveInTrustedSpace, v8::internal::StandardFrameConstants::kArgCOffset, v8::internal::TranslatedFrame::kBuiltinContinuation, v8::internal::CommonFrameConstants::kCallerPCOffset, v8::internal::CommonFrameConstants::kConstantPoolOffset, v8::internal::TranslatedFrame::kConstructCreateStub, v8::internal::TranslatedFrame::kConstructInvokeStub, v8::internal::kDelayMaglev, v8::internal::TranslatedFrame::kind(), v8::internal::TranslatedFrame::kInlinedExtraArguments, v8::internal::TranslatedFrame::kInvalid, v8::internal::TranslatedFrame::kJavaScriptBuiltinContinuation, v8::internal::TranslatedFrame::kJavaScriptBuiltinContinuationWithCatch, v8::internal::kJSArgcReceiverSlots, v8::internal::kNormal, v8::internal::kPtrComprCageBaseRegister, v8::internal::kReset, v8::internal::kRootRegister, v8::internal::kStackLimitSlackForDeoptimizationInBytes, v8::internal::TranslatedFrame::kUnoptimizedFunction, v8::internal::anonymous_namespace{deoptimizer.cc}::LookupCatchHandler(), output_, output_count_, v8::internal::StackGuard::real_jslimit(), restart_frame_index_, v8::internal::FrameDescription::SetContinuation(), v8::internal::RegisterValues::SetRegister(), v8::internal::trap_handler::SetThreadInWasm(), stack_fp_, v8::internal::Isolate::stack_guard(), v8::base::ElapsedTimer::Start(), v8::internal::STUB, trace_scope(), TraceDeoptBegin(), TraceDeoptEnd(), tracing_enabled(), translated_state_, V8_EMBEDDED_CONSTANT_POOL_BOOL, v8::internal::v8_flags, and verbose_tracing_enabled().
Referenced by ComputeOutputFrames().
DoComputeUnoptimizedFrame()
void v8::internal::Deoptimizer::DoComputeUnoptimizedFrame (TranslatedFrame * translated_frame, int frame_index, bool goto_catch_handler) [private]
Definition at line 1802 of file deoptimizer.cc.
                                                                     {
  Tagged<BytecodeArray> bytecode_array = translated_frame->raw_bytecode_array();
  TranslatedFrame::iterator value_iterator = translated_frame->begin();
  const bool is_bottommost = (0 == frame_index);
  const bool is_topmost = (output_count_ - 1 == frame_index);
  const int real_bytecode_offset = translated_frame->bytecode_offset().ToInt();
  const int bytecode_offset =
      goto_catch_handler ? catch_handler_pc_offset_ : real_bytecode_offset;
  const int parameters_count = bytecode_array->parameter_count();
  // If this is the bottom most frame or the previous frame was the inlined
  // extra arguments frame, then we already have extra arguments in the stack
  // (including any extra padding). Therefore we should not try to add any
  // padding.
  bool should_pad_arguments =
      !is_bottommost && (translated_state_.frames()[frame_index - 1]).kind() !=
                            TranslatedFrame::kInlinedExtraArguments;
  const int locals_count = translated_frame->height();
  UnoptimizedFrameInfo frame_info = UnoptimizedFrameInfo::Precise(
      parameters_count, locals_count, is_topmost, should_pad_arguments);
  const uint32_t output_frame_size = frame_info.frame_size_in_bytes();
  TranslatedFrame::iterator function_iterator = value_iterator++;
  std::optional<Tagged<DebugInfo>> debug_info =
      translated_frame->raw_shared_info()->TryGetDebugInfo(isolate());
  if (debug_info.has_value() && debug_info.value()->HasBreakInfo()) {
    // TODO(leszeks): Validate this bytecode.
    bytecode_array = debug_info.value()->DebugBytecodeArray(isolate());
  }
  // Allocate and store the output frame description.
  FrameDescription* output_frame =
      FrameDescription::Create(output_frame_size, parameters_count, isolate());
  FrameWriter frame_writer(this, output_frame, verbose_trace_scope());
  CHECK(frame_index >= 0 && frame_index < output_count_);
  CHECK_NULL(output_[frame_index]);
  output_[frame_index] = output_frame;
  // Compute this frame's PC and state.
  // For interpreted frames, the PC will be a special builtin that
  // continues the bytecode dispatch. Note that non-topmost and lazy-style
  // bailout handlers also advance the bytecode offset before dispatch, hence
  // simulating what normal handlers do upon completion of the operation.
  // For baseline frames, the PC will be a builtin to convert the interpreter
  // frame to a baseline frame before continuing execution of baseline code.
  // We can't directly continue into baseline code, because of CFI.
  Builtins* builtins = isolate_->builtins();
  const bool advance_bc =
      (!is_topmost || (deopt_kind_ == DeoptimizeKind::kLazy)) &&
      !goto_catch_handler;
  const bool restart_frame = goto_catch_handler && is_restart_frame();
  Tagged<Code> dispatch_builtin =
      builtins->code(DispatchBuiltinFor(advance_bc, restart_frame));
  if (verbose_tracing_enabled()) {
    PrintF(trace_scope()->file(), " translating interpreted frame ");
    std::unique_ptr<char[]> name =
        translated_frame->raw_shared_info()->DebugNameCStr();
    PrintF(trace_scope()->file(), "%s", name.get());
    PrintF(trace_scope()->file(), " => bytecode_offset=%d, ",
           real_bytecode_offset);
    PrintF(trace_scope()->file(), "variable_frame_size=%d, frame_size=%d%s\n",
           frame_info.frame_size_in_bytes_without_fixed(), output_frame_size,
           goto_catch_handler ? " (throw)" : "");
  }
  // The top address of the frame is computed from the previous frame's top and
  // this frame's size.
  const intptr_t top_address =
      is_bottommost ? caller_frame_top_ - output_frame_size
                    : output_[frame_index - 1]->GetTop() - output_frame_size;
  output_frame->SetTop(top_address);
  // Compute the incoming parameter translation.
  ReadOnlyRoots roots(isolate());
  if (should_pad_arguments) {
    for (int i = 0; i < ArgumentPaddingSlots(parameters_count); ++i) {
      frame_writer.PushRawObject(roots.the_hole_value(), "padding\n");
    }
  }
  if (verbose_tracing_enabled() && is_bottommost &&
      actual_argument_count_ > parameters_count) {
    PrintF(trace_scope_->file(),
           " -- %d extra argument(s) already in the stack --\n",
           actual_argument_count_ - parameters_count);
  }
  frame_writer.PushStackJSArguments(value_iterator, parameters_count);
  DCHECK_EQ(output_frame->GetLastArgumentSlotOffset(should_pad_arguments),
            frame_writer.top_offset());
  if (verbose_tracing_enabled()) {
    PrintF(trace_scope()->file(), " -------------------------\n");
  }
  // There are no translation commands for the caller's pc and fp, the
  // context, the function and the bytecode offset. Synthesize
  // their values and set them up
  // explicitly.
  //
  // The caller's pc for the bottommost output frame is the same as in the
  // input frame. For all subsequent output frames, it can be read from the
  // previous one. This frame's pc can be computed from the non-optimized
  // function code and bytecode offset of the bailout.
  if (is_bottommost) {
    frame_writer.PushBottommostCallerPc(caller_pc_);
  } else {
    frame_writer.PushApprovedCallerPc(output_[frame_index - 1]->GetPc());
  }
  // The caller's frame pointer for the bottommost output frame is the same
  // as in the input frame. For all subsequent output frames, it can be
  // read from the previous one. Also compute and set this frame's frame
  // pointer.
  const intptr_t caller_fp =
      is_bottommost ? caller_fp_ : output_[frame_index - 1]->GetFp();
  frame_writer.PushCallerFp(caller_fp);
  const intptr_t fp_value = top_address + frame_writer.top_offset();
  output_frame->SetFp(fp_value);
  if (is_topmost) {
    Register fp_reg = UnoptimizedJSFrame::fp_register();
    output_frame->SetRegister(fp_reg.code(), fp_value);
  }
  if (V8_EMBEDDED_CONSTANT_POOL_BOOL) {
    // For the bottommost output frame the constant pool pointer can be gotten
    // from the input frame. For subsequent output frames, it can be read from
    // the previous frame.
    const intptr_t caller_cp =
        is_bottommost ? caller_constant_pool_
                      : output_[frame_index - 1]->GetConstantPool();
    frame_writer.PushCallerConstantPool(caller_cp);
  }
  // For the bottommost output frame the context can be gotten from the input
  // frame. For all subsequent output frames it can be gotten from the function
  // so long as we don't inline functions that need local contexts.
  // When deoptimizing into a catch block, we need to take the context
  // from a register that was specified in the handler table.
  TranslatedFrame::iterator context_pos = value_iterator++;
  if (goto_catch_handler) {
    // Skip to the translated value of the register specified
    // in the handler table.
    for (int i = 0; i < catch_handler_data_ + 1; ++i) {
      context_pos++;
    }
  }
  // Read the context from the translations.
  frame_writer.PushTranslatedValue(context_pos, "context");
  // The function was mentioned explicitly in the BEGIN_FRAME.
  frame_writer.PushTranslatedValue(function_iterator, "function");
  // Actual argument count.
  int argc;
  if (is_bottommost) {
    argc = actual_argument_count_;
  } else {
    TranslatedFrame::Kind previous_frame_kind =
        (translated_state_.frames()[frame_index - 1]).kind();
    argc = previous_frame_kind == TranslatedFrame::kInlinedExtraArguments
               ? output_[frame_index - 1]->parameter_count()
               : parameters_count;
  }
  frame_writer.PushRawValue(argc, "actual argument count\n");
  // Set the bytecode array pointer.
  frame_writer.PushRawObject(bytecode_array, "bytecode array\n");
  // The bytecode offset was mentioned explicitly in the BEGIN_FRAME.
  const int raw_bytecode_offset =
      BytecodeArray::kHeaderSize - kHeapObjectTag + bytecode_offset;
  Tagged<Smi> smi_bytecode_offset = Smi::FromInt(raw_bytecode_offset);
  frame_writer.PushRawObject(smi_bytecode_offset, "bytecode offset\n");
  // We need to materialize the closure before getting the feedback vector.
  frame_writer.PushFeedbackVectorForMaterialization(function_iterator);
  if (verbose_tracing_enabled()) {
    PrintF(trace_scope()->file(), " -------------------------\n");
  }
  // Translate the rest of the interpreter registers in the frame.
  // The return_value_offset is counted from the top. Here, we compute the
  // register index (counted from the start).
  const int return_value_first_reg =
      locals_count - translated_frame->return_value_offset();
  const int return_value_count = translated_frame->return_value_count();
  for (int i = 0; i < locals_count; ++i, ++value_iterator) {
    // Ensure we write the return value if we have one and we are returning
    // normally to a lazy deopt point.
    if (is_topmost && !goto_catch_handler &&
        deopt_kind_ == DeoptimizeKind::kLazy && i >= return_value_first_reg &&
        i < return_value_first_reg + return_value_count) {
      const int return_index = i - return_value_first_reg;
      if (return_index == 0) {
        frame_writer.PushRawValue(input_->GetRegister(kReturnRegister0.code()),
                                  "return value 0\n");
        // We do not handle the situation when one return value should go into
        // the accumulator and another one into an ordinary register. Since
        // the interpreter should never create such situation, just assert
        // this does not happen.
        CHECK_LE(return_value_first_reg + return_value_count, locals_count);
      } else {
        CHECK_EQ(return_index, 1);
        frame_writer.PushRawValue(input_->GetRegister(kReturnRegister1.code()),
                                  "return value 1\n");
      }
    } else {
      // This is not return value, just write the value from the translations.
      frame_writer.PushTranslatedValue(value_iterator, "stack parameter");
    }
  }
  uint32_t register_slots_written = static_cast<uint32_t>(locals_count);
  DCHECK_LE(register_slots_written, frame_info.register_stack_slot_count());
  // Some architectures must pad the stack frame with extra stack slots
  // to ensure the stack frame is aligned. Do this now.
  while (register_slots_written < frame_info.register_stack_slot_count()) {
    register_slots_written++;
    frame_writer.PushRawObject(roots.the_hole_value(), "padding\n");
  }
  // Translate the accumulator register (depending on frame position).
  if (is_topmost) {
    for (int i = 0; i < ArgumentPaddingSlots(1); ++i) {
      frame_writer.PushRawObject(roots.the_hole_value(), "padding\n");
    }
    // For topmost frame, put the accumulator on the stack. The
    // {NotifyDeoptimized} builtin pops it off the topmost frame (possibly
    // after materialization).
    if (goto_catch_handler) {
      // If we are lazy deopting to a catch handler, we set the accumulator to
      // the exception (which lives in the result register).
      intptr_t accumulator_value =
          input_->GetRegister(kInterpreterAccumulatorRegister.code());
      frame_writer.PushRawObject(Tagged<Object>(accumulator_value),
                                 "accumulator\n");
    } else {
      // If we are lazily deoptimizing make sure we store the deopt
      // return value into the appropriate slot.
      if (deopt_kind_ == DeoptimizeKind::kLazy &&
          translated_frame->return_value_offset() == 0 &&
          translated_frame->return_value_count() > 0) {
        CHECK_EQ(translated_frame->return_value_count(), 1);
        frame_writer.PushRawValue(input_->GetRegister(kReturnRegister0.code()),
                                  "return value 0\n");
      } else {
        frame_writer.PushTranslatedValue(value_iterator, "accumulator");
      }
    }
    ++value_iterator; // Move over the accumulator.
  } else {
    // For non-topmost frames, skip the accumulator translation. For those
    // frames, the return value from the callee will become the accumulator.
    ++value_iterator;
  }
  CHECK_EQ(translated_frame->end(), value_iterator);
  CHECK_EQ(0u, frame_writer.top_offset());
  const intptr_t pc =
      static_cast<intptr_t>(dispatch_builtin->instruction_start()) +
      isolate()->heap()->deopt_pc_offset_after_adapt_shadow_stack().value();
  if (is_topmost) {
    // Only the pc of the topmost frame needs to be signed since it is
    // authenticated at the end of the DeoptimizationEntry builtin.
    const intptr_t top_most_pc = PointerAuthentication::SignAndCheckPC(
        isolate(), pc, frame_writer.frame()->GetTop());
    output_frame->SetPc(top_most_pc);
  } else {
    output_frame->SetPc(pc);
  }
  // Update constant pool.
  if (V8_EMBEDDED_CONSTANT_POOL_BOOL) {
    intptr_t constant_pool_value =
        static_cast<intptr_t>(dispatch_builtin->constant_pool());
    output_frame->SetConstantPool(constant_pool_value);
    if (is_topmost) {
      Register constant_pool_reg =
          UnoptimizedJSFrame::constant_pool_pointer_register();
      output_frame->SetRegister(constant_pool_reg.code(), constant_pool_value);
    }
  }
  // Clear the context register. The context might be a de-materialized object
  // and will be materialized by {Runtime_NotifyDeoptimized}. For additional
  // safety we use Tagged<Smi>(0) instead of the potential {arguments_marker}
  // here.
  if (is_topmost) {
    intptr_t context_value = static_cast<intptr_t>(Smi::zero().ptr());
    Register context_reg = JavaScriptFrame::context_register();
    output_frame->SetRegister(context_reg.code(), context_value);
    // Set the continuation for the topmost frame.
    Tagged<Code> continuation = builtins->code(Builtin::kNotifyDeoptimized);
    output_frame->SetContinuation(
        static_cast<intptr_t>(continuation->instruction_start()));
  }
}
References actual_argument_count_, v8::internal::ArgumentPaddingSlots(), v8::internal::TranslatedFrame::begin(), v8::internal::Isolate::builtins(), v8::internal::TranslatedFrame::bytecode_offset(), caller_constant_pool_, caller_fp_, caller_frame_top_, caller_pc_, catch_handler_data_, catch_handler_pc_offset_, CHECK, CHECK_EQ, CHECK_LE, CHECK_NULL, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::Builtins::code(), v8::internal::JavaScriptFrame::constant_pool_pointer_register(), v8::internal::JavaScriptFrame::context_register(), v8::internal::FrameDescription::Create(), DCHECK_EQ, DCHECK_LE, deopt_kind_, v8::internal::anonymous_namespace{deoptimizer.cc}::DispatchBuiltinFor(), v8::internal::TranslatedFrame::end(), v8::internal::CodeTracer::Scope::file(), file(), v8::internal::JavaScriptFrame::fp_register(), v8::internal::FrameWriter::frame(), v8::internal::UnoptimizedFrameInfo::frame_size_in_bytes(), v8::internal::UnoptimizedFrameInfo::frame_size_in_bytes_without_fixed(), v8::internal::TranslatedState::frames(), v8::internal::Smi::FromInt(), v8::internal::FrameDescription::GetConstantPool(), v8::internal::FrameDescription::GetFp(), v8::internal::FrameDescription::GetLastArgumentSlotOffset(), v8::internal::FrameDescription::GetRegister(), v8::internal::FrameDescription::GetTop(), v8::internal::Isolate::heap(), v8::internal::TranslatedFrame::height(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, input_, is_restart_frame(), isolate(), isolate_, v8::internal::ExposedTrustedObject::kHeaderSize, v8::internal::kHeapObjectTag, v8::internal::TranslatedFrame::kInlinedExtraArguments, v8::internal::kInterpreterAccumulatorRegister, v8::internal::kLazy, v8::internal::kReturnRegister0, v8::internal::kReturnRegister1, v8::internal::name, output_, output_count_, v8::internal::FrameDescription::parameter_count(), v8::internal::UnoptimizedFrameInfo::Precise(), v8::internal::PrintF(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::FrameWriter::PushApprovedCallerPc(), v8::internal::FrameWriter::PushBottommostCallerPc(), v8::internal::FrameWriter::PushCallerConstantPool(), v8::internal::FrameWriter::PushCallerFp(), v8::internal::FrameWriter::PushFeedbackVectorForMaterialization(), v8::internal::FrameWriter::PushRawObject(), v8::internal::FrameWriter::PushRawValue(), v8::internal::FrameWriter::PushStackJSArguments(), v8::internal::FrameWriter::PushTranslatedValue(), v8::internal::TranslatedFrame::raw_bytecode_array(), v8::internal::TranslatedFrame::raw_shared_info(), v8::internal::UnoptimizedFrameInfo::register_stack_slot_count(), v8::internal::TranslatedFrame::return_value_count(), v8::internal::TranslatedFrame::return_value_offset(), v8::internal::FrameDescription::SetConstantPool(), v8::internal::FrameDescription::SetContinuation(), v8::internal::FrameDescription::SetFp(), v8::internal::FrameDescription::SetPc(), v8::internal::FrameDescription::SetRegister(), v8::internal::FrameDescription::SetTop(), v8::internal::PointerAuthentication::SignAndCheckPC(), v8::internal::BytecodeOffset::ToInt(), v8::internal::FrameWriter::top_offset(), trace_scope(), trace_scope_, translated_state_, V8_EMBEDDED_CONSTANT_POOL_BOOL, verbose_trace_scope(), verbose_tracing_enabled(), and v8::internal::Smi::zero().
Referenced by DoComputeOutputFrames().
EnsureValidReturnAddress()
Address v8::internal::Deoptimizer::EnsureValidReturnAddress (Isolate * isolate, Address address) [static]
Definition at line 547 of file deoptimizer.cc.
                                                               {
  // TODO(42201233): We should make sure everything here we use for validation
  // (builtins array, code object, and offset values) are not writable.
  Builtins* builtins = isolate->builtins();
  Heap* heap = isolate->heap();
#define CHECK_BUILTIN(builtin, offset) \
  if (builtins->code(builtin)->instruction_start() + heap->offset().value() - \
          Deoptimizer::kAdaptShadowStackOffsetToSubtract == \
      address) \
    return address;
  DEOPTIMIZATION_HELPER_BUILTINS(CHECK_BUILTIN)
#undef CHECK_BUILTIN
  // NotifyDeoptimized is used for continuation.
  if (builtins->code(Builtin::kNotifyDeoptimized)->instruction_start() ==
      address)
    return address;
#if V8_ENABLE_WEBASSEMBLY
  if (v8_flags.wasm_deopt &&
      wasm::GetWasmCodeManager()->LookupCode(isolate, address) != nullptr) {
    // TODO(42204618): This does not check for the PC being a valid "deopt
    // point" but could be any arbitrary address inside a wasm code object
    // (including pointing into the middle of an instruction).
    return address;
  }
#endif
  CHECK_WITH_MSG(false, "Not allowed return address");
}
References v8::internal::Isolate::builtins(), CHECK_BUILTIN, CHECK_WITH_MSG, v8::internal::Builtins::code(), DEOPTIMIZATION_HELPER_BUILTINS, v8::internal::wasm::GetWasmCodeManager(), v8::internal::Isolate::heap(), v8::internal::wasm::WasmCodeManager::LookupCode(), and v8::internal::v8_flags.
Referenced by v8::internal::PointerAuthentication::SignAndCheckPC().
function()
DirectHandle< JSFunction > v8::internal::Deoptimizer::function () const
Definition at line 747 of file deoptimizer.cc.
                                                     {
  return DirectHandle<JSFunction>(function_, isolate());
}
References function_, and isolate().
Referenced by DeoptExitIsInsideOsrLoop(), Deoptimizer(), and v8::internal::RUNTIME_FUNCTION().
GetDeoptimizationEntry()
Builtin v8::internal::Deoptimizer::GetDeoptimizationEntry (DeoptimizeKind kind) [static]
Definition at line 786 of file deoptimizer.cc.
                                                               {
  switch (kind) {
    case DeoptimizeKind::kEager:
      return Builtin::kDeoptimizationEntry_Eager;
    case DeoptimizeKind::kLazyAfterFastCall:
      return Builtin::kDeoptimizationEntry_LazyAfterFastCall;
    case DeoptimizeKind::kLazy:
      return Builtin::kDeoptimizationEntry_Lazy;
  }
}
References v8::internal::kEager, v8::internal::kLazy, and v8::internal::kLazyAfterFastCall.
Referenced by v8::internal::compiler::CodeGenerator::AssembleDeoptimizerCall().
GetDeoptInfo() [1/2]
DeoptInfo v8::internal::Deoptimizer::GetDeoptInfo () const [inline]
Definition at line 65 of file deoptimizer.h.
                                 {
    return Deoptimizer::GetDeoptInfo(compiled_code_, from_);
  }
References compiled_code_, and from_.
Referenced by v8::internal::V8FileLogger::CodeDeoptEvent(), v8::internal::ProfilerListener::CodeDeoptEvent(), DoComputeOutputFrames(), ProcessDeoptReason(), and TraceDeoptBegin().
GetDeoptInfo() [2/2]
Deoptimizer::DeoptInfo v8::internal::Deoptimizer::GetDeoptInfo (Tagged< Code > code, Address from) [static]
Definition at line 3057 of file deoptimizer.cc.
                                                             {
  CHECK(code->instruction_start() <= pc && pc <= code->instruction_end());
  SourcePosition last_position = SourcePosition::Unknown();
  DeoptimizeReason last_reason = DeoptimizeReason::kUnknown;
  uint32_t last_node_id = 0;
  int last_deopt_id = kNoDeoptimizationId;
  int mask = RelocInfo::ModeMask(RelocInfo::DEOPT_REASON) |
             RelocInfo::ModeMask(RelocInfo::DEOPT_ID) |
             RelocInfo::ModeMask(RelocInfo::DEOPT_SCRIPT_OFFSET) |
             RelocInfo::ModeMask(RelocInfo::DEOPT_INLINING_ID) |
             RelocInfo::ModeMask(RelocInfo::DEOPT_NODE_ID);
  for (RelocIterator it(code, mask); !it.done(); it.next()) {
    RelocInfo* info = it.rinfo();
    if (info->pc() >= pc) break;
    if (info->rmode() == RelocInfo::DEOPT_SCRIPT_OFFSET) {
      int script_offset = static_cast<int>(info->data());
      it.next();
      DCHECK(it.rinfo()->rmode() == RelocInfo::DEOPT_INLINING_ID);
      int inlining_id = static_cast<int>(it.rinfo()->data());
      last_position = SourcePosition(script_offset, inlining_id);
    } else if (info->rmode() == RelocInfo::DEOPT_ID) {
      last_deopt_id = static_cast<int>(info->data());
    } else if (info->rmode() == RelocInfo::DEOPT_REASON) {
      last_reason = static_cast<DeoptimizeReason>(info->data());
    } else if (info->rmode() == RelocInfo::DEOPT_NODE_ID) {
      last_node_id = static_cast<uint32_t>(info->data());
    }
  }
  return DeoptInfo(last_position, last_reason, last_node_id, last_deopt_id);
}
References CHECK, code, v8::internal::RelocInfo::data(), v8::internal::DCHECK(), v8::internal::RelocInfo::DEOPT_ID, v8::internal::RelocInfo::DEOPT_INLINING_ID, v8::internal::RelocInfo::DEOPT_NODE_ID, v8::internal::RelocInfo::DEOPT_REASON, v8::internal::RelocInfo::DEOPT_SCRIPT_OFFSET, v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::kNoDeoptimizationId, v8::internal::RelocInfo::ModeMask(), v8::internal::RelocInfo::pc(), v8::internal::RelocInfo::rmode(), and v8::internal::SourcePosition::Unknown().
Referenced by v8::internal::RUNTIME_FUNCTION().
Grab()
Deoptimizer * v8::internal::Deoptimizer::Grab (Isolate * isolate) [static]
Definition at line 280 of file deoptimizer.cc.
                                               {
  Deoptimizer* result = isolate->GetAndClearCurrentDeoptimizer();
  result->DeleteFrameDescriptions();
  return result;
}
References v8::internal::Isolate::GetAndClearCurrentDeoptimizer(), and v8::base::internal::result.
Referenced by DeleteForWasm().
input_offset()
static int v8::internal::Deoptimizer::input_offset () [inline], [static]
Definition at line 136 of file deoptimizer.h.
{ return offsetof(Deoptimizer, input_); }
References input_.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_DeoptimizationEntry().
is_restart_frame()
bool v8::internal::Deoptimizer::is_restart_frame () const [inline], [private]
Definition at line 250 of file deoptimizer.h.
{ return restart_frame_index_ >= 0; }
References restart_frame_index_.
Referenced by DoComputeOutputFrames(), and DoComputeUnoptimizedFrame().
isolate()
Isolate* v8::internal::Deoptimizer::isolate () const [inline]
Definition at line 156 of file deoptimizer.h.
{ return isolate_; }
References isolate_.
Referenced by compiled_code(), DeoptExitIsInsideOsrLoop(), Deoptimizer(), DoComputeBuiltinContinuation(), DoComputeConstructCreateStubFrame(), DoComputeConstructInvokeStubFrame(), DoComputeInlinedExtraArguments(), DoComputeOutputFrames(), DoComputeUnoptimizedFrame(), function(), TraceDeoptAll(), TraceEvictFromOptimizedCodeCache(), and TraceMarkForDeoptimization().
MaterializeHeapObjects()
void v8::internal::Deoptimizer::MaterializeHeapObjects ()
Definition at line 2912 of file deoptimizer.cc.
                                         {
  translated_state_.Prepare(static_cast<Address>(stack_fp_));
  if (v8_flags.deopt_every_n_times > 0) {
    // Doing a GC here will find problems with the deoptimized frames.
    isolate_->heap()->CollectAllGarbage(GCFlag::kNoFlags,
                                        GarbageCollectionReason::kTesting);
  }
  for (auto& materialization : values_to_materialize_) {
    DirectHandle<Object> value = materialization.value_->GetValue();
    if (verbose_tracing_enabled()) {
      PrintF(trace_scope()->file(),
             "Materialization [" V8PRIxPTR_FMT "] <- " V8PRIxPTR_FMT " ; ",
             static_cast<intptr_t>(materialization.output_slot_address_),
             (*value).ptr());
      ShortPrint(*value, trace_scope()->file());
      PrintF(trace_scope()->file(), "\n");
    }
    *(reinterpret_cast<Address*>(materialization.output_slot_address_)) =
        (*value).ptr();
  }
  for (auto& fbv_materialization : feedback_vector_to_materialize_) {
    DirectHandle<Object> closure = fbv_materialization.value_->GetValue();
    DCHECK(IsJSFunction(*closure));
    Tagged<Object> feedback_vector =
        Cast<JSFunction>(*closure)->raw_feedback_cell()->value();
    CHECK(IsFeedbackVector(feedback_vector));
    *(reinterpret_cast<Address*>(fbv_materialization.output_slot_address_)) =
        feedback_vector.ptr();
  }
  translated_state_.VerifyMaterializedObjects();
  isolate_->materialized_object_store()->Remove(
      static_cast<Address>(stack_fp_));
}
References CHECK, v8::internal::Heap::CollectAllGarbage(), v8::internal::DCHECK(), feedback_vector_to_materialize_, file(), v8::internal::Isolate::heap(), isolate_, v8::internal::kNoFlags, v8::internal::kTesting, v8::internal::Isolate::materialized_object_store(), v8::internal::TranslatedState::Prepare(), v8::internal::PrintF(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::MaterializedObjectStore::Remove(), v8::internal::ShortPrint(), stack_fp_, trace_scope(), translated_state_, v8::internal::v8_flags, V8PRIxPTR_FMT, v8::internal::value, values_to_materialize_, verbose_tracing_enabled(), and v8::internal::TranslatedState::VerifyMaterializedObjects().
Referenced by v8::internal::RUNTIME_FUNCTION().
MessageFor()
const char * v8::internal::Deoptimizer::MessageFor (DeoptimizeKind kind) [static]
Definition at line 590 of file deoptimizer.cc.
                                                       {
  switch (kind) {
    case DeoptimizeKind::kEager:
      return "deopt-eager";
    case DeoptimizeKind::kLazyAfterFastCall:
      return "deopt-lazy-after-fastcall";
    case DeoptimizeKind::kLazy:
      return "deopt-lazy";
  }
}
References v8::internal::kEager, v8::internal::kLazy, and v8::internal::kLazyAfterFastCall.
Referenced by v8::internal::V8FileLogger::CodeDeoptEvent(), and TraceDeoptBegin().
New()
Deoptimizer * v8::internal::Deoptimizer::New (Address raw_function, DeoptimizeKind kind, Address from, int fp_to_sp_delta, Isolate * isolate) [static]
Definition at line 267 of file deoptimizer.cc.
                                                {
  // This is zero for wasm.
  Tagged<JSFunction> function =
      raw_function != 0 ? Cast<JSFunction>(Tagged<Object>(raw_function))
                        : Tagged<JSFunction>();
  Deoptimizer* deoptimizer =
      new Deoptimizer(isolate, function, kind, from, fp_to_sp_delta);
  isolate->set_current_deoptimizer(deoptimizer);
  return deoptimizer;
}
References v8::internal::Isolate::set_current_deoptimizer().
output_count()
int v8::internal::Deoptimizer::output_count () const [inline]
Definition at line 74 of file deoptimizer.h.
{ return output_count_; }
References output_count_.
Referenced by DeleteForWasm().
output_count_offset()
static int v8::internal::Deoptimizer::output_count_offset () [inline], [static]
Definition at line 137 of file deoptimizer.h.
                                   {
    return offsetof(Deoptimizer, output_count_);
  }
References output_count_.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_DeoptimizationEntry().
output_offset()
static int v8::internal::Deoptimizer::output_offset () [inline], [static]
Definition at line 140 of file deoptimizer.h.
{ return offsetof(Deoptimizer, output_); }
References output_.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_DeoptimizationEntry().
PatchToJump()
void v8::internal::Deoptimizer::PatchToJump (Address pc, Address new_pc) [static]
Definition at line 29 of file deoptimizer-arm.cc.
                                                        {
  int offset = new_pc - (pc + Instruction::kPcLoadDelta);
  // We'll overwrite only one instruction of 4-bytes. Give enough
  // space not to try to grow the buffer.
  constexpr int kSize = 64;
  Assembler masm(
      AssemblerOptions{},
      ExternalAssemblerBuffer(reinterpret_cast<uint8_t*>(pc), kSize));
  masm.b(offset);
  FlushInstructionCache(pc, kSize);
}
References v8::internal::Assembler::b(), v8::internal::ExternalAssemblerBuffer(), v8::internal::FlushInstructionCache(), and v8::internal::Instruction::kPcLoadDelta.
Referenced by v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor::VisitThread(), and v8::internal::anonymous_namespace{deoptimizer.cc}::ActivationsFinder::VisitThread().
ProcessDeoptReason()
void v8::internal::Deoptimizer::ProcessDeoptReason (DeoptimizeReason reason)
Definition at line 2952 of file deoptimizer.cc.
                                                            {
  bool feedback_updated = translated_state_.DoUpdateFeedback(reason);
  if (verbose_tracing_enabled() && feedback_updated) {
    FILE* file = trace_scope()->file();
    Deoptimizer::DeoptInfo info = Deoptimizer::GetDeoptInfo();
    PrintF(file, "Feedback updated from deoptimization at ");
    OFStream outstr(file);
    info.position.Print(outstr, compiled_code_);
    PrintF(file, ", %s\n", DeoptimizeReasonToString(info.deopt_reason));
  }
}
References compiled_code_, v8::internal::Deoptimizer::DeoptInfo::deopt_reason, v8::internal::DeoptimizeReasonToString(), v8::internal::TranslatedState::DoUpdateFeedback(), v8::internal::CodeTracer::Scope::file(), file(), GetDeoptInfo(), v8::internal::Deoptimizer::DeoptInfo::position, v8::internal::SourcePosition::Print(), v8::internal::PrintF(), trace_scope(), translated_state_, and verbose_tracing_enabled().
Referenced by v8::internal::RUNTIME_FUNCTION().
QueueFeedbackVectorForMaterialization()
void v8::internal::Deoptimizer::QueueFeedbackVectorForMaterialization (Address output_address, const TranslatedFrame::iterator & iterator) [private]
Definition at line 2972 of file deoptimizer.cc.
                                                                     {
  feedback_vector_to_materialize_.push_back({output_address, iterator});
}
References feedback_vector_to_materialize_.
QueueValueForMaterialization()
void v8::internal::Deoptimizer::QueueValueForMaterialization (Address output_address, Tagged< Object > obj, const TranslatedFrame::iterator & iterator) [private]
Definition at line 2964 of file deoptimizer.cc.
                                             {
  if (obj == ReadOnlyRoots(isolate_).arguments_marker()) {
    values_to_materialize_.push_back({output_address, iterator});
  }
}
References isolate_, and values_to_materialize_.
trace_scope()
CodeTracer::Scope* v8::internal::Deoptimizer::trace_scope () const [inline], [private]
Definition at line 238 of file deoptimizer.h.
{ return trace_scope_; }
References trace_scope_.
Referenced by DoComputeBuiltinContinuation(), DoComputeConstructCreateStubFrame(), DoComputeConstructInvokeStubFrame(), DoComputeOutputFrames(), DoComputeUnoptimizedFrame(), MaterializeHeapObjects(), ProcessDeoptReason(), TraceDeoptBegin(), TraceDeoptEnd(), and verbose_trace_scope().
TraceDeoptAll()
void v8::internal::Deoptimizer::TraceDeoptAll (Isolate * isolate) [static], [private]
Definition at line 927 of file deoptimizer.cc.
                                                {
  if (!v8_flags.trace_deopt_verbose) return;
  CodeTracer::Scope scope(isolate->GetCodeTracer());
  PrintF(scope.file(), "[deoptimize all code in all contexts]\n");
}
References v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), isolate(), v8::internal::PrintF(), and v8::internal::v8_flags.
TraceDeoptBegin()
void v8::internal::Deoptimizer::TraceDeoptBegin (int optimization_id, BytecodeOffset bytecode_offset) [private]
Definition at line 823 of file deoptimizer.cc.
                                                                  {
  DCHECK(tracing_enabled());
  FILE* file = trace_scope()->file();
  Deoptimizer::DeoptInfo info = Deoptimizer::GetDeoptInfo();
  PrintF(file, "[bailout (kind: %s, reason: %s): begin. deoptimizing ",
         MessageFor(deopt_kind_), DeoptimizeReasonToString(info.deopt_reason));
  if (IsJSFunction(function_)) {
    ShortPrint(function_, file);
    PrintF(file, ", ");
  }
  ShortPrint(compiled_code_, file);
  PrintF(file,
         ", opt id %d, "
#ifdef DEBUG
         "node id %d, "
#endif // DEBUG
         "bytecode offset %d, deopt exit %d, FP to SP "
         "delta %d, "
         "caller SP " V8PRIxPTR_FMT ", pc " V8PRIxPTR_FMT "]\n",
         optimization_id,
#ifdef DEBUG
         info.node_id,
#endif // DEBUG
         bytecode_offset.ToInt(), deopt_exit_index_, fp_to_sp_delta_,
         caller_frame_top_, PointerAuthentication::StripPAC(from_));
  if (verbose_tracing_enabled() && deopt_kind_ != DeoptimizeKind::kLazy) {
    PrintF(file, " ;;; deoptimize at ");
    OFStream outstr(file);
    info.position.Print(outstr, compiled_code_);
    PrintF(file, "\n");
  }
}
References caller_frame_top_, compiled_code_, v8::internal::DCHECK(), deopt_exit_index_, deopt_kind_, v8::internal::Deoptimizer::DeoptInfo::deopt_reason, v8::internal::DeoptimizeReasonToString(), v8::internal::CodeTracer::Scope::file(), file(), fp_to_sp_delta_, from_, function_, GetDeoptInfo(), v8::internal::kLazy, MessageFor(), v8::internal::Deoptimizer::DeoptInfo::node_id, v8::internal::Deoptimizer::DeoptInfo::position, v8::internal::SourcePosition::Print(), v8::internal::PrintF(), v8::internal::ShortPrint(), v8::internal::PointerAuthentication::StripPAC(), v8::internal::BytecodeOffset::ToInt(), trace_scope(), tracing_enabled(), V8PRIxPTR_FMT, and verbose_tracing_enabled().
Referenced by DoComputeOutputFrames().
TraceDeoptEnd()
void v8::internal::Deoptimizer::TraceDeoptEnd (double deopt_duration) [private]
Definition at line 857 of file deoptimizer.cc.
                                                     {
  DCHECK(verbose_tracing_enabled());
  PrintF(trace_scope()->file(), "[bailout end. took %0.3f ms]\n",
         deopt_duration);
}
References v8::internal::DCHECK(), file(), v8::internal::PrintF(), trace_scope(), and verbose_tracing_enabled().
Referenced by DoComputeOutputFrames().
TraceEvictFromOptimizedCodeCache()
void v8::internal::Deoptimizer::TraceEvictFromOptimizedCodeCache (Isolate * isolate, Tagged< SharedFunctionInfo > sfi, const char * reason) [static]
Definition at line 901 of file deoptimizer.cc.
                                                                          {
  if (!v8_flags.trace_deopt_verbose) return;
  DisallowGarbageCollection no_gc;
  CodeTracer::Scope scope(isolate->GetCodeTracer());
  PrintF(scope.file(),
         "[evicting optimized code marked for deoptimization (%s) for ",
         reason);
  ShortPrint(sfi, scope.file());
  PrintF(scope.file(), "]\n");
}
References v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), isolate(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PrintF(), v8::internal::ShortPrint(), and v8::internal::v8_flags.
Referenced by v8::internal::FeedbackVector::EvictOptimizedCodeMarkedForDeoptimization().
TraceMarkForDeoptimization()
void v8::internal::Deoptimizer::TraceMarkForDeoptimization (Isolate * isolate, Tagged< Code > code, LazyDeoptimizeReason reason) [static]
Definition at line 864 of file deoptimizer.cc.
                                                                          {
  // `DiscardBaselineCodeVisitor` can discard baseline code for debug purpose,
  // and it may use `MarkForDeoptimization` for interpreting the new stack
  // frame as an interpreter frame, but it does not have deoptimization data.
  if (code->kind() == CodeKind::BASELINE) return;
  DCHECK(code->uses_deoptimization_data());
  if (!v8_flags.trace_deopt && !v8_flags.log_deopt) return;
  DisallowGarbageCollection no_gc;
  Tagged<DeoptimizationData> deopt_data =
      Cast<DeoptimizationData>(code->deoptimization_data());
  CodeTracer::Scope scope(isolate->GetCodeTracer());
  if (v8_flags.trace_deopt) {
    PrintF(scope.file(), "[marking dependent code ");
    ShortPrint(code, scope.file());
    PrintF(scope.file(), " (");
    ShortPrint(deopt_data->GetSharedFunctionInfo(), scope.file());
    PrintF(") (opt id %d) for deoptimization, reason: %s]\n",
           deopt_data->OptimizationId().value(),
           DeoptimizeReasonToString(reason));
  }
  if (!v8_flags.log_deopt) return;
  no_gc.Release();
  {
    HandleScope handle_scope(isolate);
    PROFILE(isolate,
            CodeDependencyChangeEvent(
                direct_handle(code, isolate),
                direct_handle(deopt_data->GetSharedFunctionInfo(), isolate),
                DeoptimizeReasonToString(reason)));
  }
}
References code, v8::internal::DCHECK(), v8::internal::DeoptimizeReasonToString(), v8::internal::direct_handle(), v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), isolate(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PrintF(), PROFILE, v8::internal::PerThreadAssertScopeEmpty< kAllow, kTypes >::Release(), v8::internal::ShortPrint(), and v8::internal::v8_flags.
Referenced by v8::internal::Code::TraceMarkForDeoptimization().
tracing_enabled()
bool v8::internal::Deoptimizer::tracing_enabled () const [inline], [private]
Definition at line 234 of file deoptimizer.h.
{ return trace_scope_ != nullptr; }
References trace_scope_.
Referenced by DoComputeOutputFrames(), TraceDeoptBegin(), and verbose_tracing_enabled().
TrampolineForBuiltinContinuation()
Builtin v8::internal::Deoptimizer::TrampolineForBuiltinContinuation (BuiltinContinuationMode mode, bool must_handle_result) [static], [private]
Definition at line 2493 of file deoptimizer.cc.
                                                           {
  switch (mode) {
    case BuiltinContinuationMode::STUB:
      return must_handle_result ? Builtin::kContinueToCodeStubBuiltinWithResult
                                : Builtin::kContinueToCodeStubBuiltin;
    case BuiltinContinuationMode::JAVASCRIPT:
    case BuiltinContinuationMode::JAVASCRIPT_WITH_CATCH:
    case BuiltinContinuationMode::JAVASCRIPT_HANDLE_EXCEPTION:
      return must_handle_result
                 ? Builtin::kContinueToJavaScriptBuiltinWithResult
                 : Builtin::kContinueToJavaScriptBuiltin;
  }
  UNREACHABLE();
}
References v8::internal::JAVASCRIPT, v8::internal::JAVASCRIPT_HANDLE_EXCEPTION, v8::internal::JAVASCRIPT_WITH_CATCH, mode(), v8::internal::STUB, and v8::internal::UNREACHABLE().
Referenced by DoComputeBuiltinContinuation().
verbose_trace_scope()
CodeTracer::Scope* v8::internal::Deoptimizer::verbose_trace_scope () const [inline], [private]
Definition at line 239 of file deoptimizer.h.
                                               {
    return v8_flags.trace_deopt_verbose ? trace_scope() : nullptr;
  }
References trace_scope(), and v8::internal::v8_flags.
Referenced by DoComputeBuiltinContinuation(), DoComputeConstructCreateStubFrame(), DoComputeConstructInvokeStubFrame(), DoComputeInlinedExtraArguments(), and DoComputeUnoptimizedFrame().
verbose_tracing_enabled()
bool v8::internal::Deoptimizer::verbose_tracing_enabled () const [inline], [private]
Definition at line 235 of file deoptimizer.h.
                                       {
    return v8_flags.trace_deopt_verbose && tracing_enabled();
  }
References tracing_enabled(), and v8::internal::v8_flags.
Referenced by DoComputeBuiltinContinuation(), DoComputeConstructCreateStubFrame(), DoComputeConstructInvokeStubFrame(), DoComputeInlinedExtraArguments(), DoComputeOutputFrames(), DoComputeUnoptimizedFrame(), MaterializeHeapObjects(), ProcessDeoptReason(), TraceDeoptBegin(), and TraceDeoptEnd().
Friends And Related Function Documentation
DeoptimizedFrameInfo
friend class DeoptimizedFrameInfo [friend]
Definition at line 320 of file deoptimizer.h.
FrameDescription
friend class FrameDescription [friend]
Definition at line 321 of file deoptimizer.h.
FrameWriter
friend class FrameWriter [friend]
Definition at line 322 of file deoptimizer.h.
Member Data Documentation
actual_argument_count_
int v8::internal::Deoptimizer::actual_argument_count_ [private]
Definition at line 282 of file deoptimizer.h.
Referenced by DoComputeOutputFrames(), and DoComputeUnoptimizedFrame().
bytecode_offset_in_outermost_frame_
BytecodeOffset v8::internal::Deoptimizer::bytecode_offset_in_outermost_frame_ = BytecodeOffset::None() [private]
Definition at line 259 of file deoptimizer.h.
Referenced by bytecode_offset_in_outermost_frame(), and DoComputeOutputFrames().
caller_constant_pool_
intptr_t v8::internal::Deoptimizer::caller_constant_pool_ [private]
Definition at line 279 of file deoptimizer.h.
Referenced by DoComputeBuiltinContinuation(), DoComputeOutputFrames(), and DoComputeUnoptimizedFrame().
caller_fp_
intptr_t v8::internal::Deoptimizer::caller_fp_ [private]
Definition at line 277 of file deoptimizer.h.
Referenced by DoComputeBuiltinContinuation(), DoComputeOutputFrames(), and DoComputeUnoptimizedFrame().
caller_frame_top_
intptr_t v8::internal::Deoptimizer::caller_frame_top_ [private]
Definition at line 276 of file deoptimizer.h.
Referenced by caller_frame_top_offset(), DoComputeBuiltinContinuation(), DoComputeOutputFrames(), DoComputeUnoptimizedFrame(), and TraceDeoptBegin().
caller_pc_
intptr_t v8::internal::Deoptimizer::caller_pc_ [private]
Definition at line 278 of file deoptimizer.h.
Referenced by DoComputeBuiltinContinuation(), DoComputeOutputFrames(), and DoComputeUnoptimizedFrame().
catch_handler_data_
int v8::internal::Deoptimizer::catch_handler_data_ [private]
Definition at line 264 of file deoptimizer.h.
Referenced by DoComputeOutputFrames(), and DoComputeUnoptimizedFrame().
catch_handler_pc_offset_
int v8::internal::Deoptimizer::catch_handler_pc_offset_ [private]
Definition at line 265 of file deoptimizer.h.
Referenced by DoComputeOutputFrames(), and DoComputeUnoptimizedFrame().
compiled_code_
Tagged<Code> v8::internal::Deoptimizer::compiled_code_ [private]
Definition at line 254 of file deoptimizer.h.
Referenced by compiled_code(), ComputeInputFrameAboveFpFixedSize(), ComputeInputFrameSize(), Deoptimizer(), DoComputeOutputFrames(), GetDeoptInfo(), ProcessDeoptReason(), and TraceDeoptBegin().
deopt_exit_index_
unsigned v8::internal::Deoptimizer::deopt_exit_index_ [private]
Definition at line 258 of file deoptimizer.h.
Referenced by Deoptimizer(), DoComputeOutputFrames(), and TraceDeoptBegin().
deopt_kind_
DeoptimizeKind v8::internal::Deoptimizer::deopt_kind_ [private]
Definition at line 260 of file deoptimizer.h.
Referenced by deopt_kind(), DoComputeBuiltinContinuation(), DoComputeConstructCreateStubFrame(), DoComputeConstructInvokeStubFrame(), DoComputeUnoptimizedFrame(), and TraceDeoptBegin().
deoptimizing_throw_
bool v8::internal::Deoptimizer::deoptimizing_throw_ [private]
Definition at line 263 of file deoptimizer.h.
Referenced by ComputeInputFrameSize(), Deoptimizer(), and DoComputeOutputFrames().
feedback_vector_to_materialize_
std::vector<ValueToMaterialize> v8::internal::Deoptimizer::feedback_vector_to_materialize_ [private]
Definition at line 293 of file deoptimizer.h.
Referenced by MaterializeHeapObjects(), and QueueFeedbackVectorForMaterialization().
fp_to_sp_delta_
int v8::internal::Deoptimizer::fp_to_sp_delta_ [private]
Definition at line 262 of file deoptimizer.h.
Referenced by ComputeInputFrameSize(), Deoptimizer(), and TraceDeoptBegin().
from_
Address v8::internal::Deoptimizer::from_ [private]
Definition at line 261 of file deoptimizer.h.
Referenced by ComputeInputFrameSize(), Deoptimizer(), GetDeoptInfo(), and TraceDeoptBegin().
function_
Tagged<JSFunction> v8::internal::Deoptimizer::function_ [private]
Definition at line 253 of file deoptimizer.h.
Referenced by ComputeInputFrameAboveFpFixedSize(), DoComputeOutputFrames(), function(), and TraceDeoptBegin().
input_
FrameDescription* v8::internal::Deoptimizer::input_ [private]
Definition at line 269 of file deoptimizer.h.
Referenced by DeleteFrameDescriptions(), Deoptimizer(), DoComputeBuiltinContinuation(), DoComputeConstructCreateStubFrame(), DoComputeConstructInvokeStubFrame(), DoComputeOutputFrames(), DoComputeUnoptimizedFrame(), input_offset(), and ~Deoptimizer().
isolate_
Isolate* v8::internal::Deoptimizer::isolate_ [private]
Definition at line 252 of file deoptimizer.h.
Referenced by ComputeInputFrameSize(), Deoptimizer(), DoComputeConstructCreateStubFrame(), DoComputeConstructInvokeStubFrame(), DoComputeOutputFrames(), DoComputeUnoptimizedFrame(), isolate(), MaterializeHeapObjects(), and QueueValueForMaterialization().
kAdaptShadowStackOffsetToSubtract
const int v8::internal::Deoptimizer::kAdaptShadowStackOffsetToSubtract = 0 [static]
Definition at line 170 of file deoptimizer.h.
Referenced by DoComputeOutputFrames().
kEagerDeoptExitSize
const int v8::internal::Deoptimizer::kEagerDeoptExitSize = 2 * kInstrSize [static]
Definition at line 166 of file deoptimizer.h.
Referenced by v8::internal::MacroAssembler::CallForDeoptimization(), Deoptimizer(), v8::internal::wasm::WasmCode::Disassemble(), and v8::internal::anonymous_namespace{deoptimizer.cc}::GetDeoptCallPCFromReturnPC().
kFixedExitSizeMarker
constexpr unsigned v8::internal::Deoptimizer::kFixedExitSizeMarker = kMaxUInt32 [static], [constexpr]
Definition at line 163 of file deoptimizer.h.
Referenced by Deoptimizer().
kLazyDeoptExitSize
const int v8::internal::Deoptimizer::kLazyDeoptExitSize = 2 * kInstrSize [static]
Definition at line 167 of file deoptimizer.h.
Referenced by v8::internal::MacroAssembler::CallForDeoptimization(), Deoptimizer(), and v8::internal::anonymous_namespace{deoptimizer.cc}::GetDeoptCallPCFromReturnPC().
kMaxNumberOfEntries
constexpr int v8::internal::Deoptimizer::kMaxNumberOfEntries = 16384 [static], [constexpr]
Definition at line 158 of file deoptimizer.h.
Referenced by v8::internal::compiler::CodeGenerator::AssembleDeoptimizerCall(), and v8::internal::maglev::MaglevCodeGenerator::EmitDeopts().
output_
FrameDescription** v8::internal::Deoptimizer::output_ [private]
Definition at line 273 of file deoptimizer.h.
Referenced by DeleteFrameDescriptions(), DoComputeBuiltinContinuation(), DoComputeConstructCreateStubFrame(), DoComputeConstructInvokeStubFrame(), DoComputeInlinedExtraArguments(), DoComputeOutputFrames(), DoComputeUnoptimizedFrame(), output_offset(), and ~Deoptimizer().
output_count_
int v8::internal::Deoptimizer::output_count_ [private]
Definition at line 271 of file deoptimizer.h.
Referenced by DeleteFrameDescriptions(), DoComputeBuiltinContinuation(), DoComputeConstructCreateStubFrame(), DoComputeConstructInvokeStubFrame(), DoComputeInlinedExtraArguments(), DoComputeOutputFrames(), DoComputeUnoptimizedFrame(), output_count(), and output_count_offset().
restart_frame_index_
int v8::internal::Deoptimizer::restart_frame_index_ [private]
Definition at line 266 of file deoptimizer.h.
Referenced by Deoptimizer(), DoComputeOutputFrames(), and is_restart_frame().
stack_fp_
intptr_t v8::internal::Deoptimizer::stack_fp_ [private]
Definition at line 285 of file deoptimizer.h.
Referenced by DoComputeOutputFrames(), and MaterializeHeapObjects().
trace_scope_
CodeTracer::Scope* const v8::internal::Deoptimizer::trace_scope_ [private]
Definition at line 306 of file deoptimizer.h.
Referenced by DoComputeInlinedExtraArguments(), DoComputeUnoptimizedFrame(), trace_scope(), tracing_enabled(), and ~Deoptimizer().
translated_state_
TranslatedState v8::internal::Deoptimizer::translated_state_ [private]
Definition at line 287 of file deoptimizer.h.
Referenced by DoComputeOutputFrames(), DoComputeUnoptimizedFrame(), MaterializeHeapObjects(), and ProcessDeoptReason().
values_to_materialize_
std::vector<ValueToMaterialize> v8::internal::Deoptimizer::values_to_materialize_ [private]
Definition at line 292 of file deoptimizer.h.
Referenced by MaterializeHeapObjects(), and QueueValueForMaterialization().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/deoptimizer/deoptimizer.h
/mnt/V8SourceCode/src/deoptimizer/arm/deoptimizer-arm.cc
/mnt/V8SourceCode/src/deoptimizer/arm64/deoptimizer-arm64.cc
/mnt/V8SourceCode/src/deoptimizer/deoptimizer.cc
/mnt/V8SourceCode/src/deoptimizer/loong64/deoptimizer-loong64.cc
/mnt/V8SourceCode/src/deoptimizer/mips64/deoptimizer-mips64.cc
/mnt/V8SourceCode/src/deoptimizer/ppc/deoptimizer-ppc.cc
/mnt/V8SourceCode/src/deoptimizer/riscv/deoptimizer-riscv.cc
/mnt/V8SourceCode/src/deoptimizer/s390/deoptimizer-s390.cc