v8::internal::anonymous_namespace{cpp-heap.cc}::CollectCustomSpaceStatisticsAtLastGCTask Class Reference
Public Member Functions
CollectCustomSpaceStatisticsAtLastGCTask (cppgc::internal::HeapBase &heap, std::vector< cppgc::CustomSpaceIndex > custom_spaces, std::unique_ptr< CustomSpaceStatisticsReceiver > receiver)
void Run () final
Static Public Attributes
static constexpr v8::base::TimeDelta kTaskDelayMs
Private Attributes
cppgc::internal::HeapBase & heap_
std::vector< cppgc::CustomSpaceIndex > custom_spaces_
std::unique_ptr< CustomSpaceStatisticsReceiver > receiver_
Static Private Attributes
static constexpr v8::base::TimeDelta kStepSizeMs
Detailed Description
Definition at line 1174 of file cpp-heap.cc.
Constructor & Destructor Documentation
CollectCustomSpaceStatisticsAtLastGCTask()
v8::internal::anonymous_namespace{cpp-heap.cc}::CollectCustomSpaceStatisticsAtLastGCTask::CollectCustomSpaceStatisticsAtLastGCTask (cppgc::internal::HeapBase & heap, std::vector< cppgc::CustomSpaceIndex > custom_spaces, std::unique_ptr< CustomSpaceStatisticsReceiver > receiver) [inline]
Definition at line 1179 of file cpp-heap.cc.
      : heap_(heap),
        custom_spaces_(std::move(custom_spaces)),
        receiver_(std::move(receiver)) {}
Member Function Documentation
Run()
void v8::internal::anonymous_namespace{cpp-heap.cc}::CollectCustomSpaceStatisticsAtLastGCTask::Run () [inline], [final], [virtual]
Implements v8::Task.
Definition at line 1187 of file cpp-heap.cc.
                   {
    cppgc::internal::Sweeper& sweeper = heap_.sweeper();
    if (sweeper.PerformSweepOnMutatorThread(
            kStepSizeMs,
            cppgc::internal::StatsCollector::kSweepInTaskForStatistics)) {
      // Sweeping is done.
      DCHECK(!sweeper.IsSweepingInProgress());
      ReportCustomSpaceStatistics(heap_.raw_heap(), std::move(custom_spaces_),
                                  std::move(receiver_));
    } else {
      heap_.platform()->GetForegroundTaskRunner()->PostDelayedTask(
          std::make_unique<CollectCustomSpaceStatisticsAtLastGCTask>(
              heap_, std::move(custom_spaces_), std::move(receiver_)),
          kTaskDelayMs.InSecondsF());
    }
  }
References v8::internal::DCHECK(), cppgc::internal::Sweeper::IsSweepingInProgress(), cppgc::internal::Sweeper::PerformSweepOnMutatorThread(), and v8::internal::anonymous_namespace{cpp-heap.cc}::ReportCustomSpaceStatistics().
Member Data Documentation
custom_spaces_
std::vector<cppgc::CustomSpaceIndex> v8::internal::anonymous_namespace{cpp-heap.cc}::CollectCustomSpaceStatisticsAtLastGCTask::custom_spaces_ [private]
Definition at line 1209 of file cpp-heap.cc.
heap_
cppgc::internal::HeapBase& v8::internal::anonymous_namespace{cpp-heap.cc}::CollectCustomSpaceStatisticsAtLastGCTask::heap_ [private]
Definition at line 1208 of file cpp-heap.cc.
kStepSizeMs
constexpr v8::base::TimeDelta v8::internal::anonymous_namespace{cpp-heap.cc}::CollectCustomSpaceStatisticsAtLastGCTask::kStepSizeMs [static], [constexpr], [private]
Initial value:
=
      v8::base::TimeDelta::FromMilliseconds(5)
Definition at line 1205 of file cpp-heap.cc.
kTaskDelayMs
constexpr v8::base::TimeDelta v8::internal::anonymous_namespace{cpp-heap.cc}::CollectCustomSpaceStatisticsAtLastGCTask::kTaskDelayMs [static], [constexpr]
Initial value:
=
      v8::base::TimeDelta::FromMilliseconds(10)
Definition at line 1176 of file cpp-heap.cc.
receiver_
std::unique_ptr<CustomSpaceStatisticsReceiver> v8::internal::anonymous_namespace{cpp-heap.cc}::CollectCustomSpaceStatisticsAtLastGCTask::receiver_ [private]
Definition at line 1210 of file cpp-heap.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc-js/cpp-heap.cc