v8::internal::MarkCompactCollector::SharedHeapObjectVisitor Class Reference
Public Member Functions
SharedHeapObjectVisitor (MarkCompactCollector *collector)
void VisitPointer (Tagged< HeapObject > host, ObjectSlot p) final
void VisitPointer (Tagged< HeapObject > host, MaybeObjectSlot p) final
void VisitMapPointer (Tagged< HeapObject > host) final
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) final
void VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) override
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) final
void VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo *rinfo) override
Private Member Functions
void CheckForSharedObject (Tagged< HeapObject > host, ObjectSlot slot, Tagged< Object > object)
Private Attributes
MarkCompactCollector *const collector_
Additional Inherited Members
Detailed Description
Definition at line 1018 of file mark-compact.cc.
Constructor & Destructor Documentation
SharedHeapObjectVisitor()
v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::SharedHeapObjectVisitor (MarkCompactCollector * collector) [inline], [explicit]
Definition at line 1021 of file mark-compact.cc.
      : HeapVisitor(collector->heap_->isolate()), collector_(collector) {}
Member Function Documentation
CheckForSharedObject()
void v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::CheckForSharedObject (Tagged< HeapObject > host, ObjectSlot slot, Tagged< Object > object) [inline], [private]
Definition at line 1074 of file mark-compact.cc.
                                                             {
    DCHECK(!HeapLayout::InAnySharedSpace(host));
    Tagged<HeapObject> heap_object;
    if (!object.GetHeapObject(&heap_object)) return;
    if (!HeapLayout::InWritableSharedSpace(heap_object)) return;
    DCHECK(HeapLayout::InWritableSharedSpace(heap_object));
    MemoryChunk* host_chunk = MemoryChunk::FromHeapObject(host);
    MutablePageMetadata* host_page_metadata =
        MutablePageMetadata::cast(host_chunk->Metadata());
    DCHECK(HeapLayout::InYoungGeneration(host));
    // Temporarily record new-to-shared slots in the old-to-shared remembered
    // set so we don't need to iterate the page again later for updating the
    // references.
    RememberedSet<OLD_TO_SHARED>::Insert<AccessMode::NON_ATOMIC>(
        host_page_metadata, host_chunk->Offset(slot.address()));
    if (MarkingHelper::ShouldMarkObject(collector_->heap(), heap_object)) {
      collector_->MarkRootObject(Root::kClientHeap, heap_object,
                                 MarkingHelper::WorklistTarget::kRegular);
    }
  }
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), v8::internal::MutablePageMetadata::cast(), collector_, v8::internal::DCHECK(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MarkCompactCollector::heap(), v8::internal::HeapLayout::InAnySharedSpace(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::MarkingHelper::kRegular, v8::internal::MarkCompactCollector::MarkRootObject(), v8::internal::MemoryChunk::Metadata(), v8::internal::MemoryChunk::Offset(), and v8::internal::MarkingHelper::ShouldMarkObject().
Referenced by VisitMapPointer(), VisitPointer(), and VisitPointers().
VisitCodeTarget()
void v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1063 of file mark-compact.cc.
                                                  {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitEmbeddedPointer()
void v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1068 of file mark-compact.cc.
                                                       {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitInstructionStreamPointer()
void v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 1049 of file mark-compact.cc.
                                                                          {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitMapPointer()
void v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::VisitMapPointer (Tagged< HeapObject > host) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1035 of file mark-compact.cc.
                                                      {
    CheckForSharedObject(host, host->map_slot(), host->map(cage_base()));
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), and CheckForSharedObject().
VisitPointer() [1/2]
void v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::VisitPointer (Tagged< HeapObject > host, MaybeObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1028 of file mark-compact.cc.
                                                                      {
    Tagged<MaybeObject> object = p.load(cage_base());
    Tagged<HeapObject> heap_object;
    if (object.GetHeapObject(&heap_object))
      CheckForSharedObject(host, ObjectSlot(p), heap_object);
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), and CheckForSharedObject().
VisitPointer() [2/2]
void v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::VisitPointer (Tagged< HeapObject > host, ObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1024 of file mark-compact.cc.
                                                                 {
    CheckForSharedObject(host, p, p.load(cage_base()));
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), and CheckForSharedObject().
Referenced by VisitPointers().
VisitPointers() [1/2]
void v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 1054 of file mark-compact.cc.
                                                {
    for (MaybeObjectSlot p = start; p < end; ++p) {
      // The map slot should be handled in VisitMapPointer.
      DCHECK_NE(host->map_slot(), ObjectSlot(p));
      VisitPointer(host, p);
    }
  }
References DCHECK_NE, v8::internal::compiler::end(), and VisitPointer().
VisitPointers() [2/2]
void v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 1039 of file mark-compact.cc.
                                           {
    for (ObjectSlot p = start; p < end; ++p) {
      // The map slot should be handled in VisitMapPointer.
      DCHECK_NE(host->map_slot(), p);
      DCHECK(!HasWeakHeapObjectTag(p.load(cage_base())));
      CheckForSharedObject(host, p, p.load(cage_base()));
    }
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), CheckForSharedObject(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::compiler::end(), and v8::internal::HasWeakHeapObjectTag().
Member Data Documentation
collector_
MarkCompactCollector* const v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::collector_ [private]
Definition at line 1096 of file mark-compact.cc.
Referenced by CheckForSharedObject().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc