v8::internal::torque::Stack< T > Class Template Reference
#include <utils.h>
Public Types
using value_type = T
Public Member Functions
Stack ()=default
Stack (std::initializer_list< T > initializer)
Stack (std::vector< T > v)
size_t Size () const
const T & Peek (BottomOffset from_bottom) const
void Poke (BottomOffset from_bottom, T x)
void Push (T x)
StackRange TopRange (size_t slot_count) const
StackRange PushMany (const std::vector< T > &v)
const T & Top () const
T Pop ()
std::vector< T > PopMany (size_t count)
BottomOffset AboveTop () const
void DeleteRange (StackRange range)
bool operator== (const Stack &other) const
bool operator!= (const Stack &other) const
T * begin ()
T * end ()
const T * begin () const
const T * end () const
Private Attributes
std::vector< T > elements_
Detailed Description
template<class T>
class v8::internal::torque::Stack< T >
Definition at line 236 of file utils.h.
Member Typedef Documentation
value_type
template<class T >
using v8::internal::torque::Stack< T >::value_type = T
Definition at line 238 of file utils.h.
Constructor & Destructor Documentation
Stack() [1/3]
template<class T >
v8::internal::torque::Stack< T >::Stack () [default]
Stack() [2/3]
template<class T >
v8::internal::torque::Stack< T >::Stack (std::initializer_list< T > initializer) [inline]
Definition at line 240 of file utils.h.
      : Stack(std::vector<T>(initializer)) {}
Stack() [3/3]
template<class T >
v8::internal::torque::Stack< T >::Stack (std::vector< T > v) [inline], [explicit]
Definition at line 242 of file utils.h.
: elements_(std::move(v)) {}
Member Function Documentation
AboveTop()
template<class T >
BottomOffset v8::internal::torque::Stack< T >::AboveTop () const [inline]
Definition at line 280 of file utils.h.
{ return BottomOffset{Size()}; }
References v8::internal::torque::Stack< T >::Size().
Referenced by v8::internal::torque::Stack< T >::DeleteRange(), v8::internal::torque::CCGenerator::EmitGraph(), v8::internal::torque::CSAGenerator::EmitGraph(), v8::internal::torque::Block::MergeInputDefinitions(), v8::internal::torque::Stack< T >::Top(), and v8::internal::torque::Stack< T >::TopRange().
begin() [1/2]
template<class T >
T* v8::internal::torque::Stack< T >::begin () [inline]
Definition at line 298 of file utils.h.
{ return elements_.data(); }
References v8::internal::torque::Stack< T >::elements_.
Referenced by v8::internal::torque::Stack< T >::end(), and v8::internal::torque::Block::SetInputTypes().
begin() [2/2]
template<class T >
const T* v8::internal::torque::Stack< T >::begin () const [inline]
Definition at line 300 of file utils.h.
{ return elements_.data(); }
References v8::internal::torque::Stack< T >::elements_.
DeleteRange()
template<class T >
void v8::internal::torque::Stack< T >::DeleteRange (StackRange range) [inline]
Definition at line 282 of file utils.h.
                                     {
    DCHECK_LE(range.end(), AboveTop());
    if (range.Size() == 0) return;
    for (BottomOffset i = range.end(); i < AboveTop(); ++i) {
      elements_[i.offset - range.Size()] = std::move(elements_[i.offset]);
    }
    elements_.resize(elements_.size() - range.Size());
  }
References v8::internal::torque::Stack< T >::AboveTop(), DCHECK_LE, v8::internal::torque::Stack< T >::elements_, v8::internal::torque::StackRange::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::torque::StackRange::Size().
end() [1/2]
template<class T >
T* v8::internal::torque::Stack< T >::end () [inline]
Definition at line 299 of file utils.h.
{ return begin() + elements_.size(); }
References v8::internal::torque::Stack< T >::begin(), and v8::internal::torque::Stack< T >::elements_.
end() [2/2]
template<class T >
const T* v8::internal::torque::Stack< T >::end () const [inline]
Definition at line 301 of file utils.h.
{ return begin() + elements_.size(); }
References v8::internal::torque::Stack< T >::begin(), and v8::internal::torque::Stack< T >::elements_.
operator!=()
template<class T >
bool v8::internal::torque::Stack< T >::operator!= (const Stack< T > & other) const [inline]
Definition at line 294 of file utils.h.
                                            {
    return elements_ != other.elements_;
  }
References v8::internal::torque::Stack< T >::elements_.
operator==()
template<class T >
bool v8::internal::torque::Stack< T >::operator== (const Stack< T > & other) const [inline]
Definition at line 291 of file utils.h.
                                            {
    return elements_ == other.elements_;
  }
References v8::internal::torque::Stack< T >::elements_.
Peek()
template<class T >
const T& v8::internal::torque::Stack< T >::Peek (BottomOffset from_bottom) const [inline]
Definition at line 244 of file utils.h.
                                                {
    return elements_.at(from_bottom.offset);
  }
References v8::internal::torque::Stack< T >::elements_, and v8::internal::torque::BottomOffset::offset.
Referenced by v8::internal::torque::anonymous_namespace{cc-generator.cc}::CollectAllFields(), v8::internal::torque::CSAGenerator::EmitCSAValue(), v8::internal::torque::CCGenerator::EmitGraph(), v8::internal::torque::CSAGenerator::EmitGraph(), v8::internal::torque::Block::MergeInputDefinitions(), v8::internal::torque::Block::SetInputTypes(), and v8::internal::torque::Stack< T >::Top().
Poke()
template<class T >
void v8::internal::torque::Stack< T >::Poke (BottomOffset from_bottom, T x) [inline]
Definition at line 247 of file utils.h.
                                           {
    elements_.at(from_bottom.offset) = std::move(x);
  }
References v8::internal::torque::Stack< T >::elements_, and v8::internal::torque::BottomOffset::offset.
Pop()
template<class T >
T v8::internal::torque::Stack< T >::Pop () [inline]
Definition at line 264 of file utils.h.
          {
    T result = std::move(elements_.back());
    elements_.pop_back();
    return result;
  }
References v8::internal::torque::Stack< T >::elements_, and v8::base::internal::result.
PopMany()
template<class T >
std::vector<T> v8::internal::torque::Stack< T >::PopMany (size_t count) [inline]
Definition at line 269 of file utils.h.
                                     {
    DCHECK_GE(elements_.size(), count);
    std::vector<T> result;
    result.reserve(count);
    for (auto it = elements_.end() - count; it != elements_.end(); ++it) {
      result.push_back(std::move(*it));
    }
    elements_.resize(elements_.size() - count);
    return result;
  }
References DCHECK_GE, v8::internal::torque::Stack< T >::elements_, and v8::base::internal::result.
Push()
template<class T >
void v8::internal::torque::Stack< T >::Push (T x) [inline]
Definition at line 250 of file utils.h.
                 {
    elements_.push_back(std::move(x));
  }
References v8::internal::torque::Stack< T >::elements_.
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::AddParameter(), v8::internal::torque::CfgAssembler::ComputeInputDefinitions(), v8::internal::torque::ImplementationVisitor::LowerParameter(), v8::internal::torque::Stack< T >::PushMany(), v8::internal::torque::Block::SetInputTypes(), and v8::internal::torque::ImplementationVisitor::Visit().
PushMany()
template<class T >
StackRange v8::internal::torque::Stack< T >::PushMany (const std::vector< T > & v) [inline]
Definition at line 257 of file utils.h.
                                             {
    for (const T& x : v) {
      Push(x);
    }
    return TopRange(v.size());
  }
References v8::internal::torque::Stack< T >::Push(), and v8::internal::torque::Stack< T >::TopRange().
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::AddParameter(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
Size()
template<class T >
size_t v8::internal::torque::Stack< T >::Size () const [inline]
Definition at line 243 of file utils.h.
{ return elements_.size(); }
References v8::internal::torque::Stack< T >::elements_.
Referenced by v8::internal::torque::Stack< T >::AboveTop(), v8::internal::torque::Block::MergeInputDefinitions(), v8::internal::torque::Block::SetInputTypes(), v8::internal::torque::Stack< T >::TopRange(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
Top()
template<class T >
const T& v8::internal::torque::Stack< T >::Top () const [inline]
Definition at line 263 of file utils.h.
{ return Peek(AboveTop() - 1); }
References v8::internal::torque::Stack< T >::AboveTop(), and v8::internal::torque::Stack< T >::Peek().
TopRange()
template<class T >
StackRange v8::internal::torque::Stack< T >::TopRange (size_t slot_count) const [inline]
Definition at line 253 of file utils.h.
                                               {
    DCHECK_GE(Size(), slot_count);
    return StackRange{AboveTop() - slot_count, AboveTop()};
  }
References v8::internal::torque::Stack< T >::AboveTop(), DCHECK_GE, and v8::internal::torque::Stack< T >::Size().
Referenced by v8::internal::torque::ImplementationVisitor::LowerParameter(), and v8::internal::torque::Stack< T >::PushMany().
Member Data Documentation
elements_
template<class T >
std::vector<T> v8::internal::torque::Stack< T >::elements_ [private]
Definition at line 304 of file utils.h.
Referenced by v8::internal::torque::Stack< T >::begin(), v8::internal::torque::Stack< T >::DeleteRange(), v8::internal::torque::Stack< T >::end(), v8::internal::torque::Stack< T >::operator!=(), v8::internal::torque::Stack< T >::operator==(), v8::internal::torque::Stack< T >::Peek(), v8::internal::torque::Stack< T >::Poke(), v8::internal::torque::Stack< T >::Pop(), v8::internal::torque::Stack< T >::PopMany(), v8::internal::torque::Stack< T >::Push(), and v8::internal::torque::Stack< T >::Size().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/utils.h