v8::internal::detail::WaiterQueueNode Class Reference
#include <waiter-queue-node.h>
Public Types
using DequeueMatcher = std::function< bool(WaiterQueueNode *)>
Public Member Functions
virtual ~WaiterQueueNode ()
uint32_t NotifyAllInList ()
virtual void Notify ()=0
virtual bool IsSameIsolateForAsyncCleanup (Isolate *isolate)=0
virtual void CleanupMatchingAsyncWaiters (const DequeueMatcher &matcher)=0
Static Public Member Functions
static void Enqueue (WaiterQueueNode **head, WaiterQueueNode *new_tail)
static WaiterQueueNode * DequeueMatching (WaiterQueueNode **head, const DequeueMatcher &matcher)
static void DequeueAllMatchingForAsyncCleanup (WaiterQueueNode **head, const DequeueMatcher &matcher)
static WaiterQueueNode * Dequeue (WaiterQueueNode **head)
static WaiterQueueNode * Split (WaiterQueueNode **head, uint32_t count)
static int LengthFromHead (WaiterQueueNode *head)
Protected Member Functions
WaiterQueueNode (Isolate *requester)
void SetNotInListForVerification ()
virtual void SetReadyForAsyncCleanup ()=0
Protected Attributes
Isolate * requester_
WaiterQueueNode * next_ = nullptr
WaiterQueueNode * prev_ = nullptr
Private Member Functions
void DequeueUnchecked (WaiterQueueNode **head)
void VerifyNotInList ()
Detailed Description
Definition at line 38 of file waiter-queue-node.h.
Member Typedef Documentation
DequeueMatcher
using v8::internal::detail::WaiterQueueNode::DequeueMatcher = std::function<bool(WaiterQueueNode*)>
Definition at line 45 of file waiter-queue-node.h.
Constructor & Destructor Documentation
 WaiterQueueNode()
v8::internal::detail::WaiterQueueNode::~WaiterQueueNode () [virtual]
Definition at line 17 of file waiter-queue-node.cc.
                                  {
  // Since waiter queue nodes are allocated on the stack, they must be removed
  // from the intrusive linked list once they go out of scope, otherwise there
  // will be dangling pointers.
  VerifyNotInList();
}
References VerifyNotInList().
WaiterQueueNode()
v8::internal::detail::WaiterQueueNode::WaiterQueueNode (Isolate * requester) [explicit], [protected]
Definition at line 15 of file waiter-queue-node.cc.
: requester_(requester) {}
Member Function Documentation
CleanupMatchingAsyncWaiters()
virtual void v8::internal::detail::WaiterQueueNode::CleanupMatchingAsyncWaiters (const DequeueMatcher & matcher) [pure virtual]
Implemented in v8::internal::detail::AsyncWaiterQueueNode< T >, and v8::internal::detail::SyncWaiterQueueNode.
Referenced by v8::internal::JSSynchronizationPrimitive::CleanupAsyncWaiterLists().
Dequeue()
WaiterQueueNode * v8::internal::detail::WaiterQueueNode::Dequeue (WaiterQueueNode ** head) [static]
Definition at line 100 of file waiter-queue-node.cc.
                                                                {
  return DequeueMatching(head, [](WaiterQueueNode* node) { return true; });
}
References DequeueMatching().
Referenced by v8::internal::JSAtomicsMutex::CleanupMatchingAsyncWaiters(), v8::internal::JSAtomicsMutex::HandleAsyncNotify(), v8::internal::JSAtomicsCondition::Notify(), and v8::internal::JSAtomicsMutex::UnlockSlowPath().
DequeueAllMatchingForAsyncCleanup()
void v8::internal::detail::WaiterQueueNode::DequeueAllMatchingForAsyncCleanup (WaiterQueueNode ** head, const DequeueMatcher & matcher) [static]
Definition at line 81 of file waiter-queue-node.cc.
                                                           {
  DCHECK_NOT_NULL(head);
  DCHECK_NOT_NULL(*head);
  WaiterQueueNode* original_tail = (*head)->prev_;
  WaiterQueueNode* cur = *head;
  for (;;) {
    DCHECK_NOT_NULL(cur);
    WaiterQueueNode* next = cur->next_;
    if (matcher(cur)) {
      cur->DequeueUnchecked(head);
      cur->SetReadyForAsyncCleanup();
    }
    if (cur == original_tail) break;
    cur = next;
  }
}
References DCHECK_NOT_NULL, DequeueUnchecked(), next_, prev_, and SetReadyForAsyncCleanup().
Referenced by v8::internal::JSAtomicsMutex::CleanupMatchingAsyncWaiters(), and v8::internal::JSAtomicsCondition::CleanupMatchingAsyncWaiters().
DequeueMatching()
WaiterQueueNode * v8::internal::detail::WaiterQueueNode::DequeueMatching (WaiterQueueNode ** head, const DequeueMatcher & matcher) [static]
Definition at line 65 of file waiter-queue-node.cc.
                                                           {
  DCHECK_NOT_NULL(head);
  DCHECK_NOT_NULL(*head);
  WaiterQueueNode* original_head = *head;
  WaiterQueueNode* cur = *head;
  do {
    if (matcher(cur)) {
      cur->DequeueUnchecked(head);
      return cur;
    }
    cur = cur->next_;
  } while (cur != original_head);
  return nullptr;
}
References DCHECK_NOT_NULL, DequeueUnchecked(), and next_.
Referenced by Dequeue(), v8::internal::JSAtomicsMutex::DequeueTimedOutAsyncWaiter(), v8::internal::JSAtomicsCondition::HandleAsyncTimeout(), v8::internal::JSAtomicsMutex::LockJSMutexOrDequeueTimedOutWaiter(), and v8::internal::JSAtomicsCondition::WaitFor().
DequeueUnchecked()
void v8::internal::detail::WaiterQueueNode::DequeueUnchecked (WaiterQueueNode ** head) [private]
Definition at line 43 of file waiter-queue-node.cc.
                                                             {
  if (next_ == this) {
    // The queue contains exactly 1 node.
    *head = nullptr;
  } else {
    // The queue contains >1 nodes.
    if (this == *head) {
      WaiterQueueNode* tail = (*head)->prev_;
      // The matched node is the head, so next is the new head.
      next_->prev_ = tail;
      tail->next_ = next_;
      *head = next_;
    } else {
      // The matched node is in the middle of the queue, so the head does
      // not need to be updated.
      prev_->next_ = next_;
      next_->prev_ = prev_;
    }
  }
  SetNotInListForVerification();
}
References next_, prev_, and SetNotInListForVerification().
Referenced by DequeueAllMatchingForAsyncCleanup(), and DequeueMatching().
Enqueue()
void v8::internal::detail::WaiterQueueNode::Enqueue (WaiterQueueNode ** head, WaiterQueueNode * new_tail) [static]
Definition at line 25 of file waiter-queue-node.cc.
                                                         {
  DCHECK_NOT_NULL(head);
  new_tail->VerifyNotInList();
  WaiterQueueNode* current_head = *head;
  if (current_head == nullptr) {
    new_tail->next_ = new_tail;
    new_tail->prev_ = new_tail;
    *head = new_tail;
  } else {
    WaiterQueueNode* current_tail = current_head->prev_;
    current_tail->next_ = new_tail;
    current_head->prev_ = new_tail;
    new_tail->next_ = current_head;
    new_tail->prev_ = current_tail;
  }
}
References DCHECK_NOT_NULL, next_, prev_, and VerifyNotInList().
Referenced by v8::internal::JSAtomicsMutex::MaybeEnqueueNode(), and v8::internal::JSAtomicsCondition::QueueWaiter().
IsSameIsolateForAsyncCleanup()
virtual bool v8::internal::detail::WaiterQueueNode::IsSameIsolateForAsyncCleanup (Isolate * isolate) [pure virtual]
Implemented in v8::internal::detail::AsyncWaiterQueueNode< T >, and v8::internal::detail::SyncWaiterQueueNode.
Referenced by v8::internal::JSSynchronizationPrimitive::IsolateDeinit().
LengthFromHead()
int v8::internal::detail::WaiterQueueNode::LengthFromHead (WaiterQueueNode * head) [static]
Definition at line 137 of file waiter-queue-node.cc.
                                                         {
  WaiterQueueNode* cur = head;
  int len = 0;
  do {
    len++;
    cur = cur->next_;
  } while (cur != head);
  return len;
}
References next_.
Referenced by v8::internal::JSSynchronizationPrimitive::NumWaitersForTesting().
Notify()
virtual void v8::internal::detail::WaiterQueueNode::Notify () [pure virtual]
Implemented in v8::internal::detail::AsyncWaiterQueueNode< T >, and v8::internal::detail::SyncWaiterQueueNode.
Referenced by v8::internal::JSAtomicsMutex::CleanupMatchingAsyncWaiters(), v8::internal::JSAtomicsMutex::HandleAsyncNotify(), v8::internal::JSAtomicsCondition::Notify(), NotifyAllInList(), and v8::internal::JSAtomicsMutex::UnlockSlowPath().
NotifyAllInList()
uint32_t v8::internal::detail::WaiterQueueNode::NotifyAllInList ()
Definition at line 147 of file waiter-queue-node.cc.
                                          {
  WaiterQueueNode* cur = this;
  uint32_t count = 0;
  do {
    WaiterQueueNode* next = cur->next_;
    cur->Notify();
    cur = next;
    count++;
  } while (cur != this);
  return count;
}
References next_, and Notify().
Referenced by v8::internal::JSAtomicsCondition::Notify().
SetNotInListForVerification()
void v8::internal::detail::WaiterQueueNode::SetNotInListForVerification () [protected]
Definition at line 164 of file waiter-queue-node.cc.
                                                  {
#ifdef DEBUG
  next_ = prev_ = nullptr;
#endif
}
References next_, and prev_.
Referenced by v8::internal::JSAtomicsMutex::CleanupMatchingAsyncWaiters(), v8::internal::JSAtomicsCondition::CleanupMatchingAsyncWaiters(), and DequeueUnchecked().
SetReadyForAsyncCleanup()
virtual void v8::internal::detail::WaiterQueueNode::SetReadyForAsyncCleanup () [protected], [pure virtual]
Implemented in v8::internal::detail::AsyncWaiterQueueNode< T >, and v8::internal::detail::SyncWaiterQueueNode.
Referenced by DequeueAllMatchingForAsyncCleanup().
Split()
WaiterQueueNode * v8::internal::detail::WaiterQueueNode::Split (WaiterQueueNode ** head, uint32_t count) [static]
Definition at line 105 of file waiter-queue-node.cc.
                                                        {
  DCHECK_GT(count, 0);
  DCHECK_NOT_NULL(head);
  DCHECK_NOT_NULL(*head);
  WaiterQueueNode* front_head = *head;
  WaiterQueueNode* back_head = front_head;
  uint32_t actual_count = 0;
  while (actual_count < count) {
    back_head = back_head->next_;
    // The queue is shorter than the requested count, return the whole queue.
    if (back_head == front_head) {
      *head = nullptr;
      return front_head;
    }
    actual_count++;
  }
  WaiterQueueNode* front_tail = back_head->prev_;
  WaiterQueueNode* back_tail = front_head->prev_;
  // Fix up the back list (i.e. remainder of the list).
  back_head->prev_ = back_tail;
  back_tail->next_ = back_head;
  *head = back_head;
  // Fix up and return the front list (i.e. the dequeued list).
  front_head->prev_ = front_tail;
  front_tail->next_ = front_head;
  return front_head;
}
References DCHECK_GT, DCHECK_NOT_NULL, next_, and prev_.
Referenced by v8::internal::JSAtomicsCondition::Notify().
VerifyNotInList()
void v8::internal::detail::WaiterQueueNode::VerifyNotInList () [private]
Definition at line 159 of file waiter-queue-node.cc.
                                      {
  DCHECK_NULL(next_);
  DCHECK_NULL(prev_);
}
References DCHECK_NULL, next_, and prev_.
Referenced by Enqueue(), and ~WaiterQueueNode().
Member Data Documentation
next_
WaiterQueueNode* v8::internal::detail::WaiterQueueNode::next_ = nullptr [protected]
Definition at line 85 of file waiter-queue-node.h.
Referenced by DequeueAllMatchingForAsyncCleanup(), DequeueMatching(), DequeueUnchecked(), Enqueue(), LengthFromHead(), NotifyAllInList(), SetNotInListForVerification(), Split(), and VerifyNotInList().
prev_
WaiterQueueNode* v8::internal::detail::WaiterQueueNode::prev_ = nullptr [protected]
Definition at line 86 of file waiter-queue-node.h.
Referenced by DequeueAllMatchingForAsyncCleanup(), DequeueUnchecked(), Enqueue(), SetNotInListForVerification(), Split(), and VerifyNotInList().
requester_
Isolate* v8::internal::detail::WaiterQueueNode::requester_ [protected]
Definition at line 82 of file waiter-queue-node.h.
Referenced by v8::internal::JSAtomicsMutex::HandleAsyncNotify(), v8::internal::JSAtomicsCondition::HandleAsyncNotify(), v8::internal::JSAtomicsMutex::HandleAsyncTimeout(), v8::internal::JSAtomicsCondition::HandleAsyncTimeout(), and v8::internal::detail::AsyncWaiterQueueNode< T >::RemoveFromAsyncWaiterQueueList().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/waiter-queue-node.h
/mnt/V8SourceCode/src/objects/waiter-queue-node.cc