v8::internal::compiler::turboshaft::GrowableStacksReducer< Next > Class Template Reference
#include <growable-stacks-reducer.h>
Public Member Functions
GrowableStacksReducer ()
V< None > REDUCE() WasmStackCheck (WasmStackCheckOp::Kind kind)
OpIndex REDUCE() Return (V< Word32 > pop_count, base::Vector< const OpIndex > return_values, bool spill_caller_frame_slots)
Private Attributes
bool skip_reducer_ = false
CallDescriptor * call_descriptor_ = nullptr
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >
Definition at line 22 of file growable-stacks-reducer.h.
Constructor & Destructor Documentation
GrowableStacksReducer()
template<class Next >
v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::GrowableStacksReducer () [inline]
Definition at line 26 of file growable-stacks-reducer.h.
                          {
    if (!__ data()->wasm_module_sig() ||
        !v8_flags.experimental_wasm_growable_stacks) {
      // We are not compiling a wasm function if there is no signature.
      skip_reducer_ = true;
      return;
    }
    call_descriptor_ = compiler::GetWasmCallDescriptor(
        __ graph_zone(), __ data()->wasm_module_sig());
#if V8_TARGET_ARCH_32_BIT
    call_descriptor_ =
        compiler::GetI32WasmCallDescriptor(__ graph_zone(), call_descriptor_);
#endif
  }
References __, v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::call_descriptor_, v8::internal::compiler::GetWasmCallDescriptor(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::skip_reducer_, and v8::internal::v8_flags.
Member Function Documentation
Return()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return (V< Word32 > pop_count, base::Vector< const OpIndex > return_values, bool spill_caller_frame_slots) [inline]
Definition at line 75 of file growable-stacks-reducer.h.
                                                        {
    if (skip_reducer_ || !spill_caller_frame_slots ||
        call_descriptor_->ReturnSlotCount() == 0) {
      return Next::ReduceReturn(pop_count, return_values,
                                spill_caller_frame_slots);
    }
    V<Word32> frame_marker = __ Load(
        __ FramePointer(), LoadOp::Kind::RawAligned(),
        MemoryRepresentation::Uint32(), WasmFrameConstants::kFrameTypeOffset);
    Label<WordPtr> done(this);
    IF (UNLIKELY(__ Word32Equal(
            frame_marker,
            StackFrame::TypeToMarker(StackFrame::WASM_SEGMENT_START)))) {
      auto sig =
          FixedSizeSignature<MachineType>::Returns(MachineType::Pointer())
              .Params(MachineType::Pointer());
      const CallDescriptor* ccall_descriptor =
          compiler::Linkage::GetSimplifiedCDescriptor(__ graph_zone(), &sig);
      const TSCallDescriptor* ts_ccall_descriptor = TSCallDescriptor::Create(
          ccall_descriptor, compiler::CanThrow::kNo,
          compiler::LazyDeoptOnThrow::kNo, __ graph_zone());
      GOTO(done, __ template Call<WordPtr>(
                     __ ExternalConstant(ExternalReference::wasm_load_old_fp()),
                     OpIndex::Invalid(),
                     base::VectorOf({__ ExternalConstant(
                         ExternalReference::isolate_address())}),
                     ts_ccall_descriptor));
    } ELSE {
      GOTO(done, __ FramePointer());
    }
    BIND(done, old_fp);
    base::SmallVector<OpIndex, 8> register_return_values;
    for (size_t i = 0; i < call_descriptor_->ReturnCount(); i++) {
      LinkageLocation loc = call_descriptor_->GetReturnLocation(i);
      if (!loc.IsCallerFrameSlot()) {
        register_return_values.push_back(return_values[i]);
        continue;
      }
      MemoryRepresentation mem_rep =
          MemoryRepresentation::FromMachineType(loc.GetType());
      OpIndex ret_value = return_values[i];
      // Pointers are stored uncompressed on the stacks.
      // Also, we don't need to mark the stack slot as a reference, because
      // we are about to return from this frame, so it is the caller's
      // responsibility to track the tagged return values using the signature.
      if (mem_rep == MemoryRepresentation::AnyTagged()) {
        mem_rep = MemoryRepresentation::UintPtr();
        ret_value = __ BitcastTaggedToWordPtr(ret_value);
      }
      __ StoreOffHeap(old_fp, ret_value, mem_rep,
                      FrameSlotToFPOffset(loc.GetLocation()));
    }
    return Next::ReduceReturn(pop_count, base::VectorOf(register_return_values),
                              spill_caller_frame_slots);
  }
References __, v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::call_descriptor_, v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::FrameSlotToFPOffset(), v8::internal::compiler::turboshaft::MemoryRepresentation::FromMachineType(), v8::internal::compiler::CallDescriptor::GetReturnLocation(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::ExternalReference::isolate_address(), v8::internal::compiler::kNo, v8::Load(), v8::internal::loc, v8::internal::MachineType::Pointer(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::compiler::CallDescriptor::ReturnCount(), v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::Returns(), v8::internal::compiler::CallDescriptor::ReturnSlotCount(), v8::internal::sig, v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::skip_reducer_, v8::internal::StackFrame::TypeToMarker(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr(), v8::base::VectorOf(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
WasmStackCheck()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::WasmStackCheck (WasmStackCheckOp::Kind kind) [inline]
Definition at line 41 of file growable-stacks-reducer.h.
                                                            {
    CHECK_EQ(kind, WasmStackCheckOp::Kind::kFunctionEntry);
    if (skip_reducer_) {
      return Next::ReduceWasmStackCheck(kind);
    }
    // Loads of the stack limit should not be load-eliminated as it can be
    // modified by another thread.
    V<WordPtr> limit = __ Load(
        __ LoadRootRegister(), LoadOp::Kind::RawAligned().NotLoadEliminable(),
        MemoryRepresentation::UintPtr(), IsolateData::jslimit_offset());
    IF_NOT (LIKELY(__ StackPointerGreaterThan(limit, StackCheckKind::kWasm))) {
      const int stack_parameter_count = 0;
      const CallDescriptor* stub_call_descriptor =
          compiler::Linkage::GetStubCallDescriptor(
              __ graph_zone(), WasmGrowableStackGuardDescriptor{},
              stack_parameter_count, CallDescriptor::kNoFlags,
              Operator::kNoProperties, StubCallMode::kCallWasmRuntimeStub);
      const TSCallDescriptor* ts_stub_call_descriptor =
          TSCallDescriptor::Create(stub_call_descriptor,
                                   compiler::CanThrow::kNo,
                                   LazyDeoptOnThrow::kNo, __ graph_zone());
      V<WordPtr> builtin =
          __ RelocatableWasmBuiltinCallTarget(Builtin::kWasmGrowableStackGuard);
      auto param_slots_size = __ IntPtrConstant(
          call_descriptor_->ParameterSlotCount() * kSystemPointerSize);
      __ Call(
          builtin, {param_slots_size}, ts_stub_call_descriptor,
          OpEffects().CanReadMemory().RequiredWhenUnused().CanCreateIdentity());
    }
    return V<None>::Invalid();
  }
References __, v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::call_descriptor_, v8::internal::compiler::turboshaft::OpEffects::CanCreateIdentity(), v8::internal::compiler::turboshaft::OpEffects::CanReadMemory(), CHECK_EQ, v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::turboshaft::V< T >::Invalid(), v8::internal::IsolateData::jslimit_offset(), v8::internal::compiler::kNo, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, v8::internal::kSystemPointerSize, v8::internal::compiler::kWasm, v8::Load(), v8::internal::compiler::CallDescriptor::ParameterSlotCount(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::compiler::turboshaft::OpEffects::RequiredWhenUnused(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::skip_reducer_, and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
Member Data Documentation
call_descriptor_
template<class Next >
CallDescriptor* v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::call_descriptor_ = nullptr [private]
Definition at line 137 of file growable-stacks-reducer.h.
Referenced by v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::GrowableStacksReducer(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), and v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::WasmStackCheck().
skip_reducer_
template<class Next >
bool v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::skip_reducer_ = false [private]
Definition at line 136 of file growable-stacks-reducer.h.
Referenced by v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::GrowableStacksReducer(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), and v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::WasmStackCheck().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/growable-stacks-reducer.h