v8::Private Class Reference
A private symbol.
#include <v8-object.h>
Public Member Functions
Local< Value > Name () const
Returns the print name string of the private symbol, or undefined if none.
Static Public Member Functions
static Local< Private > New (Isolate *isolate, Local< String > name=Local< String >())
Create a private symbol.
static Local< Private > ForApi (Isolate *isolate, Local< String > name)
Retrieve a global private symbol.
static Private * Cast (Data *data)
Private Member Functions
Private ()
Static Private Member Functions
static void CheckCast (Data *that)
Detailed Description
A private symbol.
This is an experimental feature. Use at your own risk.
Definition at line 33 of file v8-object.h.
Constructor & Destructor Documentation
Private()
v8::Private::Private () [private]
Member Function Documentation
Cast()
Private * v8::Private::Cast (Data * data) [inline], [static]
Definition at line 1171 of file v8-object.h.
                                 {
#ifdef V8_ENABLE_CHECKS
  CheckCast(data);
#endif
  return reinterpret_cast<Private*>(data);
}
References CheckCast().
CheckCast()
void v8::Private::CheckCast (v8::Data * that) [static], [private]
Definition at line 3898 of file api.cc.
                                      {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(IsSymbol(*obj) && i::Cast<i::Symbol>(obj)->is_private(),
                  "v8::Private::Cast", "Value is not a Private");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Referenced by Cast().
ForApi()
Local< Private > v8::Private::ForApi (Isolate * isolate, Local< String > name) [static]
Retrieve a global private symbol.
If a symbol with this name has not been retrieved in the same isolate before, it is created. Note that private symbols created this way are never collected, so they should only be used for statically fixed properties. Also, there is only one global name space for the names used as keys. To minimize the potential for clashes, use qualified names as keys, e.g., `Class#property`.
Definition at line 9521 of file api.cc.
                                                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  auto i_name = Utils::OpenHandle(*name);
  Local<Symbol> result = Utils::ToLocal(
      i_isolate->SymbolFor(i::RootIndex::kApiPrivateSymbolTable, i_name, true));
  return result.UnsafeAs<Private>();
}
References name, v8::Utils::OpenHandle(), v8::base::internal::result, and v8::internal::Isolate::SymbolFor().
Name()
Local< Value > v8::Private::Name () const
Returns the print name string of the private symbol, or undefined if none.
Definition at line 6175 of file api.cc.
                                 {
  const Symbol* sym = reinterpret_cast<const Symbol*>(this);
  auto i_sym = Utils::OpenDirectHandle(sym);
  // v8::Private symbols are created by API and are therefore writable, so we
  // can always recover an Isolate.
  i::Isolate* i_isolate = i::GetIsolateFromWritableObject(*i_sym);
  return sym->Description(reinterpret_cast<Isolate*>(i_isolate));
}
References v8::Symbol::Description(), v8::internal::GetIsolateFromWritableObject(), and v8::Utils::OpenDirectHandle().
New()
Local< Private > v8::Private::New (Isolate * isolate, Local< String > name = Local<String>()) [static]
Create a private symbol.
If name is not empty, it will be the description.
Definition at line 9511 of file api.cc.
                                                                     {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Private_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::Symbol> symbol = i_isolate->factory()->NewPrivateSymbol();
  if (!name.IsEmpty()) symbol->set_description(*Utils::OpenDirectHandle(*name));
  Local<Symbol> result = Utils::ToLocal(symbol);
  return result.UnsafeAs<Private>();
}
References v8::internal::Isolate::factory(), name, v8::internal::Factory::NewPrivateSymbol(), v8::Utils::OpenDirectHandle(), and v8::base::internal::result.
Referenced by v8::AsyncHooks::AsyncHooks(), and v8_inspector::V8Console::taskInfoKey().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-object.h
/mnt/V8SourceCode/src/api/api.cc