v8::internal::JSDate Class Reference
#include <js-objects.h>
Classes
class BodyDescriptor
Public Types
enum FieldIndex {
kYear
, kMonth
, kDay
, kWeekday
,
kHour
, kMinute
, kSecond
, kFirstUncachedField
,
kMillisecond = kFirstUncachedField
, kDays
, kTimeInDay
, kFirstUTCField
,
kYearUTC = kFirstUTCField
, kMonthUTC
, kDayUTC
, kWeekdayUTC
,
kHourUTC
, kMinuteUTC
, kSecondUTC
, kMillisecondUTC
,
kDaysUTC
, kTimeInDayUTC
, kTimezoneOffset
 }
Public Member Functions
void SetValue (Isolate *isolate, double v)
void SetNanValue ()
void UpdateFieldsAfterDeserialization (Isolate *isolate)
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSDate > New (Isolate *isolate, DirectHandle< JSFunction > constructor, DirectHandle< JSReceiver > new_target, double tv)
static int64_t CurrentTimeValue (Isolate *isolate)
static Address GetField (Isolate *isolate, Address raw_date, Address smi_index)
Private Member Functions
Tagged< Object > DoGetField (Isolate *isolate, FieldIndex index)
Tagged< Object > GetUTCField (FieldIndex index, double value, DateCache *date_cache)
void SetCachedFields (Isolate *isolate, int64_t local_time_ms, DateCache *date_cache)
Detailed Description
Definition at line 1235 of file js-objects.h.
Member Enumeration Documentation
FieldIndex
enum v8::internal::JSDate::FieldIndex
Enumerator
kYear
kMonth
kDay
kWeekday
kHour
kMinute
kSecond
kFirstUncachedField
kMillisecond
kDays
kTimeInDay
kFirstUTCField
kYearUTC
kMonthUTC
kDayUTC
kWeekdayUTC
kHourUTC
kMinuteUTC
kSecondUTC
kMillisecondUTC
kDaysUTC
kTimeInDayUTC
kTimezoneOffset
Definition at line 1265 of file js-objects.h.
                  {
    kYear,
    kMonth,
    kDay,
    kWeekday,
    kHour,
    kMinute,
    kSecond,
    kFirstUncachedField,
    kMillisecond = kFirstUncachedField,
    kDays,
    kTimeInDay,
    kFirstUTCField,
    kYearUTC = kFirstUTCField,
    kMonthUTC,
    kDayUTC,
    kWeekdayUTC,
    kHourUTC,
    kMinuteUTC,
    kSecondUTC,
    kMillisecondUTC,
    kDaysUTC,
    kTimeInDayUTC,
    kTimezoneOffset
  };
Member Function Documentation
CurrentTimeValue()
int64_t v8::internal::JSDate::CurrentTimeValue (Isolate * isolate) [static]
Definition at line 5723 of file js-objects.cc.
                                                 {
  if (v8_flags.log_timer_events) LOG(isolate, CurrentTimeEvent());
  if (v8_flags.correctness_fuzzer_suppressions) return 4;
  // According to ECMA-262, section 15.9.1, page 117, the precision of
  // the number in a Date object representing a particular instant in
  // time is milliseconds. Therefore, we floor the result of getting
  // the OS time.
  return V8::GetCurrentPlatform()->CurrentClockTimeMilliseconds();
}
References v8::Platform::CurrentClockTimeMilliseconds(), v8::internal::V8::GetCurrentPlatform(), LOG, and v8::internal::v8_flags.
Referenced by v8::internal::BUILTIN(), v8::internal::JSDateTimeFormat::DateTimeFormat(), v8::internal::JSDateTimeFormat::FormatToParts(), v8::internal::anonymous_namespace{js-date-time-format.cc}::HandleDateTimeOthers(), and v8::internal::RUNTIME_FUNCTION().
DoGetField()
Tagged< Object > v8::internal::JSDate::DoGetField (Isolate * isolate, FieldIndex index) [private]
Definition at line 5749 of file js-objects.cc.
                                                                    {
  DateCache* date_cache = isolate->date_cache();
  if (index < kFirstUncachedField) {
    Tagged<Object> stamp = cache_stamp();
    if (stamp != isolate->date_cache_stamp() && IsSmi(stamp)) {
      // Since the stamp is not NaN, the value is also not NaN.
      int64_t local_time_ms =
          date_cache->ToLocal(static_cast<int64_t>(value()));
      SetCachedFields(isolate, local_time_ms, date_cache);
    }
    switch (index) {
      case kYear:
        return year();
      case kMonth:
        return month();
      case kDay:
        return day();
      case kWeekday:
        return weekday();
      case kHour:
        return hour();
      case kMinute:
        return min();
      case kSecond:
        return sec();
      default:
        UNREACHABLE();
    }
  }
  if (index >= kFirstUTCField) {
    return GetUTCField(index, value(), date_cache);
  }
  double time = value();
  if (std::isnan(time)) return GetReadOnlyRoots().nan_value();
  int64_t local_time_ms = date_cache->ToLocal(static_cast<int64_t>(time));
  int days = DateCache::DaysFromTime(local_time_ms);
  if (index == kDays) return Smi::FromInt(days);
  int time_in_day_ms = DateCache::TimeInDay(local_time_ms, days);
  if (index == kMillisecond) return Smi::FromInt(time_in_day_ms % 1000);
  DCHECK_EQ(index, kTimeInDay);
  return Smi::FromInt(time_in_day_ms);
}
References v8::internal::Isolate::date_cache(), v8::internal::Isolate::date_cache_stamp(), v8::internal::DateCache::DaysFromTime(), DCHECK_EQ, v8::internal::Smi::FromInt(), v8::internal::GetReadOnlyRoots(), GetUTCField(), v8::internal::index, v8::internal::IsSmi(), kDay, kDays, kFirstUncachedField, kFirstUTCField, kHour, kMillisecond, kMinute, kMonth, kSecond, kTimeInDay, kWeekday, kYear, SetCachedFields(), v8::internal::time, v8::internal::DateCache::TimeInDay(), v8::internal::DateCache::ToLocal(), v8::internal::UNREACHABLE(), and v8::internal::value.
GetField()
Address v8::internal::JSDate::GetField (Isolate * isolate, Address raw_date, Address smi_index) [static]
Definition at line 5735 of file js-objects.cc.
                                            {
  // Called through CallCFunction.
  DisallowGarbageCollection no_gc;
  DisallowHandleAllocation no_handles;
  DisallowJavascriptExecution no_js(isolate);
  Tagged<Object> object(raw_object);
  Tagged<Smi> index(smi_index);
  return Cast<JSDate>(object)
      ->DoGetField(isolate, static_cast<FieldIndex>(index.value()))
      .ptr();
}
References v8::internal::index, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetUTCField()
Tagged< Object > v8::internal::JSDate::GetUTCField (FieldIndex index, double value, DateCache * date_cache) [private]
Definition at line 5798 of file js-objects.cc.
                                                          {
  DCHECK_GE(index, kFirstUTCField);
  if (std::isnan(value)) return GetReadOnlyRoots().nan_value();
  int64_t time_ms = static_cast<int64_t>(value);
  if (index == kTimezoneOffset) {
    return Smi::FromInt(date_cache->TimezoneOffset(time_ms));
  }
  int days = DateCache::DaysFromTime(time_ms);
  if (index == kWeekdayUTC) return Smi::FromInt(date_cache->Weekday(days));
  if (index <= kDayUTC) {
    int year, month, day;
    date_cache->YearMonthDayFromDays(days, &year, &month, &day);
    if (index == kYearUTC) return Smi::FromInt(year);
    if (index == kMonthUTC) return Smi::FromInt(month);
    DCHECK_EQ(index, kDayUTC);
    return Smi::FromInt(day);
  }
  int time_in_day_ms = DateCache::TimeInDay(time_ms, days);
  switch (index) {
    case kHourUTC:
      return Smi::FromInt(time_in_day_ms / (60 * 60 * 1000));
    case kMinuteUTC:
      return Smi::FromInt((time_in_day_ms / (60 * 1000)) % 60);
    case kSecondUTC:
      return Smi::FromInt((time_in_day_ms / 1000) % 60);
    case kMillisecondUTC:
      return Smi::FromInt(time_in_day_ms % 1000);
    case kDaysUTC:
      return Smi::FromInt(days);
    case kTimeInDayUTC:
      return Smi::FromInt(time_in_day_ms);
    default:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::DateCache::DaysFromTime(), DCHECK_EQ, DCHECK_GE, v8::internal::Smi::FromInt(), v8::internal::GetReadOnlyRoots(), v8::internal::index, kDaysUTC, kDayUTC, kFirstUTCField, kHourUTC, kMillisecondUTC, kMinuteUTC, kMonthUTC, kSecondUTC, kTimeInDayUTC, kTimezoneOffset, kWeekdayUTC, kYearUTC, v8::internal::DateCache::TimeInDay(), v8::internal::DateCache::TimezoneOffset(), v8::internal::UNREACHABLE(), v8::internal::value, v8::internal::DateCache::Weekday(), and v8::internal::DateCache::YearMonthDayFromDays().
Referenced by DoGetField().
New()
MaybeDirectHandle< JSDate > v8::internal::JSDate::New (Isolate * isolate, DirectHandle< JSFunction > constructor, DirectHandle< JSReceiver > new_target, double tv) [static]
Definition at line 5706 of file js-objects.cc.
                                                 {
  DirectHandle<JSDate> result;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, result,
      Cast<JSDate>(JSObject::New(constructor, new_target, {})));
  if (DateCache::TryTimeClip(&tv)) {
    result->SetValue(isolate, tv);
  } else {
    result->SetNanValue();
  }
  return result;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::JSObject::New(), v8::base::internal::result, and v8::internal::DateCache::TryTimeClip().
Referenced by v8::internal::BUILTIN(), v8::Date::New(), v8::Date::Parse(), and v8::internal::ValueDeserializer::ReadJSDate().
SetCachedFields()
void v8::internal::JSDate::SetCachedFields (Isolate * isolate, int64_t local_time_ms, DateCache * date_cache) [inline], [private]
Definition at line 5886 of file js-objects.cc.
                                                    {
  int days = DateCache::DaysFromTime(local_time_ms);
  int time_in_day_ms = DateCache::TimeInDay(local_time_ms, days);
  int year, month, day;
  date_cache->YearMonthDayFromDays(days, &year, &month, &day);
  int weekday = date_cache->Weekday(days);
  int hour = time_in_day_ms / (60 * 60 * 1000);
  int min = (time_in_day_ms / (60 * 1000)) % 60;
  int sec = (time_in_day_ms / 1000) % 60;
  set_cache_stamp(isolate->GetDateCacheStampAndRecordUsage(),
                  SKIP_WRITE_BARRIER);
  set_year(Smi::FromInt(year), SKIP_WRITE_BARRIER);
  set_month(Smi::FromInt(month), SKIP_WRITE_BARRIER);
  set_day(Smi::FromInt(day), SKIP_WRITE_BARRIER);
  set_weekday(Smi::FromInt(weekday), SKIP_WRITE_BARRIER);
  set_hour(Smi::FromInt(hour), SKIP_WRITE_BARRIER);
  set_min(Smi::FromInt(min), SKIP_WRITE_BARRIER);
  set_sec(Smi::FromInt(sec), SKIP_WRITE_BARRIER);
}
References v8::internal::DateCache::DaysFromTime(), v8::internal::Smi::FromInt(), v8::internal::Isolate::GetDateCacheStampAndRecordUsage(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::DateCache::TimeInDay(), v8::internal::DateCache::Weekday(), and v8::internal::DateCache::YearMonthDayFromDays().
Referenced by DoGetField(), SetValue(), and UpdateFieldsAfterDeserialization().
SetNanValue()
void v8::internal::JSDate::SetNanValue ()
Definition at line 5860 of file js-objects.cc.
                         {
  set_value(std::numeric_limits<double>::quiet_NaN());
  Tagged<HeapNumber> nan = GetReadOnlyRoots().nan_value();
  set_cache_stamp(nan, SKIP_WRITE_BARRIER);
  set_year(nan, SKIP_WRITE_BARRIER);
  set_month(nan, SKIP_WRITE_BARRIER);
  set_day(nan, SKIP_WRITE_BARRIER);
  set_hour(nan, SKIP_WRITE_BARRIER);
  set_min(nan, SKIP_WRITE_BARRIER);
  set_sec(nan, SKIP_WRITE_BARRIER);
  set_weekday(nan, SKIP_WRITE_BARRIER);
}
References v8::internal::GetReadOnlyRoots(), and v8::internal::SKIP_WRITE_BARRIER.
SetValue()
void v8::internal::JSDate::SetValue (Isolate * isolate, double v)
Definition at line 5845 of file js-objects.cc.
                                                    {
#ifdef DEBUG
  DCHECK(!std::isnan(value));
  double clipped_value = value;
  DCHECK(DateCache::TryTimeClip(&clipped_value));
  DCHECK_EQ(value, clipped_value);
#endif
  set_value(value);
  DateCache* date_cache = isolate->date_cache();
  // Since the stamp is not NaN, the value is also not NaN.
  int64_t local_time_ms = date_cache->ToLocal(static_cast<int64_t>(value));
  SetCachedFields(isolate, local_time_ms, date_cache);
}
References v8::internal::Isolate::date_cache(), v8::internal::DCHECK(), DCHECK_EQ, SetCachedFields(), v8::internal::DateCache::ToLocal(), v8::internal::DateCache::TryTimeClip(), and v8::internal::value.
UpdateFieldsAfterDeserialization()
void v8::internal::JSDate::UpdateFieldsAfterDeserialization (Isolate * isolate)
Definition at line 5874 of file js-objects.cc.
                                                              {
  double time = value();
  if (std::isnan(time)) {
    // In this case all the cached fields are set to NaNs, thus no updates
    // necessary.
    return;
  }
  DateCache* date_cache = isolate->date_cache();
  int64_t local_time_ms = date_cache->ToLocal(static_cast<int64_t>(time));
  SetCachedFields(isolate, local_time_ms, date_cache);
}
References v8::internal::Isolate::date_cache(), SetCachedFields(), v8::internal::time, v8::internal::DateCache::ToLocal(), and v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-objects.h
/mnt/V8SourceCode/src/objects/js-objects.cc