v8::internal::interpreter::TryFinallyBuilder Class Reference
#include <control-flow-builders.h>
Public Member Functions
TryFinallyBuilder (BytecodeArrayBuilder *builder, BlockCoverageBuilder *block_coverage_builder, TryFinallyStatement *statement, HandlerTable::CatchPrediction catch_prediction)
~TryFinallyBuilder () override
void BeginTry (Register context)
void LeaveTry ()
void EndTry ()
void BeginHandler ()
void BeginFinally ()
void EndFinally ()
Private Attributes
int handler_id_
HandlerTable::CatchPrediction catch_prediction_
BytecodeLabel handler_
BytecodeLabels finalization_sites_
BlockCoverageBuilder * block_coverage_builder_
TryFinallyStatement * statement_
Additional Inherited Members
Detailed Description
Definition at line 230 of file control-flow-builders.h.
Constructor & Destructor Documentation
TryFinallyBuilder()
v8::internal::interpreter::TryFinallyBuilder::TryFinallyBuilder (BytecodeArrayBuilder * builder, BlockCoverageBuilder * block_coverage_builder, TryFinallyStatement * statement, HandlerTable::CatchPrediction catch_prediction) [inline]
Definition at line 232 of file control-flow-builders.h.
      : ControlFlowBuilder(builder),
        handler_id_(builder->NewHandlerEntry()),
        catch_prediction_(catch_prediction),
        finalization_sites_(builder->zone()),
        block_coverage_builder_(block_coverage_builder),
        statement_(statement) {}
 TryFinallyBuilder()
v8::internal::interpreter::TryFinallyBuilder::~TryFinallyBuilder () [override]
Definition at line 173 of file control-flow-builders.cc.
                                      {
  if (block_coverage_builder_ != nullptr) {
    block_coverage_builder_->IncrementBlockCounter(
        statement_, SourceRangeKind::kContinuation);
  }
}
References block_coverage_builder_, v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter(), v8::internal::kContinuation, and statement_.
Member Function Documentation
BeginFinally()
void v8::internal::interpreter::TryFinallyBuilder::BeginFinally ()
Definition at line 200 of file control-flow-builders.cc.
                                     {
  finalization_sites_.Bind(builder());
  if (block_coverage_builder_ != nullptr) {
    block_coverage_builder_->IncrementBlockCounter(statement_,
                                                   SourceRangeKind::kFinally);
  }
}
References v8::internal::interpreter::BytecodeLabels::Bind(), block_coverage_builder_, v8::internal::interpreter::ControlFlowBuilder::builder(), finalization_sites_, v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter(), v8::internal::kFinally, and statement_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildTryFinally().
BeginHandler()
void v8::internal::interpreter::TryFinallyBuilder::BeginHandler ()
Definition at line 195 of file control-flow-builders.cc.
                                     {
  builder()->Bind(&handler_);
  builder()->MarkHandler(handler_id_, catch_prediction_);
}
References v8::internal::interpreter::BytecodeArrayBuilder::Bind(), v8::internal::interpreter::ControlFlowBuilder::builder(), catch_prediction_, handler_, handler_id_, and v8::internal::interpreter::BytecodeArrayBuilder::MarkHandler().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildTryFinally().
BeginTry()
void v8::internal::interpreter::TryFinallyBuilder::BeginTry (Register context)
Definition at line 180 of file control-flow-builders.cc.
                                                 {
  builder()->MarkTryBegin(handler_id_, context);
}
References v8::internal::interpreter::ControlFlowBuilder::builder(), handler_id_, and v8::internal::interpreter::BytecodeArrayBuilder::MarkTryBegin().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildTryFinally().
EndFinally()
void v8::internal::interpreter::TryFinallyBuilder::EndFinally ()
Definition at line 209 of file control-flow-builders.cc.
                                   {
  // Nothing to be done here.
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildTryFinally().
EndTry()
void v8::internal::interpreter::TryFinallyBuilder::EndTry ()
Definition at line 190 of file control-flow-builders.cc.
                               {
  builder()->MarkTryEnd(handler_id_);
}
References v8::internal::interpreter::ControlFlowBuilder::builder(), handler_id_, and v8::internal::interpreter::BytecodeArrayBuilder::MarkTryEnd().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildTryFinally().
LeaveTry()
void v8::internal::interpreter::TryFinallyBuilder::LeaveTry ()
Definition at line 185 of file control-flow-builders.cc.
                                 {
  builder()->Jump(finalization_sites_.New());
}
References v8::internal::interpreter::ControlFlowBuilder::builder(), finalization_sites_, v8::internal::interpreter::BytecodeArrayBuilder::Jump(), and v8::internal::interpreter::BytecodeLabels::New().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildTryFinally(), and v8::internal::interpreter::BytecodeGenerator::ControlScopeForTryFinally::Execute().
Member Data Documentation
block_coverage_builder_
BlockCoverageBuilder* v8::internal::interpreter::TryFinallyBuilder::block_coverage_builder_ [private]
Definition at line 260 of file control-flow-builders.h.
Referenced by BeginFinally(), and ~TryFinallyBuilder().
catch_prediction_
HandlerTable::CatchPrediction v8::internal::interpreter::TryFinallyBuilder::catch_prediction_ [private]
Definition at line 254 of file control-flow-builders.h.
Referenced by BeginHandler().
finalization_sites_
BytecodeLabels v8::internal::interpreter::TryFinallyBuilder::finalization_sites_ [private]
Definition at line 258 of file control-flow-builders.h.
Referenced by BeginFinally(), and LeaveTry().
handler_
BytecodeLabel v8::internal::interpreter::TryFinallyBuilder::handler_ [private]
Definition at line 255 of file control-flow-builders.h.
Referenced by BeginHandler().
handler_id_
int v8::internal::interpreter::TryFinallyBuilder::handler_id_ [private]
Definition at line 253 of file control-flow-builders.h.
Referenced by BeginHandler(), BeginTry(), and EndTry().
statement_
TryFinallyStatement* v8::internal::interpreter::TryFinallyBuilder::statement_ [private]
Definition at line 261 of file control-flow-builders.h.
Referenced by BeginFinally(), and ~TryFinallyBuilder().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/control-flow-builders.h
/mnt/V8SourceCode/src/interpreter/control-flow-builders.cc