v8::internal::Scanner::BookmarkScope Class Reference
#include <scanner.h>
Public Member Functions
BookmarkScope (Scanner *scanner)
~BookmarkScope ()=default
BookmarkScope (const BookmarkScope &)=delete
BookmarkScope & operator= (const BookmarkScope &)=delete
void Set (size_t bookmark)
void Apply ()
bool HasBeenSet () const
bool HasBeenApplied () const
Private Attributes
Scanner * scanner_
size_t bookmark_
bool had_parser_error_
Static Private Attributes
static const size_t kNoBookmark
static const size_t kBookmarkWasApplied
Detailed Description
Definition at line 218 of file scanner.h.
Constructor & Destructor Documentation
BookmarkScope() [1/2]
v8::internal::Scanner::BookmarkScope::BookmarkScope (Scanner * scanner) [inline], [explicit]
Definition at line 220 of file scanner.h.
        : scanner_(scanner),
          bookmark_(kNoBookmark),
          had_parser_error_(scanner->has_parser_error()) {
      DCHECK_NOT_NULL(scanner_);
    }
References DCHECK_NOT_NULL.
 BookmarkScope()
v8::internal::Scanner::BookmarkScope::~BookmarkScope () [default]
BookmarkScope() [2/2]
v8::internal::Scanner::BookmarkScope::BookmarkScope (const BookmarkScope &) [delete]
Member Function Documentation
Apply()
void v8::internal::Scanner::BookmarkScope::Apply ()
Definition at line 74 of file scanner.cc.
                                 {
  DCHECK(HasBeenSet()); // Caller hasn't called SetBookmark.
  if (had_parser_error_) {
    scanner_->set_parser_error();
  } else {
    scanner_->reset_parser_error_flag();
    scanner_->SeekNext(bookmark_);
  }
  bookmark_ = kBookmarkWasApplied;
}
References v8::internal::DCHECK().
Referenced by v8::internal::Parser::SkipFunction().
HasBeenApplied()
bool v8::internal::Scanner::BookmarkScope::HasBeenApplied () const
Definition at line 89 of file scanner.cc.
                                                {
  return bookmark_ == kBookmarkWasApplied;
}
HasBeenSet()
bool v8::internal::Scanner::BookmarkScope::HasBeenSet () const
Definition at line 85 of file scanner.cc.
                                            {
  return bookmark_ != kNoBookmark && bookmark_ != kBookmarkWasApplied;
}
operator=()
BookmarkScope& v8::internal::Scanner::BookmarkScope::operator= (const BookmarkScope &) [delete]
Set()
void v8::internal::Scanner::BookmarkScope::Set (size_t bookmark)
Definition at line 69 of file scanner.cc.
                                              {
  DCHECK_EQ(bookmark_, kNoBookmark);
  bookmark_ = position;
}
References bookmark_, DCHECK_EQ, and kNoBookmark.
Referenced by v8::internal::Parser::SkipFunction().
Member Data Documentation
bookmark_
size_t v8::internal::Scanner::BookmarkScope::bookmark_ [private]
Definition at line 240 of file scanner.h.
Referenced by Set().
had_parser_error_
bool v8::internal::Scanner::BookmarkScope::had_parser_error_ [private]
Definition at line 241 of file scanner.h.
kBookmarkWasApplied
const size_t v8::internal::Scanner::BookmarkScope::kBookmarkWasApplied [static], [private]
Initial value:
=
    std::numeric_limits<size_t>::max()
Definition at line 237 of file scanner.h.
kNoBookmark
const size_t v8::internal::Scanner::BookmarkScope::kNoBookmark [static], [private]
Initial value:
=
    std::numeric_limits<size_t>::max() - 1
Definition at line 236 of file scanner.h.
Referenced by Set().
scanner_
Scanner* v8::internal::Scanner::BookmarkScope::scanner_ [private]
Definition at line 239 of file scanner.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/scanner.h
/mnt/V8SourceCode/src/parsing/scanner.cc