v8::internal::wasm::ConstantExpressionInterface Class Reference
#include <constant-expression-interface.h>
Classes
struct Value
Public Types
using ValidationTag = Decoder::FullValidationTag
using Control = ControlBase< Value, ValidationTag >
using FullDecoder = WasmFullDecoder< ValidationTag, ConstantExpressionInterface, decoding_mode >
Public Member Functions
ConstantExpressionInterface (const WasmModule *module, Isolate *isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, DirectHandle< WasmTrustedInstanceData > shared_trusted_instance_data)
ConstantExpressionInterface (WasmModule *outer_module)
WasmValue computed_value () const
bool end_found () const
bool ends_with_struct_new () const
bool has_error () const
MessageTemplate error () const
Static Public Attributes
static constexpr DecodingMode decoding_mode = kConstantExpression
static constexpr bool kUsesPoppedArgs = true
Private Member Functions
bool generate_value () const
DirectHandle< WasmTrustedInstanceData > GetTrustedInstanceDataForTypeIndex (ModuleTypeIndex index)
DirectHandle< Map > GetRtt (DirectHandle< WasmTrustedInstanceData > data, ModuleTypeIndex index, const TypeDefinition &type, const Value &descriptor)
Private Attributes
bool end_found_ = false
bool ends_with_struct_new_ = false
WasmValue computed_value_
MessageTemplate error_ = MessageTemplate::kNone
const WasmModule * module_
WasmModule * outer_module_
Isolate * isolate_
DirectHandle< WasmTrustedInstanceData > trusted_instance_data_
DirectHandle< WasmTrustedInstanceData > shared_trusted_instance_data_
Detailed Description
Definition at line 31 of file constant-expression-interface.h.
Member Typedef Documentation
Control
using v8::internal::wasm::ConstantExpressionInterface::Control = ControlBase<Value, ValidationTag>
Definition at line 45 of file constant-expression-interface.h.
FullDecoder
using v8::internal::wasm::ConstantExpressionInterface::FullDecoder = WasmFullDecoder<ValidationTag, ConstantExpressionInterface, decoding_mode>
Definition at line 46 of file constant-expression-interface.h.
ValidationTag
using v8::internal::wasm::ConstantExpressionInterface::ValidationTag = Decoder::FullValidationTag
Definition at line 33 of file constant-expression-interface.h.
Constructor & Destructor Documentation
ConstantExpressionInterface() [1/2]
v8::internal::wasm::ConstantExpressionInterface::ConstantExpressionInterface (const WasmModule * module, Isolate * isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, DirectHandle< WasmTrustedInstanceData > shared_trusted_instance_data) [inline]
Definition at line 50 of file constant-expression-interface.h.
      : module_(module),
        outer_module_(nullptr),
        isolate_(isolate),
        trusted_instance_data_(trusted_instance_data),
        shared_trusted_instance_data_(shared_trusted_instance_data) {
    DCHECK_NOT_NULL(isolate);
  }
References DCHECK_NOT_NULL.
ConstantExpressionInterface() [2/2]
v8::internal::wasm::ConstantExpressionInterface::ConstantExpressionInterface (WasmModule * outer_module) [inline], [explicit]
Definition at line 62 of file constant-expression-interface.h.
      : module_(nullptr), outer_module_(outer_module), isolate_(nullptr) {}
Member Function Documentation
computed_value()
WasmValue v8::internal::wasm::ConstantExpressionInterface::computed_value () const [inline]
Definition at line 79 of file constant-expression-interface.h.
                                   {
    DCHECK(generate_value());
    // The value has to be initialized.
    DCHECK_NE(computed_value_.type(), kWasmVoid);
    return computed_value_;
  }
References v8::internal::DCHECK(), DCHECK_NE, and v8::internal::wasm::kWasmVoid.
end_found()
bool v8::internal::wasm::ConstantExpressionInterface::end_found () const [inline]
Definition at line 85 of file constant-expression-interface.h.
{ return end_found_; }
ends_with_struct_new()
bool v8::internal::wasm::ConstantExpressionInterface::ends_with_struct_new () const [inline]
Definition at line 86 of file constant-expression-interface.h.
{ return ends_with_struct_new_; }
error()
MessageTemplate v8::internal::wasm::ConstantExpressionInterface::error () const [inline]
Definition at line 88 of file constant-expression-interface.h.
                                {
    DCHECK(has_error());
    DCHECK_EQ(computed_value_.type(), kWasmVoid);
    return error_;
  }
References v8::internal::DCHECK(), DCHECK_EQ, and v8::internal::wasm::kWasmVoid.
generate_value()
bool v8::internal::wasm::ConstantExpressionInterface::generate_value () const [inline], [private]
Definition at line 95 of file constant-expression-interface.h.
{ return isolate_ != nullptr && !has_error(); }
GetRtt()
DirectHandle< Map > v8::internal::wasm::ConstantExpressionInterface::GetRtt (DirectHandle< WasmTrustedInstanceData > data, ModuleTypeIndex index, const TypeDefinition & type, const Value & descriptor) [private]
Definition at line 158 of file constant-expression-interface.cc.
                                                         {
  if (!type.has_descriptor()) {
    return direct_handle(
        Cast<Map>(data->managed_object_maps()->get(index.index)), isolate_);
  }
  DCHECK(type.has_descriptor());
  WasmValue desc = descriptor.runtime_value;
  DCHECK_EQ(desc.type().ref_index(),
            module_->canonical_type_id(type.descriptor));
  DirectHandle<Object> maybe_obj = desc.to_ref();
  if (!IsWasmStruct(*maybe_obj)) {
    DCHECK(IsNull(*maybe_obj));
    error_ = MessageTemplate::kWasmTrapNullDereference;
    return {};
  }
  return direct_handle(Cast<WasmStruct>(*maybe_obj)->described_rtt(), isolate_);
}
References v8::internal::wasm::WasmModule::canonical_type_id(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), error_, v8::internal::index, v8::internal::IsNull(), isolate_, module_, v8::internal::wasm::CanonicalValueType::ref_index(), v8::internal::wasm::ConstantExpressionInterface::Value::runtime_value, v8::internal::wasm::WasmValue::to_ref(), v8::internal::tracing::type, and v8::internal::wasm::WasmValue::type().
GetTrustedInstanceDataForTypeIndex()
DirectHandle< WasmTrustedInstanceData > v8::internal::wasm::ConstantExpressionInterface::GetTrustedInstanceDataForTypeIndex (ModuleTypeIndex index) [private]
Definition at line 493 of file constant-expression-interface.cc.
                           {
  bool type_is_shared = module_->type(index).is_shared;
  return type_is_shared ? shared_trusted_instance_data_
                        : trusted_instance_data_;
}
References v8::internal::index, v8::internal::wasm::TypeDefinition::is_shared, module_, shared_trusted_instance_data_, trusted_instance_data_, and v8::internal::wasm::WasmModule::type().
has_error()
bool v8::internal::wasm::ConstantExpressionInterface::has_error () const [inline]
Definition at line 87 of file constant-expression-interface.h.
{ return error_ != MessageTemplate::kNone; }
Member Data Documentation
computed_value_
WasmValue v8::internal::wasm::ConstantExpressionInterface::computed_value_ [private]
Definition at line 105 of file constant-expression-interface.h.
decoding_mode
constexpr DecodingMode v8::internal::wasm::ConstantExpressionInterface::decoding_mode = kConstantExpression [static], [constexpr]
Definition at line 34 of file constant-expression-interface.h.
end_found_
bool v8::internal::wasm::ConstantExpressionInterface::end_found_ = false [private]
Definition at line 103 of file constant-expression-interface.h.
ends_with_struct_new_
bool v8::internal::wasm::ConstantExpressionInterface::ends_with_struct_new_ = false [private]
Definition at line 104 of file constant-expression-interface.h.
error_
MessageTemplate v8::internal::wasm::ConstantExpressionInterface::error_ = MessageTemplate::kNone [private]
Definition at line 106 of file constant-expression-interface.h.
Referenced by GetRtt().
isolate_
Isolate* v8::internal::wasm::ConstantExpressionInterface::isolate_ [private]
Definition at line 109 of file constant-expression-interface.h.
Referenced by GetRtt().
kUsesPoppedArgs
constexpr bool v8::internal::wasm::ConstantExpressionInterface::kUsesPoppedArgs = true [static], [constexpr]
Definition at line 35 of file constant-expression-interface.h.
module_
const WasmModule* v8::internal::wasm::ConstantExpressionInterface::module_ [private]
Definition at line 107 of file constant-expression-interface.h.
Referenced by GetRtt(), and GetTrustedInstanceDataForTypeIndex().
outer_module_
WasmModule* v8::internal::wasm::ConstantExpressionInterface::outer_module_ [private]
Definition at line 108 of file constant-expression-interface.h.
shared_trusted_instance_data_
DirectHandle<WasmTrustedInstanceData> v8::internal::wasm::ConstantExpressionInterface::shared_trusted_instance_data_ [private]
Definition at line 111 of file constant-expression-interface.h.
Referenced by GetTrustedInstanceDataForTypeIndex().
trusted_instance_data_
DirectHandle<WasmTrustedInstanceData> v8::internal::wasm::ConstantExpressionInterface::trusted_instance_data_ [private]
Definition at line 110 of file constant-expression-interface.h.
Referenced by GetTrustedInstanceDataForTypeIndex().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/constant-expression-interface.h
/mnt/V8SourceCode/src/wasm/constant-expression-interface.cc