v8::internal::baseline::BaselineBatchCompiler Class Reference
#include <baseline-batch-compiler.h>
Public Member Functions
BaselineBatchCompiler (Isolate *isolate)
~BaselineBatchCompiler ()
void EnqueueFunction (DirectHandle< JSFunction > function)
void EnqueueSFI (Tagged< SharedFunctionInfo > shared)
void set_enabled (bool enabled)
bool is_enabled ()
void InstallBatch ()
Static Public Attributes
static const int kInitialQueueSize = 32
Private Member Functions
bool concurrent () const
void EnsureQueueCapacity ()
void Enqueue (DirectHandle< SharedFunctionInfo > shared)
bool ShouldCompileBatch (Tagged< SharedFunctionInfo > shared)
void CompileBatch (DirectHandle< JSFunction > function)
void CompileBatchConcurrent (Tagged< SharedFunctionInfo > shared)
void ClearBatch ()
bool MaybeCompileFunction (Tagged< MaybeObject > maybe_sfi)
Private Attributes
Isolate * isolate_
Handle< WeakFixedArray > compilation_queue_
int last_index_
int estimated_instruction_size_
bool enabled_
std::unique_ptr< ConcurrentBaselineCompiler > concurrent_compiler_
Detailed Description
Definition at line 20 of file baseline-batch-compiler.h.
Constructor & Destructor Documentation
BaselineBatchCompiler()
v8::internal::baseline::BaselineBatchCompiler::BaselineBatchCompiler (Isolate * isolate) [explicit]
Definition at line 235 of file baseline-batch-compiler.cc.
    : isolate_(isolate),
      compilation_queue_(Handle<WeakFixedArray>::null()),
      last_index_(0),
      estimated_instruction_size_(0),
      enabled_(true) {
  if (v8_flags.concurrent_sparkplug) {
    concurrent_compiler_ =
        std::make_unique<ConcurrentBaselineCompiler>(isolate_);
  }
}
References concurrent_compiler_, isolate_, and v8::internal::v8_flags.
 BaselineBatchCompiler()
v8::internal::baseline::BaselineBatchCompiler::~BaselineBatchCompiler ()
Definition at line 247 of file baseline-batch-compiler.cc.
                                              {
  if (!compilation_queue_.is_null()) {
    GlobalHandles::Destroy(compilation_queue_.location());
    compilation_queue_ = Handle<WeakFixedArray>::null();
  }
}
References compilation_queue_, v8::internal::GlobalHandles::Destroy(), and v8::internal::Handle< T >::null().
Member Function Documentation
ClearBatch()
void v8::internal::baseline::BaselineBatchCompiler::ClearBatch () [private]
Definition at line 391 of file baseline-batch-compiler.cc.
                                       {
  estimated_instruction_size_ = 0;
  last_index_ = 0;
}
References estimated_instruction_size_, and last_index_.
Referenced by CompileBatch(), and CompileBatchConcurrent().
CompileBatch()
void v8::internal::baseline::BaselineBatchCompiler::CompileBatch (DirectHandle< JSFunction > function) [private]
Definition at line 315 of file baseline-batch-compiler.cc.
                                                                          {
  {
    IsCompiledScope is_compiled_scope(
        function->shared()->is_compiled_scope(isolate_));
    Compiler::CompileBaseline(isolate_, function, Compiler::CLEAR_EXCEPTION,
                              &is_compiled_scope);
  }
  for (int i = 0; i < last_index_; i++) {
    Tagged<MaybeObject> maybe_sfi = compilation_queue_->get(i);
    MaybeCompileFunction(maybe_sfi);
    compilation_queue_->set(i, ClearedValue(isolate_));
  }
  ClearBatch();
}
References v8::internal::Compiler::CLEAR_EXCEPTION, ClearBatch(), v8::internal::ClearedValue(), compilation_queue_, v8::internal::Compiler::CompileBaseline(), isolate_, last_index_, and MaybeCompileFunction().
Referenced by EnqueueFunction().
CompileBatchConcurrent()
void v8::internal::baseline::BaselineBatchCompiler::CompileBatchConcurrent (Tagged< SharedFunctionInfo > shared) [private]
Definition at line 330 of file baseline-batch-compiler.cc.
                                       {
  Enqueue(DirectHandle<SharedFunctionInfo>(shared, isolate_));
  concurrent_compiler_->CompileBatch(compilation_queue_, last_index_);
  ClearBatch();
}
References ClearBatch(), compilation_queue_, concurrent_compiler_, Enqueue(), isolate_, and last_index_.
Referenced by EnqueueFunction(), and EnqueueSFI().
concurrent()
bool v8::internal::baseline::BaselineBatchCompiler::concurrent () const [private]
Definition at line 254 of file baseline-batch-compiler.cc.
                                             {
  return v8_flags.concurrent_sparkplug &&
         !isolate_->EfficiencyModeEnabledForTiering();
}
References v8::internal::Isolate::EfficiencyModeEnabledForTiering(), isolate_, and v8::internal::v8_flags.
Referenced by EnqueueFunction().
Enqueue()
void v8::internal::baseline::BaselineBatchCompiler::Enqueue (DirectHandle< SharedFunctionInfo > shared) [private]
Definition at line 289 of file baseline-batch-compiler.cc.
                                                                           {
  EnsureQueueCapacity();
  compilation_queue_->set(last_index_++, MakeWeak(*shared));
}
References compilation_queue_, EnsureQueueCapacity(), last_index_, and v8::internal::MakeWeak().
Referenced by CompileBatchConcurrent(), EnqueueFunction(), and EnqueueSFI().
EnqueueFunction()
void v8::internal::baseline::BaselineBatchCompiler::EnqueueFunction (DirectHandle< JSFunction > function)
Definition at line 259 of file baseline-batch-compiler.cc.
                                                                             {
  DirectHandle<SharedFunctionInfo> shared(function->shared(), isolate_);
  // Immediately compile the function if batch compilation is disabled.
  if (!is_enabled()) {
    IsCompiledScope is_compiled_scope(
        function->shared()->is_compiled_scope(isolate_));
    Compiler::CompileBaseline(isolate_, function, Compiler::CLEAR_EXCEPTION,
                              &is_compiled_scope);
    return;
  }
  if (ShouldCompileBatch(*shared)) {
    if (concurrent()) {
      CompileBatchConcurrent(*shared);
    } else {
      CompileBatch(function);
    }
  } else {
    Enqueue(shared);
  }
}
References v8::internal::Compiler::CLEAR_EXCEPTION, v8::internal::Compiler::CompileBaseline(), CompileBatch(), CompileBatchConcurrent(), concurrent(), Enqueue(), is_enabled(), isolate_, and ShouldCompileBatch().
EnqueueSFI()
void v8::internal::baseline::BaselineBatchCompiler::EnqueueSFI (Tagged< SharedFunctionInfo > shared)
Definition at line 280 of file baseline-batch-compiler.cc.
                                                                        {
  if (!v8_flags.concurrent_sparkplug || !is_enabled()) return;
  if (ShouldCompileBatch(shared)) {
    CompileBatchConcurrent(shared);
  } else {
    Enqueue(DirectHandle<SharedFunctionInfo>(shared, isolate_));
  }
}
References CompileBatchConcurrent(), Enqueue(), is_enabled(), isolate_, ShouldCompileBatch(), and v8::internal::v8_flags.
EnsureQueueCapacity()
void v8::internal::baseline::BaselineBatchCompiler::EnsureQueueCapacity () [private]
Definition at line 299 of file baseline-batch-compiler.cc.
                                                {
  if (compilation_queue_.is_null()) {
    compilation_queue_ = isolate_->global_handles()->Create(
        *isolate_->factory()->NewWeakFixedArray(kInitialQueueSize,
                                                AllocationType::kOld));
    return;
  }
  if (last_index_ >= compilation_queue_->length()) {
    DirectHandle<WeakFixedArray> new_queue =
        isolate_->factory()->CopyWeakFixedArrayAndGrow(compilation_queue_,
                                                       last_index_);
    GlobalHandles::Destroy(compilation_queue_.location());
    compilation_queue_ = isolate_->global_handles()->Create(*new_queue);
  }
}
References compilation_queue_, v8::internal::Factory::CopyWeakFixedArrayAndGrow(), v8::internal::GlobalHandles::Create(), v8::internal::GlobalHandles::Destroy(), v8::internal::Isolate::factory(), v8::internal::Isolate::global_handles(), isolate_, kInitialQueueSize, v8::internal::kOld, last_index_, and v8::internal::FactoryBase< Impl >::NewWeakFixedArray().
Referenced by Enqueue().
InstallBatch()
void v8::internal::baseline::BaselineBatchCompiler::InstallBatch ()
Definition at line 294 of file baseline-batch-compiler.cc.
                                         {
  DCHECK(v8_flags.concurrent_sparkplug);
  concurrent_compiler_->InstallBatch();
}
References concurrent_compiler_, v8::internal::DCHECK(), and v8::internal::v8_flags.
is_enabled()
bool v8::internal::baseline::BaselineBatchCompiler::is_enabled () [inline]
Definition at line 31 of file baseline-batch-compiler.h.
{ return enabled_; }
References enabled_.
Referenced by EnqueueFunction(), and EnqueueSFI().
MaybeCompileFunction()
bool v8::internal::baseline::BaselineBatchCompiler::MaybeCompileFunction (Tagged< MaybeObject > maybe_sfi) [private]
Definition at line 376 of file baseline-batch-compiler.cc.
                                   {
  Tagged<HeapObject> heapobj;
  // Skip functions where the weak reference is no longer valid.
  if (!maybe_sfi.GetHeapObjectIfWeak(&heapobj)) return false;
  Handle<SharedFunctionInfo> shared =
      handle(Cast<SharedFunctionInfo>(heapobj), isolate_);
  // Skip functions where the bytecode has been flushed.
  if (!shared->is_compiled()) return false;
  IsCompiledScope is_compiled_scope(shared->is_compiled_scope(isolate_));
  return Compiler::CompileSharedWithBaseline(
      isolate_, shared, Compiler::CLEAR_EXCEPTION, &is_compiled_scope);
}
References v8::internal::Compiler::CLEAR_EXCEPTION, v8::internal::Compiler::CompileSharedWithBaseline(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), v8::internal::handle(), and isolate_.
Referenced by CompileBatch().
set_enabled()
void v8::internal::baseline::BaselineBatchCompiler::set_enabled (bool enabled) [inline]
Definition at line 30 of file baseline-batch-compiler.h.
{ enabled_ = enabled; }
References enabled_.
ShouldCompileBatch()
bool v8::internal::baseline::BaselineBatchCompiler::ShouldCompileBatch (Tagged< SharedFunctionInfo > shared) [private]
Definition at line 337 of file baseline-batch-compiler.cc.
                                       {
  // Early return if the function is compiled with baseline already or it is not
  // suitable for baseline compilation.
  if (shared->HasBaselineCode()) return false;
  // If we're already compiling this function, return.
  if (shared->is_sparkplug_compiling()) return false;
  if (!CanCompileWithBaseline(isolate_, shared)) return false;
  int estimated_size;
  {
    DisallowHeapAllocation no_gc;
    estimated_size = BaselineCompiler::EstimateInstructionSize(
        shared->GetBytecodeArray(isolate_));
  }
  estimated_instruction_size_ += estimated_size;
  if (v8_flags.trace_baseline_batch_compilation) {
    CodeTracer::Scope trace_scope(isolate_->GetCodeTracer());
    PrintF(trace_scope.file(), "[Baseline batch compilation] Enqueued SFI %s",
           shared->DebugNameCStr().get());
    PrintF(trace_scope.file(),
           " with estimated size %d (current budget: %d/%d)\n", estimated_size,
           estimated_instruction_size_,
           v8_flags.baseline_batch_compilation_threshold.value());
  }
  if (estimated_instruction_size_ >=
      v8_flags.baseline_batch_compilation_threshold) {
    if (v8_flags.trace_baseline_batch_compilation) {
      CodeTracer::Scope trace_scope(isolate_->GetCodeTracer());
      PrintF(trace_scope.file(),
             "[Baseline batch compilation] Compiling current batch of %d "
             "functions\n",
             (last_index_ + 1));
    }
    return true;
  }
  return false;
}
References v8::internal::CanCompileWithBaseline(), estimated_instruction_size_, v8::internal::baseline::BaselineCompiler::EstimateInstructionSize(), v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), isolate_, last_index_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PrintF(), and v8::internal::v8_flags.
Referenced by EnqueueFunction(), and EnqueueSFI().
Member Data Documentation
compilation_queue_
Handle<WeakFixedArray> v8::internal::baseline::BaselineBatchCompiler::compilation_queue_ [private]
Definition at line 66 of file baseline-batch-compiler.h.
Referenced by CompileBatch(), CompileBatchConcurrent(), Enqueue(), EnsureQueueCapacity(), and ~BaselineBatchCompiler().
concurrent_compiler_
std::unique_ptr<ConcurrentBaselineCompiler> v8::internal::baseline::BaselineBatchCompiler::concurrent_compiler_ [private]
Definition at line 79 of file baseline-batch-compiler.h.
Referenced by BaselineBatchCompiler(), CompileBatchConcurrent(), and InstallBatch().
enabled_
bool v8::internal::baseline::BaselineBatchCompiler::enabled_ [private]
Definition at line 76 of file baseline-batch-compiler.h.
Referenced by is_enabled(), and set_enabled().
estimated_instruction_size_
int v8::internal::baseline::BaselineBatchCompiler::estimated_instruction_size_ [private]
Definition at line 72 of file baseline-batch-compiler.h.
Referenced by ClearBatch(), and ShouldCompileBatch().
isolate_
Isolate* v8::internal::baseline::BaselineBatchCompiler::isolate_ [private]
Definition at line 62 of file baseline-batch-compiler.h.
Referenced by BaselineBatchCompiler(), CompileBatch(), CompileBatchConcurrent(), concurrent(), EnqueueFunction(), EnqueueSFI(), EnsureQueueCapacity(), MaybeCompileFunction(), and ShouldCompileBatch().
kInitialQueueSize
const int v8::internal::baseline::BaselineBatchCompiler::kInitialQueueSize = 32 [static]
Definition at line 22 of file baseline-batch-compiler.h.
Referenced by EnsureQueueCapacity().
last_index_
int v8::internal::baseline::BaselineBatchCompiler::last_index_ [private]
Definition at line 69 of file baseline-batch-compiler.h.
Referenced by ClearBatch(), CompileBatch(), CompileBatchConcurrent(), Enqueue(), EnsureQueueCapacity(), and ShouldCompileBatch().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/baseline/baseline-batch-compiler.h
/mnt/V8SourceCode/src/baseline/baseline-batch-compiler.cc