cppgc::internal::PersistentRegionBase Class Reference
#include <persistent-node.h>
Public Member Functions
~PersistentRegionBase ()
PersistentRegionBase (const PersistentRegionBase &)=delete
PersistentRegionBase & operator= (const PersistentRegionBase &)=delete
void Iterate (RootVisitor &)
size_t NodesInUse () const
void ClearAllUsedNodes ()
Protected Member Functions
PersistentRegionBase (const FatalOutOfMemoryHandler &oom_handler)
PersistentNode * TryAllocateNodeFromFreeList (void *owner, TraceRootCallback trace)
void FreeNode (PersistentNode *node)
PersistentNode * RefillFreeListAndAllocateNode (void *owner, TraceRootCallback trace)
Private Types
using PersistentNodeSlots = std::array< PersistentNode, 256u >
Private Member Functions
template<typename PersistentBaseClass >
void ClearAllUsedNodes ()
void RefillFreeList ()
Private Attributes
std::vector< std::unique_ptr< PersistentNodeSlots > > nodes_
PersistentNode * free_list_head_ = nullptr
size_t nodes_in_use_ = 0
const FatalOutOfMemoryHandler & oom_handler_
Friends
class CrossThreadPersistentRegion
Detailed Description
Definition at line 78 of file persistent-node.h.
Member Typedef Documentation
PersistentNodeSlots
using cppgc::internal::PersistentRegionBase::PersistentNodeSlots = std::array<PersistentNode, 256u> [private]
Definition at line 79 of file persistent-node.h.
Constructor & Destructor Documentation
 PersistentRegionBase()
cppgc::internal::PersistentRegionBase::~PersistentRegionBase ()
Definition at line 24 of file persistent-node.cc.
{ ClearAllUsedNodes(); }
References ClearAllUsedNodes().
PersistentRegionBase() [1/2]
cppgc::internal::PersistentRegionBase::PersistentRegionBase (const PersistentRegionBase &) [delete]
PersistentRegionBase() [2/2]
cppgc::internal::PersistentRegionBase::PersistentRegionBase (const FatalOutOfMemoryHandler & oom_handler) [explicit], [protected]
Definition at line 20 of file persistent-node.cc.
    : oom_handler_(oom_handler) {}
Member Function Documentation
ClearAllUsedNodes() [1/2]
void cppgc::internal::PersistentRegionBase::ClearAllUsedNodes ()
Definition at line 49 of file persistent-node.cc.
                                             {
  ClearAllUsedNodes<PersistentBase>();
}
Referenced by cppgc::internal::HeapBase::Terminate(), and ~PersistentRegionBase().
ClearAllUsedNodes() [2/2]
template<typename PersistentBaseClass >
void cppgc::internal::PersistentRegionBase::ClearAllUsedNodes [private]
Definition at line 27 of file persistent-node.cc.
                                             {
  for (auto& slots : nodes_) {
    for (auto& node : *slots) {
      if (!node.IsUsed()) continue;
      static_cast<PersistentBaseClass*>(node.owner())->ClearFromGC();
      // Add nodes back to the free list to allow reusing for subsequent
      // creation calls.
      node.InitializeAsFreeNode(free_list_head_);
      free_list_head_ = &node;
      CPPGC_DCHECK(nodes_in_use_ > 0);
      nodes_in_use_--;
    }
  }
  CPPGC_DCHECK(0u == nodes_in_use_);
}
References CPPGC_DCHECK, free_list_head_, nodes_, and nodes_in_use_.
FreeNode()
void cppgc::internal::PersistentRegionBase::FreeNode (PersistentNode * node) [inline], [protected]
Definition at line 110 of file persistent-node.h.
                                      {
    CPPGC_DCHECK(node);
    CPPGC_DCHECK(node->IsUsed());
    node->InitializeAsFreeNode(free_list_head_);
    free_list_head_ = node;
    CPPGC_DCHECK(nodes_in_use_ > 0);
    nodes_in_use_--;
  }
References CPPGC_DCHECK, cppgc::internal::PersistentNode::InitializeAsFreeNode(), and cppgc::internal::PersistentNode::IsUsed().
Referenced by cppgc::internal::PersistentRegion::FreeNode(), and cppgc::internal::CrossThreadPersistentRegion::FreeNode().
Iterate()
void cppgc::internal::PersistentRegionBase::Iterate (RootVisitor & root_visitor)
Definition at line 87 of file persistent-node.cc.
                                                            {
  free_list_head_ = nullptr;
  for (auto& slots : nodes_) {
    bool is_empty = true;
    for (auto& node : *slots) {
      if (node.IsUsed()) {
        node.Trace(root_visitor);
        is_empty = false;
      } else {
        node.InitializeAsFreeNode(free_list_head_);
        free_list_head_ = &node;
      }
    }
    if (is_empty) {
      PersistentNode* first_next = (*slots)[0].FreeListNext();
      // First next was processed first in the loop above, guaranteeing that it
      // either points to null or into a different node block.
      CPPGC_DCHECK(!first_next || first_next < &slots->front() ||
                   first_next > &slots->back());
      free_list_head_ = first_next;
      slots.reset();
    }
  }
  nodes_.erase(std::remove_if(nodes_.begin(), nodes_.end(),
                              [](const auto& ptr) { return !ptr; }),
               nodes_.end());
}
References CPPGC_DCHECK, cppgc::internal::PersistentNode::FreeListNext(), and v8::internal::compiler::turboshaft::is_empty().
Referenced by cppgc::internal::CrossThreadPersistentRegion::Iterate(), cppgc::internal::MarkerBase::ProcessWeakness(), and cppgc::internal::MarkerBase::VisitLocalRoots().
NodesInUse()
size_t cppgc::internal::PersistentRegionBase::NodesInUse () const
Definition at line 53 of file persistent-node.cc.
                                              {
#ifdef DEBUG
  const size_t accumulated_nodes_in_use_ = std::accumulate(
      nodes_.cbegin(), nodes_.cend(), 0u, [](size_t acc, const auto& slots) {
        return acc + std::count_if(slots->cbegin(), slots->cend(),
                                   [](const PersistentNode& node) {
                                     return node.IsUsed();
                                   });
      });
  DCHECK_EQ(accumulated_nodes_in_use_, nodes_in_use_);
#endif // DEBUG
  return nodes_in_use_;
}
References nodes_.
Referenced by cppgc::internal::CrossThreadPersistentRegion::NodesInUse(), and cppgc::internal::HeapBase::Terminate().
operator=()
PersistentRegionBase& cppgc::internal::PersistentRegionBase::operator= (const PersistentRegionBase &) [delete]
RefillFreeList()
void cppgc::internal::PersistentRegionBase::RefillFreeList () [private]
Definition at line 67 of file persistent-node.cc.
                                          {
  auto node_slots = std::make_unique<PersistentNodeSlots>();
  if (!node_slots.get()) {
    oom_handler_("Oilpan: PersistentRegionBase::RefillFreeList()");
  }
  nodes_.push_back(std::move(node_slots));
  for (auto& node : *nodes_.back()) {
    node.InitializeAsFreeNode(free_list_head_);
    free_list_head_ = &node;
  }
}
RefillFreeListAndAllocateNode()
PersistentNode * cppgc::internal::PersistentRegionBase::RefillFreeListAndAllocateNode (void * owner, TraceRootCallback trace) [protected]
Definition at line 79 of file persistent-node.cc.
                                          {
  RefillFreeList();
  auto* node = TryAllocateNodeFromFreeList(owner, trace);
  CPPGC_DCHECK(node);
  return node;
}
References CPPGC_DCHECK.
TryAllocateNodeFromFreeList()
PersistentNode* cppgc::internal::PersistentRegionBase::TryAllocateNodeFromFreeList (void * owner, TraceRootCallback trace) [inline], [protected]
Definition at line 97 of file persistent-node.h.
                                                                       {
    PersistentNode* node = nullptr;
    if (V8_LIKELY(free_list_head_)) {
      node = free_list_head_;
      free_list_head_ = free_list_head_->FreeListNext();
      CPPGC_DCHECK(!node->IsUsed());
      node->InitializeAsUsedNode(owner, trace);
      nodes_in_use_++;
    }
    return node;
  }
References CPPGC_DCHECK, cppgc::internal::PersistentNode::FreeListNext(), cppgc::internal::PersistentNode::InitializeAsUsedNode(), cppgc::internal::PersistentNode::IsUsed(), and V8_LIKELY.
Friends And Related Function Documentation
CrossThreadPersistentRegion
friend class CrossThreadPersistentRegion [friend]
Definition at line 133 of file persistent-node.h.
Member Data Documentation
free_list_head_
PersistentNode* cppgc::internal::PersistentRegionBase::free_list_head_ = nullptr [private]
Definition at line 129 of file persistent-node.h.
Referenced by ClearAllUsedNodes().
nodes_
std::vector<std::unique_ptr<PersistentNodeSlots> > cppgc::internal::PersistentRegionBase::nodes_ [private]
Definition at line 128 of file persistent-node.h.
Referenced by ClearAllUsedNodes(), NodesInUse(), and cppgc::internal::CrossThreadPersistentRegion::~CrossThreadPersistentRegion().
nodes_in_use_
size_t cppgc::internal::PersistentRegionBase::nodes_in_use_ = 0 [private]
Definition at line 130 of file persistent-node.h.
Referenced by ClearAllUsedNodes().
oom_handler_
const FatalOutOfMemoryHandler& cppgc::internal::PersistentRegionBase::oom_handler_ [private]
Definition at line 131 of file persistent-node.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/internal/persistent-node.h
/mnt/V8SourceCode/src/heap/cppgc/persistent-node.cc