v8::internal::compiler::MoveOptimizer Class Reference
#include <move-optimizer.h>
Public Member Functions
MoveOptimizer (Zone *local_zone, InstructionSequence *code)
MoveOptimizer (const MoveOptimizer &)=delete
MoveOptimizer & operator= (const MoveOptimizer &)=delete
void Run ()
Private Types
using MoveOpVector = ZoneVector< MoveOperands * >
Private Member Functions
InstructionSequence * code () const
Zone * local_zone () const
Zone * code_zone () const
MoveOpVector & local_vector ()
void CompressGaps (Instruction *instr)
void CompressBlock (InstructionBlock *block)
void CompressMoves (ParallelMove *left, MoveOpVector *right)
void MigrateMoves (Instruction *to, Instruction *from)
void RemoveClobberedDestinations (Instruction *instruction)
const Instruction * LastInstruction (const InstructionBlock *block) const
void OptimizeMerge (InstructionBlock *block)
void FinalizeMoves (Instruction *instr)
Private Attributes
Zone *const local_zone_
InstructionSequence *const code_
MoveOpVector local_vector_
ZoneVector< InstructionOperand > operand_buffer1
ZoneVector< InstructionOperand > operand_buffer2
Detailed Description
Definition at line 15 of file move-optimizer.h.
Member Typedef Documentation
MoveOpVector
using v8::internal::compiler::MoveOptimizer::MoveOpVector = ZoneVector<MoveOperands*> [private]
Definition at line 24 of file move-optimizer.h.
Constructor & Destructor Documentation
MoveOptimizer() [1/2]
v8::internal::compiler::MoveOptimizer::MoveOptimizer (Zone * local_zone, InstructionSequence * code)
Definition at line 127 of file move-optimizer.cc.
    : local_zone_(local_zone),
      code_(code),
      local_vector_(local_zone),
      operand_buffer1(local_zone),
      operand_buffer2(local_zone) {}
MoveOptimizer() [2/2]
v8::internal::compiler::MoveOptimizer::MoveOptimizer (const MoveOptimizer &) [delete]
Member Function Documentation
code()
InstructionSequence* v8::internal::compiler::MoveOptimizer::code () const [inline], [private]
Definition at line 26 of file move-optimizer.h.
{ return code_; }
Referenced by CompressBlock(), LastInstruction(), OptimizeMerge(), and Run().
code_zone()
Zone* v8::internal::compiler::MoveOptimizer::code_zone () const [inline], [private]
Definition at line 28 of file move-optimizer.h.
{ return code()->zone(); }
References code.
Referenced by FinalizeMoves(), MigrateMoves(), and OptimizeMerge().
CompressBlock()
void v8::internal::compiler::MoveOptimizer::CompressBlock (InstructionBlock * block) [private]
Definition at line 353 of file move-optimizer.cc.
                                                         {
  int first_instr_index = block->first_instruction_index();
  int last_instr_index = block->last_instruction_index();
  // Start by removing gap assignments where the output of the subsequent
  // instruction appears on LHS, as long as they are not needed by its input.
  Instruction* prev_instr = code()->instructions()[first_instr_index];
  RemoveClobberedDestinations(prev_instr);
  for (int index = first_instr_index + 1; index <= last_instr_index; ++index) {
    Instruction* instr = code()->instructions()[index];
    // Migrate to the gap of prev_instr eligible moves from instr.
    MigrateMoves(instr, prev_instr);
    // Remove gap assignments clobbered by instr's output.
    RemoveClobberedDestinations(instr);
    prev_instr = instr;
  }
}
References code(), v8::internal::compiler::InstructionBlock::first_instruction_index(), v8::internal::index, v8::internal::compiler::InstructionSequence::instructions(), v8::internal::compiler::InstructionBlock::last_instruction_index(), MigrateMoves(), and RemoveClobberedDestinations().
Referenced by OptimizeMerge(), and Run().
CompressGaps()
void v8::internal::compiler::MoveOptimizer::CompressGaps (Instruction * instr) [private]
Definition at line 326 of file move-optimizer.cc.
                                                         {
  int i = FindFirstNonEmptySlot(instruction);
  bool has_moves = i <= Instruction::LAST_GAP_POSITION;
  USE(has_moves);
  if (i == Instruction::LAST_GAP_POSITION) {
    std::swap(instruction->parallel_moves()[Instruction::FIRST_GAP_POSITION],
              instruction->parallel_moves()[Instruction::LAST_GAP_POSITION]);
  } else if (i == Instruction::FIRST_GAP_POSITION) {
    CompressMoves(
        instruction->parallel_moves()[Instruction::FIRST_GAP_POSITION],
        instruction->parallel_moves()[Instruction::LAST_GAP_POSITION]);
  }
  // We either have no moves, or, after swapping or compressing, we have
  // all the moves in the first gap position, and none in the second/end gap
  // position.
  ParallelMove* first =
      instruction->parallel_moves()[Instruction::FIRST_GAP_POSITION];
  ParallelMove* last =
      instruction->parallel_moves()[Instruction::LAST_GAP_POSITION];
  USE(first);
  USE(last);
  DCHECK(!has_moves ||
         (first != nullptr && (last == nullptr || last->empty())));
}
References CompressMoves(), v8::internal::DCHECK(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::FindFirstNonEmptySlot(), v8::internal::compiler::Instruction::FIRST_GAP_POSITION, v8::internal::compiler::Instruction::LAST_GAP_POSITION, v8::internal::compiler::Instruction::parallel_moves(), and USE.
Referenced by Run().
CompressMoves()
void v8::internal::compiler::MoveOptimizer::CompressMoves (ParallelMove * left, MoveOpVector * right) [private]
Definition at line 297 of file move-optimizer.cc.
                                                                         {
  if (right == nullptr) return;
  MoveOpVector& eliminated = local_vector();
  DCHECK(eliminated.empty());
  if (!left->empty()) {
    // Modify the right moves in place and collect moves that will be killed by
    // merging the two gaps.
    for (MoveOperands* move : *right) {
      if (move->IsRedundant()) continue;
      left->PrepareInsertAfter(move, &eliminated);
    }
    // Eliminate dead moves.
    for (MoveOperands* to_eliminate : eliminated) {
      to_eliminate->Eliminate();
    }
    eliminated.clear();
  }
  // Add all possibly modified moves from right side.
  for (MoveOperands* move : *right) {
    if (move->IsRedundant()) continue;
    left->push_back(move);
  }
  // Nuke right.
  right->clear();
  DCHECK(eliminated.empty());
}
References v8::internal::ZoneVector< T >::clear(), v8::internal::DCHECK(), v8::internal::ZoneVector< T >::empty(), local_vector(), and v8::internal::compiler::ParallelMove::PrepareInsertAfter().
Referenced by CompressGaps(), MigrateMoves(), and OptimizeMerge().
FinalizeMoves()
void v8::internal::compiler::MoveOptimizer::FinalizeMoves (Instruction * instr) [private]
Definition at line 551 of file move-optimizer.cc.
                                                    {
  MoveOpVector& loads = local_vector();
  DCHECK(loads.empty());
  ParallelMove* parallel_moves = instr->parallel_moves()[0];
  if (parallel_moves == nullptr) return;
  // Find all the loads.
  for (MoveOperands* move : *parallel_moves) {
    if (move->IsRedundant()) continue;
    if (move->source().IsConstant() || IsSlot(move->source())) {
      loads.push_back(move);
    }
  }
  if (loads.empty()) return;
  // Group the loads by source, moving the preferred destination to the
  // beginning of the group.
  std::sort(loads.begin(), loads.end(), LoadCompare);
  MoveOperands* group_begin = nullptr;
  for (MoveOperands* load : loads) {
    // New group.
    if (group_begin == nullptr ||
        !load->source().EqualsCanonicalized(group_begin->source())) {
      group_begin = load;
      continue;
    }
    // Nothing to be gained from splitting here. However, due to the sorting
    // scheme, there could be optimizable groups of loads later in the group,
    // so bump the {group_begin} along.
    if (IsSlot(group_begin->destination())) {
      group_begin = load;
      continue;
    }
    // Insert new move into slot 1.
    ParallelMove* slot_1 = instr->GetOrCreateParallelMove(
        static_cast<Instruction::GapPosition>(1), code_zone());
    slot_1->AddMove(group_begin->destination(), load->destination());
    load->Eliminate();
  }
  loads.clear();
}
References v8::internal::compiler::ParallelMove::AddMove(), v8::internal::ZoneVector< T >::begin(), v8::internal::ZoneVector< T >::clear(), code_zone(), v8::internal::DCHECK(), v8::internal::compiler::MoveOperands::destination(), v8::internal::compiler::MoveOperands::Eliminate(), v8::internal::ZoneVector< T >::empty(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::InstructionOperand::EqualsCanonicalized(), v8::internal::compiler::Instruction::GetOrCreateParallelMove(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::IsSlot(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::LoadCompare(), local_vector(), v8::internal::compiler::Instruction::parallel_moves(), v8::internal::ZoneVector< T >::push_back(), v8::base::sort(), and v8::internal::compiler::MoveOperands::source().
Referenced by Run().
LastInstruction()
const Instruction * v8::internal::compiler::MoveOptimizer::LastInstruction (const InstructionBlock * block) const [private]
Definition at line 372 of file move-optimizer.cc.
                                         {
  return code()->instructions()[block->last_instruction_index()];
}
References code(), v8::internal::compiler::InstructionSequence::instructions(), and v8::internal::compiler::InstructionBlock::last_instruction_index().
Referenced by OptimizeMerge().
local_vector()
MoveOpVector& v8::internal::compiler::MoveOptimizer::local_vector () [inline], [private]
Definition at line 29 of file move-optimizer.h.
{ return local_vector_; }
Referenced by CompressMoves(), and FinalizeMoves().
local_zone()
Zone* v8::internal::compiler::MoveOptimizer::local_zone () const [inline], [private]
Definition at line 27 of file move-optimizer.h.
{ return local_zone_; }
Referenced by MigrateMoves(), and OptimizeMerge().
MigrateMoves()
void v8::internal::compiler::MoveOptimizer::MigrateMoves (Instruction * to, Instruction * from) [private]
Definition at line 208 of file move-optimizer.cc.
                                                                   {
  if (from->IsCall()) return;
  ParallelMove* from_moves = from->parallel_moves()[0];
  if (from_moves == nullptr || from_moves->empty()) return;
  OperandSet dst_cant_be(&operand_buffer1);
  OperandSet src_cant_be(&operand_buffer2);
  // If an operand is an input to the instruction, we cannot move assignments
  // where it appears on the LHS.
  for (size_t i = 0; i < from->InputCount(); ++i) {
    dst_cant_be.InsertOp(*from->InputAt(i));
  }
  // If an operand is output to the instruction, we cannot move assignments
  // where it appears on the RHS, because we would lose its value before the
  // instruction.
  // Same for temp operands.
  // The output can't appear on the LHS because we performed
  // RemoveClobberedDestinations for the "from" instruction.
  for (size_t i = 0; i < from->OutputCount(); ++i) {
    src_cant_be.InsertOp(*from->OutputAt(i));
  }
  for (size_t i = 0; i < from->TempCount(); ++i) {
    src_cant_be.InsertOp(*from->TempAt(i));
  }
  for (MoveOperands* move : *from_moves) {
    if (move->IsRedundant()) continue;
    // Assume dest has a value "V". If we have a "dest = y" move, then we can't
    // move "z = dest", because z would become y rather than "V".
    // We assume CompressMoves has happened before this, which means we don't
    // have more than one assignment to dest.
    src_cant_be.InsertOp(move->destination());
  }
  // This set is usually small, e.g., for JetStream2 it has 16 elements or less
  // in 99.99% of the cases, hence use inline storage and fast linear search.
  // It is encoded as a `SmallMap` to `Dummy` values, since we don't have an
  // equivalent `SmallSet` type.
  struct Dummy {};
  SmallZoneMap<MoveKey, Dummy, 16> move_candidates(local_zone());
  // We start with all the moves that don't have conflicting source or
  // destination operands are eligible for being moved down.
  for (MoveOperands* move : *from_moves) {
    if (move->IsRedundant()) continue;
    if (!dst_cant_be.ContainsOpOrAlias(move->destination())) {
      MoveKey key = {move->source(), move->destination()};
      move_candidates.emplace(key, Dummy{});
    }
  }
  if (move_candidates.empty()) return;
  // Stabilize the candidate set.
  bool changed = false;
  do {
    changed = false;
    for (auto iter = move_candidates.begin(); iter != move_candidates.end();) {
      auto [move, _] = *iter;
      if (src_cant_be.ContainsOpOrAlias(move.source)) {
        src_cant_be.InsertOp(move.destination);
        iter = move_candidates.erase(iter);
        changed = true;
      } else {
        ++iter;
      }
    }
  } while (changed);
  ParallelMove to_move(local_zone());
  for (MoveOperands* move : *from_moves) {
    if (move->IsRedundant()) continue;
    MoveKey key = {move->source(), move->destination()};
    if (move_candidates.find(key) != move_candidates.end()) {
      to_move.AddMove(move->source(), move->destination(), code_zone());
      move->Eliminate();
    }
  }
  if (to_move.empty()) return;
  ParallelMove* dest =
      to->GetOrCreateParallelMove(Instruction::GapPosition::START, code_zone());
  CompressMoves(&to_move, dest);
  DCHECK(dest->empty());
  for (MoveOperands* m : to_move) {
    dest->push_back(m);
  }
}
References _, v8::internal::compiler::ParallelMove::AddMove(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::begin(), code_zone(), CompressMoves(), v8::internal::DCHECK(), v8::Dummy(), v8::internal::compiler::MoveOperands::Eliminate(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::emplace(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::empty(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::end(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::erase(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::find(), v8::internal::compiler::Instruction::GetOrCreateParallelMove(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::Instruction::InputCount(), v8::internal::compiler::Instruction::IsCall(), v8::internal::key, local_zone(), operand_buffer1, operand_buffer2, v8::internal::compiler::Instruction::OutputAt(), v8::internal::compiler::Instruction::OutputCount(), v8::internal::compiler::Instruction::parallel_moves(), v8::internal::compiler::Instruction::TempAt(), and v8::internal::compiler::Instruction::TempCount().
Referenced by CompressBlock().
operator=()
MoveOptimizer& v8::internal::compiler::MoveOptimizer::operator= (const MoveOptimizer &) [delete]
OptimizeMerge()
void v8::internal::compiler::MoveOptimizer::OptimizeMerge (InstructionBlock * block) [private]
Definition at line 377 of file move-optimizer.cc.
                                                         {
  DCHECK_LT(1, block->PredecessorCount());
  // Ensure that the last instruction in all incoming blocks don't contain
  // things that would prevent moving gap moves across them.
  for (RpoNumber& pred_index : block->predecessors()) {
    const InstructionBlock* pred = code()->InstructionBlockAt(pred_index);
    // If the predecessor has more than one successor, we shouldn't attempt to
    // move down to this block (one of the successors) any of the gap moves,
    // because their effect may be necessary to the other successors.
    if (pred->SuccessorCount() > 1) return;
    const Instruction* last_instr =
        code()->instructions()[pred->last_instruction_index()];
    if (last_instr->IsCall()) return;
    if (last_instr->TempCount() != 0) return;
    if (last_instr->OutputCount() != 0) return;
    for (size_t i = 0; i < last_instr->InputCount(); ++i) {
      const InstructionOperand* op = last_instr->InputAt(i);
      if (!op->IsConstant() && !op->IsImmediate()) return;
    }
  }
  // This map is usually small, e.g., for JetStream2 in 99.5% of the cases it
  // has 16 elements or less. Hence use a `SmallMap` with inline storage and
  // fast linear search in the common case.
  SmallZoneMap<MoveKey, /* count */ size_t, 16> move_map(local_zone());
  size_t correct_counts = 0;
  // Accumulate set of shared moves.
  for (RpoNumber& pred_index : block->predecessors()) {
    const InstructionBlock* pred = code()->InstructionBlockAt(pred_index);
    const Instruction* instr = LastInstruction(pred);
    if (instr->parallel_moves()[0] == nullptr ||
        instr->parallel_moves()[0]->empty()) {
      return;
    }
    for (const MoveOperands* move : *instr->parallel_moves()[0]) {
      if (move->IsRedundant()) continue;
      InstructionOperand src = move->source();
      InstructionOperand dst = move->destination();
      MoveKey key = {src, dst};
      auto [it, inserted] = move_map.emplace(key, 1);
      if (!inserted) {
        it->second++;
        if (it->second == block->PredecessorCount()) {
          correct_counts++;
        }
      }
    }
  }
  if (move_map.empty() || correct_counts == 0) return;
  // Find insertion point.
  Instruction* instr = code()->instructions()[block->first_instruction_index()];
  if (correct_counts != move_map.size()) {
    // Moves that are unique to each predecessor won't be pushed to the common
    // successor.
    OperandSet conflicting_srcs(&operand_buffer1);
    for (auto iter = move_map.begin(); iter != move_map.end();) {
      auto [move, count] = *iter;
      if (count != block->PredecessorCount()) {
        // Not all the moves in all the gaps are the same. Maybe some are. If
        // there are such moves, we could move them, but the destination of the
        // moves staying behind can't appear as a source of a common move,
        // because the move staying behind will clobber this destination.
        conflicting_srcs.InsertOp(move.destination);
        iter = move_map.erase(iter);
      } else {
        ++iter;
      }
    }
    bool changed = false;
    do {
      // If a common move can't be pushed to the common successor, then its
      // destination also can't appear as source to any move being pushed.
      changed = false;
      for (auto iter = move_map.begin(); iter != move_map.end();) {
        auto [move, count] = *iter;
        DCHECK_EQ(block->PredecessorCount(), count);
        USE(count);
        if (conflicting_srcs.ContainsOpOrAlias(move.source)) {
          conflicting_srcs.InsertOp(move.destination);
          iter = move_map.erase(iter);
          changed = true;
        } else {
          ++iter;
        }
      }
    } while (changed);
  }
  if (move_map.empty()) return;
  DCHECK_NOT_NULL(instr);
  bool gap_initialized = true;
  if (instr->parallel_moves()[0] != nullptr &&
      !instr->parallel_moves()[0]->empty()) {
    // Will compress after insertion.
    gap_initialized = false;
    std::swap(instr->parallel_moves()[0], instr->parallel_moves()[1]);
  }
  ParallelMove* moves = instr->GetOrCreateParallelMove(
      static_cast<Instruction::GapPosition>(0), code_zone());
  // Delete relevant entries in predecessors and move everything to block.
  bool first_iteration = true;
  for (RpoNumber& pred_index : block->predecessors()) {
    const InstructionBlock* pred = code()->InstructionBlockAt(pred_index);
    for (MoveOperands* move : *LastInstruction(pred)->parallel_moves()[0]) {
      if (move->IsRedundant()) continue;
      MoveKey key = {move->source(), move->destination()};
      auto it = move_map.find(key);
      if (it != move_map.end()) {
        if (first_iteration) {
          moves->AddMove(move->source(), move->destination());
        }
        move->Eliminate();
      }
    }
    first_iteration = false;
  }
  // Compress.
  if (!gap_initialized) {
    CompressMoves(instr->parallel_moves()[0], instr->parallel_moves()[1]);
  }
  CompressBlock(block);
}
References v8::internal::compiler::ParallelMove::AddMove(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::begin(), code(), code_zone(), CompressBlock(), CompressMoves(), DCHECK_EQ, DCHECK_LT, DCHECK_NOT_NULL, v8::internal::compiler::MoveOperands::Eliminate(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::emplace(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::empty(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::end(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::erase(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::find(), v8::internal::compiler::InstructionBlock::first_instruction_index(), v8::internal::compiler::Instruction::GetOrCreateParallelMove(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::Instruction::InputCount(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::compiler::InstructionSequence::instructions(), v8::internal::compiler::Instruction::IsCall(), v8::internal::key, v8::internal::compiler::InstructionBlock::last_instruction_index(), LastInstruction(), local_zone(), operand_buffer1, v8::internal::compiler::Instruction::OutputCount(), v8::internal::compiler::Instruction::parallel_moves(), v8::internal::compiler::InstructionBlock::PredecessorCount(), v8::internal::compiler::InstructionBlock::predecessors(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size(), v8::internal::size_t, v8::internal::compiler::InstructionBlock::SuccessorCount(), v8::internal::compiler::Instruction::TempCount(), and USE.
Referenced by Run().
RemoveClobberedDestinations()
void v8::internal::compiler::MoveOptimizer::RemoveClobberedDestinations (Instruction * instruction) [private]
Definition at line 164 of file move-optimizer.cc.
                                                                        {
  if (instruction->IsCall()) return;
  ParallelMove* moves = instruction->parallel_moves()[0];
  if (moves == nullptr) return;
  DCHECK(instruction->parallel_moves()[1] == nullptr ||
         instruction->parallel_moves()[1]->empty());
  OperandSet outputs(&operand_buffer1);
  OperandSet inputs(&operand_buffer2);
  // Outputs and temps are treated together as potentially clobbering a
  // destination operand.
  for (size_t i = 0; i < instruction->OutputCount(); ++i) {
    outputs.InsertOp(*instruction->OutputAt(i));
  }
  for (size_t i = 0; i < instruction->TempCount(); ++i) {
    outputs.InsertOp(*instruction->TempAt(i));
  }
  // Input operands block elisions.
  for (size_t i = 0; i < instruction->InputCount(); ++i) {
    inputs.InsertOp(*instruction->InputAt(i));
  }
  // Elide moves made redundant by the instruction.
  for (MoveOperands* move : *moves) {
    if (outputs.ContainsOpOrAlias(move->destination()) &&
        !inputs.ContainsOpOrAlias(move->destination())) {
      move->Eliminate();
    }
  }
  // The ret instruction makes any assignment before it unnecessary, except for
  // the one for its input.
  if (instruction->IsRet() || instruction->IsTailCall()) {
    for (MoveOperands* move : *moves) {
      if (!inputs.ContainsOpOrAlias(move->destination())) {
        move->Eliminate();
      }
    }
  }
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::Instruction::InputCount(), v8::internal::compiler::Instruction::IsCall(), v8::internal::compiler::Instruction::IsRet(), v8::internal::compiler::Instruction::IsTailCall(), operand_buffer1, operand_buffer2, v8::internal::compiler::Instruction::OutputAt(), v8::internal::compiler::Instruction::OutputCount(), v8::internal::compiler::Instruction::parallel_moves(), v8::internal::compiler::Instruction::TempAt(), and v8::internal::compiler::Instruction::TempCount().
Referenced by CompressBlock().
Run()
void v8::internal::compiler::MoveOptimizer::Run ()
Definition at line 134 of file move-optimizer.cc.
                        {
  for (Instruction* instruction : code()->instructions()) {
    CompressGaps(instruction);
  }
  for (InstructionBlock* block : code()->instruction_blocks()) {
    CompressBlock(block);
  }
  for (InstructionBlock* block : code()->instruction_blocks()) {
    if (block->PredecessorCount() <= 1) continue;
    if (!block->IsDeferred()) {
      bool has_only_deferred = true;
      for (RpoNumber& pred_id : block->predecessors()) {
        if (!code()->InstructionBlockAt(pred_id)->IsDeferred()) {
          has_only_deferred = false;
          break;
        }
      }
      // This would pull down common moves. If the moves occur in deferred
      // blocks, and the closest common successor is not deferred, we lose the
      // optimization of just spilling/filling in deferred blocks, when the
      // current block is not deferred.
      if (has_only_deferred) continue;
    }
    OptimizeMerge(block);
  }
  for (Instruction* gap : code()->instructions()) {
    FinalizeMoves(gap);
  }
}
References code(), CompressBlock(), CompressGaps(), FinalizeMoves(), v8::internal::torque::IsDeferred(), and OptimizeMerge().
Referenced by v8::internal::compiler::turboshaft::OptimizeMovesPhase::Run().
Member Data Documentation
code_
InstructionSequence* const v8::internal::compiler::MoveOptimizer::code_ [private]
Definition at line 54 of file move-optimizer.h.
local_vector_
MoveOpVector v8::internal::compiler::MoveOptimizer::local_vector_ [private]
Definition at line 55 of file move-optimizer.h.
local_zone_
Zone* const v8::internal::compiler::MoveOptimizer::local_zone_ [private]
Definition at line 53 of file move-optimizer.h.
operand_buffer1
ZoneVector<InstructionOperand> v8::internal::compiler::MoveOptimizer::operand_buffer1 [private]
Definition at line 59 of file move-optimizer.h.
Referenced by MigrateMoves(), OptimizeMerge(), and RemoveClobberedDestinations().
operand_buffer2
ZoneVector<InstructionOperand> v8::internal::compiler::MoveOptimizer::operand_buffer2 [private]
Definition at line 60 of file move-optimizer.h.
Referenced by MigrateMoves(), and RemoveClobberedDestinations().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/move-optimizer.h
/mnt/V8SourceCode/src/compiler/backend/move-optimizer.cc