v8::internal::Signature< T > Class Template Reference
#include <signature.h>
Public Types
using Builder = SignatureBuilder< Signature< T >, T >
Public Member Functions
constexpr Signature (size_t return_count, size_t parameter_count, const T *reps)
size_t return_count () const
size_t parameter_count () const
T GetParam (size_t index) const
T GetReturn (size_t index=0) const
bool contains (T element) const
base::Vector< const T > parameters () const
base::Vector< const T > returns () const
base::Vector< const T > all () const
bool operator== (const Signature &other) const
bool operator!= (const Signature &other) const
Static Public Member Functions
static Signature< T > * Build (Zone *zone, std::initializer_list< T > returns, std::initializer_list< T > params)
Static Public Attributes
static constexpr size_t kReturnCountOffset = 0
static constexpr size_t kParameterCountOffset
static constexpr size_t kRepsOffset = kParameterCountOffset + kSizetSize
Protected Attributes
size_t return_count_
size_t parameter_count_
const T * reps_
Detailed Description
template<typename T>
class v8::internal::Signature< T >
Definition at line 80 of file signature.h.
Member Typedef Documentation
Builder
template<typename T >
using v8::internal::Signature< T >::Builder = SignatureBuilder<Signature<T>, T>
Definition at line 130 of file signature.h.
Constructor & Destructor Documentation
Signature()
template<typename T >
constexpr v8::internal::Signature< T >::Signature (size_t return_count, size_t parameter_count, const T * reps) [inline], [constexpr]
Definition at line 82 of file signature.h.
      : return_count_(return_count),
        parameter_count_(parameter_count),
        reps_(reps) {
    DCHECK_EQ(kReturnCountOffset, offsetof(Signature, return_count_));
    DCHECK_EQ(kParameterCountOffset, offsetof(Signature, parameter_count_));
    DCHECK_EQ(kRepsOffset, offsetof(Signature, reps_));
    static_assert(std::is_standard_layout_v<Signature<T>>);
  }
References DCHECK_EQ, v8::internal::Signature< T >::kParameterCountOffset, v8::internal::Signature< T >::kRepsOffset, v8::internal::Signature< T >::kReturnCountOffset, v8::internal::Signature< T >::parameter_count_, v8::internal::Signature< T >::reps_, and v8::internal::Signature< T >::return_count_.
Member Function Documentation
all()
template<typename T >
base::Vector<const T> v8::internal::Signature< T >::all () const [inline]
Definition at line 117 of file signature.h.
                                  {
    return {reps_, return_count_ + parameter_count_};
  }
References v8::internal::Signature< T >::parameter_count_, v8::internal::Signature< T >::reps_, and v8::internal::Signature< T >::return_count_.
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::BlockType(), v8::internal::Signature< T >::contains(), v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualSig(), v8::internal::wasm::EquivalentNumericSig(), v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup(), v8::internal::Signature< T >::operator==(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
Build()
template<typename T >
static Signature<T>* v8::internal::Signature< T >::Build (Zone * zone, std::initializer_list< T > returns, std::initializer_list< T > params) [inline], [static]
Definition at line 132 of file signature.h.
                                                            {
    Builder builder(zone, returns.size(), params.size());
    for (T ret : returns) builder.AddReturn(ret);
    for (T param : params) builder.AddParam(param);
    return builder.Get();
  }
References v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::SignatureBuilder< SigT, T >::Get(), and v8::internal::Signature< T >::returns().
contains()
template<typename T >
bool v8::internal::Signature< T >::contains (T element) const [inline]
Definition at line 108 of file signature.h.
                                 {
    return std::find(all().cbegin(), all().cend(), element) != all().cend();
  }
References v8::internal::Signature< T >::all().
GetParam()
template<typename T >
T v8::internal::Signature< T >::GetParam (size_t index) const [inline]
Definition at line 96 of file signature.h.
                                 {
    // If heap memory is corrupted, we may get confused about the number of
    // parameters during compilation. These SBXCHECKs defend against that.
    SBXCHECK_LT(index, parameter_count_);
    return reps_[return_count_ + index];
  }
References v8::internal::index, v8::internal::Signature< T >::parameter_count_, v8::internal::Signature< T >::reps_, v8::internal::Signature< T >::return_count_, and SBXCHECK_LT.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), v8::internal::compiler::BuildParameterLocations(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchCase(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchException(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchException(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::wasm::WasmBytecodeGenerator::GenerateBytecode(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::wasm::BlockTypeImmediate::in_type(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineTargetIsTypeCompatible(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsSupportedWasmFastApiFunction(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessParameter(), v8::internal::wasm::WasmWrapperTSGraphBuilder::QualifiesForFastTransform(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
GetReturn()
template<typename T >
T v8::internal::Signature< T >::GetReturn (size_t index = 0) const [inline]
Definition at line 103 of file signature.h.
                                      {
    SBXCHECK_LT(index, return_count_);
    return reps_[index];
  }
References v8::internal::index, v8::internal::Signature< T >::reps_, v8::internal::Signature< T >::return_count_, and SBXCHECK_LT.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAndReturn(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeFunctionBody(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall(), v8::internal::wasm::WasmBytecodeGenerator::GenerateBytecode(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::wasm::anonymous_namespace{wasm-interpreter.cc}::GetWasmReturnTypeFromSignature(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::HasSameReturns(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineTargetIsTypeCompatible(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsSupportedWasmFastApiFunction(), v8::internal::wasm::BlockTypeImmediate::out_type(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), v8::internal::wasm::WasmReturnTypeFromSignature(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
operator!=()
template<typename T >
bool v8::internal::Signature< T >::operator!= (const Signature< T > & other) const [inline]
Definition at line 127 of file signature.h.
{ return !(*this == other); }
operator==()
template<typename T >
bool v8::internal::Signature< T >::operator== (const Signature< T > & other) const [inline]
Definition at line 121 of file signature.h.
                                                {
    if (this == &other) return true;
    if (parameter_count() != other.parameter_count()) return false;
    if (return_count() != other.return_count()) return false;
    return std::equal(all().begin(), all().end(), other.all().begin());
  }
References v8::internal::Signature< T >::all(), v8::internal::compiler::begin(), v8::internal::compiler::end(), v8::internal::equal, v8::internal::Signature< T >::parameter_count(), and v8::internal::Signature< T >::return_count().
parameter_count()
template<typename T >
size_t v8::internal::Signature< T >::parameter_count () const [inline]
Definition at line 94 of file signature.h.
{ return parameter_count_; }
References v8::internal::Signature< T >::parameter_count_.
Referenced by v8::internal::wasm::LocalDeclEncoder::AddLocals(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), v8::internal::compiler::BuildParameterLocations(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchCase(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchException(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchException(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), v8::internal::wasm::ResolvedWasmImport::ComputeKind(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeFunctionBody(), v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::wasm::ModuleDecoderImpl::DecodeStartSection(), v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualSig(), v8::internal::wasm::EquivalentNumericSig(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::wasm::BlockTypeImmediate::in_arity(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::InitializeInitializedLocalsTracking(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineTargetIsTypeCompatible(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsSupportedWasmFastApiFunction(), v8::internal::Signature< T >::operator==(), v8::internal::wasm::InstanceBuilder::ProcessImportedFunction(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushControl(), v8::internal::wasm::WasmWrapperTSGraphBuilder::QualifiesForFastTransform(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StartFunction(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StartFunctionBody(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Throw(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidFunctionSubtypeDefinition(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::WasmIntoJSInlinerImpl(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
parameters()
template<typename T >
base::Vector<const T> v8::internal::Signature< T >::parameters () const [inline]
Definition at line 113 of file signature.h.
                                         {
    return {reps_ + return_count_, parameter_count_};
  }
References v8::internal::Signature< T >::parameter_count_, v8::internal::Signature< T >::reps_, and v8::internal::Signature< T >::return_count_.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::throw_or_rethrow(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_block_helper(), and v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidFunctionSubtypeDefinition().
return_count()
template<typename T >
size_t v8::internal::Signature< T >::return_count () const [inline]
Definition at line 93 of file signature.h.
{ return return_count_; }
References v8::internal::Signature< T >::return_count_.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAndReturn(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildMultiReturnFixedArrayFromIterable(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::CanReturnCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeFunctionBody(), v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), v8::internal::wasm::ModuleDecoderImpl::DecodeStartSection(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::DoReturn(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), v8::internal::wasm::EquivalentNumericSig(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall(), v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::wasm::anonymous_namespace{wasm-interpreter.cc}::GetWasmReturnTypeFromSignature(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::HasSameReturns(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineTargetIsTypeCompatible(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsSupportedWasmFastApiFunction(), v8::internal::Signature< T >::operator==(), v8::internal::wasm::BlockTypeImmediate::out_arity(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ReturnImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TraceFunctionExit(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidFunctionSubtypeDefinition(), v8::internal::wasm::WasmReturnTypeFromSignature(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
returns()
template<typename T >
base::Vector<const T> v8::internal::Signature< T >::returns () const [inline]
Definition at line 116 of file signature.h.
{ return {reps_, return_count_}; }
References v8::internal::Signature< T >::reps_, and v8::internal::Signature< T >::return_count_.
Referenced by v8::internal::Signature< T >::Build(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::CanReturnCall(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues(), v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::FixedSizeSignature(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ReturnImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction(), and v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidFunctionSubtypeDefinition().
Member Data Documentation
kParameterCountOffset
template<typename T >
constexpr size_t v8::internal::Signature< T >::kParameterCountOffset [static], [constexpr]
Initial value:
=
      kReturnCountOffset + kSizetSize
Definition at line 141 of file signature.h.
Referenced by v8::internal::Signature< T >::Signature().
kRepsOffset
template<typename T >
constexpr size_t v8::internal::Signature< T >::kRepsOffset = kParameterCountOffset + kSizetSize [static], [constexpr]
Definition at line 143 of file signature.h.
Referenced by v8::internal::Signature< T >::Signature().
kReturnCountOffset
template<typename T >
constexpr size_t v8::internal::Signature< T >::kReturnCountOffset = 0 [static], [constexpr]
Definition at line 140 of file signature.h.
Referenced by v8::internal::Signature< T >::Signature().
parameter_count_
template<typename T >
size_t v8::internal::Signature< T >::parameter_count_ [protected]
Definition at line 147 of file signature.h.
Referenced by v8::internal::Signature< T >::all(), v8::internal::Signature< T >::GetParam(), v8::internal::Signature< T >::parameter_count(), v8::internal::Signature< T >::parameters(), and v8::internal::Signature< T >::Signature().
reps_
template<typename T >
const T* v8::internal::Signature< T >::reps_ [protected]
Definition at line 148 of file signature.h.
Referenced by v8::internal::Signature< T >::all(), v8::internal::Signature< T >::GetParam(), v8::internal::Signature< T >::GetReturn(), v8::internal::Signature< T >::parameters(), v8::internal::Signature< T >::returns(), and v8::internal::Signature< T >::Signature().
return_count_
template<typename T >
size_t v8::internal::Signature< T >::return_count_ [protected]
Definition at line 146 of file signature.h.
Referenced by v8::internal::Signature< T >::all(), v8::internal::Signature< T >::GetParam(), v8::internal::Signature< T >::GetReturn(), v8::internal::Signature< T >::parameters(), v8::internal::Signature< T >::return_count(), v8::internal::Signature< T >::returns(), and v8::internal::Signature< T >::Signature().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/linkage-location.h
/mnt/V8SourceCode/src/codegen/signature.h