v8::String::ExternalStringResource Class Reference
An ExternalStringResource is a wrapper around a two-byte string buffer that resides outside V8's heap.
#include <v8-primitive.h>
Public Member Functions
~ExternalStringResource () override=default
Override the destructor to manage the life cycle of the underlying buffer.
virtual const uint16_t * data () const =0
The string data from the underlying buffer.
virtual size_t length () const =0
The length of the string.
const uint16_t * cached_data () const
Returns the cached data from the underlying buffer.
void UpdateDataCache ()
Update {cached_data_} with the data from the underlying buffer.
Protected Member Functions
ExternalStringResource ()=default
Private Member Functions
void CheckCachedDataInvariants () const
Private Attributes
const uint16_t * cached_data_ = nullptr
Additional Inherited Members
Detailed Description
An ExternalStringResource is a wrapper around a two-byte string buffer that resides outside V8's heap.
Implement an ExternalStringResource to manage the life cycle of the underlying buffer. Note that the string data must be immutable.
Definition at line 390 of file v8-primitive.h.
Constructor & Destructor Documentation
 ExternalStringResource()
v8::String::ExternalStringResource::~ExternalStringResource () [override], [default]
Override the destructor to manage the life cycle of the underlying buffer.
ExternalStringResource()
v8::String::ExternalStringResource::ExternalStringResource () [protected], [default]
Member Function Documentation
cached_data()
const uint16_t* v8::String::ExternalStringResource::cached_data () const [inline]
Returns the cached data from the underlying buffer.
This method can be called only for cacheable resources (i.e. IsCacheable() == true) and only after UpdateDataCache() was called.
Definition at line 414 of file v8-primitive.h.
                                        {
      CheckCachedDataInvariants();
      return cached_data_;
    }
CheckCachedDataInvariants()
void v8::String::ExternalStringResource::CheckCachedDataInvariants () const [private]
Definition at line 6097 of file api.cc.
                                                                   {
  DCHECK(IsCacheable() && cached_data_ != nullptr);
}
References DCHECK.
data()
virtual const uint16_t* v8::String::ExternalStringResource::data () const [pure virtual]
The string data from the underlying buffer.
If the resource is cacheable then data() must return the same value for all invocations.
Referenced by v8::String::MakeExternal(), v8::String::NewExternalTwoByte(), and UpdateDataCache().
length()
virtual size_t v8::String::ExternalStringResource::length () const [pure virtual]
The length of the string.
That is, the number of two-byte characters.
Referenced by v8::internal::Factory::NewExternalStringFromTwoByte(), v8::String::NewExternalTwoByte(), and v8::internal::ExternalTwoByteString::SetResource().
UpdateDataCache()
void v8::String::ExternalStringResource::UpdateDataCache ()
Update {cached_data_} with the data from the underlying buffer.
This can be called only for cacheable resources.
Definition at line 6092 of file api.cc.
                                                   {
  DCHECK(IsCacheable());
  cached_data_ = data();
}
References cached_data_, data(), DCHECK, and v8::String::ExternalStringResourceBase::IsCacheable().
Member Data Documentation
cached_data_
const uint16_t* v8::String::ExternalStringResource::cached_data_ = nullptr [private]
Definition at line 431 of file v8-primitive.h.
Referenced by UpdateDataCache().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive.h
/mnt/V8SourceCode/src/api/api.cc