v8::internal::SloppyBlockFunctionStatement Class Reference
#include <ast.h>
Public Member Functions
Statement * statement () const
void set_statement (Statement *statement)
Scope * scope () const
Variable * var () const
Token::Value init () const
const AstRawString * name () const
SloppyBlockFunctionStatement ** next ()
Private Types
using TokenField = Statement::NextBitField< Token::Value, 8 >
Private Member Functions
SloppyBlockFunctionStatement (int pos, Variable *var, Token::Value init, Statement *statement)
Private Attributes
friend Zone
Variable * var_
Statement * statement_
SloppyBlockFunctionStatement * next_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 910 of file ast.h.
Member Typedef Documentation
TokenField
using v8::internal::SloppyBlockFunctionStatement::TokenField = Statement::NextBitField<Token::Value, 8> [private]
Definition at line 924 of file ast.h.
Constructor & Destructor Documentation
SloppyBlockFunctionStatement()
v8::internal::SloppyBlockFunctionStatement::SloppyBlockFunctionStatement (int pos, Variable * var, Token::Value init, Statement * statement) [inline], [private]
Definition at line 926 of file ast.h.
      : Statement(pos, kSloppyBlockFunctionStatement),
        var_(var),
        statement_(statement),
        next_(nullptr) {
    bit_field_ = TokenField::update(bit_field_, init);
  }
References v8::internal::AstNode::bit_field_, init(), and v8::base::BitField< T, shift, size, U >::update().
Member Function Documentation
init()
Token::Value v8::internal::SloppyBlockFunctionStatement::init () const [inline]
Definition at line 916 of file ast.h.
{ return TokenField::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by SloppyBlockFunctionStatement().
name()
const AstRawString* v8::internal::SloppyBlockFunctionStatement::name () const [inline]
Definition at line 917 of file ast.h.
{ return var_->raw_name(); }
References v8::internal::Variable::raw_name(), and var_.
next()
SloppyBlockFunctionStatement** v8::internal::SloppyBlockFunctionStatement::next () [inline]
Definition at line 918 of file ast.h.
{ return &next_; }
References next_.
scope()
Scope* v8::internal::SloppyBlockFunctionStatement::scope () const [inline]
Definition at line 914 of file ast.h.
{ return var_->scope(); }
References v8::internal::Variable::scope(), and var_.
set_statement()
void v8::internal::SloppyBlockFunctionStatement::set_statement (Statement * statement) [inline]
Definition at line 913 of file ast.h.
{ statement_ = statement; }
References statement(), and statement_.
statement()
Statement* v8::internal::SloppyBlockFunctionStatement::statement () const [inline]
Definition at line 912 of file ast.h.
{ return statement_; }
References statement_.
Referenced by set_statement().
var()
Variable* v8::internal::SloppyBlockFunctionStatement::var () const [inline]
Definition at line 915 of file ast.h.
{ return var_; }
References var_.
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 921 of file ast.h.
Member Data Documentation
next_
SloppyBlockFunctionStatement* v8::internal::SloppyBlockFunctionStatement::next_ [private]
Definition at line 937 of file ast.h.
Referenced by next().
statement_
Statement* v8::internal::SloppyBlockFunctionStatement::statement_ [private]
Definition at line 936 of file ast.h.
Referenced by set_statement(), and statement().
var_
Variable* v8::internal::SloppyBlockFunctionStatement::var_ [private]
Definition at line 935 of file ast.h.
Referenced by name(), scope(), and var().
Zone
friend v8::internal::SloppyBlockFunctionStatement::Zone [private]
Definition at line 922 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h