v8::internal::compiler::SourceTextModuleRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< SourceTextModule > object () const
OptionalCellRef GetCell (JSHeapBroker *broker, int cell_index) const
OptionalObjectRef import_meta (JSHeapBroker *broker) const
Detailed Description
Definition at line 1251 of file heap-refs.h.
Member Function Documentation
GetCell()
OptionalCellRef v8::internal::compiler::SourceTextModuleRef::GetCell (JSHeapBroker * broker, int cell_index) const
Definition at line 2236 of file heap-refs.cc.
                                                                   {
  return TryMakeRef(broker, object()->GetCell(cell_index));
}
References broker(), and v8::internal::compiler::TryMakeRef().
Referenced by v8::internal::compiler::JSTypedLowering::BuildGetModuleCell().
import_meta()
OptionalObjectRef v8::internal::compiler::SourceTextModuleRef::import_meta (JSHeapBroker * broker) const
Definition at line 2241 of file heap-refs.cc.
                                                                             {
  return TryMakeRef(broker, object()->import_meta(kAcquireLoad));
}
References broker(), v8::kAcquireLoad, and v8::internal::compiler::TryMakeRef().
object()
IndirectHandle<SourceTextModule> v8::internal::compiler::SourceTextModuleRef::object () const
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc