v8::internal::Factory::JSFunctionBuilder Class Reference
#include <factory.h>
Public Member Functions
JSFunctionBuilder (Isolate *isolate, DirectHandle< SharedFunctionInfo > sfi, DirectHandle< Context > context)
V8_WARN_UNUSED_RESULT Handle< JSFunction > Build ()
JSFunctionBuilder & set_map (DirectHandle< Map > v)
JSFunctionBuilder & set_allocation_type (AllocationType v)
JSFunctionBuilder & set_feedback_cell (DirectHandle< FeedbackCell > v)
Private Member Functions
V8_WARN_UNUSED_RESULT Handle< JSFunction > BuildRaw (DirectHandle< Code > code)
Private Attributes
Isolate *const isolate_
DirectHandle< SharedFunctionInfo > sfi_
DirectHandle< Context > context_
MaybeDirectHandle< Map > maybe_map_
MaybeDirectHandle< FeedbackCell > maybe_feedback_cell_
AllocationType allocation_type_ = AllocationType::kOld
Friends
class Factory
Detailed Description
Definition at line 1121 of file factory.h.
Constructor & Destructor Documentation
JSFunctionBuilder()
v8::internal::Factory::JSFunctionBuilder::JSFunctionBuilder (Isolate * isolate, DirectHandle< SharedFunctionInfo > sfi, DirectHandle< Context > context)
Definition at line 4765 of file factory.cc.
    : isolate_(isolate), sfi_(sfi), context_(context) {}
Member Function Documentation
Build()
Handle< JSFunction > v8::internal::Factory::JSFunctionBuilder::Build ()
Definition at line 4770 of file factory.cc.
                                                   {
  DirectHandle<Code> code(sfi_->GetCode(isolate_), isolate_);
  // Retain the code across the call to BuildRaw, because it allocates and can
  // trigger code to be flushed. Otherwise the SFI's compiled state and the
  // function's compiled state can diverge, and the call to PostInstantiation
  // below can fail to initialize the feedback vector.
  IsCompiledScope is_compiled_scope(sfi_->is_compiled_scope(isolate_));
  Handle<JSFunction> result = BuildRaw(code);
  if (code->kind() == CodeKind::BASELINE) {
    JSFunction::EnsureFeedbackVector(isolate_, result, &is_compiled_scope);
  }
  Compiler::PostInstantiation(isolate_, result, &is_compiled_scope);
  return result;
}
References code, v8::internal::JSFunction::EnsureFeedbackVector(), v8::internal::Compiler::PostInstantiation(), and v8::base::internal::result.
Referenced by v8::internal::RUNTIME_FUNCTION().
BuildRaw()
Handle< JSFunction > v8::internal::Factory::JSFunctionBuilder::BuildRaw (DirectHandle< Code > code) [private]
Definition at line 4787 of file factory.cc.
                             {
  Isolate* isolate = isolate_;
  Factory* factory = isolate_->factory();
  DirectHandle<Map> map;
  if (!maybe_map_.ToHandle(&map)) {
    // No specific map requested, use the default.
    map = direct_handle(Cast<Map>(context_->native_context()->GetNoCell(
                            sfi_->function_map_index())),
                        isolate_);
  }
  DCHECK(InstanceTypeChecker::IsJSFunction(*map));
  Handle<JSFunction> function_handle;
  bool many_closures_cell = false;
  {
    // Allocation.
    Tagged<JSFunction> function =
        Cast<JSFunction>(factory->New(map, allocation_type_));
    DisallowGarbageCollection no_gc;
    // Transition the feedback cell after allocating the JSFunction. This is so
    // that the leap-tiering-relevant one-to-many feedback cell mutation below
    // happens atomically with the closure count increase here, without the
    // object verifier potentially observing a many-closures cell with context
    // specialised code.
    DirectHandle<FeedbackCell> feedback_cell;
    FeedbackCell::ClosureCountTransition cell_transition;
    if (maybe_feedback_cell_.ToHandle(&feedback_cell)) {
      // Track the newly-created closure.
      cell_transition = feedback_cell->IncrementClosureCount(isolate_);
    } else {
      // Fall back to the many_closures_cell.
      feedback_cell = isolate_->factory()->many_closures_cell();
      cell_transition = FeedbackCell::kMany;
      many_closures_cell = true;
    }
    WriteBarrierMode mode = allocation_type_ == AllocationType::kYoung
                                ? SKIP_WRITE_BARRIER
                                : UPDATE_WRITE_BARRIER;
    // Header initialization.
    function->initialize_properties(isolate);
    function->initialize_elements();
    function->set_shared(*sfi_, mode);
    function->set_context(*context_, kReleaseStore, mode);
    function->set_raw_feedback_cell(*feedback_cell, mode);
#ifdef V8_ENABLE_LEAPTIERING
    if (!many_closures_cell) {
      // TODO(olivf, 42204201): Here we are explicitly not updating (only
      // potentially initializing) the code. Worst case the dispatch handle
      // still contains bytecode or CompileLazy and we'll tier on the next call.
      // Otoh, if we would UpdateCode we would risk tiering down already
      // existing closures with optimized code installed.
      DCHECK_NE(*feedback_cell, *isolate->factory()->many_closures_cell());
      DCHECK_NE(feedback_cell->dispatch_handle(), kNullJSDispatchHandle);
      JSDispatchHandle dispatch_handle = feedback_cell->dispatch_handle();
      JSDispatchTable* jdt = IsolateGroup::current()->js_dispatch_table();
      Tagged<Code> old_code = jdt->GetCode(dispatch_handle);
      // A write barrier is needed when settings code, because the update can
      // race with marking which could leave the dispatch slot unmarked.
      // TODO(olivf): This should be fixed by using a more traditional WB
      // for dispatch handles (i.e. have a marking queue with dispatch handles
      // instead of marking through the handle).
      constexpr WriteBarrierMode mode_if_setting_code =
          WriteBarrierMode::UPDATE_WRITE_BARRIER;
      // TODO(olivf): We should go through the cases where this is still
      // needed and maybe find some alternative to initialize it correctly
      // from the beginning.
      if (old_code->is_builtin()) {
        jdt->SetCodeNoWriteBarrier(dispatch_handle, *code);
        function->set_dispatch_handle(dispatch_handle, mode_if_setting_code);
      } else {
        // On a transition of a feedback cell from one closure to many, make
        // sure that the code on the feedback cell isn't native context
        // specialized, and if it was, eagerly re-optimize.
        if (cell_transition == FeedbackCell::kOneToMany &&
            old_code->is_context_specialized()) {
          jdt->SetCodeNoWriteBarrier(dispatch_handle, *code);
          function->set_dispatch_handle(dispatch_handle, mode_if_setting_code);
          DCHECK(old_code->kind() == CodeKind::MAGLEV ||
                 old_code->kind() == CodeKind::TURBOFAN_JS);
          if (!old_code->marked_for_deoptimization()) {
            function->RequestOptimization(isolate, old_code->kind());
          }
        } else {
          function->set_dispatch_handle(dispatch_handle, mode);
        }
      }
    }
#else
    USE(cell_transition, many_closures_cell);
    function->UpdateCode(isolate, *code, mode);
#endif // V8_ENABLE_LEAPTIERING
    if (function->has_prototype_slot()) {
      function->set_prototype_or_initial_map(
          ReadOnlyRoots(isolate).the_hole_value(), kReleaseStore,
          SKIP_WRITE_BARRIER);
    }
    // Potentially body initialization.
    factory->InitializeJSObjectBody(
        function, *map, JSFunction::GetHeaderSize(map->has_prototype_slot()));
    function_handle = handle(function, isolate_);
  }
#ifdef V8_ENABLE_LEAPTIERING
  // If the FeedbackCell doesn't have a dispatch handle, we need to allocate a
  // dispatch entry now. This should only be the case for functions using the
  // generic many_closures_cell (for example builtin functions), and only for
  // functions using certain kinds of code.
  if (many_closures_cell) {
    // We currently only expect to see these kinds of Code here. For BASELINE
    // code, we will allocate a FeedbackCell after building the JSFunction. See
    // JSFunctionBuilder::Build.
    DCHECK(code->kind() == CodeKind::BUILTIN ||
           code->kind() == CodeKind::JS_TO_WASM_FUNCTION ||
           code->kind() == CodeKind::BASELINE);
    // TODO(saelo): in the future, we probably want to use
    // code->parameter_count() here instead, but not all Code objects know
    // their parameter count yet.
    function_handle->clear_dispatch_handle();
    HeapObject::AllocateAndInstallJSDispatchHandle(
        function_handle, JSFunction::kDispatchHandleOffset, isolate,
        sfi_->internal_formal_parameter_count_with_receiver(), code);
  } else {
    DCHECK_NE(function_handle->dispatch_handle(), kNullJSDispatchHandle);
  }
#endif
  return function_handle;
}
References v8::internal::HeapObject::AllocateAndInstallJSDispatchHandle(), BUILTIN, code, v8::internal::IsolateGroup::current(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::JSFunction::GetHeaderSize(), v8::internal::handle(), v8::internal::Factory::InitializeJSObjectBody(), v8::internal::Factory::isolate(), v8::internal::FeedbackCell::kMany, v8::internal::kNullJSDispatchHandle(), v8::internal::FeedbackCell::kOneToMany, v8::kReleaseStore, v8::internal::kYoung, mode(), v8::internal::Factory::New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, v8::internal::UPDATE_WRITE_BARRIER, and USE.
set_allocation_type()
JSFunctionBuilder& v8::internal::Factory::JSFunctionBuilder::set_allocation_type (AllocationType v) [inline]
Definition at line 1132 of file factory.h.
                                                             {
      allocation_type_ = v;
      return *this;
    }
set_feedback_cell()
JSFunctionBuilder& v8::internal::Factory::JSFunctionBuilder::set_feedback_cell (DirectHandle< FeedbackCell > v) [inline]
Definition at line 1136 of file factory.h.
                                                                       {
      maybe_feedback_cell_ = v;
      return *this;
    }
Referenced by v8::internal::RUNTIME_FUNCTION().
set_map()
JSFunctionBuilder& v8::internal::Factory::JSFunctionBuilder::set_map (DirectHandle< Map > v) [inline]
Definition at line 1128 of file factory.h.
                                                    {
      maybe_map_ = v;
      return *this;
    }
Friends And Related Function Documentation
Factory
friend class Factory [friend]
Definition at line 1151 of file factory.h.
Member Data Documentation
allocation_type_
AllocationType v8::internal::Factory::JSFunctionBuilder::allocation_type_ = AllocationType::kOld [private]
Definition at line 1149 of file factory.h.
context_
DirectHandle<Context> v8::internal::Factory::JSFunctionBuilder::context_ [private]
Definition at line 1146 of file factory.h.
isolate_
Isolate* const v8::internal::Factory::JSFunctionBuilder::isolate_ [private]
Definition at line 1144 of file factory.h.
maybe_feedback_cell_
MaybeDirectHandle<FeedbackCell> v8::internal::Factory::JSFunctionBuilder::maybe_feedback_cell_ [private]
Definition at line 1148 of file factory.h.
maybe_map_
MaybeDirectHandle<Map> v8::internal::Factory::JSFunctionBuilder::maybe_map_ [private]
Definition at line 1147 of file factory.h.
sfi_
DirectHandle<SharedFunctionInfo> v8::internal::Factory::JSFunctionBuilder::sfi_ [private]
Definition at line 1145 of file factory.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/factory.h
/mnt/V8SourceCode/src/heap/factory.cc