v8::internal::OffThreadObjectDeserializer Class Reference
#include <object-deserializer.h>
Static Public Member Functions
static MaybeDirectHandle< SharedFunctionInfo > DeserializeSharedFunctionInfo (LocalIsolate *isolate, const SerializedCodeData *data, std::vector< IndirectHandle< Script >> *deserialized_scripts)
Private Member Functions
OffThreadObjectDeserializer (LocalIsolate *isolate, const SerializedCodeData *data)
MaybeDirectHandle< HeapObject > Deserialize (std::vector< IndirectHandle< Script >> *deserialized_scripts)
Additional Inherited Members
Detailed Description
Definition at line 34 of file object-deserializer.h.
Constructor & Destructor Documentation
OffThreadObjectDeserializer()
v8::internal::OffThreadObjectDeserializer::OffThreadObjectDeserializer (LocalIsolate * isolate, const SerializedCodeData * data) [explicit], [private]
Definition at line 91 of file object-deserializer.cc.
    : Deserializer(isolate, data->Payload(), data->GetMagicNumber(), true,
                   false) {}
Member Function Documentation
Deserialize()
MaybeDirectHandle< HeapObject > v8::internal::OffThreadObjectDeserializer::Deserialize (std::vector< IndirectHandle< Script >> * deserialized_scripts) [private]
Definition at line 112 of file object-deserializer.cc.
                                                             {
  DCHECK(deserializing_user_code());
  LocalHandleScope scope(isolate());
  DirectHandle<HeapObject> result;
  {
    result = ReadObject();
    DeserializeDeferredObjects();
    CHECK(new_code_objects().empty());
    CHECK(new_allocation_sites().empty());
    CHECK(new_maps().empty());
    WeakenDescriptorArrays();
  }
  Rehash();
  // TODO(leszeks): Figure out a better way of dealing with scripts.
  CHECK_EQ(new_scripts().size(), 1);
  for (DirectHandle<Script> script : new_scripts()) {
    // Assign a new script id to avoid collision.
    script->set_id(isolate()->GetNextScriptId());
    LogScriptEvents(*script);
    deserialized_scripts->push_back(
        isolate()->heap()->NewPersistentHandle(script));
  }
  return scope.CloseAndEscape(result);
}
References CHECK, CHECK_EQ, v8::internal::DCHECK(), v8::internal::Deserializer< LocalIsolate >::DeserializeDeferredObjects(), v8::internal::Deserializer< LocalIsolate >::deserializing_user_code(), heap(), v8::internal::Deserializer< LocalIsolate >::isolate(), v8::internal::Deserializer< LocalIsolate >::LogScriptEvents(), v8::internal::Deserializer< LocalIsolate >::new_allocation_sites(), v8::internal::Deserializer< LocalIsolate >::new_code_objects(), v8::internal::Deserializer< LocalIsolate >::new_maps(), v8::internal::Deserializer< LocalIsolate >::new_scripts(), v8::internal::Deserializer< LocalIsolate >::ReadObject(), v8::internal::Deserializer< LocalIsolate >::Rehash(), v8::base::internal::result, v8::internal::script, size(), and v8::internal::Deserializer< LocalIsolate >::WeakenDescriptorArrays().
Referenced by DeserializeSharedFunctionInfo().
DeserializeSharedFunctionInfo()
MaybeDirectHandle< SharedFunctionInfo > v8::internal::OffThreadObjectDeserializer::DeserializeSharedFunctionInfo (LocalIsolate * isolate, const SerializedCodeData * data, std::vector< IndirectHandle< Script >> * deserialized_scripts) [static]
Definition at line 97 of file object-deserializer.cc.
                                                             {
  OffThreadObjectDeserializer d(isolate, data);
  // Attach the empty string as the source.
  d.AddAttachedObject(isolate->factory()->empty_string());
  DirectHandle<HeapObject> result;
  if (!d.Deserialize(deserialized_scripts).ToHandle(&result)) {
    return MaybeDirectHandle<SharedFunctionInfo>();
  }
  return Cast<SharedFunctionInfo>(result);
}
References v8::internal::Deserializer< IsolateT >::AddAttachedObject(), Deserialize(), v8::internal::LocalIsolate::factory(), v8::internal::Deserializer< LocalIsolate >::isolate(), and v8::base::internal::result.
Referenced by v8::internal::CodeSerializer::StartDeserializeOffThread().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/object-deserializer.h
/mnt/V8SourceCode/src/snapshot/object-deserializer.cc