v8::internal::RegExpClassRanges Class Reference
#include <regexp-ast.h>
Public Types
enum Flag { NEGATED = 1 << 0
, CONTAINS_SPLIT_SURROGATE = 1 << 1
, IS_CASE_FOLDED = 1 << 2
 }
using ClassRangesFlags = base::Flags< Flag >
Public Member Functions
RegExpClassRanges (Zone *zone, ZoneList< CharacterRange > *ranges, ClassRangesFlags class_ranges_flags=ClassRangesFlags())
RegExpClassRanges (StandardCharacterSet standard_set_type)
DECL_BOILERPLATE (ClassRanges)
bool IsTextElement () override
int min_match () override
int max_match () override
void AppendToText (RegExpText *text, Zone *zone) override
bool is_standard (Zone *zone)
StandardCharacterSet standard_type () const
CharacterSet character_set () const
ZoneList< CharacterRange > * ranges (Zone *zone)
bool is_negated () const
bool contains_split_surrogate () const
bool is_case_folded () const
Private Attributes
CharacterSet set_
ClassRangesFlags class_ranges_flags_
Additional Inherited Members
Detailed Description
Definition at line 305 of file regexp-ast.h.
Member Typedef Documentation
ClassRangesFlags
using v8::internal::RegExpClassRanges::ClassRangesFlags = base::Flags<Flag>
Definition at line 318 of file regexp-ast.h.
Member Enumeration Documentation
Flag
enum v8::internal::RegExpClassRanges::Flag
Enumerator
NEGATED
CONTAINS_SPLIT_SURROGATE
IS_CASE_FOLDED
Definition at line 313 of file regexp-ast.h.
            {
    NEGATED = 1 << 0,
    CONTAINS_SPLIT_SURROGATE = 1 << 1,
    IS_CASE_FOLDED = 1 << 2,
  };
Constructor & Destructor Documentation
RegExpClassRanges() [1/2]
v8::internal::RegExpClassRanges::RegExpClassRanges (Zone * zone, ZoneList< CharacterRange > * ranges, ClassRangesFlags class_ranges_flags = ClassRangesFlags()) [inline]
Definition at line 320 of file regexp-ast.h.
      : set_(ranges), class_ranges_flags_(class_ranges_flags) {
    // Convert the empty set of ranges to the negated Everything() range.
    if (ranges->is_empty()) {
      ranges->Add(CharacterRange::Everything(), zone);
      class_ranges_flags_ ^= NEGATED;
    }
  }
References class_ranges_flags_, v8::internal::CharacterRange::Everything(), NEGATED, and ranges().
RegExpClassRanges() [2/2]
v8::internal::RegExpClassRanges::RegExpClassRanges (StandardCharacterSet standard_set_type) [inline], [explicit]
Definition at line 329 of file regexp-ast.h.
      : set_(standard_set_type), class_ranges_flags_() {}
Member Function Documentation
AppendToText()
void v8::internal::RegExpClassRanges::AppendToText (RegExpText * text, Zone * zone) [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 201 of file regexp-compiler.cc.
                                                                 {
  text->AddElement(TextElement::ClassRanges(this), zone);
}
References v8::internal::RegExpText::AddElement(), and v8::internal::TextElement::ClassRanges().
character_set()
CharacterSet v8::internal::RegExpClassRanges::character_set () const [inline]
Definition at line 352 of file regexp-ast.h.
{ return set_; }
References set_.
contains_split_surrogate()
bool v8::internal::RegExpClassRanges::contains_split_surrogate () const [inline]
Definition at line 356 of file regexp-ast.h.
                                        {
    return (class_ranges_flags_ & CONTAINS_SPLIT_SURROGATE) != 0;
  }
References class_ranges_flags_, and CONTAINS_SPLIT_SURROGATE.
DECL_BOILERPLATE()
v8::internal::RegExpClassRanges::DECL_BOILERPLATE (ClassRanges)
is_case_folded()
bool v8::internal::RegExpClassRanges::is_case_folded () const [inline]
Definition at line 359 of file regexp-ast.h.
                              {
    return (class_ranges_flags_ & IS_CASE_FOLDED) != 0;
  }
References class_ranges_flags_, and IS_CASE_FOLDED.
is_negated()
bool v8::internal::RegExpClassRanges::is_negated () const [inline]
Definition at line 355 of file regexp-ast.h.
{ return (class_ranges_flags_ & NEGATED) != 0; }
References class_ranges_flags_, and NEGATED.
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), v8::internal::TextNode::FillInBMInfo(), v8::internal::TextNode::FilterOneByte(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::TextNode::GetSuccessorOfOmnivorousTextNode(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitClassRanges().
is_standard()
bool v8::internal::RegExpClassRanges::is_standard (Zone * zone)
Definition at line 96 of file regexp-compiler-tonode.cc.
                                              {
  // TODO(lrn): Remove need for this function, by not throwing away information
  // along the way.
  if (is_negated()) {
    return false;
  }
  if (set_.is_standard()) {
    return true;
  }
  if (CompareRanges(set_.ranges(zone), kSpaceRanges, kSpaceRangeCount)) {
    set_.set_standard_set_type(StandardCharacterSet::kWhitespace);
    return true;
  }
  if (CompareInverseRanges(set_.ranges(zone), kSpaceRanges, kSpaceRangeCount)) {
    set_.set_standard_set_type(StandardCharacterSet::kNotWhitespace);
    return true;
  }
  if (CompareInverseRanges(set_.ranges(zone), kLineTerminatorRanges,
                           kLineTerminatorRangeCount)) {
    set_.set_standard_set_type(StandardCharacterSet::kNotLineTerminator);
    return true;
  }
  if (CompareRanges(set_.ranges(zone), kLineTerminatorRanges,
                    kLineTerminatorRangeCount)) {
    set_.set_standard_set_type(StandardCharacterSet::kLineTerminator);
    return true;
  }
  if (CompareRanges(set_.ranges(zone), kWordRanges, kWordRangeCount)) {
    set_.set_standard_set_type(StandardCharacterSet::kWord);
    return true;
  }
  if (CompareInverseRanges(set_.ranges(zone), kWordRanges, kWordRangeCount)) {
    set_.set_standard_set_type(StandardCharacterSet::kNotWord);
    return true;
  }
  return false;
}
References v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareInverseRanges(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareRanges(), v8::internal::kLineTerminator, v8::internal::regexp_compiler_constants::kLineTerminatorRangeCount, v8::internal::regexp_compiler_constants::kLineTerminatorRanges, v8::internal::kNotLineTerminator, v8::internal::kNotWhitespace, v8::internal::kNotWord, v8::internal::regexp_compiler_constants::kSpaceRangeCount, v8::internal::regexp_compiler_constants::kSpaceRanges, v8::internal::kWhitespace, v8::internal::kWord, v8::internal::regexp_compiler_constants::kWordRangeCount, and v8::internal::regexp_compiler_constants::kWordRanges.
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), and v8::internal::TextNode::MakeCaseIndependent().
IsTextElement()
bool v8::internal::RegExpClassRanges::IsTextElement () [inline], [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 334 of file regexp-ast.h.
{ return true; }
max_match()
int v8::internal::RegExpClassRanges::max_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 339 of file regexp-ast.h.
{ return 2; }
min_match()
int v8::internal::RegExpClassRanges::min_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 335 of file regexp-ast.h.
{ return 1; }
ranges()
ZoneList<CharacterRange>* v8::internal::RegExpClassRanges::ranges (Zone * zone) [inline]
Definition at line 353 of file regexp-ast.h.
{ return set_.ranges(zone); }
References v8::internal::CharacterSet::ranges(), and set_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), v8::internal::TextNode::FillInBMInfo(), v8::internal::TextNode::FilterOneByte(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::TextNode::GetSuccessorOfOmnivorousTextNode(), v8::internal::TextNode::MakeCaseIndependent(), RegExpClassRanges(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitClassRanges().
standard_type()
StandardCharacterSet v8::internal::RegExpClassRanges::standard_type () const [inline]
Definition at line 348 of file regexp-ast.h.
                                             {
    return set_.standard_set_type();
  }
References set_, and v8::internal::CharacterSet::standard_set_type().
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges().
Member Data Documentation
class_ranges_flags_
ClassRangesFlags v8::internal::RegExpClassRanges::class_ranges_flags_ [private]
Definition at line 365 of file regexp-ast.h.
Referenced by contains_split_surrogate(), is_case_folded(), is_negated(), and RegExpClassRanges().
set_
CharacterSet v8::internal::RegExpClassRanges::set_ [private]
Definition at line 364 of file regexp-ast.h.
Referenced by character_set(), ranges(), and standard_type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-compiler-tonode.cc
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc