cppgc::internal::CrossThreadPersistentRegion Class Reference
#include <persistent-node.h>
Public Member Functions
CrossThreadPersistentRegion (const FatalOutOfMemoryHandler &)
~CrossThreadPersistentRegion ()
CrossThreadPersistentRegion (const CrossThreadPersistentRegion &)=delete
CrossThreadPersistentRegion & operator= (const CrossThreadPersistentRegion &)=delete
PersistentNode * AllocateNode (void *owner, TraceRootCallback trace)
void FreeNode (PersistentNode *node)
void Iterate (RootVisitor &)
size_t NodesInUse () const
void ClearAllUsedNodes ()
Additional Inherited Members
Detailed Description
Definition at line 184 of file persistent-node.h.
Constructor & Destructor Documentation
CrossThreadPersistentRegion() [1/2]
cppgc::internal::CrossThreadPersistentRegion::CrossThreadPersistentRegion (const FatalOutOfMemoryHandler & oom_handler) [explicit]
Definition at line 132 of file persistent-node.cc.
    : PersistentRegionBase(oom_handler) {}
 CrossThreadPersistentRegion()
cppgc::internal::CrossThreadPersistentRegion::~CrossThreadPersistentRegion ()
Definition at line 136 of file persistent-node.cc.
                                                          {
  PersistentRegionLock guard;
  PersistentRegionBase::ClearAllUsedNodes<CrossThreadPersistentBase>();
  nodes_.clear();
  // PersistentRegionBase destructor will be a noop.
}
References cppgc::internal::PersistentRegionBase::nodes_.
CrossThreadPersistentRegion() [2/2]
cppgc::internal::CrossThreadPersistentRegion::CrossThreadPersistentRegion (const CrossThreadPersistentRegion &) [delete]
Member Function Documentation
AllocateNode()
PersistentNode* cppgc::internal::CrossThreadPersistentRegion::AllocateNode (void * owner, TraceRootCallback trace) [inline]
Definition at line 195 of file persistent-node.h.
                                                                               {
    PersistentRegionLock::AssertLocked();
    auto* node = TryAllocateNodeFromFreeList(owner, trace);
    if (V8_LIKELY(node)) return node;
    return RefillFreeListAndAllocateNode(owner, trace);
  }
References cppgc::internal::PersistentRegionLock::AssertLocked(), and V8_LIKELY.
Referenced by cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicCrossThreadPersistent().
ClearAllUsedNodes()
void cppgc::internal::CrossThreadPersistentRegion::ClearAllUsedNodes ()
Definition at line 153 of file persistent-node.cc.
                                                    {
  PersistentRegionLock::AssertLocked();
  PersistentRegionBase::ClearAllUsedNodes<CrossThreadPersistentBase>();
}
References cppgc::internal::PersistentRegionLock::AssertLocked().
Referenced by cppgc::internal::HeapBase::Terminate().
FreeNode()
void cppgc::internal::CrossThreadPersistentRegion::FreeNode (PersistentNode * node) [inline]
Definition at line 203 of file persistent-node.h.
                                                {
    PersistentRegionLock::AssertLocked();
    PersistentRegionBase::FreeNode(node);
  }
References cppgc::internal::PersistentRegionLock::AssertLocked(), and cppgc::internal::PersistentRegionBase::FreeNode().
Referenced by cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignSafe(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignUnsafe(), and cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::~BasicCrossThreadPersistent().
Iterate()
void cppgc::internal::CrossThreadPersistentRegion::Iterate (RootVisitor & root_visitor)
Definition at line 143 of file persistent-node.cc.
                                                                   {
  PersistentRegionLock::AssertLocked();
  PersistentRegionBase::Iterate(root_visitor);
}
References cppgc::internal::PersistentRegionLock::AssertLocked(), and cppgc::internal::PersistentRegionBase::Iterate().
Referenced by cppgc::internal::MarkerBase::MarkStrongCrossThreadRoots(), cppgc::internal::MarkerBase::ProcessCrossThreadWeaknessIfNeeded(), and cppgc::internal::MarkerBase::VisitCrossThreadRoots().
NodesInUse()
size_t cppgc::internal::CrossThreadPersistentRegion::NodesInUse () const
Definition at line 148 of file persistent-node.cc.
                                                     {
  // This method does not require a lock.
  return PersistentRegionBase::NodesInUse();
}
References cppgc::internal::PersistentRegionBase::NodesInUse().
Referenced by cppgc::internal::HeapBase::Terminate().
operator=()
CrossThreadPersistentRegion& cppgc::internal::CrossThreadPersistentRegion::operator= (const CrossThreadPersistentRegion &) [delete]
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/internal/persistent-node.h
/mnt/V8SourceCode/src/heap/cppgc/persistent-node.cc