v8::internal::Sweeper::MajorSweeperJob Class Reference
Public Member Functions
MajorSweeperJob (Isolate *isolate, Sweeper *sweeper)
~MajorSweeperJob () override=default
MajorSweeperJob (const MajorSweeperJob &)=delete
MajorSweeperJob & operator= (const MajorSweeperJob &)=delete
void Run (JobDelegate *delegate) final
size_t GetMaxConcurrency (size_t worker_count) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Static Public Attributes
static constexpr int kMaxTasks = kNumberOfMajorSweepingSpaces
Private Member Functions
void RunImpl (JobDelegate *delegate, bool is_main_thread)
Private Attributes
Sweeper *const sweeper_
std::vector< ConcurrentMajorSweeper > & concurrent_sweepers
GCTracer *const tracer_
const uint64_t trace_id_
Static Private Attributes
static constexpr int kNumberOfMajorSweepingSpaces
Detailed Description
Definition at line 108 of file sweeper.cc.
Constructor & Destructor Documentation
MajorSweeperJob() [1/2]
v8::internal::Sweeper::MajorSweeperJob::MajorSweeperJob (Isolate * isolate, Sweeper * sweeper) [inline]
Definition at line 117 of file sweeper.cc.
      : sweeper_(sweeper),
        concurrent_sweepers(
            sweeper_->major_sweeping_state_.concurrent_sweepers()),
        tracer_(isolate->heap()->tracer()),
        trace_id_(sweeper_->major_sweeping_state_.background_trace_id()) {
    DCHECK_LE(concurrent_sweepers.size(), kMaxTasks);
  }
References concurrent_sweepers, DCHECK_LE, and kMaxTasks.
 MajorSweeperJob()
v8::internal::Sweeper::MajorSweeperJob::~MajorSweeperJob () [override], [default]
MajorSweeperJob() [2/2]
v8::internal::Sweeper::MajorSweeperJob::MajorSweeperJob (const MajorSweeperJob &) [delete]
Member Function Documentation
GetMaxConcurrency()
size_t v8::internal::Sweeper::MajorSweeperJob::GetMaxConcurrency (size_t worker_count) const [inline], [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 144 of file sweeper.cc.
                                                               {
    static constexpr int kPagePerTask = 2;
    return std::min<size_t>(
        concurrent_sweepers.size(),
        worker_count +
            (sweeper_->ConcurrentMajorSweepingPageCount() + kPagePerTask - 1) /
                kPagePerTask);
  }
References concurrent_sweepers, v8::internal::Sweeper::ConcurrentMajorSweepingPageCount(), and sweeper_.
operator=()
MajorSweeperJob& v8::internal::Sweeper::MajorSweeperJob::operator= (const MajorSweeperJob &) [delete]
Run()
void v8::internal::Sweeper::MajorSweeperJob::Run (JobDelegate * delegate) [inline], [final], [virtual]
Implements v8::JobTask.
Definition at line 131 of file sweeper.cc.
                                        {
    DCHECK_IMPLIES(
        delegate->IsJoiningThread(),
        sweeper_->heap_->IsMainThread() ||
            (!sweeper_->heap_->isolate()->is_shared_space_isolate() &&
             sweeper_->heap_->isolate()
                 ->shared_space_isolate()
                 ->heap()
                 ->IsMainThread()));
    RunImpl(delegate,
            delegate->IsJoiningThread() && sweeper_->heap_->IsMainThread());
  }
References DCHECK_IMPLIES, v8::internal::Isolate::heap(), v8::internal::Sweeper::heap_, v8::internal::Isolate::is_shared_space_isolate(), v8::internal::Heap::IsMainThread(), v8::internal::Heap::isolate(), RunImpl(), v8::internal::Isolate::shared_space_isolate(), and sweeper_.
RunImpl()
void v8::internal::Sweeper::MajorSweeperJob::RunImpl (JobDelegate * delegate, bool is_main_thread) [inline], [private]
Definition at line 154 of file sweeper.cc.
                                                           {
    // Set the current isolate such that trusted pointer tables etc are
    // available and the cage base is set correctly for multi-cage mode.
    SetCurrentIsolateScope isolate_scope(sweeper_->heap_->isolate());
    DCHECK(sweeper_->major_sweeping_in_progress());
    const int offset = delegate->GetTaskId();
    DCHECK_LT(offset, concurrent_sweepers.size());
    ConcurrentMajorSweeper& concurrent_sweeper = concurrent_sweepers[offset];
    TRACE_GC_EPOCH_WITH_FLOW(
        tracer_, sweeper_->GetTracingScope(OLD_SPACE, is_main_thread),
        is_main_thread ? ThreadKind::kMain : ThreadKind::kBackground, trace_id_,
        TRACE_EVENT_FLAG_FLOW_IN);
    for (int i = 0; i < kNumberOfMajorSweepingSpaces; i++) {
      const AllocationSpace space_id = static_cast<AllocationSpace>(
          FIRST_SWEEPABLE_SPACE + 1 +
          ((offset + i) % kNumberOfMajorSweepingSpaces));
      DCHECK_LE(FIRST_SWEEPABLE_SPACE, space_id);
      DCHECK_LE(space_id, LAST_SWEEPABLE_SPACE);
      DCHECK_NE(NEW_SPACE, space_id);
      if (!concurrent_sweeper.ConcurrentSweepSpace(space_id, delegate)) return;
    }
  }
References concurrent_sweepers, v8::internal::Sweeper::ConcurrentMajorSweeper::ConcurrentSweepSpace(), v8::internal::DCHECK(), DCHECK_LE, DCHECK_LT, DCHECK_NE, v8::internal::FIRST_SWEEPABLE_SPACE, v8::JobDelegate::GetTaskId(), v8::internal::Sweeper::GetTracingScope(), v8::internal::Sweeper::heap_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Heap::isolate(), v8::internal::kBackground, v8::internal::kMain, kNumberOfMajorSweepingSpaces, v8::internal::LAST_SWEEPABLE_SPACE, v8::internal::Sweeper::major_sweeping_in_progress(), v8::internal::NEW_SPACE, v8::internal::OLD_SPACE, sweeper_, TRACE_EVENT_FLAG_FLOW_IN, TRACE_GC_EPOCH_WITH_FLOW, trace_id_, and tracer_.
Referenced by Run().
Member Data Documentation
concurrent_sweepers
std::vector<ConcurrentMajorSweeper>& v8::internal::Sweeper::MajorSweeperJob::concurrent_sweepers [private]
Definition at line 179 of file sweeper.cc.
Referenced by GetMaxConcurrency(), MajorSweeperJob(), and RunImpl().
kMaxTasks
constexpr int v8::internal::Sweeper::MajorSweeperJob::kMaxTasks = kNumberOfMajorSweepingSpaces [static], [constexpr]
Definition at line 115 of file sweeper.cc.
Referenced by MajorSweeperJob().
kNumberOfMajorSweepingSpaces
constexpr int v8::internal::Sweeper::MajorSweeperJob::kNumberOfMajorSweepingSpaces [static], [constexpr], [private]
Initial value:
=
      kNumberOfSweepingSpaces - 1
Definition at line 111 of file sweeper.cc.
Referenced by RunImpl().
sweeper_
Sweeper* const v8::internal::Sweeper::MajorSweeperJob::sweeper_ [private]
Definition at line 178 of file sweeper.cc.
Referenced by GetMaxConcurrency(), Run(), and RunImpl().
trace_id_
const uint64_t v8::internal::Sweeper::MajorSweeperJob::trace_id_ [private]
Definition at line 181 of file sweeper.cc.
Referenced by RunImpl().
tracer_
GCTracer* const v8::internal::Sweeper::MajorSweeperJob::tracer_ [private]
Definition at line 180 of file sweeper.cc.
Referenced by RunImpl().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/sweeper.cc