v8::internal::interpreter::BytecodeGenerator::ControlScopeForTopLevel Class Reference
Public Member Functions
ControlScopeForTopLevel (BytecodeGenerator *generator)
Protected Member Functions
bool Execute (Command command, Statement *statement, int source_position) override
Additional Inherited Members
Detailed Description
Definition at line 406 of file bytecode-generator.cc.
Constructor & Destructor Documentation
ControlScopeForTopLevel()
v8::internal::interpreter::BytecodeGenerator::ControlScopeForTopLevel::ControlScopeForTopLevel (BytecodeGenerator * generator) [inline], [explicit]
Definition at line 409 of file bytecode-generator.cc.
      : ControlScope(generator) {}
Member Function Documentation
Execute()
bool v8::internal::interpreter::BytecodeGenerator::ControlScopeForTopLevel::Execute (Command command, Statement * statement, int source_position) [inline], [override], [protected], [virtual]
Implements v8::internal::interpreter::BytecodeGenerator::ControlScope.
Definition at line 413 of file bytecode-generator.cc.
                                             {
    switch (command) {
      case CMD_BREAK: // We should never see break/continue in top-level.
      case CMD_CONTINUE:
        UNREACHABLE();
      case CMD_RETURN:
        // No need to pop contexts, execution leaves the method body.
        generator()->BuildReturn(source_position);
        return true;
      case CMD_ASYNC_RETURN:
        // No need to pop contexts, execution leaves the method body.
        generator()->BuildAsyncReturn(source_position);
        return true;
      case CMD_RETHROW:
        // No need to pop contexts, execution leaves the method body.
        generator()->BuildReThrow();
        return true;
    }
    return false;
  }
References v8::internal::interpreter::BytecodeGenerator::BuildAsyncReturn(), v8::internal::interpreter::BytecodeGenerator::BuildReThrow(), v8::internal::interpreter::BytecodeGenerator::BuildReturn(), v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_ASYNC_RETURN, v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_BREAK, v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_CONTINUE, v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_RETHROW, v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_RETURN, v8::internal::interpreter::BytecodeGenerator::ControlScope::generator(), and v8::internal::UNREACHABLE().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc