v8::internal::LowDwVfpRegister Class Reference
#include <register-arm.h>
Public Member Functions
constexpr operator DwVfpRegister () const
SwVfpRegister low () const
SwVfpRegister high () const
VfpRegList ToVfpRegList () const
Private Member Functions
constexpr LowDwVfpRegister (int code)
Friends
class RegisterBase
Additional Inherited Members
Detailed Description
Definition at line 195 of file register-arm.h.
Constructor & Destructor Documentation
LowDwVfpRegister()
constexpr v8::internal::LowDwVfpRegister::LowDwVfpRegister (int code) [inline], [explicit], [constexpr], [private]
Definition at line 211 of file register-arm.h.
: RegisterBase(code) {}
Member Function Documentation
high()
SwVfpRegister v8::internal::LowDwVfpRegister::high () const [inline]
Definition at line 201 of file register-arm.h.
                             {
    return SwVfpRegister::from_code(code() * 2 + 1);
  }
References v8::internal::RegisterBase< LowDwVfpRegister, kDoubleCode_d16 >::code(), and v8::internal::RegisterBase< SwVfpRegister, kSwVfpAfterLast >::from_code().
Referenced by v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_demote_f64x2_zero(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_div(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_sqrt(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_trunc_sat_f64x2_s_zero(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_trunc_sat_f64x2_u_zero(), and v8::internal::wasm::LiftoffAssembler::emit_s128_store_nonzero_if_nan().
low()
SwVfpRegister v8::internal::LowDwVfpRegister::low () const [inline]
Definition at line 200 of file register-arm.h.
{ return SwVfpRegister::from_code(code() * 2); }
References v8::internal::RegisterBase< LowDwVfpRegister, kDoubleCode_d16 >::code(), and v8::internal::RegisterBase< SwVfpRegister, kSwVfpAfterLast >::from_code().
Referenced by v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_demote_f64x2_zero(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_div(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_sqrt(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_trunc_sat_f64x2_s_zero(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_trunc_sat_f64x2_u_zero(), v8::internal::wasm::LiftoffAssembler::emit_s128_store_nonzero_if_nan(), v8::internal::wasm::liftoff::GetFloatRegister(), v8::internal::maglev::MaglevAssembler::Int32ToDouble(), v8::internal::maglev::MaglevAssembler::LoadFloat32(), v8::internal::maglev::MaglevAssembler::TryChangeFloat64ToIndex(), v8::internal::maglev::MaglevAssembler::TryTruncateDoubleToInt32(), v8::internal::maglev::MaglevAssembler::TryTruncateDoubleToUint32(), v8::internal::maglev::anonymous_namespace{maglev-ir-arm.cc}::Uint32Mod(), and v8::internal::maglev::MaglevAssembler::Uint32ToDouble().
operator DwVfpRegister()
constexpr v8::internal::LowDwVfpRegister::operator DwVfpRegister () const [inline], [constexpr]
Definition at line 198 of file register-arm.h.
{ return DwVfpRegister(code()); }
References v8::internal::RegisterBase< LowDwVfpRegister, kDoubleCode_d16 >::code().
ToVfpRegList()
VfpRegList v8::internal::LowDwVfpRegister::ToVfpRegList () const [inline]
Definition at line 204 of file register-arm.h.
                                  {
    // A D register overlaps two S registers.
    return uint64_t{0x3} << (code() * 2);
  }
References v8::internal::RegisterBase< LowDwVfpRegister, kDoubleCode_d16 >::code().
Friends And Related Function Documentation
RegisterBase
friend class RegisterBase [friend]
Definition at line 210 of file register-arm.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/arm/register-arm.h