v8::internal::CppBuiltinsAdaptorAssembler Class Reference
Public Types
using Descriptor = CppBuiltinAdaptorDescriptor
Public Member Functions
CppBuiltinsAdaptorAssembler (compiler::CodeAssemblerState *state)
void GenerateAdaptor (int formal_parameter_count)
Additional Inherited Members
Detailed Description
Definition at line 1244 of file builtins-internal-gen.cc.
Member Typedef Documentation
Descriptor
using v8::internal::CppBuiltinsAdaptorAssembler::Descriptor = CppBuiltinAdaptorDescriptor
Definition at line 1246 of file builtins-internal-gen.cc.
Constructor & Destructor Documentation
CppBuiltinsAdaptorAssembler()
v8::internal::CppBuiltinsAdaptorAssembler::CppBuiltinsAdaptorAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 1248 of file builtins-internal-gen.cc.
      : CodeStubAssembler(state) {}
Member Function Documentation
GenerateAdaptor()
void v8::internal::CppBuiltinsAdaptorAssembler::GenerateAdaptor (int formal_parameter_count)
Definition at line 1254 of file builtins-internal-gen.cc.
                                                                            {
  auto context = Parameter<Context>(Descriptor::kContext);
  auto target = Parameter<JSFunction>(Descriptor::kTarget);
  auto new_target = Parameter<Object>(Descriptor::kNewTarget);
  auto c_function = UncheckedParameter<WordT>(Descriptor::kCFunction);
  auto actual_argc =
      UncheckedParameter<Int32T>(Descriptor::kActualArgumentsCount);
  // The logic contained here is mirrored for TurboFan inlining in
  // JSTypedLowering::ReduceJSCall{Function,Construct}. Keep these in sync.
  // Make sure we operate in the context of the called function.
  CSA_DCHECK(this, TaggedEqual(context, LoadJSFunctionContext(target)));
  static_assert(kDontAdaptArgumentsSentinel == 0);
  // The code below relies on |actual_argc| to include receiver.
  static_assert(i::JSParameterCount(0) == 1);
  TVARIABLE(Int32T, pushed_argc, actual_argc);
  // It's guaranteed that the receiver is pushed to the stack, thus both
  // kDontAdaptArgumentsSentinel and JSParameterCount(0) cases don't require
  // arguments adaptation. Just use the latter version for consistency.
  DCHECK_NE(kDontAdaptArgumentsSentinel, formal_parameter_count);
  if (formal_parameter_count > i::JSParameterCount(0)) {
    TNode<Int32T> formal_count = Int32Constant(formal_parameter_count);
    // The number of arguments pushed is the maximum of actual arguments count
    // and formal parameters count.
    Label done_argc(this);
    GotoIf(Int32GreaterThanOrEqual(pushed_argc.value(), formal_count),
           &done_argc);
    // Update pushed args.
    pushed_argc = formal_count;
    Goto(&done_argc);
    BIND(&done_argc);
  }
  // Update arguments count for CEntry to contain the number of arguments
  // including the receiver and the extra arguments.
  TNode<Int32T> argc =
      Int32Add(pushed_argc.value(),
               Int32Constant(BuiltinExitFrameConstants::kNumExtraArgs));
  const bool builtin_exit_frame = true;
  const bool switch_to_central_stack = false;
  Builtin centry = Builtins::CEntry(1, ArgvMode::kStack, builtin_exit_frame,
                                    switch_to_central_stack);
  static_assert(BuiltinArguments::kNewTargetIndex == 0);
  static_assert(BuiltinArguments::kTargetIndex == 1);
  static_assert(BuiltinArguments::kArgcIndex == 2);
  static_assert(BuiltinArguments::kPaddingIndex == 3);
  // Unconditionally push argc, target and new target as extra stack arguments.
  // They will be used by stack frame iterators when constructing stack trace.
  TailCallBuiltin(centry, context, // standard arguments for TailCallBuiltin
                  argc, c_function, // register arguments
                  TheHoleConstant(), // additional stack argument 1 (padding)
                  SmiFromInt32(argc), // additional stack argument 2
                  target, // additional stack argument 3
                  new_target); // additional stack argument 4
}
References v8::internal::Builtins::CEntry(), DCHECK_NE, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::Int32Add(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::JSParameterCount(), v8::internal::BuiltinArguments::kArgcIndex, v8::internal::kDontAdaptArgumentsSentinel, v8::internal::BuiltinArguments::kNewTargetIndex, v8::internal::BuiltinExitFrameConstants::kNumExtraArgs, v8::internal::BuiltinArguments::kPaddingIndex, v8::internal::kStack, v8::internal::BuiltinArguments::kTargetIndex, v8::internal::CodeStubAssembler::SmiFromInt32(), v8::internal::CodeStubAssembler::TaggedEqual(), and v8::internal::compiler::CodeAssembler::TailCallBuiltin().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-internal-gen.cc