v8::internal::maglev::IntPtrToBoolean Class Reference
#include <maglev-ir.h>
Public Member Functions
IntPtrToBoolean (uint64_t bitfield, bool flip)
Input & value ()
constexpr bool flip () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kIntPtr}
Private Types
using Base = FixedInputValueNodeT< 1, IntPtrToBoolean >
using FlipBitField = NextBitField< bool, 1 >
Additional Inherited Members
Detailed Description
Definition at line 3344 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::IntPtrToBoolean::Base = FixedInputValueNodeT<1, IntPtrToBoolean> [private]
Definition at line 3345 of file maglev-ir.h.
FlipBitField
using v8::internal::maglev::IntPtrToBoolean::FlipBitField = NextBitField<bool, 1> [private]
Definition at line 3364 of file maglev-ir.h.
Constructor & Destructor Documentation
IntPtrToBoolean()
v8::internal::maglev::IntPtrToBoolean::IntPtrToBoolean (uint64_t bitfield, bool flip) [inline], [explicit]
Definition at line 3348 of file maglev-ir.h.
      : Base(FlipBitField::update(bitfield, flip)) {}
Member Function Documentation
flip()
constexpr bool v8::internal::maglev::IntPtrToBoolean::flip () const [inline], [constexpr]
Definition at line 3355 of file maglev-ir.h.
{ return FlipBitField::decode(bitfield()); }
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), options(), and PrintParams().
GenerateCode()
void v8::internal::maglev::IntPtrToBoolean::GenerateCode (MaglevAssembler * , const ProcessingState &)
options()
auto v8::internal::maglev::IntPtrToBoolean::options () const [inline]
Definition at line 3361 of file maglev-ir.h.
{ return std::tuple{flip()}; }
References flip().
PrintParams()
void v8::internal::maglev::IntPtrToBoolean::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8330 of file maglev-ir.cc.
                                                                             {
  if (flip()) {
    os << "(flipped)";
  }
}
References flip().
SetValueLocationConstraints()
void v8::internal::maglev::IntPtrToBoolean::SetValueLocationConstraints ()
value()
Input& v8::internal::maglev::IntPtrToBoolean::value () [inline]
Definition at line 3353 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::IntPtrToBoolean::kInputTypes {ValueRepresentation::kIntPtr} [static], [constexpr]
Definition at line 3351 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc