v8::internal::ObjectLock Class Reference
#include <object-lock.h>
Static Public Member Functions
static void Lock (Tagged< HeapObject > heap_object)
static void Unlock (Tagged< HeapObject > heap_object)
Detailed Description
Definition at line 13 of file object-lock.h.
Member Function Documentation
Lock()
void v8::internal::ObjectLock::Lock (Tagged< HeapObject > heap_object) [inline], [static]
Definition at line 17 of file object-lock-inl.h.
                                                    {
  MutablePageMetadata::FromHeapObject(heap_object)->object_mutex().Lock();
}
References v8::internal::MutablePageMetadata::FromHeapObject(), v8::base::Mutex::Lock(), and v8::internal::MutablePageMetadata::object_mutex().
Referenced by v8::internal::Heap::NotifyObjectLayoutChange(), and v8::internal::ObjectLockGuard::ObjectLockGuard().
Unlock()
void v8::internal::ObjectLock::Unlock (Tagged< HeapObject > heap_object) [inline], [static]
Definition at line 22 of file object-lock-inl.h.
                                                      {
  MutablePageMetadata::FromHeapObject(heap_object)->object_mutex().Unlock();
}
References v8::internal::MutablePageMetadata::FromHeapObject(), v8::internal::MutablePageMetadata::object_mutex(), and v8::base::Mutex::Unlock().
Referenced by v8::internal::Heap::NotifyObjectLayoutChangeDone(), and v8::internal::ObjectLockGuard::~ObjectLockGuard().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/object-lock.h
/mnt/V8SourceCode/src/heap/object-lock-inl.h