v8::SymbolObject Class Reference
A Symbol object (ECMA-262 edition 6).
#include <v8-primitive-object.h>
Public Member Functions
Local< Symbol > ValueOf () const
Static Public Member Functions
static Local< Value > New (Isolate *isolate, Local< Symbol > value)
static SymbolObject * Cast (Value *value)
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
A Symbol object (ECMA-262 edition 6).
Definition at line 99 of file v8-primitive-object.h.
Member Function Documentation
Cast()
static SymbolObject* v8::SymbolObject::Cast (Value * value) [inline], [static]
Definition at line 105 of file v8-primitive-object.h.
                                                    {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<SymbolObject*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::SymbolObject::CheckCast (v8::Value * that) [static], [private]
Definition at line 4141 of file api.cc.
                                            {
  auto obj = *Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsSymbolWrapper(obj), "v8::SymbolObject::Cast()",
                  "Value is not a SymbolObject");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
New()
Local< v8::Value > v8::SymbolObject::New (Isolate * isolate, Local< Symbol > value) [static]
Definition at line 7927 of file api.cc.
                                                            {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_SymbolObject_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::Object> obj =
      i::Object::ToObject(i_isolate, Utils::OpenDirectHandle(*value))
          .ToHandleChecked();
  return Utils::ToLocal(obj);
}
References v8::Utils::OpenDirectHandle(), v8::anonymous_namespace{api.cc}::ToObject(), and v8::internal::value.
ValueOf()
Local< v8::Symbol > v8::SymbolObject::ValueOf () const
Definition at line 7938 of file api.cc.
                                              {
  auto obj = Utils::OpenDirectHandle(this);
  auto js_primitive_wrapper = i::Cast<i::JSPrimitiveWrapper>(obj);
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_SymbolObject_SymbolValue);
  return Utils::ToLocal(i::direct_handle(
      i::Cast<i::Symbol>(js_primitive_wrapper->value()), i_isolate));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive-object.h
/mnt/V8SourceCode/src/api/api.cc