v8::internal::FrameSummary Class Reference
#include <frames.h>
Classes
class FrameSummaryBase
class JavaScriptFrameSummary
Public Types
enum Kind { FRAME_SUMMARY_VARIANTS =(FRAME_SUMMARY_KIND)
 }
Public Member Functions
~FrameSummary ()
void EnsureSourcePositionsAvailable ()
bool AreSourcePositionsAvailable () const
Handle< Object > receiver () const
int code_offset () const
bool is_constructor () const
bool is_subject_to_debugging () const
Handle< Object > script () const
int SourcePosition () const
int SourceStatementPosition () const
DirectHandle< Context > native_context () const
DirectHandle< StackFrameInfo > CreateStackFrameInfo () const
Static Public Member Functions
static FrameSummary GetTop (const CommonFrame *frame)
static FrameSummary GetBottom (const CommonFrame *frame)
static FrameSummary GetSingle (const CommonFrame *frame)
static FrameSummary Get (const CommonFrame *frame, int index)
Private Attributes
xx xx xx xx xx xx xx xx xx
union {
 FrameSummaryBase base_
};
Detailed Description
Definition at line 407 of file frames.h.
Member Enumeration Documentation
Kind
enum v8::internal::FrameSummary::Kind
Enumerator
FRAME_SUMMARY_VARIANTS
Definition at line 420 of file frames.h.
{ FRAME_SUMMARY_VARIANTS(FRAME_SUMMARY_KIND) };
Constructor & Destructor Documentation
 FrameSummary()
v8::internal::FrameSummary::~FrameSummary ()
Definition at line 2948 of file frames.cc.
                            {
#define FRAME_SUMMARY_DESTR(kind, type, field, desc) \
  case kind: \
    field.~type(); \
    break;
  switch (base_.kind()) {
    FRAME_SUMMARY_VARIANTS(FRAME_SUMMARY_DESTR)
    default:
      UNREACHABLE();
  }
#undef FRAME_SUMMARY_DESTR
}
References base_, FRAME_SUMMARY_DESTR, FRAME_SUMMARY_VARIANTS, v8::internal::FrameSummary::FrameSummaryBase::kind(), and v8::internal::UNREACHABLE().
Member Function Documentation
AreSourcePositionsAvailable()
bool v8::internal::FrameSummary::AreSourcePositionsAvailable () const
Definition at line 2713 of file frames.cc.
                                                     {
  if (IsJavaScript()) {
    return javascript_summary_.AreSourcePositionsAvailable();
  }
  return true;
}
Referenced by v8::internal::Isolate::ComputeLocation().
code_offset()
int v8::internal::FrameSummary::code_offset () const
Referenced by v8::internal::BreakLocation::AllAtCurrentStatement(), v8::internal::Debug::Break(), v8::internal::Isolate::ComputeLocation(), v8::internal::FrameSummary::JavaScriptFrameSummary::CreateStackFrameInfo(), v8::internal::BreakLocation::FromFrame(), v8::internal::Compiler::GetFunctionFromEval(), v8::internal::UnoptimizedJSFrame::position(), v8::internal::anonymous_namespace{isolate.cc}::PredictException(), v8::internal::Debug::PrepareStepOnThrow(), v8::internal::FrameSummary::JavaScriptFrameSummary::SourcePosition(), v8::internal::FrameSummary::JavaScriptFrameSummary::SourceStatementPosition(), and v8::internal::OptimizedJSFrame::Summarize().
CreateStackFrameInfo()
DirectHandle<StackFrameInfo> v8::internal::FrameSummary::CreateStackFrameInfo () const
Referenced by v8::internal::anonymous_namespace{isolate.cc}::StackFrameBuilder::Visit().
EnsureSourcePositionsAvailable()
void v8::internal::FrameSummary::EnsureSourcePositionsAvailable ()
Definition at line 2707 of file frames.cc.
                                                  {
  if (IsJavaScript()) {
    javascript_summary_.EnsureSourcePositionsAvailable();
  }
}
Referenced by v8::internal::FrameInspector::FrameInspector(), and v8::internal::Debug::ShouldBeSkipped().
Get()
FrameSummary v8::internal::FrameSummary::Get (const CommonFrame * frame, int index) [static]
Definition at line 2977 of file frames.cc.
                                                                  {
  DCHECK_LE(0, index);
  FrameSummaries summaries = frame->Summarize();
  DCHECK_GT(summaries.size(), index);
  return summaries.frames[index];
}
References DCHECK_GT, DCHECK_LE, v8::internal::FrameSummaries::frames, v8::internal::index, v8::internal::FrameSummaries::size(), and v8::internal::CommonFrame::Summarize().
Referenced by v8::internal::DebugStackTraceIterator::Advance(), v8::internal::FrameInspector::FrameInspector(), and GetBottom().
GetBottom()
FrameSummary v8::internal::FrameSummary::GetBottom (const CommonFrame * frame) [static]
Definition at line 2967 of file frames.cc.
                                                             {
  return Get(frame, 0);
}
References Get().
GetSingle()
FrameSummary v8::internal::FrameSummary::GetSingle (const CommonFrame * frame) [static]
Definition at line 2971 of file frames.cc.
                                                             {
  FrameSummaries summaries = frame->Summarize();
  DCHECK_EQ(1, summaries.size());
  return summaries.frames.front();
}
References DCHECK_EQ, v8::internal::FrameSummaries::frames, v8::internal::FrameSummaries::size(), and v8::internal::CommonFrame::Summarize().
GetTop()
FrameSummary v8::internal::FrameSummary::GetTop (const CommonFrame * frame) [static]
Definition at line 2961 of file frames.cc.
                                                          {
  FrameSummaries summaries = frame->Summarize();
  DCHECK_LT(0, summaries.size());
  return summaries.frames.back();
}
References DCHECK_LT, v8::internal::FrameSummaries::frames, v8::internal::FrameSummaries::size(), and v8::internal::CommonFrame::Summarize().
Referenced by v8::internal::BreakLocation::AllAtCurrentStatement(), v8::internal::Debug::Break(), v8::internal::BreakLocation::FromFrame(), v8::internal::BreakLocation::IsPausedInJsFunctionEntry(), v8::internal::Debug::OnException(), and v8::internal::Debug::PrepareStep().
is_constructor()
bool v8::internal::FrameSummary::is_constructor () const
Referenced by v8::internal::FrameSummary::JavaScriptFrameSummary::CreateStackFrameInfo(), v8::internal::FrameInspector::FrameInspector(), and v8::internal::OptimizedJSFrame::Summarize().
is_subject_to_debugging()
bool v8::internal::FrameSummary::is_subject_to_debugging () const
Referenced by v8::internal::DebugStackTraceIterator::Advance(), v8::internal::DebuggableStackFrameIterator::GetTopValidFrame(), v8::internal::anonymous_namespace{isolate.cc}::StackFrameBuilder::Visit(), v8::internal::anonymous_namespace{isolate.cc}::CurrentScriptNameStackVisitor::Visit(), and v8::internal::anonymous_namespace{isolate.cc}::CurrentScriptStackVisitor::Visit().
native_context()
DirectHandle<Context> v8::internal::FrameSummary::native_context () const
receiver()
Handle<Object> v8::internal::FrameSummary::receiver () const
Referenced by v8::internal::FrameInspector::FrameInspector(), v8::internal::JavaScriptFrame::Print(), v8::internal::OptimizedJSFrame::Summarize(), and v8::internal::UnoptimizedJSFrame::Summarize().
script()
Handle<Object> v8::internal::FrameSummary::script () const
Referenced by v8::internal::Isolate::ComputeLocation(), v8::internal::FrameSummary::JavaScriptFrameSummary::CreateStackFrameInfo(), v8::internal::FrameInspector::FrameInspector(), v8::internal::Compiler::GetFunctionFromEval(), v8::internal::JavaScriptFrame::Print(), v8::internal::JsonParser< Char >::ReportUnexpectedToken(), v8::internal::Debug::ShouldBeSkipped(), v8::internal::anonymous_namespace{isolate.cc}::CurrentScriptNameStackVisitor::Visit(), and v8::internal::anonymous_namespace{isolate.cc}::CurrentScriptStackVisitor::Visit().
SourcePosition()
int v8::internal::FrameSummary::SourcePosition () const
Referenced by v8::internal::Isolate::ComputeLocation(), v8::internal::FrameInspector::FrameInspector(), and v8::internal::Debug::ShouldBeSkipped().
SourceStatementPosition()
int v8::internal::FrameSummary::SourceStatementPosition () const
Referenced by v8::internal::Debug::Break().
Member Data Documentation
union { ... } [private]
base_
FrameSummaryBase v8::internal::FrameSummary::base_
Definition at line 616 of file frames.h.
Referenced by ~FrameSummary().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames.cc