v8::internal::BaseConsumedPreparseData< Data >::ByteData Class Reference
#include <preparse-data-impl.h>
Classes
class ReadingScope
Public Member Functions
void SetPosition (int position)
size_t RemainingBytes () const
bool HasRemainingBytes (size_t bytes) const
int32_t ReadUint32 ()
int32_t ReadVarint32 ()
uint8_t ReadUint8 ()
uint8_t ReadQuarter ()
Private Attributes
Data data_ = {}
int index_ = 0
uint8_t stored_quarters_ = 0
uint8_t stored_byte_ = 0
Additional Inherited Members
Detailed Description
template<class Data>
class v8::internal::BaseConsumedPreparseData< Data >::ByteData
Definition at line 47 of file preparse-data-impl.h.
Member Function Documentation
HasRemainingBytes()
template<class Data >
bool v8::internal::BaseConsumedPreparseData< Data >::ByteData::HasRemainingBytes (size_t bytes) const [inline]
Definition at line 85 of file preparse-data-impl.h.
                                               {
      DCHECK(has_data_);
      return index_ <= data_->data_length() && bytes <= RemainingBytes();
    }
References v8::internal::BaseConsumedPreparseData< Data >::ByteData::data_, v8::internal::DCHECK(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::index_, and v8::internal::BaseConsumedPreparseData< Data >::ByteData::RemainingBytes().
Referenced by v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadQuarter(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadUint32(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadUint8(), and v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadVarint32().
ReadQuarter()
template<class Data >
uint8_t v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadQuarter () [inline]
Definition at line 129 of file preparse-data-impl.h.
                          {
      DCHECK(has_data_);
      if (stored_quarters_ == 0) {
        DCHECK(HasRemainingBytes(kUint8Size));
        // Check that there indeed are quarters following.
        DCHECK_EQ(data_->get(index_++), kQuarterMarker);
        stored_byte_ = data_->get(index_++);
        stored_quarters_ = 4;
      }
      // Read the first 2 bits from stored_byte_.
      uint8_t result = (stored_byte_ >> 6) & 3;
      DCHECK_LE(result, 3);
      --stored_quarters_;
      stored_byte_ <<= 2;
      return result;
    }
References v8::internal::BaseConsumedPreparseData< Data >::ByteData::data_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::BaseConsumedPreparseData< Data >::ByteData::HasRemainingBytes(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::index_, v8::internal::PreparseByteDataConstants::kUint8Size, v8::base::internal::result, v8::internal::BaseConsumedPreparseData< Data >::ByteData::stored_byte_, and v8::internal::BaseConsumedPreparseData< Data >::ByteData::stored_quarters_.
ReadUint32()
template<class Data >
int32_t v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadUint32 () [inline]
Definition at line 90 of file preparse-data-impl.h.
                         {
      DCHECK(has_data_);
      DCHECK(HasRemainingBytes(kUint32Size));
      // Check that there indeed is an integer following.
      DCHECK_EQ(data_->get(index_++), kUint32Size);
      int32_t result = data_->get(index_) + (data_->get(index_ + 1) << 8) +
                       (data_->get(index_ + 2) << 16) +
                       (data_->get(index_ + 3) << 24);
      index_ += 4;
      stored_quarters_ = 0;
      return result;
    }
References v8::internal::BaseConsumedPreparseData< Data >::ByteData::data_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::BaseConsumedPreparseData< Data >::ByteData::HasRemainingBytes(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::index_, v8::internal::PreparseByteDataConstants::kUint32Size, v8::base::internal::result, and v8::internal::BaseConsumedPreparseData< Data >::ByteData::stored_quarters_.
ReadUint8()
template<class Data >
uint8_t v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadUint8 () [inline]
Definition at line 120 of file preparse-data-impl.h.
                        {
      DCHECK(has_data_);
      DCHECK(HasRemainingBytes(kUint8Size));
      // Check that there indeed is a byte following.
      DCHECK_EQ(data_->get(index_++), kUint8Size);
      stored_quarters_ = 0;
      return data_->get(index_++);
    }
References v8::internal::BaseConsumedPreparseData< Data >::ByteData::data_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::BaseConsumedPreparseData< Data >::ByteData::HasRemainingBytes(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::index_, v8::internal::PreparseByteDataConstants::kUint8Size, and v8::internal::BaseConsumedPreparseData< Data >::ByteData::stored_quarters_.
ReadVarint32()
template<class Data >
int32_t v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadVarint32 () [inline]
Definition at line 103 of file preparse-data-impl.h.
                           {
      DCHECK(HasRemainingBytes(kVarint32MinSize));
      DCHECK_EQ(data_->get(index_++), kVarint32MinSize);
      int32_t value = 0;
      bool has_another_byte;
      unsigned shift = 0;
      do {
        uint8_t byte = data_->get(index_++);
        value |= static_cast<int32_t>(byte & 0x7F) << shift;
        shift += 7;
        has_another_byte = byte & 0x80;
      } while (has_another_byte);
      DCHECK_EQ(data_->get(index_++), kVarint32EndMarker);
      stored_quarters_ = 0;
      return value;
    }
References v8::internal::BaseConsumedPreparseData< Data >::ByteData::data_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::BaseConsumedPreparseData< Data >::ByteData::HasRemainingBytes(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::index_, v8::internal::PreparseByteDataConstants::kVarint32MinSize, v8::internal::BaseConsumedPreparseData< Data >::ByteData::stored_quarters_, and v8::internal::value.
RemainingBytes()
template<class Data >
size_t v8::internal::BaseConsumedPreparseData< Data >::ByteData::RemainingBytes () const [inline]
Definition at line 79 of file preparse-data-impl.h.
                                  {
      DCHECK(has_data_);
      DCHECK_LE(index_, data_->data_length());
      return data_->data_length() - index_;
    }
References v8::internal::BaseConsumedPreparseData< Data >::ByteData::data_, v8::internal::DCHECK(), DCHECK_LE, and v8::internal::BaseConsumedPreparseData< Data >::ByteData::index_.
Referenced by v8::internal::BaseConsumedPreparseData< Data >::ByteData::HasRemainingBytes().
SetPosition()
template<class Data >
void v8::internal::BaseConsumedPreparseData< Data >::ByteData::SetPosition (int position) [inline]
Definition at line 74 of file preparse-data-impl.h.
                                   {
      DCHECK_LE(position, data_->data_length());
      index_ = position;
    }
References v8::internal::BaseConsumedPreparseData< Data >::ByteData::data_, DCHECK_LE, and v8::internal::BaseConsumedPreparseData< Data >::ByteData::index_.
Member Data Documentation
data_
template<class Data >
Data v8::internal::BaseConsumedPreparseData< Data >::ByteData::data_ = {} [private]
Definition at line 147 of file preparse-data-impl.h.
Referenced by v8::internal::BaseConsumedPreparseData< Data >::ByteData::HasRemainingBytes(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadingScope::ReadingScope(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadQuarter(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadUint32(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadUint8(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadVarint32(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::RemainingBytes(), and v8::internal::BaseConsumedPreparseData< Data >::ByteData::SetPosition().
index_
template<class Data >
int v8::internal::BaseConsumedPreparseData< Data >::ByteData::index_ = 0 [private]
Definition at line 148 of file preparse-data-impl.h.
Referenced by v8::internal::BaseConsumedPreparseData< Data >::ByteData::HasRemainingBytes(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadQuarter(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadUint32(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadUint8(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadVarint32(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::RemainingBytes(), and v8::internal::BaseConsumedPreparseData< Data >::ByteData::SetPosition().
stored_byte_
template<class Data >
uint8_t v8::internal::BaseConsumedPreparseData< Data >::ByteData::stored_byte_ = 0 [private]
Definition at line 150 of file preparse-data-impl.h.
Referenced by v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadQuarter().
stored_quarters_
template<class Data >
uint8_t v8::internal::BaseConsumedPreparseData< Data >::ByteData::stored_quarters_ = 0 [private]
Definition at line 149 of file preparse-data-impl.h.
Referenced by v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadQuarter(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadUint32(), v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadUint8(), and v8::internal::BaseConsumedPreparseData< Data >::ByteData::ReadVarint32().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/preparse-data-impl.h