v8_inspector::RemoteCallFrameId Class Reference
#include <remote-object-id.h>
Public Member Functions
~RemoteCallFrameId ()=default
int frameOrdinal () const
Static Public Member Functions
static Response parse (const String16 &, std::unique_ptr< RemoteCallFrameId > *)
static String16 serialize (uint64_t isolateId, int injectedScriptId, int frameOrdinal)
Additional Inherited Members
Detailed Description
Definition at line 41 of file remote-object-id.h.
Constructor & Destructor Documentation
 RemoteCallFrameId()
v8_inspector::RemoteCallFrameId::~RemoteCallFrameId () [default]
Member Function Documentation
frameOrdinal()
int v8_inspector::RemoteCallFrameId::frameOrdinal () const [inline]
Definition at line 46 of file remote-object-id.h.
{ return m_id; }
References v8_inspector::RemoteObjectIdBase::m_id.
Referenced by serialize().
parse()
Response v8_inspector::RemoteCallFrameId::parse (const String16 & objectId, std::unique_ptr< RemoteCallFrameId > * result) [static]
Definition at line 63 of file remote-object-id.cc.
                                                                            {
  std::unique_ptr<RemoteCallFrameId> remoteCallFrameId(new RemoteCallFrameId());
  if (!remoteCallFrameId->parseId(objectId))
    return Response::ServerError("Invalid call frame id");
  *result = std::move(remoteCallFrameId);
  return Response::Success();
}
References v8::base::internal::result.
Referenced by v8_inspector::InjectedScript::CallFrameScope::findInjectedScript().
serialize()
String16 v8_inspector::RemoteCallFrameId::serialize (uint64_t isolateId, int injectedScriptId, int frameOrdinal) [static]
Definition at line 72 of file remote-object-id.cc.
                                                        {
  return serializeId(isolateId, injectedScriptId, frameOrdinal);
}
References frameOrdinal(), v8_inspector::RemoteObjectIdBase::isolateId(), and v8_inspector::anonymous_namespace{remote-object-id.cc}::serializeId().
Referenced by v8_inspector::V8DebuggerAgentImpl::currentCallFrames().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/remote-object-id.h
/mnt/V8SourceCode/src/inspector/remote-object-id.cc