v8::internal::maglev::ReduceResult Class Reference
#include <maglev-graph-builder.h>
Public Member Functions
ReduceResult (ValueNode *value)
ReduceResult (const MaybeReduceResult &other)
bool IsFail () const
ReduceResult Checked ()
Static Public Member Functions
static ReduceResult Done (ValueNode *value)
static ReduceResult Done ()
static ReduceResult DoneWithAbort ()
Protected Member Functions
ReduceResult (Kind kind)
Additional Inherited Members
Detailed Description
Definition at line 113 of file maglev-graph-builder.h.
Constructor & Destructor Documentation
ReduceResult() [1/3]
v8::internal::maglev::ReduceResult::ReduceResult (ValueNode * value) [inline]
Definition at line 116 of file maglev-graph-builder.h.
: MaybeReduceResult(value) {}
ReduceResult() [2/3]
v8::internal::maglev::ReduceResult::ReduceResult (const MaybeReduceResult & other) [inline], [explicit]
Definition at line 118 of file maglev-graph-builder.h.
      : MaybeReduceResult(other.GetPayload()) {
    CHECK(!IsFail());
  }
References CHECK.
ReduceResult() [3/3]
v8::internal::maglev::ReduceResult::ReduceResult (Kind kind) [inline], [explicit], [protected]
Definition at line 131 of file maglev-graph-builder.h.
: MaybeReduceResult(kind) {}
Member Function Documentation
Checked()
ReduceResult v8::internal::maglev::ReduceResult::Checked () [inline]
Definition at line 128 of file maglev-graph-builder.h.
{ return *this; }
Done() [1/2]
static ReduceResult v8::internal::maglev::ReduceResult::Done () [inline], [static]
Definition at line 124 of file maglev-graph-builder.h.
{ return ReduceResult(kDoneWithoutValue); }
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Branch(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckHeapObject(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckJSFunction(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckJSReceiver(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckJSReceiverOrNullOrUndefined(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumber(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckSeqOneByteString(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckString(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckStringOrOddball(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckStringOrStringWrapper(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckSymbol(), v8::internal::maglev::MaglevGraphBuilder::BuildCompareMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildFloat64BinaryOperationNodeForToNumber(), v8::internal::maglev::MaglevGraphBuilder::BuildFloat64BinarySmiOperationNodeForToNumber(), v8::internal::maglev::MaglevGraphBuilder::BuildFloat64UnaryOperationNodeForToNumber(), v8::internal::maglev::MaglevInliner::BuildInlineFunction(), v8::internal::maglev::MaglevGraphBuilder::BuildInt32BinaryOperationNode(), v8::internal::maglev::MaglevGraphBuilder::BuildInt32BinarySmiOperationNode(), v8::internal::maglev::MaglevGraphBuilder::BuildInt32UnaryOperationNode(), v8::internal::maglev::MaglevGraphBuilder::BuildStringConcat(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindAndCompareMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindOrCheckMap(), v8::internal::maglev::MaglevGraphBuilder::BuildTruncatingInt32BinaryOperationNodeForToNumber(), v8::internal::maglev::MaglevGraphBuilder::BuildTruncatingInt32BinarySmiOperationNodeForToNumber(), v8::internal::maglev::MaglevGraphBuilder::BuildTruncatingInt32BitwiseNotForToNumber(), v8::internal::maglev::MaglevGraphBuilder::StoreAndCacheContextSlot(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::TrimPredecessorsAndBind(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellStore(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertySetterCall(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeStoreContextSlot(), v8::internal::maglev::MaglevGraphBuilder::VisitBinaryOperation(), v8::internal::maglev::MaglevGraphBuilder::VisitBinarySmiOperation(), v8::internal::maglev::MaglevGraphBuilder::VisitCompareOperation(), and v8::internal::maglev::MaglevGraphBuilder::VisitUnaryOperation().
Done() [2/2]
static ReduceResult v8::internal::maglev::ReduceResult::Done (ValueNode * value) [inline], [static]
Definition at line 123 of file maglev-graph-builder.h.
{ return ReduceResult(value); }
References v8::internal::value.
DoneWithAbort()
static ReduceResult v8::internal::maglev::ReduceResult::DoneWithAbort () [inline], [static]
Definition at line 125 of file maglev-graph-builder.h.
{ return ReduceResult(kDoneWithAbort); }
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Branch(), v8::internal::maglev::MaglevGraphBuilder::BuildCompareMaps(), v8::internal::maglev::MaglevGraphBuilder::EmitUnconditionalDeopt(), v8::internal::maglev::MaglevGraphBuilder::SelectReduction(), and v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::TrimPredecessorsAndBind().
IsFail()
bool v8::internal::maglev::ReduceResult::IsFail () const [inline]
Definition at line 127 of file maglev-graph-builder.h.
{ return false; }
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-graph-builder.h