v8::internal::detail::BuiltinArgumentsTS< Assembler > Class Template Reference
#include <turboshaft-builtins-assembler-inl.h>
Classes
class Iterator
Public Member Functions
auto & Asm () const
template<typename T >
BuiltinArgumentsTS (Assembler *assembler, V< T > argc, OptionalV< WordPtr > fp={})
V< WordPtr > GetLengthWithReceiver () const
V< WordPtr > GetLengthWithoutReceiver () const
V< Object > AtIndex (ConstOrV< WordPtr > index) const
Iterator Range (ConstOrV< WordPtr > begin, ConstOrV< WordPtr > end) const
Iterator Range (ConstOrV< WordPtr > begin) const
Iterator Range () const
Private Member Functions
V< WordPtr > AtIndexPtr (ConstOrV< WordPtr > index) const
Private Attributes
Assembler * assembler_
V< WordPtr > argc_
V< WordPtr > fp_
V< WordPtr > base_
Detailed Description
template<typename Assembler>
class v8::internal::detail::BuiltinArgumentsTS< Assembler >
Definition at line 57 of file turboshaft-builtins-assembler-inl.h.
Constructor & Destructor Documentation
BuiltinArgumentsTS()
template<typename Assembler >
template<typename T >
v8::internal::detail::BuiltinArgumentsTS< Assembler >::BuiltinArgumentsTS (Assembler * assembler, V< T > argc, OptionalV< WordPtr > fp = {}) [inline]
Definition at line 65 of file turboshaft-builtins-assembler-inl.h.
                                             {})
      : assembler_(assembler) {
    if constexpr (std::is_same_v<T, WordPtr>) {
      argc_ = argc;
    } else {
      if constexpr (std::is_same_v<T, Word32>) {
        DCHECK((std::is_same_v<WordPtr, Word64>));
        argc_ = assembler_->ChangeInt32ToInt64(argc);
      } else {
        static_assert(std::is_same_v<T, Word64>);
        DCHECK((std::is_same_v<WordPtr, Word32>));
        argc_ = assembler_->TruncateWord64ToWord32(argc);
      }
    }
    if (fp.has_value()) {
      fp_ = fp.value();
    } else {
      fp_ = __ FramePointer();
    }
    const intptr_t offset =
        (StandardFrameConstants::kFixedSlotCountAboveFp + 1) *
        kSystemPointerSize;
    // base_ points to the first argument, not the receiver
    // whether present or not.
    base_ = __ WordPtrAdd(fp_, offset);
  }
Member Function Documentation
Asm()
template<typename Assembler >
auto& v8::internal::detail::BuiltinArgumentsTS< Assembler >::Asm () const [inline]
Definition at line 61 of file turboshaft-builtins-assembler-inl.h.
{ return *assembler_; }
References v8::internal::detail::BuiltinArgumentsTS< Assembler >::assembler_.
AtIndex()
template<typename Assembler >
V<Object> v8::internal::detail::BuiltinArgumentsTS< Assembler >::AtIndex (ConstOrV< WordPtr > index) const [inline]
Definition at line 99 of file turboshaft-builtins-assembler-inl.h.
                                                   {
    TSA_DCHECK(this, __ UintPtrLessThan(index, GetLengthWithoutReceiver()));
    return V<Object>::Cast(
        __ LoadOffHeap(AtIndexPtr(index), MemoryRepresentation::AnyTagged()));
  }
References __, v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::detail::BuiltinArgumentsTS< Assembler >::AtIndexPtr(), v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::detail::BuiltinArgumentsTS< Assembler >::GetLengthWithoutReceiver(), v8::internal::index, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan().
AtIndexPtr()
template<typename Assembler >
V<WordPtr> v8::internal::detail::BuiltinArgumentsTS< Assembler >::AtIndexPtr (ConstOrV< WordPtr > index) const [inline], [private]
Definition at line 161 of file turboshaft-builtins-assembler-inl.h.
                                                       {
    V<WordPtr> offset =
        assembler_->ElementOffsetFromIndex(index, SYSTEM_POINTER_ELEMENTS, 0);
    return __ WordPtrAdd(base_, offset);
  }
References __, v8::internal::detail::BuiltinArgumentsTS< Assembler >::assembler_, v8::internal::detail::BuiltinArgumentsTS< Assembler >::base_, v8::internal::index, and v8::internal::SYSTEM_POINTER_ELEMENTS.
Referenced by v8::internal::detail::BuiltinArgumentsTS< Assembler >::AtIndex(), and v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::Begin().
GetLengthWithoutReceiver()
template<typename Assembler >
V<WordPtr> v8::internal::detail::BuiltinArgumentsTS< Assembler >::GetLengthWithoutReceiver () const [inline]
Definition at line 95 of file turboshaft-builtins-assembler-inl.h.
                                              {
    return __ WordPtrSub(argc_, kJSArgcReceiverSlots);
  }
References __, v8::internal::detail::BuiltinArgumentsTS< Assembler >::argc_, and v8::internal::kJSArgcReceiverSlots.
Referenced by v8::internal::detail::BuiltinArgumentsTS< Assembler >::AtIndex(), and v8::internal::detail::BuiltinArgumentsTS< Assembler >::Range().
GetLengthWithReceiver()
template<typename Assembler >
V<WordPtr> v8::internal::detail::BuiltinArgumentsTS< Assembler >::GetLengthWithReceiver () const [inline]
Definition at line 93 of file turboshaft-builtins-assembler-inl.h.
{ return argc_; }
References v8::internal::detail::BuiltinArgumentsTS< Assembler >::argc_.
Referenced by v8::internal::BuiltinsReducer< Next >::PopAndReturn().
Range() [1/3]
template<typename Assembler >
Iterator v8::internal::detail::BuiltinArgumentsTS< Assembler >::Range () const [inline]
Definition at line 156 of file turboshaft-builtins-assembler-inl.h.
                         {
    return Iterator(this, 0, GetLengthWithoutReceiver());
  }
References v8::internal::detail::BuiltinArgumentsTS< Assembler >::GetLengthWithoutReceiver().
Range() [2/3]
template<typename Assembler >
Iterator v8::internal::detail::BuiltinArgumentsTS< Assembler >::Range (ConstOrV< WordPtr > begin) const [inline]
Definition at line 152 of file turboshaft-builtins-assembler-inl.h.
                                                {
    return Iterator(this, begin, GetLengthWithoutReceiver());
  }
References v8::internal::compiler::begin(), and v8::internal::detail::BuiltinArgumentsTS< Assembler >::GetLengthWithoutReceiver().
Range() [3/3]
template<typename Assembler >
Iterator v8::internal::detail::BuiltinArgumentsTS< Assembler >::Range (ConstOrV< WordPtr > begin, ConstOrV< WordPtr > end) const [inline]
Definition at line 148 of file turboshaft-builtins-assembler-inl.h.
                                                                       {
    return Iterator(this, begin, end);
  }
References v8::internal::compiler::begin(), and v8::internal::compiler::end().
Member Data Documentation
argc_
template<typename Assembler >
V<WordPtr> v8::internal::detail::BuiltinArgumentsTS< Assembler >::argc_ [private]
Definition at line 168 of file turboshaft-builtins-assembler-inl.h.
Referenced by v8::internal::detail::BuiltinArgumentsTS< Assembler >::GetLengthWithoutReceiver(), and v8::internal::detail::BuiltinArgumentsTS< Assembler >::GetLengthWithReceiver().
assembler_
template<typename Assembler >
Assembler* v8::internal::detail::BuiltinArgumentsTS< Assembler >::assembler_ [private]
Definition at line 167 of file turboshaft-builtins-assembler-inl.h.
Referenced by v8::internal::detail::BuiltinArgumentsTS< Assembler >::Asm(), and v8::internal::detail::BuiltinArgumentsTS< Assembler >::AtIndexPtr().
base_
template<typename Assembler >
V<WordPtr> v8::internal::detail::BuiltinArgumentsTS< Assembler >::base_ [private]
Definition at line 170 of file turboshaft-builtins-assembler-inl.h.
Referenced by v8::internal::detail::BuiltinArgumentsTS< Assembler >::AtIndexPtr().
fp_
template<typename Assembler >
V<WordPtr> v8::internal::detail::BuiltinArgumentsTS< Assembler >::fp_ [private]
Definition at line 169 of file turboshaft-builtins-assembler-inl.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/turboshaft-builtins-assembler-inl.h