v8::internal::compiler::SLVerifierHintParameters Class Reference
#include <common-operator.h>
Public Member Functions
SLVerifierHintParameters (const Operator *semantics, std::optional< Type > override_output_type)
const Operator * semantics () const
const std::optional< Type > & override_output_type () const
Private Attributes
const Operator * semantics_
std::optional< Type > override_output_type_
Detailed Description
Definition at line 484 of file common-operator.h.
Constructor & Destructor Documentation
SLVerifierHintParameters()
v8::internal::compiler::SLVerifierHintParameters::SLVerifierHintParameters (const Operator * semantics, std::optional< Type > override_output_type) [inline], [explicit]
Definition at line 486 of file common-operator.h.
      : semantics_(semantics), override_output_type_(override_output_type) {}
Member Function Documentation
override_output_type()
const std::optional<Type>& v8::internal::compiler::SLVerifierHintParameters::override_output_type () const [inline]
Definition at line 491 of file common-operator.h.
                                                        {
    return override_output_type_;
  }
References override_output_type_.
Referenced by v8::internal::compiler::hash_value(), and v8::internal::compiler::operator<<().
semantics()
const Operator* v8::internal::compiler::SLVerifierHintParameters::semantics () const [inline]
Definition at line 490 of file common-operator.h.
{ return semantics_; }
References semantics_.
Referenced by v8::internal::compiler::hash_value(), and v8::internal::compiler::operator<<().
Member Data Documentation
override_output_type_
std::optional<Type> v8::internal::compiler::SLVerifierHintParameters::override_output_type_ [private]
Definition at line 497 of file common-operator.h.
Referenced by override_output_type().
semantics_
const Operator* v8::internal::compiler::SLVerifierHintParameters::semantics_ [private]
Definition at line 496 of file common-operator.h.
Referenced by semantics().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/common-operator.h