v8::internal::ObjectMultiHashTableBase< Derived, N > Class Template Reference
#include <hash-table.h>
Public Member Functions
std::array< Tagged< Object >, N > Lookup (DirectHandle< Object > key)
std::array< Tagged< Object >, N > Lookup (PtrComprCageBase cage_base, DirectHandle< Object > key)
Static Public Member Functions
static Handle< Derived > Put (Isolate *isolate, Handle< Derived > table, DirectHandle< Object > key, const std::array< DirectHandle< Object >, N > &values)
Private Member Functions
void SetEntryValues (InternalIndex entry, const std::array< DirectHandle< Object >, N > &values)
Static Private Member Functions
static constexpr int EntryToValueIndexStart (InternalIndex entry)
Detailed Description
template<typename Derived, int N>
class v8::internal::ObjectMultiHashTableBase< Derived, N >
Definition at line 477 of file hash-table.h.
Member Function Documentation
EntryToValueIndexStart()
template<typename Derived , int N>
static constexpr int v8::internal::ObjectMultiHashTableBase< Derived, N >::EntryToValueIndexStart (InternalIndex entry) [inline], [static], [constexpr], [private]
Definition at line 497 of file hash-table.h.
                                                                          {
    return HashTable<Derived, ObjectMultiHashTableShape<N>>::EntryToIndex(
               entry) +
           ObjectMultiHashTableShape<N>::kEntryValueIndex;
  }
Lookup() [1/2]
template<typename Derived , int N>
std::array< Tagged< Object >, N > v8::internal::ObjectMultiHashTableBase< Derived, N >::Lookup (DirectHandle< Object > key)
Definition at line 6226 of file objects.cc.
                              {
  return Lookup(GetPtrComprCageBase(this), key);
}
References v8::internal::GetPtrComprCageBase(), and v8::internal::key.
Lookup() [2/2]
template<typename Derived , int N>
std::array< Tagged< Object >, N > v8::internal::ObjectMultiHashTableBase< Derived, N >::Lookup (PtrComprCageBase cage_base, DirectHandle< Object > key)
Definition at line 6232 of file objects.cc.
                                                          {
  DisallowGarbageCollection no_gc;
  ReadOnlyRoots roots = GetReadOnlyRoots();
  DCHECK(this->IsKey(roots, *key));
  Tagged<Object> hash_obj = Object::GetHash(*key);
  if (IsUndefined(hash_obj, roots)) {
    return {roots.the_hole_value(), roots.the_hole_value()};
  }
  int32_t hash = Smi::ToInt(hash_obj);
  InternalIndex entry = this->FindEntry(cage_base, roots, key, hash);
  if (entry.is_not_found()) {
    return {roots.the_hole_value(), roots.the_hole_value()};
  }
  int start_index = this->EntryToIndex(entry) +
                    ObjectMultiHashTableShape<N>::kEntryValueIndex;
  std::array<Tagged<Object>, N> values;
  for (int i = 0; i < N; i++) {
    values[i] = this->get(start_index + i);
    DCHECK(!IsTheHole(values[i]));
  }
  return values;
}
References v8::internal::DCHECK(), v8::internal::Object::GetHash(), v8::internal::GetReadOnlyRoots(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::InternalIndex::is_not_found(), v8::internal::key, v8::internal::N, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Smi::ToInt().
Put()
template<typename Derived , int N>
Handle< Derived > v8::internal::ObjectMultiHashTableBase< Derived, N >::Put (Isolate * isolate, Handle< Derived > table, DirectHandle< Object > key, const std::array< DirectHandle< Object >, N > & values) [static]
Definition at line 6262 of file objects.cc.
                                                     {
  ReadOnlyRoots roots(isolate);
  DCHECK(table->IsKey(roots, *key));
  int32_t hash = Object::GetOrCreateHash(*key, isolate).value();
  InternalIndex entry = table->FindEntry(isolate, roots, key, hash);
  // Overwrite values if entry is found.
  if (entry.is_found()) {
    table->SetEntryValues(entry, values);
    return table;
  }
  RehashObjectHashTableAndGCIfNeeded(isolate, table);
  // Check whether the hash table should be extended.
  table = Derived::EnsureCapacity(isolate, table);
  entry = table->FindInsertionEntry(isolate, hash);
  table->set(Derived::EntryToIndex(entry), *key);
  table->SetEntryValues(entry, values);
  return table;
}
References v8::internal::DCHECK(), v8::internal::Object::GetOrCreateHash(), v8::internal::InternalIndex::is_found(), v8::internal::key, v8::internal::anonymous_namespace{objects.cc}::RehashObjectHashTableAndGCIfNeeded(), and v8::internal::Tagged< Smi >::value().
SetEntryValues()
template<typename Derived , int N>
void v8::internal::ObjectMultiHashTableBase< Derived, N >::SetEntryValues (InternalIndex entry, const std::array< DirectHandle< Object >, N > & values) [private]
Definition at line 6288 of file objects.cc.
                                                                          {
  int start_index = EntryToValueIndexStart(entry);
  for (int i = 0; i < N; i++) {
    this->set(start_index + i, *values[i]);
  }
}
References v8::internal::N.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/hash-table.h
/mnt/V8SourceCode/src/objects/objects.cc