v8::internal::maglev::HoleyFloat64ToTagged Class Reference
#include <maglev-ir.h>
Public Types
enum class ConversionMode { kCanonicalizeSmi
, kForceHeapNumber
 }
Public Member Functions
HoleyFloat64ToTagged (uint64_t bitfield, ConversionMode mode)
Input & input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
void SetMode (ConversionMode mode)
auto options () const
ConversionMode conversion_mode () const
Static Public Attributes
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kHoleyFloat64}
static constexpr OpProperties kProperties
Private Types
using Base = FixedInputValueNodeT< 1, HoleyFloat64ToTagged >
using ConversionModeBitField = NextBitField< ConversionMode, 1 >
Private Member Functions
bool canonicalize_smi ()
Additional Inherited Members
Detailed Description
Definition at line 4176 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::HoleyFloat64ToTagged::Base = FixedInputValueNodeT<1, HoleyFloat64ToTagged> [private]
Definition at line 4178 of file maglev-ir.h.
ConversionModeBitField
using v8::internal::maglev::HoleyFloat64ToTagged::ConversionModeBitField = NextBitField<ConversionMode, 1> [private]
Definition at line 4213 of file maglev-ir.h.
Member Enumeration Documentation
ConversionMode
enum v8::internal::maglev::HoleyFloat64ToTagged::ConversionMode [strong]
Enumerator
kCanonicalizeSmi
kForceHeapNumber
Definition at line 4181 of file maglev-ir.h.
{ kCanonicalizeSmi, kForceHeapNumber };
Constructor & Destructor Documentation
HoleyFloat64ToTagged()
v8::internal::maglev::HoleyFloat64ToTagged::HoleyFloat64ToTagged (uint64_t bitfield, ConversionMode mode) [inline], [explicit]
Definition at line 4182 of file maglev-ir.h.
      : Base(ConversionModeBitField::update(bitfield, mode)) {}
Member Function Documentation
canonicalize_smi()
bool v8::internal::maglev::HoleyFloat64ToTagged::canonicalize_smi () [inline], [private]
Definition at line 4209 of file maglev-ir.h.
                          {
    return ConversionModeBitField::decode(bitfield()) ==
           ConversionMode::kCanonicalizeSmi;
  }
References kCanonicalizeSmi.
conversion_mode()
ConversionMode v8::internal::maglev::HoleyFloat64ToTagged::conversion_mode () const [inline]
Definition at line 4204 of file maglev-ir.h.
                                         {
    return ConversionModeBitField::decode(bitfield());
  }
Referenced by options().
GenerateCode()
void v8::internal::maglev::HoleyFloat64ToTagged::GenerateCode (MaglevAssembler * , const ProcessingState &)
input()
Input& v8::internal::maglev::HoleyFloat64ToTagged::input () [inline]
Definition at line 4191 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
MaxCallStackArgs()
int v8::internal::maglev::HoleyFloat64ToTagged::MaxCallStackArgs () const [inline]
Definition at line 4193 of file maglev-ir.h.
{ return 0; }
options()
auto v8::internal::maglev::HoleyFloat64ToTagged::options () const [inline]
Definition at line 4202 of file maglev-ir.h.
{ return std::tuple{conversion_mode()}; }
References conversion_mode().
PrintParams()
void v8::internal::maglev::HoleyFloat64ToTagged::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 4196 of file maglev-ir.h.
{}
SetMode()
void v8::internal::maglev::HoleyFloat64ToTagged::SetMode (ConversionMode mode) [inline]
Definition at line 4198 of file maglev-ir.h.
                                    {
    set_bitfield(ConversionModeBitField::update(bitfield(), mode));
  }
References mode().
SetValueLocationConstraints()
void v8::internal::maglev::HoleyFloat64ToTagged::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::HoleyFloat64ToTagged::kInputTypes {ValueRepresentation::kHoleyFloat64} [static], [constexpr]
Definition at line 4185 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::HoleyFloat64ToTagged::kProperties [static], [constexpr]
Initial value:
= OpProperties::CanAllocate() |
                                              OpProperties::DeferredCall() |
                                              OpProperties::ConversionNode()
Definition at line 4187 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h