v8::internal::interpreter::BytecodeArrayWriter Class Reference
#include <bytecode-array-writer.h>
Public Member Functions
BytecodeArrayWriter (Zone *zone, ConstantArrayBuilder *constant_array_builder, SourcePositionTableBuilder::RecordingMode source_position_mode)
BytecodeArrayWriter (const BytecodeArrayWriter &)=delete
BytecodeArrayWriter & operator= (const BytecodeArrayWriter &)=delete
void Write (BytecodeNode *node)
void WriteJump (BytecodeNode *node, BytecodeLabel *label)
void WriteJumpLoop (BytecodeNode *node, BytecodeLoopHeader *loop_header)
void WriteSwitch (BytecodeNode *node, BytecodeJumpTable *jump_table)
void BindLabel (BytecodeLabel *label)
void BindLoopHeader (BytecodeLoopHeader *loop_header)
void BindJumpTableEntry (BytecodeJumpTable *jump_table, int case_value)
void BindHandlerTarget (HandlerTableBuilder *handler_table_builder, int handler_id)
void BindTryRegionStart (HandlerTableBuilder *handler_table_builder, int handler_id)
void BindTryRegionEnd (HandlerTableBuilder *handler_table_builder, int handler_id)
void SetFunctionEntrySourcePosition (int position)
template<typename IsolateT >
Handle< BytecodeArray > ToBytecodeArray (IsolateT *isolate, int register_count, uint16_t parameter_count, uint16_t max_arguments, DirectHandle< TrustedByteArray > handler_table)
template<typename IsolateT >
DirectHandle< TrustedByteArray > ToSourcePositionTable (IsolateT *isolate)
bool RemainderOfBlockIsDead () const
Private Member Functions
void PatchJump (size_t jump_target, size_t jump_location)
void PatchJumpWith8BitOperand (size_t jump_location, int delta)
void PatchJumpWith16BitOperand (size_t jump_location, int delta)
void PatchJumpWith32BitOperand (size_t jump_location, int delta)
void EmitBytecode (const BytecodeNode *const node)
void EmitJump (BytecodeNode *node, BytecodeLabel *label)
void EmitJumpLoop (BytecodeNode *node, BytecodeLoopHeader *loop_header)
void EmitSwitch (BytecodeNode *node, BytecodeJumpTable *jump_table)
void UpdateSourcePositionTable (const BytecodeNode *const node)
void UpdateExitSeenInBlock (Bytecode bytecode)
void MaybeElideLastBytecode (Bytecode next_bytecode, bool has_source_info)
void InvalidateLastBytecode ()
void StartBasicBlock ()
ZoneVector< uint8_t > * bytecodes ()
SourcePositionTableBuilder * source_position_table_builder ()
ConstantArrayBuilder * constant_array_builder ()
Private Attributes
const uint32_t k8BitJumpPlaceholder = 0x7f
const uint32_t k16BitJumpPlaceholder
const uint32_t k32BitJumpPlaceholder
ZoneVector< uint8_t > bytecodes_
int unbound_jumps_
SourcePositionTableBuilder source_position_table_builder_
ConstantArrayBuilder * constant_array_builder_
Bytecode last_bytecode_
size_t last_bytecode_offset_
bool last_bytecode_had_source_info_
bool elide_noneffectful_bytecodes_
bool exit_seen_in_block_
Static Private Attributes
static const size_t kMaxSizeOfPackedBytecode
Friends
class bytecode_array_writer_unittest::BytecodeArrayWriterUnittest
Detailed Description
Definition at line 34 of file bytecode-array-writer.h.
Constructor & Destructor Documentation
BytecodeArrayWriter() [1/2]
v8::internal::interpreter::BytecodeArrayWriter::BytecodeArrayWriter (Zone * zone, ConstantArrayBuilder * constant_array_builder, SourcePositionTableBuilder::RecordingMode source_position_mode)
Definition at line 24 of file bytecode-array-writer.cc.
    : bytecodes_(zone),
      unbound_jumps_(0),
      source_position_table_builder_(zone, source_position_mode),
      constant_array_builder_(constant_array_builder),
      last_bytecode_(Bytecode::kIllegal),
      last_bytecode_offset_(0),
      last_bytecode_had_source_info_(false),
      elide_noneffectful_bytecodes_(
          v8_flags.ignition_elide_noneffectful_bytecodes),
      exit_seen_in_block_(false) {
  bytecodes_.reserve(512); // Derived via experimentation.
}
References bytecodes_, and v8::internal::ZoneVector< T >::reserve().
BytecodeArrayWriter() [2/2]
v8::internal::interpreter::BytecodeArrayWriter::BytecodeArrayWriter (const BytecodeArrayWriter &) [delete]
Member Function Documentation
BindHandlerTarget()
void v8::internal::interpreter::BytecodeArrayWriter::BindHandlerTarget (HandlerTableBuilder * handler_table_builder, int handler_id)
Definition at line 186 of file bytecode-array-writer.cc.
                                                                {
  size_t current_offset = bytecodes()->size();
  StartBasicBlock();
  handler_table_builder->SetHandlerTarget(handler_id, current_offset);
}
References bytecodes(), v8::internal::interpreter::HandlerTableBuilder::SetHandlerTarget(), v8::internal::ZoneVector< T >::size(), and StartBasicBlock().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::MarkHandler().
BindJumpTableEntry()
void v8::internal::interpreter::BytecodeArrayWriter::BindJumpTableEntry (BytecodeJumpTable * jump_table, int case_value)
Definition at line 171 of file bytecode-array-writer.cc.
                                                             {
  DCHECK(!jump_table->is_bound(case_value));
  size_t current_offset = bytecodes()->size();
  size_t relative_jump = current_offset - jump_table->switch_bytecode_offset();
  constant_array_builder()->SetJumpTableSmi(
      jump_table->ConstantPoolEntryFor(case_value),
      Smi::FromInt(static_cast<int>(relative_jump)));
  jump_table->mark_bound(case_value);
  StartBasicBlock();
}
References bytecodes(), constant_array_builder(), v8::internal::interpreter::BytecodeJumpTable::ConstantPoolEntryFor(), v8::internal::DCHECK(), v8::internal::Smi::FromInt(), v8::internal::interpreter::BytecodeJumpTable::mark_bound(), v8::internal::interpreter::ConstantArrayBuilder::SetJumpTableSmi(), v8::internal::ZoneVector< T >::size(), StartBasicBlock(), and v8::internal::interpreter::BytecodeJumpTable::switch_bytecode_offset().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::Bind().
BindLabel()
void v8::internal::interpreter::BytecodeArrayWriter::BindLabel (BytecodeLabel * label)
Definition at line 154 of file bytecode-array-writer.cc.
                                                        {
  DCHECK(label->has_referrer_jump());
  size_t current_offset = bytecodes()->size();
  // Update the jump instruction's location.
  PatchJump(current_offset, label->jump_offset());
  label->bind();
  StartBasicBlock();
}
References v8::internal::interpreter::BytecodeLabel::bind(), bytecodes(), v8::internal::DCHECK(), v8::internal::interpreter::BytecodeLabel::has_referrer_jump(), v8::internal::interpreter::BytecodeLabel::jump_offset(), PatchJump(), v8::internal::ZoneVector< T >::size(), and StartBasicBlock().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::Bind().
BindLoopHeader()
void v8::internal::interpreter::BytecodeArrayWriter::BindLoopHeader (BytecodeLoopHeader * loop_header)
Definition at line 163 of file bytecode-array-writer.cc.
                                                                        {
  size_t current_offset = bytecodes()->size();
  loop_header->bind_to(current_offset);
  // Don't start a basic block when the entire loop is dead.
  if (exit_seen_in_block_) return;
  StartBasicBlock();
}
References v8::internal::interpreter::BytecodeLoopHeader::bind_to(), bytecodes(), exit_seen_in_block_, v8::internal::ZoneVector< T >::size(), and StartBasicBlock().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::Bind().
BindTryRegionEnd()
void v8::internal::interpreter::BytecodeArrayWriter::BindTryRegionEnd (HandlerTableBuilder * handler_table_builder, int handler_id)
Definition at line 202 of file bytecode-array-writer.cc.
                                                                {
  // Try blocks don't have to be in a separate basic block, but we do have to
  // invalidate the bytecode to avoid eliding it and changing the offset.
  InvalidateLastBytecode();
  size_t current_offset = bytecodes()->size();
  handler_table_builder->SetTryRegionEnd(handler_id, current_offset);
}
References bytecodes(), InvalidateLastBytecode(), v8::internal::interpreter::HandlerTableBuilder::SetTryRegionEnd(), and v8::internal::ZoneVector< T >::size().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::MarkTryEnd().
BindTryRegionStart()
void v8::internal::interpreter::BytecodeArrayWriter::BindTryRegionStart (HandlerTableBuilder * handler_table_builder, int handler_id)
Definition at line 193 of file bytecode-array-writer.cc.
                                                                {
  size_t current_offset = bytecodes()->size();
  // Try blocks don't have to be in a separate basic block, but we do have to
  // invalidate the bytecode to avoid eliding it and changing the offset.
  InvalidateLastBytecode();
  handler_table_builder->SetTryRegionStart(handler_id, current_offset);
}
References bytecodes(), InvalidateLastBytecode(), v8::internal::interpreter::HandlerTableBuilder::SetTryRegionStart(), and v8::internal::ZoneVector< T >::size().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::MarkTryBegin().
bytecodes()
ZoneVector<uint8_t>* v8::internal::interpreter::BytecodeArrayWriter::bytecodes () [inline], [private]
Definition at line 110 of file bytecode-array-writer.h.
{ return &bytecodes_; }
Referenced by BindHandlerTarget(), BindJumpTableEntry(), BindLabel(), BindLoopHeader(), BindTryRegionEnd(), BindTryRegionStart(), EmitBytecode(), EmitJump(), EmitJumpLoop(), EmitSwitch(), MaybeElideLastBytecode(), PatchJump(), PatchJumpWith16BitOperand(), PatchJumpWith32BitOperand(), PatchJumpWith8BitOperand(), ToBytecodeArray(), and UpdateSourcePositionTable().
constant_array_builder()
ConstantArrayBuilder* v8::internal::interpreter::BytecodeArrayWriter::constant_array_builder () [inline], [private]
Definition at line 114 of file bytecode-array-writer.h.
                                                 {
    return constant_array_builder_;
  }
Referenced by BindJumpTableEntry(), EmitJump(), PatchJumpWith16BitOperand(), PatchJumpWith32BitOperand(), PatchJumpWith8BitOperand(), and ToBytecodeArray().
EmitBytecode()
void v8::internal::interpreter::BytecodeArrayWriter::EmitBytecode (const BytecodeNode *const node) [private]
Definition at line 276 of file bytecode-array-writer.cc.
                                                                     {
  DCHECK_NE(node->bytecode(), Bytecode::kIllegal);
  Bytecode bytecode = node->bytecode();
  OperandScale operand_scale = node->operand_scale();
  if (operand_scale != OperandScale::kSingle) {
    Bytecode prefix = Bytecodes::OperandScaleToPrefixBytecode(operand_scale);
    bytecodes()->push_back(Bytecodes::ToByte(prefix));
  }
  bytecodes()->push_back(Bytecodes::ToByte(bytecode));
  const uint32_t* const operands = node->operands();
  const int operand_count = node->operand_count();
  const OperandSize* operand_sizes =
      Bytecodes::GetOperandSizes(bytecode, operand_scale);
  for (int i = 0; i < operand_count; ++i) {
    switch (operand_sizes[i]) {
      case OperandSize::kNone:
        UNREACHABLE();
      case OperandSize::kByte:
        bytecodes()->push_back(static_cast<uint8_t>(operands[i]));
        break;
      case OperandSize::kShort: {
        uint16_t operand = static_cast<uint16_t>(operands[i]);
        const uint8_t* raw_operand = reinterpret_cast<const uint8_t*>(&operand);
        bytecodes()->push_back(raw_operand[0]);
        bytecodes()->push_back(raw_operand[1]);
        break;
      }
      case OperandSize::kQuad: {
        const uint8_t* raw_operand =
            reinterpret_cast<const uint8_t*>(&operands[i]);
        bytecodes()->push_back(raw_operand[0]);
        bytecodes()->push_back(raw_operand[1]);
        bytecodes()->push_back(raw_operand[2]);
        bytecodes()->push_back(raw_operand[3]);
        break;
      }
    }
  }
}
References v8::internal::interpreter::BytecodeNode::bytecode(), bytecodes(), DCHECK_NE, v8::internal::interpreter::Bytecodes::GetOperandSizes(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::interpreter::kByte, v8::internal::interpreter::kNone, v8::internal::interpreter::kQuad, v8::internal::interpreter::kShort, v8::internal::interpreter::BytecodeNode::operand_count(), v8::internal::interpreter::BytecodeNode::operand_scale(), v8::internal::interpreter::BytecodeNode::operands(), v8::internal::interpreter::Bytecodes::OperandScaleToPrefixBytecode(), v8::internal::ZoneVector< T >::push_back(), v8::internal::interpreter::Bytecodes::ToByte(), and v8::internal::UNREACHABLE().
Referenced by EmitJump(), EmitJumpLoop(), and EmitSwitch().
EmitJump()
void v8::internal::interpreter::BytecodeArrayWriter::EmitJump (BytecodeNode * node, BytecodeLabel * label) [private]
Definition at line 500 of file bytecode-array-writer.cc.
                                                                           {
  DCHECK(Bytecodes::IsForwardJump(node->bytecode()));
  DCHECK_EQ(0u, node->operand(0));
  size_t current_offset = bytecodes()->size();
  // The label has not yet been bound so this is a forward reference
  // that will be patched when the label is bound. We create a
  // reservation in the constant pool so the jump can be patched
  // when the label is bound. The reservation means the maximum size
  // of the operand for the constant is known and the jump can
  // be emitted into the bytecode stream with space for the operand.
  unbound_jumps_++;
  label->set_referrer(current_offset);
  OperandSize reserved_operand_size =
      constant_array_builder()->CreateReservedEntry(
          static_cast<OperandSize>(node->operand_scale()));
  DCHECK_NE(Bytecode::kJumpLoop, node->bytecode());
  switch (reserved_operand_size) {
    case OperandSize::kNone:
      UNREACHABLE();
    case OperandSize::kByte:
      node->update_operand0(k8BitJumpPlaceholder);
      break;
    case OperandSize::kShort:
      node->update_operand0(k16BitJumpPlaceholder);
      break;
    case OperandSize::kQuad:
      node->update_operand0(k32BitJumpPlaceholder);
      break;
  }
  EmitBytecode(node);
}
References v8::internal::interpreter::BytecodeNode::bytecode(), bytecodes(), constant_array_builder(), v8::internal::interpreter::ConstantArrayBuilder::CreateReservedEntry(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, EmitBytecode(), v8::internal::interpreter::Bytecodes::IsForwardJump(), k16BitJumpPlaceholder, k32BitJumpPlaceholder, k8BitJumpPlaceholder, v8::internal::interpreter::kByte, v8::internal::interpreter::kNone, v8::internal::interpreter::kQuad, v8::internal::interpreter::kShort, v8::internal::interpreter::BytecodeNode::operand(), v8::internal::interpreter::BytecodeNode::operand_scale(), v8::internal::interpreter::BytecodeLabel::set_referrer(), v8::internal::ZoneVector< T >::size(), unbound_jumps_, v8::internal::UNREACHABLE(), and v8::internal::interpreter::BytecodeNode::update_operand0().
Referenced by WriteJump().
EmitJumpLoop()
void v8::internal::interpreter::BytecodeArrayWriter::EmitJumpLoop (BytecodeNode * node, BytecodeLoopHeader * loop_header) [private]
Definition at line 462 of file bytecode-array-writer.cc.
                                                                        {
  DCHECK_EQ(node->bytecode(), Bytecode::kJumpLoop);
  DCHECK_EQ(0u, node->operand(0));
  size_t current_offset = bytecodes()->size();
  CHECK_GE(current_offset, loop_header->offset());
  CHECK_LE(current_offset, static_cast<size_t>(kMaxUInt32));
  // Update the actual jump offset now that we know the bytecode offset of both
  // the target loop header and this JumpLoop bytecode.
  //
  // The label has been bound already so this is a backwards jump.
  uint32_t delta =
      static_cast<uint32_t>(current_offset - loop_header->offset());
  // This JumpLoop bytecode itself may have a kWide or kExtraWide prefix; if
  // so, bump the delta to account for it.
  const bool emits_prefix_bytecode =
      Bytecodes::OperandScaleRequiresPrefixBytecode(node->operand_scale()) ||
      Bytecodes::OperandScaleRequiresPrefixBytecode(
          Bytecodes::ScaleForUnsignedOperand(delta));
  if (emits_prefix_bytecode) {
    static constexpr int kPrefixBytecodeSize = 1;
    delta += kPrefixBytecodeSize;
    DCHECK_EQ(Bytecodes::Size(Bytecode::kWide, OperandScale::kSingle),
              kPrefixBytecodeSize);
    DCHECK_EQ(Bytecodes::Size(Bytecode::kExtraWide, OperandScale::kSingle),
              kPrefixBytecodeSize);
  }
  node->update_operand0(delta);
  DCHECK_EQ(
      Bytecodes::OperandScaleRequiresPrefixBytecode(node->operand_scale()),
      emits_prefix_bytecode);
  EmitBytecode(node);
}
References v8::internal::interpreter::BytecodeNode::bytecode(), bytecodes(), CHECK_GE, CHECK_LE, DCHECK_EQ, EmitBytecode(), v8::internal::kMaxUInt32, v8::internal::interpreter::BytecodeLoopHeader::offset(), v8::internal::interpreter::BytecodeNode::operand(), v8::internal::interpreter::BytecodeNode::operand_scale(), v8::internal::interpreter::Bytecodes::OperandScaleRequiresPrefixBytecode(), v8::internal::interpreter::Bytecodes::ScaleForUnsignedOperand(), v8::internal::ZoneVector< T >::size(), v8::internal::interpreter::Bytecodes::Size(), and v8::internal::interpreter::BytecodeNode::update_operand0().
Referenced by WriteJumpLoop().
EmitSwitch()
void v8::internal::interpreter::BytecodeArrayWriter::EmitSwitch (BytecodeNode * node, BytecodeJumpTable * jump_table) [private]
Definition at line 534 of file bytecode-array-writer.cc.
                                                                    {
  DCHECK(Bytecodes::IsSwitch(node->bytecode()));
  size_t current_offset = bytecodes()->size();
  if (node->operand_scale() > OperandScale::kSingle) {
    // Adjust for scaling byte prefix.
    current_offset += 1;
  }
  jump_table->set_switch_bytecode_offset(current_offset);
  EmitBytecode(node);
}
References v8::internal::interpreter::BytecodeNode::bytecode(), bytecodes(), v8::internal::DCHECK(), EmitBytecode(), v8::internal::interpreter::Bytecodes::IsSwitch(), v8::internal::interpreter::BytecodeNode::operand_scale(), v8::internal::interpreter::BytecodeJumpTable::set_switch_bytecode_offset(), and v8::internal::ZoneVector< T >::size().
Referenced by WriteSwitch().
InvalidateLastBytecode()
void v8::internal::interpreter::BytecodeArrayWriter::InvalidateLastBytecode () [private]
Definition at line 272 of file bytecode-array-writer.cc.
                                                 {
  last_bytecode_ = Bytecode::kIllegal;
}
References last_bytecode_.
Referenced by BindTryRegionEnd(), BindTryRegionStart(), and StartBasicBlock().
MaybeElideLastBytecode()
void v8::internal::interpreter::BytecodeArrayWriter::MaybeElideLastBytecode (Bytecode next_bytecode, bool has_source_info) [private]
Definition at line 250 of file bytecode-array-writer.cc.
                                                                       {
  if (!elide_noneffectful_bytecodes_) return;
  // If the last bytecode loaded the accumulator without any external effect,
  // and the next bytecode clobbers this load without reading the accumulator,
  // then the previous bytecode can be elided as it has no effect.
  if (Bytecodes::IsAccumulatorLoadWithoutEffects(last_bytecode_) &&
      Bytecodes::GetImplicitRegisterUse(next_bytecode) ==
          ImplicitRegisterUse::kWriteAccumulator &&
      (!last_bytecode_had_source_info_ || !has_source_info)) {
    DCHECK_GT(bytecodes()->size(), last_bytecode_offset_);
    bytecodes()->resize(last_bytecode_offset_);
    // If the last bytecode had source info we will transfer the source info
    // to this bytecode.
    has_source_info |= last_bytecode_had_source_info_;
  }
  last_bytecode_ = next_bytecode;
  last_bytecode_had_source_info_ = has_source_info;
  last_bytecode_offset_ = bytecodes()->size();
}
References bytecodes(), DCHECK_GT, elide_noneffectful_bytecodes_, v8::internal::interpreter::Bytecodes::GetImplicitRegisterUse(), v8::internal::interpreter::Bytecodes::IsAccumulatorLoadWithoutEffects(), v8::internal::interpreter::kWriteAccumulator, last_bytecode_, last_bytecode_had_source_info_, last_bytecode_offset_, v8::internal::ZoneVector< T >::resize(), v8::internal::ZoneVector< T >::size(), and size().
Referenced by WriteJump(), WriteJumpLoop(), and WriteSwitch().
operator=()
BytecodeArrayWriter& v8::internal::interpreter::BytecodeArrayWriter::operator= (const BytecodeArrayWriter &) [delete]
PatchJump()
void v8::internal::interpreter::BytecodeArrayWriter::PatchJump (size_t jump_target, size_t jump_location) [private]
Definition at line 430 of file bytecode-array-writer.cc.
                                                                            {
  Bytecode jump_bytecode = Bytecodes::FromByte(bytecodes()->at(jump_location));
  int delta = static_cast<int>(jump_target - jump_location);
  int prefix_offset = 0;
  OperandScale operand_scale = OperandScale::kSingle;
  if (Bytecodes::IsPrefixScalingBytecode(jump_bytecode)) {
    // If a prefix scaling bytecode is emitted the target offset is one
    // less than the case of no prefix scaling bytecode.
    delta -= 1;
    prefix_offset = 1;
    operand_scale = Bytecodes::PrefixBytecodeToOperandScale(jump_bytecode);
    jump_bytecode =
        Bytecodes::FromByte(bytecodes()->at(jump_location + prefix_offset));
  }
  DCHECK(Bytecodes::IsJump(jump_bytecode));
  switch (operand_scale) {
    case OperandScale::kSingle:
      PatchJumpWith8BitOperand(jump_location, delta);
      break;
    case OperandScale::kDouble:
      PatchJumpWith16BitOperand(jump_location + prefix_offset, delta);
      break;
    case OperandScale::kQuadruple:
      PatchJumpWith32BitOperand(jump_location + prefix_offset, delta);
      break;
    default:
      UNREACHABLE();
  }
  unbound_jumps_--;
}
References bytecodes(), v8::internal::DCHECK(), v8::internal::interpreter::Bytecodes::FromByte(), v8::internal::interpreter::Bytecodes::IsJump(), v8::internal::interpreter::Bytecodes::IsPrefixScalingBytecode(), PatchJumpWith16BitOperand(), PatchJumpWith32BitOperand(), PatchJumpWith8BitOperand(), v8::internal::interpreter::Bytecodes::PrefixBytecodeToOperandScale(), unbound_jumps_, and v8::internal::UNREACHABLE().
Referenced by BindLabel().
PatchJumpWith16BitOperand()
void v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith16BitOperand (size_t jump_location, int delta) [private]
Definition at line 379 of file bytecode-array-writer.cc.
                                                               {
  Bytecode jump_bytecode = Bytecodes::FromByte(bytecodes()->at(jump_location));
  DCHECK(Bytecodes::IsForwardJump(jump_bytecode));
  DCHECK(Bytecodes::IsJumpImmediate(jump_bytecode));
  DCHECK_EQ(Bytecodes::GetOperandType(jump_bytecode, 0), OperandType::kUImm);
  DCHECK_GT(delta, 0);
  size_t operand_location = jump_location + 1;
  uint8_t operand_bytes[2];
  if (Bytecodes::ScaleForUnsignedOperand(delta) <= OperandScale::kDouble) {
    // The jump fits within the range of an Imm16 operand, so cancel
    // the reservation and jump directly.
    constant_array_builder()->DiscardReservedEntry(OperandSize::kShort);
    base::WriteUnalignedValue<uint16_t>(
        reinterpret_cast<Address>(operand_bytes), static_cast<uint16_t>(delta));
  } else {
    // The jump does not fit within the range of an Imm16 operand, so
    // commit reservation putting the offset into the constant pool,
    // and update the jump instruction and operand.
    size_t entry = constant_array_builder()->CommitReservedEntry(
        OperandSize::kShort, Smi::FromInt(delta));
    jump_bytecode = GetJumpWithConstantOperand(jump_bytecode);
    bytecodes()->at(jump_location) = Bytecodes::ToByte(jump_bytecode);
    base::WriteUnalignedValue<uint16_t>(
        reinterpret_cast<Address>(operand_bytes), static_cast<uint16_t>(entry));
  }
  DCHECK(bytecodes()->at(operand_location) == k8BitJumpPlaceholder &&
         bytecodes()->at(operand_location + 1) == k8BitJumpPlaceholder);
  bytecodes()->at(operand_location++) = operand_bytes[0];
  bytecodes()->at(operand_location) = operand_bytes[1];
}
References v8::internal::ZoneVector< T >::at(), bytecodes(), v8::internal::interpreter::ConstantArrayBuilder::CommitReservedEntry(), constant_array_builder(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, v8::internal::interpreter::ConstantArrayBuilder::DiscardReservedEntry(), v8::internal::interpreter::Bytecodes::FromByte(), v8::internal::Smi::FromInt(), v8::internal::interpreter::GetJumpWithConstantOperand(), v8::internal::interpreter::Bytecodes::GetOperandType(), v8::internal::interpreter::Bytecodes::IsForwardJump(), v8::internal::interpreter::Bytecodes::IsJumpImmediate(), k8BitJumpPlaceholder, v8::internal::interpreter::kShort, v8::internal::interpreter::Bytecodes::ScaleForUnsignedOperand(), and v8::internal::interpreter::Bytecodes::ToByte().
Referenced by PatchJump().
PatchJumpWith32BitOperand()
void v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith32BitOperand (size_t jump_location, int delta) [private]
Definition at line 411 of file bytecode-array-writer.cc.
                                                               {
  DCHECK(Bytecodes::IsJumpImmediate(
      Bytecodes::FromByte(bytecodes()->at(jump_location))));
  constant_array_builder()->DiscardReservedEntry(OperandSize::kQuad);
  uint8_t operand_bytes[4];
  base::WriteUnalignedValue<uint32_t>(reinterpret_cast<Address>(operand_bytes),
                                      static_cast<uint32_t>(delta));
  size_t operand_location = jump_location + 1;
  DCHECK(bytecodes()->at(operand_location) == k8BitJumpPlaceholder &&
         bytecodes()->at(operand_location + 1) == k8BitJumpPlaceholder &&
         bytecodes()->at(operand_location + 2) == k8BitJumpPlaceholder &&
         bytecodes()->at(operand_location + 3) == k8BitJumpPlaceholder);
  bytecodes()->at(operand_location++) = operand_bytes[0];
  bytecodes()->at(operand_location++) = operand_bytes[1];
  bytecodes()->at(operand_location++) = operand_bytes[2];
  bytecodes()->at(operand_location) = operand_bytes[3];
}
References v8::internal::ZoneVector< T >::at(), bytecodes(), constant_array_builder(), v8::internal::DCHECK(), v8::internal::interpreter::ConstantArrayBuilder::DiscardReservedEntry(), v8::internal::interpreter::Bytecodes::FromByte(), v8::internal::interpreter::Bytecodes::IsJumpImmediate(), k8BitJumpPlaceholder, and v8::internal::interpreter::kQuad.
Referenced by PatchJump().
PatchJumpWith8BitOperand()
void v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith8BitOperand (size_t jump_location, int delta) [private]
Definition at line 351 of file bytecode-array-writer.cc.
                                                              {
  Bytecode jump_bytecode = Bytecodes::FromByte(bytecodes()->at(jump_location));
  DCHECK(Bytecodes::IsForwardJump(jump_bytecode));
  DCHECK(Bytecodes::IsJumpImmediate(jump_bytecode));
  DCHECK_EQ(Bytecodes::GetOperandType(jump_bytecode, 0), OperandType::kUImm);
  DCHECK_GT(delta, 0);
  size_t operand_location = jump_location + 1;
  DCHECK_EQ(bytecodes()->at(operand_location), k8BitJumpPlaceholder);
  if (Bytecodes::ScaleForUnsignedOperand(delta) == OperandScale::kSingle) {
    // The jump fits within the range of an UImm8 operand, so cancel
    // the reservation and jump directly.
    constant_array_builder()->DiscardReservedEntry(OperandSize::kByte);
    bytecodes()->at(operand_location) = static_cast<uint8_t>(delta);
  } else {
    // The jump does not fit within the range of an UImm8 operand, so
    // commit reservation putting the offset into the constant pool,
    // and update the jump instruction and operand.
    size_t entry = constant_array_builder()->CommitReservedEntry(
        OperandSize::kByte, Smi::FromInt(delta));
    DCHECK_EQ(Bytecodes::SizeForUnsignedOperand(static_cast<uint32_t>(entry)),
              OperandSize::kByte);
    jump_bytecode = GetJumpWithConstantOperand(jump_bytecode);
    bytecodes()->at(jump_location) = Bytecodes::ToByte(jump_bytecode);
    bytecodes()->at(operand_location) = static_cast<uint8_t>(entry);
  }
}
References v8::internal::ZoneVector< T >::at(), bytecodes(), v8::internal::interpreter::ConstantArrayBuilder::CommitReservedEntry(), constant_array_builder(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, v8::internal::interpreter::ConstantArrayBuilder::DiscardReservedEntry(), v8::internal::interpreter::Bytecodes::FromByte(), v8::internal::Smi::FromInt(), v8::internal::interpreter::GetJumpWithConstantOperand(), v8::internal::interpreter::Bytecodes::GetOperandType(), v8::internal::interpreter::Bytecodes::IsForwardJump(), v8::internal::interpreter::Bytecodes::IsJumpImmediate(), k8BitJumpPlaceholder, v8::internal::interpreter::kByte, v8::internal::interpreter::Bytecodes::ScaleForUnsignedOperand(), v8::internal::interpreter::Bytecodes::SizeForUnsignedOperand(), and v8::internal::interpreter::Bytecodes::ToByte().
Referenced by PatchJump().
RemainderOfBlockIsDead()
bool v8::internal::interpreter::BytecodeArrayWriter::RemainderOfBlockIsDead () const [inline]
Definition at line 73 of file bytecode-array-writer.h.
{ return exit_seen_in_block_; }
SetFunctionEntrySourcePosition()
void v8::internal::interpreter::BytecodeArrayWriter::SetFunctionEntrySourcePosition (int position)
Definition at line 211 of file bytecode-array-writer.cc.
                                                                     {
  bool is_statement = false;
  source_position_table_builder_.AddPosition(
      kFunctionEntryBytecodeOffset, SourcePosition(position), is_statement);
}
References v8::internal::SourcePositionTableBuilder::AddPosition(), v8::internal::kFunctionEntryBytecodeOffset, and source_position_table_builder_.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::EmitFunctionStartSourcePosition().
source_position_table_builder()
SourcePositionTableBuilder* v8::internal::interpreter::BytecodeArrayWriter::source_position_table_builder () [inline], [private]
Definition at line 111 of file bytecode-array-writer.h.
                                                              {
    return &source_position_table_builder_;
  }
Referenced by UpdateSourcePositionTable().
StartBasicBlock()
void v8::internal::interpreter::BytecodeArrayWriter::StartBasicBlock () [private]
Definition at line 217 of file bytecode-array-writer.cc.
                                          {
  InvalidateLastBytecode();
  exit_seen_in_block_ = false;
}
References exit_seen_in_block_, and InvalidateLastBytecode().
Referenced by BindHandlerTarget(), BindJumpTableEntry(), BindLabel(), and BindLoopHeader().
ToBytecodeArray()
template<typename IsolateT >
Handle< BytecodeArray > v8::internal::interpreter::BytecodeArrayWriter::ToBytecodeArray (IsolateT * isolate, int register_count, uint16_t parameter_count, uint16_t max_arguments, DirectHandle< TrustedByteArray > handler_table)
Definition at line 41 of file bytecode-array-writer.cc.
                                                                          {
  DCHECK_EQ(0, unbound_jumps_);
  int bytecode_size = static_cast<int>(bytecodes()->size());
  int frame_size = register_count * kSystemPointerSize;
  DirectHandle<TrustedFixedArray> constant_pool =
      constant_array_builder()->ToFixedArray(isolate);
  Handle<BytecodeArray> bytecode_array = isolate->factory()->NewBytecodeArray(
      bytecode_size, &bytecodes()->front(), frame_size, parameter_count,
      max_arguments, constant_pool, handler_table);
  return bytecode_array;
}
References bytecodes(), constant_array_builder(), v8::internal::constant_pool, DCHECK_EQ, v8::internal::kSystemPointerSize, v8::internal::ZoneVector< T >::size(), v8::internal::interpreter::ConstantArrayBuilder::ToFixedArray(), and unbound_jumps_.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::ToBytecodeArray().
ToSourcePositionTable()
template<typename IsolateT >
DirectHandle<TrustedByteArray> v8::internal::interpreter::BytecodeArrayWriter::ToSourcePositionTable (IsolateT * isolate)
UpdateExitSeenInBlock()
void v8::internal::interpreter::BytecodeArrayWriter::UpdateExitSeenInBlock (Bytecode bytecode) [private]
Definition at line 233 of file bytecode-array-writer.cc.
                                                                 {
  switch (bytecode) {
    case Bytecode::kReturn:
    case Bytecode::kThrow:
    case Bytecode::kReThrow:
    case Bytecode::kAbort:
    case Bytecode::kJump:
    case Bytecode::kJumpLoop:
    case Bytecode::kJumpConstant:
    case Bytecode::kSuspendGenerator:
      exit_seen_in_block_ = true;
      break;
    default:
      break;
  }
}
References exit_seen_in_block_.
Referenced by WriteJump(), WriteJumpLoop(), and WriteSwitch().
UpdateSourcePositionTable()
void v8::internal::interpreter::BytecodeArrayWriter::UpdateSourcePositionTable (const BytecodeNode *const node) [private]
Definition at line 222 of file bytecode-array-writer.cc.
                                    {
  int bytecode_offset = static_cast<int>(bytecodes()->size());
  const BytecodeSourceInfo& source_info = node->source_info();
  if (source_info.is_valid()) {
    source_position_table_builder()->AddPosition(
        bytecode_offset, SourcePosition(source_info.source_position()),
        source_info.is_statement(), source_info.is_breakable());
  }
}
References v8::internal::SourcePositionTableBuilder::AddPosition(), bytecodes(), v8::internal::interpreter::BytecodeSourceInfo::is_breakable(), v8::internal::interpreter::BytecodeSourceInfo::is_statement(), v8::internal::interpreter::BytecodeSourceInfo::is_valid(), v8::internal::ZoneVector< T >::size(), v8::internal::interpreter::BytecodeNode::source_info(), v8::internal::interpreter::BytecodeSourceInfo::source_position(), and source_position_table_builder().
Referenced by WriteJump(), WriteJumpLoop(), and WriteSwitch().
Write()
void v8::internal::interpreter::BytecodeArrayWriter::Write (BytecodeNode * node)
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::Write().
WriteJump()
void v8::internal::interpreter::BytecodeArrayWriter::WriteJump (BytecodeNode * node, BytecodeLabel * label)
Definition at line 119 of file bytecode-array-writer.cc.
                                                                            {
  DCHECK(Bytecodes::IsForwardJump(node->bytecode()));
  if (exit_seen_in_block_) return; // Don't emit dead code.
  UpdateExitSeenInBlock(node->bytecode());
  MaybeElideLastBytecode(node->bytecode(), node->source_info().is_valid());
  UpdateSourcePositionTable(node);
  EmitJump(node, label);
}
References v8::internal::interpreter::BytecodeNode::bytecode(), v8::internal::DCHECK(), EmitJump(), exit_seen_in_block_, v8::internal::interpreter::BytecodeSourceInfo::is_valid(), v8::internal::interpreter::Bytecodes::IsForwardJump(), MaybeElideLastBytecode(), v8::internal::interpreter::BytecodeNode::source_info(), UpdateExitSeenInBlock(), and UpdateSourcePositionTable().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::WriteJump().
WriteJumpLoop()
void v8::internal::interpreter::BytecodeArrayWriter::WriteJumpLoop (BytecodeNode * node, BytecodeLoopHeader * loop_header)
Definition at line 130 of file bytecode-array-writer.cc.
                                                                         {
  DCHECK_EQ(node->bytecode(), Bytecode::kJumpLoop);
  if (exit_seen_in_block_) return; // Don't emit dead code.
  UpdateExitSeenInBlock(node->bytecode());
  MaybeElideLastBytecode(node->bytecode(), node->source_info().is_valid());
  UpdateSourcePositionTable(node);
  EmitJumpLoop(node, loop_header);
}
References v8::internal::interpreter::BytecodeNode::bytecode(), DCHECK_EQ, EmitJumpLoop(), exit_seen_in_block_, v8::internal::interpreter::BytecodeSourceInfo::is_valid(), MaybeElideLastBytecode(), v8::internal::interpreter::BytecodeNode::source_info(), UpdateExitSeenInBlock(), and UpdateSourcePositionTable().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::WriteJumpLoop().
WriteSwitch()
void v8::internal::interpreter::BytecodeArrayWriter::WriteSwitch (BytecodeNode * node, BytecodeJumpTable * jump_table)
Definition at line 142 of file bytecode-array-writer.cc.
                                                                     {
  DCHECK(Bytecodes::IsSwitch(node->bytecode()));
  if (exit_seen_in_block_) return; // Don't emit dead code.
  UpdateExitSeenInBlock(node->bytecode());
  MaybeElideLastBytecode(node->bytecode(), node->source_info().is_valid());
  UpdateSourcePositionTable(node);
  EmitSwitch(node, jump_table);
}
References v8::internal::interpreter::BytecodeNode::bytecode(), v8::internal::DCHECK(), EmitSwitch(), exit_seen_in_block_, v8::internal::interpreter::BytecodeSourceInfo::is_valid(), v8::internal::interpreter::Bytecodes::IsSwitch(), MaybeElideLastBytecode(), v8::internal::interpreter::BytecodeNode::source_info(), UpdateExitSeenInBlock(), and UpdateSourcePositionTable().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::WriteSwitch().
Friends And Related Function Documentation
bytecode_array_writer_unittest::BytecodeArrayWriterUnittest
friend class bytecode_array_writer_unittest::BytecodeArrayWriterUnittest [friend]
Definition at line 130 of file bytecode-array-writer.h.
Member Data Documentation
bytecodes_
ZoneVector<uint8_t> v8::internal::interpreter::BytecodeArrayWriter::bytecodes_ [private]
Definition at line 118 of file bytecode-array-writer.h.
Referenced by BytecodeArrayWriter().
constant_array_builder_
ConstantArrayBuilder* v8::internal::interpreter::BytecodeArrayWriter::constant_array_builder_ [private]
Definition at line 121 of file bytecode-array-writer.h.
elide_noneffectful_bytecodes_
bool v8::internal::interpreter::BytecodeArrayWriter::elide_noneffectful_bytecodes_ [private]
Definition at line 126 of file bytecode-array-writer.h.
Referenced by MaybeElideLastBytecode().
exit_seen_in_block_
bool v8::internal::interpreter::BytecodeArrayWriter::exit_seen_in_block_ [private]
Definition at line 128 of file bytecode-array-writer.h.
Referenced by BindLoopHeader(), StartBasicBlock(), UpdateExitSeenInBlock(), WriteJump(), WriteJumpLoop(), and WriteSwitch().
k16BitJumpPlaceholder
const uint32_t v8::internal::interpreter::BytecodeArrayWriter::k16BitJumpPlaceholder [private]
Initial value:
=
      k8BitJumpPlaceholder | (k8BitJumpPlaceholder << 8)
Definition at line 87 of file bytecode-array-writer.h.
Referenced by EmitJump().
k32BitJumpPlaceholder
const uint32_t v8::internal::interpreter::BytecodeArrayWriter::k32BitJumpPlaceholder [private]
Initial value:
=
      k16BitJumpPlaceholder | (k16BitJumpPlaceholder << 16)
Definition at line 89 of file bytecode-array-writer.h.
Referenced by EmitJump().
k8BitJumpPlaceholder
const uint32_t v8::internal::interpreter::BytecodeArrayWriter::k8BitJumpPlaceholder = 0x7f [private]
Definition at line 86 of file bytecode-array-writer.h.
Referenced by EmitJump(), PatchJumpWith16BitOperand(), PatchJumpWith32BitOperand(), and PatchJumpWith8BitOperand().
kMaxSizeOfPackedBytecode
STATIC_CONST_MEMBER_DEFINITION const size_t v8::internal::interpreter::BytecodeArrayWriter::kMaxSizeOfPackedBytecode [static], [private]
Initial value:
=
      2 * sizeof(Bytecode) +
      Bytecodes::kMaxOperands * static_cast<size_t>(OperandSize::kLast)
Definition at line 79 of file bytecode-array-writer.h.
last_bytecode_
Bytecode v8::internal::interpreter::BytecodeArrayWriter::last_bytecode_ [private]
Definition at line 123 of file bytecode-array-writer.h.
Referenced by InvalidateLastBytecode(), and MaybeElideLastBytecode().
last_bytecode_had_source_info_
bool v8::internal::interpreter::BytecodeArrayWriter::last_bytecode_had_source_info_ [private]
Definition at line 125 of file bytecode-array-writer.h.
Referenced by MaybeElideLastBytecode().
last_bytecode_offset_
size_t v8::internal::interpreter::BytecodeArrayWriter::last_bytecode_offset_ [private]
Definition at line 124 of file bytecode-array-writer.h.
Referenced by MaybeElideLastBytecode().
source_position_table_builder_
SourcePositionTableBuilder v8::internal::interpreter::BytecodeArrayWriter::source_position_table_builder_ [private]
Definition at line 120 of file bytecode-array-writer.h.
Referenced by SetFunctionEntrySourcePosition().
unbound_jumps_
int v8::internal::interpreter::BytecodeArrayWriter::unbound_jumps_ [private]
Definition at line 119 of file bytecode-array-writer.h.
Referenced by EmitJump(), PatchJump(), and ToBytecodeArray().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/bytecode-array-writer.h
/mnt/V8SourceCode/src/interpreter/bytecode-array-writer.cc