v8::internal::compiler::JSSetNamedPropertyNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSSetNamedPropertyNode (Node *node)
const NamedAccess & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1595 of file js-operator.h.
Constructor & Destructor Documentation
JSSetNamedPropertyNode()
constexpr v8::internal::compiler::JSSetNamedPropertyNode::JSSetNamedPropertyNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1597 of file js-operator.h.
      : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSSetNamedProperty, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const NamedAccess& v8::internal::compiler::JSSetNamedPropertyNode::Parameters () const [inline]
Definition at line 1602 of file js-operator.h.
{ return NamedAccessOf(node()->op()); }
References v8::internal::compiler::NamedAccessOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSSetNamedProperty().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h