v8::internal::JsonParser< Char > Class Template Reference
#include <json-parser.h>
Classes
struct JsonContinuation
class NamedPropertyIterator
Public Types
using SeqString = typename CharTraits< Char >::String
using SeqExternalString = typename CharTraits< Char >::ExternalString
Static Public Member Functions
static V8_WARN_UNUSED_RESULT bool CheckRawJson (Isolate *isolate, Handle< String > source)
static V8_WARN_UNUSED_RESULT MaybeHandle< Object > Parse (Isolate *isolate, Handle< String > source, Handle< Object > reviver)
Static Public Attributes
static constexpr base::uc32 kEndOfString = static_cast<base::uc32>(-1)
static constexpr base::uc32 kInvalidUnicodeCharacter
Private Types
template<typename T >
using SmallVector = base::SmallVector< T, 16 >
Private Member Functions
JsonParser (Isolate *isolate, Handle< String > source)
~JsonParser ()
MaybeHandle< Object > ParseJson (DirectHandle< Object > reviver)
bool ParseRawJson ()
void advance ()
base::uc32 CurrentCharacter ()
base::uc32 NextCharacter ()
void AdvanceToNonDecimal ()
JsonToken peek () const
void Consume (JsonToken token)
void Expect (JsonToken token, std::optional< MessageTemplate > errorMessage=std::nullopt)
void ExpectNext (JsonToken token, std::optional< MessageTemplate > errorMessage=std::nullopt)
bool Check (JsonToken token)
template<size_t N>
void ScanLiteral (const char(&s)[N])
void SkipWhitespace ()
JsonString ScanJsonString (bool needs_internalization)
JsonString ScanJsonPropertyKey (JsonContinuation *cont)
base::uc32 ScanUnicodeCharacter ()
base::Vector< const Char > GetKeyChars (JsonString key)
Handle< String > MakeString (const JsonString &string, Handle< String > hint=Handle< String >())
template<typename SinkChar >
void DecodeString (SinkChar *sink, uint32_t start, uint32_t length)
template<typename SinkSeqString >
Handle< String > DecodeString (const JsonString &string, Handle< SinkSeqString > intermediate, Handle< String > hint)
Handle< Object > ParseJsonNumber ()
bool ParseJsonNumberAsDoubleOrSmi (double *result_double, int *result_smi)
template<bool should_track_json_source>
MaybeHandle< Object > ParseJsonValue ()
MaybeHandle< Object > ParseJsonValueRecursive (Handle< Map > feedback={})
MaybeHandle< Object > ParseJsonArray ()
MaybeHandle< Object > ParseJsonObject (Handle< Map > feedback)
template<DescriptorArray::FastIterableState fast_iterable_state>
bool ParseJsonObjectProperties (JsonContinuation *cont, MessageTemplate first_token_msg, Handle< DescriptorArray > descriptors)
bool ParseJsonPropertyValue (const JsonString &key)
bool FastKeyMatch (const uint8_t *key_chars, uint32_t key_length)
template<bool should_track_json_source>
Handle< JSObject > BuildJsonObject (const JsonContinuation &cont, DirectHandle< Map > feedback)
Handle< Object > BuildJsonArray (size_t start)
void ReportUnexpectedCharacter (base::uc32 c)
bool IsSpecialString ()
MessageTemplate GetErrorMessageWithEllipses (DirectHandle< Object > &arg, DirectHandle< Object > &arg2, int pos)
MessageTemplate LookUpErrorMessageForJsonToken (JsonToken token, DirectHandle< Object > &arg, DirectHandle< Object > &arg2, int pos)
void CalculateFileLocation (DirectHandle< Object > &line, DirectHandle< Object > &column)
void ReportUnexpectedToken (JsonToken token, std::optional< MessageTemplate > errorMessage=std::nullopt)
Isolate * isolate ()
Factory * factory ()
ReadOnlyRoots roots ()
DirectHandle< JSFunction > object_constructor ()
void UpdatePointers ()
bool is_at_end () const
size_t remaining_chars () const
uint32_t position () const
Static Private Member Functions
static void UpdatePointersCallback (void *parser)
Private Attributes
Isolate * isolate_
const uint64_t hash_seed_
JsonToken next_
bool chars_may_relocate_
Handle< JSFunction > object_constructor_
const Handle< String > original_source_
Handle< String > source_
MaybeHandle< Object > parsed_val_node_
SmallVector< Handle< Object > > element_stack_
SmallVector< JsonProperty > property_stack_
SmallVector< double > double_elements_
SmallVector< int > smi_elements_
const Char * cursor_
const Char * end_
const Char * chars_
Static Private Attributes
static const int kMaxContextCharacters = 10
static const int kMinOriginalSourceLengthForContext
static const int kInitialSpecialStringLength = 32
static const bool kIsOneByte = sizeof(Char) == 1
Detailed Description
template<typename Char>
class v8::internal::JsonParser< Char >
Definition at line 156 of file json-parser.h.
Member Typedef Documentation
SeqExternalString
template<typename Char >
using v8::internal::JsonParser< Char >::SeqExternalString = typename CharTraits<Char>::ExternalString
Definition at line 159 of file json-parser.h.
SeqString
template<typename Char >
using v8::internal::JsonParser< Char >::SeqString = typename CharTraits<Char>::String
Definition at line 158 of file json-parser.h.
SmallVector
template<typename Char >
template<typename T >
using v8::internal::JsonParser< Char >::SmallVector = base::SmallVector<T, 16> [private]
Definition at line 192 of file json-parser.h.
Constructor & Destructor Documentation
JsonParser()
template<typename Char >
v8::internal::JsonParser< Char >::JsonParser (Isolate * isolate, Handle< String > source) [private]
Definition at line 303 of file json-parser.cc.
    : isolate_(isolate),
      hash_seed_(HashSeed(isolate)),
      object_constructor_(isolate_->object_function()),
      original_source_(source) {
  size_t start = 0;
  size_t length = source->length();
  PtrComprCageBase cage_base(isolate);
  if (IsSlicedString(*source, cage_base)) {
    Tagged<SlicedString> string = Cast<SlicedString>(*source);
    start = string->offset();
    Tagged<String> parent = string->parent();
    if (IsThinString(parent, cage_base))
      parent = Cast<ThinString>(parent)->actual();
    source_ = handle(parent, isolate);
  } else {
    source_ = String::Flatten(isolate, source);
  }
  if (StringShape(*source_).IsExternal()) {
    chars_ =
        static_cast<const Char*>(Cast<SeqExternalString>(*source_)->GetChars());
    chars_may_relocate_ = false;
  } else {
    DisallowGarbageCollection no_gc;
    isolate->main_thread_local_heap()->AddGCEpilogueCallback(
        UpdatePointersCallback, this);
    chars_ = Cast<SeqString>(*source_)->GetChars(no_gc);
    chars_may_relocate_ = true;
  }
  cursor_ = chars_ + start;
  end_ = cursor_ + length;
}
References v8::internal::LocalHeap::AddGCEpilogueCallback(), v8::internal::JsonParser< Char >::chars_, v8::internal::JsonParser< Char >::chars_may_relocate_, v8::internal::JsonParser< Char >::cursor_, v8::internal::JsonParser< Char >::end_, v8::internal::handle(), v8::internal::StringShape::IsExternal(), v8::internal::JsonParser< Char >::isolate(), v8::internal::InstanceTypeChecker::IsSlicedString(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::length, v8::internal::Isolate::main_thread_local_heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::JsonParser< Char >::source_, and v8::internal::JsonParser< Char >::UpdatePointersCallback().
Referenced by v8::internal::JsonParser< Char >::CheckRawJson().
 JsonParser()
template<typename Char >
v8::internal::JsonParser< Char >::~JsonParser [private]
Definition at line 517 of file json-parser.cc.
                              {
  if (StringShape(*source_).IsExternal()) {
    // Check that the string shape hasn't changed. Otherwise our GC hooks are
    // broken.
    Cast<SeqExternalString>(*source_);
  } else {
    // Check that the string shape hasn't changed. Otherwise our GC hooks are
    // broken.
    Cast<SeqString>(*source_);
    isolate()->main_thread_local_heap()->RemoveGCEpilogueCallback(
        UpdatePointersCallback, this);
  }
}
References v8::internal::StringShape::IsExternal().
Member Function Documentation
advance()
template<typename Char >
void v8::internal::JsonParser< Char >::advance () [inline], [private]
Definition at line 221 of file json-parser.h.
{ ++cursor_; }
References v8::internal::JsonParser< Char >::cursor_.
Referenced by v8::internal::JsonParser< Char >::Check(), v8::internal::JsonParser< Char >::Consume(), v8::internal::JsonParser< Char >::Expect(), and v8::internal::JsonParser< Char >::NextCharacter().
AdvanceToNonDecimal()
template<typename Char >
void v8::internal::JsonParser< Char >::AdvanceToNonDecimal [private]
Definition at line 2163 of file json-parser.cc.
                                           {
  cursor_ =
      std::find_if(cursor_, end_, [](Char c) { return !IsDecimalDigit(c); });
}
References v8::internal::IsDecimalDigit().
BuildJsonArray()
template<typename Char >
Handle< Object > v8::internal::JsonParser< Char >::BuildJsonArray (size_t start) [private]
Definition at line 1357 of file json-parser.cc.
                                                            {
  int length = static_cast<int>(element_stack_.size() - start);
  ElementsKind kind = PACKED_SMI_ELEMENTS;
  for (size_t i = start; i < element_stack_.size(); i++) {
    Tagged<Object> value = *element_stack_[i];
    if (IsHeapObject(value)) {
      if (IsHeapNumber(Cast<HeapObject>(value))) {
        kind = PACKED_DOUBLE_ELEMENTS;
      } else {
        kind = PACKED_ELEMENTS;
        break;
      }
    }
  }
  Handle<JSArray> array = factory()->NewJSArray(kind, length, length);
  if (kind == PACKED_DOUBLE_ELEMENTS) {
    DisallowGarbageCollection no_gc;
    Tagged<FixedDoubleArray> elements =
        Cast<FixedDoubleArray>(array->elements());
    for (int i = 0; i < length; i++) {
      elements->set(i, Object::NumberValue(*element_stack_[start + i]));
    }
  } else {
    DisallowGarbageCollection no_gc;
    Tagged<FixedArray> elements = Cast<FixedArray>(array->elements());
    WriteBarrierMode mode = kind == PACKED_SMI_ELEMENTS
                                ? SKIP_WRITE_BARRIER
                                : elements->GetWriteBarrierMode(no_gc);
    for (int i = 0; i < length; i++) {
      elements->set(i, *element_stack_[start + i], mode);
    }
  }
  return array;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsHeapObject(), v8::internal::length, mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::NumberValue(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, v8::internal::SKIP_WRITE_BARRIER, and v8::internal::value.
BuildJsonObject()
template<typename Char >
template<bool should_track_json_source>
Handle< JSObject > v8::internal::JsonParser< Char >::BuildJsonObject (const JsonContinuation & cont, DirectHandle< Map > feedback) [private]
Definition at line 1289 of file json-parser.cc.
                                                                               {
  if (!feedback.is_null() && feedback->is_deprecated()) {
    feedback = Map::Update(isolate_, feedback);
  }
  size_t start = cont.index;
  DCHECK_LE(start, property_stack_.size());
  int length = static_cast<int>(property_stack_.size() - start);
  int named_length = length - cont.elements;
  DCHECK_LE(0, named_length);
  Handle<FixedArrayBase> elements;
  ElementsKind elements_kind = HOLEY_ELEMENTS;
  // First store the elements.
  if (cont.elements > 0) {
    // Store as dictionary elements if that would use less memory.
    if (ShouldConvertToSlowElements(cont.elements, cont.max_index + 1)) {
      Handle<NumberDictionary> elms =
          NumberDictionary::New(isolate_, cont.elements);
      for (int i = 0; i < length; i++) {
        const JsonProperty& property = property_stack_[start + i];
        if (!property.string.is_index()) continue;
        uint32_t index = property.string.index();
        DirectHandle<Object> value = property.value;
        NumberDictionary::UncheckedSet(isolate_, elms, index, value);
      }
      elms->SetInitialNumberOfElements(cont.elements);
      elms->UpdateMaxNumberKey(cont.max_index, Handle<JSObject>::null());
      elements_kind = DICTIONARY_ELEMENTS;
      elements = elms;
    } else {
      Handle<FixedArray> elms =
          factory()->NewFixedArrayWithHoles(cont.max_index + 1);
      DisallowGarbageCollection no_gc;
      Tagged<FixedArray> raw_elements = *elms;
      WriteBarrierMode mode = raw_elements->GetWriteBarrierMode(no_gc);
      for (int i = 0; i < length; i++) {
        const JsonProperty& property = property_stack_[start + i];
        if (!property.string.is_index()) continue;
        uint32_t index = property.string.index();
        DirectHandle<Object> value = property.value;
        raw_elements->set(static_cast<int>(index), *value, mode);
      }
      elements = elms;
    }
  } else {
    elements = factory()->empty_fixed_array();
  }
  // When tracking JSON source with a reviver, do not use mutable HeapNumbers.
  // In this mode, values are snapshotted at the beginning because the source is
  // only passed to the reviver if the reviver does not muck with the original
  // value. Mutable HeapNumbers would make the snapshot incorrect.
  JSDataObjectBuilder js_data_object_builder(
      isolate_, elements_kind, named_length, feedback,
      should_track_json_source
          ? JSDataObjectBuilder::kNormalHeapNumbers
          : JSDataObjectBuilder::kHeapNumbersGuaranteedUniquelyOwned);
  NamedPropertyIterator it(*this, property_stack_.begin() + start,
                           property_stack_.end());
  return js_data_object_builder.BuildFromIterator(it, elements);
}
References v8::internal::JSDataObjectBuilder::BuildFromIterator(), DCHECK_LE, v8::internal::DICTIONARY_ELEMENTS, v8::internal::JsonParser< Char >::JsonContinuation::elements, v8::internal::HOLEY_ELEMENTS, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::JsonParser< Char >::JsonContinuation::index, v8::internal::index, v8::internal::DirectHandle< T >::is_null(), v8::internal::JSDataObjectBuilder::kHeapNumbersGuaranteedUniquelyOwned, v8::internal::JSDataObjectBuilder::kNormalHeapNumbers, v8::internal::length, v8::internal::JsonParser< Char >::JsonContinuation::max_index, mode(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::ShouldConvertToSlowElements(), v8::internal::NumberDictionary::UncheckedSet(), v8::internal::Map::Update(), and v8::internal::value.
CalculateFileLocation()
template<typename Char >
void v8::internal::JsonParser< Char >::CalculateFileLocation (DirectHandle< Object > & line, DirectHandle< Object > & column) [private]
Definition at line 432 of file json-parser.cc.
                                                                           {
  // JSON allows only \r and \n as line terminators.
  // (See https://www.json.org/json-en.html - "whitespace")
  int line_number = 1;
  const Char* start =
      chars_ + (IsSlicedString(*original_source_)
                    ? Cast<SlicedString>(*original_source_)->offset()
                    : 0);
  const Char* last_line_break = start;
  const Char* cursor = start;
  const Char* end = cursor_; // cursor_ points to the position of the error.
  for (; cursor < end; ++cursor) {
    if (*cursor == '\r' && cursor < end - 1 && cursor[1] == '\n') {
      // \r\n counts as a single line terminator, as of
      // https://tc39.es/ecma262/#sec-line-terminators. JSON itself does not
      // have a notion of lines or line terminators.
      ++cursor;
    }
    if (*cursor == '\r' || *cursor == '\n') {
      ++line_number;
      last_line_break = cursor + 1;
    }
  }
  int column_number = 1 + static_cast<int>(cursor - last_line_break);
  line = direct_handle(Smi::FromInt(line_number), isolate());
  column = direct_handle(Smi::FromInt(column_number), isolate());
}
References v8::internal::direct_handle(), v8::internal::compiler::end(), v8::internal::Smi::FromInt(), and v8::internal::InstanceTypeChecker::IsSlicedString().
Check()
template<typename Char >
bool v8::internal::JsonParser< Char >::Check (JsonToken token) [inline], [private]
Definition at line 258 of file json-parser.h.
                              {
    SkipWhitespace();
    if (next_ != token) return false;
    advance();
    return true;
  }
References v8::internal::JsonParser< Char >::advance(), v8::internal::JsonParser< Char >::next_, and v8::internal::JsonParser< Char >::SkipWhitespace().
CheckRawJson()
template<typename Char >
static V8_WARN_UNUSED_RESULT bool v8::internal::JsonParser< Char >::CheckRawJson (Isolate * isolate, Handle< String > source) [inline], [static]
Definition at line 161 of file json-parser.h.
                                                                        {
    return JsonParser(isolate, source).ParseRawJson();
  }
References v8::internal::JsonParser< Char >::isolate(), and v8::internal::JsonParser< Char >::JsonParser().
Consume()
template<typename Char >
void v8::internal::JsonParser< Char >::Consume (JsonToken token) [inline], [private]
Definition at line 237 of file json-parser.h.
                                {
    DCHECK_EQ(peek(), token);
    advance();
  }
References v8::internal::JsonParser< Char >::advance(), DCHECK_EQ, and v8::internal::JsonParser< Char >::peek().
CurrentCharacter()
template<typename Char >
base::uc32 v8::internal::JsonParser< Char >::CurrentCharacter () [inline], [private]
Definition at line 223 of file json-parser.h.
                              {
    if (V8_UNLIKELY(is_at_end())) return kEndOfString;
    return *cursor_;
  }
References v8::internal::JsonParser< Char >::cursor_, v8::internal::JsonParser< Char >::is_at_end(), v8::internal::JsonParser< Char >::kEndOfString, and V8_UNLIKELY.
Referenced by v8::internal::JsonParser< Char >::NextCharacter().
DecodeString() [1/2]
template<typename Char >
template<typename SinkSeqString >
Handle< String > v8::internal::JsonParser< Char >::DecodeString (const JsonString & string, Handle< SinkSeqString > intermediate, Handle< String > hint) [private]
Definition at line 2293 of file json-parser.cc.
                         {
  using SinkChar = typename SinkSeqString::Char;
  {
    DisallowGarbageCollection no_gc;
    SinkChar* dest = intermediate->GetChars(no_gc);
    if (!string.has_escape()) {
      DCHECK(!string.internalize());
      CopyChars(dest, chars_ + string.start(), string.length());
      return intermediate;
    }
    DecodeString(dest, string.start(), string.length());
    if (!string.internalize()) return intermediate;
    base::Vector<const SinkChar> data(dest, string.length());
    if (!hint.is_null() && Matches(data, hint)) return hint;
  }
  DCHECK_EQ(intermediate->length(), string.length());
  return factory()->InternalizeString(intermediate);
}
References v8::internal::CopyChars(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::HandleBase::is_null(), v8::internal::length, v8::internal::anonymous_namespace{json-parser.cc}::Matches(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
DecodeString() [2/2]
template<typename Char >
template<typename SinkChar >
void v8::internal::JsonParser< Char >::DecodeString (SinkChar * sink, uint32_t start, uint32_t length) [private]
Definition at line 2359 of file json-parser.cc.
                                                     {
  const Char* cursor = chars_ + start;
  while (length > 0) {
    // Copy everything until the first escape character
    const Char* backslash_pos = std::find(cursor, cursor + length, '\\');
    size_t to_copy = backslash_pos - cursor;
    std::copy_n(cursor, to_copy, sink);
    length -= to_copy;
    cursor += to_copy;
    sink += to_copy;
    if (length == 0) return;
    cursor++;
    switch (GetEscapeKind(character_json_scan_flags[*cursor])) {
      case EscapeKind::kSelf:
        *sink++ = *cursor;
        length--;
        break;
      case EscapeKind::kBackspace:
        *sink++ = '\x08';
        length--;
        break;
      case EscapeKind::kTab:
        *sink++ = '\x09';
        length--;
        break;
      case EscapeKind::kNewLine:
        *sink++ = '\x0A';
        length--;
        break;
      case EscapeKind::kFormFeed:
        *sink++ = '\x0C';
        length--;
        break;
      case EscapeKind::kCarriageReturn:
        *sink++ = '\x0D';
        length--;
        break;
      case EscapeKind::kUnicode: {
        base::uc32 value = 0;
        for (int i = 0; i < 4; i++) {
          value = value * 16 + base::HexValue(*++cursor);
        }
        if (value <=
            static_cast<base::uc32>(unibrow::Utf16::kMaxNonSurrogateCharCode)) {
          *sink++ = value;
          length--;
        } else {
          SBXCHECK_GE(length, 2);
          *sink++ = unibrow::Utf16::LeadSurrogate(value);
          *sink++ = unibrow::Utf16::TrailSurrogate(value);
          length -= 2;
        }
        break;
      }
      case EscapeKind::kIllegal:
        UNREACHABLE();
    }
    cursor++;
  }
}
References v8::internal::anonymous_namespace{json-parser.cc}::character_json_scan_flags, v8::internal::anonymous_namespace{json-parser.cc}::GetEscapeKind(), v8::base::HexValue(), unibrow::Utf16::kMaxNonSurrogateCharCode, unibrow::Utf16::LeadSurrogate(), v8::internal::length, SBXCHECK_GE, unibrow::Utf16::TrailSurrogate(), v8::internal::UNREACHABLE(), and v8::internal::value.
Expect()
template<typename Char >
void v8::internal::JsonParser< Char >::Expect (JsonToken token, std::optional< MessageTemplate > errorMessage = std::nullopt) [inline], [private]
Definition at line 242 of file json-parser.h.
                                                                      {
    if (V8_LIKELY(peek() == token)) {
      advance();
    } else {
      errorMessage ? ReportUnexpectedToken(peek(), errorMessage.value())
                   : ReportUnexpectedToken(peek());
    }
  }
References v8::internal::JsonParser< Char >::advance(), v8::internal::JsonParser< Char >::peek(), v8::internal::JsonParser< Char >::ReportUnexpectedToken(), and V8_LIKELY.
Referenced by v8::internal::JsonParser< Char >::ExpectNext().
ExpectNext()
template<typename Char >
void v8::internal::JsonParser< Char >::ExpectNext (JsonToken token, std::optional< MessageTemplate > errorMessage = std::nullopt) [inline], [private]
Definition at line 252 of file json-parser.h.
                                                                          {
    SkipWhitespace();
    errorMessage ? Expect(token, errorMessage.value()) : Expect(token);
  }
References v8::internal::JsonParser< Char >::Expect(), and v8::internal::JsonParser< Char >::SkipWhitespace().
factory()
template<typename Char >
Factory* v8::internal::JsonParser< Char >::factory () [inline], [private]
Definition at line 377 of file json-parser.h.
{ return isolate_->factory(); }
References v8::internal::Isolate::factory(), and v8::internal::JsonParser< Char >::isolate_.
FastKeyMatch()
template<typename Char >
bool v8::internal::JsonParser< Char >::FastKeyMatch (const uint8_t * key_chars, uint32_t key_length) [inline], [private]
Definition at line 1480 of file json-parser.cc.
                                                         {
  return key_length < remaining_chars() && *(cursor_ + key_length) == '"' &&
         CompareCharsEqual(key_chars, cursor_, key_length);
}
References v8::internal::CompareCharsEqual().
GetErrorMessageWithEllipses()
template<typename Char >
MessageTemplate v8::internal::JsonParser< Char >::GetErrorMessageWithEllipses (DirectHandle< Object > & arg, DirectHandle< Object > & arg2, int pos) [private]
Definition at line 363 of file json-parser.cc.
                                                                    {
  MessageTemplate message;
  Factory* factory = this->factory();
  arg = factory->LookupSingleCharacterStringFromCode(*cursor_);
  int origin_source_length = original_source_->length();
  // Only provide context for strings with at least
  // kMinOriginalSourceLengthForContext characters in length.
  if (origin_source_length >= kMinOriginalSourceLengthForContext) {
    int substring_start = 0;
    int substring_end = origin_source_length;
    if (pos < kMaxContextCharacters) {
      message =
          MessageTemplate::kJsonParseUnexpectedTokenStartStringWithContext;
      // Output the string followed by ellipses.
      substring_end = pos + kMaxContextCharacters;
    } else if (pos >= kMaxContextCharacters &&
               pos < origin_source_length - kMaxContextCharacters) {
      message =
          MessageTemplate::kJsonParseUnexpectedTokenSurroundStringWithContext;
      // Add context before and after position of bad token surrounded by
      // ellipses.
      substring_start = pos - kMaxContextCharacters;
      substring_end = pos + kMaxContextCharacters;
    } else {
      message = MessageTemplate::kJsonParseUnexpectedTokenEndStringWithContext;
      // Add ellipses followed by some context before bad token.
      substring_start = pos - kMaxContextCharacters;
    }
    arg2 =
        factory->NewSubString(original_source_, substring_start, substring_end);
  } else {
    arg2 = original_source_;
    // Output the entire string without ellipses but provide the token which
    // was unexpected.
    message = MessageTemplate::kJsonParseUnexpectedTokenShortString;
  }
  return message;
}
References v8::internal::FactoryBase< Impl >::LookupSingleCharacterStringFromCode().
GetKeyChars()
template<typename Char >
base::Vector<const Char> v8::internal::JsonParser< Char >::GetKeyChars (JsonString key) [inline], [private]
Definition at line 304 of file json-parser.h.
                                                     {
    return base::Vector<const Char>(chars_ + key.start(), key.length());
  }
References v8::internal::JsonParser< Char >::chars_, and v8::internal::key.
is_at_end()
template<typename Char >
bool v8::internal::JsonParser< Char >::is_at_end () const [inline], [private]
Definition at line 404 of file json-parser.h.
                         {
    DCHECK_LE(cursor_, end_);
    return cursor_ == end_;
  }
References v8::internal::JsonParser< Char >::cursor_, DCHECK_LE, and v8::internal::JsonParser< Char >::end_.
Referenced by v8::internal::JsonParser< Char >::CurrentCharacter(), and v8::internal::JsonParser< Char >::ScanLiteral().
isolate()
template<typename Char >
Isolate* v8::internal::JsonParser< Char >::isolate () [inline], [private]
Definition at line 376 of file json-parser.h.
{ return isolate_; }
References v8::internal::JsonParser< Char >::isolate_.
Referenced by v8::internal::JsonParser< Char >::CheckRawJson(), v8::internal::JsonParser< Char >::JsonParser(), and v8::internal::JsonParser< Char >::Parse().
IsSpecialString()
template<typename Char >
bool v8::internal::JsonParser< Char >::IsSpecialString [private]
Definition at line 338 of file json-parser.cc.
                                       {
  // The special cases are undefined, NaN, Infinity, and {} being passed to the
  // parse method
  int offset = IsSlicedString(*original_source_)
                   ? Cast<SlicedString>(*original_source_)->offset()
                   : 0;
  size_t length = original_source_->length();
#define CASES(V) \
  V("[object Object]") \
  V("undefined") \
  V("Infinity") \
  V("NaN")
  switch (length) {
#define CASE(n) \
  case arraysize(n) - 1: \
    return CompareCharsEqual(chars_ + offset, n, arraysize(n) - 1);
    CASES(CASE)
    default:
      return false;
  }
#undef CASE
#undef CASES
}
References CASE, CASES, v8::internal::InstanceTypeChecker::IsSlicedString(), and v8::internal::length.
LookUpErrorMessageForJsonToken()
template<typename Char >
MessageTemplate v8::internal::JsonParser< Char >::LookUpErrorMessageForJsonToken (JsonToken token, DirectHandle< Object > & arg, DirectHandle< Object > & arg2, int pos) [private]
Definition at line 404 of file json-parser.cc.
             {
  MessageTemplate message;
  switch (token) {
    case JsonToken::EOS:
      message = MessageTemplate::kJsonParseUnexpectedEOS;
      break;
    case JsonToken::NUMBER:
      message = MessageTemplate::kJsonParseUnexpectedTokenNumber;
      break;
    case JsonToken::STRING:
      message = MessageTemplate::kJsonParseUnexpectedTokenString;
      break;
    default:
      // Output entire string without ellipses and don't provide the token
      // that was unexpected because it makes the error messages more confusing
      if (IsSpecialString()) {
        arg = original_source_;
        message = MessageTemplate::kJsonParseShortString;
      } else {
        message = GetErrorMessageWithEllipses(arg, arg2, pos);
      }
  }
  return message;
}
References v8::internal::EOS, v8::internal::NUMBER, and v8::internal::STRING.
MakeString()
template<typename Char >
Handle< String > v8::internal::JsonParser< Char >::MakeString (const JsonString & string, Handle< String > hint = Handle<String>()) [private]
Definition at line 2318 of file json-parser.cc.
                                                                 {
  if (string.length() == 0) return factory()->empty_string();
  if (string.length() == 1) {
    uint16_t first_char;
    if (!string.has_escape()) {
      first_char = chars_[string.start()];
    } else {
      DecodeString(&first_char, string.start(), 1);
    }
    return factory()->LookupSingleCharacterStringFromCode(first_char);
  }
  if (string.internalize() && !string.has_escape()) {
    if (!hint.is_null()) {
      base::Vector<const Char> data(chars_ + string.start(), string.length());
      if (Matches(data, hint)) return hint;
    }
    if (chars_may_relocate_) {
      return factory()->InternalizeSubString(Cast<SeqString>(source_),
                                             string.start(), string.length(),
                                             string.needs_conversion());
    }
    base::Vector<const Char> chars(chars_ + string.start(), string.length());
    return factory()->InternalizeString(chars, string.needs_conversion());
  }
  if (sizeof(Char) == 1 ? V8_LIKELY(!string.needs_conversion())
                        : string.needs_conversion()) {
    Handle<SeqOneByteString> intermediate =
        factory()->NewRawOneByteString(string.length()).ToHandleChecked();
    return DecodeString(string, intermediate, hint);
  }
  Handle<SeqTwoByteString> intermediate =
      factory()->NewRawTwoByteString(string.length()).ToHandleChecked();
  return DecodeString(string, intermediate, hint);
}
References v8::internal::HandleBase::is_null(), v8::internal::length, v8::internal::anonymous_namespace{json-parser.cc}::Matches(), and V8_LIKELY.
NextCharacter()
template<typename Char >
base::uc32 v8::internal::JsonParser< Char >::NextCharacter () [inline], [private]
Definition at line 228 of file json-parser.h.
                           {
    advance();
    return CurrentCharacter();
  }
References v8::internal::JsonParser< Char >::advance(), and v8::internal::JsonParser< Char >::CurrentCharacter().
object_constructor()
template<typename Char >
DirectHandle<JSFunction> v8::internal::JsonParser< Char >::object_constructor () [inline], [private]
Definition at line 379 of file json-parser.h.
                                                       {
    return object_constructor_;
  }
References v8::internal::JsonParser< Char >::object_constructor_.
Parse()
template<typename Char >
static V8_WARN_UNUSED_RESULT MaybeHandle<Object> v8::internal::JsonParser< Char >::Parse (Isolate * isolate, Handle< String > source, Handle< Object > reviver) [inline], [static]
Definition at line 166 of file json-parser.h.
                                                                       {
    HighAllocationThroughputScope high_throughput_scope(
        V8::GetCurrentPlatform());
    Handle<Object> result;
    MaybeHandle<Object> val_node;
    {
      JsonParser parser(isolate, source);
      ASSIGN_RETURN_ON_EXCEPTION(isolate, result, parser.ParseJson(reviver));
      val_node = parser.parsed_val_node_;
    }
    if (IsCallable(*reviver)) {
      return JsonParseInternalizer::Internalize(isolate, result, reviver,
                                                source, val_node);
    }
    return result;
  }
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::V8::GetCurrentPlatform(), v8::internal::JsonParseInternalizer::Internalize(), v8::internal::JsonParser< Char >::isolate(), v8::internal::JsonParser< Char >::parsed_val_node_, v8::internal::JsonParser< Char >::ParseJson(), and v8::base::internal::result.
Referenced by v8::JSON::Parse().
ParseJson()
template<typename Char >
MaybeHandle< Object > v8::internal::JsonParser< Char >::ParseJson (DirectHandle< Object > reviver) [private]
Definition at line 532 of file json-parser.cc.
                                                                            {
  Handle<Object> result;
  // Only record the val node when reviver is callable.
  bool reviver_is_callable = IsCallable(*reviver);
  bool should_track_json_source = reviver_is_callable;
  if (V8_UNLIKELY(should_track_json_source)) {
    ASSIGN_RETURN_ON_EXCEPTION(isolate(), result, ParseJsonValue<true>());
  } else {
    ASSIGN_RETURN_ON_EXCEPTION(isolate(), result, ParseJsonValueRecursive());
  }
  if (!Check(JsonToken::EOS)) {
    ReportUnexpectedToken(
        peek(), MessageTemplate::kJsonParseUnexpectedNonWhiteSpaceCharacter);
    return MaybeHandle<Object>();
  }
  if (isolate_->has_exception()) {
    return MaybeHandle<Object>();
  }
  return result;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::EOS, v8::base::internal::result, and V8_UNLIKELY.
Referenced by v8::internal::JsonParser< Char >::Parse().
ParseJsonArray()
template<typename Char >
MaybeHandle< Object > v8::internal::JsonParser< Char >::ParseJsonArray [private]
Definition at line 1720 of file json-parser.cc.
                                                     {
  {
    StackLimitCheck check(isolate_);
    if (V8_UNLIKELY(check.HasOverflowed())) {
      return ParseJsonValue<false>();
    }
  }
  Consume(JsonToken::LBRACK);
  if (Check(JsonToken::RBRACK)) {
    return factory()->NewJSArray(0, PACKED_SMI_ELEMENTS);
  }
  HandleScope handle_scope(isolate_);
  size_t start = element_stack_.size();
  // Avoid allocating HeapNumbers until we really need to.
  SkipWhitespace();
  bool saw_double = false;
  bool success = false;
  DCHECK_EQ(double_elements_.size(), 0);
  DCHECK_EQ(smi_elements_.size(), 0);
  while (peek() == JsonToken::NUMBER) {
    double current_double;
    int current_smi;
    if (ParseJsonNumberAsDoubleOrSmi(&current_double, &current_smi)) {
      saw_double = true;
      double_elements_.push_back(current_double);
    } else {
      if (saw_double) {
        double_elements_.push_back(current_smi);
      } else {
        smi_elements_.push_back(current_smi);
      }
    }
    if (Check(JsonToken::COMMA)) {
      SkipWhitespace();
      continue;
    } else {
      Expect(JsonToken::RBRACK,
             MessageTemplate::kJsonParseExpectedCommaOrRBrack);
      success = true;
      break;
    }
  }
  if (success) {
    // We managed to parse the whole array either as Smis or doubles. Empty
    // arrays are handled above, so here we will have some elements.
    DCHECK(smi_elements_.size() != 0 || double_elements_.size() != 0);
    int length =
        static_cast<int>(smi_elements_.size() + double_elements_.size());
    Handle<JSArray> array;
    if (!saw_double) {
      array = factory()->NewJSArray(PACKED_SMI_ELEMENTS, length, length);
      DisallowGarbageCollection no_gc;
      Tagged<FixedArray> elements = Cast<FixedArray>(array->elements());
      for (int i = 0; i < length; i++) {
        elements->set(i, Smi::FromInt(smi_elements_[i]));
      }
    } else {
      array = factory()->NewJSArray(PACKED_DOUBLE_ELEMENTS, length, length);
      DisallowGarbageCollection no_gc;
      Tagged<FixedDoubleArray> elements =
          Cast<FixedDoubleArray>(array->elements());
      int i = 0;
      for (int element : smi_elements_) {
        elements->set(i++, element);
      }
      for (double element : double_elements_) {
        elements->set(i++, element);
      }
    }
    smi_elements_.resize(0);
    double_elements_.resize(0);
    return handle_scope.CloseAndEscape(array);
  }
  // Otherwise, we fell out of the while loop above because the next element
  // is not a number. Move the smi_elements_ and double_elements_ to
  // element_stack_ and continue parsing the next element.
  for (int element : smi_elements_) {
    element_stack_.emplace_back(handle(Smi::FromInt(element), isolate_));
  }
  smi_elements_.resize(0);
  for (double element : double_elements_) {
    element_stack_.emplace_back(factory()->NewNumber(element));
  }
  double_elements_.resize(0);
  Handle<Object> value;
  if (V8_UNLIKELY(!ParseJsonValueRecursive().ToHandle(&value))) return {};
  element_stack_.emplace_back(value);
  while (Check(JsonToken::COMMA)) {
    Handle<Map> feedback;
    if (IsJSObject(*value)) {
      Tagged<Map> maybe_feedback = Cast<JSObject>(*value)->map();
      // Don't consume feedback from objects with a map that's detached
      // from the transition tree.
      if (!maybe_feedback->IsDetached(isolate_)) {
        feedback = handle(maybe_feedback, isolate_);
      }
    }
    if (V8_UNLIKELY(!ParseJsonValueRecursive(feedback).ToHandle(&value))) {
      return {};
    }
    element_stack_.emplace_back(value);
  }
  Expect(JsonToken::RBRACK, MessageTemplate::kJsonParseExpectedCommaOrRBrack);
  Handle<Object> result = BuildJsonArray(start);
  element_stack_.resize(start);
  return handle_scope.CloseAndEscape(result);
}
References v8::internal::COMMA, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Smi::FromInt(), v8::internal::handle(), v8::internal::StackLimitCheck::HasOverflowed(), v8::internal::LBRACK, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NUMBER, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, v8::internal::RBRACK, v8::base::internal::result, v8::anonymous_namespace{api.cc}::ToHandle(), V8_UNLIKELY, and v8::internal::value.
ParseJsonNumber()
template<typename Char >
Handle< Object > v8::internal::JsonParser< Char >::ParseJsonNumber [private]
Definition at line 2169 of file json-parser.cc.
                                                 {
  double double_number;
  int smi_number;
  if (ParseJsonNumberAsDoubleOrSmi(&double_number, &smi_number)) {
    return factory()->NewHeapNumber(double_number);
  }
  return handle(Smi::FromInt(smi_number), isolate_);
}
References v8::internal::Smi::FromInt(), and v8::internal::handle().
ParseJsonNumberAsDoubleOrSmi()
template<typename Char >
bool v8::internal::JsonParser< Char >::ParseJsonNumberAsDoubleOrSmi (double * result_double, int * result_smi) [private]
Definition at line 2179 of file json-parser.cc.
                                                                     {
  int sign = 1;
  {
    const Char* start = cursor_;
    DisallowGarbageCollection no_gc;
    base::uc32 c = *cursor_;
    if (c == '-') {
      sign = -1;
      c = NextCharacter();
    }
    if (c == '0') {
      // Prefix zero is only allowed if it's the only digit before
      // a decimal point or exponent.
      c = NextCharacter();
      if (base::IsInRange(c, 0,
                          static_cast<int32_t>(unibrow::Latin1::kMaxChar)) &&
          IsNumberPart(character_json_scan_flags[c])) {
        if (V8_UNLIKELY(IsDecimalDigit(c))) {
          AllowGarbageCollection allow_before_exception;
          ReportUnexpectedToken(JsonToken::NUMBER);
          *result_smi = 0;
          return false;
        }
      } else if (sign > 0) {
        *result_smi = 0;
        return false;
      }
    } else {
      const Char* smi_start = cursor_;
      static_assert(Smi::IsValid(-999999999));
      static_assert(Smi::IsValid(999999999));
      const int kMaxSmiLength = 9;
      int32_t i = 0;
      const Char* stop = cursor_ + kMaxSmiLength;
      if (stop > end_) stop = end_;
      while (cursor_ < stop && IsDecimalDigit(*cursor_)) {
        i = (i * 10) + ((*cursor_) - '0');
        cursor_++;
      }
      if (V8_UNLIKELY(smi_start == cursor_)) {
        AllowGarbageCollection allow_before_exception;
        ReportUnexpectedToken(
            JsonToken::ILLEGAL,
            MessageTemplate::kJsonParseNoNumberAfterMinusSign);
        *result_smi = 0;
        return false;
      }
      c = CurrentCharacter();
      if (!base::IsInRange(c, 0,
                           static_cast<int32_t>(unibrow::Latin1::kMaxChar)) ||
          !IsNumberPart(character_json_scan_flags[c])) {
        // Smi.
        // TODO(verwaest): Cache?
        *result_smi = i * sign;
        return false;
      }
      AdvanceToNonDecimal();
    }
    if (CurrentCharacter() == '.') {
      c = NextCharacter();
      if (!IsDecimalDigit(c)) {
        AllowGarbageCollection allow_before_exception;
        ReportUnexpectedToken(
            JsonToken::ILLEGAL,
            MessageTemplate::kJsonParseUnterminatedFractionalNumber);
        *result_smi = 0;
        return false;
      }
      AdvanceToNonDecimal();
    }
    if (AsciiAlphaToLower(CurrentCharacter()) == 'e') {
      c = NextCharacter();
      if (c == '-' || c == '+') c = NextCharacter();
      if (!IsDecimalDigit(c)) {
        AllowGarbageCollection allow_before_exception;
        ReportUnexpectedToken(
            JsonToken::ILLEGAL,
            MessageTemplate::kJsonParseExponentPartMissingNumber);
        *result_smi = 0;
        return false;
      }
      AdvanceToNonDecimal();
    }
    base::Vector<const Char> chars(start, cursor_ - start);
    *result_double =
        StringToDouble(chars,
                       NO_CONVERSION_FLAG, // Hex, octal or trailing junk.
                       std::numeric_limits<double>::quiet_NaN());
    DCHECK(!std::isnan(*result_double));
    // The result might still be a smi even if it has a decimal part.
    return !DoubleToSmiInteger(*result_double, result_smi);
  }
}
References v8::internal::AsciiAlphaToLower(), v8::internal::anonymous_namespace{json-parser.cc}::character_json_scan_flags, v8::internal::DCHECK(), v8::internal::DoubleToSmiInteger(), v8::internal::ILLEGAL, v8::internal::IsDecimalDigit(), v8::internal::anonymous_namespace{json-parser.cc}::IsNumberPart(), v8::internal::Smi::IsValid(), unibrow::Latin1::kMaxChar, v8::internal::NO_CONVERSION_FLAG, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NUMBER, v8::internal::sign, v8::internal::StringToDouble(), and V8_UNLIKELY.
ParseJsonObject()
template<typename Char >
MaybeHandle< Object > v8::internal::JsonParser< Char >::ParseJsonObject (Handle< Map > feedback) [private]
Definition at line 1664 of file json-parser.cc.
                                                                          {
  {
    StackLimitCheck check(isolate_);
    if (V8_UNLIKELY(check.HasOverflowed())) {
      return ParseJsonValue<false>();
    }
  }
  Consume(JsonToken::LBRACE);
  if (Check(JsonToken::RBRACE)) {
    return factory()->NewJSObject(object_constructor_);
  }
  JsonContinuation cont(isolate_, JsonContinuation::kObjectProperty,
                        property_stack_.size());
  bool success;
  using FastIterableState = DescriptorArray::FastIterableState;
  const MessageTemplate first_token_msg =
      MessageTemplate::kJsonParseExpectedPropNameOrRBrace;
  if (!feedback.is_null()) {
    Handle<DescriptorArray> descriptors =
        handle(feedback->instance_descriptors(), isolate_);
    if (*descriptors == ReadOnlyRoots(isolate_).empty_descriptor_array()) {
      success = ParseJsonObjectProperties<FastIterableState::kJsonSlow>(
          &cont, first_token_msg, {});
    } else {
      switch (descriptors->fast_iterable()) {
        case FastIterableState::kJsonFast:
          success = ParseJsonObjectProperties<FastIterableState::kJsonFast>(
              &cont, first_token_msg, descriptors);
          break;
        case FastIterableState::kJsonSlow:
          success = ParseJsonObjectProperties<FastIterableState::kJsonSlow>(
              &cont, first_token_msg, {});
          break;
        case FastIterableState::kUnknown:
          success = ParseJsonObjectProperties<FastIterableState::kUnknown>(
              &cont, first_token_msg, descriptors);
          break;
      }
    }
  } else {
    success = ParseJsonObjectProperties<FastIterableState::kJsonSlow>(
        &cont, first_token_msg, {});
  }
  if (V8_UNLIKELY(!success)) {
    return {};
  }
  Expect(JsonToken::RBRACE, MessageTemplate::kJsonParseExpectedCommaOrRBrace);
  Handle<Object> result = BuildJsonObject<false>(cont, feedback);
  property_stack_.resize(cont.index);
  return cont.scope.CloseAndEscape(result);
}
References v8::internal::handle(), v8::internal::StackLimitCheck::HasOverflowed(), v8::internal::JsonParser< Char >::JsonContinuation::index, v8::internal::HandleBase::is_null(), v8::internal::LBRACE, v8::internal::RBRACE, v8::base::internal::result, v8::internal::JsonParser< Char >::JsonContinuation::scope, and V8_UNLIKELY.
ParseJsonObjectProperties()
template<typename Char >
template<DescriptorArray::FastIterableState fast_iterable_state>
bool v8::internal::JsonParser< Char >::ParseJsonObjectProperties (JsonContinuation * cont, MessageTemplate first_token_msg, Handle< DescriptorArray > descriptors) [inline], [private]
Definition at line 1529 of file json-parser.cc.
                                         {
  using FastIterableState = DescriptorArray::FastIterableState;
  if constexpr (fast_iterable_state == FastIterableState::kJsonSlow) {
    do {
      ExpectNext(JsonToken::STRING, first_token_msg);
      first_token_msg =
          MessageTemplate::kJsonParseExpectedDoubleQuotedPropertyName;
      JsonString key = ScanJsonPropertyKey(cont);
      if (V8_UNLIKELY(!ParseJsonPropertyValue(key))) return false;
    } while (Check(JsonToken::COMMA));
  } else {
    DCHECK_GT(descriptors->number_of_descriptors(), 0);
    InternalIndex idx{0};
    do {
      ExpectNext(JsonToken::STRING, first_token_msg);
      first_token_msg =
          MessageTemplate::kJsonParseExpectedDoubleQuotedPropertyName;
      bool key_match;
      if constexpr (fast_iterable_state == FastIterableState::kJsonFast) {
        uint32_t key_length;
        {
          DisallowGarbageCollection no_gc;
          Tagged<String> expected_key = Cast<String>(descriptors->GetKey(idx));
          Tagged<Map> key_map = expected_key->map();
          // Fast iterable keys are guaranteed to be 1-byte.
          const uint8_t* expected_chars =
              GetFastKeyChars(isolate_, expected_key, key_map, no_gc);
          key_length = expected_key->length();
          key_match = FastKeyMatch(expected_chars, key_length);
        }
        if (V8_LIKELY(key_match)) {
          JsonString key =
              JsonString(position(), key_length, false, true, false);
          ++idx;
          cursor_ += key_length + 1 /* double quote */;
          if (V8_UNLIKELY(!ParseJsonPropertyValue(key))) return false;
        } else {
          JsonString key = ScanJsonPropertyKey(cont);
          if (!key.is_index()) {
            // Feedback doesn't match. Finish processing the current property
            // and continue in slow-path if we have more properties.
            if (V8_UNLIKELY(!ParseJsonPropertyValue(key))) return false;
            if (Check(JsonToken::COMMA)) {
              return ParseJsonObjectProperties<FastIterableState::kJsonSlow>(
                  cont, first_token_msg, {});
            }
            return true;
          }
          if (V8_UNLIKELY(!ParseJsonPropertyValue(key))) return false;
        }
      } else {
        DCHECK_EQ(fast_iterable_state, FastIterableState::kUnknown);
        JsonString key = ScanJsonPropertyKey(cont);
        // Indices don't participate in fast iterable key checks.
        if (key.is_index()) {
          if (V8_UNLIKELY(!ParseJsonPropertyValue(key))) return false;
          continue;
        }
        // Check if the key is fast iterable.
        // Some of the checks below are not relevant for the parser, but are
        // requirements for fast iterable keys in general (e.g. for
        // JSON.stringify).
        Tagged<Name> property_name = descriptors->GetKey(idx);
        bool is_slow = key.has_escape();
        // Check that the property is enumerable and located in field.
        PropertyDetails details = descriptors->GetDetails(idx);
        if (V8_UNLIKELY(details.IsDontEnum() ||
                        details.location() != PropertyLocation::kField)) {
          is_slow = true;
        }
        // Symbol property keys are slow.
        if (V8_UNLIKELY(IsSymbol(property_name))) {
          is_slow = true;
        }
        key_match = false;
        if (V8_LIKELY(!is_slow)) {
          DisallowGarbageCollection no_gc;
          // Property key is known to be fast so far, so it is guaranteed to
          // be a string.
          Tagged<String> expected_key = Cast<String>(property_name);
          Tagged<Map> key_map = expected_key->map();
          if (InstanceTypeChecker::IsTwoByteString(key_map)) {
            // Two-byte keys are slow.
            is_slow = true;
          } else {
            const uint8_t* expected_chars =
                GetFastKeyChars(isolate_, expected_key, key_map, no_gc);
            const uint32_t key_length = expected_key->length();
            key_match = FastKeyMatch(expected_chars, key_length);
          }
        }
        if (V8_UNLIKELY(is_slow)) {
          // The key is not fast iterable. Mark it as slow in the descriptor
          // array.
          descriptors->set_fast_iterable(FastIterableState::kJsonSlow);
        }
        // Finish parsing the property.
        if (V8_UNLIKELY(!ParseJsonPropertyValue(key))) return false;
        // If key is not fast iterable or doesn't match the feedback, we
        // continue on the slow-path.
        if (V8_UNLIKELY(is_slow || !key_match)) {
          if (Check(JsonToken::COMMA)) {
            return ParseJsonObjectProperties<FastIterableState::kJsonSlow>(
                cont, first_token_msg, {});
          }
          // No more properties to scan, we are done.
          return true;
        }
        ++idx;
      }
    } while (idx < InternalIndex(descriptors->number_of_descriptors()) &&
             Check(JsonToken::COMMA));
    if constexpr (fast_iterable_state == FastIterableState::kUnknown) {
      if (idx == InternalIndex(descriptors->number_of_descriptors())) {
        descriptors->set_fast_iterable_if(FastIterableState::kJsonFast,
                                          FastIterableState::kUnknown);
      }
    }
    // Additional, unknown properties. Scan them slow.
    if (Check(JsonToken::COMMA)) {
      return ParseJsonObjectProperties<FastIterableState::kJsonSlow>(
          cont, first_token_msg, descriptors);
    }
  }
  return true;
}
References v8::internal::COMMA, DCHECK_EQ, DCHECK_GT, v8::internal::anonymous_namespace{json-parser.cc}::GetFastKeyChars(), v8::internal::PropertyDetails::IsDontEnum(), v8::internal::InstanceTypeChecker::IsTwoByteString(), v8::internal::key, v8::internal::kField, v8::internal::PropertyDetails::location(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::STRING, V8_LIKELY, and V8_UNLIKELY.
ParseJsonPropertyValue()
template<typename Char >
bool v8::internal::JsonParser< Char >::ParseJsonPropertyValue (const JsonString & key) [inline], [private]
Definition at line 1487 of file json-parser.cc.
                                                                   {
  ExpectNext(JsonToken::COLON,
             MessageTemplate::kJsonParseExpectedColonAfterPropertyName);
  Handle<Object> value;
  if (V8_UNLIKELY(!ParseJsonValueRecursive().ToHandle(&value))) return false;
  property_stack_.emplace_back(key, value);
  return true;
}
References v8::internal::COLON, v8::internal::key, v8::anonymous_namespace{api.cc}::ToHandle(), V8_UNLIKELY, and v8::internal::value.
ParseJsonValue()
template<typename Char >
template<bool should_track_json_source>
MaybeHandle< Object > v8::internal::JsonParser< Char >::ParseJsonValue [private]
Definition at line 1837 of file json-parser.cc.
                                                     {
  std::vector<JsonContinuation> cont_stack;
  cont_stack.reserve(16);
  JsonContinuation cont(isolate_, JsonContinuation::kReturn, 0);
  Handle<Object> value;
  // When should_track_json_source is true, we use val_node to record current
  // JSON value's parse node.
  //
  // For primitive values, the val_node is the source string of the JSON value.
  //
  // For JSObject values, the val_node is an ObjectHashTable in which the key is
  // the property name and the first value is the property value's parse
  // node. The order in which properties are defined may be different from the
  // order in which properties are enumerated when calling
  // InternalizeJSONProperty for the JSObject value. E.g., the JSON source
  // string is '{"a": 1, "1": 2}', and the properties enumerate order is ["1",
  // "a"]. Moreover, properties may be defined repeatedly in the JSON string.
  // E.g., the JSON string is '{"a": 1, "a": 1}', and the properties enumerate
  // order is ["a"]. So we cannot use the FixedArray to record the properties's
  // parse node by the order in which properties are defined and we use a
  // ObjectHashTable here to record the property name and the property's parse
  // node. We then look up the property's parse node by the property name when
  // calling InternalizeJSONProperty. The second value associated with the key
  // is the property value's snapshot.
  //
  // For JSArray values, the val_node is a FixedArray containing the parse nodes
  // and snapshots of the elements.
  //
  // For information about snapshotting, see below.
  Handle<Object> val_node;
  // Record the start position and end position for the primitive values.
  uint32_t start_position;
  uint32_t end_position;
  // Workaround for -Wunused-but-set-variable on old gcc versions (version < 8).
  USE(start_position);
  USE(end_position);
  // element_val_node_stack is used to track all the elements's
  // parse nodes. And we use this to construct the JSArray's
  // parse node and value snapshot.
  SmallVector<Handle<Object>> element_val_node_stack;
  // property_val_node_stack is used to track all the property
  // value's parse nodes. And we use this to construct the
  // JSObject's parse node and value snapshot.
  SmallVector<Handle<Object>> property_val_node_stack;
  while (true) {
    // Produce a json value.
    //
    // Iterate until a value is produced. Starting but not immediately finishing
    // objects and arrays will cause the loop to continue until a first member
    // is completed.
    while (true) {
      SkipWhitespace();
      // The switch is immediately followed by 'break' so we can use 'break' to
      // break out of the loop, and 'continue' to continue the loop.
      if constexpr (should_track_json_source) {
        start_position = position();
      }
      switch (peek()) {
        case JsonToken::STRING:
          Consume(JsonToken::STRING);
          value = MakeString(ScanJsonString(false));
          if constexpr (should_track_json_source) {
            end_position = position();
            val_node = isolate_->factory()->NewSubString(
                source_, start_position, end_position);
          }
          break;
        case JsonToken::NUMBER:
          value = ParseJsonNumber();
          if constexpr (should_track_json_source) {
            end_position = position();
            val_node = isolate_->factory()->NewSubString(
                source_, start_position, end_position);
          }
          break;
        case JsonToken::LBRACE: {
          Consume(JsonToken::LBRACE);
          if (Check(JsonToken::RBRACE)) {
            // TODO(verwaest): Directly use the map instead.
            value = factory()->NewJSObject(object_constructor_);
            if constexpr (should_track_json_source) {
              val_node = ObjectTwoHashTable::New(isolate_, 0);
            }
            break;
          }
          // Start parsing an object with properties.
          cont_stack.emplace_back(std::move(cont));
          cont = JsonContinuation(isolate_, JsonContinuation::kObjectProperty,
                                  property_stack_.size());
          // Parse the property key.
          ExpectNext(JsonToken::STRING,
                     MessageTemplate::kJsonParseExpectedPropNameOrRBrace);
          property_stack_.emplace_back(ScanJsonPropertyKey(&cont));
          if constexpr (should_track_json_source) {
            property_val_node_stack.emplace_back(Handle<Object>());
          }
          ExpectNext(JsonToken::COLON,
                     MessageTemplate::kJsonParseExpectedColonAfterPropertyName);
          // Continue to start producing the first property value.
          continue;
        }
        case JsonToken::LBRACK:
          Consume(JsonToken::LBRACK);
          if (Check(JsonToken::RBRACK)) {
            value = factory()->NewJSArray(0, PACKED_SMI_ELEMENTS);
            if constexpr (should_track_json_source) {
              val_node = factory()->NewFixedArray(0);
            }
            break;
          }
          // Start parsing an array with elements.
          cont_stack.emplace_back(std::move(cont));
          cont = JsonContinuation(isolate_, JsonContinuation::kArrayElement,
                                  element_stack_.size());
          // Continue to start producing the first array element.
          continue;
        case JsonToken::TRUE_LITERAL:
          ScanLiteral("true");
          value = factory()->true_value();
          if constexpr (should_track_json_source) {
            val_node = isolate_->factory()->true_string();
          }
          break;
        case JsonToken::FALSE_LITERAL:
          ScanLiteral("false");
          value = factory()->false_value();
          if constexpr (should_track_json_source) {
            val_node = isolate_->factory()->false_string();
          }
          break;
        case JsonToken::NULL_LITERAL:
          ScanLiteral("null");
          value = factory()->null_value();
          if constexpr (should_track_json_source) {
            val_node = isolate_->factory()->null_string();
          }
          break;
        case JsonToken::COLON:
        case JsonToken::COMMA:
        case JsonToken::ILLEGAL:
        case JsonToken::RBRACE:
        case JsonToken::RBRACK:
        case JsonToken::EOS:
          ReportUnexpectedCharacter(CurrentCharacter());
          // Pop the continuation stack to correctly tear down handle scopes.
          while (!cont_stack.empty()) {
            cont = std::move(cont_stack.back());
            cont_stack.pop_back();
          }
          return MaybeHandle<Object>();
        case JsonToken::WHITESPACE:
          UNREACHABLE();
      }
      // Done producing a value, consume it.
      break;
    }
    // Consume a produced json value.
    //
    // Iterate as long as values are produced (arrays or object literals are
    // finished).
    while (true) {
      // The switch is immediately followed by 'break' so we can use 'break' to
      // break out of the loop, and 'continue' to continue the loop.
      switch (cont.type()) {
        case JsonContinuation::kReturn:
          if constexpr (should_track_json_source) {
            DCHECK(!val_node.is_null());
            Tagged<Object> raw_value = *value;
            parsed_val_node_ = cont.scope.CloseAndEscape(val_node);
            return cont.scope.CloseAndEscape(handle(raw_value, isolate_));
          } else {
            return cont.scope.CloseAndEscape(value);
          }
        case JsonContinuation::kObjectProperty: {
          // Store the previous property value into its property info.
          property_stack_.back().value = value;
          if constexpr (should_track_json_source) {
            property_val_node_stack.back() = val_node;
          }
          if (V8_LIKELY(Check(JsonToken::COMMA))) {
            // Parse the property key.
            ExpectNext(
                JsonToken::STRING,
                MessageTemplate::kJsonParseExpectedDoubleQuotedPropertyName);
            property_stack_.emplace_back(ScanJsonPropertyKey(&cont));
            if constexpr (should_track_json_source) {
              property_val_node_stack.emplace_back(Handle<Object>());
            }
            ExpectNext(
                JsonToken::COLON,
                MessageTemplate::kJsonParseExpectedColonAfterPropertyName);
            // Break to start producing the subsequent property value.
            break;
          }
          Handle<Map> feedback;
          if (cont_stack.size() > 0 &&
              cont_stack.back().type() == JsonContinuation::kArrayElement &&
              cont_stack.back().index < element_stack_.size() &&
              IsJSObject(*element_stack_.back())) {
            Tagged<Map> maybe_feedback =
                Cast<JSObject>(*element_stack_.back())->map();
            // Don't consume feedback from objects with a map that's detached
            // from the transition tree.
            if (!maybe_feedback->IsDetached(isolate_)) {
              feedback = handle(maybe_feedback, isolate_);
            }
          }
          value = BuildJsonObject<should_track_json_source>(cont, feedback);
          Expect(JsonToken::RBRACE,
                 MessageTemplate::kJsonParseExpectedCommaOrRBrace);
          // Return the object.
          if constexpr (should_track_json_source) {
            size_t start = cont.index;
            int num_properties =
                static_cast<int>(property_stack_.size() - start);
            Handle<ObjectTwoHashTable> table =
                ObjectTwoHashTable::New(isolate(), num_properties);
            for (int i = 0; i < num_properties; i++) {
              const JsonProperty& property = property_stack_[start + i];
              DirectHandle<Object> property_val_node =
                  property_val_node_stack[start + i];
              DirectHandle<Object> property_snapshot = property.value;
              DirectHandle<String> key;
              if (property.string.is_index()) {
                key = factory()->Uint32ToString(property.string.index());
              } else {
                key = MakeString(property.string);
              }
              table = ObjectTwoHashTable::Put(
                  isolate(), table, key,
                  {property_val_node, property_snapshot});
            }
            property_val_node_stack.resize(cont.index);
            DisallowGarbageCollection no_gc;
            Tagged<ObjectTwoHashTable> raw_table = *table;
            value = cont.scope.CloseAndEscape(value);
            val_node = cont.scope.CloseAndEscape(handle(raw_table, isolate_));
          } else {
            value = cont.scope.CloseAndEscape(value);
          }
          property_stack_.resize(cont.index);
          // Pop the continuation.
          cont = std::move(cont_stack.back());
          cont_stack.pop_back();
          // Consume to produced object.
          continue;
        }
        case JsonContinuation::kArrayElement: {
          // Store the previous element on the stack.
          element_stack_.emplace_back(value);
          if constexpr (should_track_json_source) {
            element_val_node_stack.emplace_back(val_node);
          }
          // Break to start producing the subsequent element value.
          if (V8_LIKELY(Check(JsonToken::COMMA))) break;
          value = BuildJsonArray(cont.index);
          Expect(JsonToken::RBRACK,
                 MessageTemplate::kJsonParseExpectedCommaOrRBrack);
          // Return the array.
          if constexpr (should_track_json_source) {
            size_t start = cont.index;
            int num_elements = static_cast<int>(element_stack_.size() - start);
            DirectHandle<FixedArray> val_node_and_snapshot_array =
                factory()->NewFixedArray(num_elements * 2);
            DisallowGarbageCollection no_gc;
            Tagged<FixedArray> raw_val_node_and_snapshot_array =
                *val_node_and_snapshot_array;
            for (int i = 0; i < num_elements; i++) {
              raw_val_node_and_snapshot_array->set(
                  i * 2, *element_val_node_stack[start + i]);
              raw_val_node_and_snapshot_array->set(i * 2 + 1,
                                                   *element_stack_[start + i]);
            }
            element_val_node_stack.resize(cont.index);
            value = cont.scope.CloseAndEscape(value);
            val_node = cont.scope.CloseAndEscape(
                handle(raw_val_node_and_snapshot_array, isolate_));
          } else {
            value = cont.scope.CloseAndEscape(value);
          }
          element_stack_.resize(cont.index);
          // Pop the continuation.
          cont = std::move(cont_stack.back());
          cont_stack.pop_back();
          // Consume the produced array.
          continue;
        }
      }
      // Done consuming a value. Produce next value.
      break;
    }
  }
}
References v8::base::SmallVector< T, kSize, Allocator >::back(), v8::internal::COLON, v8::internal::COMMA, v8::internal::DCHECK(), v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::internal::EOS, v8::internal::FALSE_LITERAL, v8::internal::handle(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ILLEGAL, v8::internal::JsonParser< Char >::JsonContinuation::index, v8::internal::HandleBase::is_null(), v8::internal::key, v8::internal::LBRACE, v8::internal::LBRACK, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NULL_LITERAL, v8::internal::NUMBER, v8::internal::PACKED_SMI_ELEMENTS, v8::internal::ObjectMultiHashTableBase< ObjectTwoHashTable, 2 >::Put(), v8::internal::RBRACE, v8::internal::RBRACK, v8::base::SmallVector< T, kSize, Allocator >::resize(), v8::internal::JsonParser< Char >::JsonContinuation::scope, v8::internal::STRING, v8::internal::TRUE_LITERAL, v8::internal::JsonParser< Char >::JsonContinuation::type(), v8::internal::UNREACHABLE(), USE, V8_LIKELY, v8::internal::value, and v8::internal::WHITESPACE.
ParseJsonValueRecursive()
template<typename Char >
MaybeHandle< Object > v8::internal::JsonParser< Char >::ParseJsonValueRecursive (Handle< Map > feedback = {}) [inline], [private]
Definition at line 1439 of file json-parser.cc.
                          {
  SkipWhitespace();
  switch (peek()) {
    case JsonToken::NUMBER:
      return ParseJsonNumber();
    case JsonToken::STRING:
      Consume(JsonToken::STRING);
      return MakeString(ScanJsonString(false));
    case JsonToken::TRUE_LITERAL:
      ScanLiteral("true");
      return factory()->true_value();
    case JsonToken::FALSE_LITERAL:
      ScanLiteral("false");
      return factory()->false_value();
    case JsonToken::NULL_LITERAL:
      ScanLiteral("null");
      return factory()->null_value();
    case JsonToken::LBRACE:
      return ParseJsonObject(feedback);
    case JsonToken::LBRACK:
      return ParseJsonArray();
    case JsonToken::COLON:
    case JsonToken::COMMA:
    case JsonToken::ILLEGAL:
    case JsonToken::RBRACE:
    case JsonToken::RBRACK:
    case JsonToken::EOS:
      ReportUnexpectedCharacter(CurrentCharacter());
      // Pop the continuation stack to correctly tear down handle scopes.
      return MaybeHandle<Object>();
    case JsonToken::WHITESPACE:
      UNREACHABLE();
  }
}
References v8::internal::COLON, v8::internal::COMMA, v8::internal::EOS, v8::internal::FALSE_LITERAL, v8::internal::ILLEGAL, v8::internal::LBRACE, v8::internal::LBRACK, v8::internal::NULL_LITERAL, v8::internal::NUMBER, v8::internal::RBRACE, v8::internal::RBRACK, v8::internal::STRING, v8::internal::TRUE_LITERAL, v8::internal::UNREACHABLE(), and v8::internal::WHITESPACE.
ParseRawJson()
template<typename Char >
bool v8::internal::JsonParser< Char >::ParseRawJson [private]
Definition at line 1396 of file json-parser.cc.
                                    {
  if (end_ == cursor_) {
    isolate_->Throw(*isolate_->factory()->NewSyntaxError(
        MessageTemplate::kInvalidRawJsonValue));
    return false;
  }
  next_ = GetTokenForCharacter(*cursor_);
  switch (peek()) {
    case JsonToken::STRING:
      Consume(JsonToken::STRING);
      ScanJsonString(false);
      break;
    case JsonToken::NUMBER:
      ParseJsonNumber();
      break;
    case JsonToken::TRUE_LITERAL:
      ScanLiteral("true");
      break;
    case JsonToken::FALSE_LITERAL:
      ScanLiteral("false");
      break;
    case JsonToken::NULL_LITERAL:
      ScanLiteral("null");
      break;
    default:
      ReportUnexpectedCharacter(CurrentCharacter());
      return false;
  }
  if (isolate_->has_exception()) return false;
  if (cursor_ != end_) {
    isolate_->Throw(*isolate_->factory()->NewSyntaxError(
        MessageTemplate::kInvalidRawJsonValue));
    return false;
  }
  return true;
}
References v8::internal::FALSE_LITERAL, v8::internal::anonymous_namespace{json-parser.cc}::GetTokenForCharacter(), v8::internal::NULL_LITERAL, v8::internal::NUMBER, v8::internal::STRING, and v8::internal::TRUE_LITERAL.
peek()
template<typename Char >
JsonToken v8::internal::JsonParser< Char >::peek () const [inline], [private]
Definition at line 235 of file json-parser.h.
{ return next_; }
References v8::internal::JsonParser< Char >::next_.
Referenced by v8::internal::JsonParser< Char >::Consume(), and v8::internal::JsonParser< Char >::Expect().
position()
template<typename Char >
uint32_t v8::internal::JsonParser< Char >::position () const [inline], [private]
Definition at line 411 of file json-parser.h.
{ return static_cast<uint32_t>(cursor_ - chars_); }
References v8::internal::JsonParser< Char >::chars_, and v8::internal::JsonParser< Char >::cursor_.
Referenced by v8::internal::JsonParser< Char >::UpdatePointers().
remaining_chars()
template<typename Char >
size_t v8::internal::JsonParser< Char >::remaining_chars () const [inline], [private]
Definition at line 409 of file json-parser.h.
{ return end_ - cursor_; }
References v8::internal::JsonParser< Char >::cursor_, and v8::internal::JsonParser< Char >::end_.
Referenced by v8::internal::JsonParser< Char >::ScanLiteral().
ReportUnexpectedCharacter()
template<typename Char >
void v8::internal::JsonParser< Char >::ReportUnexpectedCharacter (base::uc32 c) [private]
Definition at line 506 of file json-parser.cc.
                                                           {
  JsonToken token = JsonToken::ILLEGAL;
  if (c == kEndOfString) {
    token = JsonToken::EOS;
  } else if (c <= unibrow::Latin1::kMaxChar) {
    token = one_char_json_tokens[c];
  }
  return ReportUnexpectedToken(token);
}
References v8::internal::EOS, v8::internal::ILLEGAL, unibrow::Latin1::kMaxChar, and v8::internal::anonymous_namespace{json-parser.cc}::one_char_json_tokens.
Referenced by v8::internal::JsonParser< Char >::ScanLiteral().
ReportUnexpectedToken()
template<typename Char >
void v8::internal::JsonParser< Char >::ReportUnexpectedToken (JsonToken token, std::optional< MessageTemplate > errorMessage = std::nullopt) [private]
Definition at line 462 of file json-parser.cc.
                                                                {
  // Some exception (for example stack overflow) was already thrown.
  if (isolate_->has_exception()) return;
  // Parse failed. Current character is the unexpected token.
  Factory* factory = this->factory();
  int offset = IsSlicedString(*original_source_)
                   ? Cast<SlicedString>(*original_source_)->offset()
                   : 0;
  int pos = position() - offset;
  DirectHandle<Object> arg(Smi::FromInt(pos), isolate());
  DirectHandle<Object> arg2;
  DirectHandle<Object> arg3;
  CalculateFileLocation(arg2, arg3);
  MessageTemplate message =
      errorMessage ? errorMessage.value()
                   : LookUpErrorMessageForJsonToken(token, arg, arg2, pos);
  Handle<Script> script(factory->NewScript(original_source_));
  DCHECK_IMPLIES(isolate_->NeedsSourcePositions(), script->has_line_ends());
  DebuggableStackFrameIterator it(isolate_);
  if (!it.done() && it.is_javascript()) {
    FrameSummary summary = it.GetTopValidFrame();
    script->set_eval_from_shared(summary.AsJavaScript().function()->shared());
    if (IsScript(*summary.script())) {
      script->set_origin_options(
          Cast<Script>(*summary.script())->origin_options());
    }
  }
  // We should sent compile error event because we compile JSON object in
  // separated source file.
  isolate()->debug()->OnCompileError(script);
  MessageLocation location(script, pos, pos + 1);
  isolate()->ThrowAt(factory->NewSyntaxError(message, arg, arg2, arg3),
                     &location);
  // Move the cursor to the end so we won't be able to proceed parsing.
  cursor_ = end_;
}
References DCHECK_IMPLIES, v8::internal::DebuggableStackFrameIterator::done(), v8::internal::Smi::FromInt(), v8::internal::DebuggableStackFrameIterator::GetTopValidFrame(), v8::internal::DebuggableStackFrameIterator::is_javascript(), v8::internal::InstanceTypeChecker::IsSlicedString(), v8::internal::FactoryBase< Impl >::NewScript(), v8::internal::FrameSummary::script(), and v8::internal::script.
Referenced by v8::internal::JsonParser< Char >::Expect(), and v8::internal::JsonParser< Char >::ScanLiteral().
roots()
template<typename Char >
ReadOnlyRoots v8::internal::JsonParser< Char >::roots () [inline], [private]
Definition at line 378 of file json-parser.h.
{ return ReadOnlyRoots(isolate_); }
References v8::internal::JsonParser< Char >::isolate_.
ScanJsonPropertyKey()
template<typename Char >
JsonString v8::internal::JsonParser< Char >::ScanJsonPropertyKey (JsonContinuation * cont) [private]
Definition at line 592 of file json-parser.cc.
                                                                       {
  {
    DisallowGarbageCollection no_gc;
    const Char* start = cursor_;
    base::uc32 first = CurrentCharacter();
    if (first == '\\' && NextCharacter() == 'u') first = ScanUnicodeCharacter();
    if (IsDecimalDigit(first)) {
      if (first == '0') {
        if (NextCharacter() == '"') {
          advance();
          // Record element information.
          cont->elements++;
          DCHECK_LE(0, cont->max_index);
          return JsonString(0);
        }
      } else {
        uint32_t index = first - '0';
        while (true) {
          cursor_ = std::find_if(cursor_ + 1, end_, [&index](Char c) {
            return !IsDecimalDigit(c) || !TryAddArrayIndexChar(&index, c);
          });
          if (CurrentCharacter() == '"') {
            advance();
            // Record element information.
            cont->elements++;
            cont->max_index = std::max(cont->max_index, index);
            return JsonString(index);
          }
          if (CurrentCharacter() == '\\' && NextCharacter() == 'u') {
            base::uc32 c = ScanUnicodeCharacter();
            if (IsDecimalDigit(c) && TryAddArrayIndexChar(&index, c)) continue;
          }
          break;
        }
      }
    }
    // Reset cursor_ to start if the key is not an index.
    cursor_ = start;
  }
  return ScanJsonString(true);
}
References DCHECK_LE, v8::internal::JsonParser< Char >::JsonContinuation::elements, v8::internal::index, v8::internal::IsDecimalDigit(), v8::internal::JsonParser< Char >::JsonContinuation::max_index, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::TryAddArrayIndexChar().
ScanJsonString()
template<typename Char >
JsonString v8::internal::JsonParser< Char >::ScanJsonString (bool needs_internalization) [private]
Definition at line 2432 of file json-parser.cc.
                                                                      {
  DisallowGarbageCollection no_gc;
  uint32_t start = position();
  uint32_t offset = start;
  bool has_escape = false;
  base::uc32 bits = 0;
  while (true) {
    cursor_ = std::find_if(cursor_, end_, [&bits](Char c) {
      if (sizeof(Char) == 2 && V8_UNLIKELY(c > unibrow::Latin1::kMaxChar)) {
        bits |= c;
        return false;
      }
      return MayTerminateJsonString(character_json_scan_flags[c]);
    });
    if (V8_UNLIKELY(is_at_end())) {
      AllowGarbageCollection allow_before_exception;
      ReportUnexpectedToken(JsonToken::ILLEGAL,
                            MessageTemplate::kJsonParseUnterminatedString);
      break;
    }
    if (*cursor_ == '"') {
      uint32_t end = position();
      advance();
      uint32_t length = end - offset;
      bool convert = sizeof(Char) == 1 ? bits > unibrow::Latin1::kMaxChar
                                       : bits <= unibrow::Latin1::kMaxChar;
      constexpr int kMaxInternalizedStringValueLength = 10;
      bool internalize =
          needs_internalization ||
          (sizeof(Char) == 1 && length < kMaxInternalizedStringValueLength);
      return JsonString(start, length, convert, internalize, has_escape);
    }
    if (*cursor_ == '\\') {
      has_escape = true;
      base::uc32 c = NextCharacter();
      if (V8_UNLIKELY(!base::IsInRange(
              c, 0, static_cast<int32_t>(unibrow::Latin1::kMaxChar)))) {
        AllowGarbageCollection allow_before_exception;
        ReportUnexpectedCharacter(c);
        break;
      }
      switch (GetEscapeKind(character_json_scan_flags[c])) {
        case EscapeKind::kSelf:
        case EscapeKind::kBackspace:
        case EscapeKind::kTab:
        case EscapeKind::kNewLine:
        case EscapeKind::kFormFeed:
        case EscapeKind::kCarriageReturn:
          offset += 1;
          break;
        case EscapeKind::kUnicode: {
          base::uc32 value = ScanUnicodeCharacter();
          if (value == kInvalidUnicodeCharacter) {
            AllowGarbageCollection allow_before_exception;
            ReportUnexpectedToken(JsonToken::ILLEGAL,
                                  MessageTemplate::kJsonParseBadUnicodeEscape);
            return JsonString();
          }
          bits |= value;
          // \uXXXX results in either 1 or 2 Utf16 characters, depending on
          // whether the decoded value requires a surrogate pair.
          offset += 5 - (value > static_cast<base::uc32>(
                                     unibrow::Utf16::kMaxNonSurrogateCharCode));
          break;
        }
        case EscapeKind::kIllegal:
          AllowGarbageCollection allow_before_exception;
          ReportUnexpectedToken(JsonToken::ILLEGAL,
                                MessageTemplate::kJsonParseBadEscapedCharacter);
          return JsonString();
      }
      advance();
      continue;
    }
    DCHECK_LT(*cursor_, 0x20);
    AllowGarbageCollection allow_before_exception;
    ReportUnexpectedToken(JsonToken::ILLEGAL,
                          MessageTemplate::kJsonParseBadControlCharacter);
    break;
  }
  return JsonString();
}
References v8::internal::anonymous_namespace{json-parser.cc}::character_json_scan_flags, DCHECK_LT, v8::internal::compiler::end(), v8::internal::anonymous_namespace{json-parser.cc}::GetEscapeKind(), v8::internal::ILLEGAL, unibrow::Latin1::kMaxChar, unibrow::Utf16::kMaxNonSurrogateCharCode, v8::internal::length, v8::internal::anonymous_namespace{json-parser.cc}::MayTerminateJsonString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, V8_UNLIKELY, and v8::internal::value.
ScanLiteral()
template<typename Char >
template<size_t N>
void v8::internal::JsonParser< Char >::ScanLiteral (const char(&) s[N]) [inline], [private]
Definition at line 266 of file json-parser.h.
                                       {
    DCHECK(!is_at_end());
    // There's at least 1 character, we always consume a character and compare
    // the next character. The first character was compared before we jumped
    // to ScanLiteral.
    static_assert(N > 2);
    size_t remaining = remaining_chars();
    if (V8_LIKELY(remaining >= N - 1 &&
                  CompareCharsEqual(s + 1, cursor_ + 1, N - 2))) {
      cursor_ += N - 1;
      return;
    }
    cursor_++;
    for (size_t i = 0; i < std::min(N - 2, remaining - 1); i++) {
      if (*(s + 1 + i) != *cursor_) {
        ReportUnexpectedCharacter(*cursor_);
        return;
      }
      cursor_++;
    }
    DCHECK(is_at_end());
    ReportUnexpectedToken(JsonToken::EOS);
  }
References v8::internal::CompareCharsEqual(), v8::internal::JsonParser< Char >::cursor_, v8::internal::DCHECK(), v8::internal::EOS, v8::internal::JsonParser< Char >::is_at_end(), v8::internal::N, v8::internal::JsonParser< Char >::remaining_chars(), v8::internal::JsonParser< Char >::ReportUnexpectedCharacter(), v8::internal::JsonParser< Char >::ReportUnexpectedToken(), and V8_LIKELY.
ScanUnicodeCharacter()
template<typename Char >
base::uc32 v8::internal::JsonParser< Char >::ScanUnicodeCharacter [private]
Definition at line 580 of file json-parser.cc.
                                                {
  base::uc32 value = 0;
  for (int i = 0; i < 4; i++) {
    int digit = base::HexValue(NextCharacter());
    if (V8_UNLIKELY(digit < 0)) return kInvalidUnicodeCharacter;
    value = value * 16 + digit;
  }
  return value;
}
References v8::base::HexValue(), V8_UNLIKELY, and v8::internal::value.
SkipWhitespace()
template<typename Char >
void v8::internal::JsonParser< Char >::SkipWhitespace [private]
Definition at line 566 of file json-parser.cc.
                                      {
  JsonToken local_next = JsonToken::EOS;
  cursor_ = std::find_if(cursor_, end_, [&](Char c) {
    JsonToken current = GetTokenForCharacter(c);
    bool result = current != JsonToken::WHITESPACE;
    if (V8_LIKELY(result)) local_next = current;
    return result;
  });
  next_ = local_next;
}
References v8::internal::EOS, v8::internal::anonymous_namespace{json-parser.cc}::GetTokenForCharacter(), v8::base::internal::result, V8_LIKELY, and v8::internal::WHITESPACE.
Referenced by v8::internal::JsonParser< Char >::Check(), and v8::internal::JsonParser< Char >::ExpectNext().
UpdatePointers()
template<typename Char >
void v8::internal::JsonParser< Char >::UpdatePointers () [inline], [private]
Definition at line 389 of file json-parser.h.
                        {
    DisallowGarbageCollection no_gc;
    const Char* chars = Cast<SeqString>(source_)->GetChars(no_gc);
    if (chars_ != chars) {
      size_t position = cursor_ - chars_;
      size_t length = end_ - chars_;
      chars_ = chars;
      cursor_ = chars_ + position;
      end_ = chars_ + length;
    }
  }
References v8::internal::JsonParser< Char >::chars_, v8::internal::JsonParser< Char >::cursor_, v8::internal::JsonParser< Char >::end_, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::JsonParser< Char >::position(), and v8::internal::JsonParser< Char >::source_.
Referenced by v8::internal::JsonParser< Char >::UpdatePointersCallback().
UpdatePointersCallback()
template<typename Char >
static void v8::internal::JsonParser< Char >::UpdatePointersCallback (void * parser) [inline], [static], [private]
Definition at line 385 of file json-parser.h.
                                                   {
    reinterpret_cast<JsonParser<Char>*>(parser)->UpdatePointers();
  }
References v8::internal::JsonParser< Char >::UpdatePointers().
Referenced by v8::internal::JsonParser< Char >::JsonParser().
Member Data Documentation
chars_
template<typename Char >
const Char* v8::internal::JsonParser< Char >::chars_ [private]
Definition at line 437 of file json-parser.h.
Referenced by v8::internal::JsonParser< Char >::GetKeyChars(), v8::internal::JsonParser< Char >::JsonParser(), v8::internal::JsonParser< Char >::position(), and v8::internal::JsonParser< Char >::UpdatePointers().
chars_may_relocate_
template<typename Char >
bool v8::internal::JsonParser< Char >::chars_may_relocate_ [private]
Definition at line 417 of file json-parser.h.
Referenced by v8::internal::JsonParser< Char >::JsonParser().
cursor_
template<typename Char >
const Char* v8::internal::JsonParser< Char >::cursor_ [private]
Definition at line 435 of file json-parser.h.
Referenced by v8::internal::JsonParser< Char >::advance(), v8::internal::JsonParser< Char >::CurrentCharacter(), v8::internal::JsonParser< Char >::is_at_end(), v8::internal::JsonParser< Char >::JsonParser(), v8::internal::JsonParser< Char >::position(), v8::internal::JsonParser< Char >::remaining_chars(), v8::internal::JsonParser< Char >::ScanLiteral(), and v8::internal::JsonParser< Char >::UpdatePointers().
double_elements_
template<typename Char >
SmallVector<double> v8::internal::JsonParser< Char >::double_elements_ [private]
Definition at line 427 of file json-parser.h.
element_stack_
template<typename Char >
SmallVector<Handle<Object> > v8::internal::JsonParser< Char >::element_stack_ [private]
Definition at line 425 of file json-parser.h.
end_
template<typename Char >
const Char* v8::internal::JsonParser< Char >::end_ [private]
Definition at line 436 of file json-parser.h.
Referenced by v8::internal::JsonParser< Char >::NamedPropertyIterator< Char >::Advance(), v8::internal::JsonParser< Char >::NamedPropertyIterator< Char >::Done(), v8::internal::JsonParser< Char >::is_at_end(), v8::internal::JsonParser< Char >::JsonParser(), v8::internal::JsonParser< Char >::NamedPropertyIterator< Char >::NamedPropertyIterator(), v8::internal::JsonParser< Char >::remaining_chars(), and v8::internal::JsonParser< Char >::UpdatePointers().
hash_seed_
template<typename Char >
const uint64_t v8::internal::JsonParser< Char >::hash_seed_ [private]
Definition at line 414 of file json-parser.h.
isolate_
template<typename Char >
Isolate* v8::internal::JsonParser< Char >::isolate_ [private]
Definition at line 413 of file json-parser.h.
Referenced by v8::internal::JsonParser< Char >::factory(), v8::internal::JsonParser< Char >::isolate(), and v8::internal::JsonParser< Char >::roots().
kEndOfString
template<typename Char >
constexpr base::uc32 v8::internal::JsonParser< Char >::kEndOfString = static_cast<base::uc32>(-1) [static], [constexpr]
Definition at line 184 of file json-parser.h.
Referenced by v8::internal::JsonParser< Char >::CurrentCharacter().
kInitialSpecialStringLength
template<typename Char >
const int v8::internal::JsonParser< Char >::kInitialSpecialStringLength = 32 [static], [private]
Definition at line 383 of file json-parser.h.
kInvalidUnicodeCharacter
template<typename Char >
constexpr base::uc32 v8::internal::JsonParser< Char >::kInvalidUnicodeCharacter [static], [constexpr]
Initial value:
=
      static_cast<base::uc32>(-1)
Definition at line 185 of file json-parser.h.
kIsOneByte
template<typename Char >
const bool v8::internal::JsonParser< Char >::kIsOneByte = sizeof(Char) == 1 [static], [private]
Definition at line 402 of file json-parser.h.
kMaxContextCharacters
template<typename Char >
const int v8::internal::JsonParser< Char >::kMaxContextCharacters = 10 [static], [private]
Definition at line 352 of file json-parser.h.
kMinOriginalSourceLengthForContext
template<typename Char >
const int v8::internal::JsonParser< Char >::kMinOriginalSourceLengthForContext [static], [private]
Initial value:
=
      (kMaxContextCharacters * 2) + 1
Definition at line 353 of file json-parser.h.
next_
template<typename Char >
JsonToken v8::internal::JsonParser< Char >::next_ [private]
Definition at line 415 of file json-parser.h.
Referenced by v8::internal::JsonParser< Char >::Check(), and v8::internal::JsonParser< Char >::peek().
object_constructor_
template<typename Char >
Handle<JSFunction> v8::internal::JsonParser< Char >::object_constructor_ [private]
Definition at line 418 of file json-parser.h.
Referenced by v8::internal::JsonParser< Char >::object_constructor().
original_source_
template<typename Char >
const Handle<String> v8::internal::JsonParser< Char >::original_source_ [private]
Definition at line 419 of file json-parser.h.
parsed_val_node_
template<typename Char >
MaybeHandle<Object> v8::internal::JsonParser< Char >::parsed_val_node_ [private]
Definition at line 423 of file json-parser.h.
Referenced by v8::internal::JsonParser< Char >::Parse().
property_stack_
template<typename Char >
SmallVector<JsonProperty> v8::internal::JsonParser< Char >::property_stack_ [private]
Definition at line 426 of file json-parser.h.
smi_elements_
template<typename Char >
SmallVector<int> v8::internal::JsonParser< Char >::smi_elements_ [private]
Definition at line 428 of file json-parser.h.
source_
template<typename Char >
Handle<String> v8::internal::JsonParser< Char >::source_ [private]
Definition at line 420 of file json-parser.h.
Referenced by v8::internal::JsonParser< Char >::JsonParser(), and v8::internal::JsonParser< Char >::UpdatePointers().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/json/json-parser.h
/mnt/V8SourceCode/src/json/json-parser.cc