v8::internal::wasm::gdb_server::GdbServer Class Reference
#include <gdb-server.h>
Classes
class DebugDelegate
struct WasmModuleInfo
Public Member Functions
GdbServer (const GdbServer &)=delete
GdbServer & operator= (const GdbServer &)=delete
~GdbServer ()
std::vector< WasmModuleInfo > GetLoadedModules (bool clear_module_list_changed_flag=false)
bool HasModuleListChanged () const
bool GetWasmGlobal (uint32_t frame_index, uint32_t index, uint8_t *buffer, uint32_t buffer_size, uint32_t *size)
bool GetWasmLocal (uint32_t frame_index, uint32_t index, uint8_t *buffer, uint32_t buffer_size, uint32_t *size)
bool GetWasmStackValue (uint32_t frame_index, uint32_t index, uint8_t *buffer, uint32_t buffer_size, uint32_t *size)
uint32_t GetWasmMemory (uint32_t module_id, uint32_t offset, uint8_t *buffer, uint32_t size)
uint32_t GetWasmData (uint32_t module_id, uint32_t offset, uint8_t *buffer, uint32_t size)
uint32_t GetWasmModuleBytes (wasm_addr_t address, uint8_t *buffer, uint32_t size)
bool AddBreakpoint (uint32_t wasm_module_id, uint32_t offset)
bool RemoveBreakpoint (uint32_t wasm_module_id, uint32_t offset)
std::vector< wasm_addr_t > GetWasmCallStack () const
void AddIsolate (Isolate *isolate)
void RemoveIsolate (Isolate *isolate)
void Suspend ()
void PrepareStep ()
void QuitMessageLoopOnPause ()
template<typename Functor >
auto RunSyncTask (Functor &&callback) const
Static Public Member Functions
static std::unique_ptr< GdbServer > Create ()
Private Types
typedef std::map< uint64_t, int > BreakpointsMap
typedef std::map< uint32_t, WasmModuleDebug > ScriptsMap
typedef std::map< Isolate *, std::unique_ptr< DebugDelegate > > IsolateDebugDelegateMap
Private Member Functions
GdbServer ()
void RunMessageLoopOnPause ()
template<typename Callback >
auto RunSyncTask (Callback &&callback) const
void AddWasmModule (uint32_t module_id, Local< debug::WasmScript > wasm_script)
bool GetModuleDebugHandler (uint32_t module_id, WasmModuleDebug **wasm_module_debug)
Target & GetTarget () const
Private Attributes
std::unique_ptr< GdbServerThread > thread_
std::unique_ptr< TaskRunner > task_runner_
std::atomic< bool > has_module_list_changed_
BreakpointsMap breakpoints_
ScriptsMap scripts_
IsolateDebugDelegateMap isolate_delegates_
Detailed Description
Definition at line 25 of file gdb-server.h.
Member Typedef Documentation
BreakpointsMap
typedef std::map<uint64_t, int> v8::internal::wasm::gdb_server::GdbServer::BreakpointsMap [private]
Definition at line 197 of file gdb-server.h.
IsolateDebugDelegateMap
typedef std::map<Isolate*, std::unique_ptr<DebugDelegate> > v8::internal::wasm::gdb_server::GdbServer::IsolateDebugDelegateMap [private]
Definition at line 204 of file gdb-server.h.
ScriptsMap
typedef std::map<uint32_t, WasmModuleDebug> v8::internal::wasm::gdb_server::GdbServer::ScriptsMap [private]
Definition at line 200 of file gdb-server.h.
Constructor & Destructor Documentation
GdbServer() [1/2]
v8::internal::wasm::gdb_server::GdbServer::GdbServer (const GdbServer &) [delete]
 GdbServer()
v8::internal::wasm::gdb_server::GdbServer::~GdbServer ()
Definition at line 137 of file gdb-server.cc.
                      {
  // All Isolates have been deregistered.
  DCHECK(isolate_delegates_.empty());
  if (thread_) {
    // Waits for the GDB-stub thread to terminate.
    thread_->Stop();
    thread_->Join();
  }
}
References v8::internal::DCHECK(), isolate_delegates_, and thread_.
GdbServer() [2/2]
v8::internal::wasm::gdb_server::GdbServer::GdbServer () [private]
Definition at line 108 of file gdb-server.cc.
                     : has_module_list_changed_(false) {
  task_runner_ = std::make_unique<TaskRunner>();
}
References task_runner_.
Referenced by Create().
Member Function Documentation
AddBreakpoint()
bool v8::internal::wasm::gdb_server::GdbServer::AddBreakpoint (uint32_t wasm_module_id, uint32_t offset)
Definition at line 268 of file gdb-server.cc.
                                                                      {
  // Executed in the GDBServerThread.
  bool result = false;
  RunSyncTask([this, &result, wasm_module_id, offset]() {
    // Executed in the isolate thread.
    WasmModuleDebug* module_debug;
    if (GetModuleDebugHandler(wasm_module_id, &module_debug)) {
      int breakpoint_id = 0;
      if (module_debug->AddBreakpoint(offset, &breakpoint_id)) {
        breakpoints_[wasm_addr_t(wasm_module_id, offset)] = breakpoint_id;
        result = true;
      }
    }
  });
  return result;
}
References v8::internal::wasm::gdb_server::WasmModuleDebug::AddBreakpoint(), GetModuleDebugHandler(), v8::base::internal::result, and RunSyncTask().
Referenced by v8::internal::wasm::gdb_server::Target::ProcessPacket().
AddIsolate()
void v8::internal::wasm::gdb_server::GdbServer::AddIsolate (Isolate * isolate)
Definition at line 316 of file gdb-server.cc.
                                           {
  // Executed in the isolate thread.
  if (isolate_delegates_.find(isolate) == isolate_delegates_.end()) {
    isolate_delegates_[isolate] =
        std::make_unique<DebugDelegate>(isolate, this);
  }
}
AddWasmModule()
void v8::internal::wasm::gdb_server::GdbServer::AddWasmModule (uint32_t module_id, Local< debug::WasmScript > wasm_script) [private]
Definition at line 371 of file gdb-server.cc.
                                                                  {
  // Executed in the isolate thread.
  DCHECK_EQ(Script::Type::kWasm, Utils::OpenHandle(*wasm_script)->type());
  v8::Isolate* isolate = Isolate::Current();
  scripts_.insert(
      std::make_pair(module_id, WasmModuleDebug(isolate, wasm_script)));
  has_module_list_changed_ = true;
  if (v8_flags.wasm_pause_waiting_for_debugger && scripts_.size() == 1) {
    TRACE_GDB_REMOTE("Paused, waiting for a debugger to attach...\n");
    Suspend();
  }
}
References v8::internal::Isolate::Current(), DCHECK_EQ, v8::Utils::OpenHandle(), TRACE_GDB_REMOTE, and v8::internal::v8_flags.
Create()
std::unique_ptr< GdbServer > v8::internal::wasm::gdb_server::GdbServer::Create () [static]
Definition at line 121 of file gdb-server.cc.
                                           {
  DCHECK(v8_flags.wasm_gdb_remote);
  std::unique_ptr<GdbServer> gdb_server(new GdbServer());
  // Spawns the GDB-stub thread where all the communication with the debugger
  // happens.
  gdb_server->thread_ = std::make_unique<GdbServerThread>(gdb_server.get());
  if (!gdb_server->thread_->StartAndInitialize()) {
    TRACE_GDB_REMOTE(
        "Cannot initialize thread, GDB-remote debugging will be disabled.\n");
    return nullptr;
  }
  return gdb_server;
}
References v8::internal::DCHECK(), GdbServer(), TRACE_GDB_REMOTE, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmEngine::NewNativeModule().
GetLoadedModules()
std::vector< GdbServer::WasmModuleInfo > v8::internal::wasm::gdb_server::GdbServer::GetLoadedModules (bool clear_module_list_changed_flag = false)
Definition at line 152 of file gdb-server.cc.
                                         {
  // Executed in the GDBServerThread.
  std::vector<GdbServer::WasmModuleInfo> modules;
  RunSyncTask([this, &modules, clear_module_list_changed_flag]() {
    // Executed in the isolate thread.
    for (const auto& pair : scripts_) {
      uint32_t module_id = pair.first;
      const WasmModuleDebug& module_debug = pair.second;
      modules.push_back({module_id, module_debug.GetModuleName()});
    }
    if (clear_module_list_changed_flag) has_module_list_changed_ = false;
  });
  return modules;
}
References v8::internal::wasm::gdb_server::WasmModuleDebug::GetModuleName(), has_module_list_changed_, RunSyncTask(), and scripts_.
Referenced by v8::internal::wasm::gdb_server::Target::ProcessQueryPacket().
GetModuleDebugHandler()
bool v8::internal::wasm::gdb_server::GdbServer::GetModuleDebugHandler (uint32_t module_id, WasmModuleDebug ** wasm_module_debug) [private]
Definition at line 170 of file gdb-server.cc.
                                                                           {
  // Always executed in the isolate thread.
  ScriptsMap::iterator scriptIterator = scripts_.find(module_id);
  if (scriptIterator != scripts_.end()) {
    *wasm_module_debug = &scriptIterator->second;
    return true;
  }
  wasm_module_debug = nullptr;
  return false;
}
References scripts_.
Referenced by AddBreakpoint(), GetWasmData(), GetWasmMemory(), and GetWasmModuleBytes().
GetTarget()
Target & v8::internal::wasm::gdb_server::GdbServer::GetTarget () const [private]
Definition at line 386 of file gdb-server.cc.
{ return thread_->GetTarget(); }
Referenced by GetWasmData(), GetWasmGlobal(), GetWasmLocal(), GetWasmMemory(), and GetWasmStackValue().
GetWasmCallStack()
std::vector< wasm_addr_t > v8::internal::wasm::gdb_server::GdbServer::GetWasmCallStack () const
Definition at line 306 of file gdb-server.cc.
                                                         {
  // Executed in the GDBServerThread.
  std::vector<wasm_addr_t> result;
  RunSyncTask([this, &result]() {
    // Executed in the isolate thread.
    result = GetTarget().GetCallStack();
  });
  return result;
}
References v8::base::internal::result.
Referenced by v8::internal::wasm::gdb_server::Target::ProcessQueryPacket().
GetWasmData()
uint32_t v8::internal::wasm::gdb_server::GdbServer::GetWasmData (uint32_t module_id, uint32_t offset, uint8_t * buffer, uint32_t size)
Definition at line 239 of file gdb-server.cc.
                                                                {
  // Executed in the GDBServerThread.
  uint32_t bytes_read = 0;
  RunSyncTask([this, &bytes_read, module_id, offset, buffer, size]() {
    // Executed in the isolate thread.
    WasmModuleDebug* module_debug = nullptr;
    if (GetModuleDebugHandler(module_id, &module_debug)) {
      bytes_read = module_debug->GetWasmData(GetTarget().GetCurrentIsolate(),
                                             offset, buffer, size);
    }
  });
  return bytes_read;
}
References v8::internal::GetCurrentIsolate(), GetModuleDebugHandler(), GetTarget(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmData(), RunSyncTask(), and size().
Referenced by v8::internal::wasm::gdb_server::Target::ProcessQueryPacket().
GetWasmGlobal()
bool v8::internal::wasm::gdb_server::GdbServer::GetWasmGlobal (uint32_t frame_index, uint32_t index, uint8_t * buffer, uint32_t buffer_size, uint32_t * size)
Definition at line 182 of file gdb-server.cc.
                                              {
  // Executed in the GDBServerThread.
  bool result = false;
  RunSyncTask([this, &result, frame_index, index, buffer, buffer_size, size]() {
    // Executed in the isolate thread.
    result = WasmModuleDebug::GetWasmGlobal(GetTarget().GetCurrentIsolate(),
                                            frame_index, index, buffer,
                                            buffer_size, size);
  });
  return result;
}
References v8::internal::GetCurrentIsolate(), GetTarget(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmGlobal(), v8::internal::index, v8::base::internal::result, RunSyncTask(), and size().
Referenced by v8::internal::wasm::gdb_server::Target::ProcessQueryPacket().
GetWasmLocal()
bool v8::internal::wasm::gdb_server::GdbServer::GetWasmLocal (uint32_t frame_index, uint32_t index, uint8_t * buffer, uint32_t buffer_size, uint32_t * size)
Definition at line 196 of file gdb-server.cc.
                                             {
  // Executed in the GDBServerThread.
  bool result = false;
  RunSyncTask([this, &result, frame_index, index, buffer, buffer_size, size]() {
    // Executed in the isolate thread.
    result = WasmModuleDebug::GetWasmLocal(GetTarget().GetCurrentIsolate(),
                                           frame_index, index, buffer,
                                           buffer_size, size);
  });
  return result;
}
References v8::internal::GetCurrentIsolate(), GetTarget(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmLocal(), v8::internal::index, v8::base::internal::result, RunSyncTask(), and size().
Referenced by v8::internal::wasm::gdb_server::Target::ProcessQueryPacket().
GetWasmMemory()
uint32_t v8::internal::wasm::gdb_server::GdbServer::GetWasmMemory (uint32_t module_id, uint32_t offset, uint8_t * buffer, uint32_t size)
Definition at line 224 of file gdb-server.cc.
                                                                  {
  // Executed in the GDBServerThread.
  uint32_t bytes_read = 0;
  RunSyncTask([this, &bytes_read, module_id, offset, buffer, size]() {
    // Executed in the isolate thread.
    WasmModuleDebug* module_debug = nullptr;
    if (GetModuleDebugHandler(module_id, &module_debug)) {
      bytes_read = module_debug->GetWasmMemory(GetTarget().GetCurrentIsolate(),
                                               offset, buffer, size);
    }
  });
  return bytes_read;
}
References v8::internal::GetCurrentIsolate(), GetModuleDebugHandler(), GetTarget(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmMemory(), RunSyncTask(), and size().
Referenced by v8::internal::wasm::gdb_server::Target::ProcessQueryPacket().
GetWasmModuleBytes()
uint32_t v8::internal::wasm::gdb_server::GdbServer::GetWasmModuleBytes (wasm_addr_t address, uint8_t * buffer, uint32_t size)
Definition at line 254 of file gdb-server.cc.
                                                      {
  // Executed in the GDBServerThread.
  uint32_t bytes_read = 0;
  RunSyncTask([this, &bytes_read, wasm_addr, buffer, size]() {
    // Executed in the isolate thread.
    WasmModuleDebug* module_debug;
    if (GetModuleDebugHandler(wasm_addr.ModuleId(), &module_debug)) {
      bytes_read = module_debug->GetWasmModuleBytes(wasm_addr, buffer, size);
    }
  });
  return bytes_read;
}
References GetModuleDebugHandler(), v8::internal::wasm::gdb_server::wasm_addr_t::ModuleId(), RunSyncTask(), and size().
Referenced by v8::internal::wasm::gdb_server::Target::ProcessPacket().
GetWasmStackValue()
bool v8::internal::wasm::gdb_server::GdbServer::GetWasmStackValue (uint32_t frame_index, uint32_t index, uint8_t * buffer, uint32_t buffer_size, uint32_t * size)
Definition at line 210 of file gdb-server.cc.
                                                  {
  // Executed in the GDBServerThread.
  bool result = false;
  RunSyncTask([this, &result, frame_index, index, buffer, buffer_size, size]() {
    // Executed in the isolate thread.
    result = WasmModuleDebug::GetWasmStackValue(GetTarget().GetCurrentIsolate(),
                                                frame_index, index, buffer,
                                                buffer_size, size);
  });
  return result;
}
References v8::internal::GetCurrentIsolate(), GetTarget(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmStackValue(), v8::internal::index, v8::base::internal::result, RunSyncTask(), and size().
Referenced by v8::internal::wasm::gdb_server::Target::ProcessQueryPacket().
HasModuleListChanged()
bool v8::internal::wasm::gdb_server::GdbServer::HasModuleListChanged () const [inline]
Definition at line 50 of file gdb-server.h.
{ return has_module_list_changed_; }
References has_module_list_changed_.
Referenced by v8::internal::wasm::gdb_server::Target::SetStopReply().
operator=()
GdbServer& v8::internal::wasm::gdb_server::GdbServer::operator= (const GdbServer &) [delete]
PrepareStep()
void v8::internal::wasm::gdb_server::GdbServer::PrepareStep ()
Definition at line 359 of file gdb-server.cc.
                            {
  // Executed in the GDBServerThread.
  wasm_addr_t pc = GetTarget().GetCurrentPc();
  RunSyncTask([this, pc]() {
    // Executed in the isolate thread.
    WasmModuleDebug* module_debug;
    if (GetModuleDebugHandler(pc.ModuleId(), &module_debug)) {
      module_debug->PrepareStep();
    }
  });
}
References v8::internal::wasm::gdb_server::wasm_addr_t::ModuleId().
Referenced by v8::internal::wasm::gdb_server::Target::ProcessPacket().
QuitMessageLoopOnPause()
void v8::internal::wasm::gdb_server::GdbServer::QuitMessageLoopOnPause ()
Definition at line 150 of file gdb-server.cc.
{ task_runner_->Terminate(); }
References task_runner_.
Referenced by v8::internal::wasm::gdb_server::Target::ProcessCommands().
RemoveBreakpoint()
bool v8::internal::wasm::gdb_server::GdbServer::RemoveBreakpoint (uint32_t wasm_module_id, uint32_t offset)
Definition at line 285 of file gdb-server.cc.
                                                                         {
  // Executed in the GDBServerThread.
  bool result = false;
  RunSyncTask([this, &result, wasm_module_id, offset]() {
    // Executed in the isolate thread.
    BreakpointsMap::iterator it =
        breakpoints_.find(wasm_addr_t(wasm_module_id, offset));
    if (it != breakpoints_.end()) {
      int breakpoint_id = it->second;
      breakpoints_.erase(it);
      WasmModuleDebug* module_debug;
      if (GetModuleDebugHandler(wasm_module_id, &module_debug)) {
        module_debug->RemoveBreakpoint(offset, breakpoint_id);
        result = true;
      }
    }
  });
  return result;
}
References breakpoints_, v8::base::internal::result, and RunSyncTask().
Referenced by v8::internal::wasm::gdb_server::Target::ProcessPacket().
RemoveIsolate()
void v8::internal::wasm::gdb_server::GdbServer::RemoveIsolate (Isolate * isolate)
Definition at line 324 of file gdb-server.cc.
                                              {
  // Executed in the isolate thread.
  auto it = isolate_delegates_.find(isolate);
  if (it != isolate_delegates_.end()) {
    for (auto it = scripts_.begin(); it != scripts_.end();) {
      if (it->second.GetIsolate() == isolate) {
        it = scripts_.erase(it);
        has_module_list_changed_ = true;
      } else {
        ++it;
      }
    }
    isolate_delegates_.erase(it);
  }
}
RunMessageLoopOnPause()
void v8::internal::wasm::gdb_server::GdbServer::RunMessageLoopOnPause () [private]
Definition at line 148 of file gdb-server.cc.
{ task_runner_->Run(); }
References task_runner_.
RunSyncTask() [1/2]
template<typename Callback >
auto v8::internal::wasm::gdb_server::GdbServer::RunSyncTask (Callback && callback) const [private]
Referenced by AddBreakpoint(), GetLoadedModules(), GetWasmData(), GetWasmGlobal(), GetWasmLocal(), GetWasmMemory(), GetWasmModuleBytes(), GetWasmStackValue(), and RemoveBreakpoint().
RunSyncTask() [2/2]
template<typename Functor >
auto v8::internal::wasm::gdb_server::GdbServer::RunSyncTask (Functor && callback) const
Definition at line 113 of file gdb-server.cc.
                                                    {
  // Executed in the GDBServerThread.
  v8::base::Semaphore ready_semaphore(0);
  task_runner_->Append(&ready_semaphore, callback);
  ready_semaphore.Wait();
}
References task_runner_, and v8::base::Semaphore::Wait().
Suspend()
void v8::internal::wasm::gdb_server::GdbServer::Suspend ()
Definition at line 340 of file gdb-server.cc.
                        {
  // Executed in the GDBServerThread.
  auto it = isolate_delegates_.begin();
  if (it != isolate_delegates_.end()) {
    Isolate* isolate = it->first;
    v8::Isolate* v8Isolate = (v8::Isolate*)isolate;
    v8Isolate->RequestInterrupt(
        // Executed in the isolate thread.
        [](v8::Isolate* isolate, void*) {
          if (v8::debug::AllFramesOnStackAreBlackboxed(isolate)) {
            v8::debug::SetBreakOnNextFunctionCall(isolate);
          } else {
            v8::debug::BreakRightNow(isolate);
          }
        },
        this);
  }
}
References v8::debug::BreakRightNow(), v8::Isolate::RequestInterrupt(), and v8::debug::SetBreakOnNextFunctionCall().
Referenced by v8::internal::wasm::gdb_server::Target::Suspend().
Member Data Documentation
breakpoints_
BreakpointsMap v8::internal::wasm::gdb_server::GdbServer::breakpoints_ [private]
Definition at line 198 of file gdb-server.h.
Referenced by RemoveBreakpoint().
has_module_list_changed_
std::atomic<bool> v8::internal::wasm::gdb_server::GdbServer::has_module_list_changed_ [private]
Definition at line 191 of file gdb-server.h.
Referenced by GetLoadedModules(), and HasModuleListChanged().
isolate_delegates_
IsolateDebugDelegateMap v8::internal::wasm::gdb_server::GdbServer::isolate_delegates_ [private]
Definition at line 205 of file gdb-server.h.
Referenced by ~GdbServer().
scripts_
ScriptsMap v8::internal::wasm::gdb_server::GdbServer::scripts_ [private]
Definition at line 201 of file gdb-server.h.
Referenced by GetLoadedModules(), and GetModuleDebugHandler().
task_runner_
std::unique_ptr<TaskRunner> v8::internal::wasm::gdb_server::GdbServer::task_runner_ [private]
Definition at line 189 of file gdb-server.h.
Referenced by GdbServer(), QuitMessageLoopOnPause(), RunMessageLoopOnPause(), and RunSyncTask().
thread_
std::unique_ptr<GdbServerThread> v8::internal::wasm::gdb_server::GdbServer::thread_ [private]
Definition at line 185 of file gdb-server.h.
Referenced by ~GdbServer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/wasm/gdb-server/gdb-server.h
/mnt/V8SourceCode/src/debug/wasm/gdb-server/gdb-server.cc