v8::internal::compiler::TopLevelLiveRange Class Reference
#include <register-allocator.h>
Classes
struct SpillMoveInsertionList
Public Types
enum SlotUseKind { kNoSlotUse
, kDeferredSlotUse
, kGeneralSlotUse
 }
enum class SpillType { kNoSpillType
, kSpillOperand
, kSpillRange
, kDeferredSpillRange
 }
Public Member Functions
TopLevelLiveRange (int vreg, MachineRepresentation rep, Zone *zone)
TopLevelLiveRange (const TopLevelLiveRange &)=delete
TopLevelLiveRange & operator= (const TopLevelLiveRange &)=delete
int spill_start_index () const
bool IsFixed () const
bool IsDeferredFixed () const
void set_deferred_fixed ()
bool is_phi () const
void set_is_phi (bool value)
bool is_non_loop_phi () const
bool is_loop_phi () const
void set_is_non_loop_phi (bool value)
bool SpillAtLoopHeaderNotBeneficial () const
void set_spilling_at_loop_header_not_beneficial ()
bool has_slot_use () const
bool has_non_deferred_slot_use () const
void reset_slot_use ()
void register_slot_use (SlotUseKind value)
SlotUseKind slot_use_kind () const
void EnsureInterval (LifetimePosition start, LifetimePosition end, Zone *zone)
void AddUseInterval (LifetimePosition start, LifetimePosition end, Zone *zone)
void AddUsePosition (UsePosition *pos, Zone *zone)
void ShortenTo (LifetimePosition start)
void SetSpillRange (SpillRange *spill_range)
void set_spill_type (SpillType value)
SpillType spill_type () const
InstructionOperand * GetSpillOperand () const
SpillRange * GetAllocatedSpillRange () const
SpillRange * GetSpillRange () const
bool HasNoSpillType () const
bool HasSpillOperand () const
bool HasSpillRange () const
bool HasGeneralSpillRange () const
AllocatedOperand GetSpillRangeOperand () const
void RecordSpillLocation (Zone *zone, int gap_index, InstructionOperand *operand)
void SetSpillOperand (InstructionOperand *operand)
void SetSpillStartIndex (int start)
void FilterSpillMoves (RegisterAllocationData *data, const InstructionOperand &operand)
void CommitSpillMoves (RegisterAllocationData *data, const InstructionOperand &operand)
void TreatAsSpilledInDeferredBlock (Zone *zone)
void TransitionRangeToDeferredSpill (Zone *zone)
void TransitionRangeToSpillAtDefinition ()
bool MayRequireSpillRange () const
void UpdateSpillRangePostMerge (TopLevelLiveRange *merged)
int vreg () const
LiveRange * GetChildCovers (LifetimePosition pos)
const ZoneVector< LiveRange * > & Children () const
int GetNextChildId ()
bool IsSpilledOnlyInDeferredBlocks (const RegisterAllocationData *data) const
SpillMoveInsertionList * GetSpillMoveInsertionLocations (const RegisterAllocationData *data) const
void MarkHasPreassignedSlot ()
bool has_preassigned_slot () const
void SetLateSpillingSelected (bool late_spilling_selected)
bool LateSpillingSelected () const
void AddBlockRequiringSpillOperand (RpoNumber block_id, const RegisterAllocationData *data)
SparseBitVector * GetListOfBlocksRequiringSpillOperands (const RegisterAllocationData *data) const
LiveRangeBundle * get_bundle () const
void set_bundle (LiveRangeBundle *bundle)
Private Types
enum class SpillRangeMode : uint8_t { kNotSet
, kSpillAtDefinition
, kSpillLater
 }
using HasSlotUseField = base::BitField< SlotUseKind, 1, 2 >
using IsPhiField = base::BitField< bool, 3, 1 >
using IsNonLoopPhiField = base::BitField< bool, 4, 1 >
using SpillTypeField = base::BitField< SpillType, 5, 2 >
using DeferredFixedField = base::BitField< bool, 28, 1 >
using SpillAtLoopHeaderNotBeneficialField = base::BitField< bool, 29, 1 >
using SpillRangeModeField = base::BitField< SpillRangeMode, 30, 2 >
Private Attributes
int vreg_
int last_child_id_
xx xx xx xx xx xx xx xx xx
union {
 InstructionOperand * spill_operand_
 SpillRange * spill_range_
};
xx xx xx xx xx xx xx xx xx
union {
 SpillMoveInsertionList * spill_move_insertion_locations_
 SparseBitVector * list_of_blocks_requiring_spill_operands_
};
LiveRangeBundle * bundle_ = nullptr
UsePositionVector positions_
ZoneVector< LiveRange * > children_
bool spilled_in_deferred_blocks_
bool has_preassigned_slot_
int spill_start_index_
Friends
class LiveRange
Detailed Description
Definition at line 1016 of file register-allocator.h.
Member Typedef Documentation
DeferredFixedField
using v8::internal::compiler::TopLevelLiveRange::DeferredFixedField = base::BitField<bool, 28, 1> [private]
Definition at line 1251 of file register-allocator.h.
HasSlotUseField
using v8::internal::compiler::TopLevelLiveRange::HasSlotUseField = base::BitField<SlotUseKind, 1, 2> [private]
Definition at line 1247 of file register-allocator.h.
IsNonLoopPhiField
using v8::internal::compiler::TopLevelLiveRange::IsNonLoopPhiField = base::BitField<bool, 4, 1> [private]
Definition at line 1249 of file register-allocator.h.
IsPhiField
using v8::internal::compiler::TopLevelLiveRange::IsPhiField = base::BitField<bool, 3, 1> [private]
Definition at line 1248 of file register-allocator.h.
SpillAtLoopHeaderNotBeneficialField
using v8::internal::compiler::TopLevelLiveRange::SpillAtLoopHeaderNotBeneficialField = base::BitField<bool, 29, 1> [private]
Definition at line 1252 of file register-allocator.h.
SpillRangeModeField
using v8::internal::compiler::TopLevelLiveRange::SpillRangeModeField = base::BitField<SpillRangeMode, 30, 2> [private]
Definition at line 1253 of file register-allocator.h.
SpillTypeField
using v8::internal::compiler::TopLevelLiveRange::SpillTypeField = base::BitField<SpillType, 5, 2> [private]
Definition at line 1250 of file register-allocator.h.
Member Enumeration Documentation
SlotUseKind
enum v8::internal::compiler::TopLevelLiveRange::SlotUseKind
Enumerator
kNoSlotUse
kDeferredSlotUse
kGeneralSlotUse
Definition at line 1043 of file register-allocator.h.
{ kNoSlotUse, kDeferredSlotUse, kGeneralSlotUse };
SpillRangeMode
enum v8::internal::compiler::TopLevelLiveRange::SpillRangeMode : uint8_t [strong], [private]
Enumerator
kNotSet
kSpillAtDefinition
kSpillLater
Definition at line 1241 of file register-allocator.h.
                            : uint8_t {
    kNotSet,
    kSpillAtDefinition,
    kSpillLater,
  };
SpillType
enum v8::internal::compiler::TopLevelLiveRange::SpillType [strong]
Enumerator
kNoSpillType
kSpillOperand
kSpillRange
kDeferredSpillRange
Definition at line 1085 of file register-allocator.h.
                       {
    kNoSpillType,
    kSpillOperand,
    kSpillRange,
    kDeferredSpillRange
  };
Constructor & Destructor Documentation
TopLevelLiveRange() [1/2]
v8::internal::compiler::TopLevelLiveRange::TopLevelLiveRange (int vreg, MachineRepresentation rep, Zone * zone) [explicit]
Definition at line 688 of file register-allocator.cc.
    : LiveRange(0, rep, this),
      vreg_(vreg),
      last_child_id_(0),
      spill_operand_(nullptr),
      spill_move_insertion_locations_(nullptr),
      children_({this}, zone),
      spilled_in_deferred_blocks_(false),
      has_preassigned_slot_(false),
      spill_start_index_(kMaxInt) {
  bits_ |= SpillTypeField::encode(SpillType::kNoSpillType);
}
TopLevelLiveRange() [2/2]
v8::internal::compiler::TopLevelLiveRange::TopLevelLiveRange (const TopLevelLiveRange &) [delete]
Member Function Documentation
AddBlockRequiringSpillOperand()
void v8::internal::compiler::TopLevelLiveRange::AddBlockRequiringSpillOperand (RpoNumber block_id, const RegisterAllocationData * data) [inline]
Definition at line 1221 of file register-allocator.h.
                                                                         {
    DCHECK(IsSpilledOnlyInDeferredBlocks(data));
    GetListOfBlocksRequiringSpillOperands(data)->Add(block_id.ToInt());
  }
References v8::internal::DCHECK(), and v8::internal::compiler::RpoNumber::ToInt().
Referenced by v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks().
AddUseInterval()
void v8::internal::compiler::TopLevelLiveRange::AddUseInterval (LifetimePosition start, LifetimePosition end, Zone * zone)
Definition at line 860 of file register-allocator.cc.
                                                                         {
  TRACE("Add to live range %d interval [%d %d[\n", vreg(), start.value(),
        end.value());
  if (intervals_.empty()) {
    intervals_.push_front(zone, UseInterval(start, end));
    start_ = start;
    end_ = end;
  } else {
    UseInterval& first_interval = intervals_.front();
    if (end == first_interval.start()) {
      // Coalesce directly adjacent intervals.
      first_interval.set_start(start);
      start_ = start;
    } else if (end < first_interval.start()) {
      intervals_.push_front(zone, UseInterval(start, end));
      start_ = start;
    } else {
      // Order of instruction's processing (see ProcessInstructions) guarantees
      // that each new use interval either precedes, intersects with or touches
      // the last added interval.
      DCHECK(intervals_.size() == 1 || end <= intervals_.begin()[1].start());
      first_interval.set_start(std::min(start, first_interval.start()));
      first_interval.set_end(std::max(end, first_interval.end()));
      if (start_ > start) {
        start_ = start;
      }
      if (end_ < end) {
        end_ = end;
      }
    }
  }
  current_interval_ = intervals_.begin();
}
References v8::internal::compiler::DoubleEndedSplitVector< T >::begin(), v8::internal::compiler::LiveRange::current_interval_, v8::internal::DCHECK(), v8::internal::compiler::DoubleEndedSplitVector< T >::empty(), v8::internal::compiler::UseInterval::end(), v8::internal::compiler::end(), v8::internal::compiler::LiveRange::end_, v8::internal::compiler::DoubleEndedSplitVector< T >::front(), v8::internal::compiler::LiveRange::intervals_, v8::internal::compiler::DoubleEndedSplitVector< T >::push_front(), v8::internal::compiler::UseInterval::set_end(), v8::internal::compiler::UseInterval::set_start(), v8::internal::compiler::DoubleEndedSplitVector< T >::size(), v8::internal::compiler::UseInterval::start(), v8::internal::compiler::LiveRange::start_, v8::internal::TRACE(), v8::internal::compiler::LifetimePosition::value(), and vreg().
Referenced by v8::internal::compiler::LiveRangeBuilder::AddInitialIntervals(), v8::internal::compiler::LiveRangeBuilder::Define(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), and v8::internal::compiler::LiveRangeBuilder::Use().
AddUsePosition()
void v8::internal::compiler::TopLevelLiveRange::AddUsePosition (UsePosition * pos, Zone * zone)
Definition at line 895 of file register-allocator.cc.
                                                                       {
  TRACE("Add to live range %d use position %d\n", vreg(),
        use_pos->pos().value());
  // Since we `ProcessInstructions` in reverse, the `use_pos` is almost always
  // inserted at the front of `positions_`, hence (i) use linear instead of
  // binary search and (ii) grow towards the `kFront` exclusively on `insert`.
  UsePositionVector::iterator insert_it = std::find_if(
      positions_.begin(), positions_.end(), [=](const UsePosition* pos) {
        return UsePosition::Ordering()(use_pos, pos);
      });
  positions_.insert<kFront>(zone, insert_it, use_pos);
  positions_span_ = base::VectorOf(positions_);
  // We must not have child `LiveRange`s yet (e.g. from splitting), otherwise we
  // would have to adjust their `positions_span_` as well.
  DCHECK_NULL(next_);
}
References v8::internal::compiler::DoubleEndedSplitVector< T >::begin(), DCHECK_NULL, v8::internal::compiler::DoubleEndedSplitVector< T >::end(), v8::internal::compiler::DoubleEndedSplitVector< T >::insert(), v8::internal::compiler::kFront, v8::internal::compiler::LiveRange::next_, v8::internal::compiler::UsePosition::pos(), positions_, v8::internal::compiler::LiveRange::positions_span_, v8::internal::TRACE(), v8::internal::compiler::LifetimePosition::value(), v8::base::VectorOf(), and vreg().
Referenced by v8::internal::compiler::LiveRangeBuilder::Define(), and v8::internal::compiler::LiveRangeBuilder::Use().
Children()
const ZoneVector<LiveRange*>& v8::internal::compiler::TopLevelLiveRange::Children () const [inline]
Definition at line 1182 of file register-allocator.h.
{ return children_; }
CommitSpillMoves()
void v8::internal::compiler::TopLevelLiveRange::CommitSpillMoves (RegisterAllocationData * data, const InstructionOperand & operand)
Definition at line 709 of file register-allocator.cc.
                                                                       {
  DCHECK_IMPLIES(op.IsConstant(),
                 GetSpillMoveInsertionLocations(data) == nullptr);
  if (HasGeneralSpillRange()) {
    SetLateSpillingSelected(false);
  }
  InstructionSequence* sequence = data->code();
  Zone* zone = sequence->zone();
  for (SpillMoveInsertionList* to_spill = GetSpillMoveInsertionLocations(data);
       to_spill != nullptr; to_spill = to_spill->next) {
    Instruction* instr = sequence->InstructionAt(to_spill->gap_index);
    ParallelMove* move =
        instr->GetOrCreateParallelMove(Instruction::START, zone);
    move->AddMove(*to_spill->operand, op);
    instr->block()->mark_needs_frame();
  }
}
References v8::internal::compiler::ParallelMove::AddMove(), v8::internal::compiler::Instruction::block(), v8::internal::compiler::RegisterAllocationData::code(), DCHECK_IMPLIES, v8::internal::compiler::Instruction::GetOrCreateParallelMove(), GetSpillMoveInsertionLocations(), HasGeneralSpillRange(), v8::internal::compiler::InstructionSequence::InstructionAt(), v8::internal::compiler::InstructionBlock::mark_needs_frame(), v8::internal::compiler::TopLevelLiveRange::SpillMoveInsertionList::next, SetLateSpillingSelected(), v8::internal::compiler::Instruction::START, and v8::internal::compiler::InstructionSequence::zone().
Referenced by v8::internal::compiler::SpillPlacer::Add(), and v8::internal::compiler::SpillPlacer::SecondBackwardPass().
EnsureInterval()
void v8::internal::compiler::TopLevelLiveRange::EnsureInterval (LifetimePosition start, LifetimePosition end, Zone * zone)
Definition at line 836 of file register-allocator.cc.
                                                                         {
  TRACE("Ensure live range %d in interval [%d %d[\n", vreg(), start.value(),
        end.value());
  DCHECK(!IsEmpty());
  // Drop front intervals until intervals_.front().start() > end.
  LifetimePosition new_end = end;
  while (!intervals_.empty() && intervals_.front().start() <= end) {
    if (intervals_.front().end() > end) {
      new_end = intervals_.front().end();
    }
    intervals_.pop_front();
  }
  intervals_.push_front(zone, UseInterval(start, new_end));
  current_interval_ = intervals_.begin();
  if (end_ < new_end) {
    end_ = new_end;
  }
  if (start_ > start) {
    start_ = start;
  }
}
References v8::internal::compiler::DoubleEndedSplitVector< T >::begin(), v8::internal::compiler::LiveRange::current_interval_, v8::internal::DCHECK(), v8::internal::compiler::DoubleEndedSplitVector< T >::empty(), v8::internal::compiler::UseInterval::end(), v8::internal::compiler::end(), v8::internal::compiler::LiveRange::end_, v8::internal::compiler::DoubleEndedSplitVector< T >::front(), v8::internal::compiler::LiveRange::intervals_, v8::internal::compiler::LiveRange::IsEmpty(), v8::internal::compiler::DoubleEndedSplitVector< T >::pop_front(), v8::internal::compiler::DoubleEndedSplitVector< T >::push_front(), v8::internal::compiler::UseInterval::start(), v8::internal::compiler::LiveRange::start_, v8::internal::TRACE(), v8::internal::compiler::LifetimePosition::value(), and vreg().
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessLoopHeader().
FilterSpillMoves()
void v8::internal::compiler::TopLevelLiveRange::FilterSpillMoves (RegisterAllocationData * data, const InstructionOperand & operand)
Definition at line 731 of file register-allocator.cc.
                                                                       {
  DCHECK_IMPLIES(op.IsConstant(),
                 GetSpillMoveInsertionLocations(data) == nullptr);
  bool might_be_duplicated = has_slot_use() || spilled();
  InstructionSequence* sequence = data->code();
  SpillMoveInsertionList* previous = nullptr;
  for (SpillMoveInsertionList* to_spill = GetSpillMoveInsertionLocations(data);
       to_spill != nullptr; previous = to_spill, to_spill = to_spill->next) {
    Instruction* instr = sequence->InstructionAt(to_spill->gap_index);
    ParallelMove* move = instr->GetParallelMove(Instruction::START);
    // Skip insertion if it's possible that the move exists already as a
    // constraint move from a fixed output register to a slot.
    bool found = false;
    if (move != nullptr && (might_be_duplicated || has_preassigned_slot())) {
      for (MoveOperands* move_op : *move) {
        if (move_op->IsEliminated()) continue;
        if (move_op->source().Equals(*to_spill->operand) &&
            move_op->destination().Equals(op)) {
          found = true;
          if (has_preassigned_slot()) move_op->Eliminate();
          break;
        }
      }
    }
    if (found || has_preassigned_slot()) {
      // Remove the item from the list.
      if (previous == nullptr) {
        spill_move_insertion_locations_ = to_spill->next;
      } else {
        previous->next = to_spill->next;
      }
      // Even though this location doesn't need a spill instruction, the
      // block does require a frame.
      instr->block()->mark_needs_frame();
    }
  }
}
References v8::internal::compiler::Instruction::block(), v8::internal::compiler::RegisterAllocationData::code(), DCHECK_IMPLIES, v8::internal::compiler::ParallelMove::Eliminate(), v8::internal::compiler::Instruction::GetParallelMove(), GetSpillMoveInsertionLocations(), has_preassigned_slot(), has_slot_use(), v8::internal::compiler::InstructionSequence::InstructionAt(), v8::internal::compiler::InstructionBlock::mark_needs_frame(), v8::internal::compiler::TopLevelLiveRange::SpillMoveInsertionList::next, spill_move_insertion_locations_, v8::internal::compiler::LiveRange::spilled(), and v8::internal::compiler::Instruction::START.
Referenced by v8::internal::compiler::SpillPlacer::Add().
get_bundle()
LiveRangeBundle* v8::internal::compiler::TopLevelLiveRange::get_bundle () const [inline]
Definition at line 1233 of file register-allocator.h.
{ return bundle_; }
Referenced by v8::internal::compiler::BundleBuilder::BuildBundles(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), v8::internal::compiler::LiveRange::RegisterFromBundle(), v8::internal::compiler::LiveRangeBundle::TryAddRange(), v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi(), and v8::internal::compiler::LiveRange::UpdateBundleRegister().
GetAllocatedSpillRange()
SpillRange* v8::internal::compiler::TopLevelLiveRange::GetAllocatedSpillRange () const [inline]
Definition at line 1100 of file register-allocator.h.
                                             {
    DCHECK_NE(SpillType::kSpillOperand, spill_type());
    return spill_range_;
  }
References DCHECK_NE.
Referenced by v8::internal::compiler::RegisterAllocationData::AssignSpillRangeToLiveRange().
GetChildCovers()
LiveRange * v8::internal::compiler::TopLevelLiveRange::GetChildCovers (LifetimePosition pos)
Definition at line 790 of file register-allocator.cc.
                                                                 {
#ifdef DEBUG
  // Make sure the cache contains the correct, actual children.
  LiveRange* child = this;
  for (LiveRange* cached_child : children_) {
    DCHECK_EQ(cached_child, child);
    child = child->next();
  }
  DCHECK_NULL(child);
#endif
  auto child_it =
      std::lower_bound(children_.begin(), children_.end(), pos,
                       [](const LiveRange* range, LifetimePosition pos) {
                         return range->End() <= pos;
                       });
  return child_it == children_.end() || !(*child_it)->Covers(pos) ? nullptr
                                                                  : *child_it;
}
References children_, DCHECK_EQ, DCHECK_NULL, v8::internal::compiler::LiveRange::next(), and nullptr.
Referenced by v8::internal::compiler::LinearScanAllocator::ChooseOneOfTwoPredecessorStates(), v8::internal::compiler::SpillPlacer::CommitSpill(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::RegisterAllocator::FindOptimalSpillingPos(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), and v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
GetListOfBlocksRequiringSpillOperands()
SparseBitVector* v8::internal::compiler::TopLevelLiveRange::GetListOfBlocksRequiringSpillOperands (const RegisterAllocationData * data) const [inline]
Definition at line 1227 of file register-allocator.h.
                                                {
    DCHECK(IsSpilledOnlyInDeferredBlocks(data));
    return list_of_blocks_requiring_spill_operands_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), and v8::internal::compiler::LiveRangeConnector::ResolveControlFlow().
GetNextChildId()
int v8::internal::compiler::TopLevelLiveRange::GetNextChildId () [inline]
Definition at line 1184 of file register-allocator.h.
{ return ++last_child_id_; }
Referenced by v8::internal::compiler::LiveRange::SplitAt().
GetSpillMoveInsertionLocations()
SpillMoveInsertionList* v8::internal::compiler::TopLevelLiveRange::GetSpillMoveInsertionLocations (const RegisterAllocationData * data) const [inline]
Definition at line 1192 of file register-allocator.h.
                                                {
    DCHECK(!IsSpilledOnlyInDeferredBlocks(data));
    return spill_move_insertion_locations_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::SpillPlacer::Add(), CommitSpillMoves(), and FilterSpillMoves().
GetSpillOperand()
InstructionOperand* v8::internal::compiler::TopLevelLiveRange::GetSpillOperand () const [inline]
Definition at line 1095 of file register-allocator.h.
                                              {
    DCHECK_EQ(SpillType::kSpillOperand, spill_type());
    return spill_operand_;
  }
References DCHECK_EQ.
Referenced by v8::internal::compiler::LiveRange::GetAssignedOperand(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::operator<<(), and v8::internal::compiler::GraphC1Visualizer::PrintLiveRange().
GetSpillRange()
SpillRange* v8::internal::compiler::TopLevelLiveRange::GetSpillRange () const [inline]
Definition at line 1105 of file register-allocator.h.
                                    {
    DCHECK_GE(spill_type(), SpillType::kSpillRange);
    return spill_range_;
  }
References DCHECK_GE.
Referenced by v8::internal::compiler::LiveRangeBuilder::BuildLiveRanges(), GetSpillRangeOperand(), v8::internal::compiler::operator<<(), and v8::internal::compiler::SpillRange::TryMerge().
GetSpillRangeOperand()
AllocatedOperand v8::internal::compiler::TopLevelLiveRange::GetSpillRangeOperand () const
Definition at line 784 of file register-allocator.cc.
                                                               {
  SpillRange* spill_range = GetSpillRange();
  int index = spill_range->assigned_slot();
  return AllocatedOperand(LocationOperand::STACK_SLOT, representation(), index);
}
References v8::internal::compiler::SpillRange::assigned_slot(), GetSpillRange(), v8::internal::index, v8::internal::compiler::LiveRange::representation(), and v8::internal::compiler::LocationOperand::STACK_SLOT.
Referenced by v8::internal::compiler::SpillPlacer::Add(), v8::internal::compiler::SpillPlacer::CommitSpill(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::LiveRange::GetAssignedOperand(), and v8::internal::compiler::SpillPlacer::SecondBackwardPass().
has_non_deferred_slot_use()
bool v8::internal::compiler::TopLevelLiveRange::has_non_deferred_slot_use () const [inline]
Definition at line 1049 of file register-allocator.h.
                                         {
    return slot_use_kind() == SlotUseKind::kGeneralSlotUse;
  }
Referenced by v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand().
has_preassigned_slot()
bool v8::internal::compiler::TopLevelLiveRange::has_preassigned_slot () const [inline]
Definition at line 1199 of file register-allocator.h.
{ return has_preassigned_slot_; }
Referenced by FilterSpillMoves().
has_slot_use()
bool v8::internal::compiler::TopLevelLiveRange::has_slot_use () const [inline]
Definition at line 1045 of file register-allocator.h.
                            {
    return slot_use_kind() > SlotUseKind::kNoSlotUse;
  }
Referenced by FilterSpillMoves().
HasGeneralSpillRange()
bool v8::internal::compiler::TopLevelLiveRange::HasGeneralSpillRange () const [inline]
Definition at line 1116 of file register-allocator.h.
                                    {
    return spill_type() == SpillType::kSpillRange;
  }
Referenced by v8::internal::compiler::SpillPlacer::Add(), and CommitSpillMoves().
HasNoSpillType()
bool v8::internal::compiler::TopLevelLiveRange::HasNoSpillType () const [inline]
Definition at line 1109 of file register-allocator.h.
                              {
    return spill_type() == SpillType::kNoSpillType;
  }
Referenced by v8::internal::compiler::operator<<(), RecordSpillLocation(), SetSpillOperand(), v8::internal::compiler::RegisterAllocator::Spill(), and v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand().
HasSpillOperand()
bool v8::internal::compiler::TopLevelLiveRange::HasSpillOperand () const [inline]
Definition at line 1112 of file register-allocator.h.
                               {
    return spill_type() == SpillType::kSpillOperand;
  }
Referenced by v8::internal::compiler::RegisterAllocationData::AssignSpillRangeToLiveRange(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::operator<<(), SetSpillRange(), and v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
HasSpillRange()
bool v8::internal::compiler::TopLevelLiveRange::HasSpillRange () const [inline]
Definition at line 1115 of file register-allocator.h.
{ return spill_type() >= SpillType::kSpillRange; }
Referenced by v8::internal::compiler::LiveRangeBuilder::BuildLiveRanges(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand(), and v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
is_loop_phi()
bool v8::internal::compiler::TopLevelLiveRange::is_loop_phi () const [inline]
Definition at line 1032 of file register-allocator.h.
{ return is_phi() && !is_non_loop_phi(); }
Referenced by v8::internal::compiler::SpillPlacer::Add().
is_non_loop_phi()
bool v8::internal::compiler::TopLevelLiveRange::is_non_loop_phi () const [inline]
Definition at line 1031 of file register-allocator.h.
{ return IsNonLoopPhiField::decode(bits_); }
Referenced by v8::internal::compiler::operator<<(), and v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
is_phi()
bool v8::internal::compiler::TopLevelLiveRange::is_phi () const [inline]
Definition at line 1028 of file register-allocator.h.
{ return IsPhiField::decode(bits_); }
Referenced by v8::internal::compiler::operator<<(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::LinearScanAllocator::SetLiveRangeAssignedRegister(), and v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
IsDeferredFixed()
bool v8::internal::compiler::TopLevelLiveRange::IsDeferredFixed () const [inline]
Definition at line 1026 of file register-allocator.h.
{ return DeferredFixedField::decode(bits_); }
Referenced by v8::internal::compiler::operator<<().
IsFixed()
bool v8::internal::compiler::TopLevelLiveRange::IsFixed () const [inline]
Definition at line 1024 of file register-allocator.h.
{ return vreg_ < 0; }
Referenced by v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors(), v8::internal::compiler::operator<<(), v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges(), v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), v8::internal::compiler::RegisterAllocator::SplitBetween(), and v8::internal::compiler::RegisterAllocator::SplitRangeAt().
IsSpilledOnlyInDeferredBlocks()
bool v8::internal::compiler::TopLevelLiveRange::IsSpilledOnlyInDeferredBlocks (const RegisterAllocationData * data) const [inline]
Definition at line 1186 of file register-allocator.h.
                                                                               {
    return spill_type() == SpillType::kDeferredSpillRange;
  }
Referenced by v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), and v8::internal::compiler::LiveRangeConnector::ResolveControlFlow().
LateSpillingSelected()
bool v8::internal::compiler::TopLevelLiveRange::LateSpillingSelected () const [inline]
Definition at line 1214 of file register-allocator.h.
                                    {
    // Nobody should be reading this value until it's been decided.
    DCHECK_IMPLIES(HasGeneralSpillRange(), SpillRangeModeField::decode(bits_) !=
                                               SpillRangeMode::kNotSet);
    return SpillRangeModeField::decode(bits_) == SpillRangeMode::kSpillLater;
  }
References DCHECK_IMPLIES.
MarkHasPreassignedSlot()
void v8::internal::compiler::TopLevelLiveRange::MarkHasPreassignedSlot () [inline]
Definition at line 1198 of file register-allocator.h.
{ has_preassigned_slot_ = true; }
Referenced by v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter().
MayRequireSpillRange()
bool v8::internal::compiler::TopLevelLiveRange::MayRequireSpillRange () const [inline]
Definition at line 1167 of file register-allocator.h.
                                    {
    return !HasSpillOperand() && spill_range_ == nullptr;
  }
operator=()
TopLevelLiveRange& v8::internal::compiler::TopLevelLiveRange::operator= (const TopLevelLiveRange &) [delete]
RecordSpillLocation()
void v8::internal::compiler::TopLevelLiveRange::RecordSpillLocation (Zone * zone, int gap_index, InstructionOperand * operand)
Definition at line 702 of file register-allocator.cc.
                                                                         {
  DCHECK(HasNoSpillType());
  spill_move_insertion_locations_ = zone->New<SpillMoveInsertionList>(
      gap_index, operand, spill_move_insertion_locations_);
}
References v8::internal::DCHECK(), HasNoSpillType(), v8::internal::Zone::New(), and spill_move_insertion_locations_.
Referenced by v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), and v8::internal::compiler::ConstraintBuilder::ResolvePhis().
register_slot_use()
void v8::internal::compiler::TopLevelLiveRange::register_slot_use (SlotUseKind value) [inline]
Definition at line 1056 of file register-allocator.h.
                                            {
    bits_ = HasSlotUseField::update(bits_, std::max(slot_use_kind(), value));
  }
References v8::internal::value.
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
reset_slot_use()
void v8::internal::compiler::TopLevelLiveRange::reset_slot_use () [inline]
Definition at line 1053 of file register-allocator.h.
                        {
    bits_ = HasSlotUseField::update(bits_, SlotUseKind::kNoSlotUse);
  }
set_bundle()
void v8::internal::compiler::TopLevelLiveRange::set_bundle (LiveRangeBundle * bundle) [inline]
Definition at line 1234 of file register-allocator.h.
{ bundle_ = bundle; }
Referenced by v8::internal::compiler::LiveRangeBundle::AddRange().
set_deferred_fixed()
void v8::internal::compiler::TopLevelLiveRange::set_deferred_fixed () [inline]
Definition at line 1027 of file register-allocator.h.
{ bits_ = DeferredFixedField::update(bits_, true); }
set_is_non_loop_phi()
void v8::internal::compiler::TopLevelLiveRange::set_is_non_loop_phi (bool value) [inline]
Definition at line 1033 of file register-allocator.h.
                                       {
    bits_ = IsNonLoopPhiField::update(bits_, value);
  }
References v8::internal::value.
Referenced by v8::internal::compiler::ConstraintBuilder::ResolvePhis().
set_is_phi()
void v8::internal::compiler::TopLevelLiveRange::set_is_phi (bool value) [inline]
Definition at line 1029 of file register-allocator.h.
{ bits_ = IsPhiField::update(bits_, value); }
References v8::internal::value.
Referenced by v8::internal::compiler::ConstraintBuilder::ResolvePhis().
set_spill_type()
void v8::internal::compiler::TopLevelLiveRange::set_spill_type (SpillType value) [inline]
Definition at line 1091 of file register-allocator.h.
                                       {
    bits_ = SpillTypeField::update(bits_, value);
  }
References v8::internal::value.
Referenced by v8::internal::compiler::RegisterAllocationData::AssignSpillRangeToLiveRange(), SetSpillOperand(), and v8::internal::compiler::RegisterAllocator::Spill().
set_spilling_at_loop_header_not_beneficial()
void v8::internal::compiler::TopLevelLiveRange::set_spilling_at_loop_header_not_beneficial () [inline]
Definition at line 1039 of file register-allocator.h.
                                                    {
    bits_ = SpillAtLoopHeaderNotBeneficialField::update(bits_, true);
  }
Referenced by v8::internal::compiler::BundleBuilder::BuildBundles().
SetLateSpillingSelected()
void v8::internal::compiler::TopLevelLiveRange::SetLateSpillingSelected (bool late_spilling_selected) [inline]
Definition at line 1204 of file register-allocator.h.
                                                            {
    DCHECK(spill_type() == SpillType::kSpillRange);
    SpillRangeMode new_mode = late_spilling_selected
                                  ? SpillRangeMode::kSpillLater
                                  : SpillRangeMode::kSpillAtDefinition;
    // A single TopLevelLiveRange should never be used in both modes.
    DCHECK(SpillRangeModeField::decode(bits_) == SpillRangeMode::kNotSet ||
           SpillRangeModeField::decode(bits_) == new_mode);
    bits_ = SpillRangeModeField::update(bits_, new_mode);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::SpillPlacer::Add(), v8::internal::compiler::SpillPlacer::CommitSpill(), and CommitSpillMoves().
SetSpillOperand()
void v8::internal::compiler::TopLevelLiveRange::SetSpillOperand (InstructionOperand * operand)
Definition at line 771 of file register-allocator.cc.
                                                                   {
  DCHECK(HasNoSpillType());
  DCHECK(!operand->IsUnallocated() && !operand->IsImmediate());
  set_spill_type(SpillType::kSpillOperand);
  spill_operand_ = operand;
}
References v8::internal::DCHECK(), HasNoSpillType(), kSpillOperand, set_spill_type(), and spill_operand_.
Referenced by v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), and v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock().
SetSpillRange()
void v8::internal::compiler::TopLevelLiveRange::SetSpillRange (SpillRange * spill_range)
Definition at line 778 of file register-allocator.cc.
                                                             {
  DCHECK(!HasSpillOperand());
  DCHECK(spill_range);
  spill_range_ = spill_range;
}
References v8::internal::DCHECK(), HasSpillOperand(), and spill_range_.
Referenced by v8::internal::compiler::SpillRange::SpillRange(), and v8::internal::compiler::SpillRange::TryMerge().
SetSpillStartIndex()
void v8::internal::compiler::TopLevelLiveRange::SetSpillStartIndex (int start) [inline]
Definition at line 1124 of file register-allocator.h.
                                     {
    spill_start_index_ = std::min(start, spill_start_index_);
  }
Referenced by v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), and v8::internal::compiler::ConstraintBuilder::ResolvePhis().
ShortenTo()
void v8::internal::compiler::TopLevelLiveRange::ShortenTo (LifetimePosition start)
Definition at line 828 of file register-allocator.cc.
                                                        {
  TRACE("Shorten live range %d to [%d\n", vreg(), start.value());
  DCHECK(!IsEmpty());
  DCHECK_LE(intervals_.front().start(), start);
  intervals_.front().set_start(start);
  start_ = start;
}
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::compiler::DoubleEndedSplitVector< T >::front(), v8::internal::compiler::LiveRange::intervals_, v8::internal::compiler::LiveRange::IsEmpty(), v8::internal::compiler::UseInterval::set_start(), v8::internal::compiler::UseInterval::start(), v8::internal::compiler::LiveRange::start_, v8::internal::TRACE(), v8::internal::compiler::LifetimePosition::value(), and vreg().
Referenced by v8::internal::compiler::LiveRangeBuilder::Define().
slot_use_kind()
SlotUseKind v8::internal::compiler::TopLevelLiveRange::slot_use_kind () const [inline]
Definition at line 1059 of file register-allocator.h.
{ return HasSlotUseField::decode(bits_); }
spill_start_index()
int v8::internal::compiler::TopLevelLiveRange::spill_start_index () const [inline]
Definition at line 1022 of file register-allocator.h.
{ return spill_start_index_; }
spill_type()
SpillType v8::internal::compiler::TopLevelLiveRange::spill_type () const [inline]
Definition at line 1094 of file register-allocator.h.
{ return SpillTypeField::decode(bits_); }
Referenced by v8::internal::compiler::RegisterAllocationData::AssignSpillRangeToLiveRange(), v8::internal::compiler::LinearScanAllocator::PrintRangeRow(), and v8::internal::compiler::RegisterAllocator::Spill().
SpillAtLoopHeaderNotBeneficial()
bool v8::internal::compiler::TopLevelLiveRange::SpillAtLoopHeaderNotBeneficial () const [inline]
Definition at line 1036 of file register-allocator.h.
                                              {
    return SpillAtLoopHeaderNotBeneficialField::decode(bits_);
  }
Referenced by v8::internal::compiler::RegisterAllocator::FindOptimalSpillingPos().
TransitionRangeToDeferredSpill()
void v8::internal::compiler::TopLevelLiveRange::TransitionRangeToDeferredSpill (Zone * zone) [inline]
Definition at line 1152 of file register-allocator.h.
                                                  {
    spill_start_index_ = -1;
    spill_move_insertion_locations_ = nullptr;
    list_of_blocks_requiring_spill_operands_ = zone->New<SparseBitVector>(zone);
  }
References v8::internal::Zone::New().
TransitionRangeToSpillAtDefinition()
void v8::internal::compiler::TopLevelLiveRange::TransitionRangeToSpillAtDefinition () [inline]
Definition at line 1160 of file register-allocator.h.
                                            {
    DCHECK_NOT_NULL(spill_move_insertion_locations_);
    if (spill_type() == SpillType::kDeferredSpillRange) {
      set_spill_type(SpillType::kSpillRange);
    }
  }
References DCHECK_NOT_NULL.
TreatAsSpilledInDeferredBlock()
void v8::internal::compiler::TopLevelLiveRange::TreatAsSpilledInDeferredBlock (Zone * zone) [inline]
Definition at line 1143 of file register-allocator.h.
                                                 {
    spill_start_index_ = -1;
    spilled_in_deferred_blocks_ = true;
    spill_move_insertion_locations_ = nullptr;
    list_of_blocks_requiring_spill_operands_ = zone->New<SparseBitVector>(zone);
  }
References v8::internal::Zone::New().
UpdateSpillRangePostMerge()
void v8::internal::compiler::TopLevelLiveRange::UpdateSpillRangePostMerge (TopLevelLiveRange * merged)
vreg()
int v8::internal::compiler::TopLevelLiveRange::vreg () const [inline]
Definition at line 1171 of file register-allocator.h.
{ return vreg_; }
Referenced by v8::internal::compiler::SpillPlacer::Add(), v8::internal::compiler::LinearScanAllocator::AddToActive(), v8::internal::compiler::LinearScanAllocator::AddToInactive(), v8::internal::compiler::LinearScanAllocator::AddToUnhandled(), AddUseInterval(), AddUsePosition(), v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::AssignRegisterOnReload(), v8::internal::compiler::BundleBuilder::BuildBundles(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors(), EnsureInterval(), v8::internal::compiler::RegisterAllocationData::GetPhiMapValueFor(), v8::internal::compiler::LinearScanAllocator::InactiveToActive(), v8::internal::compiler::LinearScanAllocator::InactiveToHandled(), v8::internal::compiler::LinearScanAllocator::MaybeUndoPreviousSplit(), v8::internal::compiler::operator<<(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRangeChain(), v8::internal::compiler::LinearScanAllocator::PrintRangeRow(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), ShortenTo(), v8::internal::compiler::LiveRange::ShouldBeAllocatedBefore(), v8::internal::compiler::RegisterAllocator::Spill(), v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil(), v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges(), v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand(), v8::internal::compiler::RegisterAllocator::SplitBetween(), v8::internal::compiler::RegisterAllocator::SplitRangeAt(), v8::internal::compiler::LinearScanAllocator::TryAllocateFreeReg(), and v8::internal::compiler::LinearScanAllocator::TryAllocatePreferredReg().
Friends And Related Function Documentation
LiveRange
friend class LiveRange [friend]
Definition at line 1237 of file register-allocator.h.
Member Data Documentation
union { ... } [private]
union { ... } [private]
bundle_
LiveRangeBundle* v8::internal::compiler::TopLevelLiveRange::bundle_ = nullptr [private]
Definition at line 1268 of file register-allocator.h.
children_
ZoneVector<LiveRange*> v8::internal::compiler::TopLevelLiveRange::children_ [private]
Definition at line 1274 of file register-allocator.h.
Referenced by v8::internal::compiler::LiveRange::AttachToNext(), GetChildCovers(), and v8::internal::compiler::LiveRange::SplitAt().
has_preassigned_slot_
bool v8::internal::compiler::TopLevelLiveRange::has_preassigned_slot_ [private]
Definition at line 1279 of file register-allocator.h.
last_child_id_
int v8::internal::compiler::TopLevelLiveRange::last_child_id_ [private]
Definition at line 1256 of file register-allocator.h.
list_of_blocks_requiring_spill_operands_
SparseBitVector* v8::internal::compiler::TopLevelLiveRange::list_of_blocks_requiring_spill_operands_
Definition at line 1265 of file register-allocator.h.
positions_
UsePositionVector v8::internal::compiler::TopLevelLiveRange::positions_ [private]
Definition at line 1270 of file register-allocator.h.
Referenced by AddUsePosition().
spill_move_insertion_locations_
SpillMoveInsertionList* v8::internal::compiler::TopLevelLiveRange::spill_move_insertion_locations_
Definition at line 1264 of file register-allocator.h.
Referenced by FilterSpillMoves(), and RecordSpillLocation().
spill_operand_
InstructionOperand* v8::internal::compiler::TopLevelLiveRange::spill_operand_
Definition at line 1259 of file register-allocator.h.
Referenced by SetSpillOperand().
spill_range_
SpillRange* v8::internal::compiler::TopLevelLiveRange::spill_range_
Definition at line 1260 of file register-allocator.h.
Referenced by SetSpillRange().
spill_start_index_
int v8::internal::compiler::TopLevelLiveRange::spill_start_index_ [private]
Definition at line 1281 of file register-allocator.h.
spilled_in_deferred_blocks_
bool v8::internal::compiler::TopLevelLiveRange::spilled_in_deferred_blocks_ [private]
Definition at line 1278 of file register-allocator.h.
vreg_
int v8::internal::compiler::TopLevelLiveRange::vreg_ [private]
Definition at line 1255 of file register-allocator.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc