v8::internal::wasm::InliningTree Class Reference
#include <inlining-tree.h>
Classes
struct Data
Public Types
using CasesPerCallSite = base::Vector< InliningTree * >
Public Member Functions
int64_t score () const
base::Vector< CasesPerCallSite > function_calls ()
base::Vector< bool > has_non_inlineable_targets ()
bool feedback_found ()
bool is_inlined ()
uint32_t function_index ()
Static Public Member Functions
static InliningTree * CreateRoot (Zone *zone, const WasmModule *module, uint32_t function_index)
static int NoLiftoffBudget (const WasmModule *module, uint32_t func_index)
Static Public Attributes
static constexpr int kMaxInlinedCount = 60
static constexpr uint32_t kMaxInliningNestingDepth = 7
Private Member Functions
InliningTree (Data *shared, uint32_t function_index, int call_count, int wire_byte_size, uint32_t caller_index, int feedback_slot, int the_case, uint32_t depth)
void FullyExpand ()
void Inline ()
bool SmallEnoughToInline (size_t initial_wire_byte_size, size_t inlined_wire_byte_count)
Static Private Member Functions
static double BudgetScaleFactor (const WasmModule *module)
Private Attributes
Data * data_
uint32_t function_index_
int call_count_
int wire_byte_size_
bool is_inlined_ = false
bool feedback_found_ = false
base::Vector< CasesPerCallSite > function_calls_ {}
base::Vector< bool > has_non_inlineable_targets_ {}
uint32_t depth_
uint32_t caller_index_
int feedback_slot_
int case_
Friends
class v8::internal::Zone
Detailed Description
Definition at line 35 of file inlining-tree.h.
Member Typedef Documentation
CasesPerCallSite
using v8::internal::wasm::InliningTree::CasesPerCallSite = base::Vector<InliningTree*>
Definition at line 40 of file inlining-tree.h.
Constructor & Destructor Documentation
InliningTree()
v8::internal::wasm::InliningTree::InliningTree (Data * shared, uint32_t function_index, int call_count, int wire_byte_size, uint32_t caller_index, int feedback_slot, int the_case, uint32_t depth) [inline], [private]
Definition at line 167 of file inlining-tree.h.
      : data_(shared),
        function_index_(function_index),
        call_count_(call_count),
        wire_byte_size_(wire_byte_size),
        depth_(depth),
        caller_index_(caller_index),
        feedback_slot_(feedback_slot),
        case_(the_case) {}
Member Function Documentation
BudgetScaleFactor()
static double v8::internal::wasm::InliningTree::BudgetScaleFactor (const WasmModule * module) [inline], [static], [private]
Definition at line 107 of file inlining-tree.h.
                                                            {
    // If there are few small functions, that indicates that the toolchain
    // already performed significant inlining, so we reduce the budget
    // significantly as further inlining has diminishing benefits.
    // For both major knobs, we apply a smoothened step function based on
    // the module's percentage of small functions (sfp):
    // sfp <= 25%: use "low" budget
    // sfp >= 50%: use "high" budget
    // 25% < sfp < 50%: interpolate linearly between both budgets.
    double small_function_percentage =
        module->num_small_functions * 100.0 / module->num_declared_functions;
    if (small_function_percentage <= 25) {
      return 0;
    } else if (small_function_percentage >= 50) {
      return 1;
    } else {
      return (small_function_percentage - 25) / 25;
    }
  }
References v8::internal::wasm::WasmModule::num_declared_functions, and v8::internal::wasm::WasmModule::num_small_functions.
Referenced by v8::internal::wasm::InliningTree::Data::Data(), and NoLiftoffBudget().
CreateRoot()
static InliningTree* v8::internal::wasm::InliningTree::CreateRoot (Zone * zone, const WasmModule * module, uint32_t function_index) [inline], [static]
Definition at line 42 of file inlining-tree.h.
                                                           {
    InliningTree* tree = zone->New<InliningTree>(
        zone->New<Data>(zone, module, function_index), function_index,
        0, // Call count.
        0, // Wire byte size. `0` causes the root node to always get
                     // expanded, regardless of budget.
        -1, -1, -1, // Caller, feedback slot, case.
        0 // Inlining depth.
    );
    tree->FullyExpand();
    return tree;
  }
References FullyExpand(), function_index(), and v8::internal::Zone::New().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction().
feedback_found()
bool v8::internal::wasm::InliningTree::feedback_found () [inline]
Definition at line 100 of file inlining-tree.h.
{ return feedback_found_; }
References feedback_found_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::FinishFunction(), FullyExpand(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::should_inline(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction().
FullyExpand()
void v8::internal::wasm::InliningTree::FullyExpand () [private]
Definition at line 251 of file inlining-tree.h.
                               {
  DCHECK_EQ(this->function_index_, data_->topmost_caller_index);
  size_t initial_wire_byte_size =
      data_->module->functions[function_index_].code.length();
  size_t inlined_wire_byte_count = 0;
  std::priority_queue<InliningTree*, std::vector<InliningTree*>,
                      TreeNodeOrdering>
      queue;
  queue.push(this);
  int inlined_count = 0;
  base::MutexGuard mutex_guard(&data_->module->type_feedback.mutex);
  while (!queue.empty() && inlined_count < kMaxInlinedCount) {
    InliningTree* top = queue.top();
    if (v8_flags.trace_wasm_inlining) {
      if (top != this) {
        PrintF(
            "[function %d: in function %d, considering call #%d, case #%d, to "
            "function %d (count=%d, size=%d, score=%" PRId64 ")... ",
            data_->topmost_caller_index, top->caller_index_,
            top->feedback_slot_, static_cast<int>(top->case_),
            static_cast<int>(top->function_index_), top->call_count_,
            top->wire_byte_size_, static_cast<int64_t>(top->score()));
      } else {
        PrintF("[function %d: expanding topmost caller... ",
               data_->topmost_caller_index);
      }
    }
    queue.pop();
    if (top->function_index_ < data_->module->num_imported_functions) {
      if (v8_flags.trace_wasm_inlining && top != this) {
        PrintF("imported function]\n");
      }
      continue;
    }
    if (is_asmjs_module(data_->module)) {
      if (v8_flags.trace_wasm_inlining) {
        PrintF("cannot inline asm.js function]\n");
      }
      continue;
    }
    // Key idea: inlining hot calls is good, inlining big functions is bad,
    // so inline when a candidate is "hotter than it is big". Exception:
    // tiny candidates can get inlined regardless of their call count.
    if (top != this && top->wire_byte_size_ >= 12 &&
        !v8_flags.wasm_inlining_ignore_call_counts) {
      if (top->call_count_ < top->wire_byte_size_ / 2) {
        if (v8_flags.trace_wasm_inlining) {
          PrintF("not called often enough]\n");
        }
        continue;
      }
    }
    if (!top->SmallEnoughToInline(initial_wire_byte_size,
                                  inlined_wire_byte_count)) {
      if (v8_flags.trace_wasm_inlining && top != this) {
        PrintF("not enough inlining budget]\n");
      }
      continue;
    }
    if (v8_flags.trace_wasm_inlining && top != this) {
      PrintF("decided to inline! ");
    }
    top->Inline();
    inlined_count++;
    // For tiny functions, inlining may actually decrease generated code size
    // because we have one less call and don't need to push arguments, etc.
    // Subtract a little bit from the code size increase, such that inlining
    // these tiny functions doesn't use up any of the budget.
    constexpr int kOneLessCall = 6; // Guesstimated savings per call.
    inlined_wire_byte_count += std::max(top->wire_byte_size_ - kOneLessCall, 0);
    if (!top->feedback_found()) {
      if (v8_flags.trace_wasm_inlining) {
        PrintF("no feedback yet or no callees]\n");
      }
    } else if (top->depth_ < kMaxInliningNestingDepth) {
      if (v8_flags.trace_wasm_inlining) {
        PrintF("queueing %zu callee(s)]\n", top->function_calls_.size());
      }
      for (CasesPerCallSite cases : top->function_calls_) {
        for (InliningTree* call : cases) {
          if (call != nullptr) {
            queue.push(call);
          }
        }
      }
    } else if (v8_flags.trace_wasm_inlining) {
      PrintF("max inlining depth reached]\n");
    }
  }
  if (v8_flags.trace_wasm_inlining && !queue.empty()) {
    PrintF("[function %d: too many inlining candidates, stopping...]\n",
           data_->topmost_caller_index);
  }
}
References call_count_, caller_index_, case_, data_, DCHECK_EQ, depth_, feedback_found(), feedback_slot_, function_calls_, function_index_, v8::internal::wasm::WasmModule::functions, Inline(), v8::internal::wasm::is_asmjs_module(), kMaxInlinedCount, kMaxInliningNestingDepth, v8::internal::wasm::InliningTree::Data::module, v8::internal::wasm::TypeFeedbackStorage::mutex, v8::internal::wasm::WasmModule::num_imported_functions, v8::internal::PrintF(), score(), SmallEnoughToInline(), v8::internal::wasm::InliningTree::Data::topmost_caller_index, v8::internal::wasm::WasmModule::type_feedback, v8::internal::v8_flags, and wire_byte_size_.
Referenced by CreateRoot().
function_calls()
base::Vector<CasesPerCallSite> v8::internal::wasm::InliningTree::function_calls () [inline]
Definition at line 96 of file inlining-tree.h.
{ return function_calls_; }
References function_calls_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::wasm::TurboshaftGraphBuildingInterface::FinishFunction(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallRef(), v8::internal::wasm::TurboshaftGraphBuildingInterface::should_inline(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction().
function_index()
uint32_t v8::internal::wasm::InliningTree::function_index () [inline]
Definition at line 102 of file inlining-tree.h.
{ return function_index_; }
References function_index_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), CreateRoot(), v8::internal::wasm::TreeNodeOrdering::operator()(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallRef(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction().
has_non_inlineable_targets()
base::Vector<bool> v8::internal::wasm::InliningTree::has_non_inlineable_targets () [inline]
Definition at line 97 of file inlining-tree.h.
                                                {
    return has_non_inlineable_targets_;
  }
References has_non_inlineable_targets_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect().
Inline()
void v8::internal::wasm::InliningTree::Inline () [private]
Definition at line 209 of file inlining-tree.h.
                          {
  is_inlined_ = true;
  auto& feedback_map = data_->module->type_feedback.feedback_for_function;
  auto feedback_it = feedback_map.find(function_index_);
  if (feedback_it == feedback_map.end()) return;
  const FunctionTypeFeedback& feedback = feedback_it->second;
  base::Vector<CallSiteFeedback> type_feedback =
      feedback.feedback_vector.as_vector();
  if (type_feedback.empty()) return; // No feedback yet.
  DCHECK_EQ(type_feedback.size(), feedback.call_targets.size());
  feedback_found_ = true;
  function_calls_ =
      data_->zone->AllocateVector<CasesPerCallSite>(type_feedback.size());
  has_non_inlineable_targets_ =
      data_->zone->AllocateVector<bool>(type_feedback.size());
  for (size_t i = 0; i < type_feedback.size(); i++) {
    function_calls_[i] = data_->zone->AllocateVector<InliningTree*>(
        type_feedback[i].num_cases());
    has_non_inlineable_targets_[i] =
        type_feedback[i].has_non_inlineable_targets();
    for (int the_case = 0; the_case < type_feedback[i].num_cases();
         the_case++) {
      uint32_t callee_index = type_feedback[i].function_index(the_case);
      // TODO(jkummerow): Experiment with propagating relative call counts
      // into the nested InliningTree, and weighting scores there accordingly.
      function_calls_[i][the_case] = data_->zone->New<InliningTree>(
          data_, callee_index, type_feedback[i].call_count(the_case),
          data_->module->functions[callee_index].code.length(), function_index_,
          static_cast<int>(i), the_case, depth_ + 1);
    }
  }
}
References v8::internal::Zone::AllocateVector(), v8::internal::wasm::FunctionTypeFeedback::call_targets, data_, DCHECK_EQ, depth_, v8::base::Vector< T >::empty(), v8::internal::wasm::TypeFeedbackStorage::feedback_for_function, feedback_found_, v8::internal::wasm::FunctionTypeFeedback::feedback_vector, function_calls_, function_index_, v8::internal::wasm::WasmModule::functions, has_non_inlineable_targets_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, is_inlined_, v8::internal::wasm::InliningTree::Data::module, v8::internal::Zone::New(), v8::base::Vector< T >::size(), v8::base::OwnedVector< T >::size(), v8::internal::wasm::WasmModule::type_feedback, and v8::internal::wasm::InliningTree::Data::zone.
Referenced by FullyExpand().
is_inlined()
bool v8::internal::wasm::InliningTree::is_inlined () [inline]
Definition at line 101 of file inlining-tree.h.
{ return is_inlined_; }
References is_inlined_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallRef(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction().
NoLiftoffBudget()
static int v8::internal::wasm::InliningTree::NoLiftoffBudget (const WasmModule * module, uint32_t func_index) [inline], [static]
Definition at line 59 of file inlining-tree.h.
                                                                            {
    size_t wirebytes = module->functions[func_index].code.length();
    double scaled = BudgetScaleFactor(module);
    // TODO(jkummerow): When TF is gone, remove this adjustment by folding
    // it into the flag's default value.
    constexpr int kTurboshaftAdjustment = 2;
    int high_growth =
        static_cast<int>(v8_flags.wasm_inlining_factor) + kTurboshaftAdjustment;
    constexpr int kLowestUsefulValue = 2;
    int low_growth = std::max(kLowestUsefulValue, high_growth - 3);
    double max_growth_factor = low_growth * (1 - scaled) + high_growth * scaled;
    return std::max(static_cast<int>(v8_flags.wasm_inlining_min_budget),
                    static_cast<int>(max_growth_factor * wirebytes));
  }
References BudgetScaleFactor(), v8::internal::wasm::WasmModule::functions, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction().
score()
int64_t v8::internal::wasm::InliningTree::score () const [inline]
Definition at line 74 of file inlining-tree.h.
                        {
    // Note that the zero-point is arbitrary. Functions with negative score
    // can still get inlined.
    constexpr int count_factor = 2;
    constexpr int size_factor = 3;
    return int64_t{call_count_} * count_factor -
           int64_t{wire_byte_size_} * size_factor;
  }
References call_count_, and wire_byte_size_.
Referenced by FullyExpand(), and v8::internal::wasm::TreeNodeOrdering::operator()().
SmallEnoughToInline()
bool v8::internal::wasm::InliningTree::SmallEnoughToInline (size_t initial_wire_byte_size, size_t inlined_wire_byte_count) [private]
Definition at line 351 of file inlining-tree.h.
                                                                       {
  if (wire_byte_size_ > static_cast<int>(v8_flags.wasm_inlining_max_size)) {
    return false;
  }
  // For tiny functions, let's be a bit more generous.
  // TODO(dlehmann): Since we don't use up budget (i.e., increase
  // `inlined_wire_byte_count` see above) for very tiny functions, we might be
  // able to remove/simplify this code in the future.
  if (wire_byte_size_ < 12) {
    if (inlined_wire_byte_count > 100) {
      inlined_wire_byte_count -= 100;
    } else {
      inlined_wire_byte_count = 0;
    }
  }
  // For small-ish functions, the inlining budget is defined by the larger of
  // 1) the wasm_inlining_min_budget and
  // 2) the max_growth_factor * initial_wire_byte_size.
  // Inlining a little bit should always be fine even for tiny functions (1),
  // otherwise (2) makes sure that the budget scales in relation with the
  // original function size, to limit the compile time increase caused by
  // inlining.
  size_t budget_small_function =
      std::max<size_t>(v8_flags.wasm_inlining_min_budget,
                       data_->max_growth_factor * initial_wire_byte_size);
  // For large functions, growing by the same factor would add too much
  // compilation effort, so we also apply a fixed cap. However, independent
  // of the budget cap, for large functions we should still allow a little
  // inlining, which is why we allow 10% of the graph size is the minimal
  // budget even for large functions that exceed the regular budget.
  //
  // Note for future tuning: it might make sense to allow 20% here, and in
  // turn perhaps lower --wasm-inlining-budget. The drawback is that this
  // would allow truly huge functions to grow even bigger; the benefit is
  // that we wouldn't fall off as steep a cliff when hitting the cap.
  size_t budget_large_function =
      std::max<size_t>(data_->budget_cap, initial_wire_byte_size * 1.1);
  size_t total_size = initial_wire_byte_size + inlined_wire_byte_count +
                      static_cast<size_t>(wire_byte_size_);
  if (v8_flags.trace_wasm_inlining) {
    PrintF("budget=min(%zu, %zu), size %zu->%zu ", budget_small_function,
           budget_large_function,
           (initial_wire_byte_size + inlined_wire_byte_count), total_size);
  }
  return total_size <
         std::min<size_t>(budget_small_function, budget_large_function);
}
References v8::internal::wasm::InliningTree::Data::budget_cap, data_, v8::internal::wasm::InliningTree::Data::max_growth_factor, v8::internal::PrintF(), v8::internal::v8_flags, and wire_byte_size_.
Referenced by FullyExpand().
Friends And Related Function Documentation
v8::internal::Zone
friend class v8::internal::Zone [friend]
Definition at line 105 of file inlining-tree.h.
Member Data Documentation
call_count_
int v8::internal::wasm::InliningTree::call_count_ [private]
Definition at line 193 of file inlining-tree.h.
Referenced by FullyExpand(), and score().
caller_index_
uint32_t v8::internal::wasm::InliningTree::caller_index_ [private]
Definition at line 204 of file inlining-tree.h.
Referenced by FullyExpand().
case_
int v8::internal::wasm::InliningTree::case_ [private]
Definition at line 206 of file inlining-tree.h.
Referenced by FullyExpand().
data_
Data* v8::internal::wasm::InliningTree::data_ [private]
Definition at line 191 of file inlining-tree.h.
Referenced by FullyExpand(), Inline(), and SmallEnoughToInline().
depth_
uint32_t v8::internal::wasm::InliningTree::depth_ [private]
Definition at line 201 of file inlining-tree.h.
Referenced by FullyExpand(), and Inline().
feedback_found_
bool v8::internal::wasm::InliningTree::feedback_found_ = false [private]
Definition at line 196 of file inlining-tree.h.
Referenced by feedback_found(), and Inline().
feedback_slot_
int v8::internal::wasm::InliningTree::feedback_slot_ [private]
Definition at line 205 of file inlining-tree.h.
Referenced by FullyExpand().
function_calls_
base::Vector<CasesPerCallSite> v8::internal::wasm::InliningTree::function_calls_ {} [private]
Definition at line 198 of file inlining-tree.h.
Referenced by FullyExpand(), function_calls(), and Inline().
function_index_
uint32_t v8::internal::wasm::InliningTree::function_index_ [private]
Definition at line 192 of file inlining-tree.h.
Referenced by FullyExpand(), function_index(), and Inline().
has_non_inlineable_targets_
base::Vector<bool> v8::internal::wasm::InliningTree::has_non_inlineable_targets_ {} [private]
Definition at line 199 of file inlining-tree.h.
Referenced by has_non_inlineable_targets(), and Inline().
is_inlined_
bool v8::internal::wasm::InliningTree::is_inlined_ = false [private]
Definition at line 195 of file inlining-tree.h.
Referenced by Inline(), and is_inlined().
kMaxInlinedCount
constexpr int v8::internal::wasm::InliningTree::kMaxInlinedCount = 60 [static], [constexpr]
Definition at line 87 of file inlining-tree.h.
Referenced by FullyExpand(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::should_inline().
kMaxInliningNestingDepth
constexpr uint32_t v8::internal::wasm::InliningTree::kMaxInliningNestingDepth = 7 [static], [constexpr]
Definition at line 94 of file inlining-tree.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), and FullyExpand().
wire_byte_size_
int v8::internal::wasm::InliningTree::wire_byte_size_ [private]
Definition at line 194 of file inlining-tree.h.
Referenced by FullyExpand(), score(), and SmallEnoughToInline().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/inlining-tree.h