v8::internal::JSTemporalPlainTime Class Reference
#include <js-temporal-objects.h>
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainTime > Constructor (Isolate *isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > hour, DirectHandle< Object > minute, DirectHandle< Object > second, DirectHandle< Object > millisecond, DirectHandle< Object > microsecond, DirectHandle< Object > nanosecond)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Smi > Compare (Isolate *isolate, DirectHandle< Object > one, DirectHandle< Object > two)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Oddball > Equals (Isolate *isolate, DirectHandle< JSTemporalPlainTime > plain_date, DirectHandle< Object > other)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainTime > From (Isolate *isolate, DirectHandle< Object > item, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > ToZonedDateTime (Isolate *isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > item)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainTime > Add (Isolate *isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > temporal_duration_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainTime > Subtract (Isolate *isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > temporal_duration_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Until (Isolate *isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > other, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Since (Isolate *isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > other, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainTime > Round (Isolate *isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > round_to)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainTime > With (Isolate *isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > temporal_time_like, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainTime > NowISO (Isolate *isolate, DirectHandle< Object > temporal_time_zone_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToJSON (Isolate *isolate, DirectHandle< JSTemporalPlainTime > plain_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToString (Isolate *isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToLocaleString (Isolate *isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > locales, DirectHandle< Object > options)
Detailed Description
Definition at line 544 of file js-temporal-objects.h.
Member Function Documentation
Add()
MaybeDirectHandle< JSTemporalPlainTime > v8::internal::JSTemporalPlainTime::Add (Isolate * isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > temporal_duration_like) [static]
Definition at line 2727 of file js-temporal-objects.cc.
                                                 {
  TEMPORAL_ENTER_FUNC();
  const char method_name[] = "Temporal.PlainTime.prototype.add";
  DirectHandle<JSTemporalDuration> other_duration;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, other_duration,
                             temporal::ToTemporalDuration(
                                 isolate, temporal_duration_like, method_name));
  auto added =
      temporal_time->time()->raw()->add(*other_duration->duration()->raw());
  return ConstructRustWrappingType<JSTemporalPlainTime>(
      isolate, CONSTRUCTOR(plain_time), CONSTRUCTOR(plain_time),
      std::move(added));
}
References ASSIGN_RETURN_ON_EXCEPTION, CONSTRUCTOR, TEMPORAL_ENTER_FUNC, and v8::internal::temporal::ToTemporalDuration().
Compare()
MaybeDirectHandle< Smi > v8::internal::JSTemporalPlainTime::Compare (Isolate * isolate, DirectHandle< Object > one, DirectHandle< Object > two) [static]
Definition at line 2655 of file js-temporal-objects.cc.
                                  {
  const char method_name[] = "Temporal.PlainTime.compare";
  DirectHandle<JSTemporalPlainTime> one;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, one,
      temporal::ToTemporalTime(isolate, one_obj, std::nullopt, method_name));
  DirectHandle<JSTemporalPlainTime> two;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, two,
      temporal::ToTemporalTime(isolate, two_obj, std::nullopt, method_name));
  return direct_handle(Smi::FromInt(temporal_rs::PlainTime::compare(
                           *one->time()->raw(), *two->time()->raw())),
                       isolate);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::direct_handle(), v8::internal::Smi::FromInt(), one, and v8::internal::temporal::ToTemporalTime().
Constructor()
MaybeDirectHandle< JSTemporalPlainTime > v8::internal::JSTemporalPlainTime::Constructor (Isolate * isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > hour, DirectHandle< Object > minute, DirectHandle< Object > second, DirectHandle< Object > millisecond, DirectHandle< Object > microsecond, DirectHandle< Object > nanosecond) [static]
Definition at line 2564 of file js-temporal-objects.cc.
                                         {
  // 1. If NewTarget is undefined, then
  if (IsUndefined(*new_target)) {
    // a. Throw a TypeError exception.
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kMethodInvokedOnWrongType,
                                 isolate->factory()->NewStringFromAsciiChecked(
                                     "Temporal.PlainTime")));
  }
  // 2. If hour is undefined, set hour to 0; else set hour to ?
  // ToIntegerWithTruncation(hour).
  double hour = 0;
  if (!IsUndefined(*hour_obj)) {
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, hour, temporal::ToIntegerWithTruncation(isolate, hour_obj),
        kNullMaybeHandle);
  }
  // 3. If minute is undefined, set minute to 0; else set minute to ?
  // ToIntegerWithTruncation(minute).
  double minute = 0;
  if (!IsUndefined(*minute_obj)) {
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, minute, temporal::ToIntegerWithTruncation(isolate, minute_obj),
        kNullMaybeHandle);
  }
  // 4. If second is undefined, set second to 0; else set second to ?
  // ToIntegerWithTruncation(second).
  double second = 0;
  if (!IsUndefined(*second_obj)) {
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, second, temporal::ToIntegerWithTruncation(isolate, second_obj),
        kNullMaybeHandle);
  }
  // 5. If millisecond is undefined, set millisecond to 0; else set millisecond
  // to ? ToIntegerWithTruncation(millisecond).
  double millisecond = 0;
  if (!IsUndefined(*millisecond_obj)) {
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, millisecond,
        temporal::ToIntegerWithTruncation(isolate, millisecond_obj),
        kNullMaybeHandle);
  }
  // 6. If microsecond is undefined, set microsecond to 0; else set microsecond
  // to ? ToIntegerWithTruncation(microsecond).
  double microsecond = 0;
  if (!IsUndefined(*microsecond_obj)) {
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, microsecond,
        temporal::ToIntegerWithTruncation(isolate, microsecond_obj),
        kNullMaybeHandle);
  }
  // 7. If nanosecond is undefined, set nanosecond to 0; else set nanosecond to
  // ? ToIntegerWithTruncation(nanosecond).
  double nanosecond = 0;
  if (!IsUndefined(*nanosecond_obj)) {
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, nanosecond,
        temporal::ToIntegerWithTruncation(isolate, nanosecond_obj),
        kNullMaybeHandle);
  }
  // 8. If IsValidTime(hour, minute, second, millisecond, microsecond,
  // nanosecond) is false, throw a RangeError exception.
  if (!temporal::IsValidTime(hour, minute, second, millisecond, microsecond,
                             nanosecond)) {
    THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR());
  }
  // Rest of the steps handled in Rust
  // These static_casts are fine to perform since IsValid* will have constrained
  // these values to range already.
  // https://github.com/boa-dev/temporal/issues/334 for moving this logic into
  // the Rust code
  auto rust_object = temporal_rs::PlainTime::try_new(
      static_cast<uint8_t>(hour), static_cast<uint8_t>(minute),
      static_cast<uint8_t>(second), static_cast<uint16_t>(millisecond),
      static_cast<uint16_t>(microsecond), static_cast<uint16_t>(nanosecond));
  return ConstructRustWrappingType<JSTemporalPlainTime>(
      isolate, CONSTRUCTOR(plain_time), CONSTRUCTOR(plain_time),
      std::move(rust_object));
}
References CONSTRUCTOR, v8::internal::Isolate::factory(), v8::internal::temporal::IsValidTime(), v8::internal::kNullMaybeHandle, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::microsecond, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), THROW_NEW_ERROR, and v8::internal::temporal::ToIntegerWithTruncation().
Referenced by v8::internal::BUILTIN().
Equals()
MaybeDirectHandle< Oddball > v8::internal::JSTemporalPlainTime::Equals (Isolate * isolate, DirectHandle< JSTemporalPlainTime > plain_date, DirectHandle< Object > other) [static]
Definition at line 2674 of file js-temporal-objects.cc.
                                    {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
From()
MaybeDirectHandle< JSTemporalPlainTime > v8::internal::JSTemporalPlainTime::From (Isolate * isolate, DirectHandle< Object > item, DirectHandle< Object > options) [static]
Definition at line 2702 of file js-temporal-objects.cc.
                                      {
  const char method_name[] = "Temporal.PlainTime.from";
  DirectHandle<JSTemporalPlainTime> item;
  // Options parsing hoisted out of ToTemporalTime
  // https://github.com/tc39/proposal-temporal/issues/3116
  temporal_rs::ArithmeticOverflow overflow;
  // (ToTemporalTime) i. Let resolvedOptions be ?GetOptionsObject(options).
  // (ToTemporalTime) ii. Perform ?GetTemporalOverflowOption(resolvedOptions).
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, overflow,
      temporal::ToTemporalOverflowHandleUndefined(isolate, options_obj,
                                                  method_name),
      DirectHandle<JSTemporalPlainTime>());
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, item,
      temporal::ToTemporalTime(isolate, item_obj, overflow, method_name));
  return item;
}
References ASSIGN_RETURN_ON_EXCEPTION, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::overflow, v8::internal::temporal::ToTemporalOverflowHandleUndefined(), and v8::internal::temporal::ToTemporalTime().
NowISO()
MaybeDirectHandle< JSTemporalPlainTime > v8::internal::JSTemporalPlainTime::NowISO (Isolate * isolate, DirectHandle< Object > temporal_time_zone_like) [static]
Definition at line 2696 of file js-temporal-objects.cc.
                                                                    {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Round()
MaybeDirectHandle< JSTemporalPlainTime > v8::internal::JSTemporalPlainTime::Round (Isolate * isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > round_to) [static]
Definition at line 2681 of file js-temporal-objects.cc.
                                       {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Since()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalPlainTime::Since (Isolate * isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > other, DirectHandle< Object > options) [static]
Definition at line 2779 of file js-temporal-objects.cc.
                                                              {
  TEMPORAL_ENTER_FUNC();
  const char method_name[] = "Temporal.PlainTime.prototype.since";
  return temporal::DifferenceTemporalPlainTime(
      isolate, temporal::DifferenceOperation::kSince, handle, other, options,
      method_name);
}
References v8::internal::temporal::DifferenceTemporalPlainTime(), v8::internal::handle(), v8::internal::temporal::kSince, and TEMPORAL_ENTER_FUNC.
Subtract()
MaybeDirectHandle< JSTemporalPlainTime > v8::internal::JSTemporalPlainTime::Subtract (Isolate * isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > temporal_duration_like) [static]
Definition at line 2747 of file js-temporal-objects.cc.
                                                 {
  TEMPORAL_ENTER_FUNC();
  const char method_name[] = "Temporal.PlainTime.prototype.subtract";
  DirectHandle<JSTemporalDuration> other_duration;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, other_duration,
                             temporal::ToTemporalDuration(
                                 isolate, temporal_duration_like, method_name));
  auto subtracted = temporal_time->time()->raw()->subtract(
      *other_duration->duration()->raw());
  return ConstructRustWrappingType<JSTemporalPlainTime>(
      isolate, CONSTRUCTOR(plain_time), CONSTRUCTOR(plain_time),
      std::move(subtracted));
}
References ASSIGN_RETURN_ON_EXCEPTION, CONSTRUCTOR, TEMPORAL_ENTER_FUNC, and v8::internal::temporal::ToTemporalDuration().
ToJSON()
MaybeDirectHandle< String > v8::internal::JSTemporalPlainTime::ToJSON (Isolate * isolate, DirectHandle< JSTemporalPlainTime > plain_time) [static]
Definition at line 2792 of file js-temporal-objects.cc.
                                                                       {
  return temporal::TimeRecordToString(isolate, temporal_time,
                                      std::move(temporal::kToStringAuto));
}
References v8::internal::temporal::kToStringAuto, and v8::internal::temporal::TimeRecordToString().
ToLocaleString()
MaybeDirectHandle< String > v8::internal::JSTemporalPlainTime::ToLocaleString (Isolate * isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > locales, DirectHandle< Object > options) [static]
Definition at line 2799 of file js-temporal-objects.cc.
                                                                {
  return temporal::TimeRecordToString(isolate, temporal_time,
                                      std::move(temporal::kToStringAuto));
}
References v8::internal::temporal::kToStringAuto, and v8::internal::temporal::TimeRecordToString().
ToString()
MaybeDirectHandle< String > v8::internal::JSTemporalPlainTime::ToString (Isolate * isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > options) [static]
Definition at line 2807 of file js-temporal-objects.cc.
                                      {
  const char method_name[] = "Temporal.PlainTime.prototype.toString";
  // 3. Let resolvedOptions be ?GetOptionsObject(options).
  DirectHandle<JSReceiver> options;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, options, GetOptionsObject(isolate, options_obj, method_name));
  // 5. Let digits be ?GetTemporalFractionalSecondDigitsOption(resolvedOptions).
  temporal_rs::Precision digits;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, digits,
      temporal::GetTemporalFractionalSecondDigitsOption(isolate, options,
                                                        method_name),
      DirectHandle<String>());
  // 6. Let roundingMode be ? GetRoundingModeOption(resolvedOptions, trunc).
  RoundingMode rounding_mode;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, rounding_mode,
      temporal::GetRoundingModeOption(isolate, options, RoundingMode::Trunc,
                                      method_name),
      DirectHandle<String>());
  // 7. Let smallestUnit be ? GetTemporalUnitValuedOption(resolvedOptions,
  // "smallestUnit", time, unset).
  std::optional<Unit> smallest_unit;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, smallest_unit,
      temporal::GetTemporalUnit(isolate, options, "smallestUnit",
                                UnitGroup::kTime, std::nullopt, false,
                                method_name),
      DirectHandle<String>());
  // 8-10 performed by Rust
  auto rust_options = temporal_rs::ToStringRoundingOptions{
      .precision = digits,
      .smallest_unit = smallest_unit,
      .rounding_mode = rounding_mode,
  };
  return temporal::TimeRecordToString(isolate, temporal_time,
                                      std::move(rust_options));
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::GetOptionsObject(), v8::internal::temporal::GetRoundingModeOption(), v8::internal::temporal::GetTemporalFractionalSecondDigitsOption(), v8::internal::temporal::GetTemporalUnit(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, and v8::internal::temporal::TimeRecordToString().
ToZonedDateTime()
static V8_WARN_UNUSED_RESULT MaybeDirectHandle<JSTemporalZonedDateTime> v8::internal::JSTemporalPlainTime::ToZonedDateTime (Isolate * isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > item) [static]
Until()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalPlainTime::Until (Isolate * isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > other, DirectHandle< Object > options) [static]
Definition at line 2767 of file js-temporal-objects.cc.
                                                              {
  TEMPORAL_ENTER_FUNC();
  const char method_name[] = "Temporal.PlainTime.prototype.until";
  return temporal::DifferenceTemporalPlainTime(
      isolate, temporal::DifferenceOperation::kUntil, handle, other, options,
      method_name);
}
References v8::internal::temporal::DifferenceTemporalPlainTime(), v8::internal::handle(), v8::internal::temporal::kUntil, and TEMPORAL_ENTER_FUNC.
With()
MaybeDirectHandle< JSTemporalPlainTime > v8::internal::JSTemporalPlainTime::With (Isolate * isolate, DirectHandle< JSTemporalPlainTime > plain_time, DirectHandle< Object > temporal_time_like, DirectHandle< Object > options) [static]
Definition at line 2688 of file js-temporal-objects.cc.
                                      {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-temporal-objects.h
/mnt/V8SourceCode/src/objects/js-temporal-objects.cc