v8::internal::maglev::CallRuntime Class Reference
#include <maglev-ir.h>
Public Member Functions
CallRuntime (uint64_t bitfield, Runtime::FunctionId function_id, ValueNode *context)
Runtime::FunctionId function_id () const
Input & context ()
const Input & context () const
int num_args () const
Input & arg (int i)
void set_arg (int i, ValueNode *node)
auto args ()
int ReturnCount () const
void VerifyInputs (MaglevGraphLabeller *graph_labeller) const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr int kContextIndex = 0
static constexpr int kFixedInputCount = 1
static constexpr OpProperties kProperties = OpProperties::JSCall()
Private Types
using Base = ValueNodeT< CallRuntime >
Private Attributes
Runtime::FunctionId function_id_
Additional Inherited Members
Detailed Description
Definition at line 10333 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CallRuntime::Base = ValueNodeT<CallRuntime> [private]
Definition at line 10334 of file maglev-ir.h.
Constructor & Destructor Documentation
CallRuntime()
v8::internal::maglev::CallRuntime::CallRuntime (uint64_t bitfield, Runtime::FunctionId function_id, ValueNode * context) [inline]
Definition at line 10343 of file maglev-ir.h.
      : Base(bitfield), function_id_(function_id) {
    set_input(kContextIndex, context);
  }
Member Function Documentation
arg()
Input& v8::internal::maglev::CallRuntime::arg (int i) [inline]
Definition at line 10356 of file maglev-ir.h.
{ return input(i + kFixedInputCount); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
args()
auto v8::internal::maglev::CallRuntime::args () [inline]
Definition at line 10360 of file maglev-ir.h.
              {
    return base::make_iterator_range(
        std::make_reverse_iterator(&arg(-1)),
        std::make_reverse_iterator(&arg(num_args() - 1)));
  }
References v8::base::make_iterator_range().
context() [1/2]
Input& v8::internal::maglev::CallRuntime::context () [inline]
Definition at line 10353 of file maglev-ir.h.
{ return input(kContextIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context() [2/2]
const Input& v8::internal::maglev::CallRuntime::context () const [inline]
Definition at line 10354 of file maglev-ir.h.
{ return input(kContextIndex); }
function_id()
Runtime::FunctionId v8::internal::maglev::CallRuntime::function_id () const [inline]
Definition at line 10351 of file maglev-ir.h.
{ return function_id_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::CallRuntime::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::CallRuntime::MaxCallStackArgs () const
num_args()
int v8::internal::maglev::CallRuntime::num_args () const [inline]
Definition at line 10355 of file maglev-ir.h.
{ return input_count() - kFixedInputCount; }
References v8::internal::compiler::turboshaft::detail::input_count().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::CallRuntime::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8423 of file maglev-ir.cc.
                                                                         {
  os << "(" << Runtime::FunctionForId(function_id())->name << ")";
}
References function_id(), v8::internal::Runtime::FunctionForId(), and v8::internal::Runtime::Function::name.
ReturnCount()
int v8::internal::maglev::CallRuntime::ReturnCount () const [inline]
Definition at line 10366 of file maglev-ir.h.
                          {
    return Runtime::FunctionForId(function_id())->result_size;
  }
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetSecondValue(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
set_arg()
void v8::internal::maglev::CallRuntime::set_arg (int i, ValueNode * node) [inline]
Definition at line 10357 of file maglev-ir.h.
                                       {
    set_input(i + kFixedInputCount, node);
  }
SetValueLocationConstraints()
void v8::internal::maglev::CallRuntime::SetValueLocationConstraints ()
VerifyInputs()
void v8::internal::maglev::CallRuntime::VerifyInputs (MaglevGraphLabeller * graph_labeller) const
Definition at line 1117 of file maglev-ir.cc.
                                                                        {
  for (int i = 0; i < input_count(); i++) {
    CheckValueInputIs(this, i, ValueRepresentation::kTagged, graph_labeller);
  }
}
References v8::internal::maglev::CheckValueInputIs(), v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::maglev::kTagged.
Member Data Documentation
function_id_
Runtime::FunctionId v8::internal::maglev::CallRuntime::function_id_ [private]
Definition at line 10380 of file maglev-ir.h.
kContextIndex
constexpr int v8::internal::maglev::CallRuntime::kContextIndex = 0 [static], [constexpr]
Definition at line 10338 of file maglev-ir.h.
kFixedInputCount
constexpr int v8::internal::maglev::CallRuntime::kFixedInputCount = 1 [static], [constexpr]
Definition at line 10339 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CallRuntime::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 10349 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc