v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency Class Reference
Public Member Functions
ConstantInDictionaryPrototypeChainDependency (const MapRef receiver_map, const NameRef property_name, const ObjectRef constant, PropertyKind kind)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
MaybeHandle< JSObject > GetHolderIfValid (JSHeapBroker *broker) const
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const MapRef receiver_map_
const NameRef property_name_
const ObjectRef constant_
const PropertyKind kind_
Additional Inherited Members
Detailed Description
Definition at line 317 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
ConstantInDictionaryPrototypeChainDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::ConstantInDictionaryPrototypeChainDependency (const MapRef receiver_map, const NameRef property_name, const ObjectRef constant, PropertyKind kind) [inline], [explicit]
Definition at line 320 of file compilation-dependencies.cc.
      : CompilationDependency(kConstantInDictionaryPrototypeChain),
        receiver_map_(receiver_map),
        property_name_{property_name},
        constant_{constant},
        kind_{kind} {
    DCHECK(V8_DICT_PROPERTY_CONST_TRACKING_BOOL);
  }
References v8::internal::DCHECK(), and V8_DICT_PROPERTY_CONST_TRACKING_BOOL.
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 439 of file compilation-dependencies.cc.
                                                                {
    const ConstantInDictionaryPrototypeChainDependency* const zat =
        that->AsConstantInDictionaryPrototypeChain();
    return receiver_map_.equals(zat->receiver_map_) &&
           property_name_.equals(zat->property_name_) &&
           constant_.equals(zat->constant_) && kind_ == zat->kind_;
  }
References constant_, kind_, property_name_, and receiver_map_.
GetHolderIfValid()
MaybeHandle<JSObject> v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::GetHolderIfValid (JSHeapBroker * broker) const [inline], [private]
Definition at line 360 of file compilation-dependencies.cc.
                                                                     {
    DisallowGarbageCollection no_gc;
    Isolate* isolate = broker->isolate();
    Tagged<HeapObject> prototype = receiver_map_.object()->prototype();
    enum class ValidationResult { kFoundCorrect, kFoundIncorrect, kNotFound };
    auto try_load = [&](auto dictionary) -> ValidationResult {
      InternalIndex entry =
          dictionary->FindEntry(isolate, property_name_.object());
      if (entry.is_not_found()) {
        return ValidationResult::kNotFound;
      }
      PropertyDetails details = dictionary->DetailsAt(entry);
      if (details.constness() != PropertyConstness::kConst) {
        return ValidationResult::kFoundIncorrect;
      }
      Tagged<Object> dictionary_value = dictionary->ValueAt(entry);
      Tagged<Object> value;
      // We must be able to detect the case that the property |property_name_|
      // of |holder_| was originally a plain function |constant_| (when creating
      // this dependency) and has since become an accessor whose getter is
      // |constant_|. Therefore, we cannot just look at the property kind of
      // |details|, because that reflects the current situation, not the one
      // when creating this dependency.
      if (details.kind() != kind_) {
        return ValidationResult::kFoundIncorrect;
      }
      if (kind_ == PropertyKind::kAccessor) {
        if (!IsAccessorPair(dictionary_value)) {
          return ValidationResult::kFoundIncorrect;
        }
        // Only supporting loading at the moment, so we only ever want the
        // getter.
        value = Cast<AccessorPair>(dictionary_value)
                    ->get(AccessorComponent::ACCESSOR_GETTER);
      } else {
        value = dictionary_value;
      }
      return value == *constant_.object() ? ValidationResult::kFoundCorrect
                                          : ValidationResult::kFoundIncorrect;
    };
    while (IsJSObject(prototype)) {
      // We only care about JSObjects because that's the only type of holder
      // (and types of prototypes on the chain to the holder) that
      // AccessInfoFactory::ComputePropertyAccessInfo allows.
      Tagged<JSObject> object = Cast<JSObject>(prototype);
      // We only support dictionary mode prototypes on the chain for this kind
      // of dependency.
      CHECK(!object->HasFastProperties());
      ValidationResult result =
          V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL
              ? try_load(object->property_dictionary_swiss())
              : try_load(object->property_dictionary());
      if (result == ValidationResult::kFoundCorrect) {
        return handle(object, isolate);
      } else if (result == ValidationResult::kFoundIncorrect) {
        return MaybeHandle<JSObject>();
      }
      // In case of kNotFound, continue walking up the chain.
      prototype = object->map()->prototype();
    }
    return MaybeHandle<JSObject>();
  }
References v8::internal::ACCESSOR_GETTER, broker(), CHECK, v8::internal::PropertyDetails::constness(), v8::internal::handle(), v8::internal::InternalIndex::is_not_found(), v8::internal::kAccessor, v8::internal::kConst, v8::internal::PropertyDetails::kind(), v8::internal::kNotFound, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::prototype, v8::base::internal::result, V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, and v8::internal::value.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 433 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(receiver_map_), h(property_name_), h(constant_),
                              static_cast<int>(kind_));
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 337 of file compilation-dependencies.cc.
                                                                               {
    SLOW_DCHECK(IsValid(broker));
    Isolate* isolate = broker->isolate();
    DirectHandle<JSObject> holder = GetHolderIfValid(broker).ToHandleChecked();
    Handle<Map> map = receiver_map_.object();
    while (map->prototype() != *holder) {
      map = handle(map->prototype()->map(), isolate);
      DCHECK(IsJSObjectMap(*map)); // Due to IsValid holding.
      deps->Register(map, DependentCode::kPrototypeCheckGroup);
    }
    DCHECK(IsJSObjectMap(map->prototype()->map())); // Due to IsValid holding.
    deps->Register(handle(map->prototype()->map(), isolate),
                   DependentCode::kPrototypeCheckGroup);
  }
References broker(), v8::internal::DCHECK(), v8::internal::handle(), v8::internal::DependentCode::kPrototypeCheckGroup, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), and SLOW_DCHECK.
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 333 of file compilation-dependencies.cc.
                                                    {
    return !GetHolderIfValid(broker).is_null();
  }
References broker().
Member Data Documentation
constant_
const ObjectRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::constant_ [private]
Definition at line 449 of file compilation-dependencies.cc.
Referenced by Equals().
kind_
const PropertyKind v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::kind_ [private]
Definition at line 450 of file compilation-dependencies.cc.
Referenced by Equals().
property_name_
const NameRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::property_name_ [private]
Definition at line 448 of file compilation-dependencies.cc.
Referenced by Equals().
receiver_map_
const MapRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::receiver_map_ [private]
Definition at line 447 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc