v8::internal::wasm::DebugSideTable Class Reference
#include <wasm-debug.h>
Classes
class Entry
struct EntryPositionLess
Public Member Functions
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (DebugSideTable)
DebugSideTable (int num_locals, std::vector< Entry > entries)
const Entry * GetEntry (int pc_offset) const
const Entry::Value * FindValue (const Entry *entry, int stack_index) const
auto entries () const
int num_locals () const
void Print (std::ostream &) const
size_t EstimateCurrentMemoryConsumption () const
Private Attributes
int num_locals_
std::vector< Entry > entries_
Detailed Description
Definition at line 42 of file wasm-debug.h.
Constructor & Destructor Documentation
DebugSideTable()
v8::internal::wasm::DebugSideTable::DebugSideTable (int num_locals, std::vector< Entry > entries) [inline], [explicit]
Definition at line 121 of file wasm-debug.h.
      : num_locals_(num_locals), entries_(std::move(entries)) {
    DCHECK(
        std::is_sorted(entries_.begin(), entries_.end(), EntryPositionLess{}));
  }
References v8::internal::DCHECK(), and entries_.
Referenced by EstimateCurrentMemoryConsumption().
Member Function Documentation
entries()
auto v8::internal::wasm::DebugSideTable::entries () const [inline]
Definition at line 150 of file wasm-debug.h.
                       {
    return base::make_iterator_range(entries_.begin(), entries_.end());
  }
References entries_, and v8::base::make_iterator_range().
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::DebugSideTable::EstimateCurrentMemoryConsumption () const
Definition at line 121 of file wasm-debug.cc.
                                                              {
  UPDATE_WHEN_CLASS_CHANGES(DebugSideTable, 32);
  size_t result = sizeof(DebugSideTable) + ContentSize(entries_);
  for (const Entry& entry : entries_) {
    result += entry.EstimateCurrentMemoryConsumption();
  }
  return result;
}
References v8::internal::wasm::ContentSize(), DebugSideTable(), entries_, v8::base::internal::result, and UPDATE_WHEN_CLASS_CHANGES.
FindValue()
const Entry::Value* v8::internal::wasm::DebugSideTable::FindValue (const Entry * entry, int stack_index) const [inline]
Definition at line 135 of file wasm-debug.h.
                                                                         {
    while (true) {
      if (auto* value = entry->FindChangedValue(stack_index)) {
        // Check that the table was correctly minimized: If the previous stack
        // also had an entry for {stack_index}, it must be different.
        DCHECK(entry == &entries_.front() ||
               (entry - 1)->stack_height() <= stack_index ||
               *FindValue(entry - 1, stack_index) != *value);
        return value;
      }
      DCHECK_NE(&entries_.front(), entry);
      --entry;
    }
  }
References v8::internal::DCHECK(), DCHECK_NE, entries_, v8::internal::wasm::DebugSideTable::Entry::FindChangedValue(), and v8::internal::value.
Referenced by v8::internal::wasm::DebugInfoImpl::GetValue().
GetEntry()
const Entry* v8::internal::wasm::DebugSideTable::GetEntry (int pc_offset) const [inline]
Definition at line 127 of file wasm-debug.h.
                                             {
    auto it = std::lower_bound(entries_.begin(), entries_.end(),
                               Entry{pc_offset}, EntryPositionLess{});
    if (it == entries_.end() || it->pc_offset() != pc_offset) return nullptr;
    DCHECK_LE(num_locals_, it->stack_height());
    return &*it;
  }
References DCHECK_LE, entries_, and num_locals_.
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR()
v8::internal::wasm::DebugSideTable::MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (DebugSideTable)
num_locals()
int v8::internal::wasm::DebugSideTable::num_locals () const [inline]
Definition at line 154 of file wasm-debug.h.
{ return num_locals_; }
References num_locals_.
Referenced by v8::internal::wasm::DebugInfoImpl::GetNumLocals(), v8::internal::wasm::DebugInfoImpl::GetStackDepth(), and v8::internal::wasm::DebugInfoImpl::GetStackValue().
Print()
void v8::internal::wasm::DebugSideTable::Print (std::ostream & os) const
Definition at line 89 of file wasm-debug.cc.
                                               {
  os << "Debug side table (" << num_locals_ << " locals, " << entries_.size()
     << " entries):\n";
  for (auto& entry : entries_) entry.Print(os);
  os << "\n";
}
References entries_, and num_locals_.
Member Data Documentation
entries_
std::vector<Entry> v8::internal::wasm::DebugSideTable::entries_ [private]
Definition at line 168 of file wasm-debug.h.
Referenced by DebugSideTable(), entries(), EstimateCurrentMemoryConsumption(), FindValue(), GetEntry(), and Print().
num_locals_
int v8::internal::wasm::DebugSideTable::num_locals_ [private]
Definition at line 167 of file wasm-debug.h.
Referenced by GetEntry(), num_locals(), and Print().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-debug.h
/mnt/V8SourceCode/src/wasm/wasm-debug.cc