v8::internal::Tagged< HeapObject > Class Reference
#include <tagged.h>
Public Member Functions
constexpr Tagged ()=default
Tagged (const HeapObjectLayout *ptr)
template<typename U >
constexpr Tagged & operator= (Tagged< U > other) requires(is_subtype_v< U
template<typename U >
constexpr Tagged (Tagged< U > other) requires(is_subtype_v< U
constexpr detail::TaggedOperatorArrowRef< HeapObject > operator-> () const
constexpr bool is_null () const
constexpr bool IsHeapObject () const
constexpr bool IsSmi () const
template<typename U >
constexpr Tagged (U raw) requires(std
Address address () const
Static Public Member Functions
template<typename U >
static constexpr Tagged< HeapObject > cast (U other)
Public Attributes
constexpr Tagged HeapObject
constexpr HeapObject: Base(other) {} inline constexpr HeapObject operator*() const
Protected Member Functions
constexpr Tagged (Address ptr)
Private Types
using Base = StrongTaggedBase
Private Member Functions
constexpr HeapObject ToRawPtr () const
Friends
class HeapObject
class Handle< HeapObject >
template<typename TFieldType , int kFieldOffset, typename CompressionScheme >
class TaggedField
template<typename To , typename From >
Tagged< To > UncheckedCast (Tagged< From > value)
Tagged< HeapObject > MakeStrong (Tagged< HeapObject > value)
Tagged< HeapObject > MakeStrong (Tagged< MaybeWeak< HeapObject >> value)
Additional Inherited Members
Detailed Description
Definition at line 470 of file tagged.h.
Member Typedef Documentation
Base
using v8::internal::Tagged< HeapObject >::Base = StrongTaggedBase [private]
Definition at line 471 of file tagged.h.
Constructor & Destructor Documentation
Tagged() [1/5]
constexpr v8::internal::Tagged< HeapObject >::Tagged () [inline], [constexpr], [default]
Tagged() [2/5]
v8::internal::Tagged< HeapObject >::Tagged (const HeapObjectLayout * ptr) [inline]
Definition at line 480 of file tagged.h.
      : Tagged(reinterpret_cast<Address>(ptr) + kHeapObjectTag) {}
Tagged() [3/5]
template<typename U >
constexpr v8::internal::Tagged< HeapObject >::Tagged (Tagged< U > other) [inline], [constexpr]
Tagged() [4/5]
template<typename U >
constexpr v8::internal::Tagged< HeapObject >::Tagged (U raw) [inline], [constexpr]
Definition at line 514 of file tagged.h.
      : Base(raw.ptr()) {
    static_assert(kTaggedCanConvertToRawObjects);
  }
References v8::internal::kTaggedCanConvertToRawObjects.
Tagged() [5/5]
constexpr v8::internal::Tagged< HeapObject >::Tagged (Address ptr) [inline], [explicit], [constexpr], [protected]
Definition at line 528 of file tagged.h.
: Base(ptr) {}
Member Function Documentation
address()
Address v8::internal::Tagged< HeapObject >::address () const [inline]
Definition at line 525 of file tagged.h.
{ return this->ptr() - kHeapObjectTag; }
References v8::internal::kHeapObjectTag, and v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::ptr().
Referenced by v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::address(), v8::internal::MainAllocator::AllocateFastAligned(), v8::internal::MainAllocator::AllocateFastUnaligned(), v8::internal::AllocationTracker::AllocationEvent(), v8::internal::CodeAddressMap::BytecodeMoveEvent(), v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(), v8::internal::Code::ClearEmbeddedObjectsAndJSDispatchHandles(), v8::internal::CodeAddressMap::CodeMoveEvent(), v8::internal::anonymous_namespace{heap.cc}::CompareWords(), v8::internal::Serializer::CopyCode(), v8::internal::SharedFunctionInfo::CopyFrom(), v8::internal::Factory::CopyJSObjectWithAllocationSite(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::CopyToReadOnlyHeap(), v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::anonymous_namespace{read-only-serializer.cc}::Encode(), v8::internal::V8HeapExplorer::ExtractDescriptorArrayReferences(), v8::internal::V8FileLogger::FeedbackVectorEvent(), v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::FilterNormalObject(), v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::FindBasePtr(), v8::internal::MarkCompactCollector::FlushBytecodeFromSFI(), v8::internal::WritableJitAllocation::ForInstructionStream(), v8::internal::Heap::GcSafeInstructionStreamContains(), v8::internal::TranslatedValue::GetRawValue(), v8::internal::anonymous_namespace{read-only-serializer.cc}::GetUnmappedRegions(), v8::internal::ExternalPointerSlot::init(), v8::internal::InitSelfIndirectPointerField(), v8::internal::anonymous_namespace{concurrent-marking.cc}::IsYoungObjectInLab(), v8::internal::DoubleStringCache::BodyDescriptor::IterateBody(), v8::internal::V8FileLogger::LogSourceCodeInformation(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::LogUpdatedCodePointerTableEntry(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::LogUpdatedExternalPointerTableEntry(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::LogUpdatedPointer(), v8::internal::WriteBarrier::MarkingFromCode(), v8::internal::WriteBarrier::MarkingSlow(), v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry(), v8::internal::Scavenger::MigrateObject(), v8::internal::Heap::OnMoveEvent(), v8::internal::OutsideSandboxOrInReadonlySpace(), v8::internal::Scavenger::PinAndPushObject(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::ProcessStrongHeapObject(), v8::internal::Evacuator::RawEvacuatePage(), v8::internal::EvacuateVisitorBase::RawMigrateObject(), v8::internal::EphemeronRememberedSet::RecordEphemeronKeyWrite(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualFeedbackVectorDetails(), v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), v8::internal::MarkCompactCollector::RightTrimDescriptorArray(), v8::internal::FreeListCategory::SearchForNodeInList(), v8::internal::Serializer::ObjectSerializer::SerializeContent(), v8::internal::Serializer::SerializeReadOnlyObjectReference(), v8::internal::ReadOnlyPageMetadata::ShrinkToHighWaterMark(), v8::internal::Heap::StaticRootsEnsureAllocatedSize(), v8::internal::EmbedderDataSlot::store_aligned_pointer(), v8::internal::MapWord::ToForwardingAddress(), v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList(), v8::internal::MapUpdater::TryUpdateNoLock(), and v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitPointersImpl().
cast()
template<typename U >
static constexpr Tagged<HeapObject> v8::internal::Tagged< HeapObject >::cast (U other) [inline], [static], [constexpr]
Definition at line 520 of file tagged.h.
                                                    {
    static_assert(kTaggedCanConvertToRawObjects);
    return Cast<HeapObject>(Tagged<U>(other));
  }
References v8::internal::kTaggedCanConvertToRawObjects.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-objects.cc}::CheckExpectedSharedness(), and v8::internal::wasm::anonymous_namespace{wasm-objects.cc}::ConvertToSharedIfExpected().
is_null()
constexpr bool v8::internal::Tagged< HeapObject >::is_null () const [inline], [constexpr]
Definition at line 502 of file tagged.h.
                                           {
    return static_cast<Tagged_t>(this->ptr()) ==
           static_cast<Tagged_t>(kNullAddress);
  }
References v8::internal::kNullAddress, and v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::ptr().
Referenced by v8::internal::MutableBigInt::AbsoluteAddOne(), v8::internal::StringComparator::State::Advance(), v8::internal::FreeListMany::Allocate(), v8::internal::FreeListManyCached::Allocate(), v8::internal::FreeListManyCachedFastPathBase::Allocate(), v8::internal::CodeEventLogger::NameBuffer::AppendString(), v8::internal::LogFile::MessageBuilder::AppendString(), v8::internal::LogFile::MessageBuilder::AppendSymbolName(), v8::internal::LogFile::MessageBuilder::AppendSymbolNameDetails(), v8::internal::Factory::CodeBuilder::BuildInternal(), v8::ContainsOnlyOneByteHelper::Check(), v8::ContainsOnlyOneByteHelper::CheckCons(), v8::internal::MarkCompactCollector::ClearFullMapTransitions(), v8::internal::Snapshot::ClearReconstructableDataForSerialization(), v8::internal::Heap::CollectAllAvailableGarbage(), v8::internal::anonymous_namespace{debug-coverage.cc}::CollectAndMaybeResetCounts(), v8::internal::CodeStatistics::CollectCodeStatistics(), v8::internal::KeyAccumulator::CollectOwnKeys(), v8::internal::Isolate::CollectSourcePositionsForAllBytecodeArrays(), v8::internal::MarkCompactCollector::CompactTransitionArray(), v8::internal::Heap::CompactWeakArrayLists(), v8::internal::anonymous_namespace{api-natives.cc}::ConfigureInstance(), v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl(), v8::internal::ContainsMap(), v8::internal::Map::CopyAsElementsKind(), v8::internal::WriteBarrier::CurrentMarkingBarrier(), v8::internal::Deoptimizer::DeoptimizeMarkedCode(), v8::internal::anonymous_namespace{liveedit.cc}::DetermineOuterScopeInfo(), v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::DeterminePromotees(), v8::internal::Debug::DiscardAllBaselineCode(), v8::internal::Debug::DiscardBaselineCode(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::EncodeTaggedSlots(), v8::internal::EnumerateCompiledFunctions(), v8::internal::V8HeapExplorer::EstimateObjectsCount(), v8::internal::ETWJITInterface::EventHandler(), v8::internal::V8HeapExplorer::ExtractLocation(), v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::Fill(), v8::internal::PretenuringHandler::FindAllocationMemento(), v8::internal::FindClosestElementsTransition(), v8::internal::Map::FindElementsKindTransitionedMap(), v8::internal::HeapProfiler::FindHeapObjectById(), v8::internal::Debug::FindInnermostContainingFunctionInfo(), v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::FindScopeInfoForScope(), v8::internal::MapUpdater::FindSplitMap(), v8::internal::TransitionsAccessor::FindTransitionToField(), v8::internal::FreeListCategory::FreeListLength(), v8::internal::MapWord::FromMap(), v8::internal::V8FileLogger::FunctionEvent(), v8::internal::Heap::GcSafeGetCodeFromInstructionStream(), v8::internal::MaglevFrame::GetBytecodeOffsetForOSR(), v8::internal::StatisticsExtension::GetCounters(), v8::Isolate::GetCurrentContext(), v8::internal::HeapProfiler::GetDetachedJSWrapperObjects(), v8::internal::OptimizedJSFrame::GetFunctions(), v8::internal::Isolate::GetIncumbentContext(), v8::internal::LookupIterator::GetInterceptorForFailedAccessCheck(), v8::internal::compiler::JSHeapBroker::GetNameFeedback(), v8::internal::ObjectTemplateInfo::GetParent(), v8::internal::WasmExportedFunction::GetWrapper(), v8::internal::StringComparator::State::Init(), v8::internal::ConsStringIterator::Initialize(), v8::internal::anonymous_namespace{bootstrapper.cc}::InitializeJSArrayMaps(), v8::internal::TransitionsAccessor::InsertHelper(), v8::internal::Debug::InstallDebugBreakTrampoline(), v8::internal::anonymous_namespace{js-objects.cc}::InvalidatePrototypeChainsInternal(), v8::internal::AllocationResult::IsFailure(), v8::internal::IC::IsTransitionOfMonomorphicTarget(), v8::internal::V8HeapExplorer::IterateAndExtractReferences(), v8::internal::anonymous_namespace{object-stats.cc}::IterateHeap(), v8::internal::compiler::JsonPrintBytecodeSource(), v8::internal::KeyedLoadIC::LoadElementPolymorphicHandlers(), v8::internal::V8FileLogger::LogAccessorCallbacks(), v8::internal::V8FileLogger::LogAllMaps(), v8::internal::ExistingCodeLogger::LogCodeObjects(), v8::internal::ExistingCodeLogger::LogCompiledFunctions(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), v8::internal::Isolate::MayAccess(), v8::internal::Isolate::MaybeInitializeVectorListFromHeap(), v8::internal::Factory::NewJSArrayWithUnverifiedElements(), v8::internal::HeapObjectIterator::Next(), v8::internal::ReadOnlyHeapObjectIterator::Next(), v8::internal::LookupIterator::NextInternal(), v8::internal::HeapObjectIterator::NextObject(), v8::internal::JSObject::OptimizeAsPrototype(), v8::internal::CompiledReplacement::ParseReplacementPattern(), v8::internal::FreeListCategory::PickNodeFromList(), v8::internal::ReadOnlyDeserializer::PostProcessNewObjects(), v8::internal::FastKeyAccumulator::Prepare(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::PreProcessSegment(), v8::internal::JavaScriptFrame::Print(), v8::internal::compiler::JSHeapBroker::ProcessFeedbackMapsForElementAccess(), v8::internal::HeapProfiler::QueryObjects(), v8::internal::FreeListCategory::RepairFreeList(), v8::internal::Isolate::ReportFailedAccessCheck(), v8::internal::ConsStringIterator::Reset(), v8::internal::StringCharacterStream::Reset(), v8::debug::ResetBlackboxedStateCache(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ObjectStatsCollectorImpl::SameLiveness(), v8::internal::FreeList::SearchForNodeInList(), v8::internal::FreeListCategory::SearchForNodeInList(), v8::internal::anonymous_namespace{map.cc}::SearchMigrationTarget(), v8::internal::Coverage::SelectMode(), v8::internal::ReadOnlySerializer::Serialize(), v8::debug::Script::SetInstrumentationBreakpoint(), v8::internal::IC::ShouldRecomputeHandler(), v8::internal::KeyedStoreIC::StoreElementPolymorphicHandlers(), v8::internal::FreeListCategory::SumFreeList(), v8::internal::OptimizedJSFrame::Summarize(), v8::internal::TranslatedState::TranslatedState(), v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList(), v8::internal::anonymous_namespace{js-objects.cc}::TryFastAddDataProperty(), v8::internal::FreeList::TryFindNodeIn(), v8::internal::Map::TryReplayPropertyTransitions(), v8::internal::Map::TryUpdate(), v8::internal::MapUpdater::TryUpdateNoLock(), v8::internal::WasmMemoryMapDescriptor::UnmapDescriptor(), v8::internal::ScopeIterator::UnwrapEvaluationContext(), v8::internal::Map::Update(), v8::internal::PretenuringHandler::UpdateAllocationSite(), v8::internal::JSObject::UpdateAllocationSite(), v8::internal::HeapObjectsMap::UpdateHeapObjectsMap(), v8::internal::IC::UpdateOneMapManyNamesIC(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointers(), v8::internal::ConstantPoolPointerForwarder::UpdateScopeInfo(), v8::internal::Heap::ExternalStringTable::UpdateYoungReferences(), v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::VisitObject(), v8::internal::VisitWeakList(), v8::internal::anonymous_namespace{string.cc}::wtf_push(), and v8::internal::anonymous_namespace{string.cc}::wtf_try_pop().
IsHeapObject()
constexpr bool v8::internal::Tagged< HeapObject >::IsHeapObject () const [inline], [constexpr]
Definition at line 507 of file tagged.h.
{ return true; }
IsSmi()
constexpr bool v8::internal::Tagged< HeapObject >::IsSmi () const [inline], [constexpr]
Definition at line 508 of file tagged.h.
{ return false; }
Referenced by v8::internal::PrototypeUsers::Compact(), v8::internal::wasm::WasmExportWrapperCache::EnsureCapacity(), v8::internal::FastInReadOnlySpaceOrSmallSmi(), v8::internal::wasm::WasmExportWrapperCache::Get(), v8::internal::TransitionArray::GetTargetIfExists(), v8::internal::wasm::WasmExportWrapperCache::PutInternal(), v8::internal::MarkCompactCollector::TransitionArrayNeedsCompaction(), v8::internal::MapUpdater::UpdateFieldType(), and v8::internal::Serializer::ObjectSerializer::VisitProtectedPointer().
operator->()
constexpr detail::TaggedOperatorArrowRef< HeapObject > v8::internal::Tagged< HeapObject >::operator-> () const [inline], [constexpr]
Definition at line 566 of file heap-object.h.
                                     {
  return detail::TaggedOperatorArrowRef<HeapObject>{ToRawPtr()};
}
References v8::internal::Tagged< T >::ToRawPtr().
operator=()
template<typename U >
constexpr Tagged& v8::internal::Tagged< HeapObject >::operator= (Tagged< U > other) [inline], [constexpr]
ToRawPtr()
constexpr HeapObject v8::internal::Tagged< HeapObject >::ToRawPtr () const [inline], [constexpr], [private]
Definition at line 569 of file heap-object.h.
                                                        {
  return HeapObject(this->ptr(), HeapObject::SkipTypeCheckTag{});
}
References HeapObject, and v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::ptr().
Friends And Related Function Documentation
Handle< HeapObject >
friend class Handle< HeapObject > [friend]
Definition at line 531 of file tagged.h.
HeapObject
friend class HeapObject [friend]
Definition at line 531 of file tagged.h.
MakeStrong [1/2]
Tagged<HeapObject> MakeStrong (Tagged< HeapObject > value) [friend]
MakeStrong [2/2]
Tagged<HeapObject> MakeStrong (Tagged< MaybeWeak< HeapObject >> value) [friend]
TaggedField
template<typename TFieldType , int kFieldOffset, typename CompressionScheme >
friend class TaggedField [friend]
Definition at line 538 of file tagged.h.
UncheckedCast
template<typename To , typename From >
Tagged<To> UncheckedCast (Tagged< From > value) [friend]
Definition at line 61 of file casting.h.
                                                    {
  return Tagged<To>(value.ptr());
}
Member Data Documentation
HeapObject [1/2]
constexpr Tagged v8::internal::Tagged< HeapObject >::HeapObject
Initial value:
{
    return *this = Tagged(other)
Definition at line 486 of file tagged.h.
Referenced by ToRawPtr().
HeapObject [2/2]
constexpr v8::internal::Tagged< HeapObject >::HeapObject
Definition at line 495 of file tagged.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/tagged.h
/mnt/V8SourceCode/src/objects/heap-object.h