v8::internal::TranslatedValue Class Reference
#include <translated-state.h>
Classes
struct MaterializedObjectInfo
Public Member Functions
Tagged< Object > GetRawValue () const
int GetSmiValue () const
Handle< Object > GetValue ()
bool IsMaterializedObject () const
bool IsMaterializableByDebugger () const
Private Types
enum Kind : uint8_t {
kInvalid
, kTagged
, kInt32
, kInt64
,
kInt64ToBigInt
, kUint64ToBigInt
, kUint32
, kUint64
,
kBoolBit
, kFloat
, kDouble
, kHoleyDouble
,
kSimd128
, kCapturedObject
, kDuplicatedObject
, kCapturedStringConcat
 }
enum MaterializationState : uint8_t { kUninitialized
, kAllocated
, kFinished
 }
Private Member Functions
TranslatedValue (TranslatedState *container, Kind kind)
Kind kind () const
MaterializationState materialization_state () const
void Handlify ()
int GetChildrenCount () const
Isolate * isolate () const
void set_storage (Handle< HeapObject > storage)
void set_initialized_storage (Handle< HeapObject > storage)
void mark_finished ()
void mark_allocated ()
Handle< HeapObject > storage ()
void ReplaceElementsArrayWithCopy ()
Tagged< Object > raw_literal () const
int32_t int32_value () const
int64_t int64_value () const
uint32_t uint32_value () const
uint64_t uint64_value () const
Float32 float_value () const
Float64 double_value () const
Simd128 simd_value () const
int object_length () const
int object_index () const
int string_concat_index () const
Static Private Member Functions
static TranslatedValue NewDeferredObject (TranslatedState *container, int length, int object_index)
static TranslatedValue NewDuplicateObject (TranslatedState *container, int id)
static TranslatedValue NewStringConcat (TranslatedState *container, int id)
static TranslatedValue NewFloat (TranslatedState *container, Float32 value)
static TranslatedValue NewDouble (TranslatedState *container, Float64 value)
static TranslatedValue NewHoleyDouble (TranslatedState *container, Float64 value)
static TranslatedValue NewSimd128 (TranslatedState *container, Simd128 value)
static TranslatedValue NewInt32 (TranslatedState *container, int32_t value)
static TranslatedValue NewInt64 (TranslatedState *container, int64_t value)
static TranslatedValue NewInt64ToBigInt (TranslatedState *container, int64_t value)
static TranslatedValue NewUint64ToBigInt (TranslatedState *container, uint64_t value)
static TranslatedValue NewUint32 (TranslatedState *container, uint32_t value)
static TranslatedValue NewUint64 (TranslatedState *container, uint64_t value)
static TranslatedValue NewBool (TranslatedState *container, uint32_t value)
static TranslatedValue NewTagged (TranslatedState *container, Tagged< Object > literal)
static TranslatedValue NewInvalid (TranslatedState *container)
Private Attributes
Kind kind_
MaterializationState materialization_state_ = kUninitialized
TranslatedState * container_
Handle< HeapObject > storage_
xx xx xx xx xx xx xx xx xx
union {
 Tagged< Object > raw_literal_
 uint32_t uint32_value_
 int32_t int32_value_
 uint64_t uint64_value_
 int64_t int64_value_
 Float32 float_value_
 Float64 double_value_
 MaterializedObjectInfo materialization_info_
 Simd128 simd128_value_
};
Friends
class TranslatedState
class TranslatedFrame
class Deoptimizer
class DeoptimizationLiteralProvider
Detailed Description
Definition at line 53 of file translated-state.h.
Member Enumeration Documentation
Kind
enum v8::internal::TranslatedValue::Kind : uint8_t [private]
Enumerator
kInvalid
kTagged
kInt32
kInt64
kInt64ToBigInt
kUint64ToBigInt
kUint32
kUint64
kBoolBit
kFloat
kDouble
kHoleyDouble
kSimd128
kCapturedObject
kDuplicatedObject
kCapturedStringConcat
Definition at line 77 of file translated-state.h.
            : uint8_t {
    kInvalid,
    kTagged,
    kInt32,
    kInt64,
    kInt64ToBigInt,
    kUint64ToBigInt,
    kUint32,
    kUint64,
    kBoolBit,
    kFloat,
    kDouble,
    kHoleyDouble,
    kSimd128,
    kCapturedObject, // Object captured by the escape analysis.
                        // The number of nested objects can be obtained
                        // with the DeferredObjectLength() method
                        // (the values of the nested objects follow
                        // this value in the depth-first order.)
    kDuplicatedObject, // Duplicated object of a deferred object.
    kCapturedStringConcat
  };
MaterializationState
enum v8::internal::TranslatedValue::MaterializationState : uint8_t [private]
Enumerator
kUninitialized
kAllocated
kFinished
Definition at line 100 of file translated-state.h.
                            : uint8_t {
    kUninitialized,
    kAllocated, // Storage for the object has been allocated (or
                 // enqueued for allocation).
    kFinished, // The object has been initialized (or enqueued for
                 // initialization).
  };
Constructor & Destructor Documentation
TranslatedValue()
v8::internal::TranslatedValue::TranslatedValue (TranslatedState * container, Kind kind) [inline], [private]
Definition at line 108 of file translated-state.h.
      : kind_(kind), container_(container) {}
Referenced by NewInvalid().
Member Function Documentation
double_value()
Float64 v8::internal::TranslatedValue::double_value () const [private]
Definition at line 535 of file translated-state.cc.
                                            {
  DCHECK(kDouble == kind() || kHoleyDouble == kind());
  return double_value_;
}
References v8::internal::DCHECK(), double_value_, kDouble, kHoleyDouble, and kind().
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), GetRawValue(), and GetValue().
float_value()
Float32 v8::internal::TranslatedValue::float_value () const [private]
Definition at line 530 of file translated-state.cc.
                                           {
  DCHECK_EQ(kFloat, kind());
  return float_value_;
}
References DCHECK_EQ, float_value_, kFloat, and kind().
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), GetRawValue(), and GetValue().
GetChildrenCount()
int v8::internal::TranslatedValue::GetChildrenCount () const [private]
Definition at line 805 of file translated-state.cc.
                                            {
  if (kind() == kCapturedObject) {
    return object_length();
  } else if (kind() == kCapturedStringConcat) {
    static constexpr int kLeft = 1, kRight = 1;
    return kLeft + kRight;
  } else {
    return 0;
  }
}
References kCapturedObject, kCapturedStringConcat, kind(), and object_length().
Referenced by v8::internal::TranslatedState::AllocateStorageFor(), v8::internal::TranslatedState::CreateNextTranslatedValue(), v8::internal::TranslatedState::EnsureCapturedObjectAllocatedAt(), v8::internal::TranslatedState::EnsureJSObjectAllocated(), v8::internal::TranslatedState::InitializeCapturedObjectAt(), v8::internal::TranslatedState::InitializeJSObjectAt(), v8::internal::TranslatedState::InitializeObjectWithTaggedFieldsAt(), and v8::internal::TranslatedState::SkipSlots().
GetRawValue()
Tagged< Object > v8::internal::TranslatedValue::GetRawValue () const
Definition at line 556 of file translated-state.cc.
                                                  {
  // If we have a value, return it.
  if (materialization_state() == kFinished) {
    int smi;
    if (IsHeapNumber(*storage_) &&
        DoubleToSmiInteger(Object::NumberValue(*storage_), &smi)) {
      return Smi::FromInt(smi);
    }
    return *storage_;
  }
  // Otherwise, do a best effort to get the value without allocation.
  switch (kind()) {
    case kTagged: {
      Tagged<Object> object = raw_literal();
      if (IsSlicedString(object)) {
        // If {object} is a sliced string of length smaller than
        // SlicedString::kMinLength, then trim the underlying SeqString and
        // return it. This assumes that such sliced strings are only built by
        // the fast string builder optimization of Turbofan's
        // StringBuilderOptimizer/EffectControlLinearizer.
        Tagged<SlicedString> string = Cast<SlicedString>(object);
        if (string->length() < SlicedString::kMinLength) {
          Tagged<String> backing_store = string->parent();
          CHECK(IsSeqString(backing_store));
          // Creating filler at the end of the backing store if needed.
          int string_size =
              IsSeqOneByteString(backing_store)
                  ? SeqOneByteString::SizeFor(backing_store->length())
                  : SeqTwoByteString::SizeFor(backing_store->length());
          int needed_size = IsSeqOneByteString(backing_store)
                                ? SeqOneByteString::SizeFor(string->length())
                                : SeqTwoByteString::SizeFor(string->length());
          if (needed_size < string_size) {
            Address new_end = backing_store.address() + needed_size;
            isolate()->heap()->CreateFillerObjectAt(
                new_end, (string_size - needed_size));
          }
          // Updating backing store's length, effectively trimming it.
          backing_store->set_length(string->length());
          // Zeroing the padding bytes of {backing_store}.
          SeqString::DataAndPaddingSizes sz =
              Cast<SeqString>(backing_store)->GetDataAndPaddingSizes();
          auto padding =
              reinterpret_cast<char*>(backing_store.address() + sz.data_size);
          for (int i = 0; i < sz.padding_size; ++i) {
            padding[i] = 0;
          }
          // Overwriting {string} with a filler, so that we don't leave around a
          // potentially-too-small SlicedString.
          isolate()->heap()->CreateFillerObjectAt(string.address(),
                                                  sizeof(SlicedString));
          return backing_store;
        }
      }
      return object;
    }
    case kInt32: {
      bool is_smi = Smi::IsValid(int32_value());
      if (is_smi) {
        return Smi::FromInt(int32_value());
      }
      break;
    }
    case kInt64: {
      bool is_smi = (int64_value() >= static_cast<int64_t>(Smi::kMinValue) &&
                     int64_value() <= static_cast<int64_t>(Smi::kMaxValue));
      if (is_smi) {
        return Smi::FromIntptr(static_cast<intptr_t>(int64_value()));
      }
      break;
    }
    case kInt64ToBigInt:
      // Return the arguments marker.
      break;
    case kUint32: {
      bool is_smi = (uint32_value() <= static_cast<uintptr_t>(Smi::kMaxValue));
      if (is_smi) {
        return Smi::FromInt(static_cast<int32_t>(uint32_value()));
      }
      break;
    }
    case kBoolBit: {
      if (uint32_value() == 0) {
        return ReadOnlyRoots(isolate()).false_value();
      } else {
        CHECK_EQ(1U, uint32_value());
        return ReadOnlyRoots(isolate()).true_value();
      }
    }
    case kFloat: {
      int smi;
      if (DoubleToSmiInteger(float_value().get_scalar(), &smi)) {
        return Smi::FromInt(smi);
      }
      break;
    }
    case kHoleyDouble:
      if (double_value().is_hole_nan()
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
          || double_value().is_undefined_nan()
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      ) {
        // Hole NaNs and undefined NaNs that made it to here represent the
        // undefined value.
        return ReadOnlyRoots(isolate()).undefined_value();
      }
      // If this is not the hole nan, then this is a normal double value, so
      // fall through to that.
      [[fallthrough]];
    case kDouble: {
      int smi;
      if (DoubleToSmiInteger(double_value().get_scalar(), &smi)) {
        return Smi::FromInt(smi);
      }
      break;
    }
    default:
      break;
  }
  // If we could not get the value without allocation, return the arguments
  // marker.
  return ReadOnlyRoots(isolate()).arguments_marker();
}
References v8::internal::Tagged< HeapObject >::address(), CHECK, CHECK_EQ, v8::internal::Heap::CreateFillerObjectAt(), v8::internal::SeqString::DataAndPaddingSizes::data_size, double_value(), v8::internal::DoubleToSmiInteger(), float_value(), v8::internal::Smi::FromInt(), v8::internal::Smi::FromIntptr(), v8::internal::Isolate::heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, int32_value(), int64_value(), isolate(), v8::internal::InstanceTypeChecker::IsSeqString(), v8::internal::InstanceTypeChecker::IsSlicedString(), v8::internal::Smi::IsValid(), kBoolBit, kDouble, kFinished, kFloat, kHoleyDouble, kind(), kInt32, kInt64, kInt64ToBigInt, v8::internal::Smi::kMaxValue, v8::internal::SlicedString::kMinLength, v8::internal::Smi::kMinValue, kTagged, kUint32, materialization_state(), v8::internal::Object::NumberValue(), v8::internal::SeqString::DataAndPaddingSizes::padding_size, raw_literal(), v8::internal::SeqOneByteString::SizeFor(), v8::internal::SeqTwoByteString::SizeFor(), storage_, v8::internal::string, and uint32_value().
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), GetSmiValue(), GetValue(), v8::internal::anonymous_namespace{deoptimized-frame-info.cc}::GetValueForDebugger(), v8::internal::FrameWriter::PushTranslatedValue(), and v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt().
GetSmiValue()
int v8::internal::TranslatedValue::GetSmiValue () const
Definition at line 2172 of file translated-state.cc.
                                       {
  Tagged<Object> value = GetRawValue();
  CHECK(IsSmi(value));
  return Cast<Smi>(value).value();
}
References CHECK, GetRawValue(), v8::internal::IsSmi(), and v8::internal::value.
GetValue()
Handle< Object > v8::internal::TranslatedValue::GetValue ()
Definition at line 702 of file translated-state.cc.
                                         {
  Handle<Object> value(GetRawValue(), isolate());
  if (materialization_state() == kFinished) return value;
  if (IsSmi(*value)) {
    // Even though stored as a Smi, this number might instead be needed as a
    // HeapNumber when materializing a JSObject with a field of HeapObject
    // representation. Since we don't have this information available here, we
    // just always allocate a HeapNumber and later extract the Smi again if we
    // don't need a HeapObject.
    set_initialized_storage(
        isolate()->factory()->NewHeapNumber(Object::NumberValue(*value)));
    return value;
  }
  if (*value != ReadOnlyRoots(isolate()).arguments_marker()) {
    set_initialized_storage(Cast<HeapObject>(value));
    return storage_;
  }
  // Otherwise we have to materialize.
  if (kind() == TranslatedValue::kCapturedObject ||
      kind() == TranslatedValue::kDuplicatedObject) {
    // We need to materialize the object (or possibly even object graphs).
    // To make the object verifier happy, we materialize in two steps.
    // 1. Allocate storage for reachable objects. This makes sure that for
    // each object we have allocated space on heap. The space will be
    // a byte array that will be later initialized, or a fully
    // initialized object if it is safe to allocate one that will
    // pass the verifier.
    container_->EnsureObjectAllocatedAt(this);
    // 2. Initialize the objects. If we have allocated only byte arrays
    // for some objects, we now overwrite the byte arrays with the
    // correct object fields. Note that this phase does not allocate
    // any new objects, so it does not trigger the object verifier.
    return container_->InitializeObjectAt(this);
  }
  if (kind() == TranslatedValue::kCapturedStringConcat) {
    // We need to materialize the string concatenation.
    return container_->ResolveStringConcat(this);
  }
  double number = 0;
  Handle<HeapObject> heap_object;
  switch (kind()) {
    case TranslatedValue::kInt32:
      number = int32_value();
      heap_object = isolate()->factory()->NewHeapNumber(number);
      break;
    case TranslatedValue::kInt64:
      number = int64_value();
      heap_object = isolate()->factory()->NewHeapNumber(number);
      break;
    case TranslatedValue::kInt64ToBigInt:
      heap_object = BigInt::FromInt64(isolate(), int64_value());
      break;
    case TranslatedValue::kUint64ToBigInt:
      heap_object = BigInt::FromUint64(isolate(), uint64_value());
      break;
    case TranslatedValue::kUint32:
      number = uint32_value();
      heap_object = isolate()->factory()->NewHeapNumber(number);
      break;
    case TranslatedValue::kFloat:
      number = float_value().get_scalar();
      heap_object = isolate()->factory()->NewHeapNumber(number);
      break;
    case TranslatedValue::kDouble:
    // We shouldn't have hole values by now, so treat holey double as normal
    // doubles.
    case TranslatedValue::kHoleyDouble:
      number = double_value().get_scalar();
      heap_object = isolate()->factory()->NewHeapNumber(number);
      break;
    default:
      UNREACHABLE();
  }
  DCHECK(!IsSmiDouble(number) || kind() == TranslatedValue::kInt64ToBigInt ||
         kind() == TranslatedValue::kUint64ToBigInt);
  set_initialized_storage(heap_object);
  return storage_;
}
References container_, v8::internal::DCHECK(), double_value(), v8::internal::TranslatedState::EnsureObjectAllocatedAt(), v8::internal::Isolate::factory(), float_value(), v8::internal::BigInt::FromInt64(), v8::internal::BigInt::FromUint64(), v8::internal::Float32::get_scalar(), v8::internal::Float64::get_scalar(), GetRawValue(), v8::internal::TranslatedState::InitializeObjectAt(), int32_value(), int64_value(), isolate(), v8::internal::IsSmi(), v8::internal::IsSmiDouble(), kCapturedObject, kCapturedStringConcat, kDouble, kDuplicatedObject, kFinished, kFloat, kHoleyDouble, kind(), kInt32, kInt64, kInt64ToBigInt, kUint32, kUint64ToBigInt, materialization_state(), v8::internal::FactoryBase< Impl >::NewHeapNumber(), v8::internal::Object::NumberValue(), v8::internal::TranslatedState::ResolveStringConcat(), set_initialized_storage(), storage_, uint32_value(), uint64_value(), v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{accessors.cc}::ArgumentsFromDeoptInfo(), v8::internal::DeoptimizedFrameInfo::DeoptimizedFrameInfo(), v8::internal::TranslatedState::EnsureCapturedObjectAllocatedAt(), v8::internal::TranslatedState::EnsureChildrenAllocated(), v8::internal::anonymous_namespace{runtime-scopes.cc}::GetCallerArguments(), v8::internal::TranslatedState::GetValueAndAdvance(), v8::internal::anonymous_namespace{deoptimized-frame-info.cc}::GetValueForDebugger(), v8::internal::TranslatedState::InitializeJSObjectAt(), v8::internal::TranslatedState::InitializeObjectWithTaggedFieldsAt(), v8::internal::FrameFunctionIterator::MaterializeFunction(), ReplaceElementsArrayWithCopy(), v8::internal::TranslatedState::ResolveStringConcat(), and v8::internal::OptimizedJSFrame::Summarize().
Handlify()
void v8::internal::TranslatedValue::Handlify () [private]
Definition at line 849 of file translated-state.cc.
                               {
  if (kind() == kTagged && IsHeapObject(raw_literal())) {
    set_initialized_storage(
        Handle<HeapObject>(Cast<HeapObject>(raw_literal()), isolate()));
    raw_literal_ = Tagged<Object>();
  }
}
References v8::internal::IsHeapObject(), isolate(), kind(), kTagged, raw_literal(), raw_literal_, set_initialized_storage(), and v8::internal::Tagged< Object >.
int32_value()
int32_t v8::internal::TranslatedValue::int32_value () const [private]
Definition at line 510 of file translated-state.cc.
                                           {
  DCHECK_EQ(kInt32, kind());
  return int32_value_;
}
References DCHECK_EQ, int32_value_, kind(), and kInt32.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), GetRawValue(), and GetValue().
int64_value()
int64_t v8::internal::TranslatedValue::int64_value () const [private]
Definition at line 515 of file translated-state.cc.
                                           {
  DCHECK(kInt64 == kind() || kInt64ToBigInt == kind());
  return int64_value_;
}
References v8::internal::DCHECK(), int64_value_, kind(), kInt64, and kInt64ToBigInt.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), GetRawValue(), and GetValue().
IsMaterializableByDebugger()
bool v8::internal::TranslatedValue::IsMaterializableByDebugger () const
Definition at line 800 of file translated-state.cc.
                                                       {
  // At the moment, we only allow materialization of doubles.
  return (kind() == kDouble || kind() == kHoleyDouble);
}
References kDouble, kHoleyDouble, and kind().
Referenced by v8::internal::anonymous_namespace{deoptimized-frame-info.cc}::GetValueForDebugger().
IsMaterializedObject()
bool v8::internal::TranslatedValue::IsMaterializedObject () const
Definition at line 789 of file translated-state.cc.
                                                 {
  switch (kind()) {
    case kCapturedObject:
    case kDuplicatedObject:
    case kCapturedStringConcat:
      return true;
    default:
      return false;
  }
}
References kCapturedObject, kCapturedStringConcat, kDuplicatedObject, and kind().
Referenced by v8::internal::anonymous_namespace{accessors.cc}::ArgumentsFromDeoptInfo(), v8::internal::anonymous_namespace{runtime-scopes.cc}::GetCallerArguments(), v8::internal::FrameFunctionIterator::MaterializeFunction(), v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt(), v8::internal::OptimizedJSFrame::Summarize(), and v8::internal::TranslatedState::UpdateFromPreviouslyMaterializedObjects().
isolate()
Isolate * v8::internal::TranslatedValue::isolate () const [private]
Definition at line 503 of file translated-state.cc.
{ return container_->isolate(); }
References container_, and v8::internal::TranslatedState::isolate().
Referenced by GetRawValue(), GetValue(), Handlify(), and ReplaceElementsArrayWithCopy().
kind()
Kind v8::internal::TranslatedValue::kind () const [inline], [private]
Definition at line 110 of file translated-state.h.
{ return kind_; }
References kind_.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), double_value(), v8::internal::TranslatedState::EnsureCapturedObjectAllocatedAt(), v8::internal::TranslatedState::EnsureChildrenAllocated(), v8::internal::TranslatedState::EnsureObjectAllocatedAt(), float_value(), GetChildrenCount(), GetRawValue(), v8::internal::TranslatedState::GetResolvedSlot(), GetValue(), Handlify(), v8::internal::TranslatedState::InitializeCapturedObjectAt(), v8::internal::TranslatedState::InitializeJSObjectAt(), int32_value(), int64_value(), IsMaterializableByDebugger(), IsMaterializedObject(), object_index(), object_length(), raw_literal(), ReplaceElementsArrayWithCopy(), v8::internal::TranslatedState::ResolveCapturedObject(), simd_value(), v8::internal::TranslatedState::SkipSlots(), uint32_value(), uint64_value(), v8::internal::TranslatedState::UpdateFromPreviouslyMaterializedObjects(), and v8::internal::TranslatedState::VerifyMaterializedObjects().
mark_allocated()
void v8::internal::TranslatedValue::mark_allocated () [inline], [private]
Definition at line 144 of file translated-state.h.
{ materialization_state_ = kAllocated; }
References kAllocated, and materialization_state_.
Referenced by v8::internal::TranslatedState::EnsureChildrenAllocated(), v8::internal::TranslatedState::EnsureObjectAllocatedAt(), and v8::internal::TranslatedState::EnsurePropertiesAllocatedAndMarked().
mark_finished()
void v8::internal::TranslatedValue::mark_finished () [inline], [private]
Definition at line 143 of file translated-state.h.
{ materialization_state_ = kFinished; }
References kFinished, and materialization_state_.
Referenced by v8::internal::TranslatedState::InitializeCapturedObjectAt(), and v8::internal::TranslatedState::InitializeObjectAt().
materialization_state()
MaterializationState v8::internal::TranslatedValue::materialization_state () const [inline], [private]
Definition at line 111 of file translated-state.h.
                                                     {
    return materialization_state_;
  }
References materialization_state_.
Referenced by v8::internal::TranslatedState::EnsureCapturedObjectAllocatedAt(), v8::internal::TranslatedState::EnsureChildrenAllocated(), v8::internal::TranslatedState::EnsureObjectAllocatedAt(), v8::internal::TranslatedState::EnsurePropertiesAllocatedAndMarked(), GetRawValue(), v8::internal::TranslatedState::GetResolvedSlot(), GetValue(), v8::internal::TranslatedState::InitializeCapturedObjectAt(), v8::internal::TranslatedState::InitializeObjectAt(), ReplaceElementsArrayWithCopy(), v8::internal::TranslatedState::ResolveStringConcat(), set_initialized_storage(), storage(), and v8::internal::TranslatedState::VerifyMaterializedObjects().
NewBool()
TranslatedValue v8::internal::TranslatedValue::NewBool (TranslatedState * container, uint32_t value) [static], [private]
Definition at line 483 of file translated-state.cc.
                                                         {
  TranslatedValue slot(container, kBoolBit);
  slot.uint32_value_ = value;
  return slot;
}
References kBoolBit, uint32_value_, and v8::internal::value.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue().
NewDeferredObject()
TranslatedValue v8::internal::TranslatedValue::NewDeferredObject (TranslatedState * container, int length, int object_index) [static], [private]
Definition at line 379 of file translated-state.cc.
                                                                     {
  TranslatedValue slot(container, kCapturedObject);
  slot.materialization_info_ = {object_index, length};
  return slot;
}
References kCapturedObject, v8::internal::length, materialization_info_, and object_index().
Referenced by v8::internal::TranslatedState::CreateArgumentsElementsTranslatedValues(), and v8::internal::TranslatedState::CreateNextTranslatedValue().
NewDouble()
TranslatedValue v8::internal::TranslatedValue::NewDouble (TranslatedState * container, Float64 value) [static], [private]
Definition at line 412 of file translated-state.cc.
                                                          {
  TranslatedValue slot(container, kDouble);
  slot.double_value_ = value;
  return slot;
}
References double_value_, kDouble, and v8::internal::value.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), and v8::internal::DeoptimizationLiteralProvider::Get().
NewDuplicateObject()
TranslatedValue v8::internal::TranslatedValue::NewDuplicateObject (TranslatedState * container, int id) [static], [private]
Definition at line 388 of file translated-state.cc.
                                                            {
  TranslatedValue slot(container, kDuplicatedObject);
  slot.materialization_info_ = {id, -1};
  return slot;
}
References kDuplicatedObject, and materialization_info_.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue().
NewFloat()
TranslatedValue v8::internal::TranslatedValue::NewFloat (TranslatedState * container, Float32 value) [static], [private]
Definition at line 404 of file translated-state.cc.
                                                         {
  TranslatedValue slot(container, kFloat);
  slot.float_value_ = value;
  return slot;
}
References float_value_, kFloat, and v8::internal::value.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), and v8::internal::DeoptimizationLiteralProvider::Get().
NewHoleyDouble()
TranslatedValue v8::internal::TranslatedValue::NewHoleyDouble (TranslatedState * container, Float64 value) [static], [private]
Definition at line 420 of file translated-state.cc.
                                                               {
  TranslatedValue slot(container, kHoleyDouble);
  slot.double_value_ = value;
  return slot;
}
References double_value_, kHoleyDouble, and v8::internal::value.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue().
NewInt32()
TranslatedValue v8::internal::TranslatedValue::NewInt32 (TranslatedState * container, int32_t value) [static], [private]
Definition at line 436 of file translated-state.cc.
                                                         {
  TranslatedValue slot(container, kInt32);
  slot.int32_value_ = value;
  return slot;
}
References int32_value_, kInt32, and v8::internal::value.
Referenced by v8::internal::TranslatedState::CreateArgumentsElementsTranslatedValues(), v8::internal::TranslatedState::CreateNextTranslatedValue(), and v8::internal::DeoptimizationLiteralProvider::Get().
NewInt64()
TranslatedValue v8::internal::TranslatedValue::NewInt64 (TranslatedState * container, int64_t value) [static], [private]
Definition at line 444 of file translated-state.cc.
                                                         {
  TranslatedValue slot(container, kInt64);
  slot.int64_value_ = value;
  return slot;
}
References int64_value_, kInt64, and v8::internal::value.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), and v8::internal::DeoptimizationLiteralProvider::Get().
NewInt64ToBigInt()
TranslatedValue v8::internal::TranslatedValue::NewInt64ToBigInt (TranslatedState * container, int64_t value) [static], [private]
Definition at line 452 of file translated-state.cc.
                                                                 {
  TranslatedValue slot(container, kInt64ToBigInt);
  slot.int64_value_ = value;
  return slot;
}
References int64_value_, kInt64ToBigInt, and v8::internal::value.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue().
NewInvalid()
TranslatedValue v8::internal::TranslatedValue::NewInvalid (TranslatedState * container) [static], [private]
Definition at line 499 of file translated-state.cc.
                                                                      {
  return TranslatedValue(container, kInvalid);
}
References kInvalid, and TranslatedValue().
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue().
NewSimd128()
TranslatedValue v8::internal::TranslatedValue::NewSimd128 (TranslatedState * container, Simd128 value) [static], [private]
Definition at line 428 of file translated-state.cc.
                                                           {
  TranslatedValue slot(container, kSimd128);
  slot.simd128_value_ = value;
  return slot;
}
References kSimd128, simd128_value_, and v8::internal::value.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue().
NewStringConcat()
TranslatedValue v8::internal::TranslatedValue::NewStringConcat (TranslatedState * container, int id) [static], [private]
Definition at line 396 of file translated-state.cc.
                                                         {
  TranslatedValue slot(container, kCapturedStringConcat);
  slot.materialization_info_ = {id, -1};
  return slot;
}
References kCapturedStringConcat, and materialization_info_.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue().
NewTagged()
TranslatedValue v8::internal::TranslatedValue::NewTagged (TranslatedState * container, Tagged< Object > literal) [static], [private]
Definition at line 491 of file translated-state.cc.
                                                                   {
  TranslatedValue slot(container, kTagged);
  slot.raw_literal_ = literal;
  return slot;
}
References kTagged, and raw_literal_.
Referenced by v8::internal::TranslatedState::CreateArgumentsElementsTranslatedValues(), v8::internal::TranslatedState::CreateNextTranslatedValue(), and v8::internal::DeoptimizationLiteralProvider::Get().
NewUint32()
TranslatedValue v8::internal::TranslatedValue::NewUint32 (TranslatedState * container, uint32_t value) [static], [private]
Definition at line 468 of file translated-state.cc.
                                                           {
  TranslatedValue slot(container, kUint32);
  slot.uint32_value_ = value;
  return slot;
}
References kUint32, uint32_value_, and v8::internal::value.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue().
NewUint64()
TranslatedValue v8::internal::TranslatedValue::NewUint64 (TranslatedState * container, uint64_t value) [static], [private]
Definition at line 475 of file translated-state.cc.
                                                           {
  TranslatedValue slot(container, kUint64);
  slot.uint64_value_ = value;
  return slot;
}
References kUint64, uint64_value_, and v8::internal::value.
NewUint64ToBigInt()
TranslatedValue v8::internal::TranslatedValue::NewUint64ToBigInt (TranslatedState * container, uint64_t value) [static], [private]
Definition at line 460 of file translated-state.cc.
                                                                   {
  TranslatedValue slot(container, kUint64ToBigInt);
  slot.uint64_value_ = value;
  return slot;
}
References kUint64ToBigInt, uint64_value_, and v8::internal::value.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue().
object_index()
int v8::internal::TranslatedValue::object_index () const [private]
Definition at line 550 of file translated-state.cc.
                                        {
  DCHECK(kind() == kCapturedObject || kind() == kDuplicatedObject ||
         kind() == kCapturedStringConcat);
  return materialization_info_.id_;
}
References v8::internal::DCHECK(), v8::internal::TranslatedValue::MaterializedObjectInfo::id_, kCapturedObject, kCapturedStringConcat, kDuplicatedObject, kind(), and materialization_info_.
Referenced by v8::internal::TranslatedState::EnsureChildrenAllocated(), v8::internal::TranslatedState::EnsureObjectAllocatedAt(), v8::internal::TranslatedState::InitializeCapturedObjectAt(), v8::internal::TranslatedState::InitializeObjectAt(), NewDeferredObject(), v8::internal::TranslatedState::ResolveCapturedObject(), v8::internal::TranslatedState::ResolveStringConcat(), v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt(), and v8::internal::TranslatedState::VerifyMaterializedObjects().
object_length()
int v8::internal::TranslatedValue::object_length () const [private]
Definition at line 545 of file translated-state.cc.
                                         {
  DCHECK_EQ(kind(), kCapturedObject);
  return materialization_info_.length_;
}
References DCHECK_EQ, kCapturedObject, kind(), v8::internal::TranslatedValue::MaterializedObjectInfo::length_, and materialization_info_.
Referenced by GetChildrenCount().
raw_literal()
Tagged< Object > v8::internal::TranslatedValue::raw_literal () const [private]
Definition at line 505 of file translated-state.cc.
                                                  {
  DCHECK_EQ(kTagged, kind());
  return raw_literal_;
}
References DCHECK_EQ, kind(), kTagged, and raw_literal_.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), GetRawValue(), and Handlify().
ReplaceElementsArrayWithCopy()
void v8::internal::TranslatedValue::ReplaceElementsArrayWithCopy () [private]
Definition at line 2375 of file translated-state.cc.
                                                   {
  DCHECK_EQ(kind(), TranslatedValue::kTagged);
  DCHECK_EQ(materialization_state(), TranslatedValue::kFinished);
  auto elements = Cast<FixedArrayBase>(GetValue());
  DCHECK(IsFixedArray(*elements) || IsFixedDoubleArray(*elements));
  if (IsFixedDoubleArray(*elements)) {
    DCHECK(!elements->IsCowArray());
    set_storage(isolate()->factory()->CopyFixedDoubleArray(
        Cast<FixedDoubleArray>(elements)));
  } else if (!elements->IsCowArray()) {
    set_storage(
        isolate()->factory()->CopyFixedArray(Cast<FixedArray>(elements)));
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, GetValue(), isolate(), kFinished, kind(), kTagged, materialization_state(), and set_storage().
Referenced by v8::internal::TranslatedState::EnsureCapturedObjectAllocatedAt().
set_initialized_storage()
void v8::internal::TranslatedValue::set_initialized_storage (Handle< HeapObject > storage) [private]
Definition at line 696 of file translated-state.cc.
                                                                        {
  DCHECK_EQ(kUninitialized, materialization_state());
  storage_ = storage;
  materialization_state_ = kFinished;
}
References DCHECK_EQ, kFinished, kUninitialized, materialization_state(), materialization_state_, storage(), and storage_.
Referenced by GetValue(), Handlify(), v8::internal::TranslatedState::ResolveStringConcat(), and v8::internal::TranslatedState::UpdateFromPreviouslyMaterializedObjects().
set_storage()
void v8::internal::TranslatedValue::set_storage (Handle< HeapObject > storage) [inline], [private]
Definition at line 141 of file translated-state.h.
{ storage_ = storage; }
References storage(), and storage_.
Referenced by v8::internal::TranslatedState::EnsureCapturedObjectAllocatedAt(), v8::internal::TranslatedState::EnsureJSObjectAllocated(), v8::internal::TranslatedState::EnsurePropertiesAllocatedAndMarked(), v8::internal::TranslatedState::MaterializeFixedDoubleArray(), v8::internal::TranslatedState::MaterializeHeapNumber(), and ReplaceElementsArrayWithCopy().
simd_value()
Simd128 v8::internal::TranslatedValue::simd_value () const [private]
Definition at line 540 of file translated-state.cc.
                                          {
  CHECK_EQ(kind(), kSimd128);
  return simd128_value_;
}
References CHECK_EQ, kind(), kSimd128, and simd128_value_.
storage()
Handle<HeapObject> v8::internal::TranslatedValue::storage () [inline], [private]
Definition at line 146 of file translated-state.h.
                               {
    DCHECK_NE(materialization_state(), kUninitialized);
    return storage_;
  }
References DCHECK_NE, kUninitialized, materialization_state(), and storage_.
Referenced by v8::internal::TranslatedState::InitializeJSObjectAt(), v8::internal::TranslatedState::InitializeObjectAt(), v8::internal::TranslatedState::InitializeObjectWithTaggedFieldsAt(), v8::internal::TranslatedState::ResolveStringConcat(), set_initialized_storage(), set_storage(), and v8::internal::TranslatedState::VerifyMaterializedObjects().
string_concat_index()
int v8::internal::TranslatedValue::string_concat_index () const [private]
uint32_value()
uint32_t v8::internal::TranslatedValue::uint32_value () const [private]
Definition at line 525 of file translated-state.cc.
                                             {
  DCHECK(kind() == kUint32 || kind() == kBoolBit);
  return uint32_value_;
}
References v8::internal::DCHECK(), kBoolBit, kind(), kUint32, and uint32_value_.
Referenced by GetRawValue(), and GetValue().
uint64_value()
uint64_t v8::internal::TranslatedValue::uint64_value () const [private]
Definition at line 520 of file translated-state.cc.
                                             {
  DCHECK(kUint64ToBigInt == kind());
  return uint64_value_;
}
References v8::internal::DCHECK(), kind(), kUint64ToBigInt, and uint64_value_.
Referenced by GetValue().
Friends And Related Function Documentation
DeoptimizationLiteralProvider
friend class DeoptimizationLiteralProvider [friend]
Definition at line 75 of file translated-state.h.
Deoptimizer
friend class Deoptimizer [friend]
Definition at line 74 of file translated-state.h.
TranslatedFrame
friend class TranslatedFrame [friend]
Definition at line 73 of file translated-state.h.
TranslatedState
friend class TranslatedState [friend]
Definition at line 72 of file translated-state.h.
Member Data Documentation
union { ... } [private]
container_
TranslatedState* v8::internal::TranslatedValue::container_ [private]
Definition at line 155 of file translated-state.h.
Referenced by GetValue(), and isolate().
double_value_
Float64 v8::internal::TranslatedValue::double_value_
Definition at line 182 of file translated-state.h.
Referenced by double_value(), NewDouble(), and NewHoleyDouble().
float_value_
Float32 v8::internal::TranslatedValue::float_value_
Definition at line 180 of file translated-state.h.
Referenced by float_value(), and NewFloat().
int32_value_
int32_t v8::internal::TranslatedValue::int32_value_
Definition at line 174 of file translated-state.h.
Referenced by int32_value(), and NewInt32().
int64_value_
int64_t v8::internal::TranslatedValue::int64_value_
Definition at line 178 of file translated-state.h.
Referenced by int64_value(), NewInt64(), and NewInt64ToBigInt().
kind_
Kind v8::internal::TranslatedValue::kind_ [private]
Definition at line 153 of file translated-state.h.
Referenced by kind().
materialization_info_
MaterializedObjectInfo v8::internal::TranslatedValue::materialization_info_
Definition at line 184 of file translated-state.h.
Referenced by NewDeferredObject(), NewDuplicateObject(), NewStringConcat(), object_index(), and object_length().
materialization_state_
MaterializationState v8::internal::TranslatedValue::materialization_state_ = kUninitialized [private]
Definition at line 154 of file translated-state.h.
Referenced by mark_allocated(), mark_finished(), materialization_state(), and set_initialized_storage().
raw_literal_
Tagged<Object> v8::internal::TranslatedValue::raw_literal_
Definition at line 170 of file translated-state.h.
Referenced by Handlify(), NewTagged(), and raw_literal().
simd128_value_
Simd128 v8::internal::TranslatedValue::simd128_value_
Definition at line 186 of file translated-state.h.
Referenced by NewSimd128(), and simd_value().
storage_
Handle<HeapObject> v8::internal::TranslatedValue::storage_ [private]
Definition at line 159 of file translated-state.h.
Referenced by GetRawValue(), GetValue(), v8::internal::TranslatedState::InitializeJSObjectAt(), v8::internal::TranslatedState::InitializeObjectWithTaggedFieldsAt(), set_initialized_storage(), set_storage(), and storage().
uint32_value_
uint32_t v8::internal::TranslatedValue::uint32_value_
Definition at line 172 of file translated-state.h.
Referenced by NewBool(), NewUint32(), and uint32_value().
uint64_value_
uint64_t v8::internal::TranslatedValue::uint64_value_
Definition at line 176 of file translated-state.h.
Referenced by NewUint64(), NewUint64ToBigInt(), and uint64_value().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/deoptimizer/translated-state.h
/mnt/V8SourceCode/src/deoptimizer/translated-state.cc