v8::internal::compiler::turboshaft::OptionalV< T > Class Template Reference
#include <index.h>
Public Types
using type = T
Public Member Functions
constexpr OptionalV ()
template<typename U >
requires implicitly_constructible_from< U > OptionalV (OptionalV< U > index)
template<typename U >
requires implicitly_constructible_from< U > OptionalV (V< U > index)
constexpr V< T > value () const
constexpr V< T > value_or_invalid () const
template<typename U >
requires (std::is_same_v< U, OptionalOpIndex >||std::is_same_v< U, OpIndex >) OptionalV(U index)
Static Public Member Functions
static OptionalV Nullopt ()
template<typename U >
static OptionalV< T > Cast (OptionalV< U > index)
static OptionalV< T > Cast (OptionalOpIndex index)
Static Public Attributes
static constexpr auto rep = v_traits<type>::rep
Static Private Attributes
template<typename U >
constexpr static bool implicitly_constructible_from
Additional Inherited Members
Detailed Description
template<typename T>
class v8::internal::compiler::turboshaft::OptionalV< T >
Definition at line 659 of file index.h.
Member Typedef Documentation
type
template<typename T >
using v8::internal::compiler::turboshaft::OptionalV< T >::type = T
Definition at line 669 of file index.h.
Constructor & Destructor Documentation
OptionalV() [1/3]
template<typename T >
constexpr v8::internal::compiler::turboshaft::OptionalV< T >::OptionalV () [inline], [constexpr]
Definition at line 671 of file index.h.
: OptionalOpIndex() {}
Referenced by v8::internal::compiler::turboshaft::OptionalV< T >::Nullopt().
OptionalV() [2/3]
template<typename T >
template<typename U >
requires implicitly_constructible_from<U> v8::internal::compiler::turboshaft::OptionalV< T >::OptionalV (OptionalV< U > index) [inline]
Definition at line 675 of file index.h.
      : OptionalOpIndex(index) {}
OptionalV() [3/3]
template<typename T >
template<typename U >
requires implicitly_constructible_from<U> v8::internal::compiler::turboshaft::OptionalV< T >::OptionalV (V< U > index) [inline]
Definition at line 679 of file index.h.
: OptionalOpIndex(index) {} // NOLINT(runtime/explicit)
Member Function Documentation
Cast() [1/2]
template<typename T >
static OptionalV<T> v8::internal::compiler::turboshaft::OptionalV< T >::Cast (OptionalOpIndex index) [inline], [static]
Definition at line 695 of file index.h.
                                                  {
    return OptionalV<T>(index);
  }
References v8::internal::index.
Cast() [2/2]
template<typename T >
template<typename U >
static OptionalV<T> v8::internal::compiler::turboshaft::OptionalV< T >::Cast (OptionalV< U > index) [inline], [static]
Definition at line 692 of file index.h.
                                               {
    return OptionalV<T>(OptionalOpIndex{index});
  }
References v8::internal::index.
Nullopt()
template<typename T >
static OptionalV v8::internal::compiler::turboshaft::OptionalV< T >::Nullopt () [inline], [static]
Definition at line 681 of file index.h.
{ return OptionalV(OptionalOpIndex::Nullopt()); }
References v8::internal::compiler::turboshaft::OptionalOpIndex::Nullopt(), and v8::internal::compiler::turboshaft::OptionalV< T >::OptionalV().
Referenced by v8::internal::compiler::turboshaft::JSStackCheckOp::frame_state(), v8::internal::compiler::turboshaft::CallOp::frame_state(), v8::internal::compiler::turboshaft::Sequence< T >::IsEnd(), v8::internal::compiler::turboshaft::CompareMapsOp::map(), v8::internal::compiler::turboshaft::CheckMapsOp::map(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::TailCall().
requires()
template<typename T >
template<typename U >
v8::internal::compiler::turboshaft::OptionalV< T >::requires (std::is_same_v< U, OptionalOpIndex >||std::is_same_v< U, OpIndex >) [inline]
Definition at line 705 of file index.h.
                     : OptionalOpIndex(index) {} // NOLINT(runtime/explicit)
value()
template<typename T >
constexpr V<T> v8::internal::compiler::turboshaft::OptionalV< T >::value () const [inline], [constexpr]
Definition at line 683 of file index.h.
                               {
    DCHECK(has_value());
    return V<T>::Cast(OptionalOpIndex::value());
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::OptionalOpIndex::has_value(), and v8::internal::compiler::turboshaft::OptionalOpIndex::value().
Referenced by v8::internal::compiler::turboshaft::AtomicWord32PairOp::AtomicWord32PairOp(), v8::internal::compiler::turboshaft::CallOp::CallOp(), v8::internal::compiler::turboshaft::CheckMapsOp::CheckMapsOp(), v8::internal::compiler::turboshaft::CompareMapsOp::CompareMapsOp(), v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_Foreach(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertUntaggedToJSPrimitive(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::IncreaseOffset(), v8::internal::compiler::turboshaft::Zip< Iterables >::IsEnd(), v8::internal::compiler::turboshaft::JSStackCheckOp::JSStackCheckOp(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt().
value_or_invalid()
template<typename T >
constexpr V<T> v8::internal::compiler::turboshaft::OptionalV< T >::value_or_invalid () const [inline], [constexpr]
Definition at line 687 of file index.h.
                                          {
    return V<T>::Cast(OptionalOpIndex::value_or_invalid());
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), and v8::internal::compiler::turboshaft::OptionalOpIndex::value_or_invalid().
Member Data Documentation
implicitly_constructible_from
template<typename T >
template<typename U >
constexpr static bool v8::internal::compiler::turboshaft::OptionalV< T >::implicitly_constructible_from [static], [constexpr], [private]
Initial value:
=
      v_traits<T>::template implicitly_constructible_from<U>::value
Definition at line 665 of file index.h.
rep
template<typename T >
constexpr auto v8::internal::compiler::turboshaft::OptionalV< T >::rep = v_traits<type>::rep [static], [constexpr]
Definition at line 670 of file index.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/index.h