v8::internal::compiler::VariableTracker Class Reference
Classes
class Scope
class State
Public Member Functions
VariableTracker (JSGraph *graph, EffectGraphReducer *reducer, Zone *zone)
VariableTracker (const VariableTracker &)=delete
VariableTracker & operator= (const VariableTracker &)=delete
Variable NewVariable ()
Node * Get (Variable var, Node *effect)
Zone * zone ()
Private Member Functions
State MergeInputs (Node *effect_phi)
Private Attributes
Zone * zone_
JSGraph * graph_
SparseSidetable< State > table_
ZoneVector< Node * > buffer_
EffectGraphReducer * reducer_
int next_variable_ = 0
TickCounter *const tick_counter_
Detailed Description
Definition at line 98 of file escape-analysis.cc.
Constructor & Destructor Documentation
VariableTracker() [1/2]
v8::internal::compiler::VariableTracker::VariableTracker (JSGraph * graph, EffectGraphReducer * reducer, Zone * zone)
Definition at line 402 of file escape-analysis.cc.
    : zone_(zone),
      graph_(graph),
      table_(zone, State(zone)),
      buffer_(zone),
      reducer_(reducer),
      tick_counter_(reducer->tick_counter()) {}
VariableTracker() [2/2]
v8::internal::compiler::VariableTracker::VariableTracker (const VariableTracker &) [delete]
Member Function Documentation
Get()
Node* v8::internal::compiler::VariableTracker::Get (Variable var, Node * effect) [inline]
Definition at line 128 of file escape-analysis.cc.
{ return table_.Get(effect).Get(var); }
References table_.
MergeInputs()
VariableTracker::State v8::internal::compiler::VariableTracker::MergeInputs (Node * effect_phi) [private]
Definition at line 439 of file escape-analysis.cc.
                                                                  {
  // A variable that is mapped to [nullptr] was not assigned a value on every
  // execution path to the current effect phi. Relying on the invariant that
  // every variable is initialized (at least with a sentinel like the Dead
  // node), this means that the variable initialization does not dominate the
  // current point. So for loop effect phis, we can keep nullptr for a variable
  // as long as the first input of the loop has nullptr for this variable. For
  // non-loop effect phis, we can even keep it nullptr as long as any input has
  // nullptr.
  DCHECK_EQ(IrOpcode::kEffectPhi, effect_phi->opcode());
  int arity = effect_phi->op()->EffectInputCount();
  Node* control = NodeProperties::GetControlInput(effect_phi, 0);
  TRACE("control: %s#%d\n", control->op()->mnemonic(), control->id());
  bool is_loop = control->opcode() == IrOpcode::kLoop;
  buffer_.reserve(arity + 1);
  State first_input = table_.Get(NodeProperties::GetEffectInput(effect_phi, 0));
  State result = first_input;
  for (std::pair<Variable, Node*> var_value : first_input) {
    tick_counter_->TickAndMaybeEnterSafepoint();
    if (Node* value = var_value.second) {
      Variable var = var_value.first;
      TRACE("var %i:\n", var.id_);
      buffer_.clear();
      buffer_.push_back(value);
      bool identical_inputs = true;
      int num_defined_inputs = 1;
      TRACE(" input 0: %s#%d\n", value->op()->mnemonic(), value->id());
      for (int i = 1; i < arity; ++i) {
        Node* next_value =
            table_.Get(NodeProperties::GetEffectInput(effect_phi, i)).Get(var);
        if (next_value != value) identical_inputs = false;
        if (next_value != nullptr) {
          num_defined_inputs++;
          TRACE(" input %i: %s#%d\n", i, next_value->op()->mnemonic(),
                next_value->id());
        } else {
          TRACE(" input %i: nullptr\n", i);
        }
        buffer_.push_back(next_value);
      }
      Node* old_value = table_.Get(effect_phi).Get(var);
      if (old_value) {
        TRACE(" old: %s#%d\n", old_value->op()->mnemonic(), old_value->id());
      } else {
        TRACE(" old: nullptr\n");
      }
      // Reuse a previously created phi node if possible.
      if (old_value && old_value->opcode() == IrOpcode::kPhi &&
          NodeProperties::GetControlInput(old_value, 0) == control) {
        // Since a phi node can never dominate its control node,
        // [old_value] cannot originate from the inputs. Thus [old_value]
        // must have been created by a previous reduction of this [effect_phi].
        for (int i = 0; i < arity; ++i) {
          Node* old_input = NodeProperties::GetValueInput(old_value, i);
          Node* new_input = buffer_[i] ? buffer_[i] : graph_->Dead();
          if (old_input != new_input) {
            NodeProperties::ReplaceValueInput(old_value, new_input, i);
            reducer_->Revisit(old_value);
          }
        }
        result.Set(var, old_value);
      } else {
        if (num_defined_inputs == 1 && is_loop) {
          // For loop effect phis, the variable initialization dominates iff it
          // dominates the first input.
          DCHECK_EQ(2, arity);
          DCHECK_EQ(value, buffer_[0]);
          result.Set(var, value);
        } else if (num_defined_inputs < arity) {
          // If the variable is undefined on some input of this non-loop effect
          // phi, then its initialization does not dominate this point.
          result.Set(var, nullptr);
        } else {
          DCHECK_EQ(num_defined_inputs, arity);
          // We only create a phi if the values are different.
          if (identical_inputs) {
            result.Set(var, value);
          } else {
            TRACE("Creating new phi\n");
            buffer_.push_back(control);
            Node* phi = graph_->graph()->NewNode(
                graph_->common()->Phi(MachineRepresentation::kTagged, arity),
                arity + 1, &buffer_.front());
            // TODO(turbofan): Computing precise types here is tricky, because
            // of the necessary revisitations. If we really need this, we should
            // probably do it afterwards.
            NodeProperties::SetType(phi, Type::Any());
            reducer_->AddRoot(phi);
            result.Set(var, phi);
          }
        }
      }
#ifdef DEBUG
      if (Node* result_node = result.Get(var)) {
        TRACE(" result: %s#%d\n", result_node->op()->mnemonic(),
              result_node->id());
      } else {
        TRACE(" result: nullptr\n");
      }
#endif
    }
  }
  return result;
}
References v8::internal::compiler::EffectGraphReducer::AddRoot(), v8::internal::compiler::turboshaft::Type::Any(), buffer_, v8::internal::ZoneVector< T >::clear(), v8::internal::compiler::MachineGraph::common(), DCHECK_EQ, v8::internal::compiler::MachineGraph::Dead(), v8::internal::compiler::Operator::EffectInputCount(), v8::internal::ZoneVector< T >::front(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::MachineGraph::graph(), graph_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::id(), v8::internal::compiler::Variable::id_, v8::internal::kTagged, v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::CommonOperatorBuilder::Phi(), v8::internal::ZoneVector< T >::push_back(), reducer_, v8::internal::compiler::NodeProperties::ReplaceValueInput(), v8::internal::ZoneVector< T >::reserve(), v8::base::internal::result, v8::internal::compiler::EffectGraphReducer::Revisit(), v8::internal::compiler::NodeProperties::SetType(), table_, tick_counter_, v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), v8::internal::TRACE(), and v8::internal::value.
Referenced by v8::internal::compiler::VariableTracker::Scope::Scope().
NewVariable()
Variable v8::internal::compiler::VariableTracker::NewVariable () [inline]
Definition at line 127 of file escape-analysis.cc.
{ return Variable(next_variable_++); }
References next_variable_.
Referenced by v8::internal::compiler::VirtualObject::VirtualObject().
operator=()
VariableTracker& v8::internal::compiler::VariableTracker::operator= (const VariableTracker &) [delete]
zone()
Zone* v8::internal::compiler::VariableTracker::zone () [inline]
Definition at line 129 of file escape-analysis.cc.
{ return zone_; }
References zone_.
Member Data Documentation
buffer_
ZoneVector<Node*> v8::internal::compiler::VariableTracker::buffer_ [private]
Definition at line 159 of file escape-analysis.cc.
Referenced by MergeInputs().
graph_
JSGraph* v8::internal::compiler::VariableTracker::graph_ [private]
Definition at line 157 of file escape-analysis.cc.
Referenced by MergeInputs().
next_variable_
int v8::internal::compiler::VariableTracker::next_variable_ = 0 [private]
Definition at line 161 of file escape-analysis.cc.
Referenced by NewVariable().
reducer_
EffectGraphReducer* v8::internal::compiler::VariableTracker::reducer_ [private]
Definition at line 160 of file escape-analysis.cc.
Referenced by MergeInputs().
table_
SparseSidetable<State> v8::internal::compiler::VariableTracker::table_ [private]
Definition at line 158 of file escape-analysis.cc.
Referenced by Get(), MergeInputs(), and v8::internal::compiler::VariableTracker::Scope::Scope().
tick_counter_
TickCounter* const v8::internal::compiler::VariableTracker::tick_counter_ [private]
Definition at line 162 of file escape-analysis.cc.
Referenced by MergeInputs().
zone_
Zone* v8::internal::compiler::VariableTracker::zone_ [private]
Definition at line 156 of file escape-analysis.cc.
Referenced by zone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/escape-analysis.cc