v8::internal::compiler::DeoptimizeParameters Class Reference
#include <common-operator.h>
Public Member Functions
DeoptimizeParameters (DeoptimizeReason reason, FeedbackSource const &feedback)
DeoptimizeReason reason () const
const FeedbackSource & feedback () const
Private Attributes
DeoptimizeReason const reason_
FeedbackSource const feedback_
Detailed Description
Definition at line 138 of file common-operator.h.
Constructor & Destructor Documentation
DeoptimizeParameters()
v8::internal::compiler::DeoptimizeParameters::DeoptimizeParameters (DeoptimizeReason reason, FeedbackSource const & feedback) [inline]
Definition at line 140 of file common-operator.h.
      : reason_(reason), feedback_(feedback) {}
Member Function Documentation
feedback()
const FeedbackSource& v8::internal::compiler::DeoptimizeParameters::feedback () const [inline]
Definition at line 144 of file common-operator.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::BranchElimination::ReduceDeoptimizeConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceDeoptimizeConditional(), v8::internal::compiler::MachineOperatorReducer::SimplifyBranch(), v8::internal::compiler::InstructionSelector::VisitControl(), and v8::internal::compiler::InstructionSelector::VisitDeoptimizeIf().
reason()
DeoptimizeReason v8::internal::compiler::DeoptimizeParameters::reason () const [inline]
Definition at line 143 of file common-operator.h.
{ return reason_; }
References reason_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::BranchElimination::ReduceDeoptimizeConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceDeoptimizeConditional(), v8::internal::compiler::MachineOperatorReducer::SimplifyBranch(), v8::internal::compiler::InstructionSelector::VisitControl(), and v8::internal::compiler::InstructionSelector::VisitDeoptimizeIf().
Member Data Documentation
feedback_
FeedbackSource const v8::internal::compiler::DeoptimizeParameters::feedback_ [private]
Definition at line 148 of file common-operator.h.
Referenced by feedback().
reason_
DeoptimizeReason const v8::internal::compiler::DeoptimizeParameters::reason_ [private]
Definition at line 147 of file common-operator.h.
Referenced by reason().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/common-operator.h