heap::base::Worklist< EntryType, MinSegmentSize >::Segment Class Reference
#include <worklist.h>
Public Member Functions
void Push (EntryType entry)
void Pop (EntryType *entry)
template<typename Callback >
void Update (Callback callback)
template<typename Callback >
void Iterate (Callback callback) const
Segment * next () const
void set_next (Segment *segment)
Static Public Member Functions
static Segment * Create (uint16_t min_segment_size)
static void Delete (Segment *segment)
Private Member Functions
constexpr Segment (size_t capacity)
EntryType & entry (size_t index)
const EntryType & entry (size_t index) const
Static Private Member Functions
static constexpr size_t MallocSizeForCapacity (size_t num_entries)
static constexpr size_t CapacityForMallocSize (size_t malloc_size)
Private Attributes
Segment * next_ = nullptr
Additional Inherited Members
Detailed Description
template<typename EntryType, uint16_t MinSegmentSize>
class heap::base::Worklist< EntryType, MinSegmentSize >::Segment
Definition at line 215 of file worklist.h.
Constructor & Destructor Documentation
Segment()
template<typename EntryType , uint16_t MinSegmentSize>
constexpr heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Segment (size_t capacity) [inline], [explicit], [constexpr], [private]
Definition at line 256 of file worklist.h.
      : internal::SegmentBase(capacity) {}
Member Function Documentation
CapacityForMallocSize()
template<typename EntryType , uint16_t MinSegmentSize>
static constexpr size_t heap::base::Worklist< EntryType, MinSegmentSize >::Segment::CapacityForMallocSize (size_t malloc_size) [inline], [static], [constexpr], [private]
Definition at line 252 of file worklist.h.
                                                                    {
    return (malloc_size - sizeof(Segment)) / sizeof(EntryType);
  }
Create()
template<typename EntryType , uint16_t MinSegmentSize>
static Segment* heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Create (uint16_t min_segment_size) [inline], [static]
Definition at line 218 of file worklist.h.
                                                    {
    const auto wanted_bytes = MallocSizeForCapacity(min_segment_size);
    v8::base::AllocationResult<char*> result;
    if (WorklistBase::PredictableOrder()) {
      result.ptr = static_cast<char*>(v8::base::Malloc(wanted_bytes));
      result.count = wanted_bytes;
    } else {
      result = v8::base::AllocateAtLeast<char>(wanted_bytes);
    }
    if (!result.ptr) {
      v8::base::FatalOOM(v8::base::OOMType::kProcess,
                         "Worklist::Segment::Create");
    }
    return new (result.ptr)
        Segment(CapacityForMallocSize(result.count * sizeof(char)));
  }
References v8::base::FatalOOM(), v8::base::kProcess, v8::base::Malloc(), heap::base::WorklistBase::PredictableOrder(), and v8::base::internal::result.
Referenced by heap::base::Worklist< EntryType, MinSegmentSize >::Local::NewSegment().
Delete()
template<typename EntryType , uint16_t MinSegmentSize>
static void heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Delete (Segment * segment) [inline], [static]
Definition at line 235 of file worklist.h.
{ v8::base::Free(segment); }
References v8::base::Free().
Referenced by heap::base::Worklist< EntryType, MinSegmentSize >::Local::DeleteSegment().
entry() [1/2]
template<typename EntryType , uint16_t MinSegmentSize>
EntryType& heap::base::Worklist< EntryType, MinSegmentSize >::Segment::entry (size_t index) [inline], [private]
Definition at line 259 of file worklist.h.
                                 {
    return reinterpret_cast<EntryType*>(this + 1)[index];
  }
References v8::internal::index.
Referenced by heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Push().
entry() [2/2]
template<typename EntryType , uint16_t MinSegmentSize>
const EntryType& heap::base::Worklist< EntryType, MinSegmentSize >::Segment::entry (size_t index) const [inline], [private]
Definition at line 262 of file worklist.h.
                                             {
    return reinterpret_cast<const EntryType*>(this + 1)[index];
  }
References v8::internal::index.
Iterate()
template<typename EntryType , uint16_t MinSegmentSize>
template<typename Callback >
void heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Iterate (Callback callback) const
Definition at line 295 of file worklist.h.
                             {
  for (size_t i = 0; i < index_; i++) {
    callback(entry(i));
  }
}
MallocSizeForCapacity()
template<typename EntryType , uint16_t MinSegmentSize>
static constexpr size_t heap::base::Worklist< EntryType, MinSegmentSize >::Segment::MallocSizeForCapacity (size_t num_entries) [inline], [static], [constexpr], [private]
Definition at line 249 of file worklist.h.
                                                                    {
    return sizeof(Segment) + sizeof(EntryType) * num_entries;
  }
next()
template<typename EntryType , uint16_t MinSegmentSize>
Segment* heap::base::Worklist< EntryType, MinSegmentSize >::Segment::next () const [inline]
Definition at line 245 of file worklist.h.
{ return next_; }
Referenced by heap::base::Worklist< EntryType, MinSegmentSize >::Clear(), heap::base::Worklist< EntryType, MinSegmentSize >::Iterate(), heap::base::Worklist< EntryType, MinSegmentSize >::Pop(), and heap::base::Worklist< EntryType, MinSegmentSize >::Update().
Pop()
template<typename EntryType , uint16_t MinSegmentSize>
void heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Pop (EntryType * entry) [inline]
Definition at line 276 of file worklist.h.
                                                                 {
  DCHECK(!IsEmpty());
  *e = entry(--index_);
}
References DCHECK, and heap::base::Worklist< EntryType, MinSegmentSize >::IsEmpty().
Push()
template<typename EntryType , uint16_t MinSegmentSize>
void heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Push (EntryType entry) [inline]
Definition at line 270 of file worklist.h.
                                                                 {
  DCHECK(!IsFull());
  entry(index_++) = e;
}
References DCHECK, heap::base::Worklist< EntryType, MinSegmentSize >::Segment::entry(), heap::base::internal::SegmentBase::index_, and heap::base::internal::SegmentBase::IsFull().
set_next()
template<typename EntryType , uint16_t MinSegmentSize>
void heap::base::Worklist< EntryType, MinSegmentSize >::Segment::set_next (Segment * segment) [inline]
Definition at line 246 of file worklist.h.
{ next_ = segment; }
Referenced by heap::base::Worklist< EntryType, MinSegmentSize >::Push(), and heap::base::Worklist< EntryType, MinSegmentSize >::Update().
Update()
template<typename EntryType , uint16_t MinSegmentSize>
template<typename Callback >
void heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Update (Callback callback)
Definition at line 283 of file worklist.h.
                                                                         {
  size_t new_index = 0;
  for (size_t i = 0; i < index_; i++) {
    if (callback(entry(i), &entry(new_index))) {
      new_index++;
    }
  }
  index_ = new_index;
}
Referenced by heap::base::Worklist< EntryType, MinSegmentSize >::Update().
Member Data Documentation
next_
template<typename EntryType , uint16_t MinSegmentSize>
Segment* heap::base::Worklist< EntryType, MinSegmentSize >::Segment::next_ = nullptr [private]
Definition at line 266 of file worklist.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/base/worklist.h