v8::internal::compiler::FinalAssessment Class Reference
#include <register-allocator-verifier.h>
Public Member Functions
FinalAssessment (int virtual_register)
FinalAssessment (const FinalAssessment &)=delete
FinalAssessment & operator= (const FinalAssessment &)=delete
int virtual_register () const
Static Public Member Functions
static const FinalAssessment * cast (const Assessment *assessment)
Private Attributes
int virtual_register_
Additional Inherited Members
Detailed Description
Definition at line 111 of file register-allocator-verifier.h.
Constructor & Destructor Documentation
FinalAssessment() [1/2]
v8::internal::compiler::FinalAssessment::FinalAssessment (int virtual_register) [inline], [explicit]
Definition at line 113 of file register-allocator-verifier.h.
      : Assessment(Final), virtual_register_(virtual_register) {}
FinalAssessment() [2/2]
v8::internal::compiler::FinalAssessment::FinalAssessment (const FinalAssessment &) [delete]
Member Function Documentation
cast()
static const FinalAssessment* v8::internal::compiler::FinalAssessment::cast (const Assessment * assessment) [inline], [static]
Definition at line 119 of file register-allocator-verifier.h.
                                                                   {
    CHECK(assessment->kind() == Final);
    return static_cast<const FinalAssessment*>(assessment);
  }
References CHECK, v8::internal::compiler::Final, and v8::internal::compiler::Assessment::kind().
Referenced by v8::internal::compiler::BlockAssessments::Print(), v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment(), v8::internal::compiler::RegisterAllocatorVerifier::ValidateUse(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
operator=()
FinalAssessment& v8::internal::compiler::FinalAssessment::operator= (const FinalAssessment &) [delete]
virtual_register()
int v8::internal::compiler::FinalAssessment::virtual_register () const [inline]
Definition at line 118 of file register-allocator-verifier.h.
{ return virtual_register_; }
References virtual_register_.
Referenced by v8::internal::compiler::BlockAssessments::Print(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
Member Data Documentation
virtual_register_
int v8::internal::compiler::FinalAssessment::virtual_register_ [private]
Definition at line 125 of file register-allocator-verifier.h.
Referenced by virtual_register().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/register-allocator-verifier.h