v8::PageAllocator Class Reference
A V8 memory page allocator.
#include <v8-platform.h>
Classes
class AllocationHint
Optional hints for AllocatePages().
class SharedMemory
INTERNAL ONLY: This interface has not been stabilised and may change without notice from one release to another without being deprecated first.
class SharedMemoryMapping
INTERNAL ONLY: This interface has not been stabilised and may change without notice from one release to another without being deprecated first.
Public Types
enum Permission {
kNoAccess
, kRead
, kReadWrite
, kReadWriteExecute
,
kReadExecute
, kNoAccessWillJitLater
 }
Memory permissions.
Public Member Functions
virtual ~PageAllocator ()=default
virtual size_t AllocatePageSize ()=0
Gets the page granularity for AllocatePages and FreePages.
virtual size_t CommitPageSize ()=0
Gets the page granularity for SetPermissions and ReleasePages.
virtual void SetRandomMmapSeed (int64_t seed)=0
Sets the random seed so that GetRandomMmapAddr() will generate repeatable sequences of random mmap addresses.
virtual void * GetRandomMmapAddr ()=0
Returns a randomized address, suitable for memory allocation under ASLR.
virtual void * AllocatePages (void *address, size_t length, size_t alignment, Permission permissions)=0
Allocates memory in range with the given alignment and permission.
virtual void * AllocatePages (size_t length, size_t alignment, Permission permissions, AllocationHint hint)
Allocates memory in range with the given alignment and permission.
virtual bool ResizeAllocationAt (void *address, size_t old_length, size_t new_length, Permission permissions)
Resizes the previously allocated memory at the given address.
virtual bool FreePages (void *address, size_t length)=0
Frees memory in a range that was allocated by a call to AllocatePages.
virtual bool ReleasePages (void *address, size_t length, size_t new_length)=0
Releases memory in a range that was allocated by a call to AllocatePages.
virtual bool SetPermissions (void *address, size_t length, Permission permissions)=0
Sets permissions on pages in an allocated range.
virtual bool RecommitPages (void *address, size_t length, Permission permissions)
Recommits discarded pages in the given range with given permissions.
virtual bool DiscardSystemPages (void *address, size_t size)
Frees memory in the given [address, address + size) range.
virtual bool DecommitPages (void *address, size_t size)=0
Decommits any wired memory pages in the given range, allowing the OS to reclaim them, and marks the region as inacessible (kNoAccess).
virtual bool SealPages (void *address, size_t length)
Block any modifications to the given mapping such as changing permissions or unmapping the pages on supported platforms.
virtual bool ReserveForSharedMemoryMapping (void *address, size_t size)
INTERNAL ONLY: This interface has not been stabilised and may change without notice from one release to another without being deprecated first.
virtual std::unique_ptr< SharedMemory > AllocateSharedPages (size_t length, const void *original_address)
INTERNAL ONLY: This interface has not been stabilised and may change without notice from one release to another without being deprecated first.
virtual bool CanAllocateSharedPages ()
INTERNAL ONLY: This interface has not been stabilised and may change without notice from one release to another without being deprecated first.
Detailed Description
A V8 memory page allocator.
Can be implemented by an embedder to manage large host OS allocations.
Definition at line 455 of file v8-platform.h.
Member Enumeration Documentation
Permission
enum v8::PageAllocator::Permission
Memory permissions.
Enumerator
kNoAccess
kRead
kReadWrite
kReadWriteExecute
kReadExecute
kNoAccessWillJitLater
Definition at line 486 of file v8-platform.h.
                  {
    kNoAccess,
    kRead,
    kReadWrite,
    kReadWriteExecute,
    kReadExecute,
    // Set this when reserving memory that will later require kReadWriteExecute
    // permissions. The resulting behavior is platform-specific, currently
    // this is used to set the MAP_JIT flag on Apple Silicon.
    // TODO(jkummerow): Remove this when Wasm has a platform-independent
    // w^x implementation.
    // TODO(saelo): Remove this once all JIT pages are allocated through the
    // VirtualAddressSpace API.
    kNoAccessWillJitLater
  };
Constructor & Destructor Documentation
 PageAllocator()
virtual v8::PageAllocator::~PageAllocator () [virtual], [default]
Member Function Documentation
AllocatePages() [1/2]
virtual void* v8::PageAllocator::AllocatePages (size_t length, size_t alignment, Permission permissions, AllocationHint hint) [inline], [virtual]
Allocates memory in range with the given alignment and permission.
In addition to AllocatePages it allows to pass in allocation hints. The underlying implementation may not make use of hints.
Reimplemented in v8::base::BoundedPageAllocator.
Definition at line 540 of file v8-platform.h.
                                                                           {
    return AllocatePages(hint.Address(), length, alignment, permissions);
  }
References v8::PageAllocator::AllocationHint::Address(), AllocatePages(), and v8::internal::length.
AllocatePages() [2/2]
virtual void* v8::PageAllocator::AllocatePages (void * address, size_t length, size_t alignment, Permission permissions) [pure virtual]
Allocates memory in range with the given alignment and permission.
Implemented in v8::base::VirtualAddressSpacePageAllocator, v8::base::BoundedPageAllocator, and v8::base::LsanPageAllocator.
Referenced by AllocatePages(), v8::internal::AllocatePages(), v8::base::LsanPageAllocator::AllocatePages(), cppgc::internal::anonymous_namespace{page-memory.cc}::ReserveMemoryRegion(), v8::internal::wasm::StackMemory::StackSegment::StackSegment(), and cppgc::internal::VirtualMemory::VirtualMemory().
AllocatePageSize()
virtual size_t v8::PageAllocator::AllocatePageSize () [pure virtual]
Gets the page granularity for AllocatePages and FreePages.
Addresses and lengths for those calls should be multiples of AllocatePageSize().
Implemented in v8::base::VirtualAddressSpacePageAllocator, v8::base::LsanPageAllocator, and v8::base::BoundedPageAllocator.
Referenced by v8::internal::AllocatePages(), v8::internal::AllocatePageSize(), v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator::AllocateVM(), v8::base::BoundedPageAllocator::BoundedPageAllocator(), cppgc::internal::anonymous_namespace{page-memory.cc}::CreateLargePageMemoryRegion(), cppgc::internal::anonymous_namespace{page-memory.cc}::CreateNormalPageMemoryRegion(), v8::internal::OffHeapInstructionStream::CreateOffHeapOffHeapInstructionStream(), v8::internal::VirtualMemory::Free(), v8::internal::OffHeapInstructionStream::FreeOffHeapOffHeapInstructionStream(), v8::internal::FreePages(), v8::internal::MemoryAllocator::FreeReadOnlyPage(), v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator::FreeVM(), v8::internal::wasm::StackMemory::Grow(), cppgc::internal::GCInfoTable::InitialTableLimit(), v8::internal::VirtualMemoryCage::InitReservation(), cppgc::internal::GCInfoTable::MaxTableSize(), cppgc::internal::anonymous_namespace{caged-heap.cc}::ReserveCagedHeap(), cppgc::internal::GCInfoTable::Resize(), v8::internal::wasm::StackMemory::StackMemory(), v8::internal::wasm::StackMemory::StackSegment::StackSegment(), v8::internal::wasm::WasmCodeManager::TryAllocate(), cppgc::internal::VirtualMemory::VirtualMemory(), v8::internal::VirtualMemory::VirtualMemory(), v8::internal::wasm::WasmInterpreterThread::WasmInterpreterThread(), v8::internal::ReadOnlyArtifacts::~ReadOnlyArtifacts(), and v8::internal::wasm::StackMemory::StackSegment::~StackSegment().
AllocateSharedPages()
virtual std::unique_ptr<SharedMemory> v8::PageAllocator::AllocateSharedPages (size_t length, const void * original_address) [inline], [virtual]
INTERNAL ONLY: This interface has not been stabilised and may change without notice from one release to another without being deprecated first.
Allocates shared memory pages. Not all PageAllocators need support this and so this method need not be overridden. Allocates a new read-only shared memory region of size |length| and copies the memory at |original_address| into it.
Reimplemented in v8::base::LsanPageAllocator.
Definition at line 663 of file v8-platform.h.
                                                   {
    return {};
  }
Referenced by v8::base::LsanPageAllocator::AllocateSharedPages().
CanAllocateSharedPages()
virtual bool v8::PageAllocator::CanAllocateSharedPages () [inline], [virtual]
INTERNAL ONLY: This interface has not been stabilised and may change without notice from one release to another without being deprecated first.
If not overridden and changed to return true, V8 will not attempt to call AllocateSharedPages or RemapSharedPages. If overridden, AllocateSharedPages and RemapSharedPages must also be overridden.
Reimplemented in v8::base::LsanPageAllocator.
Definition at line 676 of file v8-platform.h.
{ return false; }
Referenced by v8::base::LsanPageAllocator::CanAllocateSharedPages().
CommitPageSize()
virtual size_t v8::PageAllocator::CommitPageSize () [pure virtual]
Gets the page granularity for SetPermissions and ReleasePages.
Addresses and lengths for those calls should be multiples of CommitPageSize().
Implemented in v8::base::VirtualAddressSpacePageAllocator, v8::base::LsanPageAllocator, and v8::base::BoundedPageAllocator.
Referenced by cppgc::internal::CagedHeap::CommitAgeTable(), v8::internal::CommitPageSize(), v8::internal::wasm::WasmCodeManager::Decommit(), v8::internal::VirtualMemory::Release(), v8::internal::ReleasePages(), v8::internal::VirtualMemory::Resize(), cppgc::internal::anonymous_namespace{page-memory.cc}::TryDiscard(), cppgc::internal::anonymous_namespace{page-memory.cc}::TryUnprotect(), cppgc::internal::VirtualMemory::VirtualMemory(), and v8::internal::VirtualMemory::VirtualMemory().
DecommitPages()
virtual bool v8::PageAllocator::DecommitPages (void * address, size_t size) [pure virtual]
Decommits any wired memory pages in the given range, allowing the OS to reclaim them, and marks the region as inacessible (kNoAccess).
The address range stays reserved and can be accessed again later by changing its permissions. However, in that case the memory content is guaranteed to be zero-initialized again. The memory must have been previously allocated by a call to AllocatePages. Returns true on success, false otherwise.
Implemented in v8::base::VirtualAddressSpacePageAllocator, v8::base::LsanPageAllocator, and v8::base::BoundedPageAllocator.
Referenced by v8::internal::wasm::WasmCodeManager::Decommit(), v8::base::BoundedPageAllocator::DecommitPages(), v8::base::BoundedPageAllocator::FreePages(), v8::base::BoundedPageAllocator::ReleasePages(), cppgc::internal::NormalPageMemoryPool::ReleasePooledPages(), and v8::internal::wasm::StackMemory::StackSegment::~StackSegment().
DiscardSystemPages()
virtual bool v8::PageAllocator::DiscardSystemPages (void * address, size_t size) [inline], [virtual]
Frees memory in the given [address, address + size) range.
address and size should be operating system page-aligned. The next write to this memory area brings the memory transparently back. This should be treated as a hint to the OS that the pages are no longer needed. It does not guarantee that the pages will be discarded immediately or at all.
Reimplemented in v8::base::VirtualAddressSpacePageAllocator, v8::base::LsanPageAllocator, and v8::base::BoundedPageAllocator.
Definition at line 590 of file v8-platform.h.
{ return true; }
Referenced by v8::internal::VirtualMemory::DiscardSystemPages(), v8::base::BoundedPageAllocator::DiscardSystemPages(), v8::base::BoundedPageAllocator::FreePages(), v8::internal::CodeRange::InitReservation(), v8::base::BoundedPageAllocator::ReleasePages(), v8::internal::wasm::WasmCodeManager::TryAllocate(), cppgc::internal::anonymous_namespace{page-memory.cc}::TryDiscard(), and v8::internal::Sweeper::ZeroOrDiscardUnusedMemory().
FreePages()
virtual bool v8::PageAllocator::FreePages (void * address, size_t length) [pure virtual]
Frees memory in a range that was allocated by a call to AllocatePages.
Implemented in v8::base::VirtualAddressSpacePageAllocator, v8::base::LsanPageAllocator, and v8::base::BoundedPageAllocator.
Referenced by cppgc::internal::anonymous_namespace{page-memory.cc}::FreeMemoryRegion(), v8::internal::FreePages(), v8::base::LsanPageAllocator::FreePages(), v8::internal::ReadOnlyArtifacts::~ReadOnlyArtifacts(), and cppgc::internal::VirtualMemory::~VirtualMemory().
GetRandomMmapAddr()
virtual void* v8::PageAllocator::GetRandomMmapAddr () [pure virtual]
Returns a randomized address, suitable for memory allocation under ASLR.
The address will be aligned to AllocatePageSize.
Implemented in v8::base::VirtualAddressSpacePageAllocator, v8::base::LsanPageAllocator, and v8::base::BoundedPageAllocator.
Referenced by v8::internal::AllocatePages(), v8::internal::GetRandomMmapAddr(), and cppgc::internal::anonymous_namespace{caged-heap.cc}::ReserveCagedHeap().
RecommitPages()
virtual bool v8::PageAllocator::RecommitPages (void * address, size_t length, Permission permissions) [inline], [virtual]
Recommits discarded pages in the given range with given permissions.
Discarded pages must be recommitted with their original permissions before they are used again.
Reimplemented in v8::base::VirtualAddressSpacePageAllocator, v8::base::LsanPageAllocator, and v8::base::BoundedPageAllocator.
Definition at line 577 of file v8-platform.h.
                                                     {
    // TODO(v8:12797): make it pure once it's implemented on Chromium side.
    return false;
  }
Referenced by v8::base::BoundedPageAllocator::AllocatePages(), v8::internal::wasm::WasmCodeManager::Commit(), v8::internal::VirtualMemory::RecommitPages(), v8::base::BoundedPageAllocator::RecommitPages(), and cppgc::internal::NormalPageMemoryPool::Take().
ReleasePages()
virtual bool v8::PageAllocator::ReleasePages (void * address, size_t length, size_t new_length) [pure virtual]
Releases memory in a range that was allocated by a call to AllocatePages.
Implemented in v8::base::VirtualAddressSpacePageAllocator, v8::base::LsanPageAllocator, and v8::base::BoundedPageAllocator.
Referenced by v8::internal::ReleasePages(), v8::base::LsanPageAllocator::ReleasePages(), and cppgc::internal::GCInfoTable::~GCInfoTable().
ReserveForSharedMemoryMapping()
virtual bool v8::PageAllocator::ReserveForSharedMemoryMapping (void * address, size_t size) [inline], [virtual]
INTERNAL ONLY: This interface has not been stabilised and may change without notice from one release to another without being deprecated first.
Reserve pages at a fixed address returning whether the reservation is possible. The reserved memory is detached from the PageAllocator and so should not be freed by it. It's intended for use with SharedMemory::RemapTo, where ~SharedMemoryMapping would free the memory.
Reimplemented in v8::base::BoundedPageAllocator.
Definition at line 650 of file v8-platform.h.
                                                                         {
    return false;
  }
ResizeAllocationAt()
virtual bool v8::PageAllocator::ResizeAllocationAt (void * address, size_t old_length, size_t new_length, Permission permissions) [inline], [virtual]
Resizes the previously allocated memory at the given address.
Returns true if the allocation could be resized. Returns false if this operation is either not supported or the object could not be resized in-place.
Reimplemented in v8::base::BoundedPageAllocator.
Definition at line 550 of file v8-platform.h.
                                                                             {
    return false;
  }
Referenced by v8::internal::VirtualMemory::Resize().
SealPages()
virtual bool v8::PageAllocator::SealPages (void * address, size_t length) [inline], [virtual]
Block any modifications to the given mapping such as changing permissions or unmapping the pages on supported platforms.
The address space reservation will exist until the process ends, but it's possible to release the memory using DiscardSystemPages. Note that this might require write permissions to the page as e.g. on Linux, mseal will block discarding sealed anonymous memory.
Reimplemented in v8::base::VirtualAddressSpacePageAllocator, and v8::base::BoundedPageAllocator.
Definition at line 610 of file v8-platform.h.
                                                       {
    // TODO(360048056): make it pure once it's implemented on Chromium side.
    return false;
  }
Referenced by v8::internal::CodeRange::InitReservation(), and v8::base::BoundedPageAllocator::SealPages().
SetPermissions()
virtual bool v8::PageAllocator::SetPermissions (void * address, size_t length, Permission permissions) [pure virtual]
Sets permissions on pages in an allocated range.
Implemented in v8::base::VirtualAddressSpacePageAllocator, v8::base::BoundedPageAllocator, and v8::base::LsanPageAllocator.
Referenced by v8::base::BoundedPageAllocator::AllocatePages(), v8::base::BoundedPageAllocator::AllocatePagesAt(), cppgc::internal::CagedHeap::CommitAgeTable(), v8::base::BoundedPageAllocator::FreePages(), v8::internal::CodeRange::InitReservation(), v8::base::BoundedPageAllocator::ReleasePages(), v8::base::BoundedPageAllocator::ReserveForSharedMemoryMapping(), cppgc::internal::GCInfoTable::Resize(), v8::base::BoundedPageAllocator::ResizeAllocationAt(), v8::internal::VirtualMemory::SetPermissions(), v8::internal::SetPermissions(), v8::base::BoundedPageAllocator::SetPermissions(), cppgc::internal::NormalPageMemoryPool::Take(), and cppgc::internal::anonymous_namespace{page-memory.cc}::TryUnprotect().
SetRandomMmapSeed()
virtual void v8::PageAllocator::SetRandomMmapSeed (int64_t seed) [pure virtual]
Sets the random seed so that GetRandomMmapAddr() will generate repeatable sequences of random mmap addresses.
Implemented in v8::base::VirtualAddressSpacePageAllocator, v8::base::LsanPageAllocator, and v8::base::BoundedPageAllocator.
Referenced by v8::internal::V8::Initialize().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-platform.h