v8::internal::maglev::CreateObjectLiteral Class Reference
#include <maglev-ir.h>
Public Member Functions
CreateObjectLiteral (uint64_t bitfield, compiler::ObjectBoilerplateDescriptionRef boilerplate_descriptor, const compiler::FeedbackSource &feedback, int flags)
compiler::ObjectBoilerplateDescriptionRef boilerplate_descriptor ()
compiler::FeedbackSource feedback () const
int flags () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
Private Types
using Base = FixedInputValueNodeT< 0, CreateObjectLiteral >
Private Attributes
const compiler::ObjectBoilerplateDescriptionRef boilerplate_descriptor_
const compiler::FeedbackSource feedback_
const int flags_
Additional Inherited Members
Detailed Description
Definition at line 5732 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CreateObjectLiteral::Base = FixedInputValueNodeT<0, CreateObjectLiteral> [private]
Definition at line 5734 of file maglev-ir.h.
Constructor & Destructor Documentation
CreateObjectLiteral()
v8::internal::maglev::CreateObjectLiteral::CreateObjectLiteral (uint64_t bitfield, compiler::ObjectBoilerplateDescriptionRef boilerplate_descriptor, const compiler::FeedbackSource & feedback, int flags) [inline], [explicit]
Definition at line 5737 of file maglev-ir.h.
      : Base(bitfield),
        boilerplate_descriptor_(boilerplate_descriptor),
        feedback_(feedback),
        flags_(flags) {}
Member Function Documentation
boilerplate_descriptor()
compiler::ObjectBoilerplateDescriptionRef v8::internal::maglev::CreateObjectLiteral::boilerplate_descriptor () [inline]
Definition at line 5746 of file maglev-ir.h.
                                                                   {
    return boilerplate_descriptor_;
  }
References boilerplate_descriptor_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
compiler::FeedbackSource v8::internal::maglev::CreateObjectLiteral::feedback () const [inline]
Definition at line 5749 of file maglev-ir.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
flags()
int v8::internal::maglev::CreateObjectLiteral::flags () const [inline]
Definition at line 5750 of file maglev-ir.h.
{ return flags_; }
References flags_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::CreateObjectLiteral::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::CreateObjectLiteral::MaxCallStackArgs () const
PrintParams()
void v8::internal::maglev::CreateObjectLiteral::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 5761 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::CreateObjectLiteral::SetValueLocationConstraints ()
Member Data Documentation
boilerplate_descriptor_
const compiler::ObjectBoilerplateDescriptionRef v8::internal::maglev::CreateObjectLiteral::boilerplate_descriptor_ [private]
Definition at line 5764 of file maglev-ir.h.
Referenced by boilerplate_descriptor().
feedback_
const compiler::FeedbackSource v8::internal::maglev::CreateObjectLiteral::feedback_ [private]
Definition at line 5765 of file maglev-ir.h.
Referenced by feedback().
flags_
const int v8::internal::maglev::CreateObjectLiteral::flags_ [private]
Definition at line 5766 of file maglev-ir.h.
Referenced by flags().
kProperties
constexpr OpProperties v8::internal::maglev::CreateObjectLiteral::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::Call() | OpProperties::CanAllocate() |
      OpProperties::CanThrow() | OpProperties::LazyDeopt() |
      OpProperties::NotIdempotent()
Definition at line 5753 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h