v8::internal::ProfilerEventsProcessor Class Reference
#include <cpu-profiler.h>
Public Member Functions
~ProfilerEventsProcessor () override
void CodeEventHandler (const CodeEventsContainer &evt_rec) override
void Run () override=0
void StopSynchronously ()
bool running ()
void Enqueue (const CodeEventsContainer &event)
void AddCurrentStack (bool update_stats=false, const std::optional< uint64_t > trace_id=std::nullopt)
void AddDeoptStack (Address from, int fp_to_sp_delta)
void AddSample (TickSample sample)
virtual void SetSamplingInterval (base::TimeDelta)
Protected Types
enum SampleProcessingResult { OneSampleProcessed
, FoundSampleForNextCodeEvent
, NoSamplesInQueue
 }
Protected Member Functions
ProfilerEventsProcessor (Isolate *isolate, Symbolizer *symbolizer, ProfilerCodeObserver *code_observer, CpuProfilesCollection *profiles)
bool ProcessCodeEvent ()
virtual SampleProcessingResult ProcessOneSample ()=0
Protected Attributes
Symbolizer * symbolizer_
ProfilerCodeObserver * code_observer_
CpuProfilesCollection * profiles_
std::atomic_bool running_ {true}
base::ConditionVariable running_cond_
base::Mutex running_mutex_
LockedQueue< CodeEventsContainer > events_buffer_
LockedQueue< TickSampleEventRecord > ticks_from_vm_buffer_
std::atomic< unsigned > last_code_event_id_
unsigned last_processed_code_event_id_
Isolate * isolate_
Additional Inherited Members
Detailed Description
Definition at line 169 of file cpu-profiler.h.
Member Enumeration Documentation
SampleProcessingResult
enum v8::internal::ProfilerEventsProcessor::SampleProcessingResult [protected]
Enumerator
OneSampleProcessed
FoundSampleForNextCodeEvent
NoSamplesInQueue
Definition at line 199 of file cpu-profiler.h.
                              {
    OneSampleProcessed,
    FoundSampleForNextCodeEvent,
    NoSamplesInQueue
  };
Constructor & Destructor Documentation
 ProfilerEventsProcessor()
v8::internal::ProfilerEventsProcessor::~ProfilerEventsProcessor () [override]
Definition at line 139 of file cpu-profiler.cc.
                                                  {
  DCHECK_EQ(code_observer_->processor(), this);
  code_observer_->clear_processor();
}
References v8::internal::ProfilerCodeObserver::clear_processor(), code_observer_, DCHECK_EQ, and v8::internal::ProfilerCodeObserver::processor().
ProfilerEventsProcessor()
v8::internal::ProfilerEventsProcessor::ProfilerEventsProcessor (Isolate * isolate, Symbolizer * symbolizer, ProfilerCodeObserver * code_observer, CpuProfilesCollection * profiles) [protected]
Definition at line 108 of file cpu-profiler.cc.
    : Thread(Thread::Options("v8:ProfEvntProc", kProfilerStackSize)),
      symbolizer_(symbolizer),
      code_observer_(code_observer),
      profiles_(profiles),
      last_code_event_id_(0),
      last_processed_code_event_id_(0),
      isolate_(isolate) {
  DCHECK(!code_observer_->processor());
  code_observer_->set_processor(this);
}
References code_observer_, v8::internal::DCHECK(), v8::internal::ProfilerCodeObserver::processor(), and v8::internal::ProfilerCodeObserver::set_processor().
Member Function Documentation
AddCurrentStack()
void v8::internal::ProfilerEventsProcessor::AddCurrentStack (bool update_stats = false, const std::optional< uint64_t > trace_id = std::nullopt)
Definition at line 161 of file cpu-profiler.cc.
                                                             {
  TickSampleEventRecord record(last_code_event_id_);
  RegisterState regs;
  StackFrameIterator it(isolate_, isolate_->thread_local_top());
  if (!it.done()) {
    StackFrame* frame = it.frame();
    regs.sp = reinterpret_cast<void*>(frame->sp());
    regs.fp = reinterpret_cast<void*>(frame->fp());
    regs.pc = reinterpret_cast<void*>(frame->pc());
  }
  record.sample.Init(isolate_, regs, TickSample::kSkipCEntryFrame, update_stats,
                     false, base::TimeDelta(), trace_id);
  ticks_from_vm_buffer_.Enqueue(record);
}
References v8::internal::StackFrameIteratorBase::done(), v8::RegisterState::fp, v8::internal::StackFrame::fp(), v8::internal::StackFrameIterator::frame(), v8::internal::TickSample::Init(), isolate_, v8::internal::TickSample::kSkipCEntryFrame, last_code_event_id_, v8::RegisterState::pc, v8::internal::StackFrame::pc(), v8::internal::TickSampleEventRecord::sample, v8::RegisterState::sp, v8::internal::StackFrame::sp(), v8::internal::Isolate::thread_local_top(), and ticks_from_vm_buffer_.
AddDeoptStack()
void v8::internal::ProfilerEventsProcessor::AddDeoptStack (Address from, int fp_to_sp_delta)
Definition at line 149 of file cpu-profiler.cc.
                                                                            {
  TickSampleEventRecord record(last_code_event_id_);
  RegisterState regs;
  Address fp = isolate_->c_entry_fp(isolate_->thread_local_top());
  regs.sp = reinterpret_cast<void*>(fp - fp_to_sp_delta);
  regs.fp = reinterpret_cast<void*>(fp);
  regs.pc = reinterpret_cast<void*>(from);
  record.sample.Init(isolate_, regs, TickSample::kSkipCEntryFrame, false,
                     false);
  ticks_from_vm_buffer_.Enqueue(record);
}
References v8::internal::Isolate::c_entry_fp(), v8::RegisterState::fp, v8::internal::TickSample::Init(), isolate_, v8::internal::TickSample::kSkipCEntryFrame, last_code_event_id_, v8::RegisterState::pc, v8::internal::TickSampleEventRecord::sample, v8::RegisterState::sp, v8::internal::Isolate::thread_local_top(), and ticks_from_vm_buffer_.
Referenced by CodeEventHandler().
AddSample()
void v8::internal::ProfilerEventsProcessor::AddSample (TickSample sample)
Definition at line 177 of file cpu-profiler.cc.
                                                         {
  TickSampleEventRecord record(last_code_event_id_);
  record.sample = sample;
  ticks_from_vm_buffer_.Enqueue(record);
}
References last_code_event_id_, v8::internal::TickSampleEventRecord::sample, and ticks_from_vm_buffer_.
CodeEventHandler()
void v8::internal::ProfilerEventsProcessor::CodeEventHandler (const CodeEventsContainer & evt_rec) [override], [virtual]
Implements v8::internal::CodeEventObserver.
Definition at line 213 of file cpu-profiler.cc.
                                        {
  switch (evt_rec.generic.type) {
    case CodeEventRecord::Type::kCodeCreation:
    case CodeEventRecord::Type::kCodeMove:
    case CodeEventRecord::Type::kCodeDisableOpt:
    case CodeEventRecord::Type::kCodeDelete:
    case CodeEventRecord::Type::kNativeContextMove:
      Enqueue(evt_rec);
      break;
    case CodeEventRecord::Type::kCodeDeopt: {
      const CodeDeoptEventRecord* rec = &evt_rec.CodeDeoptEventRecord_;
      Address pc = rec->pc;
      int fp_to_sp_delta = rec->fp_to_sp_delta;
      Enqueue(evt_rec);
      AddDeoptStack(pc, fp_to_sp_delta);
      break;
    }
    case CodeEventRecord::Type::kNoEvent:
    case CodeEventRecord::Type::kReportBuiltin:
      UNREACHABLE();
  }
}
References AddDeoptStack(), Enqueue(), v8::internal::CodeDeoptEventRecord::fp_to_sp_delta, v8::internal::CodeEventsContainer::generic, v8::internal::CodeEventRecord::kNoEvent, v8::internal::CodeDeoptEventRecord::pc, v8::internal::CodeEventRecord::type, and v8::internal::UNREACHABLE().
Referenced by v8::internal::ProfilerCodeObserver::CodeEventHandler().
Enqueue()
void v8::internal::ProfilerEventsProcessor::Enqueue (const CodeEventsContainer & event)
Definition at line 144 of file cpu-profiler.cc.
                                                                      {
  event.generic.order = ++last_code_event_id_;
  events_buffer_.Enqueue(event);
}
References events_buffer_, and last_code_event_id_.
Referenced by CodeEventHandler().
ProcessCodeEvent()
bool v8::internal::ProfilerEventsProcessor::ProcessCodeEvent () [protected]
Definition at line 196 of file cpu-profiler.cc.
                                               {
  CodeEventsContainer record;
  if (events_buffer_.Dequeue(&record)) {
    if (record.generic.type == CodeEventRecord::Type::kNativeContextMove) {
      NativeContextMoveEventRecord& nc_record =
          record.NativeContextMoveEventRecord_;
      profiles_->UpdateNativeContextAddressForCurrentProfiles(
          nc_record.from_address, nc_record.to_address);
    } else {
      code_observer_->CodeEventHandlerInternal(record);
    }
    last_processed_code_event_id_ = record.generic.order;
    return true;
  }
  return false;
}
References code_observer_, v8::internal::ProfilerCodeObserver::CodeEventHandlerInternal(), events_buffer_, v8::internal::NativeContextMoveEventRecord::from_address, v8::internal::CodeEventsContainer::generic, last_processed_code_event_id_, v8::internal::CodeEventRecord::order, profiles_, v8::internal::NativeContextMoveEventRecord::to_address, v8::internal::CodeEventRecord::type, and v8::internal::CpuProfilesCollection::UpdateNativeContextAddressForCurrentProfiles().
Referenced by v8::internal::SamplingEventsProcessor::Run().
ProcessOneSample()
virtual SampleProcessingResult v8::internal::ProfilerEventsProcessor::ProcessOneSample () [protected], [pure virtual]
Implemented in v8::internal::SamplingEventsProcessor.
Run()
void v8::internal::ProfilerEventsProcessor::Run () [override], [pure virtual]
Implements v8::base::Thread.
Implemented in v8::internal::SamplingEventsProcessor.
running()
bool v8::internal::ProfilerEventsProcessor::running () [inline]
Definition at line 179 of file cpu-profiler.h.
{ return running_.load(std::memory_order_relaxed); }
SetSamplingInterval()
virtual void v8::internal::ProfilerEventsProcessor::SetSamplingInterval (base::TimeDelta) [inline], [virtual]
Reimplemented in v8::internal::SamplingEventsProcessor.
Definition at line 189 of file cpu-profiler.h.
{}
StopSynchronously()
void v8::internal::ProfilerEventsProcessor::StopSynchronously ()
Definition at line 183 of file cpu-profiler.cc.
                                                {
  bool expected = true;
  if (!running_.compare_exchange_strong(expected, false,
                                        std::memory_order_relaxed))
    return;
  {
    base::MutexGuard guard(&running_mutex_);
    running_cond_.NotifyOne();
  }
  Join();
}
References v8::base::Thread::Join(), v8::base::ConditionVariable::NotifyOne(), running_, running_cond_, and running_mutex_.
Referenced by v8::internal::SamplingEventsProcessor::SetSamplingInterval().
Member Data Documentation
code_observer_
ProfilerCodeObserver* v8::internal::ProfilerEventsProcessor::code_observer_ [protected]
Definition at line 207 of file cpu-profiler.h.
Referenced by ProcessCodeEvent(), ProfilerEventsProcessor(), and ~ProfilerEventsProcessor().
events_buffer_
LockedQueue<CodeEventsContainer> v8::internal::ProfilerEventsProcessor::events_buffer_ [protected]
Definition at line 212 of file cpu-profiler.h.
Referenced by Enqueue(), and ProcessCodeEvent().
isolate_
Isolate* v8::internal::ProfilerEventsProcessor::isolate_ [protected]
Definition at line 216 of file cpu-profiler.h.
Referenced by AddCurrentStack(), AddDeoptStack(), and v8::internal::SamplingEventsProcessor::Run().
last_code_event_id_
std::atomic<unsigned> v8::internal::ProfilerEventsProcessor::last_code_event_id_ [protected]
Definition at line 214 of file cpu-profiler.h.
Referenced by AddCurrentStack(), AddDeoptStack(), AddSample(), Enqueue(), and v8::internal::SamplingEventsProcessor::StartTickSample().
last_processed_code_event_id_
unsigned v8::internal::ProfilerEventsProcessor::last_processed_code_event_id_ [protected]
Definition at line 215 of file cpu-profiler.h.
Referenced by ProcessCodeEvent(), and v8::internal::SamplingEventsProcessor::ProcessOneSample().
profiles_
CpuProfilesCollection* v8::internal::ProfilerEventsProcessor::profiles_ [protected]
Definition at line 208 of file cpu-profiler.h.
Referenced by ProcessCodeEvent(), and v8::internal::SamplingEventsProcessor::SymbolizeAndAddToProfiles().
running_
std::atomic_bool v8::internal::ProfilerEventsProcessor::running_ {true} [protected]
Definition at line 209 of file cpu-profiler.h.
Referenced by v8::internal::SamplingEventsProcessor::Run(), v8::internal::SamplingEventsProcessor::SetSamplingInterval(), and StopSynchronously().
running_cond_
base::ConditionVariable v8::internal::ProfilerEventsProcessor::running_cond_ [protected]
Definition at line 210 of file cpu-profiler.h.
Referenced by v8::internal::SamplingEventsProcessor::Run(), and StopSynchronously().
running_mutex_
base::Mutex v8::internal::ProfilerEventsProcessor::running_mutex_ [protected]
Definition at line 211 of file cpu-profiler.h.
Referenced by v8::internal::SamplingEventsProcessor::Run(), and StopSynchronously().
symbolizer_
Symbolizer* v8::internal::ProfilerEventsProcessor::symbolizer_ [protected]
Definition at line 206 of file cpu-profiler.h.
Referenced by v8::internal::SamplingEventsProcessor::SymbolizeAndAddToProfiles().
ticks_from_vm_buffer_
LockedQueue<TickSampleEventRecord> v8::internal::ProfilerEventsProcessor::ticks_from_vm_buffer_ [protected]
Definition at line 213 of file cpu-profiler.h.
Referenced by AddCurrentStack(), AddDeoptStack(), AddSample(), and v8::internal::SamplingEventsProcessor::ProcessOneSample().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/cpu-profiler.h
/mnt/V8SourceCode/src/profiler/cpu-profiler.cc