v8::internal::maglev::Int32BitwiseNot Class Reference
#include <maglev-ir.h>
Public Member Functions
Int32BitwiseNot (uint64_t bitfield)
Input & value_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::Int32()
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kInt32}
static constexpr int kValueIndex = 0
Private Types
using Base = FixedInputValueNodeT< 1, Int32BitwiseNot >
Additional Inherited Members
Detailed Description
Definition at line 3226 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::Int32BitwiseNot::Base = FixedInputValueNodeT<1, Int32BitwiseNot> [private]
Definition at line 3227 of file maglev-ir.h.
Constructor & Destructor Documentation
Int32BitwiseNot()
v8::internal::maglev::Int32BitwiseNot::Int32BitwiseNot (uint64_t bitfield) [inline], [explicit]
Definition at line 3230 of file maglev-ir.h.
: Base(bitfield) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::Int32BitwiseNot::GenerateCode (MaglevAssembler * masm, const ProcessingState & state)
Definition at line 551 of file maglev-ir-arm.cc.
                                                                 {
  Register value = ToRegister(value_input());
  Register out = ToRegister(result());
PrintParams()
void v8::internal::maglev::Int32BitwiseNot::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 3241 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::Int32BitwiseNot::SetValueLocationConstraints ()
Definition at line 546 of file maglev-ir-arm.cc.
                                                  {
  UseRegister(value_input());
References v8::internal::maglev::DefineAsRegister(), v8::internal::maglev::UseRegister(), and value_input().
value_input()
Input& v8::internal::maglev::Int32BitwiseNot::value_input () [inline]
Definition at line 3237 of file maglev-ir.h.
{ return Node::input(kValueIndex); }
References v8::internal::maglev::NodeBase::input(), and kValueIndex.
Referenced by SetValueLocationConstraints().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::Int32BitwiseNot::kInputTypes {ValueRepresentation::kInt32} [static], [constexpr]
Definition at line 3234 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::Int32BitwiseNot::kProperties = OpProperties::Int32() [static], [constexpr]
Definition at line 3232 of file maglev-ir.h.
kValueIndex
constexpr int v8::internal::maglev::Int32BitwiseNot::kValueIndex = 0 [static], [constexpr]
Definition at line 3236 of file maglev-ir.h.
Referenced by value_input().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/arm/maglev-ir-arm.cc
/mnt/V8SourceCode/src/maglev/arm64/maglev-ir-arm64.cc
/mnt/V8SourceCode/src/maglev/riscv/maglev-ir-riscv.cc
/mnt/V8SourceCode/src/maglev/s390/maglev-ir-s390.cc
/mnt/V8SourceCode/src/maglev/x64/maglev-ir-x64.cc