v8::BasicTracedReference< T > Class Template Reference
A traced handle with copy and move semantics.
#include <v8-traced-handle.h>
Public Member Functions
Local< T > Get (Isolate *isolate) const
Construct a Local<T> from this handle.
template<class S >
BasicTracedReference< S > & As () const
Private Member Functions
BasicTracedReference ()=default
An empty BasicTracedReference without storage cell.
Static Private Member Functions
static internal::Address * NewFromNonEmptyValue (Isolate *isolate, T *that, internal::Address **slot, internal::TracedReferenceStoreMode store_mode, internal::TracedReferenceHandling reference_handling)
Friends
template<typename F >
class Local
class Object
template<typename F >
class TracedReference
template<typename F >
class BasicTracedReference
template<typename F >
class ReturnValue
Additional Inherited Members
Detailed Description
template<typename T>
class v8::BasicTracedReference< T >
A traced handle with copy and move semantics.
The handle is to be used together as part of GarbageCollected objects (see v8-cppgc.h) or from stack and specifies edges from C++ objects to JavaScript.
The exact semantics are:
Tracing garbage collections using CppHeap.
Non-tracing garbage collections refer to |v8::EmbedderRootsHandler::IsRoot()| whether the handle should be treated as root or not.
Note that the base class cannot be instantiated itself, use |TracedReference| instead.
Definition at line 124 of file v8-traced-handle.h.
Constructor & Destructor Documentation
BasicTracedReference()
template<typename T >
v8::BasicTracedReference< T >::BasicTracedReference () [private], [default]
An empty BasicTracedReference without storage cell.
Member Function Documentation
As()
template<typename T >
template<class S >
BasicTracedReference<S>& v8::BasicTracedReference< T >::As () const [inline]
Definition at line 132 of file v8-traced-handle.h.
                                                {
    return reinterpret_cast<BasicTracedReference<S>&>(
        const_cast<BasicTracedReference<T>&>(*this));
  }
Get()
template<typename T >
Local<T> v8::BasicTracedReference< T >::Get (Isolate * isolate) const [inline]
Construct a Local<T> from this handle.
Definition at line 129 of file v8-traced-handle.h.
{ return Local<T>::New(isolate, *this); }
References v8::Local< T >::New().
NewFromNonEmptyValue()
template<class T >
internal::Address * v8::BasicTracedReference< T >::NewFromNonEmptyValue (Isolate * isolate, T * that, internal::Address ** slot, internal::TracedReferenceStoreMode store_mode, internal::TracedReferenceHandling reference_handling) [inline], [static], [private]
Definition at line 298 of file v8-traced-handle.h.
                                                        {
  return internal::GlobalizeTracedReference(
      reinterpret_cast<internal::Isolate*>(isolate),
      internal::ValueHelper::ValueAsAddress(that),
      reinterpret_cast<internal::Address*>(slot), store_mode,
      reference_handling);
}
References v8::internal::GlobalizeTracedReference(), and v8::internal::ValueHelper::ValueAsAddress().
Referenced by v8::TracedReference< T >::TracedReference().
Friends And Related Function Documentation
BasicTracedReference
template<typename T >
template<typename F >
friend class BasicTracedReference [friend]
Definition at line 154 of file v8-traced-handle.h.
Local
template<typename T >
template<typename F >
friend class Local [friend]
Definition at line 149 of file v8-traced-handle.h.
Object
template<typename T >
friend class Object [friend]
Definition at line 150 of file v8-traced-handle.h.
ReturnValue
template<typename T >
template<typename F >
friend class ReturnValue [friend]
Definition at line 156 of file v8-traced-handle.h.
TracedReference
template<typename T >
template<typename F >
friend class TracedReference [friend]
Definition at line 152 of file v8-traced-handle.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-function-callback.h
/mnt/V8SourceCode/include/v8-traced-handle.h