v8::internal::RegisterBase< SubType, kAfterLastRegister > Class Template Reference
#include <register-base.h>
Public Member Functions
constexpr bool is_valid () const
constexpr int8_t code () const
constexpr bool operator== (const RegisterBase< SubType, kAfterLastRegister > &other) const
constexpr bool operator!= (const RegisterBase< SubType, kAfterLastRegister > &other) const
Static Public Member Functions
static constexpr SubType no_reg ()
static constexpr SubType from_code (int8_t code)
static const char * GetSpecialRegisterName (int code)
Static Public Attributes
static constexpr int8_t kCode_no_reg = -1
static constexpr int8_t kNumRegisters = kAfterLastRegister
Protected Member Functions
constexpr RegisterBase (int code)
Private Attributes
int8_t reg_code_
Detailed Description
template<typename SubType, int kAfterLastRegister>
class v8::internal::RegisterBase< SubType, kAfterLastRegister >
Definition at line 29 of file register-base.h.
Constructor & Destructor Documentation
RegisterBase()
template<typename SubType , int kAfterLastRegister>
constexpr v8::internal::RegisterBase< SubType, kAfterLastRegister >::RegisterBase (int code) [inline], [explicit], [constexpr], [protected]
Definition at line 66 of file register-base.h.
: reg_code_(code) {}
Member Function Documentation
code()
template<typename SubType , int kAfterLastRegister>
constexpr int8_t v8::internal::RegisterBase< SubType, kAfterLastRegister >::code () const [inline], [constexpr]
Definition at line 43 of file register-base.h.
                                {
#if V8_TARGET_ARCH_ARM64
    // Arm64 uses kSPRegInternalCode which is > kNumRegisters.
    V8_ASSUME(reg_code_ >= 0);
#else
    V8_ASSUME(reg_code_ >= 0 && reg_code_ < kNumRegisters);
#endif
    return reg_code_;
  }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::kNumRegisters, v8::internal::RegisterBase< SubType, kAfterLastRegister >::reg_code_, and V8_ASSUME.
Referenced by v8::internal::MacroAssembler::AlignedStoreHelper(), v8::internal::MacroAssembler::And(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::Assembler::bc(), v8::internal::AssemblerRISCVC::c_and(), v8::internal::AssemblerRISCVC::c_andi(), v8::internal::AssemblerRISCVC::c_beqz(), v8::internal::AssemblerRISCVC::c_bnez(), v8::internal::AssemblerRISCVC::c_fld(), v8::internal::AssemblerRISCVC::c_fsd(), v8::internal::AssemblerRISCVC::c_lw(), v8::internal::AssemblerRISCVC::c_or(), v8::internal::AssemblerRISCVC::c_srai(), v8::internal::AssemblerRISCVC::c_srli(), v8::internal::AssemblerRISCVC::c_sub(), v8::internal::AssemblerRISCVC::c_sw(), v8::internal::AssemblerRISCVC::c_xor(), v8::internal::wasm::LinkageAllocator::CanAllocateFP(), v8::internal::Assembler::cmpi_optimization(), v8::internal::CPURegList::Combine(), v8::internal::JavaScriptBuiltinContinuationFrame::ComputeParametersCount(), v8::internal::maglev::DefineAsFixed(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), v8::internal::Deoptimizer::DoComputeOutputFrames(), v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_demote_f64x2_zero(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_div(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_sqrt(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_trunc_sat_f64x2_s_zero(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_trunc_sat_f64x2_u_zero(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_shuffle(), v8::internal::Assembler::emit_optional_rex_32(), v8::internal::Assembler::emit_rex_64(), v8::internal::wasm::LiftoffAssembler::emit_s128_store_nonzero_if_nan(), v8::internal::Assembler::emit_vex2_byte1(), v8::internal::Assembler::emit_vex3_byte2(), v8::internal::Assembler::emit_vex_prefix(), v8::internal::Assembler::emit_xor(), v8::internal::wasm::liftoff::EmitAllTrue(), v8::internal::Assembler::encode_crbit(), v8::internal::Assembler::extsw(), v8::internal::wasm::F16x8BinOpViaF32(), v8::internal::wasm::F16x8CmpOpViaF32(), v8::internal::maglev::ValueNode::FirstRegisterCode(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::from_code(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_ContinueToBuiltinHelper(), v8::internal::AssemblerRiscvBase::GenInstrB(), v8::internal::AssemblerRiscvBase::GenInstrCA(), v8::internal::AssemblerRiscvBase::GenInstrCB(), v8::internal::AssemblerRiscvBase::GenInstrCBA(), v8::internal::AssemblerRiscvBase::GenInstrCI(), v8::internal::AssemblerRiscvBase::GenInstrCIU(), v8::internal::AssemblerRiscvBase::GenInstrCIW(), v8::internal::AssemblerRiscvBase::GenInstrCL(), v8::internal::AssemblerRiscvBase::GenInstrCR(), v8::internal::AssemblerRiscvBase::GenInstrCS(), v8::internal::AssemblerRiscvBase::GenInstrCSS(), v8::internal::AssemblerRiscvBase::GenInstrI(), v8::internal::AssemblerRiscvBase::GenInstrIShift(), v8::internal::AssemblerRiscvBase::GenInstrIShiftW(), v8::internal::AssemblerRiscvBase::GenInstrJ(), v8::internal::AssemblerRiscvBase::GenInstrR(), v8::internal::AssemblerRiscvBase::GenInstrR4(), v8::internal::AssemblerRiscvBase::GenInstrRAtomic(), v8::internal::AssemblerRiscvBase::GenInstrRFrm(), v8::internal::AssemblerRiscvBase::GenInstrS(), v8::internal::AssemblerRiscvBase::GenInstrU(), v8::internal::AssemblerRISCVV::GenInstrV(), v8::internal::wasm::liftoff::GetFloatRegister(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::CPURegList::IncludesAliasOf(), v8::internal::Operand::is_reg(), v8::internal::CallInterfaceDescriptor::IsValidFloatParameterRegister(), v8::internal::wasm::IterateSignatureImpl(), v8::internal::MacroAssembler::LoadDouble(), v8::internal::maglev::MaglevAssembler::LoadFloat32(), v8::internal::MacroAssembler::Lw(), v8::internal::Assembler::lzer(), v8::internal::wasm::LinkageAllocator::NextFpReg(), v8::internal::wasm::LinkageAllocator::NextGpReg(), v8::internal::Operand::Operand(), v8::internal::MacroAssembler::Or(), v8::internal::Assembler::pfd(), v8::internal::MacroAssembler::Pop(), v8::internal::wasm::LiftoffAssembler::PopRegisters(), v8::internal::MacroAssembler::Push(), v8::internal::wasm::LiftoffAssembler::PushRegisters(), v8::internal::Assembler::Ra(), v8::internal::Assembler::Rd(), v8::internal::Assembler::RdSP(), v8::internal::compiler::anonymous_namespace{linkage.cc}::regloc(), v8::internal::CPURegList::Remove(), v8::internal::Assembler::Rm(), v8::internal::Assembler::RmNot31(), v8::internal::Assembler::Rn(), v8::internal::Assembler::RnSP(), v8::internal::Assembler::Rs(), v8::internal::Assembler::Rt(), v8::internal::Assembler::Rt2(), v8::internal::Operand::set_modrm(), v8::internal::Operand::set_sib(), v8::internal::wasm::LiftoffAssembler::SpillAdjacentFpRegisters(), v8::internal::FrameTranslationBuilder::StoreDoubleRegister(), v8::internal::FrameTranslationBuilder::StoreFloatRegister(), v8::internal::FrameTranslationBuilder::StoreHoleyDoubleRegister(), v8::internal::FrameTranslationBuilder::StoreRegister(), v8::internal::FrameTranslationBuilder::StoreSimd128Register(), v8::internal::ToNumber(), v8::internal::maglev::UseFixed(), v8::internal::Assembler::vblendvpd(), v8::internal::Assembler::vblendvps(), v8::internal::Assembler::vc_form(), v8::internal::Assembler::vcvtlsi2sd(), v8::internal::Assembler::vcvtlsi2ss(), v8::internal::Assembler::vcvtqsi2sd(), v8::internal::Assembler::vcvtqsi2ss(), v8::internal::Assembler::vcvtsd2si(), v8::internal::Assembler::vcvttsd2si(), v8::internal::Assembler::vcvttsd2siq(), v8::internal::Assembler::vcvttss2si(), v8::internal::Assembler::vcvttss2siq(), v8::internal::Assembler::VfpRegisterIsAvailable(), v8::internal::Assembler::vmovmskpd(), v8::internal::Assembler::vmovmskps(), v8::internal::Assembler::vpblendvb(), v8::internal::Assembler::vpextrq(), v8::internal::Assembler::vpinsrb(), v8::internal::Assembler::vpinsrd(), v8::internal::Assembler::vpinsrq(), v8::internal::Assembler::vpinsrw(), v8::internal::AssemblerRISCVV::vsetivli(), v8::internal::AssemblerRISCVV::vsetvl(), v8::internal::AssemblerRISCVV::vsetvli(), v8::internal::Assembler::vx_form(), v8::internal::Assembler::x_form(), v8::internal::MacroAssembler::Xor(), and v8::internal::Assembler::xx3_form().
from_code()
template<typename SubType , int kAfterLastRegister>
static constexpr SubType v8::internal::RegisterBase< SubType, kAfterLastRegister >::from_code (int8_t code) [inline], [static], [constexpr]
Definition at line 36 of file register-base.h.
                                                  {
    V8_ASSUME(code >= 0 && code < kNumRegisters);
    return SubType{code};
  }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::kNumRegisters, and V8_ASSUME.
GetSpecialRegisterName()
template<typename SubType , int kAfterLastRegister>
static const char* v8::internal::RegisterBase< SubType, kAfterLastRegister >::GetSpecialRegisterName (int code) [inline], [static]
Definition at line 63 of file register-base.h.
{ return "UNKNOWN"; }
is_valid()
template<typename SubType , int kAfterLastRegister>
constexpr bool v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid () const [inline], [constexpr]
Definition at line 41 of file register-base.h.
{ return reg_code_ != kCode_no_reg; }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::kCode_no_reg, and v8::internal::RegisterBase< SubType, kAfterLastRegister >::reg_code_.
Referenced by v8::internal::CallApiFunctionAndReturn(), v8::internal::MacroAssembler::CallDebugOnFunctionCall(), v8::internal::wasm::liftoff::EmitShiftOperation(), v8::internal::MacroAssembler::ExternalReferenceAsOperand(), v8::internal::AssemblerRiscvBase::GenInstrB(), v8::internal::AssemblerRiscvBase::GenInstrCA(), v8::internal::AssemblerRiscvBase::GenInstrCI(), v8::internal::AssemblerRiscvBase::GenInstrCIU(), v8::internal::AssemblerRiscvBase::GenInstrCIW(), v8::internal::AssemblerRiscvBase::GenInstrCL(), v8::internal::AssemblerRiscvBase::GenInstrCR(), v8::internal::AssemblerRiscvBase::GenInstrCS(), v8::internal::AssemblerRiscvBase::GenInstrCSS(), v8::internal::AssemblerRiscvBase::GenInstrI(), v8::internal::AssemblerRiscvBase::GenInstrIShift(), v8::internal::AssemblerRiscvBase::GenInstrIShiftW(), v8::internal::AssemblerRiscvBase::GenInstrJ(), v8::internal::AssemblerRiscvBase::GenInstrR(), v8::internal::AssemblerRiscvBase::GenInstrR4(), v8::internal::AssemblerRiscvBase::GenInstrRAtomic(), v8::internal::AssemblerRiscvBase::GenInstrRFrm(), v8::internal::AssemblerRiscvBase::GenInstrS(), v8::internal::AssemblerRiscvBase::GenInstrU(), v8::internal::wasm::liftoff::GetEffectiveAddress(), v8::internal::wasm::liftoff::GetMemOp(), v8::internal::MacroAssembler::InvokeFunctionCode(), v8::internal::Operand::is_reg(), v8::internal::Operand::IsExtendedRegister(), v8::internal::Operand::IsImmediate(), v8::internal::Operand::IsShiftedRegister(), v8::internal::Assembler::LoadOpFor(), v8::internal::Operand::Operand(), v8::internal::MacroAssembler::Pop(), v8::internal::MacroAssembler::Push(), v8::internal::MacroAssembler::PushCommonFrame(), v8::internal::MacroAssembler::PushStandardFrame(), v8::internal::Assembler::StoreOpFor(), v8::internal::ToNumber(), and v8::internal::Assembler::VfpRegisterIsAvailable().
no_reg()
template<typename SubType , int kAfterLastRegister>
static constexpr SubType v8::internal::RegisterBase< SubType, kAfterLastRegister >::no_reg () [inline], [static], [constexpr]
Definition at line 34 of file register-base.h.
{ return SubType{kCode_no_reg}; }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::kCode_no_reg.
operator!=()
template<typename SubType , int kAfterLastRegister>
constexpr bool v8::internal::RegisterBase< SubType, kAfterLastRegister >::operator!= (const RegisterBase< SubType, kAfterLastRegister > & other) const [inline], [constexpr]
Definition at line 57 of file register-base.h.
                                                                    {
    return reg_code_ != other.reg_code_;
  }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::reg_code_.
operator==()
template<typename SubType , int kAfterLastRegister>
constexpr bool v8::internal::RegisterBase< SubType, kAfterLastRegister >::operator== (const RegisterBase< SubType, kAfterLastRegister > & other) const [inline], [constexpr]
Definition at line 53 of file register-base.h.
                                                                    {
    return reg_code_ == other.reg_code_;
  }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::reg_code_.
Referenced by v8::internal::CPURegister::Aliases(), and v8::internal::CPURegister::operator==().
Member Data Documentation
kCode_no_reg
template<typename SubType , int kAfterLastRegister>
constexpr int8_t v8::internal::RegisterBase< SubType, kAfterLastRegister >::kCode_no_reg = -1 [static], [constexpr]
Definition at line 31 of file register-base.h.
Referenced by v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), and v8::internal::RegisterBase< SubType, kAfterLastRegister >::no_reg().
kNumRegisters
template<typename SubType , int kAfterLastRegister>
constexpr int8_t v8::internal::RegisterBase< SubType, kAfterLastRegister >::kNumRegisters = kAfterLastRegister [static], [constexpr]
Definition at line 32 of file register-base.h.
Referenced by v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), and v8::internal::RegisterBase< SubType, kAfterLastRegister >::from_code().
reg_code_
template<typename SubType , int kAfterLastRegister>
int8_t v8::internal::RegisterBase< SubType, kAfterLastRegister >::reg_code_ [private]
Definition at line 69 of file register-base.h.
Referenced by v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::operator!=(), and v8::internal::RegisterBase< SubType, kAfterLastRegister >::operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/register-base.h