v8::StackTrace Class Reference
Representation of a JavaScript stack trace.
#include <v8-debug.h>
Public Types
enum StackTraceOptions {
kLineNumber = 1
, kColumnOffset = 1 << 1 | kLineNumber
, kScriptName = 1 << 2
, kFunctionName = 1 << 3
,
kIsEval = 1 << 4
, kIsConstructor = 1 << 5
, kScriptNameOrSourceURL = 1 << 6
, kScriptId = 1 << 7
,
kExposeFramesAcrossSecurityOrigins = 1 << 8
, kOverview = kLineNumber | kColumnOffset | kScriptName | kFunctionName
, kDetailed = kOverview | kIsEval | kIsConstructor | kScriptNameOrSourceURL
 }
Flags that determine what information is placed captured for each StackFrame when grabbing the current stack trace.
Public Member Functions
int GetID () const
Returns the (unique) ID of this stack trace.
Local< StackFrame > GetFrame (Isolate *isolate, uint32_t index) const
Returns a StackFrame at a particular index.
int GetFrameCount () const
Returns the number of StackFrames.
Static Public Member Functions
static Local< StackTrace > CurrentStackTrace (Isolate *isolate, int frame_limit, StackTraceOptions options=kDetailed)
Grab a snapshot of the current JavaScript execution stack.
static Local< String > CurrentScriptNameOrSourceURL (Isolate *isolate)
Returns the first valid script name or source URL starting at the top of the JS stack.
Detailed Description
Representation of a JavaScript stack trace.
The information collected is a snapshot of the execution stack and the information remains valid after execution continues.
Definition at line 117 of file v8-debug.h.
Member Enumeration Documentation
StackTraceOptions
enum v8::StackTrace::StackTraceOptions
Flags that determine what information is placed captured for each StackFrame when grabbing the current stack trace.
Note: these options are deprecated and we always collect all available information (kDetailed).
Enumerator
kLineNumber
kColumnOffset
kScriptName
kFunctionName
kIsEval
kIsConstructor
kScriptNameOrSourceURL
kScriptId
kExposeFramesAcrossSecurityOrigins
kOverview
kDetailed
Definition at line 125 of file v8-debug.h.
                         {
    kLineNumber = 1,
    kColumnOffset = 1 << 1 | kLineNumber,
    kScriptName = 1 << 2,
    kFunctionName = 1 << 3,
    kIsEval = 1 << 4,
    kIsConstructor = 1 << 5,
    kScriptNameOrSourceURL = 1 << 6,
    kScriptId = 1 << 7,
    kExposeFramesAcrossSecurityOrigins = 1 << 8,
    kOverview = kLineNumber | kColumnOffset | kScriptName | kFunctionName,
    kDetailed = kOverview | kIsEval | kIsConstructor | kScriptNameOrSourceURL
  };
Member Function Documentation
CurrentScriptNameOrSourceURL()
Local< String > v8::StackTrace::CurrentScriptNameOrSourceURL (Isolate * isolate) [static]
Returns the first valid script name or source URL starting at the top of the JS stack.
The returned string is either an empty handle if no script name/url was found or a non-zero-length string.
This method is equivalent to calling StackTrace::CurrentStackTrace and walking the resulting frames from the beginning until a non-empty script name/url is found. The difference is that this method won't allocate a stack trace.
Definition at line 3114 of file api.cc.
                                                                          {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::String> name_or_source_url =
      i_isolate->CurrentScriptNameOrSourceURL();
  return Utils::ToLocal(name_or_source_url);
}
References v8::internal::Isolate::CurrentScriptNameOrSourceURL().
CurrentStackTrace()
Local< StackTrace > v8::StackTrace::CurrentStackTrace (Isolate * isolate, int frame_limit, StackTraceOptions options = kDetailed) [static]
Grab a snapshot of the current JavaScript execution stack.
Parameters
frame_limit The maximum number of stack frames we want to capture.
options Enumerates the set of things we will capture for each StackFrame.
Definition at line 3104 of file api.cc.
                                                                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::StackTraceInfo> stack_trace =
      i_isolate->CaptureDetailedStackTrace(frame_limit, options);
  return Utils::StackTraceToLocal(stack_trace);
}
References v8::internal::Isolate::CaptureDetailedStackTrace().
Referenced by v8_inspector::AsyncStackTrace::capture(), and v8_inspector::V8StackTraceImpl::capture().
GetFrame()
Local< StackFrame > v8::StackTrace::GetFrame (Isolate * isolate, uint32_t index) const
Returns a StackFrame at a particular index.
Definition at line 3091 of file api.cc.
                                                             {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  return Utils::StackFrameToLocal(
      i::direct_handle(self->get(index), i_isolate));
}
References v8::internal::direct_handle(), v8::internal::index, and v8::Utils::OpenDirectHandle().
GetFrameCount()
int v8::StackTrace::GetFrameCount () const
Returns the number of StackFrames.
Definition at line 3099 of file api.cc.
                                    {
  auto self = Utils::OpenDirectHandle(this);
  return self->length();
}
References v8::Utils::OpenDirectHandle().
GetID()
int v8::StackTrace::GetID () const
Returns the (unique) ID of this stack trace.
Definition at line 3086 of file api.cc.
                            {
  auto self = Utils::OpenDirectHandle(this);
  return self->id();
}
References v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-debug.h
/mnt/V8SourceCode/src/api/api.cc