v8::internal::LiteralBoilerplateBuilder Class Reference
#include <ast.h>
Public Types
enum DepthKind { kUninitialized
, kShallow
, kNotShallow
 }
Public Member Functions
bool is_initialized () const
DepthKind depth () const
bool is_shallow () const
bool needs_initial_allocation_site () const
int ComputeFlags (bool disable_mementos=false) const
bool is_simple () const
ElementsKind boilerplate_descriptor_kind () const
Static Public Member Functions
template<typename IsolateT >
static DirectHandle< Object > GetBoilerplateValue (Expression *expression, IsolateT *isolate)
Static Public Attributes
static constexpr int kDepthKindBits = 2
Protected Types
template<class T , int size>
using NextBitField = BoilerplateDescriptorKindField::Next< T, size >
Protected Member Functions
LiteralBoilerplateBuilder ()
void set_is_simple (bool is_simple)
void set_boilerplate_descriptor_kind (ElementsKind kind)
void set_depth (DepthKind depth)
void set_needs_initial_allocation_site (bool required)
template<typename IsolateT >
void BuildConstants (IsolateT *isolate, MaterializedLiteral *expr)
Static Protected Member Functions
static void InitDepthAndFlags (MaterializedLiteral *expr)
Protected Attributes
uint32_t bit_field_
Private Types
using DepthField = base::BitField< DepthKind, 0, kDepthKindBits >
using NeedsInitialAllocationSiteField = DepthField::Next< bool, 1 >
using IsSimpleField = NeedsInitialAllocationSiteField::Next< bool, 1 >
using BoilerplateDescriptorKindField = IsSimpleField::Next< ElementsKind, kFastElementsKindBits >
Detailed Description
Definition at line 1135 of file ast.h.
Member Typedef Documentation
BoilerplateDescriptorKindField
using v8::internal::LiteralBoilerplateBuilder::BoilerplateDescriptorKindField = IsSimpleField::Next<ElementsKind, kFastElementsKindBits> [private]
Definition at line 1189 of file ast.h.
DepthField
using v8::internal::LiteralBoilerplateBuilder::DepthField = base::BitField<DepthKind, 0, kDepthKindBits> [private]
Definition at line 1186 of file ast.h.
IsSimpleField
using v8::internal::LiteralBoilerplateBuilder::IsSimpleField = NeedsInitialAllocationSiteField::Next<bool, 1> [private]
Definition at line 1188 of file ast.h.
NeedsInitialAllocationSiteField
using v8::internal::LiteralBoilerplateBuilder::NeedsInitialAllocationSiteField = DepthField::Next<bool, 1> [private]
Definition at line 1187 of file ast.h.
NextBitField
template<class T , int size>
using v8::internal::LiteralBoilerplateBuilder::NextBitField = BoilerplateDescriptorKindField::Next<T, size> [protected]
Definition at line 1229 of file ast.h.
Member Enumeration Documentation
DepthKind
enum v8::internal::LiteralBoilerplateBuilder::DepthKind
Enumerator
kUninitialized
kShallow
kNotShallow
Definition at line 1137 of file ast.h.
{ kUninitialized, kShallow, kNotShallow };
Constructor & Destructor Documentation
LiteralBoilerplateBuilder()
v8::internal::LiteralBoilerplateBuilder::LiteralBoilerplateBuilder () [inline], [protected]
Definition at line 1195 of file ast.h.
                              {
    bit_field_ =
        DepthField::encode(kUninitialized) |
        NeedsInitialAllocationSiteField::encode(false) |
        IsSimpleField::encode(false) |
        BoilerplateDescriptorKindField::encode(FIRST_FAST_ELEMENTS_KIND);
  }
References bit_field_, v8::base::BitField< T, shift, size, U >::encode(), v8::internal::FIRST_FAST_ELEMENTS_KIND, and kUninitialized.
Member Function Documentation
boilerplate_descriptor_kind()
ElementsKind v8::internal::LiteralBoilerplateBuilder::boilerplate_descriptor_kind () const [inline]
Definition at line 1177 of file ast.h.
                                                   {
    return BoilerplateDescriptorKindField::decode(bit_field_);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::ArrayLiteralBoilerplateBuilder::BuildBoilerplateDescription().
BuildConstants()
template<typename IsolateT >
void v8::internal::LiteralBoilerplateBuilder::BuildConstants (IsolateT * isolate, MaterializedLiteral * expr) [protected]
Definition at line 792 of file ast.cc.
                                                                          {
  if (expr->IsArrayLiteral()) {
    expr->AsArrayLiteral()->builder()->BuildBoilerplateDescription(isolate);
    return;
  }
  if (expr->IsObjectLiteral()) {
    expr->AsObjectLiteral()->builder()->BuildBoilerplateDescription(isolate);
    return;
  }
  DCHECK(expr->IsRegExpLiteral());
}
References v8::internal::DCHECK().
Referenced by v8::internal::ObjectLiteralBoilerplateBuilder::BuildBoilerplateDescription(), and v8::internal::ArrayLiteralBoilerplateBuilder::BuildBoilerplateDescription().
ComputeFlags()
int v8::internal::LiteralBoilerplateBuilder::ComputeFlags (bool disable_mementos = false) const [inline]
Definition at line 1164 of file ast.h.
                                                        {
    int flags = AggregateLiteral::kNoFlags;
    if (is_shallow()) flags |= AggregateLiteral::kIsShallow;
    if (disable_mementos) flags |= AggregateLiteral::kDisableMementos;
    if (needs_initial_allocation_site())
      flags |= AggregateLiteral::kNeedsInitialAllocationSite;
    return flags;
  }
References v8::internal::flags, is_shallow(), v8::internal::AggregateLiteral::kDisableMementos, v8::internal::AggregateLiteral::kIsShallow, v8::internal::AggregateLiteral::kNeedsInitialAllocationSite, v8::internal::AggregateLiteral::kNoFlags, and needs_initial_allocation_site().
Referenced by v8::internal::ObjectLiteralBoilerplateBuilder::ComputeFlags(), and v8::internal::ArrayLiteralBoilerplateBuilder::ComputeFlags().
depth()
DepthKind v8::internal::LiteralBoilerplateBuilder::depth () const [inline]
Definition at line 1145 of file ast.h.
                          {
    DCHECK(is_initialized());
    return DepthField::decode(bit_field_);
  }
References bit_field_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), and is_initialized().
Referenced by v8::internal::ArrayLiteralBoilerplateBuilder::BuildBoilerplateDescription(), is_shallow(), and set_depth().
GetBoilerplateValue()
template<typename IsolateT >
DirectHandle< Object > v8::internal::LiteralBoilerplateBuilder::GetBoilerplateValue (Expression * expression, IsolateT * isolate) [static]
Definition at line 556 of file ast.cc.
                                               {
  if (expression->IsLiteral()) {
    return expression->AsLiteral()->BuildValue(isolate);
  }
  if (expression->IsCompileTimeValue()) {
    if (expression->IsObjectLiteral()) {
      ObjectLiteral* object_literal = expression->AsObjectLiteral();
      DCHECK(object_literal->builder()->is_simple());
      return object_literal->builder()->boilerplate_description();
    } else {
      DCHECK(expression->IsArrayLiteral());
      ArrayLiteral* array_literal = expression->AsArrayLiteral();
      DCHECK(array_literal->builder()->is_simple());
      return array_literal->builder()->boilerplate_description();
    }
  }
  return isolate->factory()->uninitialized_value();
}
References v8::internal::ObjectLiteralBoilerplateBuilder::boilerplate_description(), v8::internal::ArrayLiteralBoilerplateBuilder::boilerplate_description(), v8::internal::ObjectLiteral::builder(), v8::internal::ArrayLiteral::builder(), v8::internal::DCHECK(), is_simple(), and v8::internal::Expression::IsCompileTimeValue().
Referenced by v8::internal::ObjectLiteralBoilerplateBuilder::BuildBoilerplateDescription(), and v8::internal::ArrayLiteralBoilerplateBuilder::BuildBoilerplateDescription().
InitDepthAndFlags()
void v8::internal::LiteralBoilerplateBuilder::InitDepthAndFlags (MaterializedLiteral * expr) [static], [protected]
Definition at line 768 of file ast.cc.
                                                                           {
  if (expr->IsArrayLiteral()) {
    return expr->AsArrayLiteral()->builder()->InitDepthAndFlags();
  }
  if (expr->IsObjectLiteral()) {
    return expr->AsObjectLiteral()->builder()->InitDepthAndFlags();
  }
  DCHECK(expr->IsRegExpLiteral());
}
References v8::internal::DCHECK().
Referenced by v8::internal::ObjectLiteralBoilerplateBuilder::InitDepthAndFlags().
is_initialized()
bool v8::internal::LiteralBoilerplateBuilder::is_initialized () const [inline]
Definition at line 1142 of file ast.h.
                              {
    return kUninitialized != DepthField::decode(bit_field_);
  }
References bit_field_, v8::base::BitField< T, shift, size, U >::decode(), and kUninitialized.
Referenced by depth(), v8::internal::ObjectLiteralBoilerplateBuilder::InitDepthAndFlags(), v8::internal::ObjectLiteralBoilerplateBuilder::is_empty(), and set_depth().
is_shallow()
bool v8::internal::LiteralBoilerplateBuilder::is_shallow () const [inline]
Definition at line 1159 of file ast.h.
{ return depth() == kShallow; }
References depth(), and kShallow.
Referenced by ComputeFlags().
is_simple()
bool v8::internal::LiteralBoilerplateBuilder::is_simple () const [inline]
Definition at line 1175 of file ast.h.
{ return IsSimpleField::decode(bit_field_); }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::ArrayLiteralBoilerplateBuilder::BuildBoilerplateDescription(), GetBoilerplateValue(), v8::internal::ObjectLiteralBoilerplateBuilder::InitDepthAndFlags(), and set_is_simple().
needs_initial_allocation_site()
bool v8::internal::LiteralBoilerplateBuilder::needs_initial_allocation_site () const [inline]
Definition at line 1160 of file ast.h.
                                             {
    return NeedsInitialAllocationSiteField::decode(bit_field_);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by ComputeFlags(), and v8::internal::ObjectLiteralBoilerplateBuilder::InitDepthAndFlags().
set_boilerplate_descriptor_kind()
void v8::internal::LiteralBoilerplateBuilder::set_boilerplate_descriptor_kind (ElementsKind kind) [inline], [protected]
Definition at line 1207 of file ast.h.
                                                          {
    DCHECK(IsFastElementsKind(kind));
    bit_field_ = BoilerplateDescriptorKindField::update(bit_field_, kind);
  }
References bit_field_, v8::internal::DCHECK(), v8::internal::IsFastElementsKind(), and v8::base::BitField< T, shift, size, U >::update().
set_depth()
void v8::internal::LiteralBoilerplateBuilder::set_depth (DepthKind depth) [inline], [protected]
Definition at line 1212 of file ast.h.
                                  {
    DCHECK(!is_initialized());
    bit_field_ = DepthField::update(bit_field_, depth);
  }
References bit_field_, v8::internal::DCHECK(), depth(), is_initialized(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::ObjectLiteralBoilerplateBuilder::InitDepthAndFlags().
set_is_simple()
void v8::internal::LiteralBoilerplateBuilder::set_is_simple (bool is_simple) [inline], [protected]
Definition at line 1203 of file ast.h.
                                     {
    bit_field_ = IsSimpleField::update(bit_field_, is_simple);
  }
References bit_field_, is_simple(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::ObjectLiteralBoilerplateBuilder::InitDepthAndFlags().
set_needs_initial_allocation_site()
void v8::internal::LiteralBoilerplateBuilder::set_needs_initial_allocation_site (bool required) [inline], [protected]
Definition at line 1217 of file ast.h.
                                                        {
    bit_field_ = NeedsInitialAllocationSiteField::update(bit_field_, required);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::ObjectLiteralBoilerplateBuilder::InitDepthAndFlags().
Member Data Documentation
bit_field_
uint32_t v8::internal::LiteralBoilerplateBuilder::bit_field_ [protected]
Definition at line 1193 of file ast.h.
Referenced by boilerplate_descriptor_kind(), depth(), v8::internal::ObjectLiteralBoilerplateBuilder::fast_elements(), v8::internal::ObjectLiteralBoilerplateBuilder::has_elements(), v8::internal::ObjectLiteralBoilerplateBuilder::has_null_prototype(), v8::internal::ObjectLiteralBoilerplateBuilder::has_rest_property(), is_initialized(), is_simple(), LiteralBoilerplateBuilder(), needs_initial_allocation_site(), v8::internal::ObjectLiteralBoilerplateBuilder::ObjectLiteralBoilerplateBuilder(), set_boilerplate_descriptor_kind(), set_depth(), v8::internal::ObjectLiteralBoilerplateBuilder::set_fast_elements(), v8::internal::ObjectLiteralBoilerplateBuilder::set_has_elements(), v8::internal::ObjectLiteralBoilerplateBuilder::set_has_null_protoype(), set_is_simple(), and set_needs_initial_allocation_site().
kDepthKindBits
constexpr int v8::internal::LiteralBoilerplateBuilder::kDepthKindBits = 2 [static], [constexpr]
Definition at line 1139 of file ast.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc