v8::internal::SerializerReference Class Reference
#include <references.h>
Public Member Functions
bool is_back_reference () const
uint32_t back_ref_index () const
bool is_off_heap_backing_store_reference () const
uint32_t off_heap_backing_store_index () const
bool is_attached_reference () const
uint32_t attached_reference_index () const
bool is_builtin_reference () const
uint32_t builtin_index () const
Static Public Member Functions
static SerializerReference BackReference (uint32_t index)
static SerializerReference OffHeapBackingStoreReference (uint32_t index)
static SerializerReference AttachedReference (uint32_t index)
static SerializerReference BuiltinReference (uint32_t index)
Private Types
enum SpecialValueType { kBackReference
, kAttachedReference
, kOffHeapBackingStore
, kBuiltinReference
 }
using TypeBits = base::BitField< SpecialValueType, 0, 2 >
using ValueBits = TypeBits::Next< uint32_t, 32 - TypeBits::kSize >
Private Member Functions
SerializerReference (SpecialValueType type, uint32_t value)
Private Attributes
uint32_t bit_field_
Friends
class SerializerReferenceMap
Detailed Description
Definition at line 26 of file references.h.
Member Typedef Documentation
TypeBits
using v8::internal::SerializerReference::TypeBits = base::BitField<SpecialValueType, 0, 2> [private]
Definition at line 92 of file references.h.
ValueBits
using v8::internal::SerializerReference::ValueBits = TypeBits::Next<uint32_t, 32 - TypeBits::kSize> [private]
Definition at line 93 of file references.h.
Member Enumeration Documentation
SpecialValueType
enum v8::internal::SerializerReference::SpecialValueType [private]
Enumerator
kBackReference
kAttachedReference
kOffHeapBackingStore
kBuiltinReference
Definition at line 28 of file references.h.
                        {
    kBackReference,
    kAttachedReference,
    kOffHeapBackingStore,
    kBuiltinReference,
  };
Constructor & Destructor Documentation
SerializerReference()
v8::internal::SerializerReference::SerializerReference (SpecialValueType type, uint32_t value) [inline], [private]
Definition at line 35 of file references.h.
      : bit_field_(TypeBits::encode(type) | ValueBits::encode(value)) {}
Referenced by AttachedReference(), BackReference(), BuiltinReference(), and OffHeapBackingStoreReference().
Member Function Documentation
attached_reference_index()
uint32_t v8::internal::SerializerReference::attached_reference_index () const [inline]
Definition at line 77 of file references.h.
                                            {
    DCHECK(is_attached_reference());
    return ValueBits::decode(bit_field_);
  }
References bit_field_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), and is_attached_reference().
Referenced by v8::internal::Serializer::PutAttachedReference(), and v8::internal::Serializer::SerializeBackReference().
AttachedReference()
static SerializerReference v8::internal::SerializerReference::AttachedReference (uint32_t index) [inline], [static]
Definition at line 47 of file references.h.
                                                               {
    return SerializerReference(kAttachedReference, index);
  }
References v8::internal::index, kAttachedReference, and SerializerReference().
Referenced by v8::internal::SerializerReferenceMap::AddAttachedReference().
back_ref_index()
uint32_t v8::internal::SerializerReference::back_ref_index () const [inline]
Definition at line 59 of file references.h.
                                  {
    DCHECK(is_back_reference());
    return ValueBits::decode(bit_field_);
  }
References bit_field_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), and is_back_reference().
Referenced by v8::internal::Serializer::PutBackReference(), v8::internal::ContextSerializer::SerializeApiWrapperFields(), v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields(), and v8::internal::Serializer::ObjectSerializer::SerializePrologue().
BackReference()
static SerializerReference v8::internal::SerializerReference::BackReference (uint32_t index) [inline], [static]
Definition at line 39 of file references.h.
                                                           {
    return SerializerReference(kBackReference, index);
  }
References v8::internal::index, kBackReference, and SerializerReference().
Referenced by v8::internal::Serializer::ObjectSerializer::SerializePrologue().
builtin_index()
uint32_t v8::internal::SerializerReference::builtin_index () const [inline]
Definition at line 86 of file references.h.
                                 {
    DCHECK(is_builtin_reference());
    return ValueBits::decode(bit_field_);
  }
References bit_field_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), and is_builtin_reference().
BuiltinReference()
static SerializerReference v8::internal::SerializerReference::BuiltinReference (uint32_t index) [inline], [static]
Definition at line 51 of file references.h.
                                                              {
    return SerializerReference(kBuiltinReference, index);
  }
References v8::internal::index, kBuiltinReference, and SerializerReference().
is_attached_reference()
bool v8::internal::SerializerReference::is_attached_reference () const [inline]
Definition at line 73 of file references.h.
                                     {
    return TypeBits::decode(bit_field_) == kAttachedReference;
  }
References bit_field_, v8::base::BitField< T, shift, size, U >::decode(), and kAttachedReference.
Referenced by attached_reference_index(), v8::internal::Serializer::PutAttachedReference(), and v8::internal::Serializer::SerializeBackReference().
is_back_reference()
bool v8::internal::SerializerReference::is_back_reference () const [inline]
Definition at line 55 of file references.h.
                                 {
    return TypeBits::decode(bit_field_) == kBackReference;
  }
References bit_field_, v8::base::BitField< T, shift, size, U >::decode(), and kBackReference.
Referenced by back_ref_index(), v8::internal::ContextSerializer::SerializeApiWrapperFields(), v8::internal::Serializer::SerializeBackReference(), and v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields().
is_builtin_reference()
bool v8::internal::SerializerReference::is_builtin_reference () const [inline]
Definition at line 82 of file references.h.
                                    {
    return TypeBits::decode(bit_field_) == kBuiltinReference;
  }
References bit_field_, v8::base::BitField< T, shift, size, U >::decode(), and kBuiltinReference.
Referenced by builtin_index().
is_off_heap_backing_store_reference()
bool v8::internal::SerializerReference::is_off_heap_backing_store_reference () const [inline]
Definition at line 64 of file references.h.
                                                   {
    return TypeBits::decode(bit_field_) == kOffHeapBackingStore;
  }
References bit_field_, v8::base::BitField< T, shift, size, U >::decode(), and kOffHeapBackingStore.
Referenced by off_heap_backing_store_index().
off_heap_backing_store_index()
uint32_t v8::internal::SerializerReference::off_heap_backing_store_index () const [inline]
Definition at line 68 of file references.h.
                                                {
    DCHECK(is_off_heap_backing_store_reference());
    return ValueBits::decode(bit_field_);
  }
References bit_field_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), and is_off_heap_backing_store_reference().
Referenced by v8::internal::Serializer::ObjectSerializer::SerializeBackingStore().
OffHeapBackingStoreReference()
static SerializerReference v8::internal::SerializerReference::OffHeapBackingStoreReference (uint32_t index) [inline], [static]
Definition at line 43 of file references.h.
                                                                          {
    return SerializerReference(kOffHeapBackingStore, index);
  }
References v8::internal::index, kOffHeapBackingStore, and SerializerReference().
Referenced by v8::internal::Serializer::ObjectSerializer::SerializeBackingStore().
Friends And Related Function Documentation
SerializerReferenceMap
friend class SerializerReferenceMap [friend]
Definition at line 97 of file references.h.
Member Data Documentation
bit_field_
uint32_t v8::internal::SerializerReference::bit_field_ [private]
Definition at line 95 of file references.h.
Referenced by attached_reference_index(), back_ref_index(), builtin_index(), is_attached_reference(), is_back_reference(), is_builtin_reference(), is_off_heap_backing_store_reference(), and off_heap_backing_store_index().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/references.h