v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet Class Reference
Public Member Functions
OperandSet (ZoneVector< InstructionOperand > *buffer)
void InsertOp (const InstructionOperand &op)
bool Contains (const InstructionOperand &op) const
bool ContainsOpOrAlias (const InstructionOperand &op) const
Static Private Member Functions
static bool HasMixedFPReps (int reps)
Private Attributes
ZoneVector< InstructionOperand > * set_
int fp_reps_
Detailed Description
Definition at line 30 of file move-optimizer.cc.
Constructor & Destructor Documentation
OperandSet()
v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::OperandSet (ZoneVector< InstructionOperand > * buffer) [inline], [explicit]
Definition at line 32 of file move-optimizer.cc.
      : set_(buffer), fp_reps_(0) {
    buffer->clear();
  }
References v8::internal::ZoneVector< T >::clear().
Member Function Documentation
Contains()
bool v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::Contains (const InstructionOperand & op) const [inline]
Definition at line 44 of file move-optimizer.cc.
                                                    {
    for (const InstructionOperand& elem : *set_) {
      if (elem.EqualsCanonicalized(op)) return true;
    }
    return false;
  }
ContainsOpOrAlias()
bool v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::ContainsOpOrAlias (const InstructionOperand & op) const [inline]
Definition at line 51 of file move-optimizer.cc.
                                                             {
    if (Contains(op)) return true;
    if (kFPAliasing == AliasingKind::kCombine && op.IsFPRegister()) {
      // Platforms where FP registers have complex aliasing need extra checks.
      const LocationOperand& loc = LocationOperand::cast(op);
      MachineRepresentation rep = loc.representation();
      // If haven't encountered mixed rep FP registers, skip the extra checks.
      if (!HasMixedFPReps(fp_reps_ | RepresentationBit(rep))) return false;
      // Check register against aliasing registers of other FP representations.
      MachineRepresentation other_rep1, other_rep2;
      switch (rep) {
        case MachineRepresentation::kFloat32:
          other_rep1 = MachineRepresentation::kFloat64;
          other_rep2 = MachineRepresentation::kSimd128;
          break;
        case MachineRepresentation::kFloat64:
          other_rep1 = MachineRepresentation::kFloat32;
          other_rep2 = MachineRepresentation::kSimd128;
          break;
        case MachineRepresentation::kSimd128:
          other_rep1 = MachineRepresentation::kFloat32;
          other_rep2 = MachineRepresentation::kFloat64;
          break;
        default:
          UNREACHABLE();
      }
      const RegisterConfiguration* config = RegisterConfiguration::Default();
      int base = -1;
      int aliases =
          config->GetAliases(rep, loc.register_code(), other_rep1, &base);
      DCHECK(aliases > 0 || (aliases == 0 && base == -1));
      while (aliases--) {
        if (Contains(AllocatedOperand(LocationOperand::REGISTER, other_rep1,
                                      base + aliases))) {
          return true;
        }
      }
      aliases = config->GetAliases(rep, loc.register_code(), other_rep2, &base);
      DCHECK(aliases > 0 || (aliases == 0 && base == -1));
      while (aliases--) {
        if (Contains(AllocatedOperand(LocationOperand::REGISTER, other_rep2,
                                      base + aliases))) {
          return true;
        }
      }
    }
    return false;
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::anonymous_namespace{read-only-promotion.cc}::Contains(), v8::internal::DCHECK(), v8::internal::RegisterConfiguration::Default(), v8::internal::RegisterConfiguration::GetAliases(), v8::internal::compiler::InstructionOperand::IsFPRegister(), v8::internal::kCombine, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kFPAliasing, v8::internal::kSimd128, v8::internal::loc, v8::internal::compiler::LocationOperand::REGISTER, v8::internal::RepresentationBit(), and v8::internal::UNREACHABLE().
HasMixedFPReps()
static bool v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::HasMixedFPReps (int reps) [inline], [static], [private]
Definition at line 103 of file move-optimizer.cc.
                                       {
    return reps && !base::bits::IsPowerOfTwo(reps);
  }
References v8::base::bits::IsPowerOfTwo().
InsertOp()
void v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::InsertOp (const InstructionOperand & op) [inline]
Definition at line 37 of file move-optimizer.cc.
                                              {
    set_->push_back(op);
    if (kFPAliasing == AliasingKind::kCombine && op.IsFPRegister())
      fp_reps_ |= RepresentationBit(LocationOperand::cast(op).representation());
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::compiler::InstructionOperand::IsFPRegister(), v8::internal::kCombine, v8::internal::kFPAliasing, and v8::internal::RepresentationBit().
Member Data Documentation
fp_reps_
int v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::fp_reps_ [private]
Definition at line 108 of file move-optimizer.cc.
set_
ZoneVector<InstructionOperand>* v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::set_ [private]
Definition at line 107 of file move-optimizer.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/move-optimizer.cc