v8::internal::SharedFeedbackSlot Class Reference
#include <feedback-vector.h>
Public Member Functions
SharedFeedbackSlot (FeedbackVectorSpec *spec, FeedbackSlotKind kind)
FeedbackSlot Get ()
Private Attributes
FeedbackSlotKind kind_
FeedbackSlot slot_
FeedbackVectorSpec * spec_
Detailed Description
Definition at line 703 of file feedback-vector.h.
Constructor & Destructor Documentation
SharedFeedbackSlot()
v8::internal::SharedFeedbackSlot::SharedFeedbackSlot (FeedbackVectorSpec * spec, FeedbackSlotKind kind) [inline]
Definition at line 706 of file feedback-vector.h.
      : kind_(kind), spec_(spec) {}
Member Function Documentation
Get()
FeedbackSlot v8::internal::SharedFeedbackSlot::Get () [inline]
Definition at line 709 of file feedback-vector.h.
                     {
    if (slot_.IsInvalid()) slot_ = spec_->AddSlot(kind_);
    return slot_;
  }
References v8::internal::FeedbackVectorSpec::AddSlot(), v8::internal::FeedbackSlot::IsInvalid(), kind_, slot_, and spec_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), and v8::internal::interpreter::BytecodeGenerator::GetDummyCompareICSlot().
Member Data Documentation
kind_
FeedbackSlotKind v8::internal::SharedFeedbackSlot::kind_ [private]
Definition at line 715 of file feedback-vector.h.
Referenced by Get().
slot_
FeedbackSlot v8::internal::SharedFeedbackSlot::slot_ [private]
Definition at line 716 of file feedback-vector.h.
Referenced by Get().
spec_
FeedbackVectorSpec* v8::internal::SharedFeedbackSlot::spec_ [private]
Definition at line 717 of file feedback-vector.h.
Referenced by Get().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/feedback-vector.h