v8::DictionaryTemplate Class Reference
A template to create dictionary objects at runtime.
#include <v8-template.h>
Public Member Functions
V8_WARN_UNUSED_RESULT Local< Object > NewInstance (Local< Context > context, MemorySpan< MaybeLocal< Value >> property_values)
Creates a new instance of this template.
Static Public Member Functions
static Local< DictionaryTemplate > New (Isolate *isolate, MemorySpan< const std::string_view > names)
Creates a new template.
static DictionaryTemplate * Cast (Data *data)
Private Member Functions
DictionaryTemplate ()
Static Private Member Functions
static void CheckCast (Data *that)
Detailed Description
A template to create dictionary objects at runtime.
Definition at line 1074 of file v8-template.h.
Constructor & Destructor Documentation
DictionaryTemplate()
v8::DictionaryTemplate::DictionaryTemplate () [private]
Member Function Documentation
Cast()
DictionaryTemplate * v8::DictionaryTemplate::Cast (Data * data) [inline], [static]
Definition at line 1151 of file v8-template.h.
                                                       {
#ifdef V8_ENABLE_CHECKS
  CheckCast(data);
#endif
  return reinterpret_cast<DictionaryTemplate*>(data);
}
References CheckCast().
CheckCast()
void v8::DictionaryTemplate::CheckCast (Data * that) [static], [private]
Definition at line 7339 of file api.cc.
                                               {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsDictionaryTemplateInfo(*obj),
                  "v8::DictionaryTemplate::Cast",
                  "Value is not an DictionaryTemplate");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Referenced by Cast().
New()
Local< DictionaryTemplate > v8::DictionaryTemplate::New (Isolate * isolate, MemorySpan< const std::string_view > names) [static]
Creates a new template.
Also declares data properties that can be passed on instantiation of the template. Properties can only be declared on construction and are then immutable. The values are passed on creating the object via NewInstance().
Parameters
names the keys that can be passed on instantiation.
Definition at line 1726 of file api.cc.
                                                              {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_DictionaryTemplate_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  return Utils::ToLocal(i::DictionaryTemplateInfo::Create(i_isolate, names));
}
References v8::internal::DictionaryTemplateInfo::Create().
NewInstance()
Local< Object > v8::DictionaryTemplate::NewInstance (Local< Context > context, MemorySpan< MaybeLocal< Value >> property_values)
Creates a new instance of this template.
Parameters
context The context used to create the dictionary object.
property_values Values of properties that were declared using DeclareDataProperties(). The span only passes values and expectes the order to match the declaration. Non-existent properties are signaled via empty MaybeLocals.
Definition at line 1735 of file api.cc.
                                                                           {
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(
      i_isolate, RCCId::kAPI_DictionaryTemplate_NewInstance);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  auto self = Utils::OpenDirectHandle(this);
  return ToApiHandle<Object>(i::DictionaryTemplateInfo::NewInstance(
      Utils::OpenDirectHandle(*context), self, property_values));
}
References v8::internal::Isolate::Current(), v8::internal::DictionaryTemplateInfo::NewInstance(), and v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-template.h
/mnt/V8SourceCode/src/api/api.cc