v8::internal::wasm::CallSiteFeedback Class Reference
#include <wasm-module.h>
Classes
struct PolymorphicCase
Public Member Functions
CallSiteFeedback ()
CallSiteFeedback (int function_index, int call_count)
CallSiteFeedback (PolymorphicCase *polymorphic_cases, int num_cases)
CallSiteFeedback (const CallSiteFeedback &other) V8_NOEXCEPT
CallSiteFeedback (CallSiteFeedback &&other) V8_NOEXCEPT
CallSiteFeedback & operator= (const CallSiteFeedback &other) V8_NOEXCEPT
CallSiteFeedback & operator= (CallSiteFeedback &&other) V8_NOEXCEPT
~CallSiteFeedback ()
int num_cases () const
int function_index (int i) const
int call_count (int i) const
bool has_non_inlineable_targets () const
void set_has_non_inlineable_targets (bool has_non_inlineable_targets)
bool is_megamorphic () const
Static Public Member Functions
static CallSiteFeedback CreateMegamorphic ()
Private Member Functions
bool is_monomorphic () const
bool is_polymorphic () const
bool is_invalid () const
const PolymorphicCase * polymorphic_storage () const
Private Attributes
int index_or_count_
bool has_non_inlineable_targets_ = false
bool is_megamorphic_ = false
intptr_t frequency_or_ool_
Detailed Description
Definition at line 492 of file wasm-module.h.
Constructor & Destructor Documentation
CallSiteFeedback() [1/5]
v8::internal::wasm::CallSiteFeedback::CallSiteFeedback () [inline]
Definition at line 511 of file wasm-module.h.
: index_or_count_(-1), frequency_or_ool_(0) {}
CallSiteFeedback() [2/5]
v8::internal::wasm::CallSiteFeedback::CallSiteFeedback (int function_index, int call_count) [inline]
Definition at line 512 of file wasm-module.h.
      : index_or_count_(function_index), frequency_or_ool_(call_count) {}
CallSiteFeedback() [3/5]
v8::internal::wasm::CallSiteFeedback::CallSiteFeedback (PolymorphicCase * polymorphic_cases, int num_cases) [inline]
Definition at line 514 of file wasm-module.h.
      : index_or_count_(-num_cases),
        frequency_or_ool_(reinterpret_cast<intptr_t>(polymorphic_cases)) {}
CallSiteFeedback() [4/5]
v8::internal::wasm::CallSiteFeedback::CallSiteFeedback (const CallSiteFeedback & other) [inline]
Definition at line 521 of file wasm-module.h.
{ *this = other; }
CallSiteFeedback() [5/5]
v8::internal::wasm::CallSiteFeedback::CallSiteFeedback (CallSiteFeedback && other) [inline]
Definition at line 522 of file wasm-module.h.
{ *this = other; }
 CallSiteFeedback()
v8::internal::wasm::CallSiteFeedback::~CallSiteFeedback () [inline]
Definition at line 551 of file wasm-module.h.
                      {
    if (is_polymorphic()) delete[] polymorphic_storage();
  }
Member Function Documentation
call_count()
int v8::internal::wasm::CallSiteFeedback::call_count (int i) const [inline]
Definition at line 565 of file wasm-module.h.
                              {
    DCHECK(!is_invalid() && !is_megamorphic());
    if (is_monomorphic()) return static_cast<int>(frequency_or_ool_);
    return polymorphic_storage()[i].absolute_call_frequency;
  }
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction(), and v8::internal::wasm::ProfileGenerator::SerializeTypeFeedback().
CreateMegamorphic()
static CallSiteFeedback v8::internal::wasm::CallSiteFeedback::CreateMegamorphic () [inline], [static]
Definition at line 499 of file wasm-module.h.
                                              {
    CallSiteFeedback feedback;
    feedback.is_megamorphic_ = true;
    DCHECK(!feedback.is_invalid());
    DCHECK(!feedback.is_monomorphic());
    DCHECK(!feedback.is_polymorphic());
    DCHECK(feedback.is_megamorphic());
    return feedback;
  }
References v8::internal::DCHECK(), is_invalid(), is_megamorphic(), is_megamorphic_, is_monomorphic(), and is_polymorphic().
Referenced by v8::internal::wasm::FeedbackMaker::FinalizeCall().
function_index()
int v8::internal::wasm::CallSiteFeedback::function_index (int i) const [inline]
Definition at line 560 of file wasm-module.h.
                                  {
    DCHECK(!is_invalid() && !is_megamorphic());
    if (is_monomorphic()) return index_or_count_;
    return polymorphic_storage()[i].function_index;
  }
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction(), and v8::internal::wasm::ProfileGenerator::SerializeTypeFeedback().
has_non_inlineable_targets()
bool v8::internal::wasm::CallSiteFeedback::has_non_inlineable_targets () const [inline]
Definition at line 570 of file wasm-module.h.
                                          {
    return has_non_inlineable_targets_;
  }
Referenced by v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction().
is_invalid()
bool v8::internal::wasm::CallSiteFeedback::is_invalid () const [inline], [private]
Definition at line 582 of file wasm-module.h.
{ return index_or_count_ == -1 && !is_megamorphic_; }
Referenced by CreateMegamorphic().
is_megamorphic()
bool v8::internal::wasm::CallSiteFeedback::is_megamorphic () const [inline]
Definition at line 577 of file wasm-module.h.
{ return is_megamorphic_; }
Referenced by CreateMegamorphic(), and v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction().
is_monomorphic()
bool v8::internal::wasm::CallSiteFeedback::is_monomorphic () const [inline], [private]
Definition at line 580 of file wasm-module.h.
{ return index_or_count_ >= 0; }
Referenced by CreateMegamorphic().
is_polymorphic()
bool v8::internal::wasm::CallSiteFeedback::is_polymorphic () const [inline], [private]
Definition at line 581 of file wasm-module.h.
{ return index_or_count_ <= -2; }
Referenced by CreateMegamorphic().
num_cases()
int v8::internal::wasm::CallSiteFeedback::num_cases () const [inline]
Definition at line 555 of file wasm-module.h.
                        {
    if (is_monomorphic()) return 1;
    if (is_invalid() || is_megamorphic()) return 0;
    return -index_or_count_;
  }
Referenced by v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction(), and v8::internal::wasm::ProfileGenerator::SerializeTypeFeedback().
operator=() [1/2]
CallSiteFeedback& v8::internal::wasm::CallSiteFeedback::operator= (CallSiteFeedback && other) [inline]
Definition at line 540 of file wasm-module.h.
                                                                    {
    if (this != &other) {
      index_or_count_ = other.index_or_count_;
      frequency_or_ool_ = other.frequency_or_ool_;
      other.frequency_or_ool_ = 0;
    }
    has_non_inlineable_targets_ = other.has_non_inlineable_targets_;
    is_megamorphic_ = other.is_megamorphic_;
    return *this;
  }
operator=() [2/2]
CallSiteFeedback& v8::internal::wasm::CallSiteFeedback::operator= (const CallSiteFeedback & other) [inline]
Definition at line 523 of file wasm-module.h.
                                                                         {
    index_or_count_ = other.index_or_count_;
    if (other.is_polymorphic()) {
      int num_cases = other.num_cases();
      PolymorphicCase* polymorphic = new PolymorphicCase[num_cases];
      for (int i = 0; i < num_cases; i++) {
        polymorphic[i].function_index = other.function_index(i);
        polymorphic[i].absolute_call_frequency = other.call_count(i);
      }
      frequency_or_ool_ = reinterpret_cast<intptr_t>(polymorphic);
    } else {
      frequency_or_ool_ = other.frequency_or_ool_;
    }
    has_non_inlineable_targets_ = other.has_non_inlineable_targets_;
    is_megamorphic_ = other.is_megamorphic_;
    return *this;
  }
References v8::internal::wasm::CallSiteFeedback::PolymorphicCase::absolute_call_frequency, v8::internal::wasm::CallSiteFeedback::PolymorphicCase::function_index, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
polymorphic_storage()
const PolymorphicCase* v8::internal::wasm::CallSiteFeedback::polymorphic_storage () const [inline], [private]
Definition at line 583 of file wasm-module.h.
                                                     {
    DCHECK(is_polymorphic());
    return reinterpret_cast<PolymorphicCase*>(frequency_or_ool_);
  }
References v8::internal::DCHECK().
set_has_non_inlineable_targets()
void v8::internal::wasm::CallSiteFeedback::set_has_non_inlineable_targets (bool has_non_inlineable_targets) [inline]
Definition at line 573 of file wasm-module.h.
                                                                       {
    has_non_inlineable_targets_ = has_non_inlineable_targets;
  }
Member Data Documentation
frequency_or_ool_
intptr_t v8::internal::wasm::CallSiteFeedback::frequency_or_ool_ [private]
Definition at line 591 of file wasm-module.h.
has_non_inlineable_targets_
bool v8::internal::wasm::CallSiteFeedback::has_non_inlineable_targets_ = false [private]
Definition at line 589 of file wasm-module.h.
index_or_count_
int v8::internal::wasm::CallSiteFeedback::index_or_count_ [private]
Definition at line 588 of file wasm-module.h.
is_megamorphic_
bool v8::internal::wasm::CallSiteFeedback::is_megamorphic_ = false [private]
Definition at line 590 of file wasm-module.h.
Referenced by CreateMegamorphic().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-module.h