v8::internal::maglev::BuiltinStringFromCharCode Class Reference
#include <maglev-ir.h>
Public Member Functions
BuiltinStringFromCharCode (uint64_t bitfield)
Input & code_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kInt32}
Private Types
using Base = FixedInputValueNodeT< 1, BuiltinStringFromCharCode >
Additional Inherited Members
Detailed Description
Definition at line 7708 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::BuiltinStringFromCharCode::Base = FixedInputValueNodeT<1, BuiltinStringFromCharCode> [private]
Definition at line 7710 of file maglev-ir.h.
Constructor & Destructor Documentation
BuiltinStringFromCharCode()
v8::internal::maglev::BuiltinStringFromCharCode::BuiltinStringFromCharCode (uint64_t bitfield) [inline], [explicit]
Definition at line 7713 of file maglev-ir.h.
: Base(bitfield) {}
Member Function Documentation
code_input()
Input& v8::internal::maglev::BuiltinStringFromCharCode::code_input () [inline]
Definition at line 7720 of file maglev-ir.h.
{ return input(0); }
Referenced by GenerateCode(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and SetValueLocationConstraints().
GenerateCode()
void v8::internal::maglev::BuiltinStringFromCharCode::GenerateCode (MaglevAssembler * masm, const ProcessingState & state)
Definition at line 100 of file maglev-ir-arm.cc.
                                                                           {
  MaglevAssembler::TemporaryRegisterScope temps(masm);
  Register scratch = temps.Acquire();
  Register result_string = ToRegister(result());
  if (Int32Constant* constant = code_input().node()->TryCast<Int32Constant>()) {
    int32_t char_code = constant->value() & 0xFFFF;
    if (0 <= char_code && char_code < String::kMaxOneByteCharCode) {
      __ LoadSingleCharacterString(result_string, char_code);
    } else {
      DCHECK_NE(scratch, result_string);
      __ AllocateTwoByteString(register_snapshot(), result_string, 1);
      __ Move(scratch, char_code);
      __ strh(scratch, FieldMemOperand(result_string,
                                       OFFSET_OF_DATA_START(SeqTwoByteString)));
    }
  } else {
    __ StringFromCharCode(register_snapshot(), nullptr, result_string,
                          ToRegister(code_input()), scratch,
                          MaglevAssembler::CharCodeMaskMode::kMustApplyMask);
  }
}
References __, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Acquire(), code_input(), DCHECK_NE, v8::internal::FieldMemOperand(), v8::internal::String::kMaxOneByteCharCode, v8::internal::maglev::MaglevAssembler::kMustApplyMask, OFFSET_OF_DATA_START, v8::base::internal::result, and v8::internal::maglev::ToRegister().
MaxCallStackArgs()
int v8::internal::maglev::BuiltinStringFromCharCode::MaxCallStackArgs () const
Definition at line 88 of file maglev-ir-arm.cc.
                                                      {
  return AllocateDescriptor::GetStackParameterCount();
}
References v8::internal::StaticCallInterfaceDescriptor< AllocateDescriptor >::GetStackParameterCount().
PrintParams()
void v8::internal::maglev::BuiltinStringFromCharCode::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 7725 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::BuiltinStringFromCharCode::SetValueLocationConstraints ()
Definition at line 91 of file maglev-ir-arm.cc.
                                                            {
  if (code_input().node()->Is<Int32Constant>()) {
    UseAny(code_input());
  } else {
    UseAndClobberRegister(code_input());
  }
  set_temporaries_needed(1);
  DefineAsRegister(this);
}
References code_input(), v8::internal::maglev::DefineAsRegister(), v8::internal::maglev::UseAndClobberRegister(), and v8::internal::maglev::UseAny().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::BuiltinStringFromCharCode::kInputTypes {ValueRepresentation::kInt32} [static], [constexpr]
Definition at line 7718 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::BuiltinStringFromCharCode::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::CanAllocate() | OpProperties::DeferredCall()
Definition at line 7715 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/arm/maglev-ir-arm.cc
/mnt/V8SourceCode/src/maglev/arm64/maglev-ir-arm64.cc
/mnt/V8SourceCode/src/maglev/riscv/maglev-ir-riscv.cc
/mnt/V8SourceCode/src/maglev/s390/maglev-ir-s390.cc
/mnt/V8SourceCode/src/maglev/x64/maglev-ir-x64.cc