heap::base::ActiveSystemPages Class Reference
#include <active-system-pages.h>
Public Member Functions
V8_EXPORT_PRIVATE size_t Init (size_t header_size, size_t page_size_bits, size_t user_page_size)
V8_EXPORT_PRIVATE size_t Add (size_t start, size_t end, size_t page_size_bits)
V8_EXPORT_PRIVATE size_t Reduce (ActiveSystemPages updated_value)
V8_EXPORT_PRIVATE size_t Clear ()
V8_EXPORT_PRIVATE size_t Size (size_t page_size_bits) const
Static Public Attributes
static constexpr size_t kMaxPages = 64
Private Types
using bitset_t = std::bitset< kMaxPages >
Private Attributes
bitset_t value_
Detailed Description
Definition at line 17 of file active-system-pages.h.
Member Typedef Documentation
bitset_t
using heap::base::ActiveSystemPages::bitset_t = std::bitset<kMaxPages> [private]
Definition at line 43 of file active-system-pages.h.
Member Function Documentation
Add()
size_t heap::base::ActiveSystemPages::Add (size_t start, size_t end, size_t page_size_bits)
Definition at line 26 of file active-system-pages.cc.
                                                     {
  const size_t page_size = 1 << page_size_bits;
  DCHECK_LE(start, end);
  DCHECK_LE(end, kMaxPages * page_size);
  // Make sure we actually get the bitcount as argument.
  DCHECK_LT(page_size_bits, sizeof(uintptr_t) * CHAR_BIT);
  const uintptr_t start_page_bit =
      RoundDown(start, page_size) >> page_size_bits;
  const uintptr_t end_page_bit = RoundUp(end, page_size) >> page_size_bits;
  DCHECK_LE(start_page_bit, end_page_bit);
  const uintptr_t bits = end_page_bit - start_page_bit;
  DCHECK_LE(bits, kMaxPages);
  const bitset_t mask = bits == kMaxPages
                            ? int64_t{-1}
                            : ((uint64_t{1} << bits) - 1) << start_page_bit;
  const bitset_t added_pages = ~value_ & mask;
  value_ |= mask;
  return added_pages.count();
}
References DCHECK_LE, DCHECK_LT, v8::internal::compiler::end(), kMaxPages, RoundDown(), RoundUp(), and value_.
Referenced by v8::internal::SemiSpace::AddRangeToActiveSystemPages(), v8::internal::PagedSpaceBase::AddRangeToActiveSystemPages(), and Init().
Clear()
size_t heap::base::ActiveSystemPages::Clear ()
Definition at line 58 of file active-system-pages.cc.
                                {
  const size_t removed_pages = value_.count();
  value_ = 0;
  return removed_pages;
}
References value_.
Referenced by Init().
Init()
size_t heap::base::ActiveSystemPages::Init (size_t header_size, size_t page_size_bits, size_t user_page_size)
Definition at line 15 of file active-system-pages.cc.
                                                      {
#if DEBUG
  size_t page_size = 1 << page_size_bits;
  DCHECK_LE(RoundUp(user_page_size, page_size) >> page_size_bits,
            ActiveSystemPages::kMaxPages);
#endif // DEBUG
  Clear();
  return Add(0, header_size, page_size_bits);
}
References Add(), Clear(), DCHECK_LE, kMaxPages, and RoundUp().
Referenced by v8::internal::Sweeper::SweepEmptyNewSpacePage().
Reduce()
size_t heap::base::ActiveSystemPages::Reduce (ActiveSystemPages updated_value)
Definition at line 51 of file active-system-pages.cc.
                                                                {
  DCHECK_EQ(~value_ & updated_value.value_, 0);
  const bitset_t removed_pages(value_ & ~updated_value.value_);
  value_ = updated_value.value_;
  return removed_pages.count();
}
References DCHECK_EQ, and value_.
Referenced by v8::internal::PagedSpaceBase::ReduceActiveSystemPages().
Size()
size_t heap::base::ActiveSystemPages::Size (size_t page_size_bits) const
Definition at line 64 of file active-system-pages.cc.
                                                          {
  // Make sure we don't get the full page size as argument.
  DCHECK_LT(page_size_bits, sizeof(uintptr_t) * CHAR_BIT);
  return value_.count() * (size_t{1} << page_size_bits);
}
References DCHECK_LT, and value_.
Member Data Documentation
kMaxPages
constexpr size_t heap::base::ActiveSystemPages::kMaxPages = 64 [static], [constexpr]
Definition at line 21 of file active-system-pages.h.
Referenced by Add(), and Init().
value_
bitset_t heap::base::ActiveSystemPages::value_ [private]
Definition at line 45 of file active-system-pages.h.
Referenced by Add(), Clear(), Reduce(), and Size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/base/active-system-pages.h
/mnt/V8SourceCode/src/heap/base/active-system-pages.cc