v8::internal::ConstantPoolEntry Class Reference
#include <constant-pool.h>
Public Types
enum Type { INTPTR
, DOUBLE
, NUMBER_OF_TYPES
 }
enum Access { REGULAR
, OVERFLOWED
 }
Public Member Functions
ConstantPoolEntry ()=default
ConstantPoolEntry (int position, intptr_t value, bool sharing_ok, RelocInfo::Mode rmode=RelocInfo::NO_INFO)
ConstantPoolEntry (int position, base::Double value, RelocInfo::Mode rmode=RelocInfo::NO_INFO)
int position () const
bool sharing_ok () const
bool is_merged () const
int merged_index () const
void set_merged_index (int index)
int offset () const
void set_offset (int offset)
intptr_t value () const
uint64_t value64 () const
RelocInfo::Mode rmode () const
Static Public Member Functions
static int size (Type type)
Private Types
enum { SHARING_PROHIBITED = -2
, SHARING_ALLOWED = -1
 }
Private Attributes
int position_
int merged_index_
xx xx xx xx xx xx xx xx xx
union {
 intptr_t value_
 uint64_t value64_
};
RelocInfo::Mode rmode_
Detailed Description
Definition at line 23 of file constant-pool.h.
Member Enumeration Documentation
anonymous enum
anonymous enum [private]
Enumerator
SHARING_PROHIBITED
SHARING_ALLOWED
Definition at line 81 of file constant-pool.h.
{ SHARING_PROHIBITED = -2, SHARING_ALLOWED = -1 };
Access
enum v8::internal::ConstantPoolEntry::Access
Enumerator
REGULAR
OVERFLOWED
Definition at line 69 of file constant-pool.h.
{ REGULAR, OVERFLOWED };
Type
enum v8::internal::ConstantPoolEntry::Type
Enumerator
INTPTR
DOUBLE
NUMBER_OF_TYPES
Definition at line 63 of file constant-pool.h.
{ INTPTR, DOUBLE, NUMBER_OF_TYPES };
Constructor & Destructor Documentation
ConstantPoolEntry() [1/3]
v8::internal::ConstantPoolEntry::ConstantPoolEntry () [default]
ConstantPoolEntry() [2/3]
v8::internal::ConstantPoolEntry::ConstantPoolEntry (int position, intptr_t value, bool sharing_ok, RelocInfo::Mode rmode = RelocInfo::NO_INFO) [inline]
Definition at line 26 of file constant-pool.h.
      : position_(position),
        merged_index_(sharing_ok ? SHARING_ALLOWED : SHARING_PROHIBITED),
        value_(value),
        rmode_(rmode) {}
ConstantPoolEntry() [3/3]
v8::internal::ConstantPoolEntry::ConstantPoolEntry (int position, base::Double value, RelocInfo::Mode rmode = RelocInfo::NO_INFO) [inline]
Definition at line 32 of file constant-pool.h.
      : position_(position),
        merged_index_(SHARING_ALLOWED),
        value64_(value.AsUint64()),
        rmode_(rmode) {}
Member Function Documentation
is_merged()
bool v8::internal::ConstantPoolEntry::is_merged () const [inline]
Definition at line 41 of file constant-pool.h.
{ return merged_index_ >= 0; }
References merged_index_.
Referenced by merged_index(), and set_merged_index().
merged_index()
int v8::internal::ConstantPoolEntry::merged_index () const [inline]
Definition at line 42 of file constant-pool.h.
                           {
    DCHECK(is_merged());
    return merged_index_;
  }
References v8::internal::DCHECK(), is_merged(), and merged_index_.
offset()
int v8::internal::ConstantPoolEntry::offset () const [inline]
Definition at line 51 of file constant-pool.h.
                     {
    DCHECK_GE(merged_index_, 0);
    return merged_index_;
  }
References DCHECK_GE, and merged_index_.
Referenced by set_offset().
position()
int v8::internal::ConstantPoolEntry::position () const [inline]
Definition at line 39 of file constant-pool.h.
{ return position_; }
References position_.
rmode()
RelocInfo::Mode v8::internal::ConstantPoolEntry::rmode () const [inline]
Definition at line 61 of file constant-pool.h.
{ return rmode_; }
References rmode_.
set_merged_index()
void v8::internal::ConstantPoolEntry::set_merged_index (int index) [inline]
Definition at line 46 of file constant-pool.h.
                                   {
    DCHECK(sharing_ok());
    merged_index_ = index;
    DCHECK(is_merged());
  }
References v8::internal::DCHECK(), v8::internal::index, is_merged(), merged_index_, and sharing_ok().
set_offset()
void v8::internal::ConstantPoolEntry::set_offset (int offset) [inline]
Definition at line 55 of file constant-pool.h.
                              {
    DCHECK_GE(offset, 0);
    merged_index_ = offset;
  }
References DCHECK_GE, merged_index_, and offset().
sharing_ok()
bool v8::internal::ConstantPoolEntry::sharing_ok () const [inline]
Definition at line 40 of file constant-pool.h.
{ return merged_index_ != SHARING_PROHIBITED; }
References merged_index_, and SHARING_PROHIBITED.
Referenced by set_merged_index().
size()
static int v8::internal::ConstantPoolEntry::size (Type type) [inline], [static]
Definition at line 65 of file constant-pool.h.
                             {
    return (type == INTPTR) ? kSystemPointerSize : kDoubleSize;
  }
References INTPTR, v8::internal::kDoubleSize, v8::internal::kSystemPointerSize, and v8::internal::tracing::type.
value()
intptr_t v8::internal::ConstantPoolEntry::value () const [inline]
Definition at line 59 of file constant-pool.h.
{ return value_; }
References value_.
value64()
uint64_t v8::internal::ConstantPoolEntry::value64 () const [inline]
Definition at line 60 of file constant-pool.h.
{ return value64_; }
References value64_.
Member Data Documentation
union { ... } [private]
merged_index_
int v8::internal::ConstantPoolEntry::merged_index_ [private]
Definition at line 73 of file constant-pool.h.
Referenced by is_merged(), merged_index(), offset(), set_merged_index(), set_offset(), and sharing_ok().
position_
int v8::internal::ConstantPoolEntry::position_ [private]
Definition at line 72 of file constant-pool.h.
Referenced by position().
rmode_
RelocInfo::Mode v8::internal::ConstantPoolEntry::rmode_ [private]
Definition at line 80 of file constant-pool.h.
Referenced by rmode().
value64_
uint64_t v8::internal::ConstantPoolEntry::value64_
Definition at line 76 of file constant-pool.h.
Referenced by value64().
value_
intptr_t v8::internal::ConstantPoolEntry::value_
Definition at line 75 of file constant-pool.h.
Referenced by value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/constant-pool.h