v8::internal::anonymous_namespace{allocation.cc}::PageAllocatorInitializer Class Reference
Public Member Functions
PageAllocatorInitializer ()
PageAllocator * page_allocator () const
void SetPageAllocatorForTesting (PageAllocator *allocator)
Private Attributes
PageAllocator * page_allocator_
Detailed Description
Definition at line 33 of file allocation.cc.
Constructor & Destructor Documentation
PageAllocatorInitializer()
v8::internal::anonymous_namespace{allocation.cc}::PageAllocatorInitializer::PageAllocatorInitializer () [inline]
Definition at line 35 of file allocation.cc.
                             {
    page_allocator_ = V8::GetCurrentPlatform()->GetPageAllocator();
    if (page_allocator_ == nullptr) {
      static base::LeakyObject<base::PageAllocator> default_page_allocator;
      page_allocator_ = default_page_allocator.get();
    }
#if defined(LEAK_SANITIZER)
    static base::LeakyObject<base::LsanPageAllocator> lsan_allocator(
        page_allocator_);
    page_allocator_ = lsan_allocator.get();
#endif
  }
References v8::base::LeakyObject< T >::get(), v8::internal::V8::GetCurrentPlatform(), and v8::Platform::GetPageAllocator().
Member Function Documentation
page_allocator()
PageAllocator* v8::internal::anonymous_namespace{allocation.cc}::PageAllocatorInitializer::page_allocator () const [inline]
Definition at line 48 of file allocation.cc.
{ return page_allocator_; }
SetPageAllocatorForTesting()
void v8::internal::anonymous_namespace{allocation.cc}::PageAllocatorInitializer::SetPageAllocatorForTesting (PageAllocator * allocator) [inline]
Definition at line 50 of file allocation.cc.
                                                            {
    page_allocator_ = allocator;
  }
Member Data Documentation
page_allocator_
PageAllocator* v8::internal::anonymous_namespace{allocation.cc}::PageAllocatorInitializer::page_allocator_ [private]
Definition at line 55 of file allocation.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/utils/allocation.cc