v8::internal::maglev::ConstantGapMove Class Reference
#include <maglev-ir.h>
Public Member Functions
ConstantGapMove (uint64_t bitfield, ValueNode *node, compiler::AllocatedOperand target)
compiler::AllocatedOperand target () const
ValueNode * node () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Private Types
using Base = FixedInputNodeT< 0, ConstantGapMove >
Private Attributes
ValueNode * node_
compiler::InstructionOperand source_
compiler::AllocatedOperand target_
Additional Inherited Members
Detailed Description
Definition at line 9778 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::ConstantGapMove::Base = FixedInputNodeT<0, ConstantGapMove> [private]
Definition at line 9779 of file maglev-ir.h.
Constructor & Destructor Documentation
ConstantGapMove()
v8::internal::maglev::ConstantGapMove::ConstantGapMove (uint64_t bitfield, ValueNode * node, compiler::AllocatedOperand target) [inline]
Definition at line 9782 of file maglev-ir.h.
      : Base(bitfield), node_(node), target_(target) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::ConstantGapMove::GenerateCode (MaglevAssembler * , const ProcessingState &)
node()
ValueNode* v8::internal::maglev::ConstantGapMove::node () const [inline]
Definition at line 9787 of file maglev-ir.h.
{ return node_; }
PrintParams()
void v8::internal::maglev::ConstantGapMove::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8299 of file maglev-ir.cc.
                                                                             {
  os << "(";
  graph_labeller->PrintNodeLabel(os, node_);
  os << " → " << target() << ")";
}
References node_, v8::internal::maglev::MaglevGraphLabeller::PrintNodeLabel(), and target().
SetValueLocationConstraints()
void v8::internal::maglev::ConstantGapMove::SetValueLocationConstraints ()
target()
compiler::AllocatedOperand v8::internal::maglev::ConstantGapMove::target () const [inline]
Definition at line 9786 of file maglev-ir.h.
{ return target_; }
Referenced by PrintParams().
Member Data Documentation
node_
ValueNode* v8::internal::maglev::ConstantGapMove::node_ [private]
Definition at line 9794 of file maglev-ir.h.
Referenced by PrintParams().
source_
compiler::InstructionOperand v8::internal::maglev::ConstantGapMove::source_ [private]
Definition at line 9795 of file maglev-ir.h.
target_
compiler::AllocatedOperand v8::internal::maglev::ConstantGapMove::target_ [private]
Definition at line 9796 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc