v8::internal::MapWord Class Reference
#include <objects.h>
Public Member Functions
Tagged< Map > ToMap () const
bool IsForwardingAddress () const
Tagged< HeapObject > ToForwardingAddress (Tagged< HeapObject > map_word_host)
constexpr Address ptr () const
constexpr bool operator== (MapWord other) const
constexpr bool operator!= (MapWord other) const
Static Public Member Functions
static MapWord FromMap (const Tagged< Map > map)
static V8_EXPORT_PRIVATE bool IsMapOrForwarded (Tagged< Map > map)
static MapWord FromForwardingAddress (Tagged< HeapObject > map_word_host, Tagged< HeapObject > object)
static constexpr bool IsPacked (Address)
Private Member Functions
constexpr MapWord (Address value)
Private Attributes
Address value_
Friends
class HeapObject
template<typename TFieldType , int kFieldOffset, typename CompressionScheme >
class TaggedField
Detailed Description
Definition at line 790 of file objects.h.
Constructor & Destructor Documentation
MapWord()
constexpr v8::internal::MapWord::MapWord (Address value) [inline], [explicit], [constexpr], [private]
Definition at line 853 of file objects.h.
: value_(value) {}
Referenced by FromForwardingAddress(), and FromMap().
Member Function Documentation
FromForwardingAddress()
MapWord v8::internal::MapWord::FromForwardingAddress (Tagged< HeapObject > map_word_host, Tagged< HeapObject > object) [inline], [static]
Definition at line 1281 of file objects-inl.h.
                                                                  {
#ifdef V8_EXTERNAL_CODE_SPACE
  // When external code space is enabled forwarding pointers are encoded as
  // Smi representing a diff from the source object address in kObjectAlignment
  // chunks.
  intptr_t diff = static_cast<intptr_t>(object.ptr() - map_word_host.ptr());
  DCHECK(IsAligned(diff, kObjectAlignment));
  MapWord map_word(Smi::FromIntptr(diff / kObjectAlignment).ptr());
  DCHECK(map_word.IsForwardingAddress());
  return map_word;
#else
  return MapWord(object.ptr() - kHeapObjectTag);
#endif // V8_EXTERNAL_CODE_SPACE
}
References v8::internal::DCHECK(), v8::internal::Smi::FromIntptr(), IsAligned(), IsForwardingAddress(), v8::internal::kHeapObjectTag, v8::internal::kObjectAlignment, MapWord(), ptr(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by v8::internal::HeapLayout::IsSelfForwarded(), v8::internal::EvacuateVisitorBase::RawMigrateObject(), v8::internal::HeapObject::relaxed_compare_and_swap_map_word_forwarded(), v8::internal::HeapObject::release_compare_and_swap_map_word_forwarded(), and v8::internal::HeapObject::set_map_word_forwarded().
FromMap()
MapWord v8::internal::MapWord::FromMap (const Tagged< Map > map) [inline], [static]
Definition at line 1253 of file objects-inl.h.
                                              {
  DCHECK(map.is_null() || !MapWord::IsPacked(map.ptr()));
#ifdef V8_MAP_PACKING
  return MapWord(Pack(map.ptr()));
#else
  return MapWord(map.ptr());
#endif
}
References v8::internal::DCHECK(), v8::internal::Tagged< HeapObject >::is_null(), IsPacked(), MapWord(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by v8::internal::Scavenger::EvacuateObject(), v8::internal::Scavenger::HandleLargeObject(), v8::internal::Heap::LeftTrimFixedArray(), v8::internal::Scavenger::MigrateObject(), v8::internal::ReadOnlyRoots::one_pointer_filler_map_word(), and v8::internal::HeapObject::set_map_word().
IsForwardingAddress()
bool v8::internal::MapWord::IsForwardingAddress () const [inline]
Definition at line 1270 of file objects-inl.h.
                                        {
#ifdef V8_EXTERNAL_CODE_SPACE
  // When external code space is enabled forwarding pointers are encoded as
  // Smi representing a diff from the source object address in kObjectAlignment
  // chunks.
  return HAS_SMI_TAG(value_);
#else
  return (value_ & kForwardingTagMask) == kForwardingTag;
#endif // V8_EXTERNAL_CODE_SPACE
}
References HAS_SMI_TAG, v8::internal::kForwardingTag, v8::internal::kForwardingTagMask, and value_.
Referenced by v8::internal::Scavenger::EvacuateShortcutCandidate(), v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::FilterNormalObject(), v8::internal::ForwardingAddress(), FromForwardingAddress(), v8::internal::Heap::GcSafeMapOfHeapObject(), v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::HandleHeapObject(), IsMapOrForwarded(), v8::internal::PretenuringHandler::MergeAllocationSitePretenuringFeedback(), v8::internal::EphemeronTableUpdatingItem::Process(), v8::internal::EvacuationWeakObjectRetainer::RetainAs(), v8::internal::Scavenger::ScavengeObject(), ToForwardingAddress(), v8::internal::anonymous_namespace{string-forwarding-table.cc}::UpdateForwardedSlot(), v8::internal::anonymous_namespace{scavenger.cc}::GlobalHandlesWeakRootsUpdatingVisitor::UpdatePointer(), v8::internal::MarkCompactCollector::UpdatePointersInPointerTables(), v8::internal::UpdateReferenceInExternalStringTableEntry(), v8::internal::anonymous_namespace{mark-compact.cc}::UpdateSlot(), v8::internal::Heap::UpdateYoungReferenceInExternalStringTableEntry(), and v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlot().
IsMapOrForwarded()
bool v8::internal::MapWord::IsMapOrForwarded (Tagged< Map > map) [static]
Definition at line 6736 of file objects.cc.
                                              {
  MapWord map_word = map->map_word(kRelaxedLoad);
  if (map_word.IsForwardingAddress()) {
    // During GC we can't access forwarded maps without synchronization.
    return true;
  }
  // The meta map might be moved away by GC too but we can read instance
  // type from both old and new location as it can't change.
  return InstanceTypeChecker::IsMap(map_word.ToMap()->instance_type());
}
References IsForwardingAddress(), v8::kRelaxedLoad, and ToMap().
Referenced by v8::internal::LiveObjectRange::iterator::AdvanceToNextMarkedObject().
IsPacked()
static constexpr bool v8::internal::MapWord::IsPacked (Address) [inline], [static], [constexpr]
Definition at line 844 of file objects.h.
{ return false; }
Referenced by FromMap(), v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::HandleHeapObject(), v8::internal::V8HeapExplorer::SetHiddenReference(), v8::internal::RecordMigratedSlotVisitor::VisitPointer(), v8::internal::RecordMigratedSlotVisitor::VisitProtectedPointer(), v8::internal::RootMarkingVisitor::VisitRootPointer(), v8::internal::RootsReferencesExtractor::VisitRootPointers(), and v8::internal::GlobalObjectsEnumerator::VisitRootPointersImpl().
operator!=()
constexpr bool v8::internal::MapWord::operator!= (MapWord other) const [inline], [constexpr]
Definition at line 826 of file objects.h.
                                                 {
    return static_cast<Tagged_t>(ptr()) != static_cast<Tagged_t>(other.ptr());
  }
References ptr().
operator==()
constexpr bool v8::internal::MapWord::operator== (MapWord other) const [inline], [constexpr]
Definition at line 823 of file objects.h.
                                                 {
    return static_cast<Tagged_t>(ptr()) == static_cast<Tagged_t>(other.ptr());
  }
References ptr().
ptr()
constexpr Address v8::internal::MapWord::ptr () const [inline], [constexpr]
Definition at line 818 of file objects.h.
{ return value_; }
Referenced by FromForwardingAddress(), v8::internal::JSObject::InitializeBody(), operator!=(), operator==(), v8::internal::HeapObject::relaxed_compare_and_swap_map_word_forwarded(), and v8::internal::HeapObject::release_compare_and_swap_map_word_forwarded().
ToForwardingAddress()
Tagged< HeapObject > v8::internal::MapWord::ToForwardingAddress (Tagged< HeapObject > map_word_host) [inline]
Definition at line 1297 of file objects-inl.h.
                                      {
  DCHECK(IsForwardingAddress());
#ifdef V8_EXTERNAL_CODE_SPACE
  // When the sandbox or the external code space is enabled, forwarding
  // pointers are encoded as Smi representing a diff from the source object
  // address in kObjectAlignment chunks. This is required as we are using
  // multiple pointer compression cages in these scenarios.
  intptr_t diff =
      static_cast<intptr_t>(Tagged<Smi>(value_).value()) * kObjectAlignment;
  Address address = map_word_host.address() + diff;
  return HeapObject::FromAddress(address);
#else
  // The sandbox requires the external code space.
  DCHECK(!V8_ENABLE_SANDBOX_BOOL);
  return HeapObject::FromAddress(value_);
#endif // V8_EXTERNAL_CODE_SPACE
}
References v8::internal::Tagged< HeapObject >::address(), v8::internal::DCHECK(), v8::internal::HeapObject::FromAddress(), IsForwardingAddress(), v8::internal::kObjectAlignment, v8::internal::Tagged< Smi >, V8_ENABLE_SANDBOX_BOOL, and value_.
Referenced by v8::internal::Scavenger::EvacuateShortcutCandidate(), v8::internal::ForwardingAddress(), v8::internal::Heap::GcSafeMapOfHeapObject(), v8::internal::PretenuringHandler::MergeAllocationSitePretenuringFeedback(), v8::internal::EphemeronTableUpdatingItem::Process(), v8::internal::Scavenger::PromoteObject(), v8::internal::EvacuationWeakObjectRetainer::RetainAs(), v8::internal::Scavenger::ScavengeObject(), v8::internal::Scavenger::SemiSpaceCopyObject(), v8::internal::anonymous_namespace{string-forwarding-table.cc}::UpdateForwardedSlot(), v8::internal::anonymous_namespace{scavenger.cc}::GlobalHandlesWeakRootsUpdatingVisitor::UpdatePointer(), v8::internal::MarkCompactCollector::UpdatePointersInPointerTables(), v8::internal::UpdateReferenceInExternalStringTableEntry(), v8::internal::anonymous_namespace{mark-compact.cc}::UpdateSlot(), v8::internal::Heap::UpdateYoungReferenceInExternalStringTableEntry(), and v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlot().
ToMap()
Tagged< Map > v8::internal::MapWord::ToMap () const [inline]
Definition at line 1262 of file objects-inl.h.
                                 {
#ifdef V8_MAP_PACKING
  return UncheckedCast<Map>(Tagged<Object>(Unpack(value_)));
#else
  return UncheckedCast<Map>(Tagged<Object>(value_));
#endif
}
References value_.
Referenced by v8::internal::Scavenger::EvacuateShortcutCandidate(), v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::FindBasePtr(), v8::internal::Heap::GcSafeMapOfHeapObject(), v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::HandleHeapObject(), IsMapOrForwarded(), v8::internal::Scavenger::PinAndPushObject(), and v8::internal::Scavenger::ScavengeObject().
Friends And Related Function Documentation
HeapObject
friend class HeapObject [friend]
Definition at line 849 of file objects.h.
TaggedField
template<typename TFieldType , int kFieldOffset, typename CompressionScheme >
friend class TaggedField [friend]
Definition at line 851 of file objects.h.
Member Data Documentation
value_
Address v8::internal::MapWord::value_ [private]
Definition at line 855 of file objects.h.
Referenced by IsForwardingAddress(), ToForwardingAddress(), and ToMap().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/objects.h
/mnt/V8SourceCode/src/objects/objects-inl.h
/mnt/V8SourceCode/src/objects/objects.cc