v8::internal::AllocationSiteUsageContext Class Reference
#include <allocation-site-scopes.h>
Public Member Functions
AllocationSiteUsageContext (Isolate *isolate, Handle< AllocationSite > site, bool activated)
Handle< AllocationSite > EnterNewScope ()
void ExitScope (DirectHandle< AllocationSite > scope_site, DirectHandle< JSObject > object)
bool ShouldCreateMemento (DirectHandle< JSObject > object)
Static Public Attributes
static const bool kCopying = true
Private Attributes
Handle< AllocationSite > top_site_
bool activated_
Additional Inherited Members
Detailed Description
Definition at line 44 of file allocation-site-scopes.h.
Constructor & Destructor Documentation
AllocationSiteUsageContext()
v8::internal::AllocationSiteUsageContext::AllocationSiteUsageContext (Isolate * isolate, Handle< AllocationSite > site, bool activated) [inline]
Definition at line 46 of file allocation-site-scopes.h.
      : AllocationSiteContext(isolate),
        top_site_(site),
        activated_(activated) {}
Member Function Documentation
EnterNewScope()
Handle< AllocationSite > v8::internal::AllocationSiteUsageContext::EnterNewScope () [inline]
Definition at line 23 of file allocation-site-scopes-inl.h.
                                                                 {
  if (top().is_null()) {
    InitializeTraversal(top_site_);
  } else {
    // Advance current site
    Tagged<Object> nested_site = current()->nested_site();
    // Something is wrong if we advance to the end of the list here.
    update_current_site(Cast<AllocationSite>(nested_site));
  }
  return Handle<AllocationSite>(*current(), isolate());
}
References v8::internal::AllocationSiteContext::current(), v8::internal::AllocationSiteContext::InitializeTraversal(), v8::internal::AllocationSiteContext::isolate(), v8::internal::AllocationSiteContext::top(), top_site_, and v8::internal::AllocationSiteContext::update_current_site().
Referenced by v8::internal::anonymous_namespace{runtime-literals.cc}::CreateLiteral().
ExitScope()
void v8::internal::AllocationSiteUsageContext::ExitScope (DirectHandle< AllocationSite > scope_site, DirectHandle< JSObject > object) [inline]
Definition at line 35 of file allocation-site-scopes-inl.h.
                                                                            {
  // This assert ensures that we are pointing at the right sub-object in a
  // recursive walk of a nested literal.
  DCHECK(object.is_null() || *object == scope_site->boilerplate());
}
References v8::internal::DCHECK().
Referenced by v8::internal::anonymous_namespace{runtime-literals.cc}::CreateLiteral().
ShouldCreateMemento()
bool v8::internal::AllocationSiteUsageContext::ShouldCreateMemento (DirectHandle< JSObject > object) [inline]
Definition at line 42 of file allocation-site-scopes-inl.h.
                                   {
  if (activated_ && AllocationSite::CanTrack(object->map()->instance_type())) {
    if (v8_flags.allocation_site_pretenuring ||
        AllocationSite::ShouldTrack(object->GetElementsKind())) {
      if (v8_flags.trace_creation_allocation_sites) {
        PrintF("*** Creating Memento for %s %p\n",
               IsJSArray(*object) ? "JSArray" : "JSObject",
               reinterpret_cast<void*>(object->ptr()));
      }
      return true;
    }
  }
  return false;
}
References activated_, v8::internal::AllocationSite::CanTrack(), v8::internal::PrintF(), v8::internal::AllocationSite::ShouldTrack(), and v8::internal::v8_flags.
Member Data Documentation
activated_
bool v8::internal::AllocationSiteUsageContext::activated_ [private]
Definition at line 63 of file allocation-site-scopes.h.
Referenced by ShouldCreateMemento().
kCopying
const bool v8::internal::AllocationSiteUsageContext::kCopying = true [static]
Definition at line 59 of file allocation-site-scopes.h.
top_site_
Handle<AllocationSite> v8::internal::AllocationSiteUsageContext::top_site_ [private]
Definition at line 62 of file allocation-site-scopes.h.
Referenced by EnterNewScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/allocation-site-scopes.h
/mnt/V8SourceCode/src/objects/allocation-site-scopes-inl.h