v8::internal::compiler::turboshaft::MemoryContentTable Class Reference
#include <late-load-elimination-reducer.h>
Public Types
using Replacement = LoadEliminationReplacement
Public Member Functions
MemoryContentTable (Zone *zone, SparseOpIndexSnapshotTable< bool > &non_aliasing_objects, SparseOpIndexSnapshotTable< MapMaskAndOr > &object_maps, FixedOpIndexSidetable< Replacement > &replacements)
void OnNewKey (Key key, OpIndex value)
void OnValueChange (Key key, OpIndex old_value, OpIndex new_value)
void Invalidate (const StoreOp &store)
void Invalidate (OpIndex base, OptionalOpIndex index, int32_t offset)
void InvalidateMaybeAliasing ()
OpIndex Find (const LoadOp &load)
void Insert (const StoreOp &store)
void Insert (const LoadOp &load, OpIndex load_idx)
Private Member Functions
void Insert (OpIndex base, OptionalOpIndex index, int32_t offset, uint8_t element_size_log2, uint8_t size, OpIndex value)
void InsertImmutable (OpIndex base, OptionalOpIndex index, int32_t offset, uint8_t element_size_log2, uint8_t size, OpIndex value)
void InvalidateAtOffset (int32_t offset, OpIndex base)
OpIndex ResolveBase (OpIndex base)
void AddKeyInBaseOffsetMaps (Key key)
void RemoveKeyFromBaseOffsetMaps (Key key)
Private Attributes
SparseOpIndexSnapshotTable< bool > & non_aliasing_objects_
SparseOpIndexSnapshotTable< MapMaskAndOr > & object_maps_
FixedOpIndexSidetable< Replacement > & replacements_
ZoneAbslFlatHashMap< MemoryAddress, Key > all_keys_
ZoneAbslFlatHashMap< OpIndex, BaseData > base_keys_
ZoneAbslFlatHashMap< int, v8::base::DoublyThreadedList< Key, OffsetListTraits > > offset_keys_
v8::base::DoublyThreadedList< Key, OffsetListTraits > index_keys_
Static Private Attributes
static constexpr size_t kMaxKeys = 10000
Detailed Description
Definition at line 310 of file late-load-elimination-reducer.h.
Member Typedef Documentation
Replacement
using v8::internal::compiler::turboshaft::MemoryContentTable::Replacement = LoadEliminationReplacement
Definition at line 313 of file late-load-elimination-reducer.h.
Constructor & Destructor Documentation
MemoryContentTable()
v8::internal::compiler::turboshaft::MemoryContentTable::MemoryContentTable (Zone * zone, SparseOpIndexSnapshotTable< bool > & non_aliasing_objects, SparseOpIndexSnapshotTable< MapMaskAndOr > & object_maps, FixedOpIndexSidetable< Replacement > & replacements) [inline], [explicit]
Definition at line 314 of file late-load-elimination-reducer.h.
      : ChangeTrackingSnapshotTable(zone),
        non_aliasing_objects_(non_aliasing_objects),
        object_maps_(object_maps),
        replacements_(replacements),
        all_keys_(zone),
        base_keys_(zone),
        offset_keys_(zone) {}
Member Function Documentation
AddKeyInBaseOffsetMaps()
void v8::internal::compiler::turboshaft::MemoryContentTable::AddKeyInBaseOffsetMaps (Key key) [inline], [private]
Definition at line 609 of file late-load-elimination-reducer.h.
                                       {
    // Inserting in {base_keys_}.
    OpIndex base = key.data().mem.base;
    auto base_keys = base_keys_.find(base);
    if (base_keys != base_keys_.end()) {
      if (key.data().mem.index.valid()) {
        base_keys->second.with_indices.PushFront(key);
      } else {
        base_keys->second.with_offsets.PushFront(key);
      }
    } else {
      BaseData data;
      if (key.data().mem.index.valid()) {
        data.with_indices.PushFront(key);
      } else {
        data.with_offsets.PushFront(key);
      }
      base_keys_.insert({base, std::move(data)});
    }
    if (key.data().mem.index.valid()) {
      // Inserting in {index_keys_}.
      index_keys_.PushFront(key);
    } else {
      // Inserting in {offset_keys_}.
      int offset = key.data().mem.offset;
      auto offset_keys = offset_keys_.find(offset);
      if (offset_keys != offset_keys_.end()) {
        offset_keys->second.PushFront(key);
      } else {
        v8::base::DoublyThreadedList<Key, OffsetListTraits> list;
        list.PushFront(key);
        offset_keys_.insert({offset, std::move(list)});
      }
    }
  }
References base_keys_, index_keys_, v8::internal::key, offset_keys_, v8::base::DoublyThreadedList< T, DTLTraits >::PushFront(), v8::internal::compiler::turboshaft::BaseData::with_indices, and v8::internal::compiler::turboshaft::BaseData::with_offsets.
Referenced by OnNewKey(), and OnValueChange().
Find()
OpIndex v8::internal::compiler::turboshaft::MemoryContentTable::Find (const LoadOp & load) [inline]
Definition at line 442 of file late-load-elimination-reducer.h.
                                   {
    OpIndex base = ResolveBase(load.base());
    OptionalOpIndex index = load.index();
    int32_t offset = load.offset;
    uint8_t element_size_log2 = index.valid() ? load.element_size_log2 : 0;
    uint8_t size = load.loaded_rep.SizeInBytes();
    MemoryAddress mem{base, index, offset, element_size_log2, size};
    auto key = all_keys_.find(mem);
    if (key == all_keys_.end()) return OpIndex::Invalid();
    return Get(key->second);
  }
References all_keys_, v8::internal::compiler::turboshaft::LoadOp::base(), v8::internal::compiler::turboshaft::LoadOp::element_size_log2, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Get(), v8::internal::compiler::turboshaft::LoadOp::index(), v8::internal::index, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::key, v8::internal::compiler::turboshaft::LoadOp::loaded_rep, v8::internal::compiler::turboshaft::LoadOp::offset, ResolveBase(), size(), and v8::internal::compiler::turboshaft::MemoryRepresentation::SizeInBytes().
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad().
Insert() [1/3]
void v8::internal::compiler::turboshaft::MemoryContentTable::Insert (const LoadOp & load, OpIndex load_idx) [inline]
Definition at line 470 of file late-load-elimination-reducer.h.
                                                    {
    OpIndex base = ResolveBase(load.base());
    OptionalOpIndex index = load.index();
    int32_t offset = load.offset;
    uint8_t element_size_log2 = index.valid() ? load.element_size_log2 : 0;
    uint8_t size = load.loaded_rep.SizeInBytes();
    if (load.kind.is_immutable) {
      InsertImmutable(base, index, offset, element_size_log2, size, load_idx);
    } else {
      Insert(base, index, offset, element_size_log2, size, load_idx);
    }
  }
References v8::internal::compiler::turboshaft::LoadOp::base(), v8::internal::compiler::turboshaft::LoadOp::element_size_log2, v8::internal::compiler::turboshaft::LoadOp::index(), v8::internal::index, Insert(), InsertImmutable(), v8::internal::compiler::turboshaft::LoadOp::Kind::is_immutable, v8::internal::compiler::turboshaft::LoadOp::kind, v8::internal::compiler::turboshaft::LoadOp::loaded_rep, v8::internal::compiler::turboshaft::LoadOp::offset, ResolveBase(), size(), and v8::internal::compiler::turboshaft::MemoryRepresentation::SizeInBytes().
Insert() [2/3]
void v8::internal::compiler::turboshaft::MemoryContentTable::Insert (const StoreOp & store) [inline]
Definition at line 455 of file late-load-elimination-reducer.h.
                                    {
    OpIndex base = ResolveBase(store.base());
    OptionalOpIndex index = store.index();
    int32_t offset = store.offset;
    uint8_t element_size_log2 = index.valid() ? store.element_size_log2 : 0;
    OpIndex value = store.value();
    uint8_t size = store.stored_rep.SizeInBytes();
    if (store.kind.is_immutable) {
      InsertImmutable(base, index, offset, element_size_log2, size, value);
    } else {
      Insert(base, index, offset, element_size_log2, size, value);
    }
  }
References v8::internal::index, InsertImmutable(), ResolveBase(), size(), store(), and v8::internal::value.
Referenced by Insert(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad(), and v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessStore().
Insert() [3/3]
void v8::internal::compiler::turboshaft::MemoryContentTable::Insert (OpIndex base, OptionalOpIndex index, int32_t offset, uint8_t element_size_log2, uint8_t size, OpIndex value) [inline], [private]
Definition at line 513 of file late-load-elimination-reducer.h.
                                                                      {
    DCHECK_EQ(base, ResolveBase(base));
    MemoryAddress mem{base, index, offset, element_size_log2, size};
    TRACE("> MemoryContentTable: will insert " << mem
                                               << " with value=" << value);
    auto existing_key = all_keys_.find(mem);
    if (existing_key != all_keys_.end()) {
      TRACE(">> Reusing existing key");
      Set(existing_key->second, value);
      return;
    }
    if (all_keys_.size() > kMaxKeys) {
      TRACE(">> Bailing out because too many keys");
      if (V8_UNLIKELY(v8_flags.trace_turbo_bailouts)) {
        std::cout
            << "Bailing out in Late Load Elimination because of kMaxKeys [1]\n";
      }
      return;
    }
    // Creating a new key.
    Key key = NewKey({mem});
    all_keys_.insert({mem, key});
    Set(key, value);
  }
References all_keys_, DCHECK_EQ, v8::internal::index, v8::internal::key, kMaxKeys, v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< MemoryContentTable, OpIndex, KeyData >::NewKey(), ResolveBase(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< MemoryContentTable, OpIndex, KeyData >::Set(), size(), v8::internal::TRACE(), v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::value.
InsertImmutable()
void v8::internal::compiler::turboshaft::MemoryContentTable::InsertImmutable (OpIndex base, OptionalOpIndex index, int32_t offset, uint8_t element_size_log2, uint8_t size, OpIndex value) [inline], [private]
Definition at line 542 of file late-load-elimination-reducer.h.
                                                                               {
    DCHECK_EQ(base, ResolveBase(base));
    MemoryAddress mem{base, index, offset, element_size_log2, size};
    TRACE("> MemoryContentTable: will insert immutable "
          << mem << " with value=" << value);
    auto existing_key = all_keys_.find(mem);
    if (existing_key != all_keys_.end()) {
      TRACE(">> Reusing existing key");
      SetNoNotify(existing_key->second, value);
      return;
    }
    if (all_keys_.size() > kMaxKeys) {
      TRACE(">> Bailing out because too many keys");
      if (V8_UNLIKELY(v8_flags.trace_turbo_bailouts)) {
        std::cout
            << "Bailing out in Late Load Elimination because of kMaxKeys [2]\n";
      }
      return;
    }
    // Creating a new key.
    Key key = NewKey({mem});
    all_keys_.insert({mem, key});
    // Call `SetNoNotify` to avoid calls to `OnNewKey` and `OnValueChanged`.
    SetNoNotify(key, value);
  }
References all_keys_, DCHECK_EQ, v8::internal::index, v8::internal::key, kMaxKeys, v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< MemoryContentTable, OpIndex, KeyData >::NewKey(), ResolveBase(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< MemoryContentTable, OpIndex, KeyData >::SetNoNotify(), size(), v8::internal::TRACE(), v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::value.
Referenced by Insert().
Invalidate() [1/2]
void v8::internal::compiler::turboshaft::MemoryContentTable::Invalidate (const StoreOp & store) [inline]
Definition at line 344 of file late-load-elimination-reducer.h.
                                        {
    Invalidate(store.base(), store.index(), store.offset);
  }
References store().
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessCall(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad(), and v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessStore().
Invalidate() [2/2]
void v8::internal::compiler::turboshaft::MemoryContentTable::Invalidate (OpIndex base, OptionalOpIndex index, int32_t offset) [inline]
Definition at line 348 of file late-load-elimination-reducer.h.
                                                                       {
    TRACE("> MemoryContentTable: Invalidating based on "
          << base << ", " << index << ", " << offset);
    base = ResolveBase(base);
    if (non_aliasing_objects_.Get(base)) {
      TRACE(">> base is non-aliasing");
      // Since {base} is non-aliasing, it's enough to just iterate the values at
      // this base.
      auto base_keys = base_keys_.find(base);
      if (base_keys == base_keys_.end()) return;
      for (auto it = base_keys->second.with_offsets.begin();
           it != base_keys->second.with_offsets.end();) {
        Key key = *it;
        DCHECK_EQ(key.data().mem.base, base);
        DCHECK(!key.data().mem.index.valid());
        if (index.valid() || offset == key.data().mem.offset) {
          // Overwrites {key}.
          it = base_keys->second.with_offsets.RemoveAt(it);
          TRACE(">>> invalidating " << key.data().mem);
          Set(key, OpIndex::Invalid());
        } else {
          ++it;
        }
      }
      // Invalidating all of the value with valid Index at base {base}.
      for (auto it = base_keys->second.with_indices.begin();
           it != base_keys->second.with_indices.end();) {
        Key key = *it;
        DCHECK(key.data().mem.index.valid());
        it = base_keys->second.with_indices.RemoveAt(it);
        Set(key, OpIndex::Invalid());
      }
    } else {
      TRACE(">> base is maybe-aliasing");
      // {base} could alias with other things, so we iterate the whole state.
      if (index.valid()) {
        // {index} could be anything, so we invalidate everything.
        TRACE(">> Invalidating everything because of valid index");
        return InvalidateMaybeAliasing();
      }
      // Invalidating all of the values with valid Index.
      // TODO(dmercadier): we could keep keys that don't alias here, but that
      // would require doing a map lookup on the base of each key. A better
      // alternative would probably be to have 2 {non_alias_index_keys_} and
      // {maybe_alias_index_keys_} tables instead of just {index_keys_}. This
      // has the downside that when a base stops being non-alias, all of its
      // indexed memory cells have to be moved. This could be worked around by
      // having these 2 tables contain BaseData.with_indices values instead of
      // Keys, so that a whole BaseData.with_indices can be removed in a single
      // operation from the global {non_alias_index_keys_}.
      for (auto it = index_keys_.begin(); it != index_keys_.end();) {
        Key key = *it;
        it = index_keys_.RemoveAt(it);
        TRACE(">>> Invalidating indexed memory " << key.data().mem);
        Set(key, OpIndex::Invalid());
      }
      TRACE(">>> Invalidating everything maybe-aliasing at offset " << offset);
      InvalidateAtOffset(offset, base);
    }
  }
References base_keys_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), v8::internal::index, index_keys_, v8::internal::compiler::turboshaft::OpIndex::Invalid(), InvalidateAtOffset(), InvalidateMaybeAliasing(), v8::internal::key, non_aliasing_objects_, ResolveBase(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< MemoryContentTable, OpIndex, KeyData >::Set(), and v8::internal::TRACE().
InvalidateAtOffset()
void v8::internal::compiler::turboshaft::MemoryContentTable::InvalidateAtOffset (int32_t offset, OpIndex base) [inline], [private]
Definition at line 572 of file late-load-elimination-reducer.h.
                                                        {
    MapMaskAndOr base_maps = object_maps_.Get(base);
    auto offset_keys = offset_keys_.find(offset);
    if (offset_keys == offset_keys_.end()) return;
    for (auto it = offset_keys->second.begin();
         it != offset_keys->second.end();) {
      Key key = *it;
      DCHECK_EQ(offset, key.data().mem.offset);
      // It can overwrite previous stores to any base (except non-aliasing
      // ones).
      if (non_aliasing_objects_.Get(key.data().mem.base)) {
        ++it;
        continue;
      }
      MapMaskAndOr this_maps = key.data().mem.base == base
                                   ? base_maps
                                   : object_maps_.Get(key.data().mem.base);
      if (!is_empty(base_maps) && !is_empty(this_maps) &&
          !CouldHaveSameMap(base_maps, this_maps)) {
        TRACE(">>>> InvalidateAtOffset: not invalidating thanks for maps: "
              << key.data().mem);
        ++it;
        continue;
      }
      it = offset_keys->second.RemoveAt(it);
      TRACE(">>>> InvalidateAtOffset: invalidating " << key.data().mem);
      Set(key, OpIndex::Invalid());
    }
  }
References v8::internal::compiler::turboshaft::CouldHaveSameMap(), DCHECK_EQ, v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::is_empty(), v8::internal::key, non_aliasing_objects_, object_maps_, offset_keys_, v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< MemoryContentTable, OpIndex, KeyData >::Set(), and v8::internal::TRACE().
Referenced by Invalidate().
InvalidateMaybeAliasing()
void v8::internal::compiler::turboshaft::MemoryContentTable::InvalidateMaybeAliasing () [inline]
Definition at line 413 of file late-load-elimination-reducer.h.
                                 {
    TRACE(">> InvalidateMaybeAliasing");
    // We find current active keys through {base_keys_} so that we can bail out
    // for whole buckets non-aliasing bases (if we had gone through
    // {offset_keys_} instead, then for each key we would've had to check
    // whether it was non-aliasing or not).
    for (auto& base_keys : base_keys_) {
      OpIndex base = base_keys.first;
      if (non_aliasing_objects_.Get(base)) continue;
      for (auto it = base_keys.second.with_offsets.begin();
           it != base_keys.second.with_offsets.end();) {
        Key key = *it;
        // It's important to remove with RemoveAt before Setting the key to
        // invalid, otherwise OnKeyChange will remove {key} from {base_keys},
        // which will invalidate {it}.
        it = base_keys.second.with_offsets.RemoveAt(it);
        TRACE(">>> Invalidating " << key.data().mem);
        Set(key, OpIndex::Invalid());
      }
      for (auto it = base_keys.second.with_indices.begin();
           it != base_keys.second.with_indices.end();) {
        Key key = *it;
        it = base_keys.second.with_indices.RemoveAt(it);
        TRACE(">>> Invalidating " << key.data().mem);
        Set(key, OpIndex::Invalid());
      }
    }
  }
References base_keys_, v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::key, non_aliasing_objects_, v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< MemoryContentTable, OpIndex, KeyData >::Set(), and v8::internal::TRACE().
Referenced by Invalidate(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessAtomicRMW(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessCall(), and v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessStore().
OnNewKey()
void v8::internal::compiler::turboshaft::MemoryContentTable::OnNewKey (Key key, OpIndex value) [inline]
Definition at line 326 of file late-load-elimination-reducer.h.
                                        {
    if (value.valid()) {
      AddKeyInBaseOffsetMaps(key);
    }
  }
References AddKeyInBaseOffsetMaps(), v8::internal::key, and v8::internal::value.
OnValueChange()
void v8::internal::compiler::turboshaft::MemoryContentTable::OnValueChange (Key key, OpIndex old_value, OpIndex new_value) [inline]
Definition at line 332 of file late-load-elimination-reducer.h.
                                                                    {
    DCHECK_NE(old_value, new_value);
    if (old_value.valid() && !new_value.valid()) {
      RemoveKeyFromBaseOffsetMaps(key);
    } else if (new_value.valid() && !old_value.valid()) {
      AddKeyInBaseOffsetMaps(key);
    } else {
      DCHECK_EQ(new_value.valid(), old_value.valid());
    }
  }
References AddKeyInBaseOffsetMaps(), DCHECK_EQ, DCHECK_NE, v8::internal::key, RemoveKeyFromBaseOffsetMaps(), and v8::internal::compiler::turboshaft::OpIndex::valid().
RemoveKeyFromBaseOffsetMaps()
void v8::internal::compiler::turboshaft::MemoryContentTable::RemoveKeyFromBaseOffsetMaps (Key key) [inline], [private]
Definition at line 646 of file late-load-elimination-reducer.h.
                                            {
    // Removing from {base_keys_}.
    v8::base::DoublyThreadedList<Key, BaseListTraits>::Remove(key);
    v8::base::DoublyThreadedList<Key, OffsetListTraits>::Remove(key);
  }
References v8::internal::key, and v8::base::DoublyThreadedList< T, DTLTraits >::Remove().
Referenced by OnValueChange().
ResolveBase()
OpIndex v8::internal::compiler::turboshaft::MemoryContentTable::ResolveBase (OpIndex base) [inline], [private]
Definition at line 602 of file late-load-elimination-reducer.h.
                                    {
    while (replacements_[base].IsLoadElimination()) {
      base = replacements_[base].replacement();
    }
    return base;
  }
References replacements_.
Referenced by Find(), Insert(), InsertImmutable(), and Invalidate().
Member Data Documentation
all_keys_
ZoneAbslFlatHashMap<MemoryAddress, Key> v8::internal::compiler::turboshaft::MemoryContentTable::all_keys_ [private]
Definition at line 658 of file late-load-elimination-reducer.h.
Referenced by Find(), Insert(), and InsertImmutable().
base_keys_
ZoneAbslFlatHashMap<OpIndex, BaseData> v8::internal::compiler::turboshaft::MemoryContentTable::base_keys_ [private]
Definition at line 660 of file late-load-elimination-reducer.h.
Referenced by AddKeyInBaseOffsetMaps(), Invalidate(), and InvalidateMaybeAliasing().
index_keys_
v8::base::DoublyThreadedList<Key, OffsetListTraits> v8::internal::compiler::turboshaft::MemoryContentTable::index_keys_ [private]
Definition at line 666 of file late-load-elimination-reducer.h.
Referenced by AddKeyInBaseOffsetMaps(), and Invalidate().
kMaxKeys
constexpr size_t v8::internal::compiler::turboshaft::MemoryContentTable::kMaxKeys = 10000 [static], [constexpr], [private]
Definition at line 511 of file late-load-elimination-reducer.h.
Referenced by Insert(), and InsertImmutable().
non_aliasing_objects_
SparseOpIndexSnapshotTable<bool>& v8::internal::compiler::turboshaft::MemoryContentTable::non_aliasing_objects_ [private]
Definition at line 652 of file late-load-elimination-reducer.h.
Referenced by Invalidate(), InvalidateAtOffset(), and InvalidateMaybeAliasing().
object_maps_
SparseOpIndexSnapshotTable<MapMaskAndOr>& v8::internal::compiler::turboshaft::MemoryContentTable::object_maps_ [private]
Definition at line 653 of file late-load-elimination-reducer.h.
Referenced by InvalidateAtOffset().
offset_keys_
ZoneAbslFlatHashMap<int, v8::base::DoublyThreadedList<Key, OffsetListTraits> > v8::internal::compiler::turboshaft::MemoryContentTable::offset_keys_ [private]
Definition at line 663 of file late-load-elimination-reducer.h.
Referenced by AddKeyInBaseOffsetMaps(), and InvalidateAtOffset().
replacements_
FixedOpIndexSidetable<Replacement>& v8::internal::compiler::turboshaft::MemoryContentTable::replacements_ [private]
Definition at line 654 of file late-load-elimination-reducer.h.
Referenced by ResolveBase().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/late-load-elimination-reducer.h