v8::internal::Block Class Reference
#include <ast.h>
Public Member Functions
ZonePtrList< Statement > * statements ()
bool ignore_completion_value () const
bool is_breakable () const
bool is_initialization_block_for_parameters () const
Scope * scope () const
void set_scope (Scope *scope)
void InitializeStatements (const ScopedPtrList< Statement > &statements, Zone *zone)
Protected Member Functions
Block (Zone *zone, int capacity, bool ignore_completion_value, bool is_breakable, bool is_initialization_block_for_parameters)
Block (bool ignore_completion_value, bool is_breakable, bool is_initialization_block_for_parameters)
Private Types
using IgnoreCompletionField = BreakableStatement::NextBitField< bool, 1 >
using IsBreakableField = IgnoreCompletionField::Next< bool, 1 >
using IsInitializationBlockForParametersField = IsBreakableField::Next< bool, 1 >
Private Attributes
friend Zone
ZonePtrList< Statement > statements_
Scope * scope_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 309 of file ast.h.
Member Typedef Documentation
IgnoreCompletionField
using v8::internal::Block::IgnoreCompletionField = BreakableStatement::NextBitField<bool, 1> [private]
Definition at line 336 of file ast.h.
IsBreakableField
using v8::internal::Block::IsBreakableField = IgnoreCompletionField::Next<bool, 1> [private]
Definition at line 337 of file ast.h.
IsInitializationBlockForParametersField
using v8::internal::Block::IsInitializationBlockForParametersField = IsBreakableField::Next<bool, 1> [private]
Definition at line 338 of file ast.h.
Constructor & Destructor Documentation
Block() [1/2]
v8::internal::Block::Block (Zone * zone, int capacity, bool ignore_completion_value, bool is_breakable, bool is_initialization_block_for_parameters) [inline], [protected]
Definition at line 342 of file ast.h.
      : BreakableStatement(kNoSourcePosition, kBlock),
        statements_(capacity, zone),
        scope_(nullptr) {
    bit_field_ |= IgnoreCompletionField::encode(ignore_completion_value) |
                  IsBreakableField::encode(is_breakable) |
                  IsInitializationBlockForParametersField::encode(
                      is_initialization_block_for_parameters);
  }
References v8::internal::AstNode::bit_field_, v8::base::BitField< T, shift, size, U >::encode(), ignore_completion_value(), is_breakable(), is_initialization_block_for_parameters(), and v8::internal::kBlock.
Block() [2/2]
v8::internal::Block::Block (bool ignore_completion_value, bool is_breakable, bool is_initialization_block_for_parameters) [inline], [protected]
Definition at line 353 of file ast.h.
      : Block(nullptr, 0, ignore_completion_value, is_breakable,
              is_initialization_block_for_parameters) {}
Member Function Documentation
ignore_completion_value()
bool v8::internal::Block::ignore_completion_value () const [inline]
Definition at line 312 of file ast.h.
                                       {
    return IgnoreCompletionField::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by Block().
InitializeStatements()
void v8::internal::Block::InitializeStatements (const ScopedPtrList< Statement > & statements, Zone * zone) [inline]
Definition at line 323 of file ast.h.
                                        {
    DCHECK_EQ(0, statements_.length());
    statements_ = ZonePtrList<Statement>(statements.ToConstVector(), zone);
  }
References DCHECK_EQ, statements(), and statements_.
is_breakable()
bool v8::internal::Block::is_breakable () const [inline]
Definition at line 315 of file ast.h.
{ return IsBreakableField::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by Block().
is_initialization_block_for_parameters()
bool v8::internal::Block::is_initialization_block_for_parameters () const [inline]
Definition at line 316 of file ast.h.
                                                      {
    return IsInitializationBlockForParametersField::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by Block().
scope()
Scope* v8::internal::Block::scope () const [inline]
Definition at line 320 of file ast.h.
{ return scope_; }
References scope_.
Referenced by v8::internal::Parser::InsertShadowingVarBindingInitializers(), v8::internal::Parser::RewriteTryStatement(), and set_scope().
set_scope()
void v8::internal::Block::set_scope (Scope * scope) [inline]
Definition at line 321 of file ast.h.
{ scope_ = scope; }
References scope(), and scope_.
Referenced by v8::internal::Parser::DesugarLexicalBindingsInForStatement(), and v8::internal::Parser::RewriteSwitchStatement().
statements()
ZonePtrList<Statement>* v8::internal::Block::statements () [inline]
Definition at line 311 of file ast.h.
{ return &statements_; }
References statements_.
Referenced by v8::internal::Processor::AssignUndefinedBefore(), v8::internal::Parser::DesugarBindingInForEachStatement(), v8::internal::Parser::DesugarLexicalBindingsInForStatement(), v8::internal::Parser::IgnoreCompletion(), InitializeStatements(), v8::internal::Parser::InsertShadowingVarBindingInitializers(), v8::internal::SourceRangeAstVisitor::MaybeRemoveContinuationRangeOfAsyncReturn(), v8::internal::Parser::RewriteForVarInLegacy(), v8::internal::Parser::RewriteSwitchStatement(), v8::internal::Parser::RewriteTryStatement(), and v8::internal::SourceRangeAstVisitor::VisitBlock().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 330 of file ast.h.
Member Data Documentation
scope_
Scope* v8::internal::Block::scope_ [private]
Definition at line 334 of file ast.h.
Referenced by scope(), and set_scope().
statements_
ZonePtrList<Statement> v8::internal::Block::statements_ [private]
Definition at line 333 of file ast.h.
Referenced by InitializeStatements(), and statements().
Zone
friend v8::internal::Block::Zone [private]
Definition at line 331 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h