v8::base::iterator_range< ForwardIterator > Class Template Reference
#include <iterator.h>
Public Types
using iterator = ForwardIterator
using const_iterator = ForwardIterator
using pointer = typename std::iterator_traits< iterator >::pointer
using reference = typename std::iterator_traits< iterator >::reference
using value_type = typename std::iterator_traits< iterator >::value_type
using difference_type = typename std::iterator_traits< iterator >::difference_type
Public Member Functions
iterator_range ()
iterator_range (ForwardIterator begin, ForwardIterator end)
iterator begin () const
iterator end () const
const_iterator cbegin () const
const_iterator cend () const
auto rbegin () const
auto rend () const
bool empty () const
reference operator[] (difference_type n)
difference_type size () const
Private Attributes
const_iterator const begin_
const_iterator const end_
Detailed Description
template<typename ForwardIterator>
class v8::base::iterator_range< ForwardIterator >
Definition at line 32 of file iterator.h.
Member Typedef Documentation
const_iterator
template<typename ForwardIterator >
using v8::base::iterator_range< ForwardIterator >::const_iterator = ForwardIterator
Definition at line 35 of file iterator.h.
difference_type
template<typename ForwardIterator >
using v8::base::iterator_range< ForwardIterator >::difference_type = typename std::iterator_traits<iterator>::difference_type
Definition at line 39 of file iterator.h.
iterator
template<typename ForwardIterator >
using v8::base::iterator_range< ForwardIterator >::iterator = ForwardIterator
Definition at line 34 of file iterator.h.
pointer
template<typename ForwardIterator >
using v8::base::iterator_range< ForwardIterator >::pointer = typename std::iterator_traits<iterator>::pointer
Definition at line 36 of file iterator.h.
reference
template<typename ForwardIterator >
using v8::base::iterator_range< ForwardIterator >::reference = typename std::iterator_traits<iterator>::reference
Definition at line 37 of file iterator.h.
value_type
template<typename ForwardIterator >
using v8::base::iterator_range< ForwardIterator >::value_type = typename std::iterator_traits<iterator>::value_type
Definition at line 38 of file iterator.h.
Constructor & Destructor Documentation
iterator_range() [1/2]
template<typename ForwardIterator >
v8::base::iterator_range< ForwardIterator >::iterator_range () [inline]
Definition at line 42 of file iterator.h.
: begin_(), end_() {}
iterator_range() [2/2]
template<typename ForwardIterator >
v8::base::iterator_range< ForwardIterator >::iterator_range (ForwardIterator begin, ForwardIterator end) [inline]
Definition at line 43 of file iterator.h.
      : begin_(begin), end_(end) {}
Member Function Documentation
begin()
template<typename ForwardIterator >
iterator v8::base::iterator_range< ForwardIterator >::begin () const [inline]
Definition at line 46 of file iterator.h.
{ return begin_; }
References v8::base::iterator_range< ForwardIterator >::begin_.
Referenced by v8::base::IterateWithoutFirst(), v8::base::IterateWithoutLast(), v8::base::iterator_range< ForwardIterator >::operator[](), and v8::internal::maglev::detail::PushIterator().
cbegin()
template<typename ForwardIterator >
const_iterator v8::base::iterator_range< ForwardIterator >::cbegin () const [inline]
Definition at line 48 of file iterator.h.
{ return begin_; }
References v8::base::iterator_range< ForwardIterator >::begin_.
Referenced by v8::base::iterator_range< ForwardIterator >::empty(), and v8::base::iterator_range< ForwardIterator >::size().
cend()
template<typename ForwardIterator >
const_iterator v8::base::iterator_range< ForwardIterator >::cend () const [inline]
Definition at line 49 of file iterator.h.
{ return end_; }
References v8::base::iterator_range< ForwardIterator >::end_.
Referenced by v8::base::iterator_range< ForwardIterator >::empty(), and v8::base::iterator_range< ForwardIterator >::size().
empty()
template<typename ForwardIterator >
bool v8::base::iterator_range< ForwardIterator >::empty () const [inline]
Definition at line 53 of file iterator.h.
{ return cbegin() == cend(); }
References v8::base::iterator_range< ForwardIterator >::cbegin(), and v8::base::iterator_range< ForwardIterator >::cend().
end()
template<typename ForwardIterator >
iterator v8::base::iterator_range< ForwardIterator >::end () const [inline]
Definition at line 47 of file iterator.h.
{ return end_; }
References v8::base::iterator_range< ForwardIterator >::end_.
Referenced by v8::base::IterateWithoutFirst(), v8::base::IterateWithoutLast(), and v8::internal::maglev::detail::PushIterator().
operator[]()
template<typename ForwardIterator >
reference v8::base::iterator_range< ForwardIterator >::operator[] (difference_type n) [inline]
Definition at line 56 of file iterator.h.
{ return begin()[n]; }
References v8::base::iterator_range< ForwardIterator >::begin().
rbegin()
template<typename ForwardIterator >
auto v8::base::iterator_range< ForwardIterator >::rbegin () const [inline]
Definition at line 50 of file iterator.h.
{ return std::make_reverse_iterator(end_); }
References v8::base::iterator_range< ForwardIterator >::end_.
Referenced by v8::internal::maglev::detail::PushIteratorReverse().
rend()
template<typename ForwardIterator >
auto v8::base::iterator_range< ForwardIterator >::rend () const [inline]
Definition at line 51 of file iterator.h.
{ return std::make_reverse_iterator(begin_); }
References v8::base::iterator_range< ForwardIterator >::begin_.
Referenced by v8::internal::maglev::detail::PushIteratorReverse().
size()
template<typename ForwardIterator >
difference_type v8::base::iterator_range< ForwardIterator >::size () const [inline]
Definition at line 57 of file iterator.h.
{ return cend() - cbegin(); }
References v8::base::iterator_range< ForwardIterator >::cbegin(), and v8::base::iterator_range< ForwardIterator >::cend().
Member Data Documentation
begin_
template<typename ForwardIterator >
const_iterator const v8::base::iterator_range< ForwardIterator >::begin_ [private]
Definition at line 60 of file iterator.h.
Referenced by v8::base::iterator_range< ForwardIterator >::begin(), v8::base::iterator_range< ForwardIterator >::cbegin(), and v8::base::iterator_range< ForwardIterator >::rend().
end_
template<typename ForwardIterator >
const_iterator const v8::base::iterator_range< ForwardIterator >::end_ [private]
Definition at line 61 of file iterator.h.
Referenced by v8::base::iterator_range< ForwardIterator >::cend(), v8::base::iterator_range< ForwardIterator >::end(), and v8::base::iterator_range< ForwardIterator >::rbegin().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/iterator.h