v8::internal::compiler::Effect Class Reference
#include <node.h>
Public Member Functions
constexpr Effect (Node *node)
Node * operator= (Node *value)
Additional Inherited Members
Detailed Description
Definition at line 339 of file node.h.
Constructor & Destructor Documentation
Effect()
constexpr v8::internal::compiler::Effect::Effect (Node * node) [inline], [explicit], [constexpr]
Definition at line 341 of file node.h.
                                        : NodeWrapper(node) {
    // TODO(jgruber): Remove the End special case.
    SLOW_DCHECK(node == nullptr || node->op()->opcode() == IrOpcode::kEnd ||
                node->op()->EffectOutputCount() > 0);
  }
References v8::internal::compiler::Operator::EffectOutputCount(), v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, v8::internal::compiler::Node::op(), v8::internal::compiler::Operator::opcode(), and SLOW_DCHECK.
Member Function Documentation
operator=()
Node* v8::internal::compiler::Effect::operator= (Node * value) [inline]
Definition at line 348 of file node.h.
                               {
    DCHECK_GT(value->op()->EffectOutputCount(), 0);
    set_node(value);
    return value;
  }
References DCHECK_GT, and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/node.h