v8_inspector::V8Debugger Class Reference
#include <v8-debugger.h>
Classes
struct CachedStackFrameKey
Public Member Functions
V8Debugger (v8::Isolate *, V8InspectorImpl *)
~V8Debugger () override
V8Debugger (const V8Debugger &)=delete
V8Debugger & operator= (const V8Debugger &)=delete
bool enabled () const
v8::Isolate * isolate () const
void setBreakpointsActive (bool)
void removeBreakpoint (v8::debug::BreakpointId id)
v8::debug::ExceptionBreakState getPauseOnExceptionsState ()
void setPauseOnExceptionsState (v8::debug::ExceptionBreakState)
bool canBreakProgram ()
bool isInInstrumentationPause () const
void breakProgram (int targetContextGroupId)
void interruptAndBreak (int targetContextGroupId)
void requestPauseAfterInstrumentation ()
void continueProgram (int targetContextGroupId, bool terminateOnResume=false)
void breakProgramOnAssert (int targetContextGroupId)
void setPauseOnNextCall (bool, int targetContextGroupId)
void stepIntoStatement (int targetContextGroupId, bool breakOnAsyncCall)
void stepOverStatement (int targetContextGroupId)
void stepOutOfFunction (int targetContextGroupId)
void terminateExecution (v8::Local< v8::Context > context, std::unique_ptr< TerminateExecutionCallback > callback)
Response continueToLocation (int targetContextGroupId, V8DebuggerScript *script, std::unique_ptr< protocol::Debugger::Location >, const String16 &targetCallFramess)
bool restartFrame (int targetContextGroupId, int callFrameOrdinal)
std::vector< std::unique_ptr< V8DebuggerScript > > getCompiledScripts (int contextGroupId, V8DebuggerAgentImpl *agent)
void enable ()
void disable ()
bool isPaused () const
bool isPausedInContextGroup (int contextGroupId) const
int maxAsyncCallChainDepth ()
void setAsyncCallStackDepth (V8DebuggerAgentImpl *, int)
int maxCallStackSizeToCapture () const
void setMaxCallStackSizeToCapture (V8RuntimeAgentImpl *, int)
std::shared_ptr< AsyncStackTrace > currentAsyncParent ()
V8StackTraceId currentExternalParent ()
std::shared_ptr< StackFrame > symbolize (v8::Local< v8::StackFrame > v8Frame)
std::unique_ptr< V8StackTraceImpl > createStackTrace (v8::Local< v8::StackTrace >)
std::unique_ptr< V8StackTraceImpl > captureStackTrace (bool fullStack)
v8::MaybeLocal< v8::Array > internalProperties (v8::Local< v8::Context >, v8::Local< v8::Value >)
v8::Local< v8::Array > queryObjects (v8::Local< v8::Context > context, v8::Local< v8::Object > prototype)
void asyncTaskScheduled (const StringView &taskName, void *task, bool recurring)
void asyncTaskCanceled (void *task)
void asyncTaskStarted (void *task)
void asyncTaskFinished (void *task)
void allAsyncTasksCanceled ()
V8StackTraceId storeCurrentStackTrace (const StringView &description)
void externalAsyncTaskStarted (const V8StackTraceId &parent)
void externalAsyncTaskFinished (const V8StackTraceId &parent)
uintptr_t storeStackTrace (std::shared_ptr< AsyncStackTrace > stack)
void muteScriptParsedEvents ()
void unmuteScriptParsedEvents ()
V8InspectorImpl * inspector ()
void setMaxAsyncTaskStacksForTest (int limit)
void dumpAsyncTaskStacksStateForTest ()
void asyncParentFor (int stackTraceId, std::shared_ptr< AsyncStackTrace > *asyncParent, V8StackTraceId *externalParent) const
internal::V8DebuggerId debuggerIdFor (int contextGroupId)
std::shared_ptr< AsyncStackTrace > stackTraceFor (int contextGroupId, const V8StackTraceId &id)
void reportTermination ()
Private Types
enum ScopeTargetKind { FUNCTION
, GENERATOR
 }
using AsyncTaskToStackTrace = std::unordered_map< void *, std::weak_ptr< AsyncStackTrace > >
using StackTraceToAsyncParent = std::unordered_map< int, std::weak_ptr< AsyncStackTrace > >
using StackTraceToExternalParent = std::deque< std::pair< int, V8StackTraceId > >
using StoredStackTraces = std::unordered_map< uintptr_t, std::weak_ptr< AsyncStackTrace > >
Private Member Functions
bool addInternalObject (v8::Local< v8::Context > context, v8::Local< v8::Object > object, V8InternalValueType type)
void clearContinueToLocation ()
bool shouldContinueToCurrentLocation ()
void installTerminateExecutionCallbacks (v8::Local< v8::Context > context)
void handleProgramBreak (v8::Local< v8::Context > pausedContext, v8::Local< v8::Value > exception, const std::vector< v8::debug::BreakpointId > &hitBreakpoints, v8::debug::BreakReasons break_reasons, v8::debug::ExceptionType exception_type=v8::debug::kException, bool isUncaught=false)
v8::MaybeLocal< v8::Value > getTargetScopes (v8::Local< v8::Context >, v8::Local< v8::Value >, ScopeTargetKind)
v8::MaybeLocal< v8::Value > functionScopes (v8::Local< v8::Context >, v8::Local< v8::Function >)
v8::MaybeLocal< v8::Value > generatorScopes (v8::Local< v8::Context >, v8::Local< v8::Value >)
v8::MaybeLocal< v8::Array > collectionsEntries (v8::Local< v8::Context > context, v8::Local< v8::Value > value)
v8::MaybeLocal< v8::Array > privateMethods (v8::Local< v8::Context > context, v8::Local< v8::Value > value)
void asyncTaskScheduledForStack (const StringView &taskName, void *task, bool recurring, bool skipTopFrame=false)
void asyncTaskCanceledForStack (void *task)
void asyncTaskStartedForStack (void *task)
void asyncTaskFinishedForStack (void *task)
void asyncTaskCandidateForStepping (void *task)
void asyncTaskStartedForStepping (void *task)
void asyncTaskFinishedForStepping (void *task)
void asyncTaskCanceledForStepping (void *task)
void asyncStackTraceCaptured (int id)
void AsyncEventOccurred (v8::debug::DebugAsyncActionType type, int id, bool isBlackboxed) override
void ScriptCompiled (v8::Local< v8::debug::Script > script, bool is_live_edited, bool has_compile_error) override
void BreakProgramRequested (v8::Local< v8::Context > paused_context, const std::vector< v8::debug::BreakpointId > &break_points_hit, v8::debug::BreakReasons break_reasons) override
ActionAfterInstrumentation BreakOnInstrumentation (v8::Local< v8::Context > paused_context, v8::debug::BreakpointId) override
void ExceptionThrown (v8::Local< v8::Context > paused_context, v8::Local< v8::Value > exception, v8::Local< v8::Value > promise, bool is_uncaught, v8::debug::ExceptionType exception_type) override
bool IsFunctionBlackboxed (v8::Local< v8::debug::Script > script, const v8::debug::Location &start, const v8::debug::Location &end) override
bool ShouldBeSkipped (v8::Local< v8::debug::Script > script, int line, int column) override
void BreakpointConditionEvaluated (v8::Local< v8::Context > context, v8::debug::BreakpointId breakpoint_id, bool exception_thrown, v8::Local< v8::Value > exception) override
int currentContextGroupId ()
bool hasScheduledBreakOnNextFunctionCall () const
void quitMessageLoopIfAgentsFinishedInstrumentation ()
void collectOldAsyncStacksIfNeeded ()
Static Private Member Functions
static size_t nearHeapLimitCallback (void *data, size_t current_heap_limit, size_t initial_heap_limit)
static void terminateExecutionCompletedCallback (v8::Isolate *isolate)
static void terminateExecutionCompletedCallbackIgnoringData (v8::Isolate *isolate, void *)
Private Attributes
v8::Isolate * m_isolate
V8InspectorImpl * m_inspector
int m_enableCount
int m_breakpointsActiveCount = 0
int m_ignoreScriptParsedEventsCounter
size_t m_originalHeapLimit = 0
bool m_scheduledOOMBreak = false
int m_targetContextGroupId = 0
int m_pausedContextGroupId = 0
bool m_instrumentationPause = false
bool m_requestedPauseAfterInstrumentation = false
int m_continueToLocationBreakpointId
String16 m_continueToLocationTargetCallFrames
std::unique_ptr< V8StackTraceImpl > m_continueToLocationStack
std::unordered_map< CachedStackFrameKey, std::weak_ptr< StackFrame >, CachedStackFrameKey::Hash, CachedStackFrameKey::Equal > m_cachedStackFrames
AsyncTaskToStackTrace m_asyncTaskStacks
std::unordered_set< void * > m_recurringTasks
size_t m_maxAsyncCallStacks
int m_maxAsyncCallStackDepth
int m_maxCallStackSizeToCapture
std::vector< void * > m_currentTasks
std::vector< std::shared_ptr< AsyncStackTrace > > m_currentAsyncParent
std::vector< V8StackTraceId > m_currentExternalParent
StackTraceToAsyncParent m_asyncParents
StackTraceToExternalParent m_externalParents
std::list< std::shared_ptr< AsyncStackTrace > > m_allAsyncStacks
std::unordered_map< V8DebuggerAgentImpl *, int > m_maxAsyncCallStackDepthMap
std::unordered_map< V8RuntimeAgentImpl *, int > m_maxCallStackSizeToCaptureMap
void * m_taskWithScheduledBreak = nullptr
bool m_externalAsyncTaskPauseRequested = false
bool m_taskWithScheduledBreakPauseRequested = false
bool m_pauseOnNextCallRequested = false
v8::debug::ExceptionBreakState m_pauseOnExceptionsState
bool m_pauseOnAsyncCall = false
StoredStackTraces m_storedStackTraces
uintptr_t m_lastStackTraceId = 0
std::unordered_map< int, internal::V8DebuggerId > m_contextGroupIdToDebuggerId
std::unique_ptr< TerminateExecutionCallback > m_terminateExecutionCallback
v8::Global< v8::Context > m_terminateExecutionCallbackContext
bool m_terminateExecutionReported = true
Additional Inherited Members
Detailed Description
Definition at line 51 of file v8-debugger.h.
Member Typedef Documentation
AsyncTaskToStackTrace
using v8_inspector::V8Debugger::AsyncTaskToStackTrace = std::unordered_map<void*, std::weak_ptr<AsyncStackTrace> > [private]
Definition at line 282 of file v8-debugger.h.
StackTraceToAsyncParent
using v8_inspector::V8Debugger::StackTraceToAsyncParent = std::unordered_map<int, std::weak_ptr<AsyncStackTrace> > [private]
Definition at line 296 of file v8-debugger.h.
StackTraceToExternalParent
using v8_inspector::V8Debugger::StackTraceToExternalParent = std::deque<std::pair<int, V8StackTraceId> > [private]
Definition at line 298 of file v8-debugger.h.
StoredStackTraces
using v8_inspector::V8Debugger::StoredStackTraces = std::unordered_map<uintptr_t, std::weak_ptr<AsyncStackTrace> > [private]
Definition at line 322 of file v8-debugger.h.
Member Enumeration Documentation
ScopeTargetKind
enum v8_inspector::V8Debugger::ScopeTargetKind [private]
Enumerator
FUNCTION
GENERATOR
Definition at line 175 of file v8-debugger.h.
                       {
    FUNCTION,
    GENERATOR,
  };
Constructor & Destructor Documentation
V8Debugger() [1/2]
v8_inspector::V8Debugger::V8Debugger (v8::Isolate * isolate, V8InspectorImpl * inspector)
Definition at line 87 of file v8-debugger.cc.
    : m_isolate(isolate),
      m_inspector(inspector),
      m_enableCount(0),
      m_ignoreScriptParsedEventsCounter(0),
      m_continueToLocationBreakpointId(kNoBreakpointId),
      m_maxAsyncCallStacks(kMaxAsyncTaskStacks),
      m_maxAsyncCallStackDepth(0),
      m_maxCallStackSizeToCapture(
          V8StackTraceImpl::kDefaultMaxCallStackSizeToCapture),
      m_pauseOnExceptionsState(v8::debug::NoBreakOnException) {}
 V8Debugger()
v8_inspector::V8Debugger::~V8Debugger () [override]
Definition at line 99 of file v8-debugger.cc.
                        {
  m_isolate->RemoveCallCompletedCallback(
      &V8Debugger::terminateExecutionCompletedCallback);
  if (!m_terminateExecutionCallbackContext.IsEmpty()) {
    v8::HandleScope handles(m_isolate);
    v8::MicrotaskQueue* microtask_queue =
        m_terminateExecutionCallbackContext.Get(m_isolate)->GetMicrotaskQueue();
    microtask_queue->RemoveMicrotasksCompletedCallback(
        &V8Debugger::terminateExecutionCompletedCallbackIgnoringData,
        microtask_queue);
  }
}
References v8::PersistentBase< T >::Get(), v8::api_internal::IndirectHandleBase::IsEmpty(), m_isolate, m_terminateExecutionCallbackContext, v8::Isolate::RemoveCallCompletedCallback(), v8::MicrotaskQueue::RemoveMicrotasksCompletedCallback(), terminateExecutionCompletedCallback(), and terminateExecutionCompletedCallbackIgnoringData().
V8Debugger() [2/2]
v8_inspector::V8Debugger::V8Debugger (const V8Debugger &) [delete]
Member Function Documentation
addInternalObject()
bool v8_inspector::V8Debugger::addInternalObject (v8::Local< v8::Context > context, v8::Local< v8::Object > object, V8InternalValueType type) [private]
Definition at line 1459 of file v8-debugger.cc.
                                                             {
  int contextId = InspectedContext::contextId(context);
  InspectedContext* inspectedContext = m_inspector->getContext(contextId);
  return inspectedContext ? inspectedContext->addInternalObject(object, type)
                          : false;
}
References v8_inspector::InspectedContext::addInternalObject(), v8_inspector::InspectedContext::contextId(), v8_inspector::V8InspectorImpl::getContext(), m_inspector, and v8::internal::tracing::type.
Referenced by collectionsEntries(), getTargetScopes(), and privateMethods().
allAsyncTasksCanceled()
void v8_inspector::V8Debugger::allAsyncTasksCanceled ()
Definition at line 1343 of file v8-debugger.cc.
                                       {
  m_asyncTaskStacks.clear();
  m_recurringTasks.clear();
  m_currentAsyncParent.clear();
  m_currentExternalParent.clear();
  m_currentTasks.clear();
  m_currentAsyncParent.clear();
  m_externalParents.clear();
  m_allAsyncStacks.clear();
}
References m_allAsyncStacks, m_asyncTaskStacks, m_currentAsyncParent, m_currentExternalParent, m_currentTasks, m_externalParents, and m_recurringTasks.
Referenced by v8_inspector::V8DebuggerAgentImpl::reset(), and setAsyncCallStackDepth().
AsyncEventOccurred()
void v8_inspector::V8Debugger::AsyncEventOccurred (v8::debug::DebugAsyncActionType type, int id, bool isBlackboxed) [override], [private], [virtual]
Implements v8::debug::AsyncEventDelegate.
Definition at line 757 of file v8-debugger.cc.
                                                               {
  // Async task events from Promises are given misaligned pointers to prevent
  // from overlapping with other Blink task identifiers.
  void* task = reinterpret_cast<void*>(id * 2 + 1);
  switch (type) {
    case v8::debug::kDebugPromiseThen:
      asyncTaskScheduledForStack(toStringView("Promise.then"), task, false);
      if (!isBlackboxed) asyncTaskCandidateForStepping(task);
      break;
    case v8::debug::kDebugPromiseCatch:
      asyncTaskScheduledForStack(toStringView("Promise.catch"), task, false);
      if (!isBlackboxed) asyncTaskCandidateForStepping(task);
      break;
    case v8::debug::kDebugPromiseFinally:
      asyncTaskScheduledForStack(toStringView("Promise.finally"), task, false);
      if (!isBlackboxed) asyncTaskCandidateForStepping(task);
      break;
    case v8::debug::kDebugWillHandle:
      asyncTaskStartedForStack(task);
      asyncTaskStartedForStepping(task);
      break;
    case v8::debug::kDebugDidHandle:
      asyncTaskFinishedForStack(task);
      asyncTaskFinishedForStepping(task);
      break;
    case v8::debug::kDebugAwait:
      asyncTaskScheduledForStack(toStringView("await"), task, false, true);
      break;
    case v8::debug::kDebugStackTraceCaptured:
      asyncStackTraceCaptured(id);
      break;
  }
}
References asyncStackTraceCaptured(), asyncTaskCandidateForStepping(), asyncTaskFinishedForStack(), asyncTaskFinishedForStepping(), asyncTaskScheduledForStack(), asyncTaskStartedForStack(), asyncTaskStartedForStepping(), v8::debug::kDebugAwait, v8::debug::kDebugDidHandle, v8::debug::kDebugPromiseCatch, v8::debug::kDebugPromiseFinally, v8::debug::kDebugPromiseThen, v8::debug::kDebugStackTraceCaptured, v8::debug::kDebugWillHandle, v8_inspector::toStringView(), and v8::internal::tracing::type.
asyncParentFor()
void v8_inspector::V8Debugger::asyncParentFor (int stackTraceId, std::shared_ptr< AsyncStackTrace > * asyncParent, V8StackTraceId * externalParent) const
Definition at line 1092 of file v8-debugger.cc.
                                                                      {
  auto it = m_asyncParents.find(stackTraceId);
  if (it != m_asyncParents.end()) {
    *asyncParent = it->second.lock();
    if (*asyncParent && (*asyncParent)->isEmpty()) {
      *asyncParent = (*asyncParent)->parent().lock();
    }
  } else {
    auto externalIt = std::find_if(
        m_externalParents.begin(), m_externalParents.end(),
        [stackTraceId](const auto& p) { return p.first == stackTraceId; });
    if (externalIt != m_externalParents.end()) {
      *externalParent = externalIt->second;
    }
  }
  DCHECK_IMPLIES(!externalParent->IsInvalid(), !*asyncParent);
  DCHECK_IMPLIES(*asyncParent, externalParent->IsInvalid());
}
References DCHECK_IMPLIES, v8_inspector::V8StackTraceId::IsInvalid(), m_asyncParents, and m_externalParents.
Referenced by v8_inspector::AsyncStackTrace::capture(), and v8_inspector::V8StackTraceImpl::create().
asyncStackTraceCaptured()
void v8_inspector::V8Debugger::asyncStackTraceCaptured (int id) [private]
Definition at line 1332 of file v8-debugger.cc.
                                               {
  auto async_stack = currentAsyncParent();
  if (async_stack) {
    m_asyncParents.emplace(id, async_stack);
  }
  auto externalParent = currentExternalParent();
  if (!externalParent.IsInvalid()) {
    m_externalParents.push_back(std::make_pair(id, externalParent));
  }
}
References currentAsyncParent(), currentExternalParent(), m_asyncParents, and m_externalParents.
Referenced by AsyncEventOccurred().
asyncTaskCanceled()
void v8_inspector::V8Debugger::asyncTaskCanceled (void * task)
Definition at line 1187 of file v8-debugger.cc.
                                             {
  asyncTaskCanceledForStack(task);
  asyncTaskCanceledForStepping(task);
}
References asyncTaskCanceledForStack(), and asyncTaskCanceledForStepping().
asyncTaskCanceledForStack()
void v8_inspector::V8Debugger::asyncTaskCanceledForStack (void * task) [private]
Definition at line 1238 of file v8-debugger.cc.
                                                     {
#ifdef V8_USE_PERFETTO
  TRACE_EVENT(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
              "v8::Debugger::AsyncTaskCanceled",
              perfetto::Flow::ProcessScoped(reinterpret_cast<uintptr_t>(task)),
              "data", [isolate = m_isolate](perfetto::TracedValue context) {
                AddTraceDataWithSample(isolate, std::move(context));
              });
#endif // V8_USE_PERFETTO
  if (!m_maxAsyncCallStackDepth) return;
  m_asyncTaskStacks.erase(task);
  m_recurringTasks.erase(task);
}
References isolate(), m_asyncTaskStacks, m_isolate, m_maxAsyncCallStackDepth, m_recurringTasks, and TRACE_DISABLED_BY_DEFAULT.
Referenced by asyncTaskCanceled(), and asyncTaskFinishedForStack().
asyncTaskCanceledForStepping()
void v8_inspector::V8Debugger::asyncTaskCanceledForStepping (void * task) [private]
Definition at line 1328 of file v8-debugger.cc.
                                                        {
  asyncTaskFinishedForStepping(task);
}
References asyncTaskFinishedForStepping().
Referenced by asyncTaskCanceled().
asyncTaskCandidateForStepping()
void v8_inspector::V8Debugger::asyncTaskCandidateForStepping (void * task) [private]
Definition at line 1300 of file v8-debugger.cc.
                                                         {
  if (!m_pauseOnAsyncCall) return;
  int contextGroupId = currentContextGroupId();
  if (contextGroupId != m_targetContextGroupId) return;
  m_taskWithScheduledBreak = task;
  m_pauseOnAsyncCall = false;
  v8::debug::ClearStepping(m_isolate); // Cancel step into.
}
References v8::debug::ClearStepping(), currentContextGroupId(), m_isolate, m_pauseOnAsyncCall, m_targetContextGroupId, and m_taskWithScheduledBreak.
Referenced by AsyncEventOccurred(), and asyncTaskScheduled().
asyncTaskFinished()
void v8_inspector::V8Debugger::asyncTaskFinished (void * task)
Definition at line 1197 of file v8-debugger.cc.
                                             {
  asyncTaskFinishedForStepping(task);
  asyncTaskFinishedForStack(task);
}
References asyncTaskFinishedForStack(), and asyncTaskFinishedForStepping().
asyncTaskFinishedForStack()
void v8_inspector::V8Debugger::asyncTaskFinishedForStack (void * task) [private]
Definition at line 1281 of file v8-debugger.cc.
                                                     {
#ifdef V8_USE_PERFETTO
  TRACE_EVENT_END0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
                   "v8::Debugger::AsyncTaskRun");
#endif // V8_USE_PERFETTO
  if (!m_maxAsyncCallStackDepth) return;
  // We could start instrumenting half way and the stack is empty.
  if (m_currentTasks.empty()) return;
  DCHECK(m_currentTasks.back() == task);
  m_currentTasks.pop_back();
  m_currentAsyncParent.pop_back();
  m_currentExternalParent.pop_back();
  if (m_recurringTasks.find(task) == m_recurringTasks.end()) {
    asyncTaskCanceledForStack(task);
  }
}
References asyncTaskCanceledForStack(), DCHECK, m_currentAsyncParent, m_currentExternalParent, m_currentTasks, m_maxAsyncCallStackDepth, m_recurringTasks, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT_END0.
Referenced by AsyncEventOccurred(), and asyncTaskFinished().
asyncTaskFinishedForStepping()
void v8_inspector::V8Debugger::asyncTaskFinishedForStepping (void * task) [private]
Definition at line 1320 of file v8-debugger.cc.
                                                        {
  if (task != m_taskWithScheduledBreak) return;
  m_taskWithScheduledBreak = nullptr;
  m_taskWithScheduledBreakPauseRequested = false;
  if (hasScheduledBreakOnNextFunctionCall()) return;
  v8::debug::ClearBreakOnNextFunctionCall(m_isolate);
}
References v8::debug::ClearBreakOnNextFunctionCall(), hasScheduledBreakOnNextFunctionCall(), m_isolate, m_taskWithScheduledBreak, and m_taskWithScheduledBreakPauseRequested.
Referenced by AsyncEventOccurred(), asyncTaskCanceledForStepping(), and asyncTaskFinished().
asyncTaskScheduled()
void v8_inspector::V8Debugger::asyncTaskScheduled (const StringView & taskName, void * task, bool recurring)
Definition at line 1181 of file v8-debugger.cc.
                                                    {
  asyncTaskScheduledForStack(taskName, task, recurring);
  asyncTaskCandidateForStepping(task);
}
References asyncTaskCandidateForStepping(), and asyncTaskScheduledForStack().
asyncTaskScheduledForStack()
void v8_inspector::V8Debugger::asyncTaskScheduledForStack (const StringView & taskName, void * task, bool recurring, bool skipTopFrame = false) [private]
Definition at line 1214 of file v8-debugger.cc.
                                                               {
#ifdef V8_USE_PERFETTO
  TRACE_EVENT(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
              "v8::Debugger::AsyncTaskScheduled", "taskName",
              TRACE_STR_COPY(toString16(taskName).utf8().c_str()),
              perfetto::Flow::ProcessScoped(reinterpret_cast<uintptr_t>(task)),
              "data", [isolate = m_isolate](perfetto::TracedValue context) {
                AddTraceDataWithSample(isolate, std::move(context));
              });
#endif // V8_USE_PERFETTO
  if (!m_maxAsyncCallStackDepth) return;
  v8::HandleScope scope(m_isolate);
  std::shared_ptr<AsyncStackTrace> asyncStack =
      AsyncStackTrace::capture(this, toString16(taskName), skipTopFrame);
  if (asyncStack) {
    m_asyncTaskStacks[task] = asyncStack;
    if (recurring) m_recurringTasks.insert(task);
    m_allAsyncStacks.push_back(std::move(asyncStack));
    collectOldAsyncStacksIfNeeded();
  }
}
References v8_inspector::AsyncStackTrace::capture(), collectOldAsyncStacksIfNeeded(), isolate(), m_allAsyncStacks, m_asyncTaskStacks, m_isolate, m_maxAsyncCallStackDepth, m_recurringTasks, v8_inspector::toString16(), TRACE_DISABLED_BY_DEFAULT, and TRACE_STR_COPY.
Referenced by AsyncEventOccurred(), and asyncTaskScheduled().
asyncTaskStarted()
void v8_inspector::V8Debugger::asyncTaskStarted (void * task)
Definition at line 1192 of file v8-debugger.cc.
                                            {
  asyncTaskStartedForStack(task);
  asyncTaskStartedForStepping(task);
}
References asyncTaskStartedForStack(), and asyncTaskStartedForStepping().
asyncTaskStartedForStack()
void v8_inspector::V8Debugger::asyncTaskStartedForStack (void * task) [private]
Definition at line 1252 of file v8-debugger.cc.
                                                    {
#ifdef V8_USE_PERFETTO
  TRACE_EVENT_BEGIN(
      TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "v8::Debugger::AsyncTaskRun",
      perfetto::Flow::ProcessScoped(reinterpret_cast<uintptr_t>(task)), "data",
      [isolate = m_isolate](perfetto::TracedValue context) {
        AddTraceDataWithSample(isolate, std::move(context));
      });
#endif // V8_USE_PERFETTO
  if (!m_maxAsyncCallStackDepth) return;
  // Needs to support following order of events:
  // - asyncTaskScheduled
  // <-- attached here -->
  // - asyncTaskStarted
  // - asyncTaskCanceled <-- canceled before finished
  // <-- async stack requested here -->
  // - asyncTaskFinished
  m_currentTasks.push_back(task);
  AsyncTaskToStackTrace::iterator stackIt = m_asyncTaskStacks.find(task);
  if (stackIt != m_asyncTaskStacks.end() && !stackIt->second.expired()) {
    std::shared_ptr<AsyncStackTrace> stack(stackIt->second);
    m_currentAsyncParent.push_back(stack);
  } else {
    m_currentAsyncParent.emplace_back();
  }
  m_currentExternalParent.emplace_back();
}
References isolate(), m_asyncTaskStacks, m_currentAsyncParent, m_currentExternalParent, m_currentTasks, m_isolate, m_maxAsyncCallStackDepth, v8::internal::stack, and TRACE_DISABLED_BY_DEFAULT.
Referenced by AsyncEventOccurred(), and asyncTaskStarted().
asyncTaskStartedForStepping()
void v8_inspector::V8Debugger::asyncTaskStartedForStepping (void * task) [private]
Definition at line 1309 of file v8-debugger.cc.
                                                       {
  // TODO(kozyatinskiy): we should search task in async chain to support
  // blackboxing.
  if (task != m_taskWithScheduledBreak) return;
  bool didHaveBreak = hasScheduledBreakOnNextFunctionCall();
  m_taskWithScheduledBreakPauseRequested = true;
  if (didHaveBreak) return;
  m_targetContextGroupId = currentContextGroupId();
  v8::debug::SetBreakOnNextFunctionCall(m_isolate);
}
References currentContextGroupId(), hasScheduledBreakOnNextFunctionCall(), m_isolate, m_targetContextGroupId, m_taskWithScheduledBreak, m_taskWithScheduledBreakPauseRequested, and v8::debug::SetBreakOnNextFunctionCall().
Referenced by AsyncEventOccurred(), and asyncTaskStarted().
BreakOnInstrumentation()
V8Debugger::ActionAfterInstrumentation v8_inspector::V8Debugger::BreakOnInstrumentation (v8::Local< v8::Context > paused_context, v8::debug::BreakpointId instrumentationId) [override], [private], [virtual]
Reimplemented from v8::debug::DebugDelegate.
Definition at line 622 of file v8-debugger.cc.
                                           {
  // Don't allow nested breaks.
  if (isPaused()) return ActionAfterInstrumentation::kPauseIfBreakpointsHit;
  int contextGroupId = m_inspector->contextGroupId(pausedContext);
  bool hasAgents = false;
  m_inspector->forEachSession(
      contextGroupId, [&hasAgents](V8InspectorSessionImpl* session) {
        if (session->debuggerAgent()->acceptsPause(false /* isOOMBreak */))
          hasAgents = true;
      });
  if (!hasAgents) return ActionAfterInstrumentation::kPauseIfBreakpointsHit;
  m_pausedContextGroupId = contextGroupId;
  m_instrumentationPause = true;
  m_inspector->forEachSession(
      contextGroupId, [instrumentationId](V8InspectorSessionImpl* session) {
        if (session->debuggerAgent()->acceptsPause(false /* isOOMBreak */)) {
          session->debuggerAgent()->didPauseOnInstrumentation(
              instrumentationId);
        }
      });
  {
    v8::Context::Scope scope(pausedContext);
    m_inspector->client()->runMessageLoopOnInstrumentationPause(contextGroupId);
  }
  bool requestedPauseAfterInstrumentation =
      m_requestedPauseAfterInstrumentation;
  m_requestedPauseAfterInstrumentation = false;
  m_pausedContextGroupId = 0;
  m_instrumentationPause = false;
  hasAgents = false;
  m_inspector->forEachSession(
      contextGroupId, [&hasAgents](V8InspectorSessionImpl* session) {
        if (session->debuggerAgent()->enabled())
          session->debuggerAgent()->didContinue();
        if (session->debuggerAgent()->acceptsPause(false /* isOOMBreak */))
          hasAgents = true;
      });
  if (!hasAgents) {
    return ActionAfterInstrumentation::kContinue;
  } else if (requestedPauseAfterInstrumentation) {
    return ActionAfterInstrumentation::kPause;
  } else {
    return ActionAfterInstrumentation::kPauseIfBreakpointsHit;
  }
}
References v8_inspector::V8DebuggerAgentImpl::acceptsPause(), v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorImpl::contextGroupId(), v8_inspector::V8InspectorSessionImpl::debuggerAgent(), v8_inspector::V8DebuggerAgentImpl::didContinue(), v8_inspector::V8DebuggerAgentImpl::enabled(), v8_inspector::V8InspectorImpl::forEachSession(), v8::base::internal::if(), isPaused(), v8::debug::DebugDelegate::kContinue, v8::debug::DebugDelegate::kPause, v8::debug::DebugDelegate::kPauseIfBreakpointsHit, m_inspector, m_instrumentationPause, m_pausedContextGroupId, m_requestedPauseAfterInstrumentation, and v8_inspector::V8InspectorClient::runMessageLoopOnInstrumentationPause().
BreakpointConditionEvaluated()
void v8_inspector::V8Debugger::BreakpointConditionEvaluated (v8::Local< v8::Context > context, v8::debug::BreakpointId breakpoint_id, bool exception_thrown, v8::Local< v8::Value > exception) [override], [private], [virtual]
Reimplemented from v8::debug::DebugDelegate.
Definition at line 734 of file v8-debugger.cc.
                                                       {
  if (!exception_thrown || exception.IsEmpty()) return;
  v8::Local<v8::Message> message =
      v8::debug::CreateMessageFromException(isolate(), exception);
  v8::ScriptOrigin origin = message->GetScriptOrigin();
  String16 url;
  if (origin.ResourceName()->IsString()) {
    url = toProtocolString(isolate(), origin.ResourceName().As<v8::String>());
  }
  // The message text is prepended to the exception text itself so we don't
  // need to get it from the v8::Message.
  StringView messageText;
  StringView detailedMessage;
  m_inspector->exceptionThrown(
      context, messageText, exception, detailedMessage, toStringView(url),
      message->GetLineNumber(context).FromMaybe(0),
      message->GetStartColumn() + 1, createStackTrace(message->GetStackTrace()),
      origin.ScriptId());
}
References v8::debug::CreateMessageFromException(), createStackTrace(), v8_inspector::V8InspectorImpl::exceptionThrown(), v8::api_internal::IndirectHandleBase::IsEmpty(), isolate(), m_inspector, v8::ScriptOrigin::ResourceName(), v8::ScriptOrigin::ScriptId(), v8_inspector::toProtocolString(), and v8_inspector::toStringView().
breakProgram()
void v8_inspector::V8Debugger::breakProgram (int targetContextGroupId)
Definition at line 241 of file v8-debugger.cc.
                                                      {
  DCHECK(canBreakProgram());
  // Don't allow nested breaks.
  if (isPaused()) return;
  DCHECK(targetContextGroupId);
  m_targetContextGroupId = targetContextGroupId;
  v8::debug::BreakRightNow(m_isolate);
}
References v8::debug::BreakRightNow(), canBreakProgram(), DCHECK, isPaused(), m_isolate, and m_targetContextGroupId.
Referenced by v8_inspector::V8DebuggerAgentImpl::breakProgram().
breakProgramOnAssert()
void v8_inspector::V8Debugger::breakProgramOnAssert (int targetContextGroupId)
Definition at line 304 of file v8-debugger.cc.
                                                              {
  if (!enabled()) return;
  if (m_pauseOnExceptionsState == v8::debug::NoBreakOnException) return;
  // Don't allow nested breaks.
  if (isPaused()) return;
  if (!canBreakProgram()) return;
  DCHECK(targetContextGroupId);
  m_targetContextGroupId = targetContextGroupId;
  v8::debug::BreakRightNow(
      m_isolate, v8::debug::BreakReasons({v8::debug::BreakReason::kAssert}));
}
References v8::debug::BreakRightNow(), canBreakProgram(), DCHECK, enabled(), isPaused(), v8::debug::kAssert, m_isolate, m_pauseOnExceptionsState, m_targetContextGroupId, and v8::debug::NoBreakOnException.
Referenced by v8_inspector::V8Console::Assert().
BreakProgramRequested()
void v8_inspector::V8Debugger::BreakProgramRequested (v8::Local< v8::Context > paused_context, const std::vector< v8::debug::BreakpointId > & break_points_hit, v8::debug::BreakReasons break_reasons) [override], [private]
Definition at line 674 of file v8-debugger.cc.
                                 {
  handleProgramBreak(pausedContext, v8::Local<v8::Value>(), break_points_hit,
                     reasons);
}
References handleProgramBreak().
canBreakProgram()
bool v8_inspector::V8Debugger::canBreakProgram ()
Definition at line 233 of file v8-debugger.cc.
                                 {
  return v8::debug::CanBreakProgram(m_isolate);
}
References v8::debug::CanBreakProgram(), and m_isolate.
Referenced by v8_inspector::V8DebuggerAgentImpl::breakProgram(), breakProgram(), breakProgramOnAssert(), and v8_inspector::V8DebuggerAgentImpl::pause().
captureStackTrace()
std::unique_ptr< V8StackTraceImpl > v8_inspector::V8Debugger::captureStackTrace (bool fullStack)
Definition at line 1364 of file v8-debugger.cc.
                    {
  int contextGroupId = currentContextGroupId();
  if (!contextGroupId) return nullptr;
  int stackSize = 1;
  if (fullStack) {
    stackSize = V8StackTraceImpl::kDefaultMaxCallStackSizeToCapture;
  } else {
    m_inspector->forEachSession(
        contextGroupId, [this, &stackSize](V8InspectorSessionImpl* session) {
          if (session->runtimeAgent()->enabled())
            stackSize = maxCallStackSizeToCapture();
        });
  }
  return V8StackTraceImpl::capture(this, stackSize);
}
References v8_inspector::V8StackTraceImpl::capture(), currentContextGroupId(), v8_inspector::V8RuntimeAgentImpl::enabled(), v8_inspector::V8InspectorImpl::forEachSession(), v8_inspector::V8StackTraceImpl::kDefaultMaxCallStackSizeToCapture, m_inspector, maxCallStackSizeToCapture(), and v8_inspector::V8InspectorSessionImpl::runtimeAgent().
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback().
clearContinueToLocation()
void v8_inspector::V8Debugger::clearContinueToLocation () [private]
Definition at line 471 of file v8-debugger.cc.
                                         {
  if (m_continueToLocationBreakpointId == kNoBreakpointId) return;
  v8::debug::RemoveBreakpoint(m_isolate, m_continueToLocationBreakpointId);
  m_continueToLocationBreakpointId = kNoBreakpointId;
  m_continueToLocationTargetCallFrames = String16();
  m_continueToLocationStack.reset();
}
References v8_inspector::anonymous_namespace{v8-debugger.cc}::kNoBreakpointId, m_continueToLocationBreakpointId, m_continueToLocationStack, m_continueToLocationTargetCallFrames, m_isolate, and v8::debug::RemoveBreakpoint().
Referenced by disable(), and handleProgramBreak().
collectionsEntries()
v8::MaybeLocal< v8::Array > v8_inspector::V8Debugger::collectionsEntries (v8::Local< v8::Context > context, v8::Local< v8::Value > value) [private]
Definition at line 888 of file v8-debugger.cc.
                                                             {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::Local<v8::Array> entries;
  bool isKeyValue = false;
  if (!collection->IsObject() || !collection.As<v8::Object>()
                                      ->PreviewEntries(&isKeyValue)
                                      .ToLocal(&entries)) {
    return v8::MaybeLocal<v8::Array>();
  }
  v8::Local<v8::Array> wrappedEntries = v8::Array::New(isolate);
  CHECK(!isKeyValue || wrappedEntries->Length() % 2 == 0);
  if (!wrappedEntries->SetPrototypeV2(context, v8::Null(isolate))
           .FromMaybe(false))
    return v8::MaybeLocal<v8::Array>();
  for (uint32_t i = 0; i < entries->Length(); i += isKeyValue ? 2 : 1) {
    v8::Local<v8::Value> item;
    if (!entries->Get(context, i).ToLocal(&item)) continue;
    v8::Local<v8::Value> value;
    if (isKeyValue && !entries->Get(context, i + 1).ToLocal(&value)) continue;
    v8::Local<v8::Object> wrapper = v8::Object::New(isolate);
    if (!wrapper->SetPrototypeV2(context, v8::Null(isolate)).FromMaybe(false))
      continue;
    createDataProperty(
        context, wrapper,
        toV8StringInternalized(isolate, isKeyValue ? "key" : "value"), item);
    if (isKeyValue) {
      createDataProperty(context, wrapper,
                         toV8StringInternalized(isolate, "value"), value);
    }
    if (!addInternalObject(context, wrapper, V8InternalValueType::kEntry))
      continue;
    createDataProperty(context, wrappedEntries, wrappedEntries->Length(),
                       wrapper);
  }
  return wrappedEntries;
}
References addInternalObject(), v8::Local< T >::As(), CHECK, v8_inspector::createDataProperty(), v8::Object::Get(), v8::Isolate::GetCurrent(), v8::Value::IsObject(), isolate(), v8_inspector::kEntry, v8::Array::Length(), v8::Object::New(), v8::Array::New(), v8::Null(), v8::Object::PreviewEntries(), v8::Object::SetPrototypeV2(), v8::MaybeLocal< T >::ToLocal(), v8_inspector::toV8StringInternalized(), and v8::internal::value.
Referenced by internalProperties().
collectOldAsyncStacksIfNeeded()
void v8_inspector::V8Debugger::collectOldAsyncStacksIfNeeded () [private]
Definition at line 1388 of file v8-debugger.cc.
                                               {
  if (m_allAsyncStacks.size() <= m_maxAsyncCallStacks) return;
  size_t halfOfLimitRoundedUp =
      m_maxAsyncCallStacks / 2 + m_maxAsyncCallStacks % 2;
  while (m_allAsyncStacks.size() > halfOfLimitRoundedUp) {
    m_allAsyncStacks.pop_front();
  }
  cleanupExpiredWeakPointers(m_asyncTaskStacks);
  cleanupExpiredWeakPointers(m_cachedStackFrames);
  cleanupExpiredWeakPointers(m_asyncParents);
  cleanupExpiredWeakPointers(m_storedStackTraces);
  for (auto it = m_recurringTasks.begin(); it != m_recurringTasks.end();) {
    if (m_asyncTaskStacks.find(*it) == m_asyncTaskStacks.end()) {
      it = m_recurringTasks.erase(it);
    } else {
      ++it;
    }
  }
  if (m_externalParents.size() > kMaxExternalParents) {
    size_t halfOfExternalParents = (m_externalParents.size() + 1) / 2;
    while (m_externalParents.size() > halfOfExternalParents) {
      m_externalParents.pop_front();
    }
  }
}
References v8_inspector::anonymous_namespace{v8-debugger.cc}::cleanupExpiredWeakPointers(), v8_inspector::anonymous_namespace{v8-debugger.cc}::kMaxExternalParents, m_allAsyncStacks, m_asyncParents, m_asyncTaskStacks, m_cachedStackFrames, m_externalParents, m_maxAsyncCallStacks, m_recurringTasks, and m_storedStackTraces.
Referenced by asyncTaskScheduledForStack(), setMaxAsyncTaskStacksForTest(), and storeCurrentStackTrace().
continueProgram()
void v8_inspector::V8Debugger::continueProgram (int targetContextGroupId, bool terminateOnResume = false)
Definition at line 282 of file v8-debugger.cc.
                                                         {
  if (m_pausedContextGroupId != targetContextGroupId) return;
  if (isPaused()) {
    if (m_instrumentationPause) {
      quitMessageLoopIfAgentsFinishedInstrumentation();
    } else if (terminateOnResume) {
      v8::debug::SetTerminateOnResume(m_isolate);
      v8::HandleScope handles(m_isolate);
      v8::Local<v8::Context> context =
          m_inspector->client()->ensureDefaultContextInGroup(
              targetContextGroupId);
      installTerminateExecutionCallbacks(context);
      m_inspector->client()->quitMessageLoopOnPause();
    } else {
      m_inspector->client()->quitMessageLoopOnPause();
    }
  }
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorClient::ensureDefaultContextInGroup(), installTerminateExecutionCallbacks(), isPaused(), m_inspector, m_instrumentationPause, m_isolate, m_pausedContextGroupId, quitMessageLoopIfAgentsFinishedInstrumentation(), v8_inspector::V8InspectorClient::quitMessageLoopOnPause(), and v8::debug::SetTerminateOnResume().
Referenced by continueToLocation(), restartFrame(), v8_inspector::V8DebuggerAgentImpl::resume(), stepIntoStatement(), stepOutOfFunction(), and stepOverStatement().
continueToLocation()
Response v8_inspector::V8Debugger::continueToLocation (int targetContextGroupId, V8DebuggerScript * script, std::unique_ptr< protocol::Debugger::Location > location, const String16 & targetCallFramess)
Definition at line 418 of file v8-debugger.cc.
                                      {
  DCHECK(isPaused());
  DCHECK(targetContextGroupId);
  m_targetContextGroupId = targetContextGroupId;
  v8::debug::Location v8Location(location->getLineNumber(),
                                 location->getColumnNumber(0));
  if (script->setBreakpoint(String16(), &v8Location,
                            &m_continueToLocationBreakpointId)) {
    m_continueToLocationTargetCallFrames = targetCallFrames;
    if (m_continueToLocationTargetCallFrames !=
        protocol::Debugger::ContinueToLocation::TargetCallFramesEnum::Any) {
      m_continueToLocationStack = V8StackTraceImpl::capture(
          this, V8StackTraceImpl::kDefaultMaxCallStackSizeToCapture);
      DCHECK(m_continueToLocationStack);
    }
    continueProgram(targetContextGroupId);
    // TODO(kozyatinskiy): Return actual line and column number.
    return Response::Success();
  } else {
    return Response::ServerError("Cannot continue to specified location");
  }
}
References v8_inspector::V8StackTraceImpl::capture(), continueProgram(), DCHECK, isPaused(), v8_inspector::V8StackTraceImpl::kDefaultMaxCallStackSizeToCapture, m_continueToLocationBreakpointId, m_continueToLocationStack, m_continueToLocationTargetCallFrames, m_targetContextGroupId, and v8::internal::script.
Referenced by v8_inspector::V8DebuggerAgentImpl::continueToLocation().
createStackTrace()
std::unique_ptr< V8StackTraceImpl > v8_inspector::V8Debugger::createStackTrace (v8::Local< v8::StackTrace > v8StackTrace)
Definition at line 1026 of file v8-debugger.cc.
                                        {
  return V8StackTraceImpl::create(
      this, v8StackTrace, V8StackTraceImpl::kDefaultMaxCallStackSizeToCapture);
}
References v8_inspector::V8StackTraceImpl::create(), and v8_inspector::V8StackTraceImpl::kDefaultMaxCallStackSizeToCapture.
Referenced by BreakpointConditionEvaluated(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), and v8_inspector::InjectedScript::createExceptionDetails().
currentAsyncParent()
std::shared_ptr< AsyncStackTrace > v8_inspector::V8Debugger::currentAsyncParent ()
Definition at line 792 of file v8-debugger.cc.
                                                              {
  return m_currentAsyncParent.empty() ? nullptr : m_currentAsyncParent.back();
}
References m_currentAsyncParent, and nullptr.
Referenced by asyncStackTraceCaptured(), and v8_inspector::V8DebuggerAgentImpl::currentAsyncStackTrace().
currentContextGroupId()
int v8_inspector::V8Debugger::currentContextGroupId () [private]
Definition at line 1382 of file v8-debugger.cc.
                                      {
  if (!m_isolate->InContext()) return 0;
  v8::HandleScope handleScope(m_isolate);
  return m_inspector->contextGroupId(m_isolate->GetCurrentContext());
}
References v8_inspector::V8InspectorImpl::contextGroupId(), v8::Isolate::GetCurrentContext(), v8::Isolate::InContext(), m_inspector, and m_isolate.
Referenced by asyncTaskCandidateForStepping(), asyncTaskStartedForStepping(), captureStackTrace(), externalAsyncTaskStarted(), and storeCurrentStackTrace().
currentExternalParent()
V8StackTraceId v8_inspector::V8Debugger::currentExternalParent ()
Definition at line 796 of file v8-debugger.cc.
                                                 {
  return m_currentExternalParent.empty() ? V8StackTraceId()
                                         : m_currentExternalParent.back();
}
References m_currentExternalParent.
Referenced by asyncStackTraceCaptured(), and v8_inspector::V8DebuggerAgentImpl::currentExternalStackTrace().
debuggerIdFor()
internal::V8DebuggerId v8_inspector::V8Debugger::debuggerIdFor (int contextGroupId)
Definition at line 1449 of file v8-debugger.cc.
                                                                 {
  auto it = m_contextGroupIdToDebuggerId.find(contextGroupId);
  if (it != m_contextGroupIdToDebuggerId.end()) return it->second;
  internal::V8DebuggerId debuggerId =
      internal::V8DebuggerId::generate(m_inspector);
  m_contextGroupIdToDebuggerId.insert(
      it, std::make_pair(contextGroupId, debuggerId));
  return debuggerId;
}
References v8_inspector::internal::V8DebuggerId::generate(), m_contextGroupIdToDebuggerId, and m_inspector.
Referenced by v8_inspector::V8DebuggerAgentImpl::enable(), v8_inspector::V8DebuggerAgentImpl::getStackTrace(), stackTraceFor(), and storeCurrentStackTrace().
disable()
void v8_inspector::V8Debugger::disable ()
Definition at line 124 of file v8-debugger.cc.
                         {
  if (isPaused()) {
    bool scheduledOOMBreak = m_scheduledOOMBreak;
    bool hasAgentAcceptsPause = false;
    if (m_instrumentationPause) {
      quitMessageLoopIfAgentsFinishedInstrumentation();
    } else {
      m_inspector->forEachSession(
          m_pausedContextGroupId, [&scheduledOOMBreak, &hasAgentAcceptsPause](
                                      V8InspectorSessionImpl* session) {
            if (session->debuggerAgent()->acceptsPause(scheduledOOMBreak)) {
              hasAgentAcceptsPause = true;
            }
          });
      if (!hasAgentAcceptsPause)
        m_inspector->client()->quitMessageLoopOnPause();
    }
  }
  if (--m_enableCount) return;
  clearContinueToLocation();
  m_taskWithScheduledBreak = nullptr;
  m_externalAsyncTaskPauseRequested = false;
  m_taskWithScheduledBreakPauseRequested = false;
  m_pauseOnNextCallRequested = false;
  m_pauseOnAsyncCall = false;
#if V8_ENABLE_WEBASSEMBLY
  v8::debug::LeaveDebuggingForIsolate(m_isolate);
#endif // V8_ENABLE_WEBASSEMBLY
  v8::debug::SetDebugDelegate(m_isolate, nullptr);
  m_isolate->RemoveNearHeapLimitCallback(&V8Debugger::nearHeapLimitCallback,
                                         m_originalHeapLimit);
  m_originalHeapLimit = 0;
}
References v8_inspector::V8DebuggerAgentImpl::acceptsPause(), clearContinueToLocation(), v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorSessionImpl::debuggerAgent(), v8_inspector::V8InspectorImpl::forEachSession(), isPaused(), m_enableCount, m_externalAsyncTaskPauseRequested, m_inspector, m_instrumentationPause, m_isolate, m_originalHeapLimit, m_pausedContextGroupId, m_pauseOnAsyncCall, m_pauseOnNextCallRequested, m_scheduledOOMBreak, m_taskWithScheduledBreak, m_taskWithScheduledBreakPauseRequested, nearHeapLimitCallback(), quitMessageLoopIfAgentsFinishedInstrumentation(), v8_inspector::V8InspectorClient::quitMessageLoopOnPause(), v8::Isolate::RemoveNearHeapLimitCallback(), and v8::debug::SetDebugDelegate().
Referenced by v8_inspector::V8DebuggerAgentImpl::disable().
dumpAsyncTaskStacksStateForTest()
void v8_inspector::V8Debugger::dumpAsyncTaskStacksStateForTest ()
Definition at line 1468 of file v8-debugger.cc.
                                                 {
  fprintf(stdout, "Async stacks count: %zu\n", m_allAsyncStacks.size());
  fprintf(stdout, "Scheduled async tasks: %zu\n", m_asyncTaskStacks.size());
  fprintf(stdout, "Recurring async tasks: %zu\n", m_recurringTasks.size());
  fprintf(stdout, "\n");
}
References m_allAsyncStacks, m_asyncTaskStacks, and m_recurringTasks.
enable()
void v8_inspector::V8Debugger::enable ()
Definition at line 112 of file v8-debugger.cc.
                        {
  if (m_enableCount++) return;
  v8::HandleScope scope(m_isolate);
  v8::debug::SetDebugDelegate(m_isolate, this);
  m_isolate->AddNearHeapLimitCallback(&V8Debugger::nearHeapLimitCallback, this);
  v8::debug::ChangeBreakOnException(m_isolate, v8::debug::NoBreakOnException);
  m_pauseOnExceptionsState = v8::debug::NoBreakOnException;
#if V8_ENABLE_WEBASSEMBLY
  v8::debug::EnterDebuggingForIsolate(m_isolate);
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::Isolate::AddNearHeapLimitCallback(), v8::debug::ChangeBreakOnException(), m_enableCount, m_isolate, m_pauseOnExceptionsState, nearHeapLimitCallback(), v8::debug::NoBreakOnException, and v8::debug::SetDebugDelegate().
Referenced by v8_inspector::V8DebuggerAgentImpl::enableImpl().
enabled()
bool v8_inspector::V8Debugger::enabled () const
Definition at line 163 of file v8-debugger.cc.
{ return m_enableCount > 0; }
References m_enableCount.
Referenced by breakProgramOnAssert(), getPauseOnExceptionsState(), setBreakpointsActive(), and setPauseOnExceptionsState().
ExceptionThrown()
void v8_inspector::V8Debugger::ExceptionThrown (v8::Local< v8::Context > paused_context, v8::Local< v8::Value > exception, v8::Local< v8::Value > promise, bool is_uncaught, v8::debug::ExceptionType exception_type) [override], [private], [virtual]
Reimplemented from v8::debug::DebugDelegate.
Definition at line 682 of file v8-debugger.cc.
                                                                     {
  std::vector<v8::debug::BreakpointId> break_points_hit;
  handleProgramBreak(
      pausedContext, exception, break_points_hit,
      v8::debug::BreakReasons({v8::debug::BreakReason::kException}),
      exceptionType, isUncaught);
}
References handleProgramBreak(), and v8::debug::kException.
externalAsyncTaskFinished()
void v8_inspector::V8Debugger::externalAsyncTaskFinished (const V8StackTraceId & parent)
Definition at line 1168 of file v8-debugger.cc.
                                                                       {
  if (!m_maxAsyncCallStackDepth || m_currentExternalParent.empty()) return;
  m_currentExternalParent.pop_back();
  m_currentAsyncParent.pop_back();
  DCHECK(m_currentTasks.back() == reinterpret_cast<void*>(parent.id));
  m_currentTasks.pop_back();
  if (!parent.should_pause) return;
  m_externalAsyncTaskPauseRequested = false;
  if (hasScheduledBreakOnNextFunctionCall()) return;
  v8::debug::ClearBreakOnNextFunctionCall(m_isolate);
}
References v8::debug::ClearBreakOnNextFunctionCall(), DCHECK, hasScheduledBreakOnNextFunctionCall(), v8_inspector::V8StackTraceId::id, m_currentAsyncParent, m_currentExternalParent, m_currentTasks, m_externalAsyncTaskPauseRequested, m_isolate, m_maxAsyncCallStackDepth, and v8_inspector::V8StackTraceId::should_pause.
externalAsyncTaskStarted()
void v8_inspector::V8Debugger::externalAsyncTaskStarted (const V8StackTraceId & parent)
Definition at line 1154 of file v8-debugger.cc.
                                                                      {
  if (!m_maxAsyncCallStackDepth || parent.IsInvalid()) return;
  m_currentExternalParent.push_back(parent);
  m_currentAsyncParent.emplace_back();
  m_currentTasks.push_back(reinterpret_cast<void*>(parent.id));
  if (!parent.should_pause) return;
  bool didHaveBreak = hasScheduledBreakOnNextFunctionCall();
  m_externalAsyncTaskPauseRequested = true;
  if (didHaveBreak) return;
  m_targetContextGroupId = currentContextGroupId();
  v8::debug::SetBreakOnNextFunctionCall(m_isolate);
}
References currentContextGroupId(), hasScheduledBreakOnNextFunctionCall(), v8_inspector::V8StackTraceId::id, v8_inspector::V8StackTraceId::IsInvalid(), m_currentAsyncParent, m_currentExternalParent, m_currentTasks, m_externalAsyncTaskPauseRequested, m_isolate, m_maxAsyncCallStackDepth, m_targetContextGroupId, v8::debug::SetBreakOnNextFunctionCall(), and v8_inspector::V8StackTraceId::should_pause.
functionScopes()
v8::MaybeLocal< v8::Value > v8_inspector::V8Debugger::functionScopes (v8::Local< v8::Context > context, v8::Local< v8::Function > function) [private]
Definition at line 878 of file v8-debugger.cc.
                                                              {
  return getTargetScopes(context, function, FUNCTION);
}
References FUNCTION, and getTargetScopes().
Referenced by internalProperties().
generatorScopes()
v8::MaybeLocal< v8::Value > v8_inspector::V8Debugger::generatorScopes (v8::Local< v8::Context > context, v8::Local< v8::Value > generator) [private]
Definition at line 883 of file v8-debugger.cc.
                                                            {
  return getTargetScopes(context, generator, GENERATOR);
}
References GENERATOR, and getTargetScopes().
Referenced by internalProperties().
getCompiledScripts()
std::vector< std::unique_ptr< V8DebuggerScript > > v8_inspector::V8Debugger::getCompiledScripts (int contextGroupId, V8DebuggerAgentImpl * agent)
Definition at line 165 of file v8-debugger.cc.
                                                    {
  std::vector<std::unique_ptr<V8DebuggerScript>> result;
  v8::HandleScope scope(m_isolate);
  std::vector<v8::Global<v8::debug::Script>> scripts;
  v8::debug::GetLoadedScripts(m_isolate, scripts);
  for (size_t i = 0; i < scripts.size(); ++i) {
    v8::Local<v8::debug::Script> script = scripts[i].Get(m_isolate);
    if (!script->WasCompiled()) continue;
    if (!script->IsEmbedded()) {
      int contextId;
      if (!script->ContextId().To(&contextId)) continue;
      if (m_inspector->contextGroupId(contextId) != contextGroupId) continue;
    }
    result.push_back(std::make_unique<V8DebuggerScript>(
        m_isolate, script, false, agent, m_inspector->client()));
  }
  return result;
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorImpl::contextGroupId(), v8::debug::GetLoadedScripts(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, m_inspector, m_isolate, v8::base::internal::result, and v8::internal::script.
Referenced by v8_inspector::V8DebuggerAgentImpl::enableImpl().
getPauseOnExceptionsState()
v8::debug::ExceptionBreakState v8_inspector::V8Debugger::getPauseOnExceptionsState ()
Definition at line 198 of file v8-debugger.cc.
                                                                 {
  DCHECK(enabled());
  return m_pauseOnExceptionsState;
}
References DCHECK, enabled(), and m_pauseOnExceptionsState.
getTargetScopes()
v8::MaybeLocal< v8::Value > v8_inspector::V8Debugger::getTargetScopes (v8::Local< v8::Context > context, v8::Local< v8::Value > value, ScopeTargetKind kind) [private]
Definition at line 801 of file v8-debugger.cc.
                          {
  std::unique_ptr<v8::debug::ScopeIterator> iterator;
  switch (kind) {
    case FUNCTION:
      iterator = v8::debug::ScopeIterator::CreateForFunction(
          m_isolate, value.As<v8::Function>());
      break;
    case GENERATOR:
      v8::Local<v8::debug::GeneratorObject> generatorObject =
          v8::debug::GeneratorObject::Cast(value);
      if (!generatorObject->IsSuspended()) return v8::MaybeLocal<v8::Value>();
      iterator = v8::debug::ScopeIterator::CreateForGeneratorObject(
          m_isolate, value.As<v8::Object>());
      break;
  }
  if (!iterator) return v8::MaybeLocal<v8::Value>();
  v8::Local<v8::Array> result = v8::Array::New(m_isolate);
  if (!result->SetPrototypeV2(context, v8::Null(m_isolate)).FromMaybe(false)) {
    return v8::MaybeLocal<v8::Value>();
  }
  for (; !iterator->Done(); iterator->Advance()) {
    v8::Local<v8::Object> scope = v8::Object::New(m_isolate);
    if (!addInternalObject(context, scope, V8InternalValueType::kScope))
      return v8::MaybeLocal<v8::Value>();
    String16 nameSuffix = toProtocolStringWithTypeCheck(
        m_isolate, iterator->GetFunctionDebugName());
    String16 description;
    if (nameSuffix.length()) nameSuffix = " (" + nameSuffix + ")";
    switch (iterator->GetType()) {
      case v8::debug::ScopeIterator::ScopeTypeGlobal:
        description = "Global" + nameSuffix;
        break;
      case v8::debug::ScopeIterator::ScopeTypeLocal:
        description = "Local" + nameSuffix;
        break;
      case v8::debug::ScopeIterator::ScopeTypeWith:
        description = "With Block" + nameSuffix;
        break;
      case v8::debug::ScopeIterator::ScopeTypeClosure:
        description = "Closure" + nameSuffix;
        break;
      case v8::debug::ScopeIterator::ScopeTypeCatch:
        description = "Catch" + nameSuffix;
        break;
      case v8::debug::ScopeIterator::ScopeTypeBlock:
        description = "Block" + nameSuffix;
        break;
      case v8::debug::ScopeIterator::ScopeTypeScript:
        description = "Script" + nameSuffix;
        break;
      case v8::debug::ScopeIterator::ScopeTypeEval:
        description = "Eval" + nameSuffix;
        break;
      case v8::debug::ScopeIterator::ScopeTypeModule:
        description = "Module" + nameSuffix;
        break;
      case v8::debug::ScopeIterator::ScopeTypeWasmExpressionStack:
        description = "Wasm Expression Stack" + nameSuffix;
        break;
    }
    v8::Local<v8::Object> object = iterator->GetObject();
    createDataProperty(context, scope,
                       toV8StringInternalized(m_isolate, "description"),
                       toV8String(m_isolate, description));
    createDataProperty(context, scope,
                       toV8StringInternalized(m_isolate, "object"), object);
    createDataProperty(context, result, result->Length(), scope);
  }
  if (!addInternalObject(context, result, V8InternalValueType::kScopeList))
    return v8::MaybeLocal<v8::Value>();
  return result;
}
References addInternalObject(), v8::debug::GeneratorObject::Cast(), v8_inspector::createDataProperty(), v8::debug::ScopeIterator::CreateForFunction(), v8::debug::ScopeIterator::CreateForGeneratorObject(), FUNCTION, GENERATOR, v8_inspector::kScope, v8_inspector::kScopeList, v8_inspector::String16::length(), m_isolate, v8::Object::New(), v8::Array::New(), v8::Null(), v8::base::internal::result, v8::debug::ScopeIterator::ScopeTypeBlock, v8::debug::ScopeIterator::ScopeTypeCatch, v8::debug::ScopeIterator::ScopeTypeClosure, v8::debug::ScopeIterator::ScopeTypeEval, v8::debug::ScopeIterator::ScopeTypeGlobal, v8::debug::ScopeIterator::ScopeTypeLocal, v8::debug::ScopeIterator::ScopeTypeModule, v8::debug::ScopeIterator::ScopeTypeScript, v8::debug::ScopeIterator::ScopeTypeWasmExpressionStack, v8::debug::ScopeIterator::ScopeTypeWith, v8_inspector::toProtocolStringWithTypeCheck(), v8_inspector::toV8String(), v8_inspector::toV8StringInternalized(), and v8::internal::value.
Referenced by functionScopes(), and generatorScopes().
handleProgramBreak()
void v8_inspector::V8Debugger::handleProgramBreak (v8::Local< v8::Context > pausedContext, v8::Local< v8::Value > exception, const std::vector< v8::debug::BreakpointId > & hitBreakpoints, v8::debug::BreakReasons break_reasons, v8::debug::ExceptionType exception_type = v8::debug::kException, bool isUncaught = false) [private]
Definition at line 479 of file v8-debugger.cc.
                                                         {
  // Don't allow nested breaks.
  if (isPaused()) return;
  int contextGroupId = m_inspector->contextGroupId(pausedContext);
  if (m_targetContextGroupId && contextGroupId != m_targetContextGroupId) {
    v8::debug::PrepareStep(m_isolate, v8::debug::StepOut);
    return;
  }
  DCHECK(hasScheduledBreakOnNextFunctionCall() ==
         (m_taskWithScheduledBreakPauseRequested ||
          m_externalAsyncTaskPauseRequested || m_pauseOnNextCallRequested));
  if (m_taskWithScheduledBreakPauseRequested ||
      m_externalAsyncTaskPauseRequested)
    breakReasons.Add(v8::debug::BreakReason::kAsyncStep);
  if (m_pauseOnNextCallRequested)
    breakReasons.Add(v8::debug::BreakReason::kAgent);
  m_targetContextGroupId = 0;
  m_pauseOnNextCallRequested = false;
  m_pauseOnAsyncCall = false;
  m_taskWithScheduledBreak = nullptr;
  m_externalAsyncTaskPauseRequested = false;
  m_taskWithScheduledBreakPauseRequested = false;
  bool scheduledOOMBreak = m_scheduledOOMBreak;
  DCHECK(scheduledOOMBreak ==
         breakReasons.contains(v8::debug::BreakReason::kOOM));
  bool hasAgents = false;
  m_inspector->forEachSession(
      contextGroupId,
      [&scheduledOOMBreak, &hasAgents](V8InspectorSessionImpl* session) {
        if (session->debuggerAgent()->acceptsPause(scheduledOOMBreak))
          hasAgents = true;
      });
  if (!hasAgents) return;
  if (breakpointIds.size() == 1 &&
      breakpointIds[0] == m_continueToLocationBreakpointId) {
    v8::Context::Scope contextScope(pausedContext);
    if (!shouldContinueToCurrentLocation()) return;
  }
  clearContinueToLocation();
  DCHECK(contextGroupId);
  m_pausedContextGroupId = contextGroupId;
  m_inspector->forEachSession(
      contextGroupId,
      [&pausedContext, &exception, &breakpointIds, &exceptionType, &isUncaught,
       &scheduledOOMBreak, &breakReasons](V8InspectorSessionImpl* session) {
        if (session->debuggerAgent()->acceptsPause(scheduledOOMBreak)) {
          session->debuggerAgent()->didPause(
              InspectedContext::contextId(pausedContext), exception,
              breakpointIds, exceptionType, isUncaught, breakReasons);
        }
      });
  {
    v8::Context::Scope scope(pausedContext);
    m_inspector->forEachSession(
        contextGroupId, [](V8InspectorSessionImpl* session) {
          if (session->heapProfilerAgent()) {
            session->heapProfilerAgent()->takePendingHeapSnapshots();
          }
        });
    m_inspector->client()->runMessageLoopOnPause(contextGroupId);
    m_pausedContextGroupId = 0;
  }
  m_inspector->forEachSession(contextGroupId,
                              [](V8InspectorSessionImpl* session) {
                                if (session->debuggerAgent()->enabled()) {
                                  session->debuggerAgent()->clearBreakDetails();
                                  session->debuggerAgent()->didContinue();
                                }
                              });
  if (m_scheduledOOMBreak) m_isolate->RestoreOriginalHeapLimit();
  m_scheduledOOMBreak = false;
}
References v8_inspector::V8DebuggerAgentImpl::acceptsPause(), v8::base::EnumSet< E, T >::Add(), clearContinueToLocation(), v8_inspector::V8InspectorImpl::client(), v8::base::EnumSet< E, T >::contains(), v8_inspector::V8InspectorImpl::contextGroupId(), DCHECK, v8_inspector::V8InspectorSessionImpl::debuggerAgent(), v8_inspector::V8DebuggerAgentImpl::enabled(), v8_inspector::V8InspectorImpl::forEachSession(), hasScheduledBreakOnNextFunctionCall(), v8_inspector::V8InspectorSessionImpl::heapProfilerAgent(), isPaused(), v8::debug::kAgent, v8::debug::kAsyncStep, v8::debug::kOOM, m_continueToLocationBreakpointId, m_externalAsyncTaskPauseRequested, m_inspector, m_isolate, m_pausedContextGroupId, m_pauseOnAsyncCall, m_pauseOnNextCallRequested, m_scheduledOOMBreak, m_targetContextGroupId, m_taskWithScheduledBreak, m_taskWithScheduledBreakPauseRequested, v8::debug::PrepareStep(), v8::Isolate::RestoreOriginalHeapLimit(), v8_inspector::V8InspectorClient::runMessageLoopOnPause(), shouldContinueToCurrentLocation(), and v8::debug::StepOut.
Referenced by BreakProgramRequested(), and ExceptionThrown().
hasScheduledBreakOnNextFunctionCall()
bool v8_inspector::V8Debugger::hasScheduledBreakOnNextFunctionCall () const [private]
Definition at line 1475 of file v8-debugger.cc.
                                                           {
  return m_pauseOnNextCallRequested || m_taskWithScheduledBreakPauseRequested ||
         m_externalAsyncTaskPauseRequested;
}
References m_externalAsyncTaskPauseRequested, m_pauseOnNextCallRequested, and m_taskWithScheduledBreakPauseRequested.
Referenced by asyncTaskFinishedForStepping(), asyncTaskStartedForStepping(), externalAsyncTaskFinished(), externalAsyncTaskStarted(), handleProgramBreak(), and setPauseOnNextCall().
inspector()
V8InspectorImpl* v8_inspector::V8Debugger::inspector () [inline]
Definition at line 138 of file v8-debugger.h.
{ return m_inspector; }
References m_inspector.
Referenced by v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::buildInspectorObjectCommon(), and terminateExecutionCompletedCallback().
installTerminateExecutionCallbacks()
void v8_inspector::V8Debugger::installTerminateExecutionCallbacks (v8::Local< v8::Context > context) [private]
Definition at line 357 of file v8-debugger.cc.
                                {
  m_isolate->AddCallCompletedCallback(
      &V8Debugger::terminateExecutionCompletedCallback);
  if (!context.IsEmpty()) {
    m_terminateExecutionCallbackContext.Reset(m_isolate, context);
    m_terminateExecutionCallbackContext.SetWeak();
    v8::MicrotaskQueue* microtask_queue = context->GetMicrotaskQueue();
    microtask_queue->AddMicrotasksCompletedCallback(
        &V8Debugger::terminateExecutionCompletedCallbackIgnoringData,
        microtask_queue);
  }
  DCHECK(m_terminateExecutionReported);
  m_terminateExecutionReported = false;
}
References v8::Isolate::AddCallCompletedCallback(), v8::MicrotaskQueue::AddMicrotasksCompletedCallback(), DCHECK, v8::Context::GetMicrotaskQueue(), v8::api_internal::IndirectHandleBase::IsEmpty(), m_isolate, m_terminateExecutionCallbackContext, m_terminateExecutionReported, v8::PersistentBase< T >::Reset(), v8::PersistentBase< T >::SetWeak(), terminateExecutionCompletedCallback(), and terminateExecutionCompletedCallbackIgnoringData().
Referenced by continueProgram(), and terminateExecution().
internalProperties()
v8::MaybeLocal< v8::Array > v8_inspector::V8Debugger::internalProperties (v8::Local< v8::Context > context, v8::Local< v8::Value > value)
Definition at line 969 of file v8-debugger.cc.
                                                        {
  v8::Local<v8::Array> properties;
  if (!v8::debug::GetInternalProperties(m_isolate, value).ToLocal(&properties))
    return v8::MaybeLocal<v8::Array>();
  v8::Local<v8::Array> entries;
  if (collectionsEntries(context, value).ToLocal(&entries)) {
    createDataProperty(context, properties, properties->Length(),
                       toV8StringInternalized(m_isolate, "[[Entries]]"));
    createDataProperty(context, properties, properties->Length(), entries);
  }
  if (value->IsGeneratorObject()) {
    v8::Local<v8::Value> scopes;
    if (generatorScopes(context, value).ToLocal(&scopes)) {
      createDataProperty(context, properties, properties->Length(),
                         toV8StringInternalized(m_isolate, "[[Scopes]]"));
      createDataProperty(context, properties, properties->Length(), scopes);
    }
  }
  if (value->IsFunction()) {
    v8::Local<v8::Function> function = value.As<v8::Function>();
    v8::Local<v8::Value> scopes;
    if (functionScopes(context, function).ToLocal(&scopes)) {
      createDataProperty(context, properties, properties->Length(),
                         toV8StringInternalized(m_isolate, "[[Scopes]]"));
      createDataProperty(context, properties, properties->Length(), scopes);
    }
  }
  v8::Local<v8::Array> private_methods;
  if (privateMethods(context, value).ToLocal(&private_methods)) {
    createDataProperty(context, properties, properties->Length(),
                       toV8StringInternalized(m_isolate, "[[PrivateMethods]]"));
    createDataProperty(context, properties, properties->Length(),
                       private_methods);
  }
  return properties;
}
References collectionsEntries(), v8_inspector::createDataProperty(), functionScopes(), generatorScopes(), v8::debug::GetInternalProperties(), v8::Array::Length(), m_isolate, privateMethods(), v8::MaybeLocal< T >::ToLocal(), v8_inspector::toV8StringInternalized(), and v8::internal::value.
Referenced by v8_inspector::ValueMirror::getInternalProperties().
interruptAndBreak()
void v8_inspector::V8Debugger::interruptAndBreak (int targetContextGroupId)
Definition at line 250 of file v8-debugger.cc.
                                                           {
  // Don't allow nested breaks.
  if (isPaused()) return;
  DCHECK(targetContextGroupId);
  m_targetContextGroupId = targetContextGroupId;
  m_isolate->RequestInterrupt(
      [](v8::Isolate* isolate, void*) {
        v8::debug::BreakRightNow(
            isolate,
            v8::debug::BreakReasons({v8::debug::BreakReason::kScheduled}));
      },
      nullptr);
}
References v8::debug::BreakRightNow(), DCHECK, isolate(), isPaused(), v8::debug::kScheduled, m_isolate, m_targetContextGroupId, and v8::Isolate::RequestInterrupt().
Referenced by v8_inspector::V8DebuggerAgentImpl::pause().
IsFunctionBlackboxed()
bool v8_inspector::V8Debugger::IsFunctionBlackboxed (v8::Local< v8::debug::Script > script, const v8::debug::Location & start, const v8::debug::Location & end) [override], [private], [virtual]
Reimplemented from v8::debug::DebugDelegate.
Definition at line 693 of file v8-debugger.cc.
                                                                  {
  int contextId;
  if (!script->ContextId().To(&contextId)) return false;
  bool hasAgents = false;
  bool allBlackboxed = true;
  String16 scriptId = String16::fromInteger(script->Id());
  m_inspector->forEachSession(
      m_inspector->contextGroupId(contextId),
      [&hasAgents, &allBlackboxed, &scriptId, &start,
       &end](V8InspectorSessionImpl* session) {
        V8DebuggerAgentImpl* agent = session->debuggerAgent();
        if (!agent->enabled()) return;
        hasAgents = true;
        allBlackboxed &= agent->isFunctionBlackboxed(scriptId, start, end);
      });
  return hasAgents && allBlackboxed;
}
References v8_inspector::V8InspectorImpl::contextGroupId(), v8::internal::compiler::end(), v8_inspector::V8InspectorImpl::forEachSession(), v8_inspector::String16::fromInteger(), m_inspector, and v8::internal::script.
isInInstrumentationPause()
bool v8_inspector::V8Debugger::isInInstrumentationPause () const
Definition at line 237 of file v8-debugger.cc.
                                                {
  return m_instrumentationPause;
}
References m_instrumentationPause.
Referenced by v8_inspector::V8DebuggerAgentImpl::pause().
isolate()
v8::Isolate* v8_inspector::V8Debugger::isolate () const [inline]
Definition at line 60 of file v8-debugger.h.
{ return m_isolate; }
References m_isolate.
Referenced by asyncTaskCanceledForStack(), asyncTaskScheduledForStack(), asyncTaskStartedForStack(), BreakpointConditionEvaluated(), v8_inspector::AsyncStackTrace::capture(), v8_inspector::V8StackTraceImpl::capture(), collectionsEntries(), v8_inspector::V8StackTraceImpl::create(), v8_inspector::V8DebuggerAgentImpl::didPause(), interruptAndBreak(), nearHeapLimitCallback(), privateMethods(), queryObjects(), ScriptCompiled(), symbolize(), terminateExecutionCompletedCallback(), terminateExecutionCompletedCallbackIgnoringData(), and v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::toFramesVector().
isPaused()
bool v8_inspector::V8Debugger::isPaused () const [inline]
Definition at line 99 of file v8-debugger.h.
{ return m_pausedContextGroupId; }
References m_pausedContextGroupId.
Referenced by BreakOnInstrumentation(), breakProgram(), breakProgramOnAssert(), continueProgram(), continueToLocation(), disable(), handleProgramBreak(), interruptAndBreak(), isPausedInContextGroup(), restartFrame(), setPauseOnNextCall(), stepIntoStatement(), stepOutOfFunction(), stepOverStatement(), and v8_inspector::V8HeapProfilerAgentImpl::takeHeapSnapshot().
isPausedInContextGroup()
bool v8_inspector::V8Debugger::isPausedInContextGroup (int contextGroupId) const
Definition at line 159 of file v8-debugger.cc.
                                                                {
  return isPaused() && m_pausedContextGroupId == contextGroupId;
}
References isPaused(), and m_pausedContextGroupId.
Referenced by v8_inspector::V8DebuggerAgentImpl::isPaused().
maxAsyncCallChainDepth()
int v8_inspector::V8Debugger::maxAsyncCallChainDepth () [inline]
Definition at line 102 of file v8-debugger.h.
{ return m_maxAsyncCallStackDepth; }
References m_maxAsyncCallStackDepth.
Referenced by v8_inspector::V8StackTraceImpl::create(), v8_inspector::V8DebuggerAgentImpl::currentAsyncStackTrace(), and v8_inspector::V8DebuggerAgentImpl::getStackTrace().
maxCallStackSizeToCapture()
int v8_inspector::V8Debugger::maxCallStackSizeToCapture () const [inline]
Definition at line 105 of file v8-debugger.h.
{ return m_maxCallStackSizeToCapture; }
References m_maxCallStackSizeToCapture.
Referenced by v8_inspector::AsyncStackTrace::capture(), and captureStackTrace().
muteScriptParsedEvents()
void v8_inspector::V8Debugger::muteScriptParsedEvents ()
Definition at line 1355 of file v8-debugger.cc.
                                        {
  ++m_ignoreScriptParsedEventsCounter;
}
References m_ignoreScriptParsedEventsCounter.
Referenced by v8_inspector::V8RuntimeAgentImpl::compileScript().
nearHeapLimitCallback()
size_t v8_inspector::V8Debugger::nearHeapLimitCallback (void * data, size_t current_heap_limit, size_t initial_heap_limit) [static], [private]
Definition at line 577 of file v8-debugger.cc.
                                                                    {
  V8Debugger* thisPtr = static_cast<V8Debugger*>(data);
  thisPtr->m_originalHeapLimit = current_heap_limit;
  thisPtr->m_scheduledOOMBreak = true;
  v8::Local<v8::Context> context =
      thisPtr->m_isolate->GetEnteredOrMicrotaskContext();
  thisPtr->m_targetContextGroupId =
      context.IsEmpty() ? 0 : thisPtr->m_inspector->contextGroupId(context);
  thisPtr->m_isolate->RequestInterrupt(
      [](v8::Isolate* isolate, void*) {
        // There's a redundancy between setting `m_scheduledOOMBreak` and
        // passing the reason along in `BreakRightNow`. The
        // `m_scheduledOOMBreak` is used elsewhere, so we cannot remove it. And
        // for being explicit, we still pass the break reason along.
        v8::debug::BreakRightNow(
            isolate, v8::debug::BreakReasons({v8::debug::BreakReason::kOOM}));
      },
      nullptr);
  return HeapLimitForDebugging(initial_heap_limit);
}
References v8::debug::BreakRightNow(), v8_inspector::V8InspectorImpl::contextGroupId(), v8::Isolate::GetEnteredOrMicrotaskContext(), v8_inspector::anonymous_namespace{v8-debugger.cc}::HeapLimitForDebugging(), v8::api_internal::IndirectHandleBase::IsEmpty(), isolate(), v8::debug::kOOM, m_inspector, m_isolate, m_originalHeapLimit, m_scheduledOOMBreak, m_targetContextGroupId, and v8::Isolate::RequestInterrupt().
Referenced by disable(), and enable().
operator=()
V8Debugger& v8_inspector::V8Debugger::operator= (const V8Debugger &) [delete]
privateMethods()
v8::MaybeLocal< v8::Array > v8_inspector::V8Debugger::privateMethods (v8::Local< v8::Context > context, v8::Local< v8::Value > value) [private]
Definition at line 927 of file v8-debugger.cc.
                                                           {
  if (!receiver->IsObject()) {
    return v8::MaybeLocal<v8::Array>();
  }
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::LocalVector<v8::Value> names(isolate);
  v8::LocalVector<v8::Value> values(isolate);
  int filter =
      static_cast<int>(v8::debug::PrivateMemberFilter::kPrivateMethods);
  if (!v8::debug::GetPrivateMembers(context, receiver.As<v8::Object>(), filter,
                                    &names, &values) ||
      names.empty()) {
    return v8::MaybeLocal<v8::Array>();
  }
  v8::Local<v8::Array> result = v8::Array::New(isolate);
  if (!result->SetPrototypeV2(context, v8::Null(isolate)).FromMaybe(false))
    return v8::MaybeLocal<v8::Array>();
  for (uint32_t i = 0; i < names.size(); i++) {
    v8::Local<v8::Value> name = names[i];
    v8::Local<v8::Value> value = values[i];
    DCHECK(value->IsFunction());
    v8::Local<v8::Object> wrapper = v8::Object::New(isolate);
    if (!wrapper->SetPrototypeV2(context, v8::Null(isolate)).FromMaybe(false))
      continue;
    createDataProperty(context, wrapper,
                       toV8StringInternalized(isolate, "name"), name);
    createDataProperty(context, wrapper,
                       toV8StringInternalized(isolate, "value"), value);
    if (!addInternalObject(context, wrapper,
                           V8InternalValueType::kPrivateMethod))
      continue;
    createDataProperty(context, result, result->Length(), wrapper);
  }
  if (!addInternalObject(context, result,
                         V8InternalValueType::kPrivateMethodList))
    return v8::MaybeLocal<v8::Array>();
  return result;
}
References addInternalObject(), v8::Local< T >::As(), v8_inspector::createDataProperty(), DCHECK, v8::LocalVector< T >::empty(), v8::Isolate::GetCurrent(), v8::debug::GetPrivateMembers(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::Value::IsObject(), isolate(), v8_inspector::kPrivateMethod, v8_inspector::kPrivateMethodList, v8::debug::kPrivateMethods, name, v8::Object::New(), v8::Array::New(), v8::Null(), v8::base::internal::result, v8::Object::SetPrototypeV2(), v8::LocalVector< T >::size(), v8_inspector::toV8StringInternalized(), and v8::internal::value.
Referenced by internalProperties().
queryObjects()
v8::Local< v8::Array > v8_inspector::V8Debugger::queryObjects (v8::Local< v8::Context > context, v8::Local< v8::Object > prototype)
Definition at line 1008 of file v8-debugger.cc.
                                                                           {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  std::vector<v8::Global<v8::Object>> v8_objects;
  MatchPrototypePredicate predicate(m_inspector, context, prototype);
  isolate->GetHeapProfiler()->QueryObjects(context, &predicate, &v8_objects);
  v8::MicrotasksScope microtasksScope(context,
                                      v8::MicrotasksScope::kDoNotRunMicrotasks);
  v8::Local<v8::Array> resultArray = v8::Array::New(
      m_inspector->isolate(), static_cast<int>(v8_objects.size()));
  for (size_t i = 0; i < v8_objects.size(); ++i) {
    createDataProperty(context, resultArray, static_cast<int>(i),
                       v8_objects[i].Get(isolate));
  }
  return resultArray;
}
References v8_inspector::createDataProperty(), v8::internal::compiler::turboshaft::Get(), v8::Isolate::GetCurrent(), v8::Isolate::GetHeapProfiler(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate(), v8_inspector::V8InspectorImpl::isolate(), v8::MicrotasksScope::kDoNotRunMicrotasks, m_inspector, v8::Array::New(), v8::internal::prototype, and v8::HeapProfiler::QueryObjects().
Referenced by v8_inspector::V8RuntimeAgentImpl::queryObjects().
quitMessageLoopIfAgentsFinishedInstrumentation()
void v8_inspector::V8Debugger::quitMessageLoopIfAgentsFinishedInstrumentation () [private]
Definition at line 268 of file v8-debugger.cc.
                                                                {
  bool allAgentsFinishedInstrumentation = true;
  m_inspector->forEachSession(
      m_pausedContextGroupId,
      [&allAgentsFinishedInstrumentation](V8InspectorSessionImpl* session) {
        if (!session->debuggerAgent()->instrumentationFinished()) {
          allAgentsFinishedInstrumentation = false;
        }
      });
  if (allAgentsFinishedInstrumentation) {
    m_inspector->client()->quitMessageLoopOnPause();
  }
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorSessionImpl::debuggerAgent(), v8_inspector::V8InspectorImpl::forEachSession(), v8_inspector::V8DebuggerAgentImpl::instrumentationFinished(), m_inspector, m_pausedContextGroupId, and v8_inspector::V8InspectorClient::quitMessageLoopOnPause().
Referenced by continueProgram(), and disable().
removeBreakpoint()
void v8_inspector::V8Debugger::removeBreakpoint (v8::debug::BreakpointId id)
Definition at line 194 of file v8-debugger.cc.
                                                        {
  v8::debug::RemoveBreakpoint(m_isolate, id);
}
References m_isolate, and v8::debug::RemoveBreakpoint().
Referenced by v8_inspector::V8DebuggerAgentImpl::disable(), and v8_inspector::V8DebuggerAgentImpl::removeBreakpointImpl().
reportTermination()
void v8_inspector::V8Debugger::reportTermination ()
Definition at line 375 of file v8-debugger.cc.
                                   {
  if (m_terminateExecutionReported) {
    DCHECK(m_terminateExecutionCallbackContext.IsEmpty());
    return;
  }
  v8::HandleScope handles(m_isolate);
  m_isolate->RemoveCallCompletedCallback(
      &V8Debugger::terminateExecutionCompletedCallback);
  if (!m_terminateExecutionCallbackContext.IsEmpty()) {
    v8::MicrotaskQueue* microtask_queue =
        m_terminateExecutionCallbackContext.Get(m_isolate)->GetMicrotaskQueue();
    if (microtask_queue) {
      microtask_queue->RemoveMicrotasksCompletedCallback(
          &V8Debugger::terminateExecutionCompletedCallbackIgnoringData,
          microtask_queue);
    }
  }
  m_isolate->CancelTerminateExecution();
  if (m_terminateExecutionCallback) {
    m_terminateExecutionCallback->sendSuccess();
    m_terminateExecutionCallback.reset();
  }
  m_terminateExecutionCallbackContext.Reset();
  m_terminateExecutionReported = true;
}
References v8::Isolate::CancelTerminateExecution(), DCHECK, v8::PersistentBase< T >::Get(), v8::api_internal::IndirectHandleBase::IsEmpty(), m_isolate, m_terminateExecutionCallback, m_terminateExecutionCallbackContext, m_terminateExecutionReported, v8::Isolate::RemoveCallCompletedCallback(), v8::MicrotaskQueue::RemoveMicrotasksCompletedCallback(), v8::PersistentBase< T >::Reset(), terminateExecutionCompletedCallback(), and terminateExecutionCompletedCallbackIgnoringData().
Referenced by terminateExecutionCompletedCallback().
requestPauseAfterInstrumentation()
void v8_inspector::V8Debugger::requestPauseAfterInstrumentation ()
Definition at line 264 of file v8-debugger.cc.
                                                  {
  m_requestedPauseAfterInstrumentation = true;
}
References m_requestedPauseAfterInstrumentation.
Referenced by v8_inspector::V8DebuggerAgentImpl::pause().
restartFrame()
bool v8_inspector::V8Debugger::restartFrame (int targetContextGroupId, int callFrameOrdinal)
Definition at line 444 of file v8-debugger.cc.
                                                                            {
  DCHECK(isPaused());
  DCHECK(targetContextGroupId);
  m_targetContextGroupId = targetContextGroupId;
  if (v8::debug::PrepareRestartFrame(m_isolate, callFrameOrdinal)) {
    continueProgram(targetContextGroupId);
    return true;
  }
  return false;
}
References continueProgram(), DCHECK, isPaused(), m_isolate, m_targetContextGroupId, and v8::debug::PrepareRestartFrame().
Referenced by v8_inspector::V8DebuggerAgentImpl::restartFrame(), and v8_inspector::V8DebuggerAgentImpl::setScriptSource().
ScriptCompiled()
void v8_inspector::V8Debugger::ScriptCompiled (v8::Local< v8::debug::Script > script, bool is_live_edited, bool has_compile_error) [override], [private], [virtual]
Reimplemented from v8::debug::DebugDelegate.
Definition at line 599 of file v8-debugger.cc.
                                                                             {
  if (m_ignoreScriptParsedEventsCounter != 0) return;
  int contextId;
  if (!script->ContextId().To(&contextId)) return;
  v8::Isolate* isolate = m_isolate;
  V8InspectorClient* client = m_inspector->client();
  m_inspector->forEachSession(
      m_inspector->contextGroupId(contextId),
      [isolate, &script, has_compile_error, is_live_edited,
       client](V8InspectorSessionImpl* session) {
        auto agent = session->debuggerAgent();
        if (!agent->enabled()) return;
        agent->didParseSource(
            std::make_unique<V8DebuggerScript>(isolate, script, is_live_edited,
                                               agent, client),
            !has_compile_error);
      });
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorImpl::contextGroupId(), v8_inspector::V8InspectorImpl::forEachSession(), isolate(), m_ignoreScriptParsedEventsCounter, m_inspector, m_isolate, and v8::internal::script.
setAsyncCallStackDepth()
void v8_inspector::V8Debugger::setAsyncCallStackDepth (V8DebuggerAgentImpl * agent, int depth)
Definition at line 1032 of file v8-debugger.cc.
                                                                             {
  if (depth <= 0)
    m_maxAsyncCallStackDepthMap.erase(agent);
  else
    m_maxAsyncCallStackDepthMap[agent] = depth;
  int maxAsyncCallStackDepth = 0;
  for (const auto& pair : m_maxAsyncCallStackDepthMap) {
    if (pair.second > maxAsyncCallStackDepth)
      maxAsyncCallStackDepth = pair.second;
  }
  if (m_maxAsyncCallStackDepth == maxAsyncCallStackDepth) return;
  // TODO(dgozman): ideally, this should be per context group.
  m_maxAsyncCallStackDepth = maxAsyncCallStackDepth;
  m_inspector->client()->maxAsyncCallStackDepthChanged(
      m_maxAsyncCallStackDepth);
  if (!maxAsyncCallStackDepth) allAsyncTasksCanceled();
  v8::debug::SetAsyncEventDelegate(m_isolate,
                                   maxAsyncCallStackDepth ? this : nullptr);
}
References allAsyncTasksCanceled(), v8_inspector::V8InspectorImpl::client(), m_inspector, m_isolate, m_maxAsyncCallStackDepth, m_maxAsyncCallStackDepthMap, v8_inspector::V8InspectorClient::maxAsyncCallStackDepthChanged(), and v8::debug::SetAsyncEventDelegate().
Referenced by v8_inspector::V8DebuggerAgentImpl::disable(), v8_inspector::V8DebuggerAgentImpl::restore(), and v8_inspector::V8DebuggerAgentImpl::setAsyncCallStackDepth().
setBreakpointsActive()
void v8_inspector::V8Debugger::setBreakpointsActive (bool active)
Definition at line 185 of file v8-debugger.cc.
                                                 {
  if (!enabled()) {
    UNREACHABLE();
  }
  m_breakpointsActiveCount += active ? 1 : -1;
  DCHECK_GE(m_breakpointsActiveCount, 0);
  v8::debug::SetBreakPointsActive(m_isolate, m_breakpointsActiveCount);
}
References DCHECK_GE, enabled(), m_breakpointsActiveCount, m_isolate, v8::debug::SetBreakPointsActive(), and UNREACHABLE.
Referenced by v8_inspector::V8DebuggerAgentImpl::disable(), v8_inspector::V8DebuggerAgentImpl::enableImpl(), and v8_inspector::V8DebuggerAgentImpl::setBreakpointsActive().
setMaxAsyncTaskStacksForTest()
void v8_inspector::V8Debugger::setMaxAsyncTaskStacksForTest (int limit)
Definition at line 1443 of file v8-debugger.cc.
                                                       {
  m_maxAsyncCallStacks = 0;
  collectOldAsyncStacksIfNeeded();
  m_maxAsyncCallStacks = limit;
}
References collectOldAsyncStacksIfNeeded(), and m_maxAsyncCallStacks.
setMaxCallStackSizeToCapture()
void v8_inspector::V8Debugger::setMaxCallStackSizeToCapture (V8RuntimeAgentImpl * agent, int size)
Definition at line 1054 of file v8-debugger.cc.
                                                        {
  if (size < 0) {
    m_maxCallStackSizeToCaptureMap.erase(agent);
  } else {
    m_maxCallStackSizeToCaptureMap[agent] = size;
  }
  // The following logic is a bit complicated to decipher because we
  // want to retain backwards compatible semantics:
  //
  // (a) When no `Runtime` domain is enabled, we stick to the default
  // maximum call stack size, but don't let V8 collect stack traces
  // for uncaught exceptions.
  // (b) When `Runtime` is enabled for at least one front-end, we compute
  // the maximum of the requested maximum call stack sizes of all the
  // front-ends whose `Runtime` domains are enabled (which might be 0),
  // and ask V8 to collect stack traces for uncaught exceptions.
  //
  // The latter allows performance test automation infrastructure to drive
  // browser via `Runtime` domain while still minimizing the performance
  // overhead of having the inspector attached - see the relevant design
  // document https://bit.ly/v8-cheaper-inspector-stack-traces for more
  if (m_maxCallStackSizeToCaptureMap.empty()) {
    m_maxCallStackSizeToCapture =
        V8StackTraceImpl::kDefaultMaxCallStackSizeToCapture;
    m_isolate->SetCaptureStackTraceForUncaughtExceptions(false);
  } else {
    m_maxCallStackSizeToCapture = 0;
    for (auto const& pair : m_maxCallStackSizeToCaptureMap) {
      if (m_maxCallStackSizeToCapture < pair.second)
        m_maxCallStackSizeToCapture = pair.second;
    }
    m_isolate->SetCaptureStackTraceForUncaughtExceptions(
        m_maxCallStackSizeToCapture > 0, m_maxCallStackSizeToCapture);
  }
}
References v8_inspector::V8StackTraceImpl::kDefaultMaxCallStackSizeToCapture, m_isolate, m_maxCallStackSizeToCapture, m_maxCallStackSizeToCaptureMap, v8::Isolate::SetCaptureStackTraceForUncaughtExceptions(), and size().
Referenced by v8_inspector::V8RuntimeAgentImpl::disable(), v8_inspector::V8RuntimeAgentImpl::enable(), v8_inspector::V8RuntimeAgentImpl::restore(), and v8_inspector::V8RuntimeAgentImpl::setMaxCallStackSizeToCapture().
setPauseOnExceptionsState()
void v8_inspector::V8Debugger::setPauseOnExceptionsState (v8::debug::ExceptionBreakState pauseOnExceptionsState)
Definition at line 203 of file v8-debugger.cc.
                                                       {
  DCHECK(enabled());
  if (m_pauseOnExceptionsState == pauseOnExceptionsState) return;
  v8::debug::ChangeBreakOnException(m_isolate, pauseOnExceptionsState);
  m_pauseOnExceptionsState = pauseOnExceptionsState;
}
References v8::debug::ChangeBreakOnException(), DCHECK, enabled(), m_isolate, m_pauseOnExceptionsState, and v8_inspector::DebuggerAgentState::pauseOnExceptionsState.
Referenced by v8_inspector::V8DebuggerAgentImpl::setPauseOnExceptionsImpl().
setPauseOnNextCall()
void v8_inspector::V8Debugger::setPauseOnNextCall (bool pause, int targetContextGroupId)
Definition at line 211 of file v8-debugger.cc.
                                                                        {
  if (isPaused()) return;
  DCHECK(targetContextGroupId);
  if (!pause && m_targetContextGroupId &&
      m_targetContextGroupId != targetContextGroupId) {
    return;
  }
  if (pause) {
    bool didHaveBreak = hasScheduledBreakOnNextFunctionCall();
    m_pauseOnNextCallRequested = true;
    if (!didHaveBreak) {
      m_targetContextGroupId = targetContextGroupId;
      v8::debug::SetBreakOnNextFunctionCall(m_isolate);
    }
  } else {
    m_pauseOnNextCallRequested = false;
    if (!hasScheduledBreakOnNextFunctionCall()) {
      v8::debug::ClearBreakOnNextFunctionCall(m_isolate);
    }
  }
}
References v8::debug::ClearBreakOnNextFunctionCall(), DCHECK, hasScheduledBreakOnNextFunctionCall(), isPaused(), m_isolate, m_pauseOnNextCallRequested, m_targetContextGroupId, and v8::debug::SetBreakOnNextFunctionCall().
Referenced by v8_inspector::V8DebuggerAgentImpl::breakProgram(), v8_inspector::V8DebuggerAgentImpl::cancelPauseOnNextStatement(), v8_inspector::V8DebuggerAgentImpl::pause(), v8_inspector::V8DebuggerAgentImpl::schedulePauseOnNextStatement(), and v8_inspector::V8DebuggerAgentImpl::setBreakpointsActive().
ShouldBeSkipped()
bool v8_inspector::V8Debugger::ShouldBeSkipped (v8::Local< v8::debug::Script > script, int line, int column) [override], [private], [virtual]
Reimplemented from v8::debug::DebugDelegate.
Definition at line 713 of file v8-debugger.cc.
                                             {
  int contextId;
  if (!script->ContextId().To(&contextId)) return false;
  bool hasAgents = false;
  bool allShouldBeSkipped = true;
  String16 scriptId = String16::fromInteger(script->Id());
  m_inspector->forEachSession(
      m_inspector->contextGroupId(contextId),
      [&hasAgents, &allShouldBeSkipped, &scriptId, line,
       column](V8InspectorSessionImpl* session) {
        V8DebuggerAgentImpl* agent = session->debuggerAgent();
        if (!agent->enabled()) return;
        hasAgents = true;
        const bool skip = agent->shouldBeSkipped(scriptId, line, column);
        allShouldBeSkipped &= skip;
      });
  return hasAgents && allShouldBeSkipped;
}
References v8_inspector::V8InspectorImpl::contextGroupId(), v8_inspector::V8InspectorImpl::forEachSession(), v8_inspector::String16::fromInteger(), m_inspector, and v8::internal::script.
shouldContinueToCurrentLocation()
bool v8_inspector::V8Debugger::shouldContinueToCurrentLocation () [private]
Definition at line 456 of file v8-debugger.cc.
                                                 {
  if (m_continueToLocationTargetCallFrames ==
      protocol::Debugger::ContinueToLocation::TargetCallFramesEnum::Any) {
    return true;
  }
  std::unique_ptr<V8StackTraceImpl> currentStack = V8StackTraceImpl::capture(
      this, V8StackTraceImpl::kDefaultMaxCallStackSizeToCapture);
  if (m_continueToLocationTargetCallFrames ==
      protocol::Debugger::ContinueToLocation::TargetCallFramesEnum::Current) {
    return m_continueToLocationStack->isEqualIgnoringTopFrame(
        currentStack.get());
  }
  return true;
}
References v8_inspector::V8StackTraceImpl::capture(), v8_inspector::V8StackTraceImpl::kDefaultMaxCallStackSizeToCapture, m_continueToLocationStack, and m_continueToLocationTargetCallFrames.
Referenced by handleProgramBreak().
stackTraceFor()
std::shared_ptr< AsyncStackTrace > v8_inspector::V8Debugger::stackTraceFor (int contextGroupId, const V8StackTraceId & id)
Definition at line 1113 of file v8-debugger.cc.
                                                  {
  if (debuggerIdFor(contextGroupId).pair() != id.debugger_id) return nullptr;
  auto it = m_storedStackTraces.find(id.id);
  if (it == m_storedStackTraces.end()) return nullptr;
  return it->second.lock();
}
References debuggerIdFor(), and m_storedStackTraces.
Referenced by v8_inspector::V8DebuggerAgentImpl::getStackTrace().
stepIntoStatement()
void v8_inspector::V8Debugger::stepIntoStatement (int targetContextGroupId, bool breakOnAsyncCall)
Definition at line 316 of file v8-debugger.cc.
                                                          {
  DCHECK(isPaused());
  DCHECK(targetContextGroupId);
  m_targetContextGroupId = targetContextGroupId;
  m_pauseOnAsyncCall = breakOnAsyncCall;
  v8::debug::PrepareStep(m_isolate, v8::debug::StepInto);
  continueProgram(targetContextGroupId);
}
References continueProgram(), DCHECK, isPaused(), m_isolate, m_pauseOnAsyncCall, m_targetContextGroupId, v8::debug::PrepareStep(), and v8::debug::StepInto.
Referenced by v8_inspector::V8DebuggerAgentImpl::stepInto().
stepOutOfFunction()
void v8_inspector::V8Debugger::stepOutOfFunction (int targetContextGroupId)
Definition at line 334 of file v8-debugger.cc.
                                                           {
  DCHECK(isPaused());
  DCHECK(targetContextGroupId);
  m_targetContextGroupId = targetContextGroupId;
  v8::debug::PrepareStep(m_isolate, v8::debug::StepOut);
  continueProgram(targetContextGroupId);
}
References continueProgram(), DCHECK, isPaused(), m_isolate, m_targetContextGroupId, v8::debug::PrepareStep(), and v8::debug::StepOut.
Referenced by v8_inspector::V8DebuggerAgentImpl::stepOut().
stepOverStatement()
void v8_inspector::V8Debugger::stepOverStatement (int targetContextGroupId)
Definition at line 326 of file v8-debugger.cc.
                                                           {
  DCHECK(isPaused());
  DCHECK(targetContextGroupId);
  m_targetContextGroupId = targetContextGroupId;
  v8::debug::PrepareStep(m_isolate, v8::debug::StepOver);
  continueProgram(targetContextGroupId);
}
References continueProgram(), DCHECK, isPaused(), m_isolate, m_targetContextGroupId, v8::debug::PrepareStep(), and v8::debug::StepOver.
Referenced by v8_inspector::V8DebuggerAgentImpl::stepOver().
storeCurrentStackTrace()
V8StackTraceId v8_inspector::V8Debugger::storeCurrentStackTrace (const StringView & description)
Definition at line 1121 of file v8-debugger.cc.
                                   {
  if (!m_maxAsyncCallStackDepth) return V8StackTraceId();
  v8::HandleScope scope(m_isolate);
  int contextGroupId = currentContextGroupId();
  if (!contextGroupId) return V8StackTraceId();
  std::shared_ptr<AsyncStackTrace> asyncStack =
      AsyncStackTrace::capture(this, toString16(description));
  if (!asyncStack) return V8StackTraceId();
  uintptr_t id = AsyncStackTrace::store(this, asyncStack);
  m_allAsyncStacks.push_back(std::move(asyncStack));
  collectOldAsyncStacksIfNeeded();
  bool shouldPause =
      m_pauseOnAsyncCall && contextGroupId == m_targetContextGroupId;
  if (shouldPause) {
    m_pauseOnAsyncCall = false;
    v8::debug::ClearStepping(m_isolate); // Cancel step into.
  }
  return V8StackTraceId(id, debuggerIdFor(contextGroupId).pair(), shouldPause);
}
References v8_inspector::AsyncStackTrace::capture(), v8::debug::ClearStepping(), collectOldAsyncStacksIfNeeded(), currentContextGroupId(), debuggerIdFor(), m_allAsyncStacks, m_isolate, m_maxAsyncCallStackDepth, m_pauseOnAsyncCall, m_targetContextGroupId, v8_inspector::AsyncStackTrace::store(), and v8_inspector::toString16().
storeStackTrace()
uintptr_t v8_inspector::V8Debugger::storeStackTrace (std::shared_ptr< AsyncStackTrace > stack)
Definition at line 1147 of file v8-debugger.cc.
                                               {
  uintptr_t id = ++m_lastStackTraceId;
  m_storedStackTraces[id] = asyncStack;
  return id;
}
References m_lastStackTraceId, and m_storedStackTraces.
Referenced by v8_inspector::AsyncStackTrace::store().
symbolize()
std::shared_ptr< StackFrame > v8_inspector::V8Debugger::symbolize (v8::Local< v8::StackFrame > v8Frame)
Definition at line 1414 of file v8-debugger.cc.
                                   {
  int scriptId = v8Frame->GetScriptId();
  auto location = v8Frame->GetLocation();
  int lineNumber = location.GetLineNumber();
  int columnNumber = location.GetColumnNumber();
  CachedStackFrameKey key{scriptId, lineNumber, columnNumber};
  auto functionName = toProtocolString(isolate(), v8Frame->GetFunctionName());
  auto it = m_cachedStackFrames.find(key);
  std::shared_ptr<StackFrame> stackFrame;
  if (it != m_cachedStackFrames.end() && (stackFrame = it->second.lock())) {
    if (stackFrame->functionName() == functionName) {
      DCHECK_EQ(
          stackFrame->sourceURL(),
          toProtocolString(isolate(), v8Frame->GetScriptNameOrSourceURL()));
      return stackFrame;
    }
  }
  auto sourceURL =
      toProtocolString(isolate(), v8Frame->GetScriptNameOrSourceURL());
  auto hasSourceURLComment =
      v8Frame->GetScriptName() != v8Frame->GetScriptNameOrSourceURL();
  stackFrame = std::make_shared<StackFrame>(std::move(functionName), scriptId,
                                            std::move(sourceURL), lineNumber,
                                            columnNumber, hasSourceURLComment);
  m_cachedStackFrames.emplace(key, stackFrame);
  return stackFrame;
}
References DCHECK_EQ, isolate(), v8::internal::key, m_cachedStackFrames, and v8_inspector::toProtocolString().
Referenced by v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::toFramesVector().
terminateExecution()
void v8_inspector::V8Debugger::terminateExecution (v8::Local< v8::Context > context, std::unique_ptr< TerminateExecutionCallback > callback)
Definition at line 342 of file v8-debugger.cc.
                                                        {
  if (!m_terminateExecutionReported) {
    if (callback) {
      callback->sendFailure(Response::ServerError(
          "There is current termination request in progress"));
    }
    return;
  }
  m_terminateExecutionCallback = std::move(callback);
  installTerminateExecutionCallbacks(context);
  m_isolate->TerminateExecution();
}
References installTerminateExecutionCallbacks(), m_isolate, m_terminateExecutionCallback, m_terminateExecutionReported, and v8::Isolate::TerminateExecution().
Referenced by v8_inspector::V8RuntimeAgentImpl::terminateExecution().
terminateExecutionCompletedCallback()
void v8_inspector::V8Debugger::terminateExecutionCompletedCallback (v8::Isolate * isolate) [static], [private]
Definition at line 401 of file v8-debugger.cc.
                                                                       {
  V8InspectorImpl* inspector =
      static_cast<V8InspectorImpl*>(v8::debug::GetInspector(isolate));
  V8Debugger* debugger = inspector->debugger();
  debugger->reportTermination();
}
References v8_inspector::V8InspectorImpl::debugger(), v8::debug::GetInspector(), inspector(), isolate(), and reportTermination().
Referenced by installTerminateExecutionCallbacks(), reportTermination(), terminateExecutionCompletedCallbackIgnoringData(), and ~V8Debugger().
terminateExecutionCompletedCallbackIgnoringData()
void v8_inspector::V8Debugger::terminateExecutionCompletedCallbackIgnoringData (v8::Isolate * isolate, void * data) [static], [private]
Definition at line 408 of file v8-debugger.cc.
                                    {
  DCHECK(data);
  // Ensure that after every microtask completed callback we remove the
  // callback regardless of how `terminateExecutionCompletedCallback` behaves.
  static_cast<v8::MicrotaskQueue*>(data)->RemoveMicrotasksCompletedCallback(
      &V8Debugger::terminateExecutionCompletedCallbackIgnoringData, data);
  terminateExecutionCompletedCallback(isolate);
}
References DCHECK, isolate(), and terminateExecutionCompletedCallback().
Referenced by installTerminateExecutionCallbacks(), reportTermination(), and ~V8Debugger().
unmuteScriptParsedEvents()
void v8_inspector::V8Debugger::unmuteScriptParsedEvents ()
Definition at line 1359 of file v8-debugger.cc.
                                          {
  --m_ignoreScriptParsedEventsCounter;
  DCHECK_GE(m_ignoreScriptParsedEventsCounter, 0);
}
References DCHECK_GE, and m_ignoreScriptParsedEventsCounter.
Referenced by v8_inspector::V8RuntimeAgentImpl::compileScript().
Member Data Documentation
m_allAsyncStacks
std::list<std::shared_ptr<AsyncStackTrace> > v8_inspector::V8Debugger::m_allAsyncStacks [private]
Definition at line 305 of file v8-debugger.h.
Referenced by allAsyncTasksCanceled(), asyncTaskScheduledForStack(), collectOldAsyncStacksIfNeeded(), dumpAsyncTaskStacksStateForTest(), and storeCurrentStackTrace().
m_asyncParents
StackTraceToAsyncParent v8_inspector::V8Debugger::m_asyncParents [private]
Definition at line 299 of file v8-debugger.h.
Referenced by asyncParentFor(), asyncStackTraceCaptured(), and collectOldAsyncStacksIfNeeded().
m_asyncTaskStacks
AsyncTaskToStackTrace v8_inspector::V8Debugger::m_asyncTaskStacks [private]
Definition at line 284 of file v8-debugger.h.
Referenced by allAsyncTasksCanceled(), asyncTaskCanceledForStack(), asyncTaskScheduledForStack(), asyncTaskStartedForStack(), collectOldAsyncStacksIfNeeded(), and dumpAsyncTaskStacksStateForTest().
m_breakpointsActiveCount
int v8_inspector::V8Debugger::m_breakpointsActiveCount = 0 [private]
Definition at line 240 of file v8-debugger.h.
Referenced by setBreakpointsActive().
m_cachedStackFrames
std::unordered_map<CachedStackFrameKey, std::weak_ptr<StackFrame>, CachedStackFrameKey::Hash, CachedStackFrameKey::Equal> v8_inspector::V8Debugger::m_cachedStackFrames [private]
Definition at line 280 of file v8-debugger.h.
Referenced by collectOldAsyncStacksIfNeeded(), and symbolize().
m_contextGroupIdToDebuggerId
std::unordered_map<int, internal::V8DebuggerId> v8_inspector::V8Debugger::m_contextGroupIdToDebuggerId [private]
Definition at line 327 of file v8-debugger.h.
Referenced by debuggerIdFor().
m_continueToLocationBreakpointId
int v8_inspector::V8Debugger::m_continueToLocationBreakpointId [private]
Definition at line 248 of file v8-debugger.h.
Referenced by clearContinueToLocation(), continueToLocation(), and handleProgramBreak().
m_continueToLocationStack
std::unique_ptr<V8StackTraceImpl> v8_inspector::V8Debugger::m_continueToLocationStack [private]
Definition at line 250 of file v8-debugger.h.
Referenced by clearContinueToLocation(), continueToLocation(), and shouldContinueToCurrentLocation().
m_continueToLocationTargetCallFrames
String16 v8_inspector::V8Debugger::m_continueToLocationTargetCallFrames [private]
Definition at line 249 of file v8-debugger.h.
Referenced by clearContinueToLocation(), continueToLocation(), and shouldContinueToCurrentLocation().
m_currentAsyncParent
std::vector<std::shared_ptr<AsyncStackTrace> > v8_inspector::V8Debugger::m_currentAsyncParent [private]
Definition at line 292 of file v8-debugger.h.
Referenced by allAsyncTasksCanceled(), asyncTaskFinishedForStack(), asyncTaskStartedForStack(), currentAsyncParent(), externalAsyncTaskFinished(), and externalAsyncTaskStarted().
m_currentExternalParent
std::vector<V8StackTraceId> v8_inspector::V8Debugger::m_currentExternalParent [private]
Definition at line 293 of file v8-debugger.h.
Referenced by allAsyncTasksCanceled(), asyncTaskFinishedForStack(), asyncTaskStartedForStack(), currentExternalParent(), externalAsyncTaskFinished(), and externalAsyncTaskStarted().
m_currentTasks
std::vector<void*> v8_inspector::V8Debugger::m_currentTasks [private]
Definition at line 291 of file v8-debugger.h.
Referenced by allAsyncTasksCanceled(), asyncTaskFinishedForStack(), asyncTaskStartedForStack(), externalAsyncTaskFinished(), and externalAsyncTaskStarted().
m_enableCount
int v8_inspector::V8Debugger::m_enableCount [private]
Definition at line 238 of file v8-debugger.h.
Referenced by disable(), enable(), and enabled().
m_externalAsyncTaskPauseRequested
bool v8_inspector::V8Debugger::m_externalAsyncTaskPauseRequested = false [private]
Definition at line 313 of file v8-debugger.h.
Referenced by disable(), externalAsyncTaskFinished(), externalAsyncTaskStarted(), handleProgramBreak(), and hasScheduledBreakOnNextFunctionCall().
m_externalParents
StackTraceToExternalParent v8_inspector::V8Debugger::m_externalParents [private]
Definition at line 300 of file v8-debugger.h.
Referenced by allAsyncTasksCanceled(), asyncParentFor(), asyncStackTraceCaptured(), and collectOldAsyncStacksIfNeeded().
m_ignoreScriptParsedEventsCounter
int v8_inspector::V8Debugger::m_ignoreScriptParsedEventsCounter [private]
Definition at line 241 of file v8-debugger.h.
Referenced by muteScriptParsedEvents(), ScriptCompiled(), and unmuteScriptParsedEvents().
m_inspector
V8InspectorImpl* v8_inspector::V8Debugger::m_inspector [private]
Definition at line 237 of file v8-debugger.h.
Referenced by addInternalObject(), BreakOnInstrumentation(), BreakpointConditionEvaluated(), captureStackTrace(), continueProgram(), currentContextGroupId(), debuggerIdFor(), disable(), getCompiledScripts(), handleProgramBreak(), inspector(), IsFunctionBlackboxed(), nearHeapLimitCallback(), queryObjects(), quitMessageLoopIfAgentsFinishedInstrumentation(), ScriptCompiled(), setAsyncCallStackDepth(), and ShouldBeSkipped().
m_instrumentationPause
bool v8_inspector::V8Debugger::m_instrumentationPause = false [private]
Definition at line 246 of file v8-debugger.h.
Referenced by BreakOnInstrumentation(), continueProgram(), disable(), and isInInstrumentationPause().
m_isolate
v8::Isolate* v8_inspector::V8Debugger::m_isolate [private]
Definition at line 236 of file v8-debugger.h.
Referenced by asyncTaskCanceledForStack(), asyncTaskCandidateForStepping(), asyncTaskFinishedForStepping(), asyncTaskScheduledForStack(), asyncTaskStartedForStack(), asyncTaskStartedForStepping(), breakProgram(), breakProgramOnAssert(), canBreakProgram(), clearContinueToLocation(), continueProgram(), currentContextGroupId(), disable(), enable(), externalAsyncTaskFinished(), externalAsyncTaskStarted(), getCompiledScripts(), getTargetScopes(), handleProgramBreak(), installTerminateExecutionCallbacks(), internalProperties(), interruptAndBreak(), isolate(), nearHeapLimitCallback(), removeBreakpoint(), reportTermination(), restartFrame(), ScriptCompiled(), setAsyncCallStackDepth(), setBreakpointsActive(), setMaxCallStackSizeToCapture(), setPauseOnExceptionsState(), setPauseOnNextCall(), stepIntoStatement(), stepOutOfFunction(), stepOverStatement(), storeCurrentStackTrace(), terminateExecution(), and ~V8Debugger().
m_lastStackTraceId
uintptr_t v8_inspector::V8Debugger::m_lastStackTraceId = 0 [private]
Definition at line 325 of file v8-debugger.h.
Referenced by storeStackTrace().
m_maxAsyncCallStackDepth
int v8_inspector::V8Debugger::m_maxAsyncCallStackDepth [private]
Definition at line 288 of file v8-debugger.h.
Referenced by asyncTaskCanceledForStack(), asyncTaskFinishedForStack(), asyncTaskScheduledForStack(), asyncTaskStartedForStack(), externalAsyncTaskFinished(), externalAsyncTaskStarted(), maxAsyncCallChainDepth(), setAsyncCallStackDepth(), and storeCurrentStackTrace().
m_maxAsyncCallStackDepthMap
std::unordered_map<V8DebuggerAgentImpl*, int> v8_inspector::V8Debugger::m_maxAsyncCallStackDepthMap [private]
Definition at line 307 of file v8-debugger.h.
Referenced by setAsyncCallStackDepth().
m_maxAsyncCallStacks
size_t v8_inspector::V8Debugger::m_maxAsyncCallStacks [private]
Definition at line 287 of file v8-debugger.h.
Referenced by collectOldAsyncStacksIfNeeded(), and setMaxAsyncTaskStacksForTest().
m_maxCallStackSizeToCapture
int v8_inspector::V8Debugger::m_maxCallStackSizeToCapture [private]
Definition at line 289 of file v8-debugger.h.
Referenced by maxCallStackSizeToCapture(), and setMaxCallStackSizeToCapture().
m_maxCallStackSizeToCaptureMap
std::unordered_map<V8RuntimeAgentImpl*, int> v8_inspector::V8Debugger::m_maxCallStackSizeToCaptureMap [private]
Definition at line 308 of file v8-debugger.h.
Referenced by setMaxCallStackSizeToCapture().
m_originalHeapLimit
size_t v8_inspector::V8Debugger::m_originalHeapLimit = 0 [private]
Definition at line 242 of file v8-debugger.h.
Referenced by disable(), and nearHeapLimitCallback().
m_pausedContextGroupId
int v8_inspector::V8Debugger::m_pausedContextGroupId = 0 [private]
Definition at line 245 of file v8-debugger.h.
Referenced by BreakOnInstrumentation(), continueProgram(), disable(), handleProgramBreak(), isPaused(), isPausedInContextGroup(), and quitMessageLoopIfAgentsFinishedInstrumentation().
m_pauseOnAsyncCall
bool v8_inspector::V8Debugger::m_pauseOnAsyncCall = false [private]
Definition at line 320 of file v8-debugger.h.
Referenced by asyncTaskCandidateForStepping(), disable(), handleProgramBreak(), stepIntoStatement(), and storeCurrentStackTrace().
m_pauseOnExceptionsState
v8::debug::ExceptionBreakState v8_inspector::V8Debugger::m_pauseOnExceptionsState [private]
Definition at line 317 of file v8-debugger.h.
Referenced by breakProgramOnAssert(), enable(), getPauseOnExceptionsState(), and setPauseOnExceptionsState().
m_pauseOnNextCallRequested
bool v8_inspector::V8Debugger::m_pauseOnNextCallRequested = false [private]
Definition at line 315 of file v8-debugger.h.
Referenced by disable(), handleProgramBreak(), hasScheduledBreakOnNextFunctionCall(), and setPauseOnNextCall().
m_recurringTasks
std::unordered_set<void*> v8_inspector::V8Debugger::m_recurringTasks [private]
Definition at line 285 of file v8-debugger.h.
Referenced by allAsyncTasksCanceled(), asyncTaskCanceledForStack(), asyncTaskFinishedForStack(), asyncTaskScheduledForStack(), collectOldAsyncStacksIfNeeded(), and dumpAsyncTaskStacksStateForTest().
m_requestedPauseAfterInstrumentation
bool v8_inspector::V8Debugger::m_requestedPauseAfterInstrumentation = false [private]
Definition at line 247 of file v8-debugger.h.
Referenced by BreakOnInstrumentation(), and requestPauseAfterInstrumentation().
m_scheduledOOMBreak
bool v8_inspector::V8Debugger::m_scheduledOOMBreak = false [private]
Definition at line 243 of file v8-debugger.h.
Referenced by disable(), handleProgramBreak(), and nearHeapLimitCallback().
m_storedStackTraces
StoredStackTraces v8_inspector::V8Debugger::m_storedStackTraces [private]
Definition at line 324 of file v8-debugger.h.
Referenced by collectOldAsyncStacksIfNeeded(), stackTraceFor(), and storeStackTrace().
m_targetContextGroupId
int v8_inspector::V8Debugger::m_targetContextGroupId = 0 [private]
Definition at line 244 of file v8-debugger.h.
Referenced by asyncTaskCandidateForStepping(), asyncTaskStartedForStepping(), breakProgram(), breakProgramOnAssert(), continueToLocation(), externalAsyncTaskStarted(), handleProgramBreak(), interruptAndBreak(), nearHeapLimitCallback(), restartFrame(), setPauseOnNextCall(), stepIntoStatement(), stepOutOfFunction(), stepOverStatement(), and storeCurrentStackTrace().
m_taskWithScheduledBreak
void* v8_inspector::V8Debugger::m_taskWithScheduledBreak = nullptr [private]
Definition at line 309 of file v8-debugger.h.
Referenced by asyncTaskCandidateForStepping(), asyncTaskFinishedForStepping(), asyncTaskStartedForStepping(), disable(), and handleProgramBreak().
m_taskWithScheduledBreakPauseRequested
bool v8_inspector::V8Debugger::m_taskWithScheduledBreakPauseRequested = false [private]
Definition at line 314 of file v8-debugger.h.
Referenced by asyncTaskFinishedForStepping(), asyncTaskStartedForStepping(), disable(), handleProgramBreak(), and hasScheduledBreakOnNextFunctionCall().
m_terminateExecutionCallback
std::unique_ptr<TerminateExecutionCallback> v8_inspector::V8Debugger::m_terminateExecutionCallback [private]
Definition at line 329 of file v8-debugger.h.
Referenced by reportTermination(), and terminateExecution().
m_terminateExecutionCallbackContext
v8::Global<v8::Context> v8_inspector::V8Debugger::m_terminateExecutionCallbackContext [private]
Definition at line 330 of file v8-debugger.h.
Referenced by installTerminateExecutionCallbacks(), reportTermination(), and ~V8Debugger().
m_terminateExecutionReported
bool v8_inspector::V8Debugger::m_terminateExecutionReported = true [private]
Definition at line 331 of file v8-debugger.h.
Referenced by installTerminateExecutionCallbacks(), reportTermination(), and terminateExecution().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-debugger.h
/mnt/V8SourceCode/src/inspector/v8-debugger.cc