v8::internal::GlobalObjectsEnumerator Class Reference
Public Member Functions
GlobalObjectsEnumerator (Isolate *isolate, std::function< void(Handle< JSGlobalObject >)> handler)
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) override
void VisitRootPointers (Root root, const char *description, OffHeapObjectSlot start, OffHeapObjectSlot end) override
Private Member Functions
template<typename TSlot >
void VisitRootPointersImpl (Root root, const char *description, TSlot start, TSlot end)
Private Attributes
Isolate * isolate_
std::function< void(Handle< JSGlobalObject >)> handler_
Additional Inherited Members
Detailed Description
Definition at line 2932 of file heap-snapshot-generator.cc.
Constructor & Destructor Documentation
GlobalObjectsEnumerator()
v8::internal::GlobalObjectsEnumerator::GlobalObjectsEnumerator (Isolate * isolate, std::function< void(Handle< JSGlobalObject >)> handler) [inline]
Definition at line 2934 of file heap-snapshot-generator.cc.
      : isolate_(isolate), handler_(handler) {}
Member Function Documentation
VisitRootPointers() [1/2]
void v8::internal::GlobalObjectsEnumerator::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 2938 of file heap-snapshot-generator.cc.
                                                                            {
    VisitRootPointersImpl(root, description, start, end);
  }
References v8::internal::compiler::end(), and VisitRootPointersImpl().
VisitRootPointers() [2/2]
void v8::internal::GlobalObjectsEnumerator::VisitRootPointers (Root root, const char * description, OffHeapObjectSlot start, OffHeapObjectSlot end) [inline], [override], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 2943 of file heap-snapshot-generator.cc.
                                                         {
    VisitRootPointersImpl(root, description, start, end);
  }
References v8::internal::compiler::end(), and VisitRootPointersImpl().
VisitRootPointersImpl()
template<typename TSlot >
void v8::internal::GlobalObjectsEnumerator::VisitRootPointersImpl (Root root, const char * description, TSlot start, TSlot end) [inline], [private]
Definition at line 2951 of file heap-snapshot-generator.cc.
                                        {
    for (TSlot p = start; p < end; ++p) {
      DCHECK(!MapWord::IsPacked(p.Relaxed_Load(isolate_).ptr()));
      Tagged<Object> o = p.load(isolate_);
      if (!IsNativeContext(o, isolate_)) continue;
      Tagged<JSObject> proxy = Cast<Context>(o)->global_proxy();
      if (!IsJSGlobalProxy(proxy, isolate_)) continue;
      Tagged<Object> global = proxy->map(isolate_)->prototype(isolate_);
      if (!IsJSGlobalObject(global, isolate_)) continue;
      handler_(handle(Cast<JSGlobalObject>(global), isolate_));
    }
  }
References v8::internal::DCHECK(), v8::internal::compiler::end(), v8::internal::handle(), handler_, isolate_, and v8::internal::MapWord::IsPacked().
Referenced by VisitRootPointers().
Member Data Documentation
handler_
std::function<void(Handle<JSGlobalObject>)> v8::internal::GlobalObjectsEnumerator::handler_ [private]
Definition at line 2966 of file heap-snapshot-generator.cc.
Referenced by VisitRootPointersImpl().
isolate_
Isolate* v8::internal::GlobalObjectsEnumerator::isolate_ [private]
Definition at line 2965 of file heap-snapshot-generator.cc.
Referenced by VisitRootPointersImpl().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.cc