v8::internal::maglev::Int32Compare Class Reference
#include <maglev-ir.h>
Public Member Functions
Int32Compare (uint64_t bitfield, Operation operation)
Input & left_input ()
Input & right_input ()
constexpr Operation operation () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr Base::InputTypes kInputTypes
static constexpr int kLeftIndex = 0
static constexpr int kRightIndex = 1
Private Types
using Base = FixedInputValueNodeT< 2, Int32Compare >
using OperationBitField = NextBitField< Operation, 5 >
Additional Inherited Members
Detailed Description
Definition at line 3292 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::Int32Compare::Base = FixedInputValueNodeT<2, Int32Compare> [private]
Definition at line 3293 of file maglev-ir.h.
OperationBitField
using v8::internal::maglev::Int32Compare::OperationBitField = NextBitField<Operation, 5> [private]
Definition at line 3318 of file maglev-ir.h.
Constructor & Destructor Documentation
Int32Compare()
v8::internal::maglev::Int32Compare::Int32Compare (uint64_t bitfield, Operation operation) [inline], [explicit]
Definition at line 3296 of file maglev-ir.h.
      : Base(OperationBitField::update(bitfield, operation)) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::Int32Compare::GenerateCode (MaglevAssembler * , const ProcessingState &)
left_input()
Input& v8::internal::maglev::Int32Compare::left_input () [inline]
Definition at line 3304 of file maglev-ir.h.
{ return Node::input(kLeftIndex); }
References v8::internal::maglev::NodeBase::input(), and kLeftIndex.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
operation()
constexpr Operation v8::internal::maglev::Int32Compare::operation () const [inline], [constexpr]
Definition at line 3307 of file maglev-ir.h.
                                        {
    return OperationBitField::decode(bitfield());
  }
Referenced by options(), PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
options()
auto v8::internal::maglev::Int32Compare::options () const [inline]
Definition at line 3315 of file maglev-ir.h.
{ return std::tuple{operation()}; }
References operation().
PrintParams()
void v8::internal::maglev::Int32Compare::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8318 of file maglev-ir.cc.
                                                                          {
  os << "(" << operation() << ")";
}
References operation().
right_input()
Input& v8::internal::maglev::Int32Compare::right_input () [inline]
Definition at line 3305 of file maglev-ir.h.
{ return Node::input(kRightIndex); }
References v8::internal::maglev::NodeBase::input(), and kRightIndex.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::Int32Compare::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::Int32Compare::kInputTypes [static], [constexpr]
Initial value:
{ValueRepresentation::kInt32,
                                                ValueRepresentation::kInt32}
Definition at line 3299 of file maglev-ir.h.
kLeftIndex
constexpr int v8::internal::maglev::Int32Compare::kLeftIndex = 0 [static], [constexpr]
Definition at line 3302 of file maglev-ir.h.
Referenced by left_input().
kRightIndex
constexpr int v8::internal::maglev::Int32Compare::kRightIndex = 1 [static], [constexpr]
Definition at line 3303 of file maglev-ir.h.
Referenced by right_input().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc