cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy > Class Template Reference
#include <persistent.h>
Public Types
using PointeeType = T
Public Member Functions
BasicPersistent (const SourceLocation &loc=SourceLocation::Current())
BasicPersistent (std::nullptr_t, const SourceLocation &loc=SourceLocation::Current())
BasicPersistent (SentinelPointer s, const SourceLocation &loc=SourceLocation::Current())
BasicPersistent (T *raw, const SourceLocation &loc=SourceLocation::Current())
BasicPersistent (T &raw, const SourceLocation &loc=SourceLocation::Current())
BasicPersistent (const BasicPersistent &other, const SourceLocation &loc=SourceLocation::Current())
template<typename U , typename OtherWeaknessPolicy , typename OtherLocationPolicy , typename OtherCheckingPolicy , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
BasicPersistent (const BasicPersistent< U, OtherWeaknessPolicy, OtherLocationPolicy, OtherCheckingPolicy > &other, const SourceLocation &loc=SourceLocation::Current())
BasicPersistent (BasicPersistent &&other, const SourceLocation &loc=SourceLocation::Current()) noexcept
template<typename U , typename MemberBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
BasicPersistent (const internal::BasicMember< U, MemberBarrierPolicy, MemberWeaknessTag, MemberCheckingPolicy, MemberStorageType > &member, const SourceLocation &loc=SourceLocation::Current())
~BasicPersistent ()
BasicPersistent & operator= (const BasicPersistent &other)
template<typename U , typename OtherWeaknessPolicy , typename OtherLocationPolicy , typename OtherCheckingPolicy , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
BasicPersistent & operator= (const BasicPersistent< U, OtherWeaknessPolicy, OtherLocationPolicy, OtherCheckingPolicy > &other)
BasicPersistent & operator= (BasicPersistent &&other) noexcept
template<typename U , typename MemberBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
BasicPersistent & operator= (const internal::BasicMember< U, MemberBarrierPolicy, MemberWeaknessTag, MemberCheckingPolicy, MemberStorageType > &member)
BasicPersistent & operator= (T *other)
BasicPersistent & operator= (std::nullptr_t)
BasicPersistent & operator= (SentinelPointer s)
operator bool () const
operator T* () const
T * operator-> () const
T & operator* () const
V8_CLANG_NO_SANITIZE (`cfi-unrelated-cast`) T *Get() const
void Clear ()
T * Release ()
template<typename U , typename OtherWeaknessPolicy = WeaknessPolicy, typename OtherLocationPolicy = LocationPolicy, typename OtherCheckingPolicy = CheckingPolicy>
BasicPersistent< U, OtherWeaknessPolicy, OtherLocationPolicy, OtherCheckingPolicy > To () const
Private Member Functions
bool IsValid () const
void Assign (T *ptr)
void ClearFromGC () const
T * GetFromGC () const
Static Private Member Functions
static void TraceAsRoot (RootVisitor &root_visitor, const void *ptr)
Friends
class internal::RootVisitor
Additional Inherited Members
Detailed Description
template<typename T, typename WeaknessPolicy, typename LocationPolicy, typename CheckingPolicy>
class cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >
Definition at line 51 of file persistent.h.
Member Typedef Documentation
PointeeType
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
using cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::PointeeType = T
Definition at line 57 of file persistent.h.
Constructor & Destructor Documentation
BasicPersistent() [1/9]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent (const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 60 of file persistent.h.
      : LocationPolicy(loc) {}
BasicPersistent() [2/9]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent (std::nullptr_t , const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 64 of file persistent.h.
      : LocationPolicy(loc) {}
BasicPersistent() [3/9]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent (SentinelPointer s, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 68 of file persistent.h.
      : PersistentBase(s), LocationPolicy(loc) {}
BasicPersistent() [4/9]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent (T * raw, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 73 of file persistent.h.
      : PersistentBase(raw), LocationPolicy(loc) {
    if (!IsValid()) return;
    SetNode(WeaknessPolicy::GetPersistentRegion(GetValue())
                .AllocateNode(this, &TraceAsRoot));
    this->CheckPointer(Get());
  }
References v8::internal::compiler::turboshaft::Get(), cppgc::internal::PersistentBase::GetValue(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid(), cppgc::internal::PersistentBase::SetNode(), and cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::TraceAsRoot().
BasicPersistent() [5/9]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent (T & raw, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 82 of file persistent.h.
      : BasicPersistent(&raw, loc) {}
BasicPersistent() [6/9]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent (const BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy > & other, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 87 of file persistent.h.
      : BasicPersistent(other.Get(), loc) {}
BasicPersistent() [7/9]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
template<typename U , typename OtherWeaknessPolicy , typename OtherLocationPolicy , typename OtherCheckingPolicy , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent (const BasicPersistent< U, OtherWeaknessPolicy, OtherLocationPolicy, OtherCheckingPolicy > & other, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 96 of file persistent.h.
      : BasicPersistent(other.Get(), loc) {}
BasicPersistent() [8/9]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent (BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy > && other, const SourceLocation & loc = SourceLocation::Current()) [inline], [noexcept]
Definition at line 104 of file persistent.h.
      : PersistentBase(std::move(other)), LocationPolicy(std::move(other)) {
    if (!IsValid()) return;
    GetNode()->UpdateOwner(this);
    other.SetValue(nullptr);
    other.SetNode(nullptr);
    this->CheckPointer(Get());
  }
References v8::internal::compiler::turboshaft::Get(), cppgc::internal::PersistentBase::GetNode(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid(), and cppgc::internal::PersistentNode::UpdateOwner().
BasicPersistent() [9/9]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
template<typename U , typename MemberBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent (const internal::BasicMember< U, MemberBarrierPolicy, MemberWeaknessTag, MemberCheckingPolicy, MemberStorageType > & member, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 121 of file persistent.h.
      : BasicPersistent(member.Get(), loc) {}
 BasicPersistent()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::~BasicPersistent () [inline]
Definition at line 127 of file persistent.h.
{ Clear(); }
References cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Clear().
Member Function Documentation
Assign()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
void cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Assign (T * ptr) [inline], [private]
Definition at line 239 of file persistent.h.
                      {
    if (IsValid()) {
      if (ptr && ptr != kSentinelPointer) {
        // Simply assign the pointer reusing the existing node.
        SetValue(ptr);
        this->CheckPointer(ptr);
        return;
      }
      WeaknessPolicy::GetPersistentRegion(GetValue()).FreeNode(GetNode());
      SetNode(nullptr);
    }
    SetValue(ptr);
    if (!IsValid()) return;
    SetNode(WeaknessPolicy::GetPersistentRegion(GetValue())
                .AllocateNode(this, &TraceAsRoot));
    this->CheckPointer(Get());
  }
References v8::internal::compiler::turboshaft::Get(), cppgc::internal::PersistentBase::GetNode(), cppgc::internal::PersistentBase::GetValue(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid(), cppgc::kSentinelPointer, cppgc::internal::PersistentBase::SetNode(), cppgc::internal::PersistentBase::SetValue(), and cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::TraceAsRoot().
Referenced by cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=().
Clear()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
void cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Clear () [inline]
Definition at line 201 of file persistent.h.
               {
    // Simplified version of `Assign()` to allow calling without a complete type
    // `T`.
    if (IsValid()) {
      WeaknessPolicy::GetPersistentRegion(GetValue()).FreeNode(GetNode());
      SetNode(nullptr);
    }
    SetValue(nullptr);
  }
References cppgc::internal::PersistentBase::GetNode(), cppgc::internal::PersistentBase::GetValue(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid(), cppgc::internal::PersistentBase::SetNode(), and cppgc::internal::PersistentBase::SetValue().
Referenced by cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Release(), and cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::~BasicPersistent().
ClearFromGC()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
void cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::ClearFromGC () const [inline], [private]
Definition at line 257 of file persistent.h.
                           {
    if (IsValid()) {
      WeaknessPolicy::GetPersistentRegion(GetValue()).FreeNode(GetNode());
      PersistentBase::ClearFromGC();
    }
  }
References cppgc::internal::PersistentBase::ClearFromGC(), cppgc::internal::PersistentBase::GetNode(), cppgc::internal::PersistentBase::GetValue(), and cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid().
GetFromGC()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
T* cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::GetFromGC () const [inline], [private]
Definition at line 266 of file persistent.h.
                       {
    return static_cast<T*>(const_cast<void*>(GetValue()));
  }
References cppgc::internal::PersistentBase::GetValue().
IsValid()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
bool cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid () const [inline], [private]
Definition at line 232 of file persistent.h.
                       {
    // Ideally, handling kSentinelPointer would be done by the embedder. On the
    // other hand, having Persistent aware of it is beneficial since no node
    // gets wasted.
    return GetValue() != nullptr && GetValue() != kSentinelPointer;
  }
References cppgc::internal::PersistentBase::GetValue(), and cppgc::kSentinelPointer.
Referenced by cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Assign(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Clear(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::ClearFromGC(), and cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=().
operator bool()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator bool () const [inline], [explicit]
Definition at line 184 of file persistent.h.
{ return Get(); }
References v8::internal::compiler::turboshaft::Get().
operator T*()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator T* () const [inline]
Definition at line 187 of file persistent.h.
{ return Get(); }
References v8::internal::compiler::turboshaft::Get().
operator*()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
T& cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator* () const [inline]
Definition at line 189 of file persistent.h.
{ return *Get(); }
References v8::internal::compiler::turboshaft::Get().
operator->()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
T* cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator-> () const [inline]
Definition at line 188 of file persistent.h.
{ return Get(); }
References v8::internal::compiler::turboshaft::Get().
operator=() [1/7]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
BasicPersistent& cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator= (BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy > && other) [inline], [noexcept]
Definition at line 144 of file persistent.h.
                                                               {
    if (this == &other) return *this;
    Clear();
    PersistentBase::operator=(std::move(other));
    LocationPolicy::operator=(std::move(other));
    if (!IsValid()) return *this;
    GetNode()->UpdateOwner(this);
    other.SetValue(nullptr);
    other.SetNode(nullptr);
    this->CheckPointer(Get());
    return *this;
  }
References cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Clear(), v8::internal::compiler::turboshaft::Get(), cppgc::internal::PersistentBase::GetNode(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid(), cppgc::internal::PersistentBase::SetNode(), cppgc::internal::PersistentBase::SetValue(), and cppgc::internal::PersistentNode::UpdateOwner().
operator=() [2/7]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
BasicPersistent& cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator= (const BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy > & other) [inline]
Definition at line 130 of file persistent.h.
                                                           {
    return operator=(other.Get());
  }
Referenced by cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=().
operator=() [3/7]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
template<typename U , typename OtherWeaknessPolicy , typename OtherLocationPolicy , typename OtherCheckingPolicy , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
BasicPersistent& cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator= (const BasicPersistent< U, OtherWeaknessPolicy, OtherLocationPolicy, OtherCheckingPolicy > & other) [inline]
Definition at line 137 of file persistent.h.
                                                         {
    return operator=(other.Get());
  }
References cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=().
operator=() [4/7]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
template<typename U , typename MemberBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
BasicPersistent& cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator= (const internal::BasicMember< U, MemberBarrierPolicy, MemberWeaknessTag, MemberCheckingPolicy, MemberStorageType > & member) [inline]
Definition at line 162 of file persistent.h.
                  {
    return operator=(member.Get());
  }
References cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=().
operator=() [5/7]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
BasicPersistent& cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator= (SentinelPointer s) [inline]
Definition at line 179 of file persistent.h.
                                                {
    Assign(s);
    return *this;
  }
References cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Assign().
operator=() [6/7]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
BasicPersistent& cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator= (std::nullptr_t) [inline]
Definition at line 174 of file persistent.h.
                                           {
    Clear();
    return *this;
  }
References cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Clear().
operator=() [7/7]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
BasicPersistent& cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator= (T * other) [inline]
Definition at line 169 of file persistent.h.
                                       {
    Assign(other);
    return *this;
  }
References cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Assign().
Release()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
T* cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Release () [inline]
Definition at line 211 of file persistent.h.
               {
    T* result = Get();
    Clear();
    return result;
  }
References cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Clear(), v8::internal::compiler::turboshaft::Get(), and v8::base::internal::result.
To()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
template<typename U , typename OtherWeaknessPolicy = WeaknessPolicy, typename OtherLocationPolicy = LocationPolicy, typename OtherCheckingPolicy = CheckingPolicy>
BasicPersistent<U, OtherWeaknessPolicy, OtherLocationPolicy, OtherCheckingPolicy> cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::To () const [inline]
Definition at line 222 of file persistent.h.
             {
    return BasicPersistent<U, OtherWeaknessPolicy, OtherLocationPolicy,
                           OtherCheckingPolicy>(static_cast<U*>(Get()));
  }
References v8::internal::compiler::turboshaft::Get(), and v8::base::internal::U.
TraceAsRoot()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
static void cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::TraceAsRoot (RootVisitor & root_visitor, const void * ptr) [inline], [static], [private]
Definition at line 228 of file persistent.h.
                                                                      {
    root_visitor.Trace(*static_cast<const BasicPersistent*>(ptr));
  }
References cppgc::internal::RootVisitor::Trace().
Referenced by cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Assign(), and cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent().
V8_CLANG_NO_SANITIZE()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::V8_CLANG_NO_SANITIZE (`cfi-unrelated-cast`) const [inline]
Definition at line 194 of file persistent.h.
                                                            {
    // The const_cast below removes the constness from PersistentBase storage.
    // The following static_cast re-adds any constness if specified through the
    // user-visible template parameter T.
    return static_cast<T*>(const_cast<void*>(GetValue()));
  }
References cppgc::internal::PersistentBase::GetValue().
Friends And Related Function Documentation
internal::RootVisitor
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
friend class internal::RootVisitor [friend]
Definition at line 270 of file persistent.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/internal/pointer-policies.h
/mnt/V8SourceCode/include/cppgc/persistent.h