v8::internal::wasm::FeedbackMaker Class Reference
Public Member Functions
FeedbackMaker (Isolate *const isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data, int func_index, int num_calls)
void AddCallRefCandidate (Tagged< WasmFuncRef > funcref, int count)
void AddCallIndirectCandidate (Tagged< Object > target_truncated_obj, int count)
void AddCall (int target, int count)
bool HasTargetCached (int target)
void AddResult (CallSiteFeedback feedback)
void FinalizeCall ()
void set_has_non_inlineable_targets ()
void set_megamorphic ()
base::OwnedVector< CallSiteFeedback > GetResult () &&
Private Attributes
Isolate *const isolate_
const Tagged< WasmTrustedInstanceData > instance_data_
base::OwnedVector< CallSiteFeedback > result_
int seen_calls_ = 0
const int num_imported_functions_
const int func_index_
int cache_usage_ {0}
std::array< int, kMaxPolymorphism > targets_cache_
std::array< int, kMaxPolymorphism > counts_cache_
bool has_non_inlineable_targets_ = false
bool is_megamorphic_ = false
Detailed Description
Definition at line 1355 of file module-compiler.cc.
Constructor & Destructor Documentation
FeedbackMaker()
v8::internal::wasm::FeedbackMaker::FeedbackMaker (Isolate *const isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data, int func_index, int num_calls) [inline]
Definition at line 1357 of file module-compiler.cc.
      : isolate_(isolate),
        instance_data_(trusted_instance_data),
        result_(
            base::OwnedVector<CallSiteFeedback>::NewForOverwrite(num_calls)),
        num_imported_functions_(static_cast<int>(
            trusted_instance_data->module()->num_imported_functions)),
        func_index_(func_index) {}
Member Function Documentation
AddCall()
void v8::internal::wasm::FeedbackMaker::AddCall (int target, int count) [inline]
Definition at line 1418 of file module-compiler.cc.
                                      {
    // If we add too many calls, treat it as megamorphic.
    if (static_cast<size_t>(cache_usage_) == targets_cache_.size() ||
        is_megamorphic_) {
      is_megamorphic_ = true;
      return;
    }
    // Keep the cache sorted (using insertion-sort), highest count first.
    int insertion_index = 0;
    while (insertion_index < cache_usage_ &&
           counts_cache_[insertion_index] >= count) {
      insertion_index++;
    }
    for (int shifted_index = cache_usage_ - 1; shifted_index >= insertion_index;
         shifted_index--) {
      targets_cache_[shifted_index + 1] = targets_cache_[shifted_index];
      counts_cache_[shifted_index + 1] = counts_cache_[shifted_index];
    }
    targets_cache_[insertion_index] = target;
    counts_cache_[insertion_index] = count;
    cache_usage_++;
  }
References cache_usage_, counts_cache_, is_megamorphic_, and targets_cache_.
Referenced by AddCallIndirectCandidate(), AddCallRefCandidate(), and v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction().
AddCallIndirectCandidate()
void v8::internal::wasm::FeedbackMaker::AddCallIndirectCandidate (Tagged< Object > target_truncated_obj, int count) [inline]
Definition at line 1384 of file module-compiler.cc.
                                           {
    // Discard cross-instance calls, as we can only inline same-instance code.
    if (IsCrossInstanceCall(target_truncated_obj, isolate_)) {
      has_non_inlineable_targets_ = true;
      return;
    }
    Tagged<Smi> target_truncated_smi = Cast<Smi>(target_truncated_obj);
    // We need to map a truncated call target back to a function index.
    // Generally there may be multiple jump tables if code spaces are far apart
    // (to ensure that direct calls can always use a near call to the closest
    // jump table).
    // However, here we are always handling call targets that are originally
    // from the `WasmDispatchTable`, whose entries are always targets pointing
    // into the main jump table, so we only need to check against that.
    WasmCodePointer handle =
        WasmCodePointer{static_cast<uint32_t>(target_truncated_smi.value())};
    Address entry = GetProcessWideWasmCodePointerTable()
                        ->GetEntrypointWithoutSignatureCheck(handle);
    wasm::WasmCode* code =
        wasm::GetWasmCodeManager()->LookupCode(nullptr, entry);
    if (!code || code->native_module() != instance_data_->native_module() ||
        code->IsAnonymous()) {
      // Was not in the main table (e.g., because it's an imported function).
      has_non_inlineable_targets_ = true;
      return;
    }
    DCHECK_EQ(code->kind(), WasmCode::Kind::kWasmFunction);
    uint32_t func_idx = code->index();
    AddCall(func_idx, count);
  }
References AddCall(), code, DCHECK_EQ, v8::internal::wasm::WasmCodePointerTable::GetEntrypointWithoutSignatureCheck(), v8::internal::wasm::GetProcessWideWasmCodePointerTable(), v8::internal::wasm::GetWasmCodeManager(), v8::internal::handle(), has_non_inlineable_targets_, instance_data_, v8::internal::wasm::IsCrossInstanceCall(), isolate_, v8::internal::compiler::kWasmFunction, v8::internal::wasm::WasmCodeManager::LookupCode(), and v8::internal::Tagged< Smi >::value().
Referenced by v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction().
AddCallRefCandidate()
void v8::internal::wasm::FeedbackMaker::AddCallRefCandidate (Tagged< WasmFuncRef > funcref, int count) [inline]
Definition at line 1368 of file module-compiler.cc.
                                                                   {
    Tagged<WasmInternalFunction> internal_function =
        Cast<WasmFuncRef>(funcref)->internal(isolate_);
    // Discard cross-instance calls, as we can only inline same-instance code.
    if (internal_function->implicit_arg() != instance_data_) {
      has_non_inlineable_targets_ = true;
      return;
    }
    // Discard imports for now.
    if (internal_function->function_index() < num_imported_functions_) {
      has_non_inlineable_targets_ = true;
      return;
    }
    AddCall(internal_function->function_index(), count);
  }
References AddCall(), has_non_inlineable_targets_, instance_data_, isolate_, and num_imported_functions_.
Referenced by v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction().
AddResult()
void v8::internal::wasm::FeedbackMaker::AddResult (CallSiteFeedback feedback) [inline]
Definition at line 1447 of file module-compiler.cc.
                                            {
    DCHECK_LT(seen_calls_, result_.size());
    result_[seen_calls_] = feedback;
    ++seen_calls_;
  }
References DCHECK_LT, result_, and seen_calls_.
Referenced by FinalizeCall().
FinalizeCall()
void v8::internal::wasm::FeedbackMaker::FinalizeCall () [inline]
Definition at line 1453 of file module-compiler.cc.
                      {
    if (is_megamorphic_) {
      if (v8_flags.trace_wasm_inlining) {
        PrintF("[function %d: call #%d: megamorphic]\n", func_index_,
               seen_calls_);
      }
      AddResult(CallSiteFeedback::CreateMegamorphic());
    } else if (cache_usage_ == 0) {
      AddResult(CallSiteFeedback{});
    } else if (cache_usage_ == 1) {
      if (v8_flags.trace_wasm_inlining) {
        PrintF("[function %d: call #%d inlineable (monomorphic)]\n",
               func_index_, seen_calls_);
      }
      AddResult(CallSiteFeedback{targets_cache_[0], counts_cache_[0]});
    } else {
      if (v8_flags.trace_wasm_inlining) {
        PrintF("[function %d: call #%d inlineable (polymorphic %d)]\n",
               func_index_, seen_calls_, cache_usage_);
      }
      DCHECK_LE(cache_usage_, kMaxPolymorphism);
      CallSiteFeedback::PolymorphicCase* polymorphic =
          new CallSiteFeedback::PolymorphicCase[cache_usage_];
      for (int i = 0; i < cache_usage_; i++) {
        polymorphic[i].function_index = targets_cache_[i];
        polymorphic[i].absolute_call_frequency = counts_cache_[i];
      }
      AddResult(CallSiteFeedback{polymorphic, cache_usage_});
    }
    result_[seen_calls_ - 1].set_has_non_inlineable_targets(
        has_non_inlineable_targets_);
    // TODO(mliedtke): Have a better representation that merges these properties
    // into one object.
    has_non_inlineable_targets_ = false;
    is_megamorphic_ = false;
    cache_usage_ = 0;
  }
References v8::internal::wasm::CallSiteFeedback::PolymorphicCase::absolute_call_frequency, AddResult(), cache_usage_, counts_cache_, v8::internal::wasm::CallSiteFeedback::CreateMegamorphic(), DCHECK_LE, func_index_, v8::internal::wasm::CallSiteFeedback::PolymorphicCase::function_index, has_non_inlineable_targets_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, is_megamorphic_, v8::internal::wasm::kMaxPolymorphism, v8::internal::PrintF(), result_, seen_calls_, targets_cache_, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction().
GetResult()
base::OwnedVector<CallSiteFeedback> v8::internal::wasm::FeedbackMaker::GetResult () && [inline]
Definition at line 1496 of file module-compiler.cc.
                                                   {
    return std::move(result_);
  }
References result_.
HasTargetCached()
bool v8::internal::wasm::FeedbackMaker::HasTargetCached (int target) [inline]
Definition at line 1441 of file module-compiler.cc.
                                   {
    auto end = targets_cache_.begin() + cache_usage_;
    DCHECK_LE(end, targets_cache_.end());
    return std::find(targets_cache_.begin(), end, target) != end;
  }
References cache_usage_, DCHECK_LE, v8::internal::compiler::end(), and targets_cache_.
Referenced by v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction().
set_has_non_inlineable_targets()
void v8::internal::wasm::FeedbackMaker::set_has_non_inlineable_targets () [inline]
Definition at line 1491 of file module-compiler.cc.
{ has_non_inlineable_targets_ = true; }
References has_non_inlineable_targets_.
Referenced by v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction().
set_megamorphic()
void v8::internal::wasm::FeedbackMaker::set_megamorphic () [inline]
Definition at line 1492 of file module-compiler.cc.
{ is_megamorphic_ = true; }
References is_megamorphic_.
Referenced by v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction().
Member Data Documentation
cache_usage_
int v8::internal::wasm::FeedbackMaker::cache_usage_ {0} [private]
Definition at line 1507 of file module-compiler.cc.
Referenced by AddCall(), FinalizeCall(), and HasTargetCached().
counts_cache_
std::array<int, kMaxPolymorphism> v8::internal::wasm::FeedbackMaker::counts_cache_ [private]
Definition at line 1509 of file module-compiler.cc.
Referenced by AddCall(), and FinalizeCall().
func_index_
const int v8::internal::wasm::FeedbackMaker::func_index_ [private]
Definition at line 1506 of file module-compiler.cc.
Referenced by FinalizeCall().
has_non_inlineable_targets_
bool v8::internal::wasm::FeedbackMaker::has_non_inlineable_targets_ = false [private]
Definition at line 1510 of file module-compiler.cc.
Referenced by AddCallIndirectCandidate(), AddCallRefCandidate(), FinalizeCall(), and set_has_non_inlineable_targets().
instance_data_
const Tagged<WasmTrustedInstanceData> v8::internal::wasm::FeedbackMaker::instance_data_ [private]
Definition at line 1502 of file module-compiler.cc.
Referenced by AddCallIndirectCandidate(), and AddCallRefCandidate().
is_megamorphic_
bool v8::internal::wasm::FeedbackMaker::is_megamorphic_ = false [private]
Definition at line 1513 of file module-compiler.cc.
Referenced by AddCall(), FinalizeCall(), and set_megamorphic().
isolate_
Isolate* const v8::internal::wasm::FeedbackMaker::isolate_ [private]
Definition at line 1501 of file module-compiler.cc.
Referenced by AddCallIndirectCandidate(), and AddCallRefCandidate().
num_imported_functions_
const int v8::internal::wasm::FeedbackMaker::num_imported_functions_ [private]
Definition at line 1505 of file module-compiler.cc.
Referenced by AddCallRefCandidate().
result_
base::OwnedVector<CallSiteFeedback> v8::internal::wasm::FeedbackMaker::result_ [private]
Definition at line 1503 of file module-compiler.cc.
Referenced by AddResult(), FinalizeCall(), and GetResult().
seen_calls_
int v8::internal::wasm::FeedbackMaker::seen_calls_ = 0 [private]
Definition at line 1504 of file module-compiler.cc.
Referenced by AddResult(), and FinalizeCall().
targets_cache_
std::array<int, kMaxPolymorphism> v8::internal::wasm::FeedbackMaker::targets_cache_ [private]
Definition at line 1508 of file module-compiler.cc.
Referenced by AddCall(), FinalizeCall(), and HasTargetCached().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc