v8::CFunction Class Reference
#include <v8-fast-api-calls.h>
Classes
class ArgUnwrap
class ArgUnwrap< R(*)(Args...)>
Public Types
enum class OverloadResolution { kImpossible
, kAtRuntime
, kAtCompileTime
 }
Public Member Functions
constexpr CFunction ()
const CTypeInfo & ReturnInfo () const
const CTypeInfo & ArgumentInfo (unsigned int index) const
unsigned int ArgumentCount () const
const void * GetAddress () const
CFunctionInfo::Int64Representation GetInt64Representation () const
const CFunctionInfo * GetTypeInfo () const
CFunction (const void *address, const CFunctionInfo *type_info)
Static Public Member Functions
template<typename F >
static CFunction Make (F *func, CFunctionInfo::Int64Representation int64_rep=CFunctionInfo::Int64Representation::kNumber)
template<typename R , typename... Args, typename R_Patch , typename... Args_Patch>
static CFunction Make (R(*func)(Args...), R_Patch(*patching_func)(Args_Patch...), CFunctionInfo::Int64Representation int64_rep=CFunctionInfo::Int64Representation::kNumber)
Private Attributes
const void * address_
const CFunctionInfo * type_info_
Detailed Description
Definition at line 419 of file v8-fast-api-calls.h.
Member Enumeration Documentation
OverloadResolution
enum v8::CFunction::OverloadResolution [strong]
Enumerator
kImpossible
kAtRuntime
kAtCompileTime
Definition at line 437 of file v8-fast-api-calls.h.
{ kImpossible, kAtRuntime, kAtCompileTime };
Constructor & Destructor Documentation
CFunction() [1/2]
constexpr v8::CFunction::CFunction () [inline], [constexpr]
Definition at line 421 of file v8-fast-api-calls.h.
: address_(nullptr), type_info_(nullptr) {}
CFunction() [2/2]
v8::CFunction::CFunction (const void * address, const CFunctionInfo * type_info)
Definition at line 11871 of file api.cc.
    : address_(address), type_info_(type_info) {
  CHECK_NOT_NULL(address_);
  CHECK_NOT_NULL(type_info_);
}
References address_, CHECK_NOT_NULL, and type_info_.
Member Function Documentation
ArgumentCount()
unsigned int v8::CFunction::ArgumentCount () const [inline]
Definition at line 429 of file v8-fast-api-calls.h.
{ return type_info_->ArgumentCount(); }
ArgumentInfo()
const CTypeInfo& v8::CFunction::ArgumentInfo (unsigned int index) const [inline]
Definition at line 425 of file v8-fast-api-calls.h.
                                                          {
    return type_info_->ArgumentInfo(index);
  }
References v8::internal::index.
GetAddress()
const void* v8::CFunction::GetAddress () const [inline]
Definition at line 431 of file v8-fast-api-calls.h.
{ return address_; }
Referenced by v8::FunctionTemplate::SetCallHandler().
GetInt64Representation()
CFunctionInfo::Int64Representation v8::CFunction::GetInt64Representation () const [inline]
Definition at line 432 of file v8-fast-api-calls.h.
                                                                  {
    return type_info_->GetInt64Representation();
  }
GetTypeInfo()
const CFunctionInfo* v8::CFunction::GetTypeInfo () const [inline]
Definition at line 435 of file v8-fast-api-calls.h.
{ return type_info_; }
Referenced by v8::FunctionTemplate::SetCallHandler().
Make() [1/2]
template<typename F >
static CFunction v8::CFunction::Make (F * func, CFunctionInfo::Int64Representation int64_rep = CFunctionInfo::Int64Representation::kNumber) [inline], [static]
Definition at line 440 of file v8-fast-api-calls.h.
                                                                     {
    CFunction result = ArgUnwrap<F*>::Make(func, int64_rep);
    result.GetInt64Representation();
    return result;
  }
References v8::base::internal::result.
Referenced by v8::Shell::CreateTestFastCApiTemplate().
Make() [2/2]
template<typename R , typename... Args, typename R_Patch , typename... Args_Patch>
static CFunction v8::CFunction::Make (R(*)(Args...) func, R_Patch(*)(Args_Patch...) patching_func, CFunctionInfo::Int64Representation int64_rep = CFunctionInfo::Int64Representation::kNumber) [inline], [static]
Definition at line 451 of file v8-fast-api-calls.h.
                                                                     {
    CFunction c_func = ArgUnwrap<R (*)(Args...)>::Make(func, int64_rep);
    static_assert(
        sizeof...(Args_Patch) == sizeof...(Args),
        "The patching function must have the same number of arguments.");
    c_func.address_ = reinterpret_cast<void*>(patching_func);
    return c_func;
  }
References address_.
ReturnInfo()
const CTypeInfo& v8::CFunction::ReturnInfo () const [inline]
Definition at line 423 of file v8-fast-api-calls.h.
{ return type_info_->ReturnInfo(); }
Member Data Documentation
address_
const void* v8::CFunction::address_ [private]
Definition at line 466 of file v8-fast-api-calls.h.
Referenced by CFunction(), and Make().
type_info_
const CFunctionInfo* v8::CFunction::type_info_ [private]
Definition at line 467 of file v8-fast-api-calls.h.
Referenced by CFunction().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-fast-api-calls.h
/mnt/V8SourceCode/src/api/api.cc