cppgc::internal::PageMemoryRegion Class Reference
#include <page-memory.h>
Public Member Functions
PageMemoryRegion (PageAllocator &, MemoryRegion)
~PageMemoryRegion ()
const MemoryRegion region () const
Address Lookup (ConstAddress address) const
PageAllocator & allocator () const
PageMemoryRegion (const PageMemoryRegion &)=delete
PageMemoryRegion & operator= (const PageMemoryRegion &)=delete
void UnprotectForTesting ()
Private Attributes
PageAllocator & allocator_
const MemoryRegion reserved_region_
Detailed Description
Definition at line 48 of file page-memory.h.
Constructor & Destructor Documentation
PageMemoryRegion() [1/2]
cppgc::internal::PageMemoryRegion::PageMemoryRegion (PageAllocator & allocator, MemoryRegion reserved_region)
Definition at line 85 of file page-memory.cc.
    : allocator_(allocator), reserved_region_(reserved_region) {}
 PageMemoryRegion()
cppgc::internal::PageMemoryRegion::~PageMemoryRegion ()
Definition at line 89 of file page-memory.cc.
                                    {
  FreeMemoryRegion(allocator_, region());
}
References allocator_, cppgc::internal::anonymous_namespace{page-memory.cc}::FreeMemoryRegion(), and region().
PageMemoryRegion() [2/2]
cppgc::internal::PageMemoryRegion::PageMemoryRegion (const PageMemoryRegion &) [delete]
Member Function Documentation
allocator()
PageAllocator& cppgc::internal::PageMemoryRegion::allocator () const [inline]
Definition at line 62 of file page-memory.h.
{ return allocator_; }
Referenced by cppgc::internal::NormalPageMemoryPool::Take().
Lookup()
Address cppgc::internal::PageMemoryRegion::Lookup (ConstAddress address) const [inline]
Definition at line 57 of file page-memory.h.
                                                    {
    const MemoryRegion memory_region = region();
    return memory_region.Contains(address) ? memory_region.base() : nullptr;
  }
References cppgc::internal::MemoryRegion::base(), and cppgc::internal::MemoryRegion::Contains().
Referenced by cppgc::internal::PageBackend::Lookup().
operator=()
PageMemoryRegion& cppgc::internal::PageMemoryRegion::operator= (const PageMemoryRegion &) [delete]
region()
const MemoryRegion cppgc::internal::PageMemoryRegion::region () const [inline]
Definition at line 53 of file page-memory.h.
{ return reserved_region_; }
Referenced by cppgc::internal::PageMemoryRegionTree::Add(), cppgc::internal::NormalPageMemoryPool::Add(), cppgc::internal::PageMemoryRegionTree::Remove(), cppgc::internal::NormalPageMemoryPool::Take(), UnprotectForTesting(), and ~PageMemoryRegion().
UnprotectForTesting()
void cppgc::internal::PageMemoryRegion::UnprotectForTesting ()
Definition at line 93 of file page-memory.cc.
                                           {
  CHECK(TryUnprotect(allocator_, region()));
}
References allocator_, CHECK, region(), and cppgc::internal::anonymous_namespace{page-memory.cc}::TryUnprotect().
Member Data Documentation
allocator_
PageAllocator& cppgc::internal::PageMemoryRegion::allocator_ [private]
Definition at line 71 of file page-memory.h.
Referenced by UnprotectForTesting(), and ~PageMemoryRegion().
reserved_region_
const MemoryRegion cppgc::internal::PageMemoryRegion::reserved_region_ [private]
Definition at line 72 of file page-memory.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/page-memory.h
/mnt/V8SourceCode/src/heap/cppgc/page-memory.cc