v8::internal::compiler::NativeContextRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< NativeContext > object () const
MapRef GetFunctionMapFromIndex (JSHeapBroker *broker, int index) const
MapRef GetInitialJSArrayMap (JSHeapBroker *broker, ElementsKind kind) const
OptionalJSFunctionRef GetConstructorFunction (JSHeapBroker *broker, MapRef map) const
bool GlobalIsDetached (JSHeapBroker *broker) const
Detailed Description
Definition at line 796 of file heap-refs.h.
Member Function Documentation
GetConstructorFunction()
OptionalJSFunctionRef v8::internal::compiler::NativeContextRef::GetConstructorFunction (JSHeapBroker * broker, MapRef map) const
Definition at line 1958 of file heap-refs.cc.
                                            {
  CHECK(map.IsPrimitiveMap());
  switch (map.constructor_function_index()) {
    case Map::kNoConstructorFunctionIndex:
      return std::nullopt;
    case Context::BIGINT_FUNCTION_INDEX:
      return bigint_function(broker);
    case Context::BOOLEAN_FUNCTION_INDEX:
      return boolean_function(broker);
    case Context::NUMBER_FUNCTION_INDEX:
      return number_function(broker);
    case Context::STRING_FUNCTION_INDEX:
      return string_function(broker);
    case Context::SYMBOL_FUNCTION_INDEX:
      return symbol_function(broker);
    default:
      UNREACHABLE();
  }
}
References broker(), CHECK, v8::internal::compiler::MapRef::constructor_function_index(), v8::internal::compiler::MapRef::IsPrimitiveMap(), v8::internal::Map::kNoConstructorFunctionIndex, v8::internal::compiler::HeapObjectRef::map(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), and v8::internal::compiler::CompilationDependencies::DependOnStablePrototypeChain().
GetFunctionMapFromIndex()
MapRef v8::internal::compiler::NativeContextRef::GetFunctionMapFromIndex (JSHeapBroker * broker, int index) const
Definition at line 1921 of file heap-refs.cc.
                                                                  {
  DCHECK_GE(index, Context::FIRST_FUNCTION_MAP_INDEX);
  DCHECK_LE(index, Context::LAST_FUNCTION_MAP_INDEX);
  CHECK_LT(index, object()->length());
  return MakeRefAssumeMemoryFence(
      broker, Cast<Map>(object()->GetNoCell(index, kAcquireLoad)));
}
References broker(), CHECK_LT, DCHECK_GE, DCHECK_LE, v8::internal::Context::FIRST_FUNCTION_MAP_INDEX, v8::internal::index, v8::kAcquireLoad, v8::internal::Context::LAST_FUNCTION_MAP_INDEX, v8::internal::length, and v8::internal::compiler::MakeRefAssumeMemoryFence().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure().
GetInitialJSArrayMap()
MapRef v8::internal::compiler::NativeContextRef::GetInitialJSArrayMap (JSHeapBroker * broker, ElementsKind kind) const
Definition at line 1930 of file heap-refs.cc.
                                                                       {
  switch (kind) {
    case PACKED_SMI_ELEMENTS:
      return js_array_packed_smi_elements_map(broker);
    case HOLEY_SMI_ELEMENTS:
      return js_array_holey_smi_elements_map(broker);
    case PACKED_DOUBLE_ELEMENTS:
      return js_array_packed_double_elements_map(broker);
    case HOLEY_DOUBLE_ELEMENTS:
      return js_array_holey_double_elements_map(broker);
    case PACKED_ELEMENTS:
      return js_array_packed_elements_map(broker);
    case HOLEY_ELEMENTS:
      return js_array_holey_elements_map(broker);
    default:
      UNREACHABLE();
  }
}
References broker(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralArray().
GlobalIsDetached()
bool v8::internal::compiler::NativeContextRef::GlobalIsDetached (JSHeapBroker * broker) const
Definition at line 2512 of file heap-refs.cc.
                                                                  {
  ObjectRef proxy_proto =
      global_proxy_object(broker).map(broker).prototype(broker);
  return !proxy_proto.equals(global_object(broker));
}
References broker().
object()
IndirectHandle<NativeContext> v8::internal::compiler::NativeContextRef::object () const
Referenced by v8::internal::maglev::MaglevAssembler::AssertElidedWriteBarrier(), v8::internal::maglev::anonymous_namespace{maglev-ir-x64.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-riscv.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-s390.cc}::HandleInterruptsAndTiering(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessGraph(), and v8::internal::maglev::MaglevAssembler::StringCharCodeOrCodePointAt().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc