v8::internal::compiler::SimplifyTFLoops Class Reference
#include <simplify-tf-loops.h>
Public Member Functions
SimplifyTFLoops (Editor *editor, MachineGraph *mcgraph)
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Attributes
MachineGraph *const mcgraph_
Additional Inherited Members
Detailed Description
Definition at line 16 of file simplify-tf-loops.h.
Constructor & Destructor Documentation
SimplifyTFLoops()
v8::internal::compiler::SimplifyTFLoops::SimplifyTFLoops (Editor * editor, MachineGraph * mcgraph) [inline]
Definition at line 18 of file simplify-tf-loops.h.
      : AdvancedReducer(editor), mcgraph_(mcgraph) {}
Member Function Documentation
Reduce()
Reduction v8::internal::compiler::SimplifyTFLoops::Reduce (Node * node) [final], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 13 of file simplify-tf-loops.cc.
                                            {
  if (node->opcode() != IrOpcode::kLoop) return NoChange();
  if (node->InputCount() <= 2) return NoChange();
  Node* new_loop = mcgraph_->graph()->NewNode(mcgraph_->common()->Loop(2),
                                              node->InputAt(0), node);
  node->RemoveInput(0);
  NodeProperties::ChangeOp(node, mcgraph_->common()->Merge(node->InputCount()));
  base::SmallVector<Edge, 4> control_uses;
  for (Edge edge : node->use_edges()) {
    Node* use = edge.from();
    if (!NodeProperties::IsPhi(use)) {
      control_uses.emplace_back(edge);
      continue;
    }
    Node* dominating_input = use->InputAt(0);
    use->RemoveInput(0);
    NodeProperties::ChangeOp(
        use, use->opcode() == IrOpcode::kPhi
                 ? mcgraph_->common()->Phi(PhiRepresentationOf(use->op()),
                                           use->InputCount() - 1)
                 : mcgraph_->common()->EffectPhi(use->InputCount() - 1));
    Node* new_phi = mcgraph_->graph()->NewNode(
        use->opcode() == IrOpcode::kPhi
            ? mcgraph_->common()->Phi(PhiRepresentationOf(use->op()), 2)
            : mcgraph_->common()->EffectPhi(2),
        dominating_input, use, new_loop);
    ReplaceWithValue(use, new_phi, new_phi, new_phi);
    // Restore the use <- new_phi edge we just broke.
    new_phi->ReplaceInput(1, use);
  }
  for (Edge edge : control_uses) {
    if (edge.from() != new_loop) {
      edge.from()->ReplaceInput(edge.index(), new_loop);
    }
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::MachineGraph::common(), v8::internal::compiler::CommonOperatorBuilder::EffectPhi(), v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::internal::compiler::MachineGraph::graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::NodeProperties::IsPhi(), v8::internal::compiler::CommonOperatorBuilder::Loop(), mcgraph_, v8::internal::compiler::CommonOperatorBuilder::Merge(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::CommonOperatorBuilder::Phi(), v8::internal::compiler::PhiRepresentationOf(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), use(), and v8::internal::compiler::Node::use_edges().
reducer_name()
const char* v8::internal::compiler::SimplifyTFLoops::reducer_name () const [inline], [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 21 of file simplify-tf-loops.h.
{ return "SimplifyTFLoops"; }
Member Data Documentation
mcgraph_
MachineGraph* const v8::internal::compiler::SimplifyTFLoops::mcgraph_ [private]
Definition at line 26 of file simplify-tf-loops.h.
Referenced by Reduce().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/simplify-tf-loops.h
/mnt/V8SourceCode/src/compiler/turboshaft/simplify-tf-loops.cc