v8::internal::int31_t Class Reference
#include <globals.h>
Public Member Functions
constexpr int31_t ()
constexpr int31_t (int value)
int31_t & operator= (int value)
int32_t value () const
operator int32_t () const
Private Attributes
int32_t value_
Detailed Description
Definition at line 2856 of file globals.h.
Constructor & Destructor Documentation
int31_t() [1/2]
constexpr v8::internal::int31_t::int31_t () [inline], [constexpr]
Definition at line 2858 of file globals.h.
: value_(0) {}
int31_t() [2/2]
constexpr v8::internal::int31_t::int31_t (int value) [inline], [constexpr]
Definition at line 2859 of file globals.h.
                               : value_(value) { // NOLINT(runtime/explicit)
    DCHECK_EQ((value & 0x80000000) != 0, (value & 0x40000000) != 0);
  }
References DCHECK_EQ, and value().
Member Function Documentation
operator int32_t()
v8::internal::int31_t::operator int32_t () const [inline]
Definition at line 2868 of file globals.h.
{ return value_; }
References value_.
operator=()
int31_t& v8::internal::int31_t::operator= (int value) [inline]
Definition at line 2862 of file globals.h.
                                {
    DCHECK_EQ((value & 0x80000000) != 0, (value & 0x40000000) != 0);
    value_ = value;
    return *this;
  }
References DCHECK_EQ, value(), and value_.
value()
int32_t v8::internal::int31_t::value () const [inline]
Definition at line 2867 of file globals.h.
{ return value_; }
References value_.
Referenced by int31_t(), and operator=().
Member Data Documentation
value_
int32_t v8::internal::int31_t::value_ [private]
Definition at line 2871 of file globals.h.
Referenced by operator int32_t(), operator=(), and value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/common/globals.h