v8::internal::TieringManager Class Reference
#include <tiering-manager.h>
Classes
class OnInterruptTickScope
Public Member Functions
TieringManager (Isolate *isolate)
void OnInterruptTick (DirectHandle< JSFunction > function, CodeKind code_kind)
void NotifyICChanged (Tagged< FeedbackVector > vector)
void RequestOsrAtNextOpportunity (Tagged< JSFunction > function)
void MarkForTurboFanOptimization (Tagged< JSFunction > function)
Static Public Member Functions
static int InterruptBudgetFor (Isolate *isolate, Tagged< JSFunction > function, std::optional< CodeKind > override_active_tier={})
Private Member Functions
void MaybeOptimizeFrame (Tagged< JSFunction > function, CodeKind code_kind)
OptimizationDecision ShouldOptimize (Tagged< FeedbackVector > feedback_vector, CodeKind code_kind)
void Optimize (Tagged< JSFunction > function, OptimizationDecision decision)
void Baseline (Tagged< JSFunction > function, OptimizationReason reason)
Private Attributes
Isolate *const isolate_
Detailed Description
Definition at line 27 of file tiering-manager.h.
Constructor & Destructor Documentation
TieringManager()
v8::internal::TieringManager::TieringManager (Isolate * isolate) [inline], [explicit]
Definition at line 29 of file tiering-manager.h.
: isolate_(isolate) {}
Member Function Documentation
Baseline()
void v8::internal::TieringManager::Baseline (Tagged< JSFunction > function, OptimizationReason reason) [private]
InterruptBudgetFor()
int v8::internal::TieringManager::InterruptBudgetFor (Isolate * isolate, Tagged< JSFunction > function, std::optional< CodeKind > override_active_tier = {}) [static]
Definition at line 228 of file tiering-manager.cc.
                                                {
  DCHECK(function->shared()->is_compiled());
  const int bytecode_length =
      function->shared()->GetBytecodeArray(isolate)->length();
  if (FirstTimeTierUpToSparkplug(isolate, function)) {
    return bytecode_length * v8_flags.invocation_count_for_feedback_allocation;
  }
  DCHECK(function->has_feedback_vector());
  if (bytecode_length > v8_flags.max_optimized_bytecode_size) {
    // Decrease times of interrupt budget underflow, the reason of not setting
    // to INT_MAX is the interrupt budget may overflow when doing add
    // operation for forward jump.
    return INT_MAX / 2;
  }
  return ::i::InterruptBudgetFor(
      isolate,
      override_active_tier ? override_active_tier
                           : function->GetActiveTier(isolate),
      function, function->shared()->cached_tiering_decision(), bytecode_length);
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{tiering-manager.cc}::FirstTimeTierUpToSparkplug(), v8::internal::anonymous_namespace{tiering-manager.cc}::InterruptBudgetFor(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{debug-coverage.cc}::CollectAndMaybeResetCounts(), and v8::internal::JSFunction::SetInterruptBudget().
MarkForTurboFanOptimization()
void v8::internal::TieringManager::MarkForTurboFanOptimization (Tagged< JSFunction > function)
Definition at line 150 of file tiering-manager.cc.
                                                                            {
  Optimize(function, OptimizationDecision::TurbofanHotAndStable());
}
References Optimize(), and v8::internal::OptimizationDecision::TurbofanHotAndStable().
MaybeOptimizeFrame()
void v8::internal::TieringManager::MaybeOptimizeFrame (Tagged< JSFunction > function, CodeKind code_kind) [private]
Definition at line 300 of file tiering-manager.cc.
                                                                    {
  const bool tiering_in_progress = function->tiering_in_progress();
  const bool osr_in_progress =
      function->feedback_vector()->osr_tiering_in_progress();
  // Attenzione! Update this constant in case the condition below changes.
  static_assert(kTieringStateInProgressBlocksTierup);
  if (V8_UNLIKELY(tiering_in_progress) || V8_UNLIKELY(osr_in_progress)) {
    if (v8_flags.concurrent_recompilation_front_running &&
        ((tiering_in_progress && function->ActiveTierIsMaglev(isolate_)) ||
         (osr_in_progress &&
          function->feedback_vector()->maybe_has_optimized_osr_code()))) {
      // TODO(olivf): In the case of Maglev we tried a queue with two
      // priorities, but it seems not actually beneficial. More
      // investigation is needed.
      isolate_->IncreaseConcurrentOptimizationPriority(CodeKind::TURBOFAN_JS,
                                                       function->shared());
    }
    // Note: This effectively disables further tiering actions (e.g. OSR, or
    // tiering up into Maglev) for the function while it is being compiled.
    TraceInOptimizationQueue(function, current_code_kind);
    return;
  }
  if (V8_UNLIKELY(v8_flags.testing_d8_test_runner) &&
      ManualOptimizationTable::IsMarkedForManualOptimization(isolate_,
                                                             function)) {
    TraceHeuristicOptimizationDisallowed(function);
    return;
  }
  if (V8_UNLIKELY(function->shared()->optimization_disabled(
          current_code_kind == CodeKind::MAGLEV ? CodeKind::TURBOFAN_JS
                                                : CodeKind::MAGLEV))) {
    return;
  }
  if (V8_UNLIKELY(v8_flags.always_osr)) {
    TryRequestOsrAtNextOpportunity(isolate_, function);
    // Continue below and do a normal optimized compile as well.
  }
  const bool maglev_osr = maglev::IsMaglevOsrEnabled();
  const CodeKinds available_kinds = function->GetAvailableCodeKinds(isolate_);
  const bool waiting_for_tierup =
      (current_code_kind < CodeKind::TURBOFAN_JS &&
       (available_kinds & CodeKindFlag::TURBOFAN_JS)) ||
      (maglev_osr && current_code_kind < CodeKind::MAGLEV &&
       (available_kinds & CodeKindFlag::MAGLEV));
  // Baseline OSR uses a separate mechanism and must not be considered here,
  // therefore we limit to kOptimizedJSFunctionCodeKindsMask.
  if (function->IsOptimizationRequested(isolate_) || waiting_for_tierup) {
    if (V8_UNLIKELY(maglev_osr && current_code_kind == CodeKind::MAGLEV &&
                    (!v8_flags.osr_from_maglev ||
                     isolate_->EfficiencyModeEnabledForTiering() ||
                     isolate_->BatterySaverModeEnabled()))) {
      return;
    }
    // OSR kicks in only once we've previously decided to tier up, but we are
    // still in a lower-tier frame (this implies a long-running loop).
    TryIncrementOsrUrgency(isolate_, function);
    // Return unconditionally and don't run through the optimization decision
    // again; we've already decided to tier up previously.
    return;
  }
  const std::optional<CodeKind> existing_request =
      function->GetRequestedOptimizationIfAny(isolate_);
  DCHECK(existing_request != CodeKind::TURBOFAN_JS);
  DCHECK(!function->HasAvailableCodeKind(isolate_, CodeKind::TURBOFAN_JS));
  OptimizationDecision d =
      ShouldOptimize(function->feedback_vector(), current_code_kind);
  // We might be stuck in a baseline frame that wants to tier up to Maglev, but
  // is in a loop, and can't OSR, because Maglev doesn't have OSR. Allow it to
  // skip over Maglev by re-checking ShouldOptimize as if we were in Maglev.
  if (V8_UNLIKELY(!isolate_->EfficiencyModeEnabledForTiering() && !maglev_osr &&
                  d.should_optimize() && d.code_kind == CodeKind::MAGLEV)) {
    bool is_marked_for_maglev_optimization =
        existing_request == CodeKind::MAGLEV ||
        (available_kinds & CodeKindFlag::MAGLEV);
    if (is_marked_for_maglev_optimization) {
      d = ShouldOptimize(function->feedback_vector(), CodeKind::MAGLEV);
    }
  }
  if (V8_UNLIKELY(isolate_->EfficiencyModeEnabledForTiering() &&
                  d.code_kind != CodeKind::TURBOFAN_JS)) {
    d.concurrency_mode = ConcurrencyMode::kSynchronous;
  }
  if (d.should_optimize()) Optimize(function, d);
}
References v8::internal::Isolate::BatterySaverModeEnabled(), v8::internal::OptimizationDecision::code_kind, v8::internal::OptimizationDecision::concurrency_mode, v8::internal::DCHECK(), v8::internal::Isolate::EfficiencyModeEnabledForTiering(), v8::internal::Isolate::IncreaseConcurrentOptimizationPriority(), v8::internal::maglev::IsMaglevOsrEnabled(), v8::internal::ManualOptimizationTable::IsMarkedForManualOptimization(), isolate_, v8::internal::kSynchronous, v8::internal::kTieringStateInProgressBlocksTierup, Optimize(), v8::internal::OptimizationDecision::should_optimize(), ShouldOptimize(), v8::internal::anonymous_namespace{tiering-manager.cc}::TraceHeuristicOptimizationDisallowed(), v8::internal::anonymous_namespace{tiering-manager.cc}::TraceInOptimizationQueue(), v8::internal::anonymous_namespace{tiering-manager.cc}::TryIncrementOsrUrgency(), v8::internal::anonymous_namespace{tiering-manager.cc}::TryRequestOsrAtNextOpportunity(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by OnInterruptTick().
NotifyICChanged()
void v8::internal::TieringManager::NotifyICChanged (Tagged< FeedbackVector > vector)
Definition at line 457 of file tiering-manager.cc.
                                                                  {
  CodeKind code_kind = vector->shared_function_info()->HasBaselineCode()
                           ? CodeKind::BASELINE
                           : CodeKind::INTERPRETED_FUNCTION;
#ifndef V8_ENABLE_LEAPTIERING
  if (vector->has_optimized_code()) {
    code_kind = vector->optimized_code(isolate_)->kind();
  }
#endif // !V8_ENABLE_LEAPTIERING
  if (code_kind == CodeKind::INTERPRETED_FUNCTION &&
      CanCompileWithBaseline(isolate_, vector->shared_function_info()) &&
      vector->shared_function_info()->cached_tiering_decision() ==
          CachedTieringDecision::kPending) {
    // Don't delay tier-up if we haven't tiered up to baseline yet, but will --
    // baseline code is feedback independent.
    return;
  }
  OptimizationDecision decision = ShouldOptimize(vector, code_kind);
  if (decision.should_optimize()) {
    Tagged<SharedFunctionInfo> shared = vector->shared_function_info();
    int bytecode_length = shared->GetBytecodeArray(isolate_)->length();
    Tagged<FeedbackCell> cell = vector->parent_feedback_cell();
    int invocations = v8_flags.minimum_invocations_after_ic_update;
    int bytecodes = std::min(bytecode_length, (kMaxInt >> 1) / invocations);
    int new_budget = invocations * bytecodes;
    int current_budget = cell->interrupt_budget();
    if (v8_flags.profile_guided_optimization &&
        shared->cached_tiering_decision() <=
            CachedTieringDecision::kEarlySparkplug) {
      DCHECK_LT(v8_flags.invocation_count_for_early_optimization,
                FeedbackVector::kInvocationCountBeforeStableDeoptSentinel);
      if (vector->invocation_count_before_stable() <
          v8_flags.invocation_count_for_early_optimization) {
        // Record how many invocation count were consumed before the last IC
        // change.
        int new_invocation_count_before_stable;
        if (vector->interrupt_budget_reset_by_ic_change()) {
          // Initial interrupt budget is
          // v8_flags.minimum_invocations_after_ic_update * bytecodes
          int new_consumed_budget = new_budget - current_budget;
          new_invocation_count_before_stable =
              vector->invocation_count_before_stable(kRelaxedLoad) +
              std::ceil(static_cast<float>(new_consumed_budget) / bytecodes);
        } else {
          // Initial interrupt budget is
          // v8_flags.invocation_count_for_{maglev|turbofan} * bytecodes
          int total_consumed_budget =
              (maglev::IsMaglevEnabled()
                   ? v8_flags.invocation_count_for_maglev
                   : v8_flags.invocation_count_for_turbofan) *
                  bytecodes -
              current_budget;
          new_invocation_count_before_stable =
              std::ceil(static_cast<float>(total_consumed_budget) / bytecodes);
        }
        if (new_invocation_count_before_stable >=
            v8_flags.invocation_count_for_early_optimization) {
          vector->set_invocation_count_before_stable(
              v8_flags.invocation_count_for_early_optimization, kRelaxedStore);
          shared->set_cached_tiering_decision(CachedTieringDecision::kNormal);
        } else {
          vector->set_invocation_count_before_stable(
              new_invocation_count_before_stable, kRelaxedStore);
        }
      } else {
        shared->set_cached_tiering_decision(CachedTieringDecision::kNormal);
      }
    }
    if (!v8_flags.profile_guided_optimization ||
        ShouldResetInterruptBudgetByICChange(
            shared->cached_tiering_decision())) {
      if (new_budget > current_budget) {
        if (v8_flags.trace_opt_verbose) {
          PrintF("[delaying optimization of %s, IC changed]\n",
                 shared->DebugNameCStr().get());
        }
        vector->set_interrupt_budget_reset_by_ic_change(true);
        cell->set_interrupt_budget(new_budget);
      }
    }
  }
}
References v8::internal::CanCompileWithBaseline(), DCHECK_LT, v8::internal::maglev::IsMaglevEnabled(), isolate_, v8::internal::kEarlySparkplug, v8::internal::FeedbackVector::kInvocationCountBeforeStableDeoptSentinel, v8::internal::kMaxInt, v8::internal::kNormal, v8::internal::kPending, v8::kRelaxedLoad, v8::kRelaxedStore, v8::internal::PrintF(), v8::internal::OptimizationDecision::should_optimize(), ShouldOptimize(), v8::internal::anonymous_namespace{tiering-manager.cc}::ShouldResetInterruptBudgetByICChange(), and v8::internal::v8_flags.
Referenced by v8::internal::IC::OnFeedbackChanged().
OnInterruptTick()
void v8::internal::TieringManager::OnInterruptTick (DirectHandle< JSFunction > function, CodeKind code_kind)
Definition at line 548 of file tiering-manager.cc.
                                                         {
  IsCompiledScope is_compiled_scope(
      function->shared()->is_compiled_scope(isolate_));
  // Remember whether the function had a vector at this point. This is
  // relevant later since the configuration 'Ignition without a vector' can be
  // considered a tier on its own. We begin tiering up to tiers higher than
  // Sparkplug only when reaching this point *with* a feedback vector.
  const bool had_feedback_vector = function->has_feedback_vector();
  const bool first_time_tiered_up_to_sparkplug =
      FirstTimeTierUpToSparkplug(isolate_, *function);
  // We don't want to trigger GC in the middle of OSR, so do not build a
  // baseline code for such case.
  const bool maybe_had_optimized_osr_code =
      had_feedback_vector &&
      function->feedback_vector()->maybe_has_optimized_osr_code();
  const bool compile_sparkplug =
      CanCompileWithBaseline(isolate_, function->shared()) &&
      function->ActiveTierIsIgnition(isolate_) && !maybe_had_optimized_osr_code;
  // Ensure that the feedback vector has been allocated.
  if (!had_feedback_vector) {
    if (compile_sparkplug && function->shared()->cached_tiering_decision() ==
                                 CachedTieringDecision::kPending) {
      // Mark the function as compiled with sparkplug before the feedback
      // vector is created to initialize the interrupt budget for the next
      // tier.
      function->shared()->set_cached_tiering_decision(
          CachedTieringDecision::kEarlySparkplug);
    }
    JSFunction::CreateAndAttachFeedbackVector(isolate_, function,
                                              &is_compiled_scope);
    DCHECK(is_compiled_scope.is_compiled());
    // Also initialize the invocation count here. This is only really needed
    // for OSR. When we OSR functions with lazy feedback allocation we want to
    // have a non zero invocation count so we can inline functions.
    function->feedback_vector()->set_invocation_count(1, kRelaxedStore);
  }
  DCHECK(function->has_feedback_vector());
  DCHECK(function->shared()->is_compiled());
  DCHECK(function->shared()->HasBytecodeArray());
  // TODO(jgruber): Consider integrating this into a linear tiering system
  // controlled by TieringState in which the order is always
  // Ignition-Sparkplug-Turbofan, and only a single tierup is requested at
  // once.
  // It's unclear whether this is possible and/or makes sense - for example,
  // batching compilation can introduce arbitrary latency between the SP
  // compile request and fulfillment, which doesn't work with strictly linear
  // tiering.
  if (compile_sparkplug) {
#ifdef V8_ENABLE_SPARKPLUG
    if (v8_flags.baseline_batch_compilation) {
      isolate_->baseline_batch_compiler()->EnqueueFunction(function);
    } else {
      IsCompiledScope inner_is_compiled_scope(
          function->shared()->is_compiled_scope(isolate_));
      Compiler::CompileBaseline(isolate_, function, Compiler::CLEAR_EXCEPTION,
                                &inner_is_compiled_scope);
    }
#else
    UNREACHABLE();
#endif // V8_ENABLE_SPARKPLUG
  }
  // We only tier up beyond sparkplug if we already had a feedback vector.
  if (first_time_tiered_up_to_sparkplug) {
    // If we didn't have a feedback vector, the interrupt budget has already
    // been set by JSFunction::CreateAndAttachFeedbackVector, so no need to
    // set it again.
    if (had_feedback_vector) {
      if (function->shared()->cached_tiering_decision() ==
          CachedTieringDecision::kPending) {
        function->shared()->set_cached_tiering_decision(
            CachedTieringDecision::kEarlySparkplug);
      }
      function->SetInterruptBudget(isolate_, BudgetModification::kRaise);
    }
    return;
  }
  // Don't tier up if Turbofan is disabled.
  // TODO(jgruber): Update this for a multi-tier world.
  if (V8_UNLIKELY(!isolate_->use_optimizer())) {
    function->SetInterruptBudget(isolate_, BudgetModification::kRaise);
    return;
  }
  // --- We've decided to proceed for now. ---
  DisallowGarbageCollection no_gc;
  OnInterruptTickScope scope;
  Tagged<JSFunction> function_obj = *function;
  MaybeOptimizeFrame(function_obj, code_kind);
  // Make sure to set the interrupt budget after maybe starting an optimization,
  // so that the interrupt budget size takes into account tiering state.
  DCHECK(had_feedback_vector);
  function->SetInterruptBudget(isolate_, BudgetModification::kRaise);
}
References v8::internal::CanCompileWithBaseline(), v8::internal::Compiler::CLEAR_EXCEPTION, v8::internal::Compiler::CompileBaseline(), v8::internal::JSFunction::CreateAndAttachFeedbackVector(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{tiering-manager.cc}::FirstTimeTierUpToSparkplug(), v8::internal::IsCompiledScope::is_compiled(), isolate_, v8::internal::kEarlySparkplug, v8::internal::kPending, v8::internal::kRaise, v8::kRelaxedStore, MaybeOptimizeFrame(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::UNREACHABLE(), v8::internal::Isolate::use_optimizer(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::anonymous_namespace{runtime-internal.cc}::BytecodeBudgetInterrupt(), and v8::internal::anonymous_namespace{runtime-internal.cc}::BytecodeBudgetInterruptWithStackCheck().
Optimize()
void v8::internal::TieringManager::Optimize (Tagged< JSFunction > function, OptimizationDecision decision) [private]
Definition at line 143 of file tiering-manager.cc.
                                                      {
  DCHECK(d.should_optimize());
  TraceRecompile(isolate_, function, d);
  function->RequestOptimization(isolate_, d.code_kind, d.concurrency_mode);
}
References v8::internal::OptimizationDecision::code_kind, v8::internal::OptimizationDecision::concurrency_mode, v8::internal::DCHECK(), isolate_, v8::internal::OptimizationDecision::should_optimize(), and v8::internal::anonymous_namespace{tiering-manager.cc}::TraceRecompile().
Referenced by MarkForTurboFanOptimization(), and MaybeOptimizeFrame().
RequestOsrAtNextOpportunity()
void v8::internal::TieringManager::RequestOsrAtNextOpportunity (Tagged< JSFunction > function)
Definition at line 295 of file tiering-manager.cc.
                                                                            {
  DisallowGarbageCollection no_gc;
  TryRequestOsrAtNextOpportunity(isolate_, function);
}
References isolate_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::anonymous_namespace{tiering-manager.cc}::TryRequestOsrAtNextOpportunity().
ShouldOptimize()
OptimizationDecision v8::internal::TieringManager::ShouldOptimize (Tagged< FeedbackVector > feedback_vector, CodeKind code_kind) [private]
Definition at line 395 of file tiering-manager.cc.
                                                                        {
  Tagged<SharedFunctionInfo> shared = feedback_vector->shared_function_info();
  if (current_code_kind == CodeKind::TURBOFAN_JS) {
    return OptimizationDecision::DoNotOptimize();
  }
  if (TiersUpToMaglev(current_code_kind) &&
      shared->PassesFilter(v8_flags.maglev_filter) &&
      !shared->maglev_compilation_failed()) {
    if (v8_flags.profile_guided_optimization &&
        shared->cached_tiering_decision() ==
            CachedTieringDecision::kEarlyTurbofan) {
      return OptimizationDecision::TurbofanHotAndStable();
    }
    return OptimizationDecision::Maglev();
  }
  if (V8_UNLIKELY(!v8_flags.turbofan ||
                  !shared->PassesFilter(v8_flags.turbo_filter) ||
                  (v8_flags.efficiency_mode_disable_turbofan &&
                   isolate_->EfficiencyModeEnabledForTiering()) ||
                  isolate_->BatterySaverModeEnabled())) {
    return OptimizationDecision::DoNotOptimize();
  }
  if (isolate_->EfficiencyModeEnabledForTiering() &&
      v8_flags.efficiency_mode_delay_turbofan &&
      feedback_vector->invocation_count() <
          v8_flags.efficiency_mode_delay_turbofan) {
    return OptimizationDecision::DoNotOptimize();
  }
  Tagged<BytecodeArray> bytecode = shared->GetBytecodeArray(isolate_);
  if (bytecode->length() > v8_flags.max_optimized_bytecode_size) {
    return OptimizationDecision::DoNotOptimize();
  }
  return OptimizationDecision::TurbofanHotAndStable();
}
References v8::internal::Isolate::BatterySaverModeEnabled(), v8::internal::OptimizationDecision::DoNotOptimize(), v8::internal::Isolate::EfficiencyModeEnabledForTiering(), isolate_, v8::internal::kEarlyTurbofan, v8::internal::OptimizationDecision::Maglev(), v8::internal::anonymous_namespace{tiering-manager.cc}::TiersUpToMaglev(), v8::internal::OptimizationDecision::TurbofanHotAndStable(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by MaybeOptimizeFrame(), and NotifyICChanged().
Member Data Documentation
isolate_
Isolate* const v8::internal::TieringManager::isolate_ [private]
Definition at line 67 of file tiering-manager.h.
Referenced by MaybeOptimizeFrame(), NotifyICChanged(), OnInterruptTick(), Optimize(), RequestOsrAtNextOpportunity(), and ShouldOptimize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/tiering-manager.h
/mnt/V8SourceCode/src/execution/tiering-manager.cc