v8::internal::GlobalBackingStoreRegistry Class Reference
#include <backing-store.h>
Static Public Member Functions
static void Register (std::shared_ptr< BackingStore > backing_store)
Static Private Member Functions
static void Unregister (BackingStore *backing_store)
static void AddSharedWasmMemoryObject (Isolate *isolate, BackingStore *backing_store, DirectHandle< WasmMemoryObject > memory_object)
static void Purge (Isolate *isolate)
static void BroadcastSharedWasmMemoryGrow (Isolate *isolate, const BackingStore *backing_store)
static void UpdateSharedWasmMemoryObjects (Isolate *isolate)
Friends
class BackingStore
Detailed Description
Definition at line 285 of file backing-store.h.
Member Function Documentation
AddSharedWasmMemoryObject()
static void v8::internal::GlobalBackingStoreRegistry::AddSharedWasmMemoryObject (Isolate * isolate, BackingStore * backing_store, DirectHandle< WasmMemoryObject > memory_object) [static], [private]
BroadcastSharedWasmMemoryGrow()
static void v8::internal::GlobalBackingStoreRegistry::BroadcastSharedWasmMemoryGrow (Isolate * isolate, const BackingStore * backing_store) [static], [private]
Purge()
void v8::internal::GlobalBackingStoreRegistry::Purge (Isolate * isolate) [static], [private]
Definition at line 802 of file backing-store.cc.
                                                       {
  // We need to keep a reference to all backing stores that are inspected
  // in the purging loop below. Otherwise, we might get a deadlock
  // if the temporary backing store reference created in the loop is
  // the last reference. In that case the destructor of the backing store
  // may try to take the &impl->mutex_ in order to unregister itself.
  std::vector<std::shared_ptr<BackingStore>> prevent_destruction_under_lock;
  GlobalBackingStoreRegistryImpl* impl = GetGlobalBackingStoreRegistryImpl();
  base::MutexGuard scope_lock(&impl->mutex_);
  // Purge all entries in the map that refer to the given isolate.
  for (auto& entry : impl->map_) {
    auto backing_store = entry.second.lock();
    prevent_destruction_under_lock.emplace_back(backing_store);
    if (!backing_store) continue; // skip entries where weak ptr is null
    CHECK(backing_store->is_wasm_memory());
    if (!backing_store->is_shared()) continue; // skip non-shared memory
    SharedWasmMemoryData* shared_data =
        backing_store->get_shared_wasm_memory_data();
    // Remove this isolate from the isolates list.
    std::vector<Isolate*>& isolates = shared_data->isolates_;
    auto isolates_it = std::find(isolates.begin(), isolates.end(), isolate);
    if (isolates_it != isolates.end()) {
      *isolates_it = isolates.back();
      isolates.pop_back();
    }
    DCHECK_EQ(isolates.end(),
              std::find(isolates.begin(), isolates.end(), isolate));
  }
}
References CHECK, DCHECK_EQ, wasm::impl(), and v8::internal::SharedWasmMemoryData::isolates_.
Register()
void v8::internal::GlobalBackingStoreRegistry::Register (std::shared_ptr< BackingStore > backing_store) [static]
Definition at line 767 of file backing-store.cc.
                                               {
  if (!backing_store || !backing_store->buffer_start()) return;
  // Only wasm memory backing stores need to be registered globally.
  CHECK(backing_store->is_wasm_memory());
  GlobalBackingStoreRegistryImpl* impl = GetGlobalBackingStoreRegistryImpl();
  base::MutexGuard scope_lock(&impl->mutex_);
  if (backing_store->globally_registered()) return;
  TRACE_BS("BS:reg bs=%p mem=%p (length=%zu, capacity=%zu)\n",
           backing_store.get(), backing_store->buffer_start(),
           backing_store->byte_length(), backing_store->byte_capacity());
  std::weak_ptr<BackingStore> weak = backing_store;
  auto result = impl->map_.insert({backing_store->buffer_start(), weak});
  CHECK(result.second);
  backing_store->set_flag(BackingStore::kGloballyRegistered);
}
References CHECK, wasm::impl(), v8::internal::BackingStore::kGloballyRegistered, v8::base::internal::result, and TRACE_BS.
Unregister()
void v8::internal::GlobalBackingStoreRegistry::Unregister (BackingStore * backing_store) [static], [private]
Definition at line 785 of file backing-store.cc.
                                                                       {
  if (!backing_store->globally_registered()) return;
  CHECK(backing_store->is_wasm_memory());
  DCHECK_NOT_NULL(backing_store->buffer_start());
  GlobalBackingStoreRegistryImpl* impl = GetGlobalBackingStoreRegistryImpl();
  base::MutexGuard scope_lock(&impl->mutex_);
  const auto& result = impl->map_.find(backing_store->buffer_start());
  if (result != impl->map_.end()) {
    DCHECK(!result->second.lock());
    impl->map_.erase(result);
  }
  backing_store->clear_flag(BackingStore::kGloballyRegistered);
}
References v8::internal::BackingStore::buffer_start(), CHECK, v8::internal::BackingStore::clear_flag(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::BackingStore::globally_registered(), wasm::impl(), v8::internal::BackingStore::is_wasm_memory(), v8::internal::BackingStore::kGloballyRegistered, and v8::base::internal::result.
Referenced by v8::internal::BackingStore::~BackingStore().
UpdateSharedWasmMemoryObjects()
static void v8::internal::GlobalBackingStoreRegistry::UpdateSharedWasmMemoryObjects (Isolate * isolate) [static], [private]
Friends And Related Function Documentation
BackingStore
friend class BackingStore [friend]
Definition at line 294 of file backing-store.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/backing-store.h
/mnt/V8SourceCode/src/objects/backing-store.cc