v8::internal::CodeTracer Class Reference
#include <code-tracer.h>
Classes
class Scope
class StreamScope
Public Member Functions
CodeTracer (int isolate_id)
void OpenFile ()
void CloseFile ()
FILE * file () const
Static Private Member Functions
static bool ShouldRedirect ()
Private Attributes
base::EmbeddedVector< char, 128 > filename_
FILE * file_
int scope_depth_
Additional Inherited Members
Detailed Description
Definition at line 22 of file code-tracer.h.
Constructor & Destructor Documentation
CodeTracer()
v8::internal::CodeTracer::CodeTracer (int isolate_id) [inline], [explicit]
Definition at line 24 of file code-tracer.h.
                                      : file_(nullptr), scope_depth_(0) {
    if (!ShouldRedirect()) {
      file_ = stdout;
      return;
    }
    if (v8_flags.redirect_code_traces_to != nullptr) {
      base::StrNCpy(filename_, v8_flags.redirect_code_traces_to,
                    filename_.length());
    } else if (isolate_id >= 0) {
      base::SNPrintF(filename_, "code-%d-%d.asm",
                     base::OS::GetCurrentProcessId(), isolate_id);
    } else {
      base::SNPrintF(filename_, "code-%d.asm", base::OS::GetCurrentProcessId());
    }
    WriteChars(filename_.begin(), "", 0, false);
  }
References v8::base::Vector< T >::begin(), file_, filename_, v8::base::OS::GetCurrentProcessId(), v8::base::Vector< T >::length(), ShouldRedirect(), v8::base::SNPrintF(), v8::base::StrNCpy(), v8::internal::v8_flags, and v8::internal::WriteChars().
Member Function Documentation
CloseFile()
void v8::internal::CodeTracer::CloseFile () [inline]
Definition at line 91 of file code-tracer.h.
                   {
    if (!ShouldRedirect()) {
      return;
    }
    if (--scope_depth_ == 0) {
      DCHECK_NOT_NULL(file_);
      base::Fclose(file_);
      file_ = nullptr;
    }
  }
References DCHECK_NOT_NULL, v8::base::Fclose(), file_, scope_depth_, and ShouldRedirect().
file()
FILE* v8::internal::CodeTracer::file () const [inline]
Definition at line 103 of file code-tracer.h.
{ return file_; }
References file_.
Referenced by v8::internal::CodeTracer::StreamScope::StreamScope().
OpenFile()
void v8::internal::CodeTracer::OpenFile () [inline]
Definition at line 76 of file code-tracer.h.
                  {
    if (!ShouldRedirect()) {
      return;
    }
    if (file_ == nullptr) {
      file_ = base::OS::FOpen(filename_.begin(), "ab");
      CHECK_WITH_MSG(file_ != nullptr,
                     "could not open file. If on Android, try passing "
                     "--redirect-code-traces-to=/sdcard/Download/<file-name>");
    }
    scope_depth_++;
  }
References v8::base::Vector< T >::begin(), CHECK_WITH_MSG, file_, filename_, v8::base::OS::FOpen(), scope_depth_, and ShouldRedirect().
Referenced by v8::internal::CodeTracer::Scope::Scope().
ShouldRedirect()
static bool v8::internal::CodeTracer::ShouldRedirect () [inline], [static], [private]
Definition at line 106 of file code-tracer.h.
{ return v8_flags.redirect_code_traces; }
References v8::internal::v8_flags.
Referenced by CloseFile(), CodeTracer(), and OpenFile().
Member Data Documentation
file_
FILE* v8::internal::CodeTracer::file_ [private]
Definition at line 109 of file code-tracer.h.
Referenced by CloseFile(), CodeTracer(), file(), and OpenFile().
filename_
base::EmbeddedVector<char, 128> v8::internal::CodeTracer::filename_ [private]
Definition at line 108 of file code-tracer.h.
Referenced by CodeTracer(), and OpenFile().
scope_depth_
int v8::internal::CodeTracer::scope_depth_ [private]
Definition at line 110 of file code-tracer.h.
Referenced by CloseFile(), and OpenFile().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/diagnostics/code-tracer.h