v8::Maybe< T > Class Template Reference
A simple Maybe type, representing an object which may or may not have a value, see https://hackage.haskell.org/package/base/docs/Data-Maybe.html.
#include <v8-maybe.h>
Public Member Functions
constexpr Maybe ()=default
bool IsNothing () const
bool IsJust () const
T ToChecked () const
An alias for |FromJust|.
void Check () const
Short-hand for ToChecked(), which doesn't return a value.
V8_WARN_UNUSED_RESULT bool To (T *out) const
Converts this Maybe<> to a value of type T.
V8_WARN_UNUSED_RESULT bool MoveTo (T *out) &&
Converts this Maybe<> to a value of type T, moving out of it.
T FromJust () const &
Converts this Maybe<> to a value of type T.
T FromJust () &&
Converts this Maybe<> to a value of type T.
T FromMaybe (const T &default_value) const
Converts this Maybe<> to a value of type T, using a default value if this Maybe<> is nothing (empty).
bool operator== (const Maybe &other) const
bool operator!= (const Maybe &other) const
Private Member Functions
Maybe (const T &t)
Maybe (T &&t)
Private Attributes
bool has_value_ = false
T value_
Friends
template<class U >
Maybe< U > Just (const U &u)
template<class U , std::enable_if_t<!std::is_lvalue_reference_v< U >> * >
Maybe< U > Just (U &&u)
Detailed Description
template<class T>
class v8::Maybe< T >
A simple Maybe type, representing an object which may or may not have a value, see https://hackage.haskell.org/package/base/docs/Data-Maybe.html.
If an API method returns a Maybe<>, the API method can potentially fail either because an exception is thrown, or because an exception is pending, e.g. because a previous API call threw an exception that hasn't been caught yet, or because a TerminateExecution exception was thrown. In that case, a `Nothing` value is returned.
Definition at line 33 of file v8-maybe.h.
Constructor & Destructor Documentation
Maybe() [1/3]
template<class T >
constexpr v8::Maybe< T >::Maybe () [constexpr], [default]
Maybe() [2/3]
template<class T >
v8::Maybe< T >::Maybe (const T & t) [inline], [explicit], [private]
Definition at line 108 of file v8-maybe.h.
: has_value_(true), value_(t) {}
Maybe() [3/3]
template<class T >
v8::Maybe< T >::Maybe (T && t) [inline], [explicit], [private]
Definition at line 109 of file v8-maybe.h.
: has_value_(true), value_(std::move(t)) {}
Member Function Documentation
Check()
template<class T >
void v8::Maybe< T >::Check () const [inline]
Short-hand for ToChecked(), which doesn't return a value.
To be used, where the actual value of the Maybe is not needed like Object::Set.
Definition at line 49 of file v8-maybe.h.
                               {
    if (V8_UNLIKELY(!IsJust())) api_internal::FromJustIsNothing();
  }
References v8::api_internal::FromJustIsNothing(), v8::Maybe< T >::IsJust(), and V8_UNLIKELY.
FromJust() [1/2]
template<class T >
T v8::Maybe< T >::FromJust () && [inline]
Converts this Maybe<> to a value of type T.
If this Maybe<> is nothing (empty), V8 will crash the process.
Definition at line 85 of file v8-maybe.h.
                            {
    if (V8_UNLIKELY(!IsJust())) api_internal::FromJustIsNothing();
    return std::move(value_);
  }
References v8::api_internal::FromJustIsNothing(), v8::Maybe< T >::IsJust(), V8_UNLIKELY, and v8::Maybe< T >::value_.
FromJust() [2/2]
template<class T >
T v8::Maybe< T >::FromJust () const & [inline]
Converts this Maybe<> to a value of type T.
If this Maybe<> is nothing (empty), V8 will crash the process.
Definition at line 76 of file v8-maybe.h.
                                {
    if (V8_UNLIKELY(!IsJust())) api_internal::FromJustIsNothing();
    return value_;
  }
References v8::api_internal::FromJustIsNothing(), v8::Maybe< T >::IsJust(), V8_UNLIKELY, and v8::Maybe< T >::value_.
Referenced by v8::internal::anonymous_namespace{js-locale.cc}::ApplyOptionsToTag(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), v8::internal::JSArray::ArraySetLength(), v8::internal::Object::ArraySpeciesConstructor(), v8::internal::BUILTIN(), v8::internal::Intl::CanonicalizeLocaleList(), v8::internal::JSProxy::CheckDeleteTrap(), v8::internal::JSProxy::CheckGetSetTrapResult(), v8::internal::JSProxy::CheckHasTrap(), v8::internal::JSObject::CheckIfCanDefineAsConfigurable(), v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::JSWrappedFunction::Create(), v8::internal::JSObject::CreateDataProperty(), v8::internal::anonymous_namespace{js-plural-rules.cc}::CreateDataPropertyForOptions(), v8::internal::anonymous_namespace{js-collator.cc}::CreateDataPropertyForOptions(), v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareGlobal(), v8::internal::DefaultWasmAsyncResolvePromiseCallback(), v8::internal::Runtime::DefineObjectOwnProperty(), v8::internal::JSArray::DefineOwnProperty(), v8::internal::JSModuleNamespace::DefineOwnProperty(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSReceiver::DefineProperties(), v8::internal::JSReceiver::DefineProperty(), v8::internal::DebugPropertyIterator::descriptor(), v8::internal::DoWait(), v8::internal::ExternalReferenceEncoder::Encode(), v8::internal::FilterProxyKeys(), v8::internal::anonymous_namespace{js-list-format.cc}::FormatListCommon(), v8::internal::FormattedListToJSArray(), v8::internal::anonymous_namespace{js-objects.cc}::GenericTestIntegrityLevel(), v8::internal::Intl::GetCanonicalLocales(), v8::internal::Intl::GetNumberingSystem(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), v8::Object::GetOwnPropertyDescriptor(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::GetOwnValuesOrEntries(), v8::internal::Object::GetProperty(), v8::internal::JSProxy::GetPropertyAttributes(), v8::internal::anonymous_namespace{property-descriptor.cc}::GetPropertyIfPresent(), v8::internal::GetShouldThrow(), v8::internal::GetStringOption(), v8::internal::JSReceiver::HasOwnProperty(), v8::internal::Runtime::HasProperty(), v8::internal::JsonStringifier::InitializeReplacer(), v8::internal::anonymous_namespace{js-locale.cc}::InsertOptionsIntoLocale(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::JSProxy::IsExtensible(), v8::internal::anonymous_namespace{builtins-array.cc}::IterateElements(), v8::internal::anonymous_namespace{builtins-array.cc}::IterateElementsSlow(), v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor(), v8::internal::LoadIC::Load(), v8::internal::Context::Lookup(), v8::internal::RootIndexMap::Lookup(), v8::internal::ExternalReferenceEncoder::NameOfAddress(), v8::internal::JSV8BreakIterator::New(), v8::internal::JSDisplayNames::New(), v8::internal::JSListFormat::New(), v8::internal::JSPluralRules::New(), v8::internal::JSRelativeTimeFormat::New(), v8::internal::JSSegmenter::New(), v8::internal::JSCollator::New(), v8::internal::JSNumberFormat::New(), v8::internal::JSLocale::New(), v8::internal::anonymous_namespace{execution.cc}::NewScriptContext(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectDefineAccessor(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor(), v8_inspector::objectToProtocolValue(), v8::internal::JSDisplayNames::Of(), v8::internal::Isolate::OnPromiseThen(), v8::Maybe< T >::operator==(), v8::internal::anonymous_namespace{js-number-format.cc}::PartitionNumberRangePattern(), v8::internal::JSProxy::PreventExtensions(), v8::PrintMessageCallback(), v8::internal::PropertyCallbackArguments::PropertyCallbackArguments(), v8::internal::ValueDeserializer::ReadObjectInternal(), v8::internal::JSCollator::ResolvedOptions(), v8::internal::JSDateTimeFormat::ResolvedOptions(), v8::internal::JSDisplayNames::ResolvedOptions(), v8::internal::Intl::ResolveLocale(), v8::internal::JSPluralRules::ResolvePluralRange(), v8::internal::RootIndexMap::RootIndexMap(), v8::anonymous_namespace{d8.cc}::D8WasmAsyncResolvePromiseTask::Run(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Serializer::ObjectSerializer::SerializeBackingStore(), v8::internal::JsonStringifier::SerializeJSProxy(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeObjectValue(), v8::internal::JSObject::SetAccessor(), v8::internal::ScopeIterator::SetContextExtensionValue(), v8::internal::SyntheticModule::SetExportStrict(), v8::internal::JSReceiver::SetIntegrityLevel(), v8::internal::Intl::SetNumberFormatDigitOptions(), v8::internal::Runtime::SetObjectProperty(), v8::internal::JSReceiver::SetOrCopyDataProperties(), v8::internal::Object::SetPropertyInternal(), v8::internal::Object::SetSuperProperty(), v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat(), v8::internal::StoreIC::Store(), v8::internal::anonymous_namespace{intl-objects.cc}::SupportedLocales(), v8::internal::Intl::SupportedLocalesOf(), v8::Maybe< T >::ToChecked(), v8::internal::ExternalReferenceEncoder::TryEncode(), v8::internal::UnscopableLookup(), v8::internal::ValueSerializer::WriteJSError(), and v8::internal::ValueSerializer::WriteJSReceiver().
FromMaybe()
template<class T >
T v8::Maybe< T >::FromMaybe (const T & default_value) const [inline]
Converts this Maybe<> to a value of type T, using a default value if this Maybe<> is nothing (empty).
Definition at line 94 of file v8-maybe.h.
                                                      {
    return has_value_ ? value_ : default_value;
  }
References v8::Maybe< T >::has_value_, and v8::Maybe< T >::value_.
Referenced by v8::internal::Context::Lookup().
IsJust()
template<class T >
bool v8::Maybe< T >::IsJust () const [inline]
Definition at line 38 of file v8-maybe.h.
{ return has_value_; }
References v8::Maybe< T >::has_value_.
Referenced by v8::internal::JSObject::AddProperty(), v8::Maybe< T >::Check(), v8::internal::DefaultWasmAsyncResolvePromiseCallback(), v8::internal::anonymous_namespace{api-natives.cc}::DefineDataProperty(), v8::Maybe< T >::FromJust(), v8::internal::GetShouldThrow(), v8::internal::JSObject::HasRealNamedCallbackProperty(), v8::internal::RootIndexMap::Lookup(), v8::Maybe< T >::MoveTo(), v8::internal::Isolate::OnPromiseThen(), v8::Maybe< T >::operator==(), v8::Maybe< void >::operator==(), v8::PrintMessageCallback(), v8::internal::PropertyCallbackArguments::PropertyCallbackArguments(), v8::internal::JSDisplayNames::ResolvedOptions(), v8::internal::RootIndexMap::RootIndexMap(), v8::anonymous_namespace{d8.cc}::D8WasmAsyncResolvePromiseTask::Run(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Serializer::ObjectSerializer::SerializeBackingStore(), v8::internal::ScopeIterator::SetContextExtensionValue(), and v8::Maybe< T >::To().
IsNothing()
template<class T >
bool v8::Maybe< T >::IsNothing () const [inline]
Definition at line 37 of file v8-maybe.h.
{ return !has_value_; }
References v8::Maybe< T >::has_value_.
Referenced by v8::internal::BUILTIN(), v8::internal::ErrorUtils::Construct(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::JSWrappedFunction::Create(), v8::internal::JSObject::CreateDataProperty(), v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareGlobal(), v8::internal::JSArray::DefineOwnProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSReceiver::DefineProperties(), v8::internal::DebugPropertyIterator::descriptor(), v8::internal::DoWait(), v8::internal::ExternalReferenceEncoder::Encode(), v8::Object::GetOwnPropertyDescriptor(), v8::internal::GetOwnValuesOrEntries(), v8::internal::Object::GetProperty(), v8::internal::anonymous_namespace{property-descriptor.cc}::GetPropertyIfPresent(), v8::internal::Runtime::HasProperty(), v8::internal::JsonStringifier::InitializeReplacer(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::anonymous_namespace{builtins-array.cc}::IterateElements(), v8::internal::anonymous_namespace{builtins-array.cc}::IterateElementsSlow(), v8::internal::LoadIC::Load(), v8::internal::Context::Lookup(), v8::internal::ExternalReferenceEncoder::NameOfAddress(), v8::internal::JSNumberFormat::New(), v8::internal::anonymous_namespace{execution.cc}::NewScriptContext(), v8_inspector::objectToProtocolValue(), v8::internal::ValueDeserializer::ReadObjectInternal(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JsonStringifier::SerializeJSProxy(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeObjectValue(), v8::internal::JSReceiver::SetOrCopyDataProperties(), v8::internal::Object::SetPropertyInternal(), v8::internal::ExternalReferenceEncoder::TryEncode(), v8::internal::UnscopableLookup(), v8::internal::Intl::ValidateAndCanonicalizeUnicodeLocaleId(), and v8::internal::ValueSerializer::WriteJSReceiver().
MoveTo()
template<class T >
V8_WARN_UNUSED_RESULT bool v8::Maybe< T >::MoveTo (T * out) && [inline]
Converts this Maybe<> to a value of type T, moving out of it.
If this Maybe<> is nothing (empty), |false| is returned and |out| is left untouched.
Definition at line 67 of file v8-maybe.h.
                                                         {
    if (V8_LIKELY(IsJust())) *out = std::move(value_);
    return IsJust();
  }
References v8::Maybe< T >::IsJust(), V8_LIKELY, and v8::Maybe< T >::value_.
operator!=()
template<class T >
bool v8::Maybe< T >::operator!= (const Maybe< T > & other) const [inline]
Definition at line 103 of file v8-maybe.h.
                                                      {
    return !operator==(other);
  }
References v8::Maybe< T >::operator==().
operator==()
template<class T >
bool v8::Maybe< T >::operator== (const Maybe< T > & other) const [inline]
Definition at line 98 of file v8-maybe.h.
                                                      {
    return (IsJust() == other.IsJust()) &&
           (!IsJust() || FromJust() == other.FromJust());
  }
References v8::Maybe< T >::FromJust(), and v8::Maybe< T >::IsJust().
Referenced by v8::Maybe< T >::operator!=(), and v8::Maybe< void >::operator!=().
To()
template<class T >
V8_WARN_UNUSED_RESULT bool v8::Maybe< T >::To (T * out) const [inline]
Converts this Maybe<> to a value of type T.
If this Maybe<> is nothing (empty), |false| is returned and |out| is left untouched.
Definition at line 57 of file v8-maybe.h.
                                                        {
    if (V8_LIKELY(IsJust())) *out = value_;
    return IsJust();
  }
References v8::Maybe< T >::IsJust(), V8_LIKELY, and v8::Maybe< T >::value_.
Referenced by v8::internal::Object::Compare(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::compiler::VirtualObject::FieldAt(), v8::internal::compiler::GetModuleContext(), v8::internal::compiler::anonymous_namespace{js-context-specialization.cc}::GetSpecializationContext(), v8::internal::anonymous_namespace{simd.cc}::HandleRemainingHexValues(), and v8::internal::Intl::SetNumberFormatDigitOptions().
ToChecked()
template<class T >
T v8::Maybe< T >::ToChecked () const [inline]
An alias for |FromJust|.
Will crash if the Maybe<> is nothing.
Definition at line 43 of file v8-maybe.h.
{ return FromJust(); }
References v8::Maybe< T >::FromJust().
Referenced by v8::internal::ErrorUtils::Construct(), and v8::internal::ValueDeserializer::ReadVarint().
Friends And Related Function Documentation
Just [1/2]
template<class T >
template<class U >
Maybe<U> Just (const U & u) [friend]
Just [2/2]
template<class T >
template<class U , std::enable_if_t<!std::is_lvalue_reference_v< U >> * >
Maybe<U> Just (U && u) [friend]
Member Data Documentation
has_value_
template<class T >
bool v8::Maybe< T >::has_value_ = false [private]
Definition at line 111 of file v8-maybe.h.
Referenced by v8::Maybe< T >::FromMaybe(), v8::Maybe< T >::IsJust(), and v8::Maybe< T >::IsNothing().
value_
template<class T >
T v8::Maybe< T >::value_ [private]
Definition at line 112 of file v8-maybe.h.
Referenced by v8::Maybe< T >::FromJust(), v8::Maybe< T >::FromMaybe(), v8::Maybe< T >::MoveTo(), and v8::Maybe< T >::To().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-maybe.h