v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next > Class Template Reference
#include <machine-optimization-reducer.h>
Public Member Functions
V< Untagged > REDUCE() Change (V< Untagged > input, ChangeOp::Kind kind, ChangeOp::Assumption assumption, RegisterRepresentation from, RegisterRepresentation to)
V< Float64 > REDUCE() BitcastWord32PairToFloat64 (V< Word32 > hi_word32, V< Word32 > lo_word32)
V< Any > REDUCE() TaggedBitcast (V< Any > input, RegisterRepresentation from, RegisterRepresentation to, TaggedBitcastOp::Kind kind)
V< Float > REDUCE() FloatUnary (V< Float > input, FloatUnaryOp::Kind kind, FloatRepresentation rep)
V< Word > REDUCE() WordUnary (V< Word > input, WordUnaryOp::Kind kind, WordRepresentation rep)
V< Float > REDUCE() FloatBinop (V< Float > lhs, V< Float > rhs, FloatBinopOp::Kind kind, FloatRepresentation rep)
V< Word > REDUCE() WordBinop (V< Word > left, V< Word > right, WordBinopOp::Kind kind, WordRepresentation rep)
bool TryMatchHeapObject (V< Any > idx, int depth=0)
std::optional< V< Word > > TryReduceToRor (V< Word > left, V< Word > right, WordBinopOp::Kind kind, WordRepresentation rep)
V< Tuple< Word, Word32 > > REDUCE() OverflowCheckedBinop (V< Word > left, V< Word > right, OverflowCheckedBinopOp::Kind kind, WordRepresentation rep)
V< Word32 > REDUCE() Comparison (V< Any > left, V< Any > right, ComparisonOp::Kind kind, RegisterRepresentation rep)
V< Word > REDUCE() Shift (V< Word > left, V< Word32 > right, ShiftOp::Kind kind, WordRepresentation rep)
V< None > REDUCE() Branch (OpIndex condition, Block *if_true, Block *if_false, BranchHint hint)
V< None > REDUCE() DeoptimizeIf (V< Word32 > condition, V< FrameState > frame_state, bool negated, const DeoptimizeParameters *parameters)
V< Any > REDUCE() Select (V< Word32 > cond, V< Any > vtrue, V< Any > vfalse, RegisterRepresentation rep, BranchHint hint, SelectOp::Implementation implem)
V< None > REDUCE() StaticAssert (V< Word32 > condition, const char *source)
V< None > REDUCE() Switch (V< Word32 > input, base::Vector< SwitchOp::Case > cases, Block *default_case, BranchHint default_hint)
V< None > REDUCE() Store (OpIndex base_idx, OptionalOpIndex index, OpIndex value, StoreOp::Kind kind, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset, uint8_t element_scale, bool maybe_initializing_or_transitioning, IndirectPointerTag maybe_indirect_pointer_tag)
OpIndex REDUCE() Load (OpIndex base_idx, OptionalOpIndex index, LoadOp::Kind kind, MemoryRepresentation loaded_rep, RegisterRepresentation result_rep, int32_t offset, uint8_t element_scale)
Private Member Functions
V< Word32 > ReduceCompareEqual (V< Any > left, V< Any > right, RegisterRepresentation rep)
bool TryAdjustOffset (int32_t *offset, const Operation &maybe_constant, uint8_t element_scale, bool tagged_base)
bool TryAdjustIndex (int32_t offset, OpIndex *index, const Operation &maybe_constant, uint8_t element_scale)
bool TryAdjustElementScale (uint8_t *element_scale, OpIndex maybe_constant)
OpIndex ReduceMemoryIndex (OpIndex index, int32_t *offset, uint8_t *element_scale, bool tagged_base)
bool IsFloat32ConvertedToFloat64 (V< Any > value)
V< Float32 > UndoFloat32ToFloat64Conversion (V< Float64 > value)
bool IsBit (V< Word > value)
bool IsInt8 (V< Word > value)
bool IsInt16 (V< Word > value)
bool IsWord32ConvertedToWord64 (V< Any > value, std::optional< bool > *sign_extended=nullptr)
V< Word32 > UndoWord32ToWord64Conversion (V< Word > value)
V< Word > TryRemoveWord32ToWord64Conversion (V< Word > value)
uint64_t TruncateWord (uint64_t value, WordRepresentation rep)
V< Word > ReduceWithTruncation (V< Word > value, uint64_t truncation_mask, WordRepresentation rep)
V< Word > ReduceSignedDiv (V< Word > left, int64_t right, WordRepresentation rep)
V< Word > ReduceUnsignedDiv (V< Word > left, uint64_t right, WordRepresentation rep)
std::optional< V< Word32 > > ReduceBranchCondition (V< Word32 > condition, bool *negated)
std::optional< bool > MatchBoolConstant (V< Any > condition)
bool MapLoadCanBeConstantFolded (OptionalMapRef map)
Static Private Member Functions
static constexpr bool IsNegativePowerOfTwo (int64_t x)
static constexpr uint16_t CountLeadingSignBits (int64_t c, WordRepresentation rep)
Private Attributes
JSHeapBroker * broker = __ data() -> broker()
const OperationMatcher & matcher_ = __ matcher()
Static Private Attributes
static constexpr bool signalling_nan_possible = false
static constexpr bool ensure_deterministic_nan = false
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >
Definition at line 191 of file machine-optimization-reducer.h.
Member Function Documentation
BitcastWord32PairToFloat64()
template<class Next >
V<Float64> REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::BitcastWord32PairToFloat64 (V< Word32 > hi_word32, V< Word32 > lo_word32) [inline]
Definition at line 318 of file machine-optimization-reducer.h.
                                                                     {
    if (ShouldSkipOptimizationStep()) {
      return Next::ReduceBitcastWord32PairToFloat64(hi_word32, lo_word32);
    }
    uint32_t lo, hi;
    if (matcher_.MatchIntegralWord32Constant(hi_word32, &hi) &&
        matcher_.MatchIntegralWord32Constant(lo_word32, &lo)) {
      return __ Float64Constant(
          base::bit_cast<double>(uint64_t{hi} << 32 | uint64_t{lo}));
    }
    return Next::ReduceBitcastWord32PairToFloat64(hi_word32, lo_word32);
  }
References __, v8::internal::hi, v8::internal::lo, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), and v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep().
Branch()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Branch (OpIndex condition, Block * if_true, Block * if_false, BranchHint hint) [inline]
Definition at line 1831 of file machine-optimization-reducer.h.
                                          {
    LABEL_BLOCK(no_change) {
      return Next::ReduceBranch(condition, if_true, if_false, hint);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    // Try to replace the Branch by a Goto.
    if (std::optional<bool> decision = MatchBoolConstant(condition)) {
      __ Goto(*decision ? if_true : if_false);
      return V<None>::Invalid();
    }
    // Try to simplify the Branch's condition (eg, `if (x == 0) A else B` can
    // become `if (x) B else A`).
    bool negated = false;
    if (std::optional<OpIndex> new_condition =
            ReduceBranchCondition(condition, &negated)) {
      if (negated) {
        std::swap(if_true, if_false);
        hint = NegateBranchHint(hint);
      }
      return __ ReduceBranch(new_condition.value(), if_true, if_false, hint);
    }
    goto no_change;
  }
References __, v8::internal::compiler::turboshaft::V< T >::Invalid(), LABEL_BLOCK, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::MatchBoolConstant(), v8::internal::compiler::NegateBranchHint(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceBranchCondition(), and v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep().
Change()
template<class Next >
V<Untagged> REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change (V< Untagged > input, ChangeOp::Kind kind, ChangeOp::Assumption assumption, RegisterRepresentation from, RegisterRepresentation to) [inline]
Definition at line 208 of file machine-optimization-reducer.h.
                                                        {
    if (ShouldSkipOptimizationStep()) {
      return Next::ReduceChange(input, kind, assumption, from, to);
    }
    using Kind = ChangeOp::Kind;
    if (from == WordRepresentation::Word32()) {
      input = TryRemoveWord32ToWord64Conversion(V<Word64>::Cast(input));
    }
    if (uint64_t value;
        from.IsWord() && matcher_.MatchIntegralWordConstant(
                             input, WordRepresentation(from), &value)) {
      using Rep = RegisterRepresentation;
      switch (multi(kind, from, to)) {
        case multi(Kind::kSignExtend, Rep::Word32(), Rep::Word64()):
          return __ Word64Constant(int64_t{static_cast<int32_t>(value)});
        case multi(Kind::kZeroExtend, Rep::Word32(), Rep::Word64()):
        case multi(Kind::kBitcast, Rep::Word32(), Rep::Word64()):
          return __ Word64Constant(uint64_t{static_cast<uint32_t>(value)});
        case multi(Kind::kBitcast, Rep::Word32(), Rep::Float32()):
          return __ Float32Constant(
              i::Float32::FromBits(static_cast<uint32_t>(value)));
        case multi(Kind::kBitcast, Rep::Word64(), Rep::Float64()):
          return __ Float64Constant(i::Float64::FromBits(value));
        case multi(Kind::kSignedToFloat, Rep::Word32(), Rep::Float64()):
          return __ Float64Constant(
              static_cast<double>(static_cast<int32_t>(value)));
        case multi(Kind::kSignedToFloat, Rep::Word64(), Rep::Float64()):
          return __ Float64Constant(
              static_cast<double>(static_cast<int64_t>(value)));
        case multi(Kind::kUnsignedToFloat, Rep::Word32(), Rep::Float64()):
          return __ Float64Constant(
              static_cast<double>(static_cast<uint32_t>(value)));
        case multi(Kind::kTruncate, Rep::Word64(), Rep::Word32()):
          return __ Word32Constant(static_cast<uint32_t>(value));
        default:
          break;
      }
    }
    if (i::Float32 value; from == RegisterRepresentation::Float32() &&
                          matcher_.MatchFloat32Constant(input, &value)) {
      if (kind == Kind::kFloatConversion &&
          to == RegisterRepresentation::Float64()) {
        return __ Float64Constant(value.get_scalar());
      }
      if (kind == Kind::kBitcast && to == WordRepresentation::Word32()) {
        return __ Word32Constant(value.get_bits());
      }
    }
    if (i::Float64 value; from == RegisterRepresentation::Float64() &&
                          matcher_.MatchFloat64Constant(input, &value)) {
      if (kind == Kind::kFloatConversion &&
          to == RegisterRepresentation::Float32()) {
        return __ Float32Constant(DoubleToFloat32_NoInline(value.get_scalar()));
      }
      if (kind == Kind::kBitcast && to == WordRepresentation::Word64()) {
        return __ Word64Constant(base::bit_cast<uint64_t>(value));
      }
      if (kind == Kind::kSignedFloatTruncateOverflowToMin) {
        double truncated = std::trunc(value.get_scalar());
        if (to == WordRepresentation::Word64()) {
          int64_t result = std::numeric_limits<int64_t>::min();
          if (truncated >= std::numeric_limits<int64_t>::min() &&
              truncated <= kMaxDoubleRepresentableInt64) {
            result = static_cast<int64_t>(truncated);
          }
          return __ Word64Constant(result);
        }
        if (to == WordRepresentation::Word32()) {
          int32_t result = std::numeric_limits<int32_t>::min();
          if (truncated >= std::numeric_limits<int32_t>::min() &&
              truncated <= std::numeric_limits<int32_t>::max()) {
            result = static_cast<int32_t>(truncated);
          }
          return __ Word32Constant(result);
        }
      }
      if (kind == Kind::kJSFloatTruncate &&
          to == WordRepresentation::Word32()) {
        return __ Word32Constant(DoubleToInt32_NoInline(value.get_scalar()));
      }
      if (kind == Kind::kExtractHighHalf) {
        DCHECK_EQ(to, RegisterRepresentation::Word32());
        return __ Word32Constant(static_cast<uint32_t>(value.get_bits() >> 32));
      }
      if (kind == Kind::kExtractLowHalf) {
        DCHECK_EQ(to, RegisterRepresentation::Word32());
        return __ Word32Constant(static_cast<uint32_t>(value.get_bits()));
      }
    }
    if (float value; from == RegisterRepresentation::Float32() &&
                     matcher_.MatchFloat32Constant(input, &value)) {
      if (kind == Kind::kFloatConversion &&
          to == RegisterRepresentation::Float64()) {
        return __ Float64Constant(value);
      }
    }
    const Operation& input_op = matcher_.Get(input);
    if (const ChangeOp* change_op = input_op.TryCast<ChangeOp>()) {
      if (change_op->from == to && change_op->to == from &&
          change_op->IsReversibleBy(kind, signalling_nan_possible)) {
        return change_op->input();
      }
    }
    return Next::ReduceChange(input, kind, assumption, from, to);
  }
References __, DCHECK_EQ, v8::internal::DoubleToFloat32_NoInline(), v8::internal::DoubleToInt32_NoInline(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::Float32::FromBits(), v8::internal::Float64::FromBits(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), kMaxDoubleRepresentableInt64, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat32Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat64Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant(), v8::internal::compiler::turboshaft::multi(), v8::base::internal::result, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::signalling_nan_possible, v8::internal::compiler::turboshaft::Operation::TryCast(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryRemoveWord32ToWord64Conversion(), v8::internal::value, v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Comparison()
template<class Next >
V<Word32> REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison (V< Any > left, V< Any > right, ComparisonOp::Kind kind, RegisterRepresentation rep) [inline]
Definition at line 1431 of file machine-optimization-reducer.h.
                                                           {
    if (ShouldSkipOptimizationStep()) {
      return Next::ReduceComparison(left, right, kind, rep);
    }
    if (kind == ComparisonOp::Kind::kEqual) {
      return ReduceCompareEqual(left, right, rep);
    }
    if (rep == WordRepresentation::Word32()) {
      left = TryRemoveWord32ToWord64Conversion(V<Word>::Cast(left));
      right = TryRemoveWord32ToWord64Conversion(V<Word>::Cast(right));
    }
    using Kind = ComparisonOp::Kind;
    if (left == right &&
        !(rep == any_of(RegisterRepresentation::Float32(),
                        RegisterRepresentation::Float64())) &&
        kind == any_of(Kind::kSignedLessThanOrEqual,
                       Kind::kUnsignedLessThanOrEqual)) {
      switch (kind) {
        case Kind::kEqual:
          UNREACHABLE();
        case Kind::kUnsignedLessThanOrEqual:
        case Kind::kSignedLessThanOrEqual:
          return __ Word32Constant(1);
        case Kind::kUnsignedLessThan:
        case Kind::kSignedLessThan:
          return __ Word32Constant(0);
      }
    }
    // constant folding
    if (matcher_.Is<ConstantOp>(right) && matcher_.Is<ConstantOp>(left)) {
      switch (rep.value()) {
        case RegisterRepresentation::Word32():
        case RegisterRepresentation::Word64(): {
          if (kind ==
              any_of(Kind::kSignedLessThan, Kind::kSignedLessThanOrEqual)) {
            if (int64_t k1, k2; matcher_.MatchIntegralWordConstant(
                                    left, WordRepresentation(rep), &k1) &&
                                matcher_.MatchIntegralWordConstant(
                                    right, WordRepresentation(rep), &k2)) {
              switch (kind) {
                case ComparisonOp::Kind::kSignedLessThan:
                  return __ Word32Constant(k1 < k2);
                case ComparisonOp::Kind::kSignedLessThanOrEqual:
                  return __ Word32Constant(k1 <= k2);
                case ComparisonOp::Kind::kEqual:
                case ComparisonOp::Kind::kUnsignedLessThan:
                case ComparisonOp::Kind::kUnsignedLessThanOrEqual:
                  UNREACHABLE();
              }
            }
          } else {
            if (uint64_t k1, k2; matcher_.MatchIntegralWordConstant(
                                     left, WordRepresentation(rep), &k1) &&
                                 matcher_.MatchIntegralWordConstant(
                                     right, WordRepresentation(rep), &k2)) {
              switch (kind) {
                case ComparisonOp::Kind::kUnsignedLessThan:
                  return __ Word32Constant(k1 < k2);
                case ComparisonOp::Kind::kUnsignedLessThanOrEqual:
                  return __ Word32Constant(k1 <= k2);
                case ComparisonOp::Kind::kEqual:
                case ComparisonOp::Kind::kSignedLessThan:
                case ComparisonOp::Kind::kSignedLessThanOrEqual:
                  UNREACHABLE();
              }
            }
          }
          break;
        }
        case RegisterRepresentation::Float32(): {
          if (float k1, k2; matcher_.MatchFloat32Constant(left, &k1) &&
                            matcher_.MatchFloat32Constant(right, &k2)) {
            switch (kind) {
              case ComparisonOp::Kind::kSignedLessThan:
                return __ Word32Constant(k1 < k2);
              case ComparisonOp::Kind::kSignedLessThanOrEqual:
                return __ Word32Constant(k1 <= k2);
              case ComparisonOp::Kind::kEqual:
              case ComparisonOp::Kind::kUnsignedLessThan:
              case ComparisonOp::Kind::kUnsignedLessThanOrEqual:
                UNREACHABLE();
            }
          }
          break;
        }
        case RegisterRepresentation::Float64(): {
          if (double k1, k2; matcher_.MatchFloat64Constant(left, &k1) &&
                             matcher_.MatchFloat64Constant(right, &k2)) {
            switch (kind) {
              case ComparisonOp::Kind::kSignedLessThan:
                return __ Word32Constant(k1 < k2);
              case ComparisonOp::Kind::kSignedLessThanOrEqual:
                return __ Word32Constant(k1 <= k2);
              case ComparisonOp::Kind::kEqual:
              case ComparisonOp::Kind::kUnsignedLessThan:
              case ComparisonOp::Kind::kUnsignedLessThanOrEqual:
                UNREACHABLE();
            }
          }
          break;
        }
        default:
          UNREACHABLE();
      }
    }
    if (rep == RegisterRepresentation::Float64() &&
        IsFloat32ConvertedToFloat64(left) &&
        IsFloat32ConvertedToFloat64(right)) {
      return __ Comparison(
          UndoFloat32ToFloat64Conversion(V<Float64>::Cast(left)),
          UndoFloat32ToFloat64Conversion(V<Float64>::Cast(right)), kind,
          RegisterRepresentation::Float32());
    }
    if (rep.IsWord()) {
      WordRepresentation rep_w{rep};
      if (kind == Kind::kUnsignedLessThanOrEqual) {
        // 0 <= x => true
        if (uint64_t k;
            matcher_.MatchIntegralWordConstant(left, rep_w, &k) && k == 0) {
          return __ Word32Constant(1);
        }
        // x <= MaxUint => true
        if (uint64_t k; matcher_.MatchIntegralWordConstant(right, rep_w, &k) &&
                        k == rep.MaxUnsignedValue()) {
          return __ Word32Constant(1);
        }
        // x <= 0 => x == 0
        if (uint64_t k;
            matcher_.MatchIntegralWordConstant(right, rep_w, &k) && k == 0) {
          return __ Equal(left, __ WordConstant(0, rep_w), rep_w);
        }
      }
      if (kind == Kind::kUnsignedLessThan) {
        // x < 0 => false
        if (uint64_t k;
            matcher_.MatchIntegralWordConstant(right, rep_w, &k) && k == 0) {
          return __ Word32Constant(0);
        }
        // MaxUint < x => true
        if (uint64_t k; matcher_.MatchIntegralWordConstant(left, rep_w, &k) &&
                        k == rep.MaxUnsignedValue()) {
          return __ Word32Constant(0);
        }
      }
      {
        // (x >> k) </<= (y >> k) => x </<= y if shifts reversible
        V<Word> x, y;
        uint16_t k1, k2;
        if (matcher_.MatchConstantShiftRightArithmeticShiftOutZeros(
                left, &x, rep_w, &k1) &&
            matcher_.MatchConstantShiftRightArithmeticShiftOutZeros(
                right, &y, rep_w, &k2) &&
            k1 == k2) {
          return __ Comparison(x, y, kind, rep_w);
        }
      }
      {
        // (x >> k1) </<= k2 => x </<= (k2 << k1) if shifts reversible
        // Only perform the transformation if the shift is not used yet, to
        // avoid keeping both the shift and x alive.
        V<Word> x;
        uint16_t k1;
        int64_t k2;
        if (matcher_.MatchConstantShiftRightArithmeticShiftOutZeros(
                left, &x, rep_w, &k1) &&
            matcher_.MatchIntegralWordConstant(right, rep_w, &k2) &&
            CountLeadingSignBits(k2, rep_w) > k1) {
          if (matcher_.Get(left).saturated_use_count.IsZero()) {
            return __ Comparison(
                x, __ WordConstant(base::bits::Unsigned(k2) << k1, rep_w), kind,
                rep_w);
          } else if constexpr (reducer_list_contains<
                                   ReducerList, ValueNumberingReducer>::value) {
            // If the shift has uses, we only apply the transformation if the
            // result would be GVNed away.
            V<Word> rhs =
                __ WordConstant(base::bits::Unsigned(k2) << k1, rep_w);
            static_assert(ComparisonOp::input_count == 2);
            static_assert(sizeof(ComparisonOp) == 8);
            base::SmallVector<OperationStorageSlot, 32> storage;
            ComparisonOp* cmp =
                CreateOperation<ComparisonOp>(storage, x, rhs, kind, rep_w);
            if (__ WillGVNOp(*cmp)) {
              return __ Comparison(x, rhs, kind, rep_w);
            }
          }
        }
        // k2 </<= (x >> k1) => (k2 << k1) </<= x if shifts reversible
        // Only perform the transformation if the shift is not used yet, to
        // avoid keeping both the shift and x alive.
        if (matcher_.MatchConstantShiftRightArithmeticShiftOutZeros(
                right, &x, rep_w, &k1) &&
            matcher_.MatchIntegralWordConstant(left, rep_w, &k2) &&
            CountLeadingSignBits(k2, rep_w) > k1) {
          if (matcher_.Get(right).saturated_use_count.IsZero()) {
            return __ Comparison(
                __ WordConstant(base::bits::Unsigned(k2) << k1, rep_w), x, kind,
                rep_w);
          } else if constexpr (reducer_list_contains<
                                   ReducerList, ValueNumberingReducer>::value) {
            // If the shift has uses, we only apply the transformation if the
            // result would be GVNed away.
            V<Word> lhs =
                __ WordConstant(base::bits::Unsigned(k2) << k1, rep_w);
            static_assert(ComparisonOp::input_count == 2);
            static_assert(sizeof(ComparisonOp) == 8);
            base::SmallVector<OperationStorageSlot, 32> storage;
            ComparisonOp* cmp =
                CreateOperation<ComparisonOp>(storage, lhs, x, kind, rep_w);
            if (__ WillGVNOp(*cmp)) {
              return __ Comparison(lhs, x, kind, rep_w);
            }
          }
        }
      }
      // Map 64bit to 32bit comparisons.
      if (rep_w == WordRepresentation::Word64()) {
        std::optional<bool> left_sign_extended;
        std::optional<bool> right_sign_extended;
        if (IsWord32ConvertedToWord64(left, &left_sign_extended) &&
            IsWord32ConvertedToWord64(right, &right_sign_extended)) {
          if (left_sign_extended != true && right_sign_extended != true) {
            // Both sides were zero-extended, so the resulting comparison always
            // behaves unsigned even if it was a signed 64bit comparison.
            auto SetSigned = [](Kind kind, bool is_signed) {
              switch (kind) {
                case Kind::kSignedLessThan:
                case Kind::kUnsignedLessThan:
                  return is_signed ? Kind::kSignedLessThan
                                   : Kind::kUnsignedLessThan;
                case Kind::kSignedLessThanOrEqual:
                case Kind::kUnsignedLessThanOrEqual:
                  return is_signed ? Kind::kSignedLessThanOrEqual
                                   : Kind::kUnsignedLessThanOrEqual;
                case Kind::kEqual:
                  UNREACHABLE();
              }
            };
            return __ Comparison(
                UndoWord32ToWord64Conversion(V<Word64>::Cast(left)),
                UndoWord32ToWord64Conversion(V<Word64>::Cast(right)),
                SetSigned(kind, false), WordRepresentation::Word32());
          } else if (left_sign_extended != false &&
                     right_sign_extended != false) {
            // Both sides were sign-extended, this preserves both signed and
            // unsigned comparisons.
            return __ Comparison(
                UndoWord32ToWord64Conversion(V<Word64>::Cast(left)),
                UndoWord32ToWord64Conversion(V<Word64>::Cast(right)), kind,
                WordRepresentation::Word32());
          }
        }
      }
    }
    return Next::ReduceComparison(left, right, kind, rep);
  }
References __, v8::internal::compiler::turboshaft::any_of(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::CountLeadingSignBits(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::FixedArityOperationT< 2, ComparisonOp >::input_count, v8::internal::compiler::turboshaft::OperationMatcher::Is(), v8::internal::is_signed(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsFloat32ConvertedToFloat64(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsWord32ConvertedToWord64(), v8::internal::compiler::turboshaft::SaturatedUint8::IsZero(), v8::internal::kEqual, v8::internal::compiler::turboshaft::ComparisonOp::kEqual, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThan, v8::internal::compiler::kSignedLessThanOrEqual, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThanOrEqual, v8::internal::kUnsignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThanOrEqual, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat32Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat64Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::Operation::saturated_use_count, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryRemoveWord32ToWord64Conversion(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoFloat32ToFloat64Conversion(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoWord32ToWord64Conversion(), v8::internal::UNREACHABLE(), v8::base::bits::Unsigned(), v8::internal::value, v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word64(), v8::internal::compiler::turboshaft::WordRepresentation::Word64(), and v8::internal::y.
CountLeadingSignBits()
template<class Next >
static constexpr uint16_t v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::CountLeadingSignBits (int64_t c, WordRepresentation rep) [inline], [static], [constexpr], [private]
Definition at line 2918 of file machine-optimization-reducer.h.
                                                                         {
    return base::bits::CountLeadingSignBits(c) - (64 - rep.bit_width());
  }
References v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::bit_width(), and v8::base::bits::CountLeadingSignBits().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual().
DeoptimizeIf()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::DeoptimizeIf (V< Word32 > condition, V< FrameState > frame_state, bool negated, const DeoptimizeParameters * parameters) [inline]
Definition at line 1860 of file machine-optimization-reducer.h.
                                                                       {
    if (ShouldSkipOptimizationStep()) {
      return Next::ReduceDeoptimizeIf(condition, frame_state, negated,
                                      parameters);
    }
    if (std::optional<bool> decision = MatchBoolConstant(condition)) {
      if (*decision != negated) {
        __ Deoptimize(frame_state, parameters);
      }
      // `DeoptimizeIf` doesn't produce a value.
      return V<None>::Invalid();
    }
    if (std::optional<V<Word32>> new_condition =
            ReduceBranchCondition(condition, &negated)) {
      return __ ReduceDeoptimizeIf(new_condition.value(), frame_state, negated,
                                   parameters);
    } else {
      return Next::ReduceDeoptimizeIf(condition, frame_state, negated,
                                      parameters);
    }
  }
References __, v8::internal::compiler::turboshaft::V< T >::Invalid(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::MatchBoolConstant(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceBranchCondition(), and v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep().
FloatBinop()
template<class Next >
V<Float> REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop (V< Float > lhs, V< Float > rhs, FloatBinopOp::Kind kind, FloatRepresentation rep) [inline]
Definition at line 581 of file machine-optimization-reducer.h.
                                                       {
    if (ShouldSkipOptimizationStep()) {
      return Next::ReduceFloatBinop(lhs, rhs, kind, rep);
    }
    using Kind = FloatBinopOp::Kind;
    // Place constant on the right for commutative operators.
    if (FloatBinopOp::IsCommutative(kind) && matcher_.Is<ConstantOp>(lhs) &&
        !matcher_.Is<ConstantOp>(rhs) && !ensure_deterministic_nan) {
      return ReduceFloatBinop(rhs, lhs, kind, rep);
    }
    // constant folding
    if (float k1, k2;
        rep == FloatRepresentation::Float32() &&
        matcher_.MatchFloat32Constant(lhs, &k1) &&
        matcher_.MatchFloat32Constant(rhs, &k2) &&
        detail::CanFoldFloatConstants(ensure_deterministic_nan, k1, k2)) {
      switch (kind) {
        case Kind::kAdd:
          return __ Float32Constant(k1 + k2);
        case Kind::kMul:
          return __ Float32Constant(k1 * k2);
        case Kind::kSub:
          return __ Float32Constant(k1 - k2);
        case Kind::kMin:
          return __ Float32Constant(JSMin(k1, k2));
        case Kind::kMax:
          return __ Float32Constant(JSMax(k1, k2));
        case Kind::kDiv:
          return __ Float32Constant(k1 / k2);
        case Kind::kPower:
          return __ Float32Constant(internal::math::pow(k1, k2));
        case Kind::kAtan2:
          return __ Float32Constant(base::ieee754::atan2(k1, k2));
        case Kind::kMod:
          UNREACHABLE();
      }
    }
    if (double k1, k2;
        rep == FloatRepresentation::Float64() &&
        matcher_.MatchFloat64Constant(lhs, &k1) &&
        matcher_.MatchFloat64Constant(rhs, &k2) &&
        detail::CanFoldFloatConstants(ensure_deterministic_nan, k1, k2)) {
      switch (kind) {
        case Kind::kAdd:
          return __ Float64Constant(k1 + k2);
        case Kind::kMul:
          return __ Float64Constant(k1 * k2);
        case Kind::kSub:
          return __ Float64Constant(k1 - k2);
        case Kind::kMin:
          return __ Float64Constant(JSMin(k1, k2));
        case Kind::kMax:
          return __ Float64Constant(JSMax(k1, k2));
        case Kind::kDiv:
          return __ Float64Constant(k1 / k2);
        case Kind::kMod:
          return __ Float64Constant(Modulo(k1, k2));
        case Kind::kPower:
          return __ Float64Constant(math::pow(k1, k2));
        case Kind::kAtan2:
          return __ Float64Constant(base::ieee754::atan2(k1, k2));
      }
    }
    // All NaN folding is disabled for Wasm; architectures disagree on which
    // input to take in case both are NaN, sometimes it even depends on the
    // exact NaN which one is propagated as the result.
    // Even though the Wasm spec allows propagating any NaN input, we want
    // determinism here for differential fuzzing across compilers.
    if (!ensure_deterministic_nan) {
      // NaN <op> rhs => NaN (except for Kind::kPower).
      // lhs <op> NaN => NaN.
      if (i::Float32 nan;
          (matcher_.MatchFloat32Constant(lhs, &nan) && nan.is_nan() &&
           kind != Kind::kPower) ||
          (matcher_.MatchFloat32Constant(rhs, &nan) && nan.is_nan())) {
        // Return a quiet NaN since Wasm operations could have signalling NaN as
        // input but not as output.
        return __ Float32Constant(std::numeric_limits<float>::quiet_NaN());
      }
      // Same for float64.
      if (i::Float64 nan;
          (matcher_.MatchFloat64Constant(lhs, &nan) && nan.is_nan() &&
           kind != Kind::kPower) ||
          (matcher_.MatchFloat64Constant(rhs, &nan) && nan.is_nan())) {
        // Return a quiet NaN since Wasm operations could have signalling NaN as
        // input but not as output.
        return __ Float64Constant(std::numeric_limits<double>::quiet_NaN());
      }
    }
    if (matcher_.Is<ConstantOp>(rhs)) {
      if (kind == Kind::kMul) {
        // lhs * 1 => lhs
        if (!signalling_nan_possible && matcher_.MatchFloat(rhs, 1.0)) {
          return lhs;
        }
        // lhs * 2 => lhs + lhs
        if (matcher_.MatchFloat(rhs, 2.0)) {
          return __ FloatAdd(lhs, lhs, rep);
        }
        // lhs * -1 => -lhs
        // Note: FloatNegate does not set the quiet bit so we cannot use this if
        // signalling nans can happen.
        if (!signalling_nan_possible && matcher_.MatchFloat(rhs, -1.0)) {
          return __ FloatNegate(lhs, rep);
        }
      }
      if (kind == Kind::kDiv) {
        // lhs / 1 => lhs
        if (!signalling_nan_possible && matcher_.MatchFloat(rhs, 1.0)) {
          return lhs;
        }
        // lhs / -1 => -lhs
        // Note: FloatNegate does not set the quiet bit so we cannot use this if
        // signalling nans can happen.
        if (!signalling_nan_possible && matcher_.MatchFloat(rhs, -1.0)) {
          return __ FloatNegate(lhs, rep);
        }
        // All reciprocals of non-denormal powers of two can be represented
        // exactly, so division by power of two can be reduced to
        // multiplication by reciprocal, with the same result.
        // x / k => x * (1 / k)
        if (rep == FloatRepresentation::Float32()) {
          if (float k;
              matcher_.MatchFloat32Constant(rhs, &k) && std::isnormal(k) &&
              k != 0 && std::isfinite(k) &&
              base::bits::IsPowerOfTwo(base::Double(k).Significand())) {
            return __ FloatMul(lhs, __ FloatConstant(1.0 / k, rep), rep);
          }
        } else {
          DCHECK_EQ(rep, FloatRepresentation::Float64());
          if (double k;
              matcher_.MatchFloat64Constant(rhs, &k) && std::isnormal(k) &&
              k != 0 && std::isfinite(k) &&
              base::bits::IsPowerOfTwo(base::Double(k).Significand())) {
            return __ FloatMul(lhs, __ FloatConstant(1.0 / k, rep), rep);
          }
        }
      }
      if (kind == Kind::kMod) {
        // x % 0 => NaN
        if (matcher_.MatchFloat(rhs, 0.0)) {
          return __ FloatConstant(std::numeric_limits<double>::quiet_NaN(),
                                  rep);
        }
      }
      if (kind == Kind::kSub) {
        // lhs - +0.0 => lhs
        if (!signalling_nan_possible && matcher_.MatchFloat(rhs, +0.0)) {
          return lhs;
        }
      }
      if (kind == Kind::kPower) {
        if (matcher_.MatchFloat(rhs, 0.0) || matcher_.MatchFloat(rhs, -0.0)) {
          // lhs ** 0 ==> 1
          return __ FloatConstant(1.0, rep);
        }
        if (matcher_.MatchFloat(rhs, 2.0)) {
          // lhs ** 2 ==> lhs * lhs
          return __ FloatMul(lhs, lhs, rep);
        }
        if (matcher_.MatchFloat(rhs, 0.5)) {
          // lhs ** 0.5 ==> sqrt(lhs)
          // (unless if lhs is -infinity)
          Variable result = __ NewLoopInvariantVariable(rep);
          IF (UNLIKELY(__ FloatLessThanOrEqual(
                  lhs, __ FloatConstant(-V8_INFINITY, rep), rep))) {
            __ SetVariable(result, __ FloatConstant(V8_INFINITY, rep));
          } ELSE {
            __ SetVariable(
                result,
                __ FloatSqrt(__ FloatAdd(lhs, __ FloatConstant(0, rep), rep),
                             rep));
          }
          return __ GetVariable(result);
        }
      }
    }
    if (!signalling_nan_possible && kind == Kind::kSub &&
        matcher_.MatchFloat(lhs, -0.0)) {
      // -0.0 - round_down(-0.0 - y) => round_up(y)
      if (V<Float> a, b, c;
          FloatUnaryOp::IsSupported(FloatUnaryOp::Kind::kRoundUp, rep) &&
          matcher_.MatchFloatRoundDown(rhs, &a, rep) &&
          matcher_.MatchFloatSub(a, &b, &c, rep) &&
          matcher_.MatchFloat(b, -0.0)) {
        return __ FloatRoundUp(c, rep);
      }
      // -0.0 - rhs => -rhs
      return __ FloatNegate(rhs, rep);
    }
    return Next::ReduceFloatBinop(lhs, rhs, kind, rep);
  }
References __, v8::base::ieee754::atan2(), v8::internal::compiler::turboshaft::detail::CanFoldFloatConstants(), DCHECK_EQ, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ensure_deterministic_nan, v8::internal::compiler::turboshaft::FloatRepresentation::Float32(), v8::internal::compiler::turboshaft::FloatRepresentation::Float64(), v8::internal::compiler::turboshaft::OperationMatcher::Is(), v8::internal::compiler::turboshaft::FloatBinopOp::IsCommutative(), v8::base::bits::IsPowerOfTwo(), v8::internal::compiler::turboshaft::FloatUnaryOp::IsSupported(), v8::internal::JSMax(), v8::internal::JSMin(), v8::internal::compiler::turboshaft::FloatUnaryOp::kRoundUp, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat32Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat64Constant(), v8::internal::math::pow(), v8::base::internal::result, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::signalling_nan_possible, v8::internal::UNREACHABLE(), and V8_INFINITY.
FloatUnary()
template<class Next >
V<Float> REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary (V< Float > input, FloatUnaryOp::Kind kind, FloatRepresentation rep) [inline]
Definition at line 396 of file machine-optimization-reducer.h.
                                                       {
    if (ShouldSkipOptimizationStep()) {
      return Next::ReduceFloatUnary(input, kind, rep);
    }
    if (float f32_k; rep == FloatRepresentation::Float32() &&
                     matcher_.MatchFloat32Constant(input, &f32_k)) {
      if (std::isnan(f32_k) && !ensure_deterministic_nan) {
        return __ Float32Constant(std::numeric_limits<float>::quiet_NaN());
      }
      switch (kind) {
        case FloatUnaryOp::Kind::kAbs:
          return __ Float32Constant(std::abs(f32_k));
        case FloatUnaryOp::Kind::kNegate:
          return __ Float32Constant(-f32_k);
        case FloatUnaryOp::Kind::kSilenceNaN:
          DCHECK(!std::isnan(f32_k));
          return __ Float32Constant(f32_k);
        case FloatUnaryOp::Kind::kRoundDown:
          return __ Float32Constant(std::floor(f32_k));
        case FloatUnaryOp::Kind::kRoundUp:
          return __ Float32Constant(std::ceil(f32_k));
        case FloatUnaryOp::Kind::kRoundToZero:
          return __ Float32Constant(std::trunc(f32_k));
        case FloatUnaryOp::Kind::kRoundTiesEven:
          DCHECK_EQ(std::nearbyint(1.5), 2);
          DCHECK_EQ(std::nearbyint(2.5), 2);
          return __ Float32Constant(std::nearbyint(f32_k));
        case FloatUnaryOp::Kind::kLog:
          return __ Float32Constant(base::ieee754::log(f32_k));
        case FloatUnaryOp::Kind::kSqrt:
          return __ Float32Constant(std::sqrt(f32_k));
        case FloatUnaryOp::Kind::kExp:
          return __ Float32Constant(base::ieee754::exp(f32_k));
        case FloatUnaryOp::Kind::kExpm1:
          return __ Float32Constant(base::ieee754::expm1(f32_k));
        case FloatUnaryOp::Kind::kSin:
          return __ Float32Constant(SIN_IMPL(f32_k));
        case FloatUnaryOp::Kind::kCos:
          return __ Float32Constant(COS_IMPL(f32_k));
        case FloatUnaryOp::Kind::kSinh:
          return __ Float32Constant(base::ieee754::sinh(f32_k));
        case FloatUnaryOp::Kind::kCosh:
          return __ Float32Constant(base::ieee754::cosh(f32_k));
        case FloatUnaryOp::Kind::kAcos:
          return __ Float32Constant(base::ieee754::acos(f32_k));
        case FloatUnaryOp::Kind::kAsin:
          return __ Float32Constant(base::ieee754::asin(f32_k));
        case FloatUnaryOp::Kind::kAsinh:
          return __ Float32Constant(base::ieee754::asinh(f32_k));
        case FloatUnaryOp::Kind::kAcosh:
          return __ Float32Constant(base::ieee754::acosh(f32_k));
        case FloatUnaryOp::Kind::kTan:
          return __ Float32Constant(base::ieee754::tan(f32_k));
        case FloatUnaryOp::Kind::kTanh:
          return __ Float32Constant(base::ieee754::tanh(f32_k));
        case FloatUnaryOp::Kind::kLog2:
          return __ Float32Constant(base::ieee754::log2(f32_k));
        case FloatUnaryOp::Kind::kLog10:
          return __ Float32Constant(base::ieee754::log10(f32_k));
        case FloatUnaryOp::Kind::kLog1p:
          return __ Float32Constant(base::ieee754::log1p(f32_k));
        case FloatUnaryOp::Kind::kCbrt:
          return __ Float32Constant(base::ieee754::cbrt(f32_k));
        case FloatUnaryOp::Kind::kAtan:
          return __ Float32Constant(base::ieee754::atan(f32_k));
        case FloatUnaryOp::Kind::kAtanh:
          return __ Float32Constant(base::ieee754::atanh(f32_k));
      }
    } else if (double f64_k; rep == FloatRepresentation::Float64() &&
                             matcher_.MatchFloat64Constant(input, &f64_k)) {
      if (std::isnan(f64_k) && !ensure_deterministic_nan) {
        return __ Float64Constant(std::numeric_limits<double>::quiet_NaN());
      }
      switch (kind) {
        case FloatUnaryOp::Kind::kAbs:
          return __ Float64Constant(std::abs(f64_k));
        case FloatUnaryOp::Kind::kNegate:
          return __ Float64Constant(-f64_k);
        case FloatUnaryOp::Kind::kSilenceNaN:
          DCHECK(!std::isnan(f64_k));
          return __ Float64Constant(f64_k);
        case FloatUnaryOp::Kind::kRoundDown:
          return __ Float64Constant(std::floor(f64_k));
        case FloatUnaryOp::Kind::kRoundUp:
          return __ Float64Constant(std::ceil(f64_k));
        case FloatUnaryOp::Kind::kRoundToZero:
          return __ Float64Constant(std::trunc(f64_k));
        case FloatUnaryOp::Kind::kRoundTiesEven:
          DCHECK_EQ(std::nearbyint(1.5), 2);
          DCHECK_EQ(std::nearbyint(2.5), 2);
          return __ Float64Constant(std::nearbyint(f64_k));
        case FloatUnaryOp::Kind::kLog:
          return __ Float64Constant(base::ieee754::log(f64_k));
        case FloatUnaryOp::Kind::kSqrt:
          return __ Float64Constant(std::sqrt(f64_k));
        case FloatUnaryOp::Kind::kExp:
          return __ Float64Constant(base::ieee754::exp(f64_k));
        case FloatUnaryOp::Kind::kExpm1:
          return __ Float64Constant(base::ieee754::expm1(f64_k));
        case FloatUnaryOp::Kind::kSin:
          return __ Float64Constant(SIN_IMPL(f64_k));
        case FloatUnaryOp::Kind::kCos:
          return __ Float64Constant(COS_IMPL(f64_k));
        case FloatUnaryOp::Kind::kSinh:
          return __ Float64Constant(base::ieee754::sinh(f64_k));
        case FloatUnaryOp::Kind::kCosh:
          return __ Float64Constant(base::ieee754::cosh(f64_k));
        case FloatUnaryOp::Kind::kAcos:
          return __ Float64Constant(base::ieee754::acos(f64_k));
        case FloatUnaryOp::Kind::kAsin:
          return __ Float64Constant(base::ieee754::asin(f64_k));
        case FloatUnaryOp::Kind::kAsinh:
          return __ Float64Constant(base::ieee754::asinh(f64_k));
        case FloatUnaryOp::Kind::kAcosh:
          return __ Float64Constant(base::ieee754::acosh(f64_k));
        case FloatUnaryOp::Kind::kTan:
          return __ Float64Constant(base::ieee754::tan(f64_k));
        case FloatUnaryOp::Kind::kTanh:
          return __ Float64Constant(base::ieee754::tanh(f64_k));
        case FloatUnaryOp::Kind::kLog2:
          return __ Float64Constant(base::ieee754::log2(f64_k));
        case FloatUnaryOp::Kind::kLog10:
          return __ Float64Constant(base::ieee754::log10(f64_k));
        case FloatUnaryOp::Kind::kLog1p:
          return __ Float64Constant(base::ieee754::log1p(f64_k));
        case FloatUnaryOp::Kind::kCbrt:
          return __ Float64Constant(base::ieee754::cbrt(f64_k));
        case FloatUnaryOp::Kind::kAtan:
          return __ Float64Constant(base::ieee754::atan(f64_k));
        case FloatUnaryOp::Kind::kAtanh:
          return __ Float64Constant(base::ieee754::atanh(f64_k));
      }
    }
    return Next::ReduceFloatUnary(input, kind, rep);
  }
References __, v8::base::ieee754::acos(), v8::base::ieee754::acosh(), v8::base::ieee754::asin(), v8::base::ieee754::asinh(), v8::base::ieee754::atan(), v8::base::ieee754::atanh(), v8::base::ieee754::cbrt(), COS_IMPL, v8::base::ieee754::cosh(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ensure_deterministic_nan, v8::base::ieee754::exp(), v8::base::ieee754::expm1(), v8::internal::compiler::turboshaft::FloatRepresentation::Float32(), v8::internal::compiler::turboshaft::FloatRepresentation::Float64(), v8::internal::compiler::turboshaft::FloatUnaryOp::kAbs, v8::internal::compiler::turboshaft::FloatUnaryOp::kAcos, v8::internal::compiler::turboshaft::FloatUnaryOp::kAcosh, v8::internal::compiler::turboshaft::FloatUnaryOp::kAsin, v8::internal::compiler::turboshaft::FloatUnaryOp::kAsinh, v8::internal::compiler::turboshaft::FloatUnaryOp::kAtan, v8::internal::compiler::turboshaft::FloatUnaryOp::kAtanh, v8::internal::compiler::turboshaft::FloatUnaryOp::kCbrt, v8::internal::compiler::turboshaft::FloatUnaryOp::kCos, v8::internal::compiler::turboshaft::FloatUnaryOp::kCosh, v8::internal::compiler::turboshaft::FloatUnaryOp::kExp, v8::internal::compiler::turboshaft::FloatUnaryOp::kExpm1, v8::internal::compiler::turboshaft::FloatUnaryOp::kLog, v8::internal::compiler::turboshaft::FloatUnaryOp::kLog10, v8::internal::compiler::turboshaft::FloatUnaryOp::kLog1p, v8::internal::compiler::turboshaft::FloatUnaryOp::kLog2, v8::internal::compiler::turboshaft::FloatUnaryOp::kNegate, v8::internal::compiler::turboshaft::FloatUnaryOp::kRoundDown, v8::internal::compiler::turboshaft::FloatUnaryOp::kRoundTiesEven, v8::internal::compiler::turboshaft::FloatUnaryOp::kRoundToZero, v8::internal::compiler::turboshaft::FloatUnaryOp::kRoundUp, v8::internal::compiler::turboshaft::FloatUnaryOp::kSilenceNaN, v8::internal::compiler::turboshaft::FloatUnaryOp::kSin, v8::internal::compiler::turboshaft::FloatUnaryOp::kSinh, v8::internal::compiler::turboshaft::FloatUnaryOp::kSqrt, v8::internal::compiler::turboshaft::FloatUnaryOp::kTan, v8::internal::compiler::turboshaft::FloatUnaryOp::kTanh, v8::base::ieee754::log(), v8::base::ieee754::log10(), v8::base::ieee754::log1p(), v8::base::ieee754::log2(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat32Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat64Constant(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), SIN_IMPL, v8::base::ieee754::sinh(), v8::base::ieee754::tan(), and v8::base::ieee754::tanh().
IsBit()
template<class Next >
bool v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsBit (V< Word > value) [inline], [private]
Definition at line 2560 of file machine-optimization-reducer.h.
{ return matcher_.Is<ComparisonOp>(value); }
References v8::internal::compiler::turboshaft::OperationMatcher::Is(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
IsFloat32ConvertedToFloat64()
template<class Next >
bool v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsFloat32ConvertedToFloat64 (V< Any > value) [inline], [private]
Definition at line 2532 of file machine-optimization-reducer.h.
                                                 {
    if (V<Float32> input; matcher_.MatchChange<Float32>(
            value, &input, ChangeOp::Kind::kFloatConversion, {},
            RegisterRepresentation::Float32(),
            RegisterRepresentation::Float64())) {
      return true;
    }
    if (double c;
        matcher_.MatchFloat64Constant(value, &c) && DoubleToFloat32(c) == c) {
      return true;
    }
    return false;
  }
References v8::internal::DoubleToFloat32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::ChangeOp::kFloatConversion, v8::internal::compiler::turboshaft::OperationMatcher::MatchChange(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat64Constant(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison().
IsInt16()
template<class Next >
bool v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsInt16 (V< Word > value) [inline], [private]
Definition at line 2569 of file machine-optimization-reducer.h.
                              {
    if (auto* op = matcher_.TryCast<LoadOp>(value)) {
      return op->loaded_rep == any_of(MemoryRepresentation::Int16(),
                                      MemoryRepresentation::Int8());
    }
    return false;
  }
References v8::internal::compiler::turboshaft::any_of(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int8(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::TryCast(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift().
IsInt8()
template<class Next >
bool v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsInt8 (V< Word > value) [inline], [private]
Definition at line 2562 of file machine-optimization-reducer.h.
                             {
    if (auto* op = matcher_.TryCast<LoadOp>(value)) {
      return op->loaded_rep == MemoryRepresentation::Int8();
    }
    return false;
  }
References v8::internal::compiler::turboshaft::MemoryRepresentation::Int8(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::TryCast(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift().
IsNegativePowerOfTwo()
template<class Next >
static constexpr bool v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsNegativePowerOfTwo (int64_t x) [inline], [static], [constexpr], [private]
Definition at line 2910 of file machine-optimization-reducer.h.
                                                        {
    if (x >= 0) return false;
    if (x == std::numeric_limits<int64_t>::min()) return true;
    int64_t x_abs = -x; // This can't overflow after the check above.
    DCHECK_GE(x_abs, 1); // The subtraction below can't underflow.
    return (x_abs & (x_abs - 1)) == 0;
  }
References DCHECK_GE.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
IsWord32ConvertedToWord64()
template<class Next >
bool v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsWord32ConvertedToWord64 (V< Any > value, std::optional< bool > * sign_extended = nullptr) [inline], [private]
Definition at line 2577 of file machine-optimization-reducer.h.
                                                                             {
    if (const ChangeOp* change_op = matcher_.TryCast<ChangeOp>(value)) {
      if (change_op->from == WordRepresentation::Word32() &&
          change_op->to == WordRepresentation::Word64()) {
        if (change_op->kind == ChangeOp::Kind::kSignExtend) {
          if (sign_extended) *sign_extended = true;
          return true;
        } else if (change_op->kind == ChangeOp::Kind::kZeroExtend) {
          if (sign_extended) *sign_extended = false;
          return true;
        }
      }
    }
    if (int64_t c; matcher_.MatchIntegralWord64Constant(value, &c) &&
                   c >= std::numeric_limits<int32_t>::min()) {
      if (c < 0) {
        if (sign_extended) *sign_extended = true;
        return true;
      } else if (c <= std::numeric_limits<int32_t>::max()) {
        // Sign- and zero-extension produce the same result.
        if (sign_extended) *sign_extended = {};
        return true;
      } else if (c <= std::numeric_limits<uint32_t>::max()) {
        if (sign_extended) *sign_extended = false;
        return true;
      }
    }
    return false;
  }
References v8::internal::compiler::turboshaft::ChangeOp::kSignExtend, v8::internal::compiler::turboshaft::ChangeOp::kZeroExtend, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord64Constant(), v8::internal::compiler::turboshaft::OperationMatcher::TryCast(), v8::internal::value, v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoWord32ToWord64Conversion(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
Load()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load (OpIndex base_idx, OptionalOpIndex index, LoadOp::Kind kind, MemoryRepresentation loaded_rep, RegisterRepresentation result_rep, int32_t offset, uint8_t element_scale) [inline]
Definition at line 2029 of file machine-optimization-reducer.h.
                                              {
    LABEL_BLOCK(no_change) {
      return Next::ReduceLoad(base_idx, index, kind, loaded_rep, result_rep,
                              offset, element_scale);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
#if V8_TARGET_ARCH_32_BIT
    if (kind.is_atomic && loaded_rep.SizeInBytes() == 8) {
      // AtomicWord32PairOp (as used by Int64Lowering) cannot handle
      // element_scale != 0 currently.
      // TODO(jkummerow): Add support for element_scale in AtomicWord32PairOp.
      goto no_change;
    }
#endif
    while (true) {
      index = ReduceMemoryIndex(index.value_or_invalid(), &offset,
                                &element_scale, kind.tagged_base);
      if (!kind.tagged_base && !index.valid()) {
        if (V<WordPtr> left, right;
            matcher_.MatchWordAdd(base_idx, &left, &right,
                                  WordRepresentation::WordPtr()) &&
            TryAdjustOffset(&offset, matcher_.Get(right), element_scale,
                            kind.tagged_base)) {
          base_idx = left;
          continue;
        }
      }
      break;
    }
    if (!index.valid() && matcher_.Is<ConstantOp>(base_idx)) {
      const ConstantOp& base = matcher_.Cast<ConstantOp>(base_idx);
      if (base.kind == any_of(ConstantOp::Kind::kHeapObject,
                              ConstantOp::Kind::kCompressedHeapObject)) {
        if (offset == HeapObject::kMapOffset) {
          // Only few loads should be loading the map from a ConstantOp
          // HeapObject, so unparking the JSHeapBroker here rather than before
          // the optimization pass itself it probably more efficient.
          DCHECK_IMPLIES(
              __ data()->pipeline_kind() != TurboshaftPipelineKind::kCSA,
              broker != nullptr);
          if (broker != nullptr) {
            UnparkedScopeIfNeeded scope(broker);
            AllowHandleDereference allow_handle_dereference;
            OptionalMapRef map = TryMakeRef(broker, base.handle()->map());
            if (MapLoadCanBeConstantFolded(map)) {
              return __ HeapConstant(map->object());
            }
          }
        }
        // TODO(dmercadier): consider constant-folding other accesses, in
        // particular for constant objects (ie, if
        // base.handle()->InReadOnlySpace() is true). We have to be a bit
        // careful though, because loading could be invalid (since we could
        // be in unreachable code). (all objects have a map, so loading the map
        // should always be safe, regardless of whether we are generating
        // unreachable code or not)
      }
    }
    // If index is invalid and base is `left+right`, we use `left` as base and
    // `right` as index.
    if (!index.valid() && matcher_.Is<Opmask::kWord64Add>(base_idx)) {
      DCHECK_EQ(element_scale, 0);
      const WordBinopOp& base = matcher_.Cast<WordBinopOp>(base_idx);
      base_idx = base.left();
      index = base.right();
      // We go through the Load stack again, which might merge {index} into
      // {offset}, or just do other optimizations on this Load.
      return __ Load(base_idx, index, kind, loaded_rep, result_rep, offset,
                     element_scale);
    }
    return Next::ReduceLoad(base_idx, index, kind, loaded_rep, result_rep,
                            offset, element_scale);
  }
References __, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::broker, v8::internal::compiler::turboshaft::OperationMatcher::Cast(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::ConstantOp::handle(), v8::internal::index, v8::internal::compiler::turboshaft::OperationMatcher::Is(), v8::internal::compiler::turboshaft::ConstantOp::kCompressedHeapObject, v8::internal::compiler::turboshaft::kCSA, v8::internal::compiler::turboshaft::ConstantOp::kHeapObject, v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::HeapObject::kMapOffset, LABEL_BLOCK, v8::internal::compiler::turboshaft::WordBinopOp::left(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::MapLoadCanBeConstantFolded(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceMemoryIndex(), v8::internal::compiler::turboshaft::WordBinopOp::right(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustOffset(), v8::internal::compiler::TryMakeRef(), and v8::internal::compiler::turboshaft::WordRepresentation::WordPtr().
MapLoadCanBeConstantFolded()
template<class Next >
bool v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::MapLoadCanBeConstantFolded (OptionalMapRef map) [inline], [private]
Definition at line 2893 of file machine-optimization-reducer.h.
                                                      {
    if (!map.has_value()) return false;
    if (map->IsJSObjectMap() && map->is_stable()) {
      broker->dependencies()->DependOnStableMap(*map);
      // For JS objects, this is only safe is the map is stable.
      return true;
    }
    if (map->instance_type() ==
        any_of(BIG_INT_BASE_TYPE, HEAP_NUMBER_TYPE, ODDBALL_TYPE)) {
      return true;
    }
    return false;
  }
References v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::broker, v8::internal::compiler::JSHeapBroker::dependencies(), and v8::internal::compiler::CompilationDependencies::DependOnStableMap().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load().
MatchBoolConstant()
template<class Next >
std::optional<bool> v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::MatchBoolConstant (V< Any > condition) [inline], [private]
Definition at line 2881 of file machine-optimization-reducer.h.
                                                        {
    if (uint32_t value;
        matcher_.MatchIntegralWord32Constant(condition, &value)) {
      return value != 0;
    }
    return std::nullopt;
  }
References v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Branch(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::DeoptimizeIf(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceBranchCondition(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Select(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::StaticAssert().
OverflowCheckedBinop()
template<class Next >
V<Tuple<Word, Word32> > REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop (V< Word > left, V< Word > right, OverflowCheckedBinopOp::Kind kind, WordRepresentation rep) [inline]
Definition at line 1300 of file machine-optimization-reducer.h.
                              {
    if (ShouldSkipOptimizationStep()) {
      return Next::ReduceOverflowCheckedBinop(left, right, kind, rep);
    }
    using Kind = OverflowCheckedBinopOp::Kind;
    if (OverflowCheckedBinopOp::IsCommutative(kind) &&
        matcher_.Is<ConstantOp>(left) && !matcher_.Is<ConstantOp>(right)) {
      return ReduceOverflowCheckedBinop(right, left, kind, rep);
    }
    if (rep == WordRepresentation::Word32()) {
      left = TryRemoveWord32ToWord64Conversion(left);
      right = TryRemoveWord32ToWord64Conversion(right);
    }
    // constant folding
    if (rep == WordRepresentation::Word32()) {
      if (int32_t k1, k2; matcher_.MatchIntegralWord32Constant(left, &k1) &&
                          matcher_.MatchIntegralWord32Constant(right, &k2)) {
        bool overflow;
        int32_t res;
        switch (kind) {
          case OverflowCheckedBinopOp::Kind::kSignedAdd:
            overflow = base::bits::SignedAddOverflow32(k1, k2, &res);
            break;
          case OverflowCheckedBinopOp::Kind::kSignedMul:
            overflow = base::bits::SignedMulOverflow32(k1, k2, &res);
            break;
          case OverflowCheckedBinopOp::Kind::kSignedSub:
            overflow = base::bits::SignedSubOverflow32(k1, k2, &res);
            break;
        }
        return __ Tuple(__ Word32Constant(res), __ Word32Constant(overflow));
      }
    } else {
      DCHECK_EQ(rep, WordRepresentation::Word64());
      if (int64_t k1, k2; matcher_.MatchIntegralWord64Constant(left, &k1) &&
                          matcher_.MatchIntegralWord64Constant(right, &k2)) {
        bool overflow;
        int64_t res;
        switch (kind) {
          case OverflowCheckedBinopOp::Kind::kSignedAdd:
            overflow = base::bits::SignedAddOverflow64(k1, k2, &res);
            break;
          case OverflowCheckedBinopOp::Kind::kSignedMul:
            overflow = base::bits::SignedMulOverflow64(k1, k2, &res);
            break;
          case OverflowCheckedBinopOp::Kind::kSignedSub:
            overflow = base::bits::SignedSubOverflow64(k1, k2, &res);
            break;
        }
        return __ Tuple(__ Word64Constant(res), __ Word32Constant(overflow));
      }
    }
    // left + 0 => (left, false)
    // left - 0 => (left, false)
    if (kind == any_of(Kind::kSignedAdd, Kind::kSignedSub) &&
        matcher_.MatchZero(right)) {
      return __ Tuple(left, __ Word32Constant(0));
    }
    if (kind == Kind::kSignedMul) {
      if (int64_t k; matcher_.MatchIntegralWordConstant(right, rep, &k)) {
        // left * 0 => (0, false)
        if (k == 0) {
          return __ Tuple(__ WordConstant(0, rep), __ Word32Constant(false));
        }
        // left * 1 => (left, false)
        if (k == 1) {
          return __ Tuple(left, __ Word32Constant(false));
        }
        // left * -1 => 0 - left
        if (k == -1) {
          return __ IntSubCheckOverflow(__ WordConstant(0, rep), left, rep);
        }
        // left * 2 => left + left
        if (k == 2) {
          return __ IntAddCheckOverflow(left, left, rep);
        }
      }
    }
    if (kind == Kind::kSignedAdd && left == right) {
      uint16_t amount;
      // UntagSmi(x) + UntagSmi(x) => (x, false)
      // (where UntagSmi(x) = x >> 1 with a ShiftOutZeros shift)
      if (V<Word32> x; matcher_.MatchConstantShiftRightArithmeticShiftOutZeros(
                           left, &x, WordRepresentation::Word32(), &amount) &&
                       amount == 1) {
        return __ Tuple(x, __ Word32Constant(0));
      }
      // t1 = UntagSmi(x)
      // t2 = t1 bitwise_op k
      // t2 + t2
      // => x bitwise_op (k << 1)
      // (where UntagSmi(x) = x >> 1 with a ShiftOutZeros shift)
      WordBinopOp::Kind bitwise_op_kind;
      if (V<Word32> t1, tk; matcher_.MatchWordBinop<Word32>(
              left, &t1, &tk, &bitwise_op_kind, WordRepresentation::Word32())) {
        if (V<Word32> x;
            matcher_.MatchConstantShiftRightArithmeticShiftOutZeros(
                t1, &x, WordRepresentation::Word32(), &amount) &&
            amount == 1) {
          if (int32_t k; matcher_.MatchIntegralWord32Constant(tk, &k)) {
            switch (bitwise_op_kind) {
              case WordBinopOp::Kind::kBitwiseAnd:
              case WordBinopOp::Kind::kBitwiseOr:
              case WordBinopOp::Kind::kBitwiseXor:
                // If the topmost two bits are not identical then retagging
                // the smi could cause an overflow, so we do not optimize that
                // here.
                if (((k >> 31) & 0b1) == ((k >> 30) & 0b1)) {
                  return __ Tuple(__ WordBinop(x, __ Word32Constant(k << 1),
                                               bitwise_op_kind,
                                               WordRepresentation::Word32()),
                                  __ Word32Constant(0));
                }
                break;
              default:
                break;
            }
          }
        }
      }
    }
    return Next::ReduceOverflowCheckedBinop(left, right, kind, rep);
  }
References __, v8::internal::compiler::turboshaft::any_of(), DCHECK_EQ, v8::internal::compiler::turboshaft::OperationMatcher::Is(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::IsCommutative(), v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseAnd, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseOr, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseXor, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kSignedAdd, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kSignedMul, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kSignedSub, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord64Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), v8::internal::overflow, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::base::bits::SignedAddOverflow32(), v8::base::bits::SignedAddOverflow64(), v8::base::bits::SignedMulOverflow32(), v8::base::bits::SignedMulOverflow64(), v8::base::bits::SignedSubOverflow32(), v8::base::bits::SignedSubOverflow64(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryRemoveWord32ToWord64Conversion(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), v8::internal::compiler::turboshaft::WordRepresentation::Word64(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
ReduceBranchCondition()
template<class Next >
std::optional<V<Word32> > v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceBranchCondition (V< Word32 > condition, bool * negated) [inline], [private]
Definition at line 2802 of file machine-optimization-reducer.h.
                                                                {
    // TODO(dmercadier): consider generalizing this function both Word32 and
    // Word64.
    bool reduced = false;
    while (true) {
      // x == 0 => x with flipped branches
      if (V<Word32> left, right;
          matcher_.MatchEqual(condition, &left, &right) &&
          matcher_.MatchZero(right)) {
        reduced = true;
        condition = left;
        *negated = !*negated;
        continue;
      }
      // x - y => x == y with flipped branches
      if (V<Word32> left, right; matcher_.MatchWordSub(
              condition, &left, &right, WordRepresentation::Word32())) {
        reduced = true;
        condition = __ Word32Equal(left, right);
        *negated = !*negated;
        continue;
      }
      // x & (1 << k) == (1 << k) => x & (1 << k)
      if (V<Word32> left, right;
          matcher_.MatchEqual(condition, &left, &right)) {
        V<Word32> x, mask;
        uint32_t k1, k2;
        if (matcher_.MatchBitwiseAnd(left, &x, &mask,
                                     WordRepresentation::Word32()) &&
            matcher_.MatchIntegralWord32Constant(mask, &k1) &&
            matcher_.MatchIntegralWord32Constant(right, &k2) && k1 == k2 &&
            base::bits::IsPowerOfTwo(k1)) {
          reduced = true;
          condition = left;
          continue;
        }
      }
      // (x >> k1) & k2 => x & (k2 << k1)
      {
        V<Word32> shift, k2_index, x;
        int k1_int;
        uint32_t k1, k2;
        if (matcher_.MatchBitwiseAnd(condition, &shift, &k2_index,
                                     WordRepresentation::Word32()) &&
            matcher_.MatchConstantRightShift(
                shift, &x, WordRepresentation::Word32(), &k1_int) &&
            matcher_.MatchIntegralWord32Constant(k2_index, &k2)) {
          k1 = static_cast<uint32_t>(k1_int);
          if (k1 <= base::bits::CountLeadingZeros(k2) &&
              (static_cast<uint64_t>(k2) << k1 <=
               std::numeric_limits<uint32_t>::max())) {
            return __ Word32BitwiseAnd(x, k2 << k1);
          }
        }
      }
      // Select(x, true, false) => x
      if (const SelectOp* select = matcher_.TryCast<SelectOp>(condition)) {
        auto left_val = MatchBoolConstant(select->vtrue());
        auto right_val = MatchBoolConstant(select->vfalse());
        if (left_val && right_val) {
          if (*left_val == *right_val) {
            // Select(x, v, v) => v
            return __ Word32Constant(*left_val);
          }
          if (*left_val == false) {
            // Select(x, false, true) => !x
            *negated = !*negated;
          }
          condition = select->cond();
          reduced = true;
          continue;
        }
      }
      break;
    }
    return reduced ? std::optional<V<Word32>>(condition) : std::nullopt;
  }
References __, v8::base::bits::CountLeadingZeros(), v8::base::bits::IsPowerOfTwo(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::MatchBoolConstant(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), v8::internal::compiler::turboshaft::OperationMatcher::TryCast(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Branch(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::DeoptimizeIf().
ReduceCompareEqual()
template<class Next >
V<Word32> v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual (V< Any > left, V< Any > right, RegisterRepresentation rep) [inline], [private]
Definition at line 2300 of file machine-optimization-reducer.h.
                                                           {
    if (left == right && !rep.IsFloat()) {
      return __ Word32Constant(1);
    }
    if (rep == WordRepresentation::Word32()) {
      left = TryRemoveWord32ToWord64Conversion(V<Word>::Cast(left));
      right = TryRemoveWord32ToWord64Conversion(V<Word>::Cast(right));
    }
    if (matcher_.Is<ConstantOp>(left) && !matcher_.Is<ConstantOp>(right)) {
      return ReduceCompareEqual(right, left, rep);
    }
    if (matcher_.Is<ConstantOp>(right)) {
      if (matcher_.Is<ConstantOp>(left)) {
        // k1 == k2 => k
        switch (rep.value()) {
          case RegisterRepresentation::Word32():
          case RegisterRepresentation::Word64(): {
            if (uint64_t k1, k2; matcher_.MatchIntegralWordConstant(
                                     left, WordRepresentation(rep), &k1) &&
                                 matcher_.MatchIntegralWordConstant(
                                     right, WordRepresentation(rep), &k2)) {
              return __ Word32Constant(k1 == k2);
            }
            break;
          }
          case RegisterRepresentation::Float32(): {
            if (float k1, k2; matcher_.MatchFloat32Constant(left, &k1) &&
                              matcher_.MatchFloat32Constant(right, &k2)) {
              return __ Word32Constant(k1 == k2);
            }
            break;
          }
          case RegisterRepresentation::Float64(): {
            if (double k1, k2; matcher_.MatchFloat64Constant(left, &k1) &&
                               matcher_.MatchFloat64Constant(right, &k2)) {
              return __ Word32Constant(k1 == k2);
            }
            break;
          }
          case RegisterRepresentation::Tagged(): {
            if (Handle<HeapObject> o1, o2;
                matcher_.MatchHeapConstant(left, &o1) &&
                matcher_.MatchHeapConstant(right, &o2)) {
              UnparkedScopeIfNeeded unparked(broker);
              if (IsString(*o1) && IsString(*o2)) {
                // If handles refer to the same object, we can eliminate the
                // check.
                if (o1.address() == o2.address()) return __ Word32Constant(1);
                // But if they are different, we cannot eliminate the
                // comparison, because the objects might be different now, but
                // if they contain the same content, they might be internalized
                // to the same object eventually.
                break;
              }
              return __ Word32Constant(o1.address() == o2.address());
            }
            break;
          }
          default:
            UNREACHABLE();
        }
      }
      if (rep.IsWord()) {
        WordRepresentation rep_w{rep};
        // x - y == 0 => x == y
        if (V<Word> x, y; matcher_.MatchWordSub(left, &x, &y, rep_w) &&
                          matcher_.MatchZero(right)) {
          return ReduceCompareEqual(x, y, rep);
        }
        {
          // ((x >> shift_amount) & mask) == k
          // => (x & (mask << shift_amount)) == (k << shift_amount)
          V<Word> shift, x, mask_op;
          int shift_amount;
          uint64_t mask, k;
          if (matcher_.MatchBitwiseAnd(left, &shift, &mask_op, rep_w) &&
              matcher_.MatchConstantRightShift(shift, &x, rep_w,
                                               &shift_amount) &&
              matcher_.MatchIntegralWordConstant(mask_op, rep_w, &mask) &&
              matcher_.MatchIntegralWordConstant(right, rep_w, &k) &&
              mask <= rep.MaxUnsignedValue() >> shift_amount &&
              k <= rep.MaxUnsignedValue() >> shift_amount) {
            return ReduceCompareEqual(
                __ WordBitwiseAnd(
                    x, __ WordConstant(mask << shift_amount, rep_w), rep_w),
                __ WordConstant(k << shift_amount, rep_w), rep_w);
          }
        }
        {
          // (x >> k1) == k2 => x == (k2 << k1) if shifts reversible
          // Only perform the transformation if the shift is not used yet, to
          // avoid keeping both the shift and x alive.
          V<Word> x;
          uint16_t k1;
          int64_t k2;
          if (matcher_.MatchConstantShiftRightArithmeticShiftOutZeros(
                  left, &x, rep_w, &k1) &&
              matcher_.MatchIntegralWordConstant(right, rep_w, &k2) &&
              CountLeadingSignBits(k2, rep_w) > k1 &&
              matcher_.Get(left).saturated_use_count.IsZero()) {
            return __ Equal(
                x, __ WordConstant(base::bits::Unsigned(k2) << k1, rep_w),
                rep_w);
          }
        }
        // Map 64bit to 32bit equals.
        if (rep_w == WordRepresentation::Word64()) {
          std::optional<bool> left_sign_extended;
          std::optional<bool> right_sign_extended;
          if (IsWord32ConvertedToWord64(left, &left_sign_extended) &&
              IsWord32ConvertedToWord64(right, &right_sign_extended)) {
            if (left_sign_extended == right_sign_extended) {
              return __ Equal(
                  UndoWord32ToWord64Conversion(V<Word64>::Cast(left)),
                  UndoWord32ToWord64Conversion(V<Word64>::Cast(right)),
                  WordRepresentation::Word32());
            }
          }
        }
      }
    }
    return Next::ReduceComparison(left, right, ComparisonOp::Kind::kEqual, rep);
  }
References __, v8::internal::HandleBase::address(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::broker, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::CountLeadingSignBits(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::OperationMatcher::Is(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::IsFloat(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::IsWord(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsWord32ConvertedToWord64(), v8::internal::compiler::turboshaft::SaturatedUint8::IsZero(), v8::internal::compiler::turboshaft::ComparisonOp::kEqual, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat32Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat64Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchHeapConstant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::MaxUnsignedValue(), v8::internal::compiler::turboshaft::Operation::saturated_use_count, v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryRemoveWord32ToWord64Conversion(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoWord32ToWord64Conversion(), v8::internal::UNREACHABLE(), v8::base::bits::Unsigned(), v8::internal::compiler::turboshaft::RegisterRepresentation::value(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word64(), v8::internal::compiler::turboshaft::WordRepresentation::Word64(), and v8::internal::y.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison().
ReduceMemoryIndex()
template<class Next >
OpIndex v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceMemoryIndex (OpIndex index, int32_t * offset, uint8_t * element_scale, bool tagged_base) [inline], [private]
Definition at line 2494 of file machine-optimization-reducer.h.
                                                                      {
    while (index.valid()) {
      const Operation& index_op = matcher_.Get(index);
      if (TryAdjustOffset(offset, index_op, *element_scale, tagged_base)) {
        index = OpIndex::Invalid();
        *element_scale = 0;
      } else if (TryAdjustIndex(*offset, &index, index_op, *element_scale)) {
        *element_scale = 0;
        *offset = 0;
        // This function cannot optimize the index further since at this point
        // it's just a WordPtrConstant.
        return index;
      } else if (const ShiftOp* shift_op = index_op.TryCast<ShiftOp>()) {
        if (shift_op->kind == ShiftOp::Kind::kShiftLeft &&
            TryAdjustElementScale(element_scale, shift_op->right())) {
          index = shift_op->left();
          continue;
        }
      } else if (const WordBinopOp* binary_op =
                     index_op.TryCast<WordBinopOp>()) {
        // TODO(jkummerow): This doesn't trigger for wasm32 memory operations
        // on 64-bit platforms, because `index_op` is a `Change` (from uint32
        // to uint64) in that case, and that Change's input is the addition
        // we're looking for. When we fix that, we must also teach the x64
        // instruction selector to support xchg with index *and* offset.
        if (binary_op->kind == WordBinopOp::Kind::kAdd &&
            TryAdjustOffset(offset, matcher_.Get(binary_op->right()),
                            *element_scale, tagged_base)) {
          index = binary_op->left();
          continue;
        }
      }
      break;
    }
    return index;
  }
References v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::index, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::WordBinopOp::kAdd, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustElementScale(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustIndex(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustOffset(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store().
ReduceSignedDiv()
template<class Next >
V<Word> v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceSignedDiv (V< Word > left, int64_t right, WordRepresentation rep) [inline], [private]
Definition at line 2684 of file machine-optimization-reducer.h.
                                                                               {
    // left / -1 => 0 - left
    if (right == -1) {
      return __ WordSub(__ WordConstant(0, rep), left, rep);
    }
    // left / 0 => 0
    if (right == 0) {
      return __ WordConstant(0, rep);
    }
    // left / 1 => left
    if (right == 1) {
      return left;
    }
    // left / MinSignedValue => left == MinSignedValue
    if (right == rep.MinSignedValue()) {
      V<Word32> equal_op = __ Equal(left, __ WordConstant(right, rep), rep);
      if (rep == WordRepresentation::Word64()) {
        return __ ChangeUint32ToUint64(equal_op);
      } else {
        return equal_op;
      }
    }
    // left / -right => -(left / right)
    if (right < 0) {
      DCHECK_NE(right, rep.MinSignedValue());
      return __ WordSub(__ WordConstant(0, rep),
                        ReduceSignedDiv(left, Abs(right), rep), rep);
    }
    V<Word> quotient = left;
    if (base::bits::IsPowerOfTwo(right)) {
      uint32_t shift = base::bits::WhichPowerOfTwo(right);
      DCHECK_GT(shift, 0);
      if (shift > 1) {
        quotient = __ ShiftRightArithmetic(quotient, rep.bit_width() - 1, rep);
      }
      quotient = __ ShiftRightLogical(quotient, rep.bit_width() - shift, rep);
      quotient = __ WordAdd(quotient, left, rep);
      quotient = __ ShiftRightArithmetic(quotient, shift, rep);
      return quotient;
    }
    DCHECK_GT(right, 0);
    // Compute the magic number for `right`, using a generic lambda to treat
    // 32- and 64-bit uniformly.
    auto LowerToMul = [this, left](auto right, WordRepresentation rep) {
      base::MagicNumbersForDivision<decltype(right)> magic =
          base::SignedDivisionByConstant(right);
      V<Word> quotient = __ IntMulOverflownBits(
          left, __ WordConstant(magic.multiplier, rep), rep);
      if (magic.multiplier < 0) {
        quotient = __ WordAdd(quotient, left, rep);
      }
      V<Word> sign_bit = __ ShiftRightLogical(left, rep.bit_width() - 1, rep);
      return __ WordAdd(__ ShiftRightArithmetic(quotient, magic.shift, rep),
                        sign_bit, rep);
    };
    if (rep == WordRepresentation::Word32()) {
      return LowerToMul(static_cast<int32_t>(right),
                        WordRepresentation::Word32());
    } else {
      DCHECK_EQ(rep, WordRepresentation::Word64());
      return LowerToMul(static_cast<int64_t>(right),
                        WordRepresentation::Word64());
    }
  }
References __, v8::internal::Abs(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::bit_width(), DCHECK_EQ, DCHECK_GT, DCHECK_NE, v8::base::bits::IsPowerOfTwo(), v8::internal::compiler::turboshaft::WordRepresentation::MinSignedValue(), v8::base::SignedDivisionByConstant(), v8::base::bits::WhichPowerOfTwo(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
ReduceUnsignedDiv()
template<class Next >
V<Word> v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceUnsignedDiv (V< Word > left, uint64_t right, WordRepresentation rep) [inline], [private]
Definition at line 2750 of file machine-optimization-reducer.h.
                                                    {
    // left / 0 => 0
    if (right == 0) {
      return __ WordConstant(0, rep);
    }
    // left / 1 => left
    if (right == 1) {
      return left;
    }
    // left / 2^k => left >> k
    if (base::bits::IsPowerOfTwo(right)) {
      return __ ShiftRightLogical(left, base::bits::WhichPowerOfTwo(right),
                                  rep);
    }
    DCHECK_GT(right, 0);
    // If `right` is even, we can avoid using the expensive fixup by
    // shifting `left` upfront.
    unsigned const shift = base::bits::CountTrailingZeros(right);
    left = __ ShiftRightLogical(left, shift, rep);
    right >>= shift;
    // Compute the magic number for `right`, using a generic lambda to treat
    // 32- and 64-bit uniformly.
    auto LowerToMul = [this, left, shift](auto right, WordRepresentation rep) {
      base::MagicNumbersForDivision<decltype(right)> const mag =
          base::UnsignedDivisionByConstant(right, shift);
      V<Word> quotient = __ UintMulOverflownBits(
          left, __ WordConstant(mag.multiplier, rep), rep);
      if (mag.add) {
        DCHECK_GE(mag.shift, 1);
        // quotient = (((left - quotient) >> 1) + quotient) >> (mag.shift -
        // 1)
        quotient = __ ShiftRightLogical(
            __ WordAdd(
                __ ShiftRightLogical(__ WordSub(left, quotient, rep), 1, rep),
                quotient, rep),
            mag.shift - 1, rep);
      } else {
        quotient = __ ShiftRightLogical(quotient, mag.shift, rep);
      }
      return quotient;
    };
    if (rep == WordRepresentation::Word32()) {
      return LowerToMul(static_cast<uint32_t>(right),
                        WordRepresentation::Word32());
    } else {
      DCHECK_EQ(rep, WordRepresentation::Word64());
      return LowerToMul(static_cast<uint64_t>(right),
                        WordRepresentation::Word64());
    }
  }
References __, v8::base::bits::CountTrailingZeros(), DCHECK_EQ, DCHECK_GE, DCHECK_GT, v8::base::bits::IsPowerOfTwo(), v8::base::UnsignedDivisionByConstant(), v8::base::bits::WhichPowerOfTwo(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
ReduceWithTruncation()
template<class Next >
V<Word> v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceWithTruncation (V< Word > value, uint64_t truncation_mask, WordRepresentation rep) [inline], [private]
Definition at line 2639 of file machine-optimization-reducer.h.
                                                       {
    { // Remove bitwise-and with a mask whose zero-bits are not observed.
      V<Word> input, mask;
      uint64_t mask_value;
      if (matcher_.MatchBitwiseAnd(value, &input, &mask, rep) &&
          matcher_.MatchIntegralWordConstant(mask, rep, &mask_value)) {
        if ((mask_value & truncation_mask) == truncation_mask) {
          return ReduceWithTruncation(input, truncation_mask, rep);
        }
      }
    }
    {
      int left_shift_amount;
      int right_shift_amount;
      WordRepresentation value_rep;
      V<Word> left_shift;
      ShiftOp::Kind right_shift_kind;
      V<Word> left_shift_input;
      if (matcher_.MatchConstantShift(value, &left_shift, &right_shift_kind,
                                      &value_rep, &right_shift_amount) &&
          ShiftOp::IsRightShift(right_shift_kind) &&
          matcher_.MatchConstantShift(left_shift, &left_shift_input,
                                      ShiftOp::Kind::kShiftLeft, value_rep,
                                      &left_shift_amount) &&
          ((value_rep.MaxUnsignedValue() >> right_shift_amount) &
           truncation_mask) == truncation_mask) {
        if (left_shift_amount == right_shift_amount) {
          return left_shift_input;
        } else if (left_shift_amount < right_shift_amount) {
          V<Word32> shift_amount =
              __ Word32Constant(right_shift_amount - left_shift_amount);
          return __ Shift(left_shift_input, shift_amount, right_shift_kind,
                          value_rep);
        } else if (left_shift_amount > right_shift_amount) {
          V<Word32> shift_amount =
              __ Word32Constant(left_shift_amount - right_shift_amount);
          return __ Shift(left_shift_input, shift_amount,
                          ShiftOp::Kind::kShiftLeft, value_rep);
        }
      }
    }
    return value;
  }
References __, v8::internal::compiler::turboshaft::ShiftOp::IsRightShift(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant(), v8::internal::compiler::turboshaft::WordRepresentation::MaxUnsignedValue(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store().
Select()
template<class Next >
V<Any> REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Select (V< Word32 > cond, V< Any > vtrue, V< Any > vfalse, RegisterRepresentation rep, BranchHint hint, SelectOp::Implementation implem) [inline]
Definition at line 1909 of file machine-optimization-reducer.h.
                                                       {
    LABEL_BLOCK(no_change) {
      return Next::ReduceSelect(cond, vtrue, vfalse, rep, hint, implem);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    // Try to remove the Select.
    if (std::optional<bool> decision = MatchBoolConstant(cond)) {
      return *decision ? vtrue : vfalse;
    }
    goto no_change;
  }
References LABEL_BLOCK, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::MatchBoolConstant(), and v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep().
Shift()
template<class Next >
V<Word> REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift (V< Word > left, V< Word32 > right, ShiftOp::Kind kind, WordRepresentation rep) [inline]
Definition at line 1690 of file machine-optimization-reducer.h.
                                                {
    if (ShouldSkipOptimizationStep()) {
      return Next::ReduceShift(left, right, kind, rep);
    }
    if (rep == WordRepresentation::Word32()) {
      left = TryRemoveWord32ToWord64Conversion(left);
    }
    using Kind = ShiftOp::Kind;
    uint64_t c_unsigned;
    int64_t c_signed;
    if (matcher_.MatchIntegralWordConstant(left, rep, &c_unsigned, &c_signed)) {
      if (uint32_t amount;
          matcher_.MatchIntegralWord32Constant(right, &amount)) {
        amount = amount & (rep.bit_width() - 1);
        switch (kind) {
          case Kind::kShiftRightArithmeticShiftOutZeros:
            if (base::bits::CountTrailingZeros(c_signed) < amount) {
              // This assumes that we never hoist operations to before their
              // original place in the control flow.
              __ Unreachable();
              return V<Word>::Invalid();
            }
            [[fallthrough]];
          case Kind::kShiftRightArithmetic:
            switch (rep.value()) {
              case WordRepresentation::Word32():
                return __ Word32Constant(static_cast<int32_t>(c_signed) >>
                                         amount);
              case WordRepresentation::Word64():
                return __ Word64Constant(c_signed >> amount);
            }
          case Kind::kShiftRightLogical:
            switch (rep.value()) {
              case WordRepresentation::Word32():
                return __ Word32Constant(static_cast<uint32_t>(c_unsigned) >>
                                         amount);
              case WordRepresentation::Word64():
                return __ Word64Constant(c_unsigned >> amount);
            }
          case Kind::kShiftLeft:
            return __ WordConstant(c_unsigned << amount, rep);
          case Kind::kRotateRight:
            switch (rep.value()) {
              case WordRepresentation::Word32():
                return __ Word32Constant(base::bits::RotateRight32(
                    static_cast<uint32_t>(c_unsigned), amount));
              case WordRepresentation::Word64():
                return __ Word64Constant(
                    base::bits::RotateRight64(c_unsigned, amount));
            }
          case Kind::kRotateLeft:
            switch (rep.value()) {
              case WordRepresentation::Word32():
                return __ Word32Constant(base::bits::RotateLeft32(
                    static_cast<uint32_t>(c_unsigned), amount));
              case WordRepresentation::Word64():
                return __ Word64Constant(
                    base::bits::RotateLeft64(c_unsigned, amount));
            }
        }
      }
    }
    if (int32_t amount; matcher_.MatchIntegralWord32Constant(right, &amount) &&
                        0 <= amount && amount < rep.bit_width()) {
      if (amount == 0) {
        return left;
      }
      if (kind == Kind::kShiftLeft) {
        // If x >> K only shifted out zeros:
        // (x >> K) << L => x if K == L
        // (x >> K) << L => x >> (K-L) if K > L
        // (x >> K) << L => x << (L-K) if K < L
        // Since this is used for Smi untagging, we currently only need it for
        // signed shifts.
        int k;
        V<Word> x;
        if (matcher_.MatchConstantShift(
                left, &x, Kind::kShiftRightArithmeticShiftOutZeros, rep, &k)) {
          int32_t l = amount;
          if (k == l) {
            return x;
          } else if (k > l) {
            return __ ShiftRightArithmeticShiftOutZeros(
                x, __ Word32Constant(k - l), rep);
          } else if (k < l) {
            return __ ShiftLeft(x, __ Word32Constant(l - k), rep);
          }
        }
        // (x >>> K) << K => x & ~(2^K - 1)
        // (x >> K) << K => x & ~(2^K - 1)
        if (matcher_.MatchConstantRightShift(left, &x, rep, &k) &&
            k == amount) {
          return __ WordBitwiseAnd(
              x, __ WordConstant(rep.MaxUnsignedValue() << k, rep), rep);
        }
      }
      if (kind == any_of(Kind::kShiftRightArithmetic,
                         Kind::kShiftRightArithmeticShiftOutZeros)) {
        V<Word> x;
        int left_shift_amount;
        // (x << k) >> k
        if (matcher_.MatchConstantShift(left, &x, ShiftOp::Kind::kShiftLeft,
                                        rep, &left_shift_amount) &&
            amount == left_shift_amount) {
          // x << (bit_width - 1) >> (bit_width - 1) => 0 - x if x is 0 or 1
          if (amount == rep.bit_width() - 1 && IsBit(x)) {
            return __ WordSub(__ WordConstant(0, rep), x, rep);
          }
          // x << (bit_width - 8) >> (bit_width - 8) => x if x is within Int8
          if (amount <= rep.bit_width() - 8 && IsInt8(x)) {
            return x;
          }
          // x << (bit_width - 8) >> (bit_width - 8) => x if x is within Int8
          if (amount <= rep.bit_width() - 16 && IsInt16(x)) {
            return x;
          }
        }
      }
      if (rep == WordRepresentation::Word32() &&
          SupportedOperations::word32_shift_is_safe()) {
        // Remove the explicit 'and' with 0x1F if the shift provided by the
        // machine instruction matcher_.Matches that required by JavaScript.
        if (V<Word32> a, b; matcher_.MatchBitwiseAnd(
                right, &a, &b, WordRepresentation::Word32())) {
#if defined(__clang__)
          static_assert(0x1f == WordRepresentation::Word32().bit_width() - 1);
#endif
          if (uint32_t b_value;
              matcher_.MatchIntegralWord32Constant(b, &b_value) &&
              b_value == 0x1f) {
            return __ Shift(left, a, kind, rep);
          }
        }
      }
    }
    return Next::ReduceShift(left, right, kind, rep);
  }
References __, v8::internal::compiler::turboshaft::any_of(), v8::base::bits::CountTrailingZeros(), v8::internal::compiler::turboshaft::V< T >::Invalid(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsBit(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsInt16(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsInt8(), v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant(), v8::base::bits::RotateLeft32(), v8::base::bits::RotateLeft64(), v8::base::bits::RotateRight32(), v8::base::bits::RotateRight64(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryRemoveWord32ToWord64Conversion(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceWithTruncation().
StaticAssert()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::StaticAssert (V< Word32 > condition, const char * source) [inline]
Definition at line 1925 of file machine-optimization-reducer.h.
                                                                        {
    LABEL_BLOCK(no_change) {
      return Next::ReduceStaticAssert(condition, source);
    }
    if (std::optional<bool> decision = MatchBoolConstant(condition)) {
      if (*decision) {
        // Drop the assert, the condition holds true.
        return V<None>::Invalid();
      } else {
        // Leave the assert, as the condition is not true.
        goto no_change;
      }
    }
    goto no_change;
  }
References v8::internal::compiler::turboshaft::V< T >::Invalid(), LABEL_BLOCK, and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::MatchBoolConstant().
Store()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store (OpIndex base_idx, OptionalOpIndex index, OpIndex value, StoreOp::Kind kind, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset, uint8_t element_scale, bool maybe_initializing_or_transitioning, IndirectPointerTag maybe_indirect_pointer_tag) [inline]
Definition at line 1960 of file machine-optimization-reducer.h.
                                                                       {
    LABEL_BLOCK(no_change) {
      return Next::ReduceStore(base_idx, index, value, kind, stored_rep,
                               write_barrier, offset, element_scale,
                               maybe_initializing_or_transitioning,
                               maybe_indirect_pointer_tag);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
#if V8_TARGET_ARCH_32_BIT
    if (kind.is_atomic && stored_rep.SizeInBytes() == 8) {
      // AtomicWord32PairOp (as used by Int64Lowering) cannot handle
      // element_scale != 0 currently.
      // TODO(jkummerow): Add support for element_scale in AtomicWord32PairOp.
      goto no_change;
    }
#endif
    if (stored_rep.SizeInBytes() <= 4) {
      value = TryRemoveWord32ToWord64Conversion(value);
    }
    index = ReduceMemoryIndex(index.value_or_invalid(), &offset, &element_scale,
                              kind.tagged_base);
    switch (stored_rep) {
      case MemoryRepresentation::Uint8():
      case MemoryRepresentation::Int8():
        value = ReduceWithTruncation(value, std::numeric_limits<uint8_t>::max(),
                                     WordRepresentation::Word32());
        break;
      case MemoryRepresentation::Uint16():
      case MemoryRepresentation::Int16():
        value =
            ReduceWithTruncation(value, std::numeric_limits<uint16_t>::max(),
                                 WordRepresentation::Word32());
        break;
      case MemoryRepresentation::Uint32():
      case MemoryRepresentation::Int32():
        value =
            ReduceWithTruncation(value, std::numeric_limits<uint32_t>::max(),
                                 WordRepresentation::Word32());
        break;
      default:
        break;
    }
    // If index is invalid and base is `left+right`, we use `left` as base and
    // `right` as index.
    if (!index.valid() && matcher_.Is<Opmask::kWord64Add>(base_idx)) {
      DCHECK_EQ(element_scale, 0);
      const WordBinopOp& base = matcher_.Cast<WordBinopOp>(base_idx);
      base_idx = base.left();
      index = base.right();
      // We go through the Store stack again, which might merge {index} into
      // {offset}, or just do other optimizations on this Store.
      __ Store(base_idx, index, value, kind, stored_rep, write_barrier, offset,
               element_scale, maybe_initializing_or_transitioning,
               maybe_indirect_pointer_tag);
      return V<None>::Invalid();
    }
    return Next::ReduceStore(base_idx, index, value, kind, stored_rep,
                             write_barrier, offset, element_scale,
                             maybe_initializing_or_transitioning,
                             maybe_indirect_pointer_tag);
  }
References __, v8::internal::compiler::turboshaft::OperationMatcher::Cast(), DCHECK_EQ, v8::internal::index, v8::internal::compiler::turboshaft::MemoryRepresentation::Int16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int8(), v8::internal::compiler::turboshaft::V< T >::Invalid(), v8::internal::compiler::turboshaft::OperationMatcher::Is(), LABEL_BLOCK, v8::internal::compiler::turboshaft::WordBinopOp::left(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceMemoryIndex(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceWithTruncation(), v8::internal::compiler::turboshaft::WordBinopOp::right(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryRemoveWord32ToWord64Conversion(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), v8::internal::value, and v8::internal::compiler::turboshaft::WordRepresentation::Word32().
Switch()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Switch (V< Word32 > input, base::Vector< SwitchOp::Case > cases, Block * default_case, BranchHint default_hint) [inline]
Definition at line 1941 of file machine-optimization-reducer.h.
                                                                       {
    LABEL_BLOCK(no_change) {
      return Next::ReduceSwitch(input, cases, default_case, default_hint);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    if (int32_t value; matcher_.MatchIntegralWord32Constant(input, &value)) {
      for (const SwitchOp::Case& if_value : cases) {
        if (if_value.value == value) {
          __ Goto(if_value.destination);
          return {};
        }
      }
      __ Goto(default_case);
      return {};
    }
    goto no_change;
  }
References __, LABEL_BLOCK, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), and v8::internal::value.
TaggedBitcast()
template<class Next >
V<Any> REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TaggedBitcast (V< Any > input, RegisterRepresentation from, RegisterRepresentation to, TaggedBitcastOp::Kind kind) [inline]
Definition at line 332 of file machine-optimization-reducer.h.
                                                         {
    if (ShouldSkipOptimizationStep()) {
      return Next::ReduceTaggedBitcast(input, from, to, kind);
    }
    // A Tagged -> Untagged -> Tagged sequence can be short-cut.
    // An Untagged -> Tagged -> Untagged sequence however cannot be removed,
    // because the GC might have modified the pointer.
    if (auto* input_bitcast = matcher_.TryCast<TaggedBitcastOp>(input)) {
      if (all_of(input_bitcast->to, from) ==
              RegisterRepresentation::WordPtr() &&
          all_of(input_bitcast->from, to) == RegisterRepresentation::Tagged()) {
        return input_bitcast->input();
      }
    }
    // An Untagged -> Smi -> Untagged sequence can be short-cut.
    if (auto* input_bitcast = matcher_.TryCast<TaggedBitcastOp>(input);
        input_bitcast && to.IsWord() &&
        (kind == TaggedBitcastOp::Kind::kSmi ||
         input_bitcast->kind == TaggedBitcastOp::Kind::kSmi)) {
      if (input_bitcast->from == to) return input_bitcast->input();
      if (input_bitcast->from == RegisterRepresentation::Word32()) {
        DCHECK_EQ(to, RegisterRepresentation::Word64());
        return __ BitcastWord32ToWord64(input_bitcast->input());
      }
      DCHECK(input_bitcast->from == RegisterRepresentation::Word64() &&
             to == RegisterRepresentation::Word32());
      return __ TruncateWord64ToWord32(input_bitcast->input());
    }
    // Try to constant-fold TaggedBitcast from Word Constant to Word.
    if (to.IsWord()) {
      if (const ConstantOp* cst = matcher_.TryCast<ConstantOp>(input)) {
        if (cst->kind == ConstantOp::Kind::kWord32 ||
            cst->kind == ConstantOp::Kind::kWord64) {
          if (to == RegisterRepresentation::Word64()) {
            return __ Word64Constant(cst->integral());
          } else {
            DCHECK_EQ(to, RegisterRepresentation::Word32());
            return __ Word32Constant(static_cast<uint32_t>(cst->integral()));
          }
        }
      }
    }
    if (const ConstantOp* cst = matcher_.TryCast<ConstantOp>(input)) {
      // Try to constant-fold Word constant -> Tagged (Smi).
      if (cst->IsIntegral() && to == RegisterRepresentation::Tagged()) {
        if (Smi::IsValid(cst->integral())) {
          return __ SmiConstant(
              i::Tagged<Smi>(static_cast<intptr_t>(cst->integral())));
        }
      }
      // Try to constant-fold Smi -> Untagged.
      if (cst->kind == ConstantOp::Kind::kSmi) {
        if (to == RegisterRepresentation::Word32()) {
          return __ Word32Constant(static_cast<uint32_t>(cst->smi().ptr()));
        } else if (to == RegisterRepresentation::Word64()) {
          return __ Word64Constant(static_cast<uint64_t>(cst->smi().ptr()));
        }
      }
    }
    return Next::ReduceTaggedBitcast(input, from, to, kind);
  }
References __, v8::internal::compiler::turboshaft::all_of(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Smi::IsValid(), v8::internal::compiler::turboshaft::TaggedBitcastOp::kSmi, v8::internal::compiler::turboshaft::ConstantOp::kSmi, v8::internal::compiler::turboshaft::ConstantOp::kWord32, v8::internal::compiler::turboshaft::ConstantOp::kWord64, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::OperationMatcher::TryCast(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word64(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
TruncateWord()
template<class Next >
uint64_t v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TruncateWord (uint64_t value, WordRepresentation rep) [inline], [private]
Definition at line 2628 of file machine-optimization-reducer.h.
                                                                {
    if (rep == WordRepresentation::Word32()) {
      return static_cast<uint32_t>(value);
    } else {
      DCHECK_EQ(rep, WordRepresentation::Word64());
      return value;
    }
  }
References DCHECK_EQ, v8::internal::value, v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
TryAdjustElementScale()
template<class Next >
bool v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustElementScale (uint8_t * element_scale, OpIndex maybe_constant) [inline], [private]
Definition at line 2475 of file machine-optimization-reducer.h.
                                                                             {
    uint64_t diff;
    if (!matcher_.MatchIntegralWordConstant(
            maybe_constant, WordRepresentation::WordPtr(), &diff)) {
      return false;
    }
    DCHECK_LT(*element_scale, WordRepresentation::WordPtr().bit_width());
    if (diff < (WordRepresentation::WordPtr().bit_width() -
                uint64_t{*element_scale})) {
      *element_scale += diff;
      return true;
    }
    return false;
  }
References DCHECK_LT, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant(), and v8::internal::compiler::turboshaft::WordRepresentation::WordPtr().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceMemoryIndex().
TryAdjustIndex()
template<class Next >
bool v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustIndex (int32_t offset, OpIndex * index, const Operation & maybe_constant, uint8_t element_scale) [inline], [private]
Definition at line 2454 of file machine-optimization-reducer.h.
                                                                              {
    if (!maybe_constant.Is<ConstantOp>()) return false;
    const ConstantOp& constant = maybe_constant.Cast<ConstantOp>();
    if (constant.rep != WordRepresentation::WordPtr() ||
        !constant.IsIntegral()) {
      // This can only happen in unreachable code. Ideally, we identify this
      // situation and use `__ Unreachable()`. However, this is difficult to
      // do from within this helper, so we just don't perform the reduction.
      return false;
    }
    int64_t diff = constant.signed_integral();
    int64_t new_index;
    if (!base::bits::SignedAddOverflow64(offset, diff << element_scale,
                                         &new_index)) {
      *index = __ IntPtrConstant(new_index);
      return true;
    }
    return false;
  }
References __, v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::index, v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::ConstantOp::IsIntegral(), v8::internal::compiler::turboshaft::ConstantOp::rep, v8::internal::compiler::turboshaft::ConstantOp::signed_integral(), v8::base::bits::SignedAddOverflow64(), and v8::internal::compiler::turboshaft::WordRepresentation::WordPtr().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceMemoryIndex().
TryAdjustOffset()
template<class Next >
bool v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustOffset (int32_t * offset, const Operation & maybe_constant, uint8_t element_scale, bool tagged_base) [inline], [private]
Definition at line 2427 of file machine-optimization-reducer.h.
                                                                {
    if (!maybe_constant.Is<ConstantOp>()) return false;
    const ConstantOp& constant = maybe_constant.Cast<ConstantOp>();
    if (constant.rep != WordRepresentation::WordPtr() ||
        !constant.IsIntegral()) {
      // This can only happen in unreachable code. Ideally, we identify this
      // situation and use `__ Unreachable()`. However, this is difficult to
      // do from within this helper, so we just don't perform the reduction.
      return false;
    }
    int64_t diff = constant.signed_integral();
    int32_t new_offset;
    if (element_scale > 31) return false;
    if (diff <= (std::numeric_limits<int32_t>::max() >> element_scale) &&
        diff >= (std::numeric_limits<int32_t>::min() >> element_scale) &&
        !base::bits::SignedAddOverflow32(
            *offset,
            static_cast<int32_t>(base::bits::Unsigned(diff) << element_scale),
            &new_offset) &&
        LoadOp::OffsetIsValid(new_offset, tagged_base)) {
      *offset = new_offset;
      return true;
    }
    return false;
  }
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::ConstantOp::IsIntegral(), v8::internal::compiler::turboshaft::LoadOp::OffsetIsValid(), v8::internal::compiler::turboshaft::ConstantOp::rep, v8::internal::compiler::turboshaft::ConstantOp::signed_integral(), v8::base::bits::SignedAddOverflow32(), v8::base::bits::Unsigned(), and v8::internal::compiler::turboshaft::WordRepresentation::WordPtr().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceMemoryIndex().
TryMatchHeapObject()
template<class Next >
bool v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryMatchHeapObject (V< Any > idx, int depth = 0) [inline]
Definition at line 1212 of file machine-optimization-reducer.h.
                                                     {
    constexpr int kMaxDepth = 2;
    if (depth == kMaxDepth) return false;
    if (matcher_.MatchHeapConstant(idx)) return true;
    if (matcher_.Is<AllocateOp>(idx)) return true;
    if (matcher_.Is<Opmask::kTaggedBitcastHeapObject>(idx)) return true;
    // A Phi whose inputs are all HeapObject is itself a HeapObject.
    if (const PhiOp* phi = matcher_.TryCast<Opmask::kTaggedPhi>(idx)) {
      return base::all_of(phi->inputs(), [depth, this](V<Any> input) {
        return TryMatchHeapObject(input, depth + 1);
      });
    }
    // For anything else, assume that it's not a heap object.
    return false;
  }
References v8::base::all_of(), v8::internal::compiler::turboshaft::OperationMatcher::Is(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchHeapConstant(), and v8::internal::compiler::turboshaft::OperationMatcher::TryCast().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
TryReduceToRor()
template<class Next >
std::optional<V<Word> > v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryReduceToRor (V< Word > left, V< Word > right, WordBinopOp::Kind kind, WordRepresentation rep) [inline]
Definition at line 1231 of file machine-optimization-reducer.h.
                                                                {
    // Recognize rotation, we are matcher_.Matching and transforming as follows
    // (assuming kWord32, kWord64 is handled correspondingly):
    // x << y | x >>> (32 - y) => x ror (32 - y)
    // x << (32 - y) | x >>> y => x ror y
    // x << y ^ x >>> (32 - y) => x ror (32 - y) if 1 <= y < 32
    // x << (32 - y) ^ x >>> y => x ror y if 1 <= y < 32
    // (As well as the commuted forms.)
    // Note the side condition for XOR: the optimization doesn't hold for
    // an effective rotation amount of 0.
    if (!(kind == any_of(WordBinopOp::Kind::kBitwiseOr,
                         WordBinopOp::Kind::kBitwiseXor))) {
      return {};
    }
    const ShiftOp* high = matcher_.TryCast<ShiftOp>(left);
    if (!high) return {};
    const ShiftOp* low = matcher_.TryCast<ShiftOp>(right);
    if (!low) return {};
    if (low->kind == ShiftOp::Kind::kShiftLeft) {
      std::swap(low, high);
    }
    if (high->kind != ShiftOp::Kind::kShiftLeft ||
        low->kind != ShiftOp::Kind::kShiftRightLogical) {
      return {};
    }
    V<Word> x = high->left();
    if (low->left() != x) return {};
    if (uint64_t k1, k2;
        matcher_.MatchIntegralWordConstant(high->right(), rep, &k1) &&
        matcher_.MatchIntegralWordConstant(low->right(), rep, &k2) &&
        k1 + k2 == rep.bit_width() && k1 >= 0 && k2 >= 0) {
      if (k1 == 0 || k2 == 0) {
        if (kind == WordBinopOp::Kind::kBitwiseXor) {
          return __ WordConstant(0, rep);
        } else {
          DCHECK_EQ(kind, WordBinopOp::Kind::kBitwiseOr);
          return x;
        }
      }
      return __ RotateRight(x, low->right(), rep);
    }
    if (kind == WordBinopOp::Kind::kBitwiseXor) {
      // Can't guarantee that rotation amount is not 0.
      return {};
    }
    DCHECK_EQ(kind, WordBinopOp::Kind::kBitwiseOr);
    V<Word> a, b;
    uint64_t k;
    if (matcher_.MatchWordSub(high->right(), &a, &b, rep) &&
        matcher_.MatchIntegralWordConstant(a, rep, &k) && b == low->right() &&
        k == rep.bit_width()) {
      return __ RotateRight(x, b, rep);
    } else if (matcher_.MatchWordSub(low->right(), &a, &b, rep) &&
               matcher_.MatchIntegralWordConstant(a, rep, &k) &&
               b == high->right() && k == rep.bit_width()) {
      return __ RotateRight(x, low->right(), rep);
    }
    return {};
  }
References __, v8::internal::compiler::turboshaft::any_of(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::bit_width(), DCHECK_EQ, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseOr, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseXor, v8::internal::compiler::turboshaft::ShiftOp::kind, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant(), v8::internal::compiler::turboshaft::ShiftOp::right(), and v8::internal::compiler::turboshaft::OperationMatcher::TryCast().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
TryRemoveWord32ToWord64Conversion()
template<class Next >
V<Word> v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryRemoveWord32ToWord64Conversion (V< Word > value) [inline], [private]
Definition at line 2616 of file machine-optimization-reducer.h.
                                                           {
    if (const ChangeOp* op = matcher_.TryCast<ChangeOp>(value)) {
      if (op->from == WordRepresentation::Word32() &&
          op->to == WordRepresentation::Word64() &&
          op->kind == any_of(ChangeOp::Kind::kZeroExtend,
                             ChangeOp::Kind::kSignExtend)) {
        return V<Word32>::Cast(op->input());
      }
    }
    return value;
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::compiler::turboshaft::ChangeOp::kSignExtend, v8::internal::compiler::turboshaft::ChangeOp::kZeroExtend, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::TryCast(), v8::internal::value, v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordUnary().
UndoFloat32ToFloat64Conversion()
template<class Next >
V<Float32> v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoFloat32ToFloat64Conversion (V< Float64 > value) [inline], [private]
Definition at line 2546 of file machine-optimization-reducer.h.
                                                              {
    if (V<Float32> input; matcher_.MatchChange<Float32>(
            value, &input, ChangeOp::Kind::kFloatConversion, {},
            RegisterRepresentation::Float32(),
            RegisterRepresentation::Float64())) {
      return input;
    }
    if (double c;
        matcher_.MatchFloat64Constant(value, &c) && DoubleToFloat32(c) == c) {
      return __ Float32Constant(DoubleToFloat32(c));
    }
    UNREACHABLE();
  }
References __, v8::internal::DoubleToFloat32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::ChangeOp::kFloatConversion, v8::internal::compiler::turboshaft::OperationMatcher::MatchChange(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat64Constant(), v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison().
UndoWord32ToWord64Conversion()
template<class Next >
V<Word32> v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoWord32ToWord64Conversion (V< Word > value) [inline], [private]
Definition at line 2608 of file machine-optimization-reducer.h.
                                                        {
    DCHECK(IsWord32ConvertedToWord64(value));
    if (const ChangeOp* op = matcher_.TryCast<ChangeOp>(value)) {
      return V<Word32>::Cast(op->input());
    }
    return __ Word32Constant(matcher_.Cast<ConstantOp>(value).word32());
  }
References __, v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsWord32ConvertedToWord64(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::TryCast(), v8::internal::value, and v8::internal::compiler::turboshaft::ConstantOp::word32().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
WordBinop()
template<class Next >
V<Word> REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop (V< Word > left, V< Word > right, WordBinopOp::Kind kind, WordRepresentation rep) [inline]
Definition at line 789 of file machine-optimization-reducer.h.
                                                    {
    if (ShouldSkipOptimizationStep()) {
      return Next::ReduceWordBinop(left, right, kind, rep);
    }
    using Kind = WordBinopOp::Kind;
    DCHECK_EQ(rep, any_of(WordRepresentation::Word32(),
                          WordRepresentation::Word64()));
    bool is_64 = rep == WordRepresentation::Word64();
    if (!is_64) {
      left = TryRemoveWord32ToWord64Conversion(left);
      right = TryRemoveWord32ToWord64Conversion(right);
    }
    // Place constant on the right for commutative operators.
    if (WordBinopOp::IsCommutative(kind) && matcher_.Is<ConstantOp>(left) &&
        !matcher_.Is<ConstantOp>(right)) {
      return ReduceWordBinop(right, left, kind, rep);
    }
    // constant folding
    if (uint64_t k1, k2; matcher_.MatchIntegralWordConstant(left, rep, &k1) &&
                         matcher_.MatchIntegralWordConstant(right, rep, &k2)) {
      switch (kind) {
        case Kind::kAdd:
          return __ WordConstant(k1 + k2, rep);
        case Kind::kMul:
          return __ WordConstant(k1 * k2, rep);
        case Kind::kBitwiseAnd:
          return __ WordConstant(k1 & k2, rep);
        case Kind::kBitwiseOr:
          return __ WordConstant(k1 | k2, rep);
        case Kind::kBitwiseXor:
          return __ WordConstant(k1 ^ k2, rep);
        case Kind::kSub:
          return __ WordConstant(k1 - k2, rep);
        case Kind::kSignedMulOverflownBits:
          return __ WordConstant(
              is_64 ? base::bits::SignedMulHigh64(static_cast<int64_t>(k1),
                                                  static_cast<int64_t>(k2))
                    : base::bits::SignedMulHigh32(static_cast<int32_t>(k1),
                                                  static_cast<int32_t>(k2)),
              rep);
        case Kind::kUnsignedMulOverflownBits:
          return __ WordConstant(
              is_64 ? base::bits::UnsignedMulHigh64(k1, k2)
                    : base::bits::UnsignedMulHigh32(static_cast<uint32_t>(k1),
                                                    static_cast<uint32_t>(k2)),
              rep);
        case Kind::kSignedDiv:
          return __ WordConstant(
              is_64 ? base::bits::SignedDiv64(k1, k2)
                    : base::bits::SignedDiv32(static_cast<int32_t>(k1),
                                              static_cast<int32_t>(k2)),
              rep);
        case Kind::kUnsignedDiv:
          return __ WordConstant(
              is_64 ? base::bits::UnsignedDiv64(k1, k2)
                    : base::bits::UnsignedDiv32(static_cast<uint32_t>(k1),
                                                static_cast<uint32_t>(k2)),
              rep);
        case Kind::kSignedMod:
          return __ WordConstant(
              is_64 ? base::bits::SignedMod64(k1, k2)
                    : base::bits::SignedMod32(static_cast<int32_t>(k1),
                                              static_cast<int32_t>(k2)),
              rep);
        case Kind::kUnsignedMod:
          return __ WordConstant(
              is_64 ? base::bits::UnsignedMod64(k1, k2)
                    : base::bits::UnsignedMod32(static_cast<uint32_t>(k1),
                                                static_cast<uint32_t>(k2)),
              rep);
      }
    }
    if (kind == WordBinopOp::Kind::kBitwiseAnd &&
        rep == WordRepresentation::Word32()) {
      if (auto right_bitfield = detail::BitfieldCheck::Detect(
              matcher_, __ output_graph(), right)) {
        if (auto left_bitfield = detail::BitfieldCheck::Detect(
                matcher_, __ output_graph(), left)) {
          if (auto combined_bitfield =
                  left_bitfield->TryCombine(*right_bitfield)) {
            V<Word> source = combined_bitfield->source;
            if (combined_bitfield->truncate_from_64_bit) {
              source = __ TruncateWord64ToWord32(V<Word64>::Cast(source));
            }
            return __ Word32Equal(__ Word32BitwiseAnd(V<Word32>::Cast(source),
                                                      combined_bitfield->mask),
                                  combined_bitfield->masked_value);
          }
        }
      }
    }
    if (uint64_t right_value;
        matcher_.MatchIntegralWordConstant(right, rep, &right_value)) {
      // TODO(jkummerow): computing {right_value_signed} could probably be
      // handled by the 4th argument to {MatchIntegralWordConstant}.
      int64_t right_value_signed =
          is_64 ? static_cast<int64_t>(right_value)
                : int64_t{static_cast<int32_t>(right_value)};
      // (a <op> k1) <op> k2 => a <op> (k1 <op> k2)
      if (V<Word> a, k1;
          WordBinopOp::IsAssociative(kind) &&
          matcher_.MatchWordBinop<Word>(left, &a, &k1, kind, rep) &&
          matcher_.Is<ConstantOp>(k1)) {
        V<Word> k2 = right;
        // This optimization allows to do constant folding of `k1` and `k2`.
        // However, if (a <op> k1) has to be calculated anyways, then constant
        // folding does not save any calculations during runtime, and it may
        // increase register pressure because it extends the lifetime of `a`.
        // Therefore we do the optimization only when `left = (a <op k1)` has no
        // other uses.
        if (matcher_.Get(left).saturated_use_count.IsZero()) {
          return ReduceWordBinop(a, ReduceWordBinop(k1, k2, kind, rep), kind,
                                 rep);
        }
      }
      switch (kind) {
        case Kind::kSub:
          // left - k => left + -k
          return ReduceWordBinop(left, __ WordConstant(-right_value, rep),
                                 Kind::kAdd, rep);
        case Kind::kAdd:
          // left + 0 => left
          if (right_value == 0) {
            return left;
          }
          break;
        case Kind::kBitwiseXor:
          // left ^ 0 => left
          if (right_value == 0) {
            return left;
          }
          // left ^ 1 => left == 0 if left is 0 or 1
          if (right_value == 1 && IsBit(left)) {
            return __ Word32Equal(V<Word32>::Cast(left), 0);
          }
          // (x ^ -1) ^ -1 => x
          {
            V<Word> x, y;
            int64_t k;
            if (right_value_signed == -1 &&
                matcher_.MatchBitwiseAnd(left, &x, &y, rep) &&
                matcher_.MatchIntegralWordConstant(y, rep, &k) && k == -1) {
              return x;
            }
          }
          break;
        case Kind::kBitwiseOr:
          // left | 0 => left
          if (right_value == 0) {
            return left;
          }
          // left | -1 => -1
          if (right_value_signed == -1) {
            return right;
          }
          // (x & K1) | K2 => x | K2 if K2 has ones for every zero bit in K1.
          // This case can be constructed by UpdateWord and UpdateWord32 in CSA.
          {
            V<Word> x, y;
            uint64_t k1;
            uint64_t k2 = right_value;
            if (matcher_.MatchBitwiseAnd(left, &x, &y, rep) &&
                matcher_.MatchIntegralWordConstant(y, rep, &k1) &&
                (k1 | k2) == rep.MaxUnsignedValue()) {
              return __ WordBitwiseOr(x, right, rep);
            }
          }
          break;
        case Kind::kMul:
          // left * 0 => 0
          if (right_value == 0) {
            return __ WordConstant(0, rep);
          }
          // left * 1 => left
          if (right_value == 1) {
            return left;
          }
          // left * -1 => 0 - left
          if (right_value_signed == -1) {
            return __ WordSub(__ WordConstant(0, rep), left, rep);
          }
          // left * 2^k => left << k
          if (base::bits::IsPowerOfTwo(right_value)) {
            return __ ShiftLeft(left, base::bits::WhichPowerOfTwo(right_value),
                                rep);
          }
          break;
        case Kind::kBitwiseAnd:
          // left & -1 => left
          if (right_value_signed == -1) {
            return left;
          }
          // x & 0 => 0
          if (right_value == 0) {
            return right;
          }
          if (right_value == 1) {
            // (x + x) & 1 => 0
            V<Word> left_ignore_extensions =
                IsWord32ConvertedToWord64(left)
                    ? UndoWord32ToWord64Conversion(left)
                    : left;
            if (V<Word> a, b;
                matcher_.MatchWordAdd(left_ignore_extensions, &a, &b,
                                      WordRepresentation::Word32()) &&
                a == b) {
              return __ WordConstant(0, rep);
            }
            // CMP & 1 => CMP
            if (IsBit(left_ignore_extensions)) {
              return left;
            }
            static_assert(kSmiTagMask == 1);
            // HeapObject & 1 => 1 ("& 1" is a Smi-check)
            if (TryMatchHeapObject(left)) {
              return __ WordConstant(1, rep);
            } else if (__ Get(left).template Is<Opmask::kSmiConstant>()) {
              return __ WordConstant(0, rep);
            }
          }
          // asm.js often benefits from these transformations, to optimize out
          // unnecessary memory access alignment masks. Conventions used in
          // the comments below:
          // x, y: arbitrary values
          // K, L, M: arbitrary constants
          // (-1 << K) == mask: the right-hand side of the bitwise AND.
          if (IsNegativePowerOfTwo(right_value_signed)) {
            uint64_t mask = right_value;
            int K = base::bits::CountTrailingZeros64(mask);
            V<Word> x, y;
            {
              int L;
              // (x << L) & (-1 << K)
              // => x << L iff L >= K
              if (matcher_.MatchConstantLeftShift(left, &x, rep, &L) &&
                  L >= K) {
                return left;
              }
            }
            if (matcher_.MatchWordAdd(left, &x, &y, rep)) {
              uint64_t L; // L == (M << K) iff (L & mask) == L.
              // (x + (M << K)) & (-1 << K)
              // => (x & (-1 << K)) + (M << K)
              if (matcher_.MatchIntegralWordConstant(y, rep, &L) &&
                  (L & mask) == L) {
                return __ WordAdd(__ WordBitwiseAnd(x, right, rep),
                                  __ WordConstant(L, rep), rep);
              }
              // (x1 * (M << K) + y) & (-1 << K)
              // => x1 * (M << K) + (y & (-1 << K))
              V<Word> x1, x2, y1, y2;
              if (matcher_.MatchWordMul(x, &x1, &x2, rep) &&
                  matcher_.MatchIntegralWordConstant(x2, rep, &L) &&
                  (L & mask) == L) {
                return __ WordAdd(x, __ WordBitwiseAnd(y, right, rep), rep);
              }
              // Same as above with swapped order:
              // (x + y1 * (M << K)) & (-1 << K)
              // => (x & (-1 << K)) + y1 * (M << K)
              if (matcher_.MatchWordMul(y, &y1, &y2, rep) &&
                  matcher_.MatchIntegralWordConstant(y2, rep, &L) &&
                  (L & mask) == L) {
                return __ WordAdd(__ WordBitwiseAnd(x, right, rep), y, rep);
              }
              // ((x1 << K) + y) & (-1 << K)
              // => (x1 << K) + (y & (-1 << K))
              int K2;
              if (matcher_.MatchConstantLeftShift(x, &x1, rep, &K2) &&
                  K2 == K) {
                return __ WordAdd(x, __ WordBitwiseAnd(y, right, rep), rep);
              }
              // Same as above with swapped order:
              // (x + (y1 << K)) & (-1 << K)
              // => (x & (-1 << K)) + (y1 << K)
              if (matcher_.MatchConstantLeftShift(y, &y1, rep, &K2) &&
                  K2 == K) {
                return __ WordAdd(__ WordBitwiseAnd(x, right, rep), y, rep);
              }
            } else if (matcher_.MatchWordMul(left, &x, &y, rep)) {
              // (x * (M << K)) & (-1 << K) => x * (M << K)
              uint64_t L; // L == (M << K) iff (L & mask) == L.
              if (matcher_.MatchIntegralWordConstant(y, rep, &L) &&
                  (L & mask) == L) {
                return left;
              }
            }
          }
          break;
        case WordBinopOp::Kind::kSignedDiv:
          return ReduceSignedDiv(left, right_value_signed, rep);
        case WordBinopOp::Kind::kUnsignedDiv:
          return ReduceUnsignedDiv(left, right_value, rep);
        case WordBinopOp::Kind::kSignedMod:
          // left % 0 => 0
          // left % 1 => 0
          // left % -1 => 0
          if (right_value_signed == any_of(0, 1, -1)) {
            return __ WordConstant(0, rep);
          }
          if (right_value_signed != rep.MinSignedValue()) {
            right_value_signed = Abs(right_value_signed);
          }
          // left % 2^n => ((left + m) & (2^n - 1)) - m
          // where m = (left >> bits-1) >>> bits-n
          // This is a branch-free version of the following:
          // left >= 0 ? left & (2^n - 1)
          // : ((left + (2^n - 1)) & (2^n - 1)) - (2^n - 1)
          // Adding and subtracting (2^n - 1) before and after the bitwise-and
          // keeps the result congruent modulo 2^n, but shifts the resulting
          // value range to become -(2^n - 1) ... 0.
          if (base::bits::IsPowerOfTwo(right_value_signed)) {
            uint32_t bits = rep.bit_width();
            uint32_t n = base::bits::WhichPowerOfTwo(right_value_signed);
            V<Word> m = __ ShiftRightLogical(
                __ ShiftRightArithmetic(left, bits - 1, rep), bits - n, rep);
            return __ WordSub(
                __ WordBitwiseAnd(__ WordAdd(left, m, rep),
                                  __ WordConstant(right_value_signed - 1, rep),
                                  rep),
                m, rep);
          }
          // The `IntDiv` with a constant right-hand side will be turned into a
          // multiplication, avoiding the expensive integer division.
          return __ WordSub(
              left, __ WordMul(__ IntDiv(left, right, rep), right, rep), rep);
        case WordBinopOp::Kind::kUnsignedMod:
          // left % 0 => 0
          // left % 1 => 0
          if (right_value == 0 || right_value == 1) {
            return __ WordConstant(0, rep);
          }
          // x % 2^n => x & (2^n - 1)
          if (base::bits::IsPowerOfTwo(right_value)) {
            return __ WordBitwiseAnd(
                left, __ WordConstant(right_value - 1, rep), rep);
          }
          // The `UintDiv` with a constant right-hand side will be turned into a
          // multiplication, avoiding the expensive integer division.
          return __ WordSub(
              left, __ WordMul(right, __ UintDiv(left, right, rep), rep), rep);
        case WordBinopOp::Kind::kSignedMulOverflownBits:
        case WordBinopOp::Kind::kUnsignedMulOverflownBits:
          break;
      }
    }
    if (kind == Kind::kAdd) {
      V<Word> x, y, zero;
      // (0 - x) + y => y - x
      if (matcher_.MatchWordSub(left, &zero, &x, rep) &&
          matcher_.MatchZero(zero)) {
        y = right;
        return __ WordSub(y, x, rep);
      }
      // x + (0 - y) => x - y
      if (matcher_.MatchWordSub(right, &zero, &y, rep) &&
          matcher_.MatchZero(zero)) {
        x = left;
        return __ WordSub(x, y, rep);
      }
    }
    // 0 / right => 0
    // 0 % right => 0
    if (matcher_.MatchZero(left) &&
        kind == any_of(Kind::kSignedDiv, Kind::kUnsignedDiv, Kind::kUnsignedMod,
                       Kind::kSignedMod)) {
      return __ WordConstant(0, rep);
    }
    if (left == right) {
      V<Word> x = left;
      switch (kind) {
        // x & x => x
        // x | x => x
        case WordBinopOp::Kind::kBitwiseAnd:
        case WordBinopOp::Kind::kBitwiseOr:
          return x;
        // x ^ x => 0
        // x - x => 0
        // x % x => 0
        case WordBinopOp::Kind::kBitwiseXor:
        case WordBinopOp::Kind::kSub:
        case WordBinopOp::Kind::kSignedMod:
        case WordBinopOp::Kind::kUnsignedMod:
          return __ WordConstant(0, rep);
        // x / x => x != 0
        case WordBinopOp::Kind::kSignedDiv:
        case WordBinopOp::Kind::kUnsignedDiv: {
          V<Word> zero = __ WordConstant(0, rep);
          V<Word32> result = __ Word32Equal(__ Equal(left, zero, rep), 0);
          return __ ZeroExtendWord32ToRep(result, rep);
        }
        case WordBinopOp::Kind::kAdd:
        case WordBinopOp::Kind::kMul:
        case WordBinopOp::Kind::kSignedMulOverflownBits:
        case WordBinopOp::Kind::kUnsignedMulOverflownBits:
          break;
      }
    }
    if (std::optional<V<Word>> ror = TryReduceToRor(left, right, kind, rep)) {
      return *ror;
    }
    return Next::ReduceWordBinop(left, right, kind, rep);
  }
References __, v8::internal::Abs(), v8::internal::compiler::turboshaft::any_of(), v8::base::bits::CountTrailingZeros64(), DCHECK_EQ, v8::internal::compiler::turboshaft::detail::BitfieldCheck::Detect(), v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::OperationMatcher::Is(), v8::internal::compiler::turboshaft::WordBinopOp::IsAssociative(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsBit(), v8::internal::compiler::turboshaft::WordBinopOp::IsCommutative(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsNegativePowerOfTwo(), v8::base::bits::IsPowerOfTwo(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsWord32ConvertedToWord64(), v8::internal::compiler::turboshaft::SaturatedUint8::IsZero(), v8::internal::K, v8::internal::compiler::turboshaft::WordBinopOp::kAdd, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseAnd, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseOr, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseXor, v8::internal::compiler::turboshaft::WordBinopOp::kMul, v8::internal::compiler::turboshaft::WordBinopOp::kSignedDiv, v8::internal::compiler::turboshaft::WordBinopOp::kSignedMod, v8::internal::compiler::turboshaft::WordBinopOp::kSignedMulOverflownBits, v8::internal::kSmiTagMask, v8::internal::compiler::turboshaft::WordBinopOp::kSub, v8::internal::compiler::turboshaft::WordBinopOp::kUnsignedDiv, v8::internal::compiler::turboshaft::WordBinopOp::kUnsignedMod, v8::internal::compiler::turboshaft::WordBinopOp::kUnsignedMulOverflownBits, v8::internal::L, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceSignedDiv(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceUnsignedDiv(), v8::base::internal::result, ror, v8::internal::compiler::turboshaft::Operation::saturated_use_count, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::base::bits::SignedDiv32(), v8::base::bits::SignedDiv64(), v8::base::bits::SignedMod32(), v8::base::bits::SignedMod64(), v8::base::bits::SignedMulHigh32(), v8::base::bits::SignedMulHigh64(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryMatchHeapObject(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryReduceToRor(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryRemoveWord32ToWord64Conversion(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoWord32ToWord64Conversion(), v8::base::bits::UnsignedDiv32(), v8::base::bits::UnsignedDiv64(), v8::base::bits::UnsignedMod32(), v8::base::bits::UnsignedMod64(), v8::base::bits::UnsignedMulHigh32(), v8::base::bits::UnsignedMulHigh64(), v8::base::bits::WhichPowerOfTwo(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal(), v8::internal::compiler::turboshaft::WordRepresentation::Word64(), v8::internal::y, and v8::internal::zero.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop().
WordUnary()
template<class Next >
V<Word> REDUCE() v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordUnary (V< Word > input, WordUnaryOp::Kind kind, WordRepresentation rep) [inline]
Definition at line 533 of file machine-optimization-reducer.h.
                                                    {
    if (ShouldSkipOptimizationStep()) {
      return Next::ReduceWordUnary(input, kind, rep);
    }
    if (rep == WordRepresentation::Word32()) {
      input = TryRemoveWord32ToWord64Conversion(input);
    }
    if (uint32_t w32_k; rep == WordRepresentation::Word32() &&
                        matcher_.MatchIntegralWord32Constant(input, &w32_k)) {
      switch (kind) {
        case WordUnaryOp::Kind::kReverseBytes:
          return __ Word32Constant(base::bits::ReverseBytes(w32_k));
        case WordUnaryOp::Kind::kCountLeadingZeros:
          return __ Word32Constant(base::bits::CountLeadingZeros(w32_k));
        case WordUnaryOp::Kind::kCountTrailingZeros:
          return __ Word32Constant(base::bits::CountTrailingZeros(w32_k));
        case WordUnaryOp::Kind::kPopCount:
          return __ Word32Constant(base::bits::CountPopulation(w32_k));
        case WordUnaryOp::Kind::kSignExtend8:
          return __ Word32Constant(int32_t{static_cast<int8_t>(w32_k)});
        case WordUnaryOp::Kind::kSignExtend16:
          return __ Word32Constant(int32_t{static_cast<int16_t>(w32_k)});
      }
    } else if (uint64_t w64_k;
               rep == WordRepresentation::Word64() &&
               matcher_.MatchIntegralWord64Constant(input, &w64_k)) {
      switch (kind) {
        case WordUnaryOp::Kind::kReverseBytes:
          return __ Word64Constant(base::bits::ReverseBytes(w64_k));
        case WordUnaryOp::Kind::kCountLeadingZeros:
          return __ Word64Constant(
              uint64_t{base::bits::CountLeadingZeros(w64_k)});
        case WordUnaryOp::Kind::kCountTrailingZeros:
          return __ Word64Constant(
              uint64_t{base::bits::CountTrailingZeros(w64_k)});
        case WordUnaryOp::Kind::kPopCount:
          return __ Word64Constant(
              uint64_t{base::bits::CountPopulation(w64_k)});
        case WordUnaryOp::Kind::kSignExtend8:
          return __ Word64Constant(int64_t{static_cast<int8_t>(w64_k)});
        case WordUnaryOp::Kind::kSignExtend16:
          return __ Word64Constant(int64_t{static_cast<int16_t>(w64_k)});
      }
    }
    return Next::ReduceWordUnary(input, kind, rep);
  }
References __, v8::base::bits::CountLeadingZeros(), v8::base::bits::CountPopulation(), v8::base::bits::CountTrailingZeros(), v8::internal::compiler::int16_t, v8::internal::compiler::turboshaft::WordUnaryOp::kCountLeadingZeros, v8::internal::compiler::turboshaft::WordUnaryOp::kCountTrailingZeros, v8::internal::compiler::turboshaft::WordUnaryOp::kPopCount, v8::internal::compiler::turboshaft::WordUnaryOp::kReverseBytes, v8::internal::compiler::turboshaft::WordUnaryOp::kSignExtend16, v8::internal::compiler::turboshaft::WordUnaryOp::kSignExtend8, v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord64Constant(), v8::base::bits::ReverseBytes(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryRemoveWord32ToWord64Conversion(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Member Data Documentation
broker
template<class Next >
JSHeapBroker* v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::broker = __ data() -> broker() [private]
Definition at line 2923 of file machine-optimization-reducer.h.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::MapLoadCanBeConstantFolded(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual().
ensure_deterministic_nan
template<class Next >
constexpr bool v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ensure_deterministic_nan = false [static], [constexpr], [private]
Definition at line 2932 of file machine-optimization-reducer.h.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary().
matcher_
template<class Next >
const OperationMatcher& v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::matcher_ = __ matcher() [private]
Definition at line 2924 of file machine-optimization-reducer.h.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::BitcastWord32PairToFloat64(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsBit(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsFloat32ConvertedToFloat64(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsInt16(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsInt8(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsWord32ConvertedToWord64(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::MatchBoolConstant(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceBranchCondition(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceMemoryIndex(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceWithTruncation(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Switch(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TaggedBitcast(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustElementScale(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryMatchHeapObject(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryReduceToRor(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryRemoveWord32ToWord64Conversion(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoFloat32ToFloat64Conversion(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoWord32ToWord64Conversion(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordUnary().
signalling_nan_possible
template<class Next >
constexpr bool v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::signalling_nan_possible = false [static], [constexpr], [private]
Definition at line 2931 of file machine-optimization-reducer.h.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/machine-optimization-reducer.h