v8::internal::compiler::ScopeInfoRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< ScopeInfo > object () const
int ContextLength () const
bool HasContext () const
bool HasOuterScopeInfo () const
bool HasContextExtensionSlot () const
bool SomeContextHasExtension () const
bool ClassScopeHasPrivateBrand () const
bool SloppyEvalCanExtendVars () const
ScopeType scope_type () const
ScopeInfoRef OuterScopeInfo (JSHeapBroker *broker) const
Detailed Description
Definition at line 1116 of file heap-refs.h.
Member Function Documentation
ClassScopeHasPrivateBrand()
bool v8::internal::compiler::ScopeInfoRef::ClassScopeHasPrivateBrand () const
ContextLength()
int v8::internal::compiler::ScopeInfoRef::ContextLength () const
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateBlockContext().
HasContext()
bool v8::internal::compiler::ScopeInfoRef::HasContext () const
Referenced by v8::internal::maglev::MaglevGraphBuilder::Build(), and v8::internal::maglev::MaglevGraphBuilder::BuildCallWithFeedback().
HasContextExtensionSlot()
bool v8::internal::compiler::ScopeInfoRef::HasContextExtensionSlot () const
Referenced by v8::internal::maglev::MaglevGraphBuilder::CheckContextExtensions(), and v8::internal::compiler::BytecodeGraphBuilder::CheckContextExtensions().
HasOuterScopeInfo()
bool v8::internal::compiler::ScopeInfoRef::HasOuterScopeInfo () const
Referenced by v8::internal::maglev::MaglevGraphBuilder::Build(), v8::internal::maglev::MaglevGraphBuilder::BuildCallWithFeedback(), v8::internal::maglev::MaglevGraphBuilder::CheckContextExtensions(), v8::internal::compiler::BytecodeGraphBuilder::CheckContextExtensions(), and v8::internal::compiler::BytecodeGraphBuilder::TryGetScopeInfo().
object()
IndirectHandle<ScopeInfo> v8::internal::compiler::ScopeInfoRef::object () const
Referenced by v8::internal::compiler::CompilationDependencies::DependOnEmptyContextExtension(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency::EmptyContextExtensionDependency(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::maglev::CreateFunctionContext::PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
OuterScopeInfo()
ScopeInfoRef v8::internal::compiler::ScopeInfoRef::OuterScopeInfo (JSHeapBroker * broker) const
Definition at line 1746 of file heap-refs.cc.
                                                                    {
  return MakeRefAssumeMemoryFence(broker, object()->OuterScopeInfo());
}
References broker(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
Referenced by v8::internal::maglev::MaglevGraphBuilder::Build(), v8::internal::maglev::MaglevGraphBuilder::BuildCallWithFeedback(), v8::internal::maglev::MaglevGraphBuilder::CheckContextExtensions(), v8::internal::compiler::BytecodeGraphBuilder::CheckContextExtensions(), and v8::internal::compiler::BytecodeGraphBuilder::TryGetScopeInfo().
scope_type()
ScopeType v8::internal::compiler::ScopeInfoRef::scope_type () const
Referenced by v8::internal::maglev::MaglevGraphBuilder::CheckContextExtensions().
SloppyEvalCanExtendVars()
bool v8::internal::compiler::ScopeInfoRef::SloppyEvalCanExtendVars () const
Referenced by v8::internal::compiler::CompilationDependencies::DependOnEmptyContextExtension(), and v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency::EmptyContextExtensionDependency().
SomeContextHasExtension()
bool v8::internal::compiler::ScopeInfoRef::SomeContextHasExtension () const
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc