cppgc::subtle::HeapConsistency Class Reference
DO NOT USE: Use the appropriate managed types.
#include <heap-consistency.h>
Public Types
using WriteBarrierParams = internal::WriteBarrier::Params
using WriteBarrierType = internal::WriteBarrier::Type
Static Public Member Functions
static WriteBarrierType GetWriteBarrierType (const void *slot, const void *value, WriteBarrierParams &params)
Gets the required write barrier type for a specific write.
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
static WriteBarrierType GetWriteBarrierType (const internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > &value, WriteBarrierParams &params)
Gets the required write barrier type for a specific write.
template<typename HeapHandleCallback >
static WriteBarrierType GetWriteBarrierType (const void *slot, WriteBarrierParams &params, HeapHandleCallback callback)
Gets the required write barrier type for a specific write.
static WriteBarrierType GetWriteBarrierType (const void *value, WriteBarrierParams &params)
Gets the required write barrier type for a specific write.
static void DijkstraWriteBarrier (const WriteBarrierParams &params, const void *object)
Conservative Dijkstra-style write barrier that processes an object if it has not yet been processed.
static void DijkstraWriteBarrierRange (const WriteBarrierParams &params, const void *first_element, size_t element_size, size_t number_of_elements, TraceCallback trace_callback)
Conservative Dijkstra-style write barrier that processes a range of elements if they have not yet been processed.
static void SteeleWriteBarrier (const WriteBarrierParams &params, const void *object)
Steele-style write barrier that re-processes an object if it has already been processed.
static void GenerationalBarrier (const WriteBarrierParams &params, const void *slot)
Generational barrier for maintaining consistency when running with multiple generations.
static void GenerationalBarrierForUncompressedSlot (const WriteBarrierParams &params, const void *uncompressed_slot)
Generational barrier for maintaining consistency when running with multiple generations.
static void GenerationalBarrierForSourceObject (const WriteBarrierParams &params, const void *inner_pointer)
Generational barrier for source object that may contain outgoing pointers to objects in young generation.
Private Member Functions
HeapConsistency ()=delete
Detailed Description
DO NOT USE: Use the appropriate managed types.
Consistency helpers that aid in maintaining a consistent internal state of the garbage collector.
Definition at line 28 of file heap-consistency.h.
Member Typedef Documentation
WriteBarrierParams
using cppgc::subtle::HeapConsistency::WriteBarrierParams = internal::WriteBarrier::Params
Definition at line 30 of file heap-consistency.h.
WriteBarrierType
using cppgc::subtle::HeapConsistency::WriteBarrierType = internal::WriteBarrier::Type
Definition at line 31 of file heap-consistency.h.
Constructor & Destructor Documentation
HeapConsistency()
cppgc::subtle::HeapConsistency::HeapConsistency () [private], [delete]
Member Function Documentation
DijkstraWriteBarrier()
static void cppgc::subtle::HeapConsistency::DijkstraWriteBarrier (const WriteBarrierParams & params, const void * object) [inline], [static]
Conservative Dijkstra-style write barrier that processes an object if it has not yet been processed.
Parameters
params The parameters retrieved from GetWriteBarrierType().
object The pointer to the object. May be an interior pointer to an interface of the actual object.
Definition at line 120 of file heap-consistency.h.
                                                                 {
    internal::WriteBarrier::DijkstraMarkingBarrier(params, object);
  }
References cppgc::internal::WriteBarrier::DijkstraMarkingBarrier().
DijkstraWriteBarrierRange()
static void cppgc::subtle::HeapConsistency::DijkstraWriteBarrierRange (const WriteBarrierParams & params, const void * first_element, size_t element_size, size_t number_of_elements, TraceCallback trace_callback) [inline], [static]
Conservative Dijkstra-style write barrier that processes a range of elements if they have not yet been processed.
Parameters
params The parameters retrieved from GetWriteBarrierType().
first_element Pointer to the first element that should be processed. The slot itself must reside in an object that has been allocated using MakeGarbageCollected().
element_size Size of the element in bytes.
number_of_elements Number of elements that should be processed, starting with first_element.
trace_callback The trace callback that should be invoked for each element if necessary.
Definition at line 139 of file heap-consistency.h.
                                    {
    internal::WriteBarrier::DijkstraMarkingBarrierRange(
        params, first_element, element_size, number_of_elements,
        trace_callback);
  }
References cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRange().
GenerationalBarrier()
static void cppgc::subtle::HeapConsistency::GenerationalBarrier (const WriteBarrierParams & params, const void * slot) [inline], [static]
Generational barrier for maintaining consistency when running with multiple generations.
Parameters
params The parameters retrieved from GetWriteBarrierType().
slot Slot containing the pointer to the object. The slot itself must reside in an object that has been allocated using MakeGarbageCollected().
Definition at line 171 of file heap-consistency.h.
                                                              {
    internal::WriteBarrier::GenerationalBarrier<
        internal::WriteBarrier::GenerationalBarrierType::kPreciseSlot>(params,
                                                                       slot);
  }
References cppgc::internal::WriteBarrier::GenerationalBarrier(), and cppgc::internal::WriteBarrier::kPreciseSlot.
GenerationalBarrierForSourceObject()
static void cppgc::subtle::HeapConsistency::GenerationalBarrierForSourceObject (const WriteBarrierParams & params, const void * inner_pointer) [inline], [static]
Generational barrier for source object that may contain outgoing pointers to objects in young generation.
Parameters
params The parameters retrieved from GetWriteBarrierType().
inner_pointer Pointer to the source object.
Definition at line 201 of file heap-consistency.h.
                                                                   {
    internal::WriteBarrier::GenerationalBarrier<
        internal::WriteBarrier::GenerationalBarrierType::kImpreciseSlot>(
        params, inner_pointer);
  }
References cppgc::internal::WriteBarrier::GenerationalBarrier(), and cppgc::internal::WriteBarrier::kImpreciseSlot.
GenerationalBarrierForUncompressedSlot()
static void cppgc::subtle::HeapConsistency::GenerationalBarrierForUncompressedSlot (const WriteBarrierParams & params, const void * uncompressed_slot) [inline], [static]
Generational barrier for maintaining consistency when running with multiple generations.
This version is used when slot contains uncompressed pointer.
Parameters
params The parameters retrieved from GetWriteBarrierType().
slot Uncompressed slot containing the direct pointer to the object. The slot itself must reside in an object that has been allocated using MakeGarbageCollected().
Definition at line 187 of file heap-consistency.h.
                                                                       {
    internal::WriteBarrier::GenerationalBarrier<
        internal::WriteBarrier::GenerationalBarrierType::
            kPreciseUncompressedSlot>(params, uncompressed_slot);
  }
References cppgc::internal::WriteBarrier::GenerationalBarrier().
GetWriteBarrierType() [1/4]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
static WriteBarrierType cppgc::subtle::HeapConsistency::GetWriteBarrierType (const internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > & value, WriteBarrierParams & params) [inline], [static]
Gets the required write barrier type for a specific write.
This override is only used for all the BasicMember types.
Parameters
slot Slot containing the pointer to the object. The slot itself must reside in an object that has been allocated using MakeGarbageCollected().
value The pointer to the object held via BasicMember.
params Parameters that may be used for actual write barrier calls. Only filled if return value indicates that a write barrier is needed. The contents of the params are an implementation detail.
Returns
whether a write barrier is needed and which barrier to invoke.
Definition at line 66 of file heap-consistency.h.
                                  {
    return internal::WriteBarrier::GetWriteBarrierType(
        value.GetRawSlot(), value.GetRawStorage(), params);
  }
References cppgc::internal::WriteBarrier::GetWriteBarrierType(), and v8::internal::value.
GetWriteBarrierType() [2/4]
static WriteBarrierType cppgc::subtle::HeapConsistency::GetWriteBarrierType (const void * slot, const void * value, WriteBarrierParams & params) [inline], [static]
Gets the required write barrier type for a specific write.
Parameters
slot Slot containing the pointer to the object. The slot itself must reside in an object that has been allocated using MakeGarbageCollected().
value The pointer to the object. May be an interior pointer to an interface of the actual object.
params Parameters that may be used for actual write barrier calls. Only filled if return value indicates that a write barrier is needed. The contents of the params are an implementation detail.
Returns
whether a write barrier is needed and which barrier to invoke.
Definition at line 46 of file heap-consistency.h.
                                                                       {
    return internal::WriteBarrier::GetWriteBarrierType(slot, value, params);
  }
References cppgc::internal::WriteBarrier::GetWriteBarrierType(), and v8::internal::value.
GetWriteBarrierType() [3/4]
template<typename HeapHandleCallback >
static WriteBarrierType cppgc::subtle::HeapConsistency::GetWriteBarrierType (const void * slot, WriteBarrierParams & params, HeapHandleCallback callback) [inline], [static]
Gets the required write barrier type for a specific write.
Parameters
slot Slot to some part of an object. The object must not necessarily have been allocated using MakeGarbageCollected() but can also live off-heap or on stack.
params Parameters that may be used for actual write barrier calls. Only filled if return value indicates that a write barrier is needed. The contents of the params are an implementation detail.
callback Callback returning the corresponding heap handle. The callback is only invoked if the heap cannot otherwise be figured out. The callback must not allocate.
Returns
whether a write barrier is needed and which barrier to invoke.
Definition at line 90 of file heap-consistency.h.
                                                   {
    return internal::WriteBarrier::GetWriteBarrierType(slot, params, callback);
  }
References cppgc::internal::WriteBarrier::GetWriteBarrierType().
GetWriteBarrierType() [4/4]
static WriteBarrierType cppgc::subtle::HeapConsistency::GetWriteBarrierType (const void * value, WriteBarrierParams & params) [inline], [static]
Gets the required write barrier type for a specific write.
This version is meant to be used in conjunction with with a marking write barrier barrier which doesn't consider the slot.
Parameters
value The pointer to the object. May be an interior pointer to an interface of the actual object.
params Parameters that may be used for actual write barrier calls. Only filled if return value indicates that a write barrier is needed. The contents of the params are an implementation detail.
Returns
whether a write barrier is needed and which barrier to invoke.
Definition at line 108 of file heap-consistency.h.
                                                                     {
    return internal::WriteBarrier::GetWriteBarrierType(value, params);
  }
References cppgc::internal::WriteBarrier::GetWriteBarrierType(), and v8::internal::value.
SteeleWriteBarrier()
static void cppgc::subtle::HeapConsistency::SteeleWriteBarrier (const WriteBarrierParams & params, const void * object) [inline], [static]
Steele-style write barrier that re-processes an object if it has already been processed.
Parameters
params The parameters retrieved from GetWriteBarrierType().
object The pointer to the object which must point to an object that has been allocated using MakeGarbageCollected(). Interior pointers are not supported.
Definition at line 157 of file heap-consistency.h.
                                                               {
    internal::WriteBarrier::SteeleMarkingBarrier(params, object);
  }
References cppgc::internal::WriteBarrier::SteeleMarkingBarrier().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/cppgc/heap-consistency.h