v8::internal::BackgroundMergeTask Class Reference
#include <background-merge-task.h>
Classes
struct NewCompiledDataForCachedSfi
Public Member Functions
void SetUpOnMainThread (Isolate *isolate, Handle< String > source_text, const ScriptDetails &script_details, LanguageMode language_mode)
void SetUpOnMainThread (Isolate *isolate, DirectHandle< Script > cached_script)
void BeginMergeInBackground (LocalIsolate *isolate, DirectHandle< Script > new_script)
Handle< SharedFunctionInfo > CompleteMergeInForeground (Isolate *isolate, DirectHandle< Script > new_script)
bool HasPendingBackgroundWork () const
bool HasPendingForegroundWork () const
Static Public Member Functions
static void ForceGCDuringNextMergeForTesting ()
Private Types
enum State { kNotStarted
, kPendingBackgroundWork
, kPendingForegroundWork
, kDone
 }
Private Attributes
std::unique_ptr< PersistentHandles > persistent_handles_
MaybeHandle< Script > cached_script_
MaybeHandle< SharedFunctionInfo > toplevel_sfi_from_cached_script_
std::vector< Handle< SharedFunctionInfo > > used_new_sfis_
std::vector< NewCompiledDataForCachedSfi > new_compiled_data_for_cached_sfis_
State state_ = kNotStarted
Detailed Description
Definition at line 26 of file background-merge-task.h.
Member Enumeration Documentation
State
enum v8::internal::BackgroundMergeTask::State [private]
Enumerator
kNotStarted
kPendingBackgroundWork
kPendingForegroundWork
kDone
Definition at line 92 of file background-merge-task.h.
             {
    kNotStarted,
    kPendingBackgroundWork,
    kPendingForegroundWork,
    kDone,
  };
Member Function Documentation
BeginMergeInBackground()
void v8::internal::BackgroundMergeTask::BeginMergeInBackground (LocalIsolate * isolate, DirectHandle< Script > new_script)
Definition at line 2410 of file compiler.cc.
                                                            {
  DCHECK_EQ(state_, kPendingBackgroundWork);
  LocalHeap* local_heap = isolate->heap();
  local_heap->AttachPersistentHandles(std::move(persistent_handles_));
  LocalHandleScope handle_scope(local_heap);
  DirectHandle<Script> old_script = cached_script_.ToHandleChecked();
  ConstantPoolPointerForwarder forwarder(isolate, local_heap, old_script);
  {
    DisallowGarbageCollection no_gc;
    Tagged<MaybeObject> maybe_old_toplevel_sfi =
        old_script->infos()->get(kFunctionLiteralIdTopLevel);
    if (maybe_old_toplevel_sfi.IsWeak()) {
      Tagged<SharedFunctionInfo> old_toplevel_sfi = Cast<SharedFunctionInfo>(
          maybe_old_toplevel_sfi.GetHeapObjectAssumeWeak());
      toplevel_sfi_from_cached_script_ =
          local_heap->NewPersistentHandle(old_toplevel_sfi);
    }
  }
  // Iterate the SFI lists on both Scripts to set up the forwarding table and
  // follow-up worklists for the main thread.
  CHECK_EQ(old_script->infos()->length(), new_script->infos()->length());
  for (int i = 0; i < old_script->infos()->length(); ++i) {
    DisallowGarbageCollection no_gc;
    Tagged<MaybeObject> maybe_new_sfi = new_script->infos()->get(i);
    Tagged<MaybeObject> maybe_old_info = old_script->infos()->get(i);
    // We might have scope infos in the table if it's deserialized from a code
    // cache.
    if (maybe_new_sfi.IsWeak() &&
        Is<SharedFunctionInfo>(maybe_new_sfi.GetHeapObjectAssumeWeak())) {
      Tagged<SharedFunctionInfo> new_sfi =
          Cast<SharedFunctionInfo>(maybe_new_sfi.GetHeapObjectAssumeWeak());
      if (maybe_old_info.IsWeak()) {
        forwarder.set_has_shared_function_info_to_forward();
        // The old script and the new script both have SharedFunctionInfos for
        // this function literal.
        Tagged<SharedFunctionInfo> old_sfi =
            Cast<SharedFunctionInfo>(maybe_old_info.GetHeapObjectAssumeWeak());
        // Make sure to allocate a persistent handle to the old sfi whether or
        // not it or the new sfi have bytecode -- this is necessary to keep the
        // old sfi reference in the old script list alive, so that pointers to
        // the new sfi are redirected to the old sfi.
        Handle<SharedFunctionInfo> old_sfi_handle =
            local_heap->NewPersistentHandle(old_sfi);
        if (old_sfi->HasBytecodeArray()) {
          // Reset the old SFI's bytecode age so that it won't likely get
          // flushed right away. This operation might be racing against
          // concurrent modification by another thread, but such a race is not
          // catastrophic.
          old_sfi->set_age(0);
        } else if (new_sfi->HasBytecodeArray()) {
          // Also push the old_sfi to make sure it stays alive / isn't replaced.
          new_compiled_data_for_cached_sfis_.push_back(
              {old_sfi_handle, local_heap->NewPersistentHandle(new_sfi)});
          Tagged<ScopeInfo> info = old_sfi->scope_info();
          if (!info->IsEmpty()) {
            new_sfi->SetScopeInfo(info);
          } else if (old_sfi->HasOuterScopeInfo()) {
            new_sfi->scope_info()->set_outer_scope_info(
                old_sfi->GetOuterScopeInfo());
          }
          forwarder.AddBytecodeArray(new_sfi->GetBytecodeArray(isolate));
        }
      } else {
        // The old script didn't have a SharedFunctionInfo for this function
        // literal, so it can use the new SharedFunctionInfo.
        new_sfi->set_script(*old_script, kReleaseStore);
        used_new_sfis_.push_back(local_heap->NewPersistentHandle(new_sfi));
        if (new_sfi->HasBytecodeArray()) {
          forwarder.AddBytecodeArray(new_sfi->GetBytecodeArray(isolate));
        }
      }
    }
    if (maybe_old_info.IsWeak()) {
      forwarder.RecordScopeInfos(maybe_old_info);
      // If the old script has a SFI, point to it from the new script to
      // indicate we've already seen it and we'll reuse it if necessary (if
      // newly compiled bytecode points to it).
      new_script->infos()->set(i, maybe_old_info);
    }
  }
  // Since we are walking the script infos weak list both when figuring out
  // which SFIs to merge above, and actually merging them below, make sure that
  // a GC here which clears any dead weak refs or flushes any bytecode doesn't
  // break anything.
  if (V8_UNLIKELY(force_gc_during_next_merge_for_testing_)) {
    // This GC is only synchronous on the main thread at the moment.
    DCHECK(isolate->is_main_thread());
    local_heap->AsHeap()->CollectAllAvailableGarbage(
        GarbageCollectionReason::kTesting);
  }
  if (forwarder.HasAnythingToForward()) {
    for (DirectHandle<SharedFunctionInfo> new_sfi : used_new_sfis_) {
      forwarder.UpdateScopeInfo(*new_sfi);
    }
    for (const auto& new_compiled_data : new_compiled_data_for_cached_sfis_) {
      // It's possible that new_compiled_data.cached_sfi had
      // scope_info()->IsEmpty() while an inner function has scope info if the
      // cached_sfi was recreated when an outer function was recompiled. If so,
      // new_compiled_data.new_sfi does not have a reused scope info yet, and
      // we'll have found it when we visited the inner function. Try to pick it
      // up here.
      forwarder.InstallOwnScopeInfo(*new_compiled_data.new_sfi);
    }
    forwarder.IterateAndForwardPointers();
  }
  persistent_handles_ = local_heap->DetachPersistentHandles();
  state_ = kPendingForegroundWork;
}
References v8::internal::ConstantPoolPointerForwarder::AddBytecodeArray(), v8::internal::LocalHeap::AsHeap(), v8::internal::LocalHeap::AttachPersistentHandles(), cached_script_, CHECK_EQ, v8::internal::Heap::CollectAllAvailableGarbage(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::LocalHeap::DetachPersistentHandles(), v8::internal::force_gc_during_next_merge_for_testing_, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak(), v8::internal::ConstantPoolPointerForwarder::HasAnythingToForward(), v8::internal::LocalIsolate::heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ConstantPoolPointerForwarder::InstallOwnScopeInfo(), v8::internal::LocalIsolate::is_main_thread(), v8::internal::TaggedImpl< kRefType, StorageType >::IsWeak(), v8::internal::ConstantPoolPointerForwarder::IterateAndForwardPointers(), v8::internal::kFunctionLiteralIdTopLevel, kPendingBackgroundWork, kPendingForegroundWork, v8::kReleaseStore, v8::internal::kTesting, v8::internal::length, new_compiled_data_for_cached_sfis_, v8::internal::LocalHeap::NewPersistentHandle(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, persistent_handles_, v8::internal::ConstantPoolPointerForwarder::RecordScopeInfos(), v8::internal::ConstantPoolPointerForwarder::set_has_shared_function_info_to_forward(), state_, toplevel_sfi_from_cached_script_, v8::internal::ConstantPoolPointerForwarder::UpdateScopeInfo(), used_new_sfis_, and V8_UNLIKELY.
Referenced by v8::internal::CodeSerializer::Deserialize(), v8::internal::BackgroundCompileTask::FinalizeScript(), and v8::internal::BackgroundDeserializeTask::MergeWithExistingScript().
CompleteMergeInForeground()
Handle< SharedFunctionInfo > v8::internal::BackgroundMergeTask::CompleteMergeInForeground (Isolate * isolate, DirectHandle< Script > new_script)
Definition at line 2526 of file compiler.cc.
                                                       {
  DCHECK_EQ(state_, kPendingForegroundWork);
  HandleScope handle_scope(isolate);
  DirectHandle<Script> old_script = cached_script_.ToHandleChecked();
  ConstantPoolPointerForwarder forwarder(
      isolate, isolate->main_thread_local_heap(), old_script);
  for (const auto& new_compiled_data : new_compiled_data_for_cached_sfis_) {
    Tagged<SharedFunctionInfo> sfi = *new_compiled_data.cached_sfi;
    if (!sfi->is_compiled() && new_compiled_data.new_sfi->is_compiled()) {
      // Updating existing DebugInfos is not supported, but we don't expect
      // uncompiled SharedFunctionInfos to contain DebugInfos.
      DCHECK(!new_compiled_data.cached_sfi->HasDebugInfo(isolate));
      // The goal here is to copy every field except script from
      // new_sfi to cached_sfi. The safest way to do so (including a DCHECK that
      // no fields were skipped) is to first copy the script from
      // cached_sfi to new_sfi, and then copy every field using CopyFrom.
      new_compiled_data.new_sfi->set_script(sfi->script(kAcquireLoad),
                                            kReleaseStore);
      sfi->CopyFrom(*new_compiled_data.new_sfi, isolate);
    }
  }
  for (int i = 0; i < old_script->infos()->length(); ++i) {
    Tagged<MaybeObject> maybe_old_info = old_script->infos()->get(i);
    Tagged<MaybeObject> maybe_new_info = new_script->infos()->get(i);
    if (maybe_new_info == maybe_old_info) continue;
    DisallowGarbageCollection no_gc;
    if (maybe_old_info.IsWeak()) {
      // The old script's SFI didn't exist during the background work, but does
      // now. This means a re-merge is necessary. Potential references to the
      // new script's SFI need to be updated to point to the cached script's SFI
      // instead. The cached script's SFI's outer scope infos need to be used by
      // the new script's outer SFIs.
      if (Is<SharedFunctionInfo>(maybe_old_info.GetHeapObjectAssumeWeak())) {
        forwarder.set_has_shared_function_info_to_forward();
      }
      forwarder.RecordScopeInfos(maybe_old_info);
    } else {
      old_script->infos()->set(i, maybe_new_info);
    }
  }
  // Most of the time, the background merge was sufficient. However, if there
  // are any new pointers that need forwarding, a new traversal of the constant
  // pools is required.
  if (forwarder.HasAnythingToForward()) {
    for (DirectHandle<SharedFunctionInfo> new_sfi : used_new_sfis_) {
      forwarder.UpdateScopeInfo(*new_sfi);
      if (new_sfi->HasBytecodeArray(isolate)) {
        forwarder.AddBytecodeArray(new_sfi->GetBytecodeArray(isolate));
      }
    }
    for (const auto& new_compiled_data : new_compiled_data_for_cached_sfis_) {
      // It's possible that cached_sfi wasn't compiled, but an inner function
      // existed that didn't exist when be background merged. In that case, pick
      // up the relevant scope infos.
      Tagged<SharedFunctionInfo> sfi = *new_compiled_data.cached_sfi;
      forwarder.InstallOwnScopeInfo(sfi);
      if (new_compiled_data.cached_sfi->HasBytecodeArray(isolate)) {
        forwarder.AddBytecodeArray(
            new_compiled_data.cached_sfi->GetBytecodeArray(isolate));
      }
    }
    forwarder.IterateAndForwardPointers();
  }
  Tagged<MaybeObject> maybe_toplevel_sfi =
      old_script->infos()->get(kFunctionLiteralIdTopLevel);
  CHECK(maybe_toplevel_sfi.IsWeak());
  Handle<SharedFunctionInfo> result = handle(
      Cast<SharedFunctionInfo>(maybe_toplevel_sfi.GetHeapObjectAssumeWeak()),
      isolate);
  state_ = kDone;
  if (isolate->NeedsSourcePositions()) {
    Script::InitLineEnds(isolate, new_script);
    SharedFunctionInfo::EnsureSourcePositionsAvailable(isolate, result);
  }
#ifdef DEBUG
  VerifyCodeMerge(isolate, old_script);
#else
  if (v8_flags.verify_code_merge) {
    VerifyCodeMerge(isolate, old_script);
  }
#endif
  return handle_scope.CloseAndEscape(result);
}
References v8::internal::ConstantPoolPointerForwarder::AddBytecodeArray(), cached_script_, CHECK, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak(), v8::internal::handle(), v8::internal::ConstantPoolPointerForwarder::HasAnythingToForward(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Script::InitLineEnds(), v8::internal::ConstantPoolPointerForwarder::InstallOwnScopeInfo(), v8::internal::TaggedImpl< kRefType, StorageType >::IsWeak(), v8::internal::ConstantPoolPointerForwarder::IterateAndForwardPointers(), v8::kAcquireLoad, kDone, v8::internal::kFunctionLiteralIdTopLevel, kPendingForegroundWork, v8::kReleaseStore, v8::internal::length, v8::internal::Isolate::main_thread_local_heap(), v8::internal::Isolate::NeedsSourcePositions(), new_compiled_data_for_cached_sfis_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::ConstantPoolPointerForwarder::RecordScopeInfos(), v8::base::internal::result, v8::internal::ConstantPoolPointerForwarder::set_has_shared_function_info_to_forward(), state_, v8::internal::ConstantPoolPointerForwarder::UpdateScopeInfo(), used_new_sfis_, v8::internal::v8_flags, and v8::internal::anonymous_namespace{compiler.cc}::VerifyCodeMerge().
Referenced by v8::internal::CodeSerializer::Deserialize(), v8::internal::BackgroundCompileTask::FinalizeScript(), and v8::internal::CodeSerializer::FinishOffThreadDeserialize().
ForceGCDuringNextMergeForTesting()
void v8::internal::BackgroundMergeTask::ForceGCDuringNextMergeForTesting () [static]
Definition at line 2406 of file compiler.cc.
                                                           {
  force_gc_during_next_merge_for_testing_ = true;
}
References v8::internal::force_gc_during_next_merge_for_testing_.
HasPendingBackgroundWork()
bool v8::internal::BackgroundMergeTask::HasPendingBackgroundWork () const [inline]
Definition at line 52 of file background-merge-task.h.
                                        {
    return state_ == kPendingBackgroundWork;
  }
Referenced by v8::internal::CodeSerializer::Deserialize(), v8::internal::BackgroundCompileTask::FinalizeScript(), and v8::internal::BackgroundDeserializeTask::ShouldMergeWithExistingScript().
HasPendingForegroundWork()
bool v8::internal::BackgroundMergeTask::HasPendingForegroundWork () const [inline]
Definition at line 55 of file background-merge-task.h.
                                        {
    return state_ == kPendingForegroundWork;
  }
Referenced by v8::internal::CodeSerializer::Deserialize(), v8::internal::BackgroundCompileTask::FinalizeScript(), and v8::internal::CodeSerializer::FinishOffThreadDeserialize().
SetUpOnMainThread() [1/2]
void v8::internal::BackgroundMergeTask::SetUpOnMainThread (Isolate * isolate, DirectHandle< Script > cached_script)
Definition at line 2388 of file compiler.cc.
                                                          {
  // Any data sent to the background thread will need to be a persistent handle.
#ifdef DEBUG
  VerifyCodeMerge(isolate, cached_script);
#else
  if (v8_flags.verify_code_merge) {
    VerifyCodeMerge(isolate, cached_script);
  }
#endif
  persistent_handles_ = std::make_unique<PersistentHandles>(isolate);
  state_ = kPendingBackgroundWork;
  cached_script_ = persistent_handles_->NewHandle(*cached_script);
}
References cached_script_, kPendingBackgroundWork, persistent_handles_, state_, v8::internal::v8_flags, and v8::internal::anonymous_namespace{compiler.cc}::VerifyCodeMerge().
SetUpOnMainThread() [2/2]
void v8::internal::BackgroundMergeTask::SetUpOnMainThread (Isolate * isolate, Handle< String > source_text, const ScriptDetails & script_details, LanguageMode language_mode)
Definition at line 2293 of file compiler.cc.
                                                                        {
  DCHECK_EQ(state_, kNotStarted);
  HandleScope handle_scope(isolate);
  CompilationCacheScript::LookupResult lookup_result =
      isolate->compilation_cache()->LookupScript(source_text, script_details,
                                                 language_mode);
  DirectHandle<Script> script;
  if (!lookup_result.script().ToHandle(&script)) {
    state_ = kDone;
    return;
  }
  if (lookup_result.is_compiled_scope().is_compiled()) {
    // There already exists a compiled top-level SFI, so the main thread will
    // discard the background serialization results and use the top-level SFI
    // from the cache, assuming the top-level SFI is still compiled by then.
    // Thus, there is no need to keep the Script pointer for background merging.
    // Do nothing in this case.
    state_ = kDone;
  } else {
    DCHECK(lookup_result.toplevel_sfi().is_null());
    // A background merge is required.
    SetUpOnMainThread(isolate, script);
  }
}
References v8::internal::Isolate::compilation_cache(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::IsCompiledScope::is_compiled(), v8::internal::CompilationCacheScriptLookupResult::is_compiled_scope(), kDone, kNotStarted, v8::internal::CompilationCache::LookupScript(), v8::internal::CompilationCacheScriptLookupResult::script(), v8::internal::script, state_, and v8::internal::CompilationCacheScriptLookupResult::toplevel_sfi().
Referenced by v8::internal::CodeSerializer::Deserialize(), v8::internal::BackgroundCompileTask::FinalizeScript(), and v8::internal::BackgroundDeserializeTask::SourceTextAvailable().
Member Data Documentation
cached_script_
MaybeHandle<Script> v8::internal::BackgroundMergeTask::cached_script_ [private]
Definition at line 66 of file background-merge-task.h.
Referenced by BeginMergeInBackground(), CompleteMergeInForeground(), and SetUpOnMainThread().
new_compiled_data_for_cached_sfis_
std::vector<NewCompiledDataForCachedSfi> v8::internal::BackgroundMergeTask::new_compiled_data_for_cached_sfis_ [private]
Definition at line 90 of file background-merge-task.h.
Referenced by BeginMergeInBackground(), and CompleteMergeInForeground().
persistent_handles_
std::unique_ptr<PersistentHandles> v8::internal::BackgroundMergeTask::persistent_handles_ [private]
Definition at line 62 of file background-merge-task.h.
Referenced by BeginMergeInBackground(), and SetUpOnMainThread().
state_
State v8::internal::BackgroundMergeTask::state_ = kNotStarted [private]
Definition at line 98 of file background-merge-task.h.
Referenced by BeginMergeInBackground(), CompleteMergeInForeground(), and SetUpOnMainThread().
toplevel_sfi_from_cached_script_
MaybeHandle<SharedFunctionInfo> v8::internal::BackgroundMergeTask::toplevel_sfi_from_cached_script_ [private]
Definition at line 72 of file background-merge-task.h.
Referenced by BeginMergeInBackground().
used_new_sfis_
std::vector<Handle<SharedFunctionInfo> > v8::internal::BackgroundMergeTask::used_new_sfis_ [private]
Definition at line 79 of file background-merge-task.h.
Referenced by BeginMergeInBackground(), and CompleteMergeInForeground().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/background-merge-task.h
/mnt/V8SourceCode/src/codegen/compiler.cc