v8::internal::SafepointEntry Class Reference
#include <safepoint-table.h>
Public Member Functions
SafepointEntry ()=default
SafepointEntry (int pc, int deopt_index, uint32_t tagged_register_indexes, base::Vector< uint8_t > tagged_slots, int trampoline_pc)
bool operator== (const SafepointEntry &other) const
uint32_t tagged_register_indexes () const
base::Vector< const uint8_t > tagged_slots () const
Private Attributes
uint32_t tagged_register_indexes_ = 0
base::Vector< uint8_t > tagged_slots_
Additional Inherited Members
Detailed Description
Definition at line 26 of file safepoint-table.h.
Constructor & Destructor Documentation
SafepointEntry() [1/2]
v8::internal::SafepointEntry::SafepointEntry () [default]
SafepointEntry() [2/2]
v8::internal::SafepointEntry::SafepointEntry (int pc, int deopt_index, uint32_t tagged_register_indexes, base::Vector< uint8_t > tagged_slots, int trampoline_pc) [inline]
Definition at line 30 of file safepoint-table.h.
      : SafepointEntryBase(pc, deopt_index, trampoline_pc),
        tagged_register_indexes_(tagged_register_indexes),
        tagged_slots_(tagged_slots) {
    DCHECK(is_initialized());
  }
References v8::internal::DCHECK(), and v8::internal::SafepointEntryBase::is_initialized().
Member Function Documentation
operator==()
bool v8::internal::SafepointEntry::operator== (const SafepointEntry & other) const [inline]
Definition at line 38 of file safepoint-table.h.
                                                     {
    return this->SafepointEntryBase::operator==(other) &&
           tagged_register_indexes_ == other.tagged_register_indexes_ &&
           tagged_slots_ == other.tagged_slots_;
  }
References v8::internal::SafepointEntryBase::operator==(), tagged_register_indexes_, and tagged_slots_.
tagged_register_indexes()
uint32_t v8::internal::SafepointEntry::tagged_register_indexes () const [inline]
Definition at line 44 of file safepoint-table.h.
                                           {
    DCHECK(is_initialized());
    return tagged_register_indexes_;
  }
References v8::internal::DCHECK(), v8::internal::SafepointEntryBase::is_initialized(), and tagged_register_indexes_.
Referenced by v8::internal::SafepointTable::Print().
tagged_slots()
base::Vector<const uint8_t> v8::internal::SafepointEntry::tagged_slots () const [inline]
Definition at line 49 of file safepoint-table.h.
                                                 {
    DCHECK(is_initialized());
    DCHECK_NOT_NULL(tagged_slots_.data());
    return tagged_slots_;
  }
References v8::base::Vector< T >::data(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::SafepointEntryBase::is_initialized(), and tagged_slots_.
Referenced by v8::internal::TypedFrame::Iterate(), v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame(), and v8::internal::SafepointTable::Print().
Member Data Documentation
tagged_register_indexes_
uint32_t v8::internal::SafepointEntry::tagged_register_indexes_ = 0 [private]
Definition at line 56 of file safepoint-table.h.
Referenced by operator==(), and tagged_register_indexes().
tagged_slots_
base::Vector<uint8_t> v8::internal::SafepointEntry::tagged_slots_ [private]
Definition at line 57 of file safepoint-table.h.
Referenced by operator==(), and tagged_slots().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/safepoint-table.h