v8::internal::FreeList Class Reference
#include <free-list.h>
Classes
class FreeListCategoryIterator
Public Member Functions
FreeList (int number_of_categories, size_t min_block_size)
virtual ~FreeList ()=default
virtual size_t Free (const WritableFreeSpace &free_space, FreeMode mode)
virtual V8_WARN_UNUSED_RESULT Tagged< FreeSpace > Allocate (size_t size_in_bytes, size_t *node_size, AllocationOrigin origin)=0
virtual V8_EXPORT_PRIVATE PageMetadata * GetPageForSize (size_t size_in_bytes)=0
virtual void Reset ()
virtual void ResetForNonBlackAllocatedPages ()
size_t Available ()
void IncreaseAvailableBytes (size_t bytes)
void DecreaseAvailableBytes (size_t bytes)
size_t wasted_bytes () const
void increase_wasted_bytes (size_t bytes)
void decrease_wasted_bytes (size_t bytes)
bool IsEmpty ()
void RepairLists (Heap *heap)
V8_EXPORT_PRIVATE void EvictFreeListItems (PageMetadata *page)
int number_of_categories ()
FreeListCategoryType last_category ()
size_t min_block_size () const
template<typename Callback >
void ForAllFreeListCategories (FreeListCategoryType type, Callback callback)
template<typename Callback >
void ForAllFreeListCategories (Callback callback)
virtual bool AddCategory (FreeListCategory *category)
virtual V8_EXPORT_PRIVATE void RemoveCategory (FreeListCategory *category)
void PrintCategories (FreeListCategoryType type)
Static Public Member Functions
static V8_EXPORT_PRIVATE std::unique_ptr< FreeList > CreateFreeList ()
static V8_EXPORT_PRIVATE std::unique_ptr< FreeList > CreateFreeListForNewSpace ()
Protected Member Functions
void VerifyAvailable ()
Tagged< FreeSpace > TryFindNodeIn (FreeListCategoryType type, size_t minimum_size, size_t *node_size)
Tagged< FreeSpace > SearchForNodeInList (FreeListCategoryType type, size_t minimum_size, size_t *node_size)
virtual FreeListCategoryType SelectFreeListCategoryType (size_t size_in_bytes)=0
FreeListCategory * top (FreeListCategoryType type) const
PageMetadata * GetPageForCategoryType (FreeListCategoryType type)
Protected Attributes
const int number_of_categories_ = 0
const FreeListCategoryType last_category_ = 0
size_t min_block_size_ = 0
FreeListCategory ** categories_ = nullptr
size_t available_ = 0
std::atomic< size_t > wasted_bytes_ = 0
Friends
class FreeListCategory
class PageMetadata
class MutablePageMetadata
class ReadOnlyPageMetadata
class MapSpace
Detailed Description
Definition at line 135 of file free-list.h.
Constructor & Destructor Documentation
FreeList()
v8::internal::FreeList::FreeList (int number_of_categories, size_t min_block_size)
Definition at line 126 of file free-list.cc.
    : number_of_categories_(number_of_categories),
      last_category_(number_of_categories - 1),
      min_block_size_(min_block_size) {}
 FreeList()
virtual v8::internal::FreeList::~FreeList () [virtual], [default]
Member Function Documentation
AddCategory()
bool v8::internal::FreeList::AddCategory (FreeListCategory * category) [virtual]
Reimplemented in v8::internal::FreeListManyCached.
Definition at line 486 of file free-list.cc.
                                                     {
  FreeListCategoryType type = category->type_;
  DCHECK_LT(type, number_of_categories_);
  FreeListCategory* top = categories_[type];
  if (category->is_empty()) return false;
  DCHECK_NE(top, category);
  // Common double-linked list insertion.
  if (top != nullptr) {
    top->set_prev(category);
  }
  category->set_next(top);
  categories_[type] = category;
  IncreaseAvailableBytes(category->available());
  return true;
}
References v8::internal::FreeListCategory::available(), DCHECK_LT, DCHECK_NE, v8::internal::FreeListCategory::is_empty(), v8::internal::FreeListCategory::set_next(), v8::internal::FreeListCategory::set_prev(), v8::internal::tracing::type, and v8::internal::FreeListCategory::type_.
Referenced by v8::internal::FreeListManyCached::AddCategory(), v8::internal::FreeListCategory::Free(), and v8::internal::FreeListCategory::Relink().
Allocate()
virtual V8_WARN_UNUSED_RESULT Tagged<FreeSpace> v8::internal::FreeList::Allocate (size_t size_in_bytes, size_t * node_size, AllocationOrigin origin) [pure virtual]
Implemented in v8::internal::FreeListManyCachedOrigin, v8::internal::FreeListManyCachedFastPathBase, v8::internal::FreeListManyCached, and v8::internal::FreeListMany.
Available()
size_t v8::internal::FreeList::Available () [inline]
Definition at line 169 of file free-list.h.
                     {
    VerifyAvailable();
    return available_;
  }
References available_, and VerifyAvailable().
CreateFreeList()
std::unique_ptr< FreeList > v8::internal::FreeList::CreateFreeList () [static]
Definition at line 131 of file free-list.cc.
                                                 {
  return std::make_unique<FreeListManyCachedOrigin>();
}
CreateFreeListForNewSpace()
std::unique_ptr< FreeList > v8::internal::FreeList::CreateFreeListForNewSpace () [static]
Definition at line 135 of file free-list.cc.
                                                            {
  return std::make_unique<FreeListManyCachedFastPathForNewSpace>();
}
decrease_wasted_bytes()
void v8::internal::FreeList::decrease_wasted_bytes (size_t bytes) [inline]
Definition at line 184 of file free-list.h.
                                           {
    wasted_bytes_.fetch_sub(bytes, std::memory_order_relaxed);
  }
References wasted_bytes_.
DecreaseAvailableBytes()
void v8::internal::FreeList::DecreaseAvailableBytes (size_t bytes) [inline]
Definition at line 176 of file free-list.h.
{ available_ -= bytes; }
References available_.
Referenced by SearchForNodeInList(), TryFindNodeIn(), and v8::internal::FreeListCategory::Unlink().
EvictFreeListItems()
void v8::internal::FreeList::EvictFreeListItems (PageMetadata * page)
Definition at line 471 of file free-list.cc.
                                                    {
  size_t sum = 0;
  page->ForAllFreeListCategories([this, &sum](FreeListCategory* category) {
    sum += category->available();
    RemoveCategory(category);
    category->Reset(this);
  });
  page->add_wasted_memory(sum);
}
References v8::internal::MemoryChunkMetadata::add_wasted_memory(), v8::internal::FreeListCategory::available(), v8::internal::PageMetadata::ForAllFreeListCategories(), and v8::internal::FreeListCategory::Reset().
ForAllFreeListCategories() [1/2]
template<typename Callback >
void v8::internal::FreeList::ForAllFreeListCategories (Callback callback) [inline]
Definition at line 211 of file free-list.h.
                                                   {
    for (int i = kFirstCategory; i < number_of_categories(); i++) {
      ForAllFreeListCategories(static_cast<FreeListCategoryType>(i), callback);
    }
  }
References ForAllFreeListCategories(), v8::internal::kFirstCategory, and number_of_categories().
ForAllFreeListCategories() [2/2]
template<typename Callback >
void v8::internal::FreeList::ForAllFreeListCategories (FreeListCategoryType type, Callback callback) [inline]
Definition at line 201 of file free-list.h.
                                                                              {
    FreeListCategory* current = categories_[type];
    while (current != nullptr) {
      FreeListCategory* next = current->next();
      callback(current);
      current = next;
    }
  }
References categories_, v8::internal::FreeListCategory::next(), and v8::internal::tracing::type.
Referenced by ForAllFreeListCategories(), IsEmpty(), Reset(), and ResetForNonBlackAllocatedPages().
Free()
size_t v8::internal::FreeList::Free (const WritableFreeSpace & free_space, FreeMode mode) [virtual]
Reimplemented in v8::internal::FreeListManyCached.
Definition at line 175 of file free-list.cc.
                                                                        {
  Address start = free_space.Address();
  size_t size_in_bytes = free_space.Size();
  PageMetadata* page = PageMetadata::FromAddress(start);
  page->DecreaseAllocatedBytes(size_in_bytes);
  // Blocks have to be a minimum size to hold free list items.
  if (size_in_bytes < min_block_size_) {
    page->add_wasted_memory(size_in_bytes);
    return size_in_bytes;
  }
  // Insert other blocks at the head of a free list of the appropriate
  // magnitude.
  FreeListCategoryType type = SelectFreeListCategoryType(size_in_bytes);
  page->free_list_category(type)->Free(free_space, mode, this);
  DCHECK_EQ(page->AvailableInFreeList(),
            page->AvailableInFreeListFromAllocatedBytes());
  return 0;
}
References v8::internal::MemoryChunkMetadata::add_wasted_memory(), v8::internal::WritableFreeSpace::Address(), v8::internal::PageMetadata::AvailableInFreeList(), v8::internal::PageMetadata::AvailableInFreeListFromAllocatedBytes(), DCHECK_EQ, v8::internal::MemoryChunkMetadata::DecreaseAllocatedBytes(), v8::internal::FreeListCategory::Free(), v8::internal::PageMetadata::free_list_category(), v8::internal::PageMetadata::FromAddress(), min_block_size_, mode(), SelectFreeListCategoryType(), v8::internal::WritableFreeSpace::Size(), and v8::internal::tracing::type.
GetPageForCategoryType()
PageMetadata * v8::internal::FreeList::GetPageForCategoryType (FreeListCategoryType type) [inline], [protected]
Definition at line 26 of file free-list-inl.h.
                                                                        {
  FreeListCategory* category_top = top(type);
  if (category_top != nullptr) {
    DCHECK(!category_top->top().is_null());
    return PageMetadata::FromHeapObject(category_top->top());
  } else {
    return nullptr;
  }
}
References v8::internal::DCHECK(), v8::internal::PageMetadata::FromHeapObject(), v8::internal::FreeListCategory::top(), top(), and v8::internal::tracing::type.
Referenced by v8::internal::FreeListMany::GetPageForSize().
GetPageForSize()
virtual V8_EXPORT_PRIVATE PageMetadata* v8::internal::FreeList::GetPageForSize (size_t size_in_bytes) [pure virtual]
Implemented in v8::internal::FreeListMany.
increase_wasted_bytes()
void v8::internal::FreeList::increase_wasted_bytes (size_t bytes) [inline]
Definition at line 181 of file free-list.h.
                                           {
    wasted_bytes_.fetch_add(bytes, std::memory_order_relaxed);
  }
References wasted_bytes_.
IncreaseAvailableBytes()
void v8::internal::FreeList::IncreaseAvailableBytes (size_t bytes) [inline]
Definition at line 175 of file free-list.h.
{ available_ += bytes; }
References available_.
Referenced by v8::internal::FreeListCategory::Free().
IsEmpty()
bool v8::internal::FreeList::IsEmpty () [inline]
Definition at line 36 of file free-list-inl.h.
                       {
  bool empty = true;
  ForAllFreeListCategories([&empty](FreeListCategory* category) {
    if (!category->is_empty()) empty = false;
  });
  return empty;
}
References ForAllFreeListCategories(), and v8::internal::FreeListCategory::is_empty().
last_category()
FreeListCategoryType v8::internal::FreeList::last_category () [inline]
Definition at line 196 of file free-list.h.
{ return last_category_; }
References last_category_.
Referenced by v8::internal::PageMetadata::AllocateFreeListCategories(), v8::internal::MutablePageMetadata::ComputeFreeListsLength(), v8::internal::PageMetadata::InitializeFreeListCategories(), and v8::internal::PageMetadata::ReleaseFreeListCategories().
min_block_size()
size_t v8::internal::FreeList::min_block_size () const [inline]
Definition at line 198 of file free-list.h.
{ return min_block_size_; }
References min_block_size_.
number_of_categories()
int v8::internal::FreeList::number_of_categories () [inline]
Definition at line 195 of file free-list.h.
{ return number_of_categories_; }
References number_of_categories_.
Referenced by v8::internal::PageMetadata::AllocateFreeListCategories(), ForAllFreeListCategories(), and v8::internal::PageMetadata::ForAllFreeListCategories().
PrintCategories()
void v8::internal::FreeList::PrintCategories (FreeListCategoryType type)
Definition at line 528 of file free-list.cc.
                                                        {
  FreeListCategoryIterator it(this, type);
  PrintF("FreeList[%p, top=%p, %d] ", static_cast<void*>(this),
         static_cast<void*>(categories_[type]), type);
  while (it.HasNext()) {
    FreeListCategory* current = it.Next();
    PrintF("%p -> ", static_cast<void*>(current));
  }
  PrintF("null\n");
}
References v8::internal::FreeList::FreeListCategoryIterator::HasNext(), v8::internal::FreeList::FreeListCategoryIterator::Next(), v8::internal::PrintF(), and v8::internal::tracing::type.
RemoveCategory()
void v8::internal::FreeList::RemoveCategory (FreeListCategory * category) [virtual]
Reimplemented in v8::internal::FreeListManyCached.
Definition at line 505 of file free-list.cc.
                                                        {
  FreeListCategoryType type = category->type_;
  DCHECK_LT(type, number_of_categories_);
  FreeListCategory* top = categories_[type];
  if (category->is_linked(this)) {
    DecreaseAvailableBytes(category->available());
  }
  // Common double-linked list removal.
  if (top == category) {
    categories_[type] = category->next();
  }
  if (category->prev() != nullptr) {
    category->prev()->set_next(category->next());
  }
  if (category->next() != nullptr) {
    category->next()->set_prev(category->prev());
  }
  category->set_next(nullptr);
  category->set_prev(nullptr);
}
References v8::internal::FreeListCategory::available(), DCHECK_LT, v8::internal::FreeListCategory::is_linked(), v8::internal::FreeListCategory::next(), v8::internal::FreeListCategory::prev(), v8::internal::FreeListCategory::set_next(), v8::internal::FreeListCategory::set_prev(), v8::internal::tracing::type, and v8::internal::FreeListCategory::type_.
Referenced by v8::internal::FreeListManyCached::RemoveCategory(), SearchForNodeInList(), and TryFindNodeIn().
RepairLists()
void v8::internal::FreeList::RepairLists (Heap * heap)
Definition at line 481 of file free-list.cc.
                                     {
  ForAllFreeListCategories(
      [heap](FreeListCategory* category) { category->RepairFreeList(heap); });
}
References v8::internal::FreeListCategory::RepairFreeList().
Reset()
void v8::internal::FreeList::Reset () [virtual]
Reimplemented in v8::internal::FreeListManyCached.
Definition at line 442 of file free-list.cc.
                     {
  ForAllFreeListCategories(
      [this](FreeListCategory* category) { category->Reset(this); });
  for (int i = kFirstCategory; i < number_of_categories_; i++) {
    categories_[i] = nullptr;
  }
  wasted_bytes_ = 0;
  available_ = 0;
}
References available_, categories_, ForAllFreeListCategories(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kFirstCategory, number_of_categories_, v8::internal::FreeListCategory::Reset(), and wasted_bytes_.
Referenced by v8::internal::FreeListMany::FreeListMany(), and v8::internal::FreeListManyCached::Reset().
ResetForNonBlackAllocatedPages()
void v8::internal::FreeList::ResetForNonBlackAllocatedPages () [virtual]
Reimplemented in v8::internal::FreeListManyCached.
Definition at line 452 of file free-list.cc.
                                              {
  DCHECK(v8_flags.black_allocated_pages);
  ForAllFreeListCategories([this](FreeListCategory* category) {
    if (!category->is_empty()) {
      auto* chunk = MemoryChunk::FromHeapObject(category->top());
      if (chunk->IsFlagSet(MemoryChunk::BLACK_ALLOCATED)) {
        category->Unlink(this);
        return;
      }
    }
    category->Reset(this);
  });
  for (int i = kFirstCategory; i < number_of_categories_; i++) {
    categories_[i] = nullptr;
  }
  wasted_bytes_ = 0;
  available_ = 0;
}
References v8::internal::DCHECK(), ForAllFreeListCategories(), v8::internal::FreeListCategory::is_empty(), v8::internal::FreeListCategory::Reset(), and v8::internal::v8_flags.
Referenced by v8::internal::FreeListManyCached::ResetForNonBlackAllocatedPages().
SearchForNodeInList()
Tagged< FreeSpace > v8::internal::FreeList::SearchForNodeInList (FreeListCategoryType type, size_t minimum_size, size_t * node_size) [protected]
Definition at line 155 of file free-list.cc.
                                                                   {
  FreeListCategoryIterator it(this, type);
  Tagged<FreeSpace> node;
  while (it.HasNext()) {
    FreeListCategory* current = it.Next();
    node = current->SearchForNodeInList(minimum_size, node_size);
    if (!node.is_null()) {
      DecreaseAvailableBytes(*node_size);
      VerifyAvailable();
      if (current->is_empty()) {
        RemoveCategory(current);
      }
      return node;
    }
  }
  return node;
}
References DecreaseAvailableBytes(), v8::internal::FreeList::FreeListCategoryIterator::HasNext(), v8::internal::FreeListCategory::is_empty(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::FreeList::FreeListCategoryIterator::Next(), RemoveCategory(), v8::internal::FreeListCategory::SearchForNodeInList(), v8::internal::tracing::type, and VerifyAvailable().
Referenced by v8::internal::FreeListMany::Allocate(), v8::internal::FreeListManyCached::Allocate(), and v8::internal::FreeListManyCachedFastPathBase::Allocate().
SelectFreeListCategoryType()
virtual FreeListCategoryType v8::internal::FreeList::SelectFreeListCategoryType (size_t size_in_bytes) [protected], [pure virtual]
Implemented in v8::internal::FreeListMany.
Referenced by Free().
top()
FreeListCategory* v8::internal::FreeList::top (FreeListCategoryType type) const [inline], [protected]
Definition at line 264 of file free-list.h.
                                                         {
    return categories_[type];
  }
References categories_, and v8::internal::tracing::type.
Referenced by GetPageForCategoryType().
TryFindNodeIn()
Tagged< FreeSpace > v8::internal::FreeList::TryFindNodeIn (FreeListCategoryType type, size_t minimum_size, size_t * node_size) [protected]
Definition at line 139 of file free-list.cc.
                                                             {
  FreeListCategory* category = categories_[type];
  if (category == nullptr) return Tagged<FreeSpace>();
  Tagged<FreeSpace> node = category->PickNodeFromList(minimum_size, node_size);
  if (!node.is_null()) {
    DecreaseAvailableBytes(*node_size);
    VerifyAvailable();
  }
  if (category->is_empty()) {
    RemoveCategory(category);
  }
  return node;
}
References categories_, DecreaseAvailableBytes(), v8::internal::FreeListCategory::is_empty(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::FreeListCategory::PickNodeFromList(), RemoveCategory(), v8::internal::tracing::type, and VerifyAvailable().
Referenced by v8::internal::FreeListMany::Allocate(), v8::internal::FreeListManyCached::Allocate(), and v8::internal::FreeListManyCachedFastPathBase::Allocate().
VerifyAvailable()
void v8::internal::FreeList::VerifyAvailable () [inline], [protected]
Definition at line 245 of file free-list.h.
                         {
    DCHECK(IsVeryLong() || available_ == SumFreeLists());
  }
References available_, and v8::internal::DCHECK().
Referenced by v8::internal::FreeListMany::Allocate(), v8::internal::FreeListManyCached::Allocate(), v8::internal::FreeListManyCachedFastPathBase::Allocate(), Available(), SearchForNodeInList(), and TryFindNodeIn().
wasted_bytes()
size_t v8::internal::FreeList::wasted_bytes () const [inline]
Definition at line 178 of file free-list.h.
                              {
    return wasted_bytes_.load(std::memory_order_relaxed);
  }
References wasted_bytes_.
Friends And Related Function Documentation
FreeListCategory
friend class FreeListCategory [friend]
Definition at line 282 of file free-list.h.
MapSpace
friend class MapSpace [friend]
Definition at line 286 of file free-list.h.
MutablePageMetadata
friend class MutablePageMetadata [friend]
Definition at line 284 of file free-list.h.
PageMetadata
friend class PageMetadata [friend]
Definition at line 283 of file free-list.h.
ReadOnlyPageMetadata
friend class ReadOnlyPageMetadata [friend]
Definition at line 285 of file free-list.h.
Member Data Documentation
available_
size_t v8::internal::FreeList::available_ = 0 [protected]
Definition at line 277 of file free-list.h.
Referenced by Available(), DecreaseAvailableBytes(), IncreaseAvailableBytes(), Reset(), and VerifyAvailable().
categories_
FreeListCategory** v8::internal::FreeList::categories_ = nullptr [protected]
Definition at line 274 of file free-list.h.
Referenced by v8::internal::FreeListManyCached::Allocate(), v8::internal::FreeListManyCachedFastPathBase::Allocate(), ForAllFreeListCategories(), v8::internal::FreeListMany::FreeListMany(), v8::internal::FreeListCategory::is_linked(), v8::internal::FreeListManyCached::RemoveCategory(), Reset(), top(), TryFindNodeIn(), and v8::internal::FreeListMany::~FreeListMany().
last_category_
const FreeListCategoryType v8::internal::FreeList::last_category_ = 0 [protected]
Definition at line 271 of file free-list.h.
Referenced by v8::internal::FreeListMany::Allocate(), v8::internal::FreeListManyCached::Allocate(), v8::internal::FreeListManyCachedFastPathBase::Allocate(), v8::internal::FreeListMany::GetPageForSize(), and last_category().
min_block_size_
size_t v8::internal::FreeList::min_block_size_ = 0 [protected]
Definition at line 272 of file free-list.h.
Referenced by Free(), v8::internal::FreeListManyCached::Free(), and min_block_size().
number_of_categories_
const int v8::internal::FreeList::number_of_categories_ = 0 [protected]
Definition at line 270 of file free-list.h.
Referenced by v8::internal::FreeListMany::FreeListMany(), number_of_categories(), and Reset().
wasted_bytes_
std::atomic<size_t> v8::internal::FreeList::wasted_bytes_ = 0 [protected]
Definition at line 280 of file free-list.h.
Referenced by decrease_wasted_bytes(), increase_wasted_bytes(), Reset(), and wasted_bytes().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/free-list.h
/mnt/V8SourceCode/src/heap/free-list-inl.h
/mnt/V8SourceCode/src/heap/free-list.cc