v8::internal::PrototypeUsers Class Reference
#include <prototype-info.h>
Public Types
using CompactionCallback = void(*)(Tagged< HeapObject > object, int from_index, int to_index)
Static Public Member Functions
static Handle< WeakArrayList > Add (Isolate *isolate, Handle< WeakArrayList > array, DirectHandle< Map > value, int *assigned_index)
static void MarkSlotEmpty (Tagged< WeakArrayList > array, int index)
static Tagged< WeakArrayList > Compact (DirectHandle< WeakArrayList > array, Heap *heap, CompactionCallback callback, AllocationType allocation=AllocationType::kYoung)
Static Public Attributes
static const int kEmptySlotIndex = 0
static const int kFirstIndex = 1
static const int kNoEmptySlotsMarker = 0
Private Member Functions
DISALLOW_IMPLICIT_CONSTRUCTORS (PrototypeUsers)
Static Private Member Functions
static Tagged< Smi > empty_slot_index (Tagged< WeakArrayList > array)
static void set_empty_slot_index (Tagged< WeakArrayList > array, int index)
static void ScanForEmptySlots (Tagged< WeakArrayList > array)
Additional Inherited Members
Detailed Description
Definition at line 71 of file prototype-info.h.
Member Typedef Documentation
CompactionCallback
using v8::internal::PrototypeUsers::CompactionCallback = void (*)(Tagged<HeapObject> object, int from_index, int to_index)
Definition at line 83 of file prototype-info.h.
Member Function Documentation
Add()
Handle< WeakArrayList > v8::internal::PrototypeUsers::Add (Isolate * isolate, Handle< WeakArrayList > array, DirectHandle< Map > value, int * assigned_index) [static]
Definition at line 3809 of file objects.cc.
                                                               {
  int length = array->length();
  if (length == 0) {
    // Uninitialized WeakArrayList; need to initialize empty_slot_index.
    array = WeakArrayList::EnsureSpace(isolate, array, kFirstIndex + 1);
    set_empty_slot_index(*array, kNoEmptySlotsMarker);
    array->Set(kFirstIndex, MakeWeak(*value));
    array->set_length(kFirstIndex + 1);
    if (assigned_index != nullptr) *assigned_index = kFirstIndex;
    return array;
  }
  // If the array has unfilled space at the end, use it.
  if (!array->IsFull()) {
    array->Set(length, MakeWeak(*value));
    array->set_length(length + 1);
    if (assigned_index != nullptr) *assigned_index = length;
    return array;
  }
  // If there are empty slots, use one of them.
  int empty_slot = Smi::ToInt(empty_slot_index(*array));
  if (empty_slot == kNoEmptySlotsMarker) {
    // GCs might have cleared some references, rescan the array for empty slots.
    PrototypeUsers::ScanForEmptySlots(*array);
    empty_slot = Smi::ToInt(empty_slot_index(*array));
  }
  if (empty_slot != kNoEmptySlotsMarker) {
    DCHECK_GE(empty_slot, kFirstIndex);
    CHECK_LT(empty_slot, array->length());
    int next_empty_slot = array->Get(empty_slot).ToSmi().value();
    array->Set(empty_slot, MakeWeak(*value));
    if (assigned_index != nullptr) *assigned_index = empty_slot;
    set_empty_slot_index(*array, next_empty_slot);
    return array;
  } else {
    DCHECK_EQ(empty_slot, kNoEmptySlotsMarker);
  }
  // Array full and no empty slots. Grow the array.
  array = WeakArrayList::EnsureSpace(isolate, array, length + 1);
  array->Set(length, MakeWeak(*value));
  array->set_length(length + 1);
  if (assigned_index != nullptr) *assigned_index = length;
  return array;
}
References CHECK_LT, DCHECK_EQ, DCHECK_GE, empty_slot_index(), v8::internal::WeakArrayList::EnsureSpace(), kFirstIndex, kNoEmptySlotsMarker, v8::internal::length, v8::internal::MakeWeak(), ScanForEmptySlots(), set_empty_slot_index(), v8::internal::Smi::ToInt(), and v8::internal::value.
Referenced by v8::internal::JSObject::LazyRegisterPrototypeUser().
Compact()
Tagged< WeakArrayList > v8::internal::PrototypeUsers::Compact (DirectHandle< WeakArrayList > array, Heap * heap, CompactionCallback callback, AllocationType allocation = AllocationType::kYoung) [static]
Definition at line 3872 of file objects.cc.
                                                                         {
  if (array->length() == 0) {
    return *array;
  }
  int new_length = kFirstIndex + array->CountLiveWeakReferences();
  if (new_length == array->length()) {
    return *array;
  }
  DirectHandle<WeakArrayList> new_array = WeakArrayList::EnsureSpace(
      heap->isolate(),
      handle(ReadOnlyRoots(heap).empty_weak_array_list(), heap->isolate()),
      new_length, allocation);
  // Allocation might have caused GC and turned some of the elements into
  // cleared weak heap objects. Count the number of live objects again.
  int copy_to = kFirstIndex;
  for (int i = kFirstIndex; i < array->length(); i++) {
    Tagged<MaybeObject> element = array->Get(i);
    Tagged<HeapObject> value;
    if (element.GetHeapObjectIfWeak(&value)) {
      callback(value, i, copy_to);
      new_array->Set(copy_to++, element);
    } else {
      DCHECK(element.IsCleared() || element.IsSmi());
    }
  }
  new_array->set_length(copy_to);
  set_empty_slot_index(*new_array, kNoEmptySlotsMarker);
  return *new_array;
}
References v8::internal::DCHECK(), v8::internal::WeakArrayList::EnsureSpace(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), v8::internal::handle(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::Tagged< HeapObject >::IsSmi(), kFirstIndex, kNoEmptySlotsMarker, set_empty_slot_index(), and v8::internal::value.
Referenced by v8::internal::Heap::CompactWeakArrayLists().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::PrototypeUsers::DISALLOW_IMPLICIT_CONSTRUCTORS (PrototypeUsers) [private]
empty_slot_index()
Tagged< Smi > v8::internal::PrototypeUsers::empty_slot_index (Tagged< WeakArrayList > array) [inline], [static], [private]
Definition at line 150 of file prototype-info-inl.h.
                                                                        {
  return array->Get(kEmptySlotIndex).ToSmi();
}
References kEmptySlotIndex, and v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi().
Referenced by Add(), and v8::internal::BOOL_ACCESSORS().
MarkSlotEmpty()
static void v8::internal::PrototypeUsers::MarkSlotEmpty (Tagged< WeakArrayList > array, int index) [inline], [static]
Referenced by ScanForEmptySlots(), and v8::internal::JSObject::UnregisterPrototypeUser().
ScanForEmptySlots()
void v8::internal::PrototypeUsers::ScanForEmptySlots (Tagged< WeakArrayList > array) [static], [private]
Definition at line 3864 of file objects.cc.
                                                                  {
  for (int i = kFirstIndex; i < array->length(); i++) {
    if (array->Get(i).IsCleared()) {
      PrototypeUsers::MarkSlotEmpty(array, i);
    }
  }
}
References v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), kFirstIndex, and MarkSlotEmpty().
Referenced by Add().
set_empty_slot_index()
void v8::internal::PrototypeUsers::set_empty_slot_index (Tagged< WeakArrayList > array, int index) [inline], [static], [private]
Definition at line 154 of file prototype-info-inl.h.
                                                     {
  array->Set(kEmptySlotIndex, Smi::FromInt(index));
}
References v8::internal::Smi::FromInt(), v8::internal::index, and kEmptySlotIndex.
Referenced by Add(), v8::internal::BOOL_ACCESSORS(), and Compact().
Member Data Documentation
kEmptySlotIndex
const int v8::internal::PrototypeUsers::kEmptySlotIndex = 0 [static]
Definition at line 94 of file prototype-info.h.
Referenced by empty_slot_index(), and set_empty_slot_index().
kFirstIndex
const int v8::internal::PrototypeUsers::kFirstIndex = 1 [static]
Definition at line 95 of file prototype-info.h.
Referenced by Add(), Compact(), v8::internal::anonymous_namespace{js-objects.cc}::InvalidatePrototypeChainsInternal(), and ScanForEmptySlots().
kNoEmptySlotsMarker
const int v8::internal::PrototypeUsers::kNoEmptySlotsMarker = 0 [static]
Definition at line 97 of file prototype-info.h.
Referenced by Add(), and Compact().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/prototype-info.h
/mnt/V8SourceCode/src/objects/objects.cc
/mnt/V8SourceCode/src/objects/prototype-info-inl.h