v8::internal::ContextFilter Class Reference
#include <profile-generator.h>
Public Member Functions
ContextFilter (Address native_context_address=kNullAddress)
void OnMoveEvent (Address from_address, Address to_address)
bool Accept (Address native_context_address) const
void set_native_context_address (Address address)
Address native_context_address () const
Private Attributes
Address native_context_address_
Detailed Description
Definition at line 274 of file profile-generator.h.
Constructor & Destructor Documentation
ContextFilter()
v8::internal::ContextFilter::ContextFilter (Address native_context_address = kNullAddress) [inline], [explicit]
Definition at line 276 of file profile-generator.h.
      : native_context_address_(native_context_address) {}
Member Function Documentation
Accept()
bool v8::internal::ContextFilter::Accept (Address native_context_address) const [inline]
Definition at line 282 of file profile-generator.h.
                                                    {
    if (native_context_address_ == kNullAddress) return true;
    return (native_context_address & ~kHeapObjectTag) ==
           native_context_address_;
  }
References v8::internal::kHeapObjectTag, v8::internal::kNullAddress, native_context_address(), and native_context_address_.
Referenced by v8::internal::CpuProfilesCollection::AddPathToCurrentProfiles().
native_context_address()
Address v8::internal::ContextFilter::native_context_address () const [inline]
Definition at line 292 of file profile-generator.h.
{ return native_context_address_; }
References native_context_address_.
Referenced by Accept(), and OnMoveEvent().
OnMoveEvent()
void v8::internal::ContextFilter::OnMoveEvent (Address from_address, Address to_address)
Definition at line 565 of file profile-generator.cc.
                                                                        {
  if (native_context_address() != from_address) return;
  set_native_context_address(to_address);
}
References native_context_address(), and set_native_context_address().
set_native_context_address()
void v8::internal::ContextFilter::set_native_context_address (Address address) [inline]
Definition at line 289 of file profile-generator.h.
                                                   {
    native_context_address_ = address;
  }
References native_context_address_.
Referenced by v8::internal::CpuProfile::CpuProfile(), v8::internal::CpuProfile::FinishProfile(), and OnMoveEvent().
Member Data Documentation
native_context_address_
Address v8::internal::ContextFilter::native_context_address_ [private]
Definition at line 295 of file profile-generator.h.
Referenced by Accept(), native_context_address(), and set_native_context_address().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/profile-generator.h
/mnt/V8SourceCode/src/profiler/profile-generator.cc