v8::internal::wasm::EffectHandlerTableIterator< ValidationTag > Class Template Reference
#include <function-body-decoder-impl.h>
Public Member Functions
uint32_t cur_index () const
bool has_next () const
HandlerCase next ()
uint32_t length () const
const uint8_t * pc () const
EffectHandlerTableIterator (Decoder *decoder, const EffectHandlerTableImmediate &imm)
Private Attributes
Decoder *const decoder_
const uint8_t *const start_
const uint8_t * pc_
uint32_t index_ = 0
const uint32_t table_count_
Detailed Description
template<typename ValidationTag>
class v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >
Definition at line 1012 of file function-body-decoder-impl.h.
Constructor & Destructor Documentation
EffectHandlerTableIterator()
template<typename ValidationTag >
v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::EffectHandlerTableIterator (Decoder * decoder, const EffectHandlerTableImmediate & imm) [inline]
Definition at line 1045 of file function-body-decoder-impl.h.
      : decoder_(decoder),
        start_(imm.start),
        pc_(imm.table),
        table_count_(imm.table_count) {}
Member Function Documentation
cur_index()
template<typename ValidationTag >
uint32_t v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::cur_index () const [inline]
Definition at line 1014 of file function-body-decoder-impl.h.
{ return index_; }
References v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::index_.
has_next()
template<typename ValidationTag >
bool v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::has_next () const [inline]
Definition at line 1015 of file function-body-decoder-impl.h.
                        {
    return VALIDATE(decoder_->ok()) && index_ < table_count_;
  }
References v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::decoder_, v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::index_, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::table_count_, and VALIDATE.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeEffectHandlerTable(), v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::length(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength().
length()
template<typename ValidationTag >
uint32_t v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::length () const [inline]
Definition at line 1039 of file function-body-decoder-impl.h.
                          {
    DCHECK(!has_next());
    return static_cast<uint32_t>(pc_ - start_);
  }
References v8::internal::DCHECK(), v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::has_next(), v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::pc_, and v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::start_.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeEffectHandlerTable(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength().
next()
template<typename ValidationTag >
HandlerCase v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::next () [inline]
Definition at line 1019 of file function-body-decoder-impl.h.
                     {
    uint8_t kind =
        static_cast<CatchKind>(decoder_->read_u8<ValidationTag>(pc_));
    pc_ += 1;
    TagIndexImmediate tag = TagIndexImmediate(decoder_, pc_, ValidationTag{});
    pc_ += tag.length;
    HandlerCase::MaybeHandlerDepth maybe_depth{0};
    if (kind == kOnSuspend) {
      maybe_depth.br = BranchDepthImmediate(decoder_, pc_, ValidationTag{});
      pc_ += maybe_depth.br.length;
    }
    index_++;
    return HandlerCase{static_cast<SwitchKind>(kind), tag, maybe_depth};
  }
References v8::internal::wasm::HandlerCase::MaybeHandlerDepth::br, v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::decoder_, v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::index_, v8::internal::wasm::kOnSuspend, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::pc_, and v8::internal::wasm::Decoder::read_u8().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeEffectHandlerTable(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength().
pc()
template<typename ValidationTag >
const uint8_t* v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::pc () const [inline]
Definition at line 1043 of file function-body-decoder-impl.h.
{ return pc_; }
References v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::pc_.
Member Data Documentation
decoder_
template<typename ValidationTag >
Decoder* const v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::decoder_ [private]
Definition at line 1053 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::has_next(), and v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::next().
index_
template<typename ValidationTag >
uint32_t v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::index_ = 0 [private]
Definition at line 1056 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::cur_index(), v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::has_next(), and v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::next().
pc_
template<typename ValidationTag >
const uint8_t* v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::pc_ [private]
Definition at line 1055 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::length(), v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::next(), and v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::pc().
start_
template<typename ValidationTag >
const uint8_t* const v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::start_ [private]
Definition at line 1054 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::length().
table_count_
template<typename ValidationTag >
const uint32_t v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::table_count_ [private]
Definition at line 1057 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::has_next().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/function-body-decoder-impl.h