v8::internal::SerializedData Class Reference
#include <snapshot-data.h>
Public Types
using ChunkSizeBits = base::BitField< uint32_t, 0, 31 >
using IsLastChunkBits = base::BitField< bool, 31, 1 >
Public Member Functions
SerializedData (uint8_t *data, int size)
SerializedData ()
SerializedData (SerializedData &&other) V8_NOEXCEPT
SerializedData (const SerializedData &)=delete
SerializedData & operator= (const SerializedData &)=delete
virtual ~SerializedData ()
uint32_t GetMagicNumber () const
Static Public Attributes
static constexpr uint32_t kMagicNumberOffset = 0
static constexpr uint32_t kMagicNumber
Protected Member Functions
void SetHeaderValue (uint32_t offset, uint32_t value)
uint32_t GetHeaderValue (uint32_t offset) const
void AllocateData (uint32_t size)
void SetMagicNumber ()
Protected Attributes
uint8_t * data_
uint32_t size_
bool owns_data_
Detailed Description
Definition at line 21 of file snapshot-data.h.
Member Typedef Documentation
ChunkSizeBits
using v8::internal::SerializedData::ChunkSizeBits = base::BitField<uint32_t, 0, 31>
Definition at line 42 of file snapshot-data.h.
IsLastChunkBits
using v8::internal::SerializedData::IsLastChunkBits = base::BitField<bool, 31, 1>
Definition at line 43 of file snapshot-data.h.
Constructor & Destructor Documentation
SerializedData() [1/4]
v8::internal::SerializedData::SerializedData (uint8_t * data, int size) [inline]
Definition at line 23 of file snapshot-data.h.
      : data_(data), size_(size), owns_data_(false) {}
SerializedData() [2/4]
v8::internal::SerializedData::SerializedData () [inline]
Definition at line 25 of file snapshot-data.h.
: data_(nullptr), size_(0), owns_data_(false) {}
SerializedData() [3/4]
v8::internal::SerializedData::SerializedData (SerializedData && other) [inline]
Definition at line 26 of file snapshot-data.h.
      : data_(other.data_),
        size_(other.size_),
        owns_data_(other.owns_data_) {
    // Ensure |other| will not attempt to destroy our data in destructor.
    other.owns_data_ = false;
  }
SerializedData() [4/4]
v8::internal::SerializedData::SerializedData (const SerializedData &) [delete]
 SerializedData()
virtual v8::internal::SerializedData::~SerializedData () [inline], [virtual]
Definition at line 36 of file snapshot-data.h.
                            {
    if (owns_data_) DeleteArray<uint8_t>(data_);
  }
References data_, and owns_data_.
Member Function Documentation
AllocateData()
void v8::internal::SerializedData::AllocateData (uint32_t size) [protected]
Definition at line 13 of file snapshot-data.cc.
                                               {
  DCHECK(!owns_data_);
  data_ = NewArray<uint8_t>(size);
  size_ = size;
  owns_data_ = true;
}
References data_, v8::internal::DCHECK(), owns_data_, size(), and size_.
Referenced by v8::internal::SnapshotCompression::Compress(), v8::internal::SnapshotCompression::Decompress(), and v8::internal::SnapshotData::SnapshotData().
GetHeaderValue()
uint32_t v8::internal::SerializedData::GetHeaderValue (uint32_t offset) const [inline], [protected]
Definition at line 55 of file snapshot-data.h.
                                                 {
    return base::ReadLittleEndianValue<uint32_t>(
        reinterpret_cast<Address>(data_) + offset);
  }
References data_.
Referenced by GetMagicNumber(), and v8::internal::SnapshotData::Payload().
GetMagicNumber()
uint32_t v8::internal::SerializedData::GetMagicNumber () const [inline]
Definition at line 40 of file snapshot-data.h.
{ return GetHeaderValue(kMagicNumberOffset); }
References GetHeaderValue(), and kMagicNumberOffset.
operator=()
SerializedData& v8::internal::SerializedData::operator= (const SerializedData &) [delete]
SetHeaderValue()
void v8::internal::SerializedData::SetHeaderValue (uint32_t offset, uint32_t value) [inline], [protected]
Definition at line 50 of file snapshot-data.h.
                                                       {
    base::WriteLittleEndianValue(reinterpret_cast<Address>(data_) + offset,
                                 value);
  }
References data_, v8::internal::value, and v8::base::WriteLittleEndianValue().
Referenced by SetMagicNumber(), and v8::internal::SnapshotData::SnapshotData().
SetMagicNumber()
void v8::internal::SerializedData::SetMagicNumber () [inline], [protected]
Definition at line 62 of file snapshot-data.h.
{ SetHeaderValue(kMagicNumberOffset, kMagicNumber); }
References kMagicNumber, kMagicNumberOffset, and SetHeaderValue().
Referenced by v8::internal::SnapshotData::SnapshotData().
Member Data Documentation
data_
uint8_t* v8::internal::SerializedData::data_ [protected]
Definition at line 64 of file snapshot-data.h.
Referenced by AllocateData(), GetHeaderValue(), v8::internal::SnapshotData::Payload(), SetHeaderValue(), v8::internal::SnapshotData::SnapshotData(), and ~SerializedData().
kMagicNumber
constexpr uint32_t v8::internal::SerializedData::kMagicNumber [static], [constexpr]
Initial value:
=
      0xC0DE0000 ^ ExternalReferenceTable::kSize
Definition at line 46 of file snapshot-data.h.
Referenced by v8::internal::Deserializer< IsolateT >::Deserializer(), SetMagicNumber(), and v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::WriteHeader().
kMagicNumberOffset
constexpr uint32_t v8::internal::SerializedData::kMagicNumberOffset = 0 [static], [constexpr]
Definition at line 45 of file snapshot-data.h.
Referenced by GetMagicNumber(), and SetMagicNumber().
owns_data_
bool v8::internal::SerializedData::owns_data_ [protected]
Definition at line 66 of file snapshot-data.h.
Referenced by AllocateData(), and ~SerializedData().
size_
uint32_t v8::internal::SerializedData::size_ [protected]
Definition at line 65 of file snapshot-data.h.
Referenced by AllocateData(), and v8::internal::SnapshotData::Payload().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/snapshot-data.h
/mnt/V8SourceCode/src/snapshot/snapshot-data.cc