v8::base::BitField< T, shift, size, U > Class Template Reference
#include <bit-field.h>
Public Types
using FieldType = T
using BaseType = U
template<class T2 , int size2>
using Next = BitField< T2, kShift+kSize, size2, U >
Static Public Member Functions
static constexpr bool is_valid (T value)
static constexpr U encode (T value)
static constexpr U update (U previous, T value)
static constexpr T decode (U value)
Static Public Attributes
static constexpr int kShift = shift
static constexpr int kSize = size
static constexpr U kMask = ((U{1} << kShift) << kSize) - (U{1} << kShift)
static constexpr int kLastUsedBit = kShift + kSize - 1
static constexpr U kNumValues = U{1} << kSize
static constexpr U kMax = kNumValues - 1
Detailed Description
template<class T, int shift, int size, class U = uint32_t>
class v8::base::BitField< T, shift, size, U >
Definition at line 25 of file bit-field.h.
Member Typedef Documentation
BaseType
template<class T , int shift, int size, class U = uint32_t>
using v8::base::BitField< T, shift, size, U >::BaseType = U
Definition at line 34 of file bit-field.h.
FieldType
template<class T , int shift, int size, class U = uint32_t>
using v8::base::BitField< T, shift, size, U >::FieldType = T
Definition at line 33 of file bit-field.h.
Next
template<class T , int shift, int size, class U = uint32_t>
template<class T2 , int size2>
using v8::base::BitField< T, shift, size, U >::Next = BitField<T2, kShift + kSize, size2, U>
Definition at line 47 of file bit-field.h.
Member Function Documentation
decode()
template<class T , int shift, int size, class U = uint32_t>
static constexpr T v8::base::BitField< T, shift, size, U >::decode (U value) [inline], [static], [constexpr]
Definition at line 66 of file bit-field.h.
                                     {
    return static_cast<T>((value & kMask) >> kShift);
  }
References v8::base::BitField< T, shift, size, U >::kMask, v8::base::BitField< T, shift, size, U >::kShift, and v8::internal::value.
Referenced by v8::internal::ArrayBufferExtension::AccountingState::accounting_length(), v8::internal::compiler::Instruction::addressing_mode(), v8::internal::ArrayBufferExtension::AccountingState::age(), v8::internal::compiler::Node::AppendInput(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ApplyCompilationHintToInitialProgress(), v8::internal::compiler::JumpThreading::ApplyForwarding(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ApplyPgoInfoLate(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ApplyPgoInfoToInitialProgress(), v8::internal::compiler::Instruction::arch_opcode(), v8::internal::compiler::ConstructForwardVarargsParameters::arity(), v8::internal::compiler::CallForwardVarargsParameters::arity(), v8::internal::compiler::CallParameters::arity(), v8::internal::String::AsArrayIndex(), v8::internal::PreParserExpression::AsIdentifier(), v8::internal::String::AsIntegerIndex(), v8::internal::VariableDeclaration::AsNested(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleInstruction(), v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::AssembleOp(), v8::internal::SerializerReference::attached_reference_index(), v8::internal::PropertyDetails::attributes(), v8::internal::SerializerReference::back_ref_index(), v8::internal::maglev::MergePointInterpreterFrameState::basic_block_type(), v8::internal::compiler::UnallocatedOperand::basic_policy(), v8::internal::BIT_FIELD_ACCESSORS(), v8::internal::LiteralBoilerplateBuilder::boilerplate_descriptor_kind(), v8::internal::compiler::Instruction::branch_hinted(), v8::internal::CodeEntry::builtin(), v8::internal::SerializerReference::builtin_index(), v8::internal::maglev::OpProperties::can_allocate(), v8::internal::maglev::OpProperties::can_eager_deopt(), v8::internal::maglev::OpProperties::can_lazy_deopt(), v8::internal::maglev::OpProperties::can_read(), v8::internal::maglev::OpProperties::can_throw(), v8::internal::maglev::OpProperties::can_write(), v8::internal::compiler::Loong64OperandGenerator::CanBeImmediate(), v8::internal::compiler::Mips64OperandGenerator::CanBeImmediate(), v8::internal::compiler::RiscvOperandGenerator::CanBeImmediate(), v8::internal::compiler::ArmOperandGenerator::CanBeImmediate(), v8::internal::LoadHandler::CanHandleHolderNotLookupStart(), v8::internal::AllocationSite::CanInlineCall(), v8::internal::PropertyDetails::cell_type(), v8::internal::JSAtomicsMutex::CleanupMatchingAsyncWaiters(), unibrow::Predicate< T, size >::CacheEntry::code_point(), v8::internal::CodeEntry::code_tag(), v8::internal::CodeEntry::code_type_string(), v8::internal::compiler::CodeGenerator::ComputeBranchInfo(), v8::internal::compiler::JumpThreading::ComputeForwarding(), v8::internal::anonymous_namespace{strings-storage.cc}::ComputeStringHash(), v8::internal::PropertyDetails::constness(), v8::internal::compiler::CallParameters::convert_mode(), cppgc::internal::HeapObjectHeader::DecodeSize(), v8::internal::AllocationSite::deopt_dependent_code(), v8::internal::MaglevSafepointTable::deopt_index_size(), v8::internal::SafepointTable::deopt_index_size(), v8::internal::maglev::LazyDeoptInfo::deopting_call_return_pc(), v8::internal::LiteralBoilerplateBuilder::depth(), v8::internal::JSSynchronizationPrimitive::DestructivelyGetWaiterQueueHead(), v8::internal::PropertyDetails::dictionary_index(), v8::internal::BigInt::DigitsByteLengthForBitfield(), v8::internal::JSDisposableStackBase::DisposeResources(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitStore(), v8::internal::TranslatedState::EnsureCapturedObjectAllocatedAt(), v8::internal::Name::EnsureHash(), v8::internal::Call::eval_scope_info_index(), v8::internal::CodeEntry::event(), v8::internal::wasm::ValueTypeBase::exactness(), v8::internal::compiler::UnallocatedOperand::extended_policy(), v8::internal::SourcePosition::ExternalFileId(), v8::internal::SourcePosition::ExternalLine(), v8::internal::ObjectLiteralBoilerplateBuilder::fast_elements(), v8::internal::compiler::CallParameters::feedback_relation(), v8::internal::PropertyDetails::field_index(), v8::internal::FieldIndex::first_inobject_property_offset(), v8::internal::compiler::UnallocatedOperand::fixed_register_index(), v8::internal::compiler::Instruction::flags_condition(), v8::internal::compiler::Instruction::flags_mode(), v8::internal::FieldIndex::ForSmiLoadHandler(), v8::internal::HeapGraphEdge::from_index(), v8::internal::BigInt::FromSerializedDigits(), v8::internal::FeedbackNexus::GetCallCount(), v8::internal::FeedbackNexus::GetCallFeedbackContent(), v8::internal::AllocationSite::GetElementsKind(), cppgc::internal::HeapObjectHeader::GetGCInfoIndex(), v8::internal::LoadHandler::GetHandlerKind(), v8::internal::LoadHandler::GetKeyedAccessLoadMode(), v8::internal::StoreHandler::GetKeyedAccessStoreMode(), v8::internal::interpreter::StoreLookupSlotFlags::GetLanguageMode(), v8::internal::HandlerTable::GetRangeHandler(), v8::internal::HandlerTable::GetRangePrediction(), v8::internal::Name::GetRawHashFromForwardingTable(), v8::internal::HandlerTable::GetReturnHandler(), v8::internal::compiler::UnallocatedOperand::GetSecondaryStorage(), v8::internal::FeedbackNexus::GetSpeculationMode(), v8::internal::HandlerTable::HandlerWasUsed(), v8::internal::MaglevSafepointTable::has_deopt_data(), v8::internal::SafepointTable::has_deopt_data(), v8::internal::FunctionLiteral::has_duplicate_parameters(), v8::internal::ObjectLiteralBoilerplateBuilder::has_elements(), v8::internal::ObjectLiteralBoilerplateBuilder::has_null_prototype(), v8::internal::TracedNode::has_old_host(), v8::internal::ObjectLiteralBoilerplateBuilder::has_rest_property(), v8::internal::ClassLiteral::has_static_computed_names(), v8::internal::FunctionLiteral::has_static_private_methods_or_accessors(), v8::internal::compiler::Instruction::HasCallDescriptorFlag(), v8::internal::AstRawString::Hash(), v8::internal::Name::hash(), v8::internal::PropertyArray::Hash(), v8::internal::StringTableKey::hash(), v8::internal::compiler::UnallocatedOperand::HasSecondaryStorage(), v8::internal::compiler::UsePosition::HintRegister(), v8::internal::VariableProxy::hole_check_mode(), v8::internal::wasm::ConstantExpression::i32_value(), v8::internal::Block::ignore_completion_value(), v8::internal::ExternalReferenceEncoder::Value::index(), v8::internal::RegExpInstruction::LookaroundPayload::index(), v8::internal::wasm::ConstantExpression::index(), v8::internal::SloppyBlockFunctionStatement::init(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationUnitForSingleFunction(), v8::internal::SourcePosition::InliningId(), v8::internal::maglev::NodeBase::input_count(), v8::internal::compiler::Node::input_edges(), v8::internal::compiler::UnallocatedOperand::input_index(), v8::internal::compiler::ArmOperandConverter::InputOffset(), v8::internal::compiler::ArmOperandConverter::InputOperand2(), v8::internal::compiler::Arm64OperandConverter::InputOperand2_32(), v8::internal::compiler::Arm64OperandConverter::InputOperand2_64(), v8::internal::compiler::Node::inputs(), v8::internal::compiler::Node::inputs_vector(), v8::internal::ClassLiteral::is_anonymous_expression(), v8::internal::VariableProxy::is_assigned(), v8::internal::SerializerReference::is_attached_reference(), v8::internal::SerializerReference::is_back_reference(), v8::internal::Block::is_breakable(), v8::internal::SerializerReference::is_builtin_reference(), v8::internal::maglev::OpProperties::is_call(), v8::internal::maglev::OpProperties::is_conversion(), v8::internal::maglev::OpProperties::is_deopt_checkpoint(), v8::internal::FieldIndex::is_double(), v8::internal::TracedNode::is_droppable(), v8::internal::ExternalReferenceEncoder::Value::is_from_api(), v8::internal::VariableProxy::is_home_object(), v8::internal::TracedNode::is_in_use(), v8::internal::GlobalHandles::Node::is_in_young_list(), v8::internal::TracedNode::is_in_young_list(), v8::internal::Block::is_initialization_block_for_parameters(), v8::internal::LiteralBoilerplateBuilder::is_initialized(), v8::internal::FieldIndex::is_inobject(), v8::internal::maglev::MergePointInterpreterFrameState::is_loop_with_peeled_iteration(), v8::internal::VariableProxy::is_new_target(), v8::internal::SerializerReference::is_off_heap_backing_store_reference(), v8::internal::Property::is_optional_chain_link(), v8::internal::Call::is_optional_chain_link(), v8::internal::Expression::is_parenthesized(), v8::internal::PreParserExpression::is_parenthesized(), v8::internal::RegExpInstruction::LookaroundPayload::is_positive(), v8::internal::Call::is_possibly_eval(), v8::internal::CountOperation::is_prefix(), v8::internal::Symbol::is_private_name(), v8::internal::WasmExportedFunctionData::is_promising(), v8::internal::wasm::ValueTypeBase::is_ref(), v8::internal::CodeEntry::is_ref_counted(), v8::internal::VariableProxy::is_removed_from_unresolved(), v8::internal::VariableProxy::is_resolved(), v8::internal::maglev::MergePointInterpreterFrameState::is_resumable_loop(), v8::internal::wasm::ValueTypeBase::is_shared(), v8::internal::CodeEntry::is_shared_cross_origin(), v8::internal::LiteralBoilerplateBuilder::is_simple(), v8::internal::Call::is_tagged_template(), v8::internal::wasm::ValueTypeBase::is_valid(), v8::internal::TracedNode::is_weak(), v8::internal::PreParserExpression::IsAssignment(), v8::internal::PreParserExpression::IsCall(), v8::internal::compiler::Instruction::IsDeoptimizeCall(), v8::internal::SourcePosition::IsExternal(), v8::internal::Name::IsExternalForwardingIndex(), v8::internal::PreParserExpression::IsFailureExpression(), v8::internal::Name::IsForwardingIndex(), v8::internal::Name::IsHash(), v8::internal::JSAtomicsMutex::IsHeld(), v8::internal::PreParserExpression::IsIdentifier(), v8::internal::PreParserExpression::IsImportCallExpression(), cppgc::internal::HeapObjectHeader::IsInConstruction(), v8::internal::Name::IsIntegerIndex(), v8::internal::Name::IsInternalizedForwardingIndex(), v8::internal::interpreter::StoreLookupSlotFlags::IsLookupHoistingMode(), cppgc::internal::HeapObjectHeader::IsMarked(), v8::internal::PreParserExpression::IsNull(), v8::internal::PreParserExpression::IsPattern(), v8::internal::PreParserExpression::IsPrivateReference(), v8::internal::PreParserExpression::IsProperty(), v8::internal::LinkageLocation::IsRegister(), v8::internal::PreParserExpression::IsStringLiteral(), v8::internal::PreParserExpression::IsSuperCallReference(), v8::internal::PreParserExpression::IsThis(), v8::internal::PreParserExpression::IsThisProperty(), v8::internal::compiler::Instruction::IsTrap(), v8::internal::compiler::UnallocatedOperand::IsUsedAtStart(), v8::internal::TypedSlotSet::IterateSlotsInRanges(), v8::internal::PropertyDetails::kind(), v8::internal::wasm::ConstantExpression::kind(), v8::internal::BigIntBase::length(), v8::internal::PropertyArray::length(), v8::internal::LoadHandler::LoadFullChain(), v8::internal::LoadHandler::LoadNonExistent(), v8::internal::PropertyDetails::location(), v8::internal::JSAtomicsMutex::LockJSMutexOrDequeueTimedOutWaiter(), v8::internal::JSAtomicsMutex::LockWaiterQueueOrJSMutex(), v8::internal::Assignment::lookup_hoisting_mode(), v8::internal::StringTable::LookupString(), v8::internal::JSAtomicsMutex::MaybeEnqueueNode(), v8::internal::AllocationSite::memento_found_count(), v8::internal::compiler::Instruction::memory_access_mode(), v8::internal::compiler::PPCOperandConverter::MemoryOperand(), v8::internal::compiler::S390OperandConverter::MemoryOperand(), v8::internal::compiler::Loong64OperandConverter::MemoryOperand(), v8::internal::compiler::MipsOperandConverter::MemoryOperand(), v8::internal::compiler::RiscvOperandConverter::MemoryOperand(), v8::internal::compiler::IA32OperandConverter::MemoryOperand(), v8::internal::compiler::X64OperandConverter::MemoryOperand(), v8::internal::compiler::Arm64OperandConverter::MemoryOperand(), v8::internal::compiler::Instruction::misc(), v8::internal::LiteralBoilerplateBuilder::needs_initial_allocation_site(), v8::internal::maglev::OpProperties::needs_register_snapshot(), v8::internal::compiler::ArmOperandConverter::NeonInputOperand(), v8::internal::Displacement::next(), v8::internal::compiler::IA32OperandConverter::NextMemoryOperand(), v8::internal::AstNode::node_type(), v8::internal::maglev::OpProperties::not_idempotent(), v8::internal::wasm::ValueTypeBase::nullability(), v8::internal::maglev::NodeBase::num_temporaries_needed(), v8::internal::JSSynchronizationPrimitive::NumWaitersForTesting(), v8::internal::SerializerReference::off_heap_backing_store_index(), v8::internal::FieldIndex::offset(), v8::internal::Suspend::on_abrupt_resume(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnFinishedUnits(), v8::internal::UnaryOperation::op(), v8::internal::BinaryOperation::op(), v8::internal::NaryOperation::op(), v8::internal::CountOperation::op(), v8::internal::CompareOperation::op(), v8::internal::Assignment::op(), v8::internal::maglev::NodeBase::opcode(), v8::internal::compiler::operator<<(), v8::internal::wasm::TurboshaftGraphBuildingInterface::OpIndexToSourcePosition(), v8::internal::SafepointTable::pc_size(), v8::internal::PropertyDetails::pointer(), v8::internal::FunctionLiteral::pretenure(), v8::internal::AllocationSite::pretenure_decision(), v8::internal::Displacement::print(), v8::internal::maglev::NodeBase::properties(), v8::internal::FieldIndex::property_index(), v8::internal::wasm::ValueTypeBase::raw_index(), v8::internal::compiler::anonymous_namespace{code-generator-arm64.cc}::RecordTrapInfoIfNeeded(), v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::RecordTrapInfoIfNeeded(), v8::internal::compiler::anonymous_namespace{code-generator-riscv.cc}::RecordTrapInfoIfNeeded(), v8::internal::wasm::ValueTypeBase::ref_type_kind(), v8::internal::SafepointTable::register_indexes_size(), v8::internal::PropertyDetails::representation(), v8::internal::FunctionLiteral::requires_instance_members_initializer(), v8::internal::compiler::UsePosition::ResolveHint(), v8::internal::maglev::LazyDeoptInfo::result_size(), v8::internal::FunctionLiteral::return_position(), v8::internal::JSProxy::Revoke(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::S390OpcodeOnlySupport12BitDisp(), v8::internal::SourcePosition::ScriptOffset(), v8::internal::maglev::LazyDeoptInfo::set_deopting_call_return_pc(), v8::internal::compiler::UsePosition::set_type(), v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference(), v8::internal::JSSynchronizationPrimitive::SetWaiterQueueHead(), v8::internal::FunctionLiteral::should_parallel_compile(), v8::internal::compiler::ShouldAlignForJCCErratum(), v8::internal::compiler::CodeGenerator::ShouldApplyOffsetToStackCheck(), v8::internal::compiler::ShouldClearOutputRegisterBeforeInstruction(), v8::internal::BigIntBase::sign(), v8::internal::compiler::CallParameters::speculation_mode(), v8::internal::CallBase::spread_position(), v8::internal::wasm::ValueTypeBase::standard_type(), v8::internal::compiler::ConstructForwardVarargsParameters::start_index(), v8::internal::compiler::CallForwardVarargsParameters::start_index(), v8::internal::GlobalHandles::Node::state(), v8::internal::StringBuilderConcatHelper(), v8::internal::StringBuilderConcatLength(), v8::internal::FunctionLiteral::syntax_kind(), v8::internal::SafepointTable::tagged_slots_bytes(), v8::internal::wasm::value_type_impl::ToZeroBasedIndex(), v8::internal::Name::TryGetHash(), v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting(), v8::internal::ReturnStatement::type(), v8::internal::Literal::type(), v8::internal::Displacement::type(), v8::internal::HeapGraphEdge::type(), v8::internal::RegExpInstruction::LookaroundPayload::type(), v8::internal::wasm::ConstantExpression::type(), v8::internal::wasm::ValueTypeBase::type_kind(), unibrow::Predicate< T, size >::CacheEntry::value(), v8::internal::maglev::OpProperties::value_representation(), v8::internal::compiler::UnallocatedOperand::virtual_register(), v8::internal::compiler::ConstantOperand::virtual_register(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitShift(), v8::internal::detail::WaiterQueueLockGuard::WaiterQueueLockGuard(), v8::internal::GlobalHandles::Node::weakness_type(), v8::internal::wasm::ConstantExpression::wire_bytes_ref(), and v8::internal::detail::WaiterQueueLockGuard::~WaiterQueueLockGuard().
encode()
template<class T , int shift, int size, class U = uint32_t>
static constexpr U v8::base::BitField< T, shift, size, U >::encode (T value) [inline], [static], [constexpr]
Definition at line 55 of file bit-field.h.
                                     {
    DCHECK(is_valid(value));
    return static_cast<U>(value) << kShift;
  }
References DCHECK, v8::base::BitField< T, shift, size, U >::is_valid(), v8::base::BitField< T, shift, size, U >::kShift, v8::base::internal::U, and v8::internal::value.
Referenced by v8::internal::ReplacementStringBuilder::AddSubjectSlice(), v8::internal::maglev::NodeBase::Allocate(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::AllocateBigInt(), v8::internal::compiler::Node::AppendInput(), v8::internal::PreParserExpression::ArrayLiteral(), v8::internal::PreParserExpression::Assignment(), v8::internal::Assignment::Assignment(), v8::internal::CodeStubAssembler::BigIntFromInt32Pair(), v8::internal::CodeStubAssembler::BigIntFromInt64(), v8::internal::BinaryOperation::BinaryOperation(), v8::internal::BIT_FIELD_ACCESSORS(), v8::internal::Block::Block(), v8::internal::maglev::OpProperties::Call(), v8::internal::PreParserExpression::Call(), v8::internal::Call::Call(), v8::internal::CallBase::CallBase(), v8::internal::PreParserExpression::CallEval(), v8::internal::maglev::OpProperties::CanAllocate(), v8::internal::maglev::OpProperties::CanRead(), v8::internal::maglev::OpProperties::CanThrow(), v8::internal::maglev::OpProperties::CanWrite(), v8::internal::ClassLiteral::ClassLiteral(), v8::internal::CompareOperation::CompareOperation(), v8::internal::CallBase::ComputeSpreadPosition(), v8::internal::compiler::ConstantOperand::ConstantOperand(), v8::internal::maglev::OpProperties::ConversionNode(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertUntaggedToJSPrimitive(), v8::internal::CountOperation::CountOperation(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchSingleArgument(), v8::internal::Name::CreateExternalForwardingIndex(), v8::internal::Name::CreateHashFieldValue(), v8::internal::Name::CreateInternalizedForwardingIndex(), v8::internal::DataViewBuiltinsAssembler::DataViewEncodeBigIntBits(), v8::internal::PreParserExpression::Default(), v8::internal::maglev::OpProperties::DeoptCheckpoint(), v8::internal::maglev::OpProperties::EagerDeopt(), v8::internal::SafepointTableBuilder::Emit(), v8::internal::MaglevSafepointTableBuilder::Emit(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitAddBeforeS128LoadStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitBic(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitBranchOrDeoptimize(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::EmitLea(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::EmitLea(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitLoad(), v8::internal::compiler::InstructionSelector::EmitPrepareArguments(), v8::internal::HandlerTable::EmitReturnEntry(), v8::internal::compiler::EmitS128Load(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitStore(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::interpreter::CreateClosureFlags::Encode(), v8::internal::interpreter::CreateArrayLiteralFlags::Encode(), v8::internal::compiler::FlagsContinuation::Encode(), v8::internal::interpreter::CreateObjectLiteralFlags::Encode(), v8::internal::interpreter::StoreLookupSlotFlags::Encode(), v8::internal::ExternalReferenceEncoder::Value::Encode(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::EncodeCallDescriptorFlags(), cppgc::internal::HeapObjectHeader::EncodeSize(), v8::internal::maglev::OpProperties::ExternalReference(), v8::internal::compiler::Node::OutOfLineInputs::ExtractFrom(), v8::internal::PreParserExpression::Failure(), v8::internal::FieldIndex::FieldIndex(), v8::internal::maglev::OpProperties::Float64(), v8::internal::maglev::OpProperties::ForValueRepresentation(), v8::internal::PreParserExpression::FromIdentifier(), v8::internal::FunctionLiteral::FunctionLiteral(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateRightOperands(), v8::internal::BigInt::GetBitfieldForSerialization(), v8::internal::PropertyDetails::HasKindAndAttributes(), cppgc::internal::HeapObjectHeader::HeapObjectHeader(), v8::internal::maglev::OpProperties::HoleyFloat64(), v8::internal::wasm::ConstantExpression::I32Const(), v8::internal::PreParserExpression::ImportCall(), v8::internal::MutableBigInt::initialize_bitfield(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgress(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgressAfterDeserialization(), v8::internal::TypedSlots::Insert(), v8::internal::maglev::OpProperties::Int32(), v8::internal::maglev::OpProperties::IntPtr(), v8::internal::maglev::OpProperties::is_deferred_call(), v8::internal::maglev::OpProperties::LazyDeopt(), v8::internal::LinkageLocation::LinkageLocation(), v8::internal::LiteralBoilerplateBuilder::LiteralBoilerplateBuilder(), v8::internal::compiler::LiveRange::LiveRange(), v8::internal::LoadHandler::LoadAccessorFromPrototype(), v8::internal::LoadHandler::LoadApiGetter(), v8::internal::LoadHandler::LoadConstantFromPrototype(), v8::internal::LoadHandler::LoadElement(), v8::internal::LoadHandler::LoadField(), v8::internal::LoadHandler::LoadGeneric(), v8::internal::LoadHandler::LoadGlobal(), v8::internal::LoadHandler::LoadIndexedString(), v8::internal::LoadHandler::LoadInterceptor(), v8::internal::LoadHandler::LoadModuleExport(), v8::internal::LoadHandler::LoadNativeDataProperty(), v8::internal::LoadHandler::LoadNonExistent(), v8::internal::LoadHandler::LoadNormal(), v8::internal::LoadHandler::LoadProxy(), v8::internal::LoadHandler::LoadSlow(), v8::internal::LoadHandler::LoadWasmArrayElement(), v8::internal::LoadHandler::LoadWasmStructField(), cppgc::internal::HeapObjectHeader::MarkNonAtomic(), v8::internal::NaryOperation::NaryOperation(), v8::internal::maglev::OpProperties::NeedsRegisterSnapshot(), v8::internal::WasmExportedFunction::New(), v8::internal::compiler::Node::NewImpl(), v8::internal::Factory::NewJSProxy(), v8::internal::maglev::OpProperties::NotIdempotent(), v8::internal::PreParserExpression::ObjectLiteral(), v8::internal::ObjectLiteralBoilerplateBuilder::ObjectLiteralBoilerplateBuilder(), v8::internal::compiler::Instruction::OverwriteWithNop(), v8::internal::PreParserExpression::PrivateReference(), v8::internal::Isolate::PromiseHookStateUpdated(), v8::internal::PreParserExpression::Property(), v8::internal::Property::Property(), v8::internal::wasm::ConstantExpression::RefFunc(), v8::internal::wasm::ConstantExpression::RefNull(), v8::internal::ReturnStatement::ReturnStatement(), v8::internal::compiler::UsePosition::set_type(), v8::internal::HandlerTable::SetRangeHandler(), v8::internal::StoreHandler::StoreAccessorFromPrototype(), v8::internal::StoreHandler::StoreApiSetter(), v8::internal::StoreHandler::StoreField(), v8::internal::StoreHandler::StoreGeneric(), v8::internal::StoreHandler::StoreGlobalProxy(), v8::internal::StoreHandler::StoreInterceptor(), v8::internal::StoreHandler::StoreNativeDataProperty(), v8::internal::StoreHandler::StoreNormal(), v8::internal::StoreHandler::StoreOwnTransition(), v8::internal::StoreHandler::StoreProxy(), v8::internal::StoreHandler::StoreSlow(), v8::internal::StoreHandler::StoreTransition(), v8::internal::PreParserExpression::StringLiteral(), v8::internal::PreParserExpression::SuperCallReference(), v8::internal::Suspend::Suspend(), v8::internal::maglev::OpProperties::TaggedValue(), v8::internal::PreParserExpression::This(), v8::internal::PreParserExpression::ThisPrivateReference(), v8::internal::PreParserExpression::ThisProperty(), v8::internal::LoadHandler::TransitionAndLoadElement(), v8::internal::maglev::OpProperties::TrustedPointer(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitExtendingLoad(), v8::internal::compiler::TryEmitExtendingLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryEmitLoadForLoadWord64AndShiftRight(), cppgc::internal::HeapObjectHeader::TryMarkAtomic(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchAnyExtend(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchAnyShift(), v8::internal::compiler::TryMatchImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchImmediateOrShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShiftImmediate(), v8::internal::maglev::OpProperties::Uint32(), v8::internal::compiler::UnallocatedOperand::UnallocatedOperand(), v8::internal::UnaryOperation::UnaryOperation(), cppgc::internal::HeapObjectHeader::Unmark(), v8::base::BitField< T, shift, size, U >::update(), v8::internal::ArrayBufferExtension::UpdateAccountingLength(), v8::internal::AccessorAssembler::UpdateMayHaveInterestingProperty(), v8::internal::compiler::UsePosition::UsePosition(), v8::internal::VariableProxy::VariableProxy(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicBinop(), v8::internal::compiler::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicBinOp(), v8::internal::compiler::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), v8::internal::compiler::InstructionSelector::VisitCall(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitCompareWithMemoryOperand(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareWithMemoryOperand(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitLoadAndTest(), v8::internal::compiler::VisitLoadCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitOptimizedWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::InstructionSelector::VisitStackPointerGreaterThan(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon(), v8::internal::compiler::VisitStoreCommon(), v8::internal::compiler::InstructionSelector::VisitSwitch(), v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32EqualImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64EqualImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare(), v8::internal::compiler::InstructionSelector::VisitWordCompareZero(), v8::internal::wasm::TurboshaftGraphBuildingInterface::WasmPositionToOpIndex(), and v8::internal::wasm::ConstantExpression::WireBytes().
is_valid()
template<class T , int shift, int size, class U = uint32_t>
static constexpr bool v8::base::BitField< T, shift, size, U >::is_valid (T value) [inline], [static], [constexpr]
Definition at line 50 of file bit-field.h.
                                          {
    return (static_cast<U>(value) & ~kMax) == 0;
  }
References v8::base::BitField< T, shift, size, U >::kMax, v8::base::internal::U, and v8::internal::value.
Referenced by v8::internal::ReplacementStringBuilder::AddSubjectSlice(), v8::internal::compiler::Node::AppendInput(), v8::internal::SafepointTableBuilder::Emit(), v8::internal::MaglevSafepointTableBuilder::Emit(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::Node::OutOfLineInputs::ExtractFrom(), v8::internal::OrderedNameDictionary::Hash(), v8::internal::SmallOrderedNameDictionary::Hash(), v8::internal::PropertyArray::initialize_length(), v8::internal::PropertyDetails::IsValidIndex(), v8::internal::compiler::Node::NewImpl(), v8::internal::compiler::Node::Node(), v8::internal::ParserBase< Impl >::ParseLeftHandSideContinuation(), v8::internal::OrderedNameDictionary::SetHash(), v8::internal::SmallOrderedNameDictionary::SetHash(), v8::internal::anonymous_namespace{js-objects.cc}::SetHashAndUpdateProperties(), v8::internal::JSReceiver::SetIdentityHash(), v8::internal::StringTable::TryStringToIndexOrLookupExisting(), and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
update()
template<class T , int shift, int size, class U = uint32_t>
static constexpr U v8::base::BitField< T, shift, size, U >::update (U previous, T value) [inline], [static], [constexpr]
Definition at line 61 of file bit-field.h.
                                                              {
    return (previous & ~kMask) | encode(value);
  }
References v8::base::BitField< T, shift, size, U >::encode(), v8::base::BitField< T, shift, size, U >::kMask, and v8::internal::value.
Referenced by v8::internal::Call::adjust_eval_scope_info_index(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::AllocateBigInt(), v8::internal::compiler::Node::AppendInput(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ApplyCompilationHintToInitialProgress(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ApplyPgoInfoLate(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ApplyPgoInfoToInitialProgress(), v8::internal::wasm::HeapType::AsExact(), v8::internal::wasm::ValueType::AsExact(), v8::internal::wasm::CanonicalValueType::AsExact(), v8::internal::wasm::ValueType::AsNonShared(), v8::internal::wasm::ValueType::AsNullable(), v8::internal::wasm::ValueType::Canonicalize(), v8::internal::maglev::NodeBase::change_representation(), v8::internal::JSAtomicsMutex::CleanupMatchingAsyncWaiters(), v8::internal::VariableProxy::clear_is_assigned(), v8::internal::maglev::MergePointInterpreterFrameState::clear_is_loop(), v8::internal::Expression::clear_parenthesized(), v8::internal::PreParserExpression::clear_parenthesized(), v8::internal::compiler::InstructionOperand::GetCanonicalizedValue(), v8::internal::Literal::Literal(), v8::internal::JSAtomicsMutex::LockJSMutexOrDequeueTimedOutWaiter(), v8::internal::Expression::mark_parenthesized(), v8::internal::PreParserExpression::mark_parenthesized(), v8::internal::CodeEntry::mark_ref_counted(), v8::internal::VariableProxy::mark_removed_from_unresolved(), v8::internal::HandlerTable::MarkHandlerUsed(), v8::internal::JSAtomicsMutex::MaybeEnqueueNode(), v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop(), v8::internal::JSSynchronizationPrimitive::NumWaitersForTesting(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnFinishedUnits(), v8::internal::maglev::NodeBase::OverwriteWithIdentityTo(), v8::internal::wasm::ValueTypeBase::Populate(), v8::internal::PropertyDetails::PropertyDetails(), v8::internal::maglev::NodeBase::reduce_input_count(), v8::internal::wasm::CanonicalValueType::RefMaybeNull(), v8::internal::compiler::UsePosition::ResolveHint(), v8::internal::compiler::LiveRange::set_assigned_register(), v8::internal::LiteralBoilerplateBuilder::set_boilerplate_descriptor_kind(), v8::internal::PropertyDetails::set_cell_type(), v8::internal::AllocationSite::set_deopt_dependent_code(), v8::internal::maglev::LazyDeoptInfo::set_deopting_call_return_pc(), v8::internal::LiteralBoilerplateBuilder::set_depth(), v8::internal::maglev::NodeBase::set_double_temporaries_needed(), v8::internal::TracedNode::set_droppable(), v8::internal::ObjectLiteralBoilerplateBuilder::set_fast_elements(), v8::internal::ObjectLiteralBoilerplateBuilder::set_has_elements(), v8::internal::ObjectLiteralBoilerplateBuilder::set_has_null_protoype(), v8::internal::TracedNode::set_has_old_host(), v8::internal::FunctionLiteral::set_has_static_private_methods_or_accessors(), v8::internal::GlobalHandles::Node::set_in_young_list(), v8::internal::PropertyDetails::set_index(), v8::internal::VariableProxy::set_is_assigned(), v8::internal::VariableProxy::set_is_home_object(), v8::internal::TracedNode::set_is_in_use(), v8::internal::TracedNode::set_is_in_young_list(), v8::internal::VariableProxy::set_is_new_target(), v8::internal::Symbol::set_is_private_name(), v8::internal::VariableProxy::set_is_resolved(), v8::internal::maglev::MergePointInterpreterFrameState::set_is_resumable_loop(), v8::internal::LiteralBoilerplateBuilder::set_is_simple(), v8::internal::MutableBigInt::set_length(), v8::internal::Assignment::set_lookup_hoisting_mode(), v8::internal::AllocationSite::set_memento_found_count(), v8::internal::VariableProxy::set_needs_hole_check(), v8::internal::LiteralBoilerplateBuilder::set_needs_initial_allocation_site(), v8::internal::maglev::NodeBase::set_opcode(), v8::internal::FunctionLiteral::set_pretenure(), v8::internal::AllocationSite::set_pretenure_decision(), v8::internal::maglev::NodeBase::set_properties(), v8::internal::FunctionLiteral::set_requires_instance_members_initializer(), v8::internal::FunctionLiteral::set_should_parallel_compile(), v8::internal::MutableBigInt::set_sign(), v8::internal::GlobalHandles::Node::set_state(), v8::internal::maglev::NodeBase::set_temporaries_needed(), v8::internal::TracedNode::set_weak(), v8::internal::GlobalHandles::Node::set_weakness_type(), v8::internal::CodeEntry::SetBuiltinId(), v8::internal::AllocationSite::SetDoNotInlineCall(), v8::internal::AllocationSite::SetElementsKind(), v8::internal::SourcePosition::SetExternalFileId(), v8::internal::SourcePosition::SetExternalLine(), v8::internal::PropertyArray::SetHash(), v8::internal::compiler::UsePosition::SetHint(), v8::internal::SourcePosition::SetInliningId(), v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference(), v8::internal::SourcePosition::SetIsExternal(), v8::internal::SourcePosition::SetScriptOffset(), v8::internal::FeedbackNexus::SetSpeculationMode(), v8::internal::JSSynchronizationPrimitive::SetWaiterQueueHead(), v8::internal::SloppyBlockFunctionStatement::SloppyBlockFunctionStatement(), v8::internal::compiler::LiveRange::Spill(), v8::internal::compiler::Node::TrimInputCount(), v8::internal::JSAtomicsMutex::TryLockExplicit(), v8::internal::JSSynchronizationPrimitive::TryLockWaiterQueueExplicit(), v8::internal::compiler::UnallocatedOperand::UnallocatedOperand(), v8::internal::JSAtomicsMutex::UnlockSlowPath(), v8::internal::compiler::LiveRange::UnsetAssignedRegister(), v8::internal::compiler::LiveRange::Unspill(), v8::internal::VariableDeclaration::VariableDeclaration(), v8::internal::maglev::OpProperties::WithNewValueRepresentation(), v8::internal::maglev::OpProperties::WithoutDeopt(), and v8::internal::detail::WaiterQueueLockGuard::~WaiterQueueLockGuard().
Member Data Documentation
kLastUsedBit
template<class T , int shift, int size, class U = uint32_t>
constexpr int v8::base::BitField< T, shift, size, U >::kLastUsedBit = kShift + kSize - 1 [static], [constexpr]
Definition at line 42 of file bit-field.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::StringHash().
kMask
template<class T , int shift, int size, class U = uint32_t>
constexpr U v8::base::BitField< T, shift, size, U >::kMask = ((U{1} << kShift) << kSize) - (U{1} << kShift) [static], [constexpr]
Definition at line 41 of file bit-field.h.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), unibrow::Predicate< T, size >::CacheEntry::CacheEntry(), cppgc::internal::HeapObjectHeader::CheckApiConstants(), v8::internal::ArrayBufferExtension::ClearAccountingLength(), v8::base::BitField< T, shift, size, U >::decode(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::ExtendPropertiesBackingStore(), v8::internal::FieldIndex::GetFieldAccessStubKey(), v8::internal::WeakCollectionsBuiltinsAssembler::GetHash(), v8::internal::LinkageLocation::GetLocation(), v8::internal::BaseCollectionsAssembler::GotoIfCannotBeHeldWeakly(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase(), v8::internal::PropertyDetails::HasKindAndAttributes(), v8::internal::wasm::ValueTypeBase::is_valid(), v8::internal::CodeStubAssembler::IsAnyPromiseHookEnabled(), v8::internal::CodeStubAssembler::IsIsolatePromiseHookEnabledOrDebugIsActiveOrHasAsyncEventDelegate(), v8::internal::CodeStubAssembler::IsIsolatePromiseHookEnabledOrHasAsyncEventDelegate(), v8::internal::LinkageLocation::LinkageLocation(), v8::internal::LoadHandler::LoadNonExistent(), v8::internal::GlobalHandles::Node::Node(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ObjectIs(), v8::internal::Isolate::PromiseHookStateUpdated(), v8::internal::ArrayBufferExtension::SetOld(), v8::internal::ArrayBufferExtension::SetYoung(), v8::internal::maglev::MaglevAssembler::ToBoolean(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TruncateJSPrimitiveToUntagged(), cppgc::internal::HeapObjectHeader::Unmark(), v8::base::BitField< T, shift, size, U >::update(), and v8::internal::BigIntBuiltinsAssembler::WriteBigIntSignAndLength().
kMax
template<class T , int shift, int size, class U = uint32_t>
constexpr U v8::base::BitField< T, shift, size, U >::kMax = kNumValues - 1 [static], [constexpr]
Definition at line 44 of file bit-field.h.
Referenced by v8::internal::CodeStubAssembler::AddToDictionary(), v8::internal::compiler::Node::AppendInput(), v8::internal::detail::ConvertRawHashToUsableHash(), v8::internal::Name::CreateHashFieldValue(), v8::internal::JSReceiver::CreateIdentityHash(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::EncodeCallDescriptorFlags(), v8::internal::BigInt::GetBitfieldForSerialization(), v8::internal::StringHasher::GetTrivialHash(), v8::internal::CodeStubAssembler::InitializePropertyArrayLength(), v8::internal::maglev::NodeBase::input_count(), v8::base::BitField< T, shift, size, U >::is_valid(), v8::internal::Factory::NewSymbolInternal(), v8::internal::compiler::Node::Node(), v8::internal::AllocationSite::set_memento_found_count(), and cppgc::internal::HeapObjectHeader::SetAllocatedSize().
kNumValues
template<class T , int shift, int size, class U = uint32_t>
constexpr U v8::base::BitField< T, shift, size, U >::kNumValues = U{1} << kSize [static], [constexpr]
Definition at line 43 of file bit-field.h.
kShift
template<class T , int shift, int size, class U = uint32_t>
constexpr int v8::base::BitField< T, shift, size, U >::kShift = shift [static], [constexpr]
Definition at line 39 of file bit-field.h.
Referenced by v8::internal::CodeStubAssembler::AllocateBigInt(), v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertUntaggedToJSPrimitive(), v8::base::BitField< T, shift, size, U >::decode(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::ExtendPropertiesBackingStore(), v8::internal::compiler::UnallocatedOperand::fixed_slot_index(), v8::internal::LinkageLocation::GetLocation(), v8::internal::StringHasher::HashSequentialString(), v8::internal::CodeStubAssembler::IncrementCallCount(), v8::internal::CodeStubAssembler::InsertEntry(), v8::internal::LinkageLocation::LinkageLocation(), v8::internal::StringHasher::MakeArrayIndexHash(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ObjectIs(), v8::internal::TracedNode::Publish(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringHash(), v8::internal::compiler::UnallocatedOperand::UnallocatedOperand(), and v8::internal::BigIntBuiltinsAssembler::WriteBigIntSignAndLength().
kSize
template<class T , int shift, int size, class U = uint32_t>
constexpr int v8::base::BitField< T, shift, size, U >::kSize = size [static], [constexpr]
Definition at line 40 of file bit-field.h.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::EncodeCallDescriptorFlags(), and v8::internal::compiler::InstructionSelector::VisitCall().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/bit-field.h