v8::internal::compiler::turboshaft::ConstOrV< T, C > Class Template Reference
#include <index.h>
Public Types
using type = T
using constant_type = C
Public Member Functions
ConstOrV (constant_type value)
template<typename U >
ConstOrV (V< U > index) requires(std
bool is_constant () const
constant_type constant_value () const
V< type > value () const
template<typename U >
ConstOrV (U index) requires(std
Private Attributes
std::optional< constant_type > constant_value_
V< type > value_
Detailed Description
template<typename T, typename C = typename v_traits<T>::constexpr_type>
class v8::internal::compiler::turboshaft::ConstOrV< T, C >
Definition at line 730 of file index.h.
Member Typedef Documentation
constant_type
template<typename T , typename C = typename v_traits<T>::constexpr_type>
using v8::internal::compiler::turboshaft::ConstOrV< T, C >::constant_type = C
Definition at line 733 of file index.h.
type
template<typename T , typename C = typename v_traits<T>::constexpr_type>
using v8::internal::compiler::turboshaft::ConstOrV< T, C >::type = T
Definition at line 732 of file index.h.
Constructor & Destructor Documentation
ConstOrV() [1/3]
template<typename T , typename C = typename v_traits<T>::constexpr_type>
v8::internal::compiler::turboshaft::ConstOrV< T, C >::ConstOrV (constant_type value) [inline]
Definition at line 735 of file index.h.
      : constant_value_(value), value_() {}
ConstOrV() [2/3]
template<typename T , typename C = typename v_traits<T>::constexpr_type>
template<typename U >
v8::internal::compiler::turboshaft::ConstOrV< T, C >::ConstOrV (V< U > index) [inline]
Definition at line 741 of file index.h.
      : constant_value_(std::nullopt), value_(index) {}
ConstOrV() [3/3]
template<typename T , typename C = typename v_traits<T>::constexpr_type>
template<typename U >
v8::internal::compiler::turboshaft::ConstOrV< T, C >::ConstOrV (U index) [inline]
Definition at line 761 of file index.h.
      : constant_value_(), value_(index) {}
Member Function Documentation
constant_value()
template<typename T , typename C = typename v_traits<T>::constexpr_type>
constant_type v8::internal::compiler::turboshaft::ConstOrV< T, C >::constant_value () const [inline]
Definition at line 746 of file index.h.
                                       {
    DCHECK(is_constant());
    return *constant_value_;
  }
References v8::internal::compiler::turboshaft::ConstOrV< T, C >::constant_value_, v8::internal::DCHECK(), and v8::internal::compiler::turboshaft::ConstOrV< T, C >::is_constant().
Referenced by v8::internal::wasm::WasmGraphBuilderBase::BuildImportedFunctionTargetAndImplicitArg(), and v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::resolve().
is_constant()
template<typename T , typename C = typename v_traits<T>::constexpr_type>
bool v8::internal::compiler::turboshaft::ConstOrV< T, C >::is_constant () const [inline]
Definition at line 745 of file index.h.
{ return constant_value_.has_value(); }
References v8::internal::compiler::turboshaft::ConstOrV< T, C >::constant_value_.
Referenced by v8::internal::compiler::turboshaft::StringView::Begin(), v8::internal::wasm::WasmGraphBuilderBase::BuildImportedFunctionTargetAndImplicitArg(), v8::internal::compiler::turboshaft::ConstOrV< T, C >::constant_value(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::resolve(), and v8::internal::compiler::turboshaft::ConstOrV< T, C >::value().
value()
template<typename T , typename C = typename v_traits<T>::constexpr_type>
V<type> v8::internal::compiler::turboshaft::ConstOrV< T, C >::value () const [inline]
Definition at line 750 of file index.h.
                        {
    DCHECK(!is_constant());
    return value_;
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::ConstOrV< T, C >::is_constant(), and v8::internal::compiler::turboshaft::ConstOrV< T, C >::value_.
Referenced by v8::internal::compiler::turboshaft::StringView::Begin(), v8::internal::wasm::WasmGraphBuilderBase::BuildImportedFunctionTargetAndImplicitArg(), and v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::resolve().
Member Data Documentation
constant_value_
template<typename T , typename C = typename v_traits<T>::constexpr_type>
std::optional<constant_type> v8::internal::compiler::turboshaft::ConstOrV< T, C >::constant_value_ [private]
Definition at line 766 of file index.h.
Referenced by v8::internal::compiler::turboshaft::ConstOrV< T, C >::constant_value(), and v8::internal::compiler::turboshaft::ConstOrV< T, C >::is_constant().
value_
template<typename T , typename C = typename v_traits<T>::constexpr_type>
V<type> v8::internal::compiler::turboshaft::ConstOrV< T, C >::value_ [private]
Definition at line 767 of file index.h.
Referenced by v8::internal::compiler::turboshaft::ConstOrV< T, C >::value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/index.h