v8::AsyncHooksWrap Class Reference
#include <async-hooks-wrapper.h>
Public Member Functions
AsyncHooksWrap (Isolate *isolate)
void Enable ()
void Disable ()
bool IsEnabled () const
v8::Local< v8::Function > init_function () const
void set_init_function (v8::Local< v8::Function > value)
v8::Local< v8::Function > before_function () const
void set_before_function (v8::Local< v8::Function > value)
v8::Local< v8::Function > after_function () const
void set_after_function (v8::Local< v8::Function > value)
v8::Local< v8::Function > promiseResolve_function () const
void set_promiseResolve_function (v8::Local< v8::Function > value)
Static Public Attributes
static constexpr internal::ExternalPointerTag kManagedTag
Private Attributes
Isolate * isolate_
Persistent< v8::Function > init_function_
Persistent< v8::Function > before_function_
Persistent< v8::Function > after_function_
Persistent< v8::Function > promiseResolve_function_
bool enabled_
Detailed Description
Definition at line 29 of file async-hooks-wrapper.h.
Constructor & Destructor Documentation
AsyncHooksWrap()
v8::AsyncHooksWrap::AsyncHooksWrap (Isolate * isolate) [inline], [explicit]
Definition at line 34 of file async-hooks-wrapper.h.
      : isolate_(isolate), enabled_(false) {}
Member Function Documentation
after_function()
v8::Local< v8::Function > v8::AsyncHooksWrap::after_function () const [inline]
Definition at line 104 of file async-hooks-wrapper.cc.
                                                         {
  return after_function_.Get(isolate_);
}
References after_function_, v8::PersistentBase< T >::Get(), and isolate_.
Referenced by v8::AsyncHooks::PromiseHookDispatch().
before_function()
v8::Local< v8::Function > v8::AsyncHooksWrap::before_function () const [inline]
Definition at line 98 of file async-hooks-wrapper.cc.
                                                          {
  return before_function_.Get(isolate_);
}
References before_function_, v8::PersistentBase< T >::Get(), and isolate_.
Referenced by v8::AsyncHooks::PromiseHookDispatch().
Disable()
void v8::AsyncHooksWrap::Disable ()
Definition at line 90 of file async-hooks-wrapper.cc.
{ enabled_ = false; }
References enabled_.
Enable()
void v8::AsyncHooksWrap::Enable ()
Definition at line 88 of file async-hooks-wrapper.cc.
{ enabled_ = true; }
References enabled_.
init_function()
v8::Local< v8::Function > v8::AsyncHooksWrap::init_function () const [inline]
Definition at line 92 of file async-hooks-wrapper.cc.
                                                        {
  return init_function_.Get(isolate_);
}
References v8::PersistentBase< T >::Get(), init_function_, and isolate_.
Referenced by v8::AsyncHooks::PromiseHookDispatch().
IsEnabled()
bool v8::AsyncHooksWrap::IsEnabled () const [inline]
Definition at line 38 of file async-hooks-wrapper.h.
{ return enabled_; }
References enabled_.
Referenced by v8::AsyncHooks::PromiseHookDispatch().
promiseResolve_function()
v8::Local< v8::Function > v8::AsyncHooksWrap::promiseResolve_function () const [inline]
Definition at line 110 of file async-hooks-wrapper.cc.
                                                                  {
  return promiseResolve_function_.Get(isolate_);
}
References v8::PersistentBase< T >::Get(), isolate_, and promiseResolve_function_.
Referenced by v8::AsyncHooks::PromiseHookDispatch().
set_after_function()
void v8::AsyncHooksWrap::set_after_function (v8::Local< v8::Function > value) [inline]
Definition at line 107 of file async-hooks-wrapper.cc.
                                                                 {
  after_function_.Reset(isolate_, value);
}
References after_function_, isolate_, v8::PersistentBase< T >::Reset(), and v8::internal::value.
set_before_function()
void v8::AsyncHooksWrap::set_before_function (v8::Local< v8::Function > value) [inline]
Definition at line 101 of file async-hooks-wrapper.cc.
                                                                  {
  before_function_.Reset(isolate_, value);
}
References before_function_, isolate_, v8::PersistentBase< T >::Reset(), and v8::internal::value.
set_init_function()
void v8::AsyncHooksWrap::set_init_function (v8::Local< v8::Function > value) [inline]
Definition at line 95 of file async-hooks-wrapper.cc.
                                                                {
  init_function_.Reset(isolate_, value);
}
References init_function_, isolate_, v8::PersistentBase< T >::Reset(), and v8::internal::value.
set_promiseResolve_function()
void v8::AsyncHooksWrap::set_promiseResolve_function (v8::Local< v8::Function > value) [inline]
Definition at line 113 of file async-hooks-wrapper.cc.
                               {
  promiseResolve_function_.Reset(isolate_, value);
}
References isolate_, promiseResolve_function_, v8::PersistentBase< T >::Reset(), and v8::internal::value.
Member Data Documentation
after_function_
Persistent<v8::Function> v8::AsyncHooksWrap::after_function_ [private]
Definition at line 54 of file async-hooks-wrapper.h.
Referenced by after_function(), and set_after_function().
before_function_
Persistent<v8::Function> v8::AsyncHooksWrap::before_function_ [private]
Definition at line 53 of file async-hooks-wrapper.h.
Referenced by before_function(), and set_before_function().
enabled_
bool v8::AsyncHooksWrap::enabled_ [private]
Definition at line 57 of file async-hooks-wrapper.h.
Referenced by Disable(), Enable(), and IsEnabled().
init_function_
Persistent<v8::Function> v8::AsyncHooksWrap::init_function_ [private]
Definition at line 52 of file async-hooks-wrapper.h.
Referenced by init_function(), and set_init_function().
isolate_
Isolate* v8::AsyncHooksWrap::isolate_ [private]
Definition at line 50 of file async-hooks-wrapper.h.
Referenced by after_function(), before_function(), init_function(), promiseResolve_function(), set_after_function(), set_before_function(), set_init_function(), and set_promiseResolve_function().
kManagedTag
constexpr internal::ExternalPointerTag v8::AsyncHooksWrap::kManagedTag [static], [constexpr]
Initial value:
=
      internal::kGenericManagedTag
Definition at line 31 of file async-hooks-wrapper.h.
promiseResolve_function_
Persistent<v8::Function> v8::AsyncHooksWrap::promiseResolve_function_ [private]
Definition at line 55 of file async-hooks-wrapper.h.
Referenced by promiseResolve_function(), and set_promiseResolve_function().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/d8/async-hooks-wrapper.h
/mnt/V8SourceCode/src/d8/async-hooks-wrapper.cc