v8::internal::ZoneAllocator< T > Class Template Reference
#include <zone-allocator.h>
Public Types
using value_type = T
Public Member Functions
ZoneAllocator (Zone *zone)
template<typename U >
ZoneAllocator (const ZoneAllocator< U > &other) V8_NOEXCEPT
T * allocate (size_t length)
void deallocate (T *p, size_t length)
bool operator== (ZoneAllocator const &other) const
bool operator!= (ZoneAllocator const &other) const
Zone * zone () const
Private Attributes
Zone * zone_
Detailed Description
template<typename T>
class v8::internal::ZoneAllocator< T >
Definition at line 16 of file zone-allocator.h.
Member Typedef Documentation
value_type
template<typename T >
using v8::internal::ZoneAllocator< T >::value_type = T
Definition at line 18 of file zone-allocator.h.
Constructor & Destructor Documentation
ZoneAllocator() [1/2]
template<typename T >
v8::internal::ZoneAllocator< T >::ZoneAllocator (Zone * zone) [inline], [explicit]
Definition at line 34 of file zone-allocator.h.
: zone_(zone) {}
ZoneAllocator() [2/2]
template<typename T >
template<typename U >
v8::internal::ZoneAllocator< T >::ZoneAllocator (const ZoneAllocator< U > & other) [inline]
Definition at line 36 of file zone-allocator.h.
      : ZoneAllocator<T>(other.zone()) {}
Member Function Documentation
allocate()
template<typename T >
T* v8::internal::ZoneAllocator< T >::allocate (size_t length) [inline]
Definition at line 39 of file zone-allocator.h.
{ return zone_->AllocateArray<T>(length); }
References v8::internal::Zone::AllocateArray(), v8::internal::length, and v8::internal::ZoneAllocator< T >::zone_.
Referenced by v8::internal::RecyclingZoneAllocator< T >::allocate().
deallocate()
template<typename T >
void v8::internal::ZoneAllocator< T >::deallocate (T * p, size_t length) [inline]
Definition at line 40 of file zone-allocator.h.
{ zone_->DeleteArray<T>(p, length); }
References v8::internal::Zone::DeleteArray(), v8::internal::length, and v8::internal::ZoneAllocator< T >::zone_.
operator!=()
template<typename T >
bool v8::internal::ZoneAllocator< T >::operator!= (ZoneAllocator< T > const & other) const [inline]
Definition at line 45 of file zone-allocator.h.
                                                    {
    return zone_ != other.zone_;
  }
References v8::internal::ZoneAllocator< T >::zone_.
operator==()
template<typename T >
bool v8::internal::ZoneAllocator< T >::operator== (ZoneAllocator< T > const & other) const [inline]
Definition at line 42 of file zone-allocator.h.
                                                    {
    return zone_ == other.zone_;
  }
References v8::internal::ZoneAllocator< T >::zone_.
zone()
template<typename T >
Zone* v8::internal::ZoneAllocator< T >::zone () const [inline]
Definition at line 49 of file zone-allocator.h.
{ return zone_; }
References v8::internal::ZoneAllocator< T >::zone_.
Member Data Documentation
zone_
template<typename T >
Zone* v8::internal::ZoneAllocator< T >::zone_ [private]
Definition at line 52 of file zone-allocator.h.
Referenced by v8::internal::ZoneAllocator< T >::allocate(), v8::internal::ZoneAllocator< T >::deallocate(), v8::internal::ZoneAllocator< T >::operator!=(), v8::internal::ZoneAllocator< T >::operator==(), and v8::internal::ZoneAllocator< T >::zone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/zone/zone-allocator.h