v8::base::ElapsedTimer Class Reference
#include <elapsed-timer.h>
Public Member Functions
ElapsedTimer ()
void Start ()
void Start (TimeTicks now)
void Stop ()
bool IsStarted () const
TimeDelta Restart ()
TimeDelta Restart (TimeTicks now)
void Pause ()
void Pause (TimeTicks now)
void Resume ()
void Resume (TimeTicks now)
TimeDelta Elapsed () const
TimeDelta Elapsed (TimeTicks now) const
bool HasExpired (TimeDelta time_delta) const
Private Member Functions
TimeDelta paused_elapsed ()
void set_paused_elapsed (TimeDelta delta)
TimeTicks start_ticks () const
void set_start_ticks (TimeTicks start_ticks)
Static Private Member Functions
static TimeTicks Now ()
Private Attributes
xx xx xx xx xx xx xx xx xx
union {
 TimeTicks start_ticks_
 TimeDelta paused_elapsed_
};
Detailed Description
Definition at line 14 of file elapsed-timer.h.
Constructor & Destructor Documentation
ElapsedTimer()
v8::base::ElapsedTimer::ElapsedTimer () [inline]
Definition at line 16 of file elapsed-timer.h.
: start_ticks_() {}
Member Function Documentation
Elapsed() [1/2]
TimeDelta v8::base::ElapsedTimer::Elapsed () const [inline]
Definition at line 99 of file elapsed-timer.h.
{ return Elapsed(Now()); }
References Elapsed(), and Now().
Referenced by v8::internal::wasm::InstanceBuilder::Build(), v8::internal::SnapshotCompression::Compress(), anonymous_namespace{mksnapshot.cc}::CreateSnapshotDataBlob(), v8::internal::wasm::DecodeWasmModule(), v8::internal::SnapshotCompression::Decompress(), v8::internal::CodeSerializer::Deserialize(), v8::internal::ContextDeserializer::DeserializeContext(), v8::internal::ReadOnlyDeserializer::DeserializeIntoIsolate(), v8::internal::StartupDeserializer::DeserializeIntoIsolate(), v8::internal::Deoptimizer::DoComputeOutputFrames(), Elapsed(), v8::internal::OptimizedCompilationJob::ElapsedTime(), v8::internal::DebugScope::ElapsedTimeSinceCreation(), v8::internal::anonymous_namespace{code-serializer.cc}::FinalizeDeserialization(), v8::internal::AsmJsCompilationJob::FinalizeJobImpl(), v8::internal::CodeSerializer::FinishOffThreadDeserialize(), v8::internal::HeapSnapshotGenerator::GenerateSnapshot(), v8::internal::Genesis::Genesis(), HasExpired(), v8::internal::Isolate::Init(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::ParserBase< Impl >::ParseArrowFunctionLiteral(), v8::internal::Parser::ParseFunction(), v8::internal::Parser::ParseFunctionLiteral(), v8::internal::PreParser::ParseFunctionLiteral(), v8::internal::Parser::ParseProgram(), Pause(), v8::internal::MemoryMeasurement::ReportResults(), v8::internal::RUNTIME_FUNCTION(), v8::internal::CodeSerializer::Serialize(), v8::internal::HeapSnapshotJSONSerializer::Serialize(), v8::internal::TimedHistogram::Stop(), v8::internal::BaseTimedHistogramScope::StopInternal(), v8::internal::wasm::WasmExecutionTimer::StopInternal(), v8::internal::CollectionBarrier::StopTimeToCollectionTimer(), v8::internal::V8FileLogger::Time(), v8::internal::Snapshot::VerifyChecksum(), anonymous_namespace{mksnapshot.cc}::WarmUpSnapshotDataBlob(), and v8::base::ScopedTimer::~ScopedTimer().
Elapsed() [2/2]
TimeDelta v8::base::ElapsedTimer::Elapsed (TimeTicks now) const [inline]
Definition at line 101 of file elapsed-timer.h.
                                         {
    DCHECK(!now.IsNull());
    DCHECK(IsStarted());
    TimeDelta elapsed = now - start_ticks();
    DCHECK_GE(elapsed.InMicroseconds(), 0);
    return elapsed;
  }
References DCHECK, DCHECK_GE, v8::base::TimeDelta::InMicroseconds(), v8::base::time_internal::TimeBase< TimeClass >::IsNull(), IsStarted(), and start_ticks().
HasExpired()
bool v8::base::ElapsedTimer::HasExpired (TimeDelta time_delta) const [inline]
Definition at line 112 of file elapsed-timer.h.
                                              {
    DCHECK(IsStarted());
    return Elapsed() >= time_delta;
  }
References DCHECK, Elapsed(), and IsStarted().
IsStarted()
bool v8::base::ElapsedTimer::IsStarted () const [inline]
Definition at line 45 of file elapsed-timer.h.
                         {
    DCHECK(!paused_);
    DCHECK_NE(started_, start_ticks_.IsNull());
    return !start_ticks_.IsNull();
  }
References DCHECK, DCHECK_NE, v8::base::time_internal::TimeBase< TimeClass >::IsNull(), and start_ticks_.
Referenced by v8::internal::CollectionBarrier::AwaitCollectionBackground(), v8::internal::wasm::InstanceBuilder::Build(), v8::internal::CollectionBarrier::CancelCollectionAndResumeThreads(), Elapsed(), HasExpired(), v8::internal::CollectionBarrier::NotifyShutdownRequested(), Pause(), v8::internal::TimedHistogram::RecordAbandon(), Restart(), Resume(), v8::internal::CollectionBarrier::ResumeThreadsAwaitingCollection(), Start(), v8::internal::wasm::WasmExecutionTimer::StartInternal(), Stop(), v8::internal::wasm::WasmExecutionTimer::StopInternal(), v8::internal::CollectionBarrier::StopTimeToCollectionTimer(), v8::internal::wasm::WasmExecutionTimer::Terminate(), and v8::internal::CollectionBarrier::TryRequestGC().
Now()
static TimeTicks v8::base::ElapsedTimer::Now () [inline], [static], [private]
Definition at line 118 of file elapsed-timer.h.
                                   {
    TimeTicks now = TimeTicks::Now();
    DCHECK(!now.IsNull());
    return now;
  }
References DCHECK, v8::base::time_internal::TimeBase< TimeClass >::IsNull(), and v8::base::TimeTicks::Now().
Referenced by Elapsed(), Pause(), Restart(), Resume(), and Start().
Pause() [1/2]
void v8::base::ElapsedTimer::Pause () [inline]
Definition at line 72 of file elapsed-timer.h.
{ Pause(Now()); }
References Now(), and Pause().
Referenced by Pause().
Pause() [2/2]
void v8::base::ElapsedTimer::Pause (TimeTicks now) [inline]
Definition at line 74 of file elapsed-timer.h.
                            {
    TimeDelta elapsed = Elapsed(now);
    DCHECK(IsStarted());
#ifdef DEBUG
    paused_ = true;
#endif
    set_paused_elapsed(elapsed);
  }
References DCHECK, Elapsed(), IsStarted(), and set_paused_elapsed().
paused_elapsed()
TimeDelta v8::base::ElapsedTimer::paused_elapsed () [inline], [private]
Definition at line 124 of file elapsed-timer.h.
                             {
    // Only used started_ since paused_elapsed_ can be 0.
    DCHECK(paused_);
    DCHECK(started_);
    return paused_elapsed_;
  }
References DCHECK, and paused_elapsed_.
Referenced by Resume().
Restart() [1/2]
TimeDelta v8::base::ElapsedTimer::Restart () [inline]
Definition at line 60 of file elapsed-timer.h.
{ return Restart(Now()); }
References Now(), and Restart().
Referenced by Restart().
Restart() [2/2]
TimeDelta v8::base::ElapsedTimer::Restart (TimeTicks now) [inline]
Definition at line 62 of file elapsed-timer.h.
                                   {
    DCHECK(!now.IsNull());
    DCHECK(IsStarted());
    TimeDelta elapsed = now - start_ticks_;
    DCHECK_GE(elapsed.InMicroseconds(), 0);
    set_start_ticks(now);
    DCHECK(IsStarted());
    return elapsed;
  }
References DCHECK, DCHECK_GE, v8::base::TimeDelta::InMicroseconds(), v8::base::time_internal::TimeBase< TimeClass >::IsNull(), IsStarted(), set_start_ticks(), and start_ticks_.
Resume() [1/2]
void v8::base::ElapsedTimer::Resume () [inline]
Definition at line 83 of file elapsed-timer.h.
{ Resume(Now()); }
References Now(), and Resume().
Referenced by Resume().
Resume() [2/2]
void v8::base::ElapsedTimer::Resume (TimeTicks now) [inline]
Definition at line 85 of file elapsed-timer.h.
                             {
    DCHECK(!now.IsNull());
    DCHECK(started_);
    DCHECK(paused_);
    TimeDelta elapsed = paused_elapsed();
#ifdef DEBUG
    paused_ = false;
#endif
    set_start_ticks(now - elapsed);
    DCHECK(IsStarted());
  }
References DCHECK, v8::base::time_internal::TimeBase< TimeClass >::IsNull(), IsStarted(), paused_elapsed(), and set_start_ticks().
set_paused_elapsed()
void v8::base::ElapsedTimer::set_paused_elapsed (TimeDelta delta) [inline], [private]
Definition at line 131 of file elapsed-timer.h.
                                           {
    DCHECK(paused_);
    DCHECK(started_);
    paused_elapsed_ = delta;
  }
References DCHECK, and paused_elapsed_.
Referenced by Pause().
set_start_ticks()
void v8::base::ElapsedTimer::set_start_ticks (TimeTicks start_ticks) [inline], [private]
Definition at line 141 of file elapsed-timer.h.
                                              {
    DCHECK(!paused_);
    start_ticks_ = start_ticks;
  }
References DCHECK, start_ticks(), and start_ticks_.
Referenced by Restart(), Resume(), Start(), and Stop().
Start() [1/2]
void v8::base::ElapsedTimer::Start () [inline]
Definition at line 21 of file elapsed-timer.h.
{ Start(Now()); }
References Now(), and Start().
Referenced by v8::internal::compiler::PipelineStatisticsBase::CommonStats::Begin(), v8::internal::wasm::WasmExecutionTimer::BeginInterval(), v8::internal::wasm::InstanceBuilder::Build(), v8::internal::SnapshotCompression::Compress(), anonymous_namespace{mksnapshot.cc}::CreateSnapshotDataBlob(), v8::internal::DebugScope::DebugScope(), v8::internal::wasm::DecodeWasmModule(), v8::internal::SnapshotCompression::Decompress(), v8::internal::CodeSerializer::Deserialize(), v8::internal::ContextDeserializer::DeserializeContext(), v8::internal::ReadOnlyDeserializer::DeserializeIntoIsolate(), v8::internal::StartupDeserializer::DeserializeIntoIsolate(), v8::internal::Deoptimizer::DoComputeOutputFrames(), v8::internal::MemoryMeasurement::EnqueueRequest(), v8::internal::AsmJsCompilationJob::FinalizeJobImpl(), v8::internal::CodeSerializer::FinishOffThreadDeserialize(), v8::internal::HeapSnapshotGenerator::GenerateSnapshot(), v8::internal::Genesis::Genesis(), v8::internal::Isolate::Init(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::OptimizedCompilationJob::OptimizedCompilationJob(), v8::internal::ParserBase< Impl >::ParseArrowFunctionLiteral(), v8::internal::Parser::ParseFunction(), v8::internal::Parser::ParseFunctionLiteral(), v8::internal::PreParser::ParseFunctionLiteral(), v8::internal::Parser::ParseProgram(), v8::internal::RUNTIME_FUNCTION(), v8::base::ScopedTimer::ScopedTimer(), v8::internal::CodeSerializer::Serialize(), v8::internal::HeapSnapshotJSONSerializer::Serialize(), v8::internal::V8FileLogger::SetUp(), Start(), v8::internal::BaseTimedHistogramScope::StartInternal(), v8::internal::wasm::WasmExecutionTimer::StartInternal(), v8::internal::CollectionBarrier::TryRequestGC(), v8::internal::Snapshot::VerifyChecksum(), and anonymous_namespace{mksnapshot.cc}::WarmUpSnapshotDataBlob().
Start() [2/2]
void v8::base::ElapsedTimer::Start (TimeTicks now) [inline]
Definition at line 23 of file elapsed-timer.h.
                            {
    DCHECK(!now.IsNull());
    DCHECK(!IsStarted());
    set_start_ticks(now);
#ifdef DEBUG
    started_ = true;
#endif
    DCHECK(IsStarted());
  }
References DCHECK, v8::base::time_internal::TimeBase< TimeClass >::IsNull(), IsStarted(), and set_start_ticks().
start_ticks()
TimeTicks v8::base::ElapsedTimer::start_ticks () const [inline], [private]
Definition at line 137 of file elapsed-timer.h.
                                {
    DCHECK(!paused_);
    return start_ticks_;
  }
References DCHECK, and start_ticks_.
Referenced by Elapsed(), and set_start_ticks().
Stop()
void v8::base::ElapsedTimer::Stop () [inline]
Definition at line 35 of file elapsed-timer.h.
              {
    DCHECK(IsStarted());
    set_start_ticks(TimeTicks());
#ifdef DEBUG
    started_ = false;
#endif
    DCHECK(!IsStarted());
  }
References DCHECK, IsStarted(), and set_start_ticks().
Referenced by v8::internal::CollectionBarrier::CancelCollectionAndResumeThreads(), anonymous_namespace{mksnapshot.cc}::CreateSnapshotDataBlob(), v8::internal::wasm::DecodeWasmModule(), v8::internal::HeapSnapshotGenerator::GenerateSnapshot(), v8::internal::CollectionBarrier::NotifyShutdownRequested(), v8::internal::TimedHistogram::RecordAbandon(), v8::internal::HeapSnapshotJSONSerializer::Serialize(), v8::internal::TimedHistogram::Stop(), v8::internal::BaseTimedHistogramScope::StopInternal(), v8::internal::wasm::WasmExecutionTimer::StopInternal(), v8::internal::CollectionBarrier::StopTimeToCollectionTimer(), v8::internal::V8FileLogger::TearDownAndGetLogFile(), v8::internal::wasm::WasmExecutionTimer::Terminate(), and anonymous_namespace{mksnapshot.cc}::WarmUpSnapshotDataBlob().
Member Data Documentation
union { ... } [private]
paused_elapsed_
TimeDelta v8::base::ElapsedTimer::paused_elapsed_
Definition at line 148 of file elapsed-timer.h.
Referenced by paused_elapsed(), and set_paused_elapsed().
start_ticks_
TimeTicks v8::base::ElapsedTimer::start_ticks_
Definition at line 147 of file elapsed-timer.h.
Referenced by IsStarted(), Restart(), set_start_ticks(), and start_ticks().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/platform/elapsed-timer.h