v8::internal::ExecutionAccess Class Reference
#include <isolate.h>
Public Member Functions
ExecutionAccess (Isolate *isolate)
~ExecutionAccess ()
Static Public Member Functions
static void Lock (Isolate *isolate)
static void Unlock (Isolate *isolate)
static bool TryLock (Isolate *isolate)
Private Attributes
Isolate * isolate_
Detailed Description
Definition at line 3054 of file isolate.h.
Constructor & Destructor Documentation
ExecutionAccess()
v8::internal::ExecutionAccess::ExecutionAccess (Isolate * isolate) [inline], [explicit]
Definition at line 3056 of file isolate.h.
                                             : isolate_(isolate) {
    Lock(isolate);
  }
References Lock().
 ExecutionAccess()
v8::internal::ExecutionAccess::~ExecutionAccess () [inline]
Definition at line 3059 of file isolate.h.
{ Unlock(isolate_); }
References isolate_, and Unlock().
Member Function Documentation
Lock()
static void v8::internal::ExecutionAccess::Lock (Isolate * isolate) [inline], [static]
Definition at line 3061 of file isolate.h.
{ isolate->break_access()->Lock(); }
References v8::internal::Isolate::break_access(), and v8::base::RecursiveMutex::Lock().
Referenced by ExecutionAccess().
TryLock()
static bool v8::internal::ExecutionAccess::TryLock (Isolate * isolate) [inline], [static]
Definition at line 3064 of file isolate.h.
                                        {
    return isolate->break_access()->TryLock();
  }
References v8::internal::Isolate::break_access(), and v8::base::RecursiveMutex::TryLock().
Unlock()
static void v8::internal::ExecutionAccess::Unlock (Isolate * isolate) [inline], [static]
Definition at line 3062 of file isolate.h.
{ isolate->break_access()->Unlock(); }
References v8::internal::Isolate::break_access(), and v8::base::RecursiveMutex::Unlock().
Referenced by ~ExecutionAccess().
Member Data Documentation
isolate_
Isolate* v8::internal::ExecutionAccess::isolate_ [private]
Definition at line 3069 of file isolate.h.
Referenced by ~ExecutionAccess().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/execution/isolate.h