v8::internal::MaglevSafepointEntry Class Reference
#include <maglev-safepoint-table.h>
Public Member Functions
MaglevSafepointEntry ()=default
MaglevSafepointEntry (int pc, int deopt_index, uint32_t num_tagged_slots, uint8_t num_extra_spill_slots, uint32_t tagged_register_indexes, int trampoline_pc)
bool operator== (const MaglevSafepointEntry &other) const
uint32_t num_tagged_slots () const
uint8_t num_extra_spill_slots () const
uint32_t tagged_register_indexes () const
uint32_t register_input_count () const
Static Public Attributes
static constexpr int kNoDeoptIndex = -1
static constexpr int kNoTrampolinePC = -1
Private Attributes
uint32_t num_tagged_slots_ = 0
uint8_t num_extra_spill_slots_ = 0
uint32_t tagged_register_indexes_ = 0
Additional Inherited Members
Detailed Description
Definition at line 22 of file maglev-safepoint-table.h.
Constructor & Destructor Documentation
MaglevSafepointEntry() [1/2]
v8::internal::MaglevSafepointEntry::MaglevSafepointEntry () [default]
MaglevSafepointEntry() [2/2]
v8::internal::MaglevSafepointEntry::MaglevSafepointEntry (int pc, int deopt_index, uint32_t num_tagged_slots, uint8_t num_extra_spill_slots, uint32_t tagged_register_indexes, int trampoline_pc) [inline]
Definition at line 29 of file maglev-safepoint-table.h.
      : SafepointEntryBase(pc, deopt_index, trampoline_pc),
        num_tagged_slots_(num_tagged_slots),
        num_extra_spill_slots_(num_extra_spill_slots),
        tagged_register_indexes_(tagged_register_indexes) {
    DCHECK(is_initialized());
  }
References v8::internal::DCHECK(), and v8::internal::SafepointEntryBase::is_initialized().
Member Function Documentation
num_extra_spill_slots()
uint8_t v8::internal::MaglevSafepointEntry::num_extra_spill_slots () const [inline]
Definition at line 47 of file maglev-safepoint-table.h.
{ return num_extra_spill_slots_; }
References num_extra_spill_slots_.
Referenced by v8::internal::Deoptimizer::ComputeInputFrameSize(), v8::internal::MaglevFrame::Iterate(), and v8::internal::MaglevSafepointTable::Print().
num_tagged_slots()
uint32_t v8::internal::MaglevSafepointEntry::num_tagged_slots () const [inline]
Definition at line 46 of file maglev-safepoint-table.h.
{ return num_tagged_slots_; }
References num_tagged_slots_.
Referenced by v8::internal::MaglevFrame::Iterate().
operator==()
bool v8::internal::MaglevSafepointEntry::operator== (const MaglevSafepointEntry & other) const [inline]
Definition at line 39 of file maglev-safepoint-table.h.
                                                           {
    return this->SafepointEntryBase::operator==(other) &&
           num_tagged_slots_ == other.num_tagged_slots_ &&
           num_extra_spill_slots_ == other.num_extra_spill_slots_ &&
           tagged_register_indexes_ == other.tagged_register_indexes_;
  }
References num_extra_spill_slots_, num_tagged_slots_, v8::internal::SafepointEntryBase::operator==(), and tagged_register_indexes_.
register_input_count()
uint32_t v8::internal::MaglevSafepointEntry::register_input_count () const [inline]
Definition at line 50 of file maglev-safepoint-table.h.
{ return tagged_register_indexes_; }
References tagged_register_indexes_.
tagged_register_indexes()
uint32_t v8::internal::MaglevSafepointEntry::tagged_register_indexes () const [inline]
Definition at line 48 of file maglev-safepoint-table.h.
{ return tagged_register_indexes_; }
References tagged_register_indexes_.
Referenced by v8::internal::MaglevFrame::Iterate(), and v8::internal::MaglevSafepointTable::Print().
Member Data Documentation
kNoDeoptIndex
constexpr int v8::internal::MaglevSafepointEntry::kNoDeoptIndex = -1 [static], [constexpr]
Definition at line 24 of file maglev-safepoint-table.h.
Referenced by v8::internal::MaglevSafepointTableBuilder::Emit(), v8::internal::MaglevSafepointTable::FindEntry(), v8::internal::MaglevSafepointTable::GetEntry(), and v8::internal::MaglevSafepointTableBuilder::UpdateDeoptimizationInfo().
kNoTrampolinePC
constexpr int v8::internal::MaglevSafepointEntry::kNoTrampolinePC = -1 [static], [constexpr]
Definition at line 25 of file maglev-safepoint-table.h.
Referenced by v8::internal::MaglevSafepointTableBuilder::Emit(), v8::internal::MaglevSafepointTable::FindEntry(), v8::internal::MaglevSafepointTable::GetEntry(), and v8::internal::MaglevSafepointTableBuilder::UpdateDeoptimizationInfo().
num_extra_spill_slots_
uint8_t v8::internal::MaglevSafepointEntry::num_extra_spill_slots_ = 0 [private]
Definition at line 54 of file maglev-safepoint-table.h.
Referenced by num_extra_spill_slots(), and operator==().
num_tagged_slots_
uint32_t v8::internal::MaglevSafepointEntry::num_tagged_slots_ = 0 [private]
Definition at line 53 of file maglev-safepoint-table.h.
Referenced by num_tagged_slots(), and operator==().
tagged_register_indexes_
uint32_t v8::internal::MaglevSafepointEntry::tagged_register_indexes_ = 0 [private]
Definition at line 55 of file maglev-safepoint-table.h.
Referenced by operator==(), register_input_count(), and tagged_register_indexes().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/maglev-safepoint-table.h