v8::internal::StubCache Class Reference
#include <stub-cache.h>
Classes
struct Entry
Public Types
enum Table { kPrimary
, kSecondary
 }
Public Member Functions
void Initialize ()
void Set (Tagged< Name > name, Tagged< Map > map, Tagged< MaybeObject > handler)
Tagged< MaybeObject > Get (Tagged< Name > name, Tagged< Map > map)
void Clear ()
SCTableReference key_reference (StubCache::Table table)
SCTableReference map_reference (StubCache::Table table)
SCTableReference value_reference (StubCache::Table table)
StubCache::Entry * first_entry (StubCache::Table table)
Isolate * isolate ()
StubCache (Isolate *isolate)
StubCache (const StubCache &)=delete
StubCache & operator= (const StubCache &)=delete
Static Public Member Functions
static int PrimaryOffsetForTesting (Tagged< Name > name, Tagged< Map > map)
static int SecondaryOffsetForTesting (Tagged< Name > name, Tagged< Map > map)
Static Public Attributes
static const int kCacheIndexShift = Name::HashBits::kShift
static const int kPrimaryTableBits = 11
static const int kPrimaryTableSize = (1 << kPrimaryTableBits)
static const int kSecondaryTableBits = 9
static const int kSecondaryTableSize = (1 << kSecondaryTableBits)
Static Private Member Functions
static int PrimaryOffset (Tagged< Name > name, Tagged< Map > map)
static int SecondaryOffset (Tagged< Name > name, Tagged< Map > map)
static Entry * entry (Entry *table, int offset)
Private Attributes
Entry primary_ [kPrimaryTableSize]
Entry secondary_ [kSecondaryTableSize]
Isolate * isolate_
Friends
class Isolate
class SCTableReference
Detailed Description
Definition at line 32 of file stub-cache.h.
Member Enumeration Documentation
Table
enum v8::internal::StubCache::Table
Enumerator
kPrimary
kSecondary
Definition at line 52 of file stub-cache.h.
{ kPrimary, kSecondary };
Constructor & Destructor Documentation
StubCache() [1/2]
v8::internal::StubCache::StubCache (Isolate * isolate) [explicit]
Definition at line 17 of file stub-cache.cc.
                                     : isolate_(isolate) {
  // Ensure the nullptr (aka Smi::zero()) which StubCache::Get() returns
  // when the entry is not found is not considered as a handler.
  DCHECK(!IC::IsHandler(Tagged<MaybeObject>()));
}
References v8::internal::DCHECK(), and v8::internal::IC::IsHandler().
StubCache() [2/2]
v8::internal::StubCache::StubCache (const StubCache &) [delete]
Member Function Documentation
Clear()
void v8::internal::StubCache::Clear ()
Definition at line 136 of file stub-cache.cc.
                      {
  Tagged<MaybeObject> empty = isolate_->builtins()->code(Builtin::kIllegal);
  Tagged<Name> empty_string = ReadOnlyRoots(isolate()).empty_string();
  for (int i = 0; i < kPrimaryTableSize; i++) {
    primary_[i].key = StrongTaggedValue(empty_string);
    primary_[i].map = StrongTaggedValue(Smi::zero());
    primary_[i].value = TaggedValue(empty);
  }
  for (int j = 0; j < kSecondaryTableSize; j++) {
    secondary_[j].key = StrongTaggedValue(empty_string);
    secondary_[j].map = StrongTaggedValue(Smi::zero());
    secondary_[j].value = TaggedValue(empty);
  }
}
References v8::internal::Isolate::builtins(), v8::internal::Builtins::code(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate(), isolate_, v8::internal::StubCache::Entry::key, kPrimaryTableSize, kSecondaryTableSize, v8::internal::StubCache::Entry::map, primary_, secondary_, v8::internal::StubCache::Entry::value, and v8::internal::Smi::zero().
Referenced by v8::internal::anonymous_namespace{heap.cc}::ClearStubCaches(), and Initialize().
entry()
static Entry* v8::internal::StubCache::entry (Entry * table, int offset) [inline], [static], [private]
Definition at line 124 of file stub-cache.h.
                                                {
    // The size of {Entry} must be a multiple of 1 << kCacheIndexShift.
    static_assert((sizeof(*table) >> kCacheIndexShift) << kCacheIndexShift ==
                  sizeof(*table));
    const int multiplier = sizeof(*table) >> kCacheIndexShift;
    return reinterpret_cast<Entry*>(reinterpret_cast<Address>(table) +
                                    offset * multiplier);
  }
Referenced by Get(), and Set().
first_entry()
StubCache::Entry* v8::internal::StubCache::first_entry (StubCache::Table table) [inline]
Definition at line 69 of file stub-cache.h.
                                                    {
    switch (table) {
      case StubCache::kPrimary:
        return StubCache::primary_;
      case StubCache::kSecondary:
        return StubCache::secondary_;
    }
    UNREACHABLE();
  }
References kPrimary, kSecondary, primary_, secondary_, and v8::internal::UNREACHABLE().
Get()
Tagged< MaybeObject > v8::internal::StubCache::Get (Tagged< Name > name, Tagged< Map > map)
Definition at line 121 of file stub-cache.cc.
                                                                     {
  DCHECK(CommonStubCacheChecks(this, name, map, Tagged<MaybeObject>()));
  int primary_offset = PrimaryOffset(name, map);
  Entry* primary = entry(primary_, primary_offset);
  if (primary->key == name && primary->map == map) {
    return TaggedValue::ToMaybeObject(isolate(), primary->value);
  }
  int secondary_offset = SecondaryOffset(name, map);
  Entry* secondary = entry(secondary_, secondary_offset);
  if (secondary->key == name && secondary->map == map) {
    return TaggedValue::ToMaybeObject(isolate(), secondary->value);
  }
  return Tagged<MaybeObject>();
}
References v8::internal::DCHECK(), entry(), isolate(), v8::internal::StubCache::Entry::key, v8::internal::StubCache::Entry::map, v8::internal::name, primary_, PrimaryOffset(), secondary_, SecondaryOffset(), v8::internal::TaggedValue::ToMaybeObject(), and v8::internal::StubCache::Entry::value.
Initialize()
void v8::internal::StubCache::Initialize ()
Definition at line 23 of file stub-cache.cc.
                           {
  DCHECK(base::bits::IsPowerOfTwo(kPrimaryTableSize));
  DCHECK(base::bits::IsPowerOfTwo(kSecondaryTableSize));
  Clear();
}
References Clear(), v8::internal::DCHECK(), v8::base::bits::IsPowerOfTwo(), kPrimaryTableSize, and kSecondaryTableSize.
Referenced by v8::internal::Isolate::Init().
isolate()
Isolate* v8::internal::StubCache::isolate () [inline]
Definition at line 79 of file stub-cache.h.
{ return isolate_; }
Referenced by Clear(), Get(), and Set().
key_reference()
SCTableReference v8::internal::StubCache::key_reference (StubCache::Table table) [inline]
Definition at line 54 of file stub-cache.h.
                                                       {
    return SCTableReference(
        reinterpret_cast<Address>(&first_entry(table)->key));
  }
References v8::internal::key.
Referenced by v8::internal::AccessorAssembler::TryProbeStubCacheTable().
map_reference()
SCTableReference v8::internal::StubCache::map_reference (StubCache::Table table) [inline]
Definition at line 59 of file stub-cache.h.
                                                       {
    return SCTableReference(
        reinterpret_cast<Address>(&first_entry(table)->map));
  }
operator=()
StubCache& v8::internal::StubCache::operator= (const StubCache &) [delete]
PrimaryOffset()
int v8::internal::StubCache::PrimaryOffset (Tagged< Name > name, Tagged< Map > map) [static], [private]
Definition at line 32 of file stub-cache.cc.
                                                               {
  // Compute the hash of the name (use entire hash field).
  uint32_t field = name->RawHash();
  DCHECK(Name::IsHashFieldComputed(field));
  // Using only the low bits in 64-bit mode is unlikely to increase the
  // risk of collision even if the heap is spread over an area larger than
  // 4Gb (and not at all if it isn't).
  uint32_t map_low32bits =
      static_cast<uint32_t>(map.ptr() ^ (map.ptr() >> kPrimaryTableBits));
  // Base the offset on a simple combination of name and map.
  uint32_t key = map_low32bits + field;
  return key & ((kPrimaryTableSize - 1) << kCacheIndexShift);
}
References v8::internal::DCHECK(), v8::internal::Name::IsHashFieldComputed(), kCacheIndexShift, v8::internal::key, kPrimaryTableBits, kPrimaryTableSize, v8::internal::name, and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by Get(), PrimaryOffsetForTesting(), and Set().
PrimaryOffsetForTesting()
int v8::internal::StubCache::PrimaryOffsetForTesting (Tagged< Name > name, Tagged< Map > map) [static]
Definition at line 58 of file stub-cache.cc.
                                                                         {
  return PrimaryOffset(name, map);
}
References v8::internal::name, and PrimaryOffset().
SecondaryOffset()
int v8::internal::StubCache::SecondaryOffset (Tagged< Name > name, Tagged< Map > map) [static], [private]
Definition at line 50 of file stub-cache.cc.
                                                                     {
  uint32_t name_low32bits = static_cast<uint32_t>(name.ptr());
  uint32_t map_low32bits = static_cast<uint32_t>(old_map.ptr());
  uint32_t key = (map_low32bits + name_low32bits);
  key = key + (key >> kSecondaryTableBits);
  return key & ((kSecondaryTableSize - 1) << kCacheIndexShift);
}
References kCacheIndexShift, v8::internal::key, kSecondaryTableBits, kSecondaryTableSize, v8::internal::name, and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by Get(), SecondaryOffsetForTesting(), and Set().
SecondaryOffsetForTesting()
int v8::internal::StubCache::SecondaryOffsetForTesting (Tagged< Name > name, Tagged< Map > map) [static]
Definition at line 62 of file stub-cache.cc.
                                                                           {
  return SecondaryOffset(name, map);
}
References v8::internal::name, and SecondaryOffset().
Set()
void v8::internal::StubCache::Set (Tagged< Name > name, Tagged< Map > map, Tagged< MaybeObject > handler)
Definition at line 89 of file stub-cache.cc.
                                                 {
  DCHECK(CommonStubCacheChecks(this, name, map, handler));
  // Compute the primary entry.
  int primary_offset = PrimaryOffset(name, map);
  Entry* primary = entry(primary_, primary_offset);
  Tagged<MaybeObject> old_handler(
      TaggedValue::ToMaybeObject(isolate(), primary->value));
  // If the primary entry has useful data in it, we retire it to the
  // secondary cache before overwriting it.
  // We need SafeEquals here while Builtin Code objects still live in the RO
  // space inside the sandbox.
  static_assert(!kAllCodeObjectsLiveInTrustedSpace);
  if (!old_handler.SafeEquals(isolate()->builtins()->code(Builtin::kIllegal)) &&
      !primary->map.IsSmi()) {
    Tagged<Map> old_map =
        Cast<Map>(StrongTaggedValue::ToObject(isolate(), primary->map));
    Tagged<Name> old_name =
        Cast<Name>(StrongTaggedValue::ToObject(isolate(), primary->key));
    int secondary_offset = SecondaryOffset(old_name, old_map);
    Entry* secondary = entry(secondary_, secondary_offset);
    *secondary = *primary;
  }
  // Update primary cache.
  primary->key = StrongTaggedValue(name);
  primary->value = TaggedValue(handler);
  primary->map = StrongTaggedValue(map);
  isolate()->counters()->megamorphic_stub_cache_updates()->Increment();
}
References code, v8::internal::Isolate::counters(), v8::internal::DCHECK(), entry(), isolate(), v8::internal::TaggedImpl< kRefType, StorageType >::IsSmi(), v8::internal::kAllCodeObjectsLiveInTrustedSpace, v8::internal::StubCache::Entry::key, v8::internal::StubCache::Entry::map, v8::internal::name, primary_, PrimaryOffset(), v8::internal::TaggedImpl< kRefType, StorageType >::SafeEquals(), secondary_, SecondaryOffset(), v8::internal::TaggedValue::ToMaybeObject(), v8::internal::StrongTaggedValue::ToObject(), and v8::internal::StubCache::Entry::value.
Referenced by v8::internal::IC::UpdateMegamorphicCache().
value_reference()
SCTableReference v8::internal::StubCache::value_reference (StubCache::Table table) [inline]
Definition at line 64 of file stub-cache.h.
                                                         {
    return SCTableReference(
        reinterpret_cast<Address>(&first_entry(table)->value));
  }
References v8::internal::value.
Friends And Related Function Documentation
Isolate
friend class Isolate [friend]
Definition at line 138 of file stub-cache.h.
SCTableReference
friend class SCTableReference [friend]
Definition at line 139 of file stub-cache.h.
Member Data Documentation
isolate_
Isolate* v8::internal::StubCache::isolate_ [private]
Definition at line 136 of file stub-cache.h.
Referenced by Clear().
kCacheIndexShift
const int v8::internal::StubCache::kCacheIndexShift = Name::HashBits::kShift [static]
Definition at line 86 of file stub-cache.h.
Referenced by PrimaryOffset(), SecondaryOffset(), v8::internal::AccessorAssembler::StubCachePrimaryOffset(), v8::internal::AccessorAssembler::StubCacheSecondaryOffset(), and v8::internal::AccessorAssembler::TryProbeStubCacheTable().
kPrimaryTableBits
const int v8::internal::StubCache::kPrimaryTableBits = 11 [static]
Definition at line 88 of file stub-cache.h.
Referenced by PrimaryOffset(), and v8::internal::AccessorAssembler::StubCachePrimaryOffset().
kPrimaryTableSize
const int v8::internal::StubCache::kPrimaryTableSize = (1 << kPrimaryTableBits) [static]
Definition at line 89 of file stub-cache.h.
Referenced by Clear(), Initialize(), PrimaryOffset(), and v8::internal::AccessorAssembler::StubCachePrimaryOffset().
kSecondaryTableBits
const int v8::internal::StubCache::kSecondaryTableBits = 9 [static]
Definition at line 90 of file stub-cache.h.
Referenced by SecondaryOffset(), and v8::internal::AccessorAssembler::StubCacheSecondaryOffset().
kSecondaryTableSize
const int v8::internal::StubCache::kSecondaryTableSize = (1 << kSecondaryTableBits) [static]
Definition at line 91 of file stub-cache.h.
Referenced by Clear(), Initialize(), SecondaryOffset(), and v8::internal::AccessorAssembler::StubCacheSecondaryOffset().
primary_
Entry v8::internal::StubCache::primary_[kPrimaryTableSize] [private]
Definition at line 134 of file stub-cache.h.
Referenced by Clear(), first_entry(), Get(), and Set().
secondary_
Entry v8::internal::StubCache::secondary_[kSecondaryTableSize] [private]
Definition at line 135 of file stub-cache.h.
Referenced by Clear(), first_entry(), Get(), and Set().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ic/stub-cache.h
/mnt/V8SourceCode/src/ic/stub-cache.cc