v8::internal::StringForwardingTable::Block Class Reference
#include <string-forwarding-table-inl.h>
Public Member Functions
Block (int capacity)
int capacity () const
void * operator new (size_t size, int capacity)
void * operator new (size_t size)=delete
void operator delete (void *data)
Record * record (int index)
const Record * record (int index) const
void UpdateAfterYoungEvacuation (PtrComprCageBase cage_base)
void UpdateAfterYoungEvacuation (PtrComprCageBase cage_base, int up_to_index)
void UpdateAfterFullEvacuation (PtrComprCageBase cage_base)
void UpdateAfterFullEvacuation (PtrComprCageBase cage_base, int up_to_index)
Static Public Member Functions
static std::unique_ptr< Block > New (int capacity)
Private Attributes
const int capacity_
Record elements_ [1]
Detailed Description
Definition at line 233 of file string-forwarding-table-inl.h.
Constructor & Destructor Documentation
Block()
v8::internal::StringForwardingTable::Block::Block (int capacity) [explicit]
Definition at line 19 of file string-forwarding-table.cc.
                                              : capacity_(capacity) {
  static_assert(unused_element().ptr() == 0);
  static_assert(kNullAddress == 0);
  static_assert(sizeof(Record) % sizeof(Address) == 0);
  static_assert(offsetof(Record, original_string_) == 0);
  constexpr int kRecordPointerSize = sizeof(Record) / sizeof(Address);
  MemsetPointer(reinterpret_cast<Address*>(&elements_[0]), 0,
                capacity_ * kRecordPointerSize);
}
References capacity_, elements_, v8::internal::kNullAddress, v8::internal::MemsetPointer(), and v8::internal::StringForwardingTable::unused_element().
Member Function Documentation
capacity()
int v8::internal::StringForwardingTable::Block::capacity () const [inline]
Definition at line 237 of file string-forwarding-table-inl.h.
{ return capacity_; }
Referenced by v8::internal::StringForwardingTable::IterateElements().
New()
std::unique_ptr< StringForwardingTable::Block > v8::internal::StringForwardingTable::Block::New (int capacity) [static]
Definition at line 57 of file string-forwarding-table.cc.
                  {
  return std::unique_ptr<Block>(new (capacity) Block(capacity));
}
Referenced by v8::internal::StringForwardingTable::EnsureCapacity(), and v8::internal::StringForwardingTable::InitializeBlockVector().
operator delete()
void v8::internal::StringForwardingTable::Block::operator delete (void * data)
Definition at line 53 of file string-forwarding-table.cc.
                                                            {
  AlignedFree(block);
}
References v8::internal::AlignedFree().
operator new() [1/2]
void* v8::internal::StringForwardingTable::Block::operator new (size_t size) [delete]
operator new() [2/2]
void * v8::internal::StringForwardingTable::Block::operator new (size_t size, int capacity)
Definition at line 29 of file string-forwarding-table.cc.
                                                                        {
  // Make sure the size given is the size of the Block structure.
  DCHECK_EQ(size, sizeof(StringForwardingTable::Block));
  // Make sure the Record class is trivial and has standard layout.
  static_assert(std::is_trivial_v<Record>);
  static_assert(std::is_standard_layout_v<Record>);
  // Make sure that the elements_ array is at the end of Block, with no padding,
  // so that subsequent elements can be accessed as offsets from elements_.
  static_assert(offsetof(StringForwardingTable::Block, elements_) ==
                sizeof(StringForwardingTable::Block) - sizeof(Record));
  // Make sure that elements_ is aligned when StringTable::Block is aligned.
  static_assert((alignof(StringForwardingTable::Block) +
                 offsetof(StringForwardingTable::Block, elements_)) %
                    kTaggedSize ==
                0);
  const size_t elements_size = capacity * sizeof(Record);
  // Storage for the first element is already supplied by elements_, so subtract
  // sizeof(Record).
  const size_t new_size = size + elements_size - sizeof(Record);
  DCHECK_LE(alignof(StringForwardingTable::Block), kSystemPointerSize);
  return AlignedAllocWithRetry(new_size, kSystemPointerSize);
}
References v8::internal::AlignedAllocWithRetry(), DCHECK_EQ, DCHECK_LE, v8::internal::kSystemPointerSize, v8::internal::kTaggedSize, and v8::internal::StringForwardingTable::size().
record() [1/2]
Record* v8::internal::StringForwardingTable::Block::record (int index) [inline]
Definition at line 242 of file string-forwarding-table-inl.h.
                            {
    DCHECK_LT(index, capacity());
    return &elements_[index];
  }
References DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::StringForwardingTable::AddExternalResourceAndHash(), v8::internal::StringForwardingTable::AddForwardString(), v8::internal::StringForwardingTable::GetExternalResource(), v8::internal::StringForwardingTable::GetRawHash(), v8::internal::StringForwardingTable::IterateElements(), and v8::internal::StringForwardingTable::UpdateForwardString().
record() [2/2]
const Record* v8::internal::StringForwardingTable::Block::record (int index) const [inline]
Definition at line 247 of file string-forwarding-table-inl.h.
                                        {
    DCHECK_LT(index, capacity());
    return &elements_[index];
  }
References DCHECK_LT, and v8::internal::index.
UpdateAfterFullEvacuation() [1/2]
void v8::internal::StringForwardingTable::Block::UpdateAfterFullEvacuation (PtrComprCageBase cage_base)
Definition at line 67 of file string-forwarding-table.cc.
                                {
  UpdateAfterFullEvacuation(cage_base, capacity_);
}
References v8::internal::StringForwardingTable::UpdateAfterFullEvacuation().
Referenced by v8::internal::StringForwardingTable::UpdateAfterFullEvacuation().
UpdateAfterFullEvacuation() [2/2]
void v8::internal::StringForwardingTable::Block::UpdateAfterFullEvacuation (PtrComprCageBase cage_base, int up_to_index)
Definition at line 120 of file string-forwarding-table.cc.
                                                 {
  for (int index = 0; index < up_to_index; ++index) {
    OffHeapObjectSlot original_slot = record(index)->OriginalStringSlot();
    Tagged<Object> original = original_slot.Acquire_Load(cage_base);
    if (!IsHeapObject(original)) continue;
    UpdateForwardedSlot(Cast<HeapObject>(original), original_slot);
    // During mark compact the forwarded (internalized) string may have been
    // evacuated.
    OffHeapObjectSlot forward_slot = record(index)->ForwardStringOrHashSlot();
    Tagged<Object> forward = forward_slot.Acquire_Load(cage_base);
    UpdateForwardedSlot(forward, forward_slot);
  }
}
References v8::internal::FullObjectSlot::Acquire_Load(), v8::internal::index, v8::internal::IsHeapObject(), and v8::internal::anonymous_namespace{string-forwarding-table.cc}::UpdateForwardedSlot().
UpdateAfterYoungEvacuation() [1/2]
void v8::internal::StringForwardingTable::Block::UpdateAfterYoungEvacuation (PtrComprCageBase cage_base)
Definition at line 62 of file string-forwarding-table.cc.
                                {
  UpdateAfterYoungEvacuation(cage_base, capacity_);
}
References v8::internal::StringForwardingTable::UpdateAfterYoungEvacuation().
Referenced by v8::internal::StringForwardingTable::UpdateAfterYoungEvacuation().
UpdateAfterYoungEvacuation() [2/2]
void v8::internal::StringForwardingTable::Block::UpdateAfterYoungEvacuation (PtrComprCageBase cage_base, int up_to_index)
Definition at line 91 of file string-forwarding-table.cc.
                                                 {
  for (int index = 0; index < up_to_index; ++index) {
    OffHeapObjectSlot slot = record(index)->OriginalStringSlot();
    Tagged<Object> original = slot.Acquire_Load(cage_base);
    if (!IsHeapObject(original)) continue;
    Tagged<HeapObject> object = Cast<HeapObject>(original);
    if (Heap::InFromPage(object)) {
      DCHECK(!HeapLayout::InWritableSharedSpace(object));
      const bool was_forwarded = UpdateForwardedSlot(object, slot);
      if (!was_forwarded) {
        // The object died in young space.
        slot.Release_Store(deleted_element());
      }
    } else {
      DCHECK(!object->map_word(kRelaxedLoad).IsForwardingAddress());
    }
// No need to update forwarded (internalized) strings as they are never
// in young space.
#ifdef DEBUG
    Tagged<Object> forward =
        record(index)->ForwardStringObjectOrHash(cage_base);
    if (IsHeapObject(forward)) {
      DCHECK(!HeapLayout::InYoungGeneration(Cast<HeapObject>(forward)));
    }
#endif
  }
}
References v8::internal::FullObjectSlot::Acquire_Load(), v8::internal::DCHECK(), v8::internal::StringForwardingTable::deleted_element(), v8::internal::index, v8::internal::Heap::InFromPage(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::IsHeapObject(), v8::kRelaxedLoad, v8::internal::FullObjectSlot::Release_Store(), and v8::internal::anonymous_namespace{string-forwarding-table.cc}::UpdateForwardedSlot().
Member Data Documentation
capacity_
const int v8::internal::StringForwardingTable::Block::capacity_ [private]
Definition at line 258 of file string-forwarding-table-inl.h.
Referenced by Block().
elements_
Record v8::internal::StringForwardingTable::Block::elements_[1] [private]
Definition at line 259 of file string-forwarding-table-inl.h.
Referenced by Block().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string-forwarding-table-inl.h
/mnt/V8SourceCode/src/objects/string-forwarding-table.cc