v8::internal::ReadOnlyPageObjectIterator Class Reference
#include <read-only-heap.h>
Public Member Functions
ReadOnlyPageObjectIterator (const ReadOnlyPageMetadata *page, SkipFreeSpaceOrFiller skip_free_space_or_filler=SkipFreeSpaceOrFiller::kYes)
ReadOnlyPageObjectIterator (const ReadOnlyPageMetadata *page, Address current_addr, SkipFreeSpaceOrFiller skip_free_space_or_filler=SkipFreeSpaceOrFiller::kYes)
Tagged< HeapObject > Next ()
Private Member Functions
void Reset (const ReadOnlyPageMetadata *page)
Private Attributes
const ReadOnlyPageMetadata * page_
Address current_addr_
const SkipFreeSpaceOrFiller skip_free_space_or_filler_
Friends
class ReadOnlyHeapObjectIterator
Detailed Description
Definition at line 137 of file read-only-heap.h.
Constructor & Destructor Documentation
ReadOnlyPageObjectIterator() [1/2]
v8::internal::ReadOnlyPageObjectIterator::ReadOnlyPageObjectIterator (const ReadOnlyPageMetadata * page, SkipFreeSpaceOrFiller skip_free_space_or_filler = SkipFreeSpaceOrFiller::kYes) [explicit]
Definition at line 251 of file read-only-heap.cc.
    : ReadOnlyPageObjectIterator(
          page, page == nullptr ? kNullAddress : page->GetAreaStart(),
          skip_free_space_or_filler) {}
ReadOnlyPageObjectIterator() [2/2]
v8::internal::ReadOnlyPageObjectIterator::ReadOnlyPageObjectIterator (const ReadOnlyPageMetadata * page, Address current_addr, SkipFreeSpaceOrFiller skip_free_space_or_filler = SkipFreeSpaceOrFiller::kYes)
Definition at line 258 of file read-only-heap.cc.
    : page_(page),
      current_addr_(current_addr),
      skip_free_space_or_filler_(skip_free_space_or_filler) {
  DCHECK_GE(current_addr, page->GetAreaStart());
  DCHECK_LT(current_addr, page->GetAreaStart() + page->area_size());
}
References v8::internal::MemoryChunkMetadata::area_size(), DCHECK_GE, DCHECK_LT, and v8::internal::ReadOnlyPageMetadata::GetAreaStart().
Member Function Documentation
Next()
Tagged< HeapObject > v8::internal::ReadOnlyPageObjectIterator::Next ()
Definition at line 268 of file read-only-heap.cc.
                                                    {
  if (page_ == nullptr) return HeapObject();
  Address end = page_->GetAreaStart() + page_->area_size();
  for (;;) {
    DCHECK_LE(current_addr_, end);
    if (current_addr_ == end) return HeapObject();
    Tagged<HeapObject> object = HeapObject::FromAddress(current_addr_);
    const int object_size = object->Size();
    current_addr_ += ALIGN_TO_ALLOCATION_ALIGNMENT(object_size);
    if (skip_free_space_or_filler_ == SkipFreeSpaceOrFiller::kYes &&
        IsFreeSpaceOrFiller(object)) {
      continue;
    }
    DCHECK_OBJECT_SIZE(object_size);
    return object;
  }
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::MemoryChunkMetadata::area_size(), current_addr_, DCHECK_LE, DCHECK_OBJECT_SIZE, v8::internal::compiler::end(), v8::internal::HeapObject::FromAddress(), v8::internal::ReadOnlyPageMetadata::GetAreaStart(), v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller(), v8::internal::kYes, page_, and skip_free_space_or_filler_.
Referenced by v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::EncodeTaggedSlots(), v8::internal::ReadOnlyHeapObjectIterator::Next(), and v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::PreProcessSegment().
Reset()
void v8::internal::ReadOnlyPageObjectIterator::Reset (const ReadOnlyPageMetadata * page) [private]
Definition at line 290 of file read-only-heap.cc.
                                                                       {
  page_ = page;
  current_addr_ = page->GetAreaStart();
}
References current_addr_, v8::internal::ReadOnlyPageMetadata::GetAreaStart(), and page_.
Referenced by v8::internal::ReadOnlyHeapObjectIterator::Next().
Friends And Related Function Documentation
ReadOnlyHeapObjectIterator
friend class ReadOnlyHeapObjectIterator [friend]
Definition at line 157 of file read-only-heap.h.
Member Data Documentation
current_addr_
Address v8::internal::ReadOnlyPageObjectIterator::current_addr_ [private]
Definition at line 154 of file read-only-heap.h.
Referenced by Next(), and Reset().
page_
const ReadOnlyPageMetadata* v8::internal::ReadOnlyPageObjectIterator::page_ [private]
Definition at line 153 of file read-only-heap.h.
Referenced by Next(), and Reset().
skip_free_space_or_filler_
const SkipFreeSpaceOrFiller v8::internal::ReadOnlyPageObjectIterator::skip_free_space_or_filler_ [private]
Definition at line 155 of file read-only-heap.h.
Referenced by Next().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/read-only-heap.h
/mnt/V8SourceCode/src/heap/read-only-heap.cc