v8::internal::maglev::MaglevCompiler Class Reference
#include <maglev-compiler.h>
Static Public Member Functions
static bool Compile (LocalIsolate *local_isolate, MaglevCompilationInfo *compilation_info)
static std::pair< MaybeHandle< Code >, BailoutReason > GenerateCode (Isolate *isolate, MaglevCompilationInfo *compilation_info)
Detailed Description
Definition at line 24 of file maglev-compiler.h.
Member Function Documentation
Compile()
bool v8::internal::maglev::MaglevCompiler::Compile (LocalIsolate * local_isolate, MaglevCompilationInfo * compilation_info) [static]
Definition at line 60 of file maglev-compiler.cc.
                                                                      {
  compiler::CurrentHeapBrokerScope current_broker(compilation_info->broker());
  Graph* graph = Graph::New(compilation_info);
  bool is_tracing_enabled = false;
  {
    UnparkedScopeIfOnBackground unparked_scope(local_isolate->heap());
    // Build graph.
    if (v8_flags.print_maglev_code || v8_flags.code_comments ||
        v8_flags.print_maglev_graph || v8_flags.print_maglev_graphs ||
        v8_flags.trace_maglev_graph_building ||
        v8_flags.trace_maglev_escape_analysis ||
        v8_flags.trace_maglev_phi_untagging || v8_flags.trace_maglev_regalloc ||
        v8_flags.trace_maglev_object_tracking) {
      is_tracing_enabled = compilation_info->toplevel_compilation_unit()
                               ->shared_function_info()
                               .object()
                               ->PassesFilter(v8_flags.maglev_print_filter);
      compilation_info->set_graph_labeller(new MaglevGraphLabeller());
    }
    if (is_tracing_enabled &&
        (v8_flags.print_maglev_code || v8_flags.print_maglev_graph ||
         v8_flags.print_maglev_graphs || v8_flags.trace_maglev_graph_building ||
         v8_flags.trace_maglev_phi_untagging ||
         v8_flags.trace_maglev_regalloc)) {
      MaglevCompilationUnit* top_level_unit =
          compilation_info->toplevel_compilation_unit();
      std::cout << "Compiling " << Brief(*compilation_info->toplevel_function())
                << " with Maglev\n";
      BytecodeArray::Disassemble(top_level_unit->bytecode().object(),
                                 std::cout);
      if (v8_flags.maglev_print_feedback) {
        Print(*top_level_unit->feedback().object(), std::cout);
      }
    }
    {
      TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                   "V8.Maglev.GraphBuilding");
      MaglevGraphBuilder graph_builder(
          local_isolate, compilation_info->toplevel_compilation_unit(), graph);
      graph_builder.Build();
      if (is_tracing_enabled && v8_flags.print_maglev_graphs) {
        std::cout << "\nAfter graph building" << std::endl;
        PrintGraph(std::cout, graph);
      }
    }
#ifdef DEBUG
    {
      GraphProcessor<MaglevGraphVerifier, /* visit_identity_nodes */ true>
          verifier(compilation_info);
      verifier.ProcessGraph(graph);
    }
#endif
    if (v8_flags.maglev_non_eager_inlining) {
      TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                   "V8.Maglev.Inlining");
      MaglevInliner inliner(graph);
      inliner.Run(is_tracing_enabled);
      // TODO(victorgomes): We need to remove all identity nodes before
      // PhiRepresentationSelector. Since Identity has different semantics
      // there. Check if we can remove the identity nodes during
      // PhiRepresentationSelector instead.
      GraphProcessor<SweepIdentityNodes, /* visit_identity_nodes */ true> sweep;
      sweep.ProcessGraph(graph);
    }
#ifdef DEBUG
    {
      GraphProcessor<MaglevGraphVerifier, /* visit_identity_nodes */ true>
          verifier(compilation_info);
      verifier.ProcessGraph(graph);
    }
#endif
    if (v8_flags.maglev_licm) {
      TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                   "V8.Maglev.LoopOptimizations");
      GraphProcessor<LoopOptimizationProcessor> loop_optimizations(
          compilation_info);
      loop_optimizations.ProcessGraph(graph);
      if (is_tracing_enabled && v8_flags.print_maglev_graphs) {
        std::cout << "\nAfter loop optimizations" << std::endl;
        PrintGraph(std::cout, graph);
      }
    }
#ifdef DEBUG
    {
      GraphProcessor<MaglevGraphVerifier, /* visit_identity_nodes */ true>
          verifier(compilation_info);
      verifier.ProcessGraph(graph);
    }
#endif
    if (v8_flags.maglev_untagged_phis) {
      TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                   "V8.Maglev.PhiUntagging");
      GraphProcessor<MaglevPhiRepresentationSelector> representation_selector(
          graph);
      representation_selector.ProcessGraph(graph);
      if (is_tracing_enabled && v8_flags.print_maglev_graphs) {
        std::cout << "\nAfter Phi untagging" << std::endl;
        PrintGraph(std::cout, graph);
      }
    }
  }
#ifdef DEBUG
  {
    GraphProcessor<MaglevGraphVerifier, /* visit_identity_nodes */ true>
        verifier(compilation_info);
    verifier.ProcessGraph(graph);
  }
#endif
  {
    // Post-hoc optimisation:
    // - Remove unreachable blocks
    // - Dead node marking
    // - Cleaning up identity nodes
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                 "V8.Maglev.DeadCodeMarking");
    if (graph->may_have_unreachable_blocks()) {
      graph->RemoveUnreachableBlocks();
    }
    GraphProcessor<AnyUseMarkingProcessor> processor;
    processor.ProcessGraph(graph);
  }
  if (is_tracing_enabled && v8_flags.print_maglev_graphs) {
    UnparkedScopeIfOnBackground unparked_scope(local_isolate->heap());
    std::cout << "After use marking" << std::endl;
    PrintGraph(std::cout, graph);
  }
#ifdef DEBUG
  {
    GraphProcessor<MaglevGraphVerifier, /* visit_identity_nodes */ true>
        verifier(compilation_info);
    verifier.ProcessGraph(graph);
  }
#endif
  {
    RegallocInfo regalloc_info;
    {
      // Preprocessing for register allocation and code gen:
      // - Remove dead nodes
      // - Collect input/output location constraints
      // - Find the maximum number of stack arguments passed to calls
      // - Collect use information, for SSA liveness and next-use distance.
      // - Mark
      TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                   "V8.Maglev.NodeProcessing");
      UnparkedScopeIfOnBackground unparked_scope(local_isolate->heap());
      GraphMultiProcessor<DeadNodeSweepingProcessor,
                          ValueLocationConstraintProcessor,
                          MaxCallDepthProcessor, LiveRangeAndNextUseProcessor,
                          DecompressedUseMarkingProcessor>
          processor(LiveRangeAndNextUseProcessor{compilation_info, graph,
                                                 &regalloc_info});
      processor.ProcessGraph(graph);
    }
    if (is_tracing_enabled && v8_flags.print_maglev_graphs) {
      UnparkedScopeIfOnBackground unparked_scope(local_isolate->heap());
      std::cout << "After register allocation pre-processing" << std::endl;
      PrintGraph(std::cout, graph);
    }
    {
      TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                   "V8.Maglev.RegisterAllocation");
      StraightForwardRegisterAllocator allocator(compilation_info, graph,
                                                 &regalloc_info);
    }
    if (is_tracing_enabled &&
        (v8_flags.print_maglev_graph || v8_flags.print_maglev_graphs)) {
      UnparkedScopeIfOnBackground unparked_scope(local_isolate->heap());
      std::cout << "After register allocation" << std::endl;
      PrintGraph(std::cout, graph);
    }
  }
  {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                 "V8.Maglev.CodeAssembly");
    UnparkedScopeIfOnBackground unparked_scope(local_isolate->heap());
    std::unique_ptr<MaglevCodeGenerator> code_generator =
        std::make_unique<MaglevCodeGenerator>(local_isolate, compilation_info,
                                              graph);
    bool success = code_generator->Assemble();
    if (!success) {
      return false;
    }
    // Stash the compiled code_generator on the compilation info.
    compilation_info->set_code_generator(std::move(code_generator));
  }
  return true;
}
References v8::internal::maglev::MaglevCompilationInfo::broker(), v8::internal::maglev::MaglevGraphBuilder::Build(), v8::internal::maglev::MaglevCompilationUnit::bytecode(), v8::internal::BytecodeArray::Disassemble(), v8::internal::maglev::MaglevCompilationUnit::feedback(), graph(), v8::internal::LocalIsolate::heap(), v8::internal::maglev::Graph::New(), v8::internal::compiler::FeedbackVectorRef::object(), v8::internal::compiler::BytecodeArrayRef::object(), v8::internal::compiler::SharedFunctionInfoRef::object(), v8::internal::Print(), v8::internal::maglev::PrintGraph(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph(), v8::internal::maglev::MaglevInliner::Run(), v8::internal::maglev::MaglevCompilationInfo::set_graph_labeller(), v8::internal::maglev::MaglevCompilationUnit::shared_function_info(), v8::internal::maglev::MaglevCompilationInfo::toplevel_compilation_unit(), v8::internal::maglev::MaglevCompilationInfo::toplevel_function(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and v8::internal::v8_flags.
GenerateCode()
std::pair< MaybeHandle< Code >, BailoutReason > v8::internal::maglev::MaglevCompiler::GenerateCode (Isolate * isolate, MaglevCompilationInfo * compilation_info) [static]
Definition at line 278 of file maglev-compiler.cc.
                                                               {
  compiler::CurrentHeapBrokerScope current_broker(compilation_info->broker());
  MaglevCodeGenerator* const code_generator =
      compilation_info->code_generator();
  DCHECK_NOT_NULL(code_generator);
  Handle<Code> code;
  {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                 "V8.Maglev.CodeGeneration");
    if (compilation_info->is_detached() ||
        !code_generator->Generate(isolate).ToHandle(&code)) {
      compilation_info->toplevel_compilation_unit()
          ->shared_function_info()
          .object()
          ->set_maglev_compilation_failed(true);
      return {{}, BailoutReason::kMaglevCodeGenerationFailed};
    }
  }
  {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                 "V8.Maglev.CommittingDependencies");
    if (!compilation_info->broker()->dependencies()->Commit(code)) {
      // Don't `set_maglev_compilation_failed` s.t. we may reattempt
      // compilation.
      // TODO(v8:7700): Make this more robust, i.e.: don't recompile endlessly.
      compilation_info->toplevel_function()->SetInterruptBudget(
          isolate, BudgetModification::kReduce);
      return {{}, BailoutReason::kBailedOutDueToDependencyChange};
    }
  }
  if (v8_flags.print_maglev_code) {
#ifdef OBJECT_PRINT
    std::unique_ptr<char[]> debug_name =
        compilation_info->toplevel_function()->shared()->DebugNameCStr();
    CodeTracer::StreamScope tracing_scope(isolate->GetCodeTracer());
    auto& os = tracing_scope.stream();
    code->CodePrint(os, debug_name.get());
#else
    Print(*code);
#endif
  }
  return {code, BailoutReason::kNoReason};
}
References v8::internal::maglev::MaglevCompilationInfo::broker(), code, v8::internal::compiler::CompilationDependencies::Commit(), DCHECK_NOT_NULL, v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::maglev::MaglevCodeGenerator::Generate(), v8::internal::Isolate::GetCodeTracer(), v8::internal::maglev::MaglevCompilationInfo::is_detached(), v8::internal::kReduce, v8::internal::compiler::SharedFunctionInfoRef::object(), v8::internal::Print(), v8::internal::maglev::MaglevCompilationUnit::shared_function_info(), v8::internal::CodeTracer::StreamScope::stream(), v8::internal::maglev::MaglevCompilationInfo::toplevel_compilation_unit(), v8::internal::maglev::MaglevCompilationInfo::toplevel_function(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and v8::internal::v8_flags.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-compiler.h
/mnt/V8SourceCode/src/maglev/maglev-compiler.cc