v8::internal::compiler::NodeOriginTable Class Reference
#include <node-origin-table.h>
Classes
class Decorator
class PhaseScope
class Scope
Public Member Functions
NodeOriginTable (TFGraph *graph)
NodeOriginTable (Zone *zone)
NodeOriginTable (const NodeOriginTable &)=delete
NodeOriginTable & operator= (const NodeOriginTable &)=delete
void AddDecorator ()
void RemoveDecorator ()
NodeOrigin GetNodeOrigin (Node *node) const
NodeOrigin GetNodeOrigin (NodeId id) const
void SetNodeOrigin (Node *node, const NodeOrigin &no)
void SetNodeOrigin (NodeId id, NodeId origin)
void SetNodeOrigin (NodeId id, NodeOrigin::OriginKind kind, NodeId origin)
void SetCurrentPosition (const NodeOrigin &no)
void SetCurrentBytecodePosition (int offset)
int GetCurrentBytecodePosition ()
void PrintJson (std::ostream &os) const
Static Private Member Functions
static NodeOrigin UnknownNodeOrigin (Zone *zone)
Private Attributes
TFGraph *const graph_
Decorator * decorator_
NodeOrigin current_origin_
int current_bytecode_position_
const char * current_phase_name_
NodeAuxData< NodeOrigin, UnknownNodeOrigin > table_
Detailed Description
Definition at line 66 of file node-origin-table.h.
Constructor & Destructor Documentation
NodeOriginTable() [1/3]
v8::internal::compiler::NodeOriginTable::NodeOriginTable (TFGraph * graph) [explicit]
Definition at line 43 of file node-origin-table.cc.
    : graph_(graph),
      decorator_(nullptr),
      current_origin_(NodeOrigin::Unknown()),
      current_bytecode_position_(0),
      current_phase_name_("unknown"),
      table_(graph->zone()) {}
NodeOriginTable() [2/3]
v8::internal::compiler::NodeOriginTable::NodeOriginTable (Zone * zone) [explicit]
Definition at line 51 of file node-origin-table.cc.
    : graph_(nullptr),
      decorator_(nullptr),
      current_origin_(NodeOrigin::Unknown()),
      current_bytecode_position_(0),
      current_phase_name_("unknown"),
      table_(zone) {}
NodeOriginTable() [3/3]
v8::internal::compiler::NodeOriginTable::NodeOriginTable (const NodeOriginTable &) [delete]
Member Function Documentation
AddDecorator()
void v8::internal::compiler::NodeOriginTable::AddDecorator ()
Definition at line 59 of file node-origin-table.cc.
                                   {
  DCHECK_NOT_NULL(graph_);
  DCHECK_NULL(decorator_);
  decorator_ = graph_->zone()->New<Decorator>(this);
  graph_->AddDecorator(decorator_);
}
References v8::internal::compiler::TFGraph::AddDecorator(), DCHECK_NOT_NULL, DCHECK_NULL, decorator_, graph_, v8::internal::Zone::New(), and v8::internal::compiler::TFGraph::zone().
Referenced by v8::internal::compiler::PipelineImpl::InitializeHeapBroker().
GetCurrentBytecodePosition()
int v8::internal::compiler::NodeOriginTable::GetCurrentBytecodePosition () [inline]
Definition at line 135 of file node-origin-table.h.
{ return current_bytecode_position_; }
Referenced by v8::internal::compiler::BytecodeGraphBuilder::BytecodePositionDecorator::Decorate().
GetNodeOrigin() [1/2]
NodeOrigin v8::internal::compiler::NodeOriginTable::GetNodeOrigin (Node * node) const
Definition at line 73 of file node-origin-table.cc.
                                                          {
  return table_.Get(node);
}
References table_.
Referenced by v8::internal::compiler::JSONGraphWriter::PrintNode(), and v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintNodes().
GetNodeOrigin() [2/2]
NodeOrigin v8::internal::compiler::NodeOriginTable::GetNodeOrigin (NodeId id) const
Definition at line 76 of file node-origin-table.cc.
                                                         {
  return table_.Get(id);
}
References table_.
operator=()
NodeOriginTable& v8::internal::compiler::NodeOriginTable::operator= (const NodeOriginTable &) [delete]
PrintJson()
void v8::internal::compiler::NodeOriginTable::PrintJson (std::ostream & os) const
Definition at line 91 of file node-origin-table.cc.
                                                    {
  os << "{";
  bool needs_comma = false;
  for (auto i : table_) {
    NodeOrigin no = i.second;
    if (no.IsKnown()) {
      if (needs_comma) {
        os << ",";
      }
      os << "\"" << i.first << "\""
         << ": ";
      no.PrintJson(os);
      needs_comma = true;
    }
  }
  os << "}";
}
References v8::internal::compiler::NodeOrigin::IsKnown(), v8::internal::compiler::NodeOrigin::PrintJson(), and table_.
RemoveDecorator()
void v8::internal::compiler::NodeOriginTable::RemoveDecorator ()
Definition at line 66 of file node-origin-table.cc.
                                      {
  DCHECK_NOT_NULL(graph_);
  DCHECK_NOT_NULL(decorator_);
  graph_->RemoveDecorator(decorator_);
  decorator_ = nullptr;
}
References DCHECK_NOT_NULL, decorator_, graph_, and v8::internal::compiler::TFGraph::RemoveDecorator().
Referenced by v8::internal::compiler::PipelineImpl::OptimizeTurbofanGraph().
SetCurrentBytecodePosition()
void v8::internal::compiler::NodeOriginTable::SetCurrentBytecodePosition (int offset) [inline]
Definition at line 131 of file node-origin-table.h.
                                              {
    current_bytecode_position_ = offset;
  }
SetCurrentPosition()
void v8::internal::compiler::NodeOriginTable::SetCurrentPosition (const NodeOrigin & no) [inline]
Definition at line 129 of file node-origin-table.h.
{ current_origin_ = no; }
SetNodeOrigin() [1/3]
void v8::internal::compiler::NodeOriginTable::SetNodeOrigin (Node * node, const NodeOrigin & no)
Definition at line 80 of file node-origin-table.cc.
                                                                    {
  table_.Set(node, no);
}
References table_.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::BytecodePositionDecorator::Decorate(), v8::internal::compiler::NodeOriginTable::Decorator::Decorate(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::Finalize().
SetNodeOrigin() [2/3]
void v8::internal::compiler::NodeOriginTable::SetNodeOrigin (NodeId id, NodeId origin)
Definition at line 83 of file node-origin-table.cc.
                                                            {
  table_.Set(id, NodeOrigin(current_phase_name_, "", origin));
}
References current_phase_name_, and table_.
SetNodeOrigin() [3/3]
void v8::internal::compiler::NodeOriginTable::SetNodeOrigin (NodeId id, NodeOrigin::OriginKind kind, NodeId origin)
Definition at line 86 of file node-origin-table.cc.
                                                   {
  table_.Set(id, NodeOrigin(current_phase_name_, "", kind, origin));
}
References current_phase_name_, and table_.
UnknownNodeOrigin()
static NodeOrigin v8::internal::compiler::NodeOriginTable::UnknownNodeOrigin (Zone * zone) [inline], [static], [private]
Definition at line 148 of file node-origin-table.h.
                                                  {
    return NodeOrigin::Unknown();
  }
References v8::internal::compiler::NodeOrigin::Unknown().
Member Data Documentation
current_bytecode_position_
int v8::internal::compiler::NodeOriginTable::current_bytecode_position_ [private]
Definition at line 145 of file node-origin-table.h.
current_origin_
NodeOrigin v8::internal::compiler::NodeOriginTable::current_origin_ [private]
Definition at line 144 of file node-origin-table.h.
Referenced by v8::internal::compiler::NodeOriginTable::Decorator::Decorate(), and v8::internal::compiler::NodeOriginTable::Scope::Scope().
current_phase_name_
const char* v8::internal::compiler::NodeOriginTable::current_phase_name_ [private]
Definition at line 147 of file node-origin-table.h.
Referenced by v8::internal::compiler::NodeOriginTable::PhaseScope::PhaseScope(), v8::internal::compiler::NodeOriginTable::Scope::Scope(), and SetNodeOrigin().
decorator_
Decorator* v8::internal::compiler::NodeOriginTable::decorator_ [private]
Definition at line 143 of file node-origin-table.h.
Referenced by AddDecorator(), and RemoveDecorator().
graph_
TFGraph* const v8::internal::compiler::NodeOriginTable::graph_ [private]
Definition at line 142 of file node-origin-table.h.
Referenced by AddDecorator(), and RemoveDecorator().
table_
NodeAuxData<NodeOrigin, UnknownNodeOrigin> v8::internal::compiler::NodeOriginTable::table_ [private]
Definition at line 151 of file node-origin-table.h.
Referenced by GetNodeOrigin(), PrintJson(), and SetNodeOrigin().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/node-origin-table.h
/mnt/V8SourceCode/src/compiler/node-origin-table.cc