cppgc::testing::OverrideEmbedderStackStateScope Class Reference
Overrides the state of the stack with the provided value.
#include <testing.h>
Public Member Functions
OverrideEmbedderStackStateScope (HeapHandle &heap_handle, EmbedderStackState state)
Constructs a scoped object that automatically enters and leaves the scope.
~OverrideEmbedderStackStateScope ()
OverrideEmbedderStackStateScope (const OverrideEmbedderStackStateScope &)=delete
OverrideEmbedderStackStateScope & operator= (const OverrideEmbedderStackStateScope &)=delete
Private Member Functions
CPPGC_STACK_ALLOCATED ()
Private Attributes
HeapHandle & heap_handle_
Detailed Description
Overrides the state of the stack with the provided value.
Parameters passed to explicit garbage collection calls still take precedence. Must not be nested.
This scope is useful to make the garbage collector consider the stack when tasks that invoke garbage collection (through the provided platform) contain interesting pointers on its stack.
Definition at line 30 of file testing.h.
Constructor & Destructor Documentation
OverrideEmbedderStackStateScope() [1/2]
cppgc::testing::OverrideEmbedderStackStateScope::OverrideEmbedderStackStateScope (HeapHandle & heap_handle, EmbedderStackState state) [explicit]
Constructs a scoped object that automatically enters and leaves the scope.
Parameters
heap_handle The corresponding heap.
Definition at line 13 of file testing.cc.
    : heap_handle_(heap_handle) {
  internal::HeapBase::From(heap_handle_).set_override_stack_state(state);
}
References cppgc::internal::HeapBase::From(), heap_handle_, and cppgc::internal::HeapBase::set_override_stack_state().
 OverrideEmbedderStackStateScope()
cppgc::testing::OverrideEmbedderStackStateScope::~OverrideEmbedderStackStateScope ()
Definition at line 19 of file testing.cc.
                                                                  {
  internal::HeapBase::From(heap_handle_).clear_overridden_stack_state();
}
References cppgc::internal::HeapBase::clear_overridden_stack_state(), cppgc::internal::HeapBase::From(), and heap_handle_.
OverrideEmbedderStackStateScope() [2/2]
cppgc::testing::OverrideEmbedderStackStateScope::OverrideEmbedderStackStateScope (const OverrideEmbedderStackStateScope &) [delete]
Member Function Documentation
CPPGC_STACK_ALLOCATED()
cppgc::testing::OverrideEmbedderStackStateScope::CPPGC_STACK_ALLOCATED () [private]
operator=()
OverrideEmbedderStackStateScope& cppgc::testing::OverrideEmbedderStackStateScope::operator= (const OverrideEmbedderStackStateScope &) [delete]
Member Data Documentation
heap_handle_
HeapHandle& cppgc::testing::OverrideEmbedderStackStateScope::heap_handle_ [private]
Definition at line 49 of file testing.h.
Referenced by OverrideEmbedderStackStateScope(), and ~OverrideEmbedderStackStateScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/testing.h
/mnt/V8SourceCode/src/heap/cppgc/testing.cc