v8::NumberObject Class Reference
A Number object (ECMA-262, 4.3.21).
#include <v8-primitive-object.h>
Public Member Functions
double ValueOf () const
Static Public Member Functions
static Local< Value > New (Isolate *isolate, double value)
static NumberObject * Cast (Value *value)
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
A Number object (ECMA-262, 4.3.21).
Definition at line 19 of file v8-primitive-object.h.
Member Function Documentation
Cast()
static NumberObject* v8::NumberObject::Cast (Value * value) [inline], [static]
Definition at line 25 of file v8-primitive-object.h.
                                                    {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<NumberObject*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::NumberObject::CheckCast (v8::Value * that) [static], [private]
Definition at line 4147 of file api.cc.
                                            {
  auto obj = *Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsNumberWrapper(obj), "v8::NumberObject::Cast()",
                  "Value is not a NumberObject");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
New()
Local< v8::Value > v8::NumberObject::New (Isolate * isolate, double value) [static]
Definition at line 7847 of file api.cc.
                                                                    {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_NumberObject_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::Object> number = i_isolate->factory()->NewNumber(value);
  i::DirectHandle<i::Object> obj =
      i::Object::ToObject(i_isolate, number).ToHandleChecked();
  return Utils::ToLocal(obj);
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewNumber(), v8::anonymous_namespace{api.cc}::ToObject(), and v8::internal::value.
ValueOf()
double v8::NumberObject::ValueOf () const
Definition at line 7857 of file api.cc.
                                     {
  auto obj = Utils::OpenDirectHandle(this);
  auto js_primitive_wrapper = i::Cast<i::JSPrimitiveWrapper>(obj);
  ApiRuntimeCallStatsScope rcs_scope(i::Isolate::Current(),
                                     RCCId::kAPI_NumberObject_NumberValue);
  return i::Object::NumberValue(
      i::Cast<i::Number>(js_primitive_wrapper->value()));
}
References v8::internal::Isolate::Current(), v8::internal::Object::NumberValue(), and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::append().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive-object.h
/mnt/V8SourceCode/src/api/api.cc