v8::internal::ReturnStatement Class Reference
#include <ast.h>
Public Types
enum Type { kNormal
, kAsyncReturn
, kSyntheticAsyncReturn
 }
Public Member Functions
Expression * expression () const
Type type () const
bool is_async_return () const
bool is_synthetic_async_return () const
int end_position () const
Static Public Attributes
static constexpr int kFunctionLiteralReturnPosition = -2
Private Types
using TypeField = JumpStatement::NextBitField< Type, 2 >
Private Member Functions
ReturnStatement (Expression *expression, Type type, int pos, int end_position)
Private Attributes
friend Zone
Expression * expression_
int end_position_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 641 of file ast.h.
Member Typedef Documentation
TypeField
using v8::internal::ReturnStatement::TypeField = JumpStatement::NextBitField<Type, 2> [private]
Definition at line 673 of file ast.h.
Member Enumeration Documentation
Type
enum v8::internal::ReturnStatement::Type
Enumerator
kNormal
kAsyncReturn
kSyntheticAsyncReturn
Definition at line 643 of file ast.h.
{ kNormal, kAsyncReturn, kSyntheticAsyncReturn };
Constructor & Destructor Documentation
ReturnStatement()
v8::internal::ReturnStatement::ReturnStatement (Expression * expression, Type type, int pos, int end_position) [inline], [private]
Definition at line 663 of file ast.h.
      : JumpStatement(pos, kReturnStatement),
        expression_(expression),
        end_position_(end_position) {
    bit_field_ |= TypeField::encode(type);
  }
References v8::internal::AstNode::bit_field_, v8::base::BitField< T, shift, size, U >::encode(), and type().
Member Function Documentation
end_position()
int v8::internal::ReturnStatement::end_position () const [inline]
Definition at line 657 of file ast.h.
{ return end_position_; }
References end_position_.
expression()
Expression* v8::internal::ReturnStatement::expression () const [inline]
Definition at line 644 of file ast.h.
{ return expression_; }
References expression_.
is_async_return()
bool v8::internal::ReturnStatement::is_async_return () const [inline]
Definition at line 647 of file ast.h.
{ return type() != kNormal; }
References kNormal, and type().
is_synthetic_async_return()
bool v8::internal::ReturnStatement::is_synthetic_async_return () const [inline]
Definition at line 648 of file ast.h.
                                         {
    return type() == kSyntheticAsyncReturn;
  }
References kSyntheticAsyncReturn, and type().
type()
Type v8::internal::ReturnStatement::type () const [inline]
Definition at line 646 of file ast.h.
{ return TypeField::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by is_async_return(), is_synthetic_async_return(), and ReturnStatement().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 660 of file ast.h.
Member Data Documentation
end_position_
int v8::internal::ReturnStatement::end_position_ [private]
Definition at line 671 of file ast.h.
Referenced by end_position().
expression_
Expression* v8::internal::ReturnStatement::expression_ [private]
Definition at line 670 of file ast.h.
Referenced by expression().
kFunctionLiteralReturnPosition
constexpr int v8::internal::ReturnStatement::kFunctionLiteralReturnPosition = -2 [static], [constexpr]
Definition at line 654 of file ast.h.
Zone
friend v8::internal::ReturnStatement::Zone [private]
Definition at line 661 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h