v8::internal::CompactionSpaceCollection Class Reference
#include <paged-spaces.h>
Public Member Functions
CompactionSpaceCollection (Heap *heap, CompactionSpaceKind compaction_space_kind)
CompactionSpace * Get (AllocationSpace space)
Private Attributes
CompactionSpace old_space_
CompactionSpace code_space_
std::optional< CompactionSpace > shared_space_
CompactionSpace trusted_space_
Additional Inherited Members
Detailed Description
Definition at line 412 of file paged-spaces.h.
Constructor & Destructor Documentation
CompactionSpaceCollection()
v8::internal::CompactionSpaceCollection::CompactionSpaceCollection (Heap * heap, CompactionSpaceKind compaction_space_kind) [explicit]
Definition at line 609 of file paged-spaces.cc.
    : old_space_(heap, OLD_SPACE, Executability::NOT_EXECUTABLE,
                 compaction_space_kind,
                 CompactionSpace::DestinationHeap::kSameHeap),
      code_space_(heap, CODE_SPACE, Executability::EXECUTABLE,
                  compaction_space_kind,
                  CompactionSpace::DestinationHeap::kSameHeap),
      trusted_space_(heap, TRUSTED_SPACE, Executability::NOT_EXECUTABLE,
                     compaction_space_kind,
                     CompactionSpace::DestinationHeap::kSameHeap) {
  if (heap->isolate()->has_shared_space()) {
    const CompactionSpace::DestinationHeap dest_heap =
        heap->isolate()->is_shared_space_isolate()
            ? CompactionSpace::DestinationHeap::kSameHeap
            : CompactionSpace::DestinationHeap::kSharedSpaceHeap;
    shared_space_.emplace(heap->isolate()->shared_space_isolate()->heap(),
                          SHARED_SPACE, Executability::NOT_EXECUTABLE,
                          compaction_space_kind, dest_heap);
  }
}
References v8::internal::CompactionSpace::kSameHeap, v8::internal::CompactionSpace::kSharedSpaceHeap, v8::internal::NOT_EXECUTABLE, v8::internal::SHARED_SPACE, and shared_space_.
Member Function Documentation
Get()
CompactionSpace* v8::internal::CompactionSpaceCollection::Get (AllocationSpace space) [inline]
Definition at line 417 of file paged-spaces.h.
                                              {
    switch (space) {
      case OLD_SPACE:
        return &old_space_;
      case CODE_SPACE:
        return &code_space_;
      case SHARED_SPACE:
        DCHECK(shared_space_);
        return &*shared_space_;
      case TRUSTED_SPACE:
        return &trusted_space_;
      default:
        UNREACHABLE();
    }
    UNREACHABLE();
  }
References v8::internal::CODE_SPACE, code_space_, v8::internal::DCHECK(), v8::internal::OLD_SPACE, old_space_, v8::internal::SHARED_SPACE, shared_space_, space, v8::internal::TRUSTED_SPACE, trusted_space_, and v8::internal::UNREACHABLE().
Referenced by v8::internal::EvacuationAllocator::EvacuationAllocator(), and v8::internal::EvacuationAllocator::Finalize().
Member Data Documentation
code_space_
CompactionSpace v8::internal::CompactionSpaceCollection::code_space_ [private]
Definition at line 436 of file paged-spaces.h.
Referenced by Get().
old_space_
CompactionSpace v8::internal::CompactionSpaceCollection::old_space_ [private]
Definition at line 435 of file paged-spaces.h.
Referenced by Get().
shared_space_
std::optional<CompactionSpace> v8::internal::CompactionSpaceCollection::shared_space_ [private]
Definition at line 437 of file paged-spaces.h.
Referenced by CompactionSpaceCollection(), and Get().
trusted_space_
CompactionSpace v8::internal::CompactionSpaceCollection::trusted_space_ [private]
Definition at line 438 of file paged-spaces.h.
Referenced by Get().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/paged-spaces.h
/mnt/V8SourceCode/src/heap/paged-spaces.cc