v8::internal::FeedbackVector Class Reference
#include <feedback-vector.h>
Public Member Functions
bool is_empty () const
void clear_invocation_count (RelaxedStoreTag tag)
int osr_urgency () const
void set_osr_urgency (int urgency)
void reset_osr_urgency ()
void RequestOsrAtNextOpportunity ()
bool maybe_has_maglev_osr_code () const
bool maybe_has_turbofan_osr_code () const
bool maybe_has_optimized_osr_code () const
void set_maybe_has_optimized_osr_code (bool value, CodeKind code_kind)
void reset_osr_state ()
bool log_next_execution () const
void set_log_next_execution (bool value=true)
Tagged< Code > optimized_code (IsolateForSandbox isolate) const
bool has_optimized_code () const
bool maybe_has_maglev_code () const
void set_maybe_has_maglev_code (bool value)
bool maybe_has_turbofan_code () const
void set_maybe_has_turbofan_code (bool value)
void SetOptimizedCode (IsolateForSandbox isolate, Tagged< Code > code)
void EvictOptimizedCodeMarkedForDeoptimization (Isolate *isolate, Tagged< SharedFunctionInfo > shared, const char *reason)
void ClearOptimizedCode ()
std::optional< Tagged< Code > > GetOptimizedOsrCode (Isolate *isolate, Handle< BytecodeArray > bytecode_array, FeedbackSlot slot)
void SetOptimizedOsrCode (Isolate *isolate, FeedbackSlot slot, Tagged< Code > code)
void RecomputeOptimizedOsrCodeFlags (Isolate *isolate, Handle< BytecodeArray > bytecode_array)
TieringState tiering_state () const
V8_EXPORT_PRIVATE void set_tiering_state (TieringState state)
void reset_tiering_state ()
bool osr_tiering_in_progress ()
void set_osr_tiering_in_progress (bool osr_in_progress)
bool interrupt_budget_reset_by_ic_change () const
void set_interrupt_budget_reset_by_ic_change (bool value)
bool was_once_deoptimized () const
void set_was_once_deoptimized ()
void reset_flags ()
Tagged< MaybeObject > SynchronizedGet (FeedbackSlot slot) const
void SynchronizedSet (FeedbackSlot slot, Tagged< MaybeObject > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< MaybeObject > Get (FeedbackSlot slot) const
Tagged< MaybeObject > Get (PtrComprCageBase cage_base, FeedbackSlot slot) const
DirectHandle< FeedbackCell > GetClosureFeedbackCell (Isolate *isolate, int index) const
Tagged< FeedbackCell > closure_feedback_cell (int index) const
MaybeObjectSlot slots_start ()
V8_EXPORT_PRIVATE FeedbackSlotKind GetKind (FeedbackSlot slot) const
V8_EXPORT_PRIVATE FeedbackSlotKind GetKind (FeedbackSlot slot, AcquireLoadTag tag) const
TypeofMode GetTypeofMode (FeedbackSlot slot) const
LanguageMode GetLanguageMode (FeedbackSlot slot) const
void FeedbackSlotPrint (std::ostream &os, FeedbackSlot slot)
bool ClearSlots (Isolate *isolate)
bool ClearAllSlotsForTesting (Isolate *isolate)
Static Public Member Functions
static constexpr uint32_t FlagMaskForNeedsProcessingCheckFrom (CodeKind code_kind)
static int GetIndex (FeedbackSlot slot)
static FeedbackSlot ToSlot (intptr_t index)
static V8_EXPORT_PRIVATE Handle< FeedbackVector > New (Isolate *isolate, DirectHandle< SharedFunctionInfo > shared, DirectHandle< ClosureFeedbackCellArray > closure_feedback_cell_array, DirectHandle< FeedbackCell > parent_feedback_cell, IsCompiledScope *is_compiled_scope)
static V8_EXPORT_PRIVATE Handle< FeedbackVector > NewForTesting (Isolate *isolate, const FeedbackVectorSpec *spec)
static V8_EXPORT_PRIVATE Handle< FeedbackVector > NewWithOneBinarySlotForTesting (Zone *zone, Isolate *isolate)
static V8_EXPORT_PRIVATE Handle< FeedbackVector > NewWithOneCompareSlotForTesting (Zone *zone, Isolate *isolate)
static DirectHandle< Symbol > UninitializedSentinel (Isolate *isolate)
static Handle< Symbol > MegamorphicSentinel (Isolate *isolate)
static DirectHandle< Symbol > MegaDOMSentinel (Isolate *isolate)
static Tagged< Symbol > RawUninitializedSentinel (Isolate *isolate)
static constexpr int OffsetOfElementAt (int index)
Static Public Attributes
static constexpr uint32_t kFlagsMaybeHasTurbofanCode
static constexpr uint32_t kFlagsMaybeHasMaglevCode
static constexpr uint32_t kFlagsHasAnyOptimizedCode
static constexpr uint32_t kFlagsTieringStateIsAnyRequested
static constexpr uint32_t kFlagsLogNextExecution
static constexpr uint8_t kInvocationCountBeforeStableDeoptSentinel = 0xff
static constexpr int kMaxOsrUrgency = 6
Private Member Functions
bool ClearSlots (Isolate *isolate, ClearBehavior behavior)
void Set (FeedbackSlot slot, Tagged< MaybeObject > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Static Private Member Functions
static void AddToVectorsForProfilingTools (Isolate *isolate, DirectHandle< FeedbackVector > vector)
Private Attributes
friend NexusConfig
Detailed Description
Definition at line 309 of file feedback-vector.h.
Member Function Documentation
AddToVectorsForProfilingTools()
void v8::internal::FeedbackVector::AddToVectorsForProfilingTools (Isolate * isolate, DirectHandle< FeedbackVector > vector) [static], [private]
Definition at line 382 of file feedback-vector.cc.
                                                           {
  DCHECK(!isolate->is_best_effort_code_coverage());
  if (!vector->shared_function_info()->IsSubjectToDebugging()) return;
  DirectHandle<ArrayList> list = Cast<ArrayList>(
      isolate->factory()->feedback_vectors_for_profiling_tools());
  list = ArrayList::Add(isolate, list, vector);
  isolate->SetFeedbackVectorsForProfilingTools(*list);
}
References v8::internal::ArrayList::Add(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::Isolate::is_best_effort_code_coverage(), and v8::internal::Isolate::SetFeedbackVectorsForProfilingTools().
Referenced by New().
clear_invocation_count()
void v8::internal::FeedbackVector::clear_invocation_count (RelaxedStoreTag tag) [inline]
ClearAllSlotsForTesting()
bool v8::internal::FeedbackVector::ClearAllSlotsForTesting (Isolate * isolate) [inline]
Definition at line 511 of file feedback-vector.h.
                                                 {
    return ClearSlots(isolate, ClearBehavior::kClearAll);
  }
References ClearSlots(), and v8::internal::kClearAll.
ClearOptimizedCode()
void v8::internal::FeedbackVector::ClearOptimizedCode ()
Definition at line 438 of file feedback-vector.cc.
                                        {
  DCHECK(has_optimized_code());
  DCHECK(maybe_has_maglev_code() || maybe_has_turbofan_code());
  set_maybe_optimized_code(ClearedValue(GetIsolate()));
  set_maybe_has_maglev_code(false);
  set_maybe_has_turbofan_code(false);
}
References v8::internal::ClearedValue(), v8::internal::DCHECK(), has_optimized_code(), maybe_has_maglev_code(), maybe_has_turbofan_code(), set_maybe_has_maglev_code(), and set_maybe_has_turbofan_code().
Referenced by EvictOptimizedCodeMarkedForDeoptimization().
ClearSlots() [1/2]
bool v8::internal::FeedbackVector::ClearSlots (Isolate * isolate) [inline]
Definition at line 506 of file feedback-vector.h.
                                    {
    return ClearSlots(isolate, ClearBehavior::kDefault);
  }
References v8::internal::kDefault.
Referenced by ClearAllSlotsForTesting().
ClearSlots() [2/2]
bool v8::internal::FeedbackVector::ClearSlots (Isolate * isolate, ClearBehavior behavior) [private]
Definition at line 505 of file feedback-vector.cc.
                                                                        {
  if (!shared_function_info()->HasFeedbackMetadata()) return false;
  Tagged<MaybeObject> uninitialized_sentinel =
      FeedbackVector::RawUninitializedSentinel(isolate);
  bool feedback_updated = false;
  FeedbackMetadataIterator iter(metadata());
  while (iter.HasNext()) {
    FeedbackSlot slot = iter.Next();
    Tagged<MaybeObject> obj = Get(slot);
    if (obj != uninitialized_sentinel) {
      FeedbackNexus nexus(isolate, *this, slot);
      feedback_updated |= nexus.Clear(behavior);
    }
  }
  return feedback_updated;
}
References v8::internal::FeedbackNexus::Clear(), Get(), v8::internal::FeedbackMetadataIterator::HasNext(), v8::internal::FeedbackMetadataIterator::Next(), and RawUninitializedSentinel().
closure_feedback_cell()
Tagged< FeedbackCell > v8::internal::FeedbackVector::closure_feedback_cell (int index) const [inline]
Definition at line 359 of file feedback-vector-inl.h.
                                                                          {
  DCHECK_GE(index, 0);
  return closure_feedback_cell_array()->get(index);
}
References DCHECK_GE, and v8::internal::index.
EvictOptimizedCodeMarkedForDeoptimization()
void v8::internal::FeedbackVector::EvictOptimizedCodeMarkedForDeoptimization (Isolate * isolate, Tagged< SharedFunctionInfo > shared, const char * reason)
Definition at line 446 of file feedback-vector.cc.
                                                                             {
  Tagged<MaybeObject> slot = maybe_optimized_code();
  if (slot.IsCleared()) {
    set_maybe_has_maglev_code(false);
    set_maybe_has_turbofan_code(false);
    return;
  }
  Tagged<Code> code = Cast<CodeWrapper>(slot.GetHeapObject())->code(isolate);
  if (code->marked_for_deoptimization()) {
    Deoptimizer::TraceEvictFromOptimizedCodeCache(isolate, shared, reason);
    ClearOptimizedCode();
  }
}
References ClearOptimizedCode(), code, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), set_maybe_has_maglev_code(), set_maybe_has_turbofan_code(), and v8::internal::Deoptimizer::TraceEvictFromOptimizedCodeCache().
FeedbackSlotPrint()
void v8::internal::FeedbackVector::FeedbackSlotPrint (std::ostream & os, FeedbackSlot slot)
FlagMaskForNeedsProcessingCheckFrom()
constexpr uint32_t v8::internal::FeedbackVector::FlagMaskForNeedsProcessingCheckFrom (CodeKind code_kind) [inline], [static], [constexpr]
Definition at line 62 of file feedback-vector-inl.h.
                        {
  DCHECK(CodeKindCanTierUp(code_kind));
  uint32_t flag_mask = FeedbackVector::kFlagsTieringStateIsAnyRequested |
                       FeedbackVector::kFlagsLogNextExecution |
                       FeedbackVector::kFlagsMaybeHasTurbofanCode;
  if (code_kind != CodeKind::MAGLEV) {
    flag_mask |= FeedbackVector::kFlagsMaybeHasMaglevCode;
  }
  return flag_mask;
}
References v8::internal::CodeKindCanTierUp(), v8::internal::DCHECK(), kFlagsLogNextExecution, kFlagsMaybeHasMaglevCode, kFlagsMaybeHasTurbofanCode, and kFlagsTieringStateIsAnyRequested.
Referenced by v8::internal::MacroAssembler::LoadFeedbackVectorFlagsAndJumpIfNeedsProcessing(), and v8::internal::LazyBuiltinsAssembler::MaybeTailCallOptimizedCodeSlot().
Get() [1/2]
Tagged< MaybeObject > v8::internal::FeedbackVector::Get (FeedbackSlot slot) const [inline]
Definition at line 339 of file feedback-vector-inl.h.
                                                               {
  Tagged<MaybeObject> value = raw_feedback_slots(GetIndex(slot), kRelaxedLoad);
  DCHECK(!IsOfLegacyType(value));
  return value;
}
References v8::internal::DCHECK(), GetIndex(), v8::kRelaxedLoad, and v8::internal::value.
Referenced by ClearSlots(), and GetOptimizedOsrCode().
Get() [2/2]
Tagged< MaybeObject > v8::internal::FeedbackVector::Get (PtrComprCageBase cage_base, FeedbackSlot slot) const [inline]
Definition at line 345 of file feedback-vector-inl.h.
                                                                 {
  Tagged<MaybeObject> value =
      raw_feedback_slots(cage_base, GetIndex(slot), kRelaxedLoad);
  DCHECK(!IsOfLegacyType(value));
  return value;
}
References v8::internal::DCHECK(), GetIndex(), v8::kRelaxedLoad, and v8::internal::value.
GetClosureFeedbackCell()
DirectHandle< FeedbackCell > v8::internal::FeedbackVector::GetClosureFeedbackCell (Isolate * isolate, int index) const [inline]
Definition at line 353 of file feedback-vector-inl.h.
                                       {
  DCHECK_GE(index, 0);
  return direct_handle(closure_feedback_cell_array()->get(index), isolate);
}
References DCHECK_GE, v8::internal::direct_handle(), and v8::internal::index.
GetIndex()
static int v8::internal::FeedbackVector::GetIndex (FeedbackSlot slot) [inline], [static]
Definition at line 431 of file feedback-vector.h.
{ return slot.ToInt(); }
References v8::internal::FeedbackSlot::ToInt().
Referenced by v8::internal::interpreter::BytecodeGenerator::feedback_index(), Get(), v8::internal::compiler::FeedbackSource::index(), and Set().
GetKind() [1/2]
FeedbackSlotKind v8::internal::FeedbackVector::GetKind (FeedbackSlot slot) const
Definition at line 205 of file feedback-vector.cc.
                                                                {
  DCHECK(!is_empty());
  return metadata()->GetKind(slot);
}
References v8::internal::DCHECK(), and is_empty().
Referenced by GetLanguageMode(), and GetTypeofMode().
GetKind() [2/2]
FeedbackSlotKind v8::internal::FeedbackVector::GetKind (FeedbackSlot slot, AcquireLoadTag tag) const
Definition at line 210 of file feedback-vector.cc.
                                                                   {
  DCHECK(!is_empty());
  return metadata(tag)->GetKind(slot);
}
References v8::internal::DCHECK(), and is_empty().
GetLanguageMode()
LanguageMode v8::internal::FeedbackVector::GetLanguageMode (FeedbackSlot slot) const [inline]
Definition at line 491 of file feedback-vector.h.
                                                               {
    return GetLanguageModeFromSlotKind(GetKind(slot));
  }
References GetKind(), and v8::internal::GetLanguageModeFromSlotKind().
GetOptimizedOsrCode()
std::optional< Tagged< Code > > v8::internal::FeedbackVector::GetOptimizedOsrCode (Isolate * isolate, Handle< BytecodeArray > bytecode_array, FeedbackSlot slot) [inline]
Definition at line 275 of file feedback-vector-inl.h.
                                                                         {
  Tagged<MaybeObject> maybe_code = Get(isolate, slot);
  if (maybe_code.IsCleared()) return {};
  Tagged<Code> code =
      Cast<CodeWrapper>(maybe_code.GetHeapObject())->code(isolate);
  if (code->marked_for_deoptimization()) {
    // Clear the cached Code object if deoptimized.
    // TODO(jgruber): Add tracing.
    Set(slot, ClearedValue(isolate));
    if (!bytecode.is_null()) {
      RecomputeOptimizedOsrCodeFlags(isolate, bytecode);
    }
    return {};
  }
  return code;
}
References v8::internal::ClearedValue(), code, Get(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::HandleBase::is_null(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), RecomputeOptimizedOsrCodeFlags(), and Set().
Referenced by RecomputeOptimizedOsrCodeFlags(), and SetOptimizedOsrCode().
GetTypeofMode()
TypeofMode v8::internal::FeedbackVector::GetTypeofMode (FeedbackSlot slot) const [inline]
Definition at line 486 of file feedback-vector.h.
                                                           {
    return GetTypeofModeFromSlotKind(GetKind(slot));
  }
References GetKind(), and v8::internal::GetTypeofModeFromSlotKind().
has_optimized_code()
bool v8::internal::FeedbackVector::has_optimized_code () const [inline]
Definition at line 250 of file feedback-vector-inl.h.
                                              {
  bool is_cleared = maybe_optimized_code().IsCleared();
  DCHECK_IMPLIES(!is_cleared,
                 maybe_has_maglev_code() || maybe_has_turbofan_code());
  return !is_cleared;
}
References DCHECK_IMPLIES, maybe_has_maglev_code(), and maybe_has_turbofan_code().
Referenced by ClearOptimizedCode(), and SetOptimizedCode().
interrupt_budget_reset_by_ic_change()
bool v8::internal::FeedbackVector::interrupt_budget_reset_by_ic_change () const [inline]
Definition at line 188 of file feedback-vector-inl.h.
                                                               {
  return InterruptBudgetResetByIcChangeBit::decode(flags());
}
References v8::internal::flags.
is_empty()
bool v8::internal::FeedbackVector::is_empty () const [inline]
Definition at line 126 of file feedback-vector-inl.h.
{ return length() == 0; }
References v8::internal::length.
Referenced by GetKind().
log_next_execution()
bool v8::internal::FeedbackVector::log_next_execution () const [inline]
Definition at line 222 of file feedback-vector-inl.h.
                                              {
  return LogNextExecutionBit::decode(flags());
}
References v8::internal::flags.
maybe_has_maglev_code()
bool v8::internal::FeedbackVector::maybe_has_maglev_code () const [inline]
Definition at line 257 of file feedback-vector-inl.h.
                                                 {
  return MaybeHasMaglevCodeBit::decode(flags());
}
References v8::internal::flags.
Referenced by ClearOptimizedCode(), has_optimized_code(), and optimized_code().
maybe_has_maglev_osr_code()
bool v8::internal::FeedbackVector::maybe_has_maglev_osr_code () const [inline]
Definition at line 169 of file feedback-vector-inl.h.
                                                     {
  return MaybeHasMaglevOsrCodeBit::decode(osr_state());
}
Referenced by maybe_has_optimized_osr_code(), and RecomputeOptimizedOsrCodeFlags().
maybe_has_optimized_osr_code()
bool v8::internal::FeedbackVector::maybe_has_optimized_osr_code () const [inline]
Definition at line 165 of file feedback-vector-inl.h.
                                                        {
  return maybe_has_maglev_osr_code() || maybe_has_turbofan_osr_code();
}
References maybe_has_maglev_osr_code(), and maybe_has_turbofan_osr_code().
maybe_has_turbofan_code()
bool v8::internal::FeedbackVector::maybe_has_turbofan_code () const [inline]
Definition at line 265 of file feedback-vector-inl.h.
                                                   {
  return MaybeHasTurbofanCodeBit::decode(flags());
}
References v8::internal::flags.
Referenced by ClearOptimizedCode(), has_optimized_code(), and optimized_code().
maybe_has_turbofan_osr_code()
bool v8::internal::FeedbackVector::maybe_has_turbofan_osr_code () const [inline]
Definition at line 173 of file feedback-vector-inl.h.
                                                       {
  return MaybeHasTurbofanOsrCodeBit::decode(osr_state());
}
Referenced by maybe_has_optimized_osr_code(), and RecomputeOptimizedOsrCodeFlags().
MegaDOMSentinel()
DirectHandle< Symbol > v8::internal::FeedbackVector::MegaDOMSentinel (Isolate * isolate) [inline], [static]
Definition at line 500 of file feedback-vector-inl.h.
                                                                     {
  return isolate->factory()->mega_dom_symbol();
}
References v8::internal::Isolate::factory().
Referenced by v8::internal::FeedbackNexus::MegaDOMSentinel().
MegamorphicSentinel()
Handle< Symbol > v8::internal::FeedbackVector::MegamorphicSentinel (Isolate * isolate) [inline], [static]
Definition at line 496 of file feedback-vector-inl.h.
                                                                   {
  return isolate->factory()->megamorphic_symbol();
}
References v8::internal::Isolate::factory().
Referenced by v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread(), and v8::internal::FeedbackNexus::MegamorphicSentinel().
New()
Handle< FeedbackVector > v8::internal::FeedbackVector::New (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared, DirectHandle< ClosureFeedbackCellArray > closure_feedback_cell_array, DirectHandle< FeedbackCell > parent_feedback_cell, IsCompiledScope * is_compiled_scope) [static]
Definition at line 252 of file feedback-vector.cc.
                                        {
  DCHECK(is_compiled_scope->is_compiled());
  Factory* factory = isolate->factory();
  DirectHandle<FeedbackMetadata> feedback_metadata(shared->feedback_metadata(),
                                                   isolate);
  const int slot_count = feedback_metadata->slot_count();
  Handle<FeedbackVector> vector = factory->NewFeedbackVector(
      shared, closure_feedback_cell_array, parent_feedback_cell);
  DCHECK_EQ(vector->length(), slot_count);
  DCHECK_EQ(vector->shared_function_info(), *shared);
  DCHECK_EQ(vector->invocation_count(), 0);
#ifndef V8_ENABLE_LEAPTIERING
  DCHECK_EQ(vector->tiering_state(), TieringState::kNone);
  DCHECK(!vector->maybe_has_maglev_code());
  DCHECK(!vector->maybe_has_turbofan_code());
  DCHECK(vector->maybe_optimized_code().IsCleared());
#endif // !V8_ENABLE_LEAPTIERING
  // Ensure we can skip the write barrier
  DirectHandle<Symbol> uninitialized_sentinel = UninitializedSentinel(isolate);
  DCHECK_EQ(ReadOnlyRoots(isolate).uninitialized_symbol(),
            *uninitialized_sentinel);
  for (int i = 0; i < slot_count;) {
    FeedbackSlot slot(i);
    FeedbackSlotKind kind = feedback_metadata->GetKind(slot);
    int entry_size = FeedbackMetadata::GetSlotSize(kind);
    Tagged<MaybeObject> extra_value = *uninitialized_sentinel;
    switch (kind) {
      case FeedbackSlotKind::kLoadGlobalInsideTypeof:
      case FeedbackSlotKind::kLoadGlobalNotInsideTypeof:
      case FeedbackSlotKind::kStoreGlobalSloppy:
      case FeedbackSlotKind::kStoreGlobalStrict:
      case FeedbackSlotKind::kJumpLoop:
        vector->Set(slot, ClearedValue(isolate), SKIP_WRITE_BARRIER);
        break;
      case FeedbackSlotKind::kForIn:
      case FeedbackSlotKind::kCompareOp:
      case FeedbackSlotKind::kBinaryOp:
      case FeedbackSlotKind::kTypeOf:
        vector->Set(slot, Smi::zero(), SKIP_WRITE_BARRIER);
        break;
      case FeedbackSlotKind::kLiteral:
        vector->Set(slot, Smi::zero(), SKIP_WRITE_BARRIER);
        break;
      case FeedbackSlotKind::kCall:
        vector->Set(slot, *uninitialized_sentinel, SKIP_WRITE_BARRIER);
        extra_value = Smi::zero();
        break;
      case FeedbackSlotKind::kCloneObject:
      case FeedbackSlotKind::kLoadProperty:
      case FeedbackSlotKind::kLoadKeyed:
      case FeedbackSlotKind::kHasKeyed:
      case FeedbackSlotKind::kSetNamedSloppy:
      case FeedbackSlotKind::kSetNamedStrict:
      case FeedbackSlotKind::kDefineNamedOwn:
      case FeedbackSlotKind::kDefineKeyedOwn:
      case FeedbackSlotKind::kSetKeyedSloppy:
      case FeedbackSlotKind::kSetKeyedStrict:
      case FeedbackSlotKind::kStoreInArrayLiteral:
      case FeedbackSlotKind::kDefineKeyedOwnPropertyInLiteral:
      case FeedbackSlotKind::kInstanceOf:
        vector->Set(slot, *uninitialized_sentinel, SKIP_WRITE_BARRIER);
        break;
      case FeedbackSlotKind::kStringAddAndInternalize:
        vector->Set(slot, Smi::zero(), SKIP_WRITE_BARRIER);
        break;
      case FeedbackSlotKind::kInvalid:
        UNREACHABLE();
    }
    for (int j = 1; j < entry_size; j++) {
      vector->Set(slot.WithOffset(j), extra_value, SKIP_WRITE_BARRIER);
    }
    i += entry_size;
  }
  if (!isolate->is_best_effort_code_coverage()) {
    AddToVectorsForProfilingTools(isolate, vector);
  }
  parent_feedback_cell->set_value(*vector, kReleaseStore);
  return vector;
}
References AddToVectorsForProfilingTools(), v8::internal::ClearedValue(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::FeedbackMetadata::GetSlotSize(), v8::internal::Isolate::is_best_effort_code_coverage(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::kBinaryOp, v8::internal::kCall, v8::internal::kCloneObject, v8::internal::kCompareOp, v8::internal::kDefineKeyedOwn, v8::internal::kDefineKeyedOwnPropertyInLiteral, v8::internal::kDefineNamedOwn, v8::internal::kForIn, v8::internal::kHasKeyed, v8::internal::kInstanceOf, v8::internal::kInvalid, v8::internal::kJumpLoop, v8::internal::kLiteral, v8::internal::kLoadGlobalInsideTypeof, v8::internal::kLoadGlobalNotInsideTypeof, v8::internal::kLoadKeyed, v8::internal::kLoadProperty, v8::kReleaseStore, v8::internal::kSetKeyedSloppy, v8::internal::kSetKeyedStrict, v8::internal::kSetNamedSloppy, v8::internal::kSetNamedStrict, v8::internal::kStoreGlobalSloppy, v8::internal::kStoreGlobalStrict, v8::internal::kStoreInArrayLiteral, v8::internal::kStringAddAndInternalize, v8::internal::kTypeOf, v8::internal::Factory::NewFeedbackVector(), v8::internal::SKIP_WRITE_BARRIER, UninitializedSentinel(), v8::internal::UNREACHABLE(), v8::internal::FeedbackSlot::WithOffset(), and v8::internal::Smi::zero().
Referenced by v8::internal::JSFunction::CreateAndAttachFeedbackVector(), and NewForTesting().
NewForTesting()
Handle< FeedbackVector > v8::internal::FeedbackVector::NewForTesting (Isolate * isolate, const FeedbackVectorSpec * spec) [static]
Definition at line 345 of file feedback-vector.cc.
                                                      {
  DirectHandle<FeedbackMetadata> metadata =
      FeedbackMetadata::New(isolate, spec);
  DirectHandle<SharedFunctionInfo> shared =
      isolate->factory()->NewSharedFunctionInfoForBuiltin(
          isolate->factory()->empty_string(), Builtin::kIllegal, 0, kDontAdapt);
  // Set the raw feedback metadata to circumvent checks that we are not
  // overwriting existing metadata.
  shared->set_raw_outer_scope_info_or_feedback_metadata(*metadata);
  DirectHandle<ClosureFeedbackCellArray> closure_feedback_cell_array =
      ClosureFeedbackCellArray::New(isolate, shared);
  DirectHandle<FeedbackCell> parent_cell =
      isolate->factory()->NewNoClosuresCell();
  IsCompiledScope is_compiled_scope(shared->is_compiled_scope(isolate));
  return FeedbackVector::New(isolate, shared, closure_feedback_cell_array,
                             parent_cell, &is_compiled_scope);
}
References v8::internal::Isolate::factory(), v8::internal::kDontAdapt, v8::internal::ClosureFeedbackCellArray::New(), New(), v8::internal::FeedbackMetadata::New(), v8::internal::Factory::NewNoClosuresCell(), and v8::internal::Factory::NewSharedFunctionInfoForBuiltin().
Referenced by NewWithOneBinarySlotForTesting(), and NewWithOneCompareSlotForTesting().
NewWithOneBinarySlotForTesting()
Handle< FeedbackVector > v8::internal::FeedbackVector::NewWithOneBinarySlotForTesting (Zone * zone, Isolate * isolate) [static]
Definition at line 366 of file feedback-vector.cc.
                                  {
  FeedbackVectorSpec one_slot(zone);
  one_slot.AddBinaryOpICSlot();
  return NewForTesting(isolate, &one_slot);
}
References v8::internal::FeedbackVectorSpec::AddBinaryOpICSlot(), and NewForTesting().
NewWithOneCompareSlotForTesting()
Handle< FeedbackVector > v8::internal::FeedbackVector::NewWithOneCompareSlotForTesting (Zone * zone, Isolate * isolate) [static]
Definition at line 374 of file feedback-vector.cc.
                                  {
  FeedbackVectorSpec one_slot(zone);
  one_slot.AddCompareICSlot();
  return NewForTesting(isolate, &one_slot);
}
References v8::internal::FeedbackVectorSpec::AddCompareICSlot(), and NewForTesting().
OffsetOfElementAt()
static constexpr int v8::internal::FeedbackVector::OffsetOfElementAt (int index) [inline], [static], [constexpr]
Definition at line 533 of file feedback-vector.h.
                                                    {
    return kRawFeedbackSlotsOffset + index * kTaggedSize;
  }
References v8::internal::index, and v8::internal::kTaggedSize.
Referenced by v8::internal::compiler::AccessBuilder::ForFeedbackVectorSlot(), v8::internal::FeedbackNexus::ic_state(), slots_start(), v8::internal::MacroAssembler::TryLoadOptimizedOsrCode(), and v8::internal::baseline::BaselineAssembler::TryLoadOptimizedOsrCode().
optimized_code()
Tagged< Code > v8::internal::FeedbackVector::optimized_code (IsolateForSandbox isolate) const [inline]
Definition at line 230 of file feedback-vector-inl.h.
                                                                           {
  Tagged<MaybeWeak<HeapObject>> slot = maybe_optimized_code();
  DCHECK(slot.IsWeakOrCleared());
  Tagged<HeapObject> heap_object;
  Tagged<Code> code;
  if (slot.GetHeapObject(&heap_object)) {
    code = Cast<CodeWrapper>(heap_object)->code(isolate);
  }
  // It is possible that the maybe_optimized_code slot is cleared but the flags
  // haven't been updated yet. We update them when we execute the function next
  // time / when we create new closure.
  DCHECK_IMPLIES(!code.is_null(),
                 maybe_has_maglev_code() || maybe_has_turbofan_code());
  DCHECK_IMPLIES(!code.is_null() && code->is_maglevved(),
                 maybe_has_maglev_code());
  DCHECK_IMPLIES(!code.is_null() && code->is_turbofanned(),
                 maybe_has_turbofan_code());
  return code;
}
References code, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::TaggedImpl< kRefType, StorageType >::IsWeakOrCleared(), maybe_has_maglev_code(), and maybe_has_turbofan_code().
Referenced by SetOptimizedCode().
osr_tiering_in_progress()
bool v8::internal::FeedbackVector::osr_tiering_in_progress ()
Definition at line 497 of file feedback-vector.cc.
                                             {
  return OsrTieringInProgressBit::decode(flags());
}
References v8::internal::flags.
osr_urgency()
int v8::internal::FeedbackVector::osr_urgency () const [inline]
RawUninitializedSentinel()
Tagged< Symbol > v8::internal::FeedbackVector::RawUninitializedSentinel (Isolate * isolate) [inline], [static]
Definition at line 504 of file feedback-vector-inl.h.
                                                                        {
  return ReadOnlyRoots(isolate).uninitialized_symbol();
}
Referenced by ClearSlots().
RecomputeOptimizedOsrCodeFlags()
void v8::internal::FeedbackVector::RecomputeOptimizedOsrCodeFlags (Isolate * isolate, Handle< BytecodeArray > bytecode_array) [inline]
Definition at line 295 of file feedback-vector-inl.h.
                                                            {
  bool turbofan = false;
  bool maglev = false;
  interpreter::BytecodeArrayIterator it(bytecode_array);
  for (; !it.done(); it.Advance()) {
    if (it.current_bytecode() != interpreter::Bytecode::kJumpLoop) continue;
    if (auto code = GetOptimizedOsrCode(isolate, {}, it.GetSlotOperand(2))) {
      if ((*code)->marked_for_deoptimization()) continue;
      turbofan |= (*code)->is_turbofanned();
      maglev |= (*code)->is_maglevved();
    }
  }
  if (!maglev && maybe_has_maglev_osr_code()) {
    set_maybe_has_optimized_osr_code(false, CodeKind::MAGLEV);
  }
  if (!turbofan && maybe_has_turbofan_osr_code()) {
    set_maybe_has_optimized_osr_code(false, CodeKind::TURBOFAN_JS);
  }
}
References v8::internal::interpreter::BytecodeArrayIterator::Advance(), code, v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeArrayIterator::done(), GetOptimizedOsrCode(), v8::internal::interpreter::BytecodeArrayIterator::GetSlotOperand(), maybe_has_maglev_osr_code(), maybe_has_turbofan_osr_code(), and set_maybe_has_optimized_osr_code().
Referenced by GetOptimizedOsrCode().
RequestOsrAtNextOpportunity()
void v8::internal::FeedbackVector::RequestOsrAtNextOpportunity () [inline]
Definition at line 159 of file feedback-vector-inl.h.
                                                 {
  set_osr_urgency(kMaxOsrUrgency);
}
References kMaxOsrUrgency, and set_osr_urgency().
reset_flags()
void v8::internal::FeedbackVector::reset_flags ()
Definition at line 470 of file feedback-vector.cc.
                                 {
  set_flags(
#ifdef V8_ENABLE_LEAPTIERING
      TieringInProgressBit::encode(false) |
#else
      TieringStateBits::encode(TieringState::kNone) |
      LogNextExecutionBit::encode(false) |
      MaybeHasMaglevCodeBit::encode(false) |
      MaybeHasTurbofanCodeBit::encode(false) |
#endif // V8_ENABLE_LEAPTIERING
      OsrTieringInProgressBit::encode(false) |
      MaybeHasMaglevOsrCodeBit::encode(false) |
      MaybeHasTurbofanOsrCodeBit::encode(false));
}
reset_osr_state()
void v8::internal::FeedbackVector::reset_osr_state () [inline]
Definition at line 163 of file feedback-vector-inl.h.
{ set_osr_state(0); }
reset_osr_urgency()
void v8::internal::FeedbackVector::reset_osr_urgency () [inline]
Definition at line 157 of file feedback-vector-inl.h.
{ set_osr_urgency(0); }
References set_osr_urgency().
reset_tiering_state()
void v8::internal::FeedbackVector::reset_tiering_state () [inline]
Definition at line 218 of file feedback-vector-inl.h.
                                         {
  set_tiering_state(TieringState::kNone);
}
References set_tiering_state().
Set()
void v8::internal::FeedbackVector::Set (FeedbackSlot slot, Tagged< MaybeObject > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline], [private]
Definition at line 385 of file feedback-vector-inl.h.
                                                {
  DCHECK(!IsOfLegacyType(value));
  set_raw_feedback_slots(GetIndex(slot), value, kRelaxedStore, mode);
}
References v8::internal::DCHECK(), GetIndex(), v8::kRelaxedStore, mode(), and v8::internal::value.
Referenced by GetOptimizedOsrCode(), and SetOptimizedOsrCode().
set_interrupt_budget_reset_by_ic_change()
void v8::internal::FeedbackVector::set_interrupt_budget_reset_by_ic_change (bool value) [inline]
Definition at line 192 of file feedback-vector-inl.h.
                                                                       {
  set_flags(InterruptBudgetResetByIcChangeBit::update(flags(), value));
}
References v8::internal::flags, and v8::internal::value.
set_log_next_execution()
void v8::internal::FeedbackVector::set_log_next_execution (bool value = true) [inline]
Definition at line 226 of file feedback-vector-inl.h.
                                                      {
  set_flags(LogNextExecutionBit::update(flags(), value));
}
References v8::internal::flags, and v8::internal::value.
set_maybe_has_maglev_code()
void v8::internal::FeedbackVector::set_maybe_has_maglev_code (bool value) [inline]
Definition at line 261 of file feedback-vector-inl.h.
                                                         {
  set_flags(MaybeHasMaglevCodeBit::update(flags(), value));
}
References v8::internal::flags, and v8::internal::value.
Referenced by ClearOptimizedCode(), and EvictOptimizedCodeMarkedForDeoptimization().
set_maybe_has_optimized_osr_code()
void v8::internal::FeedbackVector::set_maybe_has_optimized_osr_code (bool value, CodeKind code_kind) [inline]
Definition at line 177 of file feedback-vector-inl.h.
                                                                          {
  if (code_kind == CodeKind::MAGLEV) {
    CHECK(v8_flags.maglev_osr);
    set_osr_state(MaybeHasMaglevOsrCodeBit::update(osr_state(), value));
  } else {
    CHECK_EQ(code_kind, CodeKind::TURBOFAN_JS);
    set_osr_state(MaybeHasTurbofanOsrCodeBit::update(osr_state(), value));
  }
}
References CHECK, CHECK_EQ, v8::internal::v8_flags, and v8::internal::value.
Referenced by RecomputeOptimizedOsrCodeFlags(), and SetOptimizedOsrCode().
set_maybe_has_turbofan_code()
void v8::internal::FeedbackVector::set_maybe_has_turbofan_code (bool value) [inline]
Definition at line 269 of file feedback-vector-inl.h.
                                                           {
  set_flags(MaybeHasTurbofanCodeBit::update(flags(), value));
}
References v8::internal::flags, and v8::internal::value.
Referenced by ClearOptimizedCode(), and EvictOptimizedCodeMarkedForDeoptimization().
set_osr_tiering_in_progress()
void v8::internal::FeedbackVector::set_osr_tiering_in_progress (bool osr_in_progress)
Definition at line 501 of file feedback-vector.cc.
                                                                     {
  set_flags(OsrTieringInProgressBit::update(flags(), osr_in_progress));
}
References v8::internal::flags.
set_osr_urgency()
void v8::internal::FeedbackVector::set_osr_urgency (int urgency) [inline]
Referenced by RequestOsrAtNextOpportunity(), and reset_osr_urgency().
set_tiering_state()
void v8::internal::FeedbackVector::set_tiering_state (TieringState state)
Definition at line 462 of file feedback-vector.cc.
                                                         {
  int32_t new_flags = flags();
  new_flags = TieringStateBits::update(new_flags, state);
  set_flags(new_flags);
}
References v8::internal::flags.
Referenced by reset_tiering_state().
set_was_once_deoptimized()
void v8::internal::FeedbackVector::set_was_once_deoptimized () [inline]
Definition at line 201 of file feedback-vector-inl.h.
                                              {
  set_invocation_count_before_stable(kInvocationCountBeforeStableDeoptSentinel,
                                     kRelaxedStore);
}
References kInvocationCountBeforeStableDeoptSentinel, and v8::kRelaxedStore.
SetOptimizedCode()
void v8::internal::FeedbackVector::SetOptimizedCode (IsolateForSandbox isolate, Tagged< Code > code)
Definition at line 400 of file feedback-vector.cc.
                                                         {
  DCHECK(CodeKindIsOptimizedJSFunction(code->kind()));
  int32_t state = flags();
  // Skip setting optimized code if it would cause us to tier down.
  if (!has_optimized_code()) {
    state = MaybeHasTurbofanCodeBit::update(state, false);
  } else if (!CodeKindCanTierUp(optimized_code(isolate)->kind()) ||
             optimized_code(isolate)->kind() > code->kind()) {
    if (!v8_flags.stress_concurrent_inlining_attach_code &&
        !optimized_code(isolate)->marked_for_deoptimization()) {
      return;
    }
    // If we fall through, we may be tiering down. This is fine since we only do
    // that when the current code is marked for deoptimization, or because we're
    // stress testing.
    state = MaybeHasTurbofanCodeBit::update(state, false);
  }
  // TODO(mythria): We could see a CompileOptimized state here either from
  // tests that use %OptimizeFunctionOnNextCall, --always-turbofan or because we
  // re-mark the function for non-concurrent optimization after an OSR. We
  // should avoid these cases and also check that marker isn't
  // TieringState::kRequestTurbofan*.
  set_maybe_optimized_code(MakeWeak(code->wrapper()));
  // TODO(leszeks): Reconsider whether this could clear the tiering state vs.
  // the callers doing so.
  state = TieringStateBits::update(state, TieringState::kNone);
  if (code->is_maglevved()) {
    DCHECK(!MaybeHasTurbofanCodeBit::decode(state));
    state = MaybeHasMaglevCodeBit::update(state, true);
  } else {
    DCHECK(code->is_turbofanned());
    state = MaybeHasTurbofanCodeBit::update(state, true);
    state = MaybeHasMaglevCodeBit::update(state, false);
  }
  set_flags(state);
}
References code, v8::internal::CodeKindCanTierUp(), v8::internal::CodeKindIsOptimizedJSFunction(), v8::internal::DCHECK(), v8::internal::flags, has_optimized_code(), v8::internal::MakeWeak(), optimized_code(), and v8::internal::v8_flags.
SetOptimizedOsrCode()
void v8::internal::FeedbackVector::SetOptimizedOsrCode (Isolate * isolate, FeedbackSlot slot, Tagged< Code > code)
Definition at line 485 of file feedback-vector.cc.
                                                            {
  DCHECK(CodeKindIsOptimizedJSFunction(code->kind()));
  DCHECK(!slot.IsInvalid());
  auto current = GetOptimizedOsrCode(isolate, {}, slot);
  if (V8_UNLIKELY(current && current.value()->kind() > code->kind())) {
    return;
  }
  Set(slot, MakeWeak(code->wrapper()));
  set_maybe_has_optimized_osr_code(true, code->kind());
}
References code, v8::internal::CodeKindIsOptimizedJSFunction(), v8::internal::DCHECK(), GetOptimizedOsrCode(), v8::internal::FeedbackSlot::IsInvalid(), v8::internal::MakeWeak(), Set(), set_maybe_has_optimized_osr_code(), and V8_UNLIKELY.
slots_start()
MaybeObjectSlot v8::internal::FeedbackVector::slots_start () [inline]
Definition at line 391 of file feedback-vector-inl.h.
                                                   {
  return RawMaybeWeakField(OffsetOfElementAt(0));
}
References OffsetOfElementAt().
SynchronizedGet()
Tagged< MaybeObject > v8::internal::FeedbackVector::SynchronizedGet (FeedbackSlot slot) const [inline]
Definition at line 364 of file feedback-vector-inl.h.
                                                                           {
  const int i = slot.ToInt();
  DCHECK_LT(static_cast<unsigned>(i), static_cast<unsigned>(this->length()));
  const int offset = kRawFeedbackSlotsOffset + i * kTaggedSize;
  Tagged<MaybeObject> value =
      TaggedField<MaybeObject>::Acquire_Load(*this, offset);
  DCHECK(!IsOfLegacyType(value));
  return value;
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Acquire_Load(), v8::internal::DCHECK(), DCHECK_LT, v8::internal::kTaggedSize, v8::internal::length, v8::internal::FeedbackSlot::ToInt(), and v8::internal::value.
SynchronizedSet()
void v8::internal::FeedbackVector::SynchronizedSet (FeedbackSlot slot, Tagged< MaybeObject > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 374 of file feedback-vector-inl.h.
                                                            {
  DCHECK(!IsOfLegacyType(value));
  const int i = slot.ToInt();
  DCHECK_LT(static_cast<unsigned>(i), static_cast<unsigned>(this->length()));
  const int offset = kRawFeedbackSlotsOffset + i * kTaggedSize;
  TaggedField<MaybeObject>::Release_Store(*this, offset, value);
  CONDITIONAL_WRITE_BARRIER(*this, offset, value, mode);
}
References CONDITIONAL_WRITE_BARRIER, v8::internal::DCHECK(), DCHECK_LT, v8::internal::kTaggedSize, v8::internal::length, mode(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store(), v8::internal::FeedbackSlot::ToInt(), and v8::internal::value.
tiering_state()
TieringState v8::internal::FeedbackVector::tiering_state () const [inline]
Definition at line 214 of file feedback-vector-inl.h.
                                                 {
  return TieringStateBits::decode(flags());
}
References v8::internal::flags.
ToSlot()
FeedbackSlot v8::internal::FeedbackVector::ToSlot (intptr_t index) [inline], [static]
Definition at line 318 of file feedback-vector-inl.h.
                                                  {
  if (index == static_cast<intptr_t>(FeedbackSlot::Invalid().ToInt())) {
    return FeedbackSlot();
  }
  DCHECK_LE(static_cast<uintptr_t>(index),
            static_cast<uintptr_t>(std::numeric_limits<int>::max()));
  return FeedbackSlot(static_cast<int>(index));
}
References DCHECK_LE, v8::internal::index, v8::internal::FeedbackSlot::Invalid(), and v8::internal::anonymous_namespace{temporal-parser.cc}::ToInt().
Referenced by v8::internal::compiler::BytecodeGraphBuilder::ComputeCallFeedbackRelation(), v8::internal::compiler::BytecodeGraphBuilder::ComputeCallFrequency(), v8::internal::compiler::BytecodeGraphBuilder::CreateFeedbackSource(), v8::internal::anonymous_namespace{runtime-literals.cc}::CreateLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::DefineKeyedOwnProperty(), v8::internal::interpreter::BytecodeArrayBuilder::DefineNamedOwnProperty(), v8::internal::interpreter::BytecodeArrayIterator::GetSlotOperand(), v8::internal::compiler::BytecodeGraphBuilder::GetSpeculationMode(), v8::internal::interpreter::BytecodeArrayBuilder::LoadGlobal(), v8::internal::RUNTIME_FUNCTION(), v8::internal::interpreter::BytecodeArrayBuilder::SetKeyedProperty(), v8::internal::interpreter::BytecodeArrayBuilder::SetNamedProperty(), v8::internal::anonymous_namespace{runtime-strings.cc}::StringAdd_StringConstant_Internalize(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceGetIterator().
UninitializedSentinel()
DirectHandle< Symbol > v8::internal::FeedbackVector::UninitializedSentinel (Isolate * isolate) [inline], [static]
Definition at line 492 of file feedback-vector-inl.h.
                                                                           {
  return isolate->factory()->uninitialized_symbol();
}
References v8::internal::Isolate::factory().
Referenced by New(), and v8::internal::FeedbackNexus::UninitializedSentinel().
was_once_deoptimized()
bool v8::internal::FeedbackVector::was_once_deoptimized () const [inline]
Definition at line 196 of file feedback-vector-inl.h.
                                                {
  return invocation_count_before_stable(kRelaxedLoad) ==
         kInvocationCountBeforeStableDeoptSentinel;
}
References kInvocationCountBeforeStableDeoptSentinel, and v8::kRelaxedLoad.
Member Data Documentation
kFlagsHasAnyOptimizedCode
constexpr uint32_t v8::internal::FeedbackVector::kFlagsHasAnyOptimizedCode [static], [constexpr]
Initial value:
=
      FeedbackVector::MaybeHasMaglevCodeBit::kMask |
      FeedbackVector::MaybeHasTurbofanCodeBit::kMask
Definition at line 322 of file feedback-vector.h.
kFlagsLogNextExecution
constexpr uint32_t v8::internal::FeedbackVector::kFlagsLogNextExecution [static], [constexpr]
Initial value:
=
      FeedbackVector::LogNextExecutionBit::kMask
Definition at line 327 of file feedback-vector.h.
Referenced by FlagMaskForNeedsProcessingCheckFrom(), and v8::internal::LazyBuiltinsAssembler::MaybeTailCallOptimizedCodeSlot().
kFlagsMaybeHasMaglevCode
constexpr uint32_t v8::internal::FeedbackVector::kFlagsMaybeHasMaglevCode [static], [constexpr]
Initial value:
=
      FeedbackVector::MaybeHasMaglevCodeBit::kMask
Definition at line 320 of file feedback-vector.h.
Referenced by FlagMaskForNeedsProcessingCheckFrom().
kFlagsMaybeHasTurbofanCode
constexpr uint32_t v8::internal::FeedbackVector::kFlagsMaybeHasTurbofanCode [static], [constexpr]
Initial value:
=
      FeedbackVector::MaybeHasTurbofanCodeBit::kMask
Definition at line 318 of file feedback-vector.h.
Referenced by FlagMaskForNeedsProcessingCheckFrom().
kFlagsTieringStateIsAnyRequested
constexpr uint32_t v8::internal::FeedbackVector::kFlagsTieringStateIsAnyRequested [static], [constexpr]
Initial value:
=
      kNoneOrInProgressMask << FeedbackVector::TieringStateBits::kShift
Definition at line 325 of file feedback-vector.h.
Referenced by FlagMaskForNeedsProcessingCheckFrom(), v8::internal::LazyBuiltinsAssembler::MaybeTailCallOptimizedCodeSlot(), and v8::internal::MacroAssembler::OptimizeCodeOrTailCallOptimizedCodeSlot().
kInvocationCountBeforeStableDeoptSentinel
constexpr uint8_t v8::internal::FeedbackVector::kInvocationCountBeforeStableDeoptSentinel = 0xff [static], [constexpr]
Definition at line 350 of file feedback-vector.h.
Referenced by v8::internal::TieringManager::NotifyICChanged(), set_was_once_deoptimized(), and was_once_deoptimized().
kMaxOsrUrgency
constexpr int v8::internal::FeedbackVector::kMaxOsrUrgency = 6 [static], [constexpr]
Definition at line 355 of file feedback-vector.h.
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER(), v8::internal::interpreter::LoopBuilder::JumpToHeader(), RequestOsrAtNextOpportunity(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{tiering-manager.cc}::TryIncrementOsrUrgency(), and v8::internal::anonymous_namespace{tiering-manager.cc}::TryRequestOsrAtNextOpportunity().
NexusConfig
friend v8::internal::FeedbackVector::NexusConfig [private]
Definition at line 556 of file feedback-vector.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/feedback-vector.h
/mnt/V8SourceCode/src/objects/feedback-vector-inl.h
/mnt/V8SourceCode/src/objects/feedback-vector.cc