v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole Class Reference
Public Member Functions
RegExpBytecodePeephole (Zone *zone, size_t buffer_size, const ZoneUnorderedMap< int, int > &jump_edges)
bool OptimizeBytecode (const uint8_t *bytecode, int length)
void CopyOptimizedBytecode (uint8_t *to_address) const
int Length () const
Private Member Functions
void DefineStandardSequences ()
BytecodeSequenceNode & CreateSequence (int bytecode)
int TryOptimizeSequence (const uint8_t *bytecode, int bytecode_length, int start_pc)
void EmitOptimization (int start_pc, const uint8_t *bytecode, const BytecodeSequenceNode &last_node)
void AddJumpSourceFixup (int fixup, int pos)
void AddJumpDestinationFixup (int fixup, int pos)
void SetJumpDestinationFixup (int fixup, int pos)
void PrepareJumpStructures (const ZoneUnorderedMap< int, int > &jump_edges)
void FixJumps ()
void FixJump (int jump_source, int jump_destination)
void AddSentinelFixups (int pos)
template<typename T >
void EmitValue (T value)
template<typename T >
void OverwriteValue (int offset, T value)
void CopyRangeToOutput (const uint8_t *orig_bytecode, int start, int length)
void SetRange (uint8_t value, int count)
void EmitArgument (int start_pc, const uint8_t *bytecode, BytecodeArgumentMapping arg)
int pc () const
Zone * zone () const
DISALLOW_IMPLICIT_CONSTRUCTORS (RegExpBytecodePeephole)
Private Attributes
ZoneVector< uint8_t > optimized_bytecode_buffer_
BytecodeSequenceNode * sequences_
ZoneMap< int, int > jump_edges_
ZoneMap< int, int > jump_edges_mapped_
ZoneMap< int, int > jump_usage_counts_
ZoneMap< int, int > jump_source_fixups_
ZoneMap< int, int > jump_destination_fixups_
Zone * zone_
Detailed Description
Definition at line 171 of file regexp-bytecode-peephole.cc.
Constructor & Destructor Documentation
RegExpBytecodePeephole()
v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::RegExpBytecodePeephole (Zone * zone, size_t buffer_size, const ZoneUnorderedMap< int, int > & jump_edges)
Definition at line 472 of file regexp-bytecode-peephole.cc.
    : optimized_bytecode_buffer_(zone),
      sequences_(zone->New<BytecodeSequenceNode>(
          BytecodeSequenceNode::kDummyBytecode, zone)),
      jump_edges_(zone),
      jump_edges_mapped_(zone),
      jump_usage_counts_(zone),
      jump_source_fixups_(zone),
      jump_destination_fixups_(zone),
      zone_(zone) {
  optimized_bytecode_buffer_.reserve(buffer_size);
  PrepareJumpStructures(jump_edges);
  DefineStandardSequences();
  // Sentinel fixups at beginning of bytecode (position -1) so we don't have to
  // check for end of iterator inside the fixup loop.
  // In general fixups are deltas of original offsets of jump
  // sources/destinations (in the old bytecode) to find them in the new
  // bytecode. All jump targets are fixed after the new bytecode is fully
  // emitted in the internal buffer.
  AddSentinelFixups(-1);
  // Sentinel fixups at end of (old) bytecode so we don't have to check for
  // end of iterator inside the fixup loop.
  DCHECK_LE(buffer_size, std::numeric_limits<int>::max());
  AddSentinelFixups(static_cast<int>(buffer_size));
}
References AddSentinelFixups(), DCHECK_LE, DefineStandardSequences(), optimized_bytecode_buffer_, PrepareJumpStructures(), and v8::internal::ZoneVector< T >::reserve().
Member Function Documentation
AddJumpDestinationFixup()
void v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::AddJumpDestinationFixup (int fixup, int pos) [private]
Definition at line 817 of file regexp-bytecode-peephole.cc.
                                                                       {
  auto previous_fixup = jump_destination_fixups_.lower_bound(pos);
  DCHECK(previous_fixup != jump_destination_fixups_.end());
  DCHECK(previous_fixup != jump_destination_fixups_.begin());
  int previous_fixup_value = (--previous_fixup)->second;
  jump_destination_fixups_[pos] = previous_fixup_value + fixup;
}
References v8::internal::DCHECK(), and jump_destination_fixups_.
Referenced by EmitOptimization().
AddJumpSourceFixup()
void v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::AddJumpSourceFixup (int fixup, int pos) [private]
Definition at line 808 of file regexp-bytecode-peephole.cc.
                                                                  {
  auto previous_fixup = jump_source_fixups_.lower_bound(pos);
  DCHECK(previous_fixup != jump_source_fixups_.end());
  DCHECK(previous_fixup != jump_source_fixups_.begin());
  int previous_fixup_value = (--previous_fixup)->second;
  jump_source_fixups_[pos] = previous_fixup_value + fixup;
}
References v8::internal::DCHECK(), and jump_source_fixups_.
Referenced by EmitOptimization().
AddSentinelFixups()
void v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::AddSentinelFixups (int pos) [private]
Definition at line 896 of file regexp-bytecode-peephole.cc.
                                                      {
  jump_source_fixups_.emplace(pos, 0);
  jump_destination_fixups_.emplace(pos, 0);
}
References jump_destination_fixups_, and jump_source_fixups_.
Referenced by RegExpBytecodePeephole().
CopyOptimizedBytecode()
void v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::CopyOptimizedBytecode (uint8_t * to_address) const
Definition at line 644 of file regexp-bytecode-peephole.cc.
                                                                            {
  MemCopy(to_address, &(*optimized_bytecode_buffer_.begin()), Length());
}
References v8::internal::ZoneVector< T >::begin(), Length(), v8::internal::MemCopy(), and optimized_bytecode_buffer_.
CopyRangeToOutput()
void v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::CopyRangeToOutput (const uint8_t * orig_bytecode, int start, int length) [private]
Definition at line 920 of file regexp-bytecode-peephole.cc.
                                                                      {
  DCHECK(optimized_bytecode_buffer_.begin() + pc() ==
         optimized_bytecode_buffer_.end());
  optimized_bytecode_buffer_.insert(optimized_bytecode_buffer_.end(),
                                    orig_bytecode + start,
                                    orig_bytecode + start + length);
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::DCHECK(), v8::internal::ZoneVector< T >::end(), v8::internal::ZoneVector< T >::insert(), v8::internal::length, optimized_bytecode_buffer_, and pc().
Referenced by EmitArgument(), EmitOptimization(), and OptimizeBytecode().
CreateSequence()
BytecodeSequenceNode & v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::CreateSequence (int bytecode) [private]
Definition at line 650 of file regexp-bytecode-peephole.cc.
                                                                         {
  DCHECK(sequences_ != nullptr);
  DCHECK(0 <= bytecode && bytecode < kRegExpBytecodeCount);
  return sequences_->FollowedBy(bytecode);
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::FollowedBy(), v8::internal::kRegExpBytecodeCount, and sequences_.
Referenced by DefineStandardSequences().
DefineStandardSequences()
void v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::DefineStandardSequences () [private]
Definition at line 500 of file regexp-bytecode-peephole.cc.
                                                     {
  // Commonly used sequences can be found by creating regexp bytecode traces
  // (--trace-regexp-bytecodes) and using v8/tools/regexp-sequences.py.
  CreateSequence(BC_LOAD_CURRENT_CHAR)
      .FollowedBy(BC_CHECK_BIT_IN_TABLE)
      .FollowedBy(BC_ADVANCE_CP_AND_GOTO)
      // Sequence is only valid if the jump target of ADVANCE_CP_AND_GOTO is the
      // first bytecode in this sequence.
      .IfArgumentEqualsOffset(4, 4, 0)
      .ReplaceWith(BC_SKIP_UNTIL_BIT_IN_TABLE)
      .MapArgument(0, 1, 3) // load offset
      .MapArgument(2, 1, 3, 4) // advance by
      .MapArgument(1, 8, 16) // bit table
      .MapArgument(1, 4, 4) // goto when match
      .MapArgument(0, 4, 4) // goto on failure
      .IgnoreArgument(2, 4, 4); // loop jump
  CreateSequence(BC_CHECK_CURRENT_POSITION)
      .FollowedBy(BC_LOAD_CURRENT_CHAR_UNCHECKED)
      .FollowedBy(BC_CHECK_CHAR)
      .FollowedBy(BC_ADVANCE_CP_AND_GOTO)
      // Sequence is only valid if the jump target of ADVANCE_CP_AND_GOTO is the
      // first bytecode in this sequence.
      .IfArgumentEqualsOffset(4, 4, 0)
      .ReplaceWith(BC_SKIP_UNTIL_CHAR_POS_CHECKED)
      .MapArgument(1, 1, 3) // load offset
      .MapArgument(3, 1, 3, 2) // advance_by
      .MapArgument(2, 1, 3, 2) // c
      .MapArgument(0, 1, 3, 4) // eats at least
      .MapArgument(2, 4, 4) // goto when match
      .MapArgument(0, 4, 4) // goto on failure
      .IgnoreArgument(3, 4, 4); // loop jump
  CreateSequence(BC_CHECK_CURRENT_POSITION)
      .FollowedBy(BC_LOAD_CURRENT_CHAR_UNCHECKED)
      .FollowedBy(BC_AND_CHECK_CHAR)
      .FollowedBy(BC_ADVANCE_CP_AND_GOTO)
      // Sequence is only valid if the jump target of ADVANCE_CP_AND_GOTO is the
      // first bytecode in this sequence.
      .IfArgumentEqualsOffset(4, 4, 0)
      .ReplaceWith(BC_SKIP_UNTIL_CHAR_AND)
      .MapArgument(1, 1, 3) // load offset
      .MapArgument(3, 1, 3, 2) // advance_by
      .MapArgument(2, 1, 3, 2) // c
      .MapArgument(2, 4, 4) // mask
      .MapArgument(0, 1, 3, 4) // eats at least
      .MapArgument(2, 8, 4) // goto when match
      .MapArgument(0, 4, 4) // goto on failure
      .IgnoreArgument(3, 4, 4); // loop jump
  // TODO(pthier): It might make sense for short sequences like this one to only
  // optimize them if the resulting optimization is not longer than the current
  // one. This could be the case if there are jumps inside the sequence and we
  // have to replicate parts of the sequence. A method to mark such sequences
  // might be useful.
  CreateSequence(BC_LOAD_CURRENT_CHAR)
      .FollowedBy(BC_CHECK_CHAR)
      .FollowedBy(BC_ADVANCE_CP_AND_GOTO)
      // Sequence is only valid if the jump target of ADVANCE_CP_AND_GOTO is the
      // first bytecode in this sequence.
      .IfArgumentEqualsOffset(4, 4, 0)
      .ReplaceWith(BC_SKIP_UNTIL_CHAR)
      .MapArgument(0, 1, 3) // load offset
      .MapArgument(2, 1, 3, 2) // advance by
      .MapArgument(1, 1, 3, 2) // character
      .MapArgument(1, 4, 4) // goto when match
      .MapArgument(0, 4, 4) // goto on failure
      .IgnoreArgument(2, 4, 4); // loop jump
  CreateSequence(BC_LOAD_CURRENT_CHAR)
      .FollowedBy(BC_CHECK_CHAR)
      .FollowedBy(BC_CHECK_CHAR)
      // Sequence is only valid if the jump targets of both CHECK_CHAR bytecodes
      // are equal.
      .IfArgumentEqualsValueAtOffset(4, 4, 1, 4, 4)
      .FollowedBy(BC_ADVANCE_CP_AND_GOTO)
      // Sequence is only valid if the jump target of ADVANCE_CP_AND_GOTO is the
      // first bytecode in this sequence.
      .IfArgumentEqualsOffset(4, 4, 0)
      .ReplaceWith(BC_SKIP_UNTIL_CHAR_OR_CHAR)
      .MapArgument(0, 1, 3) // load offset
      .MapArgument(3, 1, 3, 4) // advance by
      .MapArgument(1, 1, 3, 2) // character 1
      .MapArgument(2, 1, 3, 2) // character 2
      .MapArgument(1, 4, 4) // goto when match
      .MapArgument(0, 4, 4) // goto on failure
      .IgnoreArgument(2, 4, 4) // goto when match 2
      .IgnoreArgument(3, 4, 4); // loop jump
  CreateSequence(BC_LOAD_CURRENT_CHAR)
      .FollowedBy(BC_CHECK_GT)
      // Sequence is only valid if the jump target of CHECK_GT is the first
      // bytecode AFTER the whole sequence.
      .IfArgumentEqualsOffset(4, 4, 56)
      .FollowedBy(BC_CHECK_BIT_IN_TABLE)
      // Sequence is only valid if the jump target of CHECK_BIT_IN_TABLE is
      // the ADVANCE_CP_AND_GOTO bytecode at the end of the sequence.
      .IfArgumentEqualsOffset(4, 4, 48)
      .FollowedBy(BC_GOTO)
      // Sequence is only valid if the jump target of GOTO is the same as the
      // jump target of CHECK_GT (i.e. both jump to the first bytecode AFTER the
      // whole sequence.
      .IfArgumentEqualsValueAtOffset(4, 4, 1, 4, 4)
      .FollowedBy(BC_ADVANCE_CP_AND_GOTO)
      // Sequence is only valid if the jump target of ADVANCE_CP_AND_GOTO is the
      // first bytecode in this sequence.
      .IfArgumentEqualsOffset(4, 4, 0)
      .ReplaceWith(BC_SKIP_UNTIL_GT_OR_NOT_BIT_IN_TABLE)
      .MapArgument(0, 1, 3) // load offset
      .MapArgument(4, 1, 3, 2) // advance by
      .MapArgument(1, 1, 3, 2) // character
      .MapArgument(2, 8, 16) // bit table
      .MapArgument(1, 4, 4) // goto when match
      .MapArgument(0, 4, 4) // goto on failure
      .IgnoreArgument(2, 4, 4) // indirect loop jump
      .IgnoreArgument(3, 4, 4) // jump out of loop
      .IgnoreArgument(4, 4, 4); // loop jump
}
References CreateSequence(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::FollowedBy(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::IfArgumentEqualsOffset(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::IfArgumentEqualsValueAtOffset(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::IgnoreArgument(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::MapArgument(), and v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::ReplaceWith().
Referenced by RegExpBytecodePeephole().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::DISALLOW_IMPLICIT_CONSTRUCTORS (RegExpBytecodePeephole) [private]
EmitArgument()
void v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::EmitArgument (int start_pc, const uint8_t * bytecode, BytecodeArgumentMapping arg) [private]
Definition at line 936 of file regexp-bytecode-peephole.cc.
                                                                       {
  int arg_pos = start_pc + arg.offset;
  switch (arg.length) {
    case 1:
      DCHECK_EQ(arg.new_length, arg.length);
      EmitValue(GetValue<uint8_t>(bytecode, arg_pos));
      break;
    case 2:
      DCHECK_EQ(arg.new_length, arg.length);
      EmitValue(GetValue<uint16_t>(bytecode, arg_pos));
      break;
    case 3: {
      // Length 3 only occurs in 'packed' arguments where the lowermost byte is
      // the current bytecode, and the remaining 3 bytes are the packed value.
      //
      // We load 4 bytes from position - 1 and shift out the bytecode.
#ifdef V8_TARGET_BIG_ENDIAN
      UNIMPLEMENTED();
      int32_t val = 0;
#else
      int32_t val = GetValue<int32_t>(bytecode, arg_pos - 1) >> kBitsPerByte;
#endif // V8_TARGET_BIG_ENDIAN
      switch (arg.new_length) {
        case 2:
          EmitValue<uint16_t>(val);
          break;
        case 3: {
          // Pack with previously emitted value.
          auto prev_val =
              GetValue<int32_t>(&(*optimized_bytecode_buffer_.begin()),
                                Length() - sizeof(uint32_t));
#ifdef V8_TARGET_BIG_ENDIAN
      UNIMPLEMENTED();
      USE(prev_val);
#else
          DCHECK_EQ(prev_val & 0xFFFFFF00, 0);
          OverwriteValue<uint32_t>(
              pc() - sizeof(uint32_t),
              (static_cast<uint32_t>(val) << 8) | (prev_val & 0xFF));
#endif // V8_TARGET_BIG_ENDIAN
          break;
        }
        case 4:
          EmitValue<uint32_t>(val);
          break;
      }
      break;
    }
    case 4:
      DCHECK_EQ(arg.new_length, arg.length);
      EmitValue(GetValue<uint32_t>(bytecode, arg_pos));
      break;
    case 8:
      DCHECK_EQ(arg.new_length, arg.length);
      EmitValue(GetValue<uint64_t>(bytecode, arg_pos));
      break;
    default:
      CopyRangeToOutput(bytecode, arg_pos,
                        std::min(arg.length, arg.new_length));
      if (arg.length < arg.new_length) {
        SetRange(0x00, arg.new_length - arg.length);
      }
      break;
  }
}
References v8::internal::ZoneVector< T >::begin(), CopyRangeToOutput(), DCHECK_EQ, EmitValue(), v8::internal::kBitsPerByte, v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeArgument::length, Length(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeArgumentMapping::new_length, v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeArgument::offset, optimized_bytecode_buffer_, pc(), SetRange(), v8::internal::UNIMPLEMENTED(), and USE.
Referenced by EmitOptimization().
EmitOptimization()
void v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::EmitOptimization (int start_pc, const uint8_t * bytecode, const BytecodeSequenceNode & last_node) [private]
Definition at line 684 of file regexp-bytecode-peephole.cc.
                                           {
#ifdef DEBUG
  int optimized_start_pc = pc();
#endif
  // Jump sources that are mapped or marked as unused will be deleted at the end
  // of this method. We don't delete them immediately as we might need the
  // information when we have to preserve bytecodes at the end.
  // TODO(pthier): Replace with a stack-allocated data structure.
  ZoneLinkedList<int> delete_jumps = ZoneLinkedList<int>(zone());
  uint32_t bc = last_node.OptimizedBytecode();
  EmitValue(bc);
  for (size_t arg = 0; arg < last_node.ArgumentSize(); arg++) {
    BytecodeArgumentMapping arg_map = last_node.ArgumentMapping(arg);
    int arg_pos = start_pc + arg_map.offset;
    // If we map any jump source we mark the old source for deletion and insert
    // a new jump.
    auto jump_edge_iter = jump_edges_.find(arg_pos);
    if (jump_edge_iter != jump_edges_.end()) {
      int jump_source = jump_edge_iter->first;
      int jump_destination = jump_edge_iter->second;
      // Add new jump edge add current position.
      jump_edges_mapped_.emplace(Length(), jump_destination);
      // Mark old jump edge for deletion.
      delete_jumps.push_back(jump_source);
      // Decrement usage count of jump destination.
      auto jump_count_iter = jump_usage_counts_.find(jump_destination);
      DCHECK(jump_count_iter != jump_usage_counts_.end());
      int& usage_count = jump_count_iter->second;
      --usage_count;
    }
    // TODO(pthier): DCHECK that mapped arguments are never sources of jumps
    // to destinations inside the sequence.
    EmitArgument(start_pc, bytecode, arg_map);
  }
  DCHECK_EQ(pc(), optimized_start_pc +
                      RegExpBytecodeLength(last_node.OptimizedBytecode()));
  // Remove jumps from arguments we ignore.
  if (last_node.HasIgnoredArguments()) {
    for (auto ignored_arg = last_node.ArgumentIgnoredBegin();
         ignored_arg != last_node.ArgumentIgnoredEnd(); ignored_arg++) {
      auto jump_edge_iter = jump_edges_.find(start_pc + ignored_arg->offset);
      if (jump_edge_iter != jump_edges_.end()) {
        int jump_source = jump_edge_iter->first;
        int jump_destination = jump_edge_iter->second;
        // Mark old jump edge for deletion.
        delete_jumps.push_back(jump_source);
        // Decrement usage count of jump destination.
        auto jump_count_iter = jump_usage_counts_.find(jump_destination);
        DCHECK(jump_count_iter != jump_usage_counts_.end());
        int& usage_count = jump_count_iter->second;
        --usage_count;
      }
    }
  }
  int fixup_length = RegExpBytecodeLength(bc) - last_node.SequenceLength();
  // Check if there are any jumps inside the old sequence.
  // If so we have to keep the bytecodes that are jumped to around.
  auto jump_destination_candidate = jump_usage_counts_.upper_bound(start_pc);
  int jump_candidate_destination = jump_destination_candidate->first;
  int jump_candidate_count = jump_destination_candidate->second;
  // Jump destinations only jumped to from inside the sequence will be ignored.
  while (jump_destination_candidate != jump_usage_counts_.end() &&
         jump_candidate_count == 0) {
    ++jump_destination_candidate;
    jump_candidate_destination = jump_destination_candidate->first;
    jump_candidate_count = jump_destination_candidate->second;
  }
  int preserve_from = start_pc + last_node.SequenceLength();
  if (jump_destination_candidate != jump_usage_counts_.end() &&
      jump_candidate_destination < start_pc + last_node.SequenceLength()) {
    preserve_from = jump_candidate_destination;
    // Check if any jump in the sequence we are preserving has a jump
    // destination inside the optimized sequence before the current position we
    // want to preserve. If so we have to preserve all bytecodes starting at
    // this jump destination.
    for (auto jump_iter = jump_edges_.lower_bound(preserve_from);
         jump_iter != jump_edges_.end() &&
         jump_iter->first /* jump source */ <
             start_pc + last_node.SequenceLength();
         ++jump_iter) {
      int jump_destination = jump_iter->second;
      if (jump_destination > start_pc && jump_destination < preserve_from) {
        preserve_from = jump_destination;
      }
    }
    // We preserve everything to the end of the sequence. This is conservative
    // since it would be enough to preserve all bytecodes up to an unconditional
    // jump.
    int preserve_length = start_pc + last_node.SequenceLength() - preserve_from;
    fixup_length += preserve_length;
    // Jumps after the start of the preserved sequence need fixup.
    AddJumpSourceFixup(fixup_length,
                       start_pc + last_node.SequenceLength() - preserve_length);
    // All jump targets after the start of the optimized sequence need to be
    // fixed relative to the length of the optimized sequence including
    // bytecodes we preserved.
    AddJumpDestinationFixup(fixup_length, start_pc + 1);
    // Jumps to the sequence we preserved need absolute fixup as they could
    // occur before or after the sequence.
    SetJumpDestinationFixup(pc() - preserve_from, preserve_from);
    CopyRangeToOutput(bytecode, preserve_from, preserve_length);
  } else {
    AddJumpDestinationFixup(fixup_length, start_pc + 1);
    // Jumps after the end of the old sequence need fixup.
    AddJumpSourceFixup(fixup_length, start_pc + last_node.SequenceLength());
  }
  // Delete jumps we definitely don't need anymore
  for (int del : delete_jumps) {
    if (del < preserve_from) {
      jump_edges_.erase(del);
    }
  }
}
References AddJumpDestinationFixup(), AddJumpSourceFixup(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::ArgumentIgnoredBegin(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::ArgumentIgnoredEnd(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::ArgumentMapping(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::ArgumentSize(), CopyRangeToOutput(), v8::internal::DCHECK(), DCHECK_EQ, EmitArgument(), EmitValue(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::HasIgnoredArguments(), jump_edges_, jump_edges_mapped_, jump_usage_counts_, Length(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeArgument::offset, v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::OptimizedBytecode(), pc(), v8::internal::RegExpBytecodeLength(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::SequenceLength(), SetJumpDestinationFixup(), and zone().
Referenced by TryOptimizeSequence().
EmitValue()
template<typename T >
void v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::EmitValue (T value) [private]
Definition at line 902 of file regexp-bytecode-peephole.cc.
                                              {
  DCHECK(optimized_bytecode_buffer_.begin() + pc() ==
         optimized_bytecode_buffer_.end());
  uint8_t* value_byte_iter = reinterpret_cast<uint8_t*>(&value);
  optimized_bytecode_buffer_.insert(optimized_bytecode_buffer_.end(),
                                    value_byte_iter,
                                    value_byte_iter + sizeof(T));
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::DCHECK(), v8::internal::ZoneVector< T >::end(), v8::internal::ZoneVector< T >::insert(), optimized_bytecode_buffer_, pc(), T, and v8::internal::value.
Referenced by EmitArgument(), and EmitOptimization().
FixJump()
void v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::FixJump (int jump_source, int jump_destination) [private]
Definition at line 878 of file regexp-bytecode-peephole.cc.
                                                                          {
  int fixed_jump_destination =
      jump_destination +
      (--jump_destination_fixups_.upper_bound(jump_destination))->second;
  DCHECK_LT(fixed_jump_destination, Length());
#ifdef DEBUG
  // TODO(pthier): This check could be better if we track the bytecodes
  // actually used and check if we jump to one of them.
  uint8_t jump_bc = optimized_bytecode_buffer_[fixed_jump_destination];
  DCHECK_GT(jump_bc, 0);
  DCHECK_LT(jump_bc, kRegExpBytecodeCount);
#endif
  if (jump_destination != fixed_jump_destination) {
    OverwriteValue<uint32_t>(jump_source, fixed_jump_destination);
  }
}
References DCHECK_GT, DCHECK_LT, jump_destination_fixups_, v8::internal::kRegExpBytecodeCount, Length(), and optimized_bytecode_buffer_.
Referenced by FixJumps().
FixJumps()
void v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::FixJumps () [private]
Definition at line 847 of file regexp-bytecode-peephole.cc.
                                      {
  int position_fixup = 0;
  // Next position where fixup changes.
  auto next_source_fixup = jump_source_fixups_.lower_bound(0);
  int next_source_fixup_offset = next_source_fixup->first;
  int next_source_fixup_value = next_source_fixup->second;
  for (auto jump_edge : jump_edges_) {
    int jump_source = jump_edge.first;
    int jump_destination = jump_edge.second;
    while (jump_source >= next_source_fixup_offset) {
      position_fixup = next_source_fixup_value;
      ++next_source_fixup;
      next_source_fixup_offset = next_source_fixup->first;
      next_source_fixup_value = next_source_fixup->second;
    }
    jump_source += position_fixup;
    FixJump(jump_source, jump_destination);
  }
  // Mapped jump edges don't need source fixups, as the position already is an
  // offset in the new bytecode.
  for (auto jump_edge : jump_edges_mapped_) {
    int jump_source = jump_edge.first;
    int jump_destination = jump_edge.second;
    FixJump(jump_source, jump_destination);
  }
}
References FixJump(), jump_edges_, jump_edges_mapped_, and jump_source_fixups_.
Referenced by OptimizeBytecode().
Length()
int v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::Length () const
Definition at line 648 of file regexp-bytecode-peephole.cc.
{ return pc(); }
References pc().
Referenced by CopyOptimizedBytecode(), EmitArgument(), EmitOptimization(), and FixJump().
OptimizeBytecode()
bool v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::OptimizeBytecode (const uint8_t * bytecode, int length)
Definition at line 619 of file regexp-bytecode-peephole.cc.
                                                          {
  int old_pc = 0;
  bool did_optimize = false;
  while (old_pc < length) {
    int replaced_len = TryOptimizeSequence(bytecode, length, old_pc);
    if (replaced_len > 0) {
      old_pc += replaced_len;
      did_optimize = true;
    } else {
      int bc = bytecode[old_pc];
      int bc_len = RegExpBytecodeLength(bc);
      CopyRangeToOutput(bytecode, old_pc, bc_len);
      old_pc += bc_len;
    }
  }
  if (did_optimize) {
    FixJumps();
  }
  return did_optimize;
}
References CopyRangeToOutput(), FixJumps(), v8::internal::length, v8::internal::RegExpBytecodeLength(), and TryOptimizeSequence().
OverwriteValue()
template<typename T >
void v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::OverwriteValue (int offset, T value) [private]
Definition at line 912 of file regexp-bytecode-peephole.cc.
                                                               {
  uint8_t* value_byte_iter = reinterpret_cast<uint8_t*>(&value);
  uint8_t* value_byte_iter_end = value_byte_iter + sizeof(T);
  while (value_byte_iter < value_byte_iter_end) {
    optimized_bytecode_buffer_[offset++] = *value_byte_iter++;
  }
}
References optimized_bytecode_buffer_, T, and v8::internal::value.
pc()
int v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::pc () const [private]
Definition at line 1004 of file regexp-bytecode-peephole.cc.
                                     {
  DCHECK_LE(optimized_bytecode_buffer_.size(), std::numeric_limits<int>::max());
  return static_cast<int>(optimized_bytecode_buffer_.size());
}
References DCHECK_LE, optimized_bytecode_buffer_, and v8::internal::ZoneVector< T >::size().
Referenced by CopyRangeToOutput(), EmitArgument(), EmitOptimization(), EmitValue(), Length(), and SetRange().
PrepareJumpStructures()
void v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::PrepareJumpStructures (const ZoneUnorderedMap< int, int > & jump_edges) [private]
Definition at line 836 of file regexp-bytecode-peephole.cc.
                                                  {
  for (auto jump_edge : jump_edges) {
    int jump_source = jump_edge.first;
    int jump_destination = jump_edge.second;
    jump_edges_.emplace(jump_source, jump_destination);
    jump_usage_counts_[jump_destination]++;
  }
}
References jump_edges_, and jump_usage_counts_.
Referenced by RegExpBytecodePeephole().
SetJumpDestinationFixup()
void v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::SetJumpDestinationFixup (int fixup, int pos) [private]
Definition at line 826 of file regexp-bytecode-peephole.cc.
                                                                       {
  auto previous_fixup = jump_destination_fixups_.lower_bound(pos);
  DCHECK(previous_fixup != jump_destination_fixups_.end());
  DCHECK(previous_fixup != jump_destination_fixups_.begin());
  int previous_fixup_value = (--previous_fixup)->second;
  jump_destination_fixups_.emplace(pos, fixup);
  jump_destination_fixups_.emplace(pos + 1, previous_fixup_value);
}
References v8::internal::DCHECK(), and jump_destination_fixups_.
Referenced by EmitOptimization().
SetRange()
void v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::SetRange (uint8_t value, int count) [private]
Definition at line 929 of file regexp-bytecode-peephole.cc.
                                                              {
  DCHECK(optimized_bytecode_buffer_.begin() + pc() ==
         optimized_bytecode_buffer_.end());
  optimized_bytecode_buffer_.insert(optimized_bytecode_buffer_.end(), count,
                                    value);
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::DCHECK(), v8::internal::ZoneVector< T >::end(), v8::internal::ZoneVector< T >::insert(), optimized_bytecode_buffer_, pc(), and v8::internal::value.
Referenced by EmitArgument().
TryOptimizeSequence()
int v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::TryOptimizeSequence (const uint8_t * bytecode, int bytecode_length, int start_pc) [private]
Definition at line 657 of file regexp-bytecode-peephole.cc.
                                                              {
  BytecodeSequenceNode* seq_node = sequences_;
  BytecodeSequenceNode* valid_seq_end = nullptr;
  int current_pc = start_pc;
  // Check for the longest valid sequence matching any of the pre-defined
  // sequences in the Trie data structure.
  while (current_pc < bytecode_length) {
    seq_node = seq_node->Find(bytecode[current_pc]);
    if (seq_node == nullptr) break;
    if (!seq_node->CheckArguments(bytecode, start_pc)) break;
    if (seq_node->IsSequence()) valid_seq_end = seq_node;
    current_pc += RegExpBytecodeLength(bytecode[current_pc]);
  }
  if (valid_seq_end) {
    EmitOptimization(start_pc, bytecode, *valid_seq_end);
    return valid_seq_end->SequenceLength();
  }
  return 0;
}
References v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::CheckArguments(), EmitOptimization(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::Find(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::IsSequence(), v8::internal::RegExpBytecodeLength(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::SequenceLength(), and sequences_.
Referenced by OptimizeBytecode().
zone()
Zone * v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::zone () const [private]
Definition at line 1009 of file regexp-bytecode-peephole.cc.
{ return zone_; }
References zone_.
Referenced by EmitOptimization().
Member Data Documentation
jump_destination_fixups_
ZoneMap<int, int> v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::jump_destination_fixups_ [private]
Definition at line 250 of file regexp-bytecode-peephole.cc.
Referenced by AddJumpDestinationFixup(), AddSentinelFixups(), FixJump(), and SetJumpDestinationFixup().
jump_edges_
ZoneMap<int, int> v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::jump_edges_ [private]
Definition at line 232 of file regexp-bytecode-peephole.cc.
Referenced by EmitOptimization(), FixJumps(), and PrepareJumpStructures().
jump_edges_mapped_
ZoneMap<int, int> v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::jump_edges_mapped_ [private]
Definition at line 236 of file regexp-bytecode-peephole.cc.
Referenced by EmitOptimization(), and FixJumps().
jump_source_fixups_
ZoneMap<int, int> v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::jump_source_fixups_ [private]
Definition at line 244 of file regexp-bytecode-peephole.cc.
Referenced by AddJumpSourceFixup(), AddSentinelFixups(), and FixJumps().
jump_usage_counts_
ZoneMap<int, int> v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::jump_usage_counts_ [private]
Definition at line 240 of file regexp-bytecode-peephole.cc.
Referenced by EmitOptimization(), and PrepareJumpStructures().
optimized_bytecode_buffer_
ZoneVector<uint8_t> v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::optimized_bytecode_buffer_ [private]
Definition at line 227 of file regexp-bytecode-peephole.cc.
Referenced by CopyOptimizedBytecode(), CopyRangeToOutput(), EmitArgument(), EmitValue(), FixJump(), OverwriteValue(), pc(), RegExpBytecodePeephole(), and SetRange().
sequences_
BytecodeSequenceNode* v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::sequences_ [private]
Definition at line 228 of file regexp-bytecode-peephole.cc.
Referenced by CreateSequence(), and TryOptimizeSequence().
zone_
Zone* v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::zone_ [private]
Definition at line 252 of file regexp-bytecode-peephole.cc.
Referenced by zone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-bytecode-peephole.cc