v8::internal::Genesis Class Reference
Classes
class ExtensionStates
Public Member Functions
Genesis (Isolate *isolate, MaybeDirectHandle< JSGlobalProxy > maybe_global_proxy, v8::Local< v8::ObjectTemplate > global_proxy_template, size_t context_snapshot_index, DeserializeEmbedderFieldsCallback embedder_fields_deserializer, v8::MicrotaskQueue *microtask_queue)
Genesis (Isolate *isolate, MaybeDirectHandle< JSGlobalProxy > maybe_global_proxy, v8::Local< v8::ObjectTemplate > global_proxy_template)
~Genesis ()=default
Isolate * isolate () const
Factory * factory () const
Builtins * builtins () const
Heap * heap () const
DirectHandle< NativeContext > result ()
DirectHandle< JSGlobalProxy > global_proxy ()
Private Types
enum ArrayBufferKind { ARRAY_BUFFER
, SHARED_ARRAY_BUFFER
 }
enum ExtensionTraversalState { UNVISITED
, VISITED
, INSTALLED
 }
Private Member Functions
DirectHandle< NativeContext > native_context ()
void CreateRoots ()
DirectHandle< JSFunction > CreateEmptyFunction ()
DirectHandle< JSFunction > GetThrowTypeErrorIntrinsic ()
void CreateSloppyModeFunctionMaps (DirectHandle< JSFunction > empty)
void CreateStrictModeFunctionMaps (DirectHandle< JSFunction > empty)
void CreateObjectFunction (DirectHandle< JSFunction > empty)
void CreateIteratorMaps (DirectHandle< JSFunction > empty)
void CreateAsyncIteratorMaps (DirectHandle< JSFunction > empty)
void CreateAsyncFunctionMaps (DirectHandle< JSFunction > empty)
void CreateJSProxyMaps ()
void AddRestrictedFunctionProperties (DirectHandle< JSFunction > empty)
DirectHandle< JSGlobalObject > CreateNewGlobals (v8::Local< v8::ObjectTemplate > global_proxy_template, DirectHandle< JSGlobalProxy > global_proxy)
void HookUpGlobalObject (DirectHandle< JSGlobalObject > global_object)
void HookUpGlobalProxy (DirectHandle< JSGlobalProxy > global_proxy)
void InstallGlobalThisBinding ()
void InitializeGlobal (DirectHandle< JSGlobalObject > global_object, DirectHandle< JSFunction > empty_function)
void InitializeExperimentalGlobal ()
void InitializeIteratorFunctions ()
void InitializeCallSiteBuiltins ()
void InitializeConsole (DirectHandle< JSObject > extras_binding)
void InitializeGlobal_regexp_linear_flag ()
void InitializeGlobal_sharedarraybuffer ()
DirectHandle< JSFunction > CreateArrayBuffer (DirectHandle< String > name, ArrayBufferKind array_buffer_kind)
bool InstallABunchOfRandomThings ()
bool InstallExtrasBindings ()
DirectHandle< JSFunction > InstallTypedArray (const char *name, ElementsKind elements_kind, InstanceType constructor_type, int rab_gsab_initial_map_index)
void InitializeMapCaches ()
bool ConfigureApiObject (DirectHandle< JSObject > object, DirectHandle< ObjectTemplateInfo > object_template)
bool ConfigureGlobalObject (v8::Local< v8::ObjectTemplate > global_proxy_template)
void TransferObject (DirectHandle< JSObject > from, DirectHandle< JSObject > to)
void TransferNamedProperties (DirectHandle< JSObject > from, DirectHandle< JSObject > to)
void TransferIndexedProperties (DirectHandle< JSObject > from, DirectHandle< JSObject > to)
DirectHandle< Map > CreateInitialMapForArraySubclass (int size, int inobject_properties)
Static Private Member Functions
static bool InstallExtensions (Isolate *isolate, DirectHandle< Context > native_context, v8::ExtensionConfiguration *extensions)
static bool InstallAutoExtensions (Isolate *isolate, ExtensionStates *extension_states)
static bool InstallRequestedExtensions (Isolate *isolate, v8::ExtensionConfiguration *extensions, ExtensionStates *extension_states)
static bool InstallExtension (Isolate *isolate, const char *name, ExtensionStates *extension_states)
static bool InstallExtension (Isolate *isolate, v8::RegisteredExtension *current, ExtensionStates *extension_states)
static bool InstallSpecialObjects (Isolate *isolate, DirectHandle< NativeContext > native_context)
static bool CompileExtension (Isolate *isolate, v8::Extension *extension)
Private Attributes
Isolate * isolate_
DirectHandle< NativeContext > result_
DirectHandle< NativeContext > native_context_
DirectHandle< JSGlobalProxy > global_proxy_
DirectHandle< JSFunction > restricted_properties_thrower_
BootstrapperActive active_
Friends
class Bootstrapper
Detailed Description
Definition at line 183 of file bootstrapper.cc.
Member Enumeration Documentation
ArrayBufferKind
enum v8::internal::Genesis::ArrayBufferKind [private]
Enumerator
ARRAY_BUFFER
SHARED_ARRAY_BUFFER
Definition at line 269 of file bootstrapper.cc.
{ ARRAY_BUFFER, SHARED_ARRAY_BUFFER };
ExtensionTraversalState
enum v8::internal::Genesis::ExtensionTraversalState [private]
Enumerator
UNVISITED
VISITED
INSTALLED
Definition at line 282 of file bootstrapper.cc.
{ UNVISITED, VISITED, INSTALLED };
Constructor & Destructor Documentation
Genesis() [1/2]
v8::internal::Genesis::Genesis (Isolate * isolate, MaybeDirectHandle< JSGlobalProxy > maybe_global_proxy, v8::Local< v8::ObjectTemplate > global_proxy_template, size_t context_snapshot_index, DeserializeEmbedderFieldsCallback embedder_fields_deserializer, v8::MicrotaskQueue * microtask_queue)
Definition at line 6928 of file bootstrapper.cc.
    : isolate_(isolate), active_(isolate->bootstrapper()) {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kGenesis);
  result_ = {};
  global_proxy_ = {};
  // Before creating the roots we must save the context and restore it
  // on all function exits.
  SaveContext saved_context(isolate);
  // The deserializer needs to hook up references to the global proxy.
  // Create an uninitialized global proxy now if we don't have one
  // and initialize it later in CreateNewGlobals.
  DirectHandle<JSGlobalProxy> global_proxy;
  if (!maybe_global_proxy.ToHandle(&global_proxy)) {
    int instance_size = 0;
    if (context_snapshot_index > 0) {
      // The global proxy function to reinitialize this global proxy is in the
      // context that is yet to be deserialized. We need to prepare a global
      // proxy of the correct size.
      Tagged<Object> size =
          isolate->heap()->serialized_global_proxy_sizes()->get(
              static_cast<int>(context_snapshot_index) -
              SnapshotCreatorImpl::kFirstAddtlContextIndex);
      instance_size = Smi::ToInt(size);
    } else {
      instance_size = JSGlobalProxy::SizeWithEmbedderFields(
          global_proxy_template.IsEmpty()
              ? 0
              : global_proxy_template->InternalFieldCount());
    }
    global_proxy =
        isolate->factory()->NewUninitializedJSGlobalProxy(instance_size);
  }
  // We can only de-serialize a context if the isolate was initialized from
  // a snapshot. Otherwise we have to build the context from scratch.
  // Also create a context from scratch to expose natives, if required by flag.
  DCHECK(native_context_.is_null());
  if (isolate->initialized_from_snapshot()) {
    DirectHandle<Context> context;
    if (Snapshot::NewContextFromSnapshot(isolate, global_proxy,
                                         context_snapshot_index,
                                         embedder_fields_deserializer)
            .ToHandle(&context)) {
      native_context_ = Cast<NativeContext>(context);
    }
  }
  if (!native_context().is_null()) {
    AddToWeakNativeContextList(isolate, *native_context());
    isolate->set_context(*native_context());
    // If no global proxy template was passed in, simply use the global in the
    // snapshot. If a global proxy template was passed in it's used to recreate
    // the global object and its prototype chain, and the data and the accessor
    // properties from the deserialized global are copied onto it.
    if (context_snapshot_index == 0 && !global_proxy_template.IsEmpty()) {
      DirectHandle<JSGlobalObject> global_object =
          CreateNewGlobals(global_proxy_template, global_proxy);
      HookUpGlobalObject(global_object);
      if (!ConfigureGlobalObject(global_proxy_template)) return;
    } else {
      // The global proxy needs to be integrated into the native context.
      HookUpGlobalProxy(global_proxy);
    }
    DCHECK_EQ(global_proxy->GetCreationContext(), *native_context());
    DCHECK(!global_proxy->IsDetachedFrom(isolate,
                                         native_context()->global_object()));
  } else {
    DCHECK(native_context().is_null());
    Isolate::EnableRoAllocationForSnapshotScope enable_ro_allocation(isolate);
    base::ElapsedTimer timer;
    if (v8_flags.profile_deserialization) timer.Start();
    DCHECK_EQ(0u, context_snapshot_index);
    // We get here if there was no context snapshot.
    CreateRoots();
    MathRandom::InitializeContext(isolate, native_context());
    DirectHandle<JSFunction> empty_function = CreateEmptyFunction();
    CreateSloppyModeFunctionMaps(empty_function);
    CreateStrictModeFunctionMaps(empty_function);
    CreateObjectFunction(empty_function);
    CreateIteratorMaps(empty_function);
    CreateAsyncIteratorMaps(empty_function);
    CreateAsyncFunctionMaps(empty_function);
    DirectHandle<JSGlobalObject> global_object =
        CreateNewGlobals(global_proxy_template, global_proxy);
    InitializeMapCaches();
    InitializeGlobal(global_object, empty_function);
    InitializeIteratorFunctions();
    InitializeCallSiteBuiltins();
    if (!InstallABunchOfRandomThings()) return;
    if (!InstallExtrasBindings()) return;
    if (!ConfigureGlobalObject(global_proxy_template)) return;
#ifdef V8_ENABLE_WEBASSEMBLY
    WasmJs::PrepareForSnapshot(isolate);
#endif // V8_ENABLE_WEBASSEMBLY
    if (v8_flags.profile_deserialization) {
      double ms = timer.Elapsed().InMillisecondsF();
      PrintF("[Initializing context from scratch took %0.3f ms]\n", ms);
    }
  }
  native_context()->set_microtask_queue(
      isolate, microtask_queue ? static_cast<MicrotaskQueue*>(microtask_queue)
                               : isolate->default_microtask_queue());
  // Install experimental natives. Do not include them into the
  // snapshot as we should be able to turn them off at runtime. Re-installing
  // them after they have already been deserialized would also fail.
  if (!isolate->serializer_enabled()) {
    InitializeExperimentalGlobal();
    // Store String.prototype's map again in case it has been changed by
    // experimental natives.
    DirectHandle<JSFunction> string_function(
        native_context()->string_function(), isolate);
    Tagged<JSObject> string_function_prototype =
        Cast<JSObject>(string_function->initial_map()->prototype());
    DCHECK(string_function_prototype->HasFastProperties());
    native_context()->set_string_function_prototype_map(
        string_function_prototype->map());
  }
  if (v8_flags.disallow_code_generation_from_strings) {
    native_context()->set_allow_code_gen_from_strings(
        ReadOnlyRoots(isolate).false_value());
  }
  // We created new functions, which may require debug instrumentation.
  if (isolate->debug()->is_active()) {
    isolate->debug()->InstallDebugBreakTrampoline();
  }
  native_context()->ResetErrorsThrown();
  result_ = native_context();
}
References v8::internal::AddToWeakNativeContextList(), ConfigureGlobalObject(), CreateAsyncFunctionMaps(), CreateAsyncIteratorMaps(), CreateEmptyFunction(), CreateIteratorMaps(), CreateNewGlobals(), CreateObjectFunction(), CreateRoots(), CreateSloppyModeFunctionMaps(), CreateStrictModeFunctionMaps(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::debug(), v8::base::ElapsedTimer::Elapsed(), v8::internal::Isolate::factory(), global_proxy(), global_proxy_, v8::internal::Isolate::heap(), HookUpGlobalObject(), HookUpGlobalProxy(), InitializeCallSiteBuiltins(), v8::internal::MathRandom::InitializeContext(), v8::internal::Isolate::initialized_from_snapshot(), InitializeExperimentalGlobal(), InitializeGlobal(), InitializeIteratorFunctions(), InitializeMapCaches(), v8::base::TimeDelta::InMillisecondsF(), InstallABunchOfRandomThings(), v8::internal::Debug::InstallDebugBreakTrampoline(), InstallExtrasBindings(), v8::internal::Debug::is_active(), v8::api_internal::IndirectHandleBase::IsEmpty(), isolate(), v8::internal::SnapshotCreatorImpl::kFirstAddtlContextIndex, native_context(), native_context_, v8::internal::Snapshot::NewContextFromSnapshot(), v8::internal::Factory::NewUninitializedJSGlobalProxy(), v8::internal::WasmJs::PrepareForSnapshot(), v8::internal::PrintF(), RCS_SCOPE, result_, v8::internal::Isolate::serializer_enabled(), v8::internal::Isolate::set_context(), size(), v8::internal::JSGlobalProxy::SizeWithEmbedderFields(), v8::base::ElapsedTimer::Start(), v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::Smi::ToInt(), and v8::internal::v8_flags.
Genesis() [2/2]
v8::internal::Genesis::Genesis (Isolate * isolate, MaybeDirectHandle< JSGlobalProxy > maybe_global_proxy, v8::Local< v8::ObjectTemplate > global_proxy_template)
Definition at line 7076 of file bootstrapper.cc.
    : isolate_(isolate), active_(isolate->bootstrapper()) {
  result_ = {};
  global_proxy_ = {};
  // Before creating the roots we must save the context and restore it
  // on all function exits.
  SaveContext saved_context(isolate);
  const int proxy_size = JSGlobalProxy::SizeWithEmbedderFields(
      global_proxy_template->InternalFieldCount());
  DirectHandle<JSGlobalProxy> global_proxy;
  if (maybe_global_proxy.ToHandle(&global_proxy)) {
    global_proxy->map()->set_map(isolate, ReadOnlyRoots(isolate).meta_map());
  } else {
    global_proxy = factory()->NewUninitializedJSGlobalProxy(proxy_size);
  }
  // Create a remote object as the global object.
  DirectHandle<ObjectTemplateInfo> global_proxy_data =
      Utils::OpenDirectHandle(*global_proxy_template);
  DirectHandle<FunctionTemplateInfo> global_constructor(
      Cast<FunctionTemplateInfo>(global_proxy_data->constructor()), isolate);
  DirectHandle<ObjectTemplateInfo> global_object_template(
      Cast<ObjectTemplateInfo>(global_constructor->GetPrototypeTemplate()),
      isolate);
  DirectHandle<JSObject> global_object =
      ApiNatives::InstantiateRemoteObject(global_object_template)
          .ToHandleChecked();
  // (Re)initialize the global proxy object.
  DCHECK_EQ(global_proxy_data->embedder_field_count(),
            global_proxy_template->InternalFieldCount());
  DirectHandle<Map> global_proxy_map = factory()->NewContextlessMap(
      JS_GLOBAL_PROXY_TYPE, proxy_size, TERMINAL_FAST_ELEMENTS_KIND);
  global_proxy_map->set_is_access_check_needed(true);
  global_proxy_map->set_may_have_interesting_properties(true);
  // Configure the hidden prototype chain of the global proxy.
  JSObject::ForceSetPrototype(isolate, global_proxy, global_object);
  global_proxy->map()->SetConstructor(*global_constructor);
  global_proxy_ = global_proxy;
}
References DCHECK_EQ, factory(), v8::internal::JSObject::ForceSetPrototype(), global_proxy(), global_proxy_, v8::internal::ApiNatives::InstantiateRemoteObject(), isolate(), v8::internal::Factory::NewContextlessMap(), v8::internal::Factory::NewUninitializedJSGlobalProxy(), v8::Utils::OpenDirectHandle(), result_, v8::internal::JSGlobalProxy::SizeWithEmbedderFields(), v8::internal::TERMINAL_FAST_ELEMENTS_KIND, and v8::internal::MaybeDirectHandle< T >::ToHandle().
 Genesis()
v8::internal::Genesis::~Genesis () [default]
Member Function Documentation
AddRestrictedFunctionProperties()
void v8::internal::Genesis::AddRestrictedFunctionProperties (DirectHandle< JSFunction > empty) [private]
Definition at line 1316 of file bootstrapper.cc.
                                                                            {
  PropertyAttributes rw_attribs = static_cast<PropertyAttributes>(DONT_ENUM);
  DirectHandle<JSFunction> thrower = GetThrowTypeErrorIntrinsic();
  DirectHandle<AccessorPair> accessors = factory()->NewAccessorPair();
  accessors->set_getter(*thrower);
  accessors->set_setter(*thrower);
  DirectHandle<Map> map(empty->map(), isolate());
  ReplaceAccessors(isolate(), map, factory()->arguments_string(), rw_attribs,
                   accessors);
  ReplaceAccessors(isolate(), map, factory()->caller_string(), rw_attribs,
                   accessors);
}
References v8::internal::DONT_ENUM, factory(), GetThrowTypeErrorIntrinsic(), isolate(), v8::internal::FactoryBase< Impl >::NewAccessorPair(), and v8::internal::anonymous_namespace{bootstrapper.cc}::ReplaceAccessors().
Referenced by CreateStrictModeFunctionMaps().
builtins()
Builtins* v8::internal::Genesis::builtins () const [inline]
Definition at line 196 of file bootstrapper.cc.
{ return isolate_->builtins(); }
References v8::internal::Isolate::builtins(), and isolate_.
CompileExtension()
bool v8::internal::Genesis::CompileExtension (Isolate * isolate, v8::Extension * extension) [static], [private]
Definition at line 5144 of file bootstrapper.cc.
                                                                       {
  Factory* factory = isolate->factory();
  HandleScope scope(isolate);
  DirectHandle<SharedFunctionInfo> function_info;
  Handle<String> source =
      isolate->factory()
          ->NewExternalStringFromOneByte(extension->source())
          .ToHandleChecked();
  DCHECK(source->IsOneByteRepresentation());
  // If we can't find the function in the cache, we compile a new
  // function and insert it into the cache.
  base::Vector<const char> name = base::CStrVector(extension->name());
  SourceCodeCache* cache = isolate->bootstrapper()->extensions_cache();
  DirectHandle<Context> context(isolate->context(), isolate);
  DCHECK(IsNativeContext(*context));
  if (!cache->Lookup(isolate, name, &function_info)) {
    Handle<String> script_name =
        factory->NewStringFromUtf8(name).ToHandleChecked();
    ScriptCompiler::CompilationDetails compilation_details;
    MaybeDirectHandle<SharedFunctionInfo> maybe_function_info =
        Compiler::GetSharedFunctionInfoForScriptWithExtension(
            isolate, source, ScriptDetails(script_name), extension,
            ScriptCompiler::kNoCompileOptions, EXTENSION_CODE,
            &compilation_details);
    if (!maybe_function_info.ToHandle(&function_info)) return false;
    cache->Add(isolate, name, function_info);
  }
  // Set up the function context. Conceptually, we should clone the
  // function before overwriting the context but since we're in a
  // single-threaded environment it is not strictly necessary.
  DirectHandle<JSFunction> fun =
      Factory::JSFunctionBuilder{isolate, function_info, context}.Build();
  // Call function using either the runtime object or the global
  // object as the receiver. Provide no parameters.
  DirectHandle<Object> receiver = isolate->global_object();
  DirectHandle<FixedArray> host_defined_options =
      isolate->factory()->empty_fixed_array();
  TryCallScope try_call_scope(isolate);
  // Blink generally assumes that context creation (where extension compilation
  // is part) cannot be interrupted.
  PostponeInterruptsScope postpone(isolate);
  return !Execution::TryCallScript(isolate, fun, receiver, host_defined_options)
              .is_null();
}
References v8::internal::SourceCodeCache::Add(), v8::internal::Isolate::bootstrapper(), v8::internal::Isolate::context(), v8::base::CStrVector(), v8::internal::DCHECK(), v8::internal::EXTENSION_CODE, v8::internal::Bootstrapper::extensions_cache(), v8::internal::Isolate::factory(), factory(), v8::internal::Compiler::GetSharedFunctionInfoForScriptWithExtension(), v8::internal::Isolate::global_object(), isolate(), v8::ScriptCompiler::kNoCompileOptions, v8::internal::SourceCodeCache::Lookup(), v8::Extension::name(), v8::internal::name, v8::internal::Factory::NewExternalStringFromOneByte(), v8::internal::Factory::NewStringFromUtf8(), v8::Extension::source(), v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::Execution::TryCallScript().
Referenced by InstallExtension().
ConfigureApiObject()
bool v8::internal::Genesis::ConfigureApiObject (DirectHandle< JSObject > object, DirectHandle< ObjectTemplateInfo > object_template) [private]
Definition at line 6709 of file bootstrapper.cc.
                                                      {
  DCHECK(!object_template.is_null());
  DCHECK(Cast<FunctionTemplateInfo>(object_template->constructor())
             ->IsTemplateFor(object->map()));
  MaybeDirectHandle<JSObject> maybe_obj =
      ApiNatives::InstantiateObject(isolate_, object_template);
  DirectHandle<JSObject> instantiated_template;
  if (!maybe_obj.ToHandle(&instantiated_template)) {
    DCHECK(isolate()->has_exception());
    DirectHandle<String> message =
        ErrorUtils::ToString(isolate_,
                             direct_handle(isolate_->exception(), isolate_))
            .ToHandleChecked();
    base::OS::PrintError(
        "V8 Error: Exception in Genesis::ConfigureApiObject: %s\n",
        message->ToCString().get());
    isolate()->clear_exception();
    return false;
  }
  TransferObject(instantiated_template, object);
  return true;
}
References v8::internal::Isolate::clear_exception(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::exception(), v8::internal::ApiNatives::InstantiateObject(), v8::internal::DirectHandle< T >::is_null(), isolate(), isolate_, v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::internal::ErrorUtils::ToString(), and TransferObject().
Referenced by ConfigureGlobalObject().
ConfigureGlobalObject()
bool v8::internal::Genesis::ConfigureGlobalObject (v8::Local< v8::ObjectTemplate > global_proxy_template) [private]
Definition at line 6669 of file bootstrapper.cc.
                                                     {
  DirectHandle<JSObject> global_proxy(native_context()->global_proxy(),
                                      isolate());
  DirectHandle<JSObject> global_object(native_context()->global_object(),
                                       isolate());
  if (!global_proxy_template.IsEmpty()) {
    // Configure the global proxy object.
    DirectHandle<ObjectTemplateInfo> global_proxy_data =
        v8::Utils::OpenDirectHandle(*global_proxy_template);
    if (!ConfigureApiObject(global_proxy, global_proxy_data)) {
      base::OS::PrintError("V8 Error: Failed to configure global_proxy_data\n");
      return false;
    }
    // Configure the global object.
    DirectHandle<FunctionTemplateInfo> proxy_constructor(
        Cast<FunctionTemplateInfo>(global_proxy_data->constructor()),
        isolate());
    if (!IsUndefined(proxy_constructor->GetPrototypeTemplate(), isolate())) {
      DirectHandle<ObjectTemplateInfo> global_object_data(
          Cast<ObjectTemplateInfo>(proxy_constructor->GetPrototypeTemplate()),
          isolate());
      if (!ConfigureApiObject(global_object, global_object_data)) {
        base::OS::PrintError(
            "V8 Error: Failed to configure global_object_data\n");
        return false;
      }
    }
  }
  JSObject::ForceSetPrototype(isolate(), global_proxy, global_object);
  native_context()->set_array_buffer_map(
      native_context()->array_buffer_fun()->initial_map());
  return true;
}
References ConfigureApiObject(), v8::internal::JSObject::ForceSetPrototype(), global_proxy(), v8::internal::compiler::initial_map, v8::api_internal::IndirectHandleBase::IsEmpty(), isolate(), native_context(), and v8::Utils::OpenDirectHandle().
Referenced by Genesis().
CreateArrayBuffer()
DirectHandle< JSFunction > v8::internal::Genesis::CreateArrayBuffer (DirectHandle< String > name, ArrayBufferKind array_buffer_kind) [private]
Definition at line 5970 of file bootstrapper.cc.
                                                                  {
  // Create the %ArrayBufferPrototype%
  // Setup the {prototype} with the given {name} for @@toStringTag.
  DirectHandle<JSObject> prototype = factory()->NewJSObject(
      isolate()->object_function(), AllocationType::kOld);
  InstallToStringTag(isolate(), prototype, name);
  // Allocate the constructor with the given {prototype}.
  DirectHandle<JSFunction> array_buffer_fun =
      CreateFunction(isolate(), name, JS_ARRAY_BUFFER_TYPE,
                     JSArrayBuffer::kSizeWithEmbedderFields, 0, prototype,
                     Builtin::kArrayBufferConstructor, 1, kAdapt);
  // Install the "constructor" property on the {prototype}.
  JSObject::AddProperty(isolate(), prototype, factory()->constructor_string(),
                        array_buffer_fun, DONT_ENUM);
  switch (array_buffer_kind) {
    case ARRAY_BUFFER:
      InstallFunctionWithBuiltinId(isolate(), array_buffer_fun, "isView",
                                   Builtin::kArrayBufferIsView, 1, kAdapt);
      // Install the "byteLength" getter on the {prototype}.
      SimpleInstallGetter(isolate(), prototype, factory()->byte_length_string(),
                          Builtin::kArrayBufferPrototypeGetByteLength, kAdapt);
      SimpleInstallFunction(isolate(), prototype, "slice",
                            Builtin::kArrayBufferPrototypeSlice, 2, kAdapt);
      break;
    case SHARED_ARRAY_BUFFER:
      // Install the "byteLength" getter on the {prototype}.
      SimpleInstallGetter(isolate(), prototype, factory()->byte_length_string(),
                          Builtin::kSharedArrayBufferPrototypeGetByteLength,
                          kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "slice",
                            Builtin::kSharedArrayBufferPrototypeSlice, 2,
                            kAdapt);
      break;
  }
  return array_buffer_fun;
}
References v8::internal::JSObject::AddProperty(), ARRAY_BUFFER, v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunction(), v8::internal::DONT_ENUM, factory(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunctionWithBuiltinId(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallToStringTag(), isolate(), v8::internal::kAdapt, v8::internal::kDontAdapt, v8::internal::kOld, v8::internal::JSArrayBuffer::kSizeWithEmbedderFields, v8::internal::name, v8::internal::Factory::NewJSObject(), v8::internal::prototype, SHARED_ARRAY_BUFFER, v8::internal::SimpleInstallFunction(), and v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleInstallGetter().
Referenced by InitializeGlobal().
CreateAsyncFunctionMaps()
void v8::internal::Genesis::CreateAsyncFunctionMaps (DirectHandle< JSFunction > empty) [private]
Definition at line 1205 of file bootstrapper.cc.
                                                                    {
  // %AsyncFunctionPrototype% intrinsic
  DirectHandle<JSObject> async_function_prototype = factory()->NewJSObject(
      isolate()->object_function(), AllocationType::kOld);
  JSObject::ForceSetPrototype(isolate(), async_function_prototype, empty);
  InstallToStringTag(isolate(), async_function_prototype, "AsyncFunction");
  DirectHandle<Map> map =
      Map::Copy(isolate(), isolate()->strict_function_without_prototype_map(),
                "AsyncFunction");
  Map::SetPrototype(isolate(), map, async_function_prototype);
  native_context()->set_async_function_map(*map);
  map = Map::Copy(isolate(), isolate()->method_with_name_map(),
                  "AsyncFunction with name");
  Map::SetPrototype(isolate(), map, async_function_prototype);
  native_context()->set_async_function_with_name_map(*map);
}
References v8::internal::Map::Copy(), factory(), v8::internal::JSObject::ForceSetPrototype(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallToStringTag(), isolate(), v8::internal::kOld, native_context(), v8::internal::Factory::NewJSObject(), and v8::internal::Map::SetPrototype().
Referenced by Genesis().
CreateAsyncIteratorMaps()
void v8::internal::Genesis::CreateAsyncIteratorMaps (DirectHandle< JSFunction > empty) [private]
Definition at line 1095 of file bootstrapper.cc.
                                                                    {
  // %AsyncIteratorPrototype%
  // proposal-async-iteration/#sec-asynciteratorprototype
  DirectHandle<JSObject> async_iterator_prototype = factory()->NewJSObject(
      isolate()->object_function(), AllocationType::kOld);
  InstallFunctionAtSymbol(
      isolate(), async_iterator_prototype, factory()->async_iterator_symbol(),
      "[Symbol.asyncIterator]", Builtin::kReturnReceiver, 0, kAdapt);
  native_context()->set_initial_async_iterator_prototype(
      *async_iterator_prototype);
  // %AsyncFromSyncIteratorPrototype%
  // proposal-async-iteration/#sec-%asyncfromsynciteratorprototype%-object
  DirectHandle<JSObject> async_from_sync_iterator_prototype =
      factory()->NewJSObject(isolate()->object_function(),
                             AllocationType::kOld);
  SimpleInstallFunction(isolate(), async_from_sync_iterator_prototype, "next",
                        Builtin::kAsyncFromSyncIteratorPrototypeNext, 1,
                        kDontAdapt);
  SimpleInstallFunction(isolate(), async_from_sync_iterator_prototype, "return",
                        Builtin::kAsyncFromSyncIteratorPrototypeReturn, 1,
                        kDontAdapt);
  SimpleInstallFunction(isolate(), async_from_sync_iterator_prototype, "throw",
                        Builtin::kAsyncFromSyncIteratorPrototypeThrow, 1,
                        kDontAdapt);
  InstallToStringTag(isolate(), async_from_sync_iterator_prototype,
                     "Async-from-Sync Iterator");
  JSObject::ForceSetPrototype(isolate(), async_from_sync_iterator_prototype,
                              async_iterator_prototype);
  DirectHandle<Map> async_from_sync_iterator_map =
      factory()->NewContextfulMapForCurrentContext(
          JS_ASYNC_FROM_SYNC_ITERATOR_TYPE,
          JSAsyncFromSyncIterator::kHeaderSize);
  Map::SetPrototype(isolate(), async_from_sync_iterator_map,
                    async_from_sync_iterator_prototype);
  native_context()->set_async_from_sync_iterator_map(
      *async_from_sync_iterator_map);
  // Async Generators
  DirectHandle<JSObject> async_generator_object_prototype =
      factory()->NewJSObject(isolate()->object_function(),
                             AllocationType::kOld);
  DirectHandle<JSObject> async_generator_function_prototype =
      factory()->NewJSObject(isolate()->object_function(),
                             AllocationType::kOld);
  // %AsyncGenerator% / %AsyncGeneratorFunction%.prototype
  JSObject::ForceSetPrototype(isolate(), async_generator_function_prototype,
                              empty);
  // The value of AsyncGeneratorFunction.prototype.prototype is the
  // %AsyncGeneratorPrototype% intrinsic object.
  // This property has the attributes
  // { [[Writable]]: false, [[Enumerable]]: false, [[Configurable]]: true }.
  JSObject::AddProperty(isolate(), async_generator_function_prototype,
                        factory()->prototype_string(),
                        async_generator_object_prototype,
                        static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY));
  JSObject::AddProperty(isolate(), async_generator_object_prototype,
                        factory()->constructor_string(),
                        async_generator_function_prototype,
                        static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY));
  InstallToStringTag(isolate(), async_generator_function_prototype,
                     "AsyncGeneratorFunction");
  // %AsyncGeneratorPrototype%
  JSObject::ForceSetPrototype(isolate(), async_generator_object_prototype,
                              async_iterator_prototype);
  native_context()->set_initial_async_generator_prototype(
      *async_generator_object_prototype);
  InstallToStringTag(isolate(), async_generator_object_prototype,
                     "AsyncGenerator");
  SimpleInstallFunction(isolate(), async_generator_object_prototype, "next",
                        Builtin::kAsyncGeneratorPrototypeNext, 1, kDontAdapt);
  SimpleInstallFunction(isolate(), async_generator_object_prototype, "return",
                        Builtin::kAsyncGeneratorPrototypeReturn, 1, kDontAdapt);
  SimpleInstallFunction(isolate(), async_generator_object_prototype, "throw",
                        Builtin::kAsyncGeneratorPrototypeThrow, 1, kDontAdapt);
  // Create maps for generator functions and their prototypes. Store those
  // maps in the native context. The "prototype" property descriptor is
  // writable, non-enumerable, and non-configurable (as per ES6 draft
  // 04-14-15, section 25.2.4.3).
  // Async Generator functions do not have "caller" or "arguments" accessors.
  DirectHandle<Map> map;
  map = CreateNonConstructorMap(isolate(), isolate()->strict_function_map(),
                                async_generator_function_prototype,
                                "AsyncGeneratorFunction");
  native_context()->set_async_generator_function_map(*map);
  map = CreateNonConstructorMap(
      isolate(), isolate()->strict_function_with_name_map(),
      async_generator_function_prototype, "AsyncGeneratorFunction with name");
  native_context()->set_async_generator_function_with_name_map(*map);
  DirectHandle<JSFunction> object_function(native_context()->object_function(),
                                           isolate());
  DirectHandle<Map> async_generator_object_prototype_map =
      Map::Create(isolate(), 0);
  Map::SetPrototype(isolate(), async_generator_object_prototype_map,
                    async_generator_object_prototype);
  native_context()->set_async_generator_object_prototype_map(
      *async_generator_object_prototype_map);
}
References v8::internal::JSObject::AddProperty(), v8::internal::Map::Create(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateNonConstructorMap(), v8::internal::DONT_ENUM, factory(), v8::internal::JSObject::ForceSetPrototype(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunctionAtSymbol(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallToStringTag(), isolate(), v8::internal::kAdapt, v8::internal::kDontAdapt, v8::internal::kOld, native_context(), v8::internal::Factory::NewContextfulMapForCurrentContext(), v8::internal::Factory::NewJSObject(), v8::internal::READ_ONLY, v8::internal::Map::SetPrototype(), and v8::internal::SimpleInstallFunction().
Referenced by Genesis().
CreateEmptyFunction()
DirectHandle< JSFunction > v8::internal::Genesis::CreateEmptyFunction () [private]
Definition at line 773 of file bootstrapper.cc.
                                                      {
  // Allocate the function map first and then patch the prototype later.
  DirectHandle<Map> empty_function_map =
      factory()->CreateSloppyFunctionMap(FUNCTION_WITHOUT_PROTOTYPE, {});
  empty_function_map->set_is_prototype_map(true);
  DCHECK(!empty_function_map->is_dictionary_map());
  // Allocate the empty function as the prototype for function according to
  // ES#sec-properties-of-the-function-prototype-object
  DirectHandle<JSFunction> empty_function = CreateFunctionForBuiltin(
      isolate(), factory()->empty_string(), empty_function_map,
      Builtin::kEmptyFunction, 0, kDontAdapt);
  empty_function_map->SetConstructor(*empty_function);
  native_context()->set_empty_function(*empty_function);
  // --- E m p t y ---
  DirectHandle<String> source = factory()->InternalizeString("() {}");
  DirectHandle<Script> script = factory()->NewScript(source);
  script->set_type(Script::Type::kNative);
  DirectHandle<WeakFixedArray> infos = factory()->NewWeakFixedArray(2);
  script->set_infos(*infos);
  ReadOnlyRoots roots{isolate()};
  Tagged<SharedFunctionInfo> sfi = empty_function->shared();
  sfi->set_raw_scope_info(roots.empty_function_scope_info());
  sfi->SetScript(isolate(), roots, *script, 1);
  sfi->UpdateFunctionMapIndex();
  return empty_function;
}
References v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltin(), v8::internal::Factory::CreateSloppyFunctionMap(), v8::internal::DCHECK(), factory(), v8::internal::FUNCTION_WITHOUT_PROTOTYPE, v8::internal::Factory::InternalizeString(), isolate(), v8::internal::kDontAdapt, v8::internal::Script::kNative, native_context(), v8::internal::FactoryBase< Impl >::NewScript(), v8::internal::FactoryBase< Impl >::NewWeakFixedArray(), and v8::internal::script.
Referenced by Genesis().
CreateInitialMapForArraySubclass()
DirectHandle< Map > v8::internal::Genesis::CreateInitialMapForArraySubclass (int size, int inobject_properties) [private]
Definition at line 6887 of file bootstrapper.cc.
                                       {
  // Find global.Array.prototype to inherit from.
  DirectHandle<JSFunction> array_constructor(native_context()->array_function(),
                                             isolate());
  DirectHandle<JSObject> array_prototype(
      native_context()->initial_array_prototype(), isolate());
  // Add initial map.
  DirectHandle<Map> initial_map = factory()->NewContextfulMapForCurrentContext(
      JS_ARRAY_TYPE, size, TERMINAL_FAST_ELEMENTS_KIND, inobject_properties);
  initial_map->SetConstructor(*array_constructor);
  // Set prototype on map.
  initial_map->set_has_non_instance_prototype(false);
  Map::SetPrototype(isolate(), initial_map, array_prototype);
  // Update map with length accessor from Array.
  static constexpr int kTheLengthAccessor = 1;
  Map::EnsureDescriptorSlack(isolate(), initial_map,
                             inobject_properties + kTheLengthAccessor);
  // length descriptor.
  {
    Tagged<JSFunction> array_function = native_context()->array_function();
    DirectHandle<DescriptorArray> array_descriptors(
        array_function->initial_map()->instance_descriptors(isolate()),
        isolate());
    DirectHandle<String> length = factory()->length_string();
    InternalIndex old = array_descriptors->SearchWithCache(
        isolate(), *length, array_function->initial_map());
    DCHECK(old.is_found());
    Descriptor d = Descriptor::AccessorConstant(
        length,
        direct_handle(array_descriptors->GetStrongValue(old), isolate()),
        array_descriptors->GetDetails(old).attributes());
    initial_map->AppendDescriptor(isolate(), &d);
  }
  return initial_map;
}
References v8::internal::Descriptor::AccessorConstant(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Map::EnsureDescriptorSlack(), factory(), v8::internal::compiler::initial_map, v8::internal::InternalIndex::is_found(), isolate(), v8::internal::length, native_context(), v8::internal::Factory::NewContextfulMapForCurrentContext(), v8::internal::Map::SetPrototype(), size(), and v8::internal::TERMINAL_FAST_ELEMENTS_KIND.
Referenced by InstallABunchOfRandomThings().
CreateIteratorMaps()
void v8::internal::Genesis::CreateIteratorMaps (DirectHandle< JSFunction > empty) [private]
Definition at line 1009 of file bootstrapper.cc.
                                                               {
  // Create iterator-related meta-objects.
  DirectHandle<JSObject> iterator_prototype = factory()->NewJSObject(
      isolate()->object_function(), AllocationType::kOld);
  InstallFunctionAtSymbol(isolate(), iterator_prototype,
                          factory()->iterator_symbol(), "[Symbol.iterator]",
                          Builtin::kReturnReceiver, 0, kAdapt);
  native_context()->set_initial_iterator_prototype(*iterator_prototype);
  CHECK_NE(iterator_prototype->map().ptr(),
           isolate_->initial_object_prototype()->map().ptr());
  iterator_prototype->map()->set_instance_type(JS_ITERATOR_PROTOTYPE_TYPE);
  DirectHandle<JSObject> generator_object_prototype = factory()->NewJSObject(
      isolate()->object_function(), AllocationType::kOld);
  native_context()->set_initial_generator_prototype(
      *generator_object_prototype);
  JSObject::ForceSetPrototype(isolate(), generator_object_prototype,
                              iterator_prototype);
  DirectHandle<JSObject> generator_function_prototype = factory()->NewJSObject(
      isolate()->object_function(), AllocationType::kOld);
  JSObject::ForceSetPrototype(isolate(), generator_function_prototype, empty);
  InstallToStringTag(isolate(), generator_function_prototype,
                     "GeneratorFunction");
  JSObject::AddProperty(isolate(), generator_function_prototype,
                        factory()->prototype_string(),
                        generator_object_prototype,
                        static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY));
  JSObject::AddProperty(isolate(), generator_object_prototype,
                        factory()->constructor_string(),
                        generator_function_prototype,
                        static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY));
  InstallToStringTag(isolate(), generator_object_prototype, "Generator");
  SimpleInstallFunction(isolate(), generator_object_prototype, "next",
                        Builtin::kGeneratorPrototypeNext, 1, kDontAdapt);
  SimpleInstallFunction(isolate(), generator_object_prototype, "return",
                        Builtin::kGeneratorPrototypeReturn, 1, kDontAdapt);
  SimpleInstallFunction(isolate(), generator_object_prototype, "throw",
                        Builtin::kGeneratorPrototypeThrow, 1, kDontAdapt);
  // Internal version of generator_prototype_next, flagged as non-native such
  // that it doesn't show up in Error traces.
  DirectHandle<JSFunction> generator_next_internal =
      SimpleCreateFunction(isolate(), factory()->next_string(),
                           Builtin::kGeneratorPrototypeNext, 1, kDontAdapt);
  generator_next_internal->shared()->set_native(false);
  native_context()->set_generator_next_internal(*generator_next_internal);
  // Internal version of async module functions, flagged as non-native such
  // that they don't show up in Error traces.
  {
    DirectHandle<JSFunction> async_module_evaluate_internal =
        SimpleCreateFunction(isolate(), factory()->next_string(),
                             Builtin::kAsyncModuleEvaluate, 1, kDontAdapt);
    async_module_evaluate_internal->shared()->set_native(false);
    native_context()->set_async_module_evaluate_internal(
        *async_module_evaluate_internal);
  }
  // Create maps for generator functions and their prototypes. Store those
  // maps in the native context. The "prototype" property descriptor is
  // writable, non-enumerable, and non-configurable (as per ES6 draft
  // 04-14-15, section 25.2.4.3).
  // Generator functions do not have "caller" or "arguments" accessors.
  DirectHandle<Map> map;
  map = CreateNonConstructorMap(isolate(), isolate()->strict_function_map(),
                                generator_function_prototype,
                                "GeneratorFunction");
  native_context()->set_generator_function_map(*map);
  map = CreateNonConstructorMap(
      isolate(), isolate()->strict_function_with_name_map(),
      generator_function_prototype, "GeneratorFunction with name");
  native_context()->set_generator_function_with_name_map(*map);
  DirectHandle<JSFunction> object_function(native_context()->object_function(),
                                           isolate());
  DirectHandle<Map> generator_object_prototype_map = Map::Create(isolate(), 0);
  Map::SetPrototype(isolate(), generator_object_prototype_map,
                    generator_object_prototype);
  native_context()->set_generator_object_prototype_map(
      *generator_object_prototype_map);
}
References v8::internal::JSObject::AddProperty(), CHECK_NE, v8::internal::Map::Create(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateNonConstructorMap(), v8::internal::DONT_ENUM, factory(), v8::internal::JSObject::ForceSetPrototype(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunctionAtSymbol(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallToStringTag(), isolate(), isolate_, v8::internal::kAdapt, v8::internal::kDontAdapt, v8::internal::kOld, native_context(), v8::internal::Factory::NewJSObject(), v8::internal::READ_ONLY, v8::internal::Map::SetPrototype(), v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleCreateFunction(), and v8::internal::SimpleInstallFunction().
Referenced by Genesis().
CreateJSProxyMaps()
void v8::internal::Genesis::CreateJSProxyMaps () [private]
Definition at line 1225 of file bootstrapper.cc.
                                {
  // Allocate maps for all Proxy types.
  // Next to the default proxy, we need maps indicating callable and
  // constructable proxies.
  DirectHandle<Map> proxy_map = factory()->NewContextfulMapForCurrentContext(
      JS_PROXY_TYPE, JSProxy::kSize, TERMINAL_FAST_ELEMENTS_KIND);
  proxy_map->set_is_dictionary_map(true);
  proxy_map->set_may_have_interesting_properties(true);
  native_context()->set_proxy_map(*proxy_map);
  proxy_map->SetConstructor(native_context()->object_function());
  DirectHandle<Map> proxy_callable_map =
      Map::Copy(isolate_, proxy_map, "callable Proxy");
  proxy_callable_map->set_is_callable(true);
  native_context()->set_proxy_callable_map(*proxy_callable_map);
  proxy_callable_map->SetConstructor(native_context()->function_function());
  DirectHandle<Map> proxy_constructor_map =
      Map::Copy(isolate_, proxy_callable_map, "constructor Proxy");
  proxy_constructor_map->set_is_constructor(true);
  native_context()->set_proxy_constructor_map(*proxy_constructor_map);
  {
    DirectHandle<Map> map = factory()->NewContextfulMapForCurrentContext(
        JS_OBJECT_TYPE, JSProxyRevocableResult::kSize,
        TERMINAL_FAST_ELEMENTS_KIND, 2);
    Map::EnsureDescriptorSlack(isolate_, map, 2);
    { // proxy
      Descriptor d = Descriptor::DataField(isolate(), factory()->proxy_string(),
                                           JSProxyRevocableResult::kProxyIndex,
                                           NONE, Representation::Tagged());
      map->AppendDescriptor(isolate(), &d);
    }
    { // revoke
      Descriptor d = Descriptor::DataField(
          isolate(), factory()->revoke_string(),
          JSProxyRevocableResult::kRevokeIndex, NONE, Representation::Tagged());
      map->AppendDescriptor(isolate(), &d);
    }
    Map::SetPrototype(isolate(), map, isolate()->initial_object_prototype());
    map->SetConstructor(native_context()->object_function());
    native_context()->set_proxy_revocable_result_map(*map);
  }
}
References v8::internal::Map::Copy(), v8::internal::Descriptor::DataField(), v8::internal::Map::EnsureDescriptorSlack(), factory(), isolate(), isolate_, v8::internal::JSProxyRevocableResult::kProxyIndex, v8::internal::JSProxyRevocableResult::kRevokeIndex, native_context(), v8::internal::Factory::NewContextfulMapForCurrentContext(), v8::internal::NONE, v8::internal::Map::SetPrototype(), v8::internal::Representation::Tagged(), and v8::internal::TERMINAL_FAST_ELEMENTS_KIND.
Referenced by InitializeGlobal().
CreateNewGlobals()
DirectHandle< JSGlobalObject > v8::internal::Genesis::CreateNewGlobals (v8::Local< v8::ObjectTemplate > global_proxy_template, DirectHandle< JSGlobalProxy > global_proxy) [private]
Definition at line 1378 of file bootstrapper.cc.
                                              {
  // The argument global_proxy_template aka data is an ObjectTemplateInfo.
  // It has a constructor pointer that points at global_constructor which is a
  // FunctionTemplateInfo.
  // The global_proxy_constructor is used to (re)initialize the
  // global_proxy. The global_proxy_constructor also has a prototype_template
  // pointer that points at js_global_object_template which is an
  // ObjectTemplateInfo.
  // That in turn has a constructor pointer that points at
  // js_global_object_constructor which is a FunctionTemplateInfo.
  // js_global_object_constructor is used to make js_global_object_function
  // js_global_object_function is used to make the new global_object.
  //
  // --- G l o b a l ---
  // Step 1: Create a fresh JSGlobalObject.
  DirectHandle<JSFunction> js_global_object_function;
  DirectHandle<ObjectTemplateInfo> js_global_object_template;
  if (!global_proxy_template.IsEmpty()) {
    // Get prototype template of the global_proxy_template.
    DirectHandle<ObjectTemplateInfo> data =
        v8::Utils::OpenDirectHandle(*global_proxy_template);
    DirectHandle<FunctionTemplateInfo> global_constructor(
        Cast<FunctionTemplateInfo>(data->constructor()), isolate());
    DirectHandle<Object> proto_template(
        global_constructor->GetPrototypeTemplate(), isolate());
    if (!IsUndefined(*proto_template, isolate())) {
      js_global_object_template = Cast<ObjectTemplateInfo>(proto_template);
    }
  }
  if (js_global_object_template.is_null()) {
    DirectHandle<String> name = factory()->empty_string();
    DirectHandle<JSObject> prototype =
        factory()->NewFunctionPrototype(isolate()->object_function());
    js_global_object_function = CreateFunctionForBuiltinWithPrototype(
        isolate(), name, Builtin::kIllegal, prototype, JS_GLOBAL_OBJECT_TYPE,
        JSGlobalObject::kHeaderSize, 0, MUTABLE, 0, kDontAdapt);
#ifdef DEBUG
    LookupIterator it(isolate(), prototype, factory()->constructor_string(),
                      LookupIterator::OWN_SKIP_INTERCEPTOR);
    DirectHandle<Object> value = Object::GetProperty(&it).ToHandleChecked();
    DCHECK(it.IsFound());
    DCHECK_EQ(*isolate()->object_function(), *value);
#endif
  } else {
    DirectHandle<FunctionTemplateInfo> js_global_object_constructor(
        Cast<FunctionTemplateInfo>(js_global_object_template->constructor()),
        isolate());
    js_global_object_function = ApiNatives::CreateApiFunction(
        isolate(), isolate()->native_context(), js_global_object_constructor,
        factory()->the_hole_value(), JS_GLOBAL_OBJECT_TYPE);
  }
  js_global_object_function->initial_map()->set_is_prototype_map(true);
  js_global_object_function->initial_map()->set_is_dictionary_map(true);
  js_global_object_function->initial_map()->set_may_have_interesting_properties(
      true);
  DirectHandle<JSGlobalObject> global_object =
      factory()->NewJSGlobalObject(js_global_object_function);
  // Step 2: (re)initialize the global proxy object.
  DirectHandle<JSFunction> global_proxy_function;
  if (global_proxy_template.IsEmpty()) {
    DirectHandle<String> name = factory()->empty_string();
    global_proxy_function = CreateFunctionForBuiltinWithPrototype(
        isolate(), name, Builtin::kIllegal, factory()->the_hole_value(),
        JS_GLOBAL_PROXY_TYPE, JSGlobalProxy::SizeWithEmbedderFields(0), 0,
        MUTABLE, 0, kDontAdapt);
  } else {
    DirectHandle<ObjectTemplateInfo> data =
        v8::Utils::OpenDirectHandle(*global_proxy_template);
    DirectHandle<FunctionTemplateInfo> global_constructor(
        Cast<FunctionTemplateInfo>(data->constructor()), isolate());
    global_proxy_function = ApiNatives::CreateApiFunction(
        isolate(), isolate()->native_context(), global_constructor,
        factory()->the_hole_value(), JS_GLOBAL_PROXY_TYPE);
  }
  global_proxy_function->initial_map()->set_is_access_check_needed(true);
  global_proxy_function->initial_map()->set_may_have_interesting_properties(
      true);
  native_context()->set_global_proxy_function(*global_proxy_function);
  // Set the global object as the (hidden) __proto__ of the global proxy after
  // ConfigureGlobalObject
  factory()->ReinitializeJSGlobalProxy(global_proxy, global_proxy_function);
  // Set up the pointer back from the global object to the global proxy.
  global_object->set_global_proxy(*global_proxy);
  // Set the native context of the global proxy.
  global_proxy->map()->set_map(isolate(), native_context()->meta_map());
  // Set the global proxy of the native context. If the native context has been
  // deserialized, the global proxy is already correctly set up by the
  // deserializer. Otherwise it's undefined.
  DCHECK(IsUndefined(native_context()->GetNoCell(Context::GLOBAL_PROXY_INDEX),
                     isolate()) ||
         native_context()->global_proxy_object() == *global_proxy);
  native_context()->set_global_proxy_object(*global_proxy);
  return global_object;
}
References v8::internal::ApiNatives::CreateApiFunction(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltinWithPrototype(), v8::internal::DCHECK(), DCHECK_EQ, factory(), v8::internal::Object::GetProperty(), global_proxy(), v8::internal::DirectHandle< T >::is_null(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::LookupIterator::IsFound(), isolate(), v8::internal::kDontAdapt, v8::internal::MUTABLE, v8::internal::name, native_context(), v8::internal::Factory::NewFunctionPrototype(), v8::internal::Factory::NewJSGlobalObject(), v8::Utils::OpenDirectHandle(), v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR, v8::internal::prototype, v8::internal::Factory::ReinitializeJSGlobalProxy(), v8::internal::JSGlobalProxy::SizeWithEmbedderFields(), and v8::internal::value.
Referenced by Genesis().
CreateObjectFunction()
void v8::internal::Genesis::CreateObjectFunction (DirectHandle< JSFunction > empty) [private]
Definition at line 911 of file bootstrapper.cc.
                                                                          {
  Factory* factory = isolate_->factory();
  // --- O b j e c t ---
  int inobject_properties = JSObject::kInitialGlobalObjectUnusedPropertiesCount;
  int instance_size = JSObject::kHeaderSize + kTaggedSize * inobject_properties;
  DirectHandle<JSFunction> object_fun =
      CreateFunction(isolate_, factory->Object_string(), JS_OBJECT_TYPE,
                     instance_size, inobject_properties, factory->null_value(),
                     Builtin::kObjectConstructor, 1, kDontAdapt);
  native_context()->set_object_function(*object_fun);
  {
    // Finish setting up Object function's initial map.
    Tagged<Map> initial_map = object_fun->initial_map();
    initial_map->set_elements_kind(HOLEY_ELEMENTS);
  }
  // Allocate a new prototype for the object function.
  DirectHandle<JSObject> object_function_prototype =
      factory->NewFunctionPrototype(object_fun);
  {
    DirectHandle<Map> map = Map::Copy(
        isolate(), direct_handle(object_function_prototype->map(), isolate()),
        "EmptyObjectPrototype");
    map->set_is_prototype_map(true);
    // Ban re-setting Object.prototype.__proto__ to prevent Proxy security bug
    map->set_is_immutable_proto(true);
    object_function_prototype->set_map(isolate(), *map);
  }
  // Complete setting up empty function.
  {
    DirectHandle<Map> empty_function_map(empty_function->map(), isolate_);
    Map::SetPrototype(isolate(), empty_function_map, object_function_prototype);
  }
  native_context()->set_initial_object_prototype(*object_function_prototype);
  JSFunction::SetPrototype(isolate_, object_fun, object_function_prototype);
  object_function_prototype->map()->set_instance_type(JS_OBJECT_PROTOTYPE_TYPE);
  {
    // Set up slow map for Object.create(null) instances without in-object
    // properties.
    DirectHandle<Map> map(object_fun->initial_map(), isolate_);
    map = Map::CopyInitialMapNormalized(isolate(), map);
    Map::SetPrototype(isolate(), map, factory->null_value());
    native_context()->set_slow_object_with_null_prototype_map(*map);
    // Set up slow map for literals with too many properties.
    map = Map::Copy(isolate(), map, "slow_object_with_object_prototype_map");
    Map::SetPrototype(isolate(), map, object_function_prototype);
    native_context()->set_slow_object_with_object_prototype_map(*map);
  }
}
References v8::internal::Map::Copy(), v8::internal::Map::CopyInitialMapNormalized(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunction(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), factory(), v8::internal::HOLEY_ELEMENTS, v8::internal::compiler::initial_map, isolate(), isolate_, v8::internal::kDontAdapt, v8::internal::JSObject::kInitialGlobalObjectUnusedPropertiesCount, v8::internal::kTaggedSize, native_context(), v8::internal::Factory::NewFunctionPrototype(), v8::internal::JSFunction::SetPrototype(), and v8::internal::Map::SetPrototype().
Referenced by Genesis().
CreateRoots()
void v8::internal::Genesis::CreateRoots () [private]
Definition at line 1350 of file bootstrapper.cc.
                          {
  // Allocate the native context FixedArray first and then patch the
  // closure and extension object later (we need the empty function
  // and the global object, but in order to create those, we need the
  // native context).
  native_context_ = factory()->NewNativeContext();
  AddToWeakNativeContextList(isolate(), *native_context());
  isolate()->set_context(*native_context());
}
References v8::internal::AddToWeakNativeContextList(), factory(), isolate(), native_context(), native_context_, v8::internal::Factory::NewNativeContext(), and v8::internal::Isolate::set_context().
Referenced by Genesis().
CreateSloppyModeFunctionMaps()
void v8::internal::Genesis::CreateSloppyModeFunctionMaps (DirectHandle< JSFunction > empty) [private]
Definition at line 803 of file bootstrapper.cc.
                                                                         {
  Factory* factory = isolate_->factory();
  DirectHandle<Map> map;
  //
  // Allocate maps for sloppy functions without prototype.
  //
  map = factory->CreateSloppyFunctionMap(FUNCTION_WITHOUT_PROTOTYPE, empty);
  native_context()->set_sloppy_function_without_prototype_map(*map);
  //
  // Allocate maps for sloppy functions with readonly prototype.
  //
  map =
      factory->CreateSloppyFunctionMap(FUNCTION_WITH_READONLY_PROTOTYPE, empty);
  native_context()->set_sloppy_function_with_readonly_prototype_map(*map);
  //
  // Allocate maps for sloppy functions with writable prototype.
  //
  map = factory->CreateSloppyFunctionMap(FUNCTION_WITH_WRITEABLE_PROTOTYPE,
                                         empty);
  native_context()->set_sloppy_function_map(*map);
  map = factory->CreateSloppyFunctionMap(
      FUNCTION_WITH_NAME_AND_WRITEABLE_PROTOTYPE, empty);
  native_context()->set_sloppy_function_with_name_map(*map);
}
References v8::internal::Factory::CreateSloppyFunctionMap(), v8::internal::Isolate::factory(), factory(), v8::internal::FUNCTION_WITH_NAME_AND_WRITEABLE_PROTOTYPE, v8::internal::FUNCTION_WITH_READONLY_PROTOTYPE, v8::internal::FUNCTION_WITH_WRITEABLE_PROTOTYPE, v8::internal::FUNCTION_WITHOUT_PROTOTYPE, isolate_, and native_context().
Referenced by Genesis().
CreateStrictModeFunctionMaps()
void v8::internal::Genesis::CreateStrictModeFunctionMaps (DirectHandle< JSFunction > empty) [private]
Definition at line 867 of file bootstrapper.cc.
                                                                         {
  Factory* factory = isolate_->factory();
  DirectHandle<Map> map;
  //
  // Allocate maps for strict functions without prototype.
  //
  map = factory->CreateStrictFunctionMap(FUNCTION_WITHOUT_PROTOTYPE, empty);
  native_context()->set_strict_function_without_prototype_map(*map);
  map = factory->CreateStrictFunctionMap(METHOD_WITH_NAME, empty);
  native_context()->set_method_with_name_map(*map);
  //
  // Allocate maps for strict functions with writable prototype.
  //
  map = factory->CreateStrictFunctionMap(FUNCTION_WITH_WRITEABLE_PROTOTYPE,
                                         empty);
  native_context()->set_strict_function_map(*map);
  map = factory->CreateStrictFunctionMap(
      FUNCTION_WITH_NAME_AND_WRITEABLE_PROTOTYPE, empty);
  native_context()->set_strict_function_with_name_map(*map);
  //
  // Allocate maps for strict functions with readonly prototype.
  //
  map =
      factory->CreateStrictFunctionMap(FUNCTION_WITH_READONLY_PROTOTYPE, empty);
  native_context()->set_strict_function_with_readonly_prototype_map(*map);
  //
  // Allocate map for class functions.
  //
  map = factory->CreateClassFunctionMap(empty);
  native_context()->set_class_function_map(*map);
#ifdef V8_FUNCTION_ARGUMENTS_CALLER_ARE_OWN_PROPS
  // Now that the strict mode function map is available, set up the
  // restricted "arguments" and "caller" getters.
  AddRestrictedFunctionProperties(empty);
#endif // V8_FUNCTION_ARGUMENTS_CALLER_ARE_OWN_PROPS
}
References AddRestrictedFunctionProperties(), v8::internal::Factory::CreateClassFunctionMap(), v8::internal::Factory::CreateStrictFunctionMap(), v8::internal::Isolate::factory(), factory(), v8::internal::FUNCTION_WITH_NAME_AND_WRITEABLE_PROTOTYPE, v8::internal::FUNCTION_WITH_READONLY_PROTOTYPE, v8::internal::FUNCTION_WITH_WRITEABLE_PROTOTYPE, v8::internal::FUNCTION_WITHOUT_PROTOTYPE, isolate_, v8::internal::METHOD_WITH_NAME, and native_context().
Referenced by Genesis().
factory()
Factory* v8::internal::Genesis::factory () const [inline]
Definition at line 195 of file bootstrapper.cc.
{ return isolate_->factory(); }
References v8::internal::Isolate::factory(), and isolate_.
Referenced by AddRestrictedFunctionProperties(), CompileExtension(), CreateArrayBuffer(), CreateAsyncFunctionMaps(), CreateAsyncIteratorMaps(), CreateEmptyFunction(), CreateInitialMapForArraySubclass(), CreateIteratorMaps(), CreateJSProxyMaps(), CreateNewGlobals(), CreateObjectFunction(), CreateRoots(), CreateSloppyModeFunctionMaps(), CreateStrictModeFunctionMaps(), Genesis(), GetThrowTypeErrorIntrinsic(), HookUpGlobalProxy(), InitializeCallSiteBuiltins(), InitializeConsole(), InitializeGlobal(), InitializeGlobal_regexp_linear_flag(), InitializeIteratorFunctions(), InitializeMapCaches(), InstallABunchOfRandomThings(), InstallExtrasBindings(), InstallGlobalThisBinding(), InstallTypedArray(), and TransferIndexedProperties().
GetThrowTypeErrorIntrinsic()
DirectHandle< JSFunction > v8::internal::Genesis::GetThrowTypeErrorIntrinsic () [private]
Definition at line 832 of file bootstrapper.cc.
                                                             {
  if (!restricted_properties_thrower_.is_null()) {
    return restricted_properties_thrower_;
  }
  DirectHandle<String> name = factory()->empty_string();
  DirectHandle<JSFunction> function = CreateFunctionForBuiltinWithoutPrototype(
      isolate(), name, Builtin::kStrictPoisonPillThrower, 0, kAdapt);
  // %ThrowTypeError% must have a name property with an empty string value. Per
  // spec, ThrowTypeError's name is non-configurable, unlike ordinary functions'
  // name property. To redefine it to be non-configurable, use
  // SetOwnPropertyIgnoreAttributes.
  JSObject::SetOwnPropertyIgnoreAttributes(
      function, factory()->name_string(), factory()->empty_string(),
      static_cast<PropertyAttributes>(DONT_ENUM | DONT_DELETE | READ_ONLY))
      .Assert();
  // length needs to be non configurable.
  DirectHandle<Object> value(Smi::FromInt(function->length()), isolate());
  JSObject::SetOwnPropertyIgnoreAttributes(
      function, factory()->length_string(), value,
      static_cast<PropertyAttributes>(DONT_ENUM | DONT_DELETE | READ_ONLY))
      .Assert();
  if (JSObject::PreventExtensions(isolate_, function, kThrowOnError)
          .IsNothing()) {
    DCHECK(false);
  }
  JSObject::MigrateSlowToFast(function, 0, "Bootstrapping");
  restricted_properties_thrower_ = function;
  return function;
}
References v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltinWithoutPrototype(), v8::internal::DCHECK(), v8::internal::DONT_DELETE, v8::internal::DONT_ENUM, factory(), v8::internal::Smi::FromInt(), isolate(), isolate_, v8::internal::kAdapt, v8::internal::kThrowOnError, v8::internal::JSObject::MigrateSlowToFast(), v8::internal::name, v8::internal::JSObject::PreventExtensions(), v8::internal::READ_ONLY, restricted_properties_thrower_, v8::internal::JSObject::SetOwnPropertyIgnoreAttributes(), and v8::internal::value.
Referenced by AddRestrictedFunctionProperties(), and InitializeGlobal().
global_proxy()
DirectHandle<JSGlobalProxy> v8::internal::Genesis::global_proxy () [inline]
Definition at line 201 of file bootstrapper.cc.
{ return global_proxy_; }
References global_proxy_.
Referenced by ConfigureGlobalObject(), CreateNewGlobals(), Genesis(), HookUpGlobalProxy(), InitializeGlobal(), InstallGlobalThisBinding(), and v8::internal::Bootstrapper::NewRemoteContext().
heap()
Heap* v8::internal::Genesis::heap () const [inline]
Definition at line 197 of file bootstrapper.cc.
{ return isolate_->heap(); }
References v8::internal::Isolate::heap(), and isolate_.
Referenced by InstallABunchOfRandomThings().
HookUpGlobalObject()
void v8::internal::Genesis::HookUpGlobalObject (DirectHandle< JSGlobalObject > global_object) [private]
Definition at line 1494 of file bootstrapper.cc.
                                                                           {
  DirectHandle<JSGlobalObject> global_object_from_snapshot(
      Cast<JSGlobalObject>(native_context()->extension()), isolate());
  native_context()->set_extension(*global_object);
  native_context()->set_security_token(*global_object);
  TransferNamedProperties(global_object_from_snapshot, global_object);
  if (global_object_from_snapshot->HasDictionaryElements()) {
    JSObject::NormalizeElements(isolate(), global_object);
  }
  DCHECK_EQ(global_object_from_snapshot->GetElementsKind(),
            global_object->GetElementsKind());
  TransferIndexedProperties(global_object_from_snapshot, global_object);
}
References DCHECK_EQ, isolate(), native_context(), v8::internal::JSObject::NormalizeElements(), TransferIndexedProperties(), and TransferNamedProperties().
Referenced by Genesis().
HookUpGlobalProxy()
void v8::internal::Genesis::HookUpGlobalProxy (DirectHandle< JSGlobalProxy > global_proxy) [private]
Definition at line 1481 of file bootstrapper.cc.
                                                                        {
  // Re-initialize the global proxy with the global proxy function from the
  // snapshot, and then set up the link to the native context.
  DirectHandle<JSFunction> global_proxy_function(
      native_context()->global_proxy_function(), isolate());
  factory()->ReinitializeJSGlobalProxy(global_proxy, global_proxy_function);
  DirectHandle<JSObject> global_object(
      Cast<JSObject>(native_context()->global_object()), isolate());
  JSObject::ForceSetPrototype(isolate(), global_proxy, global_object);
  global_proxy->map()->set_map(isolate(), native_context()->meta_map());
  DCHECK(native_context()->global_proxy() == *global_proxy);
}
References v8::internal::DCHECK(), factory(), v8::internal::JSObject::ForceSetPrototype(), global_proxy(), isolate(), native_context(), and v8::internal::Factory::ReinitializeJSGlobalProxy().
Referenced by Genesis().
InitializeCallSiteBuiltins()
void v8::internal::Genesis::InitializeCallSiteBuiltins () [private]
Definition at line 5373 of file bootstrapper.cc.
                                         {
  Factory* factory = isolate()->factory();
  HandleScope scope(isolate());
  // -- C a l l S i t e
  // Builtin functions for CallSite.
  // CallSites are a special case; the constructor is for our private use
  // only, therefore we set it up as a builtin that throws. Internally, we use
  // CallSiteUtils::Construct to create CallSite objects.
  DirectHandle<JSFunction> callsite_fun = CreateFunction(
      isolate(), "CallSite", JS_OBJECT_TYPE, JSObject::kHeaderSize, 0,
      factory->the_hole_value(), Builtin::kUnsupportedThrower, 0, kDontAdapt);
  isolate()->native_context()->set_callsite_function(*callsite_fun);
  // Setup CallSite.prototype.
  DirectHandle<JSObject> prototype(
      Cast<JSObject>(callsite_fun->instance_prototype()), isolate());
  struct FunctionInfo {
    const char* name;
    Builtin id;
  };
  FunctionInfo infos[] = {
      {"getColumnNumber", Builtin::kCallSitePrototypeGetColumnNumber},
      {"getEnclosingColumnNumber",
       Builtin::kCallSitePrototypeGetEnclosingColumnNumber},
      {"getEnclosingLineNumber",
       Builtin::kCallSitePrototypeGetEnclosingLineNumber},
      {"getEvalOrigin", Builtin::kCallSitePrototypeGetEvalOrigin},
      {"getFileName", Builtin::kCallSitePrototypeGetFileName},
      {"getFunction", Builtin::kCallSitePrototypeGetFunction},
      {"getFunctionName", Builtin::kCallSitePrototypeGetFunctionName},
      {"getLineNumber", Builtin::kCallSitePrototypeGetLineNumber},
      {"getMethodName", Builtin::kCallSitePrototypeGetMethodName},
      {"getPosition", Builtin::kCallSitePrototypeGetPosition},
      {"getPromiseIndex", Builtin::kCallSitePrototypeGetPromiseIndex},
      {"getScriptNameOrSourceURL",
       Builtin::kCallSitePrototypeGetScriptNameOrSourceURL},
      {"getScriptHash", Builtin::kCallSitePrototypeGetScriptHash},
      {"getThis", Builtin::kCallSitePrototypeGetThis},
      {"getTypeName", Builtin::kCallSitePrototypeGetTypeName},
      {"isAsync", Builtin::kCallSitePrototypeIsAsync},
      {"isConstructor", Builtin::kCallSitePrototypeIsConstructor},
      {"isEval", Builtin::kCallSitePrototypeIsEval},
      {"isNative", Builtin::kCallSitePrototypeIsNative},
      {"isPromiseAll", Builtin::kCallSitePrototypeIsPromiseAll},
      {"isToplevel", Builtin::kCallSitePrototypeIsToplevel},
      {"toString", Builtin::kCallSitePrototypeToString}};
  PropertyAttributes attrs =
      static_cast<PropertyAttributes>(DONT_ENUM | DONT_DELETE | READ_ONLY);
  for (const FunctionInfo& info : infos) {
    SimpleInstallFunction(isolate(), prototype, info.name, info.id, 0, kAdapt,
                          attrs);
  }
}
References v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunction(), v8::internal::DONT_DELETE, v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), factory(), isolate(), v8::internal::kAdapt, v8::internal::kDontAdapt, v8::internal::name, v8::internal::Isolate::native_context(), v8::internal::prototype, v8::internal::READ_ONLY, and v8::internal::SimpleInstallFunction().
Referenced by Genesis().
InitializeConsole()
void v8::internal::Genesis::InitializeConsole (DirectHandle< JSObject > extras_binding) [private]
Definition at line 5433 of file bootstrapper.cc.
                                                                     {
  HandleScope scope(isolate());
  Factory* factory = isolate_->factory();
  // -- C o n s o l e
  DirectHandle<String> name = factory->console_string();
  DirectHandle<NativeContext> context(isolate_->native_context());
  DirectHandle<JSGlobalObject> global(context->global_object(), isolate());
  DirectHandle<SharedFunctionInfo> info =
      factory->NewSharedFunctionInfoForBuiltin(name, Builtin::kIllegal, 0,
                                               kDontAdapt);
  info->set_language_mode(LanguageMode::kStrict);
  DirectHandle<JSFunction> cons =
      Factory::JSFunctionBuilder{isolate(), info, context}.Build();
  DirectHandle<JSObject> empty =
      factory->NewJSObject(isolate_->object_function());
  JSFunction::SetPrototype(isolate_, cons, empty);
  DirectHandle<JSObject> console =
      factory->NewJSObject(cons, AllocationType::kOld);
  DCHECK(IsJSObject(*console));
  JSObject::AddProperty(isolate_, extras_binding, name, console, DONT_ENUM);
  // TODO(v8:11989): remove this in the next release
  JSObject::AddProperty(isolate_, global, name, console, DONT_ENUM);
  SimpleInstallFunction(isolate_, console, "debug", Builtin::kConsoleDebug, 0,
                        kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "error", Builtin::kConsoleError, 0,
                        kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "info", Builtin::kConsoleInfo, 0,
                        kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "log", Builtin::kConsoleLog, 0,
                        kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "warn", Builtin::kConsoleWarn, 0,
                        kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "dir", Builtin::kConsoleDir, 0,
                        kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "dirxml", Builtin::kConsoleDirXml, 0,
                        kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "table", Builtin::kConsoleTable, 0,
                        kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "trace", Builtin::kConsoleTrace, 0,
                        kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "group", Builtin::kConsoleGroup, 0,
                        kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "groupCollapsed",
                        Builtin::kConsoleGroupCollapsed, 0, kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "groupEnd",
                        Builtin::kConsoleGroupEnd, 0, kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "clear", Builtin::kConsoleClear, 0,
                        kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "count", Builtin::kConsoleCount, 0,
                        kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "countReset",
                        Builtin::kConsoleCountReset, 0, kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "assert",
                        Builtin::kFastConsoleAssert, 0, kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "profile", Builtin::kConsoleProfile,
                        0, kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "profileEnd",
                        Builtin::kConsoleProfileEnd, 0, kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "time", Builtin::kConsoleTime, 0,
                        kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "timeLog", Builtin::kConsoleTimeLog,
                        0, kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "timeEnd", Builtin::kConsoleTimeEnd,
                        0, kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "timeStamp",
                        Builtin::kConsoleTimeStamp, 0, kDontAdapt, NONE);
  SimpleInstallFunction(isolate_, console, "context", Builtin::kConsoleContext,
                        1, kDontAdapt, NONE);
  InstallToStringTag(isolate_, console, "console");
}
References v8::internal::JSObject::AddProperty(), v8::internal::DCHECK(), v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), factory(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallToStringTag(), isolate(), isolate_, v8::internal::kDontAdapt, v8::internal::kOld, v8::internal::kStrict, v8::internal::name, v8::internal::Isolate::native_context(), v8::internal::Factory::NewJSObject(), v8::internal::Factory::NewSharedFunctionInfoForBuiltin(), v8::internal::NONE, v8::internal::JSFunction::SetPrototype(), and v8::internal::SimpleInstallFunction().
Referenced by InstallExtrasBindings().
InitializeExperimentalGlobal()
void v8::internal::Genesis::InitializeExperimentalGlobal () [private]
Definition at line 5112 of file bootstrapper.cc.
                                           {
#define FEATURE_INITIALIZE_GLOBAL(id, descr) InitializeGlobal_##id();
  // Initialize features from more mature to less mature, because less mature
  // features may depend on more mature features having been initialized
  // already.
  HARMONY_SHIPPING(FEATURE_INITIALIZE_GLOBAL)
  JAVASCRIPT_SHIPPING_FEATURES(FEATURE_INITIALIZE_GLOBAL)
  HARMONY_STAGED(FEATURE_INITIALIZE_GLOBAL)
  JAVASCRIPT_STAGED_FEATURES(FEATURE_INITIALIZE_GLOBAL)
  HARMONY_INPROGRESS(FEATURE_INITIALIZE_GLOBAL)
  JAVASCRIPT_INPROGRESS_FEATURES(FEATURE_INITIALIZE_GLOBAL)
#undef FEATURE_INITIALIZE_GLOBAL
  InitializeGlobal_regexp_linear_flag();
  InitializeGlobal_sharedarraybuffer();
}
References FEATURE_INITIALIZE_GLOBAL, HARMONY_INPROGRESS, HARMONY_SHIPPING, HARMONY_STAGED, InitializeGlobal_regexp_linear_flag(), InitializeGlobal_sharedarraybuffer(), JAVASCRIPT_INPROGRESS_FEATURES, JAVASCRIPT_SHIPPING_FEATURES, and JAVASCRIPT_STAGED_FEATURES.
Referenced by Genesis().
InitializeGlobal()
void v8::internal::Genesis::InitializeGlobal (DirectHandle< JSGlobalObject > global_object, DirectHandle< JSFunction > empty_function) [private]
Definition at line 2143 of file bootstrapper.cc.
                                                                        {
  // --- N a t i v e C o n t e x t ---
  // Set extension and global object.
  native_context()->set_extension(*global_object);
  // Security setup: Set the security token of the native context to the global
  // object. This makes the security check between two different contexts fail
  // by default even in case of global object reinitialization.
  native_context()->set_security_token(*global_object);
  Factory* factory = isolate_->factory();
  { // -- C o n t e x t
    DirectHandle<Map> meta_map(native_context()->meta_map(), isolate());
    DirectHandle<Map> map = factory->NewMapWithMetaMap(
        meta_map, FUNCTION_CONTEXT_TYPE, kVariableSizeSentinel);
    map->set_native_context(*native_context());
    native_context()->set_function_context_map(*map);
    map = factory->NewMapWithMetaMap(meta_map, CATCH_CONTEXT_TYPE,
                                     kVariableSizeSentinel);
    map->set_native_context(*native_context());
    native_context()->set_catch_context_map(*map);
    map = factory->NewMapWithMetaMap(meta_map, WITH_CONTEXT_TYPE,
                                     kVariableSizeSentinel);
    map->set_native_context(*native_context());
    native_context()->set_with_context_map(*map);
    map = factory->NewMapWithMetaMap(meta_map, DEBUG_EVALUATE_CONTEXT_TYPE,
                                     kVariableSizeSentinel);
    map->set_native_context(*native_context());
    native_context()->set_debug_evaluate_context_map(*map);
    map = factory->NewMapWithMetaMap(meta_map, BLOCK_CONTEXT_TYPE,
                                     kVariableSizeSentinel);
    map->set_native_context(*native_context());
    native_context()->set_block_context_map(*map);
    map = factory->NewMapWithMetaMap(meta_map, MODULE_CONTEXT_TYPE,
                                     kVariableSizeSentinel);
    map->set_native_context(*native_context());
    native_context()->set_module_context_map(*map);
    map = factory->NewMapWithMetaMap(meta_map, AWAIT_CONTEXT_TYPE,
                                     kVariableSizeSentinel);
    map->set_native_context(*native_context());
    native_context()->set_await_context_map(*map);
    map = factory->NewMapWithMetaMap(meta_map, SCRIPT_CONTEXT_TYPE,
                                     kVariableSizeSentinel);
    map->set_native_context(*native_context());
    native_context()->set_script_context_map(*map);
    map = factory->NewMapWithMetaMap(meta_map, EVAL_CONTEXT_TYPE,
                                     kVariableSizeSentinel);
    map->set_native_context(*native_context());
    native_context()->set_eval_context_map(*map);
    DirectHandle<ScriptContextTable> script_context_table =
        factory->NewScriptContextTable();
    native_context()->set_script_context_table(*script_context_table);
    InstallGlobalThisBinding();
  }
  { // --- O b j e c t ---
    DirectHandle<String> object_name = factory->Object_string();
    DirectHandle<JSFunction> object_function = isolate_->object_function();
    JSObject::AddProperty(isolate_, global_object, object_name, object_function,
                          DONT_ENUM);
    SimpleInstallFunction(isolate_, object_function, "assign",
                          Builtin::kObjectAssign, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, object_function, "getOwnPropertyDescriptor",
                          Builtin::kObjectGetOwnPropertyDescriptor, 2,
                          kDontAdapt);
    SimpleInstallFunction(
        isolate_, object_function, "getOwnPropertyDescriptors",
        Builtin::kObjectGetOwnPropertyDescriptors, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, object_function, "getOwnPropertyNames",
                          Builtin::kObjectGetOwnPropertyNames, 1, kAdapt);
    SimpleInstallFunction(isolate_, object_function, "getOwnPropertySymbols",
                          Builtin::kObjectGetOwnPropertySymbols, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, object_function, "hasOwn",
                          Builtin::kObjectHasOwn, 2, kAdapt);
    SimpleInstallFunction(isolate_, object_function, "is", Builtin::kObjectIs,
                          2, kAdapt);
    SimpleInstallFunction(isolate_, object_function, "preventExtensions",
                          Builtin::kObjectPreventExtensions, 1, kAdapt);
    SimpleInstallFunction(isolate_, object_function, "seal",
                          Builtin::kObjectSeal, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, object_function, "create",
                          Builtin::kObjectCreate, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, object_function, "defineProperties",
                          Builtin::kObjectDefineProperties, 2, kAdapt);
    SimpleInstallFunction(isolate_, object_function, "defineProperty",
                          Builtin::kObjectDefineProperty, 3, kAdapt);
    SimpleInstallFunction(isolate_, object_function, "freeze",
                          Builtin::kObjectFreeze, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, object_function, "getPrototypeOf",
                          Builtin::kObjectGetPrototypeOf, 1, kAdapt);
    SimpleInstallFunction(isolate_, object_function, "setPrototypeOf",
                          Builtin::kObjectSetPrototypeOf, 2, kAdapt);
    SimpleInstallFunction(isolate_, object_function, "isExtensible",
                          Builtin::kObjectIsExtensible, 1, kAdapt);
    SimpleInstallFunction(isolate_, object_function, "isFrozen",
                          Builtin::kObjectIsFrozen, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, object_function, "isSealed",
                          Builtin::kObjectIsSealed, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, object_function, "keys",
                          Builtin::kObjectKeys, 1, kAdapt);
    SimpleInstallFunction(isolate_, object_function, "entries",
                          Builtin::kObjectEntries, 1, kAdapt);
    SimpleInstallFunction(isolate_, object_function, "fromEntries",
                          Builtin::kObjectFromEntries, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, object_function, "values",
                          Builtin::kObjectValues, 1, kAdapt);
    SimpleInstallFunction(isolate_, object_function, "groupBy",
                          Builtin::kObjectGroupBy, 2, kAdapt);
    SimpleInstallFunction(isolate_, isolate_->initial_object_prototype(),
                          "__defineGetter__", Builtin::kObjectDefineGetter, 2,
                          kAdapt);
    SimpleInstallFunction(isolate_, isolate_->initial_object_prototype(),
                          "__defineSetter__", Builtin::kObjectDefineSetter, 2,
                          kAdapt);
    SimpleInstallFunction(isolate_, isolate_->initial_object_prototype(),
                          "hasOwnProperty",
                          Builtin::kObjectPrototypeHasOwnProperty, 1, kAdapt);
    SimpleInstallFunction(isolate_, isolate_->initial_object_prototype(),
                          "__lookupGetter__", Builtin::kObjectLookupGetter, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, isolate_->initial_object_prototype(),
                          "__lookupSetter__", Builtin::kObjectLookupSetter, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, isolate_->initial_object_prototype(),
                          "isPrototypeOf",
                          Builtin::kObjectPrototypeIsPrototypeOf, 1, kAdapt);
    SimpleInstallFunction(
        isolate_, isolate_->initial_object_prototype(), "propertyIsEnumerable",
        Builtin::kObjectPrototypePropertyIsEnumerable, 1, kDontAdapt);
    DirectHandle<JSFunction> object_to_string = SimpleInstallFunction(
        isolate_, isolate_->initial_object_prototype(), "toString",
        Builtin::kObjectPrototypeToString, 0, kAdapt);
    native_context()->set_object_to_string(*object_to_string);
    DirectHandle<JSFunction> object_value_of = SimpleInstallFunction(
        isolate_, isolate_->initial_object_prototype(), "valueOf",
        Builtin::kObjectPrototypeValueOf, 0, kAdapt);
    native_context()->set_object_value_of_function(*object_value_of);
    SimpleInstallGetterSetter(
        isolate_, isolate_->initial_object_prototype(), factory->proto_string(),
        Builtin::kObjectPrototypeGetProto, Builtin::kObjectPrototypeSetProto);
    SimpleInstallFunction(isolate_, isolate_->initial_object_prototype(),
                          "toLocaleString",
                          Builtin::kObjectPrototypeToLocaleString, 0, kAdapt);
  }
  DirectHandle<JSObject> global(native_context()->global_object(), isolate());
  { // --- F u n c t i o n ---
    DirectHandle<JSFunction> prototype = empty_function;
    DirectHandle<JSFunction> function_fun =
        InstallFunction(isolate_, global, "Function", JS_FUNCTION_TYPE,
                        JSFunction::kSizeWithPrototype, 0, prototype,
                        Builtin::kFunctionConstructor, 1, kDontAdapt);
    // Function instances are sloppy by default.
    function_fun->set_prototype_or_initial_map(*isolate_->sloppy_function_map(),
                                               kReleaseStore);
    InstallWithIntrinsicDefaultProto(isolate_, function_fun,
                                     Context::FUNCTION_FUNCTION_INDEX);
    native_context()->set_function_prototype(*prototype);
    // Setup the methods on the %FunctionPrototype%.
    JSObject::AddProperty(isolate_, prototype, factory->constructor_string(),
                          function_fun, DONT_ENUM);
    DirectHandle<JSFunction> function_prototype_apply =
        SimpleInstallFunction(isolate_, prototype, "apply",
                              Builtin::kFunctionPrototypeApply, 2, kDontAdapt);
    native_context()->set_function_prototype_apply(*function_prototype_apply);
    SimpleInstallFunction(isolate_, prototype, "bind",
                          Builtin::kFastFunctionPrototypeBind, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "call",
                          Builtin::kFunctionPrototypeCall, 1, kDontAdapt);
    DirectHandle<JSFunction> function_to_string = SimpleInstallFunction(
        isolate_, prototype, "toString", Builtin::kFunctionPrototypeToString, 0,
        kDontAdapt);
    native_context()->set_function_to_string(*function_to_string);
    // Install the @@hasInstance function.
    DirectHandle<JSFunction> has_instance = InstallFunctionAtSymbol(
        isolate_, prototype, factory->has_instance_symbol(),
        "[Symbol.hasInstance]", Builtin::kFunctionPrototypeHasInstance, 1,
        kAdapt,
        static_cast<PropertyAttributes>(DONT_ENUM | DONT_DELETE | READ_ONLY));
    native_context()->set_function_has_instance(*has_instance);
#ifndef V8_FUNCTION_ARGUMENTS_CALLER_ARE_OWN_PROPS
    // The .arguments and .caller getters are non-standard.
    SimpleInstallGetterSetter(isolate_, prototype, factory->arguments_string(),
                              Builtin::kFunctionPrototypeLegacyArgumentsGetter,
                              Builtin::kFunctionPrototypeLegacyArgumentsSetter);
    SimpleInstallGetterSetter(isolate_, prototype, factory->caller_string(),
                              Builtin::kFunctionPrototypeLegacyCallerGetter,
                              Builtin::kFunctionPrototypeLegacyCallerSetter);
#endif // !V8_FUNCTION_ARGUMENTS_CALLER_ARE_OWN_PROPS
    // Complete setting up function maps.
    {
      isolate_->sloppy_function_map()->SetConstructor(*function_fun);
      isolate_->sloppy_function_with_name_map()->SetConstructor(*function_fun);
      isolate_->sloppy_function_with_readonly_prototype_map()->SetConstructor(
          *function_fun);
      isolate_->sloppy_function_without_prototype_map()->SetConstructor(
          *function_fun);
      isolate_->strict_function_map()->SetConstructor(*function_fun);
      isolate_->strict_function_with_name_map()->SetConstructor(*function_fun);
      isolate_->strict_function_with_readonly_prototype_map()->SetConstructor(
          *function_fun);
      isolate_->strict_function_without_prototype_map()->SetConstructor(
          *function_fun);
      isolate_->class_function_map()->SetConstructor(*function_fun);
    }
  }
  DirectHandle<JSFunction> array_prototype_to_string_fun;
  { // --- A r r a y ---
    // This seems a bit hackish, but we need to make sure Array.length is 1.
    int length = 1;
    DirectHandle<JSFunction> array_function = InstallFunction(
        isolate_, global, "Array", JS_ARRAY_TYPE, JSArray::kHeaderSize, 0,
        isolate_->initial_object_prototype(), Builtin::kArrayConstructor,
        length, kDontAdapt);
    DirectHandle<Map> initial_map(array_function->initial_map(), isolate());
    // This assert protects an optimization in
    // HGraphBuilder::JSArrayBuilder::EmitMapCode()
    DCHECK(initial_map->elements_kind() == GetInitialFastElementsKind());
    Map::EnsureDescriptorSlack(isolate_, initial_map, 1);
    PropertyAttributes attribs =
        static_cast<PropertyAttributes>(DONT_ENUM | DONT_DELETE);
    static_assert(JSArray::kLengthDescriptorIndex == 0);
    { // Add length.
      Descriptor d = Descriptor::AccessorConstant(
          factory->length_string(), factory->array_length_accessor(), attribs);
      initial_map->AppendDescriptor(isolate(), &d);
    }
    InstallWithIntrinsicDefaultProto(isolate_, array_function,
                                     Context::ARRAY_FUNCTION_INDEX);
    InstallSpeciesGetter(isolate_, array_function);
    // Create the initial array map for Array.prototype which is required by
    // the used ArrayConstructorStub.
    // This is repeated after properly instantiating the Array.prototype.
    InitializeJSArrayMaps(isolate_, native_context(), initial_map);
    // Set up %ArrayPrototype%.
    // The %ArrayPrototype% has TERMINAL_FAST_ELEMENTS_KIND in order to ensure
    // that constant functions stay constant after turning prototype to setup
    // mode and back.
    DirectHandle<JSArray> proto = factory->NewJSArray(
        0, TERMINAL_FAST_ELEMENTS_KIND, AllocationType::kOld);
    JSFunction::SetPrototype(isolate_, array_function, proto);
    native_context()->set_initial_array_prototype(*proto);
    InitializeJSArrayMaps(
        isolate_, native_context(),
        direct_handle(array_function->initial_map(), isolate_));
    SimpleInstallFunction(isolate_, array_function, "isArray",
                          Builtin::kArrayIsArray, 1, kAdapt);
    SimpleInstallFunction(isolate_, array_function, "from", Builtin::kArrayFrom,
                          1, kDontAdapt);
    SimpleInstallFunction(isolate(), array_function, "fromAsync",
                          Builtin::kArrayFromAsync, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, array_function, "of", Builtin::kArrayOf, 0,
                          kDontAdapt);
    SetConstructorInstanceType(isolate_, array_function,
                               JS_ARRAY_CONSTRUCTOR_TYPE);
    JSObject::AddProperty(isolate_, proto, factory->constructor_string(),
                          array_function, DONT_ENUM);
    SimpleInstallFunction(isolate_, proto, "at", Builtin::kArrayPrototypeAt, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, proto, "concat",
                          Builtin::kArrayPrototypeConcat, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "copyWithin",
                          Builtin::kArrayPrototypeCopyWithin, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "fill", Builtin::kArrayPrototypeFill,
                          1, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "find", Builtin::kArrayPrototypeFind,
                          1, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "findIndex",
                          Builtin::kArrayPrototypeFindIndex, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "findLast",
                          Builtin::kArrayPrototypeFindLast, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "findLastIndex",
                          Builtin::kArrayPrototypeFindLastIndex, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "lastIndexOf",
                          Builtin::kArrayPrototypeLastIndexOf, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "pop", Builtin::kArrayPrototypePop,
                          0, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "push", Builtin::kArrayPrototypePush,
                          1, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "reverse",
                          Builtin::kArrayPrototypeReverse, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "shift",
                          Builtin::kArrayPrototypeShift, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "unshift",
                          Builtin::kArrayPrototypeUnshift, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "slice",
                          Builtin::kArrayPrototypeSlice, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "sort", Builtin::kArrayPrototypeSort,
                          1, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "splice",
                          Builtin::kArrayPrototypeSplice, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "includes", Builtin::kArrayIncludes,
                          1, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "indexOf", Builtin::kArrayIndexOf, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "join", Builtin::kArrayPrototypeJoin,
                          1, kDontAdapt);
    { // Set up iterator-related properties.
      DirectHandle<JSFunction> keys = InstallFunctionWithBuiltinId(
          isolate_, proto, "keys", Builtin::kArrayPrototypeKeys, 0, kAdapt);
      native_context()->set_array_keys_iterator(*keys);
      DirectHandle<JSFunction> entries = InstallFunctionWithBuiltinId(
          isolate_, proto, "entries", Builtin::kArrayPrototypeEntries, 0,
          kAdapt);
      native_context()->set_array_entries_iterator(*entries);
      DirectHandle<JSFunction> values = InstallFunctionWithBuiltinId(
          isolate_, proto, "values", Builtin::kArrayPrototypeValues, 0, kAdapt);
      JSObject::AddProperty(isolate_, proto, factory->iterator_symbol(), values,
                            DONT_ENUM);
      native_context()->set_array_values_iterator(*values);
    }
    DirectHandle<JSFunction> for_each_fun = SimpleInstallFunction(
        isolate_, proto, "forEach", Builtin::kArrayForEach, 1, kDontAdapt);
    native_context()->set_array_for_each_iterator(*for_each_fun);
    SimpleInstallFunction(isolate_, proto, "filter", Builtin::kArrayFilter, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "flat", Builtin::kArrayPrototypeFlat,
                          0, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "flatMap",
                          Builtin::kArrayPrototypeFlatMap, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "map", Builtin::kArrayMap, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "every", Builtin::kArrayEvery, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "some", Builtin::kArraySome, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "reduce", Builtin::kArrayReduce, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "reduceRight",
                          Builtin::kArrayReduceRight, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "toReversed",
                          Builtin::kArrayPrototypeToReversed, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "toSorted",
                          Builtin::kArrayPrototypeToSorted, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "toSpliced",
                          Builtin::kArrayPrototypeToSpliced, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, proto, "with", Builtin::kArrayPrototypeWith,
                          2, kAdapt);
    SimpleInstallFunction(isolate_, proto, "toLocaleString",
                          Builtin::kArrayPrototypeToLocaleString, 0,
                          kDontAdapt);
    array_prototype_to_string_fun =
        SimpleInstallFunction(isolate_, proto, "toString",
                              Builtin::kArrayPrototypeToString, 0, kDontAdapt);
    DirectHandle<JSObject> unscopables = factory->NewJSObjectWithNullProto();
    InstallTrueValuedProperty(isolate_, unscopables, "at");
    InstallTrueValuedProperty(isolate_, unscopables, "copyWithin");
    InstallTrueValuedProperty(isolate_, unscopables, "entries");
    InstallTrueValuedProperty(isolate_, unscopables, "fill");
    InstallTrueValuedProperty(isolate_, unscopables, "find");
    InstallTrueValuedProperty(isolate_, unscopables, "findIndex");
    InstallTrueValuedProperty(isolate_, unscopables, "findLast");
    InstallTrueValuedProperty(isolate_, unscopables, "findLastIndex");
    InstallTrueValuedProperty(isolate_, unscopables, "flat");
    InstallTrueValuedProperty(isolate_, unscopables, "flatMap");
    InstallTrueValuedProperty(isolate_, unscopables, "includes");
    InstallTrueValuedProperty(isolate_, unscopables, "keys");
    InstallTrueValuedProperty(isolate_, unscopables, "toReversed");
    InstallTrueValuedProperty(isolate_, unscopables, "toSorted");
    InstallTrueValuedProperty(isolate_, unscopables, "toSpliced");
    InstallTrueValuedProperty(isolate_, unscopables, "values");
    JSObject::MigrateSlowToFast(unscopables, 0, "Bootstrapping");
    JSObject::AddProperty(
        isolate_, proto, factory->unscopables_symbol(), unscopables,
        static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY));
    DirectHandle<Map> map(proto->map(), isolate_);
    Map::SetShouldBeFastPrototypeMap(map, true, isolate_);
    auto validity_cell =
        Cast<Cell>(Map::GetOrCreatePrototypeChainValidityCell(map, isolate()));
    native_context()->set_initial_array_prototype_validity_cell(*validity_cell);
  }
  { // --- A r r a y I t e r a t o r ---
    DirectHandle<JSObject> iterator_prototype(
        native_context()->initial_iterator_prototype(), isolate());
    DirectHandle<JSObject> array_iterator_prototype =
        factory->NewJSObject(isolate_->object_function(), AllocationType::kOld);
    JSObject::ForceSetPrototype(isolate(), array_iterator_prototype,
                                iterator_prototype);
    CHECK_NE(array_iterator_prototype->map().ptr(),
             isolate_->initial_object_prototype()->map().ptr());
    array_iterator_prototype->map()->set_instance_type(
        JS_ARRAY_ITERATOR_PROTOTYPE_TYPE);
    InstallToStringTag(isolate_, array_iterator_prototype,
                       factory->ArrayIterator_string());
    InstallFunctionWithBuiltinId(isolate_, array_iterator_prototype, "next",
                                 Builtin::kArrayIteratorPrototypeNext, 0,
                                 kAdapt);
    DirectHandle<JSFunction> array_iterator_function = CreateFunction(
        isolate_, factory->ArrayIterator_string(), JS_ARRAY_ITERATOR_TYPE,
        JSArrayIterator::kHeaderSize, 0, array_iterator_prototype,
        Builtin::kIllegal, 0, kDontAdapt);
    array_iterator_function->shared()->set_native(false);
    native_context()->set_initial_array_iterator_map(
        array_iterator_function->initial_map());
    native_context()->set_initial_array_iterator_prototype(
        *array_iterator_prototype);
  }
  { // --- N u m b e r ---
    DirectHandle<JSFunction> number_fun =
        InstallFunction(isolate_, global, "Number", JS_PRIMITIVE_WRAPPER_TYPE,
                        JSPrimitiveWrapper::kHeaderSize, 0,
                        isolate_->initial_object_prototype(),
                        Builtin::kNumberConstructor, 1, kDontAdapt);
    InstallWithIntrinsicDefaultProto(isolate_, number_fun,
                                     Context::NUMBER_FUNCTION_INDEX);
    // Create the %NumberPrototype%
    DirectHandle<JSPrimitiveWrapper> prototype = Cast<JSPrimitiveWrapper>(
        factory->NewJSObject(number_fun, AllocationType::kOld));
    prototype->set_value(Smi::zero());
    JSFunction::SetPrototype(isolate_, number_fun, prototype);
    // Install the "constructor" property on the {prototype}.
    JSObject::AddProperty(isolate_, prototype, factory->constructor_string(),
                          number_fun, DONT_ENUM);
    // Install the Number.prototype methods.
    SimpleInstallFunction(isolate_, prototype, "toExponential",
                          Builtin::kNumberPrototypeToExponential, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toFixed",
                          Builtin::kNumberPrototypeToFixed, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toPrecision",
                          Builtin::kNumberPrototypeToPrecision, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toString",
                          Builtin::kNumberPrototypeToString, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "valueOf",
                          Builtin::kNumberPrototypeValueOf, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "toLocaleString",
                          Builtin::kNumberPrototypeToLocaleString, 0,
                          kDontAdapt);
    // Install the Number functions.
    SimpleInstallFunction(isolate_, number_fun, "isFinite",
                          Builtin::kNumberIsFinite, 1, kAdapt);
    SimpleInstallFunction(isolate_, number_fun, "isInteger",
                          Builtin::kNumberIsInteger, 1, kAdapt);
    SimpleInstallFunction(isolate_, number_fun, "isNaN", Builtin::kNumberIsNaN,
                          1, kAdapt);
    SimpleInstallFunction(isolate_, number_fun, "isSafeInteger",
                          Builtin::kNumberIsSafeInteger, 1, kAdapt);
    // Install Number.parseFloat and Global.parseFloat.
    DirectHandle<JSFunction> parse_float_fun =
        SimpleInstallFunction(isolate_, number_fun, "parseFloat",
                              Builtin::kNumberParseFloat, 1, kAdapt);
    JSObject::AddProperty(isolate_, global_object, "parseFloat",
                          parse_float_fun, DONT_ENUM);
    native_context()->set_global_parse_float_fun(*parse_float_fun);
    // Install Number.parseInt and Global.parseInt.
    DirectHandle<JSFunction> parse_int_fun = SimpleInstallFunction(
        isolate_, number_fun, "parseInt", Builtin::kNumberParseInt, 2, kAdapt);
    JSObject::AddProperty(isolate_, global_object, "parseInt", parse_int_fun,
                          DONT_ENUM);
    native_context()->set_global_parse_int_fun(*parse_int_fun);
    // Install Number constants
    const double kMaxValue = 1.7976931348623157e+308;
    const double kMinValue = 5e-324;
    const double kEPS = 2.220446049250313e-16;
    InstallConstant(isolate_, number_fun, "MAX_VALUE",
                    factory->NewNumber(kMaxValue));
    InstallConstant(isolate_, number_fun, "MIN_VALUE",
                    factory->NewNumber(kMinValue));
    InstallConstant(isolate_, number_fun, "NaN", factory->nan_value());
    InstallConstant(isolate_, number_fun, "NEGATIVE_INFINITY",
                    factory->NewNumber(-V8_INFINITY));
    InstallConstant(isolate_, number_fun, "POSITIVE_INFINITY",
                    factory->infinity_value());
    InstallConstant(isolate_, number_fun, "MAX_SAFE_INTEGER",
                    factory->NewNumber(kMaxSafeInteger));
    InstallConstant(isolate_, number_fun, "MIN_SAFE_INTEGER",
                    factory->NewNumber(kMinSafeInteger));
    InstallConstant(isolate_, number_fun, "EPSILON", factory->NewNumber(kEPS));
    InstallConstant(isolate_, global, "Infinity", factory->infinity_value());
    InstallConstant(isolate_, global, "NaN", factory->nan_value());
    InstallConstant(isolate_, global, "undefined", factory->undefined_value());
  }
  { // --- B o o l e a n ---
    DirectHandle<JSFunction> boolean_fun =
        InstallFunction(isolate_, global, "Boolean", JS_PRIMITIVE_WRAPPER_TYPE,
                        JSPrimitiveWrapper::kHeaderSize, 0,
                        isolate_->initial_object_prototype(),
                        Builtin::kBooleanConstructor, 1, kDontAdapt);
    InstallWithIntrinsicDefaultProto(isolate_, boolean_fun,
                                     Context::BOOLEAN_FUNCTION_INDEX);
    // Create the %BooleanPrototype%
    DirectHandle<JSPrimitiveWrapper> prototype = Cast<JSPrimitiveWrapper>(
        factory->NewJSObject(boolean_fun, AllocationType::kOld));
    prototype->set_value(ReadOnlyRoots(isolate_).false_value());
    JSFunction::SetPrototype(isolate_, boolean_fun, prototype);
    // Install the "constructor" property on the {prototype}.
    JSObject::AddProperty(isolate_, prototype, factory->constructor_string(),
                          boolean_fun, DONT_ENUM);
    // Install the Boolean.prototype methods.
    SimpleInstallFunction(isolate_, prototype, "toString",
                          Builtin::kBooleanPrototypeToString, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "valueOf",
                          Builtin::kBooleanPrototypeValueOf, 0, kAdapt);
  }
  { // --- S t r i n g ---
    DirectHandle<JSFunction> string_fun =
        InstallFunction(isolate_, global, "String", JS_PRIMITIVE_WRAPPER_TYPE,
                        JSPrimitiveWrapper::kHeaderSize, 0,
                        isolate_->initial_object_prototype(),
                        Builtin::kStringConstructor, 1, kDontAdapt);
    InstallWithIntrinsicDefaultProto(isolate_, string_fun,
                                     Context::STRING_FUNCTION_INDEX);
    DirectHandle<Map> string_map(
        native_context()->string_function()->initial_map(), isolate());
    string_map->set_elements_kind(FAST_STRING_WRAPPER_ELEMENTS);
    Map::EnsureDescriptorSlack(isolate_, string_map, 1);
    PropertyAttributes attribs =
        static_cast<PropertyAttributes>(DONT_ENUM | DONT_DELETE | READ_ONLY);
    { // Add length.
      Descriptor d = Descriptor::AccessorConstant(
          factory->length_string(), factory->string_length_accessor(), attribs);
      string_map->AppendDescriptor(isolate(), &d);
    }
    // Install the String.fromCharCode function.
    SimpleInstallFunction(isolate_, string_fun, "fromCharCode",
                          Builtin::kStringFromCharCode, 1, kDontAdapt);
    // Install the String.fromCodePoint function.
    SimpleInstallFunction(isolate_, string_fun, "fromCodePoint",
                          Builtin::kStringFromCodePoint, 1, kDontAdapt);
    // Install the String.raw function.
    SimpleInstallFunction(isolate_, string_fun, "raw", Builtin::kStringRaw, 1,
                          kDontAdapt);
    // Create the %StringPrototype%
    DirectHandle<JSPrimitiveWrapper> prototype = Cast<JSPrimitiveWrapper>(
        factory->NewJSObject(string_fun, AllocationType::kOld));
    prototype->set_value(ReadOnlyRoots(isolate_).empty_string());
    JSFunction::SetPrototype(isolate_, string_fun, prototype);
    native_context()->set_initial_string_prototype(*prototype);
    // Install the "constructor" property on the {prototype}.
    JSObject::AddProperty(isolate_, prototype, factory->constructor_string(),
                          string_fun, DONT_ENUM);
    // Install the String.prototype methods.
    SimpleInstallFunction(isolate_, prototype, "anchor",
                          Builtin::kStringPrototypeAnchor, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "at",
                          Builtin::kStringPrototypeAt, 1, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "big",
                          Builtin::kStringPrototypeBig, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "blink",
                          Builtin::kStringPrototypeBlink, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "bold",
                          Builtin::kStringPrototypeBold, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "charAt",
                          Builtin::kStringPrototypeCharAt, 1, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "charCodeAt",
                          Builtin::kStringPrototypeCharCodeAt, 1, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "codePointAt",
                          Builtin::kStringPrototypeCodePointAt, 1, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "concat",
                          Builtin::kStringPrototypeConcat, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "endsWith",
                          Builtin::kStringPrototypeEndsWith, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "fontcolor",
                          Builtin::kStringPrototypeFontcolor, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "fontsize",
                          Builtin::kStringPrototypeFontsize, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "fixed",
                          Builtin::kStringPrototypeFixed, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "includes",
                          Builtin::kStringPrototypeIncludes, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "indexOf",
                          Builtin::kStringPrototypeIndexOf, 1, kDontAdapt);
    SimpleInstallFunction(isolate(), prototype, "isWellFormed",
                          Builtin::kStringPrototypeIsWellFormed, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "italics",
                          Builtin::kStringPrototypeItalics, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "lastIndexOf",
                          Builtin::kStringPrototypeLastIndexOf, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "link",
                          Builtin::kStringPrototypeLink, 1, kDontAdapt);
#ifdef V8_INTL_SUPPORT
    SimpleInstallFunction(isolate_, prototype, "localeCompare",
                          Builtin::kStringPrototypeLocaleCompareIntl, 1,
                          kDontAdapt);
#else
    SimpleInstallFunction(isolate_, prototype, "localeCompare",
                          Builtin::kStringPrototypeLocaleCompare, 1, kAdapt);
#endif // V8_INTL_SUPPORT
    SimpleInstallFunction(isolate_, prototype, "match",
                          Builtin::kStringPrototypeMatch, 1, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "matchAll",
                          Builtin::kStringPrototypeMatchAll, 1, kAdapt);
#ifdef V8_INTL_SUPPORT
    SimpleInstallFunction(isolate_, prototype, "normalize",
                          Builtin::kStringPrototypeNormalizeIntl, 0,
                          kDontAdapt);
#else
    SimpleInstallFunction(isolate_, prototype, "normalize",
                          Builtin::kStringPrototypeNormalize, 0, kDontAdapt);
#endif // V8_INTL_SUPPORT
    SimpleInstallFunction(isolate_, prototype, "padEnd",
                          Builtin::kStringPrototypePadEnd, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "padStart",
                          Builtin::kStringPrototypePadStart, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "repeat",
                          Builtin::kStringPrototypeRepeat, 1, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "replace",
                          Builtin::kStringPrototypeReplace, 2, kAdapt);
    SimpleInstallFunction(isolate(), prototype, "replaceAll",
                          Builtin::kStringPrototypeReplaceAll, 2, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "search",
                          Builtin::kStringPrototypeSearch, 1, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "slice",
                          Builtin::kStringPrototypeSlice, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "small",
                          Builtin::kStringPrototypeSmall, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "split",
                          Builtin::kStringPrototypeSplit, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "strike",
                          Builtin::kStringPrototypeStrike, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "sub",
                          Builtin::kStringPrototypeSub, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "substr",
                          Builtin::kStringPrototypeSubstr, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "substring",
                          Builtin::kStringPrototypeSubstring, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "sup",
                          Builtin::kStringPrototypeSup, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "startsWith",
                          Builtin::kStringPrototypeStartsWith, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toString",
                          Builtin::kStringPrototypeToString, 0, kAdapt);
    SimpleInstallFunction(isolate(), prototype, "toWellFormed",
                          Builtin::kStringPrototypeToWellFormed, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "trim",
                          Builtin::kStringPrototypeTrim, 0, kDontAdapt);
    // Install `String.prototype.trimStart` with `trimLeft` alias.
    DirectHandle<JSFunction> trim_start_fun = SimpleInstallFunction(
        isolate_, prototype, "trimStart", Builtin::kStringPrototypeTrimStart, 0,
        kDontAdapt);
    JSObject::AddProperty(isolate_, prototype, "trimLeft", trim_start_fun,
                          DONT_ENUM);
    // Install `String.prototype.trimEnd` with `trimRight` alias.
    DirectHandle<JSFunction> trim_end_fun =
        SimpleInstallFunction(isolate_, prototype, "trimEnd",
                              Builtin::kStringPrototypeTrimEnd, 0, kDontAdapt);
    JSObject::AddProperty(isolate_, prototype, "trimRight", trim_end_fun,
                          DONT_ENUM);
    SimpleInstallFunction(isolate_, prototype, "toLocaleLowerCase",
                          Builtin::kStringPrototypeToLocaleLowerCase, 0,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toLocaleUpperCase",
                          Builtin::kStringPrototypeToLocaleUpperCase, 0,
                          kDontAdapt);
#ifdef V8_INTL_SUPPORT
    SimpleInstallFunction(isolate_, prototype, "toLowerCase",
                          Builtin::kStringPrototypeToLowerCaseIntl, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "toUpperCase",
                          Builtin::kStringPrototypeToUpperCaseIntl, 0,
                          kDontAdapt);
#else
    SimpleInstallFunction(isolate_, prototype, "toLowerCase",
                          Builtin::kStringPrototypeToLowerCase, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toUpperCase",
                          Builtin::kStringPrototypeToUpperCase, 0, kDontAdapt);
#endif
    SimpleInstallFunction(isolate_, prototype, "valueOf",
                          Builtin::kStringPrototypeValueOf, 0, kAdapt);
    InstallFunctionAtSymbol(
        isolate_, prototype, factory->iterator_symbol(), "[Symbol.iterator]",
        Builtin::kStringPrototypeIterator, 0, kAdapt, DONT_ENUM);
  }
  { // --- S t r i n g I t e r a t o r ---
    DirectHandle<JSObject> iterator_prototype(
        native_context()->initial_iterator_prototype(), isolate());
    DirectHandle<JSObject> string_iterator_prototype =
        factory->NewJSObject(isolate_->object_function(), AllocationType::kOld);
    JSObject::ForceSetPrototype(isolate(), string_iterator_prototype,
                                iterator_prototype);
    CHECK_NE(string_iterator_prototype->map().ptr(),
             isolate_->initial_object_prototype()->map().ptr());
    string_iterator_prototype->map()->set_instance_type(
        JS_STRING_ITERATOR_PROTOTYPE_TYPE);
    InstallToStringTag(isolate_, string_iterator_prototype, "String Iterator");
    InstallFunctionWithBuiltinId(isolate_, string_iterator_prototype, "next",
                                 Builtin::kStringIteratorPrototypeNext, 0,
                                 kAdapt);
    DirectHandle<JSFunction> string_iterator_function = CreateFunction(
        isolate_, factory->InternalizeUtf8String("StringIterator"),
        JS_STRING_ITERATOR_TYPE, JSStringIterator::kHeaderSize, 0,
        string_iterator_prototype, Builtin::kIllegal, 0, kDontAdapt);
    string_iterator_function->shared()->set_native(false);
    native_context()->set_initial_string_iterator_map(
        string_iterator_function->initial_map());
    native_context()->set_initial_string_iterator_prototype(
        *string_iterator_prototype);
  }
  { // --- S y m b o l ---
    DirectHandle<JSFunction> symbol_fun = InstallFunction(
        isolate_, global, "Symbol", JS_PRIMITIVE_WRAPPER_TYPE,
        JSPrimitiveWrapper::kHeaderSize, 0, factory->the_hole_value(),
        Builtin::kSymbolConstructor, 0, kDontAdapt);
    native_context()->set_symbol_function(*symbol_fun);
    // Install the Symbol.for and Symbol.keyFor functions.
    SimpleInstallFunction(isolate_, symbol_fun, "for", Builtin::kSymbolFor, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, symbol_fun, "keyFor",
                          Builtin::kSymbolKeyFor, 1, kDontAdapt);
    // Install well-known symbols.
    InstallConstant(isolate_, symbol_fun, "asyncIterator",
                    factory->async_iterator_symbol());
    InstallConstant(isolate_, symbol_fun, "hasInstance",
                    factory->has_instance_symbol());
    InstallConstant(isolate_, symbol_fun, "isConcatSpreadable",
                    factory->is_concat_spreadable_symbol());
    InstallConstant(isolate_, symbol_fun, "iterator",
                    factory->iterator_symbol());
    InstallConstant(isolate_, symbol_fun, "match", factory->match_symbol());
    InstallConstant(isolate_, symbol_fun, "matchAll",
                    factory->match_all_symbol());
    InstallConstant(isolate_, symbol_fun, "replace", factory->replace_symbol());
    InstallConstant(isolate_, symbol_fun, "search", factory->search_symbol());
    InstallConstant(isolate_, symbol_fun, "species", factory->species_symbol());
    InstallConstant(isolate_, symbol_fun, "split", factory->split_symbol());
    InstallConstant(isolate_, symbol_fun, "toPrimitive",
                    factory->to_primitive_symbol());
    InstallConstant(isolate_, symbol_fun, "toStringTag",
                    factory->to_string_tag_symbol());
    InstallConstant(isolate_, symbol_fun, "unscopables",
                    factory->unscopables_symbol());
    InstallConstant(isolate_, symbol_fun, "dispose", factory->dispose_symbol());
    InstallConstant(isolate_, symbol_fun, "asyncDispose",
                    factory->async_dispose_symbol());
    // Setup %SymbolPrototype%.
    DirectHandle<JSObject> prototype(
        Cast<JSObject>(symbol_fun->instance_prototype()), isolate());
    InstallToStringTag(isolate_, prototype, "Symbol");
    // Install the Symbol.prototype methods.
    InstallFunctionWithBuiltinId(isolate_, prototype, "toString",
                                 Builtin::kSymbolPrototypeToString, 0, kAdapt);
    InstallFunctionWithBuiltinId(isolate_, prototype, "valueOf",
                                 Builtin::kSymbolPrototypeValueOf, 0, kAdapt);
    // Install the Symbol.prototype.description getter.
    SimpleInstallGetter(isolate_, prototype,
                        factory->InternalizeUtf8String("description"),
                        Builtin::kSymbolPrototypeDescriptionGetter, kAdapt);
    // Install the @@toPrimitive function.
    InstallFunctionAtSymbol(
        isolate_, prototype, factory->to_primitive_symbol(),
        "[Symbol.toPrimitive]", Builtin::kSymbolPrototypeToPrimitive, 1, kAdapt,
        static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY));
  }
  { // --- D a t e ---
    DirectHandle<JSFunction> date_fun = InstallFunction(
        isolate_, global, "Date", JS_DATE_TYPE, JSDate::kHeaderSize, 0,
        factory->the_hole_value(), Builtin::kDateConstructor, 7, kDontAdapt);
    InstallWithIntrinsicDefaultProto(isolate_, date_fun,
                                     Context::DATE_FUNCTION_INDEX);
    // Install the Date.now, Date.parse and Date.UTC functions.
    SimpleInstallFunction(isolate_, date_fun, "now", Builtin::kDateNow, 0,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, date_fun, "parse", Builtin::kDateParse, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, date_fun, "UTC", Builtin::kDateUTC, 7,
                          kDontAdapt);
    // Setup %DatePrototype%.
    DirectHandle<JSObject> prototype(
        Cast<JSObject>(date_fun->instance_prototype()), isolate());
    // Install the Date.prototype methods.
    SimpleInstallFunction(isolate_, prototype, "toString",
                          Builtin::kDatePrototypeToString, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toDateString",
                          Builtin::kDatePrototypeToDateString, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toTimeString",
                          Builtin::kDatePrototypeToTimeString, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toISOString",
                          Builtin::kDatePrototypeToISOString, 0, kDontAdapt);
    DirectHandle<JSFunction> to_utc_string = SimpleInstallFunction(
        isolate_, prototype, "toUTCString", Builtin::kDatePrototypeToUTCString,
        0, kDontAdapt);
    JSObject::AddProperty(isolate_, prototype, "toGMTString", to_utc_string,
                          DONT_ENUM);
    SimpleInstallFunction(isolate_, prototype, "getDate",
                          Builtin::kDatePrototypeGetDate, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setDate",
                          Builtin::kDatePrototypeSetDate, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getDay",
                          Builtin::kDatePrototypeGetDay, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "getFullYear",
                          Builtin::kDatePrototypeGetFullYear, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setFullYear",
                          Builtin::kDatePrototypeSetFullYear, 3, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getHours",
                          Builtin::kDatePrototypeGetHours, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setHours",
                          Builtin::kDatePrototypeSetHours, 4, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getMilliseconds",
                          Builtin::kDatePrototypeGetMilliseconds, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setMilliseconds",
                          Builtin::kDatePrototypeSetMilliseconds, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getMinutes",
                          Builtin::kDatePrototypeGetMinutes, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setMinutes",
                          Builtin::kDatePrototypeSetMinutes, 3, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getMonth",
                          Builtin::kDatePrototypeGetMonth, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setMonth",
                          Builtin::kDatePrototypeSetMonth, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getSeconds",
                          Builtin::kDatePrototypeGetSeconds, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setSeconds",
                          Builtin::kDatePrototypeSetSeconds, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getTime",
                          Builtin::kDatePrototypeGetTime, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setTime",
                          Builtin::kDatePrototypeSetTime, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getTimezoneOffset",
                          Builtin::kDatePrototypeGetTimezoneOffset, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "getUTCDate",
                          Builtin::kDatePrototypeGetUTCDate, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setUTCDate",
                          Builtin::kDatePrototypeSetUTCDate, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getUTCDay",
                          Builtin::kDatePrototypeGetUTCDay, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "getUTCFullYear",
                          Builtin::kDatePrototypeGetUTCFullYear, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setUTCFullYear",
                          Builtin::kDatePrototypeSetUTCFullYear, 3, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getUTCHours",
                          Builtin::kDatePrototypeGetUTCHours, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setUTCHours",
                          Builtin::kDatePrototypeSetUTCHours, 4, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getUTCMilliseconds",
                          Builtin::kDatePrototypeGetUTCMilliseconds, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setUTCMilliseconds",
                          Builtin::kDatePrototypeSetUTCMilliseconds, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getUTCMinutes",
                          Builtin::kDatePrototypeGetUTCMinutes, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setUTCMinutes",
                          Builtin::kDatePrototypeSetUTCMinutes, 3, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getUTCMonth",
                          Builtin::kDatePrototypeGetUTCMonth, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setUTCMonth",
                          Builtin::kDatePrototypeSetUTCMonth, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getUTCSeconds",
                          Builtin::kDatePrototypeGetUTCSeconds, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setUTCSeconds",
                          Builtin::kDatePrototypeSetUTCSeconds, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "valueOf",
                          Builtin::kDatePrototypeValueOf, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "getYear",
                          Builtin::kDatePrototypeGetYear, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "setYear",
                          Builtin::kDatePrototypeSetYear, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toJSON",
                          Builtin::kDatePrototypeToJson, 1, kDontAdapt);
#ifdef V8_INTL_SUPPORT
    SimpleInstallFunction(isolate_, prototype, "toLocaleString",
                          Builtin::kDatePrototypeToLocaleString, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toLocaleDateString",
                          Builtin::kDatePrototypeToLocaleDateString, 0,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toLocaleTimeString",
                          Builtin::kDatePrototypeToLocaleTimeString, 0,
                          kDontAdapt);
#else
    // Install Intl fallback functions.
    SimpleInstallFunction(isolate_, prototype, "toLocaleString",
                          Builtin::kDatePrototypeToString, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toLocaleDateString",
                          Builtin::kDatePrototypeToDateString, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toLocaleTimeString",
                          Builtin::kDatePrototypeToTimeString, 0, kDontAdapt);
#endif // V8_INTL_SUPPORT
    // Install the @@toPrimitive function.
    InstallFunctionAtSymbol(
        isolate_, prototype, factory->to_primitive_symbol(),
        "[Symbol.toPrimitive]", Builtin::kDatePrototypeToPrimitive, 1, kAdapt,
        static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY));
  }
  { // -- P r o m i s e
    DirectHandle<JSFunction> promise_fun = InstallFunction(
        isolate_, global, "Promise", JS_PROMISE_TYPE,
        JSPromise::kSizeWithEmbedderFields, 0, factory->the_hole_value(),
        Builtin::kPromiseConstructor, 1, kAdapt);
    InstallWithIntrinsicDefaultProto(isolate_, promise_fun,
                                     Context::PROMISE_FUNCTION_INDEX);
    InstallSpeciesGetter(isolate_, promise_fun);
    DirectHandle<JSFunction> promise_all = InstallFunctionWithBuiltinId(
        isolate_, promise_fun, "all", Builtin::kPromiseAll, 1, kAdapt);
    native_context()->set_promise_all(*promise_all);
    DirectHandle<JSFunction> promise_all_settled =
        InstallFunctionWithBuiltinId(isolate_, promise_fun, "allSettled",
                                     Builtin::kPromiseAllSettled, 1, kAdapt);
    native_context()->set_promise_all_settled(*promise_all_settled);
    DirectHandle<JSFunction> promise_any = InstallFunctionWithBuiltinId(
        isolate_, promise_fun, "any", Builtin::kPromiseAny, 1, kAdapt);
    native_context()->set_promise_any(*promise_any);
    InstallFunctionWithBuiltinId(isolate_, promise_fun, "race",
                                 Builtin::kPromiseRace, 1, kAdapt);
    DirectHandle<JSFunction> promise_resolve = InstallFunctionWithBuiltinId(
        isolate_, promise_fun, "resolve", Builtin::kPromiseResolveTrampoline, 1,
        kAdapt);
    native_context()->set_promise_resolve(*promise_resolve);
    InstallFunctionWithBuiltinId(isolate_, promise_fun, "reject",
                                 Builtin::kPromiseReject, 1, kAdapt);
    std::array<DirectHandle<Name>, 3> fields{factory->promise_string(),
                                             factory->resolve_string(),
                                             factory->reject_string()};
    DirectHandle<Map> result_map =
        CreateLiteralObjectMapFromCache(isolate_, fields);
    native_context()->set_promise_withresolvers_result_map(*result_map);
    InstallFunctionWithBuiltinId(isolate_, promise_fun, "withResolvers",
                                 Builtin::kPromiseWithResolvers, 0, kAdapt);
    SetConstructorInstanceType(isolate_, promise_fun,
                               JS_PROMISE_CONSTRUCTOR_TYPE);
    // Setup %PromisePrototype%.
    DirectHandle<JSObject> prototype(
        Cast<JSObject>(promise_fun->instance_prototype()), isolate());
    native_context()->set_promise_prototype(*prototype);
    InstallToStringTag(isolate_, prototype, factory->Promise_string());
    DirectHandle<JSFunction> promise_then = InstallFunctionWithBuiltinId(
        isolate_, prototype, "then", Builtin::kPromisePrototypeThen, 2, kAdapt);
    native_context()->set_promise_then(*promise_then);
    DirectHandle<JSFunction> perform_promise_then =
        SimpleCreateFunction(isolate_, factory->empty_string(),
                             Builtin::kPerformPromiseThenFunction, 2, kAdapt);
    native_context()->set_perform_promise_then(*perform_promise_then);
    InstallFunctionWithBuiltinId(isolate_, prototype, "catch",
                                 Builtin::kPromisePrototypeCatch, 1, kAdapt);
    InstallFunctionWithBuiltinId(isolate_, prototype, "finally",
                                 Builtin::kPromisePrototypeFinally, 1, kAdapt);
    DCHECK(promise_fun->HasFastProperties());
    DirectHandle<Map> prototype_map(prototype->map(), isolate());
    Map::SetShouldBeFastPrototypeMap(prototype_map, true, isolate_);
    CHECK_NE(prototype->map().ptr(),
             isolate_->initial_object_prototype()->map().ptr());
    prototype->map()->set_instance_type(JS_PROMISE_PROTOTYPE_TYPE);
    DCHECK(promise_fun->HasFastProperties());
  }
  { // -- R e g E x p
    // Builtin functions for RegExp.prototype.
    DirectHandle<JSFunction> regexp_fun = InstallFunction(
        isolate_, global, "RegExp", JS_REG_EXP_TYPE,
        JSRegExp::kHeaderSize + JSRegExp::kInObjectFieldCount * kTaggedSize,
        JSRegExp::kInObjectFieldCount, factory->the_hole_value(),
        Builtin::kRegExpConstructor, 2, kAdapt);
    InstallWithIntrinsicDefaultProto(isolate_, regexp_fun,
                                     Context::REGEXP_FUNCTION_INDEX);
    {
      // Setup %RegExpPrototype%.
      DirectHandle<JSObject> prototype(
          Cast<JSObject>(regexp_fun->instance_prototype()), isolate());
      native_context()->set_regexp_prototype(*prototype);
      {
        DirectHandle<JSFunction> fun =
            SimpleInstallFunction(isolate_, prototype, "exec",
                                  Builtin::kRegExpPrototypeExec, 1, kAdapt);
        native_context()->set_regexp_exec_function(*fun);
        DCHECK_EQ(JSRegExp::kExecFunctionDescriptorIndex,
                  prototype->map()->LastAdded().as_int());
      }
      SimpleInstallGetter(isolate_, prototype, factory->dotAll_string(),
                          Builtin::kRegExpPrototypeDotAllGetter, kAdapt);
      SimpleInstallGetter(isolate_, prototype, factory->flags_string(),
                          Builtin::kRegExpPrototypeFlagsGetter, kAdapt);
      SimpleInstallGetter(isolate_, prototype, factory->global_string(),
                          Builtin::kRegExpPrototypeGlobalGetter, kAdapt);
      SimpleInstallGetter(isolate(), prototype, factory->hasIndices_string(),
                          Builtin::kRegExpPrototypeHasIndicesGetter, kAdapt);
      SimpleInstallGetter(isolate_, prototype, factory->ignoreCase_string(),
                          Builtin::kRegExpPrototypeIgnoreCaseGetter, kAdapt);
      SimpleInstallGetter(isolate_, prototype, factory->multiline_string(),
                          Builtin::kRegExpPrototypeMultilineGetter, kAdapt);
      SimpleInstallGetter(isolate_, prototype, factory->source_string(),
                          Builtin::kRegExpPrototypeSourceGetter, kAdapt);
      SimpleInstallGetter(isolate_, prototype, factory->sticky_string(),
                          Builtin::kRegExpPrototypeStickyGetter, kAdapt);
      SimpleInstallGetter(isolate_, prototype, factory->unicode_string(),
                          Builtin::kRegExpPrototypeUnicodeGetter, kAdapt);
      SimpleInstallGetter(isolate(), prototype, factory->unicodeSets_string(),
                          Builtin::kRegExpPrototypeUnicodeSetsGetter, kAdapt);
      SimpleInstallFunction(isolate_, prototype, "compile",
                            Builtin::kRegExpPrototypeCompile, 2, kAdapt);
      SimpleInstallFunction(isolate_, prototype, "toString",
                            Builtin::kRegExpPrototypeToString, 0, kDontAdapt);
      SimpleInstallFunction(isolate_, prototype, "test",
                            Builtin::kRegExpPrototypeTest, 1, kAdapt);
      {
        DirectHandle<JSFunction> fun = InstallFunctionAtSymbol(
            isolate_, prototype, factory->match_symbol(), "[Symbol.match]",
            Builtin::kRegExpPrototypeMatch, 1, kAdapt);
        native_context()->set_regexp_match_function(*fun);
        DCHECK_EQ(JSRegExp::kSymbolMatchFunctionDescriptorIndex,
                  prototype->map()->LastAdded().as_int());
      }
      {
        DirectHandle<JSFunction> fun = InstallFunctionAtSymbol(
            isolate_, prototype, factory->match_all_symbol(),
            "[Symbol.matchAll]", Builtin::kRegExpPrototypeMatchAll, 1, kAdapt);
        native_context()->set_regexp_match_all_function(*fun);
        DCHECK_EQ(JSRegExp::kSymbolMatchAllFunctionDescriptorIndex,
                  prototype->map()->LastAdded().as_int());
      }
      {
        DirectHandle<JSFunction> fun = InstallFunctionAtSymbol(
            isolate_, prototype, factory->replace_symbol(), "[Symbol.replace]",
            Builtin::kRegExpPrototypeReplace, 2, kDontAdapt);
        native_context()->set_regexp_replace_function(*fun);
        DCHECK_EQ(JSRegExp::kSymbolReplaceFunctionDescriptorIndex,
                  prototype->map()->LastAdded().as_int());
      }
      {
        DirectHandle<JSFunction> fun = InstallFunctionAtSymbol(
            isolate_, prototype, factory->search_symbol(), "[Symbol.search]",
            Builtin::kRegExpPrototypeSearch, 1, kAdapt);
        native_context()->set_regexp_search_function(*fun);
        DCHECK_EQ(JSRegExp::kSymbolSearchFunctionDescriptorIndex,
                  prototype->map()->LastAdded().as_int());
      }
      {
        DirectHandle<JSFunction> fun = InstallFunctionAtSymbol(
            isolate_, prototype, factory->split_symbol(), "[Symbol.split]",
            Builtin::kRegExpPrototypeSplit, 2, kDontAdapt);
        native_context()->set_regexp_split_function(*fun);
        DCHECK_EQ(JSRegExp::kSymbolSplitFunctionDescriptorIndex,
                  prototype->map()->LastAdded().as_int());
      }
      DirectHandle<Map> prototype_map(prototype->map(), isolate());
      Map::SetShouldBeFastPrototypeMap(prototype_map, true, isolate_);
      CHECK_NE((*prototype_map).ptr(),
               isolate_->initial_object_prototype()->map().ptr());
      prototype_map->set_instance_type(JS_REG_EXP_PROTOTYPE_TYPE);
      // Store the initial RegExp.prototype map. This is used in fast-path
      // checks. Do not alter the prototype after this point.
      native_context()->set_regexp_prototype_map(*prototype_map);
    }
    {
      // RegExp getters and setters.
      InstallSpeciesGetter(isolate_, regexp_fun);
      // Static properties set by a successful match.
      SimpleInstallGetterSetter(isolate_, regexp_fun, factory->input_string(),
                                Builtin::kRegExpInputGetter,
                                Builtin::kRegExpInputSetter);
      SimpleInstallGetterSetter(isolate_, regexp_fun, "$_",
                                Builtin::kRegExpInputGetter,
                                Builtin::kRegExpInputSetter);
      SimpleInstallGetterSetter(isolate_, regexp_fun, "lastMatch",
                                Builtin::kRegExpLastMatchGetter,
                                Builtin::kEmptyFunction1);
      SimpleInstallGetterSetter(isolate_, regexp_fun, "$&",
                                Builtin::kRegExpLastMatchGetter,
                                Builtin::kEmptyFunction1);
      SimpleInstallGetterSetter(isolate_, regexp_fun, "lastParen",
                                Builtin::kRegExpLastParenGetter,
                                Builtin::kEmptyFunction1);
      SimpleInstallGetterSetter(isolate_, regexp_fun, "$+",
                                Builtin::kRegExpLastParenGetter,
                                Builtin::kEmptyFunction1);
      SimpleInstallGetterSetter(isolate_, regexp_fun, "leftContext",
                                Builtin::kRegExpLeftContextGetter,
                                Builtin::kEmptyFunction1);
      SimpleInstallGetterSetter(isolate_, regexp_fun, "$`",
                                Builtin::kRegExpLeftContextGetter,
                                Builtin::kEmptyFunction1);
      SimpleInstallGetterSetter(isolate_, regexp_fun, "rightContext",
                                Builtin::kRegExpRightContextGetter,
                                Builtin::kEmptyFunction1);
      SimpleInstallGetterSetter(isolate_, regexp_fun, "$'",
                                Builtin::kRegExpRightContextGetter,
                                Builtin::kEmptyFunction1);
#define INSTALL_CAPTURE_GETTER(i) \
  SimpleInstallGetterSetter(isolate_, regexp_fun, "$" #i, \
                            Builtin::kRegExpCapture##i##Getter, \
                            Builtin::kEmptyFunction1)
      INSTALL_CAPTURE_GETTER(1);
      INSTALL_CAPTURE_GETTER(2);
      INSTALL_CAPTURE_GETTER(3);
      INSTALL_CAPTURE_GETTER(4);
      INSTALL_CAPTURE_GETTER(5);
      INSTALL_CAPTURE_GETTER(6);
      INSTALL_CAPTURE_GETTER(7);
      INSTALL_CAPTURE_GETTER(8);
      INSTALL_CAPTURE_GETTER(9);
#undef INSTALL_CAPTURE_GETTER
    }
    SetConstructorInstanceType(isolate_, regexp_fun,
                               JS_REG_EXP_CONSTRUCTOR_TYPE);
    DCHECK(regexp_fun->has_initial_map());
    DirectHandle<Map> initial_map(regexp_fun->initial_map(), isolate());
    DCHECK_EQ(1, initial_map->GetInObjectProperties());
    Map::EnsureDescriptorSlack(isolate_, initial_map, 1);
    // ECMA-262, section 15.10.7.5.
    PropertyAttributes writable =
        static_cast<PropertyAttributes>(DONT_ENUM | DONT_DELETE);
    Descriptor d = Descriptor::DataField(isolate(), factory->lastIndex_string(),
                                         JSRegExp::kLastIndexFieldIndex,
                                         writable, Representation::Tagged());
    initial_map->AppendDescriptor(isolate(), &d);
    // Create the last match info.
    DirectHandle<RegExpMatchInfo> last_match_info =
        RegExpMatchInfo::New(isolate(), RegExpMatchInfo::kMinCapacity);
    native_context()->set_regexp_last_match_info(*last_match_info);
    DCHECK(regexp_fun->HasFastProperties());
  }
  { // --- R e g E x p S t r i n g I t e r a t o r ---
    DirectHandle<JSObject> iterator_prototype(
        native_context()->initial_iterator_prototype(), isolate());
    DirectHandle<JSObject> regexp_string_iterator_prototype =
        factory->NewJSObject(isolate()->object_function(),
                             AllocationType::kOld);
    JSObject::ForceSetPrototype(isolate(), regexp_string_iterator_prototype,
                                iterator_prototype);
    InstallToStringTag(isolate(), regexp_string_iterator_prototype,
                       "RegExp String Iterator");
    SimpleInstallFunction(isolate(), regexp_string_iterator_prototype, "next",
                          Builtin::kRegExpStringIteratorPrototypeNext, 0,
                          kAdapt);
    DirectHandle<JSFunction> regexp_string_iterator_function = CreateFunction(
        isolate(), "RegExpStringIterator", JS_REG_EXP_STRING_ITERATOR_TYPE,
        JSRegExpStringIterator::kHeaderSize, 0,
        regexp_string_iterator_prototype, Builtin::kIllegal, 0, kDontAdapt);
    regexp_string_iterator_function->shared()->set_native(false);
    native_context()->set_initial_regexp_string_iterator_prototype_map(
        regexp_string_iterator_function->initial_map());
  }
  // -- E r r o r
  InstallError(isolate_, global, factory->Error_string(),
               Context::ERROR_FUNCTION_INDEX);
  // -- A g g r e g a t e E r r o r
  InstallError(isolate_, global, factory->AggregateError_string(),
               Context::AGGREGATE_ERROR_FUNCTION_INDEX,
               Builtin::kAggregateErrorConstructor, 2);
  // -- E v a l E r r o r
  InstallError(isolate_, global, factory->EvalError_string(),
               Context::EVAL_ERROR_FUNCTION_INDEX);
  // -- R a n g e E r r o r
  InstallError(isolate_, global, factory->RangeError_string(),
               Context::RANGE_ERROR_FUNCTION_INDEX);
  // -- R e f e r e n c e E r r o r
  InstallError(isolate_, global, factory->ReferenceError_string(),
               Context::REFERENCE_ERROR_FUNCTION_INDEX);
  // -- S y n t a x E r r o r
  InstallError(isolate_, global, factory->SyntaxError_string(),
               Context::SYNTAX_ERROR_FUNCTION_INDEX);
  // -- T y p e E r r o r
  InstallError(isolate_, global, factory->TypeError_string(),
               Context::TYPE_ERROR_FUNCTION_INDEX);
  // -- U R I E r r o r
  InstallError(isolate_, global, factory->URIError_string(),
               Context::URI_ERROR_FUNCTION_INDEX);
  // Initialize the embedder data slot.
  // TODO(ishell): microtask queue pointer will be moved from native context
  // to the embedder data array so we don't need an empty embedder data array.
  DirectHandle<EmbedderDataArray> embedder_data =
      factory->NewEmbedderDataArray(0);
  native_context()->set_embedder_data(*embedder_data);
  { // -- g l o b a l T h i s
    DirectHandle<JSGlobalProxy> global_proxy(native_context()->global_proxy(),
                                             isolate_);
    JSObject::AddProperty(isolate_, global, factory->globalThis_string(),
                          global_proxy, DONT_ENUM);
  }
  { // -- J S O N
    DirectHandle<Map> raw_json_map = factory->NewContextfulMapForCurrentContext(
        JS_RAW_JSON_TYPE, JSRawJson::kInitialSize, TERMINAL_FAST_ELEMENTS_KIND,
        1);
    Map::EnsureDescriptorSlack(isolate_, raw_json_map, 1);
    {
      Descriptor d = Descriptor::DataField(
          isolate(), factory->raw_json_string(),
          JSRawJson::kRawJsonInitialIndex, NONE, Representation::Tagged());
      raw_json_map->AppendDescriptor(isolate(), &d);
    }
    raw_json_map->SetPrototype(isolate(), raw_json_map, factory->null_value());
    raw_json_map->SetConstructor(native_context()->object_function());
    native_context()->set_js_raw_json_map(*raw_json_map);
    DirectHandle<JSObject> json_object =
        factory->NewJSObject(isolate_->object_function(), AllocationType::kOld);
    JSObject::AddProperty(isolate_, global, "JSON", json_object, DONT_ENUM);
    SimpleInstallFunction(isolate_, json_object, "parse", Builtin::kJsonParse,
                          2, kDontAdapt);
    SimpleInstallFunction(isolate_, json_object, "stringify",
                          Builtin::kJsonStringify, 3, kAdapt);
    SimpleInstallFunction(isolate_, json_object, "rawJSON",
                          Builtin::kJsonRawJson, 1, kAdapt);
    SimpleInstallFunction(isolate_, json_object, "isRawJSON",
                          Builtin::kJsonIsRawJson, 1, kAdapt);
    InstallToStringTag(isolate_, json_object, "JSON");
    native_context()->set_json_object(*json_object);
  }
  { // -- M a t h
    DirectHandle<JSObject> math =
        factory->NewJSObject(isolate_->object_function(), AllocationType::kOld);
    JSObject::AddProperty(isolate_, global, "Math", math, DONT_ENUM);
    SimpleInstallFunction(isolate_, math, "abs", Builtin::kMathAbs, 1, kAdapt);
    SimpleInstallFunction(isolate_, math, "acos", Builtin::kMathAcos, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "acosh", Builtin::kMathAcosh, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "asin", Builtin::kMathAsin, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "asinh", Builtin::kMathAsinh, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "atan", Builtin::kMathAtan, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "atanh", Builtin::kMathAtanh, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "atan2", Builtin::kMathAtan2, 2,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "ceil", Builtin::kMathCeil, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "cbrt", Builtin::kMathCbrt, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "expm1", Builtin::kMathExpm1, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "clz32", Builtin::kMathClz32, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "cos", Builtin::kMathCos, 1, kAdapt);
    SimpleInstallFunction(isolate_, math, "cosh", Builtin::kMathCosh, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "exp", Builtin::kMathExp, 1, kAdapt);
    SimpleInstallFunction(isolate_, math, "floor", Builtin::kMathFloor, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "fround", Builtin::kMathFround, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "hypot", Builtin::kMathHypot, 2,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, math, "imul", Builtin::kMathImul, 2,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "log", Builtin::kMathLog, 1, kAdapt);
    SimpleInstallFunction(isolate_, math, "log1p", Builtin::kMathLog1p, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "log2", Builtin::kMathLog2, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "log10", Builtin::kMathLog10, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "max", Builtin::kMathMax, 2,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, math, "min", Builtin::kMathMin, 2,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, math, "pow", Builtin::kMathPow, 2, kAdapt);
    SimpleInstallFunction(isolate_, math, "random", Builtin::kMathRandom, 0,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "round", Builtin::kMathRound, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "sign", Builtin::kMathSign, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "sin", Builtin::kMathSin, 1, kAdapt);
    SimpleInstallFunction(isolate_, math, "sinh", Builtin::kMathSinh, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "sqrt", Builtin::kMathSqrt, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "tan", Builtin::kMathTan, 1, kAdapt);
    SimpleInstallFunction(isolate_, math, "tanh", Builtin::kMathTanh, 1,
                          kAdapt);
    SimpleInstallFunction(isolate_, math, "trunc", Builtin::kMathTrunc, 1,
                          kAdapt);
    // Install math constants.
    double const kE = base::ieee754::exp(1.0);
    double const kPI = 3.1415926535897932;
    InstallConstant(isolate_, math, "E", factory->NewNumber(kE));
    InstallConstant(isolate_, math, "LN10",
                    factory->NewNumber(base::ieee754::log(10.0)));
    InstallConstant(isolate_, math, "LN2",
                    factory->NewNumber(base::ieee754::log(2.0)));
    InstallConstant(isolate_, math, "LOG10E",
                    factory->NewNumber(base::ieee754::log10(kE)));
    InstallConstant(isolate_, math, "LOG2E",
                    factory->NewNumber(base::ieee754::log2(kE)));
    InstallConstant(isolate_, math, "PI", factory->NewNumber(kPI));
    InstallConstant(isolate_, math, "SQRT1_2",
                    factory->NewNumber(std::sqrt(0.5)));
    InstallConstant(isolate_, math, "SQRT2",
                    factory->NewNumber(std::sqrt(2.0)));
    InstallToStringTag(isolate_, math, "Math");
  }
#ifdef V8_INTL_SUPPORT
  { // -- I n t l
    DirectHandle<JSObject> intl =
        factory->NewJSObject(isolate_->object_function(), AllocationType::kOld);
    JSObject::AddProperty(isolate_, global, "Intl", intl, DONT_ENUM);
    // ecma402 #sec-Intl-toStringTag
    // The initial value of the @@toStringTag property is the string value
    // *"Intl"*.
    InstallToStringTag(isolate_, intl, "Intl");
    SimpleInstallFunction(isolate(), intl, "getCanonicalLocales",
                          Builtin::kIntlGetCanonicalLocales, 1, kDontAdapt);
    SimpleInstallFunction(isolate(), intl, "supportedValuesOf",
                          Builtin::kIntlSupportedValuesOf, 1, kDontAdapt);
    { // -- D a t e T i m e F o r m a t
      DirectHandle<JSFunction> date_time_format_constructor = InstallFunction(
          isolate_, intl, "DateTimeFormat", JS_DATE_TIME_FORMAT_TYPE,
          JSDateTimeFormat::kHeaderSize, 0, factory->the_hole_value(),
          Builtin::kDateTimeFormatConstructor, 0, kDontAdapt);
      InstallWithIntrinsicDefaultProto(
          isolate_, date_time_format_constructor,
          Context::INTL_DATE_TIME_FORMAT_FUNCTION_INDEX);
      SimpleInstallFunction(
          isolate(), date_time_format_constructor, "supportedLocalesOf",
          Builtin::kDateTimeFormatSupportedLocalesOf, 1, kDontAdapt);
      DirectHandle<JSObject> prototype(
          Cast<JSObject>(date_time_format_constructor->prototype()), isolate_);
      InstallToStringTag(isolate_, prototype, "Intl.DateTimeFormat");
      SimpleInstallFunction(isolate_, prototype, "resolvedOptions",
                            Builtin::kDateTimeFormatPrototypeResolvedOptions, 0,
                            kDontAdapt);
      SimpleInstallFunction(isolate_, prototype, "formatToParts",
                            Builtin::kDateTimeFormatPrototypeFormatToParts, 1,
                            kDontAdapt);
      SimpleInstallGetter(isolate_, prototype, factory->format_string(),
                          Builtin::kDateTimeFormatPrototypeFormat, kDontAdapt);
      SimpleInstallFunction(isolate_, prototype, "formatRange",
                            Builtin::kDateTimeFormatPrototypeFormatRange, 2,
                            kDontAdapt);
      SimpleInstallFunction(isolate_, prototype, "formatRangeToParts",
                            Builtin::kDateTimeFormatPrototypeFormatRangeToParts,
                            2, kDontAdapt);
    }
    { // -- N u m b e r F o r m a t
      DirectHandle<JSFunction> number_format_constructor = InstallFunction(
          isolate_, intl, "NumberFormat", JS_NUMBER_FORMAT_TYPE,
          JSNumberFormat::kHeaderSize, 0, factory->the_hole_value(),
          Builtin::kNumberFormatConstructor, 0, kDontAdapt);
      InstallWithIntrinsicDefaultProto(
          isolate_, number_format_constructor,
          Context::INTL_NUMBER_FORMAT_FUNCTION_INDEX);
      SimpleInstallFunction(
          isolate(), number_format_constructor, "supportedLocalesOf",
          Builtin::kNumberFormatSupportedLocalesOf, 1, kDontAdapt);
      DirectHandle<JSObject> prototype(
          Cast<JSObject>(number_format_constructor->prototype()), isolate_);
      InstallToStringTag(isolate_, prototype, "Intl.NumberFormat");
      SimpleInstallFunction(isolate_, prototype, "resolvedOptions",
                            Builtin::kNumberFormatPrototypeResolvedOptions, 0,
                            kDontAdapt);
      SimpleInstallFunction(isolate_, prototype, "formatToParts",
                            Builtin::kNumberFormatPrototypeFormatToParts, 1,
                            kDontAdapt);
      SimpleInstallGetter(isolate_, prototype, factory->format_string(),
                          Builtin::kNumberFormatPrototypeFormatNumber,
                          kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "formatRange",
                            Builtin::kNumberFormatPrototypeFormatRange, 2,
                            kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "formatRangeToParts",
                            Builtin::kNumberFormatPrototypeFormatRangeToParts,
                            2, kDontAdapt);
    }
    { // -- C o l l a t o r
      DirectHandle<JSFunction> collator_constructor =
          InstallFunction(isolate_, intl, "Collator", JS_COLLATOR_TYPE,
                          JSCollator::kHeaderSize, 0, factory->the_hole_value(),
                          Builtin::kCollatorConstructor, 0, kDontAdapt);
      InstallWithIntrinsicDefaultProto(isolate_, collator_constructor,
                                       Context::INTL_COLLATOR_FUNCTION_INDEX);
      SimpleInstallFunction(
          isolate(), collator_constructor, "supportedLocalesOf",
          Builtin::kCollatorSupportedLocalesOf, 1, kDontAdapt);
      DirectHandle<JSObject> prototype(
          Cast<JSObject>(collator_constructor->prototype()), isolate_);
      InstallToStringTag(isolate_, prototype, "Intl.Collator");
      SimpleInstallFunction(isolate_, prototype, "resolvedOptions",
                            Builtin::kCollatorPrototypeResolvedOptions, 0,
                            kDontAdapt);
      SimpleInstallGetter(isolate_, prototype, factory->compare_string(),
                          Builtin::kCollatorPrototypeCompare, kDontAdapt);
    }
    { // -- V 8 B r e a k I t e r a t o r
      DirectHandle<JSFunction> v8_break_iterator_constructor = InstallFunction(
          isolate_, intl, "v8BreakIterator", JS_V8_BREAK_ITERATOR_TYPE,
          JSV8BreakIterator::kHeaderSize, 0, factory->the_hole_value(),
          Builtin::kV8BreakIteratorConstructor, 0, kDontAdapt);
      SimpleInstallFunction(
          isolate_, v8_break_iterator_constructor, "supportedLocalesOf",
          Builtin::kV8BreakIteratorSupportedLocalesOf, 1, kDontAdapt);
      DirectHandle<JSObject> prototype(
          Cast<JSObject>(v8_break_iterator_constructor->prototype()), isolate_);
      InstallToStringTag(isolate_, prototype, factory->Object_string());
      SimpleInstallFunction(isolate_, prototype, "resolvedOptions",
                            Builtin::kV8BreakIteratorPrototypeResolvedOptions,
                            0, kDontAdapt);
      SimpleInstallGetter(isolate_, prototype, factory->adoptText_string(),
                          Builtin::kV8BreakIteratorPrototypeAdoptText,
                          kDontAdapt);
      SimpleInstallGetter(isolate_, prototype, factory->first_string(),
                          Builtin::kV8BreakIteratorPrototypeFirst, kDontAdapt);
      SimpleInstallGetter(isolate_, prototype, factory->next_string(),
                          Builtin::kV8BreakIteratorPrototypeNext, kDontAdapt);
      SimpleInstallGetter(isolate_, prototype, factory->current_string(),
                          Builtin::kV8BreakIteratorPrototypeCurrent,
                          kDontAdapt);
      SimpleInstallGetter(isolate_, prototype, factory->breakType_string(),
                          Builtin::kV8BreakIteratorPrototypeBreakType,
                          kDontAdapt);
    }
    { // -- P l u r a l R u l e s
      DirectHandle<JSFunction> plural_rules_constructor = InstallFunction(
          isolate_, intl, "PluralRules", JS_PLURAL_RULES_TYPE,
          JSPluralRules::kHeaderSize, 0, factory->the_hole_value(),
          Builtin::kPluralRulesConstructor, 0, kDontAdapt);
      InstallWithIntrinsicDefaultProto(
          isolate_, plural_rules_constructor,
          Context::INTL_PLURAL_RULES_FUNCTION_INDEX);
      SimpleInstallFunction(
          isolate(), plural_rules_constructor, "supportedLocalesOf",
          Builtin::kPluralRulesSupportedLocalesOf, 1, kDontAdapt);
      DirectHandle<JSObject> prototype(
          Cast<JSObject>(plural_rules_constructor->prototype()), isolate_);
      InstallToStringTag(isolate_, prototype, "Intl.PluralRules");
      SimpleInstallFunction(isolate_, prototype, "resolvedOptions",
                            Builtin::kPluralRulesPrototypeResolvedOptions, 0,
                            kDontAdapt);
      SimpleInstallFunction(isolate_, prototype, "select",
                            Builtin::kPluralRulesPrototypeSelect, 1,
                            kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "selectRange",
                            Builtin::kPluralRulesPrototypeSelectRange, 2,
                            kDontAdapt);
    }
    { // -- R e l a t i v e T i m e F o r m a t
      DirectHandle<JSFunction> relative_time_format_fun = InstallFunction(
          isolate(), intl, "RelativeTimeFormat", JS_RELATIVE_TIME_FORMAT_TYPE,
          JSRelativeTimeFormat::kHeaderSize, 0, factory->the_hole_value(),
          Builtin::kRelativeTimeFormatConstructor, 0, kDontAdapt);
      InstallWithIntrinsicDefaultProto(
          isolate_, relative_time_format_fun,
          Context::INTL_RELATIVE_TIME_FORMAT_FUNCTION_INDEX);
      SimpleInstallFunction(
          isolate(), relative_time_format_fun, "supportedLocalesOf",
          Builtin::kRelativeTimeFormatSupportedLocalesOf, 1, kDontAdapt);
      // Setup %RelativeTimeFormatPrototype%.
      DirectHandle<JSObject> prototype(
          Cast<JSObject>(relative_time_format_fun->instance_prototype()),
          isolate());
      InstallToStringTag(isolate(), prototype, "Intl.RelativeTimeFormat");
      SimpleInstallFunction(
          isolate(), prototype, "resolvedOptions",
          Builtin::kRelativeTimeFormatPrototypeResolvedOptions, 0, kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "format",
                            Builtin::kRelativeTimeFormatPrototypeFormat, 2,
                            kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "formatToParts",
                            Builtin::kRelativeTimeFormatPrototypeFormatToParts,
                            2, kDontAdapt);
    }
    { // -- L i s t F o r m a t
      DirectHandle<JSFunction> list_format_fun = InstallFunction(
          isolate(), intl, "ListFormat", JS_LIST_FORMAT_TYPE,
          JSListFormat::kHeaderSize, 0, factory->the_hole_value(),
          Builtin::kListFormatConstructor, 0, kDontAdapt);
      InstallWithIntrinsicDefaultProto(
          isolate_, list_format_fun, Context::INTL_LIST_FORMAT_FUNCTION_INDEX);
      SimpleInstallFunction(isolate(), list_format_fun, "supportedLocalesOf",
                            Builtin::kListFormatSupportedLocalesOf, 1,
                            kDontAdapt);
      // Setup %ListFormatPrototype%.
      DirectHandle<JSObject> prototype(
          Cast<JSObject>(list_format_fun->instance_prototype()), isolate());
      InstallToStringTag(isolate(), prototype, "Intl.ListFormat");
      SimpleInstallFunction(isolate(), prototype, "resolvedOptions",
                            Builtin::kListFormatPrototypeResolvedOptions, 0,
                            kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "format",
                            Builtin::kListFormatPrototypeFormat, 1, kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "formatToParts",
                            Builtin::kListFormatPrototypeFormatToParts, 1,
                            kDontAdapt);
    }
    { // -- L o c a l e
      DirectHandle<JSFunction> locale_fun =
          InstallFunction(isolate(), intl, "Locale", JS_LOCALE_TYPE,
                          JSLocale::kHeaderSize, 0, factory->the_hole_value(),
                          Builtin::kLocaleConstructor, 1, kDontAdapt);
      InstallWithIntrinsicDefaultProto(isolate(), locale_fun,
                                       Context::INTL_LOCALE_FUNCTION_INDEX);
      // Setup %LocalePrototype%.
      DirectHandle<JSObject> prototype(
          Cast<JSObject>(locale_fun->instance_prototype()), isolate());
      InstallToStringTag(isolate(), prototype, "Intl.Locale");
      SimpleInstallFunction(isolate(), prototype, "toString",
                            Builtin::kLocalePrototypeToString, 0, kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "maximize",
                            Builtin::kLocalePrototypeMaximize, 0, kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "minimize",
                            Builtin::kLocalePrototypeMinimize, 0, kDontAdapt);
      // Base locale getters.
      SimpleInstallGetter(isolate(), prototype, factory->language_string(),
                          Builtin::kLocalePrototypeLanguage, kAdapt);
      SimpleInstallGetter(isolate(), prototype, factory->script_string(),
                          Builtin::kLocalePrototypeScript, kAdapt);
      SimpleInstallGetter(isolate(), prototype, factory->region_string(),
                          Builtin::kLocalePrototypeRegion, kAdapt);
      SimpleInstallGetter(isolate(), prototype, factory->baseName_string(),
                          Builtin::kLocalePrototypeBaseName, kAdapt);
      // Unicode extension getters.
      SimpleInstallGetter(isolate(), prototype, factory->calendar_string(),
                          Builtin::kLocalePrototypeCalendar, kAdapt);
      SimpleInstallGetter(isolate(), prototype, factory->caseFirst_string(),
                          Builtin::kLocalePrototypeCaseFirst, kAdapt);
      SimpleInstallGetter(isolate(), prototype, factory->collation_string(),
                          Builtin::kLocalePrototypeCollation, kAdapt);
      SimpleInstallGetter(isolate(), prototype,
                          factory->firstDayOfWeek_string(),
                          Builtin::kLocalePrototypeFirstDayOfWeek, kAdapt);
      SimpleInstallGetter(isolate(), prototype, factory->hourCycle_string(),
                          Builtin::kLocalePrototypeHourCycle, kAdapt);
      SimpleInstallGetter(isolate(), prototype, factory->numeric_string(),
                          Builtin::kLocalePrototypeNumeric, kAdapt);
      SimpleInstallGetter(isolate(), prototype,
                          factory->numberingSystem_string(),
                          Builtin::kLocalePrototypeNumberingSystem, kAdapt);
      if (!v8_flags.harmony_remove_intl_locale_info_getters) {
        // Intl Locale Info functions
        SimpleInstallGetter(isolate(), prototype, factory->calendars_string(),
                            Builtin::kLocalePrototypeCalendars, kAdapt);
        SimpleInstallGetter(isolate(), prototype, factory->collations_string(),
                            Builtin::kLocalePrototypeCollations, kAdapt);
        SimpleInstallGetter(isolate(), prototype, factory->hourCycles_string(),
                            Builtin::kLocalePrototypeHourCycles, kAdapt);
        SimpleInstallGetter(isolate(), prototype,
                            factory->numberingSystems_string(),
                            Builtin::kLocalePrototypeNumberingSystems, kAdapt);
        SimpleInstallGetter(isolate(), prototype, factory->textInfo_string(),
                            Builtin::kLocalePrototypeTextInfo, kAdapt);
        SimpleInstallGetter(isolate(), prototype, factory->timeZones_string(),
                            Builtin::kLocalePrototypeTimeZones, kAdapt);
        SimpleInstallGetter(isolate(), prototype, factory->weekInfo_string(),
                            Builtin::kLocalePrototypeWeekInfo, kAdapt);
      }
      SimpleInstallFunction(isolate(), prototype, "getCalendars",
                            Builtin::kLocalePrototypeGetCalendars, 0,
                            kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "getCollations",
                            Builtin::kLocalePrototypeGetCollations, 0,
                            kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "getHourCycles",
                            Builtin::kLocalePrototypeGetHourCycles, 0,
                            kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "getNumberingSystems",
                            Builtin::kLocalePrototypeGetNumberingSystems, 0,
                            kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "getTimeZones",
                            Builtin::kLocalePrototypeGetTimeZones, 0,
                            kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "getTextInfo",
                            Builtin::kLocalePrototypeGetTextInfo, 0,
                            kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "getWeekInfo",
                            Builtin::kLocalePrototypeGetWeekInfo, 0,
                            kDontAdapt);
    }
    { // -- D i s p l a y N a m e s
      DirectHandle<JSFunction> display_names_fun = InstallFunction(
          isolate(), intl, "DisplayNames", JS_DISPLAY_NAMES_TYPE,
          JSDisplayNames::kHeaderSize, 0, factory->the_hole_value(),
          Builtin::kDisplayNamesConstructor, 2, kDontAdapt);
      InstallWithIntrinsicDefaultProto(
          isolate(), display_names_fun,
          Context::INTL_DISPLAY_NAMES_FUNCTION_INDEX);
      SimpleInstallFunction(isolate(), display_names_fun, "supportedLocalesOf",
                            Builtin::kDisplayNamesSupportedLocalesOf, 1,
                            kDontAdapt);
      {
        // Setup %DisplayNamesPrototype%.
        DirectHandle<JSObject> prototype(
            Cast<JSObject>(display_names_fun->instance_prototype()), isolate());
        InstallToStringTag(isolate(), prototype, "Intl.DisplayNames");
        SimpleInstallFunction(isolate(), prototype, "resolvedOptions",
                              Builtin::kDisplayNamesPrototypeResolvedOptions, 0,
                              kDontAdapt);
        SimpleInstallFunction(isolate(), prototype, "of",
                              Builtin::kDisplayNamesPrototypeOf, 1, kDontAdapt);
      }
    }
    { // -- S e g m e n t e r
      DirectHandle<JSFunction> segmenter_fun = InstallFunction(
          isolate(), intl, "Segmenter", JS_SEGMENTER_TYPE,
          JSSegmenter::kHeaderSize, 0, factory->the_hole_value(),
          Builtin::kSegmenterConstructor, 0, kDontAdapt);
      InstallWithIntrinsicDefaultProto(isolate_, segmenter_fun,
                                       Context::INTL_SEGMENTER_FUNCTION_INDEX);
      SimpleInstallFunction(isolate(), segmenter_fun, "supportedLocalesOf",
                            Builtin::kSegmenterSupportedLocalesOf, 1,
                            kDontAdapt);
      {
        // Setup %SegmenterPrototype%.
        DirectHandle<JSObject> prototype(
            Cast<JSObject>(segmenter_fun->instance_prototype()), isolate());
        // #sec-intl.segmenter.prototype-@@tostringtag
        //
        // Intl.Segmenter.prototype [ @@toStringTag ]
        //
        // The initial value of the @@toStringTag property is the String value
        // "Intl.Segmenter".
        InstallToStringTag(isolate(), prototype, "Intl.Segmenter");
        SimpleInstallFunction(isolate(), prototype, "resolvedOptions",
                              Builtin::kSegmenterPrototypeResolvedOptions, 0,
                              kDontAdapt);
        SimpleInstallFunction(isolate(), prototype, "segment",
                              Builtin::kSegmenterPrototypeSegment, 1,
                              kDontAdapt);
      }
      {
        // Setup %SegmentsPrototype%.
        DirectHandle<JSObject> prototype = factory->NewJSObject(
            isolate()->object_function(), AllocationType::kOld);
        DirectHandle<String> name_string =
            Name::ToFunctionName(isolate(), factory->Segments_string())
                .ToHandleChecked();
        DirectHandle<JSFunction> segments_fun = CreateFunction(
            isolate(), name_string, JS_SEGMENTS_TYPE, JSSegments::kHeaderSize,
            0, prototype, Builtin::kIllegal, 0, kDontAdapt);
        segments_fun->shared()->set_native(false);
        SimpleInstallFunction(isolate(), prototype, "containing",
                              Builtin::kSegmentsPrototypeContaining, 1,
                              kDontAdapt);
        InstallFunctionAtSymbol(isolate_, prototype, factory->iterator_symbol(),
                                "[Symbol.iterator]",
                                Builtin::kSegmentsPrototypeIterator, 0, kAdapt,
                                DONT_ENUM);
        DirectHandle<Map> segments_map(segments_fun->initial_map(), isolate());
        native_context()->set_intl_segments_map(*segments_map);
      }
      {
        // Setup %SegmentIteratorPrototype%.
        DirectHandle<JSObject> iterator_prototype(
            native_context()->initial_iterator_prototype(), isolate());
        DirectHandle<JSObject> prototype = factory->NewJSObject(
            isolate()->object_function(), AllocationType::kOld);
        JSObject::ForceSetPrototype(isolate(), prototype, iterator_prototype);
        // #sec-%segmentiteratorprototype%.@@tostringtag
        //
        // %SegmentIteratorPrototype% [ @@toStringTag ]
        //
        // The initial value of the @@toStringTag property is the String value
        // "Segmenter String Iterator".
        InstallToStringTag(isolate(), prototype, "Segmenter String Iterator");
        SimpleInstallFunction(isolate(), prototype, "next",
                              Builtin::kSegmentIteratorPrototypeNext, 0,
                              kDontAdapt);
        // Setup SegmentIterator constructor.
        DirectHandle<String> name_string =
            Name::ToFunctionName(isolate(), factory->SegmentIterator_string())
                .ToHandleChecked();
        DirectHandle<JSFunction> segment_iterator_fun =
            CreateFunction(isolate(), name_string, JS_SEGMENT_ITERATOR_TYPE,
                           JSSegmentIterator::kHeaderSize, 0, prototype,
                           Builtin::kIllegal, 0, kDontAdapt);
        segment_iterator_fun->shared()->set_native(false);
        DirectHandle<Map> segment_iterator_map(
            segment_iterator_fun->initial_map(), isolate());
        native_context()->set_intl_segment_iterator_map(*segment_iterator_map);
      }
      {
        // Set up the maps for SegmentDataObjects, with and without "isWordLike"
        // property.
        constexpr int kNumProperties = 3;
        constexpr int kNumPropertiesWithWordlike = kNumProperties + 1;
        constexpr int kInstanceSize =
            JSObject::kHeaderSize + kNumProperties * kTaggedSize;
        constexpr int kInstanceSizeWithWordlike =
            JSObject::kHeaderSize + kNumPropertiesWithWordlike * kTaggedSize;
        DirectHandle<Map> map = factory->NewContextfulMapForCurrentContext(
            JS_OBJECT_TYPE, kInstanceSize, TERMINAL_FAST_ELEMENTS_KIND,
            kNumProperties);
        DirectHandle<Map> map_with_wordlike =
            factory->NewContextfulMapForCurrentContext(
                JS_OBJECT_TYPE, kInstanceSizeWithWordlike,
                TERMINAL_FAST_ELEMENTS_KIND, kNumPropertiesWithWordlike);
        map->SetConstructor(native_context()->object_function());
        map_with_wordlike->SetConstructor(native_context()->object_function());
        map->set_prototype(*isolate_->initial_object_prototype());
        map_with_wordlike->set_prototype(*isolate_->initial_object_prototype());
        Map::EnsureDescriptorSlack(isolate_, map, kNumProperties);
        Map::EnsureDescriptorSlack(isolate_, map_with_wordlike,
                                   kNumPropertiesWithWordlike);
        int index = 0;
        { // segment
          Descriptor d =
              Descriptor::DataField(isolate_, factory->segment_string(),
                                    index++, NONE, Representation::Tagged());
          map->AppendDescriptor(isolate_, &d);
          map_with_wordlike->AppendDescriptor(isolate_, &d);
        }
        { // index
          Descriptor d =
              Descriptor::DataField(isolate_, factory->index_string(), index++,
                                    NONE, Representation::Tagged());
          map->AppendDescriptor(isolate_, &d);
          map_with_wordlike->AppendDescriptor(isolate_, &d);
        }
        { // input
          Descriptor d =
              Descriptor::DataField(isolate_, factory->input_string(), index++,
                                    NONE, Representation::Tagged());
          map->AppendDescriptor(isolate_, &d);
          map_with_wordlike->AppendDescriptor(isolate_, &d);
        }
        DCHECK_EQ(index, kNumProperties);
        { // isWordLike
          Descriptor d =
              Descriptor::DataField(isolate_, factory->isWordLike_string(),
                                    index++, NONE, Representation::Tagged());
          map_with_wordlike->AppendDescriptor(isolate_, &d);
        }
        DCHECK_EQ(index, kNumPropertiesWithWordlike);
        DCHECK(!map->is_dictionary_map());
        DCHECK(!map_with_wordlike->is_dictionary_map());
        native_context()->set_intl_segment_data_object_map(*map);
        native_context()->set_intl_segment_data_object_wordlike_map(
            *map_with_wordlike);
      }
    }
    { // -- D u r a t i o n F o r m a t
      DirectHandle<JSFunction> duration_format_fun = InstallFunction(
          isolate(), intl, "DurationFormat", JS_DURATION_FORMAT_TYPE,
          JSDurationFormat::kHeaderSize, 0, factory->the_hole_value(),
          Builtin::kDurationFormatConstructor, 0, kDontAdapt);
      InstallWithIntrinsicDefaultProto(
          isolate(), duration_format_fun,
          Context::INTL_DURATION_FORMAT_FUNCTION_INDEX);
      SimpleInstallFunction(
          isolate(), duration_format_fun, "supportedLocalesOf",
          Builtin::kDurationFormatSupportedLocalesOf, 1, kDontAdapt);
      DirectHandle<JSObject> prototype(
          Cast<JSObject>(duration_format_fun->instance_prototype()), isolate());
      InstallToStringTag(isolate(), prototype, "Intl.DurationFormat");
      SimpleInstallFunction(isolate(), prototype, "resolvedOptions",
                            Builtin::kDurationFormatPrototypeResolvedOptions, 0,
                            kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "format",
                            Builtin::kDurationFormatPrototypeFormat, 1,
                            kDontAdapt);
      SimpleInstallFunction(isolate(), prototype, "formatToParts",
                            Builtin::kDurationFormatPrototypeFormatToParts, 1,
                            kDontAdapt);
    }
  }
#endif // V8_INTL_SUPPORT
  { // -- A r r a y B u f f e r
    DirectHandle<String> name = factory->ArrayBuffer_string();
    DirectHandle<JSFunction> array_buffer_fun =
        CreateArrayBuffer(name, ARRAY_BUFFER);
    JSObject::AddProperty(isolate_, global, name, array_buffer_fun, DONT_ENUM);
    InstallWithIntrinsicDefaultProto(isolate_, array_buffer_fun,
                                     Context::ARRAY_BUFFER_FUN_INDEX);
    InstallSpeciesGetter(isolate_, array_buffer_fun);
    DirectHandle<JSFunction> array_buffer_noinit_fun = SimpleCreateFunction(
        isolate_,
        factory->InternalizeUtf8String(
            "arrayBufferConstructor_DoNotInitialize"),
        Builtin::kArrayBufferConstructor_DoNotInitialize, 1, kDontAdapt);
    native_context()->set_array_buffer_noinit_fun(*array_buffer_noinit_fun);
    DirectHandle<JSObject> array_buffer_prototype(
        Cast<JSObject>(array_buffer_fun->instance_prototype()), isolate_);
    SimpleInstallGetter(isolate_, array_buffer_prototype,
                        factory->max_byte_length_string(),
                        Builtin::kArrayBufferPrototypeGetMaxByteLength, kAdapt);
    SimpleInstallGetter(isolate_, array_buffer_prototype,
                        factory->resizable_string(),
                        Builtin::kArrayBufferPrototypeGetResizable, kAdapt);
    SimpleInstallFunction(isolate_, array_buffer_prototype, "resize",
                          Builtin::kArrayBufferPrototypeResize, 1, kAdapt);
    SimpleInstallFunction(isolate_, array_buffer_prototype, "transfer",
                          Builtin::kArrayBufferPrototypeTransfer, 0,
                          kDontAdapt);
    SimpleInstallFunction(
        isolate_, array_buffer_prototype, "transferToFixedLength",
        Builtin::kArrayBufferPrototypeTransferToFixedLength, 0, kDontAdapt);
    SimpleInstallGetter(isolate_, array_buffer_prototype,
                        factory->detached_string(),
                        Builtin::kArrayBufferPrototypeGetDetached, kAdapt);
  }
  { // -- S h a r e d A r r a y B u f f e r
    DirectHandle<String> name = factory->SharedArrayBuffer_string();
    DirectHandle<JSFunction> shared_array_buffer_fun =
        CreateArrayBuffer(name, SHARED_ARRAY_BUFFER);
    InstallWithIntrinsicDefaultProto(isolate_, shared_array_buffer_fun,
                                     Context::SHARED_ARRAY_BUFFER_FUN_INDEX);
    InstallSpeciesGetter(isolate_, shared_array_buffer_fun);
    DirectHandle<JSObject> shared_array_buffer_prototype(
        Cast<JSObject>(shared_array_buffer_fun->instance_prototype()),
        isolate_);
    SimpleInstallGetter(isolate_, shared_array_buffer_prototype,
                        factory->max_byte_length_string(),
                        Builtin::kSharedArrayBufferPrototypeGetMaxByteLength,
                        kAdapt);
    SimpleInstallGetter(
        isolate_, shared_array_buffer_prototype, factory->growable_string(),
        Builtin::kSharedArrayBufferPrototypeGetGrowable, kAdapt);
    SimpleInstallFunction(isolate_, shared_array_buffer_prototype, "grow",
                          Builtin::kSharedArrayBufferPrototypeGrow, 1, kAdapt);
  }
  { // -- A t o m i c s
    DirectHandle<JSObject> atomics_object =
        factory->NewJSObject(isolate_->object_function(), AllocationType::kOld);
    JSObject::AddProperty(isolate_, global, "Atomics", atomics_object,
                          DONT_ENUM);
    InstallToStringTag(isolate_, atomics_object, "Atomics");
    SimpleInstallFunction(isolate_, atomics_object, "load",
                          Builtin::kAtomicsLoad, 2, kAdapt);
    SimpleInstallFunction(isolate_, atomics_object, "store",
                          Builtin::kAtomicsStore, 3, kAdapt);
    SimpleInstallFunction(isolate_, atomics_object, "add", Builtin::kAtomicsAdd,
                          3, kAdapt);
    SimpleInstallFunction(isolate_, atomics_object, "sub", Builtin::kAtomicsSub,
                          3, kAdapt);
    SimpleInstallFunction(isolate_, atomics_object, "and", Builtin::kAtomicsAnd,
                          3, kAdapt);
    SimpleInstallFunction(isolate_, atomics_object, "or", Builtin::kAtomicsOr,
                          3, kAdapt);
    SimpleInstallFunction(isolate_, atomics_object, "xor", Builtin::kAtomicsXor,
                          3, kAdapt);
    SimpleInstallFunction(isolate_, atomics_object, "exchange",
                          Builtin::kAtomicsExchange, 3, kAdapt);
    SimpleInstallFunction(isolate_, atomics_object, "compareExchange",
                          Builtin::kAtomicsCompareExchange, 4, kAdapt);
    SimpleInstallFunction(isolate_, atomics_object, "isLockFree",
                          Builtin::kAtomicsIsLockFree, 1, kAdapt);
    SimpleInstallFunction(isolate_, atomics_object, "wait",
                          Builtin::kAtomicsWait, 4, kAdapt);
    SimpleInstallFunction(isolate(), atomics_object, "waitAsync",
                          Builtin::kAtomicsWaitAsync, 4, kAdapt);
    SimpleInstallFunction(isolate_, atomics_object, "notify",
                          Builtin::kAtomicsNotify, 3, kAdapt);
  }
  { // -- T y p e d A r r a y
    DirectHandle<JSFunction> typed_array_fun =
        CreateFunction(isolate_, factory->InternalizeUtf8String("TypedArray"),
                       JS_TYPED_ARRAY_TYPE, JSTypedArray::kHeaderSize, 0,
                       factory->the_hole_value(),
                       Builtin::kTypedArrayBaseConstructor, 0, kAdapt);
    typed_array_fun->shared()->set_native(false);
    InstallSpeciesGetter(isolate_, typed_array_fun);
    native_context()->set_typed_array_function(*typed_array_fun);
    SimpleInstallFunction(isolate_, typed_array_fun, "of",
                          Builtin::kTypedArrayOf, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, typed_array_fun, "from",
                          Builtin::kTypedArrayFrom, 1, kDontAdapt);
    // Setup %TypedArrayPrototype%.
    DirectHandle<JSObject> prototype(
        Cast<JSObject>(typed_array_fun->instance_prototype()), isolate());
    native_context()->set_typed_array_prototype(*prototype);
    // Install the "buffer", "byteOffset", "byteLength", "length"
    // and @@toStringTag getters on the {prototype}.
    SimpleInstallGetter(isolate_, prototype, factory->buffer_string(),
                        Builtin::kTypedArrayPrototypeBuffer, kDontAdapt);
    SimpleInstallGetter(isolate_, prototype, factory->byte_length_string(),
                        Builtin::kTypedArrayPrototypeByteLength, kAdapt);
    SimpleInstallGetter(isolate_, prototype, factory->byte_offset_string(),
                        Builtin::kTypedArrayPrototypeByteOffset, kAdapt);
    SimpleInstallGetter(isolate_, prototype, factory->length_string(),
                        Builtin::kTypedArrayPrototypeLength, kAdapt);
    SimpleInstallGetter(isolate_, prototype, factory->to_string_tag_symbol(),
                        Builtin::kTypedArrayPrototypeToStringTag, kAdapt);
    // Install "keys", "values" and "entries" methods on the {prototype}.
    InstallFunctionWithBuiltinId(isolate_, prototype, "entries",
                                 Builtin::kTypedArrayPrototypeEntries, 0,
                                 kDontAdapt);
    InstallFunctionWithBuiltinId(isolate_, prototype, "keys",
                                 Builtin::kTypedArrayPrototypeKeys, 0,
                                 kDontAdapt);
    DirectHandle<JSFunction> values = InstallFunctionWithBuiltinId(
        isolate_, prototype, "values", Builtin::kTypedArrayPrototypeValues, 0,
        kDontAdapt);
    JSObject::AddProperty(isolate_, prototype, factory->iterator_symbol(),
                          values, DONT_ENUM);
    // TODO(caitp): alphasort accessors/methods
    SimpleInstallFunction(isolate_, prototype, "at",
                          Builtin::kTypedArrayPrototypeAt, 1, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "copyWithin",
                          Builtin::kTypedArrayPrototypeCopyWithin, 2,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "every",
                          Builtin::kTypedArrayPrototypeEvery, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "fill",
                          Builtin::kTypedArrayPrototypeFill, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "filter",
                          Builtin::kTypedArrayPrototypeFilter, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "find",
                          Builtin::kTypedArrayPrototypeFind, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "findIndex",
                          Builtin::kTypedArrayPrototypeFindIndex, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "findLast",
                          Builtin::kTypedArrayPrototypeFindLast, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "findLastIndex",
                          Builtin::kTypedArrayPrototypeFindLastIndex, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "forEach",
                          Builtin::kTypedArrayPrototypeForEach, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "includes",
                          Builtin::kTypedArrayPrototypeIncludes, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "indexOf",
                          Builtin::kTypedArrayPrototypeIndexOf, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "join",
                          Builtin::kTypedArrayPrototypeJoin, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "lastIndexOf",
                          Builtin::kTypedArrayPrototypeLastIndexOf, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "map",
                          Builtin::kTypedArrayPrototypeMap, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "reverse",
                          Builtin::kTypedArrayPrototypeReverse, 0, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "reduce",
                          Builtin::kTypedArrayPrototypeReduce, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "reduceRight",
                          Builtin::kTypedArrayPrototypeReduceRight, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "set",
                          Builtin::kTypedArrayPrototypeSet, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "slice",
                          Builtin::kTypedArrayPrototypeSlice, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "some",
                          Builtin::kTypedArrayPrototypeSome, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "sort",
                          Builtin::kTypedArrayPrototypeSort, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "subarray",
                          Builtin::kTypedArrayPrototypeSubArray, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toReversed",
                          Builtin::kTypedArrayPrototypeToReversed, 0,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "toSorted",
                          Builtin::kTypedArrayPrototypeToSorted, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "with",
                          Builtin::kTypedArrayPrototypeWith, 2, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "toLocaleString",
                          Builtin::kTypedArrayPrototypeToLocaleString, 0,
                          kDontAdapt);
    JSObject::AddProperty(isolate_, prototype, factory->toString_string(),
                          array_prototype_to_string_fun, DONT_ENUM);
  }
  { // -- T y p e d A r r a y s
#define INSTALL_TYPED_ARRAY(Type, type, TYPE, ctype) \
  { \
    DirectHandle<JSFunction> fun = InstallTypedArray(\
        #Type "Array", TYPE##_ELEMENTS, TYPE##_TYPED_ARRAY_CONSTRUCTOR_TYPE, \
        Context::RAB_GSAB_##TYPE##_ARRAY_MAP_INDEX); \
    InstallWithIntrinsicDefaultProto(isolate_, fun, \
                                     Context::TYPE##_ARRAY_FUN_INDEX); \
  }
    TYPED_ARRAYS_BASE(INSTALL_TYPED_ARRAY)
#undef INSTALL_TYPED_ARRAY
  }
  { // -- D a t a V i e w
    DirectHandle<JSFunction> data_view_fun = InstallFunction(
        isolate_, global, "DataView", JS_DATA_VIEW_TYPE,
        JSDataView::kSizeWithEmbedderFields, 0, factory->the_hole_value(),
        Builtin::kDataViewConstructor, 1, kDontAdapt);
    InstallWithIntrinsicDefaultProto(isolate_, data_view_fun,
                                     Context::DATA_VIEW_FUN_INDEX);
    // Setup %DataViewPrototype%.
    DirectHandle<JSObject> prototype(
        Cast<JSObject>(data_view_fun->instance_prototype()), isolate());
    InstallToStringTag(isolate_, prototype, "DataView");
    // Setup objects needed for the JSRabGsabDataView.
    DirectHandle<Map> rab_gsab_data_view_map =
        factory->NewContextfulMapForCurrentContext(
            JS_RAB_GSAB_DATA_VIEW_TYPE, JSDataView::kSizeWithEmbedderFields,
            TERMINAL_FAST_ELEMENTS_KIND);
    Map::SetPrototype(isolate(), rab_gsab_data_view_map, prototype);
    rab_gsab_data_view_map->SetConstructor(*data_view_fun);
    native_context()->set_js_rab_gsab_data_view_map(*rab_gsab_data_view_map);
    // Install the "buffer", "byteOffset" and "byteLength" getters
    // on the {prototype}.
    SimpleInstallGetter(isolate_, prototype, factory->buffer_string(),
                        Builtin::kDataViewPrototypeGetBuffer, kDontAdapt);
    SimpleInstallGetter(isolate_, prototype, factory->byte_length_string(),
                        Builtin::kDataViewPrototypeGetByteLength, kDontAdapt);
    SimpleInstallGetter(isolate_, prototype, factory->byte_offset_string(),
                        Builtin::kDataViewPrototypeGetByteOffset, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getInt8",
                          Builtin::kDataViewPrototypeGetInt8, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "setInt8",
                          Builtin::kDataViewPrototypeSetInt8, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getUint8",
                          Builtin::kDataViewPrototypeGetUint8, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "setUint8",
                          Builtin::kDataViewPrototypeSetUint8, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getInt16",
                          Builtin::kDataViewPrototypeGetInt16, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "setInt16",
                          Builtin::kDataViewPrototypeSetInt16, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getUint16",
                          Builtin::kDataViewPrototypeGetUint16, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "setUint16",
                          Builtin::kDataViewPrototypeSetUint16, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getInt32",
                          Builtin::kDataViewPrototypeGetInt32, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "setInt32",
                          Builtin::kDataViewPrototypeSetInt32, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getUint32",
                          Builtin::kDataViewPrototypeGetUint32, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "setUint32",
                          Builtin::kDataViewPrototypeSetUint32, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getFloat32",
                          Builtin::kDataViewPrototypeGetFloat32, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "setFloat32",
                          Builtin::kDataViewPrototypeSetFloat32, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getFloat64",
                          Builtin::kDataViewPrototypeGetFloat64, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "setFloat64",
                          Builtin::kDataViewPrototypeSetFloat64, 2, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getBigInt64",
                          Builtin::kDataViewPrototypeGetBigInt64, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "setBigInt64",
                          Builtin::kDataViewPrototypeSetBigInt64, 2,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "getBigUint64",
                          Builtin::kDataViewPrototypeGetBigUint64, 1,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "setBigUint64",
                          Builtin::kDataViewPrototypeSetBigUint64, 2,
                          kDontAdapt);
  }
  { // -- M a p
    DirectHandle<JSFunction> js_map_fun = InstallFunction(
        isolate_, global, "Map", JS_MAP_TYPE, JSMap::kHeaderSize, 0,
        factory->the_hole_value(), Builtin::kMapConstructor, 0, kDontAdapt);
    InstallWithIntrinsicDefaultProto(isolate_, js_map_fun,
                                     Context::JS_MAP_FUN_INDEX);
    SimpleInstallFunction(isolate_, js_map_fun, "groupBy", Builtin::kMapGroupBy,
                          2, kAdapt);
    // Setup %MapPrototype%.
    DirectHandle<JSObject> prototype(
        Cast<JSObject>(js_map_fun->instance_prototype()), isolate());
    InstallToStringTag(isolate_, prototype, factory->Map_string());
    DirectHandle<JSFunction> map_get = SimpleInstallFunction(
        isolate_, prototype, "get", Builtin::kMapPrototypeGet, 1, kAdapt);
    native_context()->set_map_get(*map_get);
    DirectHandle<JSFunction> map_set = SimpleInstallFunction(
        isolate_, prototype, "set", Builtin::kMapPrototypeSet, 2, kAdapt);
    // Check that index of "set" function in JSCollection is correct.
    DCHECK_EQ(JSCollection::kAddFunctionDescriptorIndex,
              prototype->map()->LastAdded().as_int());
    native_context()->set_map_set(*map_set);
    DirectHandle<JSFunction> map_has = SimpleInstallFunction(
        isolate_, prototype, "has", Builtin::kMapPrototypeHas, 1, kAdapt);
    native_context()->set_map_has(*map_has);
    DirectHandle<JSFunction> map_delete = SimpleInstallFunction(
        isolate_, prototype, "delete", Builtin::kMapPrototypeDelete, 1, kAdapt);
    native_context()->set_map_delete(*map_delete);
    SimpleInstallFunction(isolate_, prototype, "clear",
                          Builtin::kMapPrototypeClear, 0, kAdapt);
    DirectHandle<JSFunction> entries =
        SimpleInstallFunction(isolate_, prototype, "entries",
                              Builtin::kMapPrototypeEntries, 0, kAdapt);
    JSObject::AddProperty(isolate_, prototype, factory->iterator_symbol(),
                          entries, DONT_ENUM);
    SimpleInstallFunction(isolate_, prototype, "forEach",
                          Builtin::kMapPrototypeForEach, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "keys",
                          Builtin::kMapPrototypeKeys, 0, kAdapt);
    SimpleInstallGetter(isolate_, prototype,
                        factory->InternalizeUtf8String("size"),
                        Builtin::kMapPrototypeGetSize, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "values",
                          Builtin::kMapPrototypeValues, 0, kAdapt);
    native_context()->set_initial_map_prototype_map(prototype->map());
    InstallSpeciesGetter(isolate_, js_map_fun);
    DCHECK(js_map_fun->HasFastProperties());
    native_context()->set_js_map_map(js_map_fun->initial_map());
  }
  { // -- B i g I n t
    DirectHandle<JSFunction> bigint_fun = InstallFunction(
        isolate_, global, "BigInt", JS_PRIMITIVE_WRAPPER_TYPE,
        JSPrimitiveWrapper::kHeaderSize, 0, factory->the_hole_value(),
        Builtin::kBigIntConstructor, 1, kDontAdapt);
    InstallWithIntrinsicDefaultProto(isolate_, bigint_fun,
                                     Context::BIGINT_FUNCTION_INDEX);
    // Install the properties of the BigInt constructor.
    // asUintN(bits, bigint)
    SimpleInstallFunction(isolate_, bigint_fun, "asUintN",
                          Builtin::kBigIntAsUintN, 2, kDontAdapt);
    // asIntN(bits, bigint)
    SimpleInstallFunction(isolate_, bigint_fun, "asIntN",
                          Builtin::kBigIntAsIntN, 2, kDontAdapt);
    // Set up the %BigIntPrototype%.
    DirectHandle<JSObject> prototype(
        Cast<JSObject>(bigint_fun->instance_prototype()), isolate_);
    JSFunction::SetPrototype(isolate_, bigint_fun, prototype);
    // Install the properties of the BigInt.prototype.
    // "constructor" is created implicitly by InstallFunction() above.
    // toLocaleString([reserved1 [, reserved2]])
    SimpleInstallFunction(isolate_, prototype, "toLocaleString",
                          Builtin::kBigIntPrototypeToLocaleString, 0,
                          kDontAdapt);
    // toString([radix])
    SimpleInstallFunction(isolate_, prototype, "toString",
                          Builtin::kBigIntPrototypeToString, 0, kDontAdapt);
    // valueOf()
    SimpleInstallFunction(isolate_, prototype, "valueOf",
                          Builtin::kBigIntPrototypeValueOf, 0, kDontAdapt);
    // @@toStringTag
    InstallToStringTag(isolate_, prototype, factory->BigInt_string());
  }
  { // -- S e t
    DirectHandle<JSFunction> js_set_fun = InstallFunction(
        isolate_, global, "Set", JS_SET_TYPE, JSSet::kHeaderSize, 0,
        factory->the_hole_value(), Builtin::kSetConstructor, 0, kDontAdapt);
    InstallWithIntrinsicDefaultProto(isolate_, js_set_fun,
                                     Context::JS_SET_FUN_INDEX);
    // Setup %SetPrototype%.
    DirectHandle<JSObject> prototype(
        Cast<JSObject>(js_set_fun->instance_prototype()), isolate());
    InstallToStringTag(isolate_, prototype, factory->Set_string());
    DirectHandle<JSFunction> set_has = SimpleInstallFunction(
        isolate_, prototype, "has", Builtin::kSetPrototypeHas, 1, kAdapt);
    native_context()->set_set_has(*set_has);
    DirectHandle<JSFunction> set_add = SimpleInstallFunction(
        isolate_, prototype, "add", Builtin::kSetPrototypeAdd, 1, kAdapt);
    // Check that index of "add" function in JSCollection is correct.
    DCHECK_EQ(JSCollection::kAddFunctionDescriptorIndex,
              prototype->map()->LastAdded().as_int());
    native_context()->set_set_add(*set_add);
    DirectHandle<JSFunction> set_delete = SimpleInstallFunction(
        isolate_, prototype, "delete", Builtin::kSetPrototypeDelete, 1, kAdapt);
    native_context()->set_set_delete(*set_delete);
    SimpleInstallFunction(isolate_, prototype, "difference",
                          Builtin::kSetPrototypeDifference, 1, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "clear",
                          Builtin::kSetPrototypeClear, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "entries",
                          Builtin::kSetPrototypeEntries, 0, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "forEach",
                          Builtin::kSetPrototypeForEach, 1, kDontAdapt);
    SimpleInstallFunction(isolate_, prototype, "intersection",
                          Builtin::kSetPrototypeIntersection, 1, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "isSubsetOf",
                          Builtin::kSetPrototypeIsSubsetOf, 1, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "isSupersetOf",
                          Builtin::kSetPrototypeIsSupersetOf, 1, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "isDisjointFrom",
                          Builtin::kSetPrototypeIsDisjointFrom, 1, kAdapt);
    SimpleInstallGetter(isolate_, prototype,
                        factory->InternalizeUtf8String("size"),
                        Builtin::kSetPrototypeGetSize, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "symmetricDifference",
                          Builtin::kSetPrototypeSymmetricDifference, 1, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "union",
                          Builtin::kSetPrototypeUnion, 1, kAdapt);
    DirectHandle<JSFunction> values = SimpleInstallFunction(
        isolate_, prototype, "values", Builtin::kSetPrototypeValues, 0, kAdapt);
    JSObject::AddProperty(isolate_, prototype, factory->keys_string(), values,
                          DONT_ENUM);
    JSObject::AddProperty(isolate_, prototype, factory->iterator_symbol(),
                          values, DONT_ENUM);
    native_context()->set_initial_set_prototype_map(prototype->map());
    native_context()->set_initial_set_prototype(*prototype);
    InstallSpeciesGetter(isolate_, js_set_fun);
    DCHECK(js_set_fun->HasFastProperties());
    native_context()->set_js_set_map(js_set_fun->initial_map());
    CHECK_NE(prototype->map().ptr(),
             isolate_->initial_object_prototype()->map().ptr());
    prototype->map()->set_instance_type(JS_SET_PROTOTYPE_TYPE);
  }
  { // -- J S M o d u l e N a m e s p a c e
    DirectHandle<Map> map = factory->NewContextfulMapForCurrentContext(
        JS_MODULE_NAMESPACE_TYPE, JSModuleNamespace::kSize,
        TERMINAL_FAST_ELEMENTS_KIND, JSModuleNamespace::kInObjectFieldCount);
    map->SetConstructor(native_context()->object_function());
    Map::SetPrototype(isolate(), map, isolate_->factory()->null_value());
    Map::EnsureDescriptorSlack(isolate_, map, 1);
    native_context()->set_js_module_namespace_map(*map);
    { // Install @@toStringTag.
      PropertyAttributes attribs =
          static_cast<PropertyAttributes>(DONT_DELETE | DONT_ENUM | READ_ONLY);
      Descriptor d =
          Descriptor::DataField(isolate(), factory->to_string_tag_symbol(),
                                JSModuleNamespace::kToStringTagFieldIndex,
                                attribs, Representation::Tagged());
      map->AppendDescriptor(isolate(), &d);
    }
  }
  { // -- I t e r a t o r and helpers
    DirectHandle<JSObject> iterator_prototype(
        native_context()->initial_iterator_prototype(), isolate());
    DirectHandle<JSFunction> iterator_function = InstallFunction(
        isolate(), global, "Iterator", JS_OBJECT_TYPE, JSObject::kHeaderSize, 0,
        iterator_prototype, Builtin::kIteratorConstructor, 0, kAdapt);
    SimpleInstallFunction(isolate(), iterator_function, "from",
                          Builtin::kIteratorFrom, 1, kAdapt);
    InstallWithIntrinsicDefaultProto(isolate(), iterator_function,
                                     Context::ITERATOR_FUNCTION_INDEX);
    // --- %WrapForValidIteratorPrototype%
    DirectHandle<JSObject> wrap_for_valid_iterator_prototype =
        factory->NewJSObject(isolate()->object_function(),
                             AllocationType::kOld);
    JSObject::ForceSetPrototype(isolate(), wrap_for_valid_iterator_prototype,
                                iterator_prototype);
    JSObject::AddProperty(isolate(), iterator_prototype,
                          factory->constructor_string(), iterator_function,
                          DONT_ENUM);
    SimpleInstallFunction(isolate(), wrap_for_valid_iterator_prototype, "next",
                          Builtin::kWrapForValidIteratorPrototypeNext, 0,
                          kAdapt);
    SimpleInstallFunction(
        isolate(), wrap_for_valid_iterator_prototype, "return",
        Builtin::kWrapForValidIteratorPrototypeReturn, 0, kAdapt);
    DirectHandle<Map> valid_iterator_wrapper_map =
        factory->NewContextfulMapForCurrentContext(
            JS_VALID_ITERATOR_WRAPPER_TYPE, JSValidIteratorWrapper::kHeaderSize,
            TERMINAL_FAST_ELEMENTS_KIND, 0);
    Map::SetPrototype(isolate(), valid_iterator_wrapper_map,
                      wrap_for_valid_iterator_prototype);
    valid_iterator_wrapper_map->SetConstructor(*iterator_function);
    native_context()->set_valid_iterator_wrapper_map(
        *valid_iterator_wrapper_map);
    // --- %IteratorHelperPrototype%
    DirectHandle<JSObject> iterator_helper_prototype = factory->NewJSObject(
        isolate()->object_function(), AllocationType::kOld);
    JSObject::ForceSetPrototype(isolate(), iterator_helper_prototype,
                                iterator_prototype);
    InstallToStringTag(isolate(), iterator_helper_prototype, "Iterator Helper");
    SimpleInstallFunction(isolate(), iterator_helper_prototype, "next",
                          Builtin::kIteratorHelperPrototypeNext, 0, kAdapt);
    SimpleInstallFunction(isolate(), iterator_helper_prototype, "return",
                          Builtin::kIteratorHelperPrototypeReturn, 0, kAdapt);
    SimpleInstallFunction(isolate(), iterator_prototype, "reduce",
                          Builtin::kIteratorPrototypeReduce, 1, kDontAdapt);
    SimpleInstallFunction(isolate(), iterator_prototype, "toArray",
                          Builtin::kIteratorPrototypeToArray, 0, kAdapt);
    SimpleInstallFunction(isolate(), iterator_prototype, "forEach",
                          Builtin::kIteratorPrototypeForEach, 1, kAdapt);
    SimpleInstallFunction(isolate(), iterator_prototype, "some",
                          Builtin::kIteratorPrototypeSome, 1, kAdapt);
    SimpleInstallFunction(isolate(), iterator_prototype, "every",
                          Builtin::kIteratorPrototypeEvery, 1, kAdapt);
    SimpleInstallFunction(isolate(), iterator_prototype, "find",
                          Builtin::kIteratorPrototypeFind, 1, kAdapt);
    SimpleInstallGetterSetter(isolate(), iterator_prototype,
                              factory->to_string_tag_symbol(),
                              Builtin::kIteratorPrototypeGetToStringTag,
                              Builtin::kIteratorPrototypeSetToStringTag);
    SimpleInstallGetterSetter(isolate(), iterator_prototype,
                              factory->constructor_string(),
                              Builtin::kIteratorPrototypeGetConstructor,
                              Builtin::kIteratorPrototypeSetConstructor);
    // --- Helper maps
#define INSTALL_ITERATOR_HELPER(lowercase_name, Capitalized_name, \
                                ALL_CAPS_NAME, argc) \
  { \
    DirectHandle<Map> map = factory->NewContextfulMapForCurrentContext(\
        JS_ITERATOR_##ALL_CAPS_NAME##_HELPER_TYPE, \
        JSIterator##Capitalized_name##Helper::kHeaderSize, \
        TERMINAL_FAST_ELEMENTS_KIND, 0); \
    Map::SetPrototype(isolate(), map, iterator_helper_prototype); \
    map->SetConstructor(*iterator_function); \
    native_context()->set_iterator_##lowercase_name##_helper_map(*map); \
    SimpleInstallFunction(isolate(), iterator_prototype, #lowercase_name, \
                          Builtin::kIteratorPrototype##Capitalized_name, argc, \
                          kAdapt); \
  }
#define ITERATOR_HELPERS(V) \
  V(map, Map, MAP, 1) \
  V(filter, Filter, FILTER, 1) \
  V(take, Take, TAKE, 1) \
  V(drop, Drop, DROP, 1) \
  V(flatMap, FlatMap, FLAT_MAP, 1)
    ITERATOR_HELPERS(INSTALL_ITERATOR_HELPER)
#undef INSTALL_ITERATOR_HELPER
#undef ITERATOR_HELPERS
  }
  { // -- I t e r a t o r R e s u l t
    std::array<DirectHandle<Name>, 2> fields{factory->value_string(),
                                             factory->done_string()};
    DirectHandle<Map> map = CreateLiteralObjectMapFromCache(isolate(), fields);
    native_context()->set_iterator_result_map(*map);
  }
  { // -- W e a k M a p
    DirectHandle<JSFunction> cons =
        InstallFunction(isolate_, global, "WeakMap", JS_WEAK_MAP_TYPE,
                        JSWeakMap::kHeaderSize, 0, factory->the_hole_value(),
                        Builtin::kWeakMapConstructor, 0, kDontAdapt);
    InstallWithIntrinsicDefaultProto(isolate_, cons,
                                     Context::JS_WEAK_MAP_FUN_INDEX);
    // Setup %WeakMapPrototype%.
    DirectHandle<JSObject> prototype(Cast<JSObject>(cons->instance_prototype()),
                                     isolate());
    DirectHandle<JSFunction> weakmap_delete =
        SimpleInstallFunction(isolate_, prototype, "delete",
                              Builtin::kWeakMapPrototypeDelete, 1, kAdapt);
    native_context()->set_weakmap_delete(*weakmap_delete);
    DirectHandle<JSFunction> weakmap_get = SimpleInstallFunction(
        isolate_, prototype, "get", Builtin::kWeakMapGet, 1, kAdapt);
    native_context()->set_weakmap_get(*weakmap_get);
    DirectHandle<JSFunction> weakmap_set = SimpleInstallFunction(
        isolate_, prototype, "set", Builtin::kWeakMapPrototypeSet, 2, kAdapt);
    // Check that index of "set" function in JSWeakCollection is correct.
    DCHECK_EQ(JSWeakCollection::kAddFunctionDescriptorIndex,
              prototype->map()->LastAdded().as_int());
    native_context()->set_weakmap_set(*weakmap_set);
    SimpleInstallFunction(isolate_, prototype, "has",
                          Builtin::kWeakMapPrototypeHas, 1, kAdapt);
    InstallToStringTag(isolate_, prototype, "WeakMap");
    native_context()->set_initial_weakmap_prototype_map(prototype->map());
  }
  { // -- W e a k S e t
    DirectHandle<JSFunction> cons =
        InstallFunction(isolate_, global, "WeakSet", JS_WEAK_SET_TYPE,
                        JSWeakSet::kHeaderSize, 0, factory->the_hole_value(),
                        Builtin::kWeakSetConstructor, 0, kDontAdapt);
    InstallWithIntrinsicDefaultProto(isolate_, cons,
                                     Context::JS_WEAK_SET_FUN_INDEX);
    // Setup %WeakSetPrototype%.
    DirectHandle<JSObject> prototype(Cast<JSObject>(cons->instance_prototype()),
                                     isolate());
    SimpleInstallFunction(isolate_, prototype, "delete",
                          Builtin::kWeakSetPrototypeDelete, 1, kAdapt);
    SimpleInstallFunction(isolate_, prototype, "has",
                          Builtin::kWeakSetPrototypeHas, 1, kAdapt);
    DirectHandle<JSFunction> weakset_add = SimpleInstallFunction(
        isolate_, prototype, "add", Builtin::kWeakSetPrototypeAdd, 1, kAdapt);
    // Check that index of "add" function in JSWeakCollection is correct.
    DCHECK_EQ(JSWeakCollection::kAddFunctionDescriptorIndex,
              prototype->map()->LastAdded().as_int());
    native_context()->set_weakset_add(*weakset_add);
    InstallToStringTag(isolate_, prototype,
                       factory->InternalizeUtf8String("WeakSet"));
    native_context()->set_initial_weakset_prototype_map(prototype->map());
  }
  { // -- P r o x y
    CreateJSProxyMaps();
    // Proxy function map has prototype slot for storing initial map but does
    // not have a prototype property.
    DirectHandle<Map> proxy_function_map = Map::Copy(
        isolate_, isolate_->strict_function_without_prototype_map(), "Proxy");
    proxy_function_map->set_is_constructor(true);
    DirectHandle<String> name = factory->Proxy_string();
    DirectHandle<JSFunction> proxy_function =
        CreateFunctionForBuiltin(isolate(), name, proxy_function_map,
                                 Builtin::kProxyConstructor, 2, kAdapt);
    isolate_->proxy_map()->SetConstructor(*proxy_function);
    native_context()->set_proxy_function(*proxy_function);
    JSObject::AddProperty(isolate_, global, name, proxy_function, DONT_ENUM);
    DCHECK(!proxy_function->has_prototype_property());
    SimpleInstallFunction(isolate_, proxy_function, "revocable",
                          Builtin::kProxyRevocable, 2, kAdapt);
  }
  { // -- R e f l e c t
    DirectHandle<String> reflect_string =
        factory->InternalizeUtf8String("Reflect");
    DirectHandle<JSObject> reflect =
        factory->NewJSObject(isolate_->object_function(), AllocationType::kOld);
    JSObject::AddProperty(isolate_, global, reflect_string, reflect, DONT_ENUM);
    InstallToStringTag(isolate_, reflect, reflect_string);
    SimpleInstallFunction(isolate_, reflect, "defineProperty",
                          Builtin::kReflectDefineProperty, 3, kAdapt);
    SimpleInstallFunction(isolate_, reflect, "deleteProperty",
                          Builtin::kReflectDeleteProperty, 2, kAdapt);
    DirectHandle<JSFunction> apply = SimpleInstallFunction(
        isolate_, reflect, "apply", Builtin::kReflectApply, 3, kDontAdapt);
    native_context()->set_reflect_apply(*apply);
    DirectHandle<JSFunction> construct =
        SimpleInstallFunction(isolate_, reflect, "construct",
                              Builtin::kReflectConstruct, 2, kDontAdapt);
    native_context()->set_reflect_construct(*construct);
    SimpleInstallFunction(isolate_, reflect, "get", Builtin::kReflectGet, 2,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, reflect, "getOwnPropertyDescriptor",
                          Builtin::kReflectGetOwnPropertyDescriptor, 2, kAdapt);
    SimpleInstallFunction(isolate_, reflect, "getPrototypeOf",
                          Builtin::kReflectGetPrototypeOf, 1, kAdapt);
    SimpleInstallFunction(isolate_, reflect, "has", Builtin::kReflectHas, 2,
                          kAdapt);
    SimpleInstallFunction(isolate_, reflect, "isExtensible",
                          Builtin::kReflectIsExtensible, 1, kAdapt);
    SimpleInstallFunction(isolate_, reflect, "ownKeys",
                          Builtin::kReflectOwnKeys, 1, kAdapt);
    SimpleInstallFunction(isolate_, reflect, "preventExtensions",
                          Builtin::kReflectPreventExtensions, 1, kAdapt);
    SimpleInstallFunction(isolate_, reflect, "set", Builtin::kReflectSet, 3,
                          kDontAdapt);
    SimpleInstallFunction(isolate_, reflect, "setPrototypeOf",
                          Builtin::kReflectSetPrototypeOf, 2, kAdapt);
  }
  { // --- B o u n d F u n c t i o n
    DirectHandle<Map> map = factory->NewContextfulMapForCurrentContext(
        JS_BOUND_FUNCTION_TYPE, JSBoundFunction::kHeaderSize,
        TERMINAL_FAST_ELEMENTS_KIND, 0);
    map->SetConstructor(native_context()->object_function());
    map->set_is_callable(true);
    Map::SetPrototype(isolate(), map, empty_function);
    PropertyAttributes roc_attribs =
        static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY);
    Map::EnsureDescriptorSlack(isolate_, map, 2);
    { // length
      static_assert(
          JSFunctionOrBoundFunctionOrWrappedFunction::kLengthDescriptorIndex ==
          0);
      Descriptor d = Descriptor::AccessorConstant(
          factory->length_string(), factory->bound_function_length_accessor(),
          roc_attribs);
      map->AppendDescriptor(isolate(), &d);
    }
    { // name
      static_assert(
          JSFunctionOrBoundFunctionOrWrappedFunction::kNameDescriptorIndex ==
          1);
      Descriptor d = Descriptor::AccessorConstant(
          factory->name_string(), factory->bound_function_name_accessor(),
          roc_attribs);
      map->AppendDescriptor(isolate(), &d);
    }
    native_context()->set_bound_function_without_constructor_map(*map);
    map = Map::Copy(isolate_, map, "IsConstructor");
    map->set_is_constructor(true);
    native_context()->set_bound_function_with_constructor_map(*map);
  }
  { // -- F i n a l i z a t i o n R e g i s t r y
    DirectHandle<JSFunction> finalization_registry_fun = InstallFunction(
        isolate_, global, factory->FinalizationRegistry_string(),
        JS_FINALIZATION_REGISTRY_TYPE, JSFinalizationRegistry::kHeaderSize, 0,
        factory->the_hole_value(), Builtin::kFinalizationRegistryConstructor, 1,
        kDontAdapt);
    InstallWithIntrinsicDefaultProto(
        isolate_, finalization_registry_fun,
        Context::JS_FINALIZATION_REGISTRY_FUNCTION_INDEX);
    DirectHandle<JSObject> finalization_registry_prototype(
        Cast<JSObject>(finalization_registry_fun->instance_prototype()),
        isolate());
    InstallToStringTag(isolate_, finalization_registry_prototype,
                       factory->FinalizationRegistry_string());
    SimpleInstallFunction(isolate_, finalization_registry_prototype, "register",
                          Builtin::kFinalizationRegistryRegister, 2,
                          kDontAdapt);
    SimpleInstallFunction(
        isolate_, finalization_registry_prototype, "unregister",
        Builtin::kFinalizationRegistryUnregister, 1, kDontAdapt);
  }
  { // -- W e a k R e f
    DirectHandle<JSFunction> weak_ref_fun =
        InstallFunction(isolate_, global, "WeakRef", JS_WEAK_REF_TYPE,
                        JSWeakRef::kHeaderSize, 0, factory->the_hole_value(),
                        Builtin::kWeakRefConstructor, 1, kDontAdapt);
    InstallWithIntrinsicDefaultProto(isolate_, weak_ref_fun,
                                     Context::JS_WEAK_REF_FUNCTION_INDEX);
    DirectHandle<JSObject> weak_ref_prototype(
        Cast<JSObject>(weak_ref_fun->instance_prototype()), isolate());
    InstallToStringTag(isolate_, weak_ref_prototype, factory->WeakRef_string());
    SimpleInstallFunction(isolate_, weak_ref_prototype, "deref",
                          Builtin::kWeakRefDeref, 0, kAdapt);
  }
  { // --- sloppy arguments map
    DirectHandle<String> arguments_string = factory->Arguments_string();
    DirectHandle<JSFunction> function = CreateFunctionForBuiltinWithPrototype(
        isolate(), arguments_string, Builtin::kIllegal,
        isolate()->initial_object_prototype(), JS_ARGUMENTS_OBJECT_TYPE,
        JSSloppyArgumentsObject::kSize, 2, MUTABLE, 0, kDontAdapt);
    DirectHandle<Map> map(function->initial_map(), isolate());
    // Create the descriptor array for the arguments object.
    Map::EnsureDescriptorSlack(isolate_, map, 2);
    { // length
      Descriptor d =
          Descriptor::DataField(isolate(), factory->length_string(),
                                JSSloppyArgumentsObject::kLengthIndex,
                                DONT_ENUM, Representation::Tagged());
      map->AppendDescriptor(isolate(), &d);
    }
    { // callee
      Descriptor d =
          Descriptor::DataField(isolate(), factory->callee_string(),
                                JSSloppyArgumentsObject::kCalleeIndex,
                                DONT_ENUM, Representation::Tagged());
      map->AppendDescriptor(isolate(), &d);
    }
    // @@iterator method is added later.
    native_context()->set_sloppy_arguments_map(*map);
    DCHECK(!map->is_dictionary_map());
    DCHECK(IsObjectElementsKind(map->elements_kind()));
  }
  { // --- fast and slow aliased arguments map
    DirectHandle<Map> map = isolate_->sloppy_arguments_map();
    map = Map::Copy(isolate_, map, "FastAliasedArguments");
    map->set_elements_kind(FAST_SLOPPY_ARGUMENTS_ELEMENTS);
    DCHECK_EQ(2, map->GetInObjectProperties());
    native_context()->set_fast_aliased_arguments_map(*map);
    map = Map::Copy(isolate_, map, "SlowAliasedArguments");
    map->set_elements_kind(SLOW_SLOPPY_ARGUMENTS_ELEMENTS);
    DCHECK_EQ(2, map->GetInObjectProperties());
    native_context()->set_slow_aliased_arguments_map(*map);
  }
  { // --- strict mode arguments map
    const PropertyAttributes attributes =
        static_cast<PropertyAttributes>(DONT_ENUM | DONT_DELETE | READ_ONLY);
    // Create the ThrowTypeError function.
    DirectHandle<AccessorPair> callee = factory->NewAccessorPair();
    DirectHandle<JSFunction> poison = GetThrowTypeErrorIntrinsic();
    // Install the ThrowTypeError function.
    callee->set_getter(*poison);
    callee->set_setter(*poison);
    // Create the map. Allocate one in-object field for length.
    DirectHandle<Map> map = factory->NewContextfulMapForCurrentContext(
        JS_ARGUMENTS_OBJECT_TYPE, JSStrictArgumentsObject::kSize,
        PACKED_ELEMENTS, 1);
    // Create the descriptor array for the arguments object.
    Map::EnsureDescriptorSlack(isolate_, map, 2);
    { // length
      Descriptor d =
          Descriptor::DataField(isolate(), factory->length_string(),
                                JSStrictArgumentsObject::kLengthIndex,
                                DONT_ENUM, Representation::Tagged());
      map->AppendDescriptor(isolate(), &d);
    }
    { // callee
      Descriptor d = Descriptor::AccessorConstant(factory->callee_string(),
                                                  callee, attributes);
      map->AppendDescriptor(isolate(), &d);
    }
    // @@iterator method is added later.
    DCHECK_EQ(native_context()->object_function()->prototype(),
              *isolate_->initial_object_prototype());
    Map::SetPrototype(isolate(), map, isolate_->initial_object_prototype());
    // Copy constructor from the sloppy arguments boilerplate.
    map->SetConstructor(
        native_context()->sloppy_arguments_map()->GetConstructor());
    native_context()->set_strict_arguments_map(*map);
    DCHECK(!map->is_dictionary_map());
    DCHECK(IsObjectElementsKind(map->elements_kind()));
  }
  { // --- context extension
    // Create a function for the context extension objects.
    DirectHandle<JSFunction> context_extension_fun = CreateFunction(
        isolate_, factory->empty_string(), JS_CONTEXT_EXTENSION_OBJECT_TYPE,
        JSObject::kHeaderSize, 0, factory->the_hole_value(), Builtin::kIllegal,
        0, kDontAdapt);
    native_context()->set_context_extension_function(*context_extension_fun);
  }
  {
    // Set up the call-as-function delegate.
    DirectHandle<JSFunction> delegate = SimpleCreateFunction(
        isolate_, factory->empty_string(),
        Builtin::kHandleApiCallAsFunctionDelegate, 0, kDontAdapt);
    native_context()->set_call_as_function_delegate(*delegate);
  }
  {
    // Set up the call-as-constructor delegate.
    DirectHandle<JSFunction> delegate = SimpleCreateFunction(
        isolate_, factory->empty_string(),
        Builtin::kHandleApiCallAsConstructorDelegate, 0, kDontAdapt);
    native_context()->set_call_as_constructor_delegate(*delegate);
  }
}
References v8::internal::Descriptor::AccessorConstant(), v8::internal::JSObject::AddProperty(), ARRAY_BUFFER, CHECK_NE, v8::internal::Map::Copy(), CreateArrayBuffer(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunction(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltin(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltinWithPrototype(), CreateJSProxyMaps(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateLiteralObjectMapFromCache(), v8::internal::Descriptor::DataField(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::DONT_DELETE, v8::internal::DONT_ENUM, v8::internal::Map::EnsureDescriptorSlack(), v8::base::ieee754::exp(), v8::internal::Isolate::factory(), factory(), v8::internal::FAST_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::FAST_STRING_WRAPPER_ELEMENTS, v8::internal::JSObject::ForceSetPrototype(), v8::internal::GetInitialFastElementsKind(), v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), GetThrowTypeErrorIntrinsic(), global_proxy(), v8::internal::index, v8::internal::compiler::initial_map, v8::internal::anonymous_namespace{bootstrapper.cc}::InitializeJSArrayMaps(), INSTALL_CAPTURE_GETTER, INSTALL_ITERATOR_HELPER, INSTALL_TYPED_ARRAY, v8::internal::anonymous_namespace{bootstrapper.cc}::InstallConstant(), v8::internal::InstallError(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunction(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunctionAtSymbol(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunctionWithBuiltinId(), InstallGlobalThisBinding(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallSpeciesGetter(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallToStringTag(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallTrueValuedProperty(), v8::internal::InstallWithIntrinsicDefaultProto(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::IsObjectElementsKind(), isolate(), isolate_, ITERATOR_HELPERS, v8::internal::kAdapt, v8::internal::JSCollection::kAddFunctionDescriptorIndex, v8::internal::JSWeakCollection::kAddFunctionDescriptorIndex, v8::internal::JSSloppyArgumentsObject::kCalleeIndex, v8::internal::kDontAdapt, v8::internal::JSRegExp::kExecFunctionDescriptorIndex, v8::internal::JSRegExp::kInObjectFieldCount, v8::internal::JSModuleNamespace::kInObjectFieldCount, v8::internal::JSRegExp::kLastIndexFieldIndex, v8::internal::JSArray::kLengthDescriptorIndex, v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::kLengthDescriptorIndex, v8::internal::JSSloppyArgumentsObject::kLengthIndex, v8::internal::JSStrictArgumentsObject::kLengthIndex, v8::internal::kMaxSafeInteger, v8::internal::RegExpMatchInfo::kMinCapacity, v8::internal::kMinSafeInteger, v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::kNameDescriptorIndex, v8::internal::kOld, v8::internal::JSRawJson::kRawJsonInitialIndex, v8::kReleaseStore, v8::internal::JSModuleNamespace::kSize, v8::internal::JSPromise::kSizeWithEmbedderFields, v8::internal::JSFunction::kSizeWithPrototype, v8::internal::JSRegExp::kSymbolMatchAllFunctionDescriptorIndex, v8::internal::JSRegExp::kSymbolMatchFunctionDescriptorIndex, v8::internal::JSRegExp::kSymbolReplaceFunctionDescriptorIndex, v8::internal::JSRegExp::kSymbolSearchFunctionDescriptorIndex, v8::internal::JSRegExp::kSymbolSplitFunctionDescriptorIndex, v8::internal::kTaggedSize, v8::internal::JSModuleNamespace::kToStringTagFieldIndex, v8::internal::kVariableSizeSentinel, v8::internal::length, v8::base::ieee754::log(), v8::base::ieee754::log10(), v8::base::ieee754::log2(), v8::internal::JSObject::MigrateSlowToFast(), v8::internal::MUTABLE, v8::internal::name, native_context(), v8::internal::RegExpMatchInfo::New(), v8::internal::FactoryBase< Impl >::NewAccessorPair(), v8::internal::Factory::NewContextfulMapForCurrentContext(), v8::internal::Factory::NewEmbedderDataArray(), v8::internal::Factory::NewJSArray(), v8::internal::Factory::NewJSObject(), v8::internal::Factory::NewJSObjectWithNullProto(), v8::internal::Factory::NewMapWithMetaMap(), v8::internal::FactoryBase< Impl >::NewNumber(), v8::internal::Factory::NewScriptContextTable(), v8::internal::NONE, v8::internal::PACKED_ELEMENTS, v8::internal::prototype, v8::internal::READ_ONLY, v8::internal::anonymous_namespace{bootstrapper.cc}::SetConstructorInstanceType(), v8::internal::JSFunction::SetPrototype(), v8::internal::Map::SetPrototype(), v8::internal::Map::SetShouldBeFastPrototypeMap(), SHARED_ARRAY_BUFFER, v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleCreateFunction(), v8::internal::SimpleInstallFunction(), v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleInstallGetter(), v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleInstallGetterSetter(), v8::internal::SLOW_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::Representation::Tagged(), v8::internal::TERMINAL_FAST_ELEMENTS_KIND, v8::internal::Name::ToFunctionName(), TYPED_ARRAYS_BASE, v8::internal::v8_flags, V8_INFINITY, and v8::internal::Smi::zero().
Referenced by Genesis().
InitializeGlobal_regexp_linear_flag()
void v8::internal::Genesis::InitializeGlobal_regexp_linear_flag () [private]
Definition at line 5924 of file bootstrapper.cc.
                                                  {
  if (!v8_flags.enable_experimental_regexp_engine) return;
  DirectHandle<JSFunction> regexp_fun(native_context()->regexp_function(),
                                      isolate());
  DirectHandle<JSObject> regexp_prototype(
      Cast<JSObject>(regexp_fun->instance_prototype()), isolate());
  SimpleInstallGetter(isolate(), regexp_prototype,
                      isolate()->factory()->linear_string(),
                      Builtin::kRegExpPrototypeLinearGetter, kAdapt);
  // Store regexp prototype map again after change.
  native_context()->set_regexp_prototype_map(regexp_prototype->map());
}
References factory(), isolate(), v8::internal::kAdapt, native_context(), v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleInstallGetter(), and v8::internal::v8_flags.
Referenced by InitializeExperimentalGlobal().
InitializeGlobal_sharedarraybuffer()
void v8::internal::Genesis::InitializeGlobal_sharedarraybuffer () [private]
Definition at line 5714 of file bootstrapper.cc.
                                                 {
  if (v8_flags.enable_sharedarraybuffer_per_context) {
    return;
  }
  DirectHandle<JSGlobalObject> global(native_context()->global_object(),
                                      isolate());
  JSObject::AddProperty(isolate_, global, "SharedArrayBuffer",
                        isolate()->shared_array_buffer_fun(), DONT_ENUM);
}
References v8::internal::JSObject::AddProperty(), v8::internal::DONT_ENUM, isolate(), isolate_, native_context(), and v8::internal::v8_flags.
Referenced by InitializeExperimentalGlobal().
InitializeIteratorFunctions()
void v8::internal::Genesis::InitializeIteratorFunctions () [private]
Definition at line 5194 of file bootstrapper.cc.
                                          {
  Isolate* isolate = isolate_;
  Factory* factory = isolate->factory();
  HandleScope scope(isolate);
  DirectHandle<NativeContext> native_context = isolate->native_context();
  DirectHandle<JSObject> iterator_prototype(
      native_context->initial_iterator_prototype(), isolate);
  { // -- G e n e r a t o r
    PrototypeIterator iter(isolate, native_context->generator_function_map());
    DirectHandle<JSObject> generator_function_prototype(
        iter.GetCurrent<JSObject>(), isolate);
    DirectHandle<JSFunction> generator_function_function = CreateFunction(
        isolate, "GeneratorFunction", JS_FUNCTION_TYPE,
        JSFunction::kSizeWithPrototype, 0, generator_function_prototype,
        Builtin::kGeneratorFunctionConstructor, 1, kDontAdapt);
    generator_function_function->set_prototype_or_initial_map(
        native_context->generator_function_map(), kReleaseStore);
    InstallWithIntrinsicDefaultProto(
        isolate, generator_function_function,
        Context::GENERATOR_FUNCTION_FUNCTION_INDEX);
    JSObject::ForceSetPrototype(isolate, generator_function_function,
                                isolate->function_function());
    JSObject::AddProperty(
        isolate, generator_function_prototype, factory->constructor_string(),
        generator_function_function,
        static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY));
    native_context->generator_function_map()->SetConstructor(
        *generator_function_function);
    native_context->generator_function_with_name_map()->SetConstructor(
        *generator_function_function);
  }
  { // -- A s y n c G e n e r a t o r
    PrototypeIterator iter(isolate,
                           native_context->async_generator_function_map());
    DirectHandle<JSObject> async_generator_function_prototype(
        iter.GetCurrent<JSObject>(), isolate);
    DirectHandle<JSFunction> async_generator_function_function = CreateFunction(
        isolate, "AsyncGeneratorFunction", JS_FUNCTION_TYPE,
        JSFunction::kSizeWithPrototype, 0, async_generator_function_prototype,
        Builtin::kAsyncGeneratorFunctionConstructor, 1, kDontAdapt);
    async_generator_function_function->set_prototype_or_initial_map(
        native_context->async_generator_function_map(), kReleaseStore);
    InstallWithIntrinsicDefaultProto(
        isolate, async_generator_function_function,
        Context::ASYNC_GENERATOR_FUNCTION_FUNCTION_INDEX);
    JSObject::ForceSetPrototype(isolate, async_generator_function_function,
                                isolate->function_function());
    JSObject::AddProperty(
        isolate, async_generator_function_prototype,
        factory->constructor_string(), async_generator_function_function,
        static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY));
    native_context->async_generator_function_map()->SetConstructor(
        *async_generator_function_function);
    native_context->async_generator_function_with_name_map()->SetConstructor(
        *async_generator_function_function);
  }
  { // -- S e t I t e r a t o r
    // Setup %SetIteratorPrototype%.
    DirectHandle<JSObject> prototype =
        factory->NewJSObject(isolate->object_function(), AllocationType::kOld);
    JSObject::ForceSetPrototype(isolate, prototype, iterator_prototype);
    InstallToStringTag(isolate, prototype, factory->SetIterator_string());
    // Install the next function on the {prototype}.
    InstallFunctionWithBuiltinId(isolate, prototype, "next",
                                 Builtin::kSetIteratorPrototypeNext, 0, kAdapt);
    native_context->set_initial_set_iterator_prototype(*prototype);
    CHECK_NE(prototype->map().ptr(),
             isolate_->initial_object_prototype()->map().ptr());
    prototype->map()->set_instance_type(JS_SET_ITERATOR_PROTOTYPE_TYPE);
    // Setup SetIterator constructor.
    DirectHandle<JSFunction> set_iterator_function =
        CreateFunction(isolate, "SetIterator", JS_SET_VALUE_ITERATOR_TYPE,
                       JSSetIterator::kHeaderSize, 0, prototype,
                       Builtin::kIllegal, 0, kDontAdapt);
    set_iterator_function->shared()->set_native(false);
    DirectHandle<Map> set_value_iterator_map(
        set_iterator_function->initial_map(), isolate);
    native_context->set_set_value_iterator_map(*set_value_iterator_map);
    DirectHandle<Map> set_key_value_iterator_map = Map::Copy(
        isolate, set_value_iterator_map, "JS_SET_KEY_VALUE_ITERATOR_TYPE");
    set_key_value_iterator_map->set_instance_type(
        JS_SET_KEY_VALUE_ITERATOR_TYPE);
    native_context->set_set_key_value_iterator_map(*set_key_value_iterator_map);
  }
  { // -- M a p I t e r a t o r
    // Setup %MapIteratorPrototype%.
    DirectHandle<JSObject> prototype =
        factory->NewJSObject(isolate->object_function(), AllocationType::kOld);
    JSObject::ForceSetPrototype(isolate, prototype, iterator_prototype);
    InstallToStringTag(isolate, prototype, factory->MapIterator_string());
    // Install the next function on the {prototype}.
    InstallFunctionWithBuiltinId(isolate, prototype, "next",
                                 Builtin::kMapIteratorPrototypeNext, 0, kAdapt);
    native_context->set_initial_map_iterator_prototype(*prototype);
    CHECK_NE(prototype->map().ptr(),
             isolate_->initial_object_prototype()->map().ptr());
    prototype->map()->set_instance_type(JS_MAP_ITERATOR_PROTOTYPE_TYPE);
    // Setup MapIterator constructor.
    DirectHandle<JSFunction> map_iterator_function =
        CreateFunction(isolate, "MapIterator", JS_MAP_KEY_ITERATOR_TYPE,
                       JSMapIterator::kHeaderSize, 0, prototype,
                       Builtin::kIllegal, 0, kDontAdapt);
    map_iterator_function->shared()->set_native(false);
    DirectHandle<Map> map_key_iterator_map(map_iterator_function->initial_map(),
                                           isolate);
    native_context->set_map_key_iterator_map(*map_key_iterator_map);
    DirectHandle<Map> map_key_value_iterator_map = Map::Copy(
        isolate, map_key_iterator_map, "JS_MAP_KEY_VALUE_ITERATOR_TYPE");
    map_key_value_iterator_map->set_instance_type(
        JS_MAP_KEY_VALUE_ITERATOR_TYPE);
    native_context->set_map_key_value_iterator_map(*map_key_value_iterator_map);
    DirectHandle<Map> map_value_iterator_map =
        Map::Copy(isolate, map_key_iterator_map, "JS_MAP_VALUE_ITERATOR_TYPE");
    map_value_iterator_map->set_instance_type(JS_MAP_VALUE_ITERATOR_TYPE);
    native_context->set_map_value_iterator_map(*map_value_iterator_map);
  }
  { // -- A s y n c F u n c t i o n
    // Builtin functions for AsyncFunction.
    PrototypeIterator iter(isolate, native_context->async_function_map());
    DirectHandle<JSObject> async_function_prototype(iter.GetCurrent<JSObject>(),
                                                    isolate);
    DirectHandle<JSFunction> async_function_constructor = CreateFunction(
        isolate, "AsyncFunction", JS_FUNCTION_TYPE,
        JSFunction::kSizeWithPrototype, 0, async_function_prototype,
        Builtin::kAsyncFunctionConstructor, 1, kDontAdapt);
    async_function_constructor->set_prototype_or_initial_map(
        native_context->async_function_map(), kReleaseStore);
    InstallWithIntrinsicDefaultProto(isolate, async_function_constructor,
                                     Context::ASYNC_FUNCTION_FUNCTION_INDEX);
    native_context->set_async_function_constructor(*async_function_constructor);
    JSObject::ForceSetPrototype(isolate, async_function_constructor,
                                isolate->function_function());
    JSObject::AddProperty(
        isolate, async_function_prototype, factory->constructor_string(),
        async_function_constructor,
        static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY));
    // Async functions don't have a prototype, but they use generator objects
    // under the hood to model the suspend/resume (in await). Instead of using
    // the "prototype" / initial_map machinery (like for (async) generators),
    // there's one global (per native context) map here that is used for the
    // async function generator objects. These objects never escape to user
    // JavaScript anyways.
    DirectHandle<Map> async_function_object_map =
        factory->NewContextfulMapForCurrentContext(
            JS_ASYNC_FUNCTION_OBJECT_TYPE, JSAsyncFunctionObject::kHeaderSize);
    native_context->set_async_function_object_map(*async_function_object_map);
    isolate_->async_function_map()->SetConstructor(*async_function_constructor);
    isolate_->async_function_with_name_map()->SetConstructor(
        *async_function_constructor);
  }
}
References v8::internal::JSObject::AddProperty(), CHECK_NE, v8::internal::Map::Copy(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunction(), v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), factory(), v8::internal::JSObject::ForceSetPrototype(), v8::internal::PrototypeIterator::GetCurrent(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunctionWithBuiltinId(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallToStringTag(), v8::internal::InstallWithIntrinsicDefaultProto(), isolate(), isolate_, v8::internal::kAdapt, v8::internal::kDontAdapt, v8::internal::kOld, v8::kReleaseStore, v8::internal::JSFunction::kSizeWithPrototype, v8::internal::Isolate::native_context(), native_context(), v8::internal::Factory::NewContextfulMapForCurrentContext(), v8::internal::Factory::NewJSObject(), v8::internal::prototype, and v8::internal::READ_ONLY.
Referenced by Genesis().
InitializeMapCaches()
void v8::internal::Genesis::InitializeMapCaches () [private]
Definition at line 6489 of file bootstrapper.cc.
                                  {
  {
    DirectHandle<NormalizedMapCache> cache = NormalizedMapCache::New(isolate());
    native_context()->set_normalized_map_cache(*cache);
  }
  {
    DirectHandle<WeakFixedArray> cache = factory()->NewWeakFixedArray(
        JSObject::kMapCacheSize, AllocationType::kOld);
    DisallowGarbageCollection no_gc;
    for (int i = 0; i < JSObject::kMapCacheSize; i++) {
      cache->set(i, ClearedValue(isolate()));
    }
    native_context()->set_map_cache(*cache);
    Tagged<Map> initial = native_context()->object_function()->initial_map();
    cache->set(0, MakeWeak(initial));
    cache->set(initial->GetInObjectProperties(), MakeWeak(initial));
  }
}
References v8::internal::ClearedValue(), factory(), isolate(), v8::internal::JSObject::kMapCacheSize, v8::internal::kOld, v8::internal::MakeWeak(), native_context(), v8::internal::NormalizedMapCache::New(), v8::internal::FactoryBase< Impl >::NewWeakFixedArray(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by Genesis().
InstallABunchOfRandomThings()
bool v8::internal::Genesis::InstallABunchOfRandomThings () [private]
Definition at line 6018 of file bootstrapper.cc.
                                          {
  HandleScope scope(isolate());
  auto fast_template_instantiations_cache =
      isolate()->factory()->NewFixedArrayWithHoles(
          TemplateInfo::kFastTemplateInstantiationsCacheSize);
  native_context()->set_fast_template_instantiations_cache(
      *fast_template_instantiations_cache);
  auto slow_template_instantiations_cache =
      EphemeronHashTable::New(isolate(), ApiNatives::kInitialFunctionCacheSize);
  native_context()->set_slow_template_instantiations_cache(
      *slow_template_instantiations_cache);
  auto wasm_debug_maps = isolate()->factory()->empty_fixed_array();
  native_context()->set_wasm_debug_maps(*wasm_debug_maps);
  // Store the map for the %ObjectPrototype% after the natives has been compiled
  // and the Object function has been set up.
  {
    DirectHandle<JSFunction> object_function(
        native_context()->object_function(), isolate());
    DCHECK(Cast<JSObject>(object_function->initial_map()->prototype())
               ->HasFastProperties());
    native_context()->set_object_function_prototype(
        Cast<JSObject>(object_function->initial_map()->prototype()));
    native_context()->set_object_function_prototype_map(
        Cast<HeapObject>(object_function->initial_map()->prototype())->map());
  }
  // Store the map for the %StringPrototype% after the natives has been compiled
  // and the String function has been set up.
  DirectHandle<JSFunction> string_function(native_context()->string_function(),
                                           isolate());
  Tagged<JSObject> string_function_prototype =
      Cast<JSObject>(string_function->initial_map()->prototype());
  DCHECK(string_function_prototype->HasFastProperties());
  native_context()->set_string_function_prototype_map(
      string_function_prototype->map());
  DirectHandle<JSGlobalObject> global_object(native_context()->global_object(),
                                             isolate());
  // Install Global.decodeURI.
  InstallFunctionWithBuiltinId(isolate(), global_object, "decodeURI",
                               Builtin::kGlobalDecodeURI, 1, kDontAdapt);
  // Install Global.decodeURIComponent.
  InstallFunctionWithBuiltinId(isolate(), global_object, "decodeURIComponent",
                               Builtin::kGlobalDecodeURIComponent, 1,
                               kDontAdapt);
  // Install Global.encodeURI.
  InstallFunctionWithBuiltinId(isolate(), global_object, "encodeURI",
                               Builtin::kGlobalEncodeURI, 1, kDontAdapt);
  // Install Global.encodeURIComponent.
  InstallFunctionWithBuiltinId(isolate(), global_object, "encodeURIComponent",
                               Builtin::kGlobalEncodeURIComponent, 1,
                               kDontAdapt);
  // Install Global.escape.
  InstallFunctionWithBuiltinId(isolate(), global_object, "escape",
                               Builtin::kGlobalEscape, 1, kDontAdapt);
  // Install Global.unescape.
  InstallFunctionWithBuiltinId(isolate(), global_object, "unescape",
                               Builtin::kGlobalUnescape, 1, kDontAdapt);
  // Install Global.eval.
  {
    DirectHandle<JSFunction> eval = SimpleInstallFunction(
        isolate(), global_object, "eval", Builtin::kGlobalEval, 1, kDontAdapt);
    native_context()->set_global_eval_fun(*eval);
  }
  // Install Global.isFinite
  InstallFunctionWithBuiltinId(isolate(), global_object, "isFinite",
                               Builtin::kGlobalIsFinite, 1, kAdapt);
  // Install Global.isNaN
  InstallFunctionWithBuiltinId(isolate(), global_object, "isNaN",
                               Builtin::kGlobalIsNaN, 1, kAdapt);
  // Install Array builtin functions.
  {
    DirectHandle<JSFunction> array_constructor(
        native_context()->array_function(), isolate());
    DirectHandle<JSArray> proto(Cast<JSArray>(array_constructor->prototype()),
                                isolate());
    // Verification of important array prototype properties.
    Tagged<Object> length = proto->length();
    CHECK(IsSmi(length));
    CHECK_EQ(Smi::ToInt(length), 0);
    CHECK(proto->HasSmiOrObjectElements());
    // This is necessary to enable fast checks for absence of elements
    // on Array.prototype and below.
    proto->set_elements(ReadOnlyRoots(heap()).empty_fixed_array());
  }
  // Create a map for accessor property descriptors (a variant of JSObject
  // that predefines four properties get, set, configurable and enumerable).
  {
    // AccessorPropertyDescriptor initial map.
    DirectHandle<Map> map = factory()->NewContextfulMapForCurrentContext(
        JS_OBJECT_TYPE, JSAccessorPropertyDescriptor::kSize,
        TERMINAL_FAST_ELEMENTS_KIND, 4);
    // Create the descriptor array for the property descriptor object.
    Map::EnsureDescriptorSlack(isolate(), map, 4);
    { // get
      Descriptor d =
          Descriptor::DataField(isolate(), factory()->get_string(),
                                JSAccessorPropertyDescriptor::kGetIndex, NONE,
                                Representation::Tagged());
      map->AppendDescriptor(isolate(), &d);
    }
    { // set
      Descriptor d =
          Descriptor::DataField(isolate(), factory()->set_string(),
                                JSAccessorPropertyDescriptor::kSetIndex, NONE,
                                Representation::Tagged());
      map->AppendDescriptor(isolate(), &d);
    }
    { // enumerable
      Descriptor d =
          Descriptor::DataField(isolate(), factory()->enumerable_string(),
                                JSAccessorPropertyDescriptor::kEnumerableIndex,
                                NONE, Representation::Tagged());
      map->AppendDescriptor(isolate(), &d);
    }
    { // configurable
      Descriptor d = Descriptor::DataField(
          isolate(), factory()->configurable_string(),
          JSAccessorPropertyDescriptor::kConfigurableIndex, NONE,
          Representation::Tagged());
      map->AppendDescriptor(isolate(), &d);
    }
    Map::SetPrototype(isolate(), map, isolate()->initial_object_prototype());
    map->SetConstructor(native_context()->object_function());
    native_context()->set_accessor_property_descriptor_map(*map);
  }
  // Create a map for data property descriptors (a variant of JSObject
  // that predefines four properties value, writable, configurable and
  // enumerable).
  {
    // DataPropertyDescriptor initial map.
    DirectHandle<Map> map = factory()->NewContextfulMapForCurrentContext(
        JS_OBJECT_TYPE, JSDataPropertyDescriptor::kSize,
        TERMINAL_FAST_ELEMENTS_KIND, 4);
    // Create the descriptor array for the property descriptor object.
    Map::EnsureDescriptorSlack(isolate(), map, 4);
    { // value
      Descriptor d =
          Descriptor::DataField(isolate(), factory()->value_string(),
                                JSDataPropertyDescriptor::kValueIndex, NONE,
                                Representation::Tagged());
      map->AppendDescriptor(isolate(), &d);
    }
    { // writable
      Descriptor d =
          Descriptor::DataField(isolate(), factory()->writable_string(),
                                JSDataPropertyDescriptor::kWritableIndex, NONE,
                                Representation::Tagged());
      map->AppendDescriptor(isolate(), &d);
    }
    { // enumerable
      Descriptor d =
          Descriptor::DataField(isolate(), factory()->enumerable_string(),
                                JSDataPropertyDescriptor::kEnumerableIndex,
                                NONE, Representation::Tagged());
      map->AppendDescriptor(isolate(), &d);
    }
    { // configurable
      Descriptor d =
          Descriptor::DataField(isolate(), factory()->configurable_string(),
                                JSDataPropertyDescriptor::kConfigurableIndex,
                                NONE, Representation::Tagged());
      map->AppendDescriptor(isolate(), &d);
    }
    Map::SetPrototype(isolate(), map, isolate()->initial_object_prototype());
    map->SetConstructor(native_context()->object_function());
    native_context()->set_data_property_descriptor_map(*map);
  }
  {
    // -- TemplateLiteral JSArray Map
    DirectHandle<JSFunction> array_function(native_context()->array_function(),
                                            isolate());
    DirectHandle<Map> template_map(array_function->initial_map(), isolate_);
    template_map = Map::CopyAsElementsKind(isolate_, template_map,
                                           PACKED_ELEMENTS, OMIT_TRANSITION);
    DCHECK_GE(TemplateLiteralObject::kHeaderSize,
              template_map->instance_size());
    template_map->set_instance_size(TemplateLiteralObject::kHeaderSize);
    // Temporarily instantiate a full template_literal_object to get the final
    // map.
    auto template_object =
        Cast<JSArray>(factory()->NewJSObjectFromMap(template_map));
    {
      DisallowGarbageCollection no_gc;
      Tagged<JSArray> raw = *template_object;
      raw->set_elements(ReadOnlyRoots(isolate()).empty_fixed_array());
      raw->set_length(Smi::FromInt(0));
    }
    // Install a "raw" data property for {raw_object} on {template_object}.
    // See ES#sec-gettemplateobject.
    PropertyDescriptor raw_desc;
    // Use arbrirary object {template_object} as ".raw" value.
    raw_desc.set_value(template_object);
    raw_desc.set_configurable(false);
    raw_desc.set_enumerable(false);
    raw_desc.set_writable(false);
    JSArray::DefineOwnProperty(isolate(), template_object,
                               factory()->raw_string(), &raw_desc,
                               Just(kThrowOnError))
        .ToChecked();
    // Install private symbol fields for function_literal_id and slot_id.
    raw_desc.set_value(direct_handle(Smi::zero(), isolate()));
    JSArray::DefineOwnProperty(
        isolate(), template_object,
        factory()->template_literal_function_literal_id_symbol(), &raw_desc,
        Just(kThrowOnError))
        .ToChecked();
    JSArray::DefineOwnProperty(isolate(), template_object,
                               factory()->template_literal_slot_id_symbol(),
                               &raw_desc, Just(kThrowOnError))
        .ToChecked();
    // Freeze the {template_object} as well.
    JSObject::SetIntegrityLevel(isolate(), template_object, FROZEN,
                                kThrowOnError)
        .ToChecked();
    {
      DisallowGarbageCollection no_gc;
      Tagged<DescriptorArray> desc =
          template_object->map()->instance_descriptors();
      {
        // Verify TemplateLiteralObject::kRawOffset
        InternalIndex descriptor_index = desc->Search(
            *factory()->raw_string(), desc->number_of_descriptors());
        FieldIndex index =
            FieldIndex::ForDescriptor(template_object->map(), descriptor_index);
        CHECK(index.is_inobject());
        CHECK_EQ(index.offset(), TemplateLiteralObject::kRawOffset);
      }
      {
        // Verify TemplateLiteralObject::kFunctionLiteralIdOffset
        InternalIndex descriptor_index = desc->Search(
            *factory()->template_literal_function_literal_id_symbol(),
            desc->number_of_descriptors());
        FieldIndex index =
            FieldIndex::ForDescriptor(template_object->map(), descriptor_index);
        CHECK(index.is_inobject());
        CHECK_EQ(index.offset(),
                 TemplateLiteralObject::kFunctionLiteralIdOffset);
      }
      {
        // Verify TemplateLiteralObject::kSlotIdOffset
        InternalIndex descriptor_index =
            desc->Search(*factory()->template_literal_slot_id_symbol(),
                         desc->number_of_descriptors());
        FieldIndex index =
            FieldIndex::ForDescriptor(template_object->map(), descriptor_index);
        CHECK(index.is_inobject());
        CHECK_EQ(index.offset(), TemplateLiteralObject::kSlotIdOffset);
      }
    }
    native_context()->set_js_array_template_literal_object_map(
        template_object->map());
  }
  // Create a constructor for RegExp results (a variant of Array that
  // predefines the properties index, input, and groups).
  {
    // JSRegExpResult initial map.
    // Add additional slack to the initial map in case regexp_match_indices
    // are enabled to account for the additional descriptor.
    DirectHandle<Map> initial_map = CreateInitialMapForArraySubclass(
        JSRegExpResult::kSize, JSRegExpResult::kInObjectPropertyCount);
    // index descriptor.
    {
      Descriptor d = Descriptor::DataField(isolate(), factory()->index_string(),
                                           JSRegExpResult::kIndexIndex, NONE,
                                           Representation::Tagged());
      initial_map->AppendDescriptor(isolate(), &d);
    }
    // input descriptor.
    {
      Descriptor d = Descriptor::DataField(isolate(), factory()->input_string(),
                                           JSRegExpResult::kInputIndex, NONE,
                                           Representation::Tagged());
      initial_map->AppendDescriptor(isolate(), &d);
    }
    // groups descriptor.
    {
      Descriptor d = Descriptor::DataField(
          isolate(), factory()->groups_string(), JSRegExpResult::kGroupsIndex,
          NONE, Representation::Tagged());
      initial_map->AppendDescriptor(isolate(), &d);
    }
    // Private internal only fields. All of the remaining fields have special
    // symbols to prevent their use in Javascript.
    {
      PropertyAttributes attribs = DONT_ENUM;
      // names descriptor.
      {
        Descriptor d = Descriptor::DataField(
            isolate(), factory()->regexp_result_names_symbol(),
            JSRegExpResult::kNamesIndex, attribs, Representation::Tagged());
        initial_map->AppendDescriptor(isolate(), &d);
      }
      // regexp_input_index descriptor.
      {
        Descriptor d = Descriptor::DataField(
            isolate(), factory()->regexp_result_regexp_input_symbol(),
            JSRegExpResult::kRegExpInputIndex, attribs,
            Representation::Tagged());
        initial_map->AppendDescriptor(isolate(), &d);
      }
      // regexp_last_index descriptor.
      {
        Descriptor d = Descriptor::DataField(
            isolate(), factory()->regexp_result_regexp_last_index_symbol(),
            JSRegExpResult::kRegExpLastIndex, attribs,
            Representation::Tagged());
        initial_map->AppendDescriptor(isolate(), &d);
      }
    }
    // Set up the map for RegExp results objects for regexps with the /d flag.
    DirectHandle<Map> initial_with_indices_map =
        Map::Copy(isolate(), initial_map, "JSRegExpResult with indices");
    initial_with_indices_map->set_instance_size(
        JSRegExpResultWithIndices::kSize);
    DCHECK_EQ(initial_with_indices_map->GetInObjectProperties(),
              JSRegExpResultWithIndices::kInObjectPropertyCount);
    // indices descriptor
    {
      Descriptor d =
          Descriptor::DataField(isolate(), factory()->indices_string(),
                                JSRegExpResultWithIndices::kIndicesIndex, NONE,
                                Representation::Tagged());
      Map::EnsureDescriptorSlack(isolate(), initial_with_indices_map, 1);
      initial_with_indices_map->AppendDescriptor(isolate(), &d);
    }
    native_context()->set_regexp_result_map(*initial_map);
    native_context()->set_regexp_result_with_indices_map(
        *initial_with_indices_map);
  }
  // Create a constructor for JSRegExpResultIndices (a variant of Array that
  // predefines the groups property).
  {
    // JSRegExpResultIndices initial map.
    DirectHandle<Map> initial_map = CreateInitialMapForArraySubclass(
        JSRegExpResultIndices::kSize,
        JSRegExpResultIndices::kInObjectPropertyCount);
    // groups descriptor.
    {
      Descriptor d = Descriptor::DataField(
          isolate(), factory()->groups_string(),
          JSRegExpResultIndices::kGroupsIndex, NONE, Representation::Tagged());
      initial_map->AppendDescriptor(isolate(), &d);
      DCHECK_EQ(initial_map->LastAdded().as_int(),
                JSRegExpResultIndices::kGroupsDescriptorIndex);
    }
    native_context()->set_regexp_result_indices_map(*initial_map);
  }
  // Add @@iterator method to the arguments object maps.
  {
    PropertyAttributes attribs = DONT_ENUM;
    DirectHandle<AccessorInfo> arguments_iterator =
        factory()->arguments_iterator_accessor();
    {
      Descriptor d = Descriptor::AccessorConstant(factory()->iterator_symbol(),
                                                  arguments_iterator, attribs);
      DirectHandle<Map> map(native_context()->sloppy_arguments_map(),
                            isolate());
      Map::EnsureDescriptorSlack(isolate(), map, 1);
      map->AppendDescriptor(isolate(), &d);
    }
    {
      Descriptor d = Descriptor::AccessorConstant(factory()->iterator_symbol(),
                                                  arguments_iterator, attribs);
      DirectHandle<Map> map(native_context()->fast_aliased_arguments_map(),
                            isolate());
      Map::EnsureDescriptorSlack(isolate(), map, 1);
      map->AppendDescriptor(isolate(), &d);
    }
    {
      Descriptor d = Descriptor::AccessorConstant(factory()->iterator_symbol(),
                                                  arguments_iterator, attribs);
      DirectHandle<Map> map(native_context()->slow_aliased_arguments_map(),
                            isolate());
      Map::EnsureDescriptorSlack(isolate(), map, 1);
      map->AppendDescriptor(isolate(), &d);
    }
    {
      Descriptor d = Descriptor::AccessorConstant(factory()->iterator_symbol(),
                                                  arguments_iterator, attribs);
      DirectHandle<Map> map(native_context()->strict_arguments_map(),
                            isolate());
      Map::EnsureDescriptorSlack(isolate(), map, 1);
      map->AppendDescriptor(isolate(), &d);
    }
  }
  {
    DirectHandle<OrderedHashSet> promises =
        OrderedHashSet::Allocate(isolate(), 0).ToHandleChecked();
    native_context()->set_atomics_waitasync_promises(*promises);
  }
  return true;
}
References v8::internal::Descriptor::AccessorConstant(), v8::internal::OrderedHashSet::Allocate(), CHECK, CHECK_EQ, v8::internal::Map::Copy(), v8::internal::Map::CopyAsElementsKind(), CreateInitialMapForArraySubclass(), v8::internal::Descriptor::DataField(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::JSArray::DefineOwnProperty(), v8::internal::direct_handle(), v8::internal::DONT_ENUM, v8::internal::Map::EnsureDescriptorSlack(), v8::internal::Isolate::factory(), factory(), v8::internal::FieldIndex::ForDescriptor(), v8::internal::Smi::FromInt(), v8::internal::FROZEN, heap(), v8::internal::index, v8::internal::compiler::initial_map, v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunctionWithBuiltinId(), isolate(), isolate_, v8::internal::IsSmi(), v8::Just(), v8::internal::kAdapt, v8::internal::JSAccessorPropertyDescriptor::kConfigurableIndex, v8::internal::JSDataPropertyDescriptor::kConfigurableIndex, v8::internal::kDontAdapt, v8::internal::JSAccessorPropertyDescriptor::kEnumerableIndex, v8::internal::JSDataPropertyDescriptor::kEnumerableIndex, v8::internal::TemplateInfo::kFastTemplateInstantiationsCacheSize, v8::internal::JSRegExpResultIndices::kGroupsDescriptorIndex, v8::internal::JSRegExpResult::kGroupsIndex, v8::internal::JSRegExpResultIndices::kGroupsIndex, v8::internal::JSRegExpResult::kIndexIndex, v8::internal::JSRegExpResultWithIndices::kIndicesIndex, v8::internal::ApiNatives::kInitialFunctionCacheSize, v8::internal::JSRegExpResult::kInObjectPropertyCount, v8::internal::JSRegExpResultWithIndices::kInObjectPropertyCount, v8::internal::JSRegExpResultIndices::kInObjectPropertyCount, v8::internal::JSRegExpResult::kInputIndex, v8::internal::JSRegExpResult::kNamesIndex, v8::internal::JSRegExpResult::kRegExpInputIndex, v8::internal::JSRegExpResult::kRegExpLastIndex, v8::internal::JSAccessorPropertyDescriptor::kSetIndex, v8::internal::kThrowOnError, v8::internal::JSDataPropertyDescriptor::kWritableIndex, v8::internal::length, native_context(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::Factory::NewContextfulMapForCurrentContext(), v8::internal::FactoryBase< Impl >::NewFixedArrayWithHoles(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NONE, v8::internal::OMIT_TRANSITION, v8::internal::PACKED_ELEMENTS, v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), v8::internal::Map::SetPrototype(), v8::internal::SimpleInstallFunction(), v8::internal::Representation::Tagged(), v8::internal::TERMINAL_FAST_ELEMENTS_KIND, v8::internal::Smi::ToInt(), and v8::internal::Smi::zero().
Referenced by Genesis().
InstallAutoExtensions()
bool v8::internal::Genesis::InstallAutoExtensions (Isolate * isolate, ExtensionStates * extension_states) [static], [private]
Definition at line 6597 of file bootstrapper.cc.
                                                                       {
  for (v8::RegisteredExtension* it = v8::RegisteredExtension::first_extension();
       it != nullptr; it = it->next()) {
    if (it->extension()->auto_enable() &&
        !InstallExtension(isolate, it, extension_states)) {
      return false;
    }
  }
  return true;
}
References v8::RegisteredExtension::first_extension(), InstallExtension(), isolate(), and v8::RegisteredExtension::next().
Referenced by InstallExtensions().
InstallExtension() [1/2]
bool v8::internal::Genesis::InstallExtension (Isolate * isolate, const char * name, ExtensionStates * extension_states) [static], [private]
Definition at line 6620 of file bootstrapper.cc.
                                                                  {
  for (v8::RegisteredExtension* it = v8::RegisteredExtension::first_extension();
       it != nullptr; it = it->next()) {
    if (strcmp(name, it->extension()->name()) == 0) {
      return InstallExtension(isolate, it, extension_states);
    }
  }
  return Utils::ApiCheck(false, "v8::Context::New()",
                         "Cannot find required extension");
}
References v8::Utils::ApiCheck(), v8::RegisteredExtension::first_extension(), isolate(), v8::internal::name, and v8::RegisteredExtension::next().
Referenced by InstallAutoExtensions(), InstallExtension(), InstallExtensions(), and InstallRequestedExtensions().
InstallExtension() [2/2]
bool v8::internal::Genesis::InstallExtension (Isolate * isolate, v8::RegisteredExtension * current, ExtensionStates * extension_states) [static], [private]
Definition at line 6632 of file bootstrapper.cc.
                                                                  {
  HandleScope scope(isolate);
  if (extension_states->get_state(current) == INSTALLED) return true;
  // The current node has already been visited so there must be a
  // cycle in the dependency graph; fail.
  if (!Utils::ApiCheck(extension_states->get_state(current) != VISITED,
                       "v8::Context::New()", "Circular extension dependency")) {
    return false;
  }
  DCHECK(extension_states->get_state(current) == UNVISITED);
  extension_states->set_state(current, VISITED);
  v8::Extension* extension = current->extension();
  // Install the extension's dependencies
  for (int i = 0; i < extension->dependency_count(); i++) {
    if (!InstallExtension(isolate, extension->dependencies()[i],
                          extension_states)) {
      return false;
    }
  }
  if (!CompileExtension(isolate, extension)) {
    // We print out the name of the extension that fail to install.
    // When an error is thrown during bootstrapping we automatically print
    // the line number at which this happened to the console in the isolate
    // error throwing functionality.
    base::OS::PrintError("Error installing extension '%s'.\n",
                         current->extension()->name());
    return false;
  }
  DCHECK(!isolate->has_exception());
  extension_states->set_state(current, INSTALLED);
  return true;
}
References v8::Utils::ApiCheck(), CompileExtension(), v8::internal::DCHECK(), v8::Extension::dependencies(), v8::Extension::dependency_count(), v8::RegisteredExtension::extension(), v8::internal::Genesis::ExtensionStates::get_state(), v8::internal::Isolate::has_exception(), INSTALLED, InstallExtension(), isolate(), v8::Extension::name(), v8::internal::Genesis::ExtensionStates::set_state(), UNVISITED, and VISITED.
InstallExtensions()
bool v8::internal::Genesis::InstallExtensions (Isolate * isolate, DirectHandle< Context > native_context, v8::ExtensionConfiguration * extensions) [static], [private]
Definition at line 6568 of file bootstrapper.cc.
                                                                      {
  ExtensionStates extension_states; // All extensions have state UNVISITED.
  return InstallAutoExtensions(isolate, &extension_states) &&
         (!v8_flags.expose_gc ||
          InstallExtension(isolate, "v8/gc", &extension_states)) &&
         (!v8_flags.expose_externalize_string ||
          InstallExtension(isolate, "v8/externalize", &extension_states)) &&
         (!(v8_flags.expose_statistics ||
            TracingFlags::is_gc_stats_enabled()) ||
          InstallExtension(isolate, "v8/statistics", &extension_states)) &&
         (!v8_flags.expose_trigger_failure ||
          InstallExtension(isolate, "v8/trigger-failure", &extension_states)) &&
         (!v8_flags.expose_ignition_statistics ||
          InstallExtension(isolate, "v8/ignition-statistics",
                           &extension_states)) &&
         (!isValidCpuTraceMarkFunctionName() ||
          InstallExtension(isolate, "v8/cpumark", &extension_states)) &&
#ifdef V8_FUZZILLI
         InstallExtension(isolate, "v8/fuzzilli", &extension_states) &&
#endif
#ifdef ENABLE_VTUNE_TRACEMARK
         (!v8_flags.enable_vtune_domain_support ||
          InstallExtension(isolate, "v8/vtunedomain", &extension_states)) &&
#endif // ENABLE_VTUNE_TRACEMARK
         InstallRequestedExtensions(isolate, extensions, &extension_states);
}
References InstallAutoExtensions(), InstallExtension(), InstallRequestedExtensions(), v8::internal::TracingFlags::is_gc_stats_enabled(), isolate(), v8::internal::isValidCpuTraceMarkFunctionName(), and v8::internal::v8_flags.
Referenced by v8::internal::Bootstrapper::InstallExtensions().
InstallExtrasBindings()
bool v8::internal::Genesis::InstallExtrasBindings () [private]
Definition at line 6457 of file bootstrapper.cc.
                                    {
  HandleScope scope(isolate());
  DirectHandle<JSObject> extras_binding = factory()->NewJSObjectWithNullProto();
  // binding.isTraceCategoryEnabled(category)
  SimpleInstallFunction(isolate(), extras_binding, "isTraceCategoryEnabled",
                        Builtin::kIsTraceCategoryEnabled, 1, kAdapt);
  // binding.trace(phase, category, name, id, data)
  SimpleInstallFunction(isolate(), extras_binding, "trace", Builtin::kTrace, 5,
                        kAdapt);
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  // binding.getContinuationPreservedEmbedderData()
  SimpleInstallFunction(
      isolate(), extras_binding, "getContinuationPreservedEmbedderData",
      Builtin::kGetContinuationPreservedEmbedderData, 0, kAdapt);
  // binding.setContinuationPreservedEmbedderData(value)
  SimpleInstallFunction(
      isolate(), extras_binding, "setContinuationPreservedEmbedderData",
      Builtin::kSetContinuationPreservedEmbedderData, 1, kAdapt);
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  InitializeConsole(extras_binding);
  native_context()->set_extras_binding_object(*extras_binding);
  return true;
}
References factory(), InitializeConsole(), isolate(), v8::internal::kAdapt, native_context(), v8::internal::Factory::NewJSObjectWithNullProto(), and v8::internal::SimpleInstallFunction().
Referenced by Genesis().
InstallGlobalThisBinding()
void v8::internal::Genesis::InstallGlobalThisBinding () [private]
Definition at line 1361 of file bootstrapper.cc.
                                       {
  DirectHandle<ScopeInfo> scope_info =
      isolate()->factory()->global_this_binding_scope_info();
  DirectHandle<Context> context =
      factory()->NewScriptContext(native_context(), scope_info);
  // Go ahead and hook it up while we're at it.
  int slot = scope_info->ReceiverContextSlotIndex();
  context->SetNoCell(slot, native_context()->global_proxy());
  Handle<ScriptContextTable> script_contexts(
      native_context()->script_context_table(), isolate());
  DirectHandle<ScriptContextTable> new_script_contexts =
      ScriptContextTable::Add(isolate(), script_contexts, context, false);
  native_context()->set_script_context_table(*new_script_contexts);
}
References v8::internal::ScriptContextTable::Add(), v8::internal::Isolate::factory(), factory(), global_proxy(), isolate(), native_context(), and v8::internal::Factory::NewScriptContext().
Referenced by InitializeGlobal().
InstallRequestedExtensions()
bool v8::internal::Genesis::InstallRequestedExtensions (Isolate * isolate, v8::ExtensionConfiguration * extensions, ExtensionStates * extension_states) [static], [private]
Definition at line 6609 of file bootstrapper.cc.
                                                                            {
  for (const char** it = extensions->begin(); it != extensions->end(); ++it) {
    if (!InstallExtension(isolate, *it, extension_states)) return false;
  }
  return true;
}
References v8::ExtensionConfiguration::begin(), v8::ExtensionConfiguration::end(), InstallExtension(), and isolate().
Referenced by InstallExtensions().
InstallSpecialObjects()
bool v8::internal::Genesis::InstallSpecialObjects (Isolate * isolate, DirectHandle< NativeContext > native_context) [static], [private]
Definition at line 6520 of file bootstrapper.cc.
                                                                  {
  HandleScope scope(isolate);
  // Error.stackTraceLimit.
  {
    DirectHandle<JSObject> Error = isolate->error_function();
    DirectHandle<String> name = isolate->factory()->stackTraceLimit_string();
    DirectHandle<Smi> stack_trace_limit(
        Smi::FromInt(v8_flags.stack_trace_limit), isolate);
    JSObject::AddProperty(isolate, Error, name, stack_trace_limit, NONE);
  }
#if V8_ENABLE_WEBASSEMBLY
  WasmJs::Install(isolate);
#endif // V8_ENABLE_WEBASSEMBLY
#ifdef V8_ENABLE_MEMORY_CORRUPTION_API
  if (v8_flags.expose_memory_corruption_api) {
    SandboxTesting::InstallMemoryCorruptionApi(isolate);
  }
#endif // V8_ENABLE_MEMORY_CORRUPTION_API
  return true;
}
References v8::internal::JSObject::AddProperty(), v8::internal::torque::Error(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::WasmJs::Install(), isolate(), v8::internal::name, v8::internal::NONE, and v8::internal::v8_flags.
Referenced by v8::internal::Bootstrapper::InstallExtensions().
InstallTypedArray()
DirectHandle< JSFunction > v8::internal::Genesis::InstallTypedArray (const char * name, ElementsKind elements_kind, InstanceType constructor_type, int rab_gsab_initial_map_index) [private]
Definition at line 5047 of file bootstrapper.cc.
                                    {
  DirectHandle<JSObject> global(native_context()->global_object(), isolate());
  DirectHandle<JSObject> typed_array_prototype =
      isolate()->typed_array_prototype();
  DirectHandle<JSFunction> typed_array_function =
      isolate()->typed_array_function();
  DirectHandle<JSFunction> result = InstallFunction(
      isolate(), global, name, JS_TYPED_ARRAY_TYPE,
      JSTypedArray::kSizeWithEmbedderFields, 0, factory()->the_hole_value(),
      Builtin::kTypedArrayConstructor, 3, kDontAdapt);
  result->initial_map()->set_elements_kind(elements_kind);
  CHECK(JSObject::SetPrototype(isolate(), result, typed_array_function, false,
                               kDontThrow)
            .FromJust());
  DirectHandle<Smi> bytes_per_element(
      Smi::FromInt(1 << ElementsKindToShiftSize(elements_kind)), isolate());
  InstallConstant(isolate(), result, "BYTES_PER_ELEMENT", bytes_per_element);
  // TODO(v8:11256, ishell): given the granularity of typed array constructor
  // protectors, consider creating only one constructor instance type for all
  // typed array constructors.
  SetConstructorInstanceType(isolate_, result, constructor_type);
  // Setup prototype object.
  DCHECK(IsJSObject(result->prototype()));
  DirectHandle<JSObject> prototype(Cast<JSObject>(result->prototype()),
                                   isolate());
  CHECK(JSObject::SetPrototype(isolate(), prototype, typed_array_prototype,
                               false, kDontThrow)
            .FromJust());
  CHECK_NE(prototype->map().ptr(),
           isolate_->initial_object_prototype()->map().ptr());
  prototype->map()->set_instance_type(JS_TYPED_ARRAY_PROTOTYPE_TYPE);
  InstallConstant(isolate(), prototype, "BYTES_PER_ELEMENT", bytes_per_element);
  // RAB / GSAB backed TypedArrays don't have separate constructors, but they
  // have their own maps. Create the corresponding map here.
  DirectHandle<Map> rab_gsab_initial_map =
      factory()->NewContextfulMapForCurrentContext(
          JS_TYPED_ARRAY_TYPE, JSTypedArray::kSizeWithEmbedderFields,
          GetCorrespondingRabGsabElementsKind(elements_kind), 0);
  rab_gsab_initial_map->SetConstructor(*result);
  if (rab_gsab_initial_map_index == Context::RAB_GSAB_FLOAT16_ARRAY_MAP_INDEX &&
      v8_flags.js_float16array) {
    LOG(isolate(), MapDetails(*rab_gsab_initial_map));
  }
  native_context()->set(rab_gsab_initial_map_index, *rab_gsab_initial_map,
                        UPDATE_WRITE_BARRIER, kReleaseStore);
  Map::SetPrototype(isolate(), rab_gsab_initial_map, prototype);
  return result;
}
References CHECK, CHECK_NE, v8::internal::DCHECK(), v8::internal::ElementsKindToShiftSize(), factory(), v8::internal::Smi::FromInt(), v8::internal::GetCorrespondingRabGsabElementsKind(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallConstant(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunction(), isolate(), isolate_, v8::internal::kDontAdapt, v8::internal::kDontThrow, v8::kReleaseStore, v8::internal::JSTypedArray::kSizeWithEmbedderFields, LOG, v8::internal::name, native_context(), v8::internal::Factory::NewContextfulMapForCurrentContext(), v8::internal::prototype, result(), v8::internal::anonymous_namespace{bootstrapper.cc}::SetConstructorInstanceType(), v8::internal::JSObject::SetPrototype(), v8::internal::Map::SetPrototype(), v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::v8_flags.
isolate()
Isolate* v8::internal::Genesis::isolate () const [inline]
Definition at line 194 of file bootstrapper.cc.
{ return isolate_; }
References isolate_.
Referenced by AddRestrictedFunctionProperties(), CompileExtension(), ConfigureApiObject(), ConfigureGlobalObject(), CreateArrayBuffer(), CreateAsyncFunctionMaps(), CreateAsyncIteratorMaps(), CreateEmptyFunction(), CreateInitialMapForArraySubclass(), CreateIteratorMaps(), CreateJSProxyMaps(), CreateNewGlobals(), CreateObjectFunction(), CreateRoots(), Genesis(), GetThrowTypeErrorIntrinsic(), HookUpGlobalObject(), HookUpGlobalProxy(), InitializeCallSiteBuiltins(), InitializeConsole(), InitializeGlobal(), InitializeGlobal_regexp_linear_flag(), InitializeGlobal_sharedarraybuffer(), InitializeIteratorFunctions(), InitializeMapCaches(), InstallABunchOfRandomThings(), InstallAutoExtensions(), InstallExtension(), InstallExtensions(), InstallExtrasBindings(), InstallGlobalThisBinding(), InstallRequestedExtensions(), InstallSpecialObjects(), InstallTypedArray(), v8::internal::PropertyAlreadyExists(), TransferIndexedProperties(), TransferNamedProperties(), and TransferObject().
native_context()
DirectHandle<NativeContext> v8::internal::Genesis::native_context () [inline], [private]
Definition at line 204 of file bootstrapper.cc.
{ return native_context_; }
References native_context_.
Referenced by ConfigureGlobalObject(), CreateAsyncFunctionMaps(), CreateAsyncIteratorMaps(), CreateEmptyFunction(), CreateInitialMapForArraySubclass(), CreateIteratorMaps(), CreateJSProxyMaps(), CreateNewGlobals(), CreateObjectFunction(), CreateRoots(), CreateSloppyModeFunctionMaps(), CreateStrictModeFunctionMaps(), Genesis(), HookUpGlobalObject(), HookUpGlobalProxy(), InitializeGlobal(), InitializeGlobal_regexp_linear_flag(), InitializeGlobal_sharedarraybuffer(), InitializeIteratorFunctions(), InitializeMapCaches(), InstallABunchOfRandomThings(), InstallExtrasBindings(), InstallGlobalThisBinding(), and InstallTypedArray().
result()
DirectHandle<NativeContext> v8::internal::Genesis::result () [inline]
Definition at line 199 of file bootstrapper.cc.
{ return result_; }
References result_.
Referenced by v8::internal::Bootstrapper::CreateEnvironment(), and InstallTypedArray().
TransferIndexedProperties()
void v8::internal::Genesis::TransferIndexedProperties (DirectHandle< JSObject > from, DirectHandle< JSObject > to) [private]
Definition at line 6862 of file bootstrapper.cc.
                                                                   {
  // Cloning the elements array is sufficient.
  Handle<FixedArray> from_elements(Cast<FixedArray>(from->elements()),
                                   isolate());
  DirectHandle<FixedArray> to_elements =
      factory()->CopyFixedArray(from_elements);
  to->set_elements(*to_elements);
}
References v8::internal::Factory::CopyFixedArray(), factory(), and isolate().
Referenced by HookUpGlobalObject(), and TransferObject().
TransferNamedProperties()
void v8::internal::Genesis::TransferNamedProperties (DirectHandle< JSObject > from, DirectHandle< JSObject > to) [private]
Definition at line 6744 of file bootstrapper.cc.
                                                                 {
  // If JSObject::AddProperty asserts due to already existing property,
  // it is likely due to both global objects sharing property name(s).
  // Merging those two global objects is impossible.
  // The global template must not create properties that already exist
  // in the snapshotted global object.
  if (from->HasFastProperties()) {
    DirectHandle<DescriptorArray> descs(
        from->map()->instance_descriptors(isolate()), isolate());
    for (InternalIndex i : from->map()->IterateOwnDescriptors()) {
      PropertyDetails details = descs->GetDetails(i);
      if (details.location() == PropertyLocation::kField) {
        if (details.kind() == PropertyKind::kData) {
          HandleScope inner(isolate());
          DirectHandle<Name> key(descs->GetKey(i), isolate());
          // If the property is already there we skip it.
          if (PropertyAlreadyExists(isolate(), to, key)) continue;
          FieldIndex index = FieldIndex::ForDetails(from->map(), details);
          DirectHandle<Object> value = JSObject::FastPropertyAt(
              isolate(), from, details.representation(), index);
          JSObject::AddProperty(isolate(), to, key, value,
                                details.attributes());
        } else {
          DCHECK_EQ(PropertyKind::kAccessor, details.kind());
          UNREACHABLE();
        }
      } else {
        DCHECK_EQ(PropertyLocation::kDescriptor, details.location());
        DCHECK_EQ(PropertyKind::kAccessor, details.kind());
        DirectHandle<Name> key(descs->GetKey(i), isolate());
        // If the property is already there we skip it.
        if (PropertyAlreadyExists(isolate(), to, key)) continue;
        HandleScope inner(isolate());
        DCHECK(!to->HasFastProperties());
        // Add to dictionary.
        DirectHandle<Object> value(descs->GetStrongValue(i), isolate());
        PropertyDetails d(PropertyKind::kAccessor, details.attributes(),
                          PropertyCellType::kMutable);
        JSObject::SetNormalizedProperty(to, key, value, d);
      }
    }
  } else if (IsJSGlobalObject(*from)) {
    // Copy all keys and values in enumeration order.
    DirectHandle<GlobalDictionary> properties(
        Cast<JSGlobalObject>(*from)->global_dictionary(kAcquireLoad),
        isolate());
    DirectHandle<FixedArray> indices =
        GlobalDictionary::IterationIndices(isolate(), properties);
    for (int i = 0; i < indices->length(); i++) {
      InternalIndex index(Smi::ToInt(indices->get(i)));
      DirectHandle<PropertyCell> cell(properties->CellAt(index), isolate());
      DirectHandle<Name> key(cell->name(), isolate());
      // If the property is already there we skip it.
      if (PropertyAlreadyExists(isolate(), to, key)) continue;
      // Set the property.
      DirectHandle<Object> value(cell->value(), isolate());
      if (IsTheHole(*value, isolate())) continue;
      PropertyDetails details = cell->property_details();
      if (details.kind() == PropertyKind::kData) {
        JSObject::AddProperty(isolate(), to, key, value, details.attributes());
      } else {
        DCHECK_EQ(PropertyKind::kAccessor, details.kind());
        DCHECK(!to->HasFastProperties());
        PropertyDetails d(PropertyKind::kAccessor, details.attributes(),
                          PropertyCellType::kMutable);
        JSObject::SetNormalizedProperty(to, key, value, d);
      }
    }
  } else if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    // Copy all keys and values in enumeration order.
    DirectHandle<SwissNameDictionary> properties(
        from->property_dictionary_swiss(), isolate());
    ReadOnlyRoots roots(isolate());
    for (InternalIndex entry : properties->IterateEntriesOrdered()) {
      Tagged<Object> raw_key;
      if (!properties->ToKey(roots, entry, &raw_key)) continue;
      DCHECK(IsName(raw_key));
      DirectHandle<Name> key(Cast<Name>(raw_key), isolate());
      // If the property is already there we skip it.
      if (PropertyAlreadyExists(isolate(), to, key)) continue;
      // Set the property.
      DirectHandle<Object> value(properties->ValueAt(entry), isolate());
      DCHECK(!IsCell(*value));
      DCHECK(!IsTheHole(*value, isolate()));
      PropertyDetails details = properties->DetailsAt(entry);
      DCHECK_EQ(PropertyKind::kData, details.kind());
      JSObject::AddProperty(isolate(), to, key, value, details.attributes());
    }
  } else {
    // Copy all keys and values in enumeration order.
    DirectHandle<NameDictionary> properties(from->property_dictionary(),
                                            isolate());
    DirectHandle<FixedArray> key_indices =
        NameDictionary::IterationIndices(isolate(), properties);
    ReadOnlyRoots roots(isolate());
    for (int i = 0; i < key_indices->length(); i++) {
      InternalIndex key_index(Smi::ToInt(key_indices->get(i)));
      Tagged<Object> raw_key = properties->KeyAt(key_index);
      DCHECK(properties->IsKey(roots, raw_key));
      DCHECK(IsName(raw_key));
      DirectHandle<Name> key(Cast<Name>(raw_key), isolate());
      // If the property is already there we skip it.
      if (PropertyAlreadyExists(isolate(), to, key)) continue;
      // Set the property.
      DirectHandle<Object> value(properties->ValueAt(key_index), isolate());
      DCHECK(!IsCell(*value));
      DCHECK(!IsTheHole(*value, isolate()));
      PropertyDetails details = properties->DetailsAt(key_index);
      DCHECK_EQ(PropertyKind::kData, details.kind());
      JSObject::AddProperty(isolate(), to, key, value, details.attributes());
    }
  }
}
References v8::internal::JSObject::AddProperty(), v8::internal::PropertyDetails::attributes(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::JSObject::FastPropertyAt(), v8::internal::FieldIndex::ForDetails(), v8::internal::index, isolate(), v8::internal::kAccessor, v8::kAcquireLoad, v8::internal::kData, v8::internal::kDescriptor, v8::internal::key, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::kMutable, v8::internal::PropertyDetails::location(), v8::internal::PropertyAlreadyExists(), v8::internal::PropertyDetails::representation(), v8::internal::JSObject::SetNormalizedProperty(), v8::internal::Smi::ToInt(), v8::internal::UNREACHABLE(), V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, and v8::internal::value.
Referenced by HookUpGlobalObject(), and TransferObject().
TransferObject()
void v8::internal::Genesis::TransferObject (DirectHandle< JSObject > from, DirectHandle< JSObject > to) [private]
Definition at line 6872 of file bootstrapper.cc.
                                                        {
  HandleScope outer(isolate());
  DCHECK(!IsJSArray(*from));
  DCHECK(!IsJSArray(*to));
  TransferNamedProperties(from, to);
  TransferIndexedProperties(from, to);
  // Transfer the prototype (new map is needed).
  DirectHandle<JSPrototype> proto(from->map()->prototype(), isolate());
  JSObject::ForceSetPrototype(isolate(), to, proto);
}
References v8::internal::DCHECK(), v8::internal::JSObject::ForceSetPrototype(), isolate(), TransferIndexedProperties(), and TransferNamedProperties().
Referenced by ConfigureApiObject().
Friends And Related Function Documentation
Bootstrapper
friend class Bootstrapper [friend]
Definition at line 342 of file bootstrapper.cc.
Member Data Documentation
active_
BootstrapperActive v8::internal::Genesis::active_ [private]
Definition at line 341 of file bootstrapper.cc.
global_proxy_
DirectHandle<JSGlobalProxy> v8::internal::Genesis::global_proxy_ [private]
Definition at line 336 of file bootstrapper.cc.
Referenced by Genesis(), and global_proxy().
isolate_
Isolate* v8::internal::Genesis::isolate_ [private]
Definition at line 333 of file bootstrapper.cc.
Referenced by builtins(), ConfigureApiObject(), CreateIteratorMaps(), CreateJSProxyMaps(), CreateObjectFunction(), CreateSloppyModeFunctionMaps(), CreateStrictModeFunctionMaps(), factory(), GetThrowTypeErrorIntrinsic(), heap(), InitializeConsole(), InitializeGlobal(), InitializeGlobal_sharedarraybuffer(), InitializeIteratorFunctions(), InstallABunchOfRandomThings(), InstallTypedArray(), and isolate().
native_context_
DirectHandle<NativeContext> v8::internal::Genesis::native_context_ [private]
Definition at line 335 of file bootstrapper.cc.
Referenced by CreateRoots(), Genesis(), and native_context().
restricted_properties_thrower_
DirectHandle<JSFunction> v8::internal::Genesis::restricted_properties_thrower_ [private]
Definition at line 339 of file bootstrapper.cc.
Referenced by GetThrowTypeErrorIntrinsic().
result_
DirectHandle<NativeContext> v8::internal::Genesis::result_ [private]
Definition at line 334 of file bootstrapper.cc.
Referenced by Genesis(), and result().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/init/bootstrapper.cc