v8::internal::HandlerTable Class Reference
#include <handler-table.h>
Public Types
enum CatchPrediction {
UNCAUGHT
, CAUGHT
, PROMISE
, ASYNC_AWAIT
,
UNCAUGHT_ASYNC_AWAIT
 }
enum EncodingMode { kRangeBasedEncoding
, kReturnAddressBasedEncoding
 }
Public Member Functions
HandlerTable (Tagged< InstructionStream > code)
HandlerTable (Tagged< Code > code)
HandlerTable (Tagged< TrustedByteArray > byte_array)
HandlerTable (Tagged< BytecodeArray > bytecode_array)
HandlerTable (Address handler_table, int handler_table_size, EncodingMode encoding_mode)
int GetRangeStart (int index) const
int GetRangeEnd (int index) const
int GetRangeHandler (int index) const
int GetRangeData (int index) const
void SetRangeStart (int index, int value)
void SetRangeEnd (int index, int value)
void SetRangeHandler (int index, int offset, CatchPrediction pred)
void SetRangeData (int index, int value)
int LookupHandlerIndexForRange (int pc_offset) const
int LookupReturn (int pc_offset)
int NumberOfRangeEntries () const
int NumberOfReturnEntries () const
bool HandlerWasUsed (int index) const
void MarkHandlerUsed (int index)
CatchPrediction GetRangePrediction (int index) const
Static Public Member Functions
static int LengthForRange (int entries)
static int EmitReturnTableStart (Assembler *masm)
static void EmitReturnEntry (Assembler *masm, int offset, int handler)
Static Public Attributes
static const int kNoHandlerFound = -1
static const int kLazyDeopt = HandlerOffsetField::kMax
Private Types
using HandlerPredictionField = base::BitField< CatchPrediction, 0, 3 >
using HandlerWasUsedField = HandlerPredictionField::Next< bool, 1 >
using HandlerOffsetField = HandlerWasUsedField::Next< int, 28 >
Private Member Functions
int GetRangeHandlerBitfield (int index) const
int GetReturnOffset (int index) const
int GetReturnHandler (int index) const
Static Private Member Functions
static int EntrySizeFromMode (EncodingMode mode)
Private Attributes
const int number_of_entries_
const Address raw_encoded_data_
Static Private Attributes
static const int kRangeStartIndex = 0
static const int kRangeEndIndex = 1
static const int kRangeHandlerIndex = 2
static const int kRangeDataIndex = 3
static const int kRangeEntrySize = 4
static const int kReturnOffsetIndex = 0
static const int kReturnHandlerIndex = 1
static const int kReturnEntrySize = 2
Detailed Description
Definition at line 37 of file handler-table.h.
Member Typedef Documentation
HandlerOffsetField
using v8::internal::HandlerTable::HandlerOffsetField = HandlerWasUsedField::Next<int, 28> [private]
Definition at line 151 of file handler-table.h.
HandlerPredictionField
using v8::internal::HandlerTable::HandlerPredictionField = base::BitField<CatchPrediction, 0, 3> [private]
Definition at line 149 of file handler-table.h.
HandlerWasUsedField
using v8::internal::HandlerTable::HandlerWasUsedField = HandlerPredictionField::Next<bool, 1> [private]
Definition at line 150 of file handler-table.h.
Member Enumeration Documentation
CatchPrediction
enum v8::internal::HandlerTable::CatchPrediction
Enumerator
UNCAUGHT
CAUGHT
PROMISE
ASYNC_AWAIT
UNCAUGHT_ASYNC_AWAIT
Definition at line 42 of file handler-table.h.
                       {
    UNCAUGHT, // The handler will (likely) rethrow the exception.
    CAUGHT, // The exception will be caught by the handler.
    PROMISE, // The exception will be caught and cause a promise rejection.
    ASYNC_AWAIT, // The exception will be caught and cause a promise rejection
                  // in the desugaring of an async function, so special
                  // async/await handling in the debugger can take place.
    UNCAUGHT_ASYNC_AWAIT, // The exception will be caught and cause a promise
                           // rejection in the desugaring of an async REPL
                           // script. The corresponding message object needs to
                           // be kept alive on the Isolate though.
  };
EncodingMode
enum v8::internal::HandlerTable::EncodingMode
Enumerator
kRangeBasedEncoding
kReturnAddressBasedEncoding
Definition at line 55 of file handler-table.h.
{ kRangeBasedEncoding, kReturnAddressBasedEncoding };
Constructor & Destructor Documentation
HandlerTable() [1/5]
v8::internal::HandlerTable::HandlerTable (Tagged< InstructionStream > code) [explicit]
HandlerTable() [2/5]
v8::internal::HandlerTable::HandlerTable (Tagged< Code > code) [explicit]
Definition at line 22 of file handler-table.cc.
    : HandlerTable(code->handler_table_address(), code->handler_table_size(),
                   kReturnAddressBasedEncoding) {}
HandlerTable() [3/5]
v8::internal::HandlerTable::HandlerTable (Tagged< TrustedByteArray > byte_array) [explicit]
Definition at line 35 of file handler-table.cc.
    : HandlerTable(reinterpret_cast<Address>(byte_array->begin()),
                   byte_array->length(), kRangeBasedEncoding) {}
HandlerTable() [4/5]
v8::internal::HandlerTable::HandlerTable (Tagged< BytecodeArray > bytecode_array) [explicit]
Definition at line 32 of file handler-table.cc.
    : HandlerTable(bytecode_array->handler_table()) {}
HandlerTable() [5/5]
v8::internal::HandlerTable::HandlerTable (Address handler_table, int handler_table_size, EncodingMode encoding_mode)
Definition at line 39 of file handler-table.cc.
    : number_of_entries_(handler_table_size / EntrySizeFromMode(encoding_mode) /
                         sizeof(int32_t)),
#ifdef DEBUG
      mode_(encoding_mode),
#endif
      raw_encoded_data_(handler_table) {
  // Check padding.
  static_assert(4 < kReturnEntrySize * sizeof(int32_t), "allowed padding");
  // For return address encoding, maximum padding is 4; otherwise, there should
  // be no padding.
  DCHECK_GE(kReturnAddressBasedEncoding == encoding_mode ? 4 : 0,
            handler_table_size %
                (EntrySizeFromMode(encoding_mode) * sizeof(int32_t)));
}
References DCHECK_GE, EntrySizeFromMode(), kReturnAddressBasedEncoding, and kReturnEntrySize.
Member Function Documentation
EmitReturnEntry()
void v8::internal::HandlerTable::EmitReturnEntry (Assembler * masm, int offset, int handler) [static]
Definition at line 170 of file handler-table.cc.
                                                                           {
  masm->dd(offset);
  masm->dd(HandlerOffsetField::encode(handler));
}
References v8::internal::Assembler::dd(), and v8::base::BitField< T, shift, size, U >::encode().
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler(), v8::internal::maglev::MaglevCodeGenerator::EmitMetadata(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishFunction().
EmitReturnTableStart()
int v8::internal::HandlerTable::EmitReturnTableStart (Assembler * masm) [static]
Definition at line 162 of file handler-table.cc.
                                                      {
  masm->DataAlign(InstructionStream::kMetadataAlignment);
  masm->RecordComment(";;; Exception handler table.");
  int table_start = masm->pc_offset();
  return table_start;
}
References v8::internal::Assembler::DataAlign(), v8::internal::InstructionStream::kMetadataAlignment, v8::internal::AssemblerBase::pc_offset(), and v8::internal::AssemblerBase::RecordComment().
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler(), v8::internal::maglev::MaglevCodeGenerator::EmitMetadata(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishFunction().
EntrySizeFromMode()
int v8::internal::HandlerTable::EntrySizeFromMode (EncodingMode mode) [static], [private]
Definition at line 57 of file handler-table.cc.
                                                     {
  switch (mode) {
    case kReturnAddressBasedEncoding:
      return kReturnEntrySize;
    case kRangeBasedEncoding:
      return kRangeEntrySize;
  }
  UNREACHABLE();
}
References kRangeBasedEncoding, kRangeEntrySize, kReturnAddressBasedEncoding, kReturnEntrySize, mode(), and v8::internal::UNREACHABLE().
Referenced by HandlerTable().
GetRangeData()
int v8::internal::HandlerTable::GetRangeData (int index) const
Definition at line 93 of file handler-table.cc.
                                              {
  DCHECK_EQ(kRangeBasedEncoding, mode_);
  DCHECK_LT(index, NumberOfRangeEntries());
  int offset = index * kRangeEntrySize + kRangeDataIndex;
  return Memory<int32_t>(raw_encoded_data_ + offset * sizeof(int32_t));
}
References DCHECK_EQ, DCHECK_LT, v8::internal::index, kRangeBasedEncoding, kRangeDataIndex, kRangeEntrySize, NumberOfRangeEntries(), and raw_encoded_data_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildMergeStates(), v8::internal::compiler::BytecodeGraphBuilder::ExitThenEnterExceptionHandlers(), v8::internal::anonymous_namespace{deoptimizer.cc}::LookupCatchHandler(), v8::internal::UnoptimizedJSFrame::LookupExceptionHandlerInTable(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness().
GetRangeEnd()
int v8::internal::HandlerTable::GetRangeEnd (int index) const
Definition at line 74 of file handler-table.cc.
                                             {
  DCHECK_EQ(kRangeBasedEncoding, mode_);
  DCHECK_LT(index, NumberOfRangeEntries());
  int offset = index * kRangeEntrySize + kRangeEndIndex;
  return Memory<int32_t>(raw_encoded_data_ + offset * sizeof(int32_t));
}
References DCHECK_EQ, DCHECK_LT, v8::internal::index, kRangeBasedEncoding, kRangeEndIndex, kRangeEntrySize, NumberOfRangeEntries(), and raw_encoded_data_.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::ExitThenEnterExceptionHandlers(), LookupHandlerIndexForRange(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
GetRangeHandler()
int v8::internal::HandlerTable::GetRangeHandler (int index) const
Definition at line 89 of file handler-table.cc.
                                                 {
  return HandlerOffsetField::decode(GetRangeHandlerBitfield(index));
}
References v8::base::BitField< T, shift, size, U >::decode(), GetRangeHandlerBitfield(), and v8::internal::index.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildMergeStates(), v8::internal::compiler::BytecodeGraphBuilder::ExitThenEnterExceptionHandlers(), v8::internal::baseline::BaselineCompiler::GenerateCode(), v8::internal::anonymous_namespace{deoptimizer.cc}::LookupCatchHandler(), v8::internal::UnoptimizedJSFrame::LookupExceptionHandlerInTable(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
GetRangeHandlerBitfield()
int v8::internal::HandlerTable::GetRangeHandlerBitfield (int index) const [private]
Definition at line 81 of file handler-table.cc.
                                                         {
  DCHECK_EQ(kRangeBasedEncoding, mode_);
  DCHECK_LT(index, NumberOfRangeEntries());
  int offset = index * kRangeEntrySize + kRangeHandlerIndex;
  return base::Relaxed_Load(
      &Memory<int32_t>(raw_encoded_data_ + offset * sizeof(int32_t)));
}
References DCHECK_EQ, DCHECK_LT, v8::internal::index, kRangeBasedEncoding, kRangeEntrySize, kRangeHandlerIndex, NumberOfRangeEntries(), raw_encoded_data_, and v8::base::Relaxed_Load().
Referenced by GetRangeHandler(), GetRangePrediction(), and HandlerWasUsed().
GetRangePrediction()
HandlerTable::CatchPrediction v8::internal::HandlerTable::GetRangePrediction (int index) const
Definition at line 100 of file handler-table.cc.
                     {
  return HandlerPredictionField::decode(GetRangeHandlerBitfield(index));
}
References v8::base::BitField< T, shift, size, U >::decode(), GetRangeHandlerBitfield(), and v8::internal::index.
Referenced by v8::internal::UnoptimizedJSFrame::LookupExceptionHandlerInTable(), and v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionFromBytecode().
GetRangeStart()
int v8::internal::HandlerTable::GetRangeStart (int index) const
Definition at line 67 of file handler-table.cc.
                                               {
  DCHECK_EQ(kRangeBasedEncoding, mode_);
  DCHECK_LT(index, NumberOfRangeEntries());
  int offset = index * kRangeEntrySize + kRangeStartIndex;
  return Memory<int32_t>(raw_encoded_data_ + offset * sizeof(int32_t));
}
References DCHECK_EQ, DCHECK_LT, v8::internal::index, kRangeBasedEncoding, kRangeEntrySize, kRangeStartIndex, NumberOfRangeEntries(), and raw_encoded_data_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoopForPeeling(), v8::internal::compiler::BytecodeGraphBuilder::ExitThenEnterExceptionHandlers(), LookupHandlerIndexForRange(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
GetReturnHandler()
int v8::internal::HandlerTable::GetReturnHandler (int index) const [private]
Definition at line 124 of file handler-table.cc.
                                                  {
  DCHECK_EQ(kReturnAddressBasedEncoding, mode_);
  DCHECK_LT(index, NumberOfReturnEntries());
  int offset = index * kReturnEntrySize + kReturnHandlerIndex;
  return HandlerOffsetField::decode(
      Memory<int32_t>(raw_encoded_data_ + offset * sizeof(int32_t)));
}
References DCHECK_EQ, DCHECK_LT, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, kReturnAddressBasedEncoding, kReturnEntrySize, kReturnHandlerIndex, NumberOfReturnEntries(), and raw_encoded_data_.
Referenced by LookupReturn().
GetReturnOffset()
int v8::internal::HandlerTable::GetReturnOffset (int index) const [private]
Definition at line 117 of file handler-table.cc.
                                                 {
  DCHECK_EQ(kReturnAddressBasedEncoding, mode_);
  DCHECK_LT(index, NumberOfReturnEntries());
  int offset = index * kReturnEntrySize + kReturnOffsetIndex;
  return Memory<int32_t>(raw_encoded_data_ + offset * sizeof(int32_t));
}
References DCHECK_EQ, DCHECK_LT, v8::internal::index, kReturnAddressBasedEncoding, kReturnEntrySize, kReturnOffsetIndex, NumberOfReturnEntries(), and raw_encoded_data_.
HandlerWasUsed()
bool v8::internal::HandlerTable::HandlerWasUsed (int index) const
Definition at line 105 of file handler-table.cc.
                                                 {
  return HandlerWasUsedField::decode(GetRangeHandlerBitfield(index));
}
References v8::base::BitField< T, shift, size, U >::decode(), GetRangeHandlerBitfield(), and v8::internal::index.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildMergeStates().
LengthForRange()
int v8::internal::HandlerTable::LengthForRange (int entries) [static]
Definition at line 157 of file handler-table.cc.
                                            {
  return entries * kRangeEntrySize * sizeof(int32_t);
}
References kRangeEntrySize.
Referenced by v8::internal::interpreter::HandlerTableBuilder::ToHandlerTable().
LookupHandlerIndexForRange()
int v8::internal::HandlerTable::LookupHandlerIndexForRange (int pc_offset) const
Definition at line 185 of file handler-table.cc.
                                                                {
  int innermost_handler = kNoHandlerFound;
#ifdef DEBUG
  // Assuming that ranges are well nested, we don't need to track the innermost
  // offsets. This is just to verify that the table is actually well nested.
  int innermost_start = std::numeric_limits<int>::min();
  int innermost_end = std::numeric_limits<int>::max();
#endif
  for (int i = 0; i < NumberOfRangeEntries(); ++i) {
    int start_offset = GetRangeStart(i);
    int end_offset = GetRangeEnd(i);
    if (end_offset <= pc_offset) continue;
    if (start_offset > pc_offset) break;
    DCHECK_GE(start_offset, innermost_start);
    DCHECK_LT(end_offset, innermost_end);
    innermost_handler = i;
#ifdef DEBUG
    innermost_start = start_offset;
    innermost_end = end_offset;
#endif
  }
  return innermost_handler;
}
References DCHECK_GE, DCHECK_LT, GetRangeEnd(), GetRangeStart(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, kNoHandlerFound, and NumberOfRangeEntries().
Referenced by v8::internal::anonymous_namespace{deoptimizer.cc}::LookupCatchHandler(), v8::internal::UnoptimizedJSFrame::LookupExceptionHandlerInTable(), v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionFromBytecode(), v8::internal::Debug::PrepareStepOnThrow(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness().
LookupReturn()
int v8::internal::HandlerTable::LookupReturn (int pc_offset)
Definition at line 209 of file handler-table.cc.
                                            {
  // We only implement the methods needed by the standard libraries we care
  // about. This is not technically a full random access iterator by the spec.
  struct Iterator : base::iterator<std::random_access_iterator_tag, int> {
    Iterator(HandlerTable* tbl, int idx) : table(tbl), index(idx) {}
    value_type operator*() const { return table->GetReturnOffset(index); }
    bool operator!=(const Iterator& other) const { return !(*this == other); }
    bool operator==(const Iterator& other) const {
      return index == other.index;
    }
    // GLIBCXX_DEBUG checks uses the <= comparator.
    bool operator<=(const Iterator& other) { return index <= other.index; }
    Iterator& operator++() {
      index++;
      return *this;
    }
    Iterator& operator--() {
      index--;
      return *this;
    }
    Iterator& operator+=(difference_type offset) {
      index += offset;
      return *this;
    }
    difference_type operator-(const Iterator& other) const {
      return index - other.index;
    }
    HandlerTable* table;
    int index;
  };
  Iterator begin{this, 0}, end{this, NumberOfReturnEntries()};
  SLOW_DCHECK(std::is_sorted(begin, end)); // Must be sorted.
  Iterator result = std::lower_bound(begin, end, pc_offset);
  if (result != end && *result == pc_offset) {
    return GetReturnHandler(result.index);
  }
  return -1;
}
References v8::internal::compiler::begin(), v8::internal::compiler::end(), GetReturnHandler(), v8::internal::index, NumberOfReturnEntries(), v8::internal::operator!=(), v8::internal::operator++(), v8::base::internal::operator-(), v8::internal::operator--(), cppgc::internal::operator<=(), v8::internal::operator==(), v8::base::internal::result, SLOW_DCHECK, and v8::internal::wasm::value_type().
Referenced by v8::internal::StubFrame::LookupExceptionHandlerInTable(), v8::internal::OptimizedJSFrame::LookupExceptionHandlerInTable(), and v8::internal::Isolate::UnwindAndFindHandler().
MarkHandlerUsed()
void v8::internal::HandlerTable::MarkHandlerUsed (int index)
Definition at line 109 of file handler-table.cc.
                                            {
  DCHECK_EQ(kRangeBasedEncoding, mode_);
  DCHECK_LT(index, NumberOfRangeEntries());
  int offset = index * kRangeEntrySize + kRangeHandlerIndex;
  auto& mem = Memory<int32_t>(raw_encoded_data_ + offset * sizeof(int32_t));
  base::Relaxed_Store(&mem, HandlerWasUsedField::update(mem, true));
}
References DCHECK_EQ, DCHECK_LT, v8::internal::index, kRangeBasedEncoding, kRangeEntrySize, kRangeHandlerIndex, NumberOfRangeEntries(), raw_encoded_data_, v8::base::Relaxed_Store(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::anonymous_namespace{deoptimizer.cc}::LookupCatchHandler(), and v8::internal::UnoptimizedJSFrame::LookupExceptionHandlerInTable().
NumberOfRangeEntries()
int v8::internal::HandlerTable::NumberOfRangeEntries () const
Definition at line 175 of file handler-table.cc.
                                             {
  DCHECK_EQ(kRangeBasedEncoding, mode_);
  return number_of_entries_;
}
References DCHECK_EQ, kRangeBasedEncoding, and number_of_entries_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildMergeStates(), v8::internal::compiler::BytecodeGraphBuilder::ExitThenEnterExceptionHandlers(), v8::internal::baseline::BaselineCompiler::GenerateCode(), GetRangeData(), GetRangeEnd(), GetRangeHandlerBitfield(), GetRangeStart(), LookupHandlerIndexForRange(), MarkHandlerUsed(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
NumberOfReturnEntries()
int v8::internal::HandlerTable::NumberOfReturnEntries () const
Definition at line 180 of file handler-table.cc.
                                              {
  DCHECK_EQ(kReturnAddressBasedEncoding, mode_);
  return number_of_entries_;
}
References DCHECK_EQ, kReturnAddressBasedEncoding, and number_of_entries_.
Referenced by v8::internal::wasm::WasmCode::Disassemble(), GetReturnHandler(), GetReturnOffset(), v8::internal::OptimizedJSFrame::LookupExceptionHandlerInTable(), and LookupReturn().
SetRangeData()
void v8::internal::HandlerTable::SetRangeData (int index, int value)
Definition at line 151 of file handler-table.cc.
                                                    {
  int offset = index * kRangeEntrySize + kRangeDataIndex;
  Memory<int32_t>(raw_encoded_data_ + offset * sizeof(int32_t)) = value;
}
References v8::internal::index, kRangeDataIndex, kRangeEntrySize, raw_encoded_data_, and v8::internal::value.
Referenced by v8::internal::interpreter::HandlerTableBuilder::ToHandlerTable().
SetRangeEnd()
void v8::internal::HandlerTable::SetRangeEnd (int index, int value)
Definition at line 137 of file handler-table.cc.
                                                   {
  int offset = index * kRangeEntrySize + kRangeEndIndex;
  Memory<int32_t>(raw_encoded_data_ + offset * sizeof(int32_t)) = value;
}
References v8::internal::index, kRangeEndIndex, kRangeEntrySize, raw_encoded_data_, and v8::internal::value.
Referenced by v8::internal::interpreter::HandlerTableBuilder::ToHandlerTable().
SetRangeHandler()
void v8::internal::HandlerTable::SetRangeHandler (int index, int offset, CatchPrediction pred)
Definition at line 142 of file handler-table.cc.
                                                               {
  int value = HandlerOffsetField::encode(handler_offset) |
              HandlerWasUsedField::encode(false) |
              HandlerPredictionField::encode(prediction);
  int offset = index * kRangeEntrySize + kRangeHandlerIndex;
  Memory<int32_t>(raw_encoded_data_ + offset * sizeof(int32_t)) = value;
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::index, kRangeEntrySize, kRangeHandlerIndex, raw_encoded_data_, and v8::internal::value.
Referenced by v8::internal::interpreter::HandlerTableBuilder::ToHandlerTable().
SetRangeStart()
void v8::internal::HandlerTable::SetRangeStart (int index, int value)
Definition at line 132 of file handler-table.cc.
                                                     {
  int offset = index * kRangeEntrySize + kRangeStartIndex;
  Memory<int32_t>(raw_encoded_data_ + offset * sizeof(int32_t)) = value;
}
References v8::internal::index, kRangeEntrySize, kRangeStartIndex, raw_encoded_data_, and v8::internal::value.
Referenced by v8::internal::interpreter::HandlerTableBuilder::ToHandlerTable().
Member Data Documentation
kLazyDeopt
const int v8::internal::HandlerTable::kLazyDeopt = HandlerOffsetField::kMax [static]
Definition at line 154 of file handler-table.h.
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::maglev::MaglevCodeGenerator::EmitMetadata(), and v8::internal::OptimizedJSFrame::LookupExceptionHandlerInTable().
kNoHandlerFound
const int v8::internal::HandlerTable::kNoHandlerFound = -1 [static]
Definition at line 109 of file handler-table.h.
Referenced by v8::internal::anonymous_namespace{deoptimizer.cc}::LookupCatchHandler(), v8::internal::UnoptimizedJSFrame::LookupExceptionHandlerInTable(), LookupHandlerIndexForRange(), v8::internal::Debug::PrepareStepOnThrow(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness().
kRangeDataIndex
const int v8::internal::HandlerTable::kRangeDataIndex = 3 [static], [private]
Definition at line 140 of file handler-table.h.
Referenced by GetRangeData(), and SetRangeData().
kRangeEndIndex
const int v8::internal::HandlerTable::kRangeEndIndex = 1 [static], [private]
Definition at line 138 of file handler-table.h.
Referenced by GetRangeEnd(), and SetRangeEnd().
kRangeEntrySize
const int v8::internal::HandlerTable::kRangeEntrySize = 4 [static], [private]
Definition at line 141 of file handler-table.h.
Referenced by EntrySizeFromMode(), GetRangeData(), GetRangeEnd(), GetRangeHandlerBitfield(), GetRangeStart(), LengthForRange(), MarkHandlerUsed(), SetRangeData(), SetRangeEnd(), SetRangeHandler(), and SetRangeStart().
kRangeHandlerIndex
const int v8::internal::HandlerTable::kRangeHandlerIndex = 2 [static], [private]
Definition at line 139 of file handler-table.h.
Referenced by GetRangeHandlerBitfield(), MarkHandlerUsed(), and SetRangeHandler().
kRangeStartIndex
const int v8::internal::HandlerTable::kRangeStartIndex = 0 [static], [private]
Definition at line 137 of file handler-table.h.
Referenced by GetRangeStart(), and SetRangeStart().
kReturnEntrySize
const int v8::internal::HandlerTable::kReturnEntrySize = 2 [static], [private]
Definition at line 146 of file handler-table.h.
Referenced by EntrySizeFromMode(), GetReturnHandler(), GetReturnOffset(), and HandlerTable().
kReturnHandlerIndex
const int v8::internal::HandlerTable::kReturnHandlerIndex = 1 [static], [private]
Definition at line 145 of file handler-table.h.
Referenced by GetReturnHandler().
kReturnOffsetIndex
const int v8::internal::HandlerTable::kReturnOffsetIndex = 0 [static], [private]
Definition at line 144 of file handler-table.h.
Referenced by GetReturnOffset().
number_of_entries_
const int v8::internal::HandlerTable::number_of_entries_ [private]
Definition at line 121 of file handler-table.h.
Referenced by NumberOfRangeEntries(), and NumberOfReturnEntries().
raw_encoded_data_
const Address v8::internal::HandlerTable::raw_encoded_data_ [private]
Definition at line 133 of file handler-table.h.
Referenced by GetRangeData(), GetRangeEnd(), GetRangeHandlerBitfield(), GetRangeStart(), GetReturnHandler(), GetReturnOffset(), MarkHandlerUsed(), SetRangeData(), SetRangeEnd(), SetRangeHandler(), and SetRangeStart().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/handler-table.h
/mnt/V8SourceCode/src/codegen/handler-table.cc