v8::internal::ClosureFeedbackCellArray Class Reference
#include <feedback-vector.h>
Classes
class BodyDescriptor
Public Types
using Shape = ClosureFeedbackCellArrayShape
Static Public Member Functions
static V8_EXPORT_PRIVATE DirectHandle< ClosureFeedbackCellArray > New (Isolate *isolate, DirectHandle< SharedFunctionInfo > shared, AllocationType allocation=AllocationType::kYoung)
Private Types
using Super = TaggedArrayBase< ClosureFeedbackCellArray, ClosureFeedbackCellArrayShape >
Additional Inherited Members
Detailed Description
Definition at line 286 of file feedback-vector.h.
Member Typedef Documentation
Shape
using v8::internal::ClosureFeedbackCellArray::Shape = ClosureFeedbackCellArrayShape
Definition at line 293 of file feedback-vector.h.
Super
using v8::internal::ClosureFeedbackCellArray::Super = TaggedArrayBase<ClosureFeedbackCellArray, ClosureFeedbackCellArrayShape> [private]
Definition at line 289 of file feedback-vector.h.
Member Function Documentation
New()
DirectHandle< ClosureFeedbackCellArray > v8::internal::ClosureFeedbackCellArray::New (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared, AllocationType allocation = AllocationType::kYoung) [static]
Definition at line 217 of file feedback-vector.cc.
                               {
  int length = shared->feedback_metadata()->create_closure_slot_count();
  if (length == 0) {
    return isolate->factory()->empty_closure_feedback_cell_array();
  }
  // Pre-allocate the cells s.t. we can initialize `result` without further
  // allocation.
  DirectHandleVector<FeedbackCell> cells(isolate);
  cells.reserve(length);
  for (int i = 0; i < length; i++) {
    DirectHandle<FeedbackCell> cell = isolate->factory()->NewNoClosuresCell();
#ifdef V8_ENABLE_LEAPTIERING
    uint16_t parameter_count =
        shared->feedback_metadata()->GetCreateClosureParameterCount(i);
    auto initial_code = BUILTIN_CODE(isolate, CompileLazy);
    FeedbackCell::AllocateAndInstallJSDispatchHandle(
        cell, FeedbackCell::kDispatchHandleOffset, isolate, parameter_count,
        initial_code);
#endif
    cells.push_back(cell);
  }
  std::optional<DisallowGarbageCollection> no_gc;
  auto result = Allocate(isolate, length, &no_gc, allocation);
  for (int i = 0; i < length; i++) {
    result->set(i, *cells[i]);
  }
  return result;
}
References v8::internal::TaggedArrayBase< ClosureFeedbackCellArray, ClosureFeedbackCellArrayShape >::Allocate(), BUILTIN_CODE, v8::internal::wasm::CompileLazy(), v8::internal::Isolate::factory(), v8::internal::length, v8::internal::Factory::NewNoClosuresCell(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::DirectHandleVector< T >::push_back(), v8::internal::DirectHandleVector< T >::reserve(), and v8::base::internal::result.
Referenced by v8::internal::JSFunction::EnsureClosureFeedbackCellArray(), and v8::internal::FeedbackVector::NewForTesting().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/feedback-vector.h
/mnt/V8SourceCode/src/objects/feedback-vector.cc