v8::internal::torque::TypeBase Class Reference
#include <types.h>
Public Types
enum class Kind {
kTopType
, kAbstractType
, kBuiltinPointerType
, kUnionType
,
kBitFieldStructType
, kStructType
, kClassType
 }
Public Member Functions
virtual ~TypeBase ()=default
bool IsTopType () const
bool IsAbstractType () const
bool IsBuiltinPointerType () const
bool IsUnionType () const
bool IsBitFieldStructType () const
bool IsStructType () const
bool IsClassType () const
bool IsAggregateType () const
Protected Member Functions
TypeBase (Kind kind)
Kind kind () const
Private Attributes
const Kind kind_
Detailed Description
Definition at line 32 of file types.h.
Member Enumeration Documentation
Kind
enum v8::internal::torque::TypeBase::Kind [strong]
Enumerator
kTopType
kAbstractType
kBuiltinPointerType
kUnionType
kBitFieldStructType
kStructType
kClassType
Definition at line 34 of file types.h.
                  {
    kTopType,
    kAbstractType,
    kBuiltinPointerType,
    kUnionType,
    kBitFieldStructType,
    kStructType,
    kClassType
  };
Constructor & Destructor Documentation
 TypeBase()
virtual v8::internal::torque::TypeBase::~TypeBase () [virtual], [default]
TypeBase()
v8::internal::torque::TypeBase::TypeBase (Kind kind) [inline], [explicit], [protected]
Definition at line 58 of file types.h.
: kind_(kind) {}
Member Function Documentation
IsAbstractType()
bool v8::internal::torque::TypeBase::IsAbstractType () const [inline]
Definition at line 45 of file types.h.
{ return kind() == Kind::kAbstractType; }
References kAbstractType, and kind().
IsAggregateType()
bool v8::internal::torque::TypeBase::IsAggregateType () const [inline]
Definition at line 55 of file types.h.
{ return IsStructType() || IsClassType(); }
References IsClassType(), and IsStructType().
IsBitFieldStructType()
bool v8::internal::torque::TypeBase::IsBitFieldStructType () const [inline]
Definition at line 50 of file types.h.
                                    {
    return kind() == Kind::kBitFieldStructType;
  }
References kBitFieldStructType, and kind().
IsBuiltinPointerType()
bool v8::internal::torque::TypeBase::IsBuiltinPointerType () const [inline]
Definition at line 46 of file types.h.
                                    {
    return kind() == Kind::kBuiltinPointerType;
  }
References kBuiltinPointerType, and kind().
Referenced by v8::internal::torque::PushBuiltinPointerInstruction::PushBuiltinPointerInstruction().
IsClassType()
bool v8::internal::torque::TypeBase::IsClassType () const [inline]
Definition at line 54 of file types.h.
{ return kind() == Kind::kClassType; }
References kClassType, and kind().
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateFieldAccessors(), v8::internal::torque::AggregateType::GetHierarchy(), v8::internal::torque::ClassType::GetSuperClass(), IsAggregateType(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
IsStructType()
bool v8::internal::torque::TypeBase::IsStructType () const [inline]
Definition at line 53 of file types.h.
{ return kind() == Kind::kStructType; }
References kind(), and kStructType.
Referenced by v8::internal::torque::ClassType::GenerateAccessors(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateFieldAccessors(), and IsAggregateType().
IsTopType()
bool v8::internal::torque::TypeBase::IsTopType () const [inline]
Definition at line 44 of file types.h.
{ return kind() == Kind::kTopType; }
References kind(), and kTopType.
IsUnionType()
bool v8::internal::torque::TypeBase::IsUnionType () const [inline]
Definition at line 49 of file types.h.
{ return kind() == Kind::kUnionType; }
References kind(), and kUnionType.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::UnionType::InsertConstexprGeneratedTypeName(), and v8::internal::torque::UnionType::InsertGeneratedTNodeTypeName().
kind()
Kind v8::internal::torque::TypeBase::kind () const [inline], [protected]
Definition at line 59 of file types.h.
{ return kind_; }
References kind_.
Referenced by IsAbstractType(), IsBitFieldStructType(), IsBuiltinPointerType(), IsClassType(), IsStructType(), IsTopType(), and IsUnionType().
Member Data Documentation
kind_
const Kind v8::internal::torque::TypeBase::kind_ [private]
Definition at line 62 of file types.h.
Referenced by kind().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/types.h