cppgc::internal::SameThreadEnabledCheckingPolicyBase Class Reference
#include <pointer-policies.h>
Protected Member Functions
void CheckPointerImpl (const void *ptr, bool points_to_payload, bool check_off_heap_assignments)
Protected Attributes
const HeapBase * heap_ = nullptr
Detailed Description
Definition at line 121 of file pointer-policies.h.
Member Function Documentation
CheckPointerImpl()
void cppgc::internal::SameThreadEnabledCheckingPolicyBase::CheckPointerImpl (const void * ptr, bool points_to_payload, bool check_off_heap_assignments) [protected]
Definition at line 33 of file pointer-policies.cc.
                                                                              {
  // `ptr` must not reside on stack.
  DCHECK(!IsOnStack(ptr));
#if defined(CPPGC_CAGED_HEAP)
  // `ptr` must reside in the cage.
  DCHECK(CagedHeapBase::IsWithinCage(ptr));
#endif // defined(CPPGC_CAGED_HEAP)
  // Check for the most commonly used wrong sentinel value (-1).
  DCHECK_NE(reinterpret_cast<void*>(-1), ptr);
  auto* base_page = BasePage::FromPayload(ptr);
  // Large objects do not support mixins. This also means that `base_page` is
  // valid for large objects.
  DCHECK_IMPLIES(base_page->is_large(), points_to_payload);
  // References cannot change their heap association which means that state is
  // immutable once it is set.
  bool is_on_heap = true;
  if (!heap_) {
    heap_ = &base_page->heap();
    if (!heap_->page_backend()->Lookup(reinterpret_cast<Address>(this))) {
      // If `this` is not contained within the heap of `ptr`, we must deal with
      // an on-stack or off-heap reference. For both cases there should be no
      // heap registered.
      is_on_heap = false;
      CHECK(!HeapRegistry::TryFromManagedPointer(this));
    }
  }
  // Member references should never mix heaps.
  DCHECK_EQ(heap_, &base_page->heap());
  DCHECK(heap_->CurrentThreadIsHeapThread());
  // Header checks.
  const HeapObjectHeader* header = nullptr;
  if (points_to_payload) {
    // Unmask the alignment bits for the tagged pointer.
    const void* untagged = reinterpret_cast<const void*>(
        reinterpret_cast<uintptr_t>(ptr) & ~kAllocationMask);
    header = &HeapObjectHeader::FromObject(untagged);
    DCHECK_EQ(
        header,
        &base_page->ObjectHeaderFromInnerAddress<AccessMode::kAtomic>(ptr));
  } else {
    // Mixin case. Access the ObjectStartBitmap atomically since sweeping can be
    // in progress.
    header =
        &base_page->ObjectHeaderFromInnerAddress<AccessMode::kAtomic>(ptr);
    DCHECK_LE(header->ObjectStart(), ptr);
    DCHECK_GT(header->ObjectEnd<AccessMode::kAtomic>(), ptr);
  }
  if (header) {
    DCHECK(!header->IsFree());
  }
#ifdef CPPGC_VERIFY_HEAP
  if (check_off_heap_assignments || is_on_heap) {
    if (heap_->prefinalizer_handler()->IsInvokingPreFinalizers()) {
      // Slot can be in a large object.
      const auto* slot_page = BasePage::FromInnerAddress(heap_, this);
      // Off-heap slots (from other heaps or on-stack) are considered live.
      bool slot_is_live =
          !slot_page ||
          slot_page->ObjectHeaderFromInnerAddress(this).IsMarked();
      // During prefinalizers invocation, check that if the slot is live then
      // |ptr| refers to a live object.
      DCHECK_IMPLIES(slot_is_live, header->IsMarked());
      USE(slot_is_live);
    }
  }
#else
  USE(is_on_heap);
#endif // CPPGC_VERIFY_HEAP
}
References CHECK, cppgc::internal::HeapBase::CurrentThreadIsHeapThread(), DCHECK, DCHECK_EQ, DCHECK_GT, DCHECK_IMPLIES, DCHECK_LE, DCHECK_NE, cppgc::internal::BasePage::FromInnerAddress(), cppgc::internal::HeapObjectHeader::FromObject(), cppgc::internal::BasePage::FromPayload(), heap_, cppgc::internal::HeapObjectHeader::IsFree(), cppgc::internal::PreFinalizerHandler::IsInvokingPreFinalizers(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::kAllocationMask, cppgc::internal::kAtomic, cppgc::internal::PageBackend::Lookup(), cppgc::internal::HeapObjectHeader::ObjectEnd(), cppgc::internal::HeapObjectHeader::ObjectStart(), cppgc::internal::HeapBase::page_backend(), cppgc::internal::HeapBase::prefinalizer_handler(), cppgc::internal::HeapRegistry::TryFromManagedPointer(), and USE.
Referenced by cppgc::internal::SameThreadEnabledCheckingPolicy< kCheckOffHeapAssignments >::CheckPointersImplTrampoline< T, bool >::Call(), and cppgc::internal::SameThreadEnabledCheckingPolicy< kCheckOffHeapAssignments >::CheckPointersImplTrampoline< T, true >::Call().
Member Data Documentation
heap_
const HeapBase* cppgc::internal::SameThreadEnabledCheckingPolicyBase::heap_ = nullptr [protected]
Definition at line 126 of file pointer-policies.h.
Referenced by CheckPointerImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/internal/pointer-policies.h
/mnt/V8SourceCode/src/heap/cppgc/pointer-policies.cc