v8::ValueSerializer::Delegate Class Reference
#include <v8-value-serializer.h>
Public Member Functions
virtual ~Delegate ()=default
virtual void ThrowDataCloneError (Local< String > message)=0
Handles the case where a DataCloneError would be thrown in the structured clone spec.
virtual bool HasCustomHostObject (Isolate *isolate)
The embedder overrides this method to enable custom host object filter with Delegate::IsHostObject.
virtual Maybe< bool > IsHostObject (Isolate *isolate, Local< Object > object)
The embedder overrides this method to determine if an JS object is a host object and needs to be serialized by the host.
virtual Maybe< bool > WriteHostObject (Isolate *isolate, Local< Object > object)
The embedder overrides this method to write some kind of host object, if possible.
virtual Maybe< uint32_t > GetSharedArrayBufferId (Isolate *isolate, Local< SharedArrayBuffer > shared_array_buffer)
Called when the ValueSerializer is going to serialize a SharedArrayBuffer object.
virtual Maybe< uint32_t > GetWasmModuleTransferId (Isolate *isolate, Local< WasmModuleObject > module)
virtual bool AdoptSharedValueConveyor (Isolate *isolate, SharedValueConveyor &&conveyor)
Called when the first shared value is serialized.
virtual void * ReallocateBufferMemory (void *old_buffer, size_t size, size_t *actual_size)
Allocates memory for the buffer of at least the size provided.
virtual void FreeBufferMemory (void *buffer)
Frees a buffer allocated with |ReallocateBufferMemory|.
Detailed Description
Definition at line 67 of file v8-value-serializer.h.
Constructor & Destructor Documentation
 Delegate()
virtual v8::ValueSerializer::Delegate::~Delegate () [virtual], [default]
Member Function Documentation
AdoptSharedValueConveyor()
bool v8::ValueSerializer::Delegate::AdoptSharedValueConveyor (Isolate * isolate, SharedValueConveyor && conveyor) [virtual]
Called when the first shared value is serialized.
All subsequent shared values will use the same conveyor.
The embedder must ensure the lifetime of the conveyor matches the lifetime of the serialized data.
If the embedder supports serializing shared values, this method should return true. Otherwise the embedder should throw an exception and return false.
This method is called at most once per serializer.
Reimplemented in v8::Serializer.
Definition at line 3303 of file api.cc.
                                                         {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i_isolate->Throw(*i_isolate->factory()->NewError(
      i_isolate->error_function(), i::MessageTemplate::kDataCloneError,
      i_isolate->factory()->NewStringFromAsciiChecked("shared value")));
  return false;
}
References v8::internal::Isolate::factory(), v8::internal::Factory::NewError(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), and v8::internal::Isolate::Throw().
Referenced by v8::internal::ValueSerializer::WriteSharedObject().
FreeBufferMemory()
void v8::ValueSerializer::Delegate::FreeBufferMemory (void * buffer) [virtual]
Frees a buffer allocated with |ReallocateBufferMemory|.
The default implementation uses the stdlib's free() function.
Reimplemented in v8::Serializer.
Definition at line 3319 of file api.cc.
                                                           {
  return base::Free(buffer);
}
References v8::base::Free().
Referenced by v8::internal::ValueSerializer::~ValueSerializer().
GetSharedArrayBufferId()
Maybe< uint32_t > v8::ValueSerializer::Delegate::GetSharedArrayBufferId (Isolate * isolate, Local< SharedArrayBuffer > shared_array_buffer) [virtual]
Called when the ValueSerializer is going to serialize a SharedArrayBuffer object.
The embedder must return an ID for the object, using the same ID if this SharedArrayBuffer has already been serialized in this buffer. When deserializing, this ID will be passed to ValueDeserializer::GetSharedArrayBufferFromId as |clone_id|.
If the object cannot be serialized, an exception should be thrown and Nothing<uint32_t>() returned.
Reimplemented in v8::Serializer.
Definition at line 3289 of file api.cc.
                                                                       {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i_isolate->Throw(*i_isolate->factory()->NewError(
      i_isolate->error_function(), i::MessageTemplate::kDataCloneError,
      Utils::OpenDirectHandle(*shared_array_buffer)));
  return {};
}
References v8::internal::Isolate::factory(), v8::internal::Factory::NewError(), v8::Utils::OpenDirectHandle(), and v8::internal::Isolate::Throw().
Referenced by v8::internal::ValueSerializer::WriteJSArrayBuffer().
GetWasmModuleTransferId()
Maybe< uint32_t > v8::ValueSerializer::Delegate::GetWasmModuleTransferId (Isolate * isolate, Local< WasmModuleObject > module) [virtual]
Reimplemented in v8::Serializer.
Definition at line 3298 of file api.cc.
                                                         {
  return {};
}
HasCustomHostObject()
bool v8::ValueSerializer::Delegate::HasCustomHostObject (Isolate * isolate) [virtual]
The embedder overrides this method to enable custom host object filter with Delegate::IsHostObject.
This method is called at most once per serializer.
Definition at line 3277 of file api.cc.
                                                                     {
  return false;
}
Referenced by v8::internal::ValueSerializer::ValueSerializer().
IsHostObject()
Maybe< bool > v8::ValueSerializer::Delegate::IsHostObject (Isolate * isolate, Local< Object > object) [virtual]
The embedder overrides this method to determine if an JS object is a host object and needs to be serialized by the host.
Definition at line 3281 of file api.cc.
                                                                          {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  auto js_object = i::Cast<i::JSObject>(Utils::OpenDirectHandle(*object));
  return Just<bool>(
      i::JSObject::GetEmbedderFieldCount(js_object->map(i_isolate)));
}
References v8::internal::JSObject::GetEmbedderFieldCount(), and v8::Utils::OpenDirectHandle().
Referenced by v8::internal::ValueSerializer::IsHostObject().
ReallocateBufferMemory()
void * v8::ValueSerializer::Delegate::ReallocateBufferMemory (void * old_buffer, size_t size, size_t * actual_size) [virtual]
Allocates memory for the buffer of at least the size provided.
The actual size (which may be greater or equal) is written to |actual_size|. If no buffer has been allocated yet, nullptr will be provided.
If the memory cannot be allocated, nullptr should be returned. |actual_size| will be ignored. It is assumed that |old_buffer| is still valid in this case and has not been modified.
The default implementation uses the stdlib's realloc() function.
Reimplemented in v8::Serializer.
Definition at line 3312 of file api.cc.
                                                                             {
  *actual_size = size;
  return base::Realloc(old_buffer, size);
}
References v8::base::Realloc(), and size().
Referenced by v8::internal::ValueSerializer::ExpandBuffer().
ThrowDataCloneError()
virtual void v8::ValueSerializer::Delegate::ThrowDataCloneError (Local< String > message) [pure virtual]
Handles the case where a DataCloneError would be thrown in the structured clone spec.
Other V8 embedders may throw some other appropriate exception type.
Implemented in v8::Serializer.
Referenced by v8::internal::ValueSerializer::ThrowDataCloneError().
WriteHostObject()
Maybe< bool > v8::ValueSerializer::Delegate::WriteHostObject (Isolate * isolate, Local< Object > object) [virtual]
The embedder overrides this method to write some kind of host object, if possible.
If not, a suitable exception should be thrown and Nothing<bool>() returned.
Definition at line 3267 of file api.cc.
                                                                             {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  THROW_NEW_ERROR_RETURN_VALUE(
      i_isolate,
      NewError(i_isolate->error_function(), i::MessageTemplate::kDataCloneError,
               Utils::OpenDirectHandle(*object)),
      Nothing<bool>());
}
References v8::internal::anonymous_namespace{runtime-internal.cc}::NewError(), v8::Utils::OpenDirectHandle(), and THROW_NEW_ERROR_RETURN_VALUE.
Referenced by v8::internal::ValueSerializer::WriteHostObject().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-value-serializer.h
/mnt/V8SourceCode/src/api/api.cc