v8::internal::compiler::BytecodeLivenessMap Class Reference
#include <bytecode-liveness-map.h>
Public Member Functions
BytecodeLivenessMap (int bytecode_size, Zone *zone)
BytecodeLiveness & InsertNewLiveness (int offset)
BytecodeLiveness & GetLiveness (int offset)
const BytecodeLiveness & GetLiveness (int offset) const
BytecodeLivenessState * GetInLiveness (int offset)
const BytecodeLivenessState * GetInLiveness (int offset) const
BytecodeLivenessState * GetOutLiveness (int offset)
const BytecodeLivenessState * GetOutLiveness (int offset) const
Private Attributes
BytecodeLiveness * liveness_
Detailed Description
Definition at line 122 of file bytecode-liveness-map.h.
Constructor & Destructor Documentation
BytecodeLivenessMap()
v8::internal::compiler::BytecodeLivenessMap::BytecodeLivenessMap (int bytecode_size, Zone * zone) [inline]
Definition at line 124 of file bytecode-liveness-map.h.
      : liveness_(zone->AllocateArray<BytecodeLiveness>(bytecode_size))
#ifdef DEBUG
        ,
        size_(bytecode_size)
#endif
  {
  }
Member Function Documentation
GetInLiveness() [1/2]
BytecodeLivenessState* v8::internal::compiler::BytecodeLivenessMap::GetInLiveness (int offset) [inline]
Definition at line 157 of file bytecode-liveness-map.h.
                                                   {
    return GetLiveness(offset).in;
  }
Referenced by v8::internal::compiler::BytecodeAnalysis::GetInLivenessFor(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness().
GetInLiveness() [2/2]
const BytecodeLivenessState* v8::internal::compiler::BytecodeLivenessMap::GetInLiveness (int offset) const [inline]
Definition at line 160 of file bytecode-liveness-map.h.
                                                               {
    return GetLiveness(offset).in;
  }
GetLiveness() [1/2]
BytecodeLiveness& v8::internal::compiler::BytecodeLivenessMap::GetLiveness (int offset) [inline]
Definition at line 146 of file bytecode-liveness-map.h.
                                            {
    DCHECK_GE(offset, 0);
    DCHECK_LT(offset, size_);
    return liveness_[offset];
  }
References DCHECK_GE, and DCHECK_LT.
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
GetLiveness() [2/2]
const BytecodeLiveness& v8::internal::compiler::BytecodeLivenessMap::GetLiveness (int offset) const [inline]
Definition at line 151 of file bytecode-liveness-map.h.
                                                        {
    DCHECK_GE(offset, 0);
    DCHECK_LT(offset, size_);
    return liveness_[offset];
  }
References DCHECK_GE, and DCHECK_LT.
GetOutLiveness() [1/2]
BytecodeLivenessState* v8::internal::compiler::BytecodeLivenessMap::GetOutLiveness (int offset) [inline]
Definition at line 164 of file bytecode-liveness-map.h.
                                                    {
    return GetLiveness(offset).out;
  }
Referenced by v8::internal::compiler::BytecodeAnalysis::GetOutLivenessFor().
GetOutLiveness() [2/2]
const BytecodeLivenessState* v8::internal::compiler::BytecodeLivenessMap::GetOutLiveness (int offset) const [inline]
Definition at line 167 of file bytecode-liveness-map.h.
                                                                {
    return GetLiveness(offset).out;
  }
InsertNewLiveness()
BytecodeLiveness& v8::internal::compiler::BytecodeLivenessMap::InsertNewLiveness (int offset) [inline]
Definition at line 133 of file bytecode-liveness-map.h.
                                                  {
    DCHECK_GE(offset, 0);
    DCHECK_LT(offset, size_);
#ifdef DEBUG
    // Null out the in/out liveness, so that later DCHECKs know whether these
    // have been correctly initialised or not. That code does initialise them
    // unconditionally though, so we can skip the nulling out in release.
    liveness_[offset].in = nullptr;
    liveness_[offset].out = nullptr;
#endif
    return liveness_[offset];
  }
References DCHECK_GE, and DCHECK_LT.
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
Member Data Documentation
liveness_
BytecodeLiveness* v8::internal::compiler::BytecodeLivenessMap::liveness_ [private]
Definition at line 172 of file bytecode-liveness-map.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/bytecode-liveness-map.h