v8::internal::torque::KytheData Class Reference
#include <kythe-data.h>
Public Member Functions
KytheData ()=default
Static Public Member Functions
static void SetConsumer (KytheConsumer *consumer)
static V8_EXPORT_PRIVATE kythe_entity_t AddConstantDefinition (const Value *constant)
static V8_EXPORT_PRIVATE void AddConstantUse (SourcePosition use_position, const Value *constant)
static V8_EXPORT_PRIVATE kythe_entity_t AddFunctionDefinition (Callable *callable)
static V8_EXPORT_PRIVATE void AddCall (Callable *caller, SourcePosition call_position, Callable *callee)
static V8_EXPORT_PRIVATE kythe_entity_t AddClassFieldDefinition (const Field *field)
static V8_EXPORT_PRIVATE void AddClassFieldUse (SourcePosition use_position, const Field *field)
static V8_EXPORT_PRIVATE kythe_entity_t AddBindingDefinition (Binding< LocalValue > *binding)
static V8_EXPORT_PRIVATE kythe_entity_t AddBindingDefinition (Binding< LocalLabel > *binding)
static V8_EXPORT_PRIVATE void AddBindingUse (SourcePosition use_position, Binding< LocalValue > *binding)
static V8_EXPORT_PRIVATE void AddBindingUse (SourcePosition use_position, Binding< LocalLabel > *binding)
static V8_EXPORT_PRIVATE kythe_entity_t AddTypeDefinition (const Declarable *type_decl)
static V8_EXPORT_PRIVATE void AddTypeUse (SourcePosition use_position, const Declarable *type_decl)
Static Private Member Functions
static kythe_entity_t AddBindingDefinitionImpl (uint64_t binding_index, const std::string &name, const SourcePosition &ident_pos)
Private Attributes
KytheConsumer * consumer_
std::unordered_map< const Value *, kythe_entity_t > constants_
std::unordered_map< Callable *, kythe_entity_t > callables_
std::unordered_map< const Field *, std::set< SourcePosition > > field_uses_
std::unordered_map< uint64_t, kythe_entity_t > local_bindings_
std::unordered_map< const Declarable *, kythe_entity_t > types_
std::unordered_map< const Field *, kythe_entity_t > class_fields_
Additional Inherited Members
Detailed Description
Definition at line 49 of file kythe-data.h.
Constructor & Destructor Documentation
KytheData()
v8::internal::torque::KytheData::KytheData () [default]
Member Function Documentation
AddBindingDefinition() [1/2]
kythe_entity_t v8::internal::torque::KytheData::AddBindingDefinition (Binding< LocalLabel > * binding) [static]
Definition at line 117 of file kythe-data.cc.
                                                                           {
  CHECK(binding);
  const uint64_t binding_index = binding->unique_index();
  return AddBindingDefinitionImpl(binding_index, binding->name(),
                                  binding->declaration_position());
}
References AddBindingDefinitionImpl(), CHECK, v8::internal::torque::Binding< T >::declaration_position(), v8::internal::torque::Binding< T >::name(), and v8::internal::torque::Binding< T >::unique_index().
AddBindingDefinition() [2/2]
kythe_entity_t v8::internal::torque::KytheData::AddBindingDefinition (Binding< LocalValue > * binding) [static]
Definition at line 110 of file kythe-data.cc.
                                                                           {
  CHECK(binding);
  const uint64_t binding_index = binding->unique_index();
  return AddBindingDefinitionImpl(binding_index, binding->name(),
                                  binding->declaration_position());
}
References AddBindingDefinitionImpl(), CHECK, v8::internal::torque::Binding< T >::declaration_position(), v8::internal::torque::Binding< T >::name(), and v8::internal::torque::Binding< T >::unique_index().
Referenced by AddBindingUse(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::AddParameter(), and v8::internal::torque::ImplementationVisitor::InlineMacro().
AddBindingDefinitionImpl()
kythe_entity_t v8::internal::torque::KytheData::AddBindingDefinitionImpl (uint64_t binding_index, const std::string & name, const SourcePosition & ident_pos) [static], [private]
Definition at line 124 of file kythe-data.cc.
                                     {
  KytheData* that = &KytheData::Get();
  // Check if we know the binding already.
  auto it = that->local_bindings_.find(binding_index);
  if (it != that->local_bindings_.end()) return it->second;
  // Register this binding.
  kythe_entity_t binding_id = that->consumer_->AddDefinition(
      KytheConsumer::Kind::Variable, name, MakeKythePosition(ident_pos));
  that->local_bindings_.insert(it, std::make_pair(binding_index, binding_id));
  return binding_id;
}
References v8::internal::torque::KytheConsumer::AddDefinition(), consumer_, v8::base::ContextualVariable< Derived, VarType >::Get(), local_bindings_, v8::internal::torque::anonymous_namespace{kythe-data.cc}::MakeKythePosition(), v8::internal::name, and v8::internal::torque::KytheConsumer::Variable.
Referenced by AddBindingDefinition().
AddBindingUse() [1/2]
void v8::internal::torque::KytheData::AddBindingUse (SourcePosition use_position, Binding< LocalLabel > * binding) [static]
Definition at line 148 of file kythe-data.cc.
                                                            {
  CHECK(binding);
  KytheData* that = &KytheData::Get();
  kythe_entity_t binding_id = AddBindingDefinition(binding);
  KythePosition use_pos = MakeKythePosition(use_position);
  that->consumer_->AddUse(KytheConsumer::Kind::Variable, binding_id, use_pos);
}
References AddBindingDefinition(), v8::internal::torque::KytheConsumer::AddUse(), CHECK, consumer_, v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::torque::anonymous_namespace{kythe-data.cc}::MakeKythePosition(), and v8::internal::torque::KytheConsumer::Variable.
AddBindingUse() [2/2]
void v8::internal::torque::KytheData::AddBindingUse (SourcePosition use_position, Binding< LocalValue > * binding) [static]
Definition at line 138 of file kythe-data.cc.
                                                            {
  CHECK(binding);
  KytheData* that = &KytheData::Get();
  kythe_entity_t binding_id = AddBindingDefinition(binding);
  KythePosition use_pos = MakeKythePosition(use_position);
  that->consumer_->AddUse(KytheConsumer::Kind::Variable, binding_id, use_pos);
}
References AddBindingDefinition(), v8::internal::torque::KytheConsumer::AddUse(), CHECK, consumer_, v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::torque::anonymous_namespace{kythe-data.cc}::MakeKythePosition(), and v8::internal::torque::KytheConsumer::Variable.
Referenced by v8::internal::torque::ImplementationVisitor::GetLocationReference(), and v8::internal::torque::ImplementationVisitor::Visit().
AddCall()
void v8::internal::torque::KytheData::AddCall (Callable * caller, SourcePosition call_position, Callable * callee) [static]
Definition at line 68 of file kythe-data.cc.
                                          {
  if (!caller) return; // Ignore those for now.
  DCHECK_NOT_NULL(caller);
  DCHECK_NOT_NULL(callee);
  KytheData* that = &Get();
  if (call_position.source.IsValid()) {
    kythe_entity_t caller_id = AddFunctionDefinition(caller);
    kythe_entity_t callee_id = AddFunctionDefinition(callee);
    KythePosition call_pos = MakeKythePosition(call_position);
    that->consumer_->AddCall(KytheConsumer::Kind::Function, caller_id, call_pos,
                             callee_id);
  }
}
References v8::internal::torque::KytheConsumer::AddCall(), AddFunctionDefinition(), consumer_, DCHECK_NOT_NULL, v8::internal::torque::KytheConsumer::Function, v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::torque::SourceId::IsValid(), v8::internal::torque::anonymous_namespace{kythe-data.cc}::MakeKythePosition(), and v8::internal::torque::SourcePosition::source.
AddClassFieldDefinition()
kythe_entity_t v8::internal::torque::KytheData::AddClassFieldDefinition (const Field * field) [static]
Definition at line 85 of file kythe-data.cc.
                                                                    {
  DCHECK(field);
  KytheData* that = &KytheData::Get();
  // Check if we know that field already.
  auto it = that->class_fields_.find(field);
  if (it != that->class_fields_.end()) return it->second;
  // Register this field.
  KythePosition pos = MakeKythePosition(field->pos);
  kythe_entity_t field_id = that->consumer_->AddDefinition(
      KytheConsumer::Kind::ClassField, field->name_and_type.name, pos);
  that->class_fields_.insert(it, std::make_pair(field, field_id));
  return field_id;
}
References v8::internal::torque::KytheConsumer::AddDefinition(), class_fields_, v8::internal::torque::KytheConsumer::ClassField, consumer_, v8::internal::DCHECK(), v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::torque::anonymous_namespace{kythe-data.cc}::MakeKythePosition(), v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, and v8::internal::torque::Field::pos.
Referenced by AddClassFieldUse().
AddClassFieldUse()
void v8::internal::torque::KytheData::AddClassFieldUse (SourcePosition use_position, const Field * field) [static]
Definition at line 99 of file kythe-data.cc.
                                                     {
  DCHECK(field);
  KytheData* that = &KytheData::Get();
  kythe_entity_t field_id = AddClassFieldDefinition(field);
  KythePosition use_pos = MakeKythePosition(use_position);
  that->consumer_->AddUse(KytheConsumer::Kind::ClassField, field_id, use_pos);
}
References AddClassFieldDefinition(), v8::internal::torque::KytheConsumer::AddUse(), v8::internal::torque::KytheConsumer::ClassField, consumer_, v8::internal::DCHECK(), v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::torque::anonymous_namespace{kythe-data.cc}::MakeKythePosition().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFieldAccess().
AddConstantDefinition()
kythe_entity_t v8::internal::torque::KytheData::AddConstantDefinition (const Value * constant) [static]
Definition at line 28 of file kythe-data.cc.
                                                                     {
  DCHECK(constant->IsNamespaceConstant() || constant->IsExternConstant());
  KytheData* that = &KytheData::Get();
  // Check if we know the constant already.
  auto it = that->constants_.find(constant);
  if (it != that->constants_.end()) return it->second;
  // Register this constant.
  KythePosition pos = MakeKythePosition(constant->name()->pos);
  kythe_entity_t constant_id = that->consumer_->AddDefinition(
      KytheConsumer::Kind::Constant, constant->name()->value, pos);
  that->constants_.insert(it, std::make_pair(constant, constant_id));
  return constant_id;
}
References v8::internal::torque::KytheConsumer::AddDefinition(), v8::internal::torque::KytheConsumer::Constant, constants_, consumer_, v8::internal::DCHECK(), v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::torque::Declarable::IsExternConstant(), v8::internal::torque::Declarable::IsNamespaceConstant(), v8::internal::torque::anonymous_namespace{kythe-data.cc}::MakeKythePosition(), v8::internal::torque::Value::name(), v8::internal::torque::AstNode::pos, and v8::internal::torque::Identifier::value.
Referenced by AddConstantUse(), and v8::internal::torque::DeclarationVisitor::Visit().
AddConstantUse()
void v8::internal::torque::KytheData::AddConstantUse (SourcePosition use_position, const Value * constant) [static]
Definition at line 43 of file kythe-data.cc.
                                                      {
  DCHECK(constant->IsNamespaceConstant() || constant->IsExternConstant());
  KytheData* that = &Get();
  kythe_entity_t constant_id = AddConstantDefinition(constant);
  KythePosition use_pos = MakeKythePosition(use_position);
  that->consumer_->AddUse(KytheConsumer::Kind::Constant, constant_id, use_pos);
}
References AddConstantDefinition(), v8::internal::torque::KytheConsumer::AddUse(), v8::internal::torque::KytheConsumer::Constant, consumer_, v8::internal::DCHECK(), v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::torque::Declarable::IsExternConstant(), v8::internal::torque::Declarable::IsNamespaceConstant(), and v8::internal::torque::anonymous_namespace{kythe-data.cc}::MakeKythePosition().
Referenced by v8::internal::torque::ImplementationVisitor::GetLocationReference().
AddFunctionDefinition()
kythe_entity_t v8::internal::torque::KytheData::AddFunctionDefinition (Callable * callable) [static]
Definition at line 53 of file kythe-data.cc.
                                                                  {
  KytheData* that = &KytheData::Get();
  // Check if we know the caller already.
  auto it = that->callables_.find(callable);
  if (it != that->callables_.end()) return it->second;
  // Register this callable.
  auto ident_pos = callable->IdentifierPosition();
  kythe_entity_t callable_id = that->consumer_->AddDefinition(
      KytheConsumer::Kind::Function, callable->ExternalName(),
      MakeKythePosition(ident_pos));
  that->callables_.insert(it, std::make_pair(callable, callable_id));
  return callable_id;
}
References v8::internal::torque::KytheConsumer::AddDefinition(), callables_, consumer_, v8::internal::torque::Callable::ExternalName(), v8::internal::torque::KytheConsumer::Function, v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::torque::Declarable::IdentifierPosition(), and v8::internal::torque::anonymous_namespace{kythe-data.cc}::MakeKythePosition().
Referenced by AddCall(), and v8::internal::torque::DeclarationVisitor::Visit().
AddTypeDefinition()
kythe_entity_t v8::internal::torque::KytheData::AddTypeDefinition (const Declarable * type_decl) [static]
Definition at line 159 of file kythe-data.cc.
                                                                       {
  CHECK(type_decl);
  KytheData* that = &KytheData::Get();
  // Check if we know that type already.
  auto it = that->types_.find(type_decl);
  if (it != that->types_.end()) return it->second;
  // Register this type.
  KythePosition pos = MakeKythePosition(type_decl->IdentifierPosition());
  kythe_entity_t type_id = that->consumer_->AddDefinition(
      KytheConsumer::Kind::Type, type_decl->type_name(), pos);
  that->types_.insert(it, std::make_pair(type_decl, type_id));
  return type_id;
}
References v8::internal::torque::KytheConsumer::AddDefinition(), CHECK, consumer_, v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::torque::Declarable::IdentifierPosition(), v8::internal::torque::anonymous_namespace{kythe-data.cc}::MakeKythePosition(), v8::internal::torque::KytheConsumer::Type, v8::internal::torque::Declarable::type_name(), and types_.
Referenced by AddTypeUse(), and v8::internal::torque::PredeclarationVisitor::Predeclare().
AddTypeUse()
void v8::internal::torque::KytheData::AddTypeUse (SourcePosition use_position, const Declarable * type_decl) [static]
Definition at line 173 of file kythe-data.cc.
                                                        {
  CHECK(type_decl);
  KytheData* that = &KytheData::Get();
  kythe_entity_t type_id = AddTypeDefinition(type_decl);
  KythePosition use_pos = MakeKythePosition(use_position);
  that->consumer_->AddUse(KytheConsumer::Kind::Type, type_id, use_pos);
}
References AddTypeDefinition(), v8::internal::torque::KytheConsumer::AddUse(), CHECK, consumer_, v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::torque::anonymous_namespace{kythe-data.cc}::MakeKythePosition(), and v8::internal::torque::KytheConsumer::Type.
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
SetConsumer()
static void v8::internal::torque::KytheData::SetConsumer (KytheConsumer * consumer) [inline], [static]
Definition at line 53 of file kythe-data.h.
                                                   {
    Get().consumer_ = consumer;
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Member Data Documentation
callables_
std::unordered_map<Callable*, kythe_entity_t> v8::internal::torque::KytheData::callables_ [private]
Definition at line 96 of file kythe-data.h.
Referenced by AddFunctionDefinition().
class_fields_
std::unordered_map<const Field*, kythe_entity_t> v8::internal::torque::KytheData::class_fields_ [private]
Definition at line 101 of file kythe-data.h.
Referenced by AddClassFieldDefinition().
constants_
std::unordered_map<const Value*, kythe_entity_t> v8::internal::torque::KytheData::constants_ [private]
Definition at line 95 of file kythe-data.h.
Referenced by AddConstantDefinition().
consumer_
KytheConsumer* v8::internal::torque::KytheData::consumer_ [private]
Definition at line 94 of file kythe-data.h.
Referenced by AddBindingDefinitionImpl(), AddBindingUse(), AddCall(), AddClassFieldDefinition(), AddClassFieldUse(), AddConstantDefinition(), AddConstantUse(), AddFunctionDefinition(), AddTypeDefinition(), and AddTypeUse().
field_uses_
std::unordered_map<const Field*, std::set<SourcePosition> > v8::internal::torque::KytheData::field_uses_ [private]
Definition at line 98 of file kythe-data.h.
local_bindings_
std::unordered_map<uint64_t, kythe_entity_t> v8::internal::torque::KytheData::local_bindings_ [private]
Definition at line 99 of file kythe-data.h.
Referenced by AddBindingDefinitionImpl().
types_
std::unordered_map<const Declarable*, kythe_entity_t> v8::internal::torque::KytheData::types_ [private]
Definition at line 100 of file kythe-data.h.
Referenced by AddTypeDefinition().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/kythe-data.h
/mnt/V8SourceCode/src/torque/kythe-data.cc