v8::internal::JSRawJson Class Reference
#include <js-raw-json.h>
Public Member Functions
bool HasInitialLayout (Isolate *isolate) const
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSRawJson > Create (Isolate *isolate, Handle< Object > text)
Static Public Attributes
static const int kRawJsonInitialIndex = 0
Detailed Description
Definition at line 18 of file js-raw-json.h.
Member Function Documentation
Create()
MaybeDirectHandle< JSRawJson > v8::internal::JSRawJson::Create (Isolate * isolate, Handle< Object > text) [static]
Definition at line 17 of file js-raw-json.cc.
                                                                    {
  Handle<String> json_string;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, json_string,
                             Object::ToString(isolate, text));
  Handle<String> flat = String::Flatten(isolate, json_string);
  if (String::IsOneByteRepresentationUnderneath(*flat)) {
    if (!JsonParser<uint8_t>::CheckRawJson(isolate, flat)) {
      DCHECK(isolate->has_exception());
      return MaybeDirectHandle<JSRawJson>();
    }
  } else {
    if (!JsonParser<uint16_t>::CheckRawJson(isolate, flat)) {
      DCHECK(isolate->has_exception());
      return MaybeDirectHandle<JSRawJson>();
    }
  }
  DirectHandle<JSObject> result =
      isolate->factory()->NewJSObjectFromMap(isolate->js_raw_json_map());
  result->InObjectPropertyAtPut(JSRawJson::kRawJsonInitialIndex, *flat);
  JSObject::SetIntegrityLevel(isolate, result, FROZEN, kThrowOnError).Check();
  return Cast<JSRawJson>(result);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::FROZEN, v8::internal::Isolate::has_exception(), v8::internal::String::IsOneByteRepresentationUnderneath(), kRawJsonInitialIndex, v8::internal::kThrowOnError, v8::internal::Factory::NewJSObjectFromMap(), v8::base::internal::result, and v8::Value::ToString().
Referenced by v8::internal::BUILTIN().
HasInitialLayout()
bool v8::internal::JSRawJson::HasInitialLayout (Isolate * isolate) const [inline]
Definition at line 23 of file js-raw-json-inl.h.
                                                       {
  return map() == *isolate->js_raw_json_map();
}
Member Data Documentation
kRawJsonInitialIndex
const int v8::internal::JSRawJson::kRawJsonInitialIndex = 0 [static]
Definition at line 29 of file js-raw-json.h.
Referenced by Create(), v8::internal::Genesis::InitializeGlobal(), and v8::internal::JsonStringifier::Serialize_().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-raw-json.h
/mnt/V8SourceCode/src/objects/js-raw-json-inl.h
/mnt/V8SourceCode/src/objects/js-raw-json.cc