v8::internal::compiler::FastApiCallNode Class Reference
#include <simplified-operator.h>
Public Member Functions
FastApiCallNode (Node *node)
const FastApiCallParameters & Parameters () const
constexpr int CallbackDataIndex () const
TNode< Object > CallbackData () const
constexpr int ContextIndex () const
TNode< Object > Context () const
constexpr int FrameStateIndex () const
constexpr int CArgumentCount () const
constexpr int FastCallArgumentCount () const
constexpr int SlowCallArgumentCount () const
constexpr int FirstFastCallArgumentIndex () const
constexpr int FastCallArgumentIndex (int i) const
TNode< Object > FastCallArgument (int i) const
constexpr int FirstSlowCallArgumentIndex () const
constexpr int SlowCallArgumentIndex (int i) const
TNode< Object > SlowCallArgument (int i) const
Static Public Member Functions
static constexpr int ArityForArgc (int c_arg_count, int slow_arg_count)
Static Public Attributes
static constexpr int kCallbackData = 1
static constexpr int kSlowCodeTarget = 1
static constexpr int kFrameState = 1
Static Private Member Functions
static int FastCallArgumentCount (Node *node)
static int SlowCallArgumentCount (Node *node)
Private Attributes
const int c_arg_count_
const int slow_arg_count_
Additional Inherited Members
Detailed Description
Definition at line 1317 of file simplified-operator.h.
Constructor & Destructor Documentation
FastApiCallNode()
v8::internal::compiler::FastApiCallNode::FastApiCallNode (Node * node) [inline], [explicit]
Definition at line 1319 of file simplified-operator.h.
      : SimplifiedNodeWrapperBase(node),
        c_arg_count_(FastCallArgumentCount(node)),
        slow_arg_count_(SlowCallArgumentCount(node)) {
    DCHECK_EQ(IrOpcode::kFastApiCall, node->opcode());
  }
References DCHECK_EQ, and v8::internal::compiler::Node::opcode().
Member Function Documentation
ArityForArgc()
static constexpr int v8::internal::compiler::FastApiCallNode::ArityForArgc (int c_arg_count, int slow_arg_count) [inline], [static], [constexpr]
Definition at line 1382 of file simplified-operator.h.
                                                                         {
    return c_arg_count + kCallbackData + kSlowCodeTarget + slow_arg_count +
           kFrameState;
  }
Referenced by v8::internal::compiler::SimplifiedOperatorBuilder::FastApiCall(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), and v8::internal::compiler::RepresentationSelector::VisitFastApiCall().
CallbackData()
TNode<Object> v8::internal::compiler::FastApiCallNode::CallbackData () const [inline]
Definition at line 1339 of file simplified-operator.h.
                                     {
    return TNode<Object>::UncheckedCast(
        NodeProperties::GetValueInput(node(), CallbackDataIndex()));
  }
References v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
CallbackDataIndex()
constexpr int v8::internal::compiler::FastApiCallNode::CallbackDataIndex () const [inline], [constexpr]
Definition at line 1335 of file simplified-operator.h.
                                          {
    // The last fast argument is the callback data.
    return FastCallArgumentCount() - 1;
  }
Referenced by v8::internal::compiler::RepresentationSelector::VisitFastApiCall().
CArgumentCount()
constexpr int v8::internal::compiler::FastApiCallNode::CArgumentCount () const [inline], [constexpr]
Definition at line 1387 of file simplified-operator.h.
{ return c_arg_count_; }
Context()
TNode<Object> v8::internal::compiler::FastApiCallNode::Context () const [inline]
Definition at line 1350 of file simplified-operator.h.
                                {
    return TNode<Object>::UncheckedCast(
        NodeProperties::GetValueInput(node(), ContextIndex()));
  }
References v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
ContextIndex()
constexpr int v8::internal::compiler::FastApiCallNode::ContextIndex () const [inline], [constexpr]
Definition at line 1345 of file simplified-operator.h.
                                     {
    // The last slow call argument is the frame state, the one before is the
    // context.
    return SlowCallArgumentIndex(SlowCallArgumentCount() - kFrameState - 1);
  }
FastCallArgument()
TNode<Object> v8::internal::compiler::FastApiCallNode::FastCallArgument (int i) const [inline]
Definition at line 1400 of file simplified-operator.h.
                                              {
    DCHECK_LT(i, FastCallArgumentCount());
    return TNode<Object>::UncheckedCast(
        NodeProperties::GetValueInput(node(), FastCallArgumentIndex(i)));
  }
References DCHECK_LT, and v8::internal::TNode< T >::UncheckedCast().
FastCallArgumentCount() [1/2]
constexpr int v8::internal::compiler::FastApiCallNode::FastCallArgumentCount () const [inline], [constexpr]
Definition at line 1389 of file simplified-operator.h.
                                              {
    return CArgumentCount() + kCallbackData;
  }
FastCallArgumentCount() [2/2]
int v8::internal::compiler::FastApiCallNode::FastCallArgumentCount (Node * node) [static], [private]
Definition at line 2538 of file simplified-operator.cc.
                                                     {
  FastApiCallParameters p = FastApiCallParametersOf(node->op());
  const CFunctionInfo* signature = p.c_function().signature;
  CHECK_NOT_NULL(signature);
  return signature->ArgumentCount();
}
References v8::CFunctionInfo::ArgumentCount(), v8::internal::compiler::FastApiCallParameters::c_function(), CHECK_NOT_NULL, v8::internal::compiler::FastApiCallParametersOf(), v8::internal::compiler::NodeWrapper::node(), v8::internal::compiler::Node::op(), and v8::internal::compiler::FastApiCallFunction::signature.
FastCallArgumentIndex()
constexpr int v8::internal::compiler::FastApiCallNode::FastCallArgumentIndex (int i) const [inline], [constexpr]
Definition at line 1397 of file simplified-operator.h.
                                                   {
    return FirstFastCallArgumentIndex() + i;
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
FirstFastCallArgumentIndex()
constexpr int v8::internal::compiler::FastApiCallNode::FirstFastCallArgumentIndex () const [inline], [constexpr]
Definition at line 1394 of file simplified-operator.h.
                                                   {
    return ReceiverIndex() + 1;
  }
FirstSlowCallArgumentIndex()
constexpr int v8::internal::compiler::FastApiCallNode::FirstSlowCallArgumentIndex () const [inline], [constexpr]
Definition at line 1406 of file simplified-operator.h.
                                                   {
    return FastCallArgumentCount();
  }
FrameStateIndex()
constexpr int v8::internal::compiler::FastApiCallNode::FrameStateIndex () const [inline], [constexpr]
Definition at line 1356 of file simplified-operator.h.
                                        {
    // The last slow call argument is the frame state.
    return SlowCallArgumentIndex(SlowCallArgumentCount() - 1);
  }
Referenced by v8::internal::compiler::RepresentationSelector::VisitFastApiCall().
Parameters()
const FastApiCallParameters& v8::internal::compiler::FastApiCallNode::Parameters () const [inline]
Definition at line 1326 of file simplified-operator.h.
                                                  {
    return FastApiCallParametersOf(node()->op());
  }
References v8::internal::compiler::FastApiCallParametersOf().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
SlowCallArgument()
TNode<Object> v8::internal::compiler::FastApiCallNode::SlowCallArgument (int i) const [inline]
Definition at line 1412 of file simplified-operator.h.
                                              {
    DCHECK_LT(i, SlowCallArgumentCount());
    return TNode<Object>::UncheckedCast(
        NodeProperties::GetValueInput(node(), SlowCallArgumentIndex(i)));
  }
References DCHECK_LT, and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
SlowCallArgumentCount() [1/2]
constexpr int v8::internal::compiler::FastApiCallNode::SlowCallArgumentCount () const [inline], [constexpr]
Definition at line 1392 of file simplified-operator.h.
{ return slow_arg_count_; }
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
SlowCallArgumentCount() [2/2]
int v8::internal::compiler::FastApiCallNode::SlowCallArgumentCount (Node * node) [static], [private]
Definition at line 2546 of file simplified-operator.cc.
                                                     {
  FastApiCallParameters p = FastApiCallParametersOf(node->op());
  CallDescriptor* descriptor = p.descriptor();
  CHECK_NOT_NULL(descriptor);
  return kSlowCodeTarget + static_cast<int>(descriptor->ParameterCount()) +
         kFrameState;
}
References CHECK_NOT_NULL, v8::internal::compiler::FastApiCallParameters::descriptor(), v8::internal::compiler::FastApiCallParametersOf(), kFrameState, kSlowCodeTarget, v8::internal::compiler::NodeWrapper::node(), v8::internal::compiler::Node::op(), and v8::internal::compiler::CallDescriptor::ParameterCount().
SlowCallArgumentIndex()
constexpr int v8::internal::compiler::FastApiCallNode::SlowCallArgumentIndex (int i) const [inline], [constexpr]
Definition at line 1409 of file simplified-operator.h.
                                                   {
    return FirstSlowCallArgumentIndex() + i;
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Member Data Documentation
c_arg_count_
const int v8::internal::compiler::FastApiCallNode::c_arg_count_ [private]
Definition at line 1422 of file simplified-operator.h.
kCallbackData
constexpr int v8::internal::compiler::FastApiCallNode::kCallbackData = 1 [static], [constexpr]
Definition at line 1367 of file simplified-operator.h.
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
kFrameState
constexpr int v8::internal::compiler::FastApiCallNode::kFrameState = 1 [static], [constexpr]
Definition at line 1377 of file simplified-operator.h.
Referenced by SlowCallArgumentCount().
kSlowCodeTarget
constexpr int v8::internal::compiler::FastApiCallNode::kSlowCodeTarget = 1 [static], [constexpr]
Definition at line 1372 of file simplified-operator.h.
Referenced by SlowCallArgumentCount().
slow_arg_count_
const int v8::internal::compiler::FastApiCallNode::slow_arg_count_ [private]
Definition at line 1423 of file simplified-operator.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/simplified-operator.h
/mnt/V8SourceCode/src/compiler/simplified-operator.cc