v8::internal::ReadOnlyRoots Class Reference
#include <roots.h>
Public Member Functions
ReadOnlyRoots (Heap *heap)
ReadOnlyRoots (const Isolate *isolate)
ReadOnlyRoots (LocalIsolate *isolate)
MapWord one_pointer_filler_map_word ()
bool IsNameForProtector (Tagged< HeapObject > object) const
void VerifyNameForProtectorsPages () const
Tagged< Boolean > boolean_value (bool value) const
Tagged< String > single_character_string (int code) const
Address address_at (RootIndex root_index) const
Tagged< Object > object_at (RootIndex root_index) const
bool is_initialized (RootIndex root_index) const
void Iterate (RootVisitor *visitor)
void InitFromStaticRootsTable (Address cage_base)
Static Public Attributes
static constexpr size_t kEntriesCount
Private Member Functions
Address first_name_for_protector () const
Address last_name_for_protector () const
ReadOnlyRoots (Address *ro_roots)
Private Attributes
Address * read_only_roots_
Friends
class ReadOnlyHeap
class DeserializerAllocator
class ReadOnlyHeapImageDeserializer
ReadOnlyRoots GetReadOnlyRoots ()
Detailed Description
Definition at line 724 of file roots.h.
Constructor & Destructor Documentation
ReadOnlyRoots() [1/4]
v8::internal::ReadOnlyRoots::ReadOnlyRoots (Heap * heap) [inline], [explicit]
Definition at line 91 of file roots-inl.h.
    : ReadOnlyRoots(Isolate::FromHeap(heap)) {}
ReadOnlyRoots() [2/4]
v8::internal::ReadOnlyRoots::ReadOnlyRoots (const Isolate * isolate) [inline], [explicit]
Definition at line 94 of file roots-inl.h.
    : read_only_roots_(reinterpret_cast<Address*>(
          isolate->roots_table().read_only_roots_begin().address())) {}
ReadOnlyRoots() [3/4]
v8::internal::ReadOnlyRoots::ReadOnlyRoots (LocalIsolate * isolate) [inline], [explicit]
Definition at line 98 of file roots-inl.h.
    : ReadOnlyRoots(isolate->factory()->read_only_roots()) {}
ReadOnlyRoots() [4/4]
v8::internal::ReadOnlyRoots::ReadOnlyRoots (Address * ro_roots) [inline], [explicit], [private]
Definition at line 775 of file roots.h.
      : read_only_roots_(ro_roots) {}
Member Function Documentation
address_at()
Address v8::internal::ReadOnlyRoots::address_at (RootIndex root_index) const [inline]
Definition at line 147 of file roots-inl.h.
                                                            {
#if V8_STATIC_ROOTS_BOOL
  return V8HeapCompressionScheme::DecompressTagged(
      StaticReadOnlyRootsPointerTable[static_cast<int>(root_index)]);
#else
  size_t index = static_cast<size_t>(root_index);
  DCHECK_LT(index, kEntriesCount);
  // Filler objects must be created before the free space map is initialized.
  // Bootstrapping is able to handle kNullAddress being returned here.
  DCHECK_IMPLIES(read_only_roots_[index] == kNullAddress,
                 root_index == RootIndex::kFreeSpaceMap);
  return read_only_roots_[index];
#endif
}
References DCHECK_IMPLIES, DCHECK_LT, v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTagged(), v8::internal::index, kEntriesCount, v8::internal::kNullAddress, and read_only_roots_.
Referenced by first_name_for_protector(), last_name_for_protector(), and object_at().
boolean_value()
Tagged< Boolean > v8::internal::ReadOnlyRoots::boolean_value (bool value) const [inline]
Definition at line 115 of file roots-inl.h.
                                                             {
  return value ? Tagged<Boolean>(true_value()) : Tagged<Boolean>(false_value());
}
References v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::Heap::ToBoolean().
first_name_for_protector()
Address v8::internal::ReadOnlyRoots::first_name_for_protector () const [inline], [private]
Definition at line 123 of file roots-inl.h.
                                                      {
  return address_at(RootIndex::kFirstNameForProtector);
}
References address_at(), and v8::internal::kFirstNameForProtector.
Referenced by IsNameForProtector(), and VerifyNameForProtectorsPages().
InitFromStaticRootsTable()
void v8::internal::ReadOnlyRoots::InitFromStaticRootsTable (Address cage_base)
Definition at line 115 of file roots.cc.
                                                              {
  CHECK(V8_STATIC_ROOTS_BOOL);
#if V8_STATIC_ROOTS_BOOL
  RootIndex pos = RootIndex::kFirstReadOnlyRoot;
  for (auto element : StaticReadOnlyRootsPointerTable) {
    auto ptr = V8HeapCompressionScheme::DecompressTagged(element);
    DCHECK(!is_initialized(pos));
    read_only_roots_[static_cast<size_t>(pos)] = ptr;
    ++pos;
  }
  DCHECK_EQ(static_cast<int>(pos) - 1, RootIndex::kLastReadOnlyRoot);
#endif // V8_STATIC_ROOTS_BOOL
}
References CHECK, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTagged(), is_initialized(), v8::internal::kFirstReadOnlyRoot, v8::internal::kLastReadOnlyRoot, read_only_roots_, and V8_STATIC_ROOTS_BOOL.
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::DeserializeReadOnlyRootsTable().
is_initialized()
bool v8::internal::ReadOnlyRoots::is_initialized (RootIndex root_index) const [inline]
Definition at line 162 of file roots-inl.h.
                                                             {
  size_t index = static_cast<size_t>(root_index);
  DCHECK_LT(index, kEntriesCount);
  return read_only_roots_[index] != kNullAddress;
}
References DCHECK_LT, v8::internal::index, kEntriesCount, v8::internal::kNullAddress, and read_only_roots_.
Referenced by v8::internal::anonymous_namespace{heap.cc}::CreateFillerObjectAtImpl(), v8::internal::Heap::CreateReadOnlyHeapObjects(), and InitFromStaticRootsTable().
IsNameForProtector()
bool v8::internal::ReadOnlyRoots::IsNameForProtector (Tagged< HeapObject > object) const [inline]
Definition at line 131 of file roots-inl.h.
                                                                      {
  return base::IsInRange(object.ptr(), first_name_for_protector(),
                         last_name_for_protector());
}
References first_name_for_protector(), and last_name_for_protector().
Referenced by v8::internal::LookupIterator::UpdateProtector().
Iterate()
void v8::internal::ReadOnlyRoots::Iterate (RootVisitor * visitor)
Definition at line 54 of file roots.cc.
                                                {
  visitor->VisitRootPointers(Root::kReadOnlyRootList, nullptr,
                             FullObjectSlot(read_only_roots_),
                             FullObjectSlot(&read_only_roots_[kEntriesCount]));
  visitor->Synchronize(VisitorSynchronization::kReadOnlyRootList);
}
References kEntriesCount, read_only_roots_, v8::internal::RootVisitor::Synchronize(), and v8::internal::RootVisitor::VisitRootPointers().
Referenced by v8::internal::V8HeapExplorer::IterateAndExtractReferences().
last_name_for_protector()
Address v8::internal::ReadOnlyRoots::last_name_for_protector () const [inline], [private]
Definition at line 127 of file roots-inl.h.
                                                     {
  return address_at(RootIndex::kLastNameForProtector);
}
References address_at(), and v8::internal::kLastNameForProtector.
Referenced by IsNameForProtector(), and VerifyNameForProtectorsPages().
object_at()
Tagged< Object > v8::internal::ReadOnlyRoots::object_at (RootIndex root_index) const [inline]
Definition at line 143 of file roots-inl.h.
                                                                  {
  return Tagged<Object>(address_at(root_index));
}
References address_at(), and v8::internal::Tagged< Object >.
Referenced by v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitReadOnlyRootsTable(), v8::internal::Map::GetMapFor(), and single_character_string().
one_pointer_filler_map_word()
MapWord v8::internal::ReadOnlyRoots::one_pointer_filler_map_word ()
Definition at line 50 of file roots.cc.
                                                   {
  return MapWord::FromMap(one_pointer_filler_map());
}
References v8::internal::MapWord::FromMap().
single_character_string()
Tagged< String > v8::internal::ReadOnlyRoots::single_character_string (int code) const [inline]
Definition at line 119 of file roots-inl.h.
                                                                    {
  return Cast<String>(object_at(RootsTable::SingleCharacterStringIndex(code)));
}
References code, object_at(), and v8::internal::RootsTable::SingleCharacterStringIndex().
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::ConcurrentLookupIterator::TryGetOwnChar().
VerifyNameForProtectorsPages()
void v8::internal::ReadOnlyRoots::VerifyNameForProtectorsPages () const [inline]
Definition at line 136 of file roots-inl.h.
                                                       {
  // The symbols and strings that can cause protector invalidation should
  // reside on the same page so we can do a fast range check.
  CHECK_EQ(PageMetadata::FromAddress(first_name_for_protector()),
           PageMetadata::FromAddress(last_name_for_protector()));
}
References CHECK_EQ, first_name_for_protector(), v8::internal::PageMetadata::FromAddress(), and last_name_for_protector().
Referenced by v8::internal::Heap::CreateReadOnlyObjects(), and v8::internal::ReadOnlyDeserializer::DeserializeIntoIsolate().
Friends And Related Function Documentation
DeserializerAllocator
friend class DeserializerAllocator [friend]
Definition at line 781 of file roots.h.
GetReadOnlyRoots
ReadOnlyRoots GetReadOnlyRoots () [friend]
Definition at line 82 of file roots-inl.h.
                                 {
  ReadOnlyHeap* shared_ro_heap =
      IsolateGroup::current()->shared_read_only_heap();
  // If this check fails in code that runs during initialization use
  // EarlyGetReadOnlyRoots instead.
  DCHECK(shared_ro_heap && shared_ro_heap->roots_init_complete());
  return ReadOnlyRoots(shared_ro_heap->read_only_roots_);
}
ReadOnlyHeap
friend class ReadOnlyHeap [friend]
Definition at line 780 of file roots.h.
ReadOnlyHeapImageDeserializer
friend class ReadOnlyHeapImageDeserializer [friend]
Definition at line 782 of file roots.h.
Member Data Documentation
kEntriesCount
constexpr size_t v8::internal::ReadOnlyRoots::kEntriesCount [static], [constexpr]
Initial value:
=
      static_cast<size_t>(RootIndex::kReadOnlyRootsCount)
Definition at line 726 of file roots.h.
Referenced by address_at(), v8::internal::ReadOnlyHeapImageDeserializer::DeserializeReadOnlyRootsTable(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitReadOnlyRootsTable(), is_initialized(), and Iterate().
read_only_roots_
Address* v8::internal::ReadOnlyRoots::read_only_roots_ [private]
Definition at line 778 of file roots.h.
Referenced by address_at(), v8::internal::ReadOnlyHeapImageDeserializer::DeserializeReadOnlyRootsTable(), InitFromStaticRootsTable(), is_initialized(), and Iterate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/roots/roots.h
/mnt/V8SourceCode/src/roots/roots-inl.h
/mnt/V8SourceCode/src/roots/roots.cc