v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector Class Reference
Classes
class Segment
Public Member Functions
const CanonicalType * operator[] (CanonicalTypeIndex index) const
const CanonicalType * operator[] (CanonicalValueType type) const
void reserve (uint32_t size, Zone *zone)
void set (CanonicalTypeIndex index, const CanonicalType *type)
void ClearForTesting ()
const CanonicalTypeIndex FindIndex_Slow (const CanonicalSig *sig) const
Private Attributes
std::atomic< Segment * > segments_ [kNumSegments] {}
Static Private Attributes
static constexpr uint32_t kSegmentSize = 1024
static constexpr uint32_t kNumSegments
Detailed Description
Definition at line 451 of file canonical-types.h.
Member Function Documentation
ClearForTesting()
void v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::ClearForTesting () [inline]
Definition at line 496 of file canonical-types.h.
                           {
      for (uint32_t i = 0; i < kNumSegments; ++i) {
        if (segments_[i].load(std::memory_order_relaxed) == nullptr) break;
        segments_[i].store(nullptr, std::memory_order_relaxed);
      }
    }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, kNumSegments, and segments_.
Referenced by v8::internal::wasm::TypeCanonicalizer::EmptyStorageForTesting().
FindIndex_Slow()
const CanonicalTypeIndex v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::FindIndex_Slow (const CanonicalSig * sig) const [inline]
Definition at line 503 of file canonical-types.h.
                                                                           {
      for (uint32_t i = 0; i < kNumSegments; ++i) {
        Segment* segment = segments_[i].load(std::memory_order_relaxed);
        // If callers have a CanonicalSig* to pass into this function, the
        // type canonicalizer must know about this sig, hence we must find it
        // before hitting a `nullptr` segment.
        DCHECK_NOT_NULL(segment);
        for (uint32_t k = 0; k < kSegmentSize; ++k) {
          const CanonicalType* type = (*segment)[k];
          // Again: We expect to find the signature before hitting uninitialized
          // slots.
          DCHECK_NOT_NULL(type);
          if (type->kind == CanonicalType::kFunction &&
              type->function_sig == sig) {
            return CanonicalTypeIndex{i * kSegmentSize + k};
          }
        }
      }
      UNREACHABLE();
    }
References DCHECK_NOT_NULL, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::TypeCanonicalizer::CanonicalType::kFunction, kNumSegments, kSegmentSize, segments_, v8::internal::sig, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::TypeCanonicalizer::FindIndex_Slow().
operator[]() [1/2]
const CanonicalType* v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::operator[] (CanonicalTypeIndex index) const [inline]
Definition at line 461 of file canonical-types.h.
                                                                    {
      uint32_t segment_idx = index.index / kSegmentSize;
      // Only check against the static constant here; uninitialized segments are
      // {nullptr}, so accessing them crashes.
      SBXCHECK_GT(kNumSegments, segment_idx);
      Segment* segment = segments_[segment_idx].load(std::memory_order_relaxed);
      const CanonicalType* type = (*segment)[index.index % kSegmentSize];
      // DCHECK is sufficient as returning {nullptr} is safe.
      DCHECK_NOT_NULL(type);
      return type;
    }
References DCHECK_NOT_NULL, v8::internal::index, kNumSegments, kSegmentSize, SBXCHECK_GT, segments_, and v8::internal::tracing::type.
operator[]() [2/2]
const CanonicalType* v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::operator[] (CanonicalValueType type) const [inline]
Definition at line 473 of file canonical-types.h.
                                                                   {
      DCHECK(type.has_index());
      return (*this)[type.ref_index()];
    }
References v8::internal::DCHECK(), and v8::internal::tracing::type.
reserve()
void v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::reserve (uint32_t size, Zone * zone) [inline]
Definition at line 478 of file canonical-types.h.
                                            {
      DCHECK_GE(kMaxCanonicalTypes, size);
      uint32_t segment_idx = size / kSegmentSize;
      // Stop on the first segment (iterating backwards) which already exists.
      while (!segments_[segment_idx].load(std::memory_order_relaxed)) {
        segments_[segment_idx].store(zone->New<Segment>(),
                                     std::memory_order_relaxed);
        if (segment_idx-- == 0) break;
      }
    }
References DCHECK_GE, v8::internal::wasm::kMaxCanonicalTypes, kSegmentSize, v8::internal::Zone::New(), segments_, and size().
Referenced by v8::internal::wasm::TypeCanonicalizer::AddPredefinedArrayTypes(), v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), and v8::internal::wasm::TypeCanonicalizer::AddRecursiveSingletonGroup().
set()
void v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::set (CanonicalTypeIndex index, const CanonicalType * type) [inline]
Definition at line 489 of file canonical-types.h.
                                                                  {
      // No checking needed, this is only executed after CheckMaxCanonicalIndex.
      uint32_t segment_idx = index.index / kSegmentSize;
      Segment* segment = segments_[segment_idx].load(std::memory_order_relaxed);
      segment->set(index.index % kSegmentSize, type);
    }
References v8::internal::index, kSegmentSize, segments_, v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::Segment::set(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::TypeCanonicalizer::AddPredefinedArrayTypes(), v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), and v8::internal::wasm::TypeCanonicalizer::AddRecursiveSingletonGroup().
Member Data Documentation
kNumSegments
constexpr uint32_t v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::kNumSegments [static], [constexpr], [private]
Initial value:
=
        (kMaxCanonicalTypes + kSegmentSize - 1) / kSegmentSize
Definition at line 453 of file canonical-types.h.
Referenced by ClearForTesting(), FindIndex_Slow(), and operator[]().
kSegmentSize
constexpr uint32_t v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::kSegmentSize = 1024 [static], [constexpr], [private]
Definition at line 452 of file canonical-types.h.
Referenced by FindIndex_Slow(), operator[](), v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::Segment::operator[](), reserve(), set(), and v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::Segment::set().
segments_
std::atomic<Segment*> v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::segments_[kNumSegments] {} [private]
Definition at line 542 of file canonical-types.h.
Referenced by ClearForTesting(), FindIndex_Slow(), operator[](), reserve(), and set().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/canonical-types.h