v8::internal::DwVfpRegister Class Reference
#include <register-arm.h>
Public Member Functions
void split_code (int *vm, int *m) const
VfpRegList ToVfpRegList () const
Static Public Member Functions
static int SupportedRegisterCount ()
static void split_code (int reg_code, int *vm, int *m)
Static Public Attributes
static constexpr int kSizeInBytes = 8
Private Member Functions
constexpr DwVfpRegister (int code)
Friends
class RegisterBase
class LowDwVfpRegister
Additional Inherited Members
Detailed Description
Definition at line 162 of file register-arm.h.
Constructor & Destructor Documentation
DwVfpRegister()
constexpr v8::internal::DwVfpRegister::DwVfpRegister (int code) [inline], [explicit], [constexpr], [private]
Definition at line 185 of file register-arm.h.
: RegisterBase(code) {}
Member Function Documentation
split_code() [1/2]
void v8::internal::DwVfpRegister::split_code (int * vm, int * m) const [inline]
Definition at line 176 of file register-arm.h.
{ split_code(code(), vm, m); }
References v8::internal::RegisterBase< DwVfpRegister, kDoubleAfterLast >::code(), and split_code().
Referenced by split_code().
split_code() [2/2]
static void v8::internal::DwVfpRegister::split_code (int reg_code, int * vm, int * m) [inline], [static]
Definition at line 171 of file register-arm.h.
                                                        {
    DCHECK(from_code(reg_code).is_valid());
    *m = (reg_code & 0x10) >> 4;
    *vm = reg_code & 0x0F;
  }
References v8::internal::DCHECK(), v8::internal::RegisterBase< DwVfpRegister, kDoubleAfterLast >::from_code(), and v8::internal::RegisterBase< DwVfpRegister, kDoubleAfterLast >::is_valid().
SupportedRegisterCount()
static int v8::internal::DwVfpRegister::SupportedRegisterCount () [inline], [static]
ToVfpRegList()
VfpRegList v8::internal::DwVfpRegister::ToVfpRegList () const [inline]
Definition at line 177 of file register-arm.h.
                                  {
    // A D register overlaps two S registers.
    return uint64_t{0x3} << (code() * 2);
  }
References v8::internal::RegisterBase< DwVfpRegister, kDoubleAfterLast >::code().
Referenced by v8::internal::compiler::CodeGenerator::SetPendingMove().
Friends And Related Function Documentation
LowDwVfpRegister
friend class LowDwVfpRegister [friend]
Definition at line 184 of file register-arm.h.
RegisterBase
friend class RegisterBase [friend]
Definition at line 183 of file register-arm.h.
Member Data Documentation
kSizeInBytes
constexpr int v8::internal::DwVfpRegister::kSizeInBytes = 8 [static], [constexpr]
Definition at line 164 of file register-arm.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/arm/register-arm.h