v8::internal::WeakCodeRegistry Class Reference
#include <weak-code-registry.h>
Classes
struct Listener
Public Member Functions
WeakCodeRegistry (Isolate *isolate)
~WeakCodeRegistry ()
void Track (CodeEntry *entry, DirectHandle< AbstractCode > code)
void Sweep (Listener *listener)
void Clear ()
Private Attributes
Isolate *const isolate_
std::vector< CodeEntry * > entries_
Detailed Description
Definition at line 17 of file weak-code-registry.h.
Constructor & Destructor Documentation
WeakCodeRegistry()
v8::internal::WeakCodeRegistry::WeakCodeRegistry (Isolate * isolate) [inline], [explicit]
Definition at line 23 of file weak-code-registry.h.
: isolate_(isolate) {}
 WeakCodeRegistry()
v8::internal::WeakCodeRegistry::~WeakCodeRegistry () [inline]
Definition at line 24 of file weak-code-registry.h.
{ Clear(); }
Member Function Documentation
Clear()
void v8::internal::WeakCodeRegistry::Clear ()
Definition at line 56 of file weak-code-registry.cc.
                             {
  for (CodeEntry* entry : entries_) {
    Untrack(entry);
  }
  entries_.clear();
}
References entries_, and v8::internal::anonymous_namespace{weak-code-registry.cc}::Untrack().
Referenced by v8::internal::ProfilerCodeObserver::ClearCodeMap().
Sweep()
void v8::internal::WeakCodeRegistry::Sweep (WeakCodeRegistry::Listener * listener)
Definition at line 40 of file weak-code-registry.cc.
                                                               {
  std::vector<CodeEntry*> alive_entries;
  for (CodeEntry* entry : entries_) {
    // Mark the CodeEntry as being deleted on the heap if the heap object
    // location was nulled, indicating the object was freed.
    if (!*entry->heap_object_location_address()) {
      if (listener) {
        listener->OnHeapObjectDeletion(entry);
      }
    } else {
      alive_entries.push_back(entry);
    }
  }
  entries_ = std::move(alive_entries);
}
References entries_, and v8::internal::WeakCodeRegistry::Listener::OnHeapObjectDeletion().
Referenced by v8::internal::ProfilerListener::CodeSweepEvent(), and v8::internal::ProfilerListener::WeakCodeClearEvent().
Track()
void v8::internal::WeakCodeRegistry::Track (CodeEntry * entry, DirectHandle< AbstractCode > code)
Definition at line 26 of file weak-code-registry.cc.
                                                              {
  DCHECK(!*entry->heap_object_location_address());
  DisallowGarbageCollection no_gc;
  Handle<AbstractCode> handle = isolate_->global_handles()->Create(*code);
  Address** heap_object_location_address =
      entry->heap_object_location_address();
  *heap_object_location_address = handle.location();
  GlobalHandles::MakeWeak(heap_object_location_address);
  entries_.push_back(entry);
}
References code, v8::internal::GlobalHandles::Create(), v8::internal::DCHECK(), entries_, v8::internal::Isolate::global_handles(), v8::internal::handle(), v8::internal::CodeEntry::heap_object_location_address(), isolate_, v8::internal::GlobalHandles::MakeWeak(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::ProfilerListener::CodeCreateEvent(), and v8::internal::ProfilerListener::RegExpCodeCreateEvent().
Member Data Documentation
entries_
std::vector<CodeEntry*> v8::internal::WeakCodeRegistry::entries_ [private]
Definition at line 41 of file weak-code-registry.h.
Referenced by Clear(), Sweep(), and Track().
isolate_
Isolate* const v8::internal::WeakCodeRegistry::isolate_ [private]
Definition at line 37 of file weak-code-registry.h.
Referenced by Track().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/weak-code-registry.h
/mnt/V8SourceCode/src/profiler/weak-code-registry.cc