v8::internal::compiler::LoadElimination::IndexRange Class Reference
Classes
struct Iterator
Public Member Functions
IndexRange (int begin, int size)
bool operator== (const IndexRange &other) const
bool operator!= (const IndexRange &other) const
Iterator begin ()
Iterator end ()
Static Public Member Functions
static IndexRange Invalid ()
Private Member Functions
IndexRange ()
Private Attributes
int begin_
int end_
Detailed Description
Definition at line 217 of file load-elimination.h.
Constructor & Destructor Documentation
IndexRange() [1/2]
v8::internal::compiler::LoadElimination::IndexRange::IndexRange (int begin, int size) [inline]
Definition at line 219 of file load-elimination.h.
                                    : begin_(begin), end_(begin + size) {
      DCHECK_LE(0, begin);
      DCHECK_LE(1, size);
      if (end_ > static_cast<int>(kMaxTrackedFieldsPerObject)) {
        if (V8_UNLIKELY(v8_flags.trace_turbo_bailouts)) {
          std::cout << "Bailing out in Load Elimination because of "
                       "kMaxTrackedFieldsPerObject\n";
        }
        *this = IndexRange::Invalid();
      }
    }
References v8::internal::compiler::begin(), DCHECK_LE, size(), v8::internal::v8_flags, and V8_UNLIKELY.
IndexRange() [2/2]
v8::internal::compiler::LoadElimination::IndexRange::IndexRange () [inline], [private]
Definition at line 251 of file load-elimination.h.
: begin_(-1), end_(-1) {}
Member Function Documentation
begin()
Iterator v8::internal::compiler::LoadElimination::IndexRange::begin () [inline]
Definition at line 244 of file load-elimination.h.
{ return {begin_}; }
end()
Iterator v8::internal::compiler::LoadElimination::IndexRange::end () [inline]
Definition at line 245 of file load-elimination.h.
{ return {end_}; }
Invalid()
static IndexRange v8::internal::compiler::LoadElimination::IndexRange::Invalid () [inline], [static]
Definition at line 230 of file load-elimination.h.
{ return IndexRange(); }
Referenced by v8::internal::compiler::LoadElimination::ComputeLoopStateForStoreField(), v8::internal::compiler::LoadElimination::FieldIndexOf(), v8::internal::compiler::LoadElimination::ReduceLoadField(), and v8::internal::compiler::LoadElimination::ReduceStoreField().
operator!=()
bool v8::internal::compiler::LoadElimination::IndexRange::operator!= (const IndexRange & other) const [inline]
Definition at line 235 of file load-elimination.h.
{ return !(*this == other); }
operator==()
bool v8::internal::compiler::LoadElimination::IndexRange::operator== (const IndexRange & other) const [inline]
Definition at line 232 of file load-elimination.h.
                                                   {
      return begin_ == other.begin_ && end_ == other.end_;
    }
References begin_, and end_.
Member Data Documentation
begin_
int v8::internal::compiler::LoadElimination::IndexRange::begin_ [private]
Definition at line 248 of file load-elimination.h.
Referenced by operator==().
end_
int v8::internal::compiler::LoadElimination::IndexRange::end_ [private]
Definition at line 249 of file load-elimination.h.
Referenced by operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/load-elimination.h