v8::internal::torque::Builtin Class Reference
#include <declarable.h>
Public Types
enum Kind { kStub
, kFixedArgsJavaScript
, kVarArgsJavaScript
 }
enum class Flag { kNone = 0
, kCustomInterfaceDescriptor = 1 << 0
 }
using Flags = base::Flags< Flag >
Public Member Functions
Kind kind () const
Flags flags () const
std::optional< std::string > use_counter_name () const
bool IsStub () const
bool IsVarArgsJavaScript () const
bool IsFixedArgsJavaScript () const
bool IsJavaScript () const
bool HasCustomInterfaceDescriptor () const
Private Member Functions
Builtin (std::string external_name, std::string readable_name, Builtin::Kind kind, Flags flags, const Signature &signature, std::optional< std::string > use_counter_name, std::optional< Statement * > body)
Private Attributes
Kind kind_
Flags flags_
std::optional< std::string > use_counter_name_
Friends
class Declarations
Additional Inherited Members
Detailed Description
Definition at line 497 of file declarable.h.
Member Typedef Documentation
Flags
using v8::internal::torque::Builtin::Flags = base::Flags<Flag>
Definition at line 501 of file declarable.h.
Member Enumeration Documentation
Flag
enum v8::internal::torque::Builtin::Flag [strong]
Enumerator
kNone
kCustomInterfaceDescriptor
Definition at line 500 of file declarable.h.
{ kNone = 0, kCustomInterfaceDescriptor = 1 << 0 };
Kind
enum v8::internal::torque::Builtin::Kind
Enumerator
kStub
kFixedArgsJavaScript
kVarArgsJavaScript
Definition at line 499 of file declarable.h.
{ kStub, kFixedArgsJavaScript, kVarArgsJavaScript };
Constructor & Destructor Documentation
Builtin()
v8::internal::torque::Builtin::Builtin (std::string external_name, std::string readable_name, Builtin::Kind kind, Flags flags, const Signature & signature, std::optional< std::string > use_counter_name, std::optional< Statement * > body) [inline], [private]
Definition at line 520 of file declarable.h.
      : Callable(Declarable::kBuiltin, std::move(external_name),
                 std::move(readable_name), signature, body),
        kind_(kind),
        flags_(flags),
        use_counter_name_(use_counter_name) {}
Member Function Documentation
flags()
Flags v8::internal::torque::Builtin::flags () const [inline]
Definition at line 504 of file declarable.h.
{ return flags_; }
References flags_.
HasCustomInterfaceDescriptor()
bool v8::internal::torque::Builtin::HasCustomInterfaceDescriptor () const [inline]
Definition at line 514 of file declarable.h.
                                            {
    return flags_ & Flag::kCustomInterfaceDescriptor;
  }
References flags_, and kCustomInterfaceDescriptor.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors().
IsFixedArgsJavaScript()
bool v8::internal::torque::Builtin::IsFixedArgsJavaScript () const [inline]
Definition at line 510 of file declarable.h.
{ return kind_ == kFixedArgsJavaScript; }
References kFixedArgsJavaScript, and kind_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors(), IsJavaScript(), and v8::internal::torque::ImplementationVisitor::Visit().
IsJavaScript()
bool v8::internal::torque::Builtin::IsJavaScript () const [inline]
Definition at line 511 of file declarable.h.
                            {
    return IsVarArgsJavaScript() || IsFixedArgsJavaScript();
  }
References IsFixedArgsJavaScript(), and IsVarArgsJavaScript().
IsStub()
bool v8::internal::torque::Builtin::IsStub () const [inline]
Definition at line 508 of file declarable.h.
{ return kind_ == kStub; }
References kind_, and kStub.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors(), and v8::internal::torque::ImplementationVisitor::Visit().
IsVarArgsJavaScript()
bool v8::internal::torque::Builtin::IsVarArgsJavaScript () const [inline]
Definition at line 509 of file declarable.h.
{ return kind_ == kVarArgsJavaScript; }
References kind_, and kVarArgsJavaScript.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors(), IsJavaScript(), and v8::internal::torque::ImplementationVisitor::Visit().
kind()
Kind v8::internal::torque::Builtin::kind () const [inline]
Definition at line 503 of file declarable.h.
{ return kind_; }
References kind_.
Referenced by v8::internal::torque::ImplementationVisitor::GetBuiltinCode(), and v8::internal::torque::ImplementationVisitor::Visit().
use_counter_name()
std::optional<std::string> v8::internal::torque::Builtin::use_counter_name () const [inline]
Definition at line 505 of file declarable.h.
                                                  {
    return use_counter_name_;
  }
References use_counter_name_.
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
Friends And Related Function Documentation
Declarations
friend class Declarations [friend]
Definition at line 519 of file declarable.h.
Member Data Documentation
flags_
Flags v8::internal::torque::Builtin::flags_ [private]
Definition at line 531 of file declarable.h.
Referenced by flags(), and HasCustomInterfaceDescriptor().
kind_
Kind v8::internal::torque::Builtin::kind_ [private]
Definition at line 530 of file declarable.h.
Referenced by IsFixedArgsJavaScript(), IsStub(), IsVarArgsJavaScript(), and kind().
use_counter_name_
std::optional<std::string> v8::internal::torque::Builtin::use_counter_name_ [private]
Definition at line 532 of file declarable.h.
Referenced by use_counter_name().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/declarable.h