v8::internal::RootIndexMap Class Reference
#include <address-map.h>
Public Member Functions
RootIndexMap (Isolate *isolate)
RootIndexMap (const RootIndexMap &)=delete
RootIndexMap & operator= (const RootIndexMap &)=delete
V8_EXPORT_PRIVATE bool Lookup (Tagged< HeapObject > obj, RootIndex *out_root_list) const
Private Attributes
HeapObjectToIndexHashMap * map_
Detailed Description
Definition at line 57 of file address-map.h.
Constructor & Destructor Documentation
RootIndexMap() [1/2]
v8::internal::RootIndexMap::RootIndexMap (Isolate * isolate) [explicit]
Definition at line 13 of file address-map.cc.
                                           {
  map_ = isolate->root_index_map();
  if (map_ != nullptr) return;
  map_ = new HeapObjectToIndexHashMap();
  for (RootIndex root_index = RootIndex::kFirstStrongOrReadOnlyRoot;
       root_index <= RootIndex::kLastStrongOrReadOnlyRoot; ++root_index) {
    Tagged<Object> root = isolate->root(root_index);
    if (!IsHeapObject(root)) continue;
    // Omit root entries that can be written after initialization. They must
    // not be referenced through the root list in the snapshot.
    // Since we map the raw address of an root item to its root list index, the
    // raw address must be constant, i.e. the object must be immovable.
    if (RootsTable::IsImmortalImmovable(root_index)) {
      Tagged<HeapObject> heap_object = Cast<HeapObject>(root);
      Maybe<uint32_t> maybe_index = map_->Get(heap_object);
      uint32_t index = static_cast<uint32_t>(root_index);
      if (maybe_index.IsJust()) {
        // Some are initialized to a previous value in the root list.
        DCHECK_LT(maybe_index.FromJust(), index);
      } else {
        map_->Set(heap_object, index);
      }
    }
  }
  isolate->set_root_index_map(map_);
}
References DCHECK_LT, v8::Maybe< T >::FromJust(), v8::internal::PointerToIndexHashMap< Type >::Get(), v8::internal::index, v8::internal::IsHeapObject(), v8::internal::RootsTable::IsImmortalImmovable(), v8::Maybe< T >::IsJust(), v8::internal::kFirstStrongOrReadOnlyRoot, v8::internal::kLastStrongOrReadOnlyRoot, map_, v8::internal::Isolate::root(), and v8::internal::PointerToIndexHashMap< Type >::Set().
RootIndexMap() [2/2]
v8::internal::RootIndexMap::RootIndexMap (const RootIndexMap &) [delete]
Member Function Documentation
Lookup()
V8_EXPORT_PRIVATE bool v8::internal::RootIndexMap::Lookup (Tagged< HeapObject > obj, RootIndex * out_root_list) const [inline]
Definition at line 64 of file address-map.h.
                                                                {
    Maybe<uint32_t> maybe_index = map_->Get(obj);
    if (maybe_index.IsJust()) {
      *out_root_list = static_cast<RootIndex>(maybe_index.FromJust());
      return true;
    }
    return false;
  }
References v8::Maybe< T >::FromJust(), and v8::Maybe< T >::IsJust().
operator=()
RootIndexMap& v8::internal::RootIndexMap::operator= (const RootIndexMap &) [delete]
Member Data Documentation
map_
HeapObjectToIndexHashMap* v8::internal::RootIndexMap::map_ [private]
Definition at line 75 of file address-map.h.
Referenced by RootIndexMap().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/utils/address-map.h
/mnt/V8SourceCode/src/utils/address-map.cc