v8::HandleScope Class Reference
A stack-allocated class that governs a number of local handles.
#include <v8-local-handle.h>
Public Member Functions
HandleScope (Isolate *isolate)
~HandleScope ()
Isolate * GetIsolate () const
HandleScope (const HandleScope &)=delete
void operator= (const HandleScope &)=delete
Static Public Member Functions
static int NumberOfHandles (Isolate *isolate)
Counts the number of allocated handles.
static internal::Address * CreateHandleForCurrentIsolate (internal::Address value)
Protected Member Functions
HandleScope ()=default
void Initialize (Isolate *isolate)
Static Protected Member Functions
static internal::Address * CreateHandle (internal::Isolate *i_isolate, internal::Address value)
Private Member Functions
void * operator new (size_t size)
void * operator new[] (size_t size)
void operator delete (void *, size_t)
void operator delete[] (void *, size_t)
Private Attributes
internal::Isolate * i_isolate_
internal::Address * prev_next_
internal::Address * prev_limit_
Friends
template<typename T >
class LocalBase
class Object
class Context
Detailed Description
A stack-allocated class that governs a number of local handles.
After a handle scope has been created, all local handles will be allocated within that handle scope until either the handle scope is deleted or another handle scope is created. If there is already a handle scope and a new one is created, all allocations will take place in the new handle scope until it is deleted. After that, new handles will again be allocated in the original handle scope.
After the handle scope of a local handle has been deleted the garbage collector will no longer track the object stored in the handle and may deallocate it. The behavior of accessing a handle for which the handle scope has been deleted is undefined.
Definition at line 119 of file v8-local-handle.h.
Constructor & Destructor Documentation
HandleScope() [1/3]
v8::HandleScope::HandleScope (Isolate * isolate) [explicit]
Definition at line 701 of file api.cc.
{ Initialize(v8_isolate); }
References Initialize().
 HandleScope()
v8::HandleScope::~HandleScope ()
Definition at line 725 of file api.cc.
                          {
#ifdef V8_ENABLE_CHECKS
  CHECK_EQ(scope_level_, i_isolate_->handle_scope_data()->level);
#endif
  i::HandleScope::CloseScope(i_isolate_, prev_next_, prev_limit_);
}
References CHECK_EQ, v8::internal::HandleScope::CloseScope(), v8::internal::Isolate::handle_scope_data(), i_isolate_, v8::internal::HandleScopeData::level, prev_limit_, and prev_next_.
HandleScope() [2/3]
v8::HandleScope::HandleScope (const HandleScope &) [delete]
HandleScope() [3/3]
v8::HandleScope::HandleScope () [inline], [protected], [default]
Member Function Documentation
CreateHandle()
i::Address * v8::HandleScope::CreateHandle (internal::Isolate * i_isolate, internal::Address value) [static], [protected]
Definition at line 742 of file api.cc.
                                                                       {
  return i::HandleScope::CreateHandle(i_isolate, value);
}
References v8::internal::HandleScope::CreateHandle(), and v8::internal::value.
Referenced by v8::EscapableHandleScopeBase::EscapableHandleScopeBase(), and v8::LocalBase< T >::New().
CreateHandleForCurrentIsolate()
static internal::Address* v8::HandleScope::CreateHandleForCurrentIsolate (internal::Address value) [static]
GetIsolate()
Isolate* v8::HandleScope::GetIsolate () const [inline]
Definition at line 130 of file v8-local-handle.h.
                                        {
    return reinterpret_cast<Isolate*>(i_isolate_);
  }
Referenced by v8::EscapableHandleScopeBase::EscapeSlot().
Initialize()
void v8::HandleScope::Initialize (Isolate * isolate) [protected]
Definition at line 703 of file api.cc.
                                                {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  // We do not want to check the correct usage of the Locker class all over the
  // place, so we do it only here: Without a HandleScope, an embedder can do
  // almost nothing, so it is enough to check in this central place.
  // We make an exception if the serializer is enabled, which means that the
  // Isolate is exclusively used to create a snapshot.
  Utils::ApiCheck(!i_isolate->was_locker_ever_used() ||
                      i_isolate->thread_manager()->IsLockedByCurrentThread() ||
                      i_isolate->serializer_enabled(),
                  "HandleScope::HandleScope",
                  "Entering the V8 API without proper locking in place");
  i::HandleScopeData* current = i_isolate->handle_scope_data();
  i_isolate_ = i_isolate;
  prev_next_ = current->next;
  prev_limit_ = current->limit;
  current->level++;
#ifdef V8_ENABLE_CHECKS
  scope_level_ = current->level;
#endif
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::handle_scope_data(), i_isolate_, v8::internal::ThreadManager::IsLockedByCurrentThread(), v8::internal::HandleScopeData::level, v8::internal::HandleScopeData::limit, v8::internal::HandleScopeData::next, prev_limit_, prev_next_, v8::internal::Isolate::serializer_enabled(), v8::internal::Isolate::thread_manager(), and v8::internal::Isolate::was_locker_ever_used().
Referenced by v8::EscapableHandleScopeBase::EscapableHandleScopeBase(), and HandleScope().
NumberOfHandles()
int v8::HandleScope::NumberOfHandles (Isolate * isolate) [static]
Counts the number of allocated handles.
Definition at line 737 of file api.cc.
                                                    {
  return i::HandleScope::NumberOfHandles(
      reinterpret_cast<i::Isolate*>(v8_isolate));
}
References v8::internal::HandleScope::NumberOfHandles().
Referenced by v8::internal::HandleScope::CloseScope().
operator delete()
void v8::HandleScope::operator delete (void * , size_t) [private]
Definition at line 734 of file api.cc.
{ base::OS::Abort(); }
References v8::base::OS::Abort().
operator delete[]()
void v8::HandleScope::operator delete[] (void * , size_t) [private]
Definition at line 735 of file api.cc.
{ base::OS::Abort(); }
References v8::base::OS::Abort().
operator new()
void * v8::HandleScope::operator new (size_t size) [private]
Definition at line 732 of file api.cc.
{ base::OS::Abort(); }
References v8::base::OS::Abort().
operator new[]()
void * v8::HandleScope::operator new[] (size_t size) [private]
Definition at line 733 of file api.cc.
{ base::OS::Abort(); }
References v8::base::OS::Abort().
operator=()
void v8::HandleScope::operator= (const HandleScope &) [delete]
Friends And Related Function Documentation
Context
friend class Context [friend]
Definition at line 170 of file v8-local-handle.h.
LocalBase
template<typename T >
friend class LocalBase [friend]
Definition at line 165 of file v8-local-handle.h.
Object
friend class Object [friend]
Definition at line 169 of file v8-local-handle.h.
Member Data Documentation
i_isolate_
internal::Isolate* v8::HandleScope::i_isolate_ [private]
Definition at line 156 of file v8-local-handle.h.
Referenced by Initialize(), and ~HandleScope().
prev_limit_
internal::Address* v8::HandleScope::prev_limit_ [private]
Definition at line 158 of file v8-local-handle.h.
Referenced by v8::internal::HandleScope::HandleScope(), Initialize(), ~HandleScope(), and v8::internal::HandleScope::~HandleScope().
prev_next_
internal::Address* v8::HandleScope::prev_next_ [private]
Definition at line 157 of file v8-local-handle.h.
Referenced by v8::internal::HandleScope::HandleScope(), Initialize(), ~HandleScope(), and v8::internal::HandleScope::~HandleScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-local-handle.h
/mnt/V8SourceCode/src/api/api.cc