v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper Class Reference
Public Member Functions
ConsoleHelper (const v8::debug::ConsoleCallArguments &info, const v8::debug::ConsoleContext &consoleContext, V8InspectorImpl *inspector)
ConsoleHelper (const ConsoleHelper &)=delete
ConsoleHelper & operator= (const ConsoleHelper &)=delete
v8::Isolate * isolate () const
v8::Local< v8::Context > context () const
int contextId () const
int groupId () const
InjectedScript * injectedScript (int sessionId)
V8InspectorSessionImpl * session (int sessionId)
V8ConsoleMessageStorage * consoleMessageStorage ()
void reportCall (ConsoleAPIType type)
void reportCallWithDefaultArgument (ConsoleAPIType type, const String16 &message)
void reportCallAndReplaceFirstArgument (ConsoleAPIType type, const String16 &message)
void reportCallWithArgument (ConsoleAPIType type, const String16 &message)
void reportCall (ConsoleAPIType type, v8::MemorySpan< const v8::Local< v8::Value >> arguments)
void reportDeprecatedCall (const char *id, const String16 &message)
bool firstArgToBoolean (bool defaultValue)
v8::Local< v8::String > firstArgToString ()
v8::MaybeLocal< v8::Object > firstArgAsObject ()
v8::MaybeLocal< v8::Function > firstArgAsFunction ()
void forEachSession (std::function< void(V8InspectorSessionImpl *)> callback)
Private Attributes
const v8::debug::ConsoleCallArguments & m_info
const v8::debug::ConsoleContext & m_consoleContext
V8InspectorImpl * m_inspector
Detailed Description
Definition at line 42 of file v8-console.cc.
Constructor & Destructor Documentation
ConsoleHelper() [1/2]
v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::ConsoleHelper (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext, V8InspectorImpl * inspector) [inline]
Definition at line 44 of file v8-console.cc.
      : m_info(info),
        m_consoleContext(consoleContext),
        m_inspector(inspector) {}
ConsoleHelper() [2/2]
v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::ConsoleHelper (const ConsoleHelper &) [delete]
Member Function Documentation
consoleMessageStorage()
V8ConsoleMessageStorage* v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::consoleMessageStorage () [inline]
Definition at line 71 of file v8-console.cc.
                                                   {
    return m_inspector->ensureConsoleMessageStorage(groupId());
  }
context()
v8::Local<v8::Context> v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::context () const [inline]
Definition at line 55 of file v8-console.cc.
                                     {
    return isolate()->GetCurrentContext();
  }
contextId()
int v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::contextId () const [inline]
Definition at line 58 of file v8-console.cc.
{ return InspectedContext::contextId(context()); }
References v8_inspector::InspectedContext::contextId().
firstArgAsFunction()
v8::MaybeLocal<v8::Function> v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::firstArgAsFunction () [inline]
Definition at line 184 of file v8-console.cc.
                                                {
    if (m_info.Length() < 1 || !m_info[0]->IsFunction())
      return v8::MaybeLocal<v8::Function>();
    v8::Local<v8::Function> func = m_info[0].As<v8::Function>();
    while (func->GetBoundFunction()->IsFunction())
      func = func->GetBoundFunction().As<v8::Function>();
    return func;
  }
References v8::Local< T >::As().
firstArgAsObject()
v8::MaybeLocal<v8::Object> v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::firstArgAsObject () [inline]
Definition at line 178 of file v8-console.cc.
                                            {
    if (m_info.Length() < 1 || !m_info[0]->IsObject())
      return v8::MaybeLocal<v8::Object>();
    return m_info[0].As<v8::Object>();
  }
firstArgToBoolean()
bool v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::firstArgToBoolean (bool defaultValue) [inline]
Definition at line 158 of file v8-console.cc.
                                            {
    if (m_info.Length() < 1) return defaultValue;
    if (m_info[0]->IsBoolean()) return m_info[0].As<v8::Boolean>()->Value();
    return m_info[0]->BooleanValue(m_inspector->isolate());
  }
firstArgToString()
v8::Local<v8::String> v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::firstArgToString () [inline]
Definition at line 164 of file v8-console.cc.
                                       {
    if (V8_LIKELY(m_info.Length() > 0)) {
      v8::Local<v8::Value> arg = m_info[0];
      if (V8_LIKELY(arg->IsString())) {
        return arg.As<v8::String>();
      }
      v8::Local<v8::String> label;
      if (!arg->IsUndefined() && arg->ToString(context()).ToLocal(&label)) {
        return label;
      }
    }
    return toV8StringInternalized(isolate(), "default");
  }
References v8::Local< T >::As(), v8::Value::IsString(), v8::Value::IsUndefined(), v8::Value::ToString(), v8_inspector::toV8StringInternalized(), and V8_LIKELY.
forEachSession()
void v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::forEachSession (std::function< void(V8InspectorSessionImpl *)> callback) [inline]
Definition at line 193 of file v8-console.cc.
                                                                           {
    m_inspector->forEachSession(groupId(), std::move(callback));
  }
groupId()
int v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::groupId () const [inline]
Definition at line 59 of file v8-console.cc.
{ return m_inspector->contextGroupId(contextId()); }
injectedScript()
InjectedScript* v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::injectedScript (int sessionId) [inline]
Definition at line 61 of file v8-console.cc.
                                                {
    InspectedContext* context = m_inspector->getContext(groupId(), contextId());
    if (!context) return nullptr;
    return context->getInjectedScript(sessionId);
  }
References v8_inspector::InspectedContext::getInjectedScript().
isolate()
v8::Isolate* v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::isolate () const [inline]
Definition at line 54 of file v8-console.cc.
{ return m_inspector->isolate(); }
operator=()
ConsoleHelper& v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::operator= (const ConsoleHelper &) [delete]
reportCall() [1/2]
void v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCall (ConsoleAPIType type) [inline]
Definition at line 75 of file v8-console.cc.
                                       {
    if (!m_info.Length()) return;
    v8::LocalVector<v8::Value> arguments(isolate());
    arguments.reserve(m_info.Length());
    for (int i = 0; i < m_info.Length(); ++i) arguments.push_back(m_info[i]);
    reportCall(type, {arguments.begin(), arguments.end()});
  }
References v8::LocalVector< T >::begin(), v8::LocalVector< T >::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::LocalVector< T >::push_back(), v8::LocalVector< T >::reserve(), and v8::internal::tracing::type.
reportCall() [2/2]
void v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCall (ConsoleAPIType type, v8::MemorySpan< const v8::Local< v8::Value >> arguments) [inline]
Definition at line 106 of file v8-console.cc.
                                                                  {
    if (!groupId()) return;
    // Depending on the type of the console message, we capture only parts of
    // the stack trace, or no stack trace at all.
    std::unique_ptr<V8StackTraceImpl> stackTrace;
    switch (type) {
      case ConsoleAPIType::kTrace:
        // The purpose of `console.trace()` is to output a stack trace to the
        // developer tools console, therefore we should always strive to
        // capture a full stack trace, even before any debugger is attached.
        stackTrace = m_inspector->debugger()->captureStackTrace(true);
        break;
      case ConsoleAPIType::kTimeEnd:
        // The `console.time()` and `console.timeEnd()` APIs are meant for
        // performance investigations, and therefore it's important to reduce
        // the total overhead of these calls, but also make sure these APIs
        // have consistent performance overhead. In order to guarantee that,
        // we always capture only the top frame, otherwise the performance
        // characteristics of `console.timeEnd()` would differ based on the
        // current call depth, which would skew the results.
        //
        // See https://crbug.com/41433391 for more information.
        stackTrace = V8StackTraceImpl::capture(m_inspector->debugger(), 1);
        break;
      default:
        // All other APIs get a full stack trace only when the debugger is
        // attached, otherwise record only the top frame.
        stackTrace = m_inspector->debugger()->captureStackTrace(false);
        break;
    }
    std::unique_ptr<V8ConsoleMessage> message =
        V8ConsoleMessage::createForConsoleAPI(
            context(), contextId(), groupId(), m_inspector,
            m_inspector->client()->currentTimeMS(), type, arguments,
            consoleContextToString(isolate(), m_consoleContext),
            std::move(stackTrace));
    consoleMessageStorage()->addMessage(std::move(message));
  }
References v8_inspector::V8StackTraceImpl::capture(), v8_inspector::anonymous_namespace{v8-console.cc}::consoleContextToString(), v8_inspector::V8ConsoleMessage::createForConsoleAPI(), v8_inspector::kTimeEnd, v8_inspector::kTrace, and v8::internal::tracing::type.
reportCallAndReplaceFirstArgument()
void v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCallAndReplaceFirstArgument (ConsoleAPIType type, const String16 & message) [inline]
Definition at line 92 of file v8-console.cc.
                                                                  {
    v8::LocalVector<v8::Value> arguments(isolate());
    arguments.push_back(toV8String(isolate(), message));
    for (int i = 1; i < m_info.Length(); ++i) arguments.push_back(m_info[i]);
    reportCall(type, {arguments.begin(), arguments.end()});
  }
References v8::LocalVector< T >::begin(), v8::LocalVector< T >::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::LocalVector< T >::push_back(), v8_inspector::toV8String(), and v8::internal::tracing::type.
reportCallWithArgument()
void v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCallWithArgument (ConsoleAPIType type, const String16 & message) [inline]
Definition at line 100 of file v8-console.cc.
                                                                            {
    auto arguments =
        v8::to_array<v8::Local<v8::Value>>({toV8String(isolate(), message)});
    reportCall(type, arguments);
  }
References v8_inspector::toV8String(), and v8::internal::tracing::type.
reportCallWithDefaultArgument()
void v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCallWithDefaultArgument (ConsoleAPIType type, const String16 & message) [inline]
Definition at line 83 of file v8-console.cc.
                                                              {
    v8::LocalVector<v8::Value> arguments(isolate());
    arguments.reserve(m_info.Length());
    for (int i = 0; i < m_info.Length(); ++i) arguments.push_back(m_info[i]);
    if (!m_info.Length()) arguments.push_back(toV8String(isolate(), message));
    reportCall(type, {arguments.begin(), arguments.end()});
  }
References v8::LocalVector< T >::begin(), v8::LocalVector< T >::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::LocalVector< T >::push_back(), v8::LocalVector< T >::reserve(), v8_inspector::toV8String(), and v8::internal::tracing::type.
reportDeprecatedCall()
void v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportDeprecatedCall (const char * id, const String16 & message) [inline]
Definition at line 148 of file v8-console.cc.
                                                                     {
    if (!consoleMessageStorage()->shouldReportDeprecationMessage(contextId(),
                                                                 id)) {
      return;
    }
    auto arguments =
        v8::to_array<v8::Local<v8::Value>>({toV8String(isolate(), message)});
    reportCall(ConsoleAPIType::kWarning, arguments);
  }
References v8_inspector::kWarning, and v8_inspector::toV8String().
session()
V8InspectorSessionImpl* v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::session (int sessionId) [inline]
Definition at line 67 of file v8-console.cc.
                                                 {
    return m_inspector->sessionById(groupId(), sessionId);
  }
Member Data Documentation
m_consoleContext
const v8::debug::ConsoleContext& v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::m_consoleContext [private]
Definition at line 199 of file v8-console.cc.
m_info
const v8::debug::ConsoleCallArguments& v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::m_info [private]
Definition at line 198 of file v8-console.cc.
m_inspector
V8InspectorImpl* v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::m_inspector [private]
Definition at line 200 of file v8-console.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/inspector/v8-console.cc