v8::internal::CountOperation Class Reference
#include <ast.h>
Public Member Functions
bool is_prefix () const
bool is_postfix () const
Token::Value op () const
Expression * expression () const
Private Types
using IsPrefixField = Expression::NextBitField< bool, 1 >
using TokenField = IsPrefixField::Next< Token::Value, 7 >
Private Member Functions
CountOperation (Token::Value op, bool is_prefix, Expression *expr, int pos)
Private Attributes
friend Zone
Expression * expression_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 1999 of file ast.h.
Member Typedef Documentation
IsPrefixField
using v8::internal::CountOperation::IsPrefixField = Expression::NextBitField<bool, 1> [private]
Definition at line 2017 of file ast.h.
TokenField
using v8::internal::CountOperation::TokenField = IsPrefixField::Next<Token::Value, 7> [private]
Definition at line 2018 of file ast.h.
Constructor & Destructor Documentation
CountOperation()
v8::internal::CountOperation::CountOperation (Token::Value op, bool is_prefix, Expression * expr, int pos) [inline], [private]
Definition at line 2012 of file ast.h.
      : Expression(pos, kCountOperation), expression_(expr) {
    bit_field_ |= IsPrefixField::encode(is_prefix) | TokenField::encode(op);
  }
References v8::internal::AstNode::bit_field_, v8::base::BitField< T, shift, size, U >::encode(), is_prefix(), and op().
Member Function Documentation
expression()
Expression* v8::internal::CountOperation::expression () const [inline]
Definition at line 2006 of file ast.h.
{ return expression_; }
References expression_.
is_postfix()
bool v8::internal::CountOperation::is_postfix () const [inline]
Definition at line 2002 of file ast.h.
{ return !is_prefix(); }
References is_prefix().
is_prefix()
bool v8::internal::CountOperation::is_prefix () const [inline]
Definition at line 2001 of file ast.h.
{ return IsPrefixField::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by CountOperation(), and is_postfix().
op()
Token::Value v8::internal::CountOperation::op () const [inline]
Definition at line 2004 of file ast.h.
{ return TokenField::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by CountOperation().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 2009 of file ast.h.
Member Data Documentation
expression_
Expression* v8::internal::CountOperation::expression_ [private]
Definition at line 2020 of file ast.h.
Referenced by expression().
Zone
friend v8::internal::CountOperation::Zone [private]
Definition at line 2010 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h