v8::internal::AssemblerRISCVM Class Reference
#include <extension-riscv-m.h>
Public Member Functions
void mul (Register rd, Register rs1, Register rs2)
void mulh (Register rd, Register rs1, Register rs2)
void mulhsu (Register rd, Register rs1, Register rs2)
void mulhu (Register rd, Register rs1, Register rs2)
void div (Register rd, Register rs1, Register rs2)
void divu (Register rd, Register rs1, Register rs2)
void rem (Register rd, Register rs1, Register rs2)
void remu (Register rd, Register rs1, Register rs2)
Additional Inherited Members
Detailed Description
Definition at line 15 of file extension-riscv-m.h.
Member Function Documentation
div()
void v8::internal::AssemblerRISCVM::div (Register rd, Register rs1, Register rs2)
Definition at line 26 of file extension-riscv-m.cc.
                                                                 {
  GenInstrALU_rr(0b0000001, 0b100, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
divu()
void v8::internal::AssemblerRISCVM::divu (Register rd, Register rs1, Register rs2)
Definition at line 30 of file extension-riscv-m.cc.
                                                                  {
  GenInstrALU_rr(0b0000001, 0b101, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
mul()
void v8::internal::AssemblerRISCVM::mul (Register rd, Register rs1, Register rs2)
Definition at line 10 of file extension-riscv-m.cc.
                                                                 {
  GenInstrALU_rr(0b0000001, 0b000, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
mulh()
void v8::internal::AssemblerRISCVM::mulh (Register rd, Register rs1, Register rs2)
Definition at line 14 of file extension-riscv-m.cc.
                                                                  {
  GenInstrALU_rr(0b0000001, 0b001, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
mulhsu()
void v8::internal::AssemblerRISCVM::mulhsu (Register rd, Register rs1, Register rs2)
Definition at line 18 of file extension-riscv-m.cc.
                                                                    {
  GenInstrALU_rr(0b0000001, 0b010, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
mulhu()
void v8::internal::AssemblerRISCVM::mulhu (Register rd, Register rs1, Register rs2)
Definition at line 22 of file extension-riscv-m.cc.
                                                                   {
  GenInstrALU_rr(0b0000001, 0b011, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
rem()
void v8::internal::AssemblerRISCVM::rem (Register rd, Register rs1, Register rs2)
Definition at line 34 of file extension-riscv-m.cc.
                                                                 {
  GenInstrALU_rr(0b0000001, 0b110, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
remu()
void v8::internal::AssemblerRISCVM::remu (Register rd, Register rs1, Register rs2)
Definition at line 38 of file extension-riscv-m.cc.
                                                                  {
  GenInstrALU_rr(0b0000001, 0b111, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-m.h
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-m.cc