v8::internal::SourceTextModule Class Reference
#include <source-text-module.h>
Classes
struct AsyncEvaluationOrdinalCompare
Public Types
enum ExecuteAsyncModuleContextSlots { kModule = Context::MIN_CONTEXT_SLOTS
, kContextLength
 }
using BodyDescriptor = SubclassBodyDescriptor< Module::BodyDescriptor, FixedBodyDescriptor< kCodeOffset, kSize, kSize > >
Public Member Functions
Tagged< SharedFunctionInfo > GetSharedFunctionInfo () const
Tagged< Script > GetScript () const
Tagged< SourceTextModuleInfo > info () const
Tagged< Cell > GetCell (int cell_index)
V8_EXPORT_PRIVATE std::pair< DirectHandleVector< SourceTextModule >, DirectHandleVector< JSMessageObject > > GetStalledTopLevelAwaitMessages (Isolate *isolate)
Static Public Member Functions
static Handle< Object > LoadVariable (Isolate *isolate, DirectHandle< SourceTextModule > module, int cell_index)
static void StoreVariable (DirectHandle< SourceTextModule > module, int cell_index, DirectHandle< Object > value)
static int ImportIndex (int cell_index)
static int ExportIndex (int cell_index)
static Maybe< bool > AsyncModuleExecutionFulfilled (Isolate *isolate, Handle< SourceTextModule > module)
static void AsyncModuleExecutionRejected (Isolate *isolate, DirectHandle< SourceTextModule > module, DirectHandle< Object > exception)
static DirectHandle< JSModuleNamespace > GetModuleNamespace (Isolate *isolate, DirectHandle< SourceTextModule > module, int module_request)
static V8_EXPORT_PRIVATE MaybeHandle< JSObject > GetImportMeta (Isolate *isolate, DirectHandle< SourceTextModule > module)
Static Public Attributes
static constexpr unsigned kFirstAsyncEvaluationOrdinal = 2
Private Types
using AvailableAncestorsSet = ZoneSet< Handle< SourceTextModule >, AsyncEvaluationOrdinalCompare >
Private Member Functions
Handle< SourceTextModule > GetCycleRoot (Isolate *isolate) const
Handle< SourceTextModule > GetAsyncParentModule (Isolate *isolate, int index)
int AsyncParentModuleCount ()
bool HasAsyncEvaluationOrdinal () const
bool HasPendingAsyncDependencies ()
void IncrementPendingAsyncDependencies ()
void DecrementPendingAsyncDependencies ()
bool MaybeHandleEvaluationException (Isolate *isolate, ZoneForwardList< Handle< SourceTextModule >> *stack)
V8_EXPORT_PRIVATE void InnerGetStalledTopLevelAwaitModule (Isolate *isolate, UnorderedModuleSet *visited, DirectHandleVector< SourceTextModule > *result)
Static Private Member Functions
static void AddAsyncParentModule (Isolate *isolate, DirectHandle< SourceTextModule > module, DirectHandle< SourceTextModule > parent)
static void CreateExport (Isolate *isolate, DirectHandle< SourceTextModule > module, int cell_index, DirectHandle< FixedArray > names)
static void CreateIndirectExport (Isolate *isolate, DirectHandle< SourceTextModule > module, DirectHandle< String > name, DirectHandle< SourceTextModuleInfoEntry > entry)
static V8_WARN_UNUSED_RESULT MaybeHandle< Cell > ResolveExport (Isolate *isolate, Handle< SourceTextModule > module, DirectHandle< String > module_specifier, Handle< String > export_name, MessageLocation loc, bool must_resolve, ResolveSet *resolve_set)
static V8_WARN_UNUSED_RESULT MaybeHandle< Cell > ResolveImport (Isolate *isolate, DirectHandle< SourceTextModule > module, Handle< String > name, int module_request_index, MessageLocation loc, bool must_resolve, ResolveSet *resolve_set)
static V8_WARN_UNUSED_RESULT MaybeHandle< Cell > ResolveExportUsingStarExports (Isolate *isolate, DirectHandle< SourceTextModule > module, DirectHandle< String > module_specifier, Handle< String > export_name, MessageLocation loc, bool must_resolve, ResolveSet *resolve_set)
static V8_WARN_UNUSED_RESULT bool PrepareInstantiate (Isolate *isolate, DirectHandle< SourceTextModule > module, v8::Local< v8::Context > context, v8::Module::ResolveModuleCallback module_callback, v8::Module::ResolveSourceCallback source_callback)
static V8_WARN_UNUSED_RESULT bool FinishInstantiate (Isolate *isolate, Handle< SourceTextModule > module, ZoneForwardList< Handle< SourceTextModule >> *stack, unsigned *dfs_index, Zone *zone)
static V8_WARN_UNUSED_RESULT bool RunInitializationCode (Isolate *isolate, DirectHandle< SourceTextModule > module)
static void FetchStarExports (Isolate *isolate, Handle< SourceTextModule > module, Zone *zone, UnorderedModuleSet *visited)
static void GatherAvailableAncestors (Isolate *isolate, Zone *zone, Handle< SourceTextModule > start, AvailableAncestorsSet *exec_list)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Evaluate (Isolate *isolate, Handle< SourceTextModule > module)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > InnerModuleEvaluation (Isolate *isolate, Handle< SourceTextModule > module, ZoneForwardList< Handle< SourceTextModule >> *stack, unsigned *dfs_index)
static V8_WARN_UNUSED_RESULT bool MaybeTransitionComponent (Isolate *isolate, DirectHandle< SourceTextModule > module, ZoneForwardList< Handle< SourceTextModule >> *stack, Status new_status)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > InnerExecuteAsyncModule (Isolate *isolate, DirectHandle< SourceTextModule > module, DirectHandle< JSPromise > capability)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > ExecuteModule (Isolate *isolate, DirectHandle< SourceTextModule > module, MaybeDirectHandle< Object > *exception_out)
static V8_WARN_UNUSED_RESULT Maybe< bool > ExecuteAsyncModule (Isolate *isolate, DirectHandle< SourceTextModule > module)
static void Reset (Isolate *isolate, DirectHandle< SourceTextModule > module)
Static Private Attributes
static constexpr unsigned kNotAsyncEvaluated = 0
static constexpr unsigned kAsyncEvaluateDidFinish = 1
Friends
class Factory
class Module
Detailed Description
Definition at line 28 of file source-text-module.h.
Member Typedef Documentation
AvailableAncestorsSet
using v8::internal::SourceTextModule::AvailableAncestorsSet = ZoneSet<Handle<SourceTextModule>, AsyncEvaluationOrdinalCompare> [private]
Definition at line 98 of file source-text-module.h.
BodyDescriptor
using v8::internal::SourceTextModule::BodyDescriptor = SubclassBodyDescriptor<Module::BodyDescriptor, FixedBodyDescriptor<kCodeOffset, kSize, kSize> >
Definition at line 77 of file source-text-module.h.
Member Enumeration Documentation
ExecuteAsyncModuleContextSlots
enum v8::internal::SourceTextModule::ExecuteAsyncModuleContextSlots
Enumerator
kModule
kContextLength
Definition at line 83 of file source-text-module.h.
                                      {
    kModule = Context::MIN_CONTEXT_SLOTS,
    kContextLength,
  };
Member Function Documentation
AddAsyncParentModule()
void v8::internal::SourceTextModule::AddAsyncParentModule (Isolate * isolate, DirectHandle< SourceTextModule > module, DirectHandle< SourceTextModule > parent) [inline], [static], [private]
Definition at line 121 of file module-inl.h.
                                           {
  DirectHandle<ArrayList> async_parent_modules(module->async_parent_modules(),
                                               isolate);
  DirectHandle<ArrayList> new_array_list =
      ArrayList::Add(isolate, async_parent_modules, parent);
  module->set_async_parent_modules(*new_array_list);
}
References v8::internal::ArrayList::Add().
Referenced by InnerModuleEvaluation().
AsyncModuleExecutionFulfilled()
Maybe< bool > v8::internal::SourceTextModule::AsyncModuleExecutionFulfilled (Isolate * isolate, Handle< SourceTextModule > module) [static]
Definition at line 886 of file source-text-module.cc.
                                                       {
  // 1. If module.[[Status]] is EVALUATED, then
  if (module->status() == kErrored) {
    // a. Assert: module.[[EvaluationError]] is not EMPTY.
    DCHECK(!IsTheHole(module->exception(), isolate));
    // b. Return UNUSED.
    return Just(true);
  }
  // 2. Assert: module.[[Status]] is EVALUATING-ASYNC.
  DCHECK_EQ(module->status(), kEvaluatingAsync);
  // 3. Assert: module.[[AsyncEvaluation]] is true.
  DCHECK(module->HasAsyncEvaluationOrdinal());
  // 4. Assert: module.[[EvaluationError]] is EMPTY.
  // (Done by step 2.)
  // 5. Set module.[[AsyncEvaluation]] to false.
  module->set_async_evaluation_ordinal(kAsyncEvaluateDidFinish);
  // 6. Set module.[[Status]] to EVALUATED.
  module->SetStatus(kEvaluated);
  // 7. If module.[[TopLevelCapability]] is not EMPTY, then
  if (!IsUndefined(module->top_level_capability(), isolate)) {
    // a. Assert: module.[[CycleRoot]] is equal to module.
    DCHECK_EQ(*module->GetCycleRoot(isolate), *module);
    // i. Perform ! Call(module.[[TopLevelCapability]].[[Resolve]], undefined,
    // «undefined»).
    DirectHandle<JSPromise> capability(
        Cast<JSPromise>(module->top_level_capability()), isolate);
    JSPromise::Resolve(capability, isolate->factory()->undefined_value())
        .ToHandleChecked();
  }
  // 8. Let execList be a new empty List.
  Zone zone(isolate->allocator(), ZONE_NAME);
  AvailableAncestorsSet exec_list(&zone);
  // 9. Perform GatherAvailableAncestors(module, execList).
  GatherAvailableAncestors(isolate, &zone, module, &exec_list);
  // 10. Let sortedExecList be a List of elements that are the elements of
  // execList, in the order in which they had their [[AsyncEvaluation]]
  // fields set to true in InnerModuleEvaluation.
  //
  // This step is implemented by AvailableAncestorsSet, which is a set
  // ordered on async_evaluation_ordinal.
  // 11. Assert: All elements of sortedExecList have their [[AsyncEvaluation]]
  // field set to true, [[PendingAsyncDependencies]] field set to 0 and
  // [[EvaluationError]] field set to undefined.
#ifdef DEBUG
  for (DirectHandle<SourceTextModule> m : exec_list) {
    DCHECK(m->HasAsyncEvaluationOrdinal());
    DCHECK(!m->HasPendingAsyncDependencies());
    DCHECK_NE(m->status(), kErrored);
  }
#endif
  // 12. For each Module m of sortedExecList, do
  for (DirectHandle<SourceTextModule> m : exec_list) {
    if (m->status() == kErrored) { // a. If m.[[Status]] is EVALUATED, then
      // i. Assert: m.[[EvaluationError]] is not EMPTY.
      DCHECK(!IsTheHole(m->exception(), isolate));
    } else if (m->has_toplevel_await()) { // b. Else if m.[[HasTLA]] is true,
                                           // then
      // i. Perform ExecuteAsyncModule(m).
      //
      // The execution may have been terminated and can not be resumed, so just
      // raise the exception.
      MAYBE_RETURN(ExecuteAsyncModule(isolate, m), Nothing<bool>());
    } else { // c. Else,
      // i. Let result be m.ExecuteModule().
      DirectHandle<Object> unused_result;
      MaybeDirectHandle<Object> exception;
      // ii. If result is an abrupt completion, then
      if (!ExecuteModule(isolate, m, &exception).ToHandle(&unused_result)) {
        // 1. Perform AsyncModuleExecutionRejected(m, result.[[Value]]).
        AsyncModuleExecutionRejected(isolate, m, exception.ToHandleChecked());
      } else { // iii. Else,
        // 1. Set m.[[AsyncEvaluation]] to false.
        m->set_async_evaluation_ordinal(kAsyncEvaluateDidFinish);
        // 2. Set m.[[Status]] to EVALUATED.
        m->SetStatus(kEvaluated);
        // 3. If m.[[TopLevelCapability]] is not EMPTY, then
        if (!IsUndefined(m->top_level_capability(), isolate)) {
          // a. Assert: m.[[CycleRoot]] and m are the same Module Record.
          DCHECK_EQ(*m->GetCycleRoot(isolate), *m);
          // b. Perform ! Call(m.[[TopLevelCapability]].[[Resolve]], undefined,
          // « undefined »).
          DirectHandle<JSPromise> capability(
              Cast<JSPromise>(m->top_level_capability()), isolate);
          JSPromise::Resolve(capability, isolate->factory()->undefined_value())
              .ToHandleChecked();
        }
      }
    }
  }
  // Return UNUSED.
  return Just(true);
}
References v8::internal::Isolate::allocator(), AsyncModuleExecutionRejected(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, ExecuteAsyncModule(), ExecuteModule(), v8::internal::Isolate::factory(), GatherAvailableAncestors(), v8::Just(), kAsyncEvaluateDidFinish, MAYBE_RETURN, v8::internal::JSPromise::Resolve(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::MaybeDirectHandle< T >::ToHandleChecked(), and ZONE_NAME.
Referenced by v8::internal::BUILTIN().
AsyncModuleExecutionRejected()
void v8::internal::SourceTextModule::AsyncModuleExecutionRejected (Isolate * isolate, DirectHandle< SourceTextModule > module, DirectHandle< Object > exception) [static]
Definition at line 997 of file source-text-module.cc.
                                    {
  // 1. If module.[[Status]] is EVALUATED, then
  if (module->status() == kErrored) {
    // a. Assert: module.[[EvaluationError]] is not empty.
    DCHECK(!IsTheHole(module->exception(), isolate));
    // b. Return UNUSED.
    return;
  }
  DCHECK(isolate->is_catchable_by_javascript(*exception));
  // 2. Assert: module.[[Status]] is EVALUATING-ASYNC.
  CHECK_EQ(module->status(), kEvaluatingAsync);
  // 3. Assert: module.[[AsyncEvaluation]] is true.
  DCHECK(module->HasAsyncEvaluationOrdinal());
  // 4. Assert: module.[[EvaluationError]] is EMPTY.
  DCHECK(IsTheHole(module->exception(), isolate));
  // 5. Set module.[[EvaluationError]] to ThrowCompletion(error).
  module->RecordError(isolate, *exception);
  // 6. Set module.[[Status]] to EVALUATED.
  // (We have a status for kErrored, so don't set to kEvaluated.)
  module->set_async_evaluation_ordinal(kAsyncEvaluateDidFinish);
  // 7. For each Cyclic Module Record m of module.[[AsyncParentModules]], do
  for (int i = 0; i < module->AsyncParentModuleCount(); i++) {
    // a. Perform AsyncModuleExecutionRejected(m, error).
    DirectHandle<SourceTextModule> m = module->GetAsyncParentModule(isolate, i);
    AsyncModuleExecutionRejected(isolate, m, exception);
  }
  // 8. If module.[[TopLevelCapability]] is not EMPTY, then
  if (!IsUndefined(module->top_level_capability(), isolate)) {
    // a. Assert: module.[[CycleRoot]] and module are the same Module Record.
    DCHECK_EQ(*module->GetCycleRoot(isolate), *module);
    // b. Perform ! Call(module.[[TopLevelCapability]].[[Reject]],
    // undefined, «error»).
    DirectHandle<JSPromise> capability(
        Cast<JSPromise>(module->top_level_capability()), isolate);
    JSPromise::Reject(capability, exception);
  }
  // 9. Return UNUSED.
}
References CHECK_EQ, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::is_catchable_by_javascript(), kAsyncEvaluateDidFinish, and v8::internal::JSPromise::Reject().
Referenced by AsyncModuleExecutionFulfilled(), and v8::internal::BUILTIN().
AsyncParentModuleCount()
int v8::internal::SourceTextModule::AsyncParentModuleCount () [inline], [private]
Definition at line 138 of file module-inl.h.
                                             {
  return async_parent_modules()->length();
}
CreateExport()
void v8::internal::SourceTextModule::CreateExport (Isolate * isolate, DirectHandle< SourceTextModule > module, int cell_index, DirectHandle< FixedArray > names) [static], [private]
Definition at line 135 of file source-text-module.cc.
                                                                    {
  DCHECK_LT(0, names->length());
  DirectHandle<Cell> cell = isolate->factory()->NewCell();
  module->regular_exports()->set(ExportIndex(cell_index), *cell);
  Handle<ObjectHashTable> exports(module->exports(), isolate);
  for (int i = 0, n = names->length(); i < n; ++i) {
    DirectHandle<String> name(Cast<String>(names->get(i)), isolate);
    DCHECK(IsTheHole(exports->Lookup(name), isolate));
    exports = ObjectHashTable::Put(exports, name, cell);
  }
  module->set_exports(*exports);
}
References v8::internal::DCHECK(), DCHECK_LT, ExportIndex(), v8::internal::Isolate::factory(), v8::internal::name, and v8::internal::Factory::NewCell().
Referenced by PrepareInstantiate().
CreateIndirectExport()
void v8::internal::SourceTextModule::CreateIndirectExport (Isolate * isolate, DirectHandle< SourceTextModule > module, DirectHandle< String > name, DirectHandle< SourceTextModuleInfoEntry > entry) [static], [private]
Definition at line 126 of file source-text-module.cc.
                                                                              {
  Handle<ObjectHashTable> exports(module->exports(), isolate);
  DCHECK(IsTheHole(exports->Lookup(name), isolate));
  exports = ObjectHashTable::Put(exports, name, entry);
  module->set_exports(*exports);
}
References v8::internal::DCHECK(), and v8::internal::name.
Referenced by PrepareInstantiate().
DecrementPendingAsyncDependencies()
void v8::internal::SourceTextModule::DecrementPendingAsyncDependencies () [inline], [private]
Definition at line 155 of file module-inl.h.
                                                         {
  set_pending_async_dependencies(pending_async_dependencies() - 1);
}
Evaluate()
MaybeDirectHandle< Object > v8::internal::SourceTextModule::Evaluate (Isolate * isolate, Handle< SourceTextModule > module) [static], [private]
Definition at line 833 of file source-text-module.cc.
                                                       {
  CHECK(module->status() == kLinked || module->status() == kEvaluatingAsync ||
        module->status() == kEvaluated);
  // 5. Let stack be a new empty List.
  Zone zone(isolate->allocator(), ZONE_NAME);
  ZoneForwardList<Handle<SourceTextModule>> stack(&zone);
  unsigned dfs_index = 0;
  // 6. Let capability be ! NewPromiseCapability(%Promise%).
  DirectHandle<JSPromise> capability = isolate->factory()->NewJSPromise();
  // 7. Set module.[[TopLevelCapability]] to capability.
  module->set_top_level_capability(*capability);
  DCHECK(IsJSPromise(module->top_level_capability()));
  // 8. Let result be InnerModuleEvaluation(module, stack, 0).
  // 9. If result is an abrupt completion, then
  v8::TryCatch try_catch(reinterpret_cast<v8::Isolate*>(isolate));
  try_catch.SetVerbose(false);
  try_catch.SetCaptureMessage(false);
  // TODO(verwaest): Return a bool from InnerModuleEvaluation instead?
  if (InnerModuleEvaluation(isolate, module, &stack, &dfs_index).is_null()) {
    if (!module->MaybeHandleEvaluationException(isolate, &stack)) return {};
    CHECK(try_catch.HasCaught());
    // d. Perform ! Call(capability.[[Reject]], undefined,
    // «result.[[Value]]»).
    JSPromise::Reject(capability, direct_handle(module->exception(), isolate));
  } else { // 10. Else,
    // a. Assert: module.[[Status]] is either EVALUATING-ASYNC or EVALUATED.
    CHECK_GE(module->status(), kEvaluatingAsync);
    // c. If module.[[AsyncEvaluation]] is false, then
    if (!module->HasAsyncEvaluationOrdinal()) {
      // i. Assert: module.[[Status]] is EVALUATED.
      DCHECK_EQ(module->status(), kEvaluated);
      // ii. Perform ! Call(capability.[[Resolve]], undefined,
      // «undefined»).
      JSPromise::Resolve(capability, isolate->factory()->undefined_value())
          .ToHandleChecked();
    }
    // d. Assert: stack is empty.
    DCHECK(stack.empty());
  }
  // 11. Return capability.[[Promise]].
  return capability;
}
References v8::internal::Isolate::allocator(), CHECK, CHECK_GE, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::TryCatch::HasCaught(), InnerModuleEvaluation(), v8::internal::Factory::NewJSPromise(), v8::internal::JSPromise::Reject(), v8::internal::JSPromise::Resolve(), v8::TryCatch::SetCaptureMessage(), v8::TryCatch::SetVerbose(), v8::internal::stack, and ZONE_NAME.
Referenced by v8::internal::Module::Evaluate().
ExecuteAsyncModule()
Maybe< bool > v8::internal::SourceTextModule::ExecuteAsyncModule (Isolate * isolate, DirectHandle< SourceTextModule > module) [static], [private]
Definition at line 1046 of file source-text-module.cc.
                                                             {
  // 1. Assert: module.[[Status]] is either EVALUATING or EVALUATING-ASYNC.
  CHECK(module->status() == kEvaluating ||
        module->status() == kEvaluatingAsync);
  // 2. Assert: module.[[HasTLA]] is true.
  DCHECK(module->has_toplevel_await());
  // 3. Let capability be ! NewPromiseCapability(%Promise%).
  DirectHandle<JSPromise> capability = isolate->factory()->NewJSPromise();
  DirectHandle<Context> execute_async_module_context =
      isolate->factory()->NewBuiltinContext(
          isolate->native_context(),
          ExecuteAsyncModuleContextSlots::kContextLength);
  execute_async_module_context->SetNoCell(
      ExecuteAsyncModuleContextSlots::kModule, *module);
  // 4. Let fulfilledClosure be a new Abstract Closure with no parameters that
  // captures module and performs the following steps when called:
  // a. Perform AsyncModuleExecutionFulfilled(module).
  // b. Return undefined.
  // 5. Let onFulfilled be CreateBuiltinFunction(fulfilledClosure, 0, "", « »).
  DirectHandle<JSFunction> on_fulfilled =
      Factory::JSFunctionBuilder{
          isolate,
          isolate->factory()
              ->source_text_module_execute_async_module_fulfilled_sfi(),
          execute_async_module_context}
          .Build();
  // 6. Let rejectedClosure be a new Abstract Closure with parameters (error)
  // that captures module and performs the following steps when called:
  // a. Perform AsyncModuleExecutionRejected(module, error).
  // b. Return undefined.
  // 7. Let onRejected be CreateBuiltinFunction(rejectedClosure, 0, "", « »).
  DirectHandle<JSFunction> on_rejected =
      Factory::JSFunctionBuilder{
          isolate,
          isolate->factory()
              ->source_text_module_execute_async_module_rejected_sfi(),
          execute_async_module_context}
          .Build();
  // 8. Perform ! PerformPromiseThen(capability.[[Promise]],
  // onFulfilled, onRejected).
  DirectHandle<Object> args[] = {on_fulfilled, on_rejected};
  if (V8_UNLIKELY(Execution::CallBuiltin(isolate, isolate->promise_then(),
                                         capability, base::VectorOf(args))
                      .is_null())) {
    // TODO(349961173): We assume the builtin call can only fail with a
    // termination exception. If this check fails in the wild investigate why
    // the call fails. Otherwise turn this into a DCHECK in the future.
    CHECK(isolate->is_execution_terminating());
    return Nothing<bool>();
  }
  // 9. Perform ! module.ExecuteModule(capability).
  // Note: In V8 we have broken module.ExecuteModule into
  // ExecuteModule for synchronous module execution and
  // InnerExecuteAsyncModule for asynchronous execution.
  MaybeDirectHandle<Object> ret =
      InnerExecuteAsyncModule(isolate, module, capability);
  if (ret.is_null()) {
    // The evaluation of async module cannot throw a JavaScript observable
    // exception.
    DCHECK_IMPLIES(v8_flags.strict_termination_checks,
                   isolate->is_execution_terminating());
    return Nothing<bool>();
  }
  // 10. Return UNUSED.
  return Just<bool>(true);
}
References v8::base::args, v8::internal::Execution::CallBuiltin(), CHECK, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::Isolate::factory(), InnerExecuteAsyncModule(), v8::internal::Isolate::is_execution_terminating(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::Isolate::native_context(), v8::internal::Factory::NewBuiltinContext(), v8::internal::Factory::NewJSPromise(), v8::internal::v8_flags, V8_UNLIKELY, and v8::base::VectorOf().
Referenced by AsyncModuleExecutionFulfilled(), and InnerModuleEvaluation().
ExecuteModule()
MaybeDirectHandle< Object > v8::internal::SourceTextModule::ExecuteModule (Isolate * isolate, DirectHandle< SourceTextModule > module, MaybeDirectHandle< Object > * exception_out) [static], [private]
Definition at line 1137 of file source-text-module.cc.
                                              {
  // Synchronous modules have an associated JSGeneratorObject.
  DirectHandle<JSGeneratorObject> generator(
      Cast<JSGeneratorObject>(module->code()), isolate);
  DirectHandle<JSFunction> resume(
      isolate->native_context()->generator_next_internal(), isolate);
  DirectHandle<Object> result;
  if (!Execution::TryCall(isolate, resume, generator, {},
                          Execution::MessageHandling::kKeepPending,
                          exception_out)
           .ToHandle(&result)) {
    return {};
  }
  DCHECK(
      Object::BooleanValue(Cast<JSIteratorResult>(*result)->done(), isolate));
  return direct_handle(Cast<JSIteratorResult>(*result)->value(), isolate);
}
References v8::internal::Object::BooleanValue(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Execution::kKeepPending, v8::internal::Isolate::native_context(), v8::base::internal::result, v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::Execution::TryCall().
Referenced by AsyncModuleExecutionFulfilled(), and InnerModuleEvaluation().
ExportIndex()
int v8::internal::SourceTextModule::ExportIndex (int cell_index) [static]
Definition at line 114 of file source-text-module.cc.
                                                {
  DCHECK_EQ(SourceTextModuleDescriptor::GetCellIndexKind(cell_index),
            SourceTextModuleDescriptor::kExport);
  return cell_index - 1;
}
References DCHECK_EQ, v8::internal::SourceTextModuleDescriptor::GetCellIndexKind(), and v8::internal::SourceTextModuleDescriptor::kExport.
Referenced by CreateExport(), and GetCell().
FetchStarExports()
void v8::internal::SourceTextModule::FetchStarExports (Isolate * isolate, Handle< SourceTextModule > module, Zone * zone, UnorderedModuleSet * visited) [static], [private]
Definition at line 646 of file source-text-module.cc.
                                                                     {
  DCHECK_GE(module->status(), Module::kLinking);
  if (IsJSModuleNamespace(module->module_namespace())) return; // Shortcut.
  bool cycle = !visited->insert(module).second;
  if (cycle) return;
  Handle<ObjectHashTable> exports(module->exports(), isolate);
  UnorderedStringMap more_exports(zone);
  // TODO(neis): Only allocate more_exports if there are star exports.
  // Maybe split special_exports into indirect_exports and star_exports.
  ReadOnlyRoots roots(isolate);
  DirectHandle<FixedArray> special_exports(module->info()->special_exports(),
                                           isolate);
  for (int i = 0, n = special_exports->length(); i < n; ++i) {
    DirectHandle<SourceTextModuleInfoEntry> entry(
        Cast<SourceTextModuleInfoEntry>(special_exports->get(i)), isolate);
    if (!IsUndefined(entry->export_name(), roots)) {
      continue; // Indirect export.
    }
    DCHECK_EQ(Cast<ModuleRequest>(module->info()->module_requests()->get(
                                      entry->module_request()))
                  ->phase(),
              ModuleImportPhase::kEvaluation);
    Handle<Module> requested_module(
        Cast<Module>(module->requested_modules()->get(entry->module_request())),
        isolate);
    // Recurse.
    if (IsSourceTextModule(*requested_module))
      FetchStarExports(isolate, Cast<SourceTextModule>(requested_module), zone,
                       visited);
    // Collect all of [requested_module]'s exports that must be added to
    // [module]'s exports (i.e. to [exports]). We record these in
    // [more_exports]. Ambiguities (conflicting exports) are marked by mapping
    // the name to undefined instead of a Cell.
    DirectHandle<ObjectHashTable> requested_exports(requested_module->exports(),
                                                    isolate);
    for (InternalIndex index : requested_exports->IterateEntries()) {
      Tagged<Object> key;
      if (!requested_exports->ToKey(roots, index, &key)) continue;
      Handle<String> name(Cast<String>(key), isolate);
      if (name->Equals(roots.default_string())) continue;
      if (!IsTheHole(exports->Lookup(name), roots)) continue;
      Handle<Cell> cell(Cast<Cell>(requested_exports->ValueAt(index)), isolate);
      auto insert_result = more_exports.insert(std::make_pair(name, cell));
      if (!insert_result.second) {
        auto it = insert_result.first;
        if (*it->second == *cell || IsUndefined(*it->second, roots)) {
          // We already recorded this mapping before, or the name is already
          // known to be ambiguous. In either case, there's nothing to do.
        } else {
          DCHECK(IsCell(*it->second));
          // Different star exports provide different cells for this name, hence
          // mark the name as ambiguous.
          it->second = isolate->factory()->undefined_value();
        }
      }
    }
  }
  // Copy [more_exports] into [exports].
  for (const auto& elem : more_exports) {
    if (IsUndefined(*elem.second, isolate)) continue; // Ambiguous export.
    DCHECK(!elem.first->Equals(ReadOnlyRoots(isolate).default_string()));
    DCHECK(IsCell(*elem.second));
    exports = ObjectHashTable::Put(exports, elem.first, elem.second);
  }
  module->set_exports(*exports);
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::Isolate::factory(), v8::internal::index, v8::kEvaluation, v8::internal::key, v8::internal::Module::kLinking, and v8::internal::name.
Referenced by v8::internal::Module::GetModuleNamespace().
FinishInstantiate()
bool v8::internal::SourceTextModule::FinishInstantiate (Isolate * isolate, Handle< SourceTextModule > module, ZoneForwardList< Handle< SourceTextModule >> * stack, unsigned * dfs_index, Zone * zone) [static], [private]
Definition at line 551 of file source-text-module.cc.
                {
  // Instantiate SharedFunctionInfo and mark module as instantiating for
  // the recursion.
  DirectHandle<SharedFunctionInfo> shared(
      Cast<SharedFunctionInfo>(module->code()), isolate);
  DirectHandle<JSFunction> function =
      Factory::JSFunctionBuilder{isolate, shared, isolate->native_context()}
          .Build();
  module->set_code(*function);
  module->SetStatus(kLinking);
  module->set_dfs_index(*dfs_index);
  module->set_dfs_ancestor_index(*dfs_index);
  stack->push_front(module);
  (*dfs_index)++;
  // Recurse.
  DirectHandle<FixedArray> module_requests(module->info()->module_requests(),
                                           isolate);
  DirectHandle<FixedArray> requested_modules(module->requested_modules(),
                                             isolate);
  for (int i = 0, length = requested_modules->length(); i < length; ++i) {
    DirectHandle<ModuleRequest> module_request(
        Cast<ModuleRequest>(module_requests->get(i)), isolate);
    if (module_request->phase() != ModuleImportPhase::kEvaluation) {
      continue;
    }
    Handle<Module> requested_module(Cast<Module>(requested_modules->get(i)),
                                    isolate);
    if (!Module::FinishInstantiate(isolate, requested_module, stack, dfs_index,
                                   zone)) {
      return false;
    }
    DCHECK_NE(requested_module->status(), kEvaluating);
    DCHECK_GE(requested_module->status(), kLinking);
    SLOW_DCHECK(
        // {requested_module} is instantiating iff it's on the {stack}.
        (requested_module->status() == kLinking) ==
        std::count_if(
            stack->begin(), stack->end(),
            [&](DirectHandle<Module> m) { return *m == *requested_module; }));
    if (requested_module->status() == kLinking) {
      // SyntheticModules go straight to kLinked so this must be a
      // SourceTextModule
      module->set_dfs_ancestor_index(std::min(
          module->dfs_ancestor_index(),
          Cast<SourceTextModule>(*requested_module)->dfs_ancestor_index()));
    }
  }
  Handle<Script> script(module->GetScript(), isolate);
  DirectHandle<SourceTextModuleInfo> module_info(module->info(), isolate);
  // Resolve imports.
  DirectHandle<FixedArray> regular_imports(module_info->regular_imports(),
                                           isolate);
  for (int i = 0, n = regular_imports->length(); i < n; ++i) {
    DirectHandle<SourceTextModuleInfoEntry> entry(
        Cast<SourceTextModuleInfoEntry>(regular_imports->get(i)), isolate);
    Handle<String> name(Cast<String>(entry->import_name()), isolate);
    MessageLocation loc(script, entry->beg_pos(), entry->end_pos());
    ResolveSet resolve_set(zone);
    DirectHandle<Cell> cell;
    if (!ResolveImport(isolate, module, name, entry->module_request(), loc,
                       true, &resolve_set)
             .ToHandle(&cell)) {
      return false;
    }
    module->regular_imports()->set(ImportIndex(entry->cell_index()), *cell);
  }
  // Resolve indirect exports.
  DirectHandle<FixedArray> special_exports(module_info->special_exports(),
                                           isolate);
  for (int i = 0, n = special_exports->length(); i < n; ++i) {
    DirectHandle<SourceTextModuleInfoEntry> entry(
        Cast<SourceTextModuleInfoEntry>(special_exports->get(i)), isolate);
    Handle<Object> name(entry->export_name(), isolate);
    if (IsUndefined(*name, isolate)) continue; // Star export.
    MessageLocation loc(script, entry->beg_pos(), entry->end_pos());
    ResolveSet resolve_set(zone);
    if (ResolveExport(isolate, module, {}, Cast<String>(name), loc, true,
                      &resolve_set)
            .is_null()) {
      return false;
    }
  }
  return MaybeTransitionComponent(isolate, module, stack, kLinked);
}
References v8::base::count_if(), DCHECK_GE, DCHECK_NE, v8::internal::Module::FinishInstantiate(), ImportIndex(), v8::kEvaluation, v8::internal::length, v8::internal::loc, MaybeTransitionComponent(), v8::internal::name, v8::internal::Isolate::native_context(), ResolveExport(), ResolveImport(), v8::internal::script, SLOW_DCHECK, and v8::internal::stack.
Referenced by v8::internal::Module::FinishInstantiate().
GatherAvailableAncestors()
void v8::internal::SourceTextModule::GatherAvailableAncestors (Isolate * isolate, Zone * zone, Handle< SourceTextModule > start, AvailableAncestorsSet * exec_list) [static], [private]
Definition at line 726 of file source-text-module.cc.
                                      {
  // The spec algorithm is recursive. It is transformed to an equivalent
  // iterative one here.
  ZoneStack<Handle<SourceTextModule>> worklist(zone);
  worklist.push(start);
  while (!worklist.empty()) {
    DirectHandle<SourceTextModule> module = worklist.top();
    worklist.pop();
    // 1. For each Module m of module.[[AsyncParentModules]], do
    for (int i = module->AsyncParentModuleCount(); i-- > 0;) {
      Handle<SourceTextModule> m = module->GetAsyncParentModule(isolate, i);
      // a. If execList does not contain m and
      // m.[[CycleRoot]].[[EvaluationError]] is empty, then
      if (m->GetCycleRoot(isolate)->status() != kErrored &&
          exec_list->find(m) == exec_list->end()) {
        // i. Assert: m.[[Status]] is EVALUATING-ASYNC.
        // ii. Assert: m.[[EvaluationError]] is empty.
        DCHECK_EQ(m->status(), kEvaluatingAsync);
        // iii. Assert: m.[[AsyncEvaluation]] is true.
        DCHECK(m->HasAsyncEvaluationOrdinal());
        // iv. Assert: m.[[PendingAsyncDependencies]] > 0.
        DCHECK(m->HasPendingAsyncDependencies());
        // v. Set m.[[PendingAsyncDependencies]] to
        // m.[[PendingAsyncDependencies]] - 1.
        m->DecrementPendingAsyncDependencies();
        // vi. If m.[[PendingAsyncDependencies]] = 0, then
        if (!m->HasPendingAsyncDependencies()) {
          // 1. Append m to execList.
          exec_list->insert(m);
          // 2. If m.[[HasTLA]] is false,
          // perform ! GatherAvailableAncestors(m, execList).
          if (!m->has_toplevel_await()) worklist.push(m);
        }
      }
    }
  }
  // 2. Return UNUSED.
}
References v8::internal::DCHECK(), and DCHECK_EQ.
Referenced by AsyncModuleExecutionFulfilled().
GetAsyncParentModule()
Handle< SourceTextModule > v8::internal::SourceTextModule::GetAsyncParentModule (Isolate * isolate, int index) [inline], [private]
Definition at line 131 of file module-inl.h.
                                 {
  Handle<SourceTextModule> module(
      Cast<SourceTextModule>(async_parent_modules()->get(index)), isolate);
  return module;
}
References v8::internal::index.
GetCell()
Tagged< Cell > v8::internal::SourceTextModule::GetCell (int cell_index)
Definition at line 152 of file source-text-module.cc.
                                                     {
  DisallowGarbageCollection no_gc;
  Tagged<Object> cell;
  switch (SourceTextModuleDescriptor::GetCellIndexKind(cell_index)) {
    case SourceTextModuleDescriptor::kImport:
      cell = regular_imports()->get(ImportIndex(cell_index));
      break;
    case SourceTextModuleDescriptor::kExport:
      cell = regular_exports()->get(ExportIndex(cell_index));
      break;
    case SourceTextModuleDescriptor::kInvalid:
      UNREACHABLE();
  }
  return Cast<Cell>(cell);
}
References ExportIndex(), v8::internal::SourceTextModuleDescriptor::GetCellIndexKind(), ImportIndex(), v8::internal::SourceTextModuleDescriptor::kExport, v8::internal::SourceTextModuleDescriptor::kImport, v8::internal::SourceTextModuleDescriptor::kInvalid, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::UNREACHABLE().
GetCycleRoot()
Handle< SourceTextModule > v8::internal::SourceTextModule::GetCycleRoot (Isolate * isolate) const [inline], [private]
Definition at line 113 of file module-inl.h.
                            {
  CHECK_GE(status(), kEvaluatingAsync);
  DCHECK(!IsTheHole(cycle_root(), isolate));
  Handle<SourceTextModule> root(Cast<SourceTextModule>(cycle_root()), isolate);
  return root;
}
References CHECK_GE, v8::internal::DCHECK(), and v8::internal::status.
GetImportMeta()
MaybeHandle< JSObject > v8::internal::SourceTextModule::GetImportMeta (Isolate * isolate, DirectHandle< SourceTextModule > module) [static]
Definition at line 788 of file source-text-module.cc.
                                                             {
  Handle<UnionOf<JSObject, Hole>> import_meta(module->import_meta(kAcquireLoad),
                                              isolate);
  if (IsTheHole(*import_meta, isolate)) {
    if (!isolate->RunHostInitializeImportMetaObjectCallback(module).ToHandle(
            &import_meta)) {
      return {};
    }
    module->set_import_meta(*import_meta, kReleaseStore);
  }
  return Cast<JSObject>(import_meta);
}
References v8::kAcquireLoad, v8::kReleaseStore, and v8::internal::Isolate::RunHostInitializeImportMetaObjectCallback().
Referenced by v8::internal::RUNTIME_FUNCTION().
GetModuleNamespace()
DirectHandle< JSModuleNamespace > v8::internal::SourceTextModule::GetModuleNamespace (Isolate * isolate, DirectHandle< SourceTextModule > module, int module_request) [static]
Definition at line 776 of file source-text-module.cc.
                        {
  DCHECK_EQ(Cast<ModuleRequest>(
                module->info()->module_requests()->get(module_request))
                ->phase(),
            ModuleImportPhase::kEvaluation);
  Handle<Module> requested_module(
      Cast<Module>(module->requested_modules()->get(module_request)), isolate);
  return Module::GetModuleNamespace(isolate, requested_module);
}
References DCHECK_EQ, v8::internal::Module::GetModuleNamespace(), and v8::kEvaluation.
Referenced by v8::internal::RUNTIME_FUNCTION().
GetScript()
Tagged< Script > v8::internal::SourceTextModule::GetScript () const
Definition at line 109 of file source-text-module.cc.
                                                 {
  DisallowGarbageCollection no_gc;
  return Cast<Script>(GetSharedFunctionInfo()->script());
}
References GetSharedFunctionInfo(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::script.
GetSharedFunctionInfo()
Tagged< SharedFunctionInfo > v8::internal::SourceTextModule::GetSharedFunctionInfo () const
Definition at line 90 of file source-text-module.cc.
                                                                         {
  DisallowGarbageCollection no_gc;
  switch (status()) {
    case kUnlinked:
    case kPreLinking:
      return Cast<SharedFunctionInfo>(code());
    case kLinking:
      return Cast<JSFunction>(code())->shared();
    case kLinked:
    case kEvaluating:
    case kEvaluatingAsync:
    case kEvaluated:
      return Cast<JSGeneratorObject>(code())->function()->shared();
    case kErrored:
      return Cast<SharedFunctionInfo>(code());
  }
  UNREACHABLE();
}
References code, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::status, and v8::internal::UNREACHABLE().
Referenced by GetScript(), and info().
GetStalledTopLevelAwaitMessages()
std::pair< DirectHandleVector< SourceTextModule >, DirectHandleVector< JSMessageObject > > v8::internal::SourceTextModule::GetStalledTopLevelAwaitMessages (Isolate * isolate)
Definition at line 1367 of file source-text-module.cc.
                                                                  {
  Zone zone(isolate->allocator(), ZONE_NAME);
  UnorderedModuleSet visited(&zone);
  DirectHandleVector<SourceTextModule> stalled_modules(isolate);
  DirectHandleVector<JSMessageObject> messages(isolate);
  InnerGetStalledTopLevelAwaitModule(isolate, &visited, &stalled_modules);
  size_t stalled_modules_size = stalled_modules.size();
  if (stalled_modules_size == 0) return {stalled_modules, messages};
  messages.reserve(stalled_modules_size);
  for (DirectHandle<SourceTextModule> found : stalled_modules) {
    CHECK(IsJSGeneratorObject(found->code()));
    DirectHandle<JSGeneratorObject> code(Cast<JSGeneratorObject>(found->code()),
                                         isolate);
    Handle<SharedFunctionInfo> shared(found->GetSharedFunctionInfo(), isolate);
    Handle<Object> script(shared->script(), isolate);
    MessageLocation location =
        MessageLocation(Cast<Script>(script), shared, code->code_offset());
    DirectHandle<JSMessageObject> message = MessageHandler::MakeMessageObject(
        isolate, MessageTemplate::kTopLevelAwaitStalled, &location,
        isolate->factory()->null_value());
    messages.push_back(message);
  }
  return {stalled_modules, messages};
}
References v8::internal::Isolate::allocator(), CHECK, code, v8::internal::Isolate::factory(), InnerGetStalledTopLevelAwaitModule(), v8::internal::MessageHandler::MakeMessageObject(), v8::internal::DirectHandleVector< T >::push_back(), v8::internal::DirectHandleVector< T >::reserve(), v8::internal::script, v8::internal::DirectHandleVector< T >::size(), and ZONE_NAME.
HasAsyncEvaluationOrdinal()
bool v8::internal::SourceTextModule::HasAsyncEvaluationOrdinal () const [inline], [private]
Definition at line 142 of file module-inl.h.
                                                       {
  return async_evaluation_ordinal() >= kFirstAsyncEvaluationOrdinal;
}
References v8::internal::async_evaluation_ordinal, and kFirstAsyncEvaluationOrdinal.
Referenced by InnerGetStalledTopLevelAwaitModule().
HasPendingAsyncDependencies()
bool v8::internal::SourceTextModule::HasPendingAsyncDependencies () [inline], [private]
Definition at line 146 of file module-inl.h.
                                                   {
  DCHECK_GE(pending_async_dependencies(), 0);
  return pending_async_dependencies() > 0;
}
References DCHECK_GE.
Referenced by InnerGetStalledTopLevelAwaitModule().
ImportIndex()
int v8::internal::SourceTextModule::ImportIndex (int cell_index) [static]
Definition at line 120 of file source-text-module.cc.
                                                {
  DCHECK_EQ(SourceTextModuleDescriptor::GetCellIndexKind(cell_index),
            SourceTextModuleDescriptor::kImport);
  return -cell_index - 1;
}
References DCHECK_EQ, v8::internal::SourceTextModuleDescriptor::GetCellIndexKind(), and v8::internal::SourceTextModuleDescriptor::kImport.
Referenced by FinishInstantiate(), and GetCell().
IncrementPendingAsyncDependencies()
void v8::internal::SourceTextModule::IncrementPendingAsyncDependencies () [inline], [private]
Definition at line 151 of file module-inl.h.
                                                         {
  set_pending_async_dependencies(pending_async_dependencies() + 1);
}
info()
Tagged< SourceTextModuleInfo > v8::internal::SourceTextModule::info () const [inline]
Definition at line 55 of file module-inl.h.
                                                          {
  return GetSharedFunctionInfo()->scope_info()->ModuleDescriptorInfo();
}
References GetSharedFunctionInfo().
Referenced by InnerGetStalledTopLevelAwaitModule().
InnerExecuteAsyncModule()
MaybeDirectHandle< Object > v8::internal::SourceTextModule::InnerExecuteAsyncModule (Isolate * isolate, DirectHandle< SourceTextModule > module, DirectHandle< JSPromise > capability) [static], [private]
Definition at line 1122 of file source-text-module.cc.
                                        {
  // If we have an async module, then it has an associated
  // JSAsyncFunctionObject, which we then evaluate with the passed in promise
  // capability.
  DirectHandle<JSAsyncFunctionObject> async_function_object(
      Cast<JSAsyncFunctionObject>(module->code()), isolate);
  async_function_object->set_promise(*capability);
  DirectHandle<JSFunction> resume(
      isolate->native_context()->async_module_evaluate_internal(), isolate);
  return Execution::TryCall(isolate, resume, async_function_object, {},
                            Execution::MessageHandling::kKeepPending, nullptr);
}
References v8::internal::Execution::kKeepPending, v8::internal::Isolate::native_context(), and v8::internal::Execution::TryCall().
Referenced by ExecuteAsyncModule().
InnerGetStalledTopLevelAwaitModule()
void v8::internal::SourceTextModule::InnerGetStalledTopLevelAwaitModule (Isolate * isolate, UnorderedModuleSet * visited, DirectHandleVector< SourceTextModule > * result) [private]
Definition at line 1393 of file source-text-module.cc.
                                                  {
  DisallowGarbageCollection no_gc;
  // If it's a module that is waiting for no other modules but itself,
  // it's what we are looking for. Add it to the results.
  if (!HasPendingAsyncDependencies() && HasAsyncEvaluationOrdinal()) {
    DCHECK(HasAsyncEvaluationOrdinal());
    result->push_back(direct_handle(*this, isolate));
    return;
  }
  // The module isn't what we are looking for, continue looking in the graph.
  Tagged<FixedArray> requests = info()->module_requests();
  Tagged<FixedArray> requested = requested_modules();
  int length = requested->length();
  for (int i = 0; i < length; ++i) {
    Tagged<ModuleRequest> request = Cast<ModuleRequest>(requests->get(i));
    if (request->phase() != ModuleImportPhase::kEvaluation) {
      continue;
    }
    Tagged<Module> requested_module = Cast<Module>(requested->get(i));
    if (IsSourceTextModule(requested_module) &&
        visited->insert(handle(requested_module, isolate)).second) {
      Tagged<SourceTextModule> source_text_module =
          Cast<SourceTextModule>(requested_module);
      source_text_module->InnerGetStalledTopLevelAwaitModule(isolate, visited,
                                                             result);
    }
  }
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::handle(), HasAsyncEvaluationOrdinal(), HasPendingAsyncDependencies(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, info(), v8::kEvaluation, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
Referenced by GetStalledTopLevelAwaitMessages().
InnerModuleEvaluation()
MaybeDirectHandle< Object > v8::internal::SourceTextModule::InnerModuleEvaluation (Isolate * isolate, Handle< SourceTextModule > module, ZoneForwardList< Handle< SourceTextModule >> * stack, unsigned * dfs_index) [static], [private]
Definition at line 1158 of file source-text-module.cc.
                                                                           {
  STACK_CHECK(isolate, MaybeDirectHandle<Object>());
  int module_status = module->status();
  // InnerModuleEvaluation(module, stack, index)
  // 2. If module.[[Status]] is either EVALUATING-ASYNC or EVALUATED, then
  if (module_status == kEvaluatingAsync || module_status == kEvaluating ||
      module_status == kEvaluated) {
    // a. If module.[[EvaluationError]] is undefined, return index.
    // (We return undefined instead)
    //
    // 3. If module.[[Status]] is EVALUATING, return index.
    // (Out of order)
    return isolate->factory()->undefined_value();
  } else if (module_status == kErrored) {
    // b. Otherwise return module.[[EvaluationError]].
    // (We throw on isolate and return a MaybeHandle<Object> instead)
    isolate->Throw(module->exception());
    return MaybeDirectHandle<Object>();
  }
  // 4. Assert: module.[[Status]] is LINKED.
  CHECK_EQ(module_status, kLinked);
  DirectHandle<FixedArray> module_requests;
  DirectHandle<FixedArray> requested_modules;
  {
    DisallowGarbageCollection no_gc;
    Tagged<SourceTextModule> raw_module = *module;
    // 5. Set module.[[Status]] to EVALUATING.
    raw_module->SetStatus(kEvaluating);
    // 6. Set module.[[DFSIndex]] to index.
    raw_module->set_dfs_index(*dfs_index);
    // 7. Set module.[[DFSAncestorIndex]] to index.
    raw_module->set_dfs_ancestor_index(*dfs_index);
    // 8. Set module.[[PendingAsyncDependencies]] to 0.
    DCHECK(!raw_module->HasPendingAsyncDependencies());
    // 9. Set index to index + 1.
    (*dfs_index)++;
    // 10. Append module to stack.
    stack->push_front(module);
    // Recursion.
    module_requests =
        direct_handle(raw_module->info()->module_requests(), isolate);
    requested_modules = direct_handle(raw_module->requested_modules(), isolate);
  }
  // 11. For each ModuleRequest Record required of module.[[RequestedModules]],
  for (int i = 0, length = requested_modules->length(); i < length; ++i) {
    DirectHandle<ModuleRequest> module_request(
        Cast<ModuleRequest>(module_requests->get(i)), isolate);
    if (module_request->phase() != ModuleImportPhase::kEvaluation) {
      continue;
    }
    // b. If requiredModule.[[Phase]] is evaluation, then
    Handle<Module> requested_module(Cast<Module>(requested_modules->get(i)),
                                    isolate);
    // c. If requiredModule is a Cyclic Module Record, then
    if (IsSourceTextModule(*requested_module)) {
      // b. Set index to ? InnerModuleEvaluation(requiredModule, stack, index).
      // (Out of order because InnerModuleEvaluation is type-driven.)
      Handle<SourceTextModule> required_module(
          Cast<SourceTextModule>(*requested_module), isolate);
      RETURN_ON_EXCEPTION(
          isolate,
          InnerModuleEvaluation(isolate, required_module, stack, dfs_index));
      int required_module_status = required_module->status();
      // i. Assert: requiredModule.[[Status]] is one of EVALUATING,
      // EVALUATING-ASYNC, or EVALUATED.
      // (We also assert the module cannot be errored, because if it was
      // we would have already returned from InnerModuleEvaluation)
      CHECK_GE(required_module_status, kEvaluating);
      CHECK_NE(required_module_status, kErrored);
      // ii. Assert: requiredModule.[[Status]] is EVALUATING if and only if
      // requiredModule is in stack.
      SLOW_DCHECK((requested_module->status() == kEvaluating) ==
                  std::count_if(stack->begin(), stack->end(),
                                [&](DirectHandle<Module> m) {
                                  return *m == *requested_module;
                                }));
      // iii. If requiredModule.[[Status]] is EVALUATING, then
      if (required_module_status == kEvaluating) {
        // 1. Set module.[[DFSAncestorIndex]] to
        // min(module.[[DFSAncestorIndex]],
        // requiredModule.[[DFSAncestorIndex]]).
        module->set_dfs_ancestor_index(
            std::min(module->dfs_ancestor_index(),
                     required_module->dfs_ancestor_index()));
      } else { // iv. Else,
        // 1. Set requiredModule to requiredModule.[[CycleRoot]].
        required_module = required_module->GetCycleRoot(isolate);
        required_module_status = required_module->status();
        // 2. Assert: requiredModule.[[Status]] is either EVALUATING-ASYNC or
        // EVALUATED.
        CHECK_GE(required_module_status, kEvaluatingAsync);
        // 3. If requiredModule.[[EvaluationError]] is not EMPTY,
        // return ? module.[[EvaluationError]].
        // (If there was an exception on the original required module we would
        // have already returned. This check handles the case where the
        // AsyncCycleRoot has an error. Instead of returning the exception, we
        // throw on isolate and return a MaybeHandle<Object>.)
        if (required_module_status == kErrored) {
          isolate->Throw(required_module->exception());
          return MaybeDirectHandle<Object>();
        }
      }
      // v. If requiredModule.[[AsyncEvaluation]] is true, then
      if (required_module->HasAsyncEvaluationOrdinal()) {
        // 1. Set module.[[PendingAsyncDependencies]] to
        // module.[[PendingAsyncDependencies]] + 1.
        module->IncrementPendingAsyncDependencies();
        // 2. Append module to requiredModule.[[AsyncParentModules]].
        AddAsyncParentModule(isolate, required_module, module);
      }
    } else {
      // b. Set index to ? InnerModuleEvaluation(requiredModule, stack, index).
      // (Out of order because InnerModuleEvaluation is type-driven.)
      RETURN_ON_EXCEPTION(isolate, Module::Evaluate(isolate, requested_module));
    }
  }
  // The spec returns the module index for proper numbering of dependencies.
  // However, we pass the module index by pointer instead.
  //
  // Before async modules v8 returned the value result from calling next
  // on the module's implicit iterator. We preserve this behavior for
  // synchronous modules, but return undefined for AsyncModules.
  DirectHandle<Object> result = isolate->factory()->undefined_value();
  // 12. If module.[[PendingAsyncDependencies]] > 0 or module.[[HasTLA]] is
  // true, then
  if (module->HasPendingAsyncDependencies() || module->has_toplevel_await()) {
    // a. Assert: module.[[AsyncEvaluation]] is false and was never previously
    // set to true.
    DCHECK_EQ(module->async_evaluation_ordinal(), kNotAsyncEvaluated);
    // b. Set module.[[AsyncEvaluation]] to true.
    // c. NOTE: The order in which module records have their [[AsyncEvaluation]]
    // fields transition to true is significant.
    module->set_async_evaluation_ordinal(
        isolate->NextModuleAsyncEvaluationOrdinal());
    // c. If module.[[PendingAsyncDependencies]] = 0, perform
    // ExecuteAsyncModule(module).
    // The execution may have been terminated and can not be resumed, so just
    // raise the exception.
    if (!module->HasPendingAsyncDependencies()) {
      MAYBE_RETURN(SourceTextModule::ExecuteAsyncModule(isolate, module),
                   MaybeDirectHandle<Object>());
    }
  } else { // 13. Else,
    // a. Perform ? module.ExecuteModule().
    MaybeDirectHandle<Object> exception;
    DirectHandle<Object> maybe_result;
    if (!ExecuteModule(isolate, module, &exception).ToHandle(&maybe_result)) {
      if (!isolate->is_execution_terminating()) {
        isolate->Throw(*exception.ToHandleChecked());
      }
      return maybe_result;
    }
  }
  CHECK(MaybeTransitionComponent(isolate, module, stack, kEvaluated));
  return result;
}
References AddAsyncParentModule(), CHECK, CHECK_EQ, CHECK_GE, CHECK_NE, v8::base::count_if(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::Module::Evaluate(), ExecuteAsyncModule(), ExecuteModule(), v8::internal::Isolate::factory(), v8::internal::Isolate::is_execution_terminating(), v8::kEvaluation, kNotAsyncEvaluated, v8::internal::length, MAYBE_RETURN, MaybeTransitionComponent(), v8::internal::Isolate::NextModuleAsyncEvaluationOrdinal(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, RETURN_ON_EXCEPTION, SLOW_DCHECK, v8::internal::stack, STACK_CHECK, v8::internal::Isolate::Throw(), v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::MaybeDirectHandle< T >::ToHandleChecked().
Referenced by Evaluate().
LoadVariable()
Handle< Object > v8::internal::SourceTextModule::LoadVariable (Isolate * isolate, DirectHandle< SourceTextModule > module, int cell_index) [static]
Definition at line 168 of file source-text-module.cc.
                                                                             {
  return handle(module->GetCell(cell_index)->value(), isolate);
}
References v8::internal::handle().
Referenced by v8::internal::anonymous_namespace{runtime-scopes.cc}::LoadLookupSlot(), v8::internal::ScopeIterator::VisitLocals(), and v8::internal::ScopeIterator::VisitModuleScope().
MaybeHandleEvaluationException()
bool v8::internal::SourceTextModule::MaybeHandleEvaluationException (Isolate * isolate, ZoneForwardList< Handle< SourceTextModule >> * stack) [private]
Definition at line 803 of file source-text-module.cc.
                                                                        {
  DisallowGarbageCollection no_gc;
  Tagged<Object> exception = isolate->exception();
  // Step 9.
  if (isolate->is_catchable_by_javascript(exception)) {
    // a. For each Cyclic Module Record m in stack, do
    for (DirectHandle<SourceTextModule> descendant : *stack) {
      // i. Assert: m.[[Status]] is EVALUATING.
      CHECK_EQ(descendant->status(), kEvaluating);
      // ii. Set m.[[Status]] to EVALUATED.
      // iii. Set m.[[EvaluationError]] to result.
      descendant->RecordError(isolate, exception);
    }
    return true;
  }
  // If the exception was a termination exception, rejecting the promise
  // would resume execution, and our API contract is to return an empty
  // handle. The module's status should be set to kErrored and the
  // exception field should be set to `null`.
  RecordError(isolate, exception);
  for (DirectHandle<SourceTextModule> descendant : *stack) {
    descendant->RecordError(isolate, exception);
  }
  CHECK_EQ(status(), kErrored);
  CHECK_EQ(this->exception(), *isolate->factory()->null_value());
  return false;
}
References CHECK_EQ, v8::internal::Isolate::exception(), v8::internal::Isolate::factory(), v8::internal::Isolate::is_catchable_by_javascript(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::stack, and v8::internal::status.
MaybeTransitionComponent()
bool v8::internal::SourceTextModule::MaybeTransitionComponent (Isolate * isolate, DirectHandle< SourceTextModule > module, ZoneForwardList< Handle< SourceTextModule >> * stack, Status new_status) [static], [private]
Definition at line 465 of file source-text-module.cc.
                                                                         {
  DCHECK(new_status == kLinked || new_status == kEvaluated);
#ifdef DEBUG
  if (v8_flags.trace_module_status) {
    StdoutStream os;
    os << "Transitioning strongly connected module graph component to "
       << Module::StatusString(new_status) << " {\n";
  }
#endif // DEBUG
  // Below, N/M means step N in InnerModuleEvaluation and step M in
  // InnerModuleLinking.
  // 14/11. Assert: module occurs exactly once in stack.
  SLOW_DCHECK(
      // {module} is on the {stack}.
      std::count_if(stack->begin(), stack->end(), [&](DirectHandle<Module> m) {
        return *m == *module;
      }) == 1);
  // 15/12. Assert: module.[[DFSAncestorIndex]] ≤ module.[[DFSIndex]].
  DCHECK_LE(module->dfs_ancestor_index(), module->dfs_index());
  // 16/13. If module.[[DFSAncestorIndex]] = module.[[DFSIndex]], then
  if (module->dfs_ancestor_index() == module->dfs_index()) {
    // This is the root of its strongly connected component.
    DirectHandle<SourceTextModule> cycle_root = module;
    DirectHandle<SourceTextModule> ancestor;
    // This loop handles the loops in both InnerModuleEvaluation and
    // InnerModuleLinking.
    //
    // InnerModuleEvaluation
    //
    // a. Let done be false.
    // b. Repeat, while done is false,
    // i. Let requiredModule be the last element of stack.
    // ii. Remove the last element of stack.
    // iii. Assert: requiredModule is a Cyclic Module Record.
    // iv. If requiredModule.[[AsyncEvaluation]] is false, set
    // requiredModule.[[Status]] to EVALUATED.
    // v. Otherwise, set requiredModule.[[Status]] to EVALUATING-ASYNC.
    // vi. If requiredModule and module are the same Module Record, set done
    // to true.
    // vii. Set requiredModule.[[CycleRoot]] to module.
    //
    // InnerModuleLinking
    //
    // a. Let done be false.
    // b. Repeat, while done is false,
    // i. Let requiredModule be the last element of stack.
    // ii. Remove the last element of stack.
    // iii. Assert: requiredModule is a Cyclic Module Record.
    // iv. Set requiredModule.[[Status]] to LINKED.
    // v. If requiredModule and module are the same Module Record, set done
    // to true.
    do {
      ancestor = stack->front();
      stack->pop_front();
      DCHECK_EQ(ancestor->status(),
                new_status == kLinked ? kLinking : kEvaluating);
      if (new_status == kLinked) {
        if (!SourceTextModule::RunInitializationCode(isolate, ancestor)) {
          return false;
        }
        ancestor->SetStatus(kLinked);
      } else {
        DCHECK(IsTheHole(ancestor->cycle_root(), isolate));
        ancestor->set_cycle_root(*cycle_root);
        ancestor->SetStatus(ancestor->HasAsyncEvaluationOrdinal()
                                ? kEvaluatingAsync
                                : kEvaluated);
      }
    } while (*ancestor != *module);
  }
#ifdef DEBUG
  if (v8_flags.trace_module_status) {
    StdoutStream os;
    os << "}\n";
  }
#endif // DEBUG
  return true;
}
References v8::base::count_if(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, RunInitializationCode(), SLOW_DCHECK, v8::internal::stack, and v8::internal::v8_flags.
Referenced by FinishInstantiate(), and InnerModuleEvaluation().
PrepareInstantiate()
bool v8::internal::SourceTextModule::PrepareInstantiate (Isolate * isolate, DirectHandle< SourceTextModule > module, v8::Local< v8::Context > context, v8::Module::ResolveModuleCallback module_callback, v8::Module::ResolveSourceCallback source_callback) [static], [private]
Definition at line 346 of file source-text-module.cc.
                                                   {
  DCHECK_NE(module_callback, nullptr);
  // Obtain requested modules.
  DirectHandle<SourceTextModuleInfo> module_info(module->info(), isolate);
  DirectHandle<FixedArray> module_requests(module_info->module_requests(),
                                           isolate);
  DirectHandle<FixedArray> requested_modules(module->requested_modules(),
                                             isolate);
  for (int i = 0, length = module_requests->length(); i < length; ++i) {
    DirectHandle<ModuleRequest> module_request(
        Cast<ModuleRequest>(module_requests->get(i)), isolate);
    DirectHandle<String> specifier(module_request->specifier(), isolate);
    DirectHandle<FixedArray> import_attributes(
        module_request->import_attributes(), isolate);
    switch (module_request->phase()) {
      case ModuleImportPhase::kEvaluation: {
        v8::Local<v8::Module> api_requested_module;
        if (!module_callback(context, v8::Utils::ToLocal(specifier),
                             v8::Utils::FixedArrayToLocal(import_attributes),
                             v8::Utils::ToLocal(Cast<Module>(module)))
                 .ToLocal(&api_requested_module)) {
          return false;
        }
        DirectHandle<Module> requested_module =
            Utils::OpenDirectHandle(*api_requested_module);
        requested_modules->set(i, *requested_module);
        break;
      }
      case ModuleImportPhase::kSource: {
        DCHECK(v8_flags.js_source_phase_imports);
        v8::Local<v8::Object> api_requested_module_source;
        if (!source_callback(context, v8::Utils::ToLocal(specifier),
                             v8::Utils::FixedArrayToLocal(import_attributes),
                             v8::Utils::ToLocal(Cast<Module>(module)))
                 .ToLocal(&api_requested_module_source)) {
          return false;
        }
        DirectHandle<JSReceiver> requested_module_source =
            Utils::OpenDirectHandle(*api_requested_module_source);
        requested_modules->set(i, *requested_module_source);
        break;
      }
      default:
        UNREACHABLE();
    }
  }
  // Recurse.
  for (int i = 0, length = requested_modules->length(); i < length; ++i) {
    DirectHandle<ModuleRequest> module_request(
        Cast<ModuleRequest>(module_requests->get(i)), isolate);
    if (module_request->phase() != ModuleImportPhase::kEvaluation) {
      continue;
    }
    DirectHandle<Module> requested_module(
        Cast<Module>(requested_modules->get(i)), isolate);
    if (!Module::PrepareInstantiate(isolate, requested_module, context,
                                    module_callback, source_callback)) {
      return false;
    }
  }
  // Set up local exports.
  // TODO(neis): Create regular_exports array here instead of in factory method?
  for (int i = 0, n = module_info->RegularExportCount(); i < n; ++i) {
    int cell_index = module_info->RegularExportCellIndex(i);
    DirectHandle<FixedArray> export_names(
        module_info->RegularExportExportNames(i), isolate);
    CreateExport(isolate, module, cell_index, export_names);
  }
  // Partially set up indirect exports.
  // For each indirect export, we create the appropriate slot in the export
  // table and store its SourceTextModuleInfoEntry there. When we later find
  // the correct Cell in the module that actually provides the value, we replace
  // the SourceTextModuleInfoEntry by that Cell (see ResolveExport).
  DirectHandle<FixedArray> special_exports(module_info->special_exports(),
                                           isolate);
  for (int i = 0, n = special_exports->length(); i < n; ++i) {
    DirectHandle<SourceTextModuleInfoEntry> entry(
        Cast<SourceTextModuleInfoEntry>(special_exports->get(i)), isolate);
    DirectHandle<Object> export_name(entry->export_name(), isolate);
    if (IsUndefined(*export_name, isolate)) continue; // Star export.
    CreateIndirectExport(isolate, module, Cast<String>(export_name), entry);
  }
  DCHECK_EQ(module->status(), kPreLinking);
  return true;
}
References CreateExport(), CreateIndirectExport(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::kEvaluation, v8::kSource, v8::internal::length, v8::Utils::OpenDirectHandle(), v8::internal::Module::PrepareInstantiate(), v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
Referenced by v8::internal::Module::PrepareInstantiate().
Reset()
void v8::internal::SourceTextModule::Reset (Isolate * isolate, DirectHandle< SourceTextModule > module) [static], [private]
Definition at line 1340 of file source-text-module.cc.
                                                                    {
  Factory* factory = isolate->factory();
  DCHECK(IsTheHole(module->import_meta(kAcquireLoad), isolate));
  DirectHandle<FixedArray> regular_exports =
      factory->NewFixedArray(module->regular_exports()->length());
  DirectHandle<FixedArray> regular_imports =
      factory->NewFixedArray(module->regular_imports()->length());
  DirectHandle<FixedArray> requested_modules =
      factory->NewFixedArray(module->requested_modules()->length());
  DisallowGarbageCollection no_gc;
  Tagged<SourceTextModule> raw_module = *module;
  if (raw_module->status() == kLinking) {
    raw_module->set_code(Cast<JSFunction>(raw_module->code())->shared());
  }
  raw_module->set_regular_exports(*regular_exports);
  raw_module->set_regular_imports(*regular_imports);
  raw_module->set_requested_modules(*requested_modules);
  raw_module->set_dfs_index(-1);
  raw_module->set_dfs_ancestor_index(-1);
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::kAcquireLoad, v8::internal::FactoryBase< Impl >::NewFixedArray(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::Module::Reset().
ResolveExport()
MaybeHandle< Cell > v8::internal::SourceTextModule::ResolveExport (Isolate * isolate, Handle< SourceTextModule > module, DirectHandle< String > module_specifier, Handle< String > export_name, MessageLocation loc, bool must_resolve, ResolveSet * resolve_set) [static], [private]
Definition at line 182 of file source-text-module.cc.
                                                                           {
  Handle<Object> object(module->exports()->Lookup(export_name), isolate);
  if (IsCell(*object)) {
    // Already resolved (e.g. because it's a local export).
    return Cast<Cell>(object);
  }
  // Check for cycle before recursing.
  {
    // Attempt insertion with a null string set.
    auto result = resolve_set->insert({module, nullptr});
    UnorderedStringSet*& name_set = result.first->second;
    if (result.second) {
      // |module| wasn't in the map previously, so allocate a new name set.
      Zone* zone = resolve_set->zone();
      name_set = zone->New<UnorderedStringSet>(zone);
    } else if (name_set->count(export_name)) {
      // Cycle detected.
      if (must_resolve) {
        isolate->ThrowAt(isolate->factory()->NewSyntaxError(
                             MessageTemplate::kCyclicModuleDependency,
                             export_name, module_specifier),
                         &loc);
        return MaybeHandle<Cell>();
      }
      return MaybeHandle<Cell>();
    }
    name_set->insert(export_name);
  }
  if (IsSourceTextModuleInfoEntry(*object)) {
    // Not yet resolved indirect export.
    auto entry = Cast<SourceTextModuleInfoEntry>(object);
    Handle<String> import_name(Cast<String>(entry->import_name()), isolate);
    Handle<Script> script(module->GetScript(), isolate);
    MessageLocation new_loc(script, entry->beg_pos(), entry->end_pos());
    Handle<Cell> cell;
    if (!ResolveImport(isolate, module, import_name, entry->module_request(),
                       new_loc, true, resolve_set)
             .ToHandle(&cell)) {
      DCHECK(isolate->has_exception());
      return MaybeHandle<Cell>();
    }
    // The export table may have changed but the entry in question should be
    // unchanged.
    Handle<ObjectHashTable> exports(module->exports(), isolate);
    DCHECK(IsSourceTextModuleInfoEntry(exports->Lookup(export_name)));
    exports = ObjectHashTable::Put(exports, export_name, cell);
    module->set_exports(*exports);
    return cell;
  }
  DCHECK(IsTheHole(*object, isolate));
  return SourceTextModule::ResolveExportUsingStarExports(
      isolate, module, module_specifier, export_name, loc, must_resolve,
      resolve_set);
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), v8::internal::loc, v8::internal::Zone::New(), ResolveExportUsingStarExports(), ResolveImport(), v8::base::internal::result, v8::internal::script, v8::internal::Isolate::ThrowAt(), and v8::internal::Module::ResolveSet::zone().
Referenced by FinishInstantiate(), and v8::internal::Module::ResolveExport().
ResolveExportUsingStarExports()
MaybeHandle< Cell > v8::internal::SourceTextModule::ResolveExportUsingStarExports (Isolate * isolate, DirectHandle< SourceTextModule > module, DirectHandle< String > module_specifier, Handle< String > export_name, MessageLocation loc, bool must_resolve, ResolveSet * resolve_set) [static], [private]
Definition at line 287 of file source-text-module.cc.
                                                                           {
  if (!export_name->Equals(ReadOnlyRoots(isolate).default_string())) {
    // Go through all star exports looking for the given name. If multiple star
    // exports provide the name, make sure they all map it to the same cell.
    Handle<Cell> unique_cell;
    DirectHandle<FixedArray> special_exports(module->info()->special_exports(),
                                             isolate);
    for (int i = 0, n = special_exports->length(); i < n; ++i) {
      i::DirectHandle<i::SourceTextModuleInfoEntry> entry(
          i::Cast<i::SourceTextModuleInfoEntry>(special_exports->get(i)),
          isolate);
      if (!IsUndefined(entry->export_name(), isolate)) {
        continue; // Indirect export.
      }
      Handle<Script> script(module->GetScript(), isolate);
      MessageLocation new_loc(script, entry->beg_pos(), entry->end_pos());
      Handle<Cell> cell;
      if (ResolveImport(isolate, module, export_name, entry->module_request(),
                        new_loc, false, resolve_set)
              .ToHandle(&cell)) {
        if (unique_cell.is_null()) unique_cell = cell;
        if (*unique_cell != *cell) {
          isolate->ThrowAt(isolate->factory()->NewSyntaxError(
                               MessageTemplate::kAmbiguousExport,
                               module_specifier, export_name),
                           &loc);
          return MaybeHandle<Cell>();
        }
      } else if (isolate->has_exception()) {
        return MaybeHandle<Cell>();
      }
    }
    if (!unique_cell.is_null()) {
      // Found a unique star export for this name.
      Handle<ObjectHashTable> exports(module->exports(), isolate);
      DCHECK(IsTheHole(exports->Lookup(export_name), isolate));
      exports = ObjectHashTable::Put(exports, export_name, unique_cell);
      module->set_exports(*exports);
      return unique_cell;
    }
  }
  // Unresolvable.
  if (must_resolve) {
    isolate->ThrowAt(
        isolate->factory()->NewSyntaxError(MessageTemplate::kUnresolvableExport,
                                           module_specifier, export_name),
        &loc);
    return MaybeHandle<Cell>();
  }
  return MaybeHandle<Cell>();
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), v8::internal::HandleBase::is_null(), v8::internal::loc, ResolveImport(), v8::internal::script, and v8::internal::Isolate::ThrowAt().
Referenced by ResolveExport().
ResolveImport()
MaybeHandle< Cell > v8::internal::SourceTextModule::ResolveImport (Isolate * isolate, DirectHandle< SourceTextModule > module, Handle< String > name, int module_request_index, MessageLocation loc, bool must_resolve, ResolveSet * resolve_set) [static], [private]
Definition at line 246 of file source-text-module.cc.
                                                      {
  DirectHandle<ModuleRequest> module_request(
      Cast<ModuleRequest>(
          module->info()->module_requests()->get(module_request_index)),
      isolate);
  switch (module_request->phase()) {
    case ModuleImportPhase::kSource: {
      DCHECK(v8_flags.js_source_phase_imports);
      // https://tc39.es/proposal-source-phase-imports/#sec-source-text-module-record-initialize-environment
      // InitializeEnvironment
      // 7.c. Else if in.[[ImportName]] is source, then
      // 7.c.i. Let moduleSourceObject be ? importedModule.GetModuleSource().
      // 7.c.ii. Perform ! env.CreateImmutableBinding(in.[[LocalName]], true).
      // 7.c.iii. Perform ! env.InitializeBinding(in.[[LocalName]],
      // moduleSourceObject).
      Handle<Cell> cell = isolate->factory()->NewCell();
      cell->set_value(module->requested_modules()->get(module_request_index));
      return cell;
    }
    case ModuleImportPhase::kEvaluation: {
      DCHECK_EQ(module_request->phase(), ModuleImportPhase::kEvaluation);
      Handle<Module> requested_module(
          Cast<Module>(module->requested_modules()->get(module_request_index)),
          isolate);
      DirectHandle<String> module_specifier(
          Cast<String>(module_request->specifier()), isolate);
      MaybeHandle<Cell> result =
          Module::ResolveExport(isolate, requested_module, module_specifier,
                                name, loc, must_resolve, resolve_set);
      DCHECK_IMPLIES(isolate->has_exception(), result.is_null());
      return result;
    }
    default:
      UNREACHABLE();
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), v8::kEvaluation, v8::kSource, v8::internal::loc, v8::internal::name, v8::internal::Factory::NewCell(), v8::internal::Module::ResolveExport(), v8::base::internal::result, v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
Referenced by FinishInstantiate(), ResolveExport(), and ResolveExportUsingStarExports().
RunInitializationCode()
bool v8::internal::SourceTextModule::RunInitializationCode (Isolate * isolate, DirectHandle< SourceTextModule > module) [static], [private]
Definition at line 440 of file source-text-module.cc.
                                                             {
  DCHECK_EQ(module->status(), kLinking);
  DirectHandle<JSFunction> function(Cast<JSFunction>(module->code()), isolate);
  DCHECK_EQ(MODULE_SCOPE, function->shared()->scope_info()->scope_type());
  DirectHandle<Object> receiver = isolate->factory()->undefined_value();
  DirectHandle<ScopeInfo> scope_info(function->shared()->scope_info(), isolate);
  DirectHandle<Context> context = isolate->factory()->NewModuleContext(
      module, isolate->native_context(), scope_info);
  function->set_context(*context);
  MaybeDirectHandle<Object> maybe_generator =
      Execution::Call(isolate, function, receiver, {});
  DirectHandle<Object> generator;
  if (!maybe_generator.ToHandle(&generator)) {
    DCHECK(isolate->has_exception());
    return false;
  }
  DCHECK_EQ(*function, Cast<JSGeneratorObject>(generator)->function());
  module->set_code(Cast<JSGeneratorObject>(*generator));
  return true;
}
References v8::internal::Execution::Call(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), v8::internal::MODULE_SCOPE, v8::internal::Isolate::native_context(), v8::internal::Factory::NewModuleContext(), and v8::internal::MaybeDirectHandle< T >::ToHandle().
Referenced by MaybeTransitionComponent().
StoreVariable()
void v8::internal::SourceTextModule::StoreVariable (DirectHandle< SourceTextModule > module, int cell_index, DirectHandle< Object > value) [static]
Definition at line 173 of file source-text-module.cc.
                                                                 {
  DisallowGarbageCollection no_gc;
  DCHECK_EQ(SourceTextModuleDescriptor::GetCellIndexKind(cell_index),
            SourceTextModuleDescriptor::kExport);
  module->GetCell(cell_index)->set_value(*value);
}
References DCHECK_EQ, v8::internal::SourceTextModuleDescriptor::GetCellIndexKind(), v8::internal::SourceTextModuleDescriptor::kExport, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::value.
Referenced by v8::internal::ScopeIterator::SetLocalVariableValue(), v8::internal::ScopeIterator::SetModuleVariableValue(), and v8::internal::anonymous_namespace{runtime-scopes.cc}::StoreLookupSlot().
Friends And Related Function Documentation
Factory
friend class Factory [friend]
Definition at line 94 of file source-text-module.h.
Module
friend class Module [friend]
Definition at line 95 of file source-text-module.h.
Member Data Documentation
kAsyncEvaluateDidFinish
constexpr unsigned v8::internal::SourceTextModule::kAsyncEvaluateDidFinish = 1 [static], [constexpr], [private]
Definition at line 141 of file source-text-module.h.
Referenced by AsyncModuleExecutionFulfilled(), and AsyncModuleExecutionRejected().
kFirstAsyncEvaluationOrdinal
constexpr unsigned v8::internal::SourceTextModule::kFirstAsyncEvaluationOrdinal = 2 [static], [constexpr]
Definition at line 81 of file source-text-module.h.
Referenced by HasAsyncEvaluationOrdinal().
kNotAsyncEvaluated
constexpr unsigned v8::internal::SourceTextModule::kNotAsyncEvaluated = 0 [static], [constexpr], [private]
Definition at line 140 of file source-text-module.h.
Referenced by InnerModuleEvaluation(), and v8::internal::Factory::NewSourceTextModule().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/source-text-module.h
/mnt/V8SourceCode/src/objects/module-inl.h
/mnt/V8SourceCode/src/objects/source-text-module.cc