v8::internal::torque::StackRange Class Reference
#include <utils.h>
Public Member Functions
StackRange (BottomOffset begin, BottomOffset end)
bool operator== (const StackRange &other) const
void Extend (StackRange adjacent)
size_t Size () const
BottomOffset begin () const
BottomOffset end () const
Private Attributes
BottomOffset begin_
BottomOffset end_
Detailed Description
Definition at line 207 of file utils.h.
Constructor & Destructor Documentation
StackRange()
v8::internal::torque::StackRange::StackRange (BottomOffset begin, BottomOffset end) [inline]
Definition at line 209 of file utils.h.
                                                   : begin_(begin), end_(end) {
    DCHECK_LE(begin_, end_);
  }
References begin_, DCHECK_LE, and end_.
Member Function Documentation
begin()
BottomOffset v8::internal::torque::StackRange::begin () const [inline]
Definition at line 223 of file utils.h.
{ return begin_; }
References begin_.
Referenced by v8::internal::torque::operator<<(), v8::internal::torque::CfgAssembler::Peek(), v8::internal::torque::CfgAssembler::Poke(), and v8::internal::torque::ProjectStructField().
end()
BottomOffset v8::internal::torque::StackRange::end () const [inline]
Definition at line 224 of file utils.h.
{ return end_; }
References end_.
Referenced by v8::internal::torque::CfgAssembler::DeleteRange(), v8::internal::torque::Stack< T >::DeleteRange(), v8::internal::torque::operator<<(), and v8::internal::torque::CfgAssembler::Poke().
Extend()
void v8::internal::torque::StackRange::Extend (StackRange adjacent) [inline]
Definition at line 217 of file utils.h.
                                   {
    DCHECK_EQ(end_, adjacent.begin_);
    end_ = adjacent.end_;
  }
References begin_, DCHECK_EQ, and end_.
Referenced by v8::internal::torque::ImplementationVisitor::AddCallParameter(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateFieldReferenceForInit(), v8::internal::torque::ImplementationVisitor::GeneratePointerCall(), v8::internal::torque::ImplementationVisitor::LowerParameter(), and v8::internal::torque::ImplementationVisitor::Visit().
operator==()
bool v8::internal::torque::StackRange::operator== (const StackRange & other) const [inline]
Definition at line 213 of file utils.h.
                                                 {
    return begin_ == other.begin_ && end_ == other.end_;
  }
References begin_, and end_.
Size()
size_t v8::internal::torque::StackRange::Size () const [inline]
Definition at line 222 of file utils.h.
{ return end_.offset - begin_.offset; }
References begin_, end_, and v8::internal::torque::BottomOffset::offset.
Referenced by v8::internal::torque::CfgAssembler::DeleteRange(), v8::internal::torque::Stack< T >::DeleteRange(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::GeneratePointerCall(), v8::internal::torque::CfgAssembler::Peek(), v8::internal::torque::CfgAssembler::Poke(), and v8::internal::torque::ImplementationVisitor::Visit().
Member Data Documentation
begin_
BottomOffset v8::internal::torque::StackRange::begin_ [private]
Definition at line 227 of file utils.h.
Referenced by begin(), Extend(), operator==(), Size(), and StackRange().
end_
BottomOffset v8::internal::torque::StackRange::end_ [private]
Definition at line 228 of file utils.h.
Referenced by end(), Extend(), operator==(), Size(), and StackRange().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/utils.h