v8_inspector::InspectedContext::WeakCallbackData Class Reference
Public Member Functions
WeakCallbackData (InspectedContext *context, V8InspectorImpl *inspector, int groupId, int contextId)
Static Public Member Functions
static void resetContext (const v8::WeakCallbackInfo< WeakCallbackData > &data)
Private Attributes
InspectedContext * m_context
V8InspectorImpl * m_inspector
int m_groupId
int m_contextId
Friends
class InspectedContext::ContextCollectedCallbacks
Detailed Description
Definition at line 30 of file inspected-context.cc.
Constructor & Destructor Documentation
WeakCallbackData()
v8_inspector::InspectedContext::WeakCallbackData::WeakCallbackData (InspectedContext * context, V8InspectorImpl * inspector, int groupId, int contextId) [inline]
Definition at line 32 of file inspected-context.cc.
      : m_context(context),
        m_inspector(inspector),
        m_groupId(groupId),
        m_contextId(contextId) {}
Member Function Documentation
resetContext()
static void v8_inspector::InspectedContext::WeakCallbackData::resetContext (const v8::WeakCallbackInfo< WeakCallbackData > & data) [inline], [static]
Definition at line 39 of file inspected-context.cc.
                                                                             {
    // InspectedContext is alive here because weak handler is still alive.
    data.GetParameter()->m_context->m_weakCallbackData = nullptr;
    data.GetParameter()->m_context->m_context.Reset();
    v8::debug::GetCurrentPlatform()
        ->GetForegroundTaskRunner(data.GetIsolate())
        ->PostTask(
            std::make_unique<ContextCollectedCallbacks>(data.GetParameter()));
  }
References v8::debug::GetCurrentPlatform(), v8::Platform::GetForegroundTaskRunner(), v8::WeakCallbackInfo< T >::GetIsolate(), and v8::WeakCallbackInfo< T >::GetParameter().
Referenced by v8_inspector::InspectedContext::InspectedContext().
Friends And Related Function Documentation
InspectedContext::ContextCollectedCallbacks
friend class InspectedContext::ContextCollectedCallbacks [friend]
Definition at line 55 of file inspected-context.cc.
Member Data Documentation
m_context
InspectedContext* v8_inspector::InspectedContext::WeakCallbackData::m_context [private]
Definition at line 50 of file inspected-context.cc.
m_contextId
int v8_inspector::InspectedContext::WeakCallbackData::m_contextId [private]
Definition at line 53 of file inspected-context.cc.
m_groupId
int v8_inspector::InspectedContext::WeakCallbackData::m_groupId [private]
Definition at line 52 of file inspected-context.cc.
m_inspector
V8InspectorImpl* v8_inspector::InspectedContext::WeakCallbackData::m_inspector [private]
Definition at line 51 of file inspected-context.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/inspector/inspected-context.cc