v8::internal::PropertyArray Class Reference
#include <property-array.h>
Public Types
using BodyDescriptor = FlexibleBodyDescriptor< kHeaderSize >
using LengthField = base::BitField< int, 0, kLengthFieldSize >
using HashField = base::BitField< int, kLengthFieldSize, kSmiValueSize - kLengthFieldSize - 1 >
Public Member Functions
int length () const
int length (AcquireLoadTag) const
void initialize_length (int length)
void SetHash (int hash)
int Hash () const
Tagged< JSAny > get (int index) const
Tagged< JSAny > get (PtrComprCageBase cage_base, int index) const
Tagged< JSAny > get (int index, SeqCstAccessTag tag) const
Tagged< JSAny > get (PtrComprCageBase cage_base, int index, SeqCstAccessTag tag) const
void set (int index, Tagged< Object > value)
void set (int index, Tagged< Object > value, SeqCstAccessTag tag)
void set (int index, Tagged< Object > value, WriteBarrierMode mode)
Tagged< Object > Swap (int index, Tagged< Object > value, SeqCstAccessTag tag)
Tagged< Object > Swap (PtrComprCageBase cage_base, int index, Tagged< Object > value, SeqCstAccessTag tag)
Tagged< Object > CompareAndSwap (int index, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag)
ObjectSlot data_start ()
ObjectSlot RawFieldOfElementAt (int index)
Static Public Member Functions
static void CopyElements (Isolate *isolate, Tagged< PropertyArray > dst, int dst_index, Tagged< PropertyArray > src, int src_index, int len, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
static constexpr int SizeFor (int length)
static constexpr int OffsetOfElementAt (int index)
Static Public Attributes
static const int kLengthFieldSize = 10
static const int kMaxLength = LengthField::kMax
static const int kNoHashSentinel = 0
Detailed Description
Definition at line 18 of file property-array.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::PropertyArray::BodyDescriptor = FlexibleBodyDescriptor<kHeaderSize>
Definition at line 72 of file property-array.h.
HashField
using v8::internal::PropertyArray::HashField = base::BitField<int, kLengthFieldSize, kSmiValueSize - kLengthFieldSize - 1>
Definition at line 77 of file property-array.h.
LengthField
using v8::internal::PropertyArray::LengthField = base::BitField<int, 0, kLengthFieldSize>
Definition at line 75 of file property-array.h.
Member Function Documentation
CompareAndSwap()
Tagged< Object > v8::internal::PropertyArray::CompareAndSwap (int index, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag) [inline]
Definition at line 102 of file property-array-inl.h.
                                                                  {
  DCHECK(IsPropertyArray(*this));
  DCHECK_LT(static_cast<unsigned>(index),
            static_cast<unsigned>(this->length(kAcquireLoad)));
  DCHECK(IsShared(value));
  Tagged<Object> result = TaggedField<Object>::SeqCst_CompareAndSwap(
      *this, OffsetOfElementAt(index), expected, value);
  if (result == expected) {
    CONDITIONAL_WRITE_BARRIER(*this, OffsetOfElementAt(index), value,
                              UPDATE_WRITE_BARRIER);
  }
  return result;
}
References CONDITIONAL_WRITE_BARRIER, v8::internal::DCHECK(), DCHECK_LT, v8::internal::index, v8::internal::IsShared(), v8::kAcquireLoad, length(), OffsetOfElementAt(), v8::base::internal::result, v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::SeqCst_CompareAndSwap(), v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
CopyElements()
void v8::internal::PropertyArray::CopyElements (Isolate * isolate, Tagged< PropertyArray > dst, int dst_index, Tagged< PropertyArray > src, int src_index, int len, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline], [static]
Definition at line 146 of file property-array-inl.h.
                                                        {
  if (len == 0) return;
  DisallowGarbageCollection no_gc;
  ObjectSlot dst_slot(dst->data_start() + dst_index);
  ObjectSlot src_slot(src->data_start() + src_index);
  isolate->heap()->CopyRange(dst, dst_slot, src_slot, len, mode);
}
References v8::internal::Heap::CopyRange(), v8::internal::Isolate::heap(), mode(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
data_start()
ObjectSlot v8::internal::PropertyArray::data_start () [inline]
Definition at line 118 of file property-array-inl.h.
{ return RawFieldOfElementAt(0); }
References RawFieldOfElementAt().
get() [1/4]
Tagged<JSAny> v8::internal::PropertyArray::get (int index) const [inline]
get() [2/4]
Tagged<JSAny> v8::internal::PropertyArray::get (int index, SeqCstAccessTag tag) const [inline]
get() [3/4]
Tagged<JSAny> v8::internal::PropertyArray::get (PtrComprCageBase cage_base, int index) const [inline]
get() [4/4]
Tagged<JSAny> v8::internal::PropertyArray::get (PtrComprCageBase cage_base, int index, SeqCstAccessTag tag) const [inline]
Hash()
int v8::internal::PropertyArray::Hash () const [inline]
Definition at line 137 of file property-array-inl.h.
{ return HashField::decode(length_and_hash()); }
References v8::base::BitField< T, shift, size, U >::decode().
initialize_length()
void v8::internal::PropertyArray::initialize_length (int length) [inline]
Definition at line 128 of file property-array-inl.h.
                                             {
  DCHECK(LengthField::is_valid(len));
  set_length_and_hash(len);
}
References v8::internal::DCHECK(), and v8::base::BitField< T, shift, size, U >::is_valid().
length() [1/2]
int v8::internal::PropertyArray::length () const [inline]
Definition at line 124 of file property-array-inl.h.
                                {
  return LengthField::decode(length_and_hash());
}
References v8::base::BitField< T, shift, size, U >::decode().
Referenced by CompareAndSwap(), set(), SizeFor(), and Swap().
length() [2/2]
int v8::internal::PropertyArray::length (AcquireLoadTag) const [inline]
Definition at line 133 of file property-array-inl.h.
                                              {
  return LengthField::decode(length_and_hash(kAcquireLoad));
}
References v8::base::BitField< T, shift, size, U >::decode(), and v8::kAcquireLoad.
OffsetOfElementAt()
static constexpr int v8::internal::PropertyArray::OffsetOfElementAt (int index) [inline], [static], [constexpr]
Definition at line 66 of file property-array.h.
{ return SizeFor(index); }
References v8::internal::index, and SizeFor().
Referenced by CompareAndSwap(), v8::internal::compiler::AccessBuilder::ForPropertyArraySlot(), v8::internal::FieldIndex::ForPropertyIndex(), RawFieldOfElementAt(), set(), and Swap().
RawFieldOfElementAt()
ObjectSlot v8::internal::PropertyArray::RawFieldOfElementAt (int index) [inline]
Definition at line 120 of file property-array-inl.h.
                                                       {
  return RawField(OffsetOfElementAt(index));
}
References v8::internal::index, and OffsetOfElementAt().
Referenced by data_start().
set() [1/3]
void v8::internal::PropertyArray::set (int index, Tagged< Object > value) [inline]
set() [2/3]
void v8::internal::PropertyArray::set (int index, Tagged< Object > value, SeqCstAccessTag tag) [inline]
Definition at line 73 of file property-array-inl.h.
                                                                            {
  DCHECK(IsPropertyArray(*this));
  DCHECK_LT(static_cast<unsigned>(index),
            static_cast<unsigned>(this->length(kAcquireLoad)));
  DCHECK(IsShared(value));
  int offset = OffsetOfElementAt(index);
  SEQ_CST_WRITE_FIELD(*this, offset, value);
  CONDITIONAL_WRITE_BARRIER(*this, offset, value, UPDATE_WRITE_BARRIER);
}
References CONDITIONAL_WRITE_BARRIER, v8::internal::DCHECK(), DCHECK_LT, v8::internal::index, v8::internal::IsShared(), v8::kAcquireLoad, length(), OffsetOfElementAt(), SEQ_CST_WRITE_FIELD, v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
set() [3/3]
void v8::internal::PropertyArray::set (int index, Tagged< Object > value, WriteBarrierMode mode) [inline]
Definition at line 64 of file property-array-inl.h.
                                               {
  DCHECK_LT(static_cast<unsigned>(index),
            static_cast<unsigned>(this->length(kAcquireLoad)));
  int offset = OffsetOfElementAt(index);
  RELAXED_WRITE_FIELD(*this, offset, value);
  CONDITIONAL_WRITE_BARRIER(*this, offset, value, mode);
}
References CONDITIONAL_WRITE_BARRIER, DCHECK_LT, v8::internal::index, v8::kAcquireLoad, length(), mode(), OffsetOfElementAt(), RELAXED_WRITE_FIELD, and v8::internal::value.
SetHash()
void v8::internal::PropertyArray::SetHash (int hash) [inline]
Definition at line 139 of file property-array-inl.h.
                                    {
  int value = length_and_hash();
  value = HashField::update(value, hash);
  set_length_and_hash(value, kReleaseStore);
}
References v8::kReleaseStore, v8::base::BitField< T, shift, size, U >::update(), and v8::internal::value.
SizeFor()
static constexpr int v8::internal::PropertyArray::SizeFor (int length) [inline], [static], [constexpr]
Definition at line 63 of file property-array.h.
                                           {
    return kHeaderSize + length * kTaggedSize;
  }
References v8::internal::kTaggedSize, and length().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), v8::internal::TranslatedState::EnsureCapturedObjectAllocatedAt(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::ExtendPropertiesBackingStore(), OffsetOfElementAt(), and v8::internal::HeapObject::SizeFromMap().
Swap() [1/2]
Tagged< Object > v8::internal::PropertyArray::Swap (int index, Tagged< Object > value, SeqCstAccessTag tag) [inline]
Definition at line 83 of file property-array-inl.h.
                                                        {
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  return Swap(cage_base, index, value, tag);
}
References v8::internal::GetPtrComprCageBase(), v8::internal::index, and v8::internal::value.
Swap() [2/2]
Tagged< Object > v8::internal::PropertyArray::Swap (PtrComprCageBase cage_base, int index, Tagged< Object > value, SeqCstAccessTag tag) [inline]
Definition at line 89 of file property-array-inl.h.
                                                                              {
  DCHECK(IsPropertyArray(*this));
  DCHECK_LT(static_cast<unsigned>(index),
            static_cast<unsigned>(this->length(kAcquireLoad)));
  DCHECK(IsShared(value));
  Tagged<Object> result = TaggedField<Object>::SeqCst_Swap(
      cage_base, *this, OffsetOfElementAt(index), value);
  CONDITIONAL_WRITE_BARRIER(*this, OffsetOfElementAt(index), value,
                            UPDATE_WRITE_BARRIER);
  return result;
}
References CONDITIONAL_WRITE_BARRIER, v8::internal::DCHECK(), DCHECK_LT, v8::internal::index, v8::internal::IsShared(), v8::kAcquireLoad, length(), OffsetOfElementAt(), v8::base::internal::result, v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::SeqCst_Swap(), v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
Member Data Documentation
kLengthFieldSize
const int v8::internal::PropertyArray::kLengthFieldSize = 10 [static]
Definition at line 74 of file property-array.h.
kMaxLength
const int v8::internal::PropertyArray::kMaxLength = LengthField::kMax [static]
Definition at line 76 of file property-array.h.
kNoHashSentinel
const int v8::internal::PropertyArray::kNoHashSentinel = 0 [static]
Definition at line 80 of file property-array.h.
Referenced by v8::internal::OrderedNameDictionary::Allocate(), v8::internal::OrderedNameDictionary::AllocateEmpty(), v8::internal::CodeStubAssembler::AllocateNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::AllocateOrderedNameDictionary(), v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), v8::internal::JSReceiver::CreateIdentityHash(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::ExtendPropertiesBackingStore(), v8::internal::JSReceiver::GetIdentityHash(), v8::internal::anonymous_namespace{js-objects.cc}::GetIdentityHashHelper(), v8::internal::JSReceiver::GetOrCreateIdentityHash(), v8::internal::SwissNameDictionary::Initialize(), v8::internal::CodeStubAssembler::LoadJSReceiverIdentityHash(), v8::internal::Factory::NewSmallOrderedNameDictionary(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::anonymous_namespace{js-objects.cc}::SetHashAndUpdateProperties(), v8::internal::JSReceiver::SetIdentityHash(), and v8::internal::JSReceiver::SetProperties().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/property-array.h
/mnt/V8SourceCode/src/objects/property-array-inl.h