v8::internal::torque::Instruction Class Reference
#include <instructions.h>
Public Member Functions
template<class T >
Instruction (T instr)
template<class T >
T & Cast ()
template<class T >
const T & Cast () const
template<class T >
bool Is () const
template<class T >
T * DynamicCast ()
template<class T >
const T * DynamicCast () const
Instruction (const Instruction &other) V8_NOEXCEPT
Instruction & operator= (const Instruction &other) V8_NOEXCEPT
InstructionKind kind () const
const char * Mnemonic () const
void TypeInstruction (Stack< const Type * > *stack, ControlFlowGraph *cfg) const
void RecomputeDefinitionLocations (Stack< DefinitionLocation > *locations, Worklist< Block * > *worklist) const
InstructionBase * operator-> ()
const InstructionBase * operator-> () const
Private Attributes
InstructionKind kind_
std::unique_ptr< InstructionBase > instruction_
Detailed Description
Definition at line 204 of file instructions.h.
Constructor & Destructor Documentation
Instruction() [1/2]
template<class T >
v8::internal::torque::Instruction::Instruction (T instr) [inline]
Definition at line 207 of file instructions.h.
      : kind_(T::kKind), instruction_(new T(std::move(instr))) {}
Instruction() [2/2]
v8::internal::torque::Instruction::Instruction (const Instruction & other) [inline]
Definition at line 239 of file instructions.h.
      : kind_(other.kind_),
        instruction_(other.instruction_->Clone()) {}
Member Function Documentation
Cast() [1/2]
template<class T >
T& v8::internal::torque::Instruction::Cast () [inline]
Definition at line 211 of file instructions.h.
            {
    DCHECK(Is<T>());
    return static_cast<T&>(*instruction_);
  }
References v8::internal::DCHECK().
Cast() [2/2]
template<class T >
const T& v8::internal::torque::Instruction::Cast () const [inline]
Definition at line 217 of file instructions.h.
                        {
    DCHECK(Is<T>());
    return static_cast<const T&>(*instruction_);
  }
References v8::internal::DCHECK().
DynamicCast() [1/2]
template<class T >
T* v8::internal::torque::Instruction::DynamicCast () [inline]
Definition at line 228 of file instructions.h.
                   {
    if (Is<T>()) return &Cast<T>();
    return nullptr;
  }
DynamicCast() [2/2]
template<class T >
const T* v8::internal::torque::Instruction::DynamicCast () const [inline]
Definition at line 234 of file instructions.h.
                               {
    if (Is<T>()) return &Cast<T>();
    return nullptr;
  }
Is()
template<class T >
bool v8::internal::torque::Instruction::Is () const [inline]
Definition at line 223 of file instructions.h.
                  {
    return kind_ == T::kKind;
  }
References kind_.
kind()
InstructionKind v8::internal::torque::Instruction::kind () const [inline]
Definition at line 252 of file instructions.h.
{ return kind_; }
References kind_.
Referenced by v8::internal::torque::TorqueCodeGenerator::EmitInstruction(), v8::internal::torque::TorqueCodeGenerator::IsEmptyInstruction(), and Mnemonic().
Mnemonic()
const char* v8::internal::torque::Instruction::Mnemonic () const [inline]
Definition at line 253 of file instructions.h.
                               {
    switch (kind()) {
#define ENUM_ITEM(name) \
  case InstructionKind::k##name: \
    return #name;
      TORQUE_INSTRUCTION_LIST(ENUM_ITEM)
#undef ENUM_ITEM
      default:
        UNREACHABLE();
    }
  }
References ENUM_ITEM, kind(), TORQUE_INSTRUCTION_LIST, and v8::internal::UNREACHABLE().
operator->() [1/2]
InstructionBase* v8::internal::torque::Instruction::operator-> () [inline]
Definition at line 272 of file instructions.h.
{ return instruction_.get(); }
References instruction_.
operator->() [2/2]
const InstructionBase* v8::internal::torque::Instruction::operator-> () const [inline]
Definition at line 273 of file instructions.h.
{ return instruction_.get(); }
References instruction_.
operator=()
Instruction& v8::internal::torque::Instruction::operator= (const Instruction & other) [inline]
Definition at line 242 of file instructions.h.
                                                               {
    if (kind_ == other.kind_) {
      instruction_->Assign(*other.instruction_);
    } else {
      kind_ = other.kind_;
      instruction_ = other.instruction_->Clone();
    }
    return *this;
  }
References instruction_, and kind_.
RecomputeDefinitionLocations()
void v8::internal::torque::Instruction::RecomputeDefinitionLocations (Stack< DefinitionLocation > * locations, Worklist< Block * > * worklist) const [inline]
Definition at line 267 of file instructions.h.
                                                                      {
    instruction_->RecomputeDefinitionLocations(locations, worklist);
  }
References instruction_.
TypeInstruction()
void v8::internal::torque::Instruction::TypeInstruction (Stack< const Type * > * stack, ControlFlowGraph * cfg) const [inline]
Definition at line 264 of file instructions.h.
                                                                               {
    return instruction_->TypeInstruction(stack, cfg);
  }
References instruction_, and v8::internal::stack.
Referenced by v8::internal::torque::CfgAssembler::Emit().
Member Data Documentation
instruction_
std::unique_ptr<InstructionBase> v8::internal::torque::Instruction::instruction_ [private]
Definition at line 277 of file instructions.h.
Referenced by operator->(), operator=(), RecomputeDefinitionLocations(), and TypeInstruction().
kind_
InstructionKind v8::internal::torque::Instruction::kind_ [private]
Definition at line 276 of file instructions.h.
Referenced by Is(), kind(), and operator=().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/instructions.h