v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor Class Reference
Public Member Functions
ObjectPreProcessor (Isolate *isolate)
void PreProcessIfNeeded (Tagged< HeapObject > o)
Private Member Functions
void EncodeExternalPointerSlot (ExternalPointerSlot slot)
void EncodeExternalPointerSlot (ExternalPointerSlot slot, Address value)
void PreProcessAccessorInfo (Tagged< AccessorInfo > o)
void PreProcessInterceptorInfo (Tagged< InterceptorInfo > o)
void PreProcessJSExternalObject (Tagged< JSExternalObject > o)
void PreProcessFunctionTemplateInfo (Tagged< FunctionTemplateInfo > o)
void PreProcessCode (Tagged< Code > o)
Private Attributes
Isolate *const isolate_
ExternalReferenceEncoder extref_encoder_
Detailed Description
Definition at line 21 of file read-only-serializer.cc.
Constructor & Destructor Documentation
ObjectPreProcessor()
v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::ObjectPreProcessor (Isolate * isolate) [inline], [explicit]
Definition at line 23 of file read-only-serializer.cc.
      : isolate_(isolate), extref_encoder_(isolate) {}
Member Function Documentation
EncodeExternalPointerSlot() [1/2]
void v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::EncodeExternalPointerSlot (ExternalPointerSlot slot) [inline], [private]
Definition at line 46 of file read-only-serializer.cc.
                                                           {
    Address value = slot.load(isolate_);
    EncodeExternalPointerSlot(slot, value);
  }
References v8::internal::ExternalPointerSlot::load(), and v8::internal::value.
EncodeExternalPointerSlot() [2/2]
void v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::EncodeExternalPointerSlot (ExternalPointerSlot slot, Address value) [inline], [private]
Definition at line 51 of file read-only-serializer.cc.
                                                                          {
    // Note it's possible that `value != slot.load(...)`, e.g. for
    // AccessorInfo::remove_getter_indirection.
    ExternalReferenceEncoder::Value encoder_value =
        extref_encoder_.Encode(value);
    DCHECK_LT(encoder_value.index(),
              1UL << ro::EncodedExternalReference::kIndexBits);
    ro::EncodedExternalReference encoded{encoder_value.is_from_api(),
                                         encoder_value.index()};
    // Constructing no_gc here is not the intended use pattern (instead we
    // should pass it along the entire callchain); but there's little point of
    // doing that here - all of the code in this file relies on GC being
    // disabled, and that's guarded at entry points.
    DisallowGarbageCollection no_gc;
    slot.ReplaceContentWithIndexForSerialization(no_gc, encoded.ToUint32());
  }
References DCHECK_LT, v8::internal::ExternalReferenceEncoder::Value::Encode(), v8::internal::ExternalReferenceEncoder::Value::index(), v8::internal::ExternalReferenceEncoder::Value::is_from_api(), v8::internal::ro::EncodedExternalReference::kIndexBits, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::ExternalPointerSlot::ReplaceContentWithIndexForSerialization(), and v8::internal::value.
PreProcessAccessorInfo()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::PreProcessAccessorInfo (Tagged< AccessorInfo > o) [inline], [private]
Definition at line 67 of file read-only-serializer.cc.
                                                      {
    EncodeExternalPointerSlot(
        o->RawExternalPointerField(AccessorInfo::kMaybeRedirectedGetterOffset,
                                   kAccessorInfoGetterTag),
        o->getter(isolate_)); // Pass the non-redirected value.
    EncodeExternalPointerSlot(o->RawExternalPointerField(
        AccessorInfo::kSetterOffset, kAccessorInfoSetterTag));
  }
References v8::internal::kAccessorInfoGetterTag, v8::internal::kAccessorInfoSetterTag, and v8::internal::kSetterOffset.
PreProcessCode()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::PreProcessCode (Tagged< Code > o) [inline], [private]
Definition at line 119 of file read-only-serializer.cc.
                                      {
    o->ClearInstructionStartForSerialization(isolate_);
    CHECK(!o->has_source_position_table_or_bytecode_offset_table());
    CHECK(!o->has_deoptimization_data_or_interpreter_data());
#ifdef V8_ENABLE_LEAPTIERING
    CHECK_EQ(o->js_dispatch_handle(), kNullJSDispatchHandle);
#endif
#if V8_ENABLE_GEARBOX
    ResetGearboxPlaceholderBuiltin(o);
#endif
  }
References CHECK, CHECK_EQ, and v8::internal::kNullJSDispatchHandle().
PreProcessFunctionTemplateInfo()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::PreProcessFunctionTemplateInfo (Tagged< FunctionTemplateInfo > o) [inline], [private]
Definition at line 93 of file read-only-serializer.cc.
                                                                      {
    EncodeExternalPointerSlot(
        o->RawExternalPointerField(
            FunctionTemplateInfo::kMaybeRedirectedCallbackOffset,
            kFunctionTemplateInfoCallbackTag),
        o->callback(isolate_)); // Pass the non-redirected value.
  }
References v8::internal::kFunctionTemplateInfoCallbackTag.
PreProcessIfNeeded()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::PreProcessIfNeeded (Tagged< HeapObject > o) [inline]
Definition at line 33 of file read-only-serializer.cc.
                                                {
    const InstanceType itype = o->map(isolate_)->instance_type();
#define V(TYPE) \
  if (InstanceTypeChecker::Is##TYPE(itype)) { \
    return PreProcess##TYPE(Cast<TYPE>(o)); \
  }
    PRE_PROCESS_TYPE_LIST(V)
#undef V
    // If we reach here, no preprocessing is needed for this object.
  }
References PRE_PROCESS_TYPE_LIST.
Referenced by v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::PreProcessSegment().
PreProcessInterceptorInfo()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::PreProcessInterceptorInfo (Tagged< InterceptorInfo > o) [inline], [private]
Definition at line 75 of file read-only-serializer.cc.
                                                            {
    const bool is_named = o->is_named();
#define PROCESS_FIELD(Name, name) \
  EncodeExternalPointerSlot(o->RawExternalPointerField(\
      InterceptorInfo::k##Name##Offset, \
      is_named ? kApiNamedProperty##Name##CallbackTag \
               : kApiIndexedProperty##Name##CallbackTag));
    INTERCEPTOR_INFO_CALLBACK_LIST(PROCESS_FIELD)
#undef PROCESS_FIELD
  }
References INTERCEPTOR_INFO_CALLBACK_LIST, v8::internal::is_named(), and PROCESS_FIELD.
PreProcessJSExternalObject()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::PreProcessJSExternalObject (Tagged< JSExternalObject > o) [inline], [private]
Definition at line 87 of file read-only-serializer.cc.
                                                              {
    EncodeExternalPointerSlot(
        o->RawExternalPointerField(JSExternalObject::kValueOffset,
                                   kExternalObjectValueTag),
        reinterpret_cast<Address>(o->value(isolate_)));
  }
References v8::internal::kExternalObjectValueTag.
Member Data Documentation
extref_encoder_
ExternalReferenceEncoder v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::extref_encoder_ [private]
Definition at line 132 of file read-only-serializer.cc.
isolate_
Isolate* const v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::isolate_ [private]
Definition at line 131 of file read-only-serializer.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/read-only-serializer.cc