v8::LocalVector< T > Class Template Reference
#include <v8-local-handle.h>
Public Types
using value_type = Local< T >
using reference = value_type &
using const_reference = const value_type &
using size_type = size_t
using difference_type = ptrdiff_t
using iterator = internal::WrappedIterator< typename vector_type::iterator, Local< T > >
using const_iterator = internal::WrappedIterator< typename vector_type::const_iterator, const Local< T > >
Public Member Functions
LocalVector (Isolate *isolate)
LocalVector (Isolate *isolate, size_t n)
LocalVector (Isolate *isolate, std::initializer_list< Local< T >> init)
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
size_t size () const noexcept
bool empty () const noexcept
void reserve (size_t n)
void shrink_to_fit ()
Local< T > & operator[] (size_t n)
const Local< T > & operator[] (size_t n) const
Local< T > & at (size_t n)
const Local< T > & at (size_t n) const
Local< T > & front ()
const Local< T > & front () const
Local< T > & back ()
const Local< T > & back () const
Local< T > * data () noexcept
const Local< T > * data () const noexcept
iterator insert (const_iterator pos, const Local< T > &value)
template<typename InputIt >
iterator insert (const_iterator pos, InputIt first, InputIt last)
iterator insert (const_iterator pos, std::initializer_list< Local< T >> init)
LocalVector< T > & operator= (std::initializer_list< Local< T >> init)
void push_back (const Local< T > &x)
void pop_back ()
template<typename... Args>
void emplace_back (Args &&... args)
void clear () noexcept
void resize (size_t n)
void swap (LocalVector< T > &other)
Private Types
using element_type = internal::LocalUnchecked< T >
using allocator_type = std::allocator< element_type >
using vector_type = std::vector< element_type, allocator_type >
Static Private Member Functions
static allocator_type make_allocator (Isolate *isolate) noexcept
Private Attributes
vector_type backing_
Friends
bool operator== (const LocalVector< T > &x, const LocalVector< T > &y)
bool operator!= (const LocalVector< T > &x, const LocalVector< T > &y)
bool operator< (const LocalVector< T > &x, const LocalVector< T > &y)
bool operator> (const LocalVector< T > &x, const LocalVector< T > &y)
bool operator<= (const LocalVector< T > &x, const LocalVector< T > &y)
bool operator>= (const LocalVector< T > &x, const LocalVector< T > &y)
Detailed Description
template<typename T>
class v8::LocalVector< T >
Definition at line 525 of file v8-local-handle.h.
Member Typedef Documentation
allocator_type
template<typename T >
using v8::LocalVector< T >::allocator_type = std::allocator<element_type> [private]
Definition at line 536 of file v8-local-handle.h.
const_iterator
template<typename T >
using v8::LocalVector< T >::const_iterator = internal::WrappedIterator<typename vector_type::const_iterator, const Local<T> >
Definition at line 553 of file v8-local-handle.h.
const_reference
template<typename T >
using v8::LocalVector< T >::const_reference = const value_type&
Definition at line 548 of file v8-local-handle.h.
difference_type
template<typename T >
using v8::LocalVector< T >::difference_type = ptrdiff_t
Definition at line 550 of file v8-local-handle.h.
element_type
template<typename T >
using v8::LocalVector< T >::element_type = internal::LocalUnchecked<T> [private]
Definition at line 527 of file v8-local-handle.h.
iterator
template<typename T >
using v8::LocalVector< T >::iterator = internal::WrappedIterator<typename vector_type::iterator, Local<T> >
Definition at line 551 of file v8-local-handle.h.
reference
template<typename T >
using v8::LocalVector< T >::reference = value_type&
Definition at line 547 of file v8-local-handle.h.
size_type
template<typename T >
using v8::LocalVector< T >::size_type = size_t
Definition at line 549 of file v8-local-handle.h.
value_type
template<typename T >
using v8::LocalVector< T >::value_type = Local<T>
Definition at line 546 of file v8-local-handle.h.
vector_type
template<typename T >
using v8::LocalVector< T >::vector_type = std::vector<element_type, allocator_type> [private]
Definition at line 543 of file v8-local-handle.h.
Constructor & Destructor Documentation
LocalVector() [1/3]
template<typename T >
v8::LocalVector< T >::LocalVector (Isolate * isolate) [inline], [explicit]
Definition at line 557 of file v8-local-handle.h.
: backing_(make_allocator(isolate)) {}
LocalVector() [2/3]
template<typename T >
v8::LocalVector< T >::LocalVector (Isolate * isolate, size_t n) [inline]
Definition at line 558 of file v8-local-handle.h.
      : backing_(n, make_allocator(isolate)) {}
LocalVector() [3/3]
template<typename T >
v8::LocalVector< T >::LocalVector (Isolate * isolate, std::initializer_list< Local< T >> init) [inline], [explicit]
Definition at line 560 of file v8-local-handle.h.
      : backing_(make_allocator(isolate)) {
    if (init.size() == 0) return;
    backing_.reserve(init.size());
    backing_.insert(backing_.end(), init.begin(), init.end());
  }
References v8::LocalVector< T >::backing_.
Member Function Documentation
at() [1/2]
template<typename T >
Local<T>& v8::LocalVector< T >::at (size_t n) [inline]
Definition at line 582 of file v8-local-handle.h.
{ return backing_.at(n); }
References v8::LocalVector< T >::backing_.
at() [2/2]
template<typename T >
const Local<T>& v8::LocalVector< T >::at (size_t n) const [inline]
Definition at line 583 of file v8-local-handle.h.
{ return backing_.at(n); }
References v8::LocalVector< T >::backing_.
back() [1/2]
template<typename T >
Local<T>& v8::LocalVector< T >::back () [inline]
Definition at line 587 of file v8-local-handle.h.
{ return backing_.back(); }
References v8::LocalVector< T >::backing_.
back() [2/2]
template<typename T >
const Local<T>& v8::LocalVector< T >::back () const [inline]
Definition at line 588 of file v8-local-handle.h.
{ return backing_.back(); }
References v8::LocalVector< T >::backing_.
begin() [1/2]
template<typename T >
const_iterator v8::LocalVector< T >::begin () const [inline], [noexcept]
Definition at line 568 of file v8-local-handle.h.
                                        {
    return const_iterator(backing_.begin());
  }
References v8::LocalVector< T >::backing_.
begin() [2/2]
template<typename T >
iterator v8::LocalVector< T >::begin () [inline], [noexcept]
Definition at line 567 of file v8-local-handle.h.
{ return iterator(backing_.begin()); }
References v8::LocalVector< T >::backing_.
Referenced by v8_inspector::V8Console::Assert(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCall(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCallAndReplaceFirstArgument(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCallWithDefaultArgument(), and v8::internal::MemoryMeasurement::ReportResults().
clear()
template<typename T >
void v8::LocalVector< T >::clear () [inline], [noexcept]
Definition at line 621 of file v8-local-handle.h.
{ backing_.clear(); }
References v8::LocalVector< T >::backing_.
data() [1/2]
template<typename T >
const Local<T>* v8::LocalVector< T >::data () const [inline], [noexcept]
Definition at line 591 of file v8-local-handle.h.
{ return backing_.data(); }
References v8::LocalVector< T >::backing_.
data() [2/2]
template<typename T >
Local<T>* v8::LocalVector< T >::data () [inline], [noexcept]
Definition at line 590 of file v8-local-handle.h.
{ return backing_.data(); }
References v8::LocalVector< T >::backing_.
Referenced by v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::parseAdditionalSerializationParameters().
emplace_back()
template<typename T >
template<typename... Args>
void v8::LocalVector< T >::emplace_back (Args &&... args) [inline]
Definition at line 617 of file v8-local-handle.h.
                                    {
    backing_.push_back(value_type{std::forward<Args>(args)...});
  }
References v8::base::args, and v8::LocalVector< T >::backing_.
empty()
template<typename T >
bool v8::LocalVector< T >::empty () const [inline], [noexcept]
Definition at line 575 of file v8-local-handle.h.
{ return backing_.empty(); }
References v8::LocalVector< T >::backing_.
Referenced by v8::debug::GetPrivateMembers(), and v8_inspector::V8Debugger::privateMethods().
end() [1/2]
template<typename T >
const_iterator v8::LocalVector< T >::end () const [inline], [noexcept]
Definition at line 572 of file v8-local-handle.h.
{ return const_iterator(backing_.end()); }
References v8::LocalVector< T >::backing_.
end() [2/2]
template<typename T >
iterator v8::LocalVector< T >::end () [inline], [noexcept]
Definition at line 571 of file v8-local-handle.h.
{ return iterator(backing_.end()); }
References v8::LocalVector< T >::backing_.
Referenced by v8_inspector::V8Console::Assert(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCall(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCallAndReplaceFirstArgument(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCallWithDefaultArgument(), and v8::internal::MemoryMeasurement::ReportResults().
front() [1/2]
template<typename T >
Local<T>& v8::LocalVector< T >::front () [inline]
Definition at line 585 of file v8-local-handle.h.
{ return backing_.front(); }
References v8::LocalVector< T >::backing_.
front() [2/2]
template<typename T >
const Local<T>& v8::LocalVector< T >::front () const [inline]
Definition at line 586 of file v8-local-handle.h.
{ return backing_.front(); }
References v8::LocalVector< T >::backing_.
insert() [1/3]
template<typename T >
iterator v8::LocalVector< T >::insert (const_iterator pos, const Local< T > & value) [inline]
Definition at line 593 of file v8-local-handle.h.
                                                             {
    return iterator(backing_.insert(pos.base(), value));
  }
References v8::LocalVector< T >::backing_, v8::internal::WrappedIterator< Iterator, ElementType >::base(), and v8::internal::value.
insert() [2/3]
template<typename T >
template<typename InputIt >
iterator v8::LocalVector< T >::insert (const_iterator pos, InputIt first, InputIt last) [inline]
Definition at line 598 of file v8-local-handle.h.
                                                                   {
    return iterator(backing_.insert(pos.base(), first, last));
  }
References v8::LocalVector< T >::backing_, and v8::internal::WrappedIterator< Iterator, ElementType >::base().
insert() [3/3]
template<typename T >
iterator v8::LocalVector< T >::insert (const_iterator pos, std::initializer_list< Local< T >> init) [inline]
Definition at line 602 of file v8-local-handle.h.
                                                                          {
    return iterator(backing_.insert(pos.base(), init.begin(), init.end()));
  }
References v8::LocalVector< T >::backing_, and v8::internal::WrappedIterator< Iterator, ElementType >::base().
make_allocator()
template<typename T >
static allocator_type v8::LocalVector< T >::make_allocator (Isolate * isolate) [inline], [static], [private], [noexcept]
Definition at line 538 of file v8-local-handle.h.
                                                                  {
    return allocator_type();
  }
operator=()
template<typename T >
LocalVector<T>& v8::LocalVector< T >::operator= (std::initializer_list< Local< T >> init) [inline]
Definition at line 606 of file v8-local-handle.h.
                                                                {
    backing_.clear();
    backing_.reserve(init.size());
    backing_.insert(backing_.end(), init.begin(), init.end());
    return *this;
  }
References v8::LocalVector< T >::backing_.
operator[]() [1/2]
template<typename T >
Local<T>& v8::LocalVector< T >::operator[] (size_t n) [inline]
Definition at line 579 of file v8-local-handle.h.
{ return backing_[n]; }
References v8::LocalVector< T >::backing_.
operator[]() [2/2]
template<typename T >
const Local<T>& v8::LocalVector< T >::operator[] (size_t n) const [inline]
Definition at line 580 of file v8-local-handle.h.
{ return backing_[n]; }
References v8::LocalVector< T >::backing_.
pop_back()
template<typename T >
void v8::LocalVector< T >::pop_back () [inline]
Definition at line 614 of file v8-local-handle.h.
{ backing_.pop_back(); }
References v8::LocalVector< T >::backing_.
push_back()
template<typename T >
void v8::LocalVector< T >::push_back (const Local< T > & x) [inline]
Definition at line 613 of file v8-local-handle.h.
{ backing_.push_back(x); }
References v8::LocalVector< T >::backing_.
Referenced by v8_inspector::V8Console::Assert(), v8::debug::GetPrivateMembers(), v8::Module::GetStalledTopLevelAwaitMessages(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::parseAdditionalSerializationParameters(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCall(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCallAndReplaceFirstArgument(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCallWithDefaultArgument(), v8_inspector::anonymous_namespace{custom-preview.cc}::reportError(), and v8::internal::MemoryMeasurement::ReportResults().
reserve()
template<typename T >
void v8::LocalVector< T >::reserve (size_t n) [inline]
Definition at line 576 of file v8-local-handle.h.
{ backing_.reserve(n); }
References v8::LocalVector< T >::backing_.
Referenced by v8::debug::GetPrivateMembers(), v8::Module::GetStalledTopLevelAwaitMessages(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCall(), and v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCallWithDefaultArgument().
resize()
template<typename T >
void v8::LocalVector< T >::resize (size_t n) [inline]
Definition at line 622 of file v8-local-handle.h.
{ backing_.resize(n); }
References v8::LocalVector< T >::backing_.
shrink_to_fit()
template<typename T >
void v8::LocalVector< T >::shrink_to_fit () [inline]
Definition at line 577 of file v8-local-handle.h.
{ backing_.shrink_to_fit(); }
References v8::LocalVector< T >::backing_.
size()
template<typename T >
size_t v8::LocalVector< T >::size () const [inline], [noexcept]
Definition at line 574 of file v8-local-handle.h.
{ return backing_.size(); }
References v8::LocalVector< T >::backing_.
Referenced by v8::debug::GetPrivateMembers(), v8_inspector::ValueMirror::getPrivateProperties(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::parseAdditionalSerializationParameters(), and v8_inspector::V8Debugger::privateMethods().
swap()
template<typename T >
void v8::LocalVector< T >::swap (LocalVector< T > & other) [inline]
Definition at line 623 of file v8-local-handle.h.
{ backing_.swap(other.backing_); }
References v8::LocalVector< T >::backing_.
Friends And Related Function Documentation
operator!=
template<typename T >
bool operator!= (const LocalVector< T > & x, const LocalVector< T > & y) [friend]
Definition at line 628 of file v8-local-handle.h.
                                                                           {
    return x.backing_ != y.backing_;
  }
operator<
template<typename T >
bool operator< (const LocalVector< T > & x, const LocalVector< T > & y) [friend]
Definition at line 631 of file v8-local-handle.h.
                                                                          {
    return x.backing_ < y.backing_;
  }
operator<=
template<typename T >
bool operator<= (const LocalVector< T > & x, const LocalVector< T > & y) [friend]
Definition at line 637 of file v8-local-handle.h.
                                                                           {
    return x.backing_ <= y.backing_;
  }
operator==
template<typename T >
bool operator== (const LocalVector< T > & x, const LocalVector< T > & y) [friend]
Definition at line 625 of file v8-local-handle.h.
                                                                           {
    return x.backing_ == y.backing_;
  }
operator>
template<typename T >
bool operator> (const LocalVector< T > & x, const LocalVector< T > & y) [friend]
Definition at line 634 of file v8-local-handle.h.
                                                                          {
    return x.backing_ > y.backing_;
  }
operator>=
template<typename T >
bool operator>= (const LocalVector< T > & x, const LocalVector< T > & y) [friend]
Definition at line 640 of file v8-local-handle.h.
                                                                           {
    return x.backing_ >= y.backing_;
  }
Member Data Documentation
backing_
template<typename T >
vector_type v8::LocalVector< T >::backing_ [private]
Definition at line 645 of file v8-local-handle.h.
Referenced by v8::LocalVector< T >::at(), v8::LocalVector< T >::back(), v8::LocalVector< T >::begin(), v8::LocalVector< T >::clear(), v8::LocalVector< T >::data(), v8::LocalVector< T >::emplace_back(), v8::LocalVector< T >::empty(), v8::LocalVector< T >::end(), v8::LocalVector< T >::front(), v8::LocalVector< T >::insert(), v8::LocalVector< T >::LocalVector(), v8::LocalVector< T >::operator=(), v8::LocalVector< T >::operator[](), v8::LocalVector< T >::pop_back(), v8::LocalVector< T >::push_back(), v8::LocalVector< T >::reserve(), v8::LocalVector< T >::resize(), v8::LocalVector< T >::shrink_to_fit(), v8::LocalVector< T >::size(), and v8::LocalVector< T >::swap().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-local-handle.h