v8::Signature Class Reference
A Signature specifies which receiver is valid for a function.
#include <v8-template.h>
Static Public Member Functions
static Local< Signature > New (Isolate *isolate, Local< FunctionTemplate > receiver=Local< FunctionTemplate >())
static Signature * Cast (Data *data)
Private Member Functions
Signature ()
Static Private Member Functions
static void CheckCast (Data *that)
Additional Inherited Members
Detailed Description
A Signature specifies which receiver is valid for a function.
A receiver matches a given signature if the receiver (or any of its hidden prototypes) was created from the signature's FunctionTemplate, or from a FunctionTemplate that inherits directly or indirectly from the signature's FunctionTemplate.
Definition at line 1114 of file v8-template.h.
Constructor & Destructor Documentation
Signature()
v8::Signature::Signature () [private]
Member Function Documentation
Cast()
Signature * v8::Signature::Cast (Data * data) [inline], [static]
Definition at line 1158 of file v8-template.h.
                                     {
#ifdef V8_ENABLE_CHECKS
  CheckCast(data);
#endif
  return reinterpret_cast<Signature*>(data);
}
References CheckCast().
CheckCast()
void v8::Signature::CheckCast (Data * that) [static], [private]
Definition at line 7352 of file api.cc.
                                      {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsFunctionTemplateInfo(*obj), "v8::Signature::Cast",
                  "Value is not a Signature");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Referenced by Cast().
New()
Local< Signature > v8::Signature::New (Isolate * isolate, Local< FunctionTemplate > receiver = Local<FunctionTemplate>()) [static]
Definition at line 1220 of file api.cc.
                                                                  {
  return Local<Signature>::Cast(receiver);
}
References v8::Local< T >::Cast().
Referenced by v8::Shell::CreateNodeTemplates(), v8::Shell::CreateTestFastCApiTemplate(), and v8::Shell::CreateWorkerTemplate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-template.h
/mnt/V8SourceCode/src/api/api.cc