v8::internal::interpreter::Register Class Reference
#include <bytecode-register.h>
Public Member Functions
constexpr Register (int index=kInvalidIndex)
constexpr int index () const
constexpr bool is_parameter () const
constexpr bool is_valid () const
constexpr int ToParameterIndex () const
constexpr bool is_receiver () const
constexpr bool is_function_closure () const
constexpr bool is_current_context () const
constexpr bool is_bytecode_array () const
constexpr bool is_bytecode_offset () const
constexpr bool is_feedback_vector () const
constexpr OperandSize SizeOfOperand () const
constexpr int32_t ToOperand () const
constexpr std::optional< Bytecode > TryToShortStar () const
std::string ToString () const
constexpr bool operator== (const Register &other) const
constexpr bool operator!= (const Register &other) const
constexpr bool operator< (const Register &other) const
constexpr bool operator<= (const Register &other) const
constexpr bool operator> (const Register &other) const
constexpr bool operator>= (const Register &other) const
Static Public Member Functions
static constexpr Register FromParameterIndex (int index)
static constexpr Register receiver ()
static constexpr Register invalid_value ()
static constexpr Register function_closure ()
static constexpr Register current_context ()
static constexpr Register bytecode_array ()
static constexpr Register bytecode_offset ()
static constexpr Register feedback_vector ()
static constexpr Register argument_count ()
static constexpr Register virtual_accumulator ()
static constexpr Register FromOperand (int32_t operand)
static constexpr Register FromShortStar (Bytecode bytecode)
Private Attributes
int index_
Static Private Attributes
static constexpr int kInvalidIndex = kMaxInt
static constexpr int kRegisterFileStartOffset
static constexpr int kFirstParamRegisterIndex
static constexpr int kFunctionClosureRegisterIndex
static constexpr int kCurrentContextRegisterIndex
static constexpr int kBytecodeArrayRegisterIndex
static constexpr int kBytecodeOffsetRegisterIndex
static constexpr int kFeedbackVectorRegisterIndex
static constexpr int kCallerPCOffsetRegisterIndex
static constexpr int kArgumentCountRegisterIndex
Detailed Description
Definition at line 27 of file bytecode-register.h.
Constructor & Destructor Documentation
Register()
constexpr v8::internal::interpreter::Register::Register (int index = kInvalidIndex) [inline], [explicit], [constexpr]
Definition at line 29 of file bytecode-register.h.
: index_(index) {}
Member Function Documentation
argument_count()
constexpr Register v8::internal::interpreter::Register::argument_count () [static], [constexpr]
Definition at line 259 of file bytecode-register.h.
                                            {
  return Register(kArgumentCountRegisterIndex);
}
References v8::internal::ETWJITInterface::Register().
bytecode_array()
constexpr Register v8::internal::interpreter::Register::bytecode_array () [static], [constexpr]
Definition at line 229 of file bytecode-register.h.
                                            {
  return Register(kBytecodeArrayRegisterIndex);
}
References v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::interpreter::InterpreterAssembler::BytecodeArrayTaggedPointer(), and v8::internal::interpreter::BytecodeHandlerReducer< Next >::BytecodeArrayTaggedPointer().
bytecode_offset()
constexpr Register v8::internal::interpreter::Register::bytecode_offset () [static], [constexpr]
Definition at line 237 of file bytecode-register.h.
                                             {
  return Register(kBytecodeOffsetRegisterIndex);
}
References v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::interpreter::InterpreterAssembler::ReloadBytecodeOffset(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::ReloadBytecodeOffset(), and v8::internal::interpreter::InterpreterAssembler::SaveBytecodeOffset().
current_context()
constexpr Register v8::internal::interpreter::Register::current_context () [static], [constexpr]
Definition at line 221 of file bytecode-register.h.
                                             {
  return Register(kCurrentContextRegisterIndex);
}
References v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildRegisterFrameInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildTryCatch(), v8::internal::interpreter::BytecodeGenerator::BuildTryFinally(), v8::internal::baseline::BaselineAssembler::ContextOperand(), v8::internal::maglev::CompactInterpreterFrameState::ForEachRegister(), v8::internal::maglev::InterpreterFrameState::get(), v8::internal::interpreter::InterpreterAssembler::GetContext(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::GetContext(), v8::internal::maglev::CompactInterpreterFrameState::GetValueOf(), v8::internal::baseline::BaselineAssembler::LoadContext(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::MaglevSubGraphBuilder(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop(), v8::internal::Debug::PerformSideEffectCheckAtBytecode(), v8::internal::maglev::InterpreterFrameState::set(), v8::internal::interpreter::InterpreterAssembler::SetContext(), v8::internal::baseline::BaselineAssembler::StoreContext(), and v8::internal::interpreter::BytecodeGenerator::ContextScope::~ContextScope().
feedback_vector()
constexpr Register v8::internal::interpreter::Register::feedback_vector () [static], [constexpr]
Definition at line 245 of file bytecode-register.h.
                                             {
  return Register(kFeedbackVectorRegisterIndex);
}
References v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER(), v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVector(), and v8::internal::interpreter::InterpreterAssembler::LoadFeedbackVector().
FromOperand()
static constexpr Register v8::internal::interpreter::Register::FromOperand (int32_t operand) [inline], [static], [constexpr]
Definition at line 77 of file bytecode-register.h.
                                                         {
    return Register(kRegisterFileStartOffset - operand);
  }
References v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::interpreter::BytecodeDecoder::DecodeRegisterOperand(), v8::internal::BytecodeArray::incoming_new_target_or_generator_register(), and v8::internal::interpreter::BytecodeRegisterOptimizer::OperandToRegister().
FromParameterIndex()
constexpr Register v8::internal::interpreter::Register::FromParameterIndex (int index) [static], [constexpr]
Definition at line 201 of file bytecode-register.h.
                                                         {
  DCHECK_GE(index, 0);
  int register_index = kFirstParamRegisterIndex - index;
  DCHECK_LT(register_index, 0);
  return Register(register_index);
}
References DCHECK_GE, DCHECK_LT, v8::internal::index, and v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::maglev::MaglevGraphBuilder::Build(), v8::internal::interpreter::BytecodeRegisterOptimizer::BytecodeRegisterOptimizer(), v8::internal::maglev::RegisterFrameArray< T >::CopyFrom(), v8::internal::maglev::RegisterFrameArray< T >::data_begin(), v8::internal::maglev::RegisterFrameArray< T >::DataSize(), v8::internal::interpreter::InterpreterAssembler::ExportParametersAndRegisterFile(), v8::internal::maglev::CompactInterpreterFrameState::ForEachParameter(), v8::internal::maglev::MaglevGraphBuilder::GetArgument(), v8::internal::interpreter::BytecodeArrayIterator::GetParameter(), v8::internal::interpreter::BytecodeArrayBuilder::Parameter(), v8::internal::interpreter::BytecodeArrayBuilder::Receiver(), v8::internal::maglev::RegisterFrameArray< T >::RegisterFrameArray(), v8::internal::maglev::MaglevGraphBuilder::SetArgument(), and v8::internal::TF_BUILTIN().
FromShortStar()
static constexpr Register v8::internal::interpreter::Register::FromShortStar (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 81 of file bytecode-register.h.
                                                             {
    DCHECK(Bytecodes::IsShortStar(bytecode));
    return Register(static_cast<int>(Bytecode::kStar0) -
                    static_cast<int>(bytecode));
  }
References v8::internal::DCHECK(), v8::internal::interpreter::Bytecodes::IsShortStar(), and v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::interpreter::BytecodeArrayIterator::GetStarTargetRegister(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateAssignments(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLiveness().
function_closure()
constexpr Register v8::internal::interpreter::Register::function_closure () [static], [constexpr]
Definition at line 213 of file bytecode-register.h.
                                              {
  return Register(kFunctionClosureRegisterIndex);
}
References v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDeclareCall(), v8::internal::interpreter::BytecodeGenerator::BuildGeneratorObjectVariableInitialization(), v8::internal::maglev::MaglevGraphBuilder::BuildRegisterFrameInitialization(), v8::internal::baseline::BaselineAssembler::FunctionOperand(), v8::internal::interpreter::BytecodeGenerator::GenerateBaseConstructorBody(), v8::internal::maglev::InterpreterFrameState::get(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::baseline::BaselineAssembler::LoadFunction(), v8::internal::interpreter::InterpreterAssembler::LoadFunctionClosure(), v8::internal::maglev::InterpreterFrameState::set(), and v8::internal::interpreter::BytecodeGenerator::VisitThisFunctionVariable().
index()
constexpr int v8::internal::interpreter::Register::index () const [inline], [constexpr]
Definition at line 31 of file bytecode-register.h.
{ return index_; }
Referenced by v8::internal::compiler::BytecodeLoopAssignments::Add(), v8::internal::compiler::BytecodeLoopAssignments::AddList(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameValues(), v8::internal::maglev::MaglevGraphBuilder::BuildMergeStates(), v8::internal::maglev::MaglevGraphBuilder::BuildRegisterFrameInitialization(), v8::internal::interpreter::BytecodeRegisterOptimizer::BytecodeRegisterOptimizer(), v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod(), v8::internal::maglev::InterpretedDeoptFrame::ComputeReturnOffset(), v8::internal::maglev::RegisterFrameArray< T >::CopyFrom(), v8::internal::maglev::RegisterFrameArray< T >::data_begin(), v8::internal::maglev::RegisterFrameArray< T >::DataSize(), v8::internal::interpreter::BytecodeDecoder::DecodeRegisterListOperand(), v8::internal::BreakIterator::GetBreakLocation(), v8::internal::compiler::BytecodeGraphBuilder::GetCallArgumentsFromRegisters(), v8::internal::compiler::BytecodeGraphBuilder::GetConstructArgumentsFromRegister(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::interpreter::BytecodeRegisterOptimizer::GetInputRegisterList(), v8::internal::interpreter::BytecodeRegisterOptimizer::GetRegisterInfoTableIndex(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterListOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterPairOperand(), v8::internal::interpreter::BytecodeRegisterAllocator::GrowRegisterList(), v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value(), v8::internal::maglev::LazyDeoptInfo::InReturnValues(), v8::internal::maglev::LazyDeoptInfo::IsResultRegister(), v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), v8::internal::maglev::RegisterFrameArray< T >::operator[](), v8::internal::interpreter::BytecodeRegisterOptimizer::OutputRegisterTransfer(), v8::internal::Debug::PerformSideEffectCheckAtBytecode(), v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareOutputRegister(), v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareOutputRegisterList(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::BytecodeGraphBuilder::ProcessCallRuntimeArguments(), v8::internal::compiler::BytecodeGraphBuilder::ProcessCallVarArgs(), v8::internal::baseline::BaselineCompiler::PrologueFillFrame(), v8::internal::interpreter::BytecodeRegisterAllocator::RegisterIsLive(), v8::internal::interpreter::BytecodeArrayBuilder::RegisterIsValid(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterListAllocateEvent(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterListFreeEvent(), v8::internal::interpreter::BytecodeArrayBuilder::RegisterListIsValid(), v8::internal::compiler::BytecodeGraphBuilder::Environment::RegisterToValuesIndex(), v8::internal::interpreter::BytecodeRegisterAllocator::ReleaseRegister(), v8::internal::BytecodeArray::set_incoming_new_target_or_generator_register(), v8::internal::maglev::MaglevGraphBuilder::StoreRegisterPair(), v8::internal::interpreter::HandlerTableBuilder::ToHandlerTable(), ToString(), v8::internal::anonymous_namespace{isolate.cc}::TouchesRegister(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLiveness(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForInOperand(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForOutOperand(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness(), and v8::internal::interpreter::BytecodeGenerator::ContextScope::~ContextScope().
invalid_value()
static constexpr Register v8::internal::interpreter::Register::invalid_value () [inline], [static], [constexpr]
Definition at line 42 of file bytecode-register.h.
{ return Register(); }
References v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::maglev::MaglevGraphBuilder::Build(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForEagerCall(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetResultLocationAndSizeHelper< index >::GetResultLocationAndSize(), v8::internal::BytecodeArray::incoming_new_target_or_generator_register(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjectValue(), v8::internal::interpreter::HandlerTableBuilder::NewHandlerEntry(), v8::internal::interpreter::BytecodeGenerator::VisitClassLiteral(), and v8::internal::interpreter::BytecodeGenerator::VisitPropertyLoad().
is_bytecode_array()
constexpr bool v8::internal::interpreter::Register::is_bytecode_array () const [constexpr]
Definition at line 233 of file bytecode-register.h.
                                                 {
  return index() == kBytecodeArrayRegisterIndex;
}
References v8::internal::index.
is_bytecode_offset()
constexpr bool v8::internal::interpreter::Register::is_bytecode_offset () const [constexpr]
Definition at line 241 of file bytecode-register.h.
                                                  {
  return index() == kBytecodeOffsetRegisterIndex;
}
References v8::internal::index.
is_current_context()
constexpr bool v8::internal::interpreter::Register::is_current_context () const [constexpr]
Definition at line 225 of file bytecode-register.h.
                                                  {
  return index() == kCurrentContextRegisterIndex;
}
References v8::internal::index.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::LoadContextSlot(), v8::internal::compiler::BytecodeGraphBuilder::Environment::LookupRegister(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::interpreter::BytecodeArrayBuilder::RegisterIsValid(), v8::internal::interpreter::BytecodeArrayBuilder::StoreContextSlot(), and ToString().
is_feedback_vector()
constexpr bool v8::internal::interpreter::Register::is_feedback_vector () const [constexpr]
Definition at line 249 of file bytecode-register.h.
                                                  {
  return index() == kFeedbackVectorRegisterIndex;
}
References v8::internal::index.
is_function_closure()
constexpr bool v8::internal::interpreter::Register::is_function_closure () const [constexpr]
Definition at line 217 of file bytecode-register.h.
                                                   {
  return index() == kFunctionClosureRegisterIndex;
}
References v8::internal::index.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::Environment::LookupRegister(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::interpreter::BytecodeArrayBuilder::RegisterIsValid(), and ToString().
is_parameter()
constexpr bool v8::internal::interpreter::Register::is_parameter () const [inline], [constexpr]
Definition at line 32 of file bytecode-register.h.
{ return index() < 0; }
References v8::internal::index.
Referenced by v8::internal::compiler::BytecodeLoopAssignments::Add(), v8::internal::compiler::BytecodeLoopAssignments::AddList(), v8::internal::maglev::InterpretedDeoptFrame::ComputeReturnOffset(), v8::internal::maglev::InterpreterFrameState::get(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::maglev::CompactInterpreterFrameState::GetValueOf(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::interpreter::BytecodeArrayBuilder::RegisterIsValid(), v8::internal::compiler::BytecodeGraphBuilder::Environment::RegisterToValuesIndex(), v8::internal::maglev::InterpreterFrameState::set(), ToString(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForInOperand(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForOutOperand().
is_receiver()
constexpr bool v8::internal::interpreter::Register::is_receiver () const [inline], [constexpr]
Definition at line 39 of file bytecode-register.h.
{ return ToParameterIndex() == 0; }
is_valid()
constexpr bool v8::internal::interpreter::Register::is_valid () const [inline], [constexpr]
Definition at line 33 of file bytecode-register.h.
{ return index_ != kInvalidIndex; }
References v8::internal::trap_handler::kInvalidIndex.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildFillArrayWithIterator(), v8::internal::interpreter::BytecodeGenerator::BuildGetIteratorRecord(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorNext(), v8::internal::maglev::MaglevGraphBuilder::BuildRegisterFrameInitialization(), v8::internal::maglev::MaglevGraphBuilder::CanInlineCall(), v8::internal::interpreter::BytecodeGenerator::current_disposables_stack(), v8::internal::compiler::BytecodeGraphBuilder::Environment::Environment(), v8::internal::interpreter::BytecodeGenerator::FinalizeBytecode(), v8::internal::interpreter::BytecodeGenerator::generator_object(), v8::internal::maglev::CompactInterpreterFrameState::GetValueOf(), v8::internal::maglev::LazyDeoptInfo::HasResultLocation(), v8::internal::interpreter::BytecodeGenerator::incoming_new_target(), v8::internal::maglev::LazyDeoptInfo::InReturnValues(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessGraph(), v8::internal::maglev::Phi::PrintParams(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::interpreter::BytecodeArrayBuilder::RegisterIsValid(), v8::internal::BytecodeArray::set_incoming_new_target_or_generator_register(), v8::internal::interpreter::BytecodeGenerator::VisitKeyedSuperPropertyLoad(), and v8::internal::interpreter::BytecodeGenerator::VisitNamedSuperPropertyLoad().
operator!=()
constexpr bool v8::internal::interpreter::Register::operator!= (const Register & other) const [inline], [constexpr]
Definition at line 103 of file bytecode-register.h.
                                                         {
    return index() != other.index();
  }
References index(), and v8::internal::index.
operator<()
constexpr bool v8::internal::interpreter::Register::operator< (const Register & other) const [inline], [constexpr]
Definition at line 106 of file bytecode-register.h.
                                                        {
    return index() < other.index();
  }
References index(), and v8::internal::index.
operator<=()
constexpr bool v8::internal::interpreter::Register::operator<= (const Register & other) const [inline], [constexpr]
Definition at line 109 of file bytecode-register.h.
                                                         {
    return index() <= other.index();
  }
References index(), and v8::internal::index.
operator==()
constexpr bool v8::internal::interpreter::Register::operator== (const Register & other) const [inline], [constexpr]
Definition at line 100 of file bytecode-register.h.
                                                         {
    return index() == other.index();
  }
References index(), and v8::internal::index.
operator>()
constexpr bool v8::internal::interpreter::Register::operator> (const Register & other) const [inline], [constexpr]
Definition at line 112 of file bytecode-register.h.
                                                        {
    return index() > other.index();
  }
References index(), and v8::internal::index.
operator>=()
constexpr bool v8::internal::interpreter::Register::operator>= (const Register & other) const [inline], [constexpr]
Definition at line 115 of file bytecode-register.h.
                                                         {
    return index() >= other.index();
  }
References index(), and v8::internal::index.
receiver()
static constexpr Register v8::internal::interpreter::Register::receiver () [inline], [static], [constexpr]
Definition at line 38 of file bytecode-register.h.
{ return FromParameterIndex(0); }
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), and v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper().
SizeOfOperand()
constexpr OperandSize v8::internal::interpreter::Register::SizeOfOperand () const [constexpr]
Definition at line 263 of file bytecode-register.h.
                                                    {
  int32_t operand = ToOperand();
  if (operand >= kMinInt8 && operand <= kMaxInt8) {
    return OperandSize::kByte;
  } else if (operand >= kMinInt16 && operand <= kMaxInt16) {
    return OperandSize::kShort;
  } else {
    return OperandSize::kQuad;
  }
}
References v8::internal::interpreter::kByte, v8::internal::kMaxInt16, v8::internal::kMaxInt8, v8::internal::kMinInt16, v8::internal::kMinInt8, v8::internal::interpreter::kQuad, and v8::internal::interpreter::kShort.
ToOperand()
constexpr int32_t v8::internal::interpreter::Register::ToOperand () const [inline], [constexpr]
Definition at line 74 of file bytecode-register.h.
                                      {
    return kRegisterFileStartOffset - index_;
  }
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::GetInputOutputRegisterOperand(), v8::internal::interpreter::BytecodeArrayBuilder::GetInputRegisterListOperand(), v8::internal::interpreter::BytecodeArrayBuilder::GetInputRegisterOperand(), v8::internal::interpreter::BytecodeArrayBuilder::GetOutputRegisterListOperand(), v8::internal::interpreter::BytecodeArrayBuilder::GetOutputRegisterOperand(), v8::internal::interpreter::InterpreterAssembler::LoadAndUntagRegister(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::LoadAndUntagRegister(), v8::internal::interpreter::InterpreterAssembler::LoadRegister(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::LoadRegister(), v8::internal::interpreter::BytecodeArrayBuilder::OutputLdarRaw(), v8::internal::interpreter::BytecodeArrayBuilder::OutputMovRaw(), v8::internal::interpreter::BytecodeArrayBuilder::OutputStarRaw(), v8::internal::baseline::BaselineAssembler::RegisterFrameAddress(), v8::internal::baseline::BaselineAssembler::RegisterFrameOperand(), v8::internal::interpreter::InterpreterAssembler::RegisterLocation(), v8::internal::interpreter::InterpreterAssembler::SaveBytecodeOffset(), v8::internal::BytecodeArray::set_incoming_new_target_or_generator_register(), and v8::internal::interpreter::InterpreterAssembler::StoreRegister().
ToParameterIndex()
constexpr int v8::internal::interpreter::Register::ToParameterIndex () const [constexpr]
Definition at line 208 of file bytecode-register.h.
                                               {
  DCHECK(is_parameter());
  return kFirstParamRegisterIndex - index();
}
References v8::internal::DCHECK(), and v8::internal::index.
Referenced by v8::internal::compiler::BytecodeLoopAssignments::Add(), v8::internal::compiler::BytecodeLoopAssignments::AddList(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameValues(), v8::internal::maglev::InterpretedDeoptFrame::ComputeReturnOffset(), v8::internal::maglev::InterpreterFrameState::get(), v8::internal::maglev::CompactInterpreterFrameState::GetValueOf(), v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::interpreter::BytecodeArrayBuilder::RegisterIsValid(), v8::internal::compiler::BytecodeGraphBuilder::Environment::RegisterToValuesIndex(), v8::internal::maglev::InterpreterFrameState::set(), and ToString().
ToString()
std::string v8::internal::interpreter::Register::ToString () const
Definition at line 11 of file bytecode-register.cc.
                                   {
  if (is_current_context()) {
    return std::string("<context>");
  } else if (is_function_closure()) {
    return std::string("<closure>");
  } else if (*this == virtual_accumulator()) {
    return std::string("<accumulator>");
  } else if (is_parameter()) {
    int parameter_index = ToParameterIndex();
    if (parameter_index == 0) {
      return std::string("<this>");
    } else {
      std::ostringstream s;
      s << "a" << parameter_index - 1;
      return s.str();
    }
  } else {
    std::ostringstream s;
    s << "r" << index();
    return s.str();
  }
}
References index(), is_current_context(), is_function_closure(), is_parameter(), v8::internal::string, ToParameterIndex(), and virtual_accumulator().
Referenced by v8::internal::interpreter::BytecodeDecoder::Decode(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::PrintBeforeMerge(), v8::internal::maglev::InitialValue::PrintParams(), v8::internal::maglev::Phi::PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
TryToShortStar()
constexpr std::optional<Bytecode> v8::internal::interpreter::Register::TryToShortStar () const [inline], [constexpr]
Definition at line 87 of file bytecode-register.h.
                                                         {
    if (index() >= 0 && index() < Bytecodes::kShortStarCount) {
      Bytecode bytecode =
          static_cast<Bytecode>(static_cast<int>(Bytecode::kStar0) - index());
      DCHECK_GE(bytecode, Bytecode::kFirstShortStar);
      DCHECK_LE(bytecode, Bytecode::kLastShortStar);
      return bytecode;
    }
    return {};
  }
References DCHECK_GE, DCHECK_LE, v8::internal::index, v8::internal::interpreter::kFirstShortStar, v8::internal::interpreter::kLastShortStar, and v8::internal::interpreter::Bytecodes::kShortStarCount.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::OutputStarRaw().
virtual_accumulator()
constexpr Register v8::internal::interpreter::Register::virtual_accumulator () [static], [constexpr]
Definition at line 254 of file bytecode-register.h.
                                                 {
  return Register(kCallerPCOffsetRegisterIndex);
}
References v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::maglev::InterpreterFrameState::accumulator(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameValues(), v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad(), v8::internal::maglev::InterpretedDeoptFrame::ComputeReturnOffset(), v8::internal::maglev::MaglevGraphBuilder::FindContinuationForPolymorphicPropertyLoad(), v8::internal::maglev::CompactInterpreterFrameState::ForEachValue(), v8::internal::maglev::InterpreterFrameState::get(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetResultLocationAndSizeForBytecode(), v8::internal::maglev::CompactInterpreterFrameState::GetValueOf(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::InsertTaggingForPhis(), v8::internal::maglev::InterpreterFrameState::InterpreterFrameState(), v8::internal::maglev::LazyDeoptInfo::IsResultRegister(), v8::internal::maglev::MergePointInterpreterFrameState::NewForCatchBlock(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves(), v8::internal::maglev::InterpreterFrameState::set(), v8::internal::maglev::InterpreterFrameState::set_accumulator(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope(), ToString(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess(), and v8::internal::maglev::MaglevGraphBuilder::VisitCompareOperation().
Member Data Documentation
index_
int v8::internal::interpreter::Register::index_ [private]
Definition at line 146 of file bytecode-register.h.
kArgumentCountRegisterIndex
constexpr int v8::internal::interpreter::Register::kArgumentCountRegisterIndex [static], [constexpr], [private]
Initial value:
=
      OffsetFromFPToRegisterIndex(InterpreterFrameConstants::kArgCOffset)
Definition at line 143 of file bytecode-register.h.
kBytecodeArrayRegisterIndex
constexpr int v8::internal::interpreter::Register::kBytecodeArrayRegisterIndex [static], [constexpr], [private]
Initial value:
=
      OffsetFromFPToRegisterIndex(
          InterpreterFrameConstants::kBytecodeArrayFromFp)
Definition at line 132 of file bytecode-register.h.
kBytecodeOffsetRegisterIndex
constexpr int v8::internal::interpreter::Register::kBytecodeOffsetRegisterIndex [static], [constexpr], [private]
Initial value:
=
      OffsetFromFPToRegisterIndex(
          InterpreterFrameConstants::kBytecodeOffsetFromFp)
Definition at line 135 of file bytecode-register.h.
kCallerPCOffsetRegisterIndex
constexpr int v8::internal::interpreter::Register::kCallerPCOffsetRegisterIndex [static], [constexpr], [private]
Initial value:
=
      OffsetFromFPToRegisterIndex(InterpreterFrameConstants::kCallerPCOffset)
Definition at line 141 of file bytecode-register.h.
kCurrentContextRegisterIndex
constexpr int v8::internal::interpreter::Register::kCurrentContextRegisterIndex [static], [constexpr], [private]
Initial value:
=
      OffsetFromFPToRegisterIndex(StandardFrameConstants::kContextOffset)
Definition at line 130 of file bytecode-register.h.
kFeedbackVectorRegisterIndex
constexpr int v8::internal::interpreter::Register::kFeedbackVectorRegisterIndex [static], [constexpr], [private]
Initial value:
=
      OffsetFromFPToRegisterIndex(
          InterpreterFrameConstants::kFeedbackVectorFromFp)
Definition at line 138 of file bytecode-register.h.
kFirstParamRegisterIndex
constexpr int v8::internal::interpreter::Register::kFirstParamRegisterIndex [static], [constexpr], [private]
Initial value:
=
      OffsetFromFPToRegisterIndex(InterpreterFrameConstants::kFirstParamFromFp)
Definition at line 126 of file bytecode-register.h.
kFunctionClosureRegisterIndex
constexpr int v8::internal::interpreter::Register::kFunctionClosureRegisterIndex [static], [constexpr], [private]
Initial value:
=
      OffsetFromFPToRegisterIndex(StandardFrameConstants::kFunctionOffset)
Definition at line 128 of file bytecode-register.h.
kInvalidIndex
constexpr int v8::internal::interpreter::Register::kInvalidIndex = kMaxInt [static], [constexpr], [private]
Definition at line 122 of file bytecode-register.h.
kRegisterFileStartOffset
constexpr int v8::internal::interpreter::Register::kRegisterFileStartOffset [static], [constexpr], [private]
Initial value:
=
      OffsetFromFPToRegisterIndex(0)
Definition at line 124 of file bytecode-register.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/bytecode-register.h
/mnt/V8SourceCode/src/interpreter/bytecode-register.cc