v8::internal::RegExpText Class Reference
#include <regexp-ast.h>
Public Member Functions
RegExpText (Zone *zone)
DECL_BOILERPLATE (Text)
bool IsTextElement () override
int min_match () override
int max_match () override
void AppendToText (RegExpText *text, Zone *zone) override
void AddElement (TextElement elm, Zone *zone)
ZoneList< TextElement > * elements ()
bool StartsWithAtom () const
RegExpAtom * FirstAtom () const
Private Attributes
ZoneList< TextElement > elements_
int length_ = 0
Additional Inherited Members
Detailed Description
Definition at line 524 of file regexp-ast.h.
Constructor & Destructor Documentation
RegExpText()
v8::internal::RegExpText::RegExpText (Zone * zone) [inline], [explicit]
Definition at line 526 of file regexp-ast.h.
: elements_(2, zone) {}
Member Function Documentation
AddElement()
void v8::internal::RegExpText::AddElement (TextElement elm, Zone * zone) [inline]
Definition at line 534 of file regexp-ast.h.
                                               {
    elements_.Add(elm, zone);
    length_ += elm.length();
  }
References elements_, v8::internal::TextElement::length(), and length_.
Referenced by v8::internal::RegExpClassRanges::AppendToText(), v8::internal::RegExpAtom::AppendToText(), AppendToText(), and v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms().
AppendToText()
void v8::internal::RegExpText::AppendToText (RegExpText * text, Zone * zone) [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 205 of file regexp-compiler.cc.
                                                          {
  for (int i = 0; i < elements()->length(); i++)
    text->AddElement(elements()->at(i), zone);
}
References AddElement().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::FlushText().
DECL_BOILERPLATE()
v8::internal::RegExpText::DECL_BOILERPLATE (Text)
elements()
ZoneList<TextElement>* v8::internal::RegExpText::elements () [inline]
Definition at line 538 of file regexp-ast.h.
{ return &elements_; }
References elements_.
Referenced by v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitText(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitText().
FirstAtom()
RegExpAtom * v8::internal::RegExpText::FirstAtom () const
Definition at line 449 of file regexp-ast.cc.
{ return elements_.at(0).atom(); }
References elements_.
IsTextElement()
bool v8::internal::RegExpText::IsTextElement () [inline], [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 530 of file regexp-ast.h.
{ return true; }
max_match()
int v8::internal::RegExpText::max_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 532 of file regexp-ast.h.
{ return length_; }
References length_.
min_match()
int v8::internal::RegExpText::min_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 531 of file regexp-ast.h.
{ return length_; }
References length_.
StartsWithAtom()
bool v8::internal::RegExpText::StartsWithAtom () const
Definition at line 444 of file regexp-ast.cc.
                                      {
  if (elements_.length() == 0) return false;
  return elements_.at(0).text_type() == TextElement::ATOM;
}
References v8::internal::TextElement::ATOM, and elements_.
Member Data Documentation
elements_
ZoneList<TextElement> v8::internal::RegExpText::elements_ [private]
Definition at line 544 of file regexp-ast.h.
Referenced by AddElement(), elements(), FirstAtom(), and StartsWithAtom().
length_
int v8::internal::RegExpText::length_ = 0 [private]
Definition at line 545 of file regexp-ast.h.
Referenced by AddElement(), max_match(), and min_match().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-ast.cc
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc