v8::internal::V8HeapExplorer Class Reference
#include <heap-snapshot-generator.h>
Public Types
using TemporaryGlobalObjectTags = std::vector< std::pair< v8::Global< v8::Object >, const char * > >
Public Member Functions
V8HeapExplorer (HeapSnapshot *snapshot, SnapshottingProgressReportingInterface *progress, v8::HeapProfiler::ObjectNameResolver *resolver)
~V8HeapExplorer () override=default
V8HeapExplorer (const V8HeapExplorer &)=delete
V8HeapExplorer & operator= (const V8HeapExplorer &)=delete
Isolate * isolate ()
HeapEntry * AllocateEntry (HeapThing ptr) override
HeapEntry * AllocateEntry (Tagged< Smi > smi) override
uint32_t EstimateObjectsCount ()
void PopulateLineEnds ()
bool IterateAndExtractReferences (HeapSnapshotGenerator *generator)
TemporaryGlobalObjectTags CollectTemporaryGlobalObjectsTags ()
void MakeGlobalObjectTagMap (TemporaryGlobalObjectTags &&)
void TagBuiltinCodeObject (Tagged< Code > code, const char *name)
HeapEntry * AddEntry (Address address, HeapEntry::Type type, const char *name, size_t size)
Static Public Member Functions
static Tagged< JSFunction > GetConstructor (Isolate *isolate, Tagged< JSReceiver > receiver)
static Tagged< String > GetConstructorName (Isolate *isolate, Tagged< JSObject > object)
Private Member Functions
void MarkVisitedField (int offset)
HeapEntry * AddEntry (Tagged< HeapObject > object)
HeapEntry * AddEntry (Tagged< HeapObject > object, HeapEntry::Type type, const char *name)
const char * GetSystemEntryName (Tagged< HeapObject > object)
HeapEntry::Type GetSystemEntryType (Tagged< HeapObject > object)
Tagged< JSFunction > GetLocationFunction (Tagged< HeapObject > object)
void ExtractLocation (HeapEntry *entry, Tagged< HeapObject > object)
void ExtractLocationForJSFunction (HeapEntry *entry, Tagged< JSFunction > func)
void ExtractReferences (HeapEntry *entry, Tagged< HeapObject > obj)
void ExtractJSGlobalProxyReferences (HeapEntry *entry, Tagged< JSGlobalProxy > proxy)
void ExtractJSObjectReferences (HeapEntry *entry, Tagged< JSObject > js_obj)
void ExtractStringReferences (HeapEntry *entry, Tagged< String > obj)
void ExtractSymbolReferences (HeapEntry *entry, Tagged< Symbol > symbol)
void ExtractJSCollectionReferences (HeapEntry *entry, Tagged< JSCollection > collection)
void ExtractJSWeakCollectionReferences (HeapEntry *entry, Tagged< JSWeakCollection > collection)
void ExtractEphemeronHashTableReferences (HeapEntry *entry, Tagged< EphemeronHashTable > table)
void ExtractJSDisposableStackReferences (HeapEntry *entry, Tagged< JSDisposableStackBase > disposable_stack)
void ExtractContextReferences (HeapEntry *entry, Tagged< Context > context)
void ExtractMapReferences (HeapEntry *entry, Tagged< Map > map)
void ExtractSharedFunctionInfoReferences (HeapEntry *entry, Tagged< SharedFunctionInfo > shared)
void ExtractScriptReferences (HeapEntry *entry, Tagged< Script > script)
void ExtractAccessorInfoReferences (HeapEntry *entry, Tagged< AccessorInfo > accessor_info)
void ExtractAccessorPairReferences (HeapEntry *entry, Tagged< AccessorPair > accessors)
void ExtractCodeReferences (HeapEntry *entry, Tagged< Code > code)
void ExtractInstructionStreamReferences (HeapEntry *entry, Tagged< InstructionStream > code)
void ExtractCellReferences (HeapEntry *entry, Tagged< Cell > cell)
void ExtractJSWeakRefReferences (HeapEntry *entry, Tagged< JSWeakRef > js_weak_ref)
void ExtractWeakCellReferences (HeapEntry *entry, Tagged< WeakCell > weak_cell)
void ExtractFeedbackCellReferences (HeapEntry *entry, Tagged< FeedbackCell > feedback_cell)
void ExtractPropertyCellReferences (HeapEntry *entry, Tagged< PropertyCell > cell)
void ExtractPrototypeInfoReferences (HeapEntry *entry, Tagged< PrototypeInfo > info)
void ExtractAllocationSiteReferences (HeapEntry *entry, Tagged< AllocationSite > site)
void ExtractArrayBoilerplateDescriptionReferences (HeapEntry *entry, Tagged< ArrayBoilerplateDescription > value)
void ExtractRegExpBoilerplateDescriptionReferences (HeapEntry *entry, Tagged< RegExpBoilerplateDescription > value)
void ExtractJSArrayBufferReferences (HeapEntry *entry, Tagged< JSArrayBuffer > buffer)
void ExtractJSPromiseReferences (HeapEntry *entry, Tagged< JSPromise > promise)
void ExtractJSGeneratorObjectReferences (HeapEntry *entry, Tagged< JSGeneratorObject > generator)
void ExtractFixedArrayReferences (HeapEntry *entry, Tagged< FixedArray > array)
void ExtractNumberReference (HeapEntry *entry, Tagged< Object > number)
void ExtractBytecodeArrayReferences (HeapEntry *entry, Tagged< BytecodeArray > bytecode)
void ExtractScopeInfoReferences (HeapEntry *entry, Tagged< ScopeInfo > info)
void ExtractFeedbackVectorReferences (HeapEntry *entry, Tagged< FeedbackVector > feedback_vector)
void ExtractDescriptorArrayReferences (HeapEntry *entry, Tagged< DescriptorArray > array)
void ExtractEnumCacheReferences (HeapEntry *entry, Tagged< EnumCache > cache)
void ExtractTransitionArrayReferences (HeapEntry *entry, Tagged< TransitionArray > transitions)
template<typename T >
void ExtractWeakArrayReferences (int header_size, HeapEntry *entry, Tagged< T > array)
void ExtractPropertyReferences (Tagged< JSObject > js_obj, HeapEntry *entry)
void ExtractAccessorPairProperty (HeapEntry *entry, Tagged< Name > key, Tagged< Object > callback_obj, int field_offset=-1)
void ExtractElementReferences (Tagged< JSObject > js_obj, HeapEntry *entry)
void ExtractInternalReferences (Tagged< JSObject > js_obj, HeapEntry *entry)
void ExtractCppHeapExternalReferences (HeapEntry *entry, Tagged< CppHeapExternalObject > obj)
bool IsEssentialObject (Tagged< Object > object)
bool IsEssentialHiddenReference (Tagged< Object > parent, int field_offset)
void SetContextReference (HeapEntry *parent_entry, Tagged< String > reference_name, Tagged< Object > child, int field_offset)
void SetNativeBindReference (HeapEntry *parent_entry, const char *reference_name, Tagged< Object > child)
void SetElementReference (HeapEntry *parent_entry, int index, Tagged< Object > child)
void SetInternalReference (HeapEntry *parent_entry, const char *reference_name, Tagged< Object > child, int field_offset=-1)
void SetInternalReference (HeapEntry *parent_entry, int index, Tagged< Object > child, int field_offset=-1)
void SetHiddenReference (Tagged< HeapObject > parent_obj, HeapEntry *parent_entry, int index, Tagged< Object > child, int field_offset)
void SetWeakReference (HeapEntry *parent_entry, const char *reference_name, Tagged< Object > child_obj, int field_offset, HeapEntry::ReferenceVerification verification=HeapEntry::kVerify)
void SetWeakReference (HeapEntry *parent_entry, int index, Tagged< Object > child_obj, std::optional< int > field_offset)
void SetPropertyReference (HeapEntry *parent_entry, Tagged< Name > reference_name, Tagged< Object > child, const char *name_format_string=nullptr, int field_offset=-1)
void SetDataOrAccessorPropertyReference (PropertyKind kind, HeapEntry *parent_entry, Tagged< Name > reference_name, Tagged< Object > child, const char *name_format_string=nullptr, int field_offset=-1)
void SetUserGlobalReference (Tagged< Object > user_global)
void SetRootGcRootsReference ()
void SetGcRootsReference (Root root)
void SetGcSubrootReference (Root root, const char *description, bool is_weak, Tagged< Object > child)
const char * GetStrongGcSubrootName (Tagged< HeapObject > object)
void TagObject (Tagged< Object > obj, const char *tag, std::optional< HeapEntry::Type > type={}, bool overwrite_existing_name=false)
void RecursivelyTagConstantPool (Tagged< Object > obj, const char *tag, HeapEntry::Type type, int recursion_limit)
HeapEntry * GetEntry (Tagged< Object > obj)
Private Attributes
Heap * heap_
HeapSnapshot * snapshot_
StringsStorage * names_
HeapObjectsMap * heap_object_map_
SnapshottingProgressReportingInterface * progress_
HeapSnapshotGenerator * generator_ = nullptr
std::unordered_map< Tagged< JSGlobalObject >, const char *, Object::Hasher > global_object_tag_map_
UnorderedHeapObjectMap< const char * > strong_gc_subroot_names_
std::unordered_set< Tagged< JSGlobalObject >, Object::Hasher > user_roots_
v8::HeapProfiler::ObjectNameResolver * global_object_name_resolver_
std::vector< bool > visited_fields_
size_t max_pointers_
Friends
class IndexedReferencesExtractor
class RootsReferencesExtractor
Detailed Description
Definition at line 412 of file heap-snapshot-generator.h.
Member Typedef Documentation
TemporaryGlobalObjectTags
using v8::internal::V8HeapExplorer::TemporaryGlobalObjectTags = std::vector<std::pair<v8::Global<v8::Object>, const char*> >
Definition at line 429 of file heap-snapshot-generator.h.
Constructor & Destructor Documentation
V8HeapExplorer() [1/2]
v8::internal::V8HeapExplorer::V8HeapExplorer (HeapSnapshot * snapshot, SnapshottingProgressReportingInterface * progress, v8::HeapProfiler::ObjectNameResolver * resolver)
Definition at line 824 of file heap-snapshot-generator.cc.
    : heap_(snapshot->profiler()->heap_object_map()->heap()),
      snapshot_(snapshot),
      names_(snapshot_->profiler()->names()),
      heap_object_map_(snapshot_->profiler()->heap_object_map()),
      progress_(progress),
      generator_(nullptr),
      global_object_name_resolver_(resolver) {}
 V8HeapExplorer()
v8::internal::V8HeapExplorer::~V8HeapExplorer () [override], [default]
V8HeapExplorer() [2/2]
v8::internal::V8HeapExplorer::V8HeapExplorer (const V8HeapExplorer &) [delete]
Member Function Documentation
AddEntry() [1/3]
HeapEntry * v8::internal::V8HeapExplorer::AddEntry (Address address, HeapEntry::Type type, const char * name, size_t size)
Definition at line 1073 of file heap-snapshot-generator.cc.
                                                                   {
  if (v8_flags.heap_profiler_show_hidden_objects &&
      type == HeapEntry::kHidden) {
    type = HeapEntry::kNative;
  }
  SnapshotObjectId object_id = heap_object_map_->FindOrAddEntry(
      address, static_cast<unsigned int>(size));
  unsigned trace_node_id = 0;
  if (AllocationTracker* allocation_tracker =
          snapshot_->profiler()->allocation_tracker()) {
    trace_node_id =
        allocation_tracker->address_to_trace()->GetTraceNodeId(address);
  }
  return snapshot_->AddEntry(type, name, object_id, size, trace_node_id);
}
References v8::internal::HeapSnapshot::AddEntry(), v8::internal::HeapProfiler::allocation_tracker(), v8::internal::HeapObjectsMap::FindOrAddEntry(), heap_object_map_, v8::internal::HeapEntry::kHidden, v8::internal::HeapEntry::kNative, v8::internal::name, v8::internal::HeapSnapshot::profiler(), size(), snapshot_, v8::internal::tracing::type, and v8::internal::v8_flags.
Referenced by AddEntry(), and AllocateEntry().
AddEntry() [2/3]
HeapEntry * v8::internal::V8HeapExplorer::AddEntry (Tagged< HeapObject > object) [private]
Definition at line 895 of file heap-snapshot-generator.cc.
                                                             {
  PtrComprCageBase cage_base(isolate());
  InstanceType instance_type = object->map(cage_base)->instance_type();
  if (InstanceTypeChecker::IsJSObject(instance_type)) {
    if (InstanceTypeChecker::IsJSFunction(instance_type)) {
      Tagged<JSFunction> func = Cast<JSFunction>(object);
      Tagged<SharedFunctionInfo> shared = func->shared();
      const char* name = names_->GetName(shared->Name());
      return AddEntry(object, HeapEntry::kClosure, name);
    } else if (InstanceTypeChecker::IsJSBoundFunction(instance_type)) {
      return AddEntry(object, HeapEntry::kClosure, "native_bind");
    }
    if (InstanceTypeChecker::IsJSRegExp(instance_type)) {
      Tagged<JSRegExp> re = Cast<JSRegExp>(object);
      return AddEntry(object, HeapEntry::kRegExp,
                      names_->GetName(re->source()));
    }
    // TODO(v8:12674) Fix and run full gcmole.
    DisableGCMole no_gcmole;
    const char* name = names_->GetName(
        GetConstructorName(heap_->isolate(), Cast<JSObject>(object)));
    if (InstanceTypeChecker::IsJSGlobalObject(instance_type)) {
      auto it = global_object_tag_map_.find(Cast<JSGlobalObject>(object));
      if (it != global_object_tag_map_.end()) {
        name = names_->GetFormatted("%s / %s", name, it->second);
      }
    }
    return AddEntry(object, HeapEntry::kObject, name);
  } else if (InstanceTypeChecker::IsString(instance_type)) {
    Tagged<String> string = Cast<String>(object);
    if (IsConsString(string, cage_base)) {
      return AddEntry(object, HeapEntry::kConsString, "(concatenated string)");
    } else if (IsSlicedString(string, cage_base)) {
      return AddEntry(object, HeapEntry::kSlicedString, "(sliced string)");
    } else {
      return AddEntry(object, HeapEntry::kString,
                      names_->GetName(Cast<String>(object)));
    }
  } else if (InstanceTypeChecker::IsSymbol(instance_type)) {
    if (Cast<Symbol>(object)->is_private())
      return AddEntry(object, HeapEntry::kHidden, "private symbol");
    else
      return AddEntry(object, HeapEntry::kSymbol, "symbol");
  } else if (InstanceTypeChecker::IsBigInt(instance_type)) {
    return AddEntry(object, HeapEntry::kBigInt, "bigint");
  } else if (InstanceTypeChecker::IsInstructionStream(instance_type) ||
             InstanceTypeChecker::IsCode(instance_type)) {
    return AddEntry(object, HeapEntry::kCode, "");
  } else if (InstanceTypeChecker::IsSharedFunctionInfo(instance_type)) {
    Tagged<String> name = Cast<SharedFunctionInfo>(object)->Name();
    return AddEntry(object, HeapEntry::kCode, names_->GetName(name));
  } else if (InstanceTypeChecker::IsScript(instance_type)) {
    Tagged<Object> name = Cast<Script>(object)->name();
    return AddEntry(object, HeapEntry::kCode,
                    IsString(name) ? names_->GetName(Cast<String>(name)) : "");
  } else if (InstanceTypeChecker::IsNativeContext(instance_type)) {
    return AddEntry(object, HeapEntry::kHidden, "system / NativeContext");
  } else if (InstanceTypeChecker::IsContext(instance_type)) {
    return AddEntry(object, HeapEntry::kObject, "system / Context");
  } else if (InstanceTypeChecker::IsHeapNumber(instance_type)) {
    return AddEntry(object, HeapEntry::kHeapNumber, "heap number");
  } else if (InstanceTypeChecker::IsOddball(instance_type)) {
    Tagged<String> name = Cast<Oddball>(object)->to_string();
    return AddEntry(object, HeapEntry::kHidden, names_->GetName(name));
  } else if (InstanceTypeChecker::IsCppHeapExternalObject(instance_type)) {
    return AddEntry(object, HeapEntry::kObject, "system / CppHeapExternal");
  }
#if V8_ENABLE_WEBASSEMBLY
  if (InstanceTypeChecker::IsWasmObject(instance_type)) {
    Tagged<WasmTypeInfo> info = object->map()->wasm_type_info();
    wasm::StringBuilder sb;
    wasm::GetCanonicalTypeNamesProvider()->PrintTypeName(sb,
                                                         info->type_index());
    sb << " (wasm)" << '\0';
    const char* name = names_->GetCopy(sb.start());
    return AddEntry(object, HeapEntry::kObject, name);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  if (InstanceTypeChecker::IsForeign(instance_type)) {
    Tagged<Foreign> foreign = Cast<Foreign>(object);
    ExternalPointerTag tag = foreign->GetTag();
    size_t size = SizeForSnapshot(object, cage_base);
    const char* name = nullptr;
    // TODO(saelo): consider creating a global mapping of ExternalPointerTags
    // for Managed objects to their name if we need this anywhere else.
    switch (tag) {
      case kGenericManagedTag:
        name = "system / Managed<Unknown>";
        break;
#if V8_ENABLE_WEBASSEMBLY
      case kWasmWasmStreamingTag:
        name = "system / Managed<WasmStreaming>";
        break;
      case kWasmFuncDataTag:
        name = "system / Managed<wasm::FuncData>";
        break;
      case kWasmManagedDataTag:
        name = "system / Managed<wasm::ManagedData>";
        break;
      case kWasmNativeModuleTag:
        size = Cast<Managed<wasm::NativeModule>>(foreign)
                   ->raw()
                   ->EstimateCurrentMemoryConsumption();
        name = "system / Managed<wasm::NativeModule>";
        break;
#endif // V8_ENABLE_WEBASSEMBLY
      case kIcuBreakIteratorTag:
        name = "system / Managed<icu::BreakIterator>";
        break;
      case kIcuUnicodeStringTag:
        name = "system / Managed<icu::UnicodeString>";
        break;
      case kIcuListFormatterTag:
        name = "system / Managed<icu::ListFormatter>";
        break;
      case kIcuLocaleTag:
        name = "system / Managed<icu::Locale>";
        break;
      case kIcuSimpleDateFormatTag:
        name = "system / Managed<icu::SimpleDateFormat>";
        break;
      case kIcuDateIntervalFormatTag:
        name = "system / Managed<icu::DateIntervalFormat>";
        break;
      case kIcuRelativeDateTimeFormatterTag:
        name = "system / Managed<icu::RelativeDateTimeFormatter>";
        break;
      case kIcuLocalizedNumberFormatterTag:
        name = "system / Managed<icu::LocalizedNumberFormatter>";
        break;
      case kIcuPluralRulesTag:
        name = "system / Managed<icu::PluralRules>";
        break;
      case kIcuCollatorTag:
        name = "system / Managed<icu::Collator>";
        break;
      case kDisplayNamesInternalTag:
        name = "system / Managed<DisplayNamesInternal>";
        break;
      case kTemporalInstantTag:
        name = "system / Managed<temporal_rs::Instant>";
        break;
      case kD8WorkerTag:
        name = "system / Managed<d8::Worker>";
        break;
      case kD8ModuleEmbedderDataTag:
        name = "system / Managed<d8::ModuleEmbedderData>";
        break;
      default:
        DCHECK(!kAnyManagedExternalPointerTagRange.Contains(tag));
    }
    if (name != nullptr) {
      return AddEntry(object.address(), HeapEntry::kHidden, name, size);
    }
  }
  return AddEntry(object, GetSystemEntryType(object),
                  GetSystemEntryName(object));
}
References AddEntry(), v8::internal::TagRange< Tag >::Contains(), v8::internal::DCHECK(), v8::internal::wasm::GetCanonicalTypeNamesProvider(), GetConstructorName(), v8::internal::StringsStorage::GetCopy(), v8::internal::StringsStorage::GetName(), GetSystemEntryName(), GetSystemEntryType(), global_object_tag_map_, heap_, v8::internal::InstanceTypeChecker::IsConsString(), isolate(), v8::internal::Heap::isolate(), v8::internal::InstanceTypeChecker::IsSlicedString(), v8::internal::IsWasmObject(), v8::internal::kAnyManagedExternalPointerTagRange(), v8::internal::HeapEntry::kBigInt, v8::internal::HeapEntry::kClosure, v8::internal::HeapEntry::kCode, v8::internal::HeapEntry::kConsString, v8::internal::kD8ModuleEmbedderDataTag, v8::internal::kD8WorkerTag, v8::internal::kDisplayNamesInternalTag, v8::internal::kGenericManagedTag, v8::internal::HeapEntry::kHeapNumber, v8::internal::HeapEntry::kHidden, v8::internal::kIcuBreakIteratorTag, v8::internal::kIcuCollatorTag, v8::internal::kIcuDateIntervalFormatTag, v8::internal::kIcuListFormatterTag, v8::internal::kIcuLocaleTag, v8::internal::kIcuLocalizedNumberFormatterTag, v8::internal::kIcuPluralRulesTag, v8::internal::kIcuRelativeDateTimeFormatterTag, v8::internal::kIcuSimpleDateFormatTag, v8::internal::kIcuUnicodeStringTag, v8::internal::HeapEntry::kObject, v8::internal::HeapEntry::kRegExp, v8::internal::HeapEntry::kSlicedString, v8::internal::HeapEntry::kString, v8::internal::HeapEntry::kSymbol, v8::internal::kTemporalInstantTag, v8::internal::kWasmFuncDataTag, v8::internal::kWasmManagedDataTag, v8::internal::kWasmNativeModuleTag, v8::internal::kWasmWasmStreamingTag, v8::internal::name, names_, v8::internal::wasm::CanonicalTypeNamesProvider::PrintTypeName(), size(), v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::SizeForSnapshot(), and v8::internal::wasm::StringBuilder::start().
AddEntry() [3/3]
HeapEntry * v8::internal::V8HeapExplorer::AddEntry (Tagged< HeapObject > object, HeapEntry::Type type, const char * name) [private]
Definition at line 1066 of file heap-snapshot-generator.cc.
                                                                          {
  PtrComprCageBase cage_base(isolate());
  return AddEntry(object.address(), type, name,
                  SizeForSnapshot(object, cage_base));
}
References AddEntry(), isolate(), v8::internal::name, v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::SizeForSnapshot(), and v8::internal::tracing::type.
AllocateEntry() [1/2]
HeapEntry * v8::internal::V8HeapExplorer::AllocateEntry (HeapThing ptr) [override], [virtual]
Implements v8::internal::HeapEntriesAllocator.
Definition at line 835 of file heap-snapshot-generator.cc.
                                                      {
  return AddEntry(
      Cast<HeapObject>(Tagged<Object>(reinterpret_cast<Address>(ptr))));
}
References AddEntry().
AllocateEntry() [2/2]
HeapEntry * v8::internal::V8HeapExplorer::AllocateEntry (Tagged< Smi > smi) [override], [virtual]
Implements v8::internal::HeapEntriesAllocator.
Definition at line 840 of file heap-snapshot-generator.cc.
                                                        {
  SnapshotObjectId id = heap_object_map_->get_next_id();
  HeapEntry* entry =
      snapshot_->AddEntry(HeapEntry::kHeapNumber, "smi number", id, 0, 0);
  // XXX: Smis do not appear in CombinedHeapObjectIterator, so we need to
  // extract the references here
  ExtractNumberReference(entry, smi);
  return entry;
}
References v8::internal::HeapSnapshot::AddEntry(), ExtractNumberReference(), v8::internal::HeapObjectsMap::get_next_id(), heap_object_map_, v8::internal::HeapEntry::kHeapNumber, and snapshot_.
CollectTemporaryGlobalObjectsTags()
V8HeapExplorer::TemporaryGlobalObjectTags v8::internal::V8HeapExplorer::CollectTemporaryGlobalObjectsTags ()
Definition at line 2970 of file heap-snapshot-generator.cc.
                                                  {
  if (!global_object_name_resolver_) return {};
  Isolate* isolate = heap_->isolate();
  TemporaryGlobalObjectTags global_object_tags;
  HandleScope scope(isolate);
  GlobalObjectsEnumerator enumerator(
      isolate, [this, isolate, &global_object_tags](
                   DirectHandle<JSGlobalObject> global_object) {
        if (const char* tag = global_object_name_resolver_->GetName(
                Utils::ToLocal(Cast<JSObject>(global_object)))) {
          global_object_tags.emplace_back(
              Global<v8::Object>(reinterpret_cast<v8::Isolate*>(isolate),
                                 Utils::ToLocal(Cast<JSObject>(global_object))),
              tag);
          global_object_tags.back().first.SetWeak();
        }
      });
  isolate->global_handles()->IterateAllRoots(&enumerator);
  isolate->traced_handles()->Iterate(&enumerator);
  return global_object_tags;
}
References v8::HeapProfiler::ObjectNameResolver::GetName(), v8::internal::Isolate::global_handles(), global_object_name_resolver_, heap_, isolate(), v8::internal::Heap::isolate(), v8::internal::TracedHandles::Iterate(), v8::internal::GlobalHandles::IterateAllRoots(), and v8::internal::Isolate::traced_handles().
Referenced by v8::internal::HeapSnapshotGenerator::GenerateSnapshot(), and v8::internal::HeapSnapshotGenerator::GenerateSnapshotAfterGC().
EstimateObjectsCount()
uint32_t v8::internal::V8HeapExplorer::EstimateObjectsCount ()
Definition at line 1203 of file heap-snapshot-generator.cc.
                                              {
  CombinedHeapObjectIterator it(heap_, HeapObjectIterator::kNoFiltering);
  uint32_t objects_count = 0;
  // Avoid overflowing the objects count. In worst case, we will show the same
  // progress for a longer period of time, but we do not expect to have that
  // many objects.
  while (!it.Next().is_null() &&
         objects_count != std::numeric_limits<uint32_t>::max())
    ++objects_count;
  return objects_count;
}
References heap_, v8::internal::Tagged< HeapObject >::is_null(), v8::internal::HeapObjectIterator::kNoFiltering, and v8::internal::CombinedHeapObjectIterator::Next().
Referenced by v8::internal::HeapSnapshotGenerator::InitProgressCounter().
ExtractAccessorInfoReferences()
void v8::internal::V8HeapExplorer::ExtractAccessorInfoReferences (HeapEntry * entry, Tagged< AccessorInfo > accessor_info) [private]
Definition at line 1894 of file heap-snapshot-generator.cc.
                                                          {
  SetInternalReference(entry, "name", accessor_info->name(),
                       AccessorInfo::kNameOffset);
  SetInternalReference(entry, "data", accessor_info->data(),
                       AccessorInfo::kDataOffset);
}
References SetInternalReference().
Referenced by ExtractReferences().
ExtractAccessorPairProperty()
void v8::internal::V8HeapExplorer::ExtractAccessorPairProperty (HeapEntry * entry, Tagged< Name > key, Tagged< Object > callback_obj, int field_offset = -1) [private]
Definition at line 2272 of file heap-snapshot-generator.cc.
                                                                   {
  if (!IsAccessorPair(callback_obj)) return;
  Tagged<AccessorPair> accessors = Cast<AccessorPair>(callback_obj);
  SetPropertyReference(entry, key, accessors, nullptr, field_offset);
  Tagged<Object> getter = accessors->getter();
  if (!IsOddball(getter)) {
    SetPropertyReference(entry, key, getter, "get %s");
  }
  Tagged<Object> setter = accessors->setter();
  if (!IsOddball(setter)) {
    SetPropertyReference(entry, key, setter, "set %s");
  }
}
References v8::internal::key, SetPropertyReference(), and v8::internal::setter.
Referenced by SetDataOrAccessorPropertyReference().
ExtractAccessorPairReferences()
void v8::internal::V8HeapExplorer::ExtractAccessorPairReferences (HeapEntry * entry, Tagged< AccessorPair > accessors) [private]
Definition at line 1902 of file heap-snapshot-generator.cc.
                                                      {
  SetInternalReference(entry, "getter", accessors->getter(),
                       offsetof(AccessorPair, getter_));
  SetInternalReference(entry, "setter", accessors->setter(),
                       offsetof(AccessorPair, setter_));
}
References SetInternalReference().
Referenced by ExtractReferences().
ExtractAllocationSiteReferences()
void v8::internal::V8HeapExplorer::ExtractAllocationSiteReferences (HeapEntry * entry, Tagged< AllocationSite > site) [private]
Definition at line 2014 of file heap-snapshot-generator.cc.
                                                   {
  SetInternalReference(
      entry, "transition_info", site->transition_info_or_boilerplate(),
      offsetof(AllocationSite, transition_info_or_boilerplate_));
  SetInternalReference(entry, "nested_site", site->nested_site(),
                       offsetof(AllocationSite, nested_site_));
  TagObject(site->dependent_code(), "(dependent code)", HeapEntry::kCode);
  SetInternalReference(entry, "dependent_code", site->dependent_code(),
                       offsetof(AllocationSite, dependent_code_));
}
References v8::internal::HeapEntry::kCode, SetInternalReference(), and TagObject().
Referenced by ExtractReferences().
ExtractArrayBoilerplateDescriptionReferences()
void v8::internal::V8HeapExplorer::ExtractArrayBoilerplateDescriptionReferences (HeapEntry * entry, Tagged< ArrayBoilerplateDescription > value) [private]
Definition at line 2026 of file heap-snapshot-generator.cc.
                                                                 {
  Tagged<FixedArrayBase> constant_elements = value->constant_elements();
  SetInternalReference(entry, "constant_elements", constant_elements,
                       ArrayBoilerplateDescription::kConstantElementsOffset);
  TagObject(constant_elements, "(constant elements)", HeapEntry::kCode);
}
References v8::internal::HeapEntry::kCode, SetInternalReference(), TagObject(), and v8::internal::value.
Referenced by ExtractReferences().
ExtractBytecodeArrayReferences()
void v8::internal::V8HeapExplorer::ExtractBytecodeArrayReferences (HeapEntry * entry, Tagged< BytecodeArray > bytecode) [private]
Definition at line 2108 of file heap-snapshot-generator.cc.
                                                      {
  RecursivelyTagConstantPool(bytecode->constant_pool(), "(constant pool)",
                             HeapEntry::kCode, 3);
  TagObject(bytecode->handler_table(), "(handler table)", HeapEntry::kCode);
  TagObject(bytecode->raw_source_position_table(kAcquireLoad),
            "(source position table)", HeapEntry::kCode);
}
References v8::kAcquireLoad, v8::internal::HeapEntry::kCode, RecursivelyTagConstantPool(), and TagObject().
Referenced by ExtractReferences().
ExtractCellReferences()
void v8::internal::V8HeapExplorer::ExtractCellReferences (HeapEntry * entry, Tagged< Cell > cell) [private]
Definition at line 1985 of file heap-snapshot-generator.cc.
                                                              {
  SetInternalReference(entry, "value", cell->value(), Cell::kValueOffset);
}
References SetInternalReference().
Referenced by ExtractReferences().
ExtractCodeReferences()
void v8::internal::V8HeapExplorer::ExtractCodeReferences (HeapEntry * entry, Tagged< Code > code) [private]
Definition at line 1932 of file heap-snapshot-generator.cc.
                                                              {
  if (!code->has_instruction_stream()) return;
  SetInternalReference(entry, "instruction_stream", code->instruction_stream(),
                       Code::kInstructionStreamOffset);
  if (code->kind() == CodeKind::BASELINE) {
    TagObject(code->bytecode_or_interpreter_data(), "(interpreter data)");
    SetInternalReference(entry, "interpreter_data",
                         code->bytecode_or_interpreter_data(),
                         Code::kDeoptimizationDataOrInterpreterDataOffset);
    TagObject(code->bytecode_offset_table(), "(bytecode offset table)",
              HeapEntry::kCode);
    SetInternalReference(entry, "bytecode_offset_table",
                         code->bytecode_offset_table(),
                         Code::kPositionTableOffset);
  } else if (code->uses_deoptimization_data()) {
    Tagged<DeoptimizationData> deoptimization_data =
        Cast<DeoptimizationData>(code->deoptimization_data());
    TagObject(deoptimization_data, "(code deopt data)", HeapEntry::kCode);
    SetInternalReference(entry, "deoptimization_data", deoptimization_data,
                         Code::kDeoptimizationDataOrInterpreterDataOffset);
    if (deoptimization_data->length() > 0) {
      TagObject(deoptimization_data->FrameTranslation(), "(code deopt data)",
                HeapEntry::kCode);
      TagObject(deoptimization_data->LiteralArray(), "(code deopt data)",
                HeapEntry::kCode);
      TagObject(deoptimization_data->InliningPositions(), "(code deopt data)",
                HeapEntry::kCode);
    }
    TagObject(code->source_position_table(), "(source position table)",
              HeapEntry::kCode);
    SetInternalReference(entry, "source_position_table",
                         code->source_position_table(),
                         Code::kPositionTableOffset);
  }
}
References code, v8::internal::HeapEntry::kCode, SetInternalReference(), and TagObject().
Referenced by ExtractReferences().
ExtractContextReferences()
void v8::internal::V8HeapExplorer::ExtractContextReferences (HeapEntry * entry, Tagged< Context > context) [private]
Definition at line 1706 of file heap-snapshot-generator.cc.
                                                                       {
  DisallowGarbageCollection no_gc;
  if (!IsNativeContext(context) && context->is_declaration_context()) {
    Tagged<ScopeInfo> scope_info = context->scope_info();
    // Add context allocated locals.
    for (auto it : ScopeInfo::IterateLocalNames(scope_info, no_gc)) {
      int idx = scope_info->ContextHeaderLength() + it->index();
      SetContextReference(entry, it->name(), context->get(idx, kRelaxedLoad),
                          Context::OffsetOfElementAt(idx));
    }
    if (scope_info->HasContextAllocatedFunctionName()) {
      Tagged<String> name = Cast<String>(scope_info->FunctionName());
      int idx = scope_info->FunctionContextSlotIndex(name);
      if (idx >= 0) {
        SetContextReference(entry, name, context->get(idx, kRelaxedLoad),
                            Context::OffsetOfElementAt(idx));
      }
    }
  }
  SetInternalReference(
      entry, "scope_info",
      context->get(Context::SCOPE_INFO_INDEX, kRelaxedLoad),
      FixedArray::OffsetOfElementAt(Context::SCOPE_INFO_INDEX));
  SetInternalReference(entry, "previous",
                       context->get(Context::PREVIOUS_INDEX, kRelaxedLoad),
                       FixedArray::OffsetOfElementAt(Context::PREVIOUS_INDEX));
  if (context->has_extension()) {
    SetInternalReference(
        entry, "extension",
        context->get(Context::EXTENSION_INDEX, kRelaxedLoad),
        FixedArray::OffsetOfElementAt(Context::EXTENSION_INDEX));
  }
  if (IsNativeContext(context)) {
    TagObject(context->normalized_map_cache(), "(context norm. map cache)");
    TagObject(context->embedder_data(), "(context data)");
    for (size_t i = 0; i < arraysize(native_context_names); i++) {
      int index = native_context_names[i].index;
      const char* name = native_context_names[i].name;
      SetInternalReference(entry, name, context->get(index, kRelaxedLoad),
                           FixedArray::OffsetOfElementAt(index));
    }
    static_assert(Context::NEXT_CONTEXT_LINK == Context::FIRST_WEAK_SLOT);
    static_assert(Context::FIRST_WEAK_SLOT + 1 ==
                  Context::NATIVE_CONTEXT_SLOTS);
  }
}
References arraysize, v8::internal::Context::EXTENSION_INDEX, v8::internal::Context::FIRST_WEAK_SLOT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::ScopeInfo::IterateLocalNames(), v8::kRelaxedLoad, v8::internal::name, v8::internal::HeapEntry::name(), v8::internal::native_context_names, v8::internal::Context::NATIVE_CONTEXT_SLOTS, v8::internal::Context::NEXT_CONTEXT_LINK, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Context::OffsetOfElementAt(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), v8::internal::Context::PREVIOUS_INDEX, v8::internal::Context::SCOPE_INFO_INDEX, SetContextReference(), SetInternalReference(), and TagObject().
Referenced by ExtractReferences().
ExtractCppHeapExternalReferences()
void v8::internal::V8HeapExplorer::ExtractCppHeapExternalReferences (HeapEntry * entry, Tagged< CppHeapExternalObject > obj) [private]
Definition at line 2322 of file heap-snapshot-generator.cc.
                                                         {
  generator_->GetCppHeapExternalObjects().insert(obj);
}
References generator_, and v8::internal::HeapSnapshotGenerator::GetCppHeapExternalObjects().
Referenced by ExtractReferences().
ExtractDescriptorArrayReferences()
void v8::internal::V8HeapExplorer::ExtractDescriptorArrayReferences (HeapEntry * entry, Tagged< DescriptorArray > array) [private]
Definition at line 2146 of file heap-snapshot-generator.cc.
                                                     {
  SetInternalReference(entry, "enum_cache", array->enum_cache(),
                       DescriptorArray::kEnumCacheOffset);
  MaybeObjectSlot start = MaybeObjectSlot(array->GetDescriptorSlot(0));
  MaybeObjectSlot end = MaybeObjectSlot(
      array->GetDescriptorSlot(array->number_of_all_descriptors()));
  for (int i = 0; start + i < end; ++i) {
    MaybeObjectSlot slot = start + i;
    int offset = static_cast<int>(slot.address() - array.address());
    Tagged<MaybeObject> object = *slot;
    Tagged<HeapObject> heap_object;
    if (object.GetHeapObjectIfWeak(&heap_object)) {
      SetWeakReference(entry, i, heap_object, offset);
    } else if (object.GetHeapObjectIfStrong(&heap_object)) {
      SetInternalReference(entry, i, heap_object, offset);
    }
  }
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), v8::internal::Tagged< HeapObject >::address(), v8::internal::compiler::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, SetInternalReference(), and SetWeakReference().
Referenced by ExtractReferences().
ExtractElementReferences()
void v8::internal::V8HeapExplorer::ExtractElementReferences (Tagged< JSObject > js_obj, HeapEntry * entry) [private]
Definition at line 2289 of file heap-snapshot-generator.cc.
                                                                {
  ReadOnlyRoots roots = GetReadOnlyRoots();
  if (js_obj->HasObjectElements()) {
    Tagged<FixedArray> elements = Cast<FixedArray>(js_obj->elements());
    int length = IsJSArray(js_obj) ? Smi::ToInt(Cast<JSArray>(js_obj)->length())
                                   : elements->length();
    for (int i = 0; i < length; ++i) {
      if (!IsTheHole(elements->get(i), roots)) {
        SetElementReference(entry, i, elements->get(i));
      }
    }
  } else if (js_obj->HasDictionaryElements()) {
    Tagged<NumberDictionary> dictionary = js_obj->element_dictionary();
    for (InternalIndex i : dictionary->IterateEntries()) {
      Tagged<Object> k = dictionary->KeyAt(i);
      if (!dictionary->IsKey(roots, k)) continue;
      uint32_t index =
          static_cast<uint32_t>(Object::NumberValue(Cast<Number>(k)));
      SetElementReference(entry, index, dictionary->ValueAt(i));
    }
  }
}
References v8::internal::GetReadOnlyRoots(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::length, v8::internal::Object::NumberValue(), SetElementReference(), and v8::internal::Smi::ToInt().
Referenced by ExtractJSObjectReferences().
ExtractEnumCacheReferences()
void v8::internal::V8HeapExplorer::ExtractEnumCacheReferences (HeapEntry * entry, Tagged< EnumCache > cache) [private]
Definition at line 2166 of file heap-snapshot-generator.cc.
                                                                         {
  TagObject(cache->keys(), "(enum cache)", HeapEntry::kObjectShape);
  TagObject(cache->indices(), "(enum cache)", HeapEntry::kObjectShape);
}
References v8::internal::HeapEntry::kObjectShape, and TagObject().
Referenced by ExtractReferences().
ExtractEphemeronHashTableReferences()
void v8::internal::V8HeapExplorer::ExtractEphemeronHashTableReferences (HeapEntry * entry, Tagged< EphemeronHashTable > table) [private]
Definition at line 1653 of file heap-snapshot-generator.cc.
                                                        {
  for (InternalIndex i : table->IterateEntries()) {
    int key_index = EphemeronHashTable::EntryToIndex(i) +
                    EphemeronHashTable::kEntryKeyIndex;
    int value_index = EphemeronHashTable::EntryToValueIndex(i);
    Tagged<Object> key = table->get(key_index);
    Tagged<Object> value = table->get(value_index);
    SetWeakReference(entry, key_index, key,
                     table->OffsetOfElementAt(key_index));
    SetWeakReference(entry, value_index, value,
                     table->OffsetOfElementAt(value_index));
    HeapEntry* key_entry = GetEntry(key);
    HeapEntry* value_entry = GetEntry(value);
    HeapEntry* table_entry = GetEntry(table);
    if (key_entry && value_entry && !IsUndefined(key)) {
      const char* edge_name = names_->GetFormatted(
          "part of key (%s @%u) -> value (%s @%u) pair in WeakMap (table @%u)",
          key_entry->name(), key_entry->id(), value_entry->name(),
          value_entry->id(), table_entry->id());
      key_entry->SetNamedAutoIndexReference(HeapGraphEdge::kInternal, edge_name,
                                            value_entry, names_, generator_,
                                            HeapEntry::kEphemeron);
      table_entry->SetNamedAutoIndexReference(
          HeapGraphEdge::kInternal, edge_name, value_entry, names_, generator_,
          HeapEntry::kEphemeron);
    }
  }
}
References generator_, GetEntry(), v8::internal::HeapEntry::id(), v8::internal::HeapEntry::kEphemeron, v8::internal::key, v8::internal::HeapGraphEdge::kInternal, v8::internal::HeapEntry::name(), names_, v8::internal::HeapEntry::SetNamedAutoIndexReference(), SetWeakReference(), and v8::internal::value.
Referenced by ExtractReferences().
ExtractFeedbackCellReferences()
void v8::internal::V8HeapExplorer::ExtractFeedbackCellReferences (HeapEntry * entry, Tagged< FeedbackCell > feedback_cell) [private]
Definition at line 1990 of file heap-snapshot-generator.cc.
                                                          {
  TagObject(feedback_cell, "(feedback cell)");
  SetInternalReference(entry, "value", feedback_cell->value(),
                       FeedbackCell::kValueOffset);
}
References SetInternalReference(), and TagObject().
Referenced by ExtractReferences().
ExtractFeedbackVectorReferences()
void v8::internal::V8HeapExplorer::ExtractFeedbackVectorReferences (HeapEntry * entry, Tagged< FeedbackVector > feedback_vector) [private]
Definition at line 2125 of file heap-snapshot-generator.cc.
                                                              {
#ifndef V8_ENABLE_LEAPTIERING
  Tagged<MaybeObject> code = feedback_vector->maybe_optimized_code();
  Tagged<HeapObject> code_heap_object;
  if (code.GetHeapObjectIfWeak(&code_heap_object)) {
    SetWeakReference(entry, "optimized code", code_heap_object,
                     FeedbackVector::kMaybeOptimizedCodeOffset);
  }
#endif // !V8_ENABLE_LEAPTIERING
  for (int i = 0; i < feedback_vector->length(); ++i) {
    Tagged<MaybeObject> maybe_entry = *(feedback_vector->slots_start() + i);
    Tagged<HeapObject> entry_obj;
    if (maybe_entry.GetHeapObjectIfStrong(&entry_obj) &&
        (entry_obj->map(isolate())->instance_type() == WEAK_FIXED_ARRAY_TYPE ||
         IsFixedArrayExact(entry_obj))) {
      TagObject(entry_obj, "(feedback)", HeapEntry::kCode);
    }
  }
}
References code, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfStrong(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate(), v8::internal::HeapEntry::kCode, SetWeakReference(), and TagObject().
Referenced by ExtractReferences().
ExtractFixedArrayReferences()
void v8::internal::V8HeapExplorer::ExtractFixedArrayReferences (HeapEntry * entry, Tagged< FixedArray > array) [private]
Definition at line 2072 of file heap-snapshot-generator.cc.
                                                                           {
  for (int i = 0, l = array->length(); i < l; ++i) {
    DCHECK(!HasWeakHeapObjectTag(array->get(i)));
    SetInternalReference(entry, i, array->get(i), array->OffsetOfElementAt(i));
  }
}
References v8::internal::DCHECK(), v8::internal::HasWeakHeapObjectTag(), v8::internal::compiler::turboshaft::l, and SetInternalReference().
Referenced by ExtractReferences().
ExtractInstructionStreamReferences()
void v8::internal::V8HeapExplorer::ExtractInstructionStreamReferences (HeapEntry * entry, Tagged< InstructionStream > code) [private]
Definition at line 1971 of file heap-snapshot-generator.cc.
                                                         {
  Tagged<Code> code;
  if (!istream->TryGetCode(&code, kAcquireLoad))
    return; // Not yet initialized.
  TagObject(code, "(code)", HeapEntry::kCode);
  SetInternalReference(entry, "code", code, InstructionStream::kCodeOffset);
  TagObject(istream->relocation_info(), "(code relocation info)",
            HeapEntry::kCode);
  SetInternalReference(entry, "relocation_info", istream->relocation_info(),
                       InstructionStream::kRelocationInfoOffset);
}
References code, v8::kAcquireLoad, v8::internal::HeapEntry::kCode, SetInternalReference(), and TagObject().
Referenced by ExtractReferences().
ExtractInternalReferences()
void v8::internal::V8HeapExplorer::ExtractInternalReferences (Tagged< JSObject > js_obj, HeapEntry * entry) [private]
Definition at line 2313 of file heap-snapshot-generator.cc.
                                                                 {
  int length = js_obj->GetEmbedderFieldCount();
  for (int i = 0; i < length; ++i) {
    Tagged<Object> o = js_obj->GetEmbedderField(i);
    SetInternalReference(entry, i, o, js_obj->GetEmbedderFieldOffset(i));
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, and SetInternalReference().
Referenced by ExtractJSObjectReferences().
ExtractJSArrayBufferReferences()
void v8::internal::V8HeapExplorer::ExtractJSArrayBufferReferences (HeapEntry * entry, Tagged< JSArrayBuffer > buffer) [private]
Definition at line 2039 of file heap-snapshot-generator.cc.
                                                    {
  // Setup a reference to a native memory backing_store object.
  if (!buffer->backing_store()) return;
  size_t data_size = buffer->byte_length();
  ExternalDataEntryAllocator allocator(data_size, this,
                                       "system / JSArrayBufferData");
  HeapEntry* data_entry =
      generator_->FindOrAddEntry(buffer->backing_store(), &allocator);
  entry->SetNamedReference(HeapGraphEdge::kInternal, "backing_store",
                           data_entry, generator_, HeapEntry::kOffHeapPointer);
}
References v8::internal::HeapSnapshotGenerator::FindOrAddEntry(), generator_, v8::internal::HeapGraphEdge::kInternal, v8::internal::HeapEntry::kOffHeapPointer, and v8::internal::HeapEntry::SetNamedReference().
Referenced by ExtractReferences().
ExtractJSCollectionReferences()
void v8::internal::V8HeapExplorer::ExtractJSCollectionReferences (HeapEntry * entry, Tagged< JSCollection > collection) [private]
Definition at line 1641 of file heap-snapshot-generator.cc.
                                                       {
  SetInternalReference(entry, "table", collection->table(),
                       JSCollection::kTableOffset);
}
References SetInternalReference().
Referenced by ExtractReferences().
ExtractJSDisposableStackReferences()
void v8::internal::V8HeapExplorer::ExtractJSDisposableStackReferences (HeapEntry * entry, Tagged< JSDisposableStackBase > disposable_stack) [private]
Definition at line 1683 of file heap-snapshot-generator.cc.
                                                                      {
  SetInternalReference(entry, "stack", disposable_stack->stack(),
                       JSDisposableStackBase::kStackOffset);
  SetInternalReference(entry, "error", disposable_stack->error(),
                       JSDisposableStackBase::kErrorOffset);
  SetInternalReference(entry, "error_message",
                       disposable_stack->error_message(),
                       JSDisposableStackBase::kErrorMessageOffset);
}
References v8::internal::kStackOffset, and SetInternalReference().
Referenced by ExtractReferences().
ExtractJSGeneratorObjectReferences()
void v8::internal::V8HeapExplorer::ExtractJSGeneratorObjectReferences (HeapEntry * entry, Tagged< JSGeneratorObject > generator) [private]
Definition at line 2059 of file heap-snapshot-generator.cc.
                                                           {
  SetInternalReference(entry, "function", generator->function(),
                       JSGeneratorObject::kFunctionOffset);
  SetInternalReference(entry, "context", generator->context(),
                       JSGeneratorObject::kContextOffset);
  SetInternalReference(entry, "receiver", generator->receiver(),
                       JSGeneratorObject::kReceiverOffset);
  SetInternalReference(entry, "parameters_and_registers",
                       generator->parameters_and_registers(),
                       JSGeneratorObject::kParametersAndRegistersOffset);
}
References SetInternalReference().
Referenced by ExtractReferences().
ExtractJSGlobalProxyReferences()
void v8::internal::V8HeapExplorer::ExtractJSGlobalProxyReferences (HeapEntry * entry, Tagged< JSGlobalProxy > proxy) [private]
Definition at line 1479 of file heap-snapshot-generator.cc.
                                                   {}
Referenced by ExtractReferences().
ExtractJSObjectReferences()
void v8::internal::V8HeapExplorer::ExtractJSObjectReferences (HeapEntry * entry, Tagged< JSObject > js_obj) [private]
Definition at line 1482 of file heap-snapshot-generator.cc.
                                                                        {
  Tagged<HeapObject> obj = js_obj;
  ExtractPropertyReferences(js_obj, entry);
  ExtractElementReferences(js_obj, entry);
  ExtractInternalReferences(js_obj, entry);
  Isolate* isolate = Isolate::FromHeap(heap_);
  PrototypeIterator iter(isolate, js_obj);
  ReadOnlyRoots roots(isolate);
  SetPropertyReference(entry, roots.proto_string(), iter.GetCurrent());
  if (IsJSBoundFunction(obj)) {
    Tagged<JSBoundFunction> js_fun = Cast<JSBoundFunction>(obj);
    TagObject(js_fun->bound_arguments(), "(bound arguments)");
    SetInternalReference(entry, "bindings", js_fun->bound_arguments(),
                         JSBoundFunction::kBoundArgumentsOffset);
    SetInternalReference(entry, "bound_this", js_fun->bound_this(),
                         JSBoundFunction::kBoundThisOffset);
    SetInternalReference(entry, "bound_function",
                         js_fun->bound_target_function(),
                         JSBoundFunction::kBoundTargetFunctionOffset);
    Tagged<FixedArray> bindings = js_fun->bound_arguments();
    for (int i = 0; i < bindings->length(); i++) {
      const char* reference_name = names_->GetFormatted("bound_argument_%d", i);
      SetNativeBindReference(entry, reference_name, bindings->get(i));
    }
  } else if (IsJSFunction(obj)) {
    Tagged<JSFunction> js_fun = Cast<JSFunction>(js_obj);
    if (js_fun->has_prototype_slot()) {
      Tagged<Object> proto_or_map =
          js_fun->prototype_or_initial_map(kAcquireLoad);
      if (!IsTheHole(proto_or_map, isolate)) {
        if (!IsMap(proto_or_map)) {
          SetPropertyReference(entry, roots.prototype_string(), proto_or_map,
                               nullptr,
                               JSFunction::kPrototypeOrInitialMapOffset);
        } else {
          SetPropertyReference(entry, roots.prototype_string(),
                               js_fun->prototype());
          SetInternalReference(entry, "initial_map", proto_or_map,
                               JSFunction::kPrototypeOrInitialMapOffset);
        }
      }
    }
    Tagged<SharedFunctionInfo> shared_info = js_fun->shared();
    TagObject(js_fun->raw_feedback_cell(), "(function feedback cell)");
    SetInternalReference(entry, "feedback_cell", js_fun->raw_feedback_cell(),
                         JSFunction::kFeedbackCellOffset);
    TagObject(shared_info, "(shared function info)");
    SetInternalReference(entry, "shared", shared_info,
                         JSFunction::kSharedFunctionInfoOffset);
    TagObject(js_fun->context(), "(context)");
    SetInternalReference(entry, "context", js_fun->context(),
                         JSFunction::kContextOffset);
#ifdef V8_ENABLE_LEAPTIERING
    SetInternalReference(entry, "code", js_fun->code(isolate),
                         JSFunction::kDispatchHandleOffset);
#else
    SetInternalReference(entry, "code", js_fun->code(isolate),
                         JSFunction::kCodeOffset);
#endif // V8_ENABLE_LEAPTIERING
  } else if (IsJSGlobalObject(obj)) {
    Tagged<JSGlobalObject> global_obj = Cast<JSGlobalObject>(obj);
    SetInternalReference(entry, "global_proxy", global_obj->global_proxy(),
                         JSGlobalObject::kGlobalProxyOffset);
  } else if (IsJSArrayBufferView(obj)) {
    Tagged<JSArrayBufferView> view = Cast<JSArrayBufferView>(obj);
    SetInternalReference(entry, "buffer", view->buffer(),
                         JSArrayBufferView::kBufferOffset);
  }
  TagObject(js_obj->raw_properties_or_hash(), "(object properties)");
  SetInternalReference(entry, "properties", js_obj->raw_properties_or_hash(),
                       JSObject::kPropertiesOrHashOffset);
  TagObject(js_obj->elements(), "(object elements)");
  SetInternalReference(entry, "elements", js_obj->elements(),
                       JSObject::kElementsOffset);
}
References v8_inspector::V8RuntimeAgentImplState::bindings, ExtractElementReferences(), ExtractInternalReferences(), ExtractPropertyReferences(), v8::internal::Isolate::FromHeap(), v8::internal::PrototypeIterator::GetCurrent(), heap_, isolate(), v8::kAcquireLoad, names_, SetInternalReference(), SetNativeBindReference(), SetPropertyReference(), and TagObject().
Referenced by ExtractReferences().
ExtractJSPromiseReferences()
void v8::internal::V8HeapExplorer::ExtractJSPromiseReferences (HeapEntry * entry, Tagged< JSPromise > promise) [private]
Definition at line 2052 of file heap-snapshot-generator.cc.
                                                                           {
  SetInternalReference(entry, "reactions_or_result",
                       promise->reactions_or_result(),
                       JSPromise::kReactionsOrResultOffset);
}
References SetInternalReference().
Referenced by ExtractReferences().
ExtractJSWeakCollectionReferences()
void v8::internal::V8HeapExplorer::ExtractJSWeakCollectionReferences (HeapEntry * entry, Tagged< JSWeakCollection > collection) [private]
Definition at line 1647 of file heap-snapshot-generator.cc.
                                                    {
  SetInternalReference(entry, "table", obj->table(),
                       JSWeakCollection::kTableOffset);
}
References SetInternalReference().
Referenced by ExtractReferences().
ExtractJSWeakRefReferences()
void v8::internal::V8HeapExplorer::ExtractJSWeakRefReferences (HeapEntry * entry, Tagged< JSWeakRef > js_weak_ref) [private]
Definition at line 1910 of file heap-snapshot-generator.cc.
                                                                               {
  SetWeakReference(entry, "target", js_weak_ref->target(),
                   JSWeakRef::kTargetOffset);
}
References SetWeakReference().
Referenced by ExtractReferences().
ExtractLocation()
void v8::internal::V8HeapExplorer::ExtractLocation (HeapEntry * entry, Tagged< HeapObject > object) [private]
Definition at line 870 of file heap-snapshot-generator.cc.
                                                                {
  DisallowHeapAllocation no_gc;
  Tagged<JSFunction> func = GetLocationFunction(object);
  if (!func.is_null()) {
    ExtractLocationForJSFunction(entry, func);
  }
}
References ExtractLocationForJSFunction(), GetLocationFunction(), v8::internal::Tagged< HeapObject >::is_null(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by IterateAndExtractReferences().
ExtractLocationForJSFunction()
void v8::internal::V8HeapExplorer::ExtractLocationForJSFunction (HeapEntry * entry, Tagged< JSFunction > func) [private]
Definition at line 879 of file heap-snapshot-generator.cc.
                                                                           {
  if (!IsScript(func->shared()->script())) return;
  Tagged<Script> script = Cast<Script>(func->shared()->script());
  int scriptId = script->id();
  int start = func->shared()->StartPosition();
  Script::PositionInfo info;
  if (script->has_line_ends()) {
    script->GetPositionInfo(start, &info);
  } else {
    script->GetPositionInfoWithLineEnds(
        start, &info, snapshot_->GetScriptLineEnds(script->id()));
  }
  snapshot_->AddLocation(entry, scriptId, info.line, info.column);
}
References v8::internal::HeapSnapshot::AddLocation(), v8::internal::Script::PositionInfo::column, v8::internal::HeapSnapshot::GetScriptLineEnds(), v8::internal::Script::PositionInfo::line, v8::internal::script, and snapshot_.
Referenced by ExtractLocation().
ExtractMapReferences()
void v8::internal::V8HeapExplorer::ExtractMapReferences (HeapEntry * entry, Tagged< Map > map) [private]
Definition at line 1757 of file heap-snapshot-generator.cc.
                                                                           {
  Tagged<MaybeObject> maybe_raw_transitions_or_prototype_info =
      map->raw_transitions();
  Tagged<HeapObject> raw_transitions_or_prototype_info;
  if (maybe_raw_transitions_or_prototype_info.GetHeapObjectIfWeak(
          &raw_transitions_or_prototype_info)) {
    DCHECK(IsMap(raw_transitions_or_prototype_info));
    SetWeakReference(entry, "transition", raw_transitions_or_prototype_info,
                     Map::kTransitionsOrPrototypeInfoOffset);
  } else if (maybe_raw_transitions_or_prototype_info.GetHeapObjectIfStrong(
                 &raw_transitions_or_prototype_info)) {
    if (IsTransitionArray(raw_transitions_or_prototype_info)) {
      Tagged<TransitionArray> transitions =
          Cast<TransitionArray>(raw_transitions_or_prototype_info);
      if (map->CanTransition() && transitions->HasPrototypeTransitions()) {
        TagObject(transitions->GetPrototypeTransitions(),
                  "(prototype transitions)");
      }
      TagObject(transitions, "(transition array)");
      SetInternalReference(entry, "transitions", transitions,
                           Map::kTransitionsOrPrototypeInfoOffset);
    } else if (IsFixedArray(raw_transitions_or_prototype_info)) {
      TagObject(raw_transitions_or_prototype_info, "(transition)");
      SetInternalReference(entry, "transition",
                           raw_transitions_or_prototype_info,
                           Map::kTransitionsOrPrototypeInfoOffset);
    } else if (map->is_prototype_map()) {
      TagObject(raw_transitions_or_prototype_info, "prototype_info");
      SetInternalReference(entry, "prototype_info",
                           raw_transitions_or_prototype_info,
                           Map::kTransitionsOrPrototypeInfoOffset);
    }
  }
  Tagged<DescriptorArray> descriptors = map->instance_descriptors();
  TagObject(descriptors, "(map descriptors)");
  SetInternalReference(entry, "descriptors", descriptors,
                       Map::kInstanceDescriptorsOffset);
  SetInternalReference(entry, "prototype", map->prototype(),
                       Map::kPrototypeOffset);
  if (IsContextMap(map) || IsMapMap(map)) {
    Tagged<Object> native_context = map->native_context_or_null();
    TagObject(native_context, "(native context)");
    SetInternalReference(entry, "native_context", native_context,
                         Map::kConstructorOrBackPointerOrNativeContextOffset);
  } else {
    Tagged<Object> constructor_or_back_pointer =
        map->constructor_or_back_pointer();
    if (IsMap(constructor_or_back_pointer)) {
      TagObject(constructor_or_back_pointer, "(back pointer)");
      SetInternalReference(entry, "back_pointer", constructor_or_back_pointer,
                           Map::kConstructorOrBackPointerOrNativeContextOffset);
    } else if (IsFunctionTemplateInfo(constructor_or_back_pointer)) {
      TagObject(constructor_or_back_pointer, "(constructor function data)");
      SetInternalReference(entry, "constructor_function_data",
                           constructor_or_back_pointer,
                           Map::kConstructorOrBackPointerOrNativeContextOffset);
    } else {
      SetInternalReference(entry, "constructor", constructor_or_back_pointer,
                           Map::kConstructorOrBackPointerOrNativeContextOffset);
    }
  }
  TagObject(map->dependent_code(), "(dependent code)");
  SetInternalReference(entry, "dependent_code", map->dependent_code(),
                       Map::kDependentCodeOffset);
  TagObject(map->prototype_validity_cell(kRelaxedLoad),
            "(prototype validity cell)", HeapEntry::kObjectShape);
}
References v8::internal::constructor_or_back_pointer, v8::internal::DCHECK(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfStrong(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), v8::internal::kConstructorOrBackPointerOrNativeContextOffset, v8::internal::HeapEntry::kObjectShape, v8::internal::kPrototypeOffset, v8::kRelaxedLoad, v8::internal::native_context, SetInternalReference(), SetWeakReference(), and TagObject().
Referenced by ExtractReferences().
ExtractNumberReference()
void v8::internal::V8HeapExplorer::ExtractNumberReference (HeapEntry * entry, Tagged< Object > number) [private]
Definition at line 2080 of file heap-snapshot-generator.cc.
                                                                   {
  DCHECK(IsNumber(number));
  // Must be large enough to fit any double, int, or size_t.
  char arr[32];
  base::Vector<char> buffer = base::ArrayVector(arr);
  std::string_view string;
  if (IsSmi(number)) {
    int int_value = Smi::ToInt(number);
    string = IntToStringView(int_value, buffer);
  } else {
    double double_value = Cast<HeapNumber>(number)->value();
    string = DoubleToStringView(double_value, buffer);
  }
  // GetCopy() requires a null-terminated C-String, as the underlying hash map
  // uses strcmp.
  const char* name = names_->GetCopy(std::string(string).c_str());
  SnapshotObjectId id = heap_object_map_->get_next_id();
  HeapEntry* child_entry =
      snapshot_->AddEntry(HeapEntry::kString, name, id, 0, 0);
  entry->SetNamedReference(HeapGraphEdge::kInternal, "value", child_entry,
                           generator_);
}
References v8::internal::HeapSnapshot::AddEntry(), v8::base::ArrayVector(), v8::internal::DCHECK(), v8::internal::DoubleToStringView(), generator_, v8::internal::HeapObjectsMap::get_next_id(), v8::internal::StringsStorage::GetCopy(), heap_object_map_, v8::internal::IntToStringView(), v8::internal::IsNumber(), v8::internal::IsSmi(), v8::internal::HeapGraphEdge::kInternal, v8::internal::HeapEntry::kString, v8::internal::name, names_, v8::internal::HeapEntry::SetNamedReference(), snapshot_, v8::internal::string, and v8::internal::Smi::ToInt().
Referenced by AllocateEntry(), and ExtractReferences().
ExtractPropertyCellReferences()
void v8::internal::V8HeapExplorer::ExtractPropertyCellReferences (HeapEntry * entry, Tagged< PropertyCell > cell) [private]
Definition at line 1997 of file heap-snapshot-generator.cc.
                                                                              {
  SetInternalReference(entry, "value", cell->value(),
                       PropertyCell::kValueOffset);
  TagObject(cell->dependent_code(), "(dependent code)");
  SetInternalReference(entry, "dependent_code", cell->dependent_code(),
                       PropertyCell::kDependentCodeOffset);
}
References SetInternalReference(), and TagObject().
Referenced by ExtractReferences().
ExtractPropertyReferences()
void v8::internal::V8HeapExplorer::ExtractPropertyReferences (Tagged< JSObject > js_obj, HeapEntry * entry) [private]
Definition at line 2196 of file heap-snapshot-generator.cc.
                                                                 {
  Isolate* isolate = Isolate::Current();
  if (js_obj->HasFastProperties()) {
    Tagged<DescriptorArray> descs =
        js_obj->map()->instance_descriptors(isolate);
    for (InternalIndex i : js_obj->map()->IterateOwnDescriptors()) {
      PropertyDetails details = descs->GetDetails(i);
      switch (details.location()) {
        case PropertyLocation::kField: {
          if (!snapshot_->capture_numeric_value()) {
            Representation r = details.representation();
            if (r.IsSmi() || r.IsDouble()) break;
          }
          Tagged<Name> k = descs->GetKey(i);
          FieldIndex field_index =
              FieldIndex::ForDetails(js_obj->map(), details);
          Tagged<Object> value = js_obj->RawFastPropertyAt(field_index);
          int field_offset =
              field_index.is_inobject() ? field_index.offset() : -1;
          SetDataOrAccessorPropertyReference(details.kind(), entry, k, value,
                                             nullptr, field_offset);
          break;
        }
        case PropertyLocation::kDescriptor:
          SetDataOrAccessorPropertyReference(details.kind(), entry,
                                             descs->GetKey(i),
                                             descs->GetStrongValue(i));
          break;
      }
    }
  } else if (IsJSGlobalObject(js_obj)) {
    // We assume that global objects can only have slow properties.
    Tagged<GlobalDictionary> dictionary =
        Cast<JSGlobalObject>(js_obj)->global_dictionary(kAcquireLoad);
    ReadOnlyRoots roots(isolate);
    for (InternalIndex i : dictionary->IterateEntries()) {
      if (!dictionary->IsKey(roots, dictionary->KeyAt(i))) continue;
      Tagged<PropertyCell> cell = dictionary->CellAt(i);
      Tagged<Name> name = cell->name();
      Tagged<Object> value = cell->value();
      PropertyDetails details = cell->property_details();
      SetDataOrAccessorPropertyReference(details.kind(), entry, name, value);
    }
  } else if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    // SwissNameDictionary::IterateEntries creates a Handle, which should not
    // leak out of here.
    HandleScope scope(isolate);
    Tagged<SwissNameDictionary> dictionary =
        js_obj->property_dictionary_swiss();
    ReadOnlyRoots roots(isolate);
    for (InternalIndex i : dictionary->IterateEntries()) {
      Tagged<Object> k = dictionary->KeyAt(i);
      if (!dictionary->IsKey(roots, k)) continue;
      Tagged<Object> value = dictionary->ValueAt(i);
      PropertyDetails details = dictionary->DetailsAt(i);
      SetDataOrAccessorPropertyReference(details.kind(), entry, Cast<Name>(k),
                                         value);
    }
  } else {
    Tagged<NameDictionary> dictionary = js_obj->property_dictionary();
    ReadOnlyRoots roots(isolate);
    for (InternalIndex i : dictionary->IterateEntries()) {
      Tagged<Object> k = dictionary->KeyAt(i);
      if (!dictionary->IsKey(roots, k)) continue;
      Tagged<Object> value = dictionary->ValueAt(i);
      PropertyDetails details = dictionary->DetailsAt(i);
      SetDataOrAccessorPropertyReference(details.kind(), entry, Cast<Name>(k),
                                         value);
    }
  }
}
References v8::internal::HeapSnapshot::capture_numeric_value(), v8::internal::Isolate::Current(), v8::internal::FieldIndex::ForDetails(), v8::internal::FieldIndex::is_inobject(), v8::internal::Representation::IsDouble(), isolate(), v8::internal::Representation::IsSmi(), v8::kAcquireLoad, v8::internal::kDescriptor, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), v8::internal::name, v8::internal::FieldIndex::offset(), v8::internal::PropertyDetails::representation(), SetDataOrAccessorPropertyReference(), snapshot_, V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, and v8::internal::value.
Referenced by ExtractJSObjectReferences().
ExtractPrototypeInfoReferences()
void v8::internal::V8HeapExplorer::ExtractPrototypeInfoReferences (HeapEntry * entry, Tagged< PrototypeInfo > info) [private]
Definition at line 2006 of file heap-snapshot-generator.cc.
                                                  {
  TagObject(info->prototype_chain_enum_cache(), "(prototype chain enum cache)",
            HeapEntry::kObjectShape);
  TagObject(info->prototype_users(), "(prototype users)",
            HeapEntry::kObjectShape);
}
References v8::internal::HeapEntry::kObjectShape, and TagObject().
Referenced by ExtractReferences().
ExtractReferences()
void v8::internal::V8HeapExplorer::ExtractReferences (HeapEntry * entry, Tagged< HeapObject > obj) [private]
Definition at line 1369 of file heap-snapshot-generator.cc.
                                                               {
  if (IsJSGlobalProxy(obj)) {
    ExtractJSGlobalProxyReferences(entry, Cast<JSGlobalProxy>(obj));
  } else if (IsJSArrayBuffer(obj)) {
    ExtractJSArrayBufferReferences(entry, Cast<JSArrayBuffer>(obj));
  } else if (IsJSObject(obj)) {
    if (IsJSWeakSet(obj)) {
      ExtractJSWeakCollectionReferences(entry, Cast<JSWeakSet>(obj));
    } else if (IsJSWeakMap(obj)) {
      ExtractJSWeakCollectionReferences(entry, Cast<JSWeakMap>(obj));
    } else if (IsJSSet(obj)) {
      ExtractJSCollectionReferences(entry, Cast<JSSet>(obj));
    } else if (IsJSMap(obj)) {
      ExtractJSCollectionReferences(entry, Cast<JSMap>(obj));
    } else if (IsJSPromise(obj)) {
      ExtractJSPromiseReferences(entry, Cast<JSPromise>(obj));
    } else if (IsJSGeneratorObject(obj)) {
      ExtractJSGeneratorObjectReferences(entry, Cast<JSGeneratorObject>(obj));
    } else if (IsJSWeakRef(obj)) {
      ExtractJSWeakRefReferences(entry, Cast<JSWeakRef>(obj));
    } else if (IsJSDisposableStackBase(obj)) {
      ExtractJSDisposableStackReferences(entry,
                                         Cast<JSDisposableStackBase>(obj));
#if V8_ENABLE_WEBASSEMBLY
    } else if (IsWasmInstanceObject(obj)) {
      ExtractWasmInstanceObjectReferences(Cast<WasmInstanceObject>(obj), entry);
    } else if (IsWasmModuleObject(obj)) {
      ExtractWasmModuleObjectReferences(Cast<WasmModuleObject>(obj), entry);
#endif // V8_ENABLE_WEBASSEMBLY
    }
    ExtractJSObjectReferences(entry, Cast<JSObject>(obj));
  } else if (IsString(obj)) {
    ExtractStringReferences(entry, Cast<String>(obj));
  } else if (IsSymbol(obj)) {
    ExtractSymbolReferences(entry, Cast<Symbol>(obj));
  } else if (IsMap(obj)) {
    ExtractMapReferences(entry, Cast<Map>(obj));
  } else if (IsSharedFunctionInfo(obj)) {
    ExtractSharedFunctionInfoReferences(entry, Cast<SharedFunctionInfo>(obj));
  } else if (IsScript(obj)) {
    ExtractScriptReferences(entry, Cast<Script>(obj));
  } else if (IsAccessorInfo(obj)) {
    ExtractAccessorInfoReferences(entry, Cast<AccessorInfo>(obj));
  } else if (IsAccessorPair(obj)) {
    ExtractAccessorPairReferences(entry, Cast<AccessorPair>(obj));
  } else if (IsCode(obj)) {
    ExtractCodeReferences(entry, Cast<Code>(obj));
  } else if (IsInstructionStream(obj)) {
    ExtractInstructionStreamReferences(entry, Cast<InstructionStream>(obj));
  } else if (IsCell(obj)) {
    ExtractCellReferences(entry, Cast<Cell>(obj));
  } else if (IsFeedbackCell(obj)) {
    ExtractFeedbackCellReferences(entry, Cast<FeedbackCell>(obj));
  } else if (IsPropertyCell(obj)) {
    ExtractPropertyCellReferences(entry, Cast<PropertyCell>(obj));
  } else if (IsPrototypeInfo(obj)) {
    ExtractPrototypeInfoReferences(entry, Cast<PrototypeInfo>(obj));
  } else if (IsAllocationSite(obj)) {
    ExtractAllocationSiteReferences(entry, Cast<AllocationSite>(obj));
  } else if (IsArrayBoilerplateDescription(obj)) {
    ExtractArrayBoilerplateDescriptionReferences(
        entry, Cast<ArrayBoilerplateDescription>(obj));
  } else if (IsRegExpBoilerplateDescription(obj)) {
    ExtractRegExpBoilerplateDescriptionReferences(
        entry, Cast<RegExpBoilerplateDescription>(obj));
  } else if (IsFeedbackVector(obj)) {
    ExtractFeedbackVectorReferences(entry, Cast<FeedbackVector>(obj));
  } else if (IsDescriptorArray(obj)) {
    ExtractDescriptorArrayReferences(entry, Cast<DescriptorArray>(obj));
  } else if (IsEnumCache(obj)) {
    ExtractEnumCacheReferences(entry, Cast<EnumCache>(obj));
  } else if (IsTransitionArray(obj)) {
    ExtractTransitionArrayReferences(entry, Cast<TransitionArray>(obj));
  } else if (IsWeakFixedArray(obj)) {
    ExtractWeakArrayReferences(OFFSET_OF_DATA_START(WeakFixedArray), entry,
                               Cast<WeakFixedArray>(obj));
  } else if (IsWeakArrayList(obj)) {
    ExtractWeakArrayReferences(WeakArrayList::kHeaderSize, entry,
                               Cast<WeakArrayList>(obj));
  } else if (IsContext(obj)) {
    ExtractContextReferences(entry, Cast<Context>(obj));
  } else if (IsEphemeronHashTable(obj)) {
    ExtractEphemeronHashTableReferences(entry, Cast<EphemeronHashTable>(obj));
  } else if (IsFixedArray(obj)) {
    ExtractFixedArrayReferences(entry, Cast<FixedArray>(obj));
  } else if (IsWeakCell(obj)) {
    ExtractWeakCellReferences(entry, Cast<WeakCell>(obj));
  } else if (IsHeapNumber(obj)) {
    if (snapshot_->capture_numeric_value()) {
      ExtractNumberReference(entry, obj);
    }
  } else if (IsBytecodeArray(obj)) {
    ExtractBytecodeArrayReferences(entry, Cast<BytecodeArray>(obj));
  } else if (IsScopeInfo(obj)) {
    ExtractScopeInfoReferences(entry, Cast<ScopeInfo>(obj));
  } else if (IsCppHeapExternalObject(obj)) {
    ExtractCppHeapExternalReferences(entry, Cast<CppHeapExternalObject>(obj));
#if V8_ENABLE_WEBASSEMBLY
  } else if (IsWasmStruct(obj)) {
    ExtractWasmStructReferences(Cast<WasmStruct>(obj), entry);
  } else if (IsWasmArray(obj)) {
    ExtractWasmArrayReferences(Cast<WasmArray>(obj), entry);
  } else if (IsWasmTrustedInstanceData(obj)) {
    ExtractWasmTrustedInstanceDataReferences(Cast<WasmTrustedInstanceData>(obj),
                                             entry);
#endif // V8_ENABLE_WEBASSEMBLY
  }
}
References v8::internal::HeapSnapshot::capture_numeric_value(), ExtractAccessorInfoReferences(), ExtractAccessorPairReferences(), ExtractAllocationSiteReferences(), ExtractArrayBoilerplateDescriptionReferences(), ExtractBytecodeArrayReferences(), ExtractCellReferences(), ExtractCodeReferences(), ExtractContextReferences(), ExtractCppHeapExternalReferences(), ExtractDescriptorArrayReferences(), ExtractEnumCacheReferences(), ExtractEphemeronHashTableReferences(), ExtractFeedbackCellReferences(), ExtractFeedbackVectorReferences(), ExtractFixedArrayReferences(), ExtractInstructionStreamReferences(), ExtractJSArrayBufferReferences(), ExtractJSCollectionReferences(), ExtractJSDisposableStackReferences(), ExtractJSGeneratorObjectReferences(), ExtractJSGlobalProxyReferences(), ExtractJSObjectReferences(), ExtractJSPromiseReferences(), ExtractJSWeakCollectionReferences(), ExtractJSWeakRefReferences(), ExtractMapReferences(), ExtractNumberReference(), ExtractPropertyCellReferences(), ExtractPrototypeInfoReferences(), ExtractRegExpBoilerplateDescriptionReferences(), ExtractScopeInfoReferences(), ExtractScriptReferences(), ExtractSharedFunctionInfoReferences(), ExtractStringReferences(), ExtractSymbolReferences(), ExtractTransitionArrayReferences(), ExtractWeakArrayReferences(), ExtractWeakCellReferences(), OFFSET_OF_DATA_START, and snapshot_.
Referenced by IterateAndExtractReferences().
ExtractRegExpBoilerplateDescriptionReferences()
void v8::internal::V8HeapExplorer::ExtractRegExpBoilerplateDescriptionReferences (HeapEntry * entry, Tagged< RegExpBoilerplateDescription > value) [private]
Definition at line 2034 of file heap-snapshot-generator.cc.
                                                                  {
  TagObject(value->data(isolate()), "(RegExpData)", HeapEntry::kCode);
}
References isolate(), v8::internal::HeapEntry::kCode, TagObject(), and v8::internal::value.
Referenced by ExtractReferences().
ExtractScopeInfoReferences()
void v8::internal::V8HeapExplorer::ExtractScopeInfoReferences (HeapEntry * entry, Tagged< ScopeInfo > info) [private]
Definition at line 2117 of file heap-snapshot-generator.cc.
                                                                        {
  if (!info->HasInlinedLocalNames()) {
    TagObject(info->context_local_names_hashtable(), "(context local names)",
              HeapEntry::kCode);
  }
}
References v8::internal::HeapEntry::kCode, and TagObject().
Referenced by ExtractReferences().
ExtractScriptReferences()
void v8::internal::V8HeapExplorer::ExtractScriptReferences (HeapEntry * entry, Tagged< Script > script) [private]
Definition at line 1865 of file heap-snapshot-generator.cc.
                                                                    {
  SetInternalReference(entry, "source", script->source(),
                       Script::kSourceOffset);
  SetInternalReference(entry, "name", script->name(), Script::kNameOffset);
  SetInternalReference(entry, "context_data", script->context_data(),
                       Script::kContextDataOffset);
  TagObject(script->line_ends(), "(script line ends)", HeapEntry::kCode);
  SetInternalReference(entry, "line_ends", script->line_ends(),
                       Script::kLineEndsOffset);
  TagObject(script->infos(), "(infos)", HeapEntry::kCode);
  TagObject(script->host_defined_options(), "(host-defined options)",
            HeapEntry::kCode);
#if V8_ENABLE_WEBASSEMBLY
  if (script->type() == Script::Type::kWasm) {
    // Wasm reuses some otherwise unused fields for wasm-specific information.
    SetInternalReference(entry, "wasm_breakpoint_infos",
                         script->wasm_breakpoint_infos(),
                         Script::kEvalFromSharedOrWrappedArgumentsOffset);
    SetInternalReference(entry, "wasm_managed_native_module",
                         script->wasm_managed_native_module(),
                         Script::kEvalFromPositionOffset);
    SetInternalReference(entry, "wasm_weak_instance_list",
                         script->wasm_weak_instance_list(),
                         Script::kInfosOffset);
  }
#endif
}
References v8::internal::HeapEntry::kCode, v8::internal::kEvalFromPositionOffset, v8::internal::script, SetInternalReference(), and TagObject().
Referenced by ExtractReferences().
ExtractSharedFunctionInfoReferences()
void v8::internal::V8HeapExplorer::ExtractSharedFunctionInfoReferences (HeapEntry * entry, Tagged< SharedFunctionInfo > shared) [private]
Definition at line 1825 of file heap-snapshot-generator.cc.
                                                         {
  TagObject(shared, "(shared function info)");
  {
    std::unique_ptr<char[]> name = shared->DebugNameCStr();
    Tagged<Code> code = shared->GetCode(isolate());
    TagObject(code, name[0] != '\0'
                        ? names_->GetFormatted("(code for %s)", name.get())
                        : names_->GetFormatted("(%s code)",
                                               CodeKindToString(code->kind())));
    if (code->has_instruction_stream()) {
      TagObject(
          code->instruction_stream(),
          name[0] != '\0'
              ? names_->GetFormatted("(instruction stream for %s)", name.get())
              : names_->GetFormatted("(%s instruction stream)",
                                     CodeKindToString(code->kind())));
    }
  }
  Tagged<Object> name_or_scope_info = shared->name_or_scope_info(kAcquireLoad);
  if (IsScopeInfo(name_or_scope_info)) {
    TagObject(name_or_scope_info, "(function scope info)");
  }
  SetInternalReference(entry, "name_or_scope_info", name_or_scope_info,
                       SharedFunctionInfo::kNameOrScopeInfoOffset);
  SetInternalReference(entry, "script", shared->script(kAcquireLoad),
                       SharedFunctionInfo::kScriptOffset);
  SetInternalReference(entry, "trusted_function_data",
                       shared->GetTrustedData(isolate()),
                       SharedFunctionInfo::kTrustedFunctionDataOffset);
  SetInternalReference(entry, "untrusted_function_data",
                       shared->GetUntrustedData(),
                       SharedFunctionInfo::kUntrustedFunctionDataOffset);
  SetInternalReference(
      entry, "raw_outer_scope_info_or_feedback_metadata",
      shared->raw_outer_scope_info_or_feedback_metadata(),
      SharedFunctionInfo::kOuterScopeInfoOrFeedbackMetadataOffset);
}
References code, v8::internal::CodeKindToString(), isolate(), v8::kAcquireLoad, v8::internal::name, names_, SetInternalReference(), and TagObject().
Referenced by ExtractReferences().
ExtractStringReferences()
void v8::internal::V8HeapExplorer::ExtractStringReferences (HeapEntry * entry, Tagged< String > obj) [private]
Definition at line 1609 of file heap-snapshot-generator.cc.
                                                                    {
  if (IsConsString(string)) {
    Tagged<ConsString> cs = Cast<ConsString>(string);
    SetInternalReference(entry, "first", cs->first(),
                         offsetof(ConsString, first_));
    SetInternalReference(entry, "second", cs->second(),
                         offsetof(ConsString, second_));
  } else if (IsSlicedString(string)) {
    Tagged<SlicedString> ss = Cast<SlicedString>(string);
    SetInternalReference(entry, "parent", ss->parent(),
                         offsetof(SlicedString, parent_));
  } else if (IsThinString(string)) {
    Tagged<ThinString> ts = Cast<ThinString>(string);
    SetInternalReference(entry, "actual", ts->actual(),
                         offsetof(ThinString, actual_));
  } else if (IsExternalString(string)) {
    Tagged<ExternalString> es = Cast<ExternalString>(string);
    if (const v8::String::ExternalStringResourceBase* resource =
            GetExternalStringResource(es, isolate())) {
      ExternalStringRecorder recorder(entry, this, generator_, names_);
      resource->EstimateSharedMemoryUsage(&recorder);
    }
  }
}
References v8::internal::cs, generator_, v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::GetExternalStringResource(), v8::internal::InstanceTypeChecker::IsConsString(), v8::internal::InstanceTypeChecker::IsExternalString(), isolate(), v8::internal::InstanceTypeChecker::IsSlicedString(), v8::internal::InstanceTypeChecker::IsThinString(), names_, and SetInternalReference().
Referenced by ExtractReferences().
ExtractSymbolReferences()
void v8::internal::V8HeapExplorer::ExtractSymbolReferences (HeapEntry * entry, Tagged< Symbol > symbol) [private]
Definition at line 1635 of file heap-snapshot-generator.cc.
                                                                    {
  SetInternalReference(entry, "name", symbol->description(),
                       offsetof(Symbol, description_));
}
References SetInternalReference().
Referenced by ExtractReferences().
ExtractTransitionArrayReferences()
void v8::internal::V8HeapExplorer::ExtractTransitionArrayReferences (HeapEntry * entry, Tagged< TransitionArray > transitions) [private]
Definition at line 2172 of file heap-snapshot-generator.cc.
                                                           {
  if (transitions->HasPrototypeTransitions()) {
    TagObject(transitions->GetPrototypeTransitions(), "(prototype transitions)",
              HeapEntry::kObjectShape);
  }
}
References v8::internal::HeapEntry::kObjectShape, and TagObject().
Referenced by ExtractReferences().
ExtractWeakArrayReferences()
template<typename T >
void v8::internal::V8HeapExplorer::ExtractWeakArrayReferences (int header_size, HeapEntry * entry, Tagged< T > array) [private]
Definition at line 2181 of file heap-snapshot-generator.cc.
                                                                 {
  for (int i = 0; i < array->length(); ++i) {
    Tagged<MaybeObject> object = array->get(i);
    Tagged<HeapObject> heap_object;
    if (object.GetHeapObjectIfWeak(&heap_object)) {
      SetWeakReference(entry, i, heap_object, header_size + i * kTaggedSize);
    } else if (object.GetHeapObjectIfStrong(&heap_object)) {
      SetInternalReference(entry, i, heap_object,
                           header_size + i * kTaggedSize);
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kTaggedSize, SetInternalReference(), and SetWeakReference().
Referenced by ExtractReferences().
ExtractWeakCellReferences()
void v8::internal::V8HeapExplorer::ExtractWeakCellReferences (HeapEntry * entry, Tagged< WeakCell > weak_cell) [private]
Definition at line 1916 of file heap-snapshot-generator.cc.
                                                                           {
  SetWeakReference(entry, "target", weak_cell->target(),
                   WeakCell::kTargetOffset);
  SetWeakReference(entry, "unregister_token", weak_cell->unregister_token(),
                   WeakCell::kUnregisterTokenOffset);
}
References SetWeakReference().
Referenced by ExtractReferences().
GetConstructor()
Tagged< JSFunction > v8::internal::V8HeapExplorer::GetConstructor (Isolate * isolate, Tagged< JSReceiver > receiver) [static]
Definition at line 2467 of file heap-snapshot-generator.cc.
                                                                               {
  DisallowGarbageCollection no_gc;
  HandleScope scope(isolate);
  MaybeDirectHandle<JSFunction> maybe_constructor =
      JSReceiver::GetConstructor(isolate, direct_handle(receiver, isolate));
  if (maybe_constructor.is_null()) return JSFunction();
  return *maybe_constructor.ToHandleChecked();
}
References v8::internal::direct_handle(), v8::internal::JSReceiver::GetConstructor(), v8::internal::MaybeDirectHandle< T >::is_null(), isolate(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::MaybeDirectHandle< T >::ToHandleChecked().
Referenced by GetLocationFunction().
GetConstructorName()
Tagged< String > v8::internal::V8HeapExplorer::GetConstructorName (Isolate * isolate, Tagged< JSObject > object) [static]
Definition at line 2479 of file heap-snapshot-generator.cc.
                                                                           {
  DisallowGarbageCollection no_gc;
  HandleScope scope(isolate);
  return *JSReceiver::GetConstructorName(isolate,
                                         direct_handle(object, isolate));
}
References v8::internal::direct_handle(), v8::internal::JSReceiver::GetConstructorName(), isolate(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by AddEntry().
GetEntry()
HeapEntry * v8::internal::V8HeapExplorer::GetEntry (Tagged< Object > obj) [private]
Definition at line 2487 of file heap-snapshot-generator.cc.
                                                      {
  if (IsHeapObject(obj)) {
    return generator_->FindOrAddEntry(reinterpret_cast<void*>(obj.ptr()), this);
  }
  DCHECK(IsSmi(obj));
  if (!snapshot_->capture_numeric_value()) {
    return nullptr;
  }
  return generator_->FindOrAddEntry(Cast<Smi>(obj), this);
}
References v8::internal::HeapSnapshot::capture_numeric_value(), v8::internal::DCHECK(), v8::internal::HeapSnapshotGenerator::FindOrAddEntry(), generator_, v8::internal::IsHeapObject(), v8::internal::IsSmi(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and snapshot_.
Referenced by ExtractEphemeronHashTableReferences(), IterateAndExtractReferences(), SetContextReference(), SetElementReference(), SetGcSubrootReference(), SetHiddenReference(), SetInternalReference(), SetNativeBindReference(), SetPropertyReference(), SetUserGlobalReference(), SetWeakReference(), and TagObject().
GetLocationFunction()
Tagged< JSFunction > v8::internal::V8HeapExplorer::GetLocationFunction (Tagged< HeapObject > object) [private]
Definition at line 850 of file heap-snapshot-generator.cc.
                               {
  DisallowHeapAllocation no_gc;
  if (IsJSFunction(object)) {
    return Cast<JSFunction>(object);
  } else if (IsJSGeneratorObject(object)) {
    Tagged<JSGeneratorObject> gen = Cast<JSGeneratorObject>(object);
    return gen->function();
  } else if (IsJSObject(object)) {
    Tagged<JSObject> obj = Cast<JSObject>(object);
    Tagged<JSFunction> maybe_constructor =
        GetConstructor(heap_->isolate(), obj);
    return maybe_constructor;
  }
  return JSFunction();
}
References GetConstructor(), heap_, v8::internal::Heap::isolate(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by ExtractLocation().
GetStrongGcSubrootName()
const char * v8::internal::V8HeapExplorer::GetStrongGcSubrootName (Tagged< HeapObject > object) [private]
Definition at line 2877 of file heap-snapshot-generator.cc.
                                                                            {
  if (strong_gc_subroot_names_.empty()) {
    Isolate* isolate = Isolate::FromHeap(heap_);
    for (RootIndex root_index = RootIndex::kFirstStrongOrReadOnlyRoot;
         root_index <= RootIndex::kLastStrongOrReadOnlyRoot; ++root_index) {
      const char* name = RootsTable::name(root_index);
      Tagged<Object> root = isolate->root(root_index);
      CHECK(!IsSmi(root));
      strong_gc_subroot_names_.emplace(Cast<HeapObject>(root), name);
    }
    CHECK(!strong_gc_subroot_names_.empty());
  }
  auto it = strong_gc_subroot_names_.find(object);
  return it != strong_gc_subroot_names_.end() ? it->second : nullptr;
}
References CHECK, v8::internal::Isolate::FromHeap(), heap_, isolate(), v8::internal::IsSmi(), v8::internal::kFirstStrongOrReadOnlyRoot, v8::internal::kLastStrongOrReadOnlyRoot, v8::internal::name, v8::internal::RootsTable::name(), v8::internal::Isolate::root(), and strong_gc_subroot_names_.
Referenced by SetGcSubrootReference().
GetSystemEntryName()
const char * v8::internal::V8HeapExplorer::GetSystemEntryName (Tagged< HeapObject > object) [private]
Definition at line 1090 of file heap-snapshot-generator.cc.
                                                                        {
  if (IsMap(object)) {
    switch (Cast<Map>(object)->instance_type()) {
#define MAKE_STRING_MAP_CASE(instance_type, size, name, Name) \
  case instance_type: \
    return "system / Map (" #Name ")";
      STRING_TYPE_LIST(MAKE_STRING_MAP_CASE)
#undef MAKE_STRING_MAP_CASE
      default:
        return "system / Map";
    }
  }
  InstanceType type = object->map()->instance_type();
  // Empty string names are special: TagObject can overwrite them, and devtools
  // will report them as "(internal array)".
  if (InstanceTypeChecker::IsFixedArray(type) ||
      InstanceTypeChecker::IsFixedDoubleArray(type) ||
      InstanceTypeChecker::IsByteArray(type)) {
    return "";
  }
  switch (type) {
#define MAKE_TORQUE_CASE(Name, TYPE) \
  case TYPE: \
    return "system / " #Name;
    // The following lists include every non-String instance type.
    // This includes a few types that already have non-"system" names assigned
    // by AddEntry, but this is a convenient way to avoid manual upkeep here.
    TORQUE_INSTANCE_CHECKERS_SINGLE_FULLY_DEFINED(MAKE_TORQUE_CASE)
    TORQUE_INSTANCE_CHECKERS_MULTIPLE_FULLY_DEFINED(MAKE_TORQUE_CASE)
    TORQUE_INSTANCE_CHECKERS_SINGLE_ONLY_DECLARED(MAKE_TORQUE_CASE)
    TORQUE_INSTANCE_CHECKERS_MULTIPLE_ONLY_DECLARED(MAKE_TORQUE_CASE)
#undef MAKE_TORQUE_CASE
    // Strings were already handled by AddEntry.
#define MAKE_STRING_CASE(instance_type, size, name, Name) \
  case instance_type: \
    UNREACHABLE();
    STRING_TYPE_LIST(MAKE_STRING_CASE)
#undef MAKE_STRING_CASE
  }
}
References MAKE_STRING_CASE, MAKE_STRING_MAP_CASE, MAKE_TORQUE_CASE, STRING_TYPE_LIST, and v8::internal::tracing::type.
Referenced by AddEntry().
GetSystemEntryType()
HeapEntry::Type v8::internal::V8HeapExplorer::GetSystemEntryType (Tagged< HeapObject > object) [private]
Definition at line 1135 of file heap-snapshot-generator.cc.
                                                                          {
  InstanceType type = object->map()->instance_type();
  if (InstanceTypeChecker::IsAllocationSite(type) ||
      InstanceTypeChecker::IsArrayBoilerplateDescription(type) ||
      InstanceTypeChecker::IsBytecodeArray(type) ||
      InstanceTypeChecker::IsBytecodeWrapper(type) ||
      InstanceTypeChecker::IsClosureFeedbackCellArray(type) ||
      InstanceTypeChecker::IsCode(type) ||
      InstanceTypeChecker::IsCodeWrapper(type) ||
      InstanceTypeChecker::IsFeedbackCell(type) ||
      InstanceTypeChecker::IsFeedbackMetadata(type) ||
      InstanceTypeChecker::IsFeedbackVector(type) ||
      InstanceTypeChecker::IsInstructionStream(type) ||
      InstanceTypeChecker::IsInterpreterData(type) ||
      InstanceTypeChecker::IsLoadHandler(type) ||
      InstanceTypeChecker::IsObjectBoilerplateDescription(type) ||
      InstanceTypeChecker::IsPreparseData(type) ||
      InstanceTypeChecker::IsRegExpBoilerplateDescription(type) ||
      InstanceTypeChecker::IsScopeInfo(type) ||
      InstanceTypeChecker::IsStoreHandler(type) ||
      InstanceTypeChecker::IsTemplateObjectDescription(type) ||
      InstanceTypeChecker::IsTurbofanType(type) ||
      InstanceTypeChecker::IsUncompiledData(type)) {
    return HeapEntry::kCode;
  }
  // This check must come second, because some subtypes of FixedArray are
  // determined above to represent code content.
  if (InstanceTypeChecker::IsFixedArray(type) ||
      InstanceTypeChecker::IsFixedDoubleArray(type) ||
      InstanceTypeChecker::IsByteArray(type)) {
    return HeapEntry::kArray;
  }
  // Maps in read-only space are for internal V8 data, not user-defined object
  // shapes.
  if ((InstanceTypeChecker::IsMap(type) &&
       !MemoryChunk::FromHeapObject(object)->InReadOnlySpace()) ||
      InstanceTypeChecker::IsDescriptorArray(type) ||
      InstanceTypeChecker::IsTransitionArray(type) ||
      InstanceTypeChecker::IsPrototypeInfo(type) ||
      InstanceTypeChecker::IsEnumCache(type)) {
    return HeapEntry::kObjectShape;
  }
  return HeapEntry::kHidden;
}
References v8::internal::MemoryChunk::FromHeapObject(), v8::internal::HeapEntry::kArray, v8::internal::HeapEntry::kCode, v8::internal::HeapEntry::kHidden, v8::internal::HeapEntry::kObjectShape, and v8::internal::tracing::type.
Referenced by AddEntry().
IsEssentialHiddenReference()
bool v8::internal::V8HeapExplorer::IsEssentialHiddenReference (Tagged< Object > parent, int field_offset) [private]
Definition at line 2658 of file heap-snapshot-generator.cc.
                                                                  {
  if (IsAllocationSite(parent) &&
      field_offset == offsetof(AllocationSiteWithWeakNext, weak_next_))
    return false;
  if (IsContext(parent) &&
      field_offset == Context::OffsetOfElementAt(Context::NEXT_CONTEXT_LINK))
    return false;
  if (IsJSFinalizationRegistry(parent) &&
      field_offset == JSFinalizationRegistry::kNextDirtyOffset)
    return false;
  return true;
}
References v8::internal::Context::NEXT_CONTEXT_LINK, and v8::internal::Context::OffsetOfElementAt().
Referenced by SetHiddenReference().
IsEssentialObject()
bool v8::internal::V8HeapExplorer::IsEssentialObject (Tagged< Object > object) [private]
Definition at line 2635 of file heap-snapshot-generator.cc.
                                                            {
  if (!IsHeapObject(object)) return false;
  // Avoid comparing objects in other pointer compression cages to objects
  // inside the main cage as the comparison may only look at the lower 32 bits.
  if (HeapLayout::InCodeSpace(Cast<HeapObject>(object)) ||
      HeapLayout::InTrustedSpace(Cast<HeapObject>(object))) {
    return true;
  }
  Isolate* isolate = heap_->isolate();
  ReadOnlyRoots roots(isolate);
  return !IsOddball(object, isolate) && object != roots.the_hole_value() &&
         object != roots.empty_byte_array() &&
         object != roots.empty_fixed_array() &&
         object != roots.empty_weak_fixed_array() &&
         object != roots.empty_descriptor_array() &&
         object != roots.fixed_array_map() && object != roots.cell_map() &&
         object != roots.global_property_cell_map() &&
         object != roots.shared_function_info_map() &&
         object != roots.free_space_map() &&
         object != roots.one_pointer_filler_map() &&
         object != roots.two_pointer_filler_map();
}
References heap_, v8::internal::HeapLayout::InCodeSpace(), v8::internal::HeapLayout::InTrustedSpace(), v8::internal::IsHeapObject(), isolate(), and v8::internal::Heap::isolate().
Referenced by SetHiddenReference(), SetInternalReference(), SetWeakReference(), and TagObject().
isolate()
Isolate* v8::internal::V8HeapExplorer::isolate () [inline]
Definition at line 421 of file heap-snapshot-generator.h.
{ return Isolate::FromHeap(heap_); }
References v8::internal::Isolate::FromHeap().
Referenced by AddEntry(), CollectTemporaryGlobalObjectsTags(), ExtractFeedbackVectorReferences(), ExtractJSObjectReferences(), ExtractPropertyReferences(), ExtractRegExpBoilerplateDescriptionReferences(), ExtractSharedFunctionInfoReferences(), ExtractStringReferences(), GetConstructor(), GetConstructorName(), GetStrongGcSubrootName(), IsEssentialObject(), PopulateLineEnds(), RecursivelyTagConstantPool(), and v8::internal::IndexedReferencesExtractor::VisitIndirectPointer().
IterateAndExtractReferences()
bool v8::internal::V8HeapExplorer::IterateAndExtractReferences (HeapSnapshotGenerator * generator)
Definition at line 2556 of file heap-snapshot-generator.cc.
                                      {
  generator_ = generator;
  // Create references to the synthetic roots.
  SetRootGcRootsReference();
  for (int root = 0; root < static_cast<int>(Root::kNumberOfRoots); root++) {
    SetGcRootsReference(static_cast<Root>(root));
  }
  // Make sure builtin code objects get their builtin tags
  // first. Otherwise a particular JSFunction object could set
  // its custom name to a generic builtin.
  RootsReferencesExtractor extractor(this);
  ReadOnlyRoots(heap_).Iterate(&extractor);
  heap_->IterateRoots(
      &extractor,
      base::EnumSet<SkipRoot>{SkipRoot::kWeak, SkipRoot::kTracedHandles});
  // TODO(v8:11800): The heap snapshot generator incorrectly considers the weak
  // string tables as strong retainers. Move IterateWeakRoots after
  // SetVisitingWeakRoots.
  heap_->IterateWeakRoots(&extractor, {});
  extractor.SetVisitingWeakRoots();
  heap_->IterateWeakGlobalHandles(&extractor);
  bool interrupted = false;
  CombinedHeapObjectIterator iterator(heap_);
  PtrComprCageBase cage_base(heap_->isolate());
  // Heap iteration need not be finished but progress reporting may depend on
  // it being finished.
  for (Tagged<HeapObject> obj = iterator.Next(); !obj.is_null();
       obj = iterator.Next(), progress_->ProgressStep()) {
    if (interrupted) continue;
    max_pointers_ = obj->Size(cage_base) / kTaggedSize;
    if (max_pointers_ > visited_fields_.size()) {
      // Reallocate to right size.
      visited_fields_.resize(max_pointers_, false);
    }
#ifdef V8_ENABLE_HEAP_SNAPSHOT_VERIFY
    std::unique_ptr<HeapEntryVerifier> verifier;
    // MarkingVisitorBase doesn't expect that we will ever visit read-only
    // objects, and fails DCHECKs if we attempt to. Read-only objects can
    // never retain read-write objects, so there is no risk in skipping
    // verification for them.
    if (v8_flags.heap_snapshot_verify &&
        !MemoryChunk::FromHeapObject(obj)->InReadOnlySpace()) {
      verifier = std::make_unique<HeapEntryVerifier>(generator, obj);
    }
#endif
    HeapEntry* entry = GetEntry(obj);
    ExtractReferences(entry, obj);
    SetInternalReference(entry, "map", obj->map(cage_base),
                         HeapObject::kMapOffset);
    // Extract unvisited fields as hidden references and restore tags
    // of visited fields.
    IndexedReferencesExtractor refs_extractor(this, obj, entry);
    VisitObject(heap_->isolate(), obj, &refs_extractor);
#if DEBUG
    // Ensure visited_fields_ doesn't leak to the next object.
    for (size_t i = 0; i < max_pointers_; ++i) {
      DCHECK(!visited_fields_[i]);
    }
#endif // DEBUG
    // Extract location for specific object types
    ExtractLocation(entry, obj);
    if (!progress_->ProgressReport(false)) interrupted = true;
  }
  generator_ = nullptr;
  return interrupted ? false : progress_->ProgressReport(true);
}
References v8::internal::DCHECK(), ExtractLocation(), ExtractReferences(), false, v8::internal::MemoryChunk::FromHeapObject(), generator_, GetEntry(), heap_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::MemoryChunk::InReadOnlySpace(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::Heap::isolate(), v8::internal::ReadOnlyRoots::Iterate(), v8::internal::Heap::IterateRoots(), v8::internal::Heap::IterateWeakGlobalHandles(), v8::internal::Heap::IterateWeakRoots(), v8::internal::HeapObject::kMapOffset, v8::internal::kNumberOfRoots, v8::internal::kTaggedSize, v8::internal::kTracedHandles, v8::internal::kWeak, max_pointers_, v8::internal::CombinedHeapObjectIterator::Next(), progress_, v8::internal::SnapshottingProgressReportingInterface::ProgressReport(), v8::internal::SnapshottingProgressReportingInterface::ProgressStep(), SetGcRootsReference(), SetInternalReference(), SetRootGcRootsReference(), v8::internal::RootsReferencesExtractor::SetVisitingWeakRoots(), v8::internal::v8_flags, visited_fields_, and v8::internal::VisitObject().
Referenced by v8::internal::HeapSnapshotGenerator::FillReferences().
MakeGlobalObjectTagMap()
void v8::internal::V8HeapExplorer::MakeGlobalObjectTagMap (TemporaryGlobalObjectTags && global_object_tags)
Definition at line 2993 of file heap-snapshot-generator.cc.
                                                    {
  HandleScope scope(heap_->isolate());
  for (const auto& pair : global_object_tags) {
    if (!pair.first.IsEmpty()) {
      // Temporary local.
      auto local = Utils::OpenPersistent(pair.first);
      global_object_tag_map_.emplace(Cast<JSGlobalObject>(*local), pair.second);
    }
  }
}
References global_object_tag_map_, heap_, v8::internal::Heap::isolate(), and v8::Utils::OpenPersistent().
Referenced by v8::internal::HeapSnapshotGenerator::GenerateSnapshot(), and v8::internal::HeapSnapshotGenerator::GenerateSnapshotAfterGC().
MarkVisitedField()
void v8::internal::V8HeapExplorer::MarkVisitedField (int offset) [private]
Definition at line 2684 of file heap-snapshot-generator.cc.
                                                {
  if (offset < 0) return;
  int index = offset / kTaggedSize;
  DCHECK_LT(index, max_pointers_);
  DCHECK(!visited_fields_[index]);
  visited_fields_[index] = true;
}
References v8::internal::DCHECK(), DCHECK_LT, v8::internal::index, v8::internal::kTaggedSize, max_pointers_, and visited_fields_.
Referenced by SetContextReference(), SetInternalReference(), SetPropertyReference(), and SetWeakReference().
operator=()
V8HeapExplorer& v8::internal::V8HeapExplorer::operator= (const V8HeapExplorer &) [delete]
PopulateLineEnds()
void v8::internal::V8HeapExplorer::PopulateLineEnds ()
Definition at line 1183 of file heap-snapshot-generator.cc.
                                      {
  std::vector<Handle<Script>> scripts;
  HandleScope scope(isolate());
  {
    Script::Iterator iterator(isolate());
    for (Tagged<Script> script = iterator.Next(); !script.is_null();
         script = iterator.Next()) {
      if (!script->has_line_ends()) {
        scripts.push_back(handle(script, isolate()));
      }
    }
  }
  for (auto& script : scripts) {
    snapshot_->AddScriptLineEnds(script->id(),
                                 Script::GetLineEnds(isolate(), script));
  }
}
References v8::internal::HeapSnapshot::AddScriptLineEnds(), v8::internal::Script::GetLineEnds(), v8::internal::handle(), isolate(), v8::internal::Script::Iterator::Next(), v8::internal::script, and snapshot_.
Referenced by v8::internal::HeapSnapshotGenerator::GenerateSnapshot(), and v8::internal::HeapSnapshotGenerator::GenerateSnapshotAfterGC().
RecursivelyTagConstantPool()
void v8::internal::V8HeapExplorer::RecursivelyTagConstantPool (Tagged< Object > obj, const char * tag, HeapEntry::Type type, int recursion_limit) [private]
Definition at line 2907 of file heap-snapshot-generator.cc.
                                                                     {
  --recursion_limit;
  if (IsFixedArrayExact(obj, isolate())) {
    Tagged<FixedArray> arr = Cast<FixedArray>(obj);
    TagObject(arr, tag, type);
    if (recursion_limit <= 0) return;
    for (int i = 0; i < arr->length(); ++i) {
      RecursivelyTagConstantPool(arr->get(i), tag, type, recursion_limit);
    }
  } else if (IsTrustedFixedArray(obj, isolate())) {
    Tagged<TrustedFixedArray> arr = Cast<TrustedFixedArray>(obj);
    TagObject(arr, tag, type, /*overwrite_existing_name=*/true);
    if (recursion_limit <= 0) return;
    for (int i = 0; i < arr->length(); ++i) {
      RecursivelyTagConstantPool(arr->get(i), tag, type, recursion_limit);
    }
  } else if (IsNameDictionary(obj, isolate()) ||
             IsNumberDictionary(obj, isolate())) {
    TagObject(obj, tag, type);
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate(), TagObject(), and v8::internal::tracing::type.
Referenced by ExtractBytecodeArrayReferences().
SetContextReference()
void v8::internal::V8HeapExplorer::SetContextReference (HeapEntry * parent_entry, Tagged< String > reference_name, Tagged< Object > child, int field_offset) [private]
Definition at line 2672 of file heap-snapshot-generator.cc.
                                                           {
  HeapEntry* child_entry = GetEntry(child_obj);
  if (child_entry == nullptr) return;
  parent_entry->SetNamedReference(HeapGraphEdge::kContextVariable,
                                  names_->GetName(reference_name), child_entry,
                                  generator_);
  MarkVisitedField(field_offset);
}
References generator_, GetEntry(), v8::internal::StringsStorage::GetName(), v8::internal::HeapGraphEdge::kContextVariable, MarkVisitedField(), names_, and v8::internal::HeapEntry::SetNamedReference().
Referenced by ExtractContextReferences().
SetDataOrAccessorPropertyReference()
void v8::internal::V8HeapExplorer::SetDataOrAccessorPropertyReference (PropertyKind kind, HeapEntry * parent_entry, Tagged< Name > reference_name, Tagged< Object > child, const char * name_format_string = nullptr, int field_offset = -1) [private]
Definition at line 2784 of file heap-snapshot-generator.cc.
                      {
  if (kind == PropertyKind::kAccessor) {
    ExtractAccessorPairProperty(parent_entry, reference_name, child_obj,
                                field_offset);
  } else {
    SetPropertyReference(parent_entry, reference_name, child_obj,
                         name_format_string, field_offset);
  }
}
References ExtractAccessorPairProperty(), v8::internal::kAccessor, and SetPropertyReference().
Referenced by ExtractPropertyReferences().
SetElementReference()
void v8::internal::V8HeapExplorer::SetElementReference (HeapEntry * parent_entry, int index, Tagged< Object > child) [private]
Definition at line 2701 of file heap-snapshot-generator.cc.
                                                                   {
  HeapEntry* child_entry = GetEntry(child_obj);
  if (child_entry == nullptr) return;
  parent_entry->SetIndexedReference(HeapGraphEdge::kElement, index, child_entry,
                                    generator_);
}
References generator_, GetEntry(), v8::internal::index, v8::internal::HeapGraphEdge::kElement, and v8::internal::HeapEntry::SetIndexedReference().
Referenced by ExtractElementReferences().
SetGcRootsReference()
void v8::internal::V8HeapExplorer::SetGcRootsReference (Root root) [private]
Definition at line 2830 of file heap-snapshot-generator.cc.
                                                  {
  snapshot_->gc_roots()->SetIndexedAutoIndexReference(
      HeapGraphEdge::kElement, snapshot_->gc_subroot(root), generator_);
}
References v8::internal::HeapSnapshot::gc_roots(), v8::internal::HeapSnapshot::gc_subroot(), generator_, v8::internal::HeapGraphEdge::kElement, v8::internal::HeapEntry::SetIndexedAutoIndexReference(), and snapshot_.
Referenced by IterateAndExtractReferences().
SetGcSubrootReference()
void v8::internal::V8HeapExplorer::SetGcSubrootReference (Root root, const char * description, bool is_weak, Tagged< Object > child) [private]
Definition at line 2835 of file heap-snapshot-generator.cc.
                                                                     {
  if (IsSmi(child_obj)) {
    // TODO(arenevier): if we handle smis here, the snapshot gets 2 to 3 times
    // slower on large heaps. According to perf, The bulk of the extra works
    // happens in TemplateHashMapImpl::Probe method, when tyring to get
    // names->GetFormatted("%d / %s", index, description)
    return;
  }
  HeapEntry* child_entry = GetEntry(child_obj);
  if (child_entry == nullptr) return;
  auto child_heap_obj = Cast<HeapObject>(child_obj);
  const char* name = GetStrongGcSubrootName(child_heap_obj);
  HeapGraphEdge::Type edge_type =
      is_weak ? HeapGraphEdge::kWeak : HeapGraphEdge::kInternal;
  if (name != nullptr) {
    snapshot_->gc_subroot(root)->SetNamedReference(edge_type, name, child_entry,
                                                   generator_);
  } else {
    snapshot_->gc_subroot(root)->SetNamedAutoIndexReference(
        edge_type, description, child_entry, names_, generator_);
  }
  // For full heap snapshots we do not emit user roots but rather rely on
  // regular GC roots to retain objects.
  if (snapshot_->expose_internals()) return;
  // Add a shortcut to JS global object reference at snapshot root.
  // That allows the user to easily find global objects. They are
  // also used as starting points in distance calculations.
  if (is_weak || !IsNativeContext(child_heap_obj)) return;
  Tagged<JSGlobalObject> global =
      Cast<Context>(child_heap_obj)->global_object();
  if (!IsJSGlobalObject(global)) return;
  if (!user_roots_.insert(global).second) return;
  SetUserGlobalReference(global);
}
References v8::internal::HeapSnapshot::expose_internals(), v8::internal::HeapSnapshot::gc_subroot(), generator_, GetEntry(), GetStrongGcSubrootName(), v8::internal::IsSmi(), v8::internal::HeapGraphEdge::kInternal, v8::internal::HeapGraphEdge::kWeak, v8::internal::name, names_, v8::internal::HeapEntry::SetNamedAutoIndexReference(), v8::internal::HeapEntry::SetNamedReference(), SetUserGlobalReference(), snapshot_, and user_roots_.
Referenced by v8::internal::RootsReferencesExtractor::VisitRootPointer(), and v8::internal::RootsReferencesExtractor::VisitRootPointers().
SetHiddenReference()
void v8::internal::V8HeapExplorer::SetHiddenReference (Tagged< HeapObject > parent_obj, HeapEntry * parent_entry, int index, Tagged< Object > child, int field_offset) [private]
Definition at line 2737 of file heap-snapshot-generator.cc.
                                                          {
  DCHECK_EQ(parent_entry, GetEntry(parent_obj));
  DCHECK(!MapWord::IsPacked(child_obj.ptr()));
  if (!IsEssentialObject(child_obj)) {
    return;
  }
  HeapEntry* child_entry = GetEntry(child_obj);
  DCHECK_NOT_NULL(child_entry);
  if (IsEssentialHiddenReference(parent_obj, field_offset)) {
    parent_entry->SetIndexedReference(HeapGraphEdge::kHidden, index,
                                      child_entry, generator_);
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, generator_, GetEntry(), v8::internal::index, IsEssentialHiddenReference(), IsEssentialObject(), v8::internal::MapWord::IsPacked(), v8::internal::HeapGraphEdge::kHidden, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::HeapEntry::SetIndexedReference().
Referenced by v8::internal::IndexedReferencesExtractor::VisitHeapObjectImpl().
SetInternalReference() [1/2]
void v8::internal::V8HeapExplorer::SetInternalReference (HeapEntry * parent_entry, const char * reference_name, Tagged< Object > child, int field_offset = -1) [private]
Definition at line 2709 of file heap-snapshot-generator.cc.
                                                            {
  if (!IsEssentialObject(child_obj)) {
    return;
  }
  HeapEntry* child_entry = GetEntry(child_obj);
  DCHECK_NOT_NULL(child_entry);
  parent_entry->SetNamedReference(HeapGraphEdge::kInternal, reference_name,
                                  child_entry, generator_);
  MarkVisitedField(field_offset);
}
References DCHECK_NOT_NULL, generator_, GetEntry(), IsEssentialObject(), v8::internal::HeapGraphEdge::kInternal, MarkVisitedField(), and v8::internal::HeapEntry::SetNamedReference().
Referenced by ExtractAccessorInfoReferences(), ExtractAccessorPairReferences(), ExtractAllocationSiteReferences(), ExtractArrayBoilerplateDescriptionReferences(), ExtractCellReferences(), ExtractCodeReferences(), ExtractContextReferences(), ExtractDescriptorArrayReferences(), ExtractFeedbackCellReferences(), ExtractFixedArrayReferences(), ExtractInstructionStreamReferences(), ExtractInternalReferences(), ExtractJSCollectionReferences(), ExtractJSDisposableStackReferences(), ExtractJSGeneratorObjectReferences(), ExtractJSObjectReferences(), ExtractJSPromiseReferences(), ExtractJSWeakCollectionReferences(), ExtractMapReferences(), ExtractPropertyCellReferences(), ExtractScriptReferences(), ExtractSharedFunctionInfoReferences(), ExtractStringReferences(), ExtractSymbolReferences(), ExtractWeakArrayReferences(), and IterateAndExtractReferences().
SetInternalReference() [2/2]
void v8::internal::V8HeapExplorer::SetInternalReference (HeapEntry * parent_entry, int index, Tagged< Object > child, int field_offset = -1) [private]
Definition at line 2723 of file heap-snapshot-generator.cc.
                                                            {
  if (!IsEssentialObject(child_obj)) {
    return;
  }
  HeapEntry* child_entry = GetEntry(child_obj);
  DCHECK_NOT_NULL(child_entry);
  parent_entry->SetNamedReference(HeapGraphEdge::kInternal,
                                  names_->GetName(index), child_entry,
                                  generator_);
  MarkVisitedField(field_offset);
}
References DCHECK_NOT_NULL, generator_, GetEntry(), v8::internal::StringsStorage::GetName(), v8::internal::index, IsEssentialObject(), v8::internal::HeapGraphEdge::kInternal, MarkVisitedField(), names_, and v8::internal::HeapEntry::SetNamedReference().
SetNativeBindReference()
void v8::internal::V8HeapExplorer::SetNativeBindReference (HeapEntry * parent_entry, const char * reference_name, Tagged< Object > child) [private]
Definition at line 2692 of file heap-snapshot-generator.cc.
                                                                      {
  HeapEntry* child_entry = GetEntry(child_obj);
  if (child_entry == nullptr) return;
  parent_entry->SetNamedReference(HeapGraphEdge::kShortcut, reference_name,
                                  child_entry, generator_);
}
References generator_, GetEntry(), v8::internal::HeapGraphEdge::kShortcut, and v8::internal::HeapEntry::SetNamedReference().
Referenced by ExtractJSObjectReferences().
SetPropertyReference()
void v8::internal::V8HeapExplorer::SetPropertyReference (HeapEntry * parent_entry, Tagged< Name > reference_name, Tagged< Object > child, const char * name_format_string = nullptr, int field_offset = -1) [private]
Definition at line 2797 of file heap-snapshot-generator.cc.
                                                            {
  HeapEntry* child_entry = GetEntry(child_obj);
  if (child_entry == nullptr) return;
  HeapGraphEdge::Type type =
      IsSymbol(reference_name) || Cast<String>(reference_name)->length() > 0
          ? HeapGraphEdge::kProperty
          : HeapGraphEdge::kInternal;
  const char* name = name_format_string != nullptr && IsString(reference_name)
                         ? names_->GetFormatted(
                               name_format_string,
                               Cast<String>(reference_name)->ToCString().get())
                         : names_->GetName(reference_name);
  parent_entry->SetNamedReference(type, name, child_entry, generator_);
  MarkVisitedField(field_offset);
}
References generator_, GetEntry(), v8::internal::StringsStorage::GetName(), v8::internal::HeapGraphEdge::kInternal, v8::internal::HeapGraphEdge::kProperty, MarkVisitedField(), v8::internal::name, names_, v8::internal::HeapEntry::SetNamedReference(), and v8::internal::tracing::type.
Referenced by ExtractAccessorPairProperty(), ExtractJSObjectReferences(), and SetDataOrAccessorPropertyReference().
SetRootGcRootsReference()
void v8::internal::V8HeapExplorer::SetRootGcRootsReference () [private]
Definition at line 2818 of file heap-snapshot-generator.cc.
                                             {
  snapshot_->root()->SetIndexedAutoIndexReference(
      HeapGraphEdge::kElement, snapshot_->gc_roots(), generator_);
}
References v8::internal::HeapSnapshot::gc_roots(), generator_, v8::internal::HeapGraphEdge::kElement, v8::internal::HeapSnapshot::root(), v8::internal::HeapEntry::SetIndexedAutoIndexReference(), and snapshot_.
Referenced by IterateAndExtractReferences().
SetUserGlobalReference()
void v8::internal::V8HeapExplorer::SetUserGlobalReference (Tagged< Object > user_global) [private]
Definition at line 2823 of file heap-snapshot-generator.cc.
                                                                    {
  HeapEntry* child_entry = GetEntry(child_obj);
  DCHECK_NOT_NULL(child_entry);
  snapshot_->root()->SetNamedAutoIndexReference(
      HeapGraphEdge::kShortcut, nullptr, child_entry, names_, generator_);
}
References DCHECK_NOT_NULL, generator_, GetEntry(), v8::internal::HeapGraphEdge::kShortcut, names_, v8::internal::HeapSnapshot::root(), v8::internal::HeapEntry::SetNamedAutoIndexReference(), and snapshot_.
Referenced by SetGcSubrootReference().
SetWeakReference() [1/2]
void v8::internal::V8HeapExplorer::SetWeakReference (HeapEntry * parent_entry, const char * reference_name, Tagged< Object > child_obj, int field_offset, HeapEntry::ReferenceVerification verification = HeapEntry::kVerify) [private]
Definition at line 2754 of file heap-snapshot-generator.cc.
                                                 {
  if (!IsEssentialObject(child_obj)) {
    return;
  }
  HeapEntry* child_entry = GetEntry(child_obj);
  DCHECK_NOT_NULL(child_entry);
  parent_entry->SetNamedReference(HeapGraphEdge::kWeak, reference_name,
                                  child_entry, generator_, verification);
  MarkVisitedField(field_offset);
}
References DCHECK_NOT_NULL, generator_, GetEntry(), IsEssentialObject(), v8::internal::HeapGraphEdge::kWeak, MarkVisitedField(), and v8::internal::HeapEntry::SetNamedReference().
Referenced by ExtractDescriptorArrayReferences(), ExtractEphemeronHashTableReferences(), ExtractFeedbackVectorReferences(), ExtractJSWeakRefReferences(), ExtractMapReferences(), ExtractWeakArrayReferences(), ExtractWeakCellReferences(), v8::internal::IndexedReferencesExtractor::VisitEmbeddedPointer(), and v8::internal::IndexedReferencesExtractor::VisitSlotImpl().
SetWeakReference() [2/2]
void v8::internal::V8HeapExplorer::SetWeakReference (HeapEntry * parent_entry, int index, Tagged< Object > child_obj, std::optional< int > field_offset) [private]
Definition at line 2768 of file heap-snapshot-generator.cc.
                                                                     {
  if (!IsEssentialObject(child_obj)) {
    return;
  }
  HeapEntry* child_entry = GetEntry(child_obj);
  DCHECK_NOT_NULL(child_entry);
  parent_entry->SetNamedReference(HeapGraphEdge::kWeak,
                                  names_->GetFormatted("%d", index),
                                  child_entry, generator_);
  if (field_offset.has_value()) {
    MarkVisitedField(*field_offset);
  }
}
References DCHECK_NOT_NULL, generator_, GetEntry(), v8::internal::index, IsEssentialObject(), v8::internal::HeapGraphEdge::kWeak, MarkVisitedField(), names_, and v8::internal::HeapEntry::SetNamedReference().
TagBuiltinCodeObject()
void v8::internal::V8HeapExplorer::TagBuiltinCodeObject (Tagged< Code > code, const char * name)
Definition at line 1924 of file heap-snapshot-generator.cc.
                                                                             {
  TagObject(code, names_->GetFormatted("(%s builtin code)", name));
  if (code->has_instruction_stream()) {
    TagObject(code->instruction_stream(),
              names_->GetFormatted("(%s builtin instruction stream)", name));
  }
}
References code, v8::internal::name, names_, and TagObject().
Referenced by v8::internal::RootsReferencesExtractor::VisitRootPointer().
TagObject()
void v8::internal::V8HeapExplorer::TagObject (Tagged< Object > obj, const char * tag, std::optional< HeapEntry::Type > type = {}, bool overwrite_existing_name = false) [private]
Definition at line 2893 of file heap-snapshot-generator.cc.
                                                             {
  if (IsEssentialObject(obj)) {
    HeapEntry* entry = GetEntry(obj);
    if (overwrite_existing_name || entry->name()[0] == '\0') {
      entry->set_name(tag);
    }
    if (type.has_value()) {
      entry->set_type(*type);
    }
  }
}
References GetEntry(), IsEssentialObject(), v8::internal::HeapEntry::name(), v8::internal::HeapEntry::set_name(), v8::internal::HeapEntry::set_type(), and v8::internal::tracing::type.
Referenced by ExtractAllocationSiteReferences(), ExtractArrayBoilerplateDescriptionReferences(), ExtractBytecodeArrayReferences(), ExtractCodeReferences(), ExtractContextReferences(), ExtractEnumCacheReferences(), ExtractFeedbackCellReferences(), ExtractFeedbackVectorReferences(), ExtractInstructionStreamReferences(), ExtractJSObjectReferences(), ExtractMapReferences(), ExtractPropertyCellReferences(), ExtractPrototypeInfoReferences(), ExtractRegExpBoilerplateDescriptionReferences(), ExtractScopeInfoReferences(), ExtractScriptReferences(), ExtractSharedFunctionInfoReferences(), ExtractTransitionArrayReferences(), RecursivelyTagConstantPool(), and TagBuiltinCodeObject().
Friends And Related Function Documentation
IndexedReferencesExtractor
friend class IndexedReferencesExtractor [friend]
Definition at line 607 of file heap-snapshot-generator.h.
RootsReferencesExtractor
friend class RootsReferencesExtractor [friend]
Definition at line 608 of file heap-snapshot-generator.h.
Member Data Documentation
generator_
HeapSnapshotGenerator* v8::internal::V8HeapExplorer::generator_ = nullptr [private]
Definition at line 597 of file heap-snapshot-generator.h.
Referenced by ExtractCppHeapExternalReferences(), ExtractEphemeronHashTableReferences(), ExtractJSArrayBufferReferences(), ExtractNumberReference(), ExtractStringReferences(), GetEntry(), IterateAndExtractReferences(), SetContextReference(), SetElementReference(), SetGcRootsReference(), SetGcSubrootReference(), SetHiddenReference(), SetInternalReference(), SetNativeBindReference(), SetPropertyReference(), SetRootGcRootsReference(), SetUserGlobalReference(), and SetWeakReference().
global_object_name_resolver_
v8::HeapProfiler::ObjectNameResolver* v8::internal::V8HeapExplorer::global_object_name_resolver_ [private]
Definition at line 602 of file heap-snapshot-generator.h.
Referenced by CollectTemporaryGlobalObjectsTags().
global_object_tag_map_
std::unordered_map<Tagged<JSGlobalObject>, const char*, Object::Hasher> v8::internal::V8HeapExplorer::global_object_tag_map_ [private]
Definition at line 599 of file heap-snapshot-generator.h.
Referenced by AddEntry(), and MakeGlobalObjectTagMap().
heap_
Heap* v8::internal::V8HeapExplorer::heap_ [private]
Definition at line 592 of file heap-snapshot-generator.h.
Referenced by AddEntry(), CollectTemporaryGlobalObjectsTags(), EstimateObjectsCount(), ExtractJSObjectReferences(), GetLocationFunction(), GetStrongGcSubrootName(), IsEssentialObject(), IterateAndExtractReferences(), MakeGlobalObjectTagMap(), and v8::internal::RootsReferencesExtractor::VisitRootPointers().
heap_object_map_
HeapObjectsMap* v8::internal::V8HeapExplorer::heap_object_map_ [private]
Definition at line 595 of file heap-snapshot-generator.h.
Referenced by AddEntry(), AllocateEntry(), and ExtractNumberReference().
max_pointers_
size_t v8::internal::V8HeapExplorer::max_pointers_ [private]
Definition at line 605 of file heap-snapshot-generator.h.
Referenced by IterateAndExtractReferences(), and MarkVisitedField().
names_
StringsStorage* v8::internal::V8HeapExplorer::names_ [private]
Definition at line 594 of file heap-snapshot-generator.h.
Referenced by AddEntry(), ExtractEphemeronHashTableReferences(), ExtractJSObjectReferences(), ExtractNumberReference(), ExtractSharedFunctionInfoReferences(), ExtractStringReferences(), SetContextReference(), SetGcSubrootReference(), SetInternalReference(), SetPropertyReference(), SetUserGlobalReference(), SetWeakReference(), and TagBuiltinCodeObject().
progress_
SnapshottingProgressReportingInterface* v8::internal::V8HeapExplorer::progress_ [private]
Definition at line 596 of file heap-snapshot-generator.h.
Referenced by IterateAndExtractReferences().
snapshot_
HeapSnapshot* v8::internal::V8HeapExplorer::snapshot_ [private]
Definition at line 593 of file heap-snapshot-generator.h.
Referenced by AddEntry(), AllocateEntry(), ExtractLocationForJSFunction(), ExtractNumberReference(), ExtractPropertyReferences(), ExtractReferences(), GetEntry(), PopulateLineEnds(), SetGcRootsReference(), SetGcSubrootReference(), SetRootGcRootsReference(), and SetUserGlobalReference().
strong_gc_subroot_names_
UnorderedHeapObjectMap<const char*> v8::internal::V8HeapExplorer::strong_gc_subroot_names_ [private]
Definition at line 600 of file heap-snapshot-generator.h.
Referenced by GetStrongGcSubrootName().
user_roots_
std::unordered_set<Tagged<JSGlobalObject>, Object::Hasher> v8::internal::V8HeapExplorer::user_roots_ [private]
Definition at line 601 of file heap-snapshot-generator.h.
Referenced by SetGcSubrootReference().
visited_fields_
std::vector<bool> v8::internal::V8HeapExplorer::visited_fields_ [private]
Definition at line 604 of file heap-snapshot-generator.h.
Referenced by IterateAndExtractReferences(), MarkVisitedField(), v8::internal::IndexedReferencesExtractor::VisitJSDispatchTableEntry(), and v8::internal::IndexedReferencesExtractor::VisitSlotImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.h
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.cc