v8::internal::compiler::LoadElimination::AbstractField Class Reference
Public Member Functions
AbstractField (Zone *zone)
AbstractField (Node *object, FieldInfo info, Zone *zone)
AbstractField const * Extend (Node *object, FieldInfo info, Zone *zone, int current_field_count) const
FieldInfo const * Lookup (Node *object) const
AbstractField const * KillConst (Node *object, Zone *zone) const
AbstractField const * Kill (const AliasStateInfo &alias_info, MaybeHandle< Name > name, Zone *zone) const
bool Equals (AbstractField const *that) const
AbstractField const * Merge (AbstractField const *that, Zone *zone, int *count) const
void Print () const
int count () const
Private Attributes
ZoneMap< Node *, FieldInfo > info_for_node_
Detailed Description
Definition at line 132 of file load-elimination.h.
Constructor & Destructor Documentation
AbstractField() [1/2]
v8::internal::compiler::LoadElimination::AbstractField::AbstractField (Zone * zone) [inline], [explicit]
Definition at line 134 of file load-elimination.h.
: info_for_node_(zone) {}
AbstractField() [2/2]
v8::internal::compiler::LoadElimination::AbstractField::AbstractField (Node * object, FieldInfo info, Zone * zone) [inline]
Definition at line 135 of file load-elimination.h.
        : info_for_node_(zone) {
      info_for_node_.insert(std::make_pair(object, info));
    }
Member Function Documentation
count()
int v8::internal::compiler::LoadElimination::AbstractField::count () const [inline]
Definition at line 184 of file load-elimination.h.
{ return static_cast<int>(info_for_node_.size()); }
Referenced by v8::internal::compiler::LoadElimination::AbstractState::AddField().
Equals()
bool v8::internal::compiler::LoadElimination::AbstractField::Equals (AbstractField const * that) const [inline]
Definition at line 161 of file load-elimination.h.
                                                 {
      return this == that || this->info_for_node_ == that->info_for_node_;
    }
References info_for_node_.
Referenced by v8::internal::compiler::LoadElimination::AbstractState::FieldsEquals().
Extend()
AbstractField const* v8::internal::compiler::LoadElimination::AbstractField::Extend (Node * object, FieldInfo info, Zone * zone, int current_field_count) const [inline]
Definition at line 140 of file load-elimination.h.
                                                               {
      AbstractField* that = zone->New<AbstractField>(*this);
      if ((current_field_count >= kMaxTrackedFields &&
           that->info_for_node_.size() > 0) ||
          that->info_for_node_.size() >= kMaxTrackedObjects) {
        // We are tracking too many objects, which leads to bad performance.
        // Delete one to avoid the map from becoming bigger.
        that->info_for_node_.erase(that->info_for_node_.begin());
        if (V8_UNLIKELY(v8_flags.trace_turbo_bailouts)) {
          std::cout << "Bailing out in Load Elimination because of "
                       "kMaxTrackedFields or kMaxTrackedObjects\n";
        }
      }
      that->info_for_node_[object] = info;
      return that;
    }
References info_for_node_, v8::internal::Zone::New(), v8::internal::v8_flags, and V8_UNLIKELY.
Kill()
LoadElimination::AbstractField const * v8::internal::compiler::LoadElimination::AbstractField::Kill (const AliasStateInfo & alias_info, MaybeHandle< Name > name, Zone * zone) const
Definition at line 313 of file load-elimination.cc.
                      {
  for (auto info1 : this->info_for_node_) {
    if (info1.first->IsDead()) continue;
    if (alias_info.MayAlias(info1.first)) {
      AbstractField* that = zone->New<AbstractField>(zone);
      for (auto info2 : this->info_for_node_) {
        if (!alias_info.MayAlias(info2.first) ||
            !MayAlias(name, info2.second.name)) {
          that->info_for_node_.insert(info2);
        }
      }
      return that;
    }
  }
  return this;
}
References info_for_node_, v8::internal::compiler::anonymous_namespace{load-elimination.cc}::MayAlias(), v8::internal::compiler::LoadElimination::AliasStateInfo::MayAlias(), v8::internal::name, v8::internal::Zone::New(), and v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::AbstractState::KillFields().
KillConst()
LoadElimination::AbstractField const * v8::internal::compiler::LoadElimination::AbstractField::KillConst (Node * object, Zone * zone) const
Definition at line 291 of file load-elimination.cc.
                                    {
  for (auto info1 : this->info_for_node_) {
    if (info1.first->IsDead()) continue;
    // If we previously recorded information about a const store on the given
    // 'object', we might not have done it on the same node; e.g. we might now
    // identify the object by a FinishRegion node, whereas the initial const
    // store was performed on the Allocate node. We therefore remove information
    // on all nodes that must alias with 'object'.
    if (MustAlias(object, info1.first)) {
      AbstractField* that = zone->New<AbstractField>(zone);
      for (auto info2 : this->info_for_node_) {
        if (!MustAlias(object, info2.first)) {
          that->info_for_node_.insert(info2);
        }
      }
      return that;
    }
  }
  return this;
}
References info_for_node_, v8::internal::compiler::anonymous_namespace{load-elimination.cc}::MustAlias(), v8::internal::Zone::New(), and v8::internal::compiler::LoadElimination::zone().
Lookup()
LoadElimination::FieldInfo const * v8::internal::compiler::LoadElimination::AbstractField::Lookup (Node * object) const
Definition at line 256 of file load-elimination.cc.
                        {
  for (auto& pair : info_for_node_) {
    if (pair.first->IsDead()) continue;
    if (MustAlias(object, pair.first)) return &pair.second;
  }
  return nullptr;
}
References v8::internal::compiler::anonymous_namespace{load-elimination.cc}::MustAlias().
Merge()
AbstractField const* v8::internal::compiler::LoadElimination::AbstractField::Merge (AbstractField const * that, Zone * zone, int * count) const [inline]
Definition at line 164 of file load-elimination.h.
                                                 {
      if (this->Equals(that)) return this;
      AbstractField* copy = zone->New<AbstractField>(zone);
      for (auto this_it : this->info_for_node_) {
        Node* this_object = this_it.first;
        FieldInfo this_second = this_it.second;
        if (this_object->IsDead()) continue;
        auto that_it = that->info_for_node_.find(this_object);
        if (that_it != that->info_for_node_.end() &&
            that_it->second == this_second) {
          copy->info_for_node_.insert(this_it);
          (*count)++;
        }
      }
      return copy;
    }
References v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Equals(), info_for_node_, v8::internal::compiler::Node::IsDead(), and v8::internal::Zone::New().
Referenced by v8::internal::compiler::LoadElimination::AbstractState::FieldsMerge().
Print()
void v8::internal::compiler::LoadElimination::AbstractField::Print () const
Definition at line 332 of file load-elimination.cc.
                                               {
  for (auto pair : info_for_node_) {
    PrintF(" #%d:%s -> #%d:%s [repr=%s]\n", pair.first->id(),
           pair.first->op()->mnemonic(), pair.second.value->id(),
           pair.second.value->op()->mnemonic(),
           MachineReprToString(pair.second.representation));
  }
}
References v8::internal::MachineReprToString(), and v8::internal::PrintF().
Member Data Documentation
info_for_node_
ZoneMap<Node*, FieldInfo> v8::internal::compiler::LoadElimination::AbstractField::info_for_node_ [private]
Definition at line 187 of file load-elimination.h.
Referenced by Equals(), Extend(), Kill(), KillConst(), and Merge().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/load-elimination.h
/mnt/V8SourceCode/src/compiler/load-elimination.cc