v8::internal::SmiStringCache Class Reference
#include <number-string-cache.h>
Public Types
using Super = FixedArray
Public Member Functions
uint32_t capacity () const
void Clear ()
uint32_t GetUsedEntriesCount ()
void Print (const char *comment)
InternalIndex GetEntryFor (Tagged< Smi > number) const
Static Public Member Functions
static InternalIndex GetEntryFor (Isolate *isolate, Tagged< Smi > number)
static Handle< Object > Get (Isolate *isolate, InternalIndex entry, Tagged< Smi > number)
static void Set (Isolate *isolate, InternalIndex entry, Tagged< Smi > number, DirectHandle< String > string)
template<class IsolateT >
static DirectHandle< SmiStringCache > New (IsolateT *isolate, int capacity)
Static Public Attributes
static constexpr Tagged< Smi > kEmptySentinel = Smi::zero()
static constexpr int kEntryKeyIndex = 0
static constexpr int kEntryValueIndex = 1
static constexpr int kEntrySize = 2
static constexpr int kInitialSize = 128
static constexpr int kMaxCapacity = FixedArray::kMaxCapacity / kEntrySize
Additional Inherited Members
Detailed Description
Definition at line 20 of file number-string-cache.h.
Member Typedef Documentation
Super
using v8::internal::SmiStringCache::Super = FixedArray
Definition at line 22 of file number-string-cache.h.
Member Function Documentation
capacity()
uint32_t v8::internal::SmiStringCache::capacity () const [inline]
Definition at line 21 of file number-string-cache-inl.h.
                                        {
  return Super::capacity() / kEntrySize;
}
References kEntrySize.
Referenced by GetEntryFor(), GetUsedEntriesCount(), New(), and Print().
Clear()
void v8::internal::SmiStringCache::Clear () [inline]
Definition at line 108 of file number-string-cache-inl.h.
                           {
  MemsetTagged(RawFieldOfFirstElement(), kEmptySentinel, Super::capacity());
}
References kEmptySentinel, v8::internal::MemsetTagged(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::RawFieldOfFirstElement().
Get()
Handle< Object > v8::internal::SmiStringCache::Get (Isolate * isolate, InternalIndex entry, Tagged< Smi > number) [inline], [static]
Definition at line 38 of file number-string-cache-inl.h.
                                                       {
  DisallowGarbageCollection no_gc;
  Factory* factory = isolate->factory();
  Tagged<SmiStringCache> cache = *factory->smi_string_cache();
  uint32_t entry_index = entry.as_uint32() * kEntrySize;
  Tagged<Object> key = cache->get(entry_index + kEntryKeyIndex);
  const bool match = (key == number);
  if (V8_UNLIKELY(v8_flags.native_code_counters)) {
    Counters* counters = isolate->counters();
    counters->number_string_cache_smi_probes()->Increment();
    if (!match) {
      counters->number_string_cache_smi_misses()->Increment();
    }
  }
  if (match) {
    auto string = Cast<String>(cache->get(entry_index + kEntryValueIndex));
    return handle(string, isolate);
  }
  return factory->undefined_value();
}
References v8::internal::InternalIndex::as_uint32(), v8::internal::Isolate::counters(), v8::internal::Isolate::factory(), v8::internal::handle(), kEntryKeyIndex, kEntrySize, kEntryValueIndex, v8::internal::key, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::FactoryBase< Impl >::SmiToString().
GetEntryFor() [1/2]
InternalIndex v8::internal::SmiStringCache::GetEntryFor (Isolate * isolate, Tagged< Smi > number) [inline], [static]
Definition at line 32 of file number-string-cache-inl.h.
                                                              {
  return isolate->factory()->smi_string_cache()->GetEntryFor(number);
}
References v8::internal::Isolate::factory().
GetEntryFor() [2/2]
InternalIndex v8::internal::SmiStringCache::GetEntryFor (Tagged< Smi > number) const [inline]
Definition at line 25 of file number-string-cache-inl.h.
                                                                  {
  uint32_t hash = static_cast<uint32_t>(number.value());
  uint32_t mask = capacity() - 1;
  return InternalIndex{hash & mask};
}
References capacity(), and v8::internal::Tagged< Smi >::value().
Referenced by v8::internal::FactoryBase< Impl >::SmiToString().
GetUsedEntriesCount()
uint32_t v8::internal::SmiStringCache::GetUsedEntriesCount ()
Definition at line 12 of file number-string-cache.cc.
                                             {
  uint32_t count = 0;
  for (auto entry : InternalIndex::Range(capacity())) {
    uint32_t entry_index = entry.as_uint32() * kEntrySize;
    Tagged<Object> key = get(entry_index + kEntryKeyIndex);
    if (key != kEmptySentinel) {
      ++count;
    }
  }
  return count;
}
References capacity(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), kEmptySentinel, kEntryKeyIndex, kEntrySize, and v8::internal::key.
New()
template<class IsolateT >
DirectHandle< SmiStringCache > v8::internal::SmiStringCache::New (IsolateT * isolate, int capacity) [inline], [static]
Definition at line 98 of file number-string-cache-inl.h.
                                                               {
  std::optional<DisallowGarbageCollection> no_gc;
  DirectHandle<SmiStringCache> result = Cast<SmiStringCache>(
      Allocate(isolate, capacity * kEntrySize, &no_gc, AllocationType::kOld));
  result->Clear();
  return result;
}
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::Allocate(), capacity(), kEntrySize, v8::internal::kOld, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
Referenced by v8::internal::Heap::CreateInitialMutableObjects(), and Set().
Print()
void v8::internal::SmiStringCache::Print (const char * comment)
Definition at line 24 of file number-string-cache.cc.
                                              {
#ifdef OBJECT_PRINT
  StdoutStream os;
  os << comment;
  for (auto entry : InternalIndex::Range(capacity())) {
    uint32_t entry_index = entry.as_uint32() * kEntrySize;
    Tagged<Object> key = get(entry_index + kEntryKeyIndex);
    if (key != kEmptySentinel) {
      os << "\n - " << Brief(key);
    }
  }
  os << "\n";
#endif
}
References capacity(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), kEmptySentinel, kEntryKeyIndex, kEntrySize, and v8::internal::key.
Set()
void v8::internal::SmiStringCache::Set (Isolate * isolate, InternalIndex entry, Tagged< Smi > number, DirectHandle< String > string) [inline], [static]
Definition at line 64 of file number-string-cache-inl.h.
                                                                          {
  // Smi::zero() must never be put into this cache, one must read the value
  // from preallocated_number_string_table instead.
  DCHECK_NE(number, kEmptySentinel);
  DirectHandle<SmiStringCache> cache = isolate->factory()->smi_string_cache();
  DCHECK_EQ(entry, cache->GetEntryFor(number));
  uint32_t entry_index = entry.as_uint32() * kEntrySize;
  // Switch to full-size mode if the entry is already occupied.
  if (cache->capacity() == kInitialSize &&
      cache->get(entry_index + kEntryKeyIndex) != kEmptySentinel &&
      !isolate->MemorySaverModeEnabled()) {
    // Allocate full-size cache, recompute the entry and proceed with adding
    // the entry.
    uint32_t full_size =
        base::bits::RoundUpToPowerOfTwo32(v8_flags.smi_string_cache_size);
    CHECK_LT(kInitialSize, full_size);
    CHECK_LE(full_size, kMaxCapacity);
    // TODO(ishell): consider copying entries from previous table.
    cache = SmiStringCache::New(isolate, full_size);
    isolate->heap()->SetSmiStringCache(*cache);
    entry = cache->GetEntryFor(number);
    entry_index = entry.as_uint32() * kEntrySize;
  }
  DisallowGarbageCollection no_gc;
  cache->set(entry_index + kEntryKeyIndex, number);
  cache->set(entry_index + kEntryValueIndex, *string);
}
References v8::internal::InternalIndex::as_uint32(), CHECK_LE, CHECK_LT, DCHECK_EQ, DCHECK_NE, v8::internal::Isolate::factory(), v8::internal::Isolate::heap(), kEmptySentinel, kEntryKeyIndex, kEntrySize, kEntryValueIndex, kInitialSize, kMaxCapacity, v8::internal::Isolate::MemorySaverModeEnabled(), New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Heap::SetSmiStringCache(), and v8::internal::v8_flags.
Referenced by v8::internal::FactoryBase< Impl >::SmiToString().
Member Data Documentation
kEmptySentinel
constexpr Tagged<Smi> v8::internal::SmiStringCache::kEmptySentinel = Smi::zero() [static], [constexpr]
Definition at line 25 of file number-string-cache.h.
Referenced by Clear(), GetUsedEntriesCount(), Print(), Set(), and v8::internal::CodeStubAssembler::SmiToString().
kEntryKeyIndex
constexpr int v8::internal::SmiStringCache::kEntryKeyIndex = 0 [static], [constexpr]
Definition at line 27 of file number-string-cache.h.
Referenced by Get(), GetUsedEntriesCount(), Print(), Set(), and v8::internal::CodeStubAssembler::SmiToString().
kEntrySize
constexpr int v8::internal::SmiStringCache::kEntrySize = 2 [static], [constexpr]
Definition at line 29 of file number-string-cache.h.
Referenced by capacity(), Get(), GetUsedEntriesCount(), New(), Print(), Set(), and v8::internal::CodeStubAssembler::SmiToString().
kEntryValueIndex
constexpr int v8::internal::SmiStringCache::kEntryValueIndex = 1 [static], [constexpr]
Definition at line 28 of file number-string-cache.h.
Referenced by Get(), Set(), and v8::internal::CodeStubAssembler::SmiToString().
kInitialSize
constexpr int v8::internal::SmiStringCache::kInitialSize = 128 [static], [constexpr]
Definition at line 31 of file number-string-cache.h.
Referenced by v8::internal::Heap::CreateInitialMutableObjects(), Set(), and v8::internal::CodeStubAssembler::SmiToString().
kMaxCapacity
constexpr int v8::internal::SmiStringCache::kMaxCapacity = FixedArray::kMaxCapacity / kEntrySize [static], [constexpr]
Definition at line 34 of file number-string-cache.h.
Referenced by v8::internal::OrderedHashSet::ConvertToKeysArray(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::DirectCollectElementIndicesImpl(), and Set().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/number-string-cache.h
/mnt/V8SourceCode/src/objects/number-string-cache-inl.h
/mnt/V8SourceCode/src/objects/number-string-cache.cc