v8::TaskRunner Class Reference
A TaskRunner allows scheduling of tasks.
#include <v8-platform.h>
Public Member Functions
void PostTask (std::unique_ptr< Task > task, const SourceLocation &location=SourceLocation::Current())
Schedules a task to be invoked by this TaskRunner.
void PostNonNestableTask (std::unique_ptr< Task > task, const SourceLocation &location=SourceLocation::Current())
Schedules a task to be invoked by this TaskRunner.
void PostDelayedTask (std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation &location=SourceLocation::Current())
Schedules a task to be invoked by this TaskRunner.
void PostNonNestableDelayedTask (std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation &location=SourceLocation::Current())
Schedules a task to be invoked by this TaskRunner.
void PostIdleTask (std::unique_ptr< IdleTask > task, const SourceLocation &location=SourceLocation::Current())
Schedules an idle task to be invoked by this TaskRunner.
virtual bool IdleTasksEnabled ()=0
Returns true if idle tasks are enabled for this TaskRunner.
virtual bool NonNestableTasksEnabled () const
Returns true if non-nestable tasks are enabled for this TaskRunner.
virtual bool NonNestableDelayedTasksEnabled () const
Returns true if non-nestable delayed tasks are enabled for this TaskRunner.
TaskRunner ()=default
virtual ~TaskRunner ()=default
TaskRunner (const TaskRunner &)=delete
TaskRunner & operator= (const TaskRunner &)=delete
Protected Member Functions
virtual void PostTaskImpl (std::unique_ptr< Task > task, const SourceLocation &location)
Implementation of above methods with an additional location argument.
virtual void PostNonNestableTaskImpl (std::unique_ptr< Task > task, const SourceLocation &location)
virtual void PostDelayedTaskImpl (std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation &location)
virtual void PostNonNestableDelayedTaskImpl (std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation &location)
virtual void PostIdleTaskImpl (std::unique_ptr< IdleTask > task, const SourceLocation &location)
Detailed Description
A TaskRunner allows scheduling of tasks.
The TaskRunner may still be used to post tasks after the isolate gets destructed, but these tasks may not get executed anymore. All tasks posted to a given TaskRunner will be invoked in sequence. Tasks can be posted from any thread.
Definition at line 74 of file v8-platform.h.
Constructor & Destructor Documentation
TaskRunner() [1/2]
v8::TaskRunner::TaskRunner () [default]
 TaskRunner()
virtual v8::TaskRunner::~TaskRunner () [virtual], [default]
TaskRunner() [2/2]
v8::TaskRunner::TaskRunner (const TaskRunner &) [delete]
Member Function Documentation
IdleTasksEnabled()
virtual bool v8::TaskRunner::IdleTasksEnabled () [pure virtual]
Returns true if idle tasks are enabled for this TaskRunner.
Implemented in v8::DelayedTasksPlatform::DelayedTaskRunner.
NonNestableDelayedTasksEnabled()
virtual bool v8::TaskRunner::NonNestableDelayedTasksEnabled () const [inline], [virtual]
Returns true if non-nestable delayed tasks are enabled for this TaskRunner.
Definition at line 176 of file v8-platform.h.
{ return false; }
NonNestableTasksEnabled()
virtual bool v8::TaskRunner::NonNestableTasksEnabled () const [inline], [virtual]
Returns true if non-nestable tasks are enabled for this TaskRunner.
Reimplemented in v8::DelayedTasksPlatform::DelayedTaskRunner.
Definition at line 171 of file v8-platform.h.
{ return false; }
Referenced by cppgc::internal::MarkerBase::IncrementalMarkingTask::Post(), and v8::internal::IncrementalMarkingJob::ScheduleTask().
operator=()
TaskRunner& v8::TaskRunner::operator= (const TaskRunner &) [delete]
PostDelayedTask()
void v8::TaskRunner::PostDelayedTask (std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation & location = SourceLocation::Current()) [inline]
Schedules a task to be invoked by this TaskRunner.
The task is scheduled after the given number of seconds |delay_in_seconds|. The TaskRunner implementation takes ownership of |task|.
Embedders should override PostDelayedTaskImpl instead of this.
Definition at line 117 of file v8-platform.h.
                                                                {
    PostDelayedTaskImpl(std::move(task), delay_in_seconds, location);
  }
References PostDelayedTaskImpl().
PostDelayedTaskImpl()
virtual void v8::TaskRunner::PostDelayedTaskImpl (std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation & location) [inline], [protected], [virtual]
Reimplemented in v8::DelayedTasksPlatform::DelayedTaskRunner.
Definition at line 192 of file v8-platform.h.
                                                                   {}
Referenced by PostDelayedTask().
PostIdleTask()
void v8::TaskRunner::PostIdleTask (std::unique_ptr< IdleTask > task, const SourceLocation & location = SourceLocation::Current()) [inline]
Schedules an idle task to be invoked by this TaskRunner.
The task is scheduled when the embedder is idle. Requires that |TaskRunner::IdleTasksEnabled()| is true. Idle tasks may be reordered relative to other task types and may be starved for an arbitrarily long time if no idle time is available. The TaskRunner implementation takes ownership of |task|.
Embedders should override PostIdleTaskImpl instead of this.
Definition at line 157 of file v8-platform.h.
                                                                {
    PostIdleTaskImpl(std::move(task), location);
  }
References PostIdleTaskImpl().
PostIdleTaskImpl()
virtual void v8::TaskRunner::PostIdleTaskImpl (std::unique_ptr< IdleTask > task, const SourceLocation & location) [inline], [protected], [virtual]
Reimplemented in v8::DelayedTasksPlatform::DelayedTaskRunner.
Definition at line 198 of file v8-platform.h.
                                                                {}
Referenced by PostIdleTask().
PostNonNestableDelayedTask()
void v8::TaskRunner::PostNonNestableDelayedTask (std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation & location = SourceLocation::Current()) [inline]
Schedules a task to be invoked by this TaskRunner.
The task is scheduled after the given number of seconds |delay_in_seconds|. The TaskRunner implementation takes ownership of |task|. The |task| cannot be nested within other task executions.
Tasks which shouldn't be interleaved with JS execution must be posted with |PostNonNestableTask| or |PostNonNestableDelayedTask|. This is because the embedder may process tasks in a callback which is called during JS execution.
In particular, tasks which execute JS must be non-nestable, since JS execution is not allowed to nest.
Requires that |TaskRunner::NonNestableDelayedTasksEnabled()| is true.
Embedders should override PostNonNestableDelayedTaskImpl instead of this.
Definition at line 141 of file v8-platform.h.
                                                                {
    PostNonNestableDelayedTaskImpl(std::move(task), delay_in_seconds, location);
  }
References PostNonNestableDelayedTaskImpl().
Referenced by v8::internal::JSAtomicsMutex::LockAsyncSlowPath(), and v8::internal::JSAtomicsCondition::WaitAsync().
PostNonNestableDelayedTaskImpl()
virtual void v8::TaskRunner::PostNonNestableDelayedTaskImpl (std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation & location) [inline], [protected], [virtual]
Definition at line 195 of file v8-platform.h.
                                                                              {}
Referenced by PostNonNestableDelayedTask().
PostNonNestableTask()
void v8::TaskRunner::PostNonNestableTask (std::unique_ptr< Task > task, const SourceLocation & location = SourceLocation::Current()) [inline]
Schedules a task to be invoked by this TaskRunner.
The TaskRunner implementation takes ownership of |task|. The |task| cannot be nested within other task executions.
Tasks which shouldn't be interleaved with JS execution must be posted with |PostNonNestableTask| or |PostNonNestableDelayedTask|. This is because the embedder may process tasks in a callback which is called during JS execution.
In particular, tasks which execute JS must be non-nestable, since JS execution is not allowed to nest.
Requires that |TaskRunner::NonNestableTasksEnabled()| is true.
Embedders should override PostNonNestableTaskImpl instead of this.
Definition at line 104 of file v8-platform.h.
                                                                {
    PostNonNestableTaskImpl(std::move(task), location);
  }
References PostNonNestableTaskImpl().
Referenced by cppgc::internal::MarkerBase::IncrementalMarkingTask::Post(), cppgc::internal::GCInvoker::GCInvokerImpl::GCTask::Post(), and v8::internal::IncrementalMarkingJob::ScheduleTask().
PostNonNestableTaskImpl()
virtual void v8::TaskRunner::PostNonNestableTaskImpl (std::unique_ptr< Task > task, const SourceLocation & location) [inline], [protected], [virtual]
Reimplemented in v8::DelayedTasksPlatform::DelayedTaskRunner.
Definition at line 190 of file v8-platform.h.
                                                                       {}
Referenced by PostNonNestableTask().
PostTask()
void v8::TaskRunner::PostTask (std::unique_ptr< Task > task, const SourceLocation & location = SourceLocation::Current()) [inline]
Schedules a task to be invoked by this TaskRunner.
The TaskRunner implementation takes ownership of |task|.
Embedders should override PostTaskImpl instead of this.
Definition at line 82 of file v8-platform.h.
                                                                          {
    PostTaskImpl(std::move(task), location);
  }
References PostTaskImpl().
Referenced by cppgc::internal::MarkerBase::IncrementalMarkingTask::Post(), and v8::internal::IncrementalMarkingJob::ScheduleTask().
PostTaskImpl()
virtual void v8::TaskRunner::PostTaskImpl (std::unique_ptr< Task > task, const SourceLocation & location) [inline], [protected], [virtual]
Implementation of above methods with an additional location argument.
Reimplemented in v8::DelayedTasksPlatform::DelayedTaskRunner.
Definition at line 188 of file v8-platform.h.
                                                            {}
Referenced by PostTask().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-platform.h