v8::internal::torque::DeclarationVisitor Class Reference
#include <declaration-visitor.h>
Static Public Member Functions
static void Visit (Ast *ast)
static void Visit (Declaration *decl)
static void Visit (NamespaceDeclaration *decl)
static void Visit (TypeDeclaration *decl)
static void Visit (StructDeclaration *decl)
static Builtin * CreateBuiltin (BuiltinDeclaration *decl, std::string external_name, std::string readable_name, Signature signature, std::optional< std::string > use_counter_name, std::optional< Statement * > body)
static void Visit (ExternalBuiltinDeclaration *decl)
static void Visit (ExternalRuntimeDeclaration *decl)
static void Visit (ExternalMacroDeclaration *decl)
static void Visit (TorqueBuiltinDeclaration *decl)
static void Visit (TorqueMacroDeclaration *decl)
static void Visit (IntrinsicDeclaration *decl)
static void Visit (ConstDeclaration *decl)
static void Visit (GenericCallableDeclaration *decl)
static void Visit (GenericTypeDeclaration *decl)
static void Visit (SpecializationDeclaration *decl)
static void Visit (ExternConstDeclaration *decl)
static void Visit (CppIncludeDeclaration *decl)
static Signature MakeSpecializedSignature (const SpecializationKey< GenericCallable > &key)
static Callable * SpecializeImplicit (const SpecializationKey< GenericCallable > &key)
static Callable * Specialize (const SpecializationKey< GenericCallable > &key, CallableDeclaration *declaration, std::optional< const SpecializationDeclaration * > explicit_specialization, std::optional< Statement * > body, SourcePosition position)
Static Private Member Functions
static void DeclareSpecializedTypes (const SpecializationKey< GenericCallable > &key)
Detailed Description
Definition at line 64 of file declaration-visitor.h.
Member Function Documentation
CreateBuiltin()
Builtin * v8::internal::torque::DeclarationVisitor::CreateBuiltin (BuiltinDeclaration * decl, std::string external_name, std::string readable_name, Signature signature, std::optional< std::string > use_counter_name, std::optional< Statement * > body) [static]
Definition at line 61 of file declaration-visitor.cc.
                                  {
  const bool javascript = decl->javascript_linkage;
  const bool varargs = decl->parameters.has_varargs;
  Builtin::Kind kind = !javascript ? Builtin::kStub
                                   : varargs ? Builtin::kVarArgsJavaScript
                                             : Builtin::kFixedArgsJavaScript;
  bool has_custom_interface_descriptor = false;
  if (decl->kind == AstNode::Kind::kTorqueBuiltinDeclaration) {
    has_custom_interface_descriptor =
        static_cast<TorqueBuiltinDeclaration*>(decl)
            ->has_custom_interface_descriptor;
  }
  if (varargs && !javascript) {
    Error("Rest parameters require ", decl->name,
          " to be a JavaScript builtin");
  }
  if (javascript) {
    if (!signature.return_type->IsSubtypeOf(TypeOracle::GetJSAnyType())) {
      Error("Return type of JavaScript-linkage builtins has to be JSAny.")
          .Position(decl->return_type->pos);
    }
    // Validate the parameter types. In general, for JS builtins the parameters
    // must all be tagged values (JSAny). However, we currently allow declaring
    // "extern javascript" builtins with any parameter types. The reason is
    // that those are typically used for tailcalls, in which case we typically
    // need to supply the implicit parameters of the JS calling convention
    // (target, receiver, argc, etc.). It would probablu be nicer if we could
    // instead declare these parameters as js-implicit (like we do for
    // torque-defined javascript builtins) and then allow explicitly supplying
    // the implicit arguments during tailscalls. It's unclear though if that's
    // worth the effort. In particular, calls and tailcalls to javascript
    // builtins will emit CSA::CallJSBuiltin and CSA::TailCallJSBuiltin calls
    // which will validate the parameter types at C++ compile time.
    if (decl->kind != AstNode::Kind::kExternalBuiltinDeclaration) {
      for (size_t i = signature.implicit_count;
           i < signature.parameter_types.types.size(); ++i) {
        const Type* parameter_type = signature.parameter_types.types[i];
        if (!TypeOracle::GetJSAnyType()->IsSubtypeOf(parameter_type)) {
          Error(
              "Parameters of JavaScript-linkage builtins have to be a "
              "supertype "
              "of JSAny.")
              .Position(decl->parameters.types[i]->pos);
        }
      }
    }
  }
  for (size_t i = 0; i < signature.types().size(); ++i) {
    const Type* parameter_type = signature.types()[i];
    if (parameter_type->StructSupertype()) {
      Error("Builtin do not support structs as arguments, but argument ",
            signature.parameter_names[i], " has type ", *signature.types()[i],
            ".");
    }
    if (parameter_type->IsFloat32() || parameter_type->IsFloat64()) {
      if (!has_custom_interface_descriptor) {
        Error("Builtin ", external_name,
              " needs a custom interface descriptor, "
              "because it uses type ",
              *parameter_type, " for argument ", signature.parameter_names[i],
              ". One reason being "
              "that the default descriptor defines xmm0 to be the first "
              "floating point argument register, which is current used as "
              "scratch on ia32 and cannot be allocated.");
      }
    }
  }
  if (signature.return_type->StructSupertype() && javascript) {
    Error(
        "Builtins with JS linkage cannot return structs, but the return type "
        "is ",
        *signature.return_type, ".");
  }
  if (signature.return_type == TypeOracle::GetVoidType()) {
    Error("Builtins cannot have return type void.");
  }
  Builtin::Flags flags = Builtin::Flag::kNone;
  if (has_custom_interface_descriptor)
    flags |= Builtin::Flag::kCustomInterfaceDescriptor;
  Builtin* builtin = Declarations::CreateBuiltin(
      std::move(external_name), std::move(readable_name), kind, flags,
      std::move(signature), std::move(use_counter_name), body);
  // TODO(v8:12261): Recheck this.
  // builtin->SetIdentifierPosition(decl->name->pos);
  return builtin;
}
References v8::internal::torque::Declarations::CreateBuiltin(), v8::internal::torque::Error(), v8::internal::flags, v8::internal::torque::TypeOracle::GetJSAnyType(), v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::torque::ParameterList::has_varargs, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::Signature::implicit_count, v8::internal::torque::Type::IsFloat32(), v8::internal::torque::Type::IsFloat64(), v8::internal::torque::Type::IsSubtypeOf(), v8::internal::wasm::IsSubtypeOf(), v8::internal::torque::BuiltinDeclaration::javascript_linkage, v8::internal::torque::Builtin::kCustomInterfaceDescriptor, v8::internal::torque::Builtin::kFixedArgsJavaScript, v8::internal::torque::AstNode::kind, v8::internal::torque::Builtin::kNone, v8::internal::torque::Builtin::kStub, v8::internal::torque::Builtin::kVarArgsJavaScript, v8::internal::torque::CallableDeclaration::name, v8::internal::torque::Signature::parameter_names, v8::internal::torque::Signature::parameter_types, v8::internal::torque::CallableDeclaration::parameters, v8::internal::torque::AstNode::pos, v8::internal::torque::MessageBuilder::Position(), v8::internal::torque::CallableDeclaration::return_type, v8::internal::torque::Signature::return_type, size(), v8::internal::torque::Type::StructSupertype(), v8::internal::torque::ParameterList::types, v8::internal::torque::ParameterTypes::types, and v8::internal::torque::Signature::types().
Referenced by Specialize(), and Visit().
DeclareSpecializedTypes()
void v8::internal::torque::DeclarationVisitor::DeclareSpecializedTypes (const SpecializationKey< GenericCallable > & key) [static], [private]
Definition at line 343 of file declaration-visitor.cc.
                                                   {
  size_t i = 0;
  const std::size_t generic_parameter_count =
      key.generic->generic_parameters().size();
  if (generic_parameter_count != key.specialized_types.size()) {
    std::stringstream stream;
    stream << "Wrong generic argument count for specialization of \""
           << key.generic->name() << "\", expected: " << generic_parameter_count
           << ", actual: " << key.specialized_types.size();
    ReportError(stream.str());
  }
  for (auto type : key.specialized_types) {
    Identifier* generic_type_name = key.generic->generic_parameters()[i++].name;
    TypeAlias* alias = Declarations::DeclareType(generic_type_name, type);
    alias->SetIsUserDefined(false);
  }
}
References v8::internal::torque::Declarations::DeclareType(), v8::internal::key, v8::internal::torque::ReportError(), v8::internal::torque::Declarable::SetIsUserDefined(), v8::internal::size_t, and v8::internal::tracing::type.
Referenced by MakeSpecializedSignature(), and SpecializeImplicit().
MakeSpecializedSignature()
Signature v8::internal::torque::DeclarationVisitor::MakeSpecializedSignature (const SpecializationKey< GenericCallable > & key) [static]
Definition at line 363 of file declaration-visitor.cc.
                                                   {
  CurrentScope::Scope generic_scope(key.generic->ParentScope());
  // Create a temporary fake-namespace just to temporarily declare the
  // specialization aliases for the generic types to create a signature.
  Namespace tmp_namespace("_tmp");
  CurrentScope::Scope tmp_namespace_scope(&tmp_namespace);
  DeclareSpecializedTypes(key);
  return TypeVisitor::MakeSignature(key.generic->declaration());
}
References DeclareSpecializedTypes(), v8::internal::key, and v8::internal::torque::TypeVisitor::MakeSignature().
Referenced by v8::internal::torque::ImplementationVisitor::LookupCallable(), Specialize(), and Visit().
Specialize()
Callable * v8::internal::torque::DeclarationVisitor::Specialize (const SpecializationKey< GenericCallable > & key, CallableDeclaration * declaration, std::optional< const SpecializationDeclaration * > explicit_specialization, std::optional< Statement * > body, SourcePosition position) [static]
Definition at line 396 of file declaration-visitor.cc.
                                                           {
  CurrentSourcePosition::Scope pos_scope(position);
  size_t generic_parameter_count = key.generic->generic_parameters().size();
  if (generic_parameter_count != key.specialized_types.size()) {
    std::stringstream stream;
    stream << "number of template parameters ("
           << std::to_string(key.specialized_types.size())
           << ") to intantiation of generic " << declaration->name
           << " doesnt match the generic's declaration ("
           << std::to_string(generic_parameter_count) << ")";
    ReportError(stream.str());
  }
  if (key.generic->GetSpecialization(key.specialized_types)) {
    ReportError("cannot redeclare specialization of ", key.generic->name(),
                " with types <", key.specialized_types, ">");
  }
  Signature type_signature =
      explicit_specialization
          ? TypeVisitor::MakeSignature(*explicit_specialization)
          : MakeSpecializedSignature(key);
  std::string generated_name = Declarations::GetGeneratedCallableName(
      declaration->name->value, key.specialized_types);
  std::stringstream readable_name;
  readable_name << declaration->name->value << "<";
  bool first = true;
  for (const Type* t : key.specialized_types) {
    if (!first) readable_name << ", ";
    readable_name << *t;
    first = false;
  }
  readable_name << ">";
  Callable* callable;
  if (MacroDeclaration::DynamicCast(declaration) != nullptr) {
    callable =
        Declarations::CreateTorqueMacro(generated_name, readable_name.str(),
                                        false, type_signature, *body, true);
  } else if (IntrinsicDeclaration::DynamicCast(declaration) != nullptr) {
    callable =
        Declarations::CreateIntrinsic(declaration->name->value, type_signature);
  } else {
    BuiltinDeclaration* builtin = BuiltinDeclaration::cast(declaration);
    std::optional<std::string> use_counter_name;
    if (TorqueBuiltinDeclaration* torque_builtin =
            TorqueBuiltinDeclaration::DynamicCast(builtin)) {
      use_counter_name = torque_builtin->use_counter_name;
    } else {
      use_counter_name = std::nullopt;
    }
    callable = CreateBuiltin(
        builtin, GlobalContext::MakeUniqueName(generated_name),
        readable_name.str(), type_signature, use_counter_name, *body);
  }
  key.generic->AddSpecialization(key.specialized_types, callable);
  return callable;
}
References CreateBuiltin(), v8::internal::torque::Declarations::CreateIntrinsic(), v8::internal::torque::Declarations::CreateTorqueMacro(), v8::internal::torque::Declarations::GetGeneratedCallableName(), v8::internal::key, v8::internal::torque::TypeVisitor::MakeSignature(), MakeSpecializedSignature(), v8::internal::torque::GlobalContext::MakeUniqueName(), v8::internal::torque::CallableDeclaration::name, v8::internal::torque::ReportError(), v8::internal::string, and v8::internal::torque::Identifier::value.
Referenced by SpecializeImplicit(), and Visit().
SpecializeImplicit()
Callable * v8::internal::torque::DeclarationVisitor::SpecializeImplicit (const SpecializationKey< GenericCallable > & key) [static]
Definition at line 374 of file declaration-visitor.cc.
                                                   {
  std::optional<Statement*> body = key.generic->CallableBody();
  if (!body && IntrinsicDeclaration::DynamicCast(key.generic->declaration()) ==
                   nullptr) {
    ReportError("missing specialization of ", key.generic->name(),
                " with types <", key.specialized_types, "> declared at ",
                key.generic->Position());
  }
  SpecializationRequester requester{CurrentSourcePosition::Get(),
                                    CurrentScope::Get(), ""};
  CurrentScope::Scope generic_scope(key.generic->ParentScope());
  Callable* result = Specialize(key, key.generic->declaration(), std::nullopt,
                                body, CurrentSourcePosition::Get());
  result->SetIsUserDefined(false);
  requester.name = result->ReadableName();
  result->SetSpecializationRequester(requester);
  CurrentScope::Scope callable_scope(result);
  DeclareSpecializedTypes(key);
  return result;
}
References DeclareSpecializedTypes(), v8::internal::compiler::turboshaft::Get(), v8::internal::key, v8::internal::torque::ReportError(), v8::base::internal::result, and Specialize().
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GetOrCreateSpecialization().
Visit() [1/17]
static void v8::internal::torque::DeclarationVisitor::Visit (Ast * ast) [inline], [static]
Definition at line 66 of file declaration-visitor.h.
                              {
    CurrentScope::Scope current_namespace(GlobalContext::GetDefaultNamespace());
    for (Declaration* child : ast->declarations()) Visit(child);
  }
References v8::internal::torque::Ast::declarations(), and v8::internal::torque::GlobalContext::GetDefaultNamespace().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst(), and Visit().
Visit() [2/17]
void v8::internal::torque::DeclarationVisitor::Visit (ConstDeclaration * decl) [static]
Definition at line 251 of file declaration-visitor.cc.
                                                     {
  auto constant = Declarations::DeclareNamespaceConstant(
      decl->name, TypeVisitor::ComputeType(decl->type), decl->expression);
  if (GlobalContext::collect_kythe_data()) {
    KytheData::AddConstantDefinition(constant);
  }
}
References v8::internal::torque::KytheData::AddConstantDefinition(), v8::internal::torque::GlobalContext::collect_kythe_data(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::Declarations::DeclareNamespaceConstant(), v8::internal::torque::ConstDeclaration::expression, v8::internal::torque::ConstDeclaration::name, and v8::internal::torque::ConstDeclaration::type.
Visit() [3/17]
void v8::internal::torque::DeclarationVisitor::Visit (CppIncludeDeclaration * decl) [static]
Definition at line 339 of file declaration-visitor.cc.
                                                          {
  GlobalContext::AddCppInclude(decl->include_path);
}
References v8::internal::torque::GlobalContext::AddCppInclude(), and v8::internal::torque::CppIncludeDeclaration::include_path.
Visit() [4/17]
void v8::internal::torque::DeclarationVisitor::Visit (Declaration * decl) [static]
Definition at line 48 of file declaration-visitor.cc.
                                                {
  CurrentSourcePosition::Scope scope(decl->pos);
  switch (decl->kind) {
#define ENUM_ITEM(name) \
  case AstNode::Kind::k##name: \
    return Visit(name::cast(decl));
    AST_DECLARATION_NODE_KIND_LIST(ENUM_ITEM)
#undef ENUM_ITEM
    default:
      UNIMPLEMENTED();
  }
}
References AST_DECLARATION_NODE_KIND_LIST, ENUM_ITEM, v8::internal::torque::AstNode::kind, v8::internal::torque::AstNode::pos, and v8::internal::UNIMPLEMENTED().
Visit() [5/17]
void v8::internal::torque::DeclarationVisitor::Visit (ExternalBuiltinDeclaration * decl) [static]
Definition at line 158 of file declaration-visitor.cc.
                                                               {
  Builtin* builtin = CreateBuiltin(decl, decl->name->value, decl->name->value,
                                   TypeVisitor::MakeSignature(decl),
                                   std::nullopt, std::nullopt);
  builtin->SetIdentifierPosition(decl->name->pos);
  Declarations::Declare(decl->name->value, builtin);
}
References CreateBuiltin(), v8::internal::torque::Declarations::Declare(), v8::internal::torque::TypeVisitor::MakeSignature(), v8::internal::torque::CallableDeclaration::name, v8::internal::torque::AstNode::pos, v8::internal::torque::Declarable::SetIdentifierPosition(), and v8::internal::torque::Identifier::value.
Visit() [6/17]
void v8::internal::torque::DeclarationVisitor::Visit (ExternalMacroDeclaration * decl) [static]
Definition at line 206 of file declaration-visitor.cc.
                                                             {
  Macro* macro = Declarations::DeclareMacro(
      decl->name->value, true, decl->external_assembler_name,
      TypeVisitor::MakeSignature(decl), std::nullopt, decl->op);
  macro->SetIdentifierPosition(decl->name->pos);
  macro->SetPosition(decl->pos);
  if (GlobalContext::collect_kythe_data()) {
    KytheData::AddFunctionDefinition(macro);
  }
}
References v8::internal::torque::KytheData::AddFunctionDefinition(), v8::internal::torque::GlobalContext::collect_kythe_data(), v8::internal::torque::Declarations::DeclareMacro(), v8::internal::torque::ExternalMacroDeclaration::external_assembler_name, v8::internal::torque::TypeVisitor::MakeSignature(), v8::internal::torque::CallableDeclaration::name, v8::internal::torque::MacroDeclaration::op, v8::internal::torque::AstNode::pos, v8::internal::torque::Declarable::SetIdentifierPosition(), v8::internal::torque::Declarable::SetPosition(), and v8::internal::torque::Identifier::value.
Visit() [7/17]
void v8::internal::torque::DeclarationVisitor::Visit (ExternalRuntimeDeclaration * decl) [static]
Definition at line 166 of file declaration-visitor.cc.
                                                               {
  Signature signature = TypeVisitor::MakeSignature(decl);
  if (signature.parameter_types.types.empty()) {
    ReportError(
        "Missing parameters for runtime function, at least the context "
        "parameter is required.");
  }
  if (!(signature.parameter_types.types[0] == TypeOracle::GetContextType() ||
        signature.parameter_types.types[0] == TypeOracle::GetNoContextType())) {
    ReportError(
        "first parameter to runtime functions has to be the context and have "
        "type Context or NoContext, but found type ",
        *signature.parameter_types.types[0]);
  }
  if (!(signature.return_type->IsSubtypeOf(TypeOracle::GetStrongTaggedType()) ||
        signature.return_type == TypeOracle::GetVoidType() ||
        signature.return_type == TypeOracle::GetNeverType())) {
    ReportError(
        "runtime functions can only return strong tagged values, but "
        "found type ",
        *signature.return_type);
  }
  for (const Type* parameter_type : signature.parameter_types.types) {
    if (!parameter_type->IsSubtypeOf(TypeOracle::GetStrongTaggedType())) {
      ReportError(
          "runtime functions can only take strong tagged parameters, but "
          "found type ",
          *parameter_type);
    }
  }
  RuntimeFunction* function =
      Declarations::DeclareRuntimeFunction(decl->name->value, signature);
  function->SetIdentifierPosition(decl->name->pos);
  function->SetPosition(decl->pos);
  if (GlobalContext::collect_kythe_data()) {
    KytheData::AddFunctionDefinition(function);
  }
}
References v8::internal::torque::KytheData::AddFunctionDefinition(), v8::internal::torque::GlobalContext::collect_kythe_data(), v8::internal::torque::Declarations::DeclareRuntimeFunction(), v8::internal::torque::TypeOracle::GetContextType(), v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::TypeOracle::GetNoContextType(), v8::internal::torque::TypeOracle::GetStrongTaggedType(), v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::torque::Type::IsSubtypeOf(), v8::internal::torque::TypeVisitor::MakeSignature(), v8::internal::torque::CallableDeclaration::name, v8::internal::torque::Signature::parameter_types, v8::internal::torque::AstNode::pos, v8::internal::torque::ReportError(), v8::internal::torque::Signature::return_type, v8::internal::torque::ParameterTypes::types, and v8::internal::torque::Identifier::value.
Visit() [8/17]
void v8::internal::torque::DeclarationVisitor::Visit (ExternConstDeclaration * decl) [static]
Definition at line 323 of file declaration-visitor.cc.
                                                           {
  const Type* type = TypeVisitor::ComputeType(decl->type);
  if (!type->IsConstexpr()) {
    std::stringstream stream;
    stream << "extern constants must have constexpr type, but found: \""
           << *type << "\"\n";
    ReportError(stream.str());
  }
  ExternConstant* constant =
      Declarations::DeclareExternConstant(decl->name, type, decl->literal);
  if (GlobalContext::collect_kythe_data()) {
    KytheData::AddConstantDefinition(constant);
  }
}
References v8::internal::torque::KytheData::AddConstantDefinition(), v8::internal::torque::GlobalContext::collect_kythe_data(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::Declarations::DeclareExternConstant(), v8::internal::torque::ExternConstDeclaration::literal, v8::internal::torque::ExternConstDeclaration::name, v8::internal::torque::ReportError(), v8::internal::torque::ExternConstDeclaration::type, and v8::internal::tracing::type.
Visit() [9/17]
static void v8::internal::torque::DeclarationVisitor::Visit (GenericCallableDeclaration * decl) [inline], [static]
Definition at line 99 of file declaration-visitor.h.
                                                      {
    // The PredeclarationVisitor already handled this case.
  }
Visit() [10/17]
static void v8::internal::torque::DeclarationVisitor::Visit (GenericTypeDeclaration * decl) [inline], [static]
Definition at line 102 of file declaration-visitor.h.
                                                  {
    // The PredeclarationVisitor already handled this case.
  }
Visit() [11/17]
void v8::internal::torque::DeclarationVisitor::Visit (IntrinsicDeclaration * decl) [static]
Definition at line 246 of file declaration-visitor.cc.
                                                         {
  Declarations::DeclareIntrinsic(decl->name->value,
                                 TypeVisitor::MakeSignature(decl));
}
References v8::internal::torque::Declarations::DeclareIntrinsic(), v8::internal::torque::TypeVisitor::MakeSignature(), v8::internal::torque::CallableDeclaration::name, and v8::internal::torque::Identifier::value.
Visit() [12/17]
static void v8::internal::torque::DeclarationVisitor::Visit (NamespaceDeclaration * decl) [inline], [static]
Definition at line 71 of file declaration-visitor.h.
                                                {
    CurrentScope::Scope current_scope(GetOrCreateNamespace(decl->name));
    for (Declaration* child : decl->declarations) Visit(child);
  }
References v8::internal::torque::NamespaceDeclaration::declarations, v8::internal::torque::GetOrCreateNamespace(), v8::internal::torque::NamespaceDeclaration::name, and Visit().
Visit() [13/17]
void v8::internal::torque::DeclarationVisitor::Visit (SpecializationDeclaration * decl) [static]
Definition at line 259 of file declaration-visitor.cc.
                                                              {
  std::vector<GenericCallable*> generic_list =
      Declarations::LookupGeneric(decl->name->value);
  // Find the matching generic specialization based on the concrete parameter
  // list.
  GenericCallable* matching_generic = nullptr;
  Signature signature_with_types = TypeVisitor::MakeSignature(decl);
  for (GenericCallable* generic : generic_list) {
    // This argument inference is just to trigger constraint checking on the
    // generic arguments.
    TypeArgumentInference inference = generic->InferSpecializationTypes(
        TypeVisitor::ComputeTypeVector(decl->generic_parameters), {});
    if (inference.HasFailed()) {
      continue;
    }
    Signature generic_signature_with_types =
        MakeSpecializedSignature(SpecializationKey<GenericCallable>{
            generic, TypeVisitor::ComputeTypeVector(decl->generic_parameters)});
    if (signature_with_types.HasSameTypesAs(generic_signature_with_types,
                                            ParameterMode::kIgnoreImplicit)) {
      if (matching_generic != nullptr) {
        std::stringstream stream;
        stream << "specialization of " << decl->name
               << " is ambigous, it matches more than one generic declaration ("
               << *matching_generic << " and " << *generic << ")";
        ReportError(stream.str());
      }
      matching_generic = generic;
    }
  }
  if (matching_generic == nullptr) {
    std::stringstream stream;
    if (generic_list.empty()) {
      stream << "no generic defined with the name " << decl->name;
      ReportError(stream.str());
    }
    stream << "specialization of " << decl->name
           << " doesn't match any generic declaration\n";
    stream << "specialization signature:";
    stream << "\n " << signature_with_types;
    stream << "\ncandidates are:";
    for (GenericCallable* generic : generic_list) {
      stream << "\n "
             << MakeSpecializedSignature(SpecializationKey<GenericCallable>{
                    generic,
                    TypeVisitor::ComputeTypeVector(decl->generic_parameters)});
    }
    ReportError(stream.str());
  }
  if (GlobalContext::collect_language_server_data()) {
    LanguageServerData::AddDefinition(decl->name->pos,
                                      matching_generic->IdentifierPosition());
  }
  CallableDeclaration* generic_declaration = matching_generic->declaration();
  Specialize(SpecializationKey<GenericCallable>{matching_generic,
                                                TypeVisitor::ComputeTypeVector(
                                                    decl->generic_parameters)},
             generic_declaration, decl, decl->body, decl->pos);
}
References v8::internal::torque::LanguageServerData::AddDefinition(), v8::internal::torque::SpecializationDeclaration::body, v8::internal::torque::GlobalContext::collect_language_server_data(), v8::internal::torque::TypeVisitor::ComputeTypeVector(), v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::declaration(), v8::internal::torque::SpecializationDeclaration::generic_parameters, v8::internal::torque::TypeArgumentInference::HasFailed(), v8::internal::torque::Signature::HasSameTypesAs(), v8::internal::torque::Declarable::IdentifierPosition(), v8::internal::torque::kIgnoreImplicit, v8::internal::torque::Declarations::LookupGeneric(), v8::internal::torque::TypeVisitor::MakeSignature(), MakeSpecializedSignature(), v8::internal::torque::CallableDeclaration::name, v8::internal::torque::AstNode::pos, v8::internal::torque::ReportError(), Specialize(), and v8::internal::torque::Identifier::value.
Visit() [14/17]
static void v8::internal::torque::DeclarationVisitor::Visit (StructDeclaration * decl) [inline], [static]
Definition at line 81 of file declaration-visitor.h.
                                             {
    Declarations::LookupType(decl->name);
  }
References v8::internal::torque::Declarations::LookupType(), and v8::internal::torque::TypeDeclaration::name.
Visit() [15/17]
void v8::internal::torque::DeclarationVisitor::Visit (TorqueBuiltinDeclaration * decl) [static]
Definition at line 217 of file declaration-visitor.cc.
                                                             {
  Signature signature = TypeVisitor::MakeSignature(decl);
  if (decl->use_counter_name &&
      (signature.types().empty() ||
       (signature.types()[0] != TypeOracle::GetNativeContextType() &&
        signature.types()[0] != TypeOracle::GetContextType()))) {
    ReportError(
        "@incrementUseCounter requires the builtin's first parameter to be of "
        "type Context or NativeContext, but found type ",
        *signature.types()[0]);
  }
  auto builtin = CreateBuiltin(decl, decl->name->value, decl->name->value,
                               signature, decl->use_counter_name, decl->body);
  builtin->SetIdentifierPosition(decl->name->pos);
  builtin->SetPosition(decl->pos);
  Declarations::Declare(decl->name->value, builtin);
}
References v8::internal::torque::TorqueBuiltinDeclaration::body, CreateBuiltin(), v8::internal::torque::Declarations::Declare(), v8::internal::torque::TypeOracle::GetContextType(), v8::internal::torque::TypeOracle::GetNativeContextType(), v8::internal::torque::TypeVisitor::MakeSignature(), v8::internal::torque::CallableDeclaration::name, v8::internal::torque::AstNode::pos, v8::internal::torque::ReportError(), v8::internal::torque::Signature::types(), v8::internal::torque::TorqueBuiltinDeclaration::use_counter_name, and v8::internal::torque::Identifier::value.
Visit() [16/17]
void v8::internal::torque::DeclarationVisitor::Visit (TorqueMacroDeclaration * decl) [static]
Definition at line 235 of file declaration-visitor.cc.
                                                           {
  Macro* macro = Declarations::DeclareMacro(
      decl->name->value, decl->export_to_csa, std::nullopt,
      TypeVisitor::MakeSignature(decl), decl->body, decl->op);
  macro->SetIdentifierPosition(decl->name->pos);
  macro->SetPosition(decl->pos);
  if (GlobalContext::collect_kythe_data()) {
    KytheData::AddFunctionDefinition(macro);
  }
}
References v8::internal::torque::KytheData::AddFunctionDefinition(), v8::internal::torque::TorqueMacroDeclaration::body, v8::internal::torque::GlobalContext::collect_kythe_data(), v8::internal::torque::Declarations::DeclareMacro(), v8::internal::torque::TorqueMacroDeclaration::export_to_csa, v8::internal::torque::TypeVisitor::MakeSignature(), v8::internal::torque::CallableDeclaration::name, v8::internal::torque::MacroDeclaration::op, v8::internal::torque::AstNode::pos, v8::internal::torque::Declarable::SetIdentifierPosition(), v8::internal::torque::Declarable::SetPosition(), and v8::internal::torque::Identifier::value.
Visit() [17/17]
static void v8::internal::torque::DeclarationVisitor::Visit (TypeDeclaration * decl) [inline], [static]
Definition at line 76 of file declaration-visitor.h.
                                           {
    // Looking up the type will trigger type computation; this ensures errors
    // are reported even if the type is unused.
    Declarations::LookupType(decl->name);
  }
References v8::internal::torque::Declarations::LookupType(), and v8::internal::torque::TypeDeclaration::name.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/declaration-visitor.h
/mnt/V8SourceCode/src/torque/declaration-visitor.cc