v8::internal::HeapSnapshotGenerator Class Reference
#include <heap-snapshot-generator.h>
Public Types
using HeapEntriesMap = base::HashMap
using SmiEntriesMap = std::unordered_map< int, HeapEntry * >
Public Member Functions
HeapSnapshotGenerator (HeapSnapshot *snapshot, v8::ActivityControl *control, v8::HeapProfiler::ObjectNameResolver *resolver, Heap *heap, cppgc::EmbedderStackState stack_state)
HeapSnapshotGenerator (const HeapSnapshotGenerator &)=delete
HeapSnapshotGenerator & operator= (const HeapSnapshotGenerator &)=delete
bool GenerateSnapshot ()
bool GenerateSnapshotAfterGC ()
HeapEntry * FindEntry (HeapThing ptr)
HeapEntry * FindEntry (Tagged< Smi > smi)
HeapEntry * AddEntry (Tagged< Smi > smi, HeapEntriesAllocator *allocator)
HeapEntry * FindOrAddEntry (HeapThing ptr, HeapEntriesAllocator *allocator)
HeapEntry * FindOrAddEntry (Tagged< Smi > smi, HeapEntriesAllocator *allocator)
Heap * heap () const
UnorderedCppHeapExternalObjectSet & GetCppHeapExternalObjects ()
UnorderedCppHeapExternalObjectSet TakeCppHeapExternalObjects ()
Private Member Functions
bool FillReferences ()
void ProgressStep () override
bool ProgressReport (bool force=false) override
void InitProgressCounter ()
Private Attributes
HeapSnapshot * snapshot_
v8::ActivityControl * control_
V8HeapExplorer v8_heap_explorer_
NativeObjectsExplorer dom_explorer_
HeapEntriesMap entries_map_
SmiEntriesMap smis_map_
uint32_t progress_counter_
uint32_t progress_total_
Heap * heap_
cppgc::EmbedderStackState stack_state_
UnorderedCppHeapExternalObjectSet cpp_heap_external_objects_
Detailed Description
Definition at line 642 of file heap-snapshot-generator.h.
Member Typedef Documentation
HeapEntriesMap
using v8::internal::HeapSnapshotGenerator::HeapEntriesMap = base::HashMap
Definition at line 646 of file heap-snapshot-generator.h.
SmiEntriesMap
using v8::internal::HeapSnapshotGenerator::SmiEntriesMap = std::unordered_map<int, HeapEntry*>
Definition at line 649 of file heap-snapshot-generator.h.
Constructor & Destructor Documentation
HeapSnapshotGenerator() [1/2]
v8::internal::HeapSnapshotGenerator::HeapSnapshotGenerator (HeapSnapshot * snapshot, v8::ActivityControl * control, v8::HeapProfiler::ObjectNameResolver * resolver, Heap * heap, cppgc::EmbedderStackState stack_state)
Definition at line 3255 of file heap-snapshot-generator.cc.
    : snapshot_(snapshot),
      control_(control),
      v8_heap_explorer_(snapshot_, this, resolver),
      dom_explorer_(snapshot_, this),
      heap_(heap),
      stack_state_(stack_state) {}
HeapSnapshotGenerator() [2/2]
v8::internal::HeapSnapshotGenerator::HeapSnapshotGenerator (const HeapSnapshotGenerator &) [delete]
Member Function Documentation
AddEntry()
HeapEntry* v8::internal::HeapSnapshotGenerator::AddEntry (Tagged< Smi > smi, HeapEntriesAllocator * allocator) [inline]
Definition at line 687 of file heap-snapshot-generator.h.
                                                                        {
    return smis_map_.emplace(smi.value(), allocator->AllocateEntry(smi))
        .first->second;
  }
References v8::internal::HeapEntriesAllocator::AllocateEntry(), smis_map_, and v8::internal::Tagged< Smi >::value().
Referenced by FindOrAddEntry().
FillReferences()
bool v8::internal::HeapSnapshotGenerator::FillReferences () [private]
Definition at line 3374 of file heap-snapshot-generator.cc.
                                           {
  return v8_heap_explorer_.IterateAndExtractReferences(this) &&
         dom_explorer_.IterateAndExtractReferences(this);
}
References dom_explorer_, v8::internal::V8HeapExplorer::IterateAndExtractReferences(), v8::internal::NativeObjectsExplorer::IterateAndExtractReferences(), and v8_heap_explorer_.
Referenced by GenerateSnapshot(), and GenerateSnapshotAfterGC().
FindEntry() [1/2]
HeapEntry* v8::internal::HeapSnapshotGenerator::FindEntry (HeapThing ptr) [inline]
Definition at line 659 of file heap-snapshot-generator.h.
                                      {
    HeapEntriesMap::Entry* entry =
        entries_map_.Lookup(ptr, ComputePointerHash(ptr));
    return entry ? static_cast<HeapEntry*>(entry->value) : nullptr;
  }
References v8::internal::ComputePointerHash(), and entries_map_.
Referenced by v8::internal::NativeObjectsExplorer::EntryForEmbedderGraphNode(), and FindOrAddEntry().
FindEntry() [2/2]
HeapEntry* v8::internal::HeapSnapshotGenerator::FindEntry (Tagged< Smi > smi) [inline]
Definition at line 665 of file heap-snapshot-generator.h.
                                        {
    auto it = smis_map_.find(smi.value());
    return it != smis_map_.end() ? it->second : nullptr;
  }
References smis_map_, and v8::internal::Tagged< Smi >::value().
FindOrAddEntry() [1/2]
HeapEntry* v8::internal::HeapSnapshotGenerator::FindOrAddEntry (HeapThing ptr, HeapEntriesAllocator * allocator) [inline]
Definition at line 692 of file heap-snapshot-generator.h.
                                                                            {
    HeapEntriesMap::Entry* entry =
        entries_map_.LookupOrInsert(ptr, ComputePointerHash(ptr));
    if (entry->value != nullptr) {
      return static_cast<HeapEntry*>(entry->value);
    }
    HeapEntry* result = allocator->AllocateEntry(ptr);
    entry->value = result;
#ifdef V8_ENABLE_HEAP_SNAPSHOT_VERIFY
    if (v8_flags.heap_snapshot_verify) {
      reverse_entries_map_.emplace(result, ptr);
    }
#endif
    return result;
  }
References v8::internal::HeapEntriesAllocator::AllocateEntry(), v8::internal::ComputePointerHash(), entries_map_, v8::base::internal::result, and v8::internal::v8_flags.
Referenced by v8::internal::NativeObjectsExplorer::EntryForEmbedderGraphNode(), v8::internal::V8HeapExplorer::ExtractJSArrayBufferReferences(), and v8::internal::V8HeapExplorer::GetEntry().
FindOrAddEntry() [2/2]
HeapEntry* v8::internal::HeapSnapshotGenerator::FindOrAddEntry (Tagged< Smi > smi, HeapEntriesAllocator * allocator) [inline]
Definition at line 708 of file heap-snapshot-generator.h.
                                                                              {
    HeapEntry* entry = FindEntry(smi);
    return entry != nullptr ? entry : AddEntry(smi, allocator);
  }
References AddEntry(), and FindEntry().
GenerateSnapshot()
bool v8::internal::HeapSnapshotGenerator::GenerateSnapshot ()
Definition at line 3281 of file heap-snapshot-generator.cc.
                                             {
  v8::base::ElapsedTimer timer;
  timer.Start();
  IsolateSafepointScope scope(heap_);
  Isolate* isolate = heap_->isolate();
  auto temporary_global_object_tags =
      v8_heap_explorer_.CollectTemporaryGlobalObjectsTags();
  EmbedderStackStateScope stack_scope(
      heap_, EmbedderStackStateOrigin::kImplicitThroughTask, stack_state_);
  heap_->CollectAllAvailableGarbage(GarbageCollectionReason::kHeapProfiler);
  heap_->CompleteSweepingFull();
  // No allocation that could trigger GC from here onwards. We cannot use a
  // DisallowGarbageCollection scope as the HeapObjectIterator used during
  // snapshot creation enters a safepoint as well. However, in practice we
  // already enter a safepoint above so that should never trigger a GC.
  DisallowPositionInfoSlow no_position_info_slow;
  NullContextForSnapshotScope null_context_scope(isolate);
  v8_heap_explorer_.MakeGlobalObjectTagMap(
      std::move(temporary_global_object_tags));
  InitProgressCounter();
  snapshot_->AddSyntheticRootEntries();
  v8_heap_explorer_.PopulateLineEnds();
  if (!FillReferences()) return false;
  snapshot_->FillChildren();
  snapshot_->RememberLastJSObjectId();
  progress_counter_ = progress_total_;
  if (i::v8_flags.profile_heap_snapshot) {
    base::OS::PrintError("[Heap snapshot took %0.3f ms]\n",
                         timer.Elapsed().InMillisecondsF());
  }
  timer.Stop();
  if (!ProgressReport(true)) return false;
  return true;
}
References v8::internal::HeapSnapshot::AddSyntheticRootEntries(), v8::internal::Heap::CollectAllAvailableGarbage(), v8::internal::V8HeapExplorer::CollectTemporaryGlobalObjectsTags(), v8::internal::Heap::CompleteSweepingFull(), v8::base::ElapsedTimer::Elapsed(), v8::internal::HeapSnapshot::FillChildren(), FillReferences(), heap_, InitProgressCounter(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::Heap::isolate(), v8::internal::kHeapProfiler, v8::internal::kImplicitThroughTask, v8::internal::V8HeapExplorer::MakeGlobalObjectTagMap(), v8::internal::V8HeapExplorer::PopulateLineEnds(), progress_counter_, progress_total_, ProgressReport(), v8::internal::HeapSnapshot::RememberLastJSObjectId(), snapshot_, stack_state_, v8::base::ElapsedTimer::Start(), v8::base::ElapsedTimer::Stop(), v8::internal::v8_flags, and v8_heap_explorer_.
Referenced by v8::internal::HeapProfiler::TakeSnapshot().
GenerateSnapshotAfterGC()
bool v8::internal::HeapSnapshotGenerator::GenerateSnapshotAfterGC ()
Definition at line 3328 of file heap-snapshot-generator.cc.
                                                    {
  // Same as above, but no allocations, no GC run, and no progress report.
  IsolateSafepointScope scope(heap_);
  auto temporary_global_object_tags =
      v8_heap_explorer_.CollectTemporaryGlobalObjectsTags();
  NullContextForSnapshotScope null_context_scope(heap_->isolate());
  v8_heap_explorer_.MakeGlobalObjectTagMap(
      std::move(temporary_global_object_tags));
  snapshot_->AddSyntheticRootEntries();
  v8_heap_explorer_.PopulateLineEnds();
  if (!FillReferences()) return false;
  snapshot_->FillChildren();
  snapshot_->RememberLastJSObjectId();
  return true;
}
References v8::internal::HeapSnapshot::AddSyntheticRootEntries(), v8::internal::V8HeapExplorer::CollectTemporaryGlobalObjectsTags(), v8::internal::HeapSnapshot::FillChildren(), FillReferences(), heap_, v8::internal::Heap::isolate(), v8::internal::V8HeapExplorer::MakeGlobalObjectTagMap(), v8::internal::V8HeapExplorer::PopulateLineEnds(), v8::internal::HeapSnapshot::RememberLastJSObjectId(), snapshot_, and v8_heap_explorer_.
Referenced by v8::internal::HeapProfiler::WriteSnapshotToDiskAfterGC().
GetCppHeapExternalObjects()
UnorderedCppHeapExternalObjectSet& v8::internal::HeapSnapshotGenerator::GetCppHeapExternalObjects () [inline]
Definition at line 715 of file heap-snapshot-generator.h.
                                                                 {
    return cpp_heap_external_objects_;
  }
References cpp_heap_external_objects_.
Referenced by v8::internal::V8HeapExplorer::ExtractCppHeapExternalReferences().
heap()
Heap* v8::internal::HeapSnapshotGenerator::heap () const [inline]
Definition at line 713 of file heap-snapshot-generator.h.
{ return heap_; }
References heap_.
InitProgressCounter()
void v8::internal::HeapSnapshotGenerator::InitProgressCounter () [private]
Definition at line 3368 of file heap-snapshot-generator.cc.
                                                {
  if (control_ == nullptr) return;
  progress_total_ = v8_heap_explorer_.EstimateObjectsCount();
  progress_counter_ = 0;
}
References control_, v8::internal::V8HeapExplorer::EstimateObjectsCount(), progress_counter_, progress_total_, and v8_heap_explorer_.
Referenced by GenerateSnapshot().
operator=()
HeapSnapshotGenerator& v8::internal::HeapSnapshotGenerator::operator= (const HeapSnapshotGenerator &) [delete]
ProgressReport()
bool v8::internal::HeapSnapshotGenerator::ProgressReport (bool force = false) [override], [private], [virtual]
Implements v8::internal::SnapshottingProgressReportingInterface.
Definition at line 3358 of file heap-snapshot-generator.cc.
                                                     {
  const int kProgressReportGranularity = 10000;
  if (control_ != nullptr &&
      (force || progress_counter_ % kProgressReportGranularity == 0)) {
    return control_->ReportProgressValue(progress_counter_, progress_total_) ==
           v8::ActivityControl::kContinue;
  }
  return true;
}
References control_, v8::ActivityControl::kContinue, progress_counter_, progress_total_, and v8::ActivityControl::ReportProgressValue().
Referenced by GenerateSnapshot().
ProgressStep()
void v8::internal::HeapSnapshotGenerator::ProgressStep () [override], [private], [virtual]
Implements v8::internal::SnapshottingProgressReportingInterface.
Definition at line 3344 of file heap-snapshot-generator.cc.
                                         {
  // Only increment the progress_counter_ until
  // equal to progress_total -1 == progress_counter.
  // This ensures that intermediate ProgressReport calls will never signal
  // that the work is finished (i.e. progress_counter_ == progress_total_).
  // Only the forced ProgressReport() at the end of GenerateSnapshot() should,
  // after setting progress_counter_ = progress_total_, signal that the
  // work is finished because signalling finished twice
  // breaks the DevTools frontend.
  if (control_ != nullptr && progress_total_ > progress_counter_ + 1) {
    ++progress_counter_;
  }
}
References control_, progress_counter_, and progress_total_.
TakeCppHeapExternalObjects()
UnorderedCppHeapExternalObjectSet v8::internal::HeapSnapshotGenerator::TakeCppHeapExternalObjects () [inline]
Definition at line 719 of file heap-snapshot-generator.h.
                                                                 {
    return std::move(cpp_heap_external_objects_);
  }
References cpp_heap_external_objects_.
Referenced by v8::internal::NativeObjectsExplorer::IterateAndExtractReferences().
Member Data Documentation
control_
v8::ActivityControl* v8::internal::HeapSnapshotGenerator::control_ [private]
Definition at line 730 of file heap-snapshot-generator.h.
Referenced by InitProgressCounter(), ProgressReport(), and ProgressStep().
cpp_heap_external_objects_
UnorderedCppHeapExternalObjectSet v8::internal::HeapSnapshotGenerator::cpp_heap_external_objects_ [private]
Definition at line 741 of file heap-snapshot-generator.h.
Referenced by GetCppHeapExternalObjects(), and TakeCppHeapExternalObjects().
dom_explorer_
NativeObjectsExplorer v8::internal::HeapSnapshotGenerator::dom_explorer_ [private]
Definition at line 732 of file heap-snapshot-generator.h.
Referenced by FillReferences().
entries_map_
HeapEntriesMap v8::internal::HeapSnapshotGenerator::entries_map_ [private]
Definition at line 734 of file heap-snapshot-generator.h.
Referenced by FindEntry(), and FindOrAddEntry().
heap_
Heap* v8::internal::HeapSnapshotGenerator::heap_ [private]
Definition at line 739 of file heap-snapshot-generator.h.
Referenced by GenerateSnapshot(), GenerateSnapshotAfterGC(), and heap().
progress_counter_
uint32_t v8::internal::HeapSnapshotGenerator::progress_counter_ [private]
Definition at line 737 of file heap-snapshot-generator.h.
Referenced by GenerateSnapshot(), InitProgressCounter(), ProgressReport(), and ProgressStep().
progress_total_
uint32_t v8::internal::HeapSnapshotGenerator::progress_total_ [private]
Definition at line 738 of file heap-snapshot-generator.h.
Referenced by GenerateSnapshot(), InitProgressCounter(), ProgressReport(), and ProgressStep().
smis_map_
SmiEntriesMap v8::internal::HeapSnapshotGenerator::smis_map_ [private]
Definition at line 735 of file heap-snapshot-generator.h.
Referenced by AddEntry(), and FindEntry().
snapshot_
HeapSnapshot* v8::internal::HeapSnapshotGenerator::snapshot_ [private]
Definition at line 729 of file heap-snapshot-generator.h.
Referenced by GenerateSnapshot(), and GenerateSnapshotAfterGC().
stack_state_
cppgc::EmbedderStackState v8::internal::HeapSnapshotGenerator::stack_state_ [private]
Definition at line 740 of file heap-snapshot-generator.h.
Referenced by GenerateSnapshot().
v8_heap_explorer_
V8HeapExplorer v8::internal::HeapSnapshotGenerator::v8_heap_explorer_ [private]
Definition at line 731 of file heap-snapshot-generator.h.
Referenced by FillReferences(), GenerateSnapshot(), GenerateSnapshotAfterGC(), and InitProgressCounter().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.h
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.cc