v8::internal::torque::Block Class Reference
#include <cfg.h>
Public Member Functions
Block (ControlFlowGraph *cfg, size_t id, std::optional< Stack< const Type * >> input_types, bool is_deferred)
void Add (Instruction instruction)
bool HasInputTypes () const
const Stack< const Type * > & InputTypes () const
void SetInputTypes (const Stack< const Type * > &input_types)
void Retype ()
std::vector< Instruction > & instructions ()
const std::vector< Instruction > & instructions () const
bool IsComplete () const
size_t id () const
bool IsDeferred () const
void MergeInputDefinitions (const Stack< DefinitionLocation > &input_definitions, Worklist< Block * > *worklist)
bool HasInputDefinitions () const
const Stack< DefinitionLocation > & InputDefinitions () const
bool IsDead () const
Private Attributes
ControlFlowGraph * cfg_
std::vector< Instruction > instructions_
std::optional< Stack< const Type * > > input_types_
std::optional< Stack< DefinitionLocation > > input_definitions_
const size_t id_
bool is_deferred_
Detailed Description
Definition at line 23 of file cfg.h.
Constructor & Destructor Documentation
Block()
v8::internal::torque::Block::Block (ControlFlowGraph * cfg, size_t id, std::optional< Stack< const Type * >> input_types, bool is_deferred) [inline], [explicit]
Definition at line 25 of file cfg.h.
      : cfg_(cfg),
        input_types_(std::move(input_types)),
        id_(id),
        is_deferred_(is_deferred) {}
Member Function Documentation
Add()
void v8::internal::torque::Block::Add (Instruction instruction) [inline]
Definition at line 32 of file cfg.h.
                                    {
    DCHECK(!IsComplete());
    instructions_.push_back(std::move(instruction));
  }
References v8::internal::DCHECK(), instructions_, and IsComplete().
Referenced by v8::internal::torque::CfgAssembler::Emit().
HasInputDefinitions()
bool v8::internal::torque::Block::HasInputDefinitions () const [inline]
Definition at line 76 of file cfg.h.
                                   {
    return input_definitions_ != std::nullopt;
  }
References input_definitions_.
Referenced by InputDefinitions(), and IsDead().
HasInputTypes()
bool v8::internal::torque::Block::HasInputTypes () const [inline]
Definition at line 37 of file cfg.h.
{ return input_types_ != std::nullopt; }
References input_types_.
Referenced by v8::internal::torque::CfgAssembler::Bind(), and v8::internal::torque::CfgAssembler::Goto().
id()
size_t v8::internal::torque::Block::id () const [inline]
Definition at line 52 of file cfg.h.
{ return id_; }
References id_.
Referenced by v8::internal::torque::TorqueCodeGenerator::BlockName(), v8::internal::torque::CountBlockPredecessors(), v8::internal::torque::TorqueCodeGenerator::DefinitionToVariable(), v8::internal::torque::operator<<(), and v8::internal::torque::CfgAssembler::OptimizeCfg().
InputDefinitions()
const Stack<DefinitionLocation>& v8::internal::torque::Block::InputDefinitions () const [inline]
Definition at line 79 of file cfg.h.
                                                            {
    DCHECK(HasInputDefinitions());
    return *input_definitions_;
  }
References v8::internal::DCHECK(), HasInputDefinitions(), and input_definitions_.
Referenced by v8::internal::torque::CfgAssembler::ComputeInputDefinitions(), v8::internal::torque::CCGenerator::EmitBlock(), v8::internal::torque::CSAGenerator::EmitBlock(), and v8::internal::torque::CCGenerator::EmitGoto().
InputTypes()
const Stack<const Type*>& v8::internal::torque::Block::InputTypes () const [inline]
Definition at line 38 of file cfg.h.
{ return *input_types_; }
References input_types_.
Referenced by v8::internal::torque::CfgAssembler::Bind(), v8::internal::torque::CfgAssemblerScopedTemporaryBlock::CfgAssemblerScopedTemporaryBlock(), v8::internal::torque::CCGenerator::EmitBlock(), v8::internal::torque::CSAGenerator::EmitBlock(), v8::internal::torque::CfgAssembler::Goto(), v8::internal::torque::ControlFlowGraph::ParameterCount(), and Retype().
instructions() [1/2]
std::vector<Instruction>& v8::internal::torque::Block::instructions () [inline]
Definition at line 47 of file cfg.h.
{ return instructions_; }
References instructions_.
Referenced by v8::internal::torque::CfgAssembler::Bind(), v8::internal::torque::CfgAssembler::ComputeInputDefinitions(), v8::internal::torque::CCGenerator::EmitBlock(), v8::internal::torque::CSAGenerator::EmitBlock(), v8::internal::torque::CfgAssembler::OptimizeCfg(), and Retype().
instructions() [2/2]
const std::vector<Instruction>& v8::internal::torque::Block::instructions () const [inline]
Definition at line 48 of file cfg.h.
{ return instructions_; }
References instructions_.
IsComplete()
bool v8::internal::torque::Block::IsComplete () const [inline]
Definition at line 49 of file cfg.h.
                          {
    return !instructions_.empty() && instructions_.back()->IsBlockTerminator();
  }
References instructions_.
Referenced by Add(), v8::internal::torque::CfgAssembler::Bind(), and v8::internal::torque::CfgAssembler::CurrentBlockIsComplete().
IsDead()
bool v8::internal::torque::Block::IsDead () const [inline]
Definition at line 84 of file cfg.h.
{ return !HasInputDefinitions(); }
References HasInputDefinitions().
IsDeferred()
bool v8::internal::torque::Block::IsDeferred () const [inline]
Definition at line 53 of file cfg.h.
{ return is_deferred_; }
References is_deferred_.
MergeInputDefinitions()
void v8::internal::torque::Block::MergeInputDefinitions (const Stack< DefinitionLocation > & input_definitions, Worklist< Block * > * worklist) [inline]
Definition at line 55 of file cfg.h.
                                                         {
    if (!input_definitions_) {
      input_definitions_ = input_definitions;
      if (worklist) worklist->Enqueue(this);
      return;
    }
    DCHECK_EQ(input_definitions_->Size(), input_definitions.Size());
    bool changed = false;
    for (BottomOffset i = {0}; i < input_definitions.AboveTop(); ++i) {
      auto& current = input_definitions_->Peek(i);
      auto& input = input_definitions.Peek(i);
      if (current == input) continue;
      if (current == DefinitionLocation::Phi(this, i.offset)) continue;
      input_definitions_->Poke(i, DefinitionLocation::Phi(this, i.offset));
      changed = true;
    }
    if (changed && worklist) worklist->Enqueue(this);
  }
References v8::internal::torque::Stack< T >::AboveTop(), DCHECK_EQ, v8::internal::torque::Worklist< T >::Enqueue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, input_definitions_, v8::internal::torque::Stack< T >::Peek(), v8::internal::torque::DefinitionLocation::Phi(), and v8::internal::torque::Stack< T >::Size().
Referenced by v8::internal::torque::CfgAssembler::ComputeInputDefinitions().
Retype()
void v8::internal::torque::Block::Retype () [inline]
Definition at line 40 of file cfg.h.
                {
    Stack<const Type*> current_stack = InputTypes();
    for (const Instruction& instruction : instructions()) {
      instruction.TypeInstruction(&current_stack, cfg_);
    }
  }
References cfg_, InputTypes(), and instructions().
Referenced by SetInputTypes().
SetInputTypes()
void v8::internal::torque::Block::SetInputTypes (const Stack< const Type * > & input_types)
Definition at line 13 of file cfg.cc.
                                                               {
  if (!input_types_) {
    input_types_ = input_types;
    return;
  } else if (*input_types_ == input_types) {
    return;
  }
  DCHECK_EQ(input_types.Size(), input_types_->Size());
  Stack<const Type*> merged_types;
  bool widened = false;
  auto c2_iterator = input_types.begin();
  for (const Type* c1 : *input_types_) {
    const Type* merged_type = TypeOracle::GetUnionType(c1, *c2_iterator++);
    if (!merged_type->IsSubtypeOf(c1)) {
      widened = true;
    }
    merged_types.Push(merged_type);
  }
  if (merged_types.Size() == input_types_->Size()) {
    if (widened) {
      input_types_ = merged_types;
      Retype();
    }
    return;
  }
  std::stringstream error;
  error << "incompatible types at branch:\n";
  for (intptr_t i = std::max(input_types_->Size(), input_types.Size()) - 1;
       i >= 0; --i) {
    std::optional<const Type*> left;
    std::optional<const Type*> right;
    if (static_cast<size_t>(i) < input_types.Size()) {
      left = input_types.Peek(BottomOffset{static_cast<size_t>(i)});
    }
    if (static_cast<size_t>(i) < input_types_->Size()) {
      right = input_types_->Peek(BottomOffset{static_cast<size_t>(i)});
    }
    if (left && right && *left == *right) {
      error << **left << "\n";
    } else {
      if (left) {
        error << **left;
      } else {
        error << "/*missing*/";
      }
      error << " => ";
      if (right) {
        error << **right;
      } else {
        error << "/*missing*/";
      }
      error << "\n";
    }
  }
  ReportError(error.str());
}
References v8::internal::torque::Stack< T >::begin(), DCHECK_EQ, v8::internal::torque::TypeOracle::GetUnionType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, input_types_, v8::internal::torque::Type::IsSubtypeOf(), v8::internal::torque::Stack< T >::Peek(), v8::internal::torque::Stack< T >::Push(), v8::internal::torque::ReportError(), Retype(), and v8::internal::torque::Stack< T >::Size().
Member Data Documentation
cfg_
ControlFlowGraph* v8::internal::torque::Block::cfg_ [private]
Definition at line 87 of file cfg.h.
Referenced by Retype().
id_
const size_t v8::internal::torque::Block::id_ [private]
Definition at line 91 of file cfg.h.
Referenced by id().
input_definitions_
std::optional<Stack<DefinitionLocation> > v8::internal::torque::Block::input_definitions_ [private]
Definition at line 90 of file cfg.h.
Referenced by HasInputDefinitions(), InputDefinitions(), and MergeInputDefinitions().
input_types_
std::optional<Stack<const Type*> > v8::internal::torque::Block::input_types_ [private]
Definition at line 89 of file cfg.h.
Referenced by HasInputTypes(), InputTypes(), and SetInputTypes().
instructions_
std::vector<Instruction> v8::internal::torque::Block::instructions_ [private]
Definition at line 88 of file cfg.h.
Referenced by Add(), instructions(), and IsComplete().
is_deferred_
bool v8::internal::torque::Block::is_deferred_ [private]
Definition at line 92 of file cfg.h.
Referenced by IsDeferred().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/cfg.h
/mnt/V8SourceCode/src/torque/cfg.cc