v8::internal::wasm::NativeModule Class Reference
#include <wasm-code-manager.h>
Classes
struct CodeSpaceData
struct JumpTablesRef
class NativeModuleAllocationLockScope
Public Types
enum class RemoveFilter {
kRemoveDebugCode
, kRemoveNonDebugCode
, kRemoveLiftoffCode
, kRemoveTurbofanCode
,
kRemoveAllCode
 }
enum class JumpTableType { kJumpTable
, kFarJumpTable
, kLazyCompileTable
 }
using CallIndirectTargetMap = absl::flat_hash_map< WasmCodePointer, uint32_t >
Public Member Functions
NativeModule (const NativeModule &)=delete
NativeModule & operator= (const NativeModule &)=delete
~NativeModule ()
uint32_t DisassembleForLcov (std::ostream &out, std::vector< int > &function_body_offsets, std::map< uint32_t, uint32_t > &bytecode_disasm_offsets)
std::unique_ptr< WasmCode > AddCode (int index, const CodeDesc &desc, int stack_slots, int ool_spill_count, uint32_t tagged_parameter_slots, base::Vector< const uint8_t > protected_instructions, base::Vector< const uint8_t > source_position_table, base::Vector< const uint8_t > inlining_positions, base::Vector< const uint8_t > deopt_data, WasmCode::Kind kind, ExecutionTier tier, ForDebugging for_debugging)
WasmCode * PublishCode (UnpublishedWasmCode)
std::vector< WasmCode * > PublishCode (base::Vector< UnpublishedWasmCode >)
void UpdateWellKnownImports (base::Vector< WellKnownImport > entries)
void ReinstallDebugCode (WasmCode *)
std::pair< base::Vector< uint8_t >, JumpTablesRef > AllocateForDeserializedCode (size_t total_code_size)
std::unique_ptr< WasmCode > AddDeserializedCode (int index, base::Vector< uint8_t > instructions, int stack_slots, int ool_spills, uint32_t tagged_parameter_slots, int safepoint_table_offset, int handler_table_offset, int constant_pool_offset, int code_comments_offset, int jump_table_info_offset, int unpadded_binary_size, base::Vector< const uint8_t > protected_instructions_data, base::Vector< const uint8_t > reloc_info, base::Vector< const uint8_t > source_position_table, base::Vector< const uint8_t > inlining_positions, base::Vector< const uint8_t > deopt_data, WasmCode::Kind kind, ExecutionTier tier)
WasmCode * AddCodeForTesting (DirectHandle< Code > code, uint64_t signature_hash)
void InitializeJumpTableForLazyCompilation (uint32_t num_wasm_functions)
void InitializeCodePointerTableHandles (uint32_t num_wasm_functions)
void FreeCodePointerTableHandles ()
void UseLazyStubLocked (uint32_t func_index)
std::pair< std::vector< WasmCode * >, std::vector< WellKnownImport > > SnapshotCodeTable () const
std::vector< WasmCode * > SnapshotAllOwnedCode () const
WasmCode * GetCode (uint32_t index) const
bool HasCode (uint32_t index) const
bool HasCodeWithTier (uint32_t index, ExecutionTier tier) const
void SetWasmSourceMap (std::unique_ptr< WasmModuleSourceMap > source_map)
WasmModuleSourceMap * GetWasmSourceMap () const
Address jump_table_start () const
Address GetNearCallTargetForFunction (uint32_t func_index, const JumpTablesRef &) const
Address GetJumpTableEntryForBuiltin (Builtin builtin, const JumpTablesRef &) const
uint32_t GetFunctionIndexFromJumpTableSlot (Address slot_address) const
CallIndirectTargetMap CreateIndirectCallTargetToFunctionIndexMap () const
void LogWasmCodes (Isolate *, Tagged< Script >)
CompilationState * compilation_state () const
uint32_t num_functions () const
uint32_t num_imported_functions () const
uint32_t num_declared_functions () const
void set_lazy_compile_frozen (bool frozen)
bool lazy_compile_frozen () const
base::Vector< const uint8_t > wire_bytes () const
const WasmModule * module () const
std::shared_ptr< const WasmModule > shared_module () const
size_t committed_code_space () const
size_t generated_code_size () const
size_t liftoff_bailout_count () const
size_t liftoff_code_size () const
size_t turbofan_code_size () const
void AddLazyCompilationTimeSample (int64_t sample)
int num_lazy_compilations () const
int64_t sum_lazy_compilation_time_in_ms () const
int64_t max_lazy_compilation_time_in_ms () const
bool ShouldLazyCompilationMetricsBeReported ()
bool ShouldPgoDataBeWritten ()
bool HasWireBytes () const
void SetWireBytes (base::OwnedVector< const uint8_t > wire_bytes)
void AddLiftoffBailout ()
WasmCode * Lookup (Address) const
WasmEnabledFeatures enabled_features () const
const CompileTimeImports & compile_imports () const
Builtin GetBuiltinInJumptableSlot (Address target) const
void SampleCodeSize (Counters *) const
V8_WARN_UNUSED_RESULT UnpublishedWasmCode AddCompiledCode (WasmCompilationResult &)
V8_WARN_UNUSED_RESULT std::vector< UnpublishedWasmCode > AddCompiledCode (base::Vector< WasmCompilationResult >)
void SetDebugState (DebugState)
DebugState IsInDebugState () const
void RemoveCompiledCode (RemoveFilter filter)
size_t SumLiftoffCodeSizeForTesting () const
void FreeCode (base::Vector< WasmCode *const >)
size_t GetNumberOfCodeSpacesForTesting () const
bool HasDebugInfo () const
DebugInfo * GetDebugInfo ()
NamesProvider * GetNamesProvider ()
std::atomic< uint32_t > * tiering_budget_array () const
Counters * counters () const
size_t EstimateCurrentMemoryConsumption () const
void PrintCurrentMemoryConsumptionEstimate () const
bool log_code () const
void EnableCodeLogging ()
void DisableCodeLogging ()
bool TrySetFastApiCallTarget (int func_index, Address target)
std::atomic< Address > * fast_api_targets () const
void set_fast_api_signature (int func_index, const MachineSignature *sig)
bool has_fast_api_signature (int index)
std::atomic< const MachineSignature * > * fast_api_signatures () const
WasmCodePointer GetCodePointerHandle (int index) const
const std::shared_ptr< WasmModuleCoverageData > & coverage_data () const
Static Public Attributes
static constexpr ExternalPointerTag kManagedTag = kWasmNativeModuleTag
static constexpr bool kNeedsFarJumpsBetweenCodeSpaces = false
Private Member Functions
NativeModule (WasmEnabledFeatures enabled_features, WasmDetectedFeatures detected_features, CompileTimeImports compile_imports, VirtualMemory code_space, std::shared_ptr< const WasmModule > module, std::shared_ptr< Counters > async_counters, std::shared_ptr< NativeModule > *shared_this)
std::unique_ptr< WasmCode > AddCodeWithCodeSpace (int index, const CodeDesc &desc, int stack_slots, int ool_spill_count, uint32_t tagged_parameter_slots, base::Vector< const uint8_t > protected_instructions_data, base::Vector< const uint8_t > source_position_table, base::Vector< const uint8_t > inlining_positions, base::Vector< const uint8_t > deopt_data, WasmCode::Kind kind, ExecutionTier tier, ForDebugging for_debugging, bool frame_has_feedback_slot, base::Vector< uint8_t > code_space, const JumpTablesRef &jump_tables_ref)
WasmCode * CreateEmptyJumpTableLocked (int jump_table_size, JumpTableType type)
WasmCode * CreateEmptyJumpTableInRegionLocked (int jump_table_size, base::AddressRegion, JumpTableType type)
JumpTablesRef FindJumpTablesForRegionLocked (base::AddressRegion) const
void UpdateCodeSize (size_t, ExecutionTier, ForDebugging)
void PatchJumpTablesLocked (uint32_t slot_index, Address target, Address code_pointer_table_target, uint64_t signature_hash)
void PatchJumpTableLocked (WritableJumpTablePair &jump_table_pair, const CodeSpaceData &, uint32_t slot_index, Address target)
void AddCodeSpaceLocked (base::AddressRegion)
WasmCode * PublishCodeLocked (std::unique_ptr< WasmCode >, AssumptionsJournal *)
void TransferNewOwnedCodeLocked () const
bool should_update_code_table (WasmCode *new_code, WasmCode *prior_code) const
Private Attributes
OperationsBarrier::Token engine_scope_
WasmCodeAllocator code_allocator_
const WasmEnabledFeatures enabled_features_
const CompileTimeImports compile_imports_
std::shared_ptr< const WasmModule > module_
std::unique_ptr< WasmModuleSourceMap > source_map_
std::shared_ptr< base::OwnedVector< const uint8_t > > wire_bytes_
WasmCode * main_jump_table_ = nullptr
WasmCode * main_far_jump_table_ = nullptr
WasmCode * lazy_compile_table_ = nullptr
std::unique_ptr< CompilationState > compilation_state_
std::unique_ptr< std::atomic< uint32_t >[]> tiering_budgets_
base::RecursiveMutex allocation_mutex_
std::map< Address, std::unique_ptr< WasmCode > > owned_code_
std::vector< std::unique_ptr< WasmCode > > new_owned_code_
std::unique_ptr< WasmCode *[]> code_table_
std::unique_ptr< WasmCodePointer[]> code_pointer_handles_
size_t code_pointer_handles_size_ = 0
std::vector< CodeSpaceData > code_space_data_
std::unique_ptr< DebugInfo > debug_info_
std::unique_ptr< NamesProvider > names_provider_
DebugState debug_state_ = kNotDebugging
bool lazy_compile_frozen_ = false
std::atomic< size_t > liftoff_bailout_count_ {0}
std::atomic< size_t > liftoff_code_size_ {0}
std::atomic< size_t > turbofan_code_size_ {0}
std::atomic< int > num_lazy_compilations_ {0}
std::atomic< int64_t > sum_lazy_compilation_time_in_micro_sec_ {0}
std::atomic< int64_t > max_lazy_compilation_time_in_micro_sec_ {0}
std::atomic< bool > should_metrics_be_reported_ {true}
std::atomic< bool > should_pgo_data_be_written_ {true}
std::atomic< bool > log_code_ {false}
std::unique_ptr< std::atomic< Address >[]> fast_api_targets_
std::unique_ptr< std::atomic< const MachineSignature * >[]> fast_api_signatures_
std::shared_ptr< WasmModuleCoverageData > coverage_data_
Friends
class WasmCode
class WasmCodeAllocator
class WasmCodeManager
class CodeSpaceWriteScope
Detailed Description
Definition at line 603 of file wasm-code-manager.h.
Member Typedef Documentation
CallIndirectTargetMap
using v8::internal::wasm::NativeModule::CallIndirectTargetMap = absl::flat_hash_map<WasmCodePointer, uint32_t>
Definition at line 740 of file wasm-code-manager.h.
Member Enumeration Documentation
JumpTableType
enum v8::internal::wasm::NativeModule::JumpTableType [strong]
Enumerator
kJumpTable
kFarJumpTable
kLazyCompileTable
Definition at line 905 of file wasm-code-manager.h.
                           {
    kJumpTable,
    kFarJumpTable,
    kLazyCompileTable,
  };
RemoveFilter
enum v8::internal::wasm::NativeModule::RemoveFilter [strong]
Enumerator
kRemoveDebugCode
kRemoveNonDebugCode
kRemoveLiftoffCode
kRemoveTurbofanCode
kRemoveAllCode
Definition at line 853 of file wasm-code-manager.h.
                          {
    kRemoveDebugCode,
    kRemoveNonDebugCode,
    kRemoveLiftoffCode,
    kRemoveTurbofanCode,
    kRemoveAllCode,
  };
Constructor & Destructor Documentation
NativeModule() [1/2]
v8::internal::wasm::NativeModule::NativeModule (const NativeModule &) [delete]
Referenced by EstimateCurrentMemoryConsumption().
 NativeModule()
v8::internal::wasm::NativeModule::~NativeModule ()
Definition at line 2154 of file wasm-code-manager.cc.
                            {
  TRACE_HEAP("Deleting native module: %p\n", this);
  // Cancel all background compilation before resetting any field of the
  // NativeModule or freeing anything.
  compilation_state_->CancelCompilation();
  if (V8_UNLIKELY(v8_flags.print_wasm_offheap_memory_size)) {
    // Print the current memory consumption of both this Module *and* the whole
    // engine before freeing this module. In a benchmark with a single module
    // this will probably be the high watermark of memory usage for the whole
    // engine.
    PrintCurrentMemoryConsumptionEstimate();
    GetWasmEngine()->PrintCurrentMemoryConsumptionEstimate();
  }
  GetWasmEngine()->FreeNativeModule(this);
  // If experimental PGO support is enabled, serialize the PGO data now.
  if (V8_UNLIKELY(v8_flags.experimental_wasm_pgo_to_file)) {
    DumpProfileToFile(module_.get(), wire_bytes(), tiering_budgets_.get());
  }
  FreeCodePointerTableHandles();
}
References compilation_state_, v8::internal::wasm::DumpProfileToFile(), FreeCodePointerTableHandles(), v8::internal::wasm::WasmEngine::FreeNativeModule(), v8::internal::wasm::GetWasmEngine(), module_, PrintCurrentMemoryConsumptionEstimate(), v8::internal::wasm::WasmEngine::PrintCurrentMemoryConsumptionEstimate(), tiering_budgets_, TRACE_HEAP, v8::internal::v8_flags, V8_UNLIKELY, and wire_bytes().
NativeModule() [2/2]
v8::internal::wasm::NativeModule::NativeModule (WasmEnabledFeatures enabled_features, WasmDetectedFeatures detected_features, CompileTimeImports compile_imports, VirtualMemory code_space, std::shared_ptr< const WasmModule > module, std::shared_ptr< Counters > async_counters, std::shared_ptr< NativeModule > * shared_this) [private]
Definition at line 997 of file wasm-code-manager.cc.
    : engine_scope_(
          GetWasmEngine()->GetBarrierForBackgroundCompile()->TryLock()),
      code_allocator_(async_counters),
      enabled_features_(enabled_features),
      compile_imports_(std::move(compile_imports)),
      module_(std::move(module)),
      fast_api_targets_(
          new std::atomic<Address>[module_->num_imported_functions]()),
      fast_api_signatures_(
          new std::atomic<
              const MachineSignature*>[module_->num_imported_functions]()) {
  DCHECK(engine_scope_);
  // We receive a pointer to an empty {std::shared_ptr}, and install ourselve
  // there.
  DCHECK_NOT_NULL(shared_this);
  DCHECK_NULL(*shared_this);
  shared_this->reset(this);
  compilation_state_ = CompilationState::New(
      *shared_this, std::move(async_counters), detected_features);
  compilation_state_->InitCompileJob();
  DCHECK_NOT_NULL(module_);
  if (module_->num_declared_functions > 0) {
    code_table_ =
        std::make_unique<WasmCode*[]>(module_->num_declared_functions);
    InitializeCodePointerTableHandles(module_->num_declared_functions);
    tiering_budgets_ = std::make_unique<std::atomic<uint32_t>[]>(
        module_->num_declared_functions);
    // The tiering budget is accessed directly from generated code.
    static_assert(sizeof(*tiering_budgets_.get()) == sizeof(uint32_t));
    std::fill_n(tiering_budgets_.get(), module_->num_declared_functions,
                v8_flags.wasm_tiering_budget);
  }
  if (v8_flags.wasm_jitless) return;
  // Even though there cannot be another thread using this object (since we
  // are just constructing it), we need to hold the mutex to fulfill the
  // precondition of {WasmCodeAllocator::Init}, which calls
  // {NativeModule::AddCodeSpaceLocked}.
  base::RecursiveMutexGuard guard{&allocation_mutex_};
  auto initial_region = code_space.region();
  code_allocator_.Init(std::move(code_space));
  const bool has_code_space = initial_region.size() > 0;
  DCHECK_EQ(has_code_space, module_->num_declared_functions != 0);
  if (has_code_space) {
    code_allocator_.InitializeCodeRange(this, initial_region);
    AddCodeSpaceLocked(initial_region);
  }
  if (v8_flags.wasm_code_coverage && module_) {
    coverage_data_ = std::make_shared<WasmModuleCoverageData>(
        module_->num_declared_functions);
  }
}
References AddCodeSpaceLocked(), allocation_mutex_, code_allocator_, code_table_, compilation_state_, coverage_data_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, DCHECK_NULL, engine_scope_, v8::internal::wasm::WasmCodeAllocator::Init(), InitializeCodePointerTableHandles(), v8::internal::wasm::WasmCodeAllocator::InitializeCodeRange(), module_, v8::internal::wasm::CompilationState::New(), v8::internal::VirtualMemory::region(), tiering_budgets_, and v8::internal::v8_flags.
Member Function Documentation
AddCode()
std::unique_ptr< WasmCode > v8::internal::wasm::NativeModule::AddCode (int index, const CodeDesc & desc, int stack_slots, int ool_spill_count, uint32_t tagged_parameter_slots, base::Vector< const uint8_t > protected_instructions, base::Vector< const uint8_t > source_position_table, base::Vector< const uint8_t > inlining_positions, base::Vector< const uint8_t > deopt_data, WasmCode::Kind kind, ExecutionTier tier, ForDebugging for_debugging)
Definition at line 1263 of file wasm-code-manager.cc.
                                                    {
  base::Vector<uint8_t> code_space;
  NativeModule::JumpTablesRef jump_table_ref;
  {
    base::RecursiveMutexGuard guard{&allocation_mutex_};
    code_space = code_allocator_.AllocateForCode(this, desc.instr_size);
    jump_table_ref =
        FindJumpTablesForRegionLocked(base::AddressRegionOf(code_space));
  }
  // Only Liftoff code can have the {frame_has_feedback_slot} bit set.
  DCHECK_NE(tier, ExecutionTier::kLiftoff);
  bool frame_has_feedback_slot = false;
  ThreadIsolation::RegisterJitAllocation(
      reinterpret_cast<Address>(code_space.begin()), code_space.size(),
      ThreadIsolation::JitAllocationType::kWasmCode);
  return AddCodeWithCodeSpace(
      index, desc, stack_slots, ool_spill_count, tagged_parameter_slots,
      protected_instructions_data, source_position_table, inlining_positions,
      deopt_data, kind, tier, for_debugging, frame_has_feedback_slot,
      code_space, jump_table_ref);
}
References AddCodeWithCodeSpace(), v8::base::AddressRegionOf(), v8::internal::wasm::WasmCodeAllocator::AllocateForCode(), allocation_mutex_, v8::base::Vector< T >::begin(), code_allocator_, DCHECK_NE, FindJumpTablesForRegionLocked(), v8::internal::index, v8::internal::CodeDesc::instr_size, v8::internal::wasm::kLiftoff, v8::internal::ThreadIsolation::kWasmCode, v8::internal::ThreadIsolation::RegisterJitAllocation(), and v8::base::Vector< T >::size().
AddCodeForTesting()
WasmCode * v8::internal::wasm::NativeModule::AddCodeForTesting (DirectHandle< Code > code, uint64_t signature_hash)
Definition at line 1081 of file wasm-code-manager.cc.
                                                                   {
  const size_t relocation_size = code->relocation_size();
  base::OwnedVector<uint8_t> reloc_info =
      base::OwnedCopyOf(code->relocation_start(), relocation_size);
  DirectHandle<TrustedByteArray> source_pos_table(code->source_position_table(),
                                                  Isolate::Current());
  int source_pos_len = source_pos_table->length();
  base::OwnedVector<uint8_t> source_pos =
      base::OwnedCopyOf(source_pos_table->begin(), source_pos_len);
  static_assert(InstructionStream::kOnHeapBodyIsContiguous);
  base::Vector<const uint8_t> instructions(
      reinterpret_cast<uint8_t*>(code->body_start()),
      static_cast<size_t>(code->body_size()));
  const int stack_slots = code->stack_slots();
  // Metadata offsets in InstructionStream objects are relative to the start of
  // the metadata section, whereas WasmCode expects offsets relative to
  // instruction_start.
  const int base_offset = code->instruction_size();
  // TODO(jgruber,v8:8758): Remove this translation. It exists only because
  // InstructionStream objects contains real offsets but WasmCode expects an
  // offset of 0 to mean 'empty'.
  const int safepoint_table_offset =
      code->has_safepoint_table() ? base_offset + code->safepoint_table_offset()
                                  : 0;
  const int handler_table_offset = base_offset + code->handler_table_offset();
  const int constant_pool_offset = base_offset + code->constant_pool_offset();
  const int code_comments_offset = base_offset + code->code_comments_offset();
  const int jump_table_info_offset =
      base_offset + code->jump_table_info_offset();
  base::RecursiveMutexGuard guard{&allocation_mutex_};
  base::Vector<uint8_t> dst_code_bytes =
      code_allocator_.AllocateForCode(this, instructions.size());
  {
    WritableJitAllocation jit_allocation =
        ThreadIsolation::RegisterJitAllocation(
            reinterpret_cast<Address>(dst_code_bytes.begin()),
            dst_code_bytes.size(),
            ThreadIsolation::JitAllocationType::kWasmCode, true);
    jit_allocation.CopyCode(0, instructions.begin(), instructions.size());
    // Apply the relocation delta by iterating over the RelocInfo.
    intptr_t delta = reinterpret_cast<Address>(dst_code_bytes.begin()) -
                     code->instruction_start();
    int mode_mask =
        RelocInfo::kApplyMask | RelocInfo::ModeMask(RelocInfo::WASM_STUB_CALL) |
        RelocInfo::ModeMask(RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY);
    auto jump_tables_ref =
        FindJumpTablesForRegionLocked(base::AddressRegionOf(dst_code_bytes));
    Address dst_code_addr = reinterpret_cast<Address>(dst_code_bytes.begin());
    Address constant_pool_start = dst_code_addr + constant_pool_offset;
    RelocIterator orig_it(*code, mode_mask);
    for (WritableRelocIterator it(jit_allocation, dst_code_bytes,
                                  reloc_info.as_vector(), constant_pool_start,
                                  mode_mask);
         !it.done(); it.next(), orig_it.next()) {
      RelocInfo::Mode mode = it.rinfo()->rmode();
      if (RelocInfo::IsWasmStubCall(mode)) {
        uint32_t stub_call_tag = orig_it.rinfo()->wasm_call_tag();
        DCHECK_LT(stub_call_tag,
                  static_cast<uint32_t>(Builtin::kFirstBytecodeHandler));
        Builtin builtin = static_cast<Builtin>(stub_call_tag);
        Address entry = GetJumpTableEntryForBuiltin(builtin, jump_tables_ref);
        it.rinfo()->set_wasm_stub_call_address(entry);
      } else if (RelocInfo::IsWasmCodePointerTableEntry(mode)) {
        uint32_t function_index =
            it.rinfo()->wasm_code_pointer_table_entry().value();
        WasmCodePointer target = GetCodePointerHandle(function_index);
        it.rinfo()->set_wasm_code_pointer_table_entry(target,
                                                      SKIP_ICACHE_FLUSH);
      } else {
        it.rinfo()->apply(delta);
      }
    }
  }
  // Flush the i-cache after relocation.
  FlushInstructionCache(dst_code_bytes.begin(), dst_code_bytes.size());
  std::unique_ptr<WasmCode> new_code{
      new WasmCode{this, // native_module
                   kAnonymousFuncIndex, // index
                   dst_code_bytes, // instructions
                   stack_slots, // stack_slots
                   0, // ool_spills
                   0, // tagged_parameter_slots
                   safepoint_table_offset, // safepoint_table_offset
                   handler_table_offset, // handler_table_offset
                   constant_pool_offset, // constant_pool_offset
                   code_comments_offset, // code_comments_offset
                   jump_table_info_offset, // jump_table_info_offset
                   instructions.length(), // unpadded_binary_size
                   {}, // protected_instructions
                   reloc_info.as_vector(), // reloc_info
                   source_pos.as_vector(), // source positions
                   {}, // inlining positions
                   {}, // deopt data
                   WasmCode::kWasmFunction, // kind
                   ExecutionTier::kNone, // tier
                   kNotForDebugging, // for_debugging
                   signature_hash}}; // signature_hash
  new_code->MaybePrint();
  new_code->Validate();
  return PublishCodeLocked(std::move(new_code),
                           UnpublishedWasmCode::kNoAssumptions);
}
References v8::base::AddressRegionOf(), v8::internal::wasm::WasmCodeAllocator::AllocateForCode(), allocation_mutex_, v8::base::OwnedVector< T >::as_vector(), v8::base::Vector< T >::begin(), code, code_allocator_, v8::internal::WritableJitAllocation::CopyCode(), v8::internal::Isolate::Current(), DCHECK_LT, v8::internal::RelocIteratorBase< RelocInfoT >::done(), FindJumpTablesForRegionLocked(), v8::internal::FlushInstructionCache(), GetCodePointerHandle(), GetJumpTableEntryForBuiltin(), v8::internal::RelocInfo::IsWasmCodePointerTableEntry(), v8::internal::RelocInfo::IsWasmStubCall(), v8::internal::wasm::kAnonymousFuncIndex, v8::internal::RelocInfo::kApplyMask, v8::internal::wasm::UnpublishedWasmCode::kNoAssumptions, v8::internal::wasm::kNone, v8::internal::wasm::kNotForDebugging, v8::internal::InstructionStream::kOnHeapBodyIsContiguous, v8::internal::ThreadIsolation::kWasmCode, v8::internal::wasm::WasmCode::kWasmFunction, v8::base::Vector< T >::length(), mode(), v8::internal::RelocInfo::ModeMask(), v8::internal::RelocIteratorBase< RelocInfoT >::next(), v8::base::OwnedCopyOf(), PublishCodeLocked(), v8::internal::ThreadIsolation::RegisterJitAllocation(), v8::internal::RelocIteratorBase< RelocInfoT >::rinfo(), v8::base::Vector< T >::size(), v8::internal::SKIP_ICACHE_FLUSH, v8::internal::RelocInfo::wasm_call_tag(), v8::internal::RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY, and v8::internal::RelocInfo::WASM_STUB_CALL.
AddCodeSpaceLocked()
void v8::internal::wasm::NativeModule::AddCodeSpaceLocked (base::AddressRegion region) [private]
Definition at line 1844 of file wasm-code-manager.cc.
                                                              {
  allocation_mutex_.AssertHeld();
  // We do not need a code space if the NativeModule does not hold any
  // functions (wrappers live in the wrapper cache).
  DCHECK_LT(0, module_->num_declared_functions);
  // Each code space must be at least twice as large as the overhead per code
  // space. Otherwise, we are wasting too much memory.
  DCHECK_GE(region.size(),
            2 * OverheadPerCodeSpace(module()->num_declared_functions));
  WasmCodeRefScope code_ref_scope;
  WasmCode* jump_table = nullptr;
  WasmCode* far_jump_table = nullptr;
  const uint32_t num_wasm_functions = module_->num_declared_functions;
  const bool is_first_code_space = code_space_data_.empty();
  // We always need a far jump table, because it contains the runtime stubs.
  const bool needs_far_jump_table =
      !FindJumpTablesForRegionLocked(region).is_valid();
  const bool needs_jump_table = num_wasm_functions > 0 && needs_far_jump_table;
  if (needs_jump_table) {
    // Allocate additional jump tables just as big as the first one.
    // This is in particular needed in cctests which add functions to the module
    // after the jump tables are already created (see
    // https://crbug.com/v8/14213).
    int jump_table_size =
        is_first_code_space
            ? JumpTableAssembler::SizeForNumberOfSlots(num_wasm_functions)
            : main_jump_table_->instructions_size_;
    jump_table = CreateEmptyJumpTableInRegionLocked(jump_table_size, region,
                                                    JumpTableType::kJumpTable);
    CHECK(region.contains(jump_table->instruction_start()));
  }
  if (needs_far_jump_table) {
    int num_function_slots = NumWasmFunctionsInFarJumpTable(num_wasm_functions);
    // See comment above for the size computation.
    int far_jump_table_size =
        is_first_code_space
            ? JumpTableAssembler::SizeForNumberOfFarJumpSlots(
                  BuiltinLookup::BuiltinCount(), num_function_slots)
            : main_far_jump_table_->instructions_size_;
    far_jump_table = CreateEmptyJumpTableInRegionLocked(
        far_jump_table_size, region, JumpTableType::kFarJumpTable);
    CHECK(region.contains(far_jump_table->instruction_start()));
    EmbeddedData embedded_data = EmbeddedData::FromBlob();
    static_assert(Builtins::kAllBuiltinsAreIsolateIndependent);
    Address builtin_addresses[BuiltinLookup::BuiltinCount()];
    for (int i = 0; i < BuiltinLookup::BuiltinCount(); ++i) {
      builtin_addresses[i] = embedded_data.InstructionStartOf(
          BuiltinLookup::BuiltinForJumptableIndex(i));
    }
    WritableJitAllocation jit_allocation = ThreadIsolation::LookupJitAllocation(
        far_jump_table->instruction_start(), far_jump_table->instructions_size_,
        ThreadIsolation::JitAllocationType::kWasmFarJumpTable);
    JumpTableAssembler::GenerateFarJumpTable(
        jit_allocation, far_jump_table->instruction_start(), builtin_addresses,
        BuiltinLookup::BuiltinCount(), num_function_slots);
  }
  if (is_first_code_space) {
    // This can be updated and accessed without locks, since the addition of the
    // first code space happens during initialization of the {NativeModule},
    // where no concurrent accesses are possible.
    main_jump_table_ = jump_table;
    main_far_jump_table_ = far_jump_table;
  }
  code_space_data_.push_back(CodeSpaceData{region, jump_table, far_jump_table});
  if (is_first_code_space) {
    InitializeJumpTableForLazyCompilation(num_wasm_functions);
  }
  if (jump_table && !is_first_code_space) {
    // Patch the new jump table(s) with existing functions. If this is the first
    // code space, there cannot be any functions that have been compiled yet.
    const CodeSpaceData& new_code_space_data = code_space_data_.back();
    // TODO(sroettger): need to create two write scopes? Or have a write scope
    // for multiple allocations.
    WritableJumpTablePair writable_jump_tables =
        ThreadIsolation::LookupJumpTableAllocations(
            new_code_space_data.jump_table->instruction_start(),
            new_code_space_data.jump_table->instructions_size_,
            new_code_space_data.far_jump_table->instruction_start(),
            new_code_space_data.far_jump_table->instructions_size_);
    for (uint32_t slot_index = 0; slot_index < num_wasm_functions;
         ++slot_index) {
      if (code_table_[slot_index]) {
        PatchJumpTableLocked(writable_jump_tables, new_code_space_data,
                             slot_index,
                             code_table_[slot_index]->instruction_start());
      } else if (lazy_compile_table_) {
        // Use the main jump table as the target so that we don't have to add a
        // landing pad instruction to the lazy compile table entries.
        Address main_jump_table_target =
            main_jump_table_->instruction_start() +
            JumpTableAssembler::JumpSlotIndexToOffset(slot_index);
        PatchJumpTableLocked(writable_jump_tables, new_code_space_data,
                             slot_index, main_jump_table_target);
      }
    }
  }
}
References allocation_mutex_, v8::base::RecursiveMutex::AssertHeld(), v8::internal::wasm::BuiltinLookup::BuiltinCount(), v8::internal::wasm::BuiltinLookup::BuiltinForJumptableIndex(), CHECK, code_space_data_, code_table_, v8::base::AddressRegion::contains(), CreateEmptyJumpTableInRegionLocked(), DCHECK_GE, DCHECK_LT, v8::internal::wasm::NativeModule::CodeSpaceData::far_jump_table, FindJumpTablesForRegionLocked(), v8::internal::EmbeddedData::FromBlob(), v8::internal::wasm::JumpTableAssembler::GenerateFarJumpTable(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, InitializeJumpTableForLazyCompilation(), v8::internal::wasm::WasmCode::instruction_start(), v8::internal::wasm::WasmCode::instructions_size_, v8::internal::EmbeddedData::InstructionStartOf(), v8::internal::wasm::NativeModule::JumpTablesRef::is_valid(), v8::internal::wasm::NativeModule::CodeSpaceData::jump_table, v8::internal::wasm::JumpTableAssembler::JumpSlotIndexToOffset(), v8::internal::Builtins::kAllBuiltinsAreIsolateIndependent, kFarJumpTable, kJumpTable, v8::internal::ThreadIsolation::kWasmFarJumpTable, lazy_compile_table_, v8::internal::ThreadIsolation::LookupJitAllocation(), main_far_jump_table_, main_jump_table_, module(), module_, num_declared_functions(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::NumWasmFunctionsInFarJumpTable(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::OverheadPerCodeSpace(), PatchJumpTableLocked(), v8::base::AddressRegion::size(), v8::internal::wasm::JumpTableAssembler::SizeForNumberOfFarJumpSlots(), and v8::internal::wasm::JumpTableAssembler::SizeForNumberOfSlots().
Referenced by v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), and NativeModule().
AddCodeWithCodeSpace()
std::unique_ptr< WasmCode > v8::internal::wasm::NativeModule::AddCodeWithCodeSpace (int index, const CodeDesc & desc, int stack_slots, int ool_spill_count, uint32_t tagged_parameter_slots, base::Vector< const uint8_t > protected_instructions_data, base::Vector< const uint8_t > source_position_table, base::Vector< const uint8_t > inlining_positions, base::Vector< const uint8_t > deopt_data, WasmCode::Kind kind, ExecutionTier tier, ForDebugging for_debugging, bool frame_has_feedback_slot, base::Vector< uint8_t > code_space, const JumpTablesRef & jump_tables_ref) [private]
Definition at line 1320 of file wasm-code-manager.cc.
                                      {
  base::Vector<uint8_t> reloc_info{
      desc.buffer + desc.buffer_size - desc.reloc_size,
      static_cast<size_t>(desc.reloc_size)};
  UpdateCodeSize(desc.instr_size, tier, for_debugging);
  // TODO(jgruber,v8:8758): Remove this translation. It exists only because
  // CodeDesc contains real offsets but WasmCode expects an offset of 0 to mean
  // 'empty'.
  const int safepoint_table_offset =
      desc.safepoint_table_size == 0 ? 0 : desc.safepoint_table_offset;
  const int handler_table_offset = desc.handler_table_offset;
  const int constant_pool_offset = desc.constant_pool_offset;
  const int code_comments_offset = desc.code_comments_offset;
  const int jump_table_info_offset = desc.jump_table_info_offset;
  const int instr_size = desc.instr_size;
  {
    WritableJitAllocation jit_allocation = ThreadIsolation::LookupJitAllocation(
        reinterpret_cast<Address>(dst_code_bytes.begin()),
        dst_code_bytes.size(), ThreadIsolation::JitAllocationType::kWasmCode,
        true);
    jit_allocation.CopyCode(0, desc.buffer, desc.instr_size);
    // Apply the relocation delta by iterating over the RelocInfo.
    intptr_t delta = dst_code_bytes.begin() - desc.buffer;
    int mode_mask =
        RelocInfo::kApplyMask | RelocInfo::ModeMask(RelocInfo::WASM_CALL) |
        RelocInfo::ModeMask(RelocInfo::WASM_STUB_CALL) |
        RelocInfo::ModeMask(RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY);
    Address code_start = reinterpret_cast<Address>(dst_code_bytes.begin());
    Address constant_pool_start = code_start + constant_pool_offset;
    for (WritableRelocIterator it(jit_allocation, dst_code_bytes, reloc_info,
                                  constant_pool_start, mode_mask);
         !it.done(); it.next()) {
      RelocInfo::Mode mode = it.rinfo()->rmode();
      if (RelocInfo::IsWasmCall(mode)) {
        uint32_t call_tag = it.rinfo()->wasm_call_tag();
        Address target = GetNearCallTargetForFunction(call_tag, jump_tables);
        it.rinfo()->set_wasm_call_address(target);
      } else if (RelocInfo::IsWasmStubCall(mode)) {
        uint32_t stub_call_tag = it.rinfo()->wasm_call_tag();
        DCHECK_LT(stub_call_tag,
                  static_cast<uint32_t>(Builtin::kFirstBytecodeHandler));
        Builtin builtin = static_cast<Builtin>(stub_call_tag);
        Address entry = GetJumpTableEntryForBuiltin(builtin, jump_tables);
        it.rinfo()->set_wasm_stub_call_address(entry);
      } else if (RelocInfo::IsWasmCodePointerTableEntry(mode)) {
        uint32_t function_index =
            it.rinfo()->wasm_code_pointer_table_entry().value();
        WasmCodePointer target = GetCodePointerHandle(function_index);
        it.rinfo()->set_wasm_code_pointer_table_entry(target,
                                                      SKIP_ICACHE_FLUSH);
      } else {
        it.rinfo()->apply(delta);
      }
    }
  }
  // Flush the i-cache after relocation.
  FlushInstructionCache(dst_code_bytes.begin(), dst_code_bytes.size());
  // Liftoff code will not be relocated or serialized, thus do not store any
  // relocation information.
  if (tier == ExecutionTier::kLiftoff) reloc_info = {};
  uint64_t signature_hash =
      module_->signature_hash(GetTypeCanonicalizer(), index);
  std::unique_ptr<WasmCode> code{new WasmCode{this,
                                              index,
                                              dst_code_bytes,
                                              stack_slots,
                                              ool_spill_count,
                                              tagged_parameter_slots,
                                              safepoint_table_offset,
                                              handler_table_offset,
                                              constant_pool_offset,
                                              code_comments_offset,
                                              jump_table_info_offset,
                                              instr_size,
                                              protected_instructions_data,
                                              reloc_info,
                                              source_position_table,
                                              inlining_positions,
                                              deopt_data,
                                              kind,
                                              tier,
                                              for_debugging,
                                              signature_hash,
                                              frame_has_feedback_slot}};
  code->MaybePrint();
  code->Validate();
  return code;
}
References v8::base::Vector< T >::begin(), v8::internal::CodeDesc::buffer, v8::internal::CodeDesc::buffer_size, code, v8::internal::CodeDesc::code_comments_offset, v8::internal::CodeDesc::constant_pool_offset, v8::internal::WritableJitAllocation::CopyCode(), DCHECK_LT, v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::FlushInstructionCache(), GetCodePointerHandle(), GetJumpTableEntryForBuiltin(), GetNearCallTargetForFunction(), v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::CodeDesc::handler_table_offset, v8::internal::index, v8::internal::CodeDesc::instr_size, v8::internal::RelocInfo::IsWasmCall(), v8::internal::RelocInfo::IsWasmCodePointerTableEntry(), v8::internal::RelocInfo::IsWasmStubCall(), v8::internal::CodeDesc::jump_table_info_offset, v8::internal::RelocInfo::kApplyMask, v8::internal::wasm::kLiftoff, v8::internal::ThreadIsolation::kWasmCode, v8::internal::ThreadIsolation::LookupJitAllocation(), mode(), v8::internal::RelocInfo::ModeMask(), module_, v8::internal::CodeDesc::reloc_size, v8::internal::CodeDesc::safepoint_table_offset, v8::internal::CodeDesc::safepoint_table_size, v8::base::Vector< T >::size(), v8::internal::SKIP_ICACHE_FLUSH, UpdateCodeSize(), v8::internal::RelocInfo::WASM_CALL, v8::internal::RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY, and v8::internal::RelocInfo::WASM_STUB_CALL.
Referenced by AddCode(), and AddCompiledCode().
AddCompiledCode() [1/2]
std::vector< UnpublishedWasmCode > v8::internal::wasm::NativeModule::AddCompiledCode (base::Vector< WasmCompilationResult > results)
Definition at line 2642 of file wasm-code-manager.cc.
                                               {
  TRACE_EVENT1(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
               "wasm.AddCompiledCode", "num", results.size());
  DCHECK(!results.empty());
  std::vector<UnpublishedWasmCode> generated_code;
  generated_code.reserve(results.size());
  // First, allocate code space for all the results.
  // Never add more than half of a code space at once. This leaves some space
  // for jump tables and other overhead. We could use {OverheadPerCodeSpace},
  // but that's only an approximation, so we are conservative here and never use
  // more than half a code space.
  size_t max_code_batch_size = v8_flags.wasm_max_code_space_size_mb * MB / 2;
  size_t total_code_space = 0;
  for (auto& result : results) {
    DCHECK(result.succeeded());
    size_t new_code_space =
        RoundUp<kCodeAlignment>(result.code_desc.instr_size);
    if (total_code_space + new_code_space > max_code_batch_size) {
      // Split off the first part of the {results} vector and process it
      // separately. This method then continues with the rest.
      size_t split_point = &result - results.begin();
      if (split_point == 0) {
        // Fuzzers sometimes hit this by reducing --wasm-max-code-sapce-size-mb
        // to an unreasonably small value. Make this an OOM to avoid getting a
        // CHECK failure in this case.
        if (v8_flags.wasm_max_code_space_size_mb <
            kDefaultMaxWasmCodeSpaceSizeMb / 10) {
          auto oom_detail = base::FormattedString{}
                            << "--wasm-max-code-space-size="
                            << v8_flags.wasm_max_code_space_size_mb.value();
          V8::FatalProcessOutOfMemory(nullptr,
                                      "A single code object needs more than "
                                      "half of the code space size",
                                      oom_detail.PrintToArray().data());
        } else {
          // Otherwise make this a CHECK failure so we see if this is happening
          // in the wild or in tests.
          FATAL(
              "A single code object needs more than half of the code space "
              "size");
        }
      }
      auto first_results = AddCompiledCode(results.SubVector(0, split_point));
      generated_code.insert(generated_code.end(),
                            std::make_move_iterator(first_results.begin()),
                            std::make_move_iterator(first_results.end()));
      // Continue processing the rest of the vector. This change to the
      // {results} vector does not invalidate iterators (which are just
      // pointers). In particular, the end pointer stays the same.
      results += split_point;
      total_code_space = 0;
    }
    total_code_space += new_code_space;
  }
  base::Vector<uint8_t> code_space;
  NativeModule::JumpTablesRef jump_tables;
  {
    base::RecursiveMutexGuard guard{&allocation_mutex_};
    code_space = code_allocator_.AllocateForCode(this, total_code_space);
    // Lookup the jump tables to use once, then use for all code objects.
    jump_tables =
        FindJumpTablesForRegionLocked(base::AddressRegionOf(code_space));
  }
  // If we happen to have a {total_code_space} which is bigger than
  // {kMaxCodeSpaceSize}, we would not find valid jump tables for the whole
  // region. If this ever happens, we need to handle this case (by splitting the
  // {results} vector in smaller chunks).
  CHECK(jump_tables.is_valid());
  std::vector<size_t> sizes;
  for (const auto& result : results) {
    sizes.emplace_back(RoundUp<kCodeAlignment>(result.code_desc.instr_size));
  }
  ThreadIsolation::RegisterJitAllocations(
      reinterpret_cast<Address>(code_space.begin()), sizes,
      ThreadIsolation::JitAllocationType::kWasmCode);
  // Now copy the generated code into the code space and relocate it.
  for (auto& result : results) {
    DCHECK_EQ(result.code_desc.buffer, result.instr_buffer->start());
    size_t code_size = RoundUp<kCodeAlignment>(result.code_desc.instr_size);
    base::Vector<uint8_t> this_code_space = code_space.SubVector(0, code_size);
    code_space += code_size;
    generated_code.emplace_back(
        AddCodeWithCodeSpace(
            result.func_index, result.code_desc, result.frame_slot_count,
            result.ool_spill_count, result.tagged_parameter_slots,
            result.protected_instructions_data.as_vector(),
            result.source_positions.as_vector(),
            result.inlining_positions.as_vector(),
            result.deopt_data.as_vector(), GetCodeKind(result),
            result.result_tier, result.for_debugging,
            result.frame_has_feedback_slot, this_code_space, jump_tables),
        std::move(result.assumptions));
  }
  DCHECK_EQ(0, code_space.size());
  // Check that we added the expected amount of code objects, even if we split
  // the {results} vector.
  DCHECK_EQ(generated_code.capacity(), generated_code.size());
  return generated_code;
}
References AddCodeWithCodeSpace(), AddCompiledCode(), v8::base::AddressRegionOf(), v8::internal::wasm::WasmCodeAllocator::AllocateForCode(), allocation_mutex_, v8::base::Vector< T >::begin(), CHECK, code_allocator_, v8::internal::DCHECK(), DCHECK_EQ, v8::base::Vector< T >::empty(), FATAL, v8::internal::V8::FatalProcessOutOfMemory(), FindJumpTablesForRegionLocked(), v8::internal::wasm::GetCodeKind(), v8::internal::wasm::NativeModule::JumpTablesRef::is_valid(), v8::internal::kDefaultMaxWasmCodeSpaceSizeMb, v8::internal::ThreadIsolation::kWasmCode, v8::internal::MB, v8::internal::ThreadIsolation::RegisterJitAllocations(), v8::base::internal::result, v8::base::Vector< T >::size(), v8::base::Vector< T >::SubVector(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT1, and v8::internal::v8_flags.
AddCompiledCode() [2/2]
UnpublishedWasmCode v8::internal::wasm::NativeModule::AddCompiledCode (WasmCompilationResult & result)
Definition at line 2636 of file wasm-code-manager.cc.
                                   {
  std::vector<UnpublishedWasmCode> code = AddCompiledCode({&result, 1});
  return std::move(code[0]);
}
References code, and v8::base::internal::result.
Referenced by AddCompiledCode(), v8::internal::wasm::CompileLazy(), v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits().
AddDeserializedCode()
std::unique_ptr< WasmCode > v8::internal::wasm::NativeModule::AddDeserializedCode (int index, base::Vector< uint8_t > instructions, int stack_slots, int ool_spills, uint32_t tagged_parameter_slots, int safepoint_table_offset, int handler_table_offset, int constant_pool_offset, int code_comments_offset, int jump_table_info_offset, int unpadded_binary_size, base::Vector< const uint8_t > protected_instructions_data, base::Vector< const uint8_t > reloc_info, base::Vector< const uint8_t > source_position_table, base::Vector< const uint8_t > inlining_positions, base::Vector< const uint8_t > deopt_data, WasmCode::Kind kind, ExecutionTier tier)
Definition at line 1625 of file wasm-code-manager.cc.
                        {
  UpdateCodeSize(instructions.size(), tier, kNotForDebugging);
  uint64_t signature_hash =
      module_->signature_hash(GetTypeCanonicalizer(), index);
  return std::unique_ptr<WasmCode>{new WasmCode{this,
                                                index,
                                                instructions,
                                                stack_slots,
                                                ool_spills,
                                                tagged_parameter_slots,
                                                safepoint_table_offset,
                                                handler_table_offset,
                                                constant_pool_offset,
                                                code_comments_offset,
                                                jump_table_info_offset,
                                                unpadded_binary_size,
                                                protected_instructions_data,
                                                reloc_info,
                                                source_position_table,
                                                inlining_positions,
                                                deopt_data,
                                                kind,
                                                tier,
                                                kNotForDebugging,
                                                signature_hash}};
}
References v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::index, v8::internal::wasm::kNotForDebugging, module_, v8::base::Vector< T >::size(), and UpdateCodeSize().
Referenced by v8::internal::wasm::NativeModuleDeserializer::ReadCode().
AddLazyCompilationTimeSample()
void v8::internal::wasm::NativeModule::AddLazyCompilationTimeSample (int64_t sample)
Definition at line 1988 of file wasm-code-manager.cc.
                                                                           {
  num_lazy_compilations_.fetch_add(1, std::memory_order_relaxed);
  sum_lazy_compilation_time_in_micro_sec_.fetch_add(sample_in_micro_sec,
                                                    std::memory_order_relaxed);
  int64_t max =
      max_lazy_compilation_time_in_micro_sec_.load(std::memory_order_relaxed);
  while (sample_in_micro_sec > max &&
         !max_lazy_compilation_time_in_micro_sec_.compare_exchange_weak(
             max, sample_in_micro_sec, std::memory_order_relaxed,
             std::memory_order_relaxed)) {
    // Repeat until we set the new maximum sucessfully.
  }
}
References max_lazy_compilation_time_in_micro_sec_, num_lazy_compilations_, and sum_lazy_compilation_time_in_micro_sec_.
AddLiftoffBailout()
void v8::internal::wasm::NativeModule::AddLiftoffBailout () [inline]
Definition at line 822 of file wasm-code-manager.h.
                           {
    liftoff_bailout_count_.fetch_add(1, std::memory_order_relaxed);
  }
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits().
AllocateForDeserializedCode()
std::pair< base::Vector< uint8_t >, NativeModule::JumpTablesRef > v8::internal::wasm::NativeModule::AllocateForDeserializedCode (size_t total_code_size)
Definition at line 1616 of file wasm-code-manager.cc.
                                                                {
  base::RecursiveMutexGuard guard{&allocation_mutex_};
  base::Vector<uint8_t> code_space =
      code_allocator_.AllocateForCode(this, total_code_size);
  auto jump_tables =
      FindJumpTablesForRegionLocked(base::AddressRegionOf(code_space));
  return {code_space, jump_tables};
}
References v8::base::AddressRegionOf(), v8::internal::wasm::WasmCodeAllocator::AllocateForCode(), allocation_mutex_, code_allocator_, and FindJumpTablesForRegionLocked().
Referenced by v8::internal::wasm::NativeModuleDeserializer::ReadCode().
committed_code_space()
size_t v8::internal::wasm::NativeModule::committed_code_space () const [inline]
Definition at line 768 of file wasm-code-manager.h.
                                      {
    return code_allocator_.committed_code_space();
  }
Referenced by v8::internal::WasmModuleObject::New().
compilation_state()
CompilationState* v8::internal::wasm::NativeModule::compilation_state () const [inline]
Definition at line 748 of file wasm-code-manager.h.
                                              {
    return compilation_state_.get();
  }
Referenced by v8::internal::wasm::CompileLazy(), v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::InitializeCompilation(), v8::internal::wasm::InitializeCompilationForTesting(), v8::internal::wasm::NativeModuleDeserializer::ReadHeader(), v8::internal::wasm::ThrowLazyCompilationError(), v8::internal::wasm::TierUpNowForTesting(), v8::internal::wasm::TriggerTierUp(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateFunctions(), and v8::internal::wasm::NativeModuleSerializer::WriteHeader().
compile_imports()
const CompileTimeImports& v8::internal::wasm::NativeModule::compile_imports () const [inline]
Definition at line 829 of file wasm-code-manager.h.
{ return compile_imports_; }
Referenced by v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction(), v8::internal::wasm::NativeModuleCache::Erase(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits(), v8::internal::wasm::GetImports(), v8::internal::wasm::NativeModuleSerializer::Measure(), v8::internal::wasm::NativeModuleDeserializer::Read(), v8::internal::wasm::InstanceBuilder::SanitizeImports(), and v8::internal::wasm::NativeModuleSerializer::WriteHeader().
counters()
Counters* v8::internal::wasm::NativeModule::counters () const [inline]
Definition at line 890 of file wasm-code-manager.h.
{ return code_allocator_.counters(); }
Referenced by SampleCodeSize().
coverage_data()
const std::shared_ptr<WasmModuleCoverageData>& v8::internal::wasm::NativeModule::coverage_data () const [inline]
Definition at line 962 of file wasm-code-manager.h.
                                                                     {
    return coverage_data_;
  }
Referenced by v8::internal::wasm::CompilationEnv::ForModule().
CreateEmptyJumpTableInRegionLocked()
WasmCode * v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegionLocked (int jump_table_size, base::AddressRegion region, JumpTableType type) [private]
Definition at line 1740 of file wasm-code-manager.cc.
                                                                       {
  allocation_mutex_.AssertHeld();
  // Only call this if we really need a jump table.
  DCHECK_LT(0, jump_table_size);
  base::Vector<uint8_t> code_space =
      code_allocator_.AllocateForCodeInRegion(this, jump_table_size, region);
  DCHECK(!code_space.empty());
  UpdateCodeSize(jump_table_size, ExecutionTier::kNone, kNotForDebugging);
  {
    WritableJitAllocation jit_allocation =
        ThreadIsolation::RegisterJitAllocation(
            reinterpret_cast<Address>(code_space.begin()), code_space.size(),
            ToAllocationType(type));
    jit_allocation.ClearBytes(0, code_space.size());
  }
  std::unique_ptr<WasmCode> code{
      new WasmCode{this, // native_module
                   kAnonymousFuncIndex, // index
                   code_space, // instructions
                   0, // stack_slots
                   0, // ool_spills
                   0, // tagged_parameter_slots
                   0, // safepoint_table_offset
                   jump_table_size, // handler_table_offset
                   jump_table_size, // constant_pool_offset
                   jump_table_size, // code_comments_offset
                   jump_table_size, // jump_table_info_offset
                   jump_table_size, // unpadded_binary_size
                   {}, // protected_instructions
                   {}, // reloc_info
                   {}, // source_pos
                   {}, // inlining pos
                   {}, // deopt data
                   WasmCode::kJumpTable, // kind
                   ExecutionTier::kNone, // tier
                   kNotForDebugging, // for_debugging
                   0}}; // signature_hash
  return PublishCodeLocked(std::move(code),
                           UnpublishedWasmCode::kNoAssumptions);
}
References v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), allocation_mutex_, v8::base::RecursiveMutex::AssertHeld(), v8::base::Vector< T >::begin(), v8::internal::WritableJitAllocation::ClearBytes(), code, code_allocator_, v8::internal::DCHECK(), DCHECK_LT, v8::base::Vector< T >::empty(), v8::internal::wasm::kAnonymousFuncIndex, v8::internal::wasm::WasmCode::kJumpTable, v8::internal::wasm::UnpublishedWasmCode::kNoAssumptions, v8::internal::wasm::kNone, v8::internal::wasm::kNotForDebugging, PublishCodeLocked(), v8::internal::ThreadIsolation::RegisterJitAllocation(), v8::base::Vector< T >::size(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::ToAllocationType(), v8::internal::tracing::type, and UpdateCodeSize().
Referenced by AddCodeSpaceLocked(), and CreateEmptyJumpTableLocked().
CreateEmptyJumpTableLocked()
WasmCode * v8::internal::wasm::NativeModule::CreateEmptyJumpTableLocked (int jump_table_size, JumpTableType type) [private]
Definition at line 1718 of file wasm-code-manager.cc.
                                                                       {
  return CreateEmptyJumpTableInRegionLocked(jump_table_size,
                                            kUnrestrictedRegion, type);
}
References CreateEmptyJumpTableInRegionLocked(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kUnrestrictedRegion, and v8::internal::tracing::type.
Referenced by InitializeJumpTableForLazyCompilation().
CreateIndirectCallTargetToFunctionIndexMap()
NativeModule::CallIndirectTargetMap v8::internal::wasm::NativeModule::CreateIndirectCallTargetToFunctionIndexMap () const
Definition at line 2114 of file wasm-code-manager.cc.
                                                               {
  CallIndirectTargetMap lookup_map;
  for (uint32_t func_index = num_imported_functions();
       func_index < num_functions(); func_index++) {
    lookup_map.emplace(GetCodePointerHandle(func_index), func_index);
  }
  return lookup_map;
}
References GetCodePointerHandle(), num_functions(), and num_imported_functions().
Referenced by v8::internal::wasm::WasmCode::Validate(), and v8::internal::wasm::NativeModuleSerializer::Write().
DisableCodeLogging()
void v8::internal::wasm::NativeModule::DisableCodeLogging () [inline]
Definition at line 901 of file wasm-code-manager.h.
                            {
    log_code_.store(false, std::memory_order_relaxed);
  }
Referenced by v8::internal::wasm::WasmEngine::DisableCodeLogging().
DisassembleForLcov()
uint32_t v8::internal::wasm::NativeModule::DisassembleForLcov (std::ostream & out, std::vector< int > & function_body_offsets, std::map< uint32_t, uint32_t > & bytecode_disasm_offsets)
Definition at line 988 of file wasm-code-manager.cc.
                                                         {
  CoverageFileWriter coverage_file_writer(out, bytecode_disasm_offsets);
  debug::Disassemble(wire_bytes(), &coverage_file_writer,
                     &function_body_offsets);
  return coverage_file_writer.GetLineCount();
}
References v8::internal::wasm::Disassemble(), and wire_bytes().
EnableCodeLogging()
void v8::internal::wasm::NativeModule::EnableCodeLogging () [inline]
Definition at line 899 of file wasm-code-manager.h.
{ log_code_.store(true, std::memory_order_relaxed); }
Referenced by v8::internal::wasm::WasmEngine::EnableCodeLogging().
enabled_features()
WasmEnabledFeatures v8::internal::wasm::NativeModule::enabled_features () const [inline]
Definition at line 828 of file wasm-code-manager.h.
{ return enabled_features_; }
Referenced by v8::internal::wasm::CompileLazy(), v8::internal::wasm::CompilationEnv::ForModule(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetLazyCompilationTiers(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgress(), v8::internal::wasm::WasmSerializer::SerializeNativeModule(), v8::internal::wasm::ThrowLazyCompilationError(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ValidateFunctionNowIfNeeded(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateFunctions().
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::NativeModule::EstimateCurrentMemoryConsumption () const
Definition at line 2867 of file wasm-code-manager.cc.
                                                            {
  UPDATE_WHEN_CLASS_CHANGES(NativeModule, 472);
  size_t result = sizeof(NativeModule);
  result += module_->EstimateCurrentMemoryConsumption();
  std::shared_ptr<base::OwnedVector<const uint8_t>> wire_bytes =
      std::atomic_load(&wire_bytes_);
  size_t wire_bytes_size = wire_bytes ? wire_bytes->size() : 0;
  result += wire_bytes_size;
  if (source_map_) {
    result += source_map_->EstimateCurrentMemoryConsumption();
  }
  result += compilation_state_->EstimateCurrentMemoryConsumption();
  // For {tiering_budgets_}.
  result += module_->num_declared_functions * sizeof(uint32_t);
  size_t external_storage = compile_imports_.constants_module().capacity();
  // This is an approximation: the actual number of inline-stored characters
  // is a little less than the result of `sizeof`.
  if (external_storage > sizeof(std::string)) {
    result += external_storage;
  }
  // For fast api call targets.
  result += module_->num_imported_functions *
            (sizeof(std::atomic<Address>) + sizeof(CFunctionInfo*));
  // We cannot hold the `allocation_mutex_` while calling
  // `debug_info_->EstimateCurrentMemoryConsumption`, as we would run into a
  // lock-order-inversion when acquiring the `mutex_`. The reverse order happens
  // when calling `WasmScript::SetBreakPointForFunction`.
  DebugInfo* debug_info;
  {
    base::RecursiveMutexGuard lock(&allocation_mutex_);
    result += ContentSize(owned_code_);
    for (auto& [address, unique_code_ptr] : owned_code_) {
      result += unique_code_ptr->EstimateCurrentMemoryConsumption();
    }
    result += ContentSize(new_owned_code_);
    for (std::unique_ptr<WasmCode>& code : new_owned_code_) {
      result += code->EstimateCurrentMemoryConsumption();
    }
    // For {code_table_}.
    result += module_->num_declared_functions * sizeof(void*);
    result += ContentSize(code_space_data_);
    debug_info = debug_info_.get();
    if (names_provider_) {
      result += names_provider_->EstimateCurrentMemoryConsumption();
    }
  }
  if (debug_info) {
    result += debug_info->EstimateCurrentMemoryConsumption();
  }
  if (v8_flags.trace_wasm_offheap_memory) {
    PrintF("NativeModule wire bytes: %zu\n", wire_bytes_size);
    PrintF("NativeModule: %zu\n", result);
  }
  return result;
}
References allocation_mutex_, code, code_space_data_, compilation_state_, compile_imports_, v8::internal::wasm::CompileTimeImports::constants_module(), v8::internal::wasm::ContentSize(), debug_info_, v8::internal::wasm::DebugInfo::EstimateCurrentMemoryConsumption(), module_, names_provider_, NativeModule(), new_owned_code_, owned_code_, v8::internal::PrintF(), v8::base::internal::result, v8::base::Vector< T >::size(), source_map_, v8::internal::string, UPDATE_WHEN_CLASS_CHANGES, v8::internal::v8_flags, wire_bytes(), and wire_bytes_.
Referenced by PrintCurrentMemoryConsumptionEstimate(), and SampleCodeSize().
fast_api_signatures()
std::atomic<const MachineSignature*>* v8::internal::wasm::NativeModule::fast_api_signatures () const [inline]
Definition at line 956 of file wasm-code-manager.h.
                                                                  {
    return fast_api_signatures_.get();
  }
Referenced by v8::internal::wasm::CompilationEnv::ForModule().
fast_api_targets()
std::atomic<Address>* v8::internal::wasm::NativeModule::fast_api_targets () const [inline]
Definition at line 940 of file wasm-code-manager.h.
                                               {
    return fast_api_targets_.get();
  }
Referenced by v8::internal::wasm::CompilationEnv::ForModule().
FindJumpTablesForRegionLocked()
NativeModule::JumpTablesRef v8::internal::wasm::NativeModule::FindJumpTablesForRegionLocked (base::AddressRegion code_region) const [private]
Definition at line 2039 of file wasm-code-manager.cc.
                                         {
  allocation_mutex_.AssertHeld();
  auto jump_table_usable = [code_region](const WasmCode* jump_table) {
    // We only ever need to check for suitable jump tables if
    // {kNeedsFarJumpsBetweenCodeSpaces} is true.
    if constexpr (!kNeedsFarJumpsBetweenCodeSpaces) UNREACHABLE();
    Address table_start = jump_table->instruction_start();
    Address table_end = table_start + jump_table->instructions().size();
    // Compute the maximum distance from anywhere in the code region to anywhere
    // in the jump table, avoiding any underflow.
    size_t max_distance = std::max(
        code_region.end() > table_start ? code_region.end() - table_start : 0,
        table_end > code_region.begin() ? table_end - code_region.begin() : 0);
    // kDefaultMaxWasmCodeSpaceSizeMb is <= the maximum near call distance on
    // the current platform.
    // We can allow a max_distance that is equal to
    // kDefaultMaxWasmCodeSpaceSizeMb, because every call or jump will target an
    // address *within* the region, but never exactly the end of the region. So
    // all occuring offsets are actually smaller than max_distance.
    return max_distance <= kDefaultMaxWasmCodeSpaceSizeMb * MB;
  };
  for (auto& code_space_data : code_space_data_) {
    DCHECK_IMPLIES(code_space_data.jump_table, code_space_data.far_jump_table);
    if (!code_space_data.far_jump_table) continue;
    // Only return these jump tables if they are reachable from the whole
    // {code_region}.
    if (kNeedsFarJumpsBetweenCodeSpaces &&
        (!jump_table_usable(code_space_data.far_jump_table) ||
         (code_space_data.jump_table &&
          !jump_table_usable(code_space_data.jump_table)))) {
      continue;
    }
    return {code_space_data.jump_table
                ? code_space_data.jump_table->instruction_start()
                : kNullAddress,
            code_space_data.far_jump_table->instruction_start()};
  }
  return {};
}
References allocation_mutex_, v8::base::RecursiveMutex::AssertHeld(), v8::base::AddressRegion::begin(), code_space_data_, DCHECK_IMPLIES, v8::base::AddressRegion::end(), v8::internal::kDefaultMaxWasmCodeSpaceSizeMb, kNeedsFarJumpsBetweenCodeSpaces, v8::internal::kNullAddress, v8::internal::MB, and v8::internal::UNREACHABLE().
Referenced by AddCode(), AddCodeForTesting(), AddCodeSpaceLocked(), AddCompiledCode(), and AllocateForDeserializedCode().
FreeCode()
void v8::internal::wasm::NativeModule::FreeCode (base::Vector< WasmCode *const > codes)
Definition at line 2820 of file wasm-code-manager.cc.
                                                             {
  base::RecursiveMutexGuard guard(&allocation_mutex_);
  // Free the code space.
  code_allocator_.FreeCode(codes);
  if (!new_owned_code_.empty()) TransferNewOwnedCodeLocked();
  DebugInfo* debug_info = debug_info_.get();
  // Free the {WasmCode} objects. This will also unregister trap handler data.
  for (WasmCode* code : codes) {
    DCHECK_EQ(1, owned_code_.count(code->instruction_start()));
    // TODO(407003348): Drop this check if it doesn't trigger in the wild.
    CHECK_EQ(WasmCode::refcount(
                 code->ref_count_bitfield_.load(std::memory_order_acquire)),
             0);
    owned_code_.erase(code->instruction_start());
  }
  // Remove debug side tables for all removed code objects, after releasing our
  // lock. This is to avoid lock order inversion.
  if (debug_info) debug_info->RemoveDebugSideTables(codes);
}
References allocation_mutex_, CHECK_EQ, code, code_allocator_, DCHECK_EQ, debug_info_, v8::internal::wasm::WasmCodeAllocator::FreeCode(), new_owned_code_, owned_code_, v8::internal::wasm::WasmCode::refcount(), v8::internal::wasm::DebugInfo::RemoveDebugSideTables(), and TransferNewOwnedCodeLocked().
Referenced by v8::internal::wasm::WasmEngine::FreeDeadCodeLocked().
FreeCodePointerTableHandles()
void v8::internal::wasm::NativeModule::FreeCodePointerTableHandles ()
Definition at line 1292 of file wasm-code-manager.cc.
                                               {
  WasmCodePointerTable* code_pointer_table =
      GetProcessWideWasmCodePointerTable();
  for (uint32_t i = 0; i < code_pointer_handles_size_; i++) {
    code_pointer_table->FreeEntry(code_pointer_handles_[i]);
  }
  code_pointer_handles_.reset();
  code_pointer_handles_size_ = 0;
}
References code_pointer_handles_, code_pointer_handles_size_, v8::internal::wasm::WasmCodePointerTable::FreeEntry(), and v8::internal::wasm::GetProcessWideWasmCodePointerTable().
Referenced by InitializeCodePointerTableHandles(), and ~NativeModule().
generated_code_size()
size_t v8::internal::wasm::NativeModule::generated_code_size () const [inline]
Definition at line 771 of file wasm-code-manager.h.
                                     {
    return code_allocator_.generated_code_size();
  }
GetBuiltinInJumptableSlot()
Builtin v8::internal::wasm::NativeModule::GetBuiltinInJumptableSlot (Address target) const
Definition at line 2123 of file wasm-code-manager.cc.
                                                                    {
  base::RecursiveMutexGuard guard(&allocation_mutex_);
  for (auto& code_space_data : code_space_data_) {
    if (code_space_data.far_jump_table != nullptr &&
        code_space_data.far_jump_table->contains(target)) {
      uint32_t offset = static_cast<uint32_t>(
          target - code_space_data.far_jump_table->instruction_start());
      uint32_t index = JumpTableAssembler::FarJumpSlotOffsetToIndex(offset);
      if (index >= BuiltinLookup::BuiltinCount()) continue;
      if (JumpTableAssembler::FarJumpSlotIndexToOffset(index) != offset) {
        continue;
      }
      return BuiltinLookup::BuiltinForJumptableIndex(index);
    }
  }
  // Invalid address.
  return Builtin::kNoBuiltinId;
}
References allocation_mutex_, v8::internal::wasm::BuiltinLookup::BuiltinCount(), v8::internal::wasm::BuiltinLookup::BuiltinForJumptableIndex(), code_space_data_, v8::internal::wasm::JumpTableAssembler::FarJumpSlotIndexToOffset(), v8::internal::wasm::JumpTableAssembler::FarJumpSlotOffsetToIndex(), v8::internal::index, and v8::internal::kNoBuiltinId.
Referenced by v8::internal::wasm::NativeModuleSerializer::WriteCode().
GetCode()
WasmCode * v8::internal::wasm::NativeModule::GetCode (uint32_t index) const
Definition at line 1691 of file wasm-code-manager.cc.
                                                    {
  base::RecursiveMutexGuard guard(&allocation_mutex_);
  WasmCode* code = code_table_[declared_function_index(module(), index)];
  if (code) WasmCodeRefScope::AddRef(code);
  return code;
}
References v8::internal::wasm::WasmCodeRefScope::AddRef(), allocation_mutex_, code, code_table_, v8::internal::wasm::declared_function_index(), v8::internal::index, and module().
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnFinishedUnits(), and v8::internal::RUNTIME_FUNCTION().
GetCodePointerHandle()
WasmCodePointer v8::internal::wasm::NativeModule::GetCodePointerHandle (int index) const
Definition at line 2144 of file wasm-code-manager.cc.
                                                                  {
  DCHECK_IMPLIES(index != kAnonymousFuncIndex, index >= 0);
  if (index == kAnonymousFuncIndex ||
      static_cast<uint32_t>(index) < module_->num_imported_functions) {
    // TODO(sroettger): do ImportWrappers need a code pointer handle?
    return kInvalidWasmCodePointer;
  }
  return code_pointer_handles_[declared_function_index(module_.get(), index)];
}
References code_pointer_handles_, DCHECK_IMPLIES, v8::internal::wasm::declared_function_index(), v8::internal::index, v8::internal::wasm::kAnonymousFuncIndex, v8::internal::wasm::kInvalidWasmCodePointer, and module_.
Referenced by AddCodeForTesting(), AddCodeWithCodeSpace(), v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate(), CreateIndirectCallTargetToFunctionIndexMap(), v8::internal::WasmTrustedInstanceData::GetCallTarget(), and v8::internal::wasm::WasmCode::Validate().
GetDebugInfo()
DebugInfo * v8::internal::wasm::NativeModule::GetDebugInfo ()
Definition at line 2851 of file wasm-code-manager.cc.
                                      {
  base::RecursiveMutexGuard guard(&allocation_mutex_);
  if (!debug_info_) debug_info_ = std::make_unique<DebugInfo>(this);
  return debug_info_.get();
}
References allocation_mutex_, and debug_info_.
Referenced by v8::internal::WasmScript::ClearBreakPoint(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmLocal(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmStackValue(), v8::internal::wasm::WasmCode::Print(), and v8::internal::WasmScript::SetBreakPointForFunction().
GetFunctionIndexFromJumpTableSlot()
uint32_t v8::internal::wasm::NativeModule::GetFunctionIndexFromJumpTableSlot (Address slot_address) const
Definition at line 2097 of file wasm-code-manager.cc.
                                {
  WasmCodeRefScope code_refs;
  WasmCode* code = Lookup(slot_address);
  DCHECK_NOT_NULL(code);
  DCHECK_EQ(WasmCode::kJumpTable, code->kind());
  uint32_t slot_offset =
      static_cast<uint32_t>(slot_address - code->instruction_start());
  uint32_t slot_idx = JumpTableAssembler::SlotOffsetToIndex(slot_offset);
  DCHECK_LT(slot_idx, module_->num_declared_functions);
  DCHECK_EQ(slot_address,
            code->instruction_start() +
                JumpTableAssembler::JumpSlotIndexToOffset(slot_idx));
  return module_->num_imported_functions + slot_idx;
}
References code, DCHECK_EQ, DCHECK_LT, DCHECK_NOT_NULL, v8::internal::wasm::JumpTableAssembler::JumpSlotIndexToOffset(), v8::internal::wasm::WasmCode::kJumpTable, Lookup(), module_, and v8::internal::wasm::JumpTableAssembler::SlotOffsetToIndex().
Referenced by v8::internal::wasm::NativeModuleSerializer::WriteCode().
GetJumpTableEntryForBuiltin()
Address v8::internal::wasm::NativeModule::GetJumpTableEntryForBuiltin (Builtin builtin, const JumpTablesRef & jump_tables) const
Definition at line 2088 of file wasm-code-manager.cc.
                                                             {
  DCHECK(jump_tables.is_valid());
  int index = BuiltinLookup::JumptableIndexForBuiltin(builtin);
  auto offset = JumpTableAssembler::FarJumpSlotIndexToOffset(index);
  return jump_tables.far_jump_table_start + offset;
}
References v8::internal::DCHECK(), v8::internal::wasm::NativeModule::JumpTablesRef::far_jump_table_start, v8::internal::wasm::JumpTableAssembler::FarJumpSlotIndexToOffset(), v8::internal::index, v8::internal::wasm::NativeModule::JumpTablesRef::is_valid(), and v8::internal::wasm::BuiltinLookup::JumptableIndexForBuiltin().
Referenced by AddCodeForTesting(), AddCodeWithCodeSpace(), and v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate().
GetNamesProvider()
NamesProvider * v8::internal::wasm::NativeModule::GetNamesProvider ()
Definition at line 2857 of file wasm-code-manager.cc.
                                              {
  DCHECK(HasWireBytes());
  base::RecursiveMutexGuard guard(&allocation_mutex_);
  if (!names_provider_) {
    names_provider_ =
        std::make_unique<NamesProvider>(module_.get(), wire_bytes());
  }
  return names_provider_.get();
}
References allocation_mutex_, v8::internal::DCHECK(), HasWireBytes(), module_, names_provider_, and wire_bytes().
Referenced by v8::internal::GetWasmFunctionDebugName(), and v8::internal::compiler::JsonPrintFunctionSource().
GetNearCallTargetForFunction()
Address v8::internal::wasm::NativeModule::GetNearCallTargetForFunction (uint32_t func_index, const JumpTablesRef & jump_tables) const
Definition at line 2081 of file wasm-code-manager.cc.
                                                                 {
  DCHECK(jump_tables.is_valid());
  uint32_t slot_offset = JumpTableOffset(module(), func_index);
  return jump_tables.jump_table_start + slot_offset;
}
References v8::internal::DCHECK(), v8::internal::wasm::NativeModule::JumpTablesRef::is_valid(), v8::internal::wasm::NativeModule::JumpTablesRef::jump_table_start, v8::internal::wasm::JumpTableOffset(), and module().
Referenced by AddCodeWithCodeSpace(), and v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate().
GetNumberOfCodeSpacesForTesting()
size_t v8::internal::wasm::NativeModule::GetNumberOfCodeSpacesForTesting () const
Definition at line 2841 of file wasm-code-manager.cc.
                                                           {
  base::RecursiveMutexGuard guard{&allocation_mutex_};
  return code_allocator_.GetNumCodeSpaces();
}
References allocation_mutex_, code_allocator_, and v8::internal::wasm::WasmCodeAllocator::GetNumCodeSpaces().
GetWasmSourceMap()
WasmModuleSourceMap * v8::internal::wasm::NativeModule::GetWasmSourceMap () const
Definition at line 1714 of file wasm-code-manager.cc.
                                                          {
  return source_map_.get();
}
References source_map_.
Referenced by v8::internal::wasm::WasmCode::LogCode().
has_fast_api_signature()
bool v8::internal::wasm::NativeModule::has_fast_api_signature (int index) [inline]
Definition at line 952 of file wasm-code-manager.h.
                                         {
    return fast_api_signatures_[index] != nullptr;
  }
References v8::internal::index.
Referenced by v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport().
HasCode()
bool v8::internal::wasm::NativeModule::HasCode (uint32_t index) const
Definition at line 1698 of file wasm-code-manager.cc.
                                               {
  base::RecursiveMutexGuard guard(&allocation_mutex_);
  return code_table_[declared_function_index(module(), index)] != nullptr;
}
References allocation_mutex_, code_table_, v8::internal::wasm::declared_function_index(), v8::internal::index, and module().
Referenced by v8::internal::RUNTIME_FUNCTION().
HasCodeWithTier()
bool v8::internal::wasm::NativeModule::HasCodeWithTier (uint32_t index, ExecutionTier tier) const
Definition at line 1703 of file wasm-code-manager.cc.
                                                                           {
  base::RecursiveMutexGuard guard(&allocation_mutex_);
  return code_table_[declared_function_index(module(), index)] != nullptr &&
         code_table_[declared_function_index(module(), index)]->tier() == tier;
}
References allocation_mutex_, code_table_, v8::internal::wasm::declared_function_index(), v8::internal::index, and module().
Referenced by v8::internal::wasm::TierUpAllForTesting().
HasDebugInfo()
bool v8::internal::wasm::NativeModule::HasDebugInfo () const
Definition at line 2846 of file wasm-code-manager.cc.
                                      {
  base::RecursiveMutexGuard guard(&allocation_mutex_);
  return debug_info_ != nullptr;
}
References allocation_mutex_, and debug_info_.
Referenced by v8::internal::wasm::WasmCode::Print().
HasWireBytes()
bool v8::internal::wasm::NativeModule::HasWireBytes () const [inline]
Definition at line 816 of file wasm-code-manager.h.
                            {
    auto wire_bytes = std::atomic_load(&wire_bytes_);
    return wire_bytes && !wire_bytes->empty();
  }
Referenced by GetNamesProvider(), and v8::internal::compiler::WasmGraphBuilder::TryWasmInlining().
InitializeCodePointerTableHandles()
void v8::internal::wasm::NativeModule::InitializeCodePointerTableHandles (uint32_t num_wasm_functions)
Definition at line 1303 of file wasm-code-manager.cc.
                                 {
  if (code_pointer_handles_size_ != 0) {
    // During testing, we might already have code pointer handles allocated.
    FreeCodePointerTableHandles();
  }
  code_pointer_handles_ =
      std::make_unique<WasmCodePointer[]>(num_wasm_functions);
  code_pointer_handles_size_ = num_wasm_functions;
  WasmCodePointerTable* code_pointer_table =
      GetProcessWideWasmCodePointerTable();
  for (uint32_t i = 0; i < num_wasm_functions; i++) {
    code_pointer_handles_[i] = code_pointer_table->AllocateUninitializedEntry();
  }
}
References v8::internal::wasm::WasmCodePointerTable::AllocateUninitializedEntry(), code_pointer_handles_, code_pointer_handles_size_, FreeCodePointerTableHandles(), v8::internal::wasm::GetProcessWideWasmCodePointerTable(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by NativeModule().
InitializeJumpTableForLazyCompilation()
void v8::internal::wasm::NativeModule::InitializeJumpTableForLazyCompilation (uint32_t num_wasm_functions)
Definition at line 1192 of file wasm-code-manager.cc.
                                 {
  if (!num_wasm_functions) return;
  allocation_mutex_.AssertHeld();
  DCHECK_NULL(lazy_compile_table_);
  lazy_compile_table_ = CreateEmptyJumpTableLocked(
      JumpTableAssembler::SizeForNumberOfLazyFunctions(num_wasm_functions),
      JumpTableType::kLazyCompileTable);
  CHECK_EQ(1, code_space_data_.size());
  const CodeSpaceData& code_space_data = code_space_data_[0];
  DCHECK_NOT_NULL(code_space_data.jump_table);
  DCHECK_NOT_NULL(code_space_data.far_jump_table);
  Address compile_lazy_address =
      code_space_data.far_jump_table->instruction_start() +
      JumpTableAssembler::FarJumpSlotIndexToOffset(
          BuiltinLookup::JumptableIndexForBuiltin(Builtin::kWasmCompileLazy));
  JumpTableAssembler::GenerateLazyCompileTable(
      lazy_compile_table_->instruction_start(), num_wasm_functions,
      module_->num_imported_functions, compile_lazy_address);
  JumpTableAssembler::InitializeJumpsToLazyCompileTable(
      code_space_data.jump_table->instruction_start(), num_wasm_functions,
      lazy_compile_table_->instruction_start());
  WasmCodePointerTable* code_pointer_table =
      GetProcessWideWasmCodePointerTable();
  WasmCodePointerTable::WriteScope write_scope(
      "Initialize WasmCodePointerTable");
  DCHECK_LE(num_wasm_functions, code_pointer_handles_size_);
  TypeCanonicalizer* type_canonicalizer = GetTypeCanonicalizer();
  for (uint32_t i = 0; i < num_wasm_functions; i++) {
    uint64_t signature_hash = module_->signature_hash(
        type_canonicalizer, module_->num_imported_functions + i);
    code_pointer_table->SetEntrypointWithWriteScope(
        code_pointer_handles_[i],
        code_space_data.jump_table->instruction_start() +
            JumpTableAssembler::JumpSlotIndexToOffset(i),
        signature_hash, write_scope);
  }
}
References allocation_mutex_, v8::base::RecursiveMutex::AssertHeld(), CHECK_EQ, code_pointer_handles_, code_pointer_handles_size_, code_space_data_, CreateEmptyJumpTableLocked(), DCHECK_LE, DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::wasm::NativeModule::CodeSpaceData::far_jump_table, v8::internal::wasm::JumpTableAssembler::FarJumpSlotIndexToOffset(), v8::internal::wasm::JumpTableAssembler::GenerateLazyCompileTable(), v8::internal::wasm::GetProcessWideWasmCodePointerTable(), v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::wasm::JumpTableAssembler::InitializeJumpsToLazyCompileTable(), v8::internal::wasm::WasmCode::instruction_start(), v8::internal::wasm::NativeModule::CodeSpaceData::jump_table, v8::internal::wasm::JumpTableAssembler::JumpSlotIndexToOffset(), v8::internal::wasm::BuiltinLookup::JumptableIndexForBuiltin(), kLazyCompileTable, lazy_compile_table_, module_, v8::internal::wasm::WasmCodePointerTable::SetEntrypointWithWriteScope(), and v8::internal::wasm::JumpTableAssembler::SizeForNumberOfLazyFunctions().
Referenced by AddCodeSpaceLocked().
IsInDebugState()
DebugState v8::internal::wasm::NativeModule::IsInDebugState () const [inline]
Definition at line 848 of file wasm-code-manager.h.
                                    {
    base::RecursiveMutexGuard lock(&allocation_mutex_);
    return debug_state_;
  }
Referenced by v8::internal::wasm::CompileLazy(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgress(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgressAfterDeserialization().
jump_table_start()
Address v8::internal::wasm::NativeModule::jump_table_start () const [inline]
Definition at line 722 of file wasm-code-manager.h.
                                   {
    return main_jump_table_ ? main_jump_table_->instruction_start()
                            : kNullAddress;
  }
References v8::internal::kNullAddress.
Referenced by v8::internal::WasmTrustedInstanceData::New().
lazy_compile_frozen()
bool v8::internal::wasm::NativeModule::lazy_compile_frozen () const [inline]
Definition at line 762 of file wasm-code-manager.h.
{ return lazy_compile_frozen_; }
Referenced by v8::internal::wasm::CompileLazy().
liftoff_bailout_count()
size_t v8::internal::wasm::NativeModule::liftoff_bailout_count () const [inline]
Definition at line 774 of file wasm-code-manager.h.
                                       {
    return liftoff_bailout_count_.load(std::memory_order_relaxed);
  }
liftoff_code_size()
size_t v8::internal::wasm::NativeModule::liftoff_code_size () const [inline]
Definition at line 777 of file wasm-code-manager.h.
                                   {
    return liftoff_code_size_.load(std::memory_order_relaxed);
  }
log_code()
bool v8::internal::wasm::NativeModule::log_code () const [inline]
Definition at line 897 of file wasm-code-manager.h.
{ return log_code_.load(std::memory_order_relaxed); }
Referenced by v8::internal::wasm::CompileLazy(), v8::internal::wasm::WasmEngine::DisableCodeLogging(), v8::internal::wasm::WasmEngine::EnableCodeLogging(), v8::internal::wasm::WasmEngine::FreeNativeModule(), v8::internal::wasm::WasmEngine::ImportNativeModule(), and v8::internal::wasm::WasmEngine::LogCode().
LogWasmCodes()
void v8::internal::wasm::NativeModule::LogWasmCodes (Isolate * isolate, Tagged< Script > script)
Definition at line 1060 of file wasm-code-manager.cc.
                                                                       {
  DisallowGarbageCollection no_gc;
  if (!WasmCode::ShouldBeLogged(isolate)) return;
  TRACE_EVENT1("v8.wasm", "wasm.LogWasmCodes", "functions",
               module_->num_declared_functions);
  Tagged<Object> url_obj = script->name();
  DCHECK(IsString(url_obj) || IsUndefined(url_obj));
  std::unique_ptr<char[]> source_url =
      IsString(url_obj) ? Cast<String>(url_obj)->ToCString()
                        : std::unique_ptr<char[]>(new char[1]{'\0'});
  // Log all owned code, not just the current entries in the code table. This
  // will also include import wrappers.
  WasmCodeRefScope code_ref_scope;
  for (auto& code : SnapshotAllOwnedCode()) {
    code->LogCode(isolate, source_url.get(), script->id());
  }
}
References code, v8::internal::DCHECK(), module_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::script, v8::internal::wasm::WasmCode::ShouldBeLogged(), SnapshotAllOwnedCode(), and TRACE_EVENT1.
Referenced by v8::internal::wasm::WasmEngine::ImportNativeModule().
Lookup()
WasmCode * v8::internal::wasm::NativeModule::Lookup (Address pc) const
Definition at line 2026 of file wasm-code-manager.cc.
                                               {
  base::RecursiveMutexGuard lock(&allocation_mutex_);
  if (!new_owned_code_.empty()) TransferNewOwnedCodeLocked();
  auto iter = owned_code_.upper_bound(pc);
  if (iter == owned_code_.begin()) return nullptr;
  --iter;
  WasmCode* candidate = iter->second.get();
  DCHECK_EQ(candidate->instruction_start(), iter->first);
  if (!candidate->contains(pc)) return nullptr;
  WasmCodeRefScope::AddRef(candidate);
  return candidate;
}
References v8::internal::wasm::WasmCodeRefScope::AddRef(), allocation_mutex_, v8::internal::wasm::WasmCode::contains(), DCHECK_EQ, v8::internal::wasm::WasmCode::instruction_start(), new_owned_code_, owned_code_, and TransferNewOwnedCodeLocked().
Referenced by GetFunctionIndexFromJumpTableSlot(), v8::internal::wasm::WasmCodeManager::LookupCode(), and v8::internal::wasm::WasmCode::Validate().
max_lazy_compilation_time_in_ms()
int64_t v8::internal::wasm::NativeModule::max_lazy_compilation_time_in_ms () const [inline]
Definition at line 796 of file wasm-code-manager.h.
                                                  {
    return max_lazy_compilation_time_in_micro_sec_.load(
               std::memory_order_relaxed) /
           1000;
  }
module()
const WasmModule* v8::internal::wasm::NativeModule::module () const [inline]
Definition at line 766 of file wasm-code-manager.h.
{ return module_.get(); }
Referenced by AddCodeSpaceLocked(), v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ApplyPgoInfoLate(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ApplyPgoInfoToInitialProgress(), v8::internal::wasm::NativeModuleSerializer::CanonicalSigIdToModuleLocalTypeId(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport(), v8::internal::WasmScript::ClearBreakPoint(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::CommitCompilationUnits(), v8::internal::wasm::WasmEngine::CompileFunction(), v8::internal::wasm::CompileLazy(), v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction(), v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate(), v8::internal::wasm::WasmCode::DebugName(), v8::internal::wasm::CanonicalTypeNamesProvider::DecodeNames(), v8::internal::wasm::NativeModuleCache::Erase(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindNextBreakablePosition(), v8::internal::wasm::CompilationEnv::ForModule(), GetCode(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetDefaultTiersPerModule(), v8::internal::wasm::GetImports(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetLazyCompilationTiers(), GetNearCallTargetForFunction(), v8::internal::Script::GetPositionInfo(), v8::internal::WasmScript::GetPossibleBreakpoints(), v8::internal::GetWasmFunctionDebugName(), HasCode(), HasCodeWithTier(), v8::internal::WasmTrustedInstanceData::InitDataSegmentArrays(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgress(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgressAfterDeserialization(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationUnitForSingleFunction(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationUnits(), v8::internal::wasm::InitializeElementSegment(), v8::internal::wasm::DebugInfoImpl::IsAtReturn(), v8::internal::wasm::DebugInfoImpl::IsFrameBlackboxed(), v8::internal::compiler::JsonPrintFunctionSource(), v8::internal::wasm::WasmCode::LogCode(), v8::internal::wasm::NativeModuleSerializer::Measure(), v8::internal::WasmModuleObject::module(), v8::internal::WasmTrustedInstanceData::module(), v8::internal::WasmTrustedInstanceData::New(), v8::internal::WasmModuleObject::New(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnFinishedUnits(), PublishCodeLocked(), v8::internal::wasm::NativeModuleDeserializer::Read(), v8::internal::wasm::NativeModuleDeserializer::ReadHeader(), v8::internal::wasm::NativeModuleDeserializer::ReadTieringBudget(), ReinstallDebugCode(), v8::internal::RUNTIME_FUNCTION(), SampleCodeSize(), v8::internal::WasmScript::SetBreakPointForFunction(), SetDebugState(), v8::internal::wasm::ThrowLazyCompilationError(), v8::internal::wasm::TierUpAllForTesting(), v8::internal::wasm::TriggerTierUp(), v8::internal::compiler::WasmGraphBuilder::TryWasmInlining(), UseLazyStubLocked(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ValidateFunctionNowIfNeeded(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateFunctions(), v8::internal::wasm::NativeModuleSerializer::WriteCode(), v8::internal::wasm::NativeModuleSerializer::WriteHeader(), and v8::internal::wasm::NativeModuleSerializer::WriteTieringBudget().
num_declared_functions()
uint32_t v8::internal::wasm::NativeModule::num_declared_functions () const [inline]
Definition at line 758 of file wasm-code-manager.h.
                                          {
    return module_->num_declared_functions;
  }
Referenced by AddCodeSpaceLocked().
num_functions()
uint32_t v8::internal::wasm::NativeModule::num_functions () const [inline]
Definition at line 752 of file wasm-code-manager.h.
                                 {
    return module_->num_declared_functions + module_->num_imported_functions;
  }
Referenced by v8::internal::wasm::CompileLazy(), v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction(), CreateIndirectCallTargetToFunctionIndexMap(), v8::internal::WasmTrustedInstanceData::GetCallTarget(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnFinishedUnits(), PublishCodeLocked(), v8::internal::wasm::NativeModuleDeserializer::Read(), ReinstallDebugCode(), RemoveCompiledCode(), and SumLiftoffCodeSizeForTesting().
num_imported_functions()
uint32_t v8::internal::wasm::NativeModule::num_imported_functions () const [inline]
Definition at line 755 of file wasm-code-manager.h.
                                          {
    return module_->num_imported_functions;
  }
Referenced by v8::internal::wasm::CompileLazy(), v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction(), CreateIndirectCallTargetToFunctionIndexMap(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnFinishedUnits(), and v8::internal::wasm::NativeModuleDeserializer::Read().
num_lazy_compilations()
int v8::internal::wasm::NativeModule::num_lazy_compilations () const [inline]
Definition at line 786 of file wasm-code-manager.h.
                                    {
    return num_lazy_compilations_.load(std::memory_order_relaxed);
  }
operator=()
NativeModule& v8::internal::wasm::NativeModule::operator= (const NativeModule &) [delete]
PatchJumpTableLocked()
void v8::internal::wasm::NativeModule::PatchJumpTableLocked (WritableJumpTablePair & jump_table_pair, const CodeSpaceData & code_space_data, uint32_t slot_index, Address target) [private]
Definition at line 1815 of file wasm-code-manager.cc.
                                                                             {
  allocation_mutex_.AssertHeld();
  DCHECK_NOT_NULL(code_space_data.jump_table);
  DCHECK_NOT_NULL(code_space_data.far_jump_table);
  DCHECK_LT(slot_index, module_->num_declared_functions);
  Address jump_table_slot =
      code_space_data.jump_table->instruction_start() +
      JumpTableAssembler::JumpSlotIndexToOffset(slot_index);
  uint32_t far_jump_table_offset = JumpTableAssembler::FarJumpSlotIndexToOffset(
      BuiltinLookup::BuiltinCount() + slot_index);
  // Only pass the far jump table start if the far jump table actually has a
  // slot for this function index (i.e. does not only contain runtime stubs).
  bool has_far_jump_slot =
      far_jump_table_offset <
      code_space_data.far_jump_table->instructions().size();
  Address far_jump_table_start =
      code_space_data.far_jump_table->instruction_start();
  Address far_jump_table_slot =
      has_far_jump_slot ? far_jump_table_start + far_jump_table_offset
                        : kNullAddress;
  JumpTableAssembler::PatchJumpTableSlot(jump_table_pair, jump_table_slot,
                                         far_jump_table_slot, target);
  DCHECK_LT(slot_index, code_pointer_handles_size_);
}
References allocation_mutex_, v8::base::RecursiveMutex::AssertHeld(), v8::internal::wasm::BuiltinLookup::BuiltinCount(), code_pointer_handles_size_, DCHECK_LT, DCHECK_NOT_NULL, v8::internal::wasm::NativeModule::CodeSpaceData::far_jump_table, v8::internal::wasm::JumpTableAssembler::FarJumpSlotIndexToOffset(), v8::internal::wasm::WasmCode::instruction_start(), v8::internal::wasm::WasmCode::instructions(), v8::internal::wasm::NativeModule::CodeSpaceData::jump_table, v8::internal::wasm::JumpTableAssembler::JumpSlotIndexToOffset(), v8::internal::kNullAddress, module_, v8::internal::wasm::JumpTableAssembler::PatchJumpTableSlot(), and v8::base::Vector< T >::size().
Referenced by AddCodeSpaceLocked(), and PatchJumpTablesLocked().
PatchJumpTablesLocked()
void v8::internal::wasm::NativeModule::PatchJumpTablesLocked (uint32_t slot_index, Address target, Address code_pointer_table_target, uint64_t signature_hash) [private]
Definition at line 1791 of file wasm-code-manager.cc.
                                                                  {
  allocation_mutex_.AssertHeld();
  GetProcessWideWasmCodePointerTable()->SetEntrypointAndSignature(
      code_pointer_handles_[slot_index], code_pointer_table_target,
      signature_hash);
  for (auto& code_space_data : code_space_data_) {
    // TODO(sroettger): need to unlock both jump tables together
    DCHECK_IMPLIES(code_space_data.jump_table, code_space_data.far_jump_table);
    if (!code_space_data.jump_table) continue;
    WritableJumpTablePair writable_jump_tables =
        ThreadIsolation::LookupJumpTableAllocations(
            code_space_data.jump_table->instruction_start(),
            code_space_data.jump_table->instructions_size_,
            code_space_data.far_jump_table->instruction_start(),
            code_space_data.far_jump_table->instructions_size_);
    PatchJumpTableLocked(writable_jump_tables, code_space_data, slot_index,
                         target);
  }
}
References allocation_mutex_, v8::base::RecursiveMutex::AssertHeld(), code_pointer_handles_, code_space_data_, DCHECK_IMPLIES, v8::internal::wasm::GetProcessWideWasmCodePointerTable(), PatchJumpTableLocked(), and v8::internal::wasm::WasmCodePointerTable::SetEntrypointAndSignature().
Referenced by PublishCodeLocked(), ReinstallDebugCode(), and UseLazyStubLocked().
PrintCurrentMemoryConsumptionEstimate()
void v8::internal::wasm::NativeModule::PrintCurrentMemoryConsumptionEstimate () const
Definition at line 2928 of file wasm-code-manager.cc.
                                                               {
  DCHECK(v8_flags.print_wasm_offheap_memory_size);
  PrintF("Off-heap memory size of NativeModule: %zu\n",
         EstimateCurrentMemoryConsumption());
}
References v8::internal::DCHECK(), EstimateCurrentMemoryConsumption(), v8::internal::PrintF(), and v8::internal::v8_flags.
Referenced by ~NativeModule().
PublishCode() [1/2]
std::vector< WasmCode * > v8::internal::wasm::NativeModule::PublishCode (base::Vector< UnpublishedWasmCode > unpublished_codes)
Definition at line 1436 of file wasm-code-manager.cc.
                                                       {
  TRACE_EVENT1(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
               "wasm.PublishCode", "number", unpublished_codes.size());
  std::vector<WasmCode*> published_code;
  published_code.reserve(unpublished_codes.size());
  base::RecursiveMutexGuard lock(&allocation_mutex_);
  // The published code is put into the top-most surrounding {WasmCodeRefScope}.
  for (auto& unpublished_code : unpublished_codes) {
    WasmCode* code = PublishCodeLocked(std::move(unpublished_code.code),
                                       unpublished_code.assumptions.get());
    if (code == nullptr) {
      // There were invalid assumptions in the code.
      DCHECK_NOT_NULL(unpublished_code.assumptions);
      continue;
    }
    published_code.push_back(code);
  }
  return published_code;
}
References allocation_mutex_, code, DCHECK_NOT_NULL, PublishCodeLocked(), v8::base::Vector< T >::size(), TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT1.
PublishCode() [2/2]
WasmCode * v8::internal::wasm::NativeModule::PublishCode (UnpublishedWasmCode unpublished_code)
Definition at line 1428 of file wasm-code-manager.cc.
                                                                        {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
               "wasm.PublishCode");
  base::RecursiveMutexGuard lock(&allocation_mutex_);
  return PublishCodeLocked(std::move(unpublished_code.code),
                           unpublished_code.assumptions.get());
}
References allocation_mutex_, v8::internal::wasm::UnpublishedWasmCode::assumptions, v8::internal::wasm::UnpublishedWasmCode::code, PublishCodeLocked(), TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Referenced by v8::internal::wasm::CompileLazy(), v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction(), and v8::internal::wasm::NativeModuleDeserializer::Publish().
PublishCodeLocked()
WasmCode * v8::internal::wasm::NativeModule::PublishCodeLocked (std::unique_ptr< WasmCode > owned_code, AssumptionsJournal * assumptions) [private]
Definition at line 1485 of file wasm-code-manager.cc.
                                                                           {
  allocation_mutex_.AssertHeld();
  DCHECK_LT(owned_code->index(), num_functions());
  if (assumptions != nullptr) {
    // We should not allocate an empty set to avoid unnecessary overhead.
    DCHECK(!assumptions->empty());
    // Only Turbofan makes assumptions.
    DCHECK_EQ(ExecutionTier::kTurbofan, owned_code->tier());
    // Assumptions are not used for imports.
    DCHECK_GE(owned_code->index(),
              static_cast<int>(module_->num_imported_functions));
    WellKnownImportsList& current = module_->type_feedback.well_known_imports;
    for (auto [import_index, status] : assumptions->import_statuses()) {
      if (V8_UNLIKELY(current.get(import_index) != status)) {
        compilation_state_->AllowAnotherTopTierJob(owned_code->index());
        return nullptr;
      }
    }
  }
  WasmCode* code = owned_code.get();
  new_owned_code_.emplace_back(std::move(owned_code));
  DCHECK_NULL(owned_code);
  // Add the code to the surrounding code ref scope, so the returned pointer is
  // guaranteed to be valid.
  WasmCodeRefScope::AddRef(code);
  if (code->index() < static_cast<int>(module_->num_imported_functions)) {
    return code;
  }
  code->RegisterTrapHandlerData();
  // Assume an order of execution tiers that represents the quality of their
  // generated code.
  static_assert(ExecutionTier::kNone < ExecutionTier::kLiftoff &&
                    ExecutionTier::kLiftoff < ExecutionTier::kTurbofan,
                "Assume an order on execution tiers");
  uint32_t slot_idx = declared_function_index(module(), code->index());
  WasmCode* prior_code = code_table_[slot_idx];
  // If we are tiered down, install all debugging code (except for stepping
  // code, which is only used for a single frame and never installed in the
  // code table of jump table). Otherwise, install code if it was compiled
  // with a higher tier.
  static_assert(
      kForDebugging > kNotForDebugging && kWithBreakpoints > kForDebugging,
      "for_debugging is ordered");
  if (should_update_code_table(code, prior_code)) {
    code_table_[slot_idx] = code;
    if (prior_code) {
      WasmCodeRefScope::AddRef(prior_code);
      // The code is added to the current {WasmCodeRefScope}, hence the ref
      // count cannot drop to zero here.
      prior_code->DecRefOnLiveCode();
    }
    PatchJumpTablesLocked(slot_idx, code->instruction_start(),
                          code->instruction_start(), code->signature_hash());
  } else {
    // The code tables does not hold a reference to the code, hence decrement
    // the initial ref count of 1. The code was added to the
    // {WasmCodeRefScope} though, so it cannot die here.
    code->DecRefOnLiveCode();
  }
  return code;
}
References v8::internal::wasm::WasmCodeRefScope::AddRef(), allocation_mutex_, v8::base::RecursiveMutex::AssertHeld(), code, code_table_, compilation_state_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_LT, DCHECK_NULL, v8::internal::wasm::declared_function_index(), v8::internal::wasm::WasmCode::DecRefOnLiveCode(), v8::internal::wasm::AssumptionsJournal::empty(), v8::internal::wasm::WellKnownImportsList::get(), v8::internal::wasm::AssumptionsJournal::import_statuses(), v8::internal::wasm::kForDebugging, v8::internal::wasm::kLiftoff, v8::internal::wasm::kNone, v8::internal::wasm::kNotForDebugging, v8::internal::wasm::kTurbofan, v8::internal::wasm::kWithBreakpoints, module(), module_, new_owned_code_, num_functions(), PatchJumpTablesLocked(), should_update_code_table(), v8::internal::status, and V8_UNLIKELY.
Referenced by AddCodeForTesting(), CreateEmptyJumpTableInRegionLocked(), and PublishCode().
ReinstallDebugCode()
void v8::internal::wasm::NativeModule::ReinstallDebugCode (WasmCode * code)
Definition at line 1589 of file wasm-code-manager.cc.
                                                    {
  base::RecursiveMutexGuard lock(&allocation_mutex_);
  DCHECK_EQ(this, code->native_module());
  DCHECK_EQ(kWithBreakpoints, code->for_debugging());
  DCHECK(!code->IsAnonymous());
  DCHECK_LE(module_->num_imported_functions, code->index());
  DCHECK_LT(code->index(), num_functions());
  // If the module is tiered up by now, do not reinstall debug code.
  if (debug_state_ != kDebugging) return;
  uint32_t slot_idx = declared_function_index(module(), code->index());
  if (WasmCode* prior_code = code_table_[slot_idx]) {
    WasmCodeRefScope::AddRef(prior_code);
    // The code is added to the current {WasmCodeRefScope}, hence the ref
    // count cannot drop to zero here.
    prior_code->DecRefOnLiveCode();
  }
  code_table_[slot_idx] = code;
  code->IncRef();
  PatchJumpTablesLocked(slot_idx, code->instruction_start(),
                        code->instruction_start(), code->signature_hash());
}
References v8::internal::wasm::WasmCodeRefScope::AddRef(), allocation_mutex_, code, code_table_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, DCHECK_LT, debug_state_, v8::internal::wasm::declared_function_index(), v8::internal::wasm::kDebugging, v8::internal::wasm::kWithBreakpoints, module(), module_, num_functions(), and PatchJumpTablesLocked().
RemoveCompiledCode()
void v8::internal::wasm::NativeModule::RemoveCompiledCode (RemoveFilter filter)
Definition at line 2778 of file wasm-code-manager.cc.
                                                         {
  const uint32_t num_imports = module_->num_imported_functions;
  const uint32_t num_functions = module_->num_declared_functions;
  {
    base::RecursiveMutexGuard guard(&allocation_mutex_);
    for (uint32_t i = 0; i < num_functions; i++) {
      WasmCode* code = code_table_[i];
      if (code && ShouldRemoveCode(code, filter)) {
        code_table_[i] = nullptr;
        // Add the code to the {WasmCodeRefScope}, so the ref count cannot drop
        // to zero here. It might in the {WasmCodeRefScope} destructor, though.
        WasmCodeRefScope::AddRef(code);
        code->DecRefOnLiveCode();
        uint32_t func_index = i + num_imports;
        UseLazyStubLocked(func_index);
      }
    }
    // To avoid lock order inversion, release the {allocation_mutex_} before
    // acquiring the {type_feedback.mutex} inside {AllowAnother...} below.
  }
  // When resuming optimized execution after a debugging session ends, or when
  // discarding optimized code that made outdated assumptions, allow another
  // tier-up task to get scheduled.
  if (filter == RemoveFilter::kRemoveDebugCode ||
      filter == RemoveFilter::kRemoveTurbofanCode) {
    compilation_state_->AllowAnotherTopTierJobForAllFunctions();
  }
}
References v8::internal::wasm::WasmCodeRefScope::AddRef(), allocation_mutex_, code, code_table_, compilation_state_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kRemoveDebugCode, kRemoveTurbofanCode, module_, num_functions(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::ShouldRemoveCode(), and UseLazyStubLocked().
Referenced by UpdateWellKnownImports().
SampleCodeSize()
void v8::internal::wasm::NativeModule::SampleCodeSize (Counters * counters) const
Definition at line 2588 of file wasm-code-manager.cc.
                                                          {
  size_t code_size = code_allocator_.committed_code_space();
  int code_size_mb = static_cast<int>(code_size / MB);
#if V8_ENABLE_DRUMBRAKE
  if (v8_flags.wasm_jitless) {
    base::MutexGuard lock(&module_->interpreter_mutex_);
    if (auto interpreter = module_->interpreter_.lock()) {
      code_size_mb = static_cast<int>(interpreter->TotalBytecodeSize() / MB);
    }
  }
#endif // V8_ENABLE_DRUMBRAKE
  counters->wasm_module_code_size_mb()->AddSample(code_size_mb);
  int code_size_kb = static_cast<int>(code_size / KB);
  counters->wasm_module_code_size_kb()->AddSample(code_size_kb);
  // Record the size of metadata.
  Histogram* metadata_histogram = counters->wasm_module_metadata_size_kb();
  if (metadata_histogram->Enabled()) {
    // TODO(349610478): EstimateCurrentMemoryConsumption() acquires a large
    // amount of locks per NativeModule. This estimation is run on every
    // mark-compact GC. Reconsider whether this should be run less frequently.
    // (Probably incomplete) list of locks acquired:
    // - TypeFeedbackStorage::mutex
    // - LazilyGeneratedNames::mutex_
    // - CompilationStateImpl::mutex_
    // - CompilationUnitQueues::queues_mutex_
    // - per queue: QueueImpl::mutex
    // - BigUnitsQueue::mutex
    // - WasmImportWrapperCache::mutex_
    // - NativeModule::allocation_mutex_
    // - LazilyGeneratedNames::mutex_
    // - DebugInfoImpl::debug_side_tables_mutex_
    // - DebugInfoImpl::mutex_
    int metadata_size_kb =
        static_cast<int>(EstimateCurrentMemoryConsumption() / KB);
    metadata_histogram->AddSample(metadata_size_kb);
  }
  // If this is a wasm module of >= 2MB, also sample the freed code size,
  // absolute and relative. Code GC does not happen on asm.js
  // modules, and small modules will never trigger GC anyway.
  size_t generated_size = code_allocator_.generated_code_size();
  if (generated_size >= 2 * MB && module()->origin == kWasmOrigin) {
    size_t freed_size = code_allocator_.freed_code_size();
    DCHECK_LE(freed_size, generated_size);
    int freed_percent = static_cast<int>(100 * freed_size / generated_size);
    counters->wasm_module_freed_code_size_percent()->AddSample(freed_percent);
  }
}
References v8::internal::Histogram::AddSample(), code_allocator_, v8::internal::wasm::WasmCodeAllocator::committed_code_space(), counters(), DCHECK_LE, v8::internal::Histogram::Enabled(), EstimateCurrentMemoryConsumption(), v8::internal::wasm::WasmCodeAllocator::freed_code_size(), v8::internal::wasm::WasmCodeAllocator::generated_code_size(), v8::internal::KB, v8::internal::wasm::kWasmOrigin, v8::internal::MB, module(), module_, v8::internal::wasm::WasmModule::origin, and v8::internal::v8_flags.
set_fast_api_signature()
void v8::internal::wasm::NativeModule::set_fast_api_signature (int func_index, const MachineSignature * sig) [inline]
Definition at line 948 of file wasm-code-manager.h.
                                                                           {
    fast_api_signatures_[func_index] = sig;
  }
References v8::internal::sig.
Referenced by v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport().
set_lazy_compile_frozen()
void v8::internal::wasm::NativeModule::set_lazy_compile_frozen (bool frozen) [inline]
Definition at line 761 of file wasm-code-manager.h.
{ lazy_compile_frozen_ = frozen; }
SetDebugState()
void v8::internal::wasm::NativeModule::SetDebugState (DebugState new_debug_state)
Definition at line 2748 of file wasm-code-manager.cc.
                                                           {
  // Do not tier down asm.js (just never change the tiering state).
  if (module()->origin != kWasmOrigin) return;
  base::RecursiveMutexGuard lock(&allocation_mutex_);
  debug_state_ = new_debug_state;
}
References allocation_mutex_, debug_state_, v8::internal::wasm::kWasmOrigin, and module().
SetWasmSourceMap()
void v8::internal::wasm::NativeModule::SetWasmSourceMap (std::unique_ptr< WasmModuleSourceMap > source_map)
Definition at line 1709 of file wasm-code-manager.cc.
                                                   {
  source_map_ = std::move(source_map);
}
References source_map_.
Referenced by v8::internal::wasm::WasmCode::LogCode().
SetWireBytes()
void v8::internal::wasm::NativeModule::SetWireBytes (base::OwnedVector< const uint8_t > wire_bytes)
Definition at line 1977 of file wasm-code-manager.cc.
                                                                         {
  auto shared_wire_bytes =
      std::make_shared<base::OwnedVector<const uint8_t>>(std::move(wire_bytes));
  std::atomic_store(&wire_bytes_, shared_wire_bytes);
  if (!shared_wire_bytes->empty()) {
    compilation_state_->SetWireBytesStorage(
        std::make_shared<NativeModuleWireBytesStorage>(
            std::move(shared_wire_bytes)));
  }
}
References compilation_state_, wire_bytes(), and wire_bytes_.
shared_module()
std::shared_ptr<const WasmModule> v8::internal::wasm::NativeModule::shared_module () const [inline]
Definition at line 767 of file wasm-code-manager.h.
{ return module_; }
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits().
should_update_code_table()
bool v8::internal::wasm::NativeModule::should_update_code_table (WasmCode * new_code, WasmCode * prior_code) const [private]
Definition at line 1558 of file wasm-code-manager.cc.
                                                                        {
  if (new_code->for_debugging() == kForStepping) {
    // Never install stepping code.
    return false;
  }
  if (debug_state_ == kDebugging) {
    if (new_code->for_debugging() == kNotForDebugging) {
      // In debug state, only install debug code.
      return false;
    }
    if (prior_code && prior_code->for_debugging() > new_code->for_debugging()) {
      // In debug state, install breakpoints over normal debug code.
      return false;
    }
  }
  // In kNoDebugging:
  // Install if the tier is higher than before or we replace debugging code with
  // non-debugging code.
  // Also allow installing a lower tier if deopt support is enabled and the
  // prior code has deopt data. (The check for deopt_data is needed as with
  // compilation hints, both baseline and top tier compilation run concurrently
  // in the background and can finish in any order.)
  if (prior_code && !prior_code->for_debugging() &&
      prior_code->tier() > new_code->tier() &&
      (!v8_flags.wasm_deopt || prior_code->deopt_data().empty())) {
    return false;
  }
  return true;
}
References debug_state_, v8::internal::wasm::WasmCode::deopt_data(), v8::base::Vector< T >::empty(), v8::internal::wasm::WasmCode::for_debugging(), v8::internal::wasm::kDebugging, v8::internal::wasm::kForStepping, v8::internal::wasm::kNotForDebugging, v8::internal::wasm::WasmCode::tier(), and v8::internal::v8_flags.
Referenced by PublishCodeLocked().
ShouldLazyCompilationMetricsBeReported()
bool v8::internal::wasm::NativeModule::ShouldLazyCompilationMetricsBeReported () [inline]
Definition at line 804 of file wasm-code-manager.h.
                                                {
    return should_metrics_be_reported_.exchange(false,
                                                std::memory_order_relaxed);
  }
ShouldPgoDataBeWritten()
bool v8::internal::wasm::NativeModule::ShouldPgoDataBeWritten () [inline]
Definition at line 811 of file wasm-code-manager.h.
                                {
    return should_pgo_data_be_written_.exchange(false,
                                                std::memory_order_relaxed);
  }
SnapshotAllOwnedCode()
std::vector< WasmCode * > v8::internal::wasm::NativeModule::SnapshotAllOwnedCode () const
Definition at line 1680 of file wasm-code-manager.cc.
                                                              {
  base::RecursiveMutexGuard lock(&allocation_mutex_);
  if (!new_owned_code_.empty()) TransferNewOwnedCodeLocked();
  std::vector<WasmCode*> all_code(owned_code_.size());
  std::transform(owned_code_.begin(), owned_code_.end(), all_code.begin(),
                 [](auto& entry) { return entry.second.get(); });
  std::for_each(all_code.begin(), all_code.end(), WasmCodeRefScope::AddRef);
  return all_code;
}
References v8::internal::wasm::WasmCodeRefScope::AddRef(), allocation_mutex_, new_owned_code_, owned_code_, and TransferNewOwnedCodeLocked().
Referenced by LogWasmCodes().
SnapshotCodeTable()
std::pair< std::vector< WasmCode * >, std::vector< WellKnownImport > > v8::internal::wasm::NativeModule::SnapshotCodeTable () const
Definition at line 1666 of file wasm-code-manager.cc.
                                      {
  base::RecursiveMutexGuard lock(&allocation_mutex_);
  WasmCode** start = code_table_.get();
  WasmCode** end = start + module_->num_declared_functions;
  for (WasmCode* code : base::VectorOf(start, end - start)) {
    if (code) WasmCodeRefScope::AddRef(code);
  }
  std::vector<WellKnownImport> import_statuses(module_->num_imported_functions);
  for (uint32_t i = 0; i < module_->num_imported_functions; i++) {
    import_statuses[i] = module_->type_feedback.well_known_imports.get(i);
  }
  return {std::vector<WasmCode*>{start, end}, std::move(import_statuses)};
}
References v8::internal::wasm::WasmCodeRefScope::AddRef(), allocation_mutex_, code, code_table_, v8::internal::compiler::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, module_, and v8::base::VectorOf().
Referenced by v8::internal::wasm::WasmSerializer::WasmSerializer().
sum_lazy_compilation_time_in_ms()
int64_t v8::internal::wasm::NativeModule::sum_lazy_compilation_time_in_ms () const [inline]
Definition at line 790 of file wasm-code-manager.h.
                                                  {
    return sum_lazy_compilation_time_in_micro_sec_.load(
               std::memory_order_relaxed) /
           1000;
  }
SumLiftoffCodeSizeForTesting()
size_t v8::internal::wasm::NativeModule::SumLiftoffCodeSizeForTesting () const
Definition at line 2807 of file wasm-code-manager.cc.
                                                        {
  base::RecursiveMutexGuard guard(&allocation_mutex_);
  const uint32_t num_functions = module_->num_declared_functions;
  size_t codesize_liftoff = 0;
  for (uint32_t i = 0; i < num_functions; i++) {
    WasmCode* code = code_table_[i];
    if (code && code->is_liftoff()) {
      codesize_liftoff += code->instructions_size();
    }
  }
  return codesize_liftoff;
}
References allocation_mutex_, code, code_table_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, module_, and num_functions().
tiering_budget_array()
std::atomic<uint32_t>* v8::internal::wasm::NativeModule::tiering_budget_array () const [inline]
Definition at line 886 of file wasm-code-manager.h.
                                                    {
    return tiering_budgets_.get();
  }
Referenced by v8::internal::WasmTrustedInstanceData::New(), v8::internal::wasm::NativeModuleDeserializer::ReadTieringBudget(), v8::internal::wasm::NativeModuleSerializer::WriteCode(), and v8::internal::wasm::NativeModuleSerializer::WriteTieringBudget().
TransferNewOwnedCodeLocked()
void v8::internal::wasm::NativeModule::TransferNewOwnedCodeLocked () const [private]
Definition at line 2002 of file wasm-code-manager.cc.
                                                    {
  allocation_mutex_.AssertHeld();
  DCHECK(!new_owned_code_.empty());
  // Sort the {new_owned_code_} vector reversed, such that the position of the
  // previously inserted element can be used as a hint for the next element. If
  // elements in {new_owned_code_} are adjacent, this will guarantee
  // constant-time insertion into the map.
  std::sort(new_owned_code_.begin(), new_owned_code_.end(),
            [](const std::unique_ptr<WasmCode>& a,
               const std::unique_ptr<WasmCode>& b) {
              return a->instruction_start() > b->instruction_start();
            });
  auto insertion_hint = owned_code_.end();
  for (auto& code : new_owned_code_) {
    DCHECK_EQ(0, owned_code_.count(code->instruction_start()));
    // Check plausibility of the insertion hint.
    DCHECK(insertion_hint == owned_code_.end() ||
           insertion_hint->first > code->instruction_start());
    insertion_hint = owned_code_.emplace_hint(
        insertion_hint, code->instruction_start(), std::move(code));
  }
  new_owned_code_.clear();
}
References allocation_mutex_, v8::base::RecursiveMutex::AssertHeld(), code, v8::internal::DCHECK(), DCHECK_EQ, new_owned_code_, owned_code_, and v8::base::sort().
Referenced by FreeCode(), Lookup(), and SnapshotAllOwnedCode().
TrySetFastApiCallTarget()
bool v8::internal::wasm::NativeModule::TrySetFastApiCallTarget (int func_index, Address target) [inline]
Definition at line 917 of file wasm-code-manager.h.
                                                               {
    Address old_val =
        fast_api_targets_[func_index].load(std::memory_order_relaxed);
    if (old_val == target) {
      return true;
    }
    if (old_val != kNullAddress) {
      // If already a different target is stored, then there are conflicting
      // targets and fast api calls are not possible. In that case the import
      // will be marked as not suitable for wellknown imports, and the
      // `fast_api_target` of this import will never be used anymore in the
      // future.
      return false;
    }
    if (fast_api_targets_[func_index].compare_exchange_strong(
            old_val, target, std::memory_order_relaxed)) {
      return true;
    }
    // If a concurrent call to `TrySetFastAPICallTarget` set the call target to
    // the same value as this call, we consider also this call successful.
    return old_val == target;
  }
References v8::internal::kNullAddress.
Referenced by v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport().
turbofan_code_size()
size_t v8::internal::wasm::NativeModule::turbofan_code_size () const [inline]
Definition at line 780 of file wasm-code-manager.h.
                                    {
    return turbofan_code_size_.load(std::memory_order_relaxed);
  }
UpdateCodeSize()
void v8::internal::wasm::NativeModule::UpdateCodeSize (size_t size, ExecutionTier tier, ForDebugging for_debugging) [private]
Definition at line 1782 of file wasm-code-manager.cc.
                                                              {
  if (for_debugging != kNotForDebugging) return;
  // Count jump tables (ExecutionTier::kNone) for both Liftoff and TurboFan as
  // this is shared code.
  if (tier != ExecutionTier::kTurbofan) liftoff_code_size_.fetch_add(size);
  if (tier != ExecutionTier::kLiftoff) turbofan_code_size_.fetch_add(size);
}
References v8::internal::wasm::kLiftoff, v8::internal::wasm::kNotForDebugging, v8::internal::wasm::kTurbofan, liftoff_code_size_, size(), and turbofan_code_size_.
Referenced by AddCodeWithCodeSpace(), AddDeserializedCode(), and CreateEmptyJumpTableInRegionLocked().
UpdateWellKnownImports()
void v8::internal::wasm::NativeModule::UpdateWellKnownImports (base::Vector< WellKnownImport > entries)
Definition at line 1457 of file wasm-code-manager.cc.
                                         {
  // The {~WasmCodeRefScope} destructor must run after releasing the {lock},
  // to avoid lock order inversion.
  WasmCodeRefScope ref_scope;
  base::RecursiveMutexGuard lock(&allocation_mutex_);
  WellKnownImportsList::UpdateResult result =
      module_->type_feedback.well_known_imports.Update(entries);
  if (result == WellKnownImportsList::UpdateResult::kFoundIncompatibility) {
    RemoveCompiledCode(NativeModule::RemoveFilter::kRemoveTurbofanCode);
  }
}
References allocation_mutex_, v8::internal::wasm::WellKnownImportsList::kFoundIncompatibility, kRemoveTurbofanCode, module_, RemoveCompiledCode(), and v8::base::internal::result.
UseLazyStubLocked()
void v8::internal::wasm::NativeModule::UseLazyStubLocked (uint32_t func_index)
Definition at line 1237 of file wasm-code-manager.cc.
                                                        {
  allocation_mutex_.AssertHeld();
  DCHECK_LE(module_->num_imported_functions, func_index);
  DCHECK_LT(func_index,
            module_->num_imported_functions + module_->num_declared_functions);
  // Avoid opening a new write scope per function. The caller should hold the
  // scope instead.
  DCHECK_NOT_NULL(lazy_compile_table_);
  // Add jump table entry for jump to the lazy compile stub.
  uint32_t slot_index = declared_function_index(module(), func_index);
  DCHECK_NULL(code_table_[slot_index]);
  Address jump_table_target =
      main_jump_table_->instruction_start() +
      JumpTableAssembler::JumpSlotIndexToOffset(slot_index);
  Address lazy_compile_target =
      lazy_compile_table_->instruction_start() +
      JumpTableAssembler::LazyCompileSlotIndexToOffset(slot_index);
  uint64_t signature_hash =
      module_->signature_hash(GetTypeCanonicalizer(), func_index);
  PatchJumpTablesLocked(slot_index, lazy_compile_target, jump_table_target,
                        signature_hash);
}
References allocation_mutex_, v8::base::RecursiveMutex::AssertHeld(), code_table_, DCHECK_LE, DCHECK_LT, DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::wasm::declared_function_index(), v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::wasm::WasmCode::instruction_start(), v8::internal::wasm::JumpTableAssembler::JumpSlotIndexToOffset(), lazy_compile_table_, v8::internal::wasm::JumpTableAssembler::LazyCompileSlotIndexToOffset(), main_jump_table_, module(), module_, and PatchJumpTablesLocked().
Referenced by RemoveCompiledCode().
wire_bytes()
base::Vector<const uint8_t> v8::internal::wasm::NativeModule::wire_bytes () const [inline]
Definition at line 763 of file wasm-code-manager.h.
                                               {
    return std::atomic_load(&wire_bytes_)->as_vector();
  }
Referenced by v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction(), v8::internal::wasm::CanonicalTypeNamesProvider::DecodeNames(), DisassembleForLcov(), v8::internal::wasm::NativeModuleCache::Erase(), EstimateCurrentMemoryConsumption(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindNextBreakablePosition(), v8::internal::wasm::InterpreterHandle::GetBytes(), GetNamesProvider(), v8::internal::WasmScript::GetPossibleBreakpoints(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmModuleBytes(), v8::internal::wasm::WasmEngine::ImportNativeModule(), v8::internal::WasmTrustedInstanceData::InitDataSegmentArrays(), v8::internal::wasm::InitializeElementSegment(), v8::internal::wasm::DebugInfoImpl::IsAtReturn(), v8::internal::compiler::JsonPrintFunctionSource(), v8::internal::wasm::WasmCode::LogCode(), v8::internal::wasm::gdb_server::ReturnPc(), v8::internal::wasm::InstanceBuilder::SanitizeImports(), SetWireBytes(), v8::internal::wasm::ThrowLazyCompilationError(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall(), v8::internal::compiler::WasmGraphBuilder::TryWasmInlining(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ValidateFunctionNowIfNeeded(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateFunctions(), and ~NativeModule().
Friends And Related Function Documentation
CodeSpaceWriteScope
friend class CodeSpaceWriteScope [friend]
Definition at line 970 of file wasm-code-manager.h.
WasmCode
friend class WasmCode [friend]
Definition at line 967 of file wasm-code-manager.h.
WasmCodeAllocator
friend class WasmCodeAllocator [friend]
Definition at line 968 of file wasm-code-manager.h.
WasmCodeManager
friend class WasmCodeManager [friend]
Definition at line 969 of file wasm-code-manager.h.
Member Data Documentation
allocation_mutex_
base::RecursiveMutex v8::internal::wasm::NativeModule::allocation_mutex_ [mutable], [private]
Definition at line 1097 of file wasm-code-manager.h.
Referenced by AddCode(), AddCodeForTesting(), AddCodeSpaceLocked(), AddCompiledCode(), AllocateForDeserializedCode(), CreateEmptyJumpTableInRegionLocked(), EstimateCurrentMemoryConsumption(), FindJumpTablesForRegionLocked(), FreeCode(), GetBuiltinInJumptableSlot(), GetCode(), GetDebugInfo(), GetNamesProvider(), GetNumberOfCodeSpacesForTesting(), HasCode(), HasCodeWithTier(), HasDebugInfo(), InitializeJumpTableForLazyCompilation(), Lookup(), NativeModule(), PatchJumpTableLocked(), PatchJumpTablesLocked(), PublishCode(), PublishCodeLocked(), ReinstallDebugCode(), RemoveCompiledCode(), SetDebugState(), SnapshotAllOwnedCode(), SnapshotCodeTable(), SumLiftoffCodeSizeForTesting(), TransferNewOwnedCodeLocked(), UpdateWellKnownImports(), and UseLazyStubLocked().
code_allocator_
WasmCodeAllocator v8::internal::wasm::NativeModule::code_allocator_ [private]
Definition at line 1051 of file wasm-code-manager.h.
Referenced by AddCode(), AddCodeForTesting(), AddCompiledCode(), AllocateForDeserializedCode(), CreateEmptyJumpTableInRegionLocked(), FreeCode(), GetNumberOfCodeSpacesForTesting(), NativeModule(), and SampleCodeSize().
code_pointer_handles_
std::unique_ptr<WasmCodePointer[]> v8::internal::wasm::NativeModule::code_pointer_handles_ [private]
Definition at line 1121 of file wasm-code-manager.h.
Referenced by FreeCodePointerTableHandles(), GetCodePointerHandle(), InitializeCodePointerTableHandles(), InitializeJumpTableForLazyCompilation(), and PatchJumpTablesLocked().
code_pointer_handles_size_
size_t v8::internal::wasm::NativeModule::code_pointer_handles_size_ = 0 [private]
Definition at line 1124 of file wasm-code-manager.h.
Referenced by FreeCodePointerTableHandles(), InitializeCodePointerTableHandles(), InitializeJumpTableForLazyCompilation(), and PatchJumpTableLocked().
code_space_data_
std::vector<CodeSpaceData> v8::internal::wasm::NativeModule::code_space_data_ [private]
Definition at line 1127 of file wasm-code-manager.h.
Referenced by AddCodeSpaceLocked(), EstimateCurrentMemoryConsumption(), FindJumpTablesForRegionLocked(), GetBuiltinInJumptableSlot(), InitializeJumpTableForLazyCompilation(), and PatchJumpTablesLocked().
code_table_
std::unique_ptr<WasmCode*[]> v8::internal::wasm::NativeModule::code_table_ [private]
Definition at line 1116 of file wasm-code-manager.h.
Referenced by AddCodeSpaceLocked(), GetCode(), HasCode(), HasCodeWithTier(), NativeModule(), PublishCodeLocked(), ReinstallDebugCode(), RemoveCompiledCode(), SnapshotCodeTable(), SumLiftoffCodeSizeForTesting(), and UseLazyStubLocked().
compilation_state_
std::unique_ptr<CompilationState> v8::internal::wasm::NativeModule::compilation_state_ [private]
Definition at line 1086 of file wasm-code-manager.h.
Referenced by EstimateCurrentMemoryConsumption(), NativeModule(), PublishCodeLocked(), RemoveCompiledCode(), SetWireBytes(), and ~NativeModule().
compile_imports_
const CompileTimeImports v8::internal::wasm::NativeModule::compile_imports_ [private]
Definition at line 1059 of file wasm-code-manager.h.
Referenced by EstimateCurrentMemoryConsumption().
coverage_data_
std::shared_ptr<WasmModuleCoverageData> v8::internal::wasm::NativeModule::coverage_data_ [private]
Definition at line 1167 of file wasm-code-manager.h.
Referenced by NativeModule().
debug_info_
std::unique_ptr<DebugInfo> v8::internal::wasm::NativeModule::debug_info_ [private]
Definition at line 1133 of file wasm-code-manager.h.
Referenced by EstimateCurrentMemoryConsumption(), FreeCode(), GetDebugInfo(), and HasDebugInfo().
debug_state_
DebugState v8::internal::wasm::NativeModule::debug_state_ = kNotDebugging [private]
Definition at line 1137 of file wasm-code-manager.h.
Referenced by ReinstallDebugCode(), SetDebugState(), and should_update_code_table().
enabled_features_
const WasmEnabledFeatures v8::internal::wasm::NativeModule::enabled_features_ [private]
Definition at line 1056 of file wasm-code-manager.h.
engine_scope_
OperationsBarrier::Token v8::internal::wasm::NativeModule::engine_scope_ [private]
Definition at line 1047 of file wasm-code-manager.h.
Referenced by NativeModule().
fast_api_signatures_
std::unique_ptr<std::atomic<const MachineSignature*>[]> v8::internal::wasm::NativeModule::fast_api_signatures_ [private]
Definition at line 1165 of file wasm-code-manager.h.
fast_api_targets_
std::unique_ptr<std::atomic<Address>[]> v8::internal::wasm::NativeModule::fast_api_targets_ [private]
Definition at line 1164 of file wasm-code-manager.h.
kManagedTag
constexpr ExternalPointerTag v8::internal::wasm::NativeModule::kManagedTag = kWasmNativeModuleTag [static], [constexpr]
Definition at line 614 of file wasm-code-manager.h.
kNeedsFarJumpsBetweenCodeSpaces
constexpr bool v8::internal::wasm::NativeModule::kNeedsFarJumpsBetweenCodeSpaces = false [static], [constexpr]
Definition at line 621 of file wasm-code-manager.h.
Referenced by FindJumpTablesForRegionLocked(), v8::internal::wasm::WasmCodeManager::NewNativeModule(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::NumWasmFunctionsInFarJumpTable(), and v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::OverheadPerCodeSpace().
lazy_compile_frozen_
bool v8::internal::wasm::NativeModule::lazy_compile_frozen_ = false [private]
Definition at line 1142 of file wasm-code-manager.h.
lazy_compile_table_
WasmCode* v8::internal::wasm::NativeModule::lazy_compile_table_ = nullptr [private]
Definition at line 1081 of file wasm-code-manager.h.
Referenced by AddCodeSpaceLocked(), InitializeJumpTableForLazyCompilation(), and UseLazyStubLocked().
liftoff_bailout_count_
std::atomic<size_t> v8::internal::wasm::NativeModule::liftoff_bailout_count_ {0} [private]
Definition at line 1143 of file wasm-code-manager.h.
liftoff_code_size_
std::atomic<size_t> v8::internal::wasm::NativeModule::liftoff_code_size_ {0} [private]
Definition at line 1144 of file wasm-code-manager.h.
Referenced by UpdateCodeSize().
log_code_
std::atomic<bool> v8::internal::wasm::NativeModule::log_code_ {false} [private]
Definition at line 1162 of file wasm-code-manager.h.
main_far_jump_table_
WasmCode* v8::internal::wasm::NativeModule::main_far_jump_table_ = nullptr [private]
Definition at line 1077 of file wasm-code-manager.h.
Referenced by AddCodeSpaceLocked().
main_jump_table_
WasmCode* v8::internal::wasm::NativeModule::main_jump_table_ = nullptr [private]
Definition at line 1074 of file wasm-code-manager.h.
Referenced by AddCodeSpaceLocked(), and UseLazyStubLocked().
max_lazy_compilation_time_in_micro_sec_
std::atomic<int64_t> v8::internal::wasm::NativeModule::max_lazy_compilation_time_in_micro_sec_ {0} [private]
Definition at line 1150 of file wasm-code-manager.h.
Referenced by AddLazyCompilationTimeSample().
module_
std::shared_ptr<const WasmModule> v8::internal::wasm::NativeModule::module_ [private]
Definition at line 1063 of file wasm-code-manager.h.
Referenced by AddCodeSpaceLocked(), AddCodeWithCodeSpace(), AddDeserializedCode(), EstimateCurrentMemoryConsumption(), GetCodePointerHandle(), GetFunctionIndexFromJumpTableSlot(), GetNamesProvider(), InitializeJumpTableForLazyCompilation(), LogWasmCodes(), NativeModule(), PatchJumpTableLocked(), PublishCodeLocked(), ReinstallDebugCode(), RemoveCompiledCode(), SampleCodeSize(), SnapshotCodeTable(), SumLiftoffCodeSizeForTesting(), UpdateWellKnownImports(), UseLazyStubLocked(), and ~NativeModule().
names_provider_
std::unique_ptr<NamesProvider> v8::internal::wasm::NativeModule::names_provider_ [private]
Definition at line 1135 of file wasm-code-manager.h.
Referenced by EstimateCurrentMemoryConsumption(), and GetNamesProvider().
new_owned_code_
std::vector<std::unique_ptr<WasmCode> > v8::internal::wasm::NativeModule::new_owned_code_ [mutable], [private]
Definition at line 1110 of file wasm-code-manager.h.
Referenced by EstimateCurrentMemoryConsumption(), FreeCode(), Lookup(), PublishCodeLocked(), SnapshotAllOwnedCode(), and TransferNewOwnedCodeLocked().
num_lazy_compilations_
std::atomic<int> v8::internal::wasm::NativeModule::num_lazy_compilations_ {0} [private]
Definition at line 1148 of file wasm-code-manager.h.
Referenced by AddLazyCompilationTimeSample().
owned_code_
std::map<Address, std::unique_ptr<WasmCode> > v8::internal::wasm::NativeModule::owned_code_ [mutable], [private]
Definition at line 1105 of file wasm-code-manager.h.
Referenced by EstimateCurrentMemoryConsumption(), FreeCode(), Lookup(), SnapshotAllOwnedCode(), and TransferNewOwnedCodeLocked().
should_metrics_be_reported_
std::atomic<bool> v8::internal::wasm::NativeModule::should_metrics_be_reported_ {true} [private]
Definition at line 1151 of file wasm-code-manager.h.
should_pgo_data_be_written_
std::atomic<bool> v8::internal::wasm::NativeModule::should_pgo_data_be_written_ {true} [private]
Definition at line 1155 of file wasm-code-manager.h.
source_map_
std::unique_ptr<WasmModuleSourceMap> v8::internal::wasm::NativeModule::source_map_ [private]
Definition at line 1065 of file wasm-code-manager.h.
Referenced by EstimateCurrentMemoryConsumption(), GetWasmSourceMap(), and SetWasmSourceMap().
sum_lazy_compilation_time_in_micro_sec_
std::atomic<int64_t> v8::internal::wasm::NativeModule::sum_lazy_compilation_time_in_micro_sec_ {0} [private]
Definition at line 1149 of file wasm-code-manager.h.
Referenced by AddLazyCompilationTimeSample().
tiering_budgets_
std::unique_ptr<std::atomic<uint32_t>[]> v8::internal::wasm::NativeModule::tiering_budgets_ [private]
Definition at line 1089 of file wasm-code-manager.h.
Referenced by NativeModule(), and ~NativeModule().
turbofan_code_size_
std::atomic<size_t> v8::internal::wasm::NativeModule::turbofan_code_size_ {0} [private]
Definition at line 1145 of file wasm-code-manager.h.
Referenced by UpdateCodeSize().
wire_bytes_
std::shared_ptr<base::OwnedVector<const uint8_t> > v8::internal::wasm::NativeModule::wire_bytes_ [private]
Definition at line 1069 of file wasm-code-manager.h.
Referenced by EstimateCurrentMemoryConsumption(), and SetWireBytes().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-code-manager.h
/mnt/V8SourceCode/src/wasm/wasm-code-manager.cc