v8::internal::OldSpace Class Reference
#include <paged-spaces.h>
Public Member Functions
OldSpace (Heap *heap)
void AddPromotedPage (PageMetadata *page, FreeMode free_mode)
size_t ExternalBackingStoreBytes (ExternalBackingStoreType type) const final
void RelinkQuarantinedPageFreeList (PageMetadata *page, size_t filler_size_on_page)
Additional Inherited Members
Detailed Description
Definition at line 444 of file paged-spaces.h.
Constructor & Destructor Documentation
OldSpace()
v8::internal::OldSpace::OldSpace (Heap * heap) [inline], [explicit]
Definition at line 448 of file paged-spaces.h.
      : PagedSpace(heap, OLD_SPACE, NOT_EXECUTABLE, FreeList::CreateFreeList(),
                   CompactionSpaceKind::kNone) {}
References v8::internal::kNone.
Member Function Documentation
AddPromotedPage()
void v8::internal::OldSpace::AddPromotedPage (PageMetadata * page, FreeMode free_mode)
Definition at line 634 of file paged-spaces.cc.
                                                                     {
  DCHECK_EQ(page->area_size(), page->allocated_bytes());
  if (v8_flags.minor_ms) {
    // Reset the page's allocated bytes. The page will be swept and the
    // allocated bytes will be updated to match the live bytes.
    page->DecreaseAllocatedBytes(page->area_size());
  }
  AddPageImpl(page);
  if (free_mode == FreeMode::kLinkCategory) {
    RelinkFreeListCategories(page);
  }
}
References v8::internal::PagedSpaceBase::AddPageImpl(), v8::internal::MemoryChunkMetadata::allocated_bytes(), v8::internal::MemoryChunkMetadata::area_size(), DCHECK_EQ, v8::internal::MemoryChunkMetadata::DecreaseAllocatedBytes(), v8::internal::kLinkCategory, v8::internal::PagedSpaceBase::RelinkFreeListCategories(), and v8::internal::v8_flags.
Referenced by v8::internal::PageMetadata::ConvertNewToOld().
ExternalBackingStoreBytes()
size_t v8::internal::OldSpace::ExternalBackingStoreBytes (ExternalBackingStoreType type) const [inline], [final]
Definition at line 454 of file paged-spaces.h.
                                                                              {
    if (type == ExternalBackingStoreType::kArrayBuffer)
      return heap()->OldArrayBufferBytes();
    return external_backing_store_bytes_[static_cast<int>(type)];
  }
References heap(), v8::internal::kArrayBuffer, and v8::internal::tracing::type.
RelinkQuarantinedPageFreeList()
void v8::internal::OldSpace::RelinkQuarantinedPageFreeList (PageMetadata * page, size_t filler_size_on_page)
Definition at line 647 of file paged-spaces.cc.
                                                                         {
  base::MutexGuard guard(mutex());
  DCHECK_EQ(this, page->owner());
  DCHECK(page->SweepingDone());
  DCHECK_EQ(page->live_bytes(), 0);
  DCHECK_EQ(accounting_stats_.AllocatedOnPage(page),
            MemoryChunkLayout::AllocatableMemoryInMemoryChunk(OLD_SPACE));
  DecreaseAllocatedBytes(filler_size_on_page, page);
  RelinkFreeListCategories(page);
}
References v8::internal::PagedSpaceBase::accounting_stats_, v8::internal::MemoryChunkLayout::AllocatableMemoryInMemoryChunk(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::PagedSpaceBase::DecreaseAllocatedBytes(), v8::internal::MutablePageMetadata::live_bytes(), v8::internal::PagedSpaceBase::mutex(), v8::internal::OLD_SPACE, v8::internal::MutablePageMetadata::owner(), v8::internal::PagedSpaceBase::RelinkFreeListCategories(), and v8::internal::MutablePageMetadata::SweepingDone().
Referenced by v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/paged-spaces.h
/mnt/V8SourceCode/src/heap/paged-spaces.cc