v8::internal::compiler::JSFunctionRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< JSFunction > object () const
bool IsConsistentWithHeapState (JSHeapBroker *broker) const
ContextRef context (JSHeapBroker *broker) const
NativeContextRef native_context (JSHeapBroker *broker) const
SharedFunctionInfoRef shared (JSHeapBroker *broker) const
OptionalCodeRef code (JSHeapBroker *broker) const
bool has_initial_map (JSHeapBroker *broker) const
bool PrototypeRequiresRuntimeLookup (JSHeapBroker *broker) const
bool has_instance_prototype (JSHeapBroker *broker) const
HeapObjectRef instance_prototype (JSHeapBroker *broker) const
MapRef initial_map (JSHeapBroker *broker) const
int InitialMapInstanceSizeWithMinSlack (JSHeapBroker *broker) const
FeedbackCellRef raw_feedback_cell (JSHeapBroker *broker) const
OptionalFeedbackVectorRef feedback_vector (JSHeapBroker *broker) const
Detailed Description
Definition at line 668 of file heap-refs.h.
Member Function Documentation
code()
true JSFunctionData::kInitialMap JSFunctionData::kFeedbackCell OptionalCodeRef v8::internal::compiler::JSFunctionRef::code (JSHeapBroker * broker) const
Definition at line 2451 of file heap-refs.cc.
                                                              {
  return TryMakeRef(broker, object()->code(broker->isolate()));
}
References broker(), and v8::internal::compiler::TryMakeRef().
context()
ContextRef v8::internal::compiler::JSFunctionRef::context (JSHeapBroker * broker) const
Referenced by native_context(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildFindNonDefaultConstructorOrConstruct().
feedback_vector()
OptionalFeedbackVectorRef v8::internal::compiler::JSFunctionRef::feedback_vector (JSHeapBroker * broker) const
Definition at line 1279 of file heap-refs.cc.
                                {
  return raw_feedback_cell(broker).feedback_vector(broker);
}
References broker(), v8::internal::compiler::FeedbackCellRef::feedback_vector(), and raw_feedback_cell().
has_initial_map()
bool v8::internal::compiler::JSFunctionRef::has_initial_map (JSHeapBroker * broker) const
Referenced by v8::internal::compiler::NodeProperties::GetJSCreateMap(), v8::internal::maglev::MaglevGraphBuilder::HasValidInitialMap(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject().
has_instance_prototype()
bool v8::internal::compiler::JSFunctionRef::has_instance_prototype (JSHeapBroker * broker) const
initial_map()
MapRef v8::internal::compiler::JSFunctionRef::initial_map (JSHeapBroker * broker) const
Referenced by v8::internal::maglev::MaglevGraphBuilder::CreateJSConstructor(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetArrayConstructorInitialMap(), v8::internal::compiler::NodeProperties::GetJSCreateMap(), v8::internal::maglev::MaglevGraphBuilder::HasValidInitialMap(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCallReducer::ReduceStringConstructor(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructArrayConstructor().
InitialMapInstanceSizeWithMinSlack()
int v8::internal::compiler::JSFunctionRef::InitialMapInstanceSizeWithMinSlack (JSHeapBroker * broker) const
Definition at line 1284 of file heap-refs.cc.
                                {
  if (data_->should_access_heap()) {
    return object()->ComputeInstanceSizeWithMinSlack(broker->isolate());
  }
  RecordConsistentJSFunctionViewDependencyIfNeeded(
      broker, *this, data()->AsJSFunction(),
      JSFunctionData::kInitialMapInstanceSizeWithMinSlack);
  return data()->AsJSFunction()->initial_map_instance_size_with_min_slack();
}
References broker(), v8::internal::compiler::JSFunctionData::kInitialMapInstanceSizeWithMinSlack, object(), and v8::internal::compiler::anonymous_namespace{heap-refs.cc}::RecordConsistentJSFunctionViewDependencyIfNeeded().
instance_prototype()
HeapObjectRef v8::internal::compiler::JSFunctionRef::instance_prototype (JSHeapBroker * broker) const
IsConsistentWithHeapState()
bool v8::internal::compiler::JSFunctionRef::IsConsistentWithHeapState (JSHeapBroker * broker) const
Definition at line 776 of file heap-refs.cc.
                                                                        {
  DCHECK(broker->IsMainThread());
  return data()->AsJSFunction()->IsConsistentWithHeapState(broker);
}
References broker(), and v8::internal::DCHECK().
native_context()
NativeContextRef v8::internal::compiler::JSFunctionRef::native_context (JSHeapBroker * broker) const
Definition at line 2455 of file heap-refs.cc.
                                                                         {
  return MakeRefAssumeMemoryFence(broker,
                                  context(broker).object()->native_context());
}
References broker(), context(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
object()
IndirectHandle<JSFunction> v8::internal::compiler::JSFunctionRef::object () const
Referenced by InitialMapInstanceSizeWithMinSlack(), v8::internal::maglev::MaglevGraphBuilder::TargetIsCurrentCompilingUnit(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForConstant().
PrototypeRequiresRuntimeLookup()
bool v8::internal::compiler::JSFunctionRef::PrototypeRequiresRuntimeLookup (JSHeapBroker * broker) const
raw_feedback_cell()
FeedbackCellRef v8::internal::compiler::JSFunctionRef::raw_feedback_cell (JSHeapBroker * broker) const
Referenced by feedback_vector().
shared()
SharedFunctionInfoRef v8::internal::compiler::JSFunctionRef::shared (JSHeapBroker * broker) const
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSCallReducer::ReduceStringConstructor(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFindNonDefaultConstructorOrConstruct(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForConstant().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc