v8::internal::compiler::ReferenceMap Class Reference
#include <instruction.h>
Public Member Functions
ReferenceMap (Zone *zone)
const ZoneVector< InstructionOperand > & reference_operands () const
int instruction_position () const
void set_instruction_position (int pos)
void RecordReference (const AllocatedOperand &op)
Private Attributes
ZoneVector< InstructionOperand > reference_operands_
int instruction_position_
Friends
std::ostream & operator<< (std::ostream &, const ReferenceMap &)
Detailed Description
Definition at line 888 of file instruction.h.
Constructor & Destructor Documentation
ReferenceMap()
v8::internal::compiler::ReferenceMap::ReferenceMap (Zone * zone) [inline], [explicit]
Definition at line 890 of file instruction.h.
      : reference_operands_(zone), instruction_position_(-1) {}
Member Function Documentation
instruction_position()
int v8::internal::compiler::ReferenceMap::instruction_position () const [inline]
Definition at line 896 of file instruction.h.
{ return instruction_position_; }
Referenced by v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps().
RecordReference()
void v8::internal::compiler::ReferenceMap::RecordReference (const AllocatedOperand & op)
Definition at line 437 of file instruction.cc.
                                                             {
  // Do not record arguments as pointers.
  if (op.IsStackSlot() && LocationOperand::cast(op).index() < 0) return;
  DCHECK(!op.IsFPRegister() && !op.IsFPStackSlot());
  reference_operands_.push_back(op);
}
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::compiler::LocationOperand::index(), v8::internal::compiler::InstructionOperand::IsFPRegister(), v8::internal::compiler::InstructionOperand::IsFPStackSlot(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::ZoneVector< T >::push_back(), and reference_operands_.
Referenced by v8::internal::compiler::ConstraintBuilder::AllocateFixed(), and v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps().
reference_operands()
const ZoneVector<InstructionOperand>& v8::internal::compiler::ReferenceMap::reference_operands () const [inline]
Definition at line 893 of file instruction.h.
                                                                   {
    return reference_operands_;
  }
Referenced by v8::internal::compiler::BlockAssessments::CheckReferenceMap(), and v8::internal::compiler::CodeGenerator::RecordSafepoint().
set_instruction_position()
void v8::internal::compiler::ReferenceMap::set_instruction_position (int pos) [inline]
Definition at line 898 of file instruction.h.
                                         {
    DCHECK_EQ(-1, instruction_position_);
    instruction_position_ = pos;
  }
References DCHECK_EQ.
Referenced by v8::internal::compiler::InstructionSequence::AddInstruction().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & , const ReferenceMap &) [friend]
Definition at line 444 of file instruction.cc.
                                                               {
  os << "{";
  const char* separator = "";
  for (const InstructionOperand& op : pm.reference_operands_) {
    os << separator << op;
    separator = ";";
  }
  return os << "}";
}
Member Data Documentation
instruction_position_
int v8::internal::compiler::ReferenceMap::instruction_position_ [private]
Definition at line 909 of file instruction.h.
reference_operands_
ZoneVector<InstructionOperand> v8::internal::compiler::ReferenceMap::reference_operands_ [private]
Definition at line 908 of file instruction.h.
Referenced by RecordReference().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction.h
/mnt/V8SourceCode/src/compiler/backend/instruction.cc