v8::internal::SegmentedTable< Entry, size > Class Template Reference
A thread-safe table with a fixed maximum size split into segments.
#include <segmented-table.h>
Classes
struct FreelistHead
struct Segment
class WriteIterator
Protected Member Functions
SegmentedTable ()=default
SegmentedTable (const SegmentedTable &)=delete
SegmentedTable & operator= (const SegmentedTable &)=delete
Entry & at (uint32_t index)
const Entry & at (uint32_t index) const
WriteIterator iter_at (uint32_t index)
bool is_initialized () const
Address base () const
std::pair< Segment, FreelistHead > AllocateAndInitializeSegment ()
std::optional< std::pair< Segment, FreelistHead > > TryAllocateAndInitializeSegment ()
std::optional< Segment > TryAllocateSegment ()
std::optional< Segment > TryGetSegmentFromPool ()
std::optional< Segment > FillSegmentsPool (bool return_a_segment)
FreelistHead InitializeFreeList (Segment segment, uint32_t start_offset=0)
void FreeTableSegment (Segment segment)
void Initialize ()
void TearDown ()
Protected Attributes
Entry * base_ = nullptr
VirtualAddressSpace * vas_ = nullptr
base::Mutex * segment_pool_grow_mutex_ = nullptr
std::array< std::atomic< uint32_t >, kSegmentPoolSize > segment_pool_ = {}
uint32_t read_only_segments_used_ = 0
Static Protected Attributes
static constexpr bool kIsWriteProtected = Entry::IsWriteProtected
static constexpr int kEntrySize = sizeof(Entry)
static constexpr bool kUseContiguousMemory = false
static constexpr bool kUseSegmentPool = false
static constexpr size_t kSegmentSize = 16 * KB
static constexpr size_t kSegmentPoolSize = 4
static constexpr size_t kEntriesPerSegment = kSegmentSize / kEntrySize
static constexpr size_t kAlignment
static constexpr size_t kNumReadOnlySegments
Detailed Description
template<typename Entry, size_t size>
class v8::internal::SegmentedTable< Entry, size >
A thread-safe table with a fixed maximum size split into segments.
The table provides thread-safe methods to allocate and free of segments and an inline freelist implementation. Allocation and Freeing of entries is implemented in subclasses since it depends on if the table is manually managed or GCed.
For the purpose of memory management, the table is partitioned into Segments (for example 64kb memory chunks) that are grouped together in `Spaces`. All segments in a space share a freelist, and so entry allocation and garbage collection happen on the level of spaces.
The Entry type defines how the freelist is represented. For that, it must implement the following methods:
void MakeFreelistEntry(uint32_t next_entry_index)
uint32_t GetNextFreelistEntry()
Definition at line 34 of file segmented-table.h.
Constructor & Destructor Documentation
SegmentedTable() [1/2]
template<typename Entry , size_t size>
v8::internal::SegmentedTable< Entry, size >::SegmentedTable () [protected], [default]
SegmentedTable() [2/2]
template<typename Entry , size_t size>
v8::internal::SegmentedTable< Entry, size >::SegmentedTable (const SegmentedTable< Entry, size > &) [protected], [delete]
Member Function Documentation
AllocateAndInitializeSegment()
template<typename Entry , size_t size>
std::pair< typename SegmentedTable< Entry, size >::Segment, typename SegmentedTable< Entry, size >::FreelistHead > v8::internal::SegmentedTable< Entry, size >::AllocateAndInitializeSegment [protected]
Definition at line 220 of file segmented-table-inl.h.
                                                          {
  if (auto res = TryAllocateAndInitializeSegment()) {
    return *res;
  }
  V8::FatalProcessOutOfMemory(nullptr,
                              "SegmentedTable::AllocateAndInitializeSegment");
}
at() [1/2]
template<typename Entry , size_t size>
Entry & v8::internal::SegmentedTable< Entry, size >::at (uint32_t index) [protected]
Definition at line 34 of file segmented-table-inl.h.
                                                     {
  return base_[index];
}
References v8::internal::SegmentedTable< Entry, size >::base_, and v8::internal::index.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntryFromFreelist(), and v8::internal::ExternalEntityTable< Entry, size >::ZeroInternalNullEntry().
at() [2/2]
template<typename Entry , size_t size>
const Entry & v8::internal::SegmentedTable< Entry, size >::at (uint32_t index) const [protected]
Definition at line 39 of file segmented-table-inl.h.
                                                                 {
  return base_[index];
}
References v8::internal::SegmentedTable< Entry, size >::base_, and v8::internal::index.
base()
template<typename Entry , size_t size>
Address v8::internal::SegmentedTable< Entry, size >::base [protected]
Definition at line 56 of file segmented-table-inl.h.
                                                {
  DCHECK(is_initialized());
  return reinterpret_cast<Address>(base_);
}
References v8::internal::SegmentedTable< Entry, size >::base_, v8::internal::DCHECK(), and v8::internal::SegmentedTable< Entry, size >::is_initialized().
FillSegmentsPool()
template<typename Entry , size_t size>
std::optional< typename SegmentedTable< Entry, size >::Segment > v8::internal::SegmentedTable< Entry, size >::FillSegmentsPool (bool return_a_segment) [protected]
Definition at line 198 of file segmented-table-inl.h.
                                                                   {
  std::optional<Segment> res;
  for (size_t i = 0; i < kSegmentPoolSize; ++i) {
    DCHECK_EQ(segment_pool_[i].load(std::memory_order_acquire), 0);
    Address start =
        vas_->AllocatePages(VirtualAddressSpace::kNoHint, kSegmentSize,
                            kAlignment, PagePermissions::kReadWrite);
    if (!start) continue;
    uint32_t offset = static_cast<uint32_t>(start - vas_->base());
    if (return_a_segment && i == 0) {
      res.emplace(Segment::At(offset));
      continue;
    }
    DCHECK_NE(offset, 0);
    segment_pool_[i].store(offset, std::memory_order_release);
  }
  return res;
}
Referenced by v8::internal::ExternalEntityTable< Entry, size >::Initialize(), and v8::internal::SegmentedTable< Entry, size >::TryAllocateSegment().
FreeTableSegment()
template<typename Entry , size_t size>
void v8::internal::SegmentedTable< Entry, size >::FreeTableSegment (Segment segment) [protected]
Definition at line 241 of file segmented-table-inl.h.
                                                                  {
  if (kUseSegmentPool) {
    // Offset 0 is used as a marker for free entries. Thus we cannot store it in
    // the pool.
    if (segment.offset() != 0) {
      base::MutexGuard guard(*segment_pool_grow_mutex_);
      for (size_t i = 0; i < kSegmentPoolSize; ++i) {
        uint32_t cur = segment_pool_[i].load(std::memory_order_relaxed);
        if (cur == 0) {
          if (segment_pool_[i].compare_exchange_weak(
                  cur, segment.offset(), std::memory_order_acq_rel)) {
            return;
          }
        }
      }
    }
  }
  Address segment_start = vas_->base() + segment.offset();
  vas_->FreePages(segment_start, kSegmentSize);
}
References v8::VirtualAddressSpace::base(), v8::VirtualAddressSpace::FreePages(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::SegmentedTable< Entry, size >::kSegmentPoolSize, v8::internal::SegmentedTable< Entry, size >::kSegmentSize, v8::internal::SegmentedTable< Entry, size >::kUseSegmentPool, v8::internal::SegmentedTable< Entry, size >::Segment::offset(), v8::internal::SegmentedTable< Entry, size >::segment_pool_, v8::internal::SegmentedTable< Entry, size >::segment_pool_grow_mutex_, and v8::internal::SegmentedTable< Entry, size >::vas_.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::GenericSweep(), and v8::internal::ExternalEntityTable< Entry, size >::TearDownSpace().
Initialize()
template<typename Entry , size_t size>
void v8::internal::SegmentedTable< Entry, size >::Initialize [protected]
Definition at line 62 of file segmented-table-inl.h.
                                             {
  DCHECK(!is_initialized());
  DCHECK_EQ(vas_, nullptr);
  VirtualAddressSpace* root_space = GetPlatformVirtualAddressSpace();
#ifdef V8_TARGET_ARCH_64_BIT
  static_assert(kUseContiguousMemory);
  DCHECK(IsAligned(kReservationSize, root_space->allocation_granularity()));
  if (root_space->CanAllocateSubspaces()) {
    auto subspace = root_space->AllocateSubspace(VirtualAddressSpace::kNoHint,
                                                 kReservationSize, kAlignment,
                                                 PagePermissions::kReadWrite);
    vas_ = subspace.release();
    if (kUseSegmentPool) {
      segment_pool_grow_mutex_ = new base::Mutex();
    }
  } else {
    // This may be required on old Windows versions that don't support
    // VirtualAlloc2, which is required for subspaces. In that case, just use a
    // fully-backed emulated subspace.
    Address reservation_base = root_space->AllocatePages(
        VirtualAddressSpace::kNoHint, kReservationSize, kAlignment,
        PagePermissions::kNoAccess);
    if (reservation_base) {
      vas_ = new base::EmulatedVirtualAddressSubspace(
          root_space, reservation_base, kReservationSize, kReservationSize);
    }
    // EmulatedVirtualAddressSubspace does not suppert AllocatePagesArray.
    DCHECK(!kUseSegmentPool);
  }
  if (!vas_) {
    V8::FatalProcessOutOfMemory(
        nullptr, "SegmentedTable::InitializeTable (subspace allocation)");
  }
#else // V8_TARGET_ARCH_64_BIT
  static_assert(!kUseContiguousMemory);
  vas_ = root_space;
#endif
  base_ = reinterpret_cast<Entry*>(vas_->base());
  if constexpr (kUseContiguousMemory && kIsWriteProtected) {
    CHECK(ThreadIsolation::WriteProtectMemory(
        base(), size, PageAllocator::Permission::kNoAccess));
  }
}
References v8::VirtualAddressSpace::AllocatePages(), v8::VirtualAddressSpace::AllocateSubspace(), v8::VirtualAddressSpace::allocation_granularity(), v8::VirtualAddressSpace::CanAllocateSubspaces(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::GetPlatformVirtualAddressSpace(), v8::internal::SegmentedTable< Entry, size >::is_initialized(), IsAligned(), v8::internal::SegmentedTable< Entry, size >::kAlignment, v8::kNoAccess, v8::VirtualAddressSpace::kNoHint, v8::kReadWrite, v8::internal::SegmentedTable< Entry, size >::kUseContiguousMemory, v8::internal::SegmentedTable< Entry, size >::kUseSegmentPool, v8::internal::SegmentedTable< Entry, size >::segment_pool_grow_mutex_, and v8::internal::SegmentedTable< Entry, size >::vas_.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::Initialize().
InitializeFreeList()
template<typename Entry , size_t size>
SegmentedTable< Entry, size >::FreelistHead v8::internal::SegmentedTable< Entry, size >::InitializeFreeList (Segment segment, uint32_t start_offset = 0) [protected]
Definition at line 128 of file segmented-table-inl.h.
                                                                       {
  DCHECK_LT(start_offset, kEntriesPerSegment);
  uint32_t num_entries = kEntriesPerSegment - start_offset;
  uint32_t first = segment.first_entry() + start_offset;
  uint32_t last = segment.last_entry();
  {
    WriteIterator it = iter_at(first);
    while (it.index() != last) {
      it->MakeFreelistEntry(it.index() + 1);
      ++it;
    }
    it->MakeFreelistEntry(0);
  }
  return FreelistHead(first, num_entries);
}
References DCHECK_LT, v8::internal::SegmentedTable< Entry, size >::Segment::first_entry(), v8::internal::SegmentedTable< Entry, size >::WriteIterator::index(), v8::internal::SegmentedTable< Entry, size >::iter_at(), v8::internal::SegmentedTable< Entry, size >::kEntriesPerSegment, and v8::internal::SegmentedTable< Entry, size >::Segment::last_entry().
Referenced by v8::internal::ExternalEntityTable< Entry, size >::TryExtend().
is_initialized()
template<typename Entry , size_t size>
bool v8::internal::SegmentedTable< Entry, size >::is_initialized [protected]
Definition at line 50 of file segmented-table-inl.h.
                                                       {
  DCHECK(!base_ || reinterpret_cast<Address>(base_) == vas_->base());
  return vas_ != nullptr;
}
References v8::VirtualAddressSpace::base(), v8::internal::SegmentedTable< Entry, size >::base_, v8::internal::DCHECK(), and v8::internal::SegmentedTable< Entry, size >::vas_.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::AllocateEntryBelow(), v8::internal::ExternalEntityTable< Entry, size >::AttachSpaceToReadOnlySegments(), v8::internal::SegmentedTable< Entry, size >::base(), v8::internal::ExternalEntityTable< Entry, size >::DetachSpaceFromReadOnlySegments(), v8::internal::SegmentedTable< Entry, size >::Initialize(), v8::internal::ExternalEntityTable< Entry, size >::SealReadOnlySegments(), v8::internal::SegmentedTable< Entry, size >::TearDown(), v8::internal::ExternalEntityTable< Entry, size >::TearDown(), v8::internal::ExternalEntityTable< Entry, size >::TearDownSpace(), v8::internal::ExternalEntityTable< Entry, size >::TryAllocateEntry(), and v8::internal::ExternalEntityTable< Entry, size >::UnsealReadOnlySegments().
iter_at()
template<typename Entry , size_t size>
SegmentedTable< Entry, size >::WriteIterator v8::internal::SegmentedTable< Entry, size >::iter_at (uint32_t index) [protected]
Definition at line 45 of file segmented-table-inl.h.
                                                   {
  return WriteIterator(base_, index);
}
References v8::internal::SegmentedTable< Entry, size >::base_, and v8::internal::index.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::GenericSweep(), and v8::internal::SegmentedTable< Entry, size >::InitializeFreeList().
operator=()
template<typename Entry , size_t size>
SegmentedTable& v8::internal::SegmentedTable< Entry, size >::operator= (const SegmentedTable< Entry, size > &) [protected], [delete]
TearDown()
template<typename Entry , size_t size>
void v8::internal::SegmentedTable< Entry, size >::TearDown [protected]
Definition at line 112 of file segmented-table-inl.h.
                                           {
  DCHECK(is_initialized());
  if (segment_pool_grow_mutex_) {
    delete segment_pool_grow_mutex_;
  }
  base_ = nullptr;
#ifdef V8_TARGET_ARCH_64_BIT
  delete vas_;
#endif
  vas_ = nullptr;
}
References v8::internal::SegmentedTable< Entry, size >::base_, v8::internal::DCHECK(), v8::internal::SegmentedTable< Entry, size >::is_initialized(), v8::internal::SegmentedTable< Entry, size >::segment_pool_grow_mutex_, and v8::internal::SegmentedTable< Entry, size >::vas_.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::TearDown().
TryAllocateAndInitializeSegment()
template<typename Entry , size_t size>
std::optional< std::pair< typename SegmentedTable< Entry, size >::Segment, typename SegmentedTable< Entry, size >::FreelistHead > > v8::internal::SegmentedTable< Entry, size >::TryAllocateAndInitializeSegment [protected]
Definition at line 231 of file segmented-table-inl.h.
                                                             {
  auto segment = TryAllocateSegment();
  if (!segment) return {};
  DCHECK_IMPLIES(!kUseContiguousMemory,
                 (*segment).number() > kNumReadOnlySegments);
  FreelistHead freelist = InitializeFreeList(*segment);
  return {{*segment, freelist}};
}
References v8::internal::SegmentedTable< Entry, size >::TryAllocateSegment().
Referenced by v8::internal::ExternalEntityTable< Entry, size >::TryExtend().
TryAllocateSegment()
template<typename Entry , size_t size>
std::optional< typename SegmentedTable< Entry, size >::Segment > v8::internal::SegmentedTable< Entry, size >::TryAllocateSegment [protected]
Definition at line 169 of file segmented-table-inl.h.
                                                {
  if constexpr (!kUseSegmentPool) {
    Address start =
        vas_->AllocatePages(VirtualAddressSpace::kNoHint, kSegmentSize,
                            kSegmentSize, PagePermissions::kReadWrite);
    if (!start) {
      return {};
    }
    uint32_t offset = static_cast<uint32_t>(start - vas_->base());
    return Segment::At(offset);
  }
  if (auto segment = TryGetSegmentFromPool()) {
    return segment;
  }
  base::MutexGuard guard(*segment_pool_grow_mutex_);
  // Try again to get a segment from the pool with the mutex held. Either
  // another thread filled the pool before us and we should get a segment here,
  // or the pool is guaranteed to be empty and we can proceed to fill it.
  if (auto segment = TryGetSegmentFromPool()) {
    return segment;
  }
  return FillSegmentsPool(true);
}
References v8::VirtualAddressSpace::AllocatePages(), v8::internal::SegmentedTable< Entry, size >::Segment::At(), v8::VirtualAddressSpace::base(), v8::internal::SegmentedTable< Entry, size >::FillSegmentsPool(), v8::VirtualAddressSpace::kNoHint, v8::kReadWrite, v8::internal::SegmentedTable< Entry, size >::kSegmentSize, v8::internal::SegmentedTable< Entry, size >::kUseSegmentPool, v8::internal::SegmentedTable< Entry, size >::segment_pool_grow_mutex_, v8::internal::SegmentedTable< Entry, size >::TryGetSegmentFromPool(), and v8::internal::SegmentedTable< Entry, size >::vas_.
Referenced by v8::internal::SegmentedTable< Entry, size >::TryAllocateAndInitializeSegment().
TryGetSegmentFromPool()
template<typename Entry , size_t size>
std::optional< typename SegmentedTable< Entry, size >::Segment > v8::internal::SegmentedTable< Entry, size >::TryGetSegmentFromPool [protected]
Definition at line 149 of file segmented-table-inl.h.
                                                   {
  DCHECK(kUseSegmentPool);
  for (int i = 0; i < static_cast<int>(kSegmentPoolSize); ++i) {
    uint32_t segment = segment_pool_[i].load(std::memory_order_relaxed);
    if (segment != 0) {
      if (segment_pool_[i].compare_exchange_weak(segment, 0,
                                                 std::memory_order_acq_rel)) {
        return Segment::At(segment);
      } else {
        // Retry if CAS failed. This is needed to ensure the pool really is
        // empty when this method returns {}.
        --i;
      }
    }
  }
  return {};
}
References v8::internal::SegmentedTable< Entry, size >::Segment::At(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::SegmentedTable< Entry, size >::kSegmentPoolSize, v8::internal::SegmentedTable< Entry, size >::kUseSegmentPool, and v8::internal::SegmentedTable< Entry, size >::segment_pool_.
Referenced by v8::internal::SegmentedTable< Entry, size >::TryAllocateSegment().
Member Data Documentation
base_
template<typename Entry , size_t size>
Entry* v8::internal::SegmentedTable< Entry, size >::base_ = nullptr [protected]
Definition at line 247 of file segmented-table.h.
Referenced by v8::internal::SegmentedTable< Entry, size >::at(), v8::internal::SegmentedTable< Entry, size >::base(), v8::internal::SegmentedTable< Entry, size >::is_initialized(), v8::internal::SegmentedTable< Entry, size >::iter_at(), and v8::internal::SegmentedTable< Entry, size >::TearDown().
kAlignment
template<typename Entry , size_t size>
constexpr size_t v8::internal::SegmentedTable< Entry, size >::kAlignment [static], [constexpr], [protected]
Initial value:
=
      kSegmentSize * (kUseSegmentPool ? kSegmentPoolSize : 1)
Definition at line 75 of file segmented-table.h.
Referenced by v8::internal::SegmentedTable< Entry, size >::Initialize(), and v8::internal::ExternalEntityTable< Entry, size >::Initialize().
kEntriesPerSegment
template<typename Entry , size_t size>
constexpr size_t v8::internal::SegmentedTable< Entry, size >::kEntriesPerSegment = kSegmentSize / kEntrySize [static], [constexpr], [protected]
Definition at line 74 of file segmented-table.h.
Referenced by v8::internal::SegmentedTable< Entry, size >::Segment::Containing(), and v8::internal::SegmentedTable< Entry, size >::InitializeFreeList().
kEntrySize
template<typename Entry , size_t size>
constexpr int v8::internal::SegmentedTable< Entry, size >::kEntrySize = sizeof(Entry) [static], [constexpr], [protected]
Definition at line 37 of file segmented-table.h.
kIsWriteProtected
template<typename Entry , size_t size>
constexpr bool v8::internal::SegmentedTable< Entry, size >::kIsWriteProtected = Entry::IsWriteProtected [static], [constexpr], [protected]
Definition at line 36 of file segmented-table.h.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::ZeroInternalNullEntry().
kNumReadOnlySegments
template<typename Entry , size_t size>
constexpr size_t v8::internal::SegmentedTable< Entry, size >::kNumReadOnlySegments [static], [constexpr], [protected]
Initial value:
=
      (kUseSegmentPool ? kSegmentPoolSize : 1)
Definition at line 79 of file segmented-table.h.
kSegmentPoolSize
template<typename Entry , size_t size>
constexpr size_t v8::internal::SegmentedTable< Entry, size >::kSegmentPoolSize = 4 [static], [constexpr], [protected]
Definition at line 73 of file segmented-table.h.
Referenced by v8::internal::SegmentedTable< Entry, size >::FreeTableSegment(), and v8::internal::SegmentedTable< Entry, size >::TryGetSegmentFromPool().
kSegmentSize
template<typename Entry , size_t size>
constexpr size_t v8::internal::SegmentedTable< Entry, size >::kSegmentSize = 16 * KB [static], [constexpr], [protected]
Definition at line 62 of file segmented-table.h.
Referenced by v8::internal::SegmentedTable< Entry, size >::Segment::At(), v8::internal::SegmentedTable< Entry, size >::FreeTableSegment(), and v8::internal::SegmentedTable< Entry, size >::TryAllocateSegment().
kUseContiguousMemory
template<typename Entry , size_t size>
constexpr bool v8::internal::SegmentedTable< Entry, size >::kUseContiguousMemory = false [static], [constexpr], [protected]
Definition at line 56 of file segmented-table.h.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::AttachSpaceToReadOnlySegments(), v8::internal::ExternalEntityTable< Entry, size >::Extend(), v8::internal::SegmentedTable< Entry, size >::Initialize(), v8::internal::ExternalEntityTable< Entry, size >::Initialize(), and v8::internal::ExternalEntityTable< Entry, size >::TearDown().
kUseSegmentPool
template<typename Entry , size_t size>
constexpr bool v8::internal::SegmentedTable< Entry, size >::kUseSegmentPool = false [static], [constexpr], [protected]
Definition at line 57 of file segmented-table.h.
Referenced by v8::internal::SegmentedTable< Entry, size >::FreeTableSegment(), v8::internal::SegmentedTable< Entry, size >::Initialize(), v8::internal::ExternalEntityTable< Entry, size >::Initialize(), v8::internal::SegmentedTable< Entry, size >::TryAllocateSegment(), and v8::internal::SegmentedTable< Entry, size >::TryGetSegmentFromPool().
read_only_segments_used_
template<typename Entry , size_t size>
uint32_t v8::internal::SegmentedTable< Entry, size >::read_only_segments_used_ = 0 [protected]
Definition at line 261 of file segmented-table.h.
Referenced by v8::internal::ExternalEntityTable< Entry, size >::DetachSpaceFromReadOnlySegments(), and v8::internal::ExternalEntityTable< Entry, size >::TryExtend().
segment_pool_
template<typename Entry , size_t size>
std::array<std::atomic<uint32_t>, kSegmentPoolSize> v8::internal::SegmentedTable< Entry, size >::segment_pool_ = {} [protected]
Definition at line 259 of file segmented-table.h.
Referenced by v8::internal::SegmentedTable< Entry, size >::FreeTableSegment(), and v8::internal::SegmentedTable< Entry, size >::TryGetSegmentFromPool().
segment_pool_grow_mutex_
template<typename Entry , size_t size>
base::Mutex* v8::internal::SegmentedTable< Entry, size >::segment_pool_grow_mutex_ = nullptr [protected]
Definition at line 258 of file segmented-table.h.
Referenced by v8::internal::SegmentedTable< Entry, size >::FreeTableSegment(), v8::internal::SegmentedTable< Entry, size >::Initialize(), v8::internal::SegmentedTable< Entry, size >::TearDown(), and v8::internal::SegmentedTable< Entry, size >::TryAllocateSegment().
vas_
template<typename Entry , size_t size>
VirtualAddressSpace* v8::internal::SegmentedTable< Entry, size >::vas_ = nullptr [protected]
Definition at line 252 of file segmented-table.h.
Referenced by v8::internal::SegmentedTable< Entry, size >::FreeTableSegment(), v8::internal::SegmentedTable< Entry, size >::Initialize(), v8::internal::ExternalEntityTable< Entry, size >::Initialize(), v8::internal::SegmentedTable< Entry, size >::is_initialized(), v8::internal::ExternalEntityTable< Entry, size >::SealReadOnlySegments(), v8::internal::SegmentedTable< Entry, size >::TearDown(), v8::internal::ExternalEntityTable< Entry, size >::TearDown(), v8::internal::SegmentedTable< Entry, size >::TryAllocateSegment(), and v8::internal::ExternalEntityTable< Entry, size >::UnsealReadOnlySegments().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/segmented-table.h
/mnt/V8SourceCode/src/common/segmented-table-inl.h