v8::internal::OptimizedCompilationJob Class Reference
#include <compiler.h>
Public Member Functions
OptimizedCompilationJob (const char *compiler_name, State initial_state)
V8_EXPORT_PRIVATE V8_WARN_UNUSED_RESULT Status PrepareJob (Isolate *isolate)
V8_EXPORT_PRIVATE V8_WARN_UNUSED_RESULT Status ExecuteJob (RuntimeCallStats *stats, LocalIsolate *local_isolate=nullptr)
V8_EXPORT_PRIVATE V8_WARN_UNUSED_RESULT Status FinalizeJob (Isolate *isolate)
const char * compiler_name () const
double prepare_in_ms () const
double execute_in_ms () const
double finalize_in_ms () const
V8_WARN_UNUSED_RESULT base::TimeDelta ElapsedTime () const
Protected Member Functions
virtual Status PrepareJobImpl (Isolate *isolate)=0
virtual Status ExecuteJobImpl (RuntimeCallStats *stats, LocalIsolate *local_heap)=0
virtual Status FinalizeJobImpl (Isolate *isolate)=0
GlobalHandleVector< Map > CollectRetainedMaps (Isolate *isolate, DirectHandle< Code > code)
void RegisterWeakObjectsInOptimizedCode (Isolate *isolate, DirectHandle< NativeContext > context, DirectHandle< Code > code, GlobalHandleVector< Map > maps)
Protected Attributes
base::TimeDelta time_taken_to_prepare_
base::TimeDelta time_taken_to_execute_
base::TimeDelta time_taken_to_finalize_
base::ElapsedTimer timer_
Private Attributes
const char *const compiler_name_
Additional Inherited Members
Detailed Description
Definition at line 406 of file compiler.h.
Constructor & Destructor Documentation
OptimizedCompilationJob()
v8::internal::OptimizedCompilationJob::OptimizedCompilationJob (const char * compiler_name, State initial_state) [inline]
Definition at line 408 of file compiler.h.
      : CompilationJob(initial_state), compiler_name_(compiler_name) {
    timer_.Start();
  }
References v8::base::ElapsedTimer::Start(), and timer_.
Member Function Documentation
CollectRetainedMaps()
GlobalHandleVector< Map > v8::internal::OptimizedCompilationJob::CollectRetainedMaps (Isolate * isolate, DirectHandle< Code > code) [protected]
Definition at line 486 of file compiler.cc.
                                               {
  DCHECK(code->is_optimized_code());
  DisallowGarbageCollection no_gc;
  GlobalHandleVector<Map> maps(isolate->heap());
  PtrComprCageBase cage_base(isolate);
  int const mode_mask = RelocInfo::EmbeddedObjectModeMask();
  for (RelocIterator it(*code, mode_mask); !it.done(); it.next()) {
    DCHECK(RelocInfo::IsEmbeddedObjectMode(it.rinfo()->rmode()));
    Tagged<HeapObject> target_object = it.rinfo()->target_object(cage_base);
    if (code->IsWeakObjectInOptimizedCode(target_object)) {
      if (IsMap(target_object, cage_base)) {
        maps.Push(Cast<Map>(target_object));
      }
    }
  }
  return maps;
}
References code, v8::internal::DCHECK(), v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::RelocInfo::EmbeddedObjectModeMask(), v8::internal::Isolate::heap(), v8::internal::RelocInfo::IsEmbeddedObjectMode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::GlobalHandleVector< T >::Push().
Referenced by v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl().
compiler_name()
const char* v8::internal::OptimizedCompilationJob::compiler_name () const [inline]
Definition at line 423 of file compiler.h.
{ return compiler_name_; }
References compiler_name_.
ElapsedTime()
V8_WARN_UNUSED_RESULT base::TimeDelta v8::internal::OptimizedCompilationJob::ElapsedTime () const [inline]
Definition at line 435 of file compiler.h.
                                                          {
    return timer_.Elapsed();
  }
References v8::base::ElapsedTimer::Elapsed(), and timer_.
Referenced by v8::internal::TurbofanCompilationJob::RecordCompilationStats().
execute_in_ms()
double v8::internal::OptimizedCompilationJob::execute_in_ms () const [inline]
Definition at line 428 of file compiler.h.
                               {
    return time_taken_to_execute_.InMillisecondsF();
  }
References v8::base::TimeDelta::InMillisecondsF(), and time_taken_to_execute_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), and v8::internal::Compiler::FinalizeTurbofanCompilationJob().
ExecuteJob()
CompilationJob::Status v8::internal::OptimizedCompilationJob::ExecuteJob (RuntimeCallStats * stats, LocalIsolate * local_isolate = nullptr)
Definition at line 465 of file compiler.cc.
                                                          {
  DCHECK_IMPLIES(local_isolate && !local_isolate->is_main_thread(),
                 local_isolate->heap()->IsParked());
  // Delegate to the underlying implementation.
  DCHECK_EQ(state(), State::kReadyToExecute);
  base::ScopedTimer t(&time_taken_to_execute_);
  return UpdateState(ExecuteJobImpl(stats, local_isolate),
                     State::kReadyToFinalize);
}
References DCHECK_EQ, DCHECK_IMPLIES, ExecuteJobImpl(), v8::internal::LocalIsolate::heap(), v8::internal::LocalIsolate::is_main_thread(), v8::internal::LocalHeap::IsParked(), v8::internal::CompilationJob::kReadyToExecute, v8::internal::CompilationJob::kReadyToFinalize, v8::internal::CompilationJob::state(), time_taken_to_execute_, and v8::internal::CompilationJob::UpdateState().
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), and v8::internal::OptimizingCompileTaskExecutor::RunCompilationJob().
ExecuteJobImpl()
virtual Status v8::internal::OptimizedCompilationJob::ExecuteJobImpl (RuntimeCallStats * stats, LocalIsolate * local_heap) [protected], [pure virtual]
Implemented in v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob, and v8::internal::compiler::PipelineCompilationJob.
Referenced by ExecuteJob().
finalize_in_ms()
double v8::internal::OptimizedCompilationJob::finalize_in_ms () const [inline]
Definition at line 431 of file compiler.h.
                                {
    return time_taken_to_finalize_.InMillisecondsF();
  }
References v8::base::TimeDelta::InMillisecondsF(), and time_taken_to_finalize_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), and v8::internal::Compiler::FinalizeTurbofanCompilationJob().
FinalizeJob()
CompilationJob::Status v8::internal::OptimizedCompilationJob::FinalizeJob (Isolate * isolate)
Definition at line 476 of file compiler.cc.
                                                                          {
  DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
  DisallowJavascriptExecution no_js(isolate);
  // Delegate to the underlying implementation.
  DCHECK_EQ(state(), State::kReadyToFinalize);
  base::ScopedTimer t(&time_taken_to_finalize_);
  return UpdateState(FinalizeJobImpl(isolate), State::kSucceeded);
}
References v8::internal::ThreadId::Current(), DCHECK_EQ, FinalizeJobImpl(), v8::internal::CompilationJob::kReadyToFinalize, v8::internal::CompilationJob::kSucceeded, v8::internal::CompilationJob::state(), v8::internal::Isolate::thread_id(), time_taken_to_finalize_, and v8::internal::CompilationJob::UpdateState().
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::FinalizeJobOnMainThread(), and v8::internal::Compiler::FinalizeTurbofanCompilationJob().
FinalizeJobImpl()
virtual Status v8::internal::OptimizedCompilationJob::FinalizeJobImpl (Isolate * isolate) [protected], [pure virtual]
Implemented in v8::internal::compiler::PipelineCompilationJob, and v8::internal::compiler::CodeAssemblerCompilationJob.
Referenced by FinalizeJob().
prepare_in_ms()
double v8::internal::OptimizedCompilationJob::prepare_in_ms () const [inline]
Definition at line 425 of file compiler.h.
                               {
    return time_taken_to_prepare_.InMillisecondsF();
  }
References v8::base::TimeDelta::InMillisecondsF(), and time_taken_to_prepare_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), and v8::internal::Compiler::FinalizeTurbofanCompilationJob().
PrepareJob()
CompilationJob::Status v8::internal::OptimizedCompilationJob::PrepareJob (Isolate * isolate)
Definition at line 455 of file compiler.cc.
                                                                         {
  DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
  DisallowJavascriptExecution no_js(isolate);
  // Delegate to the underlying implementation.
  DCHECK_EQ(state(), State::kReadyToPrepare);
  base::ScopedTimer t(&time_taken_to_prepare_);
  return UpdateState(PrepareJobImpl(isolate), State::kReadyToExecute);
}
References v8::internal::ThreadId::Current(), DCHECK_EQ, v8::internal::CompilationJob::kReadyToExecute, v8::internal::CompilationJob::kReadyToPrepare, PrepareJobImpl(), v8::internal::CompilationJob::state(), v8::internal::Isolate::thread_id(), time_taken_to_prepare_, and v8::internal::CompilationJob::UpdateState().
Referenced by v8::internal::anonymous_namespace{compiler.cc}::PrepareJobWithHandleScope().
PrepareJobImpl()
virtual Status v8::internal::OptimizedCompilationJob::PrepareJobImpl (Isolate * isolate) [protected], [pure virtual]
Implemented in v8::internal::compiler::PipelineCompilationJob, and v8::internal::compiler::CodeAssemblerCompilationJob.
Referenced by PrepareJob().
RegisterWeakObjectsInOptimizedCode()
void v8::internal::OptimizedCompilationJob::RegisterWeakObjectsInOptimizedCode (Isolate * isolate, DirectHandle< NativeContext > context, DirectHandle< Code > code, GlobalHandleVector< Map > maps) [protected]
Definition at line 506 of file compiler.cc.
                                                           {
  isolate->heap()->AddRetainedMaps(context, std::move(maps));
  code->set_can_have_weak_objects(true);
}
References v8::internal::Heap::AddRetainedMaps(), code, and v8::internal::Isolate::heap().
Referenced by v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl().
Member Data Documentation
compiler_name_
const char* const v8::internal::OptimizedCompilationJob::compiler_name_ [private]
Definition at line 461 of file compiler.h.
Referenced by compiler_name().
time_taken_to_execute_
base::TimeDelta v8::internal::OptimizedCompilationJob::time_taken_to_execute_ [protected]
Definition at line 455 of file compiler.h.
Referenced by execute_in_ms(), ExecuteJob(), v8::internal::TurbofanCompilationJob::RecordCompilationStats(), and v8::internal::TurbofanCompilationJob::RecordFunctionCompilation().
time_taken_to_finalize_
base::TimeDelta v8::internal::OptimizedCompilationJob::time_taken_to_finalize_ [protected]
Definition at line 456 of file compiler.h.
Referenced by finalize_in_ms(), FinalizeJob(), v8::internal::TurbofanCompilationJob::RecordCompilationStats(), and v8::internal::TurbofanCompilationJob::RecordFunctionCompilation().
time_taken_to_prepare_
base::TimeDelta v8::internal::OptimizedCompilationJob::time_taken_to_prepare_ [protected]
Definition at line 454 of file compiler.h.
Referenced by prepare_in_ms(), PrepareJob(), v8::internal::TurbofanCompilationJob::RecordCompilationStats(), and v8::internal::TurbofanCompilationJob::RecordFunctionCompilation().
timer_
base::ElapsedTimer v8::internal::OptimizedCompilationJob::timer_ [protected]
Definition at line 458 of file compiler.h.
Referenced by ElapsedTime(), and OptimizedCompilationJob().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/compiler.h
/mnt/V8SourceCode/src/codegen/compiler.cc