v8::internal::maglev::StoreTaggedFieldWithWriteBarrier Class Reference
#include <maglev-ir.h>
Public Member Functions
StoreTaggedFieldWithWriteBarrier (uint64_t bitfield, int offset, StoreTaggedMode store_mode)
int offset () const
bool initializing_or_transitioning () const
Input & object_input ()
Input & value_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes
static constexpr int kObjectIndex = 0
static constexpr int kValueIndex = 1
Private Types
using Base = FixedInputNodeT< 2, StoreTaggedFieldWithWriteBarrier >
using InitializingOrTransitioningField = NextBitField< bool, 1 >
Private Attributes
const int offset_
Additional Inherited Members
Detailed Description
Definition at line 9102 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::Base = FixedInputNodeT<2, StoreTaggedFieldWithWriteBarrier> [private]
Definition at line 9104 of file maglev-ir.h.
InitializingOrTransitioningField
using v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::InitializingOrTransitioningField = NextBitField<bool, 1> [private]
Definition at line 9141 of file maglev-ir.h.
Constructor & Destructor Documentation
StoreTaggedFieldWithWriteBarrier()
v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::StoreTaggedFieldWithWriteBarrier (uint64_t bitfield, int offset, StoreTaggedMode store_mode) [inline], [explicit]
Definition at line 9107 of file maglev-ir.h.
      : Base(bitfield | InitializingOrTransitioningField::encode(
                            IsInitializingOrTransitioning(store_mode))),
        offset_(offset) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::GenerateCode (MaglevAssembler * , const ProcessingState &)
initializing_or_transitioning()
bool v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::initializing_or_transitioning () const [inline]
Definition at line 9119 of file maglev-ir.h.
                                             {
    return InitializingOrTransitioningField::decode(bitfield());
  }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::MaxCallStackArgs () const
object_input()
Input& v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::object_input () [inline]
Definition at line 9125 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
offset()
int v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::offset () const [inline]
Definition at line 9118 of file maglev-ir.h.
{ return offset_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8259 of file maglev-ir.cc.
                                                               {
  os << "(0x" << std::hex << offset() << std::dec << ")";
}
References offset().
SetValueLocationConstraints()
void v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::SetValueLocationConstraints ()
value_input()
Input& v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::value_input () [inline]
Definition at line 9126 of file maglev-ir.h.
{ return input(kValueIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 9115 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::kObjectIndex = 0 [static], [constexpr]
Definition at line 9123 of file maglev-ir.h.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput().
kProperties
constexpr OpProperties v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::CanWrite() | OpProperties::DeferredCall()
Definition at line 9113 of file maglev-ir.h.
kValueIndex
constexpr int v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::kValueIndex = 1 [static], [constexpr]
Definition at line 9124 of file maglev-ir.h.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput().
offset_
const int v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::offset_ [private]
Definition at line 9143 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc