v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionLength Class Reference
Public Member Functions
DecodeFunctionLength (SectionBuffer *section_buffer, size_t buffer_offset, size_t num_remaining_functions)
std::unique_ptr< DecodingState > NextWithValue (AsyncStreamingDecoder *streaming) override
Private Attributes
SectionBuffer *const section_buffer_
const size_t buffer_offset_
const size_t num_remaining_functions_
Additional Inherited Members
Detailed Description
Definition at line 512 of file streaming-decoder.cc.
Constructor & Destructor Documentation
DecodeFunctionLength()
v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionLength::DecodeFunctionLength (SectionBuffer * section_buffer, size_t buffer_offset, size_t num_remaining_functions) [inline], [explicit]
Definition at line 514 of file streaming-decoder.cc.
      : DecodeVarInt32(kV8MaxWasmFunctionSize, "function body size"),
        section_buffer_(section_buffer),
        buffer_offset_(buffer_offset),
        // We are reading a new function, so one function less is remaining.
        num_remaining_functions_(num_remaining_functions - 1) {
    DCHECK_GT(num_remaining_functions, 0);
  }
References DCHECK_GT.
Member Function Documentation
NextWithValue()
std::unique_ptr< AsyncStreamingDecoder::DecodingState > v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionLength::NextWithValue (AsyncStreamingDecoder * streaming) [override], [virtual]
Implements v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32.
Definition at line 713 of file streaming-decoder.cc.
                                      {
  TRACE_STREAMING("DecodeFunctionLength(%zu)\n", value_);
  // Copy the bytes we consumed into the section buffer.
  base::Vector<uint8_t> fun_length_buffer =
      section_buffer_->bytes() + buffer_offset_;
  if (fun_length_buffer.size() < bytes_consumed_) {
    return streaming->ToErrorState();
  }
  memcpy(fun_length_buffer.begin(), buffer().begin(), bytes_consumed_);
  // {value} is the length of the function.
  if (value_ == 0) return streaming->ToErrorState();
  if (buffer_offset_ + bytes_consumed_ + value_ > section_buffer_->length()) {
    return streaming->ToErrorState();
  }
  return std::make_unique<DecodeFunctionBody>(
      section_buffer_, buffer_offset_ + bytes_consumed_, value_,
      num_remaining_functions_, streaming->module_offset());
}
References v8::base::Vector< T >::begin(), v8::internal::compiler::begin(), v8::internal::wasm::AsyncStreamingDecoder::module_offset(), v8::base::Vector< T >::size(), v8::internal::wasm::AsyncStreamingDecoder::ToErrorState(), and TRACE_STREAMING.
Member Data Documentation
buffer_offset_
const size_t v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionLength::buffer_offset_ [private]
Definition at line 530 of file streaming-decoder.cc.
num_remaining_functions_
const size_t v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionLength::num_remaining_functions_ [private]
Definition at line 531 of file streaming-decoder.cc.
section_buffer_
SectionBuffer* const v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionLength::section_buffer_ [private]
Definition at line 529 of file streaming-decoder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/streaming-decoder.cc