v8::base::VirtualAddressSubspace Class Reference
#include <virtual-address-space.h>
Public Member Functions
~VirtualAddressSubspace () override
void SetRandomSeed (int64_t seed) override
Address RandomPageAddress () override
Address AllocatePages (Address hint, size_t size, size_t alignment, PagePermissions permissions) override
void FreePages (Address address, size_t size) override
bool SetPagePermissions (Address address, size_t size, PagePermissions permissions) override
bool AllocateGuardRegion (Address address, size_t size) override
void FreeGuardRegion (Address address, size_t size) override
Address AllocateSharedPages (Address hint, size_t size, PagePermissions permissions, PlatformSharedMemoryHandle handle, uint64_t offset) override
void FreeSharedPages (Address address, size_t size) override
bool CanAllocateSubspaces () override
std::unique_ptr< v8::VirtualAddressSpace > AllocateSubspace (Address hint, size_t size, size_t alignment, PagePermissions max_page_permissions) override
bool RecommitPages (Address address, size_t size, PagePermissions permissions) override
bool DiscardSystemPages (Address address, size_t size) override
bool DecommitPages (Address address, size_t size) override
Private Member Functions
void FreeSubspace (VirtualAddressSubspace *subspace) override
VirtualAddressSubspace (AddressSpaceReservation reservation, VirtualAddressSpaceBase *parent_space, PagePermissions max_page_permissions)
Private Attributes
AddressSpaceReservation reservation_
Mutex mutex_
RegionAllocator region_allocator_
RandomNumberGenerator rng_
VirtualAddressSpaceBase * parent_space_
Friends
class v8::base::VirtualAddressSpace
Detailed Description
Definition at line 100 of file virtual-address-space.h.
Constructor & Destructor Documentation
 VirtualAddressSubspace()
v8::base::VirtualAddressSubspace::~VirtualAddressSubspace () [override]
Definition at line 218 of file virtual-address-space.cc.
                                                {
  // TODO(chromium:1218005) here or in the RegionAllocator destructor we should
  // assert that all allocations have been freed. Otherwise we may end up
  // leaking memory on Windows because VirtualFree(subspace_base, 0) will then
  // only free the first allocation in the subspace, not the entire subspace.
  parent_space_->FreeSubspace(this);
}
References v8::base::VirtualAddressSpaceBase::FreeSubspace(), and parent_space_.
VirtualAddressSubspace()
v8::base::VirtualAddressSubspace::VirtualAddressSubspace (AddressSpaceReservation reservation, VirtualAddressSpaceBase * parent_space, PagePermissions max_page_permissions) [private]
Definition at line 192 of file virtual-address-space.cc.
    : VirtualAddressSpaceBase(parent_space->page_size(),
                              parent_space->allocation_granularity(),
                              reinterpret_cast<Address>(reservation.base()),
                              reservation.size(), max_page_permissions),
      reservation_(reservation),
      region_allocator_(reinterpret_cast<Address>(reservation.base()),
                        reservation.size(),
                        parent_space->allocation_granularity()),
      parent_space_(parent_space) {
#if V8_OS_WIN
  // On Windows, the address space reservation needs to be split and merged at
  // the OS level as well.
  region_allocator_.set_on_split_callback([this](Address start, size_t size) {
    DCHECK(IsAligned(start, allocation_granularity()));
    CHECK(reservation_.SplitPlaceholder(reinterpret_cast<void*>(start), size));
  });
  region_allocator_.set_on_merge_callback([this](Address start, size_t size) {
    DCHECK(IsAligned(start, allocation_granularity()));
    CHECK(reservation_.MergePlaceholders(reinterpret_cast<void*>(start), size));
  });
#endif // V8_OS_WIN
}
References CHECK, DCHECK, IsAligned(), region_allocator_, reservation_, v8::base::RegionAllocator::set_on_merge_callback(), v8::base::RegionAllocator::set_on_split_callback(), and size().
Member Function Documentation
AllocateGuardRegion()
bool v8::base::VirtualAddressSubspace::AllocateGuardRegion (Address address, size_t size) [override]
Definition at line 289 of file virtual-address-space.cc.
                                                                             {
  DCHECK(IsAligned(address, allocation_granularity()));
  DCHECK(IsAligned(size, allocation_granularity()));
  MutexGuard guard(&mutex_);
  // It is guaranteed that reserved address space is inaccessible, so we just
  // need to mark the region as in-use in the region allocator.
  return region_allocator_.AllocateRegionAt(address, size);
}
References v8::base::RegionAllocator::AllocateRegionAt(), DCHECK, IsAligned(), mutex_, region_allocator_, and size().
AllocatePages()
Address v8::base::VirtualAddressSubspace::AllocatePages (Address hint, size_t size, size_t alignment, PagePermissions permissions) [override]
Definition at line 239 of file virtual-address-space.cc.
                                                                           {
  DCHECK(IsAligned(alignment, allocation_granularity()));
  DCHECK(IsAligned(hint, alignment));
  DCHECK(IsAligned(size, allocation_granularity()));
  DCHECK(IsSubset(permissions, max_page_permissions()));
  MutexGuard guard(&mutex_);
  Address address = region_allocator_.AllocateRegion(hint, size, alignment);
  if (address == RegionAllocator::kAllocationFailure) return kNullAddress;
  if (!reservation_.Allocate(reinterpret_cast<void*>(address), size,
                             static_cast<OS::MemoryPermission>(permissions))) {
    // This most likely means that we ran out of memory.
    CHECK_EQ(size, region_allocator_.FreeRegion(address));
    return kNullAddress;
  }
  return address;
}
References v8::base::AddressSpaceReservation::Allocate(), v8::base::RegionAllocator::AllocateRegion(), CHECK_EQ, DCHECK, v8::base::RegionAllocator::FreeRegion(), IsAligned(), v8::base::IsSubset(), v8::base::RegionAllocator::kAllocationFailure, v8::base::kNullAddress, mutex_, region_allocator_, reservation_, and size().
AllocateSharedPages()
Address v8::base::VirtualAddressSubspace::AllocateSharedPages (Address hint, size_t size, PagePermissions permissions, PlatformSharedMemoryHandle handle, uint64_t offset) [override]
Definition at line 308 of file virtual-address-space.cc.
                                                        {
  DCHECK(IsAligned(hint, allocation_granularity()));
  DCHECK(IsAligned(size, allocation_granularity()));
  DCHECK(IsAligned(offset, allocation_granularity()));
  MutexGuard guard(&mutex_);
  Address address =
      region_allocator_.AllocateRegion(hint, size, allocation_granularity());
  if (address == RegionAllocator::kAllocationFailure) return kNullAddress;
  if (!reservation_.AllocateShared(
          reinterpret_cast<void*>(address), size,
          static_cast<OS::MemoryPermission>(permissions), handle, offset)) {
    CHECK_EQ(size, region_allocator_.FreeRegion(address));
    return kNullAddress;
  }
  return address;
}
References v8::base::RegionAllocator::AllocateRegion(), v8::base::AddressSpaceReservation::AllocateShared(), CHECK_EQ, DCHECK, v8::base::RegionAllocator::FreeRegion(), v8::internal::handle(), IsAligned(), v8::base::RegionAllocator::kAllocationFailure, v8::base::kNullAddress, mutex_, region_allocator_, reservation_, and size().
AllocateSubspace()
std::unique_ptr< v8::VirtualAddressSpace > v8::base::VirtualAddressSubspace::AllocateSubspace (Address hint, size_t size, size_t alignment, PagePermissions max_page_permissions) [override]
Definition at line 344 of file virtual-address-space.cc.
                                                                               {
  DCHECK(IsAligned(alignment, allocation_granularity()));
  DCHECK(IsAligned(hint, alignment));
  DCHECK(IsAligned(size, allocation_granularity()));
  DCHECK(IsSubset(max_page_permissions, this->max_page_permissions()));
  MutexGuard guard(&mutex_);
  Address address = region_allocator_.AllocateRegion(hint, size, alignment);
  if (address == RegionAllocator::kAllocationFailure) {
    return std::unique_ptr<v8::VirtualAddressSpace>();
  }
  std::optional<AddressSpaceReservation> reservation =
      reservation_.CreateSubReservation(
          reinterpret_cast<void*>(address), size,
          static_cast<OS::MemoryPermission>(max_page_permissions));
  if (!reservation.has_value()) {
    CHECK_EQ(size, region_allocator_.FreeRegion(address));
    return nullptr;
  }
  return std::unique_ptr<v8::VirtualAddressSpace>(
      new VirtualAddressSubspace(*reservation, this, max_page_permissions));
}
References v8::base::RegionAllocator::AllocateRegion(), CHECK_EQ, v8::base::AddressSpaceReservation::CreateSubReservation(), DCHECK, v8::base::RegionAllocator::FreeRegion(), IsAligned(), v8::base::IsSubset(), v8::base::RegionAllocator::kAllocationFailure, mutex_, region_allocator_, reservation_, size(), and v8::base::VirtualAddressSpaceBase::VirtualAddressSubspace.
CanAllocateSubspaces()
bool v8::base::VirtualAddressSubspace::CanAllocateSubspaces () [inline], [override]
Definition at line 127 of file virtual-address-space.h.
{ return true; }
DecommitPages()
bool v8::base::VirtualAddressSubspace::DecommitPages (Address address, size_t size) [override]
Definition at line 390 of file virtual-address-space.cc.
                                                                       {
  DCHECK(IsAligned(address, page_size()));
  DCHECK(IsAligned(size, page_size()));
  return reservation_.DecommitPages(reinterpret_cast<void*>(address), size);
}
References DCHECK, v8::base::AddressSpaceReservation::DecommitPages(), IsAligned(), reservation_, and size().
DiscardSystemPages()
bool v8::base::VirtualAddressSubspace::DiscardSystemPages (Address address, size_t size) [override]
Definition at line 382 of file virtual-address-space.cc.
                                                                            {
  DCHECK(IsAligned(address, page_size()));
  DCHECK(IsAligned(size, page_size()));
  return reservation_.DiscardSystemPages(reinterpret_cast<void*>(address),
                                         size);
}
References DCHECK, v8::base::AddressSpaceReservation::DiscardSystemPages(), IsAligned(), reservation_, and size().
FreeGuardRegion()
void v8::base::VirtualAddressSubspace::FreeGuardRegion (Address address, size_t size) [override]
Definition at line 300 of file virtual-address-space.cc.
                                                                         {
  DCHECK(IsAligned(address, allocation_granularity()));
  DCHECK(IsAligned(size, allocation_granularity()));
  MutexGuard guard(&mutex_);
  CHECK_EQ(size, region_allocator_.FreeRegion(address));
}
References CHECK_EQ, DCHECK, v8::base::RegionAllocator::FreeRegion(), IsAligned(), mutex_, region_allocator_, and size().
FreePages()
void v8::base::VirtualAddressSubspace::FreePages (Address address, size_t size) [override]
Definition at line 262 of file virtual-address-space.cc.
                                                                   {
  DCHECK(IsAligned(address, allocation_granularity()));
  DCHECK(IsAligned(size, allocation_granularity()));
  MutexGuard guard(&mutex_);
  // The order here is important: on Windows, the allocation first has to be
  // freed to a placeholder before the placeholder can be merged (during the
  // merge_callback) with any surrounding placeholder mappings.
  if (!reservation_.Free(reinterpret_cast<void*>(address), size)) {
    // This can happen due to an out-of-memory condition, such as running out
    // of available VMAs for the process.
    FatalOOM(OOMType::kProcess, "VirtualAddressSubspace::FreePages");
  }
  CHECK_EQ(size, region_allocator_.FreeRegion(address));
}
References CHECK_EQ, DCHECK, v8::base::FatalOOM(), v8::base::AddressSpaceReservation::Free(), v8::base::RegionAllocator::FreeRegion(), IsAligned(), v8::base::kProcess, mutex_, region_allocator_, reservation_, and size().
FreeSharedPages()
void v8::base::VirtualAddressSubspace::FreeSharedPages (Address address, size_t size) [override]
Definition at line 331 of file virtual-address-space.cc.
                                                                         {
  DCHECK(IsAligned(address, allocation_granularity()));
  DCHECK(IsAligned(size, allocation_granularity()));
  MutexGuard guard(&mutex_);
  // The order here is important: on Windows, the allocation first has to be
  // freed to a placeholder before the placeholder can be merged (during the
  // merge_callback) with any surrounding placeholder mappings.
  CHECK(reservation_.FreeShared(reinterpret_cast<void*>(address), size));
  CHECK_EQ(size, region_allocator_.FreeRegion(address));
}
References CHECK, CHECK_EQ, DCHECK, v8::base::RegionAllocator::FreeRegion(), v8::base::AddressSpaceReservation::FreeShared(), IsAligned(), mutex_, region_allocator_, reservation_, and size().
FreeSubspace()
void v8::base::VirtualAddressSubspace::FreeSubspace (VirtualAddressSubspace * subspace) [override], [private], [virtual]
Implements v8::base::VirtualAddressSpaceBase.
Definition at line 397 of file virtual-address-space.cc.
                                                                          {
  MutexGuard guard(&mutex_);
  AddressSpaceReservation reservation = subspace->reservation_;
  Address base = reinterpret_cast<Address>(reservation.base());
  CHECK_EQ(reservation.size(), region_allocator_.FreeRegion(base));
  CHECK(reservation_.FreeSubReservation(reservation));
}
References v8::base::AddressSpaceReservation::base(), CHECK, CHECK_EQ, v8::base::RegionAllocator::FreeRegion(), v8::base::AddressSpaceReservation::FreeSubReservation(), mutex_, region_allocator_, reservation_, and v8::base::AddressSpaceReservation::size().
RandomPageAddress()
Address v8::base::VirtualAddressSubspace::RandomPageAddress () [override]
Definition at line 231 of file virtual-address-space.cc.
                                                  {
  MutexGuard guard(&mutex_);
  // Note: the random numbers generated here aren't uniformly distributed if the
  // size isn't a power of two.
  Address addr = base() + (static_cast<uint64_t>(rng_.NextInt64()) % size());
  return RoundDown(addr, allocation_granularity());
}
References mutex_, v8::base::RandomNumberGenerator::NextInt64(), rng_, RoundDown(), and size().
RecommitPages()
bool v8::base::VirtualAddressSubspace::RecommitPages (Address address, size_t size, PagePermissions permissions) [override]
Definition at line 371 of file virtual-address-space.cc.
                                                                        {
  DCHECK(IsAligned(address, page_size()));
  DCHECK(IsAligned(size, page_size()));
  DCHECK(IsSubset(permissions, max_page_permissions()));
  return reservation_.RecommitPages(
      reinterpret_cast<void*>(address), size,
      static_cast<OS::MemoryPermission>(permissions));
}
References DCHECK, IsAligned(), v8::base::IsSubset(), v8::base::AddressSpaceReservation::RecommitPages(), reservation_, and size().
SetPagePermissions()
bool v8::base::VirtualAddressSubspace::SetPagePermissions (Address address, size_t size, PagePermissions permissions) [override]
Definition at line 278 of file virtual-address-space.cc.
                                                                             {
  DCHECK(IsAligned(address, page_size()));
  DCHECK(IsAligned(size, page_size()));
  DCHECK(IsSubset(permissions, max_page_permissions()));
  return reservation_.SetPermissions(
      reinterpret_cast<void*>(address), size,
      static_cast<OS::MemoryPermission>(permissions));
}
References DCHECK, IsAligned(), v8::base::IsSubset(), reservation_, v8::base::AddressSpaceReservation::SetPermissions(), and size().
SetRandomSeed()
void v8::base::VirtualAddressSubspace::SetRandomSeed (int64_t seed) [override]
Definition at line 226 of file virtual-address-space.cc.
                                                       {
  MutexGuard guard(&mutex_);
  rng_.SetSeed(seed);
}
References mutex_, rng_, and v8::base::RandomNumberGenerator::SetSeed().
Friends And Related Function Documentation
v8::base::VirtualAddressSpace
friend class v8::base::VirtualAddressSpace [friend]
Definition at line 143 of file virtual-address-space.h.
Member Data Documentation
mutex_
Mutex v8::base::VirtualAddressSubspace::mutex_ [private]
Definition at line 156 of file virtual-address-space.h.
Referenced by AllocateGuardRegion(), AllocatePages(), AllocateSharedPages(), AllocateSubspace(), FreeGuardRegion(), FreePages(), FreeSharedPages(), FreeSubspace(), RandomPageAddress(), and SetRandomSeed().
parent_space_
VirtualAddressSpaceBase* v8::base::VirtualAddressSubspace::parent_space_ [private]
Definition at line 167 of file virtual-address-space.h.
Referenced by ~VirtualAddressSubspace().
region_allocator_
RegionAllocator v8::base::VirtualAddressSubspace::region_allocator_ [private]
Definition at line 160 of file virtual-address-space.h.
Referenced by AllocateGuardRegion(), AllocatePages(), AllocateSharedPages(), AllocateSubspace(), FreeGuardRegion(), FreePages(), FreeSharedPages(), FreeSubspace(), and VirtualAddressSubspace().
reservation_
AddressSpaceReservation v8::base::VirtualAddressSubspace::reservation_ [private]
Definition at line 152 of file virtual-address-space.h.
Referenced by AllocatePages(), AllocateSharedPages(), AllocateSubspace(), DecommitPages(), DiscardSystemPages(), FreePages(), FreeSharedPages(), v8::base::VirtualAddressSpace::FreeSubspace(), FreeSubspace(), RecommitPages(), SetPagePermissions(), and VirtualAddressSubspace().
rng_
RandomNumberGenerator v8::base::VirtualAddressSubspace::rng_ [private]
Definition at line 163 of file virtual-address-space.h.
Referenced by RandomPageAddress(), and SetRandomSeed().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/virtual-address-space.h
/mnt/V8SourceCode/src/base/virtual-address-space.cc