v8::internal::ArrowHeadParsingScope< Types > Class Template Reference
#include <expression-scope.h>
Public Types
using ParserT = typename Types::Impl
using ScopeType = typename ExpressionScope< Types >::ScopeType
Public Member Functions
ArrowHeadParsingScope (ParserT *parser, FunctionKind kind, int function_literal_id)
ArrowHeadParsingScope (const ArrowHeadParsingScope &)=delete
ArrowHeadParsingScope & operator= (const ArrowHeadParsingScope &)=delete
void ValidateExpression ()
DeclarationScope * ValidateAndCreateScope ()
void RecordDeclarationError (const Scanner::Location &loc, MessageTemplate message)
void RecordNonSimpleParameter ()
void RecordThisUse ()
int function_literal_id () const
Private Member Functions
FunctionKind kind () const
Private Attributes
Scanner::Location declaration_error_location = Scanner::Location::invalid()
MessageTemplate declaration_error_message = MessageTemplate::kNone
int function_literal_id_
bool has_simple_parameter_list_ = true
bool uses_this_ = false
Additional Inherited Members
Detailed Description
template<typename Types>
class v8::internal::ArrowHeadParsingScope< Types >
Definition at line 745 of file expression-scope.h.
Member Typedef Documentation
ParserT
template<typename Types >
using v8::internal::ArrowHeadParsingScope< Types >::ParserT = typename Types::Impl
Definition at line 747 of file expression-scope.h.
ScopeType
template<typename Types >
using v8::internal::ArrowHeadParsingScope< Types >::ScopeType = typename ExpressionScope<Types>::ScopeType
Definition at line 748 of file expression-scope.h.
Constructor & Destructor Documentation
ArrowHeadParsingScope() [1/2]
template<typename Types >
v8::internal::ArrowHeadParsingScope< Types >::ArrowHeadParsingScope (ParserT * parser, FunctionKind kind, int function_literal_id) [inline]
Definition at line 750 of file expression-scope.h.
      : ExpressionParsingScope<Types>(
            parser,
            kind == FunctionKind::kArrowFunction
                ? ExpressionScope<Types>::kMaybeArrowParameterDeclaration
                : ExpressionScope<Types>::kMaybeAsyncArrowParameterDeclaration),
        function_literal_id_(function_literal_id) {
    DCHECK(kind == FunctionKind::kAsyncArrowFunction ||
           kind == FunctionKind::kArrowFunction);
    DCHECK(this->CanBeDeclaration());
    DCHECK(!this->IsCertainlyDeclaration());
    // clear last next_arrow_function_info tracked strict parameters error.
    parser->next_arrow_function_info_.ClearStrictParameterError();
  }
References v8::internal::ExpressionScope< Types >::CanBeDeclaration(), v8::internal::DCHECK(), v8::internal::ExpressionScope< Types >::IsCertainlyDeclaration(), v8::internal::kArrowFunction, v8::internal::kAsyncArrowFunction, and v8::internal::ArrowHeadParsingScope< Types >::kind().
ArrowHeadParsingScope() [2/2]
template<typename Types >
v8::internal::ArrowHeadParsingScope< Types >::ArrowHeadParsingScope (const ArrowHeadParsingScope< Types > &) [delete]
Member Function Documentation
function_literal_id()
template<typename Types >
int v8::internal::ArrowHeadParsingScope< Types >::function_literal_id () const [inline]
Definition at line 829 of file expression-scope.h.
{ return function_literal_id_; }
References v8::internal::ArrowHeadParsingScope< Types >::function_literal_id_.
kind()
template<typename Types >
FunctionKind v8::internal::ArrowHeadParsingScope< Types >::kind () const [inline], [private]
Definition at line 832 of file expression-scope.h.
                            {
    return this->IsAsyncArrowHeadParsingScope()
               ? FunctionKind::kAsyncArrowFunction
               : FunctionKind::kArrowFunction;
  }
References v8::internal::ExpressionScope< Types >::IsAsyncArrowHeadParsingScope(), v8::internal::kArrowFunction, and v8::internal::kAsyncArrowFunction.
Referenced by v8::internal::ArrowHeadParsingScope< Types >::ArrowHeadParsingScope(), and v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope().
operator=()
template<typename Types >
ArrowHeadParsingScope& v8::internal::ArrowHeadParsingScope< Types >::operator= (const ArrowHeadParsingScope< Types > &) [delete]
RecordDeclarationError()
template<typename Types >
void v8::internal::ArrowHeadParsingScope< Types >::RecordDeclarationError (const Scanner::Location & loc, MessageTemplate message) [inline]
Definition at line 820 of file expression-scope.h.
                                                       {
    DCHECK_IMPLIES(!this->has_error(), loc.IsValid());
    declaration_error_location = loc;
    declaration_error_message = message;
  }
References DCHECK_IMPLIES, v8::internal::ArrowHeadParsingScope< Types >::declaration_error_location, v8::internal::ArrowHeadParsingScope< Types >::declaration_error_message, and v8::internal::loc.
RecordNonSimpleParameter()
template<typename Types >
void v8::internal::ArrowHeadParsingScope< Types >::RecordNonSimpleParameter () [inline]
Definition at line 827 of file expression-scope.h.
{ has_simple_parameter_list_ = false; }
References v8::internal::ArrowHeadParsingScope< Types >::has_simple_parameter_list_.
RecordThisUse()
template<typename Types >
void v8::internal::ArrowHeadParsingScope< Types >::RecordThisUse () [inline]
Definition at line 828 of file expression-scope.h.
{ uses_this_ = true; }
References v8::internal::ArrowHeadParsingScope< Types >::uses_this_.
ValidateAndCreateScope()
template<typename Types >
DeclarationScope* v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope () [inline]
Definition at line 778 of file expression-scope.h.
                                             {
    DCHECK(!this->is_verified());
    DeclarationScope* result = this->parser()->NewFunctionScope(kind());
    if (declaration_error_location.IsValid()) {
      ExpressionScope<Types>::Report(declaration_error_location,
                                     declaration_error_message);
      return result;
    }
    this->ValidatePattern();
    if (!has_simple_parameter_list_) result->SetHasNonSimpleParameters();
    VariableKind kind = PARAMETER_VARIABLE;
    VariableMode mode =
        has_simple_parameter_list_ ? VariableMode::kVar : VariableMode::kLet;
    for (auto& proxy_initializer_pair : *this->variable_list()) {
      VariableProxy* proxy = proxy_initializer_pair.first;
      int initializer_position = proxy_initializer_pair.second;
      // Default values for parameters will have been parsed as assignments so
      // clear the is_assigned bit as they are not actually assignments.
      proxy->clear_is_assigned();
      bool was_added;
      this->parser()->DeclareAndBindVariable(proxy, kind, mode, result,
                                             &was_added, initializer_position);
      if (!was_added) {
        ExpressionScope<Types>::Report(proxy->location(),
                                       MessageTemplate::kParamDupe);
      }
    }
#ifdef DEBUG
    if (!this->has_error()) {
      for (auto declaration : *result->declarations()) {
        DCHECK_NE(declaration->var()->initializer_position(),
                  kNoSourcePosition);
      }
    }
#endif // DEBUG
    if (uses_this_) result->UsesThis();
    return result;
  }
References v8::internal::VariableProxy::clear_is_assigned(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::ArrowHeadParsingScope< Types >::declaration_error_location, v8::internal::ArrowHeadParsingScope< Types >::declaration_error_message, v8::internal::ArrowHeadParsingScope< Types >::has_simple_parameter_list_, v8::internal::ExpressionParsingScope< Types >::is_verified(), v8::internal::Scanner::Location::IsValid(), v8::internal::ArrowHeadParsingScope< Types >::kind(), v8::internal::kLet, v8::internal::kNoSourcePosition, v8::internal::kVar, v8::internal::VariableProxy::location(), mode(), v8::internal::PARAMETER_VARIABLE, v8::internal::ExpressionScope< Types >::parser(), v8::internal::ExpressionScope< Types >::Report(), v8::base::internal::result, v8::internal::DeclarationScope::SetHasNonSimpleParameters(), v8::internal::ArrowHeadParsingScope< Types >::uses_this_, v8::internal::ExpressionParsingScope< Types >::ValidatePattern(), and v8::internal::ExpressionParsingScope< Types >::variable_list().
ValidateExpression()
template<typename Types >
void v8::internal::ArrowHeadParsingScope< Types >::ValidateExpression () [inline]
Definition at line 769 of file expression-scope.h.
                            {
    // Turns out this is not an arrow head. Clear any possible tracked strict
    // parameter errors, and reinterpret tracked variables as unresolved
    // references.
    this->parser()->next_arrow_function_info_.ClearStrictParameterError();
    ExpressionParsingScope<Types>::ValidateExpression();
    this->parent()->MergeVariableList(this->variable_list());
  }
References v8::internal::ExpressionScope< Types >::MergeVariableList(), v8::internal::ExpressionScope< Types >::parent(), v8::internal::ExpressionScope< Types >::parser(), v8::internal::ExpressionParsingScope< Types >::ValidateExpression(), and v8::internal::ExpressionParsingScope< Types >::variable_list().
Member Data Documentation
declaration_error_location
template<typename Types >
Scanner::Location v8::internal::ArrowHeadParsingScope< Types >::declaration_error_location = Scanner::Location::invalid() [private]
Definition at line 838 of file expression-scope.h.
Referenced by v8::internal::ArrowHeadParsingScope< Types >::RecordDeclarationError(), and v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope().
declaration_error_message
template<typename Types >
MessageTemplate v8::internal::ArrowHeadParsingScope< Types >::declaration_error_message = MessageTemplate::kNone [private]
Definition at line 839 of file expression-scope.h.
Referenced by v8::internal::ArrowHeadParsingScope< Types >::RecordDeclarationError(), and v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope().
function_literal_id_
template<typename Types >
int v8::internal::ArrowHeadParsingScope< Types >::function_literal_id_ [private]
Definition at line 840 of file expression-scope.h.
Referenced by v8::internal::ArrowHeadParsingScope< Types >::function_literal_id().
has_simple_parameter_list_
template<typename Types >
bool v8::internal::ArrowHeadParsingScope< Types >::has_simple_parameter_list_ = true [private]
Definition at line 841 of file expression-scope.h.
Referenced by v8::internal::ArrowHeadParsingScope< Types >::RecordNonSimpleParameter(), and v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope().
uses_this_
template<typename Types >
bool v8::internal::ArrowHeadParsingScope< Types >::uses_this_ = false [private]
Definition at line 842 of file expression-scope.h.
Referenced by v8::internal::ArrowHeadParsingScope< Types >::RecordThisUse(), and v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/expression-scope.h