v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionPayload Class Reference
Public Member Functions
DecodeSectionPayload (SectionBuffer *section_buffer)
base::Vector< uint8_t > buffer () override
std::unique_ptr< DecodingState > Next (AsyncStreamingDecoder *streaming) override
Private Attributes
SectionBuffer *const section_buffer_
Detailed Description
Definition at line 485 of file streaming-decoder.cc.
Constructor & Destructor Documentation
DecodeSectionPayload()
v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionPayload::DecodeSectionPayload (SectionBuffer * section_buffer) [inline], [explicit]
Definition at line 487 of file streaming-decoder.cc.
      : section_buffer_(section_buffer) {}
Member Function Documentation
buffer()
base::Vector<uint8_t> v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionPayload::buffer () [inline], [override], [virtual]
Implements v8::internal::wasm::AsyncStreamingDecoder::DecodingState.
Definition at line 490 of file streaming-decoder.cc.
{ return section_buffer_->payload(); }
Next()
std::unique_ptr< AsyncStreamingDecoder::DecodingState > v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionPayload::Next (AsyncStreamingDecoder * streaming) [override], [virtual]
Implements v8::internal::wasm::AsyncStreamingDecoder::DecodingState.
Definition at line 670 of file streaming-decoder.cc.
                                      {
  TRACE_STREAMING("DecodeSectionPayload\n");
  streaming->ProcessSection(section_buffer_);
  if (!streaming->ok()) return nullptr;
  return std::make_unique<DecodeSectionID>(streaming->module_offset());
}
References v8::internal::wasm::AsyncStreamingDecoder::module_offset(), v8::internal::wasm::AsyncStreamingDecoder::ok(), v8::internal::wasm::AsyncStreamingDecoder::ProcessSection(), and TRACE_STREAMING.
Member Data Documentation
section_buffer_
SectionBuffer* const v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionPayload::section_buffer_ [private]
Definition at line 496 of file streaming-decoder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/streaming-decoder.cc