v8::PromiseRejectMessage Class Reference
#include <v8-promise.h>
Public Member Functions
PromiseRejectMessage (Local< Promise > promise, PromiseRejectEvent event, Local< Value > value)
Local< Promise > GetPromise () const
PromiseRejectEvent GetEvent () const
Local< Value > GetValue () const
Private Attributes
Local< Promise > promise_
PromiseRejectEvent event_
Local< Value > value_
Detailed Description
Definition at line 154 of file v8-promise.h.
Constructor & Destructor Documentation
PromiseRejectMessage()
v8::PromiseRejectMessage::PromiseRejectMessage (Local< Promise > promise, PromiseRejectEvent event, Local< Value > value) [inline]
Definition at line 156 of file v8-promise.h.
      : promise_(promise), event_(event), value_(value) {}
Member Function Documentation
GetEvent()
PromiseRejectEvent v8::PromiseRejectMessage::GetEvent () const [inline]
Definition at line 161 of file v8-promise.h.
{ return event_; }
References event_.
Referenced by v8::Shell::PromiseRejectCallback().
GetPromise()
Local<Promise> v8::PromiseRejectMessage::GetPromise () const [inline]
Definition at line 160 of file v8-promise.h.
{ return promise_; }
References promise_.
Referenced by v8::Shell::PromiseRejectCallback().
GetValue()
Local<Value> v8::PromiseRejectMessage::GetValue () const [inline]
Definition at line 162 of file v8-promise.h.
{ return value_; }
References value_.
Referenced by v8::Shell::PromiseRejectCallback().
Member Data Documentation
event_
PromiseRejectEvent v8::PromiseRejectMessage::event_ [private]
Definition at line 166 of file v8-promise.h.
Referenced by GetEvent().
promise_
Local<Promise> v8::PromiseRejectMessage::promise_ [private]
Definition at line 165 of file v8-promise.h.
Referenced by GetPromise().
value_
Local<Value> v8::PromiseRejectMessage::value_ [private]
Definition at line 167 of file v8-promise.h.
Referenced by GetValue().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-promise.h