v8::internal::compiler::DeadCodeElimination Class Reference
#include <dead-code-elimination.h>
Public Member Functions
DeadCodeElimination (Editor *editor, TFGraph *graph, CommonOperatorBuilder *common, Zone *temp_zone)
~DeadCodeElimination () final=default
DeadCodeElimination (const DeadCodeElimination &)=delete
DeadCodeElimination & operator= (const DeadCodeElimination &)=delete
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Member Functions
Reduction ReduceEnd (Node *node)
Reduction ReduceLoopOrMerge (Node *node)
Reduction ReduceLoopExit (Node *node)
Reduction ReduceNode (Node *node)
Reduction ReducePhi (Node *node)
Reduction ReduceEffectPhi (Node *node)
Reduction ReducePureNode (Node *node)
Reduction ReduceUnreachableOrIfException (Node *node)
Reduction ReduceEffectNode (Node *node)
Reduction ReduceDeoptimizeOrReturnOrTerminateOrTailCall (Node *node)
Reduction ReduceBranchOrSwitch (Node *node)
Reduction RemoveLoopExit (Node *node)
Reduction PropagateDeadControl (Node *node)
void TrimMergeOrPhi (Node *node, int size)
Node * DeadValue (Node *none_node, MachineRepresentation rep=MachineRepresentation::kNone)
TFGraph * graph () const
CommonOperatorBuilder * common () const
Node * dead () const
Private Attributes
TFGraph *const graph_
CommonOperatorBuilder *const common_
Node *const dead_
Zone * zone_
Detailed Description
Definition at line 38 of file dead-code-elimination.h.
Constructor & Destructor Documentation
DeadCodeElimination() [1/2]
v8::internal::compiler::DeadCodeElimination::DeadCodeElimination (Editor * editor, TFGraph * graph, CommonOperatorBuilder * common, Zone * temp_zone)
Definition at line 16 of file dead-code-elimination.cc.
    : AdvancedReducer(editor),
      graph_(graph),
      common_(common),
      dead_(graph->NewNode(common->Dead())),
      zone_(temp_zone) {
  NodeProperties::SetType(dead_, Type::None());
}
References dead_, v8::internal::compiler::turboshaft::Type::None(), and v8::internal::compiler::NodeProperties::SetType().
 DeadCodeElimination()
v8::internal::compiler::DeadCodeElimination::~DeadCodeElimination () [final], [default]
DeadCodeElimination() [2/2]
v8::internal::compiler::DeadCodeElimination::DeadCodeElimination (const DeadCodeElimination &) [delete]
Member Function Documentation
common()
CommonOperatorBuilder* v8::internal::compiler::DeadCodeElimination::common () const [inline], [private]
Definition at line 73 of file dead-code-elimination.h.
{ return common_; }
Referenced by DeadValue(), ReduceDeoptimizeOrReturnOrTerminateOrTailCall(), ReduceEffectNode(), ReduceEnd(), and TrimMergeOrPhi().
dead()
Node* v8::internal::compiler::DeadCodeElimination::dead () const [inline], [private]
Definition at line 74 of file dead-code-elimination.h.
{ return dead_; }
Referenced by ReduceBranchOrSwitch(), ReduceEnd(), and ReduceLoopOrMerge().
DeadValue()
Node * v8::internal::compiler::DeadCodeElimination::DeadValue (Node * none_node, MachineRepresentation rep = MachineRepresentation::kNone) [private]
Definition at line 373 of file dead-code-elimination.cc.
                                                                          {
  if (node->opcode() == IrOpcode::kDeadValue) {
    if (rep == DeadValueRepresentationOf(node->op())) return node;
    node = NodeProperties::GetValueInput(node, 0);
  }
  Node* dead_value = graph()->NewNode(common()->DeadValue(rep), node);
  NodeProperties::SetType(dead_value, Type::None());
  return dead_value;
}
References common(), v8::internal::compiler::DeadValueRepresentationOf(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::NodeProperties::SetType().
Referenced by ReduceEffectNode(), ReducePhi(), and ReducePureNode().
graph()
TFGraph* v8::internal::compiler::DeadCodeElimination::graph () const [inline], [private]
Definition at line 72 of file dead-code-elimination.h.
{ return graph_; }
Referenced by DeadValue(), ReduceDeoptimizeOrReturnOrTerminateOrTailCall(), and ReduceEffectNode().
operator=()
DeadCodeElimination& v8::internal::compiler::DeadCodeElimination::operator= (const DeadCodeElimination &) [delete]
PropagateDeadControl()
Reduction v8::internal::compiler::DeadCodeElimination::PropagateDeadControl (Node * node) [private]
Definition at line 79 of file dead-code-elimination.cc.
                                                              {
  DCHECK_EQ(1, node->op()->ControlInputCount());
  Node* control = NodeProperties::GetControlInput(node);
  if (control->opcode() == IrOpcode::kDead) return Replace(control);
  return NoChange();
}
References v8::internal::compiler::Operator::ControlInputCount(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by Reduce(), ReduceBranchOrSwitch(), ReduceDeoptimizeOrReturnOrTerminateOrTailCall(), ReduceEffectPhi(), ReduceNode(), ReducePhi(), and ReduceUnreachableOrIfException().
Reduce()
Reduction v8::internal::compiler::DeadCodeElimination::Reduce (Node * node) [final]
Definition at line 47 of file dead-code-elimination.cc.
                                                {
  switch (node->opcode()) {
    case IrOpcode::kEnd:
      return ReduceEnd(node);
    case IrOpcode::kLoop:
    case IrOpcode::kMerge:
      return ReduceLoopOrMerge(node);
    case IrOpcode::kLoopExit:
      return ReduceLoopExit(node);
    case IrOpcode::kUnreachable:
    case IrOpcode::kIfException:
      return ReduceUnreachableOrIfException(node);
    case IrOpcode::kPhi:
      return ReducePhi(node);
    case IrOpcode::kEffectPhi:
      return ReduceEffectPhi(node);
    case IrOpcode::kDeoptimize:
    case IrOpcode::kReturn:
    case IrOpcode::kTerminate:
    case IrOpcode::kTailCall:
      return ReduceDeoptimizeOrReturnOrTerminateOrTailCall(node);
    case IrOpcode::kThrow:
      return PropagateDeadControl(node);
    case IrOpcode::kBranch:
    case IrOpcode::kSwitch:
      return ReduceBranchOrSwitch(node);
    default:
      return ReduceNode(node);
  }
  UNREACHABLE();
}
References v8::internal::compiler::turboshaft::kBranch, v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, v8::internal::wasm::kSwitch, v8::internal::wasm::kTailCall, v8::internal::wasm::kUnreachable, v8::internal::compiler::Node::opcode(), PropagateDeadControl(), ReduceBranchOrSwitch(), ReduceDeoptimizeOrReturnOrTerminateOrTailCall(), ReduceEffectPhi(), ReduceEnd(), ReduceLoopExit(), ReduceLoopOrMerge(), ReduceNode(), ReducePhi(), ReduceUnreachableOrIfException(), and v8::internal::UNREACHABLE().
ReduceBranchOrSwitch()
Reduction v8::internal::compiler::DeadCodeElimination::ReduceBranchOrSwitch (Node * node) [private]
Definition at line 346 of file dead-code-elimination.cc.
                                                              {
  DCHECK(node->opcode() == IrOpcode::kBranch ||
         node->opcode() == IrOpcode::kSwitch);
  Reduction reduction = PropagateDeadControl(node);
  if (reduction.Changed()) return reduction;
  Node* condition = NodeProperties::GetValueInput(node, 0);
  if (condition->opcode() == IrOpcode::kDeadValue) {
    // Branches or switches on {DeadValue} must originate from unreachable code
    // and cannot matter. Due to schedule freedom between the effect and the
    // control chain, they might still appear in reachable code. Remove them by
    // always choosing the first projection.
    size_t const projection_cnt = node->op()->ControlOutputCount();
    Node** projections = zone_->AllocateArray<Node*>(projection_cnt);
    NodeProperties::CollectControlProjections(node, projections,
                                              projection_cnt);
    Replace(projections[0], NodeProperties::GetControlInput(node));
    return Replace(dead());
  }
  return NoChange();
}
References v8::internal::Zone::AllocateArray(), v8::internal::compiler::Reduction::Changed(), v8::internal::compiler::NodeProperties::CollectControlProjections(), v8::internal::compiler::Operator::ControlOutputCount(), v8::internal::DCHECK(), dead(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::turboshaft::kBranch, v8::internal::wasm::kSwitch, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), PropagateDeadControl(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and zone_.
Referenced by Reduce().
ReduceDeoptimizeOrReturnOrTerminateOrTailCall()
Reduction v8::internal::compiler::DeadCodeElimination::ReduceDeoptimizeOrReturnOrTerminateOrTailCall (Node * node) [private]
Definition at line 309 of file dead-code-elimination.cc.
                {
  DCHECK(node->opcode() == IrOpcode::kDeoptimize ||
         node->opcode() == IrOpcode::kReturn ||
         node->opcode() == IrOpcode::kTerminate ||
         node->opcode() == IrOpcode::kTailCall);
  Reduction reduction = PropagateDeadControl(node);
  if (reduction.Changed()) return reduction;
  // Terminate nodes are not part of actual control flow, so they should never
  // be replaced with Throw.
  if (node->opcode() != IrOpcode::kTerminate &&
      FindDeadInput(node) != nullptr) {
    Node* effect = NodeProperties::GetEffectInput(node, 0);
    Node* control = NodeProperties::GetControlInput(node, 0);
    if (effect->opcode() != IrOpcode::kUnreachable) {
      effect = graph()->NewNode(common()->Unreachable(), effect, control);
      NodeProperties::SetType(effect, Type::None());
    }
    node->TrimInputCount(2);
    node->ReplaceInput(0, effect);
    node->ReplaceInput(1, control);
    NodeProperties::ChangeOp(node, common()->Throw());
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::Reduction::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::DCHECK(), v8::internal::compiler::anonymous_namespace{dead-code-elimination.cc}::FindDeadInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph(), v8::internal::wasm::kTailCall, v8::internal::wasm::kUnreachable, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::Node::opcode(), PropagateDeadControl(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::NodeProperties::SetType(), and v8::internal::compiler::Node::TrimInputCount().
Referenced by Reduce().
ReduceEffectNode()
Reduction v8::internal::compiler::DeadCodeElimination::ReduceEffectNode (Node * node) [private]
Definition at line 284 of file dead-code-elimination.cc.
                                                          {
  DCHECK_EQ(1, node->op()->EffectInputCount());
  Node* effect = NodeProperties::GetEffectInput(node, 0);
  if (effect->opcode() == IrOpcode::kDead) {
    return Replace(effect);
  }
  if (Node* input = FindDeadInput(node)) {
    if (effect->opcode() == IrOpcode::kUnreachable) {
      RelaxEffectsAndControls(node);
      return Replace(DeadValue(input));
    }
    Node* control = node->op()->ControlInputCount() == 1
                        ? NodeProperties::GetControlInput(node, 0)
                        : graph()->start();
    Node* unreachable =
        graph()->NewNode(common()->Unreachable(), effect, control);
    NodeProperties::SetType(unreachable, Type::None());
    ReplaceWithValue(node, DeadValue(input), node, control);
    return Replace(unreachable);
  }
  return NoChange();
}
References common(), v8::internal::compiler::Operator::ControlInputCount(), DCHECK_EQ, DeadValue(), v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::anonymous_namespace{dead-code-elimination.cc}::FindDeadInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph(), v8::internal::wasm::kUnreachable, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::NodeProperties::SetType(), and v8::internal::compiler::TFGraph::start().
Referenced by ReduceNode().
ReduceEffectPhi()
Reduction v8::internal::compiler::DeadCodeElimination::ReduceEffectPhi (Node * node) [private]
Definition at line 233 of file dead-code-elimination.cc.
                                                         {
  DCHECK_EQ(IrOpcode::kEffectPhi, node->opcode());
  Reduction reduction = PropagateDeadControl(node);
  if (reduction.Changed()) return reduction;
  Node* merge = NodeProperties::GetControlInput(node);
  DCHECK(merge->opcode() == IrOpcode::kMerge ||
         merge->opcode() == IrOpcode::kLoop);
  int input_count = node->op()->EffectInputCount();
  for (int i = 0; i < input_count; ++i) {
    Node* effect = NodeProperties::GetEffectInput(node, i);
    if (effect->opcode() == IrOpcode::kUnreachable) {
      // If Unreachable hits an effect phi, we can re-connect the effect chain
      // to the graph end and delete the corresponding inputs from the merge and
      // phi nodes.
      Node* control = NodeProperties::GetControlInput(merge, i);
      Node* throw_node = graph_->NewNode(common_->Throw(), effect, control);
      MergeControlToEnd(graph_, common_, throw_node);
      NodeProperties::ReplaceEffectInput(node, dead_, i);
      NodeProperties::ReplaceControlInput(merge, dead_, i);
      Revisit(merge);
      reduction = Changed(node);
    }
  }
  return reduction;
}
References v8::internal::compiler::Reduction::Changed(), common_, v8::internal::DCHECK(), DCHECK_EQ, dead_, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::wasm::kUnreachable, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), PropagateDeadControl(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), and v8::internal::compiler::CommonOperatorBuilder::Throw().
Referenced by Reduce().
ReduceEnd()
Reduction v8::internal::compiler::DeadCodeElimination::ReduceEnd (Node * node) [private]
Definition at line 86 of file dead-code-elimination.cc.
                                                   {
  DCHECK_EQ(IrOpcode::kEnd, node->opcode());
  Node::Inputs inputs = node->inputs();
  DCHECK_LE(1, inputs.count());
  int live_input_count = 0;
  for (int i = 0; i < inputs.count(); ++i) {
    Node* const input = inputs[i];
    // Skip dead inputs.
    if (input->opcode() == IrOpcode::kDead) continue;
    // Compact live inputs.
    if (i != live_input_count) node->ReplaceInput(live_input_count, input);
    ++live_input_count;
  }
  if (live_input_count == 0) {
    return Replace(dead());
  } else if (live_input_count < inputs.count()) {
    node->TrimInputCount(live_input_count);
    NodeProperties::ChangeOp(node, common()->End(live_input_count));
    return Changed(node);
  }
  DCHECK_EQ(inputs.count(), live_input_count);
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), common(), DCHECK_EQ, DCHECK_LE, dead(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::inputs(), v8::internal::compiler::Node::Inputs(), v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), and v8::internal::compiler::Node::TrimInputCount().
Referenced by Reduce().
ReduceLoopExit()
Reduction v8::internal::compiler::DeadCodeElimination::ReduceLoopExit (Node * node) [private]
Definition at line 336 of file dead-code-elimination.cc.
                                                        {
  Node* control = NodeProperties::GetControlInput(node, 0);
  Node* loop = NodeProperties::GetControlInput(node, 1);
  if (control->opcode() == IrOpcode::kDead ||
      loop->opcode() == IrOpcode::kDead) {
    return RemoveLoopExit(node);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::Node::opcode(), and RemoveLoopExit().
Referenced by Reduce().
ReduceLoopOrMerge()
Reduction v8::internal::compiler::DeadCodeElimination::ReduceLoopOrMerge (Node * node) [private]
Definition at line 110 of file dead-code-elimination.cc.
                                                           {
  DCHECK(IrOpcode::IsMergeOpcode(node->opcode()));
  Node::Inputs inputs = node->inputs();
  DCHECK_LE(1, inputs.count());
  // Count the number of live inputs to {node} and compact them on the fly, also
  // compacting the inputs of the associated {Phi} and {EffectPhi} uses at the
  // same time. We consider {Loop}s dead even if only the first control input
  // is dead.
  int live_input_count = 0;
  if (node->opcode() != IrOpcode::kLoop ||
      node->InputAt(0)->opcode() != IrOpcode::kDead) {
    for (int i = 0; i < inputs.count(); ++i) {
      Node* const input = inputs[i];
      // Skip dead inputs.
      if (input->opcode() == IrOpcode::kDead) continue;
      // Compact live inputs.
      if (live_input_count != i) {
        node->ReplaceInput(live_input_count, input);
        for (Node* const use : node->uses()) {
          if (NodeProperties::IsPhi(use)) {
            DCHECK_EQ(inputs.count() + 1, use->InputCount());
            use->ReplaceInput(live_input_count, use->InputAt(i));
          }
        }
      }
      ++live_input_count;
    }
  }
  if (live_input_count == 0) {
    return Replace(dead());
  } else if (live_input_count == 1) {
    NodeVector loop_exits(zone_);
    // Due to compaction above, the live input is at offset 0.
    for (Node* const use : node->uses()) {
      if (NodeProperties::IsPhi(use)) {
        Replace(use, use->InputAt(0));
      } else if (use->opcode() == IrOpcode::kLoopExit &&
                 use->InputAt(1) == node) {
        // Remember the loop exits so that we can mark their loop input dead.
        // This has to be done after the use list iteration so that we do
        // not mutate the use list while it is being iterated.
        loop_exits.push_back(use);
      } else if (use->opcode() == IrOpcode::kTerminate) {
        DCHECK_EQ(IrOpcode::kLoop, node->opcode());
        Replace(use, dead());
      }
    }
    for (Node* loop_exit : loop_exits) {
      loop_exit->ReplaceInput(1, dead());
      Revisit(loop_exit);
    }
    return Replace(node->InputAt(0));
  }
  DCHECK_LE(2, live_input_count);
  DCHECK_LE(live_input_count, inputs.count());
  // Trim input count for the {Merge} or {Loop} node.
  if (live_input_count < inputs.count()) {
    // Trim input counts for all phi uses and revisit them.
    for (Node* const use : node->uses()) {
      if (NodeProperties::IsPhi(use)) {
        use->ReplaceInput(live_input_count, node);
        TrimMergeOrPhi(use, live_input_count);
        Revisit(use);
      }
    }
    TrimMergeOrPhi(node, live_input_count);
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, dead(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::inputs(), v8::internal::compiler::Node::Inputs(), v8::internal::compiler::IrOpcode::IsMergeOpcode(), v8::internal::compiler::NodeProperties::IsPhi(), v8::internal::compiler::Node::opcode(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), TrimMergeOrPhi(), use(), v8::internal::compiler::Node::uses(), and zone_.
Referenced by Reduce().
ReduceNode()
Reduction v8::internal::compiler::DeadCodeElimination::ReduceNode (Node * node) [private]
Definition at line 194 of file dead-code-elimination.cc.
                                                    {
  DCHECK(!IrOpcode::IsGraphTerminator(node->opcode()));
  int const effect_input_count = node->op()->EffectInputCount();
  int const control_input_count = node->op()->ControlInputCount();
  DCHECK_LE(control_input_count, 1);
  if (control_input_count == 1) {
    Reduction reduction = PropagateDeadControl(node);
    if (reduction.Changed()) return reduction;
  }
  if (effect_input_count == 0 &&
      (control_input_count == 0 || node->op()->ControlOutputCount() == 0)) {
    return ReducePureNode(node);
  }
  if (effect_input_count > 0) {
    return ReduceEffectNode(node);
  }
  return NoChange();
}
References v8::internal::compiler::Reduction::Changed(), v8::internal::compiler::Operator::ControlInputCount(), v8::internal::compiler::Operator::ControlOutputCount(), v8::internal::DCHECK(), DCHECK_LE, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::IrOpcode::IsGraphTerminator(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), PropagateDeadControl(), ReduceEffectNode(), and ReducePureNode().
Referenced by Reduce().
ReducePhi()
Reduction v8::internal::compiler::DeadCodeElimination::ReducePhi (Node * node) [private]
Definition at line 213 of file dead-code-elimination.cc.
                                                   {
  DCHECK_EQ(IrOpcode::kPhi, node->opcode());
  Reduction reduction = PropagateDeadControl(node);
  if (reduction.Changed()) return reduction;
  MachineRepresentation rep = PhiRepresentationOf(node->op());
  if (rep == MachineRepresentation::kNone ||
      NodeProperties::GetTypeOrAny(node).IsNone()) {
    return Replace(DeadValue(node, rep));
  }
  int input_count = node->op()->ValueInputCount();
  for (int i = 0; i < input_count; ++i) {
    Node* input = NodeProperties::GetValueInput(node, i);
    if (input->opcode() == IrOpcode::kDeadValue &&
        DeadValueRepresentationOf(input->op()) != rep) {
      NodeProperties::ReplaceValueInput(node, DeadValue(input, rep), i);
    }
  }
  return NoChange();
}
References v8::internal::compiler::Reduction::Changed(), DCHECK_EQ, DeadValue(), v8::internal::compiler::DeadValueRepresentationOf(), v8::internal::compiler::NodeProperties::GetTypeOrAny(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::IsNone(), v8::internal::kNone, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::PhiRepresentationOf(), PropagateDeadControl(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by Reduce().
ReducePureNode()
Reduction v8::internal::compiler::DeadCodeElimination::ReducePureNode (Node * node) [private]
Definition at line 260 of file dead-code-elimination.cc.
                                                        {
  DCHECK_EQ(0, node->op()->EffectInputCount());
  if (node->opcode() == IrOpcode::kDeadValue) return NoChange();
  if (Node* input = FindDeadInput(node)) {
    return Replace(DeadValue(input));
  }
  return NoChange();
}
References DCHECK_EQ, DeadValue(), v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::anonymous_namespace{dead-code-elimination.cc}::FindDeadInput(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by ReduceNode().
reducer_name()
const char* v8::internal::compiler::DeadCodeElimination::reducer_name () const [inline], [override]
Definition at line 47 of file dead-code-elimination.h.
{ return "DeadCodeElimination"; }
ReduceUnreachableOrIfException()
Reduction v8::internal::compiler::DeadCodeElimination::ReduceUnreachableOrIfException (Node * node) [private]
Definition at line 269 of file dead-code-elimination.cc.
                                                                        {
  DCHECK(node->opcode() == IrOpcode::kUnreachable ||
         node->opcode() == IrOpcode::kIfException);
  Reduction reduction = PropagateDeadControl(node);
  if (reduction.Changed()) return reduction;
  Node* effect = NodeProperties::GetEffectInput(node, 0);
  if (effect->opcode() == IrOpcode::kDead) {
    return Replace(effect);
  }
  if (effect->opcode() == IrOpcode::kUnreachable) {
    return Replace(effect);
  }
  return NoChange();
}
References v8::internal::compiler::Reduction::Changed(), v8::internal::DCHECK(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::wasm::kUnreachable, v8::internal::compiler::Node::opcode(), PropagateDeadControl(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by Reduce().
RemoveLoopExit()
Reduction v8::internal::compiler::DeadCodeElimination::RemoveLoopExit (Node * node) [private]
Definition at line 181 of file dead-code-elimination.cc.
                                                        {
  DCHECK_EQ(IrOpcode::kLoopExit, node->opcode());
  for (Node* const use : node->uses()) {
    if (use->opcode() == IrOpcode::kLoopExitValue ||
        use->opcode() == IrOpcode::kLoopExitEffect) {
      Replace(use, use->InputAt(0));
    }
  }
  Node* control = NodeProperties::GetControlInput(node, 0);
  Replace(node, control);
  return Replace(control);
}
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), use(), and v8::internal::compiler::Node::uses().
Referenced by ReduceLoopExit().
TrimMergeOrPhi()
void v8::internal::compiler::DeadCodeElimination::TrimMergeOrPhi (Node * node, int size) [private]
Definition at line 367 of file dead-code-elimination.cc.
                                                             {
  const Operator* const op = common()->ResizeMergeOrPhi(node->op(), size);
  node->TrimInputCount(OperatorProperties::GetTotalInputCount(op));
  NodeProperties::ChangeOp(node, op);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::compiler::OperatorProperties::GetTotalInputCount(), v8::internal::compiler::Node::op(), v8::internal::compiler::CommonOperatorBuilder::ResizeMergeOrPhi(), size(), and v8::internal::compiler::Node::TrimInputCount().
Referenced by ReduceLoopOrMerge().
Member Data Documentation
common_
CommonOperatorBuilder* const v8::internal::compiler::DeadCodeElimination::common_ [private]
Definition at line 77 of file dead-code-elimination.h.
Referenced by ReduceEffectPhi().
dead_
Node* const v8::internal::compiler::DeadCodeElimination::dead_ [private]
Definition at line 78 of file dead-code-elimination.h.
Referenced by DeadCodeElimination(), and ReduceEffectPhi().
graph_
TFGraph* const v8::internal::compiler::DeadCodeElimination::graph_ [private]
Definition at line 76 of file dead-code-elimination.h.
Referenced by ReduceEffectPhi().
zone_
Zone* v8::internal::compiler::DeadCodeElimination::zone_ [private]
Definition at line 79 of file dead-code-elimination.h.
Referenced by ReduceBranchOrSwitch(), and ReduceLoopOrMerge().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/dead-code-elimination.h
/mnt/V8SourceCode/src/compiler/dead-code-elimination.cc