v8::internal::compiler::Pipeline Class Reference
#include <pipeline.h>
Public Types
using CodeAssemblerGenerator = std::function< void(compiler::CodeAssemblerState *)>
using CodeAssemblerInstaller = std::function< void(Builtin builtin, Handle< Code > code)>
Static Public Member Functions
static V8_EXPORT_PRIVATE std::unique_ptr< TurbofanCompilationJob > NewCompilationJob (Isolate *isolate, Handle< JSFunction > function, CodeKind code_kind, bool has_script, BytecodeOffset osr_offset=BytecodeOffset::None())
static std::unique_ptr< TurbofanCompilationJob > NewCSLinkageCodeStubBuiltinCompilationJob (Isolate *isolate, Builtin builtin, CodeAssemblerGenerator generator, CodeAssemblerInstaller installer, const AssemblerOptions &assembler_options, CallDescriptors::Key interface_descriptor, const char *name, const ProfileDataFromFile *profile_data, int finalize_order)
static std::unique_ptr< TurbofanCompilationJob > NewJSLinkageCodeStubBuiltinCompilationJob (Isolate *isolate, Builtin builtin, CodeAssemblerGenerator generator, CodeAssemblerInstaller installer, const AssemblerOptions &assembler_options, int argc, const char *name, const ProfileDataFromFile *profile_data, int finalize_order)
static std::unique_ptr< TurbofanCompilationJob > NewBytecodeHandlerCompilationJob (Isolate *isolate, Builtin builtin, CodeAssemblerGenerator generator, CodeAssemblerInstaller installer, const AssemblerOptions &assembler_options, const char *name, const ProfileDataFromFile *profile_data, int finalize_order)
static MaybeHandle< Code > GenerateCodeForTurboshaftBuiltin (turboshaft::PipelineData *turboshaft_data, CallDescriptor *call_descriptor, Builtin builtin, const char *debug_name, const ProfileDataFromFile *profile_data)
static V8_EXPORT_PRIVATE MaybeHandle< Code > GenerateCodeForTesting (OptimizedCompilationInfo *info, Isolate *isolate)
static V8_EXPORT_PRIVATE MaybeHandle< Code > GenerateCodeForTesting (OptimizedCompilationInfo *info, Isolate *isolate, CallDescriptor *call_descriptor, TFGraph *graph, const AssemblerOptions &options, Schedule *schedule=nullptr)
static V8_EXPORT_PRIVATE MaybeHandle< Code > GenerateTurboshaftCodeForTesting (CallDescriptor *call_descriptor, turboshaft::PipelineData *data)
Private Member Functions
DISALLOW_IMPLICIT_CONSTRUCTORS (Pipeline)
Detailed Description
Definition at line 67 of file pipeline.h.
Member Typedef Documentation
CodeAssemblerGenerator
using v8::internal::compiler::Pipeline::CodeAssemblerGenerator = std::function<void(compiler::CodeAssemblerState*)>
Definition at line 75 of file pipeline.h.
CodeAssemblerInstaller
using v8::internal::compiler::Pipeline::CodeAssemblerInstaller = std::function<void(Builtin builtin, Handle<Code> code)>
Definition at line 77 of file pipeline.h.
Member Function Documentation
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::compiler::Pipeline::DISALLOW_IMPLICIT_CONSTRUCTORS (Pipeline) [private]
GenerateCodeForTesting() [1/2]
MaybeHandle< Code > v8::internal::compiler::Pipeline::GenerateCodeForTesting (OptimizedCompilationInfo * info, Isolate * isolate) [static]
Definition at line 3101 of file pipeline.cc.
                                                      {
  ZoneStats zone_stats(isolate->allocator());
  std::unique_ptr<TurbofanPipelineStatistics> pipeline_statistics(
      CreatePipelineStatistics(Handle<Script>::null(), info, isolate,
                               &zone_stats));
  TFPipelineData data(&zone_stats, isolate, info, pipeline_statistics.get());
  turboshaft::PipelineData turboshaft_data(
      &zone_stats, turboshaft::TurboshaftPipelineKind::kJS, isolate, info,
      AssemblerOptions::Default(isolate));
  turboshaft_data.set_pipeline_statistics(pipeline_statistics.get());
  PipelineJobScope scope(&data, isolate->counters()->runtime_call_stats());
  PipelineImpl pipeline(&data);
  turboshaft::Pipeline turboshaft_pipeline(&turboshaft_data);
  Linkage linkage(Linkage::ComputeIncoming(data.instruction_zone(), info));
  {
    CompilationHandleScope compilation_scope(isolate, info);
    info->ReopenAndCanonicalizeHandlesInNewScope(isolate);
    if (!pipeline.InitializeHeapBroker()) return {};
  }
  {
    LocalIsolateScope local_isolate_scope(data.broker(), info,
                                          isolate->main_thread_local_isolate());
    turboshaft_data.InitializeBrokerAndDependencies(data.broker_ptr(),
                                                    data.dependencies());
    if (V8_UNLIKELY(v8_flags.turbolev)) {
      if (!turboshaft_pipeline.CreateGraphWithMaglev(&linkage)) return {};
    } else {
      if (!pipeline.CreateGraph(&linkage)) return {};
      // We selectively Unpark inside OptimizeTurbofanGraph.
      if (!pipeline.OptimizeTurbofanGraph(&linkage)) return {};
      // We convert the turbofan graph to turboshaft.
      if (!turboshaft_pipeline.CreateGraphFromTurbofan(&data, &linkage)) {
        data.EndPhaseKind();
        return {};
      }
    }
    if (!turboshaft_pipeline.OptimizeTurboshaftGraph(&linkage)) {
      return {};
    }
    const bool success = GenerateCodeFromTurboshaftGraph(
        &linkage, turboshaft_pipeline, &pipeline, data.osr_helper_ptr());
    if (!success) return {};
    Handle<Code> code;
    if (turboshaft_pipeline.FinalizeCode().ToHandle(&code) &&
        turboshaft_pipeline.CommitDependencies(code)) {
      return code;
    }
    return {};
  }
}
References v8::internal::Isolate::allocator(), v8::internal::compiler::TFPipelineData::broker(), v8::internal::compiler::TFPipelineData::broker_ptr(), code, v8::internal::compiler::turboshaft::Pipeline::CommitDependencies(), v8::internal::compiler::Linkage::ComputeIncoming(), v8::internal::Isolate::counters(), v8::internal::compiler::PipelineImpl::CreateGraph(), v8::internal::compiler::turboshaft::Pipeline::CreateGraphFromTurbofan(), v8::internal::compiler::turboshaft::Pipeline::CreateGraphWithMaglev(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::CreatePipelineStatistics(), v8::internal::AssemblerOptions::Default(), v8::internal::compiler::TFPipelineData::dependencies(), v8::internal::compiler::TFPipelineData::EndPhaseKind(), v8::internal::compiler::turboshaft::Pipeline::FinalizeCode(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::GenerateCodeFromTurboshaftGraph(), v8::internal::compiler::turboshaft::PipelineData::InitializeBrokerAndDependencies(), v8::internal::compiler::PipelineImpl::InitializeHeapBroker(), v8::internal::compiler::TFPipelineData::instruction_zone(), v8::internal::TurbofanCompilationJob::isolate(), v8::internal::compiler::turboshaft::kJS, v8::internal::Isolate::main_thread_local_isolate(), v8::internal::compiler::PipelineImpl::OptimizeTurbofanGraph(), v8::internal::compiler::turboshaft::Pipeline::OptimizeTurboshaftGraph(), v8::internal::compiler::TFPipelineData::osr_helper_ptr(), v8::internal::OptimizedCompilationInfo::ReopenAndCanonicalizeHandlesInNewScope(), v8::internal::Counters::runtime_call_stats(), v8::internal::compiler::turboshaft::PipelineData::set_pipeline_statistics(), v8::internal::v8_flags, and V8_UNLIKELY.
GenerateCodeForTesting() [2/2]
MaybeHandle< Code > v8::internal::compiler::Pipeline::GenerateCodeForTesting (OptimizedCompilationInfo * info, Isolate * isolate, CallDescriptor * call_descriptor, TFGraph * graph, const AssemblerOptions & options, Schedule * schedule = nullptr) [static]
Definition at line 3163 of file pipeline.cc.
                                                      {
  // TODO(nicohartmann): Callers should properly set this, but it's hard to do
  // this through testing logic shared between JS and Wasm.
  AssemblerOptions options = opts;
#if V8_ENABLE_WEBASSEMBLY
  if (info->IsWasm() || info->IsWasmBuiltin()) {
    options.is_wasm = true;
  }
#endif
  // Construct a pipeline for scheduling and code generation.
  ZoneStats zone_stats(isolate->allocator());
  NodeOriginTable* node_positions = info->zone()->New<NodeOriginTable>(graph);
  TFPipelineData data(&zone_stats, info, isolate, isolate->allocator(), graph,
                      nullptr, schedule, nullptr, node_positions, nullptr,
                      options, nullptr);
  turboshaft::PipelineData turboshaft_data(
      &zone_stats, turboshaft::TurboshaftPipelineKind::kCSA, isolate, info,
      options);
  PipelineJobScope scope(&data, isolate->counters()->runtime_call_stats());
  std::unique_ptr<TurbofanPipelineStatistics> pipeline_statistics;
  if (v8_flags.turbo_stats || v8_flags.turbo_stats_nvp) {
    pipeline_statistics.reset(new TurbofanPipelineStatistics(
        info, isolate->GetTurboStatistics(), &zone_stats));
    pipeline_statistics->BeginPhaseKind("V8.TFTestCodegen");
  }
  PipelineImpl pipeline(&data);
  turboshaft::Pipeline turboshaft_pipeline(&turboshaft_data);
  if (info->trace_turbo_json()) {
    TurboJsonFile json_of(info, std::ios_base::trunc);
    json_of << "{\"function\":\"" << info->GetDebugName().get()
            << "\", \"source\":\"\",\n\"phases\":[";
  }
  // TODO(rossberg): Should this really be untyped?
  pipeline.RunPrintAndVerify("V8.TFMachineCode", true);
  // Ensure we have a schedule.
  if (data.schedule() == nullptr) {
    CHECK(pipeline.ComputeScheduledGraph());
  }
  Linkage linkage(call_descriptor);
  // We convert the turbofan graph to turboshaft.
  if (!turboshaft_pipeline.CreateGraphFromTurbofan(&data, &linkage)) {
    return {};
  }
  // We need to run simplification to normalize some patterns for instruction
  // selection (e.g. loads and stores).
  if (!turboshaft_pipeline.RunSimplificationAndNormalizationPhase()) {
    return {};
  }
  if (!GenerateCodeFromTurboshaftGraph(&linkage, turboshaft_pipeline, nullptr,
                                       data.osr_helper_ptr())) {
    return {};
  }
  MaybeHandle<Code> maybe_code = turboshaft_pipeline.FinalizeCode();
  Handle<Code> code;
  if (maybe_code.ToHandle(&code)) {
    return code;
  }
  return {};
}
References v8::internal::Isolate::allocator(), CHECK, code, v8::internal::compiler::PipelineImpl::ComputeScheduledGraph(), v8::internal::Isolate::counters(), v8::internal::compiler::turboshaft::Pipeline::CreateGraphFromTurbofan(), v8::internal::compiler::turboshaft::Pipeline::FinalizeCode(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::GenerateCodeFromTurboshaftGraph(), v8::internal::OptimizedCompilationInfo::GetDebugName(), v8::internal::Isolate::GetTurboStatistics(), graph(), v8::internal::AssemblerOptions::is_wasm, v8::internal::TurbofanCompilationJob::isolate(), v8::internal::compiler::turboshaft::kCSA, v8::internal::Zone::New(), v8::internal::compiler::PipelineImpl::RunPrintAndVerify(), v8::internal::compiler::turboshaft::Pipeline::RunSimplificationAndNormalizationPhase(), v8::internal::Counters::runtime_call_stats(), v8::internal::MaybeHandle< T >::ToHandle(), v8::internal::v8_flags, and v8::internal::OptimizedCompilationInfo::zone().
GenerateCodeForTurboshaftBuiltin()
MaybeHandle< Code > v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin (turboshaft::PipelineData * turboshaft_data, CallDescriptor * call_descriptor, Builtin builtin, const char * debug_name, const ProfileDataFromFile * profile_data) [static]
Definition at line 2524 of file pipeline.cc.
                                             {
  DCHECK_EQ(builtin, turboshaft_data->info()->builtin());
  Isolate* isolate = turboshaft_data->isolate();
#if V8_ENABLE_EXPERIMENTAL_TSA_BUILTINS
// TODO(nicohartmann): Use during development and remove afterwards.
#ifdef DEBUG
  std::cout << "=== Generating Builtin '" << debug_name
            << "' with Turboshaft ===" << std::endl;
#endif
#endif
  // Initialize JumpOptimizationInfo if required.
  JumpOptimizationInfo jump_opt;
  bool should_optimize_jumps =
      isolate->serializer_enabled() && v8_flags.turbo_rewrite_far_jumps &&
      !v8_flags.turbo_profiling && !v8_flags.dump_builtins_hashes_to_file;
  JumpOptimizationInfo* jump_optimization_info =
      should_optimize_jumps ? &jump_opt : nullptr;
  PipelineJobScope scope(turboshaft_data,
                         isolate->counters()->runtime_call_stats());
  RCS_SCOPE(isolate, RuntimeCallCounterId::kOptimizeCode);
  std::unique_ptr<TurbofanPipelineStatistics> pipeline_statistics(
      CreatePipelineStatistics(Handle<Script>::null(), turboshaft_data->info(),
                               isolate, turboshaft_data->zone_stats()));
  turboshaft::BuiltinPipeline turboshaft_pipeline(turboshaft_data);
  OptimizedCompilationInfo* info = turboshaft_data->info();
  if (info->trace_turbo_graph() || info->trace_turbo_json()) {
    turboshaft::ZoneWithName<turboshaft::kTempZoneName> print_zone(
        turboshaft_data->zone_stats(), turboshaft::kTempZoneName);
    std::vector<char> name_buffer(strlen("TSA: ") + strlen(debug_name) + 1);
    memcpy(name_buffer.data(), "TSA: ", 5);
    memcpy(name_buffer.data() + 5, debug_name, strlen(debug_name));
    turboshaft_pipeline.PrintGraph(print_zone, name_buffer.data());
  }
  // Validate pgo profile.
  const int initial_graph_hash =
      ComputeInitialGraphHash(builtin, profile_data, &turboshaft_data->graph());
  profile_data =
      ValidateProfileData(profile_data, initial_graph_hash, debug_name);
  turboshaft_pipeline.OptimizeBuiltin();
  Linkage linkage(call_descriptor);
  CHECK(turboshaft_pipeline.GenerateCode(&linkage, {}, jump_optimization_info,
                                         profile_data, initial_graph_hash));
  return turboshaft_pipeline.FinalizeCode();
}
References v8::internal::OptimizedCompilationInfo::builtin(), CHECK, v8::internal::compiler::anonymous_namespace{pipeline.cc}::ComputeInitialGraphHash(), v8::internal::Isolate::counters(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::CreatePipelineStatistics(), DCHECK_EQ, v8::internal::compiler::turboshaft::Pipeline::FinalizeCode(), v8::internal::compiler::turboshaft::Pipeline::GenerateCode(), v8::internal::compiler::turboshaft::PipelineData::graph(), v8::internal::compiler::turboshaft::PipelineData::info(), v8::internal::TurbofanCompilationJob::isolate(), v8::internal::compiler::turboshaft::PipelineData::isolate(), v8::internal::compiler::turboshaft::kTempZoneName, v8::internal::compiler::turboshaft::BuiltinPipeline::OptimizeBuiltin(), v8::internal::compiler::turboshaft::Pipeline::PrintGraph(), RCS_SCOPE, v8::internal::Counters::runtime_call_stats(), v8::internal::Isolate::serializer_enabled(), v8::internal::v8_flags, v8::internal::compiler::anonymous_namespace{pipeline.cc}::ValidateProfileData(), and v8::internal::compiler::turboshaft::PipelineData::zone_stats().
Referenced by v8::internal::compiler::turboshaft::BuildWithTurboshaftAssemblerImpl().
GenerateTurboshaftCodeForTesting()
MaybeHandle< Code > v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting (CallDescriptor * call_descriptor, turboshaft::PipelineData * data) [static]
Definition at line 3235 of file pipeline.cc.
                                                                   {
  Isolate* isolate = data->isolate();
  OptimizedCompilationInfo* info = data->info();
  PipelineJobScope scope(data, isolate->counters()->runtime_call_stats());
  std::unique_ptr<TurbofanPipelineStatistics> pipeline_statistics;
  if (v8_flags.turbo_stats || v8_flags.turbo_stats_nvp) {
    pipeline_statistics.reset(new TurbofanPipelineStatistics(
        info, isolate->GetTurboStatistics(), data->zone_stats()));
    pipeline_statistics->BeginPhaseKind("V8.TFTestCodegen");
  }
  turboshaft::Pipeline pipeline(data);
  if (info->trace_turbo_json()) {
    {
      TurboJsonFile json_of(info, std::ios_base::trunc);
      json_of << "{\"function\":\"" << info->GetDebugName().get()
              << "\", \"source\":\"\",\n\"phases\":[";
    }
    {
      UnparkedScopeIfNeeded unparked_scope(data->broker());
      AllowHandleDereference allow_deref;
      TurboJsonFile json_of(data->info(), std::ios_base::app);
      turboshaft::PrintTurboshaftGraphForTurbolizer(
          json_of, data->graph(), "V8.TSMachineCode", data->node_origins(),
          data->graph_zone());
    }
  }
  info->tick_counter().TickAndMaybeEnterSafepoint();
  data->InitializeCodegenComponent(nullptr);
  Handle<Code> code;
  if (pipeline.GenerateCode(call_descriptor).ToHandle(&code) &&
      pipeline.CommitDependencies(code)) {
    return code;
  }
  return {};
}
References v8::internal::compiler::turboshaft::PipelineData::broker(), code, v8::internal::compiler::turboshaft::Pipeline::CommitDependencies(), v8::internal::Isolate::counters(), v8::internal::compiler::turboshaft::Pipeline::GenerateCode(), v8::internal::OptimizedCompilationInfo::GetDebugName(), v8::internal::Isolate::GetTurboStatistics(), v8::internal::compiler::turboshaft::PipelineData::graph(), v8::internal::compiler::turboshaft::PipelineData::graph_zone(), v8::internal::compiler::turboshaft::PipelineData::info(), v8::internal::compiler::turboshaft::PipelineData::InitializeCodegenComponent(), v8::internal::TurbofanCompilationJob::isolate(), v8::internal::compiler::turboshaft::PipelineData::isolate(), v8::internal::compiler::turboshaft::PipelineData::node_origins(), v8::internal::compiler::turboshaft::PrintTurboshaftGraphForTurbolizer(), v8::internal::Counters::runtime_call_stats(), v8::internal::OptimizedCompilationInfo::tick_counter(), v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), v8::internal::v8_flags, and v8::internal::compiler::turboshaft::PipelineData::zone_stats().
NewBytecodeHandlerCompilationJob()
std::unique_ptr< TurbofanCompilationJob > v8::internal::compiler::Pipeline::NewBytecodeHandlerCompilationJob (Isolate * isolate, Builtin builtin, CodeAssemblerGenerator generator, CodeAssemblerInstaller installer, const AssemblerOptions & assembler_options, const char * name, const ProfileDataFromFile * profile_data, int finalize_order) [static]
Definition at line 2493 of file pipeline.cc.
                        {
  auto get_call_descriptor =
      [](Zone* zone) {
        InterpreterDispatchDescriptor descriptor;
        return Linkage::GetStubCallDescriptor(
            zone, descriptor, descriptor.GetStackParameterCount(),
            CallDescriptor::kNoFlags, Operator::kNoProperties);
      };
    return std::make_unique<CodeAssemblerTurboshaftCompilationJob>(
        isolate, builtin, generator, installer, assembler_options,
        get_call_descriptor, CodeKind::BYTECODE_HANDLER, name, profile_data,
        finalize_order);
}
References v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::TurbofanCompilationJob::isolate(), v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, and v8::internal::name.
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CompileBytecodeHandler().
NewCompilationJob()
std::unique_ptr< TurbofanCompilationJob > v8::internal::compiler::Pipeline::NewCompilationJob (Isolate * isolate, Handle< JSFunction > function, CodeKind code_kind, bool has_script, BytecodeOffset osr_offset = BytecodeOffset::None()) [static]
Definition at line 3279 of file pipeline.cc.
                                                {
  Handle<SharedFunctionInfo> shared(function->shared(), isolate);
  return std::make_unique<PipelineCompilationJob>(isolate, shared, function,
                                                  osr_offset, code_kind);
}
References v8::internal::TurbofanCompilationJob::isolate().
NewCSLinkageCodeStubBuiltinCompilationJob()
std::unique_ptr< TurbofanCompilationJob > v8::internal::compiler::Pipeline::NewCSLinkageCodeStubBuiltinCompilationJob (Isolate * isolate, Builtin builtin, CodeAssemblerGenerator generator, CodeAssemblerInstaller installer, const AssemblerOptions & assembler_options, CallDescriptors::Key interface_descriptor, const char * name, const ProfileDataFromFile * profile_data, int finalize_order) [static]
Definition at line 2454 of file pipeline.cc.
                                                                 {
  auto get_call_descriptor =
      [interface_descriptor](Zone* zone) {
        CallInterfaceDescriptor descriptor(interface_descriptor);
        // Ensure descriptor is already initialized.
        DCHECK_LE(0, descriptor.GetRegisterParameterCount());
        return Linkage::GetStubCallDescriptor(
            zone, descriptor, descriptor.GetStackParameterCount(),
            CallDescriptor::kNoFlags, Operator::kNoProperties);
      };
    return std::make_unique<CodeAssemblerTurboshaftCompilationJob>(
        isolate, builtin, generator, installer, assembler_options,
        get_call_descriptor, CodeKind::BUILTIN, name, profile_data,
        finalize_order);
}
References BUILTIN, DCHECK_LE, v8::internal::CallInterfaceDescriptor::GetRegisterParameterCount(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::TurbofanCompilationJob::isolate(), v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, and v8::internal::name.
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CompileCSLinkageCodeStubBuiltin().
NewJSLinkageCodeStubBuiltinCompilationJob()
std::unique_ptr< TurbofanCompilationJob > v8::internal::compiler::Pipeline::NewJSLinkageCodeStubBuiltinCompilationJob (Isolate * isolate, Builtin builtin, CodeAssemblerGenerator generator, CodeAssemblerInstaller installer, const AssemblerOptions & assembler_options, int argc, const char * name, const ProfileDataFromFile * profile_data, int finalize_order) [static]
Definition at line 2476 of file pipeline.cc.
                        {
  auto get_call_descriptor = [argc](Zone* zone) {
    return Linkage::GetJSCallDescriptor(zone, false, argc,
                                        CallDescriptor::kCanUseRoots);
  };
    return std::make_unique<CodeAssemblerTurboshaftCompilationJob>(
        isolate, builtin, generator, installer, assembler_options,
        get_call_descriptor, CodeKind::BUILTIN, name, profile_data,
        finalize_order);
}
References BUILTIN, v8::internal::compiler::Linkage::GetJSCallDescriptor(), v8::internal::TurbofanCompilationJob::isolate(), v8::internal::compiler::CallDescriptor::kCanUseRoots, and v8::internal::name.
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CompileJSLinkageCodeStubBuiltin().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/pipeline.h
/mnt/V8SourceCode/src/compiler/pipeline.cc