cppgc::internal::Sweeper::SweeperImpl Class Reference
Classes
class IncrementalSweepTask
class MutatorThreadSweepingScope
Public Member Functions
SweeperImpl (HeapBase &heap)
~SweeperImpl ()
void Start (SweepingConfig config)
void SweepForTask (v8::base::TimeDelta max_duration)
void SweepForLowPriorityTask (v8::base::TimeDelta max_duration)
bool SweepForLargeAllocation (BaseSpace *space, size_t size, v8::base::TimeDelta max_duration)
bool SweepForNormalAllocation (BaseSpace *space, size_t size, v8::base::TimeDelta max_duration)
bool SweepForAllocationIfRunning (BaseSpace *space, size_t size, v8::base::TimeDelta max_duration)
bool FinishIfRunning ()
bool IsConcurrentSweepingDone () const
void FinishIfOutOfWork ()
void Finish ()
void FinalizeSweep ()
void NotifyDone ()
void WaitForConcurrentSweepingForTesting ()
bool IsSweepingOnMutatorThread () const
bool IsSweepingInProgress () const
bool PerformSweepOnMutatorThread (v8::base::TimeDelta max_duration, StatsCollector::ScopeId internal_scope_id, MutatorThreadSweepingMode sweeping_mode)
void AddMutatorThreadSweepingObserver (Sweeper::SweepingOnMutatorThreadObserver *observer)
void RemoveMutatorThreadSweepingObserver (Sweeper::SweepingOnMutatorThreadObserver *observer)
Private Types
enum class SweepResult { kFullyDone
, kInProgress
, kMainThreadDoneConcurrentInProgress
 }
using FreeMemoryHandling = SweepingConfig::FreeMemoryHandling
Private Member Functions
SweepResult SweepInForegroundTaskImpl (v8::base::TimeDelta max_duration, StatsCollector::ScopeId scope)
void ScheduleIncrementalSweeping (std::optional< v8::base::TimeDelta > delay={})
void ScheduleLowPriorityIncrementalSweeping (std::optional< v8::base::TimeDelta > delay={})
void ScheduleConcurrentSweeping ()
void CancelAllSweepingTasks ()
void SynchronizeAndFinalizeConcurrentAndIncrementalSweeping ()
Private Attributes
RawHeap & heap_
NormalPageMemoryPool & page_pool_
StatsCollector *const stats_collector_
SpaceStates space_states_
SweepingState empty_normal_pages_
SweepingState empty_large_pages_
size_t unused_destroyed_normal_pages_ = 0
cppgc::Platform * platform_
std::shared_ptr< cppgc::TaskRunner > foreground_task_runner_
std::shared_ptr< cppgc::TaskRunner > low_priority_foreground_task_runner_
SweepingConfig config_
IncrementalSweepTask::Handle incremental_sweeper_handle_
IncrementalSweepTask::Handle incremental_sweeper_low_priority_handle_
std::unique_ptr< cppgc::JobHandle > concurrent_sweeper_handle_
std::vector< Sweeper::SweepingOnMutatorThreadObserver * > mutator_thread_sweeping_observers_
bool low_priority_task_ran_ = false
bool is_in_progress_ = false
bool notify_done_pending_ = false
bool is_sweeping_on_mutator_thread_ = false
Static Private Attributes
static constexpr double kMaxHeapPercentageForNoSweeping = 50
static constexpr auto kDelayWhileLowPrioritySweepingMakesProgress
static constexpr auto kDelayWhileConcurrentSweepingMakesProgress
static constexpr auto kDelayForRegularPrioritySweeping
Detailed Description
Definition at line 961 of file sweeper.cc.
Member Typedef Documentation
FreeMemoryHandling
using cppgc::internal::Sweeper::SweeperImpl::FreeMemoryHandling = SweepingConfig::FreeMemoryHandling [private]
Definition at line 962 of file sweeper.cc.
Member Enumeration Documentation
SweepResult
enum cppgc::internal::Sweeper::SweeperImpl::SweepResult [strong], [private]
Enumerator
kFullyDone
kInProgress
kMainThreadDoneConcurrentInProgress
Definition at line 1491 of file sweeper.cc.
                         {
    // Sweeping is fully done.
    kFullyDone,
    // Sweeping is still in progress.
    kInProgress,
    // Sweeping on the main thread is done but concurrent sweepers are still
    // making progress. This may be temporary.
    kMainThreadDoneConcurrentInProgress,
  };
Constructor & Destructor Documentation
SweeperImpl()
cppgc::internal::Sweeper::SweeperImpl::SweeperImpl (HeapBase & heap) [inline], [explicit]
Definition at line 965 of file sweeper.cc.
      : heap_(heap.raw_heap()),
        page_pool_(heap.page_backend()->page_pool()),
        stats_collector_(heap.stats_collector()),
        platform_(heap.platform()) {
    CHECK_NOT_NULL(platform_);
  }
References CHECK_NOT_NULL, and platform_.
 SweeperImpl()
cppgc::internal::Sweeper::SweeperImpl::~SweeperImpl () [inline]
Definition at line 973 of file sweeper.cc.
{ CancelAllSweepingTasks(); }
References CancelAllSweepingTasks().
Member Function Documentation
AddMutatorThreadSweepingObserver()
void cppgc::internal::Sweeper::SweeperImpl::AddMutatorThreadSweepingObserver (Sweeper::SweepingOnMutatorThreadObserver * observer) [inline]
Definition at line 1398 of file sweeper.cc.
                                                        {
    DCHECK_EQ(mutator_thread_sweeping_observers_.end(),
              std::find(mutator_thread_sweeping_observers_.begin(),
                        mutator_thread_sweeping_observers_.end(), observer));
    mutator_thread_sweeping_observers_.push_back(observer);
  }
References DCHECK_EQ, and mutator_thread_sweeping_observers_.
CancelAllSweepingTasks()
void cppgc::internal::Sweeper::SweeperImpl::CancelAllSweepingTasks () [inline], [private]
Definition at line 1586 of file sweeper.cc.
                                {
    if (incremental_sweeper_handle_) {
      incremental_sweeper_handle_.Cancel();
    }
    if (incremental_sweeper_low_priority_handle_) {
      incremental_sweeper_low_priority_handle_.Cancel();
    }
    if (concurrent_sweeper_handle_ && concurrent_sweeper_handle_->IsValid()) {
      concurrent_sweeper_handle_->Cancel();
    }
  }
References cppgc::internal::SingleThreadedHandle::Cancel(), concurrent_sweeper_handle_, incremental_sweeper_handle_, and incremental_sweeper_low_priority_handle_.
Referenced by SynchronizeAndFinalizeConcurrentAndIncrementalSweeping(), and ~SweeperImpl().
FinalizeSweep()
void cppgc::internal::Sweeper::SweeperImpl::FinalizeSweep () [inline]
Definition at line 1317 of file sweeper.cc.
                       {
    // Synchronize with the concurrent sweeper and call remaining finalizers.
    SynchronizeAndFinalizeConcurrentAndIncrementalSweeping();
    // Clear space taken up by sweeper metadata.
    space_states_.clear();
    is_in_progress_ = false;
    notify_done_pending_ = true;
    unused_destroyed_normal_pages_ = 0;
  }
References is_in_progress_, notify_done_pending_, space_states_, SynchronizeAndFinalizeConcurrentAndIncrementalSweeping(), and unused_destroyed_normal_pages_.
Referenced by Finish(), FinishIfOutOfWork(), and PerformSweepOnMutatorThread().
Finish()
void cppgc::internal::Sweeper::SweeperImpl::Finish () [inline]
Definition at line 1286 of file sweeper.cc.
                {
    DCHECK(is_in_progress_);
    MutatorThreadSweepingScope sweeping_in_progress(*this);
    // First, call finalizers on the mutator thread. This is just an
    // optimization as we need to call finalizers after sweeping as well. It
    // allows to spend the time in the concurrent sweeper for actual sweeping.
    SweepFinalizer finalizer(
        platform_, stats_collector_, kSweepWithoutSpaceAssignment,
        &unused_destroyed_normal_pages_, config_.free_memory_handling,
        EmptyPageHandling::kDestroy);
    finalizer.Finalize(space_states_);
    finalizer.Finalize(empty_normal_pages_);
    finalizer.Finalize(empty_large_pages_);
    // Then, help out the concurrent thread.
    MutatorThreadSweeper sweeper(
        heap_.heap(), platform_, stats_collector_, kSweepWithoutSpaceAssignment,
        &unused_destroyed_normal_pages_, config_.free_memory_handling,
        EmptyPageHandling::kDestroy);
    sweeper.Sweep(space_states_);
    sweeper.Sweep(empty_normal_pages_);
    sweeper.Sweep(empty_large_pages_);
    // There's nothing left to sweep here for the main thread. The concurrent
    // sweeper may still sweep pages and create pages to be finalized after
    // joining the the job.
    FinalizeSweep();
  }
References config_, DCHECK, empty_large_pages_, empty_normal_pages_, FinalizeSweep(), cppgc::internal::SweepingConfig::free_memory_handling, cppgc::internal::RawHeap::heap(), heap_, is_in_progress_, cppgc::internal::anonymous_namespace{sweeper.cc}::kSweepWithoutSpaceAssignment, platform_, space_states_, stats_collector_, and unused_destroyed_normal_pages_.
Referenced by FinishIfRunning().
FinishIfOutOfWork()
void cppgc::internal::Sweeper::SweeperImpl::FinishIfOutOfWork () [inline]
Definition at line 1245 of file sweeper.cc.
                           {
    if (!is_in_progress_ || is_sweeping_on_mutator_thread_) {
      return;
    }
    // We only finish through this method if concurrent sweeping is enabled but
    // not running anymore. All other paths finish sweeping through incremental
    // steps.
    if (!concurrent_sweeper_handle_ || !concurrent_sweeper_handle_->IsValid() ||
        concurrent_sweeper_handle_->IsActive()) {
      return;
    }
    // At this point we know that the concurrent sweeping task has run
    // out-of-work: all pages are swept. The main thread still needs to finalize
    // swept pages.
    DCHECK(std::all_of(space_states_.begin(), space_states_.end(),
                       [](const SweepingState& state) {
                         return state.unswept_pages.IsEmpty();
                       }));
    DCHECK(empty_normal_pages_.unswept_pages.IsEmpty());
    DCHECK(empty_large_pages_.unswept_pages.IsEmpty());
    if (std::any_of(space_states_.begin(), space_states_.end(),
                    [](const SweepingState& state) {
                      return !state.swept_unfinalized_pages.IsEmpty();
                    })) {
      return;
    }
    if (!empty_normal_pages_.swept_unfinalized_pages.IsEmpty() ||
        !empty_large_pages_.swept_unfinalized_pages.IsEmpty()) {
      return;
    }
    // All pages have also been finalized. Finalizing pages likely occured on
    // allocation, in which sweeping is not finalized even though all work is
    // done.
    {
      StatsCollector::EnabledScope stats_scope(
          stats_collector_, StatsCollector::kSweepFinishIfOutOfWork);
      FinalizeSweep();
    }
    NotifyDone();
  }
References v8::base::all_of(), v8::base::any_of(), concurrent_sweeper_handle_, DCHECK, empty_large_pages_, empty_normal_pages_, FinalizeSweep(), is_in_progress_, is_sweeping_on_mutator_thread_, NotifyDone(), space_states_, and stats_collector_.
FinishIfRunning()
bool cppgc::internal::Sweeper::SweeperImpl::FinishIfRunning () [inline]
Definition at line 1210 of file sweeper.cc.
                         {
    if (!is_in_progress_) {
      return false;
    }
    // Bail out for recursive sweeping calls. This can happen when finalizers
    // allocate new memory.
    if (is_sweeping_on_mutator_thread_) {
      return false;
    }
    {
      std::optional<StatsCollector::EnabledScope> stats_scope;
      if (config_.sweeping_type != SweepingConfig::SweepingType::kAtomic) {
        stats_scope.emplace(stats_collector_,
                            StatsCollector::kIncrementalSweep);
      }
      StatsCollector::EnabledScope inner_scope(stats_collector_,
                                               StatsCollector::kSweepFinish);
      if (concurrent_sweeper_handle_ && concurrent_sweeper_handle_->IsValid() &&
          concurrent_sweeper_handle_->UpdatePriorityEnabled()) {
        concurrent_sweeper_handle_->UpdatePriority(kBackgroundBoostedPriority);
      }
      Finish();
    }
    NotifyDone();
    return true;
  }
References concurrent_sweeper_handle_, config_, Finish(), is_in_progress_, is_sweeping_on_mutator_thread_, cppgc::Heap::kAtomic, cppgc::internal::anonymous_namespace{sweeper.cc}::kBackgroundBoostedPriority, NotifyDone(), stats_collector_, and cppgc::internal::SweepingConfig::sweeping_type.
IsConcurrentSweepingDone()
bool cppgc::internal::Sweeper::SweeperImpl::IsConcurrentSweepingDone () const [inline]
Definition at line 1239 of file sweeper.cc.
                                        {
    return !concurrent_sweeper_handle_ ||
           !concurrent_sweeper_handle_->IsValid() ||
           !concurrent_sweeper_handle_->IsActive();
  }
References concurrent_sweeper_handle_.
Referenced by SweepInForegroundTaskImpl().
IsSweepingInProgress()
bool cppgc::internal::Sweeper::SweeperImpl::IsSweepingInProgress () const [inline]
Definition at line 1348 of file sweeper.cc.
{ return is_in_progress_; }
References is_in_progress_.
IsSweepingOnMutatorThread()
bool cppgc::internal::Sweeper::SweeperImpl::IsSweepingOnMutatorThread () const [inline]
Definition at line 1344 of file sweeper.cc.
                                         {
    return is_sweeping_on_mutator_thread_;
  }
References is_sweeping_on_mutator_thread_.
NotifyDone()
void cppgc::internal::Sweeper::SweeperImpl::NotifyDone () [inline]
Definition at line 1329 of file sweeper.cc.
                    {
    DCHECK(!is_in_progress_);
    DCHECK(notify_done_pending_);
    notify_done_pending_ = false;
    stats_collector_->NotifySweepingCompleted(config_.sweeping_type);
    if (config_.free_memory_handling ==
        FreeMemoryHandling::kDiscardWherePossible) {
      heap_.heap()->page_backend()->ReleasePooledPages();
    }
  }
References config_, DCHECK, cppgc::internal::SweepingConfig::free_memory_handling, cppgc::internal::RawHeap::heap(), heap_, is_in_progress_, cppgc::internal::kDiscardWherePossible, notify_done_pending_, cppgc::internal::StatsCollector::NotifySweepingCompleted(), cppgc::internal::HeapBase::page_backend(), cppgc::internal::PageBackend::ReleasePooledPages(), stats_collector_, and cppgc::internal::SweepingConfig::sweeping_type.
Referenced by FinishIfOutOfWork(), FinishIfRunning(), and PerformSweepOnMutatorThread().
PerformSweepOnMutatorThread()
bool cppgc::internal::Sweeper::SweeperImpl::PerformSweepOnMutatorThread (v8::base::TimeDelta max_duration, StatsCollector::ScopeId internal_scope_id, MutatorThreadSweepingMode sweeping_mode) [inline]
Definition at line 1350 of file sweeper.cc.
                                                                            {
    if (!is_in_progress_) return true;
    MutatorThreadSweepingScope sweeping_in_progress(*this);
    {
      StatsCollector::EnabledScope stats_scope(
          stats_collector_, StatsCollector::kIncrementalSweep);
      MutatorThreadSweeper sweeper(
          heap_.heap(), platform_, stats_collector_,
          kSweepWithoutSpaceAssignment, &unused_destroyed_normal_pages_,
          config_.free_memory_handling, EmptyPageHandling::kDestroy);
      {
        StatsCollector::EnabledScope inner_stats_scope(
            stats_collector_, internal_scope_id, "max_duration_ms",
            max_duration.InMillisecondsF(), "sweeping_mode",
            ToString(sweeping_mode));
        const auto deadline = v8::base::TimeTicks::Now() + max_duration;
        if (!sweeper.FinalizeAndSweepWithDeadline(
                StatsCollector::kSweepFinalizeEmptyPages, empty_normal_pages_,
                deadline, sweeping_mode)) {
          return false;
        }
        for (auto& state : space_states_) {
          if (!sweeper.FinalizeAndSweepWithDeadline(
                  StatsCollector::kSweepFinalizeSweptPages, state, deadline,
                  sweeping_mode)) {
            return false;
          }
        }
        if (!sweeper.FinalizeAndSweepWithDeadline(
                StatsCollector::kSweepFinalizeEmptyPages, empty_large_pages_,
                deadline, sweeping_mode)) {
          return false;
        }
        if (sweeping_mode != MutatorThreadSweepingMode::kAll) {
          return false;
        }
      }
      FinalizeSweep();
    }
    NotifyDone();
    return true;
  }
References config_, empty_large_pages_, empty_normal_pages_, FinalizeSweep(), cppgc::internal::SweepingConfig::free_memory_handling, cppgc::internal::RawHeap::heap(), heap_, v8::base::TimeDelta::InMillisecondsF(), is_in_progress_, cppgc::internal::anonymous_namespace{sweeper.cc}::kSweepWithoutSpaceAssignment, NotifyDone(), v8::base::TimeTicks::Now(), platform_, space_states_, stats_collector_, ToString(), and unused_destroyed_normal_pages_.
Referenced by SweepInForegroundTaskImpl().
RemoveMutatorThreadSweepingObserver()
void cppgc::internal::Sweeper::SweeperImpl::RemoveMutatorThreadSweepingObserver (Sweeper::SweepingOnMutatorThreadObserver * observer) [inline]
Definition at line 1406 of file sweeper.cc.
                                                        {
    const auto it =
        std::find(mutator_thread_sweeping_observers_.begin(),
                  mutator_thread_sweeping_observers_.end(), observer);
    DCHECK_NE(mutator_thread_sweeping_observers_.end(), it);
    mutator_thread_sweeping_observers_.erase(it);
  }
References DCHECK_NE, and mutator_thread_sweeping_observers_.
ScheduleConcurrentSweeping()
void cppgc::internal::Sweeper::SweeperImpl::ScheduleConcurrentSweeping () [inline], [private]
Definition at line 1575 of file sweeper.cc.
                                    {
    DCHECK_GE(config_.sweeping_type,
              SweepingConfig::SweepingType::kIncrementalAndConcurrent);
    concurrent_sweeper_handle_ = platform_->PostJob(
        kBackgroundRegularPriority,
        std::make_unique<ConcurrentSweepTask>(
            platform_, *heap_.heap(), &space_states_, &empty_normal_pages_,
            &empty_large_pages_, config_.free_memory_handling));
  }
References concurrent_sweeper_handle_, config_, DCHECK_GE, empty_large_pages_, empty_normal_pages_, cppgc::internal::SweepingConfig::free_memory_handling, cppgc::internal::RawHeap::heap(), heap_, cppgc::internal::anonymous_namespace{sweeper.cc}::kBackgroundRegularPriority, cppgc::Heap::kIncrementalAndConcurrent, platform_, cppgc::Platform::PostJob(), space_states_, and cppgc::internal::SweepingConfig::sweeping_type.
Referenced by Start().
ScheduleIncrementalSweeping()
void cppgc::internal::Sweeper::SweeperImpl::ScheduleIncrementalSweeping (std::optional< v8::base::TimeDelta > delay = {}) [inline], [private]
Definition at line 1545 of file sweeper.cc.
                                           {}) {
    DCHECK_GE(config_.sweeping_type,
              SweepingConfig::SweepingType::kIncremental);
    if (!foreground_task_runner_) {
      return;
    }
    low_priority_task_ran_ = false;
    incremental_sweeper_handle_.CancelIfNonEmpty();
    incremental_sweeper_handle_ = IncrementalSweepTask::Post(
        *this, foreground_task_runner_, kForegroundRegularPriority, delay);
  }
Referenced by Start(), and SweepForTask().
ScheduleLowPriorityIncrementalSweeping()
void cppgc::internal::Sweeper::SweeperImpl::ScheduleLowPriorityIncrementalSweeping (std::optional< v8::base::TimeDelta > delay = {}) [inline], [private]
Definition at line 1560 of file sweeper.cc.
                                           {}) {
    DCHECK_GE(config_.sweeping_type,
              SweepingConfig::SweepingType::kIncremental);
    if (!low_priority_foreground_task_runner_) {
      return;
    }
    incremental_sweeper_low_priority_handle_.CancelIfNonEmpty();
    incremental_sweeper_low_priority_handle_ =
        IncrementalSweepTask::Post(*this, low_priority_foreground_task_runner_,
                                   kForegroundLowPriority, delay);
  }
Referenced by Start(), and SweepForLowPriorityTask().
Start()
void cppgc::internal::Sweeper::SweeperImpl::Start (SweepingConfig config) [inline]
Definition at line 975 of file sweeper.cc.
                                    {
    StatsCollector::EnabledScope stats_scope(stats_collector_,
                                             StatsCollector::kAtomicSweep);
    is_in_progress_ = true;
    config_ = config;
    if (!foreground_task_runner_) {
      // The sweeper is already initialized when the platform may not be able to
      // return a foreground task runner. Lazily initialize the runners on first
      // sweep.
      foreground_task_runner_ =
          platform_->GetForegroundTaskRunner(kForegroundRegularPriority);
      low_priority_foreground_task_runner_ =
          platform_->GetForegroundTaskRunner(kForegroundLowPriority);
      // Having a low priority runner implies having a regular runner as well.
      CHECK_IMPLIES(low_priority_foreground_task_runner_.get(),
                    foreground_task_runner_.get());
      const auto supports_non_nestable_tasks =
          [](const std::shared_ptr<TaskRunner>& runner) {
            return runner && runner->NonNestableTasksEnabled() &&
                   runner->NonNestableDelayedTasksEnabled();
          };
      if (!supports_non_nestable_tasks(foreground_task_runner_) ||
          !supports_non_nestable_tasks(low_priority_foreground_task_runner_)) {
        foreground_task_runner_.reset();
        low_priority_foreground_task_runner_.reset();
      }
    }
    // Verify bitmap for all spaces regardless of |compactable_space_handling|.
    ObjectStartBitmapVerifier().Verify(heap_);
    // If inaccessible memory is touched to check whether it is set up
    // correctly it cannot be discarded.
    if (!CanDiscardMemory()) {
      config_.free_memory_handling = FreeMemoryHandling::kDoNotDiscard;
    }
    if (config_.free_memory_handling ==
        FreeMemoryHandling::kDiscardWherePossible) {
      // The discarded counter will be recomputed.
      heap_.heap()->stats_collector()->ResetDiscardedMemory();
    }
    PrepareForSweepVisitor(heap_.heap(), &space_states_, &empty_normal_pages_,
                           &empty_large_pages_,
                           config.compactable_space_handling)
        .Run(heap_);
    if (config.sweeping_type >= SweepingConfig::SweepingType::kIncremental) {
      ScheduleLowPriorityIncrementalSweeping();
      ScheduleIncrementalSweeping(kDelayWhileLowPrioritySweepingMakesProgress);
    }
    if (config.sweeping_type >=
        SweepingConfig::SweepingType::kIncrementalAndConcurrent) {
      ScheduleConcurrentSweeping();
    }
  }
References cppgc::internal::Sweeper::CanDiscardMemory(), CHECK_IMPLIES, cppgc::internal::SweepingConfig::compactable_space_handling, config_, empty_large_pages_, empty_normal_pages_, foreground_task_runner_, cppgc::internal::SweepingConfig::free_memory_handling, cppgc::Platform::GetForegroundTaskRunner(), cppgc::internal::RawHeap::heap(), heap_, is_in_progress_, kDelayWhileLowPrioritySweepingMakesProgress, cppgc::internal::kDiscardWherePossible, cppgc::internal::kDoNotDiscard, cppgc::internal::anonymous_namespace{sweeper.cc}::kForegroundLowPriority, cppgc::internal::anonymous_namespace{sweeper.cc}::kForegroundRegularPriority, cppgc::Heap::kIncremental, cppgc::Heap::kIncrementalAndConcurrent, low_priority_foreground_task_runner_, platform_, cppgc::internal::StatsCollector::ResetDiscardedMemory(), ScheduleConcurrentSweeping(), ScheduleIncrementalSweeping(), ScheduleLowPriorityIncrementalSweeping(), space_states_, cppgc::internal::HeapBase::stats_collector(), stats_collector_, and cppgc::internal::SweepingConfig::sweeping_type.
SweepForAllocationIfRunning()
bool cppgc::internal::Sweeper::SweeperImpl::SweepForAllocationIfRunning (BaseSpace * space, size_t size, v8::base::TimeDelta max_duration) [inline]
Definition at line 1193 of file sweeper.cc.
                                                                 {
    if (!is_in_progress_) {
      return false;
    }
    // Bail out for recursive sweeping calls. This can happen when finalizers
    // allocate new memory.
    if (is_sweeping_on_mutator_thread_) {
      return false;
    }
    return space->is_large()
               ? SweepForLargeAllocation(space, size, max_duration)
               : SweepForNormalAllocation(space, size, max_duration);
  }
References is_in_progress_, is_sweeping_on_mutator_thread_, size(), space, SweepForLargeAllocation(), and SweepForNormalAllocation().
SweepForLargeAllocation()
bool cppgc::internal::Sweeper::SweeperImpl::SweepForLargeAllocation (BaseSpace * space, size_t size, v8::base::TimeDelta max_duration) [inline]
Definition at line 1077 of file sweeper.cc.
                                                             {
    DCHECK(space->is_large());
#ifdef DEBUG
    // SpaceState for large objects is emtpy as those objects are put directly
    // on `empty_large_pages_`.
    SweepingState& space_state = space_states_[space->index()];
    DCHECK(space_state.unswept_pages.IsEmpty());
    DCHECK(space_state.swept_unfinalized_pages.IsEmpty());
#endif // DEBUG
    // Bail out if there's no empty large pages that could be freed and be
    // reused for a large allocation.
    if (empty_large_pages_.swept_unfinalized_pages.IsEmpty() &&
        empty_large_pages_.unswept_pages.IsEmpty()) {
      return false;
    }
    StatsCollector::EnabledScope incremental_sweep_scope(
        stats_collector_, StatsCollector::kIncrementalSweep);
    StatsCollector::DisabledScope sweep_on_allocation_scope(
        stats_collector_, StatsCollector::kSweepOnAllocation);
    MutatorThreadSweepingScope sweeping_in_progress(*this);
    const auto deadline = v8::base::TimeTicks::Now() + max_duration;
    SweepFinalizer finalizer(
        platform_, stats_collector_, space, &unused_destroyed_normal_pages_,
        config_.free_memory_handling, EmptyPageHandling::kDestroy);
    // Check empty pages first. Try to just finalize a page without sweeping.
    // If there's a single page in there we will use it.
    if (finalizer.FinalizeWithDeadlineAndSize(
            StatsCollector::kSweepFinalizeEmptyPages, empty_large_pages_,
            deadline, size)) {
      return true;
    }
    MutatorThreadSweeper sweeper(heap_.heap(), platform_, stats_collector_,
                                 space, &unused_destroyed_normal_pages_,
                                 config_.free_memory_handling,
                                 EmptyPageHandling::kDestroy);
    // Sweeping an empty page in case there's nothing with finalizers. If
    // there's a single page in there we will use it.
    if (sweeper.SweepWithDeadlineAndSize(StatsCollector::kSweepEmptyPages,
                                         empty_large_pages_, deadline, size)) {
      return true;
    }
    return false;
  }
References config_, DCHECK, empty_large_pages_, cppgc::internal::SweepingConfig::free_memory_handling, cppgc::internal::RawHeap::heap(), heap_, v8::base::TimeTicks::Now(), platform_, size(), space, space_states_, stats_collector_, and unused_destroyed_normal_pages_.
Referenced by SweepForAllocationIfRunning().
SweepForLowPriorityTask()
void cppgc::internal::Sweeper::SweeperImpl::SweepForLowPriorityTask (v8::base::TimeDelta max_duration) [inline]
Definition at line 1059 of file sweeper.cc.
                                                             {
    low_priority_task_ran_ = true;
    switch (SweepInForegroundTaskImpl(
        max_duration, StatsCollector::kSweepInLowPriorityTask)) {
      case SweepResult::kFullyDone:
        return;
      case SweepResult::kInProgress:
        // More work to do. Continue sweeping with low priority.
        ScheduleLowPriorityIncrementalSweeping();
        return;
      case SweepResult::kMainThreadDoneConcurrentInProgress:
        ScheduleLowPriorityIncrementalSweeping(
            kDelayWhileLowPrioritySweepingMakesProgress);
        return;
    }
    UNREACHABLE();
  }
References kDelayWhileLowPrioritySweepingMakesProgress, kFullyDone, kInProgress, kMainThreadDoneConcurrentInProgress, low_priority_task_ran_, ScheduleLowPriorityIncrementalSweeping(), SweepInForegroundTaskImpl(), and UNREACHABLE.
Referenced by cppgc::internal::Sweeper::SweeperImpl::IncrementalSweepTask::Run().
SweepForNormalAllocation()
bool cppgc::internal::Sweeper::SweeperImpl::SweepForNormalAllocation (BaseSpace * space, size_t size, v8::base::TimeDelta max_duration) [inline]
Definition at line 1126 of file sweeper.cc.
                                                              {
    DCHECK(!space->is_large());
    if (unused_destroyed_normal_pages_ > 0 && page_pool_.pooled() > 0) {
      unused_destroyed_normal_pages_--;
      // Destroyed pages during sweeping in tasks are generally sitting in the
      // page pool and can be reused without increasing memory footprint.
      return false;
    }
    SweepingState& space_state = space_states_[space->index()];
    // Bail out if there's no empty pages and no pages to be processed for the
    // specific space at this moment.
    if (empty_normal_pages_.swept_unfinalized_pages.IsEmpty() &&
        empty_normal_pages_.unswept_pages.IsEmpty() &&
        space_state.swept_unfinalized_pages.IsEmpty() &&
        space_state.unswept_pages.IsEmpty()) {
      return false;
    }
    StatsCollector::EnabledScope incremental_sweep_scope(
        stats_collector_, StatsCollector::kIncrementalSweep);
    StatsCollector::DisabledScope sweep_on_allocation_scope(
        stats_collector_, StatsCollector::kSweepOnAllocation);
    MutatorThreadSweepingScope sweeping_in_progress(*this);
    const auto deadline = v8::base::TimeTicks::Now() + max_duration;
    SweepFinalizer finalizer(
        platform_, stats_collector_, space, &unused_destroyed_normal_pages_,
        config_.free_memory_handling, EmptyPageHandling::kReturn);
    // Check empty pages first. Try to just finalize a page without sweeping.
    // If there's a single page in there we will use it.
    if (finalizer.FinalizeWithDeadlineAndSize(
            StatsCollector::kSweepFinalizeEmptyPages, empty_normal_pages_,
            deadline, size)) {
      return true;
    }
    MutatorThreadSweeper sweeper(heap_.heap(), platform_, stats_collector_,
                                 space, &unused_destroyed_normal_pages_,
                                 config_.free_memory_handling,
                                 EmptyPageHandling::kReturn);
    // Sweeping an empty page in case there's nothing with finalizers. If
    // there's a single page in there we will use it.
    if (sweeper.SweepWithDeadlineAndSize(StatsCollector::kSweepEmptyPages,
                                         empty_normal_pages_, deadline, size)) {
      return true;
    }
    // Process unfinalized non-empty pages as finalizing a page is generally
    // faster than sweeping.
    if (finalizer.FinalizeWithDeadlineAndSize(
            StatsCollector::kSweepFinalizeSweptPages, space_state, deadline,
            size)) {
      return true;
    }
    // Then, if no matching slot is found in the unfinalized pages, search the
    // unswept page. This also helps out the concurrent sweeper.
    if (sweeper.SweepWithDeadlineAndSize(StatsCollector::kSweepPages,
                                         space_state, deadline, size)) {
      return true;
    }
    return false;
  }
References config_, DCHECK, empty_normal_pages_, cppgc::internal::SweepingConfig::free_memory_handling, cppgc::internal::RawHeap::heap(), heap_, v8::base::TimeTicks::Now(), page_pool_, platform_, cppgc::internal::NormalPageMemoryPool::pooled(), size(), space, space_states_, stats_collector_, and unused_destroyed_normal_pages_.
Referenced by SweepForAllocationIfRunning().
SweepForTask()
void cppgc::internal::Sweeper::SweeperImpl::SweepForTask (v8::base::TimeDelta max_duration) [inline]
Definition at line 1033 of file sweeper.cc.
                                                  {
    // Before sweeping in a task, handle low priority sweeping cases. These are
    // no-ops if low priority sweeping is not running.
    if (low_priority_task_ran_) {
      // Low priority task made progress. Reschedule with delay.
      ScheduleIncrementalSweeping(kDelayWhileLowPrioritySweepingMakesProgress);
      return;
    }
    // Low priority sweeping is not running or not being invoked on time.
    switch (
        SweepInForegroundTaskImpl(max_duration, StatsCollector::kSweepInTask)) {
      case SweepResult::kFullyDone:
        return;
      case SweepResult::kInProgress:
        ScheduleIncrementalSweeping(kDelayForRegularPrioritySweeping);
        return;
      case SweepResult::kMainThreadDoneConcurrentInProgress:
        // Throttle incremental sweeping while the concurrent Job is still
        // making progress.
        ScheduleIncrementalSweeping(kDelayWhileConcurrentSweepingMakesProgress);
        return;
    }
    UNREACHABLE();
  }
References kDelayForRegularPrioritySweeping, kDelayWhileConcurrentSweepingMakesProgress, kDelayWhileLowPrioritySweepingMakesProgress, kFullyDone, kInProgress, kMainThreadDoneConcurrentInProgress, low_priority_task_ran_, ScheduleIncrementalSweeping(), SweepInForegroundTaskImpl(), and UNREACHABLE.
Referenced by cppgc::internal::Sweeper::SweeperImpl::IncrementalSweepTask::Run().
SweepInForegroundTaskImpl()
SweepResult cppgc::internal::Sweeper::SweeperImpl::SweepInForegroundTaskImpl (v8::base::TimeDelta max_duration, StatsCollector::ScopeId scope) [inline], [private]
Definition at line 1514 of file sweeper.cc.
                                                                     {
    // First round of sweeping.
    bool concurrent_sweep_complete = IsConcurrentSweepingDone();
    const auto start = v8::base::TimeTicks::Now();
    bool main_thread_sweep_complete = PerformSweepOnMutatorThread(
        max_duration, scope,
        concurrent_sweep_complete ? MutatorThreadSweepingMode::kAll
                                  : MutatorThreadSweepingMode::kOnlyFinalizers);
    if (main_thread_sweep_complete && !concurrent_sweep_complete &&
        IsConcurrentSweepingDone()) {
      // Concurrent sweeping finished while processing the first round. Use the
      // left over time for a second round to avoid scheduling another task.
      max_duration -= (v8::base::TimeTicks::Now() - start);
      if (max_duration > v8::base::TimeDelta::FromMilliseconds(0)) {
        concurrent_sweep_complete = true;
        main_thread_sweep_complete = PerformSweepOnMutatorThread(
            max_duration, scope, MutatorThreadSweepingMode::kAll);
      }
    }
    if (main_thread_sweep_complete) {
      if (!concurrent_sweep_complete) {
        return SweepResult::kMainThreadDoneConcurrentInProgress;
      } else {
        CHECK(!is_in_progress_);
        return SweepResult::kFullyDone;
      }
    }
    return SweepResult::kInProgress;
  }
References CHECK, v8::base::TimeDelta::FromMilliseconds(), is_in_progress_, IsConcurrentSweepingDone(), kFullyDone, kInProgress, kMainThreadDoneConcurrentInProgress, v8::base::TimeTicks::Now(), and PerformSweepOnMutatorThread().
Referenced by SweepForLowPriorityTask(), and SweepForTask().
SynchronizeAndFinalizeConcurrentAndIncrementalSweeping()
void cppgc::internal::Sweeper::SweeperImpl::SynchronizeAndFinalizeConcurrentAndIncrementalSweeping () [inline], [private]
Definition at line 1598 of file sweeper.cc.
                                                                {
    // The precondition for this call is that actual sweeping is done. So all
    // that's left is potentially invoking finalizers.
    CancelAllSweepingTasks();
    DCHECK(std::all_of(space_states_.begin(), space_states_.end(),
                       [](const SweepingState& state) {
                         return state.unswept_pages.IsEmpty();
                       }));
    DCHECK(empty_normal_pages_.unswept_pages.IsEmpty());
    DCHECK(empty_large_pages_.unswept_pages.IsEmpty());
    SweepFinalizer finalizer(
        platform_, stats_collector_, kSweepWithoutSpaceAssignment,
        &unused_destroyed_normal_pages_, config_.free_memory_handling,
        EmptyPageHandling::kDestroy);
    finalizer.Finalize(space_states_);
    finalizer.Finalize(empty_normal_pages_);
    finalizer.Finalize(empty_large_pages_);
  }
References v8::base::all_of(), CancelAllSweepingTasks(), config_, DCHECK, empty_large_pages_, empty_normal_pages_, cppgc::internal::SweepingConfig::free_memory_handling, cppgc::internal::anonymous_namespace{sweeper.cc}::kSweepWithoutSpaceAssignment, platform_, space_states_, stats_collector_, and unused_destroyed_normal_pages_.
Referenced by FinalizeSweep().
WaitForConcurrentSweepingForTesting()
void cppgc::internal::Sweeper::SweeperImpl::WaitForConcurrentSweepingForTesting () [inline]
Definition at line 1340 of file sweeper.cc.
                                             {
    if (concurrent_sweeper_handle_) concurrent_sweeper_handle_->Join();
  }
References concurrent_sweeper_handle_.
Member Data Documentation
concurrent_sweeper_handle_
std::unique_ptr<cppgc::JobHandle> cppgc::internal::Sweeper::SweeperImpl::concurrent_sweeper_handle_ [private]
Definition at line 1642 of file sweeper.cc.
Referenced by CancelAllSweepingTasks(), FinishIfOutOfWork(), FinishIfRunning(), IsConcurrentSweepingDone(), ScheduleConcurrentSweeping(), and WaitForConcurrentSweepingForTesting().
config_
SweepingConfig cppgc::internal::Sweeper::SweeperImpl::config_ [private]
Definition at line 1639 of file sweeper.cc.
Referenced by Finish(), FinishIfRunning(), NotifyDone(), PerformSweepOnMutatorThread(), ScheduleConcurrentSweeping(), Start(), SweepForLargeAllocation(), SweepForNormalAllocation(), and SynchronizeAndFinalizeConcurrentAndIncrementalSweeping().
empty_large_pages_
SweepingState cppgc::internal::Sweeper::SweeperImpl::empty_large_pages_ [private]
Definition at line 1631 of file sweeper.cc.
Referenced by Finish(), FinishIfOutOfWork(), PerformSweepOnMutatorThread(), ScheduleConcurrentSweeping(), Start(), SweepForLargeAllocation(), and SynchronizeAndFinalizeConcurrentAndIncrementalSweeping().
empty_normal_pages_
SweepingState cppgc::internal::Sweeper::SweeperImpl::empty_normal_pages_ [private]
Definition at line 1626 of file sweeper.cc.
Referenced by Finish(), FinishIfOutOfWork(), PerformSweepOnMutatorThread(), ScheduleConcurrentSweeping(), Start(), SweepForNormalAllocation(), and SynchronizeAndFinalizeConcurrentAndIncrementalSweeping().
foreground_task_runner_
std::shared_ptr<cppgc::TaskRunner> cppgc::internal::Sweeper::SweeperImpl::foreground_task_runner_ [private]
Definition at line 1637 of file sweeper.cc.
Referenced by Start().
heap_
RawHeap& cppgc::internal::Sweeper::SweeperImpl::heap_ [private]
Definition at line 1620 of file sweeper.cc.
Referenced by Finish(), NotifyDone(), PerformSweepOnMutatorThread(), ScheduleConcurrentSweeping(), Start(), SweepForLargeAllocation(), and SweepForNormalAllocation().
incremental_sweeper_handle_
IncrementalSweepTask::Handle cppgc::internal::Sweeper::SweeperImpl::incremental_sweeper_handle_ [private]
Definition at line 1640 of file sweeper.cc.
Referenced by CancelAllSweepingTasks().
incremental_sweeper_low_priority_handle_
IncrementalSweepTask::Handle cppgc::internal::Sweeper::SweeperImpl::incremental_sweeper_low_priority_handle_ [private]
Definition at line 1641 of file sweeper.cc.
Referenced by CancelAllSweepingTasks().
is_in_progress_
bool cppgc::internal::Sweeper::SweeperImpl::is_in_progress_ = false [private]
Definition at line 1649 of file sweeper.cc.
Referenced by FinalizeSweep(), Finish(), FinishIfOutOfWork(), FinishIfRunning(), IsSweepingInProgress(), NotifyDone(), PerformSweepOnMutatorThread(), Start(), SweepForAllocationIfRunning(), and SweepInForegroundTaskImpl().
is_sweeping_on_mutator_thread_
bool cppgc::internal::Sweeper::SweeperImpl::is_sweeping_on_mutator_thread_ = false [private]
Definition at line 1653 of file sweeper.cc.
Referenced by FinishIfOutOfWork(), FinishIfRunning(), IsSweepingOnMutatorThread(), cppgc::internal::Sweeper::SweeperImpl::MutatorThreadSweepingScope::MutatorThreadSweepingScope(), SweepForAllocationIfRunning(), and cppgc::internal::Sweeper::SweeperImpl::MutatorThreadSweepingScope::~MutatorThreadSweepingScope().
kDelayForRegularPrioritySweeping
constexpr auto cppgc::internal::Sweeper::SweeperImpl::kDelayForRegularPrioritySweeping [static], [constexpr], [private]
Initial value:
=
      v8::base::TimeDelta::FromMilliseconds(1)
Definition at line 1511 of file sweeper.cc.
Referenced by SweepForTask().
kDelayWhileConcurrentSweepingMakesProgress
constexpr auto cppgc::internal::Sweeper::SweeperImpl::kDelayWhileConcurrentSweepingMakesProgress [static], [constexpr], [private]
Initial value:
=
      v8::base::TimeDelta::FromMilliseconds(5)
Definition at line 1506 of file sweeper.cc.
Referenced by SweepForTask().
kDelayWhileLowPrioritySweepingMakesProgress
constexpr auto cppgc::internal::Sweeper::SweeperImpl::kDelayWhileLowPrioritySweepingMakesProgress [static], [constexpr], [private]
Initial value:
=
      v8::base::TimeDelta::FromMilliseconds(100)
Definition at line 1503 of file sweeper.cc.
Referenced by Start(), SweepForLowPriorityTask(), and SweepForTask().
kMaxHeapPercentageForNoSweeping
constexpr double cppgc::internal::Sweeper::SweeperImpl::kMaxHeapPercentageForNoSweeping = 50 [static], [constexpr], [private]
Definition at line 1501 of file sweeper.cc.
low_priority_foreground_task_runner_
std::shared_ptr<cppgc::TaskRunner> cppgc::internal::Sweeper::SweeperImpl::low_priority_foreground_task_runner_ [private]
Definition at line 1638 of file sweeper.cc.
Referenced by Start().
low_priority_task_ran_
bool cppgc::internal::Sweeper::SweeperImpl::low_priority_task_ran_ = false [private]
Definition at line 1647 of file sweeper.cc.
Referenced by SweepForLowPriorityTask(), and SweepForTask().
mutator_thread_sweeping_observers_
std::vector<Sweeper::SweepingOnMutatorThreadObserver*> cppgc::internal::Sweeper::SweeperImpl::mutator_thread_sweeping_observers_ [private]
Definition at line 1644 of file sweeper.cc.
Referenced by AddMutatorThreadSweepingObserver(), cppgc::internal::Sweeper::SweeperImpl::MutatorThreadSweepingScope::MutatorThreadSweepingScope(), RemoveMutatorThreadSweepingObserver(), and cppgc::internal::Sweeper::SweeperImpl::MutatorThreadSweepingScope::~MutatorThreadSweepingScope().
notify_done_pending_
bool cppgc::internal::Sweeper::SweeperImpl::notify_done_pending_ = false [private]
Definition at line 1650 of file sweeper.cc.
Referenced by FinalizeSweep(), and NotifyDone().
page_pool_
NormalPageMemoryPool& cppgc::internal::Sweeper::SweeperImpl::page_pool_ [private]
Definition at line 1621 of file sweeper.cc.
Referenced by SweepForNormalAllocation().
platform_
cppgc::Platform* cppgc::internal::Sweeper::SweeperImpl::platform_ [private]
Definition at line 1636 of file sweeper.cc.
Referenced by Finish(), PerformSweepOnMutatorThread(), ScheduleConcurrentSweeping(), Start(), SweeperImpl(), SweepForLargeAllocation(), SweepForNormalAllocation(), and SynchronizeAndFinalizeConcurrentAndIncrementalSweeping().
space_states_
SpaceStates cppgc::internal::Sweeper::SweeperImpl::space_states_ [private]
Definition at line 1623 of file sweeper.cc.
Referenced by FinalizeSweep(), Finish(), FinishIfOutOfWork(), PerformSweepOnMutatorThread(), ScheduleConcurrentSweeping(), Start(), SweepForLargeAllocation(), SweepForNormalAllocation(), and SynchronizeAndFinalizeConcurrentAndIncrementalSweeping().
stats_collector_
StatsCollector* const cppgc::internal::Sweeper::SweeperImpl::stats_collector_ [private]
Definition at line 1622 of file sweeper.cc.
Referenced by Finish(), FinishIfOutOfWork(), FinishIfRunning(), NotifyDone(), PerformSweepOnMutatorThread(), Start(), SweepForLargeAllocation(), SweepForNormalAllocation(), and SynchronizeAndFinalizeConcurrentAndIncrementalSweeping().
unused_destroyed_normal_pages_
size_t cppgc::internal::Sweeper::SweeperImpl::unused_destroyed_normal_pages_ = 0 [private]
Definition at line 1635 of file sweeper.cc.
Referenced by FinalizeSweep(), Finish(), PerformSweepOnMutatorThread(), SweepForLargeAllocation(), SweepForNormalAllocation(), and SynchronizeAndFinalizeConcurrentAndIncrementalSweeping().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/sweeper.cc