v8::internal::RegExpResultsCache_MatchGlobalAtom Class Reference
#include <regexp.h>
Static Public Member Functions
static void TryInsert (Isolate *isolate, Tagged< String > subject, Tagged< String > pattern, int number_of_matches, int last_match_index)
static bool TryGet (Isolate *isolate, Tagged< String > subject, Tagged< String > pattern, int *number_of_matches_out, int *last_match_index_out)
static void Clear (Heap *heap)
Static Public Attributes
static constexpr int kSize = kEntrySize
Static Private Attributes
static constexpr int kSubjectIndex = 0
static constexpr int kPatternIndex = 1
static constexpr int kNumberOfMatchesIndex = 2
static constexpr int kLastMatchIndexIndex = 3
static constexpr int kEntrySize = 4
Detailed Description
Definition at line 266 of file regexp.h.
Member Function Documentation
Clear()
void v8::internal::RegExpResultsCache_MatchGlobalAtom::Clear (Heap * heap) [static]
Definition at line 1453 of file regexp.cc.
                                                         {
  MemsetTagged(heap->regexp_match_global_atom_cache()->RawFieldOfFirstElement(),
               Smi::zero(), kSize);
}
References kSize, v8::internal::MemsetTagged(), and v8::internal::Smi::zero().
Referenced by v8::internal::Heap::MarkCompactPrologue(), and TryGet().
TryGet()
bool v8::internal::RegExpResultsCache_MatchGlobalAtom::TryGet (Isolate * isolate, Tagged< String > subject, Tagged< String > pattern, int * number_of_matches_out, int * last_match_index_out) [static]
Definition at line 1421 of file regexp.cc.
                                                                           {
  DisallowGarbageCollection no_gc;
  Tagged<FixedArray> cache = isolate->heap()->regexp_match_global_atom_cache();
  DCHECK_EQ(cache->length(), kSize);
  if (!IsSlicedString(subject)) return false;
  if (pattern != cache->get(kPatternIndex)) return false;
  // Here we are looking for a subject slice that 1. starts at the same point
  // and 2. is of equal length or longer than the cached subject slice.
  Tagged<SlicedString> sliced_subject = Cast<SlicedString>(subject);
  Tagged<Object> cached_subject_object = cache->get(kSubjectIndex);
  if (!Is<SlicedString>(cached_subject_object)) {
    // Note while we insert only sliced strings, they may be converted into
    // other kinds, e.g. during GC or internalization.
    Clear(isolate->heap());
    return false;
  }
  auto cached_subject = Cast<SlicedString>(cached_subject_object);
  if (cached_subject->parent() != sliced_subject->parent()) return false;
  if (cached_subject->offset() != sliced_subject->offset()) return false;
  if (cached_subject->length() > sliced_subject->length()) return false;
  *number_of_matches_out = Smi::ToInt(cache->get(kNumberOfMatchesIndex));
  *last_match_index_out = Smi::ToInt(cache->get(kLastMatchIndexIndex));
  return true;
}
References Clear(), DCHECK_EQ, v8::internal::Isolate::heap(), v8::internal::InstanceTypeChecker::IsSlicedString(), kLastMatchIndexIndex, kNumberOfMatchesIndex, kPatternIndex, kSize, kSubjectIndex, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Smi::ToInt().
Referenced by v8::internal::RUNTIME_FUNCTION().
TryInsert()
void v8::internal::RegExpResultsCache_MatchGlobalAtom::TryInsert (Isolate * isolate, Tagged< String > subject, Tagged< String > pattern, int number_of_matches, int last_match_index) [static]
Definition at line 1403 of file regexp.cc.
                                                                         {
  DisallowGarbageCollection no_gc;
  DCHECK(Smi::IsValid(number_of_matches));
  DCHECK(Smi::IsValid(last_match_index));
  if (!IsSlicedString(subject)) return;
  Tagged<FixedArray> cache = isolate->heap()->regexp_match_global_atom_cache();
  DCHECK_EQ(cache->length(), kSize);
  cache->set(kSubjectIndex, subject);
  cache->set(kPatternIndex, pattern);
  cache->set(kNumberOfMatchesIndex, Smi::FromInt(number_of_matches));
  cache->set(kLastMatchIndexIndex, Smi::FromInt(last_match_index));
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Smi::FromInt(), v8::internal::Isolate::heap(), v8::internal::InstanceTypeChecker::IsSlicedString(), v8::internal::Smi::IsValid(), kLastMatchIndexIndex, kNumberOfMatchesIndex, kPatternIndex, kSize, kSubjectIndex, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::RUNTIME_FUNCTION().
Member Data Documentation
kEntrySize
constexpr int v8::internal::RegExpResultsCache_MatchGlobalAtom::kEntrySize = 4 [static], [constexpr], [private]
Definition at line 281 of file regexp.h.
kLastMatchIndexIndex
constexpr int v8::internal::RegExpResultsCache_MatchGlobalAtom::kLastMatchIndexIndex = 3 [static], [constexpr], [private]
Definition at line 280 of file regexp.h.
Referenced by TryGet(), and TryInsert().
kNumberOfMatchesIndex
constexpr int v8::internal::RegExpResultsCache_MatchGlobalAtom::kNumberOfMatchesIndex = 2 [static], [constexpr], [private]
Definition at line 279 of file regexp.h.
Referenced by TryGet(), and TryInsert().
kPatternIndex
constexpr int v8::internal::RegExpResultsCache_MatchGlobalAtom::kPatternIndex = 1 [static], [constexpr], [private]
Definition at line 278 of file regexp.h.
Referenced by TryGet(), and TryInsert().
kSize
constexpr int v8::internal::RegExpResultsCache_MatchGlobalAtom::kSize = kEntrySize [static], [constexpr]
Definition at line 284 of file regexp.h.
Referenced by Clear(), v8::internal::Heap::CreateInitialMutableObjects(), TryGet(), and TryInsert().
kSubjectIndex
constexpr int v8::internal::RegExpResultsCache_MatchGlobalAtom::kSubjectIndex = 0 [static], [constexpr], [private]
Definition at line 277 of file regexp.h.
Referenced by TryGet(), and TryInsert().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp.h
/mnt/V8SourceCode/src/regexp/regexp.cc