v8::internal::KeyedStoreGenericAssembler Class Reference
Public Member Functions
KeyedStoreGenericAssembler (compiler::CodeAssemblerState *state, StoreMode mode)
void KeyedStoreGeneric ()
void KeyedStoreMegamorphic ()
void StoreIC_NoFeedback ()
void StoreProperty (TNode< Context > context, TNode< JSReceiver > receiver, TNode< BoolT > is_simple_receiver, TNode< Name > unique_name, TNode< Object > value, LanguageMode language_mode)
void StoreProperty (TNode< Context > context, TNode< JSAny > receiver, TNode< Object > key, TNode< Object > value, LanguageMode language_mode)
Private Types
enum UpdateLength { kDontChangeLength
, kIncrementLengthByOne
, kBumpLengthWithGap
 }
enum UseStubCache { kUseStubCache
, kDontUseStubCache
 }
Private Member Functions
void KeyedStoreGeneric (TNode< Context > context, TNode< JSAny > receiver, TNode< Object > key, TNode< Object > value, Maybe< LanguageMode > language_mode, UseStubCache use_stub_cache=kDontUseStubCache, TNode< TaggedIndex > slot={}, TNode< HeapObject > maybe_vector={})
void EmitGenericElementStore (TNode< JSObject > receiver, TNode< Map > receiver_map, TNode< Uint16T > instance_type, TNode< IntPtrT > index, TNode< Object > value, TNode< Context > context, Label *slow)
void EmitGenericPropertyStore (TNode< JSReceiver > receiver, TNode< Map > receiver_map, TNode< Uint16T > instance_type, const StoreICParameters *p, ExitPoint *exit_point, Label *slow, Maybe< LanguageMode > maybe_language_mode, UseStubCache use_stub_cache)
void EmitGenericPropertyStore (TNode< JSReceiver > receiver, TNode< Map > receiver_map, TNode< Uint16T > instance_type, const StoreICParameters *p, Label *slow)
void BranchIfPrototypesMayHaveReadOnlyElements (TNode< Map > receiver_map, Label *maybe_read_only_elements, Label *only_fast_writable_elements)
void TryRewriteElements (TNode< JSObject > receiver, TNode< Map > receiver_map, TNode< FixedArrayBase > elements, TNode< NativeContext > native_context, ElementsKind from_kind, ElementsKind to_kind, Label *bailout)
void StoreSharedArrayElement (TNode< Context > context, TNode< FixedArrayBase > elements, TNode< IntPtrT > index, TNode< Object > value)
void StoreElementWithCapacity (TNode< JSObject > receiver, TNode< Map > receiver_map, TNode< FixedArrayBase > elements, TNode< Word32T > elements_kind, TNode< IntPtrT > index, TNode< Object > value, TNode< Context > context, Label *slow, UpdateLength update_length)
void MaybeUpdateLengthAndReturn (TNode< JSObject > receiver, TNode< IntPtrT > index, TNode< Object > value, UpdateLength update_length)
void TryChangeToHoleyMapHelper (TNode< JSObject > receiver, TNode< Map > receiver_map, TNode< NativeContext > native_context, ElementsKind packed_kind, ElementsKind holey_kind, Label *done, Label *map_mismatch, Label *bailout)
void TryChangeToHoleyMap (TNode< JSObject > receiver, TNode< Map > receiver_map, TNode< Word32T > current_elements_kind, TNode< Context > context, ElementsKind packed_kind, Label *bailout)
void TryChangeToHoleyMapMulti (TNode< JSObject > receiver, TNode< Map > receiver_map, TNode< Word32T > current_elements_kind, TNode< Context > context, ElementsKind packed_kind, ElementsKind packed_kind_2, Label *bailout)
void LookupPropertyOnPrototypeChain (TNode< Map > receiver_map, TNode< Name > name, Label *accessor, TVariable< Object > *var_accessor_pair, TVariable< HeapObject > *var_accessor_holder, Label *readonly, Label *bailout)
TNode< Map > FindCandidateStoreICTransitionMapHandler (TNode< Map > map, TNode< Name > name, Label *slow)
bool IsSet () const
bool IsDefineKeyedOwnInLiteral () const
bool IsDefineNamedOwn () const
bool IsDefineKeyedOwn () const
bool IsAnyDefineOwn () const
bool ShouldCheckPrototype () const
bool ShouldReconfigureExisting () const
bool ShouldCallSetter () const
bool ShouldCheckPrototypeValidity () const
Private Attributes
StoreMode mode_
Additional Inherited Members
Detailed Description
Definition at line 54 of file keyed-store-generic.cc.
Member Enumeration Documentation
UpdateLength
enum v8::internal::KeyedStoreGenericAssembler::UpdateLength [private]
Enumerator
kDontChangeLength
kIncrementLengthByOne
kBumpLengthWithGap
Definition at line 83 of file keyed-store-generic.cc.
                    {
    kDontChangeLength,
    kIncrementLengthByOne,
    kBumpLengthWithGap
  };
UseStubCache
enum v8::internal::KeyedStoreGenericAssembler::UseStubCache [private]
Enumerator
kUseStubCache
kDontUseStubCache
Definition at line 89 of file keyed-store-generic.cc.
{ kUseStubCache, kDontUseStubCache };
Constructor & Destructor Documentation
KeyedStoreGenericAssembler()
v8::internal::KeyedStoreGenericAssembler::KeyedStoreGenericAssembler (compiler::CodeAssemblerState * state, StoreMode mode) [inline], [explicit]
Definition at line 56 of file keyed-store-generic.cc.
      : AccessorAssembler(state), mode_(mode) {}
Member Function Documentation
BranchIfPrototypesMayHaveReadOnlyElements()
void v8::internal::KeyedStoreGenericAssembler::BranchIfPrototypesMayHaveReadOnlyElements (TNode< Map > receiver_map, Label * maybe_read_only_elements, Label * only_fast_writable_elements) [private]
Definition at line 267 of file keyed-store-generic.cc.
                                        {
  TVARIABLE(Map, var_map);
  var_map = receiver_map;
  Label loop_body(this, &var_map);
  Goto(&loop_body);
  BIND(&loop_body);
  {
    TNode<Map> map = var_map.value();
    TNode<HeapObject> prototype = LoadMapPrototype(map);
    GotoIf(IsNull(prototype), only_fast_writable_elements);
    TNode<Map> prototype_map = LoadMap(prototype);
    var_map = prototype_map;
    TNode<Uint16T> instance_type = LoadMapInstanceType(prototype_map);
    GotoIf(IsCustomElementsReceiverInstanceType(instance_type),
           maybe_read_only_elements);
    TNode<Int32T> elements_kind = LoadMapElementsKind(prototype_map);
    GotoIf(IsFastOrNonExtensibleOrSealedElementsKind(elements_kind),
           &loop_body);
    GotoIf(Word32Equal(elements_kind, Int32Constant(NO_ELEMENTS)), &loop_body);
    Goto(maybe_read_only_elements);
  }
}
References v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::CodeStubAssembler::IsCustomElementsReceiverInstanceType(), v8::internal::CodeStubAssembler::IsFastOrNonExtensibleOrSealedElementsKind(), v8::internal::IsNull(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapElementsKind(), v8::internal::CodeStubAssembler::LoadMapInstanceType(), v8::internal::CodeStubAssembler::LoadMapPrototype(), v8::internal::NO_ELEMENTS, v8::internal::prototype, and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by StoreElementWithCapacity().
EmitGenericElementStore()
void v8::internal::KeyedStoreGenericAssembler::EmitGenericElementStore (TNode< JSObject > receiver, TNode< Map > receiver_map, TNode< Uint16T > instance_type, TNode< IntPtrT > index, TNode< Object > value, TNode< Context > context, Label * slow) [private]
Definition at line 663 of file keyed-store-generic.cc.
                                         {
  Label if_fast(this), if_in_bounds(this), if_increment_length_by_one(this),
      if_bump_length_with_gap(this), if_grow(this), if_nonfast(this),
      if_typed_array(this), if_dictionary(this), if_shared_array(this);
  TNode<FixedArrayBase> elements = LoadElements(receiver);
  TNode<Int32T> elements_kind = LoadMapElementsKind(receiver_map);
  Branch(IsFastElementsKind(elements_kind), &if_fast, &if_nonfast);
  BIND(&if_fast);
  Label if_array(this);
  GotoIf(IsJSArrayInstanceType(instance_type), &if_array);
  {
    TNode<IntPtrT> capacity = LoadAndUntagFixedArrayBaseLength(elements);
    Branch(UintPtrLessThan(index, capacity), &if_in_bounds, &if_grow);
  }
  BIND(&if_array);
  {
    TNode<IntPtrT> length =
        PositiveSmiUntag(LoadFastJSArrayLength(CAST(receiver)));
    GotoIf(UintPtrLessThan(index, length), &if_in_bounds);
    TNode<IntPtrT> capacity = LoadAndUntagFixedArrayBaseLength(elements);
    GotoIf(UintPtrGreaterThanOrEqual(index, capacity), &if_grow);
    Branch(WordEqual(index, length), &if_increment_length_by_one,
           &if_bump_length_with_gap);
  }
  BIND(&if_in_bounds);
  {
    StoreElementWithCapacity(receiver, receiver_map, elements, elements_kind,
                             index, value, context, slow, kDontChangeLength);
  }
  BIND(&if_increment_length_by_one);
  {
    StoreElementWithCapacity(receiver, receiver_map, elements, elements_kind,
                             index, value, context, slow,
                             kIncrementLengthByOne);
  }
  BIND(&if_bump_length_with_gap);
  {
    StoreElementWithCapacity(receiver, receiver_map, elements, elements_kind,
                             index, value, context, slow, kBumpLengthWithGap);
  }
  // Out-of-capacity accesses (index >= capacity) jump here. Additionally,
  // an ElementsKind transition might be necessary.
  // The index can also be negative or larger than kMaxElementIndex at this
  // point! Jump to the runtime in that case to convert it to a named property.
  BIND(&if_grow);
  {
    Comment("Grow backing store");
    // TODO(jkummerow): Support inline backing store growth.
    Goto(slow);
  }
  // Any ElementsKind > LAST_FAST_ELEMENTS_KIND jumps here for further
  // dispatch.
  BIND(&if_nonfast);
  {
    static_assert(LAST_ELEMENTS_KIND ==
                  LAST_RAB_GSAB_FIXED_TYPED_ARRAY_ELEMENTS_KIND);
    GotoIf(Int32GreaterThanOrEqual(
               elements_kind,
               Int32Constant(FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND)),
           &if_typed_array);
    GotoIf(Word32Equal(elements_kind, Int32Constant(DICTIONARY_ELEMENTS)),
           &if_dictionary);
    GotoIf(Word32Equal(elements_kind, Int32Constant(SHARED_ARRAY_ELEMENTS)),
           &if_shared_array);
    Goto(slow);
  }
  BIND(&if_dictionary);
  {
    Comment("Dictionary");
    // TODO(jkummerow): Support storing to dictionary elements.
    Goto(slow);
  }
  BIND(&if_typed_array);
  {
    Comment("Typed array");
    // TODO(jkummerow): Support typed arrays. Note: RAB / GSAB backed typed
    // arrays end up here too.
    Goto(slow);
  }
  BIND(&if_shared_array);
  {
    TNode<IntPtrT> length = LoadAndUntagFixedArrayBaseLength(elements);
    GotoIf(UintPtrGreaterThanOrEqual(index, length), slow);
    StoreSharedArrayElement(context, elements, index, value);
  }
}
References v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::compiler::CodeAssembler::Comment(), v8::internal::DICTIONARY_ELEMENTS, v8::internal::FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::index, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::CodeStubAssembler::IsFastElementsKind(), v8::internal::CodeStubAssembler::IsJSArrayInstanceType(), kBumpLengthWithGap, kDontChangeLength, kIncrementLengthByOne, v8::internal::LAST_ELEMENTS_KIND, v8::internal::LAST_RAB_GSAB_FIXED_TYPED_ARRAY_ELEMENTS_KIND, v8::internal::length, v8::internal::CodeStubAssembler::LoadAndUntagFixedArrayBaseLength(), v8::internal::CodeStubAssembler::LoadElements(), v8::internal::CodeStubAssembler::LoadFastJSArrayLength(), v8::internal::CodeStubAssembler::LoadMapElementsKind(), v8::internal::CodeStubAssembler::PositiveSmiUntag(), v8::internal::SHARED_ARRAY_ELEMENTS, StoreElementWithCapacity(), StoreSharedArrayElement(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan(), v8::internal::value, v8::internal::compiler::CodeAssembler::Word32Equal(), and v8::internal::compiler::CodeAssembler::WordEqual().
Referenced by KeyedStoreGeneric().
EmitGenericPropertyStore() [1/2]
void v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore (TNode< JSReceiver > receiver, TNode< Map > receiver_map, TNode< Uint16T > instance_type, const StoreICParameters * p, ExitPoint * exit_point, Label * slow, Maybe< LanguageMode > maybe_language_mode, UseStubCache use_stub_cache) [private]
Definition at line 922 of file keyed-store-generic.cc.
                                 {
  CSA_DCHECK(this, IsSimpleObjectMap(receiver_map));
  // TODO(rmcilroy) Type as Struct once we use a trimmed down
  // LoadAccessorFromFastObject instead of LoadPropertyFromFastObject.
  TVARIABLE(Object, var_accessor_pair);
  TVARIABLE(HeapObject, var_accessor_holder);
  Label fast_properties(this), dictionary_properties(this), accessor(this),
      readonly(this), try_stub_cache(this);
  TNode<Uint32T> bitfield3 = LoadMapBitField3(receiver_map);
  TNode<Name> name = CAST(p->name());
  Branch(IsSetWord32<Map::Bits3::IsDictionaryMapBit>(bitfield3),
         &dictionary_properties, &fast_properties);
  BIND(&fast_properties);
  {
    Comment("fast property store");
    TNode<DescriptorArray> descriptors = LoadMapDescriptors(receiver_map);
    Label descriptor_found(this), lookup_transition(this);
    TVARIABLE(IntPtrT, var_name_index);
    DescriptorLookup(name, descriptors, bitfield3,
                     IsAnyDefineOwn() ? slow : &descriptor_found,
                     &var_name_index, &lookup_transition);
    // When dealing with class fields defined with DefineKeyedOwnIC or
    // DefineNamedOwnIC, use the slow path to check the existing property.
    if (!IsAnyDefineOwn()) {
      BIND(&descriptor_found);
      {
        TNode<IntPtrT> name_index = var_name_index.value();
        TNode<Uint32T> details = LoadDetailsByKeyIndex(descriptors, name_index);
        Label data_property(this);
        JumpIfDataProperty(details, &data_property,
                           ShouldReconfigureExisting() ? nullptr : &readonly);
        if (ShouldCallSetter()) {
          // Accessor case.
          // TODO(jkummerow): Implement a trimmed-down
          // LoadAccessorFromFastObject.
          LoadPropertyFromFastObject(receiver, receiver_map, descriptors,
                                     name_index, details, &var_accessor_pair);
          var_accessor_holder = receiver;
          Goto(&accessor);
        } else {
          // Handle accessor to data property reconfiguration in runtime.
          Goto(slow);
        }
        BIND(&data_property);
        {
          Label shared(this);
          GotoIf(IsJSSharedStructInstanceType(instance_type), &shared);
          CheckForAssociatedProtector(name, slow);
          OverwriteExistingFastDataProperty(receiver, receiver_map, descriptors,
                                            name_index, details, p->value(),
                                            slow, false);
          exit_point->Return(p->value());
          BIND(&shared);
          {
            StoreJSSharedStructField(p->context(), receiver, receiver_map,
                                     descriptors, name_index, details,
                                     p->value());
            exit_point->Return(p->value());
          }
        }
      }
    }
    BIND(&lookup_transition);
    {
      Comment("lookup transition");
      CheckForAssociatedProtector(name, slow);
      DCHECK_IMPLIES(use_stub_cache == kUseStubCache, IsSet());
      Label* if_not_found =
          use_stub_cache == kUseStubCache ? &try_stub_cache : slow;
      TNode<Map> transition_map = FindCandidateStoreICTransitionMapHandler(
          receiver_map, name, if_not_found);
      // Validate the transition handler candidate and apply the transition.
      StoreTransitionMapFlags flags = kValidateTransitionHandler;
      if (ShouldCheckPrototypeValidity()) {
        flags = StoreTransitionMapFlags(flags | kCheckPrototypeValidity);
      }
      HandleStoreICTransitionMapHandlerCase(p, transition_map, slow, flags);
      exit_point->Return(p->value());
    }
  }
  BIND(&dictionary_properties);
  {
    Comment("dictionary property store");
    // We checked for LAST_CUSTOM_ELEMENTS_RECEIVER before, which rules out
    // seeing global objects here (which would need special handling).
    TVARIABLE(IntPtrT, var_name_index);
    Label dictionary_found(this, &var_name_index),
        not_found(this, &var_name_index);
    TNode<PropertyDictionary> properties = CAST(LoadSlowProperties(receiver));
    // When dealing with class fields defined with DefineKeyedOwnIC or
    // DefineNamedOwnIC, use the slow path to check the existing property.
    NameDictionaryLookup<PropertyDictionary>(
        properties, name, IsAnyDefineOwn() ? slow : &dictionary_found,
        &var_name_index, &not_found, kFindExistingOrInsertionIndex);
    if (!IsAnyDefineOwn()) {
      BIND(&dictionary_found);
      {
        Label check_const(this), overwrite(this), done(this);
        TNode<Uint32T> details =
            LoadDetailsByKeyIndex(properties, var_name_index.value());
        JumpIfDataProperty(details, &check_const,
                           ShouldReconfigureExisting() ? nullptr : &readonly);
        if (ShouldCallSetter()) {
          // Accessor case.
          var_accessor_pair =
              LoadValueByKeyIndex(properties, var_name_index.value());
          var_accessor_holder = receiver;
          Goto(&accessor);
        } else {
          // We must reconfigure an accessor property to a data property
          // here, let the runtime take care of that.
          Goto(slow);
        }
        BIND(&check_const);
        {
          if (V8_DICT_PROPERTY_CONST_TRACKING_BOOL) {
            GotoIfNot(IsPropertyDetailsConst(details), &overwrite);
            TNode<Object> prev_value =
                LoadValueByKeyIndex(properties, var_name_index.value());
            Branch(TaggedEqual(prev_value, p->value()), &done, slow);
          } else {
            Goto(&overwrite);
          }
        }
        BIND(&overwrite);
        {
          CheckForAssociatedProtector(name, slow);
          StoreValueByKeyIndex<PropertyDictionary>(
              properties, var_name_index.value(), p->value());
          Goto(&done);
        }
        BIND(&done);
        exit_point->Return(p->value());
      }
    }
    BIND(&not_found);
    {
      // TODO(jkummerow): Also add support to correctly handle integer exotic
      // cases for typed arrays and remove this check here.
      GotoIf(IsJSTypedArrayMap(receiver_map), slow);
      CheckForAssociatedProtector(name, slow);
      Label extensible(this), is_private_symbol(this);
      GotoIf(IsPrivateSymbol(name), &is_private_symbol);
      Branch(IsSetWord32<Map::Bits3::IsExtensibleBit>(bitfield3), &extensible,
             slow);
      BIND(&is_private_symbol);
      {
        CSA_DCHECK(this, IsPrivateSymbol(name));
        // For private names, we miss to the runtime which will throw.
        // For private symbols, we extend and store an own property.
        Branch(IsPrivateName(CAST(name)), slow, &extensible);
      }
      BIND(&extensible);
      if (ShouldCheckPrototype()) {
        DCHECK(ShouldCallSetter());
        LookupPropertyOnPrototypeChain(
            receiver_map, name, &accessor, &var_accessor_pair,
            &var_accessor_holder,
            ShouldReconfigureExisting() ? nullptr : &readonly, slow);
      }
      Label add_dictionary_property_slow(this);
      InvalidateValidityCellIfPrototype(receiver_map, bitfield3);
      UpdateMayHaveInterestingProperty(properties, name);
      AddToDictionary<PropertyDictionary>(properties, name, p->value(),
                                          &add_dictionary_property_slow,
                                          var_name_index.value());
      exit_point->Return(p->value());
      BIND(&add_dictionary_property_slow);
      exit_point->ReturnCallRuntime(Runtime::kAddDictionaryProperty,
                                    p->context(), p->receiver(), name,
                                    p->value());
    }
  }
  if (ShouldCallSetter()) {
    BIND(&accessor);
    {
      Label not_callable(this);
      TNode<HeapObject> accessor_pair = CAST(var_accessor_pair.value());
      GotoIf(IsAccessorInfo(accessor_pair), slow);
      CSA_DCHECK(this, IsAccessorPair(accessor_pair));
      TNode<HeapObject> setter =
          CAST(LoadAccessorPairSetter(CAST(accessor_pair)));
      TNode<Map> setter_map = LoadMap(setter);
      // FunctionTemplateInfo setters are not supported yet.
      GotoIf(IsFunctionTemplateInfoMap(setter_map), slow);
      GotoIfNot(IsCallableMap(setter_map), &not_callable);
      Call(p->context(), setter, receiver, p->value());
      exit_point->Return(p->value());
      BIND(&not_callable);
      {
        LanguageMode language_mode;
        if (maybe_language_mode.To(&language_mode)) {
          if (language_mode == LanguageMode::kStrict) {
            exit_point->ReturnCallRuntime(
                Runtime::kThrowTypeError, p->context(),
                SmiConstant(MessageTemplate::kNoSetterInCallback), name,
                var_accessor_holder.value());
          } else {
            exit_point->Return(p->value());
          }
        } else {
          CallRuntime(Runtime::kThrowTypeErrorIfStrict, p->context(),
                      SmiConstant(MessageTemplate::kNoSetterInCallback), name,
                      var_accessor_holder.value());
          exit_point->Return(p->value());
        }
      }
    }
  }
  if (!ShouldReconfigureExisting() && !IsAnyDefineOwn()) {
    BIND(&readonly);
    {
      LanguageMode language_mode;
      if (maybe_language_mode.To(&language_mode)) {
        if (language_mode == LanguageMode::kStrict) {
          TNode<String> type = Typeof(p->receiver());
          ThrowTypeError(p->context(), MessageTemplate::kStrictReadOnlyProperty,
                         name, type, p->receiver());
        } else {
          exit_point->Return(p->value());
        }
      } else {
        CallRuntime(Runtime::kThrowTypeErrorIfStrict, p->context(),
                    SmiConstant(MessageTemplate::kStrictReadOnlyProperty), name,
                    Typeof(p->receiver()), p->receiver());
        exit_point->Return(p->value());
      }
    }
  }
  if (use_stub_cache == kUseStubCache) {
    DCHECK(IsSet());
    BIND(&try_stub_cache);
    // Do megamorphic cache lookup only for Api objects where it definitely
    // pays off.
    GotoIfNot(IsJSApiObjectInstanceType(instance_type), slow);
    Comment("stub cache probe");
    TVARIABLE(MaybeObject, var_handler);
    Label found_handler(this, &var_handler), stub_cache_miss(this);
    TryProbeStubCache(p->stub_cache(isolate()), receiver, name, &found_handler,
                      &var_handler, &stub_cache_miss);
    BIND(&found_handler);
    {
      Comment("KeyedStoreGeneric found handler");
      HandleStoreICHandlerCase(p, var_handler.value(), &stub_cache_miss,
                               ICMode::kNonGlobalIC);
    }
    BIND(&stub_cache_miss);
    {
      Comment("KeyedStoreGeneric_miss");
      TailCallRuntime(Runtime::kKeyedStoreIC_Miss, p->context(), p->value(),
                      p->slot(), p->vector(), p->receiver(), name);
    }
  }
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::CodeStubAssembler::Call(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::CodeStubAssembler::CheckForAssociatedProtector(), v8::internal::compiler::CodeAssembler::Comment(), v8::internal::AccessorAssembler::StoreICParameters::context(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::CodeStubAssembler::DescriptorLookup(), FindCandidateStoreICTransitionMapHandler(), v8::internal::flags, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase(), v8::internal::AccessorAssembler::InvalidateValidityCellIfPrototype(), IsAnyDefineOwn(), v8::internal::CodeStubAssembler::IsCallableMap(), v8::internal::CodeStubAssembler::IsJSApiObjectInstanceType(), v8::internal::CodeStubAssembler::IsJSSharedStructInstanceType(), v8::internal::CodeStubAssembler::IsJSTypedArrayMap(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::CodeStubAssembler::IsPrivateName(), v8::internal::IsPrivateSymbol(), v8::internal::AccessorAssembler::IsPropertyDetailsConst(), IsSet(), v8::internal::AccessorAssembler::JumpIfDataProperty(), v8::internal::AccessorAssembler::kCheckPrototypeValidity, v8::internal::CodeStubAssembler::kFindExistingOrInsertionIndex, v8::internal::AccessorAssembler::kNonGlobalIC, v8::internal::kStrict, kUseStubCache, v8::internal::AccessorAssembler::kValidateTransitionHandler, v8::internal::CodeStubAssembler::LoadAccessorPairSetter(), v8::internal::CodeStubAssembler::LoadDetailsByKeyIndex(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapBitField3(), v8::internal::CodeStubAssembler::LoadMapDescriptors(), v8::internal::CodeStubAssembler::LoadPropertyFromFastObject(), v8::internal::CodeStubAssembler::LoadSlowProperties(), v8::internal::CodeStubAssembler::LoadValueByKeyIndex(), LookupPropertyOnPrototypeChain(), v8::internal::AccessorAssembler::StoreICParameters::name(), v8::internal::name, v8::internal::AccessorAssembler::OverwriteExistingFastDataProperty(), v8::internal::AccessorAssembler::StoreICParameters::receiver(), v8::internal::ExitPoint::Return(), v8::internal::ExitPoint::ReturnCallRuntime(), v8::internal::setter, ShouldCallSetter(), ShouldCheckPrototype(), ShouldCheckPrototypeValidity(), ShouldReconfigureExisting(), v8::internal::AccessorAssembler::StoreICParameters::slot(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::AccessorAssembler::StoreJSSharedStructField(), v8::internal::AccessorAssembler::StoreICParameters::stub_cache(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::compiler::CodeAssembler::TailCallRuntime(), v8::internal::CodeStubAssembler::ThrowTypeError(), v8::Maybe< T >::To(), v8::internal::AccessorAssembler::TryProbeStubCache(), v8::internal::tracing::type, v8::internal::CodeStubAssembler::Typeof(), v8::internal::AccessorAssembler::UpdateMayHaveInterestingProperty(), V8_DICT_PROPERTY_CONST_TRACKING_BOOL, v8::internal::AccessorAssembler::StoreICParameters::value(), and v8::internal::AccessorAssembler::StoreICParameters::vector().
Referenced by EmitGenericPropertyStore(), KeyedStoreGeneric(), StoreIC_NoFeedback(), and StoreProperty().
EmitGenericPropertyStore() [2/2]
void v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore (TNode< JSReceiver > receiver, TNode< Map > receiver_map, TNode< Uint16T > instance_type, const StoreICParameters * p, Label * slow) [inline], [private]
Definition at line 116 of file keyed-store-generic.cc.
                                                                         {
    ExitPoint direct_exit(this);
    EmitGenericPropertyStore(receiver, receiver_map, instance_type, p,
                             &direct_exit, slow, Nothing<LanguageMode>(),
                             kDontUseStubCache);
  }
References EmitGenericPropertyStore(), and kDontUseStubCache.
FindCandidateStoreICTransitionMapHandler()
TNode< Map > v8::internal::KeyedStoreGenericAssembler::FindCandidateStoreICTransitionMapHandler (TNode< Map > map, TNode< Name > name, Label * slow) [private]
Definition at line 857 of file keyed-store-generic.cc.
                                                   {
  TVARIABLE(Map, var_transition_map);
  Label simple_transition(this), transition_array(this),
      found_handler_candidate(this);
  TNode<MaybeObject> maybe_handler =
      LoadMaybeWeakObjectField(map, Map::kTransitionsOrPrototypeInfoOffset);
  // Smi -> slow,
  // Cleared weak reference -> slow
  // weak reference -> simple_transition
  // strong reference -> transition_array
  TVARIABLE(Object, var_transition_map_or_array);
  DispatchMaybeObject(maybe_handler, slow, slow, &simple_transition,
                      &transition_array, &var_transition_map_or_array);
  BIND(&simple_transition);
  {
    var_transition_map = CAST(var_transition_map_or_array.value());
    Goto(&found_handler_candidate);
  }
  BIND(&transition_array);
  {
    TNode<Map> maybe_handler_map =
        LoadMap(CAST(var_transition_map_or_array.value()));
    GotoIfNot(IsTransitionArrayMap(maybe_handler_map), slow);
    TVARIABLE(IntPtrT, var_name_index);
    Label if_found_candidate(this);
    TNode<TransitionArray> transitions =
        CAST(var_transition_map_or_array.value());
    TransitionLookup(name, transitions, &if_found_candidate, &var_name_index,
                     slow);
    BIND(&if_found_candidate);
    {
      // Given that
      // 1) transitions with the same name are ordered in the transition
      // array by PropertyKind and then by PropertyAttributes values,
      // 2) kData < kAccessor,
      // 3) NONE == 0,
      // 4) properties with private symbol names are guaranteed to be
      // non-enumerable (so DONT_ENUM bit in attributes is always set),
      // the resulting map of transitioning store if it exists in the
      // transition array is expected to be the first among the transitions
      // with the same name.
      // See TransitionArray::CompareDetails() for details.
      static_assert(static_cast<int>(PropertyKind::kData) == 0);
      static_assert(NONE == 0);
      const int kKeyToTargetOffset = (TransitionArray::kEntryTargetIndex -
                                      TransitionArray::kEntryKeyIndex) *
                                     kTaggedSize;
      var_transition_map = CAST(GetHeapObjectAssumeWeak(
          LoadArrayElement(transitions, OFFSET_OF_DATA_START(WeakFixedArray),
                           var_name_index.value(), kKeyToTargetOffset)));
      Goto(&found_handler_candidate);
    }
  }
  BIND(&found_handler_candidate);
  return var_transition_map.value();
}
References CAST, v8::internal::CodeStubAssembler::DispatchMaybeObject(), v8::internal::CodeStubAssembler::GetHeapObjectAssumeWeak(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::kData, v8::internal::TransitionArray::kEntryKeyIndex, v8::internal::TransitionArray::kEntryTargetIndex, v8::internal::kTaggedSize, v8::internal::CodeStubAssembler::LoadArrayElement(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMaybeWeakObjectField(), v8::internal::name, v8::internal::NONE, OFFSET_OF_DATA_START, and v8::internal::CodeStubAssembler::TransitionLookup().
Referenced by EmitGenericPropertyStore().
IsAnyDefineOwn()
bool v8::internal::KeyedStoreGenericAssembler::IsAnyDefineOwn () const [inline], [private]
Definition at line 185 of file keyed-store-generic.cc.
                              {
    return IsDefineNamedOwn() || IsDefineKeyedOwn();
  }
References IsDefineKeyedOwn(), and IsDefineNamedOwn().
Referenced by EmitGenericPropertyStore().
IsDefineKeyedOwn()
bool v8::internal::KeyedStoreGenericAssembler::IsDefineKeyedOwn () const [inline], [private]
Definition at line 184 of file keyed-store-generic.cc.
{ return mode_ == StoreMode::kDefineKeyedOwn; }
References v8::internal::kDefineKeyedOwn, and mode_.
Referenced by IsAnyDefineOwn(), KeyedStoreGeneric(), and ShouldCheckPrototypeValidity().
IsDefineKeyedOwnInLiteral()
bool v8::internal::KeyedStoreGenericAssembler::IsDefineKeyedOwnInLiteral () const [inline], [private]
Definition at line 180 of file keyed-store-generic.cc.
                                         {
    return mode_ == StoreMode::kDefineKeyedOwnInLiteral;
  }
References v8::internal::kDefineKeyedOwnInLiteral, and mode_.
Referenced by KeyedStoreGeneric(), ShouldCheckPrototypeValidity(), ShouldReconfigureExisting(), StoreElementWithCapacity(), and StoreProperty().
IsDefineNamedOwn()
bool v8::internal::KeyedStoreGenericAssembler::IsDefineNamedOwn () const [inline], [private]
Definition at line 183 of file keyed-store-generic.cc.
{ return mode_ == StoreMode::kDefineNamedOwn; }
References v8::internal::kDefineNamedOwn, and mode_.
Referenced by IsAnyDefineOwn(), KeyedStoreGeneric(), ShouldCheckPrototypeValidity(), and StoreIC_NoFeedback().
IsSet()
bool v8::internal::KeyedStoreGenericAssembler::IsSet () const [inline], [private]
Definition at line 179 of file keyed-store-generic.cc.
{ return mode_ == StoreMode::kSet; }
References v8::internal::kSet, and mode_.
Referenced by EmitGenericPropertyStore(), KeyedStoreGeneric(), KeyedStoreMegamorphic(), ShouldCallSetter(), ShouldCheckPrototype(), and ShouldCheckPrototypeValidity().
KeyedStoreGeneric() [1/2]
void v8::internal::KeyedStoreGenericAssembler::KeyedStoreGeneric ()
Definition at line 1288 of file keyed-store-generic.cc.
                                                   {
  using Descriptor = StoreNoFeedbackDescriptor;
  auto receiver = Parameter<JSAny>(Descriptor::kReceiver);
  auto name = Parameter<Object>(Descriptor::kName);
  auto value = Parameter<Object>(Descriptor::kValue);
  auto context = Parameter<Context>(Descriptor::kContext);
  KeyedStoreGeneric(context, receiver, name, value, Nothing<LanguageMode>());
}
References v8::internal::anonymous_namespace{ic.cc}::kName, v8::internal::name, and v8::internal::value.
Referenced by v8::internal::KeyedStoreGenericGenerator::Generate(), v8::internal::DefineKeyedOwnGenericGenerator::Generate(), KeyedStoreMegamorphic(), and StoreProperty().
KeyedStoreGeneric() [2/2]
void v8::internal::KeyedStoreGenericAssembler::KeyedStoreGeneric (TNode< Context > context, TNode< JSAny > receiver, TNode< Object > key, TNode< Object > value, Maybe< LanguageMode > language_mode, UseStubCache use_stub_cache = kDontUseStubCache, TNode< TaggedIndex > slot = {}, TNode< HeapObject > maybe_vector = {}) [private]
Definition at line 1213 of file keyed-store-generic.cc.
                                    {
  DCHECK_IMPLIES(use_stub_cache == kUseStubCache, IsSet());
  TVARIABLE(IntPtrT, var_index);
  TVARIABLE(Name, var_unique);
  Label if_index(this, &var_index), if_unique_name(this),
      not_internalized(this), slow(this);
  GotoIf(TaggedIsSmi(receiver_maybe_smi), &slow);
  TNode<JSAnyNotSmi> receiver = CAST(receiver_maybe_smi);
  TNode<Map> receiver_map = LoadMap(receiver);
  TNode<Uint16T> instance_type = LoadMapInstanceType(receiver_map);
  // Receivers requiring non-standard element accesses (interceptors, access
  // checks, strings and string wrappers, proxies) are handled in the runtime.
  GotoIf(IsCustomElementsReceiverInstanceType(instance_type), &slow);
  TryToName(key, &if_index, &var_index, &if_unique_name, &var_unique, &slow,
            &not_internalized);
  BIND(&if_index);
  {
    Comment("integer index");
    EmitGenericElementStore(CAST(receiver), receiver_map, instance_type,
                            var_index.value(), value, context, &slow);
  }
  BIND(&if_unique_name);
  {
    Comment("key is unique name");
    StoreICParameters p(context, receiver, var_unique.value(), value,
                        std::nullopt, slot, maybe_vector,
                        StoreICMode::kDefault);
    ExitPoint direct_exit(this);
    EmitGenericPropertyStore(CAST(receiver), receiver_map, instance_type, &p,
                             &direct_exit, &slow, language_mode,
                             use_stub_cache);
  }
  BIND(&not_internalized);
  {
    if (v8_flags.internalize_on_the_fly) {
      TryInternalizeString(CAST(key), &if_index, &var_index, &if_unique_name,
                           &var_unique, &slow, &slow);
    } else {
      Goto(&slow);
    }
  }
  BIND(&slow);
  {
    if (IsSet() || IsDefineNamedOwn()) {
      // The DefineNamedOwnIC hacky reuse should never reach here.
      CSA_DCHECK(this, BoolConstant(!IsDefineNamedOwn()));
      Comment("KeyedStoreGeneric_slow");
      TailCallRuntime(Runtime::kSetKeyedProperty, context, receiver, key,
                      value);
    } else if (IsDefineKeyedOwn()) {
      TailCallRuntime(Runtime::kDefineObjectOwnProperty, context, receiver, key,
                      value);
    } else {
      DCHECK(IsDefineKeyedOwnInLiteral());
      TNode<Smi> flags =
          SmiConstant(DefineKeyedOwnPropertyInLiteralFlag::kNoFlags);
      TNode<TaggedIndex> invalid_slot =
          TaggedIndexConstant(FeedbackSlot::Invalid().ToInt());
      TailCallRuntime(Runtime::kDefineKeyedOwnPropertyInLiteral, context,
                      receiver, key, value, flags, UndefinedConstant(),
                      invalid_slot);
    }
  }
}
References v8::internal::compiler::CodeAssembler::BoolConstant(), CAST, v8::internal::compiler::CodeAssembler::Comment(), v8::internal::DCHECK(), DCHECK_IMPLIES, EmitGenericElementStore(), EmitGenericPropertyStore(), v8::internal::flags, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::FeedbackSlot::Invalid(), v8::internal::CodeStubAssembler::IsCustomElementsReceiverInstanceType(), IsDefineKeyedOwn(), IsDefineKeyedOwnInLiteral(), IsDefineNamedOwn(), IsSet(), v8::internal::AccessorAssembler::kDefault, v8::internal::key, v8::internal::kNoFlags, kUseStubCache, v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapInstanceType(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::compiler::CodeAssembler::TaggedIndexConstant(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::compiler::CodeAssembler::TailCallRuntime(), v8::internal::anonymous_namespace{temporal-parser.cc}::ToInt(), v8::internal::CodeStubAssembler::TryInternalizeString(), v8::internal::CodeStubAssembler::TryToName(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), v8::internal::v8_flags, and v8::internal::value.
KeyedStoreMegamorphic()
void v8::internal::KeyedStoreGenericAssembler::KeyedStoreMegamorphic ()
Definition at line 1299 of file keyed-store-generic.cc.
                                                       {
  DCHECK(IsSet()); // Only [[Set]] handlers are stored in the stub cache.
  using Descriptor = StoreWithVectorDescriptor;
  auto receiver = Parameter<JSAny>(Descriptor::kReceiver);
  auto name = Parameter<Object>(Descriptor::kName);
  auto value = Parameter<Object>(Descriptor::kValue);
  auto context = Parameter<Context>(Descriptor::kContext);
  auto slot = Parameter<TaggedIndex>(Descriptor::kSlot);
  auto maybe_vector = Parameter<HeapObject>(Descriptor::kVector);
  KeyedStoreGeneric(context, receiver, name, value, Nothing<LanguageMode>(),
                    kUseStubCache, slot, maybe_vector);
}
References v8::internal::DCHECK(), IsSet(), KeyedStoreGeneric(), v8::internal::anonymous_namespace{ic.cc}::kName, kUseStubCache, v8::internal::name, and v8::internal::value.
Referenced by v8::internal::KeyedStoreMegamorphicGenerator::Generate().
LookupPropertyOnPrototypeChain()
void v8::internal::KeyedStoreGenericAssembler::LookupPropertyOnPrototypeChain (TNode< Map > receiver_map, TNode< Name > name, Label * accessor, TVariable< Object > * var_accessor_pair, TVariable< HeapObject > * var_accessor_holder, Label * readonly, Label * bailout) [private]
Definition at line 761 of file keyed-store-generic.cc.
                    {
  Label ok_to_write(this);
  TVARIABLE(HeapObject, var_holder);
  TVARIABLE(Map, var_holder_map);
  var_holder = LoadMapPrototype(receiver_map);
  var_holder_map = LoadMap(var_holder.value());
  Label loop(this, {&var_holder, &var_holder_map});
  Goto(&loop);
  BIND(&loop);
  {
    TNode<HeapObject> holder = var_holder.value();
    GotoIf(IsNull(holder), &ok_to_write);
    TNode<Map> holder_map = var_holder_map.value();
    TNode<Uint16T> instance_type = LoadMapInstanceType(holder_map);
    Label next_proto(this);
    {
      Label found(this), found_fast(this), found_dict(this), found_global(this);
      TVARIABLE(HeapObject, var_meta_storage);
      TVARIABLE(IntPtrT, var_entry);
      TryLookupProperty(holder, holder_map, instance_type, name, &found_fast,
                        &found_dict, &found_global, &var_meta_storage,
                        &var_entry, &next_proto, bailout);
      BIND(&found_fast);
      {
        TNode<DescriptorArray> descriptors = CAST(var_meta_storage.value());
        TNode<IntPtrT> name_index = var_entry.value();
        TNode<Uint32T> details = LoadDetailsByKeyIndex(descriptors, name_index);
        JumpIfDataProperty(details, &ok_to_write, readonly);
        // Accessor case.
        // TODO(jkummerow): Implement a trimmed-down
        // LoadAccessorFromFastObject.
        LoadPropertyFromFastObject(holder, holder_map, descriptors, name_index,
                                   details, var_accessor_pair);
        *var_accessor_holder = holder;
        Goto(accessor);
      }
      BIND(&found_dict);
      {
        TNode<PropertyDictionary> dictionary = CAST(var_meta_storage.value());
        TNode<IntPtrT> entry = var_entry.value();
        TNode<Uint32T> details = LoadDetailsByKeyIndex(dictionary, entry);
        JumpIfDataProperty(details, &ok_to_write, readonly);
        if (accessor != nullptr) {
          // Accessor case.
          *var_accessor_pair = LoadValueByKeyIndex(dictionary, entry);
          *var_accessor_holder = holder;
          Goto(accessor);
        } else {
          Goto(&ok_to_write);
        }
      }
      BIND(&found_global);
      {
        TNode<GlobalDictionary> dictionary = CAST(var_meta_storage.value());
        TNode<IntPtrT> entry = var_entry.value();
        TNode<PropertyCell> property_cell =
            CAST(LoadValueByKeyIndex(dictionary, entry));
        TNode<Object> value =
            LoadObjectField(property_cell, PropertyCell::kValueOffset);
        GotoIf(TaggedEqual(value, TheHoleConstant()), &next_proto);
        TNode<Uint32T> details = Unsigned(LoadAndUntagToWord32ObjectField(
            property_cell, PropertyCell::kPropertyDetailsRawOffset));
        JumpIfDataProperty(details, &ok_to_write, readonly);
        if (accessor != nullptr) {
          // Accessor case.
          *var_accessor_pair = value;
          *var_accessor_holder = holder;
          Goto(accessor);
        } else {
          Goto(&ok_to_write);
        }
      }
    }
    BIND(&next_proto);
    // Bailout if it can be an integer indexed exotic case.
    GotoIf(IsJSTypedArrayInstanceType(instance_type), bailout);
    TNode<HeapObject> proto = LoadMapPrototype(holder_map);
    GotoIf(IsNull(proto), &ok_to_write);
    var_holder = proto;
    var_holder_map = LoadMap(proto);
    Goto(&loop);
  }
  BIND(&ok_to_write);
}
References CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::IsJSTypedArrayInstanceType(), v8::internal::IsNull(), v8::internal::AccessorAssembler::JumpIfDataProperty(), v8::internal::CodeStubAssembler::LoadAndUntagToWord32ObjectField(), v8::internal::CodeStubAssembler::LoadDetailsByKeyIndex(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapInstanceType(), v8::internal::CodeStubAssembler::LoadMapPrototype(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::CodeStubAssembler::LoadPropertyFromFastObject(), v8::internal::CodeStubAssembler::LoadValueByKeyIndex(), v8::internal::name, v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::CodeStubAssembler::TryLookupProperty(), v8::internal::compiler::CodeAssembler::Unsigned(), and v8::internal::value.
Referenced by EmitGenericPropertyStore().
MaybeUpdateLengthAndReturn()
void v8::internal::KeyedStoreGenericAssembler::MaybeUpdateLengthAndReturn (TNode< JSObject > receiver, TNode< IntPtrT > index, TNode< Object > value, UpdateLength update_length) [private]
Definition at line 391 of file keyed-store-generic.cc.
                                {
  if (update_length != kDontChangeLength) {
    TNode<Smi> new_length = SmiTag(Signed(IntPtrAdd(index, IntPtrConstant(1))));
    StoreObjectFieldNoWriteBarrier(receiver, JSArray::kLengthOffset,
                                   new_length);
  }
  Return(value);
}
References v8::internal::index, v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), kDontChangeLength, v8::internal::compiler::CodeAssembler::Return(), v8::internal::compiler::CodeAssembler::Signed(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), and v8::internal::value.
Referenced by StoreElementWithCapacity().
ShouldCallSetter()
bool v8::internal::KeyedStoreGenericAssembler::ShouldCallSetter () const [inline], [private]
Definition at line 191 of file keyed-store-generic.cc.
{ return IsSet(); }
References IsSet().
Referenced by EmitGenericPropertyStore().
ShouldCheckPrototype()
bool v8::internal::KeyedStoreGenericAssembler::ShouldCheckPrototype () const [inline], [private]
Definition at line 189 of file keyed-store-generic.cc.
{ return IsSet(); }
References IsSet().
Referenced by EmitGenericPropertyStore().
ShouldCheckPrototypeValidity()
bool v8::internal::KeyedStoreGenericAssembler::ShouldCheckPrototypeValidity () const [inline], [private]
Definition at line 192 of file keyed-store-generic.cc.
                                            {
    // We don't do this for "in-literal" stores, because it is impossible for
    // the target object to be a "prototype".
    // We don't need the prototype validity check for "own" stores, because
    // we don't care about the prototype chain.
    // Thus, we need the prototype check only for ordinary stores.
    DCHECK_IMPLIES(!IsSet(), IsDefineKeyedOwnInLiteral() ||
                                 IsDefineNamedOwn() || IsDefineKeyedOwn());
    return IsSet();
  }
References DCHECK_IMPLIES, IsDefineKeyedOwn(), IsDefineKeyedOwnInLiteral(), IsDefineNamedOwn(), and IsSet().
Referenced by EmitGenericPropertyStore().
ShouldReconfigureExisting()
bool v8::internal::KeyedStoreGenericAssembler::ShouldReconfigureExisting () const [inline], [private]
Definition at line 190 of file keyed-store-generic.cc.
{ return IsDefineKeyedOwnInLiteral(); }
References IsDefineKeyedOwnInLiteral().
Referenced by EmitGenericPropertyStore().
StoreElementWithCapacity()
void v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity (TNode< JSObject > receiver, TNode< Map > receiver_map, TNode< FixedArrayBase > elements, TNode< Word32T > elements_kind, TNode< IntPtrT > index, TNode< Object > value, TNode< Context > context, Label * slow, UpdateLength update_length) [private]
Definition at line 411 of file keyed-store-generic.cc.
                                             {
  if (update_length != kDontChangeLength) {
    CSA_DCHECK(this, IsJSArrayMap(receiver_map));
    // Check if the length property is writable. The fast check is only
    // supported for fast properties.
    GotoIf(IsDictionaryMap(receiver_map), slow);
    // The length property is non-configurable, so it's guaranteed to always
    // be the first property.
    TNode<DescriptorArray> descriptors = LoadMapDescriptors(receiver_map);
    TNode<Uint32T> details = LoadDetailsByDescriptorEntry(descriptors, 0);
    GotoIf(IsSetWord32(details, PropertyDetails::kAttributesReadOnlyMask),
           slow);
  }
  static_assert(OFFSET_OF_DATA_START(FixedArray) ==
                OFFSET_OF_DATA_START(FixedDoubleArray));
  const int kHeaderSize = OFFSET_OF_DATA_START(FixedArray) - kHeapObjectTag;
  Label check_double_elements(this), check_cow_elements(this);
  TNode<Map> elements_map = LoadMap(elements);
  GotoIf(IsNotFixedArrayMap(elements_map), &check_double_elements);
  // FixedArray backing store -> Smi or object elements.
  {
    TNode<IntPtrT> offset =
        ElementOffsetFromIndex(index, PACKED_ELEMENTS, kHeaderSize);
    if (!IsDefineKeyedOwnInLiteral()) {
      // Check if we're about to overwrite the hole. We can safely do that
      // only if there can be no setters on the prototype chain.
      // If we know that we're storing beyond the previous array length, we
      // can skip the hole check (and always assume the hole).
      {
        Label hole_check_passed(this);
        if (update_length == kDontChangeLength) {
          TNode<Object> element =
              CAST(Load(MachineType::AnyTagged(), elements, offset));
          GotoIf(IsNotTheHole(element), &hole_check_passed);
        }
        BranchIfPrototypesMayHaveReadOnlyElements(receiver_map, slow,
                                                  &hole_check_passed);
        BIND(&hole_check_passed);
      }
    }
    // Check if the value we're storing matches the elements_kind. Smis
    // can always be stored.
    {
      Label non_smi_value(this);
      GotoIfNot(TaggedIsSmi(value), &non_smi_value);
      // If we're about to introduce holes, ensure holey elements.
      if (update_length == kBumpLengthWithGap) {
        TryChangeToHoleyMapMulti(receiver, receiver_map, elements_kind, context,
                                 PACKED_SMI_ELEMENTS, PACKED_ELEMENTS, slow);
      }
      StoreNoWriteBarrier(MachineRepresentation::kTaggedSigned, elements,
                          offset, value);
      MaybeUpdateLengthAndReturn(receiver, index, value, update_length);
      BIND(&non_smi_value);
    }
    // Check if we already have object elements; just do the store if so.
    {
      Label must_transition(this);
      static_assert(PACKED_SMI_ELEMENTS == 0);
      static_assert(HOLEY_SMI_ELEMENTS == 1);
      GotoIf(Int32LessThanOrEqual(elements_kind,
                                  Int32Constant(HOLEY_SMI_ELEMENTS)),
             &must_transition);
      if (update_length == kBumpLengthWithGap) {
        TryChangeToHoleyMap(receiver, receiver_map, elements_kind, context,
                            PACKED_ELEMENTS, slow);
      }
      Store(elements, offset, value);
      MaybeUpdateLengthAndReturn(receiver, index, value, update_length);
      BIND(&must_transition);
    }
    // Transition to the required ElementsKind.
    {
      Label transition_to_double(this), transition_to_object(this);
      TNode<NativeContext> native_context = LoadNativeContext(context);
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      GotoIf(IsHeapNumber(CAST(value)), &transition_to_double);
      GotoIfNot(IsUndefined(value), &transition_to_object);
      {
        TryRewriteElements(receiver, receiver_map, elements, native_context,
                           PACKED_SMI_ELEMENTS, HOLEY_DOUBLE_ELEMENTS, slow);
        // Reload migrated elements.
        TNode<FixedArrayBase> double_elements = LoadElements(receiver);
        TNode<IntPtrT> double_offset =
            ElementOffsetFromIndex(index, PACKED_DOUBLE_ELEMENTS, kHeaderSize);
        // Make sure we do not store signalling NaNs into double arrays.
        if (Is64()) {
          StoreNoWriteBarrier(MachineRepresentation::kWord64, double_elements,
                              double_offset,
                              Uint64Constant(kUndefinedNanInt64));
        } else {
          static_assert(kUndefinedNanLower32 == kUndefinedNanUpper32);
          StoreNoWriteBarrier(MachineRepresentation::kWord32, double_elements,
                              double_offset,
                              Uint32Constant(kUndefinedNanLower32));
          StoreNoWriteBarrier(
              MachineRepresentation::kWord32, double_elements,
              IntPtrAdd(double_offset, IntPtrConstant(kInt32Size)),
              Uint32Constant(kUndefinedNanLower32));
        }
        MaybeUpdateLengthAndReturn(receiver, index, value, update_length);
      }
#else
      Branch(IsHeapNumber(CAST(value)), &transition_to_double,
             &transition_to_object);
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      BIND(&transition_to_double);
      {
        // If we're adding holes at the end, always transition to a holey
        // elements kind, otherwise try to remain packed.
        ElementsKind target_kind = update_length == kBumpLengthWithGap
                                       ? HOLEY_DOUBLE_ELEMENTS
                                       : PACKED_DOUBLE_ELEMENTS;
        TryRewriteElements(receiver, receiver_map, elements, native_context,
                           PACKED_SMI_ELEMENTS, target_kind, slow);
        // Reload migrated elements.
        TNode<FixedArrayBase> double_elements = LoadElements(receiver);
        TNode<IntPtrT> double_offset =
            ElementOffsetFromIndex(index, PACKED_DOUBLE_ELEMENTS, kHeaderSize);
        // Make sure we do not store signalling NaNs into double arrays.
        TNode<Float64T> double_value =
            Float64SilenceNaN(LoadHeapNumberValue(CAST(value)));
        StoreNoWriteBarrier(MachineRepresentation::kFloat64, double_elements,
                            double_offset, double_value);
        MaybeUpdateLengthAndReturn(receiver, index, value, update_length);
      }
      BIND(&transition_to_object);
      {
        // If we're adding holes at the end, always transition to a holey
        // elements kind, otherwise try to remain packed.
        ElementsKind target_kind = update_length == kBumpLengthWithGap
                                       ? HOLEY_ELEMENTS
                                       : PACKED_ELEMENTS;
        TryRewriteElements(receiver, receiver_map, elements, native_context,
                           PACKED_SMI_ELEMENTS, target_kind, slow);
        // The elements backing store didn't change, no reload necessary.
        CSA_DCHECK(this, TaggedEqual(elements, LoadElements(receiver)));
        Store(elements, offset, value);
        MaybeUpdateLengthAndReturn(receiver, index, value, update_length);
      }
    }
  }
  BIND(&check_double_elements);
  GotoIf(IsNotFixedDoubleArrayMap(elements_map), &check_cow_elements);
  // FixedDoubleArray backing store -> double elements.
  {
    TNode<IntPtrT> offset =
        ElementOffsetFromIndex(index, PACKED_DOUBLE_ELEMENTS, kHeaderSize);
    if (!IsDefineKeyedOwnInLiteral()) {
      // Check if we're about to overwrite the hole. We can safely do that
      // only if there can be no setters on the prototype chain.
      {
        Label hole_check_passed(this);
        // If we know that we're storing beyond the previous array length, we
        // can skip the hole check (and always assume the hole).
        if (update_length == kDontChangeLength) {
          Label found_hole(this);
          LoadDoubleWithUndefinedAndHoleCheck(elements, offset,
                                              &hole_check_passed, &found_hole,
                                              MachineType::None());
          Goto(&hole_check_passed);
          BIND(&found_hole);
        }
        BranchIfPrototypesMayHaveReadOnlyElements(receiver_map, slow,
                                                  &hole_check_passed);
        BIND(&hole_check_passed);
      }
    }
    // Try to store the value as a double.
    {
      Label non_number_value(this);
      Label undefined_value(this);
      TNode<Float64T> double_value = TryTaggedToFloat64(value,
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
                                                        &undefined_value,
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
                                                        &non_number_value);
      // Make sure we do not store signalling NaNs into double arrays.
      double_value = Float64SilenceNaN(double_value);
      // If we're about to introduce holes, ensure holey elements.
      if (update_length == kBumpLengthWithGap) {
        TryChangeToHoleyMap(receiver, receiver_map, elements_kind, context,
                            PACKED_DOUBLE_ELEMENTS, slow);
      }
      StoreNoWriteBarrier(MachineRepresentation::kFloat64, elements, offset,
                          double_value);
      MaybeUpdateLengthAndReturn(receiver, index, value, update_length);
      // Convert undefined to double value.
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      BIND(&undefined_value);
      // If we're about to introduce undefined, ensure holey elements.
      TryChangeToHoleyMap(receiver, receiver_map, elements_kind, context,
                          PACKED_DOUBLE_ELEMENTS, slow);
      if (Is64()) {
        StoreNoWriteBarrier(MachineRepresentation::kWord64, elements, offset,
                            Uint64Constant(kUndefinedNanInt64));
      } else {
        static_assert(kUndefinedNanLower32 == kUndefinedNanUpper32);
        StoreNoWriteBarrier(MachineRepresentation::kWord32, elements, offset,
                            Uint32Constant(kUndefinedNanLower32));
        StoreNoWriteBarrier(MachineRepresentation::kWord32, elements,
                            IntPtrAdd(offset, IntPtrConstant(kInt32Size)),
                            Uint32Constant(kUndefinedNanLower32));
      }
      MaybeUpdateLengthAndReturn(receiver, index, value, update_length);
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      BIND(&non_number_value);
    }
    // Transition to object elements.
    {
      TNode<NativeContext> native_context = LoadNativeContext(context);
      ElementsKind target_kind = update_length == kBumpLengthWithGap
                                     ? HOLEY_ELEMENTS
                                     : PACKED_ELEMENTS;
      TryRewriteElements(receiver, receiver_map, elements, native_context,
                         PACKED_DOUBLE_ELEMENTS, target_kind, slow);
      // Reload migrated elements.
      TNode<FixedArrayBase> fast_elements = LoadElements(receiver);
      TNode<IntPtrT> fast_offset =
          ElementOffsetFromIndex(index, PACKED_ELEMENTS, kHeaderSize);
      Store(fast_elements, fast_offset, value);
      MaybeUpdateLengthAndReturn(receiver, index, value, update_length);
    }
  }
  BIND(&check_cow_elements);
  {
    // TODO(jkummerow): Use GrowElementsCapacity instead of bailing out.
    Goto(slow);
  }
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::Branch(), BranchIfPrototypesMayHaveReadOnlyElements(), CAST, v8::internal::CodeStubAssembler::ElementOffsetFromIndex(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::index, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::Is64(), IsDefineKeyedOwnInLiteral(), v8::internal::CodeStubAssembler::IsDictionaryMap(), v8::internal::CodeStubAssembler::IsJSArrayMap(), v8::internal::CodeStubAssembler::IsSetWord32(), v8::internal::PropertyDetails::kAttributesReadOnlyMask, kBumpLengthWithGap, kDontChangeLength, v8::internal::kFloat64, v8::internal::kHeapObjectTag, v8::internal::kInt32Size, v8::internal::kTaggedSigned, v8::internal::kWord32, v8::internal::kWord64, v8::internal::compiler::CodeAssembler::Load(), v8::internal::CodeStubAssembler::LoadDetailsByDescriptorEntry(), v8::internal::CodeStubAssembler::LoadDoubleWithUndefinedAndHoleCheck(), v8::internal::CodeStubAssembler::LoadElements(), v8::internal::CodeStubAssembler::LoadHeapNumberValue(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapDescriptors(), v8::internal::CodeStubAssembler::LoadNativeContext(), MaybeUpdateLengthAndReturn(), v8::internal::native_context, v8::internal::MachineType::None(), OFFSET_OF_DATA_START, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, v8::internal::compiler::CodeAssembler::Store(), v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::CodeStubAssembler::TaggedIsSmi(), TryChangeToHoleyMap(), TryChangeToHoleyMapMulti(), TryRewriteElements(), v8::internal::CodeStubAssembler::TryTaggedToFloat64(), v8::internal::compiler::CodeAssembler::Uint32Constant(), v8::internal::compiler::CodeAssembler::Uint64Constant(), and v8::internal::value.
Referenced by EmitGenericElementStore().
StoreIC_NoFeedback()
void v8::internal::KeyedStoreGenericAssembler::StoreIC_NoFeedback ()
Definition at line 1322 of file keyed-store-generic.cc.
                                                    {
  using Descriptor = StoreNoFeedbackDescriptor;
  auto receiver_maybe_smi = Parameter<JSAny>(Descriptor::kReceiver);
  auto name = Parameter<Object>(Descriptor::kName);
  auto value = Parameter<Object>(Descriptor::kValue);
  auto context = Parameter<Context>(Descriptor::kContext);
  Label miss(this, Label::kDeferred), store_property(this);
  GotoIf(TaggedIsSmi(receiver_maybe_smi), &miss);
  {
    TNode<JSAnyNotSmi> receiver = CAST(receiver_maybe_smi);
    TNode<Map> receiver_map = LoadMap(receiver);
    TNode<Uint16T> instance_type = LoadMapInstanceType(receiver_map);
    // Receivers requiring non-standard element accesses (interceptors, access
    // checks, strings and string wrappers, proxies) are handled in the runtime.
    GotoIf(IsSpecialReceiverInstanceType(instance_type), &miss);
    {
      StoreICParameters p(context, receiver, name, value, std::nullopt, {},
                          UndefinedConstant(),
                          IsDefineNamedOwn() ? StoreICMode::kDefineNamedOwn
                                             : StoreICMode::kDefault);
      EmitGenericPropertyStore(CAST(receiver), receiver_map, instance_type, &p,
                               &miss);
    }
  }
  BIND(&miss);
  {
    auto runtime = IsDefineNamedOwn() ? Runtime::kDefineNamedOwnIC_Miss
                                      : Runtime::kStoreIC_Miss;
    TNode<TaggedIndex> slot =
        TaggedIndexConstant(FeedbackSlot::Invalid().ToInt());
    TailCallRuntime(runtime, context, value, slot, UndefinedConstant(),
                    receiver_maybe_smi, name);
  }
}
References CAST, EmitGenericPropertyStore(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::FeedbackSlot::Invalid(), IsDefineNamedOwn(), v8::internal::CodeStubAssembler::IsSpecialReceiverInstanceType(), v8::internal::AccessorAssembler::kDefault, v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::AccessorAssembler::kDefineNamedOwn, v8::internal::anonymous_namespace{ic.cc}::kName, v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapInstanceType(), v8::internal::name, v8::internal::compiler::CodeAssembler::TaggedIndexConstant(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::compiler::CodeAssembler::TailCallRuntime(), v8::internal::anonymous_namespace{temporal-parser.cc}::ToInt(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::value.
Referenced by v8::internal::StoreICNoFeedbackGenerator::Generate(), and v8::internal::DefineNamedOwnICNoFeedbackGenerator::Generate().
StoreProperty() [1/2]
void v8::internal::KeyedStoreGenericAssembler::StoreProperty (TNode< Context > context, TNode< JSAny > receiver, TNode< Object > key, TNode< Object > value, LanguageMode language_mode)
Definition at line 1314 of file keyed-store-generic.cc.
                                                                           {
  KeyedStoreGeneric(context, receiver, key, value, Just(language_mode));
}
References v8::Just(), v8::internal::key, KeyedStoreGeneric(), and v8::internal::value.
StoreProperty() [2/2]
void v8::internal::KeyedStoreGenericAssembler::StoreProperty (TNode< Context > context, TNode< JSReceiver > receiver, TNode< BoolT > is_simple_receiver, TNode< Name > unique_name, TNode< Object > value, LanguageMode language_mode)
Definition at line 1362 of file keyed-store-generic.cc.
                                                                           {
  StoreICParameters p(context, receiver, unique_name, value, std::nullopt, {},
                      UndefinedConstant(), StoreICMode::kDefault);
  Label done(this), slow(this, Label::kDeferred);
  ExitPoint exit_point(this, [&](TNode<Object> result) { Goto(&done); });
  CSA_DCHECK(this, Word32Equal(is_simple_receiver,
                               IsSimpleObjectMap(LoadMap(receiver))));
  GotoIfNot(is_simple_receiver, &slow);
  TNode<Map> map = LoadMap(receiver);
  TNode<Uint16T> instance_type = LoadMapInstanceType(map);
  EmitGenericPropertyStore(receiver, map, instance_type, &p, &exit_point, &slow,
                           Just(language_mode), kDontUseStubCache);
  BIND(&slow);
  {
    if (IsDefineKeyedOwnInLiteral()) {
      TNode<Smi> flags =
          SmiConstant(DefineKeyedOwnPropertyInLiteralFlag::kNoFlags);
      TNode<TaggedIndex> slot =
          TaggedIndexConstant(FeedbackSlot::Invalid().ToInt());
      CallRuntime(Runtime::kDefineKeyedOwnPropertyInLiteral, context, receiver,
                  unique_name, value, flags, p.vector(), slot);
    } else {
      CallRuntime(Runtime::kSetKeyedProperty, context, receiver, unique_name,
                  value);
    }
    Goto(&done);
  }
  BIND(&done);
}
References v8::internal::compiler::CodeAssembler::CallRuntime(), EmitGenericPropertyStore(), v8::internal::flags, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::FeedbackSlot::Invalid(), IsDefineKeyedOwnInLiteral(), v8::Just(), v8::internal::AccessorAssembler::kDefault, v8::internal::compiler::CodeAssemblerLabel::kDeferred, kDontUseStubCache, v8::internal::kNoFlags, v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapInstanceType(), v8::base::internal::result, v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::compiler::CodeAssembler::TaggedIndexConstant(), v8::internal::anonymous_namespace{temporal-parser.cc}::ToInt(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), v8::internal::value, and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by v8::internal::KeyedStoreGenericGenerator::CreateDataProperty(), and v8::internal::KeyedStoreGenericGenerator::SetProperty().
StoreSharedArrayElement()
void v8::internal::KeyedStoreGenericAssembler::StoreSharedArrayElement (TNode< Context > context, TNode< FixedArrayBase > elements, TNode< IntPtrT > index, TNode< Object > value) [private]
Definition at line 402 of file keyed-store-generic.cc.
                                               {
  TVARIABLE(Object, shared_value, value);
  SharedValueBarrier(context, &shared_value);
  UnsafeStoreFixedArrayElement(CAST(elements), index, shared_value.value());
  Return(value);
}
References CAST, v8::internal::index, v8::internal::compiler::CodeAssembler::Return(), v8::internal::CodeStubAssembler::SharedValueBarrier(), v8::internal::CodeStubAssembler::UnsafeStoreFixedArrayElement(), and v8::internal::value.
Referenced by EmitGenericElementStore().
TryChangeToHoleyMap()
void v8::internal::KeyedStoreGenericAssembler::TryChangeToHoleyMap (TNode< JSObject > receiver, TNode< Map > receiver_map, TNode< Word32T > current_elements_kind, TNode< Context > context, ElementsKind packed_kind, Label * bailout) [private]
Definition at line 352 of file keyed-store-generic.cc.
                                              {
  ElementsKind holey_kind = GetHoleyElementsKind(packed_kind);
  Label already_holey(this);
  GotoIf(Word32Equal(current_elements_kind, Int32Constant(holey_kind)),
         &already_holey);
  TNode<NativeContext> native_context = LoadNativeContext(context);
  TryChangeToHoleyMapHelper(receiver, receiver_map, native_context, packed_kind,
                            holey_kind, &already_holey, bailout, bailout);
  BIND(&already_holey);
}
References v8::internal::GetHoleyElementsKind(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::native_context, TryChangeToHoleyMapHelper(), and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by StoreElementWithCapacity().
TryChangeToHoleyMapHelper()
void v8::internal::KeyedStoreGenericAssembler::TryChangeToHoleyMapHelper (TNode< JSObject > receiver, TNode< Map > receiver_map, TNode< NativeContext > native_context, ElementsKind packed_kind, ElementsKind holey_kind, Label * done, Label * map_mismatch, Label * bailout) [private]
Definition at line 337 of file keyed-store-generic.cc.
                                                                               {
  TNode<Map> packed_map = LoadJSArrayElementsMap(packed_kind, native_context);
  GotoIf(TaggedNotEqual(receiver_map, packed_map), map_mismatch);
  if (AllocationSite::ShouldTrack(packed_kind, holey_kind)) {
    TrapAllocationMemento(receiver, bailout);
  }
  TNode<Map> holey_map = CAST(LoadContextElementNoCell(
      native_context, Context::ArrayMapIndex(holey_kind)));
  StoreMap(receiver, holey_map);
  Goto(done);
}
References v8::internal::Context::ArrayMapIndex(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), v8::internal::native_context, v8::internal::AllocationSite::ShouldTrack(), v8::internal::CodeStubAssembler::StoreMap(), v8::internal::CodeStubAssembler::TaggedNotEqual(), and v8::internal::CodeStubAssembler::TrapAllocationMemento().
Referenced by TryChangeToHoleyMap(), and TryChangeToHoleyMapMulti().
TryChangeToHoleyMapMulti()
void v8::internal::KeyedStoreGenericAssembler::TryChangeToHoleyMapMulti (TNode< JSObject > receiver, TNode< Map > receiver_map, TNode< Word32T > current_elements_kind, TNode< Context > context, ElementsKind packed_kind, ElementsKind packed_kind_2, Label * bailout) [private]
Definition at line 367 of file keyed-store-generic.cc.
                                                                          {
  ElementsKind holey_kind = GetHoleyElementsKind(packed_kind);
  ElementsKind holey_kind_2 = GetHoleyElementsKind(packed_kind_2);
  Label already_holey(this), check_other_kind(this);
  GotoIf(Word32Equal(current_elements_kind, Int32Constant(holey_kind)),
         &already_holey);
  GotoIf(Word32Equal(current_elements_kind, Int32Constant(holey_kind_2)),
         &already_holey);
  TNode<NativeContext> native_context = LoadNativeContext(context);
  TryChangeToHoleyMapHelper(receiver, receiver_map, native_context, packed_kind,
                            holey_kind, &already_holey, &check_other_kind,
                            bailout);
  BIND(&check_other_kind);
  TryChangeToHoleyMapHelper(receiver, receiver_map, native_context,
                            packed_kind_2, holey_kind_2, &already_holey,
                            bailout, bailout);
  BIND(&already_holey);
}
References v8::internal::GetHoleyElementsKind(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::native_context, TryChangeToHoleyMapHelper(), and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by StoreElementWithCapacity().
TryRewriteElements()
void v8::internal::KeyedStoreGenericAssembler::TryRewriteElements (TNode< JSObject > receiver, TNode< Map > receiver_map, TNode< FixedArrayBase > elements, TNode< NativeContext > native_context, ElementsKind from_kind, ElementsKind to_kind, Label * bailout) [private]
Definition at line 293 of file keyed-store-generic.cc.
                                                                  {
  DCHECK(IsFastPackedElementsKind(from_kind));
  ElementsKind holey_from_kind = GetHoleyElementsKind(from_kind);
  ElementsKind holey_to_kind = GetHoleyElementsKind(to_kind);
  if (AllocationSite::ShouldTrack(from_kind, to_kind)) {
    TrapAllocationMemento(receiver, bailout);
  }
  Label perform_transition(this), check_holey_map(this);
  TVARIABLE(Map, var_target_map);
  // Check if the receiver has the default |from_kind| map.
  {
    TNode<Map> packed_map = LoadJSArrayElementsMap(from_kind, native_context);
    GotoIf(TaggedNotEqual(receiver_map, packed_map), &check_holey_map);
    var_target_map = CAST(LoadContextElementNoCell(
        native_context, Context::ArrayMapIndex(to_kind)));
    Goto(&perform_transition);
  }
  // Check if the receiver has the default |holey_from_kind| map.
  BIND(&check_holey_map);
  {
    TNode<Object> holey_map = LoadContextElementNoCell(
        native_context, Context::ArrayMapIndex(holey_from_kind));
    GotoIf(TaggedNotEqual(receiver_map, holey_map), bailout);
    var_target_map = CAST(LoadContextElementNoCell(
        native_context, Context::ArrayMapIndex(holey_to_kind)));
    Goto(&perform_transition);
  }
  // Found a supported transition target map, perform the transition!
  BIND(&perform_transition);
  {
    if (IsDoubleElementsKind(from_kind) != IsDoubleElementsKind(to_kind)) {
      TNode<IntPtrT> capacity = LoadAndUntagFixedArrayBaseLength(elements);
      GrowElementsCapacity(receiver, elements, from_kind, to_kind, capacity,
                           capacity, bailout);
    }
    StoreMap(receiver, var_target_map.value());
  }
}
References v8::internal::Context::ArrayMapIndex(), CAST, v8::internal::DCHECK(), v8::internal::GetHoleyElementsKind(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::GrowElementsCapacity(), v8::internal::CodeStubAssembler::IsDoubleElementsKind(), v8::internal::CodeStubAssembler::IsFastPackedElementsKind(), v8::internal::CodeStubAssembler::LoadAndUntagFixedArrayBaseLength(), v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), v8::internal::native_context, v8::internal::AllocationSite::ShouldTrack(), v8::internal::CodeStubAssembler::StoreMap(), v8::internal::CodeStubAssembler::TaggedNotEqual(), and v8::internal::CodeStubAssembler::TrapAllocationMemento().
Referenced by StoreElementWithCapacity().
Member Data Documentation
mode_
StoreMode v8::internal::KeyedStoreGenericAssembler::mode_ [private]
Definition at line 81 of file keyed-store-generic.cc.
Referenced by IsDefineKeyedOwn(), IsDefineKeyedOwnInLiteral(), IsDefineNamedOwn(), and IsSet().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ic/keyed-store-generic.cc