v8::internal::AllocationTracker Class Reference
#include <allocation-tracker.h>
Classes
struct FunctionInfo
class ScriptData
Public Member Functions
AllocationTracker (HeapObjectsMap *ids, StringsStorage *names)
~AllocationTracker ()
AllocationTracker (const AllocationTracker &)=delete
AllocationTracker & operator= (const AllocationTracker &)=delete
void AllocationEvent (Address addr, int size)
AllocationTraceTree * trace_tree ()
const std::vector< FunctionInfo * > & function_info_list () const
AddressToTraceMap * address_to_trace ()
Private Types
using ScriptId = int
using ScriptsDataMap = std::unordered_map< ScriptId, ScriptData >
Private Member Functions
unsigned AddFunctionInfo (Tagged< SharedFunctionInfo > info, SnapshotObjectId id, Isolate *isolate)
String::LineEndsVector & GetOrCreateLineEnds (Tagged< Script > script, Isolate *isolate)
Script::PositionInfo GetScriptPositionInfo (Tagged< Script > script, Isolate *isolate, int start)
unsigned functionInfoIndexForVMState (StateTag state)
Private Attributes
HeapObjectsMap * ids_
StringsStorage * names_
AllocationTraceTree trace_tree_
unsigned allocation_trace_buffer_ [kMaxAllocationTraceLength]
std::vector< FunctionInfo * > function_info_list_
base::HashMap id_to_function_info_index_
unsigned info_index_for_other_state_
AddressToTraceMap address_to_trace_
ScriptsDataMap scripts_data_map_
Static Private Attributes
static const int kMaxAllocationTraceLength = 64
Detailed Description
Definition at line 103 of file allocation-tracker.h.
Member Typedef Documentation
ScriptId
using v8::internal::AllocationTracker::ScriptId = int [private]
Definition at line 147 of file allocation-tracker.h.
ScriptsDataMap
using v8::internal::AllocationTracker::ScriptsDataMap = std::unordered_map<ScriptId, ScriptData> [private]
Definition at line 161 of file allocation-tracker.h.
Constructor & Destructor Documentation
AllocationTracker() [1/2]
v8::internal::AllocationTracker::AllocationTracker (HeapObjectsMap * ids, StringsStorage * names)
Definition at line 176 of file allocation-tracker.cc.
    : ids_(ids),
      names_(names),
      id_to_function_info_index_(),
      info_index_for_other_state_(0) {
  FunctionInfo* info = new FunctionInfo();
  info->name = "(root)";
  function_info_list_.push_back(info);
}
References function_info_list_, and v8::internal::AllocationTracker::FunctionInfo::name.
 AllocationTracker()
v8::internal::AllocationTracker::~AllocationTracker ()
Definition at line 186 of file allocation-tracker.cc.
                                      {
  for (FunctionInfo* info : function_info_list_) delete info;
}
References function_info_list_.
AllocationTracker() [2/2]
v8::internal::AllocationTracker::AllocationTracker (const AllocationTracker &) [delete]
Member Function Documentation
AddFunctionInfo()
unsigned v8::internal::AllocationTracker::AddFunctionInfo (Tagged< SharedFunctionInfo > info, SnapshotObjectId id, Isolate * isolate) [private]
Definition at line 279 of file allocation-tracker.cc.
                                                              {
  base::HashMap::Entry* entry = id_to_function_info_index_.LookupOrInsert(
      reinterpret_cast<void*>(id), SnapshotObjectIdHash(id));
  if (entry->value == nullptr) {
    FunctionInfo* info = new FunctionInfo();
    info->name = names_->GetCopy(shared->DebugNameCStr().get());
    info->function_id = id;
    if (IsScript(shared->script())) {
      Tagged<Script> script = Cast<Script>(shared->script());
      if (IsName(script->name())) {
        Tagged<Name> name = Cast<Name>(script->name());
        info->script_name = names_->GetName(name);
      }
      info->script_id = script->id();
      info->start_position = shared->StartPosition();
      Script::PositionInfo position_info =
          GetScriptPositionInfo(script, isolate, info->start_position);
      info->line = position_info.line;
      info->column = position_info.column;
    }
    entry->value = reinterpret_cast<void*>(function_info_list_.size());
    function_info_list_.push_back(info);
  }
  return static_cast<unsigned>(reinterpret_cast<intptr_t>((entry->value)));
}
References v8::internal::Script::PositionInfo::column, v8::internal::AllocationTracker::FunctionInfo::column, v8::internal::AllocationTracker::FunctionInfo::function_id, function_info_list_, v8::internal::StringsStorage::GetCopy(), v8::internal::StringsStorage::GetName(), GetScriptPositionInfo(), id_to_function_info_index_, v8::internal::Script::PositionInfo::line, v8::internal::AllocationTracker::FunctionInfo::line, v8::internal::AllocationTracker::FunctionInfo::name, v8::internal::name, names_, v8::internal::script, v8::internal::AllocationTracker::FunctionInfo::script_id, v8::internal::AllocationTracker::FunctionInfo::script_name, v8::internal::SnapshotObjectIdHash(), and v8::internal::AllocationTracker::FunctionInfo::start_position.
Referenced by AllocationEvent().
address_to_trace()
AddressToTraceMap* v8::internal::AllocationTracker::address_to_trace () [inline]
Definition at line 127 of file allocation-tracker.h.
{ return &address_to_trace_; }
References address_to_trace_.
AllocationEvent()
void v8::internal::AllocationTracker::AllocationEvent (Address addr, int size)
Definition at line 190 of file allocation-tracker.cc.
                                                              {
  DisallowGarbageCollection no_gc;
  Heap* heap = ids_->heap();
  // Mark the new block as FreeSpace to make sure the heap is iterable
  // while we are capturing stack trace.
  heap->CreateFillerObjectAt(addr, size);
  Isolate* isolate = Isolate::FromHeap(heap);
  int length = 0;
  JavaScriptStackFrameIterator it(isolate);
  while (!it.done() && length < kMaxAllocationTraceLength) {
    JavaScriptFrame* frame = it.frame();
    Tagged<SharedFunctionInfo> shared = frame->function()->shared();
    SnapshotObjectId id =
        ids_->FindOrAddEntry(shared.address(), shared->Size(),
                             HeapObjectsMap::MarkEntryAccessed::kNo);
    allocation_trace_buffer_[length++] = AddFunctionInfo(shared, id, isolate);
    it.Advance();
  }
  if (length == 0) {
    unsigned index = functionInfoIndexForVMState(isolate->current_vm_state());
    if (index != 0) {
      allocation_trace_buffer_[length++] = index;
    }
  }
  AllocationTraceNode* top_node = trace_tree_.AddPathFromEnd(
      base::Vector<unsigned>(allocation_trace_buffer_, length));
  top_node->AddAllocation(size);
  address_to_trace_.AddRange(addr, size, top_node->id());
}
References v8::internal::AllocationTraceNode::AddAllocation(), AddFunctionInfo(), v8::internal::AllocationTraceTree::AddPathFromEnd(), v8::internal::AddressToTraceMap::AddRange(), v8::internal::Tagged< HeapObject >::address(), address_to_trace_, v8::internal::JavaScriptStackFrameIterator::Advance(), allocation_trace_buffer_, v8::internal::JavaScriptStackFrameIterator::done(), v8::internal::HeapObjectsMap::FindOrAddEntry(), v8::internal::JavaScriptStackFrameIterator::frame(), v8::internal::Isolate::FromHeap(), v8::internal::JavaScriptFrame::function(), functionInfoIndexForVMState(), v8::internal::HeapObjectsMap::heap(), v8::internal::AllocationTraceNode::id(), ids_, v8::internal::index, kMaxAllocationTraceLength, v8::internal::HeapObjectsMap::kNo, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, size(), and trace_tree_.
function_info_list()
const std::vector<FunctionInfo*>& v8::internal::AllocationTracker::function_info_list () const [inline]
Definition at line 124 of file allocation-tracker.h.
                                                             {
    return function_info_list_;
  }
References function_info_list_.
Referenced by v8::internal::AllocationTraceNode::Print(), and v8::internal::HeapSnapshotJSONSerializer::SerializeTraceNodeInfos().
functionInfoIndexForVMState()
unsigned v8::internal::AllocationTracker::functionInfoIndexForVMState (StateTag state) [private]
Definition at line 307 of file allocation-tracker.cc.
                                                                      {
  if (state != OTHER) return 0;
  if (info_index_for_other_state_ == 0) {
    FunctionInfo* info = new FunctionInfo();
    info->name = "(V8 API)";
    info_index_for_other_state_ =
        static_cast<unsigned>(function_info_list_.size());
    function_info_list_.push_back(info);
  }
  return info_index_for_other_state_;
}
References function_info_list_, info_index_for_other_state_, v8::internal::AllocationTracker::FunctionInfo::name, and v8::OTHER.
Referenced by AllocationEvent().
GetOrCreateLineEnds()
String::LineEndsVector & v8::internal::AllocationTracker::GetOrCreateLineEnds (Tagged< Script > script, Isolate * isolate) [private]
Definition at line 254 of file allocation-tracker.cc.
                                             {
  auto it = scripts_data_map_.find(script->id());
  if (it == scripts_data_map_.end()) {
    auto inserted =
        scripts_data_map_.try_emplace(script->id(), script, isolate, this);
    CHECK(inserted.second);
    return inserted.first->second.line_ends();
  } else {
    return it->second.line_ends();
  }
}
References CHECK, v8::internal::script, and scripts_data_map_.
Referenced by GetScriptPositionInfo().
GetScriptPositionInfo()
Script::PositionInfo v8::internal::AllocationTracker::GetScriptPositionInfo (Tagged< Script > script, Isolate * isolate, int start) [private]
Definition at line 267 of file allocation-tracker.cc.
                                                        {
  Script::PositionInfo position_info;
  if (script->has_line_ends()) {
    script->GetPositionInfo(start, &position_info);
  } else {
    script->GetPositionInfoWithLineEnds(start, &position_info,
                                        GetOrCreateLineEnds(script, isolate));
  }
  return position_info;
}
References GetOrCreateLineEnds(), and v8::internal::script.
Referenced by AddFunctionInfo().
operator=()
AllocationTracker& v8::internal::AllocationTracker::operator= (const AllocationTracker &) [delete]
trace_tree()
AllocationTraceTree* v8::internal::AllocationTracker::trace_tree () [inline]
Definition at line 123 of file allocation-tracker.h.
{ return &trace_tree_; }
References trace_tree_.
Referenced by v8::internal::HeapSnapshotJSONSerializer::SerializeTraceTree().
Member Data Documentation
address_to_trace_
AddressToTraceMap v8::internal::AllocationTracker::address_to_trace_ [private]
Definition at line 146 of file allocation-tracker.h.
Referenced by address_to_trace(), and AllocationEvent().
allocation_trace_buffer_
unsigned v8::internal::AllocationTracker::allocation_trace_buffer_[kMaxAllocationTraceLength] [private]
Definition at line 142 of file allocation-tracker.h.
Referenced by AllocationEvent().
function_info_list_
std::vector<FunctionInfo*> v8::internal::AllocationTracker::function_info_list_ [private]
Definition at line 143 of file allocation-tracker.h.
Referenced by AddFunctionInfo(), AllocationTracker(), function_info_list(), functionInfoIndexForVMState(), and ~AllocationTracker().
id_to_function_info_index_
base::HashMap v8::internal::AllocationTracker::id_to_function_info_index_ [private]
Definition at line 144 of file allocation-tracker.h.
Referenced by AddFunctionInfo().
ids_
HeapObjectsMap* v8::internal::AllocationTracker::ids_ [private]
Definition at line 139 of file allocation-tracker.h.
Referenced by AllocationEvent().
info_index_for_other_state_
unsigned v8::internal::AllocationTracker::info_index_for_other_state_ [private]
Definition at line 145 of file allocation-tracker.h.
Referenced by functionInfoIndexForVMState().
kMaxAllocationTraceLength
const int v8::internal::AllocationTracker::kMaxAllocationTraceLength = 64 [static], [private]
Definition at line 138 of file allocation-tracker.h.
Referenced by AllocationEvent().
names_
StringsStorage* v8::internal::AllocationTracker::names_ [private]
Definition at line 140 of file allocation-tracker.h.
Referenced by AddFunctionInfo().
scripts_data_map_
ScriptsDataMap v8::internal::AllocationTracker::scripts_data_map_ [private]
Definition at line 162 of file allocation-tracker.h.
Referenced by GetOrCreateLineEnds(), and v8::internal::AllocationTracker::ScriptData::HandleWeakScript().
trace_tree_
AllocationTraceTree v8::internal::AllocationTracker::trace_tree_ [private]
Definition at line 141 of file allocation-tracker.h.
Referenced by AllocationEvent(), and trace_tree().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/allocation-tracker.h
/mnt/V8SourceCode/src/profiler/allocation-tracker.cc