v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy > Class Template Reference
#include <hashmap.h>
Classes
struct Impl
Public Types
using Entry = TemplateHashMapEntry< Key, Value >
Public Member Functions
TemplateHashMapImpl (uint32_t capacity=kDefaultHashMapCapacity, MatchFun match=MatchFun(), AllocationPolicy allocator=AllocationPolicy())
TemplateHashMapImpl (const TemplateHashMapImpl &)=delete
TemplateHashMapImpl & operator= (const TemplateHashMapImpl &)=delete
TemplateHashMapImpl (const TemplateHashMapImpl *original, AllocationPolicy allocator=AllocationPolicy())
TemplateHashMapImpl (TemplateHashMapImpl &&other) V8_NOEXCEPT=default
~TemplateHashMapImpl ()
TemplateHashMapImpl & operator= (TemplateHashMapImpl &&other) V8_NOEXCEPT=default
Entry * Lookup (const Key &key, uint32_t hash) const
Entry * LookupOrInsert (const Key &key, uint32_t hash)
template<typename Func >
Entry * LookupOrInsert (const Key &key, uint32_t hash, const Func &value_func)
template<typename LookupKey , typename KeyFunc , typename ValueFunc >
Entry * LookupOrInsert (const LookupKey &lookup_key, uint32_t hash, const KeyFunc &key_func, const ValueFunc &value_func)
Entry * InsertNew (const Key &key, uint32_t hash)
Value Remove (const Key &key, uint32_t hash)
Value Remove (Entry *entry)
void Clear ()
void Invalidate ()
uint32_t occupancy () const
uint32_t capacity () const
Entry * Start () const
Entry * Next (Entry *entry) const
AllocationPolicy allocator () const
Static Public Attributes
static const uint32_t kDefaultHashMapCapacity = 8
Protected Member Functions
void Initialize (uint32_t capacity)
Private Member Functions
Entry * map_end () const
template<typename LookupKey >
Entry * Probe (const LookupKey &key, uint32_t hash) const
Entry * FillEmptyEntry (Entry *entry, const Key &key, const Value &value, uint32_t hash)
void Resize ()
Private Attributes
v8::base::TemplateHashMapImpl::Impl impl_
Detailed Description
template<typename Key, typename Value, class MatchFun, class AllocationPolicy>
class v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >
Definition at line 35 of file hashmap.h.
Member Typedef Documentation
Entry
template<typename Key , typename Value , class MatchFun , class AllocationPolicy >
using v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Entry = TemplateHashMapEntry<Key, Value>
Definition at line 37 of file hashmap.h.
Constructor & Destructor Documentation
TemplateHashMapImpl() [1/4]
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::TemplateHashMapImpl (uint32_t capacity = kDefaultHashMapCapacity, MatchFun match = MatchFun(), AllocationPolicy allocator = AllocationPolicy()) [explicit]
Definition at line 186 of file hashmap.h.
    : impl_(std::move(match), std::move(allocator)) {
  Initialize(initial_capacity);
}
References v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Initialize().
TemplateHashMapImpl() [2/4]
template<typename Key , typename Value , class MatchFun , class AllocationPolicy >
v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::TemplateHashMapImpl (const TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy > &) [delete]
TemplateHashMapImpl() [3/4]
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::TemplateHashMapImpl (const TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy > * original, AllocationPolicy allocator = AllocationPolicy()) [explicit]
Definition at line 195 of file hashmap.h.
    : impl_(original->impl_.match(), std::move(allocator)) {
  impl_.capacity_ = original->capacity();
  impl_.occupancy_ = original->occupancy();
  impl_.map_ = impl_.allocator().template AllocateArray<Entry>(capacity());
  memcpy(impl_.map_, original->impl_.map_, capacity() * sizeof(Entry));
}
References v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Impl::allocator(), v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::capacity(), v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Impl::capacity_, v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::impl_, v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Impl::map_, v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::occupancy(), and v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Impl::occupancy_.
TemplateHashMapImpl() [4/4]
template<typename Key , typename Value , class MatchFun , class AllocationPolicy >
v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::TemplateHashMapImpl (TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy > && other) [default]
 TemplateHashMapImpl()
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::~TemplateHashMapImpl
Definition at line 208 of file hashmap.h.
                                                            {
  if (impl_.map_) impl_.allocator().DeleteArray(impl_.map_, capacity());
}
Member Function Documentation
allocator()
template<typename Key , typename Value , class MatchFun , class AllocationPolicy >
AllocationPolicy v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::allocator () const [inline]
Definition at line 130 of file hashmap.h.
{ return impl_.allocator(); }
References v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Impl::allocator(), and v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::impl_.
capacity()
template<typename Key , typename Value , class MatchFun , class AllocationPolicy >
uint32_t v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::capacity () const [inline]
Definition at line 117 of file hashmap.h.
{ return impl_.capacity_; }
References v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Impl::capacity_, and v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::impl_.
Referenced by v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Invalidate(), v8::internal::ClassScope::ResolvePrivateNamesPartially(), and v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::TemplateHashMapImpl().
Clear()
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
void v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Clear
Definition at line 338 of file hashmap.h.
                                                                        {
  // Mark all entries as empty.
  memset(impl_.map_, 0, capacity() * sizeof(Entry));
  impl_.occupancy_ = 0;
}
Referenced by v8::internal::compiler::JSHeapBroker::InitializeAndStartSerializing().
FillEmptyEntry()
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Entry * v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::FillEmptyEntry (Entry * entry, const Key & key, const Value & value, uint32_t hash) [private]
Definition at line 391 of file hashmap.h.
                                                                     {
  DCHECK(!entry->exists());
  new (entry) Entry(key, value, hash);
  impl_.occupancy_++;
  // Grow the map if we reached >= 80% occupancy.
  if (occupancy() + occupancy() / 4 >= capacity()) {
    Resize();
    entry = Probe(key, hash);
  }
  return entry;
}
References DCHECK, v8::base::TemplateHashMapEntry< Key, Value >::exists(), v8::internal::key, cppgc::subtle::Resize(), and v8::internal::value.
Initialize()
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
void v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Initialize (uint32_t capacity) [protected]
Definition at line 409 of file hashmap.h.
                       {
  DCHECK(base::bits::IsPowerOfTwo(capacity));
  impl_.map_ = impl_.allocator().template AllocateArray<Entry>(capacity);
  if (impl_.map_ == nullptr) {
    FATAL("Out of memory: HashMap::Initialize");
    return;
  }
  impl_.capacity_ = capacity;
  Clear();
}
References DCHECK, FATAL, and v8::base::bits::IsPowerOfTwo().
Referenced by v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::TemplateHashMapImpl().
InsertNew()
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Entry * v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::InsertNew (const Key & key, uint32_t hash)
Definition at line 258 of file hashmap.h.
                                   {
  Entry* entry = Probe(key, hash);
  return FillEmptyEntry(entry, key, Value(), hash);
}
References v8::internal::key.
Invalidate()
template<typename Key , typename Value , class MatchFun , class AllocationPolicy >
void v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Invalidate () [inline]
Definition at line 105 of file hashmap.h.
                    {
    DCHECK_NOT_NULL(impl_.map_);
    impl_.allocator().DeleteArray(impl_.map_, capacity());
    impl_ = Impl(impl_.match(), AllocationPolicy());
  }
References v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Impl::allocator(), v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::capacity(), DCHECK_NOT_NULL, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::impl_, v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Impl::map_, and v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Impl::match().
Referenced by v8::internal::DeclarationScope::ResetAfterPreparsing().
Lookup()
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Entry * v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Lookup (const Key & key, uint32_t hash) const
Definition at line 215 of file hashmap.h.
                                         {
  Entry* entry = Probe(key, hash);
  return entry->exists() ? entry : nullptr;
}
References v8::base::TemplateHashMapEntry< Key, Value >::exists(), and v8::internal::key.
LookupOrInsert() [1/3]
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Entry * v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::LookupOrInsert (const Key & key, uint32_t hash)
Definition at line 224 of file hashmap.h.
                                   {
  return LookupOrInsert(key, hash, []() { return Value(); });
}
References v8::internal::key.
Referenced by v8::internal::ObjectLiteral::CalculateEmitStore(), and v8::internal::compiler::StateValuesCache::GetValuesNodeFromCache().
LookupOrInsert() [2/3]
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
template<typename Func >
TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Entry * v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::LookupOrInsert (const Key & key, uint32_t hash, const Func & value_func)
Definition at line 233 of file hashmap.h.
                                                           {
  return LookupOrInsert(
      key, hash, [&key]() { return key; }, value_func);
}
References v8::internal::key.
LookupOrInsert() [3/3]
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
template<typename LookupKey , typename KeyFunc , typename ValueFunc >
TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Entry * v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::LookupOrInsert (const LookupKey & lookup_key, uint32_t hash, const KeyFunc & key_func, const ValueFunc & value_func)
Definition at line 243 of file hashmap.h.
                                 {
  // Find a matching entry.
  Entry* entry = Probe(lookup_key, hash);
  if (entry->exists()) {
    return entry;
  }
  return FillEmptyEntry(entry, key_func(), value_func(), hash);
}
References v8::base::TemplateHashMapEntry< Key, Value >::exists().
map_end()
template<typename Key , typename Value , class MatchFun , class AllocationPolicy >
Entry* v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::map_end () const [inline], [private]
Definition at line 136 of file hashmap.h.
{ return impl_.map_ + impl_.capacity_; }
References v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Impl::capacity_, v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::impl_, and v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Impl::map_.
Next()
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Entry * v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Next (Entry * entry) const
Definition at line 354 of file hashmap.h.
                        {
  const Entry* end = map_end();
  DCHECK_LE(impl_.map_ - 1, entry);
  DCHECK_LT(entry, map_end());
  for (entry++; entry < end; entry++) {
    if (entry->exists()) {
      return entry;
    }
  }
  return nullptr;
}
References DCHECK_LE, DCHECK_LT, v8::internal::compiler::end(), and v8::base::TemplateHashMapEntry< Key, Value >::exists().
Referenced by v8::internal::Scope::FindVariableDeclaredIn(), and v8::base::TemplateHashMap< Key, Value, MatchFun, AllocationPolicy >::Iterator::operator++().
occupancy()
template<typename Key , typename Value , class MatchFun , class AllocationPolicy >
uint32_t v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::occupancy () const [inline]
Definition at line 112 of file hashmap.h.
{ return impl_.occupancy_; }
References v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::impl_, and v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Impl::occupancy_.
Referenced by v8::internal::Scope::FinalizeBlockScope(), v8::internal::Scope::ResolveVariablesRecursively(), and v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::TemplateHashMapImpl().
operator=() [1/2]
template<typename Key , typename Value , class MatchFun , class AllocationPolicy >
TemplateHashMapImpl& v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::operator= (const TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy > &) [delete]
operator=() [2/2]
template<typename Key , typename Value , class MatchFun , class AllocationPolicy >
TemplateHashMapImpl& v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::operator= (TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy > && other) [default]
Probe()
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
template<typename LookupKey >
TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Entry * v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Probe (const LookupKey & key, uint32_t hash) const [private]
Definition at line 371 of file hashmap.h.
                                               {
  hash &= 0x7FFFFFFF;
  DCHECK(base::bits::IsPowerOfTwo(capacity()));
  size_t i = hash & (capacity() - 1);
  DCHECK(i < capacity());
  DCHECK(occupancy() < capacity()); // Guarantees loop termination.
  Entry* map = impl_.map_;
  while (map[i].exists() &&
         !impl_.match()(hash, map[i].hash, key, map[i].key)) {
    i = (i + 1) & (capacity() - 1);
  }
  return &map[i];
}
References DCHECK, v8::base::TemplateHashMapEntry< Key, Value >::hash, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::bits::IsPowerOfTwo(), v8::base::TemplateHashMapEntry< Key, Value >::key, and v8::internal::key.
Remove() [1/2]
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
Value v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Remove (const Key & key, uint32_t hash)
Definition at line 266 of file hashmap.h.
                                   {
  // Lookup the entry for the key to remove.
  Entry* p = Probe(key, hash);
  if (!p->exists()) {
    // Key not found nothing to remove.
    return nullptr;
  }
  return Remove(p);
}
References v8::base::TemplateHashMapEntry< Key, Value >::exists(), and v8::internal::key.
Remove() [2/2]
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
Value v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Remove (Entry * entry)
Definition at line 281 of file hashmap.h.
              {
  DCHECK_LE(impl_.map_ - 1, p);
  DCHECK_LT(p, map_end());
  Value value = p->value;
  // To remove an entry we need to ensure that it does not create an empty
  // entry that will cause the search for another entry to stop too soon. If all
  // the entries between the entry to remove and the next empty slot have their
  // initial position inside this interval, clearing the entry to remove will
  // not break the search. If, while searching for the next empty entry, an
  // entry is encountered which does not have its initial position between the
  // entry to remove and the position looked at, then this entry can be moved to
  // the place of the entry to remove without breaking the search for it. The
  // entry made vacant by this move is now the entry to remove and the process
  // starts over.
  // Algorithm from http://en.wikipedia.org/wiki/Open_addressing.
  // This guarantees loop termination as there is at least one empty entry so
  // eventually the removed entry will have an empty entry after it.
  DCHECK(occupancy() < capacity());
  // p is the candidate entry to clear. q is used to scan forwards.
  Entry* q = p; // Start at the entry to remove.
  while (true) {
    // Move q to the next entry.
    q = q + 1;
    if (q == map_end()) {
      q = impl_.map_;
    }
    // All entries between p and q have their initial position between p and q
    // and the entry p can be cleared without breaking the search for these
    // entries.
    if (!q->exists()) {
      break;
    }
    // Find the initial position for the entry at position q.
    Entry* r = impl_.map_ + (q->hash & (capacity() - 1));
    // If the entry at position q has its initial position outside the range
    // between p and q it can be moved forward to position p and will still be
    // found. There is now a new candidate entry for clearing.
    if ((q > p && (r <= p || r > q)) || (q < p && (r <= p && r > q))) {
      *p = *q;
      p = q;
    }
  }
  // Clear the entry which is allowed to en emptied.
  p->clear();
  impl_.occupancy_--;
  return value;
}
References v8::base::TemplateHashMapEntry< Key, Value >::clear(), DCHECK, DCHECK_LE, DCHECK_LT, v8::base::TemplateHashMapEntry< Key, Value >::exists(), v8::base::TemplateHashMapEntry< Key, Value >::hash, v8::base::TemplateHashMapEntry< Key, Value >::value, and v8::internal::value.
Resize()
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
void v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Resize [private]
Definition at line 423 of file hashmap.h.
                                                                         {
  Entry* old_map = impl_.map_;
  uint32_t old_capacity = capacity();
  uint32_t n = occupancy();
  // Allocate larger map.
  Initialize(capacity() * 2);
  // Rehash all current entries.
  for (Entry* entry = old_map; n > 0; entry++) {
    if (entry->exists()) {
      Entry* new_entry = Probe(entry->key, entry->hash);
      new_entry =
          FillEmptyEntry(new_entry, entry->key, entry->value, entry->hash);
      n--;
    }
  }
  // Delete old map.
  impl_.allocator().DeleteArray(old_map, old_capacity);
}
References v8::base::TemplateHashMapEntry< Key, Value >::key.
Start()
template<typename Key , typename Value , typename MatchFun , class AllocationPolicy >
TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Entry * v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Start
Definition at line 347 of file hashmap.h.
                                                                         {
  return Next(impl_.map_ - 1);
}
References v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next().
Referenced by v8::internal::Scope::FindVariableDeclaredIn().
Member Data Documentation
impl_
template<typename Key , typename Value , class MatchFun , class AllocationPolicy >
v8::base::TemplateHashMapImpl::Impl v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::impl_ [private]
Referenced by v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::allocator(), v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::capacity(), v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::Invalidate(), v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::map_end(), v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::occupancy(), and v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::TemplateHashMapImpl().
kDefaultHashMapCapacity
template<typename Key , typename Value , class MatchFun , class AllocationPolicy >
const uint32_t v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::kDefaultHashMapCapacity = 8 [static]
Definition at line 42 of file hashmap.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/hashmap.h