v8::internal::WasmCodePointer Class Reference
#include <globals.h>
Public Member Functions
WasmCodePointer ()=default
constexpr WasmCodePointer (uint32_t value)
uint32_t value () const
bool operator== (const WasmCodePointer &other) const
bool operator!= (const WasmCodePointer &other) const
Private Attributes
uint32_t value_ = -1
Friends
template<typename H >
H AbslHashValue (H h, const WasmCodePointer &code_pointer)
Detailed Description
Definition at line 2891 of file globals.h.
Constructor & Destructor Documentation
WasmCodePointer() [1/2]
v8::internal::WasmCodePointer::WasmCodePointer () [default]
WasmCodePointer() [2/2]
constexpr v8::internal::WasmCodePointer::WasmCodePointer (uint32_t value) [inline], [explicit], [constexpr]
Definition at line 2894 of file globals.h.
: value_(value) {}
Member Function Documentation
operator!=()
bool v8::internal::WasmCodePointer::operator!= (const WasmCodePointer & other) const [inline]
Definition at line 2901 of file globals.h.
                                                      {
    return value_ != other.value_;
  }
References value_.
operator==()
bool v8::internal::WasmCodePointer::operator== (const WasmCodePointer & other) const [inline]
Definition at line 2898 of file globals.h.
                                                      {
    return value_ == other.value_;
  }
References value_.
value()
uint32_t v8::internal::WasmCodePointer::value () const [inline]
Definition at line 2896 of file globals.h.
{ return value_; }
References value_.
Referenced by v8::internal::wasm::WasmCodePointerTable::FreeEntry(), v8::internal::WasmDispatchTable::Grow(), v8::internal::WasmInternalFunction::set_call_target(), v8::internal::WritableRelocInfo::set_wasm_code_pointer_table_entry(), and v8::internal::WasmDispatchTable::SetForNonWrapper().
Friends And Related Function Documentation
AbslHashValue
template<typename H >
H AbslHashValue (H h, const WasmCodePointer & code_pointer) [friend]
Definition at line 2906 of file globals.h.
                                                                   {
    return H::combine(std::move(h), code_pointer.value());
  }
Member Data Documentation
value_
uint32_t v8::internal::WasmCodePointer::value_ = -1 [private]
Definition at line 2911 of file globals.h.
Referenced by operator!=(), operator==(), and value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/common/globals.h