v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness > Class Template Reference
#include <control-path-state.h>
Protected Member Functions
AdvancedReducerWithControlPathState (Editor *editor, Zone *zone, TFGraph *graph)
Reduction TakeStatesFromFirstControl (Node *node)
Reduction UpdateStates (Node *state_owner, ControlPathState< NodeState, node_uniqueness > new_state)
Reduction UpdateStates (Node *state_owner, ControlPathState< NodeState, node_uniqueness > prev_states, Node *additional_node, NodeState additional_state, bool in_new_block)
Zone * zone ()
ControlPathState< NodeState, node_uniqueness > GetState (Node *node)
bool IsReduced (Node *node)
Private Attributes
Zone * zone_
NodeAuxData< ControlPathState< NodeState, node_uniqueness >, ZoneConstruct< ControlPathState< NodeState, node_uniqueness > > > node_states_
NodeAuxData< bool > reduced_
Additional Inherited Members
Detailed Description
template<typename NodeState, NodeUniqueness node_uniqueness>
class v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >
Definition at line 86 of file control-path-state.h.
Constructor & Destructor Documentation
AdvancedReducerWithControlPathState()
template<typename NodeState , NodeUniqueness node_uniqueness>
v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::AdvancedReducerWithControlPathState (Editor * editor, Zone * zone, TFGraph * graph) [inline], [protected]
Definition at line 88 of file control-path-state.h.
      : AdvancedReducer(editor),
        zone_(zone),
        node_states_(graph->NodeCount(), zone),
        reduced_(graph->NodeCount(), zone) {}
Member Function Documentation
GetState()
template<typename NodeState , NodeUniqueness node_uniqueness>
ControlPathState<NodeState, node_uniqueness> v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::GetState (Node * node) [inline], [protected]
Definition at line 107 of file control-path-state.h.
                                                                    {
    return node_states_.Get(node);
  }
References v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::node_states_.
IsReduced()
template<typename NodeState , NodeUniqueness node_uniqueness>
bool v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::IsReduced (Node * node) [inline], [protected]
Definition at line 110 of file control-path-state.h.
{ return reduced_.Get(node); }
References v8::internal::compiler::NodeAuxData< T, def >::Get(), and v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::reduced_.
TakeStatesFromFirstControl()
template<typename NodeState , NodeUniqueness node_uniqueness>
Reduction v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::TakeStatesFromFirstControl (Node * node) [protected]
Definition at line 218 of file control-path-state.h.
                                                                      {
  // We just propagate the information from the control input (ideally,
  // we would only revisit control uses if there is change).
  Node* input = NodeProperties::GetControlInput(node, 0);
  if (!reduced_.Get(input)) return NoChange();
  return UpdateStates(node, node_states_.Get(input));
}
References v8::internal::compiler::NodeProperties::GetControlInput().
UpdateStates() [1/2]
template<typename NodeState , NodeUniqueness node_uniqueness>
Reduction v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::UpdateStates (Node * state_owner, ControlPathState< NodeState, node_uniqueness > new_state) [protected]
Definition at line 228 of file control-path-state.h.
                                                                               {
  // Only signal that the node has {Changed} if its state has changed.
  bool reduced_changed = reduced_.Set(state_owner, true);
  bool node_states_changed = node_states_.Set(state_owner, new_state);
  if (reduced_changed || node_states_changed) {
    return Changed(state_owner);
  }
  return NoChange();
}
UpdateStates() [2/2]
template<typename NodeState , NodeUniqueness node_uniqueness>
Reduction v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::UpdateStates (Node * state_owner, ControlPathState< NodeState, node_uniqueness > prev_states, Node * additional_node, NodeState additional_state, bool in_new_block) [protected]
Definition at line 241 of file control-path-state.h.
                                                                          {
  if (in_new_block || prev_states.IsEmpty()) {
    prev_states.AddStateInNewBlock(zone_, additional_node, additional_state);
  } else {
    ControlPathState<NodeState, node_uniqueness> original =
        node_states_.Get(state_owner);
    prev_states.AddState(zone_, additional_node, additional_state, original);
  }
  return UpdateStates(state_owner, prev_states);
}
References v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::AddState(), v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::AddStateInNewBlock(), and v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::IsEmpty().
zone()
template<typename NodeState , NodeUniqueness node_uniqueness>
Zone* v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::zone () [inline], [protected]
Definition at line 106 of file control-path-state.h.
{ return zone_; }
References v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::zone_.
Member Data Documentation
node_states_
template<typename NodeState , NodeUniqueness node_uniqueness>
NodeAuxData<ControlPathState<NodeState, node_uniqueness>, ZoneConstruct<ControlPathState<NodeState, node_uniqueness> > > v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::node_states_ [private]
Definition at line 119 of file control-path-state.h.
Referenced by v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::GetState().
reduced_
template<typename NodeState , NodeUniqueness node_uniqueness>
NodeAuxData<bool> v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::reduced_ [private]
Definition at line 120 of file control-path-state.h.
Referenced by v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::IsReduced().
zone_
template<typename NodeState , NodeUniqueness node_uniqueness>
Zone* v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::zone_ [private]
Definition at line 113 of file control-path-state.h.
Referenced by v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::zone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/control-path-state.h