v8::internal::compiler::BundleBuilder Class Reference
#include <register-allocator.h>
Public Member Functions
BundleBuilder (RegisterAllocationData *data)
void BuildBundles ()
Private Member Functions
RegisterAllocationData * data () const
InstructionSequence * code () const
Private Attributes
RegisterAllocationData * data_
int next_bundle_id_ = 0
Detailed Description
Definition at line 1450 of file register-allocator.h.
Constructor & Destructor Documentation
BundleBuilder()
v8::internal::compiler::BundleBuilder::BundleBuilder (RegisterAllocationData * data) [inline], [explicit]
Definition at line 1452 of file register-allocator.h.
: data_(data) {}
Member Function Documentation
BuildBundles()
void v8::internal::compiler::BundleBuilder::BuildBundles ()
Definition at line 2573 of file register-allocator.cc.
                                 {
  TRACE("Build bundles\n");
  // Process the blocks in reverse order.
  for (int block_id = code()->InstructionBlockCount() - 1; block_id >= 0;
       --block_id) {
    InstructionBlock* block =
        code()->InstructionBlockAt(RpoNumber::FromInt(block_id));
    TRACE("Block B%d\n", block_id);
    for (auto phi : block->phis()) {
      TopLevelLiveRange* out_range =
          data()->GetLiveRangeFor(phi->virtual_register());
      LiveRangeBundle* out = out_range->get_bundle();
      if (out == nullptr) {
        out = data()->allocation_zone()->New<LiveRangeBundle>(
            data()->allocation_zone(), next_bundle_id_++);
        out->TryAddRange(out_range);
      }
      TRACE("Processing phi for v%d with %d:%d\n", phi->virtual_register(),
            out_range->TopLevel()->vreg(), out_range->relative_id());
      bool phi_interferes_with_backedge_input = false;
      for (auto input : phi->operands()) {
        TopLevelLiveRange* input_range = data()->GetLiveRangeFor(input);
        TRACE("Input value v%d with range %d:%d\n", input,
              input_range->TopLevel()->vreg(), input_range->relative_id());
        LiveRangeBundle* input_bundle = input_range->get_bundle();
        if (input_bundle != nullptr) {
          TRACE("Merge\n");
          LiveRangeBundle* merged =
              LiveRangeBundle::TryMerge(out, input_bundle);
          if (merged != nullptr) {
            DCHECK_EQ(out_range->get_bundle(), merged);
            DCHECK_EQ(input_range->get_bundle(), merged);
            out = merged;
            TRACE("Merged %d and %d to %d\n", phi->virtual_register(), input,
                  out->id());
          } else if (input_range->Start() > out_range->Start()) {
            // We are only interested in values defined after the phi, because
            // those are values that will go over a back-edge.
            phi_interferes_with_backedge_input = true;
          }
        } else {
          TRACE("Add\n");
          if (out->TryAddRange(input_range)) {
            TRACE("Added %d and %d to %d\n", phi->virtual_register(), input,
                  out->id());
          } else if (input_range->Start() > out_range->Start()) {
            // We are only interested in values defined after the phi, because
            // those are values that will go over a back-edge.
            phi_interferes_with_backedge_input = true;
          }
        }
      }
      // Spilling the phi at the loop header is not beneficial if there is
      // a back-edge with an input for the phi that interferes with the phi's
      // value, because in case that input gets spilled it might introduce
      // a stack-to-stack move at the back-edge.
      if (phi_interferes_with_backedge_input)
        out_range->TopLevel()->set_spilling_at_loop_header_not_beneficial();
    }
    TRACE("Done block B%d\n", block_id);
  }
}
References v8::internal::compiler::RegisterAllocationData::allocation_zone(), code(), data(), DCHECK_EQ, v8::internal::compiler::RpoNumber::FromInt(), v8::internal::compiler::TopLevelLiveRange::get_bundle(), v8::internal::compiler::RegisterAllocationData::GetLiveRangeFor(), v8::internal::compiler::LiveRangeBundle::id(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::Zone::New(), next_bundle_id_, v8::internal::compiler::InstructionBlock::phis(), v8::internal::compiler::LiveRange::relative_id(), v8::internal::compiler::TopLevelLiveRange::set_spilling_at_loop_header_not_beneficial(), v8::internal::compiler::LiveRange::Start(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), v8::internal::compiler::LiveRangeBundle::TryAddRange(), v8::internal::compiler::LiveRangeBundle::TryMerge(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by v8::internal::compiler::turboshaft::BuildLiveRangeBundlesPhase::Run().
code()
InstructionSequence* v8::internal::compiler::BundleBuilder::code () const [inline], [private]
Definition at line 1458 of file register-allocator.h.
{ return data_->code(); }
References v8::internal::compiler::RegisterAllocationData::code(), and data_.
Referenced by BuildBundles().
data()
RegisterAllocationData* v8::internal::compiler::BundleBuilder::data () const [inline], [private]
Definition at line 1457 of file register-allocator.h.
{ return data_; }
References data_.
Referenced by BuildBundles().
Member Data Documentation
data_
RegisterAllocationData* v8::internal::compiler::BundleBuilder::data_ [private]
Definition at line 1459 of file register-allocator.h.
Referenced by code(), and data().
next_bundle_id_
int v8::internal::compiler::BundleBuilder::next_bundle_id_ = 0 [private]
Definition at line 1460 of file register-allocator.h.
Referenced by BuildBundles().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc