v8::internal::CompilationCacheShape Class Reference
#include <compilation-cache-table.h>
Static Public Member Functions
static bool IsMatch (HashTableKey *key, Tagged< Object > value)
static uint32_t Hash (ReadOnlyRoots roots, HashTableKey *key)
static uint32_t RegExpHash (Tagged< String > string, Tagged< Smi > flags)
static uint32_t EvalHash (Tagged< String > source, Tagged< SharedFunctionInfo > shared, LanguageMode language_mode, int position)
static uint32_t HashForObject (ReadOnlyRoots roots, Tagged< Object > object)
Static Public Attributes
static const int kPrefixSize = 0
static const int kEntrySize = 3
static const bool kMatchNeedsHoleCheck = true
static const bool kDoHashSpreading = false
static const uint32_t kHashBits = 0
Additional Inherited Members
Detailed Description
Definition at line 22 of file compilation-cache-table.h.
Member Function Documentation
EvalHash()
uint32_t v8::internal::CompilationCacheShape::EvalHash (Tagged< String > source, Tagged< SharedFunctionInfo > shared, LanguageMode language_mode, int position) [inline], [static]
Definition at line 111 of file compilation-cache-table-inl.h.
                                                       {
  uint32_t hash = source->EnsureHash();
  if (shared->HasSourceCode()) {
    // Instead of using the SharedFunctionInfo pointer in the hash
    // code computation, we use a combination of the hash of the
    // script source code and the start position of the calling scope.
    // We do this to ensure that the cache entries can survive garbage
    // collection.
    Tagged<Script> script(Cast<Script>(shared->script()));
    hash ^= Cast<String>(script->source())->EnsureHash();
  }
  static_assert(LanguageModeSize == 2);
  if (is_strict(language_mode)) hash ^= 0x8000;
  hash += position;
  return hash;
}
References v8::internal::is_strict(), v8::internal::LanguageModeSize, and v8::internal::script.
Referenced by HashForObject().
Hash()
static uint32_t v8::internal::CompilationCacheShape::Hash (ReadOnlyRoots roots, HashTableKey * key) [inline], [static]
Definition at line 28 of file compilation-cache-table.h.
                                                                      {
    return key->Hash();
  }
References v8::internal::key.
HashForObject()
uint32_t v8::internal::CompilationCacheShape::HashForObject (ReadOnlyRoots roots, Tagged< Object > object) [inline], [static]
Definition at line 131 of file compilation-cache-table-inl.h.
                                                                     {
  // Eval: The key field contains the hash as a Number.
  if (IsNumber(object))
    return static_cast<uint32_t>(Object::NumberValue(object));
  // Code: The key field contains the SFI key.
  if (IsSharedFunctionInfo(object)) {
    return Cast<SharedFunctionInfo>(object)->Hash();
  }
  // Script.
  if (IsWeakFixedArray(object)) {
    return static_cast<uint32_t>(Smi::ToInt(
        Cast<WeakFixedArray>(object)->get(ScriptCacheKey::kHash).ToSmi()));
  }
  // RegExpData: The key field (and the value field) contains the RegExpData
  // object.
  if (IsRegExpDataWrapper(object)) {
    Tagged<RegExpDataWrapper> re_wrapper = Cast<RegExpDataWrapper>(object);
    Isolate* isolate = GetIsolateFromWritableObject(re_wrapper);
    Tagged<RegExpData> data = re_wrapper->data(isolate);
    return RegExpHash(data->source(), Smi::FromInt(data->flags()));
  }
  // Eval: See EvalCacheKey::ToHandle for the encoding.
  Tagged<FixedArray> val = Cast<FixedArray>(object);
  DCHECK_EQ(val->map(), roots.fixed_cow_array_map());
  DCHECK_EQ(4, val->length());
  Tagged<String> source = Cast<String>(val->get(1));
  int language_unchecked = Smi::ToInt(val->get(2));
  DCHECK(is_valid_language_mode(language_unchecked));
  LanguageMode language_mode = static_cast<LanguageMode>(language_unchecked);
  int position = Smi::ToInt(val->get(3));
  Tagged<Object> shared = val->get(0);
  return EvalHash(source, Cast<SharedFunctionInfo>(shared), language_mode,
                  position);
}
References v8::internal::DCHECK(), DCHECK_EQ, EvalHash(), v8::internal::Smi::FromInt(), v8::internal::GetIsolateFromWritableObject(), v8::internal::is_valid_language_mode(), v8::internal::IsNumber(), v8::internal::ScriptCacheKey::kHash, v8::internal::Object::NumberValue(), RegExpHash(), and v8::internal::Smi::ToInt().
IsMatch()
static bool v8::internal::CompilationCacheShape::IsMatch (HashTableKey * key, Tagged< Object > value) [inline], [static]
Definition at line 24 of file compilation-cache-table.h.
                                                                      {
    return key->IsMatch(value);
  }
References v8::internal::key, and v8::internal::value.
RegExpHash()
uint32_t v8::internal::CompilationCacheShape::RegExpHash (Tagged< String > string, Tagged< Smi > flags) [inline], [static]
Definition at line 106 of file compilation-cache-table-inl.h.
                                                              {
  return string->EnsureHash() + flags.value();
}
References v8::internal::flags.
Referenced by HashForObject().
Member Data Documentation
kDoHashSpreading
const bool v8::internal::CompilationCacheShape::kDoHashSpreading = false [static]
Definition at line 48 of file compilation-cache-table.h.
kEntrySize
const int v8::internal::CompilationCacheShape::kEntrySize = 3 [static]
Definition at line 46 of file compilation-cache-table.h.
Referenced by v8::internal::CompilationCacheTable::EvalJSFunctionsValueAt(), and v8::internal::CompilationCacheTable::LookupEval().
kHashBits
const uint32_t v8::internal::CompilationCacheShape::kHashBits = 0 [static]
Definition at line 49 of file compilation-cache-table.h.
kMatchNeedsHoleCheck
const bool v8::internal::CompilationCacheShape::kMatchNeedsHoleCheck = true [static]
Definition at line 47 of file compilation-cache-table.h.
kPrefixSize
const int v8::internal::CompilationCacheShape::kPrefixSize = 0 [static]
Definition at line 41 of file compilation-cache-table.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/compilation-cache-table.h
/mnt/V8SourceCode/src/objects/compilation-cache-table-inl.h