v8::internal::compiler::FixedArrayRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< FixedArray > object () const
OptionalObjectRef TryGet (JSHeapBroker *broker, int i) const
Detailed Description
Definition at line 1027 of file heap-refs.h.
Member Function Documentation
object()
IndirectHandle<FixedArray> v8::internal::compiler::FixedArrayRef::object () const
Referenced by v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject().
TryGet()
OptionalObjectRef v8::internal::compiler::FixedArrayRef::TryGet (JSHeapBroker * broker, int i) const
Definition at line 1489 of file heap-refs.cc.
                                                                         {
  Handle<Object> value;
  {
    DisallowGarbageCollection no_gc;
    CHECK_GE(i, 0);
    value = broker->CanonicalPersistentHandle(object()->get(i, kAcquireLoad));
    if (i >= object()->length(kAcquireLoad)) {
      // Right-trimming happened.
      CHECK_LT(i, length());
      return {};
    }
  }
  return TryMakeRef(broker, value);
}
References broker(), CHECK_GE, CHECK_LT, v8::kAcquireLoad, v8::internal::compiler::FixedArrayBaseRef::length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::compiler::TryMakeRef(), and v8::internal::value.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadFixedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc