v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldsRange Class Reference
Public Member Functions
ValueTypeFieldsRange (const Type *type)
ValueTypeFieldIterator begin ()
ValueTypeFieldIterator end ()
Private Attributes
const Type * type_
Detailed Description
Definition at line 77 of file class-debug-reader-generator.cc.
Constructor & Destructor Documentation
ValueTypeFieldsRange()
v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldsRange::ValueTypeFieldsRange (const Type * type) [inline], [explicit]
Definition at line 79 of file class-debug-reader-generator.cc.
: type_(type) {}
Member Function Documentation
begin()
ValueTypeFieldIterator v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldsRange::begin () [inline]
Definition at line 80 of file class-debug-reader-generator.cc.
{ return {type_, 0}; }
end()
ValueTypeFieldIterator v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldsRange::end () [inline]
Definition at line 81 of file class-debug-reader-generator.cc.
                               {
    size_t index = 0;
    std::optional<const StructType*> struct_type = type_->StructSupertype();
    if (struct_type &&
        *struct_type != TypeOracle::GetFloat64OrUndefinedOrHoleType()) {
      index = (*struct_type)->fields().size();
    }
    const Type* type = type_;
    if (const auto type_wrapped_in_smi =
            Type::MatchUnaryGeneric(type_, TypeOracle::GetSmiTaggedGeneric())) {
      type = *type_wrapped_in_smi;
    }
    if (const BitFieldStructType* bit_field_struct_type =
            BitFieldStructType::DynamicCast(type)) {
      index = bit_field_struct_type->fields().size();
    }
    return {type_, index};
  }
References v8::internal::torque::TypeOracle::GetFloat64OrUndefinedOrHoleType(), v8::internal::torque::TypeOracle::GetSmiTaggedGeneric(), v8::internal::index, v8::internal::torque::Type::MatchUnaryGeneric(), and v8::internal::tracing::type.
Member Data Documentation
type_
const Type* v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldsRange::type_ [private]
Definition at line 101 of file class-debug-reader-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/class-debug-reader-generator.cc