v8::internal::ConcurrentMarking::JobTaskMinor Class Reference
Public Member Functions
JobTaskMinor (ConcurrentMarking *concurrent_marking)
~JobTaskMinor () override=default
JobTaskMinor (const JobTaskMinor &)=delete
JobTaskMinor & operator= (const JobTaskMinor &)=delete
void Run (JobDelegate *delegate) override
size_t GetMaxConcurrency (size_t worker_count) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
uint64_t trace_id () const
Private Attributes
ConcurrentMarking * concurrent_marking_
const uint64_t trace_id_
Detailed Description
Definition at line 283 of file concurrent-marking.cc.
Constructor & Destructor Documentation
JobTaskMinor() [1/2]
v8::internal::ConcurrentMarking::JobTaskMinor::JobTaskMinor (ConcurrentMarking * concurrent_marking) [inline], [explicit]
Definition at line 285 of file concurrent-marking.cc.
      : concurrent_marking_(concurrent_marking),
        trace_id_(reinterpret_cast<uint64_t>(concurrent_marking) ^
                  concurrent_marking->heap_->tracer()->CurrentEpoch(
                      GCTracer::Scope::MINOR_MS_MARK_PARALLEL)) {}
 JobTaskMinor()
v8::internal::ConcurrentMarking::JobTaskMinor::~JobTaskMinor () [override], [default]
JobTaskMinor() [2/2]
v8::internal::ConcurrentMarking::JobTaskMinor::JobTaskMinor (const JobTaskMinor &) [delete]
Member Function Documentation
GetMaxConcurrency()
size_t v8::internal::ConcurrentMarking::JobTaskMinor::GetMaxConcurrency (size_t worker_count) const [inline], [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 316 of file concurrent-marking.cc.
                                                               {
    return concurrent_marking_->GetMinorMaxConcurrency(worker_count);
  }
References concurrent_marking_, and v8::internal::ConcurrentMarking::GetMinorMaxConcurrency().
operator=()
JobTaskMinor& v8::internal::ConcurrentMarking::JobTaskMinor::operator= (const JobTaskMinor &) [delete]
Run()
void v8::internal::ConcurrentMarking::JobTaskMinor::Run (JobDelegate * delegate) [inline], [override], [virtual]
Implements v8::JobTask.
Definition at line 296 of file concurrent-marking.cc.
                                           {
    // Set the current isolate such that trusted pointer tables etc are
    // available and the cage base is set correctly for multi-cage mode.
    SetCurrentIsolateScope isolate_scope(concurrent_marking_->heap_->isolate());
    if (delegate->IsJoiningThread()) {
      TRACE_GC_WITH_FLOW(concurrent_marking_->heap_->tracer(),
                         GCTracer::Scope::MINOR_MS_MARK_PARALLEL, trace_id_,
                         TRACE_EVENT_FLAG_FLOW_IN);
      // TRACE_GC is not needed here because the caller opens the right scope.
      concurrent_marking_->RunMinor(delegate);
    } else {
      TRACE_GC_EPOCH_WITH_FLOW(concurrent_marking_->heap_->tracer(),
                               GCTracer::Scope::MINOR_MS_BACKGROUND_MARKING,
                               ThreadKind::kBackground, trace_id_,
                               TRACE_EVENT_FLAG_FLOW_IN);
      concurrent_marking_->RunMinor(delegate);
    }
  }
References concurrent_marking_, v8::internal::ConcurrentMarking::heap_, v8::JobDelegate::IsJoiningThread(), v8::internal::Heap::isolate(), v8::internal::kBackground, v8::internal::ConcurrentMarking::RunMinor(), TRACE_EVENT_FLAG_FLOW_IN, TRACE_GC_EPOCH_WITH_FLOW, TRACE_GC_WITH_FLOW, trace_id_, and v8::internal::Heap::tracer().
trace_id()
uint64_t v8::internal::ConcurrentMarking::JobTaskMinor::trace_id () const [inline]
Definition at line 320 of file concurrent-marking.cc.
{ return trace_id_; }
References trace_id_.
Member Data Documentation
concurrent_marking_
ConcurrentMarking* v8::internal::ConcurrentMarking::JobTaskMinor::concurrent_marking_ [private]
Definition at line 323 of file concurrent-marking.cc.
Referenced by GetMaxConcurrency(), and Run().
trace_id_
const uint64_t v8::internal::ConcurrentMarking::JobTaskMinor::trace_id_ [private]
Definition at line 324 of file concurrent-marking.cc.
Referenced by Run(), and trace_id().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/concurrent-marking.cc