v8::internal::wasm::ConstantExpression Class Reference
#include <constant-expression.h>
Public Types
enum class Kind {
kEmpty
, kI32Const
, kRefNull
, kRefFunc
,
kWireBytesRef
, kLastKind = kWireBytesRef
 }
Public Member Functions
constexpr ConstantExpression ()=default
constexpr Kind kind () const
constexpr bool is_set () const
constexpr uint32_t index () const
constexpr HeapType type () const
constexpr int32_t i32_value () const
V8_EXPORT_PRIVATE WireBytesRef wire_bytes_ref () const
Static Public Member Functions
static constexpr ConstantExpression I32Const (int32_t value)
static constexpr ConstantExpression RefFunc (uint32_t index)
static constexpr ConstantExpression RefNull (HeapType type)
static constexpr ConstantExpression WireBytes (uint32_t offset, uint32_t length)
Private Types
using ValueField = base::BitField< uint32_t, 0, kValueBits, uint64_t >
using OffsetField = base::BitField< uint32_t, 0, kOffsetBits, uint64_t >
using LengthField = OffsetField::Next< uint32_t, kLengthBits >
using KindField = LengthField::Next< Kind, kKindBits >
Private Member Functions
constexpr ConstantExpression (uint64_t bit_field)
Private Attributes
uint64_t bit_field_ = 0
Static Private Attributes
static constexpr int kValueBits = 32
static constexpr int kLengthBits = 30
static constexpr int kOffsetBits = 30
static constexpr int kKindBits = 3
Detailed Description
Definition at line 33 of file constant-expression.h.
Member Typedef Documentation
KindField
using v8::internal::wasm::ConstantExpression::KindField = LengthField::Next<Kind, kKindBits> [private]
Definition at line 97 of file constant-expression.h.
LengthField
using v8::internal::wasm::ConstantExpression::LengthField = OffsetField::Next<uint32_t, kLengthBits> [private]
Definition at line 96 of file constant-expression.h.
OffsetField
using v8::internal::wasm::ConstantExpression::OffsetField = base::BitField<uint32_t, 0, kOffsetBits, uint64_t> [private]
Definition at line 95 of file constant-expression.h.
ValueField
using v8::internal::wasm::ConstantExpression::ValueField = base::BitField<uint32_t, 0, kValueBits, uint64_t> [private]
Definition at line 94 of file constant-expression.h.
Member Enumeration Documentation
Kind
enum v8::internal::wasm::ConstantExpression::Kind [strong]
Enumerator
kEmpty
kI32Const
kRefNull
kRefFunc
kWireBytesRef
kLastKind
Definition at line 35 of file constant-expression.h.
                  {
    kEmpty,
    kI32Const,
    kRefNull,
    kRefFunc,
    kWireBytesRef,
    kLastKind = kWireBytesRef
  };
Constructor & Destructor Documentation
ConstantExpression() [1/2]
constexpr v8::internal::wasm::ConstantExpression::ConstantExpression () [constexpr], [default]
Referenced by I32Const(), RefFunc(), RefNull(), and WireBytes().
ConstantExpression() [2/2]
constexpr v8::internal::wasm::ConstantExpression::ConstantExpression (uint64_t bit_field) [inline], [explicit], [constexpr], [private]
Definition at line 105 of file constant-expression.h.
      : bit_field_(bit_field) {}
Member Function Documentation
i32_value()
constexpr int32_t v8::internal::wasm::ConstantExpression::i32_value () const [inline], [constexpr]
Definition at line 79 of file constant-expression.h.
                                      {
    DCHECK_EQ(kind(), Kind::kI32Const);
    return ValueField::decode(bit_field_);
  }
References bit_field_, DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), kI32Const, and kind().
Referenced by v8::internal::wasm::EvaluateConstantExpression(), and v8::internal::wasm::ModuleDisassembler::PrintInitExpression().
I32Const()
static constexpr ConstantExpression v8::internal::wasm::ConstantExpression::I32Const (int32_t value) [inline], [static], [constexpr]
Definition at line 46 of file constant-expression.h.
                                                              {
    return ConstantExpression(ValueField::encode(value) |
                              KindField::encode(Kind::kI32Const));
  }
References ConstantExpression(), v8::base::BitField< T, shift, size, U >::encode(), kI32Const, and v8::internal::value.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_init_expr().
index()
constexpr uint32_t v8::internal::wasm::ConstantExpression::index () const [inline], [constexpr]
Definition at line 69 of file constant-expression.h.
                                   {
    DCHECK_EQ(kind(), Kind::kRefFunc);
    return ValueField::decode(bit_field_);
  }
References bit_field_, DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), kind(), and kRefFunc.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeGlobalSection(), v8::internal::wasm::EvaluateConstantExpression(), v8::internal::wasm::ModuleDisassembler::PrintInitExpression(), RefFunc(), and v8::internal::wasm::InstanceBuilder::SetTableInitialValues().
is_set()
constexpr bool v8::internal::wasm::ConstantExpression::is_set () const [inline], [constexpr]
Definition at line 67 of file constant-expression.h.
{ return kind() != Kind::kEmpty; }
References kEmpty, and kind().
Referenced by v8::internal::wasm::InstanceBuilder::InitGlobals(), and v8::internal::wasm::InstanceBuilder::SetTableInitialValues().
kind()
constexpr Kind v8::internal::wasm::ConstantExpression::kind () const [inline], [constexpr]
Definition at line 65 of file constant-expression.h.
{ return KindField::decode(bit_field_); }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::wasm::EvaluateConstantExpression(), i32_value(), index(), is_set(), v8::internal::wasm::ModuleDisassembler::PrintInitExpression(), v8::internal::wasm::InstanceBuilder::SetTableInitialValues(), type(), and wire_bytes_ref().
RefFunc()
static constexpr ConstantExpression v8::internal::wasm::ConstantExpression::RefFunc (uint32_t index) [inline], [static], [constexpr]
Definition at line 50 of file constant-expression.h.
                                                              {
    return ConstantExpression(ValueField::encode(index) |
                              KindField::encode(Kind::kRefFunc));
  }
References ConstantExpression(), v8::base::BitField< T, shift, size, U >::encode(), index(), and kRefFunc.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_entry(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), and v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry().
RefNull()
static constexpr ConstantExpression v8::internal::wasm::ConstantExpression::RefNull (HeapType type) [inline], [static], [constexpr]
Definition at line 54 of file constant-expression.h.
                                                             {
    return ConstantExpression(ValueField::encode(type.raw_bit_field()) |
                              KindField::encode(Kind::kRefNull));
  }
References ConstantExpression(), v8::base::BitField< T, shift, size, U >::encode(), kRefNull, v8::internal::wasm::ValueTypeBase::raw_bit_field(), and type().
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), and v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry().
type()
constexpr HeapType v8::internal::wasm::ConstantExpression::type () const [inline], [constexpr]
Definition at line 74 of file constant-expression.h.
                                  {
    DCHECK_EQ(kind(), Kind::kRefNull);
    return HeapType::FromBits(ValueField::decode(bit_field_));
  }
References bit_field_, DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::wasm::HeapType::FromBits(), kind(), and kRefNull.
Referenced by v8::internal::wasm::EvaluateConstantExpression(), v8::internal::wasm::ModuleDisassembler::PrintInitExpression(), and RefNull().
wire_bytes_ref()
WireBytesRef v8::internal::wasm::ConstantExpression::wire_bytes_ref () const
Definition at line 23 of file constant-expression.cc.
                                                      {
  DCHECK_EQ(kind(), Kind::kWireBytesRef);
  return WireBytesRef(OffsetField::decode(bit_field_),
                      LengthField::decode(bit_field_));
}
References bit_field_, DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), kind(), and kWireBytesRef.
Referenced by v8::internal::wasm::EvaluateConstantExpression(), and v8::internal::wasm::ModuleDisassembler::PrintInitExpression().
WireBytes()
static constexpr ConstantExpression v8::internal::wasm::ConstantExpression::WireBytes (uint32_t offset, uint32_t length) [inline], [static], [constexpr]
Definition at line 58 of file constant-expression.h.
                                                                 {
    return ConstantExpression(OffsetField::encode(offset) |
                              LengthField::encode(length) |
                              KindField::encode(Kind::kWireBytesRef));
  }
References ConstantExpression(), v8::base::BitField< T, shift, size, U >::encode(), kWireBytesRef, and v8::internal::length.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_init_expr().
Member Data Documentation
bit_field_
uint64_t v8::internal::wasm::ConstantExpression::bit_field_ = 0 [private]
Definition at line 108 of file constant-expression.h.
Referenced by i32_value(), index(), kind(), type(), and wire_bytes_ref().
kKindBits
constexpr int v8::internal::wasm::ConstantExpression::kKindBits = 3 [static], [constexpr], [private]
Definition at line 90 of file constant-expression.h.
kLengthBits
constexpr int v8::internal::wasm::ConstantExpression::kLengthBits = 30 [static], [constexpr], [private]
Definition at line 88 of file constant-expression.h.
kOffsetBits
constexpr int v8::internal::wasm::ConstantExpression::kOffsetBits = 30 [static], [constexpr], [private]
Definition at line 89 of file constant-expression.h.
kValueBits
constexpr int v8::internal::wasm::ConstantExpression::kValueBits = 32 [static], [constexpr], [private]
Definition at line 87 of file constant-expression.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/constant-expression.h
/mnt/V8SourceCode/src/wasm/constant-expression.cc