v8::internal::compiler::StateValueList Class Reference
#include <instruction.h>
Classes
class iterator
struct Slice
struct Value
Public Member Functions
StateValueList (Zone *zone)
size_t size ()
size_t nested_count ()
void ReserveSize (size_t size)
StateValueList * PushRecursiveField (Zone *zone, size_t id)
StateValueList * PushStringConcat (Zone *zone, size_t id)
void PushArgumentsElements (ArgumentsStateType type)
void PushArgumentsLength ()
void PushRestLength ()
void PushDuplicate (size_t id)
void PushPlain (MachineType type)
void PushOptimizedOut (size_t num=1)
void PushCachedSlice (const Slice &cached)
Slice MakeSlice (size_t values_start)
iterator begin ()
iterator end ()
Private Member Functions
bool HasNestedFieldsAfter (size_t values_start)
Private Attributes
ZoneVector< StateValueDescriptor > fields_
ZoneVector< StateValueList * > nested_
Detailed Description
Definition at line 1415 of file instruction.h.
Constructor & Destructor Documentation
StateValueList()
v8::internal::compiler::StateValueList::StateValueList (Zone * zone) [inline], [explicit]
Definition at line 1417 of file instruction.h.
: fields_(zone), nested_(zone) {}
Member Function Documentation
begin()
iterator v8::internal::compiler::StateValueList::begin () [inline]
Definition at line 1517 of file instruction.h.
{ return iterator(fields_.begin(), nested_.begin()); }
Referenced by v8::internal::compiler::CodeGenerator::TranslateFrameStateDescriptorOperands().
end()
iterator v8::internal::compiler::StateValueList::end () [inline]
Definition at line 1518 of file instruction.h.
{ return iterator(fields_.end(), nested_.end()); }
Referenced by v8::internal::compiler::CodeGenerator::TranslateFrameStateDescriptorOperands().
HasNestedFieldsAfter()
bool v8::internal::compiler::StateValueList::HasNestedFieldsAfter (size_t values_start) [inline], [private]
Definition at line 1521 of file instruction.h.
                                                 {
    auto it = fields_.begin() + values_start;
    for (; it != fields_.end(); it++) {
      if (it->IsNested()) return true;
    }
    return false;
  }
MakeSlice()
Slice v8::internal::compiler::StateValueList::MakeSlice (size_t values_start) [inline]
Definition at line 1511 of file instruction.h.
                                       {
    DCHECK(!HasNestedFieldsAfter(values_start));
    size_t fields_count = fields_.size() - values_start;
    return Slice(fields_.begin() + values_start, fields_count);
  }
References v8::internal::DCHECK().
nested_count()
size_t v8::internal::compiler::StateValueList::nested_count () [inline]
Definition at line 1421 of file instruction.h.
{ return nested_.size(); }
PushArgumentsElements()
void v8::internal::compiler::StateValueList::PushArgumentsElements (ArgumentsStateType type) [inline]
Definition at line 1486 of file instruction.h.
                                                      {
    fields_.push_back(StateValueDescriptor::ArgumentsElements(type));
  }
References v8::internal::compiler::StateValueDescriptor::ArgumentsElements(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor().
PushArgumentsLength()
void v8::internal::compiler::StateValueList::PushArgumentsLength () [inline]
Definition at line 1489 of file instruction.h.
                             {
    fields_.push_back(StateValueDescriptor::ArgumentsLength());
  }
References v8::internal::compiler::StateValueDescriptor::ArgumentsLength().
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor().
PushCachedSlice()
void v8::internal::compiler::StateValueList::PushCachedSlice (const Slice & cached) [inline]
Definition at line 1504 of file instruction.h.
                                            {
    fields_.insert(fields_.end(), cached.start_position,
                   cached.start_position + cached.fields_count);
  }
References v8::internal::compiler::StateValueList::Slice::fields_count, and v8::internal::compiler::StateValueList::Slice::start_position.
Referenced by v8::internal::compiler::InstructionSelector::CachedStateValues::Emit().
PushDuplicate()
void v8::internal::compiler::StateValueList::PushDuplicate (size_t id) [inline]
Definition at line 1495 of file instruction.h.
                                {
    fields_.push_back(StateValueDescriptor::Duplicate(id));
  }
References v8::internal::compiler::StateValueDescriptor::Duplicate().
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor().
PushOptimizedOut()
void v8::internal::compiler::StateValueList::PushOptimizedOut (size_t num = 1) [inline]
Definition at line 1501 of file instruction.h.
                                        {
    fields_.insert(fields_.end(), num, StateValueDescriptor::OptimizedOut());
  }
References v8::internal::compiler::StateValueDescriptor::OptimizedOut().
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor().
PushPlain()
void v8::internal::compiler::StateValueList::PushPlain (MachineType type) [inline]
Definition at line 1498 of file instruction.h.
                                   {
    fields_.push_back(StateValueDescriptor::Plain(type));
  }
References v8::internal::compiler::StateValueDescriptor::Plain(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor().
PushRecursiveField()
StateValueList* v8::internal::compiler::StateValueList::PushRecursiveField (Zone * zone, size_t id) [inline]
Definition at line 1474 of file instruction.h.
                                                            {
    fields_.push_back(StateValueDescriptor::Recursive(id));
    StateValueList* nested = zone->New<StateValueList>(zone);
    nested_.push_back(nested);
    return nested;
  }
References v8::internal::Zone::New(), and v8::internal::compiler::StateValueDescriptor::Recursive().
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor().
PushRestLength()
void v8::internal::compiler::StateValueList::PushRestLength () [inline]
Definition at line 1492 of file instruction.h.
                        {
    fields_.push_back(StateValueDescriptor::RestLength());
  }
References v8::internal::compiler::StateValueDescriptor::RestLength().
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor().
PushStringConcat()
StateValueList* v8::internal::compiler::StateValueList::PushStringConcat (Zone * zone, size_t id) [inline]
Definition at line 1480 of file instruction.h.
                                                          {
    fields_.push_back(StateValueDescriptor::StringConcat(id));
    StateValueList* nested = zone->New<StateValueList>(zone);
    nested_.push_back(nested);
    return nested;
  }
References v8::internal::Zone::New(), and v8::internal::compiler::StateValueDescriptor::StringConcat().
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor().
ReserveSize()
void v8::internal::compiler::StateValueList::ReserveSize (size_t size) [inline]
Definition at line 1472 of file instruction.h.
{ fields_.reserve(size); }
References size().
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor().
size()
size_t v8::internal::compiler::StateValueList::size () [inline]
Definition at line 1419 of file instruction.h.
{ return fields_.size(); }
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), and v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
Member Data Documentation
fields_
ZoneVector<StateValueDescriptor> v8::internal::compiler::StateValueList::fields_ [private]
Definition at line 1529 of file instruction.h.
nested_
ZoneVector<StateValueList*> v8::internal::compiler::StateValueList::nested_ [private]
Definition at line 1530 of file instruction.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/instruction.h