v8::internal::compiler::LoopTree Class Reference
#include <loop-analysis.h>
Classes
class Loop
Public Member Functions
LoopTree (size_t num_nodes, Zone *zone)
Loop * ContainingLoop (Node *node)
bool Contains (const Loop *loop, Node *node)
const ZoneVector< Loop * > & outer_loops () const
ZoneVector< const Loop * > inner_loops () const
int LoopNum (const Loop *loop) const
NodeRange HeaderNodes (const Loop *loop)
Node * HeaderNode (const Loop *loop)
NodeRange BodyNodes (const Loop *loop)
NodeRange ExitNodes (const Loop *loop)
NodeRange LoopNodes (const Loop *loop)
Node * GetLoopControl (const Loop *loop)
Zone * zone () const
Private Member Functions
Loop * NewLoop ()
void SetParent (Loop *parent, Loop *child)
Private Attributes
Zone * zone_
ZoneVector< Loop * > outer_loops_
ZoneVector< Loop > all_loops_
ZoneVector< int > node_to_loop_num_
ZoneVector< Node * > loop_nodes_
Friends
class LoopFinderImpl
Detailed Description
Definition at line 34 of file loop-analysis.h.
Constructor & Destructor Documentation
LoopTree()
v8::internal::compiler::LoopTree::LoopTree (size_t num_nodes, Zone * zone) [inline]
Definition at line 36 of file loop-analysis.h.
      : zone_(zone),
        outer_loops_(zone),
        all_loops_(zone),
        node_to_loop_num_(static_cast<int>(num_nodes), -1, zone),
        loop_nodes_(zone) {}
Member Function Documentation
BodyNodes()
NodeRange v8::internal::compiler::LoopTree::BodyNodes (const Loop * loop) [inline]
Definition at line 121 of file loop-analysis.h.
                                        {
    return NodeRange(&loop_nodes_[0] + loop->body_start_,
                     &loop_nodes_[0] + loop->exits_start_);
  }
References v8::internal::compiler::LoopTree::Loop::body_start_, v8::internal::compiler::LoopTree::Loop::exits_start_, and loop_nodes_.
Referenced by v8::internal::compiler::LoopPeeler::Peel().
ContainingLoop()
Loop* v8::internal::compiler::LoopTree::ContainingLoop (Node * node) [inline]
Definition at line 77 of file loop-analysis.h.
                                   {
    if (node->id() >= node_to_loop_num_.size()) return nullptr;
    int num = node_to_loop_num_[node->id()];
    return num > 0 ? &all_loops_[num - 1] : nullptr;
  }
References all_loops_, v8::internal::compiler::Node::id(), node_to_loop_num_, and v8::internal::ZoneVector< T >::size().
Referenced by Contains().
Contains()
bool v8::internal::compiler::LoopTree::Contains (const Loop * loop, Node * node) [inline]
Definition at line 85 of file loop-analysis.h.
                                              {
    for (Loop* c = ContainingLoop(node); c != nullptr; c = c->parent_) {
      if (c == loop) return true;
    }
    return false;
  }
References ContainingLoop(), and v8::internal::compiler::LoopTree::Loop::parent_.
Referenced by v8::internal::compiler::LoopFinder::HasMarkedExits().
ExitNodes()
NodeRange v8::internal::compiler::LoopTree::ExitNodes (const Loop * loop) [inline]
Definition at line 127 of file loop-analysis.h.
                                        {
    return NodeRange(&loop_nodes_[0] + loop->exits_start_,
                     &loop_nodes_[0] + loop->exits_end_);
  }
References v8::internal::compiler::LoopTree::Loop::exits_end_, v8::internal::compiler::LoopTree::Loop::exits_start_, and loop_nodes_.
Referenced by v8::internal::compiler::LoopPeeler::Peel().
GetLoopControl()
Node* v8::internal::compiler::LoopTree::GetLoopControl (const Loop * loop) [inline]
Definition at line 139 of file loop-analysis.h.
                                         {
    // TODO(turbofan): make the loop control node always first?
    for (Node* node : HeaderNodes(loop)) {
      if (node->opcode() == IrOpcode::kLoop) return node;
    }
    UNREACHABLE();
  }
References HeaderNodes(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::LoopFinder::HasMarkedExits(), and v8::internal::compiler::LoopPeeler::Peel().
HeaderNode()
Node * v8::internal::compiler::LoopTree::HeaderNode (const Loop * loop)
Definition at line 741 of file loop-analysis.cc.
                                           {
  Node* first = *HeaderNodes(loop).begin();
  if (first->opcode() == IrOpcode::kLoop) return first;
  DCHECK(IrOpcode::IsPhiOpcode(first->opcode()));
  Node* header = NodeProperties::GetControlInput(first);
  DCHECK_EQ(IrOpcode::kLoop, header->opcode());
  return header;
}
References v8::internal::compiler::Node::begin(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::IrOpcode::IsPhiOpcode(), and v8::internal::compiler::Node::opcode().
HeaderNodes()
NodeRange v8::internal::compiler::LoopTree::HeaderNodes (const Loop * loop) [inline]
Definition at line 112 of file loop-analysis.h.
                                          {
    return NodeRange(&loop_nodes_[0] + loop->header_start_,
                     &loop_nodes_[0] + loop->body_start_);
  }
References v8::internal::compiler::LoopTree::Loop::body_start_, v8::internal::compiler::LoopTree::Loop::header_start_, and loop_nodes_.
Referenced by GetLoopControl(), v8::internal::compiler::LoopPeeler::Peel(), and v8::internal::compiler::LoopPeeler::PeelInnerLoops().
inner_loops()
ZoneVector<const Loop*> v8::internal::compiler::LoopTree::inner_loops () const [inline]
Definition at line 96 of file loop-analysis.h.
                                              {
    ZoneVector<const Loop*> inner_loops(zone_);
    for (const Loop& loop : all_loops_) {
      if (loop.children().empty()) {
        inner_loops.push_back(&loop);
      }
    }
    return inner_loops;
  }
References all_loops_, and zone_.
LoopNodes()
NodeRange v8::internal::compiler::LoopTree::LoopNodes (const Loop * loop) [inline]
Definition at line 133 of file loop-analysis.h.
                                        {
    return NodeRange(&loop_nodes_[0] + loop->header_start_,
                     &loop_nodes_[0] + loop->exits_end_);
  }
References v8::internal::compiler::LoopTree::Loop::exits_end_, v8::internal::compiler::LoopTree::Loop::header_start_, and loop_nodes_.
Referenced by v8::internal::compiler::LoopFinder::HasMarkedExits().
LoopNum()
int v8::internal::compiler::LoopTree::LoopNum (const Loop * loop) const [inline]
Definition at line 107 of file loop-analysis.h.
                                      {
    return 1 + static_cast<int>(loop - &all_loops_[0]);
  }
References all_loops_.
Referenced by v8::internal::compiler::LoopFinderImpl::SerializeLoop().
NewLoop()
Loop* v8::internal::compiler::LoopTree::NewLoop () [inline], [private]
Definition at line 152 of file loop-analysis.h.
                  {
    all_loops_.push_back(Loop(zone_));
    Loop* result = &all_loops_.back();
    return result;
  }
References all_loops_, v8::base::internal::result, and zone_.
Referenced by v8::internal::compiler::LoopFinderImpl::CreateLoopInfo().
outer_loops()
const ZoneVector<Loop*>& v8::internal::compiler::LoopTree::outer_loops () const [inline]
Definition at line 93 of file loop-analysis.h.
{ return outer_loops_; }
References outer_loops_.
Referenced by v8::internal::compiler::LoopPeeler::PeelInnerLoopsOfTree().
SetParent()
void v8::internal::compiler::LoopTree::SetParent (Loop * parent, Loop * child) [inline], [private]
Definition at line 158 of file loop-analysis.h.
                                            {
    if (parent != nullptr) {
      parent->children_.push_back(child);
      child->parent_ = parent;
      child->depth_ = parent->depth_ + 1;
    } else {
      outer_loops_.push_back(child);
    }
  }
References v8::internal::compiler::LoopTree::Loop::children_, v8::internal::compiler::LoopTree::Loop::depth_, outer_loops_, and v8::internal::compiler::LoopTree::Loop::parent_.
Referenced by v8::internal::compiler::LoopFinderImpl::ConnectLoopTree(), and v8::internal::compiler::LoopFinderImpl::FinishSingleLoop().
zone()
Zone* v8::internal::compiler::LoopTree::zone () const [inline]
Definition at line 147 of file loop-analysis.h.
{ return zone_; }
References zone_.
Friends And Related Function Documentation
LoopFinderImpl
friend class LoopFinderImpl [friend]
Definition at line 150 of file loop-analysis.h.
Member Data Documentation
all_loops_
ZoneVector<Loop> v8::internal::compiler::LoopTree::all_loops_ [private]
Definition at line 170 of file loop-analysis.h.
Referenced by v8::internal::compiler::LoopFinderImpl::ConnectLoopTree(), ContainingLoop(), v8::internal::compiler::LoopFinderImpl::FinishLoopTree(), v8::internal::compiler::LoopFinderImpl::FinishSingleLoop(), inner_loops(), LoopNum(), and NewLoop().
loop_nodes_
ZoneVector<Node*> v8::internal::compiler::LoopTree::loop_nodes_ [private]
Definition at line 172 of file loop-analysis.h.
Referenced by BodyNodes(), ExitNodes(), v8::internal::compiler::LoopFinderImpl::FinishLoopTree(), v8::internal::compiler::LoopFinderImpl::FinishSingleLoop(), HeaderNodes(), LoopNodes(), v8::internal::compiler::LoopFinderImpl::PrintLoop(), and v8::internal::compiler::LoopFinderImpl::SerializeLoop().
node_to_loop_num_
ZoneVector<int> v8::internal::compiler::LoopTree::node_to_loop_num_ [private]
Definition at line 171 of file loop-analysis.h.
Referenced by ContainingLoop(), v8::internal::compiler::LoopFinderImpl::LoopNum(), v8::internal::compiler::LoopFinderImpl::num_nodes(), v8::internal::compiler::LoopFinderImpl::SerializeLoop(), and v8::internal::compiler::LoopFinderImpl::SetLoopMark().
outer_loops_
ZoneVector<Loop*> v8::internal::compiler::LoopTree::outer_loops_ [private]
Definition at line 169 of file loop-analysis.h.
Referenced by v8::internal::compiler::LoopFinderImpl::FinishLoopTree(), outer_loops(), v8::internal::compiler::LoopFinderImpl::Print(), and SetParent().
zone_
Zone* v8::internal::compiler::LoopTree::zone_ [private]
Definition at line 168 of file loop-analysis.h.
Referenced by inner_loops(), NewLoop(), and zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/loop-analysis.h
/mnt/V8SourceCode/src/compiler/loop-analysis.cc