v8::internal::maglev::HasInPrototypeChain Class Reference
#include <maglev-ir.h>
Public Member Functions
HasInPrototypeChain (uint64_t bitfield, compiler::HeapObjectRef prototype)
Input & object ()
compiler::HeapObjectRef prototype ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = FixedInputValueNodeT< 1, HasInPrototypeChain >
Private Attributes
compiler::HeapObjectRef prototype_
Additional Inherited Members
Detailed Description
Definition at line 7679 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::HasInPrototypeChain::Base = FixedInputValueNodeT<1, HasInPrototypeChain> [private]
Definition at line 7681 of file maglev-ir.h.
Constructor & Destructor Documentation
HasInPrototypeChain()
v8::internal::maglev::HasInPrototypeChain::HasInPrototypeChain (uint64_t bitfield, compiler::HeapObjectRef prototype) [inline], [explicit]
Definition at line 7684 of file maglev-ir.h.
      : Base(bitfield), prototype_(prototype) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::HasInPrototypeChain::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::HasInPrototypeChain::MaxCallStackArgs () const
object()
Input& v8::internal::maglev::HasInPrototypeChain::object () [inline]
Definition at line 7695 of file maglev-ir.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::HasInPrototypeChain::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8289 of file maglev-ir.cc.
                                                               {
  os << "(" << *prototype_.object() << ")";
}
References v8::internal::compiler::HeapObjectRef::object(), and prototype_.
prototype()
compiler::HeapObjectRef v8::internal::maglev::HasInPrototypeChain::prototype () [inline]
Definition at line 7697 of file maglev-ir.h.
{ return prototype_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::HasInPrototypeChain::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::HasInPrototypeChain::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 7693 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::HasInPrototypeChain::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::DeferredCall() | OpProperties::CanCallUserCode()
Definition at line 7690 of file maglev-ir.h.
prototype_
compiler::HeapObjectRef v8::internal::maglev::HasInPrototypeChain::prototype_ [private]
Definition at line 7705 of file maglev-ir.h.
Referenced by PrintParams().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc