v8::internal::ExternalReferenceEncoder::Value Class Reference
#include <external-reference-encoder.h>
Public Member Functions
Value (uint32_t raw)
Value ()
bool is_from_api () const
uint32_t index () const
Static Public Member Functions
static uint32_t Encode (uint32_t index, bool is_from_api)
Private Types
using Index = base::BitField< uint32_t, 0, 31 >
using IsFromAPI = base::BitField< bool, 31, 1 >
Private Attributes
uint32_t value_
Detailed Description
Definition at line 21 of file external-reference-encoder.h.
Member Typedef Documentation
Index
using v8::internal::ExternalReferenceEncoder::Value::Index = base::BitField<uint32_t, 0, 31> [private]
Definition at line 33 of file external-reference-encoder.h.
IsFromAPI
using v8::internal::ExternalReferenceEncoder::Value::IsFromAPI = base::BitField<bool, 31, 1> [private]
Definition at line 34 of file external-reference-encoder.h.
Constructor & Destructor Documentation
Value() [1/2]
v8::internal::ExternalReferenceEncoder::Value::Value (uint32_t raw) [inline], [explicit]
Definition at line 23 of file external-reference-encoder.h.
: value_(raw) {}
Value() [2/2]
v8::internal::ExternalReferenceEncoder::Value::Value () [inline]
Definition at line 24 of file external-reference-encoder.h.
: value_(0) {}
Member Function Documentation
Encode()
static uint32_t v8::internal::ExternalReferenceEncoder::Value::Encode (uint32_t index, bool is_from_api) [inline], [static]
Definition at line 25 of file external-reference-encoder.h.
                                                             {
      return Index::encode(index) | IsFromAPI::encode(is_from_api);
    }
References v8::base::BitField< T, shift, size, U >::encode(), index(), and is_from_api().
Referenced by v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::EncodeExternalPointerSlot(), and v8::internal::ExternalReferenceEncoder::ExternalReferenceEncoder().
index()
uint32_t v8::internal::ExternalReferenceEncoder::Value::index () const [inline]
Definition at line 30 of file external-reference-encoder.h.
{ return Index::decode(value_); }
References v8::base::BitField< T, shift, size, U >::decode(), and value_.
Referenced by Encode(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::EncodeExternalPointerSlot(), v8::internal::Serializer::ObjectSerializer::OutputExternalReference(), v8::internal::MacroAssemblerBase::RootRegisterOffsetForExternalReferenceTableEntry(), v8::internal::Serializer::ObjectSerializer::SerializeExternalString(), and v8::internal::StartupSerializer::StartupSerializer().
is_from_api()
bool v8::internal::ExternalReferenceEncoder::Value::is_from_api () const [inline]
Definition at line 29 of file external-reference-encoder.h.
{ return IsFromAPI::decode(value_); }
References v8::base::BitField< T, shift, size, U >::decode(), and value_.
Referenced by Encode(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::EncodeExternalPointerSlot(), v8::internal::Serializer::ObjectSerializer::OutputExternalReference(), v8::internal::MacroAssemblerBase::RootRegisterOffsetForExternalReferenceTableEntry(), and v8::internal::Serializer::ObjectSerializer::SerializeExternalString().
Member Data Documentation
value_
uint32_t v8::internal::ExternalReferenceEncoder::Value::value_ [private]
Definition at line 35 of file external-reference-encoder.h.
Referenced by index(), and is_from_api().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/external-reference-encoder.h