v8::internal::compiler::EffectGraphReducer::Reduction Class Reference
#include <escape-analysis.h>
Public Member Functions
bool value_changed () const
void set_value_changed ()
bool effect_changed () const
void set_effect_changed ()
Private Attributes
bool value_changed_ = false
bool effect_changed_ = false
Detailed Description
Definition at line 31 of file escape-analysis.h.
Member Function Documentation
effect_changed()
bool v8::internal::compiler::EffectGraphReducer::Reduction::effect_changed () const [inline]
Definition at line 35 of file escape-analysis.h.
{ return effect_changed_; }
References effect_changed_.
Referenced by v8::internal::compiler::EffectGraphReducer::ReduceFrom().
set_effect_changed()
void v8::internal::compiler::EffectGraphReducer::Reduction::set_effect_changed () [inline]
Definition at line 36 of file escape-analysis.h.
{ effect_changed_ = true; }
References effect_changed_.
set_value_changed()
void v8::internal::compiler::EffectGraphReducer::Reduction::set_value_changed () [inline]
Definition at line 34 of file escape-analysis.h.
{ value_changed_ = true; }
References value_changed_.
Referenced by v8::internal::compiler::ReduceScope::SetValueChanged().
value_changed()
bool v8::internal::compiler::EffectGraphReducer::Reduction::value_changed () const [inline]
Definition at line 33 of file escape-analysis.h.
{ return value_changed_; }
References value_changed_.
Referenced by v8::internal::compiler::EffectGraphReducer::ReduceFrom().
Member Data Documentation
effect_changed_
bool v8::internal::compiler::EffectGraphReducer::Reduction::effect_changed_ = false [private]
Definition at line 40 of file escape-analysis.h.
Referenced by effect_changed(), and set_effect_changed().
value_changed_
bool v8::internal::compiler::EffectGraphReducer::Reduction::value_changed_ = false [private]
Definition at line 39 of file escape-analysis.h.
Referenced by set_value_changed(), and value_changed().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/escape-analysis.h