v8::internal::compiler::turboshaft::GenericReducerBase< Next > Class Template Reference
#include <assembler.h>
Public Types
using Base = ReducerBaseForwarder< Next >
Public Member Functions
void Bind (Block *block)
bool CanAutoInlineBlocksWithSinglePredecessor () const
void Analyze ()
void RemoveLast (OpIndex index_of_last_operation)
void FixLoopPhi (const PhiOp &input_phi, OpIndex output_index, Block *output_graph_loop)
OpIndex REDUCE() Phi (base::Vector< const OpIndex > inputs, RegisterRepresentation rep)
OpIndex REDUCE() PendingLoopPhi (OpIndex first, RegisterRepresentation rep)
V< None > REDUCE() Goto (Block *destination, bool is_backedge)
V< None > REDUCE() Branch (V< Word32 > condition, Block *if_true, Block *if_false, BranchHint hint)
V< Object > REDUCE() CatchBlockBegin ()
V< None > REDUCE() Switch (V< Word32 > input, base::Vector< SwitchOp::Case > cases, Block *default_case, BranchHint default_hint)
V< Any > REDUCE() Call (V< CallTarget > callee, OptionalV< turboshaft::FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor *descriptor, OpEffects effects)
OpIndex REDUCE() FastApiCall (V< FrameState > frame_state, V< Object > data_argument, V< Context > context, base::Vector< const OpIndex > arguments, const FastApiCallParameters *parameters, base::Vector< const RegisterRepresentation > out_reps)
Private Member Functions
V< None > REDUCE() CheckException (V< Any > throwing_operation, Block *successor, Block *catch_block)
bool CatchIfInCatchScope (OpIndex throwing_operation)
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::GenericReducerBase< Next >
Definition at line 1085 of file assembler.h.
Member Typedef Documentation
Base
template<class Next >
using v8::internal::compiler::turboshaft::GenericReducerBase< Next >::Base = ReducerBaseForwarder<Next>
Definition at line 1089 of file assembler.h.
Member Function Documentation
Analyze()
template<class Next >
void v8::internal::compiler::turboshaft::GenericReducerBase< Next >::Analyze () [inline]
Definition at line 1098 of file assembler.h.
{}
Bind()
template<class Next >
void v8::internal::compiler::turboshaft::GenericReducerBase< Next >::Bind (Block * block) [inline]
Definition at line 1091 of file assembler.h.
{}
Branch()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::GenericReducerBase< Next >::Branch (V< Word32 > condition, Block * if_true, Block * if_false, BranchHint hint) [inline]
Definition at line 1163 of file assembler.h.
                                          {
    // There should never be a good reason to generate a Branch where both the
    // {if_true} and {if_false} are the same Block. If we ever decide to lift
    // this condition, then AddPredecessor and SplitEdge should be updated
    // accordingly.
    DCHECK_NE(if_true, if_false);
    Block* saved_current_block = Asm().current_block();
    V<None> new_opindex =
        Base::ReduceBranch(condition, if_true, if_false, hint);
    Asm().AddPredecessor(saved_current_block, if_true, true);
    Asm().AddPredecessor(saved_current_block, if_false, true);
    return new_opindex;
  }
References DCHECK_NE.
Call()
template<class Next >
V<Any> REDUCE() v8::internal::compiler::turboshaft::GenericReducerBase< Next >::Call (V< CallTarget > callee, OptionalV< turboshaft::FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor * descriptor, OpEffects effects) [inline]
Definition at line 1227 of file assembler.h.
                                                                             {
    V<Any> raw_call =
        Base::ReduceCall(callee, frame_state, arguments, descriptor, effects);
    bool has_catch_block = false;
    if (descriptor->can_throw == CanThrow::kYes) {
      // TODO(nicohartmann@): Unfortunately, we have many descriptors where
      // effects are not set consistently with {can_throw}. We should fix those
      // and reenable this DCHECK.
      // DCHECK(effects.is_required_when_unused());
      effects = effects.RequiredWhenUnused();
      has_catch_block = CatchIfInCatchScope(raw_call);
    }
    return ReduceDidntThrow(raw_call, has_catch_block, &descriptor->out_reps,
                            effects);
  }
CanAutoInlineBlocksWithSinglePredecessor()
template<class Next >
bool v8::internal::compiler::turboshaft::GenericReducerBase< Next >::CanAutoInlineBlocksWithSinglePredecessor () const [inline]
Definition at line 1096 of file assembler.h.
{ return true; }
CatchBlockBegin()
template<class Next >
V<Object> REDUCE() v8::internal::compiler::turboshaft::GenericReducerBase< Next >::CatchBlockBegin () [inline]
Definition at line 1178 of file assembler.h.
                                      {
    Block* current_block = Asm().current_block();
    if (current_block->IsBranchTarget()) {
      DCHECK_EQ(current_block->PredecessorCount(), 1);
      DCHECK_EQ(current_block->LastPredecessor()
                    ->LastOperation(Asm().output_graph())
                    .template Cast<CheckExceptionOp>()
                    .catch_block,
                current_block);
      return Base::ReduceCatchBlockBegin();
    }
    // We are trying to emit a CatchBlockBegin into a block that used to be the
    // catch_block successor but got edge-splitted into a merge. Therefore, we
    // need to emit a phi now and can rely on the predecessors all having a
    // ReduceCatchBlockBegin and nothing else.
    DCHECK(current_block->IsMerge());
    base::SmallVector<OpIndex, 8> phi_inputs;
    for (Block* predecessor : current_block->Predecessors()) {
      V<Object> catch_begin = predecessor->begin();
      DCHECK(Asm().Get(catch_begin).template Is<CatchBlockBeginOp>());
      phi_inputs.push_back(catch_begin);
    }
    return Asm().Phi(base::VectorOf(phi_inputs),
                     RegisterRepresentation::Tagged());
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::Block::IsBranchTarget(), v8::internal::compiler::turboshaft::Block::IsMerge(), v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), v8::internal::compiler::turboshaft::Block::PredecessorCount(), v8::internal::compiler::turboshaft::Block::Predecessors(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), and v8::base::VectorOf().
CatchIfInCatchScope()
template<class Next >
bool v8::internal::compiler::turboshaft::GenericReducerBase< Next >::CatchIfInCatchScope (OpIndex throwing_operation) [inline], [private]
Definition at line 1294 of file assembler.h.
                                                       {
    if (Asm().current_catch_block()) {
      Block* successor = Asm().NewBlock();
      ReduceCheckException(throwing_operation, successor,
                           Asm().current_catch_block());
      Asm().BindReachable(successor);
      return true;
    }
    return false;
  }
CheckException()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::GenericReducerBase< Next >::CheckException (V< Any > throwing_operation, Block * successor, Block * catch_block) [inline], [private]
Definition at line 1281 of file assembler.h.
                                                     {
    // {successor} and {catch_block} should never be the same. AddPredecessor
    // and SplitEdge rely on this.
    DCHECK_NE(successor, catch_block);
    Block* saved_current_block = Asm().current_block();
    V<None> new_opindex =
        Base::ReduceCheckException(throwing_operation, successor, catch_block);
    Asm().AddPredecessor(saved_current_block, successor, true);
    Asm().AddPredecessor(saved_current_block, catch_block, true);
    return new_opindex;
  }
References DCHECK_NE.
FastApiCall()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::GenericReducerBase< Next >::FastApiCall (V< FrameState > frame_state, V< Object > data_argument, V< Context > context, base::Vector< const OpIndex > arguments, const FastApiCallParameters * parameters, base::Vector< const RegisterRepresentation > out_reps) [inline]
Definition at line 1246 of file assembler.h.
                                                         {
    OpIndex raw_call = Base::ReduceFastApiCall(
        frame_state, data_argument, context, arguments, parameters, out_reps);
    bool has_catch_block = CatchIfInCatchScope(raw_call);
    return ReduceDidntThrow(raw_call, has_catch_block,
                            &Asm()
                                 .output_graph()
                                 .Get(raw_call)
                                 .template Cast<FastApiCallOp>()
                                 .out_reps,
                            OpEffects().CanCallAnything());
  }
References v8::internal::compiler::turboshaft::Get().
FixLoopPhi()
template<class Next >
void v8::internal::compiler::turboshaft::GenericReducerBase< Next >::FixLoopPhi (const PhiOp & input_phi, OpIndex output_index, Block * output_graph_loop) [inline]
Definition at line 1108 of file assembler.h.
                                            {
    if (!Asm()
             .output_graph()
             .Get(output_index)
             .template Is<PendingLoopPhiOp>()) {
      return;
    }
    DCHECK(output_graph_loop->Contains(output_index));
    auto& pending_phi = Asm()
                            .output_graph()
                            .Get(output_index)
                            .template Cast<PendingLoopPhiOp>();
#ifdef DEBUG
    DCHECK_EQ(pending_phi.rep, input_phi.rep);
    // The 1st input of the PendingLoopPhi should be the same as the original
    // Phi, except for peeled loops (where it's the same as the 2nd input when
    // computed with the VariableReducer Snapshot right before the loop was
    // emitted).
    DCHECK_IMPLIES(
        pending_phi.first() != Asm().MapToNewGraph(input_phi.input(0)),
        output_graph_loop->has_peeled_iteration());
#endif
    Asm().output_graph().template Replace<PhiOp>(
        output_index,
        base::VectorOf<OpIndex>(
            {pending_phi.first(), Asm().MapToNewGraph(input_phi.input(1))}),
        input_phi.rep);
  }
References v8::internal::compiler::turboshaft::Block::Contains(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::OperationT< Derived >::input(), and v8::internal::compiler::turboshaft::PhiOp::rep.
Goto()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::GenericReducerBase< Next >::Goto (Block * destination, bool is_backedge) [inline]
Definition at line 1150 of file assembler.h.
                                                             {
    // Calling Base::Goto will call Emit<Goto>, which will call FinalizeBlock,
    // which will reset {current_block_}. We thus save {current_block_} before
    // calling Base::Goto, as we'll need it for AddPredecessor. Note also that
    // AddPredecessor might introduce some new blocks/operations if it needs to
    // split an edge, which means that it has to run after Base::Goto
    // (otherwise, the current Goto could be inserted in the wrong block).
    Block* saved_current_block = Asm().current_block();
    V<None> new_opindex = Base::ReduceGoto(destination, is_backedge);
    Asm().AddPredecessor(saved_current_block, destination, false);
    return new_opindex;
  }
PendingLoopPhi()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::GenericReducerBase< Next >::PendingLoopPhi (OpIndex first, RegisterRepresentation rep) [inline]
Definition at line 1145 of file assembler.h.
                                                                            {
    DCHECK(Asm().current_block()->IsLoop());
    return Base::ReducePendingLoopPhi(first, rep);
  }
References v8::internal::DCHECK().
Phi()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::GenericReducerBase< Next >::Phi (base::Vector< const OpIndex > inputs, RegisterRepresentation rep) [inline]
Definition at line 1138 of file assembler.h.
                                                  {
    DCHECK(Asm().current_block()->IsMerge() &&
           inputs.size() == Asm().current_block()->Predecessors().size());
    return Base::ReducePhi(inputs, rep);
  }
References v8::internal::DCHECK(), and size().
RemoveLast()
template<class Next >
void v8::internal::compiler::turboshaft::GenericReducerBase< Next >::RemoveLast (OpIndex index_of_last_operation) [inline]
Definition at line 1104 of file assembler.h.
                                                   {
    Asm().output_graph().RemoveLast();
  }
Switch()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::GenericReducerBase< Next >::Switch (V< Word32 > input, base::Vector< SwitchOp::Case > cases, Block * default_case, BranchHint default_hint) [inline]
Definition at line 1204 of file assembler.h.
                                                                       {
#ifdef DEBUG
    // Making sure that all cases and {default_case} are different. If we ever
    // decide to lift this condition, then AddPredecessor and SplitEdge should
    // be updated accordingly.
    std::unordered_set<Block*> seen;
    seen.insert(default_case);
    for (auto switch_case : cases) {
      DCHECK_EQ(seen.count(switch_case.destination), 0);
      seen.insert(switch_case.destination);
    }
#endif
    Block* saved_current_block = Asm().current_block();
    V<None> new_opindex =
        Base::ReduceSwitch(input, cases, default_case, default_hint);
    for (SwitchOp::Case c : cases) {
      Asm().AddPredecessor(saved_current_block, c.destination, true);
    }
    Asm().AddPredecessor(saved_current_block, default_case, true);
    return new_opindex;
  }
References DCHECK_EQ.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/assembler.h