v8::CpuProfiler Class Reference
Interface for controlling CPU profiling.
#include <v8-profiler.h>
Public Member Functions
void Dispose ()
Disposes the CPU profiler object.
void SetSamplingInterval (int us)
Changes default CPU profiler sampling interval to the specified number of microseconds.
void SetUsePreciseSampling (bool)
Sets whether or not the profiler should prioritize consistency of sample periodicity on Windows.
CpuProfilingResult Start (CpuProfilingOptions options, std::unique_ptr< DiscardedSamplesDelegate > delegate=nullptr)
Starts collecting a CPU profile.
CpuProfilingResult Start (Local< String > title, CpuProfilingOptions options, std::unique_ptr< DiscardedSamplesDelegate > delegate=nullptr)
Starts collecting a CPU profile.
CpuProfilingResult Start (Local< String > title, CpuProfilingMode mode, bool record_samples=false, unsigned max_samples=CpuProfilingOptions::kNoSampleLimit)
Starts profiling with the same semantics as above, except with expanded parameters.
CpuProfilingResult Start (Local< String > title, bool record_samples=false)
The same as StartProfiling above, but the CpuProfilingMode defaults to kLeafNodeLineNumbers mode, which was the previous default behavior of the profiler.
CpuProfilingStatus StartProfiling (Local< String > title, CpuProfilingOptions options, std::unique_ptr< DiscardedSamplesDelegate > delegate=nullptr)
Starts collecting a CPU profile.
CpuProfilingStatus StartProfiling (Local< String > title, CpuProfilingMode mode, bool record_samples=false, unsigned max_samples=CpuProfilingOptions::kNoSampleLimit)
Starts profiling with the same semantics as above, except with expanded parameters.
CpuProfilingStatus StartProfiling (Local< String > title, bool record_samples=false)
The same as StartProfiling above, but the CpuProfilingMode defaults to kLeafNodeLineNumbers mode, which was the previous default behavior of the profiler.
CpuProfile * Stop (ProfilerId id)
Stops collecting CPU profile with a given id and returns it.
CpuProfile * StopProfiling (Local< String > title)
Stops collecting CPU profile with a given title and returns it.
Static Public Member Functions
static CpuProfiler * New (Isolate *isolate, CpuProfilingNamingMode=kDebugNaming, CpuProfilingLoggingMode=kLazyLogging)
Creates a new CPU profiler for the |isolate|.
static void CollectSample (Isolate *isolate, const std::optional< uint64_t > trace_id=std::nullopt)
Synchronously collect current stack sample in all profilers attached to the |isolate|.
static void UseDetailedSourcePositionsForProfiling (Isolate *isolate)
Generate more detailed source positions to code objects.
Private Member Functions
CpuProfiler ()
~CpuProfiler ()
CpuProfiler (const CpuProfiler &)
CpuProfiler & operator= (const CpuProfiler &)
Detailed Description
Interface for controlling CPU profiling.
Instance of the profiler can be created using v8::CpuProfiler::New method.
Definition at line 410 of file v8-profiler.h.
Constructor & Destructor Documentation
CpuProfiler() [1/2]
v8::CpuProfiler::CpuProfiler () [private]
 CpuProfiler()
v8::CpuProfiler::~CpuProfiler () [private]
CpuProfiler() [2/2]
v8::CpuProfiler::CpuProfiler (const CpuProfiler &) [private]
Member Function Documentation
CollectSample()
void v8::CpuProfiler::CollectSample (Isolate * isolate, const std::optional< uint64_t > trace_id = std::nullopt) [static]
Synchronously collect current stack sample in all profilers attached to the |isolate|.
The call does not affect number of ticks recorded for the current top node. |trace_id| is an optional identifier set to the collected sample. this is useful to associate the sample with a trace event.
Definition at line 11444 of file api.cc.
                                                                      {
  i::CpuProfiler::CollectSample(reinterpret_cast<i::Isolate*>(v8_isolate),
                                trace_id);
}
References v8::internal::CpuProfiler::CollectSample().
Referenced by v8::Shell::ProfilerTriggerSample().
Dispose()
void v8::CpuProfiler::Dispose ()
Disposes the CPU profiler object.
Definition at line 11439 of file api.cc.
{ delete reinterpret_cast<i::CpuProfiler*>(this); }
Referenced by v8::D8Console::DisposeProfiler(), v8::Shell::Main(), v8_inspector::V8ProfilerAgentImpl::stopProfiling(), and v8_inspector::V8ProfilerAgentImpl::~V8ProfilerAgentImpl().
New()
CpuProfiler * v8::CpuProfiler::New (Isolate * isolate, CpuProfilingNamingMode naming_mode = kDebugNaming, CpuProfilingLoggingMode logging_mode = kLazyLogging) [static]
Creates a new CPU profiler for the |isolate|.
The isolate must be initialized. The profiler object must be disposed after use by calling |Dispose| method.
Definition at line 11411 of file api.cc.
                                                                    {
  return reinterpret_cast<CpuProfiler*>(new i::CpuProfiler(
      reinterpret_cast<i::Isolate*>(v8_isolate), naming_mode, logging_mode));
}
Referenced by v8::Shell::Main(), v8::D8Console::Profile(), and v8_inspector::V8ProfilerAgentImpl::startProfiling().
operator=()
CpuProfiler& v8::CpuProfiler::operator= (const CpuProfiler &) [private]
SetSamplingInterval()
void v8::CpuProfiler::SetSamplingInterval (int us)
Changes default CPU profiler sampling interval to the specified number of microseconds.
Default interval is 1000us. This method must be called when there are no profiles being recorded.
Definition at line 11450 of file api.cc.
                                            {
  DCHECK_GE(us, 0);
  return reinterpret_cast<i::CpuProfiler*>(this)->set_sampling_interval(
      base::TimeDelta::FromMicroseconds(us));
}
References DCHECK_GE, and v8::base::TimeDelta::FromMicroseconds().
Referenced by v8_inspector::V8ProfilerAgentImpl::startProfiling().
SetUsePreciseSampling()
void v8::CpuProfiler::SetUsePreciseSampling (bool use_precise_sampling)
Sets whether or not the profiler should prioritize consistency of sample periodicity on Windows.
Disabling this can greatly reduce CPU usage, but may result in greater variance in sample timings from the platform's scheduler. Defaults to enabled. This method must be called when there are no profiles being recorded.
Definition at line 11456 of file api.cc.
                                                                 {
  reinterpret_cast<i::CpuProfiler*>(this)->set_use_precise_sampling(
      use_precise_sampling);
}
Start() [1/4]
CpuProfilingResult v8::CpuProfiler::Start (CpuProfilingOptions options, std::unique_ptr< DiscardedSamplesDelegate > delegate = nullptr)
Starts collecting a CPU profile.
Several profiles may be collected at once. Generates an anonymous profiler, without a String identifier.
Definition at line 11461 of file api.cc.
                                                      {
  return reinterpret_cast<i::CpuProfiler*>(this)->StartProfiling(
      std::move(options), std::move(delegate));
}
References StartProfiling().
Referenced by StartProfiling().
Start() [2/4]
CpuProfilingResult v8::CpuProfiler::Start (Local< String > title, bool record_samples = false)
The same as StartProfiling above, but the CpuProfilingMode defaults to kLeafNodeLineNumbers mode, which was the previous default behavior of the profiler.
Definition at line 11476 of file api.cc.
                                                           {
  CpuProfilingOptions options(
      kLeafNodeLineNumbers,
      record_samples ? CpuProfilingOptions::kNoSampleLimit : 0);
  return reinterpret_cast<i::CpuProfiler*>(this)->StartProfiling(
      *Utils::OpenDirectHandle(*title), std::move(options));
}
References v8::kLeafNodeLineNumbers, v8::CpuProfilingOptions::kNoSampleLimit, v8::Utils::OpenDirectHandle(), and StartProfiling().
Start() [3/4]
CpuProfilingResult v8::CpuProfiler::Start (Local< String > title, CpuProfilingMode mode, bool record_samples = false, unsigned max_samples = CpuProfilingOptions::kNoSampleLimit)
Starts profiling with the same semantics as above, except with expanded parameters.
|record_samples| parameter controls whether individual samples should be recorded in addition to the aggregated tree.
|max_samples| controls the maximum number of samples that should be recorded by the profiler. Samples obtained after this limit will be discarded.
Definition at line 11485 of file api.cc.
                                                            {
  CpuProfilingOptions options(mode, record_samples ? max_samples : 0);
  return reinterpret_cast<i::CpuProfiler*>(this)->StartProfiling(
      *Utils::OpenDirectHandle(*title), std::move(options));
}
References mode(), v8::Utils::OpenDirectHandle(), and StartProfiling().
Start() [4/4]
CpuProfilingResult v8::CpuProfiler::Start (Local< String > title, CpuProfilingOptions options, std::unique_ptr< DiscardedSamplesDelegate > delegate = nullptr)
Starts collecting a CPU profile.
Title may be an empty string. Several profiles may be collected at once. Attempts to start collecting several profiles with the same title are silently ignored.
Definition at line 11468 of file api.cc.
                                                      {
  return reinterpret_cast<i::CpuProfiler*>(this)->StartProfiling(
      *Utils::OpenDirectHandle(*title), std::move(options),
      std::move(delegate));
}
References v8::Utils::OpenDirectHandle(), and StartProfiling().
StartProfiling() [1/3]
CpuProfilingStatus v8::CpuProfiler::StartProfiling (Local< String > title, bool record_samples = false)
The same as StartProfiling above, but the CpuProfilingMode defaults to kLeafNodeLineNumbers mode, which was the previous default behavior of the profiler.
Definition at line 11500 of file api.cc.
                                                                    {
  return Start(title, record_samples).status;
}
References Start(), and v8::CpuProfilingResult::status.
StartProfiling() [2/3]
CpuProfilingStatus v8::CpuProfiler::StartProfiling (Local< String > title, CpuProfilingMode mode, bool record_samples = false, unsigned max_samples = CpuProfilingOptions::kNoSampleLimit)
Starts profiling with the same semantics as above, except with expanded parameters.
|record_samples| parameter controls whether individual samples should be recorded in addition to the aggregated tree.
|max_samples| controls the maximum number of samples that should be recorded by the profiler. Samples obtained after this limit will be discarded.
Definition at line 11505 of file api.cc.
                                                                     {
  return Start(title, mode, record_samples, max_samples).status;
}
References mode(), Start(), and v8::CpuProfilingResult::status.
StartProfiling() [3/3]
CpuProfilingStatus v8::CpuProfiler::StartProfiling (Local< String > title, CpuProfilingOptions options, std::unique_ptr< DiscardedSamplesDelegate > delegate = nullptr)
Starts collecting a CPU profile.
Title may be an empty string. Several profiles may be collected at once. Attempts to start collecting several profiles with the same title are silently ignored.
Definition at line 11494 of file api.cc.
                                                      {
  return Start(title, std::move(options), std::move(delegate)).status;
}
References Start(), and v8::CpuProfilingResult::status.
Referenced by v8::Shell::Main(), v8::D8Console::Profile(), Start(), and v8_inspector::V8ProfilerAgentImpl::startProfiling().
Stop()
CpuProfile * v8::CpuProfiler::Stop (ProfilerId id)
Stops collecting CPU profile with a given id and returns it.
Definition at line 11518 of file api.cc.
                                           {
  return reinterpret_cast<CpuProfile*>(
      reinterpret_cast<i::CpuProfiler*>(this)->StopProfiling(id));
}
References StopProfiling().
StopProfiling()
CpuProfile * v8::CpuProfiler::StopProfiling (Local< String > title)
Stops collecting CPU profile with a given title and returns it.
If the title given is empty, finishes the last profile started.
Definition at line 11512 of file api.cc.
                                                          {
  return reinterpret_cast<CpuProfile*>(
      reinterpret_cast<i::CpuProfiler*>(this)->StopProfiling(
          *Utils::OpenDirectHandle(*title)));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8::D8Console::DisposeProfiler(), v8::Shell::Main(), v8::D8Console::ProfileEnd(), Stop(), and v8_inspector::V8ProfilerAgentImpl::stopProfiling().
UseDetailedSourcePositionsForProfiling()
void v8::CpuProfiler::UseDetailedSourcePositionsForProfiling (Isolate * isolate) [static]
Generate more detailed source positions to code objects.
This results in better results when mapping profiling samples to script source.
Definition at line 11523 of file api.cc.
                                                                            {
  reinterpret_cast<i::Isolate*>(v8_isolate)
      ->SetDetailedSourcePositionsForProfiling(true);
}
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-profiler.h
/mnt/V8SourceCode/src/api/api.cc