v8::internal::StackHandlerIterator Class Reference
Public Member Functions
StackHandlerIterator (const StackFrame *frame, StackHandler *handler)
StackHandler * handler () const
bool done ()
void Advance ()
Private Attributes
const Address limit_
StackHandler * handler_
Detailed Description
Definition at line 92 of file frames.cc.
Constructor & Destructor Documentation
StackHandlerIterator()
v8::internal::StackHandlerIterator::StackHandlerIterator (const StackFrame * frame, StackHandler * handler) [inline]
Definition at line 94 of file frames.cc.
      : limit_(frame->fp()), handler_(handler) {
#if V8_ENABLE_WEBASSEMBLY
#if !V8_ENABLE_DRUMBRAKE && !USE_SIMULATOR
    // Make sure the handler has already been unwound to this frame. With stack
    // switching this is not equivalent to the inequality below, because the
    // frame and the handler could be in different stacks.
    DCHECK_IMPLIES(frame->isolate()->wasm_stacks().empty(),
                   frame->InFastCCall() || frame->sp() <= AddressOf(handler));
#endif // !V8_ENABLE_DRUMBRAKE || !USE_SIMULATOR
    // For CWasmEntry frames, the handler was registered by the last C++
    // frame (Execution::CallWasm), so even though its address is already
    // beyond the limit, we know we always want to unwind one handler.
    if (frame->is_c_wasm_entry()) {
      handler_ = handler_->next();
#if V8_ENABLE_DRUMBRAKE
    // Do the same for GenericWasmToJsInterpreterWrapper frames.
    } else if (v8_flags.wasm_jitless && frame->is_wasm_to_js()) {
      handler_ = handler_->next();
#ifdef USE_SIMULATOR
      // If we are running in the simulator, the handler_ address here will
      // refer to the 'actual' stack, not to the 'simulated' stack, so we need
      // to fix 'limit_' to make sure that the StackHandlerIterator won't skip
      // any handler.
      limit_ = 0;
#endif // USE_SIMULATOR
#endif // V8_ENABLE_DRUMBRAKE
    }
#else
    // Make sure the handler has already been unwound to this frame.
    DCHECK_LE(frame->sp(), AddressOf(handler));
#endif // V8_ENABLE_WEBASSEMBLY
  }
References v8::internal::anonymous_namespace{frames.cc}::AddressOf(), DCHECK_IMPLIES, DCHECK_LE, handler(), handler_, v8::internal::StackFrame::InFastCCall(), v8::internal::StackFrame::isolate(), limit_, v8::internal::StackHandler::next(), v8::internal::StackFrame::sp(), and v8::internal::v8_flags.
Member Function Documentation
Advance()
void v8::internal::StackHandlerIterator::Advance () [inline]
Definition at line 132 of file frames.cc.
                 {
    DCHECK(!done());
    handler_ = handler_->next();
  }
References v8::internal::DCHECK(), done(), handler_, and v8::internal::StackHandler::next().
Referenced by v8::internal::StackFrameIterator::Advance().
done()
bool v8::internal::StackHandlerIterator::done () [inline]
Definition at line 131 of file frames.cc.
{ return handler_ == nullptr || AddressOf(handler_) > limit_; }
References v8::internal::anonymous_namespace{frames.cc}::AddressOf(), handler_, and limit_.
Referenced by Advance(), and v8::internal::StackFrameIterator::Advance().
handler()
StackHandler* v8::internal::StackHandlerIterator::handler () const [inline]
Definition at line 129 of file frames.cc.
{ return handler_; }
References handler_.
Referenced by v8::internal::StackFrameIterator::Advance(), and StackHandlerIterator().
Member Data Documentation
handler_
StackHandler* v8::internal::StackHandlerIterator::handler_ [private]
Definition at line 144 of file frames.cc.
Referenced by Advance(), done(), handler(), and StackHandlerIterator().
limit_
const Address v8::internal::StackHandlerIterator::limit_ [private]
Definition at line 141 of file frames.cc.
Referenced by done(), and StackHandlerIterator().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/execution/frames.cc