v8::internal::compiler::SingleValueFeedback< T, K > Class Template Reference
#include <processed-feedback.h>
Public Member Functions
SingleValueFeedback (T value, FeedbackSlotKind slot_kind)
T value () const
Private Attributes
T const value_
Additional Inherited Members
Detailed Description
template<class T, ProcessedFeedback::Kind K>
class v8::internal::compiler::SingleValueFeedback< T, K >
Definition at line 226 of file processed-feedback.h.
Constructor & Destructor Documentation
SingleValueFeedback()
template<class T , ProcessedFeedback::Kind K>
v8::internal::compiler::SingleValueFeedback< T, K >::SingleValueFeedback (T value, FeedbackSlotKind slot_kind) [inline], [explicit]
Definition at line 228 of file processed-feedback.h.
      : ProcessedFeedback(K, slot_kind), value_(value) {
    DCHECK(
        (K == kBinaryOperation && slot_kind == FeedbackSlotKind::kBinaryOp) ||
        (K == kBinaryOperation &&
         slot_kind == FeedbackSlotKind::kStringAddAndInternalize) ||
        (K == kTypeOf && slot_kind == FeedbackSlotKind::kTypeOf) ||
        (K == kCompareOperation && slot_kind == FeedbackSlotKind::kCompareOp) ||
        (K == kForIn && slot_kind == FeedbackSlotKind::kForIn) ||
        (K == kInstanceOf && slot_kind == FeedbackSlotKind::kInstanceOf) ||
        ((K == kLiteral || K == kRegExpLiteral || K == kTemplateObject) &&
         slot_kind == FeedbackSlotKind::kLiteral));
  }
References v8::internal::DCHECK(), v8::internal::K, v8::internal::kBinaryOp, v8::internal::compiler::ProcessedFeedback::kBinaryOperation, v8::internal::kCompareOp, v8::internal::compiler::ProcessedFeedback::kCompareOperation, v8::internal::compiler::ProcessedFeedback::kForIn, v8::internal::kForIn, v8::internal::compiler::ProcessedFeedback::kInstanceOf, v8::internal::kInstanceOf, v8::internal::compiler::ProcessedFeedback::kLiteral, v8::internal::kLiteral, v8::internal::compiler::ProcessedFeedback::kRegExpLiteral, v8::internal::kStringAddAndInternalize, v8::internal::compiler::ProcessedFeedback::kTemplateObject, v8::internal::compiler::ProcessedFeedback::kTypeOf, v8::internal::kTypeOf, and v8::internal::compiler::ProcessedFeedback::slot_kind().
Member Function Documentation
value()
template<class T , ProcessedFeedback::Kind K>
T v8::internal::compiler::SingleValueFeedback< T, K >::value () const [inline]
Definition at line 242 of file processed-feedback.h.
{ return value_; }
References v8::internal::compiler::SingleValueFeedback< T, K >::value_.
Referenced by v8::internal::compiler::JSHeapBroker::GetFeedbackForBinaryOperation(), v8::internal::compiler::JSHeapBroker::GetFeedbackForCompareOperation(), v8::internal::compiler::JSHeapBroker::GetFeedbackForForIn(), v8::internal::compiler::JSHeapBroker::GetFeedbackForTypeOf(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralArrayOrObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralRegExp(), v8::internal::compiler::JSCreateLowering::ReduceJSGetTemplateObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastCreateObjectOrArrayLiteral(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOfWithFeedback().
Member Data Documentation
value_
template<class T , ProcessedFeedback::Kind K>
T const v8::internal::compiler::SingleValueFeedback< T, K >::value_ [private]
Definition at line 245 of file processed-feedback.h.
Referenced by v8::internal::compiler::SingleValueFeedback< T, K >::value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/processed-feedback.h