v8::PerIsolateData Class Reference
#include <d8.h>
Classes
class ExplicitRealmScope
class RealmScope
Public Member Functions
PerIsolateData (Isolate *isolate)
~PerIsolateData ()
AsyncHooks * GetAsyncHooks ()
void RemoveUnhandledPromise (Local< Promise > promise)
void AddUnhandledPromise (Local< Promise > promise, Local< Message > message, Local< Value > exception)
int HandleUnhandledPromiseRejections ()
void AddDynamicImportData (DynamicImportData *)
void DeleteDynamicImportData (DynamicImportData *)
Local< FunctionTemplate > GetTestApiObjectCtor () const
void SetTestApiObjectCtor (Local< FunctionTemplate > ctor)
Local< FunctionTemplate > GetDomNodeCtor () const
void SetDomNodeCtor (Local< FunctionTemplate > ctor)
bool HasRunningSubscribedWorkers ()
void RegisterWorker (std::shared_ptr< Worker > worker)
void SubscribeWorkerOnMessage (const std::shared_ptr< Worker > &worker, Local< Context > context, Local< Function > callback)
std::pair< Local< Context >, Local< Function > > GetWorkerOnMessage (const std::shared_ptr< Worker > &worker) const
void UnregisterWorker (const std::shared_ptr< Worker > &worker)
Static Public Member Functions
static PerIsolateData * Get (Isolate *isolate)
Private Member Functions
int RealmIndexOrThrow (const v8::FunctionCallbackInfo< v8::Value > &info, int arg_offset)
int RealmFind (Local< Context > context)
Private Attributes
Isolate * isolate_
int realm_count_
int realm_current_
int realm_switch_
Global< Context > * realms_
Global< Value > realm_shared_
bool ignore_unhandled_promises_
std::vector< std::tuple< Global< Promise >, Global< Message >, Global< Value > > > unhandled_promises_
AsyncHooks * async_hooks_wrapper_
Global< FunctionTemplate > test_api_object_ctor_
Global< FunctionTemplate > dom_node_ctor_
std::set< std::shared_ptr< Worker > > registered_workers_
std::map< std::shared_ptr< Worker >, std::pair< Global< Context >, Global< Function > > > worker_message_callbacks_
Friends
class Shell
class RealmScope
Detailed Description
Definition at line 294 of file d8.h.
Constructor & Destructor Documentation
PerIsolateData()
v8::PerIsolateData::PerIsolateData (Isolate * isolate) [explicit]
Definition at line 1931 of file d8.cc.
    : isolate_(isolate), realms_(nullptr) {
  isolate->SetData(0, this);
  if (i::v8_flags.expose_async_hooks) {
    async_hooks_wrapper_ = new AsyncHooks(isolate);
  }
  ignore_unhandled_promises_ = false;
}
References async_hooks_wrapper_, ignore_unhandled_promises_, v8::Isolate::SetData(), and v8::internal::v8_flags.
 PerIsolateData()
v8::PerIsolateData::~PerIsolateData ()
Definition at line 1940 of file d8.cc.
                                {
  isolate_->SetData(0, nullptr); // Not really needed, just to be sure...
  if (i::v8_flags.expose_async_hooks) {
    delete async_hooks_wrapper_; // This uses the isolate
  }
#if defined(LEAK_SANITIZER)
  for (DynamicImportData* data : import_data_) {
    delete data;
  }
#endif
}
References async_hooks_wrapper_, isolate_, v8::Isolate::SetData(), and v8::internal::v8_flags.
Member Function Documentation
AddDynamicImportData()
void v8::PerIsolateData::AddDynamicImportData (DynamicImportData * data)
Definition at line 1994 of file d8.cc.
                                                                 {
#if defined(LEAK_SANITIZER)
  import_data_.insert(data);
#endif
}
Referenced by v8::Shell::HostImportModuleWithPhaseDynamically().
AddUnhandledPromise()
void v8::PerIsolateData::AddUnhandledPromise (Local< Promise > promise, Local< Message > message, Local< Value > exception)
Definition at line 1965 of file d8.cc.
                                                                 {
  if (ignore_unhandled_promises_) return;
  DCHECK_EQ(Isolate::GetCurrent(), isolate_);
  unhandled_promises_.emplace_back(v8::Global<v8::Promise>(isolate_, promise),
                                   v8::Global<v8::Message>(isolate_, message),
                                   v8::Global<v8::Value>(isolate_, exception));
}
References DCHECK_EQ, v8::Isolate::GetCurrent(), ignore_unhandled_promises_, isolate_, and unhandled_promises_.
Referenced by v8::Shell::PromiseRejectCallback().
DeleteDynamicImportData()
void v8::PerIsolateData::DeleteDynamicImportData (DynamicImportData * data)
Definition at line 1999 of file d8.cc.
                                                                    {
#if defined(LEAK_SANITIZER)
  import_data_.erase(data);
#endif
  delete data;
}
Referenced by v8::Shell::DoHostImportModuleDynamically().
Get()
static PerIsolateData* v8::PerIsolateData::Get (Isolate * isolate) [inline], [static]
Definition at line 300 of file d8.h.
                                                      {
    return reinterpret_cast<PerIsolateData*>(isolate->GetData(0));
  }
References v8::Isolate::GetData().
Referenced by v8::Shell::AsyncHooksCreateHook(), v8::Shell::AsyncHooksExecutionAsyncId(), v8::Shell::AsyncHooksTriggerAsyncId(), v8::Shell::CompleteMessageLoop(), v8::Shell::CreateNodeTemplates(), v8::Shell::CreateRealm(), v8::Shell::CreateTestFastCApiTemplate(), v8::Shell::DisposeRealm(), v8::Shell::DoHostImportModuleDynamically(), v8::Shell::ExecuteModule(), v8::Shell::ExecuteString(), v8::Shell::HandleUnhandledPromiseRejections(), v8::Shell::HostImportModuleWithPhaseDynamically(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsFastCApiObjectFastCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsFastCApiObjectSlowCallback(), v8::Shell::LoadJSON(), v8::Shell::ModuleResolutionFailureCallback(), v8::Shell::ModuleResolutionSuccessCallback(), v8::Shell::PromiseRejectCallback(), v8::Shell::RealmCurrent(), v8::Shell::RealmDetachGlobal(), v8::Shell::RealmDispose(), v8::Shell::RealmEval(), v8::Shell::RealmGlobal(), v8::Shell::RealmNavigate(), v8::Shell::RealmOwner(), v8::Shell::RealmSharedGet(), v8::Shell::RealmSharedSet(), v8::Shell::RealmSwitch(), v8::CheckMessageFromWorkerTask::Run(), v8::CleanUpWorkerTask::Run(), v8::AsyncHooks::ShellPromiseHook(), v8::anonymous_namespace{async-hooks-wrapper.cc}::UnwrapHook(), v8::Shell::WorkerNew(), v8::Shell::WorkerOnMessageGetter(), and v8::Shell::WorkerOnMessageSetter().
GetAsyncHooks()
AsyncHooks* v8::PerIsolateData::GetAsyncHooks () [inline]
Definition at line 329 of file d8.h.
{ return async_hooks_wrapper_; }
References async_hooks_wrapper_.
Referenced by v8::Shell::AsyncHooksCreateHook(), v8::Shell::AsyncHooksExecutionAsyncId(), v8::Shell::AsyncHooksTriggerAsyncId(), v8::AsyncHooks::ShellPromiseHook(), and v8::anonymous_namespace{async-hooks-wrapper.cc}::UnwrapHook().
GetDomNodeCtor()
Local< FunctionTemplate > v8::PerIsolateData::GetDomNodeCtor () const
Definition at line 2014 of file d8.cc.
                                                             {
  return dom_node_ctor_.Get(isolate_);
}
References dom_node_ctor_, and isolate_.
GetTestApiObjectCtor()
Local< FunctionTemplate > v8::PerIsolateData::GetTestApiObjectCtor () const
Definition at line 2006 of file d8.cc.
                                                                   {
  return test_api_object_ctor_.Get(isolate_);
}
References isolate_, and test_api_object_ctor_.
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsFastCApiObjectFastCallback(), and v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsFastCApiObjectSlowCallback().
GetWorkerOnMessage()
std::pair< Local< Context >, Local< Function > > v8::PerIsolateData::GetWorkerOnMessage (const std::shared_ptr< Worker > & worker) const
Definition at line 2049 of file d8.cc.
                                               {
  auto it = worker_message_callbacks_.find(worker);
  if (it == worker_message_callbacks_.end()) {
    return {};
  }
  return {it->second.first.Get(isolate_), it->second.second.Get(isolate_)};
}
References isolate_, and worker_message_callbacks_.
Referenced by v8::CheckMessageFromWorkerTask::Run(), and v8::Shell::WorkerOnMessageGetter().
HandleUnhandledPromiseRejections()
int v8::PerIsolateData::HandleUnhandledPromiseRejections ()
Definition at line 1975 of file d8.cc.
                                                     {
  // Avoid recursive calls to HandleUnhandledPromiseRejections.
  if (ignore_unhandled_promises_) return 0;
  if (isolate_->IsExecutionTerminating()) return 0;
  ignore_unhandled_promises_ = true;
  v8::HandleScope scope(isolate_);
  // Ignore promises that get added during error reporting.
  size_t i = 0;
  for (; i < unhandled_promises_.size(); i++) {
    const auto& tuple = unhandled_promises_[i];
    Local<v8::Message> message = std::get<1>(tuple).Get(isolate_);
    Local<v8::Value> value = std::get<2>(tuple).Get(isolate_);
    Shell::ReportException(isolate_, message, value);
  }
  unhandled_promises_.clear();
  ignore_unhandled_promises_ = false;
  return static_cast<int>(i);
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, ignore_unhandled_promises_, v8::Isolate::IsExecutionTerminating(), isolate_, v8::Shell::ReportException(), unhandled_promises_, and v8::internal::value.
Referenced by v8::Shell::HandleUnhandledPromiseRejections().
HasRunningSubscribedWorkers()
bool v8::PerIsolateData::HasRunningSubscribedWorkers ()
Definition at line 2022 of file d8.cc.
                                                 {
  // Only consider subscribed workers, so that code that spawns a worker and
  // never subscribes to message events will quit.
  return !worker_message_callbacks_.empty();
}
References worker_message_callbacks_.
Referenced by v8::Shell::CompleteMessageLoop().
RealmFind()
int v8::PerIsolateData::RealmFind (Local< Context > context) [private]
Definition at line 2097 of file d8.cc.
                                                    {
  for (int i = 0; i < realm_count_; ++i) {
    if (realms_[i] == context) return i;
  }
  return -1;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, realm_count_, and realms_.
Referenced by v8::Shell::RealmCurrent(), and v8::Shell::RealmOwner().
RealmIndexOrThrow()
int v8::PerIsolateData::RealmIndexOrThrow (const v8::FunctionCallbackInfo< v8::Value > & info, int arg_offset) [private]
Definition at line 2104 of file d8.cc.
                                                                 {
  if (info.Length() < arg_offset || !info[arg_offset]->IsNumber()) {
    ThrowError(info.GetIsolate(), "Invalid argument");
    return -1;
  }
  int index = info[arg_offset]
                  ->Int32Value(info.GetIsolate()->GetCurrentContext())
                  .FromMaybe(-1);
  if (index < 0 || index >= realm_count_ || realms_[index].IsEmpty()) {
    ThrowError(info.GetIsolate(), "Invalid realm index");
    return -1;
  }
  return index;
}
References v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::internal::index, v8::FunctionCallbackInfo< T >::Length(), realm_count_, realms_, and v8::anonymous_namespace{d8.cc}::ThrowError().
Referenced by v8::Shell::RealmDetachGlobal(), v8::Shell::RealmDispose(), v8::Shell::RealmEval(), v8::Shell::RealmGlobal(), v8::Shell::RealmNavigate(), and v8::Shell::RealmSwitch().
RegisterWorker()
void v8::PerIsolateData::RegisterWorker (std::shared_ptr< Worker > worker)
Definition at line 2028 of file d8.cc.
                                                                {
  registered_workers_.insert(std::move(worker));
}
References registered_workers_.
Referenced by v8::Shell::WorkerNew().
RemoveUnhandledPromise()
void v8::PerIsolateData::RemoveUnhandledPromise (Local< Promise > promise)
Definition at line 1952 of file d8.cc.
                                                                  {
  if (ignore_unhandled_promises_) return;
  // Remove handled promises from the list
  DCHECK_EQ(Isolate::GetCurrent(), isolate_);
  for (auto it = unhandled_promises_.begin(); it != unhandled_promises_.end();
       ++it) {
    v8::Local<v8::Promise> unhandled_promise = std::get<0>(*it).Get(isolate_);
    if (unhandled_promise == promise) {
      unhandled_promises_.erase(it--);
    }
  }
}
References DCHECK_EQ, v8::Isolate::GetCurrent(), ignore_unhandled_promises_, isolate_, and unhandled_promises_.
Referenced by v8::Shell::PromiseRejectCallback().
SetDomNodeCtor()
void v8::PerIsolateData::SetDomNodeCtor (Local< FunctionTemplate > ctor)
Definition at line 2018 of file d8.cc.
                                                                {
  dom_node_ctor_.Reset(isolate_, ctor);
}
References dom_node_ctor_, and isolate_.
Referenced by v8::Shell::CreateNodeTemplates().
SetTestApiObjectCtor()
void v8::PerIsolateData::SetTestApiObjectCtor (Local< FunctionTemplate > ctor)
Definition at line 2010 of file d8.cc.
                                                                      {
  test_api_object_ctor_.Reset(isolate_, ctor);
}
References isolate_, and test_api_object_ctor_.
Referenced by v8::Shell::CreateTestFastCApiTemplate().
SubscribeWorkerOnMessage()
void v8::PerIsolateData::SubscribeWorkerOnMessage (const std::shared_ptr< Worker > & worker, Local< Context > context, Local< Function > callback)
Definition at line 2032 of file d8.cc.
                              {
  if (!registered_workers_.contains(worker)) {
    // The worker has already terminated, so it won't be posting any more
    // messages. Don't try to subscribe to its events.
    fprintf(
        stderr,
        "Trying to subscribe to message events from a terminated worker -- "
        "consider registering the event handler before the event loop runs.\n");
    return;
  }
  worker_message_callbacks_.emplace(
      worker, std::make_pair(Global<Context>(isolate_, context),
                             Global<Function>(isolate_, callback)));
}
References isolate_, registered_workers_, and worker_message_callbacks_.
Referenced by v8::Shell::WorkerOnMessageSetter().
UnregisterWorker()
void v8::PerIsolateData::UnregisterWorker (const std::shared_ptr< Worker > & worker)
Definition at line 2058 of file d8.cc.
                                                                         {
  registered_workers_.erase(worker);
  worker_message_callbacks_.erase(worker);
}
References registered_workers_, and worker_message_callbacks_.
Referenced by v8::CleanUpWorkerTask::Run().
Friends And Related Function Documentation
RealmScope
friend class RealmScope [friend]
Definition at line 358 of file d8.h.
Shell
friend class Shell [friend]
Definition at line 357 of file d8.h.
Member Data Documentation
async_hooks_wrapper_
AsyncHooks* v8::PerIsolateData::async_hooks_wrapper_ [private]
Definition at line 368 of file d8.h.
Referenced by GetAsyncHooks(), PerIsolateData(), and ~PerIsolateData().
dom_node_ctor_
Global<FunctionTemplate> v8::PerIsolateData::dom_node_ctor_ [private]
Definition at line 373 of file d8.h.
Referenced by GetDomNodeCtor(), and SetDomNodeCtor().
ignore_unhandled_promises_
bool v8::PerIsolateData::ignore_unhandled_promises_ [private]
Definition at line 365 of file d8.h.
Referenced by AddUnhandledPromise(), HandleUnhandledPromiseRejections(), PerIsolateData(), and RemoveUnhandledPromise().
isolate_
Isolate* v8::PerIsolateData::isolate_ [private]
Definition at line 359 of file d8.h.
Referenced by AddUnhandledPromise(), v8::InspectorClient::ensureDefaultContextInGroup(), v8::PerIsolateData::ExplicitRealmScope::ExplicitRealmScope(), GetDomNodeCtor(), GetTestApiObjectCtor(), GetWorkerOnMessage(), HandleUnhandledPromiseRejections(), v8::InspectorClient::InspectorClient(), v8::InspectorFrontend::InspectorFrontend(), v8::PerIsolateData::RealmScope::RealmScope(), RemoveUnhandledPromise(), v8::SetTimeoutTask::Run(), v8::OnMessageFromWorkerTask::Run(), v8::CheckMessageFromWorkerTask::Run(), v8::CleanUpWorkerTask::Run(), v8::InspectorClient::runMessageLoopOnPause(), v8::InspectorFrontend::Send(), SetDomNodeCtor(), SetTestApiObjectCtor(), SubscribeWorkerOnMessage(), and ~PerIsolateData().
realm_count_
int v8::PerIsolateData::realm_count_ [private]
Definition at line 360 of file d8.h.
Referenced by v8::Shell::CreateRealm(), RealmFind(), RealmIndexOrThrow(), and v8::PerIsolateData::RealmScope::RealmScope().
realm_current_
int v8::PerIsolateData::realm_current_ [private]
Definition at line 361 of file d8.h.
Referenced by v8::Shell::ExecuteModule(), v8::Shell::ExecuteString(), v8::PerIsolateData::ExplicitRealmScope::ExplicitRealmScope(), v8::Shell::LoadJSON(), v8::Shell::ModuleResolutionFailureCallback(), v8::Shell::ModuleResolutionSuccessCallback(), v8::Shell::RealmDetachGlobal(), v8::Shell::RealmDispose(), v8::Shell::RealmNavigate(), and v8::PerIsolateData::RealmScope::RealmScope().
realm_shared_
Global<Value> v8::PerIsolateData::realm_shared_ [private]
Definition at line 364 of file d8.h.
Referenced by v8::Shell::RealmSharedGet(), and v8::Shell::RealmSharedSet().
realm_switch_
int v8::PerIsolateData::realm_switch_ [private]
Definition at line 362 of file d8.h.
Referenced by v8::Shell::ExecuteString(), v8::PerIsolateData::ExplicitRealmScope::ExplicitRealmScope(), v8::Shell::RealmDetachGlobal(), v8::Shell::RealmDispose(), v8::Shell::RealmNavigate(), v8::PerIsolateData::RealmScope::RealmScope(), and v8::Shell::RealmSwitch().
realms_
Global<Context>* v8::PerIsolateData::realms_ [private]
Definition at line 363 of file d8.h.
Referenced by v8::Shell::CreateRealm(), v8::Shell::DisposeRealm(), v8::Shell::ExecuteModule(), v8::Shell::ExecuteString(), v8::PerIsolateData::ExplicitRealmScope::ExplicitRealmScope(), v8::Shell::LoadJSON(), v8::Shell::ModuleResolutionFailureCallback(), v8::Shell::ModuleResolutionSuccessCallback(), v8::Shell::RealmDetachGlobal(), RealmFind(), v8::Shell::RealmGlobal(), RealmIndexOrThrow(), v8::Shell::RealmNavigate(), and v8::PerIsolateData::RealmScope::RealmScope().
registered_workers_
std::set<std::shared_ptr<Worker> > v8::PerIsolateData::registered_workers_ [private]
Definition at line 378 of file d8.h.
Referenced by RegisterWorker(), SubscribeWorkerOnMessage(), and UnregisterWorker().
test_api_object_ctor_
Global<FunctionTemplate> v8::PerIsolateData::test_api_object_ctor_ [private]
Definition at line 372 of file d8.h.
Referenced by GetTestApiObjectCtor(), and SetTestApiObjectCtor().
unhandled_promises_
std::vector<std::tuple<Global<Promise>, Global<Message>, Global<Value> > > v8::PerIsolateData::unhandled_promises_ [private]
Definition at line 367 of file d8.h.
Referenced by AddUnhandledPromise(), HandleUnhandledPromiseRejections(), and RemoveUnhandledPromise().
worker_message_callbacks_
std::map<std::shared_ptr<Worker>, std::pair<Global<Context>, Global<Function> > > v8::PerIsolateData::worker_message_callbacks_ [private]
Definition at line 381 of file d8.h.
Referenced by GetWorkerOnMessage(), HasRunningSubscribedWorkers(), SubscribeWorkerOnMessage(), and UnregisterWorker().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/d8/d8.h
/mnt/V8SourceCode/src/d8/d8.cc