v8::internal::EmbeddedFileWriter Class Reference
#include <embedded-file-writer.h>
Public Member Functions
int LookupOrAddExternallyCompiledFilename (const char *filename) override
const char * GetExternallyCompiledFilename (int fileid) const override
int GetExternallyCompiledFilenameCount () const override
void PrepareBuiltinSourcePositionMap (Builtins *builtins) override
void SetEmbeddedFile (const char *embedded_src_path)
void SetEmbeddedVariant (const char *embedded_variant)
void SetTargetArch (const char *target_arch)
void SetTargetOs (const char *target_os)
void WriteEmbedded (const i::EmbeddedData *blob) const
Private Member Functions
void MaybeWriteEmbeddedFile (const i::EmbeddedData *blob) const
void WriteFilePrologue (PlatformEmbeddedFileWriterBase *w) const
void WriteExternalFilenames (PlatformEmbeddedFileWriterBase *w) const
std::string EmbeddedBlobCodeSymbol () const
std::string EmbeddedBlobDataSymbol () const
void WriteDataSection (PlatformEmbeddedFileWriterBase *w, const i::EmbeddedData *blob) const
void WriteBuiltin (PlatformEmbeddedFileWriterBase *w, const i::EmbeddedData *blob, const Builtin builtin) const
void WriteBuiltinLabels (PlatformEmbeddedFileWriterBase *w, std::string name) const
void WriteCodeSection (PlatformEmbeddedFileWriterBase *w, const i::EmbeddedData *blob) const
void WriteFileEpilogue (PlatformEmbeddedFileWriterBase *w, const i::EmbeddedData *blob) const
Static Private Member Functions
static FILE * GetFileDescriptorOrDie (const char *filename)
static void WriteBinaryContentsAsInlineAssembly (PlatformEmbeddedFileWriterBase *w, const uint8_t *data, uint32_t size)
static int ExternalFilenameIndexToId (int index)
static int ExternalFilenameIdToIndex (int id)
Private Attributes
std::vector< uint8_t > source_positions_ [Builtins::kBuiltinCount]
std::vector< LabelInfo > label_info_ [Builtins::kBuiltinCount]
std::map< const char *, int > external_filenames_
std::vector< const char * > external_filenames_by_index_
const char * embedded_src_path_ = nullptr
const char * embedded_variant_ = kDefaultEmbeddedVariant
const char * target_arch_ = nullptr
const char * target_os_ = nullptr
Static Private Attributes
static constexpr int kTemporaryStringLength = 256
static constexpr int kFirstExternalFilenameId = 1
Detailed Description
Definition at line 35 of file embedded-file-writer.h.
Member Function Documentation
EmbeddedBlobCodeSymbol()
std::string v8::internal::EmbeddedFileWriter::EmbeddedBlobCodeSymbol () const [inline], [private]
Definition at line 126 of file embedded-file-writer.h.
                                           {
    base::EmbeddedVector<char, kTemporaryStringLength>
        embedded_blob_code_symbol;
    base::SNPrintF(embedded_blob_code_symbol, "v8_%s_embedded_blob_code_",
                   embedded_variant_);
    return std::string{embedded_blob_code_symbol.begin()};
  }
References v8::base::Vector< T >::begin(), embedded_variant_, v8::base::SNPrintF(), and v8::internal::string.
Referenced by WriteCodeSection(), and WriteFileEpilogue().
EmbeddedBlobDataSymbol()
std::string v8::internal::EmbeddedFileWriter::EmbeddedBlobDataSymbol () const [inline], [private]
Definition at line 134 of file embedded-file-writer.h.
                                           {
    base::EmbeddedVector<char, kTemporaryStringLength>
        embedded_blob_data_symbol;
    base::SNPrintF(embedded_blob_data_symbol, "v8_%s_embedded_blob_data_",
                   embedded_variant_);
    return std::string{embedded_blob_data_symbol.begin()};
  }
References v8::base::Vector< T >::begin(), embedded_variant_, v8::base::SNPrintF(), and v8::internal::string.
Referenced by WriteDataSection().
ExternalFilenameIdToIndex()
static int v8::internal::EmbeddedFileWriter::ExternalFilenameIdToIndex (int id) [inline], [static], [private]
Definition at line 181 of file embedded-file-writer.h.
                                               {
    return id - kFirstExternalFilenameId;
  }
References kFirstExternalFilenameId.
Referenced by GetExternallyCompiledFilename().
ExternalFilenameIndexToId()
static int v8::internal::EmbeddedFileWriter::ExternalFilenameIndexToId (int index) [inline], [static], [private]
Definition at line 178 of file embedded-file-writer.h.
                                                  {
    return kFirstExternalFilenameId + index;
  }
References v8::internal::index, and kFirstExternalFilenameId.
Referenced by LookupOrAddExternallyCompiledFilename(), and WriteExternalFilenames().
GetExternallyCompiledFilename()
const char * v8::internal::EmbeddedFileWriter::GetExternallyCompiledFilename (int fileid) const [override], [virtual]
Implements v8::internal::EmbeddedFileWriterInterface.
Definition at line 271 of file embedded-file-writer.cc.
                      {
  size_t index = static_cast<size_t>(ExternalFilenameIdToIndex(fileid));
  DCHECK_GE(index, 0);
  DCHECK_LT(index, external_filenames_by_index_.size());
  return external_filenames_by_index_[index];
}
References DCHECK_GE, DCHECK_LT, external_filenames_by_index_, ExternalFilenameIdToIndex(), and v8::internal::index.
Referenced by WriteBuiltin().
GetExternallyCompiledFilenameCount()
int v8::internal::EmbeddedFileWriter::GetExternallyCompiledFilenameCount () const [override], [virtual]
Implements v8::internal::EmbeddedFileWriterInterface.
Definition at line 280 of file embedded-file-writer.cc.
                                                                 {
  return static_cast<int>(external_filenames_.size());
}
References external_filenames_.
GetFileDescriptorOrDie()
static FILE* v8::internal::EmbeddedFileWriter::GetFileDescriptorOrDie (const char * filename) [inline], [static], [private]
Definition at line 88 of file embedded-file-writer.h.
                                                            {
    FILE* fp = v8::base::OS::FOpen(filename, "w");
    if (fp == nullptr) {
      i::PrintF("Unable to open file \"%s\" for writing.\n", filename);
      exit(1);
    }
    return fp;
  }
References v8::base::OS::FOpen(), and v8::internal::PrintF().
Referenced by MaybeWriteEmbeddedFile().
LookupOrAddExternallyCompiledFilename()
int v8::internal::EmbeddedFileWriter::LookupOrAddExternallyCompiledFilename (const char * filename) [override], [virtual]
Implements v8::internal::EmbeddedFileWriterInterface.
Definition at line 257 of file embedded-file-writer.cc.
                          {
  auto result = external_filenames_.find(filename);
  if (result != external_filenames_.end()) {
    return result->second;
  }
  int new_id =
      ExternalFilenameIndexToId(static_cast<int>(external_filenames_.size()));
  external_filenames_.insert(std::make_pair(filename, new_id));
  external_filenames_by_index_.push_back(filename);
  DCHECK_EQ(external_filenames_by_index_.size(), external_filenames_.size());
  return new_id;
}
References DCHECK_EQ, external_filenames_, external_filenames_by_index_, ExternalFilenameIndexToId(), and v8::base::internal::result.
MaybeWriteEmbeddedFile()
void v8::internal::EmbeddedFileWriter::MaybeWriteEmbeddedFile (const i::EmbeddedData * blob) const [inline], [private]
Definition at line 70 of file embedded-file-writer.h.
                                                               {
    if (embedded_src_path_ == nullptr) return;
    FILE* fp = GetFileDescriptorOrDie(embedded_src_path_);
    std::unique_ptr<PlatformEmbeddedFileWriterBase> writer =
        NewPlatformEmbeddedFileWriter(target_arch_, target_os_);
    writer->SetFile(fp);
    WriteFilePrologue(writer.get());
    WriteExternalFilenames(writer.get());
    WriteDataSection(writer.get(), blob);
    WriteCodeSection(writer.get(), blob);
    WriteFileEpilogue(writer.get(), blob);
    base::Fclose(fp);
  }
References embedded_src_path_, v8::base::Fclose(), GetFileDescriptorOrDie(), v8::internal::NewPlatformEmbeddedFileWriter(), target_arch_, target_os_, WriteCodeSection(), WriteDataSection(), WriteExternalFilenames(), WriteFileEpilogue(), and WriteFilePrologue().
Referenced by WriteEmbedded().
PrepareBuiltinSourcePositionMap()
void v8::internal::EmbeddedFileWriter::PrepareBuiltinSourcePositionMap (Builtins * builtins) [override], [virtual]
Implements v8::internal::EmbeddedFileWriterInterface.
Definition at line 284 of file embedded-file-writer.cc.
                                                                           {
  for (Builtin builtin = Builtins::kFirst; builtin <= Builtins::kLast;
       ++builtin) {
    // Retrieve the SourcePositionTable and copy it.
    Tagged<Code> code = builtins->code(builtin);
    if (!code->has_source_position_table()) continue;
    Tagged<TrustedByteArray> source_position_table =
        code->source_position_table();
    std::vector<unsigned char> data(source_position_table->begin(),
                                    source_position_table->end());
    source_positions_[static_cast<int>(builtin)] = data;
  }
}
References v8::internal::Builtins::code(), code, v8::internal::Builtins::kFirst, v8::internal::Builtins::kLast, and source_positions_.
SetEmbeddedFile()
void v8::internal::EmbeddedFileWriter::SetEmbeddedFile (const char * embedded_src_path) [inline]
Definition at line 52 of file embedded-file-writer.h.
                                                      {
    embedded_src_path_ = embedded_src_path;
  }
References embedded_src_path_.
Referenced by main().
SetEmbeddedVariant()
void v8::internal::EmbeddedFileWriter::SetEmbeddedVariant (const char * embedded_variant) [inline]
Definition at line 56 of file embedded-file-writer.h.
                                                        {
    if (embedded_variant == nullptr) return;
    embedded_variant_ = embedded_variant;
  }
References embedded_variant_.
Referenced by main().
SetTargetArch()
void v8::internal::EmbeddedFileWriter::SetTargetArch (const char * target_arch) [inline]
Definition at line 61 of file embedded-file-writer.h.
{ target_arch_ = target_arch; }
References target_arch_.
Referenced by main().
SetTargetOs()
void v8::internal::EmbeddedFileWriter::SetTargetOs (const char * target_os) [inline]
Definition at line 63 of file embedded-file-writer.h.
{ target_os_ = target_os; }
References target_os_.
Referenced by main().
WriteBinaryContentsAsInlineAssembly()
void v8::internal::EmbeddedFileWriter::WriteBinaryContentsAsInlineAssembly (PlatformEmbeddedFileWriterBase * w, const uint8_t * data, uint32_t size) [static], [private]
Definition at line 212 of file embedded-file-writer.cc.
                                                                           {
#if V8_OS_ZOS
  // HLASM source must end at column 71 (followed by an optional
  // line-continuation char on column 72), so write the binary data
  // in 32 byte chunks (length 64):
  uint32_t chunks = (size + 31) / 32;
  uint32_t i, j;
  uint32_t offset = 0;
  for (i = 0; i < chunks; ++i) {
    fprintf(w->fp(), " DC x'");
    for (j = 0; offset < size && j < 32; ++j) {
      fprintf(w->fp(), "%02x", data[offset++]);
    }
    fprintf(w->fp(), "'\n");
  }
#else
  int current_line_length = 0;
  uint32_t i = 0;
  // Begin by writing out byte chunks.
  const DataDirective directive = w->ByteChunkDataDirective();
  const int byte_chunk_size = DataDirectiveSize(directive);
  for (; i + byte_chunk_size < size; i += byte_chunk_size) {
    current_line_length =
        WriteDirectiveOrSeparator(w, current_line_length, directive);
    current_line_length += w->WriteByteChunk(data + i);
    current_line_length =
        WriteLineEndIfNeeded(w, current_line_length, byte_chunk_size);
  }
  if (current_line_length != 0) w->Newline();
  current_line_length = 0;
  // Write any trailing bytes one-by-one.
  for (; i < size; i++) {
    current_line_length =
        WriteDirectiveOrSeparator(w, current_line_length, kByte);
    current_line_length += w->HexLiteral(data[i]);
    current_line_length = WriteLineEndIfNeeded(w, current_line_length, 1);
  }
  if (current_line_length != 0) w->Newline();
#endif // V8_OS_ZOS
}
References v8::internal::PlatformEmbeddedFileWriterBase::ByteChunkDataDirective(), v8::internal::DataDirectiveSize(), v8::internal::PlatformEmbeddedFileWriterBase::fp(), v8::internal::PlatformEmbeddedFileWriterBase::HexLiteral(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kByte, v8::internal::PlatformEmbeddedFileWriterBase::Newline(), size(), v8::internal::PlatformEmbeddedFileWriterBase::WriteByteChunk(), v8::internal::anonymous_namespace{embedded-file-writer.cc}::WriteDirectiveOrSeparator(), and v8::internal::anonymous_namespace{embedded-file-writer.cc}::WriteLineEndIfNeeded().
Referenced by WriteBuiltin(), and WriteDataSection().
WriteBuiltin()
void v8::internal::EmbeddedFileWriter::WriteBuiltin (PlatformEmbeddedFileWriterBase * w, const i::EmbeddedData * blob, const Builtin builtin) const [private]
Definition at line 50 of file embedded-file-writer.cc.
                                                                   {
  const bool is_default_variant =
      std::strcmp(embedded_variant_, kDefaultEmbeddedVariant) == 0;
  base::EmbeddedVector<char, kTemporaryStringLength> builtin_symbol;
  if (is_default_variant) {
    // Create nicer symbol names for the default mode.
    base::SNPrintF(builtin_symbol, "Builtins_%s", i::Builtins::name(builtin));
  } else {
    base::SNPrintF(builtin_symbol, "%s_Builtins_%s", embedded_variant_,
                   i::Builtins::name(builtin));
  }
  // Labels created here will show up in backtraces. We check in
  // Isolate::SetEmbeddedBlob that the blob layout remains unchanged, i.e.
  // that labels do not insert bytes into the middle of the blob byte
  // stream.
  w->DeclareFunctionBegin(builtin_symbol.begin(),
                          blob->InstructionSizeOf(builtin));
  const int builtin_id = static_cast<int>(builtin);
  const std::vector<uint8_t>& current_positions = source_positions_[builtin_id];
  // The code below interleaves bytes of assembly code for the builtin
  // function with source positions at the appropriate offsets.
  base::Vector<const uint8_t> vpos(current_positions.data(),
                                   current_positions.size());
  v8::internal::SourcePositionTableIterator positions(
      vpos, SourcePositionTableIterator::kExternalOnly);
#ifndef DEBUG
  CHECK(positions.done()); // Release builds must not contain debug infos.
#endif
  // Some builtins (InterpreterPushArgsThenFastConstructFunction,
  // JSConstructStubGeneric) have entry points located in the middle of them, we
  // need to store their addresses since they are part of the list of allowed
  // return addresses in the deoptimizer.
  const std::vector<LabelInfo>& current_labels = label_info_[builtin_id];
  auto label = current_labels.begin();
  const uint8_t* data =
      reinterpret_cast<const uint8_t*>(blob->InstructionStartOf(builtin));
  uint32_t size = blob->PaddedInstructionSizeOf(builtin);
  uint32_t i = 0;
  uint32_t next_source_pos_offset =
      static_cast<uint32_t>(positions.done() ? size : positions.code_offset());
  uint32_t next_label_offset = static_cast<uint32_t>(
      (label == current_labels.end()) ? size : label->offset);
  uint32_t next_offset = 0;
  while (i < size) {
    if (i == next_source_pos_offset) {
      // Write source directive.
      w->SourceInfo(positions.source_position().ExternalFileId(),
                    GetExternallyCompiledFilename(
                        positions.source_position().ExternalFileId()),
                    positions.source_position().ExternalLine());
      positions.Advance();
      next_source_pos_offset = static_cast<uint32_t>(
          positions.done() ? size : positions.code_offset());
      CHECK_GE(next_source_pos_offset, i);
    }
    if (i == next_label_offset) {
      WriteBuiltinLabels(w, label->name);
      label++;
      next_label_offset = static_cast<uint32_t>(
          (label == current_labels.end()) ? size : label->offset);
      CHECK_GE(next_label_offset, i);
    }
    next_offset = std::min(next_source_pos_offset, next_label_offset);
    WriteBinaryContentsAsInlineAssembly(w, data + i, next_offset - i);
    i = next_offset;
  }
  w->DeclareFunctionEnd(builtin_symbol.begin());
}
References v8::internal::SourcePositionTableIterator::Advance(), v8::base::Vector< T >::begin(), CHECK, CHECK_GE, v8::internal::SourcePositionTableIterator::code_offset(), v8::internal::PlatformEmbeddedFileWriterBase::DeclareFunctionBegin(), v8::internal::PlatformEmbeddedFileWriterBase::DeclareFunctionEnd(), v8::internal::SourcePositionTableIterator::done(), embedded_variant_, v8::internal::SourcePosition::ExternalFileId(), v8::internal::SourcePosition::ExternalLine(), GetExternallyCompiledFilename(), v8::internal::EmbeddedData::InstructionSizeOf(), v8::internal::EmbeddedData::InstructionStartOf(), v8::internal::kDefaultEmbeddedVariant, v8::internal::SourcePositionTableIterator::kExternalOnly, label_info_, v8::internal::Builtins::name(), v8::internal::EmbeddedData::PaddedInstructionSizeOf(), size(), v8::base::SNPrintF(), v8::internal::SourcePositionTableIterator::source_position(), source_positions_, v8::internal::PlatformEmbeddedFileWriterBase::SourceInfo(), WriteBinaryContentsAsInlineAssembly(), and WriteBuiltinLabels().
Referenced by WriteCodeSection().
WriteBuiltinLabels()
void v8::internal::EmbeddedFileWriter::WriteBuiltinLabels (PlatformEmbeddedFileWriterBase * w, std::string name) const [private]
Definition at line 127 of file embedded-file-writer.cc.
                                                                  {
  w->DeclareLabel(name.c_str());
}
References v8::internal::PlatformEmbeddedFileWriterBase::DeclareLabel(), and v8::internal::name.
Referenced by WriteBuiltin().
WriteCodeSection()
void v8::internal::EmbeddedFileWriter::WriteCodeSection (PlatformEmbeddedFileWriterBase * w, const i::EmbeddedData * blob) const [private]
Definition at line 132 of file embedded-file-writer.cc.
                                                                           {
  w->Comment(
      "The embedded blob code section starts here. It contains the builtin");
  w->Comment("instruction streams.");
  w->SectionText();
#if V8_TARGET_ARCH_IA32 || V8_TARGET_ARCH_X64
  // UMA needs an exposed function-type label at the start of the embedded
  // code section.
  static const char* kCodeStartForProfilerSymbolName =
      "v8_code_start_for_profiler_";
  static constexpr int kDummyFunctionLength = 1;
  static constexpr int kDummyFunctionData = 0xcc;
  w->DeclareFunctionBegin(kCodeStartForProfilerSymbolName,
                          kDummyFunctionLength);
  // The label must not be at the same address as the first builtin, insert
  // padding bytes.
  WriteDirectiveOrSeparator(w, 0, kByte);
  w->HexLiteral(kDummyFunctionData);
  w->Newline();
  w->DeclareFunctionEnd(kCodeStartForProfilerSymbolName);
#endif
  w->AlignToCodeAlignment();
  w->DeclareSymbolGlobal(EmbeddedBlobCodeSymbol().c_str());
  w->DeclareLabelProlog(EmbeddedBlobCodeSymbol().c_str());
  w->DeclareLabel(EmbeddedBlobCodeSymbol().c_str());
  static_assert(Builtins::kAllBuiltinsAreIsolateIndependent);
  for (ReorderedBuiltinIndex embedded_index = 0;
       embedded_index < Builtins::kBuiltinCount; embedded_index++) {
    Builtin builtin = blob->GetBuiltinId(embedded_index);
    WriteBuiltin(w, blob, builtin);
  }
  w->AlignToPageSizeIfNeeded();
  w->DeclareLabelEpilogue();
  w->Newline();
}
References v8::internal::PlatformEmbeddedFileWriterBase::AlignToCodeAlignment(), v8::internal::PlatformEmbeddedFileWriterBase::AlignToPageSizeIfNeeded(), v8::internal::PlatformEmbeddedFileWriterBase::Comment(), v8::internal::PlatformEmbeddedFileWriterBase::DeclareFunctionBegin(), v8::internal::PlatformEmbeddedFileWriterBase::DeclareFunctionEnd(), v8::internal::PlatformEmbeddedFileWriterBase::DeclareLabel(), v8::internal::PlatformEmbeddedFileWriterBase::DeclareLabelEpilogue(), v8::internal::PlatformEmbeddedFileWriterBase::DeclareLabelProlog(), v8::internal::PlatformEmbeddedFileWriterBase::DeclareSymbolGlobal(), EmbeddedBlobCodeSymbol(), v8::internal::EmbeddedData::GetBuiltinId(), v8::internal::PlatformEmbeddedFileWriterBase::HexLiteral(), v8::internal::Builtins::kAllBuiltinsAreIsolateIndependent, v8::internal::Builtins::kBuiltinCount, v8::internal::kByte, v8::internal::PlatformEmbeddedFileWriterBase::Newline(), v8::internal::PlatformEmbeddedFileWriterBase::SectionText(), WriteBuiltin(), and v8::internal::anonymous_namespace{embedded-file-writer.cc}::WriteDirectiveOrSeparator().
Referenced by MaybeWriteEmbeddedFile().
WriteDataSection()
void v8::internal::EmbeddedFileWriter::WriteDataSection (PlatformEmbeddedFileWriterBase * w, const i::EmbeddedData * blob) const [inline], [private]
Definition at line 142 of file embedded-file-writer.h.
                                                         {
    w->Comment("The embedded blob data section starts here.");
    w->SectionRoData();
    w->AlignToDataAlignment();
    w->DeclareSymbolGlobal(EmbeddedBlobDataSymbol().c_str());
    w->DeclareLabelProlog(EmbeddedBlobDataSymbol().c_str());
    w->DeclareLabel(EmbeddedBlobDataSymbol().c_str());
    WriteBinaryContentsAsInlineAssembly(w, blob->data(), blob->data_size());
    w->DeclareLabelEpilogue();
    w->Newline();
  }
References v8::internal::PlatformEmbeddedFileWriterBase::AlignToDataAlignment(), v8::internal::PlatformEmbeddedFileWriterBase::Comment(), v8::internal::EmbeddedData::data(), v8::internal::EmbeddedData::data_size(), v8::internal::PlatformEmbeddedFileWriterBase::DeclareLabel(), v8::internal::PlatformEmbeddedFileWriterBase::DeclareLabelEpilogue(), v8::internal::PlatformEmbeddedFileWriterBase::DeclareLabelProlog(), v8::internal::PlatformEmbeddedFileWriterBase::DeclareSymbolGlobal(), EmbeddedBlobDataSymbol(), v8::internal::PlatformEmbeddedFileWriterBase::Newline(), v8::internal::PlatformEmbeddedFileWriterBase::SectionRoData(), and WriteBinaryContentsAsInlineAssembly().
Referenced by MaybeWriteEmbeddedFile().
WriteEmbedded()
void v8::internal::EmbeddedFileWriter::WriteEmbedded (const i::EmbeddedData * blob) const [inline]
Definition at line 65 of file embedded-file-writer.h.
                                                      {
    MaybeWriteEmbeddedFile(blob);
  }
References MaybeWriteEmbeddedFile().
Referenced by anonymous_namespace{mksnapshot.cc}::WriteEmbeddedFile().
WriteExternalFilenames()
void v8::internal::EmbeddedFileWriter::WriteExternalFilenames (PlatformEmbeddedFileWriterBase * w) const [inline], [private]
Definition at line 104 of file embedded-file-writer.h.
                                                                       {
#ifndef DEBUG
    // Release builds must not contain debug infos.
    CHECK_EQ(external_filenames_by_index_.size(), 0);
#endif
    w->Comment(
        "Source positions in the embedded blob refer to filenames by id.");
    w->Comment("Assembly directives here map the id to a filename.");
    w->Newline();
    // Write external filenames.
    int size = static_cast<int>(external_filenames_by_index_.size());
    for (int i = 0; i < size; i++) {
      w->DeclareExternalFilename(ExternalFilenameIndexToId(i),
                                 external_filenames_by_index_[i]);
    }
  }
References CHECK_EQ, v8::internal::PlatformEmbeddedFileWriterBase::Comment(), v8::internal::PlatformEmbeddedFileWriterBase::DeclareExternalFilename(), external_filenames_by_index_, ExternalFilenameIndexToId(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::PlatformEmbeddedFileWriterBase::Newline(), and size().
Referenced by MaybeWriteEmbeddedFile().
WriteFileEpilogue()
void v8::internal::EmbeddedFileWriter::WriteFileEpilogue (PlatformEmbeddedFileWriterBase * w, const i::EmbeddedData * blob) const [private]
Definition at line 172 of file embedded-file-writer.cc.
                                                                            {
  {
    base::EmbeddedVector<char, kTemporaryStringLength>
        embedded_blob_code_size_symbol;
    base::SNPrintF(embedded_blob_code_size_symbol,
                   "v8_%s_embedded_blob_code_size_", embedded_variant_);
    w->Comment("The size of the embedded blob code in bytes.");
    w->SectionRoData();
    w->AlignToDataAlignment();
    w->DeclareUint32(embedded_blob_code_size_symbol.begin(), blob->code_size());
    w->Newline();
    base::EmbeddedVector<char, kTemporaryStringLength>
        embedded_blob_data_size_symbol;
    base::SNPrintF(embedded_blob_data_size_symbol,
                   "v8_%s_embedded_blob_data_size_", embedded_variant_);
    w->Comment("The size of the embedded blob data section in bytes.");
    w->DeclareUint32(embedded_blob_data_size_symbol.begin(), blob->data_size());
    w->Newline();
  }
#if defined(V8_OS_WIN64)
  {
    base::EmbeddedVector<char, kTemporaryStringLength> unwind_info_symbol;
    base::SNPrintF(unwind_info_symbol, "%s_Builtins_UnwindInfo",
                   embedded_variant_);
    w->MaybeEmitUnwindData(unwind_info_symbol.begin(),
                           EmbeddedBlobCodeSymbol().c_str(), blob,
                           reinterpret_cast<const void*>(&unwind_infos_[0]));
  }
#endif // V8_OS_WIN64
  w->FileEpilogue();
}
References v8::internal::PlatformEmbeddedFileWriterBase::AlignToDataAlignment(), v8::base::Vector< T >::begin(), v8::internal::EmbeddedData::code_size(), v8::internal::PlatformEmbeddedFileWriterBase::Comment(), v8::internal::EmbeddedData::data_size(), v8::internal::PlatformEmbeddedFileWriterBase::DeclareUint32(), embedded_variant_, EmbeddedBlobCodeSymbol(), v8::internal::PlatformEmbeddedFileWriterBase::FileEpilogue(), v8::internal::PlatformEmbeddedFileWriterBase::MaybeEmitUnwindData(), v8::internal::PlatformEmbeddedFileWriterBase::Newline(), v8::internal::PlatformEmbeddedFileWriterBase::SectionRoData(), and v8::base::SNPrintF().
Referenced by MaybeWriteEmbeddedFile().
WriteFilePrologue()
void v8::internal::EmbeddedFileWriter::WriteFilePrologue (PlatformEmbeddedFileWriterBase * w) const [inline], [private]
Definition at line 98 of file embedded-file-writer.h.
                                                                  {
    w->Comment("Autogenerated file. Do not edit.");
    w->Newline();
    w->FilePrologue();
  }
References v8::internal::PlatformEmbeddedFileWriterBase::Comment(), v8::internal::PlatformEmbeddedFileWriterBase::FilePrologue(), and v8::internal::PlatformEmbeddedFileWriterBase::Newline().
Referenced by MaybeWriteEmbeddedFile().
Member Data Documentation
embedded_src_path_
const char* v8::internal::EmbeddedFileWriter::embedded_src_path_ = nullptr [private]
Definition at line 197 of file embedded-file-writer.h.
Referenced by MaybeWriteEmbeddedFile(), and SetEmbeddedFile().
embedded_variant_
const char* v8::internal::EmbeddedFileWriter::embedded_variant_ = kDefaultEmbeddedVariant [private]
Definition at line 201 of file embedded-file-writer.h.
Referenced by EmbeddedBlobCodeSymbol(), EmbeddedBlobDataSymbol(), SetEmbeddedVariant(), WriteBuiltin(), and WriteFileEpilogue().
external_filenames_
std::map<const char*, int> v8::internal::EmbeddedFileWriter::external_filenames_ [private]
Definition at line 193 of file embedded-file-writer.h.
Referenced by GetExternallyCompiledFilenameCount(), and LookupOrAddExternallyCompiledFilename().
external_filenames_by_index_
std::vector<const char*> v8::internal::EmbeddedFileWriter::external_filenames_by_index_ [private]
Definition at line 194 of file embedded-file-writer.h.
Referenced by GetExternallyCompiledFilename(), LookupOrAddExternallyCompiledFilename(), and WriteExternalFilenames().
kFirstExternalFilenameId
constexpr int v8::internal::EmbeddedFileWriter::kFirstExternalFilenameId = 1 [static], [constexpr], [private]
Definition at line 177 of file embedded-file-writer.h.
Referenced by ExternalFilenameIdToIndex(), and ExternalFilenameIndexToId().
kTemporaryStringLength
constexpr int v8::internal::EmbeddedFileWriter::kTemporaryStringLength = 256 [static], [constexpr], [private]
Definition at line 124 of file embedded-file-writer.h.
label_info_
std::vector<LabelInfo> v8::internal::EmbeddedFileWriter::label_info_[Builtins::kBuiltinCount] [private]
Definition at line 187 of file embedded-file-writer.h.
Referenced by WriteBuiltin().
source_positions_
std::vector<uint8_t> v8::internal::EmbeddedFileWriter::source_positions_[Builtins::kBuiltinCount] [private]
Definition at line 186 of file embedded-file-writer.h.
Referenced by PrepareBuiltinSourcePositionMap(), and WriteBuiltin().
target_arch_
const char* v8::internal::EmbeddedFileWriter::target_arch_ = nullptr [private]
Definition at line 206 of file embedded-file-writer.h.
Referenced by MaybeWriteEmbeddedFile(), and SetTargetArch().
target_os_
const char* v8::internal::EmbeddedFileWriter::target_os_ = nullptr [private]
Definition at line 207 of file embedded-file-writer.h.
Referenced by MaybeWriteEmbeddedFile(), and SetTargetOs().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/embedded/embedded-file-writer.h
/mnt/V8SourceCode/src/snapshot/embedded/embedded-file-writer.cc