cppgc::internal::CrossThreadPersistentBase Class Reference
#include <cross-thread-persistent.h>
Public Member Functions
CrossThreadPersistentBase ()=default
CrossThreadPersistentBase (const void *raw)
V8_CLANG_NO_SANITIZE (`address`) const void *GetValueFromGC() const
PersistentNode * GetNodeFromGC () const
void ClearFromGC () const
PersistentNode * GetNodeSafe () const
void SetNodeSafe (PersistentNode *value) const
Additional Inherited Members
Detailed Description
Definition at line 22 of file cross-thread-persistent.h.
Constructor & Destructor Documentation
CrossThreadPersistentBase() [1/2]
cppgc::internal::CrossThreadPersistentBase::CrossThreadPersistentBase () [default]
CrossThreadPersistentBase() [2/2]
cppgc::internal::CrossThreadPersistentBase::CrossThreadPersistentBase (const void * raw) [inline], [explicit]
Definition at line 25 of file cross-thread-persistent.h.
: PersistentBase(raw) {}
Member Function Documentation
ClearFromGC()
void cppgc::internal::CrossThreadPersistentBase::ClearFromGC () const [inline]
Definition at line 35 of file cross-thread-persistent.h.
                           {
    raw_ = nullptr;
    SetNodeSafe(nullptr);
  }
References cppgc::internal::PersistentBase::raw_, and SetNodeSafe().
Referenced by cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::ClearFromGC().
GetNodeFromGC()
PersistentNode* cppgc::internal::CrossThreadPersistentBase::GetNodeFromGC () const [inline]
Definition at line 32 of file cross-thread-persistent.h.
{ return node_; }
References cppgc::internal::PersistentBase::node_.
Referenced by cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::ClearFromGC().
GetNodeSafe()
PersistentNode* cppgc::internal::CrossThreadPersistentBase::GetNodeSafe () const [inline]
Definition at line 42 of file cross-thread-persistent.h.
                                      {
    return reinterpret_cast<std::atomic<PersistentNode*>*>(&node_)->load(
        std::memory_order_acquire);
  }
References cppgc::internal::PersistentBase::node_.
Referenced by cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::~BasicCrossThreadPersistent().
SetNodeSafe()
void cppgc::internal::CrossThreadPersistentBase::SetNodeSafe (PersistentNode * value) const [inline]
Definition at line 49 of file cross-thread-persistent.h.
                                                {
#if defined(__has_feature)
#if __has_feature(address_sanitizer)
#define V8_IS_ASAN 1
#endif
#endif
#ifdef V8_IS_ASAN
    __atomic_store(&node_, &value, __ATOMIC_RELEASE);
#else // !V8_IS_ASAN
    // Non-ASAN builds can use atomics. This also covers MSVC which does not
    // have the __atomic_store intrinsic.
    reinterpret_cast<std::atomic<PersistentNode*>*>(&node_)->store(
        value, std::memory_order_release);
#endif // !V8_IS_ASAN
#undef V8_IS_ASAN
  }
References cppgc::internal::PersistentBase::node_, store(), and v8::internal::value.
Referenced by ClearFromGC().
V8_CLANG_NO_SANITIZE()
cppgc::internal::CrossThreadPersistentBase::V8_CLANG_NO_SANITIZE (`address`) const [inline]
Definition at line 27 of file cross-thread-persistent.h.
                                                                     {
    return raw_;
  }
References cppgc::internal::PersistentBase::raw_.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/cppgc/cross-thread-persistent.h