v8::internal::TNode< T > Class Template Reference
#include <tnode.h>
Public Member Functions
template<class U >
TNode (const TNode< U > &other) V8_NOEXCEPT requires(is_subtype< U
TNode (const TNode &other) V8_NOEXCEPT
TNode ()
TNode operator= (TNode other)
operator compiler::Node * () const
operator bool () const
Static Public Member Functions
static TNode UncheckedCast (compiler::Node *node)
Protected Member Functions
TNode (compiler::Node *node)
void LazyTemplateChecks () const
Protected Attributes
compiler::Node * node_
Friends
template<typename U >
class TNode
Detailed Description
template<class T>
class v8::internal::TNode< T >
Definition at line 391 of file tnode.h.
Constructor & Destructor Documentation
TNode() [1/4]
template<class T >
template<class U >
v8::internal::TNode< T >::TNode (const TNode< U > & other)
References v8::internal::TNode< T >::LazyTemplateChecks().
TNode() [2/4]
template<class T >
v8::internal::TNode< T >::TNode (const TNode< T > & other) [inline]
Definition at line 400 of file tnode.h.
: node_(other.node_) {}
TNode() [3/4]
template<class T >
v8::internal::TNode< T >::TNode () [inline]
Definition at line 401 of file tnode.h.
: node_(nullptr) {}
TNode() [4/4]
template<class T >
v8::internal::TNode< T >::TNode (compiler::Node * node) [inline], [explicit], [protected]
Definition at line 419 of file tnode.h.
: node_(node) { LazyTemplateChecks(); }
References v8::internal::TNode< T >::LazyTemplateChecks().
Member Function Documentation
LazyTemplateChecks()
template<class T >
void v8::internal::TNode< T >::LazyTemplateChecks () const [inline], [protected]
Definition at line 421 of file tnode.h.
                                  {
    static_assert(is_valid_type_tag<T>::value, "invalid type tag");
  }
Referenced by v8::internal::TNode< T >::TNode().
operator bool()
template<class T >
v8::internal::TNode< T >::operator bool () const [inline], [explicit]
Definition at line 411 of file tnode.h.
{ return node_ != nullptr; }
References v8::internal::TNode< T >::node_.
operator compiler::Node *()
template<class T >
v8::internal::TNode< T >::operator compiler::Node * () const [inline]
Definition at line 409 of file tnode.h.
{ return node_; }
References v8::internal::TNode< T >::node_.
operator=()
template<class T >
TNode v8::internal::TNode< T >::operator= (TNode< T > other) [inline]
Definition at line 403 of file tnode.h.
                               {
    DCHECK_NOT_NULL(other.node_);
    node_ = other.node_;
    return *this;
  }
References DCHECK_NOT_NULL, and v8::internal::TNode< T >::node_.
UncheckedCast()
template<class T >
static TNode v8::internal::TNode< T >::UncheckedCast (compiler::Node * node) [inline], [static]
Definition at line 413 of file tnode.h.
{ return TNode(node); }
References v8::internal::TNode< T >::TNode.
Referenced by v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::CodeStubAssembler::AllocatePropertyDictionary(), v8::internal::CodeStubAssembler::AllocatePropertyDictionaryWithCapacity(), v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallReducerAssembler::Argument(), v8::internal::compiler::JSCallReducerAssembler::ArgumentAs(), v8::internal::compiler::JSCallReducerAssembler::ArgumentOrNaN(), v8::internal::compiler::JSCallReducerAssembler::ArgumentOrUndefined(), v8::internal::compiler::JSCallReducerAssembler::ArgumentOrZero(), v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::AssignPhi(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildByteLength(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildLength(), v8::internal::compiler::JSCallReducerAssembler::Call4(), v8::internal::compiler::FastApiCallNode::CallbackData(), v8::internal::compiler::GraphAssembler::ChangeUint32ToUintPtr(), v8::internal::compiler::JSGraphAssembler::Constant(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::SimplifiedNodeWrapperBase::context(), v8::internal::compiler::FastApiCallNode::Context(), v8::internal::compiler::JSCallReducerAssembler::ContextInput(), v8::internal::compiler::FastApiCallNode::FastCallArgument(), v8::internal::compiler::JSCallOrConstructNode::feedback_vector(), v8::internal::MicrotaskQueueBuiltinsAssembler::GetCurrentContext(), v8::internal::IteratorBuiltinsAssembler::GetIterator(), v8::internal::compiler::JSGraphAssembler::HeapConstant(), v8::internal::compiler::JSGraphAssembler::LoadElement(), v8::internal::compiler::JSGraphAssembler::LoadElementsKind(), v8::internal::compiler::JSGraphAssembler::LoadField(), v8::internal::compiler::GraphAssembler::LoadMap(), v8::internal::compiler::JSGraphAssembler::LoadMap(), v8::internal::compiler::JSGraphAssembler::LookupByteShiftForElementsKind(), v8::internal::compiler::JSGraphAssembler::LookupByteSizeForElementsKind(), v8::internal::compiler::JSGraphAssembler::MachineSelect(), v8::internal::compiler::JSGraphAssembler::CatchScope::MergeExceptionalPaths(), v8::internal::compiler::JSGraphAssembler::NumberConstant(), v8::internal::compiler::CodeAssembler::CheckedNode< PreviousType, FromTyped >::operator TNode< A >(), v8::internal::compiler::GraphAssemblerLabel< VarCount >::PhiAt(), v8::internal::compiler::JSCallReducerAssembler::ReceiverInputAs(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), v8::internal::compiler::JSCallReducerAssembler::ReduceMathBinary(), v8::internal::compiler::JSCallReducerAssembler::ReduceMathUnary(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharCodeAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSubstring(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength(), v8::internal::compiler::CodeAssembler::ReinterpretCast(), v8::internal::compiler::FastApiCallNode::SlowCallArgument(), v8::internal::compiler::JSGraphAssembler::SmiConstant(), v8::internal::WasmBuiltinsAssembler::StringToFloat64(), v8::internal::compiler::GraphAssembler::TypeGuard(), v8::internal::compiler::JSCallReducerAssembler::TypeGuardFixedArrayLength(), v8::internal::compiler::JSCallReducerAssembler::TypeGuardNonInternal(), v8::internal::compiler::JSCallReducerAssembler::TypeGuardUnsignedSmall(), v8::internal::compiler::GraphAssembler::Uint32Constant(), v8::internal::compiler::GraphAssembler::UintPtrAdd(), v8::internal::compiler::GraphAssembler::UintPtrConstant(), v8::internal::compiler::GraphAssembler::UintPtrDiv(), v8::internal::compiler::GraphAssembler::UintPtrSub(), v8::internal::compiler::CodeAssembler::UncheckedCast(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::Value(), and v8::internal::compiler::TypedCodeAssemblerVariable< T >::value().
Friends And Related Function Documentation
TNode
template<class T >
template<typename U >
friend class TNode [friend]
Definition at line 417 of file tnode.h.
Referenced by v8::internal::TNode< T >::UncheckedCast().
Member Data Documentation
node_
template<class T >
compiler::Node* v8::internal::TNode< T >::node_ [protected]
Definition at line 425 of file tnode.h.
Referenced by v8::internal::TNode< T >::operator bool(), v8::internal::TNode< T >::operator compiler::Node *(), and v8::internal::TNode< T >::operator=().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/tnode.h