v8::internal::IgnitionStatisticsExtension Class Reference
#include <ignition-statistics-extension.h>
Public Member Functions
IgnitionStatisticsExtension ()
v8::Local< v8::FunctionTemplate > GetNativeFunctionTemplate (v8::Isolate *isolate, v8::Local< v8::String > name) override
Static Public Member Functions
static void GetIgnitionDispatchCounters (const v8::FunctionCallbackInfo< v8::Value > &info)
Static Private Attributes
static const char *const kSource
Detailed Description
Definition at line 17 of file ignition-statistics-extension.h.
Constructor & Destructor Documentation
IgnitionStatisticsExtension()
v8::internal::IgnitionStatisticsExtension::IgnitionStatisticsExtension () [inline]
Definition at line 19 of file ignition-statistics-extension.h.
      : v8::Extension("v8/ignition-statistics", kSource) {}
Member Function Documentation
GetIgnitionDispatchCounters()
void v8::internal::IgnitionStatisticsExtension::GetIgnitionDispatchCounters (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 30 of file ignition-statistics-extension.cc.
                                                 {
  DCHECK(ValidateCallbackInfo(info));
  info.GetReturnValue().Set(
      Utils::ToLocal(reinterpret_cast<Isolate*>(info.GetIsolate())
                         ->interpreter()
                         ->GetDispatchCountersObject()));
}
References v8::internal::DCHECK(), v8::internal::interpreter::Interpreter::GetDispatchCountersObject(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::Isolate::interpreter(), and v8::internal::ValidateCallbackInfo().
Referenced by GetNativeFunctionTemplate().
GetNativeFunctionTemplate()
v8::Local< v8::FunctionTemplate > v8::internal::IgnitionStatisticsExtension::GetNativeFunctionTemplate (v8::Isolate * isolate, v8::Local< v8::String > name) [override], [virtual]
Reimplemented from v8::Extension.
Definition at line 18 of file ignition-statistics-extension.cc.
                                                {
  DCHECK_EQ(strcmp(*v8::String::Utf8Value(isolate, name),
                   "getIgnitionDispatchCounters"),
            0);
  return v8::FunctionTemplate::New(
      isolate, IgnitionStatisticsExtension::GetIgnitionDispatchCounters);
}
References DCHECK_EQ, GetIgnitionDispatchCounters(), v8::Extension::name(), and v8::FunctionTemplate::New().
Member Data Documentation
kSource
const char *const v8::internal::IgnitionStatisticsExtension::kSource [static], [private]
Initial value:
=
    "native function getIgnitionDispatchCounters();"
Definition at line 29 of file ignition-statistics-extension.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/extensions/ignition-statistics-extension.h
/mnt/V8SourceCode/src/extensions/ignition-statistics-extension.cc