v8::internal::StringCharacterStream Class Reference
#include <string-inl.h>
Public Member Functions
StringCharacterStream (Tagged< String > string, int offset=0)
StringCharacterStream (const StringCharacterStream &)=delete
StringCharacterStream & operator= (const StringCharacterStream &)=delete
uint16_t GetNext ()
bool HasMore ()
void Reset (Tagged< String > string, int offset=0)
void VisitOneByteString (const uint8_t *chars, int length)
void VisitTwoByteString (const uint16_t *chars, int length)
size_t CountUtf8Bytes (uint32_t n_chars)
size_t WriteUtf8Bytes (uint32_t n_chars, char *output, size_t output_capacity)
Private Attributes
ConsStringIterator iter_
bool is_one_byte_
xx xx xx xx xx xx xx xx xx
union {
 const uint8_t * buffer8_
 const uint16_t * buffer16_
};
const uint8_t * end_
SharedStringAccessGuardIfNeeded access_guard_
Detailed Description
Definition at line 1639 of file string-inl.h.
Constructor & Destructor Documentation
StringCharacterStream() [1/2]
v8::internal::StringCharacterStream::StringCharacterStream (Tagged< String > string, int offset = 0) [inline], [explicit]
Definition at line 1682 of file string-inl.h.
    : is_one_byte_(false), access_guard_(string) {
  Reset(string, offset);
}
References Reset().
StringCharacterStream() [2/2]
v8::internal::StringCharacterStream::StringCharacterStream (const StringCharacterStream &) [delete]
Member Function Documentation
CountUtf8Bytes()
size_t v8::internal::StringCharacterStream::CountUtf8Bytes (uint32_t n_chars) [inline]
Definition at line 1726 of file string-inl.h.
                                                                    {
  size_t utf8_bytes = 0;
  uint32_t remaining_chars = n_chars;
  uint16_t last = unibrow::Utf16::kNoPreviousCharacter;
  while (HasMore() && remaining_chars-- != 0) {
    uint16_t character = GetNext();
    utf8_bytes += unibrow::Utf8::Length(character, last);
    last = character;
  }
  return utf8_bytes;
}
References v8::internal::character, GetNext(), HasMore(), unibrow::Utf16::kNoPreviousCharacter, and unibrow::Utf8::Length().
Referenced by v8::internal::String::ToCString(), and v8::internal::String::ToStdString().
GetNext()
uint16_t v8::internal::StringCharacterStream::GetNext () [inline]
Definition at line 1671 of file string-inl.h.
                                        {
  DCHECK(buffer8_ != nullptr && end_ != nullptr);
  // Advance cursor if needed.
  if (buffer8_ == end_) HasMore();
  DCHECK(buffer8_ < end_);
  return is_one_byte_ ? *buffer8_++ : *buffer16_++;
}
References v8::internal::DCHECK().
Referenced by v8::internal::anonymous_namespace{builtins-string.cc}::ConvertCaseHelper(), CountUtf8Bytes(), v8::internal::String::DoesNotContainEscapeCharacters(), v8::internal::compiler::PrintCode(), v8::internal::String::PrintUC16(), v8::internal::StringStream::Put(), v8::internal::RUNTIME_FUNCTION(), and WriteUtf8Bytes().
HasMore()
bool v8::internal::StringCharacterStream::HasMore () [inline]
Definition at line 1701 of file string-inl.h.
                                    {
  if (buffer8_ != end_) return true;
  int offset;
  Tagged<String> string = iter_.Next(&offset);
  DCHECK_EQ(offset, 0);
  if (string.is_null()) return false;
  String::VisitFlat(this, string, 0, access_guard_);
  DCHECK(buffer8_ != end_);
  return true;
}
References access_guard_, buffer8_, v8::internal::DCHECK(), DCHECK_EQ, end_, iter_, v8::internal::ConsStringIterator::Next(), and v8::internal::String::VisitFlat().
Referenced by v8::internal::anonymous_namespace{builtins-string.cc}::ConvertCaseHelper(), CountUtf8Bytes(), v8::internal::String::DoesNotContainEscapeCharacters(), v8::internal::compiler::PrintCode(), v8::internal::String::PrintUC16(), v8::internal::StringStream::Put(), v8::internal::RUNTIME_FUNCTION(), and WriteUtf8Bytes().
operator=()
StringCharacterStream& v8::internal::StringCharacterStream::operator= (const StringCharacterStream &) [delete]
Reset()
void v8::internal::StringCharacterStream::Reset (Tagged< String > string, int offset = 0) [inline]
Definition at line 1687 of file string-inl.h.
                                                                   {
  buffer8_ = nullptr;
  end_ = nullptr;
  Tagged<ConsString> cons_string =
      String::VisitFlat(this, string, offset, access_guard_);
  iter_.Reset(cons_string, offset);
  if (!cons_string.is_null()) {
    string = iter_.Next(&offset);
    if (!string.is_null())
      String::VisitFlat(this, string, offset, access_guard_);
  }
}
References access_guard_, buffer8_, end_, v8::internal::Tagged< HeapObject >::is_null(), iter_, v8::internal::ConsStringIterator::Next(), v8::internal::ConsStringIterator::Reset(), and v8::internal::String::VisitFlat().
Referenced by StringCharacterStream(), v8::internal::String::ToCString(), and v8::internal::String::ToStdString().
VisitOneByteString()
void v8::internal::StringCharacterStream::VisitOneByteString (const uint8_t * chars, int length) [inline]
Definition at line 1712 of file string-inl.h.
                                                           {
  is_one_byte_ = true;
  buffer8_ = chars;
  end_ = chars + length;
}
References buffer8_, end_, is_one_byte_, and v8::internal::length.
VisitTwoByteString()
void v8::internal::StringCharacterStream::VisitTwoByteString (const uint16_t * chars, int length) [inline]
Definition at line 1719 of file string-inl.h.
                                                           {
  is_one_byte_ = false;
  buffer16_ = chars;
  end_ = reinterpret_cast<const uint8_t*>(chars + length);
}
References buffer16_, end_, is_one_byte_, and v8::internal::length.
WriteUtf8Bytes()
size_t v8::internal::StringCharacterStream::WriteUtf8Bytes (uint32_t n_chars, char * output, size_t output_capacity) [inline]
Definition at line 1738 of file string-inl.h.
                                                                            {
  size_t pos = 0;
  uint32_t remaining_chars = n_chars;
  uint16_t last = unibrow::Utf16::kNoPreviousCharacter;
  while (HasMore() && remaining_chars-- != 0) {
    uint16_t character = GetNext();
    if (character == 0) {
      character = ' ';
    }
    // Ensure that there's sufficient space for this character.
    //
    // This should normally always be the case, unless there is
    // in-sandbox memory corruption.
    // Alternatively, we could also over-allocate the output buffer by three
    // bytes (the maximum we can write OOB) or consider allocating it inside
    // the sandbox, but it's not clear if that would be worth the effort as the
    // performance overhead of this check appears to be negligible in practice.
    SBXCHECK_LE(unibrow::Utf8::Length(character, last), output_capacity - pos);
    pos += unibrow::Utf8::Encode(output + pos, character, last);
    last = character;
  }
  return pos;
}
References v8::internal::character, unibrow::Utf8::Encode(), GetNext(), HasMore(), unibrow::Utf16::kNoPreviousCharacter, unibrow::Utf8::Length(), and SBXCHECK_LE.
Referenced by v8::internal::String::ToCString(), and v8::internal::String::ToStdString().
Member Data Documentation
union { ... } [private]
access_guard_
SharedStringAccessGuardIfNeeded v8::internal::StringCharacterStream::access_guard_ [private]
Definition at line 1668 of file string-inl.h.
Referenced by HasMore(), and Reset().
buffer16_
const uint16_t* v8::internal::StringCharacterStream::buffer16_
Definition at line 1665 of file string-inl.h.
Referenced by VisitTwoByteString().
buffer8_
const uint8_t* v8::internal::StringCharacterStream::buffer8_
Definition at line 1664 of file string-inl.h.
Referenced by HasMore(), Reset(), and VisitOneByteString().
end_
const uint8_t* v8::internal::StringCharacterStream::end_ [private]
Definition at line 1667 of file string-inl.h.
Referenced by HasMore(), Reset(), VisitOneByteString(), and VisitTwoByteString().
is_one_byte_
bool v8::internal::StringCharacterStream::is_one_byte_ [private]
Definition at line 1662 of file string-inl.h.
Referenced by VisitOneByteString(), and VisitTwoByteString().
iter_
ConsStringIterator v8::internal::StringCharacterStream::iter_ [private]
Definition at line 1661 of file string-inl.h.
Referenced by HasMore(), and Reset().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/string-inl.h