v8::internal::StringBuiltinsReducer< Next > Class Template Reference
Public Member Functions
void CopyStringCharacters (V< String > src_string, ConstOrV< WordPtr > src_begin, String::Encoding src_encoding, V< String > dst_string, ConstOrV< WordPtr > dst_begin, String::Encoding dst_encoding, ConstOrV< WordPtr > character_count)
V< SeqOneByteString > AllocateSeqOneByteString (V< WordPtr > length)
V< SeqTwoByteString > AllocateSeqTwoByteString (V< WordPtr > length)
Detailed Description
template<typename Next>
class v8::internal::StringBuiltinsReducer< Next >
Definition at line 21 of file builtins-string-tsa.cc.
Member Function Documentation
AllocateSeqOneByteString()
template<typename Next >
V<SeqOneByteString> v8::internal::StringBuiltinsReducer< Next >::AllocateSeqOneByteString (V< WordPtr > length) [inline]
Definition at line 66 of file builtins-string-tsa.cc.
                                                                  {
    __ CodeComment("AllocateSeqOneByteString");
    Label<SeqOneByteString> done(this);
    GOTO_IF(__ WordPtrEqual(length, 0), done,
            V<SeqOneByteString>::Cast(__ EmptyStringConstant()));
    V<WordPtr> object_size =
        __ WordPtrAdd(sizeof(SeqOneByteString),
                      __ WordPtrMul(length, sizeof(SeqOneByteString::Char)));
    V<WordPtr> aligned_size = __ AlignTagged(object_size);
    Uninitialized<SeqOneByteString> new_string =
        __ template Allocate<SeqOneByteString>(aligned_size,
                                               AllocationType::kYoung);
    __ InitializeField(new_string, AccessBuilderTS::ForMap(),
                       __ SeqOneByteStringMapConstant());
    __ InitializeField(new_string, AccessBuilderTS::ForStringLength(),
                       __ TruncateWordPtrToWord32(length));
    __ InitializeField(new_string, AccessBuilderTS::ForNameRawHashField(),
                       Name::kEmptyHashField);
    V<SeqOneByteString> string = __ FinishInitialization(std::move(new_string));
    // Clear padding.
    V<WordPtr> raw_padding_begin = __ WordPtrAdd(
        __ WordPtrAdd(__ BitcastTaggedToWordPtr(string), aligned_size),
        -kObjectAlignment - kHeapObjectTag);
    static_assert(kObjectAlignment ==
                  MemoryRepresentation::TaggedSigned().SizeInBytes());
    __ Store(raw_padding_begin, {}, __ SmiConstant(0),
             StoreOp::Kind::RawAligned(), MemoryRepresentation::TaggedSigned(),
             compiler::kNoWriteBarrier, 0, 0, true);
    GOTO(done, string);
    BIND(done, result);
    return result;
  }
References __, v8::internal::compiler::turboshaft::AccessBuilderTS::ForMap(), v8::internal::Name::kEmptyHashField, v8::internal::kHeapObjectTag, v8::internal::compiler::kNoWriteBarrier, v8::internal::kObjectAlignment, v8::internal::kYoung, v8::internal::length, v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::base::internal::result, v8::internal::wasm::liftoff::Store(), and v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedSigned().
AllocateSeqTwoByteString()
template<typename Next >
V<SeqTwoByteString> v8::internal::StringBuiltinsReducer< Next >::AllocateSeqTwoByteString (V< WordPtr > length) [inline]
Definition at line 102 of file builtins-string-tsa.cc.
                                                                  {
    __ CodeComment("AllocateSeqTwoByteString");
    Label<SeqTwoByteString> done(this);
    GOTO_IF(__ WordPtrEqual(length, 0), done,
            V<SeqTwoByteString>::Cast(__ EmptyStringConstant()));
    V<WordPtr> object_size =
        __ WordPtrAdd(sizeof(SeqTwoByteString),
                      __ WordPtrMul(length, sizeof(SeqTwoByteString::Char)));
    V<WordPtr> aligned_size = __ AlignTagged(object_size);
    Uninitialized<SeqTwoByteString> new_string =
        __ template Allocate<SeqTwoByteString>(aligned_size,
                                               AllocationType::kYoung);
    __ InitializeField(new_string, AccessBuilderTS::ForMap(),
                       __ SeqTwoByteStringMapConstant());
    __ InitializeField(new_string, AccessBuilderTS::ForStringLength(),
                       __ TruncateWordPtrToWord32(length));
    __ InitializeField(new_string, AccessBuilderTS::ForNameRawHashField(),
                       Name::kEmptyHashField);
    V<SeqTwoByteString> string = __ FinishInitialization(std::move(new_string));
    // Clear padding.
    V<WordPtr> raw_padding_begin = __ WordPtrAdd(
        __ WordPtrAdd(__ BitcastTaggedToWordPtr(string), aligned_size),
        -kObjectAlignment - kHeapObjectTag);
    static_assert(kObjectAlignment ==
                  MemoryRepresentation::TaggedSigned().SizeInBytes());
    __ Store(raw_padding_begin, {}, __ SmiConstant(0),
             StoreOp::Kind::RawAligned(), MemoryRepresentation::TaggedSigned(),
             compiler::kNoWriteBarrier, 0, 0, true);
    GOTO(done, string);
    BIND(done, result);
    return result;
  }
References __, v8::internal::compiler::turboshaft::AccessBuilderTS::ForMap(), v8::internal::Name::kEmptyHashField, v8::internal::kHeapObjectTag, v8::internal::compiler::kNoWriteBarrier, v8::internal::kObjectAlignment, v8::internal::kYoung, v8::internal::length, v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::base::internal::result, v8::internal::wasm::liftoff::Store(), and v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedSigned().
CopyStringCharacters()
template<typename Next >
void v8::internal::StringBuiltinsReducer< Next >::CopyStringCharacters (V< String > src_string, ConstOrV< WordPtr > src_begin, String::Encoding src_encoding, V< String > dst_string, ConstOrV< WordPtr > dst_begin, String::Encoding dst_encoding, ConstOrV< WordPtr > character_count) [inline]
Definition at line 25 of file builtins-string-tsa.cc.
                                                               {
    bool src_one_byte = src_encoding == String::ONE_BYTE_ENCODING;
    bool dst_one_byte = dst_encoding == String::ONE_BYTE_ENCODING;
    __ CodeComment("CopyStringCharacters ",
                   src_one_byte ? "ONE_BYTE_ENCODING" : "TWO_BYTE_ENCODING",
                   " -> ",
                   dst_one_byte ? "ONE_BYTE_ENCODING" : "TWO_BYTE_ENCODING");
    const auto dst_rep = dst_one_byte ? MemoryRepresentation::Uint8()
                                      : MemoryRepresentation::Uint16();
    static_assert(OFFSET_OF_DATA_START(SeqOneByteString) ==
                  OFFSET_OF_DATA_START(SeqTwoByteString));
    const size_t data_offset = OFFSET_OF_DATA_START(SeqOneByteString);
    const int dst_stride = dst_one_byte ? 1 : 2;
    DisallowGarbageCollection no_gc;
    V<WordPtr> dst_begin_offset =
        __ WordPtrAdd(__ BitcastTaggedToWordPtr(dst_string),
                      __ WordPtrAdd(data_offset - kHeapObjectTag,
                                    __ WordPtrMul(dst_begin, dst_stride)));
    StringView src_view(no_gc, src_string, src_encoding, src_begin,
                        character_count);
    FOREACH(src_char, dst_offset,
            Zip(src_view, Sequence(dst_begin_offset, dst_stride))) {
#if DEBUG
      // Copying two-byte characters to one-byte is okay if callers have
      // checked that this loses no information.
      if (v8_flags.debug_code && !src_one_byte && dst_one_byte) {
        TSA_DCHECK(this, __ Uint32LessThanOrEqual(src_char, 0xFF));
      }
#endif
      __ Store(dst_offset, src_char, StoreOp::Kind::RawAligned(), dst_rep,
               compiler::kNoWriteBarrier);
    }
  }
References __, v8::internal::kHeapObjectTag, v8::internal::compiler::kNoWriteBarrier, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, OFFSET_OF_DATA_START, v8::internal::String::ONE_BYTE_ENCODING, v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::compiler::turboshaft::Sequence(), v8::internal::wasm::liftoff::Store(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), v8::internal::v8_flags, and v8::internal::compiler::turboshaft::Zip().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-string-tsa.cc