v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler > Class Template Reference
#include <assembler.h>
Classes
struct ControlFlowHelper_IfState
Public Types
using assembler_t = Assembler
using block_t = Block
Public Member Functions
assembler_t & Asm ()
template<typename L >
auto ControlFlowHelper_Bind (L &label) -> base::prepend_tuple_type< bool, typename L::values_t >
template<typename L >
auto ControlFlowHelper_BindLoop (L &label) -> base::prepend_tuple_type< bool, typename L::values_t >
template<typename L >
void ControlFlowHelper_EndLoop (L &label)
template<ForeachIterable< assembler_t > It>
auto ControlFlowHelper_Foreach (It iterable)
template<ForeachIterable< assembler_t > It>
void ControlFlowHelper_EndForeachLoop (It iterable, LoopLabelFor< typename It::iterator_type > &header_label, Label<> &exit_label, typename It::iterator_type current_iterator)
std::tuple< bool, LoopLabel<>, Label<> > ControlFlowHelper_While (std::function< V< Word32 >()> cond_builder)
template<typename L1 , typename L2 >
void ControlFlowHelper_EndWhileLoop (L1 &header_label, L2 &exit_label)
template<typename L >
void ControlFlowHelper_Goto (L &label, const typename L::const_or_values_t &values)
template<typename L >
void ControlFlowHelper_GotoIf (ConditionWithHint condition, L &label, const typename L::const_or_values_t &values)
template<typename L >
void ControlFlowHelper_GotoIfNot (ConditionWithHint condition, L &label, const typename L::const_or_values_t &values)
bool ControlFlowHelper_BindIf (ConditionWithHint condition, ControlFlowHelper_IfState *state)
bool ControlFlowHelper_BindIfNot (ConditionWithHint condition, ControlFlowHelper_IfState *state)
bool ControlFlowHelper_BindElse (ControlFlowHelper_IfState *state)
void ControlFlowHelper_FinishIfBlock (ControlFlowHelper_IfState *state)
void ControlFlowHelper_EndIf (ControlFlowHelper_IfState *state)
Detailed Description
template<typename Assembler>
class v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >
Definition at line 1346 of file assembler.h.
Member Typedef Documentation
assembler_t
template<typename Assembler >
using v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::assembler_t = Assembler
Definition at line 1348 of file assembler.h.
block_t
template<typename Assembler >
using v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::block_t = Block
Definition at line 1349 of file assembler.h.
Member Function Documentation
Asm()
template<typename Assembler >
assembler_t& v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::Asm () [inline]
Definition at line 1350 of file assembler.h.
{ return *static_cast<assembler_t*>(this); }
ControlFlowHelper_Bind()
template<typename Assembler >
template<typename L >
auto v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_Bind (L & label) -> base::prepend_tuple_type<bool, typename L::values_t> [inline]
Definition at line 1355 of file assembler.h.
                                                          {
    // LoopLabels need to be bound with `BIND_LOOP` instead of `BIND`.
    static_assert(!L::is_loop);
    return label.Bind(Asm());
  }
ControlFlowHelper_BindElse()
template<typename Assembler >
bool v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_BindElse (ControlFlowHelper_IfState * state) [inline]
Definition at line 1499 of file assembler.h.
                                                                    {
    block_t* else_block = state->else_block;
    state->else_block = nullptr;
    return Asm().Bind(else_block);
  }
References v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_IfState::else_block.
ControlFlowHelper_BindIf()
template<typename Assembler >
bool v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_BindIf (ConditionWithHint condition, ControlFlowHelper_IfState * state) [inline]
Definition at line 1481 of file assembler.h.
                                                                  {
    block_t* then_block = Asm().NewBlock();
    state->else_block = Asm().NewBlock();
    state->end_block = Asm().NewBlock();
    Asm().Branch(condition, then_block, state->else_block);
    return Asm().Bind(then_block);
  }
References v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_IfState::else_block, and v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_IfState::end_block.
ControlFlowHelper_BindIfNot()
template<typename Assembler >
bool v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_BindIfNot (ConditionWithHint condition, ControlFlowHelper_IfState * state) [inline]
Definition at line 1490 of file assembler.h.
                                                                     {
    block_t* then_block = Asm().NewBlock();
    state->else_block = Asm().NewBlock();
    state->end_block = Asm().NewBlock();
    Asm().Branch(condition, state->else_block, then_block);
    return Asm().Bind(then_block);
  }
References v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_IfState::else_block, and v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_IfState::end_block.
ControlFlowHelper_BindLoop()
template<typename Assembler >
template<typename L >
auto v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_BindLoop (L & label) -> base::prepend_tuple_type<bool, typename L::values_t> [inline]
Definition at line 1363 of file assembler.h.
                                                          {
    // Only LoopLabels can be bound with `BIND_LOOP`. Otherwise use `BIND`.
    static_assert(L::is_loop);
    return label.BindLoop(Asm());
  }
ControlFlowHelper_EndForeachLoop()
template<typename Assembler >
template<ForeachIterable< assembler_t > It>
void v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_EndForeachLoop (It iterable, LoopLabelFor< typename It::iterator_type > & header_label, Label<> & exit_label, typename It::iterator_type current_iterator) [inline]
Definition at line 1419 of file assembler.h.
                                                                      {
    typename It::iterator_type next_iterator =
        iterable.Advance(Asm(), current_iterator);
    ControlFlowHelper_Goto(header_label, {next_iterator});
    ControlFlowHelper_EndLoop(header_label);
    ControlFlowHelper_Bind(exit_label);
  }
ControlFlowHelper_EndIf()
template<typename Assembler >
void v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_EndIf (ControlFlowHelper_IfState * state) [inline]
Definition at line 1510 of file assembler.h.
                                                                 {
    if (state->else_block) {
      if (Asm().Bind(state->else_block)) {
        Asm().Goto(state->end_block);
      }
    }
    Asm().Bind(state->end_block);
  }
References v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_IfState::else_block, and v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_IfState::end_block.
ControlFlowHelper_EndLoop()
template<typename Assembler >
template<typename L >
void v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_EndLoop (L & label) [inline]
Definition at line 1371 of file assembler.h.
                                           {
    static_assert(L::is_loop);
    label.EndLoop(Asm());
  }
ControlFlowHelper_EndWhileLoop()
template<typename Assembler >
template<typename L1 , typename L2 >
void v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_EndWhileLoop (L1 & header_label, L2 & exit_label) [inline]
Definition at line 1444 of file assembler.h.
                                                                        {
    static_assert(L1::is_loop);
    static_assert(!L2::is_loop);
    ControlFlowHelper_Goto(header_label, {});
    ControlFlowHelper_EndLoop(header_label);
    ControlFlowHelper_Bind(exit_label);
  }
ControlFlowHelper_FinishIfBlock()
template<typename Assembler >
void v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_FinishIfBlock (ControlFlowHelper_IfState * state) [inline]
Definition at line 1505 of file assembler.h.
                                                                         {
    if (Asm().current_block() == nullptr) return;
    Asm().Goto(state->end_block);
  }
References v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_IfState::end_block.
ControlFlowHelper_Foreach()
template<typename Assembler >
template<ForeachIterable< assembler_t > It>
auto v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_Foreach (It iterable) [inline]
Definition at line 1377 of file assembler.h.
                                              {
    // We need to take ownership over the `iterable` instance as we need to make
    // sure that the `ControlFlowHelper_Foreach` and
    // `ControlFlowHelper_EndForeachLoop` functions operate on the same object.
    // This can potentially involve copying the `iterable` if it is not moved to
    // the `FOREACH` macro. `ForeachIterable`s should be cheap to copy and they
    // MUST NOT emit any code in their constructors/destructors.
#ifdef DEBUG
    OpIndex next_index = Asm().output_graph().next_operation_index();
    {
      It temp_copy = iterable;
      USE(temp_copy);
    }
    // Make sure we have not emitted any operations.
    DCHECK_EQ(next_index, Asm().output_graph().next_operation_index());
#endif
    LoopLabelFor<typename It::iterator_type> loop_header(this);
    Label<> loop_exit(this);
    typename It::iterator_type begin = iterable.Begin(Asm());
    ControlFlowHelper_Goto(loop_header, {begin});
    auto bound_and_current_iterator = loop_header.BindLoop(Asm());
    auto [bound] = base::tuple_head<1>(bound_and_current_iterator);
    auto current_iterator = detail::unwrap_unary_tuple(
        base::tuple_drop<1>(bound_and_current_iterator));
    OptionalV<Word32> is_end = iterable.IsEnd(Asm(), current_iterator);
    if (is_end.has_value()) {
      ControlFlowHelper_GotoIf(is_end.value(), loop_exit, {});
    }
    typename It::value_type current_value =
        iterable.Dereference(Asm(), current_iterator);
    return detail::BuildResultTuple(
        bound, std::move(iterable), std::move(loop_header),
        std::move(loop_exit), current_iterator, current_value);
  }
References v8::internal::compiler::begin(), v8::internal::compiler::turboshaft::detail::BuildResultTuple(), DCHECK_EQ, v8::internal::compiler::turboshaft::OptionalOpIndex::has_value(), v8::internal::compiler::turboshaft::detail::unwrap_unary_tuple(), USE, v8::internal::compiler::turboshaft::OptionalV< T >::value(), and v8::internal::wasm::value_type().
ControlFlowHelper_Goto()
template<typename Assembler >
template<typename L >
void v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_Goto (L & label, const typename L::const_or_values_t & values) [inline]
Definition at line 1453 of file assembler.h.
                                                                         {
    auto resolved_values = detail::ResolveAll(Asm(), values);
    label.Goto(Asm(), resolved_values);
  }
References v8::internal::compiler::turboshaft::detail::ResolveAll().
ControlFlowHelper_GotoIf()
template<typename Assembler >
template<typename L >
void v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_GotoIf (ConditionWithHint condition, L & label, const typename L::const_or_values_t & values) [inline]
Definition at line 1460 of file assembler.h.
                                                                           {
    auto resolved_values = detail::ResolveAll(Asm(), values);
    label.GotoIf(Asm(), condition.condition(), condition.hint(),
                 resolved_values);
  }
References v8::internal::compiler::turboshaft::ConditionWithHint::condition(), v8::internal::compiler::turboshaft::ConditionWithHint::hint(), and v8::internal::compiler::turboshaft::detail::ResolveAll().
ControlFlowHelper_GotoIfNot()
template<typename Assembler >
template<typename L >
void v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_GotoIfNot (ConditionWithHint condition, L & label, const typename L::const_or_values_t & values) [inline]
Definition at line 1468 of file assembler.h.
                                                 {
    auto resolved_values = detail::ResolveAll(Asm(), values);
    label.GotoIfNot(Asm(), condition.condition(), condition.hint(),
                    resolved_values);
  }
References v8::internal::compiler::turboshaft::ConditionWithHint::condition(), v8::internal::compiler::turboshaft::ConditionWithHint::hint(), and v8::internal::compiler::turboshaft::detail::ResolveAll().
ControlFlowHelper_While()
template<typename Assembler >
std::tuple<bool, LoopLabel<>, Label<> > v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_While (std::function< V< Word32 >()> cond_builder) [inline]
Definition at line 1429 of file assembler.h.
                                             {
    LoopLabel<> loop_header(this);
    Label<> loop_exit(this);
    ControlFlowHelper_Goto(loop_header, {});
    auto [bound] = loop_header.BindLoop(Asm());
    V<Word32> cond = cond_builder();
    ControlFlowHelper_GotoIfNot(cond, loop_exit, {});
    return std::make_tuple(bound, std::move(loop_header), std::move(loop_exit));
  }
References v8::internal::compiler::turboshaft::LoopLabel< Ts >::BindLoop().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/assembler.h