v8::internal::AsyncBuiltinsAssembler Class Reference
#include <builtins-async-gen.h>
Public Member Functions
AsyncBuiltinsAssembler (compiler::CodeAssemblerState *state)
Protected Types
using CreateClosures = std::function< std::pair< TNode< JSFunction >, TNode< JSFunction > >(TNode< Context >, TNode< NativeContext >)>
Protected Member Functions
TNode< Object > Await (TNode< Context > context, TNode< JSGeneratorObject > generator, TNode< JSAny > value, TNode< JSPromise > outer_promise, const CreateClosures &CreateClosures)
TNode< Object > Await (TNode< Context > context, TNode< JSGeneratorObject > generator, TNode< JSAny > value, TNode< JSPromise > outer_promise, RootIndex on_resolve_sfi, RootIndex on_reject_sfi)
TNode< JSFunction > CreateUnwrapClosure (TNode< NativeContext > native_context, TNode< Boolean > done)
Private Member Functions
TNode< Context > AllocateAsyncIteratorValueUnwrapContext (TNode< NativeContext > native_context, TNode< Boolean > done)
Additional Inherited Members
Detailed Description
Definition at line 14 of file builtins-async-gen.h.
Member Typedef Documentation
CreateClosures
using v8::internal::AsyncBuiltinsAssembler::CreateClosures = std::function<std::pair<TNode<JSFunction>, TNode<JSFunction> >(TNode<Context>, TNode<NativeContext>)> [protected]
Definition at line 24 of file builtins-async-gen.h.
Constructor & Destructor Documentation
AsyncBuiltinsAssembler()
v8::internal::AsyncBuiltinsAssembler::AsyncBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 16 of file builtins-async-gen.h.
      : PromiseBuiltinsAssembler(state) {}
Member Function Documentation
AllocateAsyncIteratorValueUnwrapContext()
TNode< Context > v8::internal::AsyncBuiltinsAssembler::AllocateAsyncIteratorValueUnwrapContext (TNode< NativeContext > native_context, TNode< Boolean > done) [private]
Definition at line 170 of file builtins-async-gen.cc.
                                                              {
  CSA_DCHECK(this, IsBoolean(done));
  TNode<Context> context = AllocateSyntheticFunctionContext(
      native_context, ValueUnwrapContext::kLength);
  StoreContextElementNoWriteBarrier(context, ValueUnwrapContext::kDoneSlot,
                                    done);
  return context;
}
References v8::internal::CodeStubAssembler::IsBoolean(), v8::internal::native_context, and v8::internal::CodeStubAssembler::StoreContextElementNoWriteBarrier().
Referenced by CreateUnwrapClosure().
Await() [1/2]
TNode< Object > v8::internal::AsyncBuiltinsAssembler::Await (TNode< Context > context, TNode< JSGeneratorObject > generator, TNode< JSAny > value, TNode< JSPromise > outer_promise, const CreateClosures & CreateClosures) [protected]
Definition at line 44 of file builtins-async-gen.cc.
                                          {
  const TNode<NativeContext> native_context = LoadNativeContext(context);
  // We do the `PromiseResolve(%Promise%,value)` avoiding to unnecessarily
  // create wrapper promises. Now if {value} is already a promise with the
  // intrinsics %Promise% constructor as its "constructor", we don't need
  // to allocate the wrapper promise.
  {
    TVARIABLE(JSAny, var_value, value);
    Label if_slow_path(this, Label::kDeferred), if_done(this),
        if_slow_constructor(this, Label::kDeferred);
    GotoIf(TaggedIsSmi(value), &if_slow_path);
    TNode<JSAnyNotSmi> value_object = CAST(value);
    const TNode<Map> value_map = LoadMap(value_object);
    GotoIfNot(IsJSPromiseMap(value_map), &if_slow_path);
    // We can skip the "constructor" lookup on {value} if it's [[Prototype]]
    // is the (initial) Promise.prototype and the @@species protector is
    // intact, as that guards the lookup path for "constructor" on
    // JSPromise instances which have the (initial) Promise.prototype.
    const TNode<Object> promise_prototype = LoadContextElementNoCell(
        native_context, Context::PROMISE_PROTOTYPE_INDEX);
    GotoIfNot(TaggedEqual(LoadMapPrototype(value_map), promise_prototype),
              &if_slow_constructor);
    Branch(IsPromiseSpeciesProtectorCellInvalid(), &if_slow_constructor,
           &if_done);
    // At this point, {value} doesn't have the initial promise prototype or
    // the promise @@species protector was invalidated, but {value} could still
    // have the %Promise% as its "constructor", so we need to check that as
    // well.
    BIND(&if_slow_constructor);
    {
      const TNode<Object> value_constructor = GetProperty(
          context, value, isolate()->factory()->constructor_string());
      const TNode<Object> promise_function = LoadContextElementNoCell(
          native_context, Context::PROMISE_FUNCTION_INDEX);
      Branch(TaggedEqual(value_constructor, promise_function), &if_done,
             &if_slow_path);
    }
    BIND(&if_slow_path);
    {
      // We need to mark the {value} wrapper as having {outer_promise}
      // as its parent, which is why we need to inline a good chunk of
      // logic from the `PromiseResolve` builtin here.
      var_value = NewJSPromise(native_context, outer_promise);
      CallBuiltin(Builtin::kResolvePromise, native_context, var_value.value(),
                  value);
      Goto(&if_done);
    }
    BIND(&if_done);
    value = var_value.value();
  }
  static const int kClosureContextSize =
      FixedArray::SizeFor(Context::MIN_CONTEXT_EXTENDED_SLOTS);
  TNode<Context> closure_context =
      UncheckedCast<Context>(AllocateInNewSpace(kClosureContextSize));
  {
    // Initialize the await context, storing the {generator} as extension.
    TNode<Map> map = CAST(LoadContextElementNoCell(
        native_context, Context::AWAIT_CONTEXT_MAP_INDEX));
    StoreMapNoWriteBarrier(closure_context, map);
    StoreObjectFieldNoWriteBarrier(
        closure_context, Context::kLengthOffset,
        SmiConstant(Context::MIN_CONTEXT_EXTENDED_SLOTS));
    const TNode<Object> empty_scope_info =
        LoadContextElementNoCell(native_context, Context::SCOPE_INFO_INDEX);
    StoreContextElementNoWriteBarrier(
        closure_context, Context::SCOPE_INFO_INDEX, empty_scope_info);
    StoreContextElementNoWriteBarrier(closure_context, Context::PREVIOUS_INDEX,
                                      native_context);
    StoreContextElementNoWriteBarrier(closure_context, Context::EXTENSION_INDEX,
                                      generator);
  }
  // Allocate and initialize resolve and reject handlers
  auto [on_resolve, on_reject] =
      CreateClosures(closure_context, native_context);
  // Deal with PromiseHooks and debug support in the runtime. This
  // also allocates the throwaway promise, which is only needed in
  // case of PromiseHooks or debugging.
  TVARIABLE(Object, var_throwaway, UndefinedConstant());
  Label if_instrumentation(this, Label::kDeferred),
      if_instrumentation_done(this);
  TNode<Uint32T> promiseHookFlags = PromiseHookFlags();
  GotoIf(IsIsolatePromiseHookEnabledOrDebugIsActiveOrHasAsyncEventDelegate(
             promiseHookFlags),
         &if_instrumentation);
#ifdef V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS
  // This call to NewJSPromise is to keep behaviour parity with what happens
  // in Runtime::kDebugAsyncFunctionSuspended below if native hooks are set.
  // It creates a throwaway promise that will trigger an init event and get
  // passed into Builtin::kPerformPromiseThen below.
  GotoIfNot(IsContextPromiseHookEnabled(promiseHookFlags),
            &if_instrumentation_done);
  var_throwaway = NewJSPromise(context, value);
#endif // V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS
  Goto(&if_instrumentation_done);
  BIND(&if_instrumentation);
  {
    var_throwaway =
        CallRuntime(Runtime::kDebugAsyncFunctionSuspended, native_context,
                    value, outer_promise, on_reject, generator);
    Goto(&if_instrumentation_done);
  }
  BIND(&if_instrumentation_done);
  return CallBuiltin(Builtin::kPerformPromiseThen, native_context, value,
                     on_resolve, on_reject, var_throwaway.value());
}
References v8::internal::CodeStubAssembler::AllocateInNewSpace(), v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::CallBuiltin(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::Context::EXTENSION_INDEX, v8::internal::compiler::CodeAssembler::factory(), v8::internal::CodeStubAssembler::GetProperty(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::IsIsolatePromiseHookEnabledOrDebugIsActiveOrHasAsyncEventDelegate(), v8::internal::CodeStubAssembler::IsJSPromiseMap(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::CodeStubAssembler::IsPromiseSpeciesProtectorCellInvalid(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapPrototype(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::Context::MIN_CONTEXT_EXTENDED_SLOTS, v8::internal::native_context, v8::internal::Context::PREVIOUS_INDEX, v8::internal::CodeStubAssembler::PromiseHookFlags(), v8::internal::Context::SCOPE_INFO_INDEX, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::StoreContextElementNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreMapNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::value.
Referenced by v8::internal::AsyncFunctionBuiltinsAssembler::AsyncFunctionAwait(), and Await().
Await() [2/2]
TNode< Object > v8::internal::AsyncBuiltinsAssembler::Await (TNode< Context > context, TNode< JSGeneratorObject > generator, TNode< JSAny > value, TNode< JSPromise > outer_promise, RootIndex on_resolve_sfi, RootIndex on_reject_sfi) [protected]
Definition at line 27 of file builtins-async-gen.cc.
                                                                     {
  return Await(
      context, generator, value, outer_promise,
      [&](TNode<Context> context, TNode<NativeContext> native_context) {
        auto on_resolve = AllocateRootFunctionWithContext(
            on_resolve_sfi, context, native_context);
        auto on_reject = AllocateRootFunctionWithContext(on_reject_sfi, context,
                                                         native_context);
        return std::make_pair(on_resolve, on_reject);
      });
}
References v8::internal::CodeStubAssembler::AllocateRootFunctionWithContext(), Await(), v8::internal::native_context, and v8::internal::value.
CreateUnwrapClosure()
TNode< JSFunction > v8::internal::AsyncBuiltinsAssembler::CreateUnwrapClosure (TNode< NativeContext > native_context, TNode< Boolean > done) [protected]
Definition at line 161 of file builtins-async-gen.cc.
                                                              {
  const TNode<Context> closure_context =
      AllocateAsyncIteratorValueUnwrapContext(native_context, done);
  return AllocateRootFunctionWithContext(
      RootIndex::kAsyncIteratorValueUnwrapSharedFun, closure_context,
      native_context);
}
References AllocateAsyncIteratorValueUnwrapContext(), v8::internal::CodeStubAssembler::AllocateRootFunctionWithContext(), and v8::internal::native_context.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-async-gen.h
/mnt/V8SourceCode/src/builtins/builtins-async-gen.cc