v8::internal::CodeCommentsIterator Class Reference
#include <code-comments.h>
Public Member Functions
CodeCommentsIterator (Address code_comments_start, uint32_t code_comments_size)
uint32_t size () const
const char * GetComment () const
uint32_t GetCommentSize () const
uint32_t GetPCOffset () const
void Next ()
bool HasCurrent () const
Private Attributes
Address code_comments_start_
uint32_t code_comments_size_
Address current_entry_
Detailed Description
Definition at line 48 of file code-comments.h.
Constructor & Destructor Documentation
CodeCommentsIterator()
v8::internal::CodeCommentsIterator::CodeCommentsIterator (Address code_comments_start, uint32_t code_comments_size)
Definition at line 30 of file code-comments.cc.
    : code_comments_start_(code_comments_start),
      code_comments_size_(code_comments_size),
      current_entry_(code_comments_start + kOffsetToFirstCommentEntry) {
  DCHECK_NE(kNullAddress, code_comments_start);
  DCHECK_IMPLIES(code_comments_size,
                 code_comments_size ==
                     base::ReadUnalignedValue<uint32_t>(code_comments_start_));
}
References code_comments_start_, DCHECK_IMPLIES, DCHECK_NE, and v8::internal::kNullAddress.
Member Function Documentation
GetComment()
const char * v8::internal::CodeCommentsIterator::GetComment () const
Definition at line 43 of file code-comments.cc.
                                                   {
  const char* comment_string =
      reinterpret_cast<const char*>(current_entry_ + kOffsetToCommentString);
  CHECK_EQ(GetCommentSize(), strlen(comment_string) + 1);
  return comment_string;
}
References CHECK_EQ, current_entry_, GetCommentSize(), and v8::internal::anonymous_namespace{code-comments.cc}::kOffsetToCommentString.
GetCommentSize()
uint32_t v8::internal::CodeCommentsIterator::GetCommentSize () const
Definition at line 50 of file code-comments.cc.
                                                    {
  return ReadUnalignedValue<uint32_t>(current_entry_ + kOffsetToCommentSize);
}
References current_entry_, and v8::internal::anonymous_namespace{code-comments.cc}::kOffsetToCommentSize.
Referenced by GetComment(), and Next().
GetPCOffset()
uint32_t v8::internal::CodeCommentsIterator::GetPCOffset () const
Definition at line 54 of file code-comments.cc.
                                                 {
  return ReadUnalignedValue<uint32_t>(current_entry_ + kOffsetToPCOffset);
}
References current_entry_, and v8::internal::anonymous_namespace{code-comments.cc}::kOffsetToPCOffset.
HasCurrent()
bool v8::internal::CodeCommentsIterator::HasCurrent () const
Definition at line 62 of file code-comments.cc.
                                            {
  return current_entry_ < code_comments_start_ + size();
}
References code_comments_start_, current_entry_, and size().
Next()
void v8::internal::CodeCommentsIterator::Next ()
Definition at line 58 of file code-comments.cc.
                                {
  current_entry_ += kOffsetToCommentString + GetCommentSize();
}
References current_entry_, GetCommentSize(), and v8::internal::anonymous_namespace{code-comments.cc}::kOffsetToCommentString.
size()
uint32_t v8::internal::CodeCommentsIterator::size () const
Definition at line 41 of file code-comments.cc.
{ return code_comments_size_; }
References code_comments_size_.
Referenced by HasCurrent().
Member Data Documentation
code_comments_size_
uint32_t v8::internal::CodeCommentsIterator::code_comments_size_ [private]
Definition at line 61 of file code-comments.h.
Referenced by size().
code_comments_start_
Address v8::internal::CodeCommentsIterator::code_comments_start_ [private]
Definition at line 60 of file code-comments.h.
Referenced by CodeCommentsIterator(), and HasCurrent().
current_entry_
Address v8::internal::CodeCommentsIterator::current_entry_ [private]
Definition at line 62 of file code-comments.h.
Referenced by GetComment(), GetCommentSize(), GetPCOffset(), HasCurrent(), and Next().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/code-comments.h
/mnt/V8SourceCode/src/codegen/code-comments.cc