v8::internal::ObjectVisitorForwarder Class Reference
Public Member Functions
ObjectVisitorForwarder (Isolate *isolate, ObjectVisitor *visitor)
ObjectVisitorForwarder (LocalIsolate *isolate, ObjectVisitor *visitor)
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) override
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) override
void VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) override
void VisitCustomWeakPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) override
void VisitPointer (Tagged< HeapObject > host, ObjectSlot slot) override
void VisitPointer (Tagged< HeapObject > host, MaybeObjectSlot slot) override
void VisitCustomWeakPointer (Tagged< HeapObject > host, ObjectSlot slot) override
void VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitExternalReference (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitInternalReference (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitOffHeapTarget (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot) override
void VisitCppHeapPointer (Tagged< HeapObject > host, CppHeapPointerSlot slot) override
void VisitEphemeron (Tagged< HeapObject > host, int index, ObjectSlot key, ObjectSlot value) override
void VisitIndirectPointer (Tagged< HeapObject > host, IndirectPointerSlot slot, IndirectPointerMode mode) override
void VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedPointerSlot slot) override
void VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedMaybeObjectSlot slot) override
void VisitTrustedPointerTableEntry (Tagged< HeapObject > host, IndirectPointerSlot slot) override
void VisitJSDispatchTableEntry (Tagged< HeapObject > host, JSDispatchHandle handle) override
void VisitMapPointer (Tagged< HeapObject > host) override
Static Public Member Functions
static constexpr bool ShouldVisitMapPointer ()
static constexpr bool ShouldUseUncheckedCast ()
static constexpr bool ShouldVisitFullJSObject ()
Private Attributes
ObjectVisitor *const visitor_
Additional Inherited Members
Detailed Description
Definition at line 16 of file visit-object.cc.
Constructor & Destructor Documentation
ObjectVisitorForwarder() [1/2]
v8::internal::ObjectVisitorForwarder::ObjectVisitorForwarder (Isolate * isolate, ObjectVisitor * visitor) [inline], [explicit]
Definition at line 19 of file visit-object.cc.
      : HeapVisitor(isolate), visitor_(visitor) {}
ObjectVisitorForwarder() [2/2]
v8::internal::ObjectVisitorForwarder::ObjectVisitorForwarder (LocalIsolate * isolate, ObjectVisitor * visitor) [inline], [explicit]
Definition at line 21 of file visit-object.cc.
      : HeapVisitor(isolate), visitor_(visitor) {}
Member Function Documentation
ShouldUseUncheckedCast()
static constexpr bool v8::internal::ObjectVisitorForwarder::ShouldUseUncheckedCast () [inline], [static], [constexpr]
Definition at line 25 of file visit-object.cc.
{ return true; }
ShouldVisitFullJSObject()
static constexpr bool v8::internal::ObjectVisitorForwarder::ShouldVisitFullJSObject () [inline], [static], [constexpr]
Definition at line 26 of file visit-object.cc.
{ return true; }
ShouldVisitMapPointer()
static constexpr bool v8::internal::ObjectVisitorForwarder::ShouldVisitMapPointer () [inline], [static], [constexpr]
Definition at line 24 of file visit-object.cc.
{ return false; }
VisitCodeTarget()
void v8::internal::ObjectVisitorForwarder::VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 61 of file visit-object.cc.
                                                  {
    visitor_->VisitCodeTarget(host, rinfo);
  }
References v8::internal::ObjectVisitor::VisitCodeTarget(), and visitor_.
VisitCppHeapPointer()
void v8::internal::ObjectVisitorForwarder::VisitCppHeapPointer (Tagged< HeapObject > host, CppHeapPointerSlot slot) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 91 of file visit-object.cc.
                                                             {
    visitor_->VisitCppHeapPointer(host, slot);
  }
References v8::internal::ObjectVisitor::VisitCppHeapPointer(), and visitor_.
VisitCustomWeakPointer()
void v8::internal::ObjectVisitorForwarder::VisitCustomWeakPointer (Tagged< HeapObject > host, ObjectSlot slot) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 56 of file visit-object.cc.
                                                        {
    visitor_->VisitCustomWeakPointer(host, slot);
  }
References v8::internal::ObjectVisitor::VisitCustomWeakPointer(), and visitor_.
VisitCustomWeakPointers()
void v8::internal::ObjectVisitorForwarder::VisitCustomWeakPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 43 of file visit-object.cc.
                                                        {
    visitor_->VisitCustomWeakPointers(host, start, end);
  }
References v8::internal::compiler::end(), v8::internal::ObjectVisitor::VisitCustomWeakPointers(), and visitor_.
VisitEmbeddedPointer()
void v8::internal::ObjectVisitorForwarder::VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 66 of file visit-object.cc.
                                                       {
    visitor_->VisitEmbeddedPointer(host, rinfo);
  }
References v8::internal::ObjectVisitor::VisitEmbeddedPointer(), and visitor_.
VisitEphemeron()
void v8::internal::ObjectVisitorForwarder::VisitEphemeron (Tagged< HeapObject > host, int index, ObjectSlot key, ObjectSlot value) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 96 of file visit-object.cc.
                                                 {
    visitor_->VisitEphemeron(host, index, key, value);
  }
References v8::internal::index, v8::internal::key, v8::internal::value, v8::internal::ObjectVisitor::VisitEphemeron(), and visitor_.
VisitExternalPointer()
void v8::internal::ObjectVisitorForwarder::VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 86 of file visit-object.cc.
                                                               {
    visitor_->VisitExternalPointer(host, slot);
  }
References v8::internal::ObjectVisitor::VisitExternalPointer(), and visitor_.
VisitExternalReference()
void v8::internal::ObjectVisitorForwarder::VisitExternalReference (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 71 of file visit-object.cc.
                                                         {
    visitor_->VisitExternalReference(host, rinfo);
  }
References v8::internal::ObjectVisitor::VisitExternalReference(), and visitor_.
VisitIndirectPointer()
void v8::internal::ObjectVisitorForwarder::VisitIndirectPointer (Tagged< HeapObject > host, IndirectPointerSlot slot, IndirectPointerMode mode) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 101 of file visit-object.cc.
                                                               {
    visitor_->VisitIndirectPointer(host, slot, mode);
  }
References mode(), v8::internal::ObjectVisitor::VisitIndirectPointer(), and visitor_.
VisitInstructionStreamPointer()
void v8::internal::ObjectVisitorForwarder::VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 38 of file visit-object.cc.
                                                                          {
    visitor_->VisitInstructionStreamPointer(host, slot);
  }
References v8::internal::ObjectVisitor::VisitInstructionStreamPointer(), and visitor_.
VisitInternalReference()
void v8::internal::ObjectVisitorForwarder::VisitInternalReference (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 76 of file visit-object.cc.
                                                         {
    visitor_->VisitInternalReference(host, rinfo);
  }
References v8::internal::ObjectVisitor::VisitInternalReference(), and visitor_.
VisitJSDispatchTableEntry()
void v8::internal::ObjectVisitorForwarder::VisitJSDispatchTableEntry (Tagged< HeapObject > host, JSDispatchHandle handle) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 121 of file visit-object.cc.
                                                                   {
    visitor_->VisitJSDispatchTableEntry(host, handle);
  }
References v8::internal::handle(), v8::internal::ObjectVisitor::VisitJSDispatchTableEntry(), and visitor_.
VisitMapPointer()
void v8::internal::ObjectVisitorForwarder::VisitMapPointer (Tagged< HeapObject > host) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 126 of file visit-object.cc.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
VisitOffHeapTarget()
void v8::internal::ObjectVisitorForwarder::VisitOffHeapTarget (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 81 of file visit-object.cc.
                                                     {
    visitor_->VisitOffHeapTarget(host, rinfo);
  }
References v8::internal::ObjectVisitor::VisitOffHeapTarget(), and visitor_.
VisitPointer() [1/2]
void v8::internal::ObjectVisitorForwarder::VisitPointer (Tagged< HeapObject > host, MaybeObjectSlot slot) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 52 of file visit-object.cc.
                                                                            {
    visitor_->VisitPointers(host, slot, slot + 1);
  }
References visitor_, and v8::internal::ObjectVisitor::VisitPointers().
VisitPointer() [2/2]
void v8::internal::ObjectVisitorForwarder::VisitPointer (Tagged< HeapObject > host, ObjectSlot slot) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 48 of file visit-object.cc.
                                                                       {
    visitor_->VisitPointers(host, slot, slot + 1);
  }
References visitor_, and v8::internal::ObjectVisitor::VisitPointers().
VisitPointers() [1/2]
void v8::internal::ObjectVisitorForwarder::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 33 of file visit-object.cc.
                                                   {
    visitor_->VisitPointers(host, start, end);
  }
References v8::internal::compiler::end(), visitor_, and v8::internal::ObjectVisitor::VisitPointers().
VisitPointers() [2/2]
void v8::internal::ObjectVisitorForwarder::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 28 of file visit-object.cc.
                                              {
    visitor_->VisitPointers(host, start, end);
  }
References v8::internal::compiler::end(), visitor_, and v8::internal::ObjectVisitor::VisitPointers().
VisitProtectedPointer() [1/2]
void v8::internal::ObjectVisitorForwarder::VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedMaybeObjectSlot slot) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 111 of file visit-object.cc.
                                                                     {
    visitor_->VisitProtectedPointer(host, slot);
  }
References visitor_, and v8::internal::ObjectVisitor::VisitProtectedPointer().
VisitProtectedPointer() [2/2]
void v8::internal::ObjectVisitorForwarder::VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedPointerSlot slot) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 106 of file visit-object.cc.
                                                                 {
    visitor_->VisitProtectedPointer(host, slot);
  }
References visitor_, and v8::internal::ObjectVisitor::VisitProtectedPointer().
VisitTrustedPointerTableEntry()
void v8::internal::ObjectVisitorForwarder::VisitTrustedPointerTableEntry (Tagged< HeapObject > host, IndirectPointerSlot slot) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 116 of file visit-object.cc.
                                                                        {
    visitor_->VisitTrustedPointerTableEntry(host, slot);
  }
References visitor_, and v8::internal::ObjectVisitor::VisitTrustedPointerTableEntry().
Member Data Documentation
visitor_
ObjectVisitor* const v8::internal::ObjectVisitorForwarder::visitor_ [private]
Definition at line 129 of file visit-object.cc.
Referenced by VisitCodeTarget(), VisitCppHeapPointer(), VisitCustomWeakPointer(), VisitCustomWeakPointers(), VisitEmbeddedPointer(), VisitEphemeron(), VisitExternalPointer(), VisitExternalReference(), VisitIndirectPointer(), VisitInstructionStreamPointer(), VisitInternalReference(), VisitJSDispatchTableEntry(), VisitOffHeapTarget(), VisitPointer(), VisitPointers(), VisitProtectedPointer(), and VisitTrustedPointerTableEntry().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/visit-object.cc