v8::internal::WasmExceptionTag Class Reference
#include <wasm-objects.h>
Public Types
using BodyDescriptor = StructBodyDescriptor
Static Public Member Functions
static V8_EXPORT_PRIVATE DirectHandle< WasmExceptionTag > New (Isolate *isolate, int index)
Detailed Description
Definition at line 1352 of file wasm-objects.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::WasmExceptionTag::BodyDescriptor = StructBodyDescriptor
Definition at line 1358 of file wasm-objects.h.
Member Function Documentation
New()
DirectHandle< WasmExceptionTag > v8::internal::WasmExceptionTag::New (Isolate * isolate, int index) [static]
Definition at line 3305 of file wasm-objects.cc.
                                                                {
  auto result = Cast<WasmExceptionTag>(isolate->factory()->NewStruct(
      WASM_EXCEPTION_TAG_TYPE, AllocationType::kOld));
  result->set_index(index);
  return result;
}
References v8::internal::Isolate::factory(), v8::internal::index, v8::internal::kOld, v8::internal::FactoryBase< Impl >::NewStruct(), and v8::base::internal::result.
Referenced by v8::internal::wasm::InstanceBuilder::InitializeTags(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc