v8::internal::maglev::Switch Class Reference
#include <maglev-ir.h>
Public Member Functions
Switch (uint64_t bitfield, int value_base, BasicBlockRef *targets, int size)
Switch (uint64_t bitfield, int value_base, BasicBlockRef *targets, int size, BasicBlockRef *fallthrough)
int value_base () const
BasicBlockRef * targets () const
int size () const
bool has_fallthrough () const
BasicBlock * fallthrough () const
void set_fallthrough (BasicBlock *fallthrough)
Input & value ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kInt32}
Private Types
using Base = FixedInputNodeTMixin< 1, ConditionalControlNode, Switch >
Private Attributes
const int value_base_
BasicBlockRef * targets_
const int size_
std::optional< BasicBlockRef > fallthrough_
Additional Inherited Members
Detailed Description
Definition at line 11414 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::Switch::Base = FixedInputNodeTMixin<1, ConditionalControlNode, Switch> [private]
Definition at line 11415 of file maglev-ir.h.
Constructor & Destructor Documentation
Switch() [1/2]
v8::internal::maglev::Switch::Switch (uint64_t bitfield, int value_base, BasicBlockRef * targets, int size) [inline], [explicit]
Definition at line 11418 of file maglev-ir.h.
      : Base(bitfield),
        value_base_(value_base),
        targets_(targets),
        size_(size),
        fallthrough_() {}
Switch() [2/2]
v8::internal::maglev::Switch::Switch (uint64_t bitfield, int value_base, BasicBlockRef * targets, int size, BasicBlockRef * fallthrough) [inline], [explicit]
Definition at line 11426 of file maglev-ir.h.
      : Base(bitfield),
        value_base_(value_base),
        targets_(targets),
        size_(size),
        fallthrough_(fallthrough) {}
Member Function Documentation
fallthrough()
BasicBlock* v8::internal::maglev::Switch::fallthrough () const [inline]
Definition at line 11442 of file maglev-ir.h.
                                  {
    DCHECK(has_fallthrough());
    return fallthrough_.value().block_ptr();
  }
References DCHECK.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PatchJumps().
GenerateCode()
void v8::internal::maglev::Switch::GenerateCode (MaglevAssembler * , const ProcessingState &)
has_fallthrough()
bool v8::internal::maglev::Switch::has_fallthrough () const [inline]
Definition at line 11441 of file maglev-ir.h.
{ return fallthrough_.has_value(); }
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PatchJumps(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintTargets(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::Switch::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 11456 of file maglev-ir.h.
{}
set_fallthrough()
void v8::internal::maglev::Switch::set_fallthrough (BasicBlock * fallthrough) [inline]
Definition at line 11447 of file maglev-ir.h.
                                                {
    DCHECK(has_fallthrough());
    fallthrough_.value().set_block_ptr(fallthrough);
  }
References DCHECK.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PatchJumps().
SetValueLocationConstraints()
void v8::internal::maglev::Switch::SetValueLocationConstraints ()
size()
int v8::internal::maglev::Switch::size () const [inline]
Definition at line 11439 of file maglev-ir.h.
{ return size_; }
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PatchJumps(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintTargets(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
targets()
BasicBlockRef* v8::internal::maglev::Switch::targets () const [inline]
Definition at line 11438 of file maglev-ir.h.
{ return targets_; }
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PatchJumps(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
value()
Input& v8::internal::maglev::Switch::value () [inline]
Definition at line 11452 of file maglev-ir.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
value_base()
int v8::internal::maglev::Switch::value_base () const [inline]
Definition at line 11437 of file maglev-ir.h.
{ return value_base_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
fallthrough_
std::optional<BasicBlockRef> v8::internal::maglev::Switch::fallthrough_ [private]
Definition at line 11462 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::Switch::kInputTypes {ValueRepresentation::kInt32} [static], [constexpr]
Definition at line 11435 of file maglev-ir.h.
size_
const int v8::internal::maglev::Switch::size_ [private]
Definition at line 11461 of file maglev-ir.h.
targets_
BasicBlockRef* v8::internal::maglev::Switch::targets_ [private]
Definition at line 11460 of file maglev-ir.h.
value_base_
const int v8::internal::maglev::Switch::value_base_ [private]
Definition at line 11459 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h