v8::internal::GlobalHandles Class Reference
#include <global-handles.h>
Classes
class Node
class NodeBlock
class NodeIterator
class NodeSpace
class PendingPhantomCallback
Public Member Functions
GlobalHandles (const GlobalHandles &)=delete
GlobalHandles & operator= (const GlobalHandles &)=delete
GlobalHandles (Isolate *isolate)
~GlobalHandles ()
IndirectHandle< Object > Create (Tagged< Object > value)
IndirectHandle< Object > Create (Address value)
template<typename T >
IndirectHandle< T > Create (Tagged< T > value)
void RecordStats (HeapStats *stats)
size_t InvokeFirstPassWeakCallbacks ()
void InvokeSecondPassPhantomCallbacks ()
void PostGarbageCollectionProcessing (v8::GCCallbackFlags gc_callback_flags)
void IterateStrongRoots (RootVisitor *v)
void IterateWeakRoots (RootVisitor *v)
void IterateAllRoots (RootVisitor *v)
void IterateAllYoungRoots (RootVisitor *v)
void IterateWeakRootsForPhantomHandles (WeakSlotCallbackWithHeap should_reset_handle)
void IterateYoungStrongAndDependentRoots (RootVisitor *v)
void ProcessWeakYoungObjects (RootVisitor *v, WeakSlotCallbackWithHeap should_reset_handle)
void UpdateListOfYoungNodes ()
void ClearListOfYoungNodes ()
Isolate * isolate () const
size_t TotalSize () const
size_t UsedSize () const
size_t handles_count () const
size_t last_gc_custom_callbacks () const
void IterateAllRootsForTesting (v8::PersistentHandleVisitor *v)
bool HasYoung () const
Static Public Member Functions
static void MoveGlobal (Address **from, Address **to)
static IndirectHandle< Object > CopyGlobal (Address *location)
static void Destroy (Address *location)
static void MakeWeak (Address *location, void *parameter, WeakCallbackInfo< void >::Callback weak_callback, v8::WeakCallbackType type)
static void MakeWeak (Address **location_addr)
static void AnnotateStrongRetainer (Address *location, const char *label)
static void * ClearWeakness (Address *location)
static bool IsWeak (Address *location)
Private Member Functions
void ApplyPersistentHandleVisitor (v8::PersistentHandleVisitor *visitor, Node *node)
bool ResetWeakNodeIfDead (Node *node, WeakSlotCallbackWithHeap should_reset_node)
Private Attributes
Isolate *const isolate_
std::unique_ptr< NodeSpace< Node > > regular_nodes_
std::vector< Node * > young_nodes_
std::vector< std::pair< Node *, PendingPhantomCallback > > pending_phantom_callbacks_
std::vector< PendingPhantomCallback > second_pass_callbacks_
bool second_pass_callbacks_task_posted_ = false
size_t last_gc_custom_callbacks_ = 0
Detailed Description
Definition at line 30 of file global-handles.h.
Constructor & Destructor Documentation
GlobalHandles() [1/2]
v8::internal::GlobalHandles::GlobalHandles (const GlobalHandles &) [delete]
GlobalHandles() [2/2]
v8::internal::GlobalHandles::GlobalHandles (Isolate * isolate) [explicit]
Definition at line 609 of file global-handles.cc.
    : isolate_(isolate),
      regular_nodes_(std::make_unique<NodeSpace<GlobalHandles::Node>>(this)) {}
 GlobalHandles()
v8::internal::GlobalHandles::~GlobalHandles () [default]
Member Function Documentation
AnnotateStrongRetainer()
void v8::internal::GlobalHandles::AnnotateStrongRetainer (Address * location, const char * label) [static]
Definition at line 683 of file global-handles.cc.
                                                              {
  Node::FromLocation(location)->AnnotateStrongRetainer(label);
}
References v8::internal::GlobalHandles::Node::AnnotateStrongRetainer(), and v8::internal::NodeBase< GlobalHandles::Node >::FromLocation().
Referenced by v8::api_internal::AnnotateStrongRetainer().
ApplyPersistentHandleVisitor()
DISABLE_CFI_PERF void v8::internal::GlobalHandles::ApplyPersistentHandleVisitor (v8::PersistentHandleVisitor * visitor, GlobalHandles::Node * node) [private]
Definition at line 941 of file global-handles.cc.
                                                                 {
  Address* value = node->handle().location();
  visitor->VisitPersistentHandle(
      reinterpret_cast<v8::Persistent<v8::Value>*>(&value),
      node->wrapper_class_id());
}
References v8::internal::NodeBase< Child >::handle(), v8::internal::value, v8::PersistentHandleVisitor::VisitPersistentHandle(), and v8::internal::NodeBase< Child >::wrapper_class_id().
Referenced by IterateAllRootsForTesting().
ClearListOfYoungNodes()
void v8::internal::GlobalHandles::ClearListOfYoungNodes ()
Definition at line 821 of file global-handles.cc.
                                          {
  ClearListOfYoungNodesImpl(isolate_, &young_nodes_);
}
References v8::internal::anonymous_namespace{global-handles.cc}::ClearListOfYoungNodesImpl(), isolate_, and young_nodes_.
Referenced by v8::internal::MarkCompactCollector::Finish().
ClearWeakness()
void * v8::internal::GlobalHandles::ClearWeakness (Address * location) [static]
Definition at line 679 of file global-handles.cc.
                                                    {
  return Node::FromLocation(location)->ClearWeakness();
}
References v8::internal::GlobalHandles::Node::ClearWeakness(), and v8::internal::NodeBase< GlobalHandles::Node >::FromLocation().
Referenced by v8::api_internal::ClearWeak().
CopyGlobal()
IndirectHandle< Object > v8::internal::GlobalHandles::CopyGlobal (Address * location) [static]
Definition at line 637 of file global-handles.cc.
                                                                  {
  DCHECK_NOT_NULL(location);
  GlobalHandles* global_handles =
      Node::FromLocation(location)->global_handles();
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap) {
    Object::ObjectVerify(Tagged<Object>(*location), global_handles->isolate());
  }
#endif // VERIFY_HEAP
  return global_handles->Create(*location);
}
References Create(), DCHECK_NOT_NULL, v8::internal::NodeBase< GlobalHandles::Node >::FromLocation(), v8::internal::GlobalHandles::Node::global_handles(), isolate(), and v8::internal::v8_flags.
Referenced by v8::api_internal::CopyGlobalReference().
Create() [1/3]
IndirectHandle< Object > v8::internal::GlobalHandles::Create (Address value)
Definition at line 633 of file global-handles.cc.
                                                          {
  return Create(Tagged<Object>(value));
}
References Create(), and v8::internal::value.
Create() [2/3]
IndirectHandle< Object > v8::internal::GlobalHandles::Create (Tagged< Object > value)
Definition at line 624 of file global-handles.cc.
                                                                 {
  GlobalHandles::Node* node = regular_nodes_->Allocate();
  if (NeedsTrackingInYoungNodes(value, node)) {
    young_nodes_.push_back(node);
    node->set_in_young_list(true);
  }
  return node->Publish(value);
}
References v8::internal::anonymous_namespace{global-handles.cc}::NeedsTrackingInYoungNodes(), v8::internal::NodeBase< Child >::Publish(), regular_nodes_, v8::internal::GlobalHandles::Node::set_in_young_list(), v8::internal::value, and young_nodes_.
Referenced by v8::internal::SnapshotCreatorImpl::AddContext(), v8::internal::ValueDeserializer::AddObjectWithID(), v8::internal::wasm::AsyncCompileJob::AsyncCompileJob(), CopyGlobal(), Create(), v8::internal::wasm::AsyncStreamingProcessor::Deserialize(), v8::internal::MemoryMeasurement::EnqueueRequest(), v8::internal::baseline::BaselineBatchCompiler::EnsureQueueCapacity(), v8::internal::wasm::WasmInterpreterThread::EnsureRefStackSpace(), v8::internal::Managed< CppType >::From(), v8::internal::TrustedManaged< CppType >::From(), v8::api_internal::GlobalizeReference(), v8::internal::DebugInfoCollection::Insert(), wasm::RefImpl< Ref, JSType >::make(), v8::internal::wasm::anonymous_namespace{wasm-interpreter.cc}::MakeWeak(), v8::internal::wasm::AsyncCompileJob::PrepareRuntimeObjects(), v8::internal::CrossHeapRememberedSet::RememberReferenceIfNeeded(), v8::internal::wasm::FrameState::SetCaughtException(), v8::internal::SnapshotCreatorImpl::SetDefaultContext(), v8::internal::WeakCodeRegistry::Track(), v8::internal::ValueDeserializer::TransferArrayBuffer(), and v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::WeakScriptHandle().
Create() [3/3]
template<typename T >
IndirectHandle< T > v8::internal::GlobalHandles::Create (Tagged< T > value) [inline]
Definition at line 19 of file global-handles-inl.h.
                                                       {
  static_assert(is_subtype_v<T, Object>, "static type violation");
  // The compiler should only pick this method if T is not Object.
  static_assert(!std::is_same_v<Object, T>, "compiler error");
  return Cast<T>(Create(Tagged<Object>(value)));
}
References Create(), and v8::internal::value.
Destroy()
void v8::internal::GlobalHandles::Destroy (Address * location) [static]
Definition at line 661 of file global-handles.cc.
                                             {
  if (location != nullptr) {
    NodeSpace<Node>::Release(Node::FromLocation(location));
  }
}
References v8::internal::NodeBase< GlobalHandles::Node >::FromLocation(), and v8::internal::GlobalHandles::NodeSpace< NodeType >::Release().
Referenced by v8::internal::ValueDeserializer::AddObjectWithID(), v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::clear_storage(), v8::internal::SnapshotCreatorImpl::CreateBlob(), v8::internal::DebugInfoCollection::DeleteIndex(), v8::internal::wasm::WasmOrphanedGlobalHandle::Destroy(), v8::internal::wasm::FrameState::DisposeCaughtExceptionsArray(), v8::api_internal::DisposeGlobal(), v8::internal::baseline::BaselineBatchCompiler::EnsureQueueCapacity(), v8::internal::wasm::WasmInterpreterThread::EnsureRefStackSpace(), v8::internal::ManagedObjectFinalizer(), v8::internal::wasm::anonymous_namespace{wasm-interpreter.cc}::NopFinalizer(), v8::internal::CrossHeapRememberedSet::Reset(), v8::internal::ValueDeserializer::TransferArrayBuffer(), v8::internal::anonymous_namespace{weak-code-registry.cc}::Untrack(), v8::internal::wasm::AsyncCompileJob::~AsyncCompileJob(), v8::internal::baseline::BaselineBatchCompiler::~BaselineBatchCompiler(), wasm::RefImpl< Ref, JSType >::~RefImpl(), v8::internal::SnapshotCreatorImpl::~SnapshotCreatorImpl(), v8::internal::ValueDeserializer::~ValueDeserializer(), and v8::internal::wasm::WasmInterpreterThread::~WasmInterpreterThread().
handles_count()
size_t v8::internal::GlobalHandles::handles_count () const
Definition at line 605 of file global-handles.cc.
                                          {
  return regular_nodes_->handles_count();
}
References regular_nodes_.
Referenced by v8::internal::Heap::CollectAllAvailableGarbage().
HasYoung()
bool v8::internal::GlobalHandles::HasYoung () const [inline]
Definition at line 133 of file global-handles.h.
{ return !young_nodes_.empty(); }
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences().
InvokeFirstPassWeakCallbacks()
size_t v8::internal::GlobalHandles::InvokeFirstPassWeakCallbacks ()
Definition at line 825 of file global-handles.cc.
                                                   {
  last_gc_custom_callbacks_ = 0;
  if (pending_phantom_callbacks_.empty()) return 0;
  TRACE_GC(isolate()->heap()->tracer(),
           GCTracer::Scope::HEAP_EXTERNAL_WEAK_GLOBAL_HANDLES);
  size_t freed_nodes = 0;
  std::vector<std::pair<Node*, PendingPhantomCallback>>
      pending_phantom_callbacks;
  pending_phantom_callbacks.swap(pending_phantom_callbacks_);
  // The initial pass callbacks must simply clear the nodes.
  for (auto& pair : pending_phantom_callbacks) {
    Node* node = pair.first;
    DCHECK_EQ(Node::NEAR_DEATH, node->state());
    pair.second.Invoke(isolate(), PendingPhantomCallback::kFirstPass);
    // Transition to second pass. It is required that the first pass callback
    // resets the handle using |v8::PersistentBase::Reset|. Also see comments
    // on |v8::WeakCallbackInfo|.
    CHECK_WITH_MSG(Node::FREE == node->state(),
                   "Handle not reset in first callback. See comments on "
                   "|v8::WeakCallbackInfo|.");
    if (pair.second.callback()) second_pass_callbacks_.push_back(pair.second);
    freed_nodes++;
  }
  last_gc_custom_callbacks_ = freed_nodes;
  return 0;
}
References CHECK_WITH_MSG, DCHECK_EQ, v8::internal::GlobalHandles::Node::FREE, heap(), isolate(), v8::internal::GlobalHandles::PendingPhantomCallback::kFirstPass, last_gc_custom_callbacks_, v8::internal::GlobalHandles::Node::NEAR_DEATH, pending_phantom_callbacks_, second_pass_callbacks_, v8::internal::GlobalHandles::Node::state(), and TRACE_GC.
Referenced by v8::internal::Heap::PerformGarbageCollection().
InvokeSecondPassPhantomCallbacks()
void v8::internal::GlobalHandles::InvokeSecondPassPhantomCallbacks ()
Definition at line 745 of file global-handles.cc.
                                                     {
  DCHECK(!AllowJavascriptExecution::IsAllowed(isolate()));
  DCHECK(AllowGarbageCollection::IsAllowed());
  if (second_pass_callbacks_.empty()) return;
  // The callbacks may allocate, which in turn may lead to another GC run. If we
  // are already processing the callbacks, we do not want to start over from
  // within the inner GC. Newly added callbacks will always be run by the
  // outermost GC run only.
  GCCallbacksScope scope(isolate()->heap());
  if (scope.CheckReenter()) {
    TRACE_EVENT0("v8", "V8.GCPhantomHandleProcessingCallback");
    isolate()->heap()->CallGCPrologueCallbacks(
        GCType::kGCTypeProcessWeakCallbacks, kNoGCCallbackFlags,
        GCTracer::Scope::HEAP_EXTERNAL_PROLOGUE);
    {
      TRACE_GC(isolate_->heap()->tracer(),
               GCTracer::Scope::HEAP_EXTERNAL_SECOND_PASS_CALLBACKS);
      while (!second_pass_callbacks_.empty()) {
        auto callback = second_pass_callbacks_.back();
        second_pass_callbacks_.pop_back();
        callback.Invoke(isolate(), PendingPhantomCallback::kSecondPass);
      }
    }
    isolate()->heap()->CallGCEpilogueCallbacks(
        GCType::kGCTypeProcessWeakCallbacks, kNoGCCallbackFlags,
        GCTracer::Scope::HEAP_EXTERNAL_EPILOGUE);
  }
}
References v8::internal::Heap::CallGCEpilogueCallbacks(), v8::internal::Heap::CallGCPrologueCallbacks(), v8::internal::GCCallbacksScope::CheckReenter(), v8::internal::DCHECK(), v8::internal::Isolate::heap(), heap(), isolate(), isolate_, v8::kGCTypeProcessWeakCallbacks, v8::kNoGCCallbackFlags, v8::internal::GlobalHandles::PendingPhantomCallback::kSecondPass, second_pass_callbacks_, TRACE_EVENT0, TRACE_GC, and v8::internal::Heap::tracer().
Referenced by v8::internal::Heap::CollectGarbage(), and PostGarbageCollectionProcessing().
isolate()
Isolate* v8::internal::GlobalHandles::isolate () const [inline]
Definition at line 118 of file global-handles.h.
{ return isolate_; }
Referenced by CopyGlobal(), v8::internal::EternalHandles::Create(), v8::internal::GlobalHandles::PendingPhantomCallback::Invoke(), InvokeFirstPassWeakCallbacks(), InvokeSecondPassPhantomCallbacks(), PostGarbageCollectionProcessing(), and ResetWeakNodeIfDead().
IsWeak()
bool v8::internal::GlobalHandles::IsWeak (Address * location) [static]
Definition at line 688 of file global-handles.cc.
                                            {
  return Node::FromLocation(location)->IsWeak();
}
References v8::internal::NodeBase< GlobalHandles::Node >::FromLocation(), and v8::internal::GlobalHandles::Node::IsWeak().
IterateAllRoots()
DISABLE_CFI_PERF void v8::internal::GlobalHandles::IterateAllRoots (RootVisitor * v)
Definition at line 921 of file global-handles.cc.
                                                  {
  for (Node* node : *regular_nodes_) {
    if (node->IsWeakOrStrongRetainer()) {
      v->VisitRootPointer(Root::kGlobalHandles, node->label(),
                          node->location());
    }
  }
}
References regular_nodes_, and v8::internal::RootVisitor::VisitRootPointer().
Referenced by v8::internal::SerializedHandleChecker::CheckGlobalAndEternalHandles(), v8::internal::V8HeapExplorer::CollectTemporaryGlobalObjectsTags(), and v8::internal::Heap::IterateRoots().
IterateAllRootsForTesting()
void v8::internal::GlobalHandles::IterateAllRootsForTesting (v8::PersistentHandleVisitor * v)
Definition at line 949 of file global-handles.cc.
                                        {
  for (Node* node : *regular_nodes_) {
    if (node->IsWeakOrStrongRetainer()) {
      ApplyPersistentHandleVisitor(visitor, node);
    }
  }
}
References ApplyPersistentHandleVisitor(), and regular_nodes_.
IterateAllYoungRoots()
DISABLE_CFI_PERF void v8::internal::GlobalHandles::IterateAllYoungRoots (RootVisitor * v)
Definition at line 931 of file global-handles.cc.
                                                       {
  for (Node* node : young_nodes_) {
    if (node->IsWeakOrStrongRetainer()) {
      v->VisitRootPointer(Root::kGlobalHandles, node->label(),
                          node->location());
    }
  }
}
References v8::internal::RootVisitor::VisitRootPointer(), and young_nodes_.
IterateStrongRoots()
void v8::internal::GlobalHandles::IterateStrongRoots (RootVisitor * v)
Definition at line 902 of file global-handles.cc.
                                                     {
  for (Node* node : *regular_nodes_) {
    if (node->IsStrongRetainer()) {
      v->VisitRootPointer(Root::kGlobalHandles, node->label(),
                          node->location());
    }
  }
}
References regular_nodes_, and v8::internal::RootVisitor::VisitRootPointer().
Referenced by v8::internal::Heap::IterateRoots().
IterateWeakRoots()
void v8::internal::GlobalHandles::IterateWeakRoots (RootVisitor * v)
Definition at line 911 of file global-handles.cc.
                                                   {
  for (Node* node : *regular_nodes_) {
    if (node->IsWeak()) {
      v->VisitRootPointer(Root::kGlobalHandles, node->label(),
                          node->location());
    }
  }
}
References regular_nodes_, and v8::internal::RootVisitor::VisitRootPointer().
Referenced by v8::internal::Heap::IterateWeakGlobalHandles().
IterateWeakRootsForPhantomHandles()
DISABLE_CFI_PERF void v8::internal::GlobalHandles::IterateWeakRootsForPhantomHandles (WeakSlotCallbackWithHeap should_reset_handle)
Definition at line 712 of file global-handles.cc.
                                                  {
  for (Node* node : *regular_nodes_) {
    if (node->IsWeakRetainer()) ResetWeakNodeIfDead(node, should_reset_handle);
  }
}
References regular_nodes_, and ResetWeakNodeIfDead().
Referenced by v8::internal::MarkCompactCollector::ClearNonLiveReferences().
IterateYoungStrongAndDependentRoots()
void v8::internal::GlobalHandles::IterateYoungStrongAndDependentRoots (RootVisitor * v)
Definition at line 719 of file global-handles.cc.
                                                                      {
  for (Node* node : young_nodes_) {
    if (node->IsStrongRetainer()) {
      v->VisitRootPointer(Root::kGlobalHandles, node->label(),
                          node->location());
    }
  }
}
References v8::internal::RootVisitor::VisitRootPointer(), and young_nodes_.
Referenced by v8::internal::ScavengerCollector::CollectGarbage(), v8::internal::IncrementalMarking::MarkRoots(), and v8::internal::MinorMarkSweepCollector::MarkRoots().
last_gc_custom_callbacks()
size_t v8::internal::GlobalHandles::last_gc_custom_callbacks () const [inline]
Definition at line 124 of file global-handles.h.
{ return last_gc_custom_callbacks_; }
MakeWeak() [1/2]
void v8::internal::GlobalHandles::MakeWeak (Address ** location_addr) [static]
Definition at line 675 of file global-handles.cc.
                                                    {
  Node::FromLocation(*location_addr)->MakeWeak(location_addr);
}
References v8::internal::NodeBase< GlobalHandles::Node >::FromLocation(), and v8::internal::GlobalHandles::Node::MakeWeak().
MakeWeak() [2/2]
static void v8::internal::GlobalHandles::MakeWeak (Address * location, void * parameter, WeakCallbackInfo< void >::Callback weak_callback, v8::WeakCallbackType type) [static]
Referenced by v8::internal::Managed< CppType >::From(), v8::internal::TrustedManaged< CppType >::From(), v8::api_internal::MakeWeak(), v8::internal::wasm::anonymous_namespace{wasm-interpreter.cc}::MakeWeak(), v8::internal::WeakCodeRegistry::Track(), and v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::WeakScriptHandle().
MoveGlobal()
void v8::internal::GlobalHandles::MoveGlobal (Address ** from, Address ** to) [static]
Definition at line 650 of file global-handles.cc.
                                                           {
  DCHECK_NOT_NULL(*from);
  DCHECK_NOT_NULL(*to);
  DCHECK_EQ(*from, *to);
  Node* node = Node::FromLocation(*from);
  if (node->IsWeak() && node->IsPhantomResetHandle()) {
    node->set_parameter(to);
  }
  // Strong handles do not require fixups.
}
References DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::NodeBase< GlobalHandles::Node >::FromLocation(), v8::internal::GlobalHandles::Node::IsPhantomResetHandle(), v8::internal::GlobalHandles::Node::IsWeak(), and v8::internal::NodeBase< Child >::set_parameter().
Referenced by v8::api_internal::MoveGlobalReference().
operator=()
GlobalHandles& v8::internal::GlobalHandles::operator= (const GlobalHandles &) [delete]
PostGarbageCollectionProcessing()
void v8::internal::GlobalHandles::PostGarbageCollectionProcessing (v8::GCCallbackFlags gc_callback_flags)
Definition at line 869 of file global-handles.cc.
                                         {
  // Process weak global handle callbacks. This must be done after the
  // GC is completely done, because the callbacks may invoke arbitrary
  // API functions.
  DCHECK_EQ(Heap::NOT_IN_GC, isolate_->heap()->gc_state());
  if (second_pass_callbacks_.empty()) return;
  const bool synchronous_second_pass =
      isolate_->MemorySaverModeEnabled() || v8_flags.predictable ||
      isolate_->heap()->IsTearingDown() ||
      (gc_callback_flags &
       (kGCCallbackFlagForced | kGCCallbackFlagCollectAllAvailableGarbage |
        kGCCallbackFlagSynchronousPhantomCallbackProcessing)) != 0;
  if (synchronous_second_pass) {
    InvokeSecondPassPhantomCallbacks();
    return;
  }
  if (!second_pass_callbacks_task_posted_) {
    second_pass_callbacks_task_posted_ = true;
    V8::GetCurrentPlatform()
        ->GetForegroundTaskRunner(reinterpret_cast<v8::Isolate*>(isolate()))
        ->PostTask(MakeCancelableTask(isolate(), [this] {
          DCHECK(second_pass_callbacks_task_posted_);
          second_pass_callbacks_task_posted_ = false;
          DisallowJavascriptExecution no_js(isolate());
          InvokeSecondPassPhantomCallbacks();
        }));
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Heap::gc_state(), v8::internal::V8::GetCurrentPlatform(), v8::Platform::GetForegroundTaskRunner(), v8::internal::Isolate::heap(), InvokeSecondPassPhantomCallbacks(), isolate(), isolate_, v8::internal::Heap::IsTearingDown(), v8::kGCCallbackFlagCollectAllAvailableGarbage, v8::kGCCallbackFlagForced, v8::kGCCallbackFlagSynchronousPhantomCallbackProcessing, v8::internal::MakeCancelableTask(), v8::internal::Isolate::MemorySaverModeEnabled(), v8::internal::Heap::NOT_IN_GC, second_pass_callbacks_, second_pass_callbacks_task_posted_, and v8::internal::v8_flags.
Referenced by v8::internal::Heap::CollectGarbage().
ProcessWeakYoungObjects()
void v8::internal::GlobalHandles::ProcessWeakYoungObjects (RootVisitor * v, WeakSlotCallbackWithHeap should_reset_handle)
Definition at line 728 of file global-handles.cc.
                                                                  {
  for (Node* node : young_nodes_) {
    DCHECK(node->is_in_young_list());
    if (node->IsWeakRetainer() &&
        !ResetWeakNodeIfDead(node, should_reset_handle)) {
      // Node is weak and alive, so it should be passed onto the visitor if
      // present.
      if (v) {
        v->VisitRootPointer(Root::kGlobalHandles, node->label(),
                            node->location());
      }
    }
  }
}
References v8::internal::DCHECK(), ResetWeakNodeIfDead(), v8::internal::RootVisitor::VisitRootPointer(), and young_nodes_.
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences().
RecordStats()
void v8::internal::GlobalHandles::RecordStats (HeapStats * stats)
Definition at line 958 of file global-handles.cc.
                                                {
  stats->global_handle_count = 0;
  stats->weak_global_handle_count = 0;
  stats->pending_global_handle_count = 0;
  stats->near_death_global_handle_count = 0;
  stats->free_global_handle_count = 0;
  for (Node* node : *regular_nodes_) {
    stats->global_handle_count += 1;
    if (node->state() == Node::WEAK) {
      stats->weak_global_handle_count += 1;
    } else if (node->state() == Node::NEAR_DEATH) {
      stats->near_death_global_handle_count += 1;
    } else if (node->state() == Node::FREE) {
      stats->free_global_handle_count += 1;
    }
  }
}
References v8::internal::GlobalHandles::Node::FREE, v8::internal::HeapStats::free_global_handle_count, v8::internal::HeapStats::global_handle_count, v8::internal::GlobalHandles::Node::NEAR_DEATH, v8::internal::HeapStats::near_death_global_handle_count, v8::internal::HeapStats::pending_global_handle_count, regular_nodes_, v8::internal::GlobalHandles::Node::WEAK, and v8::internal::HeapStats::weak_global_handle_count.
Referenced by v8::internal::Heap::RecordStats().
ResetWeakNodeIfDead()
bool v8::internal::GlobalHandles::ResetWeakNodeIfDead (Node * node, WeakSlotCallbackWithHeap should_reset_node) [inline], [private]
Definition at line 692 of file global-handles.cc.
                                                              {
  DCHECK(node->IsWeakRetainer());
  if (!should_reset_handle(isolate()->heap(), node->location())) return false;
  switch (node->weakness_type()) {
    case WeaknessType::kNoCallback:
      node->ResetPhantomHandle();
      break;
    case WeaknessType::kCallback:
      [[fallthrough]];
    case WeaknessType::kCallbackWithTwoEmbedderFields:
      node->CollectPhantomCallbackData(&pending_phantom_callbacks_);
      break;
  }
  return true;
}
References v8::internal::GlobalHandles::Node::CollectPhantomCallbackData(), v8::internal::DCHECK(), heap(), isolate(), v8::internal::GlobalHandles::Node::IsWeakRetainer(), v8::internal::kCallback, v8::internal::kCallbackWithTwoEmbedderFields, v8::internal::kNoCallback, v8::internal::NodeBase< Child >::location(), pending_phantom_callbacks_, v8::internal::GlobalHandles::Node::ResetPhantomHandle(), and v8::internal::GlobalHandles::Node::weakness_type().
Referenced by IterateWeakRootsForPhantomHandles(), and ProcessWeakYoungObjects().
TotalSize()
size_t v8::internal::GlobalHandles::TotalSize () const
Definition at line 599 of file global-handles.cc.
{ return regular_nodes_->TotalSize(); }
References regular_nodes_.
Referenced by v8::internal::Heap::TotalGlobalHandlesSize().
UpdateListOfYoungNodes()
void v8::internal::GlobalHandles::UpdateListOfYoungNodes ()
Definition at line 817 of file global-handles.cc.
                                           {
  UpdateListOfYoungNodesImpl(isolate_, &young_nodes_);
}
References isolate_, v8::internal::anonymous_namespace{global-handles.cc}::UpdateListOfYoungNodesImpl(), and young_nodes_.
Referenced by v8::internal::MinorMarkSweepCollector::CollectGarbage().
UsedSize()
size_t v8::internal::GlobalHandles::UsedSize () const
Definition at line 601 of file global-handles.cc.
                                     {
  return regular_nodes_->handles_count() * sizeof(Node);
}
References regular_nodes_.
Referenced by v8::internal::Heap::UsedGlobalHandlesSize().
Member Data Documentation
isolate_
Isolate* const v8::internal::GlobalHandles::isolate_ [private]
Definition at line 154 of file global-handles.h.
Referenced by ClearListOfYoungNodes(), InvokeSecondPassPhantomCallbacks(), PostGarbageCollectionProcessing(), and UpdateListOfYoungNodes().
last_gc_custom_callbacks_
size_t v8::internal::GlobalHandles::last_gc_custom_callbacks_ = 0 [private]
Definition at line 164 of file global-handles.h.
Referenced by InvokeFirstPassWeakCallbacks().
pending_phantom_callbacks_
std::vector<std::pair<Node*, PendingPhantomCallback> > v8::internal::GlobalHandles::pending_phantom_callbacks_ [private]
Definition at line 161 of file global-handles.h.
Referenced by InvokeFirstPassWeakCallbacks(), and ResetWeakNodeIfDead().
regular_nodes_
std::unique_ptr<NodeSpace<Node> > v8::internal::GlobalHandles::regular_nodes_ [private]
Definition at line 156 of file global-handles.h.
Referenced by Create(), handles_count(), IterateAllRoots(), IterateAllRootsForTesting(), IterateStrongRoots(), IterateWeakRoots(), IterateWeakRootsForPhantomHandles(), RecordStats(), TotalSize(), and UsedSize().
second_pass_callbacks_
std::vector<PendingPhantomCallback> v8::internal::GlobalHandles::second_pass_callbacks_ [private]
Definition at line 162 of file global-handles.h.
Referenced by InvokeFirstPassWeakCallbacks(), InvokeSecondPassPhantomCallbacks(), and PostGarbageCollectionProcessing().
second_pass_callbacks_task_posted_
bool v8::internal::GlobalHandles::second_pass_callbacks_task_posted_ = false [private]
Definition at line 163 of file global-handles.h.
Referenced by PostGarbageCollectionProcessing().
young_nodes_
std::vector<Node*> v8::internal::GlobalHandles::young_nodes_ [private]
Definition at line 159 of file global-handles.h.
Referenced by ClearListOfYoungNodes(), Create(), IterateAllYoungRoots(), IterateYoungStrongAndDependentRoots(), ProcessWeakYoungObjects(), and UpdateListOfYoungNodes().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/global-handles.h
/mnt/V8SourceCode/src/handles/global-handles-inl.h
/mnt/V8SourceCode/src/handles/global-handles.cc