v8::internal::compiler::WasmEscapeAnalysis Class Reference
#include <wasm-escape-analysis.h>
Public Member Functions
WasmEscapeAnalysis (Editor *editor, MachineGraph *mcgraph)
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Member Functions
Reduction ReduceAllocateRaw (Node *call)
Private Attributes
MachineGraph *const mcgraph_
Additional Inherited Members
Detailed Description
Definition at line 22 of file wasm-escape-analysis.h.
Constructor & Destructor Documentation
WasmEscapeAnalysis()
v8::internal::compiler::WasmEscapeAnalysis::WasmEscapeAnalysis (Editor * editor, MachineGraph * mcgraph) [inline]
Definition at line 24 of file wasm-escape-analysis.h.
      : AdvancedReducer(editor), mcgraph_(mcgraph) {}
Member Function Documentation
Reduce()
Reduction v8::internal::compiler::WasmEscapeAnalysis::Reduce (Node * node) [final], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 14 of file wasm-escape-analysis.cc.
                                               {
  switch (node->opcode()) {
    case IrOpcode::kAllocateRaw:
      return ReduceAllocateRaw(node);
    default:
      return NoChange();
  }
}
References v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::opcode(), and ReduceAllocateRaw().
ReduceAllocateRaw()
Reduction v8::internal::compiler::WasmEscapeAnalysis::ReduceAllocateRaw (Node * call) [private]
Definition at line 23 of file wasm-escape-analysis.cc.
                                                          {
  DCHECK_EQ(node->opcode(), IrOpcode::kAllocateRaw);
  // TODO(manoskouk): Account for phis that still have uses.
  // Collect all value edges of {node} in this vector.
  std::vector<Edge> value_edges;
  for (Edge edge : node->use_edges()) {
    if (NodeProperties::IsValueEdge(edge)) {
      if ((edge.from()->opcode() == IrOpcode::kPhi &&
           edge.from()->use_edges().empty()) ||
          (edge.index() == 0 &&
           (edge.from()->opcode() == IrOpcode::kStoreToObject ||
            edge.from()->opcode() == IrOpcode::kInitializeImmutableInObject))) {
        // StoreToObject, InitializeImmutableInObject and phis without uses can
        // be replaced and do not require the allocation.
        value_edges.push_back(edge);
      } else {
        // Allocation not reducible.
        return NoChange();
      }
    }
  }
  // Remove all discovered stores from the effect chain.
  for (Edge edge : value_edges) {
    DCHECK(NodeProperties::IsValueEdge(edge));
    Node* use = edge.from();
    if (use->opcode() == IrOpcode::kPhi) {
      DCHECK(use->use_edges().empty());
      // Useless phi. Kill it.
      use->Kill();
    } else {
      DCHECK_EQ(edge.index(), 0);
      DCHECK(!use->IsDead());
      DCHECK(use->opcode() == IrOpcode::kStoreToObject ||
             use->opcode() == IrOpcode::kInitializeImmutableInObject);
      // The value stored by this StoreToObject node might be another allocation
      // which has no more uses. Therefore we have to revisit it. Note that this
      // will not happen automatically: ReplaceWithValue does not trigger
      // revisits of former inputs of the replaced node.
      Node* stored_value = NodeProperties::GetValueInput(use, 2);
      Revisit(stored_value);
      ReplaceWithValue(use, mcgraph_->Dead(),
                       NodeProperties::GetEffectInput(use), mcgraph_->Dead());
      use->Kill();
    }
  }
  // Remove the allocation from the effect and control chains.
  ReplaceWithValue(node, mcgraph_->Dead(), NodeProperties::GetEffectInput(node),
                   NodeProperties::GetControlInput(node));
  return Changed(node);
}
References v8::internal::compiler::Reducer::Changed(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::MachineGraph::Dead(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::NodeProperties::IsValueEdge(), mcgraph_, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::compiler::AdvancedReducer::Revisit(), use(), and v8::internal::compiler::Node::use_edges().
Referenced by Reduce().
reducer_name()
const char* v8::internal::compiler::WasmEscapeAnalysis::reducer_name () const [inline], [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 27 of file wasm-escape-analysis.h.
{ return "WasmEscapeAnalysis"; }
Member Data Documentation
mcgraph_
MachineGraph* const v8::internal::compiler::WasmEscapeAnalysis::mcgraph_ [private]
Definition at line 33 of file wasm-escape-analysis.h.
Referenced by ReduceAllocateRaw().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/wasm-escape-analysis.h
/mnt/V8SourceCode/src/compiler/wasm-escape-analysis.cc