v8::internal::compiler::turboshaft::MemoryRepresentation Class Reference
#include <representations.h>
Public Types
enum class Enum : uint8_t {
kInt8
, kUint8
, kInt16
, kUint16
,
kInt32
, kUint32
, kInt64
, kUint64
,
kFloat16
, kFloat32
, kFloat64
, kAnyTagged
,
kTaggedPointer
, kTaggedSigned
, kAnyUncompressedTagged
, kUncompressedTaggedPointer
,
kUncompressedTaggedSigned
, kProtectedPointer
, kIndirectPointer
, kSandboxedPointer
,
kSimd128
, kSimd256
 }
Public Member Functions
constexpr MemoryRepresentation (Enum value)
constexpr MemoryRepresentation ()
constexpr bool is_valid () const
constexpr Enum value () const
constexpr operator Enum () const
bool IsSigned () const
bool IsCompressibleTagged () const
RegisterRepresentation ToRegisterRepresentation () const
RegisterRepresentation ToRegisterRepresentationForStore () const
MachineType ToMachineType () const
constexpr uint8_t SizeInBytes () const
constexpr uint8_t SizeInBytesLog2 () const
Static Public Member Functions
static constexpr MemoryRepresentation Int8 ()
static constexpr MemoryRepresentation Uint8 ()
static constexpr MemoryRepresentation Int16 ()
static constexpr MemoryRepresentation Uint16 ()
static constexpr MemoryRepresentation Int32 ()
static constexpr MemoryRepresentation Uint32 ()
static constexpr MemoryRepresentation Int64 ()
static constexpr MemoryRepresentation Uint64 ()
static constexpr MemoryRepresentation UintPtr ()
static constexpr MemoryRepresentation Float16 ()
static constexpr MemoryRepresentation Float32 ()
static constexpr MemoryRepresentation Float64 ()
static constexpr MemoryRepresentation AnyTagged ()
static constexpr MemoryRepresentation TaggedPointer ()
static constexpr MemoryRepresentation TaggedSigned ()
static constexpr MemoryRepresentation AnyUncompressedTagged ()
static constexpr MemoryRepresentation UncompressedTaggedPointer ()
static constexpr MemoryRepresentation UncompressedTaggedSigned ()
static constexpr MemoryRepresentation ProtectedPointer ()
static constexpr MemoryRepresentation IndirectPointer ()
static constexpr MemoryRepresentation SandboxedPointer ()
static constexpr MemoryRepresentation Simd128 ()
static constexpr MemoryRepresentation Simd256 ()
static MemoryRepresentation FromRegisterRepresentation (RegisterRepresentation repr, bool is_signed)
static MemoryRepresentation FromMachineType (MachineType type)
static constexpr MemoryRepresentation FromMachineRepresentation (MachineRepresentation rep)
Private Attributes
Enum value_
Static Private Attributes
static constexpr Enum kInvalid = static_cast<Enum>(-1)
Detailed Description
Definition at line 513 of file representations.h.
Member Enumeration Documentation
Enum
enum v8::internal::compiler::turboshaft::MemoryRepresentation::Enum : uint8_t [strong]
Enumerator
kInt8
kUint8
kInt16
kUint16
kInt32
kUint32
kInt64
kUint64
kFloat16
kFloat32
kFloat64
kAnyTagged
kTaggedPointer
kTaggedSigned
kAnyUncompressedTagged
kUncompressedTaggedPointer
kUncompressedTaggedSigned
kProtectedPointer
kIndirectPointer
kSandboxedPointer
kSimd128
kSimd256
Definition at line 515 of file representations.h.
                  : uint8_t {
    kInt8,
    kUint8,
    kInt16,
    kUint16,
    kInt32,
    kUint32,
    kInt64,
    kUint64,
    kFloat16,
    kFloat32,
    kFloat64,
    kAnyTagged,
    kTaggedPointer,
    kTaggedSigned,
    kAnyUncompressedTagged,
    kUncompressedTaggedPointer,
    kUncompressedTaggedSigned,
    kProtectedPointer,
    kIndirectPointer,
    kSandboxedPointer,
    kSimd128,
    kSimd256
  };
Constructor & Destructor Documentation
MemoryRepresentation() [1/2]
constexpr v8::internal::compiler::turboshaft::MemoryRepresentation::MemoryRepresentation (Enum value) [inline], [explicit], [constexpr]
Definition at line 540 of file representations.h.
: value_(value) {}
MemoryRepresentation() [2/2]
constexpr v8::internal::compiler::turboshaft::MemoryRepresentation::MemoryRepresentation () [inline], [constexpr]
Definition at line 541 of file representations.h.
: value_(kInvalid) {}
Referenced by AnyTagged(), AnyUncompressedTagged(), Float16(), Float32(), Float64(), IndirectPointer(), Int16(), Int32(), Int64(), Int8(), ProtectedPointer(), SandboxedPointer(), Simd128(), Simd256(), TaggedPointer(), TaggedSigned(), Uint16(), Uint32(), Uint64(), Uint8(), UncompressedTaggedPointer(), and UncompressedTaggedSigned().
Member Function Documentation
AnyTagged()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged () [inline], [static], [constexpr]
Definition at line 591 of file representations.h.
                                                    {
    return MemoryRepresentation(Enum::kAnyTagged);
  }
References kAnyTagged, and MemoryRepresentation().
Referenced by v8::internal::detail::BuiltinArgumentsTS< Assembler >::AtIndex(), v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::Dereference(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::FindOrderedHashEntry(), FromMachineRepresentation(), FromMachineType(), FromRegisterRepresentation(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::GeneratorStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), IsSigned(), v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorSlot(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadFieldByIndex(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadFixedArrayElement(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadProtectedPointerField(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::LoadRegister(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadRoot(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LowerGlobalSetOrGet(), v8::internal::compiler::turboshaft::LoadOp::machine_type(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RepresentationFor(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RttCanon(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), v8::internal::FeedbackCollectorReducer< Next >::StoreFeedbackVectorSlot(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreFixedArrayElement(), v8::internal::wasm::WasmWrapperTSGraphBuilder::ToJS(), ToMachineType(), ToRegisterRepresentation(), v8::internal::compiler::VisitGeneralStore(), and v8::internal::compiler::VisitStoreCommon().
AnyUncompressedTagged()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::AnyUncompressedTagged () [inline], [static], [constexpr]
Definition at line 600 of file representations.h.
                                                                {
    return MemoryRepresentation(Enum::kAnyUncompressedTagged);
  }
References kAnyUncompressedTagged, and MemoryRepresentation().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), IsSigned(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), ToMachineType(), ToRegisterRepresentation(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), and v8::internal::compiler::VisitStoreCommon().
Float16()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::Float16 () [inline], [static], [constexpr]
Definition at line 582 of file representations.h.
                                                  {
    return MemoryRepresentation(Enum::kFloat16);
  }
References kFloat16, and MemoryRepresentation().
Referenced by FromMachineRepresentation(), FromMachineType(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), IsSigned(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RepresentationFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), ToMachineType(), ToRegisterRepresentation(), v8::internal::compiler::VisitGeneralStore(), and v8::internal::compiler::VisitStoreCommon().
Float32()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::Float32 () [inline], [static], [constexpr]
Definition at line 585 of file representations.h.
                                                  {
    return MemoryRepresentation(Enum::kFloat32);
  }
References kFloat32, and MemoryRepresentation().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsLoadMem(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BinOpImpl(), FromMachineRepresentation(), FromMachineType(), FromRegisterRepresentation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), IsSigned(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadMem(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RepresentationFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), v8::internal::wasm::TurboshaftGraphBuildingInterface::SimdLaneOp(), v8::internal::wasm::TurboshaftGraphBuildingInterface::SimdOp(), SizeInBytesLog2(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreMem(), ToMachineType(), ToRegisterRepresentation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl(), v8::internal::compiler::VisitGeneralStore(), and v8::internal::compiler::VisitStoreCommon().
Float64()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::Float64 () [inline], [static], [constexpr]
Definition at line 588 of file representations.h.
                                                  {
    return MemoryRepresentation(Enum::kFloat64);
  }
References kFloat64, and MemoryRepresentation().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsLoadMem(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BinOpImpl(), FromMachineRepresentation(), FromMachineType(), FromRegisterRepresentation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), IsSigned(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadFixedDoubleArrayElement(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RepresentationFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreFixedDoubleArrayElement(), ToMachineType(), ToRegisterRepresentation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl(), v8::internal::compiler::VisitGeneralStore(), and v8::internal::compiler::VisitStoreCommon().
FromMachineRepresentation()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::FromMachineRepresentation (MachineRepresentation rep) [inline], [static], [constexpr]
Definition at line 852 of file representations.h.
                                 {
    switch (rep) {
      case MachineRepresentation::kWord8:
        return Uint8();
      case MachineRepresentation::kWord16:
        return Uint16();
      case MachineRepresentation::kWord32:
        return Uint32();
      case MachineRepresentation::kWord64:
        return Uint64();
      case MachineRepresentation::kTaggedSigned:
        return TaggedSigned();
      case MachineRepresentation::kTaggedPointer:
        return TaggedPointer();
      case MachineRepresentation::kTagged:
        return AnyTagged();
      case MachineRepresentation::kFloat16:
        return Float16();
      case MachineRepresentation::kFloat32:
        return Float32();
      case MachineRepresentation::kFloat64:
        return Float64();
      case MachineRepresentation::kSandboxedPointer:
        return SandboxedPointer();
      case MachineRepresentation::kSimd128:
        return Simd128();
      case MachineRepresentation::kSimd256:
        return Simd256();
      case MachineRepresentation::kNone:
      case MachineRepresentation::kMapWord:
      case MachineRepresentation::kBit:
      case MachineRepresentation::kCompressedPointer:
      case MachineRepresentation::kCompressed:
      case MachineRepresentation::kProtectedPointer:
      case MachineRepresentation::kIndirectPointer:
      case MachineRepresentation::kFloat16RawBits:
        UNREACHABLE();
    }
  }
References AnyTagged(), Float16(), Float32(), Float64(), v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::kProtectedPointer, v8::internal::kSandboxedPointer, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, SandboxedPointer(), Simd128(), Simd256(), TaggedPointer(), TaggedSigned(), Uint16(), Uint32(), Uint64(), Uint8(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::wasm::WasmWrapperTSGraphBuilder::SafeLoad(), v8::internal::wasm::WasmWrapperTSGraphBuilder::SafeStore(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreInStackSlot(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreLane(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreMem().
FromMachineType()
static MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::FromMachineType (MachineType type) [inline], [static]
Definition at line 807 of file representations.h.
                                                                {
    switch (type.representation()) {
      case MachineRepresentation::kWord8:
        return type.IsSigned() ? Int8() : Uint8();
      case MachineRepresentation::kWord16:
        return type.IsSigned() ? Int16() : Uint16();
      case MachineRepresentation::kWord32:
        return type.IsSigned() ? Int32() : Uint32();
      case MachineRepresentation::kWord64:
        return type.IsSigned() ? Int64() : Uint64();
      case MachineRepresentation::kTaggedSigned:
        return TaggedSigned();
      case MachineRepresentation::kTaggedPointer:
        return TaggedPointer();
      case MachineRepresentation::kMapWord:
        // Turboshaft does not support map packing.
        DCHECK(!V8_MAP_PACKING_BOOL);
        return TaggedPointer();
      case MachineRepresentation::kProtectedPointer:
        return ProtectedPointer();
      case MachineRepresentation::kIndirectPointer:
        return IndirectPointer();
      case MachineRepresentation::kTagged:
        return AnyTagged();
      case MachineRepresentation::kFloat16:
        return Float16();
      case MachineRepresentation::kFloat32:
        return Float32();
      case MachineRepresentation::kFloat64:
        return Float64();
      case MachineRepresentation::kSandboxedPointer:
        return SandboxedPointer();
      case MachineRepresentation::kSimd128:
        return Simd128();
      case MachineRepresentation::kSimd256:
        return Simd256();
      case MachineRepresentation::kNone:
      case MachineRepresentation::kBit:
      case MachineRepresentation::kCompressedPointer:
      case MachineRepresentation::kCompressed:
      case MachineRepresentation::kFloat16RawBits:
        UNREACHABLE();
    }
  }
References AnyTagged(), v8::internal::DCHECK(), Float16(), Float32(), Float64(), IndirectPointer(), Int16(), Int32(), Int64(), Int8(), v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::kProtectedPointer, v8::internal::kSandboxedPointer, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, ProtectedPointer(), SandboxedPointer(), Simd128(), Simd256(), TaggedPointer(), TaggedSigned(), v8::internal::tracing::type, Uint16(), Uint32(), Uint64(), Uint8(), v8::internal::UNREACHABLE(), and V8_MAP_PACKING_BOOL.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::LoadDataViewElement(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadElement(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadLane(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadMem(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadTransform(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::StoreDataViewElement(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreElement(), and v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreFieldImpl().
FromRegisterRepresentation()
static MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::FromRegisterRepresentation (RegisterRepresentation repr, bool is_signed) [inline], [static]
Definition at line 723 of file representations.h.
                                                   {
    switch (repr.value()) {
      case RegisterRepresentation::Word32():
        return is_signed ? Int32() : Uint32();
      case RegisterRepresentation::Word64():
        return is_signed ? Int64() : Uint64();
      case RegisterRepresentation::Float32():
        return Float32();
      case RegisterRepresentation::Float64():
        return Float64();
      case RegisterRepresentation::Tagged():
        return AnyTagged();
      case RegisterRepresentation::Simd128():
        return Simd128();
      case RegisterRepresentation::Simd256():
        return Simd256();
      case RegisterRepresentation::Compressed():
        UNREACHABLE();
    }
  }
References AnyTagged(), v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), Float64(), Int32(), Int64(), v8::internal::is_signed(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd128(), Simd128(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd256(), Simd256(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), Uint32(), Uint64(), v8::internal::UNREACHABLE(), v8::internal::compiler::turboshaft::RegisterRepresentation::value(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{late-load-elimination-reducer.cc}::RepIsCompatible(), and v8::internal::compiler::turboshaft::RepIsCompatible().
IndirectPointer()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::IndirectPointer () [inline], [static], [constexpr]
Definition at line 612 of file representations.h.
                                                          {
    return MemoryRepresentation(Enum::kIndirectPointer);
  }
References kIndirectPointer, and MemoryRepresentation().
Referenced by FromMachineType(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), IsSigned(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), ToMachineType(), ToRegisterRepresentation(), v8::internal::compiler::VisitGeneralStore(), and v8::internal::compiler::VisitStoreCommon().
Int16()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::Int16 () [inline], [static], [constexpr]
Definition at line 557 of file representations.h.
                                                {
    return MemoryRepresentation(Enum::kInt16);
  }
References kInt16, and MemoryRepresentation().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsLoadMem(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BinOpImpl(), FromMachineType(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsInt16(), IsSigned(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadLane(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RepresentationFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), v8::internal::wasm::TurboshaftGraphBuildingInterface::SimdLaneOp(), v8::internal::wasm::TurboshaftGraphBuildingInterface::SimdOp(), SizeInBytesLog2(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreMem(), ToMachineType(), ToRegisterRepresentation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::VisitStoreCommon(), and v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation().
Int32()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::Int32 () [inline], [static], [constexpr]
Definition at line 563 of file representations.h.
                                                {
    return MemoryRepresentation(Enum::kInt32);
  }
References kInt32, and MemoryRepresentation().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsLoadMem(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::AssertNotNull(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicNotify(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicWait(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BinOpImpl(), v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlagHelper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildReceiverNode(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::Call(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DataDrop(), FromMachineType(), FromRegisterRepresentation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), v8::internal::compiler::turboshaft::IsInt32TruncatedLoadPattern(), IsSigned(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Load(), v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::Load(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::LoadAndUntagRegister(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadLane(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LowerGlobalSetOrGet(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RepresentationFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Store(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store(), ToMachineType(), ToRegisterRepresentation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::VisitStoreCommon(), and v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation().
Int64()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::Int64 () [inline], [static], [constexpr]
Definition at line 569 of file representations.h.
                                                {
    return MemoryRepresentation(Enum::kInt64);
  }
References kInt64, and MemoryRepresentation().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::AtomicRMW(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicWait(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCcallConvertFloat(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCcallConvertFloatSat(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCCallForFloatConversion(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildDiv64Call(), FromMachineType(), FromRegisterRepresentation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), IsSigned(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Load(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadLane(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadTransform(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RepresentationFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Store(), ToMachineType(), ToRegisterRepresentation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::VisitGeneralStore(), and v8::internal::compiler::VisitStoreCommon().
Int8()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::Int8 () [inline], [static], [constexpr]
Definition at line 551 of file representations.h.
                                               {
    return MemoryRepresentation(Enum::kInt8);
  }
References kInt8, and MemoryRepresentation().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsLoadMem(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BinOpImpl(), FromMachineType(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetMemoryAccessKind(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsInt16(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsInt8(), IsSigned(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadLane(), v8::internal::compiler::turboshaft::LoadOp::Kind::MaybeUnaligned(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RepresentationFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store(), ToMachineType(), ToRegisterRepresentation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::VisitStoreCommon(), and v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation().
is_valid()
constexpr bool v8::internal::compiler::turboshaft::MemoryRepresentation::is_valid () const [inline], [constexpr]
Definition at line 543 of file representations.h.
{ return value_ != kInvalid; }
References kInvalid, and value_.
Referenced by value().
IsCompressibleTagged()
bool v8::internal::compiler::turboshaft::MemoryRepresentation::IsCompressibleTagged () const [inline]
Definition at line 659 of file representations.h.
                                    {
    switch (*this) {
      case AnyTagged():
      case TaggedPointer():
      case TaggedSigned():
        return true;
      case Int8():
      case Int16():
      case Int32():
      case Int64():
      case Uint8():
      case Uint16():
      case Uint32():
      case Uint64():
      case Float16():
      case Float32():
      case Float64():
      case AnyUncompressedTagged():
      case UncompressedTaggedPointer():
      case UncompressedTaggedSigned():
      case IndirectPointer():
      case ProtectedPointer():
      case SandboxedPointer():
      case Simd128():
      case Simd256():
        return false;
    }
  }
References AnyTagged(), AnyUncompressedTagged(), Float16(), Float32(), Float64(), IndirectPointer(), Int16(), Int32(), Int64(), Int8(), ProtectedPointer(), SandboxedPointer(), Simd128(), Simd256(), TaggedPointer(), TaggedSigned(), Uint16(), Uint32(), Uint64(), Uint8(), UncompressedTaggedPointer(), and UncompressedTaggedSigned().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::MarkAddressingBase(), and v8::internal::compiler::turboshaft::LoadOp::Validate().
IsSigned()
bool v8::internal::compiler::turboshaft::MemoryRepresentation::IsSigned () const [inline]
Definition at line 625 of file representations.h.
                        {
    switch (*this) {
      case Int8():
      case Int16():
      case Int32():
      case Int64():
        return true;
      case Uint8():
      case Uint16():
      case Uint32():
      case Uint64():
        return false;
      case Float16():
      case Float32():
      case Float64():
      case AnyTagged():
      case TaggedPointer():
      case TaggedSigned():
      case AnyUncompressedTagged():
      case UncompressedTaggedPointer():
      case UncompressedTaggedSigned():
      case ProtectedPointer():
      case IndirectPointer():
      case SandboxedPointer():
      case Simd128():
      case Simd256():
        UNREACHABLE();
    }
  }
References AnyTagged(), AnyUncompressedTagged(), Float16(), Float32(), Float64(), IndirectPointer(), Int16(), Int32(), Int64(), Int8(), ProtectedPointer(), SandboxedPointer(), Simd128(), Simd256(), TaggedPointer(), TaggedSigned(), Uint16(), Uint32(), Uint64(), Uint8(), UncompressedTaggedPointer(), UncompressedTaggedSigned(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadMem().
operator Enum()
constexpr v8::internal::compiler::turboshaft::MemoryRepresentation::operator Enum () const [inline], [constexpr]
Definition at line 549 of file representations.h.
{ return value(); }
References value().
ProtectedPointer()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::ProtectedPointer () [inline], [static], [constexpr]
Definition at line 609 of file representations.h.
                                                           {
    return MemoryRepresentation(Enum::kProtectedPointer);
  }
References kProtectedPointer, and MemoryRepresentation().
Referenced by FromMachineType(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), IsSigned(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadProtectedPointerField(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), ToMachineType(), ToRegisterRepresentation(), v8::internal::compiler::VisitGeneralStore(), and v8::internal::compiler::VisitStoreCommon().
SandboxedPointer()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::SandboxedPointer () [inline], [static], [constexpr]
Definition at line 615 of file representations.h.
                                                           {
    return MemoryRepresentation(Enum::kSandboxedPointer);
  }
References kSandboxedPointer, and MemoryRepresentation().
Referenced by FromMachineRepresentation(), FromMachineType(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), IsSigned(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), ToMachineType(), ToRegisterRepresentation(), v8::internal::compiler::VisitGeneralStore(), and v8::internal::compiler::VisitStoreCommon().
Simd128()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::Simd128 () [inline], [static], [constexpr]
Definition at line 618 of file representations.h.
                                                  {
    return MemoryRepresentation(Enum::kSimd128);
  }
References kSimd128, and MemoryRepresentation().
Referenced by v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), FromMachineRepresentation(), FromMachineType(), FromRegisterRepresentation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineMemCopy(), IsCompressibleTagged(), IsSigned(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RepresentationFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), ToMachineType(), ToRegisterRepresentation(), v8::internal::compiler::VisitGeneralStore(), and v8::internal::compiler::VisitStoreCommon().
Simd256()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::Simd256 () [inline], [static], [constexpr]
Definition at line 621 of file representations.h.
                                                  {
    return MemoryRepresentation(Enum::kSimd256);
  }
References kSimd256, and MemoryRepresentation().
Referenced by FromMachineRepresentation(), FromMachineType(), FromRegisterRepresentation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), IsSigned(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Load(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Store(), ToMachineType(), ToRegisterRepresentation(), v8::internal::compiler::VisitGeneralStore(), and v8::internal::compiler::VisitStoreCommon().
SizeInBytes()
constexpr uint8_t v8::internal::compiler::turboshaft::MemoryRepresentation::SizeInBytes () const [inline], [constexpr]
Definition at line 893 of file representations.h.
                                        {
    return uint8_t{1} << SizeInBytesLog2();
  }
References SizeInBytesLog2().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BoundsCheckMem(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCcallConvertFloatSat(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCCallForFloatConversion(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildDiv64Call(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIntToFloatConversionInstruction(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToInt32(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToStackSlot(), v8::internal::compiler::turboshaft::MemoryContentTable::Find(), v8::internal::compiler::turboshaft::MemoryContentTable::Insert(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadMem(), v8::internal::compiler::turboshaft::anonymous_namespace{late-load-elimination-reducer.cc}::RepIsCompatible(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreInStackSlot(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreMem().
SizeInBytesLog2()
constexpr uint8_t v8::internal::compiler::turboshaft::MemoryRepresentation::SizeInBytesLog2 () const [inline], [constexpr]
Definition at line 897 of file representations.h.
                                            {
    switch (*this) {
      case Int8():
      case Uint8():
        return 0;
      case Int16():
      case Uint16():
      case Float16():
        return 1;
      case Int32():
      case Uint32():
      case Float32():
      case IndirectPointer():
        return 2;
      case Int64():
      case Uint64():
      case Float64():
      case SandboxedPointer():
        return 3;
      case AnyTagged():
      case TaggedPointer():
      case TaggedSigned():
      case ProtectedPointer():
        return kTaggedSizeLog2;
      case AnyUncompressedTagged():
      case UncompressedTaggedPointer():
      case UncompressedTaggedSigned():
        return kSystemPointerSizeLog2;
      case Simd128():
        return 4;
      case Simd256():
        return 5;
    }
  }
References AnyTagged(), AnyUncompressedTagged(), Float16(), Float32(), Float64(), IndirectPointer(), Int16(), Int32(), Int64(), Int8(), v8::internal::kSystemPointerSizeLog2, v8::internal::kTaggedSizeLog2, ProtectedPointer(), SandboxedPointer(), Simd128(), Simd256(), TaggedPointer(), TaggedSigned(), Uint16(), Uint32(), Uint64(), Uint8(), UncompressedTaggedPointer(), and UncompressedTaggedSigned().
Referenced by v8::internal::compiler::Arm64OperandGenerator::CanBeLoadStoreShiftImmediate(), v8::internal::compiler::turboshaft::IsInt32TruncatedLoadPattern(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadElement(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadOffHeap(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), SizeInBytes(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreElement(), and v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreOffHeap().
TaggedPointer()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer () [inline], [static], [constexpr]
Definition at line 594 of file representations.h.
                                                        {
    return MemoryRepresentation(Enum::kTaggedPointer);
  }
References kTaggedPointer, and MemoryRepresentation().
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAndReturn(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildSuspend(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchCase(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchException(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DataDrop(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ElemDrop(), FromMachineRepresentation(), FromMachineType(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetRttFromDescriptor(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::Initialize(), IsCompressibleTagged(), IsSigned(), v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadContextFromJSFunction(), v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadMap(), v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadSharedFunctionInfo(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadStackArgument(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadTable(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadTrustedPointerField(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LoadWasmTypeInfo(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LowerGlobalSetOrGet(), v8::internal::compiler::turboshaft::LoadOp::machine_type(), v8::internal::wasm::TurboshaftGraphBuildingInterface::managed_object_maps(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefGetDesc(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallRef(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RootConstant(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Throw(), v8::internal::wasm::WasmWrapperTSGraphBuilder::ToJS(), ToMachineType(), ToRegisterRepresentation(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::VisitStoreCommon(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::WasmRefFunc(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
TaggedSigned()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedSigned () [inline], [static], [constexpr]
Definition at line 597 of file representations.h.
                                                       {
    return MemoryRepresentation(Enum::kTaggedSigned);
  }
References kTaggedSigned, and MemoryRepresentation().
Referenced by v8::internal::StringBuiltinsReducer< Next >::AllocateSeqOneByteString(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::AllocateSeqTwoByteString(), v8::internal::StringBuiltinsReducer< Next >::AllocateSeqTwoByteString(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::FindOrderedHashEntry(), FromMachineRepresentation(), FromMachineType(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::GeneratorStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), IsSigned(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::LoadAndUntagRegister(), v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadExportedFunctionIndexAsSmi(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableSize(), ToMachineType(), ToRegisterRepresentation(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::UpdateJSArrayLength(), v8::internal::compiler::VisitGeneralStore(), and v8::internal::compiler::VisitStoreCommon().
ToMachineType()
MachineType v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType () const [inline]
Definition at line 758 of file representations.h.
                                    {
    switch (*this) {
      case Int8():
        return MachineType::Int8();
      case Uint8():
        return MachineType::Uint8();
      case Int16():
        return MachineType::Int16();
      case Uint16():
        return MachineType::Uint16();
      case Int32():
        return MachineType::Int32();
      case Uint32():
        return MachineType::Uint32();
      case Int64():
        return MachineType::Int64();
      case Uint64():
        return MachineType::Uint64();
      case Float16():
        return MachineType::Float16();
      case Float32():
        return MachineType::Float32();
      case Float64():
        return MachineType::Float64();
      case AnyTagged():
        return MachineType::AnyTagged();
      case TaggedPointer():
        return MachineType::TaggedPointer();
      case TaggedSigned():
        return MachineType::TaggedSigned();
      case AnyUncompressedTagged():
        return MachineType::AnyTagged();
      case UncompressedTaggedPointer():
        return MachineType::TaggedPointer();
      case UncompressedTaggedSigned():
        return MachineType::TaggedSigned();
      case ProtectedPointer():
        return MachineType::ProtectedPointer();
      case IndirectPointer():
        return MachineType::IndirectPointer();
      case SandboxedPointer():
        return MachineType::SandboxedPointer();
      case Simd128():
        return MachineType::Simd128();
      case Simd256():
        return MachineType::Simd256();
    }
  }
References v8::internal::MachineType::AnyTagged(), AnyTagged(), AnyUncompressedTagged(), v8::internal::MachineType::Float16(), Float16(), v8::internal::MachineType::Float32(), Float32(), v8::internal::MachineType::Float64(), Float64(), v8::internal::MachineType::IndirectPointer(), IndirectPointer(), v8::internal::MachineType::Int16(), Int16(), v8::internal::MachineType::Int32(), Int32(), v8::internal::MachineType::Int64(), Int64(), v8::internal::MachineType::Int8(), Int8(), v8::internal::MachineType::ProtectedPointer(), ProtectedPointer(), v8::internal::MachineType::SandboxedPointer(), SandboxedPointer(), v8::internal::MachineType::Simd128(), Simd128(), v8::internal::MachineType::Simd256(), Simd256(), v8::internal::MachineType::TaggedPointer(), TaggedPointer(), v8::internal::MachineType::TaggedSigned(), TaggedSigned(), v8::internal::MachineType::Uint16(), Uint16(), v8::internal::MachineType::Uint32(), Uint32(), v8::internal::MachineType::Uint64(), Uint64(), v8::internal::MachineType::Uint8(), Uint8(), UncompressedTaggedPointer(), and UncompressedTaggedSigned().
Referenced by v8::internal::compiler::AtomicOpType(), v8::internal::compiler::turboshaft::SupportedOperations::IsUnalignedLoadSupported(), v8::internal::compiler::turboshaft::SupportedOperations::IsUnalignedStoreSupported(), v8::internal::compiler::turboshaft::LoadOp::machine_type(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::TraceMemoryOperation().
ToRegisterRepresentation()
RegisterRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::ToRegisterRepresentation () const [inline]
Definition at line 688 of file representations.h.
                                                          {
    switch (*this) {
      case Int8():
      case Uint8():
      case Int16():
      case Uint16():
      case Int32():
      case Uint32():
        return RegisterRepresentation::Word32();
      case Int64():
      case Uint64():
        return RegisterRepresentation::Word64();
      case Float16():
      case Float32():
        return RegisterRepresentation::Float32();
      case Float64():
        return RegisterRepresentation::Float64();
      case AnyTagged():
      case TaggedPointer():
      case TaggedSigned():
      case AnyUncompressedTagged():
      case UncompressedTaggedPointer():
      case UncompressedTaggedSigned():
      case IndirectPointer():
      case ProtectedPointer():
        return RegisterRepresentation::Tagged();
      case SandboxedPointer():
        return RegisterRepresentation::Word64();
      case Simd128():
        return RegisterRepresentation::Simd128();
      case Simd256():
        return RegisterRepresentation::Simd256();
    }
  }
References AnyTagged(), AnyUncompressedTagged(), Float16(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), Float64(), IndirectPointer(), Int16(), Int32(), Int64(), Int8(), ProtectedPointer(), SandboxedPointer(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd128(), Simd128(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd256(), Simd256(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), TaggedPointer(), TaggedSigned(), Uint16(), Uint32(), Uint64(), Uint8(), UncompressedTaggedPointer(), UncompressedTaggedSigned(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Referenced by v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ArrayAtomicRMW(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsLoadMem(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Load(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructAtomicRMW(), ToRegisterRepresentationForStore(), v8::internal::compiler::turboshaft::LoadOp::Validate(), and v8::internal::compiler::InstructionSelector::VisitNode().
ToRegisterRepresentationForStore()
RegisterRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::ToRegisterRepresentationForStore () const [inline]
Definition at line 748 of file representations.h.
                                                                  {
    RegisterRepresentation result = ToRegisterRepresentation();
#ifdef V8_COMPRESS_POINTERS
    if (result == RegisterRepresentation::Tagged()) {
      result = RegisterRepresentation::Compressed();
    }
#endif
    return result;
  }
References v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), v8::base::internal::result, v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), and ToRegisterRepresentation().
Referenced by v8::internal::compiler::turboshaft::StoreOp::inputs_rep().
Uint16()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16 () [inline], [static], [constexpr]
Definition at line 560 of file representations.h.
                                                 {
    return MemoryRepresentation(Enum::kUint16);
  }
References kUint16, and MemoryRepresentation().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsLoadMem(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::BytecodeOperand(), v8::internal::StringBuiltinsReducer< Next >::CopyStringCharacters(), v8::internal::compiler::turboshaft::StringView::Dereference(), FromMachineRepresentation(), FromMachineType(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetCodeUnitImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineMemCopy(), IsCompressibleTagged(), IsSigned(), v8::internal::wasm::WasmWrapperTSGraphBuilder::LoadInstanceType(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadMem(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RepresentationFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreLane(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringCodePointAt(), ToMachineType(), ToRegisterRepresentation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::VisitStoreCommon(), v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation(), and v8::internal::compiler::InstructionSelector::VisitWord64AtomicBinaryOperation().
Uint32()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32 () [inline], [static], [constexpr]
Definition at line 566 of file representations.h.
                                                 {
    return MemoryRepresentation(Enum::kUint32);
  }
References kUint32, and MemoryRepresentation().
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::AdaptFastCallArgument(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsLoadMem(), v8::internal::wasm::WasmGraphBuilderBase::BuildFunctionTargetAndImplicitArg(), v8::internal::wasm::WasmGraphBuilderBase::BuildImportedFunctionTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildLoadCallTargetFromExportedFunctionData(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::BytecodeOperand(), FromMachineRepresentation(), FromMachineType(), FromRegisterRepresentation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineMemCopy(), IsCompressibleTagged(), IsSigned(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::LoadCounterValue(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadExternalPointerFromObject(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadTrustedPointerField(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RepresentationFor(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::StoreCounterValue(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreLane(), ToMachineType(), ToRegisterRepresentation(), UintPtr(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::VisitStoreCommon(), v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation(), and v8::internal::compiler::InstructionSelector::VisitWord64AtomicBinaryOperation().
Uint64()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64 () [inline], [static], [constexpr]
Definition at line 572 of file representations.h.
                                                 {
    return MemoryRepresentation(Enum::kUint64);
  }
References kUint64, and MemoryRepresentation().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicOp(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::AtomicRMW(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::DecodeExternalPointer(), FromMachineRepresentation(), FromMachineType(), FromRegisterRepresentation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineMemCopy(), IsCompressibleTagged(), IsSigned(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Load(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RepresentationFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Store(), v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::Store(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreLane(), ToMachineType(), ToRegisterRepresentation(), UintPtr(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::VisitStoreCommon(), and v8::internal::compiler::InstructionSelector::VisitWord64AtomicBinaryOperation().
Uint8()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8 () [inline], [static], [constexpr]
Definition at line 554 of file representations.h.
                                                {
    return MemoryRepresentation(Enum::kUint8);
  }
References kUint8, and MemoryRepresentation().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsLoadMem(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchBackFromCentralStack(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStack(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStackIfNeeded(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::BytecodeOperand(), v8::internal::StringBuiltinsReducer< Next >::CopyStringCharacters(), v8::internal::compiler::turboshaft::StringView::Dereference(), FromMachineRepresentation(), FromMachineType(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetCodeUnitImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetMemoryAccessKind(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineMemCopy(), IsCompressibleTagged(), IsSigned(), v8::internal::compiler::turboshaft::StackCheckLoweringReducer< Next >::JSStackCheck(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::LoadBytecode(), v8::internal::compiler::turboshaft::LoadOp::Kind::MaybeUnaligned(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RepresentationFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), v8::internal::wasm::TurboshaftGraphBuildingInterface::SetDataViewOpForErrorMessage(), SizeInBytesLog2(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreLane(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringCodePointAt(), ToMachineType(), ToRegisterRepresentation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TraceMemoryOperation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::VisitStoreCommon(), v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation(), and v8::internal::compiler::InstructionSelector::VisitWord64AtomicBinaryOperation().
UintPtr()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr () [inline], [static], [constexpr]
Definition at line 575 of file representations.h.
                                                  {
    if constexpr (Is64()) {
      return Uint64();
    } else {
      return Uint32();
    }
  }
References v8::internal::Is64(), Uint32(), and Uint64().
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::AdaptFastCallArgument(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AdaptLocalArgument(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Allocate(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ArgumentsLength(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildLoadCallTargetFromExportedFunctionData(), v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlag(), v8::internal::wasm::WasmGraphBuilderBase::BuildSetNewStackLimit(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchBackFromCentralStack(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStack(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStackIfNeeded(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::Call(), v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::DecodeExternalPointer(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::DispatchToBytecode(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::GetLimitAddress(), v8::internal::compiler::turboshaft::StackCheckLoweringReducer< Next >::JSStackCheck(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadExternalPointerFromObject(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::LoadMemSize(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::LoadMemStart(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadPageFlags(), v8::internal::compiler::turboshaft::LoadRootHelper(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadTrustedPointerField(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LowerGlobalSetOrGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemSize(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemStart(), v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RootConstant(), v8::internal::wasm::WasmWrapperTSGraphBuilder::SafeLoad(), v8::internal::wasm::WasmWrapperTSGraphBuilder::SafeStore(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TraceMemoryOperation(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::WasmStackCheck(), v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi(), and v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::WrapFastCall().
UncompressedTaggedPointer()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedPointer () [inline], [static], [constexpr]
Definition at line 603 of file representations.h.
                                                                    {
    return MemoryRepresentation(Enum::kUncompressedTaggedPointer);
  }
References kUncompressedTaggedPointer, and MemoryRepresentation().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), IsSigned(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreInStackSlot(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringFromSingleCharCode(), ToMachineType(), ToRegisterRepresentation(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), and v8::internal::compiler::VisitStoreCommon().
UncompressedTaggedSigned()
static constexpr MemoryRepresentation v8::internal::compiler::turboshaft::MemoryRepresentation::UncompressedTaggedSigned () [inline], [static], [constexpr]
Definition at line 606 of file representations.h.
                                                                   {
    return MemoryRepresentation(Enum::kUncompressedTaggedSigned);
  }
References kUncompressedTaggedSigned, and MemoryRepresentation().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetLoadOpcode(), v8::internal::compiler::GetLoadOpcodeAndImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::GetStoreOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetStoreOpcodeAndImmediate(), IsCompressibleTagged(), IsSigned(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), SizeInBytesLog2(), ToMachineType(), ToRegisterRepresentation(), v8::internal::compiler::VisitGeneralStore(), and v8::internal::compiler::VisitStoreCommon().
value()
constexpr Enum v8::internal::compiler::turboshaft::MemoryRepresentation::value () const [inline], [constexpr]
Definition at line 545 of file representations.h.
                               {
    DCHECK(is_valid());
    return value_;
  }
References v8::internal::DCHECK(), is_valid(), and value_.
Referenced by v8::internal::compiler::turboshaft::hash_value(), operator Enum(), v8::internal::compiler::turboshaft::operator!=(), v8::internal::compiler::turboshaft::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
Member Data Documentation
kInvalid
constexpr Enum v8::internal::compiler::turboshaft::MemoryRepresentation::kInvalid = static_cast<Enum>(-1) [static], [constexpr], [private]
Definition at line 935 of file representations.h.
Referenced by is_valid().
value_
Enum v8::internal::compiler::turboshaft::MemoryRepresentation::value_ [private]
Definition at line 933 of file representations.h.
Referenced by is_valid(), and value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/representations.h