v8::internal::ExperimentalRegExpCompiler Class Reference
#include <experimental-compiler.h>
Static Public Member Functions
static bool CanBeHandled (RegExpTree *tree, RegExpFlags flags, int capture_count)
static ZoneList< RegExpInstruction > Compile (RegExpTree *tree, RegExpFlags flags, Zone *zone)
Detailed Description
Definition at line 16 of file experimental-compiler.h.
Member Function Documentation
CanBeHandled()
bool v8::internal::ExperimentalRegExpCompiler::CanBeHandled (RegExpTree * tree, RegExpFlags flags, int capture_count) [static]
Definition at line 221 of file experimental-compiler.cc.
                                                                 {
  return CanBeHandledVisitor::Check(tree, flags, capture_count);
}
References v8::internal::flags.
Referenced by v8::internal::ExperimentalRegExp::CanBeHandled().
Compile()
ZoneList< RegExpInstruction > v8::internal::ExperimentalRegExpCompiler::Compile (RegExpTree * tree, RegExpFlags flags, Zone * zone) [static]
Definition at line 1227 of file experimental-compiler.cc.
                                                     {
  return CompileVisitor::Compile(tree, flags, zone);
}
References v8::anonymous_namespace{d8.cc}::Compile(), and v8::internal::flags.
Referenced by v8::internal::anonymous_namespace{experimental.cc}::CompileImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/experimental/experimental-compiler.h
/mnt/V8SourceCode/src/regexp/experimental/experimental-compiler.cc