v8::internal::detail::AsyncWaiterQueueNode< T > Class Template Reference
Public Member Functions
TaskRunner * task_runner ()
Local< v8::Context > GetNativeContext ()
Handle< JSPromise > GetInternalWaitingPromise ()
bool IsEmpty () const
Handle< T > GetSynchronizationPrimitive ()
Handle< JSPromise > GetUnlockedPromise ()
void Notify () override
bool IsSameIsolateForAsyncCleanup (Isolate *isolate) override
void CleanupMatchingAsyncWaiters (const DequeueMatcher &matcher) override
Static Public Member Functions
static AsyncWaiterQueueNode< T > * NewAsyncWaiterStoredInIsolate (Isolate *requester, DirectHandle< T > synchronization_primitive, Handle< JSPromise > internal_waiting_promise, MaybeHandle< JSPromise > unlocked_promise={})
static AsyncWaiterQueueNode< T > * NewLockedAsyncWaiterStoredInIsolate (Isolate *requester, DirectHandle< T > synchronization_primitive)
static void RemoveFromAsyncWaiterQueueList (AsyncWaiterQueueNode< T > *node)
Private Member Functions
AsyncWaiterQueueNode (Isolate *requester, DirectHandle< T > synchronization_primitive)
AsyncWaiterQueueNode (Isolate *requester, DirectHandle< T > synchronization_primitive, DirectHandle< JSPromise > internal_waiting_promise, MaybeDirectHandle< JSPromise > unlocked_promise)
void SetReadyForAsyncCleanup () override
Private Attributes
friend JSAtomicsMutex
friend JSAtomicsCondition
friend AsyncWaiterNotifyTask< T >
friend AsyncWaiterTimeoutTask< T >
std::shared_ptr< TaskRunner > task_runner_
CancelableTaskManager::Id timeout_task_id_
CancelableTaskManager::Id notify_task_id_
bool ready_for_async_cleanup_ = false
Global< v8::Context > native_context_
Global< v8::Promise > internal_waiting_promise_
Global< v8::Object > synchronization_primitive_
Global< v8::Promise > unlocked_promise_
Additional Inherited Members
Detailed Description
template<typename T>
class v8::internal::detail::AsyncWaiterQueueNode< T >
Definition at line 270 of file js-atomics-synchronization.cc.
Constructor & Destructor Documentation
AsyncWaiterQueueNode() [1/2]
template<typename T >
v8::internal::detail::AsyncWaiterQueueNode< T >::AsyncWaiterQueueNode (Isolate * requester, DirectHandle< T > synchronization_primitive) [inline], [explicit], [private]
Definition at line 359 of file js-atomics-synchronization.cc.
      : WaiterQueueNode(requester),
        notify_task_id_(CancelableTaskManager::kInvalidTaskId) {
    native_context_ =
        GetWeakGlobal(requester, Utils::ToLocal(requester->native_context()));
    synchronization_primitive_ = GetWeakGlobal(
        requester, Utils::ToLocal(Cast<JSObject>(synchronization_primitive)));
  }
References v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::GetWeakGlobal(), and v8::internal::Isolate::native_context().
AsyncWaiterQueueNode() [2/2]
template<typename T >
v8::internal::detail::AsyncWaiterQueueNode< T >::AsyncWaiterQueueNode (Isolate * requester, DirectHandle< T > synchronization_primitive, DirectHandle< JSPromise > internal_waiting_promise, MaybeDirectHandle< JSPromise > unlocked_promise) [inline], [explicit], [private]
Definition at line 369 of file js-atomics-synchronization.cc.
      : WaiterQueueNode(requester),
        notify_task_id_(CancelableTaskManager::kInvalidTaskId) {
    v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(requester);
    task_runner_ =
        V8::GetCurrentPlatform()->GetForegroundTaskRunner(v8_isolate);
    timeout_task_id_ = CancelableTaskManager::kInvalidTaskId;
    native_context_ =
        GetWeakGlobal(requester, Utils::ToLocal(requester->native_context()));
    synchronization_primitive_ = GetWeakGlobal(
        requester, Utils::ToLocal(Cast<JSObject>(synchronization_primitive)));
    internal_waiting_promise_ = GetWeakGlobal(
        requester, Utils::PromiseToLocal(internal_waiting_promise));
    if (!unlocked_promise.is_null()) {
      DCHECK(IsJSAtomicsMutex(*synchronization_primitive));
      unlocked_promise_ = GetWeakGlobal(
          requester, Utils::PromiseToLocal(unlocked_promise.ToHandleChecked()));
    }
  }
References v8::internal::DCHECK(), v8::internal::V8::GetCurrentPlatform(), v8::Platform::GetForegroundTaskRunner(), v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::GetWeakGlobal(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::CancelableTaskManager::kInvalidTaskId, v8::internal::Isolate::native_context(), and v8::internal::MaybeDirectHandle< T >::ToHandleChecked().
Member Function Documentation
CleanupMatchingAsyncWaiters()
template<typename T >
void v8::internal::detail::AsyncWaiterQueueNode< T >::CleanupMatchingAsyncWaiters (const DequeueMatcher & matcher) [inline], [override], [virtual]
Implements v8::internal::detail::WaiterQueueNode.
Definition at line 341 of file js-atomics-synchronization.cc.
                                                                           {
    T::CleanupMatchingAsyncWaiters(requester_, this, matcher);
  }
GetInternalWaitingPromise()
template<typename T >
Handle<JSPromise> v8::internal::detail::AsyncWaiterQueueNode< T >::GetInternalWaitingPromise () [inline]
Definition at line 304 of file js-atomics-synchronization.cc.
                                                {
    v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(requester_);
    Handle<JSPromise> internal_waiting_promise =
        Utils::OpenHandle(*internal_waiting_promise_.Get(v8_isolate));
    return internal_waiting_promise;
  }
References v8::Utils::OpenHandle().
Referenced by v8::internal::JSAtomicsMutex::HandleAsyncNotify(), v8::internal::JSAtomicsCondition::HandleAsyncNotify(), and v8::internal::JSAtomicsMutex::HandleAsyncTimeout().
GetNativeContext()
template<typename T >
Local<v8::Context> v8::internal::detail::AsyncWaiterQueueNode< T >::GetNativeContext () [inline]
Definition at line 299 of file js-atomics-synchronization.cc.
                                      {
    v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(requester_);
    return native_context_.Get(v8_isolate);
  }
Referenced by v8::internal::JSAtomicsMutex::HandleAsyncNotify(), v8::internal::JSAtomicsCondition::HandleAsyncNotify(), and v8::internal::JSAtomicsMutex::HandleAsyncTimeout().
GetSynchronizationPrimitive()
template<typename T >
Handle<T> v8::internal::detail::AsyncWaiterQueueNode< T >::GetSynchronizationPrimitive () [inline]
Definition at line 313 of file js-atomics-synchronization.cc.
                                          {
    v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(requester_);
    Handle<T> synchronization_primitive =
        Cast<T>(Utils::OpenHandle(*synchronization_primitive_.Get(v8_isolate)));
    return synchronization_primitive;
  }
References v8::Utils::OpenHandle().
Referenced by v8::internal::JSAtomicsMutex::HandleAsyncNotify(), v8::internal::JSAtomicsMutex::HandleAsyncTimeout(), and v8::internal::JSAtomicsCondition::HandleAsyncTimeout().
GetUnlockedPromise()
template<typename T >
Handle<JSPromise> v8::internal::detail::AsyncWaiterQueueNode< T >::GetUnlockedPromise () [inline]
Definition at line 320 of file js-atomics-synchronization.cc.
                                         {
    v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(requester_);
    Handle<JSPromise> unlocked_promise =
        Cast<JSPromise>(Utils::OpenHandle(*unlocked_promise_.Get(v8_isolate)));
    return unlocked_promise;
  }
References v8::Utils::OpenHandle().
Referenced by v8::internal::JSAtomicsMutex::HandleAsyncTimeout().
IsEmpty()
template<typename T >
bool v8::internal::detail::AsyncWaiterQueueNode< T >::IsEmpty () const [inline]
Definition at line 311 of file js-atomics-synchronization.cc.
{ return synchronization_primitive_.IsEmpty(); }
IsSameIsolateForAsyncCleanup()
template<typename T >
bool v8::internal::detail::AsyncWaiterQueueNode< T >::IsSameIsolateForAsyncCleanup (Isolate * isolate) [inline], [override], [virtual]
Implements v8::internal::detail::WaiterQueueNode.
Definition at line 337 of file js-atomics-synchronization.cc.
                                                               {
    return requester_ == isolate;
  }
NewAsyncWaiterStoredInIsolate()
template<typename T >
static AsyncWaiterQueueNode<T>* v8::internal::detail::AsyncWaiterQueueNode< T >::NewAsyncWaiterStoredInIsolate (Isolate * requester, DirectHandle< T > synchronization_primitive, Handle< JSPromise > internal_waiting_promise, MaybeHandle< JSPromise > unlocked_promise = {}) [inline], [static]
Definition at line 272 of file js-atomics-synchronization.cc.
                                                {}) {
    auto waiter =
        std::unique_ptr<AsyncWaiterQueueNode<T>>(new AsyncWaiterQueueNode<T>(
            requester, synchronization_primitive, internal_waiting_promise,
            unlocked_promise));
    AsyncWaiterQueueNode<T>* raw_waiter = waiter.get();
    requester->async_waiter_queue_nodes().push_back(std::move(waiter));
    return raw_waiter;
  }
Referenced by v8::internal::JSAtomicsMutex::LockAsyncSlowPath(), and v8::internal::JSAtomicsCondition::WaitAsync().
NewLockedAsyncWaiterStoredInIsolate()
template<typename T >
static AsyncWaiterQueueNode<T>* v8::internal::detail::AsyncWaiterQueueNode< T >::NewLockedAsyncWaiterStoredInIsolate (Isolate * requester, DirectHandle< T > synchronization_primitive) [inline], [static]
Definition at line 287 of file js-atomics-synchronization.cc.
                                                                     {
    DCHECK(IsJSAtomicsMutex(*synchronization_primitive));
    auto waiter = std::unique_ptr<AsyncWaiterQueueNode<T>>(
        new AsyncWaiterQueueNode<T>(requester, synchronization_primitive));
    AsyncWaiterQueueNode<T>* raw_waiter = waiter.get();
    requester->async_waiter_queue_nodes().push_back(std::move(waiter));
    return raw_waiter;
  }
References v8::internal::Isolate::async_waiter_queue_nodes(), and v8::internal::DCHECK().
Referenced by v8::internal::JSAtomicsMutex::LockOrEnqueuePromise().
Notify()
template<typename T >
void v8::internal::detail::AsyncWaiterQueueNode< T >::Notify () [inline], [override], [virtual]
Implements v8::internal::detail::WaiterQueueNode.
Definition at line 327 of file js-atomics-synchronization.cc.
                         {
    SetNotInListForVerification();
    CancelableTaskManager* task_manager = requester_->cancelable_task_manager();
    if (task_manager->canceled()) return;
    auto notify_task =
        std::make_unique<AsyncWaiterNotifyTask<T>>(task_manager, this);
    notify_task_id_ = notify_task->id();
    task_runner_->PostNonNestableTask(std::move(notify_task));
  }
References v8::internal::CancelableTaskManager::canceled().
RemoveFromAsyncWaiterQueueList()
template<typename T >
static void v8::internal::detail::AsyncWaiterQueueNode< T >::RemoveFromAsyncWaiterQueueList (AsyncWaiterQueueNode< T > * node) [inline], [static]
Definition at line 348 of file js-atomics-synchronization.cc.
                                                                            {
    node->requester_->async_waiter_queue_nodes().remove_if(
        [=](std::unique_ptr<WaiterQueueNode>& n) { return n.get() == node; });
  }
References v8::internal::Isolate::async_waiter_queue_nodes(), and v8::internal::detail::WaiterQueueNode::requester_.
Referenced by v8::internal::JSAtomicsMutex::HandleAsyncNotify(), v8::internal::JSAtomicsCondition::HandleAsyncNotify(), v8::internal::JSAtomicsMutex::HandleAsyncTimeout(), v8::internal::JSAtomicsCondition::HandleAsyncTimeout(), and v8::internal::JSAtomicsMutex::UnlockAsyncLockedMutex().
SetReadyForAsyncCleanup()
template<typename T >
void v8::internal::detail::AsyncWaiterQueueNode< T >::SetReadyForAsyncCleanup () [inline], [override], [private], [virtual]
Implements v8::internal::detail::WaiterQueueNode.
Definition at line 392 of file js-atomics-synchronization.cc.
{ ready_for_async_cleanup_ = true; }
task_runner()
template<typename T >
TaskRunner* v8::internal::detail::AsyncWaiterQueueNode< T >::task_runner () [inline]
Definition at line 297 of file js-atomics-synchronization.cc.
{ return task_runner_.get(); }
Referenced by v8::internal::JSAtomicsMutex::LockAsyncSlowPath(), and v8::internal::JSAtomicsCondition::WaitAsync().
Member Data Documentation
AsyncWaiterNotifyTask< T >
template<typename T >
friend v8::internal::detail::AsyncWaiterQueueNode< T >::AsyncWaiterNotifyTask< T > [private]
Definition at line 356 of file js-atomics-synchronization.cc.
AsyncWaiterTimeoutTask< T >
template<typename T >
friend v8::internal::detail::AsyncWaiterQueueNode< T >::AsyncWaiterTimeoutTask< T > [private]
Definition at line 357 of file js-atomics-synchronization.cc.
internal_waiting_promise_
template<typename T >
Global<v8::Promise> v8::internal::detail::AsyncWaiterQueueNode< T >::internal_waiting_promise_ [private]
Definition at line 404 of file js-atomics-synchronization.cc.
JSAtomicsCondition
template<typename T >
friend v8::internal::detail::AsyncWaiterQueueNode< T >::JSAtomicsCondition [private]
Definition at line 355 of file js-atomics-synchronization.cc.
JSAtomicsMutex
template<typename T >
friend v8::internal::detail::AsyncWaiterQueueNode< T >::JSAtomicsMutex [private]
Definition at line 354 of file js-atomics-synchronization.cc.
native_context_
template<typename T >
Global<v8::Context> v8::internal::detail::AsyncWaiterQueueNode< T >::native_context_ [private]
Definition at line 401 of file js-atomics-synchronization.cc.
Referenced by v8::internal::JSAtomicsMutex::HandleAsyncNotify(), v8::internal::JSAtomicsCondition::HandleAsyncNotify(), v8::internal::JSAtomicsMutex::HandleAsyncTimeout(), and v8::internal::JSAtomicsCondition::HandleAsyncTimeout().
notify_task_id_
template<typename T >
CancelableTaskManager::Id v8::internal::detail::AsyncWaiterQueueNode< T >::notify_task_id_ [private]
Definition at line 396 of file js-atomics-synchronization.cc.
Referenced by v8::internal::JSAtomicsMutex::HandleAsyncTimeout(), and v8::internal::JSAtomicsCondition::HandleAsyncTimeout().
ready_for_async_cleanup_
template<typename T >
bool v8::internal::detail::AsyncWaiterQueueNode< T >::ready_for_async_cleanup_ = false [private]
Definition at line 397 of file js-atomics-synchronization.cc.
synchronization_primitive_
template<typename T >
Global<v8::Object> v8::internal::detail::AsyncWaiterQueueNode< T >::synchronization_primitive_ [private]
Definition at line 405 of file js-atomics-synchronization.cc.
Referenced by v8::internal::JSAtomicsMutex::HandleAsyncNotify().
task_runner_
template<typename T >
std::shared_ptr<TaskRunner> v8::internal::detail::AsyncWaiterQueueNode< T >::task_runner_ [private]
Definition at line 394 of file js-atomics-synchronization.cc.
timeout_task_id_
template<typename T >
CancelableTaskManager::Id v8::internal::detail::AsyncWaiterQueueNode< T >::timeout_task_id_ [private]
Definition at line 395 of file js-atomics-synchronization.cc.
Referenced by v8::internal::JSAtomicsMutex::HandleAsyncNotify(), v8::internal::JSAtomicsCondition::HandleAsyncNotify(), v8::internal::JSAtomicsCondition::HandleAsyncTimeout(), v8::internal::JSAtomicsMutex::LockAsyncSlowPath(), and v8::internal::JSAtomicsCondition::WaitAsync().
unlocked_promise_
template<typename T >
Global<v8::Promise> v8::internal::detail::AsyncWaiterQueueNode< T >::unlocked_promise_ [private]
Definition at line 408 of file js-atomics-synchronization.cc.
Referenced by v8::internal::JSAtomicsMutex::HandleAsyncNotify().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/js-atomics-synchronization.cc