v8::internal::AssemblerRISCVZfh Class Reference
#include <extension-riscv-zfh.h>
Public Member Functions
void flh (FPURegister rd, Register rs1, int16_t imm12)
void fsh (FPURegister source, Register base, int16_t imm12)
void fadd_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm=RNE)
void fsub_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm=RNE)
void fmul_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm=RNE)
void fdiv_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm=RNE)
void fmin_h (FPURegister rd, FPURegister rs1, FPURegister rs2)
void fmax_h (FPURegister rd, FPURegister rs1, FPURegister rs2)
void fsqrt_h (FPURegister rd, FPURegister rs1, FPURoundingMode frm=RNE)
void fmadd_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm=RNE)
void fmsub_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm=RNE)
void fnmsub_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm=RNE)
void fnmadd_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm=RNE)
void fcvt_h_w (FPURegister rd, Register rs1, FPURoundingMode frm=RNE)
void fcvt_h_wu (FPURegister rd, Register rs1, FPURoundingMode frm=RNE)
void fcvt_w_h (Register rd, FPURegister rs1, FPURoundingMode frm=RNE)
void fcvt_wu_h (Register rd, FPURegister rs1, FPURoundingMode frm=RNE)
void fcvt_h_s (FPURegister rd, FPURegister rs1, FPURoundingMode frm=RNE)
void fcvt_s_h (FPURegister rd, FPURegister rs1, FPURoundingMode frm=RNE)
void fcvt_h_d (FPURegister rd, FPURegister rs1, FPURoundingMode frm=RNE)
void fcvt_d_h (FPURegister rd, FPURegister rs1, FPURoundingMode frm=RNE)
void fsgnj_h (FPURegister rd, FPURegister rs1, FPURegister rs2)
void fsgnjn_h (FPURegister rd, FPURegister rs1, FPURegister rs2)
void fsgnjx_h (FPURegister rd, FPURegister rs1, FPURegister rs2)
void fmv_h_x (FPURegister rd, Register rs1)
void fmv_x_h (Register rd, FPURegister rs1)
void feq_h (Register rd, FPURegister rs1, FPURegister rs2)
void flt_h (Register rd, FPURegister rs1, FPURegister rs2)
void fle_h (Register rd, FPURegister rs1, FPURegister rs2)
void fclass_h (Register rd, FPURegister rs1)
Additional Inherited Members
Detailed Description
Definition at line 15 of file extension-riscv-zfh.h.
Member Function Documentation
fadd_h()
void v8::internal::AssemblerRISCVZfh::fadd_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm = RNE)
Definition at line 43 of file extension-riscv-zfh.cc.
                                                    {
  GenInstrALUFP_rr(0b0000010, frm, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fclass_h()
void v8::internal::AssemblerRISCVZfh::fclass_h (Register rd, FPURegister rs1)
Definition at line 105 of file extension-riscv-zfh.cc.
                                                             {
  GenInstrALUFP_rr(0b1110010, 0b001, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fcvt_d_h()
void v8::internal::AssemblerRISCVZfh::fcvt_d_h (FPURegister rd, FPURegister rs1, FPURoundingMode frm = RNE)
Definition at line 141 of file extension-riscv-zfh.cc.
                                                      {
  GenInstrALUFP_rr(0b0100001, frm, rd, rs1, ToRegister(2));
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr(), and v8::internal::ToRegister().
fcvt_h_d()
void v8::internal::AssemblerRISCVZfh::fcvt_h_d (FPURegister rd, FPURegister rs1, FPURoundingMode frm = RNE)
Definition at line 137 of file extension-riscv-zfh.cc.
                                                      {
  GenInstrALUFP_rr(0b0100010, frm, rd, rs1, ToRegister(1));
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr(), and v8::internal::ToRegister().
fcvt_h_s()
void v8::internal::AssemblerRISCVZfh::fcvt_h_s (FPURegister rd, FPURegister rs1, FPURoundingMode frm = RNE)
Definition at line 146 of file extension-riscv-zfh.cc.
                                                      {
  GenInstrALUFP_rr(0b0100010, frm, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fcvt_h_w()
void v8::internal::AssemblerRISCVZfh::fcvt_h_w (FPURegister rd, Register rs1, FPURoundingMode frm = RNE)
Definition at line 109 of file extension-riscv-zfh.cc.
                                                      {
  GenInstrALUFP_rr(0b1101010, frm, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fcvt_h_wu()
void v8::internal::AssemblerRISCVZfh::fcvt_h_wu (FPURegister rd, Register rs1, FPURoundingMode frm = RNE)
Definition at line 114 of file extension-riscv-zfh.cc.
                                                       {
  GenInstrALUFP_rr(0b1101010, frm, rd, rs1, ToRegister(1));
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr(), and v8::internal::ToRegister().
fcvt_s_h()
void v8::internal::AssemblerRISCVZfh::fcvt_s_h (FPURegister rd, FPURegister rs1, FPURoundingMode frm = RNE)
Definition at line 150 of file extension-riscv-zfh.cc.
                                                      {
  GenInstrALUFP_rr(0b0100000, frm, rd, rs1, ToRegister(2));
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr(), and v8::internal::ToRegister().
fcvt_w_h()
void v8::internal::AssemblerRISCVZfh::fcvt_w_h (Register rd, FPURegister rs1, FPURoundingMode frm = RNE)
Definition at line 119 of file extension-riscv-zfh.cc.
                                                      {
  GenInstrALUFP_rr(0b1100010, frm, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fcvt_wu_h()
void v8::internal::AssemblerRISCVZfh::fcvt_wu_h (Register rd, FPURegister rs1, FPURoundingMode frm = RNE)
Definition at line 124 of file extension-riscv-zfh.cc.
                                                       {
  GenInstrALUFP_rr(0b1100010, frm, rd, rs1, ToRegister(1));
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr(), and v8::internal::ToRegister().
fdiv_h()
void v8::internal::AssemblerRISCVZfh::fdiv_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm = RNE)
Definition at line 58 of file extension-riscv-zfh.cc.
                                                    {
  GenInstrALUFP_rr(0b0001110, frm, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
feq_h()
void v8::internal::AssemblerRISCVZfh::feq_h (Register rd, FPURegister rs1, FPURegister rs2)
Definition at line 93 of file extension-riscv-zfh.cc.
                                                                           {
  GenInstrALUFP_rr(0b1010010, 0b010, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fle_h()
void v8::internal::AssemblerRISCVZfh::fle_h (Register rd, FPURegister rs1, FPURegister rs2)
Definition at line 101 of file extension-riscv-zfh.cc.
                                                                           {
  GenInstrALUFP_rr(0b1010010, 0b000, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
flh()
void v8::internal::AssemblerRISCVZfh::flh (FPURegister rd, Register rs1, int16_t imm12)
Definition at line 11 of file extension-riscv-zfh.cc.
                                                                       {
  GenInstrLoadFP_ri(0b001, rd, rs1, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrLoadFP_ri().
flt_h()
void v8::internal::AssemblerRISCVZfh::flt_h (Register rd, FPURegister rs1, FPURegister rs2)
Definition at line 97 of file extension-riscv-zfh.cc.
                                                                           {
  GenInstrALUFP_rr(0b1010010, 0b001, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fmadd_h()
void v8::internal::AssemblerRISCVZfh::fmadd_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm = RNE)
Definition at line 19 of file extension-riscv-zfh.cc.
                                                     {
  GenInstrR4(0b10, MADD, rd, rs1, rs2, rs3, frm);
}
References v8::internal::AssemblerRiscvBase::GenInstrR4(), and v8::internal::MADD.
fmax_h()
void v8::internal::AssemblerRISCVZfh::fmax_h (FPURegister rd, FPURegister rs1, FPURegister rs2)
Definition at line 88 of file extension-riscv-zfh.cc.
                                                {
  GenInstrALUFP_rr(0b0010110, 0b001, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fmin_h()
void v8::internal::AssemblerRISCVZfh::fmin_h (FPURegister rd, FPURegister rs1, FPURegister rs2)
Definition at line 83 of file extension-riscv-zfh.cc.
                                                {
  GenInstrALUFP_rr(0b0010110, 0b000, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fmsub_h()
void v8::internal::AssemblerRISCVZfh::fmsub_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm = RNE)
Definition at line 25 of file extension-riscv-zfh.cc.
                                                     {
  GenInstrR4(0b10, MSUB, rd, rs1, rs2, rs3, frm);
}
References v8::internal::AssemblerRiscvBase::GenInstrR4(), and v8::internal::MSUB.
fmul_h()
void v8::internal::AssemblerRISCVZfh::fmul_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm = RNE)
Definition at line 53 of file extension-riscv-zfh.cc.
                                                    {
  GenInstrALUFP_rr(0b0001010, frm, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fmv_h_x()
void v8::internal::AssemblerRISCVZfh::fmv_h_x (FPURegister rd, Register rs1)
Definition at line 129 of file extension-riscv-zfh.cc.
                                                            {
  GenInstrALUFP_rr(0b1111010, 0b000, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fmv_x_h()
void v8::internal::AssemblerRISCVZfh::fmv_x_h (Register rd, FPURegister rs1)
Definition at line 133 of file extension-riscv-zfh.cc.
                                                            {
  GenInstrALUFP_rr(0b1110010, 0b000, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fnmadd_h()
void v8::internal::AssemblerRISCVZfh::fnmadd_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm = RNE)
Definition at line 37 of file extension-riscv-zfh.cc.
                                                      {
  GenInstrR4(0b10, NMADD, rd, rs1, rs2, rs3, frm);
}
References v8::internal::AssemblerRiscvBase::GenInstrR4(), and v8::internal::NMADD.
fnmsub_h()
void v8::internal::AssemblerRISCVZfh::fnmsub_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm = RNE)
Definition at line 31 of file extension-riscv-zfh.cc.
                                                      {
  GenInstrR4(0b10, NMSUB, rd, rs1, rs2, rs3, frm);
}
References v8::internal::AssemblerRiscvBase::GenInstrR4(), and v8::internal::NMSUB.
fsgnj_h()
void v8::internal::AssemblerRISCVZfh::fsgnj_h (FPURegister rd, FPURegister rs1, FPURegister rs2)
Definition at line 68 of file extension-riscv-zfh.cc.
                                                 {
  GenInstrALUFP_rr(0b0010010, 0b000, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fsgnjn_h()
void v8::internal::AssemblerRISCVZfh::fsgnjn_h (FPURegister rd, FPURegister rs1, FPURegister rs2)
Definition at line 73 of file extension-riscv-zfh.cc.
                                                  {
  GenInstrALUFP_rr(0b0010010, 0b001, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fsgnjx_h()
void v8::internal::AssemblerRISCVZfh::fsgnjx_h (FPURegister rd, FPURegister rs1, FPURegister rs2)
Definition at line 78 of file extension-riscv-zfh.cc.
                                                  {
  GenInstrALUFP_rr(0b0010010, 0b010, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fsh()
void v8::internal::AssemblerRISCVZfh::fsh (FPURegister source, Register base, int16_t imm12)
Definition at line 15 of file extension-riscv-zfh.cc.
                                                                            {
  GenInstrStoreFP_rri(0b001, base, source, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrStoreFP_rri().
fsqrt_h()
void v8::internal::AssemblerRISCVZfh::fsqrt_h (FPURegister rd, FPURegister rs1, FPURoundingMode frm = RNE)
Definition at line 63 of file extension-riscv-zfh.cc.
                                                     {
  GenInstrALUFP_rr(0b0101110, frm, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fsub_h()
void v8::internal::AssemblerRISCVZfh::fsub_h (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm = RNE)
Definition at line 48 of file extension-riscv-zfh.cc.
                                                    {
  GenInstrALUFP_rr(0b0000110, frm, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-zfh.h
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-zfh.cc