v8::internal::torque::ControlFlowGraph Class Reference
#include <cfg.h>
Public Member Functions
ControlFlowGraph (Stack< const Type * > input_types)
Block * NewBlock (std::optional< Stack< const Type * >> input_types, bool is_deferred)
void PlaceBlock (Block *block)
template<typename UnaryPredicate >
void UnplaceBlockIf (UnaryPredicate &&predicate)
Block * start () const
std::optional< Block * > end () const
void set_end (Block *end)
void SetReturnType (TypeVector t)
const std::vector< Block * > & blocks () const
size_t NumberOfBlockIds () const
std::size_t ParameterCount () const
Private Attributes
std::list< Block > blocks_
Block * start_
std::vector< Block * > placed_blocks_
std::optional< Block * > end_
std::optional< TypeVector > return_type_
size_t next_block_id_ = 0
Detailed Description
Definition at line 95 of file cfg.h.
Constructor & Destructor Documentation
ControlFlowGraph()
v8::internal::torque::ControlFlowGraph::ControlFlowGraph (Stack< const Type * > input_types) [inline], [explicit]
Definition at line 97 of file cfg.h.
                                                            {
    start_ = NewBlock(std::move(input_types), false);
    PlaceBlock(start_);
  }
References NewBlock(), PlaceBlock(), and start_.
Member Function Documentation
blocks()
const std::vector<Block*>& v8::internal::torque::ControlFlowGraph::blocks () const [inline]
Definition at line 132 of file cfg.h.
{ return placed_blocks_; }
References placed_blocks_.
Referenced by v8::internal::torque::CfgAssembler::CfgIsComplete(), v8::internal::torque::CfgAssembler::ComputeInputDefinitions(), v8::internal::torque::CountBlockPredecessors(), v8::internal::torque::CCGenerator::EmitGraph(), v8::internal::torque::CSAGenerator::EmitGraph(), and v8::internal::torque::CfgAssembler::OptimizeCfg().
end()
std::optional<Block*> v8::internal::torque::ControlFlowGraph::end () const [inline]
Definition at line 116 of file cfg.h.
{ return end_; }
References end_.
Referenced by v8::internal::torque::CCGenerator::EmitGraph(), v8::internal::torque::CSAGenerator::EmitGraph(), v8::internal::torque::CfgAssembler::OptimizeCfg(), and set_end().
NewBlock()
Block* v8::internal::torque::ControlFlowGraph::NewBlock (std::optional< Stack< const Type * >> input_types, bool is_deferred) [inline]
Definition at line 102 of file cfg.h.
                                    {
    blocks_.emplace_back(this, next_block_id_++, std::move(input_types),
                         is_deferred);
    return &blocks_.back();
  }
References blocks_, and next_block_id_.
Referenced by ControlFlowGraph(), and v8::internal::torque::CfgAssembler::NewBlock().
NumberOfBlockIds()
size_t v8::internal::torque::ControlFlowGraph::NumberOfBlockIds () const [inline]
Definition at line 133 of file cfg.h.
{ return next_block_id_; }
References next_block_id_.
Referenced by v8::internal::torque::CountBlockPredecessors().
ParameterCount()
std::size_t v8::internal::torque::ControlFlowGraph::ParameterCount () const [inline]
Definition at line 134 of file cfg.h.
                                   {
    return start_ ? start_->InputTypes().Size() : 0;
  }
References v8::internal::torque::Block::InputTypes(), and start_.
Referenced by v8::internal::torque::CfgAssembler::ComputeInputDefinitions().
PlaceBlock()
void v8::internal::torque::ControlFlowGraph::PlaceBlock (Block * block) [inline]
Definition at line 108 of file cfg.h.
{ placed_blocks_.push_back(block); }
References placed_blocks_.
Referenced by v8::internal::torque::CfgAssembler::Bind(), v8::internal::torque::CfgAssemblerScopedTemporaryBlock::CfgAssemblerScopedTemporaryBlock(), and ControlFlowGraph().
set_end()
void v8::internal::torque::ControlFlowGraph::set_end (Block * end) [inline]
Definition at line 117 of file cfg.h.
{ end_ = end; }
References end(), and end_.
Referenced by v8::internal::torque::CfgAssembler::Result().
SetReturnType()
void v8::internal::torque::ControlFlowGraph::SetReturnType (TypeVector t) [inline]
Definition at line 118 of file cfg.h.
                                   {
    if (!return_type_) {
      return_type_ = t;
      return;
    }
    if (t != *return_type_) {
      std::stringstream message;
      message << "expected return type ";
      PrintCommaSeparatedList(message, *return_type_);
      message << " instead of ";
      PrintCommaSeparatedList(message, t);
      ReportError(message.str());
    }
  }
References v8::internal::torque::PrintCommaSeparatedList(), v8::internal::torque::ReportError(), and return_type_.
start()
Block* v8::internal::torque::ControlFlowGraph::start () const [inline]
Definition at line 115 of file cfg.h.
{ return start_; }
References start_.
Referenced by v8::internal::torque::CfgAssembler::ComputeInputDefinitions(), v8::internal::torque::CountBlockPredecessors(), v8::internal::torque::CCGenerator::EmitGraph(), and v8::internal::torque::CSAGenerator::EmitGraph().
UnplaceBlockIf()
template<typename UnaryPredicate >
void v8::internal::torque::ControlFlowGraph::UnplaceBlockIf (UnaryPredicate && predicate) [inline]
Definition at line 110 of file cfg.h.
                                                  {
    auto newEnd = std::remove_if(placed_blocks_.begin(), placed_blocks_.end(),
                                 std::forward<UnaryPredicate>(predicate));
    placed_blocks_.erase(newEnd, placed_blocks_.end());
  }
References placed_blocks_.
Referenced by v8::internal::torque::CfgAssembler::OptimizeCfg().
Member Data Documentation
blocks_
std::list<Block> v8::internal::torque::ControlFlowGraph::blocks_ [private]
Definition at line 139 of file cfg.h.
Referenced by NewBlock().
end_
std::optional<Block*> v8::internal::torque::ControlFlowGraph::end_ [private]
Definition at line 142 of file cfg.h.
Referenced by end(), and set_end().
next_block_id_
size_t v8::internal::torque::ControlFlowGraph::next_block_id_ = 0 [private]
Definition at line 144 of file cfg.h.
Referenced by NewBlock(), and NumberOfBlockIds().
placed_blocks_
std::vector<Block*> v8::internal::torque::ControlFlowGraph::placed_blocks_ [private]
Definition at line 141 of file cfg.h.
Referenced by blocks(), PlaceBlock(), and UnplaceBlockIf().
return_type_
std::optional<TypeVector> v8::internal::torque::ControlFlowGraph::return_type_ [private]
Definition at line 143 of file cfg.h.
Referenced by SetReturnType().
start_
Block* v8::internal::torque::ControlFlowGraph::start_ [private]
Definition at line 140 of file cfg.h.
Referenced by ControlFlowGraph(), ParameterCount(), and start().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/cfg.h