v8::internal::LocalHandles Class Reference
#include <local-handles.h>
Public Member Functions
LocalHandles ()
~LocalHandles ()
void Iterate (RootVisitor *visitor)
Private Member Functions
V8_EXPORT_PRIVATE Address * AddBlock ()
V8_EXPORT_PRIVATE void RemoveUnusedBlocks ()
Private Attributes
HandleScopeData scope_
std::vector< Address * > blocks_
Friends
class LocalHandleScope
Detailed Description
Definition at line 19 of file local-handles.h.
Constructor & Destructor Documentation
LocalHandles()
v8::internal::LocalHandles::LocalHandles ()
Definition at line 48 of file local-handles.cc.
{ scope_.Initialize(); }
References v8::internal::HandleScopeData::Initialize(), and scope_.
 LocalHandles()
v8::internal::LocalHandles::~LocalHandles ()
Definition at line 49 of file local-handles.cc.
                            {
  scope_.limit = nullptr;
  RemoveUnusedBlocks();
  DCHECK(blocks_.empty());
}
References blocks_, v8::internal::DCHECK(), v8::internal::HandleScopeData::limit, RemoveUnusedBlocks(), and scope_.
Member Function Documentation
AddBlock()
Address * v8::internal::LocalHandles::AddBlock () [private]
Definition at line 89 of file local-handles.cc.
                                {
  DCHECK_EQ(scope_.next, scope_.limit);
  Address* block = NewArray<Address>(kHandleBlockSize);
  blocks_.push_back(block);
  scope_.next = block;
  scope_.limit = block + kHandleBlockSize;
  return block;
}
References blocks_, DCHECK_EQ, v8::internal::kHandleBlockSize, v8::internal::HandleScopeData::limit, v8::internal::HandleScopeData::next, and scope_.
Referenced by v8::internal::LocalHandleScope::GetHandle().
Iterate()
void v8::internal::LocalHandles::Iterate (RootVisitor * visitor)
Definition at line 55 of file local-handles.cc.
                                               {
  for (int i = 0; i < static_cast<int>(blocks_.size()) - 1; i++) {
    Address* block = blocks_[i];
    visitor->VisitRootPointers(Root::kHandleScope, nullptr,
                               FullObjectSlot(block),
                               FullObjectSlot(&block[kHandleBlockSize]));
  }
  if (!blocks_.empty()) {
    Address* block = blocks_.back();
    visitor->VisitRootPointers(Root::kHandleScope, nullptr,
                               FullObjectSlot(block),
                               FullObjectSlot(scope_.next));
  }
}
References blocks_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kHandleBlockSize, v8::internal::HandleScopeData::next, scope_, and v8::internal::RootVisitor::VisitRootPointers().
RemoveUnusedBlocks()
void v8::internal::LocalHandles::RemoveUnusedBlocks () [private]
Definition at line 98 of file local-handles.cc.
                                      {
  while (!blocks_.empty()) {
    Address* block_start = blocks_.back();
    Address* block_limit = block_start + kHandleBlockSize;
    if (block_limit == scope_.limit) {
      break;
    }
    blocks_.pop_back();
#ifdef ENABLE_LOCAL_HANDLE_ZAPPING
    ZapRange(block_start, block_limit);
#endif
    DeleteArray(block_start);
  }
}
References blocks_, v8::internal::kHandleBlockSize, v8::internal::HandleScopeData::limit, and scope_.
Referenced by v8::internal::LocalHandleScope::CloseScope(), and ~LocalHandles().
Friends And Related Function Documentation
LocalHandleScope
friend class LocalHandleScope [friend]
Definition at line 41 of file local-handles.h.
Member Data Documentation
blocks_
std::vector<Address*> v8::internal::LocalHandles::blocks_ [private]
Definition at line 32 of file local-handles.h.
Referenced by AddBlock(), Iterate(), RemoveUnusedBlocks(), and ~LocalHandles().
scope_
HandleScopeData v8::internal::LocalHandles::scope_ [private]
Definition at line 31 of file local-handles.h.
Referenced by AddBlock(), v8::internal::LocalHandleScope::CloseScope(), v8::internal::LocalHandleScope::GetHandle(), Iterate(), LocalHandles(), v8::internal::LocalHandleScope::LocalHandleScope(), RemoveUnusedBlocks(), and ~LocalHandles().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/local-handles.h
/mnt/V8SourceCode/src/handles/local-handles.cc