v8::internal::DebugScopeIterator Class Reference
#include <debug-scope-iterator.h>
Public Member Functions
DebugScopeIterator (Isolate *isolate, FrameInspector *frame_inspector)
DebugScopeIterator (Isolate *isolate, DirectHandle< JSFunction > function)
DebugScopeIterator (Isolate *isolate, Handle< JSGeneratorObject > generator)
bool Done () override
void Advance () override
ScopeType GetType () override
v8::Local< v8::Object > GetObject () override
v8::Local< v8::Value > GetFunctionDebugName () override
int GetScriptId () override
bool HasLocationInfo () override
debug::Location GetStartLocation () override
debug::Location GetEndLocation () override
bool SetVariableValue (v8::Local< v8::String > name, v8::Local< v8::Value > value) override
Private Member Functions
bool ShouldIgnore ()
Private Attributes
v8::internal::ScopeIterator iterator_
Additional Inherited Members
Detailed Description
Definition at line 15 of file debug-scope-iterator.h.
Constructor & Destructor Documentation
DebugScopeIterator() [1/3]
v8::internal::DebugScopeIterator::DebugScopeIterator (Isolate * isolate, FrameInspector * frame_inspector)
Definition at line 43 of file debug-scope-iterator.cc.
    : iterator_(
          isolate, frame_inspector,
          ::v8::internal::ScopeIterator::ReparseStrategy::kFunctionLiteral) {
  if (!Done() && ShouldIgnore()) Advance();
}
References Advance(), Done(), and ShouldIgnore().
DebugScopeIterator() [2/3]
v8::internal::DebugScopeIterator::DebugScopeIterator (Isolate * isolate, DirectHandle< JSFunction > function)
Definition at line 51 of file debug-scope-iterator.cc.
    : iterator_(isolate, function) {
  if (!Done() && ShouldIgnore()) Advance();
}
References Advance(), Done(), and ShouldIgnore().
DebugScopeIterator() [3/3]
v8::internal::DebugScopeIterator::DebugScopeIterator (Isolate * isolate, Handle< JSGeneratorObject > generator)
Definition at line 57 of file debug-scope-iterator.cc.
    : iterator_(isolate, generator) {
  if (!Done() && ShouldIgnore()) Advance();
}
References Advance(), Done(), and ShouldIgnore().
Member Function Documentation
Advance()
void v8::internal::DebugScopeIterator::Advance () [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 65 of file debug-scope-iterator.cc.
                                 {
  DCHECK(!Done());
  iterator_.Next();
  while (!Done() && ShouldIgnore()) {
    iterator_.Next();
  }
}
References v8::internal::DCHECK(), Done(), iterator_, v8::internal::ScopeIterator::Next(), and ShouldIgnore().
Referenced by DebugScopeIterator().
Done()
bool v8::internal::DebugScopeIterator::Done () [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 63 of file debug-scope-iterator.cc.
{ return iterator_.Done(); }
References v8::internal::ScopeIterator::Done(), and iterator_.
Referenced by Advance(), DebugScopeIterator(), GetEndLocation(), GetFunctionDebugName(), GetObject(), GetScriptId(), GetStartLocation(), GetType(), and SetVariableValue().
GetEndLocation()
debug::Location v8::internal::DebugScopeIterator::GetEndLocation () [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 111 of file debug-scope-iterator.cc.
                                                 {
  DCHECK(!Done());
  return ToApiHandle<v8::debug::Script>(iterator_.GetScript())
      ->GetSourceLocation(iterator_.end_position());
}
References v8::internal::DCHECK(), Done(), v8::internal::ScopeIterator::end_position(), v8::internal::ScopeIterator::GetScript(), and iterator_.
GetFunctionDebugName()
v8::Local< v8::Value > v8::internal::DebugScopeIterator::GetFunctionDebugName () [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 95 of file debug-scope-iterator.cc.
                                                          {
  DCHECK(!Done());
  DirectHandle<Object> name = iterator_.GetFunctionDebugName();
  return Utils::ToLocal(name);
}
References v8::internal::DCHECK(), Done(), v8::internal::ScopeIterator::GetFunctionDebugName(), iterator_, and v8::internal::name.
GetObject()
v8::Local< v8::Object > v8::internal::DebugScopeIterator::GetObject () [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 83 of file debug-scope-iterator.cc.
                                                {
  DCHECK(!Done());
  DirectHandle<JSObject> value =
      iterator_.ScopeObject(i::ScopeIterator::Mode::ALL);
  return Utils::ToLocal(value);
}
References v8::internal::DCHECK(), Done(), iterator_, v8::internal::ScopeIterator::ScopeObject(), and v8::internal::value.
GetScriptId()
int v8::internal::DebugScopeIterator::GetScriptId () [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 90 of file debug-scope-iterator.cc.
                                    {
  DCHECK(!Done());
  return iterator_.GetScript()->id();
}
References v8::internal::DCHECK(), Done(), v8::internal::ScopeIterator::GetScript(), and iterator_.
GetStartLocation()
debug::Location v8::internal::DebugScopeIterator::GetStartLocation () [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 105 of file debug-scope-iterator.cc.
                                                   {
  DCHECK(!Done());
  return ToApiHandle<v8::debug::Script>(iterator_.GetScript())
      ->GetSourceLocation(iterator_.start_position());
}
References v8::internal::DCHECK(), Done(), v8::internal::ScopeIterator::GetScript(), iterator_, and v8::internal::ScopeIterator::start_position().
GetType()
v8::debug::ScopeIterator::ScopeType v8::internal::DebugScopeIterator::GetType () [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 78 of file debug-scope-iterator.cc.
                                                          {
  DCHECK(!Done());
  return static_cast<v8::debug::ScopeIterator::ScopeType>(iterator_.Type());
}
References v8::internal::DCHECK(), Done(), iterator_, and v8::internal::ScopeIterator::Type().
Referenced by ShouldIgnore().
HasLocationInfo()
bool v8::internal::DebugScopeIterator::HasLocationInfo () [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 101 of file debug-scope-iterator.cc.
                                         {
  return iterator_.HasPositionInfo();
}
References v8::internal::ScopeIterator::HasPositionInfo(), and iterator_.
SetVariableValue()
bool v8::internal::DebugScopeIterator::SetVariableValue (v8::Local< v8::String > name, v8::Local< v8::Value > value) [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 117 of file debug-scope-iterator.cc.
                                                                  {
  DCHECK(!Done());
  return iterator_.SetVariableValue(Utils::OpenHandle(*name),
                                    Utils::OpenDirectHandle(*value));
}
References v8::internal::DCHECK(), Done(), iterator_, v8::internal::name, v8::Utils::OpenDirectHandle(), v8::Utils::OpenHandle(), v8::internal::ScopeIterator::SetVariableValue(), and v8::internal::value.
ShouldIgnore()
bool v8::internal::DebugScopeIterator::ShouldIgnore () [private]
Definition at line 73 of file debug-scope-iterator.cc.
                                      {
  if (GetType() == debug::ScopeIterator::ScopeTypeLocal) return false;
  return !iterator_.DeclaresLocals(i::ScopeIterator::Mode::ALL);
}
References v8::internal::ScopeIterator::DeclaresLocals(), GetType(), iterator_, and v8::debug::ScopeIterator::ScopeTypeLocal.
Referenced by Advance(), and DebugScopeIterator().
Member Data Documentation
iterator_
v8::internal::ScopeIterator v8::internal::DebugScopeIterator::iterator_ [private]
Definition at line 37 of file debug-scope-iterator.h.
Referenced by Advance(), Done(), GetEndLocation(), GetFunctionDebugName(), GetObject(), GetScriptId(), GetStartLocation(), GetType(), HasLocationInfo(), SetVariableValue(), and ShouldIgnore().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-scope-iterator.h
/mnt/V8SourceCode/src/debug/debug-scope-iterator.cc