v8::internal::maglev::Int32ShiftRightLogical Class Reference
#include <maglev-ir.h>
Public Member Functions
Int32ShiftRightLogical (uint64_t bitfield)
Input & left_input ()
Input & right_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::Uint32()
static constexpr Base::InputTypes kInputTypes
static constexpr int kLeftIndex = 0
static constexpr int kRightIndex = 1
Private Types
using Base = FixedInputValueNodeT< 2, Int32ShiftRightLogical >
Additional Inherited Members
Detailed Description
Definition at line 3270 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::Int32ShiftRightLogical::Base = FixedInputValueNodeT<2, Int32ShiftRightLogical> [private]
Definition at line 3272 of file maglev-ir.h.
Constructor & Destructor Documentation
Int32ShiftRightLogical()
v8::internal::maglev::Int32ShiftRightLogical::Int32ShiftRightLogical (uint64_t bitfield) [inline], [explicit]
Definition at line 3275 of file maglev-ir.h.
: Base(bitfield) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::Int32ShiftRightLogical::GenerateCode (MaglevAssembler * , const ProcessingState &)
left_input()
Input& v8::internal::maglev::Int32ShiftRightLogical::left_input () [inline]
Definition at line 3284 of file maglev-ir.h.
{ return Node::input(kLeftIndex); }
References v8::internal::maglev::NodeBase::input(), and kLeftIndex.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::Int32ShiftRightLogical::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 3289 of file maglev-ir.h.
{}
right_input()
Input& v8::internal::maglev::Int32ShiftRightLogical::right_input () [inline]
Definition at line 3285 of file maglev-ir.h.
{ return Node::input(kRightIndex); }
References v8::internal::maglev::NodeBase::input(), and kRightIndex.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::Int32ShiftRightLogical::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::Int32ShiftRightLogical::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kInt32, ValueRepresentation::kInt32}
Definition at line 3279 of file maglev-ir.h.
kLeftIndex
constexpr int v8::internal::maglev::Int32ShiftRightLogical::kLeftIndex = 0 [static], [constexpr]
Definition at line 3282 of file maglev-ir.h.
Referenced by left_input().
kProperties
constexpr OpProperties v8::internal::maglev::Int32ShiftRightLogical::kProperties = OpProperties::Uint32() [static], [constexpr]
Definition at line 3278 of file maglev-ir.h.
kRightIndex
constexpr int v8::internal::maglev::Int32ShiftRightLogical::kRightIndex = 1 [static], [constexpr]
Definition at line 3283 of file maglev-ir.h.
Referenced by right_input().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h