v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl Class Reference
Classes
struct LoopStackEntry
Public Member Functions
std::ostream & PrintLivenessTo (std::ostream &os) const
BytecodeAnalysisImpl (BytecodeAnalysis &res, Handle< BytecodeArray > bytecode_array, Zone *zone)
void Analyze ()
Private Member Functions
template<Bytecode BC>
void AnalyzeBCInLoop (int current_offset, LoopInfo *current_loop_info)
void PushLoop (int loop_header, int loop_end)
bool analyze_liveness () const
Zone * zone () const
DirectHandle< BytecodeArray > bytecode_array () const
BytecodeLivenessMap & liveness_map ()
Private Attributes
BytecodeAnalysis & res_
Zone * zone_
Handle< BytecodeArray > const bytecode_array_
ZoneStack< LoopStackEntry > loop_stack_
ZoneVector< int > loop_end_index_queue_
interpreter::BytecodeArrayRandomIterator iterator_
Detailed Description
Definition at line 457 of file bytecode-analysis.cc.
Constructor & Destructor Documentation
BytecodeAnalysisImpl()
v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::BytecodeAnalysisImpl (BytecodeAnalysis & res, Handle< BytecodeArray > bytecode_array, Zone * zone) [inline]
Definition at line 461 of file bytecode-analysis.cc.
      : res_(res),
        zone_(zone),
        bytecode_array_(bytecode_array),
        loop_stack_(zone),
        loop_end_index_queue_(zone),
        iterator_(bytecode_array, zone) {}
Member Function Documentation
Analyze()
void v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze ()
Definition at line 545 of file bytecode-analysis.cc.
                                                   {
  DCHECK_EQ(res_.bytecode_count_, -1);
  res_.bytecode_count_ = iterator_.size();
  loop_stack_.push({-1, nullptr});
  BytecodeLivenessState* next_bytecode_in_liveness = nullptr;
  int osr_loop_end_offset_ = res_.osr_bailout_id_.ToInt();
  DCHECK_EQ(osr_loop_end_offset_ < 0, res_.osr_bailout_id_.IsNone());
  if (analyze_liveness()) {
    res_.liveness_map_.emplace(bytecode_array()->length(), zone());
  }
  for (iterator_.GoToEnd(); iterator_.IsValid(); --iterator_) {
    Bytecode bytecode = iterator_.current_bytecode();
    int current_offset = iterator_.current_offset();
    if (bytecode == Bytecode::kJumpLoop) {
      // Every byte up to and including the last byte within the backwards jump
      // instruction is considered part of the loop, set loop end accordingly.
      int loop_end = current_offset + iterator_.current_bytecode_size();
      int loop_header = iterator_.GetJumpTargetOffset();
      PushLoop(loop_header, loop_end);
      if (current_offset == osr_loop_end_offset_) {
        res_.osr_entry_point_ = loop_header;
      } else if (current_offset < osr_loop_end_offset_) {
        // Assert that we've found the osr_entry_point if we've gone past the
        // osr_loop_end_offset. Note, we are iterating the bytecode in reverse,
        // so the less-than in the above condition is correct.
        DCHECK_LE(0, res_.osr_entry_point_);
      }
      // Save the index so that we can do another pass later.
      if (analyze_liveness()) {
        loop_end_index_queue_.push_back(iterator_.current_index());
      }
    }
    // We have to pop from loop_stack_ if:
    // 1) We entered the body of the loop
    // 2) If we have a JumpLoop that jumps to itself (i.e an empty loop)
    bool in_loop = loop_stack_.size() > 1 &&
                   (bytecode != Bytecode::kJumpLoop ||
                    iterator_.GetJumpTargetOffset() == current_offset);
    if (in_loop) {
      LoopStackEntry& current_loop = loop_stack_.top();
      LoopInfo* current_loop_info = current_loop.loop_info;
      // TODO(leszeks): Ideally, we'd only set values that were assigned in
      // the loop *and* are live when the loop exits. However, this requires
      // tracking the out-liveness of *all* loop exits, which is not
      // information we currently have.
      UpdateAssignments(bytecode, &current_loop_info->assignments(), iterator_);
      switch (bytecode) {
#define CASE(BC, ...) \
  case Bytecode::k##BC: \
    AnalyzeBCInLoop<Bytecode::k##BC>(current_offset, current_loop_info); \
    break;
        BYTECODE_LIST(CASE, CASE)
#undef CASE
      }
      // If we've reached the header of the loop, pop it off the stack.
      if (current_offset == current_loop.header_offset) {
        loop_stack_.pop();
        if (loop_stack_.size() > 1) {
          // If there is still an outer loop, propagate inner loop assignments.
          LoopInfo* parent_loop_info = loop_stack_.top().loop_info;
          if (current_loop_info->resumable()) {
            parent_loop_info->mark_resumable();
          }
          parent_loop_info->assignments().Union(
              current_loop_info->assignments());
          // Also, propagate resume targets. Instead of jumping to the target
          // itself, the outer loop will jump to this loop header for any
          // targets that are inside the current loop, so that this loop stays
          // reducible. Hence, a nested loop of the form:
          //
          // switch (#1 -> suspend1, #2 -> suspend2)
          // loop {
          // suspend1: suspend #1
          // loop {
          // suspend2: suspend #2
          // }
          // }
          //
          // becomes:
          //
          // switch (#1 -> loop1, #2 -> loop1)
          // loop1: loop {
          // switch (#1 -> suspend1, #2 -> loop2)
          // suspend1: suspend #1
          // loop2: loop {
          // switch (#2 -> suspend2)
          // suspend2: suspend #2
          // }
          // }
          for (const auto& target : current_loop_info->resume_jump_targets()) {
            parent_loop_info->AddResumeTarget(
                ResumeJumpTarget::AtLoopHeader(current_offset, target));
          }
        } else {
          // Otherwise, just propagate inner loop suspends to top-level.
          for (const auto& target : current_loop_info->resume_jump_targets()) {
            res_.resume_jump_targets_.push_back(
                ResumeJumpTarget::AtLoopHeader(current_offset, target));
          }
        }
      }
    } else if (bytecode == Bytecode::kSuspendGenerator) {
      // If we're not in a loop, we still need to look for suspends.
      // TODO(leszeks): It would be nice to de-duplicate this with the in-loop
      // case
      int suspend_id = iterator_.GetUnsignedImmediateOperand(3);
      int resume_offset = current_offset + iterator_.current_bytecode_size();
      res_.resume_jump_targets_.push_back(
          ResumeJumpTarget::Leaf(suspend_id, resume_offset));
    }
    if (analyze_liveness()) {
      BytecodeLiveness& liveness =
          liveness_map().InsertNewLiveness(current_offset);
      UpdateLiveness<true>(bytecode, liveness, &next_bytecode_in_liveness,
                           iterator_, bytecode_array(), liveness_map(), zone());
    }
  }
  DCHECK_EQ(loop_stack_.size(), 1u);
  DCHECK_EQ(loop_stack_.top().header_offset, -1);
  DCHECK(ResumeJumpTargetsAreValid());
  if (!analyze_liveness()) return;
  // At this point, every bytecode has a valid in and out liveness, except for
  // propagating liveness across back edges (i.e. JumpLoop). Subsequent liveness
  // analysis iterations can only add additional liveness bits that are pulled
  // across these back edges.
  //
  // Furthermore, a loop header's in-liveness can only change based on any
  // bytecodes *after* the loop end -- it cannot change as a result of the
  // JumpLoop liveness being updated, as the only liveness bits than can be
  // added to the loop body are those of the loop header.
  //
  // So, if we know that the liveness of bytecodes after a loop header won't
  // change (e.g. because there are no loops in them, or we have already ensured
  // those loops are valid), we can safely update the loop end and pass over the
  // loop body, and then never have to pass over that loop end again, because we
  // have shown that its target, the loop header, can't change from the entries
  // after the loop, and can't change from any loop body pass.
  //
  // This means that in a pass, we can iterate backwards over the bytecode
  // array, process any loops that we encounter, and on subsequent passes we can
  // skip processing those loops (though we still have to process inner loops).
  //
  // Equivalently, we can queue up loop ends from back to front, and pass over
  // the loops in that order, as this preserves both the bottom-to-top and
  // outer-to-inner requirements.
  for (int loop_end_index : loop_end_index_queue_) {
    iterator_.GoToIndex(loop_end_index);
    DCHECK_EQ(iterator_.current_bytecode(), Bytecode::kJumpLoop);
    int header_offset = iterator_.GetJumpTargetOffset();
    int end_offset = iterator_.current_offset();
    BytecodeLiveness& header_liveness =
        liveness_map().GetLiveness(header_offset);
    BytecodeLiveness& end_liveness = liveness_map().GetLiveness(end_offset);
    if (!end_liveness.out->UnionIsChanged(*header_liveness.in)) {
      // Only update the loop body if the loop end liveness changed.
      continue;
    }
    end_liveness.in->CopyFrom(*end_liveness.out);
    next_bytecode_in_liveness = end_liveness.in;
    // Advance into the loop body.
    --iterator_;
    for (; iterator_.current_offset() > header_offset; --iterator_) {
      Bytecode bytecode = iterator_.current_bytecode();
      int current_offset = iterator_.current_offset();
      BytecodeLiveness& liveness = liveness_map().GetLiveness(current_offset);
      UpdateLiveness(bytecode, liveness, &next_bytecode_in_liveness, iterator_,
                     bytecode_array(), liveness_map(), zone());
    }
    // Now we are at the loop header. Since the in-liveness of the header can't
    // change, we need only to update the out-liveness.
    UpdateOutLiveness(iterator_.current_bytecode(), header_liveness,
                      next_bytecode_in_liveness, iterator_, bytecode_array(),
                      liveness_map(), zone());
  }
  DCHECK(analyze_liveness());
  if (v8_flags.trace_environment_liveness) {
    StdoutStream of;
    PrintLivenessTo(of);
  }
  DCHECK(LivenessIsValid());
}
References v8::internal::compiler::LoopInfo::AddResumeTarget(), analyze_liveness(), v8::internal::compiler::LoopInfo::assignments(), v8::internal::compiler::ResumeJumpTarget::AtLoopHeader(), bytecode_array(), v8::internal::compiler::BytecodeAnalysis::bytecode_count_, BYTECODE_LIST, CASE, v8::internal::compiler::BytecodeLivenessState::CopyFrom(), v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeArrayIterator::current_bytecode_size(), v8::internal::interpreter::BytecodeArrayRandomIterator::current_index(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset(), v8::internal::compiler::BytecodeLivenessMap::GetLiveness(), v8::internal::interpreter::BytecodeArrayIterator::GetUnsignedImmediateOperand(), v8::internal::interpreter::BytecodeArrayRandomIterator::GoToEnd(), v8::internal::interpreter::BytecodeArrayRandomIterator::GoToIndex(), v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::LoopStackEntry::header_offset, v8::internal::compiler::BytecodeLiveness::in, v8::internal::compiler::BytecodeLivenessMap::InsertNewLiveness(), v8::internal::BytecodeOffset::IsNone(), v8::internal::interpreter::BytecodeArrayRandomIterator::IsValid(), iterator_, v8::internal::compiler::ResumeJumpTarget::Leaf(), v8::internal::length, liveness_map(), v8::internal::compiler::BytecodeAnalysis::liveness_map_, loop_end_index_queue_, v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::LoopStackEntry::loop_info, loop_stack_, v8::internal::compiler::LoopInfo::mark_resumable(), v8::internal::compiler::BytecodeAnalysis::osr_bailout_id_, v8::internal::compiler::BytecodeAnalysis::osr_entry_point_, v8::internal::compiler::BytecodeLiveness::out, PrintLivenessTo(), v8::internal::ZoneVector< T >::push_back(), PushLoop(), res_, v8::internal::compiler::LoopInfo::resumable(), v8::internal::compiler::LoopInfo::resume_jump_targets(), v8::internal::compiler::BytecodeAnalysis::resume_jump_targets_, v8::internal::interpreter::BytecodeArrayRandomIterator::size(), v8::internal::BytecodeOffset::ToInt(), v8::internal::compiler::BytecodeLoopAssignments::Union(), v8::internal::compiler::BytecodeLivenessState::UnionIsChanged(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateAssignments(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateLiveness(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness(), v8::internal::v8_flags, and zone().
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysis().
analyze_liveness()
bool v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::analyze_liveness () const [inline], [private]
Definition at line 510 of file bytecode-analysis.cc.
{ return res_.analyze_liveness_; }
References v8::internal::compiler::BytecodeAnalysis::analyze_liveness_, and res_.
Referenced by Analyze().
AnalyzeBCInLoop()
template<Bytecode BC>
void v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::AnalyzeBCInLoop (int current_offset, LoopInfo * current_loop_info) [inline], [private]
Definition at line 474 of file bytecode-analysis.cc.
                                                                               {
  }
bytecode_array()
DirectHandle<BytecodeArray> v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::bytecode_array () const [inline], [private]
Definition at line 512 of file bytecode-analysis.cc.
{ return bytecode_array_; }
References bytecode_array_.
Referenced by Analyze(), and PushLoop().
liveness_map()
BytecodeLivenessMap& v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::liveness_map () [inline], [private]
Definition at line 513 of file bytecode-analysis.cc.
{ return *res_.liveness_map_; }
References v8::internal::compiler::BytecodeAnalysis::liveness_map_, and res_.
Referenced by Analyze().
PrintLivenessTo()
std::ostream & v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::PrintLivenessTo (std::ostream & os) const
Definition at line 826 of file bytecode-analysis.cc.
                          {
  interpreter::BytecodeArrayIterator iterator(bytecode_array_);
  for (; !iterator.done(); iterator.Advance()) {
    int current_offset = iterator.current_offset();
    const BytecodeLivenessState* in_liveness =
        res_.GetInLivenessFor(current_offset);
    const BytecodeLivenessState* out_liveness =
        res_.GetOutLivenessFor(current_offset);
    os << ToString(*in_liveness) << " -> " << ToString(*out_liveness) << " | "
       << current_offset << ": ";
    iterator.PrintTo(os) << std::endl;
  }
  return os;
}
References v8::internal::interpreter::BytecodeArrayIterator::Advance(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), v8::internal::interpreter::BytecodeArrayIterator::done(), v8::internal::interpreter::BytecodeArrayIterator::PrintTo(), and v8::internal::compiler::ToString().
Referenced by Analyze().
PushLoop()
void v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::PushLoop (int loop_header, int loop_end) [inline], [private]
Definition at line 477 of file bytecode-analysis.cc.
                                               {
    DCHECK_LT(loop_header, loop_end);
    DCHECK_LT(loop_stack_.top().header_offset, loop_header);
    DCHECK_EQ(res_.end_to_header_.find(loop_end), res_.end_to_header_.end());
    DCHECK_EQ(res_.header_to_info_.find(loop_header),
              res_.header_to_info_.end());
    int parent_offset = loop_stack_.top().header_offset;
    res_.end_to_header_.insert({loop_end, loop_header});
    auto it = res_.header_to_info_.insert(
        {loop_header, LoopInfo(parent_offset, loop_header, loop_end,
                               bytecode_array()->parameter_count(),
                               bytecode_array()->register_count(), zone())});
    // Get the loop info pointer from the output of insert.
    LoopInfo* loop_info = &it.first->second;
    if (loop_stack_.top().loop_info) {
      loop_stack_.top().loop_info->mark_not_innermost();
    }
    loop_stack_.push({loop_header, loop_info});
  }
References bytecode_array(), DCHECK_EQ, DCHECK_LT, v8::internal::compiler::BytecodeAnalysis::end_to_header_, v8::internal::compiler::BytecodeAnalysis::header_to_info_, loop_stack_, res_, and zone().
Referenced by Analyze().
zone()
Zone* v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::zone () const [inline], [private]
Definition at line 511 of file bytecode-analysis.cc.
{ return zone_; }
References zone_.
Referenced by Analyze(), and PushLoop().
Member Data Documentation
bytecode_array_
Handle<BytecodeArray> const v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::bytecode_array_ [private]
Definition at line 522 of file bytecode-analysis.cc.
Referenced by bytecode_array().
iterator_
interpreter::BytecodeArrayRandomIterator v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::iterator_ [private]
Definition at line 525 of file bytecode-analysis.cc.
Referenced by Analyze().
loop_end_index_queue_
ZoneVector<int> v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::loop_end_index_queue_ [private]
Definition at line 524 of file bytecode-analysis.cc.
Referenced by Analyze().
loop_stack_
ZoneStack<LoopStackEntry> v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::loop_stack_ [private]
Definition at line 523 of file bytecode-analysis.cc.
Referenced by Analyze(), and PushLoop().
res_
BytecodeAnalysis& v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::res_ [private]
Definition at line 520 of file bytecode-analysis.cc.
Referenced by Analyze(), analyze_liveness(), liveness_map(), and PushLoop().
zone_
Zone* v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::zone_ [private]
Definition at line 521 of file bytecode-analysis.cc.
Referenced by zone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/bytecode-analysis.cc