v8::internal::compiler::JSStoreInArrayLiteralNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSStoreInArrayLiteralNode (Node *node)
const FeedbackParameter & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1700 of file js-operator.h.
Constructor & Destructor Documentation
JSStoreInArrayLiteralNode()
constexpr v8::internal::compiler::JSStoreInArrayLiteralNode::JSStoreInArrayLiteralNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1702 of file js-operator.h.
      : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSStoreInArrayLiteral, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const FeedbackParameter& v8::internal::compiler::JSStoreInArrayLiteralNode::Parameters () const [inline]
Definition at line 1707 of file js-operator.h.
                                              {
    return FeedbackParameterOf(node()->op());
  }
References v8::internal::compiler::FeedbackParameterOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreInArrayLiteral().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h