v8::HeapGraphEdge Class Reference
HeapSnapshotEdge represents a directed connection between heap graph nodes: from retainers to retained nodes.
#include <v8-profiler.h>
Public Types
enum Type {
kContextVariable = 0
, kElement = 1
, kProperty = 2
, kInternal = 3
,
kHidden = 4
, kShortcut = 5
, kWeak = 6
 }
Public Member Functions
Type GetType () const
Returns edge type (see HeapGraphEdge::Type).
Local< Value > GetName () const
Returns edge name.
const HeapGraphNode * GetFromNode () const
Returns origin node.
const HeapGraphNode * GetToNode () const
Returns destination node.
Detailed Description
HeapSnapshotEdge represents a directed connection between heap graph nodes: from retainers to retained nodes.
Definition at line 551 of file v8-profiler.h.
Member Enumeration Documentation
Type
enum v8::HeapGraphEdge::Type
Enumerator
kContextVariable
kElement
kProperty
kInternal
kHidden
kShortcut
kWeak
Definition at line 553 of file v8-profiler.h.
            {
    kContextVariable = 0, // A variable from a function context.
    kElement = 1, // An element of an array.
    kProperty = 2, // A named object property.
    kInternal = 3, // A link that can't be accessed from JS,
                           // thus, its name isn't a real property name
                           // (e.g. parts of a ConsString).
    kHidden = 4, // A link that is needed for proper sizes
                           // calculation, but may be hidden from user.
    kShortcut = 5, // A link that must not be followed during
                           // sizes calculation.
    kWeak = 6 // A weak reference (ignored by the GC).
  };
Member Function Documentation
GetFromNode()
const HeapGraphNode * v8::HeapGraphEdge::GetFromNode () const
Returns origin node.
Definition at line 11628 of file api.cc.
                                                      {
  const i::HeapEntry* from = ToInternal(this)->from();
  return reinterpret_cast<const HeapGraphNode*>(from);
}
References v8::ToInternal().
GetName()
Local< Value > v8::HeapGraphEdge::GetName () const
Returns edge name.
This can be a variable name, an element index, or a property name.
Definition at line 11608 of file api.cc.
                                          {
  i::HeapGraphEdge* edge = ToInternal(this);
  i::Isolate* i_isolate = edge->isolate();
  switch (edge->type()) {
    case i::HeapGraphEdge::kContextVariable:
    case i::HeapGraphEdge::kInternal:
    case i::HeapGraphEdge::kProperty:
    case i::HeapGraphEdge::kShortcut:
    case i::HeapGraphEdge::kWeak:
      return ToApiHandle<String>(
          i_isolate->factory()->InternalizeUtf8String(edge->name()));
    case i::HeapGraphEdge::kElement:
    case i::HeapGraphEdge::kHidden:
      return ToApiHandle<Number>(
          i_isolate->factory()->NewNumberFromInt(edge->index()));
    default:
      UNREACHABLE();
  }
}
References v8::internal::Isolate::factory(), v8::internal::HeapGraphEdge::index(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::HeapGraphEdge::isolate(), v8::internal::HeapGraphEdge::kContextVariable, v8::internal::HeapGraphEdge::kElement, v8::internal::HeapGraphEdge::kHidden, v8::internal::HeapGraphEdge::kInternal, v8::internal::HeapGraphEdge::kProperty, v8::internal::HeapGraphEdge::kShortcut, v8::internal::HeapGraphEdge::kWeak, v8::internal::HeapGraphEdge::name(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), v8::ToInternal(), v8::internal::HeapGraphEdge::type(), and UNREACHABLE.
GetToNode()
const HeapGraphNode * v8::HeapGraphEdge::GetToNode () const
Returns destination node.
Definition at line 11633 of file api.cc.
                                                    {
  const i::HeapEntry* to = ToInternal(this)->to();
  return reinterpret_cast<const HeapGraphNode*>(to);
}
References v8::ToInternal().
GetType()
HeapGraphEdge::Type v8::HeapGraphEdge::GetType () const
Returns edge type (see HeapGraphEdge::Type).
Definition at line 11604 of file api.cc.
                                               {
  return static_cast<HeapGraphEdge::Type>(ToInternal(this)->type());
}
References v8::ToInternal().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-profiler.h
/mnt/V8SourceCode/src/api/api.cc