v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch Class Reference
Public Member Functions
VectorBackedMatch (Isolate *isolate, DirectHandle< String > subject, DirectHandle< String > match, uint32_t match_position, base::Vector< DirectHandle< Object >> captures, DirectHandle< Object > groups_obj)
DirectHandle< String > GetMatch () override
DirectHandle< String > GetPrefix () override
DirectHandle< String > GetSuffix () override
bool HasNamedCaptures () override
int CaptureCount () override
MaybeDirectHandle< String > GetCapture (int i, bool *capture_exists) override
MaybeDirectHandle< String > GetNamedCapture (DirectHandle< String > name, CaptureState *state) override
Private Attributes
Isolate * isolate_
DirectHandle< String > subject_
DirectHandle< String > match_
const uint32_t match_position_
base::Vector< DirectHandle< Object > > captures_
bool has_named_captures_
DirectHandle< JSReceiver > groups_obj_
Additional Inherited Members
Detailed Description
Definition at line 1123 of file runtime-regexp.cc.
Constructor & Destructor Documentation
VectorBackedMatch()
v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::VectorBackedMatch (Isolate * isolate, DirectHandle< String > subject, DirectHandle< String > match, uint32_t match_position, base::Vector< DirectHandle< Object >> captures, DirectHandle< Object > groups_obj) [inline]
Definition at line 1125 of file runtime-regexp.cc.
      : isolate_(isolate),
        match_(match),
        match_position_(match_position),
        captures_(captures) {
    subject_ = String::Flatten(isolate, subject);
    DCHECK(IsUndefined(*groups_obj, isolate) || IsJSReceiver(*groups_obj));
    has_named_captures_ = !IsUndefined(*groups_obj, isolate);
    if (has_named_captures_) groups_obj_ = Cast<JSReceiver>(groups_obj);
  }
References v8::internal::DCHECK().
Member Function Documentation
CaptureCount()
int v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::CaptureCount () [inline], [override], [virtual]
Implements v8::internal::String::Match.
Definition at line 1160 of file runtime-regexp.cc.
{ return captures_.length(); }
GetCapture()
MaybeDirectHandle<String> v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::GetCapture (int i, bool * capture_exists) [inline], [override], [virtual]
Implements v8::internal::String::Match.
Definition at line 1162 of file runtime-regexp.cc.
                                                                             {
    DirectHandle<Object> capture_obj = captures_[i];
    if (IsUndefined(*capture_obj, isolate_)) {
      *capture_exists = false;
      return isolate_->factory()->empty_string();
    }
    *capture_exists = true;
    return Object::ToString(isolate_, capture_obj);
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::Value::ToString().
GetMatch()
DirectHandle<String> v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::GetMatch () [inline], [override], [virtual]
Implements v8::internal::String::Match.
Definition at line 1140 of file runtime-regexp.cc.
{ return match_; }
GetNamedCapture()
MaybeDirectHandle<String> v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::GetNamedCapture (DirectHandle< String > name, CaptureState * state) [inline], [override], [virtual]
Implements v8::internal::String::Match.
Definition at line 1172 of file runtime-regexp.cc.
                                                                          {
    DCHECK(has_named_captures_);
    // Strings representing integer indices are not valid identifiers (and
    // therefore not valid capture names).
    {
      size_t unused;
      if (name->AsIntegerIndex(&unused)) {
        *state = UNMATCHED;
        return isolate_->factory()->empty_string();
      }
    }
    DirectHandle<Object> capture_obj;
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate_, capture_obj,
        Object::GetProperty(isolate_, groups_obj_, name));
    if (IsUndefined(*capture_obj, isolate_)) {
      *state = UNMATCHED;
      return isolate_->factory()->empty_string();
    } else {
      *state = MATCHED;
      return Object::ToString(isolate_, capture_obj);
    }
  }
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DCHECK(), v8::internal::Object::GetProperty(), v8::internal::name, and v8::Value::ToString().
GetPrefix()
DirectHandle<String> v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::GetPrefix () [inline], [override], [virtual]
Implements v8::internal::String::Match.
Definition at line 1142 of file runtime-regexp.cc.
                                            {
    // match_position_ and match_ are user-controlled, hence we manually clamp
    // the index here.
    uint32_t end = std::min(subject_->length(), match_position_);
    return isolate_->factory()->NewSubString(subject_, 0, end);
  }
References v8::internal::compiler::end().
GetSuffix()
DirectHandle<String> v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::GetSuffix () [inline], [override], [virtual]
Implements v8::internal::String::Match.
Definition at line 1149 of file runtime-regexp.cc.
                                            {
    // match_position_ and match_ are user-controlled, hence we manually clamp
    // the index here.
    uint32_t start =
        std::min(subject_->length(), match_position_ + match_->length());
    return isolate_->factory()->NewSubString(subject_, start,
                                             subject_->length());
  }
HasNamedCaptures()
bool v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::HasNamedCaptures () [inline], [override], [virtual]
Implements v8::internal::String::Match.
Definition at line 1158 of file runtime-regexp.cc.
{ return has_named_captures_; }
Member Data Documentation
captures_
base::Vector<DirectHandle<Object> > v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::captures_ [private]
Definition at line 1203 of file runtime-regexp.cc.
groups_obj_
DirectHandle<JSReceiver> v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::groups_obj_ [private]
Definition at line 1206 of file runtime-regexp.cc.
has_named_captures_
bool v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::has_named_captures_ [private]
Definition at line 1205 of file runtime-regexp.cc.
isolate_
Isolate* v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::isolate_ [private]
Definition at line 1199 of file runtime-regexp.cc.
match_
DirectHandle<String> v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::match_ [private]
Definition at line 1201 of file runtime-regexp.cc.
match_position_
const uint32_t v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::match_position_ [private]
Definition at line 1202 of file runtime-regexp.cc.
subject_
DirectHandle<String> v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::subject_ [private]
Definition at line 1200 of file runtime-regexp.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/runtime/runtime-regexp.cc