v8::internal::torque::SourceId Class Reference
#include <source-positions.h>
Public Member Functions
bool IsValid () const
int operator== (const SourceId &s) const
bool operator< (const SourceId &s) const
Static Public Member Functions
static SourceId Invalid ()
Private Member Functions
SourceId (int id)
Private Attributes
int id_
Friends
struct SourcePosition
class SourceFileMap
Detailed Description
Definition at line 18 of file source-positions.h.
Constructor & Destructor Documentation
SourceId()
v8::internal::torque::SourceId::SourceId (int id) [inline], [explicit], [private]
Definition at line 26 of file source-positions.h.
: id_(id) {}
Referenced by Invalid().
Member Function Documentation
Invalid()
static SourceId v8::internal::torque::SourceId::Invalid () [inline], [static]
Definition at line 20 of file source-positions.h.
{ return SourceId(-1); }
References SourceId().
Referenced by v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::DiagnosticCollector::AddTorqueMessage(), v8::internal::torque::CompileTorque(), v8::internal::torque::CompileTorqueForKythe(), v8::internal::torque::SourceFileMap::GetSourceId(), and v8::internal::torque::SourcePosition::Invalid().
IsValid()
bool v8::internal::torque::SourceId::IsValid () const [inline]
Definition at line 21 of file source-positions.h.
{ return id_ != -1; }
References id_.
Referenced by v8::internal::torque::KytheData::AddCall(), v8::internal::torque::LanguageServerData::FindDefinition(), v8::internal::torque::Declarable::IdentifierPosition(), v8::internal::torque::anonymous_namespace{kythe-data.cc}::MakeKythePosition(), and v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::SendCompilationDiagnostics().
operator<()
bool v8::internal::torque::SourceId::operator< (const SourceId & s) const [inline]
Definition at line 23 of file source-positions.h.
{ return id_ < s.id_; }
References id_.
operator==()
int v8::internal::torque::SourceId::operator== (const SourceId & s) const [inline]
Definition at line 22 of file source-positions.h.
{ return id_ == s.id_; }
References id_.
Friends And Related Function Documentation
SourceFileMap
friend class SourceFileMap [friend]
Definition at line 29 of file source-positions.h.
SourcePosition
friend struct SourcePosition [friend]
Definition at line 28 of file source-positions.h.
Member Data Documentation
id_
int v8::internal::torque::SourceId::id_ [private]
Definition at line 27 of file source-positions.h.
Referenced by IsValid(), operator<(), and operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/source-positions.h