v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T > Class Template Reference
#include <sidetable.h>
Public Member Functions
SparseOpIndexSideTable (Zone *zone, const Graph *graph)
T & operator[] (OpIndex index)
const T & operator[] (OpIndex index) const
bool contains (OpIndex index, const T **value=nullptr) const
void remove (OpIndex index)
auto begin ()
auto end ()
Private Attributes
ZoneAbslFlatHashMap< OpIndex, T > data_
Detailed Description
template<class T>
class v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >
Definition at line 221 of file sidetable.h.
Constructor & Destructor Documentation
SparseOpIndexSideTable()
template<class T >
v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::SparseOpIndexSideTable (Zone * zone, const Graph * graph) [inline]
Definition at line 223 of file sidetable.h.
      : data_(zone)
#ifdef DEBUG
        ,
        graph_(graph)
#endif
  {
  }
Member Function Documentation
begin()
template<class T >
auto v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::begin () [inline]
Definition at line 258 of file sidetable.h.
{ return data_.begin(); }
References v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::data_.
contains()
template<class T >
bool v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::contains (OpIndex index, const T ** value = nullptr) const [inline]
Definition at line 243 of file sidetable.h.
                                                                {
    DCHECK(OpIndexBelongsToTableGraph(graph_, index));
    if (auto it = data_.find(index); it != data_.end()) {
      if (value) *value = &it->second;
      return true;
    }
    return false;
  }
References v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::data_, v8::internal::DCHECK(), v8::internal::index, and v8::internal::value.
end()
template<class T >
auto v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::end () [inline]
Definition at line 259 of file sidetable.h.
{ return data_.end(); }
References v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::data_.
operator[]() [1/2]
template<class T >
T& v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::operator[] (OpIndex index) [inline]
Definition at line 232 of file sidetable.h.
                               {
    DCHECK(OpIndexBelongsToTableGraph(graph_, index));
    return data_[index];
  }
References v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::data_, v8::internal::DCHECK(), and v8::internal::index.
operator[]() [2/2]
template<class T >
const T& v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::operator[] (OpIndex index) const [inline]
Definition at line 237 of file sidetable.h.
                                           {
    DCHECK(OpIndexBelongsToTableGraph(graph_, index));
    DCHECK(data_.contains(index));
    return data_.at(index);
  }
References v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::data_, v8::internal::DCHECK(), and v8::internal::index.
remove()
template<class T >
void v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::remove (OpIndex index) [inline]
Definition at line 252 of file sidetable.h.
                             {
    DCHECK(OpIndexBelongsToTableGraph(graph_, index));
    auto it = data_.find(index);
    if (it != data_.end()) data_.erase(it);
  }
References v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::data_, v8::internal::DCHECK(), and v8::internal::index.
Member Data Documentation
data_
template<class T >
ZoneAbslFlatHashMap<OpIndex, T> v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::data_ [private]
Definition at line 262 of file sidetable.h.
Referenced by v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::begin(), v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::contains(), v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::end(), v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::operator[](), and v8::internal::compiler::turboshaft::SparseOpIndexSideTable< T >::remove().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/sidetable.h