v8::internal::FlagHelpers Class Reference
#include <flags-impl.h>
Static Public Member Functions
static char NormalizeChar (char ch)
static int FlagNamesCmp (const char *a, const char *b)
static bool EqualNames (const char *a, const char *b)
static bool EqualNameWithSuffix (const char *a, const char *b)
Detailed Description
Definition at line 17 of file flags-impl.h.
Member Function Documentation
EqualNames()
bool v8::internal::FlagHelpers::EqualNames (const char * a, const char * b) [static]
Definition at line 69 of file flags.cc.
                                                         {
  return FlagNamesCmp(a, b) == 0;
}
References FlagNamesCmp().
Referenced by v8::internal::FindFlagByName().
EqualNameWithSuffix()
bool v8::internal::FlagHelpers::EqualNameWithSuffix (const char * a, const char * b) [static]
Definition at line 76 of file flags.cc.
                                                                  {
  char ac, bc;
  for (int i = 0; true; ++i) {
    ac = NormalizeChar(a[i]);
    bc = NormalizeChar(b[i]);
    if (ac == '\0') break;
    if (ac != bc) return false;
  }
  return bc == '\0' || std::isspace(bc);
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and NormalizeChar().
Referenced by v8::internal::FindImplicationFlagByName().
FlagNamesCmp()
int v8::internal::FlagHelpers::FlagNamesCmp (const char * a, const char * b) [static]
Definition at line 55 of file flags.cc.
                                                          {
  int i = 0;
  char ac, bc;
  do {
    ac = NormalizeChar(a[i]);
    bc = NormalizeChar(b[i]);
    if (ac < bc) return -1;
    if (ac > bc) return 1;
    i++;
  } while (ac != '\0');
  DCHECK_EQ(bc, '\0');
  return 0;
}
References DCHECK_EQ, and NormalizeChar().
Referenced by EqualNames(), v8::internal::FlagNameGreater::operator()(), and v8::internal::FlagLess::operator()().
NormalizeChar()
char v8::internal::FlagHelpers::NormalizeChar (char ch) [static]
Definition at line 53 of file flags.cc.
{ return ch == '_' ? '-' : ch; }
Referenced by EqualNameWithSuffix(), FlagNamesCmp(), v8::internal::operator<<(), and v8::internal::SplitArgument().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/flags/flags-impl.h
/mnt/V8SourceCode/src/flags/flags.cc