v8::internal::JSTemporalPlainMonthDay Class Reference
#include <js-temporal-objects.h>
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainMonthDay > Constructor (Isolate *isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > iso_month, DirectHandle< Object > iso_day, DirectHandle< Object > calendar_like, DirectHandle< Object > reference_iso_year)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainMonthDay > From (Isolate *isolate, DirectHandle< Object > item, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Oddball > Equals (Isolate *isolate, DirectHandle< JSTemporalPlainMonthDay > month_day, DirectHandle< Object > other)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainMonthDay > With (Isolate *isolate, DirectHandle< JSTemporalPlainMonthDay > month_day, DirectHandle< Object > temporal_month_day_like, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDate > ToPlainDate (Isolate *isolate, DirectHandle< JSTemporalPlainMonthDay > month_day, DirectHandle< Object > item)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSReceiver > GetISOFields (Isolate *isolate, DirectHandle< JSTemporalPlainMonthDay > month_day)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToString (Isolate *isolate, DirectHandle< JSTemporalPlainMonthDay > month_day, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToJSON (Isolate *isolate, DirectHandle< JSTemporalPlainMonthDay > month_day)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToLocaleString (Isolate *isolate, DirectHandle< JSTemporalPlainMonthDay > plain_date, DirectHandle< Object > locales, DirectHandle< Object > options)
Detailed Description
Definition at line 486 of file js-temporal-objects.h.
Member Function Documentation
Constructor()
MaybeDirectHandle< JSTemporalPlainMonthDay > v8::internal::JSTemporalPlainMonthDay::Constructor (Isolate * isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > iso_month, DirectHandle< Object > iso_day, DirectHandle< Object > calendar_like, DirectHandle< Object > reference_iso_year) [static]
Definition at line 2279 of file js-temporal-objects.cc.
                                                 {
  // 1. If NewTarget is undefined, then
  if (IsUndefined(*new_target)) {
    // a. Throw a TypeError exception.
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kMethodInvokedOnWrongType,
                                 isolate->factory()->NewStringFromAsciiChecked(
                                     "Temporal.PlainYearMonth")));
  }
  // 2. If referenceISOYear is undefined, then
  // a. Set referenceISOYear to 1𝔽.
  double reference_iso_year = 1972.0;
  // 3. Let m be ? ToIntegerWithTruncation(isoMonth).
  double m = 0;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, m, temporal::ToIntegerWithTruncation(isolate, iso_month_obj),
      kNullMaybeHandle);
  // 4. Let d be ? ToIntegerWithTruncation(isoYear).
  double d = 0;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, d, temporal::ToIntegerWithTruncation(isolate, iso_day_obj),
      kNullMaybeHandle);
  // 5. If calendar is undefined, set calendar to "iso8601".
  temporal_rs::AnyCalendarKind calendar = temporal_rs::AnyCalendarKind::Iso;
  if (!IsUndefined(*calendar_like)) {
    // 6. If calendar is not a String, throw a TypeError exception.
    if (!IsString(*calendar_like)) {
      THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR());
    }
    // 7. Set calendar to ?CanonicalizeCalendar(calendar).
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, calendar,
        temporal::CanonicalizeCalendar(isolate, Cast<String>(calendar_like)),
        kNullMaybeHandle);
  }
  if (!IsUndefined(*reference_iso_year_obj)) {
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, reference_iso_year,
        temporal::ToIntegerWithTruncation(isolate, reference_iso_year_obj),
        kNullMaybeHandle);
  }
  // 9. If IsValidISODate(ref, m, d) is false, throw a RangeError exception.
  if (!temporal::IsValidIsoDate(reference_iso_year, m, d)) {
    THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR());
  }
  // Rest of the steps handled in Rust.
  // These static_casts are fine to perform since IsValid* will have constrained
  // these values to range already.
  // https://github.com/boa-dev/temporal/issues/334 for moving this logic into
  // the Rust code.
  auto rust_object = temporal_rs::PlainMonthDay::try_new_with_overflow(
      static_cast<uint8_t>(m), static_cast<uint8_t>(d), calendar,
      temporal_rs::ArithmeticOverflow::Reject,
      static_cast<int32_t>(reference_iso_year));
  return ConstructRustWrappingType<JSTemporalPlainMonthDay>(
      isolate, target, new_target, std::move(rust_object));
}
References v8::internal::temporal::CanonicalizeCalendar(), v8::internal::Isolate::factory(), v8::internal::temporal::IsValidIsoDate(), v8::internal::kNullMaybeHandle, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), THROW_NEW_ERROR, and v8::internal::temporal::ToIntegerWithTruncation().
Referenced by v8::internal::BUILTIN().
Equals()
MaybeDirectHandle< Oddball > v8::internal::JSTemporalPlainMonthDay::Equals (Isolate * isolate, DirectHandle< JSTemporalPlainMonthDay > month_day, DirectHandle< Object > other) [static]
Definition at line 2357 of file js-temporal-objects.cc.
                                    {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
From()
MaybeDirectHandle< JSTemporalPlainMonthDay > v8::internal::JSTemporalPlainMonthDay::From (Isolate * isolate, DirectHandle< Object > item, DirectHandle< Object > options) [static]
Definition at line 2350 of file js-temporal-objects.cc.
                                      {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
GetISOFields()
MaybeDirectHandle< JSReceiver > v8::internal::JSTemporalPlainMonthDay::GetISOFields (Isolate * isolate, DirectHandle< JSTemporalPlainMonthDay > month_day) [static]
Definition at line 2379 of file js-temporal-objects.cc.
                                                                       {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToJSON()
MaybeDirectHandle< String > v8::internal::JSTemporalPlainMonthDay::ToJSON (Isolate * isolate, DirectHandle< JSTemporalPlainMonthDay > month_day) [static]
Definition at line 2385 of file js-temporal-objects.cc.
                                                                       {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToLocaleString()
MaybeDirectHandle< String > v8::internal::JSTemporalPlainMonthDay::ToLocaleString (Isolate * isolate, DirectHandle< JSTemporalPlainMonthDay > plain_date, DirectHandle< Object > locales, DirectHandle< Object > options) [static]
Definition at line 2398 of file js-temporal-objects.cc.
                                                                {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToPlainDate()
MaybeDirectHandle< JSTemporalPlainDate > v8::internal::JSTemporalPlainMonthDay::ToPlainDate (Isolate * isolate, DirectHandle< JSTemporalPlainMonthDay > month_day, DirectHandle< Object > item) [static]
Definition at line 2372 of file js-temporal-objects.cc.
                                   {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToString()
MaybeDirectHandle< String > v8::internal::JSTemporalPlainMonthDay::ToString (Isolate * isolate, DirectHandle< JSTemporalPlainMonthDay > month_day, DirectHandle< Object > options) [static]
Definition at line 2391 of file js-temporal-objects.cc.
                                  {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
With()
MaybeDirectHandle< JSTemporalPlainMonthDay > v8::internal::JSTemporalPlainMonthDay::With (Isolate * isolate, DirectHandle< JSTemporalPlainMonthDay > month_day, DirectHandle< Object > temporal_month_day_like, DirectHandle< Object > options) [static]
Definition at line 2364 of file js-temporal-objects.cc.
                                      {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-temporal-objects.h
/mnt/V8SourceCode/src/objects/js-temporal-objects.cc