v8::internal::NameDictionary Class Reference
#include <dictionary.h>
Public Types
using MayHaveInterestingPropertiesBit = base::BitField< bool, 0, 1, uint32_t >
Public Member Functions
Tagged< Name > NameAt (InternalIndex entry)
Tagged< Name > NameAt (PtrComprCageBase cage_base, InternalIndex entry)
void set_hash (int hash)
int hash () const
uint32_t flags () const
void set_flags (uint32_t flags)
template<typename IsolateT >
Handle< NameDictionary > New (IsolateT *isolate, int at_least_space_for, AllocationType allocation, MinimumCapacity capacity_option)
Static Public Member Functions
static DirectHandle< Map > GetMap (RootsTable &roots)
template<typename IsolateT >
static V8_WARN_UNUSED_RESULT Handle< NameDictionary > New (IsolateT *isolate, int at_least_space_for, AllocationType allocation=AllocationType::kYoung, MinimumCapacity capacity_option=USE_DEFAULT_MINIMUM_CAPACITY)
Static Public Attributes
static const int kFlagsIndex = kObjectHashIndex + 1
static const int kEntryValueIndex = 1
static const int kEntryDetailsIndex = 2
static const int kInitialCapacity = 2
static constexpr int kFlagsDefault = 0
Detailed Description
Definition at line 280 of file dictionary.h.
Member Typedef Documentation
MayHaveInterestingPropertiesBit
using v8::internal::NameDictionary::MayHaveInterestingPropertiesBit = base::BitField<bool, 0, 1, uint32_t>
Definition at line 299 of file dictionary.h.
Member Function Documentation
flags()
uint32_t v8::internal::NameDictionary::flags () const [inline]
Definition at line 228 of file dictionary-inl.h.
                                     {
  return Smi::ToInt(this->get(kFlagsIndex));
}
References kFlagsIndex, and v8::internal::Smi::ToInt().
Referenced by set_flags().
GetMap()
DirectHandle< Map > v8::internal::NameDictionary::GetMap (RootsTable & roots) [inline], [static]
Definition at line 224 of file dictionary-inl.h.
                                                          {
  return roots.name_dictionary_map();
}
hash()
int v8::internal::NameDictionary::hash () const [inline]
NameAt() [1/2]
Tagged< Name > v8::internal::NameDictionary::NameAt (InternalIndex entry) [inline]
Definition at line 214 of file dictionary-inl.h.
                                                       {
  PtrComprCageBase cage_base = GetPtrComprCageBase();
  return NameAt(cage_base, entry);
}
References v8::internal::GetPtrComprCageBase().
NameAt() [2/2]
Tagged< Name > v8::internal::NameDictionary::NameAt (PtrComprCageBase cage_base, InternalIndex entry) [inline]
Definition at line 219 of file dictionary-inl.h.
                                                         {
  return Cast<Name>(KeyAt(cage_base, entry));
}
New() [1/2]
template<typename IsolateT >
Handle<NameDictionary> v8::internal::NameDictionary::New (IsolateT * isolate, int at_least_space_for, AllocationType allocation, MinimumCapacity capacity_option)
Definition at line 5695 of file objects.cc.
                                                                            {
  Handle<NameDictionary> dict =
      BaseNameDictionary<NameDictionary, NameDictionaryShape>::New(
          isolate, at_least_space_for, allocation, capacity_option);
  dict->set_flags(kFlagsDefault);
  return dict;
}
References v8::internal::anonymous_namespace{intl-objects.cc}::New().
New() [2/2]
template<typename IsolateT >
static V8_WARN_UNUSED_RESULT Handle<NameDictionary> v8::internal::NameDictionary::New (IsolateT * isolate, int at_least_space_for, AllocationType allocation = AllocationType::kYoung, MinimumCapacity capacity_option = USE_DEFAULT_MINIMUM_CAPACITY) [static]
Referenced by v8::internal::Heap::CreateImportantReadOnlyObjects(), v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::GetNameTable(), v8::Object::New(), v8::internal::Factory::NewNameDictionary(), and v8::internal::Factory::NewSlowJSObjectFromMap().
set_flags()
void v8::internal::NameDictionary::set_flags (uint32_t flags) [inline]
Definition at line 232 of file dictionary-inl.h.
                                             {
  this->set(kFlagsIndex, Smi::FromInt(flags));
}
References flags(), v8::internal::Smi::FromInt(), and kFlagsIndex.
set_hash()
void v8::internal::NameDictionary::set_hash (int hash) [inline]
Member Data Documentation
kEntryDetailsIndex
const int v8::internal::NameDictionary::kEntryDetailsIndex = 2 [static]
Definition at line 289 of file dictionary.h.
kEntryValueIndex
const int v8::internal::NameDictionary::kEntryValueIndex = 1 [static]
Definition at line 288 of file dictionary.h.
kFlagsDefault
constexpr int v8::internal::NameDictionary::kFlagsDefault = 0 [static], [constexpr]
Definition at line 302 of file dictionary.h.
Referenced by v8::internal::CodeStubAssembler::AllocateNameDictionaryWithCapacity(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject().
kFlagsIndex
const int v8::internal::NameDictionary::kFlagsIndex = kObjectHashIndex + 1 [static]
Definition at line 287 of file dictionary.h.
Referenced by v8::internal::CodeStubAssembler::AllocateNameDictionaryWithCapacity(), flags(), v8::internal::compiler::AccessBuilder::ForNameDictionaryFlagsIndex(), v8::internal::CodeStubAssembler::GetNameDictionaryFlags(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), set_flags(), and v8::internal::CodeStubAssembler::SetNameDictionaryFlags().
kInitialCapacity
const int v8::internal::NameDictionary::kInitialCapacity = 2 [static]
Definition at line 290 of file dictionary.h.
Referenced by v8::internal::ConstructorBuiltinsAssembler::FastNewObject(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), v8::internal::JSObject::New(), v8::internal::Factory::NewFastOrSlowJSObjectFromMap(), v8::internal::Factory::NewSlowJSObjectFromMap(), v8::internal::JSObject::NewWithMap(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), and v8::internal::TF_BUILTIN().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/dictionary.h
/mnt/V8SourceCode/src/objects/dictionary-inl.h
/mnt/V8SourceCode/src/objects/objects.cc