v8::internal::compiler::turboshaft::BundlePackNode Class Reference
#include <wasm-revec-reducer.h>
Public Member Functions
BundlePackNode (Zone *zone, const NodeGroup &node_group, OpIndex base, int8_t offset, uint8_t lane_size, bool is_sign_extract, bool is_sign_convert)
OpIndex base () const
uint8_t offset () const
uint8_t lane_size () const
bool is_sign_extract () const
bool is_sign_convert () const
Private Attributes
OpIndex base_
uint8_t offset_
uint8_t lane_size_
bool is_sign_extract_
bool is_sign_convert_
Additional Inherited Members
Detailed Description
Definition at line 422 of file wasm-revec-reducer.h.
Constructor & Destructor Documentation
BundlePackNode()
v8::internal::compiler::turboshaft::BundlePackNode::BundlePackNode (Zone * zone, const NodeGroup & node_group, OpIndex base, int8_t offset, uint8_t lane_size, bool is_sign_extract, bool is_sign_convert) [inline]
Definition at line 424 of file wasm-revec-reducer.h.
      : PackNode(zone, node_group, kBundlePackNode) {
    base_ = base;
    offset_ = offset;
    lane_size_ = lane_size;
    is_sign_extract_ = is_sign_extract;
    is_sign_convert_ = is_sign_convert;
  }
References base(), base_, is_sign_convert(), is_sign_convert_, is_sign_extract(), is_sign_extract_, lane_size(), lane_size_, offset(), and offset_.
Member Function Documentation
base()
OpIndex v8::internal::compiler::turboshaft::BundlePackNode::base () const [inline]
Definition at line 435 of file wasm-revec-reducer.h.
{ return base_; }
References base_.
Referenced by BundlePackNode(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128ReplaceLane().
is_sign_convert()
bool v8::internal::compiler::turboshaft::BundlePackNode::is_sign_convert () const [inline]
Definition at line 439 of file wasm-revec-reducer.h.
{ return is_sign_convert_; }
References is_sign_convert_.
Referenced by BundlePackNode(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128ReplaceLane().
is_sign_extract()
bool v8::internal::compiler::turboshaft::BundlePackNode::is_sign_extract () const [inline]
Definition at line 438 of file wasm-revec-reducer.h.
{ return is_sign_extract_; }
References is_sign_extract_.
Referenced by BundlePackNode(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128ReplaceLane().
lane_size()
uint8_t v8::internal::compiler::turboshaft::BundlePackNode::lane_size () const [inline]
Definition at line 437 of file wasm-revec-reducer.h.
{ return lane_size_; }
References lane_size_.
Referenced by BundlePackNode(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128ReplaceLane().
offset()
uint8_t v8::internal::compiler::turboshaft::BundlePackNode::offset () const [inline]
Definition at line 436 of file wasm-revec-reducer.h.
{ return offset_; }
References offset_.
Referenced by BundlePackNode(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128ReplaceLane().
Member Data Documentation
base_
OpIndex v8::internal::compiler::turboshaft::BundlePackNode::base_ [private]
Definition at line 442 of file wasm-revec-reducer.h.
Referenced by base(), and BundlePackNode().
is_sign_convert_
bool v8::internal::compiler::turboshaft::BundlePackNode::is_sign_convert_ [private]
Definition at line 446 of file wasm-revec-reducer.h.
Referenced by BundlePackNode(), and is_sign_convert().
is_sign_extract_
bool v8::internal::compiler::turboshaft::BundlePackNode::is_sign_extract_ [private]
Definition at line 445 of file wasm-revec-reducer.h.
Referenced by BundlePackNode(), and is_sign_extract().
lane_size_
uint8_t v8::internal::compiler::turboshaft::BundlePackNode::lane_size_ [private]
Definition at line 444 of file wasm-revec-reducer.h.
Referenced by BundlePackNode(), and lane_size().
offset_
uint8_t v8::internal::compiler::turboshaft::BundlePackNode::offset_ [private]
Definition at line 443 of file wasm-revec-reducer.h.
Referenced by BundlePackNode(), and offset().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-revec-reducer.h