v8::internal::torque::BitFieldStructType Class Reference
#include <types.h>
Public Member Functions
std::string ToExplicitString () const override
std::string GetGeneratedTypeNameImpl () const override
std::string GetGeneratedTNodeTypeNameImpl () const override
std::vector< TypeChecker > GetTypeCheckers () const override
void SetConstexprVersion (const Type *) const override
const Type * ConstexprVersion () const override
void RegisterField (BitField field)
const std::string & name () const
const std::vector< BitField > & fields () const
const BitField & LookupField (const std::string &name) const
const SourcePosition GetPosition () const
Private Member Functions
BitFieldStructType (Namespace *nspace, const Type *parent, const BitFieldStructDeclaration *decl)
std::string SimpleNameImpl () const override
Private Attributes
Namespace * namespace_
const BitFieldStructDeclaration * decl_
std::vector< BitField > fields_
Friends
class TypeOracle
Additional Inherited Members
Detailed Description
Definition at line 504 of file types.h.
Constructor & Destructor Documentation
BitFieldStructType()
v8::internal::torque::BitFieldStructType::BitFieldStructType (Namespace * nspace, const Type * parent, const BitFieldStructDeclaration * decl) [inline], [private]
Definition at line 535 of file types.h.
      : Type(Kind::kBitFieldStructType, parent),
        namespace_(nspace),
        decl_(decl) {}
Member Function Documentation
ConstexprVersion()
const Type* v8::internal::torque::BitFieldStructType::ConstexprVersion () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 520 of file types.h.
                                                {
    return parent()->ConstexprVersion();
  }
References v8::internal::torque::Type::ConstexprVersion().
fields()
const std::vector<BitField>& v8::internal::torque::BitFieldStructType::fields () const [inline]
Definition at line 527 of file types.h.
{ return fields_; }
GetGeneratedTNodeTypeNameImpl()
std::string v8::internal::torque::BitFieldStructType::GetGeneratedTNodeTypeNameImpl () const [inline], [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 511 of file types.h.
                                                           {
    return parent()->GetGeneratedTNodeTypeName();
  }
GetGeneratedTypeNameImpl()
std::string v8::internal::torque::BitFieldStructType::GetGeneratedTypeNameImpl () const [inline], [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 508 of file types.h.
                                                      {
    return parent()->GetGeneratedTypeName();
  }
GetPosition()
const SourcePosition v8::internal::torque::BitFieldStructType::GetPosition () const [inline]
Definition at line 531 of file types.h.
{ return decl_->pos; }
GetTypeCheckers()
std::vector<TypeChecker> v8::internal::torque::BitFieldStructType::GetTypeCheckers () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 515 of file types.h.
                                                          {
    return parent()->GetTypeCheckers();
  }
LookupField()
const BitField & v8::internal::torque::BitFieldStructType::LookupField (const std::string & name) const
Definition at line 421 of file types.cc.
                                                                           {
  for (const BitField& field : fields_) {
    if (field.name_and_type.name == name) {
      return field;
    }
  }
  ReportError("Couldn't find bitfield ", name);
}
References name, and v8::internal::torque::ReportError().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFieldAccess().
name()
const std::string& v8::internal::torque::BitFieldStructType::name () const [inline]
Definition at line 526 of file types.h.
{ return decl_->name->value; }
RegisterField()
void v8::internal::torque::BitFieldStructType::RegisterField (BitField field) [inline]
Definition at line 524 of file types.h.
{ fields_.push_back(std::move(field)); }
SetConstexprVersion()
void v8::internal::torque::BitFieldStructType::SetConstexprVersion (const Type *) const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 519 of file types.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
SimpleNameImpl()
std::string v8::internal::torque::BitFieldStructType::SimpleNameImpl () const [inline], [override], [private], [virtual]
Implements v8::internal::torque::Type.
Definition at line 540 of file types.h.
{ return name(); }
References v8::internal::name.
ToExplicitString()
std::string v8::internal::torque::BitFieldStructType::ToExplicitString () const [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 417 of file types.cc.
                                                     {
  return "bitfield struct " + name();
}
References name.
Friends And Related Function Documentation
TypeOracle
friend class TypeOracle [friend]
Definition at line 534 of file types.h.
Member Data Documentation
decl_
const BitFieldStructDeclaration* v8::internal::torque::BitFieldStructType::decl_ [private]
Definition at line 543 of file types.h.
fields_
std::vector<BitField> v8::internal::torque::BitFieldStructType::fields_ [private]
Definition at line 544 of file types.h.
namespace_
Namespace* v8::internal::torque::BitFieldStructType::namespace_ [private]
Definition at line 542 of file types.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/types.h
/mnt/V8SourceCode/src/torque/types.cc