v8::internal::JSMap Class Reference
#include <js-collection.h>
Public Member Functions
void Rehash (Isolate *isolate)
Static Public Member Functions
static void Initialize (DirectHandle< JSMap > map, Isolate *isolate)
static void Clear (Isolate *isolate, DirectHandle< JSMap > map)
Detailed Description
Definition at line 56 of file js-collection.h.
Member Function Documentation
Clear()
void v8::internal::JSMap::Clear (Isolate * isolate, DirectHandle< JSMap > map) [static]
Definition at line 6332 of file objects.cc.
                                                           {
  Handle<OrderedHashMap> table(Cast<OrderedHashMap>(map->table()), isolate);
  table = OrderedHashMap::Clear(isolate, table);
  map->set_table(*table);
}
References v8::internal::OrderedHashTable< OrderedHashMap, 2 >::Clear().
Referenced by v8::internal::BUILTIN(), and v8::Map::Clear().
Initialize()
void v8::internal::JSMap::Initialize (DirectHandle< JSMap > map, Isolate * isolate) [static]
Definition at line 6327 of file objects.cc.
                                                                {
  DirectHandle<OrderedHashMap> table = isolate->factory()->NewOrderedHashMap();
  map->set_table(*table);
}
References v8::internal::Isolate::factory(), and v8::internal::Factory::NewOrderedHashMap().
Referenced by v8::internal::Factory::NewJSMap().
Rehash()
void v8::internal::JSMap::Rehash (Isolate * isolate)
Definition at line 6338 of file objects.cc.
                                   {
  Handle<OrderedHashMap> table_handle(Cast<OrderedHashMap>(table()), isolate);
  DirectHandle<OrderedHashMap> new_table =
      OrderedHashMap::Rehash(isolate, table_handle).ToHandleChecked();
  set_table(*new_table);
}
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-collection.h
/mnt/V8SourceCode/src/objects/objects.cc