v8::internal::compiler::CallDescriptor Class Reference
#include <linkage.h>
Public Types
enum Kind { kCallCodeObject
, kCallJSFunction
, kCallAddress
, kCallBuiltinPointer
 }
enum Flag {
kNoFlags = 0u
, kNeedsFrameState = 1u << 0
, kHasExceptionHandler = 1u << 1
, kCanUseRoots = 1u << 2
,
kInitializeRootRegister = 1u << 3
, kNoAllocate = 1u << 4
, kFixedTargetRegister = 1u << 5
, kCallerSavedRegisters = 1u << 6
,
kCallerSavedFPRegisters = 1u << 7
, kIsTailCallForTierUp = 1u << 8
, kNoFunctionDescriptor = 1u << 9
 }
using Flags = base::Flags< Flag >
Public Member Functions
CallDescriptor (Kind kind, CodeEntrypointTag tag, MachineType target_type, LinkageLocation target_loc, LocationSignature *location_sig, size_t param_slot_count, Operator::Properties properties, RegList callee_saved_registers, DoubleRegList callee_saved_fp_registers, Flags flags, const char *debug_name=``, StackArgumentOrder stack_order=StackArgumentOrder::kDefault, const RegList allocatable_registers={}, size_t return_slot_count=0, uint64_t signature_hash=kInvalidWasmSignatureHash)
CallDescriptor (const CallDescriptor &)=delete
CallDescriptor & operator= (const CallDescriptor &)=delete
Kind kind () const
CodeEntrypointTag tag () const
uint64_t signature_hash () const
uint32_t shifted_tag () const
bool IsCodeObjectCall () const
bool IsCFunctionCall () const
bool IsJSFunctionCall () const
bool IsBuiltinPointerCall () const
bool RequiresFrameAsIncoming () const
bool RequiresEntrypointTagForCall () const
size_t ReturnCount () const
size_t ParameterCount () const
size_t GPParameterCount () const
size_t FPParameterCount () const
size_t ParameterSlotCount () const
size_t ReturnSlotCount () const
size_t JSParameterCount () const
int GetStackIndexFromSlot (int slot_index) const
size_t InputCount () const
size_t FrameStateCount () const
Flags flags () const
bool NeedsFrameState () const
bool InitializeRootRegister () const
bool NeedsCallerSavedRegisters () const
bool NeedsCallerSavedFPRegisters () const
bool IsTailCallForTierUp () const
bool NoFunctionDescriptor () const
LinkageLocation GetReturnLocation (size_t index) const
LinkageLocation GetInputLocation (size_t index) const
MachineSignature * GetMachineSignature (Zone *zone) const
MachineType GetReturnType (size_t index) const
MachineType GetInputType (size_t index) const
MachineType GetParameterType (size_t index) const
StackArgumentOrder GetStackArgumentOrder () const
Operator::Properties properties () const
RegList CalleeSavedRegisters () const
DoubleRegList CalleeSavedFPRegisters () const
const char * debug_name () const
int GetStackParameterDelta (const CallDescriptor *tail_caller) const
int GetOffsetToFirstUnusedStackSlot () const
int GetOffsetToReturns () const
uint32_t GetTaggedParameterSlots () const
bool CanTailCall (const CallDescriptor *callee) const
int CalculateFixedFrameSize (CodeKind code_kind) const
RegList AllocatableRegisters () const
bool HasRestrictedAllocatableRegisters () const
EncodedCSignature ToEncodedCSignature () const
std::optional< Runtime::FunctionId > runtime_function_id () const
Static Public Attributes
static constexpr int kFlagsBitsEncodedInInstructionCode = 10
Private Member Functions
void ComputeParamCounts () const
Private Attributes
const Kind kind_
const CodeEntrypointTag tag_
const MachineType target_type_
const LinkageLocation target_loc_
const LocationSignature *const location_sig_
const size_t param_slot_count_
const size_t return_slot_count_
const Operator::Properties properties_
const RegList callee_saved_registers_
const DoubleRegList callee_saved_fp_registers_
const RegList allocatable_registers_
const Flags flags_
const StackArgumentOrder stack_order_
const char *const debug_name_
uint64_t signature_hash_
std::optional< Runtime::FunctionId > runtime_function_id_
std::optional< size_t > gp_param_count_
std::optional< size_t > fp_param_count_
Friends
class Linkage
Detailed Description
Definition at line 43 of file linkage.h.
Member Typedef Documentation
Flags
using v8::internal::compiler::CallDescriptor::Flags = base::Flags<Flag>
Definition at line 105 of file linkage.h.
Member Enumeration Documentation
Flag
enum v8::internal::compiler::CallDescriptor::Flag
Enumerator
kNoFlags
kNeedsFrameState
kHasExceptionHandler
kCanUseRoots
kInitializeRootRegister
kNoAllocate
kFixedTargetRegister
kCallerSavedRegisters
kCallerSavedFPRegisters
kIsTailCallForTierUp
kNoFunctionDescriptor
Definition at line 64 of file linkage.h.
            {
    kNoFlags = 0u,
    kNeedsFrameState = 1u << 0,
    kHasExceptionHandler = 1u << 1,
    kCanUseRoots = 1u << 2,
    // Causes the code generator to initialize the root register.
    kInitializeRootRegister = 1u << 3,
    // Does not ever try to allocate space on our heap.
    kNoAllocate = 1u << 4,
    // Use the kJavaScriptCallCodeStartRegister (fixed) register for the
    // indirect target address when calling.
    kFixedTargetRegister = 1u << 5,
    kCallerSavedRegisters = 1u << 6,
    // The kCallerSavedFPRegisters only matters (and set) when the more general
    // flag for kCallerSavedRegisters above is also set.
    kCallerSavedFPRegisters = 1u << 7,
    // Tail calls for tier up are special (in fact they are different enough
    // from normal tail calls to warrant a dedicated opcode; but they also have
    // enough similar aspects that reusing the TailCall opcode is pragmatic).
    // Specifically:
    //
    // 1. Caller and callee are both JS-linkage Code objects.
    // 2. JS runtime arguments are passed unchanged from caller to callee.
    // 3. JS runtime arguments are not attached as inputs to the TailCall node.
    // 4. Prior to the tail call, frame and register state is torn down to just
    // before the caller frame was constructed.
    // 5. Unlike normal tail calls, inlined arguments frames (if present) are
    // *not* torn down.
    //
    // In other words, behavior is identical to a jmp instruction prior caller
    // frame construction.
    kIsTailCallForTierUp = 1u << 8,
    // AIX has a function descriptor by default but it can be disabled for a
    // certain CFunction call (only used for Kind::kCallAddress).
    kNoFunctionDescriptor = 1u << 9,
    // Flags past here are *not* encoded in InstructionCode and are thus not
    // accessible from the code generator. See also
    // kFlagsBitsEncodedInInstructionCode.
  };
Kind
enum v8::internal::compiler::CallDescriptor::Kind
Enumerator
kCallCodeObject
kCallJSFunction
kCallAddress
kCallBuiltinPointer
Definition at line 47 of file linkage.h.
            {
    kCallCodeObject, // target is a Code object
    kCallJSFunction, // target is a JSFunction object
    kCallAddress, // target is a machine pointer
#if V8_ENABLE_WEBASSEMBLY // ↓ WebAssembly only
    kCallWasmCapiFunction, // target is a Wasm C API function
    kCallWasmFunction, // target is a wasm function
    kCallWasmFunctionIndirect, // target is a wasm function that will be called
                                // indirectly
    kCallWasmImportWrapper, // target is a wasm import wrapper
#endif // ↑ WebAssembly only
    kCallBuiltinPointer, // target is a builtin pointer
  };
Constructor & Destructor Documentation
CallDescriptor() [1/2]
v8::internal::compiler::CallDescriptor::CallDescriptor (Kind kind, CodeEntrypointTag tag, MachineType target_type, LinkageLocation target_loc, LocationSignature * location_sig, size_t param_slot_count, Operator::Properties properties, RegList callee_saved_registers, DoubleRegList callee_saved_fp_registers, Flags flags, const char * debug_name = ``, StackArgumentOrder stack_order = StackArgumentOrder::kDefault, const RegList allocatable_registers = {}, size_t return_slot_count = 0, uint64_t signature_hash = kInvalidWasmSignatureHash) [inline]
Definition at line 107 of file linkage.h.
                                                       {},
                 size_t return_slot_count = 0,
                 uint64_t signature_hash = kInvalidWasmSignatureHash)
      : kind_(kind),
        tag_(tag),
        target_type_(target_type),
        target_loc_(target_loc),
        location_sig_(location_sig),
        param_slot_count_(param_slot_count),
        return_slot_count_(return_slot_count),
        properties_(properties),
        callee_saved_registers_(callee_saved_registers),
        callee_saved_fp_registers_(callee_saved_fp_registers),
        allocatable_registers_(allocatable_registers),
        flags_(flags),
        stack_order_(stack_order),
        debug_name_(debug_name),
        signature_hash_(signature_hash) {
#ifdef V8_ENABLE_WEBASSEMBLY
    if (kind == Kind::kCallWasmFunctionIndirect) {
      CHECK_NE(signature_hash, kInvalidWasmSignatureHash);
    }
#endif
  }
CallDescriptor() [2/2]
v8::internal::compiler::CallDescriptor::CallDescriptor (const CallDescriptor &) [delete]
Member Function Documentation
AllocatableRegisters()
RegList v8::internal::compiler::CallDescriptor::AllocatableRegisters () const [inline]
Definition at line 331 of file linkage.h.
{ return allocatable_registers_; }
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
CalculateFixedFrameSize()
int v8::internal::compiler::CallDescriptor::CalculateFixedFrameSize (CodeKind code_kind) const
Definition at line 204 of file linkage.cc.
                                                                    {
  switch (kind_) {
    case kCallJSFunction:
      return StandardFrameConstants::kFixedSlotCount;
    case kCallAddress:
#if V8_ENABLE_WEBASSEMBLY
      if (code_kind == CodeKind::C_WASM_ENTRY) {
        return CWasmEntryFrameConstants::kFixedSlotCount;
      }
#endif // V8_ENABLE_WEBASSEMBLY
      return CommonFrameConstants::kFixedSlotCountAboveFp +
             CommonFrameConstants::kCPSlotCount;
    case kCallCodeObject:
    case kCallBuiltinPointer:
      return TypedFrameConstants::kFixedSlotCount;
#if V8_ENABLE_WEBASSEMBLY
    case kCallWasmFunction:
    case kCallWasmFunctionIndirect:
    case kCallWasmImportWrapper:
      return WasmFrameConstants::kFixedSlotCount;
    case kCallWasmCapiFunction:
      return WasmExitFrameConstants::kFixedSlotCount;
#endif // V8_ENABLE_WEBASSEMBLY
  }
  UNREACHABLE();
}
References kCallAddress, kCallBuiltinPointer, kCallCodeObject, kCallJSFunction, v8::internal::CommonFrameConstants::kCPSlotCount, v8::internal::StandardFrameConstants::kFixedSlotCount, v8::internal::TypedFrameConstants::kFixedSlotCount, v8::internal::CommonFrameConstants::kFixedSlotCountAboveFp, kind_, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::TFPipelineData::InitializeFrameData(), and v8::internal::compiler::turboshaft::PipelineData::InitializeFrameData().
CalleeSavedFPRegisters()
DoubleRegList v8::internal::compiler::CallDescriptor::CalleeSavedFPRegisters () const [inline]
Definition at line 303 of file linkage.h.
                                               {
    return callee_saved_fp_registers_;
  }
Referenced by v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::turboshaft::PipelineData::InitializeInstructionComponent(), and v8::internal::compiler::TFPipelineData::InitializeInstructionSequence().
CalleeSavedRegisters()
RegList v8::internal::compiler::CallDescriptor::CalleeSavedRegisters () const [inline]
Definition at line 300 of file linkage.h.
{ return callee_saved_registers_; }
Referenced by v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::AdjustStackPointerForTailCall().
CanTailCall()
bool v8::internal::compiler::CallDescriptor::CanTailCall (const CallDescriptor * callee) const
Definition at line 182 of file linkage.cc.
                                                                   {
  if (ReturnCount() != callee->ReturnCount()) return false;
  const int stack_returns_delta =
      GetOffsetToReturns() - callee->GetOffsetToReturns();
  for (size_t i = 0; i < ReturnCount(); ++i) {
    if (GetReturnLocation(i).IsCallerFrameSlot() &&
        callee->GetReturnLocation(i).IsCallerFrameSlot()) {
      if (GetReturnLocation(i).AsCallerFrameSlot() + stack_returns_delta !=
          callee->GetReturnLocation(i).AsCallerFrameSlot()) {
        return false;
      }
    } else if (!LinkageLocation::IsSameLocation(GetReturnLocation(i),
                                                callee->GetReturnLocation(i))) {
      return false;
    }
  }
  return true;
}
References v8::internal::LinkageLocation::AsCallerFrameSlot(), GetOffsetToReturns(), GetReturnLocation(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::LinkageLocation::IsCallerFrameSlot(), v8::internal::LinkageLocation::IsSameLocation(), and ReturnCount().
ComputeParamCounts()
void v8::internal::compiler::CallDescriptor::ComputeParamCounts () const [private]
Definition at line 262 of file linkage.cc.
                                              {
  gp_param_count_ = 0;
  fp_param_count_ = 0;
  for (size_t i = 0; i < ParameterCount(); ++i) {
    if (IsFloatingPoint(GetParameterType(i).representation())) {
      ++fp_param_count_.value();
    } else {
      ++gp_param_count_.value();
    }
  }
}
References fp_param_count_, GetParameterType(), gp_param_count_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsFloatingPoint(), and ParameterCount().
debug_name()
const char* v8::internal::compiler::CallDescriptor::debug_name () const [inline]
Definition at line 307 of file linkage.h.
{ return debug_name_; }
Referenced by v8::internal::compiler::operator<<().
flags()
Flags v8::internal::compiler::CallDescriptor::flags () const [inline]
Definition at line 255 of file linkage.h.
{ return flags_; }
Referenced by v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::CanAllocate(), v8::internal::compiler::InstructionSelector::CanUseRootsRegister(), v8::internal::compiler::CodeGenerator::IsMaterializableFromRoot(), v8::internal::compiler::turboshaft::fast_hash< TSCallDescriptor >::operator()(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::MemoryOptimizer::VisitCall(), and v8::internal::compiler::InstructionSelector::VisitCall().
FPParameterCount()
size_t v8::internal::compiler::CallDescriptor::FPParameterCount () const [inline]
Definition at line 220 of file linkage.h.
                                  {
    if (!fp_param_count_) {
      ComputeParamCounts();
    }
    return fp_param_count_.value();
  }
Referenced by v8::internal::compiler::turboshaft::fast_hash< TSCallDescriptor >::operator()(), and v8::internal::compiler::InstructionSelector::VisitCall().
FrameStateCount()
size_t v8::internal::compiler::CallDescriptor::FrameStateCount () const [inline]
Definition at line 253 of file linkage.h.
{ return NeedsFrameState() ? 1 : 0; }
Referenced by v8::internal::compiler::CommonOperatorBuilder::Call(), v8::internal::compiler::CallBuffer::frame_state_count(), v8::internal::compiler::operator<<(), and v8::internal::compiler::CommonOperatorBuilder::TailCall().
GetInputLocation()
LinkageLocation v8::internal::compiler::CallDescriptor::GetInputLocation (size_t index) const [inline]
Definition at line 274 of file linkage.h.
                                                       {
    if (index == 0) return target_loc_;
    return location_sig_->GetParam(index - 1);
  }
References v8::internal::index.
Referenced by GetOffsetToFirstUnusedStackSlot(), GetTaggedParameterSlots(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), and v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::PrepareStackTransfers().
GetInputType()
MachineType v8::internal::compiler::CallDescriptor::GetInputType (size_t index) const [inline]
Definition at line 285 of file linkage.h.
                                               {
    if (index == 0) return target_type_;
    return location_sig_->GetParam(index - 1).GetType();
  }
References v8::internal::index.
Referenced by v8::internal::compiler::RepresentationSelector::VisitFastApiCall().
GetMachineSignature()
MachineSignature * v8::internal::compiler::CallDescriptor::GetMachineSignature (Zone * zone) const
Definition at line 81 of file linkage.cc.
                                                                      {
  size_t param_count = ParameterCount();
  size_t return_count = ReturnCount();
  MachineType* types =
      zone->AllocateArray<MachineType>(param_count + return_count);
  int current = 0;
  for (size_t i = 0; i < return_count; ++i) {
    types[current++] = GetReturnType(i);
  }
  for (size_t i = 0; i < param_count; ++i) {
    types[current++] = GetParameterType(i);
  }
  return zone->New<MachineSignature>(return_count, param_count, types);
}
References v8::internal::Zone::AllocateArray(), GetParameterType(), GetReturnType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Zone::New(), ParameterCount(), and ReturnCount().
GetOffsetToFirstUnusedStackSlot()
int v8::internal::compiler::CallDescriptor::GetOffsetToFirstUnusedStackSlot () const
Definition at line 113 of file linkage.cc.
                                                          {
  int offset = kFirstCallerSlotOffset;
  for (size_t i = 0; i < InputCount(); ++i) {
    LinkageLocation operand = GetInputLocation(i);
    if (!operand.IsRegister()) {
      DCHECK(operand.IsCallerFrameSlot());
      int slot_offset = -operand.GetLocation();
      offset = std::max(offset, slot_offset + operand.GetSizeInPointers());
    }
  }
  return offset;
}
References v8::internal::DCHECK(), GetInputLocation(), v8::internal::LinkageLocation::GetLocation(), v8::internal::LinkageLocation::GetSizeInPointers(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, InputCount(), v8::internal::LinkageLocation::IsCallerFrameSlot(), v8::internal::LinkageLocation::IsRegister(), and v8::internal::compiler::anonymous_namespace{linkage.cc}::kFirstCallerSlotOffset.
Referenced by GetOffsetToReturns().
GetOffsetToReturns()
int v8::internal::compiler::CallDescriptor::GetOffsetToReturns () const
Definition at line 126 of file linkage.cc.
                                             {
  // Find the return slot with the least offset relative to the callee.
  int offset = kNoCallerSlotOffset;
  for (size_t i = 0; i < ReturnCount(); ++i) {
    LinkageLocation operand = GetReturnLocation(i);
    if (!operand.IsRegister()) {
      DCHECK(operand.IsCallerFrameSlot());
      int slot_offset = -operand.GetLocation();
      offset = std::min(offset, slot_offset);
    }
  }
  // If there was a return slot, return the offset minus 1 slot.
  if (offset != kNoCallerSlotOffset) {
    return offset - 1;
  }
  // Otherwise, return the first slot after the parameters area, including
  // optional padding slots.
  int last_argument_slot = GetOffsetToFirstUnusedStackSlot() - 1;
  offset = AddArgumentPaddingSlots(last_argument_slot);
  DCHECK_IMPLIES(offset == 0, ParameterSlotCount() == 0);
  return offset;
}
References v8::internal::AddArgumentPaddingSlots(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::LinkageLocation::GetLocation(), GetOffsetToFirstUnusedStackSlot(), GetReturnLocation(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::LinkageLocation::IsCallerFrameSlot(), v8::internal::LinkageLocation::IsRegister(), v8::internal::compiler::anonymous_namespace{linkage.cc}::kNoCallerSlotOffset, ParameterSlotCount(), and ReturnCount().
Referenced by CanTailCall(), v8::internal::compiler::InstructionSelector::EmitPrepareResults(), v8::internal::wasm::LiftoffAssembler::FinishCall(), and GetStackParameterDelta().
GetParameterType()
MachineType v8::internal::compiler::CallDescriptor::GetParameterType (size_t index) const [inline]
Definition at line 290 of file linkage.h.
                                                   {
    return location_sig_->GetParam(index).GetType();
  }
References v8::internal::index.
Referenced by ComputeParamCounts(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::BuiltinsReducer< Next >::EmitBuiltinProlog(), GetMachineSignature(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), and ToEncodedCSignature().
GetReturnLocation()
LinkageLocation v8::internal::compiler::CallDescriptor::GetReturnLocation (size_t index) const [inline]
Definition at line 270 of file linkage.h.
                                                        {
    return location_sig_->GetReturn(index);
  }
References v8::internal::index.
Referenced by CanTailCall(), v8::internal::wasm::LiftoffAssembler::FinishCall(), GetOffsetToReturns(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocationsMultiReturn(), and v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return().
GetReturnType()
MachineType v8::internal::compiler::CallDescriptor::GetReturnType (size_t index) const [inline]
Definition at line 281 of file linkage.h.
                                                {
    return location_sig_->GetReturn(index).GetType();
  }
References v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::CheckPairOrPairOp(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), GetMachineSignature(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), and ToEncodedCSignature().
GetStackArgumentOrder()
StackArgumentOrder v8::internal::compiler::CallDescriptor::GetStackArgumentOrder () const [inline]
Definition at line 294 of file linkage.h.
{ return stack_order_; }
GetStackIndexFromSlot()
int v8::internal::compiler::CallDescriptor::GetStackIndexFromSlot (int slot_index) const [inline]
Definition at line 239 of file linkage.h.
                                                  {
    switch (GetStackArgumentOrder()) {
      case StackArgumentOrder::kDefault:
        return -slot_index - 1;
      case StackArgumentOrder::kJS:
        return slot_index + static_cast<int>(ParameterSlotCount());
    }
  }
References v8::internal::kDefault, and v8::internal::kJS.
Referenced by v8::internal::compiler::InstructionSelector::InitializeCallBuffer().
GetStackParameterDelta()
int v8::internal::compiler::CallDescriptor::GetStackParameterDelta (const CallDescriptor * tail_caller) const
Definition at line 96 of file linkage.cc.
                                             {
  // In the IsTailCallForTierUp case, the callee has
  // identical linkage and runtime arguments to the caller, thus the stack
  // parameter delta is 0. We don't explicitly pass the runtime arguments as
  // inputs to the TailCall node, since they already exist on the stack.
  if (IsTailCallForTierUp()) return 0;
  // Add padding if necessary before computing the stack parameter delta.
  int callee_slots_above_sp = AddArgumentPaddingSlots(GetOffsetToReturns());
  int tail_caller_slots_above_sp =
      AddArgumentPaddingSlots(tail_caller->GetOffsetToReturns());
  int stack_param_delta = callee_slots_above_sp - tail_caller_slots_above_sp;
  DCHECK(!ShouldPadArguments(stack_param_delta));
  return stack_param_delta;
}
References v8::internal::AddArgumentPaddingSlots(), v8::internal::DCHECK(), GetOffsetToReturns(), IsTailCallForTierUp(), and v8::internal::ShouldPadArguments().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallRefImpl().
GetTaggedParameterSlots()
uint32_t v8::internal::compiler::CallDescriptor::GetTaggedParameterSlots () const
Definition at line 151 of file linkage.cc.
                                                       {
  uint32_t count = 0;
  uint32_t untagged_count = 0;
  uint32_t first_offset = kMaxInt;
  for (size_t i = 0; i < InputCount(); ++i) {
    LinkageLocation operand = GetInputLocation(i);
    if (!operand.IsRegister()) {
      if (operand.GetType().IsTagged()) {
        ++count;
        // Caller frame slots have negative indices and start at -1. Flip it
        // back to a positive offset (to be added to the frame's SP to find the
        // slot).
        int slot_offset = -operand.GetLocation() - 1;
        DCHECK_GE(slot_offset, 0);
        first_offset =
            std::min(first_offset, static_cast<uint32_t>(slot_offset));
      } else {
        untagged_count += operand.GetSizeInPointers();
      }
    }
  }
  if (count == 0) {
    // If we don't have any tagged parameter slots, still initialize the offset
    // to point past the untagged parameter slots, so that
    // offset + count == stack slot count.
    first_offset = untagged_count;
  }
  DCHECK(first_offset != kMaxInt);
  return (first_offset << 16) | (count & 0xFFFFu);
}
References v8::internal::DCHECK(), DCHECK_GE, GetInputLocation(), v8::internal::LinkageLocation::GetLocation(), v8::internal::LinkageLocation::GetSizeInPointers(), v8::internal::LinkageLocation::GetType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, InputCount(), v8::internal::LinkageLocation::IsRegister(), v8::internal::MachineType::IsTagged(), and v8::internal::kMaxInt.
GPParameterCount()
size_t v8::internal::compiler::CallDescriptor::GPParameterCount () const [inline]
Definition at line 212 of file linkage.h.
                                  {
    if (!gp_param_count_) {
      ComputeParamCounts();
    }
    return gp_param_count_.value();
  }
Referenced by v8::internal::compiler::turboshaft::fast_hash< TSCallDescriptor >::operator()(), and v8::internal::compiler::InstructionSelector::VisitCall().
HasRestrictedAllocatableRegisters()
bool v8::internal::compiler::CallDescriptor::HasRestrictedAllocatableRegisters () const [inline]
Definition at line 333 of file linkage.h.
                                                 {
    return !allocatable_registers_.is_empty();
  }
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
InitializeRootRegister()
bool v8::internal::compiler::CallDescriptor::InitializeRootRegister () const [inline]
Definition at line 258 of file linkage.h.
                                      {
    return flags() & kInitializeRootRegister;
  }
References v8::internal::flags.
InputCount()
size_t v8::internal::compiler::CallDescriptor::InputCount () const [inline]
Definition at line 251 of file linkage.h.
{ return 1 + location_sig_->parameter_count(); }
Referenced by v8::internal::compiler::CommonOperatorBuilder::Call(), GetOffsetToFirstUnusedStackSlot(), GetTaggedParameterSlots(), v8::internal::compiler::CallBuffer::input_count(), v8::internal::compiler::operator<<(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::PrepareStackTransfers(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), and v8::internal::compiler::CommonOperatorBuilder::TailCall().
IsBuiltinPointerCall()
bool v8::internal::compiler::CallDescriptor::IsBuiltinPointerCall () const [inline]
Definition at line 190 of file linkage.h.
{ return kind_ == kCallBuiltinPointer; }
References v8::internal::kCallBuiltinPointer.
Referenced by v8::internal::compiler::turboshaft::CallOp::inputs_rep().
IsCFunctionCall()
bool v8::internal::compiler::CallDescriptor::IsCFunctionCall () const [inline]
Definition at line 161 of file linkage.h.
{ return kind_ == kCallAddress; }
Referenced by v8::internal::compiler::InstructionSelector::EmitPrepareArguments(), and v8::internal::compiler::InstructionSelector::EmitPrepareResults().
IsCodeObjectCall()
bool v8::internal::compiler::CallDescriptor::IsCodeObjectCall () const [inline]
Definition at line 158 of file linkage.h.
{ return kind_ == kCallCodeObject; }
References v8::internal::kCallCodeObject.
Referenced by v8::internal::compiler::turboshaft::CallOp::inputs_rep().
IsJSFunctionCall()
bool v8::internal::compiler::CallDescriptor::IsJSFunctionCall () const [inline]
Definition at line 164 of file linkage.h.
{ return kind_ == kCallJSFunction; }
Referenced by v8::internal::compiler::Linkage::GetOsrValueLocation(), v8::internal::compiler::Linkage::GetParameterSecondaryLocation(), v8::internal::compiler::turboshaft::CallOp::inputs_rep(), v8::internal::compiler::CodeAssembler::IsJSFunctionCall(), v8::internal::compiler::Linkage::ParameterHasSecondaryLocation(), v8::internal::compiler::RawMachineAssembler::RawMachineAssembler(), and v8::internal::compiler::InstructionSelector::VisitCall().
IsTailCallForTierUp()
bool v8::internal::compiler::CallDescriptor::IsTailCallForTierUp () const [inline]
Definition at line 267 of file linkage.h.
{ return flags() & kIsTailCallForTierUp; }
References v8::internal::flags.
Referenced by GetStackParameterDelta().
JSParameterCount()
size_t v8::internal::compiler::CallDescriptor::JSParameterCount () const [inline]
Definition at line 234 of file linkage.h.
                                  {
    DCHECK(IsJSFunctionCall());
    return param_slot_count_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::Linkage::GetOsrValueLocation().
kind()
Kind v8::internal::compiler::CallDescriptor::kind () const [inline]
Definition at line 143 of file linkage.h.
{ return kind_; }
Referenced by v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::IsBuiltinCall(), v8::internal::compiler::turboshaft::fast_hash< TSCallDescriptor >::operator()(), v8::internal::compiler::operator<<(), v8::internal::compiler::anonymous_namespace{basic-block-instrumentor.cc}::StoreBuiltinCallForNode(), and v8::internal::compiler::InstructionSelector::VisitCall().
NeedsCallerSavedFPRegisters()
bool v8::internal::compiler::CallDescriptor::NeedsCallerSavedFPRegisters () const [inline]
Definition at line 264 of file linkage.h.
                                           {
    return flags() & kCallerSavedFPRegisters;
  }
References v8::internal::flags.
Referenced by v8::internal::compiler::InstructionSelector::VisitCall().
NeedsCallerSavedRegisters()
bool v8::internal::compiler::CallDescriptor::NeedsCallerSavedRegisters () const [inline]
Definition at line 261 of file linkage.h.
                                         {
    return flags() & kCallerSavedRegisters;
  }
References v8::internal::flags.
Referenced by v8::internal::compiler::InstructionSelector::VisitCall().
NeedsFrameState()
bool v8::internal::compiler::CallDescriptor::NeedsFrameState () const [inline]
Definition at line 257 of file linkage.h.
{ return flags() & kNeedsFrameState; }
References v8::internal::flags.
Referenced by v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin(), v8::internal::compiler::RawMachineAssembler::CallN(), v8::internal::compiler::RawMachineAssembler::CallNWithFrameState(), v8::internal::compiler::turboshaft::CallOp::HasFrameState(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), and v8::internal::compiler::InstructionSelector::VisitCall().
NoFunctionDescriptor()
bool v8::internal::compiler::CallDescriptor::NoFunctionDescriptor () const [inline]
Definition at line 268 of file linkage.h.
{ return flags() & kNoFunctionDescriptor; }
References v8::internal::flags, and v8::internal::compiler::anonymous_namespace{raw-machine-assembler.cc}::kNoFunctionDescriptor.
Referenced by v8::internal::compiler::InstructionSelector::VisitCall().
operator=()
CallDescriptor& v8::internal::compiler::CallDescriptor::operator= (const CallDescriptor &) [delete]
ParameterCount()
size_t v8::internal::compiler::CallDescriptor::ParameterCount () const [inline]
Definition at line 209 of file linkage.h.
{ return location_sig_->parameter_count(); }
Referenced by v8::internal::compiler::RawMachineAssembler::CallN(), v8::internal::compiler::RawMachineAssembler::CallNWithFrameState(), ComputeParamCounts(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::BuiltinsReducer< Next >::EmitBuiltinProlog(), v8::internal::compiler::InstructionSelector::EmitPrepareArguments(), v8::internal::compiler::SimplifiedOperatorBuilder::FastApiCall(), GetMachineSignature(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), v8::internal::compiler::turboshaft::fast_hash< TSCallDescriptor >::operator()(), v8::internal::compiler::FastApiCallNode::SlowCallArgumentCount(), v8::internal::compiler::GraphAssembler::TailCall(), v8::internal::compiler::RawMachineAssembler::TailCallN(), ToEncodedCSignature(), and v8::internal::compiler::RepresentationSelector::VisitFastApiCall().
ParameterSlotCount()
size_t v8::internal::compiler::CallDescriptor::ParameterSlotCount () const [inline]
Definition at line 228 of file linkage.h.
{ return param_slot_count_; }
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallRefImpl(), GetOffsetToReturns(), v8::internal::compiler::CodeGenerator::GetStackCheckOffset(), v8::internal::compiler::turboshaft::fast_hash< TSCallDescriptor >::operator()(), v8::internal::compiler::operator<<(), v8::internal::wasm::LiftoffAssembler::PrepareBuiltinCall(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), and v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::WasmStackCheck().
properties()
Operator::Properties v8::internal::compiler::CallDescriptor::properties () const [inline]
Definition at line 297 of file linkage.h.
{ return properties_; }
Referenced by v8::internal::compiler::CommonOperatorBuilder::Call(), and v8::internal::compiler::CommonOperatorBuilder::TailCall().
RequiresEntrypointTagForCall()
bool v8::internal::compiler::CallDescriptor::RequiresEntrypointTagForCall () const [inline]
Definition at line 201 of file linkage.h.
{ return IsCodeObjectCall(); }
Referenced by v8::internal::compiler::InstructionSelector::VisitCall().
RequiresFrameAsIncoming()
bool v8::internal::compiler::CallDescriptor::RequiresFrameAsIncoming () const [inline]
Definition at line 192 of file linkage.h.
                                       {
    if (IsCFunctionCall() || IsJSFunctionCall()) return true;
#if V8_ENABLE_WEBASSEMBLY
    if (IsAnyWasmFunctionCall()) return true;
#endif // V8_ENABLE_WEBASSEMBLY
    if (CalleeSavedRegisters() != kNoCalleeSaved) return true;
    return false;
  }
References v8::internal::compiler::kNoCalleeSaved.
Referenced by v8::internal::compiler::turboshaft::PipelineData::InitializeInstructionComponent(), and v8::internal::compiler::TFPipelineData::InitializeInstructionSequence().
ReturnCount()
size_t v8::internal::compiler::CallDescriptor::ReturnCount () const [inline]
Definition at line 204 of file linkage.h.
{ return location_sig_->return_count(); }
Referenced by v8::internal::compiler::CommonOperatorBuilder::Call(), v8::internal::compiler::CallBuffer::CallBuffer(), CanTailCall(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::CheckPairOrPairOp(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::wasm::LiftoffAssembler::FinishCall(), GetMachineSignature(), GetOffsetToReturns(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), v8::internal::compiler::turboshaft::fast_hash< TSCallDescriptor >::operator()(), v8::internal::compiler::operator<<(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), ToEncodedCSignature(), and v8::internal::compiler::InstructionSelector::VisitReturn().
ReturnSlotCount()
size_t v8::internal::compiler::CallDescriptor::ReturnSlotCount () const [inline]
Definition at line 231 of file linkage.h.
{ return return_slot_count_; }
Referenced by v8::internal::wasm::LiftoffAssembler::FinishCall(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::turboshaft::fast_hash< TSCallDescriptor >::operator()(), and v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return().
runtime_function_id()
std::optional<Runtime::FunctionId> v8::internal::compiler::CallDescriptor::runtime_function_id () const [inline]
Definition at line 339 of file linkage.h.
                                                             {
    return runtime_function_id_;
  }
Referenced by v8::internal::compiler::turboshaft::AnalyzeCall().
shifted_tag()
uint32_t v8::internal::compiler::CallDescriptor::shifted_tag () const [inline]
Definition at line 152 of file linkage.h.
                               {
    static_assert(kCodeEntrypointTagShift >= 32);
    return tag_ >> kCodeEntrypointTagShift;
  }
References v8::internal::kCodeEntrypointTagShift.
Referenced by v8::internal::compiler::InstructionSelector::VisitCall().
signature_hash()
uint64_t v8::internal::compiler::CallDescriptor::signature_hash () const
Definition at line 231 of file linkage.cc.
                                              {
#if V8_ENABLE_WEBASSEMBLY
  DCHECK_EQ(kind_, kCallWasmFunctionIndirect);
#endif
  return signature_hash_;
}
References DCHECK_EQ, kind_, and signature_hash_.
Referenced by v8::internal::compiler::InstructionSelector::VisitCall().
tag()
CodeEntrypointTag v8::internal::compiler::CallDescriptor::tag () const [inline]
Definition at line 146 of file linkage.h.
{ return tag_; }
Referenced by v8::internal::compiler::turboshaft::fast_hash< TSCallDescriptor >::operator()().
ToEncodedCSignature()
EncodedCSignature v8::internal::compiler::CallDescriptor::ToEncodedCSignature () const
Definition at line 238 of file linkage.cc.
                                                            {
  int parameter_count = static_cast<int>(ParameterCount());
  EncodedCSignature sig(parameter_count);
  CHECK_LT(parameter_count, EncodedCSignature::kInvalidParamCount);
  for (int i = 0; i < parameter_count; ++i) {
    if (IsFloatingPoint(GetParameterType(i).representation())) {
      sig.SetFloat(i);
    }
  }
  if (ReturnCount() > 0) {
    DCHECK_EQ(1, ReturnCount());
    if (IsFloatingPoint(GetReturnType(0).representation())) {
      if (GetReturnType(0).representation() ==
          MachineRepresentation::kFloat64) {
        sig.SetReturnFloat64();
      } else {
        sig.SetReturnFloat32();
      }
    }
  }
  return sig;
}
References CHECK_LT, DCHECK_EQ, GetParameterType(), GetReturnType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsFloatingPoint(), v8::internal::kFloat64, v8::internal::EncodedCSignature::kInvalidParamCount, ParameterCount(), ReturnCount(), and v8::internal::sig.
Friends And Related Function Documentation
Linkage
friend class Linkage [friend]
Definition at line 346 of file linkage.h.
Member Data Documentation
allocatable_registers_
const RegList v8::internal::compiler::CallDescriptor::allocatable_registers_ [private]
Definition at line 360 of file linkage.h.
callee_saved_fp_registers_
const DoubleRegList v8::internal::compiler::CallDescriptor::callee_saved_fp_registers_ [private]
Definition at line 357 of file linkage.h.
callee_saved_registers_
const RegList v8::internal::compiler::CallDescriptor::callee_saved_registers_ [private]
Definition at line 356 of file linkage.h.
debug_name_
const char* const v8::internal::compiler::CallDescriptor::debug_name_ [private]
Definition at line 363 of file linkage.h.
flags_
const Flags v8::internal::compiler::CallDescriptor::flags_ [private]
Definition at line 361 of file linkage.h.
fp_param_count_
std::optional<size_t> v8::internal::compiler::CallDescriptor::fp_param_count_ [mutable], [private]
Definition at line 372 of file linkage.h.
Referenced by ComputeParamCounts().
gp_param_count_
std::optional<size_t> v8::internal::compiler::CallDescriptor::gp_param_count_ [mutable], [private]
Definition at line 371 of file linkage.h.
Referenced by ComputeParamCounts().
kFlagsBitsEncodedInInstructionCode
constexpr int v8::internal::compiler::CallDescriptor::kFlagsBitsEncodedInInstructionCode = 10 [static], [constexpr]
Definition at line 63 of file linkage.h.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::EncodeCallDescriptorFlags(), and v8::internal::compiler::Instruction::HasCallDescriptorFlag().
kind_
const Kind v8::internal::compiler::CallDescriptor::kind_ [private]
Definition at line 348 of file linkage.h.
Referenced by CalculateFixedFrameSize(), and signature_hash().
location_sig_
const LocationSignature* const v8::internal::compiler::CallDescriptor::location_sig_ [private]
Definition at line 352 of file linkage.h.
param_slot_count_
const size_t v8::internal::compiler::CallDescriptor::param_slot_count_ [private]
Definition at line 353 of file linkage.h.
properties_
const Operator::Properties v8::internal::compiler::CallDescriptor::properties_ [private]
Definition at line 355 of file linkage.h.
return_slot_count_
const size_t v8::internal::compiler::CallDescriptor::return_slot_count_ [private]
Definition at line 354 of file linkage.h.
runtime_function_id_
std::optional<Runtime::FunctionId> v8::internal::compiler::CallDescriptor::runtime_function_id_ [private]
Definition at line 369 of file linkage.h.
Referenced by v8::internal::compiler::Linkage::GetRuntimeCallDescriptor().
signature_hash_
uint64_t v8::internal::compiler::CallDescriptor::signature_hash_ [private]
Definition at line 365 of file linkage.h.
Referenced by signature_hash().
stack_order_
const StackArgumentOrder v8::internal::compiler::CallDescriptor::stack_order_ [private]
Definition at line 362 of file linkage.h.
tag_
const CodeEntrypointTag v8::internal::compiler::CallDescriptor::tag_ [private]
Definition at line 349 of file linkage.h.
target_loc_
const LinkageLocation v8::internal::compiler::CallDescriptor::target_loc_ [private]
Definition at line 351 of file linkage.h.
target_type_
const MachineType v8::internal::compiler::CallDescriptor::target_type_ [private]
Definition at line 350 of file linkage.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/linkage.h
/mnt/V8SourceCode/src/compiler/linkage.cc