v8::internal::MessageHandler Class Reference
#include <messages.h>
Static Public Member Functions
static V8_EXPORT_PRIVATE Handle< JSMessageObject > MakeMessageObject (Isolate *isolate, MessageTemplate type, const MessageLocation *location, DirectHandle< Object > argument, DirectHandle< StackTraceInfo > stack_trace=DirectHandle< StackTraceInfo >::null())
static V8_EXPORT_PRIVATE void ReportMessage (Isolate *isolate, const MessageLocation *loc, DirectHandle< JSMessageObject > message)
static void DefaultMessageReport (Isolate *isolate, const MessageLocation *loc, DirectHandle< Object > message_obj)
static DirectHandle< String > GetMessage (Isolate *isolate, DirectHandle< Object > data)
static std::unique_ptr< char[]> GetLocalizedMessage (Isolate *isolate, DirectHandle< Object > data)
Static Private Member Functions
static void ReportMessageNoExceptions (Isolate *isolate, const MessageLocation *loc, DirectHandle< Object > message_obj, Local< Value > api_exception_obj)
Detailed Description
Definition at line 171 of file messages.h.
Member Function Documentation
DefaultMessageReport()
void v8::internal::MessageHandler::DefaultMessageReport (Isolate * isolate, const MessageLocation * loc, DirectHandle< Object > message_obj) [static]
Definition at line 61 of file messages.cc.
                                                                            {
  std::unique_ptr<char[]> str = GetLocalizedMessage(isolate, message_obj);
  if (loc == nullptr) {
    PrintF("%s\n", str.get());
  } else {
    HandleScope scope(isolate);
    DirectHandle<Object> data(loc->script()->name(), isolate);
    std::unique_ptr<char[]> data_str;
    if (IsString(*data)) data_str = Cast<String>(data)->ToCString();
    PrintF("%s:%i: %s\n", data_str ? data_str.get() : "<unknown>",
           loc->start_pos(), str.get());
  }
}
References GetLocalizedMessage(), v8::internal::loc, and v8::internal::PrintF().
Referenced by ReportMessageNoExceptions().
GetLocalizedMessage()
std::unique_ptr< char[]> v8::internal::MessageHandler::GetLocalizedMessage (Isolate * isolate, DirectHandle< Object > data) [static]
Definition at line 195 of file messages.cc.
                                                 {
  HandleScope scope(isolate);
  return GetMessage(isolate, data)->ToCString();
}
References GetMessage().
Referenced by v8::internal::Isolate::CreateMessageOrAbort(), and DefaultMessageReport().
GetMessage()
DirectHandle< String > v8::internal::MessageHandler::GetMessage (Isolate * isolate, DirectHandle< Object > data) [static]
Definition at line 187 of file messages.cc.
                                                                           {
  DirectHandle<JSMessageObject> message = Cast<JSMessageObject>(data);
  DirectHandle<Object> arg{message->argument(), isolate};
  return MessageFormatter::Format(isolate, message->type(),
                                  base::VectorOf({arg}));
}
References v8::internal::MessageFormatter::Format(), and v8::base::VectorOf().
Referenced by v8::Message::Get(), and GetLocalizedMessage().
MakeMessageObject()
Handle< JSMessageObject > v8::internal::MessageHandler::MakeMessageObject (Isolate * isolate, MessageTemplate type, const MessageLocation * location, DirectHandle< Object > argument, DirectHandle< StackTraceInfo > stack_trace = DirectHandle<StackTraceInfo>::null()) [static]
Definition at line 77 of file messages.cc.
                                                                             {
  int start = -1;
  int end = -1;
  int bytecode_offset = -1;
  DirectHandle<Script> script_handle = isolate->factory()->empty_script();
  DirectHandle<SharedFunctionInfo> shared_info;
  if (location != nullptr && !v8_flags.correctness_fuzzer_suppressions) {
    start = location->start_pos();
    end = location->end_pos();
    script_handle = location->script();
    bytecode_offset = location->bytecode_offset();
    shared_info = location->shared();
  }
  return isolate->factory()->NewJSMessageObject(message, argument, start, end,
                                                shared_info, bytecode_offset,
                                                script_handle, stack_trace);
}
References v8::internal::MessageLocation::bytecode_offset(), v8::internal::compiler::end(), v8::internal::MessageLocation::end_pos(), v8::internal::Isolate::factory(), v8::internal::Factory::NewJSMessageObject(), v8::internal::MessageLocation::script(), v8::internal::MessageLocation::shared(), v8::internal::MessageLocation::start_pos(), and v8::internal::v8_flags.
Referenced by v8::internal::Isolate::CreateMessage(), v8::internal::Isolate::CreateMessageFromException(), v8::internal::SourceTextModule::GetStalledTopLevelAwaitMessages(), v8::internal::anonymous_namespace{asm-js.cc}::Report(), and v8::internal::PendingCompilationErrorHandler::ReportWarnings().
ReportMessage()
void v8::internal::MessageHandler::ReportMessage (Isolate * isolate, const MessageLocation * loc, DirectHandle< JSMessageObject > message) [static]
Definition at line 98 of file messages.cc.
                                                                          {
  v8::Local<v8::Message> api_message_obj = v8::Utils::MessageToLocal(message);
  if (api_message_obj->ErrorLevel() != v8::Isolate::kMessageError) {
    ReportMessageNoExceptions(isolate, loc, message, v8::Local<v8::Value>());
    return;
  }
  // We are calling into embedder's code which can throw exceptions.
  // Thus we need to save current exception state, reset it to the clean one
  // and ignore scheduled exceptions callbacks can throw.
  // We pass the exception object into the message handler callback though.
  DirectHandle<Object> exception = isolate->factory()->undefined_value();
  if (isolate->has_exception()) {
    exception = direct_handle(isolate->exception(), isolate);
  }
  Isolate::ExceptionScope exception_scope(isolate);
  isolate->clear_pending_message();
  // Turn the exception on the message into a string if it is an object.
  if (IsJSObject(message->argument())) {
    HandleScope scope(isolate);
    DirectHandle<Object> argument(message->argument(), isolate);
    MaybeDirectHandle<Object> maybe_stringified;
    DirectHandle<Object> stringified;
    // Make sure we don't leak uncaught internally generated Error objects.
    if (IsJSError(*argument)) {
      maybe_stringified = Object::NoSideEffectsToString(isolate, argument);
    } else {
      v8::TryCatch catcher(reinterpret_cast<v8::Isolate*>(isolate));
      catcher.SetVerbose(false);
      catcher.SetCaptureMessage(false);
      maybe_stringified = Object::ToString(isolate, argument);
    }
    if (!maybe_stringified.ToHandle(&stringified)) {
      isolate->clear_pending_message();
      stringified = isolate->factory()->exception_string();
    }
    message->set_argument(*stringified);
  }
  v8::Local<v8::Value> api_exception_obj = v8::Utils::ToLocal(exception);
  ReportMessageNoExceptions(isolate, loc, message, api_exception_obj);
}
References v8::internal::Isolate::clear_pending_message(), v8::internal::direct_handle(), v8::internal::Isolate::exception(), v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), v8::Isolate::kMessageError, v8::internal::loc, v8::internal::Object::NoSideEffectsToString(), ReportMessageNoExceptions(), v8::TryCatch::SetCaptureMessage(), v8::TryCatch::SetVerbose(), v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::Value::ToString().
Referenced by v8::internal::anonymous_namespace{asm-js.cc}::Report(), v8::internal::Isolate::ReportPendingMessages(), v8::internal::PendingCompilationErrorHandler::ReportWarnings(), and v8::internal::RUNTIME_FUNCTION().
ReportMessageNoExceptions()
void v8::internal::MessageHandler::ReportMessageNoExceptions (Isolate * isolate, const MessageLocation * loc, DirectHandle< Object > message_obj, Local< Value > api_exception_obj) [static], [private]
Definition at line 149 of file messages.cc.
                                        {
  v8::Local<v8::Message> api_message_obj = v8::Utils::MessageToLocal(message);
  int error_level = api_message_obj->ErrorLevel();
  DirectHandle<ArrayList> global_listeners =
      isolate->factory()->message_listeners();
  int global_length = global_listeners->length();
  if (global_length == 0) {
    DefaultMessageReport(isolate, loc, message);
  } else {
    for (int i = 0; i < global_length; i++) {
      HandleScope scope(isolate);
      if (IsUndefined(global_listeners->get(i), isolate)) continue;
      Tagged<FixedArray> listener = Cast<FixedArray>(global_listeners->get(i));
      Tagged<Foreign> callback_obj = Cast<Foreign>(listener->get(0));
      int32_t message_levels =
          static_cast<int32_t>(Smi::ToInt(listener->get(2)));
      if (!(message_levels & error_level)) {
        continue;
      }
      v8::MessageCallback callback =
          v8::ToCData<v8::MessageCallback, kMessageListenerTag>(isolate,
                                                                callback_obj);
      DirectHandle<Object> callback_data(listener->get(1), isolate);
      {
        RCS_SCOPE(isolate, RuntimeCallCounterId::kMessageListenerCallback);
        // Do not allow exceptions to propagate.
        v8::TryCatch try_catch(reinterpret_cast<v8::Isolate*>(isolate));
        callback(api_message_obj, IsUndefined(*callback_data, isolate)
                                      ? api_exception_obj
                                      : v8::Utils::ToLocal(callback_data));
      }
    }
  }
}
References DefaultMessageReport(), v8::internal::Isolate::factory(), v8::internal::loc, RCS_SCOPE, and v8::internal::Smi::ToInt().
Referenced by ReportMessage().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/messages.h
/mnt/V8SourceCode/src/execution/messages.cc