v8::internal::wasm::AsyncCompileJob::CompileStep Class Reference
Public Member Functions
virtual ~CompileStep ()=default
void Run (AsyncCompileJob *job, bool on_foreground)
virtual void RunInForeground (AsyncCompileJob *)
virtual void RunInBackground (AsyncCompileJob *)
Detailed Description
Definition at line 2915 of file module-compiler.cc.
Constructor & Destructor Documentation
 CompileStep()
virtual v8::internal::wasm::AsyncCompileJob::CompileStep::~CompileStep () [virtual], [default]
Member Function Documentation
Run()
void v8::internal::wasm::AsyncCompileJob::CompileStep::Run (AsyncCompileJob * job, bool on_foreground) [inline]
Definition at line 2919 of file module-compiler.cc.
                                                     {
    if (on_foreground) {
      HandleScope scope(job->isolate_);
      SaveAndSwitchContext saved_context(job->isolate_, *job->native_context_);
      RunInForeground(job);
    } else {
      RunInBackground(job);
    }
  }
References v8::internal::wasm::AsyncCompileJob::isolate_, v8::internal::wasm::AsyncCompileJob::native_context_, RunInBackground(), and RunInForeground().
RunInBackground()
virtual void v8::internal::wasm::AsyncCompileJob::CompileStep::RunInBackground (AsyncCompileJob *) [inline], [virtual]
Reimplemented in v8::internal::wasm::AsyncCompileJob::DecodeModule.
Definition at line 2930 of file module-compiler.cc.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
Referenced by Run().
RunInForeground()
virtual void v8::internal::wasm::AsyncCompileJob::CompileStep::RunInForeground (AsyncCompileJob *) [inline], [virtual]
Reimplemented in v8::internal::wasm::AsyncCompileJob::Fail, v8::internal::wasm::AsyncCompileJob::FinishCompilation, and v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile.
Definition at line 2929 of file module-compiler.cc.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
Referenced by Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc