v8::internal::FlagList Class Reference
#include <flags.h>
Classes
class HelpOptions
Static Public Member Functions
static int SetFlagsFromCommandLine (int *argc, char **argv, bool remove_flags, FlagList::HelpOptions help_options=FlagList::HelpOptions())
static int SetFlagsFromString (const char *str, size_t len)
static void FreezeFlags ()
static bool IsFrozen ()
static void ReleaseDynamicAllocations ()
static void PrintHelp ()
static void PrintValues ()
static void PrintFeatureFlagsJSON ()
static void ResolveContradictionsWhenFuzzing ()
static void EnforceFlagImplications ()
static uint32_t Hash ()
Static Private Member Functions
static void ResetFlagHash ()
Friends
template<typename T >
class FlagValue
Detailed Description
Definition at line 77 of file flags.h.
Member Function Documentation
EnforceFlagImplications()
void v8::internal::FlagList::EnforceFlagImplications () [static]
Definition at line 1197 of file flags.cc.
                                       {
  for (ImplicationProcessor proc; proc.EnforceImplications();) {
    // Continue processing (recursive) implications. The processor has an
    // internal limit to avoid endless recursion.
  }
}
Referenced by v8::internal::V8::Initialize().
FreezeFlags()
void v8::internal::FlagList::FreezeFlags () [static]
Definition at line 817 of file flags.cc.
                           {
  // Disallow changes via the API by setting {flags_frozen}.
  flags_frozen.store(true, std::memory_order_relaxed);
  // Also memory-protect the memory that holds the flag values. This makes it
  // impossible for attackers to overwrite values, except if they find a way to
  // first unprotect the memory again.
  // Note that for string flags we only protect the pointer itself, but not the
  // string storage. TODO(12887): Fix this.
  base::OS::SetDataReadOnly(&v8_flags, sizeof(v8_flags));
}
References v8::internal::flags_frozen, v8::base::OS::SetDataReadOnly(), and v8::internal::v8_flags.
Referenced by v8::internal::V8::Initialize().
Hash()
uint32_t v8::internal::FlagList::Hash () [static]
Definition at line 1205 of file flags.cc.
                        {
  if (uint32_t hash = flag_hash.load(std::memory_order_relaxed)) return hash;
  uint32_t hash = ComputeFlagListHash();
  flag_hash.store(hash, std::memory_order_relaxed);
  return hash;
}
References v8::internal::ComputeFlagListHash(), and v8::internal::flag_hash.
Referenced by v8::ScriptCompiler::CachedDataVersionTag(), v8::internal::V8::Initialize(), v8::internal::SerializedCodeData::SanityCheckWithoutSource(), v8::internal::SerializedCodeData::SerializedCodeData(), and v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::WriteHeader().
IsFrozen()
bool v8::internal::FlagList::IsFrozen () [static]
Definition at line 829 of file flags.cc.
                        {
  return flags_frozen.load(std::memory_order_relaxed);
}
References v8::internal::flags_frozen.
Referenced by ResetFlagHash().
PrintFeatureFlagsJSON()
void v8::internal::FlagList::PrintFeatureFlagsJSON () [static]
Definition at line 914 of file flags.cc.
                                     {
  StdoutStream os;
  os << "{\n";
  {
    std::vector<const char*> inprogress_flags;
    std::vector<const char*> staged_flags;
    std::vector<const char*> shipping_flags;
#define ADD_JS_INPROGRESS_FLAG(name, desc) inprogress_flags.push_back(#name);
#define ADD_JS_STAGED_FLAG(name, desc) staged_flags.push_back(#name);
#define ADD_JS_SHIPPING_FLAG(name, desc) shipping_flags.push_back(#name);
    JAVASCRIPT_INPROGRESS_FEATURES(ADD_JS_INPROGRESS_FLAG)
    JAVASCRIPT_STAGED_FEATURES(ADD_JS_STAGED_FLAG)
    JAVASCRIPT_SHIPPING_FEATURES(ADD_JS_SHIPPING_FLAG)
    os << " \"js\": ";
    PrintFeatureFlagsJSONObject(os, inprogress_flags, staged_flags,
                                shipping_flags);
    os << ",\n";
  }
  {
    std::vector<const char*> inprogress_flags;
    std::vector<const char*> staged_flags;
    std::vector<const char*> shipping_flags;
    HARMONY_INPROGRESS(ADD_JS_INPROGRESS_FLAG)
    HARMONY_STAGED(ADD_JS_STAGED_FLAG)
    HARMONY_SHIPPING(ADD_JS_SHIPPING_FLAG)
    os << " \"harmony\": ";
    PrintFeatureFlagsJSONObject(os, inprogress_flags, staged_flags,
                                shipping_flags);
    os << ",\n";
  }
#if V8_ENABLE_WEBASSEMBLY
  {
    std::vector<const char*> inprogress_flags;
    std::vector<const char*> staged_flags;
    std::vector<const char*> shipping_flags;
#define ADD_WASM_INPROGRESS_FLAG(name, desc, val) \
  inprogress_flags.push_back("experimental_wasm_" #name);
#define ADD_WASM_STAGED_FLAG(name, desc, val) \
  staged_flags.push_back("experimental_wasm_" #name);
#define ADD_WASM_SHIPPED_FLAG(name, desc, val) \
  shipping_flags.push_back("experimental_wasm_" #name);
    FOREACH_WASM_EXPERIMENTAL_FEATURE_FLAG(ADD_WASM_INPROGRESS_FLAG)
    FOREACH_WASM_STAGING_FEATURE_FLAG(ADD_WASM_STAGED_FLAG)
    FOREACH_WASM_SHIPPED_FEATURE_FLAG(ADD_WASM_SHIPPED_FLAG)
    os << " \"wasm\": ";
    PrintFeatureFlagsJSONObject(os, inprogress_flags, staged_flags,
                                shipping_flags);
    os << "\n";
  }
#endif // V8_ENABLE_WEBASSEMBLY
  os << "}\n";
#undef ADD_JS_INPROGRESS_FLAG
#undef ADD_JS_STAGED_FLAG
#undef ADD_JS_SHIPPING_FLAG
#undef ADD_WASM_INPROGRESS_FLAG
#undef ADD_WASM_STAGED_FLAG
#undef ADD_WASM_SHIPPED_FLAG
}
References ADD_JS_INPROGRESS_FLAG, ADD_JS_SHIPPING_FLAG, ADD_JS_STAGED_FLAG, FOREACH_WASM_EXPERIMENTAL_FEATURE_FLAG, FOREACH_WASM_SHIPPED_FEATURE_FLAG, FOREACH_WASM_STAGING_FEATURE_FLAG, HARMONY_INPROGRESS, HARMONY_SHIPPING, HARMONY_STAGED, JAVASCRIPT_INPROGRESS_FEATURES, JAVASCRIPT_SHIPPING_FEATURES, JAVASCRIPT_STAGED_FEATURES, and v8::internal::anonymous_namespace{flags.cc}::PrintFeatureFlagsJSONObject().
Referenced by SetFlagsFromCommandLine().
PrintHelp()
void v8::internal::FlagList::PrintHelp () [static]
Definition at line 842 of file flags.cc.
                         {
  CpuFeatures::Probe(false);
  CpuFeatures::PrintTarget();
  CpuFeatures::PrintFeatures();
  StdoutStream os;
  os << "The following syntax for options is accepted (both '-' and '--' are "
        "ok):\n"
        " --flag (bool flags only)\n"
        " --no-flag (bool flags only)\n"
        " --flag=value (non-bool flags only, no spaces around '=')\n"
        " --flag value (non-bool flags only)\n"
        " -- (captures all remaining args in JavaScript)\n\n";
  os << "Options:\n";
  for (const Flag& f : flags) {
    os << " " << FlagName{f.name()} << " (" << f.comment() << ")\n"
       << " type: " << Type2String(f.type()) << " default: " << f
       << "\n";
  }
}
References v8::internal::flags, v8::internal::FlagName::name, v8::internal::CpuFeatures::PrintFeatures(), v8::internal::CpuFeatures::PrintTarget(), v8::internal::CpuFeatures::Probe(), and v8::internal::Type2String().
Referenced by SetFlagsFromCommandLine().
PrintValues()
void v8::internal::FlagList::PrintValues () [static]
Definition at line 865 of file flags.cc.
                           {
  StdoutStream os;
  for (const Flag& f : flags) {
    os << f << "\n";
  }
}
References v8::internal::flags.
Referenced by v8::internal::V8::Initialize().
ReleaseDynamicAllocations()
void v8::internal::FlagList::ReleaseDynamicAllocations () [static]
Definition at line 834 of file flags.cc.
                                         {
  flag_hash = 0;
  for (size_t i = 0; i < kNumFlags; ++i) {
    flags[i].ReleaseDynamicAllocations();
  }
}
References v8::internal::flag_hash, v8::internal::flags, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kNumFlags, and v8::internal::Flag::ReleaseDynamicAllocations().
Referenced by v8::internal::V8::Dispose().
ResetFlagHash()
void v8::internal::FlagList::ResetFlagHash () [static], [private]
Definition at line 1213 of file flags.cc.
                             {
  // If flags are frozen, we should not need to reset the hash since we cannot
  // change flag values anyway.
  CHECK(!IsFrozen());
  flag_hash = 0;
}
References CHECK, v8::internal::flag_hash, and IsFrozen().
Referenced by v8::internal::FlagValue< T >::operator=().
ResolveContradictionsWhenFuzzing()
void v8::internal::FlagList::ResolveContradictionsWhenFuzzing () [static]
Definition at line 1100 of file flags.cc.
                                                {
  if (!i::v8_flags.fuzzing) return;
  std::tuple<Flag*, Flag*> contradictions[] = {
      // List of flags that lead to known contradictory cycles when both
      // deviate from their defaults. One of them will be reset with precedence
      // left to right.
      CONTRADICTION(always_osr_from_maglev, disable_optimizing_compilers),
      CONTRADICTION(always_osr_from_maglev, jitless),
      CONTRADICTION(always_osr_from_maglev, lite_mode),
      CONTRADICTION(always_osr_from_maglev, turbofan),
      CONTRADICTION(always_osr_from_maglev, turboshaft),
      CONTRADICTION(always_turbofan, disable_optimizing_compilers),
      CONTRADICTION(always_turbofan, jitless),
      CONTRADICTION(always_turbofan, lite_mode),
      CONTRADICTION(always_turbofan, turboshaft),
      CONTRADICTION(assert_types, stress_concurrent_inlining),
      CONTRADICTION(assert_types, stress_concurrent_inlining_attach_code),
      CONTRADICTION(disable_optimizing_compilers, maglev_future),
      CONTRADICTION(disable_optimizing_compilers, stress_concurrent_inlining),
      CONTRADICTION(disable_optimizing_compilers,
                    stress_concurrent_inlining_attach_code),
      CONTRADICTION(disable_optimizing_compilers, stress_maglev),
      CONTRADICTION(disable_optimizing_compilers,
                    turboshaft_wasm_in_js_inlining),
      CONTRADICTION(jitless, maglev_future),
      CONTRADICTION(jitless, stress_concurrent_inlining),
      CONTRADICTION(jitless, stress_concurrent_inlining_attach_code),
      CONTRADICTION(jitless, stress_maglev),
      CONTRADICTION(lite_mode, maglev_future),
      CONTRADICTION(lite_mode, predictable_gc_schedule),
      CONTRADICTION(lite_mode, stress_concurrent_inlining),
      CONTRADICTION(lite_mode, stress_concurrent_inlining_attach_code),
      CONTRADICTION(lite_mode, stress_maglev),
      CONTRADICTION(optimize_for_size, predictable_gc_schedule),
      CONTRADICTION(predictable, stress_concurrent_inlining_attach_code),
      CONTRADICTION(predictable_gc_schedule, stress_compaction),
      CONTRADICTION(single_threaded, stress_concurrent_inlining_attach_code),
      CONTRADICTION(stress_concurrent_inlining, turboshaft_assert_types),
      CONTRADICTION(stress_concurrent_inlining_attach_code,
                    turboshaft_assert_types),
      CONTRADICTION(turboshaft, stress_concurrent_inlining),
      CONTRADICTION(turboshaft, stress_concurrent_inlining_attach_code),
      // List of flags that shouldn't be used when --fuzzing or
      // --correctness-fuzzer-suppressions is passed. These flags will be reset
      // to their defaults.
      // https://crbug.com/419424082
      RESET_WHEN_CORRECTNESS_FUZZING(default_to_experimental_regexp_engine),
      RESET_WHEN_CORRECTNESS_FUZZING(enable_experimental_regexp_engine),
      RESET_WHEN_CORRECTNESS_FUZZING(
          experimental_regexp_engine_capture_group_opt),
      // https://crbug.com/369652671
      RESET_WHEN_CORRECTNESS_FUZZING(stress_lazy_compilation),
      // https://crbug.com/380327159
      RESET_WHEN_CORRECTNESS_FUZZING(turbo_stats),
      RESET_WHEN_CORRECTNESS_FUZZING(turbo_stats_nvp),
      RESET_WHEN_CORRECTNESS_FUZZING(turbo_stats_wasm),
      // https://crbug.com/369974230
      RESET_WHEN_FUZZING(expose_async_hooks),
      // https://crbug.com/371061101
      RESET_WHEN_FUZZING(parallel_compile_tasks_for_lazy),
      // https://crbug.com/366671002
      RESET_WHEN_FUZZING(stress_snapshot),
      // https://crbug.com/393401455
      RESET_WHEN_FUZZING(turboshaft),
  };
  for (auto [flag1, flag2] : contradictions) {
    if (!flag1 || !flag2) continue;
    if (flag1->IsDefault() || flag2->IsDefault()) continue;
    // Ensure we never reset the fuzzing flags.
    CHECK(!flag1->PointsTo(&v8_flags.fuzzing));
    CHECK(!flag1->PointsTo(&v8_flags.correctness_fuzzer_suppressions));
    std::cerr << "Warning: resetting flag --" << flag1->name()
              << " due to conflicting flags" << std::endl;
    flag1->Reset();
  }
  if ((v8_flags.trace_turbo || v8_flags.trace_turbo_graph) &&
      v8_flags.fuzzing_and_concurrent_recompilation) {
    std::cerr
        << "Use --nofuzzing-and-concurrent-recompilation to force "
           "enable --trace-turbo, and friends. This is not thread-safe.\n";
  }
}
References CHECK, CONTRADICTION, RESET_WHEN_CORRECTNESS_FUZZING, RESET_WHEN_FUZZING, and v8::internal::v8_flags.
Referenced by v8::Shell::SetOptions().
SetFlagsFromCommandLine()
int v8::internal::FlagList::SetFlagsFromCommandLine (int * argc, char ** argv, bool remove_flags, FlagList::HelpOptions help_options = FlagList::HelpOptions()) [static]
Definition at line 601 of file flags.cc.
                                                                {
  int return_code = 0;
  // TODO(jgruber): Since ShouldCheckFlagContradictions looks at v8_flags
  // values to determine whether to check for contradictions, these flag values
  // must be available before the check returns a consistent value. That means
  // we'd really have to add a preprocessing pass that only considers these
  // flags (e.g. --fuzzing). Otherwise, they are position-sensitive and only
  // disable contradiction checks for flags that come after. This is pretty
  // surprising since no other v8 flags have such positional behavior.
  // Parse arguments.
  for (int i = 1; i < *argc;) {
    int j = i; // j > 0
    const char* arg = argv[i++];
    if (arg == nullptr) continue;
    // Stop processing flags on '--'.
    if (arg[0] == '-' && arg[1] == '-' && arg[2] == '\0') break;
    // Split arg into flag components.
    char buffer[1 * KB];
    const char* name;
    const char* value;
    bool negated;
    SplitArgument(arg, buffer, sizeof buffer, &name, &value, &negated);
    if (name == nullptr) continue;
    // Lookup the flag.
    Flag* flag = FindFlagByName(name);
    if (flag == nullptr) {
      if (remove_flags) {
        // We don't recognize this flag but since we're removing
        // the flags we recognize we assume that the remaining flags
        // will be processed somewhere else so this flag might make
        // sense there.
        continue;
      } else {
        PrintF(stderr, "Error: unrecognized flag %s\n", arg);
        return_code = j;
        break;
      }
    }
    // If we still need a flag value, use the next argument if available.
    if (flag->type() != Flag::TYPE_BOOL &&
        flag->type() != Flag::TYPE_MAYBE_BOOL && value == nullptr) {
      if (i < *argc) {
        value = argv[i++];
      }
      if (!value) {
        PrintF(stderr, "Error: missing value for flag %s of type %s\n", arg,
               Type2String(flag->type()));
        return_code = j;
        break;
      }
    }
    // Set the flag.
    char* endp = const_cast<char*>(""); // *endp is only read
    switch (flag->type()) {
      case Flag::TYPE_BOOL:
        flag->set_bool_variable(!negated, Flag::SetBy::kCommandLine);
        break;
      case Flag::TYPE_MAYBE_BOOL:
        flag->set_maybe_bool_variable(!negated, Flag::SetBy::kCommandLine);
        break;
      case Flag::TYPE_INT:
        flag->set_int_variable(static_cast<int>(strtol(value, &endp, 10)),
                               Flag::SetBy::kCommandLine);
        break;
      case Flag::TYPE_UINT: {
        unsigned int parsed_value;
        if (TryParseUnsigned(flag, arg, value, &endp, &parsed_value)) {
          flag->set_uint_variable(parsed_value, Flag::SetBy::kCommandLine);
        } else {
          return_code = j;
        }
        break;
      }
      case Flag::TYPE_UINT64: {
        uint64_t parsed_value;
        if (TryParseUnsigned(flag, arg, value, &endp, &parsed_value)) {
          flag->set_uint64_variable(parsed_value, Flag::SetBy::kCommandLine);
        } else {
          return_code = j;
        }
        break;
      }
      case Flag::TYPE_FLOAT:
        flag->set_float_variable(strtod(value, &endp),
                                 Flag::SetBy::kCommandLine);
        break;
      case Flag::TYPE_SIZE_T: {
        size_t parsed_value;
        if (TryParseUnsigned(flag, arg, value, &endp, &parsed_value)) {
          flag->set_size_t_variable(parsed_value, Flag::SetBy::kCommandLine);
        } else {
          return_code = j;
        }
        break;
      }
      case Flag::TYPE_STRING:
        flag->set_string_value(value ? StrDup(value) : nullptr, true,
                               Flag::SetBy::kCommandLine);
        break;
    }
    // Handle errors.
    bool is_bool_type = flag->type() == Flag::TYPE_BOOL ||
                        flag->type() == Flag::TYPE_MAYBE_BOOL;
    if ((is_bool_type && value != nullptr) || (!is_bool_type && negated) ||
        *endp != '\0') {
      // TODO(neis): TryParseUnsigned may return with {*endp == '\0'} even in
      // an error case.
      PrintF(stderr, "Error: illegal value for flag %s of type %s\n", arg,
             Type2String(flag->type()));
      if (is_bool_type) {
        PrintF(stderr,
               "To set or unset a boolean flag, use --flag or --no-flag.\n");
      }
      return_code = j;
      break;
    }
    // Remove the flag & value from the command.
    if (remove_flags) {
      while (j < i) {
        argv[j++] = nullptr;
      }
    }
  }
  if (v8_flags.help) {
    if (help_options.HasUsage()) {
      PrintF(stdout, "%s", help_options.usage());
    }
    PrintHelp();
    if (help_options.ShouldExit()) {
      exit(0);
    }
  }
  if (v8_flags.print_feature_flags_json) {
    PrintFeatureFlagsJSON();
    if (help_options.ShouldExit()) {
      exit(0);
    }
  }
  if (remove_flags) {
    // Shrink the argument list.
    int j = 1;
    for (int i = 1; i < *argc; i++) {
      if (argv[i] != nullptr) argv[j++] = argv[i];
    }
    *argc = j;
  } else if (return_code != 0) {
    if (return_code + 1 < *argc) {
      PrintF(stderr, "The remaining arguments were ignored:");
      for (int i = return_code + 1; i < *argc; ++i) {
        PrintF(stderr, " %s", argv[i]);
      }
      PrintF(stderr, "\n");
    }
  }
  if (return_code != 0) PrintF(stderr, "Try --help for options\n");
  return return_code;
}
References v8::internal::FindFlagByName(), v8::internal::FlagList::HelpOptions::HasUsage(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::KB, v8::internal::Flag::kCommandLine, v8::internal::name, v8::internal::PrintF(), PrintFeatureFlagsJSON(), PrintHelp(), v8::internal::Flag::set_bool_variable(), v8::internal::Flag::set_float_variable(), v8::internal::Flag::set_int_variable(), v8::internal::Flag::set_maybe_bool_variable(), v8::internal::Flag::set_size_t_variable(), v8::internal::Flag::set_string_value(), v8::internal::Flag::set_uint64_variable(), v8::internal::Flag::set_uint_variable(), v8::internal::FlagList::HelpOptions::ShouldExit(), v8::internal::SplitArgument(), v8::internal::StrDup(), v8::internal::TryParseUnsigned(), v8::internal::Flag::type(), v8::internal::Type2String(), v8::internal::Flag::TYPE_BOOL, v8::internal::Flag::TYPE_FLOAT, v8::internal::Flag::TYPE_INT, v8::internal::Flag::TYPE_MAYBE_BOOL, v8::internal::Flag::TYPE_SIZE_T, v8::internal::Flag::TYPE_STRING, v8::internal::Flag::TYPE_UINT, v8::internal::Flag::TYPE_UINT64, v8::internal::FlagList::HelpOptions::usage(), v8::internal::v8_flags, and v8::internal::value.
Referenced by main(), v8::V8::SetFlagsFromCommandLine(), SetFlagsFromString(), and v8::Shell::SetOptions().
SetFlagsFromString()
int v8::internal::FlagList::SetFlagsFromString (const char * str, size_t len) [static]
Definition at line 785 of file flags.cc.
                                                            {
  // Make a 0-terminated copy of str.
  std::unique_ptr<char[]> copy0{NewArray<char>(len + 1)};
  MemCopy(copy0.get(), str, len);
  copy0[len] = '\0';
  // Strip leading white space.
  char* copy = SkipWhiteSpace(copy0.get());
  // Count the number of 'arguments'.
  int argc = 1; // be compatible with SetFlagsFromCommandLine()
  for (char* p = copy; *p != '\0'; argc++) {
    p = SkipBlackSpace(p);
    p = SkipWhiteSpace(p);
  }
  // Allocate argument array.
  base::ScopedVector<char*> argv(argc);
  // Split the flags string into arguments.
  argc = 1; // be compatible with SetFlagsFromCommandLine()
  for (char* p = copy; *p != '\0'; argc++) {
    argv[argc] = p;
    p = SkipBlackSpace(p);
    if (*p != '\0') *p++ = '\0'; // 0-terminate argument
    p = SkipWhiteSpace(p);
  }
  return SetFlagsFromCommandLine(&argc, argv.begin(), false);
}
References v8::base::Vector< T >::begin(), v8::internal::MemCopy(), SetFlagsFromCommandLine(), v8::internal::SkipBlackSpace(), and v8::internal::SkipWhiteSpace().
Referenced by v8::V8::SetFlagsFromString().
Friends And Related Function Documentation
FlagValue
template<typename T >
friend class FlagValue [friend]
Definition at line 161 of file flags.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/flags/flags.h
/mnt/V8SourceCode/src/flags/flags.cc