v8::internal::compiler::JSConstructNodeBase< kOpcode > Class Template Reference
#include <js-operator.h>
Public Member Functions
constexpr JSConstructNodeBase (Node *node)
const ConstructParameters & Parameters () const
int ArgumentCount () const
Static Public Attributes
static constexpr int kNewTargetInputCount = 1
Additional Inherited Members
Detailed Description
template<int kOpcode>
class v8::internal::compiler::JSConstructNodeBase< kOpcode >
Definition at line 1527 of file js-operator.h.
Constructor & Destructor Documentation
JSConstructNodeBase()
template<int kOpcode>
constexpr v8::internal::compiler::JSConstructNodeBase< kOpcode >::JSConstructNodeBase (Node * node) [inline], [explicit], [constexpr]
Definition at line 1529 of file js-operator.h.
      : JSCallOrConstructNode(node) {
    DCHECK_EQ(kOpcode, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
ArgumentCount()
template<int kOpcode>
int v8::internal::compiler::JSConstructNodeBase< kOpcode >::ArgumentCount () const [inline], [virtual]
Implements v8::internal::compiler::JSCallOrConstructNode.
Definition at line 1548 of file js-operator.h.
                            {
    // Note: The count reported by this function depends only on the parameter,
    // thus adding/removing inputs will not affect it.
    return Parameters().arity_without_implicit_args();
  }
References v8::internal::compiler::ConstructParameters::arity_without_implicit_args(), and v8::internal::compiler::JSConstructNodeBase< kOpcode >::Parameters().
Referenced by v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), v8::internal::compiler::JSCallReducer::ReduceJSConstructWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceJSConstructWithSpread(), and v8::internal::compiler::JSCallReducer::ReduceStringConstructor().
Parameters()
template<int kOpcode>
const ConstructParameters& v8::internal::compiler::JSConstructNodeBase< kOpcode >::Parameters () const [inline]
Definition at line 1534 of file js-operator.h.
                                                {
    return ConstructParametersOf(node()->op());
  }
References v8::internal::compiler::ConstructParametersOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSConstructNodeBase< kOpcode >::ArgumentCount(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseExecutor(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseReject(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSConstruct(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), v8::internal::compiler::JSCallReducer::ReduceJSConstructWithArrayLike(), and v8::internal::compiler::JSCallReducer::ReduceJSConstructWithSpread().
Member Data Documentation
kNewTargetInputCount
template<int kOpcode>
constexpr int v8::internal::compiler::JSConstructNodeBase< kOpcode >::kNewTargetInputCount = 1 [static], [constexpr]
Definition at line 1544 of file js-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h