v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next > Class Template Reference
#include <duplication-optimization-reducer.h>
Public Member Functions
V< None > REDUCE_INPUT_GRAPH() Branch (V< None > ig_index, const BranchOp &branch)
V< Any > REDUCE_INPUT_GRAPH() Select (V< Any > ig_index, const SelectOp &select)
Private Member Functions
bool MaybeDuplicateCond (const Operation &cond, OpIndex input_idx, V< Word32 > *new_cond)
bool MaybeCanDuplicateGenericBinop (OpIndex input_idx, OpIndex left, OpIndex right)
OpIndex MaybeDuplicateWordBinop (const WordBinopOp &binop, OpIndex input_idx)
V< Word32 > MaybeDuplicateComparison (const ComparisonOp &comp, OpIndex input_idx)
OpIndex MaybeDuplicateShift (const ShiftOp &shift, OpIndex input_idx)
OpIndex MaybeDuplicateOutputGraphShift (OpIndex index)
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >
Definition at line 73 of file duplication-optimization-reducer.h.
Member Function Documentation
Branch()
template<class Next >
V<None> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::Branch (V< None > ig_index, const BranchOp & branch) [inline]
Definition at line 77 of file duplication-optimization-reducer.h.
                                                                               {
    LABEL_BLOCK(no_change) {
      return Next::ReduceInputGraphBranch(ig_index, branch);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    const Operation& cond = __ input_graph().Get(branch.condition());
    V<Word32> new_cond;
    if (!MaybeDuplicateCond(cond, branch.condition(), &new_cond)) {
      goto no_change;
    }
    DCHECK(new_cond.valid());
    __ Branch(new_cond, __ MapToNewGraph(branch.if_true),
              __ MapToNewGraph(branch.if_false), branch.hint);
    return V<None>::Invalid();
  }
References __, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::V< T >::Invalid(), LABEL_BLOCK, v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateCond(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), and v8::internal::compiler::turboshaft::OpIndex::valid().
MaybeCanDuplicateGenericBinop()
template<class Next >
bool v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeCanDuplicateGenericBinop (OpIndex input_idx, OpIndex left, OpIndex right) [inline], [private]
Definition at line 166 of file duplication-optimization-reducer.h.
                                                    {
    if (__ input_graph().Get(left).saturated_use_count.IsOne() &&
        __ input_graph().Get(right).saturated_use_count.IsOne()) {
      // We don't duplicate binops when all of their inputs are used a single
      // time (this would increase register pressure by keeping 2 values alive
      // instead of 1).
      return false;
    }
    OpIndex binop_output_idx = __ MapToNewGraph(input_idx);
    if (__ Get(binop_output_idx).saturated_use_count.IsZero()) {
      // This is the 1st use of {binop} in the output graph, so there is no need
      // to duplicate it just yet.
      return false;
    }
    return true;
  }
References __, and v8::internal::compiler::turboshaft::Get().
Referenced by v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateComparison(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateShift(), and v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateWordBinop().
MaybeDuplicateComparison()
template<class Next >
V<Word32> v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateComparison (const ComparisonOp & comp, OpIndex input_idx) [inline], [private]
Definition at line 207 of file duplication-optimization-reducer.h.
                                                        {
    if (!MaybeCanDuplicateGenericBinop(input_idx, comp.left(), comp.right())) {
      return {};
    }
    DisableValueNumbering disable_gvn(this);
    return __ Comparison(__ MapToNewGraph(comp.left()),
                         __ MapToNewGraph(comp.right()), comp.kind, comp.rep);
  }
References __, v8::internal::compiler::turboshaft::ComparisonOp::kind, v8::internal::compiler::turboshaft::ComparisonOp::left(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeCanDuplicateGenericBinop(), v8::internal::compiler::turboshaft::ComparisonOp::rep, and v8::internal::compiler::turboshaft::ComparisonOp::right().
Referenced by v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateCond().
MaybeDuplicateCond()
template<class Next >
bool v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateCond (const Operation & cond, OpIndex input_idx, V< Word32 > * new_cond) [inline], [private]
Definition at line 144 of file duplication-optimization-reducer.h.
                                               {
    if (cond.saturated_use_count.IsOne()) return false;
    switch (cond.opcode) {
      case Opcode::kComparison:
        *new_cond =
            MaybeDuplicateComparison(cond.Cast<ComparisonOp>(), input_idx);
        break;
      case Opcode::kWordBinop:
        *new_cond =
            MaybeDuplicateWordBinop(cond.Cast<WordBinopOp>(), input_idx);
        break;
      case Opcode::kShift:
        *new_cond = MaybeDuplicateShift(cond.Cast<ShiftOp>(), input_idx);
        break;
      default:
        return false;
    }
    return new_cond->valid();
  }
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::SaturatedUint8::IsOne(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateComparison(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateShift(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateWordBinop(), v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::Operation::saturated_use_count, and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::Branch(), and v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::Select().
MaybeDuplicateOutputGraphShift()
template<class Next >
OpIndex v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateOutputGraphShift (OpIndex index) [inline], [private]
Definition at line 229 of file duplication-optimization-reducer.h.
                                                        {
    V<Word> shifted;
    int shifted_by;
    ShiftOp::Kind shift_kind;
    WordRepresentation shift_rep;
    if (__ matcher().MatchConstantShift(index, &shifted, &shift_kind,
                                        &shift_rep, &shifted_by) &&
        !__ matcher().Get(index).saturated_use_count.IsZero()) {
      // We don't check the use count of {shifted}, because it might have uses
      // in the future that haven't been emitted yet.
      DisableValueNumbering disable_gvn(this);
      return __ Shift(shifted, __ Word32Constant(shifted_by), shift_kind,
                      shift_rep);
    }
    return index;
  }
References __, v8::internal::compiler::turboshaft::Get(), and v8::internal::index.
MaybeDuplicateShift()
template<class Next >
OpIndex v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateShift (const ShiftOp & shift, OpIndex input_idx) [inline], [private]
Definition at line 218 of file duplication-optimization-reducer.h.
                                                                       {
    if (!MaybeCanDuplicateGenericBinop(input_idx, shift.left(),
                                       shift.right())) {
      return OpIndex::Invalid();
    }
    DisableValueNumbering disable_gvn(this);
    return __ Shift(__ MapToNewGraph(shift.left()),
                    __ MapToNewGraph(shift.right()), shift.kind, shift.rep);
  }
References __, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::ShiftOp::kind, v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeCanDuplicateGenericBinop(), v8::internal::compiler::turboshaft::ShiftOp::rep, and v8::internal::compiler::turboshaft::ShiftOp::right().
Referenced by v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateCond().
MaybeDuplicateWordBinop()
template<class Next >
OpIndex v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateWordBinop (const WordBinopOp & binop, OpIndex input_idx) [inline], [private]
Definition at line 184 of file duplication-optimization-reducer.h.
                                                                               {
    if (!MaybeCanDuplicateGenericBinop(input_idx, binop.left(),
                                       binop.right())) {
      return OpIndex::Invalid();
    }
    switch (binop.kind) {
      case WordBinopOp::Kind::kSignedDiv:
      case WordBinopOp::Kind::kUnsignedDiv:
      case WordBinopOp::Kind::kSignedMod:
      case WordBinopOp::Kind::kUnsignedMod:
        // These operations are somewhat expensive, and duplicating them is
        // probably not worth it.
        return OpIndex::Invalid();
      default:
        break;
    }
    DisableValueNumbering disable_gvn(this);
    return __ WordBinop(__ MapToNewGraph(binop.left()),
                        __ MapToNewGraph(binop.right()), binop.kind, binop.rep);
  }
References __, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::WordBinopOp::kind, v8::internal::compiler::turboshaft::WordBinopOp::kSignedDiv, v8::internal::compiler::turboshaft::WordBinopOp::kSignedMod, v8::internal::compiler::turboshaft::WordBinopOp::kUnsignedDiv, v8::internal::compiler::turboshaft::WordBinopOp::kUnsignedMod, v8::internal::compiler::turboshaft::WordBinopOp::left(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeCanDuplicateGenericBinop(), v8::internal::compiler::turboshaft::WordBinopOp::rep, and v8::internal::compiler::turboshaft::WordBinopOp::right().
Referenced by v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateCond().
Select()
template<class Next >
V<Any> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::Select (V< Any > ig_index, const SelectOp & select) [inline]
Definition at line 95 of file duplication-optimization-reducer.h.
                                                                             {
    LABEL_BLOCK(no_change) {
      return Next::ReduceInputGraphSelect(ig_index, select);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    const Operation& cond = __ input_graph().Get(select.cond());
    V<Word32> new_cond;
    if (!MaybeDuplicateCond(cond, select.cond(), &new_cond)) goto no_change;
    DCHECK(new_cond.valid());
    return __ Select(new_cond, __ MapToNewGraph(select.vtrue()),
                     __ MapToNewGraph(select.vfalse()), select.rep, select.hint,
                     select.implem);
  }
References __, v8::internal::DCHECK(), LABEL_BLOCK, v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateCond(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), and v8::internal::compiler::turboshaft::OpIndex::valid().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/duplication-optimization-reducer.h