v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl Class Reference
Classes
class UpdatePointersVisitor
Static Public Member Functions
static void CopyToReadOnlyHeap (Isolate *isolate, const std::vector< Tagged< HeapObject >> &promotees, HeapObjectMap *moves)
static void UpdatePointers (Isolate *isolate, const SafepointScope &safepoint_scope, const HeapObjectMap &moves)
static void DeleteDeadObjects (Isolate *isolate, const SafepointScope &safepoint_scope, const HeapObjectMap &moves)
static void Verify (Isolate *isolate, const SafepointScope &safepoint_scope)
Static Private Member Functions
static void LogPromotedObject (Tagged< HeapObject > src, Tagged< HeapObject > dst)
static void LogPromotedCodePointerTableEntry (Tagged< Code > code, IndirectPointerHandle old_handle, IndirectPointerHandle new_handle)
Detailed Description
Definition at line 421 of file read-only-promotion.cc.
Member Function Documentation
CopyToReadOnlyHeap()
static void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::CopyToReadOnlyHeap (Isolate * isolate, const std::vector< Tagged< HeapObject >> & promotees, HeapObjectMap * moves) [inline], [static]
Definition at line 423 of file read-only-promotion.cc.
                            {
    ReadOnlySpace* rospace = isolate->heap()->read_only_space();
    for (Tagged<HeapObject> src : promotees) {
      const int size = src->Size(isolate);
      Tagged<HeapObject> dst =
          rospace->AllocateRaw(size, kTaggedAligned).ToObjectChecked();
      Heap::CopyBlock(dst.address(), src.address(), size);
      moves->emplace(src, dst);
      if (V8_UNLIKELY(v8_flags.trace_read_only_promotion_verbose)) {
        LogPromotedObject(src, dst);
      }
    }
  }
References v8::internal::Tagged< HeapObject >::address(), v8::internal::ReadOnlySpace::AllocateRaw(), v8::internal::Heap::CopyBlock(), v8::internal::Isolate::heap(), v8::internal::kTaggedAligned, v8::internal::Heap::read_only_space(), size(), v8::internal::AllocationResult::ToObjectChecked(), v8::internal::v8_flags, and V8_UNLIKELY.
DeleteDeadObjects()
static void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::DeleteDeadObjects (Isolate * isolate, const SafepointScope & safepoint_scope, const HeapObjectMap & moves) [inline], [static]
Definition at line 488 of file read-only-promotion.cc.
                                                            {
    // After moving a source object to a new destination, overwrite the source
    // memory with a filler. This is needed for moved objects that are verified
    // by the heap verifier to have a 1-1 relation with some other object (e.g.
    // objects related to trusted space). The verifier won't compute liveness
    // and instead just iterates linearly over pages. Without this change the
    // verifier would fail on this now-dead object.
    for (auto [src, dst] : moves) {
      CHECK(!HeapLayout::InReadOnlySpace(src));
      isolate->heap()->CreateFillerObjectAt(src.address(), src->Size(isolate));
    }
  }
References CHECK, v8::internal::Heap::CreateFillerObjectAt(), v8::internal::Isolate::heap(), and v8::internal::HeapLayout::InReadOnlySpace().
LogPromotedCodePointerTableEntry()
static void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::LogPromotedCodePointerTableEntry (Tagged< Code > code, IndirectPointerHandle old_handle, IndirectPointerHandle new_handle) [inline], [static], [private]
Definition at line 765 of file read-only-promotion.cc.
                                        {
    std::cout << "ro-promotion: promoted code pointer table entry {code "
              << reinterpret_cast<void*>(code.ptr()) << " slot "
              << AsHex(old_handle, 8, true) << " to "
              << AsHex(new_handle, 8, true) << "}\n";
  }
References code.
LogPromotedObject()
static void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::LogPromotedObject (Tagged< HeapObject > src, Tagged< HeapObject > dst) [inline], [static], [private]
Definition at line 758 of file read-only-promotion.cc.
                                                        {
    std::cout << "ro-promotion: promoted object {from "
              << reinterpret_cast<void*>(src.ptr()) << " to "
              << reinterpret_cast<void*>(dst.ptr()) << "}\n";
  }
References v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
UpdatePointers()
static void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointers (Isolate * isolate, const SafepointScope & safepoint_scope, const HeapObjectMap & moves) [inline], [static]
Definition at line 440 of file read-only-promotion.cc.
                                                         {
    Heap* heap = isolate->heap();
#ifdef V8_COMPRESS_POINTERS
    ExternalPointerTable::UnsealReadOnlySegmentScope unseal_scope(
        &isolate->external_pointer_table());
#endif // V8_COMPRESS_POINTERS
    UpdatePointersVisitor v(isolate, &moves);
    // Iterate all roots.
    EmbedderStackStateScope stack_scope(
        isolate->heap(), EmbedderStackStateOrigin::kExplicitInvocation,
        StackState::kNoHeapPointers);
    heap->IterateRoots(&v, base::EnumSet<SkipRoot>{});
    // Iterate all objects on the mutable heap.
    // We assume that a full and precise GC has reclaimed all dead objects
    // and therefore that no filtering of unreachable objects is required here.
    HeapObjectIterator it(heap, safepoint_scope);
    for (Tagged<HeapObject> o = it.Next(); !o.is_null(); o = it.Next()) {
      VisitObject(isolate, o, &v);
    }
    // Iterate all objects we just copied into RO space.
    for (auto [src, dst] : moves) {
      VisitObject(isolate, dst, &v);
    }
#ifdef V8_ENABLE_LEAPTIERING
    // Iterate all entries in the JSDispatchTable as they could contain
    // pointers to promoted Code objects.
    JSDispatchTable* const jdt = IsolateGroup::current()->js_dispatch_table();
    jdt->IterateActiveEntriesIn(heap->js_dispatch_table_space(),
                                [&](JSDispatchHandle handle) {
                                  Tagged<Code> old_code = jdt->GetCode(handle);
                                  auto it = moves.find(old_code);
                                  if (it == moves.end()) return;
                                  Tagged<HeapObject> new_code = it->second;
                                  CHECK(IsCode(new_code));
                                  // TODO(saelo): is it worth logging something
                                  // in this case?
                                  jdt->SetCodeNoWriteBarrier(
                                      handle, Cast<Code>(new_code));
                                });
#endif // V8_ENABLE_LEAPTIERING
  }
References v8::internal::IsolateGroup::current(), v8::internal::handle(), v8::internal::Isolate::heap(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::kExplicitInvocation, v8::internal::HeapObjectIterator::Next(), and v8::internal::VisitObject().
Verify()
static void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::Verify (Isolate * isolate, const SafepointScope & safepoint_scope) [inline], [static]
Definition at line 503 of file read-only-promotion.cc.
                                                                              {
#ifdef DEBUG
    // Verify that certain objects were promoted as expected.
    //
    // Known objects.
    Heap* heap = isolate->heap();
    CHECK(HeapLayout::InReadOnlySpace(
        heap->promise_all_resolve_element_closure_shared_fun()));
    CHECK(HeapLayout::InReadOnlySpace(heap->error_stack_getter_fun_template()));
    CHECK(HeapLayout::InReadOnlySpace(heap->error_stack_setter_fun_template()));
    // TODO(jgruber): Extend here with more objects as they are added to
    // the promotion algorithm.
    // Builtin Code objects.
    if (Builtins::kCodeObjectsAreInROSpace) {
      Builtins* builtins = isolate->builtins();
      for (int i = 0; i < Builtins::kBuiltinCount; i++) {
        CHECK(HeapLayout::InReadOnlySpace(
            builtins->code(static_cast<Builtin>(i))));
      }
    }
#endif // DEBUG
  }
References v8::internal::Isolate::builtins(), CHECK, v8::internal::Builtins::code(), v8::internal::Isolate::heap(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::Builtins::kBuiltinCount, and v8::internal::Builtins::kCodeObjectsAreInROSpace.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/read-only-promotion.cc