v8::internal::DebugEvaluate Class Reference
#include <debug-evaluate.h>
Classes
class ContextBuilder
Static Public Member Functions
static V8_EXPORT_PRIVATE MaybeDirectHandle< Object > Global (Isolate *isolate, Handle< String > source, debug::EvaluateGlobalMode mode, REPLMode repl_mode=REPLMode::kNo)
static V8_EXPORT_PRIVATE MaybeDirectHandle< Object > Local (Isolate *isolate, StackFrameId frame_id, int inlined_jsframe_index, DirectHandle< String > source, bool throw_on_side_effect)
static MaybeDirectHandle< Object > WithTopmostArguments (Isolate *isolate, DirectHandle< String > source)
static DebugInfo::SideEffectState FunctionGetSideEffectState (Isolate *isolate, DirectHandle< SharedFunctionInfo > info)
static void ApplySideEffectChecks (Handle< BytecodeArray > bytecode_array)
static bool IsSideEffectFreeIntrinsic (Runtime::FunctionId id)
Static Private Member Functions
static MaybeDirectHandle< Object > Evaluate (Isolate *isolate, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< Context > context, DirectHandle< Object > receiver, DirectHandle< String > source, bool throw_on_side_effect)
Detailed Description
Definition at line 25 of file debug-evaluate.h.
Member Function Documentation
ApplySideEffectChecks()
void v8::internal::DebugEvaluate::ApplySideEffectChecks (Handle< BytecodeArray > bytecode_array) [static]
Definition at line 1363 of file debug-evaluate.cc.
                                          {
  for (interpreter::BytecodeArrayIterator it(bytecode_array); !it.done();
       it.Advance()) {
    interpreter::Bytecode bytecode = it.current_bytecode();
    if (BytecodeRequiresRuntimeCheck(bytecode)) it.ApplyDebugBreak();
  }
}
References v8::internal::anonymous_namespace{debug-evaluate.cc}::BytecodeRequiresRuntimeCheck(), and v8::internal::interpreter::BytecodeArrayIterator::done().
Referenced by v8::internal::Debug::ApplySideEffectChecks().
Evaluate()
MaybeDirectHandle< Object > v8::internal::DebugEvaluate::Evaluate (Isolate * isolate, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< Context > context, DirectHandle< Object > receiver, DirectHandle< String > source, bool throw_on_side_effect) [static], [private]
Definition at line 175 of file debug-evaluate.cc.
                                                            {
  DirectHandle<JSFunction> eval_fun;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, eval_fun,
      Compiler::GetFunctionFromEval(isolate, source, outer_info, context,
                                    LanguageMode::kSloppy, NO_PARSE_RESTRICTION,
                                    kNoSourcePosition, kNoSourcePosition,
                                    ParsingWhileDebugging::kYes));
  Handle<Object> result;
  bool success = false;
  if (throw_on_side_effect) isolate->debug()->StartSideEffectCheckMode();
  success = Execution::Call(isolate, eval_fun, receiver, {}).ToHandle(&result);
  if (throw_on_side_effect) isolate->debug()->StopSideEffectCheckMode();
  if (!success) DCHECK(isolate->has_exception());
  return success ? result : MaybeHandle<Object>();
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Execution::Call(), v8::internal::DCHECK(), v8::internal::Isolate::debug(), v8::internal::Compiler::GetFunctionFromEval(), v8::internal::Isolate::has_exception(), v8::internal::kNoSourcePosition, v8::internal::kSloppy, v8::internal::kYes, v8::internal::NO_PARSE_RESTRICTION, v8::base::internal::result, v8::internal::Debug::StartSideEffectCheckMode(), v8::internal::Debug::StopSideEffectCheckMode(), and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by Local(), and WithTopmostArguments().
FunctionGetSideEffectState()
DebugInfo::SideEffectState v8::internal::DebugEvaluate::FunctionGetSideEffectState (Isolate * isolate, DirectHandle< SharedFunctionInfo > info) [static]
Definition at line 1088 of file debug-evaluate.cc.
                                                             {
  if (v8_flags.trace_side_effect_free_debug_evaluate) {
    PrintF("[debug-evaluate] Checking function %s for side effect.\n",
           info->DebugNameCStr().get());
  }
  DCHECK(info->is_compiled());
  DCHECK(!info->needs_script_context());
  if (info->HasBytecodeArray()) {
    // Check bytecodes against allowlist.
    Handle<BytecodeArray> bytecode_array(info->GetBytecodeArray(isolate),
                                         isolate);
    if (v8_flags.trace_side_effect_free_debug_evaluate) {
      Print(*bytecode_array);
    }
    bool requires_runtime_checks = false;
    for (interpreter::BytecodeArrayIterator it(bytecode_array); !it.done();
         it.Advance()) {
      interpreter::Bytecode bytecode = it.current_bytecode();
      if (BytecodeHasNoSideEffect(bytecode)) continue;
      if (BytecodeRequiresRuntimeCheck(bytecode)) {
        requires_runtime_checks = true;
        continue;
      }
      if (v8_flags.trace_side_effect_free_debug_evaluate) {
        PrintF("[debug-evaluate] bytecode %s may cause side effect.\n",
               interpreter::Bytecodes::ToString(bytecode));
      }
      // Did not match allowlist.
      return DebugInfo::kHasSideEffects;
    }
    return requires_runtime_checks ? DebugInfo::kRequiresRuntimeChecks
                                   : DebugInfo::kHasNoSideEffect;
  } else if (info->IsApiFunction()) {
    Tagged<Code> code = info->GetCode(isolate);
    if (code->is_builtin()) {
      return code->builtin_id() == Builtin::kHandleApiCallOrConstruct
                 ? DebugInfo::kHasNoSideEffect
                 : DebugInfo::kHasSideEffects;
    }
  } else {
    // Check built-ins against allowlist.
    Builtin builtin =
        info->HasBuiltinId() ? info->builtin_id() : Builtin::kNoBuiltinId;
    if (!Builtins::IsBuiltinId(builtin)) return DebugInfo::kHasSideEffects;
    DebugInfo::SideEffectState state = BuiltinGetSideEffectState(builtin);
    return state;
  }
  return DebugInfo::kHasSideEffects;
}
References v8::internal::anonymous_namespace{debug-evaluate.cc}::BuiltinGetSideEffectState(), v8::internal::anonymous_namespace{debug-evaluate.cc}::BytecodeHasNoSideEffect(), v8::internal::anonymous_namespace{debug-evaluate.cc}::BytecodeRequiresRuntimeCheck(), code, v8::internal::DCHECK(), v8::internal::interpreter::BytecodeArrayIterator::done(), v8::internal::Builtins::IsBuiltinId(), v8::internal::DebugInfo::kHasNoSideEffect, v8::internal::DebugInfo::kHasSideEffects, v8::internal::kNoBuiltinId, v8::internal::DebugInfo::kRequiresRuntimeChecks, v8::internal::Print(), v8::internal::PrintF(), v8::internal::interpreter::Bytecodes::ToString(), and v8::internal::v8_flags.
Referenced by v8::internal::DebugInfo::GetSideEffectState().
Global()
MaybeDirectHandle< Object > v8::internal::DebugEvaluate::Global (Isolate * isolate, Handle< String > source, debug::EvaluateGlobalMode mode, REPLMode repl_mode = REPLMode::kNo) [static]
Definition at line 44 of file debug-evaluate.cc.
                                                                    {
  DirectHandle<SharedFunctionInfo> shared_info;
  if (!GetFunctionInfo(isolate, source, repl_mode).ToHandle(&shared_info)) {
    return MaybeDirectHandle<Object>();
  }
  DirectHandle<NativeContext> context = isolate->native_context();
  DirectHandle<JSFunction> function =
      Factory::JSFunctionBuilder{isolate, shared_info, context}.Build();
  DisableBreak disable_break_scope(
      isolate->debug(),
      mode == debug::EvaluateGlobalMode::kDisableBreaks ||
          mode ==
              debug::EvaluateGlobalMode::kDisableBreaksAndThrowOnSideEffect);
  if (mode == debug::EvaluateGlobalMode::kDisableBreaksAndThrowOnSideEffect) {
    isolate->debug()->StartSideEffectCheckMode();
  }
  // TODO(cbruni, 1244145): Use host-defined options from script context.
  DirectHandle<FixedArray> host_defined_options(
      Cast<Script>(function->shared()->script())->host_defined_options(),
      isolate);
  MaybeDirectHandle<Object> result = Execution::CallScript(
      isolate, function,
      DirectHandle<JSObject>(context->global_proxy(), isolate),
      host_defined_options);
  if (mode == debug::EvaluateGlobalMode::kDisableBreaksAndThrowOnSideEffect) {
    isolate->debug()->StopSideEffectCheckMode();
  }
  return result;
}
References v8::internal::Execution::CallScript(), v8::internal::Isolate::debug(), v8::internal::anonymous_namespace{debug-evaluate.cc}::GetFunctionInfo(), v8::debug::kDisableBreaks, v8::debug::kDisableBreaksAndThrowOnSideEffect, mode(), v8::internal::Isolate::native_context(), v8::base::internal::result, v8::internal::Debug::StartSideEffectCheckMode(), v8::internal::Debug::StopSideEffectCheckMode(), and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::debug::EvaluateGlobal(), and v8::internal::RUNTIME_FUNCTION().
IsSideEffectFreeIntrinsic()
bool v8::internal::DebugEvaluate::IsSideEffectFreeIntrinsic (Runtime::FunctionId id) [static]
Definition at line 306 of file debug-evaluate.cc.
                                                                  {
// Use macro to include only the non-inlined version of an intrinsic.
#define INTRINSIC_ALLOWLIST(V) \
  /* Conversions */ \
  V(NumberToStringSlow) \
  V(ToBigInt) \
  V(ToLength) \
  V(ToNumber) \
  V(ToObject) \
  V(ToString) \
  /* Type checks */ \
  V(IsArray) \
  V(IsJSProxy) \
  V(IsJSReceiver) \
  V(IsSmi) \
  /* Loads */ \
  V(LoadLookupSlotForCall) \
  V(GetPrivateMember) \
  V(GetProperty) \
  /* Arrays */ \
  V(ArraySpeciesConstructor) \
  V(HasFastPackedElements) \
  V(NewArray) \
  V(NormalizeElements) \
  V(TypedArrayGetBuffer) \
  /* Errors */ \
  V(NewTypeError) \
  V(ReThrow) \
  V(ThrowCalledNonCallable) \
  V(ThrowInvalidStringLength) \
  V(ThrowIteratorError) \
  V(ThrowIteratorResultNotAnObject) \
  V(ThrowPatternAssignmentNonCoercible) \
  V(ThrowReferenceError) \
  V(ThrowSymbolIteratorInvalid) \
  /* Strings */ \
  V(StringReplaceOneCharWithString) \
  V(StringSubstring) \
  V(StringToNumber) \
  /* BigInts */ \
  V(BigIntEqualToBigInt) \
  V(BigIntToNumber) \
  /* Literals */ \
  V(CreateArrayLiteral) \
  V(CreateObjectLiteral) \
  V(CreateRegExpLiteral) \
  V(DefineClass) \
  /* Called from builtins */ \
  V(AllocateInYoungGeneration) \
  V(AllocateInOldGeneration) \
  V(ArrayIncludes_Slow) \
  V(ArrayIndexOf) \
  V(ArrayIsArray) \
  V(GetFunctionName) \
  V(GlobalPrint) \
  V(HasProperty) \
  V(ObjectCreate) \
  V(ObjectEntries) \
  V(ObjectEntriesSkipFastPath) \
  V(ObjectHasOwnProperty) \
  V(ObjectKeys) \
  V(ObjectValues) \
  V(ObjectValuesSkipFastPath) \
  V(ObjectGetOwnPropertyNames) \
  V(ObjectGetOwnPropertyNamesTryFast) \
  V(ObjectIsExtensible) \
  V(RegExpInitializeAndCompile) \
  V(StackGuard) \
  V(HandleNoHeapWritesInterrupts) \
  V(StringAdd) \
  V(StringCharCodeAt) \
  V(StringEqual) \
  V(StringParseFloat) \
  V(StringParseInt) \
  V(SymbolDescriptiveString) \
  V(ThrowRangeError) \
  V(ThrowTypeError) \
  V(ToName) \
  V(TransitionElementsKind) \
  /* Misc. */ \
  V(Call) \
  V(CompleteInobjectSlackTrackingForMap) \
  V(HasInPrototypeChain) \
  V(IncrementUseCounter) \
  V(MaxSmi) \
  V(NewObject) \
  V(StringMaxLength) \
  V(StringToArray) \
  V(AsyncFunctionEnter) \
  V(AsyncFunctionResolve) \
  /* Test */ \
  V(GetOptimizationStatus) \
  V(OptimizeFunctionOnNextCall) \
  V(OptimizeOsr)
// Intrinsics with inline versions have to be allowlisted here a second time.
#define INLINE_INTRINSIC_ALLOWLIST(V) \
  V(AsyncFunctionEnter) \
  V(AsyncFunctionResolve)
#define CASE(Name) case Runtime::k##Name:
#define INLINE_CASE(Name) case Runtime::kInline##Name:
  switch (id) {
    INTRINSIC_ALLOWLIST(CASE)
    INLINE_INTRINSIC_ALLOWLIST(INLINE_CASE)
    return true;
    default:
      if (v8_flags.trace_side_effect_free_debug_evaluate) {
        PrintF("[debug-evaluate] intrinsic %s may cause side effect.\n",
               Runtime::FunctionForId(id)->name);
      }
      return false;
  }
#undef CASE
#undef INLINE_CASE
#undef INTRINSIC_ALLOWLIST
#undef INLINE_INTRINSIC_ALLOWLIST
}
References CASE, v8::internal::Runtime::FunctionForId(), INLINE_CASE, INLINE_INTRINSIC_ALLOWLIST, INTRINSIC_ALLOWLIST, v8::internal::name, v8::internal::PrintF(), and v8::internal::v8_flags.
Referenced by v8::internal::Debug::PerformSideEffectCheckAtBytecode().
Local()
MaybeDirectHandle< Object > v8::internal::DebugEvaluate::Local (Isolate * isolate, StackFrameId frame_id, int inlined_jsframe_index, DirectHandle< String > source, bool throw_on_side_effect) [static]
Definition at line 80 of file debug-evaluate.cc.
                                                                          {
  // Handle the processing of break.
  DisableBreak disable_break_scope(isolate->debug());
  // Get the frame where the debugging is performed.
  DebuggableStackFrameIterator it(isolate, frame_id);
#if V8_ENABLE_WEBASSEMBLY
  if (it.is_wasm()) {
#if V8_ENABLE_DRUMBRAKE
    // TODO(paolosev@microsoft.com) - Not supported by Wasm interpreter.
    if (it.is_wasm_interpreter_entry()) return {};
#endif // V8_ENABLE_DRUMBRAKE
    WasmFrame* frame = WasmFrame::cast(it.frame());
    DirectHandle<SharedFunctionInfo> outer_info(
        isolate->native_context()->empty_function()->shared(), isolate);
    DirectHandle<JSObject> context_extension = GetWasmDebugProxy(frame);
    DirectHandle<ScopeInfo> scope_info =
        ScopeInfo::CreateForWithScope(isolate, Handle<ScopeInfo>::null());
    DirectHandle<Context> context = isolate->factory()->NewWithContext(
        isolate->native_context(), scope_info, context_extension);
    return Evaluate(isolate, outer_info, context, context_extension, source,
                    throw_on_side_effect);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  CHECK(it.is_javascript());
  JavaScriptFrame* frame = it.javascript_frame();
  // This is not a lot different than DebugEvaluate::Global, except that
  // variables accessible by the function we are evaluating from are
  // materialized and included on top of the native context. Changes to
  // the materialized object are written back afterwards.
  // Note that the native context is taken from the original context chain,
  // which may not be the current native context of the isolate.
  ContextBuilder context_builder(isolate, frame, inlined_jsframe_index);
  if (isolate->has_exception()) return {};
  DirectHandle<Context> context = context_builder.evaluation_context();
  DirectHandle<JSObject> receiver(context->global_proxy(), isolate);
  MaybeDirectHandle<Object> maybe_result =
      Evaluate(isolate, context_builder.outer_info(), context, receiver, source,
               throw_on_side_effect);
  if (!maybe_result.is_null()) context_builder.UpdateValues();
  return maybe_result;
}
References CHECK, v8::internal::ScopeInfo::CreateForWithScope(), v8::internal::Isolate::debug(), Evaluate(), v8::internal::DebugEvaluate::ContextBuilder::evaluation_context(), v8::internal::Isolate::factory(), v8::internal::DebuggableStackFrameIterator::frame(), v8::internal::GetWasmDebugProxy(), v8::internal::Isolate::has_exception(), v8::internal::DebuggableStackFrameIterator::is_javascript(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::DebuggableStackFrameIterator::javascript_frame(), v8::internal::Isolate::native_context(), v8::internal::Factory::NewWithContext(), v8::internal::DebugEvaluate::ContextBuilder::outer_info(), and v8::internal::DebugEvaluate::ContextBuilder::UpdateValues().
Referenced by v8::internal::Debug::CheckBreakPoint(), v8::internal::anonymous_namespace{wasm-debug.cc}::CheckBreakPoint(), and v8::internal::DebugStackTraceIterator::Evaluate().
WithTopmostArguments()
MaybeDirectHandle< Object > v8::internal::DebugEvaluate::WithTopmostArguments (Isolate * isolate, DirectHandle< String > source) [static]
Definition at line 129 of file debug-evaluate.cc.
                                                   {
  // Handle the processing of break.
  DisableBreak disable_break_scope(isolate->debug());
  Factory* factory = isolate->factory();
  JavaScriptStackFrameIterator it(isolate);
  // Get context and receiver.
  DirectHandle<Context> native_context(
      Cast<Context>(it.frame()->context())->native_context(), isolate);
  // Materialize arguments as property on an extension object.
  DirectHandle<JSObject> materialized = factory->NewSlowJSObjectWithNullProto();
  DirectHandle<String> arguments_str = factory->arguments_string();
  JSObject::SetOwnPropertyIgnoreAttributes(
      materialized, arguments_str,
      Accessors::FunctionGetArguments(it.frame(), 0), NONE)
      .Check();
  // Materialize receiver.
  DirectHandle<Object> this_value(it.frame()->receiver(), isolate);
  DCHECK_EQ(it.frame()->IsConstructor(), IsTheHole(*this_value, isolate));
  if (!IsTheHole(*this_value, isolate)) {
    DirectHandle<String> this_str = factory->this_string();
    JSObject::SetOwnPropertyIgnoreAttributes(materialized, this_str, this_value,
                                             NONE)
        .Check();
  }
  // Use extension object in a debug-evaluate scope.
  DirectHandle<ScopeInfo> scope_info =
      ScopeInfo::CreateForWithScope(isolate, Handle<ScopeInfo>::null());
  scope_info->SetIsDebugEvaluateScope();
  DirectHandle<Context> evaluation_context = factory->NewDebugEvaluateContext(
      native_context, scope_info, materialized, DirectHandle<Context>());
  DirectHandle<SharedFunctionInfo> outer_info(
      native_context->empty_function()->shared(), isolate);
  DirectHandle<JSObject> receiver(native_context->global_proxy(), isolate);
  const bool throw_on_side_effect = false;
  MaybeDirectHandle<Object> maybe_result =
      Evaluate(isolate, outer_info, evaluation_context, receiver, source,
               throw_on_side_effect);
  return maybe_result;
}
References v8::internal::JavaScriptFrame::context(), v8::internal::ScopeInfo::CreateForWithScope(), DCHECK_EQ, v8::internal::Isolate::debug(), Evaluate(), v8::internal::Isolate::factory(), v8::internal::JavaScriptStackFrameIterator::frame(), v8::internal::Accessors::FunctionGetArguments(), v8::internal::JavaScriptFrame::IsConstructor(), v8::internal::native_context, v8::internal::Factory::NewDebugEvaluateContext(), v8::internal::Factory::NewSlowJSObjectWithNullProto(), v8::internal::NONE, v8::internal::CommonFrameWithJSLinkage::receiver(), and v8::internal::JSObject::SetOwnPropertyIgnoreAttributes().
Referenced by v8::internal::Debug::CheckBreakPoint().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-evaluate.h
/mnt/V8SourceCode/src/debug/debug-evaluate.cc