v8::base::PreciseSleepTimer Class Reference
#include <platform-win32.h>
Public Member Functions
PreciseSleepTimer ()
~PreciseSleepTimer ()
PreciseSleepTimer (const PreciseSleepTimer &other)=delete
PreciseSleepTimer & operator= (const PreciseSleepTimer &other)=delete
PreciseSleepTimer (PreciseSleepTimer &&other) V8_NOEXCEPT
PreciseSleepTimer & operator= (PreciseSleepTimer &&other) V8_NOEXCEPT
void TryInit ()
bool IsInitialized () const
void Sleep (TimeDelta interval) const
Private Member Functions
void Close ()
Private Attributes
HANDLE timer_
Detailed Description
Definition at line 17 of file platform-win32.h.
Constructor & Destructor Documentation
PreciseSleepTimer() [1/3]
v8::base::PreciseSleepTimer::PreciseSleepTimer ()
Definition at line 1190 of file platform-win32.cc.
: timer_(NULL) {}
 PreciseSleepTimer()
v8::base::PreciseSleepTimer::~PreciseSleepTimer ()
Definition at line 1191 of file platform-win32.cc.
{ Close(); }
References Close().
PreciseSleepTimer() [2/3]
v8::base::PreciseSleepTimer::PreciseSleepTimer (const PreciseSleepTimer & other) [delete]
PreciseSleepTimer() [3/3]
v8::base::PreciseSleepTimer::PreciseSleepTimer (PreciseSleepTimer && other)
Definition at line 1192 of file platform-win32.cc.
                                                                          {
  Close();
  timer_ = other.timer_;
  other.timer_ = NULL;
}
Member Function Documentation
Close()
void v8::base::PreciseSleepTimer::Close () [private]
Definition at line 1205 of file platform-win32.cc.
                              {
  if (timer_ != NULL) {
    CloseHandle(timer_);
    timer_ = NULL;
  }
}
References timer_.
Referenced by TryInit(), and ~PreciseSleepTimer().
IsInitialized()
bool v8::base::PreciseSleepTimer::IsInitialized () const
Definition at line 1204 of file platform-win32.cc.
{ return timer_ != NULL; }
References timer_.
operator=() [1/2]
PreciseSleepTimer& v8::base::PreciseSleepTimer::operator= (const PreciseSleepTimer & other) [delete]
operator=() [2/2]
PreciseSleepTimer & v8::base::PreciseSleepTimer::operator= (PreciseSleepTimer && other)
Definition at line 1197 of file platform-win32.cc.
                {
  Close();
  timer_ = other.timer_;
  other.timer_ = NULL;
  return *this;
}
Sleep()
void v8::base::PreciseSleepTimer::Sleep (TimeDelta interval) const
Definition at line 1226 of file platform-win32.cc.
                                                      {
  // Time is specified in 100 nanosecond intervals. Negative values indicate
  // relative time.
  LARGE_INTEGER due_time;
  due_time.QuadPart = -interval.InMicroseconds() * 10;
  LONG period = 0; // Not periodic; wake only once
  PTIMERAPCROUTINE completion_routine = NULL;
  LPVOID arg_to_completion_routine = NULL;
  BOOL resume = false; // No need to wake system from sleep
  CHECK(SetWaitableTimer(timer_, &due_time, period, completion_routine,
                         arg_to_completion_routine, resume));
  DWORD timeout_interval = INFINITE; // Return only when the object is signaled
  CHECK_EQ(WAIT_OBJECT_0, WaitForSingleObject(timer_, timeout_interval));
}
References CHECK, CHECK_EQ, v8::base::TimeDelta::InMicroseconds(), and timer_.
TryInit()
void v8::base::PreciseSleepTimer::TryInit ()
Definition at line 1212 of file platform-win32.cc.
                                {
  Close();
  // This flag allows precise sleep times, but is only available since Windows
  // 10 version 1803.
  DWORD flags = CREATE_WAITABLE_TIMER_HIGH_RESOLUTION;
  // The TIMER_MODIFY_STATE permission allows setting the timer, and SYNCHRONIZE
  // allows waiting for it.
  DWORD desired_access = TIMER_MODIFY_STATE | SYNCHRONIZE;
  timer_ =
      CreateWaitableTimerExW(NULL, // Cannot be inherited by child processes
                             NULL, // Cannot be looked up by name
                             flags, desired_access);
}
References Close(), flags(), and timer_.
Member Data Documentation
timer_
HANDLE v8::base::PreciseSleepTimer::timer_ [private]
Definition at line 44 of file platform-win32.h.
Referenced by Close(), IsInitialized(), Sleep(), and TryInit().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/platform/platform-win32.h
/mnt/V8SourceCode/src/base/platform/platform-win32.cc