v8::internal::LocalHeap::ThreadState Class Reference
Public Member Functions
constexpr bool IsRunning () const
constexpr ThreadState SetRunning () const V8_WARN_UNUSED_RESULT
constexpr bool IsParked () const
constexpr ThreadState SetParked () const V8_WARN_UNUSED_RESULT
constexpr bool IsSafepointRequested () const
constexpr bool IsCollectionRequested () const
constexpr bool IsRunningWithSlowPathFlag () const
Static Public Member Functions
static constexpr ThreadState Parked ()
static constexpr ThreadState Running ()
Private Member Functions
constexpr ThreadState (uint8_t value)
constexpr uint8_t raw () const
Private Attributes
uint8_t raw_state_
Friends
class LocalHeap
Detailed Description
Definition at line 250 of file local-heap.h.
Constructor & Destructor Documentation
ThreadState()
constexpr v8::internal::LocalHeap::ThreadState::ThreadState (uint8_t value) [inline], [explicit], [constexpr], [private]
Definition at line 283 of file local-heap.h.
: raw_state_(value) {}
Member Function Documentation
IsCollectionRequested()
constexpr bool v8::internal::LocalHeap::ThreadState::IsCollectionRequested () const [inline], [constexpr]
Definition at line 273 of file local-heap.h.
                                                 {
      return CollectionRequestedBit::decode(raw_state_);
    }
Referenced by v8::internal::IsolateSafepoint::ClearSafepointRequestedFlags(), v8::internal::LocalHeap::ParkSlowPath(), v8::internal::LocalHeap::SafepointSlowPath(), v8::internal::IsolateSafepoint::SetSafepointRequestedFlags(), v8::internal::LocalHeap::SleepInSafepoint(), and v8::internal::LocalHeap::UnparkSlowPath().
IsParked()
constexpr bool v8::internal::LocalHeap::ThreadState::IsParked () const [inline], [constexpr]
Definition at line 263 of file local-heap.h.
{ return ParkedBit::decode(raw_state_); }
Referenced by v8::internal::IsolateSafepoint::ClearSafepointRequestedFlags(), v8::internal::Heap::CollectGarbageFromAnyThread(), v8::internal::LocalHeap::IsParked(), and v8::internal::LocalHeap::UnparkSlowPath().
IsRunning()
constexpr bool v8::internal::LocalHeap::ThreadState::IsRunning () const [inline], [constexpr]
Definition at line 257 of file local-heap.h.
{ return !ParkedBit::decode(raw_state_); }
Referenced by v8::internal::Heap::CollectGarbageFromAnyThread(), v8::internal::Heap::GarbageCollectionEpilogueInSafepoint(), v8::internal::LocalHeap::IsRunning(), v8::internal::LocalHeap::ParkSlowPath(), v8::internal::LocalHeap::SafepointSlowPath(), v8::internal::IsolateSafepoint::SetSafepointRequestedFlags(), and v8::internal::LocalHeap::SleepInSafepoint().
IsRunningWithSlowPathFlag()
constexpr bool v8::internal::LocalHeap::ThreadState::IsRunningWithSlowPathFlag () const [inline], [constexpr]
Definition at line 277 of file local-heap.h.
                                                     {
      return IsRunning() && (raw_state_ & (SafepointRequestedBit::kMask |
                                           CollectionRequestedBit::kMask));
    }
Referenced by v8::internal::LocalHeap::Safepoint().
IsSafepointRequested()
constexpr bool v8::internal::LocalHeap::ThreadState::IsSafepointRequested () const [inline], [constexpr]
Definition at line 269 of file local-heap.h.
                                                {
      return SafepointRequestedBit::decode(raw_state_);
    }
Referenced by v8::internal::IsolateSafepoint::ClearSafepointRequestedFlags(), v8::internal::LocalHeap::ParkSlowPath(), v8::internal::LocalHeap::SafepointSlowPath(), v8::internal::IsolateSafepoint::SetSafepointRequestedFlags(), v8::internal::LocalHeap::SleepInSafepoint(), and v8::internal::LocalHeap::UnparkSlowPath().
Parked()
static constexpr ThreadState v8::internal::LocalHeap::ThreadState::Parked () [inline], [static], [constexpr]
Definition at line 252 of file local-heap.h.
                                          {
      return ThreadState(ParkedBit::kMask);
    }
Referenced by v8::internal::LocalHeap::ParkSlowPath(), and v8::internal::LocalHeap::UnparkSlowPath().
raw()
constexpr uint8_t v8::internal::LocalHeap::ThreadState::raw () const [inline], [constexpr], [private]
Definition at line 285 of file local-heap.h.
{ return raw_state_; }
Referenced by v8::internal::LocalHeap::AtomicThreadState::CompareExchangeStrong(), and v8::internal::LocalHeap::AtomicThreadState::CompareExchangeWeak().
Running()
static constexpr ThreadState v8::internal::LocalHeap::ThreadState::Running () [inline], [static], [constexpr]
Definition at line 255 of file local-heap.h.
{ return ThreadState(0); }
Referenced by v8::internal::LocalHeap::ParkSlowPath(), and v8::internal::LocalHeap::UnparkSlowPath().
SetParked()
constexpr ThreadState v8::internal::LocalHeap::ThreadState::SetParked () const [inline], [constexpr]
Definition at line 265 of file local-heap.h.
                                                                  {
      return ThreadState(ParkedBit::kMask | raw_state_);
    }
Referenced by v8::internal::LocalHeap::ParkSlowPath().
SetRunning()
constexpr ThreadState v8::internal::LocalHeap::ThreadState::SetRunning () const [inline], [constexpr]
Definition at line 259 of file local-heap.h.
                                                                   {
      return ThreadState(raw_state_ & ~ParkedBit::kMask);
    }
Referenced by v8::internal::LocalHeap::UnparkSlowPath().
Friends And Related Function Documentation
LocalHeap
friend class LocalHeap [friend]
Definition at line 289 of file local-heap.h.
Member Data Documentation
raw_state_
uint8_t v8::internal::LocalHeap::ThreadState::raw_state_ [private]
Definition at line 287 of file local-heap.h.
Referenced by v8::internal::LocalHeap::AtomicThreadState::CompareExchangeStrong(), and v8::internal::LocalHeap::AtomicThreadState::CompareExchangeWeak().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/local-heap.h