v8::internal::compiler::CreateFunctionContextParameters Class Reference
#include <js-operator.h>
Public Member Functions
CreateFunctionContextParameters (ScopeInfoRef scope_info, int slot_count, ScopeType scope_type)
ScopeInfoRef scope_info () const
int slot_count () const
ScopeType scope_type () const
Private Attributes
const ScopeInfoRef scope_info_
int const slot_count_
ScopeType const scope_type_
Friends
bool operator== (CreateFunctionContextParameters const &lhs, CreateFunctionContextParameters const &rhs)
bool operator!= (CreateFunctionContextParameters const &lhs, CreateFunctionContextParameters const &rhs)
size_t hash_value (CreateFunctionContextParameters const &parameters)
std::ostream & operator<< (std::ostream &os, CreateFunctionContextParameters const &parameters)
Detailed Description
Definition at line 365 of file js-operator.h.
Constructor & Destructor Documentation
CreateFunctionContextParameters()
v8::internal::compiler::CreateFunctionContextParameters::CreateFunctionContextParameters (ScopeInfoRef scope_info, int slot_count, ScopeType scope_type) [inline]
Definition at line 367 of file js-operator.h.
      : scope_info_(scope_info),
        slot_count_(slot_count),
        scope_type_(scope_type) {}
Member Function Documentation
scope_info()
ScopeInfoRef v8::internal::compiler::CreateFunctionContextParameters::scope_info () const [inline]
Definition at line 373 of file js-operator.h.
{ return scope_info_; }
References scope_info_.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateFunctionContext(), and v8::internal::compiler::BytecodeGraphBuilder::TryGetScopeInfo().
scope_type()
ScopeType v8::internal::compiler::CreateFunctionContextParameters::scope_type () const [inline]
Definition at line 375 of file js-operator.h.
{ return scope_type_; }
References scope_type_.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateFunctionContext().
slot_count()
int v8::internal::compiler::CreateFunctionContextParameters::slot_count () const [inline]
Definition at line 374 of file js-operator.h.
{ return slot_count_; }
References slot_count_.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateFunctionContext().
Friends And Related Function Documentation
hash_value
size_t hash_value (CreateFunctionContextParameters const & parameters) [friend]
Definition at line 207 of file js-operator.cc.
                                                                     {
  return base::hash_combine(parameters.scope_info_.object().location(),
                            parameters.slot_count(),
                            static_cast<int>(parameters.scope_type()));
}
operator!=
bool operator!= (CreateFunctionContextParameters const & lhs, CreateFunctionContextParameters const & rhs) [friend]
Definition at line 202 of file js-operator.cc.
                                                            {
  return !(lhs == rhs);
}
operator<<
std::ostream& operator<< (std::ostream & os, CreateFunctionContextParameters const & parameters) [friend]
Definition at line 213 of file js-operator.cc.
                                                                            {
  return os << parameters.slot_count() << ", " << parameters.scope_type();
}
operator==
bool operator== (CreateFunctionContextParameters const & lhs, CreateFunctionContextParameters const & rhs) [friend]
Definition at line 194 of file js-operator.cc.
                                                            {
  return lhs.scope_info_.object().location() ==
             rhs.scope_info_.object().location() &&
         lhs.slot_count() == rhs.slot_count() &&
         lhs.scope_type() == rhs.scope_type();
}
Member Data Documentation
scope_info_
const ScopeInfoRef v8::internal::compiler::CreateFunctionContextParameters::scope_info_ [private]
Definition at line 378 of file js-operator.h.
Referenced by scope_info().
scope_type_
ScopeType const v8::internal::compiler::CreateFunctionContextParameters::scope_type_ [private]
Definition at line 380 of file js-operator.h.
Referenced by scope_type().
slot_count_
int const v8::internal::compiler::CreateFunctionContextParameters::slot_count_ [private]
Definition at line 379 of file js-operator.h.
Referenced by slot_count().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h