v8::internal::torque::TypeConstraint Class Reference
#include <declarable.h>
Public Member Functions
std::optional< std::string > IsViolated (const Type *) const
Static Public Member Functions
static TypeConstraint Unconstrained ()
static TypeConstraint SubtypeConstraint (const Type *upper_bound)
Private Attributes
std::optional< const Type * > upper_bound
Detailed Description
Definition at line 560 of file declarable.h.
Member Function Documentation
IsViolated()
std::optional< std::string > v8::internal::torque::TypeConstraint::IsViolated (const Type * type) const
Definition at line 106 of file declarable.cc.
                                                                        {
  if (upper_bound && !type->IsSubtypeOf(*upper_bound)) {
    if (type->IsTopType()) {
      return TopType::cast(type)->reason();
    } else {
      return {
          ToString("expected ", *type, " to be a subtype of ", **upper_bound)};
    }
  }
  return std::nullopt;
}
References v8::internal::torque::ToString(), v8::internal::tracing::type, and upper_bound.
SubtypeConstraint()
static TypeConstraint v8::internal::torque::TypeConstraint::SubtypeConstraint (const Type * upper_bound) [inline], [static]
Definition at line 565 of file declarable.h.
                                                                   {
    TypeConstraint result;
    result.upper_bound = {upper_bound};
    return result;
  }
References v8::base::internal::result, and upper_bound.
Referenced by v8::internal::torque::ComputeConstraints().
Unconstrained()
static TypeConstraint v8::internal::torque::TypeConstraint::Unconstrained () [inline], [static]
Definition at line 564 of file declarable.h.
{ return {}; }
Referenced by v8::internal::torque::ComputeConstraints().
Member Data Documentation
upper_bound
std::optional<const Type*> v8::internal::torque::TypeConstraint::upper_bound [private]
Definition at line 572 of file declarable.h.
Referenced by IsViolated(), and SubtypeConstraint().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/declarable.h
/mnt/V8SourceCode/src/torque/declarable.cc