v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask Class Reference
Public Member Functions
JobTask (Heap *heap, const PinnedObjects &&pinned_objects)
~JobTask ()
void Run (JobDelegate *delegate) override
size_t GetMaxConcurrency (size_t worker_count) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
uint64_t trace_id () const
Private Types
using ObjectsAndSizes = std::vector< std::pair< Address, size_t > >
using PinnedObjectPerPage = std::unordered_map< MemoryChunk *, ObjectsAndSizes, base::hash< MemoryChunk * > >
using FreeSpaceHandler = std::function< void(Heap *, Address, size_t, bool)>
Private Member Functions
size_t SweepPage (FreeSpaceHandler free_space_handler, MemoryChunk *chunk, PageMetadata *page, ObjectsAndSizes &pinned_objects_on_page)
void CreateFillerFreeHandler (Address address, size_t size)
Static Private Member Functions
static void CreateFillerFreeSpaceHandler (Heap *heap, Address address, size_t size, bool should_zap)
static void AddToFreeListFreeSpaceHandler (Heap *heap, Address address, size_t size, bool should_zap)
Private Attributes
Heap *const heap_
const uint64_t trace_id_
const bool should_zap_
PinnedObjects pinned_objects_
std::atomic_bool is_done_ {false}
PinnedObjectPerPage pinned_object_per_page_
PinnedObjectPerPage::iterator next_page_iterator_
Detailed Description
Definition at line 308 of file scavenger.h.
Member Typedef Documentation
FreeSpaceHandler
using v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::FreeSpaceHandler = std::function<void(Heap*, Address, size_t, bool)> [private]
Definition at line 330 of file scavenger.h.
ObjectsAndSizes
using v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::ObjectsAndSizes = std::vector<std::pair<Address, size_t> > [private]
Definition at line 326 of file scavenger.h.
PinnedObjectPerPage
using v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::PinnedObjectPerPage = std::unordered_map<MemoryChunk*, ObjectsAndSizes, base::hash<MemoryChunk*> > [private]
Definition at line 327 of file scavenger.h.
Constructor & Destructor Documentation
JobTask()
v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::JobTask (Heap * heap, const PinnedObjects && pinned_objects)
Definition at line 669 of file scavenger.cc.
    : heap_(heap),
      trace_id_(reinterpret_cast<uint64_t>(this) ^
                heap_->tracer()->CurrentEpoch(GCTracer::Scope::SCAVENGER)),
      should_zap_(heap::ShouldZapGarbage()),
      pinned_objects_(std::move(pinned_objects)) {
  DCHECK(!pinned_objects.empty());
}
References v8::internal::DCHECK(), and v8::internal::SCAVENGER.
 JobTask()
v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::~JobTask () [inline], [virtual]
Reimplemented from v8::JobTask.
Definition at line 311 of file scavenger.h.
                 {
        DCHECK(is_done_.load(std::memory_order_relaxed));
        DCHECK(pinned_object_per_page_.empty());
        DCHECK(pinned_objects_.empty());
      }
References v8::internal::DCHECK(), is_done_, pinned_object_per_page_, and pinned_objects_.
Member Function Documentation
AddToFreeListFreeSpaceHandler()
void v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::AddToFreeListFreeSpaceHandler (Heap * heap, Address address, size_t size, bool should_zap) [static], [private]
Definition at line 758 of file scavenger.cc.
                                                   {
  if (should_zap) {
    heap::ZapBlock(address, size, heap::ZapValue());
  }
  DCHECK_EQ(OLD_SPACE, PageMetadata::FromAddress(address)->owner()->identity());
  DCHECK(PageMetadata::FromAddress(address)->SweepingDone());
  OldSpace* const old_space = heap->old_space();
  old_space->FreeDuringSweep(address, size);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::PagedSpaceBase::FreeDuringSweep(), v8::internal::PageMetadata::FromAddress(), v8::internal::OLD_SPACE, size(), v8::internal::heap::ZapBlock(), and v8::internal::heap::ZapValue().
CreateFillerFreeHandler()
void v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::CreateFillerFreeHandler (Address address, size_t size) [private]
CreateFillerFreeSpaceHandler()
void v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::CreateFillerFreeSpaceHandler (Heap * heap, Address address, size_t size, bool should_zap) [static], [private]
Definition at line 748 of file scavenger.cc.
                                                  {
  if (should_zap) {
    heap::ZapBlock(address, size, heap::ZapValue());
  }
  heap->CreateFillerObjectAt(address, static_cast<int>(size));
}
References size(), v8::internal::heap::ZapBlock(), and v8::internal::heap::ZapValue().
GetMaxConcurrency()
size_t v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::GetMaxConcurrency (size_t worker_count) const [inline], [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 319 of file scavenger.h.
                                                                   {
        return is_done_.load(std::memory_order_relaxed) ? 0 : 1;
      }
References is_done_.
Run()
void v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run (JobDelegate * delegate) [override], [virtual]
Implements v8::JobTask.
Definition at line 679 of file scavenger.cc.
                           {
#ifdef V8_COMPRESS_POINTERS_IN_MULTIPLE_CAGES
  SetCurrentIsolateScope current_isolate_scope(heap_->isolate());
#endif // V8_COMPRESS_POINTERS_IN_MULTIPLE_CAGES
  DCHECK_IMPLIES(
      delegate->IsJoiningThread(),
      heap_->IsMainThread() ||
          (!heap_->isolate()->is_shared_space_isolate() &&
           heap_->isolate()->shared_space_isolate()->heap()->IsMainThread()));
  const bool is_main_thread =
      delegate->IsJoiningThread() && heap_->IsMainThread();
  TRACE_GC_EPOCH_WITH_FLOW(
      heap_->tracer(),
      GCTracer::Scope::SCAVENGER_BACKGROUND_QUARANTINED_PAGE_SWEEPING,
      is_main_thread ? ThreadKind::kMain : ThreadKind::kBackground, trace_id(),
      TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
  DCHECK(!is_done_.load(std::memory_order_relaxed));
  DCHECK(!pinned_objects_.empty());
  if (pinned_object_per_page_.empty()) {
    // Populate the per page map.
    for (const PinnedObjectEntry& entry : pinned_objects_) {
      DCHECK(!HeapLayout::IsSelfForwarded(
          HeapObject::FromAddress(entry.address), heap_->isolate()));
      MemoryChunk* chunk = MemoryChunk::FromAddress(entry.address);
      DCHECK(!chunk->IsQuarantined());
      ObjectsAndSizes& objects_for_page = pinned_object_per_page_[chunk];
      DCHECK(!std::any_of(objects_for_page.begin(), objects_for_page.end(),
                          [entry](auto& object_and_size) {
                            return object_and_size.first == entry.address;
                          }));
      objects_for_page.emplace_back(entry.address, entry.size);
    }
    // Initialize the iterator.
    next_page_iterator_ = pinned_object_per_page_.begin();
    DCHECK_NE(next_page_iterator_, pinned_object_per_page_.end());
  }
  // Sweep all quarantined pages.
  while (next_page_iterator_ != pinned_object_per_page_.end()) {
    if (delegate->ShouldYield()) {
      TRACE_GC_NOTE("Quarantined page sweeping preempted");
      return;
    }
    MemoryChunk* chunk = next_page_iterator_->first;
    PageMetadata* page = static_cast<PageMetadata*>(chunk->Metadata());
    DCHECK(!chunk->IsFromPage());
    if (chunk->IsToPage()) {
      SweepPage(CreateFillerFreeSpaceHandler, chunk, page,
                next_page_iterator_->second);
    } else {
      DCHECK_EQ(chunk->Metadata()->owner()->identity(), OLD_SPACE);
      base::MutexGuard guard(page->mutex());
      // If for some reason the page is swept twice, this DCHECK will fail.
      DCHECK_EQ(page->area_size(), page->allocated_bytes());
      size_t filler_size_on_page =
          SweepPage(AddToFreeListFreeSpaceHandler, chunk, page,
                    next_page_iterator_->second);
      DCHECK_EQ(page->owner()->identity(), OLD_SPACE);
      OldSpace* old_space = static_cast<OldSpace*>(page->owner());
      old_space->RelinkQuarantinedPageFreeList(page, filler_size_on_page);
    }
    next_page_iterator_++;
  }
  is_done_.store(true, std::memory_order_relaxed);
  pinned_object_per_page_.clear();
  pinned_objects_.clear();
}
References v8::internal::MemoryChunkMetadata::allocated_bytes(), v8::base::any_of(), v8::internal::MemoryChunkMetadata::area_size(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NE, v8::internal::MemoryChunk::FromAddress(), v8::internal::HeapObject::FromAddress(), v8::internal::Isolate::heap(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::heap_, v8::internal::BaseSpace::identity(), v8::internal::Isolate::is_shared_space_isolate(), v8::internal::MemoryChunk::IsFromPage(), v8::JobDelegate::IsJoiningThread(), v8::internal::Heap::IsMainThread(), v8::internal::Heap::isolate(), v8::internal::MemoryChunk::IsQuarantined(), v8::internal::HeapLayout::IsSelfForwarded(), v8::internal::MemoryChunk::IsToPage(), v8::internal::kBackground, v8::internal::kMain, v8::internal::MemoryChunk::Metadata(), v8::internal::MutablePageMetadata::mutex(), v8::internal::OLD_SPACE, v8::internal::MemoryChunkMetadata::owner(), v8::internal::MutablePageMetadata::owner(), v8::internal::OldSpace::RelinkQuarantinedPageFreeList(), v8::internal::Isolate::shared_space_isolate(), v8::JobDelegate::ShouldYield(), TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC_EPOCH_WITH_FLOW, TRACE_GC_NOTE, and v8::internal::Heap::tracer().
SweepPage()
size_t v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::SweepPage (FreeSpaceHandler free_space_handler, MemoryChunk * chunk, PageMetadata * page, ObjectsAndSizes & pinned_objects_on_page) [private]
Definition at line 770 of file scavenger.cc.
                                             {
  DCHECK_EQ(page, chunk->Metadata());
  DCHECK(!pinned_objects_on_page.empty());
  Address start = page->area_start();
  std::sort(pinned_objects_on_page.begin(), pinned_objects_on_page.end());
  size_t filler_size_on_page = 0;
  for (const auto& [object_adress, object_size] : pinned_objects_on_page) {
    DCHECK_LE(start, object_adress);
    if (start != object_adress) {
      size_t filler_size = object_adress - start;
      free_space_handler(heap_, start, filler_size, should_zap_);
      filler_size_on_page += filler_size;
    }
    start = object_adress + object_size;
  }
  Address end = page->area_end();
  if (start != end) {
    size_t filler_size = end - start;
    free_space_handler(heap_, start, filler_size, should_zap_);
    filler_size_on_page += filler_size;
  }
  return filler_size_on_page;
}
References v8::internal::MemoryChunkMetadata::area_end(), v8::internal::MemoryChunkMetadata::area_start(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::compiler::end(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::heap_, v8::internal::MemoryChunk::Metadata(), and v8::base::sort().
trace_id()
uint64_t v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::trace_id () const [inline]
Definition at line 323 of file scavenger.h.
{ return trace_id_; }
References trace_id_.
Member Data Documentation
heap_
Heap* const v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::heap_ [private]
Definition at line 342 of file scavenger.h.
is_done_
std::atomic_bool v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::is_done_ {false} [private]
Definition at line 347 of file scavenger.h.
Referenced by GetMaxConcurrency(), and ~JobTask().
next_page_iterator_
PinnedObjectPerPage::iterator v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::next_page_iterator_ [private]
Definition at line 349 of file scavenger.h.
pinned_object_per_page_
PinnedObjectPerPage v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::pinned_object_per_page_ [private]
Definition at line 348 of file scavenger.h.
Referenced by ~JobTask().
pinned_objects_
PinnedObjects v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::pinned_objects_ [private]
Definition at line 345 of file scavenger.h.
Referenced by ~JobTask().
should_zap_
const bool v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::should_zap_ [private]
Definition at line 344 of file scavenger.h.
trace_id_
const uint64_t v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::trace_id_ [private]
Definition at line 343 of file scavenger.h.
Referenced by trace_id().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/scavenger.h
/mnt/V8SourceCode/src/heap/scavenger.cc