v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer Class Reference
Classes
struct EditGraphArea
class FurthestReaching
struct Path
struct Point
class ResultWriter
struct Snake
Static Public Member Functions
static void MyersDiff (Comparator::Input *input, Comparator::Output *output)
Private Member Functions
MyersDiffer (Comparator::Input *input, Comparator::Output *output)
std::optional< Path > FindEditPath ()
std::optional< Path > FindEditPath (Point from, Point to)
std::optional< Snake > FindMiddleSnake (Point from, Point to)
std::optional< Snake > ShortestEditForward (const EditGraphArea &area, int d)
std::optional< Snake > ShortestEditReverse (const EditGraphArea &area, int d)
void WriteResult (const Path &path)
Point WalkDiagonal (ResultWriter &writer, Point p1, Point p2)
Private Attributes
Comparator::Input * input_
Comparator::Output * output_
FurthestReaching fr_forward_
FurthestReaching fr_reverse_
Detailed Description
Definition at line 56 of file liveedit-diff.cc.
Constructor & Destructor Documentation
MyersDiffer()
v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::MyersDiffer (Comparator::Input * input, Comparator::Output * output) [inline], [private]
Definition at line 147 of file liveedit-diff.cc.
      : input_(input),
        output_(output),
        fr_forward_(input->GetLength1() + input->GetLength2() + 1),
        fr_reverse_(input->GetLength1() + input->GetLength2() + 1) {
    // Length1 + Length2 + 1 is the upper bound for our work arrays.
    // We allocate the work arrays once and reuse them for all invocations of
    // `FindMiddleSnake`.
  }
Member Function Documentation
FindEditPath() [1/2]
std::optional<Path> v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::FindEditPath () [inline], [private]
Definition at line 157 of file liveedit-diff.cc.
                                   {
    return FindEditPath(Point{0, 0},
                        Point{input_->GetLength1(), input_->GetLength2()});
  }
References v8::internal::Comparator::Input::GetLength1(), and v8::internal::Comparator::Input::GetLength2().
Referenced by MyersDiff().
FindEditPath() [2/2]
std::optional<Path> v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::FindEditPath (Point from, Point to) [inline], [private]
Definition at line 163 of file liveedit-diff.cc.
                                                       {
    // Divide the area described by `from` and `to` by finding the
    // middle snake ...
    std::optional<Snake> snake = FindMiddleSnake(from, to);
    if (!snake) return std::nullopt;
    // ... and then conquer the two resulting sub-areas.
    std::optional<Path> head = FindEditPath(from, snake->from);
    std::optional<Path> tail = FindEditPath(snake->to, to);
    // Combine `head` and `tail` or use the snake start/end points for
    // zero-size areas.
    Path result;
    if (head) {
      result.Add(*head);
    } else {
      result.Add(snake->from);
    }
    if (tail) {
      result.Add(*tail);
    } else {
      result.Add(snake->to);
    }
    return result;
  }
References v8::base::internal::result.
FindMiddleSnake()
std::optional<Snake> v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::FindMiddleSnake (Point from, Point to) [inline], [private]
Definition at line 201 of file liveedit-diff.cc.
                                                           {
    EditGraphArea area{from, to};
    if (area.size() == 0) return std::nullopt;
    // Initialise the furthest reaching vectors with an "artificial" edge
    // from (0, -1) -> (0, 0) and (N, -M) -> (N, M) to serve as the initial
    // snake when d = 0.
    fr_forward_[1] = area.top_left.x;
    fr_reverse_[-1] = area.bottom_right.x;
    for (int d = 0; d <= std::ceil(area.size() / 2.0f); ++d) {
      if (auto snake = ShortestEditForward(area, d)) return snake;
      if (auto snake = ShortestEditReverse(area, d)) return snake;
    }
    return std::nullopt;
  }
MyersDiff()
static void v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::MyersDiff (Comparator::Input * input, Comparator::Output * output) [inline], [static]
Definition at line 395 of file liveedit-diff.cc.
                                                                          {
    MyersDiffer differ(input, output);
    auto result = differ.FindEditPath();
    if (!result) return; // Empty input doesn't produce a path.
    differ.WriteResult(*result);
  }
References FindEditPath(), v8::base::internal::result, and WriteResult().
ShortestEditForward()
std::optional<Snake> v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ShortestEditForward (const EditGraphArea & area, int d) [inline], [private]
Definition at line 226 of file liveedit-diff.cc.
                                                                           {
    Point from, to;
    // We alternate between looking at odd and even k-diagonals. That is
    // because when we extend a `d-path` by a single move we can at most move
    // one diagonal over. That is either move from `k-1` to `k` or from `k+1` to
    // `k`. That is if `d` is even (odd) then we require only the odd (even)
    // k-diagonals calculated in step `d-1`.
    for (int k = -d; k <= d; k += 2) {
      if (k == -d || (k != d && fr_forward_[k - 1] < fr_forward_[k + 1])) {
        // Move downwards, i.e. add an insertion, because either we are at the
        // edge and downwards is the only way we can move, or because the
        // `d-1`-path along the `k+1` diagonal reaches further on the x-axis
        // than the `d-1`-path along the `k-1` diagonal.
        from.x = to.x = fr_forward_[k + 1];
      } else {
        // Move right, i.e. add a deletion.
        from.x = fr_forward_[k - 1];
        to.x = from.x + 1;
      }
      // Calculate y via y = x - k. We need to adjust k though since the k=0
      // diagonal is centered on `area.top_left` and not (0, 0).
      to.y = area.top_left.y + (to.x - area.top_left.x) - k;
      from.y = (d == 0 || from.x != to.x) ? to.y : to.y - 1;
      // Extend the snake diagonally as long as we can.
      while (to < area.bottom_right && input_->Equals(to.x, to.y)) {
        ++to.x;
        ++to.y;
      }
      fr_forward_[k] = to.x;
      // Check whether there is a reverse path on this k-diagonal which we
      // are overlapping with. If yes, that is our snake.
      const bool odd = area.delta() % 2 != 0;
      const int l = k - area.delta();
      if (odd && l >= (-d + 1) && l <= d - 1 && to.x >= fr_reverse_[l]) {
        return Snake{from, to};
      }
    }
    return std::nullopt;
  }
References v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::EditGraphArea::delta(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Equals(), v8::internal::compiler::turboshaft::l, v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::EditGraphArea::top_left, v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::Point::x, and v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::Point::y.
ShortestEditReverse()
std::optional<Snake> v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ShortestEditReverse (const EditGraphArea & area, int d) [inline], [private]
Definition at line 274 of file liveedit-diff.cc.
                                                                           {
    Point from, to;
    // We alternate between looking at odd and even l-diagonals. That is
    // because when we extend a `d-path` by a single move we can at most move
    // one diagonal over. That is either move from `l-1` to `l` or from `l+1` to
    // `l`. That is if `d` is even (odd) then we require only the odd (even)
    // l-diagonals calculated in step `d-1`.
    for (int l = d; l >= -d; l -= 2) {
      if (l == d || (l != -d && fr_reverse_[l - 1] > fr_reverse_[l + 1])) {
        // Move upwards, i.e. add an insertion, because either we are at the
        // edge and upwards is the only way we can move, or because the
        // `d-1`-path along the `l-1` diagonal reaches further on the x-axis
        // than the `d-1`-path along the `l+1` diagonal.
        from.x = to.x = fr_reverse_[l - 1];
      } else {
        // Move left, i.e. add a deletion.
        from.x = fr_reverse_[l + 1];
        to.x = from.x - 1;
      }
      // Calculate y via y = x - k. We need to adjust k though since the k=0
      // diagonal is centered on `area.top_left` and not (0, 0).
      const int k = l + area.delta();
      to.y = area.top_left.y + (to.x - area.top_left.x) - k;
      from.y = (d == 0 || from.x != to.x) ? to.y : to.y + 1;
      // Extend the snake diagonally as long as we can.
      while (area.top_left < to && input_->Equals(to.x - 1, to.y - 1)) {
        --to.x;
        --to.y;
      }
      fr_reverse_[l] = to.x;
      // Check whether there is a path on this k-diagonal which we
      // are overlapping with. If yes, that is our snake.
      const bool even = area.delta() % 2 == 0;
      if (even && k >= -d && k <= d && to.x <= fr_forward_[k]) {
        // Invert the points so the snake goes left to right, top to bottom.
        return Snake{to, from};
      }
    }
    return std::nullopt;
  }
References v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::EditGraphArea::delta(), v8::internal::Comparator::Input::Equals(), v8::internal::compiler::turboshaft::l, v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::EditGraphArea::top_left, v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::Point::x, and v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::Point::y.
WalkDiagonal()
Point v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::WalkDiagonal (ResultWriter & writer, Point p1, Point p2) [inline], [private]
Definition at line 385 of file liveedit-diff.cc.
                                                               {
    while (p1.x < p2.x && p1.y < p2.y && input_->Equals(p1.x, p1.y)) {
      writer.RecordNoModification(p1);
      p1.x++;
      p1.y++;
    }
    return p1;
  }
References v8::internal::Comparator::Input::Equals(), v8::internal::p1, v8::internal::p2, and v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ResultWriter::RecordNoModification().
WriteResult()
void v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::WriteResult (const Path & path) [inline], [private]
Definition at line 360 of file liveedit-diff.cc.
                                     {
    ResultWriter writer(output_);
    for (size_t i = 1; i < path.points.size(); ++i) {
      Point p1 = path.points[i - 1];
      Point p2 = path.points[i];
      p1 = WalkDiagonal(writer, p1, p2);
      const int cmp = (p2.x - p1.x) - (p2.y - p1.y);
      if (cmp == -1) {
        writer.RecordInsertionOrDeletion(p1);
        p1.y++;
      } else if (cmp == 1) {
        writer.RecordInsertionOrDeletion(p1);
        p1.x++;
      }
      p1 = WalkDiagonal(writer, p1, p2);
      DCHECK(p1.x == p2.x && p1.y == p2.y);
    }
    // Write one diagonal in the end to flush out any open chunk.
    writer.RecordNoModification(path.points.back());
  }
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::p1, v8::internal::p2, v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::Path::points, v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ResultWriter::RecordInsertionOrDeletion(), and v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ResultWriter::RecordNoModification().
Referenced by MyersDiff().
Member Data Documentation
fr_forward_
FurthestReaching v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::fr_forward_ [private]
Definition at line 135 of file liveedit-diff.cc.
fr_reverse_
FurthestReaching v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::fr_reverse_ [private]
Definition at line 145 of file liveedit-diff.cc.
input_
Comparator::Input* v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::input_ [private]
Definition at line 129 of file liveedit-diff.cc.
output_
Comparator::Output* v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::output_ [private]
Definition at line 130 of file liveedit-diff.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/liveedit-diff.cc