v8::internal::ETWJITInterface::EtwIsolateCaptureStateMonitor Class Reference
#include <etw-isolate-capture-state-monitor-win.h>
Public Member Functions
EtwIsolateCaptureStateMonitor (base::Mutex *mutex, size_t pending_isolate_count)
EtwIsolateCaptureStateMonitor (const EtwIsolateCaptureStateMonitor &)=delete
EtwIsolateCaptureStateMonitor & operator= (const EtwIsolateCaptureStateMonitor &)=delete
bool WaitFor (const base::TimeDelta &delta)
void Notify ()
Private Attributes
base::Mutex * mutex_
size_t pending_isolate_count_
base::ConditionVariable isolates_ready_cv_
base::TimeTicks wait_started_
Detailed Description
Definition at line 16 of file etw-isolate-capture-state-monitor-win.h.
Constructor & Destructor Documentation
EtwIsolateCaptureStateMonitor() [1/2]
v8::internal::ETWJITInterface::EtwIsolateCaptureStateMonitor::EtwIsolateCaptureStateMonitor (base::Mutex * mutex, size_t pending_isolate_count)
Definition at line 16 of file etw-isolate-capture-state-monitor-win.cc.
    : mutex_(mutex), pending_isolate_count_(pending_isolate_count) {}
EtwIsolateCaptureStateMonitor() [2/2]
v8::internal::ETWJITInterface::EtwIsolateCaptureStateMonitor::EtwIsolateCaptureStateMonitor (const EtwIsolateCaptureStateMonitor &) [delete]
Member Function Documentation
Notify()
void v8::internal::ETWJITInterface::EtwIsolateCaptureStateMonitor::Notify ()
Definition at line 58 of file etw-isolate-capture-state-monitor-win.cc.
                                           {
  {
    ETWTRACEDBG << "Notify taking mutex" << std::endl;
    base::MutexGuard lock(mutex_);
    pending_isolate_count_--;
    ETWTRACEDBG << "Got mutex and isolate count reduced to "
                << pending_isolate_count_ << std::endl;
  }
  ETWTRACEDBG << "Released mutex preparing to notifyOne " << std::endl;
  isolates_ready_cv_.NotifyOne();
  ETWTRACEDBG << "Finished notifyOne " << std::endl;
}
References ETWTRACEDBG, isolates_ready_cv_, mutex_, v8::base::ConditionVariable::NotifyOne(), and pending_isolate_count_.
operator=()
EtwIsolateCaptureStateMonitor& v8::internal::ETWJITInterface::EtwIsolateCaptureStateMonitor::operator= (const EtwIsolateCaptureStateMonitor &) [delete]
WaitFor()
bool v8::internal::ETWJITInterface::EtwIsolateCaptureStateMonitor::WaitFor (const base::TimeDelta & delta)
Definition at line 20 of file etw-isolate-capture-state-monitor-win.cc.
                                                                      {
  wait_started_ = base::TimeTicks::Now();
  base::TimeDelta remaining = delta;
  if (pending_isolate_count_ == 0) {
    return true;
  }
  ETWTRACEDBG << "Waiting for " << pending_isolate_count_
              << " isolates for up to " << remaining.InMilliseconds()
              << std::endl;
  while (isolates_ready_cv_.WaitFor(mutex_, remaining)) {
    ETWTRACEDBG << "WaitFor woke up: " << pending_isolate_count_
                << " isolates remaining " << std::endl;
    if (pending_isolate_count_ == 0) {
      return true;
    }
    // If the timeout has expired, return false.
    auto elapsed = base::TimeTicks::Now() - wait_started_;
    if (elapsed >= remaining) {
      ETWTRACEDBG << "Elapsed is " << elapsed.InMilliseconds()
                  << " greater than reminaing " << remaining.InMilliseconds()
                  << std::endl;
      return false;
    }
    // If the condition variable was woken up spuriously, adjust the timeout.
    remaining -= elapsed;
    ETWTRACEDBG << "New remaining " << remaining.InMilliseconds()
                << " resuming waiting" << std::endl;
  }
  // Propagate the WaitFor false return value (timeout before being notified) to
  // the caller.
  return false;
}
References ETWTRACEDBG, v8::base::TimeDelta::InMilliseconds(), isolates_ready_cv_, mutex_, v8::base::TimeTicks::Now(), pending_isolate_count_, wait_started_, and v8::base::ConditionVariable::WaitFor().
Member Data Documentation
isolates_ready_cv_
base::ConditionVariable v8::internal::ETWJITInterface::EtwIsolateCaptureStateMonitor::isolates_ready_cv_ [private]
Definition at line 36 of file etw-isolate-capture-state-monitor-win.h.
Referenced by Notify(), and WaitFor().
mutex_
base::Mutex* v8::internal::ETWJITInterface::EtwIsolateCaptureStateMonitor::mutex_ [private]
Definition at line 34 of file etw-isolate-capture-state-monitor-win.h.
Referenced by Notify(), and WaitFor().
pending_isolate_count_
size_t v8::internal::ETWJITInterface::EtwIsolateCaptureStateMonitor::pending_isolate_count_ [private]
Definition at line 35 of file etw-isolate-capture-state-monitor-win.h.
Referenced by Notify(), and WaitFor().
wait_started_
base::TimeTicks v8::internal::ETWJITInterface::EtwIsolateCaptureStateMonitor::wait_started_ [private]
Definition at line 39 of file etw-isolate-capture-state-monitor-win.h.
Referenced by WaitFor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/diagnostics/etw-isolate-capture-state-monitor-win.h
/mnt/V8SourceCode/src/diagnostics/etw-isolate-capture-state-monitor-win.cc