v8::internal::CircularStructureMessageBuilder Class Reference
Public Member Functions
CircularStructureMessageBuilder (Isolate *isolate)
void AppendStartLine (DirectHandle< Object > start_object)
void AppendNormalLine (DirectHandle< Object > key, DirectHandle< Object > object)
void AppendClosingLine (DirectHandle< Object > closing_key)
void AppendEllipsis ()
MaybeDirectHandle< String > Finish ()
Private Member Functions
void AppendConstructorName (DirectHandle< Object > object)
void AppendKey (DirectHandle< Object > key)
void AppendSmi (Tagged< Smi > smi)
Private Attributes
IncrementalStringBuilder builder_
Static Private Attributes
static constexpr const char * kStartPrefix = `\n --> `
static constexpr const char * kEndPrefix = `\n --- `
static constexpr const char * kLinePrefix = `\n | `
Detailed Description
Definition at line 834 of file json-stringifier.cc.
Constructor & Destructor Documentation
CircularStructureMessageBuilder()
v8::internal::CircularStructureMessageBuilder::CircularStructureMessageBuilder (Isolate * isolate) [inline], [explicit]
Definition at line 836 of file json-stringifier.cc.
      : builder_(isolate) {}
Member Function Documentation
AppendClosingLine()
void v8::internal::CircularStructureMessageBuilder::AppendClosingLine (DirectHandle< Object > closing_key) [inline]
Definition at line 852 of file json-stringifier.cc.
                                                           {
    builder_.AppendCString(kEndPrefix);
    AppendKey(closing_key);
    builder_.AppendCStringLiteral(" closes the circle");
  }
References v8::internal::IncrementalStringBuilder::AppendCString(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), AppendKey(), builder_, and kEndPrefix.
Referenced by v8::internal::JsonStringifier::ConstructCircularStructureErrorMessage().
AppendConstructorName()
void v8::internal::CircularStructureMessageBuilder::AppendConstructorName (DirectHandle< Object > object) [inline], [private]
Definition at line 866 of file json-stringifier.cc.
                                                          {
    builder_.AppendCharacter('\'');
    DirectHandle<String> constructor_name = JSReceiver::GetConstructorName(
        builder_.isolate(), Cast<JSReceiver>(object));
    builder_.AppendString(constructor_name);
    builder_.AppendCharacter('\'');
  }
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendString(), builder_, v8::internal::JSReceiver::GetConstructorName(), and v8::internal::IncrementalStringBuilder::isolate().
Referenced by AppendNormalLine(), and AppendStartLine().
AppendEllipsis()
void v8::internal::CircularStructureMessageBuilder::AppendEllipsis () [inline]
Definition at line 858 of file json-stringifier.cc.
                        {
    builder_.AppendCString(kLinePrefix);
    builder_.AppendCStringLiteral("...");
  }
References v8::internal::IncrementalStringBuilder::AppendCString(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), builder_, and kLinePrefix.
Referenced by v8::internal::JsonStringifier::ConstructCircularStructureErrorMessage().
AppendKey()
void v8::internal::CircularStructureMessageBuilder::AppendKey (DirectHandle< Object > key) [inline], [private]
Definition at line 875 of file json-stringifier.cc.
                                           {
    if (IsSmi(*key)) {
      builder_.AppendCStringLiteral("index ");
      AppendSmi(Cast<Smi>(*key));
      return;
    }
    CHECK(IsString(*key));
    DirectHandle<String> key_as_string = Cast<String>(key);
    if (key_as_string->length() == 0) {
      builder_.AppendCStringLiteral("<anonymous>");
    } else {
      builder_.AppendCStringLiteral("property '");
      builder_.AppendString(key_as_string);
      builder_.AppendCharacter('\'');
    }
  }
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), AppendSmi(), v8::internal::IncrementalStringBuilder::AppendString(), builder_, CHECK, v8::internal::IsSmi(), and v8::internal::key.
Referenced by AppendClosingLine(), and AppendNormalLine().
AppendNormalLine()
void v8::internal::CircularStructureMessageBuilder::AppendNormalLine (DirectHandle< Object > key, DirectHandle< Object > object) [inline]
Definition at line 845 of file json-stringifier.cc.
                                                                               {
    builder_.AppendCString(kLinePrefix);
    AppendKey(key);
    builder_.AppendCStringLiteral(" -> object with constructor ");
    AppendConstructorName(object);
  }
References AppendConstructorName(), v8::internal::IncrementalStringBuilder::AppendCString(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), AppendKey(), builder_, v8::internal::key, and kLinePrefix.
Referenced by v8::internal::JsonStringifier::ConstructCircularStructureErrorMessage().
AppendSmi()
void v8::internal::CircularStructureMessageBuilder::AppendSmi (Tagged< Smi > smi) [inline], [private]
Definition at line 893 of file json-stringifier.cc.
                                  {
    static_assert(Smi::kMaxValue <= 2147483647);
    static_assert(Smi::kMinValue >= -2147483648);
    // sizeof(string) includes \0.
    static constexpr uint32_t kBufferSize = sizeof("-2147483648") - 1;
    char chars[kBufferSize];
    base::Vector<char> buffer(chars, kBufferSize);
    builder_.AppendString(IntToStringView(smi.value(), buffer));
  }
References v8::internal::IncrementalStringBuilder::AppendString(), builder_, v8::internal::IntToStringView(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, v8::internal::Smi::kMaxValue, v8::internal::Smi::kMinValue, and v8::internal::Tagged< Smi >::value().
Referenced by AppendKey().
AppendStartLine()
void v8::internal::CircularStructureMessageBuilder::AppendStartLine (DirectHandle< Object > start_object) [inline]
Definition at line 839 of file json-stringifier.cc.
                                                          {
    builder_.AppendCString(kStartPrefix);
    builder_.AppendCStringLiteral("starting at object with constructor ");
    AppendConstructorName(start_object);
  }
References AppendConstructorName(), v8::internal::IncrementalStringBuilder::AppendCString(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), builder_, and kStartPrefix.
Referenced by v8::internal::JsonStringifier::ConstructCircularStructureErrorMessage().
Finish()
MaybeDirectHandle<String> v8::internal::CircularStructureMessageBuilder::Finish () [inline]
Definition at line 863 of file json-stringifier.cc.
{ return builder_.Finish(); }
References builder_, and v8::internal::IncrementalStringBuilder::Finish().
Referenced by v8::internal::JsonStringifier::ConstructCircularStructureErrorMessage().
Member Data Documentation
builder_
IncrementalStringBuilder v8::internal::CircularStructureMessageBuilder::builder_ [private]
Definition at line 903 of file json-stringifier.cc.
Referenced by AppendClosingLine(), AppendConstructorName(), AppendEllipsis(), AppendKey(), AppendNormalLine(), AppendSmi(), AppendStartLine(), and Finish().
kEndPrefix
constexpr const char* v8::internal::CircularStructureMessageBuilder::kEndPrefix = `\n --- ` [static], [constexpr], [private]
Definition at line 905 of file json-stringifier.cc.
Referenced by AppendClosingLine().
kLinePrefix
constexpr const char* v8::internal::CircularStructureMessageBuilder::kLinePrefix = `\n | ` [static], [constexpr], [private]
Definition at line 906 of file json-stringifier.cc.
Referenced by AppendEllipsis(), and AppendNormalLine().
kStartPrefix
constexpr const char* v8::internal::CircularStructureMessageBuilder::kStartPrefix = `\n --> ` [static], [constexpr], [private]
Definition at line 904 of file json-stringifier.cc.
Referenced by AppendStartLine().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/json/json-stringifier.cc