v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next > Class Template Reference
#include <fast-api-call-lowering-reducer.h>
Public Member Functions
OpIndex REDUCE() FastApiCall (V< FrameState > frame_state, V< Object > data_argument, V< Context > context, base::Vector< const OpIndex > arguments, const FastApiCallParameters *parameters, base::Vector< const RegisterRepresentation > out_reps)
Private Member Functions
template<typename T >
V< T > Checked (V< Tuple< T, Word32 >> result, Label<> &otherwise)
OpIndex AdaptFastCallArgument (OpIndex argument, CTypeInfo arg_type, Label<> &handle_error)
OpIndex ClampFastCallArgument (V< Float64 > argument, CTypeInfo::Type scalar_type)
V< Any > DefaultReturnValue (const CFunctionInfo *c_signature)
V< Any > ConvertReturnValue (const CFunctionInfo *c_signature, OpIndex result)
V< HeapObject > BuildAllocateJSExternalObject (V< WordPtr > pointer)
OpIndex WrapFastCall (const TSCallDescriptor *descriptor, OpIndex callee, V< FrameState > frame_state, V< Context > context, base::Vector< const OpIndex > arguments)
Private Attributes
Isolate * isolate_ = __ data() -> isolate()
Factory * factory_ = isolate_->factory()
Detailed Description
template<typename Next>
class v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >
Definition at line 23 of file fast-api-call-lowering-reducer.h.
Member Function Documentation
AdaptFastCallArgument()
template<typename Next >
OpIndex v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::AdaptFastCallArgument (OpIndex argument, CTypeInfo arg_type, Label<> & handle_error) [inline], [private]
Definition at line 152 of file fast-api-call-lowering-reducer.h.
                                                       {
    START_ALLOW_USE_DEPRECATED()
    switch (arg_type.GetSequenceType()) {
      case CTypeInfo::SequenceType::kScalar: {
        uint8_t flags = static_cast<uint8_t>(arg_type.GetFlags());
        if (flags & static_cast<uint8_t>(CTypeInfo::Flags::kEnforceRangeBit)) {
          switch (arg_type.GetType()) {
            case CTypeInfo::Type::kInt32: {
              auto result = __ TryTruncateFloat64ToInt32(argument);
              return Checked(result, handle_error);
            }
            case CTypeInfo::Type::kUint32: {
              auto result = __ TryTruncateFloat64ToUint32(argument);
              return Checked(result, handle_error);
            }
            case CTypeInfo::Type::kInt64: {
              auto result = __ TryTruncateFloat64ToInt64(argument);
              return Checked(result, handle_error);
            }
            case CTypeInfo::Type::kUint64: {
              auto result = __ TryTruncateFloat64ToUint64(argument);
              return Checked(result, handle_error);
            }
            default: {
              GOTO(handle_error);
              return argument;
            }
          }
        } else if (flags & static_cast<uint8_t>(CTypeInfo::Flags::kClampBit)) {
          return ClampFastCallArgument(argument, arg_type.GetType());
        } else {
          switch (arg_type.GetType()) {
            case CTypeInfo::Type::kV8Value: {
              return __ AdaptLocalArgument(argument);
            }
            case CTypeInfo::Type::kFloat32: {
              return __ TruncateFloat64ToFloat32(argument);
            }
            case CTypeInfo::Type::kPointer: {
              // Check that the value is a HeapObject.
              GOTO_IF(__ ObjectIsSmi(argument), handle_error);
              Label<WordPtr> done(this);
              // Check if the value is null.
              GOTO_IF(UNLIKELY(__ TaggedEqual(
                          argument, __ HeapConstant(factory_->null_value()))),
                      done, 0);
              // Check that the value is a JSExternalObject.
              GOTO_IF_NOT(
                  __ TaggedEqual(__ LoadMapField(argument),
                                 __ HeapConstant(factory_->external_map())),
                  handle_error);
              GOTO(done, __ template LoadField<WordPtr>(
                             V<HeapObject>::Cast(argument),
                             AccessBuilder::ForJSExternalObjectValue()));
              BIND(done, result);
              return result;
            }
            case CTypeInfo::Type::kSeqOneByteString: {
              // Check that the value is a HeapObject.
              GOTO_IF(__ ObjectIsSmi(argument), handle_error);
              V<HeapObject> argument_obj = V<HeapObject>::Cast(argument);
              V<Map> map = __ LoadMapField(argument_obj);
              V<Word32> instance_type = __ LoadInstanceTypeField(map);
              V<Word32> encoding = __ Word32BitwiseAnd(
                  instance_type, kStringRepresentationAndEncodingMask);
              GOTO_IF_NOT(__ Word32Equal(encoding, kSeqOneByteStringTag),
                          handle_error);
              V<WordPtr> length_in_bytes = __ template LoadField<WordPtr>(
                  argument_obj, AccessBuilder::ForStringLength());
              V<WordPtr> data_ptr = __ GetElementStartPointer(
                  argument_obj, AccessBuilder::ForSeqOneByteStringCharacter());
              constexpr int kAlign = alignof(FastOneByteString);
              constexpr int kSize = sizeof(FastOneByteString);
              static_assert(kSize == sizeof(uintptr_t) + sizeof(size_t),
                            "The size of "
                            "FastOneByteString isn't equal to the sum of its "
                            "expected members.");
              OpIndex stack_slot = __ StackSlot(kSize, kAlign);
              __ StoreOffHeap(stack_slot, data_ptr,
                              MemoryRepresentation::UintPtr());
              __ StoreOffHeap(stack_slot, length_in_bytes,
                              MemoryRepresentation::Uint32(), sizeof(size_t));
              static_assert(sizeof(uintptr_t) == sizeof(size_t),
                            "The string length can't "
                            "fit the PointerRepresentation used to store it.");
              return stack_slot;
            }
            default: {
              return argument;
            }
          }
        }
      }
      case CTypeInfo::SequenceType::kIsSequence: {
        CHECK_EQ(arg_type.GetType(), CTypeInfo::Type::kVoid);
        // Check that the value is a HeapObject.
        GOTO_IF(__ ObjectIsSmi(argument), handle_error);
        // Check that the value is a JSArray.
        V<Map> map = __ LoadMapField(argument);
        V<Word32> instance_type = __ LoadInstanceTypeField(map);
        GOTO_IF_NOT(__ Word32Equal(instance_type, JS_ARRAY_TYPE), handle_error);
        return __ AdaptLocalArgument(argument);
      }
      default: {
        UNREACHABLE();
      }
    }
    END_ALLOW_USE_DEPRECATED()
  }
References __, v8::internal::compiler::turboshaft::V< T >::Cast(), CHECK_EQ, v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::Checked(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::ClampFastCallArgument(), END_ALLOW_USE_DEPRECATED, v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::factory_, v8::internal::flags, v8::internal::compiler::AccessBuilder::ForJSExternalObjectValue(), v8::internal::compiler::AccessBuilder::ForSeqOneByteStringCharacter(), v8::internal::compiler::AccessBuilder::ForStringLength(), v8::CTypeInfo::GetFlags(), v8::CTypeInfo::GetSequenceType(), v8::CTypeInfo::GetType(), v8::CTypeInfo::kClampBit, v8::CTypeInfo::kEnforceRangeBit, v8::CTypeInfo::kFloat32, v8::CTypeInfo::kInt32, v8::CTypeInfo::kInt64, v8::CTypeInfo::kPointer, v8::CTypeInfo::kSeqOneByteString, v8::internal::kSeqOneByteStringTag, v8::internal::kStringRepresentationAndEncodingMask, v8::CTypeInfo::kUint32, v8::CTypeInfo::kUint64, v8::CTypeInfo::kV8Value, v8::CTypeInfo::kVoid, v8::base::internal::result, START_ALLOW_USE_DEPRECATED, v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr(), v8::internal::UNREACHABLE(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall().
BuildAllocateJSExternalObject()
template<typename Next >
V<HeapObject> v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject (V< WordPtr > pointer) [inline], [private]
Definition at line 399 of file fast-api-call-lowering-reducer.h.
                                                                  {
    Label<HeapObject> done(this);
    // Check if the pointer is a null pointer.
    GOTO_IF(__ WordPtrEqual(pointer, 0), done,
            __ HeapConstant(factory_->null_value()));
    Uninitialized<HeapObject> external = __ Allocate(
        JSExternalObject::kHeaderSize, AllocationType::kYoung, kTaggedAligned);
    __ InitializeField(external, AccessBuilder::ForMap(),
                       __ HeapConstant(factory_->external_map()));
    V<FixedArray> empty_fixed_array =
        __ HeapConstant(factory_->empty_fixed_array());
    __ InitializeField(external, AccessBuilder::ForJSObjectPropertiesOrHash(),
                       empty_fixed_array);
    __ InitializeField(external, AccessBuilder::ForJSObjectElements(),
                       empty_fixed_array);
#ifdef V8_ENABLE_SANDBOX
    OpIndex isolate_ptr =
        __ ExternalConstant(ExternalReference::isolate_address());
    MachineSignature::Builder builder(__ graph_zone(), 1, 2);
    builder.AddReturn(MachineType::Uint32());
    builder.AddParam(MachineType::Pointer());
    builder.AddParam(MachineType::Pointer());
    OpIndex allocate_and_initialize_young_external_pointer_table_entry =
        __ ExternalConstant(
            ExternalReference::
                allocate_and_initialize_young_external_pointer_table_entry());
    auto call_descriptor =
        Linkage::GetSimplifiedCDescriptor(__ graph_zone(), builder.Get());
    OpIndex handle = __ Call(
        allocate_and_initialize_young_external_pointer_table_entry,
        {isolate_ptr, pointer},
        TSCallDescriptor::Create(call_descriptor, CanThrow::kNo,
                                 LazyDeoptOnThrow::kNo, __ graph_zone()));
    __ InitializeField(
        external, AccessBuilder::ForJSExternalObjectPointerHandle(), handle);
#else
    __ InitializeField(external, AccessBuilder::ForJSExternalObjectValue(),
                       pointer);
#endif // V8_ENABLE_SANDBOX
    GOTO(done, __ FinishInitialization(std::move(external)));
    BIND(done, result);
    return result;
  }
References __, v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::factory_, v8::internal::compiler::AccessBuilder::ForJSExternalObjectValue(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHash(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::SignatureBuilder< SigT, T >::Get(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::handle(), v8::internal::ExternalReference::isolate_address(), v8::internal::compiler::kNo, v8::internal::kTaggedAligned, v8::internal::kYoung, v8::internal::MachineType::Pointer(), v8::base::internal::result, and v8::internal::MachineType::Uint32().
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::ConvertReturnValue().
Checked()
template<typename Next >
template<typename T >
V<T> v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::Checked (V< Tuple< T, Word32 >> result, Label<> & otherwise) [inline], [private]
Definition at line 145 of file fast-api-call-lowering-reducer.h.
                                                               {
    V<Word32> result_state = __ template Projection<1>(result);
    GOTO_IF_NOT(__ Word32Equal(result_state, TryChangeOp::kSuccessValue),
                otherwise);
    return __ template Projection<0>(result);
  }
References __, v8::internal::compiler::turboshaft::TryChangeOp::kSuccessValue, v8::base::internal::result, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::AdaptFastCallArgument().
ClampFastCallArgument()
template<typename Next >
OpIndex v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::ClampFastCallArgument (V< Float64 > argument, CTypeInfo::Type scalar_type) [inline], [private]
Definition at line 274 of file fast-api-call-lowering-reducer.h.
                                                           {
    double min, max;
    switch (scalar_type) {
      case CTypeInfo::Type::kInt32:
        min = std::numeric_limits<int32_t>::min();
        max = std::numeric_limits<int32_t>::max();
        break;
      case CTypeInfo::Type::kUint32:
        min = 0;
        max = std::numeric_limits<uint32_t>::max();
        break;
      case CTypeInfo::Type::kInt64:
        min = kMinSafeInteger;
        max = kMaxSafeInteger;
        break;
      case CTypeInfo::Type::kUint64:
        min = 0;
        max = kMaxSafeInteger;
        break;
      default:
        UNREACHABLE();
    }
    V<Float64> clamped =
        __ Conditional(__ Float64LessThan(min, argument),
                       __ Conditional(__ Float64LessThan(argument, max),
                                      argument, __ Float64Constant(max)),
                       __ Float64Constant(min));
    Label<Float64> done(this);
    V<Float64> rounded = __ Float64RoundTiesEven(clamped);
    GOTO_IF(__ Float64IsNaN(rounded), done, 0.0);
    GOTO(done, rounded);
    BIND(done, rounded_result);
    switch (scalar_type) {
      case CTypeInfo::Type::kInt32:
        return __ ReversibleFloat64ToInt32(rounded_result);
      case CTypeInfo::Type::kUint32:
        return __ ReversibleFloat64ToUint32(rounded_result);
      case CTypeInfo::Type::kInt64:
        return __ ReversibleFloat64ToInt64(rounded_result);
      case CTypeInfo::Type::kUint64:
        return __ ReversibleFloat64ToUint64(rounded_result);
      default:
        UNREACHABLE();
    }
  }
References __, v8::CTypeInfo::kInt32, v8::CTypeInfo::kInt64, v8::internal::kMaxSafeInteger, v8::internal::kMinSafeInteger, v8::CTypeInfo::kUint32, v8::CTypeInfo::kUint64, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::AdaptFastCallArgument().
ConvertReturnValue()
template<typename Next >
V<Any> v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::ConvertReturnValue (const CFunctionInfo * c_signature, OpIndex result) [inline], [private]
Definition at line 357 of file fast-api-call-lowering-reducer.h.
                                                                              {
    switch (c_signature->ReturnInfo().GetType()) {
      case CTypeInfo::Type::kVoid:
        return __ HeapConstant(factory_->undefined_value());
      case CTypeInfo::Type::kBool:
        static_assert(sizeof(bool) == 1, "unsupported bool size");
        return __ Word32BitwiseAnd(result, __ Word32Constant(0xFF));
      case CTypeInfo::Type::kInt32:
      case CTypeInfo::Type::kUint32:
      case CTypeInfo::Type::kFloat32:
      case CTypeInfo::Type::kFloat64:
        return result;
      case CTypeInfo::Type::kInt64: {
        CFunctionInfo::Int64Representation repr =
            c_signature->GetInt64Representation();
        if (repr == CFunctionInfo::Int64Representation::kBigInt) {
          return result;
        }
        DCHECK_EQ(repr, CFunctionInfo::Int64Representation::kNumber);
        return __ ChangeInt64ToFloat64(result);
      }
      case CTypeInfo::Type::kUint64: {
        CFunctionInfo::Int64Representation repr =
            c_signature->GetInt64Representation();
        if (repr == CFunctionInfo::Int64Representation::kBigInt) {
          return result;
        }
        DCHECK_EQ(repr, CFunctionInfo::Int64Representation::kNumber);
        return __ ChangeUint64ToFloat64(result);
      }
      case CTypeInfo::Type::kPointer:
        return BuildAllocateJSExternalObject(result);
      case CTypeInfo::Type::kAny:
      case CTypeInfo::Type::kSeqOneByteString:
      case CTypeInfo::Type::kV8Value:
      case CTypeInfo::Type::kApiObject:
      case CTypeInfo::Type::kUint8:
        UNREACHABLE();
    }
  }
References __, v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject(), DCHECK_EQ, v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::factory_, v8::CFunctionInfo::GetInt64Representation(), v8::CTypeInfo::GetType(), v8::CTypeInfo::kAny, v8::CTypeInfo::kApiObject, v8::CFunctionInfo::kBigInt, v8::CTypeInfo::kBool, v8::CTypeInfo::kFloat32, v8::CTypeInfo::kFloat64, v8::CTypeInfo::kInt32, v8::CTypeInfo::kInt64, v8::CFunctionInfo::kNumber, v8::CTypeInfo::kPointer, v8::CTypeInfo::kSeqOneByteString, v8::CTypeInfo::kUint32, v8::CTypeInfo::kUint64, v8::CTypeInfo::kUint8, v8::CTypeInfo::kV8Value, v8::CTypeInfo::kVoid, v8::base::internal::result, v8::CFunctionInfo::ReturnInfo(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall().
DefaultReturnValue()
template<typename Next >
V<Any> v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::DefaultReturnValue (const CFunctionInfo * c_signature) [inline], [private]
Definition at line 324 of file fast-api-call-lowering-reducer.h.
                                                              {
    switch (c_signature->ReturnInfo().GetType()) {
      case CTypeInfo::Type::kVoid:
        return __ HeapConstant(factory_->undefined_value());
      case CTypeInfo::Type::kBool:
      case CTypeInfo::Type::kInt32:
      case CTypeInfo::Type::kUint32:
        return __ Word32Constant(0);
      case CTypeInfo::Type::kInt64:
      case CTypeInfo::Type::kUint64: {
        CFunctionInfo::Int64Representation repr =
            c_signature->GetInt64Representation();
        if (repr == CFunctionInfo::Int64Representation::kBigInt) {
          return __ Word64Constant(int64_t{0});
        }
        DCHECK_EQ(repr, CFunctionInfo::Int64Representation::kNumber);
        return __ Float64Constant(0);
      }
      case CTypeInfo::Type::kFloat32:
        return __ Float32Constant(0);
      case CTypeInfo::Type::kFloat64:
        return __ Float64Constant(0);
      case CTypeInfo::Type::kPointer:
        return __ HeapConstant(factory_->undefined_value());
      case CTypeInfo::Type::kAny:
      case CTypeInfo::Type::kSeqOneByteString:
      case CTypeInfo::Type::kV8Value:
      case CTypeInfo::Type::kApiObject:
      case CTypeInfo::Type::kUint8:
        UNREACHABLE();
    }
  }
References __, DCHECK_EQ, v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::factory_, v8::CFunctionInfo::GetInt64Representation(), v8::CTypeInfo::GetType(), v8::CTypeInfo::kAny, v8::CTypeInfo::kApiObject, v8::CFunctionInfo::kBigInt, v8::CTypeInfo::kBool, v8::CTypeInfo::kFloat32, v8::CTypeInfo::kFloat64, v8::CTypeInfo::kInt32, v8::CTypeInfo::kInt64, v8::CFunctionInfo::kNumber, v8::CTypeInfo::kPointer, v8::CTypeInfo::kSeqOneByteString, v8::CTypeInfo::kUint32, v8::CTypeInfo::kUint64, v8::CTypeInfo::kUint8, v8::CTypeInfo::kV8Value, v8::CTypeInfo::kVoid, v8::CFunctionInfo::ReturnInfo(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall().
FastApiCall()
template<typename Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall (V< FrameState > frame_state, V< Object > data_argument, V< Context > context, base::Vector< const OpIndex > arguments, const FastApiCallParameters * parameters, base::Vector< const RegisterRepresentation > out_reps) [inline]
Definition at line 27 of file fast-api-call-lowering-reducer.h.
                                                         {
    __ data() -> set_graph_has_lowered_fast_api_calls();
    FastApiCallFunction c_function = parameters->c_function;
    const auto& c_signature = parameters->c_signature();
    const int c_arg_count = c_signature->ArgumentCount();
    DCHECK_EQ(c_arg_count, arguments.size());
    Label<> handle_error(this);
    Label<Word32> done(this);
    Variable result = __ NewVariable(RegisterRepresentation::FromCTypeInfo(
        c_signature->ReturnInfo(), c_signature->GetInt64Representation()));
    OpIndex callee = __ ExternalConstant(ExternalReference::Create(
        c_function.address, ExternalReference::FAST_C_CALL));
    base::SmallVector<OpIndex, 16> args;
    for (int i = 0; i < c_arg_count; ++i) {
        CTypeInfo type = c_signature->ArgumentInfo(i);
        args.push_back(AdaptFastCallArgument(arguments[i], type, handle_error));
    }
    // While adapting the arguments, we might have noticed an inconsistency that
    // lead to unconditionally jumping to {handle_error}. If this happens, then
    // we don't emit the call.
    if (V8_LIKELY(!__ generating_unreachable_operations())) {
      MachineSignature::Builder builder(
          __ graph_zone(), 1,
          c_arg_count + (c_signature->HasOptions() ? 1 : 0));
      builder.AddReturn(MachineType::TypeForCType(c_signature->ReturnInfo()));
      for (int i = 0; i < c_arg_count; ++i) {
        CTypeInfo type = c_signature->ArgumentInfo(i);
        START_ALLOW_USE_DEPRECATED()
        MachineType machine_type =
            type.GetSequenceType() == CTypeInfo::SequenceType::kScalar
                ? MachineType::TypeForCType(type)
                : MachineType::AnyTagged();
        END_ALLOW_USE_DEPRECATED()
        builder.AddParam(machine_type);
      }
      OpIndex stack_slot;
      if (c_signature->HasOptions()) {
        const int kAlign = alignof(v8::FastApiCallbackOptions);
        const int kSize = sizeof(v8::FastApiCallbackOptions);
        // If this check fails, you've probably added new fields to
        // v8::FastApiCallbackOptions, which means you'll need to write code
        // that initializes and reads from them too.
        static_assert(kSize == sizeof(uintptr_t) * 2);
        stack_slot = __ StackSlot(kSize, kAlign);
        // isolate
        __ StoreOffHeap(
            stack_slot,
            __ ExternalConstant(ExternalReference::isolate_address()),
            MemoryRepresentation::UintPtr(),
            offsetof(v8::FastApiCallbackOptions, isolate));
        // data = data_argument
        OpIndex data_argument_to_pass = __ AdaptLocalArgument(data_argument);
        __ StoreOffHeap(stack_slot, data_argument_to_pass,
                        MemoryRepresentation::UintPtr(),
                        offsetof(v8::FastApiCallbackOptions, data));
        args.push_back(stack_slot);
        builder.AddParam(MachineType::Pointer());
      }
      // Build the actual call.
      const TSCallDescriptor* call_descriptor = TSCallDescriptor::Create(
          Linkage::GetSimplifiedCDescriptor(__ graph_zone(), builder.Get(),
                                            CallDescriptor::kNeedsFrameState),
          CanThrow::kYes, LazyDeoptOnThrow::kNo, __ graph_zone());
      OpIndex c_call_result = WrapFastCall(call_descriptor, callee, frame_state,
                                           context, base::VectorOf(args));
      Label<> trigger_exception(this);
      V<Object> exception =
          __ Load(__ ExternalConstant(ExternalReference::Create(
                      IsolateAddressId::kExceptionAddress, isolate_)),
                  LoadOp::Kind::RawAligned(), MemoryRepresentation::UintPtr());
      GOTO_IF_NOT(LIKELY(__ TaggedEqual(
                      exception,
                      __ HeapConstant(isolate_->factory()->the_hole_value()))),
                  trigger_exception);
      V<Any> fast_call_result = ConvertReturnValue(c_signature, c_call_result);
      __ SetVariable(result, fast_call_result);
      GOTO(done, FastApiCallOp::kSuccessValue);
      BIND(trigger_exception);
      __ template CallRuntime<
          typename RuntimeCallDescriptor::PropagateException>(
          isolate_, frame_state, __ NoContextConstant(), LazyDeoptOnThrow::kNo,
          {});
      __ Unreachable();
    }
    if (BIND(handle_error)) {
      __ SetVariable(result, DefaultReturnValue(c_signature));
      // We pass Tagged<Smi>(0) as the value here, although this should never be
      // visible when calling code reacts to `kFailureValue` properly.
      GOTO(done, FastApiCallOp::kFailureValue);
    }
    BIND(done, state);
    return __ Tuple(state, __ GetVariable(result));
  }
References __, v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::AdaptFastCallArgument(), v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::compiler::FastApiCallFunction::address, v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::MachineType::AnyTagged(), v8::base::args, v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::ConvertReturnValue(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::ExternalReference::Create(), DCHECK_EQ, v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::DefaultReturnValue(), END_ALLOW_USE_DEPRECATED, v8::internal::Isolate::factory(), v8::internal::ExternalReference::FAST_C_CALL, v8::internal::compiler::turboshaft::RegisterRepresentation::FromCTypeInfo(), v8::internal::SignatureBuilder< SigT, T >::Get(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::isolate_, v8::internal::ExternalReference::isolate_address(), v8::internal::compiler::turboshaft::FastApiCallOp::kFailureValue, v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::kNo, v8::internal::compiler::turboshaft::FastApiCallOp::kSuccessValue, v8::internal::compiler::kYes, v8::Load(), v8::internal::wasm::machine_type(), v8::internal::MachineType::Pointer(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::base::internal::result, START_ALLOW_USE_DEPRECATED, v8::internal::tracing::type, v8::internal::MachineType::TypeForCType(), v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr(), V8_LIKELY, v8::base::VectorOf(), and v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::WrapFastCall().
WrapFastCall()
template<typename Next >
OpIndex v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::WrapFastCall (const TSCallDescriptor * descriptor, OpIndex callee, V< FrameState > frame_state, V< Context > context, base::Vector< const OpIndex > arguments) [inline], [private]
Definition at line 447 of file fast-api-call-lowering-reducer.h.
                                                            {
    // CPU profiler support.
    OpIndex target_address =
        __ IsolateField(IsolateFieldId::kFastApiCallTarget);
    __ StoreOffHeap(target_address, __ BitcastHeapObjectToWordPtr(callee),
                    MemoryRepresentation::UintPtr());
    OpIndex context_address = __ ExternalConstant(
        ExternalReference::Create(IsolateAddressId::kContextAddress, isolate_));
    __ StoreOffHeap(context_address, __ BitcastHeapObjectToWordPtr(context),
                    MemoryRepresentation::UintPtr());
    // Create the fast call.
    OpIndex result = __ Call(callee, frame_state, arguments, descriptor);
    // Reset the CPU profiler target address.
    __ StoreOffHeap(target_address, __ IntPtrConstant(0),
                    MemoryRepresentation::UintPtr());
#if DEBUG
    // Reset the context again after the call, to make sure nobody is using the
    // leftover context in the isolate.
    __ StoreOffHeap(context_address, __ WordPtrConstant(Context::kNoContext),
                    MemoryRepresentation::UintPtr());
#endif
    return result;
  }
References __, v8::internal::ExternalReference::Create(), v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::isolate_, v8::internal::Context::kNoContext, v8::base::internal::result, and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall().
Member Data Documentation
factory_
template<typename Next >
Factory* v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::factory_ = isolate_->factory() [private]
Definition at line 480 of file fast-api-call-lowering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::AdaptFastCallArgument(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::ConvertReturnValue(), and v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::DefaultReturnValue().
isolate_
template<typename Next >
Isolate* v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::isolate_ = __ data() -> isolate() [private]
Definition at line 479 of file fast-api-call-lowering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), and v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::WrapFastCall().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/fast-api-call-lowering-reducer.h