v8::internal::Script Class Reference
#include <script.h>
Classes
class Iterator
struct PositionInfo
Public Types
enum class Type { kNative = 0
, kExtension = 1
, kNormal = 2
, kInspector = 4
 }
enum class CompilationType { kHost = 0
, kEval = 1
 }
enum class CompilationState { kInitial = 0
, kCompiled = 1
 }
enum class OffsetFlag { kNoOffset
, kWithOffset
 }
using BodyDescriptor = StructBodyDescriptor
Public Member Functions
bool is_wrapped () const
bool has_eval_from_shared () const
uint32_t flags () const
void set_flags (uint32_t new_flags)
CompilationType compilation_type () const
void set_compilation_type (CompilationType type)
bool produce_compile_hints () const
void set_produce_compile_hints (bool produce_compile_hints)
bool deserialized () const
void set_deserialized (bool value)
CompilationState compilation_state ()
void set_compilation_state (CompilationState state)
bool is_repl_mode () const
void set_is_repl_mode (bool value)
v8::ScriptOriginOptions origin_options ()
void set_origin_options (ScriptOriginOptions origin_options)
bool HasValidSource ()
bool HasSourceURLComment () const
bool HasSourceMappingURLComment () const
bool IsMaybeUnfinalized (Isolate *isolate) const
Tagged< Object > GetNameOrSourceURL ()
Tagged< Script > GetEvalOrigin ()
bool has_line_ends () const
bool CanHaveLineEnds () const
V8_EXPORT_PRIVATE bool GetPositionInfo (int position, PositionInfo *info, OffsetFlag offset_flag=OffsetFlag::kWithOffset) const
V8_EXPORT_PRIVATE bool GetPositionInfoWithLineEnds (int position, PositionInfo *info, const String::LineEndsVector &line_ends, OffsetFlag offset_flag=OffsetFlag::kWithOffset) const
V8_EXPORT_PRIVATE void AddPositionInfoOffset (PositionInfo *info, OffsetFlag offset_flag=OffsetFlag::kWithOffset) const
bool IsSubjectToDebugging () const
bool IsUserJavaScript () const
void TraceScriptRundown ()
void TraceScriptRundownSources ()
int GetColumnNumber (int code_pos) const
int GetLineNumber (int code_pos) const
template<typename IsolateT >
void InitLineEndsInternal (IsolateT *isolate, DirectHandle< Script > script)
Static Public Member Functions
static DirectHandle< String > GetScriptHash (Isolate *isolate, DirectHandle< Script > script, bool forceForInspector)
static int GetEvalPosition (Isolate *isolate, DirectHandle< Script > script)
static void InitLineEnds (Isolate *isolate, DirectHandle< Script > script)
static void InitLineEnds (LocalIsolate *isolate, DirectHandle< Script > script)
static V8_EXPORT_PRIVATE String::LineEndsVector GetLineEnds (Isolate *isolate, DirectHandle< Script > script)
static void SetSource (Isolate *isolate, DirectHandle< Script > script, DirectHandle< String > source)
static bool GetPositionInfo (DirectHandle< Script > script, int position, PositionInfo *info, OffsetFlag offset_flag=OffsetFlag::kWithOffset)
static bool GetLineColumnWithLineEnds (int position, int &line, int &column, const String::LineEndsVector &line_ends)
static int GetColumnNumber (DirectHandle< Script > script, int code_offset)
static V8_EXPORT_PRIVATE int GetLineNumber (DirectHandle< Script > script, int code_offset)
template<typename IsolateT >
static MaybeHandle< SharedFunctionInfo > FindSharedFunctionInfo (DirectHandle< Script > script, IsolateT *isolate, FunctionLiteral *function_literal)
Static Public Attributes
static constexpr int kTemporaryScriptId = -2
Private Member Functions
template<typename LineEndsContainer >
bool GetPositionInfoInternal (const LineEndsContainer &ends, int position, Script::PositionInfo *info, const DisallowGarbageCollection &no_gc) const
Static Private Member Functions
template<typename IsolateT >
static void V8_PRESERVE_MOST InitLineEndsInternal (IsolateT *isolate, DirectHandle< Script > script)
Private Attributes
friend Factory
friend FactoryBase< Factory >
friend FactoryBase< LocalFactory >
Detailed Description
Definition at line 38 of file script.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::Script::BodyDescriptor = StructBodyDescriptor
Definition at line 274 of file script.h.
Member Enumeration Documentation
CompilationState
enum v8::internal::Script::CompilationState [strong]
Enumerator
kInitial
kCompiled
Definition at line 59 of file script.h.
{ kInitial = 0, kCompiled = 1 };
CompilationType
enum v8::internal::Script::CompilationType [strong]
Enumerator
kHost
kEval
Definition at line 56 of file script.h.
{ kHost = 0, kEval = 1 };
OffsetFlag
enum v8::internal::Script::OffsetFlag [strong]
Enumerator
kNoOffset
kWithOffset
Definition at line 207 of file script.h.
{ kNoOffset, kWithOffset };
Type
enum v8::internal::Script::Type [strong]
Enumerator
kNative
kExtension
kNormal
kInspector
Definition at line 45 of file script.h.
                  {
    kNative = 0,
    kExtension = 1,
    kNormal = 2,
#if V8_ENABLE_WEBASSEMBLY
    kWasm = 3,
#endif // V8_ENABLE_WEBASSEMBLY
    kInspector = 4
  };
Member Function Documentation
AddPositionInfoOffset()
void v8::internal::Script::AddPositionInfoOffset (PositionInfo * info, OffsetFlag offset_flag = OffsetFlag::kWithOffset) const
Definition at line 4639 of file objects.cc.
                                                                 {
  // Add offsets if requested.
  if (offset_flag == OffsetFlag::kWithOffset) {
    if (info->line == 0) {
      info->column += column_offset();
    }
    info->line += line_offset();
  } else {
    DCHECK_EQ(offset_flag, OffsetFlag::kNoOffset);
  }
}
References v8::internal::Script::PositionInfo::column, DCHECK_EQ, kNoOffset, kWithOffset, and v8::internal::Script::PositionInfo::line.
Referenced by GetPositionInfo(), and GetPositionInfoWithLineEnds().
CanHaveLineEnds()
bool v8::internal::Script::CanHaveLineEnds () const [inline]
Definition at line 190 of file script-inl.h.
                                   {
#if V8_ENABLE_WEBASSEMBLY
  return type() != Script::Type::kWasm;
#else
  return true;
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::internal::tracing::type.
compilation_state()
Script::CompilationState v8::internal::Script::compilation_state () [inline]
Definition at line 140 of file script-inl.h.
                                                 {
  return CompilationStateBit::decode(flags());
}
References flags().
compilation_type()
Script::CompilationType v8::internal::Script::compilation_type () const [inline]
Definition at line 134 of file script-inl.h.
                                                     {
  return CompilationTypeBit::decode(flags());
}
References flags().
deserialized()
bool v8::internal::Script::deserialized () const [inline]
Definition at line 155 of file script-inl.h.
{ return DeserializedBit::decode(flags()); }
References flags().
FindSharedFunctionInfo()
template<typename IsolateT >
template MaybeHandle< SharedFunctionInfo > v8::internal::Script::FindSharedFunctionInfo (DirectHandle< Script > script, IsolateT * isolate, FunctionLiteral * function_literal) [static]
Definition at line 4821 of file objects.cc.
                                       {
  DCHECK(function_literal->shared_function_info().is_null());
  int function_literal_id = function_literal->function_literal_id();
  CHECK_NE(function_literal_id, kInvalidInfoId);
  // If this check fails, the problem is most probably the function id
  // renumbering done by AstFunctionLiteralIdReindexer; in particular, that
  // AstTraversalVisitor doesn't recurse properly in the construct which
  // triggers the mismatch.
  CHECK_LT(function_literal_id, script->infos()->length());
  Tagged<MaybeObject> shared = script->infos()->get(function_literal_id);
  Tagged<HeapObject> heap_object;
  if (!shared.GetHeapObject(&heap_object) ||
      IsUndefined(heap_object, isolate)) {
    return MaybeHandle<SharedFunctionInfo>();
  }
  Handle<SharedFunctionInfo> result(Cast<SharedFunctionInfo>(heap_object),
                                    isolate);
  function_literal->set_shared_function_info(result);
  return result;
}
References CHECK_LT, CHECK_NE, v8::internal::DCHECK(), v8::internal::FunctionLiteral::function_literal_id(), v8::internal::function_literal_id, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::kInvalidInfoId, v8::base::internal::result, v8::internal::script, v8::internal::FunctionLiteral::set_shared_function_info(), and v8::internal::FunctionLiteral::shared_function_info().
Referenced by v8::internal::anonymous_namespace{compiler.cc}::GetOrCreateTopLevelSharedFunctionInfo(), and v8::internal::Compiler::GetSharedFunctionInfo().
flags()
uint32_t v8::internal::Script::flags () const [inline]
Definition at line 122 of file script-inl.h.
                             {
  // Use a relaxed load since background compile threads read the
  // {compilation_type()} while the foreground thread might update e.g. the
  // {origin_options}.
  return TaggedField<Smi>::Relaxed_Load(*this, kFlagsOffset).value();
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load().
Referenced by compilation_state(), compilation_type(), deserialized(), is_repl_mode(), origin_options(), produce_compile_hints(), set_compilation_state(), set_compilation_type(), set_deserialized(), set_is_repl_mode(), set_origin_options(), set_produce_compile_hints(), v8::internal::JSPromise::set_status(), and v8::internal::JSPromise::status().
GetColumnNumber() [1/2]
int v8::internal::Script::GetColumnNumber (DirectHandle< Script > script, int code_offset) [static]
Definition at line 4744 of file objects.cc.
                                                                     {
  PositionInfo info;
  GetPositionInfo(script, code_pos, &info);
  return info.column;
}
References v8::internal::Script::PositionInfo::column, GetPositionInfo(), and v8::internal::script.
Referenced by v8::UnboundScript::GetColumnNumber(), v8::internal::CallSiteInfo::GetEnclosingColumnNumber(), v8::Function::GetScriptColumnNumber(), and v8::Function::GetScriptLocation().
GetColumnNumber() [2/2]
int v8::internal::Script::GetColumnNumber (int code_pos) const
Definition at line 4750 of file objects.cc.
                                              {
  PositionInfo info;
  GetPositionInfo(code_pos, &info);
  return info.column;
}
References v8::internal::Script::PositionInfo::column, and GetPositionInfo().
GetEvalOrigin()
Tagged< Script > v8::internal::Script::GetEvalOrigin () [inline]
Definition at line 225 of file script-inl.h.
                                     {
  DisallowGarbageCollection no_gc;
  Tagged<Script> origin_script = *this;
  while (origin_script->has_eval_from_shared()) {
    Tagged<HeapObject> maybe_script =
        origin_script->eval_from_shared()->script();
    CHECK(IsScript(maybe_script));
    origin_script = Cast<Script>(maybe_script);
  }
  return origin_script;
}
References CHECK, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetEvalPosition()
int v8::internal::Script::GetEvalPosition (Isolate * isolate, DirectHandle< Script > script) [static]
Definition at line 4332 of file objects.cc.
                                                                         {
  DCHECK(script->compilation_type() == Script::CompilationType::kEval);
  int position = script->eval_from_position();
  if (position < 0) {
    // Due to laziness, the position may not have been translated from code
    // offset yet, which would be encoded as negative integer. In that case,
    // translate and set the position.
    if (!script->has_eval_from_shared()) {
      position = 0;
    } else {
      DirectHandle<SharedFunctionInfo> shared(script->eval_from_shared(),
                                              isolate);
      SharedFunctionInfo::EnsureSourcePositionsAvailable(isolate, shared);
      position =
          shared->abstract_code(isolate)->SourcePosition(isolate, -position);
    }
    DCHECK_GE(position, 0);
    script->set_eval_from_position(position);
  }
  return position;
}
References v8::internal::DCHECK(), DCHECK_GE, v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), kEval, and v8::internal::script.
Referenced by v8::internal::BUILTIN(), and v8::internal::anonymous_namespace{call-site-info.cc}::FormatEvalOrigin().
GetLineColumnWithLineEnds()
bool v8::internal::Script::GetLineColumnWithLineEnds (int position, int & line, int & column, const String::LineEndsVector & line_ends) [static]
Definition at line 4727 of file objects.cc.
                                           {
  DisallowGarbageCollection no_gc;
  PositionInfo info;
  if (!GetLineEndsContainerPositionInfo(line_ends, position, &info, no_gc)) {
    line = -1;
    column = -1;
    return false;
  }
  line = info.line;
  column = info.column;
  return true;
}
References v8::internal::Script::PositionInfo::column, v8::internal::anonymous_namespace{objects.cc}::GetLineEndsContainerPositionInfo(), v8::internal::Script::PositionInfo::line, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetLineEnds()
String::LineEndsVector v8::internal::Script::GetLineEnds (Isolate * isolate, DirectHandle< Script > script) [static]
Definition at line 4354 of file objects.cc.
                                                                        {
  DCHECK(!script->has_line_ends());
  Tagged<Object> src_obj = script->source();
  if (IsString(src_obj)) {
    DirectHandle<String> src(Cast<String>(src_obj), isolate);
    return String::CalculateLineEndsVector(isolate, src, true);
  }
  return String::LineEndsVector();
}
References v8::internal::String::CalculateLineEndsVector(), v8::internal::DCHECK(), and v8::internal::script.
Referenced by v8::internal::V8HeapExplorer::PopulateLineEnds().
GetLineNumber() [1/2]
int v8::internal::Script::GetLineNumber (DirectHandle< Script > script, int code_offset) [static]
Definition at line 4756 of file objects.cc.
                                                                   {
  PositionInfo info;
  GetPositionInfo(script, code_pos, &info);
  return info.line;
}
References GetPositionInfo(), v8::internal::Script::PositionInfo::line, and v8::internal::script.
Referenced by v8::internal::CallSiteInfo::GetEnclosingLineNumber(), v8::internal::CallSiteInfo::GetLineNumber(), v8::UnboundScript::GetLineNumber(), v8::Function::GetScriptLineNumber(), and v8::Function::GetScriptLocation().
GetLineNumber() [2/2]
int v8::internal::Script::GetLineNumber (int code_pos) const
Definition at line 4762 of file objects.cc.
                                            {
  PositionInfo info;
  GetPositionInfo(code_pos, &info);
  return info.line;
}
References GetPositionInfo(), and v8::internal::Script::PositionInfo::line.
GetNameOrSourceURL()
Tagged< Object > v8::internal::Script::GetNameOrSourceURL ()
Definition at line 4768 of file objects.cc.
                                          {
  // Keep in sync with ScriptNameOrSourceURL in messages.js.
  if (!IsUndefined(source_url())) return source_url();
  return name();
}
References v8::internal::name.
GetPositionInfo() [1/2]
bool v8::internal::Script::GetPositionInfo (DirectHandle< Script > script, int position, PositionInfo * info, OffsetFlag offset_flag = OffsetFlag::kWithOffset) [static]
Definition at line 4405 of file objects.cc.
                                                                         {
#if V8_ENABLE_WEBASSEMBLY
  // For wasm, we do not create an artificial line_ends array, but do the
  // translation directly.
#ifdef DEBUG
  if (script->type() == Type::kWasm) {
    DCHECK(script->has_line_ends());
    DCHECK_EQ(Cast<FixedArray>(script->line_ends())->length(), 0);
  }
#endif // DEBUG
#endif // V8_ENABLE_WEBASSEMBLY
  InitLineEnds(Isolate::Current(), script);
  return script->GetPositionInfo(position, info, offset_flag);
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), DCHECK_EQ, InitLineEnds(), and v8::internal::script.
Referenced by v8::internal::anonymous_namespace{code-serializer.cc}::CreateInterpreterDataForDeserializedCode(), v8::debug::Script::EndColumn(), v8::debug::Script::EndLine(), v8::internal::anonymous_namespace{code-serializer.cc}::FinalizeDeserialization(), v8::internal::anonymous_namespace{call-site-info.cc}::FormatEvalOrigin(), v8::internal::Isolate::GetAbstractPC(), v8::internal::CallSiteInfo::GetColumnNumber(), GetColumnNumber(), v8::internal::anonymous_namespace{debug.cc}::GetDebugLocation(), v8::internal::anonymous_namespace{runtime-debug.cc}::GetJSPositionInfo(), GetLineNumber(), v8::StackFrame::GetLocation(), v8::debug::Script::GetSourceLocation(), v8::internal::Compiler::InstallInterpreterTrampolineCopy(), v8::internal::ExistingCodeLogger::LogExistingFunction(), v8::internal::Compiler::LogFunctionCompilation(), v8::internal::anonymous_namespace{runtime-debug.cc}::ScriptLinePositionWithOffset(), v8::internal::Debug::ShouldBeSkipped(), v8::Module::SourceOffsetToLocation(), v8::internal::SourcePositionInfo::SourcePositionInfo(), v8::debug::GeneratorObject::SuspendedLocation(), v8::internal::Isolate::Throw(), and v8::internal::SamplingHeapProfiler::TranslateAllocationNode().
GetPositionInfo() [2/2]
bool v8::internal::Script::GetPositionInfo (int position, PositionInfo * info, OffsetFlag offset_flag = OffsetFlag::kWithOffset) const
Definition at line 4680 of file objects.cc.
                                                           {
  DisallowGarbageCollection no_gc;
#if V8_ENABLE_WEBASSEMBLY
  // For wasm, we use the byte offset as the column.
  if (type() == Script::Type::kWasm) {
    DCHECK_LE(0, position);
    wasm::NativeModule* native_module = wasm_native_module();
    const wasm::WasmModule* module = native_module->module();
    if (module->functions.empty()) return false;
    info->line = 0;
    info->column = position;
    info->line_start = module->functions[0].code.offset();
    info->line_end = module->functions.back().code.end_offset();
    return true;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  if (!has_line_ends()) {
    // Slow mode: we do not have line_ends. We have to iterate through source.
    if (!GetPositionInfoSlow(*this, position, no_gc, info)) {
      return false;
    }
  } else {
    DCHECK(has_line_ends());
    Tagged<FixedArray> ends = Cast<FixedArray>(line_ends());
    if (!GetPositionInfoInternal(ends, position, info, no_gc)) return false;
  }
  AddPositionInfoOffset(info, offset_flag);
  return true;
}
References AddPositionInfoOffset(), v8::internal::Script::PositionInfo::column, v8::internal::DCHECK(), DCHECK_LE, v8::internal::wasm::WasmModule::functions, GetPositionInfoInternal(), v8::internal::anonymous_namespace{objects.cc}::GetPositionInfoSlow(), has_line_ends(), v8::internal::Script::PositionInfo::line, v8::internal::Script::PositionInfo::line_end, v8::internal::Script::PositionInfo::line_start, v8::internal::wasm::NativeModule::module(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::tracing::type.
GetPositionInfoInternal()
template<typename LineEndsContainer >
template bool v8::internal::Script::GetPositionInfoInternal< Tagged< FixedArray > > (const LineEndsContainer & ends, int position, Script::PositionInfo * info, const DisallowGarbageCollection & no_gc) const [private]
Definition at line 4653 of file objects.cc.
                                                  {
  if (!GetLineEndsContainerPositionInfo(ends, position, info, no_gc))
    return false;
  // Line end is position of the linebreak character.
  info->line_end = GetLineEnd(ends, info->line);
  if (info->line_end > 0) {
    DCHECK(IsString(source()));
    Tagged<String> src = Cast<String>(source());
    if (src->length() >= static_cast<uint32_t>(info->line_end) &&
        src->Get(info->line_end - 1) == '\r') {
      info->line_end--;
    }
  }
  return true;
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{objects.cc}::GetLineEnd(), v8::internal::anonymous_namespace{objects.cc}::GetLineEndsContainerPositionInfo(), v8::internal::Script::PositionInfo::line, v8::internal::Script::PositionInfo::line_end, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by GetPositionInfo(), and GetPositionInfoWithLineEnds().
GetPositionInfoWithLineEnds()
bool v8::internal::Script::GetPositionInfoWithLineEnds (int position, PositionInfo * info, const String::LineEndsVector & line_ends, OffsetFlag offset_flag = OffsetFlag::kWithOffset) const
Definition at line 4716 of file objects.cc.
                                  {
  DisallowGarbageCollection no_gc;
  if (!GetPositionInfoInternal(line_ends, position, info, no_gc)) return false;
  AddPositionInfoOffset(info, offset_flag);
  return true;
}
References AddPositionInfoOffset(), GetPositionInfoInternal(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetScriptHash()
DirectHandle< String > v8::internal::Script::GetScriptHash (Isolate * isolate, DirectHandle< Script > script, bool forceForInspector) [static]
Definition at line 4775 of file objects.cc.
                                                                   {
  if (script->origin_options().IsOpaque() && !forceForInspector) {
    return isolate->factory()->empty_string();
  }
  PtrComprCageBase cage_base(isolate);
  {
    Tagged<Object> maybe_source_hash = script->source_hash(cage_base);
    if (IsString(maybe_source_hash, cage_base)) {
      DirectHandle<String> precomputed(Cast<String>(maybe_source_hash),
                                       isolate);
      if (precomputed->length() > 0) {
        return precomputed;
      }
    }
  }
  DirectHandle<String> src_text;
  {
    Tagged<Object> maybe_script_source = script->source(cage_base);
    if (!IsString(maybe_script_source, cage_base)) {
      return isolate->factory()->empty_string();
    }
    src_text = direct_handle(Cast<String>(maybe_script_source), isolate);
  }
  char formatted_hash[kSizeOfFormattedSha256Digest];
  std::unique_ptr<char[]> string_val = src_text->ToCString();
  size_t len = strlen(string_val.get());
  uint8_t hash[kSizeOfSha256Digest];
  SHA256_hash(string_val.get(), len, hash);
  FormatBytesToHex(formatted_hash, kSizeOfFormattedSha256Digest, hash,
                   kSizeOfSha256Digest);
  formatted_hash[kSizeOfSha256Digest * 2] = '\0';
  DirectHandle<String> result =
      isolate->factory()->NewStringFromAsciiChecked(formatted_hash);
  script->set_source_hash(*result);
  return result;
}
References v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::FormatBytesToHex(), kSizeOfFormattedSha256Digest, kSizeOfSha256Digest, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::base::internal::result, v8::internal::script, and v8::internal::SHA256_hash().
Referenced by v8::internal::CallSiteInfo::GetScriptHash(), and v8::debug::Script::GetSha256Hash().
has_eval_from_shared()
bool v8::internal::Script::has_eval_from_shared () const [inline]
has_line_ends()
bool v8::internal::Script::has_line_ends () const [inline]
Definition at line 188 of file script-inl.h.
{ return line_ends() != Smi::zero(); }
References v8::internal::Smi::zero().
Referenced by GetPositionInfo().
HasSourceMappingURLComment()
bool v8::internal::Script::HasSourceMappingURLComment () const [inline]
Definition at line 213 of file script-inl.h.
                                              {
  return IsString(source_mapping_url()) &&
         Cast<String>(source_mapping_url())->length() != 0;
}
Referenced by TraceScriptRundown().
HasSourceURLComment()
bool v8::internal::Script::HasSourceURLComment () const [inline]
Definition at line 209 of file script-inl.h.
                                       {
  return IsString(source_url()) && Cast<String>(source_url())->length() != 0;
}
Referenced by TraceScriptRundown().
HasValidSource()
bool v8::internal::Script::HasValidSource () [inline]
Definition at line 175 of file script-inl.h.
                            {
  Tagged<Object> src = this->source();
  if (!IsString(src)) return true;
  Tagged<String> src_str = Cast<String>(src);
  if (!StringShape(src_str).IsExternal()) return true;
  if (src_str->IsOneByteRepresentation()) {
    return Cast<ExternalOneByteString>(src)->resource() != nullptr;
  } else if (src_str->IsTwoByteRepresentation()) {
    return Cast<ExternalTwoByteString>(src)->resource() != nullptr;
  }
  return true;
}
Referenced by TraceScriptRundown().
InitLineEnds() [1/2]
void v8::internal::Script::InitLineEnds (Isolate * isolate, DirectHandle< Script > script) [inline], [static]
Definition at line 199 of file script-inl.h.
                                                                       {
  if (script->has_line_ends()) return;
  Script::InitLineEndsInternal(isolate, script);
}
References InitLineEndsInternal(), and v8::internal::script.
Referenced by v8::internal::BackgroundMergeTask::CompleteMergeInForeground(), v8::internal::anonymous_namespace{code-serializer.cc}::CreateInterpreterDataForDeserializedCode(), v8::internal::anonymous_namespace{code-serializer.cc}::FinalizeDeserialization(), GetPositionInfo(), v8::debug::Script::GetSourceOffset(), v8::internal::JSMessageObject::InitializeSourcePositions(), v8::internal::Factory::ProcessNewScript(), v8::internal::anonymous_namespace{runtime-debug.cc}::ScriptLinePosition(), and SetSource().
InitLineEnds() [2/2]
void v8::internal::Script::InitLineEnds (LocalIsolate * isolate, DirectHandle< Script > script) [inline], [static]
Definition at line 204 of file script-inl.h.
                                                                            {
  if (script->has_line_ends()) return;
  Script::InitLineEndsInternal(isolate, script);
}
References InitLineEndsInternal(), and v8::internal::script.
InitLineEndsInternal() [1/2]
template<typename IsolateT >
void v8::internal::Script::InitLineEndsInternal (IsolateT * isolate, DirectHandle< Script > script)
Definition at line 4368 of file objects.cc.
                                                               {
  DCHECK(!script->has_line_ends());
  DCHECK(script->CanHaveLineEnds());
  Tagged<Object> src_obj = script->source();
  if (!IsString(src_obj)) {
    DCHECK(IsUndefined(src_obj, isolate));
    script->set_line_ends(ReadOnlyRoots(isolate).empty_fixed_array());
  } else {
    DCHECK(IsString(src_obj));
    DirectHandle<String> src(Cast<String>(src_obj), isolate);
    DirectHandle<FixedArray> array =
        String::CalculateLineEnds(isolate, src, true);
    script->set_line_ends(*array);
  }
  DCHECK(IsFixedArray(script->line_ends()));
  DCHECK(script->has_line_ends());
}
References v8::internal::String::CalculateLineEnds(), v8::internal::DCHECK(), and v8::internal::script.
InitLineEndsInternal() [2/2]
template<typename IsolateT >
static void V8_PRESERVE_MOST v8::internal::Script::InitLineEndsInternal (IsolateT * isolate, DirectHandle< Script > script) [static], [private]
Referenced by InitLineEnds().
is_repl_mode()
bool v8::internal::Script::is_repl_mode () const [inline]
Definition at line 161 of file script-inl.h.
{ return IsReplModeBit::decode(flags()); }
References flags().
is_wrapped()
bool v8::internal::Script::is_wrapped () const [inline]
IsMaybeUnfinalized()
bool v8::internal::Script::IsMaybeUnfinalized (Isolate * isolate) const [inline]
Definition at line 218 of file script-inl.h.
                                                      {
  // TODO(v8:12051): A more robust detection, e.g. with a dedicated sentinel
  // value.
  return IsUndefined(source(), isolate) ||
         Cast<String>(source())->length() == 0;
}
IsSubjectToDebugging()
bool v8::internal::Script::IsSubjectToDebugging () const
Definition at line 4421 of file objects.cc.
                                        {
  switch (type()) {
    case Type::kNormal:
#if V8_ENABLE_WEBASSEMBLY
    case Type::kWasm:
#endif // V8_ENABLE_WEBASSEMBLY
      return true;
    case Type::kNative:
    case Type::kInspector:
    case Type::kExtension:
      return false;
  }
  UNREACHABLE();
}
References kExtension, kInspector, kNative, kNormal, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
IsUserJavaScript()
bool v8::internal::Script::IsUserJavaScript () const
Definition at line 4436 of file objects.cc.
                                    {
  return type() == Script::Type::kNormal;
}
References kNormal, and v8::internal::tracing::type.
origin_options()
ScriptOriginOptions v8::internal::Script::origin_options () [inline]
Definition at line 167 of file script-inl.h.
                                           {
  return ScriptOriginOptions(OriginOptionsBits::decode(flags()));
}
References flags().
Referenced by set_origin_options(), and TraceScriptRundown().
produce_compile_hints()
bool v8::internal::Script::produce_compile_hints () const [inline]
Definition at line 147 of file script-inl.h.
                                         {
  return ProduceCompileHintsBit::decode(flags());
}
References flags().
Referenced by set_produce_compile_hints().
set_compilation_state()
void v8::internal::Script::set_compilation_state (CompilationState state) [inline]
Definition at line 143 of file script-inl.h.
                                                         {
  set_flags(CompilationStateBit::update(flags(), state));
}
References flags(), and set_flags().
set_compilation_type()
void v8::internal::Script::set_compilation_type (CompilationType type) [inline]
Definition at line 137 of file script-inl.h.
                                                      {
  set_flags(CompilationTypeBit::update(flags(), type));
}
References flags(), set_flags(), and v8::internal::tracing::type.
set_deserialized()
void v8::internal::Script::set_deserialized (bool value) [inline]
Definition at line 157 of file script-inl.h.
                                        {
  set_flags(DeserializedBit::update(flags(), value));
}
References flags(), set_flags(), and v8::internal::value.
set_flags()
void v8::internal::Script::set_flags (uint32_t new_flags) [inline]
Definition at line 129 of file script-inl.h.
                                         {
  DCHECK(is_int31(new_flags));
  TaggedField<Smi>::Relaxed_Store(*this, kFlagsOffset, Smi::FromInt(new_flags));
}
References v8::internal::DCHECK(), v8::internal::Smi::FromInt(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store().
Referenced by set_compilation_state(), set_compilation_type(), set_deserialized(), set_is_repl_mode(), set_origin_options(), set_produce_compile_hints(), and v8::internal::JSPromise::set_status().
set_is_repl_mode()
void v8::internal::Script::set_is_repl_mode (bool value) [inline]
Definition at line 163 of file script-inl.h.
                                        {
  set_flags(IsReplModeBit::update(flags(), value));
}
References flags(), set_flags(), and v8::internal::value.
set_origin_options()
void v8::internal::Script::set_origin_options (ScriptOriginOptions origin_options) [inline]
Definition at line 170 of file script-inl.h.
                                                                  {
  DCHECK(!(origin_options.Flags() & ~((1 << OriginOptionsBits::kSize) - 1)));
  set_flags(OriginOptionsBits::update(flags(), origin_options.Flags()));
}
References v8::internal::DCHECK(), v8::ScriptOriginOptions::Flags(), flags(), origin_options(), and set_flags().
set_produce_compile_hints()
void v8::internal::Script::set_produce_compile_hints (bool produce_compile_hints) [inline]
Definition at line 151 of file script-inl.h.
                                                                 {
  set_flags(ProduceCompileHintsBit::update(flags(), produce_compile_hints));
}
References flags(), produce_compile_hints(), and set_flags().
SetSource()
void v8::internal::Script::SetSource (Isolate * isolate, DirectHandle< Script > script, DirectHandle< String > source) [static]
Definition at line 4387 of file objects.cc.
                                                    {
  script->set_source(*source);
  if (isolate->NeedsSourcePositions()) {
    InitLineEnds(isolate, script);
  } else if (script->line_ends() ==
             ReadOnlyRoots(isolate).empty_fixed_array()) {
    DCHECK(script->has_line_ends());
    script->set_line_ends(Smi::zero());
    DCHECK(!script->has_line_ends());
  }
}
References v8::internal::DCHECK(), InitLineEnds(), v8::internal::Isolate::NeedsSourcePositions(), v8::internal::script, and v8::internal::Smi::zero().
Referenced by v8::internal::BackgroundCompileTask::FinalizeScript(), and v8::internal::CodeSerializer::FinishOffThreadDeserialize().
TraceScriptRundown()
void v8::internal::Script::TraceScriptRundown ()
Definition at line 4452 of file objects.cc.
                                {
  DisallowGarbageCollection no_gc;
  Isolate* isolate = Isolate::Current();
  Tagged<Object> context_value = isolate->native_context()->debug_context_id();
  int contextId = (IsSmi(context_value)) ? Smi::ToInt(context_value) : 0;
  auto value = v8::tracing::TracedValue::Create();
  value->SetInteger("scriptId", this->id());
  value->SetInteger("executionContextId", contextId);
  value->SetUnsignedInteger("isolate", isolate->debug()->IsolateId());
  value->SetBoolean("isModule", this->origin_options().IsModule());
  value->SetBoolean("hasSourceUrl", this->HasSourceURLComment());
  if (this->HasValidSource()) {
    if (this->HasSourceURLComment()) {
      value->SetString("sourceUrl",
                       Cast<String>(this->source_url())->ToCString().get());
    }
    if (this->HasSourceMappingURLComment()) {
      Tagged<String> sourceMapUrl = Cast<String>(this->source_mapping_url());
      // Source maps can be huge. Don't ever put a huge data url source map in
      // the trace. Also omit unusually large regular URLs.
      constexpr int kMaxSourceMapUrlLength = 2048;
      if (sourceMapUrl->length() > kMaxSourceMapUrlLength) {
        // Signal that there is a source map - clients may wish to request it by
        // other means (such as via CDP) or otherwise warn that a source map was
        // present but elided.
        value->SetBoolean("sourceMapUrlElided", true);
      } else {
        value->SetString("sourceMapUrl", sourceMapUrl->ToCString().get());
      }
    }
  }
  if (IsString(this->name())) {
    value->SetString("url", Cast<String>(this->name())->ToCString().get());
  }
  TRACE_EVENT1(TRACE_DISABLED_BY_DEFAULT("devtools.v8-source-rundown"),
               "ScriptCatchup", "data", std::move(value));
}
References v8::tracing::TracedValue::Create(), v8::internal::Isolate::Current(), v8::internal::Isolate::debug(), HasSourceMappingURLComment(), HasSourceURLComment(), HasValidSource(), v8::internal::IsModule(), v8::internal::Debug::IsolateId(), v8::internal::IsSmi(), v8::internal::name, v8::internal::Isolate::native_context(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, origin_options(), v8::internal::Smi::ToInt(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT1, and v8::internal::value.
TraceScriptRundownSources()
void v8::internal::Script::TraceScriptRundownSources ()
Definition at line 4490 of file objects.cc.
                                       {
  DisallowGarbageCollection no_gc;
  Isolate* isolate = Isolate::Current();
  if (!IsString(this->source())) return;
  Tagged<String> source = Cast<String>(this->source());
  auto script_id = this->id();
  int32_t source_length = source->length();
  const int32_t kSourceMaxLength = 25000000; // 25mb
  const int32_t kSplitMaxLength = 1000000; // 1mb
  if (source_length > kSourceMaxLength) {
    auto value = v8::tracing::TracedValue::Create();
    value->SetUnsignedInteger("isolate", isolate->debug()->IsolateId());
    value->SetInteger("scriptId", script_id);
    value->SetInteger("length", source_length);
    value->SetInteger("limit", kSourceMaxLength);
    TRACE_EVENT1(
        TRACE_DISABLED_BY_DEFAULT("devtools.v8-source-rundown-sources"),
        "TooLargeScriptCatchup", "data", std::move(value));
  } else if (source_length <= kSplitMaxLength) {
    auto value = v8::tracing::TracedValue::Create();
    value->SetUnsignedInteger("isolate", isolate->debug()->IsolateId());
    value->SetInteger("scriptId", script_id);
    value->SetInteger("length", source_length);
    value->SetString("sourceText", source->ToCString().get());
    TRACE_EVENT1(
        TRACE_DISABLED_BY_DEFAULT("devtools.v8-source-rundown-sources"),
        "ScriptCatchup", "data", std::move(value));
  } else {
    int32_t split_count = source_length / kSplitMaxLength + 1;
    std::unique_ptr<char[]> source_ptr = source->ToCString();
    for (int32_t i = 0; i < split_count; i++) {
      int32_t begin = i * kSplitMaxLength;
      int32_t end = std::min(begin + kSplitMaxLength, source_length);
      auto split_trace_value = v8::tracing::TracedValue::Create();
      split_trace_value->SetInteger("splitIndex", i);
      split_trace_value->SetInteger("splitCount", split_count);
      split_trace_value->SetUnsignedInteger("isolate",
                                            isolate->debug()->IsolateId());
      split_trace_value->SetInteger("scriptId", script_id);
      split_trace_value->SetString(
          "sourceText", std::string(source_ptr.get() + begin, end - begin));
      TRACE_EVENT1(
          TRACE_DISABLED_BY_DEFAULT("devtools.v8-source-rundown-sources"),
          "LargeScriptCatchup", "data", std::move(split_trace_value));
    }
  }
}
References v8::internal::compiler::begin(), v8::tracing::TracedValue::Create(), v8::internal::Isolate::Current(), v8::internal::Isolate::debug(), v8::internal::compiler::end(), v8::internal::Debug::IsolateId(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::string, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT1, and v8::internal::value.
Member Data Documentation
Factory
friend v8::internal::Script::Factory [private]
Definition at line 282 of file script.h.
FactoryBase< Factory >
friend v8::internal::Script::FactoryBase< Factory > [private]
Definition at line 283 of file script.h.
FactoryBase< LocalFactory >
friend v8::internal::Script::FactoryBase< LocalFactory > [private]
Definition at line 284 of file script.h.
kTemporaryScriptId
constexpr int v8::internal::Script::kTemporaryScriptId = -2 [static], [constexpr]
Definition at line 42 of file script.h.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnBothBackgroundAndMainThread(), v8::internal::ParseInfo::CreateScript(), v8::internal::UnoptimizedCompileFlags::ForTest(), v8::internal::HiddenLocalFactory::LocalFactory(), v8::internal::Debug::ProcessCompileEvent(), and v8::internal::Factory::ProcessNewScript().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/script.h
/mnt/V8SourceCode/src/objects/objects.cc
/mnt/V8SourceCode/src/objects/script-inl.h