cppgc::internal::ProcessHeapStatisticsUpdater Class Reference
#include <process-heap-statistics.h>
Classes
class AllocationObserverImpl
Static Public Member Functions
static void IncreaseTotalAllocatedObjectSize (size_t delta)
static void DecreaseTotalAllocatedObjectSize (size_t delta)
static void IncreaseTotalAllocatedSpace (size_t delta)
static void DecreaseTotalAllocatedSpace (size_t delta)
Detailed Description
Definition at line 14 of file process-heap-statistics.h.
Member Function Documentation
DecreaseTotalAllocatedObjectSize()
static void cppgc::internal::ProcessHeapStatisticsUpdater::DecreaseTotalAllocatedObjectSize (size_t delta) [inline], [static]
Definition at line 56 of file process-heap-statistics.h.
                                                             {
    ::cppgc::ProcessHeapStatistics::total_allocated_object_size_.fetch_sub(
        delta, std::memory_order_relaxed);
  }
References cppgc::ProcessHeapStatistics::total_allocated_object_size_.
Referenced by cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl::AllocatedObjectSizeDecreased(), and cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl::ResetAllocatedObjectSize().
DecreaseTotalAllocatedSpace()
static void cppgc::internal::ProcessHeapStatisticsUpdater::DecreaseTotalAllocatedSpace (size_t delta) [inline], [static]
Definition at line 64 of file process-heap-statistics.h.
                                                        {
    ::cppgc::ProcessHeapStatistics::total_allocated_space_.fetch_sub(
        delta, std::memory_order_relaxed);
  }
References cppgc::ProcessHeapStatistics::total_allocated_space_.
Referenced by cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl::AllocatedSizeDecreased().
IncreaseTotalAllocatedObjectSize()
static void cppgc::internal::ProcessHeapStatisticsUpdater::IncreaseTotalAllocatedObjectSize (size_t delta) [inline], [static]
Definition at line 52 of file process-heap-statistics.h.
                                                             {
    ::cppgc::ProcessHeapStatistics::total_allocated_object_size_.fetch_add(
        delta, std::memory_order_relaxed);
  }
References cppgc::ProcessHeapStatistics::total_allocated_object_size_.
Referenced by cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl::AllocatedObjectSizeIncreased(), and cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl::ResetAllocatedObjectSize().
IncreaseTotalAllocatedSpace()
static void cppgc::internal::ProcessHeapStatisticsUpdater::IncreaseTotalAllocatedSpace (size_t delta) [inline], [static]
Definition at line 60 of file process-heap-statistics.h.
                                                        {
    ::cppgc::ProcessHeapStatistics::total_allocated_space_.fetch_add(
        delta, std::memory_order_relaxed);
  }
References cppgc::ProcessHeapStatistics::total_allocated_space_.
Referenced by cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl::AllocatedSizeIncreased().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/process-heap-statistics.h