v8::internal::TypedFrameWithJSLinkage Class Reference
#include <frames.h>
Public Member Functions
void Iterate (RootVisitor *v) const override
Protected Member Functions
TypedFrameWithJSLinkage (StackFrameIteratorBase *iterator)
Additional Inherited Members
Detailed Description
Definition at line 749 of file frames.h.
Constructor & Destructor Documentation
TypedFrameWithJSLinkage()
v8::internal::TypedFrameWithJSLinkage::TypedFrameWithJSLinkage (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 123 of file frames-inl.h.
    : CommonFrameWithJSLinkage(iterator) {}
Member Function Documentation
Iterate()
void v8::internal::TypedFrameWithJSLinkage::Iterate (RootVisitor * v) const [override], [virtual]
Implements v8::internal::StackFrame.
Definition at line 334 of file frames.cc.
                                                          {
  IterateExpressions(v);
  IteratePc(v, constant_pool_address(), GcSafeLookupCode());
}
References v8::internal::StackFrame::constant_pool_address(), v8::internal::StackFrame::GcSafeLookupCode(), v8::internal::CommonFrame::IterateExpressions(), and v8::internal::StackFrame::IteratePc().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc