v8::base::RingBuffer< T, _SIZE > Class Template Reference
#include <ring-buffer.h>
Public Member Functions
constexpr RingBuffer ()=default
RingBuffer (const RingBuffer &)=delete
RingBuffer & operator= (const RingBuffer &)=delete
constexpr void Push (const T &value)
constexpr uint8_t Size () const
constexpr bool Empty () const
constexpr void Clear ()
template<typename Callback >
constexpr T Reduce (Callback callback, const T &initial) const
Static Public Attributes
static constexpr uint8_t kSize = _SIZE
Private Attributes
T elements_ [kSize]
uint8_t pos_ = 0
bool is_full_ = false
Detailed Description
template<typename T, uint8_t _SIZE = 10>
class v8::base::RingBuffer< T, _SIZE >
Definition at line 13 of file ring-buffer.h.
Constructor & Destructor Documentation
RingBuffer() [1/2]
template<typename T , uint8_t _SIZE = 10>
constexpr v8::base::RingBuffer< T, _SIZE >::RingBuffer () [constexpr], [default]
RingBuffer() [2/2]
template<typename T , uint8_t _SIZE = 10>
v8::base::RingBuffer< T, _SIZE >::RingBuffer (const RingBuffer< T, _SIZE > &) [delete]
Member Function Documentation
Clear()
template<typename T , uint8_t _SIZE = 10>
constexpr void v8::base::RingBuffer< T, _SIZE >::Clear () [inline], [constexpr]
Definition at line 34 of file ring-buffer.h.
                         {
    pos_ = 0;
    is_full_ = false;
  }
References v8::base::RingBuffer< T, _SIZE >::is_full_, and v8::base::RingBuffer< T, _SIZE >::pos_.
Referenced by v8::internal::GCTracer::ResetSurvivalEvents().
Empty()
template<typename T , uint8_t _SIZE = 10>
constexpr bool v8::base::RingBuffer< T, _SIZE >::Empty () const [inline], [constexpr]
Definition at line 32 of file ring-buffer.h.
{ return Size() == 0; }
References v8::base::RingBuffer< T, _SIZE >::Size().
Referenced by v8::internal::GCTracer::AverageSurvivalRatio(), and v8::internal::GCTracer::SurvivalEventsRecorded().
operator=()
template<typename T , uint8_t _SIZE = 10>
RingBuffer& v8::base::RingBuffer< T, _SIZE >::operator= (const RingBuffer< T, _SIZE > &) [delete]
Push()
template<typename T , uint8_t _SIZE = 10>
constexpr void v8::base::RingBuffer< T, _SIZE >::Push (const T & value) [inline], [constexpr]
Definition at line 22 of file ring-buffer.h.
                                      {
    elements_[pos_++] = value;
    if (pos_ == kSize) {
      pos_ = 0;
      is_full_ = true;
    }
  }
References v8::base::RingBuffer< T, _SIZE >::elements_, v8::base::RingBuffer< T, _SIZE >::is_full_, v8::base::RingBuffer< T, _SIZE >::kSize, v8::base::RingBuffer< T, _SIZE >::pos_, and v8::internal::value.
Referenced by v8::internal::GCTracer::AddCompactionEvent(), v8::internal::GCTracer::AddSurvivalRatio(), v8::internal::GCTracer::RecordEmbedderMarkingSpeed(), v8::internal::GCTracer::RecordGCSumCounters(), v8::internal::GCTracer::StopCycle(), and v8::internal::GCTracer::StopObservablePause().
Reduce()
template<typename T , uint8_t _SIZE = 10>
template<typename Callback >
constexpr T v8::base::RingBuffer< T, _SIZE >::Reduce (Callback callback, const T & initial) const [inline], [constexpr]
Definition at line 40 of file ring-buffer.h.
                                                                {
    T result = initial;
    for (uint8_t i = pos_; i > 0; --i) {
      result = callback(result, elements_[i - 1]);
    }
    if (!is_full_) {
      return result;
    }
    for (uint8_t i = kSize; i > pos_; --i) {
      result = callback(result, elements_[i - 1]);
    }
    return result;
  }
References v8::base::RingBuffer< T, _SIZE >::elements_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::RingBuffer< T, _SIZE >::is_full_, v8::base::RingBuffer< T, _SIZE >::kSize, v8::base::RingBuffer< T, _SIZE >::pos_, and v8::base::internal::result.
Referenced by heap::base::AverageSpeed(), and v8::internal::GCTracer::AverageSurvivalRatio().
Size()
template<typename T , uint8_t _SIZE = 10>
constexpr uint8_t v8::base::RingBuffer< T, _SIZE >::Size () const [inline], [constexpr]
Definition at line 30 of file ring-buffer.h.
{ return is_full_ ? kSize : pos_; }
References v8::base::RingBuffer< T, _SIZE >::is_full_, v8::base::RingBuffer< T, _SIZE >::kSize, and v8::base::RingBuffer< T, _SIZE >::pos_.
Referenced by v8::internal::GCTracer::AverageSurvivalRatio(), and v8::base::RingBuffer< T, _SIZE >::Empty().
Member Data Documentation
elements_
template<typename T , uint8_t _SIZE = 10>
T v8::base::RingBuffer< T, _SIZE >::elements_[kSize] [private]
Definition at line 55 of file ring-buffer.h.
Referenced by v8::base::RingBuffer< T, _SIZE >::Push(), and v8::base::RingBuffer< T, _SIZE >::Reduce().
is_full_
template<typename T , uint8_t _SIZE = 10>
bool v8::base::RingBuffer< T, _SIZE >::is_full_ = false [private]
Definition at line 57 of file ring-buffer.h.
Referenced by v8::base::RingBuffer< T, _SIZE >::Clear(), v8::base::RingBuffer< T, _SIZE >::Push(), v8::base::RingBuffer< T, _SIZE >::Reduce(), and v8::base::RingBuffer< T, _SIZE >::Size().
kSize
template<typename T , uint8_t _SIZE = 10>
constexpr uint8_t v8::base::RingBuffer< T, _SIZE >::kSize = _SIZE [static], [constexpr]
Definition at line 15 of file ring-buffer.h.
Referenced by v8::base::RingBuffer< T, _SIZE >::Push(), v8::base::RingBuffer< T, _SIZE >::Reduce(), and v8::base::RingBuffer< T, _SIZE >::Size().
pos_
template<typename T , uint8_t _SIZE = 10>
uint8_t v8::base::RingBuffer< T, _SIZE >::pos_ = 0 [private]
Definition at line 56 of file ring-buffer.h.
Referenced by v8::base::RingBuffer< T, _SIZE >::Clear(), v8::base::RingBuffer< T, _SIZE >::Push(), v8::base::RingBuffer< T, _SIZE >::Reduce(), and v8::base::RingBuffer< T, _SIZE >::Size().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/ring-buffer.h