v8::internal::DateParser::InputReader< Char > Class Template Reference
Public Member Functions
InputReader (base::Vector< Char > s)
int position ()
void Next ()
int ReadUnsignedNumeral ()
int ReadWord (uint32_t *prefix, int prefix_size)
bool Skip (uint32_t c)
bool SkipWhiteSpace ()
bool SkipParentheses ()
bool Is (uint32_t c) const
bool IsEnd () const
bool IsAsciiDigit () const
bool IsAsciiAlphaOrAbove () const
bool IsWhiteSpaceChar () const
bool IsAsciiSign () const
int GetAsciiSignValue () const
Private Attributes
int index_
base::Vector< Char > buffer_
uint32_t ch_
Detailed Description
template<typename Char>
class v8::internal::DateParser::InputReader< Char >
Definition at line 58 of file dateparser.h.
Constructor & Destructor Documentation
InputReader()
template<typename Char >
v8::internal::DateParser::InputReader< Char >::InputReader (base::Vector< Char > s) [inline], [explicit]
Definition at line 60 of file dateparser.h.
                                             : index_(0), buffer_(s) {
      Next();
    }
References v8::internal::DateParser::InputReader< Char >::Next().
Member Function Documentation
GetAsciiSignValue()
template<typename Char >
int v8::internal::DateParser::InputReader< Char >::GetAsciiSignValue () const [inline]
Definition at line 123 of file dateparser.h.
{ return 44 - static_cast<int>(ch_); }
References v8::internal::DateParser::InputReader< Char >::ch_.
Is()
template<typename Char >
bool v8::internal::DateParser::InputReader< Char >::Is (uint32_t c) const [inline]
Definition at line 115 of file dateparser.h.
{ return ch_ == c; }
References v8::internal::DateParser::InputReader< Char >::ch_.
IsAsciiAlphaOrAbove()
template<typename Char >
bool v8::internal::DateParser::InputReader< Char >::IsAsciiAlphaOrAbove () const [inline]
Definition at line 118 of file dateparser.h.
{ return ch_ >= 'A'; }
References v8::internal::DateParser::InputReader< Char >::ch_.
Referenced by v8::internal::DateParser::InputReader< Char >::ReadWord().
IsAsciiDigit()
template<typename Char >
bool v8::internal::DateParser::InputReader< Char >::IsAsciiDigit () const [inline]
Definition at line 117 of file dateparser.h.
{ return IsDecimalDigit(ch_); }
References v8::internal::DateParser::InputReader< Char >::ch_, and v8::internal::IsDecimalDigit().
Referenced by v8::internal::DateParser::InputReader< Char >::ReadUnsignedNumeral().
IsAsciiSign()
template<typename Char >
bool v8::internal::DateParser::InputReader< Char >::IsAsciiSign () const [inline]
Definition at line 120 of file dateparser.h.
{ return ch_ == '+' || ch_ == '-'; }
References v8::internal::DateParser::InputReader< Char >::ch_.
IsEnd()
template<typename Char >
bool v8::internal::DateParser::InputReader< Char >::IsEnd () const [inline]
Definition at line 116 of file dateparser.h.
{ return ch_ == 0; }
References v8::internal::DateParser::InputReader< Char >::ch_.
IsWhiteSpaceChar()
template<typename Char >
bool v8::internal::DateParser::InputReader< Char >::IsWhiteSpaceChar () const [inline]
Definition at line 119 of file dateparser.h.
{ return IsWhiteSpace(ch_); }
References v8::internal::DateParser::InputReader< Char >::ch_, and v8::internal::IsWhiteSpace().
Referenced by v8::internal::DateParser::InputReader< Char >::ReadWord().
Next()
template<typename Char >
void v8::internal::DateParser::InputReader< Char >::Next () [inline]
Definition at line 67 of file dateparser.h.
                {
      ch_ = (index_ < buffer_.length()) ? buffer_[index_] : 0;
      index_++;
    }
References v8::internal::DateParser::InputReader< Char >::buffer_, v8::internal::DateParser::InputReader< Char >::ch_, v8::internal::DateParser::InputReader< Char >::index_, and v8::base::Vector< T >::length().
Referenced by v8::internal::DateParser::InputReader< Char >::InputReader(), v8::internal::DateParser::InputReader< Char >::ReadUnsignedNumeral(), v8::internal::DateParser::InputReader< Char >::ReadWord(), and v8::internal::DateParser::InputReader< Char >::Skip().
position()
template<typename Char >
int v8::internal::DateParser::InputReader< Char >::position () [inline]
Definition at line 64 of file dateparser.h.
{ return index_; }
References v8::internal::DateParser::InputReader< Char >::index_.
ReadUnsignedNumeral()
template<typename Char >
int v8::internal::DateParser::InputReader< Char >::ReadUnsignedNumeral () [inline]
Definition at line 75 of file dateparser.h.
                              {
      int n = 0;
      int i = 0;
      // First, skip leading zeros
      while (ch_ == '0') Next();
      // And then, do the conversion
      while (IsAsciiDigit()) {
        if (i < kMaxSignificantDigits) n = n * 10 + ch_ - '0';
        i++;
        Next();
      }
      return n;
    }
References v8::internal::DateParser::InputReader< Char >::ch_, v8::internal::DateParser::InputReader< Char >::IsAsciiDigit(), v8::internal::DateParser::kMaxSignificantDigits, and v8::internal::DateParser::InputReader< Char >::Next().
ReadWord()
template<typename Char >
int v8::internal::DateParser::InputReader< Char >::ReadWord (uint32_t * prefix, int prefix_size) [inline]
Definition at line 92 of file dateparser.h.
                                                    {
      int len;
      for (len = 0; IsAsciiAlphaOrAbove() && !IsWhiteSpaceChar();
           Next(), len++) {
        if (len < prefix_size) prefix[len] = AsciiAlphaToLower(ch_);
      }
      for (int i = len; i < prefix_size; i++) prefix[i] = 0;
      return len;
    }
References v8::internal::AsciiAlphaToLower(), v8::internal::DateParser::InputReader< Char >::ch_, v8::internal::DateParser::InputReader< Char >::IsAsciiAlphaOrAbove(), v8::internal::DateParser::InputReader< Char >::IsWhiteSpaceChar(), and v8::internal::DateParser::InputReader< Char >::Next().
Skip()
template<typename Char >
bool v8::internal::DateParser::InputReader< Char >::Skip (uint32_t c) [inline]
Definition at line 103 of file dateparser.h.
                          {
      if (ch_ == c) {
        Next();
        return true;
      }
      return false;
    }
References v8::internal::DateParser::InputReader< Char >::ch_, and v8::internal::DateParser::InputReader< Char >::Next().
SkipParentheses()
template<typename Char >
bool v8::internal::DateParser::InputReader< Char >::SkipParentheses () [inline]
Definition at line 225 of file dateparser-inl.h.
                                                  {
  if (ch_ != '(') return false;
  int balance = 0;
  do {
    if (ch_ == ')')
      --balance;
    else if (ch_ == '(')
      ++balance;
    Next();
  } while (balance > 0 && ch_);
  return true;
}
References v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next().
SkipWhiteSpace()
template<typename Char >
bool v8::internal::DateParser::InputReader< Char >::SkipWhiteSpace () [inline]
Definition at line 216 of file dateparser-inl.h.
                                                 {
  if (IsWhiteSpaceOrLineTerminator(ch_)) {
    Next();
    return true;
  }
  return false;
}
References v8::internal::IsWhiteSpaceOrLineTerminator(), and v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next().
Member Data Documentation
buffer_
template<typename Char >
base::Vector<Char> v8::internal::DateParser::InputReader< Char >::buffer_ [private]
Definition at line 127 of file dateparser.h.
Referenced by v8::internal::DateParser::InputReader< Char >::Next().
ch_
template<typename Char >
uint32_t v8::internal::DateParser::InputReader< Char >::ch_ [private]
Definition at line 128 of file dateparser.h.
Referenced by v8::internal::DateParser::InputReader< Char >::GetAsciiSignValue(), v8::internal::DateParser::InputReader< Char >::Is(), v8::internal::DateParser::InputReader< Char >::IsAsciiAlphaOrAbove(), v8::internal::DateParser::InputReader< Char >::IsAsciiDigit(), v8::internal::DateParser::InputReader< Char >::IsAsciiSign(), v8::internal::DateParser::InputReader< Char >::IsEnd(), v8::internal::DateParser::InputReader< Char >::IsWhiteSpaceChar(), v8::internal::DateParser::InputReader< Char >::Next(), v8::internal::DateParser::InputReader< Char >::ReadUnsignedNumeral(), v8::internal::DateParser::InputReader< Char >::ReadWord(), and v8::internal::DateParser::InputReader< Char >::Skip().
index_
template<typename Char >
int v8::internal::DateParser::InputReader< Char >::index_ [private]
Definition at line 126 of file dateparser.h.
Referenced by v8::internal::DateParser::InputReader< Char >::Next(), and v8::internal::DateParser::InputReader< Char >::position().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/date/dateparser.h
/mnt/V8SourceCode/src/date/dateparser-inl.h