cppgc::internal::SequentialUnmarker Class Reference
#include <unmarker.h>
Public Member Functions
SequentialUnmarker (RawHeap &heap)
bool VisitNormalPage (NormalPage &page)
bool VisitLargePage (LargePage &page)
Private Member Functions
bool VisitHeapObjectHeader (HeapObjectHeader &header)
Friends
class HeapVisitor< SequentialUnmarker >
Detailed Description
Definition at line 14 of file unmarker.h.
Constructor & Destructor Documentation
SequentialUnmarker()
cppgc::internal::SequentialUnmarker::SequentialUnmarker (RawHeap & heap) [inline], [explicit]
Definition at line 18 of file unmarker.h.
{ Traverse(heap); }
References cppgc::internal::HeapVisitor< SequentialUnmarker >::Traverse().
Member Function Documentation
VisitHeapObjectHeader()
bool cppgc::internal::SequentialUnmarker::VisitHeapObjectHeader (HeapObjectHeader & header) [inline], [private]
Definition at line 31 of file unmarker.h.
                                                       {
    if (header.IsMarked()) {
      header.Unmark();
    }
    return true;
  }
References cppgc::internal::HeapObjectHeader::IsMarked(), and cppgc::internal::HeapObjectHeader::Unmark().
VisitLargePage()
bool cppgc::internal::SequentialUnmarker::VisitLargePage (LargePage & page) [inline]
Definition at line 25 of file unmarker.h.
                                       {
    page.ResetMarkedBytes();
    return false;
  }
References cppgc::internal::BasePage::ResetMarkedBytes().
VisitNormalPage()
bool cppgc::internal::SequentialUnmarker::VisitNormalPage (NormalPage & page) [inline]
Definition at line 20 of file unmarker.h.
                                         {
    page.ResetMarkedBytes();
    return false;
  }
References cppgc::internal::BasePage::ResetMarkedBytes().
Friends And Related Function Documentation
HeapVisitor< SequentialUnmarker >
friend class HeapVisitor< SequentialUnmarker > [friend]
Definition at line 1 of file unmarker.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/unmarker.h