v8::internal::SyntheticModule Class Reference
#include <synthetic-module.h>
Public Types
using BodyDescriptor = SubclassBodyDescriptor< Module::BodyDescriptor, FixedBodyDescriptor< kNameOffset, kSize, kSize > >
Static Public Member Functions
static Maybe< bool > SetExport (Isolate *isolate, DirectHandle< SyntheticModule > module, DirectHandle< String > export_name, DirectHandle< Object > export_value)
static void SetExportStrict (Isolate *isolate, DirectHandle< SyntheticModule > module, DirectHandle< String > export_name, DirectHandle< Object > export_value)
Static Private Member Functions
static V8_WARN_UNUSED_RESULT MaybeHandle< Cell > ResolveExport (Isolate *isolate, DirectHandle< SyntheticModule > module, DirectHandle< String > module_specifier, DirectHandle< String > export_name, MessageLocation loc, bool must_resolve)
static V8_WARN_UNUSED_RESULT bool PrepareInstantiate (Isolate *isolate, DirectHandle< SyntheticModule > module, v8::Local< v8::Context > context)
static V8_WARN_UNUSED_RESULT bool FinishInstantiate (Isolate *isolate, DirectHandle< SyntheticModule > module)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Evaluate (Isolate *isolate, DirectHandle< SyntheticModule > module)
Friends
class Module
Detailed Description
Definition at line 22 of file synthetic-module.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::SyntheticModule::BodyDescriptor = SubclassBodyDescriptor<Module::BodyDescriptor, FixedBodyDescriptor<kNameOffset, kSize, kSize> >
Definition at line 45 of file synthetic-module.h.
Member Function Documentation
Evaluate()
MaybeDirectHandle< Object > v8::internal::SyntheticModule::Evaluate (Isolate * isolate, DirectHandle< SyntheticModule > module) [static], [private]
Definition at line 101 of file synthetic-module.cc.
                                                            {
  module->SetStatus(kEvaluating);
  v8::Module::SyntheticModuleEvaluationSteps evaluation_steps =
      FUNCTION_CAST<v8::Module::SyntheticModuleEvaluationSteps>(
          module->evaluation_steps()->foreign_address<kSyntheticModuleTag>());
  v8::Local<v8::Value> result;
  if (!evaluation_steps(Utils::ToLocal(isolate->native_context()),
                        Utils::ToLocal(Cast<Module>(module)))
           .ToLocal(&result)) {
    module->RecordError(isolate, isolate->exception());
    return MaybeDirectHandle<Object>();
  }
  module->SetStatus(kEvaluated);
  DirectHandle<Object> result_from_callback = Utils::OpenDirectHandle(*result);
  DirectHandle<JSPromise> capability;
  if (IsJSPromise(*result_from_callback)) {
    capability = Cast<JSPromise>(result_from_callback);
  } else {
    // The host's evaluation steps should have returned a resolved Promise,
    // but as an allowance to hosts that have not yet finished the migration
    // to top-level await, create a Promise if the callback result didn't give
    // us one.
    capability = isolate->factory()->NewJSPromise();
    JSPromise::Resolve(capability, isolate->factory()->undefined_value())
        .ToHandleChecked();
  }
  module->set_top_level_capability(*capability);
  return result_from_callback;
}
References v8::internal::Isolate::exception(), v8::internal::Isolate::factory(), v8::internal::kSyntheticModuleTag, v8::internal::Isolate::native_context(), v8::internal::Factory::NewJSPromise(), v8::Utils::OpenDirectHandle(), v8::internal::JSPromise::Resolve(), v8::base::internal::result, and v8::MaybeLocal< T >::ToLocal().
Referenced by v8::internal::Module::Evaluate().
FinishInstantiate()
bool v8::internal::SyntheticModule::FinishInstantiate (Isolate * isolate, DirectHandle< SyntheticModule > module) [static], [private]
Definition at line 93 of file synthetic-module.cc.
                                                                              {
  module->SetStatus(kLinked);
  return true;
}
Referenced by v8::internal::Module::FinishInstantiate().
PrepareInstantiate()
bool v8::internal::SyntheticModule::PrepareInstantiate (Isolate * isolate, DirectHandle< SyntheticModule > module, v8::Local< v8::Context > context) [static], [private]
Definition at line 72 of file synthetic-module.cc.
                                                                     {
  Handle<ObjectHashTable> exports(module->exports(), isolate);
  DirectHandle<FixedArray> export_names(module->export_names(), isolate);
  // Spec step 7: For each export_name in module->export_names...
  for (int i = 0, n = export_names->length(); i < n; ++i) {
    // Spec step 7.1: Create a new mutable binding for export_name.
    // Spec step 7.2: Initialize the new mutable binding to undefined.
    DirectHandle<Cell> cell = isolate->factory()->NewCell();
    DirectHandle<String> name(Cast<String>(export_names->get(i)), isolate);
    CHECK(IsTheHole(exports->Lookup(name), isolate));
    exports = ObjectHashTable::Put(exports, name, cell);
  }
  module->set_exports(*exports);
  return true;
}
References CHECK, v8::internal::Isolate::factory(), v8::internal::name, and v8::internal::Factory::NewCell().
Referenced by v8::internal::Module::PrepareInstantiate().
ResolveExport()
MaybeHandle< Cell > v8::internal::SyntheticModule::ResolveExport (Isolate * isolate, DirectHandle< SyntheticModule > module, DirectHandle< String > module_specifier, DirectHandle< String > export_name, MessageLocation loc, bool must_resolve) [static], [private]
Definition at line 54 of file synthetic-module.cc.
                                            {
  Handle<Object> object(module->exports()->Lookup(export_name), isolate);
  if (IsCell(*object)) return Cast<Cell>(object);
  if (!must_resolve) return kNullMaybeHandle;
  isolate->ThrowAt(
      isolate->factory()->NewSyntaxError(MessageTemplate::kUnresolvableExport,
                                         module_specifier, export_name),
      &loc);
  return kNullMaybeHandle;
}
References v8::internal::Isolate::factory(), v8::internal::kNullMaybeHandle, v8::internal::loc, and v8::internal::Isolate::ThrowAt().
Referenced by v8::internal::Module::ResolveExport().
SetExport()
Maybe< bool > v8::internal::SyntheticModule::SetExport (Isolate * isolate, DirectHandle< SyntheticModule > module, DirectHandle< String > export_name, DirectHandle< Object > export_value) [static]
Definition at line 21 of file synthetic-module.cc.
                                                                          {
  DirectHandle<ObjectHashTable> exports(module->exports(), isolate);
  DirectHandle<Object> export_object(exports->Lookup(export_name), isolate);
  if (!IsCell(*export_object)) {
    isolate->Throw(*isolate->factory()->NewReferenceError(
        MessageTemplate::kModuleExportUndefined, export_name));
    return Nothing<bool>();
  }
  // Spec step 2: Set the mutable binding of export_name to export_value
  Cast<Cell>(*export_object)->set_value(*export_value);
  return Just(true);
}
References v8::internal::Isolate::factory(), v8::Just(), and v8::internal::Isolate::Throw().
Referenced by SetExportStrict(), and v8::Module::SetSyntheticModuleExport().
SetExportStrict()
void v8::internal::SyntheticModule::SetExportStrict (Isolate * isolate, DirectHandle< SyntheticModule > module, DirectHandle< String > export_name, DirectHandle< Object > export_value) [static]
Definition at line 40 of file synthetic-module.cc.
                                                                         {
  DirectHandle<ObjectHashTable> exports(module->exports(), isolate);
  DirectHandle<Object> export_object(exports->Lookup(export_name), isolate);
  CHECK(IsCell(*export_object));
  Maybe<bool> set_export_result =
      SetExport(isolate, module, export_name, export_value);
  CHECK(set_export_result.FromJust());
}
References CHECK, v8::Maybe< T >::FromJust(), and SetExport().
Friends And Related Function Documentation
Module
friend class Module [friend]
Definition at line 50 of file synthetic-module.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/synthetic-module.h
/mnt/V8SourceCode/src/objects/synthetic-module.cc