v8::internal::torque::cpp::IncludeGuardScope Class Reference
#include <cpp-builder.h>
Public Member Functions
IncludeGuardScope (File *file, std::string name)
IncludeGuardScope (const IncludeGuardScope &)=delete
IncludeGuardScope (IncludeGuardScope &&other) V8_NOEXCEPT
~IncludeGuardScope ()
IncludeGuardScope & operator= (const IncludeGuardScope &)=delete
IncludeGuardScope & operator= (IncludeGuardScope &&other) V8_NOEXCEPT
Private Attributes
File * file_
std::string name_
Detailed Description
Definition at line 208 of file cpp-builder.h.
Constructor & Destructor Documentation
IncludeGuardScope() [1/3]
v8::internal::torque::cpp::IncludeGuardScope::IncludeGuardScope (File * file, std::string name) [inline], [explicit]
Definition at line 210 of file cpp-builder.h.
      : file_(file), name_(std::move(name)) {
    file_->BeginIncludeGuard(name_);
  }
References v8::internal::torque::cpp::File::BeginIncludeGuard(), file_, and name_.
IncludeGuardScope() [2/3]
v8::internal::torque::cpp::IncludeGuardScope::IncludeGuardScope (const IncludeGuardScope &) [delete]
IncludeGuardScope() [3/3]
v8::internal::torque::cpp::IncludeGuardScope::IncludeGuardScope (IncludeGuardScope && other) [inline]
Definition at line 215 of file cpp-builder.h.
                                                           : file_(nullptr),
                                                             name_() {
    std::swap(file_, other.file_);
    std::swap(name_, other.name_);
  }
References file_, and name_.
 IncludeGuardScope()
v8::internal::torque::cpp::IncludeGuardScope::~IncludeGuardScope () [inline]
Definition at line 220 of file cpp-builder.h.
                       {
    if (file_) {
      file_->EndIncludeGuard(name_);
    }
  }
References v8::internal::torque::cpp::File::EndIncludeGuard(), file_, and name_.
Member Function Documentation
operator=() [1/2]
IncludeGuardScope& v8::internal::torque::cpp::IncludeGuardScope::operator= (const IncludeGuardScope &) [delete]
operator=() [2/2]
IncludeGuardScope& v8::internal::torque::cpp::IncludeGuardScope::operator= (IncludeGuardScope && other) [inline]
Definition at line 226 of file cpp-builder.h.
                                                                      {
    if (this != &other) {
      DCHECK_NULL(file_);
      DCHECK(name_.empty());
      std::swap(file_, other.file_);
      std::swap(name_, other.name_);
    }
    return *this;
  }
References v8::internal::DCHECK(), DCHECK_NULL, file_, and name_.
Member Data Documentation
file_
File* v8::internal::torque::cpp::IncludeGuardScope::file_ [private]
Definition at line 237 of file cpp-builder.h.
Referenced by IncludeGuardScope(), operator=(), and ~IncludeGuardScope().
name_
std::string v8::internal::torque::cpp::IncludeGuardScope::name_ [private]
Definition at line 238 of file cpp-builder.h.
Referenced by IncludeGuardScope(), operator=(), and ~IncludeGuardScope().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/cpp-builder.h