v8::HeapSpaceStatistics Class Reference
#include <v8-statistics.h>
Public Member Functions
HeapSpaceStatistics ()
const char * space_name ()
size_t space_size ()
size_t space_used_size ()
size_t space_available_size ()
size_t physical_space_size ()
Private Attributes
const char * space_name_
size_t space_size_
size_t space_used_size_
size_t space_available_size_
size_t physical_space_size_
Friends
class Isolate
Detailed Description
Definition at line 183 of file v8-statistics.h.
Constructor & Destructor Documentation
HeapSpaceStatistics()
v8::HeapSpaceStatistics::HeapSpaceStatistics ()
Definition at line 6482 of file api.cc.
    : space_name_(nullptr),
      space_size_(0),
      space_used_size_(0),
      space_available_size_(0),
      physical_space_size_(0) {}
Member Function Documentation
physical_space_size()
size_t v8::HeapSpaceStatistics::physical_space_size () [inline]
Definition at line 190 of file v8-statistics.h.
{ return physical_space_size_; }
Referenced by v8::internal::Heap::DumpJSONHeapStatistics().
space_available_size()
size_t v8::HeapSpaceStatistics::space_available_size () [inline]
Definition at line 189 of file v8-statistics.h.
{ return space_available_size_; }
Referenced by v8::internal::Heap::DumpJSONHeapStatistics().
space_name()
const char* v8::HeapSpaceStatistics::space_name () [inline]
Definition at line 186 of file v8-statistics.h.
{ return space_name_; }
space_size()
size_t v8::HeapSpaceStatistics::space_size () [inline]
Definition at line 187 of file v8-statistics.h.
{ return space_size_; }
Referenced by v8::internal::Heap::DumpJSONHeapStatistics().
space_used_size()
size_t v8::HeapSpaceStatistics::space_used_size () [inline]
Definition at line 188 of file v8-statistics.h.
{ return space_used_size_; }
Referenced by v8::internal::Heap::DumpJSONHeapStatistics().
Friends And Related Function Documentation
Isolate
friend class Isolate [friend]
Definition at line 199 of file v8-statistics.h.
Member Data Documentation
physical_space_size_
size_t v8::HeapSpaceStatistics::physical_space_size_ [private]
Definition at line 197 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapSpaceStatistics().
space_available_size_
size_t v8::HeapSpaceStatistics::space_available_size_ [private]
Definition at line 196 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapSpaceStatistics().
space_name_
const char* v8::HeapSpaceStatistics::space_name_ [private]
Definition at line 193 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapSpaceStatistics().
space_size_
size_t v8::HeapSpaceStatistics::space_size_ [private]
Definition at line 194 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapSpaceStatistics().
space_used_size_
size_t v8::HeapSpaceStatistics::space_used_size_ [private]
Definition at line 195 of file v8-statistics.h.
Referenced by v8::Isolate::GetHeapSpaceStatistics().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-statistics.h
/mnt/V8SourceCode/src/api/api.cc