v8::internal::UnaryOpAssembler Class Reference
#include <unary-op-assembler.h>
Public Member Functions
UnaryOpAssembler (compiler::CodeAssemblerState *state)
TNode< Object > Generate_BitwiseNotWithFeedback (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode)
TNode< Object > Generate_DecrementWithFeedback (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode)
TNode< Object > Generate_IncrementWithFeedback (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode)
TNode< Object > Generate_NegateWithFeedback (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode)
Private Attributes
compiler::CodeAssemblerState *const state_
Detailed Description
Definition at line 17 of file unary-op-assembler.h.
Constructor & Destructor Documentation
UnaryOpAssembler()
v8::internal::UnaryOpAssembler::UnaryOpAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 19 of file unary-op-assembler.h.
      : state_(state) {}
Member Function Documentation
Generate_BitwiseNotWithFeedback()
TNode< Object > v8::internal::UnaryOpAssembler::Generate_BitwiseNotWithFeedback (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode)
Definition at line 283 of file unary-op-assembler.cc.
                                             {
  UnaryOpAssemblerImpl a(state_);
  return a.BitwiseNot(context, value, slot, maybe_feedback_vector,
                      update_feedback_mode);
}
References state_, and v8::internal::value.
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER().
Generate_DecrementWithFeedback()
TNode< Object > v8::internal::UnaryOpAssembler::Generate_DecrementWithFeedback (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode)
Definition at line 292 of file unary-op-assembler.cc.
                                             {
  UnaryOpAssemblerImpl a(state_);
  return a.Decrement(context, value, slot, maybe_feedback_vector,
                     update_feedback_mode);
}
References state_, and v8::internal::value.
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER().
Generate_IncrementWithFeedback()
TNode< Object > v8::internal::UnaryOpAssembler::Generate_IncrementWithFeedback (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode)
Definition at line 301 of file unary-op-assembler.cc.
                                             {
  UnaryOpAssemblerImpl a(state_);
  return a.Increment(context, value, slot, maybe_feedback_vector,
                     update_feedback_mode);
}
References state_, and v8::internal::value.
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER().
Generate_NegateWithFeedback()
TNode< Object > v8::internal::UnaryOpAssembler::Generate_NegateWithFeedback (TNode< Context > context, TNode< Object > value, TNode< UintPtrT > slot, TNode< HeapObject > maybe_feedback_vector, UpdateFeedbackMode update_feedback_mode)
Definition at line 310 of file unary-op-assembler.cc.
                                             {
  UnaryOpAssemblerImpl a(state_);
  return a.Negate(context, value, slot, maybe_feedback_vector,
                  update_feedback_mode);
}
References state_, and v8::internal::value.
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::IGNITION_HANDLER().
Member Data Documentation
state_
compiler::CodeAssemblerState* const v8::internal::UnaryOpAssembler::state_ [private]
Definition at line 43 of file unary-op-assembler.h.
Referenced by Generate_BitwiseNotWithFeedback(), Generate_DecrementWithFeedback(), Generate_IncrementWithFeedback(), and Generate_NegateWithFeedback().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ic/unary-op-assembler.h
/mnt/V8SourceCode/src/ic/unary-op-assembler.cc