v8::internal::OptimizingCompileTaskExecutor::CompileTask Class Reference
Public Member Functions
CompileTask (OptimizingCompileTaskExecutor *task_executor)
void Run (JobDelegate *delegate) override
size_t GetMaxConcurrency (size_t worker_count) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Private Attributes
OptimizingCompileTaskExecutor * task_executor_
Detailed Description
Definition at line 29 of file optimizing-compile-dispatcher.cc.
Constructor & Destructor Documentation
CompileTask()
v8::internal::OptimizingCompileTaskExecutor::CompileTask::CompileTask (OptimizingCompileTaskExecutor * task_executor) [inline], [explicit]
Definition at line 31 of file optimizing-compile-dispatcher.cc.
      : task_executor_(task_executor) {}
Member Function Documentation
GetMaxConcurrency()
size_t v8::internal::OptimizingCompileTaskExecutor::CompileTask::GetMaxConcurrency (size_t worker_count) const [inline], [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 85 of file optimizing-compile-dispatcher.cc.
                                                               {
    size_t num_tasks = task_executor_->input_queue_.Length() + worker_count;
    return std::min(num_tasks, task_executor_->task_states_.size());
  }
References v8::internal::OptimizingCompileTaskExecutor::input_queue_, v8::internal::OptimizingCompileInputQueue::Length(), task_executor_, and v8::internal::OptimizingCompileTaskExecutor::task_states_.
Run()
void v8::internal::OptimizingCompileTaskExecutor::CompileTask::Run (JobDelegate * delegate) [inline], [override], [virtual]
Implements v8::JobTask.
Definition at line 34 of file optimizing-compile-dispatcher.cc.
                                           {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"), "V8.TurbofanTask");
    DCHECK_LT(delegate->GetTaskId(), task_executor_->task_states_.size());
    OptimizingCompileTaskState& task_state =
        task_executor_->task_states_[delegate->GetTaskId()];
    bool should_yield = delegate->ShouldYield();
    while (!should_yield) {
      // NextInput() sets the isolate for task_state to job->isolate() while
      // holding the lock.
      TurbofanCompilationJob* job = task_executor_->NextInput(task_state);
      if (!job) break;
      Isolate* const isolate = job->isolate();
      {
        base::FlushDenormalsScope flush_denormals_scope(
            isolate->flush_denormals());
        // Note that LocalIsolate's lifetime is shorter than the isolate value
        // in task_state which is only cleared after this LocalIsolate instance
        // was destroyed.
        LocalIsolate local_isolate(isolate, ThreadKind::kBackground);
        DCHECK(local_isolate.heap()->IsParked());
        do {
          task_executor_->RunCompilationJob(task_state, isolate, local_isolate,
                                            job);
          should_yield = delegate->ShouldYield();
          if (should_yield) break;
          // Reuse the LocalIsolate if the next worklist item has the same
          // isolate.
          job = task_executor_->NextInputIfIsolateMatches(task_state);
        } while (job);
      }
      // Reset the isolate in the task state to nullptr. Only do this after the
      // LocalIsolate was destroyed. This invariant is used by
      // WaitUntilTasksStoppedForIsolate() to ensure all tasks are stopped for
      // an isolate.
      task_executor_->ClearTaskState(task_state);
    }
    // Here we are allowed to read the isolate without holding a lock because
    // only this thread here will ever change this field and the main thread
    // will only ever read it.
    DCHECK_NULL(task_state.isolate);
  }
References v8::internal::OptimizingCompileTaskExecutor::ClearTaskState(), v8::internal::DCHECK(), DCHECK_LT, DCHECK_NULL, v8::internal::Isolate::flush_denormals(), v8::JobDelegate::GetTaskId(), v8::internal::LocalIsolate::heap(), v8::internal::TurbofanCompilationJob::isolate(), v8::internal::OptimizingCompileTaskState::isolate, v8::internal::LocalHeap::IsParked(), v8::internal::kBackground, v8::internal::OptimizingCompileTaskExecutor::NextInput(), v8::internal::OptimizingCompileTaskExecutor::NextInputIfIsolateMatches(), v8::internal::OptimizingCompileTaskExecutor::RunCompilationJob(), v8::JobDelegate::ShouldYield(), task_executor_, v8::internal::OptimizingCompileTaskExecutor::task_states_, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Member Data Documentation
task_executor_
OptimizingCompileTaskExecutor* v8::internal::OptimizingCompileTaskExecutor::CompileTask::task_executor_ [private]
Definition at line 91 of file optimizing-compile-dispatcher.cc.
Referenced by GetMaxConcurrency(), and Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler-dispatcher/optimizing-compile-dispatcher.cc