v8::bigint::FromStringAccumulator Class Reference
#include <bigint.h>
Public Types
enum class Result { kOk
, kMaxSizeExceeded
 }
Public Member Functions
FromStringAccumulator (int max_digits)
template<class CharIt >
ALWAYS_INLINE CharIt Parse (CharIt start, CharIt end, digit_t radix)
Result result ()
int ResultLength ()
template<class CharIt >
CharIt ParsePowerTwo (CharIt current, CharIt end, digit_t radix)
template<class CharIt >
CharIt Parse (CharIt start, CharIt end, digit_t radix)
Private Member Functions
template<class CharIt >
ALWAYS_INLINE CharIt ParsePowerTwo (CharIt start, CharIt end, digit_t radix)
ALWAYS_INLINE bool AddPart (digit_t multiplier, digit_t part, bool is_last)
ALWAYS_INLINE bool AddPart (digit_t part)
Private Attributes
digit_t stack_parts_ [kStackParts]
std::vector< digit_t > heap_parts_
digit_t max_multiplier_ {0}
digit_t last_multiplier_
const int max_digits_
Result result_ {Result::kOk}
int stack_parts_used_ {0}
bool inline_everything_ {false}
uint8_t radix_ {0}
Friends
class ProcessorImpl
Detailed Description
Definition at line 389 of file bigint.h.
Member Enumeration Documentation
Result
enum v8::bigint::FromStringAccumulator::Result [strong]
Enumerator
kOk
kMaxSizeExceeded
Definition at line 391 of file bigint.h.
{ kOk, kMaxSizeExceeded };
Constructor & Destructor Documentation
FromStringAccumulator()
v8::bigint::FromStringAccumulator::FromStringAccumulator (int max_digits) [inline], [explicit]
Definition at line 402 of file bigint.h.
      : max_digits_(std::max(max_digits, kStackParts)) {}
Member Function Documentation
AddPart() [1/2]
bool v8::bigint::FromStringAccumulator::AddPart (digit_t multiplier, digit_t part, bool is_last) [private]
Definition at line 564 of file bigint.h.
                                                  {
#if HAVE_TWODIGIT_T
  if (inline_everything_) {
    // Inlined version of {MultiplySingle}.
    digit_t carry = part;
    digit_t high = 0;
    for (int i = 0; i < stack_parts_used_; i++) {
      twodigit_t result = twodigit_t{stack_parts_[i]} * multiplier;
      digit_t new_high = result >> bigint::kDigitBits;
      digit_t low = static_cast<digit_t>(result);
      result = twodigit_t{low} + high + carry;
      carry = result >> bigint::kDigitBits;
      stack_parts_[i] = static_cast<digit_t>(result);
      high = new_high;
    }
    stack_parts_[stack_parts_used_++] = carry + high;
    BIGINT_H_DCHECK(stack_parts_used_ <= kStackParts);
    return true;
  }
#else
  BIGINT_H_DCHECK(!inline_everything_);
#endif
  if (is_last) {
    last_multiplier_ = multiplier;
  } else {
    BIGINT_H_DCHECK(max_multiplier_ == 0 || max_multiplier_ == multiplier);
    max_multiplier_ = multiplier;
  }
  return AddPart(part);
}
References BIGINT_H_DCHECK, v8::internal::carry, v8::internal::anonymous_namespace{json-stringifier.cc}::i, inline_everything_, v8::bigint::kDigitBits, v8::bigint::kStackParts, last_multiplier_, max_multiplier_, result(), stack_parts_, and stack_parts_used_.
Referenced by Parse(), and ParsePowerTwo().
AddPart() [2/2]
bool v8::bigint::FromStringAccumulator::AddPart (digit_t part) [private]
Definition at line 596 of file bigint.h.
                                                {
  if (stack_parts_used_ < kStackParts) {
    stack_parts_[stack_parts_used_++] = part;
    return true;
  }
  if (heap_parts_.size() == 0) {
    // Initialize heap storage. Copy the stack part to make things easier later.
    heap_parts_.reserve(kStackParts * 2);
    for (int i = 0; i < kStackParts; i++) {
      heap_parts_.push_back(stack_parts_[i]);
    }
  }
  if (static_cast<int>(heap_parts_.size()) >= max_digits_) {
    result_ = Result::kMaxSizeExceeded;
    return false;
  }
  heap_parts_.push_back(part);
  return true;
}
References heap_parts_, kMaxSizeExceeded, v8::bigint::kStackParts, max_digits_, result_, stack_parts_, and stack_parts_used_.
Parse() [1/2]
template<class CharIt >
ALWAYS_INLINE CharIt v8::bigint::FromStringAccumulator::Parse (CharIt start, CharIt end, digit_t radix)
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::ParseInternal().
Parse() [2/2]
template<class CharIt >
CharIt v8::bigint::FromStringAccumulator::Parse (CharIt start, CharIt end, digit_t radix)
Definition at line 515 of file bigint.h.
                                                                           {
  BIGINT_H_DCHECK(2 <= radix && radix <= 36);
  CharIt current = start;
#if !HAVE_BUILTIN_MUL_OVERFLOW
  const digit_t kMaxMultiplier = (~digit_t{0}) / radix;
#endif
#if HAVE_TWODIGIT_T // The inlined path requires twodigit_t availability.
  // The max supported radix is 36, and Math.log2(36) == 5.169..., so we
  // need at most 5.17 bits per char.
  static constexpr int kInlineThreshold = kStackParts * kDigitBits * 100 / 517;
  BIGINT_H_DCHECK(end >= start);
  inline_everything_ = (end - start) <= kInlineThreshold;
#endif
  if (!inline_everything_ && (radix & (radix - 1)) == 0) {
    return ParsePowerTwo(start, end, radix);
  }
  bool done = false;
  do {
    digit_t multiplier = 1;
    digit_t part = 0;
    while (true) {
      digit_t d; // Numeric value of the current character {c}.
      uint32_t c = *current;
      if (c > 127 || (d = bigint::kCharValue[c]) >= radix) {
        done = true;
        break;
      }
#if HAVE_BUILTIN_MUL_OVERFLOW
      digit_t new_multiplier;
      if (__builtin_mul_overflow(multiplier, radix, &new_multiplier)) break;
      multiplier = new_multiplier;
#else
      if (multiplier > kMaxMultiplier) break;
      multiplier *= radix;
#endif
      part = part * radix + d;
      ++current;
      if (current == end) {
        done = true;
        break;
      }
    }
    if (!AddPart(multiplier, part, done)) return current;
  } while (!done);
  return current;
}
References AddPart(), BIGINT_H_DCHECK, v8::internal::compiler::end(), inline_everything_, v8::bigint::kCharValue, v8::bigint::kDigitBits, v8::bigint::kStackParts, and ParsePowerTwo().
ParsePowerTwo() [1/2]
template<class CharIt >
CharIt v8::bigint::FromStringAccumulator::ParsePowerTwo (CharIt current, CharIt end, digit_t radix)
Definition at line 479 of file bigint.h.
                                                           {
  radix_ = static_cast<uint8_t>(radix);
  const int char_bits = kCharBits[radix >> 2];
  int bits_left;
  bool done = false;
  do {
    digit_t part = 0;
    bits_left = kDigitBits;
    while (true) {
      digit_t d; // Numeric value of the current character {c}.
      uint32_t c = *current;
      if (c > 127 || (d = bigint::kCharValue[c]) >= radix) {
        done = true;
        break;
      }
      if (bits_left < char_bits) break;
      bits_left -= char_bits;
      part = (part << char_bits) | d;
      ++current;
      if (current == end) {
        done = true;
        break;
      }
    }
    if (!AddPart(part)) return current;
  } while (!done);
  // We use the unused {last_multiplier_} field to
  // communicate how many bits are unused in the last part.
  last_multiplier_ = bits_left;
  return current;
}
References AddPart(), v8::internal::compiler::end(), v8::bigint::kCharBits, v8::bigint::kCharValue, v8::bigint::kDigitBits, last_multiplier_, and radix_.
ParsePowerTwo() [2/2]
template<class CharIt >
ALWAYS_INLINE CharIt v8::bigint::FromStringAccumulator::ParsePowerTwo (CharIt start, CharIt end, digit_t radix) [private]
Referenced by Parse().
result()
Result v8::bigint::FromStringAccumulator::result () [inline]
Definition at line 416 of file bigint.h.
{ return result_; }
References result_.
Referenced by AddPart(), and v8::internal::StringToBigIntHelper< IsolateT >::ParseInternal().
ResultLength()
int v8::bigint::FromStringAccumulator::ResultLength () [inline]
Definition at line 417 of file bigint.h.
                     {
    return std::max(stack_parts_used_, static_cast<int>(heap_parts_.size()));
  }
References heap_parts_, and stack_parts_used_.
Referenced by v8::internal::BigInt::Allocate(), v8::internal::StringToBigIntHelper< IsolateT >::DecimalString(), v8::bigint::ProcessorImpl::FromString(), and v8::bigint::ProcessorImpl::FromStringBasePowerOfTwo().
Friends And Related Function Documentation
ProcessorImpl
friend class ProcessorImpl [friend]
Definition at line 425 of file bigint.h.
Member Data Documentation
heap_parts_
std::vector<digit_t> v8::bigint::FromStringAccumulator::heap_parts_ [private]
Definition at line 434 of file bigint.h.
Referenced by AddPart(), v8::bigint::ProcessorImpl::FromStringBasePowerOfTwo(), v8::bigint::ProcessorImpl::FromStringClassic(), v8::bigint::ProcessorImpl::FromStringLarge(), and ResultLength().
inline_everything_
bool v8::bigint::FromStringAccumulator::inline_everything_ {false} [private]
Definition at line 440 of file bigint.h.
Referenced by AddPart(), v8::bigint::ProcessorImpl::FromString(), and Parse().
last_multiplier_
digit_t v8::bigint::FromStringAccumulator::last_multiplier_ [private]
Definition at line 436 of file bigint.h.
Referenced by AddPart(), v8::bigint::ProcessorImpl::FromStringBasePowerOfTwo(), v8::bigint::ProcessorImpl::FromStringClassic(), v8::bigint::ProcessorImpl::FromStringLarge(), and ParsePowerTwo().
max_digits_
const int v8::bigint::FromStringAccumulator::max_digits_ [private]
Definition at line 437 of file bigint.h.
Referenced by AddPart().
max_multiplier_
digit_t v8::bigint::FromStringAccumulator::max_multiplier_ {0} [private]
Definition at line 435 of file bigint.h.
Referenced by AddPart(), v8::bigint::ProcessorImpl::FromStringClassic(), and v8::bigint::ProcessorImpl::FromStringLarge().
radix_
uint8_t v8::bigint::FromStringAccumulator::radix_ {0} [private]
Definition at line 441 of file bigint.h.
Referenced by v8::bigint::ProcessorImpl::FromString(), v8::bigint::ProcessorImpl::FromStringBasePowerOfTwo(), and ParsePowerTwo().
result_
Result v8::bigint::FromStringAccumulator::result_ {Result::kOk} [private]
Definition at line 438 of file bigint.h.
Referenced by AddPart(), and result().
stack_parts_
digit_t v8::bigint::FromStringAccumulator::stack_parts_[kStackParts] [private]
Definition at line 433 of file bigint.h.
Referenced by AddPart(), v8::bigint::ProcessorImpl::FromString(), v8::bigint::ProcessorImpl::FromStringBasePowerOfTwo(), and v8::bigint::ProcessorImpl::FromStringClassic().
stack_parts_used_
int v8::bigint::FromStringAccumulator::stack_parts_used_ {0} [private]
Definition at line 439 of file bigint.h.
Referenced by AddPart(), v8::bigint::ProcessorImpl::FromString(), v8::bigint::ProcessorImpl::FromStringClassic(), and ResultLength().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/bigint/bigint.h