v8::internal::ExpressionParsingScope< Types > Class Template Reference
#include <expression-scope.h>
Public Types
using ParserT = typename Types::Impl
using ExpressionT = typename Types::Expression
using ExpressionScopeT = ExpressionScope< Types >
using ScopeType = typename ExpressionScopeT::ScopeType
Public Member Functions
ExpressionParsingScope (ParserT *parser, ScopeType type=ExpressionScopeT::kExpression)
ExpressionParsingScope (const ExpressionParsingScope &)=delete
ExpressionParsingScope & operator= (const ExpressionParsingScope &)=delete
void RecordAsyncArrowParametersError (const Scanner::Location &loc, MessageTemplate message)
~ExpressionParsingScope ()
ExpressionT ValidateAndRewriteReference (ExpressionT expression, int beg_pos, int end_pos)
void RecordExpressionError (const Scanner::Location &loc, MessageTemplate message)
void RecordPatternError (const Scanner::Location &loc, MessageTemplate message)
void ValidateExpression ()
void ValidatePattern (ExpressionT expression, int begin, int end)
void ClearExpressionError ()
void ClearPatternError ()
void TrackVariable (VariableProxy *variable)
void MarkIdentifierAsAssigned ()
int SetInitializers (int first_variable_index, int position)
ScopedList< std::pair< VariableProxy *, int > > * variable_list ()
Protected Member Functions
bool is_verified () const
void ValidatePattern ()
Private Types
enum ErrorNumber : uint8_t { kExpressionIndex = 0
, kPatternIndex = 1
, kNumberOfErrors = 2
 }
Private Member Functions
void clear (int index)
bool is_valid (int index) const
void Record (int index, const Scanner::Location &loc, MessageTemplate message)
void Validate (int index)
void Report (int index) const
void mark_verified ()
void clear_verified ()
Private Attributes
ScopedList< std::pair< VariableProxy *, int > > variable_list_
MessageTemplate messages_ [kNumberOfErrors]
Scanner::Location locations_ [kNumberOfErrors]
bool has_async_arrow_in_scope_chain_
Friends
class AccumulationScope< Types >
Additional Inherited Members
Detailed Description
template<typename Types>
class v8::internal::ExpressionParsingScope< Types >
Definition at line 469 of file expression-scope.h.
Member Typedef Documentation
ExpressionScopeT
template<typename Types >
using v8::internal::ExpressionParsingScope< Types >::ExpressionScopeT = ExpressionScope<Types>
Definition at line 473 of file expression-scope.h.
ExpressionT
template<typename Types >
using v8::internal::ExpressionParsingScope< Types >::ExpressionT = typename Types::Expression
Definition at line 472 of file expression-scope.h.
ParserT
template<typename Types >
using v8::internal::ExpressionParsingScope< Types >::ParserT = typename Types::Impl
Definition at line 471 of file expression-scope.h.
ScopeType
template<typename Types >
using v8::internal::ExpressionParsingScope< Types >::ScopeType = typename ExpressionScopeT::ScopeType
Definition at line 474 of file expression-scope.h.
Member Enumeration Documentation
ErrorNumber
template<typename Types >
enum v8::internal::ExpressionParsingScope::ErrorNumber : uint8_t [private]
Enumerator
kExpressionIndex
kPatternIndex
kNumberOfErrors
Definition at line 612 of file expression-scope.h.
                   : uint8_t {
    kExpressionIndex = 0,
    kPatternIndex = 1,
    kNumberOfErrors = 2,
  };
Constructor & Destructor Documentation
ExpressionParsingScope() [1/2]
template<typename Types >
v8::internal::ExpressionParsingScope< Types >::ExpressionParsingScope (ParserT * parser, ScopeType type = ExpressionScopeT::kExpression) [inline], [explicit]
Definition at line 476 of file expression-scope.h.
      : ExpressionScopeT(parser, type),
        variable_list_(parser->variable_buffer()),
        has_async_arrow_in_scope_chain_(
            type == ExpressionScopeT::kMaybeAsyncArrowParameterDeclaration ||
            (this->parent() && this->parent()->CanBeExpression() &&
             this->parent()
                 ->AsExpressionParsingScope()
                 ->has_async_arrow_in_scope_chain_)) {
    DCHECK(this->CanBeExpression());
    clear(kExpressionIndex);
    clear(kPatternIndex);
  }
References v8::internal::ExpressionScope< Types >::CanBeExpression(), v8::internal::ExpressionParsingScope< Types >::clear(), v8::internal::DCHECK(), v8::internal::ExpressionParsingScope< Types >::kExpressionIndex, and v8::internal::ExpressionParsingScope< Types >::kPatternIndex.
ExpressionParsingScope() [2/2]
template<typename Types >
v8::internal::ExpressionParsingScope< Types >::ExpressionParsingScope (const ExpressionParsingScope< Types > &) [delete]
 ExpressionParsingScope()
template<typename Types >
v8::internal::ExpressionParsingScope< Types >::~ExpressionParsingScope () [inline]
Definition at line 506 of file expression-scope.h.
{ DCHECK(this->has_error() || verified_); }
References v8::internal::DCHECK().
Member Function Documentation
clear()
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::clear (int index) [inline], [private]
Definition at line 617 of file expression-scope.h.
                        {
    messages_[index] = MessageTemplate::kNone;
    locations_[index] = Scanner::Location::invalid();
  }
References v8::internal::index, v8::internal::Scanner::Location::invalid(), v8::internal::ExpressionParsingScope< Types >::locations_, and v8::internal::ExpressionParsingScope< Types >::messages_.
Referenced by v8::internal::ExpressionParsingScope< Types >::ClearExpressionError(), v8::internal::ExpressionParsingScope< Types >::ClearPatternError(), and v8::internal::ExpressionParsingScope< Types >::ExpressionParsingScope().
clear_verified()
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::clear_verified () [inline], [private]
Definition at line 644 of file expression-scope.h.
                        {
#ifdef DEBUG
    verified_ = false;
#endif
  }
ClearExpressionError()
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::ClearExpressionError () [inline]
Definition at line 548 of file expression-scope.h.
                              {
    DCHECK(verified_);
#ifdef DEBUG
    verified_ = false;
#endif
    clear(kExpressionIndex);
  }
References v8::internal::ExpressionParsingScope< Types >::clear(), v8::internal::DCHECK(), and v8::internal::ExpressionParsingScope< Types >::kExpressionIndex.
ClearPatternError()
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::ClearPatternError () [inline]
Definition at line 556 of file expression-scope.h.
                           {
    DCHECK(verified_);
#ifdef DEBUG
    verified_ = false;
#endif
    clear(kPatternIndex);
  }
References v8::internal::ExpressionParsingScope< Types >::clear(), v8::internal::DCHECK(), and v8::internal::ExpressionParsingScope< Types >::kPatternIndex.
is_valid()
template<typename Types >
bool v8::internal::ExpressionParsingScope< Types >::is_valid (int index) const [inline], [private]
Definition at line 621 of file expression-scope.h.
{ return !locations_[index].IsValid(); }
References v8::internal::index, v8::internal::Scanner::Location::IsValid(), and v8::internal::ExpressionParsingScope< Types >::locations_.
Referenced by v8::internal::ExpressionParsingScope< Types >::Record(), and v8::internal::ExpressionParsingScope< Types >::Validate().
is_verified()
template<typename Types >
bool v8::internal::ExpressionParsingScope< Types >::is_verified () const [inline], [protected]
Definition at line 599 of file expression-scope.h.
                           {
#ifdef DEBUG
    return verified_;
#else
    return false;
#endif
  }
Referenced by v8::internal::ExpressionParsingScope< Types >::Validate(), and v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope().
mark_verified()
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::mark_verified () [inline], [private]
Definition at line 639 of file expression-scope.h.
                       {
#ifdef DEBUG
    verified_ = true;
#endif
  }
Referenced by v8::internal::ExpressionParsingScope< Types >::Validate(), and v8::internal::ExpressionParsingScope< Types >::ValidateAndRewriteReference().
MarkIdentifierAsAssigned()
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::MarkIdentifierAsAssigned () [inline]
Definition at line 571 of file expression-scope.h.
                                  {
    // It's possible we're parsing a syntax error. In that case it's not
    // guaranteed that there's a variable in the list.
    if (variable_list_.length() == 0) return;
    variable_list_.at(variable_list_.length() - 1).first->set_is_assigned();
  }
References v8::internal::ExpressionParsingScope< Types >::variable_list_.
Referenced by v8::internal::ExpressionParsingScope< Types >::ValidateAndRewriteReference().
operator=()
template<typename Types >
ExpressionParsingScope& v8::internal::ExpressionParsingScope< Types >::operator= (const ExpressionParsingScope< Types > &) [delete]
Record()
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::Record (int index, const Scanner::Location & loc, MessageTemplate message) [inline], [private]
Definition at line 622 of file expression-scope.h.
                                       {
    DCHECK_IMPLIES(!this->has_error(), loc.IsValid());
    if (!is_valid(index)) return;
    messages_[index] = message;
    locations_[index] = loc;
  }
References DCHECK_IMPLIES, v8::internal::index, v8::internal::ExpressionParsingScope< Types >::is_valid(), v8::internal::loc, v8::internal::ExpressionParsingScope< Types >::locations_, and v8::internal::ExpressionParsingScope< Types >::messages_.
Referenced by v8::internal::ExpressionParsingScope< Types >::RecordExpressionError(), and v8::internal::ExpressionParsingScope< Types >::RecordPatternError().
RecordAsyncArrowParametersError()
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::RecordAsyncArrowParametersError (const Scanner::Location & loc, MessageTemplate message) [inline]
Definition at line 494 of file expression-scope.h.
                                                                {
    for (ExpressionScopeT* scope = this; scope != nullptr;
         scope = scope->parent()) {
      if (!has_async_arrow_in_scope_chain_) break;
      if (scope->type_ ==
          ExpressionScopeT::kMaybeAsyncArrowParameterDeclaration) {
        scope->AsArrowHeadParsingScope()->RecordDeclarationError(loc, message);
      }
    }
  }
References v8::internal::ExpressionParsingScope< Types >::has_async_arrow_in_scope_chain_, v8::internal::ExpressionScope< Types >::kMaybeAsyncArrowParameterDeclaration, v8::internal::loc, and v8::internal::ExpressionScope< Types >::parent().
RecordExpressionError()
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::RecordExpressionError (const Scanner::Location & loc, MessageTemplate message) [inline]
Definition at line 525 of file expression-scope.h.
                                                      {
    Record(kExpressionIndex, loc, message);
  }
References v8::internal::ExpressionParsingScope< Types >::kExpressionIndex, v8::internal::loc, and v8::internal::ExpressionParsingScope< Types >::Record().
RecordPatternError()
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::RecordPatternError (const Scanner::Location & loc, MessageTemplate message) [inline]
Definition at line 530 of file expression-scope.h.
                                                   {
    Record(kPatternIndex, loc, message);
  }
References v8::internal::ExpressionParsingScope< Types >::kPatternIndex, v8::internal::loc, and v8::internal::ExpressionParsingScope< Types >::Record().
Report()
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::Report (int index) const [inline], [private]
Definition at line 634 of file expression-scope.h.
                               {
    ExpressionScopeT::Report(locations_[index], messages_[index]);
  }
References v8::internal::index, v8::internal::ExpressionParsingScope< Types >::locations_, v8::internal::ExpressionParsingScope< Types >::messages_, and v8::internal::ExpressionScope< Types >::Report().
Referenced by v8::internal::ExpressionParsingScope< Types >::Validate().
SetInitializers()
template<typename Types >
int v8::internal::ExpressionParsingScope< Types >::SetInitializers (int first_variable_index, int position) [inline]
Definition at line 578 of file expression-scope.h.
                                                              {
    int len = variable_list_.length();
    if (len == 0) return 0;
    int end = len - 1;
    // Loop backwards and abort as soon as we see one that's already set to
    // avoid a loop on expressions like a,b,c,d,e,f,g (outside of an arrowhead).
    // TODO(delphick): Look into removing this loop.
    for (int i = end; i >= first_variable_index &&
                      variable_list_.at(i).second == kNoSourcePosition;
         --i) {
      variable_list_.at(i).second = position;
    }
    return end;
  }
References v8::internal::compiler::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kNoSourcePosition, and v8::internal::ExpressionParsingScope< Types >::variable_list_.
TrackVariable()
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::TrackVariable (VariableProxy * variable) [inline]
Definition at line 564 of file expression-scope.h.
                                              {
    if (!this->CanBeDeclaration()) {
      this->parser()->scope()->AddUnresolved(variable);
    }
    variable_list_.Add({variable, kNoSourcePosition});
  }
References v8::internal::ExpressionScope< Types >::CanBeDeclaration(), v8::internal::kNoSourcePosition, v8::internal::ExpressionScope< Types >::parser(), and v8::internal::ExpressionParsingScope< Types >::variable_list_.
Validate()
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::Validate (int index) [inline], [private]
Definition at line 629 of file expression-scope.h.
                           {
    DCHECK(!this->is_verified());
    if (!is_valid(index)) Report(index);
    this->mark_verified();
  }
References v8::internal::DCHECK(), v8::internal::index, v8::internal::ExpressionParsingScope< Types >::is_valid(), v8::internal::ExpressionParsingScope< Types >::is_verified(), v8::internal::ExpressionParsingScope< Types >::mark_verified(), and v8::internal::ExpressionParsingScope< Types >::Report().
Referenced by v8::internal::ExpressionParsingScope< Types >::ValidateExpression(), and v8::internal::ExpressionParsingScope< Types >::ValidatePattern().
ValidateAndRewriteReference()
template<typename Types >
ExpressionT v8::internal::ExpressionParsingScope< Types >::ValidateAndRewriteReference (ExpressionT expression, int beg_pos, int end_pos) [inline]
Definition at line 508 of file expression-scope.h.
                                                       {
    if (V8_LIKELY(this->parser()->IsAssignableIdentifier(expression))) {
      MarkIdentifierAsAssigned();
      this->mark_verified();
      return expression;
    } else if (V8_LIKELY(expression->IsProperty())) {
      ValidateExpression();
      return expression;
    }
    this->mark_verified();
    const bool early_error = false;
    return this->parser()->RewriteInvalidReferenceExpression(
        expression, beg_pos, end_pos, MessageTemplate::kInvalidLhsInFor,
        early_error);
  }
References v8::internal::ExpressionParsingScope< Types >::mark_verified(), v8::internal::ExpressionParsingScope< Types >::MarkIdentifierAsAssigned(), v8::internal::ExpressionScope< Types >::parser(), V8_LIKELY, and v8::internal::ExpressionParsingScope< Types >::ValidateExpression().
ValidateExpression()
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::ValidateExpression () [inline]
Definition at line 535 of file expression-scope.h.
{ Validate(kExpressionIndex); }
References v8::internal::ExpressionParsingScope< Types >::kExpressionIndex, and v8::internal::ExpressionParsingScope< Types >::Validate().
Referenced by v8::internal::Parser::ParseClassForMemberInitialization(), v8::internal::ExpressionParsingScope< Types >::ValidateAndRewriteReference(), and v8::internal::ArrowHeadParsingScope< Types >::ValidateExpression().
ValidatePattern() [1/2]
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::ValidatePattern () [inline], [protected]
Definition at line 607 of file expression-scope.h.
{ Validate(kPatternIndex); }
Referenced by v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope().
ValidatePattern() [2/2]
template<typename Types >
void v8::internal::ExpressionParsingScope< Types >::ValidatePattern (ExpressionT expression, int begin, int end) [inline]
Definition at line 537 of file expression-scope.h.
                                                                   {
    Validate(kPatternIndex);
    if (expression->is_parenthesized()) {
      ExpressionScopeT::Report(Scanner::Location(begin, end),
                               MessageTemplate::kInvalidDestructuringTarget);
    }
    for (auto& variable_initializer_pair : variable_list_) {
      variable_initializer_pair.first->set_is_assigned();
    }
  }
References v8::internal::compiler::begin(), v8::internal::compiler::end(), v8::internal::ExpressionParsingScope< Types >::kPatternIndex, v8::internal::ExpressionScope< Types >::Report(), v8::internal::ExpressionParsingScope< Types >::Validate(), and v8::internal::ExpressionParsingScope< Types >::variable_list_.
variable_list()
template<typename Types >
ScopedList<std::pair<VariableProxy*, int> >* v8::internal::ExpressionParsingScope< Types >::variable_list () [inline]
Definition at line 594 of file expression-scope.h.
                                                            {
    return &variable_list_;
  }
References v8::internal::ExpressionParsingScope< Types >::variable_list_.
Referenced by v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope(), and v8::internal::ArrowHeadParsingScope< Types >::ValidateExpression().
Friends And Related Function Documentation
AccumulationScope< Types >
template<typename Types >
friend class AccumulationScope< Types > [friend]
Definition at line 607 of file expression-scope.h.
Member Data Documentation
has_async_arrow_in_scope_chain_
template<typename Types >
bool v8::internal::ExpressionParsingScope< Types >::has_async_arrow_in_scope_chain_ [private]
Definition at line 656 of file expression-scope.h.
Referenced by v8::internal::ExpressionParsingScope< Types >::RecordAsyncArrowParametersError().
locations_
template<typename Types >
Scanner::Location v8::internal::ExpressionParsingScope< Types >::locations_[kNumberOfErrors] [private]
Definition at line 655 of file expression-scope.h.
Referenced by v8::internal::ExpressionParsingScope< Types >::clear(), v8::internal::ExpressionParsingScope< Types >::is_valid(), v8::internal::ExpressionParsingScope< Types >::Record(), and v8::internal::ExpressionParsingScope< Types >::Report().
messages_
template<typename Types >
MessageTemplate v8::internal::ExpressionParsingScope< Types >::messages_[kNumberOfErrors] [private]
Definition at line 654 of file expression-scope.h.
Referenced by v8::internal::ExpressionParsingScope< Types >::clear(), v8::internal::ExpressionParsingScope< Types >::Record(), and v8::internal::ExpressionParsingScope< Types >::Report().
variable_list_
template<typename Types >
ScopedList<std::pair<VariableProxy*, int> > v8::internal::ExpressionParsingScope< Types >::variable_list_ [private]
Definition at line 653 of file expression-scope.h.
Referenced by v8::internal::ExpressionParsingScope< Types >::MarkIdentifierAsAssigned(), v8::internal::ExpressionParsingScope< Types >::SetInitializers(), v8::internal::ExpressionParsingScope< Types >::TrackVariable(), v8::internal::ExpressionParsingScope< Types >::ValidatePattern(), and v8::internal::ExpressionParsingScope< Types >::variable_list().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/expression-scope.h