v8::internal::CpuTraceMarkExtension Class Reference
#include <cputracemark-extension.h>
Public Member Functions
CpuTraceMarkExtension (const char *fun_name)
v8::Local< v8::FunctionTemplate > GetNativeFunctionTemplate (v8::Isolate *isolate, v8::Local< v8::String > name) override
Static Private Member Functions
static void Mark (const v8::FunctionCallbackInfo< v8::Value > &info)
static const char * BuildSource (char *buf, size_t size, const char *fun_name)
Private Attributes
char buffer_ [50]
Detailed Description
Definition at line 18 of file cputracemark-extension.h.
Constructor & Destructor Documentation
CpuTraceMarkExtension()
v8::internal::CpuTraceMarkExtension::CpuTraceMarkExtension (const char * fun_name) [inline], [explicit]
Definition at line 20 of file cputracemark-extension.h.
      : v8::Extension("v8/cpumark",
                      BuildSource(buffer_, sizeof(buffer_), fun_name)) {}
Member Function Documentation
BuildSource()
static const char* v8::internal::CpuTraceMarkExtension::BuildSource (char * buf, size_t size, const char * fun_name) [inline], [static], [private]
Definition at line 30 of file cputracemark-extension.h.
                                                                               {
    base::SNPrintF(base::VectorOf(buf, size), "native function %s();",
                   fun_name);
    return buf;
  }
References size(), v8::base::SNPrintF(), and v8::base::VectorOf().
GetNativeFunctionTemplate()
v8::Local< v8::FunctionTemplate > v8::internal::CpuTraceMarkExtension::GetNativeFunctionTemplate (v8::Isolate * isolate, v8::Local< v8::String > name) [override], [virtual]
Reimplemented from v8::Extension.
Definition at line 15 of file cputracemark-extension.cc.
                                                                        {
  return v8::FunctionTemplate::New(isolate, CpuTraceMarkExtension::Mark);
}
References Mark(), and v8::FunctionTemplate::New().
Mark()
void v8::internal::CpuTraceMarkExtension::Mark (const v8::FunctionCallbackInfo< v8::Value > & info) [static], [private]
Definition at line 20 of file cputracemark-extension.cc.
                                                 {
  DCHECK(ValidateCallbackInfo(info));
  if (info.Length() < 1 || !info[0]->IsUint32()) {
    info.GetIsolate()->ThrowError(
        "First parameter to cputracemark() must be a unsigned int32.");
    return;
  }
#if V8_HOST_ARCH_IA32 || V8_HOST_ARCH_X64
#if defined(__clang__)
  // for non msvc build
  uint32_t param =
      info[0]->Uint32Value(info.GetIsolate()->GetCurrentContext()).ToChecked();
  int magic_dummy;
#if defined(__i386__) && defined(__pic__)
  __asm__ __volatile__("push %%ebx; cpuid; pop %%ebx"
                       : "=a"(magic_dummy)
                       : "a"(0x4711 | (param << 16))
                       : "ecx", "edx");
#else
  __asm__ __volatile__("cpuid"
                       : "=a"(magic_dummy)
                       : "a"(0x4711 | (param << 16))
                       : "ecx", "edx", "ebx");
#endif // defined(__i386__) && defined(__pic__)
#else
  // no msvc build support yet.
#endif //! V8_LIBC_MSVCRT
#endif // V8_HOST_ARCH_IA32 || V8_HOST_ARCH_X64
}
References v8::internal::DCHECK(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::Length(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
Referenced by GetNativeFunctionTemplate().
Member Data Documentation
buffer_
char v8::internal::CpuTraceMarkExtension::buffer_[50] [private]
Definition at line 36 of file cputracemark-extension.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/extensions/cputracemark-extension.h
/mnt/V8SourceCode/src/extensions/cputracemark-extension.cc