v8::internal::compiler::RelocatablePtrConstantInfo Class Reference
#include <common-operator.h>
Public Types
enum Type { kInt32
, kInt64
 }
Public Member Functions
RelocatablePtrConstantInfo (int32_t value, RelocInfo::Mode rmode)
RelocatablePtrConstantInfo (int64_t value, RelocInfo::Mode rmode)
intptr_t value () const
RelocInfo::Mode rmode () const
Type type () const
Private Attributes
intptr_t value_
RelocInfo::Mode rmode_
Type type_
Detailed Description
Definition at line 247 of file common-operator.h.
Member Enumeration Documentation
Type
enum v8::internal::compiler::RelocatablePtrConstantInfo::Type
Enumerator
kInt32
kInt64
Definition at line 249 of file common-operator.h.
{ kInt32, kInt64 };
Constructor & Destructor Documentation
RelocatablePtrConstantInfo() [1/2]
v8::internal::compiler::RelocatablePtrConstantInfo::RelocatablePtrConstantInfo (int32_t value, RelocInfo::Mode rmode) [inline]
Definition at line 251 of file common-operator.h.
      : value_(value), rmode_(rmode), type_(kInt32) {}
RelocatablePtrConstantInfo() [2/2]
v8::internal::compiler::RelocatablePtrConstantInfo::RelocatablePtrConstantInfo (int64_t value, RelocInfo::Mode rmode) [inline]
Definition at line 253 of file common-operator.h.
      : value_(value), rmode_(rmode), type_(kInt64) {}
Member Function Documentation
rmode()
RelocInfo::Mode v8::internal::compiler::RelocatablePtrConstantInfo::rmode () const [inline]
Definition at line 257 of file common-operator.h.
{ return rmode_; }
References rmode_.
Referenced by v8::internal::compiler::Constant::Constant(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
type()
Type v8::internal::compiler::RelocatablePtrConstantInfo::type () const [inline]
Definition at line 258 of file common-operator.h.
{ return type_; }
References type_.
Referenced by v8::internal::compiler::Constant::Constant(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
value()
intptr_t v8::internal::compiler::RelocatablePtrConstantInfo::value () const [inline]
Definition at line 256 of file common-operator.h.
{ return value_; }
References value_.
Referenced by v8::internal::compiler::Constant::Constant(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
Member Data Documentation
rmode_
RelocInfo::Mode v8::internal::compiler::RelocatablePtrConstantInfo::rmode_ [private]
Definition at line 262 of file common-operator.h.
Referenced by rmode().
type_
Type v8::internal::compiler::RelocatablePtrConstantInfo::type_ [private]
Definition at line 263 of file common-operator.h.
Referenced by type().
value_
intptr_t v8::internal::compiler::RelocatablePtrConstantInfo::value_ [private]
Definition at line 261 of file common-operator.h.
Referenced by value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/common-operator.h