v8::internal::Histogram Class Reference
#include <counters.h>
Public Member Functions
V8_EXPORT_PRIVATE void AddSample (int sample)
bool Enabled ()
const char * name () const
int min () const
int max () const
int num_buckets () const
void AssertReportsToCounters (Counters *expected_counters)
Protected Member Functions
Histogram ()=default
Histogram (const Histogram &)=delete
Histogram & operator= (const Histogram &)=delete
void Initialize (const char *name, int min, int max, int num_buckets, Counters *counters)
Counters * counters () const
void Reset ()
void EnsureCreated (bool create_new=true)
Private Member Functions
V8_EXPORT_PRIVATE void * CreateHistogram () const
Private Attributes
const char * name_
int min_
int max_
int num_buckets_
std::atomic< void * > histogram_
Counters * counters_
base::Mutex mutex_
Friends
class Counters
class CountersInitializer
class HistogramResetter
Detailed Description
Definition at line 158 of file counters.h.
Constructor & Destructor Documentation
Histogram() [1/2]
v8::internal::Histogram::Histogram () [protected], [default]
Histogram() [2/2]
v8::internal::Histogram::Histogram (const Histogram &) [protected], [delete]
Member Function Documentation
AddSample()
void v8::internal::Histogram::AddSample (int sample)
Definition at line 50 of file counters.cc.
                                    {
  if (Enabled()) {
    counters_->AddHistogramSample(histogram_, sample);
  }
}
References v8::internal::Counters::AddHistogramSample(), counters_, Enabled(), and histogram_.
Referenced by v8::internal::wasm::WasmEngine::AddIsolate(), v8::internal::wasm::WasmExecutionTimer::AddSample(), v8::internal::TimedHistogram::AddTimedSample(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationTimeCallback::call(), v8::internal::wasm::WasmInterpreter::CodeMap::Preprocess(), v8::internal::TimedHistogram::RecordAbandon(), v8::internal::wasm::NativeModule::SampleCodeSize(), v8::internal::AggregatableHistogramTimer::Stop(), and v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::~ScriptCompileTimerScope().
AssertReportsToCounters()
void v8::internal::Histogram::AssertReportsToCounters (Counters * expected_counters) [inline]
Definition at line 174 of file counters.h.
                                                            {
    DCHECK_EQ(counters_, expected_counters);
  }
References counters_, and DCHECK_EQ.
counters()
Counters* v8::internal::Histogram::counters () const [inline], [protected]
Definition at line 194 of file counters.h.
{ return counters_; }
References counters_.
Referenced by Initialize(), v8::internal::TimedHistogram::Initialize(), v8::internal::NestedTimedHistogram::NestedTimedHistogram(), v8::internal::wasm::WasmInterpreter::CodeMap::Preprocess(), and v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::~ScriptCompileTimerScope().
CreateHistogram()
void * v8::internal::Histogram::CreateHistogram () const [private]
Definition at line 56 of file counters.cc.
                                       {
  return counters_->CreateHistogram(name_, min_, max_, num_buckets_);
}
References counters_, v8::internal::Counters::CreateHistogram(), max_, min_, name_, and num_buckets_.
Referenced by EnsureCreated().
Enabled()
bool v8::internal::Histogram::Enabled () [inline]
Definition at line 164 of file counters.h.
{ return histogram_ != nullptr; }
References histogram_.
Referenced by v8::internal::wasm::WasmEngine::AddIsolate(), AddSample(), v8::internal::TimedHistogram::AddTimedSample(), v8::internal::TimedHistogram::RecordAbandon(), v8::internal::wasm::NativeModule::SampleCodeSize(), v8::internal::LazyTimedHistogramScope::set_histogram(), v8::internal::BaseTimedHistogramScope::Start(), v8::internal::wasm::WasmExecutionTimer::Start(), v8::internal::BaseTimedHistogramScope::Stop(), v8::internal::wasm::WasmExecutionTimer::Stop(), v8::internal::TimedHistogram::Stop(), and v8::internal::wasm::WasmExecutionTimer::Terminate().
EnsureCreated()
void v8::internal::Histogram::EnsureCreated (bool create_new = true) [inline], [protected]
Definition at line 201 of file counters.h.
                                             {
    if (create_new && histogram_.load(std::memory_order_acquire) == nullptr) {
      base::MutexGuard Guard(&mutex_);
      if (histogram_.load(std::memory_order_relaxed) == nullptr)
        histogram_.store(CreateHistogram(), std::memory_order_release);
    }
  }
References CreateHistogram(), histogram_, and mutex_.
Initialize()
void v8::internal::Histogram::Initialize (const char * name, int min, int max, int num_buckets, Counters * counters) [inline], [protected]
Definition at line 183 of file counters.h.
                                      {
    name_ = name;
    min_ = min;
    max_ = max;
    num_buckets_ = num_buckets;
    histogram_ = nullptr;
    counters_ = counters;
    DCHECK_NOT_NULL(counters_);
  }
References counters(), counters_, DCHECK_NOT_NULL, histogram_, max(), max_, min(), min_, name(), name_, num_buckets(), and num_buckets_.
Referenced by v8::internal::TimedHistogram::Initialize(), and v8::internal::CountersInitializer::Visit().
max()
int v8::internal::Histogram::max () const [inline]
Definition at line 169 of file counters.h.
{ return max_; }
References max_.
Referenced by Initialize(), v8::internal::TimedHistogram::Initialize(), v8::internal::NestedTimedHistogram::NestedTimedHistogram(), and v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::~ScriptCompileTimerScope().
min()
int v8::internal::Histogram::min () const [inline]
Definition at line 168 of file counters.h.
{ return min_; }
References min_.
Referenced by Initialize(), v8::internal::TimedHistogram::Initialize(), v8::internal::NestedTimedHistogram::NestedTimedHistogram(), and v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::~ScriptCompileTimerScope().
name()
const char* v8::internal::Histogram::name () const [inline]
Definition at line 166 of file counters.h.
{ return name_; }
References name_.
Referenced by Initialize(), v8::internal::TimedHistogram::Initialize(), v8::internal::BaseTimedHistogramScope::LogEnd(), v8::internal::BaseTimedHistogramScope::LogStart(), v8::internal::NestedTimedHistogram::NestedTimedHistogram(), and v8::internal::TimedHistogram::RecordAbandon().
num_buckets()
int v8::internal::Histogram::num_buckets () const [inline]
Definition at line 170 of file counters.h.
{ return num_buckets_; }
References num_buckets_.
Referenced by Initialize(), v8::internal::TimedHistogram::Initialize(), v8::internal::NestedTimedHistogram::NestedTimedHistogram(), and v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::~ScriptCompileTimerScope().
operator=()
Histogram& v8::internal::Histogram::operator= (const Histogram &) [protected], [delete]
Reset()
void v8::internal::Histogram::Reset () [inline], [protected]
Definition at line 198 of file counters.h.
{ histogram_ = nullptr; }
References histogram_.
Referenced by v8::internal::HistogramResetter::VisitHistogram().
Friends And Related Function Documentation
Counters
friend class Counters [friend]
Definition at line 210 of file counters.h.
CountersInitializer
friend class CountersInitializer [friend]
Definition at line 211 of file counters.h.
HistogramResetter
friend class HistogramResetter [friend]
Definition at line 212 of file counters.h.
Member Data Documentation
counters_
Counters* v8::internal::Histogram::counters_ [private]
Definition at line 221 of file counters.h.
Referenced by AddSample(), AssertReportsToCounters(), counters(), CreateHistogram(), and Initialize().
histogram_
std::atomic<void*> v8::internal::Histogram::histogram_ [private]
Definition at line 220 of file counters.h.
Referenced by AddSample(), Enabled(), EnsureCreated(), Initialize(), and Reset().
max_
int v8::internal::Histogram::max_ [private]
Definition at line 218 of file counters.h.
Referenced by CreateHistogram(), Initialize(), and max().
min_
int v8::internal::Histogram::min_ [private]
Definition at line 217 of file counters.h.
Referenced by CreateHistogram(), Initialize(), and min().
mutex_
base::Mutex v8::internal::Histogram::mutex_ [private]
Definition at line 222 of file counters.h.
Referenced by EnsureCreated().
name_
const char* v8::internal::Histogram::name_ [private]
Definition at line 216 of file counters.h.
Referenced by CreateHistogram(), Initialize(), and name().
num_buckets_
int v8::internal::Histogram::num_buckets_ [private]
Definition at line 219 of file counters.h.
Referenced by CreateHistogram(), Initialize(), and num_buckets().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/logging/counters.h
/mnt/V8SourceCode/src/logging/counters.cc