v8::internal::maglev::SweepIdentityNodes Class Reference
#include <maglev-post-hoc-optimizations-processors.h>
Public Member Functions
void PreProcessGraph (Graph *graph)
void PostProcessGraph (Graph *graph)
void PostProcessBasicBlock (BasicBlock *block)
BlockProcessResult PreProcessBasicBlock (BasicBlock *block)
void PostPhiProcessing ()
ProcessResult Process (NodeBase *node, const ProcessingState &state)
Detailed Description
Definition at line 21 of file maglev-post-hoc-optimizations-processors.h.
Member Function Documentation
PostPhiProcessing()
void v8::internal::maglev::SweepIdentityNodes::PostPhiProcessing () [inline]
Definition at line 29 of file maglev-post-hoc-optimizations-processors.h.
{}
PostProcessBasicBlock()
void v8::internal::maglev::SweepIdentityNodes::PostProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 25 of file maglev-post-hoc-optimizations-processors.h.
{}
PostProcessGraph()
void v8::internal::maglev::SweepIdentityNodes::PostProcessGraph (Graph * graph) [inline]
Definition at line 24 of file maglev-post-hoc-optimizations-processors.h.
{}
PreProcessBasicBlock()
BlockProcessResult v8::internal::maglev::SweepIdentityNodes::PreProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 26 of file maglev-post-hoc-optimizations-processors.h.
                                                             {
    return BlockProcessResult::kContinue;
  }
References v8::internal::maglev::kContinue.
PreProcessGraph()
void v8::internal::maglev::SweepIdentityNodes::PreProcessGraph (Graph * graph) [inline]
Definition at line 23 of file maglev-post-hoc-optimizations-processors.h.
{}
Process()
ProcessResult v8::internal::maglev::SweepIdentityNodes::Process (NodeBase * node, const ProcessingState & state) [inline]
Definition at line 30 of file maglev-post-hoc-optimizations-processors.h.
                                                                      {
    for (int i = 0; i < node->input_count(); i++) {
      Input& input = node->input(i);
      while (input.node() && input.node()->Is<Identity>()) {
        node->change_input(i, input.node()->input(0).node());
      }
    }
    // While visiting the deopt info, the iterator will clear the identity nodes
    // automatically.
    if (node->properties().can_lazy_deopt()) {
      node->lazy_deopt_info()->ForEachInput([&](ValueNode* node) {});
    }
    if (node->properties().can_eager_deopt()) {
      node->eager_deopt_info()->ForEachInput([&](ValueNode* node) {});
    }
    return ProcessResult::kContinue;
  }
References v8::internal::maglev::OpProperties::can_eager_deopt(), v8::internal::maglev::OpProperties::can_lazy_deopt(), v8::internal::maglev::NodeBase::change_input(), v8::internal::maglev::NodeBase::eager_deopt_info(), v8::internal::maglev::EagerDeoptInfo::ForEachInput(), v8::internal::maglev::LazyDeoptInfo::ForEachInput(), v8::internal::maglev::NodeBase::input(), v8::internal::maglev::NodeBase::input_count(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::kContinue, v8::internal::maglev::NodeBase::lazy_deopt_info(), v8::internal::maglev::Input::node(), and v8::internal::maglev::NodeBase::properties().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-post-hoc-optimizations-processors.h