v8::internal::StringTable Class Reference
#include <string-table.h>
Classes
class Data
class OffHeapStringHashSet
Public Member Functions
StringTable (Isolate *isolate)
~StringTable ()
int Capacity () const
int NumberOfElements () const
DirectHandle< String > LookupString (Isolate *isolate, DirectHandle< String > key)
template<typename StringTableKey , typename IsolateT >
DirectHandle< String > LookupKey (IsolateT *isolate, StringTableKey *key)
void InsertForIsolateDeserialization (Isolate *isolate, const base::Vector< DirectHandle< String >> &strings)
void InsertEmptyStringForBootstrapping (Isolate *isolate)
void Print (PtrComprCageBase cage_base) const
size_t GetCurrentMemoryUsage () const
void IterateElements (RootVisitor *visitor)
void DropOldData ()
void NotifyElementsRemoved (int count)
void VerifyIfOwnedBy (Isolate *isolate)
Static Public Member Functions
static constexpr Tagged< Smi > empty_element ()
static constexpr Tagged< Smi > deleted_element ()
static Address TryStringToIndexOrLookupExisting (Isolate *isolate, Address raw_string)
Private Member Functions
Data * EnsureCapacity (PtrComprCageBase cage_base, int additional_elements)
Private Attributes
std::atomic< Data * > data_
base::Mutex write_mutex_
Isolate * isolate_
Detailed Description
Definition at line 48 of file string-table.h.
Constructor & Destructor Documentation
StringTable()
v8::internal::StringTable::StringTable (Isolate * isolate) [explicit]
Definition at line 161 of file string-table.cc.
    : data_(Data::New(OffHeapStringHashSet::kMinCapacity).release()),
      isolate_(isolate) {
  DCHECK_EQ(empty_element(), OffHeapStringHashSet::empty_element());
  DCHECK_EQ(deleted_element(), OffHeapStringHashSet::deleted_element());
}
References DCHECK_EQ, v8::internal::OffHeapHashTableBase< OffHeapStringHashSet >::deleted_element(), deleted_element(), v8::internal::OffHeapHashTableBase< OffHeapStringHashSet >::empty_element(), and empty_element().
 StringTable()
v8::internal::StringTable::~StringTable ()
Definition at line 168 of file string-table.cc.
{ delete data_; }
References data_.
Member Function Documentation
Capacity()
int v8::internal::StringTable::Capacity () const
Definition at line 170 of file string-table.cc.
                                {
  return data_.load(std::memory_order_acquire)->table().capacity();
}
References data_.
deleted_element()
static constexpr Tagged<Smi> v8::internal::StringTable::deleted_element () [inline], [static], [constexpr]
Definition at line 51 of file string-table.h.
{ return Smi::FromInt(1); }
References v8::internal::Smi::FromInt().
Referenced by StringTable(), and v8::internal::InternalizedStringTableCleaner::VisitRootPointers().
DropOldData()
void v8::internal::StringTable::DropOldData ()
Definition at line 735 of file string-table.cc.
                              {
  // This should only happen during garbage collection when background threads
  // are paused, so the load can be relaxed.
  isolate_->heap()->safepoint()->AssertActive();
  DCHECK_NE(isolate_->heap()->gc_state(), Heap::NOT_IN_GC);
  data_.load(std::memory_order_relaxed)->DropPreviousData();
}
References v8::internal::IsolateSafepoint::AssertActive(), data_, DCHECK_NE, v8::internal::Heap::gc_state(), v8::internal::Isolate::heap(), isolate_, v8::internal::Heap::NOT_IN_GC, and v8::internal::Heap::safepoint().
Referenced by v8::internal::anonymous_namespace{mark-compact.cc}::ClearStringTableJobItem::Run().
empty_element()
static constexpr Tagged<Smi> v8::internal::StringTable::empty_element () [inline], [static], [constexpr]
Definition at line 50 of file string-table.h.
{ return Smi::FromInt(0); }
References v8::internal::Smi::FromInt().
Referenced by StringTable().
EnsureCapacity()
StringTable::Data * v8::internal::StringTable::EnsureCapacity (PtrComprCageBase cage_base, int additional_elements) [private]
Definition at line 500 of file string-table.cc.
                                                                        {
  // This call is only allowed while the write mutex is held.
  write_mutex_.AssertHeld();
  // This load can be relaxed as the table pointer can only be modified while
  // the lock is held.
  Data* data = data_.load(std::memory_order_relaxed);
  int new_capacity;
  if (data->table().ShouldResizeToAdd(additional_elements, &new_capacity)) {
    std::unique_ptr<Data> new_data =
        Data::Resize(cage_base, std::unique_ptr<Data>(data), new_capacity);
    // `new_data` is the new owner of `data`.
    DCHECK_EQ(new_data->PreviousData(), data);
    // Release-store the new data pointer as `data_`, so that it can be
    // acquire-loaded by other threads. This string table becomes the owner of
    // the pointer.
    data = new_data.release();
    data_.store(data, std::memory_order_release);
  }
  return data;
}
References v8::base::Mutex::AssertHeld(), data_, DCHECK_EQ, v8::internal::StringTable::Data::Resize(), v8::internal::OffHeapHashTableBase< Derived >::ShouldResizeToAdd(), v8::internal::StringTable::Data::table(), and write_mutex_.
Referenced by InsertEmptyStringForBootstrapping(), InsertForIsolateDeserialization(), and LookupKey().
GetCurrentMemoryUsage()
size_t v8::internal::StringTable::GetCurrentMemoryUsage () const
Definition at line 723 of file string-table.cc.
                                                {
  return sizeof(*this) +
         data_.load(std::memory_order_acquire)->GetCurrentMemoryUsage();
}
References data_.
Referenced by v8::Isolate::GetHeapStatistics().
InsertEmptyStringForBootstrapping()
void v8::internal::StringTable::InsertEmptyStringForBootstrapping (Isolate * isolate)
Definition at line 701 of file string-table.cc.
                                                                    {
  DCHECK_EQ(NumberOfElements(), 0);
  {
    base::MutexGuard table_write_guard(&write_mutex_);
    Data* const data = EnsureCapacity(isolate, 1);
    DirectHandle<String> empty_string = isolate->factory()->empty_string();
    uint32_t hash = empty_string->EnsureHash();
    InternalIndex entry = data->table().FindInsertionEntry(isolate, hash);
    DCHECK_IMPLIES(v8_flags.shared_string_table, empty_string->IsShared());
    data->table().AddAt(isolate, entry, *empty_string);
  }
  DCHECK_EQ(NumberOfElements(), 1);
}
References v8::internal::OffHeapHashTableBase< Derived >::AddAt(), DCHECK_EQ, DCHECK_IMPLIES, EnsureCapacity(), v8::internal::Isolate::factory(), v8::internal::OffHeapHashTableBase< Derived >::FindInsertionEntry(), NumberOfElements(), v8::internal::StringTable::Data::table(), v8::internal::v8_flags, and write_mutex_.
Referenced by v8::internal::Heap::CreateImportantReadOnlyObjects().
InsertForIsolateDeserialization()
void v8::internal::StringTable::InsertForIsolateDeserialization (Isolate * isolate, const base::Vector< DirectHandle< String >> & strings)
Definition at line 676 of file string-table.cc.
                                                                       {
  DCHECK_EQ(NumberOfElements(), 0);
  const int length = static_cast<int>(strings.size());
  {
    base::MutexGuard table_write_guard(&write_mutex_);
    Data* const data = EnsureCapacity(isolate, length);
    for (const DirectHandle<String>& s : strings) {
      StringTableInsertionKey key(
          isolate, s, DeserializingUserCodeOption::kNotDeserializingUserCode);
      InternalIndex entry =
          data->table().FindEntryOrInsertionEntry(isolate, &key, key.hash());
      DirectHandle<String> inserted_string = key.GetHandleForInsertion(isolate);
      DCHECK_IMPLIES(v8_flags.shared_string_table, inserted_string->IsShared());
      data->table().AddAt(isolate, entry, *inserted_string);
    }
  }
  DCHECK_EQ(NumberOfElements(), length);
}
References v8::internal::OffHeapHashTableBase< Derived >::AddAt(), DCHECK_EQ, DCHECK_IMPLIES, EnsureCapacity(), v8::internal::OffHeapHashTableBase< Derived >::FindEntryOrInsertionEntry(), v8::internal::key, v8::internal::kNotDeserializingUserCode, v8::internal::length, NumberOfElements(), v8::internal::StringTable::Data::table(), v8::internal::v8_flags, and write_mutex_.
Referenced by v8::internal::SharedHeapDeserializer::DeserializeStringTable().
IterateElements()
void v8::internal::StringTable::IterateElements (RootVisitor * visitor)
Definition at line 728 of file string-table.cc.
                                                      {
  // This should only happen during garbage collection when background threads
  // are paused, so the load can be relaxed.
  isolate_->heap()->safepoint()->AssertActive();
  data_.load(std::memory_order_relaxed)->IterateElements(visitor);
}
References v8::internal::IsolateSafepoint::AssertActive(), data_, v8::internal::Isolate::heap(), isolate_, and v8::internal::Heap::safepoint().
Referenced by v8::internal::Heap::IterateWeakRoots(), v8::internal::anonymous_namespace{mark-compact.cc}::ClearStringTableJobItem::Run(), and v8::internal::SharedHeapSerializer::SerializeStringTable().
LookupKey()
template<typename StringTableKey , typename IsolateT >
template DirectHandle< String > v8::internal::StringTable::LookupKey (IsolateT * isolate, StringTableKey * key)
Definition at line 392 of file string-table.cc.
                                                                 {
  // String table lookups are allowed to be concurrent, assuming that:
  //
  // - The Heap access is allowed to be concurrent (using LocalHeap or
  // similar),
  // - All writes to the string table are guarded by the Isolate string table
  // mutex,
  // - Resizes of the string table first copies the old contents to the new
  // table, and only then sets the new string table pointer to the new
  // table,
  // - Only GCs can remove elements from the string table.
  //
  // These assumptions allow us to make the following statement:
  //
  // "Reads are allowed when not holding the lock, as long as false negatives
  // (misses) are ok. We will never get a false positive (hit of an entry no
  // longer in the table)"
  //
  // This is because we _know_ that if we find an entry in the string table, any
  // entry will also be in all reallocations of that tables. This is required
  // for strong consistency of internalized string equality implying reference
  // equality.
  //
  // We therefore try to optimistically read from the string table without
  // taking the lock (both here and in the NoAllocate version of the lookup),
  // and on a miss we take the lock and try to write the entry, with a second
  // read lookup in case the non-locked read missed a write.
  //
  // One complication is allocation -- we don't want to allocate while holding
  // the string table lock. This applies to both allocation of new strings, and
  // re-allocation of the string table on resize. So, we optimistically allocate
  // (without copying values) outside the lock, and potentially discard the
  // allocation if another write also did an allocation. This assumes that
  // writes are rarer than reads.
  // Load the current string table data, in case another thread updates the
  // data while we're reading.
  Data* const current_data = data_.load(std::memory_order_acquire);
  OffHeapStringHashSet& current_table = current_data->table();
  // First try to find the string in the table. This is safe to do even if the
  // table is now reallocated; we won't find a stale entry in the old table
  // because the new table won't delete it's corresponding entry until the
  // string is dead, in which case it will die in this table too and worst
  // case we'll have a false miss.
  InternalIndex entry = current_table.FindEntry(isolate, key, key->hash());
  if (entry.is_found()) {
    DirectHandle<String> result(
        Cast<String>(current_table.GetKey(isolate, entry)), isolate);
    DCHECK_IMPLIES(v8_flags.shared_string_table,
                   HeapLayout::InAnySharedSpace(*result));
    return result;
  }
  // No entry found, so adding new string.
  key->PrepareForInsertion(isolate);
  {
    base::MutexGuard table_write_guard(&write_mutex_);
    Data* data = EnsureCapacity(isolate, 1);
    OffHeapStringHashSet& table = data->table();
    // Check one last time if the key is present in the table, in case it was
    // added after the check.
    entry = table.FindEntryOrInsertionEntry(isolate, key, key->hash());
    Tagged<Object> element = table.GetKey(isolate, entry);
    if (element == OffHeapStringHashSet::empty_element()) {
      // This entry is empty, so write it and register that we added an
      // element.
      DirectHandle<String> new_string = key->GetHandleForInsertion(isolate_);
      DCHECK_IMPLIES(v8_flags.shared_string_table, new_string->IsShared());
      table.AddAt(isolate, entry, *new_string);
      return new_string;
    } else if (element == OffHeapStringHashSet::deleted_element()) {
      // This entry was deleted, so overwrite it and register that we
      // overwrote a deleted element.
      DirectHandle<String> new_string = key->GetHandleForInsertion(isolate_);
      DCHECK_IMPLIES(v8_flags.shared_string_table, new_string->IsShared());
      table.OverwriteDeletedAt(isolate, entry, *new_string);
      return new_string;
    } else {
      // Return the existing string as a handle.
      return direct_handle(Cast<String>(element), isolate);
    }
  }
}
References v8::internal::OffHeapHashTableBase< Derived >::AddAt(), data_, DCHECK_IMPLIES, v8::internal::OffHeapHashTableBase< OffHeapStringHashSet >::deleted_element(), v8::internal::direct_handle(), v8::internal::OffHeapHashTableBase< OffHeapStringHashSet >::empty_element(), EnsureCapacity(), v8::internal::OffHeapHashTableBase< Derived >::FindEntry(), v8::internal::OffHeapHashTableBase< Derived >::FindEntryOrInsertionEntry(), v8::internal::StringTable::OffHeapStringHashSet::GetKey(), v8::internal::HeapLayout::InAnySharedSpace(), v8::internal::InternalIndex::is_found(), isolate_, v8::internal::key, v8::internal::OffHeapHashTableBase< Derived >::OverwriteDeletedAt(), v8::base::internal::result, v8::internal::StringTable::Data::table(), v8::internal::v8_flags, and write_mutex_.
Referenced by LookupString().
LookupString()
DirectHandle< String > v8::internal::StringTable::LookupString (Isolate * isolate, DirectHandle< String > key)
Definition at line 336 of file string-table.cc.
                                                                            {
  // When sharing the string table, internalization is allowed to be concurrent
  // from multiple Isolates, assuming that:
  //
  // - All in-place internalizable strings (i.e. old-generation flat strings)
  // and internalized strings are in the shared heap.
  // - LookupKey supports concurrent access (see comment below).
  //
  // These assumptions guarantee the following properties:
  //
  // - String::Flatten is not threadsafe but is only called on non-shared
  // strings, since non-flat strings are not shared.
  //
  // - String::ComputeAndSetRawHash is threadsafe on flat strings. This is safe
  // because the characters are immutable and the same hash will be
  // computed. The hash field is set with relaxed memory order. A thread that
  // doesn't see the hash may do redundant work but will not be incorrect.
  //
  // - In-place internalizable strings do not incur a copy regardless of string
  // table sharing. The map mutation is threadsafe even with relaxed memory
  // order, because for concurrent table lookups, the "losing" thread will be
  // correctly ordered by LookupKey's write mutex and see the updated map
  // during the re-lookup.
  //
  // For lookup misses, the internalized string map is the same map in RO space
  // regardless of which thread is doing the lookup.
  //
  // For lookup hits, we use the StringForwardingTable for shared strings to
  // delay the transition into a ThinString to the next stop-the-world GC.
  DirectHandle<String> result =
      String::Flatten(isolate, indirect_handle(string, isolate));
  if (!IsInternalizedString(*result)) {
    uint32_t raw_hash_field = result->raw_hash_field(kAcquireLoad);
    if (String::IsInternalizedForwardingIndex(raw_hash_field)) {
      const int index =
          String::ForwardingIndexValueBits::decode(raw_hash_field);
      result = direct_handle(
          isolate->string_forwarding_table()->GetForwardString(isolate, index),
          isolate);
    } else {
      if (!Name::IsHashFieldComputed(raw_hash_field)) {
        raw_hash_field = result->EnsureRawHash();
      }
      InternalizedStringKey key(result, raw_hash_field);
      result = LookupKey(isolate, &key);
    }
  }
  if (*string != *result && !IsThinString(*string)) {
    SetInternalizedReference(isolate, *string, *result);
  }
  return result;
}
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::direct_handle(), v8::internal::StringForwardingTable::GetForwardString(), v8::internal::index, v8::internal::indirect_handle(), v8::internal::Name::IsHashFieldComputed(), v8::internal::Name::IsInternalizedForwardingIndex(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::InstanceTypeChecker::IsThinString(), v8::kAcquireLoad, v8::internal::key, LookupKey(), v8::base::internal::result, v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference(), and v8::internal::Isolate::string_forwarding_table().
NotifyElementsRemoved()
void v8::internal::StringTable::NotifyElementsRemoved (int count)
Definition at line 743 of file string-table.cc.
                                                 {
  // This should only happen during garbage collection when background threads
  // are paused, so the load can be relaxed.
  isolate_->heap()->safepoint()->AssertActive();
  DCHECK_NE(isolate_->heap()->gc_state(), Heap::NOT_IN_GC);
  data_.load(std::memory_order_relaxed)->table().ElementsRemoved(count);
}
References v8::internal::IsolateSafepoint::AssertActive(), data_, DCHECK_NE, v8::internal::Heap::gc_state(), v8::internal::Isolate::heap(), isolate_, v8::internal::Heap::NOT_IN_GC, and v8::internal::Heap::safepoint().
Referenced by v8::internal::anonymous_namespace{mark-compact.cc}::ClearStringTableJobItem::Run().
NumberOfElements()
int v8::internal::StringTable::NumberOfElements () const
Definition at line 173 of file string-table.cc.
                                        {
  {
    base::MutexGuard table_write_guard(&write_mutex_);
    return data_.load(std::memory_order_relaxed)->table().number_of_elements();
  }
}
References data_, and write_mutex_.
Referenced by v8::internal::SharedHeapDeserializer::DeserializeStringTable(), InsertEmptyStringForBootstrapping(), InsertForIsolateDeserialization(), and v8::internal::SharedHeapSerializer::SerializeStringTable().
Print()
void v8::internal::StringTable::Print (PtrComprCageBase cage_base) const
Definition at line 719 of file string-table.cc.
                                                        {
  data_.load(std::memory_order_acquire)->Print(cage_base);
}
References data_.
TryStringToIndexOrLookupExisting()
Address v8::internal::StringTable::TryStringToIndexOrLookupExisting (Isolate * isolate, Address raw_string) [static]
Definition at line 635 of file string-table.cc.
                                                                          {
  Tagged<String> string = Cast<String>(Tagged<Object>(raw_string));
  if (IsInternalizedString(string)) {
    // string could be internalized, if the string table is shared and another
    // thread internalized it.
    DCHECK(v8_flags.shared_string_table);
    return raw_string;
  }
  // Valid array indices are >= 0, so they cannot be mixed up with any of
  // the result sentinels, which are negative.
  static_assert(
      !String::ArrayIndexValueBits::is_valid(ResultSentinel::kUnsupported));
  static_assert(
      !String::ArrayIndexValueBits::is_valid(ResultSentinel::kNotFound));
  size_t start = 0;
  Tagged<String> source = string;
  if (IsSlicedString(source)) {
    Tagged<SlicedString> sliced = Cast<SlicedString>(source);
    start = sliced->offset();
    source = sliced->parent();
  } else if (IsConsString(source) && source->IsFlat()) {
    source = Cast<ConsString>(source)->first();
  }
  if (IsThinString(source)) {
    source = Cast<ThinString>(source)->actual();
    if (string->length() == source->length()) {
      return source.ptr();
    }
  }
  if (source->IsOneByteRepresentation()) {
    return StringTable::Data::TryStringToIndexOrLookupExisting<uint8_t>(
        isolate, string, source, start);
  }
  return StringTable::Data::TryStringToIndexOrLookupExisting<uint16_t>(
      isolate, string, source, start);
}
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::is_valid(), v8::internal::InstanceTypeChecker::IsConsString(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::InstanceTypeChecker::IsSlicedString(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::kNotFound, v8::internal::kUnsupported, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::string, and v8::internal::v8_flags.
VerifyIfOwnedBy()
void v8::internal::StringTable::VerifyIfOwnedBy (Isolate * isolate)
Member Data Documentation
data_
std::atomic<Data*> v8::internal::StringTable::data_ [private]
Definition at line 99 of file string-table.h.
Referenced by Capacity(), DropOldData(), EnsureCapacity(), GetCurrentMemoryUsage(), IterateElements(), LookupKey(), NotifyElementsRemoved(), NumberOfElements(), Print(), v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting(), and ~StringTable().
isolate_
Isolate* v8::internal::StringTable::isolate_ [private]
Definition at line 103 of file string-table.h.
Referenced by DropOldData(), IterateElements(), LookupKey(), and NotifyElementsRemoved().
write_mutex_
base::Mutex v8::internal::StringTable::write_mutex_ [mutable], [private]
Definition at line 102 of file string-table.h.
Referenced by EnsureCapacity(), InsertEmptyStringForBootstrapping(), InsertForIsolateDeserialization(), LookupKey(), and NumberOfElements().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string-table.h
/mnt/V8SourceCode/src/objects/string-table.cc