v8::internal::maglev::RegisterFrameState< RegisterT > Class Template Reference
#include <maglev-regalloc.h>
Public Types
using RegTList = RegListBase< RegisterT >
Public Member Functions
RegTList empty () const
RegTList free () const
RegTList unblocked_free () const
RegTList used () const
bool UnblockedFreeIsEmpty () const
template<typename Function >
void ForEachUsedRegister (Function &&f) const
void RemoveFromFree (RegisterT reg)
void AddToFree (RegisterT reg)
void AddToFree (RegTList list)
void FreeRegistersUsedBy (ValueNode *node)
void SetValue (RegisterT reg, ValueNode *node)
void SetValueWithoutBlocking (RegisterT reg, ValueNode *node)
ValueNode * GetValue (RegisterT reg) const
RegTList blocked () const
void block (RegisterT reg)
void unblock (RegisterT reg)
bool is_blocked (RegisterT reg)
void clear_blocked ()
compiler::InstructionOperand TryChooseInputRegister (ValueNode *node, const compiler::InstructionOperand &hint=compiler::InstructionOperand())
compiler::InstructionOperand TryChooseUnblockedInputRegister (ValueNode *node)
compiler::AllocatedOperand AllocateRegister (ValueNode *node, const compiler::InstructionOperand &hint=compiler::InstructionOperand())
Static Public Attributes
static constexpr bool kIsGeneralRegister
static constexpr bool kIsDoubleRegister
static constexpr RegTList kAllocatableRegisters
static constexpr RegTList kEmptyRegList = {}
Private Attributes
ValueNode * values_ [RegisterT::kNumRegisters]
RegTList free_ = kAllocatableRegisters
RegTList blocked_ = kEmptyRegList
Detailed Description
template<typename RegisterT>
class v8::internal::maglev::RegisterFrameState< RegisterT >
Definition at line 57 of file maglev-regalloc.h.
Member Typedef Documentation
RegTList
template<typename RegisterT >
using v8::internal::maglev::RegisterFrameState< RegisterT >::RegTList = RegListBase<RegisterT>
Definition at line 68 of file maglev-regalloc.h.
Member Function Documentation
AddToFree() [1/2]
template<typename RegisterT >
void v8::internal::maglev::RegisterFrameState< RegisterT >::AddToFree (RegisterT reg) [inline]
Definition at line 93 of file maglev-regalloc.h.
{ free_.set(reg); }
References v8::internal::maglev::RegisterFrameState< RegisterT >::free_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedTemporaries(), v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValueAtEnd(), and v8::internal::maglev::StraightForwardRegisterAllocator::FreeUnblockedRegister().
AddToFree() [2/2]
template<typename RegisterT >
void v8::internal::maglev::RegisterFrameState< RegisterT >::AddToFree (RegTList list) [inline]
Definition at line 94 of file maglev-regalloc.h.
{ free_ |= list; }
References v8::internal::maglev::RegisterFrameState< RegisterT >::free_.
AllocateRegister()
template<typename RegisterT >
compiler::AllocatedOperand v8::internal::maglev::RegisterFrameState< RegisterT >::AllocateRegister (ValueNode * node, const compiler::InstructionOperand & hint = compiler::InstructionOperand())
Definition at line 1929 of file maglev-regalloc.cc.
                                                             {
  DCHECK(!unblocked_free().is_empty());
  RegisterT reg = GetRegisterHint<RegisterT>(hint);
  if (!unblocked_free().has(reg)) {
    reg = unblocked_free().first();
  }
  RemoveFromFree(reg);
  // Allocation succeeded. This might have found an existing allocation.
  // Simply update the state anyway.
  SetValue(reg, node);
  return OperandForNodeRegister(node, reg);
}
References DCHECK, v8::internal::compiler::turboshaft::is_empty(), and v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::OperandForNodeRegister().
block()
template<typename RegisterT >
void v8::internal::maglev::RegisterFrameState< RegisterT >::block (RegisterT reg) [inline]
Definition at line 135 of file maglev-regalloc.h.
{ blocked_.set(reg); }
References v8::internal::maglev::RegisterFrameState< RegisterT >::blocked_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryTemporaries(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedTemporaries(), v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate(), and v8::internal::maglev::RegisterFrameState< RegisterT >::SetValue().
blocked()
template<typename RegisterT >
RegTList v8::internal::maglev::RegisterFrameState< RegisterT >::blocked () const [inline]
Definition at line 134 of file maglev-regalloc.h.
{ return blocked_; }
References v8::internal::maglev::RegisterFrameState< RegisterT >::blocked_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::EnsureFreeRegisterAtEnd(), and v8::internal::maglev::StraightForwardRegisterAllocator::FreeUnblockedRegister().
clear_blocked()
template<typename RegisterT >
void v8::internal::maglev::RegisterFrameState< RegisterT >::clear_blocked () [inline]
Definition at line 138 of file maglev-regalloc.h.
{ blocked_ = kEmptyRegList; }
References v8::internal::maglev::RegisterFrameState< RegisterT >::blocked_, and v8::internal::maglev::RegisterFrameState< RegisterT >::kEmptyRegList.
empty()
template<typename RegisterT >
RegTList v8::internal::maglev::RegisterFrameState< RegisterT >::empty () const [inline]
Definition at line 74 of file maglev-regalloc.h.
{ return kEmptyRegList; }
References v8::internal::maglev::RegisterFrameState< RegisterT >::kEmptyRegList.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::EnsureFreeRegisterAtEnd(), and v8::internal::maglev::StraightForwardRegisterAllocator::SpillAndClearRegisters().
ForEachUsedRegister()
template<typename RegisterT >
template<typename Function >
void v8::internal::maglev::RegisterFrameState< RegisterT >::ForEachUsedRegister (Function && f) const [inline]
Definition at line 86 of file maglev-regalloc.h.
                                               {
    for (RegisterT reg : used()) {
      f(reg, GetValue(reg));
    }
  }
References v8::internal::maglev::RegisterFrameState< RegisterT >::GetValue(), and v8::internal::maglev::RegisterFrameState< RegisterT >::used().
free()
template<typename RegisterT >
RegTList v8::internal::maglev::RegisterFrameState< RegisterT >::free () const [inline]
Definition at line 75 of file maglev-regalloc.h.
{ return free_; }
References v8::internal::maglev::RegisterFrameState< RegisterT >::free_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedTemporaries(), v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValue(), v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValueAtEnd(), v8::internal::maglev::StraightForwardRegisterAllocator::EnsureFreeRegisterAtEnd(), v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate(), and v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopReloads().
FreeRegistersUsedBy()
template<typename RegisterT >
void v8::internal::maglev::RegisterFrameState< RegisterT >::FreeRegistersUsedBy (ValueNode * node) [inline]
Definition at line 96 of file maglev-regalloc.h.
                                            {
    RegTList list = node->ClearRegisters<RegisterT>();
    DCHECK_EQ(free_ & list, kEmptyRegList);
    free_ |= list;
  }
References v8::internal::maglev::ValueNode::ClearRegisters(), DCHECK_EQ, v8::internal::maglev::RegisterFrameState< RegisterT >::free_, and v8::internal::maglev::RegisterFrameState< RegisterT >::kEmptyRegList.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::SpillAndClearRegisters().
GetValue()
template<typename RegisterT >
ValueNode* v8::internal::maglev::RegisterFrameState< RegisterT >::GetValue (RegisterT reg) const [inline]
Definition at line 115 of file maglev-regalloc.h.
                                           {
    DCHECK(!free_.has(reg));
    ValueNode* node = values_[reg.code()];
    DCHECK_NOT_NULL(node);
    return node;
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::maglev::RegisterFrameState< RegisterT >::free_, and v8::internal::maglev::RegisterFrameState< RegisterT >::values_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValue(), v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValueAtEnd(), v8::internal::maglev::StraightForwardRegisterAllocator::EnsureFreeRegisterAtEnd(), v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate(), v8::internal::maglev::RegisterFrameState< RegisterT >::ForEachUsedRegister(), v8::internal::maglev::StraightForwardRegisterAllocator::PickRegisterToFree(), and v8::internal::maglev::StraightForwardRegisterAllocator::SpillAndClearRegisters().
is_blocked()
template<typename RegisterT >
bool v8::internal::maglev::RegisterFrameState< RegisterT >::is_blocked (RegisterT reg) [inline]
Definition at line 137 of file maglev-regalloc.h.
{ return blocked_.has(reg); }
References v8::internal::maglev::RegisterFrameState< RegisterT >::blocked_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedTemporaries(), v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate(), and v8::internal::maglev::StraightForwardRegisterAllocator::FreeUnblockedRegister().
RemoveFromFree()
template<typename RegisterT >
void v8::internal::maglev::RegisterFrameState< RegisterT >::RemoveFromFree (RegisterT reg) [inline]
Definition at line 92 of file maglev-regalloc.h.
{ free_.clear(reg); }
References v8::internal::maglev::RegisterFrameState< RegisterT >::free_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValue(), v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate(), and v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopReloads().
SetValue()
template<typename RegisterT >
void v8::internal::maglev::RegisterFrameState< RegisterT >::SetValue (RegisterT reg, ValueNode * node) [inline]
Definition at line 102 of file maglev-regalloc.h.
                                                {
    DCHECK(!free_.has(reg));
    DCHECK(!blocked_.has(reg));
    values_[reg.code()] = node;
    block(reg);
    node->AddRegister(reg);
  }
References v8::internal::maglev::ValueNode::AddRegister(), v8::internal::maglev::RegisterFrameState< RegisterT >::block(), v8::internal::maglev::RegisterFrameState< RegisterT >::blocked_, v8::internal::DCHECK(), v8::internal::maglev::RegisterFrameState< RegisterT >::free_, and v8::internal::maglev::RegisterFrameState< RegisterT >::values_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate().
SetValueWithoutBlocking()
template<typename RegisterT >
void v8::internal::maglev::RegisterFrameState< RegisterT >::SetValueWithoutBlocking (RegisterT reg, ValueNode * node) [inline]
Definition at line 109 of file maglev-regalloc.h.
                                                               {
    DCHECK(!free_.has(reg));
    DCHECK(!blocked_.has(reg));
    values_[reg.code()] = node;
    node->AddRegister(reg);
  }
References v8::internal::maglev::ValueNode::AddRegister(), v8::internal::maglev::RegisterFrameState< RegisterT >::blocked_, v8::internal::DCHECK(), v8::internal::maglev::RegisterFrameState< RegisterT >::free_, and v8::internal::maglev::RegisterFrameState< RegisterT >::values_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValue(), and v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopReloads().
TryChooseInputRegister()
template<typename RegisterT >
compiler::InstructionOperand v8::internal::maglev::RegisterFrameState< RegisterT >::TryChooseInputRegister (ValueNode * node, const compiler::InstructionOperand & hint = compiler::InstructionOperand())
Definition at line 1897 of file maglev-regalloc.cc.
                                                             {
  RegTList result_registers = node->result_registers<RegisterT>();
  if (result_registers.is_empty()) return compiler::InstructionOperand();
  // Prefer to return an existing blocked register.
  RegTList blocked_result_registers = result_registers & blocked_;
  if (!blocked_result_registers.is_empty()) {
    RegisterT reg = GetRegisterHint<RegisterT>(hint);
    if (!blocked_result_registers.has(reg)) {
      reg = blocked_result_registers.first();
    }
    return OperandForNodeRegister(node, reg);
  }
  RegisterT reg = result_registers.first();
  block(reg);
  return OperandForNodeRegister(node, reg);
}
References v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::OperandForNodeRegister(), and v8::internal::maglev::ValueNode::result_registers().
TryChooseUnblockedInputRegister()
template<typename RegisterT >
compiler::InstructionOperand v8::internal::maglev::RegisterFrameState< RegisterT >::TryChooseUnblockedInputRegister (ValueNode * node)
Definition at line 1919 of file maglev-regalloc.cc.
                     {
  RegTList result_excl_blocked = node->result_registers<RegisterT>() - blocked_;
  if (result_excl_blocked.is_empty()) return compiler::InstructionOperand();
  RegisterT reg = result_excl_blocked.first();
  block(reg);
  return OperandForNodeRegister(node, reg);
}
References v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::OperandForNodeRegister(), and v8::internal::maglev::ValueNode::result_registers().
unblock()
template<typename RegisterT >
void v8::internal::maglev::RegisterFrameState< RegisterT >::unblock (RegisterT reg) [inline]
Definition at line 136 of file maglev-regalloc.h.
{ blocked_.clear(reg); }
References v8::internal::maglev::RegisterFrameState< RegisterT >::blocked_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValueAtEnd(), and v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate().
unblocked_free()
template<typename RegisterT >
RegTList v8::internal::maglev::RegisterFrameState< RegisterT >::unblocked_free () const [inline]
Definition at line 76 of file maglev-regalloc.h.
{ return free_ - blocked_; }
References v8::internal::maglev::RegisterFrameState< RegisterT >::blocked_, and v8::internal::maglev::RegisterFrameState< RegisterT >::free_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryTemporaries(), v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValue(), v8::internal::maglev::StraightForwardRegisterAllocator::EnsureFreeRegisterAtEnd(), and v8::internal::maglev::RegisterFrameState< RegisterT >::UnblockedFreeIsEmpty().
UnblockedFreeIsEmpty()
template<typename RegisterT >
bool v8::internal::maglev::RegisterFrameState< RegisterT >::UnblockedFreeIsEmpty () const [inline]
Definition at line 83 of file maglev-regalloc.h.
{ return unblocked_free().is_empty(); }
References v8::internal::maglev::RegisterFrameState< RegisterT >::unblocked_free().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValue().
used()
template<typename RegisterT >
RegTList v8::internal::maglev::RegisterFrameState< RegisterT >::used () const [inline]
Definition at line 77 of file maglev-regalloc.h.
                        {
    // Only allocatable registers should be free.
    DCHECK_EQ(free_, free_ & kAllocatableRegisters);
    return kAllocatableRegisters ^ free_;
  }
References DCHECK_EQ, v8::internal::maglev::RegisterFrameState< RegisterT >::free_, and v8::internal::maglev::RegisterFrameState< RegisterT >::kAllocatableRegisters.
Referenced by v8::internal::maglev::RegisterFrameState< RegisterT >::ForEachUsedRegister(), v8::internal::maglev::StraightForwardRegisterAllocator::PickRegisterToFree(), and v8::internal::maglev::StraightForwardRegisterAllocator::SpillAndClearRegisters().
Member Data Documentation
blocked_
template<typename RegisterT >
RegTList v8::internal::maglev::RegisterFrameState< RegisterT >::blocked_ = kEmptyRegList [private]
Definition at line 151 of file maglev-regalloc.h.
Referenced by v8::internal::maglev::RegisterFrameState< RegisterT >::block(), v8::internal::maglev::RegisterFrameState< RegisterT >::blocked(), v8::internal::maglev::RegisterFrameState< RegisterT >::clear_blocked(), v8::internal::maglev::RegisterFrameState< RegisterT >::is_blocked(), v8::internal::maglev::RegisterFrameState< RegisterT >::SetValue(), v8::internal::maglev::RegisterFrameState< RegisterT >::SetValueWithoutBlocking(), v8::internal::maglev::RegisterFrameState< RegisterT >::unblock(), and v8::internal::maglev::RegisterFrameState< RegisterT >::unblocked_free().
free_
template<typename RegisterT >
RegTList v8::internal::maglev::RegisterFrameState< RegisterT >::free_ = kAllocatableRegisters [private]
Definition at line 150 of file maglev-regalloc.h.
Referenced by v8::internal::maglev::RegisterFrameState< RegisterT >::AddToFree(), v8::internal::maglev::RegisterFrameState< RegisterT >::free(), v8::internal::maglev::RegisterFrameState< RegisterT >::FreeRegistersUsedBy(), v8::internal::maglev::RegisterFrameState< RegisterT >::GetValue(), v8::internal::maglev::RegisterFrameState< RegisterT >::RemoveFromFree(), v8::internal::maglev::RegisterFrameState< RegisterT >::SetValue(), v8::internal::maglev::RegisterFrameState< RegisterT >::SetValueWithoutBlocking(), v8::internal::maglev::RegisterFrameState< RegisterT >::unblocked_free(), and v8::internal::maglev::RegisterFrameState< RegisterT >::used().
kAllocatableRegisters
template<typename RegisterT >
constexpr RegTList v8::internal::maglev::RegisterFrameState< RegisterT >::kAllocatableRegisters [static], [constexpr]
Initial value:
=
      AllocatableRegisters<RegisterT>::kRegisters
Definition at line 70 of file maglev-regalloc.h.
Referenced by v8::internal::maglev::RegisterFrameState< RegisterT >::used().
kEmptyRegList
template<typename RegisterT >
constexpr RegTList v8::internal::maglev::RegisterFrameState< RegisterT >::kEmptyRegList = {} [static], [constexpr]
Definition at line 72 of file maglev-regalloc.h.
Referenced by v8::internal::maglev::RegisterFrameState< RegisterT >::clear_blocked(), v8::internal::maglev::RegisterFrameState< RegisterT >::empty(), and v8::internal::maglev::RegisterFrameState< RegisterT >::FreeRegistersUsedBy().
kIsDoubleRegister
template<typename RegisterT >
constexpr bool v8::internal::maglev::RegisterFrameState< RegisterT >::kIsDoubleRegister [static], [constexpr]
Initial value:
=
      std::is_same_v<DoubleRegister, RegisterT>
Definition at line 61 of file maglev-regalloc.h.
kIsGeneralRegister
template<typename RegisterT >
constexpr bool v8::internal::maglev::RegisterFrameState< RegisterT >::kIsGeneralRegister [static], [constexpr]
Initial value:
=
      std::is_same_v<Register, RegisterT>
Definition at line 59 of file maglev-regalloc.h.
values_
template<typename RegisterT >
ValueNode* v8::internal::maglev::RegisterFrameState< RegisterT >::values_[RegisterT::kNumRegisters] [private]
Definition at line 149 of file maglev-regalloc.h.
Referenced by v8::internal::maglev::RegisterFrameState< RegisterT >::GetValue(), v8::internal::maglev::RegisterFrameState< RegisterT >::SetValue(), and v8::internal::maglev::RegisterFrameState< RegisterT >::SetValueWithoutBlocking().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-regalloc.h
/mnt/V8SourceCode/src/maglev/maglev-regalloc.cc