v8::internal::compiler::Loong64OperandConverter Class Reference
Public Member Functions
Loong64OperandConverter (CodeGenerator *gen, Instruction *instr)
FloatRegister OutputSingleRegister (size_t index=0)
FloatRegister InputSingleRegister (size_t index)
FloatRegister ToSingleRegister (InstructionOperand *op)
Register InputOrZeroRegister (size_t index)
DoubleRegister InputOrZeroDoubleRegister (size_t index)
DoubleRegister InputOrZeroSingleRegister (size_t index)
Operand InputImmediate (size_t index)
Operand InputOperand (size_t index)
MemOperand MemoryOperand (size_t *first_index)
MemOperand MemoryOperand (size_t index=0)
MemOperand ToMemOperand (InstructionOperand *op) const
MemOperand SlotToMemOperand (int slot) const
Additional Inherited Members
Detailed Description
Definition at line 28 of file code-generator-loong64.cc.
Constructor & Destructor Documentation
Loong64OperandConverter()
v8::internal::compiler::Loong64OperandConverter::Loong64OperandConverter (CodeGenerator * gen, Instruction * instr) [inline]
Definition at line 30 of file code-generator-loong64.cc.
      : InstructionOperandConverter(gen, instr) {}
Member Function Documentation
InputImmediate()
Operand v8::internal::compiler::Loong64OperandConverter::InputImmediate (size_t index) [inline]
Definition at line 67 of file code-generator-loong64.cc.
                                       {
    Constant constant = ToConstant(instr_->InputAt(index));
    switch (constant.type()) {
      case Constant::kInt32:
        return Operand(constant.ToInt32());
      case Constant::kInt64:
        return Operand(constant.ToInt64());
      case Constant::kFloat32:
        return Operand::EmbeddedNumber(constant.ToFloat32());
      case Constant::kFloat64:
        return Operand::EmbeddedNumber(constant.ToFloat64().value());
      case Constant::kCompressedHeapObject: {
        RootIndex root_index;
        if (gen_->isolate()->roots_table().IsRootHandle(constant.ToHeapObject(),
                                                        &root_index)) {
          CHECK(COMPRESS_POINTERS_BOOL);
          CHECK(V8_STATIC_ROOTS_BOOL || !gen_->isolate()->bootstrapper());
          Tagged_t ptr =
              MacroAssemblerBase::ReadOnlyRootPtr(root_index, gen_->isolate());
          return Operand(ptr);
        }
        return Operand(constant.ToHeapObject());
      }
      case Constant::kExternalReference:
      case Constant::kHeapObject:
        break;
      case Constant::kRpoNumber:
        UNREACHABLE(); // TODO(titzer): RPO immediates on loong64?
    }
    UNREACHABLE();
  }
References v8::internal::Isolate::bootstrapper(), CHECK, COMPRESS_POINTERS_BOOL, v8::internal::Operand::EmbeddedNumber(), v8::internal::compiler::InstructionOperandConverter::gen_, v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::CodeGenerator::isolate(), v8::internal::RootsTable::IsRootHandle(), v8::internal::compiler::Constant::kCompressedHeapObject, v8::internal::compiler::Constant::kExternalReference, v8::internal::compiler::Constant::kFloat32, v8::internal::compiler::Constant::kFloat64, v8::internal::compiler::Constant::kHeapObject, v8::internal::compiler::Constant::kInt32, v8::internal::compiler::Constant::kInt64, v8::internal::compiler::Constant::kRpoNumber, v8::internal::MacroAssemblerBase::ReadOnlyRootPtr(), v8::internal::Isolate::roots_table(), v8::internal::compiler::InstructionOperandConverter::ToConstant(), v8::internal::compiler::Constant::ToFloat32(), v8::internal::compiler::Constant::ToFloat64(), v8::internal::compiler::Constant::ToHeapObject(), v8::internal::compiler::Constant::ToInt32(), v8::internal::compiler::Constant::ToInt64(), v8::internal::compiler::Constant::type(), v8::internal::UNREACHABLE(), V8_STATIC_ROOTS_BOOL, and v8::base::Double::value().
Referenced by InputOperand().
InputOperand()
Operand v8::internal::compiler::Loong64OperandConverter::InputOperand (size_t index) [inline]
Definition at line 99 of file code-generator-loong64.cc.
                                     {
    InstructionOperand* op = instr_->InputAt(index);
    if (op->IsRegister()) {
      return Operand(ToRegister(op));
    }
    return InputImmediate(index);
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), InputImmediate(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::InstructionOperand::IsRegister(), and v8::internal::compiler::InstructionOperandConverter::ToRegister().
InputOrZeroDoubleRegister()
DoubleRegister v8::internal::compiler::Loong64OperandConverter::InputOrZeroDoubleRegister (size_t index) [inline]
Definition at line 55 of file code-generator-loong64.cc.
                                                         {
    if (instr_->InputAt(index)->IsImmediate()) return kDoubleRegZero;
    return InputDoubleRegister(index);
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::InputDoubleRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, and v8::internal::kDoubleRegZero.
InputOrZeroRegister()
Register v8::internal::compiler::Loong64OperandConverter::InputOrZeroRegister (size_t index) [inline]
Definition at line 47 of file code-generator-loong64.cc.
                                             {
    if (instr_->InputAt(index)->IsImmediate()) {
      DCHECK_EQ(0, InputInt32(index));
      return zero_reg;
    }
    return InputRegister(index);
  }
References DCHECK_EQ, v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::InputInt32(), v8::internal::compiler::InstructionOperandConverter::InputRegister(), and v8::internal::compiler::InstructionOperandConverter::instr_.
InputOrZeroSingleRegister()
DoubleRegister v8::internal::compiler::Loong64OperandConverter::InputOrZeroSingleRegister (size_t index) [inline]
Definition at line 61 of file code-generator-loong64.cc.
                                                         {
    if (instr_->InputAt(index)->IsImmediate()) return kDoubleRegZero;
    return InputSingleRegister(index);
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), InputSingleRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, and v8::internal::kDoubleRegZero.
InputSingleRegister()
FloatRegister v8::internal::compiler::Loong64OperandConverter::InputSingleRegister (size_t index) [inline]
Definition at line 37 of file code-generator-loong64.cc.
                                                  {
    return ToSingleRegister(instr_->InputAt(index));
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, and ToSingleRegister().
Referenced by InputOrZeroSingleRegister().
MemoryOperand() [1/2]
MemOperand v8::internal::compiler::Loong64OperandConverter::MemoryOperand (size_t * first_index) [inline]
Definition at line 107 of file code-generator-loong64.cc.
                                                {
    const size_t index = *first_index;
    switch (AddressingModeField::decode(instr_->opcode())) {
      case kMode_None:
        break;
      case kMode_Root:
        *first_index += 1;
        return MemOperand(kRootRegister, InputInt32(index));
      case kMode_MRI:
        *first_index += 2;
        return MemOperand(InputRegister(index + 0), InputInt32(index + 1));
      case kMode_MRR:
        *first_index += 2;
        return MemOperand(InputRegister(index + 0), InputRegister(index + 1));
    }
    UNREACHABLE();
  }
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, v8::internal::compiler::InstructionOperandConverter::InputInt32(), v8::internal::compiler::InstructionOperandConverter::InputRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::kRootRegister, v8::internal::compiler::Instruction::opcode(), and v8::internal::UNREACHABLE().
MemoryOperand() [2/2]
MemOperand v8::internal::compiler::Loong64OperandConverter::MemoryOperand (size_t index = 0) [inline]
Definition at line 125 of file code-generator-loong64.cc.
{ return MemoryOperand(&index); }
References v8::internal::index, and MemoryOperand().
Referenced by MemoryOperand().
OutputSingleRegister()
FloatRegister v8::internal::compiler::Loong64OperandConverter::OutputSingleRegister (size_t index = 0) [inline]
Definition at line 33 of file code-generator-loong64.cc.
                                                       {
    return ToSingleRegister(instr_->OutputAt(index));
  }
References v8::internal::index, v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::Instruction::OutputAt(), and ToSingleRegister().
SlotToMemOperand()
MemOperand v8::internal::compiler::Loong64OperandConverter::SlotToMemOperand (int slot) const [inline]
Definition at line 133 of file code-generator-loong64.cc.
                                              {
    FrameOffset offset = frame_access_state()->GetFrameOffset(slot);
    return MemOperand(offset.from_stack_pointer() ? sp : fp, offset.offset());
  }
References v8::internal::compiler::InstructionOperandConverter::frame_access_state(), v8::internal::compiler::FrameOffset::from_stack_pointer(), v8::internal::compiler::FrameAccessState::GetFrameOffset(), and v8::internal::compiler::FrameOffset::offset().
Referenced by ToMemOperand().
ToMemOperand()
MemOperand v8::internal::compiler::Loong64OperandConverter::ToMemOperand (InstructionOperand * op) const [inline]
Definition at line 127 of file code-generator-loong64.cc.
                                                        {
    DCHECK_NOT_NULL(op);
    DCHECK(op->IsStackSlot() || op->IsFPStackSlot());
    return SlotToMemOperand(AllocatedOperand::cast(op)->index());
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::index, v8::internal::compiler::InstructionOperand::IsFPStackSlot(), v8::internal::compiler::InstructionOperand::IsStackSlot(), and SlotToMemOperand().
ToSingleRegister()
FloatRegister v8::internal::compiler::Loong64OperandConverter::ToSingleRegister (InstructionOperand * op) [inline]
Definition at line 41 of file code-generator-loong64.cc.
                                                         {
    // Single (Float) and Double register namespace is same on LOONG64,
    // both are typedefs of FPURegister.
    return ToDoubleRegister(op);
  }
References v8::internal::compiler::InstructionOperandConverter::ToDoubleRegister().
Referenced by InputSingleRegister(), and OutputSingleRegister().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/loong64/code-generator-loong64.cc