v8::internal::maglev::BranchIfRootConstant Class Reference
#include <maglev-ir.h>
Public Member Functions
BranchIfRootConstant (uint64_t bitfield, RootIndex root_index, BasicBlockRef *if_true_refs, BasicBlockRef *if_false_refs)
RootIndex root_index ()
Input & condition_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = BranchControlNodeT< 1, BranchIfRootConstant >
Private Attributes
RootIndex root_index_
Additional Inherited Members
Detailed Description
Definition at line 11489 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::BranchIfRootConstant::Base = BranchControlNodeT<1, BranchIfRootConstant> [private]
Definition at line 11491 of file maglev-ir.h.
Constructor & Destructor Documentation
BranchIfRootConstant()
v8::internal::maglev::BranchIfRootConstant::BranchIfRootConstant (uint64_t bitfield, RootIndex root_index, BasicBlockRef * if_true_refs, BasicBlockRef * if_false_refs) [inline], [explicit]
Definition at line 11494 of file maglev-ir.h.
      : Base(bitfield, if_true_refs, if_false_refs), root_index_(root_index) {}
Member Function Documentation
condition_input()
Input& v8::internal::maglev::BranchIfRootConstant::condition_input () [inline]
Definition at line 11503 of file maglev-ir.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::BranchIfRootConstant::GenerateCode (MaglevAssembler * , const ProcessingState &)
PrintParams()
void v8::internal::maglev::BranchIfRootConstant::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8448 of file maglev-ir.cc.
                                                               {
  os << "(" << RootsTable::name(root_index_) << ")";
}
References v8::internal::RootsTable::name(), and root_index_.
root_index()
RootIndex v8::internal::maglev::BranchIfRootConstant::root_index () [inline]
Definition at line 11502 of file maglev-ir.h.
{ return root_index_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::BranchIfRootConstant::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::BranchIfRootConstant::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 11500 of file maglev-ir.h.
root_index_
RootIndex v8::internal::maglev::BranchIfRootConstant::root_index_ [private]
Definition at line 11516 of file maglev-ir.h.
Referenced by PrintParams().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc