v8::internal::CpuSampler Class Reference
Public Member Functions
CpuSampler (Isolate *isolate, SamplingEventsProcessor *processor)
void SampleStack (const v8::RegisterState &regs) override
Private Attributes
SamplingEventsProcessor * processor_
Isolate::PerIsolateThreadData * perThreadData_
Additional Inherited Members
Detailed Description
Definition at line 35 of file cpu-profiler.cc.
Constructor & Destructor Documentation
CpuSampler()
v8::internal::CpuSampler::CpuSampler (Isolate * isolate, SamplingEventsProcessor * processor) [inline]
Definition at line 37 of file cpu-profiler.cc.
      : sampler::Sampler(reinterpret_cast<v8::Isolate*>(isolate)),
        processor_(processor),
        perThreadData_(isolate->FindPerThreadDataForThisThread()) {}
Member Function Documentation
SampleStack()
void v8::internal::CpuSampler::SampleStack (const v8::RegisterState & regs) [inline], [override], [virtual]
Implements v8::sampler::Sampler.
Definition at line 42 of file cpu-profiler.cc.
                                                         {
    Isolate* isolate = reinterpret_cast<Isolate*>(this->isolate());
    if (isolate->was_locker_ever_used() &&
        (!isolate->thread_manager()->IsLockedByThread(
             perThreadData_->thread_id()) ||
         perThreadData_->thread_state() != nullptr)) {
      ProfilerStats::Instance()->AddReason(
          ProfilerStats::Reason::kIsolateNotLocked);
      return;
    }
    TickSample* sample = processor_->StartTickSample();
    if (sample == nullptr) {
      ProfilerStats::Instance()->AddReason(
          ProfilerStats::Reason::kTickBufferFull);
      return;
    }
    // Every bailout up until here resulted in a dropped sample. From now on,
    // the sample is created in the buffer.
    sample->Init(isolate, regs, TickSample::kIncludeCEntryFrame,
                 /* update_stats */ true,
                 /* use_simulator_reg_state */ true, processor_->period());
    if (is_counting_samples_ && !sample->timestamp.IsNull()) {
      if (sample->state == JS) ++js_sample_count_;
      if (sample->state == EXTERNAL) ++external_sample_count_;
    }
    processor_->FinishTickSample();
  }
References v8::internal::ProfilerStats::AddReason(), v8::EXTERNAL, v8::sampler::Sampler::external_sample_count_, v8::internal::SamplingEventsProcessor::FinishTickSample(), v8::internal::TickSample::Init(), v8::internal::ProfilerStats::Instance(), v8::sampler::Sampler::is_counting_samples_, v8::base::time_internal::TimeBase< TimeClass >::IsNull(), v8::sampler::Sampler::isolate(), v8::JS, v8::sampler::Sampler::js_sample_count_, v8::internal::TickSample::kIncludeCEntryFrame, v8::internal::SamplingEventsProcessor::period(), perThreadData_, processor_, v8::internal::SamplingEventsProcessor::StartTickSample(), v8::internal::TickSample::state, v8::internal::Isolate::PerIsolateThreadData::thread_id(), v8::internal::TickSample::timestamp, and v8::internal::Isolate::was_locker_ever_used().
Member Data Documentation
perThreadData_
Isolate::PerIsolateThreadData* v8::internal::CpuSampler::perThreadData_ [private]
Definition at line 72 of file cpu-profiler.cc.
Referenced by SampleStack().
processor_
SamplingEventsProcessor* v8::internal::CpuSampler::processor_ [private]
Definition at line 71 of file cpu-profiler.cc.
Referenced by SampleStack().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/profiler/cpu-profiler.cc