v8::internal::FunctionLiteralSourceRanges Class Reference
#include <ast-source-ranges.h>
Public Member Functions
SourceRange GetRange (SourceRangeKind kind) override
bool HasRange (SourceRangeKind kind) override
Detailed Description
Definition at line 206 of file ast-source-ranges.h.
Member Function Documentation
GetRange()
SourceRange v8::internal::FunctionLiteralSourceRanges::GetRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 208 of file ast-source-ranges.h.
                                                      {
    DCHECK(HasRange(kind));
    return SourceRange::FunctionLiteralMarkerRange();
  }
References v8::internal::DCHECK(), v8::internal::SourceRange::FunctionLiteralMarkerRange(), and HasRange().
HasRange()
bool v8::internal::FunctionLiteralSourceRanges::HasRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 213 of file ast-source-ranges.h.
                                               {
    return kind == SourceRangeKind::kBody;
  }
References v8::internal::kBody.
Referenced by GetRange().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast-source-ranges.h