v8::internal::compiler::CodeAssembler Class Reference
#include <code-assembler.h>
Classes
class BuiltinCompilationScheduler
class CheckedNode
struct MessageWithSourceLocation
class SourcePositionScope
Public Types
using Label = CodeAssemblerLabel
template<class T >
using TVariable = TypedCodeAssemblerVariable< T >
using VariableList = CodeAssemblerVariableList
using CFunctionArg = std::pair< MachineType, Node * >
Public Member Functions
CodeAssembler (CodeAssemblerState *state)
~CodeAssembler ()
CodeAssembler (const CodeAssembler &)=delete
CodeAssembler & operator= (const CodeAssembler &)=delete
bool Is64 () const
bool Is32 () const
bool IsFloat64RoundUpSupported () const
bool IsFloat64RoundDownSupported () const
bool IsFloat64RoundTiesEvenSupported () const
bool IsFloat64RoundTruncateSupported () const
bool IsTruncateFloat64ToFloat16RawBitsSupported () const
bool IsInt32AbsWithOverflowSupported () const
bool IsInt64AbsWithOverflowSupported () const
bool IsIntPtrAbsWithOverflowSupported () const
bool IsWord32PopcntSupported () const
bool IsWord64PopcntSupported () const
bool IsWord32CtzSupported () const
bool IsWord64CtzSupported () const
template<class T >
TNode< T > UncheckedCast (Node *value)
template<class T , class U >
TNode< T > UncheckedCast (TNode< U > value)
template<class T >
TNode< T > ReinterpretCast (Node *value)
CheckedNode< Object, false > Cast (Node *value, const char *location=``)
template<class T >
CheckedNode< T, true > Cast (TNode< T > value, const char *location=``)
TNode< Int32T > UniqueInt32Constant (int32_t value)
TNode< Int32T > Int32Constant (int32_t value)
TNode< Int64T > UniqueInt64Constant (int64_t value)
TNode< Int64T > Int64Constant (int64_t value)
TNode< Uint64T > Uint64Constant (uint64_t value)
TNode< IntPtrT > IntPtrConstant (intptr_t value)
TNode< IntPtrT > UniqueIntPtrConstant (intptr_t value)
TNode< Uint32T > UniqueUint32Constant (int32_t value)
TNode< Uint32T > Uint32Constant (uint32_t value)
TNode< Uint32T > Uint64HighWordConstant (uint64_t value)
TNode< Uint32T > Uint64HighWordConstantNoLowWord (uint64_t value)
TNode< Uint32T > Uint64LowWordConstant (uint64_t value)
TNode< UintPtrT > UintPtrConstant (uintptr_t value)
TNode< TaggedIndex > TaggedIndexConstant (intptr_t value)
TNode< RawPtrT > PointerConstant (void *value)
TNode< Number > NumberConstant (double value)
TNode< Smi > SmiConstant (Tagged< Smi > value)
TNode< Smi > SmiConstant (int value)
template<typename E >
TNode< Smi > SmiConstant(E value) requires std TNode< HeapObject > UntypedHeapConstantNoHole (Handle< HeapObject > object)
TNode< HeapObject > UntypedHeapConstantMaybeHole (Handle< HeapObject > object)
TNode< HeapObject > UntypedHeapConstantHole (Handle< HeapObject > object)
template<class Type >
TNode< Type > HeapConstantNoHole (Handle< Type > object)
template<class Type >
TNode< Type > HeapConstantMaybeHole (Handle< Type > object)
template<class Type >
TNode< Type > HeapConstantHole (Handle< Type > object)
TNode< String > StringConstant (const char *str)
TNode< Boolean > BooleanConstant (bool value)
TNode< ExternalReference > ExternalConstant (ExternalReference address)
TNode< ExternalReference > IsolateField (IsolateFieldId id)
TNode< Float32T > Float32Constant (double value)
TNode< Float64T > Float64Constant (double value)
TNode< BoolT > Int32TrueConstant ()
TNode< BoolT > Int32FalseConstant ()
TNode< BoolT > BoolConstant (bool value)
TNode< ExternalPointerHandleT > ExternalPointerHandleNullConstant ()
bool IsMapOffsetConstant (Node *node)
bool TryToInt32Constant (TNode< IntegralT > node, int32_t *out_value)
bool TryToInt64Constant (TNode< IntegralT > node, int64_t *out_value)
bool TryToIntPtrConstant (TNode< IntegralT > node, intptr_t *out_value)
bool TryToIntPtrConstant (TNode< Smi > tnode, intptr_t *out_value)
bool TryToSmiConstant (TNode< IntegralT > node, Tagged< Smi > *out_value)
bool TryToSmiConstant (TNode< Smi > node, Tagged< Smi > *out_value)
bool IsUndefinedConstant (TNode< Object > node)
bool IsNullConstant (TNode< Object > node)
TNode< Int32T > Signed (TNode< Word32T > x)
TNode< Int64T > Signed (TNode< Word64T > x)
TNode< IntPtrT > Signed (TNode< WordT > x)
TNode< Uint32T > Unsigned (TNode< Word32T > x)
TNode< Uint64T > Unsigned (TNode< Word64T > x)
TNode< UintPtrT > Unsigned (TNode< WordT > x)
bool HasDynamicJSParameterCount ()
TNode< Uint16T > DynamicJSParameterCount ()
void SetDynamicJSParameterCount (TNode< Uint16T > parameter_count)
template<class T >
TNode< T > Parameter (int value, const SourceLocation &loc=SourceLocation::Current())
template<class T >
TNode< T > UncheckedParameter (int value)
Node * UntypedParameter (int value)
TNode< Context > GetJSContextParameter ()
void Return (TNode< Object > value)
void Return (TNode< Object > value1, TNode< Object > value2)
void Return (TNode< Object > value1, TNode< Object > value2, TNode< Object > value3)
void Return (TNode< Int32T > value)
void Return (TNode< Uint32T > value)
void Return (TNode< WordT > value)
void Return (TNode< Float32T > value)
void Return (TNode< Float64T > value)
void Return (TNode< WordT > value1, TNode< WordT > value2)
void Return (TNode< Word32T > value1, TNode< Word32T > value2)
void Return (TNode< WordT > value1, TNode< Object > value2)
void Return (TNode< Word32T > value1, TNode< Object > value2)
void PopAndReturn (Node *pop, Node *value)
void PopAndReturn (Node *pop, Node *value1, Node *value2, Node *value3, Node *value4)
void ReturnIf (TNode< BoolT > condition, TNode< Object > value)
void AbortCSADcheck (Node *message)
void DebugBreak ()
void Unreachable ()
template<class... Args>
void Comment (MessageWithSourceLocation message, Args &&... args)
void StaticAssert (TNode< BoolT > value, const char *source=`unknown position`)
void SetSourcePosition (const char *file, int line)
void PushSourcePosition ()
void PopSourcePosition ()
const std::vector< FileAndLine > & GetMacroSourcePositionStack () const
void Bind (Label *label)
void Goto (Label *label)
void GotoIf (TNode< IntegralT > condition, Label *true_label, GotoHint goto_hint=GotoHint::kNone)
void GotoIfNot (TNode< IntegralT > condition, Label *false_label, GotoHint goto_hint=GotoHint::kNone)
void Branch (TNode< IntegralT > condition, Label *true_label, Label *false_label, BranchHint branch_hint=BranchHint::kNone)
template<class T >
TNode< T > Uninitialized ()
template<class... T>
void Bind (CodeAssemblerParameterizedLabel< T... > *label, TNode< T > *... phis)
template<class... T, class... Args>
void Branch (TNode< BoolT > condition, CodeAssemblerParameterizedLabel< T... > *if_true, CodeAssemblerParameterizedLabel< T... > *if_false, Args... args)
template<class... T, class... U>
void Branch (TNode< BoolT > condition, CodeAssemblerParameterizedLabel< T... > *if_true, std::vector< Node * > args_true, CodeAssemblerParameterizedLabel< U... > *if_false, std::vector< Node * > args_false)
template<class... T, class... Args>
void Goto (CodeAssemblerParameterizedLabel< T... > *label, Args... args)
void Branch (TNode< BoolT > condition, const std::function< void()> &true_body, const std::function< void()> &false_body)
void Branch (TNode< BoolT > condition, Label *true_label, const std::function< void()> &false_body)
void Branch (TNode< BoolT > condition, const std::function< void()> &true_body, Label *false_label)
void Switch (Node *index, Label *default_label, const int32_t *case_values, Label **case_labels, size_t case_count)
TNode< RawPtrT > LoadFramePointer ()
TNode< RawPtrT > LoadParentFramePointer ()
TNode< RawPtrT > StackSlotPtr (int size, int alignment)
TNode< Object > LoadTaggedFromRootRegister (TNode< IntPtrT > offset)
TNode< RawPtrT > LoadPointerFromRootRegister (TNode< IntPtrT > offset)
TNode< Uint8T > LoadUint8FromRootRegister (TNode< IntPtrT > offset)
Node * Load (MachineType type, Node *base)
template<class Type >
TNode< Type > Load (MachineType type, TNode< RawPtr< Type >> base)
Node * Load (MachineType type, Node *base, Node *offset)
template<class Type >
TNode< Type > Load (Node *base)
template<class Type >
TNode< Type > Load (Node *base, TNode< WordT > offset)
template<class Type >
TNode< Type > AtomicLoad (AtomicMemoryOrder order, TNode< RawPtrT > base, TNode< WordT > offset)
template<class Type >
TNode< Type > AtomicLoad64 (AtomicMemoryOrder order, TNode< RawPtrT > base, TNode< WordT > offset)
TNode< Object > LoadFullTagged (Node *base)
TNode< Object > LoadFullTagged (Node *base, TNode< IntPtrT > offset)
Node * LoadFromObject (MachineType type, TNode< Object > object, TNode< IntPtrT > offset)
Node * LoadProtectedPointerFromObject (TNode< Object > object, TNode< IntPtrT > offset)
TNode< Object > LoadRoot (RootIndex root_index)
TNode< AnyTaggedT > LoadRootMapWord (RootIndex root_index)
template<typename Type >
TNode< Type > UnalignedLoad (TNode< RawPtrT > base, TNode< IntPtrT > offset)
void Store (Node *base, Node *value)
void Store (Node *base, Node *offset, Node *value)
void StoreEphemeronKey (Node *base, Node *offset, Node *value)
void StoreNoWriteBarrier (MachineRepresentation rep, Node *base, Node *value)
void StoreNoWriteBarrier (MachineRepresentation rep, Node *base, Node *offset, Node *value)
void UnsafeStoreNoWriteBarrier (MachineRepresentation rep, Node *base, Node *value)
void UnsafeStoreNoWriteBarrier (MachineRepresentation rep, Node *base, Node *offset, Node *value)
void StoreFullTaggedNoWriteBarrier (TNode< RawPtrT > base, TNode< Object > tagged_value)
void StoreFullTaggedNoWriteBarrier (TNode< RawPtrT > base, TNode< IntPtrT > offset, TNode< Object > tagged_value)
TNode< HeapObject > OptimizedAllocate (TNode< IntPtrT > size, AllocationType allocation)
void StoreToObject (MachineRepresentation rep, TNode< Object > object, TNode< IntPtrT > offset, Node *value, StoreToObjectWriteBarrier write_barrier)
void OptimizedStoreField (MachineRepresentation rep, TNode< HeapObject > object, int offset, Node *value)
void OptimizedStoreIndirectPointerField (TNode< HeapObject > object, int offset, IndirectPointerTag tag, Node *value)
void OptimizedStoreIndirectPointerFieldNoWriteBarrier (TNode< HeapObject > object, int offset, IndirectPointerTag tag, Node *value)
void OptimizedStoreFieldAssertNoWriteBarrier (MachineRepresentation rep, TNode< HeapObject > object, int offset, Node *value)
void OptimizedStoreFieldUnsafeNoWriteBarrier (MachineRepresentation rep, TNode< HeapObject > object, int offset, Node *value)
void OptimizedStoreMap (TNode< HeapObject > object, TNode< Map >)
void AtomicStore (MachineRepresentation rep, AtomicMemoryOrder order, TNode< RawPtrT > base, TNode< WordT > offset, TNode< Word32T > value)
void AtomicStore64 (AtomicMemoryOrder order, TNode< RawPtrT > base, TNode< WordT > offset, TNode< UintPtrT > value, TNode< UintPtrT > value_high)
TNode< Word32T > AtomicAdd (MachineType type, TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< Word32T > value)
template<class Type >
TNode< Type > AtomicAdd64 (TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< UintPtrT > value, TNode< UintPtrT > value_high)
TNode< Word32T > AtomicSub (MachineType type, TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< Word32T > value)
template<class Type >
TNode< Type > AtomicSub64 (TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< UintPtrT > value, TNode< UintPtrT > value_high)
TNode< Word32T > AtomicAnd (MachineType type, TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< Word32T > value)
template<class Type >
TNode< Type > AtomicAnd64 (TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< UintPtrT > value, TNode< UintPtrT > value_high)
TNode< Word32T > AtomicOr (MachineType type, TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< Word32T > value)
template<class Type >
TNode< Type > AtomicOr64 (TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< UintPtrT > value, TNode< UintPtrT > value_high)
TNode< Word32T > AtomicXor (MachineType type, TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< Word32T > value)
template<class Type >
TNode< Type > AtomicXor64 (TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< UintPtrT > value, TNode< UintPtrT > value_high)
TNode< Word32T > AtomicExchange (MachineType type, TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< Word32T > value)
template<class Type >
TNode< Type > AtomicExchange64 (TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< UintPtrT > value, TNode< UintPtrT > value_high)
TNode< Word32T > AtomicCompareExchange (MachineType type, TNode< RawPtrT > base, TNode< WordT > offset, TNode< Word32T > old_value, TNode< Word32T > new_value)
template<class Type >
TNode< Type > AtomicCompareExchange64 (TNode< RawPtrT > base, TNode< WordT > offset, TNode< UintPtrT > old_value, TNode< UintPtrT > new_value, TNode< UintPtrT > old_value_high, TNode< UintPtrT > new_value_high)
void MemoryBarrier (AtomicMemoryOrder order)
void StoreRoot (RootIndex root_index, TNode< Object > value)
TNode< PairT< Word32T, Word32T > > Int32PairAdd (TNode< Word32T > lhs_lo_word, TNode< Word32T > lhs_hi_word, TNode< Word32T > rhs_lo_word, TNode< Word32T > rhs_hi_word)
TNode< PairT< Word32T, Word32T > > Int32PairSub (TNode< Word32T > lhs_lo_word, TNode< Word32T > lhs_hi_word, TNode< Word32T > rhs_lo_word, TNode< Word32T > rhs_hi_word)
TNode< UintPtrT > WordShr (TNode< UintPtrT > left, TNode< IntegralT > right)
TNode< IntPtrT > WordSar (TNode< IntPtrT > left, TNode< IntegralT > right)
TNode< IntPtrT > WordShl (TNode< IntPtrT > left, TNode< IntegralT > right)
TNode< UintPtrT > WordShl (TNode< UintPtrT > left, TNode< IntegralT > right)
TNode< Int32T > Word32Shl (TNode< Int32T > left, TNode< Int32T > right)
TNode< Uint32T > Word32Shl (TNode< Uint32T > left, TNode< Uint32T > right)
TNode< Uint32T > Word32Shr (TNode< Uint32T > left, TNode< Uint32T > right)
TNode< Int32T > Word32Sar (TNode< Int32T > left, TNode< Int32T > right)
TNode< Int64T > Word64Shl (TNode< Int64T > left, TNode< Int64T > right)
TNode< Uint64T > Word64Shl (TNode< Uint64T > left, TNode< Uint64T > right)
TNode< Int64T > Word64Shr (TNode< Int64T > left, TNode< Uint64T > right)
TNode< Uint64T > Word64Shr (TNode< Uint64T > left, TNode< Uint64T > right)
TNode< Int64T > Word64Sar (TNode< Int64T > left, TNode< Int64T > right)
TNode< Int64T > Word64And (TNode< Int64T > left, TNode< Int64T > right)
TNode< Uint64T > Word64And (TNode< Uint64T > left, TNode< Uint64T > right)
TNode< Int64T > Word64Xor (TNode< Int64T > left, TNode< Int64T > right)
TNode< Uint64T > Word64Xor (TNode< Uint64T > left, TNode< Uint64T > right)
TNode< Int64T > Word64Not (TNode< Int64T > value)
TNode< Uint64T > Word64Not (TNode< Uint64T > value)
TNode< IntPtrT > WordAnd (TNode< IntPtrT > left, TNode< IntPtrT > right)
TNode< UintPtrT > WordAnd (TNode< UintPtrT > left, TNode< UintPtrT > right)
TNode< Int32T > Word32And (TNode< Int32T > left, TNode< Int32T > right)
TNode< Uint32T > Word32And (TNode< Uint32T > left, TNode< Uint32T > right)
TNode< IntPtrT > WordOr (TNode< IntPtrT > left, TNode< IntPtrT > right)
TNode< Int32T > Word32Or (TNode< Int32T > left, TNode< Int32T > right)
TNode< Uint32T > Word32Or (TNode< Uint32T > left, TNode< Uint32T > right)
TNode< BoolT > IntPtrEqual (TNode< WordT > left, TNode< WordT > right)
TNode< BoolT > WordEqual (TNode< WordT > left, TNode< WordT > right)
TNode< BoolT > WordNotEqual (TNode< WordT > left, TNode< WordT > right)
TNode< BoolT > Word32Equal (TNode< Word32T > left, TNode< Word32T > right)
TNode< BoolT > Word32NotEqual (TNode< Word32T > left, TNode< Word32T > right)
TNode< BoolT > Word64Equal (TNode< Word64T > left, TNode< Word64T > right)
TNode< BoolT > Word64NotEqual (TNode< Word64T > left, TNode< Word64T > right)
TNode< IntPtrT > WordNot (TNode< IntPtrT > a)
TNode< Int32T > Word32BitwiseNot (TNode< Int32T > a)
TNode< BoolT > Word32Or (TNode< BoolT > left, TNode< BoolT > right)
TNode< BoolT > Word32And (TNode< BoolT > left, TNode< BoolT > right)
TNode< Int32T > Int32Add (TNode< Int32T > left, TNode< Int32T > right)
TNode< Uint32T > Uint32Add (TNode< Uint32T > left, TNode< Uint32T > right)
TNode< Uint32T > Uint32Sub (TNode< Uint32T > left, TNode< Uint32T > right)
TNode< Int32T > Int32Sub (TNode< Int32T > left, TNode< Int32T > right)
TNode< Int32T > Int32Mul (TNode< Int32T > left, TNode< Int32T > right)
TNode< Uint32T > Uint32Mul (TNode< Uint32T > left, TNode< Uint32T > right)
TNode< Int64T > Int64Add (TNode< Int64T > left, TNode< Int64T > right)
TNode< Uint64T > Uint64Add (TNode< Uint64T > left, TNode< Uint64T > right)
TNode< Int64T > Int64Sub (TNode< Int64T > left, TNode< Int64T > right)
TNode< Uint64T > Uint64Sub (TNode< Uint64T > left, TNode< Uint64T > right)
TNode< Int64T > Int64Mul (TNode< Int64T > left, TNode< Int64T > right)
TNode< Uint64T > Uint64Mul (TNode< Uint64T > left, TNode< Uint64T > right)
TNode< IntPtrT > IntPtrAdd (TNode< IntPtrT > left, TNode< IntPtrT > right)
TNode< IntPtrT > IntPtrSub (TNode< IntPtrT > left, TNode< IntPtrT > right)
TNode< IntPtrT > IntPtrMul (TNode< IntPtrT > left, TNode< IntPtrT > right)
TNode< UintPtrT > UintPtrAdd (TNode< UintPtrT > left, TNode< UintPtrT > right)
TNode< UintPtrT > UintPtrSub (TNode< UintPtrT > left, TNode< UintPtrT > right)
TNode< RawPtrT > RawPtrAdd (TNode< RawPtrT > left, TNode< IntPtrT > right)
TNode< RawPtrT > RawPtrSub (TNode< RawPtrT > left, TNode< IntPtrT > right)
TNode< IntPtrT > RawPtrSub (TNode< RawPtrT > left, TNode< RawPtrT > right)
TNode< WordT > WordShl (TNode< WordT > value, int shift)
TNode< WordT > WordShr (TNode< WordT > value, int shift)
TNode< WordT > WordSar (TNode< WordT > value, int shift)
TNode< IntPtrT > WordShr (TNode< IntPtrT > value, int shift)
TNode< IntPtrT > WordSar (TNode< IntPtrT > value, int shift)
TNode< Word32T > Word32Shr (TNode< Word32T > value, int shift)
TNode< Word32T > Word32Sar (TNode< Word32T > value, int shift)
TNode< Int32T > Int32Sub (TNode< Int32T > left, int right)
TNode< Word32T > Word32And (TNode< Word32T > left, int right)
TNode< Int32T > Word32Shl (TNode< Int32T > left, int right)
TNode< BoolT > Word32Equal (TNode< Word32T > left, int right)
template<class Dummy = void>
TNode< IntPtrT > BitcastTaggedToWord (TNode< Smi > node)
TNode< IntPtrT > ChangeFloat64ToIntPtr (TNode< Float64T > value)
TNode< UintPtrT > ChangeFloat64ToUintPtr (TNode< Float64T > value)
TNode< Float64T > ChangeUintPtrToFloat64 (TNode< UintPtrT > value)
TNode< Float64T > RoundIntPtrToFloat64 (Node *value)
TNode< UintPtrT > ChangeUint32ToWord (TNode< Word32T > value)
TNode< IntPtrT > ChangeInt32ToIntPtr (TNode< Word32T > value)
TNode< Int32T > TruncateFloat32ToInt32 (TNode< Float32T > value)
TNode< Int64T > TruncateFloat64ToInt64 (TNode< Float64T > value)
template<int index, class T1 , class T2 >
TNode< std::tuple_element_t< index, std::tuple< T1, T2 > > > Projection (TNode< PairT< T1, T2 >> value)
template<class T = Object, class... TArgs>
TNode< T > CallRuntime (Runtime::FunctionId function, TNode< Object > context, TArgs... args)
template<class... TArgs>
void TailCallRuntime (Runtime::FunctionId function, TNode< Object > context, TArgs... args)
template<class... TArgs>
void TailCallRuntime (Runtime::FunctionId function, TNode< Int32T > arity, TNode< Object > context, TArgs... args)
Builtin builtin ()
TNode< RawPtrT > SwitchToTheCentralStackIfNeeded ()
TNode< RawPtrT > SwitchToTheCentralStack ()
void SwitchFromTheCentralStack (TNode< RawPtrT > old_sp)
template<typename T = Object, class... TArgs>
TNode< T > CallBuiltin (Builtin id, TNode< Object > context, TArgs... args)
template<class... TArgs>
void CallBuiltinVoid (Builtin id, TNode< Object > context, TArgs... args)
template<class... TArgs>
void TailCallBuiltin (Builtin id, TNode< Object > context, TArgs... args)
template<class T = Object, class... TArgs>
TNode< T > CallStub (const CallInterfaceDescriptor &descriptor, TNode< Code > target, TNode< Object > context, TArgs... args)
template<class T = Object, class... TArgs>
TNode< T > CallBuiltinPointer (const CallInterfaceDescriptor &descriptor, TNode< BuiltinPtr > target, TNode< Object > context, TArgs... args)
template<class... TArgs>
void TailCallStub (const CallInterfaceDescriptor &descriptor, TNode< Code > target, TNode< Object > context, TArgs... args)
template<class... TArgs>
void TailCallBytecodeDispatch (const CallInterfaceDescriptor &descriptor, TNode< RawPtrT > target, TArgs... args)
template<class... TArgs>
void TailCallBuiltinThenBytecodeDispatch (Builtin builtin, Node *context, TArgs... args)
template<class... TArgs>
TNode< Object > CallJSBuiltin (Builtin builtin, TNode< Context > context, TNode< Object > function, std::optional< TNode< Object >> new_target, TNode< Object > receiver, TArgs... args)
void TailCallJSBuiltin (Builtin id, TNode< Object > context, TNode< Object > function, TNode< Object > new_target, TNode< Int32T > arg_count, TNode< JSDispatchHandleT > dispatch_handle)
template<class... TArgs>
TNode< JSAny > CallJS (Builtin builtin, TNode< Context > context, TNode< Object > function, TNode< JSAny > receiver, TArgs... args)
template<class... TArgs>
TNode< JSAny > ConstructJS (Builtin builtin, TNode< Context > context, TNode< Object > function, TNode< JSAny > new_target, TArgs... args)
void TailCallJSCode (TNode< Code > code, TNode< Context > context, TNode< JSFunction > function, TNode< Object > new_target, TNode< Int32T > arg_count, TNode< JSDispatchHandleT > dispatch_handle)
Node * CallCFunctionN (Signature< MachineType > *signature, int input_count, Node *const *inputs)
template<class... CArgs>
Node * CallCFunction (Node *function, std::optional< MachineType > return_type, CArgs... cargs)
template<class... CArgs>
Node * CallCFunctionWithoutFunctionDescriptor (Node *function, MachineType return_type, CArgs... cargs)
template<class... CArgs>
Node * CallCFunctionWithCallerSavedRegisters (Node *function, MachineType return_type, SaveFPRegsMode mode, CArgs... cargs)
Factory * factory () const
Isolate * isolate () const
Zone * zone () const
CodeAssemblerState * state ()
void BreakOnNode (int node_id)
bool UnalignedLoadSupported (MachineRepresentation rep) const
bool UnalignedStoreSupported (MachineRepresentation rep) const
bool IsExceptionHandlerActive () const
Static Public Attributes
static constexpr int kTargetParameterIndex = kJSCallClosureParameterIndex
Protected Member Functions
void RegisterCallGenerationCallbacks (const CodeAssemblerCallback &call_prologue, const CodeAssemblerCallback &call_epilogue)
void UnregisterCallGenerationCallbacks ()
bool Word32ShiftIsSafe () const
bool IsJSFunctionCall () const
Private Member Functions
void HandleException (Node *result)
Node * CallCFunction (Node *function, std::optional< MachineType > return_type, std::initializer_list< CFunctionArg > args)
Node * CallCFunctionWithoutFunctionDescriptor (Node *function, MachineType return_type, std::initializer_list< CFunctionArg > args)
Node * CallCFunctionWithCallerSavedRegisters (Node *function, MachineType return_type, SaveFPRegsMode mode, std::initializer_list< CFunctionArg > args)
Node * CallRuntimeImpl (Runtime::FunctionId function, TNode< Object > context, std::initializer_list< TNode< Object >> args)
void TailCallRuntimeImpl (Runtime::FunctionId function, TNode< Int32T > arity, TNode< Object > context, std::initializer_list< TNode< Object >> args)
void TailCallStubImpl (const CallInterfaceDescriptor &descriptor, TNode< Code > target, TNode< Object > context, std::initializer_list< Node * > args)
void TailCallStubThenBytecodeDispatchImpl (const CallInterfaceDescriptor &descriptor, Node *target, Node *context, std::initializer_list< Node * > args)
template<class... TArgs>
Node * CallStubR (StubCallMode call_mode, const CallInterfaceDescriptor &descriptor, TNode< Object > target, TNode< Object > context, TArgs... args)
Node * CallStubRImpl (StubCallMode call_mode, const CallInterfaceDescriptor &descriptor, TNode< Object > target, TNode< Object > context, std::initializer_list< Node * > args)
Node * CallJSStubImpl (const CallInterfaceDescriptor &descriptor, TNode< Object > target, TNode< Object > context, TNode< Object > function, std::optional< TNode< Object >> new_target, TNode< Int32T > arity, std::optional< TNode< JSDispatchHandleT >> dispatch_handle, std::initializer_list< Node * > args)
Node * CallStubN (StubCallMode call_mode, const CallInterfaceDescriptor &descriptor, int input_count, Node *const *inputs)
Node * AtomicLoad (MachineType type, AtomicMemoryOrder order, TNode< RawPtrT > base, TNode< WordT > offset)
Node * UnalignedLoad (MachineType type, TNode< RawPtrT > base, TNode< WordT > offset)
void EmitComment (std::string msg)
TNode< Int32T > Signed (TNode< Int32T > x)
TNode< Uint32T > Unsigned (TNode< Uint32T > x)
Node * Projection (int index, Node *value)
RawMachineAssembler * raw_assembler () const
JSGraph * jsgraph () const
void CallPrologue ()
void CallEpilogue ()
Private Attributes
CodeAssemblerState * state_
Detailed Description
Definition at line 391 of file code-assembler.h.
Member Typedef Documentation
CFunctionArg
using v8::internal::compiler::CodeAssembler::CFunctionArg = std::pair<MachineType, Node*>
Definition at line 1539 of file code-assembler.h.
Label
using v8::internal::compiler::CodeAssembler::Label = CodeAssemblerLabel
Definition at line 471 of file code-assembler.h.
TVariable
template<class T >
using v8::internal::compiler::CodeAssembler::TVariable = TypedCodeAssemblerVariable<T>
Definition at line 473 of file code-assembler.h.
VariableList
using v8::internal::compiler::CodeAssembler::VariableList = CodeAssemblerVariableList
Definition at line 474 of file code-assembler.h.
Constructor & Destructor Documentation
CodeAssembler() [1/2]
v8::internal::compiler::CodeAssembler::CodeAssembler (CodeAssemblerState * state) [inline], [explicit]
Definition at line 393 of file code-assembler.h.
: state_(state) {}
 CodeAssembler()
v8::internal::compiler::CodeAssembler::~CodeAssembler () [default]
CodeAssembler() [2/2]
v8::internal::compiler::CodeAssembler::CodeAssembler (const CodeAssembler &) [delete]
Member Function Documentation
AbortCSADcheck()
void v8::internal::compiler::CodeAssembler::AbortCSADcheck (Node * message)
Definition at line 653 of file code-assembler.cc.
                                                {
  raw_assembler()->AbortCSADcheck(message);
}
References v8::internal::compiler::RawMachineAssembler::AbortCSADcheck(), and raw_assembler().
Referenced by v8::internal::CodeStubAssembler::FailAssert().
AtomicAdd()
TNode<Word32T> v8::internal::compiler::CodeAssembler::AtomicAdd (MachineType type, TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< Word32T > value)
AtomicAdd64()
template<class Type >
TNode<Type> v8::internal::compiler::CodeAssembler::AtomicAdd64 (TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< UintPtrT > value, TNode< UintPtrT > value_high)
AtomicAnd()
TNode<Word32T> v8::internal::compiler::CodeAssembler::AtomicAnd (MachineType type, TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< Word32T > value)
AtomicAnd64()
template<class Type >
TNode<Type> v8::internal::compiler::CodeAssembler::AtomicAnd64 (TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< UintPtrT > value, TNode< UintPtrT > value_high)
AtomicCompareExchange()
TNode< Word32T > v8::internal::compiler::CodeAssembler::AtomicCompareExchange (MachineType type, TNode< RawPtrT > base, TNode< WordT > offset, TNode< Word32T > old_value, TNode< Word32T > new_value)
Definition at line 1122 of file code-assembler.cc.
                                                                              {
  return UncheckedCast<Word32T>(raw_assembler()->AtomicCompareExchange(
      type, base, offset, old_value, new_value));
}
References raw_assembler(), and v8::internal::tracing::type.
AtomicCompareExchange64()
template<class Type >
template TNode< AtomicUint64 > v8::internal::compiler::CodeAssembler::AtomicCompareExchange64< AtomicUint64 > (TNode< RawPtrT > base, TNode< WordT > offset, TNode< UintPtrT > old_value, TNode< UintPtrT > new_value, TNode< UintPtrT > old_value_high, TNode< UintPtrT > new_value_high)
Definition at line 1132 of file code-assembler.cc.
                                    {
  // This uses Uint64() intentionally: AtomicCompareExchange is not implemented
  // for Int64(), which is fine because the machine instruction only cares
  // about words.
  return UncheckedCast<Type>(raw_assembler()->AtomicCompareExchange64(
      base, offset, old_value, old_value_high, new_value, new_value_high));
}
References raw_assembler().
AtomicExchange()
TNode<Word32T> v8::internal::compiler::CodeAssembler::AtomicExchange (MachineType type, TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< Word32T > value)
AtomicExchange64()
template<class Type >
TNode<Type> v8::internal::compiler::CodeAssembler::AtomicExchange64 (TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< UintPtrT > value, TNode< UintPtrT > value_high)
AtomicLoad() [1/2]
template<class Type >
TNode<Type> v8::internal::compiler::CodeAssembler::AtomicLoad (AtomicMemoryOrder order, TNode< RawPtrT > base, TNode< WordT > offset) [inline]
Definition at line 879 of file code-assembler.h.
                                              {
    return UncheckedCast<Type>(
        AtomicLoad(MachineTypeOf<Type>::value, order, base, offset));
  }
AtomicLoad() [2/2]
Node * v8::internal::compiler::CodeAssembler::AtomicLoad (MachineType type, AtomicMemoryOrder order, TNode< RawPtrT > base, TNode< WordT > offset) [private]
Definition at line 873 of file code-assembler.cc.
                                                                          {
  DCHECK(!raw_assembler()->IsMapOffsetConstantMinusTag(offset));
  return raw_assembler()->AtomicLoad(AtomicLoadParameters(type, order), base,
                                     offset);
}
References v8::internal::compiler::RawMachineAssembler::AtomicLoad(), v8::internal::DCHECK(), raw_assembler(), and v8::internal::tracing::type.
AtomicLoad64()
template<class Type >
template TNode< AtomicUint64 > v8::internal::compiler::CodeAssembler::AtomicLoad64< AtomicUint64 > (AtomicMemoryOrder order, TNode< RawPtrT > base, TNode< WordT > offset)
Definition at line 881 of file code-assembler.cc.
                                                             {
  return UncheckedCast<Type>(raw_assembler()->AtomicLoad64(
      AtomicLoadParameters(MachineType::Uint64(), order), base, offset));
}
References raw_assembler(), and v8::internal::MachineType::Uint64().
AtomicOr()
TNode<Word32T> v8::internal::compiler::CodeAssembler::AtomicOr (MachineType type, TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< Word32T > value)
AtomicOr64()
template<class Type >
TNode<Type> v8::internal::compiler::CodeAssembler::AtomicOr64 (TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< UintPtrT > value, TNode< UintPtrT > value_high)
AtomicStore()
void v8::internal::compiler::CodeAssembler::AtomicStore (MachineRepresentation rep, AtomicMemoryOrder order, TNode< RawPtrT > base, TNode< WordT > offset, TNode< Word32T > value)
Definition at line 1076 of file code-assembler.cc.
                                                                           {
  DCHECK(!raw_assembler()->IsMapOffsetConstantMinusTag(offset));
  raw_assembler()->AtomicStore(
      AtomicStoreParameters(rep, WriteBarrierKind::kNoWriteBarrier, order),
      base, offset, value);
}
References v8::internal::compiler::RawMachineAssembler::AtomicStore(), v8::internal::DCHECK(), v8::internal::compiler::kNoWriteBarrier, raw_assembler(), and v8::internal::value.
AtomicStore64()
void v8::internal::compiler::CodeAssembler::AtomicStore64 (AtomicMemoryOrder order, TNode< RawPtrT > base, TNode< WordT > offset, TNode< UintPtrT > value, TNode< UintPtrT > value_high)
Definition at line 1085 of file code-assembler.cc.
                                                              {
  raw_assembler()->AtomicStore64(
      AtomicStoreParameters(MachineRepresentation::kWord64,
                            WriteBarrierKind::kNoWriteBarrier, order),
      base, offset, value, value_high);
}
References v8::internal::compiler::RawMachineAssembler::AtomicStore64(), v8::internal::compiler::kNoWriteBarrier, v8::internal::kWord64, raw_assembler(), and v8::internal::value.
AtomicSub()
TNode<Word32T> v8::internal::compiler::CodeAssembler::AtomicSub (MachineType type, TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< Word32T > value)
AtomicSub64()
template<class Type >
TNode<Type> v8::internal::compiler::CodeAssembler::AtomicSub64 (TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< UintPtrT > value, TNode< UintPtrT > value_high)
AtomicXor()
TNode<Word32T> v8::internal::compiler::CodeAssembler::AtomicXor (MachineType type, TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< Word32T > value)
AtomicXor64()
template<class Type >
TNode<Type> v8::internal::compiler::CodeAssembler::AtomicXor64 (TNode< RawPtrT > base, TNode< UintPtrT > offset, TNode< UintPtrT > value, TNode< UintPtrT > value_high)
Bind() [1/2]
template<class... T>
void v8::internal::compiler::CodeAssembler::Bind (CodeAssemblerParameterizedLabel< T... > * label, TNode< T > *... phis) [inline]
Definition at line 807 of file code-assembler.h.
                                                                             {
    Bind(label->plain_label());
    label->CreatePhis(phis...);
  }
References v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::CreatePhis(), and v8::internal::compiler::CodeAssemblerParameterizedLabelBase::plain_label().
Bind() [2/2]
void v8::internal::compiler::CodeAssembler::Bind (Label * label)
Definition at line 688 of file code-assembler.cc.
{ return label->Bind(); }
References v8::internal::compiler::CodeAssemblerLabel::Bind().
Referenced by Branch(), GotoIf(), GotoIfNot(), HandleException(), ReturnIf(), and v8::internal::compiler::ScopedExceptionHandler::~ScopedExceptionHandler().
BitcastTaggedToWord()
template<class Dummy = void>
TNode<IntPtrT> v8::internal::compiler::CodeAssembler::BitcastTaggedToWord (TNode< Smi > node) [inline]
Definition at line 1270 of file code-assembler.h.
                                                      {
    static_assert(sizeof(Dummy) < 0,
                  "Should use BitcastTaggedToWordForTagAndSmiBits instead.");
  }
References v8::Dummy().
Referenced by v8::internal::StringBuiltinsAssembler::AllocAndCopyStringCharacters(), v8::internal::CodeStubAssembler::AllocateNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::AllocateOrderedHashTableWithCapacity(), v8::internal::CodeStubAssembler::AllocateSimpleNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::BranchIfToBooleanIsTrue(), v8::internal::CodeStubAssembler::CopyElements(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::StringBuiltinsAssembler::DirectStringData(), v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), v8::internal::CodeStubAssembler::ExtractFixedDoubleArrayFillingHoles(), v8::internal::CodeStubAssembler::ExtractToFixedArray(), v8::internal::CodeStubAssembler::FillFixedArrayWithSmiZero(), v8::internal::CodeStubAssembler::FillFixedDoubleArrayWithZero(), v8::internal::WriteBarrierCodeStubAssembler::GenerateEphemeronKeyBarrier(), v8::internal::WriteBarrierCodeStubAssembler::GenerationalBarrierSlow(), v8::internal::WriteBarrierCodeStubAssembler::GenerationalOrSharedBarrierDuringMarking(), v8::internal::WriteBarrierCodeStubAssembler::GenerationalOrSharedBarrierSlow(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrier(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierMajor(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierMinor(), v8::internal::WriteBarrierCodeStubAssembler::IndirectPointerWriteBarrier(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::InnerAllocateElements(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::InnerAllocateMemento(), v8::internal::WasmBuiltinsAssembler::InSharedSpace(), v8::internal::CodeStubAssembler::IsExternalStringMap(), v8::internal::CodeStubAssembler::IsOneByteStringMap(), v8::internal::CodeStubAssembler::IsSeqOneByteStringMap(), v8::internal::CodeStubAssembler::IsSequentialStringMap(), v8::internal::CodeStubAssembler::IsString(), v8::internal::CodeStubAssembler::IsUncachedExternalStringMap(), v8::internal::WriteBarrierCodeStubAssembler::IsValueUnmarkedOrRecordSlot(), v8::internal::CodeStubAssembler::IsWeakReferenceTo(), v8::internal::CodeStubAssembler::IsWeakReferenceToObject(), v8::internal::CodeStubAssembler::JSAnyIsNotPrimitiveMap(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMemoryChunkFlags(), v8::internal::CodeStubAssembler::MakeWeak(), v8::internal::CodeStubAssembler::MoveElements(), v8::internal::IntlBuiltinsAssembler::PointerToSeqStringData(), v8::internal::TypedArrayBuiltinsAssembler::SetJSTypedArrayOnHeapDataPtr(), v8::internal::WriteBarrierCodeStubAssembler::SharedBarrierSlow(), StoreFullTaggedNoWriteBarrier(), v8::internal::AccessorAssembler::StubCachePrimaryOffset(), v8::internal::AccessorAssembler::StubCacheSecondaryOffset(), v8::internal::CodeStubAssembler::TrySkipWriteBarrier(), v8::internal::ToDirectStringAssembler::TryToDirect(), and v8::internal::ToDirectStringAssembler::TryToSequential().
BoolConstant()
TNode<BoolT> v8::internal::compiler::CodeAssembler::BoolConstant (bool value) [inline]
Definition at line 646 of file code-assembler.h.
                                        {
    return value ? Int32TrueConstant() : Int32FalseConstant();
  }
References v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::Float64AlmostEqual(), v8::internal::BinaryOpAssembler::Generate_AddWithFeedback(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::WriteBarrierCodeStubAssembler::InYoungGeneration(), v8::internal::CodeStubAssembler::IsAdditiveSafeInteger(), v8::internal::KeyedStoreGenericAssembler::KeyedStoreGeneric(), and v8::internal::CodeStubAssembler::WordIsPowerOfTwo().
BooleanConstant()
TNode< Boolean > v8::internal::compiler::CodeAssembler::BooleanConstant (bool value)
Definition at line 391 of file code-assembler.cc.
                                                        {
  Handle<Boolean> object = isolate()->factory()->ToBoolean(value);
  return UncheckedCast<Boolean>(
      jsgraph()->HeapConstantNoHole(i::Cast<HeapObject>(object)));
}
References v8::internal::Isolate::factory(), HeapConstantNoHole(), isolate(), jsgraph(), v8::internal::FactoryBase< Impl >::ToBoolean(), and v8::internal::value.
Branch() [1/6]
template<class... T, class... Args>
void v8::internal::compiler::CodeAssembler::Branch (TNode< BoolT > condition, CodeAssemblerParameterizedLabel< T... > * if_true, CodeAssemblerParameterizedLabel< T... > * if_false, Args... args) [inline]
Definition at line 812 of file code-assembler.h.
                                                                             {
    if_true->AddInputs(args...);
    if_false->AddInputs(args...);
    Branch(condition, if_true->plain_label(), if_false->plain_label());
  }
References v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::AddInputs(), v8::base::args, and v8::internal::compiler::CodeAssemblerParameterizedLabelBase::plain_label().
Branch() [2/6]
template<class... T, class... U>
void v8::internal::compiler::CodeAssembler::Branch (TNode< BoolT > condition, CodeAssemblerParameterizedLabel< T... > * if_true, std::vector< Node * > args_true, CodeAssemblerParameterizedLabel< U... > * if_false, std::vector< Node * > args_false) [inline]
Definition at line 820 of file code-assembler.h.
                                           {
    if_true->AddInputsVector(std::move(args_true));
    if_false->AddInputsVector(std::move(args_false));
    Branch(condition, if_true->plain_label(), if_false->plain_label());
  }
References v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::AddInputsVector(), and v8::internal::compiler::CodeAssemblerParameterizedLabelBase::plain_label().
Branch() [3/6]
void v8::internal::compiler::CodeAssembler::Branch (TNode< BoolT > condition, const std::function< void()> & true_body, const std::function< void()> & false_body)
Definition at line 1602 of file code-assembler.cc.
                                                                  {
  int32_t constant;
  if (TryToInt32Constant(condition, &constant)) {
    return constant ? true_body() : false_body();
  }
  Label vtrue(this), vfalse(this);
  Branch(condition, &vtrue, &vfalse);
  Bind(&vtrue);
  true_body();
  Bind(&vfalse);
  false_body();
}
References Bind(), Branch(), and TryToInt32Constant().
Branch() [4/6]
void v8::internal::compiler::CodeAssembler::Branch (TNode< BoolT > condition, const std::function< void()> & true_body, Label * false_label)
Definition at line 1633 of file code-assembler.cc.
                                               {
  int32_t constant;
  if (TryToInt32Constant(condition, &constant)) {
    return constant ? true_body() : Goto(false_label);
  }
  Label vtrue(this);
  Branch(condition, &vtrue, false_label);
  Bind(&vtrue);
  true_body();
}
References Bind(), Branch(), Goto(), and TryToInt32Constant().
Branch() [5/6]
void v8::internal::compiler::CodeAssembler::Branch (TNode< BoolT > condition, Label * true_label, const std::function< void()> & false_body)
Definition at line 1620 of file code-assembler.cc.
                                                                  {
  int32_t constant;
  if (TryToInt32Constant(condition, &constant)) {
    return constant ? Goto(true_label) : false_body();
  }
  Label vfalse(this);
  Branch(condition, true_label, &vfalse);
  Bind(&vfalse);
  false_body();
}
References Bind(), Branch(), Goto(), and TryToInt32Constant().
Branch() [6/6]
void v8::internal::compiler::CodeAssembler::Branch (TNode< IntegralT > condition, Label * true_label, Label * false_label, BranchHint branch_hint = BranchHint::kNone)
Definition at line 1587 of file code-assembler.cc.
                                                                       {
  int32_t constant;
  if (TryToInt32Constant(condition, &constant)) {
    if ((true_label->is_used() || true_label->is_bound()) &&
        (false_label->is_used() || false_label->is_bound())) {
      return Goto(constant ? true_label : false_label);
    }
  }
  true_label->MergeVariables();
  false_label->MergeVariables();
  return raw_assembler()->Branch(condition, true_label->label_,
                                 false_label->label_, branch_hint);
}
References v8::internal::compiler::RawMachineAssembler::Branch(), Goto(), v8::internal::compiler::CodeAssemblerLabel::is_bound(), v8::internal::compiler::CodeAssemblerLabel::is_used(), v8::internal::compiler::CodeAssemblerLabel::label_, v8::internal::compiler::CodeAssemblerLabel::MergeVariables(), raw_assembler(), and TryToInt32Constant().
Referenced by v8::internal::interpreter::InterpreterAssembler::AbortIfRegisterCountInvalid(), v8::internal::interpreter::InterpreterAssembler::AbortIfWordNotEqual(), v8::internal::BaseCollectionsAssembler::AddConstructorEntries(), v8::internal::BaseCollectionsAssembler::AddConstructorEntriesFromFastJSArray(), v8::internal::CollectionsBuiltinsAssembler::AddConstructorEntriesFromSet(), v8::internal::CollectionsBuiltinsAssembler::AddValueToKeyedGroup(), v8::internal::RegExpBuiltinsAssembler::AdvanceStringIndex(), v8::internal::CodeStubAssembler::AlignToAllocationAlignment(), v8::internal::StringBuiltinsAssembler::AllocAndCopyStringCharacters(), v8::internal::CodeStubAssembler::AllocateArrayList(), v8::internal::CodeStubAssembler::AllocateByteArray(), v8::internal::CodeStubAssembler::AllocateFixedArray(), v8::internal::CodeStubAssembler::AllocateJSArray(), v8::internal::ProxiesCodeStubAssembler::AllocateProxy(), v8::internal::CodeStubAssembler::AllocateRaw(), v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::AllocateUninitializedJSArrayWithElements(), v8::internal::AsyncBuiltinsAssembler::Await(), v8::internal::CodeStubAssembler::BigIntFromInt32Pair(), v8::internal::CodeStubAssembler::BigIntFromInt64(), Branch(), v8::internal::CodeStubAssembler::BranchIfHasPrototypeProperty(), v8::internal::CollectionsBuiltinsAssembler::BranchIfIterableWithOriginalKeyOrValueMapIterator(), v8::internal::CollectionsBuiltinsAssembler::BranchIfIterableWithOriginalValueSetIterator(), v8::internal::CodeStubAssembler::BranchIfJSReceiver(), v8::internal::CollectionsBuiltinsAssembler::BranchIfMapIteratorProtectorValid(), v8::internal::AccessorAssembler::BranchIfPrototypesHaveNoElements(), v8::internal::RegExpBuiltinsAssembler::BranchIfRegExpResult(), v8::internal::CollectionsBuiltinsAssembler::BranchIfSetIteratorProtectorValid(), v8::internal::StringBuiltinsAssembler::BranchIfStringPrimitiveWithNoCustomIteration(), v8::internal::CodeStubAssembler::BranchIfToBooleanIsTrue(), v8::internal::CallOrConstructBuiltinsAssembler::CallFunctionTemplate(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithArrayLike(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithSpread(), v8::internal::CodeStubAssembler::ChangeInt32ToTagged(), v8::internal::CodeStubAssembler::ChangeNonNegativeNumberToUint32(), v8::internal::CodeStubAssembler::ChangeUint32ToTagged(), v8::internal::CodeStubAssembler::ChangeUintPtrToTagged(), v8::internal::CodeStubAssembler::Check(), v8::internal::PrototypeCheckAssembler::CheckAndBranch(), v8::internal::CodeStubAssembler::CheckEnumCache(), v8::internal::AccessorAssembler::CheckFieldType(), v8::internal::AccessorAssembler::CheckHeapObjectTypeMatchesDescriptor(), v8::internal::CodeStubAssembler::CheckPrototypeEnumCache(), v8::internal::AccessorAssembler::CheckPrototypeValidityCell(), v8::internal::ArrayPopulatorAssembler::ConstructArrayLike(), v8::internal::RegExpBuiltinsAssembler::ConstructNewResultFromMatchInfo(), v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::ConstructorBuiltinsAssembler::CopyMutableHeapNumbersInObject(), v8::internal::ConstructorBuiltinsAssembler::CreateShallowObjectLiteral(), v8::internal::interpreter::InterpreterAssembler::DecreaseInterruptBudget(), v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::StringBuiltinsAssembler::DirectStringData(), v8::internal::AccessorAssembler::EmitAccessCheck(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::KeyedStoreGenericAssembler::EmitGenericElementStore(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::CodeStubAssembler::ExtractFixedDoubleArrayFillingHoles(), v8::internal::CodeStubAssembler::ExtractToFixedArray(), v8::internal::CodeStubAssembler::FastCheck(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FastGetOwnValuesOrEntries(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForOtherKey(), v8::internal::CodeStubAssembler::Float64Ceil(), v8::internal::CodeStubAssembler::Float64Floor(), v8::internal::CodeStubAssembler::Float64RoundToEven(), v8::internal::CodeStubAssembler::Float64Trunc(), v8::internal::ArrayIncludesIndexofAssembler::Generate(), v8::internal::BinaryOpAssembler::Generate_AddWithFeedback(), v8::internal::BinaryOpAssembler::Generate_BinaryOperationWithFeedback(), v8::internal::BinaryOpAssembler::Generate_BitwiseBinaryOpWithSmiOperandAndOptionalFeedback(), v8::internal::DateBuiltinsAssembler::Generate_IsDateCheck(), v8::internal::ArrayBuiltinsAssembler::GenerateConstructor(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::ArrayBuiltinsAssembler::GenerateIteratingTypedArrayBuiltinBody(), v8::internal::ArrayIncludesIndexofAssembler::GeneratePackedDoubles(), v8::internal::StringBuiltinsAssembler::GenerateSeqStringRelationalComparison(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::StringBuiltinsAssembler::GenerateStringRelationalComparison(), v8::internal::AccessorAssembler::GenericElementLoad(), v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::CallOrConstructBuiltinsAssembler::GetCompatibleReceiver(), v8::internal::interpreter::InterpreterAssembler::GetContextAtDepth(), v8::internal::CollectionsBuiltinsAssembler::GetHash(), v8::internal::IteratorBuiltinsAssembler::GetIterator(), v8::internal::CodeStubAssembler::GetNonRabGsabElementsKind(), v8::internal::StringBuiltinsAssembler::GetSubstitution(), GotoIf(), v8::internal::CodeStubAssembler::GotoIfForceSlowPath(), v8::internal::CodeStubAssembler::GotoIfLargeBigInt(), GotoIfNot(), v8::internal::AccessorAssembler::HandleLoadICHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICProtoHandler(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerHasNamedCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), v8::internal::AccessorAssembler::HandlePolymorphicCase(), v8::internal::AccessorAssembler::HandleProtoHandler(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierLocal(), v8::internal::WriteBarrierCodeStubAssembler::InSharedHeap(), v8::internal::AccessorAssembler::InvalidateValidityCellIfPrototype(), v8::internal::WriteBarrierCodeStubAssembler::InYoungGeneration(), v8::internal::WriteBarrierCodeStubAssembler::IsValueUnmarkedOrRecordSlot(), v8::internal::interpreter::InterpreterAssembler::JumpConditional(), v8::internal::interpreter::InterpreterAssembler::JumpConditionalByConstantOperand(), v8::internal::interpreter::InterpreterAssembler::JumpConditionalByImmediateOperand(), v8::internal::AccessorAssembler::KeyedLoadIC(), v8::internal::AccessorAssembler::KeyedStoreIC(), v8::internal::CodeStubAssembler::LoadFixedArrayBaseElementAsTagged(), v8::internal::AccessorAssembler::LoadGlobalIC_TryPropertyCellCase(), v8::internal::CodeStubAssembler::LoadJSReceiverIdentityHash(), v8::internal::StringBuiltinsAssembler::LoadSurrogatePairAt(), v8::internal::CodeStubAssembler::LookupBinary(), v8::internal::CollectionsBuiltinsAssembler::MapIteratorToList(), v8::internal::StringBuiltinsAssembler::MaybeCallFunctionAtSymbol(), v8::internal::CodeStubAssembler::MoveElements(), v8::internal::CollectionsBuiltinsAssembler::NextSkipHashTableHoles(), v8::internal::CodeStubAssembler::NonNumberToNumberOrNumeric(), v8::internal::CodeStubAssembler::NumberDictionaryLookup(), v8::internal::AccessorAssembler::OverwriteExistingFastDataProperty(), v8::internal::CodeStubAssembler::PerformStackCheck(), v8::internal::CodeStubArguments::PopAndReturn(), v8::internal::GrowableFixedArray::Push(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), ReturnIf(), v8::internal::MicrotaskQueueBuiltinsAssembler::RunAllPromiseHooks(), v8::internal::MicrotaskQueueBuiltinsAssembler::RunPromiseHook(), v8::internal::CollectionsBuiltinsAssembler::SameValueZeroBigInt(), v8::internal::CollectionsBuiltinsAssembler::SameValueZeroHeapNumber(), v8::internal::CollectionsBuiltinsAssembler::SetOrSetIteratorToSet(), v8::internal::CodeStubAssembler::SharedValueBarrier(), v8::internal::CodeStubAssembler::SmiMod(), v8::internal::CodeStubAssembler::SmiMul(), v8::internal::interpreter::InterpreterAssembler::StarDispatchLookahead(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), v8::internal::AccessorAssembler::StoreGlobalIC(), v8::internal::AccessorAssembler::StoreJSSharedStructField(), v8::internal::CodeStubAssembler::StringCharCodeAt(), v8::internal::StringBuiltinsAssembler::StringEqual_Core(), v8::internal::CodeStubAssembler::StringFromSingleCharCode(), v8::internal::StringBuiltinsAssembler::StringFromSingleUTF16EncodedCodePoint(), v8::internal::StringBuiltinsAssembler::SubString(), v8::internal::CodeStubAssembler::ThrowIfNotCallable(), v8::internal::CodeStubAssembler::ThrowIfNotInstanceType(), v8::internal::CodeStubAssembler::ThrowIfNotJSReceiver(), v8::internal::interpreter::InterpreterAssembler::ToNumberOrNumeric(), v8::internal::CodeStubAssembler::ToString_Inline(), v8::internal::CodeStubAssembler::ToThisString(), v8::internal::CodeStubAssembler::ToThisValue(), v8::internal::CodeStubAssembler::ToUint32(), v8::internal::interpreter::InterpreterAssembler::TraceBytecodeDispatch(), v8::internal::CollectionsBuiltinsAssembler::Transition(), v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16(), v8::internal::CodeStubAssembler::TryFloat32ToSmi(), v8::internal::CodeStubAssembler::TryFloat64ToAdditiveSafeInteger(), v8::internal::CodeStubAssembler::TryFloat64ToInt32(), v8::internal::CodeStubAssembler::TryFloat64ToSmi(), v8::internal::CodeStubAssembler::TrySmiDiv(), v8::internal::ToDirectStringAssembler::TryToDirect(), v8::internal::CodeStubAssembler::TryToName(), v8::internal::ToDirectStringAssembler::TryToSequential(), v8::internal::ArrayBuiltinsAssembler::TypedArrayMapProcessor(), v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateAtomicAccess(), v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateIntegerTypedArray(), and v8::internal::WriteBarrierCodeStubAssembler::WriteBarrier().
BreakOnNode()
void v8::internal::compiler::CodeAssembler::BreakOnNode (int node_id)
Definition at line 122 of file code-assembler.cc.
                                           {
  TFGraph* graph = raw_assembler()->graph();
  Zone* zone = graph->zone();
  GraphDecorator* decorator =
      zone->New<BreakOnNodeDecorator>(static_cast<NodeId>(node_id));
  graph->AddDecorator(decorator);
}
References v8::internal::compiler::RawMachineAssembler::graph(), graph(), v8::internal::Zone::New(), raw_assembler(), and zone().
Referenced by v8::internal::CodeStubAssembler::HandleBreakOnNode().
builtin()
Builtin v8::internal::compiler::CodeAssembler::builtin ()
Definition at line 1278 of file code-assembler.cc.
{ return state()->builtin_; }
References v8::internal::compiler::CodeAssemblerState::builtin_, and state().
Referenced by v8::internal::interpreter::InterpreterAssembler::CallJSAndDispatch(), v8::internal::interpreter::InterpreterAssembler::CallJSWithSpreadAndDispatch(), v8::internal::interpreter::InterpreterAssembler::Construct(), v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread(), v8::internal::ArrayIncludesIndexofAssembler::Generate(), v8::internal::CodeStubAssembler::NonNumberToNumberOrNumeric(), v8::internal::ObjectBuiltinsAssembler::ReturnToStringFormat(), v8::internal::AccessorAssembler::StoreIC(), v8::internal::CodeStubAssembler::TaggedToWord32OrBigIntImpl(), and v8::internal::interpreter::InterpreterAssembler::ToNumberOrNumeric().
CallBuiltin()
template<typename T = Object, class... TArgs>
TNode<T> v8::internal::compiler::CodeAssembler::CallBuiltin (Builtin id, TNode< Object > context, TArgs... args) [inline]
Definition at line 1347 of file code-assembler.h.
                                                                         {
    DCHECK_WITH_MSG(!Builtins::HasJSLinkage(id), "Use CallJSBuiltin instead");
    TNode<RawPtrT> old_sp;
#if V8_ENABLE_WEBASSEMBLY
    bool maybe_needs_switch = wasm::BuiltinLookup::IsWasmBuiltinId(builtin()) &&
                              !wasm::BuiltinLookup::IsWasmBuiltinId(id);
    if (maybe_needs_switch) {
      old_sp = SwitchToTheCentralStackIfNeeded();
    }
#endif
    Callable callable = Builtins::CallableFor(isolate(), id);
    TNode<Code> target = HeapConstantNoHole(callable.code());
    TNode<T> call =
        CallStub<T>(callable.descriptor(), target, context, args...);
#if V8_ENABLE_WEBASSEMBLY
    if (maybe_needs_switch) {
      SwitchFromTheCentralStack(old_sp);
    }
#endif
    return call;
  }
References v8::base::args, v8::internal::Builtins::CallableFor(), v8::internal::Callable::code(), DCHECK_WITH_MSG, v8::internal::Callable::descriptor(), v8::internal::Builtins::HasJSLinkage(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::wasm::BuiltinLookup::IsWasmBuiltinId(), and v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchToTheCentralStackIfNeeded().
Referenced by v8::internal::RegExpBuiltinsAssembler::AppendStringSlice(), v8::internal::AsyncFunctionBuiltinsAssembler::AsyncFunctionAwaitResumeClosure(), v8::internal::AsyncBuiltinsAssembler::Await(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithSpread(), v8::internal::CodeStubAssembler::ChangeTaggedNonSmiToInt32(), v8::internal::CodeStubAssembler::ChangeTaggedToFloat64(), v8::internal::interpreter::InterpreterAssembler::Construct(), v8::internal::interpreter::InterpreterAssembler::ConstructForwardAllArgs(), v8::internal::RegExpBuiltinsAssembler::ConstructNewResultFromMatchInfo(), v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread(), v8::internal::IteratorBuiltinsAssembler::FastIterableToList(), v8::internal::BinaryOpAssembler::Generate_AddWithFeedback(), v8::internal::BinaryOpAssembler::Generate_BinaryOperationWithFeedback(), v8::internal::BinaryOpAssembler::Generate_BitwiseBinaryOpWithOptionalFeedback(), v8::internal::StringBuiltinsAssembler::GetSubstitution(), v8::internal::AccessorAssembler::HandleLoadAccessor(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::HandleStoreToProxy(), v8::internal::ShadowRealmBuiltinsAssembler::ImportValue(), v8::internal::StringBuiltinsAssembler::IndexOfDollarChar(), v8::internal::AccessorAssembler::KeyedLoadICGeneric(), v8::internal::IntlBuiltinsAssembler::ListFormatCommon(), v8::internal::CodeStubAssembler::NonNumberToNumberOrNumeric(), v8::internal::interpreter::InterpreterAssembler::OnStackReplacement(), v8::internal::CodeStubAssembler::OrdinaryToPrimitive(), v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::RegExpBuiltinsAssembler::RegExpReplaceGlobalSimpleString(), v8::internal::ExitPoint::ReturnCallBuiltin(), v8::internal::ObjectBuiltinsAssembler::ReturnToStringFormat(), v8::internal::MicrotaskQueueBuiltinsAssembler::RunSingleMicrotask(), v8::internal::CollectionsBuiltinsAssembler::TableHasKey(), v8::internal::CodeStubAssembler::TaggedToBigInt(), v8::internal::CodeStubAssembler::TaggedToWord32OrBigIntImpl(), v8::internal::CodeStubAssembler::ToLength_Inline(), v8::internal::CodeStubAssembler::ToNumber_Inline(), v8::internal::interpreter::InterpreterAssembler::ToNumberOrNumeric(), v8::internal::CodeStubAssembler::ToObject(), v8::internal::CodeStubAssembler::ToString_Inline(), v8::internal::CodeStubAssembler::ToThisString(), v8::internal::CollectionsBuiltinsAssembler::Transition(), v8::internal::CodeStubAssembler::TruncateTaggedToFloat64(), and v8::internal::AccessorAssembler::TryMegaDOMCase().
CallBuiltinPointer()
template<class T = Object, class... TArgs>
TNode<T> v8::internal::compiler::CodeAssembler::CallBuiltinPointer (const CallInterfaceDescriptor & descriptor, TNode< BuiltinPtr > target, TNode< Object > context, TArgs... args) [inline]
Definition at line 1406 of file code-assembler.h.
                                             {
    return UncheckedCast<T>(CallStubR(StubCallMode::kCallBuiltinPointer,
                                      descriptor, target, context, args...));
  }
References v8::base::args, and v8::internal::kCallBuiltinPointer.
CallBuiltinVoid()
template<class... TArgs>
void v8::internal::compiler::CodeAssembler::CallBuiltinVoid (Builtin id, TNode< Object > context, TArgs... args) [inline]
Definition at line 1370 of file code-assembler.h.
                                                                         {
    DCHECK_WITH_MSG(!Builtins::HasJSLinkage(id), "Use CallJSBuiltin instead");
    Callable callable = Builtins::CallableFor(isolate(), id);
    TNode<Code> target = HeapConstantNoHole(callable.code());
    CallStubR(StubCallMode::kCallCodeObject, callable.descriptor(), target,
              context, args...);
  }
References v8::base::args, v8::internal::Builtins::CallableFor(), v8::internal::Callable::code(), DCHECK_WITH_MSG, v8::internal::Callable::descriptor(), v8::internal::Builtins::HasJSLinkage(), v8::internal::compiler::HeapConstantNoHole(), and v8::internal::kCallCodeObject.
CallCFunction() [1/2]
template<class... CArgs>
Node* v8::internal::compiler::CodeAssembler::CallCFunction (Node * function, std::optional< MachineType > return_type, CArgs... cargs) [inline]
Definition at line 1543 of file code-assembler.h.
                                      {
    static_assert(
        std::conjunction_v<std::is_convertible<CArgs, CFunctionArg>...>,
        "invalid argument types");
    return CallCFunction(function, return_type, {cargs...});
  }
Referenced by v8::internal::TypedArrayBuiltinsAssembler::CallCCopyFastNumberJSArrayElementsToTypedArray(), v8::internal::TypedArrayBuiltinsAssembler::CallCCopyTypedArrayElementsSlice(), v8::internal::TypedArrayBuiltinsAssembler::CallCCopyTypedArrayElementsToTypedArray(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemcpy(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemmove(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemset(), v8::internal::TypedArrayBuiltinsAssembler::CallCRelaxedMemcpy(), v8::internal::TypedArrayBuiltinsAssembler::CallCRelaxedMemmove(), v8::internal::CollectionsBuiltinsAssembler::CallGetHashRaw(), v8::internal::CollectionsBuiltinsAssembler::CallGetOrCreateHashRaw(), v8::internal::ArrayBuiltinsAssembler::CallJSArrayArrayJoinConcatToSequentialString(), v8::internal::StringBuiltinsAssembler::CallSearchStringRaw(), v8::internal::CodeStubAssembler::ComputeSeededHash(), v8::internal::CodeStubAssembler::CopyElements(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteAddAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteCompare(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteDivAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteModAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteMulAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteSubAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseAndNegNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseAndPosNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseAndPosPosAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseOrNegNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseOrPosNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseOrPosPosAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseXorNegNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseXorPosNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseXorPosPosAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppLeftShiftAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppRightShiftAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppRightShiftResultLength(), v8::internal::WeakCollectionsBuiltinsAssembler::CreateIdentityHash(), v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), v8::internal::CodeStubAssembler::ExternalOneByteStringGetChars(), v8::internal::CodeStubAssembler::ExternalTwoByteStringGetChars(), v8::internal::CodeStubAssembler::FillFixedArrayWithSmiZero(), v8::internal::CodeStubAssembler::FillFixedDoubleArrayWithZero(), v8::internal::RegExpBuiltinsAssembler::FreeRegExpResultVector(), v8::internal::DateBuiltinsAssembler::Generate_DatePrototype_GetField(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GeneratePackedDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::CodeStubAssembler::GetCoverageInfo(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::StringBuiltinsAssembler::HasUnpairedSurrogate(), v8::internal::AccessorAssembler::InvalidateValidityCellIfPrototype(), v8::internal::CodeStubAssembler::LoadNameRawHash(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), v8::internal::CodeStubAssembler::MoveElements(), v8::internal::CodeStubAssembler::NameDictionaryLookupWithForwardIndex(), v8::internal::CodeStubAssembler::RefillMathRandom(), v8::internal::RegExpBuiltinsAssembler::RegExpExecAtom(), v8::internal::StringBuiltinsAssembler::ReplaceUnpairedSurrogates(), v8::internal::StringBuiltinsAssembler::SearchOneByteInOneByteString(), v8::internal::CodeStubAssembler::SmiLexicographicCompare(), v8::internal::WasmBuiltinsAssembler::StringToFloat64(), v8::internal::CodeStubAssembler::StringWriteToFlatOneByte(), v8::internal::CodeStubAssembler::StringWriteToFlatTwoByte(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::CodeStubAssembler::TryInternalizeString(), and v8::internal::CodeStubAssembler::TryToName().
CallCFunction() [2/2]
Node* v8::internal::compiler::CodeAssembler::CallCFunction (Node * function, std::optional< MachineType > return_type, std::initializer_list< CFunctionArg > args) [private]
CallCFunctionN()
Node * v8::internal::compiler::CodeAssembler::CallCFunctionN (Signature< MachineType > * signature, int input_count, Node *const * inputs)
Definition at line 1529 of file code-assembler.cc.
                                                                          {
  auto call_descriptor = Linkage::GetSimplifiedCDescriptor(zone(), signature);
  return raw_assembler()->CallN(call_descriptor, input_count, inputs);
}
References v8::internal::compiler::RawMachineAssembler::CallN(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::compiler::turboshaft::detail::input_count(), raw_assembler(), and zone().
CallCFunctionWithCallerSavedRegisters() [1/2]
template<class... CArgs>
Node* v8::internal::compiler::CodeAssembler::CallCFunctionWithCallerSavedRegisters (Node * function, MachineType return_type, SaveFPRegsMode mode, CArgs... cargs) [inline]
Definition at line 1565 of file code-assembler.h.
                                                              {
    static_assert(
        std::conjunction_v<std::is_convertible<CArgs, CFunctionArg>...>,
        "invalid argument types");
    return CallCFunctionWithCallerSavedRegisters(function, return_type, mode,
                                                 {cargs...});
  }
References mode().
Referenced by v8::internal::WriteBarrierCodeStubAssembler::GenerateEphemeronKeyBarrier(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierMajor(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierMinor(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierShared(), v8::internal::WriteBarrierCodeStubAssembler::IndirectPointerWriteBarrier(), v8::internal::WriteBarrierCodeStubAssembler::InsertIntoRememberedSet(), and v8::internal::WriteBarrierCodeStubAssembler::SharedBarrierSlow().
CallCFunctionWithCallerSavedRegisters() [2/2]
Node* v8::internal::compiler::CodeAssembler::CallCFunctionWithCallerSavedRegisters (Node * function, MachineType return_type, SaveFPRegsMode mode, std::initializer_list< CFunctionArg > args) [private]
CallCFunctionWithoutFunctionDescriptor() [1/2]
template<class... CArgs>
Node* v8::internal::compiler::CodeAssembler::CallCFunctionWithoutFunctionDescriptor (Node * function, MachineType return_type, CArgs... cargs) [inline]
Definition at line 1553 of file code-assembler.h.
                                                               {
    static_assert(
        std::conjunction_v<std::is_convertible<CArgs, CFunctionArg>...>,
        "invalid argument types");
    return CallCFunctionWithoutFunctionDescriptor(function, return_type,
                                                  {cargs...});
  }
Referenced by v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal().
CallCFunctionWithoutFunctionDescriptor() [2/2]
Node* v8::internal::compiler::CodeAssembler::CallCFunctionWithoutFunctionDescriptor (Node * function, MachineType return_type, std::initializer_list< CFunctionArg > args) [private]
CallEpilogue()
void v8::internal::compiler::CodeAssembler::CallEpilogue () [private]
Definition at line 151 of file code-assembler.cc.
                                 {
  if (state_->call_epilogue_) {
    state_->call_epilogue_();
  }
}
References v8::internal::compiler::CodeAssemblerState::call_epilogue_, and state_.
Referenced by CallRuntimeImpl(), and CallStubN().
CallJS()
template<class... TArgs>
TNode<JSAny> v8::internal::compiler::CodeAssembler::CallJS (Builtin builtin, TNode< Context > context, TNode< Object > function, TNode< JSAny > receiver, TArgs... args) [inline]
Definition at line 1486 of file code-assembler.h.
                                     {
    DCHECK(Builtins::IsAnyCall(builtin));
#if V8_ENABLE_WEBASSEMBLY
    // Unimplemented. Add code for switching to the central stack here if
    // needed. See {CallBuiltin} for example.
    DCHECK(!wasm::BuiltinLookup::IsWasmBuiltinId(this->builtin()) ||
           wasm::BuiltinLookup::IsWasmBuiltinId(builtin));
#endif
    Callable callable = Builtins::CallableFor(isolate(), builtin);
    int argc = JSParameterCount(static_cast<int>(sizeof...(args)));
    TNode<Int32T> arity = Int32Constant(argc);
    TNode<Code> target = HeapConstantNoHole(callable.code());
    return CAST(CallJSStubImpl(callable.descriptor(), target, context, function,
                               std::nullopt, arity, std::nullopt,
                               {receiver, args...}));
  }
References v8::base::args, v8::internal::Builtins::CallableFor(), CAST, v8::internal::Callable::code(), v8::internal::DCHECK(), v8::internal::Callable::descriptor(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::Builtins::IsAnyCall(), v8::internal::wasm::BuiltinLookup::IsWasmBuiltinId(), and v8::internal::JSParameterCount().
Referenced by v8::internal::CodeStubAssembler::Call(), and v8::internal::CodeStubAssembler::CallFunction().
CallJSBuiltin()
template<class... TArgs>
TNode<Object> v8::internal::compiler::CodeAssembler::CallJSBuiltin (Builtin builtin, TNode< Context > context, TNode< Object > function, std::optional< TNode< Object >> new_target, TNode< Object > receiver, TArgs... args) [inline]
Definition at line 1435 of file code-assembler.h.
                                                                     {
    DCHECK(Builtins::HasJSLinkage(builtin));
    // The receiver is also passed on the stack so needs to be included.
    DCHECK_EQ(Builtins::GetStackParameterCount(builtin), 1 + sizeof...(args));
#if V8_ENABLE_WEBASSEMBLY
    // Unimplemented. Add code for switching to the central stack here if
    // needed. See {CallBuiltin} for example.
    DCHECK(!wasm::BuiltinLookup::IsWasmBuiltinId(this->builtin()) ||
           wasm::BuiltinLookup::IsWasmBuiltinId(builtin));
#endif
    Callable callable = Builtins::CallableFor(isolate(), builtin);
    int argc = JSParameterCount(static_cast<int>(sizeof...(args)));
    TNode<Int32T> arity = Int32Constant(argc);
    TNode<JSDispatchHandleT> dispatch_handle = UncheckedCast<JSDispatchHandleT>(
        Uint32Constant(kInvalidDispatchHandle.value()));
    TNode<Code> target = HeapConstantNoHole(callable.code());
    return CAST(CallJSStubImpl(callable.descriptor(), target, context, function,
                               new_target, arity, dispatch_handle,
                               {receiver, args...}));
  }
References v8::base::args, v8::internal::Builtins::CallableFor(), CAST, v8::internal::Callable::code(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Callable::descriptor(), v8::internal::Builtins::GetStackParameterCount(), v8::internal::Builtins::HasJSLinkage(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::wasm::BuiltinLookup::IsWasmBuiltinId(), v8::internal::JSParameterCount(), v8::internal::kInvalidDispatchHandle(), and v8::base::StrongAlias< TagType, UnderlyingType >::value().
CallJSStubImpl()
Node * v8::internal::compiler::CodeAssembler::CallJSStubImpl (const CallInterfaceDescriptor & descriptor, TNode< Object > target, TNode< Object > context, TNode< Object > function, std::optional< TNode< Object >> new_target, TNode< Int32T > arity, std::optional< TNode< JSDispatchHandleT >> dispatch_handle, std::initializer_list< Node * > args) [private]
Definition at line 1432 of file code-assembler.cc.
                                     {
  constexpr size_t kMaxNumArgs = 10;
  DCHECK_GE(kMaxNumArgs, args.size());
  NodeArray<kMaxNumArgs + 6> inputs;
  inputs.Add(target);
  inputs.Add(function);
  if (new_target) {
    inputs.Add(*new_target);
  }
  inputs.Add(arity);
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
  if (dispatch_handle) {
    inputs.Add(*dispatch_handle);
  }
#endif
  for (auto arg : args) inputs.Add(arg);
  // Context argument is implicit so isn't counted.
  DCHECK(IsValidArgumentCountFor(descriptor, inputs.size()));
  if (descriptor.HasContextParameter()) {
    inputs.Add(context);
  }
  return CallStubN(StubCallMode::kCallCodeObject, descriptor, inputs.size(),
                   inputs.data());
}
References v8::base::args, CallStubN(), v8::internal::CallInterfaceDescriptor::data(), v8::internal::DCHECK(), DCHECK_GE, v8::internal::CallInterfaceDescriptor::HasContextParameter(), and v8::internal::kCallCodeObject.
CallPrologue()
void v8::internal::compiler::CodeAssembler::CallPrologue () [private]
Definition at line 145 of file code-assembler.cc.
                                 {
  if (state_->call_prologue_) {
    state_->call_prologue_();
  }
}
References v8::internal::compiler::CodeAssemblerState::call_prologue_, and state_.
Referenced by CallRuntimeImpl(), and CallStubN().
CallRuntime()
template<class T = Object, class... TArgs>
TNode<T> v8::internal::compiler::CodeAssembler::CallRuntime (Runtime::FunctionId function, TNode< Object > context, TArgs... args) [inline]
Definition at line 1308 of file code-assembler.h.
                                      {
    return UncheckedCast<T>(CallRuntimeImpl(
        function, context, {implicit_cast<TNode<Object>>(args)...}));
  }
References v8::base::args.
Referenced by v8::internal::interpreter::InterpreterAssembler::Abort(), v8::internal::BaseCollectionsAssembler::AddConstructorEntries(), v8::internal::CollectionsBuiltinsAssembler::AddToSetTable(), v8::internal::CollectionsBuiltinsAssembler::AddValueToKeyedGroup(), v8::internal::CodeStubAssembler::AllocateArrayList(), v8::internal::CodeStubAssembler::AllocateByteArray(), v8::internal::CodeStubAssembler::AllocateFixedArray(), v8::internal::CodeStubAssembler::AllocateRaw(), v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::ArrayListEnsureSpace(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::AsyncBuiltinsAssembler::Await(), v8::internal::CallOrConstructBuiltinsAssembler::CallFunctionTemplate(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithArrayLike(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithSpread(), v8::internal::CodeStubAssembler::CallRuntimeNewArray(), v8::internal::ProxiesCodeStubAssembler::CheckDeleteTrapResult(), v8::internal::ProxiesCodeStubAssembler::CheckGetSetTrapResult(), v8::internal::ProxiesCodeStubAssembler::CheckHasTrapResult(), v8::internal::LazyBuiltinsAssembler::CompileLazy(), v8::internal::RegExpBuiltinsAssembler::ConstructNewResultFromMatchInfo(), v8::internal::ConstructorBuiltinsAssembler::CreateRegExpLiteral(), v8::internal::interpreter::InterpreterAssembler::DecreaseInterruptBudget(), v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::DeletePropertyBaseAssembler::DictionarySpecificDelete(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::CodeStubAssembler::FailAssert(), v8::internal::ConstructorBuiltinsAssembler::FastNewObject(), v8::internal::RegExpBuiltinsAssembler::FlagsGetter(), v8::internal::CodeStubAssembler::Float64ToString(), v8::internal::CodeStubAssembler::ForEachEnumerableOwnProperty(), v8::internal::BinaryOpAssembler::Generate_AddStringConstantInternalizeWithFeedback(), v8::internal::BinaryOpAssembler::Generate_BinaryOperationWithFeedback(), v8::internal::AccessorAssembler::GenerateCloneObjectIC(), v8::internal::AccessorAssembler::GenerateCloneObjectIC_Slow(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::LazyBuiltinsAssembler::GenerateTailCallToReturnedCode(), v8::internal::CodeStubAssembler::GetImportMetaObject(), v8::internal::IteratorBuiltinsAssembler::GetIterator(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::GetOwnValuesOrEntries(), v8::internal::StringBuiltinsAssembler::GetSubstitution(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::ShadowRealmBuiltinsAssembler::ImportValue(), v8::internal::CodeStubAssembler::InitializeJSObjectBodyWithSlackTracking(), v8::internal::RegExpBuiltinsAssembler::InitializeMatchInfoFromRegisters(), v8::internal::GeneratorBuiltinsAssembler::InnerResume(), v8::internal::CodeStubAssembler::InvalidateStringWrapperToPrimitiveProtector(), v8::internal::IteratorBuiltinsAssembler::Iterate(), v8::internal::IteratorBuiltinsAssembler::IteratorStep(), v8::internal::AccessorAssembler::LoadGlobalIC_NoFeedback(), v8::internal::CodeStubAssembler::NonNumberToNumberOrNumeric(), v8::internal::CodeStubAssembler::NumberToString(), v8::internal::CodeStubAssembler::PerformStackCheck(), v8::internal::CodeStubAssembler::PrintToStream(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Single(), v8::internal::RegExpBuiltinsAssembler::RegExpInitialize(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::ExitPoint::ReturnCallRuntime(), v8::internal::MicrotaskQueueBuiltinsAssembler::RunPromiseHook(), v8::internal::MicrotaskQueueBuiltinsAssembler::RunSingleMicrotask(), v8::internal::CollectionsBuiltinsAssembler::SameValueZeroBigInt(), v8::internal::ShadowRealmBuiltinsAssembler::ShadowRealmThrow(), v8::internal::CodeStubAssembler::SharedValueBarrier(), v8::internal::KeyedStoreGenericAssembler::StoreProperty(), v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::CodeStubAssembler::StringCharCodeAt(), v8::internal::IteratorBuiltinsAssembler::StringListFromIterable(), v8::internal::StringBuiltinsAssembler::StringToArray(), v8::internal::WasmBuiltinsAssembler::StringToFloat64(), v8::internal::CodeStubAssembler::StringToNumber(), v8::internal::StringBuiltinsAssembler::SubString(), v8::internal::CodeStubAssembler::TaggedToWord32OrBigIntImpl(), v8::internal::CodeStubAssembler::TerminateExecution(), v8::internal::CodeStubAssembler::ThrowRangeError(), v8::internal::CodeStubAssembler::ThrowTypeError(), v8::internal::CodeStubAssembler::ToBigInt(), v8::internal::CodeStubAssembler::ToBigIntConvertNumber(), v8::internal::ToDirectStringAssembler::ToDirect(), and v8::internal::interpreter::InterpreterAssembler::TraceBytecode().
CallRuntimeImpl()
Node * v8::internal::compiler::CodeAssembler::CallRuntimeImpl (Runtime::FunctionId function, TNode< Object > context, std::initializer_list< TNode< Object >> args) [private]
Definition at line 1231 of file code-assembler.cc.
                                             {
  int result_size = Runtime::FunctionForId(function)->result_size;
#if V8_ENABLE_WEBASSEMBLY
  bool switch_to_the_central_stack =
      state_->kind_ == CodeKind::WASM_FUNCTION ||
      state_->kind_ == CodeKind::WASM_TO_JS_FUNCTION ||
      state_->kind_ == CodeKind::JS_TO_WASM_FUNCTION ||
      state_->builtin_ == Builtin::kJSToWasmWrapper ||
      state_->builtin_ == Builtin::kJSToWasmHandleReturns ||
      state_->builtin_ == Builtin::kWasmToJsWrapperCSA ||
      wasm::BuiltinLookup::IsWasmBuiltinId(state_->builtin_);
#else
  bool switch_to_the_central_stack = false;
#endif
  Builtin centry =
      Builtins::RuntimeCEntry(result_size, switch_to_the_central_stack);
  TNode<Code> centry_code =
      HeapConstantNoHole(isolate()->builtins()->code_handle(centry));
  constexpr size_t kMaxNumArgs = 7;
  DCHECK_GE(kMaxNumArgs, args.size());
  int argc = static_cast<int>(args.size());
  auto call_descriptor = Linkage::GetRuntimeCallDescriptor(
      zone(), function, argc, Operator::kNoProperties,
      Runtime::MayAllocate(function) ? CallDescriptor::kNoFlags
                                     : CallDescriptor::kNoAllocate);
  TNode<ExternalReference> ref =
      ExternalConstant(ExternalReference::Create(function));
  TNode<Int32T> arity = Int32Constant(argc);
  NodeArray<kMaxNumArgs + 4> inputs;
  inputs.Add(centry_code);
  for (const auto& arg : args) inputs.Add(arg);
  inputs.Add(ref);
  inputs.Add(arity);
  inputs.Add(context);
  CallPrologue();
  Node* return_value =
      raw_assembler()->CallN(call_descriptor, inputs.size(), inputs.data());
  HandleException(return_value);
  CallEpilogue();
  return return_value;
}
References v8::base::args, v8::internal::compiler::CodeAssemblerState::builtin_, CallEpilogue(), v8::internal::compiler::RawMachineAssembler::CallN(), CallPrologue(), v8::internal::ExternalReference::Create(), DCHECK_GE, ExternalConstant(), v8::internal::Runtime::FunctionForId(), v8::internal::compiler::Linkage::GetRuntimeCallDescriptor(), HandleException(), HeapConstantNoHole(), Int32Constant(), isolate(), v8::internal::wasm::BuiltinLookup::IsWasmBuiltinId(), v8::internal::compiler::CodeAssemblerState::kind_, v8::internal::compiler::CallDescriptor::kNoAllocate, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, v8::internal::Runtime::MayAllocate(), raw_assembler(), v8::internal::Runtime::Function::result_size, v8::internal::Builtins::RuntimeCEntry(), state_, v8::internal::wasm::switch_to_the_central_stack(), and zone().
CallStub()
template<class T = Object, class... TArgs>
TNode<T> v8::internal::compiler::CodeAssembler::CallStub (const CallInterfaceDescriptor & descriptor, TNode< Code > target, TNode< Object > context, TArgs... args) [inline]
Definition at line 1399 of file code-assembler.h.
                                                                              {
    return UncheckedCast<T>(CallStubR(StubCallMode::kCallCodeObject, descriptor,
                                      target, context, args...));
  }
References v8::base::args, and v8::internal::kCallCodeObject.
Referenced by v8::internal::ExitPoint::ReturnCallStub().
CallStubN()
Node * v8::internal::compiler::CodeAssembler::CallStubN (StubCallMode call_mode, const CallInterfaceDescriptor & descriptor, int input_count, Node *const * inputs) [private]
Definition at line 1364 of file code-assembler.cc.
                                                                     {
  DCHECK(call_mode == StubCallMode::kCallCodeObject ||
         call_mode == StubCallMode::kCallBuiltinPointer);
  // implicit nodes are target and optionally context.
  int implicit_nodes = descriptor.HasContextParameter() ? 2 : 1;
  DCHECK_LE(implicit_nodes, input_count);
  int argc = input_count - implicit_nodes;
  DCHECK(IsValidArgumentCountFor(descriptor, argc));
  // Extra arguments not mentioned in the descriptor are passed on the stack.
  int stack_parameter_count = argc - descriptor.GetRegisterParameterCount();
  DCHECK_LE(descriptor.GetStackParameterCount(), stack_parameter_count);
  auto call_descriptor = Linkage::GetStubCallDescriptor(
      zone(), descriptor, stack_parameter_count, CallDescriptor::kNoFlags,
      Operator::kNoProperties, call_mode);
  CallPrologue();
  Node* return_value =
      raw_assembler()->CallN(call_descriptor, input_count, inputs);
  HandleException(return_value);
  CallEpilogue();
  return return_value;
}
References CallEpilogue(), v8::internal::compiler::RawMachineAssembler::CallN(), CallPrologue(), v8::internal::DCHECK(), DCHECK_LE, v8::internal::CallInterfaceDescriptor::GetRegisterParameterCount(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), HandleException(), v8::internal::CallInterfaceDescriptor::HasContextParameter(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::kCallBuiltinPointer, v8::internal::kCallCodeObject, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, raw_assembler(), and zone().
Referenced by CallJSStubImpl(), and CallStubRImpl().
CallStubR()
template<class... TArgs>
Node* v8::internal::compiler::CodeAssembler::CallStubR (StubCallMode call_mode, const CallInterfaceDescriptor & descriptor, TNode< Object > target, TNode< Object > context, TArgs... args) [inline], [private]
Definition at line 1630 of file code-assembler.h.
                                                                              {
    return CallStubRImpl(call_mode, descriptor, target, context, {args...});
  }
References v8::base::args.
CallStubRImpl()
Node * v8::internal::compiler::CodeAssembler::CallStubRImpl (StubCallMode call_mode, const CallInterfaceDescriptor & descriptor, TNode< Object > target, TNode< Object > context, std::initializer_list< Node * > args) [private]
Definition at line 1411 of file code-assembler.cc.
                                                                    {
  DCHECK(call_mode == StubCallMode::kCallCodeObject ||
         call_mode == StubCallMode::kCallBuiltinPointer);
  DCHECK(IsValidArgumentCountFor(descriptor, args.size()));
  constexpr size_t kMaxNumArgs = 10;
  DCHECK_GE(kMaxNumArgs, args.size());
  NodeArray<kMaxNumArgs + 2> inputs;
  inputs.Add(target);
  for (auto arg : args) inputs.Add(arg);
  if (descriptor.HasContextParameter()) {
    inputs.Add(context);
  }
  return CallStubN(call_mode, descriptor, inputs.size(), inputs.data());
}
References v8::base::args, CallStubN(), v8::internal::CallInterfaceDescriptor::data(), v8::internal::DCHECK(), DCHECK_GE, v8::internal::CallInterfaceDescriptor::HasContextParameter(), v8::internal::kCallBuiltinPointer, and v8::internal::kCallCodeObject.
Cast() [1/2]
CheckedNode<Object, false> v8::internal::compiler::CodeAssembler::Cast (Node * value, const char * location = ``) [inline]
Definition at line 551 of file code-assembler.h.
                                                                          {
    return {value, this, location};
  }
References v8::internal::value.
Referenced by v8::internal::CollectionsBuiltinsAssembler::AddToSetTable().
Cast() [2/2]
template<class T >
CheckedNode<T, true> v8::internal::compiler::CodeAssembler::Cast (TNode< T > value, const char * location = ``) [inline]
Definition at line 556 of file code-assembler.h.
                                                                       {
    return {value, this, location};
  }
References v8::internal::value.
ChangeFloat64ToIntPtr()
TNode< IntPtrT > v8::internal::compiler::CodeAssembler::ChangeFloat64ToIntPtr (TNode< Float64T > value)
Definition at line 807 of file code-assembler.cc.
                                                                         {
  if (raw_assembler()->machine()->Is64()) {
    return UncheckedCast<IntPtrT>(raw_assembler()->ChangeFloat64ToInt64(value));
  }
  return UncheckedCast<IntPtrT>(raw_assembler()->ChangeFloat64ToInt32(value));
}
References Is64(), raw_assembler(), and v8::internal::value.
ChangeFloat64ToUintPtr()
TNode< UintPtrT > v8::internal::compiler::CodeAssembler::ChangeFloat64ToUintPtr (TNode< Float64T > value)
Definition at line 814 of file code-assembler.cc.
                                                                           {
  if (raw_assembler()->machine()->Is64()) {
    return UncheckedCast<UintPtrT>(
        raw_assembler()->ChangeFloat64ToUint64(value));
  }
  return UncheckedCast<UintPtrT>(raw_assembler()->ChangeFloat64ToUint32(value));
}
References Is64(), raw_assembler(), and v8::internal::value.
ChangeInt32ToIntPtr()
TNode< IntPtrT > v8::internal::compiler::CodeAssembler::ChangeInt32ToIntPtr (TNode< Word32T > value)
Definition at line 800 of file code-assembler.cc.
                                                                      {
  if (raw_assembler()->machine()->Is64()) {
    return UncheckedCast<IntPtrT>(raw_assembler()->ChangeInt32ToInt64(value));
  }
  return ReinterpretCast<IntPtrT>(value);
}
References Is64(), raw_assembler(), and v8::internal::value.
Referenced by v8::internal::CollectionsBuiltinsAssembler::AddNewToOrderedHashTable(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandIdxTaggedIndex(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandImmIntPtr(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReg(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructDoubleVarargs(), v8::internal::CodeStubAssembler::ChangeInt32ToTagged(), v8::internal::CodeStubAssembler::ChangeInt32ToTaggedNoOverflow(), v8::internal::CodeStubAssembler::EntryIndexToIndex(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::CodeStubAssembler::GetNumberOfElements(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::interpreter::InterpreterAssembler::LoadAndUntagRegister(), v8::internal::CodeStubAssembler::LoadArrayLength(), v8::internal::CodeStubAssembler::LoadDetailsByKeyIndex(), v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), v8::internal::CodeStubAssembler::LoadMapConstructorFunctionIndex(), v8::internal::CodeStubAssembler::LoadMapInobjectPropertiesStartInWords(), v8::internal::CodeStubAssembler::LoadMapInstanceSizeInWords(), v8::internal::interpreter::InterpreterAssembler::LoadParameterCountWithoutReceiver(), v8::internal::CodeStubAssembler::LoadSwissNameDictionaryNumberOfDeletedElements(), v8::internal::CodeStubAssembler::LoadSwissNameDictionaryNumberOfElements(), v8::internal::CodeStubAssembler::LookupLinear(), v8::internal::CodeStubAssembler::MapUsedInstanceSizeInWords(), v8::internal::CodeStubAssembler::NormalizeSmiIndex(), v8::internal::CodeStubArguments::PopAndReturn(), v8::internal::BigIntBuiltinsAssembler::ReadBigIntLength(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::StringBuiltinsAssembler::SearchOneByteInOneByteString(), v8::internal::WriteBarrierCodeStubAssembler::SetBitInCell(), v8::internal::CodeStubAssembler::SmiFromInt32(), v8::internal::CodeStubAssembler::SmiToTaggedIndex(), v8::internal::CodeStubAssembler::SmiUntag(), v8::internal::CodeStubAssembler::StoreDetailsByKeyIndex(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::CodeStubAssembler::TryFloat32ToSmi(), v8::internal::CodeStubAssembler::TryFloat64ToSmi(), v8::internal::CodeStubAssembler::TryMatchPreallocatedNumberString(), v8::internal::CodeStubAssembler::TrySmiAbs(), v8::internal::CodeStubAssembler::TrySmiAdd(), v8::internal::CodeStubAssembler::TrySmiSub(), and v8::internal::CodeStubAssembler::TryTaggedToInt32AsIntPtr().
ChangeUint32ToWord()
TNode< UintPtrT > v8::internal::compiler::CodeAssembler::ChangeUint32ToWord (TNode< Word32T > value)
Definition at line 792 of file code-assembler.cc.
                                                                      {
  if (raw_assembler()->machine()->Is64()) {
    return UncheckedCast<UintPtrT>(
        raw_assembler()->ChangeUint32ToUint64(value));
  }
  return ReinterpretCast<UintPtrT>(value);
}
References Is64(), raw_assembler(), and v8::internal::value.
Referenced by v8::internal::CollectionsBuiltinsAssembler::AddNewToOrderedHashTable(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandConstantPoolIdx(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandIdx(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandNativeContextIndex(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUImmWord(), v8::internal::CallOrConstructBuiltinsAssembler::CallReceiver(), v8::internal::interpreter::InterpreterAssembler::CallRuntimeN(), v8::internal::CodeStubAssembler::ChangeUint32ToTagged(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::CodeStubAssembler::DoubleStringCacheEntryToOffset(), v8::internal::interpreter::InterpreterAssembler::ExportParametersAndRegisterFile(), v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntry(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForBigIntKey(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForHeapNumberKey(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForOtherKey(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForSmiKey(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForStringKey(), v8::internal::WeakCollectionsBuiltinsAssembler::GetHash(), v8::internal::interpreter::InterpreterAssembler::ImportRegisterFile(), v8::internal::CodeStubAssembler::InitializeJSObjectBodyWithSlackTracking(), v8::internal::interpreter::InterpreterAssembler::LoadBytecode(), v8::internal::CodeStubAssembler::LoadExternalPointerFromObject(), v8::internal::CodeStubAssembler::LoadJSTypedArrayDataPtr(), v8::internal::GeneratorBuiltinsAssembler::LoadParameterCountWithoutReceiverFromBaseline(), v8::internal::CodeStubAssembler::LoadPropertyArrayLength(), v8::internal::CodeStubAssembler::LoadStringLengthAsWord(), v8::internal::CodeStubAssembler::NameDictionaryLookup(), v8::internal::CodeStubAssembler::NumberDictionaryLookup(), v8::internal::TypedArrayBuiltinsAssembler::SetJSTypedArrayOnHeapDataPtr(), v8::internal::CodeStubAssembler::SmiFromInt32(), v8::internal::CodeStubAssembler::SmiFromUint32(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::CodeStubAssembler::StoreExternalPointerToObject(), v8::internal::CodeStubAssembler::StoreFixedArrayOrPropertyArrayElement(), v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::AccessorAssembler::StubCachePrimaryOffset(), v8::internal::AccessorAssembler::StubCacheSecondaryOffset(), v8::internal::CodeStubAssembler::SwissNameDictionaryOffsetIntoPropertyDetailsTableMT(), v8::internal::CodeStubAssembler::SwissNameDictionarySetCtrl(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad(), and v8::internal::CodeStubAssembler::TryMatchRootRange().
ChangeUintPtrToFloat64()
TNode< Float64T > v8::internal::compiler::CodeAssembler::ChangeUintPtrToFloat64 (TNode< UintPtrT > value)
Definition at line 822 of file code-assembler.cc.
                                                                           {
  if (raw_assembler()->machine()->Is64()) {
    // TODO(turbofan): Maybe we should introduce a ChangeUint64ToFloat64
    // machine operator to TurboFan here?
    return UncheckedCast<Float64T>(
        raw_assembler()->RoundUint64ToFloat64(value));
  }
  return UncheckedCast<Float64T>(raw_assembler()->ChangeUint32ToFloat64(value));
}
References Is64(), raw_assembler(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::ChangeUintPtrToTagged().
Comment()
template<class... Args>
void v8::internal::compiler::CodeAssembler::Comment (MessageWithSourceLocation message, Args &&... args) [inline]
Definition at line 758 of file code-assembler.h.
                                                                  {
    if (!v8_flags.code_comments) return;
    std::ostringstream s;
    USE(s << message.message, (s << std::forward<Args>(args))...);
    if (message.loc.FileName()) {
      s << " - " << message.loc.ToString();
    }
    EmitComment(std::move(s).str());
  }
References v8::base::args, v8::SourceLocation::FileName(), v8::internal::compiler::CodeAssembler::MessageWithSourceLocation::loc, v8::internal::compiler::CodeAssembler::MessageWithSourceLocation::message, v8::SourceLocation::ToString(), USE, and v8::internal::v8_flags.
Referenced by v8::internal::CodeStubAssembler::Allocate(), v8::internal::CodeStubAssembler::AllocateByteArray(), v8::internal::StringBuiltinsAssembler::AllocateConsString(), v8::internal::CodeStubAssembler::AllocateFixedArray(), v8::internal::CodeStubAssembler::AllocateJSArray(), v8::internal::CodeStubAssembler::AllocateNonEmptyByteArray(), v8::internal::CodeStubAssembler::AllocateOrderedHashTableWithCapacity(), v8::internal::CodeStubAssembler::AllocateSeqOneByteString(), v8::internal::CodeStubAssembler::AllocateSeqTwoByteString(), v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::AllocateUninitializedJSArrayWithElements(), v8::internal::CodeStubAssembler::BuildAppendJSArray(), v8::internal::CodeStubAssembler::CalculateNewElementsCapacity(), v8::internal::interpreter::InterpreterAssembler::CallJSWithSpreadAndDispatch(), v8::internal::CodeStubAssembler::Check(), v8::internal::interpreter::InterpreterAssembler::Construct(), v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::ConstructorBuiltinsAssembler::CopyMutableHeapNumbersInObject(), v8::internal::CodeStubAssembler::CopyNameDictionary(), v8::internal::CodeStubAssembler::CopyPropertyArrayValues(), v8::internal::StringBuiltinsAssembler::CopyStringCharacters(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::ConstructorBuiltinsAssembler::CreateEmptyArrayLiteral(), v8::internal::ConstructorBuiltinsAssembler::CreateShallowObjectLiteral(), v8::internal::interpreter::InterpreterAssembler::DecreaseInterruptBudget(), v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::interpreter::InterpreterAssembler::Dispatch(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::AccessorAssembler::EmitFastElementsBoundsCheck(), v8::internal::KeyedStoreGenericAssembler::EmitGenericElementStore(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::CodeStubAssembler::EnsureArrayPushable(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::CodeStubAssembler::ExtractFixedArray(), v8::internal::CodeStubAssembler::ExtractFixedDoubleArrayFillingHoles(), v8::internal::CodeStubAssembler::ExtractToFixedArray(), v8::internal::CodeStubAssembler::FastCloneJSObject(), v8::internal::CodeStubAssembler::Float64ToString(), v8::internal::CodeStubArguments::ForEach(), v8::internal::BinaryOpAssembler::Generate_AddWithFeedback(), v8::internal::BinaryOpAssembler::Generate_BinaryOperationWithFeedback(), v8::internal::HandlerBuiltinsAssembler::Generate_ElementsTransitionAndStore(), v8::internal::HandlerBuiltinsAssembler::Generate_StoreFastElementIC(), v8::internal::AccessorAssembler::GenerateCloneObjectIC(), v8::internal::AccessorAssembler::GenericElementLoad(), v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::CodeStubAssembler::GrowElementsCapacity(), v8::internal::AccessorAssembler::HandleLoadAccessor(), v8::internal::AccessorAssembler::HandleLoadCallbackProperty(), v8::internal::AccessorAssembler::HandleLoadField(), v8::internal::AccessorAssembler::HandleLoadICHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerHasNamedCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), v8::internal::AccessorAssembler::HandlePolymorphicCase(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICNativeDataProperty(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::HandleStoreICSmiHandlerCase(), v8::internal::CodeStubAssembler::IncrementCallCount(), v8::internal::CodeStubAssembler::InitializeAllocationMemento(), v8::internal::CodeStubAssembler::InitializeJSObjectBodyWithSlackTracking(), v8::internal::CodeStubAssembler::IntPtrRoundUpToPowerOfTwo32(), v8::internal::AccessorAssembler::KeyedLoadIC(), v8::internal::AccessorAssembler::KeyedLoadICGeneric(), v8::internal::AccessorAssembler::KeyedLoadICPolymorphicName(), v8::internal::KeyedStoreGenericAssembler::KeyedStoreGeneric(), v8::internal::AccessorAssembler::KeyedStoreIC(), v8::internal::AccessorAssembler::LoadGlobalIC(), v8::internal::AccessorAssembler::LoadGlobalIC_TryHandlerCase(), v8::internal::AccessorAssembler::LoadGlobalIC_TryPropertyCellCase(), v8::internal::AccessorAssembler::LoadIC(), v8::internal::AccessorAssembler::LoadIC_BytecodeHandler(), v8::internal::AccessorAssembler::LoadSuperIC(), v8::internal::CodeStubAssembler::LookupBinary(), v8::internal::CodeStubAssembler::LookupLinear(), v8::internal::LazyBuiltinsAssembler::MaybeTailCallOptimizedCodeSlot(), v8::internal::CodeStubAssembler::NameDictionaryLookup(), v8::internal::CodeStubAssembler::NumberDictionaryLookup(), v8::internal::CodeStubAssembler::NumberToString(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::CodeStubAssembler::StoreFieldsNoWriteBarrier(), v8::internal::AccessorAssembler::StoreGlobalIC(), v8::internal::AccessorAssembler::StoreGlobalIC_PropertyCellCase(), v8::internal::AccessorAssembler::StoreIC(), v8::internal::AccessorAssembler::StoreInArrayLiteralIC(), v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::StringBuiltinsAssembler::StringEqual_Loop(), v8::internal::CodeStubAssembler::TryGrowElementsCapacity(), v8::internal::AccessorAssembler::TryMonomorphicCase(), v8::internal::CodeStubAssembler::TryToName(), and v8::internal::AccessorAssembler::UpdateMayHaveInterestingProperty().
ConstructJS()
template<class... TArgs>
TNode<JSAny> v8::internal::compiler::CodeAssembler::ConstructJS (Builtin builtin, TNode< Context > context, TNode< Object > function, TNode< JSAny > new_target, TArgs... args) [inline]
Definition at line 1507 of file code-assembler.h.
                                          {
    // Consider creating a Builtins::IsAnyConstruct if we ever expect other
    // Construct builtins here.
    DCHECK_EQ(builtin, Builtin::kConstruct);
    Callable callable = Builtins::CallableFor(isolate(), builtin);
    int argc = JSParameterCount(static_cast<int>(sizeof...(args)));
    TNode<Int32T> arity = Int32Constant(argc);
    TNode<JSAny> receiver = CAST(LoadRoot(RootIndex::kUndefinedValue));
    TNode<Code> target = HeapConstantNoHole(callable.code());
    return CAST(CallJSStubImpl(callable.descriptor(), target, context, function,
                               new_target, arity, std::nullopt,
                               {receiver, args...}));
  }
References v8::base::args, v8::internal::Builtins::CallableFor(), CAST, v8::internal::Callable::code(), DCHECK_EQ, v8::internal::Callable::descriptor(), v8::internal::compiler::HeapConstantNoHole(), and v8::internal::JSParameterCount().
DebugBreak()
void v8::internal::compiler::CodeAssembler::DebugBreak ()
Definition at line 657 of file code-assembler.cc.
{ raw_assembler()->DebugBreak(); }
References v8::internal::compiler::RawMachineAssembler::DebugBreak(), and raw_assembler().
Referenced by v8::internal::StringBuiltinsAssembler::DerefIndirectString(), and v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase().
DynamicJSParameterCount()
TNode< Uint16T > v8::internal::compiler::CodeAssembler::DynamicJSParameterCount ()
Definition at line 517 of file code-assembler.cc.
                                                      {
  DCHECK(HasDynamicJSParameterCount());
  return UncheckedCast<Uint16T>(raw_assembler()->dynamic_js_parameter_count());
}
References v8::internal::DCHECK(), HasDynamicJSParameterCount(), and raw_assembler().
Referenced by v8::internal::CodeStubArguments::PopAndReturn().
EmitComment()
void v8::internal::compiler::CodeAssembler::EmitComment (std::string msg) [private]
Definition at line 661 of file code-assembler.cc.
                                             {
  if (!v8_flags.code_comments) return;
  raw_assembler()->Comment(str);
}
References v8::internal::compiler::RawMachineAssembler::Comment(), raw_assembler(), and v8::internal::v8_flags.
ExternalConstant()
TNode< ExternalReference > v8::internal::compiler::CodeAssembler::ExternalConstant (ExternalReference address)
Definition at line 397 of file code-assembler.cc.
                               {
  return UncheckedCast<ExternalReference>(
      raw_assembler()->ExternalConstant(address));
}
References raw_assembler().
Referenced by v8::internal::CodeStubAssembler::Allocate(), v8::internal::CodeStubAssembler::ArrayBufferMaxByteLength(), v8::internal::TypedArrayBuiltinsAssembler::CallCCopyFastNumberJSArrayElementsToTypedArray(), v8::internal::TypedArrayBuiltinsAssembler::CallCCopyTypedArrayElementsSlice(), v8::internal::TypedArrayBuiltinsAssembler::CallCCopyTypedArrayElementsToTypedArray(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemcpy(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemmove(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemset(), v8::internal::TypedArrayBuiltinsAssembler::CallCRelaxedMemcpy(), v8::internal::TypedArrayBuiltinsAssembler::CallCRelaxedMemmove(), v8::internal::CollectionsBuiltinsAssembler::CallGetHashRaw(), v8::internal::CollectionsBuiltinsAssembler::CallGetOrCreateHashRaw(), v8::internal::ArrayBuiltinsAssembler::CallJSArrayArrayJoinConcatToSequentialString(), CallRuntimeImpl(), v8::internal::interpreter::InterpreterAssembler::CallRuntimeN(), v8::internal::StringBuiltinsAssembler::CallSearchStringRaw(), v8::internal::CodeStubAssembler::ComputeSeededHash(), v8::internal::CodeStubAssembler::CopyElements(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteAddAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteCompare(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteDivAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteModAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteMulAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteSubAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseAndNegNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseAndPosNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseAndPosPosAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseOrNegNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseOrPosNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseOrPosPosAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseXorNegNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseXorPosNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseXorPosPosAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppLeftShiftAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppRightShiftAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppRightShiftResultLength(), v8::internal::WeakCollectionsBuiltinsAssembler::CreateIdentityHash(), v8::internal::CodeStubAssembler::DecrementCounter(), v8::internal::interpreter::InterpreterAssembler::DispatchTablePointer(), v8::internal::CodeStubAssembler::EmptyBackingStoreBufferConstant(), v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), v8::internal::CodeStubAssembler::ExternalOneByteStringGetChars(), v8::internal::CodeStubAssembler::ExternalTwoByteStringGetChars(), v8::internal::CodeStubAssembler::FillFixedArrayWithSmiZero(), v8::internal::CodeStubAssembler::FillFixedDoubleArrayWithZero(), v8::internal::RegExpBuiltinsAssembler::FreeRegExpResultVector(), v8::internal::DateBuiltinsAssembler::Generate_DatePrototype_GetField(), v8::internal::WriteBarrierCodeStubAssembler::GenerateEphemeronKeyBarrier(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GeneratePackedDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::CodeStubAssembler::GetCoverageInfo(), v8::internal::MicrotaskQueueBuiltinsAssembler::GetCurrentContext(), v8::internal::MicrotaskQueueBuiltinsAssembler::GetEnteredContextCount(), v8::internal::CodeStubAssembler::GetPendingMessage(), v8::internal::CodeStubAssembler::GotoIfForceSlowPath(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::CodeStubAssembler::HasAsyncEventDelegate(), v8::internal::StringBuiltinsAssembler::HasUnpairedSurrogate(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierMajor(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierMinor(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierShared(), v8::internal::CodeStubAssembler::IncrementCounter(), v8::internal::WriteBarrierCodeStubAssembler::IndirectPointerWriteBarrier(), v8::internal::WriteBarrierCodeStubAssembler::InsertIntoRememberedSet(), v8::internal::CodeStubAssembler::IntlAsciiCollationWeightsL1(), v8::internal::CodeStubAssembler::IntlAsciiCollationWeightsL3(), v8::internal::AccessorAssembler::InvalidateValidityCellIfPrototype(), v8::internal::CodeStubAssembler::IsDebugActive(), v8::internal::WriteBarrierCodeStubAssembler::IsMarking(), v8::internal::WriteBarrierCodeStubAssembler::IsMinorMarking(), IsolateField(), v8::internal::WriteBarrierCodeStubAssembler::IsSharedSpaceIsolate(), v8::internal::CodeStubAssembler::LoadNameRawHash(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), LoadRoot(), v8::internal::CodeStubAssembler::MoveElements(), v8::internal::CodeStubAssembler::NameDictionaryLookupWithForwardIndex(), v8::internal::CodeStubAssembler::PerformStackCheck(), v8::internal::CodeStubAssembler::PromiseHookFlags(), v8::internal::CodeStubAssembler::RefillMathRandom(), v8::internal::RegExpBuiltinsAssembler::RegExpExecAtom(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::StringBuiltinsAssembler::ReplaceUnpairedSurrogates(), v8::internal::MicrotaskQueueBuiltinsAssembler::RewindEnteredContext(), v8::internal::StringBuiltinsAssembler::SearchOneByteInOneByteString(), v8::internal::CodeStubAssembler::SetCounter(), v8::internal::MicrotaskQueueBuiltinsAssembler::SetCurrentContext(), v8::internal::CodeStubAssembler::SetPendingMessage(), v8::internal::WriteBarrierCodeStubAssembler::SharedBarrierSlow(), v8::internal::CodeStubAssembler::SmiLexicographicCompare(), StoreRoot(), v8::internal::CodeStubAssembler::StoreSandboxedPointerToObject(), v8::internal::WasmBuiltinsAssembler::StringToFloat64(), v8::internal::CodeStubAssembler::StringWriteToFlatOneByte(), v8::internal::CodeStubAssembler::StringWriteToFlatTwoByte(), TailCallRuntimeImpl(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::interpreter::InterpreterAssembler::TraceBytecodeDispatch(), v8::internal::CodeStubAssembler::TryInternalizeString(), v8::internal::AccessorAssembler::TryProbeStubCacheTable(), and v8::internal::CodeStubAssembler::TryToName().
ExternalPointerHandleNullConstant()
TNode<ExternalPointerHandleT> v8::internal::compiler::CodeAssembler::ExternalPointerHandleNullConstant () [inline]
Definition at line 649 of file code-assembler.h.
                                                                    {
    return ReinterpretCast<ExternalPointerHandleT>(Uint32Constant(0));
  }
Referenced by v8::internal::TypedArrayBuiltinsAssembler::AllocateEmptyOnHeapBuffer().
factory()
Factory * v8::internal::compiler::CodeAssembler::factory () const
Definition at line 1671 of file code-assembler.cc.
{ return isolate()->factory(); }
References v8::internal::Isolate::factory(), and isolate().
Referenced by v8::internal::AsyncBuiltinsAssembler::Await(), v8::internal::ObjectBuiltinsAssembler::FromPropertyDescriptor(), v8::internal::IteratorBuiltinsAssembler::GetIterator(), v8::internal::IteratorBuiltinsAssembler::GetIteratorMethod(), v8::internal::StringBuiltinsAssembler::IndexOfDollarChar(), IsNullConstant(), IsUndefinedConstant(), v8::internal::IteratorBuiltinsAssembler::IteratorComplete(), v8::internal::IteratorBuiltinsAssembler::IteratorValue(), NumberConstant(), v8::internal::RegExpBuiltinsAssembler::SlowLoadLastIndex(), v8::internal::RegExpBuiltinsAssembler::SlowStoreLastIndex(), and StringConstant().
Float32Constant()
TNode< Float32T > v8::internal::compiler::CodeAssembler::Float32Constant (double value)
Definition at line 407 of file code-assembler.cc.
                                                           {
  return UncheckedCast<Float32T>(jsgraph()->Float32Constant(value));
}
References jsgraph(), and v8::internal::value.
Float64Constant()
TNode< Float64T > v8::internal::compiler::CodeAssembler::Float64Constant (double value)
Definition at line 411 of file code-assembler.cc.
                                                           {
  return UncheckedCast<Float64T>(jsgraph()->Float64Constant(value));
}
References jsgraph(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::AllocateContextCell(), v8::internal::CodeStubAssembler::BranchIfToBooleanIsTrue(), v8::internal::CodeStubAssembler::Float64AlmostEqual(), v8::internal::CodeStubAssembler::Float64Ceil(), v8::internal::CodeStubAssembler::Float64Floor(), v8::internal::CodeStubAssembler::Float64Round(), v8::internal::CodeStubAssembler::Float64RoundToEven(), v8::internal::CodeStubAssembler::Float64Trunc(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GeneratePackedDoubles(), v8::internal::CodeStubAssembler::IsHeapNumberPositive(), v8::internal::CodeStubAssembler::IsInteger(), v8::internal::CodeStubAssembler::IsNumberNormalized(), v8::internal::CodeStubAssembler::IsSafeInteger(), v8::internal::CollectionsBuiltinsAssembler::NormalizeNumberKey(), v8::internal::CodeStubAssembler::ToUint32(), and v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16().
GetJSContextParameter()
TNode< Context > v8::internal::compiler::CodeAssembler::GetJSContextParameter ()
Definition at line 506 of file code-assembler.cc.
                                                    {
  auto call_descriptor = raw_assembler()->call_descriptor();
  DCHECK(call_descriptor->IsJSFunctionCall());
  return Parameter<Context>(Linkage::GetJSCallContextParamIndex(
      static_cast<int>(call_descriptor->JSParameterCount())));
}
References v8::internal::compiler::RawMachineAssembler::call_descriptor(), v8::internal::DCHECK(), v8::internal::compiler::Linkage::GetJSCallContextParamIndex(), and raw_assembler().
GetMacroSourcePositionStack()
const std::vector< FileAndLine > & v8::internal::compiler::CodeAssembler::GetMacroSourcePositionStack () const
Definition at line 683 of file code-assembler.cc.
          {
  return state_->macro_call_stack_;
}
References v8::internal::compiler::CodeAssemblerState::macro_call_stack_, and state_.
Goto() [1/2]
template<class... T, class... Args>
void v8::internal::compiler::CodeAssembler::Goto (CodeAssemblerParameterizedLabel< T... > * label, Args... args) [inline]
Definition at line 831 of file code-assembler.h.
                                                                        {
    label->AddInputs(args...);
    Goto(label->plain_label());
  }
References v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::AddInputs(), v8::base::args, and v8::internal::compiler::CodeAssemblerParameterizedLabelBase::plain_label().
Goto() [2/2]
void v8::internal::compiler::CodeAssembler::Goto (Label * label)
Definition at line 1556 of file code-assembler.cc.
                                     {
  label->MergeVariables();
  raw_assembler()->Goto(label->label_);
}
References v8::internal::compiler::RawMachineAssembler::Goto(), v8::internal::compiler::CodeAssemblerLabel::label_, v8::internal::compiler::CodeAssemblerLabel::MergeVariables(), and raw_assembler().
Referenced by v8::internal::interpreter::InterpreterAssembler::AbortIfRegisterCountInvalid(), v8::internal::interpreter::InterpreterAssembler::AbortIfWordNotEqual(), v8::internal::BaseCollectionsAssembler::AddConstructorEntries(), v8::internal::BaseCollectionsAssembler::AddConstructorEntriesFromFastJSArray(), v8::internal::BaseCollectionsAssembler::AddConstructorEntriesFromIterable(), v8::internal::CollectionsBuiltinsAssembler::AddConstructorEntriesFromSet(), v8::internal::CollectionsBuiltinsAssembler::AddNewToOrderedHashTable(), v8::internal::CodeStubAssembler::AddToDictionary(), v8::internal::ObjectBuiltinsAssembler::AddToDictionaryIf(), v8::internal::CollectionsBuiltinsAssembler::AddToOrderedHashTable(), v8::internal::CollectionsBuiltinsAssembler::AddValueToKeyedGroup(), v8::internal::RegExpBuiltinsAssembler::AdvanceStringIndex(), v8::internal::CodeStubAssembler::AlignToAllocationAlignment(), v8::internal::StringBuiltinsAssembler::AllocAndCopyStringCharacters(), v8::internal::CodeStubAssembler::AllocateArrayList(), v8::internal::CodeStubAssembler::AllocateByteArray(), v8::internal::StringBuiltinsAssembler::AllocateConsString(), v8::internal::CodeStubAssembler::AllocateJSArray(), v8::internal::ProxiesCodeStubAssembler::AllocateProxy(), v8::internal::CodeStubAssembler::AllocateRaw(), v8::internal::RegExpBuiltinsAssembler::AllocateRegExpResult(), v8::internal::CodeStubAssembler::AllocateUninitializedJSArrayWithElements(), v8::internal::CodeStubAssembler::ArrayCreate(), v8::internal::CodeStubAssembler::ArrayListEnsureSpace(), v8::internal::AsyncBuiltinsAssembler::Await(), v8::internal::CodeStubAssembler::BigIntFromInt32Pair(), v8::internal::CodeStubAssembler::BigIntFromInt64(), v8::internal::CodeStubAssembler::BigIntFromUint32Pair(), v8::internal::CodeStubAssembler::BigIntFromUint64(), Branch(), v8::internal::StringBuiltinsAssembler::BranchIfCanDerefIndirectString(), v8::internal::CollectionsBuiltinsAssembler::BranchIfIterableWithOriginalValueSetIterator(), v8::internal::AccessorAssembler::BranchIfPrototypesHaveNoElements(), v8::internal::KeyedStoreGenericAssembler::BranchIfPrototypesMayHaveReadOnlyElements(), v8::internal::CodeStubAssembler::BuildAppendJSArray(), v8::internal::CallOrConstructBuiltinsAssembler::BuildConstructWithSpread(), v8::internal::CallOrConstructBuiltinsAssembler::CallFunctionTemplate(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithArrayLike(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithSpread(), v8::internal::CodeStubAssembler::ChangeFloat32ToTagged(), v8::internal::CodeStubAssembler::ChangeFloat64ToTagged(), v8::internal::CodeStubAssembler::ChangeInt32ToTagged(), v8::internal::CodeStubAssembler::ChangeNonNegativeNumberToUint32(), v8::internal::CodeStubAssembler::ChangeNumberToFloat64(), v8::internal::CodeStubAssembler::ChangeTaggedToFloat64(), v8::internal::CodeStubAssembler::ChangeUint32ToTagged(), v8::internal::CodeStubAssembler::ChangeUintPtrToTagged(), v8::internal::PrototypeCheckAssembler::CheckAndBranch(), v8::internal::ProxiesCodeStubAssembler::CheckDeleteTrapResult(), v8::internal::AccessorAssembler::CheckFieldType(), v8::internal::ProxiesCodeStubAssembler::CheckGetSetTrapResult(), v8::internal::ProxiesCodeStubAssembler::CheckHasTrapResult(), v8::internal::AccessorAssembler::CheckHeapObjectTypeMatchesDescriptor(), v8::internal::CodeStubAssembler::CheckPrototypeEnumCache(), v8::internal::SlowBoilerplateCloneAssembler::CloneElementsOfFixedArray(), v8::internal::CodeStubAssembler::CloneFastJSArray(), v8::internal::CodeStubAssembler::CloneIfMutablePrimitive(), v8::internal::SlowBoilerplateCloneAssembler::CloneIfObjectOrArray(), v8::internal::WeakCollectionsBuiltinsAssembler::Coefficient(), v8::internal::LazyBuiltinsAssembler::CompileLazy(), v8::internal::CollectionsBuiltinsAssembler::ComputeStringHash(), v8::internal::interpreter::InterpreterAssembler::Construct(), v8::internal::ArrayPopulatorAssembler::ConstructArrayLike(), v8::internal::RegExpBuiltinsAssembler::ConstructNewResultFromMatchInfo(), v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread(), v8::internal::CodeStubAssembler::CopyElements(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::ConstructorBuiltinsAssembler::CopyMutableHeapNumbersInObject(), v8::internal::CodeStubAssembler::CopyPropertyArrayValues(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchSingleArgument(), v8::internal::ConstructorBuiltinsAssembler::CreateEmptyArrayLiteral(), v8::internal::ConstructorBuiltinsAssembler::CreateRegExpLiteral(), v8::internal::ConstructorBuiltinsAssembler::CreateShallowObjectLiteral(), v8::internal::SharedArrayBufferBuiltinsAssembler::DebugCheckAtomicIndex(), v8::internal::interpreter::InterpreterAssembler::DecreaseInterruptBudget(), v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::StringBuiltinsAssembler::DerefIndirectString(), v8::internal::DeletePropertyBaseAssembler::DictionarySpecificDelete(), v8::internal::StringBuiltinsAssembler::DirectStringData(), v8::internal::CodeStubAssembler::DispatchMaybeObject(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::AccessorAssembler::EmitFastElementsBoundsCheck(), v8::internal::KeyedStoreGenericAssembler::EmitGenericElementStore(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), v8::internal::ExitPoint::ExitPoint(), v8::internal::interpreter::InterpreterAssembler::ExportParametersAndRegisterFile(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::CodeStubAssembler::ExtractFixedArray(), v8::internal::CodeStubAssembler::ExtractFixedDoubleArrayFillingHoles(), v8::internal::CodeStubAssembler::ExtractToFixedArray(), v8::internal::CodeStubAssembler::FastCloneJSObject(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FastGetOwnValuesOrEntries(), v8::internal::IteratorBuiltinsAssembler::FastIterableToList(), v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), v8::internal::ConstructorBuiltinsAssembler::FastNewObject(), v8::internal::KeyedStoreGenericAssembler::FindCandidateStoreICTransitionMapHandler(), v8::internal::WeakCollectionsBuiltinsAssembler::FindKeyIndex(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntry(), v8::internal::RegExpBuiltinsAssembler::FlagsGetter(), v8::internal::CodeStubAssembler::Float64AlmostEqual(), v8::internal::CodeStubAssembler::Float64Ceil(), v8::internal::CodeStubAssembler::Float64Floor(), v8::internal::CodeStubAssembler::Float64Round(), v8::internal::CodeStubAssembler::Float64RoundToEven(), v8::internal::CodeStubAssembler::Float64ToString(), v8::internal::CodeStubAssembler::Float64Trunc(), v8::internal::CodeStubAssembler::ForEachEnumerableOwnProperty(), v8::internal::RegExpBuiltinsAssembler::FreeRegExpResultVector(), v8::internal::ObjectBuiltinsAssembler::FromPropertyDescriptor(), v8::internal::ObjectBuiltinsAssembler::FromPropertyDetails(), v8::internal::ArrayIncludesIndexofAssembler::Generate(), v8::internal::BinaryOpAssembler::Generate_AddStringConstantInternalizeWithFeedback(), v8::internal::BinaryOpAssembler::Generate_AddWithFeedback(), v8::internal::BinaryOpAssembler::Generate_BinaryOperationWithFeedback(), v8::internal::BinaryOpAssembler::Generate_BitwiseBinaryOpWithOptionalFeedback(), v8::internal::BinaryOpAssembler::Generate_BitwiseBinaryOpWithSmiOperandAndOptionalFeedback(), v8::internal::BinaryOpAssembler::Generate_DivideWithFeedback(), v8::internal::HandlerBuiltinsAssembler::Generate_ElementsTransitionAndStore(), v8::internal::BinaryOpAssembler::Generate_SubtractWithFeedback(), v8::internal::CppBuiltinsAdaptorAssembler::GenerateAdaptor(), v8::internal::AccessorAssembler::GenerateCloneObjectIC(), v8::internal::AccessorAssembler::GenerateCloneObjectIC_Slow(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::GenerateMetaTableAccess(), v8::internal::ArrayIncludesIndexofAssembler::GeneratePackedDoubles(), v8::internal::StringBuiltinsAssembler::GenerateSeqStringRelationalComparison(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::StringBuiltinsAssembler::GenerateStringEqual(), v8::internal::StringBuiltinsAssembler::GenerateStringRelationalComparison(), v8::internal::WriteBarrierCodeStubAssembler::GenerationalBarrierSlow(), v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::ObjectBuiltinsAssembler::GetAccessorOrUndefined(), v8::internal::BaseCollectionsAssembler::GetAddFunction(), v8::internal::CallOrConstructBuiltinsAssembler::GetCompatibleReceiver(), v8::internal::CollectionsBuiltinsAssembler::GetEntriesIfFastCollectionOrIterable(), v8::internal::CollectionsBuiltinsAssembler::GetHash(), v8::internal::WeakCollectionsBuiltinsAssembler::GetHash(), v8::internal::CodeStubAssembler::GetImportMetaObject(), v8::internal::CodeStubAssembler::GetNonRabGsabElementsKind(), v8::internal::CodeStubArguments::GetOptionalArgumentValue(), v8::internal::CodeStubAssembler::GetSharedFunctionInfoCode(), v8::internal::StringBuiltinsAssembler::GetSubstitution(), v8::internal::BaseCollectionsAssembler::GotoIfCannotBeHeldWeakly(), HandleException(), v8::internal::AccessorAssembler::HandleLoadField(), v8::internal::AccessorAssembler::HandleLoadICProtoHandler(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), v8::internal::AccessorAssembler::HandlePolymorphicCase(), v8::internal::AccessorAssembler::HandleProtoHandler(), v8::internal::AccessorAssembler::HandleStoreFieldAndReturn(), v8::internal::AccessorAssembler::HandleStoreToProxy(), v8::internal::CodeStubAssembler::HeapObjectToFixedArray(), v8::internal::interpreter::InterpreterAssembler::ImportRegisterFile(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierMajor(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierMinor(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierShared(), v8::internal::CodeStubAssembler::InitializeJSObjectBodyWithSlackTracking(), v8::internal::RegExpBuiltinsAssembler::InitializeMatchInfoFromRegisters(), v8::internal::CodeStubAssembler::InsertEntry(), v8::internal::WriteBarrierCodeStubAssembler::InsertIntoRememberedSet(), v8::internal::CodeStubAssembler::InvalidateStringWrapperToPrimitiveProtector(), v8::internal::AccessorAssembler::InvalidateValidityCellIfPrototype(), v8::internal::CodeStubAssembler::IsAdditiveSafeInteger(), v8::internal::RegExpBuiltinsAssembler::IsFastRegExpNoPrototype(), v8::internal::CodeStubAssembler::IsFixedArrayWithKindOrEmpty(), v8::internal::CodeStubAssembler::IsNumberNormalized(), v8::internal::IteratorBuiltinsAssembler::Iterate(), v8::internal::IteratorBuiltinsAssembler::IteratorStep(), v8::internal::IteratorBuiltinsAssembler::IteratorValue(), v8::internal::AccessorAssembler::KeyedLoadIC(), v8::internal::AccessorAssembler::KeyedLoadICGeneric(), v8::internal::KeyedStoreGenericAssembler::KeyedStoreGeneric(), v8::internal::BaseCollectionsAssembler::LoadAndNormalizeFixedDoubleArrayElement(), v8::internal::WasmBuiltinsAssembler::LoadContextFromWasmOrJsFrame(), v8::internal::CodeStubAssembler::LoadElementAndPrepareForStore(), v8::internal::CodeStubAssembler::LoadFixedArrayBaseElementAsTagged(), v8::internal::AccessorAssembler::LoadIC_Noninlined(), v8::internal::CodeStubAssembler::LoadJSFunctionPrototype(), v8::internal::CodeStubAssembler::LoadJSReceiverIdentityHash(), v8::internal::CodeStubAssembler::LoadMapConstructor(), v8::internal::CodeStubAssembler::LoadModuleContext(), v8::internal::CodeStubAssembler::LoadNameRawHash(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), v8::internal::CodeStubAssembler::LoadSharedFunctionInfoBytecodeArray(), v8::internal::StringBuiltinsAssembler::LoadSurrogatePairAt(), v8::internal::CodeStubAssembler::LookupBinary(), v8::internal::CodeStubAssembler::LookupLinear(), v8::internal::KeyedStoreGenericAssembler::LookupPropertyOnPrototypeChain(), v8::internal::CodeStubAssembler::MakeFixedArrayCOW(), v8::internal::CollectionsBuiltinsAssembler::MapIteratorToList(), v8::internal::StringBuiltinsAssembler::MaybeDerefIndirectString(), v8::internal::CodeStubAssembler::MoveElements(), v8::internal::CodeStubAssembler::NameDictionaryLookup(), v8::internal::CodeStubAssembler::NameDictionaryLookupWithForwardIndex(), v8::internal::CollectionsBuiltinsAssembler::NextSkipHashTableHoles(), v8::internal::CodeStubAssembler::NonNumberToNumberOrNumeric(), v8::internal::CollectionsBuiltinsAssembler::NormalizeNumberKey(), v8::internal::CodeStubAssembler::NumberDictionaryLookup(), v8::internal::CodeStubAssembler::NumberMax(), v8::internal::CodeStubAssembler::NumberMin(), v8::internal::CodeStubAssembler::NumberToString(), v8::internal::interpreter::InterpreterAssembler::OnStackReplacement(), v8::internal::AccessorAssembler::OverwriteExistingFastDataProperty(), v8::internal::CodeStubAssembler::PerformStackCheck(), v8::internal::CodeStubAssembler::PlainPrimitiveToNumber(), v8::internal::CodeStubAssembler::PossiblyGrowElementsCapacity(), v8::internal::GrowableFixedArray::Push(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Single(), v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::RegExpBuiltinsAssembler::RegExpReplaceGlobalSimpleString(), v8::internal::GrowableFixedArray::Reserve(), v8::internal::MicrotaskQueueBuiltinsAssembler::RunAllPromiseHooks(), v8::internal::MicrotaskQueueBuiltinsAssembler::RunPromiseHook(), v8::internal::MicrotaskQueueBuiltinsAssembler::RunSingleMicrotask(), v8::internal::CollectionsBuiltinsAssembler::SameValueZeroSmi(), v8::internal::AccessorAssembler::ScriptContextTableLookup(), v8::internal::CollectionsBuiltinsAssembler::SetOrSetIteratorToList(), v8::internal::CollectionsBuiltinsAssembler::SetOrSetIteratorToSet(), v8::internal::WriteBarrierCodeStubAssembler::SharedBarrierSlow(), v8::internal::CodeStubAssembler::SharedValueBarrier(), v8::internal::CodeStubAssembler::SmiMod(), v8::internal::CodeStubAssembler::SmiMul(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), v8::internal::AccessorAssembler::StoreGlobalIC_PropertyCellCase(), v8::internal::AccessorAssembler::StoreJSSharedStructField(), v8::internal::KeyedStoreGenericAssembler::StoreProperty(), v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::CodeStubAssembler::StringCharCodeAt(), v8::internal::StringBuiltinsAssembler::StringEqual_FastLoop(), v8::internal::StringBuiltinsAssembler::StringEqual_Loop(), v8::internal::CodeStubAssembler::StringFromSingleCharCode(), v8::internal::StringBuiltinsAssembler::StringFromSingleUTF16EncodedCodePoint(), v8::internal::IteratorBuiltinsAssembler::StringListFromIterable(), v8::internal::StringBuiltinsAssembler::StringToArray(), v8::internal::CodeStubAssembler::StringToNumber(), v8::internal::StringBuiltinsAssembler::SubString(), v8::internal::CodeStubAssembler::TaggedToBigInt(), v8::internal::CodeStubAssembler::TaggedToWord32OrBigIntImpl(), v8::internal::CodeStubAssembler::ToBigInt(), v8::internal::CodeStubAssembler::ToBigIntConvertNumber(), v8::internal::ToDirectStringAssembler::ToDirect(), v8::internal::GrowableFixedArray::ToJSArray(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::CodeStubAssembler::ToNumber_Inline(), v8::internal::CodeStubAssembler::ToNumberOrNumeric(), v8::internal::interpreter::InterpreterAssembler::ToNumberOrNumeric(), v8::internal::CodeStubAssembler::ToObject_Inline(), v8::internal::CodeStubAssembler::ToString_Inline(), v8::internal::CodeStubAssembler::ToThisString(), v8::internal::CodeStubAssembler::ToThisValue(), v8::internal::CodeStubAssembler::ToUint32(), v8::internal::interpreter::InterpreterAssembler::TraceBytecodeDispatch(), v8::internal::CollectionsBuiltinsAssembler::Transition(), v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16(), v8::internal::CodeStubAssembler::TruncateNumberToWord32(), v8::internal::CodeStubAssembler::TruncateTaggedToFloat64(), v8::internal::KeyedStoreGenericAssembler::TryChangeToHoleyMapHelper(), v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad(), v8::internal::CodeStubAssembler::TryInternalizeString(), v8::internal::AccessorAssembler::TryMonomorphicCase(), v8::internal::CodeStubAssembler::TryPlainPrimitiveNonNumberToNumber(), v8::internal::AccessorAssembler::TryProbeStubCache(), v8::internal::AccessorAssembler::TryProbeStubCacheTable(), v8::internal::KeyedStoreGenericAssembler::TryRewriteElements(), v8::internal::CodeStubAssembler::TrySmiDiv(), v8::internal::CodeStubAssembler::TryTaggedToInt32AsIntPtr(), v8::internal::ToDirectStringAssembler::TryToDirect(), v8::internal::CodeStubAssembler::TryToName(), v8::internal::ToDirectStringAssembler::TryToSequential(), v8::internal::ArrayBuiltinsAssembler::TypedArrayMapProcessor(), v8::internal::ArrayBuiltinsAssembler::TypedArrayMapResultGenerator(), v8::internal::AccessorAssembler::UpdateMayHaveInterestingProperty(), v8::internal::TypedArrayBuiltinsAssembler::ValidateTypedArrayAndGetLength(), v8::internal::ArrayBuiltinsAssembler::VisitAllTypedArrayElements(), v8::internal::WriteBarrierCodeStubAssembler::WriteBarrierDuringMarking(), and v8::internal::compiler::ScopedExceptionHandler::~ScopedExceptionHandler().
GotoIf()
void v8::internal::compiler::CodeAssembler::GotoIf (TNode< IntegralT > condition, Label * true_label, GotoHint goto_hint = GotoHint::kNone)
Definition at line 1561 of file code-assembler.cc.
                                               {
  Label false_label(this);
  BranchHint branch_hint = BranchHint::kNone;
  if (goto_hint == GotoHint::kLabel) {
    branch_hint = BranchHint::kTrue;
  } else if (goto_hint == GotoHint::kFallthrough) {
    branch_hint = BranchHint::kFalse;
  }
  Branch(condition, true_label, &false_label, branch_hint);
  Bind(&false_label);
}
References Bind(), Branch(), v8::internal::kFallthrough, v8::internal::kFalse, v8::internal::kLabel, v8::internal::kNone, and v8::internal::kTrue.
Referenced by v8::internal::BaseCollectionsAssembler::AddConstructorEntries(), v8::internal::BaseCollectionsAssembler::AddConstructorEntriesFromFastJSArray(), v8::internal::CollectionsBuiltinsAssembler::AddNewToOrderedHashTable(), v8::internal::CodeStubAssembler::AddToDictionary(), v8::internal::CollectionsBuiltinsAssembler::AddToOrderedHashTable(), v8::internal::StringBuiltinsAssembler::AllocAndCopyStringCharacters(), v8::internal::CodeStubAssembler::AllocateByteArray(), v8::internal::ProxiesCodeStubAssembler::AllocateProxy(), v8::internal::CodeStubAssembler::AllocateRaw(), v8::internal::RegExpBuiltinsAssembler::AllocateRegExpResult(), v8::internal::CodeStubAssembler::AllocateUninitializedJSArrayWithElements(), v8::internal::CodeStubAssembler::ArrayListEnsureSpace(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::AsyncBuiltinsAssembler::Await(), v8::internal::CodeStubAssembler::BigIntFromInt32Pair(), v8::internal::CodeStubAssembler::BigIntFromInt64(), v8::internal::CodeStubAssembler::BigIntFromUint32Pair(), v8::internal::CodeStubAssembler::BigIntFromUint64(), v8::internal::StringBuiltinsAssembler::BranchIfCanDerefIndirectString(), v8::internal::RegExpBuiltinsAssembler::BranchIfFastRegExp(), v8::internal::CodeStubAssembler::BranchIfHasPrototypeProperty(), v8::internal::CollectionsBuiltinsAssembler::BranchIfIterableWithOriginalKeyOrValueMapIterator(), v8::internal::CollectionsBuiltinsAssembler::BranchIfIterableWithOriginalValueSetIterator(), v8::internal::CodeStubAssembler::BranchIfJSReceiver(), v8::internal::AccessorAssembler::BranchIfPrototypesHaveNoElements(), v8::internal::KeyedStoreGenericAssembler::BranchIfPrototypesMayHaveReadOnlyElements(), v8::internal::StringBuiltinsAssembler::BranchIfStringPrimitiveWithNoCustomIteration(), v8::internal::CodeStubAssembler::BranchIfToBooleanIsTrue(), v8::internal::CodeStubAssembler::BuildAppendJSArray(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithArrayLike(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithSpread(), v8::internal::CodeStubAssembler::ChangeNumberToFloat64(), v8::internal::ProxiesCodeStubAssembler::CheckDeleteTrapResult(), v8::internal::AccessorAssembler::CheckFieldType(), v8::internal::ProxiesCodeStubAssembler::CheckGetSetTrapResult(), v8::internal::ProxiesCodeStubAssembler::CheckHasTrapResult(), v8::internal::AccessorAssembler::CheckHeapObjectTypeMatchesDescriptor(), v8::internal::CodeStubAssembler::CheckPrototypeEnumCache(), v8::internal::AccessorAssembler::CheckPrototypeValidityCell(), v8::internal::CodeStubAssembler::CloneFastJSArray(), v8::internal::CodeStubAssembler::CloneIfMutablePrimitive(), v8::internal::SlowBoilerplateCloneAssembler::CloneIfObjectOrArray(), v8::internal::WeakCollectionsBuiltinsAssembler::Coefficient(), v8::internal::LazyBuiltinsAssembler::CompileLazy(), v8::internal::interpreter::InterpreterAssembler::Construct(), v8::internal::ArrayPopulatorAssembler::ConstructArrayLike(), v8::internal::interpreter::InterpreterAssembler::ConstructForwardAllArgs(), v8::internal::RegExpBuiltinsAssembler::ConstructNewResultFromMatchInfo(), v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread(), v8::internal::ConstructorBuiltinsAssembler::CopyMutableHeapNumbersInObject(), v8::internal::CodeStubAssembler::CopyNameDictionary(), v8::internal::CodeStubAssembler::CopyPropertyArrayValues(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchSingleArgument(), v8::internal::ConstructorBuiltinsAssembler::CreateEmptyArrayLiteral(), v8::internal::ConstructorBuiltinsAssembler::CreateRegExpLiteral(), v8::internal::ConstructorBuiltinsAssembler::CreateShallowObjectLiteral(), v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::DeletePropertyBaseAssembler::DeleteDictionaryProperty(), v8::internal::DeletePropertyBaseAssembler::DictionarySpecificDelete(), v8::internal::CodeStubAssembler::DispatchMaybeObject(), v8::internal::AccessorAssembler::EmitAccessCheck(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::AccessorAssembler::EmitFastElementsBoundsCheck(), v8::internal::KeyedStoreGenericAssembler::EmitGenericElementStore(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::CodeStubAssembler::EnsureOnlyHasSimpleProperties(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::CodeStubAssembler::ExtractFixedArray(), v8::internal::CodeStubAssembler::FastCloneJSObject(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FastGetOwnValuesOrEntries(), v8::internal::IteratorBuiltinsAssembler::FastIterableToList(), v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), v8::internal::ConstructorBuiltinsAssembler::FastNewObject(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FinalizeValuesOrEntriesJSArray(), v8::internal::WeakCollectionsBuiltinsAssembler::FindKeyIndexForInsertion(), v8::internal::WeakCollectionsBuiltinsAssembler::FindKeyIndexForKey(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntry(), v8::internal::CodeStubAssembler::Float64AlmostEqual(), v8::internal::CodeStubAssembler::Float64Ceil(), v8::internal::CodeStubAssembler::Float64Floor(), v8::internal::CodeStubAssembler::Float64Round(), v8::internal::CodeStubAssembler::Float64RoundToEven(), v8::internal::CodeStubAssembler::Float64Trunc(), v8::internal::CodeStubAssembler::ForEachEnumerableOwnProperty(), v8::internal::RegExpBuiltinsAssembler::FreeRegExpResultVector(), v8::internal::ObjectBuiltinsAssembler::FromPropertyDescriptor(), v8::internal::ArrayIncludesIndexofAssembler::Generate(), v8::internal::BinaryOpAssembler::Generate_AddStringConstantInternalizeWithFeedback(), v8::internal::BinaryOpAssembler::Generate_AddWithFeedback(), v8::internal::BinaryOpAssembler::Generate_BinaryOperationWithFeedback(), v8::internal::DateBuiltinsAssembler::Generate_DatePrototype_GetField(), v8::internal::DateBuiltinsAssembler::Generate_IsDateCheck(), v8::internal::CppBuiltinsAdaptorAssembler::GenerateAdaptor(), v8::internal::AccessorAssembler::GenerateCloneObjectIC(), v8::internal::AccessorAssembler::GenerateCloneObjectIC_Slow(), v8::internal::BaseCollectionsAssembler::GenerateConstructor(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::ArrayBuiltinsAssembler::GenerateIteratingTypedArrayBuiltinBody(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::GenerateMetaTableAccess(), v8::internal::StringBuiltinsAssembler::GenerateSeqStringRelationalComparison(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::StringBuiltinsAssembler::GenerateStringEqual(), v8::internal::StringBuiltinsAssembler::GenerateStringRelationalComparison(), v8::internal::AccessorAssembler::GenericElementLoad(), v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::ObjectBuiltinsAssembler::GetAccessorOrUndefined(), v8::internal::BaseCollectionsAssembler::GetAddFunction(), v8::internal::CallOrConstructBuiltinsAssembler::GetCompatibleReceiver(), v8::internal::CodeStubAssembler::GetHeapObjectAssumeWeak(), v8::internal::IteratorBuiltinsAssembler::GetIterator(), v8::internal::CodeStubArguments::GetOptionalArgumentValue(), v8::internal::CodeStubAssembler::GetSharedFunctionInfoCode(), v8::internal::BaseCollectionsAssembler::GotoIfCannotBeHeldWeakly(), v8::internal::CodeStubAssembler::GotoIfForceSlowPath(), v8::internal::CodeStubAssembler::GotoIfLargeBigInt(), v8::internal::CodeStubAssembler::GotoIfMapHasSlowProperties(), v8::internal::CodeStubAssembler::GotoIfPrototypeRequiresRuntimeLookup(), v8::internal::CodeStubAssembler::GrowElementsCapacity(), v8::internal::AccessorAssembler::HandleLoadField(), v8::internal::AccessorAssembler::HandleLoadICHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICProtoHandler(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerHasNamedCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), v8::internal::AccessorAssembler::HandleProtoHandler(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase(), v8::internal::CodeStubAssembler::HeapObjectToFixedArray(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrier(), v8::internal::CodeStubAssembler::InitializeJSObjectBodyWithSlackTracking(), v8::internal::RegExpBuiltinsAssembler::InitializeMatchInfoFromRegisters(), v8::internal::GeneratorBuiltinsAssembler::InnerResume(), v8::internal::CodeStubAssembler::InvalidateStringWrapperToPrimitiveProtector(), v8::internal::AccessorAssembler::InvalidateValidityCellIfPrototype(), v8::internal::CodeStubAssembler::IsFixedArrayWithKindOrEmpty(), v8::internal::CodeStubAssembler::IsNumberNormalized(), v8::internal::WriteBarrierCodeStubAssembler::IsValueUnmarkedOrRecordSlot(), v8::internal::IteratorBuiltinsAssembler::IteratorStep(), v8::internal::AccessorAssembler::JumpIfDataProperty(), v8::internal::IntlBuiltinsAssembler::JumpIfStartsWithIgnoreCase(), v8::internal::AccessorAssembler::KeyedLoadIC(), v8::internal::AccessorAssembler::KeyedLoadICGeneric(), v8::internal::KeyedStoreGenericAssembler::KeyedStoreGeneric(), v8::internal::AccessorAssembler::KeyedStoreIC(), v8::internal::WriteBarrierCodeStubAssembler::LoadBucket(), v8::internal::WasmBuiltinsAssembler::LoadContextFromWasmOrJsFrame(), v8::internal::CodeStubAssembler::LoadDoubleStringCacheEntryValue(), v8::internal::CodeStubAssembler::LoadDoubleWithUndefinedAndHoleCheck(), v8::internal::CodeStubAssembler::LoadElementAndPrepareForStore(), v8::internal::AccessorAssembler::LoadGlobalIC(), v8::internal::AccessorAssembler::LoadGlobalIC_TryHandlerCase(), v8::internal::AccessorAssembler::LoadGlobalIC_TryPropertyCellCase(), v8::internal::AccessorAssembler::LoadIC(), v8::internal::AccessorAssembler::LoadIC_BytecodeHandler(), v8::internal::AccessorAssembler::LoadIC_NoFeedback(), v8::internal::AccessorAssembler::LoadIC_Noninlined(), v8::internal::CodeStubAssembler::LoadJSFunctionPrototype(), v8::internal::CodeStubAssembler::LoadJSReceiverIdentityHash(), v8::internal::CodeStubAssembler::LoadMapConstructor(), v8::internal::CodeStubAssembler::LoadModuleContext(), v8::internal::CodeStubAssembler::LoadNameHash(), v8::internal::CodeStubAssembler::LoadNameRawHash(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), v8::internal::WriteBarrierCodeStubAssembler::LoadSlotSet(), v8::internal::AccessorAssembler::LoadSuperIC(), v8::internal::AccessorAssembler::LoadSuperIC_NoFeedback(), v8::internal::StringBuiltinsAssembler::LoadSurrogatePairAt(), v8::internal::CodeStubAssembler::LookupBinary(), v8::internal::CodeStubAssembler::LookupLinear(), v8::internal::KeyedStoreGenericAssembler::LookupPropertyOnPrototypeChain(), v8::internal::CodeStubAssembler::MakeFixedArrayCOW(), v8::internal::StringBuiltinsAssembler::MaybeCallFunctionAtSymbol(), v8::internal::LazyBuiltinsAssembler::MaybeTailCallOptimizedCodeSlot(), v8::internal::CodeStubAssembler::NameDictionaryLookup(), v8::internal::CodeStubAssembler::NameDictionaryLookupWithForwardIndex(), v8::internal::CollectionsBuiltinsAssembler::NormalizeNumberKey(), v8::internal::CodeStubAssembler::NumberDictionaryLookup(), v8::internal::interpreter::InterpreterAssembler::OnStackReplacement(), v8::internal::AccessorAssembler::OverwriteExistingFastDataProperty(), v8::internal::MicrotaskQueueBuiltinsAssembler::PrepareForContext(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Single(), v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::RegExpBuiltinsAssembler::RegExpReplaceGlobalSimpleString(), v8::internal::GrowableFixedArray::Reserve(), v8::internal::ArrayIncludesIndexofAssembler::ReturnIfEmpty(), v8::internal::MicrotaskQueueBuiltinsAssembler::RunPromiseHook(), v8::internal::CollectionsBuiltinsAssembler::SameValueZeroBigInt(), v8::internal::CollectionsBuiltinsAssembler::SameValueZeroHeapNumber(), v8::internal::CollectionsBuiltinsAssembler::SameValueZeroSmi(), v8::internal::CollectionsBuiltinsAssembler::SameValueZeroString(), v8::internal::AccessorAssembler::ScriptContextTableLookup(), v8::internal::CodeStubAssembler::SharedValueBarrier(), v8::internal::CodeStubAssembler::SmiMod(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), v8::internal::AccessorAssembler::StoreGlobalIC(), v8::internal::AccessorAssembler::StoreGlobalIC_PropertyCellCase(), v8::internal::AccessorAssembler::StoreIC(), v8::internal::KeyedStoreGenericAssembler::StoreIC_NoFeedback(), v8::internal::AccessorAssembler::StoreInArrayLiteralIC(), v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromPreparedValue(), v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::StringBuiltinsAssembler::StringEqual_Core(), v8::internal::StringBuiltinsAssembler::StringEqual_FastLoop(), v8::internal::StringBuiltinsAssembler::StringEqual_Loop(), v8::internal::IteratorBuiltinsAssembler::StringListFromIterable(), v8::internal::CodeStubAssembler::StringToNumber(), v8::internal::StringBuiltinsAssembler::SubString(), v8::internal::CodeStubAssembler::SwissNameDictionaryIncreaseElementCountOrBailout(), v8::internal::CodeStubAssembler::TaggedToBigInt(), v8::internal::CodeStubAssembler::TaggedToWord32OrBigIntImpl(), v8::internal::CodeStubAssembler::ThrowIfNotCallable(), v8::internal::CodeStubAssembler::ThrowIfNotInstanceType(), v8::internal::CodeStubAssembler::ThrowIfNotJSReceiver(), v8::internal::CodeStubAssembler::ToBigInt(), v8::internal::CodeStubAssembler::ToBigIntConvertNumber(), v8::internal::GrowableFixedArray::ToJSArray(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::interpreter::InterpreterAssembler::ToNumberOrNumeric(), v8::internal::CodeStubAssembler::ToString_Inline(), v8::internal::CodeStubAssembler::ToThisString(), v8::internal::CodeStubAssembler::ToThisValue(), v8::internal::CollectionsBuiltinsAssembler::Transition(), v8::internal::KeyedStoreGenericAssembler::TryChangeToHoleyMap(), v8::internal::KeyedStoreGenericAssembler::TryChangeToHoleyMapHelper(), v8::internal::KeyedStoreGenericAssembler::TryChangeToHoleyMapMulti(), v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad(), v8::internal::CodeStubAssembler::TryFloat32ToSmi(), v8::internal::CodeStubAssembler::TryFloat64ToSmi(), v8::internal::CodeStubAssembler::TryGrowElementsCapacity(), v8::internal::CodeStubAssembler::TryInt32Mul(), v8::internal::CodeStubAssembler::TryInternalizeString(), v8::internal::CodeStubAssembler::TryIntPtrAdd(), v8::internal::CodeStubAssembler::TryIntPtrDiv(), v8::internal::CodeStubAssembler::TryIntPtrMod(), v8::internal::CodeStubAssembler::TryIntPtrMul(), v8::internal::CodeStubAssembler::TryIntPtrSub(), v8::internal::CollectionsBuiltinsAssembler::TryLookupOrderedHashTableIndex(), v8::internal::CodeStubAssembler::TryMatchPreallocatedNumberString(), v8::internal::CodeStubAssembler::TryMatchRootRange(), v8::internal::AccessorAssembler::TryMegaDOMCase(), v8::internal::CodeStubAssembler::TryPlainPrimitiveNonNumberToNumber(), v8::internal::AccessorAssembler::TryProbeStubCacheTable(), v8::internal::KeyedStoreGenericAssembler::TryRewriteElements(), v8::internal::CodeStubAssembler::TrySkipWriteBarrier(), v8::internal::CodeStubAssembler::TrySmiAbs(), v8::internal::CodeStubAssembler::TrySmiAdd(), v8::internal::CodeStubAssembler::TrySmiDiv(), v8::internal::CodeStubAssembler::TrySmiSub(), v8::internal::CodeStubAssembler::TryStoreArrayElement(), v8::internal::CodeStubAssembler::TryTaggedToFloat64(), v8::internal::ToDirectStringAssembler::TryToDirect(), v8::internal::CodeStubAssembler::TryToName(), v8::internal::ToDirectStringAssembler::TryToSequential(), v8::internal::CodeStubAssembler::Use(), v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateIntegerTypedArray(), and v8::internal::ArrayBuiltinsAssembler::VisitAllTypedArrayElements().
GotoIfNot()
void v8::internal::compiler::CodeAssembler::GotoIfNot (TNode< IntegralT > condition, Label * false_label, GotoHint goto_hint = GotoHint::kNone)
Definition at line 1574 of file code-assembler.cc.
                                                  {
  Label true_label(this);
  BranchHint branch_hint = BranchHint::kNone;
  if (goto_hint == GotoHint::kLabel) {
    branch_hint = BranchHint::kFalse;
  } else if (goto_hint == GotoHint::kFallthrough) {
    branch_hint = BranchHint::kTrue;
  }
  Branch(condition, &true_label, false_label, branch_hint);
  Bind(&true_label);
}
References Bind(), Branch(), v8::internal::kFallthrough, v8::internal::kFalse, v8::internal::kLabel, v8::internal::kNone, and v8::internal::kTrue.
Referenced by v8::internal::CodeStubAssembler::AddToDictionary(), v8::internal::ObjectBuiltinsAssembler::AddToDictionaryIf(), v8::internal::RegExpBuiltinsAssembler::AdvanceStringIndex(), v8::internal::StringBuiltinsAssembler::AllocateConsString(), v8::internal::CodeStubAssembler::AllocateRaw(), v8::internal::RegExpBuiltinsAssembler::AllocateRegExpResult(), v8::internal::AsyncBuiltinsAssembler::Await(), v8::internal::CodeStubAssembler::BasicLoadNumberDictionaryElement(), v8::internal::RegExpBuiltinsAssembler::BranchIfFastRegExp(), v8::internal::CollectionsBuiltinsAssembler::BranchIfIterableWithOriginalKeyOrValueMapIterator(), v8::internal::CollectionsBuiltinsAssembler::BranchIfIterableWithOriginalValueSetIterator(), v8::internal::AccessorAssembler::BranchIfPrototypesHaveNoElements(), v8::internal::StringBuiltinsAssembler::BranchIfStringPrimitiveWithNoCustomIteration(), v8::internal::CallOrConstructBuiltinsAssembler::CallFunctionTemplate(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithArrayLike(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithSpread(), v8::internal::CodeStubAssembler::ChangeTaggedToFloat64(), v8::internal::ShadowRealmBuiltinsAssembler::CheckAccessor(), v8::internal::PrototypeCheckAssembler::CheckAndBranch(), v8::internal::ProxiesCodeStubAssembler::CheckDeleteTrapResult(), v8::internal::AccessorAssembler::CheckDescriptorConsidersNumbersMutable(), v8::internal::CodeStubAssembler::CheckEnumCache(), v8::internal::ProxiesCodeStubAssembler::CheckGetSetTrapResult(), v8::internal::ProxiesCodeStubAssembler::CheckHasTrapResult(), v8::internal::CodeStubAssembler::CheckPrototypeEnumCache(), v8::internal::CodeStubAssembler::CloneFastJSArray(), v8::internal::CodeStubAssembler::CloneIfMutablePrimitive(), v8::internal::interpreter::InterpreterAssembler::Construct(), v8::internal::RegExpBuiltinsAssembler::ConstructNewResultFromMatchInfo(), v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchNoArgument(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchSingleArgument(), v8::internal::ConstructorBuiltinsAssembler::CreateRegExpLiteral(), v8::internal::ConstructorBuiltinsAssembler::CreateShallowArrayLiteral(), v8::internal::ConstructorBuiltinsAssembler::CreateShallowObjectLiteral(), v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::AccessorAssembler::EmitAccessCheck(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::AccessorAssembler::EmitFastElementsBoundsCheck(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::CodeStubAssembler::EnsureArrayPushable(), v8::internal::interpreter::InterpreterAssembler::ExportParametersAndRegisterFile(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FastGetOwnValuesOrEntries(), v8::internal::IteratorBuiltinsAssembler::FastIterableToList(), v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), v8::internal::KeyedStoreGenericAssembler::FindCandidateStoreICTransitionMapHandler(), v8::internal::CodeStubAssembler::Float64Ceil(), v8::internal::CodeStubAssembler::Float64Floor(), v8::internal::CodeStubAssembler::Float64Trunc(), v8::internal::CodeStubAssembler::ForEachEnumerableOwnProperty(), v8::internal::ArrayIncludesIndexofAssembler::Generate(), v8::internal::BinaryOpAssembler::Generate_AddStringConstantInternalizeWithFeedback(), v8::internal::BinaryOpAssembler::Generate_AddWithFeedback(), v8::internal::BinaryOpAssembler::Generate_BinaryOperationWithFeedback(), v8::internal::BinaryOpAssembler::Generate_BitwiseBinaryOpWithOptionalFeedback(), v8::internal::AccessorAssembler::GenerateCloneObjectIC(), v8::internal::AccessorAssembler::GenerateCloneObjectIC_Slow(), v8::internal::BaseCollectionsAssembler::GenerateConstructor(), v8::internal::ArrayBuiltinsAssembler::GenerateDispatchToArrayStub(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::ArrayBuiltinsAssembler::GenerateIteratingTypedArrayBuiltinBody(), v8::internal::ArrayIncludesIndexofAssembler::GeneratePackedDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::AccessorAssembler::GenericElementLoad(), v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::BaseCollectionsAssembler::GetAddFunction(), v8::internal::CallOrConstructBuiltinsAssembler::GetCompatibleReceiver(), v8::internal::WeakCollectionsBuiltinsAssembler::GetHash(), v8::internal::CodeStubAssembler::GetHeapObjectIfStrong(), v8::internal::CodeStubAssembler::GetImportMetaObject(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::GetOwnValuesOrEntries(), v8::internal::BaseCollectionsAssembler::GotoIfCannotBeHeldWeakly(), v8::internal::CodeStubAssembler::GotoIfLargeBigInt(), v8::internal::CodeStubAssembler::GotoIfNotDoubleStringCacheEntryKeyEqual(), v8::internal::AccessorAssembler::GotoIfNotSameNumberBitPattern(), v8::internal::AccessorAssembler::HandleLoadField(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), v8::internal::AccessorAssembler::HandlePolymorphicCase(), v8::internal::AccessorAssembler::HandleStoreFieldAndReturn(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICSmiHandlerCase(), v8::internal::StringBuiltinsAssembler::HasUnpairedSurrogate(), v8::internal::interpreter::InterpreterAssembler::ImportRegisterFile(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrier(), v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierMinor(), v8::internal::CodeStubAssembler::InsertEntry(), v8::internal::RegExpBuiltinsAssembler::IsFastRegExpNoPrototype(), v8::internal::CodeStubAssembler::IsNumberNormalized(), v8::internal::WriteBarrierCodeStubAssembler::IsValueUnmarkedOrRecordSlot(), v8::internal::IteratorBuiltinsAssembler::IteratorComplete(), v8::internal::IteratorBuiltinsAssembler::IteratorStep(), v8::internal::IteratorBuiltinsAssembler::IteratorValue(), v8::internal::AccessorAssembler::KeyedLoadIC(), v8::internal::AccessorAssembler::KeyedStoreIC(), v8::internal::AccessorAssembler::LoadGlobalIC_NoFeedback(), v8::internal::AccessorAssembler::LoadIC(), v8::internal::AccessorAssembler::LoadIC_BytecodeHandler(), v8::internal::AccessorAssembler::LoadIC_NoFeedback(), v8::internal::CodeStubAssembler::LoadJSFunctionPrototype(), v8::internal::CodeStubAssembler::LoadMapConstructor(), v8::internal::CodeStubAssembler::LoadSharedFunctionInfoBytecodeArray(), v8::internal::AccessorAssembler::LoadSuperIC(), v8::internal::StringBuiltinsAssembler::LoadSurrogatePairAt(), v8::internal::StringBuiltinsAssembler::MaybeCallFunctionAtSymbol(), v8::internal::LazyBuiltinsAssembler::MaybeTailCallOptimizedCodeSlot(), v8::internal::CodeStubAssembler::NameDictionaryLookupWithForwardIndex(), v8::internal::CollectionsBuiltinsAssembler::NextSkipHashTableHoles(), v8::internal::CollectionsBuiltinsAssembler::NormalizeNumberKey(), v8::internal::CodeStubAssembler::NumberToString(), v8::internal::interpreter::InterpreterAssembler::OnStackReplacement(), v8::internal::CodeStubAssembler::PlainPrimitiveToNumber(), v8::internal::CodeStubAssembler::PossiblyGrowElementsCapacity(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::StringBuiltinsAssembler::ReplaceUnpairedSurrogates(), v8::internal::CollectionsBuiltinsAssembler::SameValueZeroBigInt(), v8::internal::CollectionsBuiltinsAssembler::SameValueZeroHeapNumber(), v8::internal::CollectionsBuiltinsAssembler::SameValueZeroSmi(), v8::internal::CollectionsBuiltinsAssembler::SameValueZeroString(), v8::internal::CodeStubAssembler::SmiMod(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), v8::internal::AccessorAssembler::StoreGlobalIC_PropertyCellCase(), v8::internal::AccessorAssembler::StoreIC(), v8::internal::AccessorAssembler::StoreInArrayLiteralIC(), v8::internal::KeyedStoreGenericAssembler::StoreProperty(), v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::StringBuiltinsAssembler::StringEqual_Core(), v8::internal::IteratorBuiltinsAssembler::StringListFromIterable(), v8::internal::StringBuiltinsAssembler::StringToArray(), v8::internal::CodeStubAssembler::TaggedToBigInt(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::CodeStubAssembler::ToNumber_Inline(), v8::internal::CodeStubAssembler::ToNumberOrNumeric(), v8::internal::interpreter::InterpreterAssembler::ToNumberOrNumeric(), v8::internal::CodeStubAssembler::TruncateNumberToWord32(), v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad(), v8::internal::CodeStubAssembler::TryFloat32ToSmi(), v8::internal::CodeStubAssembler::TryFloat64ToAdditiveSafeInteger(), v8::internal::CodeStubAssembler::TryFloat64ToInt32(), v8::internal::CodeStubAssembler::TryFloat64ToSmi(), v8::internal::AccessorAssembler::TryMegaDOMCase(), v8::internal::AccessorAssembler::TryMonomorphicCase(), v8::internal::CodeStubAssembler::TryPlainPrimitiveNonNumberToNumber(), v8::internal::CodeStubAssembler::TryTaggedToFloat64(), v8::internal::CodeStubAssembler::TryTaggedToInt32AsIntPtr(), v8::internal::ToDirectStringAssembler::TryToDirect(), v8::internal::CodeStubAssembler::TryToName(), v8::internal::AccessorAssembler::UpdateMayHaveInterestingProperty(), and v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateIntegerTypedArray().
HandleException()
void v8::internal::compiler::CodeAssembler::HandleException (Node * result) [private]
Definition at line 1176 of file code-assembler.cc.
                                              {
  if (state_->exception_handler_labels_.empty()) return;
  CodeAssemblerExceptionHandlerLabel* label =
      state_->exception_handler_labels_.back();
  if (node->op()->HasProperty(Operator::kNoThrow)) {
    return;
  }
  Label success(this), exception(this, Label::kDeferred);
  success.MergeVariables();
  exception.MergeVariables();
  raw_assembler()->Continuations(node, success.label_, exception.label_);
  Bind(&exception);
  const Operator* op = raw_assembler()->common()->IfException();
  Node* exception_value = raw_assembler()->AddNode(op, node, node);
  label->AddInputs({CAST(exception_value)});
  Goto(label->plain_label());
  Bind(&success);
  raw_assembler()->AddNode(raw_assembler()->common()->IfSuccess(), node);
}
References v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::AddInputs(), v8::internal::compiler::RawMachineAssembler::AddNode(), Bind(), CAST, v8::internal::compiler::RawMachineAssembler::common(), v8::internal::compiler::RawMachineAssembler::Continuations(), v8::internal::compiler::CodeAssemblerState::exception_handler_labels_, Goto(), v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::CommonOperatorBuilder::IfException(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::compiler::Operator::kNoThrow, v8::internal::compiler::CodeAssemblerLabel::label_, v8::internal::compiler::CodeAssemblerLabel::MergeVariables(), v8::internal::compiler::Node::op(), v8::internal::compiler::CodeAssemblerParameterizedLabelBase::plain_label(), raw_assembler(), and state_.
Referenced by CallRuntimeImpl(), and CallStubN().
HasDynamicJSParameterCount()
bool v8::internal::compiler::CodeAssembler::HasDynamicJSParameterCount ()
Definition at line 513 of file code-assembler.cc.
                                               {
  return raw_assembler()->dynamic_js_parameter_count() != nullptr;
}
References v8::internal::compiler::RawMachineAssembler::dynamic_js_parameter_count(), and raw_assembler().
Referenced by DynamicJSParameterCount(), v8::internal::CodeStubArguments::MayHavePaddingArguments(), and SetDynamicJSParameterCount().
HeapConstantHole()
template<class Type >
TNode<Type> v8::internal::compiler::CodeAssembler::HeapConstantHole (Handle< Type > object) [inline]
Definition at line 631 of file code-assembler.h.
                                                    {
    return UncheckedCast<Type>(UntypedHeapConstantHole(object));
  }
Referenced by UntypedHeapConstantHole().
HeapConstantMaybeHole()
template<class Type >
TNode<Type> v8::internal::compiler::CodeAssembler::HeapConstantMaybeHole (Handle< Type > object) [inline]
Definition at line 627 of file code-assembler.h.
                                                         {
    return UncheckedCast<Type>(UntypedHeapConstantMaybeHole(object));
  }
Referenced by LoadRoot(), and UntypedHeapConstantMaybeHole().
HeapConstantNoHole()
template<class Type >
TNode<Type> v8::internal::compiler::CodeAssembler::HeapConstantNoHole (Handle< Type > object) [inline]
Definition at line 623 of file code-assembler.h.
                                                      {
    return UncheckedCast<Type>(UntypedHeapConstantNoHole(object));
  }
Referenced by v8::internal::ObjectBuiltinsAssembler::AddToDictionaryIf(), v8::internal::CodeStubAssembler::AllocateOrderedHashTableWithCapacity(), v8::internal::WeakCollectionsBuiltinsAssembler::AllocateTable(), BooleanConstant(), CallRuntimeImpl(), v8::internal::LazyBuiltinsAssembler::CompileLazy(), v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread(), v8::internal::BaseCollectionsAssembler::GenerateConstructor(), v8::internal::BaseCollectionsAssembler::GetAddFunction(), v8::internal::CodeStubAssembler::GetInstanceTypeMap(), v8::internal::CodeStubAssembler::GetSharedFunctionInfoCode(), v8::internal::StringBuiltinsAssembler::IndexOfDollarChar(), LoadRootMapWord(), NumberConstant(), v8::internal::CodeStubAssembler::PrintToStream(), v8::internal::RegExpBuiltinsAssembler::SlowStoreLastIndex(), StringConstant(), v8::internal::ArrayBuiltinsAssembler::TailCallArrayConstructorStub(), TailCallRuntimeImpl(), and UntypedHeapConstantNoHole().
Int32Add()
TNode<Int32T> v8::internal::compiler::CodeAssembler::Int32Add (TNode< Int32T > left, TNode< Int32T > right) [inline]
Definition at line 1152 of file code-assembler.h.
                                                                  {
    return Signed(Int32Add(static_cast<TNode<Word32T>>(left),
                           static_cast<TNode<Word32T>>(right)));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::interpreter::InterpreterAssembler::CallJSAndDispatch(), v8::internal::CodeStubAssembler::ChangeInt32ToTaggedNoOverflow(), v8::internal::CollectionsBuiltinsAssembler::ComputeUnseededHash(), v8::internal::interpreter::InterpreterAssembler::DecreaseInterruptBudget(), v8::internal::CodeStubAssembler::DoubleStringCacheEntryToOffset(), v8::internal::CppBuiltinsAdaptorAssembler::GenerateAdaptor(), v8::internal::ArrayBuiltinsAssembler::GenerateArrayNArgumentsConstructor(), v8::internal::CodeStubAssembler::IncrementCounter(), v8::internal::CodeStubAssembler::InitializeAllocationMemento(), v8::internal::WeakCollectionsBuiltinsAssembler::InsufficientCapacityToAdd(), v8::internal::WeakCollectionsBuiltinsAssembler::LoadNumberOfDeleted(), v8::internal::WeakCollectionsBuiltinsAssembler::LoadNumberOfElements(), v8::internal::StringBuiltinsAssembler::LoadSurrogatePairAt(), v8::internal::CodeStubAssembler::LookupBinary(), v8::internal::CollectionsBuiltinsAssembler::NextSkipHashTableHoles(), v8::internal::CodeStubAssembler::SmiFromInt32(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::AccessorAssembler::StubCachePrimaryOffset(), v8::internal::AccessorAssembler::StubCacheSecondaryOffset(), and v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad().
Int32Constant()
TNode< Int32T > v8::internal::compiler::CodeAssembler::Int32Constant (int32_t value)
Definition at line 297 of file code-assembler.cc.
                                                        {
  return UncheckedCast<Int32T>(jsgraph()->Int32Constant(value));
}
References jsgraph(), and v8::internal::value.
Referenced by v8::internal::BaseCollectionsAssembler::AddConstructorEntries(), v8::internal::RegExpBuiltinsAssembler::AdvanceStringIndex(), v8::internal::CodeStubAssembler::AllocateBigInt(), v8::internal::StringBuiltinsAssembler::AllocateConsString(), v8::internal::CodeStubAssembler::AllocateContextCell(), v8::internal::TypedArrayBuiltinsAssembler::AllocateEmptyOnHeapBuffer(), v8::internal::CodeStubAssembler::AllocateRawBigInt(), v8::internal::CodeStubAssembler::AllocateSeqOneByteString(), v8::internal::CodeStubAssembler::AllocateSeqTwoByteString(), v8::internal::CodeStubAssembler::AllocateSlicedString(), v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::CodeStubAssembler::BasicLoadNumberDictionaryElement(), v8::internal::CodeStubAssembler::BigIntFromInt32Pair(), v8::internal::CodeStubAssembler::BigIntFromInt64(), v8::internal::StringBuiltinsAssembler::BranchIfCanDerefIndirectString(), v8::internal::KeyedStoreGenericAssembler::BranchIfPrototypesMayHaveReadOnlyElements(), v8::internal::CodeStubAssembler::BranchIfToBooleanIsTrue(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReadUnaligned(), v8::internal::interpreter::InterpreterAssembler::CallJSAndDispatch(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructDoubleVarargs(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithArrayLike(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithSpread(), CallRuntimeImpl(), v8::internal::interpreter::InterpreterAssembler::CallRuntimeN(), v8::internal::PrototypeCheckAssembler::CheckAndBranch(), v8::internal::AccessorAssembler::CheckFieldType(), v8::internal::CodeStubAssembler::CloneFastJSArray(), v8::internal::CollectionsBuiltinsAssembler::ComputeUnseededHash(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::CodeStubAssembler::CountTrailingZeros32(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchNoArgument(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchSingleArgument(), v8::internal::RegExpMatchAllAssembler::CreateRegExpStringIterator(), v8::internal::DataViewBuiltinsAssembler::DataViewEncodeBigIntBits(), v8::internal::CodeStubAssembler::DecodeWord32(), v8::internal::interpreter::InterpreterAssembler::DecreaseInterruptBudget(), v8::internal::CodeStubAssembler::DecrementCounter(), v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::StringBuiltinsAssembler::DirectStringData(), v8::internal::HandlerBuiltinsAssembler::DispatchForElementsKindTransition(), v8::internal::CodeStubAssembler::DoesntHaveInstanceType(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::KeyedStoreGenericAssembler::EmitGenericElementStore(), v8::internal::CodeStubAssembler::EntryIndexToIndex(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::CodeStubAssembler::Float64ToString(), v8::internal::CodeStubAssembler::ForEachEnumerableOwnProperty(), v8::internal::ObjectBuiltinsAssembler::FromPropertyDescriptor(), v8::internal::ArrayIncludesIndexofAssembler::Generate(), v8::internal::CppBuiltinsAdaptorAssembler::GenerateAdaptor(), v8::internal::ArrayBuiltinsAssembler::GenerateArrayNArgumentsConstructor(), v8::internal::StringBuiltinsAssembler::GenerateStringRelationalComparison(), v8::internal::interpreter::InterpreterAssembler::GetContextAtDepth(), v8::internal::CodeStubAssembler::GetNonRabGsabElementsKind(), v8::internal::AccessorAssembler::HandleLoadAccessor(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandlePolymorphicCase(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::HandleStoreICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICSmiHandlerJSSharedStructFieldCase(), v8::internal::StringBuiltinsAssembler::HasUnpairedSurrogate(), v8::internal::CodeStubAssembler::IncrementCounter(), v8::internal::CodeStubAssembler::InitializeAllocationMemento(), v8::internal::CodeStubAssembler::InitializeJSObjectBodyWithSlackTracking(), v8::internal::CodeStubAssembler::InstanceTypeEqual(), v8::internal::CodeStubAssembler::IsCleared(), v8::internal::CodeStubAssembler::IsConsStringInstanceType(), v8::internal::CodeStubAssembler::IsCustomElementsReceiverInstanceType(), v8::internal::CodeStubAssembler::IsDebugActive(), v8::internal::CodeStubAssembler::IsDoubleElementsKind(), v8::internal::CodeStubAssembler::IsDoubleHole(), v8::internal::CodeStubAssembler::IsElementsKindGreaterThan(), v8::internal::CodeStubAssembler::IsElementsKindGreaterThanOrEqual(), v8::internal::CodeStubAssembler::IsElementsKindLessThanOrEqual(), v8::internal::CodeStubAssembler::IsExtensibleNonPrototypeMap(), v8::internal::CodeStubAssembler::IsExternalStringInstanceType(), v8::internal::CodeStubAssembler::IsFastElementsKind(), v8::internal::CodeStubAssembler::IsFastOrNonExtensibleOrSealedElementsKind(), v8::internal::CodeStubAssembler::IsFastSmiElementsKind(), v8::internal::CodeStubAssembler::IsFastSmiOrTaggedElementsKind(), v8::internal::CodeStubAssembler::IsFixedArraySubclass(), v8::internal::CodeStubAssembler::IsHashTable(), v8::internal::CodeStubAssembler::IsHoleyFastElementsKindForRead(), v8::internal::CodeStubAssembler::IsIndirectStringInstanceType(), v8::internal::CodeStubAssembler::IsInternalizedStringInstanceType(), v8::internal::CodeStubAssembler::IsJSObjectInstanceType(), v8::internal::CodeStubAssembler::IsJSReceiverInstanceType(), v8::internal::WriteBarrierCodeStubAssembler::IsMarking(), v8::internal::WriteBarrierCodeStubAssembler::IsMinorMarking(), v8::internal::CodeStubAssembler::IsName(), v8::internal::CodeStubAssembler::IsNameInstanceType(), v8::internal::IntlBuiltinsAssembler::IsNonAlpha(), v8::internal::CodeStubAssembler::IsNotWeakFixedArraySubclass(), v8::internal::CodeStubAssembler::IsOneByteStringInstanceType(), v8::internal::CodeStubAssembler::IsOneByteStringMap(), v8::internal::CodeStubAssembler::IsPrimitiveInstanceType(), v8::internal::AccessorAssembler::IsPropertyDetailsConst(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::IsPropertyKindAccessor(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::IsPropertyKindData(), v8::internal::CodeStubAssembler::IsSeqOneByteStringInstanceType(), v8::internal::CodeStubAssembler::IsSeqOneByteStringMap(), v8::internal::CodeStubAssembler::IsSequentialStringInstanceType(), v8::internal::WriteBarrierCodeStubAssembler::IsSharedSpaceIsolate(), v8::internal::CodeStubAssembler::IsSharedStringInstanceType(), v8::internal::CodeStubAssembler::IsSpecialReceiverInstanceType(), v8::internal::CodeStubAssembler::IsString(), v8::internal::CodeStubAssembler::IsStringInstanceType(), v8::internal::CodeStubAssembler::IsStringWrapperElementsKind(), v8::internal::CodeStubAssembler::IsStrong(), v8::internal::TypedArrayBuiltinsAssembler::IsUint8ElementsKind(), v8::internal::CodeStubAssembler::IsWeakOrCleared(), v8::internal::CodeStubAssembler::IsWeakReferenceTo(), v8::internal::CodeStubAssembler::JSAnyIsNotPrimitiveMap(), v8::internal::AccessorAssembler::JumpIfDataProperty(), v8::internal::IntlBuiltinsAssembler::JumpIfStartsWithIgnoreCase(), v8::internal::BaseCollectionsAssembler::LoadAndNormalizeFixedDoubleArrayElement(), v8::internal::CodeStubAssembler::LoadAndUntagBytecodeArrayLength(), v8::internal::CodeStubAssembler::LoadAndUntagFixedArrayBaseLengthAsUint32(), v8::internal::CodeStubAssembler::LoadAndUntagWeakFixedArrayLengthAsUint32(), v8::internal::CodeStubAssembler::LoadBytecodeArrayParameterCountWithoutReceiver(), v8::internal::WasmBuiltinsAssembler::LoadContextFromWasmOrJsFrame(), v8::internal::WeakCollectionsBuiltinsAssembler::LoadNumberOfDeleted(), v8::internal::WeakCollectionsBuiltinsAssembler::LoadNumberOfElements(), v8::internal::CodeStubAssembler::LoadSharedFunctionInfoBytecodeArray(), v8::internal::CodeStubAssembler::LoadSharedFunctionInfoTrustedData(), v8::internal::StringBuiltinsAssembler::LoadSurrogatePairAt(), v8::internal::CodeStubAssembler::LookupBinary(), v8::internal::CodeStubAssembler::NeedsAnyPromiseHooks(), v8::internal::CollectionsBuiltinsAssembler::NextSkipHashTableHoles(), v8::internal::interpreter::InterpreterAssembler::OnStackReplacement(), v8::internal::AccessorAssembler::OverwriteExistingFastDataProperty(), v8::internal::CodeStubAssembler::PrintToStream(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::interpreter::InterpreterAssembler::RegisterLocationInRegisterList(), v8::internal::StringBuiltinsAssembler::ReplaceUnpairedSurrogates(), v8::internal::interpreter::InterpreterAssembler::SaveBytecodeOffset(), v8::internal::CodeStubAssembler::SelectInt32Constant(), v8::internal::CodeStubAssembler::SetCounter(), v8::internal::CodeStubAssembler::SmiMod(), v8::internal::CodeStubAssembler::SmiMul(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::interpreter::InterpreterAssembler::StarDispatchLookahead(), v8::internal::CodeStubAssembler::StoreDoubleHole(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), v8::internal::AccessorAssembler::StoreGlobalIC_PropertyCellCase(), v8::internal::AccessorAssembler::StoreJSSharedStructField(), v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::StringBuiltinsAssembler::StringEqual_Core(), v8::internal::StringBuiltinsAssembler::StringEqual_FastLoop(), v8::internal::CodeStubAssembler::StringFromSingleCharCode(), v8::internal::CodeStubAssembler::StringFromSingleOneByteCharCode(), v8::internal::StringBuiltinsAssembler::StringFromSingleUTF16EncodedCodePoint(), v8::internal::AccessorAssembler::StubCachePrimaryOffset(), v8::internal::AccessorAssembler::StubCacheSecondaryOffset(), v8::internal::CodeStubAssembler::TaggedIsPositiveSmi(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::CodeStubAssembler::TaggedIsStrongHeapObject(), v8::internal::CodeStubAssembler::TaggedToBigInt(), v8::internal::CodeStubAssembler::ThrowIfNotInstanceType(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16(), v8::internal::KeyedStoreGenericAssembler::TryChangeToHoleyMap(), v8::internal::KeyedStoreGenericAssembler::TryChangeToHoleyMapMulti(), v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad(), v8::internal::CodeStubAssembler::TryFloat32ToSmi(), v8::internal::CodeStubAssembler::TryFloat64ToInt32(), v8::internal::CodeStubAssembler::TryFloat64ToSmi(), v8::internal::CodeStubAssembler::TryMatchPreallocatedNumberString(), v8::internal::CodeStubAssembler::TryMatchRootRange(), v8::internal::AccessorAssembler::TryMegaDOMCase(), v8::internal::CodeStubAssembler::TrySmiDiv(), v8::internal::ToDirectStringAssembler::TryToDirect(), v8::internal::interpreter::InterpreterAssembler::UpdateInterruptBudgetOnReturn(), v8::internal::CodeStubAssembler::UpdateWord32(), v8::internal::CodeStubAssembler::Use(), v8::internal::WriteBarrierCodeStubAssembler::UsesSharedHeap(), v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateIntegerTypedArray(), Word32Sar(), Word32Shr(), v8::internal::CodeStubAssembler::WordIsAligned(), and v8::internal::BigIntBuiltinsAssembler::WriteBigIntSignAndLength().
Int32FalseConstant()
TNode<BoolT> v8::internal::compiler::CodeAssembler::Int32FalseConstant () [inline]
Definition at line 643 of file code-assembler.h.
                                    {
    return ReinterpretCast<BoolT>(Int32Constant(0));
  }
Referenced by v8::internal::CodeStubAssembler::CloneFastJSArray(), v8::internal::CodeStubAssembler::ExtractFixedDoubleArrayFillingHoles(), v8::internal::CodeStubAssembler::ForEachEnumerableOwnProperty(), v8::internal::RegExpBuiltinsAssembler::IsFastRegExpNoPrototype(), v8::internal::CodeStubAssembler::IsFixedArrayWithKindOrEmpty(), v8::internal::CodeStubAssembler::IsHeapNumberUint32(), v8::internal::CodeStubAssembler::IsInteger(), v8::internal::CodeStubAssembler::IsJSSharedArray(), v8::internal::CodeStubAssembler::IsJSSharedStruct(), v8::internal::CodeStubAssembler::IsNumberNonNegativeSafeInteger(), v8::internal::CodeStubAssembler::IsNumberNormalized(), v8::internal::CodeStubAssembler::IsSafeInteger(), v8::internal::CodeStubAssembler::IsValidPositiveSmi(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), v8::internal::CodeStubAssembler::TaggedIsCallable(), and v8::internal::CodeStubAssembler::TaggedIsCode().
Int32Mul()
TNode<Int32T> v8::internal::compiler::CodeAssembler::Int32Mul (TNode< Int32T > left, TNode< Int32T > right) [inline]
Definition at line 1172 of file code-assembler.h.
                                                                  {
    return Signed(Int32Mul(static_cast<TNode<Word32T>>(left),
                           static_cast<TNode<Word32T>>(right)));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::interpreter::InterpreterAssembler::CallRuntimeN(), v8::internal::CollectionsBuiltinsAssembler::ComputeUnseededHash(), v8::internal::CodeStubAssembler::EntryIndexToIndex(), v8::internal::CollectionsBuiltinsAssembler::NextSkipHashTableHoles(), v8::internal::interpreter::InterpreterAssembler::OnStackReplacement(), and v8::internal::CodeStubAssembler::TrySmiDiv().
Int32PairAdd()
TNode< PairT< Word32T, Word32T > > v8::internal::compiler::CodeAssembler::Int32PairAdd (TNode< Word32T > lhs_lo_word, TNode< Word32T > lhs_hi_word, TNode< Word32T > rhs_lo_word, TNode< Word32T > rhs_hi_word)
Definition at line 740 of file code-assembler.cc.
                                                            {
  return UncheckedCast<PairT<Word32T, Word32T>>(raw_assembler()->Int32PairAdd(
      lhs_lo_word, lhs_hi_word, rhs_lo_word, rhs_hi_word));
}
References v8::internal::compiler::RawMachineAssembler::Int32PairAdd(), and raw_assembler().
Referenced by v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16().
Int32PairSub()
TNode< PairT< Word32T, Word32T > > v8::internal::compiler::CodeAssembler::Int32PairSub (TNode< Word32T > lhs_lo_word, TNode< Word32T > lhs_hi_word, TNode< Word32T > rhs_lo_word, TNode< Word32T > rhs_hi_word)
Definition at line 747 of file code-assembler.cc.
                                                            {
  return UncheckedCast<PairT<Word32T, Word32T>>(raw_assembler()->Int32PairSub(
      lhs_lo_word, lhs_hi_word, rhs_lo_word, rhs_hi_word));
}
References v8::internal::compiler::RawMachineAssembler::Int32PairSub(), and raw_assembler().
Referenced by v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16().
Int32Sub() [1/2]
TNode<Int32T> v8::internal::compiler::CodeAssembler::Int32Sub (TNode< Int32T > left, int right) [inline]
Definition at line 1250 of file code-assembler.h.
                                                        {
    return Int32Sub(left, Int32Constant(right));
  }
Int32Sub() [2/2]
TNode<Int32T> v8::internal::compiler::CodeAssembler::Int32Sub (TNode< Int32T > left, TNode< Int32T > right) [inline]
Definition at line 1167 of file code-assembler.h.
                                                                  {
    return Signed(Int32Sub(static_cast<TNode<Word32T>>(left),
                           static_cast<TNode<Word32T>>(right)));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::CodeStubAssembler::CountTrailingZeros32(), v8::internal::CodeStubAssembler::DecrementCounter(), v8::internal::CodeStubAssembler::Float64ToString(), v8::internal::interpreter::InterpreterAssembler::GetContextAtDepth(), v8::internal::CodeStubAssembler::GetNonRabGsabElementsKind(), v8::internal::AccessorAssembler::HandlePolymorphicCase(), v8::internal::CodeStubAssembler::InitializeJSObjectBodyWithSlackTracking(), v8::internal::WeakCollectionsBuiltinsAssembler::InsufficientCapacityToAdd(), v8::internal::IntlBuiltinsAssembler::IsNonAlpha(), v8::internal::CodeStubAssembler::LoadBytecodeArrayParameterCountWithoutReceiver(), v8::internal::CodeStubAssembler::LookupBinary(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad(), v8::internal::CodeStubAssembler::TryMatchRootRange(), v8::internal::interpreter::InterpreterAssembler::UpdateInterruptBudget(), and v8::internal::interpreter::InterpreterAssembler::UpdateInterruptBudgetOnReturn().
Int32TrueConstant()
TNode<BoolT> v8::internal::compiler::CodeAssembler::Int32TrueConstant () [inline]
Definition at line 640 of file code-assembler.h.
                                   {
    return ReinterpretCast<BoolT>(Int32Constant(1));
  }
Referenced by v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::CodeStubAssembler::ExtractFixedDoubleArrayFillingHoles(), v8::internal::CodeStubAssembler::ForEachEnumerableOwnProperty(), v8::internal::CodeStubAssembler::IsFixedArrayWithKindOrEmpty(), v8::internal::CodeStubAssembler::IsInteger(), v8::internal::CodeStubAssembler::IsNotAnyHole(), v8::internal::CodeStubAssembler::IsNumberNormalized(), v8::internal::CodeStubAssembler::IsNumeric(), v8::internal::CodeStubAssembler::IsSafeInteger(), v8::internal::CodeStubAssembler::IsSpecialReceiverMap(), v8::internal::CodeStubAssembler::IsUniqueName(), v8::internal::CodeStubAssembler::IsValidPositiveSmi(), v8::internal::CodeStubAssembler::IsZeroOrContext(), and v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector().
Int64Add()
TNode<Int64T> v8::internal::compiler::CodeAssembler::Int64Add (TNode< Int64T > left, TNode< Int64T > right) [inline]
Definition at line 1182 of file code-assembler.h.
                                                                  {
    return Signed(Int64Add(static_cast<TNode<Word64T>>(left), right));
  }
References v8::base::bits::Signed().
Int64Constant()
TNode< Int64T > v8::internal::compiler::CodeAssembler::Int64Constant (int64_t value)
Definition at line 305 of file code-assembler.cc.
                                                        {
  return UncheckedCast<Int64T>(jsgraph()->Int64Constant(value));
}
References jsgraph(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::CodeStubAssembler::IsDoubleHole(), v8::internal::CodeStubAssembler::StoreDoubleHole(), v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16(), and v8::internal::CodeStubAssembler::TryFloat64ToAdditiveSafeInteger().
Int64Mul()
TNode<Int64T> v8::internal::compiler::CodeAssembler::Int64Mul (TNode< Int64T > left, TNode< Int64T > right) [inline]
Definition at line 1198 of file code-assembler.h.
                                                                  {
    return Signed(Int64Mul(static_cast<TNode<Word64T>>(left), right));
  }
References v8::base::bits::Signed().
Int64Sub()
TNode<Int64T> v8::internal::compiler::CodeAssembler::Int64Sub (TNode< Int64T > left, TNode< Int64T > right) [inline]
Definition at line 1190 of file code-assembler.h.
                                                                  {
    return Signed(Int64Sub(static_cast<TNode<Word64T>>(left), right));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::CodeStubAssembler::TryFloat64ToAdditiveSafeInteger().
IntPtrAdd()
TNode<IntPtrT> v8::internal::compiler::CodeAssembler::IntPtrAdd (TNode< IntPtrT > left, TNode< IntPtrT > right) [inline]
Definition at line 1206 of file code-assembler.h.
                                                                      {
    return Signed(IntPtrAdd(static_cast<TNode<WordT>>(left),
                            static_cast<TNode<WordT>>(right)));
  }
References v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrAdd(), and v8::base::bits::Signed().
Referenced by v8::internal::interpreter::InterpreterAssembler::AbortIfRegisterCountInvalid(), v8::internal::BaseCollectionsAssembler::AddConstructorEntries(), v8::internal::CollectionsBuiltinsAssembler::AddConstructorEntriesFromSet(), v8::internal::CollectionsBuiltinsAssembler::AddToOrderedHashTable(), v8::internal::interpreter::InterpreterAssembler::Advance(), v8::internal::CodeStubAssembler::AlignToAllocationAlignment(), v8::internal::StringBuiltinsAssembler::AllocAndCopyStringCharacters(), v8::internal::CodeStubAssembler::Allocate(), v8::internal::CodeStubAssembler::AllocateArrayList(), v8::internal::CodeStubAssembler::AllocateNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::AllocateOrderedHashTableWithCapacity(), v8::internal::CodeStubAssembler::AllocateRaw(), v8::internal::CodeStubAssembler::AllocateRawBigInt(), v8::internal::CodeStubAssembler::AllocateSimpleNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::BuildAppendJSArray(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReadUnaligned(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedByte(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedQuad(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedShort(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedByte(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedQuad(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedShort(), v8::internal::MicrotaskQueueBuiltinsAssembler::CalculateRingBufferOffset(), v8::internal::interpreter::InterpreterAssembler::CallRuntimeN(), v8::internal::RegExpBuiltinsAssembler::ConstructNewResultFromMatchInfo(), v8::internal::CodeStubAssembler::CopyElements(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::CodeStubAssembler::CopyRange(), v8::internal::StringBuiltinsAssembler::CopyStringCharacters(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::ConstructorBuiltinsAssembler::CreateShallowObjectLiteral(), v8::internal::interpreter::InterpreterAssembler::DispatchWide(), v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), v8::internal::CodeStubAssembler::EntryToIndex(), v8::internal::interpreter::InterpreterAssembler::ExportParametersAndRegisterFile(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::CodeStubAssembler::ExtractFixedDoubleArrayFillingHoles(), v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), v8::internal::CodeStubAssembler::FillFixedArrayWithSmiZero(), v8::internal::CodeStubAssembler::FillFixedDoubleArrayWithZero(), v8::internal::WeakCollectionsBuiltinsAssembler::FindKeyIndex(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntry(), v8::internal::CodeStubAssembler::FixedArrayBoundsCheck(), v8::internal::ArrayIncludesIndexofAssembler::Generate(), v8::internal::StringBuiltinsAssembler::GenerateSeqStringRelationalComparison(), v8::internal::CodeStubAssembler::GetFrameArguments(), v8::internal::CodeStubAssembler::GetMarkBit(), v8::internal::RegExpBuiltinsAssembler::GetStringPointers(), v8::internal::CodeStubAssembler::GotoIfNotDoubleStringCacheEntryKeyEqual(), v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase(), v8::internal::CodeStubAssembler::HashTableComputeCapacity(), v8::internal::interpreter::InterpreterAssembler::ImportRegisterFile(), v8::internal::MicrotaskQueueBuiltinsAssembler::IncrementFinishedMicrotaskCount(), v8::internal::RegExpBuiltinsAssembler::InitializeMatchInfoFromRegisters(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::InnerAllocateElements(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::InnerAllocateMemento(), v8::internal::CodeStubAssembler::IntPtrRoundUpToPowerOfTwo32(), v8::internal::CodeStubAssembler::IsDoubleHole(), v8::internal::interpreter::InterpreterAssembler::Jump(), v8::internal::WeakCollectionsBuiltinsAssembler::KeyIndexFromEntry(), v8::internal::CodeStubAssembler::LoadBigIntDigit(), v8::internal::CodeStubAssembler::LoadDoubleStringCacheEntryValue(), v8::internal::CodeStubAssembler::LoadFixedBigInt64ArrayElementAsTagged(), v8::internal::CodeStubAssembler::LoadFixedBigUint64ArrayElementAsTagged(), v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), v8::internal::StringBuiltinsAssembler::LoadSurrogatePairAt(), v8::internal::CodeStubAssembler::LoadUint64Ptr(), v8::internal::CodeStubAssembler::LoadUint8Ptr(), v8::internal::CodeStubAssembler::LookupLinear(), v8::internal::CollectionsBuiltinsAssembler::MapIteratorToList(), v8::internal::KeyedStoreGenericAssembler::MaybeUpdateLengthAndReturn(), v8::internal::CodeStubAssembler::MoveElements(), v8::internal::CodeStubAssembler::NameDictionaryLookup(), v8::internal::GrowableFixedArray::NewCapacity(), v8::internal::interpreter::InterpreterAssembler::NextRegister(), v8::internal::CodeStubAssembler::NumberDictionaryLookup(), v8::internal::AccessorAssembler::OverwriteExistingFastDataProperty(), v8::internal::IntlBuiltinsAssembler::PointerToSeqStringData(), v8::internal::GrowableFixedArray::Push(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::interpreter::InterpreterAssembler::RegisterLocation(), v8::internal::interpreter::InterpreterAssembler::ReloadBytecodeOffset(), v8::internal::AccessorAssembler::ScriptContextTableLookup(), v8::internal::StringBuiltinsAssembler::SearchOneByteInOneByteString(), v8::internal::WriteBarrierCodeStubAssembler::SetBitInCell(), v8::internal::TypedArrayBuiltinsAssembler::SetJSTypedArrayOnHeapDataPtr(), v8::internal::CollectionsBuiltinsAssembler::SetOrSetIteratorToList(), v8::internal::CodeStubAssembler::StoreBigIntDigit(), v8::internal::CodeStubAssembler::StoreDoubleHole(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), v8::internal::AccessorAssembler::StoreJSSharedStructField(), v8::internal::CollectionsBuiltinsAssembler::StoreOrderedHashTableNewEntry(), v8::internal::interpreter::InterpreterAssembler::StoreRegisterForShortStar(), v8::internal::CodeStubAssembler::StoreSwissNameDictionaryEnumToEntryMapping(), v8::internal::CodeStubAssembler::StoreSwissNameDictionaryKeyAndValue(), v8::internal::StringBuiltinsAssembler::StringEqual_FastLoop(), v8::internal::StringBuiltinsAssembler::StringToArray(), v8::internal::StringBuiltinsAssembler::SubString(), v8::internal::CodeStubAssembler::SwissNameDictionaryOffsetIntoDataTableMT(), v8::internal::CodeStubAssembler::SwissNameDictionaryOffsetIntoPropertyDetailsTableMT(), v8::internal::CodeStubAssembler::SwissNameDictionarySetCtrl(), v8::internal::CodeStubAssembler::ToKeyIndex(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::interpreter::InterpreterAssembler::TraceBytecodeDispatch(), v8::internal::CodeStubAssembler::TryMatchRootRange(), v8::internal::AccessorAssembler::TryMonomorphicCase(), v8::internal::AccessorAssembler::TryProbeStubCacheTable(), v8::internal::ToDirectStringAssembler::TryToDirect(), and v8::internal::WeakCollectionsBuiltinsAssembler::ValueIndexFromKeyIndex().
IntPtrConstant()
TNode< IntPtrT > v8::internal::compiler::CodeAssembler::IntPtrConstant (intptr_t value)
Definition at line 313 of file code-assembler.cc.
                                                           {
  return UncheckedCast<IntPtrT>(jsgraph()->IntPtrConstant(value));
}
References jsgraph(), and v8::internal::value.
Referenced by v8::internal::BaseCollectionsAssembler::AddConstructorEntries(), v8::internal::BaseCollectionsAssembler::AddConstructorEntriesFromFastJSArray(), v8::internal::CollectionsBuiltinsAssembler::AddConstructorEntriesFromSet(), v8::internal::CollectionsBuiltinsAssembler::AddNewToOrderedHashTable(), v8::internal::CollectionsBuiltinsAssembler::AddToOrderedHashTable(), v8::internal::interpreter::InterpreterAssembler::Advance(), v8::internal::CodeStubAssembler::AlignToAllocationAlignment(), v8::internal::StringBuiltinsAssembler::AllocAndCopyStringCharacters(), v8::internal::CodeStubAssembler::Allocate(), v8::internal::CodeStubAssembler::AllocateArrayList(), v8::internal::CodeStubAssembler::AllocateByteArray(), v8::internal::IntlBuiltinsAssembler::AllocateEmptyJSArray(), v8::internal::TypedArrayBuiltinsAssembler::AllocateEmptyOnHeapBuffer(), v8::internal::CodeStubAssembler::AllocateInNewSpace(), v8::internal::CodeStubAssembler::AllocateJSArray(), v8::internal::CodeStubAssembler::AllocateNameDictionary(), v8::internal::CodeStubAssembler::AllocateNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::AllocateNonEmptyByteArray(), v8::internal::CodeStubAssembler::AllocateOrderedHashMap(), v8::internal::CodeStubAssembler::AllocateOrderedHashSet(), v8::internal::CodeStubAssembler::AllocateOrderedHashTable(), v8::internal::CodeStubAssembler::AllocateOrderedHashTableWithCapacity(), v8::internal::CodeStubAssembler::AllocateOrderedNameDictionary(), v8::internal::CodeStubAssembler::AllocatePropertyArray(), v8::internal::CodeStubAssembler::AllocateRaw(), v8::internal::CodeStubAssembler::AllocateRawBigInt(), v8::internal::CodeStubAssembler::AllocateSeqOneByteString(), v8::internal::CodeStubAssembler::AllocateSeqTwoByteString(), v8::internal::CodeStubAssembler::AllocateSimpleNameDictionary(), v8::internal::CodeStubAssembler::AllocateSimpleNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::AllocateSwissNameDictionary(), v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::WeakCollectionsBuiltinsAssembler::AllocateTable(), v8::internal::CodeStubAssembler::AllocateUninitializedJSArray(), v8::internal::CodeStubAssembler::AllocateUninitializedJSArrayWithElements(), v8::internal::CodeStubArguments::AtIndex(), v8::internal::CodeStubAssembler::BigIntFromInt32Pair(), v8::internal::CodeStubAssembler::BigIntFromInt64(), v8::internal::CodeStubAssembler::BigIntFromUint32Pair(), v8::internal::CodeStubAssembler::BigIntFromUint64(), v8::internal::CodeStubAssembler::BIntConstant(), v8::internal::CodeStubAssembler::BuildAppendJSArray(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReadUnaligned(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedQuad(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedShort(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedQuad(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedShort(), v8::internal::MicrotaskQueueBuiltinsAssembler::CalculateRingBufferOffset(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructDoubleVarargs(), v8::internal::interpreter::InterpreterAssembler::CallRuntimeN(), v8::internal::PrototypeCheckAssembler::CheckAndBranch(), v8::internal::AccessorAssembler::CheckFieldType(), v8::internal::AccessorAssembler::CheckHeapObjectTypeMatchesDescriptor(), v8::internal::CodeStubAssembler::ClearedValue(), v8::internal::SlowBoilerplateCloneAssembler::CloneElementsOfFixedArray(), v8::internal::CodeStubArguments::CodeStubArguments(), v8::internal::WeakCollectionsBuiltinsAssembler::Coefficient(), v8::internal::ArrayPopulatorAssembler::ConstructArrayLike(), v8::internal::RegExpBuiltinsAssembler::ConstructNewResultFromMatchInfo(), v8::internal::CodeStubAssembler::CopyElements(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::CodeStubAssembler::CopyNameDictionary(), v8::internal::CodeStubAssembler::CopyPropertyArrayValues(), v8::internal::CodeStubAssembler::CopyRange(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::ConstructorBuiltinsAssembler::CreateEmptyArrayLiteral(), v8::internal::ConstructorBuiltinsAssembler::CreateShallowObjectLiteral(), v8::internal::CodeStubAssembler::DecodeWord(), v8::internal::CollectionsBuiltinsAssembler::DeleteFromSetTable(), v8::internal::CodeStubAssembler::DescriptorEntryToIndex(), v8::internal::StringBuiltinsAssembler::DirectStringData(), v8::internal::interpreter::InterpreterAssembler::DispatchWide(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::CodeStubAssembler::EmptyBackingStoreBufferConstant(), v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), v8::internal::WeakCollectionsBuiltinsAssembler::EntryMask(), v8::internal::CodeStubAssembler::EntryToIndex(), v8::internal::interpreter::InterpreterAssembler::ExportParametersAndRegisterFile(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::CodeStubAssembler::ExtractFixedArray(), v8::internal::CodeStubAssembler::ExtractFixedDoubleArrayFillingHoles(), v8::internal::CodeStubAssembler::ExtractToFixedArray(), v8::internal::CodeStubAssembler::FastCloneJSObject(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FastGetOwnValuesOrEntries(), v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), v8::internal::CodeStubAssembler::FillFixedArrayWithSmiZero(), v8::internal::CodeStubAssembler::FillFixedDoubleArrayWithZero(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FinalizeValuesOrEntriesJSArray(), v8::internal::WeakCollectionsBuiltinsAssembler::FindKeyIndex(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntry(), v8::internal::CodeStubAssembler::FixedArrayBoundsCheck(), v8::internal::RegExpBuiltinsAssembler::FlagsGetter(), v8::internal::CodeStubArguments::ForEach(), v8::internal::RegExpBuiltinsAssembler::FreeRegExpResultVector(), v8::internal::ArrayIncludesIndexofAssembler::Generate(), v8::internal::ArrayBuiltinsAssembler::GenerateArrayNoArgumentConstructor(), v8::internal::AccessorAssembler::GenerateCloneObjectIC_Slow(), v8::internal::BaseCollectionsAssembler::GenerateConstructor(), v8::internal::ArrayBuiltinsAssembler::GenerateDispatchToArrayStub(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::GenerateMetaTableAccess(), v8::internal::ArrayIncludesIndexofAssembler::GeneratePackedDoubles(), v8::internal::StringBuiltinsAssembler::GenerateSeqStringRelationalComparison(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::AccessorAssembler::GenericElementLoad(), v8::internal::IntlBuiltinsAssembler::GetChar(), v8::internal::TypedArrayBuiltinsAssembler::GetDefaultConstructor(), v8::internal::MicrotaskQueueBuiltinsAssembler::GetEnteredContextCount(), v8::internal::CodeStubAssembler::GetFrameArguments(), v8::internal::CodeStubAssembler::GetHeapObjectAssumeWeak(), v8::internal::CodeStubArguments::GetLengthWithoutReceiver(), v8::internal::CodeStubAssembler::GetMarkBit(), v8::internal::MicrotaskQueueBuiltinsAssembler::GetMicrotaskQueueCapacity(), v8::internal::MicrotaskQueueBuiltinsAssembler::GetMicrotaskQueueSize(), v8::internal::MicrotaskQueueBuiltinsAssembler::GetMicrotaskQueueStart(), v8::internal::MicrotaskQueueBuiltinsAssembler::GetMicrotaskRingBuffer(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::GetOwnValuesOrEntries(), v8::internal::CodeStubArguments::GetReceiver(), v8::internal::TypedArrayBuiltinsAssembler::GetTypedArrayElementSize(), v8::internal::CodeStubAssembler::GotoIfNotDoubleStringCacheEntryKeyEqual(), v8::internal::GrowableFixedArray::GrowableFixedArray(), v8::internal::AccessorAssembler::HandleLoadField(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), v8::internal::AccessorAssembler::HandleProtoHandler(), v8::internal::AccessorAssembler::HandleStoreFieldAndReturn(), v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase(), v8::internal::CodeStubAssembler::HasAsyncEventDelegate(), v8::internal::CodeStubAssembler::HashTableComputeCapacity(), v8::internal::interpreter::InterpreterAssembler::ImportRegisterFile(), v8::internal::MicrotaskQueueBuiltinsAssembler::IncrementFinishedMicrotaskCount(), v8::internal::CodeStubAssembler::InitializeJSObjectBodyNoSlackTracking(), v8::internal::CodeStubAssembler::InitializeJSObjectBodyWithSlackTracking(), v8::internal::CodeStubAssembler::InitializePropertyArrayLength(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::InnerAllocateElements(), v8::internal::WriteBarrierCodeStubAssembler::InsertIntoRememberedSet(), v8::internal::CodeStubAssembler::IntPtrMax(), v8::internal::CodeStubAssembler::IntPtrMin(), v8::internal::CodeStubAssembler::IntPtrRoundUpToPowerOfTwo32(), v8::internal::CodeStubAssembler::IntPtrToTaggedIndex(), v8::internal::RegExpBuiltinsAssembler::IntPtrZero(), v8::internal::CodeStubAssembler::IsDoubleHole(), v8::internal::CodeStubAssembler::IsMarked(), v8::internal::CodeStubAssembler::IsRegularHeapObjectSize(), v8::internal::WriteBarrierCodeStubAssembler::IsUnmarked(), v8::internal::CodeStubAssembler::IsValidPositiveSmi(), v8::internal::CodeStubAssembler::IsWeakReferenceTo(), v8::internal::CodeStubAssembler::IsWeakReferenceToObject(), v8::internal::IntlBuiltinsAssembler::JumpIfStartsWithIgnoreCase(), v8::internal::WeakCollectionsBuiltinsAssembler::KeyIndexFromEntry(), v8::internal::interpreter::InterpreterAssembler::LoadAndUntagRegister(), v8::internal::CodeStubAssembler::LoadArrayElement(), v8::internal::CodeStubAssembler::LoadArrayLength(), v8::internal::CodeStubAssembler::LoadBigIntDigit(), v8::internal::WriteBarrierCodeStubAssembler::LoadBucket(), v8::internal::CodeStubAssembler::LoadCachedMap(), v8::internal::WasmBuiltinsAssembler::LoadContextFromInstanceData(), v8::internal::CodeStubAssembler::LoadDetailsByDescriptorEntry(), v8::internal::CodeStubAssembler::LoadDoubleStringCacheEntryValue(), v8::internal::CodeStubAssembler::LoadFixedBigInt64ArrayElementAsTagged(), v8::internal::CodeStubAssembler::LoadFixedBigUint64ArrayElementAsTagged(), v8::internal::CodeStubAssembler::LoadFromParentFrame(), v8::internal::AccessorAssembler::LoadHandlerDataField(), v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), v8::internal::CodeStubAssembler::LoadKeyByDescriptorEntry(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMemoryChunkFlags(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), v8::internal::interpreter::InterpreterAssembler::LoadRegister(), LoadRoot(), v8::internal::WasmBuiltinsAssembler::LoadSharedPartFromInstanceData(), v8::internal::WriteBarrierCodeStubAssembler::LoadSlotSet(), v8::internal::StringBuiltinsAssembler::LoadSurrogatePairAt(), v8::internal::CodeStubAssembler::LoadSwissNameDictionaryCtrlTableGroup(), v8::internal::CodeStubAssembler::LoadUint64Ptr(), v8::internal::CodeStubAssembler::LoadValueByDescriptorEntry(), v8::internal::CodeStubAssembler::LookupLinear(), v8::internal::CodeStubAssembler::MakeWeak(), v8::internal::CollectionsBuiltinsAssembler::MapIteratorToList(), v8::internal::CodeStubAssembler::MapUsedInstanceSizeInWords(), v8::internal::KeyedStoreGenericAssembler::MaybeUpdateLengthAndReturn(), v8::internal::CodeStubAssembler::MoveElements(), v8::internal::CodeStubAssembler::NameDictionaryLookup(), v8::internal::CodeStubAssembler::NameDictionaryLookupWithForwardIndex(), v8::internal::GrowableFixedArray::NewCapacity(), v8::internal::interpreter::InterpreterAssembler::NextRegister(), v8::internal::CodeStubAssembler::NumberDictionaryLookup(), v8::internal::interpreter::InterpreterAssembler::OperandOffset(), v8::internal::IntlBuiltinsAssembler::PointerToSeqStringData(), v8::internal::MicrotaskQueueBuiltinsAssembler::PrepareForContext(), v8::internal::CodeStubAssembler::PrintToStream(), v8::internal::GrowableFixedArray::Push(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Single(), v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::interpreter::InterpreterAssembler::RegisterLocation(), v8::internal::interpreter::InterpreterAssembler::RegisterLocationInRegisterList(), v8::internal::interpreter::InterpreterAssembler::ReloadBytecodeOffset(), v8::internal::GrowableFixedArray::ResizeFixedArray(), v8::internal::MicrotaskQueueBuiltinsAssembler::RewindEnteredContext(), v8::internal::interpreter::InterpreterAssembler::SaveBytecodeOffset(), v8::internal::AccessorAssembler::ScriptContextTableLookup(), v8::internal::StringBuiltinsAssembler::SearchOneByteInOneByteString(), v8::internal::CodeStubAssembler::SelectIntPtrConstant(), v8::internal::WriteBarrierCodeStubAssembler::SetBitInCell(), v8::internal::MicrotaskQueueBuiltinsAssembler::SetMicrotaskQueueSize(), v8::internal::MicrotaskQueueBuiltinsAssembler::SetMicrotaskQueueStart(), v8::internal::CollectionsBuiltinsAssembler::SetOrSetIteratorToList(), v8::internal::CollectionsBuiltinsAssembler::SetOrSetIteratorToSet(), v8::internal::CodeStubArguments::SetReceiver(), v8::internal::CodeStubAssembler::SharedValueBarrier(), v8::internal::WeakCollectionsBuiltinsAssembler::ShouldShrink(), SmiConstant(), v8::internal::CodeStubAssembler::SmiFromUint32(), v8::internal::CodeStubAssembler::SmiToTaggedIndex(), v8::internal::CodeStubAssembler::SmiUntag(), v8::internal::CodeStubAssembler::StoreBigIntDigit(), v8::internal::CodeStubAssembler::StoreBoundedSizeToObject(), v8::internal::CodeStubAssembler::StoreContextElementNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreDoubleHole(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), v8::internal::CodeStubAssembler::StoreObjectByteNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreObjectField(), v8::internal::CollectionsBuiltinsAssembler::StoreOrderedHashTableNewEntry(), v8::internal::interpreter::InterpreterAssembler::StoreRegister(), v8::internal::interpreter::InterpreterAssembler::StoreRegisterForShortStar(), StoreRoot(), v8::internal::CodeStubAssembler::StoreSharedObjectField(), v8::internal::CodeStubAssembler::StoreSwissNameDictionaryEnumToEntryMapping(), v8::internal::CodeStubAssembler::StoreSwissNameDictionaryKeyAndValue(), v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::CodeStubAssembler::StringCharCodeAt(), v8::internal::StringBuiltinsAssembler::StringEqual_Core(), v8::internal::StringBuiltinsAssembler::StringEqual_FastLoop(), v8::internal::StringBuiltinsAssembler::StringEqual_Loop(), v8::internal::CodeStubAssembler::StringFromSingleCharCode(), v8::internal::StringBuiltinsAssembler::StringFromSingleUTF16EncodedCodePoint(), v8::internal::StringBuiltinsAssembler::StringToArray(), v8::internal::StringBuiltinsAssembler::SubString(), v8::internal::CodeStubAssembler::SwissNameDictionaryOffsetIntoDataTableMT(), v8::internal::CodeStubAssembler::SwissNameDictionaryOffsetIntoPropertyDetailsTableMT(), v8::internal::CodeStubAssembler::SwissNameDictionarySetCtrl(), v8::internal::CodeStubAssembler::TaggedIndexToIntPtr(), v8::internal::CodeStubAssembler::TaggedIndexToSmi(), v8::internal::CodeStubAssembler::TaggedIsPositiveSmi(), v8::internal::CodeStubAssembler::ToKeyIndex(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::interpreter::InterpreterAssembler::TraceBytecodeDispatch(), v8::internal::CodeStubAssembler::TryInternalizeString(), v8::internal::CodeStubAssembler::TryIntPtrDiv(), v8::internal::CodeStubAssembler::TryIntPtrMod(), v8::internal::CodeStubAssembler::TryMatchRootRange(), v8::internal::AccessorAssembler::TryMonomorphicCase(), v8::internal::AccessorAssembler::TryProbeStubCacheTable(), v8::internal::CodeStubAssembler::TryToName(), v8::internal::ToDirectStringAssembler::TryToSequential(), v8::internal::WeakCollectionsBuiltinsAssembler::ValueIndexFromKeyIndex(), v8::internal::CodeStubAssembler::WordIsPowerOfTwo(), WordSar(), WordShl(), and WordShr().
IntPtrEqual()
TNode<BoolT> v8::internal::compiler::CodeAssembler::IntPtrEqual (TNode< WordT > left, TNode< WordT > right)
Referenced by v8::internal::BaseCollectionsAssembler::AddConstructorEntriesFromFastJSArray(), v8::internal::CodeStubAssembler::AllocateOrderedHashTableWithCapacity(), v8::internal::CodeStubAssembler::AllocateRaw(), v8::internal::CodeStubAssembler::BigIntFromInt32Pair(), v8::internal::CodeStubAssembler::BigIntFromInt64(), v8::internal::CodeStubAssembler::BigIntFromUint32Pair(), v8::internal::CodeStubAssembler::BigIntFromUint64(), v8::internal::CodeStubAssembler::BuildAppendJSArray(), v8::internal::CodeStubAssembler::CopyElements(), v8::internal::ConstructorBuiltinsAssembler::CreateShallowObjectLiteral(), v8::internal::interpreter::InterpreterAssembler::ExportParametersAndRegisterFile(), v8::internal::CodeStubAssembler::FastCloneJSObject(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FastGetOwnValuesOrEntries(), v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FinalizeValuesOrEntriesJSArray(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntry(), v8::internal::ArrayBuiltinsAssembler::GenerateDispatchToArrayStub(), v8::internal::StringBuiltinsAssembler::GenerateSeqStringRelationalComparison(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::StringBuiltinsAssembler::GenerateStringEqual(), v8::internal::interpreter::InterpreterAssembler::ImportRegisterFile(), v8::internal::CollectionsBuiltinsAssembler::MapIteratorToList(), v8::internal::CodeStubAssembler::NameDictionaryLookupWithForwardIndex(), v8::internal::GrowableFixedArray::Push(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Single(), v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::StringBuiltinsAssembler::ReplaceUnpairedSurrogates(), v8::internal::CollectionsBuiltinsAssembler::SetOrSetIteratorToSet(), v8::internal::StringBuiltinsAssembler::SubString(), v8::internal::CodeStubAssembler::TryInternalizeString(), v8::internal::CodeStubAssembler::TryIntPtrDiv(), v8::internal::CodeStubAssembler::TryIntPtrMod(), and v8::internal::CodeStubAssembler::WordIsPowerOfTwo().
IntPtrMul()
TNode<IntPtrT> v8::internal::compiler::CodeAssembler::IntPtrMul (TNode< IntPtrT > left, TNode< IntPtrT > right) [inline]
Definition at line 1214 of file code-assembler.h.
                                                                      {
    return Signed(IntPtrMul(static_cast<TNode<WordT>>(left),
                            static_cast<TNode<WordT>>(right)));
  }
References v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrMul(), and v8::base::bits::Signed().
Referenced by v8::internal::CollectionsBuiltinsAssembler::AddConstructorEntriesFromSet(), v8::internal::CodeStubAssembler::AllocateOrderedHashTableWithCapacity(), v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::CopyElements(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::CodeStubAssembler::DescriptorEntryToIndex(), v8::internal::CodeStubAssembler::EntryToIndex(), v8::internal::WeakCollectionsBuiltinsAssembler::FindKeyIndex(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntry(), v8::internal::AccessorAssembler::HandleLoadField(), v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase(), v8::internal::WeakCollectionsBuiltinsAssembler::KeyIndexFromEntry(), v8::internal::CodeStubAssembler::LoadArrayLength(), v8::internal::CodeStubAssembler::LoadBigIntDigit(), v8::internal::CodeStubAssembler::LoadUint64Ptr(), v8::internal::CodeStubAssembler::LookupLinear(), v8::internal::CodeStubAssembler::MoveElements(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::CodeStubAssembler::StoreBigIntDigit(), v8::internal::CollectionsBuiltinsAssembler::StoreOrderedHashTableNewEntry(), v8::internal::CodeStubAssembler::SwissNameDictionaryOffsetIntoDataTableMT(), v8::internal::CodeStubAssembler::SwissNameDictionaryOffsetIntoPropertyDetailsTableMT(), and v8::internal::AccessorAssembler::TryProbeStubCacheTable().
IntPtrSub()
TNode<IntPtrT> v8::internal::compiler::CodeAssembler::IntPtrSub (TNode< IntPtrT > left, TNode< IntPtrT > right) [inline]
Definition at line 1210 of file code-assembler.h.
                                                                      {
    return Signed(IntPtrSub(static_cast<TNode<WordT>>(left),
                            static_cast<TNode<WordT>>(right)));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::StringBuiltinsAssembler::AllocAndCopyStringCharacters(), v8::internal::CodeStubAssembler::AllocateNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::AllocateOrderedHashTableWithCapacity(), v8::internal::CodeStubAssembler::AllocateSimpleNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::BigIntFromInt32Pair(), v8::internal::CodeStubAssembler::BigIntFromInt64(), v8::internal::CodeStubAssembler::BuildAppendJSArray(), v8::internal::MicrotaskQueueBuiltinsAssembler::CalculateRingBufferOffset(), v8::internal::CodeStubAssembler::CopyElements(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::WeakCollectionsBuiltinsAssembler::EntryMask(), v8::internal::interpreter::InterpreterAssembler::ExportParametersAndRegisterFile(), v8::internal::CodeStubAssembler::ExtractFixedDoubleArrayFillingHoles(), v8::internal::CodeStubAssembler::FastCloneJSObject(), v8::internal::RegExpBuiltinsAssembler::FlagsGetter(), v8::internal::CodeStubArguments::GetLengthWithoutReceiver(), v8::internal::interpreter::InterpreterAssembler::ImportRegisterFile(), v8::internal::WriteBarrierCodeStubAssembler::InsertIntoRememberedSet(), v8::internal::CodeStubAssembler::IntPtrRoundUpToPowerOfTwo32(), v8::internal::interpreter::InterpreterAssembler::JumpBackward(), v8::internal::CodeStubAssembler::MapUsedInObjectProperties(), v8::internal::CodeStubAssembler::MoveElements(), v8::internal::CodeStubAssembler::NameDictionaryLookup(), v8::internal::CodeStubAssembler::NumberDictionaryLookup(), v8::internal::AccessorAssembler::OverwriteExistingFastDataProperty(), v8::internal::interpreter::InterpreterAssembler::RegisterLocationInRegisterList(), v8::internal::interpreter::InterpreterAssembler::SaveBytecodeOffset(), v8::internal::StringBuiltinsAssembler::SearchOneByteInOneByteString(), v8::internal::TypedArrayBuiltinsAssembler::SetJSTypedArrayOnHeapDataPtr(), v8::internal::AccessorAssembler::StoreJSSharedStructField(), v8::internal::CodeStubAssembler::StoreObjectField(), v8::internal::CollectionsBuiltinsAssembler::StoreOrderedHashTableNewEntry(), v8::internal::CodeStubAssembler::StoreSharedObjectField(), v8::internal::StringBuiltinsAssembler::SubString(), v8::internal::CodeStubAssembler::SwissNameDictionarySetCtrl(), and v8::internal::CodeStubAssembler::WordIsPowerOfTwo().
Is32()
bool v8::internal::compiler::CodeAssembler::Is32 () const
Definition at line 239 of file code-assembler.cc.
{ return raw_assembler()->machine()->Is32(); }
References v8::internal::compiler::MachineOperatorBuilder::Is32(), v8::internal::compiler::RawMachineAssembler::machine(), and raw_assembler().
Referenced by v8::internal::CodeStubAssembler::CountTrailingZeros32(), v8::internal::CodeStubAssembler::CountTrailingZeros64(), v8::internal::CodeStubAssembler::PopulationCount32(), and v8::internal::CodeStubAssembler::PopulationCount64().
Is64()
bool v8::internal::compiler::CodeAssembler::Is64 () const
Definition at line 238 of file code-assembler.cc.
{ return raw_assembler()->machine()->Is64(); }
References v8::internal::compiler::MachineOperatorBuilder::Is64(), v8::internal::compiler::RawMachineAssembler::machine(), and raw_assembler().
Referenced by v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::CodeStubAssembler::BigIntFromInt32Pair(), v8::internal::CodeStubAssembler::BigIntFromInt64(), v8::internal::CodeStubAssembler::BigIntFromUint32Pair(), v8::internal::CodeStubAssembler::BigIntFromUint64(), ChangeFloat64ToIntPtr(), ChangeFloat64ToUintPtr(), ChangeInt32ToIntPtr(), ChangeUint32ToWord(), ChangeUintPtrToFloat64(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::BinaryOpAssembler::Generate_AddWithFeedback(), v8::internal::AccessorAssembler::GenericElementLoad(), v8::internal::CodeStubAssembler::GotoIfLargeBigInt(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::CodeStubAssembler::IsAdditiveSafeInteger(), v8::internal::anonymous_namespace{binary-op-assembler.cc}::IsBigInt64OpSupported(), v8::internal::CodeStubAssembler::IsDoubleHole(), IsIntPtrAbsWithOverflowSupported(), v8::internal::CodeStubAssembler::LoadFixedBigInt64ArrayElementAsTagged(), v8::internal::CodeStubAssembler::LoadFixedBigUint64ArrayElementAsTagged(), v8::internal::CodeStubAssembler::PopulationCountFallback(), RoundIntPtrToFloat64(), v8::internal::CodeStubAssembler::StoreDoubleHole(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), v8::internal::CodeStubAssembler::TaggedToBigInt(), v8::internal::CodeStubAssembler::TaggedToWord32OrBigIntImpl(), v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16(), v8::internal::CodeStubAssembler::TruncateIntPtrToInt32(), v8::internal::CodeStubAssembler::TruncateWordToInt32(), and v8::internal::CodeStubAssembler::TryFloat64ToAdditiveSafeInteger().
IsExceptionHandlerActive()
bool v8::internal::compiler::CodeAssembler::IsExceptionHandlerActive () const
Definition at line 1675 of file code-assembler.cc.
                                                   {
  return !state_->exception_handler_labels_.empty();
}
References v8::internal::compiler::CodeAssemblerState::exception_handler_labels_, and state_.
IsFloat64RoundDownSupported()
bool v8::internal::compiler::CodeAssembler::IsFloat64RoundDownSupported () const
Definition at line 245 of file code-assembler.cc.
                                                      {
  return raw_assembler()->machine()->Float64RoundDown().IsSupported();
}
References v8::internal::compiler::MachineOperatorBuilder::Float64RoundDown(), v8::internal::compiler::OptionalOperator::IsSupported(), v8::internal::compiler::RawMachineAssembler::machine(), and raw_assembler().
Referenced by v8::internal::CodeStubAssembler::Float64Floor(), and v8::internal::CodeStubAssembler::Float64Trunc().
IsFloat64RoundTiesEvenSupported()
bool v8::internal::compiler::CodeAssembler::IsFloat64RoundTiesEvenSupported () const
Definition at line 249 of file code-assembler.cc.
                                                          {
  return raw_assembler()->machine()->Float64RoundTiesEven().IsSupported();
}
References v8::internal::compiler::MachineOperatorBuilder::Float64RoundTiesEven(), v8::internal::compiler::OptionalOperator::IsSupported(), v8::internal::compiler::RawMachineAssembler::machine(), and raw_assembler().
Referenced by v8::internal::CodeStubAssembler::Float64RoundToEven().
IsFloat64RoundTruncateSupported()
bool v8::internal::compiler::CodeAssembler::IsFloat64RoundTruncateSupported () const
Definition at line 253 of file code-assembler.cc.
                                                          {
  return raw_assembler()->machine()->Float64RoundTruncate().IsSupported();
}
References v8::internal::compiler::MachineOperatorBuilder::Float64RoundTruncate(), v8::internal::compiler::OptionalOperator::IsSupported(), v8::internal::compiler::RawMachineAssembler::machine(), and raw_assembler().
Referenced by v8::internal::CodeStubAssembler::Float64Trunc().
IsFloat64RoundUpSupported()
bool v8::internal::compiler::CodeAssembler::IsFloat64RoundUpSupported () const
Definition at line 241 of file code-assembler.cc.
                                                    {
  return raw_assembler()->machine()->Float64RoundUp().IsSupported();
}
References v8::internal::compiler::MachineOperatorBuilder::Float64RoundUp(), v8::internal::compiler::OptionalOperator::IsSupported(), v8::internal::compiler::RawMachineAssembler::machine(), and raw_assembler().
Referenced by v8::internal::CodeStubAssembler::Float64Ceil(), and v8::internal::CodeStubAssembler::Float64Trunc().
IsInt32AbsWithOverflowSupported()
bool v8::internal::compiler::CodeAssembler::IsInt32AbsWithOverflowSupported () const
Definition at line 264 of file code-assembler.cc.
                                                          {
  return raw_assembler()->machine()->Int32AbsWithOverflow().IsSupported();
}
References v8::internal::compiler::MachineOperatorBuilder::Int32AbsWithOverflow(), v8::internal::compiler::OptionalOperator::IsSupported(), v8::internal::compiler::RawMachineAssembler::machine(), and raw_assembler().
Referenced by IsIntPtrAbsWithOverflowSupported(), and v8::internal::CodeStubAssembler::TrySmiAbs().
IsInt64AbsWithOverflowSupported()
bool v8::internal::compiler::CodeAssembler::IsInt64AbsWithOverflowSupported () const
Definition at line 268 of file code-assembler.cc.
                                                          {
  return raw_assembler()->machine()->Int64AbsWithOverflow().IsSupported();
}
References v8::internal::compiler::MachineOperatorBuilder::Int64AbsWithOverflow(), v8::internal::compiler::OptionalOperator::IsSupported(), v8::internal::compiler::RawMachineAssembler::machine(), and raw_assembler().
Referenced by IsIntPtrAbsWithOverflowSupported().
IsIntPtrAbsWithOverflowSupported()
bool v8::internal::compiler::CodeAssembler::IsIntPtrAbsWithOverflowSupported () const
Definition at line 272 of file code-assembler.cc.
                                                           {
  return Is64() ? IsInt64AbsWithOverflowSupported()
                : IsInt32AbsWithOverflowSupported();
}
References Is64(), IsInt32AbsWithOverflowSupported(), and IsInt64AbsWithOverflowSupported().
IsJSFunctionCall()
bool v8::internal::compiler::CodeAssembler::IsJSFunctionCall () const [protected]
Definition at line 501 of file code-assembler.cc.
                                           {
  auto call_descriptor = raw_assembler()->call_descriptor();
  return call_descriptor->IsJSFunctionCall();
}
References v8::internal::compiler::RawMachineAssembler::call_descriptor(), v8::internal::compiler::CallDescriptor::IsJSFunctionCall(), and raw_assembler().
IsMapOffsetConstant()
bool v8::internal::compiler::CodeAssembler::IsMapOffsetConstant (Node * node)
Definition at line 415 of file code-assembler.cc.
                                                  {
  return raw_assembler()->IsMapOffsetConstant(node);
}
References v8::internal::compiler::RawMachineAssembler::IsMapOffsetConstant(), and raw_assembler().
IsNullConstant()
bool v8::internal::compiler::CodeAssembler::IsNullConstant (TNode< Object > node)
Definition at line 491 of file code-assembler.cc.
                                                     {
  compiler::HeapObjectMatcher m(node);
  return m.Is(isolate()->factory()->null_value());
}
References factory(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Is(), and isolate().
Referenced by v8::internal::CodeStubAssembler::Call(), and v8::internal::CodeStubAssembler::CallFunction().
isolate()
Isolate * v8::internal::compiler::CodeAssembler::isolate () const
Definition at line 1669 of file code-assembler.cc.
{ return raw_assembler()->isolate(); }
References v8::internal::compiler::RawMachineAssembler::isolate(), and raw_assembler().
Referenced by v8::internal::CodeStubAssembler::Allocate(), v8::internal::CodeStubAssembler::AllocateOrderedHashTableWithCapacity(), v8::internal::CodeStubAssembler::AllocateRootFunctionWithContext(), v8::internal::WeakCollectionsBuiltinsAssembler::AllocateTable(), v8::internal::CodeStubAssembler::ArrayBufferMaxByteLength(), v8::internal::AsyncBuiltinsAssembler::Await(), v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::AwaitAndFinalizeCurrentBatch(), BooleanConstant(), v8::internal::CollectionsBuiltinsAssembler::BranchIfMapIteratorProtectorValid(), v8::internal::CollectionsBuiltinsAssembler::BranchIfSetIteratorProtectorValid(), v8::internal::StringBuiltinsAssembler::BranchIfStringPrimitiveWithNoCustomIteration(), v8::internal::CodeStubAssembler::BranchIfToBooleanIsTrue(), CallRuntimeImpl(), v8::internal::interpreter::InterpreterAssembler::CallRuntimeN(), v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::CompileCode(), v8::internal::LazyBuiltinsAssembler::CompileLazy(), v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchNoArgument(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchSingleArgument(), v8::internal::interpreter::InterpreterAssembler::DispatchTablePointer(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), factory(), v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::FinalizeJobOnMainThread(), v8::internal::RegExpBuiltinsAssembler::FlagsGetter(), v8::internal::CodeStubAssembler::Float64ToString(), v8::internal::RegExpBuiltinsAssembler::FreeRegExpResultVector(), v8::internal::ObjectBuiltinsAssembler::FromPropertyDescriptor(), v8::internal::DateBuiltinsAssembler::Generate_DatePrototype_GetField(), v8::internal::WriteBarrierCodeStubAssembler::GenerateEphemeronKeyBarrier(), v8::internal::WriteBarrierCodeStubAssembler::GenerateIndirectPointerBarrier(), v8::internal::AccessorAssembler::GenerateLoadIC_Megamorphic(), v8::internal::WriteBarrierCodeStubAssembler::GenerateRecordWrite(), v8::internal::AccessorAssembler::GenerateStoreIC_Megamorphic(), v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::BaseCollectionsAssembler::GetAddFunction(), v8::internal::MicrotaskQueueBuiltinsAssembler::GetCurrentContext(), v8::internal::MicrotaskQueueBuiltinsAssembler::GetEnteredContextCount(), v8::internal::CodeStubAssembler::GetInstanceTypeMap(), v8::internal::CodeStubAssembler::GetPendingMessage(), v8::internal::CodeStubAssembler::GetSharedFunctionInfoCode(), v8::internal::TypedArrayBuiltinsAssembler::GetTypedArrayElementsInfo(), v8::internal::CodeStubAssembler::GotoIfForceSlowPath(), v8::internal::CodeStubAssembler::HasAsyncEventDelegate(), v8::internal::StringBuiltinsAssembler::IndexOfDollarChar(), v8::internal::CodeStubAssembler::IsDebugActive(), v8::internal::WriteBarrierCodeStubAssembler::IsMarking(), v8::internal::WriteBarrierCodeStubAssembler::IsMinorMarking(), IsNullConstant(), v8::internal::WriteBarrierCodeStubAssembler::IsSharedSpaceIsolate(), IsUndefinedConstant(), v8::internal::AccessorAssembler::LoadIC_Noninlined(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), LoadRoot(), LoadRootMapWord(), NumberConstant(), v8::internal::CodeStubAssembler::PerformStackCheck(), v8::internal::CodeStubAssembler::PrintToStream(), v8::internal::CodeStubAssembler::PromiseHookFlags(), v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::QueueJob(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::MicrotaskQueueBuiltinsAssembler::RewindEnteredContext(), v8::internal::MicrotaskQueueBuiltinsAssembler::SetCurrentContext(), v8::internal::TypedArrayBuiltinsAssembler::SetJSTypedArrayOnHeapDataPtr(), v8::internal::CodeStubAssembler::SetPendingMessage(), v8::internal::RegExpBuiltinsAssembler::SlowLoadLastIndex(), v8::internal::RegExpBuiltinsAssembler::SlowStoreLastIndex(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::AccessorAssembler::StoreIC(), StoreRoot(), TailCallRuntimeImpl(), v8::internal::interpreter::InterpreterAssembler::TraceBytecodeDispatch(), and v8::internal::AccessorAssembler::TryProbeStubCache().
IsolateField()
TNode< ExternalReference > v8::internal::compiler::CodeAssembler::IsolateField (IsolateFieldId id)
Definition at line 403 of file code-assembler.cc.
                                                                      {
  return ExternalConstant(ExternalReference::Create(id));
}
References v8::internal::ExternalReference::Create(), and ExternalConstant().
Referenced by v8::internal::DateBuiltinsAssembler::Generate_DatePrototype_GetField(), v8::internal::CodeStubAssembler::GetContinuationPreservedEmbedderData(), v8::internal::CodeStubAssembler::LoadBuiltin(), v8::internal::CodeStubAssembler::SetContinuationPreservedEmbedderData(), and v8::internal::WriteBarrierCodeStubAssembler::UsesSharedHeap().
IsTruncateFloat64ToFloat16RawBitsSupported()
bool v8::internal::compiler::CodeAssembler::IsTruncateFloat64ToFloat16RawBitsSupported () const
Definition at line 257 of file code-assembler.cc.
                                                                     {
  return raw_assembler()
      ->machine()
      ->TruncateFloat64ToFloat16RawBits()
      .IsSupported();
}
References v8::internal::compiler::OptionalOperator::IsSupported(), v8::internal::compiler::RawMachineAssembler::machine(), raw_assembler(), and v8::internal::compiler::MachineOperatorBuilder::TruncateFloat64ToFloat16RawBits().
Referenced by v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16().
IsUndefinedConstant()
bool v8::internal::compiler::CodeAssembler::IsUndefinedConstant (TNode< Object > node)
Definition at line 486 of file code-assembler.cc.
                                                          {
  compiler::HeapObjectMatcher m(node);
  return m.Is(isolate()->factory()->undefined_value());
}
References factory(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Is(), and isolate().
Referenced by v8::internal::CodeStubAssembler::Call(), v8::internal::CodeStubAssembler::CallFunction(), and v8::internal::ObjectBuiltinsAssembler::FromPropertyDescriptor().
IsWord32CtzSupported()
bool v8::internal::compiler::CodeAssembler::IsWord32CtzSupported () const
Definition at line 285 of file code-assembler.cc.
                                               {
  return raw_assembler()->machine()->Word32Ctz().IsSupported();
}
References v8::internal::compiler::OptionalOperator::IsSupported(), v8::internal::compiler::RawMachineAssembler::machine(), raw_assembler(), and v8::internal::compiler::MachineOperatorBuilder::Word32Ctz().
Referenced by v8::internal::CodeStubAssembler::CountTrailingZeros32().
IsWord32PopcntSupported()
bool v8::internal::compiler::CodeAssembler::IsWord32PopcntSupported () const
Definition at line 277 of file code-assembler.cc.
                                                  {
  return raw_assembler()->machine()->Word32Popcnt().IsSupported();
}
References v8::internal::compiler::OptionalOperator::IsSupported(), v8::internal::compiler::RawMachineAssembler::machine(), raw_assembler(), and v8::internal::compiler::MachineOperatorBuilder::Word32Popcnt().
Referenced by v8::internal::CodeStubAssembler::PopulationCount32().
IsWord64CtzSupported()
bool v8::internal::compiler::CodeAssembler::IsWord64CtzSupported () const
Definition at line 289 of file code-assembler.cc.
                                               {
  return raw_assembler()->machine()->Word64Ctz().IsSupported();
}
References v8::internal::compiler::OptionalOperator::IsSupported(), v8::internal::compiler::RawMachineAssembler::machine(), raw_assembler(), and v8::internal::compiler::MachineOperatorBuilder::Word64Ctz().
Referenced by v8::internal::CodeStubAssembler::CountTrailingZeros64().
IsWord64PopcntSupported()
bool v8::internal::compiler::CodeAssembler::IsWord64PopcntSupported () const
Definition at line 281 of file code-assembler.cc.
                                                  {
  return raw_assembler()->machine()->Word64Popcnt().IsSupported();
}
References v8::internal::compiler::OptionalOperator::IsSupported(), v8::internal::compiler::RawMachineAssembler::machine(), raw_assembler(), and v8::internal::compiler::MachineOperatorBuilder::Word64Popcnt().
Referenced by v8::internal::CodeStubAssembler::PopulationCount64().
jsgraph()
JSGraph * v8::internal::compiler::CodeAssembler::jsgraph () const [private]
Definition at line 1683 of file code-assembler.cc.
{ return state_->jsgraph_; }
References v8::internal::compiler::CodeAssemblerState::jsgraph_, and state_.
Referenced by BooleanConstant(), Float32Constant(), Float64Constant(), Int32Constant(), Int64Constant(), IntPtrConstant(), TaggedIndexConstant(), UniqueInt32Constant(), UniqueInt64Constant(), UniqueIntPtrConstant(), UntypedHeapConstantHole(), UntypedHeapConstantMaybeHole(), and UntypedHeapConstantNoHole().
Load() [1/5]
Node * v8::internal::compiler::CodeAssembler::Load (MachineType type, Node * base)
Definition at line 854 of file code-assembler.cc.
                                                      {
  return raw_assembler()->Load(type, base);
}
References v8::internal::compiler::RawMachineAssembler::Load(), raw_assembler(), and v8::internal::tracing::type.
Referenced by v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReadUnaligned(), v8::internal::StringBuiltinsAssembler::CopyStringCharacters(), v8::internal::RegExpBuiltinsAssembler::FreeRegExpResultVector(), v8::internal::RegExpBuiltinsAssembler::InitializeMatchInfoFromRegisters(), v8::internal::WriteBarrierCodeStubAssembler::InsertIntoRememberedSet(), v8::internal::WriteBarrierCodeStubAssembler::LoadBucket(), v8::internal::WasmBuiltinsAssembler::LoadContextFromInstanceData(), v8::internal::CodeStubAssembler::LoadDoubleWithUndefinedAndHoleCheck(), v8::internal::CodeStubAssembler::LoadExternalPointerFromObject(), v8::internal::DataViewBuiltinsAssembler::LoadInt8(), v8::internal::CodeStubAssembler::LoadMemoryChunkFlags(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), LoadPointerFromRootRegister(), v8::internal::WriteBarrierCodeStubAssembler::LoadSlotSet(), v8::internal::DataViewBuiltinsAssembler::LoadUint8(), LoadUint8FromRootRegister(), v8::internal::CodeStubAssembler::PerformStackCheck(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), v8::internal::CodeStubAssembler::StoreExternalPointerToObject(), v8::internal::StringBuiltinsAssembler::StringEqual_FastLoop(), v8::internal::StringBuiltinsAssembler::StringEqual_Loop(), v8::internal::AccessorAssembler::TryMonomorphicCase(), and v8::internal::AccessorAssembler::TryProbeStubCacheTable().
Load() [2/5]
Node * v8::internal::compiler::CodeAssembler::Load (MachineType type, Node * base, Node * offset)
Definition at line 858 of file code-assembler.cc.
                                                                    {
  return raw_assembler()->Load(type, base, offset);
}
References v8::internal::compiler::RawMachineAssembler::Load(), raw_assembler(), and v8::internal::tracing::type.
Load() [3/5]
template<class Type >
TNode<Type> v8::internal::compiler::CodeAssembler::Load (MachineType type, TNode< RawPtr< Type >> base) [inline]
Definition at line 864 of file code-assembler.h.
                                                               {
    DCHECK(
        IsSubtype(type.representation(), MachineRepresentationOf<Type>::value));
    return UncheckedCast<Type>(Load(type, static_cast<Node*>(base)));
  }
References v8::internal::DCHECK(), v8::internal::IsSubtype(), v8::Load(), and v8::internal::tracing::type.
Load() [4/5]
template<class Type >
TNode<Type> v8::internal::compiler::CodeAssembler::Load (Node * base) [inline]
Definition at line 871 of file code-assembler.h.
                               {
    return UncheckedCast<Type>(Load(MachineTypeOf<Type>::value, base));
  }
References v8::Load().
Load() [5/5]
template<class Type >
TNode<Type> v8::internal::compiler::CodeAssembler::Load (Node * base, TNode< WordT > offset) [inline]
Definition at line 875 of file code-assembler.h.
                                                    {
    return UncheckedCast<Type>(Load(MachineTypeOf<Type>::value, base, offset));
  }
References v8::Load().
LoadFramePointer()
TNode< RawPtrT > v8::internal::compiler::CodeAssembler::LoadFramePointer ()
Definition at line 696 of file code-assembler.cc.
                                               {
  return UncheckedCast<RawPtrT>(raw_assembler()->LoadFramePointer());
}
References raw_assembler().
LoadFromObject()
Node * v8::internal::compiler::CodeAssembler::LoadFromObject (MachineType type, TNode< Object > object, TNode< IntPtrT > offset)
Definition at line 893 of file code-assembler.cc.
                                                           {
  return raw_assembler()->LoadFromObject(type, object, offset);
}
References v8::internal::compiler::RawMachineAssembler::LoadFromObject(), raw_assembler(), and v8::internal::tracing::type.
Referenced by v8::internal::CodeStubAssembler::LoadArrayElement().
LoadFullTagged() [1/2]
TNode< Object > v8::internal::compiler::CodeAssembler::LoadFullTagged (Node * base)
Definition at line 862 of file code-assembler.cc.
                                                      {
  return BitcastWordToTagged(Load<RawPtrT>(base));
}
Referenced by v8::internal::CodeStubArguments::AtIndex(), v8::internal::CodeStubArguments::ForEach(), v8::internal::CodeStubAssembler::GetContinuationPreservedEmbedderData(), v8::internal::MicrotaskQueueBuiltinsAssembler::GetCurrentContext(), v8::internal::CodeStubAssembler::GetPendingMessage(), v8::internal::CodeStubArguments::GetReceiver(), v8::internal::interpreter::InterpreterAssembler::LoadAndUntagRegister(), v8::internal::CodeStubAssembler::LoadFromParentFrame(), v8::internal::interpreter::InterpreterAssembler::LoadRegister(), v8::internal::interpreter::InterpreterAssembler::LoadRegisterFromRegisterList(), LoadRoot(), and v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal().
LoadFullTagged() [2/2]
TNode< Object > v8::internal::compiler::CodeAssembler::LoadFullTagged (Node * base, TNode< IntPtrT > offset)
Definition at line 866 of file code-assembler.cc.
                                                                             {
  // Please use LoadFromObject(MachineType::MapInHeader(), object,
  // IntPtrConstant(-kHeapObjectTag)) instead.
  DCHECK(!raw_assembler()->IsMapOffsetConstantMinusTag(offset));
  return BitcastWordToTagged(Load<RawPtrT>(base, offset));
}
References v8::internal::DCHECK(), and raw_assembler().
LoadParentFramePointer()
TNode< RawPtrT > v8::internal::compiler::CodeAssembler::LoadParentFramePointer ()
Definition at line 700 of file code-assembler.cc.
                                                     {
  return UncheckedCast<RawPtrT>(raw_assembler()->LoadParentFramePointer());
}
References raw_assembler().
Referenced by v8::internal::interpreter::InterpreterAssembler::GetInterpretedFramePointer(), and v8::internal::CodeStubAssembler::LoadFromParentFrame().
LoadPointerFromRootRegister()
TNode< RawPtrT > v8::internal::compiler::CodeAssembler::LoadPointerFromRootRegister (TNode< IntPtrT > offset)
Definition at line 718 of file code-assembler.cc.
                           {
  return UncheckedCast<RawPtrT>(
      Load(MachineType::IntPtr(), raw_assembler()->LoadRootRegister(), offset));
}
References v8::internal::MachineType::IntPtr(), Load(), and raw_assembler().
Referenced by LoadTaggedFromRootRegister().
LoadProtectedPointerFromObject()
Node * v8::internal::compiler::CodeAssembler::LoadProtectedPointerFromObject (TNode< Object > object, TNode< IntPtrT > offset)
Definition at line 898 of file code-assembler.cc.
                                                                           {
  return raw_assembler()->LoadProtectedPointerFromObject(object, offset);
}
References v8::internal::compiler::RawMachineAssembler::LoadProtectedPointerFromObject(), and raw_assembler().
Referenced by v8::internal::WasmBuiltinsAssembler::LoadSharedPartFromInstanceData().
LoadRoot()
TNode< Object > v8::internal::compiler::CodeAssembler::LoadRoot (RootIndex root_index)
Definition at line 924 of file code-assembler.cc.
                                                          {
  if (RootsTable::IsImmortalImmovable(root_index)) {
    Handle<Object> root = isolate()->root_handle(root_index);
    if (IsSmi(*root)) {
      return SmiConstant(i::Cast<Smi>(*root));
    } else {
      return HeapConstantMaybeHole(i::Cast<HeapObject>(root));
    }
  }
  // TODO(jgruber): In theory we could generate better code for this by
  // letting the macro assembler decide how to load from the roots list. In most
  // cases, it would boil down to loading from a fixed kRootRegister offset.
  TNode<ExternalReference> isolate_root =
      ExternalConstant(ExternalReference::isolate_root(isolate()));
  int offset = IsolateData::root_slot_offset(root_index);
  return UncheckedCast<Object>(
      LoadFullTagged(isolate_root, IntPtrConstant(offset)));
}
References ExternalConstant(), HeapConstantMaybeHole(), IntPtrConstant(), v8::internal::RootsTable::IsImmortalImmovable(), isolate(), v8::internal::IsSmi(), LoadFullTagged(), v8::internal::Isolate::root_handle(), v8::internal::IsolateData::root_slot_offset(), and SmiConstant().
Referenced by LoadRootMapWord().
LoadRootMapWord()
TNode< AnyTaggedT > v8::internal::compiler::CodeAssembler::LoadRootMapWord (RootIndex root_index)
Definition at line 913 of file code-assembler.cc.
                                                                     {
#ifdef V8_MAP_PACKING
  Handle<Object> root = isolate()->root_handle(root_index);
  Node* map = HeapConstantNoHole(Cast<Map>(root));
  map = PackMapWord(map);
  return ReinterpretCast<AnyTaggedT>(map);
#else
  return LoadRoot(root_index);
#endif
}
References HeapConstantNoHole(), isolate(), LoadRoot(), and v8::internal::Isolate::root_handle().
LoadTaggedFromRootRegister()
TNode< Object > v8::internal::compiler::CodeAssembler::LoadTaggedFromRootRegister (TNode< IntPtrT > offset)
Definition at line 714 of file code-assembler.cc.
                                                                             {
  return BitcastWordToTagged(LoadPointerFromRootRegister(offset));
}
References LoadPointerFromRootRegister().
Referenced by v8::internal::CodeStubAssembler::TryMatchRootRange().
LoadUint8FromRootRegister()
TNode< Uint8T > v8::internal::compiler::CodeAssembler::LoadUint8FromRootRegister (TNode< IntPtrT > offset)
Definition at line 724 of file code-assembler.cc.
                                                                            {
  return UncheckedCast<Uint8T>(
      Load(MachineType::Uint8(), raw_assembler()->LoadRootRegister(), offset));
}
References Load(), raw_assembler(), and v8::internal::MachineType::Uint8().
MemoryBarrier()
void v8::internal::compiler::CodeAssembler::MemoryBarrier (AtomicMemoryOrder order)
Definition at line 1153 of file code-assembler.cc.
                                                         {
  raw_assembler()->MemoryBarrier(order);
}
References v8::internal::compiler::RawMachineAssembler::MemoryBarrier(), and raw_assembler().
NumberConstant()
TNode< Number > v8::internal::compiler::CodeAssembler::NumberConstant (double value)
Definition at line 322 of file code-assembler.cc.
                                                        {
  int smi_value;
  if (DoubleToSmiInteger(value, &smi_value)) {
    return UncheckedCast<Number>(SmiConstant(smi_value));
  } else {
    // We allocate the heap number constant eagerly at this point instead of
    // deferring allocation to code generation
    // (see AllocateAndInstallRequestedHeapNumbers) since that makes it easier
    // to generate constant lookups for embedded builtins.
    return UncheckedCast<Number>(HeapConstantNoHole(
        isolate()->factory()->NewHeapNumberForCodeAssembler(value)));
  }
}
References v8::internal::DoubleToSmiInteger(), factory(), HeapConstantNoHole(), isolate(), SmiConstant(), and v8::internal::value.
Referenced by v8::internal::ArrayIncludesIndexofAssembler::Generate(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GeneratePackedDoubles(), and v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject().
operator=()
CodeAssembler& v8::internal::compiler::CodeAssembler::operator= (const CodeAssembler &) [delete]
OptimizedAllocate()
TNode< HeapObject > v8::internal::compiler::CodeAssembler::OptimizedAllocate (TNode< IntPtrT > size, AllocationType allocation)
Definition at line 1170 of file code-assembler.cc.
                                                                              {
  return UncheckedCast<HeapObject>(
      raw_assembler()->OptimizedAllocate(size, allocation));
}
References raw_assembler(), and size().
Referenced by v8::internal::CodeStubAssembler::Allocate().
OptimizedStoreField()
void v8::internal::compiler::CodeAssembler::OptimizedStoreField (MachineRepresentation rep, TNode< HeapObject > object, int offset, Node * value)
Definition at line 978 of file code-assembler.cc.
                                                     {
  raw_assembler()->OptimizedStoreField(rep, object, offset, value,
                                       WriteBarrierKind::kFullWriteBarrier);
}
References v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::RawMachineAssembler::OptimizedStoreField(), raw_assembler(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::StoreObjectField().
OptimizedStoreFieldAssertNoWriteBarrier()
void v8::internal::compiler::CodeAssembler::OptimizedStoreFieldAssertNoWriteBarrier (MachineRepresentation rep, TNode< HeapObject > object, int offset, Node * value)
Definition at line 1000 of file code-assembler.cc.
                 {
  raw_assembler()->OptimizedStoreField(rep, object, offset, value,
                                       WriteBarrierKind::kAssertNoWriteBarrier);
}
References v8::internal::compiler::kAssertNoWriteBarrier, v8::internal::compiler::RawMachineAssembler::OptimizedStoreField(), raw_assembler(), and v8::internal::value.
OptimizedStoreFieldUnsafeNoWriteBarrier()
void v8::internal::compiler::CodeAssembler::OptimizedStoreFieldUnsafeNoWriteBarrier (MachineRepresentation rep, TNode< HeapObject > object, int offset, Node * value)
Definition at line 1007 of file code-assembler.cc.
                 {
  raw_assembler()->OptimizedStoreField(rep, object, offset, value,
                                       WriteBarrierKind::kNoWriteBarrier);
}
References v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::RawMachineAssembler::OptimizedStoreField(), raw_assembler(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::UnsafeStoreObjectFieldNoWriteBarrier().
OptimizedStoreIndirectPointerField()
void v8::internal::compiler::CodeAssembler::OptimizedStoreIndirectPointerField (TNode< HeapObject > object, int offset, IndirectPointerTag tag, Node * value)
Definition at line 985 of file code-assembler.cc.
                                                                    {
  raw_assembler()->OptimizedStoreIndirectPointerField(
      object, offset, tag, value,
      WriteBarrierKind::kIndirectPointerWriteBarrier);
}
References v8::internal::compiler::kIndirectPointerWriteBarrier, v8::internal::compiler::RawMachineAssembler::OptimizedStoreIndirectPointerField(), raw_assembler(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::StoreIndirectPointerField().
OptimizedStoreIndirectPointerFieldNoWriteBarrier()
void v8::internal::compiler::CodeAssembler::OptimizedStoreIndirectPointerFieldNoWriteBarrier (TNode< HeapObject > object, int offset, IndirectPointerTag tag, Node * value)
Definition at line 994 of file code-assembler.cc.
                                                                               {
  raw_assembler()->OptimizedStoreIndirectPointerField(
      object, offset, tag, value, WriteBarrierKind::kNoWriteBarrier);
}
References v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::RawMachineAssembler::OptimizedStoreIndirectPointerField(), raw_assembler(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::StoreIndirectPointerFieldNoWriteBarrier().
OptimizedStoreMap()
void v8::internal::compiler::CodeAssembler::OptimizedStoreMap (TNode< HeapObject > object, TNode< Map > map)
Definition at line 1014 of file code-assembler.cc.
                                                      {
  raw_assembler()->OptimizedStoreMap(object, map);
}
References v8::internal::compiler::RawMachineAssembler::OptimizedStoreMap(), and raw_assembler().
Referenced by v8::internal::CodeStubAssembler::StoreMap(), and v8::internal::CodeStubAssembler::StoreMapNoWriteBarrier().
Parameter()
template<class T >
TNode<T> v8::internal::compiler::CodeAssembler::Parameter (int value, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 698 of file code-assembler.h.
                                                                          {
    static_assert(
        std::is_convertible_v<TNode<T>, TNode<Object>>,
        "Parameter is only for tagged types. Use UncheckedParameter instead.");
    std::stringstream message;
    message << "Parameter " << value;
    if (loc.FileName()) {
      message << " at " << loc.FileName() << ":" << loc.Line();
    }
    size_t buf_size = message.str().size() + 1;
    char* message_dup = zone()->AllocateArray<char>(buf_size);
    snprintf(message_dup, buf_size, "%s", message.str().c_str());
    return Cast(UntypedParameter(value), message_dup);
  }
References v8::internal::Cast(), v8::SourceLocation::FileName(), v8::SourceLocation::Line(), v8::internal::loc, and v8::internal::value.
PointerConstant()
TNode<RawPtrT> v8::internal::compiler::CodeAssembler::PointerConstant (void * value) [inline]
Definition at line 603 of file code-assembler.h.
                                              {
    return ReinterpretCast<RawPtrT>(
        IntPtrConstant(reinterpret_cast<intptr_t>(value)));
  }
References v8::internal::compiler::IntPtrConstant(), and v8::internal::value.
PopAndReturn() [1/2]
void v8::internal::compiler::CodeAssembler::PopAndReturn (Node * pop, Node * value)
Definition at line 634 of file code-assembler.cc.
                                                       {
  DCHECK_EQ(1, raw_assembler()->call_descriptor()->ReturnCount());
  return raw_assembler()->PopAndReturn(pop, value);
}
References DCHECK_EQ, v8::internal::compiler::RawMachineAssembler::PopAndReturn(), raw_assembler(), and v8::internal::value.
Referenced by v8::internal::CodeStubArguments::PopAndReturn(), and v8::internal::ArrayBuiltinsAssembler::ReturnFromBuiltin().
PopAndReturn() [2/2]
void v8::internal::compiler::CodeAssembler::PopAndReturn (Node * pop, Node * value1, Node * value2, Node * value3, Node * value4)
Definition at line 639 of file code-assembler.cc.
                                                             {
  DCHECK_EQ(4, raw_assembler()->call_descriptor()->ReturnCount());
  return raw_assembler()->PopAndReturn(pop, value1, value2, value3, value4);
}
References DCHECK_EQ, v8::internal::compiler::RawMachineAssembler::PopAndReturn(), and raw_assembler().
PopSourcePosition()
void v8::internal::compiler::CodeAssembler::PopSourcePosition ()
Definition at line 679 of file code-assembler.cc.
                                      {
  state_->macro_call_stack_.pop_back();
}
References v8::internal::compiler::CodeAssemblerState::macro_call_stack_, and state_.
Projection() [1/2]
Node * v8::internal::compiler::CodeAssembler::Projection (int index, Node * value) [private]
Definition at line 1165 of file code-assembler.cc.
                                                      {
  DCHECK_LT(index, value->op()->ValueOutputCount());
  return raw_assembler()->Projection(index, value);
}
References DCHECK_LT, v8::internal::index, v8::internal::compiler::RawMachineAssembler::Projection(), raw_assembler(), and v8::internal::value.
Projection() [2/2]
template<int index, class T1 , class T2 >
TNode<std::tuple_element_t<index, std::tuple<T1, T2> > > v8::internal::compiler::CodeAssembler::Projection (TNode< PairT< T1, T2 >> value) [inline]
Definition at line 1300 of file code-assembler.h.
                                  {
    return UncheckedCast<std::tuple_element_t<index, std::tuple<T1, T2>>>(
        Projection(index, value));
  }
References v8::internal::index, and v8::internal::value.
PushSourcePosition()
void v8::internal::compiler::CodeAssembler::PushSourcePosition ()
Definition at line 674 of file code-assembler.cc.
                                       {
  auto position = raw_assembler()->GetCurrentExternalSourcePosition();
  state_->macro_call_stack_.push_back(position);
}
References v8::internal::compiler::RawMachineAssembler::GetCurrentExternalSourcePosition(), v8::internal::compiler::CodeAssemblerState::macro_call_stack_, raw_assembler(), and state_.
Referenced by v8::internal::compiler::CodeAssembler::SourcePositionScope::SourcePositionScope().
raw_assembler()
RawMachineAssembler * v8::internal::compiler::CodeAssembler::raw_assembler () const [private]
Definition at line 1679 of file code-assembler.cc.
                                                        {
  return state_->raw_assembler_.get();
}
References v8::internal::compiler::CodeAssemblerState::raw_assembler_, and state_.
Referenced by AbortCSADcheck(), AtomicCompareExchange(), AtomicCompareExchange64(), AtomicLoad(), AtomicLoad64(), AtomicStore(), AtomicStore64(), Branch(), BreakOnNode(), CallCFunctionN(), CallRuntimeImpl(), CallStubN(), ChangeFloat64ToIntPtr(), ChangeFloat64ToUintPtr(), ChangeInt32ToIntPtr(), ChangeUint32ToWord(), ChangeUintPtrToFloat64(), DebugBreak(), DynamicJSParameterCount(), EmitComment(), ExternalConstant(), GetJSContextParameter(), Goto(), HandleException(), HasDynamicJSParameterCount(), Int32PairAdd(), Int32PairSub(), Is32(), Is64(), IsFloat64RoundDownSupported(), IsFloat64RoundTiesEvenSupported(), IsFloat64RoundTruncateSupported(), IsFloat64RoundUpSupported(), IsInt32AbsWithOverflowSupported(), IsInt64AbsWithOverflowSupported(), IsJSFunctionCall(), IsMapOffsetConstant(), isolate(), IsTruncateFloat64ToFloat16RawBitsSupported(), IsWord32CtzSupported(), IsWord32PopcntSupported(), IsWord64CtzSupported(), IsWord64PopcntSupported(), Load(), LoadFramePointer(), LoadFromObject(), LoadFullTagged(), LoadParentFramePointer(), LoadPointerFromRootRegister(), LoadProtectedPointerFromObject(), LoadUint8FromRootRegister(), MemoryBarrier(), OptimizedAllocate(), OptimizedStoreField(), OptimizedStoreFieldAssertNoWriteBarrier(), OptimizedStoreFieldUnsafeNoWriteBarrier(), OptimizedStoreIndirectPointerField(), OptimizedStoreIndirectPointerFieldNoWriteBarrier(), OptimizedStoreMap(), PopAndReturn(), Projection(), PushSourcePosition(), Return(), RoundIntPtrToFloat64(), SetDynamicJSParameterCount(), SetSourcePosition(), StackSlotPtr(), StaticAssert(), Store(), StoreEphemeronKey(), StoreFullTaggedNoWriteBarrier(), StoreNoWriteBarrier(), StoreToObject(), Switch(), TailCallBytecodeDispatch(), TailCallJSCode(), TailCallRuntimeImpl(), TailCallStubImpl(), TailCallStubThenBytecodeDispatchImpl(), TruncateFloat32ToInt32(), TruncateFloat64ToInt64(), UnalignedLoad(), UnalignedLoadSupported(), UnalignedStoreSupported(), Unreachable(), UnsafeStoreNoWriteBarrier(), UntypedParameter(), Word32ShiftIsSafe(), and zone().
RawPtrAdd()
TNode<RawPtrT> v8::internal::compiler::CodeAssembler::RawPtrAdd (TNode< RawPtrT > left, TNode< IntPtrT > right) [inline]
Definition at line 1226 of file code-assembler.h.
                                                                      {
    return ReinterpretCast<RawPtrT>(IntPtrAdd(left, right));
  }
References v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrAdd().
Referenced by v8::internal::StringBuiltinsAssembler::AllocAndCopyStringCharacters(), v8::internal::CodeStubArguments::AtIndexPtr(), v8::internal::CodeStubArguments::CodeStubArguments(), v8::internal::StringBuiltinsAssembler::DirectStringData(), v8::internal::CodeStubAssembler::LoadJSTypedArrayDataPtr(), v8::internal::StringBuiltinsAssembler::SearchOneByteInOneByteString(), v8::internal::TypedArrayBuiltinsAssembler::SetJSTypedArrayOffHeapDataPtr(), v8::internal::StringBuiltinsAssembler::StringEqual_FastLoop(), v8::internal::StringBuiltinsAssembler::StringEqual_Loop(), v8::internal::ToDirectStringAssembler::TryToSequential(), and v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateIntegerTypedArray().
RawPtrSub() [1/2]
TNode<RawPtrT> v8::internal::compiler::CodeAssembler::RawPtrSub (TNode< RawPtrT > left, TNode< IntPtrT > right) [inline]
Definition at line 1229 of file code-assembler.h.
                                                                      {
    return ReinterpretCast<RawPtrT>(IntPtrSub(left, right));
  }
Referenced by v8::internal::StringBuiltinsAssembler::SearchOneByteInOneByteString(), and v8::internal::ToDirectStringAssembler::TryToSequential().
RawPtrSub() [2/2]
TNode<IntPtrT> v8::internal::compiler::CodeAssembler::RawPtrSub (TNode< RawPtrT > left, TNode< RawPtrT > right) [inline]
Definition at line 1232 of file code-assembler.h.
                                                                      {
    return Signed(IntPtrSub(static_cast<TNode<WordT>>(left),
                            static_cast<TNode<WordT>>(right)));
  }
References v8::base::bits::Signed().
RegisterCallGenerationCallbacks()
void v8::internal::compiler::CodeAssembler::RegisterCallGenerationCallbacks (const CodeAssemblerCallback & call_prologue, const CodeAssemblerCallback & call_epilogue) [protected]
Definition at line 130 of file code-assembler.cc.
                                                {
  // The callback can be registered only once.
  DCHECK(!state_->call_prologue_);
  DCHECK(!state_->call_epilogue_);
  state_->call_prologue_ = call_prologue;
  state_->call_epilogue_ = call_epilogue;
}
References v8::internal::compiler::CodeAssemblerState::call_epilogue_, v8::internal::compiler::CodeAssemblerState::call_prologue_, v8::internal::DCHECK(), and state_.
Referenced by v8::internal::interpreter::InterpreterAssembler::InterpreterAssembler().
ReinterpretCast()
template<class T >
TNode<T> v8::internal::compiler::CodeAssembler::ReinterpretCast (Node * value) [inline]
Definition at line 547 of file code-assembler.h.
                                        {
    return TNode<T>::UncheckedCast(value);
  }
References v8::internal::TNode< T >::UncheckedCast(), and v8::internal::value.
Return() [1/12]
void v8::internal::compiler::CodeAssembler::Return (TNode< Float32T > value)
Definition at line 580 of file code-assembler.cc.
                                                {
  DCHECK_EQ(1, raw_assembler()->call_descriptor()->ReturnCount());
  DCHECK_EQ(MachineType::Float32(),
            raw_assembler()->call_descriptor()->GetReturnType(0));
  return raw_assembler()->Return(value);
}
References DCHECK_EQ, v8::internal::MachineType::Float32(), raw_assembler(), v8::internal::compiler::RawMachineAssembler::Return(), and v8::internal::value.
Return() [2/12]
void v8::internal::compiler::CodeAssembler::Return (TNode< Float64T > value)
Definition at line 587 of file code-assembler.cc.
                                                {
  DCHECK_EQ(1, raw_assembler()->call_descriptor()->ReturnCount());
  DCHECK_EQ(MachineType::Float64(),
            raw_assembler()->call_descriptor()->GetReturnType(0));
  return raw_assembler()->Return(value);
}
References DCHECK_EQ, v8::internal::MachineType::Float64(), raw_assembler(), v8::internal::compiler::RawMachineAssembler::Return(), and v8::internal::value.
Return() [3/12]
void v8::internal::compiler::CodeAssembler::Return (TNode< Int32T > value)
Definition at line 558 of file code-assembler.cc.
                                              {
  DCHECK_EQ(1, raw_assembler()->call_descriptor()->ReturnCount());
  DCHECK_EQ(MachineType::Int32(),
            raw_assembler()->call_descriptor()->GetReturnType(0));
  return raw_assembler()->Return(value);
}
References DCHECK_EQ, v8::internal::MachineType::Int32(), raw_assembler(), v8::internal::compiler::RawMachineAssembler::Return(), and v8::internal::value.
Return() [4/12]
void v8::internal::compiler::CodeAssembler::Return (TNode< Object > value)
Definition at line 536 of file code-assembler.cc.
                                              {
  DCHECK_EQ(1, raw_assembler()->call_descriptor()->ReturnCount());
  DCHECK(raw_assembler()->call_descriptor()->GetReturnType(0).IsTagged());
  return raw_assembler()->Return(value);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::IsTagged, raw_assembler(), v8::internal::compiler::RawMachineAssembler::Return(), and v8::internal::value.
Referenced by v8::internal::AsyncFunctionBuiltinsAssembler::AsyncFunctionAwait(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::DeletePropertyBaseAssembler::DeleteDictionaryProperty(), v8::internal::DateBuiltinsAssembler::Generate_DatePrototype_GetField(), v8::internal::HandlerBuiltinsAssembler::Generate_ElementsTransitionAndStore(), v8::internal::HandlerBuiltinsAssembler::Generate_KeyedStoreIC_SloppyArguments(), v8::internal::HandlerBuiltinsAssembler::Generate_StoreFastElementIC(), v8::internal::ArrayBuiltinsAssembler::GenerateArrayNoArgumentConstructor(), v8::internal::AccessorAssembler::GenerateCloneObjectIC(), v8::internal::AccessorAssembler::GenerateCloneObjectIC_Slow(), v8::internal::ArrayBuiltinsAssembler::GenerateConstructor(), v8::internal::BaseCollectionsAssembler::GenerateConstructor(), v8::internal::WriteBarrierCodeStubAssembler::GenerateEphemeronKeyBarrier(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::WriteBarrierCodeStubAssembler::GenerateIndirectPointerBarrier(), v8::internal::AccessorAssembler::GenerateKeyedHasIC_Megamorphic(), v8::internal::ArrayIncludesIndexofAssembler::GeneratePackedDoubles(), v8::internal::WriteBarrierCodeStubAssembler::GenerateRecordWrite(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::StringBuiltinsAssembler::GenerateStringEqual(), v8::internal::StringBuiltinsAssembler::GenerateStringRelationalComparison(), v8::internal::AccessorAssembler::GenericElementLoad(), v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::GetOwnValuesOrEntries(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleStoreFieldAndReturn(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::HandleStoreICSmiHandlerJSSharedStructFieldCase(), v8::internal::AccessorAssembler::HandleStoreToProxy(), v8::internal::AccessorAssembler::LoadGlobalIC_NoFeedback(), v8::internal::AccessorAssembler::LoadIC_NoFeedback(), v8::internal::AccessorAssembler::LookupContext(), v8::internal::KeyedStoreGenericAssembler::MaybeUpdateLengthAndReturn(), v8::internal::ExitPoint::Return(), v8::internal::ArrayBuiltinsAssembler::ReturnFromBuiltin(), ReturnIf(), v8::internal::ArrayIncludesIndexofAssembler::ReturnIfEmpty(), v8::internal::ObjectBuiltinsAssembler::ReturnToStringFormat(), v8::internal::AccessorAssembler::ScriptContextTableLookup(), v8::internal::AccessorAssembler::StoreGlobalIC(), and v8::internal::KeyedStoreGenericAssembler::StoreSharedArrayElement().
Return() [5/12]
void v8::internal::compiler::CodeAssembler::Return (TNode< Object > value1, TNode< Object > value2)
Definition at line 542 of file code-assembler.cc.
                                                                     {
  DCHECK_EQ(2, raw_assembler()->call_descriptor()->ReturnCount());
  DCHECK(raw_assembler()->call_descriptor()->GetReturnType(0).IsTagged());
  DCHECK(raw_assembler()->call_descriptor()->GetReturnType(1).IsTagged());
  return raw_assembler()->Return(value1, value2);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::IsTagged, raw_assembler(), and v8::internal::compiler::RawMachineAssembler::Return().
Return() [6/12]
void v8::internal::compiler::CodeAssembler::Return (TNode< Object > value1, TNode< Object > value2, TNode< Object > value3)
Definition at line 549 of file code-assembler.cc.
                                                 {
  DCHECK_EQ(3, raw_assembler()->call_descriptor()->ReturnCount());
  DCHECK(raw_assembler()->call_descriptor()->GetReturnType(0).IsTagged());
  DCHECK(raw_assembler()->call_descriptor()->GetReturnType(1).IsTagged());
  DCHECK(raw_assembler()->call_descriptor()->GetReturnType(2).IsTagged());
  return raw_assembler()->Return(value1, value2, value3);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::IsTagged, raw_assembler(), and v8::internal::compiler::RawMachineAssembler::Return().
Return() [7/12]
void v8::internal::compiler::CodeAssembler::Return (TNode< Uint32T > value)
Definition at line 565 of file code-assembler.cc.
                                               {
  DCHECK_EQ(1, raw_assembler()->call_descriptor()->ReturnCount());
  DCHECK_EQ(MachineType::Uint32(),
            raw_assembler()->call_descriptor()->GetReturnType(0));
  return raw_assembler()->Return(value);
}
References DCHECK_EQ, raw_assembler(), v8::internal::compiler::RawMachineAssembler::Return(), v8::internal::MachineType::Uint32(), and v8::internal::value.
Return() [8/12]
void v8::internal::compiler::CodeAssembler::Return (TNode< Word32T > value1, TNode< Object > value2)
Definition at line 625 of file code-assembler.cc.
                                                                      {
  DCHECK_EQ(2, raw_assembler()->call_descriptor()->ReturnCount());
  DCHECK_EQ(
      MachineRepresentation::kWord32,
      raw_assembler()->call_descriptor()->GetReturnType(0).representation());
  DCHECK(raw_assembler()->call_descriptor()->GetReturnType(1).IsTagged());
  return raw_assembler()->Return(value1, value2);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::IsTagged, v8::internal::kWord32, raw_assembler(), and v8::internal::compiler::RawMachineAssembler::Return().
Return() [9/12]
void v8::internal::compiler::CodeAssembler::Return (TNode< Word32T > value1, TNode< Word32T > value2)
Definition at line 605 of file code-assembler.cc.
                                                                       {
  DCHECK_EQ(2, raw_assembler()->call_descriptor()->ReturnCount());
  DCHECK_EQ(
      MachineRepresentation::kWord32,
      raw_assembler()->call_descriptor()->GetReturnType(0).representation());
  DCHECK_EQ(
      MachineRepresentation::kWord32,
      raw_assembler()->call_descriptor()->GetReturnType(1).representation());
  return raw_assembler()->Return(value1, value2);
}
References DCHECK_EQ, v8::internal::kWord32, raw_assembler(), and v8::internal::compiler::RawMachineAssembler::Return().
Return() [10/12]
void v8::internal::compiler::CodeAssembler::Return (TNode< WordT > value)
Definition at line 572 of file code-assembler.cc.
                                             {
  DCHECK_EQ(1, raw_assembler()->call_descriptor()->ReturnCount());
  DCHECK_EQ(
      MachineType::PointerRepresentation(),
      raw_assembler()->call_descriptor()->GetReturnType(0).representation());
  return raw_assembler()->Return(value);
}
References DCHECK_EQ, v8::internal::MachineType::PointerRepresentation(), raw_assembler(), v8::internal::compiler::RawMachineAssembler::Return(), and v8::internal::value.
Return() [11/12]
void v8::internal::compiler::CodeAssembler::Return (TNode< WordT > value1, TNode< Object > value2)
Definition at line 616 of file code-assembler.cc.
                                                                    {
  DCHECK_EQ(2, raw_assembler()->call_descriptor()->ReturnCount());
  DCHECK_EQ(
      MachineType::PointerRepresentation(),
      raw_assembler()->call_descriptor()->GetReturnType(0).representation());
  DCHECK(raw_assembler()->call_descriptor()->GetReturnType(1).IsTagged());
  return raw_assembler()->Return(value1, value2);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::IsTagged, v8::internal::MachineType::PointerRepresentation(), raw_assembler(), and v8::internal::compiler::RawMachineAssembler::Return().
Return() [12/12]
void v8::internal::compiler::CodeAssembler::Return (TNode< WordT > value1, TNode< WordT > value2)
Definition at line 594 of file code-assembler.cc.
                                                                   {
  DCHECK_EQ(2, raw_assembler()->call_descriptor()->ReturnCount());
  DCHECK_EQ(
      MachineType::PointerRepresentation(),
      raw_assembler()->call_descriptor()->GetReturnType(0).representation());
  DCHECK_EQ(
      MachineType::PointerRepresentation(),
      raw_assembler()->call_descriptor()->GetReturnType(1).representation());
  return raw_assembler()->Return(value1, value2);
}
References DCHECK_EQ, v8::internal::MachineType::PointerRepresentation(), raw_assembler(), and v8::internal::compiler::RawMachineAssembler::Return().
ReturnIf()
void v8::internal::compiler::CodeAssembler::ReturnIf (TNode< BoolT > condition, TNode< Object > value)
Definition at line 645 of file code-assembler.cc.
                                                                        {
  Label if_return(this), if_continue(this);
  Branch(condition, &if_return, &if_continue);
  Bind(&if_return);
  Return(value);
  Bind(&if_continue);
}
References Bind(), Branch(), Return(), and v8::internal::value.
Referenced by v8::internal::AccessorAssembler::GenerateCloneObjectIC_Slow().
RoundIntPtrToFloat64()
TNode< Float64T > v8::internal::compiler::CodeAssembler::RoundIntPtrToFloat64 (Node * value)
Definition at line 832 of file code-assembler.cc.
                                                               {
  if (raw_assembler()->machine()->Is64()) {
    return UncheckedCast<Float64T>(raw_assembler()->RoundInt64ToFloat64(value));
  }
  return UncheckedCast<Float64T>(raw_assembler()->ChangeInt32ToFloat64(value));
}
References Is64(), raw_assembler(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::NumberDictionaryLookup().
SetDynamicJSParameterCount()
void v8::internal::compiler::CodeAssembler::SetDynamicJSParameterCount (TNode< Uint16T > parameter_count)
Definition at line 522 of file code-assembler.cc.
                                                                             {
  DCHECK(!HasDynamicJSParameterCount());
  // For code to support a dynamic parameter count, it's static parameter count
  // must currently be zero, i.e. varargs. Otherwise we'd also need to ensure
  // that the dynamic parameter count is not smaller than the static one.
  //
  // TODO(saelo): it would probably be a bit nicer if we could assert here that
  // IsJSFunctionCall() is true and then use the JSParameterCount() of the
  // descriptor instead, but that doesn't work because not all users of this
  // feature are TFJ builtins (some are TFC builtins).
  DCHECK_EQ(raw_assembler()->call_descriptor()->ParameterSlotCount(), 0);
  raw_assembler()->set_dynamic_js_parameter_count(parameter_count);
}
References v8::internal::DCHECK(), DCHECK_EQ, HasDynamicJSParameterCount(), raw_assembler(), and v8::internal::compiler::RawMachineAssembler::set_dynamic_js_parameter_count().
Referenced by v8::internal::CodeStubAssembler::SetSupportsDynamicParameterCount().
SetSourcePosition()
void v8::internal::compiler::CodeAssembler::SetSourcePosition (const char * file, int line)
Definition at line 670 of file code-assembler.cc.
                                                                {
  raw_assembler()->SetCurrentExternalSourcePosition({file, line});
}
References file(), raw_assembler(), and v8::internal::compiler::RawMachineAssembler::SetCurrentExternalSourcePosition().
Signed() [1/4]
TNode<Int32T> v8::internal::compiler::CodeAssembler::Signed (TNode< Int32T > x) [private]
Signed() [2/4]
TNode<Int32T> v8::internal::compiler::CodeAssembler::Signed (TNode< Word32T > x) [inline]
Definition at line 665 of file code-assembler.h.
{ return UncheckedCast<Int32T>(x); }
Referenced by v8::internal::CollectionsBuiltinsAssembler::AddNewToOrderedHashTable(), v8::internal::CodeStubAssembler::AllocateByteArray(), v8::internal::CodeStubAssembler::AllocateNonEmptyByteArray(), v8::internal::CodeStubAssembler::AllocateOrderedHashTableWithCapacity(), v8::internal::CodeStubAssembler::AllocateRawBigInt(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::CallOrConstructBuiltinsAssembler::BuildConstruct(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandIdxSmi(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandIdxTaggedIndex(), v8::internal::CallOrConstructBuiltinsAssembler::CallReceiver(), v8::internal::CodeStubAssembler::ChangeTaggedNonSmiToInt32(), v8::internal::CodeStubAssembler::ChangeUint32ToTagged(), v8::internal::CodeStubAssembler::ChangeUintPtrToTagged(), v8::internal::AccessorAssembler::CheckDescriptorConsidersNumbersMutable(), v8::internal::AccessorAssembler::CheckHeapObjectTypeMatchesDescriptor(), v8::internal::WeakCollectionsBuiltinsAssembler::Coefficient(), v8::internal::interpreter::InterpreterAssembler::Construct(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::CodeStubAssembler::CountTrailingZeros32(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchSingleArgument(), v8::internal::CodeStubAssembler::DoubleStringCacheEntryToOffset(), v8::internal::CodeStubAssembler::EnsureArrayPushable(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FastGetOwnValuesOrEntries(), v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntry(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForBigIntKey(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForHeapNumberKey(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForOtherKey(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForSmiKey(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForStringKey(), v8::internal::CodeStubAssembler::Float64ToString(), v8::internal::BinaryOpAssembler::Generate_AddStringConstantInternalizeWithFeedback(), v8::internal::WeakCollectionsBuiltinsAssembler::GetHash(), v8::internal::CodeStubAssembler::GetMarkBit(), v8::internal::AccessorAssembler::HandleLoadCallbackProperty(), v8::internal::AccessorAssembler::HandleLoadField(), v8::internal::AccessorAssembler::HandlePolymorphicCase(), v8::internal::AccessorAssembler::HandleStoreFieldAndReturn(), v8::internal::AccessorAssembler::HandleStoreICNativeDataProperty(), v8::internal::AccessorAssembler::HandleStoreICSmiHandlerJSSharedStructFieldCase(), v8::internal::CodeStubAssembler::InitializeJSObjectBodyWithSlackTracking(), v8::internal::WeakCollectionsBuiltinsAssembler::InsufficientCapacityToAdd(), v8::internal::CodeStubAssembler::IntPtrRoundUpToPowerOfTwo32(), v8::internal::interpreter::InterpreterAssembler::JumpConditionalByImmediateOperand(), v8::internal::CodeStubAssembler::LoadFixedTypedArrayElementAsTagged(), v8::internal::AccessorAssembler::LoadGlobalIC_TryPropertyCellCase(), v8::internal::CodeStubAssembler::LoadJSTypedArrayDataPtr(), v8::internal::CodeStubAssembler::LoadMapElementsKind(), v8::internal::GeneratorBuiltinsAssembler::LoadParameterCountWithoutReceiverFromBaseline(), v8::internal::CodeStubAssembler::LoadPropertyArrayLength(), v8::internal::CodeStubAssembler::LoadStringLengthAsWord(), v8::internal::KeyedStoreGenericAssembler::MaybeUpdateLengthAndReturn(), v8::internal::CodeStubAssembler::NameDictionaryLookup(), v8::internal::interpreter::InterpreterAssembler::NextRegister(), v8::internal::CodeStubAssembler::NumberDictionaryLookup(), v8::internal::interpreter::InterpreterAssembler::OnStackReplacement(), v8::internal::AccessorAssembler::OverwriteExistingFastDataProperty(), v8::internal::CodeStubAssembler::PopulationCountFallback(), v8::internal::BigIntBuiltinsAssembler::ReadBigIntLength(), v8::internal::interpreter::InterpreterAssembler::RegisterLocation(), v8::internal::interpreter::InterpreterAssembler::RegisterLocationInRegisterList(), v8::internal::TypedArrayBuiltinsAssembler::SetJSTypedArrayOffHeapDataPtr(), v8::internal::TypedArrayBuiltinsAssembler::SetJSTypedArrayOnHeapDataPtr(), v8::internal::CodeStubAssembler::SmiFromUint32(), v8::internal::CodeStubAssembler::SmiToInt32(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::CodeStubAssembler::SmiUntag(), v8::internal::CodeStubAssembler::StoreFeedbackVectorSlot(), v8::internal::CodeStubAssembler::StoreFixedArrayOrPropertyArrayElement(), v8::internal::AccessorAssembler::StoreGlobalIC(), v8::internal::AccessorAssembler::StoreJSSharedStructField(), v8::internal::interpreter::InterpreterAssembler::StoreRegisterForShortStar(), v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::CodeStubAssembler::StringToNumber(), v8::internal::AccessorAssembler::StubCachePrimaryOffset(), v8::internal::AccessorAssembler::StubCacheSecondaryOffset(), v8::internal::StringBuiltinsAssembler::SubString(), v8::internal::CodeStubAssembler::TaggedIndexToIntPtr(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::CodeStubAssembler::TruncateHeapNumberValueToWord32(), v8::internal::CodeStubAssembler::TruncateNumberToWord32(), v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad(), v8::internal::CodeStubAssembler::TryMatchRootRange(), v8::internal::CodeStubAssembler::TryToName(), and v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateIntegerTypedArray().
Signed() [3/4]
TNode<Int64T> v8::internal::compiler::CodeAssembler::Signed (TNode< Word64T > x) [inline]
Definition at line 666 of file code-assembler.h.
{ return UncheckedCast<Int64T>(x); }
Signed() [4/4]
TNode<IntPtrT> v8::internal::compiler::CodeAssembler::Signed (TNode< WordT > x) [inline]
Definition at line 667 of file code-assembler.h.
{ return UncheckedCast<IntPtrT>(x); }
SmiConstant() [1/2]
TNode< Smi > v8::internal::compiler::CodeAssembler::SmiConstant (int value)
Definition at line 341 of file code-assembler.cc.
                                               {
  return SmiConstant(Smi::FromInt(value));
}
References v8::internal::Smi::FromInt(), SmiConstant(), and v8::internal::value.
SmiConstant() [2/2]
TNode< Smi > v8::internal::compiler::CodeAssembler::SmiConstant (Tagged< Smi > value)
Definition at line 336 of file code-assembler.cc.
                                                       {
  return UncheckedCast<Smi>(BitcastWordToTaggedSigned(
      IntPtrConstant(static_cast<intptr_t>(value.ptr()))));
}
References IntPtrConstant(), and v8::internal::value.
Referenced by v8::internal::interpreter::InterpreterAssembler::Abort(), v8::internal::CodeStubAssembler::AddToDictionary(), v8::internal::CollectionsBuiltinsAssembler::AddValueToKeyedGroup(), v8::internal::CodeStubAssembler::AllocateArrayList(), v8::internal::IntlBuiltinsAssembler::AllocateEmptyJSArray(), v8::internal::TypedArrayBuiltinsAssembler::AllocateEmptyOnHeapBuffer(), v8::internal::CollectionsBuiltinsAssembler::AllocateJSCollectionIterator(), v8::internal::CodeStubAssembler::AllocateNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::AllocateOrderedHashTableWithCapacity(), v8::internal::CodeStubAssembler::AllocateOrderedNameDictionary(), v8::internal::CodeStubAssembler::AllocateRaw(), v8::internal::RegExpBuiltinsAssembler::AllocateRegExpResult(), v8::internal::CodeStubAssembler::AllocateRootFunctionWithContext(), v8::internal::CodeStubAssembler::AllocateSeqOneByteString(), v8::internal::CodeStubAssembler::AllocateSeqTwoByteString(), v8::internal::CodeStubAssembler::AllocateSharedHeapNumberWithValue(), v8::internal::CodeStubAssembler::AllocateSimpleNameDictionaryWithCapacity(), v8::internal::WeakCollectionsBuiltinsAssembler::AllocateTable(), v8::internal::CodeStubAssembler::ArrayCreate(), v8::internal::CodeStubAssembler::ArrayListAdd(), v8::internal::CodeStubAssembler::ArrayListEnsureSpace(), v8::internal::AsyncFunctionBuiltinsAssembler::AsyncFunctionAwaitResumeClosure(), v8::internal::AsyncBuiltinsAssembler::Await(), v8::internal::CodeStubAssembler::BIntConstant(), v8::internal::CollectionsBuiltinsAssembler::BranchIfIterableWithOriginalKeyOrValueMapIterator(), v8::internal::CollectionsBuiltinsAssembler::BranchIfIterableWithOriginalValueSetIterator(), v8::internal::CollectionsBuiltinsAssembler::BranchIfMapIteratorProtectorValid(), v8::internal::CollectionsBuiltinsAssembler::BranchIfSetIteratorProtectorValid(), v8::internal::StringBuiltinsAssembler::BranchIfStringPrimitiveWithNoCustomIteration(), v8::internal::CodeStubAssembler::BranchIfToBooleanIsTrue(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithSpread(), v8::internal::CodeStubAssembler::CheckEnumCache(), v8::internal::ProxiesCodeStubAssembler::CheckGetSetTrapResult(), v8::internal::CodeStubAssembler::CheckPrototypeEnumCache(), v8::internal::AccessorAssembler::CheckPrototypeValidityCell(), v8::internal::CodeStubAssembler::ClearTrustedPointerField(), v8::internal::SlowBoilerplateCloneAssembler::CloneElementsOfFixedArray(), v8::internal::ArrayPopulatorAssembler::ConstructArrayLike(), v8::internal::RegExpBuiltinsAssembler::ConstructNewResultFromMatchInfo(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchSingleArgument(), v8::internal::ConstructorBuiltinsAssembler::CreateEmptyArrayLiteral(), v8::internal::ConstructorBuiltinsAssembler::CreateRegExpLiteral(), v8::internal::CollectionsBuiltinsAssembler::DeleteFromSetTable(), v8::internal::DeletePropertyBaseAssembler::DictionarySpecificDelete(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::CodeStubAssembler::FailAssert(), v8::internal::RegExpBuiltinsAssembler::FastFlagGetter(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FastGetOwnValuesOrEntries(), v8::internal::CodeStubAssembler::FixedArrayBoundsCheck(), v8::internal::BinaryOpAssembler::Generate_AddStringConstantInternalizeWithFeedback(), v8::internal::BinaryOpAssembler::Generate_AddWithFeedback(), v8::internal::BinaryOpAssembler::Generate_BinaryOperationWithFeedback(), v8::internal::BinaryOpAssembler::Generate_BitwiseBinaryOpWithOptionalFeedback(), v8::internal::BinaryOpAssembler::Generate_BitwiseBinaryOpWithSmiOperandAndOptionalFeedback(), v8::internal::DateBuiltinsAssembler::Generate_DatePrototype_GetField(), v8::internal::BinaryOpAssembler::Generate_DivideWithFeedback(), v8::internal::BinaryOpAssembler::Generate_ExponentiateWithFeedback(), v8::internal::BinaryOpAssembler::Generate_SubtractWithFeedback(), v8::internal::ArrayBuiltinsAssembler::GenerateArrayNoArgumentConstructor(), v8::internal::AccessorAssembler::GenerateCloneObjectIC_Slow(), v8::internal::ArrayBuiltinsAssembler::GenerateConstructor(), v8::internal::AccessorAssembler::GenerateLoadIC_Megamorphic(), v8::internal::StringBuiltinsAssembler::GenerateStringRelationalComparison(), v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::CodeStubAssembler::GetNameDictionaryFlags(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::GetOwnValuesOrEntries(), v8::internal::CodeStubAssembler::GetSharedFunctionInfoCode(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::CodeStubAssembler::IncrementCallCount(), v8::internal::StringBuiltinsAssembler::IndexOfDollarChar(), v8::internal::RegExpBuiltinsAssembler::InitializeMatchInfoFromRegisters(), v8::internal::GeneratorBuiltinsAssembler::InnerResume(), v8::internal::CodeStubAssembler::InsertEntry(), v8::internal::CodeStubAssembler::IsArrayIteratorProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsArraySpeciesProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsFixedArrayWithKindOrEmpty(), v8::internal::CodeStubAssembler::IsIsConcatSpreadableProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsMapIteratorProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsMegaDOMProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsNoElementsProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsNumberStringNotRegexpLikeProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsPromiseResolveProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsPromiseSpeciesProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsPromiseThenProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsRegExpSpeciesProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsSetIteratorProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsStringWrapperToPrimitiveProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsTypedArraySpeciesProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsZeroOrContext(), v8::internal::KeyedStoreGenericAssembler::KeyedStoreGeneric(), v8::internal::CodeStubAssembler::LoadBuiltin(), v8::internal::RegExpBuiltinsAssembler::LoadCaptureCount(), v8::internal::AccessorAssembler::LoadGlobalIC(), v8::internal::AccessorAssembler::LoadIC(), v8::internal::AccessorAssembler::LoadIC_BytecodeHandler(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), LoadRoot(), v8::internal::CodeStubAssembler::LoadSharedFunctionInfoTrustedData(), v8::internal::CodeStubAssembler::NoContextConstant(), v8::internal::CollectionsBuiltinsAssembler::NormalizeNumberKey(), NumberConstant(), v8::internal::interpreter::InterpreterAssembler::OnStackReplacement(), v8::internal::CodeStubAssembler::PositiveSmiToUint32(), v8::internal::CodeStubAssembler::PrintToStream(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::RegExpBuiltinsAssembler::RegExpReplaceGlobalSimpleString(), v8::internal::RegExpBuiltinsAssembler::RegistersForCaptureCount(), v8::internal::ArrayIncludesIndexofAssembler::ReturnIfEmpty(), v8::internal::CodeStubAssembler::SelectSmiConstant(), v8::internal::TypedArrayBuiltinsAssembler::SetJSTypedArrayOffHeapDataPtr(), v8::internal::TypedArrayBuiltinsAssembler::SetupTypedArrayEmbedderFields(), v8::internal::ShadowRealmBuiltinsAssembler::ShadowRealmThrow(), SmiConstant(), v8::internal::StringBuiltinsAssembler::SmiIsNegative(), v8::internal::CodeStubAssembler::SmiMul(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::RegExpBuiltinsAssembler::SmiZero(), v8::internal::AccessorAssembler::StoreIC(), v8::internal::CollectionsBuiltinsAssembler::StoreOrderedHashTableNewEntry(), v8::internal::KeyedStoreGenericAssembler::StoreProperty(), v8::internal::IteratorBuiltinsAssembler::StringListFromIterable(), v8::internal::StringBuiltinsAssembler::StringToArray(), v8::internal::CollectionsBuiltinsAssembler::TableHasKey(), v8::internal::CodeStubAssembler::TaggedToWord32OrBigIntImpl(), v8::internal::CodeStubAssembler::ThrowRangeError(), v8::internal::CodeStubAssembler::ThrowTypeError(), v8::internal::CodeStubAssembler::ToLength_Inline(), v8::internal::CodeStubAssembler::ToNumberOrNumeric(), v8::internal::interpreter::InterpreterAssembler::ToNumberOrNumeric(), v8::internal::CodeStubAssembler::ToUint32(), v8::internal::CodeStubAssembler::TrySmiDiv(), v8::internal::AccessorAssembler::UpdateMayHaveInterestingProperty(), and v8::internal::PromiseBuiltinsAssembler::ZeroOutEmbedderOffsets().
StackSlotPtr()
TNode< RawPtrT > v8::internal::compiler::CodeAssembler::StackSlotPtr (int size, int alignment)
Definition at line 729 of file code-assembler.cc.
                                                                  {
  return UncheckedCast<RawPtrT>(raw_assembler()->StackSlot(size, alignment));
}
References raw_assembler(), and size().
state()
CodeAssemblerState* v8::internal::compiler::CodeAssembler::state () [inline]
Definition at line 1581 of file code-assembler.h.
{ return state_; }
Referenced by v8::internal::BaseCollectionsAssembler::AddConstructorEntriesFromIterable(), v8::internal::BaseCollectionsAssembler::AllocateJSCollectionSlow(), v8::internal::RegExpBuiltinsAssembler::BranchIfFastRegExp(), builtin(), v8::internal::CodeStubAssembler::FastCloneJSObject(), v8::internal::IteratorBuiltinsAssembler::FastIterableToList(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::BaseCollectionsAssembler::GotoIfInitialAddFunctionModified(), v8::internal::CodeStubAssembler::HandleBreakOnNode(), v8::internal::IteratorBuiltinsAssembler::IterableToFixedArray(), v8::internal::IteratorBuiltinsAssembler::IterableToList(), v8::internal::StringBuiltinsAssembler::MaybeCallFunctionAtSymbol(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::RegExpBuiltinsAssembler::RegExpReplaceGlobalSimpleString(), v8::internal::compiler::ScopedExceptionHandler::ScopedExceptionHandler(), v8::internal::CodeStubAssembler::StringCharCodeAt(), v8::internal::IteratorBuiltinsAssembler::StringListFromIterable(), v8::internal::StringBuiltinsAssembler::StringToArray(), v8::internal::StringBuiltinsAssembler::SubString(), v8::internal::CodeStubAssembler::TaggedToDirectString(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), and v8::internal::compiler::ScopedExceptionHandler::~ScopedExceptionHandler().
StaticAssert()
void v8::internal::compiler::CodeAssembler::StaticAssert (TNode< BoolT > value, const char * source = `unknown position`)
Definition at line 666 of file code-assembler.cc.
                                                                       {
  raw_assembler()->StaticAssert(value, source);
}
References raw_assembler(), v8::internal::compiler::RawMachineAssembler::StaticAssert(), and v8::internal::value.
Store() [1/2]
void v8::internal::compiler::CodeAssembler::Store (Node * base, Node * offset, Node * value)
Definition at line 1019 of file code-assembler.cc.
                                                               {
  // Please use OptimizedStoreMap(base, value) instead.
  DCHECK(!raw_assembler()->IsMapOffsetConstantMinusTag(offset));
  raw_assembler()->Store(MachineRepresentation::kTagged, base, offset, value,
                         kFullWriteBarrier);
}
References v8::internal::DCHECK(), v8::internal::compiler::kFullWriteBarrier, v8::internal::kTagged, raw_assembler(), v8::internal::compiler::RawMachineAssembler::Store(), and v8::internal::value.
Store() [2/2]
void v8::internal::compiler::CodeAssembler::Store (Node * base, Node * value)
Definition at line 949 of file code-assembler.cc.
                                                 {
  raw_assembler()->Store(MachineRepresentation::kTagged, base, value,
                         kFullWriteBarrier);
}
References v8::internal::compiler::kFullWriteBarrier, v8::internal::kTagged, raw_assembler(), v8::internal::compiler::RawMachineAssembler::Store(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::CopyElements(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::CodeStubAssembler::CopyPropertyArrayValues(), v8::internal::CollectionsBuiltinsAssembler::MapIteratorToList(), v8::internal::CodeStubAssembler::MoveElements(), v8::internal::CollectionsBuiltinsAssembler::SetOrSetIteratorToList(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), v8::internal::CodeStubAssembler::StoreFeedbackVectorSlot(), v8::internal::CodeStubAssembler::StoreFixedArrayOrPropertyArrayElement(), v8::internal::CodeStubAssembler::StoreObjectField(), and v8::internal::CodeStubAssembler::StoreSharedObjectField().
StoreEphemeronKey()
void v8::internal::compiler::CodeAssembler::StoreEphemeronKey (Node * base, Node * offset, Node * value)
Definition at line 1026 of file code-assembler.cc.
                                                                           {
  DCHECK(!raw_assembler()->IsMapOffsetConstantMinusTag(offset));
  raw_assembler()->Store(MachineRepresentation::kTagged, base, offset, value,
                         kEphemeronKeyWriteBarrier);
}
References v8::internal::DCHECK(), v8::internal::compiler::kEphemeronKeyWriteBarrier, v8::internal::kTagged, raw_assembler(), v8::internal::compiler::RawMachineAssembler::Store(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::StoreFixedArrayOrPropertyArrayElement().
StoreFullTaggedNoWriteBarrier() [1/2]
void v8::internal::compiler::CodeAssembler::StoreFullTaggedNoWriteBarrier (TNode< RawPtrT > base, TNode< IntPtrT > offset, TNode< Object > tagged_value)
Definition at line 1067 of file code-assembler.cc.
                                                                              {
  // Please use OptimizedStoreMap(base, tagged_value) instead.
  DCHECK(!raw_assembler()->IsMapOffsetConstantMinusTag(offset));
  StoreNoWriteBarrier(MachineType::PointerRepresentation(), base, offset,
                      BitcastTaggedToWord(tagged_value));
}
References BitcastTaggedToWord(), v8::internal::DCHECK(), v8::internal::MachineType::PointerRepresentation(), raw_assembler(), and StoreNoWriteBarrier().
StoreFullTaggedNoWriteBarrier() [2/2]
void v8::internal::compiler::CodeAssembler::StoreFullTaggedNoWriteBarrier (TNode< RawPtrT > base, TNode< Object > tagged_value)
Definition at line 1061 of file code-assembler.cc.
                                                                              {
  StoreNoWriteBarrier(MachineType::PointerRepresentation(), base,
                      BitcastTaggedToWord(tagged_value));
}
References BitcastTaggedToWord(), v8::internal::MachineType::PointerRepresentation(), and StoreNoWriteBarrier().
Referenced by v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), v8::internal::interpreter::InterpreterAssembler::SaveBytecodeOffset(), v8::internal::CodeStubAssembler::SetContinuationPreservedEmbedderData(), v8::internal::MicrotaskQueueBuiltinsAssembler::SetCurrentContext(), v8::internal::CodeStubAssembler::SetPendingMessage(), v8::internal::CodeStubArguments::SetReceiver(), v8::internal::interpreter::InterpreterAssembler::StoreRegister(), v8::internal::interpreter::InterpreterAssembler::StoreRegisterForShortStar(), and StoreRoot().
StoreNoWriteBarrier() [1/2]
void v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier (MachineRepresentation rep, Node * base, Node * offset, Node * value)
Definition at line 1039 of file code-assembler.cc.
                                                                   {
  // Please use OptimizedStoreMap(base, value) instead.
  DCHECK(!raw_assembler()->IsMapOffsetConstantMinusTag(offset));
  raw_assembler()->Store(
      rep, base, offset, value,
      CanBeTaggedPointer(rep) ? kAssertNoWriteBarrier : kNoWriteBarrier);
}
References v8::internal::CanBeTaggedPointer(), v8::internal::DCHECK(), v8::internal::compiler::kAssertNoWriteBarrier, v8::internal::compiler::kNoWriteBarrier, raw_assembler(), v8::internal::compiler::RawMachineAssembler::Store(), and v8::internal::value.
StoreNoWriteBarrier() [2/2]
void v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier (MachineRepresentation rep, Node * base, Node * value)
Definition at line 1032 of file code-assembler.cc.
                                                     {
  raw_assembler()->Store(
      rep, base, value,
      CanBeTaggedPointer(rep) ? kAssertNoWriteBarrier : kNoWriteBarrier);
}
References v8::internal::CanBeTaggedPointer(), v8::internal::compiler::kAssertNoWriteBarrier, v8::internal::compiler::kNoWriteBarrier, raw_assembler(), v8::internal::compiler::RawMachineAssembler::Store(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::AllocateRaw(), v8::internal::CodeStubAssembler::AllocateSeqOneByteString(), v8::internal::CodeStubAssembler::AllocateSeqTwoByteString(), v8::internal::CodeStubAssembler::CopyElements(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::CodeStubAssembler::CopyPropertyArrayValues(), v8::internal::StringBuiltinsAssembler::CopyStringCharacters(), v8::internal::CodeStubAssembler::DecrementCounter(), v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), v8::internal::CodeStubAssembler::ExtractFixedDoubleArrayFillingHoles(), v8::internal::CodeStubAssembler::FillFixedArrayWithValue(), v8::internal::CodeStubAssembler::FillPropertyArrayWithUndefined(), v8::internal::RegExpBuiltinsAssembler::FreeRegExpResultVector(), v8::internal::CodeStubAssembler::IncrementCounter(), v8::internal::MicrotaskQueueBuiltinsAssembler::IncrementFinishedMicrotaskCount(), v8::internal::RegExpBuiltinsAssembler::InitializeMatchInfoFromRegisters(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::MicrotaskQueueBuiltinsAssembler::RewindEnteredContext(), v8::internal::interpreter::InterpreterAssembler::SaveBytecodeOffset(), v8::internal::WriteBarrierCodeStubAssembler::SetBitInCell(), v8::internal::CodeStubAssembler::SetCounter(), v8::internal::MicrotaskQueueBuiltinsAssembler::SetMicrotaskQueueSize(), v8::internal::MicrotaskQueueBuiltinsAssembler::SetMicrotaskQueueStart(), v8::internal::CodeStubAssembler::StoreContextElementNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreDoubleHole(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), v8::internal::CodeStubAssembler::StoreExternalPointerToObject(), v8::internal::CodeStubAssembler::StoreFeedbackVectorSlot(), v8::internal::CodeStubAssembler::StoreFixedArrayOrPropertyArrayElement(), v8::internal::CodeStubAssembler::StoreFixedDoubleArrayElement(), StoreFullTaggedNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreObjectByteNoWriteBarrier(), v8::internal::DataViewBuiltinsAssembler::StoreWord8(), v8::internal::CodeStubAssembler::StringFromSingleCharCode(), v8::internal::StringBuiltinsAssembler::StringFromSingleUTF16EncodedCodePoint(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), and v8::internal::interpreter::InterpreterAssembler::TraceBytecodeDispatch().
StoreRoot()
void v8::internal::compiler::CodeAssembler::StoreRoot (RootIndex root_index, TNode< Object > value)
Definition at line 1157 of file code-assembler.cc.
                                                                       {
  DCHECK(!RootsTable::IsImmortalImmovable(root_index));
  TNode<ExternalReference> isolate_root =
      ExternalConstant(ExternalReference::isolate_root(isolate()));
  int offset = IsolateData::root_slot_offset(root_index);
  StoreFullTaggedNoWriteBarrier(isolate_root, IntPtrConstant(offset), value);
}
References v8::internal::DCHECK(), ExternalConstant(), IntPtrConstant(), v8::internal::RootsTable::IsImmortalImmovable(), isolate(), v8::internal::IsolateData::root_slot_offset(), StoreFullTaggedNoWriteBarrier(), and v8::internal::value.
Referenced by v8::internal::MicrotaskQueueBuiltinsAssembler::RunSingleMicrotask().
StoreToObject()
void v8::internal::compiler::CodeAssembler::StoreToObject (MachineRepresentation rep, TNode< Object > object, TNode< IntPtrT > offset, Node * value, StoreToObjectWriteBarrier write_barrier)
Definition at line 954 of file code-assembler.cc.
                                                                           {
  WriteBarrierKind write_barrier_kind;
  switch (write_barrier) {
    case StoreToObjectWriteBarrier::kFull:
      write_barrier_kind = WriteBarrierKind::kFullWriteBarrier;
      break;
    case StoreToObjectWriteBarrier::kMap:
      write_barrier_kind = WriteBarrierKind::kMapWriteBarrier;
      break;
    case StoreToObjectWriteBarrier::kNone:
      if (CanBeTaggedPointer(rep)) {
        write_barrier_kind = WriteBarrierKind::kAssertNoWriteBarrier;
      } else {
        write_barrier_kind = WriteBarrierKind::kNoWriteBarrier;
      }
      break;
  }
  raw_assembler()->StoreToObject(rep, object, offset, value,
                                 write_barrier_kind);
}
References v8::internal::CanBeTaggedPointer(), v8::internal::compiler::kAssertNoWriteBarrier, v8::internal::kFull, v8::internal::compiler::kFullWriteBarrier, v8::internal::kMap, v8::internal::compiler::kMapWriteBarrier, v8::internal::kNone, v8::internal::compiler::kNoWriteBarrier, raw_assembler(), v8::internal::compiler::RawMachineAssembler::StoreToObject(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::CodeStubAssembler::StoreSwissNameDictionaryKeyAndValue(), v8::internal::CodeStubAssembler::StoreSwissNameDictionaryPropertyDetails(), v8::internal::CodeStubAssembler::StoreValueByKeyIndex(), and v8::internal::CodeStubAssembler::SwissNameDictionarySetCtrl().
StringConstant()
TNode< String > v8::internal::compiler::CodeAssembler::StringConstant (const char * str)
Definition at line 384 of file code-assembler.cc.
                                                           {
  Handle<String> internalized_string =
      factory()->InternalizeString(base::OneByteVector(str));
  CanonicalizeEmbeddedBuiltinsConstantIfNeeded(internalized_string);
  return UncheckedCast<String>(HeapConstantNoHole(internalized_string));
}
References factory(), HeapConstantNoHole(), v8::internal::Factory::InternalizeString(), and v8::base::OneByteVector().
Referenced by v8::internal::CodeStubAssembler::FailAssert(), v8::internal::CodeStubAssembler::PrintToStream(), v8::internal::ObjectBuiltinsAssembler::ReturnToStringFormat(), v8::internal::CodeStubAssembler::ThrowIfNotInstanceType(), v8::internal::CodeStubAssembler::ThrowIfNotJSReceiver(), and v8::internal::CodeStubAssembler::ThrowTypeError().
Switch()
void v8::internal::compiler::CodeAssembler::Switch (Node * index, Label * default_label, const int32_t * case_values, Label ** case_labels, size_t case_count)
Definition at line 1647 of file code-assembler.cc.
                                              {
  RawMachineLabel** labels =
      zone()->AllocateArray<RawMachineLabel*>(case_count);
  for (size_t i = 0; i < case_count; ++i) {
    labels[i] = case_labels[i]->label_;
    case_labels[i]->MergeVariables();
  }
  default_label->MergeVariables();
  return raw_assembler()->Switch(index, default_label->label_, case_values,
                                 labels, case_count);
}
References v8::internal::Zone::AllocateArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::compiler::CodeAssemblerLabel::label_, v8::internal::compiler::CodeAssemblerLabel::MergeVariables(), raw_assembler(), v8::internal::compiler::RawMachineAssembler::Switch(), and zone().
Referenced by v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::HandlerBuiltinsAssembler::DispatchByElementsKind(), v8::internal::HandlerBuiltinsAssembler::DispatchForElementsKindTransition(), v8::internal::TypedArrayBuiltinsAssembler::DispatchTypedArrayByElementsKind(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::ArrayBuiltinsAssembler::GenerateIteratingTypedArrayBuiltinBody(), v8::internal::CodeStubAssembler::GetSharedFunctionInfoCode(), v8::internal::AccessorAssembler::HandleStoreICSmiHandlerCase(), v8::internal::CodeStubAssembler::LoadFixedArrayBaseElementAsTagged(), v8::internal::CodeStubAssembler::LoadFixedTypedArrayElementAsTagged(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::MicrotaskQueueBuiltinsAssembler::RunSingleMicrotask(), and v8::internal::ToDirectStringAssembler::TryToDirect().
SwitchFromTheCentralStack()
void v8::internal::compiler::CodeAssembler::SwitchFromTheCentralStack (TNode< RawPtrT > old_sp)
SwitchToTheCentralStack()
TNode<RawPtrT> v8::internal::compiler::CodeAssembler::SwitchToTheCentralStack ()
SwitchToTheCentralStackIfNeeded()
TNode<RawPtrT> v8::internal::compiler::CodeAssembler::SwitchToTheCentralStackIfNeeded ()
TaggedIndexConstant()
TNode< TaggedIndex > v8::internal::compiler::CodeAssembler::TaggedIndexConstant (intptr_t value)
Definition at line 317 of file code-assembler.cc.
                                                                    {
  DCHECK(TaggedIndex::IsValid(value));
  return UncheckedCast<TaggedIndex>(jsgraph()->TaggedIndexConstant(value));
}
References v8::internal::DCHECK(), v8::internal::TaggedIndex::IsValid(), jsgraph(), and v8::internal::value.
Referenced by v8::internal::AccessorAssembler::GenerateLoadIC_NoFeedback(), v8::internal::KeyedStoreGenericAssembler::KeyedStoreGeneric(), v8::internal::KeyedStoreGenericAssembler::StoreIC_NoFeedback(), and v8::internal::KeyedStoreGenericAssembler::StoreProperty().
TailCallBuiltin()
template<class... TArgs>
void v8::internal::compiler::CodeAssembler::TailCallBuiltin (Builtin id, TNode< Object > context, TArgs... args) [inline]
Definition at line 1379 of file code-assembler.h.
                                                                         {
    DCHECK_WITH_MSG(!Builtins::HasJSLinkage(id),
                    "Use TailCallJSBuiltin instead");
#if V8_ENABLE_WEBASSEMBLY
    // Tail calling from a wasm builtin to a non-wasm builtin is not supported
    // because of stack switching. Use a call instead so that we switch to the
    // central stack and back if needed.
    DCHECK(!wasm::BuiltinLookup::IsWasmBuiltinId(builtin()) ||
           wasm::BuiltinLookup::IsWasmBuiltinId(id));
#endif
    Callable callable = Builtins::CallableFor(isolate(), id);
    TNode<Code> target = HeapConstantNoHole(callable.code());
    TailCallStub(callable.descriptor(), target, context, args...);
  }
References v8::base::args, v8::internal::Builtins::CallableFor(), v8::internal::Callable::code(), v8::internal::DCHECK(), DCHECK_WITH_MSG, v8::internal::Callable::descriptor(), v8::internal::Builtins::HasJSLinkage(), v8::internal::compiler::HeapConstantNoHole(), and v8::internal::wasm::BuiltinLookup::IsWasmBuiltinId().
Referenced by v8::internal::CallOrConstructBuiltinsAssembler::BuildConstruct(), v8::internal::CallOrConstructBuiltinsAssembler::BuildConstructForwardAllArgs(), v8::internal::CallOrConstructBuiltinsAssembler::CallFunctionTemplate(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructDoubleVarargs(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithArrayLike(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithSpread(), v8::internal::CallOrConstructBuiltinsAssembler::CallReceiver(), v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::CppBuiltinsAdaptorAssembler::GenerateAdaptor(), v8::internal::AccessorAssembler::GenerateCloneObjectIC(), v8::internal::AccessorAssembler::GenerateCloneObjectICBaseline(), v8::internal::AccessorAssembler::GenerateDefineKeyedOwnICBaseline(), v8::internal::AccessorAssembler::GenerateDefineKeyedOwnICTrampoline(), v8::internal::AccessorAssembler::GenerateDefineNamedOwnICBaseline(), v8::internal::AccessorAssembler::GenerateDefineNamedOwnICTrampoline(), v8::internal::AccessorAssembler::GenerateEnumeratedKeyedLoadICBaseline(), v8::internal::AccessorAssembler::GenerateKeyedHasICBaseline(), v8::internal::AccessorAssembler::GenerateKeyedLoadICBaseline(), v8::internal::AccessorAssembler::GenerateKeyedLoadICTrampoline(), v8::internal::AccessorAssembler::GenerateKeyedLoadICTrampoline_Megamorphic(), v8::internal::AccessorAssembler::GenerateKeyedStoreICBaseline(), v8::internal::AccessorAssembler::GenerateKeyedStoreICTrampoline(), v8::internal::AccessorAssembler::GenerateKeyedStoreICTrampoline_Megamorphic(), v8::internal::AccessorAssembler::GenerateLoadGlobalICBaseline(), v8::internal::AccessorAssembler::GenerateLoadGlobalICTrampoline(), v8::internal::AccessorAssembler::GenerateLoadICBaseline(), v8::internal::AccessorAssembler::GenerateLoadICTrampoline(), v8::internal::AccessorAssembler::GenerateLoadICTrampoline_Megamorphic(), v8::internal::AccessorAssembler::GenerateLoadSuperICBaseline(), v8::internal::AccessorAssembler::GenerateStoreGlobalICBaseline(), v8::internal::AccessorAssembler::GenerateStoreGlobalICTrampoline(), v8::internal::AccessorAssembler::GenerateStoreICBaseline(), v8::internal::AccessorAssembler::GenerateStoreICTrampoline(), v8::internal::AccessorAssembler::GenerateStoreICTrampoline_Megamorphic(), v8::internal::AccessorAssembler::GenerateStoreInArrayLiteralICBaseline(), v8::internal::AccessorAssembler::GenericElementLoad(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreToProxy(), v8::internal::AccessorAssembler::KeyedLoadIC(), v8::internal::AccessorAssembler::KeyedStoreIC(), v8::internal::AccessorAssembler::LoadGlobalIC_NoFeedback(), v8::internal::AccessorAssembler::LookupGlobalIC(), v8::internal::interpreter::InterpreterAssembler::OnStackReplacement(), v8::internal::ExitPoint::ReturnCallBuiltin(), v8::internal::AccessorAssembler::StoreIC(), and v8::internal::AccessorAssembler::StoreInArrayLiteralIC().
TailCallBuiltinThenBytecodeDispatch()
template<class... TArgs>
void v8::internal::compiler::CodeAssembler::TailCallBuiltinThenBytecodeDispatch (Builtin builtin, Node * context, TArgs... args) [inline]
Definition at line 1424 of file code-assembler.h.
                                                          {
    Callable callable = Builtins::CallableFor(isolate(), builtin);
    TNode<Code> target = HeapConstantNoHole(callable.code());
    TailCallStubThenBytecodeDispatchImpl(callable.descriptor(), target, context,
                                         {args...});
  }
References v8::internal::Builtins::CallableFor(), v8::internal::Callable::code(), v8::internal::Callable::descriptor(), and v8::internal::compiler::HeapConstantNoHole().
Referenced by v8::internal::interpreter::InterpreterAssembler::CallJSAndDispatch(), and v8::internal::interpreter::InterpreterAssembler::CallJSWithSpreadAndDispatch().
TailCallBytecodeDispatch()
template<class... TArgs>
template V8_EXPORT_PRIVATE void v8::internal::compiler::CodeAssembler::TailCallBytecodeDispatch (const CallInterfaceDescriptor & descriptor, TNode< RawPtrT > target, TArgs... args)
Definition at line 1488 of file code-assembler.cc.
                   {
  DCHECK_EQ(descriptor.GetParameterCount(), sizeof...(args));
  auto call_descriptor = Linkage::GetBytecodeDispatchCallDescriptor(
      zone(), descriptor, descriptor.GetStackParameterCount());
  Node* nodes[] = {target, args...};
  CHECK_EQ(descriptor.GetParameterCount() + 1, arraysize(nodes));
  raw_assembler()->TailCallN(call_descriptor, arraysize(nodes), nodes);
}
References v8::base::args, arraysize, CHECK_EQ, DCHECK_EQ, v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), v8::internal::CallInterfaceDescriptor::GetParameterCount(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), raw_assembler(), v8::internal::compiler::RawMachineAssembler::TailCallN(), and zone().
Referenced by v8::internal::interpreter::InterpreterAssembler::DispatchToBytecodeHandlerEntry().
TailCallJSBuiltin()
void v8::internal::compiler::CodeAssembler::TailCallJSBuiltin (Builtin id, TNode< Object > context, TNode< Object > function, TNode< Object > new_target, TNode< Int32T > arg_count, TNode< JSDispatchHandleT > dispatch_handle) [inline]
Definition at line 1461 of file code-assembler.h.
                                                                   {
    DCHECK(Builtins::HasJSLinkage(id));
#if V8_ENABLE_WEBASSEMBLY
    // Tail calling from a wasm builtin to a JS builtin is not supported because
    // of stack switching. Use a call instead so that we switch to the central
    // stack and back if needed.
    DCHECK(!wasm::BuiltinLookup::IsWasmBuiltinId(builtin()) ||
           wasm::BuiltinLookup::IsWasmBuiltinId(id));
#endif
    Callable callable = Builtins::CallableFor(isolate(), id);
    TNode<Code> target = HeapConstantNoHole(callable.code());
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
    TailCallStub(callable.descriptor(), target, context, function, new_target,
                 arg_count, dispatch_handle);
#else
    TailCallStub(callable.descriptor(), target, context, function, new_target,
                 arg_count);
#endif
  }
References v8::internal::Builtins::CallableFor(), v8::internal::Callable::code(), v8::internal::DCHECK(), v8::internal::Callable::descriptor(), v8::internal::Builtins::HasJSLinkage(), v8::internal::compiler::HeapConstantNoHole(), and v8::internal::wasm::BuiltinLookup::IsWasmBuiltinId().
TailCallJSCode()
void v8::internal::compiler::CodeAssembler::TailCallJSCode (TNode< Code > code, TNode< Context > context, TNode< JSFunction > function, TNode< Object > new_target, TNode< Int32T > arg_count, TNode< JSDispatchHandleT > dispatch_handle)
Definition at line 1507 of file code-assembler.cc.
                                                                             {
  JSTrampolineDescriptor descriptor;
  auto call_descriptor = Linkage::GetStubCallDescriptor(
      zone(), descriptor, descriptor.GetStackParameterCount(),
      CallDescriptor::kFixedTargetRegister, Operator::kNoProperties,
      StubCallMode::kCallCodeObject);
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
  Node* nodes[] = {code, function, new_target,
                   arg_count, dispatch_handle, context};
#else
  Node* nodes[] = {code, function, new_target, arg_count, context};
#endif
  // + 2 for code and context.
  CHECK_EQ(descriptor.GetParameterCount() + 2, arraysize(nodes));
  raw_assembler()->TailCallN(call_descriptor, arraysize(nodes), nodes);
}
References arraysize, CHECK_EQ, code, v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetParameterCount(), v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::kCallCodeObject, v8::internal::compiler::CallDescriptor::kFixedTargetRegister, v8::internal::compiler::Operator::kNoProperties, raw_assembler(), v8::internal::compiler::RawMachineAssembler::TailCallN(), and zone().
Referenced by v8::internal::LazyBuiltinsAssembler::GenerateTailCallToJSCode(), and v8::internal::LazyBuiltinsAssembler::GenerateTailCallToJSFunction().
TailCallRuntime() [1/2]
template<class... TArgs>
void v8::internal::compiler::CodeAssembler::TailCallRuntime (Runtime::FunctionId function, TNode< Int32T > arity, TNode< Object > context, TArgs... args) [inline]
Definition at line 1324 of file code-assembler.h.
                                                             {
    return TailCallRuntimeImpl(function, arity, context,
                               {implicit_cast<TNode<Object>>(args)...});
  }
References v8::base::args.
TailCallRuntime() [2/2]
template<class... TArgs>
void v8::internal::compiler::CodeAssembler::TailCallRuntime (Runtime::FunctionId function, TNode< Object > context, TArgs... args) [inline]
Definition at line 1315 of file code-assembler.h.
                                      {
    int argc = static_cast<int>(sizeof...(args));
    TNode<Int32T> arity = Int32Constant(argc);
    return TailCallRuntimeImpl(function, arity, context,
                               {implicit_cast<TNode<Object>>(args)...});
  }
References v8::base::args.
Referenced by v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::HandlerBuiltinsAssembler::Generate_ElementsTransitionAndStore(), v8::internal::HandlerBuiltinsAssembler::Generate_KeyedStoreIC_SloppyArguments(), v8::internal::HandlerBuiltinsAssembler::Generate_StoreFastElementIC(), v8::internal::ArrayBuiltinsAssembler::GenerateArrayNArgumentsConstructor(), v8::internal::ArrayBuiltinsAssembler::GenerateConstructor(), v8::internal::StringBuiltinsAssembler::GenerateStringEqual(), v8::internal::StringBuiltinsAssembler::GenerateStringRelationalComparison(), v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICNativeDataProperty(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::HandleStoreToProxy(), v8::internal::AccessorAssembler::KeyedLoadIC(), v8::internal::AccessorAssembler::KeyedLoadICGeneric(), v8::internal::AccessorAssembler::KeyedLoadICPolymorphicName(), v8::internal::KeyedStoreGenericAssembler::KeyedStoreGeneric(), v8::internal::AccessorAssembler::KeyedStoreIC(), v8::internal::AccessorAssembler::LoadIC_NoFeedback(), v8::internal::AccessorAssembler::LoadSuperIC_NoFeedback(), v8::internal::AccessorAssembler::LookupContext(), v8::internal::AccessorAssembler::LookupGlobalIC(), v8::internal::ExitPoint::ReturnCallRuntime(), v8::internal::AccessorAssembler::StoreGlobalIC(), v8::internal::AccessorAssembler::StoreIC(), v8::internal::KeyedStoreGenericAssembler::StoreIC_NoFeedback(), v8::internal::AccessorAssembler::StoreInArrayLiteralIC(), and v8::internal::CodeStubAssembler::TailCallRuntimeNewArray().
TailCallRuntimeImpl()
void v8::internal::compiler::CodeAssembler::TailCallRuntimeImpl (Runtime::FunctionId function, TNode< Int32T > arity, TNode< Object > context, std::initializer_list< TNode< Object >> args) [private]
Definition at line 1323 of file code-assembler.cc.
                                             {
  int result_size = Runtime::FunctionForId(function)->result_size;
#if V8_ENABLE_WEBASSEMBLY
  bool switch_to_the_central_stack =
      state_->kind_ == CodeKind::WASM_FUNCTION ||
      state_->kind_ == CodeKind::WASM_TO_JS_FUNCTION ||
      state_->kind_ == CodeKind::JS_TO_WASM_FUNCTION ||
      state_->builtin_ == Builtin::kJSToWasmWrapper ||
      state_->builtin_ == Builtin::kJSToWasmHandleReturns ||
      state_->builtin_ == Builtin::kWasmToJsWrapperCSA ||
      wasm::BuiltinLookup::IsWasmBuiltinId(state_->builtin_);
#else
  bool switch_to_the_central_stack = false;
#endif
  Builtin centry =
      Builtins::RuntimeCEntry(result_size, switch_to_the_central_stack);
  TNode<Code> centry_code =
      HeapConstantNoHole(isolate()->builtins()->code_handle(centry));
  constexpr size_t kMaxNumArgs = 6;
  DCHECK_GE(kMaxNumArgs, args.size());
  int argc = static_cast<int>(args.size());
  auto call_descriptor = Linkage::GetRuntimeCallDescriptor(
      zone(), function, argc, Operator::kNoProperties,
      CallDescriptor::kNoFlags);
  TNode<ExternalReference> ref =
      ExternalConstant(ExternalReference::Create(function));
  NodeArray<kMaxNumArgs + 4> inputs;
  inputs.Add(centry_code);
  for (const auto& arg : args) inputs.Add(arg);
  inputs.Add(ref);
  inputs.Add(arity);
  inputs.Add(context);
  raw_assembler()->TailCallN(call_descriptor, inputs.size(), inputs.data());
}
References v8::base::args, v8::internal::compiler::CodeAssemblerState::builtin_, v8::internal::ExternalReference::Create(), DCHECK_GE, ExternalConstant(), v8::internal::Runtime::FunctionForId(), v8::internal::compiler::Linkage::GetRuntimeCallDescriptor(), HeapConstantNoHole(), isolate(), v8::internal::wasm::BuiltinLookup::IsWasmBuiltinId(), v8::internal::compiler::CodeAssemblerState::kind_, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, raw_assembler(), v8::internal::Runtime::Function::result_size, v8::internal::Builtins::RuntimeCEntry(), state_, v8::internal::wasm::switch_to_the_central_stack(), v8::internal::compiler::RawMachineAssembler::TailCallN(), and zone().
TailCallStub()
template<class... TArgs>
void v8::internal::compiler::CodeAssembler::TailCallStub (const CallInterfaceDescriptor & descriptor, TNode< Code > target, TNode< Object > context, TArgs... args) [inline]
Definition at line 1414 of file code-assembler.h.
                                                                              {
    TailCallStubImpl(descriptor, target, context, {args...});
  }
References v8::base::args.
Referenced by v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::ExitPoint::ReturnCallStub(), v8::internal::AccessorAssembler::StoreInArrayLiteralIC(), and v8::internal::ArrayBuiltinsAssembler::TailCallArrayConstructorStub().
TailCallStubImpl()
void v8::internal::compiler::CodeAssembler::TailCallStubImpl (const CallInterfaceDescriptor & descriptor, TNode< Code > target, TNode< Object > context, std::initializer_list< Node * > args) [private]
Definition at line 1391 of file code-assembler.cc.
                                                                      {
  constexpr size_t kMaxNumArgs = 11;
  DCHECK_GE(kMaxNumArgs, args.size());
  DCHECK(IsValidArgumentCountFor(descriptor, args.size()));
  auto call_descriptor = Linkage::GetStubCallDescriptor(
      zone(), descriptor, descriptor.GetStackParameterCount(),
      CallDescriptor::kNoFlags, Operator::kNoProperties);
  NodeArray<kMaxNumArgs + 2> inputs;
  inputs.Add(target);
  for (auto arg : args) inputs.Add(arg);
  if (descriptor.HasContextParameter()) {
    inputs.Add(context);
  }
  raw_assembler()->TailCallN(call_descriptor, inputs.size(), inputs.data());
}
References v8::base::args, v8::internal::DCHECK(), DCHECK_GE, v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::CallInterfaceDescriptor::HasContextParameter(), v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, raw_assembler(), v8::internal::compiler::RawMachineAssembler::TailCallN(), and zone().
TailCallStubThenBytecodeDispatchImpl()
void v8::internal::compiler::CodeAssembler::TailCallStubThenBytecodeDispatchImpl (const CallInterfaceDescriptor & descriptor, Node * target, Node * context, std::initializer_list< Node * > args) [private]
Definition at line 1464 of file code-assembler.cc.
                                     {
  constexpr size_t kMaxNumArgs = 6;
  DCHECK_GE(kMaxNumArgs, args.size());
  DCHECK(IsValidArgumentCountFor(descriptor, args.size()));
  int argc = static_cast<int>(args.size());
  // Extra arguments not mentioned in the descriptor are passed on the stack.
  int stack_parameter_count = argc - descriptor.GetRegisterParameterCount();
  DCHECK_LE(descriptor.GetStackParameterCount(), stack_parameter_count);
  auto call_descriptor = Linkage::GetStubCallDescriptor(
      zone(), descriptor, stack_parameter_count, CallDescriptor::kNoFlags,
      Operator::kNoProperties);
  NodeArray<kMaxNumArgs + 2> inputs;
  inputs.Add(target);
  for (auto arg : args) inputs.Add(arg);
  inputs.Add(context);
  raw_assembler()->TailCallN(call_descriptor, inputs.size(), inputs.data());
}
References v8::base::args, v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, v8::internal::CallInterfaceDescriptor::GetRegisterParameterCount(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, raw_assembler(), v8::internal::compiler::RawMachineAssembler::TailCallN(), and zone().
TruncateFloat32ToInt32()
TNode< Int32T > v8::internal::compiler::CodeAssembler::TruncateFloat32ToInt32 (TNode< Float32T > value)
Definition at line 839 of file code-assembler.cc.
                                                                         {
  return UncheckedCast<Int32T>(raw_assembler()->TruncateFloat32ToInt32(
      value, TruncateKind::kSetOverflowToMin));
}
References v8::internal::compiler::kSetOverflowToMin, raw_assembler(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::TryFloat32ToSmi().
TruncateFloat64ToInt64()
TNode< Int64T > v8::internal::compiler::CodeAssembler::TruncateFloat64ToInt64 (TNode< Float64T > value)
Definition at line 843 of file code-assembler.cc.
                                                                         {
  return UncheckedCast<Int64T>(raw_assembler()->TruncateFloat64ToInt64(
      value, TruncateKind::kSetOverflowToMin));
}
References v8::internal::compiler::kSetOverflowToMin, raw_assembler(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::TryFloat64ToAdditiveSafeInteger().
TryToInt32Constant()
bool v8::internal::compiler::CodeAssembler::TryToInt32Constant (TNode< IntegralT > node, int32_t * out_value)
Definition at line 419 of file code-assembler.cc.
                                                           {
  {
    Int64Matcher m(node);
    if (m.HasResolvedValue() &&
        m.IsInRange(std::numeric_limits<int32_t>::min(),
                    std::numeric_limits<int32_t>::max())) {
      *out_value = static_cast<int32_t>(m.ResolvedValue());
      return true;
    }
  }
  {
    Int32Matcher m(node);
    if (m.HasResolvedValue()) {
      *out_value = m.ResolvedValue();
      return true;
    }
  }
  return false;
}
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::IntMatcher< T, kOpcode >::IsInRange(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
Referenced by v8::internal::CodeStubAssembler::AllocateUninitializedJSArrayWithElements(), Branch(), v8::internal::StringBuiltinsAssembler::CopyStringCharacters(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::CodeStubAssembler::StoreObjectField(), v8::internal::CodeStubAssembler::StoreSharedObjectField(), and v8::internal::CodeStubAssembler::TryGetIntPtrOrSmiConstantValue().
TryToInt64Constant()
bool v8::internal::compiler::CodeAssembler::TryToInt64Constant (TNode< IntegralT > node, int64_t * out_value)
Definition at line 442 of file code-assembler.cc.
                                                           {
  Int64Matcher m(node);
  if (m.HasResolvedValue()) *out_value = m.ResolvedValue();
  return m.HasResolvedValue();
}
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
TryToIntPtrConstant() [1/2]
bool v8::internal::compiler::CodeAssembler::TryToIntPtrConstant (TNode< IntegralT > node, intptr_t * out_value)
Definition at line 479 of file code-assembler.cc.
                                                             {
  IntPtrMatcher m(node);
  if (m.HasResolvedValue()) *out_value = m.ResolvedValue();
  return m.HasResolvedValue();
}
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
Referenced by v8::internal::CodeStubAssembler::AllocateOrderedHashTableWithCapacity(), v8::internal::CodeStubAssembler::AllocateRaw(), v8::internal::CodeStubAssembler::IntPtrMax(), v8::internal::CodeStubAssembler::IntPtrMin(), v8::internal::CodeStubAssembler::IsValidPositiveSmi(), v8::internal::CodeStubAssembler::LoadName(), v8::internal::CodeStubAssembler::SmiUntag(), TryToIntPtrConstant(), and v8::internal::CodeStubAssembler::WordIsPowerOfTwo().
TryToIntPtrConstant() [2/2]
bool v8::internal::compiler::CodeAssembler::TryToIntPtrConstant (TNode< Smi > tnode, intptr_t * out_value)
Definition at line 470 of file code-assembler.cc.
                                                                             {
  Node* node = tnode;
  if (node->opcode() == IrOpcode::kBitcastWordToTaggedSigned ||
      node->opcode() == IrOpcode::kBitcastWordToTagged) {
    node = node->InputAt(0);
  }
  return TryToIntPtrConstant(ReinterpretCast<IntPtrT>(tnode), out_value);
}
References v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::opcode(), and TryToIntPtrConstant().
TryToSmiConstant() [1/2]
bool v8::internal::compiler::CodeAssembler::TryToSmiConstant (TNode< IntegralT > node, Tagged< Smi > * out_value)
Definition at line 457 of file code-assembler.cc.
                                                             {
  IntPtrMatcher m(node);
  if (m.HasResolvedValue()) {
    intptr_t value = m.ResolvedValue();
    // Make sure that the value is actually a smi
    CHECK_EQ(0, value & ((static_cast<intptr_t>(1) << kSmiShiftSize) - 1));
    *out_value = Tagged<Smi>(static_cast<Address>(value));
    return true;
  }
  return false;
}
References CHECK_EQ, v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::kSmiShiftSize, v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), v8::internal::Tagged< Smi >, and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::FixedArrayBoundsCheck(), v8::internal::CodeStubAssembler::TryGetIntPtrOrSmiConstantValue(), and TryToSmiConstant().
TryToSmiConstant() [2/2]
bool v8::internal::compiler::CodeAssembler::TryToSmiConstant (TNode< Smi > node, Tagged< Smi > * out_value)
Definition at line 449 of file code-assembler.cc.
                                                                             {
  Node* node = tnode;
  if (node->opcode() == IrOpcode::kBitcastWordToTaggedSigned) {
    node = node->InputAt(0);
  }
  return TryToSmiConstant(ReinterpretCast<IntPtrT>(tnode), out_value);
}
References v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::opcode(), and TryToSmiConstant().
Uint32Add()
TNode<Uint32T> v8::internal::compiler::CodeAssembler::Uint32Add (TNode< Uint32T > left, TNode< Uint32T > right) [inline]
Definition at line 1157 of file code-assembler.h.
                                                                      {
    return Unsigned(Int32Add(static_cast<TNode<Word32T>>(left),
                             static_cast<TNode<Word32T>>(right)));
  }
References v8::base::bits::Unsigned().
Referenced by v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::CodeStubAssembler::SwissNameDictionaryIncreaseElementCountOrBailout(), and v8::internal::CodeStubAssembler::SwissNameDictionaryUpdateCountsForDeletion().
Uint32Constant()
TNode<Uint32T> v8::internal::compiler::CodeAssembler::Uint32Constant (uint32_t value) [inline]
Definition at line 586 of file code-assembler.h.
                                                {
    return Unsigned(Int32Constant(base::bit_cast<int32_t>(value)));
  }
References v8::base::bits::Unsigned(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::AddToDictionary(), v8::internal::StringBuiltinsAssembler::AllocAndCopyStringCharacters(), v8::internal::CodeStubAssembler::AllocateSeqOneByteString(), v8::internal::CodeStubAssembler::AllocateSeqTwoByteString(), v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::ChangeUint32ToTagged(), v8::internal::PrototypeCheckAssembler::CheckAndBranch(), v8::internal::CodeStubAssembler::CheckEnumCache(), v8::internal::CodeStubAssembler::CheckPrototypeEnumCache(), v8::internal::CodeStubAssembler::ClearTrustedPointerField(), v8::internal::StringBuiltinsAssembler::CopyStringCharacters(), v8::internal::IteratorBuiltinsAssembler::FastIterableToList(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntry(), v8::internal::RegExpBuiltinsAssembler::FlagsGetter(), v8::internal::CodeStubAssembler::GotoIfLargeBigInt(), v8::internal::CodeStubAssembler::InvalidDispatchHandleConstant(), v8::internal::CodeStubAssembler::IsWeakReferenceToObject(), v8::internal::CodeStubAssembler::LoadExternalPointerFromObject(), v8::internal::CodeStubAssembler::LoadJSReceiverIdentityHash(), v8::internal::CodeStubAssembler::LoadSwissNameDictionaryNumberOfDeletedElements(), v8::internal::CodeStubAssembler::LoadSwissNameDictionaryNumberOfElements(), v8::internal::interpreter::InterpreterAssembler::OnStackReplacement(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::CodeStubAssembler::SwissNameDictionaryIncreaseElementCountOrBailout(), v8::internal::CodeStubAssembler::SwissNameDictionaryUpdateCountsForDeletion(), v8::internal::CodeStubAssembler::TaggedIsPositiveSmi(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::WasmBuiltinsAssembler::ToUint(), v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16(), v8::internal::CodeStubAssembler::UpdateWord32(), and v8::internal::CodeStubAssembler::WordIsAligned().
Uint32Mul()
TNode<Uint32T> v8::internal::compiler::CodeAssembler::Uint32Mul (TNode< Uint32T > left, TNode< Uint32T > right) [inline]
Definition at line 1177 of file code-assembler.h.
                                                                      {
    return Unsigned(Int32Mul(static_cast<TNode<Word32T>>(left),
                             static_cast<TNode<Word32T>>(right)));
  }
References v8::base::bits::Unsigned().
Referenced by v8::internal::interpreter::InterpreterAssembler::OnStackReplacement().
Uint32Sub()
TNode<Uint32T> v8::internal::compiler::CodeAssembler::Uint32Sub (TNode< Uint32T > left, TNode< Uint32T > right) [inline]
Definition at line 1162 of file code-assembler.h.
                                                                      {
    return Unsigned(Int32Sub(static_cast<TNode<Word32T>>(left),
                             static_cast<TNode<Word32T>>(right)));
  }
References v8::base::bits::Unsigned().
Referenced by v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntry(), and v8::internal::CodeStubAssembler::SwissNameDictionaryUpdateCountsForDeletion().
Uint64Add()
TNode<Uint64T> v8::internal::compiler::CodeAssembler::Uint64Add (TNode< Uint64T > left, TNode< Uint64T > right) [inline]
Definition at line 1186 of file code-assembler.h.
                                                                      {
    return Unsigned(Int64Add(static_cast<TNode<Word64T>>(left), right));
  }
References v8::base::bits::Unsigned().
Referenced by v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16().
Uint64Constant()
TNode<Uint64T> v8::internal::compiler::CodeAssembler::Uint64Constant (uint64_t value) [inline]
Definition at line 578 of file code-assembler.h.
                                                {
    return Unsigned(Int64Constant(base::bit_cast<int64_t>(value)));
  }
References v8::base::bits::Unsigned(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::CountTrailingZeros64(), v8::internal::CodeStubAssembler::LoadBoundedSizeFromObject(), v8::internal::CodeStubAssembler::LoadSwissNameDictionaryCtrlTableGroup(), v8::internal::CodeStubAssembler::StoreBoundedSizeToObject(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16(), and v8::internal::CodeStubAssembler::TryFloat64ToAdditiveSafeInteger().
Uint64HighWordConstant()
TNode<Uint32T> v8::internal::compiler::CodeAssembler::Uint64HighWordConstant (uint64_t value) [inline]
Definition at line 589 of file code-assembler.h.
                                                        {
    return Uint32Constant(value >> 32);
  }
References v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16().
Uint64HighWordConstantNoLowWord()
TNode<Uint32T> v8::internal::compiler::CodeAssembler::Uint64HighWordConstantNoLowWord (uint64_t value) [inline]
Definition at line 592 of file code-assembler.h.
                                                                 {
    DCHECK_EQ(0, value & ~uint32_t{0});
    return Uint64HighWordConstant(value);
  }
References DCHECK_EQ, and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16().
Uint64LowWordConstant()
TNode<Uint32T> v8::internal::compiler::CodeAssembler::Uint64LowWordConstant (uint64_t value) [inline]
Definition at line 596 of file code-assembler.h.
                                                       {
    return Uint32Constant(static_cast<uint32_t>(value));
  }
References v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16().
Uint64Mul()
TNode<Uint64T> v8::internal::compiler::CodeAssembler::Uint64Mul (TNode< Uint64T > left, TNode< Uint64T > right) [inline]
Definition at line 1202 of file code-assembler.h.
                                                                      {
    return Unsigned(Int64Mul(static_cast<TNode<Word64T>>(left), right));
  }
References v8::base::bits::Unsigned().
Uint64Sub()
TNode<Uint64T> v8::internal::compiler::CodeAssembler::Uint64Sub (TNode< Uint64T > left, TNode< Uint64T > right) [inline]
Definition at line 1194 of file code-assembler.h.
                                                                      {
    return Unsigned(Int64Sub(static_cast<TNode<Word64T>>(left), right));
  }
References v8::base::bits::Unsigned().
Referenced by v8::internal::CodeStubAssembler::CountTrailingZeros64(), and v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16().
UintPtrAdd()
TNode<UintPtrT> v8::internal::compiler::CodeAssembler::UintPtrAdd (TNode< UintPtrT > left, TNode< UintPtrT > right) [inline]
Definition at line 1218 of file code-assembler.h.
                                                                          {
    return Unsigned(IntPtrAdd(static_cast<TNode<WordT>>(left),
                              static_cast<TNode<WordT>>(right)));
  }
References v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrAdd(), and v8::base::bits::Unsigned().
Referenced by v8::internal::BinaryOpAssembler::Generate_AddStringConstantInternalizeWithFeedback(), v8::internal::CodeStubAssembler::PopulationCountFallback(), v8::internal::TypedArrayBuiltinsAssembler::SetJSTypedArrayOnHeapDataPtr(), and v8::internal::CodeStubAssembler::StringCharCodeAt().
UintPtrConstant()
TNode<UintPtrT> v8::internal::compiler::CodeAssembler::UintPtrConstant (uintptr_t value) [inline]
Definition at line 599 of file code-assembler.h.
                                                   {
    return Unsigned(IntPtrConstant(base::bit_cast<intptr_t>(value)));
  }
References v8::internal::compiler::IntPtrConstant(), v8::base::bits::Unsigned(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::AllocateByteArray(), v8::internal::TypedArrayBuiltinsAssembler::AllocateEmptyOnHeapBuffer(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::CodeStubAssembler::ChangeUintPtrToTagged(), v8::internal::BinaryOpAssembler::Generate_AddStringConstantInternalizeWithFeedback(), v8::internal::TypedArrayBuiltinsAssembler::GetTypedArrayElementsInfo(), v8::internal::CodeStubAssembler::GotoIfLargeBigInt(), v8::internal::CodeStubAssembler::IsValidFastJSArrayCapacity(), v8::internal::CodeStubAssembler::LoadExternalPointerFromObject(), v8::internal::CodeStubAssembler::LoadName(), v8::internal::CodeStubAssembler::PopulationCountFallback(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::TypedArrayBuiltinsAssembler::SetJSTypedArrayOnHeapDataPtr(), v8::internal::CodeStubAssembler::StoreExternalPointerToObject(), v8::internal::interpreter::InterpreterAssembler::StoreRegisterForShortStar(), v8::internal::CodeStubAssembler::UpdateWord(), and v8::internal::ArrayBuiltinsAssembler::VisitAllTypedArrayElements().
UintPtrSub()
TNode<UintPtrT> v8::internal::compiler::CodeAssembler::UintPtrSub (TNode< UintPtrT > left, TNode< UintPtrT > right) [inline]
Definition at line 1222 of file code-assembler.h.
                                                                          {
    return Unsigned(IntPtrSub(static_cast<TNode<WordT>>(left),
                              static_cast<TNode<WordT>>(right)));
  }
References v8::base::bits::Unsigned().
UnalignedLoad() [1/2]
Node * v8::internal::compiler::CodeAssembler::UnalignedLoad (MachineType type, TNode< RawPtrT > base, TNode< WordT > offset) [private]
Definition at line 944 of file code-assembler.cc.
                                                        {
  return raw_assembler()->UnalignedLoad(type, static_cast<Node*>(base), offset);
}
References raw_assembler(), v8::internal::tracing::type, and v8::internal::compiler::RawMachineAssembler::UnalignedLoad().
UnalignedLoad() [2/2]
template<typename Type >
TNode<Type> v8::internal::compiler::CodeAssembler::UnalignedLoad (TNode< RawPtrT > base, TNode< IntPtrT > offset) [inline]
Definition at line 909 of file code-assembler.h.
                                                                        {
    MachineType mt = MachineTypeOf<Type>::value;
    return UncheckedCast<Type>(UnalignedLoad(mt, base, offset));
  }
UnalignedLoadSupported()
bool v8::internal::compiler::CodeAssembler::UnalignedLoadSupported (MachineRepresentation rep) const
Definition at line 1661 of file code-assembler.cc.
                                                                          {
  return raw_assembler()->machine()->UnalignedLoadSupported(rep);
}
References v8::internal::compiler::RawMachineAssembler::machine(), raw_assembler(), and v8::internal::compiler::MachineOperatorBuilder::UnalignedLoadSupported().
UnalignedStoreSupported()
bool v8::internal::compiler::CodeAssembler::UnalignedStoreSupported (MachineRepresentation rep) const
Definition at line 1664 of file code-assembler.cc.
                                                                           {
  return raw_assembler()->machine()->UnalignedStoreSupported(rep);
}
References v8::internal::compiler::RawMachineAssembler::machine(), raw_assembler(), and v8::internal::compiler::MachineOperatorBuilder::UnalignedStoreSupported().
UncheckedCast() [1/2]
template<class T >
TNode<T> v8::internal::compiler::CodeAssembler::UncheckedCast (Node * value) [inline]
Definition at line 534 of file code-assembler.h.
                                      {
    return TNode<T>::UncheckedCast(value);
  }
References v8::internal::TNode< T >::UncheckedCast(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{code-stub-assembler.cc}::InnerAllocateElements(), and v8::internal::anonymous_namespace{code-stub-assembler.cc}::InnerAllocateMemento().
UncheckedCast() [2/2]
template<class T , class U >
TNode<T> v8::internal::compiler::CodeAssembler::UncheckedCast (TNode< U > value) [inline]
Definition at line 538 of file code-assembler.h.
                                         {
    static_assert(types_have_common_values<T, U>::value,
                  "Incompatible types: this cast can never succeed.");
    return TNode<T>::UncheckedCast(value);
  }
References v8::internal::TNode< T >::UncheckedCast(), and v8::internal::value.
UncheckedParameter()
template<class T >
TNode<T> v8::internal::compiler::CodeAssembler::UncheckedParameter (int value) [inline]
Definition at line 716 of file code-assembler.h.
                                         {
    return UncheckedCast<T>(UntypedParameter(value));
  }
References v8::internal::value.
Uninitialized()
template<class T >
TNode<T> v8::internal::compiler::CodeAssembler::Uninitialized () [inline]
Definition at line 802 of file code-assembler.h.
                           {
    return {};
  }
UniqueInt32Constant()
TNode< Int32T > v8::internal::compiler::CodeAssembler::UniqueInt32Constant (int32_t value)
Definition at line 293 of file code-assembler.cc.
                                                              {
  return UncheckedCast<Int32T>(jsgraph()->UniqueInt32Constant(value));
}
References jsgraph(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::Float64Ceil(), v8::internal::CodeStubAssembler::Float64Floor(), v8::internal::CodeStubAssembler::Float64RoundToEven(), v8::internal::CodeStubAssembler::Float64Trunc(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GeneratePackedDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::CodeStubAssembler::GotoIfForceSlowPath(), and v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16().
UniqueInt64Constant()
TNode< Int64T > v8::internal::compiler::CodeAssembler::UniqueInt64Constant (int64_t value)
Definition at line 301 of file code-assembler.cc.
                                                              {
  return UncheckedCast<Int64T>(jsgraph()->UniqueInt64Constant(value));
}
References jsgraph(), and v8::internal::value.
UniqueIntPtrConstant()
TNode< IntPtrT > v8::internal::compiler::CodeAssembler::UniqueIntPtrConstant (intptr_t value)
Definition at line 309 of file code-assembler.cc.
                                                                 {
  return UncheckedCast<IntPtrT>(jsgraph()->UniqueIntPtrConstant(value));
}
References jsgraph(), and v8::internal::value.
UniqueUint32Constant()
TNode<Uint32T> v8::internal::compiler::CodeAssembler::UniqueUint32Constant (int32_t value) [inline]
Definition at line 583 of file code-assembler.h.
                                                     {
    return Unsigned(UniqueInt32Constant(base::bit_cast<int32_t>(value)));
  }
References v8::base::bits::Unsigned(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::LoadExternalPointerFromObject(), and v8::internal::CodeStubAssembler::StoreExternalPointerToObject().
Unreachable()
void v8::internal::compiler::CodeAssembler::Unreachable ()
Definition at line 659 of file code-assembler.cc.
{ raw_assembler()->Unreachable(); }
References raw_assembler(), and v8::internal::compiler::RawMachineAssembler::Unreachable().
Referenced by v8::internal::BaseCollectionsAssembler::AddConstructorEntries(), v8::internal::CodeStubAssembler::AllocateArrayList(), v8::internal::CodeStubAssembler::AllocateFixedArray(), v8::internal::CodeStubAssembler::AllocateRaw(), v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::ArrayListEnsureSpace(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithArrayLike(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithSpread(), v8::internal::RegExpBuiltinsAssembler::ConstructNewResultFromMatchInfo(), v8::internal::SharedArrayBufferBuiltinsAssembler::DebugCheckAtomicIndex(), v8::internal::HandlerBuiltinsAssembler::DispatchByElementsKind(), v8::internal::HandlerBuiltinsAssembler::DispatchForElementsKindTransition(), v8::internal::TypedArrayBuiltinsAssembler::DispatchTypedArrayByElementsKind(), v8::internal::CodeStubAssembler::FailAssert(), v8::internal::CodeStubAssembler::FastCheck(), v8::internal::ObjectBuiltinsAssembler::FromPropertyDescriptor(), v8::internal::WriteBarrierCodeStubAssembler::GenerateIndirectPointerBarrier(), v8::internal::ArrayBuiltinsAssembler::GenerateIteratingTypedArrayBuiltinBody(), v8::internal::IteratorBuiltinsAssembler::GetIterator(), v8::internal::CodeStubAssembler::GetNameDictionaryFlags(), v8::internal::CodeStubAssembler::GetSharedFunctionInfoCode(), v8::internal::GeneratorBuiltinsAssembler::InnerResume(), v8::internal::IteratorBuiltinsAssembler::Iterate(), v8::internal::IteratorBuiltinsAssembler::IteratorStep(), v8::internal::CodeStubAssembler::LoadFixedTypedArrayElementAsTagged(), v8::internal::CodeStubAssembler::PlainPrimitiveToNumber(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Single(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::MicrotaskQueueBuiltinsAssembler::RunSingleMicrotask(), v8::internal::CodeStubAssembler::SetNameDictionaryFlags(), v8::internal::ShadowRealmBuiltinsAssembler::ShadowRealmThrow(), v8::internal::IteratorBuiltinsAssembler::StringListFromIterable(), v8::internal::CodeStubAssembler::TaggedToWord32OrBigIntImpl(), v8::internal::CodeStubAssembler::TerminateExecution(), v8::internal::CodeStubAssembler::ThrowRangeError(), v8::internal::CodeStubAssembler::ThrowTypeError(), v8::internal::ToDirectStringAssembler::ToDirect(), v8::internal::ArrayBuiltinsAssembler::TypedArrayMapResultGenerator(), and v8::internal::SharedArrayBufferBuiltinsAssembler::ValidateAtomicAccess().
UnregisterCallGenerationCallbacks()
void v8::internal::compiler::CodeAssembler::UnregisterCallGenerationCallbacks () [protected]
Definition at line 140 of file code-assembler.cc.
                                                      {
  state_->call_prologue_ = nullptr;
  state_->call_epilogue_ = nullptr;
}
References v8::internal::compiler::CodeAssemblerState::call_epilogue_, v8::internal::compiler::CodeAssemblerState::call_prologue_, and state_.
Referenced by v8::internal::interpreter::InterpreterAssembler::~InterpreterAssembler().
UnsafeStoreNoWriteBarrier() [1/2]
void v8::internal::compiler::CodeAssembler::UnsafeStoreNoWriteBarrier (MachineRepresentation rep, Node * base, Node * offset, Node * value)
Definition at line 1053 of file code-assembler.cc.
                                                           {
  // Please use OptimizedStoreMap(base, value) instead.
  DCHECK(!raw_assembler()->IsMapOffsetConstantMinusTag(offset));
  raw_assembler()->Store(rep, base, offset, value, kNoWriteBarrier);
}
References v8::internal::DCHECK(), v8::internal::compiler::kNoWriteBarrier, raw_assembler(), v8::internal::compiler::RawMachineAssembler::Store(), and v8::internal::value.
UnsafeStoreNoWriteBarrier() [2/2]
void v8::internal::compiler::CodeAssembler::UnsafeStoreNoWriteBarrier (MachineRepresentation rep, Node * base, Node * value)
Definition at line 1048 of file code-assembler.cc.
                                                                       {
  raw_assembler()->Store(rep, base, value, kNoWriteBarrier);
}
References v8::internal::compiler::kNoWriteBarrier, raw_assembler(), v8::internal::compiler::RawMachineAssembler::Store(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::CodeStubAssembler::StoreFeedbackVectorSlot(), v8::internal::CodeStubAssembler::StoreFieldsNoWriteBarrier(), and v8::internal::CodeStubAssembler::StoreFixedArrayOrPropertyArrayElement().
Unsigned() [1/4]
TNode<Uint32T> v8::internal::compiler::CodeAssembler::Unsigned (TNode< Uint32T > x) [private]
Unsigned() [2/4]
TNode<Uint32T> v8::internal::compiler::CodeAssembler::Unsigned (TNode< Word32T > x) [inline]
Definition at line 668 of file code-assembler.h.
                                            {
    return UncheckedCast<Uint32T>(x);
  }
Referenced by v8::internal::RegExpBuiltinsAssembler::AdvanceStringIndex(), v8::internal::StringBuiltinsAssembler::AllocAndCopyStringCharacters(), v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::CodeStubAssembler::BigIntFromInt32Pair(), v8::internal::CodeStubAssembler::BigIntFromInt64(), v8::internal::CodeStubAssembler::ChangeNonNegativeNumberToUint32(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::CodeStubAssembler::CountTrailingZeros64(), v8::internal::ConstructorBuiltinsAssembler::CreateEmptyArrayLiteral(), v8::internal::DataViewBuiltinsAssembler::DataViewEncodeBigIntBits(), v8::internal::CodeStubAssembler::DecodeWord(), v8::internal::CodeStubAssembler::DecodeWord32(), v8::internal::CodeStubAssembler::DescriptorArrayGetDetails(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FastGetOwnValuesOrEntries(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForSmiKey(), v8::internal::CodeStubAssembler::ForEachEnumerableOwnProperty(), v8::internal::interpreter::InterpreterAssembler::GetContextAtDepth(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), v8::internal::CodeStubAssembler::LoadAndUntagBytecodeArrayLength(), v8::internal::CodeStubAssembler::LoadAndUntagFixedArrayBaseLengthAsUint32(), v8::internal::CodeStubAssembler::LoadAndUntagWeakFixedArrayLengthAsUint32(), v8::internal::CodeStubAssembler::LoadDetailsByDescriptorEntry(), v8::internal::CodeStubAssembler::LoadDetailsByKeyIndex(), v8::internal::StringBuiltinsAssembler::LoadSurrogatePairAt(), v8::internal::CodeStubAssembler::LoadSwissNameDictionaryCtrlTableGroup(), v8::internal::CodeStubAssembler::LookupBinary(), v8::internal::AccessorAssembler::LookupContext(), v8::internal::AccessorAssembler::LookupGlobalIC(), v8::internal::KeyedStoreGenericAssembler::LookupPropertyOnPrototypeChain(), v8::internal::interpreter::InterpreterAssembler::OnStackReplacement(), v8::internal::AccessorAssembler::OverwriteExistingFastDataProperty(), v8::internal::CodeStubAssembler::PositiveSmiToUint32(), v8::internal::RegExpBuiltinsAssembler::RegExpExecAtom(), v8::internal::StringBuiltinsAssembler::SearchOneByteInOneByteString(), v8::internal::TypedArrayBuiltinsAssembler::SetJSTypedArrayOnHeapDataPtr(), v8::internal::AccessorAssembler::StoreJSSharedStructField(), v8::internal::CodeStubAssembler::StoreSwissNameDictionaryEnumToEntryMapping(), v8::internal::CodeStubAssembler::StringCharCodeAt(), v8::internal::StringBuiltinsAssembler::SubString(), and v8::internal::BigIntBuiltinsAssembler::WriteBigIntSignAndLength().
Unsigned() [3/4]
TNode<Uint64T> v8::internal::compiler::CodeAssembler::Unsigned (TNode< Word64T > x) [inline]
Definition at line 671 of file code-assembler.h.
                                            {
    return UncheckedCast<Uint64T>(x);
  }
Unsigned() [4/4]
TNode<UintPtrT> v8::internal::compiler::CodeAssembler::Unsigned (TNode< WordT > x) [inline]
Definition at line 674 of file code-assembler.h.
                                           {
    return UncheckedCast<UintPtrT>(x);
  }
UntypedHeapConstantHole()
TNode< HeapObject > v8::internal::compiler::CodeAssembler::UntypedHeapConstantHole (Handle< HeapObject > object)
Definition at line 378 of file code-assembler.cc.
                               {
  CanonicalizeEmbeddedBuiltinsConstantIfNeeded(object);
  return UncheckedCast<HeapObject>(jsgraph()->HeapConstantHole(object));
}
References HeapConstantHole(), and jsgraph().
UntypedHeapConstantMaybeHole()
TNode< HeapObject > v8::internal::compiler::CodeAssembler::UntypedHeapConstantMaybeHole (Handle< HeapObject > object)
Definition at line 371 of file code-assembler.cc.
                               {
  CanonicalizeEmbeddedBuiltinsConstantIfNeeded(object);
  return UncheckedCast<HeapObject>(jsgraph()->HeapConstantMaybeHole(object));
}
References HeapConstantMaybeHole(), and jsgraph().
UntypedHeapConstantNoHole()
template<typename E >
TNode< HeapObject > v8::internal::compiler::CodeAssembler::UntypedHeapConstantNoHole (Handle< HeapObject > object)
Definition at line 361 of file code-assembler.cc.
                               {
  // jsgraph()->HeapConstantNoHole does a CHECK that it is in fact a hole
  // value.
  CanonicalizeEmbeddedBuiltinsConstantIfNeeded(object);
  return UncheckedCast<HeapObject>(jsgraph()->HeapConstantNoHole(object));
}
References HeapConstantNoHole(), and jsgraph().
UntypedParameter()
Node * v8::internal::compiler::CodeAssembler::UntypedParameter (int value)
Definition at line 496 of file code-assembler.cc.
                                               {
  if (index == kTargetParameterIndex) return raw_assembler()->TargetParameter();
  return raw_assembler()->Parameter(index);
}
References v8::internal::index, kTargetParameterIndex, v8::internal::compiler::RawMachineAssembler::Parameter(), raw_assembler(), and v8::internal::compiler::RawMachineAssembler::TargetParameter().
Word32And() [1/4]
TNode<BoolT> v8::internal::compiler::CodeAssembler::Word32And (TNode< BoolT > left, TNode< BoolT > right) [inline]
Definition at line 1147 of file code-assembler.h.
                                                                {
    return UncheckedCast<BoolT>(Word32And(static_cast<TNode<Word32T>>(left),
                                          static_cast<TNode<Word32T>>(right)));
  }
Word32And() [2/4]
TNode<Int32T> v8::internal::compiler::CodeAssembler::Word32And (TNode< Int32T > left, TNode< Int32T > right) [inline]
Definition at line 1106 of file code-assembler.h.
                                                                   {
    return Signed(Word32And(static_cast<TNode<Word32T>>(left),
                            static_cast<TNode<Word32T>>(right)));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::RegExpBuiltinsAssembler::AdvanceStringIndex(), v8::internal::StringBuiltinsAssembler::AllocateConsString(), v8::internal::StringBuiltinsAssembler::BranchIfCanDerefIndirectString(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithArrayLike(), v8::internal::PrototypeCheckAssembler::CheckAndBranch(), v8::internal::CollectionsBuiltinsAssembler::ComputeUnseededHash(), v8::internal::CodeStubAssembler::CountTrailingZeros32(), v8::internal::CodeStubAssembler::DecodeWord32(), v8::internal::AccessorAssembler::DefineKeyedOwnIC(), v8::internal::StringBuiltinsAssembler::DirectStringData(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntry(), v8::internal::CodeStubAssembler::Float64ToString(), v8::internal::ObjectBuiltinsAssembler::FromPropertyDescriptor(), v8::internal::StringBuiltinsAssembler::GenerateStringRelationalComparison(), v8::internal::WeakCollectionsBuiltinsAssembler::GetHash(), v8::internal::BaseCollectionsAssembler::GotoIfCannotBeHeldWeakly(), v8::internal::StringBuiltinsAssembler::HasUnpairedSurrogate(), v8::internal::CodeStubAssembler::IsConsStringInstanceType(), v8::internal::CodeStubAssembler::IsExtensibleNonPrototypeMap(), v8::internal::CodeStubAssembler::IsExternalStringInstanceType(), v8::internal::CodeStubAssembler::IsFastPackedElementsKind(), v8::internal::CodeStubAssembler::IsFixedArraySubclass(), v8::internal::CodeStubAssembler::IsHashTable(), v8::internal::CodeStubAssembler::IsIndirectStringInstanceType(), v8::internal::CodeStubAssembler::IsInternalizedStringInstanceType(), v8::internal::CodeStubAssembler::IsOneByteStringInstanceType(), v8::internal::CodeStubAssembler::IsOneByteStringMap(), v8::internal::CodeStubAssembler::IsSeqOneByteStringInstanceType(), v8::internal::CodeStubAssembler::IsSequentialStringInstanceType(), v8::internal::CodeStubAssembler::IsSharedStringInstanceType(), v8::internal::CodeStubAssembler::IsStrong(), v8::internal::CodeStubAssembler::IsWeakOrCleared(), v8::internal::CodeStubAssembler::IsWeakReferenceToObject(), v8::internal::interpreter::InterpreterAssembler::LoadOsrState(), v8::internal::StringBuiltinsAssembler::LoadSurrogatePairAt(), v8::internal::interpreter::InterpreterAssembler::OnStackReplacement(), v8::internal::CodeStubAssembler::PrintToStream(), v8::internal::StringBuiltinsAssembler::ReplaceUnpairedSurrogates(), v8::internal::WeakCollectionsBuiltinsAssembler::ShouldShrink(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::StringBuiltinsAssembler::StringEqual_Core(), v8::internal::AccessorAssembler::StubCachePrimaryOffset(), v8::internal::AccessorAssembler::StubCacheSecondaryOffset(), v8::internal::CodeStubAssembler::TaggedIsPositiveSmi(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::CodeStubAssembler::TaggedIsStrongHeapObject(), v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16(), v8::internal::ToDirectStringAssembler::TryToDirect(), v8::internal::CodeStubAssembler::UpdateWord32(), v8::internal::CodeStubAssembler::WordIsAligned(), and v8::internal::BigIntBuiltinsAssembler::WriteBigIntSignAndLength().
Word32And() [3/4]
TNode<Uint32T> v8::internal::compiler::CodeAssembler::Word32And (TNode< Uint32T > left, TNode< Uint32T > right) [inline]
Definition at line 1110 of file code-assembler.h.
                                                                      {
    return Unsigned(Word32And(static_cast<TNode<Word32T>>(left),
                              static_cast<TNode<Word32T>>(right)));
  }
References v8::base::bits::Unsigned().
Word32And() [4/4]
TNode<Word32T> v8::internal::compiler::CodeAssembler::Word32And (TNode< Word32T > left, int right) [inline]
Definition at line 1253 of file code-assembler.h.
                                                           {
    return Word32And(left, Int32Constant(right));
  }
Word32BitwiseNot()
TNode<Int32T> v8::internal::compiler::CodeAssembler::Word32BitwiseNot (TNode< Int32T > a) [inline]
Definition at line 1140 of file code-assembler.h.
                                                  {
    return Signed(Word32BitwiseNot(static_cast<TNode<Word32T>>(a)));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::CodeStubAssembler::CountTrailingZeros32().
Word32Equal() [1/2]
TNode<BoolT> v8::internal::compiler::CodeAssembler::Word32Equal (TNode< Word32T > left, int right) [inline]
Definition at line 1259 of file code-assembler.h.
                                                           {
    return Word32Equal(left, Int32Constant(right));
  }
References v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Word32Equal() [2/2]
TNode<BoolT> v8::internal::compiler::CodeAssembler::Word32Equal (TNode< Word32T > left, TNode< Word32T > right)
Referenced by v8::internal::BaseCollectionsAssembler::AddConstructorEntries(), v8::internal::RegExpBuiltinsAssembler::AdvanceStringIndex(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::CodeStubAssembler::BasicLoadNumberDictionaryElement(), v8::internal::StringBuiltinsAssembler::BranchIfCanDerefIndirectString(), v8::internal::KeyedStoreGenericAssembler::BranchIfPrototypesMayHaveReadOnlyElements(), v8::internal::CodeStubAssembler::BranchIfToBooleanIsTrue(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithArrayLike(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithSpread(), v8::internal::PrototypeCheckAssembler::CheckAndBranch(), v8::internal::CodeStubAssembler::CheckEnumCache(), v8::internal::AccessorAssembler::CheckFieldType(), v8::internal::AccessorAssembler::CheckHeapObjectTypeMatchesDescriptor(), v8::internal::CodeStubAssembler::CheckPrototypeEnumCache(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchNoArgument(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchSingleArgument(), v8::internal::StringBuiltinsAssembler::DirectStringData(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::KeyedStoreGenericAssembler::EmitGenericElementStore(), v8::internal::ObjectBuiltinsAssembler::FromPropertyDescriptor(), v8::internal::StringBuiltinsAssembler::GenerateStringRelationalComparison(), v8::internal::LazyBuiltinsAssembler::GenerateTailCallToJSFunction(), v8::internal::interpreter::InterpreterAssembler::GetContextAtDepth(), v8::internal::CodeStubAssembler::GotoIfLargeBigInt(), v8::internal::CodeStubAssembler::GotoIfNotDoubleStringCacheEntryKeyEqual(), v8::internal::AccessorAssembler::GotoIfNotSameNumberBitPattern(), v8::internal::AccessorAssembler::HandleLoadICProtoHandler(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerHasNamedCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), v8::internal::AccessorAssembler::HandleStoreFieldAndReturn(), v8::internal::AccessorAssembler::HandleStoreICHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICProtoHandler(), v8::internal::AccessorAssembler::HandleStoreICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleStoreICSmiHandlerJSSharedStructFieldCase(), v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase(), v8::internal::StringBuiltinsAssembler::HasUnpairedSurrogate(), v8::internal::CodeStubAssembler::InstanceTypeEqual(), v8::internal::WriteBarrierCodeStubAssembler::InYoungGeneration(), v8::internal::CodeStubAssembler::IsCleared(), v8::internal::CodeStubAssembler::IsConsStringInstanceType(), v8::internal::CodeStubAssembler::IsDoubleElementsKind(), v8::internal::CodeStubAssembler::IsDoubleHole(), v8::internal::CodeStubAssembler::IsExtensibleNonPrototypeMap(), v8::internal::CodeStubAssembler::IsExternalStringInstanceType(), v8::internal::CodeStubAssembler::IsInternalizedStringInstanceType(), v8::internal::CodeStubAssembler::IsOneByteStringInstanceType(), v8::internal::CodeStubAssembler::IsOneByteStringMap(), v8::internal::AccessorAssembler::IsPropertyDetailsConst(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::IsPropertyKindAccessor(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::IsPropertyKindData(), v8::internal::CodeStubAssembler::IsSeqOneByteStringInstanceType(), v8::internal::CodeStubAssembler::IsSeqOneByteStringMap(), v8::internal::CodeStubAssembler::IsSequentialStringInstanceType(), v8::internal::CodeStubAssembler::IsSharedStringInstanceType(), v8::internal::CodeStubAssembler::IsStringWrapperElementsKind(), v8::internal::CodeStubAssembler::IsStrong(), v8::internal::TypedArrayBuiltinsAssembler::IsUint8ElementsKind(), v8::internal::CodeStubAssembler::IsWeakOrCleared(), v8::internal::CodeStubAssembler::IsWeakReferenceTo(), v8::internal::CodeStubAssembler::IsWeakReferenceToObject(), v8::internal::AccessorAssembler::JumpIfDataProperty(), v8::internal::IntlBuiltinsAssembler::JumpIfStartsWithIgnoreCase(), v8::internal::BaseCollectionsAssembler::LoadAndNormalizeFixedDoubleArrayElement(), v8::internal::WasmBuiltinsAssembler::LoadContextFromWasmOrJsFrame(), v8::internal::CodeStubAssembler::LoadExternalPointerFromObject(), v8::internal::CodeStubAssembler::LoadJSReceiverIdentityHash(), v8::internal::CodeStubAssembler::LoadSharedFunctionInfoBytecodeArray(), v8::internal::CodeStubAssembler::LoadSharedFunctionInfoTrustedData(), v8::internal::StringBuiltinsAssembler::LoadSurrogatePairAt(), v8::internal::CollectionsBuiltinsAssembler::NextSkipHashTableHoles(), v8::internal::interpreter::InterpreterAssembler::OnStackReplacement(), v8::internal::AccessorAssembler::OverwriteExistingFastDataProperty(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::StringBuiltinsAssembler::ReplaceUnpairedSurrogates(), v8::internal::CodeStubAssembler::SmiMod(), v8::internal::CodeStubAssembler::SmiMul(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::AccessorAssembler::StoreGlobalIC_PropertyCellCase(), v8::internal::AccessorAssembler::StoreInArrayLiteralIC(), v8::internal::AccessorAssembler::StoreJSSharedStructField(), v8::internal::KeyedStoreGenericAssembler::StoreProperty(), v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::StringBuiltinsAssembler::StringEqual_Core(), v8::internal::StringBuiltinsAssembler::StringEqual_FastLoop(), v8::internal::AccessorAssembler::StubCachePrimaryOffset(), v8::internal::CodeStubAssembler::TaggedIsPositiveSmi(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::CodeStubAssembler::TaggedIsStrongHeapObject(), v8::internal::CodeStubAssembler::TaggedToBigInt(), v8::internal::CodeStubAssembler::ThrowIfNotInstanceType(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::KeyedStoreGenericAssembler::TryChangeToHoleyMap(), v8::internal::KeyedStoreGenericAssembler::TryChangeToHoleyMapMulti(), v8::internal::CodeStubAssembler::TryFloat32ToSmi(), v8::internal::CodeStubAssembler::TryFloat64ToInt32(), v8::internal::CodeStubAssembler::TryFloat64ToSmi(), v8::internal::CodeStubAssembler::TrySmiDiv(), v8::internal::ArrayBuiltinsAssembler::TypedArrayMapResultGenerator(), v8::internal::CodeStubAssembler::UpdateWord32(), v8::internal::CodeStubAssembler::Use(), and v8::internal::CodeStubAssembler::WordIsAligned().
Word32NotEqual()
TNode<BoolT> v8::internal::compiler::CodeAssembler::Word32NotEqual (TNode< Word32T > left, TNode< Word32T > right)
Referenced by v8::internal::StringBuiltinsAssembler::BranchIfCanDerefIndirectString(), v8::internal::CodeStubAssembler::DoesntHaveInstanceType(), v8::internal::StringBuiltinsAssembler::GenerateSeqStringRelationalComparison(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::CodeStubAssembler::IsDebugActive(), v8::internal::WriteBarrierCodeStubAssembler::IsMarking(), v8::internal::WriteBarrierCodeStubAssembler::IsMinorMarking(), v8::internal::WriteBarrierCodeStubAssembler::IsSharedSpaceIsolate(), v8::internal::StringBuiltinsAssembler::LoadSurrogatePairAt(), v8::internal::CodeStubAssembler::LookupBinary(), v8::internal::CodeStubAssembler::NeedsAnyPromiseHooks(), v8::internal::AccessorAssembler::OverwriteExistingFastDataProperty(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::StringBuiltinsAssembler::StringEqual_FastLoop(), v8::internal::StringBuiltinsAssembler::StringEqual_Loop(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::CodeStubAssembler::TrySmiDiv(), and v8::internal::WriteBarrierCodeStubAssembler::UsesSharedHeap().
Word32Or() [1/3]
TNode<BoolT> v8::internal::compiler::CodeAssembler::Word32Or (TNode< BoolT > left, TNode< BoolT > right) [inline]
Definition at line 1143 of file code-assembler.h.
                                                               {
    return UncheckedCast<BoolT>(Word32Or(static_cast<TNode<Word32T>>(left),
                                         static_cast<TNode<Word32T>>(right)));
  }
Word32Or() [2/3]
TNode<Int32T> v8::internal::compiler::CodeAssembler::Word32Or (TNode< Int32T > left, TNode< Int32T > right) [inline]
Definition at line 1120 of file code-assembler.h.
                                                                  {
    return Signed(Word32Or(static_cast<TNode<Word32T>>(left),
                           static_cast<TNode<Word32T>>(right)));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::StringBuiltinsAssembler::AllocAndCopyStringCharacters(), v8::internal::CodeStubAssembler::BigIntFromInt32Pair(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReadUnaligned(), v8::internal::CodeStubAssembler::CheckEnumCache(), v8::internal::CodeStubAssembler::CopyElements(), v8::internal::CodeStubAssembler::CopyPropertyArrayValues(), v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchSingleArgument(), v8::internal::RegExpMatchAllAssembler::CreateRegExpStringIterator(), v8::internal::HandlerBuiltinsAssembler::DispatchForElementsKindTransition(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::IteratorBuiltinsAssembler::FastIterableToList(), v8::internal::WeakCollectionsBuiltinsAssembler::FindKeyIndexForInsertion(), v8::internal::AccessorAssembler::GenerateCloneObjectIC(), v8::internal::AccessorAssembler::GenerateLoadIC_Megamorphic(), v8::internal::StringBuiltinsAssembler::GenerateStringRelationalComparison(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerHasNamedCase(), v8::internal::AccessorAssembler::HandleStoreICSmiHandlerCase(), v8::internal::CodeStubAssembler::InitializeJSObjectFromMap(), v8::internal::CodeStubAssembler::InsertEntry(), v8::internal::WeakCollectionsBuiltinsAssembler::InsufficientCapacityToAdd(), v8::internal::TypedArrayBuiltinsAssembler::IsBigInt64ElementsKind(), v8::internal::IntlBuiltinsAssembler::IsNonAlpha(), v8::internal::CodeStubAssembler::IsNotWeakFixedArraySubclass(), v8::internal::CodeStubAssembler::IsNullOrJSReceiver(), v8::internal::CodeStubAssembler::IsNullOrUndefined(), v8::internal::CodeStubAssembler::IsNumeric(), v8::internal::CodeStubAssembler::IsSharedStringInstanceType(), v8::internal::CodeStubAssembler::IsStringWrapperElementsKind(), v8::internal::TypedArrayBuiltinsAssembler::IsUint8ElementsKind(), v8::internal::CodeStubAssembler::IsWeakReferenceTo(), v8::internal::CodeStubAssembler::JSAnyIsNotPrimitiveMap(), v8::internal::IntlBuiltinsAssembler::JumpIfStartsWithIgnoreCase(), v8::internal::CodeStubAssembler::LoadFastJSArrayLength(), v8::internal::AccessorAssembler::LoadHandlerDataField(), v8::internal::CodeStubAssembler::LoadHeapNumberValue(), v8::internal::CodeStubAssembler::LoadSlowProperties(), v8::internal::StringBuiltinsAssembler::LoadSurrogatePairAt(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::CodeStubAssembler::SetPendingMessage(), v8::internal::CodeStubAssembler::SmiMul(), v8::internal::AccessorAssembler::StoreGlobalIC_PropertyCellCase(), v8::internal::AccessorAssembler::StoreInArrayLiteralIC(), v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::StringBuiltinsAssembler::StringEqual_Core(), v8::internal::CodeStubAssembler::SwissNameDictionarySetCtrl(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16(), v8::internal::CodeStubAssembler::UpdateWord32(), and v8::internal::BigIntBuiltinsAssembler::WriteBigIntSignAndLength().
Word32Or() [3/3]
TNode<Uint32T> v8::internal::compiler::CodeAssembler::Word32Or (TNode< Uint32T > left, TNode< Uint32T > right) [inline]
Definition at line 1124 of file code-assembler.h.
                                                                     {
    return Unsigned(Word32Or(static_cast<TNode<Word32T>>(left),
                             static_cast<TNode<Word32T>>(right)));
  }
References v8::base::bits::Unsigned().
Word32Sar() [1/2]
TNode<Int32T> v8::internal::compiler::CodeAssembler::Word32Sar (TNode< Int32T > left, TNode< Int32T > right) [inline]
Definition at line 1056 of file code-assembler.h.
                                                                   {
    return Signed(Word32Sar(static_cast<TNode<Word32T>>(left), right));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad(), and Word32Sar().
Word32Sar() [2/2]
TNode< Word32T > v8::internal::compiler::CodeAssembler::Word32Sar (TNode< Word32T > value, int shift)
Definition at line 770 of file code-assembler.cc.
                                                                       {
  return (shift != 0) ? Word32Sar(value, Int32Constant(shift)) : value;
}
References Int32Constant(), v8::internal::value, and Word32Sar().
Word32ShiftIsSafe()
bool v8::internal::compiler::CodeAssembler::Word32ShiftIsSafe () const [protected]
Definition at line 157 of file code-assembler.cc.
                                            {
  return raw_assembler()->machine()->Word32ShiftIsSafe();
}
References v8::internal::compiler::RawMachineAssembler::machine(), raw_assembler(), and v8::internal::compiler::MachineOperatorBuilder::Word32ShiftIsSafe().
Word32Shl() [1/3]
TNode<Int32T> v8::internal::compiler::CodeAssembler::Word32Shl (TNode< Int32T > left, int right) [inline]
Definition at line 1256 of file code-assembler.h.
                                                         {
    return Word32Shl(left, Int32Constant(right));
  }
Word32Shl() [2/3]
TNode<Int32T> v8::internal::compiler::CodeAssembler::Word32Shl (TNode< Int32T > left, TNode< Int32T > right) [inline]
Definition at line 1047 of file code-assembler.h.
                                                                   {
    return Signed(Word32Shl(static_cast<TNode<Word32T>>(left), right));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::CodeStubAssembler::AllocateBigInt(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReadUnaligned(), v8::internal::CollectionsBuiltinsAssembler::ComputeUnseededHash(), v8::internal::RegExpMatchAllAssembler::CreateRegExpStringIterator(), v8::internal::HandlerBuiltinsAssembler::DispatchForElementsKindTransition(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::StringBuiltinsAssembler::GenerateStringRelationalComparison(), v8::internal::StringBuiltinsAssembler::LoadSurrogatePairAt(), v8::internal::WeakCollectionsBuiltinsAssembler::ShouldRehash(), v8::internal::StringBuiltinsAssembler::StringEqual_Core(), v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad(), v8::internal::CodeStubAssembler::UpdateWord32(), and v8::internal::BigIntBuiltinsAssembler::WriteBigIntSignAndLength().
Word32Shl() [3/3]
TNode<Uint32T> v8::internal::compiler::CodeAssembler::Word32Shl (TNode< Uint32T > left, TNode< Uint32T > right) [inline]
Definition at line 1050 of file code-assembler.h.
                                                                      {
    return Unsigned(Word32Shl(static_cast<TNode<Word32T>>(left), right));
  }
References v8::base::bits::Unsigned().
Word32Shr() [1/2]
TNode<Uint32T> v8::internal::compiler::CodeAssembler::Word32Shr (TNode< Uint32T > left, TNode< Uint32T > right) [inline]
Definition at line 1053 of file code-assembler.h.
                                                                      {
    return Unsigned(Word32Shr(static_cast<TNode<Word32T>>(left), right));
  }
References v8::base::bits::Unsigned().
Referenced by v8::internal::CollectionsBuiltinsAssembler::ComputeUnseededHash(), v8::internal::CodeStubAssembler::DecodeWord32(), v8::internal::WeakCollectionsBuiltinsAssembler::InsufficientCapacityToAdd(), v8::internal::CodeStubAssembler::IsDoubleElementsKind(), v8::internal::CodeStubAssembler::LoadExternalPointerFromObject(), v8::internal::CodeStubAssembler::LookupBinary(), v8::internal::CodeStubAssembler::PrintToStream(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::CodeStubAssembler::StoreExternalPointerToObject(), v8::internal::AccessorAssembler::StubCacheSecondaryOffset(), v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16(), and Word32Shr().
Word32Shr() [2/2]
TNode< Word32T > v8::internal::compiler::CodeAssembler::Word32Shr (TNode< Word32T > value, int shift)
Definition at line 766 of file code-assembler.cc.
                                                                       {
  return (shift != 0) ? Word32Shr(value, Int32Constant(shift)) : value;
}
References Int32Constant(), v8::internal::value, and Word32Shr().
Word64And() [1/2]
TNode<Int64T> v8::internal::compiler::CodeAssembler::Word64And (TNode< Int64T > left, TNode< Int64T > right) [inline]
Definition at line 1076 of file code-assembler.h.
                                                                   {
    return Signed(Word64And(static_cast<TNode<Word64T>>(left), right));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::CodeStubAssembler::CountTrailingZeros64(), v8::internal::CodeStubAssembler::LoadSwissNameDictionaryCtrlTableGroup(), and v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16().
Word64And() [2/2]
TNode<Uint64T> v8::internal::compiler::CodeAssembler::Word64And (TNode< Uint64T > left, TNode< Uint64T > right) [inline]
Definition at line 1079 of file code-assembler.h.
                                                                      {
    return Unsigned(Word64And(static_cast<TNode<Word64T>>(left), right));
  }
References v8::base::bits::Unsigned().
Word64Equal()
TNode<BoolT> v8::internal::compiler::CodeAssembler::Word64Equal (TNode< Word64T > left, TNode< Word64T > right)
Referenced by v8::internal::CodeStubAssembler::IsDoubleHole(), and v8::internal::CodeStubAssembler::TryFloat64ToAdditiveSafeInteger().
Word64Not() [1/2]
TNode<Int64T> v8::internal::compiler::CodeAssembler::Word64Not (TNode< Int64T > value) [inline]
Definition at line 1090 of file code-assembler.h.
                                               {
    return Signed(Word64Not(static_cast<TNode<Word64T>>(value)));
  }
References v8::base::bits::Signed(), and v8::internal::value.
Referenced by v8::internal::CodeStubAssembler::CountTrailingZeros64().
Word64Not() [2/2]
TNode<Uint64T> v8::internal::compiler::CodeAssembler::Word64Not (TNode< Uint64T > value) [inline]
Definition at line 1093 of file code-assembler.h.
                                                 {
    return Unsigned(Word64Not(static_cast<TNode<Word64T>>(value)));
  }
References v8::base::bits::Unsigned(), and v8::internal::value.
Word64NotEqual()
TNode<BoolT> v8::internal::compiler::CodeAssembler::Word64NotEqual (TNode< Word64T > left, TNode< Word64T > right)
Referenced by v8::internal::StringBuiltinsAssembler::GenerateSeqStringRelationalComparison(), and v8::internal::StringBuiltinsAssembler::StringEqual_FastLoop().
Word64Sar()
TNode<Int64T> v8::internal::compiler::CodeAssembler::Word64Sar (TNode< Int64T > left, TNode< Int64T > right) [inline]
Definition at line 1072 of file code-assembler.h.
                                                                   {
    return Signed(Word64Sar(static_cast<TNode<Word64T>>(left), right));
  }
References v8::base::bits::Signed().
Word64Shl() [1/2]
TNode<Int64T> v8::internal::compiler::CodeAssembler::Word64Shl (TNode< Int64T > left, TNode< Int64T > right) [inline]
Definition at line 1060 of file code-assembler.h.
                                                                   {
    return Signed(Word64Shl(static_cast<TNode<Word64T>>(left), right));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::CodeStubAssembler::LoadSwissNameDictionaryCtrlTableGroup(), and v8::internal::CodeStubAssembler::StoreBoundedSizeToObject().
Word64Shl() [2/2]
TNode<Uint64T> v8::internal::compiler::CodeAssembler::Word64Shl (TNode< Uint64T > left, TNode< Uint64T > right) [inline]
Definition at line 1063 of file code-assembler.h.
                                                                      {
    return Unsigned(Word64Shl(static_cast<TNode<Word64T>>(left), right));
  }
References v8::base::bits::Unsigned().
Word64Shr() [1/2]
TNode<Int64T> v8::internal::compiler::CodeAssembler::Word64Shr (TNode< Int64T > left, TNode< Uint64T > right) [inline]
Definition at line 1066 of file code-assembler.h.
                                                                    {
    return Signed(Word64Shr(static_cast<TNode<Word64T>>(left), right));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::CodeStubAssembler::LoadBoundedSizeFromObject(), v8::internal::CodeStubAssembler::LoadSwissNameDictionaryCtrlTableGroup(), v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16(), and v8::internal::CodeStubAssembler::TryFloat64ToAdditiveSafeInteger().
Word64Shr() [2/2]
TNode<Uint64T> v8::internal::compiler::CodeAssembler::Word64Shr (TNode< Uint64T > left, TNode< Uint64T > right) [inline]
Definition at line 1069 of file code-assembler.h.
                                                                      {
    return Unsigned(Word64Shr(static_cast<TNode<Word64T>>(left), right));
  }
References v8::base::bits::Unsigned().
Word64Xor() [1/2]
TNode<Int64T> v8::internal::compiler::CodeAssembler::Word64Xor (TNode< Int64T > left, TNode< Int64T > right) [inline]
Definition at line 1083 of file code-assembler.h.
                                                                   {
    return Signed(Word64Xor(static_cast<TNode<Word64T>>(left), right));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16().
Word64Xor() [2/2]
TNode<Uint64T> v8::internal::compiler::CodeAssembler::Word64Xor (TNode< Uint64T > left, TNode< Uint64T > right) [inline]
Definition at line 1086 of file code-assembler.h.
                                                                      {
    return Unsigned(Word64Xor(static_cast<TNode<Word64T>>(left), right));
  }
References v8::base::bits::Unsigned().
WordAnd() [1/2]
TNode<IntPtrT> v8::internal::compiler::CodeAssembler::WordAnd (TNode< IntPtrT > left, TNode< IntPtrT > right) [inline]
Definition at line 1097 of file code-assembler.h.
                                                                    {
    return Signed(WordAnd(static_cast<TNode<WordT>>(left),
                          static_cast<TNode<WordT>>(right)));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::CodeStubAssembler::AlignToAllocationAlignment(), v8::internal::CodeStubAssembler::AllocateByteArray(), v8::internal::CodeStubAssembler::AllocateNonEmptyByteArray(), v8::internal::CodeStubAssembler::AllocateRaw(), v8::internal::MicrotaskQueueBuiltinsAssembler::CalculateRingBufferOffset(), v8::internal::CodeStubAssembler::DecodeWord(), v8::internal::CodeStubAssembler::ExtractToFixedArray(), v8::internal::WeakCollectionsBuiltinsAssembler::FindKeyIndex(), v8::internal::BinaryOpAssembler::Generate_BitwiseBinaryOpWithOptionalFeedback(), v8::internal::CodeStubAssembler::GetHeapObjectAssumeWeak(), v8::internal::CodeStubAssembler::GetMarkBit(), v8::internal::CodeStubAssembler::GotoIfLargeBigInt(), v8::internal::AccessorAssembler::HandleProtoHandler(), v8::internal::CodeStubAssembler::IsMarked(), v8::internal::WriteBarrierCodeStubAssembler::IsUnmarked(), v8::internal::CodeStubAssembler::IsWeakReferenceToObject(), v8::internal::CodeStubAssembler::LoadExternalPointerFromObject(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::NameDictionaryLookup(), v8::internal::CodeStubAssembler::NumberDictionaryLookup(), v8::internal::CodeStubAssembler::PopulationCountFallback(), v8::internal::WriteBarrierCodeStubAssembler::SetBitInCell(), v8::internal::CodeStubAssembler::SharedValueBarrier(), v8::internal::CollectionsBuiltinsAssembler::StoreOrderedHashTableNewEntry(), v8::internal::CodeStubAssembler::StoreSharedObjectField(), v8::internal::StringBuiltinsAssembler::StringEqual_FastLoop(), v8::internal::CodeStubAssembler::SwissNameDictionarySetCtrl(), v8::internal::CodeStubAssembler::TaggedIsPositiveSmi(), v8::internal::CodeStubAssembler::UpdateWord(), and v8::internal::CodeStubAssembler::WordIsPowerOfTwo().
WordAnd() [2/2]
TNode<UintPtrT> v8::internal::compiler::CodeAssembler::WordAnd (TNode< UintPtrT > left, TNode< UintPtrT > right) [inline]
Definition at line 1101 of file code-assembler.h.
                                                                       {
    return Unsigned(WordAnd(static_cast<TNode<WordT>>(left),
                            static_cast<TNode<WordT>>(right)));
  }
References v8::base::bits::Unsigned().
WordEqual()
TNode<BoolT> v8::internal::compiler::CodeAssembler::WordEqual (TNode< WordT > left, TNode< WordT > right)
Referenced by v8::internal::interpreter::InterpreterAssembler::AbortIfWordNotEqual(), v8::internal::CodeStubAssembler::AllocateByteArray(), v8::internal::CodeStubAssembler::AllocateJSArray(), v8::internal::CodeStubAssembler::AllocateUninitializedJSArrayWithElements(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::KeyedStoreGenericAssembler::EmitGenericElementStore(), v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), v8::internal::CodeStubAssembler::ExtractFixedDoubleArrayFillingHoles(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FastGetOwnValuesOrEntries(), v8::internal::RegExpBuiltinsAssembler::FreeRegExpResultVector(), v8::internal::StringBuiltinsAssembler::GenerateSeqStringRelationalComparison(), v8::internal::CodeStubAssembler::GotoIfLargeBigInt(), v8::internal::WriteBarrierCodeStubAssembler::IsUnmarked(), v8::internal::CodeStubAssembler::IsWeakReferenceTo(), v8::internal::CodeStubAssembler::IsWeakReferenceToObject(), v8::internal::WriteBarrierCodeStubAssembler::LoadBucket(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), v8::internal::WriteBarrierCodeStubAssembler::LoadSlotSet(), v8::internal::CodeStubAssembler::NumberDictionaryLookup(), v8::internal::MicrotaskQueueBuiltinsAssembler::PrepareForContext(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::StringBuiltinsAssembler::SearchOneByteInOneByteString(), v8::internal::StringBuiltinsAssembler::StringEqual_Core(), v8::internal::StringBuiltinsAssembler::StringEqual_FastLoop(), v8::internal::StringBuiltinsAssembler::StringEqual_Loop(), v8::internal::StringBuiltinsAssembler::StringToArray(), v8::internal::CodeStubAssembler::SwissNameDictionaryOffsetIntoPropertyDetailsTableMT(), v8::internal::CodeStubAssembler::SwissNameDictionarySetCtrl(), v8::internal::CodeStubAssembler::TaggedIsPositiveSmi(), v8::internal::GrowableFixedArray::ToJSArray(), v8::internal::interpreter::InterpreterAssembler::TraceBytecodeDispatch(), and v8::internal::CodeStubAssembler::UpdateWord().
WordNot()
TNode<IntPtrT> v8::internal::compiler::CodeAssembler::WordNot (TNode< IntPtrT > a) [inline]
Definition at line 1137 of file code-assembler.h.
                                           {
    return Signed(WordNot(static_cast<TNode<WordT>>(a)));
  }
References v8::base::bits::Signed().
WordNotEqual()
TNode<BoolT> v8::internal::compiler::CodeAssembler::WordNotEqual (TNode< WordT > left, TNode< WordT > right)
Referenced by v8::internal::CodeStubAssembler::AllocateNonEmptyByteArray(), v8::internal::CodeStubAssembler::AllocateUninitializedJSArrayWithElements(), v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructDoubleVarargs(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::ConstructorBuiltinsAssembler::CreateShallowObjectLiteral(), v8::internal::CodeStubAssembler::ExtractFixedDoubleArrayFillingHoles(), v8::internal::CodeStubAssembler::ExtractToFixedArray(), v8::internal::ObjectEntriesValuesBuiltinsAssembler::FastGetOwnValuesOrEntries(), v8::internal::RegExpBuiltinsAssembler::FreeRegExpResultVector(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), v8::internal::AccessorAssembler::HandleProtoHandler(), v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase(), v8::internal::CodeStubAssembler::HasAsyncEventDelegate(), v8::internal::CodeStubAssembler::IsMarked(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::NameDictionaryLookupWithForwardIndex(), v8::internal::CodeStubAssembler::SharedValueBarrier(), and v8::internal::CodeStubAssembler::StoreSharedObjectField().
WordOr()
TNode<IntPtrT> v8::internal::compiler::CodeAssembler::WordOr (TNode< IntPtrT > left, TNode< IntPtrT > right) [inline]
Definition at line 1115 of file code-assembler.h.
                                                                   {
    return Signed(WordOr(static_cast<TNode<WordT>>(left),
                         static_cast<TNode<WordT>>(right)));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::BinaryOpAssembler::Generate_BitwiseBinaryOpWithOptionalFeedback(), v8::internal::CodeStubAssembler::IntPtrRoundUpToPowerOfTwo32(), v8::internal::CodeStubAssembler::IsWeakReferenceTo(), v8::internal::CodeStubAssembler::MakeWeak(), v8::internal::WriteBarrierCodeStubAssembler::SetBitInCell(), v8::internal::CodeStubAssembler::StoreExternalPointerToObject(), and v8::internal::CodeStubAssembler::UpdateWord().
WordSar() [1/3]
TNode<IntPtrT> v8::internal::compiler::CodeAssembler::WordSar (TNode< IntPtrT > left, TNode< IntegralT > right) [inline]
Definition at line 1037 of file code-assembler.h.
                                                                      {
    return Signed(WordSar(static_cast<TNode<WordT>>(left), right));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::RegExpBuiltinsAssembler::ConstructNewResultFromMatchInfo(), v8::internal::CodeStubAssembler::SmiToTaggedIndex(), and WordSar().
WordSar() [2/3]
TNode<IntPtrT> v8::internal::compiler::CodeAssembler::WordSar (TNode< IntPtrT > value, int shift) [inline]
Definition at line 1243 of file code-assembler.h.
                                                          {
    return UncheckedCast<IntPtrT>(WordSar(TNode<WordT>(value), shift));
  }
References v8::internal::value.
WordSar() [3/3]
TNode< WordT > v8::internal::compiler::CodeAssembler::WordSar (TNode< WordT > value, int shift)
Definition at line 762 of file code-assembler.cc.
                                                                 {
  return (shift != 0) ? WordSar(value, IntPtrConstant(shift)) : value;
}
References IntPtrConstant(), v8::internal::value, and WordSar().
WordShl() [1/3]
TNode<IntPtrT> v8::internal::compiler::CodeAssembler::WordShl (TNode< IntPtrT > left, TNode< IntegralT > right) [inline]
Definition at line 1040 of file code-assembler.h.
                                                                      {
    return Signed(WordShl(static_cast<TNode<WordT>>(left), right));
  }
References v8::base::bits::Signed().
Referenced by v8::internal::CollectionsBuiltinsAssembler::AddToOrderedHashTable(), v8::internal::CodeStubAssembler::AllocateRawBigInt(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::CodeStubAssembler::GetMarkBit(), v8::internal::CodeStubAssembler::IntPtrToTaggedIndex(), v8::internal::WriteBarrierCodeStubAssembler::LoadBucket(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::WriteBarrierCodeStubAssembler::SetBitInCell(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::CodeStubAssembler::StringCharCodeAt(), v8::internal::StringBuiltinsAssembler::StringEqual_Core(), v8::internal::StringBuiltinsAssembler::StringEqual_FastLoop(), v8::internal::StringBuiltinsAssembler::StringEqual_Loop(), v8::internal::CodeStubAssembler::TaggedIndexToSmi(), v8::internal::CodeStubAssembler::TimesDoubleSize(), v8::internal::CodeStubAssembler::TimesSystemPointerSize(), v8::internal::CodeStubAssembler::TimesTaggedSize(), v8::internal::CodeStubAssembler::UpdateWord(), and WordShl().
WordShl() [2/3]
TNode<UintPtrT> v8::internal::compiler::CodeAssembler::WordShl (TNode< UintPtrT > left, TNode< IntegralT > right) [inline]
Definition at line 1043 of file code-assembler.h.
                                                                        {
    return Unsigned(WordShl(static_cast<TNode<WordT>>(left), right));
  }
References v8::base::bits::Unsigned().
WordShl() [3/3]
TNode< WordT > v8::internal::compiler::CodeAssembler::WordShl (TNode< WordT > value, int shift)
Definition at line 754 of file code-assembler.cc.
                                                                 {
  return (shift != 0) ? WordShl(value, IntPtrConstant(shift)) : value;
}
References IntPtrConstant(), v8::internal::value, and WordShl().
WordShr() [1/3]
TNode<IntPtrT> v8::internal::compiler::CodeAssembler::WordShr (TNode< IntPtrT > value, int shift) [inline]
Definition at line 1240 of file code-assembler.h.
                                                          {
    return UncheckedCast<IntPtrT>(WordShr(TNode<WordT>(value), shift));
  }
References v8::internal::value.
WordShr() [2/3]
TNode<UintPtrT> v8::internal::compiler::CodeAssembler::WordShr (TNode< UintPtrT > left, TNode< IntegralT > right) [inline]
Definition at line 1034 of file code-assembler.h.
                                                                        {
    return Unsigned(WordShr(static_cast<TNode<WordT>>(left), right));
  }
References v8::base::bits::Unsigned().
Referenced by v8::internal::CodeStubAssembler::AllocateOrderedHashTableWithCapacity(), v8::internal::WeakCollectionsBuiltinsAssembler::Coefficient(), v8::internal::RegExpBuiltinsAssembler::ConstructNewResultFromMatchInfo(), v8::internal::CodeStubAssembler::DecodeWord(), v8::internal::CodeStubAssembler::GetMarkBit(), v8::internal::CodeStubAssembler::HashTableComputeCapacity(), v8::internal::CodeStubAssembler::IntPtrRoundUpToPowerOfTwo32(), v8::internal::WriteBarrierCodeStubAssembler::LoadBucket(), v8::internal::CodeStubAssembler::LoadExternalPointerFromObject(), v8::internal::GrowableFixedArray::NewCapacity(), v8::internal::CodeStubAssembler::PopulationCountFallback(), v8::internal::CodeStubAssembler::PrintToStream(), v8::internal::WriteBarrierCodeStubAssembler::SetBitInCell(), v8::internal::WeakCollectionsBuiltinsAssembler::ShouldShrink(), v8::internal::AccessorAssembler::StubCachePrimaryOffset(), and WordShr().
WordShr() [3/3]
TNode< WordT > v8::internal::compiler::CodeAssembler::WordShr (TNode< WordT > value, int shift)
Definition at line 758 of file code-assembler.cc.
                                                                 {
  return (shift != 0) ? WordShr(value, IntPtrConstant(shift)) : value;
}
References IntPtrConstant(), v8::internal::value, and WordShr().
zone()
Zone * v8::internal::compiler::CodeAssembler::zone () const
Definition at line 1673 of file code-assembler.cc.
{ return raw_assembler()->zone(); }
References raw_assembler(), and v8::internal::compiler::RawMachineAssembler::zone().
Referenced by v8::internal::CollectionsBuiltinsAssembler::AddConstructorEntriesFromSet(), v8::internal::StringBuiltinsAssembler::AllocAndCopyStringCharacters(), BreakOnNode(), v8::internal::CodeStubAssembler::BuildAppendJSArray(), CallCFunctionN(), CallRuntimeImpl(), CallStubN(), v8::internal::SlowBoilerplateCloneAssembler::CloneElementsOfFixedArray(), v8::internal::compiler::CodeAssemblerLabel::CodeAssemblerLabel(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::StringBuiltinsAssembler::CopyStringCharacters(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), v8::internal::CodeStubAssembler::ForEachEnumerableOwnProperty(), v8::internal::RegExpBuiltinsAssembler::InitializeMatchInfoFromRegisters(), v8::internal::CollectionsBuiltinsAssembler::MapIteratorToList(), v8::internal::CodeStubAssembler::NameDictionaryLookup(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal(), v8::internal::RegExpBuiltinsAssembler::RegExpReplaceGlobalSimpleString(), v8::internal::StringBuiltinsAssembler::StringEqual_FastLoop(), v8::internal::StringBuiltinsAssembler::StringEqual_Loop(), Switch(), v8::internal::CodeStubAssembler::TaggedToWord32OrBigIntImpl(), TailCallBytecodeDispatch(), TailCallJSCode(), TailCallRuntimeImpl(), TailCallStubImpl(), TailCallStubThenBytecodeDispatchImpl(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), and v8::internal::ArrayBuiltinsAssembler::VisitAllTypedArrayElements().
Member Data Documentation
kTargetParameterIndex
constexpr int v8::internal::compiler::CodeAssembler::kTargetParameterIndex = kJSCallClosureParameterIndex [static], [constexpr]
Definition at line 694 of file code-assembler.h.
Referenced by UntypedParameter().
state_
CodeAssemblerState* v8::internal::compiler::CodeAssembler::state_ [private]
Definition at line 1675 of file code-assembler.h.
Referenced by v8::internal::CodeStubAssembler::AllocateContextCell(), CallEpilogue(), CallPrologue(), CallRuntimeImpl(), GetMacroSourcePositionStack(), HandleException(), IsExceptionHandlerActive(), jsgraph(), PopSourcePosition(), PushSourcePosition(), raw_assembler(), RegisterCallGenerationCallbacks(), TailCallRuntimeImpl(), and UnregisterCallGenerationCallbacks().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/code-assembler.h
/mnt/V8SourceCode/src/compiler/code-assembler.cc