v8::internal::wasm::StoreType Class Reference
#include <value-type.h>
Public Types
enum StoreTypeValue : uint8_t
Public Member Functions
constexpr StoreType (StoreTypeValue val)
constexpr StoreTypeValue value () const
constexpr unsigned size_log_2 () const
constexpr unsigned size () const
constexpr ValueType value_type () const
constexpr MachineRepresentation mem_rep () const
Static Public Member Functions
static StoreType ForValueKind (ValueKind kind)
Private Attributes
StoreTypeValue val_
Static Private Attributes
static constexpr uint8_t kStoreSizeLog2 []
static constexpr ValueType kValueType []
static constexpr MachineRepresentation kMemRep []
Detailed Description
Definition at line 1429 of file value-type.h.
Member Enumeration Documentation
StoreTypeValue
enum v8::internal::wasm::StoreType::StoreTypeValue : uint8_t
Definition at line 1431 of file value-type.h.
                      : uint8_t {
#define DEF_ENUM(type, suffix, ...) k##type##Store##suffix,
    FOREACH_STORE_TYPE(DEF_ENUM)
#undef DEF_ENUM
  };
Constructor & Destructor Documentation
StoreType()
constexpr v8::internal::wasm::StoreType::StoreType (StoreTypeValue val) [inline], [constexpr]
Definition at line 1439 of file value-type.h.
: val_(val) {}
Member Function Documentation
ForValueKind()
static StoreType v8::internal::wasm::StoreType::ForValueKind (ValueKind kind) [inline], [static]
Definition at line 1447 of file value-type.h.
                                                {
    switch (kind) {
      case kI32:
        return kI32Store;
      case kI64:
        return kI64Store;
      case kF32:
        return kF32Store;
      case kF64:
        return kF64Store;
      case kS128:
        return kS128Store;
      case kI8:
        return kI32Store8;
      case kI16:
        return kI32Store16;
      case kF16:
        return kF32StoreF16;
      default:
        UNREACHABLE();
    }
  }
References v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::kS128, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GlobalSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreAtomicObjectField(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreObjectField(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicCompareExchange(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicRMW().
mem_rep()
constexpr MachineRepresentation v8::internal::wasm::StoreType::mem_rep () const [inline], [constexpr]
Definition at line 1445 of file value-type.h.
{ return kMemRep[val_]; }
References kMemRep, and val_.
size()
constexpr unsigned v8::internal::wasm::StoreType::size () const [inline], [constexpr]
Definition at line 1443 of file value-type.h.
{ return 1 << size_log_2(); }
References size_log_2().
size_log_2()
constexpr unsigned v8::internal::wasm::StoreType::size_log_2 () const [inline], [constexpr]
Definition at line 1442 of file value-type.h.
{ return kStoreSizeLog2[val_]; }
References kStoreSizeLog2, and val_.
Referenced by size().
value()
constexpr StoreTypeValue v8::internal::wasm::StoreType::value () const [inline], [constexpr]
Definition at line 1441 of file value-type.h.
{ return val_; }
References val_.
value_type()
constexpr ValueType v8::internal::wasm::StoreType::value_type () const [inline], [constexpr]
Definition at line 1444 of file value-type.h.
{ return kValueType[val_]; }
References kValueType, and val_.
Member Data Documentation
kMemRep
constexpr MachineRepresentation v8::internal::wasm::StoreType::kMemRep [static], [constexpr], [private]
Initial value:
= {
#define MEMREP(_, __, memrep)
  }
Definition at line 1487 of file value-type.h.
Referenced by mem_rep().
kStoreSizeLog2
constexpr uint8_t v8::internal::wasm::StoreType::kStoreSizeLog2 [static], [constexpr], [private]
Initial value:
= {
  
#define STORE_SIZE(_, __, memrep)
  }
Definition at line 1473 of file value-type.h.
Referenced by size_log_2().
kValueType
constexpr ValueType v8::internal::wasm::StoreType::kValueType [static], [constexpr], [private]
Initial value:
= {
#define VALUE_TYPE(type, ...)
  }
Definition at line 1481 of file value-type.h.
Referenced by value_type().
val_
StoreTypeValue v8::internal::wasm::StoreType::val_ [private]
Definition at line 1471 of file value-type.h.
Referenced by mem_rep(), size_log_2(), value(), and value_type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/value-type.h
/mnt/V8SourceCode/src/wasm/wasm-opcodes.cc