v8::internal::wasm::JSToWasmWrapperCompilationUnit Class Reference
#include <function-compiler.h>
Public Member Functions
JSToWasmWrapperCompilationUnit (Isolate *isolate, const CanonicalSig *sig, CanonicalTypeIndex sig_index, bool receiver_is_first_param)
~JSToWasmWrapperCompilationUnit ()
JSToWasmWrapperCompilationUnit (JSToWasmWrapperCompilationUnit &&) V8_NOEXCEPT=default
JSToWasmWrapperCompilationUnit & operator= (JSToWasmWrapperCompilationUnit &&) V8_NOEXCEPT=default
Isolate * isolate () const
void Execute ()
DirectHandle< Code > Finalize ()
const CanonicalSig * sig () const
CanonicalTypeIndex sig_index () const
Static Public Member Functions
static DirectHandle< Code > CompileJSToWasmWrapper (Isolate *isolate, const CanonicalSig *sig, CanonicalTypeIndex sig_index, bool receiver_is_first_param)
Private Attributes
Isolate * isolate_
const CanonicalSig * sig_
CanonicalTypeIndex sig_index_
bool receiver_is_first_param_
std::unique_ptr< OptimizedCompilationJob > job_
Detailed Description
Definition at line 127 of file function-compiler.h.
Constructor & Destructor Documentation
JSToWasmWrapperCompilationUnit() [1/2]
v8::internal::wasm::JSToWasmWrapperCompilationUnit::JSToWasmWrapperCompilationUnit (Isolate * isolate, const CanonicalSig * sig, CanonicalTypeIndex sig_index, bool receiver_is_first_param)
Definition at line 199 of file function-compiler.cc.
    : isolate_(isolate),
      sig_(sig),
      sig_index_(sig_index),
      receiver_is_first_param_(receiver_is_first_param),
      job_(v8_flags.wasm_jitless ? nullptr
                                 : compiler::NewJSToWasmCompilationJob(
                                       isolate, sig, receiver_is_first_param)) {
  if (!v8_flags.wasm_jitless) {
    OptimizedCompilationInfo* info =
        static_cast<compiler::turboshaft::TurboshaftCompilationJob*>(job_.get())
            ->compilation_info();
    if (info->trace_turbo_graph()) {
      // Make sure that code tracer is initialized on the main thread if tracing
      // is enabled.
      isolate->GetCodeTracer();
    }
  }
}
References v8::internal::Isolate::GetCodeTracer(), isolate(), job_, and v8::internal::v8_flags.
 JSToWasmWrapperCompilationUnit()
v8::internal::wasm::JSToWasmWrapperCompilationUnit::~JSToWasmWrapperCompilationUnit () [default]
JSToWasmWrapperCompilationUnit() [2/2]
v8::internal::wasm::JSToWasmWrapperCompilationUnit::JSToWasmWrapperCompilationUnit (JSToWasmWrapperCompilationUnit &&) [default]
Member Function Documentation
CompileJSToWasmWrapper()
DirectHandle< Code > v8::internal::wasm::JSToWasmWrapperCompilationUnit::CompileJSToWasmWrapper (Isolate * isolate, const CanonicalSig * sig, CanonicalTypeIndex sig_index, bool receiver_is_first_param) [static]
Definition at line 263 of file function-compiler.cc.
                                  {
  // Run the compilation unit synchronously.
  JSToWasmWrapperCompilationUnit unit(isolate, sig, sig_index,
                                      receiver_is_first_param);
  unit.Execute();
  return unit.Finalize();
}
References Execute(), Finalize(), isolate(), sig(), and sig_index().
Referenced by v8::internal::WasmExportedFunction::GetWrapper(), and v8::internal::RUNTIME_FUNCTION().
Execute()
void v8::internal::wasm::JSToWasmWrapperCompilationUnit::Execute ()
Definition at line 223 of file function-compiler.cc.
                                             {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
               "wasm.CompileJSToWasmWrapper");
  if (!v8_flags.wasm_jitless) {
    CompilationJob::Status status = job_->ExecuteJob(nullptr);
    CHECK_EQ(status, CompilationJob::SUCCEEDED);
  }
}
References CHECK_EQ, job_, v8::internal::status, v8::internal::CompilationJob::SUCCEEDED, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and v8::internal::v8_flags.
Referenced by CompileJSToWasmWrapper().
Finalize()
DirectHandle< Code > v8::internal::wasm::JSToWasmWrapperCompilationUnit::Finalize ()
Definition at line 232 of file function-compiler.cc.
                                                            {
#if V8_ENABLE_DRUMBRAKE
  if (v8_flags.wasm_jitless) {
    return isolate_->builtins()->code_handle(
        Builtin::kGenericJSToWasmInterpreterWrapper);
  }
#endif // V8_ENABLE_DRUMBRAKE
  CompilationJob::Status status = job_->FinalizeJob(isolate_);
  CHECK_EQ(status, CompilationJob::SUCCEEDED);
  OptimizedCompilationInfo* info =
      static_cast<compiler::turboshaft::TurboshaftCompilationJob*>(job_.get())
          ->compilation_info();
  DirectHandle<Code> code = info->code();
  if (isolate_->IsLoggingCodeCreation()) {
    DirectHandle<String> name = isolate_->factory()->NewStringFromAsciiChecked(
        info->GetDebugName().get());
    PROFILE(isolate_, CodeCreateEvent(LogEventListener::CodeTag::kStub,
                                      Cast<AbstractCode>(code), name));
  }
  // Install the compiled wrapper in the cache now.
  WasmExportWrapperCache::Put(isolate_, sig_index_, receiver_is_first_param_,
                              code);
  Counters* counters = isolate_->counters();
  counters->wasm_generated_code_size()->Increment(code->body_size());
  counters->wasm_reloc_size()->Increment(code->relocation_size());
  counters->wasm_compiled_export_wrapper()->Increment(1);
  return code;
}
References v8::internal::Isolate::builtins(), CHECK_EQ, v8::internal::OptimizedCompilationInfo::code(), code, v8::internal::Builtins::code_handle(), v8::internal::Isolate::counters(), v8::internal::Isolate::factory(), v8::internal::OptimizedCompilationInfo::GetDebugName(), v8::internal::Isolate::IsLoggingCodeCreation(), isolate_, job_, v8::internal::wasm::name(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), PROFILE, v8::internal::wasm::WasmExportWrapperCache::Put(), receiver_is_first_param_, sig_index_, v8::internal::status, v8::internal::CompilationJob::SUCCEEDED, and v8::internal::v8_flags.
Referenced by CompileJSToWasmWrapper().
isolate()
Isolate* v8::internal::wasm::JSToWasmWrapperCompilationUnit::isolate () const [inline]
Definition at line 140 of file function-compiler.h.
{ return isolate_; }
Referenced by CompileJSToWasmWrapper(), and JSToWasmWrapperCompilationUnit().
operator=()
JSToWasmWrapperCompilationUnit& v8::internal::wasm::JSToWasmWrapperCompilationUnit::operator= (JSToWasmWrapperCompilationUnit &&) [default]
sig()
const CanonicalSig* v8::internal::wasm::JSToWasmWrapperCompilationUnit::sig () const [inline]
Definition at line 145 of file function-compiler.h.
{ return sig_; }
Referenced by CompileJSToWasmWrapper().
sig_index()
CanonicalTypeIndex v8::internal::wasm::JSToWasmWrapperCompilationUnit::sig_index () const [inline]
Definition at line 146 of file function-compiler.h.
{ return sig_index_; }
Referenced by CompileJSToWasmWrapper().
Member Data Documentation
isolate_
Isolate* v8::internal::wasm::JSToWasmWrapperCompilationUnit::isolate_ [private]
Definition at line 158 of file function-compiler.h.
Referenced by Finalize().
job_
std::unique_ptr<OptimizedCompilationJob> v8::internal::wasm::JSToWasmWrapperCompilationUnit::job_ [private]
Definition at line 162 of file function-compiler.h.
Referenced by Execute(), Finalize(), and JSToWasmWrapperCompilationUnit().
receiver_is_first_param_
bool v8::internal::wasm::JSToWasmWrapperCompilationUnit::receiver_is_first_param_ [private]
Definition at line 161 of file function-compiler.h.
Referenced by Finalize().
sig_
const CanonicalSig* v8::internal::wasm::JSToWasmWrapperCompilationUnit::sig_ [private]
Definition at line 159 of file function-compiler.h.
sig_index_
CanonicalTypeIndex v8::internal::wasm::JSToWasmWrapperCompilationUnit::sig_index_ [private]
Definition at line 160 of file function-compiler.h.
Referenced by Finalize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/function-compiler.h
/mnt/V8SourceCode/src/wasm/function-compiler.cc