v8::internal::interpreter::SwitchBuilder Class Reference
#include <control-flow-builders.h>
Public Member Functions
SwitchBuilder (BytecodeArrayBuilder *builder, BlockCoverageBuilder *block_coverage_builder, SwitchStatement *statement, int number_of_cases, BytecodeJumpTable *jump_table)
~SwitchBuilder () override
void BindCaseTargetForJumpTable (int case_value, CaseClause *clause)
void BindCaseTargetForCompareJump (int index, CaseClause *clause)
void JumpToCaseIfTrue (BytecodeArrayBuilder::ToBooleanMode mode, int index)
void EmitJumpTableIfExists (int min_case, int max_case, std::map< int, CaseClause * > &covered_cases)
void BindDefault (CaseClause *clause)
void JumpToDefault ()
void JumpToFallThroughIfFalse ()
Private Member Functions
void BuildBlockCoverage (CaseClause *clause)
Private Attributes
ZoneVector< BytecodeLabel > case_sites_
BytecodeLabels default_
BytecodeLabels fall_through_
BytecodeJumpTable * jump_table_
Additional Inherited Members
Detailed Description
Definition at line 151 of file control-flow-builders.h.
Constructor & Destructor Documentation
SwitchBuilder()
v8::internal::interpreter::SwitchBuilder::SwitchBuilder (BytecodeArrayBuilder * builder, BlockCoverageBuilder * block_coverage_builder, SwitchStatement * statement, int number_of_cases, BytecodeJumpTable * jump_table) [inline]
Definition at line 154 of file control-flow-builders.h.
      : BreakableControlFlowBuilder(builder, block_coverage_builder, statement),
        case_sites_(builder->zone()),
        default_(builder->zone()),
        fall_through_(builder->zone()),
        jump_table_(jump_table) {
    case_sites_.resize(number_of_cases);
  }
 SwitchBuilder()
v8::internal::interpreter::SwitchBuilder::~SwitchBuilder () [override]
Definition at line 99 of file control-flow-builders.cc.
                              {
#ifdef DEBUG
  for (auto site : case_sites_) {
    DCHECK(!site.has_referrer_jump() || site.is_bound());
  }
#endif
}
References case_sites_, and v8::internal::DCHECK().
Member Function Documentation
BindCaseTargetForCompareJump()
void v8::internal::interpreter::SwitchBuilder::BindCaseTargetForCompareJump (int index, CaseClause * clause)
Definition at line 113 of file control-flow-builders.cc.
                                                                     {
  builder()->Bind(&case_sites_.at(index));
  BuildBlockCoverage(clause);
}
References v8::internal::interpreter::BytecodeArrayBuilder::Bind(), BuildBlockCoverage(), v8::internal::interpreter::ControlFlowBuilder::builder(), case_sites_, and v8::internal::index.
BindCaseTargetForJumpTable()
void v8::internal::interpreter::SwitchBuilder::BindCaseTargetForJumpTable (int case_value, CaseClause * clause)
Definition at line 107 of file control-flow-builders.cc.
                                                                   {
  builder()->Bind(jump_table_, case_value);
  BuildBlockCoverage(clause);
}
References v8::internal::interpreter::BytecodeArrayBuilder::Bind(), BuildBlockCoverage(), v8::internal::interpreter::ControlFlowBuilder::builder(), and jump_table_.
Referenced by EmitJumpTableIfExists().
BindDefault()
void v8::internal::interpreter::SwitchBuilder::BindDefault (CaseClause * clause)
Definition at line 136 of file control-flow-builders.cc.
                                                  {
  default_.Bind(builder());
  BuildBlockCoverage(clause);
}
References v8::internal::interpreter::BytecodeLabels::Bind(), BuildBlockCoverage(), v8::internal::interpreter::ControlFlowBuilder::builder(), and default_.
BuildBlockCoverage()
void v8::internal::interpreter::SwitchBuilder::BuildBlockCoverage (CaseClause * clause) [inline], [private]
Definition at line 193 of file control-flow-builders.h.
                                              {
    if (block_coverage_builder_ && clause != nullptr) {
      block_coverage_builder_->IncrementBlockCounter(clause,
                                                     SourceRangeKind::kBody);
    }
  }
References v8::internal::kBody.
Referenced by BindCaseTargetForCompareJump(), BindCaseTargetForJumpTable(), and BindDefault().
EmitJumpTableIfExists()
void v8::internal::interpreter::SwitchBuilder::EmitJumpTableIfExists (int min_case, int max_case, std::map< int, CaseClause * > & covered_cases)
Definition at line 125 of file control-flow-builders.cc.
                                                                         {
  builder()->SwitchOnSmiNoFeedback(jump_table_);
  fall_through_.Bind(builder());
  for (int j = min_case; j <= max_case; ++j) {
    if (covered_cases.find(j) == covered_cases.end()) {
      this->BindCaseTargetForJumpTable(j, nullptr);
    }
  }
}
References v8::internal::interpreter::BytecodeLabels::Bind(), BindCaseTargetForJumpTable(), v8::internal::interpreter::ControlFlowBuilder::builder(), fall_through_, jump_table_, and v8::internal::interpreter::BytecodeArrayBuilder::SwitchOnSmiNoFeedback().
JumpToCaseIfTrue()
void v8::internal::interpreter::SwitchBuilder::JumpToCaseIfTrue (BytecodeArrayBuilder::ToBooleanMode mode, int index)
Definition at line 119 of file control-flow-builders.cc.
                                                {
  builder()->JumpIfTrue(mode, &case_sites_.at(index));
}
References v8::internal::interpreter::ControlFlowBuilder::builder(), case_sites_, v8::internal::index, v8::internal::interpreter::BytecodeArrayBuilder::JumpIfTrue(), and mode().
JumpToDefault()
void v8::internal::interpreter::SwitchBuilder::JumpToDefault ()
Definition at line 141 of file control-flow-builders.cc.
{ this->EmitJump(&default_); }
References default_, and v8::internal::interpreter::BreakableControlFlowBuilder::EmitJump().
JumpToFallThroughIfFalse()
void v8::internal::interpreter::SwitchBuilder::JumpToFallThroughIfFalse ()
Definition at line 143 of file control-flow-builders.cc.
                                             {
  this->EmitJumpIfFalse(BytecodeArrayBuilder::ToBooleanMode::kAlreadyBoolean,
                        &fall_through_);
}
References v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfFalse(), fall_through_, and v8::internal::interpreter::BytecodeArrayBuilder::kAlreadyBoolean.
Member Data Documentation
case_sites_
ZoneVector<BytecodeLabel> v8::internal::interpreter::SwitchBuilder::case_sites_ [private]
Definition at line 188 of file control-flow-builders.h.
Referenced by BindCaseTargetForCompareJump(), JumpToCaseIfTrue(), and ~SwitchBuilder().
default_
BytecodeLabels v8::internal::interpreter::SwitchBuilder::default_ [private]
Definition at line 189 of file control-flow-builders.h.
Referenced by BindDefault(), and JumpToDefault().
fall_through_
BytecodeLabels v8::internal::interpreter::SwitchBuilder::fall_through_ [private]
Definition at line 190 of file control-flow-builders.h.
Referenced by EmitJumpTableIfExists(), and JumpToFallThroughIfFalse().
jump_table_
BytecodeJumpTable* v8::internal::interpreter::SwitchBuilder::jump_table_ [private]
Definition at line 191 of file control-flow-builders.h.
Referenced by BindCaseTargetForJumpTable(), and EmitJumpTableIfExists().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/control-flow-builders.h
/mnt/V8SourceCode/src/interpreter/control-flow-builders.cc