v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency Class Reference
Public Member Functions
ObjectSlotValueDependency (HeapObjectRef object, int offset, ObjectRef value)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
Handle< HeapObject > object_
int offset_
Handle< Object > value_
Additional Inherited Members
Detailed Description
Definition at line 1006 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
ObjectSlotValueDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency::ObjectSlotValueDependency (HeapObjectRef object, int offset, ObjectRef value) [inline], [explicit]
Definition at line 1008 of file compilation-dependencies.cc.
      : CompilationDependency(kObjectSlotValue),
        object_(object.object()),
        offset_(offset),
        value_(value.object()) {}
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 1031 of file compilation-dependencies.cc.
                                                                {
    const ObjectSlotValueDependency* const zat = that->AsObjectSlotValue();
    return object_->address() == zat->object_->address() &&
           offset_ == zat->offset_ && value_.address() == zat->value_.address();
  }
References v8::internal::HandleBase::address(), object_, offset_, and value_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 1027 of file compilation-dependencies.cc.
                               {
    return base::hash_combine(object_.address(), offset_, value_.address());
  }
References v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 1023 of file compilation-dependencies.cc.
                                                                               {
  }
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 1015 of file compilation-dependencies.cc.
                                                    {
    PtrComprCageBase cage_base = GetPtrComprCageBase(*object_);
    Tagged<Object> current_value =
        offset_ == HeapObject::kMapOffset
            ? object_->map()
            : TaggedField<Object>::Relaxed_Load(cage_base, *object_, offset_);
    return *value_ == current_value;
  }
References v8::internal::GetPtrComprCageBase(), v8::internal::HeapObject::kMapOffset, and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load().
Member Data Documentation
object_
Handle<HeapObject> v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency::object_ [private]
Definition at line 1037 of file compilation-dependencies.cc.
Referenced by Equals().
offset_
int v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency::offset_ [private]
Definition at line 1038 of file compilation-dependencies.cc.
Referenced by Equals().
value_
Handle<Object> v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency::value_ [private]
Definition at line 1039 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc