v8::internal::wasm::LiftoffRegList Class Reference
#include <liftoff-register.h>
Classes
class Iterator
Public Types
using storage_t = std::conditional_t< use_u16, uint16_t, std::conditional_t< use_u32, uint32_t, uint64_t > >
Public Member Functions
constexpr LiftoffRegList ()=default
template<typename... Regs>
constexpr LiftoffRegList (Regs... regs) requires(std
constexpr Register set (Register reg)
constexpr DoubleRegister set (DoubleRegister reg)
constexpr LiftoffRegister set (LiftoffRegister reg)
constexpr LiftoffRegister clear (LiftoffRegister reg)
constexpr Register clear (Register reg)
constexpr DoubleRegister clear (DoubleRegister reg)
bool has (LiftoffRegister reg) const
bool has (Register reg) const
bool has (DoubleRegister reg) const
constexpr bool is_empty () const
constexpr unsigned GetNumRegsSet () const
constexpr LiftoffRegList operator& (const LiftoffRegList other) const
constexpr LiftoffRegList & operator&= (const LiftoffRegList other)
constexpr LiftoffRegList operator| (const LiftoffRegList other) const
constexpr LiftoffRegList & operator|= (const LiftoffRegList other)
constexpr LiftoffRegList GetAdjacentFpRegsSet () const
constexpr bool HasAdjacentFpRegsSet () const
constexpr LiftoffRegList SpreadSetBitsToAdjacentFpRegs () const
constexpr bool operator== (const LiftoffRegList &) const =default
LiftoffRegister GetFirstRegSet () const
LiftoffRegister GetLastRegSet () const
LiftoffRegList MaskOut (const LiftoffRegList mask) const
RegList GetGpList ()
DoubleRegList GetFpList ()
Iterator begin () const
Iterator end () const
Static Public Member Functions
static constexpr LiftoffRegList FromBits (storage_t bits)
template<storage_t bits>
static constexpr LiftoffRegList FromBits ()
Static Public Attributes
static constexpr bool use_u16 = kAfterMaxLiftoffRegCode <= 16
static constexpr bool use_u32 = !use_u16 && kAfterMaxLiftoffRegCode <= 32
static constexpr storage_t kGpMask
static constexpr storage_t kFpMask
static constexpr uint64_t kEvenFpSetMask
static constexpr uint64_t kOddFpSetMask
Private Member Functions
constexpr LiftoffRegList (storage_t bits)
Private Attributes
storage_t regs_ = 0
Detailed Description
Definition at line 344 of file liftoff-register.h.
Member Typedef Documentation
storage_t
using v8::internal::wasm::LiftoffRegList::storage_t = std::conditional_t<use_u16, uint16_t, std::conditional_t<use_u32, uint32_t, uint64_t> >
Definition at line 350 of file liftoff-register.h.
Constructor & Destructor Documentation
LiftoffRegList() [1/3]
constexpr v8::internal::wasm::LiftoffRegList::LiftoffRegList () [constexpr], [default]
Referenced by FromBits(), GetAdjacentFpRegsSet(), operator&(), and operator|().
LiftoffRegList() [2/3]
template<typename... Regs>
constexpr v8::internal::wasm::LiftoffRegList::LiftoffRegList (Regs... regs) [inline], [explicit], [constexpr]
Definition at line 370 of file liftoff-register.h.
  {
    (..., set(regs));
  }
References set().
LiftoffRegList() [3/3]
constexpr v8::internal::wasm::LiftoffRegList::LiftoffRegList (storage_t bits) [inline], [explicit], [constexpr], [private]
Definition at line 514 of file liftoff-register.h.
: regs_(bits) {}
Member Function Documentation
begin()
LiftoffRegList::Iterator v8::internal::wasm::LiftoffRegList::begin () const [inline]
Definition at line 541 of file liftoff-register.h.
                                                   {
  return Iterator{*this};
}
clear() [1/3]
constexpr DoubleRegister v8::internal::wasm::LiftoffRegList::clear (DoubleRegister reg) [inline], [constexpr]
Definition at line 408 of file liftoff-register.h.
                                                     {
    return clear(LiftoffRegister{reg}).fp();
  }
References clear().
clear() [2/3]
constexpr LiftoffRegister v8::internal::wasm::LiftoffRegList::clear (LiftoffRegister reg) [inline], [constexpr]
Definition at line 396 of file liftoff-register.h.
                                                       {
    if (reg.is_pair()) {
      regs_ &= ~(storage_t{1} << reg.low().liftoff_code());
      regs_ &= ~(storage_t{1} << reg.high().liftoff_code());
    } else {
      regs_ &= ~(storage_t{1} << reg.liftoff_code());
    }
    return reg;
  }
References v8::internal::wasm::LiftoffRegister::high(), v8::internal::wasm::LiftoffRegister::is_pair(), v8::internal::wasm::LiftoffRegister::liftoff_code(), v8::internal::wasm::LiftoffRegister::low(), and regs_.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AtomicBinop(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckHighWordEmptyForTableType(), clear(), v8::internal::wasm::LiftoffAssembler::CacheState::clear_used(), v8::internal::wasm::LiftoffAssembler::CacheState::ClearCacheRegister(), v8::internal::wasm::ParallelMove::ClearExecutedMove(), v8::internal::wasm::LiftoffAssembler::CacheState::dec_used(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryInit(), v8::internal::wasm::LiftoffRegList::Iterator::operator++(), v8::internal::wasm::operator<<(), v8::internal::wasm::LiftoffAssembler::PopRegisters(), v8::internal::wasm::LiftoffAssembler::PushRegisters(), v8::internal::wasm::LiftoffAssembler::RecordSpillsInSafepoint(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StackCheck(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicRMW(), v8::internal::wasm::LiftoffAssembler::CacheState::take_volatile_register(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TierupCheck().
clear() [3/3]
constexpr Register v8::internal::wasm::LiftoffRegList::clear (Register reg) [inline], [constexpr]
Definition at line 405 of file liftoff-register.h.
                                         {
    return clear(LiftoffRegister{reg}).gp();
  }
References clear().
end()
LiftoffRegList::Iterator v8::internal::wasm::LiftoffRegList::end () const [inline]
Definition at line 544 of file liftoff-register.h.
                                                 {
  return Iterator{LiftoffRegList{}};
}
FromBits() [1/2]
template<storage_t bits>
static constexpr LiftoffRegList v8::internal::wasm::LiftoffRegList::FromBits () [inline], [static], [constexpr]
Definition at line 503 of file liftoff-register.h.
                                             {
    static_assert(bits == (bits & (kGpMask | kFpMask)), "illegal reg list");
    return LiftoffRegList{bits};
  }
References kFpMask, and kGpMask.
Referenced by MaskOut(), and SpreadSetBitsToAdjacentFpRegs().
FromBits() [2/2]
static constexpr LiftoffRegList v8::internal::wasm::LiftoffRegList::FromBits (storage_t bits) [inline], [static], [constexpr]
Definition at line 497 of file liftoff-register.h.
                                                           {
    DCHECK_EQ(bits, bits & (kGpMask | kFpMask));
    return LiftoffRegList(bits);
  }
References DCHECK_EQ, kFpMask, kGpMask, and LiftoffRegList().
GetAdjacentFpRegsSet()
constexpr LiftoffRegList v8::internal::wasm::LiftoffRegList::GetAdjacentFpRegsSet () const [inline], [constexpr]
Definition at line 446 of file liftoff-register.h.
                                                        {
    // And regs_ with a right shifted version of itself, so reg[i] is set only
    // if reg[i+1] is set. We only care about the even fp registers.
    storage_t available = (regs_ >> 1) & regs_ & kEvenFpSetMask;
    return LiftoffRegList(available);
  }
References available(), kEvenFpSetMask, LiftoffRegList(), and regs_.
Referenced by HasAdjacentFpRegsSet().
GetFirstRegSet()
LiftoffRegister v8::internal::wasm::LiftoffRegList::GetFirstRegSet () const [inline]
Definition at line 469 of file liftoff-register.h.
                                         {
    V8_ASSUME(regs_ != 0);
    int first_code = base::bits::CountTrailingZeros(regs_);
    return LiftoffRegister::from_liftoff_code(first_code);
  }
References v8::base::bits::CountTrailingZeros(), v8::internal::wasm::LiftoffRegister::from_liftoff_code(), regs_, and V8_ASSUME.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::TempRegisterScope::Acquire(), v8::internal::wasm::ParallelMove::ExecuteMoves(), v8::internal::wasm::LiftoffAssembler::FinishCall(), v8::internal::wasm::LiftoffAssembler::CacheState::GetNextSpillReg(), v8::internal::wasm::LiftoffRegList::Iterator::operator*(), v8::internal::wasm::LiftoffRegList::Iterator::operator++(), v8::internal::wasm::operator<<(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), v8::internal::wasm::LiftoffAssembler::PushRegisters(), and v8::internal::wasm::LiftoffAssembler::CacheState::TrySetCachedInstanceRegister().
GetFpList()
DoubleRegList v8::internal::wasm::LiftoffRegList::GetFpList () [inline]
Definition at line 489 of file liftoff-register.h.
                            {
    return DoubleRegList::FromBits((regs_ & kFpMask) >>
                                   kAfterMaxLiftoffGpRegCode);
  }
References v8::internal::RegListBase< DoubleRegister >::FromBits(), v8::internal::wasm::kAfterMaxLiftoffGpRegCode, kFpMask, and regs_.
GetGpList()
RegList v8::internal::wasm::LiftoffRegList::GetGpList () [inline]
Definition at line 488 of file liftoff-register.h.
{ return RegList::FromBits(regs_ & kGpMask); }
References v8::internal::RegListBase< Register >::FromBits(), kGpMask, and regs_.
Referenced by v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::Acquire(), v8::internal::wasm::LiftoffAssembler::PopRegisters(), and v8::internal::wasm::LiftoffAssembler::PushRegisters().
GetLastRegSet()
LiftoffRegister v8::internal::wasm::LiftoffRegList::GetLastRegSet () const [inline]
Definition at line 475 of file liftoff-register.h.
                                        {
    V8_ASSUME(regs_ != 0);
    int last_code =
        8 * sizeof(regs_) - 1 - base::bits::CountLeadingZeros(regs_);
    return LiftoffRegister::from_liftoff_code(last_code);
  }
References v8::base::bits::CountLeadingZeros(), v8::internal::wasm::LiftoffRegister::from_liftoff_code(), regs_, and V8_ASSUME.
Referenced by v8::internal::wasm::LiftoffAssembler::PopRegisters(), v8::internal::wasm::LiftoffAssembler::RecordSpillsInSafepoint(), and v8::internal::wasm::LiftoffAssembler::SpillAdjacentFpRegisters().
GetNumRegsSet()
constexpr unsigned v8::internal::wasm::LiftoffRegList::GetNumRegsSet () const [inline], [constexpr]
Definition at line 424 of file liftoff-register.h.
                                           {
    return base::bits::CountPopulation(regs_);
  }
References v8::base::bits::CountPopulation(), and regs_.
Referenced by v8::internal::wasm::LiftoffAssembler::RecordSpillsInSafepoint().
has() [1/3]
bool v8::internal::wasm::LiftoffRegList::has (DoubleRegister reg) const [inline]
Definition at line 420 of file liftoff-register.h.
{ return has(LiftoffRegister{reg}); }
References has().
Referenced by has().
has() [2/3]
bool v8::internal::wasm::LiftoffRegList::has (LiftoffRegister reg) const [inline]
Definition at line 412 of file liftoff-register.h.
                                      {
    if (reg.is_pair()) {
      DCHECK_EQ(has(reg.low()), has(reg.high()));
      reg = reg.low();
    }
    return (regs_ & (storage_t{1} << reg.liftoff_code())) != 0;
  }
References DCHECK_EQ, v8::internal::wasm::LiftoffRegister::high(), v8::internal::wasm::LiftoffRegister::is_pair(), v8::internal::wasm::LiftoffRegister::liftoff_code(), v8::internal::wasm::LiftoffRegister::low(), and regs_.
Referenced by v8::internal::wasm::LiftoffAssembler::AtomicCompareExchange(), v8::internal::wasm::liftoff::AtomicOp64(), v8::internal::wasm::ParallelMove::ClearExecutedMove(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_mul(), v8::internal::wasm::ParallelMove::ExecuteMoves(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateOutOfLineCode(), v8::internal::wasm::LiftoffAssembler::CacheState::has_volatile_register(), v8::internal::wasm::LiftoffAssembler::CacheState::is_used(), v8::internal::wasm::ParallelMove::LoadConstant(), v8::internal::wasm::ParallelMove::LoadI64HalfStackSlot(), v8::internal::wasm::ParallelMove::LoadStackSlot(), v8::internal::wasm::LiftoffAssembler::LoadToModifiableRegister(), v8::internal::wasm::ParallelMove::MoveRegister(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopIndexToVarState(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), v8::internal::wasm::LiftoffAssembler::RecordSpillsInSafepoint(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StackCheck(), v8::internal::wasm::LiftoffAssembler::CacheState::take_volatile_register(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TierupCheck(), and v8::internal::wasm::LiftoffAssembler::CacheState::TrySetCachedInstanceRegister().
has() [3/3]
bool v8::internal::wasm::LiftoffRegList::has (Register reg) const [inline]
Definition at line 419 of file liftoff-register.h.
{ return has(LiftoffRegister{reg}); }
References has().
Referenced by has().
HasAdjacentFpRegsSet()
constexpr bool v8::internal::wasm::LiftoffRegList::HasAdjacentFpRegsSet () const [inline], [constexpr]
Definition at line 453 of file liftoff-register.h.
                                              {
    return !GetAdjacentFpRegsSet().is_empty();
  }
References GetAdjacentFpRegsSet(), and is_empty().
Referenced by v8::internal::wasm::LiftoffAssembler::SpillAdjacentFpRegisters().
is_empty()
constexpr bool v8::internal::wasm::LiftoffRegList::is_empty () const [inline], [constexpr]
Definition at line 422 of file liftoff-register.h.
{ return regs_ == 0; }
References regs_.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::TempRegisterScope::Acquire(), v8::internal::wasm::ParallelMove::Execute(), v8::internal::wasm::ParallelMove::ExecuteMoves(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateOutOfLineCode(), v8::internal::wasm::LiftoffAssembler::CacheState::GetNextSpillReg(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffAssembler::CacheState::has_unused_register(), HasAdjacentFpRegsSet(), v8::internal::wasm::operator<<(), v8::internal::wasm::LiftoffAssembler::PopRegisters(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), v8::internal::wasm::LiftoffAssembler::PushRegisters(), v8::internal::wasm::LiftoffAssembler::RecordSpillsInSafepoint(), and v8::internal::wasm::LiftoffAssembler::CacheState::TrySetCachedInstanceRegister().
MaskOut()
LiftoffRegList v8::internal::wasm::LiftoffRegList::MaskOut (const LiftoffRegList mask) const [inline]
Definition at line 482 of file liftoff-register.h.
                                                          {
    // Masking out is guaranteed to return a correct reg list, hence no checks
    // needed.
    return FromBits(regs_ & ~mask.regs_);
  }
References FromBits(), and regs_.
Referenced by v8::internal::wasm::LiftoffAssembler::CacheState::GetNextSpillReg(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffAssembler::CacheState::has_unused_register(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), v8::internal::wasm::LiftoffAssembler::SpillAdjacentFpRegisters(), and v8::internal::wasm::LiftoffAssembler::CacheState::TrySetCachedInstanceRegister().
operator&()
constexpr LiftoffRegList v8::internal::wasm::LiftoffRegList::operator& (const LiftoffRegList other) const [inline], [constexpr]
Definition at line 428 of file liftoff-register.h.
                                                                       {
    return LiftoffRegList(regs_ & other.regs_);
  }
References LiftoffRegList(), and regs_.
operator&=()
constexpr LiftoffRegList& v8::internal::wasm::LiftoffRegList::operator&= (const LiftoffRegList other) [inline], [constexpr]
Definition at line 432 of file liftoff-register.h.
                                                                   {
    regs_ &= other.regs_;
    return *this;
  }
References regs_.
operator==()
constexpr bool v8::internal::wasm::LiftoffRegList::operator== (const LiftoffRegList &) const [constexpr], [default]
operator|()
constexpr LiftoffRegList v8::internal::wasm::LiftoffRegList::operator| (const LiftoffRegList other) const [inline], [constexpr]
Definition at line 437 of file liftoff-register.h.
                                                                       {
    return LiftoffRegList(regs_ | other.regs_);
  }
References LiftoffRegList(), and regs_.
operator|=()
constexpr LiftoffRegList& v8::internal::wasm::LiftoffRegList::operator|= (const LiftoffRegList other) [inline], [constexpr]
Definition at line 441 of file liftoff-register.h.
                                                                   {
    regs_ |= other.regs_;
    return *this;
  }
References regs_.
set() [1/3]
constexpr DoubleRegister v8::internal::wasm::LiftoffRegList::set (DoubleRegister reg) [inline], [constexpr]
Definition at line 382 of file liftoff-register.h.
                                                   {
    return set(LiftoffRegister(reg)).fp();
  }
References set().
set() [2/3]
constexpr LiftoffRegister v8::internal::wasm::LiftoffRegList::set (LiftoffRegister reg) [inline], [constexpr]
Definition at line 386 of file liftoff-register.h.
                                                     {
    if (reg.is_pair()) {
      regs_ |= storage_t{1} << reg.low().liftoff_code();
      regs_ |= storage_t{1} << reg.high().liftoff_code();
    } else {
      regs_ |= storage_t{1} << reg.liftoff_code();
    }
    return reg;
  }
References v8::internal::wasm::LiftoffRegister::high(), v8::internal::wasm::LiftoffRegister::is_pair(), v8::internal::wasm::LiftoffRegister::liftoff_code(), v8::internal::wasm::LiftoffRegister::low(), and regs_.
set() [3/3]
constexpr Register v8::internal::wasm::LiftoffRegList::set (Register reg) [inline], [constexpr]
Definition at line 379 of file liftoff-register.h.
                                       {
    return set(LiftoffRegister(reg)).gp();
  }
Referenced by v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::Acquire(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::TempRegisterScope::AddTempRegisters(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayFill(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayInitSegment(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayLen(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNewSegment(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArraySet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AssertNullTypecheckImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AtomicBinop(), v8::internal::wasm::liftoff::AtomicBinop(), v8::internal::wasm::liftoff::AtomicBinop32(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AtomicCompareExchange(), v8::internal::wasm::LiftoffAssembler::AtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AtomicLoadMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AtomicNotify(), v8::internal::wasm::liftoff::AtomicOp32(), v8::internal::wasm::liftoff::AtomicOp64(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AtomicStoreMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AtomicWait(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BoundsCheckMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnNonNull(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnNull(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrTable(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallDirect(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallRefImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchException(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckMaxSteps(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckS128Nan(), v8::internal::wasm::LiftoffAssembler::CheckStackShrink(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CurrentMemoryPages(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::DataDrop(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ElemDrop(), v8::internal::wasm::LiftoffAssembler::emit_i32_popcnt(), v8::internal::wasm::LiftoffAssembler::emit_i64_popcnt(), v8::internal::wasm::LiftoffAssembler::emit_inc_i32_at(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitIsNull(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitRelaxedLaneSelect(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitSimdFmaOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitSimdFmaOpWithCFallback(), v8::internal::wasm::LiftoffAssembler::FinishCall(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetBaseAndOffsetForImportedMutableExternRefGlobal(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetExceptionProperty(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetExceptionValues(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetGlobalBaseAndOffset(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetRttFromDescriptorOnStack(), v8::internal::wasm::LiftoffAssembler::CacheState::GetTaggedSlotsForOOLCode(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GlobalGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GlobalSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::I31GetS(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::I31GetU(), v8::internal::wasm::LiftoffAssembler::CacheState::inc_used(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::IndexToVarStateSaturating(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Initialize(), LiftoffRegList(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Load32BitExceptionValue(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Load64BitExceptionValue(), v8::internal::wasm::ParallelMove::LoadConstant(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadExceptionValue(), v8::internal::wasm::ParallelMove::LoadI64HalfStackSlot(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadLane(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadSmiConstant(), v8::internal::wasm::ParallelMove::LoadStackSlot(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryCopy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryFill(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryGrow(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryInit(), v8::internal::wasm::LiftoffAssembler::MergeIntoNewState(), v8::internal::wasm::ParallelMove::MoveRegister(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocationsMultiReturn(), v8::internal::wasm::LiftoffAssembler::PatchPrepareStackFrame(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopIndexToVarState(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::PrepareStackTransfers(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefAsNonNull(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefGetDesc(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefTest(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RttCanon(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Select(), set(), v8::internal::wasm::LiftoffAssembler::CacheState::SetCacheRegister(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Simd8x16ShuffleOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp(), v8::internal::wasm::LiftoffAssembler::SpillAdjacentFpRegisters(), v8::internal::wasm::LiftoffAssembler::SpillRegister(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StackCheck(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StartFunctionBody(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreExceptionValue(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreLane(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringAsIter(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringAsWtf16(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringAsWtf8(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringCompare(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringConcat(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf16(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf16Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf8(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf8Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringHash(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringIsUSVSequence(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringMeasureWtf16(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringMeasureWtf8(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringNewWtf16Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringNewWtf8(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringNewWtf8Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewIterAdvance(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewIterNext(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewIterRewind(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewIterSlice(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf16Encode(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf16GetCodeUnit(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf16Slice(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf8Advance(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf8Encode(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf8Slice(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableFill(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableGrow(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableInit(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableSize(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Throw(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TraceMemoryOperation(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::UnOp().
SpreadSetBitsToAdjacentFpRegs()
constexpr LiftoffRegList v8::internal::wasm::LiftoffRegList::SpreadSetBitsToAdjacentFpRegs () const [inline], [constexpr]
Definition at line 460 of file liftoff-register.h.
                                                                 {
    storage_t odd_regs = regs_ & kOddFpSetMask;
    storage_t even_regs = regs_ & kEvenFpSetMask;
    return FromBits(regs_ | ((odd_regs >> 1) & kFpMask) |
                    ((even_regs << 1) & kFpMask));
  }
References FromBits(), kEvenFpSetMask, kFpMask, kOddFpSetMask, and regs_.
Referenced by v8::internal::wasm::LiftoffAssembler::SpillAdjacentFpRegisters().
Member Data Documentation
kEvenFpSetMask
constexpr uint64_t v8::internal::wasm::LiftoffRegList::kEvenFpSetMask [static], [constexpr]
Initial value:
= uint64_t{0x5555555555555555}
                                             << kAfterMaxLiftoffGpRegCode
Definition at line 360 of file liftoff-register.h.
Referenced by GetAdjacentFpRegsSet(), and SpreadSetBitsToAdjacentFpRegs().
kFpMask
constexpr storage_t v8::internal::wasm::LiftoffRegList::kFpMask [static], [constexpr]
Initial value:
=
      storage_t{kLiftoffAssemblerFpCacheRegs.bits()}
      << kAfterMaxLiftoffGpRegCode
Definition at line 356 of file liftoff-register.h.
Referenced by FromBits(), GetFpList(), and SpreadSetBitsToAdjacentFpRegs().
kGpMask
constexpr storage_t v8::internal::wasm::LiftoffRegList::kGpMask [static], [constexpr]
Initial value:
=
      storage_t{kLiftoffAssemblerGpCacheRegs.bits()}
Definition at line 354 of file liftoff-register.h.
Referenced by FromBits(), and GetGpList().
kOddFpSetMask
constexpr uint64_t v8::internal::wasm::LiftoffRegList::kOddFpSetMask [static], [constexpr]
Initial value:
= uint64_t{0xAAAAAAAAAAAAAAAA}
                                            << kAfterMaxLiftoffGpRegCode
Definition at line 362 of file liftoff-register.h.
Referenced by SpreadSetBitsToAdjacentFpRegs().
regs_
storage_t v8::internal::wasm::LiftoffRegList::regs_ = 0 [private]
Definition at line 516 of file liftoff-register.h.
Referenced by clear(), GetAdjacentFpRegsSet(), GetFirstRegSet(), GetFpList(), GetGpList(), GetLastRegSet(), GetNumRegsSet(), has(), is_empty(), MaskOut(), operator&(), operator&=(), operator|(), operator|=(), set(), and SpreadSetBitsToAdjacentFpRegs().
use_u16
constexpr bool v8::internal::wasm::LiftoffRegList::use_u16 = kAfterMaxLiftoffRegCode <= 16 [static], [constexpr]
Definition at line 348 of file liftoff-register.h.
use_u32
constexpr bool v8::internal::wasm::LiftoffRegList::use_u32 = !use_u16 && kAfterMaxLiftoffRegCode <= 32 [static], [constexpr]
Definition at line 349 of file liftoff-register.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/baseline/liftoff-register.h