v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode Class Reference
Public Member Functions
BytecodeSequenceNode (int bytecode, Zone *zone)
BytecodeSequenceNode & FollowedBy (int bytecode)
BytecodeSequenceNode & ReplaceWith (int bytecode)
BytecodeSequenceNode & MapArgument (int bytecode_index_in_sequence, int argument_offset, int argument_byte_length, int new_argument_byte_length=0)
BytecodeSequenceNode & IfArgumentEqualsOffset (int argument_offset, int argument_byte_length, int check_byte_offset)
BytecodeSequenceNode & IfArgumentEqualsValueAtOffset (int argument_offset, int argument_byte_length, int other_bytecode_index_in_sequence, int other_argument_offset, int other_argument_byte_length)
BytecodeSequenceNode & IgnoreArgument (int bytecode_index_in_sequence, int argument_offset, int argument_byte_length)
bool CheckArguments (const uint8_t *bytecode, int pc)
bool IsSequence () const
int SequenceLength () const
int OptimizedBytecode () const
BytecodeSequenceNode * Find (int bytecode) const
size_t ArgumentSize () const
BytecodeArgumentMapping ArgumentMapping (size_t index) const
ZoneLinkedList< BytecodeArgument >::iterator ArgumentIgnoredBegin () const
ZoneLinkedList< BytecodeArgument >::iterator ArgumentIgnoredEnd () const
bool HasIgnoredArguments () const
Static Public Attributes
static constexpr int kDummyBytecode = -1
Private Member Functions
BytecodeSequenceNode & GetNodeByIndexInSequence (int index_in_sequence)
Zone * zone () const
Private Attributes
int bytecode_
int bytecode_replacement_
int index_in_sequence_
int start_offset_
BytecodeSequenceNode * parent_
ZoneUnorderedMap< int, BytecodeSequenceNode * > children_
ZoneVector< BytecodeArgumentMapping > * argument_mapping_
ZoneLinkedList< BytecodeArgumentCheck > * argument_check_
ZoneLinkedList< BytecodeArgument > * argument_ignored_
Zone * zone_
Detailed Description
Definition at line 53 of file regexp-bytecode-peephole.cc.
Constructor & Destructor Documentation
BytecodeSequenceNode()
v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::BytecodeSequenceNode (int bytecode, Zone * zone)
Definition at line 276 of file regexp-bytecode-peephole.cc.
    : bytecode_(bytecode),
      bytecode_replacement_(kDummyBytecode),
      index_in_sequence_(0),
      start_offset_(0),
      parent_(nullptr),
      children_(ZoneUnorderedMap<int, BytecodeSequenceNode*>(zone)),
      argument_mapping_(zone->New<ZoneVector<BytecodeArgumentMapping>>(zone)),
      argument_check_(zone->New<ZoneLinkedList<BytecodeArgumentCheck>>(zone)),
      argument_ignored_(zone->New<ZoneLinkedList<BytecodeArgument>>(zone)),
      zone_(zone) {}
Member Function Documentation
ArgumentIgnoredBegin()
ZoneLinkedList< BytecodeArgument >::iterator v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::ArgumentIgnoredBegin () const
Definition at line 441 of file regexp-bytecode-peephole.cc.
                                                 {
  DCHECK(IsSequence());
  DCHECK(argument_ignored_ != nullptr);
  return argument_ignored_->begin();
}
References argument_ignored_, v8::internal::DCHECK(), and IsSequence().
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::EmitOptimization().
ArgumentIgnoredEnd()
ZoneLinkedList< BytecodeArgument >::iterator v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::ArgumentIgnoredEnd () const
Definition at line 448 of file regexp-bytecode-peephole.cc.
                                               {
  DCHECK(IsSequence());
  DCHECK(argument_ignored_ != nullptr);
  return argument_ignored_->end();
}
References argument_ignored_, v8::internal::DCHECK(), and IsSequence().
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::EmitOptimization().
ArgumentMapping()
BytecodeArgumentMapping v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::ArgumentMapping (size_t index) const
Definition at line 431 of file regexp-bytecode-peephole.cc.
                        {
  DCHECK(IsSequence());
  DCHECK(argument_mapping_ != nullptr);
  DCHECK_LT(index, argument_mapping_->size());
  return argument_mapping_->at(index);
}
References argument_mapping_, v8::internal::DCHECK(), DCHECK_LT, v8::internal::index, and IsSequence().
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::EmitOptimization().
ArgumentSize()
size_t v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::ArgumentSize () const
Definition at line 426 of file regexp-bytecode-peephole.cc.
                                                {
  DCHECK(IsSequence());
  return argument_mapping_->size();
}
References argument_mapping_, v8::internal::DCHECK(), and IsSequence().
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::EmitOptimization().
CheckArguments()
bool v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::CheckArguments (const uint8_t * bytecode, int pc)
Definition at line 389 of file regexp-bytecode-peephole.cc.
                                                                         {
  bool is_valid = true;
  for (auto check_iter = argument_check_->begin();
       check_iter != argument_check_->end() && is_valid; check_iter++) {
    auto value =
        GetArgumentValue(bytecode, pc + check_iter->offset, check_iter->length);
    if (check_iter->type == BytecodeArgumentCheck::kCheckAddress) {
      is_valid &= value == pc + check_iter->check_offset;
    } else if (check_iter->type == BytecodeArgumentCheck::kCheckValue) {
      auto other_value = GetArgumentValue(
          bytecode, pc + check_iter->check_offset, check_iter->check_length);
      is_valid &= value == other_value;
    } else {
      UNREACHABLE();
    }
  }
  return is_valid;
}
References argument_check_, v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::GetArgumentValue(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeArgumentCheck::kCheckAddress, v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeArgumentCheck::kCheckValue, v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::TryOptimizeSequence().
Find()
BytecodeSequenceNode * v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::Find (int bytecode) const
Definition at line 420 of file regexp-bytecode-peephole.cc.
                                                                   {
  auto found = children_.find(bytecode);
  if (found == children_.end()) return nullptr;
  return found->second;
}
References children_.
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::TryOptimizeSequence().
FollowedBy()
BytecodeSequenceNode & v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::FollowedBy (int bytecode)
Definition at line 288 of file regexp-bytecode-peephole.cc.
                                                                   {
  DCHECK(0 <= bytecode && bytecode < kRegExpBytecodeCount);
  if (children_.find(bytecode) == children_.end()) {
    BytecodeSequenceNode* new_node =
        zone()->New<BytecodeSequenceNode>(bytecode, zone());
    // If node is not the first in the sequence, set offsets and parent.
    if (bytecode_ != kDummyBytecode) {
      new_node->start_offset_ = start_offset_ + RegExpBytecodeLength(bytecode_);
      new_node->index_in_sequence_ = index_in_sequence_ + 1;
      new_node->parent_ = this;
    }
    children_[bytecode] = new_node;
  }
  return *children_[bytecode];
}
References bytecode_, children_, v8::internal::DCHECK(), index_in_sequence_, kDummyBytecode, v8::internal::kRegExpBytecodeCount, v8::internal::Zone::New(), parent_, v8::internal::RegExpBytecodeLength(), start_offset_, and zone().
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::CreateSequence(), and v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::DefineStandardSequences().
GetNodeByIndexInSequence()
BytecodeSequenceNode & v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::GetNodeByIndexInSequence (int index_in_sequence) [private]
Definition at line 458 of file regexp-bytecode-peephole.cc.
                           {
  DCHECK_LE(index_in_sequence, index_in_sequence_);
  if (index_in_sequence < index_in_sequence_) {
    DCHECK(parent_ != nullptr);
    return parent_->GetNodeByIndexInSequence(index_in_sequence);
  } else {
    return *this;
  }
}
References v8::internal::DCHECK(), DCHECK_LE, GetNodeByIndexInSequence(), index_in_sequence_, and parent_.
Referenced by GetNodeByIndexInSequence(), IfArgumentEqualsValueAtOffset(), IgnoreArgument(), and MapArgument().
HasIgnoredArguments()
bool v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::HasIgnoredArguments () const
Definition at line 454 of file regexp-bytecode-peephole.cc.
                                                     {
  return argument_ignored_ != nullptr;
}
References argument_ignored_.
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::EmitOptimization().
IfArgumentEqualsOffset()
BytecodeSequenceNode & v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::IfArgumentEqualsOffset (int argument_offset, int argument_byte_length, int check_byte_offset)
Definition at line 335 of file regexp-bytecode-peephole.cc.
                                                                          {
  DCHECK_LT(argument_offset, RegExpBytecodeLength(bytecode_));
  DCHECK(argument_byte_length == 1 || argument_byte_length == 2 ||
         argument_byte_length == 4);
  int absolute_offset = start_offset_ + argument_offset;
  argument_check_->push_back(BytecodeArgumentCheck{
      absolute_offset, argument_byte_length, check_byte_offset});
  return *this;
}
References argument_check_, bytecode_, v8::internal::DCHECK(), DCHECK_LT, v8::internal::RegExpBytecodeLength(), and start_offset_.
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::DefineStandardSequences().
IfArgumentEqualsValueAtOffset()
BytecodeSequenceNode & v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::IfArgumentEqualsValueAtOffset (int argument_offset, int argument_byte_length, int other_bytecode_index_in_sequence, int other_argument_offset, int other_argument_byte_length)
Definition at line 349 of file regexp-bytecode-peephole.cc.
                                    {
  DCHECK_LT(argument_offset, RegExpBytecodeLength(bytecode_));
  DCHECK_LE(other_bytecode_index_in_sequence, index_in_sequence_);
  DCHECK_EQ(argument_byte_length, other_argument_byte_length);
  BytecodeSequenceNode& ref_node =
      GetNodeByIndexInSequence(other_bytecode_index_in_sequence);
  DCHECK_LT(other_argument_offset, RegExpBytecodeLength(ref_node.bytecode_));
  int absolute_offset = start_offset_ + argument_offset;
  int other_absolute_offset = ref_node.start_offset_ + other_argument_offset;
  argument_check_->push_back(
      BytecodeArgumentCheck{absolute_offset, argument_byte_length,
                            other_absolute_offset, other_argument_byte_length});
  return *this;
}
References argument_check_, bytecode_, DCHECK_EQ, DCHECK_LE, DCHECK_LT, GetNodeByIndexInSequence(), index_in_sequence_, v8::internal::RegExpBytecodeLength(), and start_offset_.
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::DefineStandardSequences().
IgnoreArgument()
BytecodeSequenceNode & v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::IgnoreArgument (int bytecode_index_in_sequence, int argument_offset, int argument_byte_length)
Definition at line 371 of file regexp-bytecode-peephole.cc.
                              {
  DCHECK(IsSequence());
  DCHECK_LE(bytecode_index_in_sequence, index_in_sequence_);
  BytecodeSequenceNode& ref_node =
      GetNodeByIndexInSequence(bytecode_index_in_sequence);
  DCHECK_LT(argument_offset, RegExpBytecodeLength(ref_node.bytecode_));
  int absolute_offset = ref_node.start_offset_ + argument_offset;
  argument_ignored_->push_back(
      BytecodeArgument{absolute_offset, argument_byte_length});
  return *this;
}
References argument_ignored_, bytecode_, v8::internal::DCHECK(), DCHECK_LE, DCHECK_LT, GetNodeByIndexInSequence(), index_in_sequence_, IsSequence(), v8::internal::RegExpBytecodeLength(), and start_offset_.
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::DefineStandardSequences().
IsSequence()
bool v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::IsSequence () const
Definition at line 408 of file regexp-bytecode-peephole.cc.
                                            {
  return bytecode_replacement_ != kDummyBytecode;
}
References bytecode_replacement_, and kDummyBytecode.
Referenced by ArgumentIgnoredBegin(), ArgumentIgnoredEnd(), ArgumentMapping(), ArgumentSize(), IgnoreArgument(), MapArgument(), and v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::TryOptimizeSequence().
MapArgument()
BytecodeSequenceNode & v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::MapArgument (int bytecode_index_in_sequence, int argument_offset, int argument_byte_length, int new_argument_byte_length = 0)
Definition at line 314 of file regexp-bytecode-peephole.cc.
                                                            {
  DCHECK(IsSequence());
  DCHECK_LE(bytecode_index_in_sequence, index_in_sequence_);
  BytecodeSequenceNode& ref_node =
      GetNodeByIndexInSequence(bytecode_index_in_sequence);
  DCHECK_LT(argument_offset, RegExpBytecodeLength(ref_node.bytecode_));
  int absolute_offset = ref_node.start_offset_ + argument_offset;
  if (new_argument_byte_length == 0) {
    new_argument_byte_length = argument_byte_length;
  }
  argument_mapping_->push_back(BytecodeArgumentMapping{
      absolute_offset, argument_byte_length, new_argument_byte_length});
  return *this;
}
References argument_mapping_, bytecode_, v8::internal::DCHECK(), DCHECK_LE, DCHECK_LT, GetNodeByIndexInSequence(), index_in_sequence_, IsSequence(), v8::internal::RegExpBytecodeLength(), and start_offset_.
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::DefineStandardSequences().
OptimizedBytecode()
int v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::OptimizedBytecode () const
Definition at line 416 of file regexp-bytecode-peephole.cc.
                                                  {
  return bytecode_replacement_;
}
References bytecode_replacement_.
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::EmitOptimization().
ReplaceWith()
BytecodeSequenceNode & v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::ReplaceWith (int bytecode)
Definition at line 306 of file regexp-bytecode-peephole.cc.
                                                                    {
  DCHECK(0 <= bytecode && bytecode < kRegExpBytecodeCount);
  bytecode_replacement_ = bytecode;
  return *this;
}
References bytecode_replacement_, v8::internal::DCHECK(), and v8::internal::kRegExpBytecodeCount.
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::DefineStandardSequences().
SequenceLength()
int v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::SequenceLength () const
Definition at line 412 of file regexp-bytecode-peephole.cc.
                                               {
  return start_offset_ + RegExpBytecodeLength(bytecode_);
}
References bytecode_, v8::internal::RegExpBytecodeLength(), and start_offset_.
Referenced by v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::EmitOptimization(), and v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::TryOptimizeSequence().
zone()
Zone * v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::zone () const [private]
Definition at line 470 of file regexp-bytecode-peephole.cc.
{ return zone_; }
References zone_.
Referenced by FollowedBy().
Member Data Documentation
argument_check_
ZoneLinkedList<BytecodeArgumentCheck>* v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::argument_check_ [private]
Definition at line 161 of file regexp-bytecode-peephole.cc.
Referenced by CheckArguments(), IfArgumentEqualsOffset(), and IfArgumentEqualsValueAtOffset().
argument_ignored_
ZoneLinkedList<BytecodeArgument>* v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::argument_ignored_ [private]
Definition at line 162 of file regexp-bytecode-peephole.cc.
Referenced by ArgumentIgnoredBegin(), ArgumentIgnoredEnd(), HasIgnoredArguments(), and IgnoreArgument().
argument_mapping_
ZoneVector<BytecodeArgumentMapping>* v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::argument_mapping_ [private]
Definition at line 160 of file regexp-bytecode-peephole.cc.
Referenced by ArgumentMapping(), ArgumentSize(), and MapArgument().
bytecode_
int v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::bytecode_ [private]
Definition at line 154 of file regexp-bytecode-peephole.cc.
Referenced by FollowedBy(), IfArgumentEqualsOffset(), IfArgumentEqualsValueAtOffset(), IgnoreArgument(), MapArgument(), and SequenceLength().
bytecode_replacement_
int v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::bytecode_replacement_ [private]
Definition at line 155 of file regexp-bytecode-peephole.cc.
Referenced by IsSequence(), OptimizedBytecode(), and ReplaceWith().
children_
ZoneUnorderedMap<int, BytecodeSequenceNode*> v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::children_ [private]
Definition at line 159 of file regexp-bytecode-peephole.cc.
Referenced by Find(), and FollowedBy().
index_in_sequence_
int v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::index_in_sequence_ [private]
Definition at line 156 of file regexp-bytecode-peephole.cc.
Referenced by FollowedBy(), GetNodeByIndexInSequence(), IfArgumentEqualsValueAtOffset(), IgnoreArgument(), and MapArgument().
kDummyBytecode
constexpr int v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::kDummyBytecode = -1 [static], [constexpr]
Definition at line 57 of file regexp-bytecode-peephole.cc.
Referenced by FollowedBy(), and IsSequence().
parent_
BytecodeSequenceNode* v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::parent_ [private]
Definition at line 158 of file regexp-bytecode-peephole.cc.
Referenced by FollowedBy(), and GetNodeByIndexInSequence().
start_offset_
int v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::start_offset_ [private]
Definition at line 157 of file regexp-bytecode-peephole.cc.
Referenced by FollowedBy(), IfArgumentEqualsOffset(), IfArgumentEqualsValueAtOffset(), IgnoreArgument(), MapArgument(), and SequenceLength().
zone_
Zone* v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::zone_ [private]
Definition at line 164 of file regexp-bytecode-peephole.cc.
Referenced by zone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-bytecode-peephole.cc