v8::internal::interpreter::BytecodeArrayBuilder Class Reference
#include <bytecode-array-builder.h>
Public Types
enum ContextSlotMutability { kImmutableSlot
, kMutableSlot
 }
enum class ToBooleanMode { kConvertToBoolean
, kAlreadyBoolean
 }
enum NilValue { kNullValue
, kUndefinedValue
 }
Public Member Functions
BytecodeArrayBuilder (Zone *zone, int parameter_count, int locals_count, FeedbackVectorSpec *feedback_vector_spec=nullptr, SourcePositionTableBuilder::RecordingMode source_position_mode=SourcePositionTableBuilder::RECORD_SOURCE_POSITIONS)
BytecodeArrayBuilder (const BytecodeArrayBuilder &)=delete
BytecodeArrayBuilder & operator= (const BytecodeArrayBuilder &)=delete
template<typename IsolateT >
Handle< BytecodeArray > ToBytecodeArray (IsolateT *isolate)
template<typename IsolateT >
DirectHandle< TrustedByteArray > ToSourcePositionTable (IsolateT *isolate)
uint16_t parameter_count () const
uint16_t max_arguments () const
void UpdateMaxArguments (uint16_t max_arguments)
int locals_count () const
int fixed_register_count () const
int total_register_count () const
Register Local (int index) const
Register Parameter (int parameter_index) const
Register Receiver () const
BytecodeArrayBuilder & LoadConstantPoolEntry (size_t entry)
BytecodeArrayBuilder & LoadLiteral (Tagged< Smi > value)
BytecodeArrayBuilder & LoadLiteral (double value)
BytecodeArrayBuilder & LoadLiteral (const AstRawString *raw_string)
BytecodeArrayBuilder & LoadLiteral (const AstConsString *cons_string)
BytecodeArrayBuilder & LoadLiteral (const Scope *scope)
BytecodeArrayBuilder & LoadLiteral (AstBigInt bigint)
BytecodeArrayBuilder & LoadUndefined ()
BytecodeArrayBuilder & LoadNull ()
BytecodeArrayBuilder & LoadTheHole ()
BytecodeArrayBuilder & LoadTrue ()
BytecodeArrayBuilder & LoadFalse ()
BytecodeArrayBuilder & LoadBoolean (bool value)
BytecodeArrayBuilder & LoadGlobal (const AstRawString *name, int feedback_slot, TypeofMode typeof_mode)
BytecodeArrayBuilder & StoreGlobal (const AstRawString *name, int feedback_slot)
BytecodeArrayBuilder & LoadContextSlot (Register context, Variable *variable, int depth, ContextSlotMutability immutable)
BytecodeArrayBuilder & StoreContextSlot (Register context, Variable *variable, int depth)
BytecodeArrayBuilder & LoadModuleVariable (int cell_index, int depth)
BytecodeArrayBuilder & StoreModuleVariable (int cell_index, int depth)
BytecodeArrayBuilder & LoadAccumulatorWithRegister (Register reg)
BytecodeArrayBuilder & StoreAccumulatorInRegister (Register reg)
BytecodeArrayBuilder & MoveRegister (Register from, Register to)
BytecodeArrayBuilder & LoadNamedProperty (Register object, const AstRawString *name, int feedback_slot)
BytecodeArrayBuilder & LoadNamedPropertyFromSuper (Register object, const AstRawString *name, int feedback_slot)
BytecodeArrayBuilder & LoadKeyedProperty (Register object, int feedback_slot)
BytecodeArrayBuilder & LoadEnumeratedKeyedProperty (Register object, Register enum_index, Register cache_type, int feedback_slot)
BytecodeArrayBuilder & LoadIteratorProperty (Register object, int feedback_slot)
BytecodeArrayBuilder & GetIterator (Register object, int load_feedback_slot, int call_feedback_slot)
BytecodeArrayBuilder & LoadAsyncIteratorProperty (Register object, int feedback_slot)
BytecodeArrayBuilder & DefineKeyedOwnPropertyInLiteral (Register object, Register name, DefineKeyedOwnPropertyInLiteralFlags flags, int feedback_slot)
BytecodeArrayBuilder & SetNamedProperty (Register object, const AstRawString *name, int feedback_slot, LanguageMode language_mode)
BytecodeArrayBuilder & SetNamedProperty (Register object, size_t constant_pool_entry, int feedback_slot, LanguageMode language_mode)
BytecodeArrayBuilder & DefineNamedOwnProperty (Register object, const AstRawString *name, int feedback_slot)
BytecodeArrayBuilder & SetKeyedProperty (Register object, Register key, int feedback_slot, LanguageMode language_mode)
BytecodeArrayBuilder & DefineKeyedOwnProperty (Register object, Register key, DefineKeyedOwnPropertyFlags flags, int feedback_slot)
BytecodeArrayBuilder & StoreInArrayLiteral (Register array, Register index, int feedback_slot)
BytecodeArrayBuilder & StoreClassFieldsInitializer (Register constructor, int feedback_slot)
BytecodeArrayBuilder & LoadClassFieldsInitializer (Register constructor, int feedback_slot)
BytecodeArrayBuilder & LoadLookupSlot (const AstRawString *name, TypeofMode typeof_mode)
BytecodeArrayBuilder & LoadLookupContextSlot (const AstRawString *name, TypeofMode typeof_mode, ContextMode context_mode, int slot_index, int depth)
BytecodeArrayBuilder & LoadLookupGlobalSlot (const AstRawString *name, TypeofMode typeof_mode, int feedback_slot, int depth)
BytecodeArrayBuilder & StoreLookupSlot (const AstRawString *name, LanguageMode language_mode, LookupHoistingMode lookup_hoisting_mode)
BytecodeArrayBuilder & CreateClosure (size_t shared_function_info_entry, int slot, int flags)
BytecodeArrayBuilder & CreateBlockContext (const Scope *scope)
BytecodeArrayBuilder & CreateCatchContext (Register exception, const Scope *scope)
BytecodeArrayBuilder & CreateFunctionContext (const Scope *scope, int slots)
BytecodeArrayBuilder & CreateEvalContext (const Scope *scope, int slots)
BytecodeArrayBuilder & CreateWithContext (Register object, const Scope *scope)
BytecodeArrayBuilder & CreateArguments (CreateArgumentsType type)
BytecodeArrayBuilder & CreateRegExpLiteral (const AstRawString *pattern, int literal_index, int flags)
BytecodeArrayBuilder & CreateArrayLiteral (size_t constant_elements_entry, int literal_index, int flags)
BytecodeArrayBuilder & CreateEmptyArrayLiteral (int literal_index)
BytecodeArrayBuilder & CreateArrayFromIterable ()
BytecodeArrayBuilder & CreateObjectLiteral (size_t constant_properties_entry, int literal_index, int flags)
BytecodeArrayBuilder & CreateEmptyObjectLiteral ()
BytecodeArrayBuilder & CloneObject (Register source, int flags, int feedback_slot)
BytecodeArrayBuilder & GetTemplateObject (size_t template_object_description_entry, int feedback_slot)
BytecodeArrayBuilder & PushContext (Register context)
BytecodeArrayBuilder & PopContext (Register context)
BytecodeArrayBuilder & CallProperty (Register callable, RegisterList args, int feedback_slot)
BytecodeArrayBuilder & CallUndefinedReceiver (Register callable, RegisterList args, int feedback_slot)
BytecodeArrayBuilder & CallAnyReceiver (Register callable, RegisterList args, int feedback_slot)
BytecodeArrayBuilder & TailCall (Register callable, RegisterList args, int feedback_slot)
BytecodeArrayBuilder & CallWithSpread (Register callable, RegisterList args, int feedback_slot)
BytecodeArrayBuilder & Construct (Register constructor, RegisterList args, int feedback_slot)
BytecodeArrayBuilder & ConstructWithSpread (Register constructor, RegisterList args, int feedback_slot)
BytecodeArrayBuilder & ConstructForwardAllArgs (Register constructor, int feedback_slot)
BytecodeArrayBuilder & CallRuntime (Runtime::FunctionId function_id, RegisterList args)
BytecodeArrayBuilder & CallRuntime (Runtime::FunctionId function_id, Register arg)
BytecodeArrayBuilder & CallRuntime (Runtime::FunctionId function_id)
BytecodeArrayBuilder & CallRuntimeForPair (Runtime::FunctionId function_id, RegisterList args, RegisterList return_pair)
BytecodeArrayBuilder & CallRuntimeForPair (Runtime::FunctionId function_id, Register arg, RegisterList return_pair)
BytecodeArrayBuilder & CallJSRuntime (int context_index, RegisterList args)
BytecodeArrayBuilder & BinaryOperation (Token::Value binop, Register reg, int feedback_slot)
BytecodeArrayBuilder & Add_StringConstant_Internalize (Token::Value binop, Register reg, int feedback_slot, AddStringConstantAndInternalizeVariant as_variant)
BytecodeArrayBuilder & BinaryOperationSmiLiteral (Token::Value binop, Tagged< Smi > literal, int feedback_slot)
BytecodeArrayBuilder & UnaryOperation (Token::Value op, int feedback_slot)
BytecodeArrayBuilder & LogicalNot (ToBooleanMode mode)
BytecodeArrayBuilder & TypeOf (int feedback_slot)
BytecodeArrayBuilder & GetSuperConstructor (Register out)
BytecodeArrayBuilder & FindNonDefaultConstructorOrConstruct (Register this_function, Register new_target, RegisterList output)
BytecodeArrayBuilder & Delete (Register object, LanguageMode language_mode)
BytecodeArrayBuilder & CompareOperation (Token::Value op, Register reg, int feedback_slot)
BytecodeArrayBuilder & CompareReference (Register reg)
BytecodeArrayBuilder & CompareUndetectable ()
BytecodeArrayBuilder & CompareUndefined ()
BytecodeArrayBuilder & CompareNull ()
BytecodeArrayBuilder & CompareNil (Token::Value op, NilValue nil)
BytecodeArrayBuilder & CompareTypeOf (TestTypeOfFlags::LiteralFlag literal_flag)
BytecodeArrayBuilder & ToObject (Register out)
BytecodeArrayBuilder & ToName ()
BytecodeArrayBuilder & ToString ()
BytecodeArrayBuilder & ToBoolean (ToBooleanMode mode)
BytecodeArrayBuilder & ToNumber (int feedback_slot)
BytecodeArrayBuilder & ToNumeric (int feedback_slot)
BytecodeArrayBuilder & MarkHandler (int handler_id, HandlerTable::CatchPrediction will_catch)
BytecodeArrayBuilder & MarkTryBegin (int handler_id, Register context)
BytecodeArrayBuilder & MarkTryEnd (int handler_id)
BytecodeArrayBuilder & Bind (BytecodeLabel *label)
BytecodeArrayBuilder & Bind (BytecodeLoopHeader *label)
BytecodeArrayBuilder & Bind (BytecodeJumpTable *jump_table, int case_value)
BytecodeArrayBuilder & Jump (BytecodeLabel *label)
BytecodeArrayBuilder & JumpLoop (BytecodeLoopHeader *loop_header, int loop_depth, int position, int feedback_slot)
BytecodeArrayBuilder & JumpIfTrue (ToBooleanMode mode, BytecodeLabel *label)
BytecodeArrayBuilder & JumpIfFalse (ToBooleanMode mode, BytecodeLabel *label)
BytecodeArrayBuilder & JumpIfJSReceiver (BytecodeLabel *label)
BytecodeArrayBuilder & JumpIfNull (BytecodeLabel *label)
BytecodeArrayBuilder & JumpIfNotNull (BytecodeLabel *label)
BytecodeArrayBuilder & JumpIfUndefined (BytecodeLabel *label)
BytecodeArrayBuilder & JumpIfUndefinedOrNull (BytecodeLabel *label)
BytecodeArrayBuilder & JumpIfNotUndefined (BytecodeLabel *label)
BytecodeArrayBuilder & JumpIfNil (BytecodeLabel *label, Token::Value op, NilValue nil)
BytecodeArrayBuilder & JumpIfNotNil (BytecodeLabel *label, Token::Value op, NilValue nil)
BytecodeArrayBuilder & JumpIfForInDone (BytecodeLabel *label, Register index, Register cache_length)
BytecodeArrayBuilder & SwitchOnSmiNoFeedback (BytecodeJumpTable *jump_table)
BytecodeArrayBuilder & SetPendingMessage ()
BytecodeArrayBuilder & Throw ()
BytecodeArrayBuilder & ReThrow ()
BytecodeArrayBuilder & Abort (AbortReason reason)
BytecodeArrayBuilder & Return ()
BytecodeArrayBuilder & ThrowReferenceErrorIfHole (const AstRawString *name)
BytecodeArrayBuilder & ThrowSuperNotCalledIfHole ()
BytecodeArrayBuilder & ThrowSuperAlreadyCalledIfNotHole ()
BytecodeArrayBuilder & ThrowIfNotSuperConstructor (Register constructor)
BytecodeArrayBuilder & Debugger ()
BytecodeArrayBuilder & IncBlockCounter (int slot)
BytecodeArrayBuilder & ForInEnumerate (Register receiver)
BytecodeArrayBuilder & ForInPrepare (RegisterList cache_info_triple, int feedback_slot)
BytecodeArrayBuilder & ForInNext (Register receiver, Register index, RegisterList cache_type_array_pair, int feedback_slot)
BytecodeArrayBuilder & ForInStep (Register index)
BytecodeArrayBuilder & SuspendGenerator (Register generator, RegisterList registers, int suspend_id)
BytecodeArrayBuilder & SwitchOnGeneratorState (Register generator, BytecodeJumpTable *jump_table)
BytecodeArrayBuilder & ResumeGenerator (Register generator, RegisterList registers)
int NewHandlerEntry ()
BytecodeJumpTable * AllocateJumpTable (int size, int case_value_base)
BytecodeRegisterOptimizer * GetRegisterOptimizer ()
size_t GetConstantPoolEntry (const AstRawString *raw_string)
size_t GetConstantPoolEntry (const AstConsString *cons_string)
size_t GetConstantPoolEntry (AstBigInt bigint)
size_t GetConstantPoolEntry (const Scope *scope)
size_t GetConstantPoolEntry (double number)
size_t AllocateDeferredConstantPoolEntry ()
void SetDeferredConstantPoolEntry (size_t entry, Handle< Object > object)
void InitializeReturnPosition (FunctionLiteral *literal)
void SetStatementPosition (Statement *stmt, bool is_breakable=true)
std::optional< BytecodeSourceInfo > MaybePopSourcePosition (int scope_start)
void PushSourcePosition (BytecodeSourceInfo source_info)
void SetStatementPosition (int position, bool is_breakable=true)
void SetExpressionPosition (Expression *expr)
void SetExpressionPosition (int position)
void SetExpressionAsStatementPosition (Expression *expr, bool is_breakable=true)
bool RemainderOfBlockIsDead () const
uint32_t GetInputRegisterOperand (Register reg)
uint32_t GetOutputRegisterOperand (Register reg)
uint32_t GetInputOutputRegisterOperand (Register reg)
uint32_t GetInputRegisterListOperand (RegisterList reg_list)
uint32_t GetOutputRegisterListOperand (RegisterList reg_list)
void OutputLdarRaw (Register reg)
void OutputStarRaw (Register reg)
void OutputMovRaw (Register src, Register dest)
void EmitFunctionStartSourcePosition (int position)
BytecodeRegisterAllocator * register_allocator ()
const BytecodeRegisterAllocator * register_allocator () const
Zone * zone () const
Private Member Functions
const FeedbackVectorSpec * feedback_vector_spec () const
BytecodeSourceInfo CurrentSourcePosition (Bytecode bytecode)
void OutputJumpLoop (BytecodeLoopHeader *loop_header, int loop_depth, int feedback_slot)
void OutputSwitchOnSmiNoFeedback (BytecodeJumpTable *jump_table)
bool RegisterIsValid (Register reg) const
bool RegisterListIsValid (RegisterList reg_list) const
void SetDeferredSourceInfo (BytecodeSourceInfo source_info)
void AttachOrEmitDeferredSourceInfo (BytecodeNode *node)
void Write (BytecodeNode *node)
void WriteJump (BytecodeNode *node, BytecodeLabel *label)
void WriteJumpLoop (BytecodeNode *node, BytecodeLoopHeader *loop_header)
void WriteSwitch (BytecodeNode *node, BytecodeJumpTable *label)
BytecodeArrayBuilder & Illegal ()
template<Bytecode bytecode, ImplicitRegisterUse implicit_register_use>
void PrepareToOutputBytecode ()
BytecodeArrayWriter * bytecode_array_writer ()
ConstantArrayBuilder * constant_array_builder ()
const ConstantArrayBuilder * constant_array_builder () const
HandlerTableBuilder * handler_table_builder ()
Private Attributes
Zone * zone_
FeedbackVectorSpec * feedback_vector_spec_
bool bytecode_generated_
ConstantArrayBuilder constant_array_builder_
HandlerTableBuilder handler_table_builder_
uint16_t parameter_count_
uint16_t max_arguments_
int local_register_count_
BytecodeRegisterAllocator register_allocator_
BytecodeArrayWriter bytecode_array_writer_
BytecodeRegisterOptimizer * register_optimizer_
BytecodeSourceInfo latest_source_info_
BytecodeSourceInfo deferred_source_info_
Friends
class BytecodeRegisterAllocator
template<Bytecode bytecode, ImplicitRegisterUse implicit_register_use, OperandType... operand_types>
class BytecodeNodeBuilder
Detailed Description
Definition at line 38 of file bytecode-array-builder.h.
Member Enumeration Documentation
ContextSlotMutability
enum v8::internal::interpreter::BytecodeArrayBuilder::ContextSlotMutability
Enumerator
kImmutableSlot
kMutableSlot
Definition at line 111 of file bytecode-array-builder.h.
{ kImmutableSlot, kMutableSlot };
NilValue
enum v8::internal::interpreter::BytecodeArrayBuilder::NilValue
Enumerator
kNullValue
kUndefinedValue
Definition at line 413 of file bytecode-array-builder.h.
{ kNullValue, kUndefinedValue };
ToBooleanMode
enum v8::internal::interpreter::BytecodeArrayBuilder::ToBooleanMode [strong]
Enumerator
kConvertToBoolean
kAlreadyBoolean
Definition at line 391 of file bytecode-array-builder.h.
                           {
    kConvertToBoolean, // Perform ToBoolean conversion on accumulator.
    kAlreadyBoolean, // Accumulator is already a Boolean.
  };
Constructor & Destructor Documentation
BytecodeArrayBuilder() [1/2]
v8::internal::interpreter::BytecodeArrayBuilder::BytecodeArrayBuilder (Zone * zone, int parameter_count, int locals_count, FeedbackVectorSpec * feedback_vector_spec = nullptr, SourcePositionTableBuilder::RecordingMode source_position_mode = SourcePositionTableBuilder::RECORD_SOURCE_POSITIONS)
Definition at line 47 of file bytecode-array-builder.cc.
    : zone_(zone),
      feedback_vector_spec_(feedback_vector_spec),
      bytecode_generated_(false),
      constant_array_builder_(zone),
      handler_table_builder_(zone),
      parameter_count_(parameter_count),
      max_arguments_(0),
      local_register_count_(locals_count),
      register_allocator_(fixed_register_count()),
      bytecode_array_writer_(zone, &constant_array_builder_,
                             source_position_mode),
      register_optimizer_(nullptr) {
  DCHECK_GE(parameter_count_, 0);
  DCHECK_LE(parameter_count_, std::numeric_limits<uint16_t>::max());
  DCHECK_GE(local_register_count_, 0);
  if (v8_flags.ignition_reo) {
    register_optimizer_ = zone->New<BytecodeRegisterOptimizer>(
        zone, &register_allocator_, fixed_register_count(), parameter_count,
        zone->New<RegisterTransferWriter>(this));
  }
}
References DCHECK_GE, DCHECK_LE, fixed_register_count(), local_register_count_, v8::internal::Zone::New(), parameter_count(), parameter_count_, register_allocator_, register_optimizer_, v8::internal::v8_flags, and zone().
BytecodeArrayBuilder() [2/2]
v8::internal::interpreter::BytecodeArrayBuilder::BytecodeArrayBuilder (const BytecodeArrayBuilder &) [delete]
Member Function Documentation
Abort()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::Abort (AbortReason reason)
Definition at line 1412 of file bytecode-array-builder.cc.
                                                                    {
  DCHECK_LT(reason, AbortReason::kLastErrorMessage);
  DCHECK_GE(reason, AbortReason::kNoReason);
  OutputAbort(static_cast<int>(reason));
  return *this;
}
References DCHECK_GE, and DCHECK_LT.
Add_StringConstant_Internalize()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::Add_StringConstant_Internalize (Token::Value binop, Register reg, int feedback_slot, AddStringConstantAndInternalizeVariant as_variant)
Definition at line 456 of file bytecode-array-builder.cc.
                                                       {
  DCHECK_EQ(op, Token::kAdd);
#ifdef DEBUG
  using ASVariant = AddStringConstantAndInternalizeVariant;
  DCHECK(as_variant == ASVariant::kLhsIsStringConstant ||
         as_variant == ASVariant::kRhsIsStringConstant);
#endif // DEBUG
  OutputAdd_StringConstant_Internalize(reg, feedback_slot,
                                       static_cast<uint8_t>(as_variant));
  return *this;
}
References v8::internal::DCHECK(), and DCHECK_EQ.
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitArithmeticExpression().
AllocateDeferredConstantPoolEntry()
size_t v8::internal::interpreter::BytecodeArrayBuilder::AllocateDeferredConstantPoolEntry ()
Definition at line 1681 of file bytecode-array-builder.cc.
                                                               {
  return constant_array_builder()->InsertDeferred();
}
References constant_array_builder(), and v8::internal::interpreter::ConstantArrayBuilder::InsertDeferred().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), and v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral().
AllocateJumpTable()
BytecodeJumpTable * v8::internal::interpreter::BytecodeArrayBuilder::AllocateJumpTable (int size, int case_value_base)
Definition at line 1671 of file bytecode-array-builder.cc.
                                   {
  DCHECK_GT(size, 0);
  size_t constant_pool_index = constant_array_builder()->InsertJumpTable(size);
  return zone()->New<BytecodeJumpTable>(constant_pool_index, size,
                                        case_value_base, zone());
}
References constant_array_builder(), DCHECK_GT, v8::internal::interpreter::ConstantArrayBuilder::InsertJumpTable(), v8::internal::Zone::New(), size(), and zone().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildGeneratorPrologue().
AttachOrEmitDeferredSourceInfo()
void v8::internal::interpreter::BytecodeArrayBuilder::AttachOrEmitDeferredSourceInfo (BytecodeNode * node) [private]
Definition at line 163 of file bytecode-array-builder.cc.
                                                                            {
  if (!deferred_source_info_.is_valid()) return;
  if (!node->source_info().is_valid()) {
    node->set_source_info(deferred_source_info_);
  } else if (deferred_source_info_.is_statement() &&
             node->source_info().is_expression()) {
    BytecodeSourceInfo source_position = node->source_info();
    source_position.MakeStatementPosition(source_position.source_position());
    node->set_source_info(source_position);
  }
  deferred_source_info_.set_invalid();
}
References deferred_source_info_, v8::internal::interpreter::BytecodeSourceInfo::is_expression(), v8::internal::interpreter::BytecodeSourceInfo::is_statement(), v8::internal::interpreter::BytecodeSourceInfo::is_valid(), v8::internal::interpreter::BytecodeSourceInfo::MakeStatementPosition(), v8::internal::interpreter::BytecodeSourceInfo::set_invalid(), v8::internal::interpreter::BytecodeNode::set_source_info(), v8::internal::interpreter::BytecodeNode::source_info(), and v8::internal::interpreter::BytecodeSourceInfo::source_position().
Referenced by Write(), WriteJump(), WriteJumpLoop(), and WriteSwitch().
BinaryOperation()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::BinaryOperation (Token::Value binop, Register reg, int feedback_slot)
Definition at line 410 of file bytecode-array-builder.cc.
                                                                               {
  switch (op) {
    case Token::kAdd:
      OutputAdd(reg, feedback_slot);
      break;
    case Token::kSub:
      OutputSub(reg, feedback_slot);
      break;
    case Token::kMul:
      OutputMul(reg, feedback_slot);
      break;
    case Token::kDiv:
      OutputDiv(reg, feedback_slot);
      break;
    case Token::kMod:
      OutputMod(reg, feedback_slot);
      break;
    case Token::kExp:
      OutputExp(reg, feedback_slot);
      break;
    case Token::kBitOr:
      OutputBitwiseOr(reg, feedback_slot);
      break;
    case Token::kBitXor:
      OutputBitwiseXor(reg, feedback_slot);
      break;
    case Token::kBitAnd:
      OutputBitwiseAnd(reg, feedback_slot);
      break;
    case Token::kShl:
      OutputShiftLeft(reg, feedback_slot);
      break;
    case Token::kSar:
      OutputShiftRight(reg, feedback_slot);
      break;
    case Token::kShr:
      OutputShiftRightLogical(reg, feedback_slot);
      break;
    default:
      UNREACHABLE();
  }
  return *this;
}
References v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitArithmeticExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryArithmeticExpression().
BinaryOperationSmiLiteral()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::BinaryOperationSmiLiteral (Token::Value binop, Tagged< Smi > literal, int feedback_slot)
Definition at line 470 of file bytecode-array-builder.cc.
                                                           {
  switch (op) {
    case Token::kAdd:
      OutputAddSmi(literal.value(), feedback_slot);
      break;
    case Token::kSub:
      OutputSubSmi(literal.value(), feedback_slot);
      break;
    case Token::kMul:
      OutputMulSmi(literal.value(), feedback_slot);
      break;
    case Token::kDiv:
      OutputDivSmi(literal.value(), feedback_slot);
      break;
    case Token::kMod:
      OutputModSmi(literal.value(), feedback_slot);
      break;
    case Token::kExp:
      OutputExpSmi(literal.value(), feedback_slot);
      break;
    case Token::kBitOr:
      OutputBitwiseOrSmi(literal.value(), feedback_slot);
      break;
    case Token::kBitXor:
      OutputBitwiseXorSmi(literal.value(), feedback_slot);
      break;
    case Token::kBitAnd:
      OutputBitwiseAndSmi(literal.value(), feedback_slot);
      break;
    case Token::kShl:
      OutputShiftLeftSmi(literal.value(), feedback_slot);
      break;
    case Token::kSar:
      OutputShiftRightSmi(literal.value(), feedback_slot);
      break;
    case Token::kShr:
      OutputShiftRightLogicalSmi(literal.value(), feedback_slot);
      break;
    default:
      UNREACHABLE();
  }
  return *this;
}
References v8::internal::UNREACHABLE(), and v8::internal::Tagged< Smi >::value().
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitArithmeticExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryArithmeticExpression().
Bind() [1/3]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::Bind (BytecodeJumpTable * jump_table, int case_value)
Definition at line 1214 of file bytecode-array-builder.cc.
                                                                 {
  // Flush the register optimizer when binding a jump table entry to ensure
  // all expected registers are valid when jumping to this location.
  if (register_optimizer_) {
    register_optimizer_->Flush();
    register_optimizer_->ResetTypeHintForAccumulator();
  }
  bytecode_array_writer_.BindJumpTableEntry(jump_table, case_value);
  return *this;
}
References v8::internal::interpreter::BytecodeArrayWriter::BindJumpTableEntry(), bytecode_array_writer_, v8::internal::interpreter::BytecodeRegisterOptimizer::Flush(), register_optimizer_, and v8::internal::interpreter::BytecodeRegisterOptimizer::ResetTypeHintForAccumulator().
Bind() [2/3]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::Bind (BytecodeLabel * label)
Definition at line 1187 of file bytecode-array-builder.cc.
                                                                     {
  // Don't generate code for a label which hasn't had a corresponding forward
  // jump generated already. For backwards jumps, use BindLoopHeader.
  if (!label->has_referrer_jump()) return *this;
  // Flush the register optimizer when binding a label to ensure all
  // expected registers are valid when jumping to this label.
  if (register_optimizer_) {
    register_optimizer_->Flush();
    register_optimizer_->ResetTypeHintForAccumulator();
  }
  bytecode_array_writer_.BindLabel(label);
  return *this;
}
References v8::internal::interpreter::BytecodeArrayWriter::BindLabel(), bytecode_array_writer_, v8::internal::interpreter::BytecodeRegisterOptimizer::Flush(), v8::internal::interpreter::BytecodeLabel::has_referrer_jump(), register_optimizer_, and v8::internal::interpreter::BytecodeRegisterOptimizer::ResetTypeHintForAccumulator().
Referenced by v8::internal::interpreter::TryFinallyBuilder::BeginHandler(), v8::internal::interpreter::BytecodeLabels::Bind(), v8::internal::interpreter::SwitchBuilder::BindCaseTargetForCompareJump(), v8::internal::interpreter::SwitchBuilder::BindCaseTargetForJumpTable(), v8::internal::interpreter::BytecodeGenerator::BuildAwait(), v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildGetIterator(), v8::internal::interpreter::BytecodeGenerator::BuildInstanceMemberInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorClose(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorNext(), v8::internal::interpreter::BytecodeGenerator::BuildOptionalChain(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn(), v8::internal::interpreter::BytecodeGenerator::BuildSuspendPoint(), v8::internal::interpreter::TryCatchBuilder::EndCatch(), v8::internal::interpreter::LoopBuilder::LoopHeader(), v8::internal::interpreter::BytecodeGenerator::VisitCallSuper(), v8::internal::interpreter::BytecodeGenerator::VisitDelete(), and v8::internal::interpreter::BytecodeGenerator::VisitNullishSubExpression().
Bind() [3/3]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::Bind (BytecodeLoopHeader * label)
Definition at line 1202 of file bytecode-array-builder.cc.
                                     {
  // Flush the register optimizer when starting a loop to ensure all expected
  // registers are valid when jumping to the loop header.
  if (register_optimizer_) {
    register_optimizer_->Flush();
    register_optimizer_->ResetTypeHintForAccumulator();
  }
  bytecode_array_writer_.BindLoopHeader(loop_header);
  return *this;
}
References v8::internal::interpreter::BytecodeArrayWriter::BindLoopHeader(), bytecode_array_writer_, v8::internal::interpreter::BytecodeRegisterOptimizer::Flush(), register_optimizer_, and v8::internal::interpreter::BytecodeRegisterOptimizer::ResetTypeHintForAccumulator().
bytecode_array_writer()
BytecodeArrayWriter* v8::internal::interpreter::BytecodeArrayBuilder::bytecode_array_writer () [inline], [private]
Definition at line 656 of file bytecode-array-builder.h.
                                               {
    return &bytecode_array_writer_;
  }
CallAnyReceiver()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CallAnyReceiver (Register callable, RegisterList args, int feedback_slot)
Definition at line 1547 of file bytecode-array-builder.cc.
                                                                               {
  OutputCallAnyReceiver(callable, args, args.register_count(), feedback_slot);
  return *this;
}
References v8::base::args.
CallJSRuntime()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CallJSRuntime (int context_index, RegisterList args)
Definition at line 1625 of file bytecode-array-builder.cc.
                                                                             {
  OutputCallJSRuntime(context_index, args, args.register_count());
  return *this;
}
References v8::base::args.
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitCallSuper().
CallProperty()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CallProperty (Register callable, RegisterList args, int feedback_slot)
Definition at line 1517 of file bytecode-array-builder.cc.
                                                                            {
  if (args.register_count() == 1) {
    OutputCallProperty0(callable, args[0], feedback_slot);
  } else if (args.register_count() == 2) {
    OutputCallProperty1(callable, args[0], args[1], feedback_slot);
  } else if (args.register_count() == 3) {
    OutputCallProperty2(callable, args[0], args[1], args[2], feedback_slot);
  } else {
    OutputCallProperty(callable, args, args.register_count(), feedback_slot);
  }
  return *this;
}
References v8::base::args.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCallIteratorMethod(), v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildGetIterator(), v8::internal::interpreter::BytecodeGenerator::BuildInstanceMemberInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorNext(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateGetterAccess(), and v8::internal::interpreter::BytecodeGenerator::BuildPrivateSetterAccess().
CallRuntime() [1/3]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime (Runtime::FunctionId function_id)
Definition at line 1603 of file bytecode-array-builder.cc.
                                   {
  return CallRuntime(function_id, RegisterList());
}
References CallRuntime().
CallRuntime() [2/3]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime (Runtime::FunctionId function_id, Register arg)
Definition at line 1598 of file bytecode-array-builder.cc.
                                                 {
  return CallRuntime(function_id, RegisterList(arg));
}
References CallRuntime().
CallRuntime() [3/3]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime (Runtime::FunctionId function_id, RegisterList args)
Definition at line 1581 of file bytecode-array-builder.cc.
                                                      {
  DCHECK_EQ(1, Runtime::FunctionForId(function_id)->result_size);
  DCHECK_LE(Bytecodes::SizeForUnsignedOperand(function_id),
            OperandSize::kShort);
  if (IntrinsicsHelper::IsSupported(function_id)) {
    IntrinsicsHelper::IntrinsicId intrinsic_id =
        IntrinsicsHelper::FromRuntimeId(function_id);
    OutputInvokeIntrinsic(static_cast<int>(intrinsic_id), args,
                          args.register_count());
  } else {
    OutputCallRuntime(static_cast<int>(function_id), args,
                      args.register_count());
  }
  return *this;
}
References v8::base::args, DCHECK_EQ, DCHECK_LE, v8::internal::interpreter::IntrinsicsHelper::FromRuntimeId(), v8::internal::Runtime::FunctionForId(), v8::internal::interpreter::IntrinsicsHelper::IsSupported(), v8::internal::interpreter::kShort, and v8::internal::interpreter::Bytecodes::SizeForUnsignedOperand().
Referenced by v8::internal::interpreter::BytecodeGenerator::AddDisposableValue(), v8::internal::interpreter::BytecodeGenerator::BuildAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildAsyncReturn(), v8::internal::interpreter::BytecodeGenerator::BuildAwait(), v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildDeclareCall(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildGeneratorObjectVariableInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildGetIterator(), v8::internal::interpreter::BytecodeGenerator::BuildInvalidPropertyAccess(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorClose(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorNext(), v8::internal::interpreter::BytecodeGenerator::BuildNewLocalActivationContext(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicGet(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicSet(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateGetterAccess(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateSetterAccess(), v8::internal::interpreter::BytecodeGenerator::BuildReturn(), v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment(), CallRuntime(), v8::internal::interpreter::BytecodeGenerator::DisposablesStackScope::DisposablesStackScope(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncFunctionBody(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncGeneratorFunctionBody(), v8::internal::interpreter::BytecodeGenerator::GenerateBodyPrologue(), v8::internal::interpreter::BytecodeGenerator::VisitDelete(), v8::internal::interpreter::BytecodeGenerator::VisitKeyedSuperPropertyLoad(), v8::internal::interpreter::BytecodeGenerator::VisitModuleNamespaceImports(), and v8::internal::interpreter::BytecodeGenerator::VisitNamedSuperPropertyLoad().
CallRuntimeForPair() [1/2]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CallRuntimeForPair (Runtime::FunctionId function_id, Register arg, RegisterList return_pair)
Definition at line 1620 of file bytecode-array-builder.cc.
                                                                           {
  return CallRuntimeForPair(function_id, RegisterList(arg), return_pair);
}
References CallRuntimeForPair().
CallRuntimeForPair() [2/2]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CallRuntimeForPair (Runtime::FunctionId function_id, RegisterList args, RegisterList return_pair)
Definition at line 1608 of file bytecode-array-builder.cc.
                              {
  DCHECK_EQ(2, Runtime::FunctionForId(function_id)->result_size);
  DCHECK_LE(Bytecodes::SizeForUnsignedOperand(function_id),
            OperandSize::kShort);
  DCHECK_EQ(2, return_pair.register_count());
  OutputCallRuntimeForPair(static_cast<uint16_t>(function_id), args,
                           args.register_count(), return_pair);
  return *this;
}
References v8::base::args, DCHECK_EQ, DCHECK_LE, v8::internal::Runtime::FunctionForId(), v8::internal::interpreter::kShort, v8::internal::interpreter::RegisterList::register_count(), and v8::internal::interpreter::Bytecodes::SizeForUnsignedOperand().
Referenced by CallRuntimeForPair().
CallUndefinedReceiver()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CallUndefinedReceiver (Register callable, RegisterList args, int feedback_slot)
Definition at line 1532 of file bytecode-array-builder.cc.
                                                             {
  if (args.register_count() == 0) {
    OutputCallUndefinedReceiver0(callable, feedback_slot);
  } else if (args.register_count() == 1) {
    OutputCallUndefinedReceiver1(callable, args[0], feedback_slot);
  } else if (args.register_count() == 2) {
    OutputCallUndefinedReceiver2(callable, args[0], args[1], feedback_slot);
  } else {
    OutputCallUndefinedReceiver(callable, args, args.register_count(),
                                feedback_slot);
  }
  return *this;
}
References v8::base::args.
CallWithSpread()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CallWithSpread (Register callable, RegisterList args, int feedback_slot)
Definition at line 1554 of file bytecode-array-builder.cc.
                                                                              {
  OutputCallWithSpread(callable, args, args.register_count(), feedback_slot);
  return *this;
}
References v8::base::args.
CloneObject()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CloneObject (Register source, int flags, int feedback_slot)
Definition at line 1128 of file bytecode-array-builder.cc.
                                                                           {
  OutputCloneObject(source, flags, feedback_slot);
  return *this;
}
References v8::internal::flags.
CompareNil()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CompareNil (Token::Value op, NilValue nil)
Definition at line 619 of file bytecode-array-builder.cc.
                                                                     {
  if (op == Token::kEq) {
    return CompareUndetectable();
  } else {
    DCHECK_EQ(Token::kEqStrict, op);
    if (nil == kUndefinedValue) {
      return CompareUndefined();
    } else {
      DCHECK_EQ(kNullValue, nil);
      return CompareNull();
    }
  }
}
References CompareNull(), CompareUndefined(), CompareUndetectable(), DCHECK_EQ, kNullValue, and kUndefinedValue.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLiteralCompareNil().
CompareNull()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CompareNull ()
Definition at line 614 of file bytecode-array-builder.cc.
                                                        {
  OutputTestNull();
  return *this;
}
Referenced by CompareNil().
CompareOperation()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CompareOperation (Token::Value op, Register reg, int feedback_slot)
Definition at line 566 of file bytecode-array-builder.cc.
                                                    {
  switch (op) {
    case Token::kEq:
      OutputTestEqual(reg, feedback_slot);
      break;
    case Token::kEqStrict:
      OutputTestEqualStrict(reg, feedback_slot);
      break;
    case Token::kLessThan:
      OutputTestLessThan(reg, feedback_slot);
      break;
    case Token::kGreaterThan:
      OutputTestGreaterThan(reg, feedback_slot);
      break;
    case Token::kLessThanEq:
      OutputTestLessThanOrEqual(reg, feedback_slot);
      break;
    case Token::kGreaterThanEq:
      OutputTestGreaterThanOrEqual(reg, feedback_slot);
      break;
    case Token::kInstanceOf:
      OutputTestInstanceOf(reg, feedback_slot);
      break;
    case Token::kIn:
      OutputTestIn(reg, feedback_slot);
      break;
    default:
      UNREACHABLE();
  }
  return *this;
}
References v8::internal::kGreaterThan, v8::internal::kLessThan, and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), and v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn().
CompareReference()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CompareReference (Register reg)
Definition at line 599 of file bytecode-array-builder.cc.
                                                                         {
  OutputTestReferenceEqual(reg);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAwait(), v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildLiteralStrictCompareBoolean(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), and v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn().
CompareTypeOf()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CompareTypeOf (TestTypeOfFlags::LiteralFlag literal_flag)
Definition at line 634 of file bytecode-array-builder.cc.
                                             {
  DCHECK_NE(literal_flag, TestTypeOfFlags::LiteralFlag::kOther);
  OutputTestTypeOf(TestTypeOfFlags::Encode(literal_flag));
  return *this;
}
References DCHECK_NE, and v8::internal::interpreter::TestTypeOfFlags::Encode().
CompareUndefined()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CompareUndefined ()
Definition at line 609 of file bytecode-array-builder.cc.
                                                             {
  OutputTestUndefined();
  return *this;
}
Referenced by CompareNil().
CompareUndetectable()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CompareUndetectable ()
Definition at line 604 of file bytecode-array-builder.cc.
                                                                {
  OutputTestUndetectable();
  return *this;
}
Referenced by CompareNil(), JumpIfNil(), and JumpIfNotNil().
constant_array_builder() [1/2]
ConstantArrayBuilder* v8::internal::interpreter::BytecodeArrayBuilder::constant_array_builder () [inline], [private]
Definition at line 659 of file bytecode-array-builder.h.
                                                 {
    return &constant_array_builder_;
  }
Referenced by AllocateDeferredConstantPoolEntry(), AllocateJumpTable(), GetConstantPoolEntry(), and SetDeferredConstantPoolEntry().
constant_array_builder() [2/2]
const ConstantArrayBuilder* v8::internal::interpreter::BytecodeArrayBuilder::constant_array_builder () const [inline], [private]
Definition at line 662 of file bytecode-array-builder.h.
                                                             {
    return &constant_array_builder_;
  }
Construct()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::Construct (Register constructor, RegisterList args, int feedback_slot)
Definition at line 1561 of file bytecode-array-builder.cc.
                                                                            {
  OutputConstruct(constructor, args, args.register_count(), feedback_slot_id);
  return *this;
}
References v8::base::args.
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitCallSuper().
ConstructForwardAllArgs()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ConstructForwardAllArgs (Register constructor, int feedback_slot)
Definition at line 1575 of file bytecode-array-builder.cc.
                                                {
  OutputConstructForwardAllArgs(constructor, feedback_slot_id);
  return *this;
}
ConstructWithSpread()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ConstructWithSpread (Register constructor, RegisterList args, int feedback_slot)
Definition at line 1568 of file bytecode-array-builder.cc.
                                                                   {
  OutputConstructWithSpread(constructor, args, args.register_count(),
                            feedback_slot_id);
  return *this;
}
References v8::base::args.
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitCallSuper().
CreateArguments()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CreateArguments (CreateArgumentsType type)
Definition at line 1075 of file bytecode-array-builder.cc.
                              {
  switch (type) {
    case CreateArgumentsType::kMappedArguments:
      OutputCreateMappedArguments();
      break;
    case CreateArgumentsType::kUnmappedArguments:
      OutputCreateUnmappedArguments();
      break;
    case CreateArgumentsType::kRestParameter:
      OutputCreateRestParameter();
      break;
    default:
      UNREACHABLE();
  }
  return *this;
}
References v8::internal::kMappedArguments, v8::internal::kRestParameter, v8::internal::kUnmappedArguments, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitArgumentsObject(), and v8::internal::interpreter::BytecodeGenerator::VisitRestArgumentsArray().
CreateArrayFromIterable()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CreateArrayFromIterable ()
Definition at line 1112 of file bytecode-array-builder.cc.
                                                                    {
  OutputCreateArrayFromIterable();
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral().
CreateArrayLiteral()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CreateArrayLiteral (size_t constant_elements_entry, int literal_index, int flags)
Definition at line 1106 of file bytecode-array-builder.cc.
                                                                  {
  OutputCreateArrayLiteral(constant_elements_entry, literal_index, flags);
  return *this;
}
References v8::internal::flags.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral().
CreateBlockContext()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CreateBlockContext (const Scope * scope)
Definition at line 1036 of file bytecode-array-builder.cc.
                        {
  size_t entry = GetConstantPoolEntry(scope);
  OutputCreateBlockContext(entry);
  return *this;
}
References GetConstantPoolEntry().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildNewLocalBlockContext().
CreateCatchContext()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CreateCatchContext (Register exception, const Scope * scope)
Definition at line 1043 of file bytecode-array-builder.cc.
                                            {
  size_t scope_index = GetConstantPoolEntry(scope);
  OutputCreateCatchContext(exception, scope_index);
  return *this;
}
References GetConstantPoolEntry().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildNewLocalCatchContext().
CreateClosure()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CreateClosure (size_t shared_function_info_entry, int slot, int flags)
Definition at line 1030 of file bytecode-array-builder.cc.
                                                            {
  OutputCreateClosure(shared_function_info_entry, slot, flags);
  return *this;
}
References v8::internal::flags.
CreateEmptyArrayLiteral()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CreateEmptyArrayLiteral (int literal_index)
Definition at line 1100 of file bytecode-array-builder.cc.
                       {
  OutputCreateEmptyArrayLiteral(literal_index);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), and v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment().
CreateEmptyObjectLiteral()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CreateEmptyObjectLiteral ()
Definition at line 1123 of file bytecode-array-builder.cc.
                                                                     {
  OutputCreateEmptyObjectLiteral();
  return *this;
}
CreateEvalContext()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CreateEvalContext (const Scope * scope, int slots)
Definition at line 1061 of file bytecode-array-builder.cc.
                                   {
  size_t scope_index = GetConstantPoolEntry(scope);
  OutputCreateEvalContext(scope_index, slots);
  return *this;
}
References GetConstantPoolEntry().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildNewLocalActivationContext().
CreateFunctionContext()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CreateFunctionContext (const Scope * scope, int slots)
Definition at line 1050 of file bytecode-array-builder.cc.
                                   {
  size_t scope_index = GetConstantPoolEntry(scope);
  if (scope->has_context_cells()) {
    OutputCreateFunctionContextWithCells(scope_index, slots);
  } else {
    OutputCreateFunctionContext(scope_index, slots);
  }
  return *this;
}
References GetConstantPoolEntry(), and v8::internal::Scope::has_context_cells().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildNewLocalActivationContext().
CreateObjectLiteral()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CreateObjectLiteral (size_t constant_properties_entry, int literal_index, int flags)
Definition at line 1117 of file bytecode-array-builder.cc.
                                                                    {
  OutputCreateObjectLiteral(constant_properties_entry, literal_index, flags);
  return *this;
}
References v8::internal::flags.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateObjectLiteral().
CreateRegExpLiteral()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CreateRegExpLiteral (const AstRawString * pattern, int literal_index, int flags)
Definition at line 1093 of file bytecode-array-builder.cc.
                                                               {
  size_t pattern_entry = GetConstantPoolEntry(pattern);
  OutputCreateRegExpLiteral(pattern_entry, literal_index, flags);
  return *this;
}
References v8::internal::flags, and GetConstantPoolEntry().
CreateWithContext()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::CreateWithContext (Register object, const Scope * scope)
Definition at line 1068 of file bytecode-array-builder.cc.
                                         {
  size_t scope_index = GetConstantPoolEntry(scope);
  OutputCreateWithContext(object, scope_index);
  return *this;
}
References GetConstantPoolEntry().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildNewLocalWithContext().
CurrentSourcePosition()
BytecodeSourceInfo v8::internal::interpreter::BytecodeArrayBuilder::CurrentSourcePosition (Bytecode bytecode) [inline], [private]
Referenced by LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeNodeBuilder< bytecode, implicit_register_use, operand_types >::Make(), MoveRegister(), and StoreAccumulatorInRegister().
Debugger()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::Debugger ()
Definition at line 1447 of file bytecode-array-builder.cc.
                                                     {
  OutputDebugger();
  return *this;
}
DefineKeyedOwnProperty()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::DefineKeyedOwnProperty (Register object, Register key, DefineKeyedOwnPropertyFlags flags, int feedback_slot)
Definition at line 998 of file bytecode-array-builder.cc.
                       {
  // Ensure that the IC uses a strict language mode, as this is the only
  // supported mode for this use case.
  DCHECK_EQ(GetLanguageModeFromSlotKind(feedback_vector_spec()->GetKind(
                FeedbackVector::ToSlot(feedback_slot))),
            LanguageMode::kStrict);
  OutputDefineKeyedOwnProperty(object, key, flags, feedback_slot);
  return *this;
}
References DCHECK_EQ, feedback_vector_spec(), v8::internal::flags, v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::GetKind(), v8::internal::GetLanguageModeFromSlotKind(), v8::internal::key, v8::internal::kStrict, and v8::internal::FeedbackVector::ToSlot().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), and v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandInitialization().
DefineKeyedOwnPropertyInLiteral()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::DefineKeyedOwnPropertyInLiteral (Register object, Register name, DefineKeyedOwnPropertyInLiteralFlags flags, int feedback_slot)
Definition at line 951 of file bytecode-array-builder.cc.
                       {
  OutputDefineKeyedOwnPropertyInLiteral(object, name, flags, feedback_slot);
  return *this;
}
References v8::internal::flags, and v8::internal::name.
DefineNamedOwnProperty()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::DefineNamedOwnProperty (Register object, const AstRawString * name, int feedback_slot)
Definition at line 976 of file bytecode-array-builder.cc.
                                                                  {
  size_t name_index = GetConstantPoolEntry(name);
  // Ensure that the store operation is in sync with the IC slot kind.
  DCHECK_EQ(
      FeedbackSlotKind::kDefineNamedOwn,
      feedback_vector_spec()->GetKind(FeedbackVector::ToSlot(feedback_slot)));
  OutputDefineNamedOwnProperty(object, name_index, feedback_slot);
  return *this;
}
References DCHECK_EQ, feedback_vector_spec(), GetConstantPoolEntry(), v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::GetKind(), v8::internal::kDefineNamedOwn, v8::internal::name, and v8::internal::FeedbackVector::ToSlot().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassProperty().
Delete()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::Delete (Register object, LanguageMode language_mode)
Definition at line 1631 of file bytecode-array-builder.cc.
                                                                               {
  if (language_mode == LanguageMode::kSloppy) {
    OutputDeletePropertySloppy(object);
  } else {
    DCHECK_EQ(language_mode, LanguageMode::kStrict);
    OutputDeletePropertyStrict(object);
  }
  return *this;
}
References DCHECK_EQ, v8::internal::kSloppy, and v8::internal::kStrict.
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitDelete().
EmitFunctionStartSourcePosition()
void v8::internal::interpreter::BytecodeArrayBuilder::EmitFunctionStartSourcePosition (int position)
Definition at line 1765 of file bytecode-array-builder.cc.
                                                                       {
  bytecode_array_writer_.SetFunctionEntrySourcePosition(position);
  // Force an expression position to make sure we have one. If the next bytecode
  // overwrites it, its fine since it would mean we have a source position
  // anyway.
  latest_source_info_.ForceExpressionPosition(position);
}
References bytecode_array_writer_, v8::internal::interpreter::BytecodeSourceInfo::ForceExpressionPosition(), latest_source_info_, and v8::internal::interpreter::BytecodeArrayWriter::SetFunctionEntrySourcePosition().
Referenced by v8::internal::interpreter::BytecodeGenerator::GenerateBytecode().
feedback_vector_spec()
const FeedbackVectorSpec* v8::internal::interpreter::BytecodeArrayBuilder::feedback_vector_spec () const [inline], [private]
Definition at line 611 of file bytecode-array-builder.h.
                                                         {
    return feedback_vector_spec_;
  }
Referenced by DefineKeyedOwnProperty(), DefineNamedOwnProperty(), LoadGlobal(), SetKeyedProperty(), and SetNamedProperty().
FindNonDefaultConstructorOrConstruct()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::FindNonDefaultConstructorOrConstruct (Register this_function, Register new_target, RegisterList output)
Definition at line 560 of file bytecode-array-builder.cc.
                                                                      {
  OutputFindNonDefaultConstructorOrConstruct(this_function, new_target, output);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildSuperCallOptimization().
fixed_register_count()
int v8::internal::interpreter::BytecodeArrayBuilder::fixed_register_count () const [inline]
Definition at line 75 of file bytecode-array-builder.h.
{ return locals_count(); }
Referenced by BytecodeArrayBuilder(), and RegisterIsValid().
ForInEnumerate()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ForInEnumerate (Register receiver)
Definition at line 1458 of file bytecode-array-builder.cc.
                                                                            {
  OutputForInEnumerate(receiver);
  return *this;
}
ForInNext()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ForInNext (Register receiver, Register index, RegisterList cache_type_array_pair, int feedback_slot)
Definition at line 1470 of file bytecode-array-builder.cc.
                       {
  DCHECK_EQ(2, cache_type_array_pair.register_count());
  OutputForInNext(receiver, index, cache_type_array_pair, feedback_slot);
  return *this;
}
References DCHECK_EQ, v8::internal::index, and v8::internal::interpreter::RegisterList::register_count().
ForInPrepare()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ForInPrepare (RegisterList cache_info_triple, int feedback_slot)
Definition at line 1463 of file bytecode-array-builder.cc.
                                                       {
  DCHECK_EQ(3, cache_info_triple.register_count());
  OutputForInPrepare(cache_info_triple, feedback_slot);
  return *this;
}
References DCHECK_EQ, and v8::internal::interpreter::RegisterList::register_count().
ForInStep()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ForInStep (Register index)
Definition at line 1478 of file bytecode-array-builder.cc.
                                                                    {
  OutputForInStep(index);
  return *this;
}
References v8::internal::index.
GetConstantPoolEntry() [1/5]
size_t v8::internal::interpreter::BytecodeArrayBuilder::GetConstantPoolEntry (AstBigInt bigint)
Definition at line 1652 of file bytecode-array-builder.cc.
                                                                  {
  return constant_array_builder()->Insert(bigint);
}
References constant_array_builder(), and v8::internal::interpreter::ConstantArrayBuilder::Insert().
GetConstantPoolEntry() [2/5]
size_t v8::internal::interpreter::BytecodeArrayBuilder::GetConstantPoolEntry (const AstConsString * cons_string)
Definition at line 1647 of file bytecode-array-builder.cc.
                                      {
  return constant_array_builder()->Insert(cons_string);
}
References constant_array_builder(), and v8::internal::interpreter::ConstantArrayBuilder::Insert().
GetConstantPoolEntry() [3/5]
size_t v8::internal::interpreter::BytecodeArrayBuilder::GetConstantPoolEntry (const AstRawString * raw_string)
Definition at line 1642 of file bytecode-array-builder.cc.
                                    {
  return constant_array_builder()->Insert(raw_string);
}
References constant_array_builder(), and v8::internal::interpreter::ConstantArrayBuilder::Insert().
Referenced by CreateBlockContext(), CreateCatchContext(), CreateEvalContext(), CreateFunctionContext(), CreateRegExpLiteral(), CreateWithContext(), DefineNamedOwnProperty(), LoadGlobal(), LoadLiteral(), LoadLookupContextSlot(), LoadLookupGlobalSlot(), LoadLookupSlot(), LoadNamedProperty(), LoadNamedPropertyFromSuper(), SetNamedProperty(), StoreGlobal(), StoreLookupSlot(), and ThrowReferenceErrorIfHole().
GetConstantPoolEntry() [4/5]
size_t v8::internal::interpreter::BytecodeArrayBuilder::GetConstantPoolEntry (const Scope * scope)
Definition at line 1656 of file bytecode-array-builder.cc.
                                                                    {
  return constant_array_builder()->Insert(scope);
}
References constant_array_builder(), and v8::internal::interpreter::ConstantArrayBuilder::Insert().
GetConstantPoolEntry() [5/5]
size_t v8::internal::interpreter::BytecodeArrayBuilder::GetConstantPoolEntry (double number)
Definition at line 1660 of file bytecode-array-builder.cc.
                                                               {
  return constant_array_builder()->Insert(number);
}
References constant_array_builder(), and v8::internal::interpreter::ConstantArrayBuilder::Insert().
GetInputOutputRegisterOperand()
uint32_t v8::internal::interpreter::BytecodeArrayBuilder::GetInputOutputRegisterOperand (Register reg)
Definition at line 1740 of file bytecode-array-builder.cc.
                                                                         {
  DCHECK(RegisterIsValid(reg));
  if (register_optimizer_) {
    register_optimizer_->PrepareOutputRegister(reg);
    DCHECK_EQ(reg, register_optimizer_->GetInputRegister(reg));
  }
  return static_cast<uint32_t>(reg.ToOperand());
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::interpreter::BytecodeRegisterOptimizer::GetInputRegister(), v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareOutputRegister(), register_optimizer_, RegisterIsValid(), and v8::internal::interpreter::Register::ToOperand().
Referenced by v8::internal::interpreter::anonymous_namespace{bytecode-array-builder.cc}::OperandHelper< OperandType::kRegInOut >::Convert().
GetInputRegisterListOperand()
uint32_t v8::internal::interpreter::BytecodeArrayBuilder::GetInputRegisterListOperand (RegisterList reg_list)
Definition at line 1749 of file bytecode-array-builder.cc.
                           {
  DCHECK(RegisterListIsValid(reg_list));
  if (register_optimizer_)
    reg_list = register_optimizer_->GetInputRegisterList(reg_list);
  return static_cast<uint32_t>(reg_list.first_register().ToOperand());
}
References v8::internal::DCHECK(), v8::internal::interpreter::RegisterList::first_register(), v8::internal::interpreter::BytecodeRegisterOptimizer::GetInputRegisterList(), register_optimizer_, RegisterListIsValid(), and v8::internal::interpreter::Register::ToOperand().
Referenced by v8::internal::interpreter::anonymous_namespace{bytecode-array-builder.cc}::OperandHelper< OperandType::kRegList >::Convert(), and v8::internal::interpreter::anonymous_namespace{bytecode-array-builder.cc}::OperandHelper< OperandType::kRegPair >::Convert().
GetInputRegisterOperand()
uint32_t v8::internal::interpreter::BytecodeArrayBuilder::GetInputRegisterOperand (Register reg)
Definition at line 1728 of file bytecode-array-builder.cc.
                                                                   {
  DCHECK(RegisterIsValid(reg));
  if (register_optimizer_) reg = register_optimizer_->GetInputRegister(reg);
  return static_cast<uint32_t>(reg.ToOperand());
}
References v8::internal::DCHECK(), v8::internal::interpreter::BytecodeRegisterOptimizer::GetInputRegister(), register_optimizer_, RegisterIsValid(), and v8::internal::interpreter::Register::ToOperand().
Referenced by v8::internal::interpreter::anonymous_namespace{bytecode-array-builder.cc}::OperandHelper< OperandType::kReg >::Convert().
GetIterator()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::GetIterator (Register object, int load_feedback_slot, int call_feedback_slot)
Definition at line 938 of file bytecode-array-builder.cc.
                                                                     {
  OutputGetIterator(object, load_feedback_slot, call_feedback_slot);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildGetIterator().
GetOutputRegisterListOperand()
uint32_t v8::internal::interpreter::BytecodeArrayBuilder::GetOutputRegisterListOperand (RegisterList reg_list)
Definition at line 1757 of file bytecode-array-builder.cc.
                           {
  DCHECK(RegisterListIsValid(reg_list));
  if (register_optimizer_)
    register_optimizer_->PrepareOutputRegisterList(reg_list);
  return static_cast<uint32_t>(reg_list.first_register().ToOperand());
}
References v8::internal::DCHECK(), v8::internal::interpreter::RegisterList::first_register(), v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareOutputRegisterList(), register_optimizer_, RegisterListIsValid(), and v8::internal::interpreter::Register::ToOperand().
Referenced by v8::internal::interpreter::anonymous_namespace{bytecode-array-builder.cc}::OperandHelper< OperandType::kRegOutList >::Convert(), v8::internal::interpreter::anonymous_namespace{bytecode-array-builder.cc}::OperandHelper< OperandType::kRegOutPair >::Convert(), and v8::internal::interpreter::anonymous_namespace{bytecode-array-builder.cc}::OperandHelper< OperandType::kRegOutTriple >::Convert().
GetOutputRegisterOperand()
uint32_t v8::internal::interpreter::BytecodeArrayBuilder::GetOutputRegisterOperand (Register reg)
Definition at line 1734 of file bytecode-array-builder.cc.
                                                                    {
  DCHECK(RegisterIsValid(reg));
  if (register_optimizer_) register_optimizer_->PrepareOutputRegister(reg);
  return static_cast<uint32_t>(reg.ToOperand());
}
References v8::internal::DCHECK(), v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareOutputRegister(), register_optimizer_, RegisterIsValid(), and v8::internal::interpreter::Register::ToOperand().
Referenced by v8::internal::interpreter::anonymous_namespace{bytecode-array-builder.cc}::OperandHelper< OperandType::kRegOut >::Convert().
GetRegisterOptimizer()
BytecodeRegisterOptimizer* v8::internal::interpreter::BytecodeArrayBuilder::GetRegisterOptimizer () [inline]
Definition at line 514 of file bytecode-array-builder.h.
                                                    {
    return register_optimizer_;
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::GetPotentialVariableInAccumulator(), v8::internal::interpreter::BytecodeGenerator::GetTypeHintForLocalVariable(), v8::internal::interpreter::BytecodeGenerator::IsVariableInRegister(), v8::internal::interpreter::BytecodeGenerator::SetVariableInRegister(), and v8::internal::interpreter::BytecodeGenerator::VisitForAccumulatorValueImpl().
GetSuperConstructor()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::GetSuperConstructor (Register out)
Definition at line 554 of file bytecode-array-builder.cc.
                                                                            {
  OutputGetSuperConstructor(out);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildGetAndCheckSuperConstructor().
GetTemplateObject()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::GetTemplateObject (size_t template_object_description_entry, int feedback_slot)
Definition at line 1135 of file bytecode-array-builder.cc.
                                                                 {
  OutputGetTemplateObject(template_object_description_entry, feedback_slot);
  return *this;
}
handler_table_builder()
HandlerTableBuilder* v8::internal::interpreter::BytecodeArrayBuilder::handler_table_builder () [inline], [private]
Definition at line 665 of file bytecode-array-builder.h.
                                               {
    return &handler_table_builder_;
  }
Referenced by MarkHandler(), MarkTryBegin(), MarkTryEnd(), and ToBytecodeArray().
Illegal()
BytecodeArrayBuilder& v8::internal::interpreter::BytecodeArrayBuilder::Illegal () [private]
IncBlockCounter()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::IncBlockCounter (int slot)
Definition at line 1452 of file bytecode-array-builder.cc.
                             {
  OutputIncBlockCounter(coverage_array_slot);
  return *this;
}
Referenced by v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter().
InitializeReturnPosition()
void v8::internal::interpreter::BytecodeArrayBuilder::InitializeReturnPosition (FunctionLiteral * literal)
Jump()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::Jump (BytecodeLabel * label)
Definition at line 1258 of file bytecode-array-builder.cc.
                                                                     {
  DCHECK(!label->is_bound());
  OutputJump(label, 0);
  return *this;
}
References v8::internal::DCHECK(), and v8::internal::interpreter::BytecodeLabel::is_bound().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCallIteratorMethod(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildLiteralCompareNil(), v8::internal::interpreter::BytecodeGenerator::BuildOptionalChain(), v8::internal::interpreter::BytecodeGenerator::BuildTest(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJump(), v8::internal::interpreter::TryCatchBuilder::EndTry(), v8::internal::interpreter::BytecodeGenerator::ControlScopeForDerivedConstructor::Execute(), v8::internal::interpreter::BytecodeGenerator::GenerateDerivedConstructorBody(), v8::internal::interpreter::ConditionalChainControlFlowBuilder::JumpToEnd(), v8::internal::interpreter::ConditionalControlFlowBuilder::JumpToEnd(), v8::internal::interpreter::TryFinallyBuilder::LeaveTry(), v8::internal::interpreter::BytecodeGenerator::VisitDelete(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryNullishExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNullishExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitNullishSubExpression().
JumpIfFalse()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::JumpIfFalse (ToBooleanMode mode, BytecodeLabel * label)
Definition at line 1276 of file bytecode-array-builder.cc.
                                                                              {
  DCHECK(!label->is_bound());
  if (mode == ToBooleanMode::kAlreadyBoolean) {
    OutputJumpIfFalse(label, 0);
  } else {
    DCHECK_EQ(mode, ToBooleanMode::kConvertToBoolean);
    OutputJumpIfToBooleanFalse(label, 0);
  }
  return *this;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::interpreter::BytecodeLabel::is_bound(), kAlreadyBoolean, kConvertToBoolean, and mode().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildTest(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfFalse(), JumpIfNotNil(), and v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndSubExpression().
JumpIfForInDone()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::JumpIfForInDone (BytecodeLabel * label, Register index, Register cache_length)
Definition at line 1365 of file bytecode-array-builder.cc.
                                                                 {
  DCHECK(!label->is_bound());
  OutputJumpIfForInDone(label, 0, index, cache_length);
  return *this;
}
References v8::internal::DCHECK(), v8::internal::index, and v8::internal::interpreter::BytecodeLabel::is_bound().
Referenced by v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfForInDone().
JumpIfJSReceiver()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::JumpIfJSReceiver (BytecodeLabel * label)
Definition at line 1358 of file bytecode-array-builder.cc.
                          {
  DCHECK(!label->is_bound());
  OutputJumpIfJSReceiver(label, 0);
  return *this;
}
References v8::internal::DCHECK(), and v8::internal::interpreter::BytecodeLabel::is_bound().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildGetIterator(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorClose(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorNext(), and v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn().
JumpIfNil()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::JumpIfNil (BytecodeLabel * label, Token::Value op, NilValue nil)
Definition at line 1322 of file bytecode-array-builder.cc.
                                                                    {
  if (op == Token::kEq) {
    // TODO(rmcilroy): Implement JumpIfUndetectable.
    return CompareUndetectable().JumpIfTrue(ToBooleanMode::kAlreadyBoolean,
                                            label);
  } else {
    DCHECK_EQ(Token::kEqStrict, op);
    if (nil == kUndefinedValue) {
      return JumpIfUndefined(label);
    } else {
      DCHECK_EQ(kNullValue, nil);
      return JumpIfNull(label);
    }
  }
}
References CompareUndetectable(), DCHECK_EQ, JumpIfNull(), JumpIfTrue(), JumpIfUndefined(), kAlreadyBoolean, kNullValue, and kUndefinedValue.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLiteralCompareNil().
JumpIfNotNil()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::JumpIfNotNil (BytecodeLabel * label, Token::Value op, NilValue nil)
Definition at line 1340 of file bytecode-array-builder.cc.
                                                                       {
  if (op == Token::kEq) {
    // TODO(rmcilroy): Implement JumpIfUndetectable.
    return CompareUndetectable().JumpIfFalse(ToBooleanMode::kAlreadyBoolean,
                                             label);
  } else {
    DCHECK_EQ(Token::kEqStrict, op);
    if (nil == kUndefinedValue) {
      return JumpIfNotUndefined(label);
    } else {
      DCHECK_EQ(kNullValue, nil);
      return JumpIfNotNull(label);
    }
  }
}
References CompareUndetectable(), DCHECK_EQ, JumpIfFalse(), JumpIfNotNull(), JumpIfNotUndefined(), kAlreadyBoolean, kNullValue, and kUndefinedValue.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLiteralCompareNil().
JumpIfNotNull()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::JumpIfNotNull (BytecodeLabel * label)
Definition at line 1294 of file bytecode-array-builder.cc.
                          {
  DCHECK(!label->is_bound());
  OutputJumpIfNotNull(label, 0);
  return *this;
}
References v8::internal::DCHECK(), and v8::internal::interpreter::BytecodeLabel::is_bound().
Referenced by JumpIfNotNil().
JumpIfNotUndefined()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::JumpIfNotUndefined (BytecodeLabel * label)
Definition at line 1315 of file bytecode-array-builder.cc.
                          {
  DCHECK(!label->is_bound());
  OutputJumpIfNotUndefined(label, 0);
  return *this;
}
References v8::internal::DCHECK(), and v8::internal::interpreter::BytecodeLabel::is_bound().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), and JumpIfNotNil().
JumpIfNull()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::JumpIfNull (BytecodeLabel * label)
Definition at line 1288 of file bytecode-array-builder.cc.
                                                                           {
  DCHECK(!label->is_bound());
  OutputJumpIfNull(label, 0);
  return *this;
}
References v8::internal::DCHECK(), and v8::internal::interpreter::BytecodeLabel::is_bound().
Referenced by JumpIfNil().
JumpIfTrue()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::JumpIfTrue (ToBooleanMode mode, BytecodeLabel * label)
Definition at line 1264 of file bytecode-array-builder.cc.
                                                                             {
  DCHECK(!label->is_bound());
  if (mode == ToBooleanMode::kAlreadyBoolean) {
    OutputJumpIfTrue(label, 0);
  } else {
    DCHECK_EQ(mode, ToBooleanMode::kConvertToBoolean);
    OutputJumpIfToBooleanTrue(label, 0);
  }
  return *this;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::interpreter::BytecodeLabel::is_bound(), kAlreadyBoolean, kConvertToBoolean, and mode().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAwait(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), v8::internal::interpreter::BytecodeGenerator::BuildSuperCallOptimization(), v8::internal::interpreter::BytecodeGenerator::BuildTest(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfTrue(), JumpIfNil(), v8::internal::interpreter::SwitchBuilder::JumpToCaseIfTrue(), and v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrSubExpression().
JumpIfUndefined()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::JumpIfUndefined (BytecodeLabel * label)
Definition at line 1301 of file bytecode-array-builder.cc.
                          {
  DCHECK(!label->is_bound());
  OutputJumpIfUndefined(label, 0);
  return *this;
}
References v8::internal::DCHECK(), and v8::internal::interpreter::BytecodeLabel::is_bound().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildInstanceMemberInitialization(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfUndefined(), v8::internal::interpreter::BytecodeGenerator::GenerateDerivedConstructorBody(), and JumpIfNil().
JumpIfUndefinedOrNull()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::JumpIfUndefinedOrNull (BytecodeLabel * label)
Definition at line 1308 of file bytecode-array-builder.cc.
                          {
  DCHECK(!label->is_bound());
  OutputJumpIfUndefinedOrNull(label, 0);
  return *this;
}
References v8::internal::DCHECK(), and v8::internal::interpreter::BytecodeLabel::is_bound().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCallIteratorMethod(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildGetIterator(), v8::internal::interpreter::BytecodeGenerator::VisitDelete(), v8::internal::interpreter::BytecodeGenerator::VisitForNullishTest(), v8::internal::interpreter::BytecodeGenerator::VisitNullishSubExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitPropertyLoad().
JumpLoop()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::JumpLoop (BytecodeLoopHeader * loop_header, int loop_depth, int position, int feedback_slot)
Definition at line 1372 of file bytecode-array-builder.cc.
                       {
  if (position != kNoSourcePosition) {
    // We need to attach a non-breakable source position to JumpLoop for its
    // implicit stack check, so we simply add it as expression position. There
    // can be a prior statement position from constructs like:
    //
    // do var x; while (false);
    //
    // A Nop could be inserted for empty statements, but since no code
    // is associated with these positions, instead we force the jump loop's
    // expression position which eliminates the empty statement's position.
    latest_source_info_.ForceExpressionPosition(position);
  }
  OutputJumpLoop(loop_header, loop_depth, feedback_slot);
  return *this;
}
References v8::internal::interpreter::BytecodeSourceInfo::ForceExpressionPosition(), v8::internal::kNoSourcePosition, latest_source_info_, and OutputJumpLoop().
Referenced by v8::internal::interpreter::LoopBuilder::JumpToHeader().
LoadAccumulatorWithRegister()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister (Register reg)
Definition at line 724 of file bytecode-array-builder.cc.
                  {
  if (register_optimizer_) {
    // Defer source info so that if we elide the bytecode transfer, we attach
    // the source info to a subsequent bytecode if it exists.
    SetDeferredSourceInfo(CurrentSourcePosition(Bytecode::kLdar));
    register_optimizer_->DoLdar(reg);
  } else {
    OutputLdar(reg);
  }
  return *this;
}
References CurrentSourcePosition(), v8::internal::interpreter::BytecodeRegisterOptimizer::DoLdar(), register_optimizer_, and SetDeferredSourceInfo().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildAwait(), v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope(), v8::internal::interpreter::BytecodeGenerator::BuildFillArrayWithIterator(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildGetAndCheckSuperConstructor(), v8::internal::interpreter::BytecodeGenerator::BuildInstanceInitializationAfterSuperCall(), v8::internal::interpreter::BytecodeGenerator::BuildLocalActivationContextInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildSetNamedProperty(), v8::internal::interpreter::BytecodeGenerator::BuildStoreGlobal(), v8::internal::interpreter::BytecodeGenerator::BuildSuperCallOptimization(), v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad(), v8::internal::interpreter::BytecodeGenerator::GenerateDerivedConstructorBody(), v8::internal::interpreter::BytecodeGenerator::VisitCallSuper(), v8::internal::interpreter::BytecodeGenerator::VisitNewTargetVariable(), v8::internal::interpreter::BytecodeGenerator::VisitPropertyLoad(), and v8::internal::interpreter::BytecodeGenerator::VisitThisFunctionVariable().
LoadAsyncIteratorProperty()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadAsyncIteratorProperty (Register object, int feedback_slot)
Definition at line 944 of file bytecode-array-builder.cc.
                                        {
  size_t name_index = AsyncIteratorSymbolConstantPoolEntry();
  OutputGetNamedProperty(object, name_index, feedback_slot);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildGetIterator().
LoadBoolean()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadBoolean (bool value)
Definition at line 720 of file bytecode-array-builder.cc.
                                                                  {
  return value ? LoadTrue() : LoadFalse();
}
References LoadFalse(), LoadTrue(), and v8::internal::value.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLiteralStrictCompareBoolean().
LoadClassFieldsInitializer()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadClassFieldsInitializer (Register constructor, int feedback_slot)
Definition at line 1023 of file bytecode-array-builder.cc.
                                             {
  size_t name_index = ClassFieldsSymbolConstantPoolEntry();
  OutputGetNamedProperty(constructor, name_index, feedback_slot);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildInstanceMemberInitialization().
LoadConstantPoolEntry()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadConstantPoolEntry (size_t entry)
Definition at line 641 of file bytecode-array-builder.cc.
                  {
  OutputLdaConstant(entry);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), and v8::internal::interpreter::BytecodeGenerator::BuildDeclareCall().
LoadContextSlot()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadContextSlot (Register context, Variable * variable, int depth, ContextSlotMutability immutable)
Definition at line 790 of file bytecode-array-builder.cc.
                                      {
  int slot_index = variable->index();
  if (mutability == kImmutableSlot) {
    if (context.is_current_context() && depth == 0) {
      OutputLdaImmutableCurrentContextSlot(slot_index);
    } else {
      OutputLdaImmutableContextSlot(context, slot_index, depth);
    }
  } else {
    DCHECK_EQ(kMutableSlot, mutability);
    if (variable->scope()->has_context_cells()) {
      if (context.is_current_context() && depth == 0) {
        OutputLdaCurrentContextSlot(slot_index);
      } else {
        OutputLdaContextSlot(context, slot_index, depth);
      }
    } else {
      if (context.is_current_context() && depth == 0) {
        OutputLdaCurrentContextSlotNoCell(slot_index);
      } else {
        OutputLdaContextSlotNoCell(context, slot_index, depth);
      }
    }
  }
  return *this;
}
References DCHECK_EQ, v8::internal::interpreter::Register::is_current_context(), kImmutableSlot, and kMutableSlot.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment(), and v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad().
LoadEnumeratedKeyedProperty()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadEnumeratedKeyedProperty (Register object, Register enum_index, Register cache_type, int feedback_slot)
Definition at line 923 of file bytecode-array-builder.cc.
                       {
  OutputGetEnumeratedKeyedProperty(object, enum_index, cache_type,
                                   feedback_slot);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLoadKeyedProperty().
LoadFalse()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadFalse ()
Definition at line 715 of file bytecode-array-builder.cc.
                                                      {
  OutputLdaFalse();
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), LoadBoolean(), and v8::internal::interpreter::BytecodeGenerator::VisitDelete().
LoadGlobal()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadGlobal (const AstRawString * name, int feedback_slot, TypeofMode typeof_mode)
Definition at line 764 of file bytecode-array-builder.cc.
                                                                               {
  size_t name_index = GetConstantPoolEntry(name);
  // Ensure that typeof mode is in sync with the IC slot kind.
  DCHECK_EQ(GetTypeofModeFromSlotKind(feedback_vector_spec()->GetKind(
                FeedbackVector::ToSlot(feedback_slot))),
            typeof_mode);
  switch (typeof_mode) {
    case TypeofMode::kInside:
      OutputLdaGlobalInsideTypeof(name_index, feedback_slot);
      break;
    case TypeofMode::kNotInside:
      OutputLdaGlobal(name_index, feedback_slot);
      break;
  }
  return *this;
}
References DCHECK_EQ, feedback_vector_spec(), GetConstantPoolEntry(), v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::GetKind(), v8::internal::GetTypeofModeFromSlotKind(), v8::internal::kInside, v8::internal::kNotInside, v8::internal::name, and v8::internal::FeedbackVector::ToSlot().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad().
LoadIteratorProperty()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadIteratorProperty (Register object, int feedback_slot)
Definition at line 931 of file bytecode-array-builder.cc.
                                        {
  size_t name_index = IteratorSymbolConstantPoolEntry();
  OutputGetNamedProperty(object, name_index, feedback_slot);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildGetIterator().
LoadKeyedProperty()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadKeyedProperty (Register object, int feedback_slot)
Definition at line 917 of file bytecode-array-builder.cc.
                                        {
  OutputGetKeyedProperty(object, feedback_slot);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildLoadKeyedProperty(), and v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck().
LoadLiteral() [1/6]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral (AstBigInt bigint)
Definition at line 689 of file bytecode-array-builder.cc.
                                                                        {
  size_t entry = GetConstantPoolEntry(bigint);
  OutputLdaConstant(entry);
  return *this;
}
References GetConstantPoolEntry().
LoadLiteral() [2/6]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral (const AstConsString * cons_string)
Definition at line 676 of file bytecode-array-builder.cc.
                                      {
  size_t entry = GetConstantPoolEntry(cons_string);
  OutputLdaConstant(entry);
  return *this;
}
References GetConstantPoolEntry().
LoadLiteral() [3/6]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral (const AstRawString * raw_string)
Definition at line 669 of file bytecode-array-builder.cc.
                                    {
  size_t entry = GetConstantPoolEntry(raw_string);
  OutputLdaConstant(entry);
  return *this;
}
References GetConstantPoolEntry().
LoadLiteral() [4/6]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral (const Scope * scope)
Definition at line 683 of file bytecode-array-builder.cc.
                                                                          {
  size_t entry = GetConstantPoolEntry(scope);
  OutputLdaConstant(entry);
  return *this;
}
References GetConstantPoolEntry().
LoadLiteral() [5/6]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral (double value)
Definition at line 657 of file bytecode-array-builder.cc.
                                                                    {
  // If we can encode the value as a Smi, we should.
  int smi;
  if (DoubleToSmiInteger(value, &smi)) {
    LoadLiteral(Smi::FromInt(smi));
  } else {
    size_t entry = GetConstantPoolEntry(value);
    OutputLdaConstant(entry);
  }
  return *this;
}
References v8::internal::DoubleToSmiInteger(), v8::internal::Smi::FromInt(), GetConstantPoolEntry(), LoadLiteral(), and v8::internal::value.
LoadLiteral() [6/6]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral (Tagged< Smi > value)
Definition at line 647 of file bytecode-array-builder.cc.
                                                                       {
  int32_t raw_smi = smi.value();
  if (raw_smi == 0) {
    OutputLdaZero();
  } else {
    OutputLdaSmi(raw_smi);
  }
  return *this;
}
References v8::internal::Tagged< Smi >::value().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAwait(), v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildInvalidPropertyAccess(), v8::internal::interpreter::BytecodeGenerator::BuildLoadPropertyKey(), v8::internal::interpreter::BytecodeGenerator::BuildNewLocalActivationContext(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicGet(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicSet(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn(), v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment(), LoadLiteral(), v8::internal::interpreter::BytecodeGenerator::PrepareAssignmentLhs(), v8::internal::interpreter::BytecodeGenerator::VisitDelete(), v8::internal::interpreter::BytecodeGenerator::VisitModuleNamespaceImports(), and v8::internal::interpreter::BytecodeGenerator::VisitNamedSuperPropertyLoad().
LoadLookupContextSlot()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadLookupContextSlot (const AstRawString * name, TypeofMode typeof_mode, ContextMode context_mode, int slot_index, int depth)
Definition at line 854 of file bytecode-array-builder.cc.
                               {
  size_t name_index = GetConstantPoolEntry(name);
  switch (typeof_mode) {
    case TypeofMode::kInside:
      if (context_mode == ContextMode::kHasContextCells) {
        OutputLdaLookupContextSlotInsideTypeof(name_index, slot_index, depth);
      } else {
        OutputLdaLookupContextSlotNoCellInsideTypeof(name_index, slot_index,
                                                     depth);
      }
      break;
    case TypeofMode::kNotInside:
      if (context_mode == ContextMode::kHasContextCells) {
        OutputLdaLookupContextSlot(name_index, slot_index, depth);
      } else {
        OutputLdaLookupContextSlotNoCell(name_index, slot_index, depth);
      }
      break;
  }
  return *this;
}
References GetConstantPoolEntry(), v8::internal::kHasContextCells, v8::internal::kInside, v8::internal::kNotInside, and v8::internal::name.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad().
LoadLookupGlobalSlot()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadLookupGlobalSlot (const AstRawString * name, TypeofMode typeof_mode, int feedback_slot, int depth)
Definition at line 878 of file bytecode-array-builder.cc.
               {
  size_t name_index = GetConstantPoolEntry(name);
  switch (typeof_mode) {
    case TypeofMode::kInside:
      OutputLdaLookupGlobalSlotInsideTypeof(name_index, feedback_slot, depth);
      break;
    case TypeofMode::kNotInside:
      OutputLdaLookupGlobalSlot(name_index, feedback_slot, depth);
      break;
  }
  return *this;
}
References GetConstantPoolEntry(), v8::internal::kInside, v8::internal::kNotInside, and v8::internal::name.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad().
LoadLookupSlot()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadLookupSlot (const AstRawString * name, TypeofMode typeof_mode)
Definition at line 840 of file bytecode-array-builder.cc.
                                                      {
  size_t name_index = GetConstantPoolEntry(name);
  switch (typeof_mode) {
    case TypeofMode::kInside:
      OutputLdaLookupSlotInsideTypeof(name_index);
      break;
    case TypeofMode::kNotInside:
      OutputLdaLookupSlot(name_index);
      break;
  }
  return *this;
}
References GetConstantPoolEntry(), v8::internal::kInside, v8::internal::kNotInside, and v8::internal::name.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad().
LoadModuleVariable()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadModuleVariable (int cell_index, int depth)
Definition at line 1489 of file bytecode-array-builder.cc.
                                                                          {
  OutputLdaModuleVariable(cell_index, depth);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment(), and v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad().
LoadNamedProperty()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadNamedProperty (Register object, const AstRawString * name, int feedback_slot)
Definition at line 903 of file bytecode-array-builder.cc.
                                                                  {
  size_t name_index = GetConstantPoolEntry(name);
  OutputGetNamedProperty(object, name_index, feedback_slot);
  return *this;
}
References GetConstantPoolEntry(), and v8::internal::name.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCallIteratorMethod(), v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildFillArrayWithIterator(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildGetIteratorRecord(), and v8::internal::interpreter::BytecodeGenerator::BuildLoadNamedProperty().
LoadNamedPropertyFromSuper()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadNamedPropertyFromSuper (Register object, const AstRawString * name, int feedback_slot)
Definition at line 910 of file bytecode-array-builder.cc.
                                                                  {
  size_t name_index = GetConstantPoolEntry(name);
  OutputGetNamedPropertyFromSuper(object, name_index, feedback_slot);
  return *this;
}
References GetConstantPoolEntry(), and v8::internal::name.
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitNamedSuperPropertyLoad().
LoadNull()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadNull ()
Definition at line 700 of file bytecode-array-builder.cc.
                                                     {
  OutputLdaNull();
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitLiteralAccessor().
LoadTheHole()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadTheHole ()
Definition at line 705 of file bytecode-array-builder.cc.
                                                        {
  OutputLdaTheHole();
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope(), v8::internal::interpreter::BytecodeGenerator::BuildTryFinally(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncFunctionBody(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncGeneratorFunctionBody(), and v8::internal::interpreter::BytecodeGenerator::VisitForAccumulatorValueOrTheHole().
LoadTrue()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadTrue ()
Definition at line 710 of file bytecode-array-builder.cc.
                                                     {
  OutputLdaTrue();
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAsyncReturn(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope(), LoadBoolean(), and v8::internal::interpreter::BytecodeGenerator::VisitDelete().
LoadUndefined()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LoadUndefined ()
Definition at line 695 of file bytecode-array-builder.cc.
                                                          {
  OutputLdaUndefined();
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildOptionalChain(), v8::internal::interpreter::BytecodeGenerator::BuildPushUndefinedIntoRegisterList(), v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad(), v8::internal::interpreter::BytecodeGenerator::GenerateBodyStatements(), and v8::internal::interpreter::BytecodeGenerator::VisitVoid().
Local()
Register v8::internal::interpreter::BytecodeArrayBuilder::Local (int index) const
Definition at line 85 of file bytecode-array-builder.cc.
                                                    {
  DCHECK_LT(index, locals_count());
  return Register(index);
}
References DCHECK_LT, v8::internal::index, locals_count(), and v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment(), and v8::internal::interpreter::BytecodeGenerator::GetRegisterForLocalVariable().
locals_count()
int v8::internal::interpreter::BytecodeArrayBuilder::locals_count () const [inline]
Definition at line 69 of file bytecode-array-builder.h.
                           {
    DCHECK_GE(local_register_count_, 0);
    return local_register_count_;
  }
References DCHECK_GE.
Referenced by Local().
LogicalNot()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::LogicalNot (ToBooleanMode mode)
Definition at line 539 of file bytecode-array-builder.cc.
                                                                         {
  if (mode == ToBooleanMode::kAlreadyBoolean) {
    OutputLogicalNot();
  } else {
    DCHECK_EQ(mode, ToBooleanMode::kConvertToBoolean);
    OutputToBooleanLogicalNot();
  }
  return *this;
}
References DCHECK_EQ, kAlreadyBoolean, kConvertToBoolean, and mode().
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitNot().
MarkHandler()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::MarkHandler (int handler_id, HandlerTable::CatchPrediction will_catch)
Definition at line 1226 of file bytecode-array-builder.cc.
                                                                  {
  // The handler starts a new basic block, and any reasonable try block won't
  // let control fall through into it.
  DCHECK_IMPLIES(register_optimizer_,
                 register_optimizer_->EnsureAllRegistersAreFlushed());
  DCHECK_IMPLIES(register_optimizer_,
                 register_optimizer_->IsAccumulatorReset());
  bytecode_array_writer_.BindHandlerTarget(handler_table_builder(), handler_id);
  handler_table_builder()->SetPrediction(handler_id, catch_prediction);
  return *this;
}
References v8::internal::interpreter::BytecodeArrayWriter::BindHandlerTarget(), bytecode_array_writer_, DCHECK_IMPLIES, v8::internal::interpreter::BytecodeRegisterOptimizer::EnsureAllRegistersAreFlushed(), handler_table_builder(), v8::internal::interpreter::BytecodeRegisterOptimizer::IsAccumulatorReset(), register_optimizer_, and v8::internal::interpreter::HandlerTableBuilder::SetPrediction().
Referenced by v8::internal::interpreter::TryFinallyBuilder::BeginHandler(), and v8::internal::interpreter::TryCatchBuilder::EndTry().
MarkTryBegin()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::MarkTryBegin (int handler_id, Register context)
Definition at line 1239 of file bytecode-array-builder.cc.
                                                                           {
  // Flush registers to make sure everything visible to the handler is
  // materialized.
  if (register_optimizer_) register_optimizer_->Flush();
  bytecode_array_writer_.BindTryRegionStart(handler_table_builder(),
                                            handler_id);
  handler_table_builder()->SetContextRegister(handler_id, context);
  return *this;
}
References v8::internal::interpreter::BytecodeArrayWriter::BindTryRegionStart(), bytecode_array_writer_, v8::internal::interpreter::BytecodeRegisterOptimizer::Flush(), handler_table_builder(), register_optimizer_, and v8::internal::interpreter::HandlerTableBuilder::SetContextRegister().
Referenced by v8::internal::interpreter::TryCatchBuilder::BeginTry(), and v8::internal::interpreter::TryFinallyBuilder::BeginTry().
MarkTryEnd()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::MarkTryEnd (int handler_id)
Definition at line 1250 of file bytecode-array-builder.cc.
                                                                     {
  if (register_optimizer_) {
    register_optimizer_->ResetTypeHintForAccumulator();
  }
  bytecode_array_writer_.BindTryRegionEnd(handler_table_builder(), handler_id);
  return *this;
}
References v8::internal::interpreter::BytecodeArrayWriter::BindTryRegionEnd(), bytecode_array_writer_, handler_table_builder(), register_optimizer_, and v8::internal::interpreter::BytecodeRegisterOptimizer::ResetTypeHintForAccumulator().
Referenced by v8::internal::interpreter::TryCatchBuilder::EndTry(), and v8::internal::interpreter::TryFinallyBuilder::EndTry().
max_arguments()
uint16_t v8::internal::interpreter::BytecodeArrayBuilder::max_arguments () const [inline]
Definition at line 62 of file bytecode-array-builder.h.
{ return max_arguments_; }
Referenced by ToBytecodeArray().
MaybePopSourcePosition()
std::optional<BytecodeSourceInfo> v8::internal::interpreter::BytecodeArrayBuilder::MaybePopSourcePosition (int scope_start) [inline]
Definition at line 539 of file bytecode-array-builder.h.
                                                                          {
    if (!latest_source_info_.is_valid() ||
        latest_source_info_.source_position() < scope_start) {
      return std::nullopt;
    }
    BytecodeSourceInfo source_info = latest_source_info_;
    latest_source_info_.set_invalid();
    return source_info;
  }
References v8::internal::interpreter::BytecodeSourceInfo::set_invalid().
MoveRegister()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister (Register from, Register to)
Definition at line 750 of file bytecode-array-builder.cc.
                                                                      {
  DCHECK(from != to);
  if (register_optimizer_) {
    // Defer source info so that if we elide the bytecode transfer, we attach
    // the source info to a subsequent bytecode if it exists.
    SetDeferredSourceInfo(CurrentSourcePosition(Bytecode::kMov));
    register_optimizer_->DoMov(from, to);
  } else {
    OutputMov(from, to);
  }
  return *this;
}
References CurrentSourcePosition(), v8::internal::DCHECK(), v8::internal::interpreter::BytecodeRegisterOptimizer::DoMov(), register_optimizer_, and SetDeferredSourceInfo().
Referenced by v8::internal::interpreter::BytecodeGenerator::AddDisposableValue(), v8::internal::interpreter::BytecodeGenerator::BuildAsyncReturn(), v8::internal::interpreter::BytecodeGenerator::BuildAwait(), v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildDeclareCall(), v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope(), v8::internal::interpreter::BytecodeGenerator::BuildGeneratorObjectVariableInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildInstanceMemberInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicGet(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicSet(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateGetterAccess(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateSetterAccess(), v8::internal::interpreter::BytecodeGenerator::BuildSuperCallOptimization(), v8::internal::interpreter::BytecodeGenerator::BuildTryCatch(), v8::internal::interpreter::BytecodeGenerator::BuildTryFinally(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncFunctionBody(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncGeneratorFunctionBody(), v8::internal::interpreter::BytecodeGenerator::VisitKeyedSuperPropertyLoad(), and v8::internal::interpreter::BytecodeGenerator::VisitNamedSuperPropertyLoad().
NewHandlerEntry()
int v8::internal::interpreter::BytecodeArrayBuilder::NewHandlerEntry () [inline]
Definition at line 508 of file bytecode-array-builder.h.
{ return handler_table_builder()->NewHandlerEntry(); }
operator=()
BytecodeArrayBuilder& v8::internal::interpreter::BytecodeArrayBuilder::operator= (const BytecodeArrayBuilder &) [delete]
OutputJumpLoop()
void v8::internal::interpreter::BytecodeArrayBuilder::OutputJumpLoop (BytecodeLoopHeader * loop_header, int loop_depth, int feedback_slot) [inline], [private]
Definition at line 396 of file bytecode-array-builder.cc.
                                                                             {
  BytecodeNode node(CreateJumpLoopNode(0, loop_depth, feedback_slot));
  WriteJumpLoop(&node, loop_header);
}
References WriteJumpLoop().
Referenced by JumpLoop().
OutputLdarRaw()
void v8::internal::interpreter::BytecodeArrayBuilder::OutputLdarRaw (Register reg)
Definition at line 198 of file bytecode-array-builder.cc.
                                                     {
  uint32_t operand = static_cast<uint32_t>(reg.ToOperand());
  BytecodeNode node(BytecodeNode::Ldar(BytecodeSourceInfo(), operand));
  Write(&node);
}
References v8::internal::interpreter::Register::ToOperand(), and Write().
Referenced by v8::internal::interpreter::RegisterTransferWriter::EmitLdar().
OutputMovRaw()
void v8::internal::interpreter::BytecodeArrayBuilder::OutputMovRaw (Register src, Register dest)
Definition at line 213 of file bytecode-array-builder.cc.
                                                                   {
  uint32_t operand0 = static_cast<uint32_t>(src.ToOperand());
  uint32_t operand1 = static_cast<uint32_t>(dest.ToOperand());
  BytecodeNode node(
      BytecodeNode::Mov(BytecodeSourceInfo(), operand0, operand1));
  Write(&node);
}
References v8::internal::interpreter::Register::ToOperand(), and Write().
Referenced by v8::internal::interpreter::RegisterTransferWriter::EmitMov().
OutputStarRaw()
void v8::internal::interpreter::BytecodeArrayBuilder::OutputStarRaw (Register reg)
Definition at line 204 of file bytecode-array-builder.cc.
                                                     {
  uint32_t operand = static_cast<uint32_t>(reg.ToOperand());
  std::optional<Bytecode> short_code = reg.TryToShortStar();
  BytecodeNode node = short_code
                          ? BytecodeNode(*short_code)
                          : BytecodeNode::Star(BytecodeSourceInfo(), operand);
  Write(&node);
}
References v8::internal::interpreter::Register::ToOperand(), v8::internal::interpreter::Register::TryToShortStar(), and Write().
Referenced by v8::internal::interpreter::RegisterTransferWriter::EmitStar(), and StoreAccumulatorInRegister().
OutputSwitchOnSmiNoFeedback()
void v8::internal::interpreter::BytecodeArrayBuilder::OutputSwitchOnSmiNoFeedback (BytecodeJumpTable * jump_table) [inline], [private]
Definition at line 402 of file bytecode-array-builder.cc.
                                   {
  BytecodeNode node(CreateSwitchOnSmiNoFeedbackNode(
      jump_table->constant_pool_index(), jump_table->size(),
      jump_table->case_value_base()));
  WriteSwitch(&node, jump_table);
}
References v8::internal::interpreter::BytecodeJumpTable::case_value_base(), v8::internal::interpreter::BytecodeJumpTable::constant_pool_index(), v8::internal::interpreter::BytecodeJumpTable::size(), and WriteSwitch().
Referenced by SwitchOnSmiNoFeedback().
Parameter()
Register v8::internal::interpreter::BytecodeArrayBuilder::Parameter (int parameter_index) const
Definition at line 74 of file bytecode-array-builder.cc.
                                                                  {
  DCHECK_GE(parameter_index, 0);
  // The parameter indices are shifted by 1 (receiver is the
  // first entry).
  return Register::FromParameterIndex(parameter_index + 1);
}
References DCHECK_GE, and v8::internal::interpreter::Register::FromParameterIndex().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment(), and v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad().
parameter_count()
uint16_t v8::internal::interpreter::BytecodeArrayBuilder::parameter_count () const [inline]
Definition at line 61 of file bytecode-array-builder.h.
{ return parameter_count_; }
Referenced by BytecodeArrayBuilder(), RegisterIsValid(), and ToBytecodeArray().
PopContext()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::PopContext (Register context)
Definition at line 1146 of file bytecode-array-builder.cc.
                                                                       {
  OutputPopContext(context);
  return *this;
}
PrepareToOutputBytecode()
template<Bytecode bytecode, ImplicitRegisterUse implicit_register_use>
void v8::internal::interpreter::BytecodeArrayBuilder::PrepareToOutputBytecode [private]
Definition at line 1722 of file bytecode-array-builder.cc.
                                                   {
  if (register_optimizer_) {
    register_optimizer_->PrepareForBytecode<bytecode, implicit_register_use>();
  }
}
References v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareForBytecode(), and register_optimizer_.
Referenced by v8::internal::interpreter::BytecodeNodeBuilder< bytecode, implicit_register_use, operand_types >::Make().
PushContext()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::PushContext (Register context)
Definition at line 1141 of file bytecode-array-builder.cc.
                                                                        {
  OutputPushContext(context);
  return *this;
}
PushSourcePosition()
void v8::internal::interpreter::BytecodeArrayBuilder::PushSourcePosition (BytecodeSourceInfo source_info) [inline]
Definition at line 549 of file bytecode-array-builder.h.
                                                          {
    DCHECK(!latest_source_info_.is_valid());
    latest_source_info_ = source_info;
  }
References v8::internal::DCHECK().
Receiver()
Register v8::internal::interpreter::BytecodeArrayBuilder::Receiver () const
Definition at line 81 of file bytecode-array-builder.cc.
                                              {
  return Register::FromParameterIndex(0);
}
References v8::internal::interpreter::Register::FromParameterIndex().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment(), and v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad().
register_allocator() [1/2]
BytecodeRegisterAllocator* v8::internal::interpreter::BytecodeArrayBuilder::register_allocator () [inline]
Definition at line 597 of file bytecode-array-builder.h.
                                                  {
    return &register_allocator_;
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::register_allocator(), and RegisterIsValid().
register_allocator() [2/2]
const BytecodeRegisterAllocator* v8::internal::interpreter::BytecodeArrayBuilder::register_allocator () const [inline]
Definition at line 600 of file bytecode-array-builder.h.
                                                              {
    return &register_allocator_;
  }
RegisterIsValid()
bool v8::internal::interpreter::BytecodeArrayBuilder::RegisterIsValid (Register reg) const [private]
Definition at line 1690 of file bytecode-array-builder.cc.
                                                             {
  if (!reg.is_valid()) {
    return false;
  }
  if (reg.is_current_context() || reg.is_function_closure()) {
    return true;
  } else if (reg.is_parameter()) {
    int parameter_index = reg.ToParameterIndex();
    return parameter_index >= 0 && parameter_index < parameter_count();
  } else if (reg.index() < fixed_register_count()) {
    return true;
  } else {
    return register_allocator()->RegisterIsLive(reg);
  }
}
References fixed_register_count(), v8::internal::interpreter::Register::index(), v8::internal::interpreter::Register::is_current_context(), v8::internal::interpreter::Register::is_function_closure(), v8::internal::interpreter::Register::is_parameter(), v8::internal::interpreter::Register::is_valid(), parameter_count(), register_allocator(), v8::internal::interpreter::BytecodeRegisterAllocator::RegisterIsLive(), and v8::internal::interpreter::Register::ToParameterIndex().
Referenced by GetInputOutputRegisterOperand(), GetInputRegisterOperand(), GetOutputRegisterOperand(), and RegisterListIsValid().
RegisterListIsValid()
bool v8::internal::interpreter::BytecodeArrayBuilder::RegisterListIsValid (RegisterList reg_list) const [private]
Definition at line 1707 of file bytecode-array-builder.cc.
                                                                          {
  if (reg_list.register_count() == 0) {
    return reg_list.first_register() == Register(0);
  } else {
    int first_reg_index = reg_list.first_register().index();
    for (int i = 0; i < reg_list.register_count(); i++) {
      if (!RegisterIsValid(Register(first_reg_index + i))) {
        return false;
      }
    }
    return true;
  }
}
References v8::internal::interpreter::RegisterList::first_register(), v8::internal::interpreter::Register::index(), v8::internal::ETWJITInterface::Register(), v8::internal::interpreter::RegisterList::register_count(), and RegisterIsValid().
Referenced by GetInputRegisterListOperand(), and GetOutputRegisterListOperand().
RemainderOfBlockIsDead()
bool v8::internal::interpreter::BytecodeArrayBuilder::RemainderOfBlockIsDead () const [inline]
Definition at line 577 of file bytecode-array-builder.h.
                                      {
    return bytecode_array_writer_.RemainderOfBlockIsDead();
  }
Referenced by ToBytecodeArray().
ResumeGenerator()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ResumeGenerator (Register generator, RegisterList registers)
Definition at line 1511 of file bytecode-array-builder.cc.
                                                {
  OutputResumeGenerator(generator, registers, registers.register_count());
  return *this;
}
References v8::internal::interpreter::RegisterList::register_count().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildSuspendPoint().
ReThrow()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ReThrow ()
Definition at line 1407 of file bytecode-array-builder.cc.
                                                    {
  OutputReThrow();
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAwait(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), and v8::internal::interpreter::BytecodeGenerator::BuildReThrow().
Return()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::Return ()
Definition at line 1419 of file bytecode-array-builder.cc.
                                                   {
  OutputReturn();
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildReturn().
SetDeferredConstantPoolEntry()
void v8::internal::interpreter::BytecodeArrayBuilder::SetDeferredConstantPoolEntry (size_t entry, Handle< Object > object)
Definition at line 1685 of file bytecode-array-builder.cc.
                                                                               {
  constant_array_builder()->SetDeferredAt(entry, object);
}
References constant_array_builder(), and v8::internal::interpreter::ConstantArrayBuilder::SetDeferredAt().
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateDeferredConstants().
SetDeferredSourceInfo()
void v8::internal::interpreter::BytecodeArrayBuilder::SetDeferredSourceInfo (BytecodeSourceInfo source_info) [private]
Definition at line 157 of file bytecode-array-builder.cc.
                                    {
  if (!source_info.is_valid()) return;
  deferred_source_info_ = source_info;
}
References deferred_source_info_, and v8::internal::interpreter::BytecodeSourceInfo::is_valid().
Referenced by LoadAccumulatorWithRegister(), MoveRegister(), and StoreAccumulatorInRegister().
SetExpressionAsStatementPosition()
void v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionAsStatementPosition (Expression * expr, bool is_breakable = true) [inline]
Definition at line 572 of file bytecode-array-builder.h.
                                                                  {
    SetStatementPosition(expr->position(), is_breakable);
  }
References v8::internal::AstNode::position().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), v8::internal::interpreter::BytecodeGenerator::VisitCommaExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryCommaExpression().
SetExpressionPosition() [1/2]
void v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionPosition (Expression * expr) [inline]
Definition at line 559 of file bytecode-array-builder.h.
                                               {
    SetExpressionPosition(expr->position());
  }
References v8::internal::AstNode::position().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn(), v8::internal::interpreter::BytecodeGenerator::BuildSuspendPoint(), v8::internal::interpreter::BytecodeGenerator::VisitArithmeticExpression(), v8::internal::interpreter::BytecodeGenerator::VisitCallSuper(), v8::internal::interpreter::BytecodeGenerator::VisitKeyedSuperPropertyLoad(), v8::internal::interpreter::BytecodeGenerator::VisitNamedSuperPropertyLoad(), v8::internal::interpreter::BytecodeGenerator::VisitNaryArithmeticExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitPropertyLoad().
SetExpressionPosition() [2/2]
void v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionPosition (int position) [inline]
Definition at line 563 of file bytecode-array-builder.h.
                                           {
    if (position == kNoSourcePosition) return;
    if (!latest_source_info_.is_statement()) {
      // Ensure the current expression position is overwritten with the
      // latest value.
      latest_source_info_.MakeExpressionPosition(position);
    }
  }
References v8::internal::kNoSourcePosition.
SetKeyedProperty()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::SetKeyedProperty (Register object, Register key, int feedback_slot, LanguageMode language_mode)
Definition at line 987 of file bytecode-array-builder.cc.
                                {
  // Ensure that language mode is in sync with the IC slot kind.
  DCHECK_EQ(GetLanguageModeFromSlotKind(feedback_vector_spec()->GetKind(
                FeedbackVector::ToSlot(feedback_slot))),
            language_mode);
  OutputSetKeyedProperty(object, key, feedback_slot);
  return *this;
}
References DCHECK_EQ, feedback_vector_spec(), v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::GetKind(), v8::internal::GetLanguageModeFromSlotKind(), v8::internal::key, and v8::internal::FeedbackVector::ToSlot().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAssignment().
SetNamedProperty() [1/2]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::SetNamedProperty (Register object, const AstRawString * name, int feedback_slot, LanguageMode language_mode)
Definition at line 969 of file bytecode-array-builder.cc.
                                {
  size_t name_index = GetConstantPoolEntry(name);
  return SetNamedProperty(object, name_index, feedback_slot, language_mode);
}
References GetConstantPoolEntry(), and v8::internal::name.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildSetNamedProperty(), and StoreClassFieldsInitializer().
SetNamedProperty() [2/2]
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::SetNamedProperty (Register object, size_t constant_pool_entry, int feedback_slot, LanguageMode language_mode)
Definition at line 958 of file bytecode-array-builder.cc.
                                {
  // Ensure that language mode is in sync with the IC slot kind.
  DCHECK_EQ(GetLanguageModeFromSlotKind(feedback_vector_spec()->GetKind(
                FeedbackVector::ToSlot(feedback_slot))),
            language_mode);
  OutputSetNamedProperty(object, name_index, feedback_slot);
  return *this;
}
References DCHECK_EQ, feedback_vector_spec(), v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::GetKind(), v8::internal::GetLanguageModeFromSlotKind(), and v8::internal::FeedbackVector::ToSlot().
SetPendingMessage()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::SetPendingMessage ()
Definition at line 1397 of file bytecode-array-builder.cc.
                                                              {
  OutputSetPendingMessage();
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncFunctionBody(), and v8::internal::interpreter::BytecodeGenerator::GenerateAsyncGeneratorFunctionBody().
SetStatementPosition() [1/2]
void v8::internal::interpreter::BytecodeArrayBuilder::SetStatementPosition (int position, bool is_breakable = true) [inline]
Definition at line 554 of file bytecode-array-builder.h.
                                                                    {
    if (position == kNoSourcePosition) return;
    latest_source_info_.MakeStatementPosition(position, is_breakable);
  }
References v8::internal::kNoSourcePosition.
SetStatementPosition() [2/2]
void v8::internal::interpreter::BytecodeArrayBuilder::SetStatementPosition (Statement * stmt, bool is_breakable = true) [inline]
Definition at line 535 of file bytecode-array-builder.h.
                                                                       {
    SetStatementPosition(stmt->position(), is_breakable);
  }
References v8::internal::AstNode::position().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildReturn(), and v8::internal::interpreter::BytecodeGenerator::ControlScopeForDerivedConstructor::Execute().
StoreAccumulatorInRegister()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister (Register reg)
Definition at line 737 of file bytecode-array-builder.cc.
                  {
  if (register_optimizer_) {
    // Defer source info so that if we elide the bytecode transfer, we attach
    // the source info to a subsequent bytecode if it exists.
    SetDeferredSourceInfo(CurrentSourcePosition(Bytecode::kStar));
    register_optimizer_->DoStar(reg);
  } else {
    OutputStarRaw(reg);
  }
  return *this;
}
References CurrentSourcePosition(), v8::internal::interpreter::BytecodeRegisterOptimizer::DoStar(), OutputStarRaw(), register_optimizer_, and SetDeferredSourceInfo().
Referenced by v8::internal::interpreter::BytecodeGenerator::AddDisposableValue(), v8::internal::interpreter::BytecodeGenerator::BuildAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildAsyncReturn(), v8::internal::interpreter::BytecodeGenerator::BuildAwait(), v8::internal::interpreter::BytecodeGenerator::BuildCallIteratorMethod(), v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildCreateObjectLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildDeclareCall(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope(), v8::internal::interpreter::BytecodeGenerator::BuildFillArrayWithIterator(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildGeneratorObjectVariableInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildGetIterator(), v8::internal::interpreter::BytecodeGenerator::BuildGetIteratorRecord(), v8::internal::interpreter::BytecodeGenerator::BuildInstanceMemberInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildInvalidPropertyAccess(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorClose(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorNext(), v8::internal::interpreter::BytecodeGenerator::BuildLiteralStrictCompareBoolean(), v8::internal::interpreter::BytecodeGenerator::BuildLoadPropertyKey(), v8::internal::interpreter::BytecodeGenerator::BuildNewLocalActivationContext(), v8::internal::interpreter::BytecodeGenerator::BuildNewLocalCatchContext(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicGet(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicSet(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateGetterAccess(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateSetterAccess(), v8::internal::interpreter::BytecodeGenerator::BuildPushUndefinedIntoRegisterList(), v8::internal::interpreter::BytecodeGenerator::BuildReturn(), v8::internal::interpreter::BytecodeGenerator::BuildSetNamedProperty(), v8::internal::interpreter::BytecodeGenerator::BuildStoreGlobal(), v8::internal::interpreter::BytecodeGenerator::BuildTryFinally(), v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment(), v8::internal::interpreter::BytecodeGenerator::DisposablesStackScope::DisposablesStackScope(), v8::internal::interpreter::BytecodeGenerator::ControlScopeForDerivedConstructor::Execute(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncFunctionBody(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncGeneratorFunctionBody(), v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::MultipleEntryBlockContextScope(), v8::internal::interpreter::BytecodeGenerator::PrepareAssignmentLhs(), v8::internal::interpreter::BytecodeGenerator::VisitAndPushIntoRegisterList(), v8::internal::interpreter::BytecodeGenerator::VisitArithmeticExpression(), v8::internal::interpreter::BytecodeGenerator::VisitCallSuper(), v8::internal::interpreter::BytecodeGenerator::VisitDelete(), v8::internal::interpreter::BytecodeGenerator::VisitForRegisterValue(), v8::internal::interpreter::BytecodeGenerator::VisitKeyedSuperPropertyLoad(), v8::internal::interpreter::BytecodeGenerator::VisitLiteralAccessor(), v8::internal::interpreter::BytecodeGenerator::VisitModuleNamespaceImports(), v8::internal::interpreter::BytecodeGenerator::VisitNamedSuperPropertyLoad(), v8::internal::interpreter::BytecodeGenerator::VisitNaryArithmeticExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitPropertyLoadForRegister().
StoreClassFieldsInitializer()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::StoreClassFieldsInitializer (Register constructor, int feedback_slot)
Definition at line 1016 of file bytecode-array-builder.cc.
                                             {
  size_t name_index = ClassFieldsSymbolConstantPoolEntry();
  return SetNamedProperty(constructor, name_index, feedback_slot,
                          LanguageMode::kStrict);
}
References v8::internal::kStrict, and SetNamedProperty().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral().
StoreContextSlot()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::StoreContextSlot (Register context, Variable * variable, int depth)
Definition at line 819 of file bytecode-array-builder.cc.
                                                                        {
  int slot_index = variable->index();
  if (variable->maybe_assigned() != kNotAssigned &&
      variable->scope()->has_context_cells()) {
    if (context.is_current_context() && depth == 0) {
      OutputStaCurrentContextSlot(slot_index);
    } else {
      OutputStaContextSlot(context, slot_index, depth);
    }
  } else {
    if (context.is_current_context() && depth == 0) {
      OutputStaCurrentContextSlotNoCell(slot_index);
    } else {
      OutputStaContextSlotNoCell(context, slot_index, depth);
    }
  }
  return *this;
}
References v8::internal::interpreter::Register::is_current_context(), and v8::internal::kNotAssigned.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLocalActivationContextInitialization(), and v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment().
StoreGlobal()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::StoreGlobal (const AstRawString * name, int feedback_slot)
Definition at line 783 of file bytecode-array-builder.cc.
                                                 {
  size_t name_index = GetConstantPoolEntry(name);
  OutputStaGlobal(name_index, feedback_slot);
  return *this;
}
References GetConstantPoolEntry(), and v8::internal::name.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildStoreGlobal().
StoreInArrayLiteral()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::StoreInArrayLiteral (Register array, Register index, int feedback_slot)
Definition at line 1010 of file bytecode-array-builder.cc.
                                                       {
  OutputStaInArrayLiteral(array, index, feedback_slot);
  return *this;
}
References v8::internal::index.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), and v8::internal::interpreter::BytecodeGenerator::BuildFillArrayWithIterator().
StoreLookupSlot()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::StoreLookupSlot (const AstRawString * name, LanguageMode language_mode, LookupHoistingMode lookup_hoisting_mode)
Definition at line 893 of file bytecode-array-builder.cc.
                                             {
  size_t name_index = GetConstantPoolEntry(name);
  uint8_t flags =
      StoreLookupSlotFlags::Encode(language_mode, lookup_hoisting_mode);
  OutputStaLookupSlot(name_index, flags);
  return *this;
}
References v8::internal::interpreter::StoreLookupSlotFlags::Encode(), v8::internal::flags, GetConstantPoolEntry(), and v8::internal::name.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment().
StoreModuleVariable()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::StoreModuleVariable (int cell_index, int depth)
Definition at line 1483 of file bytecode-array-builder.cc.
                                                                           {
  OutputStaModuleVariable(cell_index, depth);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment().
SuspendGenerator()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::SuspendGenerator (Register generator, RegisterList registers, int suspend_id)
Definition at line 1495 of file bytecode-array-builder.cc.
                                                                {
  OutputSuspendGenerator(generator, registers, registers.register_count(),
                         suspend_id);
  return *this;
}
References v8::internal::interpreter::RegisterList::register_count().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildSuspendPoint().
SwitchOnGeneratorState()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::SwitchOnGeneratorState (Register generator, BytecodeJumpTable * jump_table)
Definition at line 1502 of file bytecode-array-builder.cc.
                                                       {
  DCHECK_EQ(jump_table->case_value_base(), 0);
  BytecodeNode node(CreateSwitchOnGeneratorStateNode(
      generator, jump_table->constant_pool_index(), jump_table->size()));
  WriteSwitch(&node, jump_table);
  return *this;
}
References v8::internal::interpreter::BytecodeJumpTable::case_value_base(), v8::internal::interpreter::BytecodeJumpTable::constant_pool_index(), DCHECK_EQ, v8::internal::interpreter::BytecodeJumpTable::size(), and WriteSwitch().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildGeneratorPrologue().
SwitchOnSmiNoFeedback()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::SwitchOnSmiNoFeedback (BytecodeJumpTable * jump_table)
Definition at line 1391 of file bytecode-array-builder.cc.
                                   {
  OutputSwitchOnSmiNoFeedback(jump_table);
  return *this;
}
References OutputSwitchOnSmiNoFeedback().
Referenced by v8::internal::interpreter::SwitchBuilder::EmitJumpTableIfExists().
TailCall()
BytecodeArrayBuilder& v8::internal::interpreter::BytecodeArrayBuilder::TailCall (Register callable, RegisterList args, int feedback_slot)
Throw()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::Throw ()
Definition at line 1402 of file bytecode-array-builder.cc.
                                                  {
  OutputThrow();
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildInvalidPropertyAccess(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), and v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn().
ThrowIfNotSuperConstructor()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ThrowIfNotSuperConstructor (Register constructor)
Definition at line 1441 of file bytecode-array-builder.cc.
                          {
  OutputThrowIfNotSuperConstructor(constructor);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildGetAndCheckSuperConstructor().
ThrowReferenceErrorIfHole()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ThrowReferenceErrorIfHole (const AstRawString * name)
Definition at line 1424 of file bytecode-array-builder.cc.
                              {
  size_t entry = GetConstantPoolEntry(name);
  OutputThrowReferenceErrorIfHole(entry);
  return *this;
}
References GetConstantPoolEntry(), and v8::internal::name.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildThrowIfHole().
ThrowSuperAlreadyCalledIfNotHole()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ThrowSuperAlreadyCalledIfNotHole ()
Definition at line 1436 of file bytecode-array-builder.cc.
                                                                             {
  OutputThrowSuperAlreadyCalledIfNotHole();
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildHoleCheckForVariableAssignment().
ThrowSuperNotCalledIfHole()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ThrowSuperNotCalledIfHole ()
Definition at line 1431 of file bytecode-array-builder.cc.
                                                                      {
  OutputThrowSuperNotCalledIfHole();
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildThrowIfHole().
ToBoolean()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ToBoolean (ToBooleanMode mode)
Definition at line 1166 of file bytecode-array-builder.cc.
                                                                        {
  if (mode == ToBooleanMode::kAlreadyBoolean) {
    // No-op, the accumulator is already a boolean and ToBoolean both reads and
    // writes the accumulator.
  } else {
    DCHECK_EQ(mode, ToBooleanMode::kConvertToBoolean);
    OutputToBoolean();
  }
  return *this;
}
References DCHECK_EQ, kAlreadyBoolean, kConvertToBoolean, and mode().
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitNot().
ToBytecodeArray()
template<typename IsolateT >
Handle< BytecodeArray > v8::internal::interpreter::BytecodeArrayBuilder::ToBytecodeArray (IsolateT * isolate)
Definition at line 91 of file bytecode-array-builder.cc.
                                                                             {
  DCHECK(RemainderOfBlockIsDead());
  DCHECK(!bytecode_generated_);
  bytecode_generated_ = true;
  int register_count = total_register_count();
  if (register_optimizer_) {
    register_optimizer_->Flush();
    register_count = register_optimizer_->maxiumum_register_index() + 1;
  }
  DirectHandle<TrustedByteArray> handler_table =
      handler_table_builder()->ToHandlerTable(isolate);
  return bytecode_array_writer_.ToBytecodeArray(isolate, register_count,
                                                parameter_count(),
                                                max_arguments(), handler_table);
}
References bytecode_array_writer_, bytecode_generated_, v8::internal::DCHECK(), v8::internal::interpreter::BytecodeRegisterOptimizer::Flush(), handler_table_builder(), max_arguments(), v8::internal::interpreter::BytecodeRegisterOptimizer::maxiumum_register_index(), parameter_count(), register_optimizer_, RemainderOfBlockIsDead(), v8::internal::interpreter::BytecodeArrayWriter::ToBytecodeArray(), v8::internal::interpreter::HandlerTableBuilder::ToHandlerTable(), and total_register_count().
Referenced by v8::internal::interpreter::BytecodeGenerator::FinalizeBytecode().
ToName()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ToName ()
Definition at line 1156 of file bytecode-array-builder.cc.
                                                   {
  OutputToName();
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), and v8::internal::interpreter::BytecodeGenerator::BuildLoadPropertyKey().
ToNumber()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ToNumber (int feedback_slot)
Definition at line 1177 of file bytecode-array-builder.cc.
                                                                      {
  OutputToNumber(feedback_slot);
  return *this;
}
ToNumeric()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ToNumeric (int feedback_slot)
Definition at line 1182 of file bytecode-array-builder.cc.
                                                                       {
  OutputToNumeric(feedback_slot);
  return *this;
}
ToObject()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ToObject (Register out)
Definition at line 1151 of file bytecode-array-builder.cc.
                                                                 {
  OutputToObject(out);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildNewLocalWithContext().
ToSourcePositionTable()
template<typename IsolateT >
DirectHandle<TrustedByteArray> v8::internal::interpreter::BytecodeArrayBuilder::ToSourcePositionTable (IsolateT * isolate)
Referenced by v8::internal::interpreter::BytecodeGenerator::FinalizeSourcePositionTable().
ToString()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::ToString ()
Definition at line 1161 of file bytecode-array-builder.cc.
                                                     {
  OutputToString();
  return *this;
}
total_register_count()
int v8::internal::interpreter::BytecodeArrayBuilder::total_register_count () const [inline]
Definition at line 78 of file bytecode-array-builder.h.
                                   {
    DCHECK_LE(fixed_register_count(),
              register_allocator()->maximum_register_count());
    return register_allocator()->maximum_register_count();
  }
References DCHECK_LE.
Referenced by ToBytecodeArray().
TypeOf()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::TypeOf (int feedback_slot)
Definition at line 549 of file bytecode-array-builder.cc.
                                                                    {
  OutputTypeOf(feedback_slot);
  return *this;
}
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitTypeOf().
UnaryOperation()
BytecodeArrayBuilder & v8::internal::interpreter::BytecodeArrayBuilder::UnaryOperation (Token::Value op, int feedback_slot)
Definition at line 515 of file bytecode-array-builder.cc.
                                                                              {
  switch (op) {
    case Token::kInc:
      OutputInc(feedback_slot);
      break;
    case Token::kDec:
      OutputDec(feedback_slot);
      break;
    case Token::kAdd:
      OutputToNumber(feedback_slot);
      break;
    case Token::kSub:
      OutputNegate(feedback_slot);
      break;
    case Token::kBitNot:
      OutputBitwiseNot(feedback_slot);
      break;
    default:
      UNREACHABLE();
  }
  return *this;
}
References v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), and v8::internal::interpreter::BytecodeGenerator::BuildFillArrayWithIterator().
UpdateMaxArguments()
void v8::internal::interpreter::BytecodeArrayBuilder::UpdateMaxArguments (uint16_t max_arguments) [inline]
Definition at line 64 of file bytecode-array-builder.h.
                                                  {
    max_arguments_ = std::max(max_arguments_, max_arguments);
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitArguments().
Write()
void v8::internal::interpreter::BytecodeArrayBuilder::Write (BytecodeNode * node) [private]
Definition at line 176 of file bytecode-array-builder.cc.
                                                   {
  AttachOrEmitDeferredSourceInfo(node);
  bytecode_array_writer_.Write(node);
}
References AttachOrEmitDeferredSourceInfo(), bytecode_array_writer_, and v8::internal::interpreter::BytecodeArrayWriter::Write().
Referenced by OutputLdarRaw(), OutputMovRaw(), and OutputStarRaw().
WriteJump()
void v8::internal::interpreter::BytecodeArrayBuilder::WriteJump (BytecodeNode * node, BytecodeLabel * label) [private]
Definition at line 181 of file bytecode-array-builder.cc.
                                                                             {
  AttachOrEmitDeferredSourceInfo(node);
  bytecode_array_writer_.WriteJump(node, label);
}
References AttachOrEmitDeferredSourceInfo(), bytecode_array_writer_, and v8::internal::interpreter::BytecodeArrayWriter::WriteJump().
WriteJumpLoop()
void v8::internal::interpreter::BytecodeArrayBuilder::WriteJumpLoop (BytecodeNode * node, BytecodeLoopHeader * loop_header) [private]
Definition at line 186 of file bytecode-array-builder.cc.
                                                                          {
  AttachOrEmitDeferredSourceInfo(node);
  bytecode_array_writer_.WriteJumpLoop(node, loop_header);
}
References AttachOrEmitDeferredSourceInfo(), bytecode_array_writer_, and v8::internal::interpreter::BytecodeArrayWriter::WriteJumpLoop().
Referenced by OutputJumpLoop().
WriteSwitch()
void v8::internal::interpreter::BytecodeArrayBuilder::WriteSwitch (BytecodeNode * node, BytecodeJumpTable * label) [private]
Definition at line 192 of file bytecode-array-builder.cc.
                                                                      {
  AttachOrEmitDeferredSourceInfo(node);
  bytecode_array_writer_.WriteSwitch(node, jump_table);
}
References AttachOrEmitDeferredSourceInfo(), bytecode_array_writer_, and v8::internal::interpreter::BytecodeArrayWriter::WriteSwitch().
Referenced by OutputSwitchOnSmiNoFeedback(), and SwitchOnGeneratorState().
zone()
Zone* v8::internal::interpreter::BytecodeArrayBuilder::zone () const [inline]
Definition at line 603 of file bytecode-array-builder.h.
{ return zone_; }
Referenced by AllocateJumpTable(), BytecodeArrayBuilder(), and v8::internal::interpreter::ConditionalChainControlFlowBuilder::ConditionalChainControlFlowBuilder().
Friends And Related Function Documentation
BytecodeNodeBuilder
template<Bytecode bytecode, ImplicitRegisterUse implicit_register_use, OperandType... operand_types>
friend class BytecodeNodeBuilder [friend]
Definition at line 609 of file bytecode-array-builder.h.
BytecodeRegisterAllocator
friend class BytecodeRegisterAllocator [friend]
Definition at line 606 of file bytecode-array-builder.h.
Member Data Documentation
bytecode_array_writer_
BytecodeArrayWriter v8::internal::interpreter::BytecodeArrayBuilder::bytecode_array_writer_ [private]
Definition at line 678 of file bytecode-array-builder.h.
Referenced by Bind(), EmitFunctionStartSourcePosition(), MarkHandler(), MarkTryBegin(), MarkTryEnd(), ToBytecodeArray(), Write(), WriteJump(), WriteJumpLoop(), and WriteSwitch().
bytecode_generated_
bool v8::internal::interpreter::BytecodeArrayBuilder::bytecode_generated_ [private]
Definition at line 671 of file bytecode-array-builder.h.
Referenced by ToBytecodeArray().
constant_array_builder_
ConstantArrayBuilder v8::internal::interpreter::BytecodeArrayBuilder::constant_array_builder_ [private]
Definition at line 672 of file bytecode-array-builder.h.
deferred_source_info_
BytecodeSourceInfo v8::internal::interpreter::BytecodeArrayBuilder::deferred_source_info_ [private]
Definition at line 681 of file bytecode-array-builder.h.
Referenced by AttachOrEmitDeferredSourceInfo(), and SetDeferredSourceInfo().
feedback_vector_spec_
FeedbackVectorSpec* v8::internal::interpreter::BytecodeArrayBuilder::feedback_vector_spec_ [private]
Definition at line 670 of file bytecode-array-builder.h.
handler_table_builder_
HandlerTableBuilder v8::internal::interpreter::BytecodeArrayBuilder::handler_table_builder_ [private]
Definition at line 673 of file bytecode-array-builder.h.
latest_source_info_
BytecodeSourceInfo v8::internal::interpreter::BytecodeArrayBuilder::latest_source_info_ [private]
Definition at line 680 of file bytecode-array-builder.h.
Referenced by EmitFunctionStartSourcePosition(), and JumpLoop().
local_register_count_
int v8::internal::interpreter::BytecodeArrayBuilder::local_register_count_ [private]
Definition at line 676 of file bytecode-array-builder.h.
Referenced by BytecodeArrayBuilder().
max_arguments_
uint16_t v8::internal::interpreter::BytecodeArrayBuilder::max_arguments_ [private]
Definition at line 675 of file bytecode-array-builder.h.
parameter_count_
uint16_t v8::internal::interpreter::BytecodeArrayBuilder::parameter_count_ [private]
Definition at line 674 of file bytecode-array-builder.h.
Referenced by BytecodeArrayBuilder().
register_allocator_
BytecodeRegisterAllocator v8::internal::interpreter::BytecodeArrayBuilder::register_allocator_ [private]
Definition at line 677 of file bytecode-array-builder.h.
Referenced by BytecodeArrayBuilder().
register_optimizer_
BytecodeRegisterOptimizer* v8::internal::interpreter::BytecodeArrayBuilder::register_optimizer_ [private]
Definition at line 679 of file bytecode-array-builder.h.
Referenced by Bind(), BytecodeArrayBuilder(), GetInputOutputRegisterOperand(), GetInputRegisterListOperand(), GetInputRegisterOperand(), GetOutputRegisterListOperand(), GetOutputRegisterOperand(), LoadAccumulatorWithRegister(), MarkHandler(), MarkTryBegin(), MarkTryEnd(), MoveRegister(), PrepareToOutputBytecode(), StoreAccumulatorInRegister(), and ToBytecodeArray().
zone_
Zone* v8::internal::interpreter::BytecodeArrayBuilder::zone_ [private]
Definition at line 669 of file bytecode-array-builder.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/bytecode-array-builder.h
/mnt/V8SourceCode/src/interpreter/bytecode-array-builder.cc