v8::internal::maglev::ToBoolean Class Reference
#include <maglev-ir.h>
Public Member Functions
ToBoolean (uint64_t bitfield, CheckType check_type)
Input & value ()
CheckType check_type () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = FixedInputValueNodeT< 1, ToBoolean >
using CheckTypeBitField = NextBitField< CheckType, 1 >
Additional Inherited Members
Detailed Description
Definition at line 4916 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::ToBoolean::Base = FixedInputValueNodeT<1, ToBoolean> [private]
Definition at line 4917 of file maglev-ir.h.
CheckTypeBitField
using v8::internal::maglev::ToBoolean::CheckTypeBitField = NextBitField<CheckType, 1> [private]
Definition at line 4936 of file maglev-ir.h.
Constructor & Destructor Documentation
ToBoolean()
v8::internal::maglev::ToBoolean::ToBoolean (uint64_t bitfield, CheckType check_type) [inline], [explicit]
Definition at line 4920 of file maglev-ir.h.
      : Base(CheckTypeBitField::update(bitfield, check_type)) {}
Member Function Documentation
check_type()
CheckType v8::internal::maglev::ToBoolean::check_type () const [inline]
Definition at line 4927 of file maglev-ir.h.
{ return CheckTypeBitField::decode(bitfield()); }
Referenced by options().
GenerateCode()
void v8::internal::maglev::ToBoolean::GenerateCode (MaglevAssembler * , const ProcessingState &)
options()
auto v8::internal::maglev::ToBoolean::options () const [inline]
Definition at line 4933 of file maglev-ir.h.
{ return std::tuple{check_type()}; }
References check_type().
PrintParams()
void v8::internal::maglev::ToBoolean::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 4931 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::ToBoolean::SetValueLocationConstraints ()
value()
Input& v8::internal::maglev::ToBoolean::value () [inline]
Definition at line 4926 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::ToBoolean::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 4924 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h