v8::internal::anonymous_namespace{regexp-interpreter.cc}::BacktrackStack Class Reference
Public Member Functions
BacktrackStack ()=default
BacktrackStack (const BacktrackStack &)=delete
BacktrackStack & operator= (const BacktrackStack &)=delete
V8_WARN_UNUSED_RESULT bool push (int v)
int peek () const
int pop ()
int sp () const
void set_sp (uint32_t new_sp)
Private Types
using ValueT = int
Private Attributes
base::SmallVector< ValueT, kStaticCapacity > data_
Static Private Attributes
static constexpr int kStaticCapacity = 64
static constexpr int kMaxSize
Detailed Description
Definition at line 128 of file regexp-interpreter.cc.
Member Typedef Documentation
ValueT
using v8::internal::anonymous_namespace{regexp-interpreter.cc}::BacktrackStack::ValueT = int [private]
Definition at line 160 of file regexp-interpreter.cc.
Constructor & Destructor Documentation
BacktrackStack() [1/2]
v8::internal::anonymous_namespace{regexp-interpreter.cc}::BacktrackStack::BacktrackStack () [default]
BacktrackStack() [2/2]
v8::internal::anonymous_namespace{regexp-interpreter.cc}::BacktrackStack::BacktrackStack (const BacktrackStack &) [delete]
Member Function Documentation
operator=()
BacktrackStack& v8::internal::anonymous_namespace{regexp-interpreter.cc}::BacktrackStack::operator= (const BacktrackStack &) [delete]
peek()
int v8::internal::anonymous_namespace{regexp-interpreter.cc}::BacktrackStack::peek () const [inline]
Definition at line 138 of file regexp-interpreter.cc.
                   {
    SBXCHECK(!data_.empty());
    return data_.back();
  }
References SBXCHECK.
Referenced by v8::internal::anonymous_namespace{regexp-interpreter.cc}::RawMatch().
pop()
int v8::internal::anonymous_namespace{regexp-interpreter.cc}::BacktrackStack::pop () [inline]
Definition at line 142 of file regexp-interpreter.cc.
            {
    int v = peek();
    data_.pop_back();
    return v;
  }
Referenced by v8::internal::anonymous_namespace{regexp-interpreter.cc}::RawMatch().
push()
V8_WARN_UNUSED_RESULT bool v8::internal::anonymous_namespace{regexp-interpreter.cc}::BacktrackStack::push (int v) [inline]
Definition at line 134 of file regexp-interpreter.cc.
                                         {
    data_.emplace_back(v);
    return (static_cast<int>(data_.size()) <= kMaxSize);
  }
Referenced by v8::internal::anonymous_namespace{regexp-interpreter.cc}::RawMatch().
set_sp()
void v8::internal::anonymous_namespace{regexp-interpreter.cc}::BacktrackStack::set_sp (uint32_t new_sp) [inline]
Definition at line 150 of file regexp-interpreter.cc.
                               {
    DCHECK_LE(new_sp, sp());
    data_.resize(new_sp);
  }
References DCHECK_LE.
Referenced by v8::internal::anonymous_namespace{regexp-interpreter.cc}::RawMatch().
sp()
int v8::internal::anonymous_namespace{regexp-interpreter.cc}::BacktrackStack::sp () const [inline]
Definition at line 149 of file regexp-interpreter.cc.
{ return static_cast<int>(data_.size()); }
Referenced by v8::internal::anonymous_namespace{regexp-interpreter.cc}::RawMatch().
Member Data Documentation
data_
base::SmallVector<ValueT, kStaticCapacity> v8::internal::anonymous_namespace{regexp-interpreter.cc}::BacktrackStack::data_ [private]
Definition at line 161 of file regexp-interpreter.cc.
kMaxSize
constexpr int v8::internal::anonymous_namespace{regexp-interpreter.cc}::BacktrackStack::kMaxSize [static], [constexpr], [private]
Initial value:
=
      RegExpStack::kMaximumStackSize / sizeof(ValueT)
Definition at line 163 of file regexp-interpreter.cc.
kStaticCapacity
constexpr int v8::internal::anonymous_namespace{regexp-interpreter.cc}::BacktrackStack::kStaticCapacity = 64 [static], [constexpr], [private]
Definition at line 158 of file regexp-interpreter.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-interpreter.cc