v8::internal::Representation Class Reference
#include <property-details.h>
Public Types
enum Kind {
kNone
, kSmi
, kDouble
, kHeapObject
,
kTagged
, kWasmValue
, kNumRepresentations
 }
Public Member Functions
constexpr Representation ()
bool Equals (const Representation &other) const
bool IsCompatibleForLoad (const Representation &other) const
bool IsCompatibleForStore (const Representation &other) const
bool MightCauseMapDeprecation () const
bool CanBeInPlaceChangedTo (const Representation &other) const
Representation MostGenericInPlaceChange () const
bool is_more_general_than (const Representation &other) const
bool fits_into (const Representation &other) const
Representation generalize (Representation other)
int size () const
constexpr Kind kind () const
constexpr bool IsNone () const
constexpr bool IsWasmValue () const
constexpr bool IsTagged () const
constexpr bool IsSmi () const
constexpr bool IsSmiOrTagged () const
constexpr bool IsDouble () const
constexpr bool IsHeapObject () const
const char * Mnemonic () const
bool operator== (const Representation &other) const
Static Public Member Functions
static constexpr Representation None ()
static constexpr Representation Tagged ()
static constexpr Representation Smi ()
static constexpr Representation Double ()
static constexpr Representation HeapObject ()
static constexpr Representation WasmValue ()
static constexpr Representation FromKind (Kind kind)
Private Member Functions
constexpr Representation (Kind k)
Private Attributes
int8_t kind_
Detailed Description
Definition at line 95 of file property-details.h.
Member Enumeration Documentation
Kind
enum v8::internal::Representation::Kind
Enumerator
kNone
kSmi
kDouble
kHeapObject
kTagged
kWasmValue
kNumRepresentations
Definition at line 97 of file property-details.h.
            {
    kNone,
    kSmi,
    kDouble,
    kHeapObject,
    kTagged,
    // This representation is used for WasmObject fields and basically means
    // that the actual field type information must be taken from the Wasm RTT
    // associated with the map.
    kWasmValue,
    kNumRepresentations
  };
Constructor & Destructor Documentation
Representation() [1/2]
constexpr v8::internal::Representation::Representation () [inline], [constexpr]
Definition at line 110 of file property-details.h.
: kind_(kNone) {}
Referenced by Double(), FromKind(), HeapObject(), None(), Smi(), Tagged(), and WasmValue().
Representation() [2/2]
constexpr v8::internal::Representation::Representation (Kind k) [inline], [explicit], [constexpr], [private]
Definition at line 234 of file property-details.h.
: kind_(k) {}
Member Function Documentation
CanBeInPlaceChangedTo()
bool v8::internal::Representation::CanBeInPlaceChangedTo (const Representation & other) const [inline]
Definition at line 157 of file property-details.h.
                                                                {
    if (Equals(other)) return true;
    if (IsWasmValue() || other.IsWasmValue()) return false;
    // If it's just a representation generalization case (i.e. property kind and
    // attributes stays unchanged) it's fine to transition from None to anything
    // but double without any modification to the object, because the default
    // uninitialized value for representation None can be overwritten by both
    // smi and tagged values. Doubles, however, would require a box allocation.
    if (IsNone()) return !other.IsDouble();
    if (!other.IsTagged()) return false;
    DCHECK(IsSmi() || IsDouble() || IsHeapObject());
    return true;
  }
References v8::internal::DCHECK(), Equals(), IsDouble(), IsHeapObject(), IsNone(), IsSmi(), IsTagged(), and IsWasmValue().
Referenced by v8::internal::MapUpdater::FindTargetMap(), v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue(), v8::internal::MapUpdater::TryReconfigureToDataFieldInplace(), and v8::internal::MapUpdater::UpdateFieldType().
Double()
static constexpr Representation v8::internal::Representation::Double () [inline], [static], [constexpr]
Definition at line 115 of file property-details.h.
{ return Representation(kDouble); }
References kDouble, and Representation().
Referenced by v8::internal::compiler::JSObjectRef::GetOwnFastConstantDoubleProperty(), v8::internal::AccessorAssembler::HandleStoreICSmiHandlerCase(), v8::internal::DictionaryTemplateInfo::NewInstance(), and v8::internal::Object::OptimalRepresentation().
Equals()
bool v8::internal::Representation::Equals (const Representation & other) const [inline]
Definition at line 127 of file property-details.h.
                                                 {
    return kind_ == other.kind_;
  }
References kind_.
Referenced by CanBeInPlaceChangedTo(), v8::internal::anonymous_namespace{ic.cc}::CanFastCloneObjectToObjectLiteral(), v8::internal::MapUpdater::FindSplitMap(), fits_into(), v8::internal::MapUpdater::GeneralizeField(), IsCompatibleForStore(), v8::internal::DescriptorArray::IsEqualUpTo(), v8::internal::compiler::PropertyAccessInfo::Merge(), v8::internal::JSObject::PrintInstanceMigration(), v8::internal::StoreHandler::StoreSharedStructField(), and v8::internal::MapUpdater::UpdateFieldType().
fits_into()
bool v8::internal::Representation::fits_into (const Representation & other) const [inline]
Definition at line 185 of file property-details.h.
                                                    {
    return other.is_more_general_than(*this) || other.Equals(*this);
  }
References Equals(), and is_more_general_than().
Referenced by v8::internal::anonymous_namespace{ic.cc}::CanFastCloneObjectToObjectLiteral(), v8::internal::MapUpdater::FindRootMap(), v8::internal::MapUpdater::FindTargetMap(), generalize(), v8::internal::Map::TryReplayPropertyTransitions(), and v8::internal::MapUpdater::UpdateFieldType().
FromKind()
static constexpr Representation v8::internal::Representation::FromKind (Kind kind) [inline], [static], [constexpr]
Definition at line 123 of file property-details.h.
                                                      {
    return Representation(kind);
  }
References kind(), and Representation().
Referenced by v8::internal::PropertyDetails::DecodeRepresentation().
generalize()
Representation v8::internal::Representation::generalize (Representation other) [inline]
Definition at line 189 of file property-details.h.
                                                  {
    if (other.fits_into(*this)) return *this;
    if (other.is_more_general_than(*this)) return other;
    return Representation::Tagged();
  }
References fits_into(), is_more_general_than(), and Tagged().
Referenced by v8::internal::MapUpdater::BuildDescriptorArray(), v8::internal::MapUpdater::FindTargetMap(), v8::internal::MapUpdater::ReconfigureToDataField(), v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue(), and v8::internal::MapUpdater::UpdateFieldType().
HeapObject()
static constexpr Representation v8::internal::Representation::HeapObject () [inline], [static], [constexpr]
Definition at line 116 of file property-details.h.
                                               {
    return Representation(kHeapObject);
  }
References kHeapObject, and Representation().
Referenced by v8::internal::AccessorAssembler::HandleStoreICSmiHandlerCase(), and v8::internal::Object::OptimalRepresentation().
is_more_general_than()
bool v8::internal::Representation::is_more_general_than (const Representation & other) const [inline]
Definition at line 179 of file property-details.h.
                                                               {
    if (IsWasmValue()) return false;
    if (IsHeapObject()) return other.IsNone();
    return kind_ > other.kind_;
  }
References IsHeapObject(), IsNone(), IsWasmValue(), and kind_.
Referenced by fits_into(), and generalize().
IsCompatibleForLoad()
bool v8::internal::Representation::IsCompatibleForLoad (const Representation & other) const [inline]
Definition at line 131 of file property-details.h.
                                                              {
    return IsDouble() == other.IsDouble();
  }
References IsDouble().
Referenced by v8::internal::MapUpdater::BuildDescriptorArray().
IsCompatibleForStore()
bool v8::internal::Representation::IsCompatibleForStore (const Representation & other) const [inline]
Definition at line 135 of file property-details.h.
                                                               {
    return Equals(other);
  }
References Equals().
IsDouble()
constexpr bool v8::internal::Representation::IsDouble () const [inline], [constexpr]
Definition at line 208 of file property-details.h.
{ return kind_ == kDouble; }
References kDouble, and kind_.
Referenced by v8::internal::JSObject::AllocateStorageForMap(), v8::internal::Map::AppendDescriptor(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadField(), CanBeInPlaceChangedTo(), v8::internal::anonymous_namespace{ic.cc}::CanFastCloneObjectToObjectLiteral(), v8::internal::LookupIterator::CanStayConst(), v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::JSDataObjectBuilder::CreateAndInitialiseObject(), v8::internal::compiler::PropertyAccessInfo::DataField(), v8::internal::TranslatedState::EnsureJSObjectAllocated(), v8::internal::TranslatedState::EnsurePropertiesAllocatedAndMarked(), v8::internal::V8HeapExplorer::ExtractPropertyReferences(), v8::internal::Object::FitsRepresentation(), v8::internal::compiler::JSObjectRef::GetOwnFastConstantDataProperty(), v8::internal::AccessorAssembler::HandleStoreFieldAndReturn(), IsCompatibleForLoad(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), v8::internal::compiler::PropertyAccessInfo::Merge(), MightCauseMapDeprecation(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), v8::internal::Object::NewStorageFor(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), size(), v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk(), v8::internal::JSDataObjectBuilder::TryAddFastPropertyForValue(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField(), v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadConstantDataField(), v8::internal::compiler::PropertyAccessBuilder::TryFoldLoadConstantDataField(), v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadConstantDoubleField(), v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue(), v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral(), v8::internal::Object::WrapForRead(), and v8::internal::JSObject::WriteToField().
IsHeapObject()
constexpr bool v8::internal::Representation::IsHeapObject () const [inline], [constexpr]
Definition at line 209 of file property-details.h.
{ return kind_ == kHeapObject; }
References kHeapObject, and kind_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadField(), CanBeInPlaceChangedTo(), v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), v8::internal::TranslatedState::EnsureJSObjectAllocated(), v8::internal::TranslatedState::EnsurePropertiesAllocatedAndMarked(), v8::internal::Object::FitsRepresentation(), v8::internal::MapUpdater::GeneralizeField(), is_more_general_than(), v8::internal::Map::IsMostGeneralFieldType(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), MightCauseMapDeprecation(), v8::internal::Object::OptimalType(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), size(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField(), v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue(), and v8::internal::MapUpdater::UpdateFieldType().
IsNone()
constexpr bool v8::internal::Representation::IsNone () const [inline], [constexpr]
Definition at line 203 of file property-details.h.
{ return kind_ == kNone; }
References kind_, and kNone.
Referenced by CanBeInPlaceChangedTo(), v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::compiler::PropertyAccessInfo::DataField(), v8::internal::compiler::PropertyAccessInfo::FastDataConstant(), v8::internal::Object::FitsRepresentation(), is_more_general_than(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), MightCauseMapDeprecation(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast(), v8::internal::Object::OptimalType(), size(), v8::internal::StoreHandler::StoreField(), v8::internal::StoreHandler::StoreOwnTransition(), v8::internal::StoreHandler::StoreTransition(), and v8::internal::MapUpdater::TryReconfigureToDataFieldInplace().
IsSmi()
constexpr bool v8::internal::Representation::IsSmi () const [inline], [constexpr]
Definition at line 206 of file property-details.h.
{ return kind_ == kSmi; }
References kind_, and kSmi.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadField(), CanBeInPlaceChangedTo(), v8::internal::anonymous_namespace{ic.cc}::CanFastCloneObjectToObjectLiteral(), v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::V8HeapExplorer::ExtractPropertyReferences(), v8::internal::Object::FitsRepresentation(), v8::internal::FieldStatsCollector::GetInobjectFieldStats(), v8::internal::AccessorAssembler::HandleStoreFieldAndReturn(), IsSmiOrTagged(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), MightCauseMapDeprecation(), size(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
IsSmiOrTagged()
constexpr bool v8::internal::Representation::IsSmiOrTagged () const [inline], [constexpr]
Definition at line 207 of file property-details.h.
{ return IsSmi() || IsTagged(); }
References IsSmi(), and IsTagged().
IsTagged()
constexpr bool v8::internal::Representation::IsTagged () const [inline], [constexpr]
Definition at line 205 of file property-details.h.
{ return kind_ == kTagged; }
References kind_, and kTagged.
Referenced by CanBeInPlaceChangedTo(), v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), IsSmiOrTagged(), MightCauseMapDeprecation(), size(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField().
IsWasmValue()
constexpr bool v8::internal::Representation::IsWasmValue () const [inline], [constexpr]
Definition at line 204 of file property-details.h.
{ return kind_ == kWasmValue; }
References kind_, and kWasmValue.
Referenced by CanBeInPlaceChangedTo(), is_more_general_than(), MightCauseMapDeprecation(), and MostGenericInPlaceChange().
kind()
constexpr Kind v8::internal::Representation::kind () const [inline], [constexpr]
Definition at line 202 of file property-details.h.
{ return static_cast<Kind>(kind_); }
References kind_.
Referenced by v8::internal::compiler::PropertyAccessBuilder::ConvertRepresentation(), v8::internal::PropertyDetails::EncodeRepresentation(), v8::internal::FieldIndex::FieldEncoding(), FromKind(), v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value(), v8::internal::operator<<(), and v8::internal::StoreHandler::StoreField().
MightCauseMapDeprecation()
bool v8::internal::Representation::MightCauseMapDeprecation () const [inline]
Definition at line 141 of file property-details.h.
                                        {
    // HeapObject to tagged representation change can be done in-place.
    // Boxed double to tagged transition is always done in-place.
    // Note that WasmValue is not supposed to be changed at all (the only
    // representation it fits into is WasmValue), so for the sake of predicate
    // correctness we treat it as in-place "changeable".
    if (IsTagged() || IsHeapObject() || IsDouble() || IsWasmValue()) {
      return false;
    }
    // None to double and smi to double representation changes require
    // deprecation, because doubles might require box allocation, see
    // CanBeInPlaceChangedTo().
    DCHECK(IsNone() || IsSmi());
    return true;
  }
References v8::internal::DCHECK(), IsDouble(), IsHeapObject(), IsNone(), IsSmi(), IsTagged(), and IsWasmValue().
Referenced by v8::internal::Map::CanBeDeprecated().
Mnemonic()
const char* v8::internal::Representation::Mnemonic () const [inline]
Definition at line 211 of file property-details.h.
                               {
    switch (kind_) {
      case kNone:
        return "v";
      case kTagged:
        return "t";
      case kSmi:
        return "s";
      case kDouble:
        return "d";
      case kHeapObject:
        return "h";
      case kWasmValue:
        return "w";
    }
    UNREACHABLE();
  }
References kDouble, kHeapObject, kind_, kNone, kSmi, kTagged, kWasmValue, and v8::internal::UNREACHABLE().
Referenced by v8::internal::FieldIndex::FieldEncoding(), v8::internal::PropertyDetails::PrintAsFastTo(), v8::internal::anonymous_namespace{map-updater.cc}::PrintGeneralization(), and v8::internal::JSObject::PrintInstanceMigration().
MostGenericInPlaceChange()
Representation v8::internal::Representation::MostGenericInPlaceChange () const [inline]
Definition at line 174 of file property-details.h.
                                                  {
    if (IsWasmValue()) return Representation::WasmValue();
    return Representation::Tagged();
  }
References IsWasmValue(), Tagged(), and WasmValue().
Referenced by v8::internal::anonymous_namespace{ic.cc}::CanFastCloneObjectToObjectLiteral().
None()
static constexpr Representation v8::internal::Representation::None () [inline], [static], [constexpr]
Definition at line 112 of file property-details.h.
{ return Representation(kNone); }
References kNone, and Representation().
Referenced by v8::internal::Object::OptimalRepresentation(), and v8::internal::MapUpdater::ReconfigureExistingProperty().
operator==()
bool v8::internal::Representation::operator== (const Representation & other) const [inline]
Definition at line 229 of file property-details.h.
                                                     {
    return kind_ == other.kind_;
  }
References kind_.
size()
int v8::internal::Representation::size () const [inline]
Definition at line 195 of file property-details.h.
                   {
    DCHECK(!IsNone());
    if (IsDouble()) return kDoubleSize;
    DCHECK(IsTagged() || IsSmi() || IsHeapObject());
    return kTaggedSize;
  }
References v8::internal::DCHECK(), IsDouble(), IsHeapObject(), IsNone(), IsSmi(), IsTagged(), v8::internal::kDoubleSize, and v8::internal::kTaggedSize.
Smi()
static constexpr Representation v8::internal::Representation::Smi () [inline], [static], [constexpr]
Definition at line 114 of file property-details.h.
{ return Representation(kSmi); }
References kSmi, and Representation().
Referenced by v8::internal::Heap::CreateLateReadOnlyJSReceiverMaps(), v8::internal::AccessorAssembler::HandleStoreICSmiHandlerCase(), v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessor(), and v8::internal::Object::OptimalRepresentation().
Tagged()
static constexpr Representation v8::internal::Representation::Tagged () [inline], [static], [constexpr]
Definition at line 113 of file property-details.h.
{ return Representation(kTagged); }
References kTagged, and Representation().
Referenced by v8::internal::Descriptor::AccessorConstant(), v8::internal::Map::CopyWithField(), v8::internal::JSSharedStruct::CreateInstanceMap(), v8::internal::Genesis::CreateJSProxyMaps(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateLiteralObjectMapFromCache(), v8::internal::Factory::CreateSloppyFunctionMap(), v8::internal::Factory::CreateStrictFunctionMap(), v8::internal::Descriptor::DataConstant(), generalize(), v8::internal::DescriptorArray::GeneralizeAllFields(), v8::internal::Map::GeneralizeIfCanHaveTransitionableFastElementsKind(), v8::internal::AccessorAssembler::HandleStoreICSmiHandlerCase(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::InstallError(), v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessor(), v8::internal::compiler::PropertyAccessInfo::Merge(), v8::internal::JSObject::MigrateSlowToFast(), MostGenericInPlaceChange(), v8::internal::WasmValueObject::New(), v8::internal::DictionaryTemplateInfo::NewInstance(), and v8::internal::StoreHandler::StoreSharedStructField().
WasmValue()
static constexpr Representation v8::internal::Representation::WasmValue () [inline], [static], [constexpr]
Definition at line 119 of file property-details.h.
                                              {
    return Representation(kWasmValue);
  }
References kWasmValue, and Representation().
Referenced by MostGenericInPlaceChange().
Member Data Documentation
kind_
int8_t v8::internal::Representation::kind_ [private]
Definition at line 239 of file property-details.h.
Referenced by Equals(), is_more_general_than(), IsDouble(), IsHeapObject(), IsNone(), IsSmi(), IsTagged(), IsWasmValue(), kind(), Mnemonic(), and operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/property-details.h