v8::internal::SlotAccessorForHeapObject Class Reference
Public Member Functions
MaybeObjectSlot slot () const
ExternalPointerSlot external_pointer_slot (ExternalPointerTag tag) const
Handle< HeapObject > object () const
int offset () const
int Write (Tagged< MaybeObject > value, int slot_offset, WriteBarrierMode mode)
int Write (Tagged< HeapObject > value, HeapObjectReferenceType ref_type, int slot_offset, WriteBarrierMode mode)
int Write (DirectHandle< HeapObject > value, HeapObjectReferenceType ref_type, int slot_offset, WriteBarrierMode mode)
int WriteIndirectPointerTo (Tagged< HeapObject > value, WriteBarrierMode mode)
int WriteProtectedPointerTo (Tagged< TrustedObject > value, WriteBarrierMode mode)
Static Public Member Functions
static SlotAccessorForHeapObject ForSlotIndex (Handle< HeapObject > object, int index)
static SlotAccessorForHeapObject ForSlotOffset (Handle< HeapObject > object, int offset)
Private Member Functions
SlotAccessorForHeapObject (Handle< HeapObject > object, int offset)
Private Attributes
const Handle< HeapObject > object_
const int offset_
Detailed Description
Definition at line 54 of file deserializer.cc.
Constructor & Destructor Documentation
SlotAccessorForHeapObject()
v8::internal::SlotAccessorForHeapObject::SlotAccessorForHeapObject (Handle< HeapObject > object, int offset) [inline], [private]
Definition at line 126 of file deserializer.cc.
      : object_(object), offset_(offset) {}
Referenced by v8::internal::Deserializer< LocalIsolate >::DeserializeDeferredObjects(), and v8::internal::Deserializer< LocalIsolate >::LogNewMapEvents().
Member Function Documentation
external_pointer_slot()
ExternalPointerSlot v8::internal::SlotAccessorForHeapObject::external_pointer_slot (ExternalPointerTag tag) const [inline]
Definition at line 66 of file deserializer.cc.
                                                                          {
    return object_->RawExternalPointerField(offset_, tag);
  }
References object_, and offset_.
ForSlotIndex()
static SlotAccessorForHeapObject v8::internal::SlotAccessorForHeapObject::ForSlotIndex (Handle< HeapObject > object, int index) [inline], [static]
Definition at line 56 of file deserializer.cc.
                                                           {
    return SlotAccessorForHeapObject(object, index * kTaggedSize);
  }
ForSlotOffset()
static SlotAccessorForHeapObject v8::internal::SlotAccessorForHeapObject::ForSlotOffset (Handle< HeapObject > object, int offset) [inline], [static]
Definition at line 60 of file deserializer.cc.
                                                             {
    return SlotAccessorForHeapObject(object, offset);
  }
object()
Handle<HeapObject> v8::internal::SlotAccessorForHeapObject::object () const [inline]
Definition at line 69 of file deserializer.cc.
{ return object_; }
References object_.
offset()
int v8::internal::SlotAccessorForHeapObject::offset () const [inline]
Definition at line 70 of file deserializer.cc.
{ return offset_; }
Referenced by v8::internal::Deserializer< LocalIsolate >::LogNewMapEvents().
slot()
MaybeObjectSlot v8::internal::SlotAccessorForHeapObject::slot () const [inline]
Definition at line 65 of file deserializer.cc.
{ return object_->RawMaybeWeakField(offset_); }
References object_, and offset_.
Referenced by Write().
Write() [1/3]
int v8::internal::SlotAccessorForHeapObject::Write (DirectHandle< HeapObject > value, HeapObjectReferenceType ref_type, int slot_offset, WriteBarrierMode mode) [inline]
Definition at line 92 of file deserializer.cc.
                                                    {
    return Write(*value, ref_type, slot_offset, mode);
  }
References mode(), v8::internal::value, and Write().
Write() [2/3]
int v8::internal::SlotAccessorForHeapObject::Write (Tagged< HeapObject > value, HeapObjectReferenceType ref_type, int slot_offset, WriteBarrierMode mode) [inline]
Definition at line 87 of file deserializer.cc.
                                                    {
    return Write(Tagged<HeapObjectReference>(value, ref_type), slot_offset,
                 mode);
  }
References mode(), v8::internal::value, and Write().
Write() [3/3]
int v8::internal::SlotAccessorForHeapObject::Write (Tagged< MaybeObject > value, int slot_offset, WriteBarrierMode mode) [inline]
Definition at line 74 of file deserializer.cc.
                                                                               {
    MaybeObjectSlot current_slot = slot() + slot_offset;
    current_slot.Relaxed_Store(value);
#ifdef V8_STATIC_ROOTS_BOOL
    if (mode != SKIP_WRITE_BARRIER && FastInReadOnlySpaceOrSmallSmi(value)) {
      // TODO(jgruber): Remove this once WriteBarrier::ForValue() contains the
      // same check.
      mode = SKIP_WRITE_BARRIER;
    }
#endif // V8_STATIC_ROOTS_BOOL
    WriteBarrier::ForValue(*object_, current_slot, value, mode);
    return 1;
  }
References v8::internal::FastInReadOnlySpaceOrSmallSmi(), v8::internal::WriteBarrier::ForValue(), mode(), object_, v8::internal::FullMaybeObjectSlot::Relaxed_Store(), v8::internal::SKIP_WRITE_BARRIER, slot(), and v8::internal::value.
Referenced by Write().
WriteIndirectPointerTo()
int v8::internal::SlotAccessorForHeapObject::WriteIndirectPointerTo (Tagged< HeapObject > value, WriteBarrierMode mode) [inline]
Definition at line 97 of file deserializer.cc.
                                                                              {
    // Only ExposedTrustedObjects can be referenced via indirect pointers, so
    // we must have one of these objects here. See the comments in
    // trusted-object.h for more details.
    DCHECK(IsExposedTrustedObject(value));
    Tagged<ExposedTrustedObject> object = Cast<ExposedTrustedObject>(value);
    InstanceType instance_type = value->map()->instance_type();
    bool shared = HeapLayout::InAnySharedSpace(value);
    IndirectPointerTag tag =
        IndirectPointerTagFromInstanceType(instance_type, shared);
    IndirectPointerSlot dest = object_->RawIndirectPointerField(offset_, tag);
    dest.store(object);
    WriteBarrier::ForIndirectPointer(*object_, dest, value, mode);
    return 1;
  }
References v8::internal::DCHECK(), v8::internal::WriteBarrier::ForIndirectPointer(), v8::internal::HeapLayout::InAnySharedSpace(), v8::internal::IndirectPointerTagFromInstanceType(), mode(), object_, offset_, v8::internal::IndirectPointerSlot::store(), and v8::internal::value.
WriteProtectedPointerTo()
int v8::internal::SlotAccessorForHeapObject::WriteProtectedPointerTo (Tagged< TrustedObject > value, WriteBarrierMode mode) [inline]
Definition at line 115 of file deserializer.cc.
                                                     {
    DCHECK(IsTrustedObject(*object_));
    Tagged<TrustedObject> host = Cast<TrustedObject>(*object_);
    ProtectedPointerSlot dest = host->RawProtectedPointerField(offset_);
    dest.store(value);
    WriteBarrier::ForProtectedPointer(host, dest, value, mode);
    return 1;
  }
Member Data Documentation
object_
const Handle<HeapObject> v8::internal::SlotAccessorForHeapObject::object_ [private]
Definition at line 129 of file deserializer.cc.
Referenced by external_pointer_slot(), object(), slot(), Write(), and WriteIndirectPointerTo().
offset_
const int v8::internal::SlotAccessorForHeapObject::offset_ [private]
Definition at line 130 of file deserializer.cc.
Referenced by external_pointer_slot(), v8::internal::Deserializer< LocalIsolate >::GetBackReferencedObject(), slot(), and WriteIndirectPointerTo().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/deserializer.cc