v8::Exception Class Reference
Create new error objects by calling the corresponding error object constructor with the message.
#include <v8-exception.h>
Static Public Member Functions
static Local< Value > RangeError (Local< String > message, Local< Value > options={})
static Local< Value > ReferenceError (Local< String > message, Local< Value > options={})
static Local< Value > SyntaxError (Local< String > message, Local< Value > options={})
static Local< Value > TypeError (Local< String > message, Local< Value > options={})
static Local< Value > WasmCompileError (Local< String > message, Local< Value > options={})
static Local< Value > WasmLinkError (Local< String > message, Local< Value > options={})
static Local< Value > WasmRuntimeError (Local< String > message, Local< Value > options={})
static Local< Value > WasmSuspendError (Local< String > message, Local< Value > options={})
static Local< Value > Error (Local< String > message, Local< Value > options={})
static Local< Message > CreateMessage (Isolate *isolate, Local< Value > exception)
Creates an error message for the given exception.
static Local< StackTrace > GetStackTrace (Local< Value > exception)
Returns the original stack trace that was captured at the creation time of a given exception, or an empty handle if not available.
static Maybe< bool > CaptureStackTrace (Local< Context > context, Local< Object > object)
Captures the current stack trace and attaches it to the given object in the form of stack property.
Detailed Description
Create new error objects by calling the corresponding error object constructor with the message.
Definition at line 32 of file v8-exception.h.
Member Function Documentation
CaptureStackTrace()
Maybe< bool > v8::Exception::CaptureStackTrace (Local< Context > context, Local< Object > object) [static]
Captures the current stack trace and attaches it to the given object in the form of stack property.
Definition at line 11183 of file api.cc.
                                                               {
  auto i_isolate = i::Isolate::Current();
  EnterV8NoScriptScope<> api_scope{i_isolate, context,
                                   RCCId::kAPI_Exception_CaptureStackTrace};
  auto obj = Utils::OpenHandle(*object);
  if (!IsJSObject(*obj)) return Just(false);
  auto js_obj = i::Cast<i::JSObject>(obj);
  i::FrameSkipMode mode = i::FrameSkipMode::SKIP_FIRST;
  auto result = i::ErrorUtils::CaptureStackTrace(i_isolate, js_obj, mode, {});
  i::DirectHandle<i::Object> handle;
  if (!result.ToHandle(&handle)) return {};
  return Just(true);
}
References v8::internal::ErrorUtils::CaptureStackTrace(), v8::internal::Isolate::Current(), v8::internal::handle(), v8::Just(), mode(), v8::Utils::OpenHandle(), v8::base::internal::result, and v8::internal::SKIP_FIRST.
CreateMessage()
Local< Message > v8::Exception::CreateMessage (Isolate * isolate, Local< Value > exception) [static]
Creates an error message for the given exception.
Will try to reconstruct the original stack trace from the exception value, or capture the current stack trace if not available.
Definition at line 11163 of file api.cc.
                                                                {
  auto obj = Utils::OpenHandle(*exception);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  return Utils::MessageToLocal(
      scope.CloseAndEscape(i_isolate->CreateMessage(obj, nullptr)));
}
References v8::internal::Isolate::CreateMessage(), and v8::Utils::OpenHandle().
Referenced by v8::Shell::PromiseRejectCallback().
Error()
static Local<Value> v8::Exception::Error (Local< String > message, Local< Value > options = {}) [static]
Referenced by v8::Shell::ExecuteModule(), v8::Shell::PromiseRejectCallback(), v8::Serializer::ThrowDataCloneError(), and v8::Isolate::ThrowError().
GetStackTrace()
Local< StackTrace > v8::Exception::GetStackTrace (Local< Value > exception) [static]
Returns the original stack trace that was captured at the creation time of a given exception, or an empty handle if not available.
Definition at line 11173 of file api.cc.
                                                                 {
  auto obj = Utils::OpenDirectHandle(*exception);
  if (!IsJSObject(*obj)) return {};
  auto js_obj = i::Cast<i::JSObject>(obj);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  auto stack_trace = i_isolate->GetDetailedStackTrace(js_obj);
  return Utils::StackTraceToLocal(stack_trace);
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::GetDetailedStackTrace(), and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback().
RangeError()
static Local<Value> v8::Exception::RangeError (Local< String > message, Local< Value > options = {}) [static]
Referenced by v8::internal::anonymous_namespace{runtime-test-wasm.cc}::NewRangeException().
ReferenceError()
static Local<Value> v8::Exception::ReferenceError (Local< String > message, Local< Value > options = {}) [static]
SyntaxError()
static Local<Value> v8::Exception::SyntaxError (Local< String > message, Local< Value > options = {}) [static]
Referenced by v8::Shell::FetchModuleSource().
TypeError()
static Local<Value> v8::Exception::TypeError (Local< String > message, Local< Value > options = {}) [static]
Referenced by v8::Shell::HostImportModuleWithPhaseDynamically().
WasmCompileError()
static Local<Value> v8::Exception::WasmCompileError (Local< String > message, Local< Value > options = {}) [static]
WasmLinkError()
static Local<Value> v8::Exception::WasmLinkError (Local< String > message, Local< Value > options = {}) [static]
WasmRuntimeError()
static Local<Value> v8::Exception::WasmRuntimeError (Local< String > message, Local< Value > options = {}) [static]
WasmSuspendError()
static Local<Value> v8::Exception::WasmSuspendError (Local< String > message, Local< Value > options = {}) [static]
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-exception.h
/mnt/V8SourceCode/src/api/api.cc