v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher Class Reference
#include <loop-unrolling-reducer.h>
Public Types
enum class CmpOp {
kEqual
, kSignedLessThan
, kSignedLessThanOrEqual
, kUnsignedLessThan
,
kUnsignedLessThanOrEqual
, kSignedGreaterThan
, kSignedGreaterThanOrEqual
, kUnsignedGreaterThan
,
kUnsignedGreaterThanOrEqual
 }
enum class BinOp {
kAdd
, kMul
, kSub
, kBitwiseAnd
,
kBitwiseOr
, kBitwiseXor
, kOverflowCheckedAdd
, kOverflowCheckedMul
,
kOverflowCheckedSub
 }
Public Member Functions
StaticCanonicalForLoopMatcher (const OperationMatcher &matcher)
IterationCount GetIterCountIfStaticCanonicalForLoop (const Block *header, OpIndex cond_idx, bool loop_if_cond_is) const
Static Public Member Functions
static constexpr CmpOp ComparisonKindToCmpOp (ComparisonOp::Kind kind)
static constexpr CmpOp InvertComparisonOp (CmpOp op)
static constexpr BinOp BinopFromWordBinopKind (WordBinopOp::Kind kind)
static constexpr BinOp BinopFromOverflowCheckedBinopKind (OverflowCheckedBinopOp::Kind kind)
static constexpr bool BinopKindIsSupported (WordBinopOp::Kind binop_kind)
Private Member Functions
bool MatchPhiCompareCst (OpIndex cond_idx, StaticCanonicalForLoopMatcher::CmpOp *cmp_op, OpIndex *phi, uint64_t *cst) const
bool MatchCheckedOverflowBinop (OpIndex idx, V< Word > *left, V< Word > *right, BinOp *binop_op, WordRepresentation *binop_rep) const
bool MatchWordBinop (OpIndex idx, V< Word > *left, V< Word > *right, BinOp *binop_op, WordRepresentation *binop_rep) const
IterationCount CountIterations (uint64_t equal_cst, CmpOp cmp_op, uint64_t initial_input, uint64_t binop_cst, BinOp binop_op, WordRepresentation binop_rep, bool loop_if_cond_is) const
template<class Int >
IterationCount CountIterationsImpl (Int init, Int max, CmpOp cmp_op, Int binop_cst, StaticCanonicalForLoopMatcher::BinOp binop_op, WordRepresentation binop_rep, bool loop_if_cond_is) const
Private Attributes
const OperationMatcher & matcher_
Static Private Attributes
static constexpr size_t kMaxExactIter = 5
Detailed Description
Definition at line 84 of file loop-unrolling-reducer.h.
Member Enumeration Documentation
BinOp
enum v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::BinOp [strong]
Enumerator
kAdd
kMul
kSub
kBitwiseAnd
kBitwiseOr
kBitwiseXor
kOverflowCheckedAdd
kOverflowCheckedMul
kOverflowCheckedSub
Definition at line 119 of file loop-unrolling-reducer.h.
                   {
    kAdd,
    kMul,
    kSub,
    kBitwiseAnd,
    kBitwiseOr,
    kBitwiseXor,
    kOverflowCheckedAdd,
    kOverflowCheckedMul,
    kOverflowCheckedSub
  };
CmpOp
enum v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::CmpOp [strong]
Enumerator
kEqual
kSignedLessThan
kSignedLessThanOrEqual
kUnsignedLessThan
kUnsignedLessThanOrEqual
kSignedGreaterThan
kSignedGreaterThanOrEqual
kUnsignedGreaterThan
kUnsignedGreaterThanOrEqual
Definition at line 106 of file loop-unrolling-reducer.h.
                   {
    kEqual,
    kSignedLessThan,
    kSignedLessThanOrEqual,
    kUnsignedLessThan,
    kUnsignedLessThanOrEqual,
    kSignedGreaterThan,
    kSignedGreaterThanOrEqual,
    kUnsignedGreaterThan,
    kUnsignedGreaterThanOrEqual,
  };
Constructor & Destructor Documentation
StaticCanonicalForLoopMatcher()
v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::StaticCanonicalForLoopMatcher (const OperationMatcher & matcher) [inline], [explicit]
Definition at line 100 of file loop-unrolling-reducer.h.
      : matcher_(matcher) {}
Member Function Documentation
BinopFromOverflowCheckedBinopKind()
constexpr StaticCanonicalForLoopMatcher::BinOp v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::BinopFromOverflowCheckedBinopKind (OverflowCheckedBinopOp::Kind kind) [static], [constexpr]
Definition at line 234 of file loop-unrolling-reducer.cc.
                                     {
  switch (kind) {
    case OverflowCheckedBinopOp::Kind::kSignedAdd:
      return BinOp::kOverflowCheckedAdd;
    case OverflowCheckedBinopOp::Kind::kSignedMul:
      return BinOp::kOverflowCheckedMul;
    case OverflowCheckedBinopOp::Kind::kSignedSub:
      return BinOp::kOverflowCheckedSub;
  }
}
References kOverflowCheckedAdd, kOverflowCheckedMul, kOverflowCheckedSub, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kSignedAdd, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kSignedMul, and v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kSignedSub.
Referenced by MatchCheckedOverflowBinop().
BinopFromWordBinopKind()
constexpr StaticCanonicalForLoopMatcher::BinOp v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::BinopFromWordBinopKind (WordBinopOp::Kind kind) [static], [constexpr]
Definition at line 213 of file loop-unrolling-reducer.cc.
                                                                          {
  DCHECK(BinopKindIsSupported(kind));
  switch (kind) {
    case WordBinopOp::Kind::kAdd:
      return BinOp::kAdd;
    case WordBinopOp::Kind::kMul:
      return BinOp::kMul;
    case WordBinopOp::Kind::kSub:
      return BinOp::kSub;
    case WordBinopOp::Kind::kBitwiseAnd:
      return BinOp::kBitwiseAnd;
    case WordBinopOp::Kind::kBitwiseOr:
      return BinOp::kBitwiseOr;
    case WordBinopOp::Kind::kBitwiseXor:
      return BinOp::kBitwiseXor;
    default:
      UNREACHABLE();
  }
}
References BinopKindIsSupported(), v8::internal::DCHECK(), kAdd, v8::internal::compiler::turboshaft::WordBinopOp::kAdd, kBitwiseAnd, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseAnd, kBitwiseOr, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseOr, kBitwiseXor, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseXor, kMul, v8::internal::compiler::turboshaft::WordBinopOp::kMul, kSub, v8::internal::compiler::turboshaft::WordBinopOp::kSub, and v8::internal::UNREACHABLE().
Referenced by MatchWordBinop().
BinopKindIsSupported()
constexpr bool v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::BinopKindIsSupported (WordBinopOp::Kind binop_kind) [static], [constexpr]
Definition at line 196 of file loop-unrolling-reducer.cc.
                                {
  switch (binop_kind) {
    // This list needs to be kept in sync with the `Next` function that follows.
    case WordBinopOp::Kind::kAdd:
    case WordBinopOp::Kind::kMul:
    case WordBinopOp::Kind::kSub:
    case WordBinopOp::Kind::kBitwiseAnd:
    case WordBinopOp::Kind::kBitwiseOr:
    case WordBinopOp::Kind::kBitwiseXor:
      return true;
    default:
      return false;
  }
}
References v8::internal::compiler::turboshaft::WordBinopOp::kAdd, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseAnd, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseOr, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseXor, v8::internal::compiler::turboshaft::WordBinopOp::kMul, and v8::internal::compiler::turboshaft::WordBinopOp::kSub.
Referenced by BinopFromWordBinopKind(), and MatchWordBinop().
ComparisonKindToCmpOp()
constexpr StaticCanonicalForLoopMatcher::CmpOp v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::ComparisonKindToCmpOp (ComparisonOp::Kind kind) [static], [constexpr]
Definition at line 541 of file loop-unrolling-reducer.cc.
                                                                          {
  switch (kind) {
    case ComparisonOp::Kind::kEqual:
      return CmpOp::kEqual;
    case ComparisonOp::Kind::kSignedLessThan:
      return CmpOp::kSignedLessThan;
    case ComparisonOp::Kind::kSignedLessThanOrEqual:
      return CmpOp::kSignedLessThanOrEqual;
    case ComparisonOp::Kind::kUnsignedLessThan:
      return CmpOp::kUnsignedLessThan;
    case ComparisonOp::Kind::kUnsignedLessThanOrEqual:
      return CmpOp::kUnsignedLessThanOrEqual;
  }
}
References kEqual, v8::internal::compiler::turboshaft::ComparisonOp::kEqual, kSignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThan, kSignedLessThanOrEqual, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThanOrEqual, kUnsignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThan, kUnsignedLessThanOrEqual, and v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThanOrEqual.
Referenced by MatchPhiCompareCst().
CountIterations()
IterationCount v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::CountIterations (uint64_t equal_cst, CmpOp cmp_op, uint64_t initial_input, uint64_t binop_cst, BinOp binop_op, WordRepresentation binop_rep, bool loop_if_cond_is) const [private]
Definition at line 500 of file loop-unrolling-reducer.cc.
                                                                              {
  switch (cmp_op) {
    case CmpOp::kSignedLessThan:
    case CmpOp::kSignedLessThanOrEqual:
    case CmpOp::kSignedGreaterThan:
    case CmpOp::kSignedGreaterThanOrEqual:
    case CmpOp::kEqual:
      if (binop_rep == WordRepresentation::Word32()) {
        return CountIterationsImpl<int32_t>(
            static_cast<int32_t>(initial_input), static_cast<int32_t>(cmp_cst),
            cmp_op, static_cast<int32_t>(binop_cst), binop_op, binop_rep,
            loop_if_cond_is);
      } else {
        DCHECK_EQ(binop_rep, WordRepresentation::Word64());
        return CountIterationsImpl<int64_t>(
            static_cast<int64_t>(initial_input), static_cast<int64_t>(cmp_cst),
            cmp_op, static_cast<int64_t>(binop_cst), binop_op, binop_rep,
            loop_if_cond_is);
      }
    case CmpOp::kUnsignedLessThan:
    case CmpOp::kUnsignedLessThanOrEqual:
    case CmpOp::kUnsignedGreaterThan:
    case CmpOp::kUnsignedGreaterThanOrEqual:
      if (binop_rep == WordRepresentation::Word32()) {
        return CountIterationsImpl<uint32_t>(
            static_cast<uint32_t>(initial_input),
            static_cast<uint32_t>(cmp_cst), cmp_op,
            static_cast<uint32_t>(binop_cst), binop_op, binop_rep,
            loop_if_cond_is);
      } else {
        DCHECK_EQ(binop_rep, WordRepresentation::Word64());
        return CountIterationsImpl<uint64_t>(initial_input, cmp_cst, cmp_op,
                                             binop_cst, binop_op, binop_rep,
                                             loop_if_cond_is);
      }
  }
}
References DCHECK_EQ, kEqual, kSignedGreaterThan, kSignedGreaterThanOrEqual, kSignedLessThan, kSignedLessThanOrEqual, kUnsignedGreaterThan, kUnsignedGreaterThanOrEqual, kUnsignedLessThan, kUnsignedLessThanOrEqual, v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Referenced by GetIterCountIfStaticCanonicalForLoop().
CountIterationsImpl()
template<class Int >
IterationCount v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::CountIterationsImpl (Int init, Int max, CmpOp cmp_op, Int binop_cst, StaticCanonicalForLoopMatcher::BinOp binop_op, WordRepresentation binop_rep, bool loop_if_cond_is) const [private]
Definition at line 393 of file loop-unrolling-reducer.cc.
                                                              {
  static_assert(std::is_integral_v<Int>);
  DCHECK_EQ(std::is_unsigned_v<Int>,
            (cmp_op == CmpOp::kUnsignedLessThan ||
             cmp_op == CmpOp::kUnsignedLessThanOrEqual ||
             cmp_op == CmpOp::kUnsignedGreaterThan ||
             cmp_op == CmpOp::kUnsignedGreaterThanOrEqual));
  // It's a bit hard to compute the number of iterations without some kind of
  // (simple) SMT solver, especially when taking overflows into account. Thus,
  // we just simulate the evolution of the loop counter: we repeatedly compute
  // `init binop_op binop_cst`, and compare the result with `max`. This is
  // somewhat inefficient, so it should only be done if `kMaxExactIter` is
  // small.
  DCHECK_LE(kMaxExactIter, 10);
  Int curr = init;
  size_t iter_count = 0;
  for (; iter_count < kMaxExactIter; iter_count++) {
    if (Cmp(curr, max, cmp_op) != loop_if_cond_is) {
      return IterationCount::Exact(iter_count);
    }
    if (auto next = Next(curr, binop_cst, binop_op, binop_rep)) {
      curr = *next;
    } else {
      // There was an overflow, bailing out.
      break;
    }
  }
  if (binop_cst == 0) {
    // If {binop_cst} is 0, the loop should either execute a single time or loop
    // infinitely (since the increment is in the form of "i = i op binop_cst"
    // with op being an arithmetic or bitwise binop). If we didn't detect above
    // that it executes a single time, then we are in the latter case.
    return {};
  }
  // Trying to figure out an approximate number of iterations
  if (binop_op == StaticCanonicalForLoopMatcher::BinOp::kAdd) {
    if (cmp_op ==
            any_of(CmpOp::kUnsignedLessThan, CmpOp::kUnsignedLessThanOrEqual,
                   CmpOp::kSignedLessThan, CmpOp::kSignedLessThanOrEqual) &&
        init < max && !SubWillOverflow(max, init) && loop_if_cond_is) {
      // eg, for (int i = 0; i < 42; i += 2)
      if (binop_cst < 0) {
        // Will either loop forever or rely on underflow wrap-around to
        // eventually stop.
        return {};
      }
      DCHECK(!DivWillOverflow(max - init, binop_cst));
      Int quotient = (max - init) / binop_cst;
      DCHECK_GE(quotient, 0);
      return IterationCount::Approx(quotient);
    }
    if (cmp_op == any_of(CmpOp::kUnsignedGreaterThan,
                         CmpOp::kUnsignedGreaterThanOrEqual,
                         CmpOp::kSignedGreaterThan,
                         CmpOp::kSignedGreaterThanOrEqual) &&
        init > max && !SubWillOverflow(max, init) && loop_if_cond_is) {
      // eg, for (int i = 42; i > 0; i += -2)
      if (binop_cst > 0) {
        // Will either loop forever or rely on overflow wrap-around to
        // eventually stop.
        return {};
      }
      if (DivWillOverflow(max - init, binop_cst)) return {};
      Int quotient = (max - init) / binop_cst;
      DCHECK_GE(quotient, 0);
      return IterationCount::Approx(quotient);
    }
    if (cmp_op == CmpOp::kEqual && !SubWillOverflow(max, init) &&
        !loop_if_cond_is) {
      // eg, for (int i = 0; i != 42; i += 2)
      // or, for (int i = 42; i != 0; i += -2)
      if (init < max && binop_cst < 0) {
        // Will either loop forever or rely on underflow wrap-around to
        // eventually stop.
        return {};
      }
      if (init > max && binop_cst > 0) {
        // Will either loop forever or rely on overflow wrap-around to
        // eventually stop.
        return {};
      }
      Int remainder = (max - init) % binop_cst;
      if (remainder != 0) {
        // Will loop forever or rely on over/underflow wrap-around to eventually
        // stop.
        return {};
      }
      Int quotient = (max - init) / binop_cst;
      DCHECK_GE(quotient, 0);
      return IterationCount::Approx(quotient);
    }
  }
  return {};
}
References v8::internal::compiler::turboshaft::any_of(), v8::internal::compiler::turboshaft::IterationCount::Approx(), v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Cmp(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_LE, v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::DivWillOverflow(), v8::internal::compiler::turboshaft::IterationCount::Exact(), kAdd, kEqual, kMaxExactIter, kSignedGreaterThan, kSignedGreaterThanOrEqual, kSignedLessThan, kSignedLessThanOrEqual, kUnsignedGreaterThan, kUnsignedGreaterThanOrEqual, kUnsignedLessThan, kUnsignedLessThanOrEqual, v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), and v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::SubWillOverflow().
GetIterCountIfStaticCanonicalForLoop()
IterationCount v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::GetIterCountIfStaticCanonicalForLoop (const Block * header, OpIndex cond_idx, bool loop_if_cond_is) const
Definition at line 138 of file loop-unrolling-reducer.cc.
                                                                       {
  CmpOp cmp_op;
  OpIndex phi_idx;
  uint64_t cmp_cst;
  if (!MatchPhiCompareCst(cond_idx, &cmp_op, &phi_idx, &cmp_cst)) {
    return {};
  }
  if (!header->Contains(phi_idx)) {
    // The termination condition for this loop is based on a Phi that is defined
    // in another loop.
    return {};
  }
  const PhiOp& phi = matcher_.Cast<PhiOp>(phi_idx);
  // We have: phi(..., ...) cmp_op cmp_cst
  // eg, for (i = ...; i < 42; ...)
  uint64_t phi_cst;
  if (matcher_.MatchUnsignedIntegralConstant(phi.input(0), &phi_cst)) {
    // We have: phi(phi_cst, ...) cmp_op cmp_cst
    // eg, for (i = 0; i < 42; ...)
    V<Word> left, right;
    BinOp binop_op;
    WordRepresentation binop_rep;
    if (MatchWordBinop(phi.input(1), &left, &right, &binop_op, &binop_rep) ||
        MatchCheckedOverflowBinop(phi.input(1), &left, &right, &binop_op,
                                  &binop_rep)) {
      // We have: phi(phi_cst, ... binop_op ...) cmp_op cmp_cst
      // eg, for (i = 0; i < 42; i = ... + ...)
      if (left == phi_idx) {
        // We have: phi(phi_cst, phi binop_op ...) cmp_op cmp_cst
        // eg, for (i = 0; i < 42; i = i + ...)
        uint64_t binop_cst;
        if (matcher_.MatchUnsignedIntegralConstant(right, &binop_cst)) {
          // We have: phi(phi_cst, phi binop_op binop_cst) cmp_op cmp_cst
          // eg, for (i = 0; i < 42; i = i + 2)
          return CountIterations(cmp_cst, cmp_op, phi_cst, binop_cst, binop_op,
                                 binop_rep, loop_if_cond_is);
        }
      } else if (right == phi_idx) {
        // We have: phi(phi_cst, ... binop_op phi) cmp_op cmp_cst
        // eg, for (i = 0; i < 42; i = ... + i)
        uint64_t binop_cst;
        if (matcher_.MatchUnsignedIntegralConstant(left, &binop_cst)) {
          // We have: phi(phi_cst, binop_cst binop_op phi) cmp_op cmp_cst
          // eg, for (i = 0; i < 42; i = 2 + i)
          return CountIterations(cmp_cst, cmp_op, phi_cst, binop_cst, binop_op,
                                 binop_rep, loop_if_cond_is);
        }
      }
    }
  }
  // The condition is not an operation that we support.
  return {};
}
References v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::compiler::turboshaft::Block::Contains(), CountIterations(), v8::internal::compiler::turboshaft::OperationT< Derived >::input(), MatchCheckedOverflowBinop(), matcher_, MatchPhiCompareCst(), v8::internal::compiler::turboshaft::OperationMatcher::MatchUnsignedIntegralConstant(), and MatchWordBinop().
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetLoopIterationCount().
InvertComparisonOp()
constexpr StaticCanonicalForLoopMatcher::CmpOp v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::InvertComparisonOp (CmpOp op) [static], [constexpr]
Definition at line 556 of file loop-unrolling-reducer.cc.
                                                          {
  switch (op) {
    case CmpOp::kEqual:
      return CmpOp::kEqual;
    case CmpOp::kSignedLessThan:
      return CmpOp::kSignedGreaterThan;
    case CmpOp::kSignedLessThanOrEqual:
      return CmpOp::kSignedGreaterThanOrEqual;
    case CmpOp::kUnsignedLessThan:
      return CmpOp::kUnsignedGreaterThan;
    case CmpOp::kUnsignedLessThanOrEqual:
      return CmpOp::kUnsignedGreaterThanOrEqual;
    case CmpOp::kSignedGreaterThan:
      return CmpOp::kSignedLessThan;
    case CmpOp::kSignedGreaterThanOrEqual:
      return CmpOp::kSignedLessThanOrEqual;
    case CmpOp::kUnsignedGreaterThan:
      return CmpOp::kUnsignedLessThan;
    case CmpOp::kUnsignedGreaterThanOrEqual:
      return CmpOp::kUnsignedLessThanOrEqual;
  }
}
References kEqual, kSignedGreaterThan, kSignedGreaterThanOrEqual, kSignedLessThan, kSignedLessThanOrEqual, kUnsignedGreaterThan, kUnsignedGreaterThanOrEqual, kUnsignedLessThan, and kUnsignedLessThanOrEqual.
Referenced by MatchPhiCompareCst().
MatchCheckedOverflowBinop()
bool v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::MatchCheckedOverflowBinop (OpIndex idx, V< Word > * left, V< Word > * right, BinOp * binop_op, WordRepresentation * binop_rep) const [private]
Definition at line 108 of file loop-unrolling-reducer.cc.
                                         {
  if (const ProjectionOp* proj = matcher_.TryCast<ProjectionOp>(idx)) {
    if (proj->index != OverflowCheckedBinopOp::kValueIndex) return false;
    if (const OverflowCheckedBinopOp* binop =
            matcher_.TryCast<OverflowCheckedBinopOp>(proj->input())) {
      *left = binop->left();
      *right = binop->right();
      *binop_op = BinopFromOverflowCheckedBinopKind(binop->kind);
      *binop_rep = binop->rep;
      return true;
    }
  }
  return false;
}
References BinopFromOverflowCheckedBinopKind(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kValueIndex, matcher_, and v8::internal::compiler::turboshaft::OperationMatcher::TryCast().
Referenced by GetIterCountIfStaticCanonicalForLoop().
MatchPhiCompareCst()
bool v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::MatchPhiCompareCst (OpIndex cond_idx, StaticCanonicalForLoopMatcher::CmpOp * cmp_op, OpIndex * phi, uint64_t * cst) const [private]
Definition at line 79 of file loop-unrolling-reducer.cc.
                                       {
  const Operation& cond = matcher_.Get(cond_idx);
  if (const ComparisonOp* cmp = cond.TryCast<ComparisonOp>()) {
    *cmp_op = ComparisonKindToCmpOp(cmp->kind);
  } else {
    return false;
  }
  OpIndex left = cond.input(0);
  OpIndex right = cond.input(1);
  if (matcher_.MatchPhi(left, 2)) {
    if (matcher_.MatchUnsignedIntegralConstant(right, cst)) {
      *phi = left;
      return true;
    }
  } else if (matcher_.MatchPhi(right, 2)) {
    if (matcher_.MatchUnsignedIntegralConstant(left, cst)) {
      *cmp_op = InvertComparisonOp(*cmp_op);
      *phi = right;
      return true;
    }
  }
  return false;
}
References ComparisonKindToCmpOp(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), InvertComparisonOp(), matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchUnsignedIntegralConstant(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by GetIterCountIfStaticCanonicalForLoop().
MatchWordBinop()
bool v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::MatchWordBinop (OpIndex idx, V< Word > * left, V< Word > * right, BinOp * binop_op, WordRepresentation * binop_rep) const [private]
Definition at line 125 of file loop-unrolling-reducer.cc.
                                         {
  WordBinopOp::Kind kind;
  if (matcher_.MatchWordBinop<Word>(idx, left, right, &kind, binop_rep) &&
      BinopKindIsSupported(kind)) {
    *binop_op = BinopFromWordBinopKind(kind);
    return true;
  }
  return false;
}
References BinopFromWordBinopKind(), BinopKindIsSupported(), and matcher_.
Referenced by GetIterCountIfStaticCanonicalForLoop().
Member Data Documentation
kMaxExactIter
constexpr size_t v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::kMaxExactIter = 5 [static], [constexpr], [private]
Definition at line 161 of file loop-unrolling-reducer.h.
Referenced by CountIterationsImpl().
matcher_
const OperationMatcher& v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::matcher_ [private]
Definition at line 154 of file loop-unrolling-reducer.h.
Referenced by GetIterCountIfStaticCanonicalForLoop(), MatchCheckedOverflowBinop(), MatchPhiCompareCst(), and MatchWordBinop().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/loop-unrolling-reducer.h
/mnt/V8SourceCode/src/compiler/turboshaft/loop-unrolling-reducer.cc