v8::internal::MutablePageMetadata Class Reference
#include <mutable-page-metadata.h>
Public Types
enum class ConcurrentSweepingState : intptr_t { kDone
, kPendingSweeping
, kPendingIteration
, kInProgress
 }
Public Member Functions
MutablePageMetadata (Heap *heap, BaseSpace *space, size_t size, Address area_start, Address area_end, VirtualMemory reservation, PageSize page_size)
MemoryChunk::MainThreadFlags InitialFlags (Executability executable) const
size_t BucketsInSlotSet () const
void SetOldGenerationPageFlags (MarkingMode marking_mode)
void SetYoungGenerationPageFlags (MarkingMode marking_mode)
base::Mutex & mutex ()
const base::Mutex & mutex () const
base::Mutex & object_mutex ()
const base::Mutex & object_mutex () const
void set_concurrent_sweeping_state (ConcurrentSweepingState state)
ConcurrentSweepingState concurrent_sweeping_state ()
bool SweepingDone () const
template<RememberedSetType type, AccessMode access_mode = AccessMode::ATOMIC>
SlotSet * slot_set ()
template<RememberedSetType type, AccessMode access_mode = AccessMode::ATOMIC>
const SlotSet * slot_set () const
template<RememberedSetType type, AccessMode access_mode = AccessMode::ATOMIC>
TypedSlotSet * typed_slot_set ()
template<RememberedSetType type, AccessMode access_mode = AccessMode::ATOMIC>
const TypedSlotSet * typed_slot_set () const
template<RememberedSetType type>
bool ContainsSlots () const
bool ContainsAnySlots () const
V8_EXPORT_PRIVATE SlotSet * AllocateSlotSet (RememberedSetType type)
void ReleaseSlotSet (RememberedSetType type)
TypedSlotSet * AllocateTypedSlotSet (RememberedSetType type)
void ReleaseTypedSlotSet (RememberedSetType type)
template<RememberedSetType type>
SlotSet * ExtractSlotSet ()
template<RememberedSetType type>
TypedSlotSet * ExtractTypedSlotSet ()
int ComputeFreeListsLength ()
V8_EXPORT_PRIVATE size_t CommittedPhysicalMemory () const
MarkingProgressTracker & marking_progress_tracker ()
const MarkingProgressTracker & marking_progress_tracker () const
void IncrementExternalBackingStoreBytes (ExternalBackingStoreType type, size_t amount)
void DecrementExternalBackingStoreBytes (ExternalBackingStoreType type, size_t amount)
size_t ExternalBackingStoreBytes (ExternalBackingStoreType type) const
Space * owner () const
AllocationSpace owner_identity () const
heap::ListNode< MutablePageMetadata > & list_node ()
const heap::ListNode< MutablePageMetadata > & list_node () const
PossiblyEmptyBuckets * possibly_empty_buckets ()
void ReleaseAllocatedMemoryNeededForWritableChunk ()
void IncreaseAllocatedLabSize (size_t bytes)
void DecreaseAllocatedLabSize (size_t bytes)
size_t AllocatedLabSize () const
void IncrementAgeInNewSpace ()
void ResetAgeInNewSpace ()
size_t AgeInNewSpace () const
void ResetAllocationStatistics ()
void ResetAllocationStatisticsForPromotedPage ()
MarkingBitmap * marking_bitmap ()
const MarkingBitmap * marking_bitmap () const
size_t live_bytes () const
void SetLiveBytes (size_t value)
void IncrementLiveBytesAtomically (intptr_t diff)
template<AccessMode mode = AccessMode::NON_ATOMIC>
void ClearLiveness ()
bool IsLivenessClear () const
bool IsLargePage ()
Static Public Member Functions
static PageAllocator::Permission GetCodeModificationPermission ()
static void MoveExternalBackingStoreBytes (ExternalBackingStoreType type, MutablePageMetadata *from, MutablePageMetadata *to, size_t amount)
static MutablePageMetadata * FromAddress (Address a)
static MutablePageMetadata * FromHeapObject (Tagged< HeapObject > o)
static MutablePageMetadata * cast (MemoryChunkMetadata *metadata)
static const MutablePageMetadata * cast (const MemoryChunkMetadata *metadata)
Static Public Attributes
static const int kPageSize = kRegularPageSize
Protected Member Functions
void ReleaseAllAllocatedMemory ()
template<RememberedSetType type, AccessMode access_mode = AccessMode::ATOMIC>
void set_slot_set (SlotSet *slot_set)
template<RememberedSetType type, AccessMode access_mode = AccessMode::ATOMIC>
void set_typed_slot_set (TypedSlotSet *typed_slot_set)
Protected Attributes
SlotSet * slot_set_ [NUMBER_OF_REMEMBERED_SET_TYPES] = {nullptr}
TypedSlotSet * typed_slot_set_ [NUMBER_OF_REMEMBERED_SET_TYPES] = {nullptr}
MarkingProgressTracker marking_progress_tracker_
std::atomic< intptr_t > live_byte_count_ {0}
std::atomic< ConcurrentSweepingState > concurrent_sweeping_
std::atomic< size_t > external_backing_store_bytes_ [static_cast< int >(ExternalBackingStoreType::kNumValues)] = {0}
heap::ListNode< MutablePageMetadata > list_node_
FreeListCategory ** categories_ = nullptr
PossiblyEmptyBuckets possibly_empty_buckets_
std::unique_ptr< ActiveSystemPages > active_system_pages_
size_t allocated_lab_size_ = 0
size_t age_in_new_space_ = 0
MarkingBitmap marking_bitmap_
base::Mutex mutex_
base::Mutex object_mutex_
Static Private Member Functions
static constexpr intptr_t MarkingBitmapOffset ()
static constexpr intptr_t SlotSetOffset (RememberedSetType remembered_set_type)
Friends
class MemoryAllocator
class PagePool
template<RememberedSetType >
class RememberedSet
class CodeStubAssembler
class MacroAssembler
class MarkingBitmap
class TestWithBitmap
class WriteBarrierCodeStubAssembler
Detailed Description
Definition at line 46 of file mutable-page-metadata.h.
Member Enumeration Documentation
ConcurrentSweepingState
enum v8::internal::MutablePageMetadata::ConcurrentSweepingState : intptr_t [strong]
Enumerator
kDone
kPendingSweeping
kPendingIteration
kInProgress
Definition at line 54 of file mutable-page-metadata.h.
                                     : intptr_t {
    kDone,
    kPendingSweeping,
    kPendingIteration,
    kInProgress,
  };
Constructor & Destructor Documentation
MutablePageMetadata()
v8::internal::MutablePageMetadata::MutablePageMetadata (Heap * heap, BaseSpace * space, size_t size, Address area_start, Address area_end, VirtualMemory reservation, PageSize page_size)
Definition at line 24 of file mutable-page-metadata.cc.
    : MemoryChunkMetadata(heap, space, chunk_size, area_start, area_end,
                          std::move(reservation)) {
  DCHECK_NE(space->identity(), RO_SPACE);
  if (page_size == PageSize::kRegular) {
    active_system_pages_ = std::make_unique<ActiveSystemPages>();
    active_system_pages_->Init(
        sizeof(MemoryChunk), MemoryAllocator::GetCommitPageSizeBits(), size());
  }
  // We do not track active system pages for large pages and use this fact for
  // `IsLargePage()`.
  DCHECK_EQ(page_size == PageSize::kLarge, IsLargePage());
  // TODO(sroettger): The following fields are accessed most often (AFAICT) and
  // are moved to the end to occupy the same cache line as the slot set array.
  // Without this change, there was a 0.5% performance impact after cache line
  // aligning the metadata on x64 (before, the metadata started at offset 0x10).
  // After reordering, the impact is still 0.1%/0.2% on jetstream2/speedometer3,
  // so there should be some more optimization potential here.
  // TODO(mlippautz): Replace 64 below with
  // `hardware_destructive_interference_size` once supported.
  static constexpr auto kOffsetOfFirstFastField =
      offsetof(MutablePageMetadata, heap_);
  static constexpr auto kOffsetOfLastFastField =
      offsetof(MutablePageMetadata, slot_set_) +
      sizeof(SlotSet*) * RememberedSetType::OLD_TO_NEW;
  // This assert is merely necessary but not sufficient to guarantee that the
  // fields sit on the same cacheline as the metadata object itself is
  // dynamically allocated without alignment restrictions.
  static_assert(kOffsetOfFirstFastField / 64 == kOffsetOfLastFastField / 64);
}
References active_system_pages_, DCHECK_EQ, DCHECK_NE, v8::internal::MemoryAllocator::GetCommitPageSizeBits(), v8::internal::MemoryChunkMetadata::heap_, IsLargePage(), v8::internal::kLarge, v8::internal::kRegular, v8::internal::OLD_TO_NEW, v8::internal::RO_SPACE, v8::internal::MemoryChunkMetadata::size(), slot_set_, and space.
Member Function Documentation
AgeInNewSpace()
size_t v8::internal::MutablePageMetadata::AgeInNewSpace () const [inline]
Definition at line 232 of file mutable-page-metadata.h.
{ return age_in_new_space_; }
References age_in_new_space_.
Referenced by v8::internal::Sweeper::AddNewSpacePage(), and v8::internal::anonymous_namespace{minor-mark-sweep.cc}::ShouldMovePage().
AllocatedLabSize()
size_t v8::internal::MutablePageMetadata::AllocatedLabSize () const [inline]
Definition at line 228 of file mutable-page-metadata.h.
{ return allocated_lab_size_; }
References allocated_lab_size_.
Referenced by v8::internal::PagedSpaceForNewSpace::IsPromotionCandidate(), v8::internal::anonymous_namespace{minor-mark-sweep.cc}::ShouldMovePage(), and v8::internal::anonymous_namespace{mark-compact.cc}::ShouldMovePage().
AllocateSlotSet()
SlotSet * v8::internal::MutablePageMetadata::AllocateSlotSet (RememberedSetType type)
Definition at line 144 of file mutable-page-metadata.cc.
                                                                    {
  SlotSet* new_slot_set = SlotSet::Allocate(BucketsInSlotSet());
  SlotSet* old_slot_set = base::AsAtomicPointer::AcquireRelease_CompareAndSwap(
      &slot_set_[type], nullptr, new_slot_set);
  if (old_slot_set) {
    SlotSet::Delete(new_slot_set);
    new_slot_set = old_slot_set;
  }
  DCHECK_NOT_NULL(new_slot_set);
  return new_slot_set;
}
References v8::base::AsAtomicImpl< TAtomicStorageType >::AcquireRelease_CompareAndSwap(), v8::internal::SlotSet::Allocate(), BucketsInSlotSet(), DCHECK_NOT_NULL, heap::base::BasicSlotSet< kTaggedSize >::Delete(), slot_set_, and v8::internal::tracing::type.
Referenced by v8::internal::RememberedSet< type >::Insert().
AllocateTypedSlotSet()
TypedSlotSet * v8::internal::MutablePageMetadata::AllocateTypedSlotSet (RememberedSetType type)
Definition at line 164 of file mutable-page-metadata.cc.
                            {
  TypedSlotSet* typed_slot_set = new TypedSlotSet(ChunkAddress());
  TypedSlotSet* old_value = base::AsAtomicPointer::Release_CompareAndSwap(
      &typed_slot_set_[type], nullptr, typed_slot_set);
  if (old_value) {
    delete typed_slot_set;
    typed_slot_set = old_value;
  }
  DCHECK(typed_slot_set);
  return typed_slot_set;
}
References v8::internal::MemoryChunkMetadata::ChunkAddress(), v8::internal::DCHECK(), v8::base::AsAtomicImpl< TAtomicStorageType >::Release_CompareAndSwap(), v8::internal::tracing::type, typed_slot_set(), and typed_slot_set_.
Referenced by v8::internal::RememberedSet< type >::InsertTyped(), and v8::internal::RememberedSet< type >::MergeTyped().
BucketsInSlotSet()
size_t v8::internal::MutablePageMetadata::BucketsInSlotSet () const [inline]
Definition at line 95 of file mutable-page-metadata.h.
{ return SlotSet::BucketsForSize(size()); }
References heap::base::BasicSlotSet< kTaggedSize >::BucketsForSize(), and v8::internal::MemoryChunkMetadata::size().
Referenced by AllocateSlotSet(), v8::internal::RememberedSet< type >::CheckPossiblyEmptyBuckets(), v8::internal::LargePageMetadata::ClearOutOfLiveRangeSlots(), v8::internal::MinorMarkSweepCollector::EvacuateExternalPointerReferences(), v8::internal::RememberedSetOperations::Iterate(), v8::internal::RememberedSet< type >::IterateAndTrackEmptyBuckets(), v8::internal::RememberedSet< type >::MergeAndDelete(), and v8::internal::RememberedSetOperations::RemoveRange().
cast() [1/2]
static const MutablePageMetadata* v8::internal::MutablePageMetadata::cast (const MemoryChunkMetadata * metadata) [inline], [static]
Definition at line 84 of file mutable-page-metadata.h.
                                                                              {
    SBXCHECK(metadata->IsMutablePageMetadata());
    return static_cast<const MutablePageMetadata*>(metadata);
  }
References v8::internal::MemoryChunkMetadata::IsMutablePageMetadata(), and SBXCHECK.
cast() [2/2]
static MutablePageMetadata* v8::internal::MutablePageMetadata::cast (MemoryChunkMetadata * metadata) [inline], [static]
Definition at line 79 of file mutable-page-metadata.h.
                                                                  {
    SBXCHECK(metadata->IsMutablePageMetadata());
    return static_cast<MutablePageMetadata*>(metadata);
  }
References v8::internal::MemoryChunkMetadata::IsMutablePageMetadata(), and SBXCHECK.
Referenced by v8::internal::LargePageMetadata::cast(), v8::internal::PageMetadata::cast(), v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::CheckForSharedObject(), v8::internal::Heap::EnsureSweepingCompletedForObject(), v8::internal::anonymous_namespace{heap-write-barrier.cc}::ForRangeImpl(), FromAddress(), FromHeapObject(), v8::internal::WriteBarrier::GenerationalBarrierSlow(), v8::internal::IterateAndScavengePromotedObjectsVisitor::HandleSlot(), v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlot(), v8::internal::MarkCompactCollector::RecordSlot(), v8::internal::ConcurrentMarking::RunMajor(), v8::internal::WriteBarrier::SharedHeapBarrierSlow(), v8::internal::Heap::AllocationTrackerForDebugging::UpdateAllocationsHash(), and v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitObjectViaSlot().
ClearLiveness()
template<AccessMode mode>
void v8::internal::MutablePageMetadata::ClearLiveness
Definition at line 69 of file mutable-page-metadata-inl.h.
                                        {
  marking_bitmap()->Clear<mode>();
  SetLiveBytes(0);
}
References v8::internal::MarkingBitmap::Clear(), marking_bitmap(), mode(), and SetLiveBytes().
Referenced by v8::internal::NewLargeObjectSpace::AllocateRaw(), v8::internal::PagedSpaceForNewSpace::InitializePage(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), v8::internal::Evacuator::RawEvacuatePage(), v8::internal::PagedSpaceBase::TearDown(), and v8::internal::SemiSpace::~SemiSpace().
CommittedPhysicalMemory()
size_t v8::internal::MutablePageMetadata::CommittedPhysicalMemory () const
Definition at line 108 of file mutable-page-metadata.cc.
                                                          {
  if (!base::OS::HasLazyCommits() || Chunk()->IsLargePage()) return size();
  return active_system_pages_->Size(MemoryAllocator::GetCommitPageSizeBits());
}
References active_system_pages_, v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryAllocator::GetCommitPageSizeBits(), v8::base::OS::HasLazyCommits(), IsLargePage(), and v8::internal::MemoryChunkMetadata::size().
Referenced by v8::internal::PagedSpaceBase::AddPageImpl(), v8::internal::SemiSpace::AllocateFreshPage(), v8::internal::SemiSpace::MoveQuarantinedPage(), v8::internal::SemiSpace::RemovePage(), v8::internal::PagedSpaceBase::RemovePage(), v8::internal::PagedSpaceBase::RemovePageFromSpaceImpl(), and v8::internal::SemiSpace::RewindPages().
ComputeFreeListsLength()
int v8::internal::MutablePageMetadata::ComputeFreeListsLength ()
Definition at line 194 of file mutable-page-metadata.cc.
                                                {
  int length = 0;
  for (int cat = kFirstCategory; cat <= owner()->free_list()->last_category();
       cat++) {
    if (categories_[cat] != nullptr) {
      length += categories_[cat]->FreeListLength();
    }
  }
  return length;
}
References categories_, v8::internal::Space::free_list(), v8::internal::FreeListCategory::FreeListLength(), v8::internal::kFirstCategory, v8::internal::FreeList::last_category(), v8::internal::length, and owner().
Referenced by v8::internal::MarkCompactCollector::AddEvacuationCandidate().
concurrent_sweeping_state()
ConcurrentSweepingState v8::internal::MutablePageMetadata::concurrent_sweeping_state () [inline]
Definition at line 111 of file mutable-page-metadata.h.
                                                      {
    return static_cast<ConcurrentSweepingState>(concurrent_sweeping_.load());
  }
References concurrent_sweeping_.
Referenced by v8::internal::Sweeper::AddPageImpl(), v8::internal::Sweeper::AddPromotedPage(), v8::internal::Sweeper::EnsurePageIsSwept(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), v8::internal::Sweeper::LocalSweeper::ParallelSweepPage(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), and v8::internal::anonymous_namespace{sweeper.cc}::VerifyPreparedPage().
ContainsAnySlots()
bool v8::internal::MutablePageMetadata::ContainsAnySlots () const
Definition at line 185 of file mutable-page-metadata.cc.
                                                 {
  for (int rs_type = 0; rs_type < NUMBER_OF_REMEMBERED_SET_TYPES; rs_type++) {
    if (slot_set_[rs_type] || typed_slot_set_[rs_type]) {
      return true;
    }
  }
  return false;
}
References v8::internal::NUMBER_OF_REMEMBERED_SET_TYPES, slot_set_, and typed_slot_set_.
Referenced by v8::internal::PagePool::Add().
ContainsSlots()
template<RememberedSetType type>
bool v8::internal::MutablePageMetadata::ContainsSlots () const [inline]
Definition at line 146 of file mutable-page-metadata.h.
                             {
    return slot_set<type>() != nullptr || typed_slot_set<type>() != nullptr;
  }
DecreaseAllocatedLabSize()
void v8::internal::MutablePageMetadata::DecreaseAllocatedLabSize (size_t bytes) [inline]
Definition at line 224 of file mutable-page-metadata.h.
                                              {
    DCHECK_GE(allocated_lab_size_, bytes);
    allocated_lab_size_ -= bytes;
  }
References allocated_lab_size_, and DCHECK_GE.
Referenced by v8::internal::PagedNewSpaceAllocatorPolicy::EnsureAllocation(), and v8::internal::PagedNewSpaceAllocatorPolicy::FreeLinearAllocationArea().
DecrementExternalBackingStoreBytes()
void v8::internal::MutablePageMetadata::DecrementExternalBackingStoreBytes (ExternalBackingStoreType type, size_t amount) [inline]
Definition at line 35 of file mutable-page-metadata-inl.h.
                                                  {
  base::CheckedDecrement(&external_backing_store_bytes_[static_cast<int>(type)],
                         amount);
  owner()->DecrementExternalBackingStoreBytes(type, amount);
}
References v8::internal::Space::DecrementExternalBackingStoreBytes(), external_backing_store_bytes_, owner(), and v8::internal::tracing::type.
Referenced by v8::internal::Heap::FinalizeExternalString(), and v8::internal::Heap::UpdateExternalString().
ExternalBackingStoreBytes()
size_t v8::internal::MutablePageMetadata::ExternalBackingStoreBytes (ExternalBackingStoreType type) const [inline]
Definition at line 198 of file mutable-page-metadata.h.
                                                                        {
    return external_backing_store_bytes_[static_cast<int>(type)];
  }
References external_backing_store_bytes_, and v8::internal::tracing::type.
Referenced by v8::internal::LargeObjectSpace::AddPage(), v8::internal::PagedSpaceBase::AddPageImpl(), v8::internal::LargeObjectSpace::RemovePage(), v8::internal::SemiSpace::RemovePage(), and v8::internal::PagedSpaceBase::RemovePage().
ExtractSlotSet()
template<RememberedSetType type>
SlotSet* v8::internal::MutablePageMetadata::ExtractSlotSet () [inline]
Definition at line 159 of file mutable-page-metadata.h.
                            {
    SlotSet* slot_set = slot_set_[type];
    // Conditionally reset to nullptr (instead of e.g. using std::exchange) to
    // avoid data races when transitioning from nullptr to nullptr.
    if (slot_set) {
      slot_set_[type] = nullptr;
    }
    return slot_set;
  }
References slot_set(), slot_set_, and v8::internal::tracing::type.
Referenced by v8::internal::YoungGenerationRememberedSetsMarkingWorklist::CollectItems().
ExtractTypedSlotSet()
template<RememberedSetType type>
TypedSlotSet* v8::internal::MutablePageMetadata::ExtractTypedSlotSet () [inline]
Definition at line 170 of file mutable-page-metadata.h.
                                      {
    TypedSlotSet* typed_slot_set = typed_slot_set_[type];
    // Conditionally reset to nullptr (instead of e.g. using std::exchange) to
    // avoid data races when transitioning from nullptr to nullptr.
    if (typed_slot_set) {
      typed_slot_set_[type] = nullptr;
    }
    return typed_slot_set;
  }
References v8::internal::tracing::type, typed_slot_set(), and typed_slot_set_.
Referenced by v8::internal::YoungGenerationRememberedSetsMarkingWorklist::CollectItems().
FromAddress()
MutablePageMetadata * v8::internal::MutablePageMetadata::FromAddress (Address a) [inline], [static]
Definition at line 19 of file mutable-page-metadata-inl.h.
                                                               {
  return cast(MemoryChunkMetadata::FromAddress(a));
}
References cast(), and v8::internal::MemoryChunkMetadata::FromAddress().
Referenced by v8::internal::MarkingBitmap::FromAddress().
FromHeapObject()
MutablePageMetadata * v8::internal::MutablePageMetadata::FromHeapObject (Tagged< HeapObject > o) [inline], [static]
Definition at line 24 of file mutable-page-metadata-inl.h.
                                                                             {
  return cast(MemoryChunkMetadata::FromHeapObject(o));
}
References cast(), and v8::internal::MemoryChunkMetadata::FromHeapObject().
Referenced by v8::internal::Heap::AllowedToBeMigrated(), v8::internal::Heap::CanMoveObjectStart(), v8::internal::WriteBarrier::CombinedGenerationalAndSharedEphemeronBarrierSlow(), v8::internal::WriteBarrier::CurrentMarkingBarrier(), v8::internal::MinorMarkSweepCollector::DrainMarkingWorklist(), v8::internal::LargePageMetadata::FromHeapObject(), v8::internal::anonymous_namespace{serializer.cc}::GetSnapshotSpace(), v8::internal::Scavenger::HandleLargeObject(), v8::internal::ObjectLock::Lock(), v8::internal::IncrementalMarking::MarkBlackBackground(), v8::internal::WriteBarrier::MarkingFromCode(), v8::internal::Heap::NotifyObjectLayoutChange(), v8::internal::ConcurrentMarking::RunMinorImpl(), v8::internal::WriteBarrier::SharedMarkingFromCode(), v8::internal::WriteBarrier::SharedSlow(), v8::internal::EvacuateVisitorBase::TryEvacuateObject(), v8::internal::MarkingStateBase< NonAtomicMarkingState, AccessMode::NON_ATOMIC >::TryMark(), v8::internal::MarkingStateBase< ConcreteState, access_mode >::TryMarkAndAccountLiveBytes(), v8::internal::ObjectLock::Unlock(), v8::internal::Heap::ExternalStringTable::Verify(), v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VerifyHost(), v8::internal::Heap::ExternalStringTable::VerifyYoung(), and v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitFixedArray().
GetCodeModificationPermission()
static PageAllocator::Permission v8::internal::MutablePageMetadata::GetCodeModificationPermission () [inline], [static]
Definition at line 64 of file mutable-page-metadata.h.
                                                                 {
    return v8_flags.jitless ? PageAllocator::kReadWrite
                            : PageAllocator::kReadWriteExecute;
  }
References v8::PageAllocator::kReadWrite, v8::PageAllocator::kReadWriteExecute, and v8::internal::v8_flags.
Referenced by v8::internal::MemoryAllocator::AllocateAlignedMemory(), and v8::internal::MemoryAllocator::SetPermissionsOnExecutableMemoryChunk().
IncreaseAllocatedLabSize()
void v8::internal::MutablePageMetadata::IncreaseAllocatedLabSize (size_t bytes) [inline]
Definition at line 223 of file mutable-page-metadata.h.
{ allocated_lab_size_ += bytes; }
References allocated_lab_size_.
Referenced by v8::internal::PagedNewSpaceAllocatorPolicy::EnsureAllocation().
IncrementAgeInNewSpace()
void v8::internal::MutablePageMetadata::IncrementAgeInNewSpace () [inline]
Definition at line 230 of file mutable-page-metadata.h.
{ age_in_new_space_++; }
References age_in_new_space_.
Referenced by v8::internal::Sweeper::AddNewSpacePage().
IncrementExternalBackingStoreBytes()
void v8::internal::MutablePageMetadata::IncrementExternalBackingStoreBytes (ExternalBackingStoreType type, size_t amount) [inline]
Definition at line 28 of file mutable-page-metadata-inl.h.
                                                  {
  base::CheckedIncrement(&external_backing_store_bytes_[static_cast<int>(type)],
                         amount);
  owner()->IncrementExternalBackingStoreBytes(type, amount);
}
References v8::base::CheckedIncrement(), external_backing_store_bytes_, v8::internal::Space::IncrementExternalBackingStoreBytes(), owner(), and v8::internal::tracing::type.
Referenced by v8::internal::Heap::UpdateExternalString().
IncrementLiveBytesAtomically()
void v8::internal::MutablePageMetadata::IncrementLiveBytesAtomically (intptr_t diff) [inline]
Definition at line 266 of file mutable-page-metadata.h.
                                                   {
    DCHECK_IMPLIES(V8_COMPRESS_POINTERS_8GB_BOOL,
                   ::IsAligned(diff, kObjectAlignment8GbHeap));
    live_byte_count_.fetch_add(diff, std::memory_order_relaxed);
  }
References DCHECK_IMPLIES, IsAligned(), v8::internal::kObjectAlignment8GbHeap, live_byte_count_, and V8_COMPRESS_POINTERS_8GB_BOOL.
Referenced by v8::internal::PageMetadata::CreateBlackArea(), v8::internal::PageMetadata::DestroyBlackArea(), v8::internal::MemoryChunkLiveBytesMap::Increment(), v8::internal::IncrementalMarking::Stop(), v8::internal::MarkingStateBase< NonAtomicMarkingState, AccessMode::NON_ATOMIC >::TryMark(), and v8::internal::MarkingStateBase< ConcreteState, access_mode >::TryMarkAndAccountLiveBytes().
InitialFlags()
MemoryChunk::MainThreadFlags v8::internal::MutablePageMetadata::InitialFlags (Executability executable) const
Definition at line 62 of file mutable-page-metadata.cc.
                                    {
  MemoryChunk::MainThreadFlags flags = MemoryChunk::NO_FLAGS;
  if (owner()->identity() == NEW_SPACE || owner()->identity() == NEW_LO_SPACE) {
    flags |= MemoryChunk::YoungGenerationPageFlags(
        heap()->incremental_marking()->marking_mode());
  } else {
    flags |= MemoryChunk::OldGenerationPageFlags(
        heap()->incremental_marking()->marking_mode(), owner()->identity());
  }
  if (executable == EXECUTABLE) {
    flags |= MemoryChunk::IS_EXECUTABLE;
    // Executable chunks are also trusted as they contain machine code and live
    // outside the sandbox (when it is enabled). While mostly symbolic, this is
    // needed for two reasons:
    // 1. We have the invariant that IsTrustedObject(obj) implies
    // IsTrustedSpaceObject(obj), where IsTrustedSpaceObject checks the
    // MemoryChunk::IS_TRUSTED flag on the host chunk. As InstructionStream
    // objects are
    // trusted, their host chunks must also be marked as such.
    // 2. References between trusted objects must use the TRUSTED_TO_TRUSTED
    // remembered set. However, that will only be used if both the host
    // and the value chunk are marked as IS_TRUSTED.
    flags |= MemoryChunk::IS_TRUSTED;
  }
  // All pages of a shared heap need to be marked with this flag.
  if (InSharedSpace()) {
    flags |= MemoryChunk::IN_WRITABLE_SHARED_SPACE;
  }
  // All pages belonging to a trusted space need to be marked with this flag.
  if (InTrustedSpace()) {
    flags |= MemoryChunk::IS_TRUSTED;
  }
  // "Trusted" chunks should never be located inside the sandbox as they
  // couldn't be trusted in that case.
  DCHECK_IMPLIES(flags & MemoryChunk::IS_TRUSTED,
                 !InsideSandbox(ChunkAddress()));
  return flags;
}
References v8::internal::MemoryChunkMetadata::ChunkAddress(), DCHECK_IMPLIES, v8::internal::EXECUTABLE, v8::internal::flags, v8::internal::MemoryChunkMetadata::heap(), v8::internal::MemoryChunk::IN_WRITABLE_SHARED_SPACE, v8::internal::MemoryChunkMetadata::InSharedSpace(), v8::internal::InsideSandbox(), v8::internal::MemoryChunkMetadata::InTrustedSpace(), v8::internal::MemoryChunk::IS_EXECUTABLE, v8::internal::MemoryChunk::IS_TRUSTED, v8::internal::NEW_LO_SPACE, v8::internal::NEW_SPACE, v8::internal::MemoryChunk::NO_FLAGS, v8::internal::MemoryChunk::OldGenerationPageFlags(), owner(), and v8::internal::MemoryChunk::YoungGenerationPageFlags().
Referenced by v8::internal::MemoryAllocator::AllocatePage(), and v8::internal::LargePageMetadata::InitialFlags().
IsLargePage()
bool v8::internal::MutablePageMetadata::IsLargePage () [inline]
Definition at line 277 of file mutable-page-metadata.h.
                     {
    // The active_system_pages_ will be nullptr for large pages, so we uses
    // that here instead of (for example) adding another enum member. See also
    // the constructor where this field is set.
    return active_system_pages_.get() == nullptr;
  }
References active_system_pages_.
Referenced by CommittedPhysicalMemory(), v8::internal::MemoryAllocator::DeleteMemoryChunk(), v8::internal::ScavengerCollector::HandleSurvivingNewLargeObjects(), v8::internal::LargePageMetadata::LargePageMetadata(), MutablePageMetadata(), v8::internal::PageMetadata::PageMetadata(), ReleaseAllocatedMemoryNeededForWritableChunk(), and v8::internal::HeapAllocator::TryResizeLargeObject().
IsLivenessClear()
bool v8::internal::MutablePageMetadata::IsLivenessClear () const
Definition at line 205 of file mutable-page-metadata.cc.
                                                {
  CHECK_IMPLIES(marking_bitmap()->IsClean(), live_bytes() == 0);
  return marking_bitmap()->IsClean();
}
References CHECK_IMPLIES, v8::internal::MarkingBitmap::IsClean(), live_bytes(), and marking_bitmap().
Referenced by v8::internal::MemoryAllocator::AllocatePage(), v8::internal::MemoryAllocator::Free(), and v8::internal::SemiSpace::InitializePage().
list_node() [1/2]
heap::ListNode<MutablePageMetadata>& v8::internal::MutablePageMetadata::list_node () [inline]
Definition at line 210 of file mutable-page-metadata.h.
{ return list_node_; }
References list_node_.
Referenced by v8::internal::SemiSpace::InitializePage(), v8::internal::PagedSpaceForNewSpace::InitializePage(), v8::internal::PagedSpaceBase::InitializePage(), v8::internal::LargePageMetadata::LargePageMetadata(), and v8::internal::MemoryChunkIterator::Next().
list_node() [2/2]
const heap::ListNode<MutablePageMetadata>& v8::internal::MutablePageMetadata::list_node () const [inline]
Definition at line 211 of file mutable-page-metadata.h.
                                                             {
    return list_node_;
  }
References list_node_.
live_bytes()
size_t v8::internal::MutablePageMetadata::live_bytes () const [inline]
Definition at line 256 of file mutable-page-metadata.h.
                            {
    return live_byte_count_.load(std::memory_order_relaxed);
  }
References live_byte_count_.
Referenced by v8::internal::Sweeper::AddNewSpacePage(), v8::internal::Sweeper::AddPromotedPage(), v8::internal::anonymous_namespace{sweeper.cc}::ComparePagesForSweepingOrder(), v8::internal::Evacuator::EvacuatePage(), v8::internal::PagedSpaceForNewSpace::FinishShrinking(), IsLivenessClear(), v8::internal::Sweeper::PrepareToBeSweptPage(), v8::internal::Evacuator::RawEvacuatePage(), v8::internal::PagedSpaceBase::RefineAllocatedBytesAfterSweeping(), v8::internal::OldSpace::RelinkQuarantinedPageFreeList(), v8::internal::PagedSpaceBase::RemovePageFromSpaceImpl(), ResetAllocationStatisticsForPromotedPage(), v8::internal::MarkCompactCollector::ResetAndRelinkBlackAllocatedPage(), v8::internal::MarkCompactCollector::StartSweepNewSpace(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpace(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpaceWithStickyBits(), v8::internal::MarkCompactCollector::StartSweepSpace(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), and v8::internal::anonymous_namespace{sweeper.cc}::VerifyPreparedPage().
marking_bitmap() [1/2]
MarkingBitmap* v8::internal::MutablePageMetadata::marking_bitmap () [inline]
Definition at line 246 of file mutable-page-metadata.h.
                                  {
    DCHECK(!Chunk()->InReadOnlySpace());
    return &marking_bitmap_;
  }
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), and marking_bitmap_.
Referenced by ClearLiveness(), v8::internal::Sweeper::ClearMarkBitsAndHandleLivenessStatistics(), v8::internal::PageMetadata::CreateBlackArea(), v8::internal::PageMetadata::DestroyBlackArea(), v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::FindBasePtr(), v8::internal::MarkingBitmap::FindPreviousValidObject(), v8::internal::Sweeper::FreeAndProcessFreedMemory(), IsLivenessClear(), v8::internal::anonymous_namespace{scavenger.cc}::QuarantinePinnedPages(), v8::internal::anonymous_namespace{mark-compact.cc}::ReRecordPage(), v8::internal::MarkCompactCollector::ResetAndRelinkBlackAllocatedPage(), v8::internal::Heap::RightTrimArray(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), and v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::~YoungGenerationConservativeStackVisitor().
marking_bitmap() [2/2]
const MarkingBitmap* v8::internal::MutablePageMetadata::marking_bitmap () const [inline]
Definition at line 251 of file mutable-page-metadata.h.
                                              {
    DCHECK(!Chunk()->InReadOnlySpace());
    return &marking_bitmap_;
  }
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), and marking_bitmap_.
marking_progress_tracker() [1/2]
MarkingProgressTracker& v8::internal::MutablePageMetadata::marking_progress_tracker () [inline]
Definition at line 185 of file mutable-page-metadata.h.
                                                     {
    return marking_progress_tracker_;
  }
References marking_progress_tracker_.
Referenced by v8::internal::FactoryBase< Impl >::AllocateRawArray(), v8::internal::MarkCompactCollector::SweepLargeSpace(), v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace(), v8::internal::Factory::TryNewFixedArray(), and v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitFixedArray().
marking_progress_tracker() [2/2]
const MarkingProgressTracker& v8::internal::MutablePageMetadata::marking_progress_tracker () const [inline]
Definition at line 188 of file mutable-page-metadata.h.
                                                                 {
    return marking_progress_tracker_;
  }
References marking_progress_tracker_.
MarkingBitmapOffset()
static constexpr intptr_t v8::internal::MutablePageMetadata::MarkingBitmapOffset () [inline], [static], [constexpr], [private]
Definition at line 364 of file mutable-page-metadata.h.
                                                  {
    return offsetof(MutablePageMetadata, marking_bitmap_);
  }
References marking_bitmap_.
Referenced by v8::internal::MarkingBitmap::FromAddress(), and v8::internal::CodeStubAssembler::GetMarkBit().
MoveExternalBackingStoreBytes()
void v8::internal::MutablePageMetadata::MoveExternalBackingStoreBytes (ExternalBackingStoreType type, MutablePageMetadata * from, MutablePageMetadata * to, size_t amount) [inline], [static]
Definition at line 42 of file mutable-page-metadata-inl.h.
                                            {
  DCHECK_NOT_NULL(from->owner());
  DCHECK_NOT_NULL(to->owner());
  base::CheckedDecrement(
      &(from->external_backing_store_bytes_[static_cast<int>(type)]), amount);
  base::CheckedIncrement(
      &(to->external_backing_store_bytes_[static_cast<int>(type)]), amount);
  Space::MoveExternalBackingStoreBytes(type, from->owner(), to->owner(),
                                       amount);
}
References v8::base::CheckedIncrement(), DCHECK_NOT_NULL, external_backing_store_bytes_, v8::internal::Space::MoveExternalBackingStoreBytes(), owner(), and v8::internal::tracing::type.
Referenced by v8::internal::Heap::UpdateYoungReferenceInExternalStringTableEntry().
mutex() [1/2]
base::Mutex& v8::internal::MutablePageMetadata::mutex () [inline]
Definition at line 102 of file mutable-page-metadata.h.
{ return mutex_; }
References mutex_.
Referenced by v8::internal::Scavenger::CheckOldToNewSlotForSharedTyped(), v8::internal::WriteBarrier::GenerationalBarrierForCodeSlow(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), v8::internal::Sweeper::LocalSweeper::ParallelSweepPage(), v8::internal::MarkingBarrier::PublishIfNeeded(), v8::internal::MarkCompactCollector::RecordRelocSlot(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), and v8::internal::WriteBarrier::SharedSlow().
mutex() [2/2]
const base::Mutex& v8::internal::MutablePageMetadata::mutex () const [inline]
Definition at line 103 of file mutable-page-metadata.h.
{ return mutex_; }
References mutex_.
object_mutex() [1/2]
base::Mutex& v8::internal::MutablePageMetadata::object_mutex () [inline]
Definition at line 104 of file mutable-page-metadata.h.
{ return object_mutex_; }
References object_mutex_.
Referenced by v8::internal::ObjectLock::Lock(), and v8::internal::ObjectLock::Unlock().
object_mutex() [2/2]
const base::Mutex& v8::internal::MutablePageMetadata::object_mutex () const [inline]
Definition at line 105 of file mutable-page-metadata.h.
{ return object_mutex_; }
References object_mutex_.
owner()
Space* v8::internal::MutablePageMetadata::owner () const [inline]
Definition at line 202 of file mutable-page-metadata.h.
                       {
    return reinterpret_cast<Space*>(MemoryChunkMetadata::owner());
  }
References v8::internal::MemoryChunkMetadata::owner().
Referenced by v8::internal::PageMetadata::AllocateFreeListCategories(), ComputeFreeListsLength(), v8::internal::PagedSpaceBase::Contains(), v8::internal::PageMetadata::CreateBlackArea(), DecrementExternalBackingStoreBytes(), v8::internal::PageMetadata::DestroyBlackArea(), v8::internal::PageMetadata::ForAllFreeListCategories(), IncrementExternalBackingStoreBytes(), InitialFlags(), v8::internal::PageMetadata::InitializeFreeListCategories(), v8::internal::PagedSpaceForNewSpace::IsPromotionCandidate(), v8::internal::PageMetadata::MarkEvacuationCandidate(), v8::internal::PageMetadata::MarkNeverAllocateForTesting(), MoveExternalBackingStoreBytes(), v8::internal::SemiSpace::MovePageToTheEnd(), v8::internal::SemiSpace::MoveQuarantinedPage(), v8::internal::Heap::NotifyOldGenerationExpansion(), owner_identity(), v8::internal::Sweeper::PrepareToBeIteratedPromotedPage(), v8::internal::HeapLayoutTracer::PrintHeapLayout(), v8::internal::OldLargeObjectSpace::PromoteNewLargeObject(), v8::internal::Sweeper::RawSweep(), v8::internal::CompactionSpace::RefillFreeList(), v8::internal::PageMetadata::ReleaseFreeListCategories(), v8::internal::PagedSpaceBase::RelinkFreeListCategories(), v8::internal::OldSpace::RelinkQuarantinedPageFreeList(), v8::internal::PagedSpaceBase::RemovePageFromSpaceImpl(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), v8::internal::SemiSpaceNewSpace::SetAgeMarkAndBelowAgeMarkPageFlags(), v8::internal::HeapAllocator::TryResizeLargeObject(), v8::internal::PagedSpaceBase::UnlinkFreeListCategories(), and v8::internal::anonymous_namespace{sweeper.cc}::VerifyPreparedPage().
owner_identity()
AllocationSpace v8::internal::MutablePageMetadata::owner_identity () const [inline]
Definition at line 55 of file mutable-page-metadata-inl.h.
                                                          {
  {
    AllowSandboxAccess temporary_sandbox_access;
    DCHECK_EQ(owner() == nullptr, Chunk()->InReadOnlySpace());
  }
  if (!owner()) return RO_SPACE;
  return owner()->identity();
}
References v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_EQ, v8::internal::BaseSpace::identity(), owner(), and v8::internal::RO_SPACE.
Referenced by v8::internal::Sweeper::AddNewSpacePage(), v8::internal::Sweeper::AddPromotedPage(), v8::internal::NewLargeObjectSpace::AllocateRaw(), v8::internal::Heap::AllowedToBeMigrated(), v8::internal::Heap::ClearRecordedSlotRange(), v8::internal::YoungGenerationRememberedSetsMarkingWorklist::CollectItems(), v8::internal::PageMetadata::CreateBlackArea(), v8::internal::PageMetadata::DestroyBlackArea(), v8::internal::Sweeper::EnsurePageIsSwept(), v8::internal::anonymous_namespace{serializer.cc}::GetSnapshotSpace(), v8::internal::ScavengerCollector::HandleSurvivingNewLargeObjects(), v8::internal::PagedSpaceForNewSpace::InitializePage(), v8::internal::PagedSpaceBase::InitializePage(), v8::internal::PageMetadata::MarkNeverAllocateForTesting(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), v8::internal::Sweeper::PrepareToBeIteratedPromotedPage(), v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::PromotedPageRecordMigratedSlotVisitor(), v8::internal::OldLargeObjectSpace::PromoteNewLargeObject(), v8::internal::MemoryAllocator::ResizeLargePage(), SetOldGenerationPageFlags(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), v8::internal::Heap::AllocationTrackerForDebugging::UpdateAllocationsHash(), and v8::internal::Sweeper::ZeroOrDiscardUnusedMemory().
possibly_empty_buckets()
PossiblyEmptyBuckets* v8::internal::MutablePageMetadata::possibly_empty_buckets () [inline]
Definition at line 215 of file mutable-page-metadata.h.
                                                 {
    return &possibly_empty_buckets_;
  }
References possibly_empty_buckets_.
Referenced by v8::internal::RememberedSet< type >::CheckPossiblyEmptyBuckets(), and v8::internal::RememberedSet< type >::IterateAndTrackEmptyBuckets().
ReleaseAllAllocatedMemory()
void v8::internal::MutablePageMetadata::ReleaseAllAllocatedMemory () [protected]
Definition at line 140 of file mutable-page-metadata.cc.
                                                    {
  ReleaseAllocatedMemoryNeededForWritableChunk();
}
References ReleaseAllocatedMemoryNeededForWritableChunk().
Referenced by v8::internal::MemoryAllocator::Free().
ReleaseAllocatedMemoryNeededForWritableChunk()
void v8::internal::MutablePageMetadata::ReleaseAllocatedMemoryNeededForWritableChunk ()
Definition at line 116 of file mutable-page-metadata.cc.
                                                                       {
  DCHECK(SweepingDone());
  active_system_pages_.reset();
  possibly_empty_buckets_.Release();
  ReleaseSlotSet(OLD_TO_NEW);
  ReleaseSlotSet(OLD_TO_NEW_BACKGROUND);
  ReleaseSlotSet(OLD_TO_OLD);
  ReleaseSlotSet(TRUSTED_TO_CODE);
  ReleaseSlotSet(OLD_TO_SHARED);
  ReleaseSlotSet(TRUSTED_TO_TRUSTED);
  ReleaseSlotSet(TRUSTED_TO_SHARED_TRUSTED);
  ReleaseSlotSet(SURVIVOR_TO_EXTERNAL_POINTER);
  ReleaseTypedSlotSet(OLD_TO_NEW);
  ReleaseTypedSlotSet(OLD_TO_OLD);
  ReleaseTypedSlotSet(OLD_TO_SHARED);
  if (!Chunk()->IsLargePage()) {
    PageMetadata* page = static_cast<PageMetadata*>(this);
    page->ReleaseFreeListCategories();
  }
}
References active_system_pages_, v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), IsLargePage(), v8::internal::OLD_TO_NEW, v8::internal::OLD_TO_NEW_BACKGROUND, v8::internal::OLD_TO_OLD, v8::internal::OLD_TO_SHARED, possibly_empty_buckets_, v8::internal::PossiblyEmptyBuckets::Release(), v8::internal::PageMetadata::ReleaseFreeListCategories(), ReleaseSlotSet(), ReleaseTypedSlotSet(), v8::internal::SURVIVOR_TO_EXTERNAL_POINTER, SweepingDone(), v8::internal::TRUSTED_TO_CODE, v8::internal::TRUSTED_TO_SHARED_TRUSTED, and v8::internal::TRUSTED_TO_TRUSTED.
Referenced by ReleaseAllAllocatedMemory().
ReleaseSlotSet()
void v8::internal::MutablePageMetadata::ReleaseSlotSet (RememberedSetType type)
Definition at line 156 of file mutable-page-metadata.cc.
                                                               {
  SlotSet* slot_set = slot_set_[type];
  if (slot_set) {
    slot_set_[type] = nullptr;
    SlotSet::Delete(slot_set);
  }
}
References heap::base::BasicSlotSet< kTaggedSize >::Delete(), slot_set(), slot_set_, and v8::internal::tracing::type.
Referenced by v8::internal::RememberedSet< type >::CheckPossiblyEmptyBuckets(), v8::internal::RememberedSet< type >::ClearAll(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), v8::internal::Sweeper::RawSweep(), ReleaseAllocatedMemoryNeededForWritableChunk(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), and v8::internal::MarkCompactCollector::UpdatePointersInClientHeap().
ReleaseTypedSlotSet()
void v8::internal::MutablePageMetadata::ReleaseTypedSlotSet (RememberedSetType type)
Definition at line 177 of file mutable-page-metadata.cc.
                                                                    {
  TypedSlotSet* typed_slot_set = typed_slot_set_[type];
  if (typed_slot_set) {
    typed_slot_set_[type] = nullptr;
    delete typed_slot_set;
  }
}
References v8::internal::tracing::type, typed_slot_set(), and typed_slot_set_.
Referenced by v8::internal::RememberedSet< type >::ClearAll(), ReleaseAllocatedMemoryNeededForWritableChunk(), v8::internal::Scavenger::ScavengePage(), and v8::internal::MarkCompactCollector::UpdatePointersInClientHeap().
ResetAgeInNewSpace()
void v8::internal::MutablePageMetadata::ResetAgeInNewSpace () [inline]
Definition at line 231 of file mutable-page-metadata.h.
{ age_in_new_space_ = 0; }
References age_in_new_space_.
Referenced by v8::internal::PageMetadata::ConvertNewToOld(), and v8::internal::Sweeper::SweepEmptyNewSpacePage().
ResetAllocationStatistics()
void v8::internal::MutablePageMetadata::ResetAllocationStatistics () [inline]
Definition at line 234 of file mutable-page-metadata.h.
                                   {
    MemoryChunkMetadata::ResetAllocationStatistics();
    allocated_lab_size_ = 0;
  }
References allocated_lab_size_, and v8::internal::MemoryChunkMetadata::ResetAllocationStatistics().
Referenced by v8::internal::PagedSpaceForNewSpace::InitializePage(), v8::internal::PagedSpaceBase::InitializePage(), v8::internal::Sweeper::PrepareToBeSweptPage(), and v8::internal::Sweeper::SweepEmptyNewSpacePage().
ResetAllocationStatisticsForPromotedPage()
void v8::internal::MutablePageMetadata::ResetAllocationStatisticsForPromotedPage () [inline]
Definition at line 239 of file mutable-page-metadata.h.
                                                  {
    DCHECK_NE(0, live_bytes());
    allocated_bytes_ = live_bytes();
    wasted_memory_ = area_size() - allocated_bytes_;
    allocated_lab_size_ = 0;
  }
References v8::internal::MemoryChunkMetadata::allocated_bytes_, allocated_lab_size_, v8::internal::MemoryChunkMetadata::area_size(), DCHECK_NE, live_bytes(), and v8::internal::MemoryChunkMetadata::wasted_memory_.
Referenced by v8::internal::Sweeper::PrepareToBeIteratedPromotedPage().
set_concurrent_sweeping_state()
void v8::internal::MutablePageMetadata::set_concurrent_sweeping_state (ConcurrentSweepingState state) [inline]
Definition at line 107 of file mutable-page-metadata.h.
                                                                    {
    concurrent_sweeping_ = state;
  }
References concurrent_sweeping_.
Referenced by v8::internal::Sweeper::AddPromotedPage(), v8::internal::Sweeper::AddSweptPage(), v8::internal::Sweeper::NotifyPromotedPageIterationFinished(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), v8::internal::Sweeper::LocalSweeper::ParallelSweepPage(), v8::internal::Sweeper::PrepareToBeIteratedPromotedPage(), and v8::internal::Sweeper::PrepareToBeSweptPage().
set_slot_set()
template<RememberedSetType type, AccessMode access_mode = AccessMode::ATOMIC>
void v8::internal::MutablePageMetadata::set_slot_set (SlotSet * slot_set) [inline], [protected]
Definition at line 290 of file mutable-page-metadata.h.
                                       {
    if (access_mode == AccessMode::ATOMIC) {
      base::AsAtomicPointer::Release_Store(&slot_set_[type], slot_set);
      return;
    }
    slot_set_[type] = slot_set;
  }
References v8::internal::ATOMIC, v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store(), slot_set(), slot_set_, and v8::internal::tracing::type.
Referenced by v8::internal::RememberedSet< type >::MergeAndDelete().
set_typed_slot_set()
template<RememberedSetType type, AccessMode access_mode = AccessMode::ATOMIC>
void v8::internal::MutablePageMetadata::set_typed_slot_set (TypedSlotSet * typed_slot_set) [inline], [protected]
Definition at line 299 of file mutable-page-metadata.h.
                                                        {
    if (access_mode == AccessMode::ATOMIC) {
      base::AsAtomicPointer::Release_Store(&typed_slot_set_[type],
                                           typed_slot_set);
      return;
    }
    typed_slot_set_[type] = typed_slot_set;
  }
References v8::internal::ATOMIC, v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store(), v8::internal::tracing::type, typed_slot_set(), and typed_slot_set_.
Referenced by v8::internal::RememberedSet< type >::MergeAndDeleteTyped().
SetLiveBytes()
void v8::internal::MutablePageMetadata::SetLiveBytes (size_t value) [inline]
Definition at line 260 of file mutable-page-metadata.h.
                                  {
    DCHECK_IMPLIES(V8_COMPRESS_POINTERS_8GB_BOOL,
                   ::IsAligned(value, kObjectAlignment8GbHeap));
    live_byte_count_.store(value, std::memory_order_relaxed);
  }
References DCHECK_IMPLIES, IsAligned(), v8::internal::kObjectAlignment8GbHeap, live_byte_count_, V8_COMPRESS_POINTERS_8GB_BOOL, and v8::internal::value.
Referenced by ClearLiveness(), v8::internal::PagedSpaceBase::RefineAllocatedBytesAfterSweeping(), v8::internal::anonymous_namespace{mark-compact.cc}::ReRecordPage(), and v8::internal::MarkCompactCollector::SweepLargeSpace().
SetOldGenerationPageFlags()
void v8::internal::MutablePageMetadata::SetOldGenerationPageFlags (MarkingMode marking_mode) [inline]
Definition at line 64 of file mutable-page-metadata-inl.h.
                                                                            {
  return Chunk()->SetOldGenerationPageFlags(marking_mode, owner_identity());
}
References v8::internal::MemoryChunkMetadata::Chunk(), owner_identity(), and v8::internal::MemoryChunk::SetOldGenerationPageFlags().
SetYoungGenerationPageFlags()
void v8::internal::MutablePageMetadata::SetYoungGenerationPageFlags (MarkingMode marking_mode) [inline]
Definition at line 98 of file mutable-page-metadata.h.
                                                             {
    return Chunk()->SetYoungGenerationPageFlags(marking_mode);
  }
References v8::internal::MemoryChunkMetadata::Chunk(), and v8::internal::MemoryChunk::SetYoungGenerationPageFlags().
slot_set() [1/2]
template<RememberedSetType type, AccessMode access_mode = AccessMode::ATOMIC>
SlotSet* v8::internal::MutablePageMetadata::slot_set () [inline]
Definition at line 120 of file mutable-page-metadata.h.
                      {
    if constexpr (access_mode == AccessMode::ATOMIC)
      return base::AsAtomicPointer::Acquire_Load(&slot_set_[type]);
    return slot_set_[type];
  }
References v8::base::AsAtomicImpl< TAtomicStorageType >::Acquire_Load(), v8::internal::ATOMIC, slot_set_, and v8::internal::tracing::type.
Referenced by v8::internal::RememberedSet< type >::CheckNoneInRange(), v8::internal::RememberedSet< type >::CheckPossiblyEmptyBuckets(), v8::internal::Sweeper::CleanupRememberedSetEntriesForFreedMemory(), v8::internal::ScavengerCollector::CollectGarbage(), v8::internal::RememberedSet< type >::Contains(), v8::internal::MinorMarkSweepCollector::EvacuateExternalPointerReferences(), ExtractSlotSet(), v8::internal::RememberedSet< type >::Insert(), v8::internal::RememberedSet< type >::Iterate(), v8::internal::RememberedSet< type >::IterateAndTrackEmptyBuckets(), v8::internal::RememberedSet< type >::IterateMemoryChunks(), v8::internal::RememberedSet< type >::MergeAndDelete(), ReleaseSlotSet(), v8::internal::RememberedSet< type >::Remove(), v8::internal::RememberedSet< type >::RemoveRange(), v8::internal::Scavenger::ScavengePage(), and set_slot_set().
slot_set() [2/2]
template<RememberedSetType type, AccessMode access_mode = AccessMode::ATOMIC>
const SlotSet* v8::internal::MutablePageMetadata::slot_set () const [inline]
Definition at line 127 of file mutable-page-metadata.h.
                                  {
    return const_cast<MutablePageMetadata*>(this)
        ->slot_set<type, access_mode>();
  }
SlotSetOffset()
static constexpr intptr_t v8::internal::MutablePageMetadata::SlotSetOffset (RememberedSetType remembered_set_type) [inline], [static], [constexpr], [private]
Definition at line 368 of file mutable-page-metadata.h.
                                             {
    return offsetof(MutablePageMetadata, slot_set_) +
           sizeof(void*) * remembered_set_type;
  }
References slot_set_.
Referenced by v8::internal::WriteBarrierCodeStubAssembler::LoadSlotSet().
SweepingDone()
bool v8::internal::MutablePageMetadata::SweepingDone () const [inline]
Definition at line 115 of file mutable-page-metadata.h.
                            {
    return concurrent_sweeping_ == ConcurrentSweepingState::kDone;
  }
References concurrent_sweeping_, and kDone.
Referenced by v8::internal::Sweeper::AddPageImpl(), v8::internal::PagedSpaceBase::AddPageImpl(), v8::internal::Heap::ClearRecordedSlotRange(), v8::internal::Sweeper::EnsurePageIsSwept(), v8::internal::Heap::EnsureSweepingCompletedForObject(), v8::internal::Evacuator::EvacuatePage(), v8::internal::PretenuringHandler::FindAllocationMemento(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), v8::internal::Sweeper::LocalSweeper::ParallelSweepPage(), v8::internal::Sweeper::RawSweep(), v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlot(), v8::internal::PagedSpaceBase::RefineAllocatedBytesAfterSweeping(), ReleaseAllocatedMemoryNeededForWritableChunk(), v8::internal::OldSpace::RelinkQuarantinedPageFreeList(), v8::internal::PagedSpaceBase::RemovePage(), v8::internal::PagedSpaceBase::RemovePageFromSpaceImpl(), v8::internal::MarkCompactCollector::StartSweepNewSpace(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpace(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpaceWithStickyBits(), v8::internal::MarkCompactCollector::StartSweepSpace(), and v8::internal::Sweeper::WaitForPageToBeSwept().
typed_slot_set() [1/2]
template<RememberedSetType type, AccessMode access_mode = AccessMode::ATOMIC>
TypedSlotSet* v8::internal::MutablePageMetadata::typed_slot_set () [inline]
Definition at line 133 of file mutable-page-metadata.h.
                                 {
    if constexpr (access_mode == AccessMode::ATOMIC)
      return base::AsAtomicPointer::Acquire_Load(&typed_slot_set_[type]);
    return typed_slot_set_[type];
  }
References v8::base::AsAtomicImpl< TAtomicStorageType >::Acquire_Load(), v8::internal::ATOMIC, v8::internal::tracing::type, and typed_slot_set_.
Referenced by AllocateTypedSlotSet(), v8::internal::PageMetadata::AssertNoTypedSlotsInFreeMemory(), v8::internal::Sweeper::CleanupTypedSlotsInFreeMemory(), v8::internal::PageMetadata::ClearTypedSlotsInFreeMemory(), v8::internal::ScavengerCollector::CollectGarbage(), ExtractTypedSlotSet(), v8::internal::RememberedSet< type >::InsertTyped(), v8::internal::RememberedSet< type >::IterateMemoryChunks(), v8::internal::RememberedSet< type >::IterateTyped(), v8::internal::RememberedSet< type >::MergeAndDeleteTyped(), v8::internal::RememberedSet< type >::MergeTyped(), v8::internal::Sweeper::RawSweep(), ReleaseTypedSlotSet(), v8::internal::RememberedSet< type >::RemoveRangeTyped(), v8::internal::anonymous_namespace{mark-compact.cc}::ReRecordPage(), v8::internal::Scavenger::ScavengePage(), set_typed_slot_set(), and v8::internal::MarkCompactCollector::UpdatePointersInClientHeap().
typed_slot_set() [2/2]
template<RememberedSetType type, AccessMode access_mode = AccessMode::ATOMIC>
const TypedSlotSet* v8::internal::MutablePageMetadata::typed_slot_set () const [inline]
Definition at line 140 of file mutable-page-metadata.h.
                                             {
    return const_cast<MutablePageMetadata*>(this)
        ->typed_slot_set<type, access_mode>();
  }
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 381 of file mutable-page-metadata.h.
MacroAssembler
friend class MacroAssembler [friend]
Definition at line 382 of file mutable-page-metadata.h.
MarkingBitmap
friend class MarkingBitmap [friend]
Definition at line 383 of file mutable-page-metadata.h.
MemoryAllocator
friend class MemoryAllocator [friend]
Definition at line 375 of file mutable-page-metadata.h.
PagePool
friend class PagePool [friend]
Definition at line 376 of file mutable-page-metadata.h.
RememberedSet
template<RememberedSetType >
friend class RememberedSet [friend]
Definition at line 379 of file mutable-page-metadata.h.
TestWithBitmap
friend class TestWithBitmap [friend]
Definition at line 384 of file mutable-page-metadata.h.
WriteBarrierCodeStubAssembler
friend class WriteBarrierCodeStubAssembler [friend]
Definition at line 386 of file mutable-page-metadata.h.
Member Data Documentation
active_system_pages_
std::unique_ptr<ActiveSystemPages> v8::internal::MutablePageMetadata::active_system_pages_ [protected]
Definition at line 343 of file mutable-page-metadata.h.
Referenced by v8::internal::PageMetadata::active_system_pages(), CommittedPhysicalMemory(), IsLargePage(), MutablePageMetadata(), and ReleaseAllocatedMemoryNeededForWritableChunk().
age_in_new_space_
size_t v8::internal::MutablePageMetadata::age_in_new_space_ = 0 [protected]
Definition at line 351 of file mutable-page-metadata.h.
Referenced by AgeInNewSpace(), IncrementAgeInNewSpace(), and ResetAgeInNewSpace().
allocated_lab_size_
size_t v8::internal::MutablePageMetadata::allocated_lab_size_ = 0 [protected]
Definition at line 347 of file mutable-page-metadata.h.
Referenced by AllocatedLabSize(), DecreaseAllocatedLabSize(), IncreaseAllocatedLabSize(), ResetAllocationStatistics(), and ResetAllocationStatisticsForPromotedPage().
categories_
FreeListCategory** v8::internal::MutablePageMetadata::categories_ = nullptr [protected]
Definition at line 338 of file mutable-page-metadata.h.
Referenced by v8::internal::PageMetadata::AllocateFreeListCategories(), ComputeFreeListsLength(), v8::internal::PageMetadata::ForAllFreeListCategories(), v8::internal::PageMetadata::free_list_category(), v8::internal::PageMetadata::InitializeFreeListCategories(), and v8::internal::PageMetadata::ReleaseFreeListCategories().
concurrent_sweeping_
std::atomic<ConcurrentSweepingState> v8::internal::MutablePageMetadata::concurrent_sweeping_ [protected]
Initial value:
{
      ConcurrentSweepingState::kDone}
Definition at line 329 of file mutable-page-metadata.h.
Referenced by concurrent_sweeping_state(), set_concurrent_sweeping_state(), and SweepingDone().
external_backing_store_bytes_
std::atomic<size_t> v8::internal::MutablePageMetadata::external_backing_store_bytes_[static_cast< int >(ExternalBackingStoreType::kNumValues)] = {0} [protected]
Definition at line 333 of file mutable-page-metadata.h.
Referenced by DecrementExternalBackingStoreBytes(), ExternalBackingStoreBytes(), IncrementExternalBackingStoreBytes(), and MoveExternalBackingStoreBytes().
kPageSize
const int v8::internal::MutablePageMetadata::kPageSize = kRegularPageSize [static]
Definition at line 62 of file mutable-page-metadata.h.
Referenced by v8::internal::Heap::ActivateMemoryReducerIfNeededOnMainThread(), v8::internal::PagePool::Add(), v8::internal::PagedSpaceForNewSpace::AddPage(), v8::internal::SemiSpace::AddRangeToActiveSystemPages(), v8::internal::PagedSpaceBase::AddRangeToActiveSystemPages(), v8::internal::SemiSpace::AdvancePage(), v8::internal::SemiSpace::AllocateFreshPage(), v8::internal::MemoryAllocator::AllocateUninitializedPageFromPool(), v8::internal::Heap::CanPromoteYoungAndExpandOldGeneration(), v8::internal::SemiSpaceNewSpace::Capacity(), v8::internal::anonymous_namespace{heap.cc}::ComputeReducedNewSpaceSize(), v8::internal::SemiSpaceNewSpace::CurrentCapacitySafe(), v8::internal::Heap::DefaultMaxSemiSpaceSize(), v8::internal::Heap::DefaultMinSemiSpaceSize(), v8::internal::SemiSpaceNewSpaceAllocatorPolicy::EnsureAllocation(), v8::internal::Heap::ExpandNewSpaceSize(), v8::internal::anonymous_namespace{heap-write-barrier.cc}::ForRangeImpl(), v8::internal::MemoryAllocator::Free(), v8::internal::Heap::Heap(), v8::internal::Heap::HeapSizeFromPhysicalMemory(), v8::internal::CodeRange::InitReservation(), v8::internal::SemiSpaceNewSpace::IsAddressBelowAgeMark(), v8::internal::anonymous_namespace{main-allocator.cc}::IsPagedNewSpaceAtFullCapacity(), v8::internal::PagedSpaceForNewSpace::IsPromotionCandidate(), v8::internal::MemoryController< Trait >::MinimumAllocationLimitGrowingStep(), v8::internal::Heap::MinOldGenerationSize(), v8::internal::SemiSpace::MoveQuarantinedPage(), v8::internal::anonymous_namespace{mark-compact.cc}::NumberOfParallelCompactionTasks(), v8::internal::ScavengerCollector::NumberOfScavengeTasks(), v8::internal::PagedSpaceForNewSpace::PagedSpaceForNewSpace(), v8::internal::GCTracer::Print(), v8::internal::Heap::PrintShortHeapStatistics(), v8::internal::Sweeper::RawSweep(), v8::internal::Heap::RememberUnmappedPage(), v8::internal::SemiSpace::RemovePage(), v8::internal::PagedSpaceForNewSpace::RemovePage(), v8::internal::PagedSpaceForNewSpace::RemovePageFromSpace(), v8::internal::SemiSpace::RewindPages(), v8::internal::StressConcurrentAllocationTask::RunInternal(), v8::internal::SemiSpaceNewSpace::SemiSpaceNewSpace(), v8::internal::SemiSpace::ShrinkCapacityTo(), v8::internal::SemiSpaceNewSpace::Size(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), v8::internal::PagedNewSpaceAllocatorPolicy::TryAllocatePage(), v8::internal::SemiSpace::Uncommit(), and v8::internal::Heap::YoungGenerationSizeFromOldGenerationSize().
list_node_
heap::ListNode<MutablePageMetadata> v8::internal::MutablePageMetadata::list_node_ [protected]
Definition at line 336 of file mutable-page-metadata.h.
Referenced by list_node(), v8::internal::LargePageMetadata::next_page(), v8::internal::PageMetadata::next_page(), and v8::internal::PageMetadata::prev_page().
live_byte_count_
std::atomic<intptr_t> v8::internal::MutablePageMetadata::live_byte_count_ {0} [protected]
Definition at line 327 of file mutable-page-metadata.h.
Referenced by IncrementLiveBytesAtomically(), live_bytes(), and SetLiveBytes().
marking_bitmap_
MarkingBitmap v8::internal::MutablePageMetadata::marking_bitmap_ [protected]
Definition at line 353 of file mutable-page-metadata.h.
Referenced by marking_bitmap(), and MarkingBitmapOffset().
marking_progress_tracker_
MarkingProgressTracker v8::internal::MutablePageMetadata::marking_progress_tracker_ [protected]
Definition at line 320 of file mutable-page-metadata.h.
Referenced by marking_progress_tracker().
mutex_
base::Mutex v8::internal::MutablePageMetadata::mutex_ [protected]
Definition at line 360 of file mutable-page-metadata.h.
Referenced by mutex().
object_mutex_
base::Mutex v8::internal::MutablePageMetadata::object_mutex_ [protected]
Definition at line 361 of file mutable-page-metadata.h.
Referenced by object_mutex().
possibly_empty_buckets_
PossiblyEmptyBuckets v8::internal::MutablePageMetadata::possibly_empty_buckets_ [protected]
Definition at line 340 of file mutable-page-metadata.h.
Referenced by possibly_empty_buckets(), and ReleaseAllocatedMemoryNeededForWritableChunk().
slot_set_
SlotSet* v8::internal::MutablePageMetadata::slot_set_[NUMBER_OF_REMEMBERED_SET_TYPES] = {nullptr} [protected]
Definition at line 311 of file mutable-page-metadata.h.
Referenced by AllocateSlotSet(), ContainsAnySlots(), ExtractSlotSet(), MutablePageMetadata(), ReleaseSlotSet(), set_slot_set(), slot_set(), and SlotSetOffset().
typed_slot_set_
TypedSlotSet* v8::internal::MutablePageMetadata::typed_slot_set_[NUMBER_OF_REMEMBERED_SET_TYPES] = {nullptr} [protected]
Definition at line 315 of file mutable-page-metadata.h.
Referenced by AllocateTypedSlotSet(), ContainsAnySlots(), ExtractTypedSlotSet(), ReleaseTypedSlotSet(), set_typed_slot_set(), and typed_slot_set().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/mutable-page-metadata.h
/mnt/V8SourceCode/src/heap/mutable-page-metadata-inl.h
/mnt/V8SourceCode/src/heap/mutable-page-metadata.cc