v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key > Class Template Reference
#include <sidetable.h>
Public Member Functions
T & operator[] (Key index)
const T & operator[] (Key index) const
void Reset ()
bool empty () const
Protected Member Functions
GrowingSidetable (Zone *zone)
GrowingSidetable (size_t size, const T &initial_value, Zone *zone)
size_t NextSize (size_t out_of_bounds_index) const
Protected Attributes
ZoneVector< T > table_
Detailed Description
template<class T, class Key>
class v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >
Definition at line 27 of file sidetable.h.
Constructor & Destructor Documentation
GrowingSidetable() [1/2]
template<class T , class Key >
v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::GrowingSidetable (Zone * zone) [inline], [explicit], [protected]
Definition at line 67 of file sidetable.h.
: table_(zone) {}
GrowingSidetable() [2/2]
template<class T , class Key >
v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::GrowingSidetable (size_t size, const T & initial_value, Zone * zone) [inline], [protected]
Definition at line 68 of file sidetable.h.
      : table_(size, initial_value, zone) {}
Member Function Documentation
empty()
template<class T , class Key >
bool v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::empty () const [inline]
Definition at line 62 of file sidetable.h.
{ return table_.empty(); }
References v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::table_.
NextSize()
template<class T , class Key >
size_t v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::NextSize (size_t out_of_bounds_index) const [inline], [protected]
Definition at line 73 of file sidetable.h.
                                                    {
    DCHECK_GE(out_of_bounds_index, table_.size());
    return out_of_bounds_index + out_of_bounds_index / 2 + 32;
  }
References DCHECK_GE, and v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::table_.
Referenced by v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::operator[]().
operator[]() [1/2]
template<class T , class Key >
T& v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::operator[] (Key index) [inline]
Definition at line 32 of file sidetable.h.
                           {
    DCHECK(index.valid());
    size_t i = index.id();
    if (V8_UNLIKELY(i >= table_.size())) {
      table_.resize(NextSize(i));
      // Make sure we also get access to potential over-allocation by
      // `resize()`.
      table_.resize(table_.capacity());
    }
    return table_[i];
  }
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::NextSize(), v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::table_, and V8_UNLIKELY.
operator[]() [2/2]
template<class T , class Key >
const T& v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::operator[] (Key index) const [inline]
Definition at line 44 of file sidetable.h.
                                       {
    DCHECK(index.valid());
    size_t i = index.id();
    if (V8_UNLIKELY(i >= table_.size())) {
      table_.resize(NextSize(i));
      // Make sure we also get access to potential over-allocation by
      // `resize()`.
      table_.resize(table_.capacity());
    }
    return table_[i];
  }
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::NextSize(), v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::table_, and V8_UNLIKELY.
Reset()
template<class T , class Key >
void v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::Reset () [inline]
Definition at line 58 of file sidetable.h.
{ std::fill(table_.begin(), table_.end(), T{}); }
References v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::table_.
Member Data Documentation
table_
template<class T , class Key >
ZoneVector<T> v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::table_ [mutable], [protected]
Definition at line 71 of file sidetable.h.
Referenced by v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::empty(), v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::NextSize(), v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::operator[](), v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::Reset(), and v8::internal::compiler::turboshaft::GrowingOpIndexSidetable< T >::SwapData().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/sidetable.h