v8::internal::wasm::AsmFunctionType Class Reference
#include <asm-types.h>
Public Member Functions
AsmFunctionType (const AsmFunctionType &)=delete
AsmFunctionType & operator= (const AsmFunctionType &)=delete
AsmFunctionType * AsFunctionType () final
void AddArgument (AsmType *type)
const ZoneVector< AsmType * > & Arguments () const
AsmType * ReturnType () const
bool CanBeInvokedWith (AsmType *return_type, const ZoneVector< AsmType * > &args) override
Protected Member Functions
AsmFunctionType (Zone *zone, AsmType *return_type)
Private Member Functions
std::string Name () override
bool IsA (AsmType *other) override
Private Attributes
friend AsmType
friend Zone
AsmType * return_type_
ZoneVector< AsmType * > args_
Detailed Description
Definition at line 125 of file asm-types.h.
Constructor & Destructor Documentation
AsmFunctionType() [1/2]
v8::internal::wasm::AsmFunctionType::AsmFunctionType (const AsmFunctionType &) [delete]
AsmFunctionType() [2/2]
v8::internal::wasm::AsmFunctionType::AsmFunctionType (Zone * zone, AsmType * return_type) [inline], [protected]
Definition at line 140 of file asm-types.h.
      : return_type_(return_type), args_(zone) {}
Member Function Documentation
AddArgument()
void v8::internal::wasm::AsmFunctionType::AddArgument (AsmType * type) [inline]
Definition at line 132 of file asm-types.h.
{ args_.push_back(type); }
References v8::internal::tracing::type.
Arguments()
const ZoneVector<AsmType*>& v8::internal::wasm::AsmFunctionType::Arguments () const [inline]
Definition at line 133 of file asm-types.h.
{ return args_; }
AsFunctionType()
AsmFunctionType* v8::internal::wasm::AsmFunctionType::AsFunctionType () [inline], [final]
Definition at line 130 of file asm-types.h.
{ return this; }
CanBeInvokedWith()
bool v8::internal::wasm::AsmFunctionType::CanBeInvokedWith (AsmType * return_type, const ZoneVector< AsmType * > & args) [override], [virtual]
Implements v8::internal::wasm::AsmCallableType.
Definition at line 258 of file asm-types.cc.
                                                                         {
  if (!AsmType::IsExactly(return_type_, return_type)) {
    return false;
  }
  if (args_.size() != args.size()) {
    return false;
  }
  for (size_t ii = 0; ii < args_.size(); ++ii) {
    if (!args[ii]->IsA(args_[ii])) {
      return false;
    }
  }
  return true;
}
References v8::base::args, args_, IsA(), v8::internal::wasm::AsmType::IsExactly(), and return_type_.
IsA()
bool v8::internal::wasm::AsmFunctionType::IsA (AsmType * other) [override], [private], [virtual]
Reimplemented from v8::internal::wasm::AsmCallableType.
Definition at line 236 of file asm-types.cc.
                                        {
  auto* that = other->AsFunctionType();
  if (that == nullptr) {
    return false;
  }
  if (!AsmType::IsExactly(return_type_, that->return_type_)) {
    return false;
  }
  if (args_.size() != that->args_.size()) {
    return false;
  }
  for (size_t ii = 0; ii < args_.size(); ++ii) {
    if (!AsmType::IsExactly(args_[ii], that->args_[ii])) {
      return false;
    }
  }
  return true;
}
References args_, v8::internal::wasm::AsmType::IsExactly(), and return_type_.
Referenced by CanBeInvokedWith().
Name()
std::string v8::internal::wasm::AsmFunctionType::Name () [override], [private], [virtual]
Implements v8::internal::wasm::AsmCallableType.
Definition at line 143 of file asm-types.cc.
                                {
  std::string ret;
  ret += "(";
  for (size_t ii = 0; ii < args_.size(); ++ii) {
    ret += args_[ii]->Name();
    if (ii != args_.size() - 1) {
      ret += ", ";
    }
  }
  ret += ") -> ";
  ret += return_type_->Name();
  return ret;
}
References args_, v8::internal::wasm::AsmType::Name(), return_type_, and v8::internal::string.
operator=()
AsmFunctionType& v8::internal::wasm::AsmFunctionType::operator= (const AsmFunctionType &) [delete]
ReturnType()
AsmType* v8::internal::wasm::AsmFunctionType::ReturnType () const [inline]
Definition at line 134 of file asm-types.h.
{ return return_type_; }
Member Data Documentation
args_
ZoneVector<AsmType*> v8::internal::wasm::AsmFunctionType::args_ [private]
Definition at line 151 of file asm-types.h.
Referenced by CanBeInvokedWith(), IsA(), and Name().
AsmType
friend v8::internal::wasm::AsmFunctionType::AsmType [private]
Definition at line 144 of file asm-types.h.
return_type_
AsmType* v8::internal::wasm::AsmFunctionType::return_type_ [private]
Definition at line 150 of file asm-types.h.
Referenced by CanBeInvokedWith(), IsA(), and Name().
Zone
friend v8::internal::wasm::AsmFunctionType::Zone [private]
Definition at line 145 of file asm-types.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/asmjs/asm-types.h
/mnt/V8SourceCode/src/asmjs/asm-types.cc