cppgc::internal::WriteBarrier::FlagUpdater Class Reference
#include <write-barrier.h>
Static Public Member Functions
static void Enter ()
static void Exit ()
Private Member Functions
FlagUpdater ()=delete
Detailed Description
Definition at line 15 of file write-barrier.h.
Constructor & Destructor Documentation
FlagUpdater()
cppgc::internal::WriteBarrier::FlagUpdater::FlagUpdater () [private], [delete]
Member Function Documentation
Enter()
static void cppgc::internal::WriteBarrier::FlagUpdater::Enter () [inline], [static]
Definition at line 17 of file write-barrier.h.
{ write_barrier_enabled_.Enter(); }
References cppgc::internal::AtomicEntryFlag::Enter(), and cppgc::internal::WriteBarrier::write_barrier_enabled_.
Referenced by cppgc::internal::anonymous_namespace{marker.cc}::EnterIncrementalMarkingIfNeeded().
Exit()
static void cppgc::internal::WriteBarrier::FlagUpdater::Exit () [inline], [static]
Definition at line 18 of file write-barrier.h.
{ write_barrier_enabled_.Exit(); }
References cppgc::internal::AtomicEntryFlag::Exit(), and cppgc::internal::WriteBarrier::write_barrier_enabled_.
Referenced by cppgc::internal::anonymous_namespace{marker.cc}::ExitIncrementalMarkingIfNeeded().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/write-barrier.h