v8::internal::compiler::IA32OperandConverter Class Reference
Public Member Functions
IA32OperandConverter (CodeGenerator *gen, Instruction *instr)
Operand InputOperand (size_t index, int extra=0)
Immediate InputImmediate (size_t index)
Operand OutputOperand ()
Operand ToOperand (InstructionOperand *op, int extra=0)
Operand SlotToOperand (int slot, int extra=0)
Immediate ToImmediate (InstructionOperand *operand)
Operand MemoryOperand (size_t *offset)
Operand MemoryOperand (size_t first_input=0)
Operand NextMemoryOperand (size_t offset=0)
void MoveInstructionOperandToRegister (Register destination, InstructionOperand *op)
Static Public Member Functions
static size_t NextOffset (size_t *offset)
static ScaleFactor ScaleFor (AddressingMode one, AddressingMode mode)
Additional Inherited Members
Detailed Description
Definition at line 36 of file code-generator-ia32.cc.
Constructor & Destructor Documentation
IA32OperandConverter()
v8::internal::compiler::IA32OperandConverter::IA32OperandConverter (CodeGenerator * gen, Instruction * instr) [inline]
Definition at line 38 of file code-generator-ia32.cc.
      : InstructionOperandConverter(gen, instr) {}
Member Function Documentation
InputImmediate()
Immediate v8::internal::compiler::IA32OperandConverter::InputImmediate (size_t index) [inline]
Definition at line 45 of file code-generator-ia32.cc.
                                         {
    return ToImmediate(instr_->InputAt(index));
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, and ToImmediate().
InputOperand()
Operand v8::internal::compiler::IA32OperandConverter::InputOperand (size_t index, int extra = 0) [inline]
Definition at line 41 of file code-generator-ia32.cc.
                                                    {
    return ToOperand(instr_->InputAt(index), extra);
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, and ToOperand().
MemoryOperand() [1/2]
Operand v8::internal::compiler::IA32OperandConverter::MemoryOperand (size_t * offset) [inline]
Definition at line 108 of file code-generator-ia32.cc.
                                        {
    AddressingMode mode = AddressingModeField::decode(instr_->opcode());
    switch (mode) {
      case kMode_MR: {
        Register base = InputRegister(NextOffset(offset));
        int32_t disp = 0;
        return Operand(base, disp);
      }
      case kMode_MRI: {
        Register base = InputRegister(NextOffset(offset));
        Constant ctant = ToConstant(instr_->InputAt(NextOffset(offset)));
        return Operand(base, ctant.ToInt32(), ctant.rmode());
      }
      case kMode_MR1:
      case kMode_MR2:
      case kMode_MR4:
      case kMode_MR8: {
        Register base = InputRegister(NextOffset(offset));
        Register index = InputRegister(NextOffset(offset));
        ScaleFactor scale = ScaleFor(kMode_MR1, mode);
        int32_t disp = 0;
        return Operand(base, index, scale, disp);
      }
      case kMode_MR1I:
      case kMode_MR2I:
      case kMode_MR4I:
      case kMode_MR8I: {
        Register base = InputRegister(NextOffset(offset));
        Register index = InputRegister(NextOffset(offset));
        ScaleFactor scale = ScaleFor(kMode_MR1I, mode);
        Constant ctant = ToConstant(instr_->InputAt(NextOffset(offset)));
        return Operand(base, index, scale, ctant.ToInt32(), ctant.rmode());
      }
      case kMode_M1:
      case kMode_M2:
      case kMode_M4:
      case kMode_M8: {
        Register index = InputRegister(NextOffset(offset));
        ScaleFactor scale = ScaleFor(kMode_M1, mode);
        int32_t disp = 0;
        return Operand(index, scale, disp);
      }
      case kMode_M1I:
      case kMode_M2I:
      case kMode_M4I:
      case kMode_M8I: {
        Register index = InputRegister(NextOffset(offset));
        ScaleFactor scale = ScaleFor(kMode_M1I, mode);
        Constant ctant = ToConstant(instr_->InputAt(NextOffset(offset)));
        return Operand(index, scale, ctant.ToInt32(), ctant.rmode());
      }
      case kMode_MI: {
        Constant ctant = ToConstant(instr_->InputAt(NextOffset(offset)));
        return Operand(ctant.ToInt32(), ctant.rmode());
      }
      case kMode_Root: {
        Register base = kRootRegister;
        int32_t disp = InputInt32(NextOffset(offset));
        return Operand(base, disp);
      }
      case kMode_None:
        UNREACHABLE();
    }
    UNREACHABLE();
  }
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::InputInt32(), v8::internal::compiler::InstructionOperandConverter::InputRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::kRootRegister, mode(), NextOffset(), v8::internal::compiler::Instruction::opcode(), v8::internal::compiler::Constant::rmode(), ScaleFor(), v8::internal::compiler::InstructionOperandConverter::ToConstant(), v8::internal::compiler::Constant::ToInt32(), and v8::internal::UNREACHABLE().
Referenced by MemoryOperand().
MemoryOperand() [2/2]
Operand v8::internal::compiler::IA32OperandConverter::MemoryOperand (size_t first_input = 0) [inline]
Definition at line 174 of file code-generator-ia32.cc.
                                                {
    return MemoryOperand(&first_input);
  }
References MemoryOperand().
MoveInstructionOperandToRegister()
void v8::internal::compiler::IA32OperandConverter::MoveInstructionOperandToRegister (Register destination, InstructionOperand * op) [inline]
Definition at line 194 of file code-generator-ia32.cc.
                                                                {
    if (op->IsImmediate() || op->IsConstant()) {
      gen_->masm()->mov(destination, ToImmediate(op));
    } else if (op->IsRegister()) {
      gen_->masm()->Move(destination, ToRegister(op));
    } else {
      gen_->masm()->mov(destination, ToOperand(op));
    }
  }
References v8::internal::compiler::InstructionOperandConverter::gen_, v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::CodeGenerator::masm(), v8::internal::MacroAssembler::mov(), v8::internal::MacroAssembler::Move(), ToImmediate(), ToOperand(), and v8::internal::compiler::InstructionOperandConverter::ToRegister().
NextMemoryOperand()
Operand v8::internal::compiler::IA32OperandConverter::NextMemoryOperand (size_t offset = 0) [inline]
Definition at line 178 of file code-generator-ia32.cc.
                                               {
    AddressingMode mode = AddressingModeField::decode(instr_->opcode());
    Register base = InputRegister(NextOffset(&offset));
    const int32_t disp = 4;
    if (mode == kMode_MR1) {
      Register index = InputRegister(NextOffset(&offset));
      ScaleFactor scale = ScaleFor(kMode_MR1, kMode_MR1);
      return Operand(base, index, scale, disp);
    } else if (mode == kMode_MRI) {
      Constant ctant = ToConstant(instr_->InputAt(NextOffset(&offset)));
      return Operand(base, ctant.ToInt32() + disp, ctant.rmode());
    } else {
      UNREACHABLE();
    }
  }
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::InputRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, mode(), NextOffset(), v8::internal::compiler::Instruction::opcode(), v8::internal::compiler::Constant::rmode(), ScaleFor(), v8::internal::compiler::InstructionOperandConverter::ToConstant(), v8::internal::compiler::Constant::ToInt32(), and v8::internal::UNREACHABLE().
NextOffset()
static size_t v8::internal::compiler::IA32OperandConverter::NextOffset (size_t * offset) [inline], [static]
Definition at line 92 of file code-generator-ia32.cc.
                                           {
    size_t i = *offset;
    (*offset)++;
    return i;
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by MemoryOperand(), and NextMemoryOperand().
OutputOperand()
Operand v8::internal::compiler::IA32OperandConverter::OutputOperand () [inline]
Definition at line 49 of file code-generator-ia32.cc.
{ return ToOperand(instr_->Output()); }
References v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::Instruction::Output(), and ToOperand().
ScaleFor()
static ScaleFactor v8::internal::compiler::IA32OperandConverter::ScaleFor (AddressingMode one, AddressingMode mode) [inline], [static]
Definition at line 98 of file code-generator-ia32.cc.
                                                                       {
    static_assert(0 == static_cast<int>(times_1));
    static_assert(1 == static_cast<int>(times_2));
    static_assert(2 == static_cast<int>(times_4));
    static_assert(3 == static_cast<int>(times_8));
    int scale = static_cast<int>(mode - one);
    DCHECK(scale >= 0 && scale < 4);
    return static_cast<ScaleFactor>(scale);
  }
References v8::internal::DCHECK(), mode(), one, v8::internal::times_1, v8::internal::times_2, v8::internal::times_4, and v8::internal::times_8.
Referenced by MemoryOperand(), and NextMemoryOperand().
SlotToOperand()
Operand v8::internal::compiler::IA32OperandConverter::SlotToOperand (int slot, int extra = 0) [inline]
Definition at line 63 of file code-generator-ia32.cc.
                                                 {
    FrameOffset offset = frame_access_state()->GetFrameOffset(slot);
    return Operand(offset.from_stack_pointer() ? esp : ebp,
                   offset.offset() + extra);
  }
References v8::internal::compiler::InstructionOperandConverter::frame_access_state(), v8::internal::compiler::FrameOffset::from_stack_pointer(), v8::internal::compiler::FrameAccessState::GetFrameOffset(), and v8::internal::compiler::FrameOffset::offset().
Referenced by ToOperand().
ToImmediate()
Immediate v8::internal::compiler::IA32OperandConverter::ToImmediate (InstructionOperand * operand) [inline]
Definition at line 69 of file code-generator-ia32.cc.
                                                     {
    Constant constant = ToConstant(operand);
    switch (constant.type()) {
      case Constant::kInt32:
        return Immediate(constant.ToInt32(), constant.rmode());
      case Constant::kFloat32:
        return Immediate::EmbeddedNumber(constant.ToFloat32());
      case Constant::kFloat64:
        return Immediate::EmbeddedNumber(constant.ToFloat64().value());
      case Constant::kExternalReference:
        return Immediate(constant.ToExternalReference());
      case Constant::kHeapObject:
        return Immediate(constant.ToHeapObject());
      case Constant::kCompressedHeapObject:
        break;
      case Constant::kInt64:
        break;
      case Constant::kRpoNumber:
        return Immediate::CodeRelativeOffset(ToLabel(operand));
    }
    UNREACHABLE();
  }
References v8::internal::Immediate::CodeRelativeOffset(), v8::internal::Immediate::EmbeddedNumber(), v8::internal::compiler::Constant::kCompressedHeapObject, v8::internal::compiler::Constant::kExternalReference, v8::internal::compiler::Constant::kFloat32, v8::internal::compiler::Constant::kFloat64, v8::internal::compiler::Constant::kHeapObject, v8::internal::compiler::Constant::kInt32, v8::internal::compiler::Constant::kInt64, v8::internal::compiler::Constant::kRpoNumber, v8::internal::compiler::Constant::rmode(), v8::internal::compiler::InstructionOperandConverter::ToConstant(), v8::internal::compiler::Constant::ToExternalReference(), v8::internal::compiler::Constant::ToFloat32(), v8::internal::compiler::Constant::ToFloat64(), v8::internal::compiler::Constant::ToHeapObject(), v8::internal::compiler::Constant::ToInt32(), v8::internal::compiler::InstructionOperandConverter::ToLabel(), v8::internal::compiler::Constant::type(), v8::internal::UNREACHABLE(), and v8::base::Double::value().
Referenced by InputImmediate(), and MoveInstructionOperandToRegister().
ToOperand()
Operand v8::internal::compiler::IA32OperandConverter::ToOperand (InstructionOperand * op, int extra = 0) [inline]
Definition at line 51 of file code-generator-ia32.cc.
                                                           {
    if (op->IsRegister()) {
      DCHECK_EQ(0, extra);
      return Operand(ToRegister(op));
    } else if (op->IsFPRegister()) {
      DCHECK_EQ(0, extra);
      return Operand(ToDoubleRegister(op));
    }
    DCHECK(op->IsStackSlot() || op->IsFPStackSlot());
    return SlotToOperand(AllocatedOperand::cast(op)->index(), extra);
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::index, v8::internal::compiler::InstructionOperand::IsFPRegister(), v8::internal::compiler::InstructionOperand::IsFPStackSlot(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), SlotToOperand(), v8::internal::compiler::InstructionOperandConverter::ToDoubleRegister(), and v8::internal::compiler::InstructionOperandConverter::ToRegister().
Referenced by InputOperand(), MoveInstructionOperandToRegister(), and OutputOperand().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/ia32/code-generator-ia32.cc