v8::internal::TrustedByteArray Class Reference
#include <fixed-array.h>
Classes
class BodyDescriptor
Public Types
using Shape = TrustedByteArrayShape
Public Member Functions
uint32_t get_int (int offset) const
void set_int (int offset, uint32_t value)
Static Public Member Functions
template<class IsolateT >
static Handle< TrustedByteArray > New (IsolateT *isolate, int capacity, AllocationType allocation_type=AllocationType::kTrusted)
static constexpr int LengthFor (int size_in_bytes)
Private Types
using Super = PrimitiveArrayBase< TrustedByteArray, TrustedByteArrayShape, TrustedObjectLayout >
Additional Inherited Members
Detailed Description
Definition at line 803 of file fixed-array.h.
Member Typedef Documentation
Shape
using v8::internal::TrustedByteArray::Shape = TrustedByteArrayShape
Definition at line 810 of file fixed-array.h.
Super
using v8::internal::TrustedByteArray::Super = PrimitiveArrayBase<TrustedByteArray, TrustedByteArrayShape, TrustedObjectLayout> [private]
Definition at line 806 of file fixed-array.h.
Member Function Documentation
get_int()
uint32_t v8::internal::TrustedByteArray::get_int (int offset) const [inline]
Definition at line 803 of file fixed-array-inl.h.
                                                   {
  DCHECK(IsInBounds(offset));
  DCHECK_LE(offset + sizeof(uint32_t), length());
  return base::ReadUnalignedValue<uint32_t>(
      reinterpret_cast<Address>(&values()[offset]));
}
References v8::internal::DCHECK(), DCHECK_LE, and v8::internal::length.
LengthFor()
static constexpr int v8::internal::TrustedByteArray::LengthFor (int size_in_bytes) [inline], [static], [constexpr]
Definition at line 822 of file fixed-array.h.
                                                    {
    DCHECK(IsAligned(size_in_bytes, kTaggedSize));
    DCHECK_GE(size_in_bytes, sizeof(Header));
    return size_in_bytes - sizeof(Header);
  }
References v8::internal::DCHECK(), DCHECK_GE, IsAligned(), and v8::internal::kTaggedSize.
New()
template<class IsolateT >
Handle< TrustedByteArray > v8::internal::TrustedByteArray::New (IsolateT * isolate, int capacity, AllocationType allocation_type = AllocationType::kTrusted) [inline], [static]
Definition at line 785 of file fixed-array-inl.h.
                                                                               {
  DCHECK(allocation_type == AllocationType::kTrusted ||
         allocation_type == AllocationType::kSharedTrusted);
  if (V8_UNLIKELY(static_cast<unsigned>(length) > kMaxLength)) {
    FATAL("Fatal JavaScript invalid size error %d", length);
  }
  std::optional<DisallowGarbageCollection> no_gc;
  Handle<TrustedByteArray> result = Cast<TrustedByteArray>(
      Allocate(isolate, length, &no_gc, allocation_type));
  int padding_size = SizeFor(length) - OffsetOfElementAt(length);
  memset(&result->values()[length], 0, padding_size);
  return result;
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), v8::internal::DCHECK(), FATAL, v8::internal::kSharedTrusted, v8::internal::kTrusted, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::WeakArrayList::OffsetOfElementAt(), v8::base::internal::result, and V8_UNLIKELY.
Referenced by v8::internal::Heap::CreateInitialMutableObjects().
set_int()
void v8::internal::TrustedByteArray::set_int (int offset, uint32_t value) [inline]
Definition at line 810 of file fixed-array-inl.h.
                                                         {
  DCHECK(IsInBounds(offset));
  DCHECK_LE(offset + sizeof(uint32_t), length());
  base::WriteUnalignedValue<uint32_t>(
      reinterpret_cast<Address>(&values()[offset]), value);
}
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::length, and v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h