v8::internal::BoyerMoorePositionInfo Class Reference
#include <regexp-compiler.h>
Public Types
using Bitset = std::bitset< kMapSize >
Public Member Functions
bool at (int i) const
int map_count () const
void Set (int character)
void SetInterval (const Interval &interval)
void SetAll ()
bool is_non_word ()
bool is_word ()
Bitset raw_bitset () const
Static Public Attributes
static constexpr int kMapSize = 128
static constexpr int kMask = kMapSize - 1
Private Attributes
Bitset map_
int map_count_ = 0
ContainedInLattice w_ = kNotYet
Detailed Description
Definition at line 146 of file regexp-compiler.h.
Member Typedef Documentation
Bitset
using v8::internal::BoyerMoorePositionInfo::Bitset = std::bitset<kMapSize>
Definition at line 162 of file regexp-compiler.h.
Member Function Documentation
at()
bool v8::internal::BoyerMoorePositionInfo::at (int i) const [inline]
Definition at line 148 of file regexp-compiler.h.
{ return map_[i]; }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and map_.
is_non_word()
bool v8::internal::BoyerMoorePositionInfo::is_non_word () [inline]
Definition at line 159 of file regexp-compiler.h.
{ return w_ == kLatticeOut; }
References v8::internal::kLatticeOut, and w_.
Referenced by v8::internal::AssertionNode::EmitBoundaryCheck().
is_word()
bool v8::internal::BoyerMoorePositionInfo::is_word () [inline]
Definition at line 160 of file regexp-compiler.h.
{ return w_ == kLatticeIn; }
References v8::internal::kLatticeIn, and w_.
Referenced by v8::internal::AssertionNode::EmitBoundaryCheck().
map_count()
int v8::internal::BoyerMoorePositionInfo::map_count () const [inline]
Definition at line 153 of file regexp-compiler.h.
{ return map_count_; }
References map_count_.
Referenced by v8::internal::BoyerMooreLookahead::EmitSkipInstructions().
raw_bitset()
Bitset v8::internal::BoyerMoorePositionInfo::raw_bitset () const [inline]
Definition at line 163 of file regexp-compiler.h.
{ return map_; }
References map_.
Referenced by v8::internal::BoyerMooreLookahead::EmitSkipInstructions().
Set()
void v8::internal::BoyerMoorePositionInfo::Set (int character)
Definition at line 2794 of file regexp-compiler.cc.
                                              {
  SetInterval(Interval(character, character));
}
References v8::internal::character, and SetInterval().
Referenced by v8::internal::BoyerMooreLookahead::Set().
SetAll()
void v8::internal::BoyerMoorePositionInfo::SetAll ()
Definition at line 2868 of file regexp-compiler.cc.
                                    {
  w_ = kLatticeUnknown;
  if (map_count_ != kMapSize) {
    map_count_ = kMapSize;
    map_.set();
  }
}
References v8::internal::kLatticeUnknown, kMapSize, map_, map_count_, and w_.
SetInterval()
void v8::internal::BoyerMoorePositionInfo::SetInterval (const Interval & interval)
Definition at line 2849 of file regexp-compiler.cc.
                                                                 {
  w_ = AddRange(w_, kWordRanges, kWordRangeCount, interval);
  if (interval.size() >= kMapSize) {
    map_count_ = kMapSize;
    map_.set();
    return;
  }
  for (int i = interval.from(); i <= interval.to(); i++) {
    int mod_character = (i & kMask);
    if (!map_[mod_character]) {
      map_count_++;
      map_.set(mod_character);
    }
    if (map_count_ == kMapSize) return;
  }
}
References v8::internal::anonymous_namespace{regexp-compiler.cc}::AddRange(), v8::internal::Interval::from(), kMapSize, kMask, v8::internal::regexp_compiler_constants::kWordRangeCount, v8::internal::regexp_compiler_constants::kWordRanges, map_, map_count_, v8::internal::Interval::size(), v8::internal::Interval::to(), and w_.
Referenced by Set(), and v8::internal::BoyerMooreLookahead::SetInterval().
Member Data Documentation
kMapSize
constexpr int v8::internal::BoyerMoorePositionInfo::kMapSize = 128 [static], [constexpr]
Definition at line 150 of file regexp-compiler.h.
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::BitsetFirstSetBit(), SetAll(), and SetInterval().
kMask
constexpr int v8::internal::BoyerMoorePositionInfo::kMask = kMapSize - 1 [static], [constexpr]
Definition at line 151 of file regexp-compiler.h.
Referenced by SetInterval().
map_
Bitset v8::internal::BoyerMoorePositionInfo::map_ [private]
Definition at line 166 of file regexp-compiler.h.
Referenced by at(), raw_bitset(), SetAll(), and SetInterval().
map_count_
int v8::internal::BoyerMoorePositionInfo::map_count_ = 0 [private]
Definition at line 167 of file regexp-compiler.h.
Referenced by map_count(), SetAll(), and SetInterval().
w_
ContainedInLattice v8::internal::BoyerMoorePositionInfo::w_ = kNotYet [private]
Definition at line 168 of file regexp-compiler.h.
Referenced by is_non_word(), is_word(), SetAll(), and SetInterval().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-compiler.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc