v8::internal::DependentCode Class Reference
#include <dependent-code.h>
Public Types
enum DependencyGroup {
kTransitionGroup = 1 << 0
, kPrototypeCheckGroup = 1 << 1
, kPropertyCellChangedGroup = 1 << 2
, kFieldTypeGroup = 1 << 3
,
kFieldConstGroup = 1 << 4
, kFieldRepresentationGroup = 1 << 5
, kInitialMapChangedGroup = 1 << 6
, kAllocationSiteTenuringChangedGroup = 1 << 7
,
kAllocationSiteTransitionChangedGroup = 1 << 8
, kContextCellChangedGroup = 1 << 9
, kEmptyContextExtensionGroup = 1 << 10
 }
using DependencyGroups = base::Flags< DependencyGroup, uint32_t >
Static Public Member Functions
static const char * DependencyGroupName (DependencyGroup group)
static LazyDeoptimizeReason DependencyGroupToLazyDeoptReason (DependencyGroup group)
static V8_EXPORT_PRIVATE void InstallDependency (Isolate *isolate, Handle< Code > code, Handle< HeapObject > object, DependencyGroups groups)
template<typename ObjectT >
static void DeoptimizeDependencyGroups (Isolate *isolate, ObjectT object, DependencyGroups groups)
template<typename ObjectT >
static void DeoptimizeDependencyGroups (Isolate *isolate, Tagged< ObjectT > object, DependencyGroups groups)
template<typename ObjectT >
static bool MarkCodeForDeoptimization (Isolate *isolate, Tagged< ObjectT > object, DependencyGroups groups)
static V8_EXPORT_PRIVATE Tagged< DependentCode > empty_dependent_code (const ReadOnlyRoots &roots)
Static Public Attributes
static constexpr RootIndex kEmptyDependentCode
static constexpr int kSlotsPerEntry
static constexpr int kCodeSlotOffset = 0
static constexpr int kGroupsSlotOffset = 1
Private Member Functions
bool MarkCodeForDeoptimization (Isolate *isolate, DependencyGroups deopt_groups)
void DeoptimizeDependencyGroups (Isolate *isolate, DependencyGroups groups)
template<typename Function >
void IterateAndCompact (IsolateForSandbox isolate, const Function &fn)
int FillEntryFromBack (int index, int length)
OBJECT_CONSTRUCTORS (DependentCode, WeakArrayList)
Static Private Member Functions
static Tagged< DependentCode > GetDependentCode (Tagged< HeapObject > object)
static void SetDependentCode (DirectHandle< HeapObject > object, DirectHandle< DependentCode > dep)
static DirectHandle< DependentCode > InsertWeakCode (Isolate *isolate, Handle< DependentCode > entries, DependencyGroups groups, DirectHandle< Code > code)
static constexpr int LengthFor (int number_of_entries)
Additional Inherited Members
Detailed Description
Definition at line 30 of file dependent-code.h.
Member Typedef Documentation
DependencyGroups
using v8::internal::DependentCode::DependencyGroups = base::Flags<DependencyGroup, uint32_t>
Definition at line 71 of file dependent-code.h.
Member Enumeration Documentation
DependencyGroup
enum v8::internal::DependentCode::DependencyGroup
Enumerator
kTransitionGroup
kPrototypeCheckGroup
kPropertyCellChangedGroup
kFieldTypeGroup
kFieldConstGroup
kFieldRepresentationGroup
kInitialMapChangedGroup
kAllocationSiteTenuringChangedGroup
kAllocationSiteTransitionChangedGroup
kContextCellChangedGroup
kEmptyContextExtensionGroup
Definition at line 32 of file dependent-code.h.
                       {
    // Group of code objects that embed a transition to this map, and depend on
    // being deoptimized when the transition is replaced by a new version.
    kTransitionGroup = 1 << 0,
    // Group of code objects that omit run-time prototype checks for prototypes
    // described by this map. The group is deoptimized whenever the following
    // conditions hold, possibly invalidating the assumptions embedded in the
    // code:
    // a) A fast-mode object described by this map changes shape (and
    // transitions to a new map), or
    // b) A dictionary-mode prototype described by this map changes shape, the
    // const-ness of one of its properties changes, or its [[Prototype]]
    // changes (only the latter causes a transition).
    kPrototypeCheckGroup = 1 << 1,
    // Group of code objects that depends on global property values in property
    // cells not being changed.
    kPropertyCellChangedGroup = 1 << 2,
    // Group of code objects that omit run-time checks for field(s) introduced
    // by this map, i.e. for the field type.
    kFieldTypeGroup = 1 << 3,
    kFieldConstGroup = 1 << 4,
    kFieldRepresentationGroup = 1 << 5,
    // Group of code objects that omit run-time type checks for initial maps of
    // constructors.
    kInitialMapChangedGroup = 1 << 6,
    // Group of code objects that depend on tenuring information in
    // AllocationSites not being changed.
    kAllocationSiteTenuringChangedGroup = 1 << 7,
    // Group of code objects that depend on element transition information in
    // AllocationSites not being changed.
    kAllocationSiteTransitionChangedGroup = 1 << 8,
    // Group of code objects that depend on a slot side table property of
    // a ScriptContext not being changed.
    kContextCellChangedGroup = 1 << 9,
    // Group of code objects that depend on particular context's extension
    // slot to be empty.
    kEmptyContextExtensionGroup = 1 << 10,
    // IMPORTANT: The last bit must fit into a Smi, i.e. into 31 bits.
  };
Member Function Documentation
DeoptimizeDependencyGroups() [1/3]
void v8::internal::DependentCode::DeoptimizeDependencyGroups (Isolate * isolate, DependentCode::DependencyGroups groups) [private]
Definition at line 175 of file dependent-code.cc.
                                                            {
  DisallowGarbageCollection no_gc_scope;
  bool marked_something = MarkCodeForDeoptimization(isolate, groups);
  if (marked_something) {
    DCHECK(AllowCodeDependencyChange::IsAllowed());
    Deoptimizer::DeoptimizeMarkedCode(isolate);
  }
}
References v8::internal::DCHECK(), v8::internal::Deoptimizer::DeoptimizeMarkedCode(), and MarkCodeForDeoptimization().
DeoptimizeDependencyGroups() [2/3]
template<typename ObjectT >
void v8::internal::DependentCode::DeoptimizeDependencyGroups (Isolate * isolate, ObjectT object, DependencyGroups groups) [static]
Definition at line 25 of file dependent-code-inl.h.
                                                                        {
  static_assert(kTaggedCanConvertToRawObjects);
  DeoptimizeDependencyGroups(isolate, Tagged<ObjectT>(object), groups);
}
References v8::internal::kTaggedCanConvertToRawObjects.
Referenced by v8::internal::PropertyCell::ClearAndInvalidate(), v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareEvalHelper(), v8::internal::Map::DeprecateTransitionTree(), v8::internal::AllocationSite::DigestTransitionFeedback(), v8::internal::MapUpdater::GeneralizeField(), v8::internal::anonymous_namespace{js-objects.cc}::InvalidateOnePrototypeValidityCellInternal(), v8::internal::PropertyCell::InvalidateProtector(), v8::internal::anonymous_namespace{contexts.cc}::NotifyContextCellStateWillChange(), v8::internal::Map::NotifyLeafMapLayoutChange(), v8::internal::PropertyCell::PrepareForAndSetValue(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{js-function.cc}::SetInstancePrototype(), and v8::internal::Map::TransitionToDataProperty().
DeoptimizeDependencyGroups() [3/3]
template<typename ObjectT >
void v8::internal::DependentCode::DeoptimizeDependencyGroups (Isolate * isolate, Tagged< ObjectT > object, DependencyGroups groups) [static]
Definition at line 33 of file dependent-code-inl.h.
                                                                        {
  // Shared objects are designed to never invalidate code.
  DCHECK(!HeapLayout::InAnySharedSpace(object) &&
         !HeapLayout::InReadOnlySpace(object));
  object->dependent_code()->DeoptimizeDependencyGroups(isolate, groups);
}
References v8::internal::DCHECK(), v8::internal::HeapLayout::InAnySharedSpace(), and v8::internal::HeapLayout::InReadOnlySpace().
DependencyGroupName()
const char * v8::internal::DependentCode::DependencyGroupName (DependencyGroup group) [static]
Definition at line 191 of file dependent-code.cc.
                                                                    {
  switch (group) {
    case kTransitionGroup:
      return "transition";
    case kPrototypeCheckGroup:
      return "prototype-check";
    case kPropertyCellChangedGroup:
      return "property-cell-changed";
    case kFieldConstGroup:
      return "field-const";
    case kFieldTypeGroup:
      return "field-type";
    case kFieldRepresentationGroup:
      return "field-representation";
    case kInitialMapChangedGroup:
      return "initial-map-changed";
    case kAllocationSiteTenuringChangedGroup:
      return "allocation-site-tenuring-changed";
    case kAllocationSiteTransitionChangedGroup:
      return "allocation-site-transition-changed";
    case kContextCellChangedGroup:
      return "script-context-slot-property-changed";
    case kEmptyContextExtensionGroup:
      return "empty-context-extension";
  }
  UNREACHABLE();
}
References kAllocationSiteTenuringChangedGroup, kAllocationSiteTransitionChangedGroup, kContextCellChangedGroup, kEmptyContextExtensionGroup, kFieldConstGroup, kFieldRepresentationGroup, kFieldTypeGroup, kInitialMapChangedGroup, kPropertyCellChangedGroup, kPrototypeCheckGroup, kTransitionGroup, and v8::internal::UNREACHABLE().
Referenced by v8::internal::anonymous_namespace{dependent-code.cc}::PrintDependencyGroups().
DependencyGroupToLazyDeoptReason()
LazyDeoptimizeReason v8::internal::DependentCode::DependencyGroupToLazyDeoptReason (DependencyGroup group) [static]
Definition at line 219 of file dependent-code.cc.
                           {
  switch (group) {
    case kTransitionGroup:
      return LazyDeoptimizeReason::kMapDeprecated;
    case kPrototypeCheckGroup:
      return LazyDeoptimizeReason::kPrototypeChange;
    case kPropertyCellChangedGroup:
      return LazyDeoptimizeReason::kPropertyCellChange;
    case kFieldConstGroup:
      return LazyDeoptimizeReason::kFieldTypeConstChange;
    case kFieldTypeGroup:
      return LazyDeoptimizeReason::kFieldTypeChange;
    case kFieldRepresentationGroup:
      return LazyDeoptimizeReason::kFieldRepresentationChange;
    case kInitialMapChangedGroup:
      return LazyDeoptimizeReason::kInitialMapChange;
    case kAllocationSiteTenuringChangedGroup:
      return LazyDeoptimizeReason::kAllocationSiteTenuringChange;
    case kAllocationSiteTransitionChangedGroup:
      return LazyDeoptimizeReason::kAllocationSiteTransitionChange;
    case kContextCellChangedGroup:
      return LazyDeoptimizeReason::kContextCellChange;
    case kEmptyContextExtensionGroup:
      return LazyDeoptimizeReason::kEmptyContextExtensionChange;
  }
  UNREACHABLE();
}
References kAllocationSiteTenuringChangedGroup, kAllocationSiteTransitionChangedGroup, kContextCellChangedGroup, kEmptyContextExtensionGroup, kFieldConstGroup, kFieldRepresentationGroup, kFieldTypeGroup, kInitialMapChangedGroup, kPropertyCellChangedGroup, kPrototypeCheckGroup, kTransitionGroup, and v8::internal::UNREACHABLE().
empty_dependent_code()
Tagged< DependentCode > v8::internal::DependentCode::empty_dependent_code (const ReadOnlyRoots & roots) [static]
Definition at line 186 of file dependent-code.cc.
                                {
  return Cast<DependentCode>(roots.empty_weak_array_list());
}
Referenced by v8::internal::ScopeInfo::Create(), v8::internal::Heap::FinalizePartialMap(), v8::internal::AllocationSite::Initialize(), v8::internal::Factory::InitializeMap(), v8::internal::anonymous_namespace{contexts.cc}::IsEmptyDependentCode(), v8::internal::Factory::NewContextCell(), v8::internal::Factory::NewPropertyCell(), and v8::internal::CodeSerializer::SerializeObjectImpl().
FillEntryFromBack()
int v8::internal::DependentCode::FillEntryFromBack (int index, int length) [private]
Definition at line 160 of file dependent-code.cc.
                                                          {
  DCHECK_EQ(index % 2, 0);
  DCHECK_EQ(length % 2, 0);
  for (int i = length - kSlotsPerEntry; i > index; i -= kSlotsPerEntry) {
    Tagged<MaybeObject> obj = Get(i + kCodeSlotOffset);
    if (obj.IsCleared()) continue;
    Set(index + kCodeSlotOffset, obj);
    Set(index + kGroupsSlotOffset, Get(i + kGroupsSlotOffset),
        SKIP_WRITE_BARRIER);
    return i;
  }
  return index; // No non-cleared entry found.
}
References DCHECK_EQ, v8::internal::WeakArrayList::Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), kCodeSlotOffset, kGroupsSlotOffset, kSlotsPerEntry, v8::internal::length, v8::internal::WeakArrayList::Set(), and v8::internal::SKIP_WRITE_BARRIER.
Referenced by IterateAndCompact().
GetDependentCode()
Tagged< DependentCode > v8::internal::DependentCode::GetDependentCode (Tagged< HeapObject > object) [static], [private]
Definition at line 17 of file dependent-code.cc.
                               {
  if (IsMap(object)) {
    return Cast<Map>(object)->dependent_code();
  } else if (IsPropertyCell(object)) {
    return Cast<PropertyCell>(object)->dependent_code();
  } else if (IsAllocationSite(object)) {
    return Cast<AllocationSite>(object)->dependent_code();
  } else if (IsContextCell(object)) {
    return Cast<ContextCell>(object)->dependent_code();
  } else if (IsScopeInfo(object)) {
    return Cast<ScopeInfo>(object)->dependent_code();
  }
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
Referenced by InstallDependency().
InsertWeakCode()
DirectHandle< DependentCode > v8::internal::DependentCode::InsertWeakCode (Isolate * isolate, Handle< DependentCode > entries, DependencyGroups groups, DirectHandle< Code > code) [static], [private]
Definition at line 84 of file dependent-code.cc.
                             {
  if (entries->length() == entries->capacity()) {
    // We'd have to grow - try to compact first.
    entries->IterateAndCompact(
        isolate, [](Tagged<Code>, DependencyGroups) { return false; });
  }
  // As the Code object lives outside of the sandbox in trusted space, we need
  // to use its in-sandbox wrapper object here.
  MaybeObjectDirectHandle code_slot(MakeWeak(code->wrapper()), isolate);
  entries = Cast<DependentCode>(WeakArrayList::AddToEnd(
      isolate, entries, code_slot, Smi::FromInt(groups)));
  return entries;
}
References v8::internal::WeakArrayList::AddToEnd(), code, v8::internal::Smi::FromInt(), and v8::internal::MakeWeak().
Referenced by InstallDependency().
InstallDependency()
void v8::internal::DependentCode::InstallDependency (Isolate * isolate, Handle< Code > code, Handle< HeapObject > object, DependencyGroups groups) [static]
Definition at line 64 of file dependent-code.cc.
                                                               {
  if (V8_UNLIKELY(v8_flags.trace_compilation_dependencies)) {
    StdoutStream{} << "Installing dependency of [" << code << "] on [" << object
                   << "] in groups [";
    PrintDependencyGroups(groups);
    StdoutStream{} << "]\n";
  }
  Handle<DependentCode> old_deps(DependentCode::GetDependentCode(*object),
                                 isolate);
  DirectHandle<DependentCode> new_deps =
      InsertWeakCode(isolate, old_deps, groups, code);
  // Update the list head if necessary.
  if (!new_deps.is_identical_to(old_deps)) {
    DependentCode::SetDependentCode(object, new_deps);
  }
}
References code, GetDependentCode(), InsertWeakCode(), v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::anonymous_namespace{dependent-code.cc}::PrintDependencyGroups(), SetDependentCode(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::InstallAll(), and v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::InstallAllPredictable().
IterateAndCompact()
template<typename Function >
void v8::internal::DependentCode::IterateAndCompact (IsolateForSandbox isolate, const Function & fn) [private]
Definition at line 102 of file dependent-code.cc.
                                                          {
  DisallowGarbageCollection no_gc;
  int len = length();
  if (len == 0) return;
  // We compact during traversal, thus use a somewhat custom loop construct:
  //
  // - Loop back-to-front s.t. trailing cleared entries can simply drop off
  // the back of the list.
  // - Any cleared slots are filled from the back of the list.
  int i = len - kSlotsPerEntry;
  while (i >= 0) {
    Tagged<MaybeObject> obj = Get(i + kCodeSlotOffset);
    if (obj.IsCleared()) {
      len = FillEntryFromBack(i, len);
      i -= kSlotsPerEntry;
      continue;
    }
    if (fn(Cast<CodeWrapper>(obj.GetHeapObjectAssumeWeak())->code(isolate),
           static_cast<DependencyGroups>(
               Get(i + kGroupsSlotOffset).ToSmi().value()))) {
      len = FillEntryFromBack(i, len);
    }
    i -= kSlotsPerEntry;
  }
  set_length(len);
}
References FillEntryFromBack(), v8::internal::WeakArrayList::Get(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), kCodeSlotOffset, kGroupsSlotOffset, kSlotsPerEntry, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::value.
Referenced by MarkCodeForDeoptimization().
LengthFor()
static constexpr int v8::internal::DependentCode::LengthFor (int number_of_entries) [inline], [static], [constexpr], [private]
Definition at line 134 of file dependent-code.h.
                                                        {
    return number_of_entries * kSlotsPerEntry;
  }
MarkCodeForDeoptimization() [1/2]
bool v8::internal::DependentCode::MarkCodeForDeoptimization (Isolate * isolate, DependentCode::DependencyGroups deopt_groups) [private]
Definition at line 135 of file dependent-code.cc.
                                                                  {
  DisallowGarbageCollection no_gc;
  bool marked_something = false;
  IterateAndCompact(isolate, [&](Tagged<Code> code, DependencyGroups groups) {
    if ((groups & deopt_groups) == 0) return false;
    if (!code->marked_for_deoptimization()) {
      // Pick a single group out of the applicable deopt groups, to use as the
      // deopt reason. Only one group is reported to avoid string concatenation.
      DependencyGroup first_group = static_cast<DependencyGroup>(
          1 << base::bits::CountTrailingZeros32(groups & deopt_groups));
      code->SetMarkedForDeoptimization(
          isolate,
          DependentCode::DependencyGroupToLazyDeoptReason(first_group));
      marked_something = true;
    }
    return true;
  });
  return marked_something;
}
References code, IterateAndCompact(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
MarkCodeForDeoptimization() [2/2]
template<typename ObjectT >
bool v8::internal::DependentCode::MarkCodeForDeoptimization (Isolate * isolate, Tagged< ObjectT > object, DependencyGroups groups) [static]
Definition at line 44 of file dependent-code-inl.h.
                                                                       {
  // Shared objects are designed to never invalidate code.
  DCHECK(!HeapLayout::InAnySharedSpace(object) &&
         !HeapLayout::InReadOnlySpace(object));
  return object->dependent_code()->MarkCodeForDeoptimization(isolate, groups);
}
References v8::internal::DCHECK(), v8::internal::HeapLayout::InAnySharedSpace(), and v8::internal::HeapLayout::InReadOnlySpace().
Referenced by DeoptimizeDependencyGroups().
OBJECT_CONSTRUCTORS()
v8::internal::DependentCode::OBJECT_CONSTRUCTORS (DependentCode , WeakArrayList) [private]
SetDependentCode()
void v8::internal::DependentCode::SetDependentCode (DirectHandle< HeapObject > object, DirectHandle< DependentCode > dep) [static], [private]
Definition at line 33 of file dependent-code.cc.
                                                                      {
  if (IsMap(*object)) {
    Cast<Map>(object)->set_dependent_code(*dep);
  } else if (IsPropertyCell(*object)) {
    Cast<PropertyCell>(object)->set_dependent_code(*dep);
  } else if (IsAllocationSite(*object)) {
    Cast<AllocationSite>(object)->set_dependent_code(*dep);
  } else if (IsContextCell(*object)) {
    Cast<ContextCell>(object)->set_dependent_code(*dep);
  } else if (IsScopeInfo(*object)) {
    Cast<ScopeInfo>(object)->set_dependent_code(*dep);
  } else {
    UNREACHABLE();
  }
}
References v8::internal::UNREACHABLE().
Referenced by InstallDependency().
Member Data Documentation
kCodeSlotOffset
constexpr int v8::internal::DependentCode::kCodeSlotOffset = 0 [static], [constexpr]
Definition at line 106 of file dependent-code.h.
Referenced by FillEntryFromBack(), and IterateAndCompact().
kEmptyDependentCode
constexpr RootIndex v8::internal::DependentCode::kEmptyDependentCode [static], [constexpr]
Initial value:
=
      RootIndex::kEmptyWeakArrayList
Definition at line 100 of file dependent-code.h.
kGroupsSlotOffset
constexpr int v8::internal::DependentCode::kGroupsSlotOffset = 1 [static], [constexpr]
Definition at line 107 of file dependent-code.h.
Referenced by FillEntryFromBack(), and IterateAndCompact().
kSlotsPerEntry
constexpr int v8::internal::DependentCode::kSlotsPerEntry [static], [constexpr]
Initial value:
=
      2
Definition at line 104 of file dependent-code.h.
Referenced by FillEntryFromBack(), and IterateAndCompact().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/dependent-code.h
/mnt/V8SourceCode/src/objects/dependent-code-inl.h
/mnt/V8SourceCode/src/objects/dependent-code.cc