v8::internal::LiteralProperty Class Reference
#include <ast.h>
Public Member Functions
Expression * key () const
Expression * value () const
bool is_computed_name () const
bool NeedsSetFunctionName () const
Protected Member Functions
LiteralProperty (Expression *key, Expression *value, bool is_computed_name)
Protected Attributes
base::PointerWithPayload< Expression, bool, 1 > key_and_is_computed_name_
Expression * value_
Detailed Description
Definition at line 1233 of file ast.h.
Constructor & Destructor Documentation
LiteralProperty()
v8::internal::LiteralProperty::LiteralProperty (Expression * key, Expression * value, bool is_computed_name) [inline], [protected]
Definition at line 1244 of file ast.h.
      : key_and_is_computed_name_(key, is_computed_name), value_(value) {}
Member Function Documentation
is_computed_name()
bool v8::internal::LiteralProperty::is_computed_name () const [inline]
Definition at line 1238 of file ast.h.
                                {
    return key_and_is_computed_name_.GetPayload();
  }
References key_and_is_computed_name_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), NeedsSetFunctionName(), v8::internal::ClassBoilerplate::New(), v8::internal::ObjectLiteralProperty::ObjectLiteralProperty(), and v8::internal::AstFunctionLiteralIdReindexer::VisitClassLiteral().
key()
Expression* v8::internal::LiteralProperty::key () const [inline]
Definition at line 1235 of file ast.h.
{ return key_and_is_computed_name_.GetPointer(); }
References key_and_is_computed_name_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), v8::internal::interpreter::BytecodeGenerator::BuildLoadPropertyKey(), v8::internal::ClassBoilerplate::New(), v8::internal::ObjectLiteralProperty::ObjectLiteralProperty(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), and v8::internal::AstFunctionLiteralIdReindexer::VisitClassLiteral().
NeedsSetFunctionName()
bool v8::internal::LiteralProperty::NeedsSetFunctionName () const
Definition at line 299 of file ast.cc.
                                                 {
  return is_computed_name() && (value_->IsAnonymousFunctionDefinition() ||
                                value_->IsConciseMethodDefinition() ||
                                value_->IsAccessorFunctionDefinition());
}
References is_computed_name(), v8::internal::Expression::IsAccessorFunctionDefinition(), v8::internal::Expression::IsAnonymousFunctionDefinition(), v8::internal::Expression::IsConciseMethodDefinition(), and value_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), and v8::internal::Parser::SetFunctionNameFromPropertyName().
value()
Expression* v8::internal::LiteralProperty::value () const [inline]
Definition at line 1236 of file ast.h.
{ return value_; }
References value_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), v8::internal::ObjectLiteralProperty::IsNullPrototype(), v8::internal::Parser::SetFunctionNameFromPropertyName(), v8::internal::AstFunctionLiteralIdReindexer::VisitClassLiteral(), and v8::internal::interpreter::BytecodeGenerator::VisitLiteralAccessor().
Member Data Documentation
key_and_is_computed_name_
base::PointerWithPayload<Expression, bool, 1> v8::internal::LiteralProperty::key_and_is_computed_name_ [protected]
Definition at line 1247 of file ast.h.
Referenced by is_computed_name(), and key().
value_
Expression* v8::internal::LiteralProperty::value_ [protected]
Definition at line 1248 of file ast.h.
Referenced by v8::internal::ObjectLiteralProperty::IsCompileTimeValue(), NeedsSetFunctionName(), v8::internal::ObjectLiteralProperty::ObjectLiteralProperty(), and value().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc