v8::internal::BodyDescriptorBase Class Reference
#include <objects-body-descriptors.h>
Public Member Functions
template<typename ObjectVisitor >
DISABLE_CFI_PERF void IteratePointers (Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor *v)
template<typename ObjectVisitor >
DISABLE_CFI_PERF void IterateMaybeWeakPointers (Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor *v)
template<typename ObjectVisitor >
DISABLE_CFI_PERF void IterateCustomWeakPointers (Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor *v)
template<typename ObjectVisitor >
DISABLE_CFI_PERF void IterateEphemeron (Tagged< HeapObject > obj, int index, int key_offset, int value_offset, ObjectVisitor *v)
Static Public Member Functions
template<typename ObjectVisitor >
static void IteratePointers (Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor *v)
template<typename ObjectVisitor >
static void IteratePointer (Tagged< HeapObject > obj, int offset, ObjectVisitor *v)
template<typename ObjectVisitor >
static void IterateCustomWeakPointers (Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor *v)
template<typename ObjectVisitor >
static void IterateCustomWeakPointer (Tagged< HeapObject > obj, int offset, ObjectVisitor *v)
template<typename ObjectVisitor >
static void IterateEphemeron (Tagged< HeapObject > obj, int index, int key_offset, int value_offset, ObjectVisitor *v)
template<typename ObjectVisitor >
static void IterateMaybeWeakPointers (Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor *v)
template<typename ObjectVisitor >
static void IterateMaybeWeakPointer (Tagged< HeapObject > obj, int offset, ObjectVisitor *v)
template<typename ObjectVisitor >
static void IterateTrustedPointer (Tagged< HeapObject > obj, int offset, ObjectVisitor *visitor, IndirectPointerMode mode, IndirectPointerTag tag)
template<typename ObjectVisitor >
static void IterateCodePointer (Tagged< HeapObject > obj, int offset, ObjectVisitor *visitor, IndirectPointerMode mode)
template<typename ObjectVisitor >
static void IterateSelfIndirectPointer (Tagged< HeapObject > obj, IndirectPointerTag tag, ObjectVisitor *v)
template<typename ObjectVisitor >
static void IterateProtectedPointer (Tagged< HeapObject > obj, int offset, ObjectVisitor *v)
Static Protected Member Functions
static bool IsValidEmbedderJSObjectSlotImpl (Tagged< Map > map, Tagged< HeapObject > obj, int offset)
template<typename ObjectVisitor >
static void IterateJSObjectBodyImpl (Tagged< Map > map, Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor *v)
template<typename ObjectVisitor >
static void IterateJSObjectBodyWithoutEmbedderFieldsImpl (Tagged< Map > map, Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor *v)
Detailed Description
Definition at line 23 of file objects-body-descriptors.h.
Member Function Documentation
IsValidEmbedderJSObjectSlotImpl()
static bool v8::internal::BodyDescriptorBase::IsValidEmbedderJSObjectSlotImpl (Tagged< Map > map, Tagged< HeapObject > obj, int offset) [inline], [static], [protected]
IterateCodePointer()
template<typename ObjectVisitor >
void v8::internal::BodyDescriptorBase::IterateCodePointer (Tagged< HeapObject > obj, int offset, ObjectVisitor * visitor, IndirectPointerMode mode) [inline], [static]
Definition at line 281 of file objects-body-descriptors-inl.h.
                                                                      {
  IterateTrustedPointer(obj, offset, v, mode, kCodeIndirectPointerTag);
}
References IterateTrustedPointer(), and mode().
Referenced by v8::internal::IrRegExpData::BodyDescriptor::IterateBody(), v8::internal::JSFunction::BodyDescriptor::IterateBody(), and v8::internal::CodeWrapper::BodyDescriptor::IterateBody().
IterateCustomWeakPointer()
template<typename ObjectVisitor >
void v8::internal::BodyDescriptorBase::IterateCustomWeakPointer (Tagged< HeapObject > obj, int offset, ObjectVisitor * v) [inline], [static]
Definition at line 258 of file objects-body-descriptors-inl.h.
                                                                    {
  v->VisitCustomWeakPointer(obj, obj->RawField(offset));
}
References v8::internal::ObjectVisitor::VisitCustomWeakPointer().
Referenced by v8::internal::WeakCell::BodyDescriptor::IterateBody(), v8::internal::JSWeakRef::BodyDescriptor::IterateBody(), v8::internal::JSFinalizationRegistry::BodyDescriptor::IterateBody(), and IterateTrustedPointer().
IterateCustomWeakPointers() [1/2]
template<typename ObjectVisitor >
DISABLE_CFI_PERF void v8::internal::BodyDescriptorBase::IterateCustomWeakPointers (Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor * v)
Definition at line 242 of file objects-body-descriptors-inl.h.
                      {
  v->VisitCustomWeakPointers(obj, obj->RawField(start_offset),
                             obj->RawField(end_offset));
}
References v8::internal::ObjectVisitor::VisitCustomWeakPointers().
IterateCustomWeakPointers() [2/2]
template<typename ObjectVisitor >
static void v8::internal::BodyDescriptorBase::IterateCustomWeakPointers (Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor * v) [inline], [static]
Referenced by v8::internal::AllocationSite::BodyDescriptor::IterateBody(), and v8::internal::NativeContext::BodyDescriptor::IterateBody().
IterateEphemeron() [1/2]
template<typename ObjectVisitor >
DISABLE_CFI_PERF void v8::internal::BodyDescriptorBase::IterateEphemeron (Tagged< HeapObject > obj, int index, int key_offset, int value_offset, ObjectVisitor * v)
Definition at line 250 of file objects-body-descriptors-inl.h.
                      {
  v->VisitEphemeron(obj, index, obj->RawField(key_offset),
                    obj->RawField(value_offset));
}
References v8::internal::index, and v8::internal::ObjectVisitor::VisitEphemeron().
IterateEphemeron() [2/2]
template<typename ObjectVisitor >
static void v8::internal::BodyDescriptorBase::IterateEphemeron (Tagged< HeapObject > obj, int index, int key_offset, int value_offset, ObjectVisitor * v) [inline], [static]
Referenced by v8::internal::EphemeronHashTable::BodyDescriptor::IterateBody().
IterateJSObjectBodyImpl()
template<typename ObjectVisitor >
void v8::internal::BodyDescriptorBase::IterateJSObjectBodyImpl (Tagged< Map > map, Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor * v) [inline], [static], [protected]
Definition at line 71 of file objects-body-descriptors-inl.h.
                                                                   {
#ifdef V8_COMPRESS_POINTERS
  static_assert(kEmbedderDataSlotSize == 2 * kTaggedSize);
  int header_end_offset = JSObject::GetHeaderSize(map);
  int inobject_fields_start_offset = map->GetInObjectPropertyOffset(0);
  // We are always requested to process header and embedder fields.
  DCHECK_LE(inobject_fields_start_offset, end_offset);
  // Embedder fields are located between header and inobject properties.
  if (header_end_offset < inobject_fields_start_offset) {
    // There are embedder fields.
    DCHECK_EQ(header_end_offset, JSObject::GetEmbedderFieldsStartOffset(map));
    IteratePointers(obj, start_offset, header_end_offset, v);
    for (int offset = header_end_offset; offset < inobject_fields_start_offset;
         offset += kEmbedderDataSlotSize) {
      IteratePointer(obj, offset + EmbedderDataSlot::kTaggedPayloadOffset, v);
      v->VisitExternalPointer(
          obj, obj->RawExternalPointerField(
                   offset + EmbedderDataSlot::kExternalPointerOffset,
                   kEmbedderDataSlotPayloadTag));
    }
    // Proceed processing inobject properties.
    start_offset = inobject_fields_start_offset;
  }
#else
  // We store raw aligned pointers as Smis, so it's safe to iterate the whole
  // embedder field area as tagged slots.
  static_assert(kEmbedderDataSlotSize == kTaggedSize);
#endif
  IteratePointers(obj, start_offset, end_offset, v);
}
References DCHECK_EQ, DCHECK_LE, v8::internal::JSObject::GetEmbedderFieldsStartOffset(), v8::internal::JSObject::GetHeaderSize(), IteratePointer(), IteratePointers(), v8::internal::kEmbedderDataSlotPayloadTag, v8::internal::kEmbedderDataSlotSize, v8::internal::EmbedderDataSlot::kExternalPointerOffset, v8::internal::EmbedderDataSlot::kTaggedPayloadOffset, v8::internal::kTaggedSize, and v8::internal::ObjectVisitor::VisitExternalPointer().
Referenced by v8::internal::JSObject::BodyDescriptor::IterateBody(), v8::internal::JSDate::BodyDescriptor::IterateBody(), v8::internal::JSRegExp::BodyDescriptor::IterateBody(), v8::internal::JSWeakRef::BodyDescriptor::IterateBody(), v8::internal::JSFinalizationRegistry::BodyDescriptor::IterateBody(), v8::internal::JSFunction::BodyDescriptor::IterateBody(), v8::internal::JSWeakCollection::BodyDescriptorImpl::IterateBody(), and v8::internal::JSAPIObjectWithEmbedderSlotsOrJSSpecialObjectBodyDescriptor::IterateJSAPIObjectWithEmbedderSlotsTail().
IterateJSObjectBodyWithoutEmbedderFieldsImpl()
template<typename ObjectVisitor >
void v8::internal::BodyDescriptorBase::IterateJSObjectBodyWithoutEmbedderFieldsImpl (Tagged< Map > map, Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor * v) [inline], [static], [protected]
Definition at line 108 of file objects-body-descriptors-inl.h.
                      {
  // This body iteration assumes that there's no embedder fields.
  DCHECK_IMPLIES(JSObject::MayHaveEmbedderFields(map),
                 UncheckedCast<JSObject>(obj)->GetEmbedderFieldCount(map) == 0);
  IteratePointers(obj, start_offset, end_offset, v);
}
References DCHECK_IMPLIES, IteratePointers(), and v8::internal::JSObject::MayHaveEmbedderFields().
Referenced by v8::internal::JSAPIObjectWithEmbedderSlotsOrJSSpecialObjectBodyDescriptor::IterateJSAPIObjectWithoutEmbedderSlotsTail().
IterateMaybeWeakPointer()
template<typename ObjectVisitor >
void v8::internal::BodyDescriptorBase::IterateMaybeWeakPointer (Tagged< HeapObject > obj, int offset, ObjectVisitor * v) [inline], [static]
Definition at line 235 of file objects-body-descriptors-inl.h.
                                                                               {
  DCHECK_NE(offset, HeapObject::kMapOffset);
  v->VisitPointer(obj, obj->RawMaybeWeakField(offset));
}
References DCHECK_NE, v8::internal::HeapObject::kMapOffset, and v8::internal::ObjectVisitor::VisitPointer().
Referenced by v8::internal::Map::BodyDescriptor::IterateBody().
IterateMaybeWeakPointers() [1/2]
template<typename ObjectVisitor >
DISABLE_CFI_PERF void v8::internal::BodyDescriptorBase::IterateMaybeWeakPointers (Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor * v)
Definition at line 227 of file objects-body-descriptors-inl.h.
                      {
  v->VisitPointers(obj, obj->RawMaybeWeakField(start_offset),
                   obj->RawMaybeWeakField(end_offset));
}
References v8::internal::ObjectVisitor::VisitPointers().
IterateMaybeWeakPointers() [2/2]
template<typename ObjectVisitor >
static void v8::internal::BodyDescriptorBase::IterateMaybeWeakPointers (Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor * v) [inline], [static]
Referenced by v8::internal::DataHandler::BodyDescriptor::IterateBody(), and v8::internal::SuffixRangeWeakBodyDescriptor< start_offset >::IterateBody().
IteratePointer()
template<typename ObjectVisitor >
void v8::internal::BodyDescriptorBase::IteratePointer (Tagged< HeapObject > obj, int offset, ObjectVisitor * v) [inline], [static]
Definition at line 220 of file objects-body-descriptors-inl.h.
                                                          {
  DCHECK_NE(offset, HeapObject::kMapOffset);
  v->VisitPointer(obj, obj->RawField(offset));
}
References DCHECK_NE, v8::internal::HeapObject::kMapOffset, and v8::internal::ObjectVisitor::VisitPointer().
Referenced by v8::internal::JSRegExp::BodyDescriptor::IterateBody(), v8::internal::RegExpData::BodyDescriptor::IterateBody(), v8::internal::AtomRegExpData::BodyDescriptor::IterateBody(), v8::internal::IrRegExpData::BodyDescriptor::IterateBody(), v8::internal::BytecodeArray::BodyDescriptor::IterateBody(), v8::internal::UncompiledDataWithoutPreparseData::BodyDescriptor::IterateBody(), v8::internal::UncompiledDataWithPreparseData::BodyDescriptor::IterateBody(), v8::internal::UncompiledDataWithoutPreparseDataWithJob::BodyDescriptor::IterateBody(), v8::internal::UncompiledDataWithPreparseDataAndJob::BodyDescriptor::IterateBody(), v8::internal::SharedFunctionInfoWrapper::BodyDescriptor::IterateBody(), v8::internal::EmbedderDataArray::BodyDescriptor::IterateBody(), v8::internal::FeedbackCell::BodyDescriptor::IterateBody(), IterateJSObjectBodyImpl(), and IterateTrustedPointer().
IteratePointers() [1/2]
template<typename ObjectVisitor >
DISABLE_CFI_PERF void v8::internal::BodyDescriptorBase::IteratePointers (Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor * v)
Definition at line 209 of file objects-body-descriptors-inl.h.
                      {
  if (start_offset == HeapObject::kMapOffset) {
    v->VisitMapPointer(obj);
    start_offset += kTaggedSize;
  }
  v->VisitPointers(obj, obj->RawField(start_offset), obj->RawField(end_offset));
}
References v8::internal::HeapObject::kMapOffset, v8::internal::kTaggedSize, v8::internal::ObjectVisitor::VisitMapPointer(), and v8::internal::ObjectVisitor::VisitPointers().
IteratePointers() [2/2]
template<typename ObjectVisitor >
static void v8::internal::BodyDescriptorBase::IteratePointers (Tagged< HeapObject > obj, int start_offset, int end_offset, ObjectVisitor * v) [inline], [static]
Referenced by v8::internal::JSObject::FastBodyDescriptor::IterateBody(), v8::internal::JSDate::BodyDescriptor::IterateBody(), v8::internal::JSRegExp::BodyDescriptor::IterateBody(), v8::internal::WeakCell::BodyDescriptor::IterateBody(), v8::internal::JSWeakRef::BodyDescriptor::IterateBody(), v8::internal::JSFinalizationRegistry::BodyDescriptor::IterateBody(), v8::internal::AllocationSite::BodyDescriptor::IterateBody(), v8::internal::JSFunction::BodyDescriptor::IterateBody(), v8::internal::JSArrayBuffer::BodyDescriptor::IterateBody(), v8::internal::JSArrayBufferView::BodyDescriptor::IterateBody(), v8::internal::JSTypedArray::BodyDescriptor::IterateBody(), v8::internal::JSDataViewOrRabGsabDataView::BodyDescriptor::IterateBody(), v8::internal::JSExternalObject::BodyDescriptor::IterateBody(), v8::internal::PreparseData::BodyDescriptor::IterateBody(), v8::internal::SharedFunctionInfo::BodyDescriptor::IterateBody(), v8::internal::DebugInfo::BodyDescriptor::IterateBody(), v8::internal::CallSiteInfo::BodyDescriptor::IterateBody(), v8::internal::PrototypeInfo::BodyDescriptor::IterateBody(), v8::internal::JSSynchronizationPrimitive::BodyDescriptor::IterateBody(), v8::internal::Map::BodyDescriptor::IterateBody(), v8::internal::DataHandler::BodyDescriptor::IterateBody(), v8::internal::NativeContext::BodyDescriptor::IterateBody(), v8::internal::Code::BodyDescriptor::IterateBody(), v8::internal::EmbedderDataArray::BodyDescriptor::IterateBody(), v8::internal::EphemeronHashTable::BodyDescriptor::IterateBody(), v8::internal::AccessorInfo::BodyDescriptor::IterateBody(), v8::internal::InterceptorInfo::BodyDescriptor::IterateBody(), v8::internal::FunctionTemplateInfo::BodyDescriptor::IterateBody(), v8::internal::SuffixRangeBodyDescriptor< start_offset >::IterateBody(), v8::internal::FixedRangeBodyDescriptor< start_offset, end_offset >::IterateBody(), v8::internal::JSAPIObjectWithEmbedderSlotsOrJSSpecialObjectBodyDescriptor::IterateJSAPIObjectWithEmbedderSlotsHeader(), IterateJSObjectBodyImpl(), and IterateJSObjectBodyWithoutEmbedderFieldsImpl().
IterateProtectedPointer()
template<typename ObjectVisitor >
void v8::internal::BodyDescriptorBase::IterateProtectedPointer (Tagged< HeapObject > obj, int offset, ObjectVisitor * v) [inline], [static]
Definition at line 299 of file objects-body-descriptors-inl.h.
                                                                               {
  DCHECK(IsTrustedObject(obj));
  Tagged<TrustedObject> host = Cast<TrustedObject>(obj);
  v->VisitProtectedPointer(host, host->RawProtectedPointerField(offset));
}
References v8::internal::DCHECK(), and v8::internal::ObjectVisitor::VisitProtectedPointer().
Referenced by v8::internal::IrRegExpData::BodyDescriptor::IterateBody(), v8::internal::BytecodeArray::BodyDescriptor::IterateBody(), v8::internal::InterpreterData::BodyDescriptor::IterateBody(), v8::internal::Code::BodyDescriptor::IterateBody(), v8::internal::ProtectedFixedArray::BodyDescriptor::IterateBody(), and v8::internal::InstructionStream::BodyDescriptor::IterateBody().
IterateSelfIndirectPointer()
template<typename ObjectVisitor >
void v8::internal::BodyDescriptorBase::IterateSelfIndirectPointer (Tagged< HeapObject > obj, IndirectPointerTag tag, ObjectVisitor * v) [inline], [static]
Definition at line 288 of file objects-body-descriptors-inl.h.
                                                                      {
#ifdef V8_ENABLE_SANDBOX
  v->VisitTrustedPointerTableEntry(
      obj, obj->RawIndirectPointerField(
               ExposedTrustedObject::kSelfIndirectPointerOffset, tag));
#endif
}
References v8::internal::ObjectVisitor::VisitTrustedPointerTableEntry().
Referenced by v8::internal::RegExpData::BodyDescriptor::IterateBody(), v8::internal::AtomRegExpData::BodyDescriptor::IterateBody(), v8::internal::IrRegExpData::BodyDescriptor::IterateBody(), v8::internal::BytecodeArray::BodyDescriptor::IterateBody(), v8::internal::InterpreterData::BodyDescriptor::IterateBody(), v8::internal::UncompiledDataWithoutPreparseData::BodyDescriptor::IterateBody(), v8::internal::UncompiledDataWithPreparseData::BodyDescriptor::IterateBody(), v8::internal::UncompiledDataWithoutPreparseDataWithJob::BodyDescriptor::IterateBody(), v8::internal::UncompiledDataWithPreparseDataAndJob::BodyDescriptor::IterateBody(), and v8::internal::Code::BodyDescriptor::IterateBody().
IterateTrustedPointer()
template<typename ObjectVisitor >
void v8::internal::BodyDescriptorBase::IterateTrustedPointer (Tagged< HeapObject > obj, int offset, ObjectVisitor * visitor, IndirectPointerMode mode, IndirectPointerTag tag) [inline], [static]
Definition at line 265 of file objects-body-descriptors-inl.h.
                                                                       {
#ifdef V8_ENABLE_SANDBOX
  v->VisitIndirectPointer(obj, obj->RawIndirectPointerField(offset, tag), mode);
#else
  if (mode == IndirectPointerMode::kStrong) {
    IteratePointer(obj, offset, v);
  } else {
    IterateCustomWeakPointer(obj, offset, v);
  }
#endif
}
References IterateCustomWeakPointer(), IteratePointer(), v8::internal::kStrong, mode(), and v8::internal::ObjectVisitor::VisitIndirectPointer().
Referenced by v8::internal::JSRegExp::BodyDescriptor::IterateBody(), v8::internal::RegExpDataWrapper::BodyDescriptor::IterateBody(), v8::internal::BytecodeWrapper::BodyDescriptor::IterateBody(), v8::internal::SharedFunctionInfo::BodyDescriptor::IterateBody(), v8::internal::DebugInfo::BodyDescriptor::IterateBody(), v8::internal::CallSiteInfo::BodyDescriptor::IterateBody(), and IterateCodePointer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/objects-body-descriptors.h
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h