v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AsyncInstantiateCompileResultResolver Class Reference
Public Member Functions
AsyncInstantiateCompileResultResolver (Isolate *isolate, Local< Context > context, Local< Promise::Resolver > promise_resolver, Local< Value > imports)
void OnCompilationSucceeded (i::DirectHandle< i::WasmModuleObject > result) override
void OnCompilationFailed (i::DirectHandle< i::JSAny > error_reason) override
Private Attributes
bool finished_ = false
Isolate * isolate_
Global< Context > context_
Global< Promise::Resolver > promise_resolver_
Global< Value > imports_
Static Private Attributes
static constexpr char kGlobalPromiseHandle []
static constexpr char kGlobalImportsHandle []
Detailed Description
Definition at line 448 of file wasm-js.cc.
Constructor & Destructor Documentation
AsyncInstantiateCompileResultResolver()
v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AsyncInstantiateCompileResultResolver::AsyncInstantiateCompileResultResolver (Isolate * isolate, Local< Context > context, Local< Promise::Resolver > promise_resolver, Local< Value > imports) [inline]
Definition at line 451 of file wasm-js.cc.
      : isolate_(isolate),
        context_(isolate, context),
        promise_resolver_(isolate, promise_resolver),
        imports_(isolate, imports) {
    context_.SetWeak();
    promise_resolver_.AnnotateStrongRetainer(kGlobalPromiseHandle);
    imports_.AnnotateStrongRetainer(kGlobalImportsHandle);
  }
Member Function Documentation
OnCompilationFailed()
void v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AsyncInstantiateCompileResultResolver::OnCompilationFailed (i::DirectHandle< i::JSAny > error_reason) [inline], [override]
Definition at line 475 of file wasm-js.cc.
                                                                        {
    if (finished_) return;
    finished_ = true;
    if (context_.IsEmpty()) return;
    auto callback = reinterpret_cast<i::Isolate*>(isolate_)
                        ->wasm_async_resolve_promise_callback();
    CHECK(callback);
    callback(isolate_, context_.Get(isolate_), promise_resolver_.Get(isolate_),
             Utils::ToLocal(error_reason), WasmAsyncSuccess::kFail);
  }
References CHECK, and v8::kFail.
OnCompilationSucceeded()
void v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AsyncInstantiateCompileResultResolver::OnCompilationSucceeded (i::DirectHandle< i::WasmModuleObject > result) [inline], [override]
Definition at line 463 of file wasm-js.cc.
                                                        {
    if (finished_) return;
    finished_ = true;
    i::wasm::GetWasmEngine()->AsyncInstantiate(
        reinterpret_cast<i::Isolate*>(isolate_),
        std::make_unique<InstantiateBytesResultResolver>(
            isolate_, context_.Get(isolate_), promise_resolver_.Get(isolate_),
            Utils::ToLocal(i::Cast<i::Object>(result))),
        result, ImportsAsMaybeReceiver(imports_.Get(isolate_)));
  }
References v8::internal::wasm::WasmEngine::AsyncInstantiate(), v8::internal::wasm::GetWasmEngine(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ImportsAsMaybeReceiver(), and v8::base::internal::result.
Member Data Documentation
context_
Global<Context> v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AsyncInstantiateCompileResultResolver::context_ [private]
Definition at line 493 of file wasm-js.cc.
finished_
bool v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AsyncInstantiateCompileResultResolver::finished_ = false [private]
Definition at line 491 of file wasm-js.cc.
imports_
Global<Value> v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AsyncInstantiateCompileResultResolver::imports_ [private]
Definition at line 495 of file wasm-js.cc.
isolate_
Isolate* v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AsyncInstantiateCompileResultResolver::isolate_ [private]
Definition at line 492 of file wasm-js.cc.
kGlobalImportsHandle
constexpr char v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AsyncInstantiateCompileResultResolver::kGlobalImportsHandle [static], [constexpr], [private]
Initial value:
=
      "AsyncInstantiateCompileResultResolver::module_"
Definition at line 489 of file wasm-js.cc.
kGlobalPromiseHandle
constexpr char v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AsyncInstantiateCompileResultResolver::kGlobalPromiseHandle [static], [constexpr], [private]
Initial value:
=
      "AsyncInstantiateCompileResultResolver::promise_"
Definition at line 487 of file wasm-js.cc.
promise_resolver_
Global<Promise::Resolver> v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AsyncInstantiateCompileResultResolver::promise_resolver_ [private]
Definition at line 494 of file wasm-js.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-js.cc