v8::internal::compiler::LiveRangeConnector Class Reference
#include <register-allocator.h>
Public Member Functions
LiveRangeConnector (RegisterAllocationData *data)
LiveRangeConnector (const LiveRangeConnector &)=delete
LiveRangeConnector & operator= (const LiveRangeConnector &)=delete
void ConnectRanges (Zone *local_zone)
void ResolveControlFlow (Zone *local_zone)
Private Member Functions
RegisterAllocationData * data () const
InstructionSequence * code () const
Zone * code_zone () const
bool CanEagerlyResolveControlFlow (const InstructionBlock *block) const
int ResolveControlFlow (const InstructionBlock *block, const InstructionOperand &cur_op, const InstructionBlock *pred, const InstructionOperand &pred_op)
void CommitSpillsInDeferredBlocks (TopLevelLiveRange *range, Zone *temp_zone)
Private Attributes
RegisterAllocationData *const data_
Detailed Description
Definition at line 1742 of file register-allocator.h.
Constructor & Destructor Documentation
LiveRangeConnector() [1/2]
v8::internal::compiler::LiveRangeConnector::LiveRangeConnector (RegisterAllocationData * data) [explicit]
Definition at line 4904 of file register-allocator.cc.
    : data_(data) {}
LiveRangeConnector() [2/2]
v8::internal::compiler::LiveRangeConnector::LiveRangeConnector (const LiveRangeConnector &) [delete]
Member Function Documentation
CanEagerlyResolveControlFlow()
bool v8::internal::compiler::LiveRangeConnector::CanEagerlyResolveControlFlow (const InstructionBlock * block) const [private]
Definition at line 4907 of file register-allocator.cc.
                                         {
  if (block->PredecessorCount() != 1) return false;
  return block->predecessors()[0].IsNext(block->rpo_number());
}
References v8::internal::compiler::InstructionBlock::PredecessorCount(), v8::internal::compiler::InstructionBlock::predecessors(), and v8::internal::compiler::InstructionBlock::rpo_number().
Referenced by ConnectRanges(), and ResolveControlFlow().
code()
InstructionSequence* v8::internal::compiler::LiveRangeConnector::code () const [inline], [private]
Definition at line 1760 of file register-allocator.h.
{ return data()->code(); }
References v8::internal::compiler::RegisterAllocationData::code(), and data().
Referenced by code_zone(), CommitSpillsInDeferredBlocks(), ConnectRanges(), and ResolveControlFlow().
code_zone()
Zone* v8::internal::compiler::LiveRangeConnector::code_zone () const [inline], [private]
Definition at line 1761 of file register-allocator.h.
{ return code()->zone(); }
References code(), and v8::internal::compiler::InstructionSequence::zone().
Referenced by ConnectRanges().
CommitSpillsInDeferredBlocks()
void v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks (TopLevelLiveRange * range, Zone * temp_zone) [private]
Definition at line 5149 of file register-allocator.cc.
                                                                       {
  DCHECK(range->IsSpilledOnlyInDeferredBlocks(data()));
  DCHECK(!range->spilled());
  InstructionSequence* code = data()->code();
  InstructionOperand spill_operand = range->GetSpillRangeOperand();
  TRACE("Live Range %d will be spilled only in deferred blocks.\n",
        range->vreg());
  // If we have ranges that aren't spilled but require the operand on the stack,
  // make sure we insert the spill.
  for (const LiveRange* child = range; child != nullptr;
       child = child->next()) {
    for (const UsePosition* pos : child->positions()) {
      if (pos->type() != UsePositionType::kRequiresSlot && !child->spilled())
        continue;
      range->AddBlockRequiringSpillOperand(
          code->GetInstructionBlock(pos->pos().ToInstructionIndex())
              ->rpo_number(),
          data());
    }
  }
  ZoneQueue<int> worklist(temp_zone);
  for (int block_id : *range->GetListOfBlocksRequiringSpillOperands(data())) {
    worklist.push(block_id);
  }
  ZoneSet<std::pair<RpoNumber, int>> done_moves(temp_zone);
  // Seek the deferred blocks that dominate locations requiring spill operands,
  // and spill there. We only need to spill at the start of such blocks.
  SparseBitVector done_blocks(temp_zone);
  while (!worklist.empty()) {
    int block_id = worklist.front();
    worklist.pop();
    if (done_blocks.Contains(block_id)) continue;
    done_blocks.Add(block_id);
    InstructionBlock* spill_block =
        code->InstructionBlockAt(RpoNumber::FromInt(block_id));
    for (const RpoNumber& pred : spill_block->predecessors()) {
      const InstructionBlock* pred_block = code->InstructionBlockAt(pred);
      if (pred_block->IsDeferred()) {
        worklist.push(pred_block->rpo_number().ToInt());
      } else {
        LifetimePosition pred_end =
            LifetimePosition::InstructionFromInstructionIndex(
                pred_block->last_instruction_index());
        LiveRange* child_range = range->GetChildCovers(pred_end);
        DCHECK_NOT_NULL(child_range);
        InstructionOperand pred_op = child_range->GetAssignedOperand();
        RpoNumber spill_block_number = spill_block->rpo_number();
        if (done_moves.find(std::make_pair(
                spill_block_number, range->vreg())) == done_moves.end()) {
          TRACE("Spilling deferred spill for range %d at B%d\n", range->vreg(),
                spill_block_number.ToInt());
          data()->AddGapMove(spill_block->first_instruction_index(),
                             Instruction::GapPosition::START, pred_op,
                             spill_operand);
          done_moves.insert(std::make_pair(spill_block_number, range->vreg()));
          spill_block->mark_needs_frame();
        }
      }
    }
  }
}
References v8::internal::SparseBitVector::Add(), v8::internal::compiler::TopLevelLiveRange::AddBlockRequiringSpillOperand(), v8::internal::compiler::RegisterAllocationData::AddGapMove(), v8::internal::compiler::RegisterAllocationData::code(), code(), v8::internal::SparseBitVector::Contains(), data(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::compiler::InstructionBlock::first_instruction_index(), v8::internal::compiler::RpoNumber::FromInt(), v8::internal::compiler::LiveRange::GetAssignedOperand(), v8::internal::compiler::TopLevelLiveRange::GetChildCovers(), v8::internal::compiler::InstructionSequence::GetInstructionBlock(), v8::internal::compiler::TopLevelLiveRange::GetListOfBlocksRequiringSpillOperands(), v8::internal::compiler::TopLevelLiveRange::GetSpillRangeOperand(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::compiler::LifetimePosition::InstructionFromInstructionIndex(), v8::internal::compiler::InstructionBlock::IsDeferred(), v8::internal::compiler::TopLevelLiveRange::IsSpilledOnlyInDeferredBlocks(), v8::internal::compiler::kRequiresSlot, v8::internal::compiler::InstructionBlock::last_instruction_index(), v8::internal::compiler::InstructionBlock::mark_needs_frame(), v8::internal::compiler::LiveRange::next(), v8::internal::compiler::InstructionBlock::predecessors(), v8::internal::compiler::InstructionBlock::rpo_number(), v8::internal::compiler::LiveRange::spilled(), v8::internal::compiler::RpoNumber::ToInt(), v8::internal::TRACE(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by ResolveControlFlow().
ConnectRanges()
void v8::internal::compiler::LiveRangeConnector::ConnectRanges (Zone * local_zone)
Definition at line 5055 of file register-allocator.cc.
                                                       {
  DelayedInsertionMap delayed_insertion_map(local_zone);
  const size_t live_ranges_size = data()->live_ranges().size();
  for (TopLevelLiveRange* top_range : data()->live_ranges()) {
    CHECK_EQ(live_ranges_size,
             data()->live_ranges().size()); // TODO(neis): crbug.com/831822
    DCHECK_NOT_NULL(top_range);
    bool connect_spilled = top_range->IsSpilledOnlyInDeferredBlocks(data());
    LiveRange* first_range = top_range;
    for (LiveRange *second_range = first_range->next(); second_range != nullptr;
         first_range = second_range, second_range = second_range->next()) {
      LifetimePosition pos = second_range->Start();
      // Add gap move if the two live ranges touch and there is no block
      // boundary.
      if (second_range->spilled()) continue;
      if (first_range->End() != pos) continue;
      if (data()->IsBlockBoundary(pos) &&
          !CanEagerlyResolveControlFlow(GetInstructionBlock(code(), pos))) {
        continue;
      }
      InstructionOperand prev_operand = first_range->GetAssignedOperand();
      InstructionOperand cur_operand = second_range->GetAssignedOperand();
      if (prev_operand.Equals(cur_operand)) continue;
      bool delay_insertion = false;
      Instruction::GapPosition gap_pos;
      int gap_index = pos.ToInstructionIndex();
      if (connect_spilled && !prev_operand.IsAnyRegister() &&
          cur_operand.IsAnyRegister()) {
        const InstructionBlock* block = code()->GetInstructionBlock(gap_index);
        DCHECK(block->IsDeferred());
        // Performing a reload in this block, meaning the spill operand must
        // be defined here.
        top_range->GetListOfBlocksRequiringSpillOperands(data())->Add(
            block->rpo_number().ToInt());
      }
      if (pos.IsGapPosition()) {
        gap_pos = pos.IsStart() ? Instruction::START : Instruction::END;
      } else {
        if (pos.IsStart()) {
          delay_insertion = true;
        } else {
          gap_index++;
        }
        gap_pos = delay_insertion ? Instruction::END : Instruction::START;
      }
      // Reloads or spills for spilled in deferred blocks ranges must happen
      // only in deferred blocks.
      DCHECK_IMPLIES(connect_spilled && !(prev_operand.IsAnyRegister() &&
                                          cur_operand.IsAnyRegister()),
                     code()->GetInstructionBlock(gap_index)->IsDeferred());
      ParallelMove* move =
          code()->InstructionAt(gap_index)->GetOrCreateParallelMove(
              gap_pos, code_zone());
      if (!delay_insertion) {
        move->AddMove(prev_operand, cur_operand);
      } else {
        delayed_insertion_map.insert(
            std::make_pair(std::make_pair(move, prev_operand), cur_operand));
      }
    }
  }
  if (delayed_insertion_map.empty()) return;
  // Insert all the moves which should occur after the stored move.
  ZoneVector<MoveOperands*> to_insert(local_zone);
  ZoneVector<MoveOperands*> to_eliminate(local_zone);
  to_insert.reserve(4);
  to_eliminate.reserve(4);
  ParallelMove* moves = delayed_insertion_map.begin()->first.first;
  for (auto it = delayed_insertion_map.begin();; ++it) {
    bool done = it == delayed_insertion_map.end();
    if (done || it->first.first != moves) {
      // Commit the MoveOperands for current ParallelMove.
      for (MoveOperands* move : to_eliminate) {
        move->Eliminate();
      }
      for (MoveOperands* move : to_insert) {
        moves->push_back(move);
      }
      if (done) break;
      // Reset state.
      to_eliminate.clear();
      to_insert.clear();
      moves = it->first.first;
    }
    // Gather all MoveOperands for a single ParallelMove.
    MoveOperands* move =
        code_zone()->New<MoveOperands>(it->first.second, it->second);
    moves->PrepareInsertAfter(move, &to_eliminate);
    to_insert.push_back(move);
  }
}
References v8::internal::compiler::ParallelMove::AddMove(), CanEagerlyResolveControlFlow(), CHECK_EQ, code(), code_zone(), data(), v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_NOT_NULL, v8::internal::compiler::Instruction::END, v8::internal::compiler::LiveRange::End(), v8::internal::compiler::InstructionOperand::Equals(), v8::internal::compiler::LiveRange::GetAssignedOperand(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetInstructionBlock(), v8::internal::compiler::InstructionSequence::GetInstructionBlock(), v8::internal::compiler::Instruction::GetOrCreateParallelMove(), v8::internal::compiler::InstructionSequence::InstructionAt(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::compiler::InstructionBlock::IsDeferred(), v8::internal::torque::IsDeferred(), v8::internal::compiler::LifetimePosition::IsGapPosition(), v8::internal::compiler::LifetimePosition::IsStart(), v8::internal::compiler::RegisterAllocationData::live_ranges(), v8::internal::Zone::New(), v8::internal::compiler::LiveRange::next(), v8::internal::compiler::ParallelMove::PrepareInsertAfter(), v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::reserve(), v8::internal::compiler::InstructionBlock::rpo_number(), size(), v8::internal::compiler::Instruction::START, v8::internal::compiler::LifetimePosition::Start(), v8::internal::compiler::LifetimePosition::ToInstructionIndex(), and v8::internal::compiler::RpoNumber::ToInt().
Referenced by v8::internal::compiler::turboshaft::ConnectRangesPhase::Run().
data()
RegisterAllocationData* v8::internal::compiler::LiveRangeConnector::data () const [inline], [private]
Definition at line 1759 of file register-allocator.h.
{ return data_; }
References data_.
Referenced by code(), CommitSpillsInDeferredBlocks(), ConnectRanges(), and ResolveControlFlow().
operator=()
LiveRangeConnector& v8::internal::compiler::LiveRangeConnector::operator= (const LiveRangeConnector &) [delete]
ResolveControlFlow() [1/2]
int v8::internal::compiler::LiveRangeConnector::ResolveControlFlow (const InstructionBlock * block, const InstructionOperand & cur_op, const InstructionBlock * pred, const InstructionOperand & pred_op) [private]
Definition at line 5021 of file register-allocator.cc.
                                                                              {
  DCHECK(!pred_op.Equals(cur_op));
  int gap_index;
  Instruction::GapPosition position;
  if (block->PredecessorCount() == 1) {
    gap_index = block->first_instruction_index();
    position = Instruction::START;
  } else {
    Instruction* last = code()->InstructionAt(pred->last_instruction_index());
    // The connecting move might invalidate uses of the destination operand in
    // the deoptimization call. See crbug.com/v8/12218. Omitting the move is
    // safe since the deopt call exits the current code.
    if (last->IsDeoptimizeCall()) {
      return -1;
    }
    // In every other case the last instruction should not participate in
    // register allocation, or it could interfere with the connecting move.
    for (size_t i = 0; i < last->InputCount(); ++i) {
      DCHECK(last->InputAt(i)->IsImmediate());
    }
    DCHECK_EQ(1, pred->SuccessorCount());
    DCHECK(!code()
                ->InstructionAt(pred->last_instruction_index())
                ->HasReferenceMap());
    gap_index = pred->last_instruction_index();
    position = Instruction::END;
  }
  data()->AddGapMove(gap_index, position, pred_op, cur_op);
  return gap_index;
}
References v8::internal::compiler::RegisterAllocationData::AddGapMove(), code(), data(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::Instruction::END, v8::internal::compiler::InstructionOperand::Equals(), v8::internal::compiler::InstructionBlock::first_instruction_index(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::Instruction::InputCount(), v8::internal::compiler::InstructionSequence::InstructionAt(), v8::internal::compiler::Instruction::IsDeoptimizeCall(), v8::internal::compiler::InstructionBlock::last_instruction_index(), v8::internal::compiler::InstructionBlock::PredecessorCount(), v8::internal::compiler::Instruction::START, and v8::internal::compiler::InstructionBlock::SuccessorCount().
ResolveControlFlow() [2/2]
void v8::internal::compiler::LiveRangeConnector::ResolveControlFlow (Zone * local_zone)
Definition at line 4913 of file register-allocator.cc.
                                                            {
  ZoneVector<SparseBitVector*>& live_in_sets = data()->live_in_sets();
  for (const InstructionBlock* block : code()->instruction_blocks()) {
    if (CanEagerlyResolveControlFlow(block)) continue;
    SparseBitVector* live = live_in_sets[block->rpo_number().ToInt()];
    for (int vreg : *live) {
      data()->tick_counter()->TickAndMaybeEnterSafepoint();
      TopLevelLiveRange* live_range = data()->live_ranges()[vreg];
      LifetimePosition cur_start = LifetimePosition::GapFromInstructionIndex(
          block->first_instruction_index());
      LiveRange* cur_range = live_range->GetChildCovers(cur_start);
      DCHECK_NOT_NULL(cur_range);
      if (cur_range->spilled()) continue;
      for (const RpoNumber& pred : block->predecessors()) {
        // Find ranges that may need to be connected.
        const InstructionBlock* pred_block = code()->InstructionBlockAt(pred);
        LifetimePosition pred_end =
            LifetimePosition::InstructionFromInstructionIndex(
                pred_block->last_instruction_index());
        // We don't need to perform the O(log n) search if we already know it
        // will be the same range.
        if (cur_range->CanCover(pred_end)) continue;
        LiveRange* pred_range = live_range->GetChildCovers(pred_end);
        // This search should always succeed because the `vreg` associated to
        // this `live_range` must be live out in all predecessor blocks.
        DCHECK_NOT_NULL(pred_range);
        // Since the `cur_range` did not cover `pred_end` earlier, the found
        // `pred_range` must be different.
        DCHECK_NE(cur_range, pred_range);
        InstructionOperand pred_op = pred_range->GetAssignedOperand();
        InstructionOperand cur_op = cur_range->GetAssignedOperand();
        if (pred_op.Equals(cur_op)) continue;
        if (!pred_op.IsAnyRegister() && cur_op.IsAnyRegister()) {
          // We're doing a reload.
          // We don't need to, if:
          // 1) there's no register use in this block, and
          // 2) the range ends before the block does, and
          // 3) we don't have a successor, or the successor is spilled.
          LifetimePosition block_start =
              LifetimePosition::GapFromInstructionIndex(block->code_start());
          LifetimePosition block_end =
              LifetimePosition::GapFromInstructionIndex(block->code_end());
          // Note that this is not the successor if we have control flow!
          // However, in the following condition, we only refer to it if it
          // begins in the current block, in which case we can safely declare it
          // to be the successor.
          const LiveRange* successor = cur_range->next();
          if (cur_range->End() < block_end &&
              (successor == nullptr || successor->spilled())) {
            // verify point 1: no register use. We can go to the end of the
            // range, since it's all within the block.
            bool uses_reg = false;
            for (UsePosition* const* use_pos_it =
                     cur_range->NextUsePosition(block_start);
                 use_pos_it != cur_range->positions().end(); ++use_pos_it) {
              if ((*use_pos_it)->operand()->IsAnyRegister()) {
                uses_reg = true;
                break;
              }
            }
            if (!uses_reg) continue;
          }
          if (cur_range->TopLevel()->IsSpilledOnlyInDeferredBlocks(data()) &&
              pred_block->IsDeferred()) {
            // The spill location should be defined in pred_block, so add
            // pred_block to the list of blocks requiring a spill operand.
            TRACE("Adding B%d to list of spill blocks for %d\n",
                  pred_block->rpo_number().ToInt(),
                  cur_range->TopLevel()->vreg());
            cur_range->TopLevel()
                ->GetListOfBlocksRequiringSpillOperands(data())
                ->Add(pred_block->rpo_number().ToInt());
          }
        }
        int move_loc = ResolveControlFlow(block, cur_op, pred_block, pred_op);
        USE(move_loc);
        DCHECK_IMPLIES(
            cur_range->TopLevel()->IsSpilledOnlyInDeferredBlocks(data()) &&
                !(pred_op.IsAnyRegister() && cur_op.IsAnyRegister()) &&
                move_loc != -1,
            code()->GetInstructionBlock(move_loc)->IsDeferred());
      }
    }
  }
  // At this stage, we collected blocks needing a spill operand due to reloads
  // from ConnectRanges and from ResolveControlFlow. Time to commit the spills
  // for deferred blocks. This is a convenient time to commit spills for general
  // spill ranges also, because they need to use the LiveRangeFinder.
  const size_t live_ranges_size = data()->live_ranges().size();
  SpillPlacer spill_placer(data(), local_zone);
  for (TopLevelLiveRange* top : data()->live_ranges()) {
    CHECK_EQ(live_ranges_size,
             data()->live_ranges().size()); // TODO(neis): crbug.com/831822
    DCHECK_NOT_NULL(top);
    if (top->IsEmpty()) continue;
    if (top->IsSpilledOnlyInDeferredBlocks(data())) {
      CommitSpillsInDeferredBlocks(top, local_zone);
    } else if (top->HasGeneralSpillRange()) {
      spill_placer.Add(top);
    }
  }
}
References v8::internal::SparseBitVector::Add(), v8::internal::compiler::SpillPlacer::Add(), v8::internal::compiler::LiveRange::CanCover(), CanEagerlyResolveControlFlow(), CHECK_EQ, code(), CommitSpillsInDeferredBlocks(), data(), DCHECK_IMPLIES, DCHECK_NE, DCHECK_NOT_NULL, v8::internal::compiler::LiveRange::End(), v8::internal::compiler::InstructionOperand::Equals(), v8::internal::compiler::LifetimePosition::GapFromInstructionIndex(), v8::internal::compiler::LiveRange::GetAssignedOperand(), v8::internal::compiler::TopLevelLiveRange::GetChildCovers(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetInstructionBlock(), v8::internal::compiler::TopLevelLiveRange::GetListOfBlocksRequiringSpillOperands(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::compiler::LifetimePosition::InstructionFromInstructionIndex(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::compiler::InstructionBlock::IsDeferred(), v8::internal::torque::IsDeferred(), v8::internal::compiler::TopLevelLiveRange::IsSpilledOnlyInDeferredBlocks(), v8::internal::compiler::InstructionBlock::last_instruction_index(), v8::internal::compiler::RegisterAllocationData::live_in_sets(), v8::internal::compiler::RegisterAllocationData::live_ranges(), v8::internal::compiler::LiveRange::next(), v8::internal::compiler::LiveRange::NextUsePosition(), v8::internal::compiler::LiveRange::positions(), v8::internal::compiler::InstructionBlock::rpo_number(), size(), v8::internal::compiler::LiveRange::spilled(), v8::internal::compiler::RegisterAllocationData::tick_counter(), v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), v8::internal::compiler::RpoNumber::ToInt(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), USE, and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by v8::internal::compiler::turboshaft::ResolveControlFlowPhase::Run().
Member Data Documentation
data_
RegisterAllocationData* const v8::internal::compiler::LiveRangeConnector::data_ [private]
Definition at line 1771 of file register-allocator.h.
Referenced by data().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc