v8::internal::LocalHandleScope Class Reference
#include <local-handles.h>
Public Member Functions
LocalHandleScope (LocalIsolate *local_isolate)
LocalHandleScope (LocalHeap *local_heap)
~LocalHandleScope ()
LocalHandleScope (const LocalHandleScope &)=delete
LocalHandleScope & operator= (const LocalHandleScope &)=delete
template<typename T , template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< T >, DirectHandle< T >>) HandleType< T > CloseAndEscape(HandleType< T > handle_value)
Static Public Member Functions
static Address * GetHandle (LocalHeap *local_heap, Address value)
Private Member Functions
void * operator new (size_t size)=delete
void operator delete (void *size_t)=delete
V8_EXPORT_PRIVATE void OpenMainThreadScope (LocalHeap *local_heap)
Static Private Member Functions
static void CloseScope (LocalHeap *local_heap, Address *prev_next, Address *prev_limit)
static V8_EXPORT_PRIVATE void CloseMainThreadScope (LocalHeap *local_heap, Address *prev_next, Address *prev_limit)
static V8_EXPORT_PRIVATE Address * GetMainThreadHandle (LocalHeap *local_heap, Address value)
Private Attributes
LocalHeap * local_heap_
Address * prev_limit_
Address * prev_next_
Detailed Description
Definition at line 44 of file local-handles.h.
Constructor & Destructor Documentation
LocalHandleScope() [1/3]
v8::internal::LocalHandleScope::LocalHandleScope (LocalIsolate * local_isolate) [inline], [explicit]
Definition at line 36 of file local-handles-inl.h.
    : LocalHandleScope(local_isolate->heap()) {}
LocalHandleScope() [2/3]
v8::internal::LocalHandleScope::LocalHandleScope (LocalHeap * local_heap) [inline], [explicit]
Definition at line 39 of file local-handles-inl.h.
                                                        {
  DCHECK(local_heap->IsRunning());
  if (local_heap->is_main_thread()) {
    OpenMainThreadScope(local_heap);
  } else {
    LocalHandles* handles = local_heap->handles();
    local_heap_ = local_heap;
    prev_next_ = handles->scope_.next;
    prev_limit_ = handles->scope_.limit;
    handles->scope_.level++;
  }
}
References v8::internal::DCHECK(), v8::internal::LocalHeap::handles(), v8::internal::LocalHeap::is_main_thread(), v8::internal::LocalHeap::IsRunning(), v8::internal::HandleScopeData::level, v8::internal::HandleScopeData::limit, local_heap_, v8::internal::HandleScopeData::next, OpenMainThreadScope(), prev_limit_, prev_next_, and v8::internal::LocalHandles::scope_.
 LocalHandleScope()
v8::internal::LocalHandleScope::~LocalHandleScope () [inline]
Definition at line 53 of file local-handles-inl.h.
                                    {
  if (local_heap_->is_main_thread()) {
#ifdef V8_ENABLE_CHECKS
    VerifyMainThreadScope();
#endif
    CloseMainThreadScope(local_heap_, prev_next_, prev_limit_);
  } else {
    CloseScope(local_heap_, prev_next_, prev_limit_);
  }
}
References CloseMainThreadScope(), CloseScope(), v8::internal::LocalHeap::is_main_thread(), local_heap_, prev_limit_, and prev_next_.
LocalHandleScope() [3/3]
v8::internal::LocalHandleScope::LocalHandleScope (const LocalHandleScope &) [delete]
Member Function Documentation
CloseMainThreadScope()
void v8::internal::LocalHandleScope::CloseMainThreadScope (LocalHeap * local_heap, Address * prev_next, Address * prev_limit) [static], [private]
Definition at line 34 of file local-handles.cc.
                                                                 {
  Isolate* isolate = local_heap->heap()->isolate();
  HandleScope::CloseScope(isolate, prev_next, prev_limit);
}
References v8::internal::HandleScope::CloseScope(), v8::internal::LocalHeap::heap(), and v8::internal::Heap::isolate().
Referenced by ~LocalHandleScope().
CloseScope()
void v8::internal::LocalHandleScope::CloseScope (LocalHeap * local_heap, Address * prev_next, Address * prev_limit) [inline], [static], [private]
Definition at line 91 of file local-handles-inl.h.
                                                       {
  LocalHandles* handles = local_heap->handles();
  Address* old_limit = handles->scope_.limit;
  handles->scope_.next = prev_next;
  handles->scope_.limit = prev_limit;
  handles->scope_.level--;
  if (old_limit != handles->scope_.limit) {
    handles->RemoveUnusedBlocks();
    old_limit = handles->scope_.limit;
  }
#ifdef ENABLE_LOCAL_HANDLE_ZAPPING
  LocalHandles::ZapRange(handles->scope_.next, old_limit);
#endif
  MSAN_ALLOCATED_UNINITIALIZED_MEMORY(
      handles->scope_.next,
      static_cast<size_t>(reinterpret_cast<Address>(old_limit) -
                          reinterpret_cast<Address>(handles->scope_.next)));
}
References v8::internal::LocalHeap::handles(), v8::internal::HandleScopeData::level, v8::internal::HandleScopeData::limit, MSAN_ALLOCATED_UNINITIALIZED_MEMORY, v8::internal::HandleScopeData::next, v8::internal::LocalHandles::RemoveUnusedBlocks(), and v8::internal::LocalHandles::scope_.
Referenced by ~LocalHandleScope().
GetHandle()
Address * v8::internal::LocalHandleScope::GetHandle (LocalHeap * local_heap, Address value) [inline], [static]
Definition at line 19 of file local-handles-inl.h.
                                                              {
  DCHECK(local_heap->IsRunning());
  if (local_heap->is_main_thread())
    return LocalHandleScope::GetMainThreadHandle(local_heap, value);
  LocalHandles* handles = local_heap->handles();
  Address* result = handles->scope_.next;
  if (result == handles->scope_.limit) {
    result = handles->AddBlock();
  }
  DCHECK_LT(result, handles->scope_.limit);
  handles->scope_.next++;
  *result = value;
  return result;
}
References v8::internal::LocalHandles::AddBlock(), v8::internal::DCHECK(), DCHECK_LT, GetMainThreadHandle(), v8::internal::LocalHeap::handles(), v8::internal::LocalHeap::is_main_thread(), v8::internal::LocalHeap::IsRunning(), v8::internal::HandleScopeData::limit, v8::internal::HandleScopeData::next, v8::base::internal::result, v8::internal::LocalHandles::scope_, and v8::internal::value.
GetMainThreadHandle()
Address * v8::internal::LocalHandleScope::GetMainThreadHandle (LocalHeap * local_heap, Address value) [static], [private]
Definition at line 16 of file local-handles.cc.
                                                              {
  Isolate* isolate = local_heap->heap()->isolate();
  return HandleScope::CreateHandle(isolate, value);
}
References v8::internal::HandleScope::CreateHandle(), v8::internal::LocalHeap::heap(), v8::internal::Heap::isolate(), and v8::internal::value.
Referenced by GetHandle().
OpenMainThreadScope()
void v8::internal::LocalHandleScope::OpenMainThreadScope (LocalHeap * local_heap) [private]
Definition at line 22 of file local-handles.cc.
                                                                {
  Isolate* isolate = local_heap->heap()->isolate();
  HandleScopeData* data = isolate->handle_scope_data();
  local_heap_ = local_heap;
  prev_next_ = data->next;
  prev_limit_ = data->limit;
  data->level++;
#ifdef V8_ENABLE_CHECKS
  scope_level_ = data->level;
#endif
}
References v8::internal::Isolate::handle_scope_data(), v8::internal::LocalHeap::heap(), v8::internal::Heap::isolate(), v8::internal::HandleScopeData::level, v8::internal::HandleScopeData::limit, local_heap_, v8::internal::HandleScopeData::next, prev_limit_, and prev_next_.
Referenced by LocalHandleScope().
operator delete()
void v8::internal::LocalHandleScope::operator delete (void * size_t) [private], [delete]
operator new()
void* v8::internal::LocalHandleScope::operator new (size_t size) [private], [delete]
operator=()
LocalHandleScope& v8::internal::LocalHandleScope::operator= (const LocalHandleScope &) [delete]
requires()
template<typename T , template< typename > typename HandleType>
v8::internal::LocalHandleScope::requires (std::is_convertible_v< HandleType< T >, DirectHandle< T >>)
Member Data Documentation
local_heap_
LocalHeap* v8::internal::LocalHandleScope::local_heap_ [private]
Definition at line 80 of file local-handles.h.
Referenced by LocalHandleScope(), OpenMainThreadScope(), and ~LocalHandleScope().
prev_limit_
Address* v8::internal::LocalHandleScope::prev_limit_ [private]
Definition at line 81 of file local-handles.h.
Referenced by LocalHandleScope(), OpenMainThreadScope(), and ~LocalHandleScope().
prev_next_
Address* v8::internal::LocalHandleScope::prev_next_ [private]
Definition at line 82 of file local-handles.h.
Referenced by LocalHandleScope(), OpenMainThreadScope(), and ~LocalHandleScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/local-handles.h
/mnt/V8SourceCode/src/handles/local-handles-inl.h
/mnt/V8SourceCode/src/handles/local-handles.cc