v8::internal::MinorMarkSweepCollector Class Reference
#include <minor-mark-sweep.h>
Public Member Functions
MinorMarkSweepCollector (Heap *heap)
~MinorMarkSweepCollector ()
void TearDown ()
void CollectGarbage ()
void StartMarking (bool force_use_background_threads)
void RequestGC ()
EphemeronRememberedSet::TableList * ephemeron_table_list () const
MarkingWorklists * marking_worklists ()
MarkingWorklists::Local * local_marking_worklists ()
YoungGenerationRememberedSetsMarkingWorklist * remembered_sets_marking_handler ()
YoungGenerationMainMarkingVisitor * main_marking_visitor ()
bool is_in_atomic_pause () const
bool gc_finalization_requsted () const
bool UseBackgroundThreadsInCycle () const
void DrainMarkingWorklistForTesting ()
Static Public Attributes
static constexpr size_t kMaxParallelTasks = 8
Private Types
using ResizeNewSpaceMode = Heap::ResizeNewSpaceMode
Private Member Functions
Sweeper * sweeper ()
void MarkLiveObjects ()
void MarkRoots (YoungGenerationRootMarkingVisitor &root_visitor, bool was_marked_incrementally)
V8_EXPORT_PRIVATE void DrainMarkingWorklist ()
void MarkRootsFromTracedHandles (YoungGenerationRootMarkingVisitor &root_visitor)
void MarkRootsFromConservativeStack (YoungGenerationRootMarkingVisitor &root_visitor)
void EvacuateExternalPointerReferences (MutablePageMetadata *p)
void TraceFragmentation ()
void ClearNonLiveReferences ()
void FinishConcurrentMarking ()
void PerformWrapperTracing ()
void Sweep ()
bool StartSweepNewSpace ()
void StartSweepNewSpaceWithStickyBits ()
bool SweepNewLargeSpace ()
void Finish ()
Private Attributes
Heap *const heap_
std::unique_ptr< MarkingWorklists > marking_worklists_
std::unique_ptr< EphemeronRememberedSet::TableList > ephemeron_table_list_
std::unique_ptr< YoungGenerationMainMarkingVisitor > main_marking_visitor_
MarkingState *const marking_state_
NonAtomicMarkingState *const non_atomic_marking_state_
Sweeper *const sweeper_
std::unique_ptr< PretenuringHandler::PretenuringFeedbackMap > pretenuring_feedback_
std::unique_ptr< YoungGenerationRememberedSetsMarkingWorklist > remembered_sets_marking_handler_
std::optional< bool > use_background_threads_in_cycle_
std::atomic< bool > is_in_atomic_pause_ {false}
std::atomic< bool > gc_finalization_requested_ {false}
Friends
class IncrementalMarking
Detailed Description
Definition at line 148 of file minor-mark-sweep.h.
Member Typedef Documentation
ResizeNewSpaceMode
using v8::internal::MinorMarkSweepCollector::ResizeNewSpaceMode = Heap::ResizeNewSpaceMode [private]
Definition at line 196 of file minor-mark-sweep.h.
Constructor & Destructor Documentation
MinorMarkSweepCollector()
v8::internal::MinorMarkSweepCollector::MinorMarkSweepCollector (Heap * heap) [explicit]
Definition at line 286 of file minor-mark-sweep.cc.
    : heap_(heap),
      marking_state_(heap_->marking_state()),
      non_atomic_marking_state_(heap_->non_atomic_marking_state()),
      sweeper_(heap_->sweeper()) {}
 MinorMarkSweepCollector()
v8::internal::MinorMarkSweepCollector::~MinorMarkSweepCollector () [default]
Member Function Documentation
ClearNonLiveReferences()
void v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences () [private]
Definition at line 506 of file minor-mark-sweep.cc.
                                                     {
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MINOR_MS_CLEAR);
  if (V8_UNLIKELY(v8_flags.always_use_string_forwarding_table)) {
    TRACE_GC(heap_->tracer(),
             GCTracer::Scope::MINOR_MS_CLEAR_STRING_FORWARDING_TABLE);
    // Clear non-live objects in the string fowarding table.
    YoungStringForwardingTableCleaner forwarding_table_cleaner(heap_);
    forwarding_table_cleaner.ProcessYoungObjects();
  }
  Heap::ExternalStringTable& external_string_table =
      heap_->external_string_table_;
  if (external_string_table.HasYoung()) {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MINOR_MS_CLEAR_STRING_TABLE);
    // Internalized strings are always stored in old space, so there is no
    // need to clean them here.
    ExternalStringTableCleanerVisitor<
        ExternalStringTableCleaningMode::kYoungOnly>
        external_visitor(heap_);
    external_string_table.IterateYoung(&external_visitor);
    external_string_table.CleanUpYoung();
  }
  Isolate* isolate = heap_->isolate();
  if (isolate->global_handles()->HasYoung() ||
      isolate->traced_handles()->HasYoung()) {
    TRACE_GC(heap_->tracer(),
             GCTracer::Scope::MINOR_MS_CLEAR_WEAK_GLOBAL_HANDLES);
    isolate->global_handles()->ProcessWeakYoungObjects(
        nullptr, &IsUnmarkedObjectInYoungGeneration);
    if (auto* cpp_heap = CppHeap::From(heap_->cpp_heap_);
        cpp_heap && cpp_heap->generational_gc_supported()) {
      isolate->traced_handles()->ResetYoungDeadNodes(
          &IsUnmarkedObjectInYoungGeneration);
    } else {
      isolate->traced_handles()->ProcessWeakYoungObjects(
          nullptr, &IsUnmarkedObjectInYoungGeneration);
    }
  }
  // Clear ephemeron entries from EphemeronHashTables in the young generation
  // whenever the entry has a dead young generation key.
  //
  // Worklist is collected during marking.
  {
    DCHECK_NOT_NULL(ephemeron_table_list_);
    EphemeronRememberedSet::TableList::Local local_ephemeron_table_list(
        *ephemeron_table_list_);
    Tagged<EphemeronHashTable> table;
    while (local_ephemeron_table_list.Pop(&table)) {
      for (InternalIndex i : table->IterateEntries()) {
        // Keys in EphemeronHashTables must be heap objects.
        HeapObjectSlot key_slot(
            table->RawFieldOfElementAt(EphemeronHashTable::EntryToIndex(i)));
        Tagged<HeapObject> key = key_slot.ToHeapObject();
        if (HeapLayout::InYoungGeneration(key) &&
            non_atomic_marking_state_->IsUnmarked(key)) {
          table->RemoveEntry(i);
        }
      }
    }
  }
  ephemeron_table_list_.reset();
  // Clear ephemeron entries from EphemeronHashTables in the old generation
  // whenever the entry has a dead young generation key.
  //
  // Does not need to be iterated as roots but is maintained in the GC to avoid
  // treating keys as strong. The set is populated from the write barrier and
  // the sweeper during promoted pages iteration.
  auto* table_map = heap_->ephemeron_remembered_set()->tables();
  for (auto it = table_map->begin(); it != table_map->end();) {
    Tagged<EphemeronHashTable> table = it->first;
    auto& indices = it->second;
    for (auto iti = indices.begin(); iti != indices.end();) {
      // Keys in EphemeronHashTables must be heap objects.
      HeapObjectSlot key_slot(table->RawFieldOfElementAt(
          EphemeronHashTable::EntryToIndex(InternalIndex(*iti))));
      Tagged<HeapObject> key = key_slot.ToHeapObject();
      // There may be old generation entries left in the remembered set as
      // MinorMS only promotes pages after clearing non-live references.
      if (!HeapLayout::InYoungGeneration(key)) {
        iti = indices.erase(iti);
      } else if (non_atomic_marking_state_->IsUnmarked(key)) {
        table->RemoveEntry(InternalIndex(*iti));
        iti = indices.erase(iti);
      } else {
        ++iti;
      }
    }
    if (indices.empty()) {
      it = table_map->erase(it);
    } else {
      ++it;
    }
  }
}
References v8::internal::Heap::ExternalStringTable::CleanUpYoung(), v8::internal::Heap::cpp_heap_, DCHECK_NOT_NULL, v8::internal::Heap::ephemeron_remembered_set(), ephemeron_table_list_, v8::internal::Heap::external_string_table_, v8::internal::CppHeap::From(), cppgc::internal::HeapBase::generational_gc_supported(), v8::internal::Isolate::global_handles(), v8::internal::GlobalHandles::HasYoung(), v8::internal::TracedHandles::HasYoung(), v8::internal::Heap::ExternalStringTable::HasYoung(), heap_, v8::internal::HeapLayout::InYoungGeneration(), v8::internal::Heap::isolate(), v8::internal::MarkingStateBase< ConcreteState, access_mode >::IsUnmarked(), v8::internal::anonymous_namespace{minor-mark-sweep.cc}::IsUnmarkedObjectInYoungGeneration(), v8::internal::Heap::ExternalStringTable::IterateYoung(), v8::internal::key, v8::internal::kYoungOnly, non_atomic_marking_state_, heap::base::Worklist< EntryType, MinSegmentSize >::Local::Pop(), v8::internal::GlobalHandles::ProcessWeakYoungObjects(), v8::internal::TracedHandles::ProcessWeakYoungObjects(), v8::internal::TracedHandles::ResetYoungDeadNodes(), v8::internal::EphemeronRememberedSet::tables(), v8::internal::FullHeapObjectSlot::ToHeapObject(), TRACE_GC, v8::internal::Isolate::traced_handles(), v8::internal::Heap::tracer(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by CollectGarbage().
CollectGarbage()
void v8::internal::MinorMarkSweepCollector::CollectGarbage ()
Definition at line 414 of file minor-mark-sweep.cc.
                                             {
  DCHECK(!heap_->mark_compact_collector()->in_use());
  DCHECK(heap_->use_new_space());
  DCHECK(!heap_->array_buffer_sweeper()->sweeping_in_progress());
  DCHECK(!sweeper()->AreMinorSweeperTasksRunning());
  if (v8_flags.sticky_mark_bits) {
    DCHECK(sweeper()->IsSweepingDoneForSpace(OLD_SPACE));
  } else {
    DCHECK(sweeper()->IsSweepingDoneForSpace(NEW_SPACE));
  }
  heap_->new_lo_space()->ResetPendingObject();
  is_in_atomic_pause_.store(true, std::memory_order_relaxed);
  MarkLiveObjects();
  if (auto* cpp_heap = CppHeap::From(heap_->cpp_heap_)) {
    cpp_heap->ProcessCrossThreadWeakness();
  }
  ClearNonLiveReferences();
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap) {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MINOR_MS_MARK_VERIFY);
    YoungGenerationMarkingVerifier verifier(heap_);
    verifier.Run();
  }
#endif // VERIFY_HEAP
  if (auto* cpp_heap = CppHeap::From(heap_->cpp_heap_)) {
    cpp_heap->FinishMarkingAndProcessWeakness();
  }
  Sweep();
  Finish();
  auto* isolate = heap_->isolate();
  isolate->global_handles()->UpdateListOfYoungNodes();
  isolate->traced_handles()->UpdateListOfYoungNodes();
  isolate->stack_guard()->ClearGC();
  gc_finalization_requested_.store(false, std::memory_order_relaxed);
  is_in_atomic_pause_.store(false, std::memory_order_relaxed);
}
References v8::internal::Heap::array_buffer_sweeper(), ClearNonLiveReferences(), v8::internal::Heap::cpp_heap_, v8::internal::DCHECK(), Finish(), v8::internal::CppHeap::From(), gc_finalization_requested_, v8::internal::Isolate::global_handles(), heap_, is_in_atomic_pause_, v8::internal::Heap::isolate(), v8::internal::Heap::mark_compact_collector(), MarkLiveObjects(), v8::internal::Heap::new_lo_space(), v8::internal::NEW_SPACE, v8::internal::OLD_SPACE, v8::internal::LargeObjectSpace::ResetPendingObject(), Sweep(), sweeper(), v8::internal::ArrayBufferSweeper::sweeping_in_progress(), TRACE_GC, v8::internal::Heap::tracer(), v8::internal::GlobalHandles::UpdateListOfYoungNodes(), v8::internal::Heap::use_new_space(), and v8::internal::v8_flags.
DrainMarkingWorklist()
void v8::internal::MinorMarkSweepCollector::DrainMarkingWorklist () [private]
Definition at line 782 of file minor-mark-sweep.cc.
                                                   {
  PtrComprCageBase cage_base(heap_->isolate());
  YoungGenerationRememberedSetsMarkingWorklist::Local remembered_sets(
      remembered_sets_marking_handler_.get());
  auto* marking_worklists_local = local_marking_worklists();
  do {
    marking_worklists_local->MergeOnHold();
    PerformWrapperTracing();
    Tagged<HeapObject> heap_object;
    while (marking_worklists_local->Pop(&heap_object)) {
      DCHECK(!IsFreeSpaceOrFiller(heap_object, cage_base));
      DCHECK(IsHeapObject(heap_object));
      DCHECK(heap_->Contains(heap_object));
      DCHECK(!marking_state_->IsUnmarked(heap_object));
      // Maps won't change in the atomic pause, so the map can be read without
      // atomics.
      Tagged<Map> map = Cast<Map>(*heap_object->map_slot());
      const auto visited_size = main_marking_visitor_->Visit(map, heap_object);
      if (visited_size) {
        main_marking_visitor_->IncrementLiveBytesCached(
            MutablePageMetadata::FromHeapObject(heap_object),
            ALIGN_TO_ALLOCATION_ALIGNMENT(visited_size));
      }
    }
  } while (remembered_sets.ProcessNextItem(main_marking_visitor_.get()) ||
           !IsCppHeapMarkingFinished(heap_, marking_worklists_local));
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::Heap::Contains(), v8::internal::DCHECK(), v8::internal::MutablePageMetadata::FromHeapObject(), heap_, v8::internal::IsCppHeapMarkingFinished(), v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller(), v8::internal::IsHeapObject(), v8::internal::Heap::isolate(), v8::internal::MarkingStateBase< ConcreteState, access_mode >::IsUnmarked(), local_marking_worklists(), main_marking_visitor_, marking_state_, PerformWrapperTracing(), v8::internal::YoungGenerationRememberedSetsMarkingWorklist::Local::ProcessNextItem(), and remembered_sets_marking_handler_.
Referenced by DrainMarkingWorklistForTesting(), and MarkLiveObjects().
DrainMarkingWorklistForTesting()
void v8::internal::MinorMarkSweepCollector::DrainMarkingWorklistForTesting () [inline]
Definition at line 193 of file minor-mark-sweep.h.
{ DrainMarkingWorklist(); }
References DrainMarkingWorklist().
ephemeron_table_list()
EphemeronRememberedSet::TableList* v8::internal::MinorMarkSweepCollector::ephemeron_table_list () const [inline]
Definition at line 161 of file minor-mark-sweep.h.
                                                                {
    return ephemeron_table_list_.get();
  }
References ephemeron_table_list_.
EvacuateExternalPointerReferences()
void v8::internal::MinorMarkSweepCollector::EvacuateExternalPointerReferences (MutablePageMetadata * p) [private]
Definition at line 905 of file minor-mark-sweep.cc.
                            {
#ifdef V8_COMPRESS_POINTERS
  using BasicSlotSet = ::heap::base::BasicSlotSet<kTaggedSize>;
  BasicSlotSet* slots = p->slot_set<SURVIVOR_TO_EXTERNAL_POINTER>();
  if (!slots) return;
  ExternalPointerTable& table = heap_->isolate()->external_pointer_table();
  ExternalPointerTable::Space* young = heap_->young_external_pointer_space();
  ExternalPointerTable::Space* old = heap_->old_external_pointer_space();
  auto callback = [&table, young, old](Address handle_location) {
    ExternalPointerHandle handle =
        *reinterpret_cast<ExternalPointerHandle*>(handle_location);
    table.Evacuate(young, old, handle, handle_location,
                   ExternalPointerTable::EvacuateMarkMode::kClearMark);
    return KEEP_SLOT;
  };
  auto slot_count = slots->Iterate<BasicSlotSet::AccessMode::NON_ATOMIC>(
      p->ChunkAddress(), 0, p->BucketsInSlotSet(), callback,
      BasicSlotSet::EmptyBucketMode::FREE_EMPTY_BUCKETS);
  DCHECK(slot_count);
  USE(slot_count);
  // SURVIVOR_TO_EXTERNAL_POINTER remembered set will be freed later by the
  // sweeper.
#endif
}
References v8::internal::MutablePageMetadata::BucketsInSlotSet(), v8::internal::MemoryChunkMetadata::ChunkAddress(), v8::internal::DCHECK(), v8::internal::handle(), heap_, v8::internal::Heap::isolate(), heap::base::KEEP_SLOT, v8::internal::MutablePageMetadata::slot_set(), v8::internal::SURVIVOR_TO_EXTERNAL_POINTER, and USE.
Referenced by StartSweepNewSpace(), and SweepNewLargeSpace().
Finish()
void v8::internal::MinorMarkSweepCollector::Finish () [private]
Definition at line 399 of file minor-mark-sweep.cc.
                                     {
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MINOR_MS_FINISH);
  use_background_threads_in_cycle_.reset();
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MINOR_MS_FINISH_ENSURE_CAPACITY);
    heap_->ResizeNewSpace();
  }
  if (!v8_flags.sticky_mark_bits) {
    heap_->new_space()->GarbageCollectionEpilogue();
  }
}
References v8::internal::NewSpace::GarbageCollectionEpilogue(), heap_, v8::internal::Heap::new_space(), v8::internal::Heap::ResizeNewSpace(), TRACE_GC, v8::internal::Heap::tracer(), use_background_threads_in_cycle_, and v8::internal::v8_flags.
Referenced by CollectGarbage().
FinishConcurrentMarking()
void v8::internal::MinorMarkSweepCollector::FinishConcurrentMarking () [private]
Definition at line 315 of file minor-mark-sweep.cc.
                                                      {
  if (v8_flags.concurrent_minor_ms_marking || v8_flags.parallel_marking) {
    DCHECK_IMPLIES(!heap_->concurrent_marking()->IsStopped(),
                   heap_->concurrent_marking()->garbage_collector() ==
                       GarbageCollector::MINOR_MARK_SWEEPER);
    heap_->concurrent_marking()->Join();
    heap_->concurrent_marking()->FlushPretenuringFeedback();
  }
  CHECK(heap_->concurrent_marking()->IsStopped());
  heap_->tracer()->SampleConcurrencyEsimate(
      heap_->concurrent_marking()->FetchAndResetConcurrencyEstimate());
  if (auto* cpp_heap = CppHeap::From(heap_->cpp_heap_)) {
    cpp_heap->FinishConcurrentMarkingIfNeeded();
  }
}
References CHECK, v8::internal::Heap::concurrent_marking(), v8::internal::Heap::cpp_heap_, DCHECK_IMPLIES, v8::internal::ConcurrentMarking::FetchAndResetConcurrencyEstimate(), v8::internal::ConcurrentMarking::FlushPretenuringFeedback(), v8::internal::CppHeap::From(), v8::internal::ConcurrentMarking::garbage_collector(), heap_, v8::internal::ConcurrentMarking::IsStopped(), v8::internal::ConcurrentMarking::Join(), v8::internal::MINOR_MARK_SWEEPER, v8::internal::GCTracer::SampleConcurrencyEsimate(), v8::internal::Heap::tracer(), and v8::internal::v8_flags.
Referenced by MarkLiveObjects().
gc_finalization_requsted()
bool v8::internal::MinorMarkSweepCollector::gc_finalization_requsted () const [inline]
Definition at line 185 of file minor-mark-sweep.h.
                                        {
    return gc_finalization_requested_.load(std::memory_order_relaxed);
  }
References gc_finalization_requested_.
is_in_atomic_pause()
bool v8::internal::MinorMarkSweepCollector::is_in_atomic_pause () const [inline]
Definition at line 181 of file minor-mark-sweep.h.
                                  {
    return is_in_atomic_pause_.load(std::memory_order_relaxed);
  }
References is_in_atomic_pause_.
Referenced by RequestGC(), and v8::internal::ConcurrentMarking::RunMinor().
local_marking_worklists()
MarkingWorklists::Local* v8::internal::MinorMarkSweepCollector::local_marking_worklists () [inline]
Definition at line 167 of file minor-mark-sweep.h.
                                                   {
    return &main_marking_visitor_->marking_worklists_local();
  }
References main_marking_visitor_.
Referenced by DrainMarkingWorklist(), MarkLiveObjects(), MarkRootsFromTracedHandles(), PerformWrapperTracing(), v8::internal::ConcurrentMarking::RescheduleJobIfNeeded(), v8::internal::IncrementalMarking::StartMarkingMinor(), and v8::internal::ConcurrentMarking::TryScheduleJob().
main_marking_visitor()
YoungGenerationMainMarkingVisitor* v8::internal::MinorMarkSweepCollector::main_marking_visitor () [inline]
Definition at line 177 of file minor-mark-sweep.h.
                                                            {
    return main_marking_visitor_.get();
  }
References main_marking_visitor_.
marking_worklists()
MarkingWorklists* v8::internal::MinorMarkSweepCollector::marking_worklists () [inline]
Definition at line 165 of file minor-mark-sweep.h.
{ return marking_worklists_.get(); }
References marking_worklists_.
Referenced by v8::internal::MarkingBarrier::Activate(), and v8::internal::ConcurrentMarking::TryScheduleJob().
MarkLiveObjects()
void v8::internal::MinorMarkSweepCollector::MarkLiveObjects () [private]
Definition at line 703 of file minor-mark-sweep.cc.
                                              {
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MINOR_MS_MARK);
  const bool was_marked_incrementally =
      !heap_->incremental_marking()->IsStopped();
  if (!was_marked_incrementally) {
    StartMarking(false);
  } else {
    auto* incremental_marking = heap_->incremental_marking();
    TRACE_GC_WITH_FLOW(
        heap_->tracer(), GCTracer::Scope::MINOR_MS_MARK_FINISH_INCREMENTAL,
        incremental_marking->current_trace_id(), TRACE_EVENT_FLAG_FLOW_IN);
    DCHECK(incremental_marking->IsMinorMarking());
    DCHECK(v8_flags.concurrent_minor_ms_marking);
    incremental_marking->Stop();
    MarkingBarrier::PublishYoung(heap_);
  }
  DCHECK_NOT_NULL(marking_worklists_);
  DCHECK_NOT_NULL(main_marking_visitor_);
  YoungGenerationRootMarkingVisitor root_visitor(this);
  MarkRoots(root_visitor, was_marked_incrementally);
  // CppGC starts parallel marking tasks that will trace TracedReferences.
  if (auto* cpp_heap = CppHeap::From(heap_->cpp_heap())) {
    cpp_heap->EnterFinalPause(heap_->embedder_stack_state_);
  }
  {
    // Mark the transitive closure in parallel.
    TRACE_GC_ARG1(heap_->tracer(),
                  GCTracer::Scope::MINOR_MS_MARK_CLOSURE_PARALLEL,
                  "UseBackgroundThreads", UseBackgroundThreadsInCycle());
    if (v8_flags.parallel_marking) {
      heap_->concurrent_marking()->RescheduleJobIfNeeded(
          GarbageCollector::MINOR_MARK_SWEEPER, TaskPriority::kUserBlocking);
    }
    DrainMarkingWorklist();
    FinishConcurrentMarking();
  }
  {
    TRACE_GC(heap_->tracer(),
             GCTracer::Scope::MINOR_MS_MARK_CONSERVATIVE_STACK);
    MarkRootsFromConservativeStack(root_visitor);
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MINOR_MS_MARK_CLOSURE);
    if (auto* cpp_heap = CppHeap::From(heap_->cpp_heap())) {
      cpp_heap->EnterProcessGlobalAtomicPause();
    }
    DrainMarkingWorklist();
  }
  CHECK(local_marking_worklists()->IsEmpty());
  if (was_marked_incrementally) {
    // Disable the marking barrier after concurrent/parallel marking has
    // finished as it will reset page flags.
    Sweeper::PauseMajorSweepingScope pause_sweeping_scope(heap_->sweeper());
    MarkingBarrier::DeactivateYoung(heap_);
  }
  main_marking_visitor_.reset();
  marking_worklists_.reset();
  remembered_sets_marking_handler_.reset();
  PretenuringHandler* pretenuring_handler = heap_->pretenuring_handler();
  pretenuring_handler->MergeAllocationSitePretenuringFeedback(
      *pretenuring_feedback_);
  pretenuring_feedback_.reset();
  if (v8_flags.minor_ms_trace_fragmentation) {
    TraceFragmentation();
  }
}
References CHECK, v8::internal::Heap::concurrent_marking(), v8::internal::Heap::cpp_heap(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::MarkingBarrier::DeactivateYoung(), DrainMarkingWorklist(), v8::internal::Heap::embedder_stack_state_, FinishConcurrentMarking(), v8::internal::CppHeap::From(), heap_, v8::internal::Heap::incremental_marking(), v8::internal::IncrementalMarking::IsStopped(), v8::kUserBlocking, local_marking_worklists(), main_marking_visitor_, marking_worklists_, MarkRoots(), MarkRootsFromConservativeStack(), v8::internal::PretenuringHandler::MergeAllocationSitePretenuringFeedback(), v8::internal::MINOR_MARK_SWEEPER, pretenuring_feedback_, v8::internal::Heap::pretenuring_handler(), v8::internal::MarkingBarrier::PublishYoung(), remembered_sets_marking_handler_, v8::internal::ConcurrentMarking::RescheduleJobIfNeeded(), StartMarking(), v8::internal::Heap::sweeper(), TRACE_EVENT_FLAG_FLOW_IN, TRACE_GC, TRACE_GC_ARG1, TRACE_GC_WITH_FLOW, TraceFragmentation(), v8::internal::Heap::tracer(), UseBackgroundThreadsInCycle(), and v8::internal::v8_flags.
Referenced by CollectGarbage().
MarkRoots()
void v8::internal::MinorMarkSweepCollector::MarkRoots (YoungGenerationRootMarkingVisitor & root_visitor, bool was_marked_incrementally) [private]
Definition at line 642 of file minor-mark-sweep.cc.
                                   {
  Isolate* isolate = heap_->isolate();
  // Seed the root set.
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MINOR_MS_MARK_SEED);
    isolate->traced_handles()->ComputeWeaknessForYoungObjects();
    // MinorMS treats all weak roots except for global handles as strong.
    // That is why we don't set skip_weak = true here and instead visit
    // global handles separately.
    heap_->IterateRoots(
        &root_visitor,
        base::EnumSet<SkipRoot>{
            SkipRoot::kExternalStringTable, SkipRoot::kGlobalHandles,
            SkipRoot::kTracedHandles, SkipRoot::kOldGeneration,
            SkipRoot::kReadOnlyBuiltins, SkipRoot::kConservativeStack});
    isolate->global_handles()->IterateYoungStrongAndDependentRoots(
        &root_visitor);
    MarkRootsFromTracedHandles(root_visitor);
  }
}
References v8::internal::TracedHandles::ComputeWeaknessForYoungObjects(), v8::internal::Isolate::global_handles(), heap_, v8::internal::Heap::isolate(), v8::internal::Heap::IterateRoots(), v8::internal::GlobalHandles::IterateYoungStrongAndDependentRoots(), v8::internal::kConservativeStack, v8::internal::kExternalStringTable, v8::internal::kGlobalHandles, v8::internal::kOldGeneration, v8::internal::kReadOnlyBuiltins, v8::internal::kTracedHandles, MarkRootsFromTracedHandles(), TRACE_GC, v8::internal::Isolate::traced_handles(), and v8::internal::Heap::tracer().
Referenced by MarkLiveObjects().
MarkRootsFromConservativeStack()
void v8::internal::MinorMarkSweepCollector::MarkRootsFromConservativeStack (YoungGenerationRootMarkingVisitor & root_visitor) [private]
Definition at line 692 of file minor-mark-sweep.cc.
                                                     {
  if (!heap_->IsGCWithStack()) return;
  TRACE_GC(heap_->tracer(), GCTracer::Scope::CONSERVATIVE_STACK_SCANNING);
  MinorMSConservativeStackVisitor stack_visitor(heap_->isolate(), root_visitor);
  heap_->IterateConservativeStackRoots(&stack_visitor,
                                       Heap::StackScanMode::kFull);
}
References heap_, v8::internal::Heap::IsGCWithStack(), v8::internal::Heap::isolate(), v8::internal::Heap::IterateConservativeStackRoots(), v8::internal::Heap::kFull, TRACE_GC, and v8::internal::Heap::tracer().
Referenced by MarkLiveObjects().
MarkRootsFromTracedHandles()
void v8::internal::MinorMarkSweepCollector::MarkRootsFromTracedHandles (YoungGenerationRootMarkingVisitor & root_visitor) [private]
Definition at line 622 of file minor-mark-sweep.cc.
                                                     {
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MINOR_MS_MARK_TRACED_HANDLES);
  if (auto* cpp_heap = CppHeap::From(heap_->cpp_heap_);
      cpp_heap && cpp_heap->generational_gc_supported()) {
    // Visit the Oilpan-to-V8 remembered set.
    heap_->isolate()->traced_handles()->IterateAndMarkYoungRootsWithOldHosts(
        &root_visitor);
    // Visit the V8-to-Oilpan remembered set.
    cpp_heap->VisitCrossHeapRememberedSetIfNeeded(
        [this](Tagged<CppHeapPointerWrapperObjectT> obj) {
          VisitObjectWithCppHeapPointerField(heap_->isolate(), obj,
                                             *local_marking_worklists());
        });
  } else {
    // Otherwise, visit all young roots.
    heap_->isolate()->traced_handles()->IterateYoungRoots(&root_visitor);
  }
}
References v8::internal::Heap::cpp_heap_, v8::internal::CppHeap::From(), cppgc::internal::HeapBase::generational_gc_supported(), heap_, v8::internal::Heap::isolate(), v8::internal::TracedHandles::IterateAndMarkYoungRootsWithOldHosts(), v8::internal::TracedHandles::IterateYoungRoots(), local_marking_worklists(), TRACE_GC, v8::internal::Isolate::traced_handles(), v8::internal::Heap::tracer(), and v8::internal::anonymous_namespace{minor-mark-sweep.cc}::VisitObjectWithCppHeapPointerField().
Referenced by MarkRoots().
PerformWrapperTracing()
void v8::internal::MinorMarkSweepCollector::PerformWrapperTracing () [private]
Definition at line 292 of file minor-mark-sweep.cc.
                                                    {
  auto* cpp_heap = CppHeap::From(heap_->cpp_heap_);
  if (!cpp_heap) return;
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MINOR_MS_MARK_EMBEDDER_TRACING);
  local_marking_worklists()->PublishCppHeapObjects();
  cpp_heap->AdvanceMarking(v8::base::TimeDelta::Max(), SIZE_MAX);
}
References v8::internal::Heap::cpp_heap_, v8::internal::CppHeap::From(), heap_, local_marking_worklists(), v8::base::TimeDelta::Max(), TRACE_GC, and v8::internal::Heap::tracer().
Referenced by DrainMarkingWorklist().
remembered_sets_marking_handler()
YoungGenerationRememberedSetsMarkingWorklist* v8::internal::MinorMarkSweepCollector::remembered_sets_marking_handler () [inline]
Definition at line 172 of file minor-mark-sweep.h.
                                    {
    DCHECK_NOT_NULL(remembered_sets_marking_handler_);
    return remembered_sets_marking_handler_.get();
  }
References DCHECK_NOT_NULL, and remembered_sets_marking_handler_.
Referenced by v8::internal::ConcurrentMarking::GetMinorMaxConcurrency(), v8::internal::ConcurrentMarking::IsWorkLeft(), and v8::internal::ConcurrentMarking::RunMinorImpl().
RequestGC()
void v8::internal::MinorMarkSweepCollector::RequestGC ()
Definition at line 1115 of file minor-mark-sweep.cc.
                                        {
  if (is_in_atomic_pause()) return;
  DCHECK(v8_flags.concurrent_minor_ms_marking);
  if (gc_finalization_requested_.exchange(true, std::memory_order_relaxed))
    return;
  heap_->isolate()->stack_guard()->RequestGC();
}
References v8::internal::DCHECK(), gc_finalization_requested_, heap_, is_in_atomic_pause(), v8::internal::Heap::isolate(), v8::internal::Isolate::stack_guard(), and v8::internal::v8_flags.
Referenced by v8::internal::ConcurrentMarking::RunMinorImpl().
StartMarking()
void v8::internal::MinorMarkSweepCollector::StartMarking (bool force_use_background_threads)
Definition at line 344 of file minor-mark-sweep.cc.
                                                                            {
#if defined(VERIFY_HEAP) && !V8_ENABLE_STICKY_MARK_BITS_BOOL
  if (v8_flags.verify_heap) {
    for (PageMetadata* page : *heap_->new_space()) {
      CHECK(page->marking_bitmap()->IsClean());
    }
  }
#endif // defined(VERIFY_HEAP) && !V8_ENABLE_STICKY_MARK_BITS_BOOL
  // The state for background thread is saved here and maintained for the whole
  // GC cycle. Both CppHeap and regular V8 heap will refer to this flag.
  CHECK(!use_background_threads_in_cycle_.has_value());
  // Once we decided to start concurrent marking we always need to use
  // background threads, this is because Minor MS doesn't perform incremental
  // marking. ShouldUseBackgroundThreads() on worker isolates can be updated
  // concurrently from the main thread outside a task, so we shouldn't invoke it
  // here again as it could return a different result.
  use_background_threads_in_cycle_ =
      force_use_background_threads || heap_->ShouldUseBackgroundThreads();
  auto* cpp_heap = CppHeap::From(heap_->cpp_heap_);
  // CppHeap's marker must be initialized before the V8 marker to allow
  // exchanging of worklists.
  if (cpp_heap && cpp_heap->generational_gc_supported()) {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MINOR_MS_MARK_EMBEDDER_PROLOGUE);
    cpp_heap->InitializeMarking(CppHeap::CollectionType::kMinor);
  }
  DCHECK_NULL(ephemeron_table_list_);
  ephemeron_table_list_ = std::make_unique<EphemeronRememberedSet::TableList>();
  DCHECK_NULL(marking_worklists_);
  marking_worklists_ = std::make_unique<MarkingWorklists>();
  DCHECK_NULL(main_marking_visitor_);
  DCHECK_NULL(pretenuring_feedback_);
  if (v8_flags.sticky_mark_bits) {
    DCHECK(ExternalPointerRememberedSetsEmpty(heap_->sticky_space()));
  } else {
    DCHECK(ExternalPointerRememberedSetsEmpty(
        heap_->paged_new_space()->paged_space()));
  }
  pretenuring_feedback_ =
      std::make_unique<PretenuringHandler::PretenuringFeedbackMap>(
          PretenuringHandler::kInitialFeedbackCapacity);
  main_marking_visitor_ = std::make_unique<YoungGenerationMainMarkingVisitor>(
      heap_, pretenuring_feedback_.get());
  DCHECK_NULL(remembered_sets_marking_handler_);
  remembered_sets_marking_handler_ =
      std::make_unique<YoungGenerationRememberedSetsMarkingWorklist>(heap_);
  if (cpp_heap && cpp_heap->generational_gc_supported()) {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MINOR_MS_MARK_EMBEDDER_PROLOGUE);
    // StartTracing immediately starts marking which requires V8 worklists to
    // be set up.
    cpp_heap->StartMarking();
  }
}
References CHECK, v8::internal::Heap::cpp_heap_, v8::internal::DCHECK(), DCHECK_NULL, ephemeron_table_list_, v8::internal::CppHeap::From(), heap_, v8::internal::PretenuringHandler::kInitialFeedbackCapacity, cppgc::internal::kMinor, main_marking_visitor_, marking_worklists_, v8::internal::Heap::new_space(), v8::internal::Heap::paged_new_space(), v8::internal::PagedNewSpace::paged_space(), pretenuring_feedback_, remembered_sets_marking_handler_, v8::internal::Heap::ShouldUseBackgroundThreads(), v8::internal::Heap::sticky_space(), TRACE_GC, v8::internal::Heap::tracer(), use_background_threads_in_cycle_, and v8::internal::v8_flags.
Referenced by MarkLiveObjects(), and v8::internal::IncrementalMarking::StartMarkingMinor().
StartSweepNewSpace()
bool v8::internal::MinorMarkSweepCollector::StartSweepNewSpace () [private]
Definition at line 931 of file minor-mark-sweep.cc.
                                                 {
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MINOR_MS_SWEEP_NEW);
  PagedSpaceForNewSpace* paged_space = heap_->paged_new_space()->paged_space();
  paged_space->ClearAllocatorState();
  int will_be_swept = 0;
  bool has_promoted_pages = false;
  heap_->StartResizeNewSpace();
  for (auto it = paged_space->begin(); it != paged_space->end();) {
    PageMetadata* p = *(it++);
    DCHECK(p->SweepingDone());
    intptr_t live_bytes_on_page = p->live_bytes();
    if (live_bytes_on_page == 0) {
      if (paged_space->ShouldReleaseEmptyPage()) {
        paged_space->RemovePageFromSpace(p);
        heap_->memory_allocator()->Free(MemoryAllocator::FreeMode::kPool, p);
      } else {
        sweeper()->SweepEmptyNewSpacePage(p);
      }
      continue;
    }
    if (ShouldMovePage(p, live_bytes_on_page, p->wasted_memory())) {
      EvacuateExternalPointerReferences(p);
      // free list categories will be relinked by the sweeper after sweeping is
      // done.
      heap_->new_space()->PromotePageToOldSpace(p,
                                                FreeMode::kDoNotLinkCategory);
      has_promoted_pages = true;
      sweeper()->AddPromotedPage(p);
    } else {
      // Page is not promoted. Sweep it instead.
      sweeper()->AddNewSpacePage(p);
      will_be_swept++;
    }
  }
#ifdef V8_COMPRESS_POINTERS
  // Now that we have evacuated any external pointers, rebuild EPT free-lists
  // for the new space.
  heap_->isolate()->external_pointer_table().SweepAndCompact(
      heap_->young_external_pointer_space(), heap_->isolate()->counters());
#endif
  if (v8_flags.gc_verbose) {
    PrintIsolate(heap_->isolate(),
                 "sweeping: space=%s initialized_for_sweeping=%d",
                 ToString(paged_space->identity()), will_be_swept);
  }
  return has_promoted_pages;
}
References v8::internal::Sweeper::AddNewSpacePage(), v8::internal::Sweeper::AddPromotedPage(), v8::internal::PagedSpaceBase::begin(), v8::internal::PagedSpaceBase::ClearAllocatorState(), v8::internal::Isolate::counters(), v8::internal::DCHECK(), v8::internal::PagedSpaceBase::end(), EvacuateExternalPointerReferences(), v8::internal::MemoryAllocator::Free(), heap_, v8::internal::Heap::isolate(), v8::internal::kDoNotLinkCategory, v8::internal::MemoryAllocator::kPool, v8::internal::MutablePageMetadata::live_bytes(), v8::internal::Heap::memory_allocator(), v8::internal::Heap::new_space(), v8::internal::Heap::paged_new_space(), v8::internal::PagedNewSpace::paged_space(), v8::internal::PrintIsolate(), v8::internal::NewSpace::PromotePageToOldSpace(), v8::internal::PagedSpaceForNewSpace::RemovePageFromSpace(), v8::internal::anonymous_namespace{minor-mark-sweep.cc}::ShouldMovePage(), v8::internal::PagedSpaceForNewSpace::ShouldReleaseEmptyPage(), v8::internal::Heap::StartResizeNewSpace(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), sweeper(), v8::internal::MutablePageMetadata::SweepingDone(), v8::internal::ToString(), TRACE_GC, v8::internal::Heap::tracer(), v8::internal::v8_flags, and v8::internal::MemoryChunkMetadata::wasted_memory().
Referenced by Sweep().
StartSweepNewSpaceWithStickyBits()
void v8::internal::MinorMarkSweepCollector::StartSweepNewSpaceWithStickyBits () [private]
Definition at line 987 of file minor-mark-sweep.cc.
                                                               {
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MINOR_MS_SWEEP_NEW);
  PagedSpaceBase* paged_space = heap_->sticky_space();
  paged_space->ClearAllocatorState();
  int will_be_swept = 0;
  for (auto it = paged_space->begin(); it != paged_space->end();) {
    PageMetadata* p = *(it++);
    DCHECK(p->SweepingDone());
    intptr_t live_bytes_on_page = p->live_bytes();
    if (live_bytes_on_page == 0) {
      // Don't release empty pages with sticky bits, since there may be other
      // live old objects not accounted in current live bytes.
      sweeper()->SweepEmptyNewSpacePage(p);
      continue;
    }
    // TODO(333906585): Fix the promotion counter.
    sweeper()->AddPage(OLD_SPACE, p);
    will_be_swept++;
  }
  static_cast<StickySpace*>(paged_space)
      ->set_old_objects_size(paged_space->Size());
#ifdef V8_COMPRESS_POINTERS
  // Now that we have evacuated any external pointers, rebuild EPT free-lists
  // for the new space.
  heap_->isolate()->external_pointer_table().SweepAndCompact(
      heap_->young_external_pointer_space(), heap_->isolate()->counters());
#endif
  if (v8_flags.gc_verbose) {
    PrintIsolate(heap_->isolate(),
                 "sweeping: space=%s initialized_for_sweeping=%d",
                 ToString(paged_space->identity()), will_be_swept);
  }
}
References v8::internal::Sweeper::AddPage(), v8::internal::PagedSpaceBase::begin(), v8::internal::PagedSpaceBase::ClearAllocatorState(), v8::internal::Isolate::counters(), v8::internal::DCHECK(), v8::internal::PagedSpaceBase::end(), heap_, v8::internal::Heap::isolate(), v8::internal::MutablePageMetadata::live_bytes(), v8::internal::OLD_SPACE, v8::internal::PrintIsolate(), v8::internal::PagedSpaceBase::Size(), v8::internal::Heap::sticky_space(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), sweeper(), v8::internal::MutablePageMetadata::SweepingDone(), v8::internal::ToString(), TRACE_GC, v8::internal::Heap::tracer(), and v8::internal::v8_flags.
Referenced by Sweep().
Sweep()
void v8::internal::MinorMarkSweepCollector::Sweep () [private]
Definition at line 1064 of file minor-mark-sweep.cc.
                                    {
  DCHECK(!sweeper()->AreMinorSweeperTasksRunning());
  sweeper_->InitializeMinorSweeping();
  TRACE_GC_WITH_FLOW(
      heap_->tracer(), GCTracer::Scope::MINOR_MS_SWEEP,
      sweeper_->GetTraceIdForFlowEvent(GCTracer::Scope::MINOR_MS_SWEEP),
      TRACE_EVENT_FLAG_FLOW_OUT);
  bool has_promoted_pages = false;
  if (v8_flags.sticky_mark_bits) {
    StartSweepNewSpaceWithStickyBits();
  } else {
    has_promoted_pages = StartSweepNewSpace();
  }
  if (SweepNewLargeSpace()) has_promoted_pages = true;
  if (v8_flags.verify_heap && has_promoted_pages) {
    // Update the external string table in preparation for heap verification.
    // Otherwise, updating the table will happen during the next full GC.
    TRACE_GC(heap_->tracer(),
             GCTracer::Scope::MINOR_MS_SWEEP_UPDATE_STRING_TABLE);
    heap_->UpdateYoungReferencesInExternalStringTable([](Heap* heap,
                                                         FullObjectSlot p) {
      DCHECK(
          !Cast<HeapObject>(*p)->map_word(kRelaxedLoad).IsForwardingAddress());
      return Cast<String>(*p);
    });
  }
  sweeper_->StartMinorSweeping();
#ifdef DEBUG
  VerifyRememberedSetsAfterEvacuation(heap_,
                                      GarbageCollector::MINOR_MARK_SWEEPER);
  heap_->VerifyCountersBeforeConcurrentSweeping(
      GarbageCollector::MINOR_MARK_SWEEPER);
#endif
  sweeper()->StartMinorSweeperTasks();
  DCHECK_EQ(0, heap_->new_lo_space()->Size());
  const bool empty_new_space =
      v8_flags.sticky_mark_bits
          ? heap_->sticky_space()->young_objects_size() == 0
          : heap_->new_space()->Size() == 0;
  heap_->array_buffer_sweeper()->RequestSweep(
      ArrayBufferSweeper::SweepingType::kYoung,
      empty_new_space ? ArrayBufferSweeper::TreatAllYoungAsPromoted::kYes
                      : ArrayBufferSweeper::TreatAllYoungAsPromoted::kNo);
}
References v8::internal::Heap::array_buffer_sweeper(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Sweeper::GetTraceIdForFlowEvent(), heap_, v8::internal::Sweeper::InitializeMinorSweeping(), v8::internal::ArrayBufferSweeper::kNo, v8::kRelaxedLoad, v8::internal::ArrayBufferSweeper::kYes, v8::internal::ArrayBufferSweeper::kYoung, v8::internal::MINOR_MARK_SWEEPER, v8::internal::Heap::new_lo_space(), v8::internal::Heap::new_space(), v8::internal::ArrayBufferSweeper::RequestSweep(), v8::internal::LargeObjectSpace::Size(), v8::internal::Sweeper::StartMinorSweeperTasks(), v8::internal::Sweeper::StartMinorSweeping(), StartSweepNewSpace(), StartSweepNewSpaceWithStickyBits(), v8::internal::Heap::sticky_space(), sweeper(), sweeper_, SweepNewLargeSpace(), TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC, TRACE_GC_WITH_FLOW, v8::internal::Heap::tracer(), v8::internal::Heap::UpdateYoungReferencesInExternalStringTable(), v8::internal::v8_flags, and v8::internal::StickySpace::young_objects_size().
Referenced by CollectGarbage().
sweeper()
Sweeper* v8::internal::MinorMarkSweepCollector::sweeper () [inline], [private]
Definition at line 200 of file minor-mark-sweep.h.
{ return sweeper_; }
References sweeper_.
Referenced by CollectGarbage(), StartSweepNewSpace(), StartSweepNewSpaceWithStickyBits(), Sweep(), and SweepNewLargeSpace().
SweepNewLargeSpace()
bool v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace () [private]
Definition at line 1028 of file minor-mark-sweep.cc.
                                                 {
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MINOR_MS_SWEEP_NEW_LO);
  NewLargeObjectSpace* new_lo_space = heap_->new_lo_space();
  DCHECK_NOT_NULL(new_lo_space);
  DCHECK_EQ(kNullAddress, heap_->new_lo_space()->pending_object());
  bool has_promoted_pages = false;
  OldLargeObjectSpace* old_lo_space = heap_->lo_space();
  for (auto it = new_lo_space->begin(); it != new_lo_space->end();) {
    LargePageMetadata* current = *it;
    MemoryChunk* chunk = current->Chunk();
    it++;
    Tagged<HeapObject> object = current->GetObject();
    if (!non_atomic_marking_state_->IsMarked(object)) {
      // Object is dead and page can be released.
      new_lo_space->RemovePage(current);
      heap_->memory_allocator()->Free(MemoryAllocator::FreeMode::kImmediately,
                                      current);
      continue;
    }
    chunk->ClearFlagNonExecutable(MemoryChunk::TO_PAGE);
    chunk->SetFlagNonExecutable(MemoryChunk::FROM_PAGE);
    current->marking_progress_tracker().ResetIfEnabled();
    EvacuateExternalPointerReferences(current);
    old_lo_space->PromoteNewLargeObject(current);
    has_promoted_pages = true;
    sweeper()->AddPromotedPage(current);
  }
  new_lo_space->set_objects_size(0);
  return has_promoted_pages;
}
References v8::internal::Sweeper::AddPromotedPage(), v8::internal::LargeObjectSpace::begin(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunk::ClearFlagNonExecutable(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::LargeObjectSpace::end(), EvacuateExternalPointerReferences(), v8::internal::MemoryAllocator::Free(), v8::internal::MemoryChunk::FROM_PAGE, v8::internal::LargePageMetadata::GetObject(), heap_, v8::internal::MarkingStateBase< ConcreteState, access_mode >::IsMarked(), v8::internal::MemoryAllocator::kImmediately, v8::internal::kNullAddress, v8::internal::Heap::lo_space(), v8::internal::MutablePageMetadata::marking_progress_tracker(), v8::internal::Heap::memory_allocator(), v8::internal::Heap::new_lo_space(), non_atomic_marking_state_, v8::internal::LargeObjectSpace::pending_object(), v8::internal::OldLargeObjectSpace::PromoteNewLargeObject(), v8::internal::LargeObjectSpace::RemovePage(), v8::internal::MarkingProgressTracker::ResetIfEnabled(), v8::internal::LargeObjectSpace::set_objects_size(), v8::internal::MemoryChunk::SetFlagNonExecutable(), sweeper(), v8::internal::MemoryChunk::TO_PAGE, TRACE_GC, and v8::internal::Heap::tracer().
Referenced by Sweep().
TearDown()
void v8::internal::MinorMarkSweepCollector::TearDown ()
Definition at line 303 of file minor-mark-sweep.cc.
                                       {
  if (heap_->incremental_marking()->IsMinorMarking()) {
    DCHECK(heap_->concurrent_marking()->IsStopped());
    remembered_sets_marking_handler_->TearDown();
    main_marking_visitor_->PublishWorklists();
    heap_->main_thread_local_heap_->marking_barrier()->PublishIfNeeded();
    // Marking barriers of LocalHeaps will be published in their destructors.
    marking_worklists_->Clear();
    ephemeron_table_list_->Clear();
  }
}
References v8::internal::Heap::concurrent_marking(), v8::internal::DCHECK(), ephemeron_table_list_, heap_, v8::internal::Heap::incremental_marking(), v8::internal::IncrementalMarking::IsMinorMarking(), v8::internal::ConcurrentMarking::IsStopped(), main_marking_visitor_, v8::internal::Heap::main_thread_local_heap_, v8::internal::LocalHeap::marking_barrier(), marking_worklists_, v8::internal::MarkingBarrier::PublishIfNeeded(), and remembered_sets_marking_handler_.
TraceFragmentation()
void v8::internal::MinorMarkSweepCollector::TraceFragmentation () [private]
Definition at line 812 of file minor-mark-sweep.cc.
                                                 {
  PagedSpaceBase* new_space =
      v8_flags.sticky_mark_bits ? heap_->sticky_space()
                                : static_cast<PagedSpaceBase*>(
                                      heap_->paged_new_space()->paged_space());
  PtrComprCageBase cage_base(heap_->isolate());
  const std::array<size_t, 4> free_size_class_limits = {0, 1024, 2048, 4096};
  size_t free_bytes_of_class[free_size_class_limits.size()] = {0};
  size_t live_bytes = 0;
  size_t allocatable_bytes = 0;
  for (PageMetadata* p : *new_space) {
    Address free_start = p->area_start();
    for (auto [object, size] : LiveObjectRange(p)) {
      Address free_end = object.address();
      if (free_end != free_start) {
        size_t free_bytes = free_end - free_start;
        int free_bytes_index = 0;
        for (auto free_size_class_limit : free_size_class_limits) {
          if (free_bytes >= free_size_class_limit) {
            free_bytes_of_class[free_bytes_index] += free_bytes;
          }
          free_bytes_index++;
        }
      }
      live_bytes += size;
      free_start = free_end + size;
    }
    const Address top = heap_->NewSpaceTop();
    size_t area_end = p->Contains(top) ? top : p->area_end();
    if (free_start != area_end) {
      size_t free_bytes = area_end - free_start;
      int free_bytes_index = 0;
      for (auto free_size_class_limit : free_size_class_limits) {
        if (free_bytes >= free_size_class_limit) {
          free_bytes_of_class[free_bytes_index] += free_bytes;
        }
        free_bytes_index++;
      }
    }
    allocatable_bytes += area_end - p->area_start();
    CHECK_EQ(allocatable_bytes, live_bytes + free_bytes_of_class[0]);
  }
  PrintIsolate(heap_->isolate(),
               "Minor Mark-Sweep Fragmentation: allocatable_bytes=%zu "
               "live_bytes=%zu "
               "free_bytes=%zu free_bytes_1K=%zu free_bytes_2K=%zu "
               "free_bytes_4K=%zu\n",
               allocatable_bytes, live_bytes, free_bytes_of_class[0],
               free_bytes_of_class[1], free_bytes_of_class[2],
               free_bytes_of_class[3]);
}
References CHECK_EQ, heap_, v8::internal::Heap::isolate(), v8::internal::Heap::NewSpaceTop(), v8::internal::Heap::paged_new_space(), v8::internal::PagedNewSpace::paged_space(), v8::internal::PrintIsolate(), size(), v8::internal::Heap::sticky_space(), and v8::internal::v8_flags.
Referenced by MarkLiveObjects().
UseBackgroundThreadsInCycle()
bool v8::internal::MinorMarkSweepCollector::UseBackgroundThreadsInCycle () const [inline]
Definition at line 189 of file minor-mark-sweep.h.
                                           {
    return use_background_threads_in_cycle_.value();
  }
References use_background_threads_in_cycle_.
Referenced by MarkLiveObjects(), v8::internal::ConcurrentMarking::RescheduleJobIfNeeded(), and v8::internal::ConcurrentMarking::TryScheduleJob().
Friends And Related Function Documentation
IncrementalMarking
friend class IncrementalMarking [friend]
Definition at line 249 of file minor-mark-sweep.h.
Member Data Documentation
ephemeron_table_list_
std::unique_ptr<EphemeronRememberedSet::TableList> v8::internal::MinorMarkSweepCollector::ephemeron_table_list_ [private]
Definition at line 231 of file minor-mark-sweep.h.
Referenced by ClearNonLiveReferences(), ephemeron_table_list(), StartMarking(), and TearDown().
gc_finalization_requested_
std::atomic<bool> v8::internal::MinorMarkSweepCollector::gc_finalization_requested_ {false} [private]
Definition at line 247 of file minor-mark-sweep.h.
Referenced by CollectGarbage(), gc_finalization_requsted(), and RequestGC().
heap_
Heap* const v8::internal::MinorMarkSweepCollector::heap_ [private]
Definition at line 227 of file minor-mark-sweep.h.
Referenced by ClearNonLiveReferences(), CollectGarbage(), DrainMarkingWorklist(), EvacuateExternalPointerReferences(), Finish(), FinishConcurrentMarking(), MarkLiveObjects(), MarkRoots(), MarkRootsFromConservativeStack(), MarkRootsFromTracedHandles(), PerformWrapperTracing(), RequestGC(), StartMarking(), StartSweepNewSpace(), StartSweepNewSpaceWithStickyBits(), Sweep(), SweepNewLargeSpace(), TearDown(), and TraceFragmentation().
is_in_atomic_pause_
std::atomic<bool> v8::internal::MinorMarkSweepCollector::is_in_atomic_pause_ {false} [private]
Definition at line 246 of file minor-mark-sweep.h.
Referenced by CollectGarbage(), and is_in_atomic_pause().
kMaxParallelTasks
constexpr size_t v8::internal::MinorMarkSweepCollector::kMaxParallelTasks = 8 [static], [constexpr]
Definition at line 150 of file minor-mark-sweep.h.
main_marking_visitor_
std::unique_ptr<YoungGenerationMainMarkingVisitor> v8::internal::MinorMarkSweepCollector::main_marking_visitor_ [private]
Definition at line 232 of file minor-mark-sweep.h.
Referenced by DrainMarkingWorklist(), local_marking_worklists(), main_marking_visitor(), MarkLiveObjects(), StartMarking(), and TearDown().
marking_state_
MarkingState* const v8::internal::MinorMarkSweepCollector::marking_state_ [private]
Definition at line 234 of file minor-mark-sweep.h.
Referenced by DrainMarkingWorklist().
marking_worklists_
std::unique_ptr<MarkingWorklists> v8::internal::MinorMarkSweepCollector::marking_worklists_ [private]
Definition at line 229 of file minor-mark-sweep.h.
Referenced by marking_worklists(), MarkLiveObjects(), StartMarking(), and TearDown().
non_atomic_marking_state_
NonAtomicMarkingState* const v8::internal::MinorMarkSweepCollector::non_atomic_marking_state_ [private]
Definition at line 235 of file minor-mark-sweep.h.
Referenced by ClearNonLiveReferences(), and SweepNewLargeSpace().
pretenuring_feedback_
std::unique_ptr<PretenuringHandler::PretenuringFeedbackMap> v8::internal::MinorMarkSweepCollector::pretenuring_feedback_ [private]
Definition at line 239 of file minor-mark-sweep.h.
Referenced by MarkLiveObjects(), and StartMarking().
remembered_sets_marking_handler_
std::unique_ptr<YoungGenerationRememberedSetsMarkingWorklist> v8::internal::MinorMarkSweepCollector::remembered_sets_marking_handler_ [private]
Definition at line 242 of file minor-mark-sweep.h.
Referenced by DrainMarkingWorklist(), MarkLiveObjects(), remembered_sets_marking_handler(), StartMarking(), and TearDown().
sweeper_
Sweeper* const v8::internal::MinorMarkSweepCollector::sweeper_ [private]
Definition at line 236 of file minor-mark-sweep.h.
Referenced by Sweep(), and sweeper().
use_background_threads_in_cycle_
std::optional<bool> v8::internal::MinorMarkSweepCollector::use_background_threads_in_cycle_ [private]
Definition at line 244 of file minor-mark-sweep.h.
Referenced by Finish(), StartMarking(), and UseBackgroundThreadsInCycle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/minor-mark-sweep.h
/mnt/V8SourceCode/src/heap/minor-mark-sweep.cc