v8::internal::compiler::turboshaft::DeadCodeAnalysis Class Reference
#include <dead-code-elimination-reducer.h>
Public Member Functions
DeadCodeAnalysis (Graph &graph, Zone *phase_zone)
template<bool trace_analysis>
std::pair< FixedOpIndexSidetable< OperationState::Liveness >, SparseOpIndexSideTable< BlockIndex > > Run ()
template<bool trace_analysis>
void ProcessBlock (const Block &block, uint32_t *unprocessed_count)
bool is_leaf_function () const
Private Attributes
Graph & graph_
FixedOpIndexSidetable< OperationState::Liveness > liveness_
FixedBlockSidetable< ControlState > entry_control_state_
SparseOpIndexSideTable< BlockIndex > rewritable_branch_targets_
bool is_leaf_function_ = true
Detailed Description
Definition at line 178 of file dead-code-elimination-reducer.h.
Constructor & Destructor Documentation
DeadCodeAnalysis()
v8::internal::compiler::turboshaft::DeadCodeAnalysis::DeadCodeAnalysis (Graph & graph, Zone * phase_zone) [inline], [explicit]
Definition at line 180 of file dead-code-elimination-reducer.h.
      : graph_(graph),
        liveness_(graph.op_id_count(), OperationState::kDead, phase_zone,
                  &graph),
        entry_control_state_(graph.block_count(), ControlState::Unreachable(),
                             phase_zone),
        rewritable_branch_targets_(phase_zone, &graph) {}
Member Function Documentation
is_leaf_function()
bool v8::internal::compiler::turboshaft::DeadCodeAnalysis::is_leaf_function () const [inline]
Definition at line 404 of file dead-code-elimination-reducer.h.
{ return is_leaf_function_; }
References is_leaf_function_.
Referenced by v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::IsLeafFunction().
ProcessBlock()
template<bool trace_analysis>
void v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock (const Block & block, uint32_t * unprocessed_count) [inline]
Definition at line 228 of file dead-code-elimination-reducer.h.
                                                                     {
    if constexpr (trace_analysis) {
      std::cout << "\n==========\n=== Processing " << PrintAsBlockHeader{block}
                << ":\n==========\nEXIT CONTROL STATE\n";
    }
    auto successors = SuccessorBlocks(block.LastOperation(graph_));
    ControlState control_state = ControlState::Unreachable();
    for (size_t i = 0; i < successors.size(); ++i) {
      const auto& r = entry_control_state_[successors[i]->index()];
      if constexpr (trace_analysis) {
        std::cout << " Successor " << successors[i]->index() << ": " << r
                  << "\n";
      }
      control_state = ControlState::LeastUpperBound(control_state, r);
    }
    if constexpr (trace_analysis)
      std::cout << "Combined: " << control_state << "\n";
    // If control_state == ControlState::Block(b), then the merge block b is
    // reachable through every path starting at the current block without any
    // live operations.
    if constexpr (trace_analysis) std::cout << "OPERATION STATE\n";
    auto op_range = graph_.OperationIndices(block);
    bool has_live_phis = false;
    for (auto it = op_range.end(); it != op_range.begin();) {
      --it;
      OpIndex index = *it;
      const Operation& op = graph_.Get(index);
      if constexpr (trace_analysis) std::cout << index << ":" << op << "\n";
      OperationState::Liveness op_state = liveness_[index];
      if (op.Is<DeadOp>()) {
        // Operation is already recognized as dead by a previous analysis.
        DCHECK_EQ(op_state, OperationState::kDead);
      } else if (op.Is<CallOp>()) {
        // The function contains a call, so it's not a leaf function.
        is_leaf_function_ = false;
      } else if (op.Is<BranchOp>() || op.Is<GotoOp>()) {
        if (control_state != ControlState::NotEliminatable()) {
          // Branch is still dead.
          DCHECK_EQ(op_state, OperationState::kDead);
          // If we know a target block we can rewrite into a goto.
          if (control_state.kind == ControlState::kBlock) {
            BlockIndex target = control_state.block;
            DCHECK(target.valid());
            rewritable_branch_targets_[index] = target;
          }
        } else {
          // Branch is live. We cannot rewrite it.
          op_state = OperationState::kLive;
          rewritable_branch_targets_.remove(index);
        }
      } else if (op.IsRequiredWhenUnused()) {
        op_state = OperationState::kLive;
      } else if (op.Is<PhiOp>()) {
        has_live_phis = has_live_phis || (op_state == OperationState::kLive);
        if (block.IsLoop()) {
          const PhiOp& phi = op.Cast<PhiOp>();
          // Check if the operation state of the input coming from the backedge
          // changes the liveness of the phi. In that case, trigger a revisit of
          // the loop.
          if (liveness_[phi.inputs()[PhiOp::kLoopPhiBackEdgeIndex]] <
              op_state) {
            if constexpr (trace_analysis) {
              std::cout
                  << "Operation state has changed. Need to revisit loop.\n";
            }
            Block* backedge = block.LastPredecessor();
            // Revisit the loop by increasing the {unprocessed_count} to include
            // all blocks of the loop.
            *unprocessed_count =
                std::max(*unprocessed_count, backedge->index().id() + 1);
          }
        }
      }
      // TODO(nicohartmann@): Handle Stack Guards to allow elimination of
      // otherwise empty loops.
      //
      // if(const CallOp* call = op.TryCast<CallOp>()) {
      // if(std::string(call->descriptor->descriptor->debug_name())
      // == "StackGuard") {
      // DCHECK_EQ(op_state, OperationState::kLive);
      // op_state = OperationState::kWeakLive;
      // }
      // }
      DCHECK_LE(liveness_[index], op_state);
      // If everything is still dead. We don't need to update anything.
      if (op_state == OperationState::kDead) continue;
      // We have a live operation.
      if constexpr (trace_analysis) {
        std::cout << " " << op_state << " <== " << liveness_[index] << "\n";
      }
      liveness_[index] = op_state;
      if constexpr (trace_analysis) {
        if (op.input_count > 0) std::cout << " Updating inputs:\n";
      }
      for (OpIndex input : op.inputs()) {
        auto old_input_state = liveness_[input];
        auto new_input_state =
            OperationState::LeastUpperBound(old_input_state, op_state);
        if constexpr (trace_analysis) {
          std::cout << " " << input << ": " << new_input_state
                    << " <== " << old_input_state << " || " << op_state << "\n";
        }
        liveness_[input] = new_input_state;
      }
      if (op_state == OperationState::kLive &&
          control_state != ControlState::NotEliminatable()) {
        // This block has live operations, which means that we can't skip it.
        // Reset the ControlState to NotEliminatable.
        if constexpr (trace_analysis) {
          std::cout << "Block has live operations. New control state: "
                    << ControlState::NotEliminatable() << "\n";
        }
        control_state = ControlState::NotEliminatable();
      }
    }
    if constexpr (trace_analysis) {
      std::cout << "ENTRY CONTROL STATE\nAfter operations: " << control_state
                << "\n";
    }
    // If this block is a merge and we don't have any live phis, it is a
    // potential target for branch redirection.
    if (block.IsMerge()) {
      if (!has_live_phis) {
        if (control_state.kind != ControlState::kBlock) {
          control_state = ControlState::Block(block.index());
          if constexpr (trace_analysis) {
            std::cout
                << "Block is loop or merge and has no live phi operations.\n";
          }
        } else if constexpr (trace_analysis) {
          std::cout << "Block is loop or merge and has no live phi "
                       "operations.\nControl state already has a goto block: "
                    << control_state << "\n";
        }
      }
    } else if (block.IsLoop()) {
      // If this is a loop, we reset the control state to avoid jumps into the
      // middle of the loop. In particular, this is required to prevent
      // introducing new backedges when blocks towards the end of the loop body
      // want to jump to a block at the beginning (past the header).
      control_state = ControlState::NotEliminatable();
      if constexpr (trace_analysis) {
        std::cout << "Block is loop header. Resetting control state: "
                  << control_state << "\n";
      }
      if (entry_control_state_[block.index()] != control_state) {
        if constexpr (trace_analysis) {
          std::cout << "Control state has changed. Need to revisit loop.\n";
        }
        Block* backedge = block.LastPredecessor();
        DCHECK_NOT_NULL(backedge);
        // Revisit the loop by increasing the {unprocessed_count} to include
        // all blocks of the loop.
        *unprocessed_count =
            std::max(*unprocessed_count, backedge->index().id() + 1);
      }
    }
    if constexpr (trace_analysis) {
      std::cout << "Final: " << control_state << "\n";
    }
    entry_control_state_[block.index()] = control_state;
  }
References v8::internal::compiler::turboshaft::ControlState::Block(), v8::internal::compiler::turboshaft::ControlState::block, v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, DCHECK_NOT_NULL, entry_control_state_, v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::index, v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::turboshaft::OperationT< Derived >::inputs(), v8::internal::compiler::turboshaft::Operation::inputs(), v8::internal::compiler::turboshaft::Operation::Is(), is_leaf_function_, v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::compiler::turboshaft::Block::IsMerge(), v8::internal::compiler::turboshaft::Operation::IsRequiredWhenUnused(), v8::internal::compiler::turboshaft::ControlState::kBlock, v8::internal::compiler::turboshaft::OperationState::kDead, v8::internal::compiler::turboshaft::ControlState::kind, v8::internal::compiler::turboshaft::OperationState::kLive, v8::internal::compiler::turboshaft::PhiOp::kLoopPhiBackEdgeIndex, v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), v8::internal::compiler::turboshaft::ControlState::LeastUpperBound(), v8::internal::compiler::turboshaft::OperationState::LeastUpperBound(), liveness_, v8::internal::compiler::turboshaft::ControlState::NotEliminatable(), v8::internal::compiler::turboshaft::Graph::OperationIndices(), rewritable_branch_targets_, v8::internal::compiler::turboshaft::SuccessorBlocks(), v8::internal::compiler::turboshaft::ControlState::Unreachable(), and v8::internal::compiler::turboshaft::BlockIndex::valid().
Run()
template<bool trace_analysis>
std::pair<FixedOpIndexSidetable<OperationState::Liveness>, SparseOpIndexSideTable<BlockIndex> > v8::internal::compiler::turboshaft::DeadCodeAnalysis::Run () [inline]
Definition at line 191 of file dead-code-elimination-reducer.h.
        {
    if constexpr (trace_analysis) {
      std::cout << "===== Running Dead Code Analysis =====\n";
    }
    for (uint32_t unprocessed_count = graph_.block_count();
         unprocessed_count > 0;) {
      BlockIndex block_index = static_cast<BlockIndex>(unprocessed_count - 1);
      --unprocessed_count;
      const Block& block = graph_.Get(block_index);
      ProcessBlock<trace_analysis>(block, &unprocessed_count);
    }
    if constexpr (trace_analysis) {
      std::cout << "===== Results =====\n== Operation State ==\n";
      for (Block b : graph_.blocks()) {
        std::cout << PrintAsBlockHeader{b} << ":\n";
        for (OpIndex index : graph_.OperationIndices(b)) {
          std::cout << " " << std::setw(8) << liveness_[index] << " "
                    << std::setw(3) << index.id() << ": " << graph_.Get(index)
                    << "\n";
        }
      }
      std::cout << "== Rewritable Branches ==\n";
      for (auto [branch_id, target] : rewritable_branch_targets_) {
        DCHECK(target.valid());
        std::cout << " " << std::setw(3) << branch_id << ": Branch ==> Goto "
                  << target.id() << "\n";
      }
      std::cout << "==========\n";
    }
    return {std::move(liveness_), std::move(rewritable_branch_targets_)};
  }
References v8::internal::compiler::turboshaft::Graph::block_count(), v8::internal::compiler::turboshaft::Graph::blocks(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::index, liveness_, v8::internal::compiler::turboshaft::Graph::OperationIndices(), and rewritable_branch_targets_.
Referenced by v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::Analyze().
Member Data Documentation
entry_control_state_
FixedBlockSidetable<ControlState> v8::internal::compiler::turboshaft::DeadCodeAnalysis::entry_control_state_ [private]
Definition at line 409 of file dead-code-elimination-reducer.h.
Referenced by ProcessBlock().
graph_
Graph& v8::internal::compiler::turboshaft::DeadCodeAnalysis::graph_ [private]
Definition at line 407 of file dead-code-elimination-reducer.h.
Referenced by ProcessBlock(), and Run().
is_leaf_function_
bool v8::internal::compiler::turboshaft::DeadCodeAnalysis::is_leaf_function_ = true [private]
Definition at line 414 of file dead-code-elimination-reducer.h.
Referenced by is_leaf_function(), and ProcessBlock().
liveness_
FixedOpIndexSidetable<OperationState::Liveness> v8::internal::compiler::turboshaft::DeadCodeAnalysis::liveness_ [private]
Definition at line 408 of file dead-code-elimination-reducer.h.
Referenced by ProcessBlock(), and Run().
rewritable_branch_targets_
SparseOpIndexSideTable<BlockIndex> v8::internal::compiler::turboshaft::DeadCodeAnalysis::rewritable_branch_targets_ [private]
Definition at line 410 of file dead-code-elimination-reducer.h.
Referenced by ProcessBlock(), and Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/dead-code-elimination-reducer.h