v8::internal::maglev::TransitionElementsKind Class Reference
#include <maglev-ir.h>
Public Member Functions
TransitionElementsKind (uint64_t bitfield, const ZoneVector< compiler::MapRef > &transition_sources, compiler::MapRef transition_target)
Input & object_input ()
Input & map_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
const ZoneVector< compiler::MapRef > & transition_sources () const
const compiler::MapRef transition_target () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputValueNodeT< 2, TransitionElementsKind >
Private Attributes
ZoneVector< compiler::MapRef > transition_sources_
const compiler::MapRef transition_target_
Additional Inherited Members
Detailed Description
Definition at line 11080 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::TransitionElementsKind::Base = FixedInputValueNodeT<2, TransitionElementsKind> [private]
Definition at line 11082 of file maglev-ir.h.
Constructor & Destructor Documentation
TransitionElementsKind()
v8::internal::maglev::TransitionElementsKind::TransitionElementsKind (uint64_t bitfield, const ZoneVector< compiler::MapRef > & transition_sources, compiler::MapRef transition_target) [inline], [explicit]
Definition at line 11085 of file maglev-ir.h.
      : Base(bitfield),
        transition_sources_(transition_sources),
        transition_target_(transition_target) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::TransitionElementsKind::GenerateCode (MaglevAssembler * , const ProcessingState &)
map_input()
Input& v8::internal::maglev::TransitionElementsKind::map_input () [inline]
Definition at line 11099 of file maglev-ir.h.
{ return input(1); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::TransitionElementsKind::MaxCallStackArgs () const
object_input()
Input& v8::internal::maglev::TransitionElementsKind::object_input () [inline]
Definition at line 11098 of file maglev-ir.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::TransitionElementsKind::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 11104 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::TransitionElementsKind::SetValueLocationConstraints ()
transition_sources()
const ZoneVector<compiler::MapRef>& v8::internal::maglev::TransitionElementsKind::transition_sources () const [inline]
Definition at line 11106 of file maglev-ir.h.
                                                               {
    return transition_sources_;
  }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
transition_target()
const compiler::MapRef v8::internal::maglev::TransitionElementsKind::transition_target () const [inline]
Definition at line 11109 of file maglev-ir.h.
                                                 {
    return transition_target_;
  }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::TransitionElementsKind::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 11095 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::TransitionElementsKind::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::AnySideEffects() | OpProperties::DeferredCall()
Definition at line 11093 of file maglev-ir.h.
transition_sources_
ZoneVector<compiler::MapRef> v8::internal::maglev::TransitionElementsKind::transition_sources_ [private]
Definition at line 11114 of file maglev-ir.h.
transition_target_
const compiler::MapRef v8::internal::maglev::TransitionElementsKind::transition_target_ [private]
Definition at line 11115 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h