v8::internal::TypedSlotSet Class Reference
#include <slot-set.h>
Public Types
enum IterationMode { FREE_EMPTY_CHUNKS
, KEEP_EMPTY_CHUNKS
 }
using FreeRangesMap = std::map< uint32_t, uint32_t >
Public Member Functions
TypedSlotSet (Address page_start)
template<typename Callback >
int Iterate (Callback callback, IterationMode mode)
void ClearInvalidSlots (const FreeRangesMap &invalid_ranges)
void AssertNoInvalidSlots (const FreeRangesMap &invalid_ranges)
Private Member Functions
template<typename Callback >
void IterateSlotsInRanges (Callback callback, const FreeRangesMap &invalid_ranges)
Chunk * LoadNext (Chunk *chunk)
void StoreNext (Chunk *chunk, Chunk *next)
Chunk * LoadHead ()
void StoreHead (Chunk *chunk)
Static Private Member Functions
static TypedSlot ClearedTypedSlot ()
Private Attributes
Address page_start_
Additional Inherited Members
Detailed Description
Definition at line 304 of file slot-set.h.
Member Typedef Documentation
FreeRangesMap
using v8::internal::TypedSlotSet::FreeRangesMap = std::map<uint32_t, uint32_t>
Definition at line 306 of file slot-set.h.
Member Enumeration Documentation
IterationMode
enum v8::internal::TypedSlotSet::IterationMode
Enumerator
FREE_EMPTY_CHUNKS
KEEP_EMPTY_CHUNKS
Definition at line 308 of file slot-set.h.
{ FREE_EMPTY_CHUNKS, KEEP_EMPTY_CHUNKS };
Constructor & Destructor Documentation
TypedSlotSet()
v8::internal::TypedSlotSet::TypedSlotSet (Address page_start) [inline], [explicit]
Definition at line 310 of file slot-set.h.
: page_start_(page_start) {}
Member Function Documentation
AssertNoInvalidSlots()
void v8::internal::TypedSlotSet::AssertNoInvalidSlots (const FreeRangesMap & invalid_ranges)
Definition at line 69 of file slot-set.cc.
                                                                           {
  IterateSlotsInRanges(
      [](TypedSlot* slot) {
        CHECK_WITH_MSG(false, "No slot in ranges expected.");
      },
      invalid_ranges);
}
References CHECK_WITH_MSG, and IterateSlotsInRanges().
Referenced by v8::internal::PageMetadata::AssertNoTypedSlotsInFreeMemory().
ClearedTypedSlot()
static TypedSlot v8::internal::TypedSlotSet::ClearedTypedSlot () [inline], [static], [private]
Definition at line 385 of file slot-set.h.
                                      {
    return TypedSlot{TypeField::encode(SlotType::kCleared) |
                     OffsetField::encode(0)};
  }
References v8::internal::kCleared.
Referenced by ClearInvalidSlots().
ClearInvalidSlots()
void v8::internal::TypedSlotSet::ClearInvalidSlots (const FreeRangesMap & invalid_ranges)
Definition at line 64 of file slot-set.cc.
                                                                        {
  IterateSlotsInRanges([](TypedSlot* slot) { *slot = ClearedTypedSlot(); },
                       invalid_ranges);
}
References ClearedTypedSlot(), and IterateSlotsInRanges().
Referenced by v8::internal::PageMetadata::ClearTypedSlotsInFreeMemory().
Iterate()
template<typename Callback >
int v8::internal::TypedSlotSet::Iterate (Callback callback, IterationMode mode) [inline]
Definition at line 323 of file slot-set.h.
                                                     {
    static_assert(static_cast<uint8_t>(SlotType::kLast) < 8);
    Chunk* chunk = head_;
    Chunk* previous = nullptr;
    int new_count = 0;
    while (chunk != nullptr) {
      bool empty = true;
      for (TypedSlot& slot : chunk->buffer) {
        SlotType type = TypeField::decode(slot.type_and_offset);
        if (type != SlotType::kCleared) {
          uint32_t offset = OffsetField::decode(slot.type_and_offset);
          Address addr = page_start_ + offset;
          if (callback(type, addr) == KEEP_SLOT) {
            new_count++;
            empty = false;
          } else {
            slot = ClearedTypedSlot();
          }
        }
      }
      Chunk* next = chunk->next;
      if (mode == FREE_EMPTY_CHUNKS && empty) {
        // We remove the chunk from the list but let it still point its next
        // chunk to allow concurrent iteration.
        if (previous) {
          StoreNext(previous, next);
        } else {
          StoreHead(next);
        }
        delete chunk;
      } else {
        previous = chunk;
      }
      chunk = next;
    }
    return new_count;
  }
References v8::internal::TypedSlots::Chunk::buffer, v8::internal::kCleared, heap::base::KEEP_SLOT, v8::internal::kLast, mode(), v8::internal::TypedSlots::Chunk::next, v8::internal::tracing::type, and v8::internal::TypedSlots::TypedSlot::type_and_offset.
Referenced by v8::internal::RememberedSet< type >::IterateTyped(), and v8::internal::RememberedSet< type >::RemoveRangeTyped().
IterateSlotsInRanges()
template<typename Callback >
void v8::internal::TypedSlotSet::IterateSlotsInRanges (Callback callback, const FreeRangesMap & invalid_ranges) [private]
Definition at line 78 of file slot-set.cc.
                                                                     {
  if (ranges.empty()) return;
  Chunk* chunk = LoadHead();
  while (chunk != nullptr) {
    for (TypedSlot& slot : chunk->buffer) {
      SlotType type = TypeField::decode(slot.type_and_offset);
      if (type == SlotType::kCleared) continue;
      uint32_t offset = OffsetField::decode(slot.type_and_offset);
      FreeRangesMap::const_iterator upper_bound = ranges.upper_bound(offset);
      if (upper_bound == ranges.begin()) continue;
      // upper_bounds points to the invalid range after the given slot. Hence,
      // we have to go to the previous element.
      upper_bound--;
      DCHECK_LE(upper_bound->first, offset);
      if (upper_bound->second > offset) {
        callback(&slot);
      }
    }
    chunk = LoadNext(chunk);
  }
}
References v8::internal::TypedSlots::Chunk::buffer, DCHECK_LE, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::kCleared, LoadHead(), LoadNext(), v8::internal::tracing::type, and v8::internal::TypedSlots::TypedSlot::type_and_offset.
Referenced by AssertNoInvalidSlots(), and ClearInvalidSlots().
LoadHead()
Chunk* v8::internal::TypedSlotSet::LoadHead () [inline], [private]
Definition at line 381 of file slot-set.h.
{ return base::AsAtomicPointer::Relaxed_Load(&head_); }
References v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load().
Referenced by IterateSlotsInRanges().
LoadNext()
Chunk* v8::internal::TypedSlotSet::LoadNext (Chunk * chunk) [inline], [private]
Definition at line 375 of file slot-set.h.
                                {
    return base::AsAtomicPointer::Relaxed_Load(&chunk->next);
  }
References v8::internal::TypedSlots::Chunk::next, and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load().
Referenced by IterateSlotsInRanges().
StoreHead()
void v8::internal::TypedSlotSet::StoreHead (Chunk * chunk) [inline], [private]
Definition at line 382 of file slot-set.h.
                               {
    base::AsAtomicPointer::Relaxed_Store(&head_, chunk);
  }
References v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store().
StoreNext()
void v8::internal::TypedSlotSet::StoreNext (Chunk * chunk, Chunk * next) [inline], [private]
Definition at line 378 of file slot-set.h.
                                            {
    return base::AsAtomicPointer::Relaxed_Store(&chunk->next, next);
  }
References v8::internal::TypedSlots::Chunk::next, and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store().
Member Data Documentation
page_start_
Address v8::internal::TypedSlotSet::page_start_ [private]
Definition at line 390 of file slot-set.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/slot-set.h
/mnt/V8SourceCode/src/heap/slot-set.cc