v8::tracing::anonymous_namespace{d8.cc}::TraceConfigParser Class Reference
Static Public Member Functions
static void FillTraceConfig (v8::Isolate *isolate, platform::tracing::TraceConfig *trace_config, const char *json_str)
Static Private Member Functions
static int UpdateIncludedCategoriesList (v8::Isolate *isolate, Local< Context > context, Local< v8::Object > object, platform::tracing::TraceConfig *trace_config)
Detailed Description
Definition at line 456 of file d8.cc.
Member Function Documentation
FillTraceConfig()
static void v8::tracing::anonymous_namespace{d8.cc}::TraceConfigParser::FillTraceConfig (v8::Isolate * isolate, platform::tracing::TraceConfig * trace_config, const char * json_str) [inline], [static]
Definition at line 458 of file d8.cc.
                                                    {
    HandleScope outer_scope(isolate);
    Local<Context> context = Context::New(isolate);
    Context::Scope context_scope(context);
    HandleScope inner_scope(isolate);
    Local<String> source =
        String::NewFromUtf8(isolate, json_str).ToLocalChecked();
    Local<Value> result = JSON::Parse(context, source).ToLocalChecked();
    Local<v8::Object> trace_config_object = result.As<v8::Object>();
    // Try reading 'trace_config' property from a full chrome trace config.
    // https://chromium.googlesource.com/chromium/src/+/master/docs/memory-infra/memory_infra_startup_tracing.md#the-advanced-way
    Local<Value> maybe_trace_config_object =
        GetValue(isolate, context, trace_config_object, kTraceConfigParam);
    if (maybe_trace_config_object->IsObject()) {
      trace_config_object = maybe_trace_config_object.As<Object>();
    }
    UpdateIncludedCategoriesList(isolate, context, trace_config_object,
                                 trace_config);
  }
References v8::Local< T >::As(), v8::anonymous_namespace{d8.cc}::GetValue(), v8::tracing::anonymous_namespace{d8.cc}::kTraceConfigParam, v8::Context::New(), v8::String::NewFromUtf8(), v8::JSON::Parse(), v8::base::internal::result, and v8::MaybeLocal< T >::ToLocalChecked().
UpdateIncludedCategoriesList()
static int v8::tracing::anonymous_namespace{d8.cc}::TraceConfigParser::UpdateIncludedCategoriesList (v8::Isolate * isolate, Local< Context > context, Local< v8::Object > object, platform::tracing::TraceConfig * trace_config) [inline], [static], [private]
Definition at line 483 of file d8.cc.
                                                {
    Local<Value> value =
        GetValue(isolate, context, object, kIncludedCategoriesParam);
    if (value->IsArray()) {
      Local<Array> v8_array = value.As<Array>();
      for (int i = 0, length = v8_array->Length(); i < length; ++i) {
        Local<Value> v = v8_array->Get(context, i)
                             .ToLocalChecked()
                             ->ToString(context)
                             .ToLocalChecked();
        String::Utf8Value str(isolate, v->ToString(context).ToLocalChecked());
        trace_config->AddIncludedCategory(*str);
      }
      return v8_array->Length();
    }
    return 0;
  }
References v8::platform::tracing::TraceConfig::AddIncludedCategory(), v8::anonymous_namespace{d8.cc}::GetValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::tracing::anonymous_namespace{d8.cc}::kIncludedCategoriesParam, v8::internal::length, and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/d8/d8.cc