v8::internal::wasm::AsmCallableType Class Reference
#include <asm-types.h>
Public Member Functions
AsmCallableType (const AsmCallableType &)=delete
AsmCallableType & operator= (const AsmCallableType &)=delete
virtual std::string Name ()=0
virtual bool CanBeInvokedWith (AsmType *return_type, const ZoneVector< AsmType * > &args)=0
Protected Member Functions
AsmCallableType ()=default
virtual ~AsmCallableType ()=default
virtual bool IsA (AsmType *other)
Friends
class AsmType
Detailed Description
Definition at line 101 of file asm-types.h.
Constructor & Destructor Documentation
AsmCallableType() [1/2]
v8::internal::wasm::AsmCallableType::AsmCallableType (const AsmCallableType &) [delete]
AsmCallableType() [2/2]
v8::internal::wasm::AsmCallableType::AsmCallableType () [protected], [default]
 AsmCallableType()
virtual v8::internal::wasm::AsmCallableType::~AsmCallableType () [protected], [virtual], [default]
Member Function Documentation
CanBeInvokedWith()
virtual bool v8::internal::wasm::AsmCallableType::CanBeInvokedWith (AsmType * return_type, const ZoneVector< AsmType * > & args) [pure virtual]
Implemented in v8::internal::wasm::AsmOverloadedFunctionType, v8::internal::wasm::AsmFunctionType, v8::internal::wasm::anonymous_namespace{asm-types.cc}::AsmMinMaxType, and v8::internal::wasm::anonymous_namespace{asm-types.cc}::AsmFroundType.
Referenced by v8::internal::wasm::AsmJsParser::ValidateCall().
IsA()
bool v8::internal::wasm::AsmCallableType::IsA (AsmType * other) [protected], [virtual]
Reimplemented in v8::internal::wasm::AsmFunctionType.
Definition at line 139 of file asm-types.cc.
                                        {
  return other->AsCallableType() == this;
}
References v8::internal::wasm::AsmType::AsCallableType().
Name()
virtual std::string v8::internal::wasm::AsmCallableType::Name () [pure virtual]
Implemented in v8::internal::wasm::AsmOverloadedFunctionType, v8::internal::wasm::AsmFunctionType, v8::internal::wasm::anonymous_namespace{asm-types.cc}::AsmMinMaxType, and v8::internal::wasm::anonymous_namespace{asm-types.cc}::AsmFroundType.
Referenced by v8::internal::wasm::AsmType::Name().
operator=()
AsmCallableType& v8::internal::wasm::AsmCallableType::operator= (const AsmCallableType &) [delete]
Friends And Related Function Documentation
AsmType
friend class AsmType [friend]
Definition at line 122 of file asm-types.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/asmjs/asm-types.h
/mnt/V8SourceCode/src/asmjs/asm-types.cc