v8::internal::SlotAccessorForHandle< IsolateT > Class Template Reference
Public Member Functions
SlotAccessorForHandle (DirectHandle< HeapObject > *handle, IsolateT *isolate)
MaybeObjectSlot slot () const
ExternalPointerSlot external_pointer_slot (ExternalPointerTag tag) const
Handle< HeapObject > object () const
int offset () const
int Write (Tagged< MaybeObject > value, int slot_offset, WriteBarrierMode mode)
int Write (Tagged< HeapObject > value, HeapObjectReferenceType ref_type, int slot_offset, WriteBarrierMode mode)
int Write (DirectHandle< HeapObject > value, HeapObjectReferenceType ref_type, int slot_offset, WriteBarrierMode mode)
int WriteIndirectPointerTo (Tagged< HeapObject > value, WriteBarrierMode mode)
int WriteProtectedPointerTo (Tagged< TrustedObject > value, WriteBarrierMode mode)
Private Attributes
DirectHandle< HeapObject > * handle_
IsolateT * isolate_
Detailed Description
template<typename IsolateT>
class v8::internal::SlotAccessorForHandle< IsolateT >
Definition at line 176 of file deserializer.cc.
Constructor & Destructor Documentation
SlotAccessorForHandle()
template<typename IsolateT >
v8::internal::SlotAccessorForHandle< IsolateT >::SlotAccessorForHandle (DirectHandle< HeapObject > * handle, IsolateT * isolate) [inline]
Definition at line 178 of file deserializer.cc.
      : handle_(handle), isolate_(isolate) {}
Member Function Documentation
external_pointer_slot()
template<typename IsolateT >
ExternalPointerSlot v8::internal::SlotAccessorForHandle< IsolateT >::external_pointer_slot (ExternalPointerTag tag) const [inline]
Definition at line 182 of file deserializer.cc.
                                                                          {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
object()
template<typename IsolateT >
Handle<HeapObject> v8::internal::SlotAccessorForHandle< IsolateT >::object () const [inline]
Definition at line 185 of file deserializer.cc.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
offset()
template<typename IsolateT >
int v8::internal::SlotAccessorForHandle< IsolateT >::offset () const [inline]
Definition at line 186 of file deserializer.cc.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
slot()
template<typename IsolateT >
MaybeObjectSlot v8::internal::SlotAccessorForHandle< IsolateT >::slot () const [inline]
Definition at line 181 of file deserializer.cc.
{ UNREACHABLE(); }
Write() [1/3]
template<typename IsolateT >
int v8::internal::SlotAccessorForHandle< IsolateT >::Write (DirectHandle< HeapObject > value, HeapObjectReferenceType ref_type, int slot_offset, WriteBarrierMode mode) [inline]
Definition at line 198 of file deserializer.cc.
                                                    {
    DCHECK_EQ(slot_offset, 0);
    DCHECK_EQ(ref_type, HeapObjectReferenceType::STRONG);
    *handle_ = value;
    return 1;
  }
Write() [2/3]
template<typename IsolateT >
int v8::internal::SlotAccessorForHandle< IsolateT >::Write (Tagged< HeapObject > value, HeapObjectReferenceType ref_type, int slot_offset, WriteBarrierMode mode) [inline]
Definition at line 191 of file deserializer.cc.
                                                    {
    DCHECK_EQ(slot_offset, 0);
    DCHECK_EQ(ref_type, HeapObjectReferenceType::STRONG);
    *handle_ = direct_handle(value, isolate_);
    return 1;
  }
Write() [3/3]
template<typename IsolateT >
int v8::internal::SlotAccessorForHandle< IsolateT >::Write (Tagged< MaybeObject > value, int slot_offset, WriteBarrierMode mode) [inline]
Definition at line 188 of file deserializer.cc.
                                                                               {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
WriteIndirectPointerTo()
template<typename IsolateT >
int v8::internal::SlotAccessorForHandle< IsolateT >::WriteIndirectPointerTo (Tagged< HeapObject > value, WriteBarrierMode mode) [inline]
Definition at line 205 of file deserializer.cc.
                                                                              {
    UNREACHABLE();
  }
WriteProtectedPointerTo()
template<typename IsolateT >
int v8::internal::SlotAccessorForHandle< IsolateT >::WriteProtectedPointerTo (Tagged< TrustedObject > value, WriteBarrierMode mode) [inline]
Definition at line 208 of file deserializer.cc.
                                                     {
    UNREACHABLE();
  }
Member Data Documentation
handle_
template<typename IsolateT >
DirectHandle<HeapObject>* v8::internal::SlotAccessorForHandle< IsolateT >::handle_ [private]
Definition at line 214 of file deserializer.cc.
isolate_
template<typename IsolateT >
IsolateT* v8::internal::SlotAccessorForHandle< IsolateT >::isolate_ [private]
Definition at line 215 of file deserializer.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/deserializer.cc