v8::internal::compiler::JSBoundFunctionRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< JSBoundFunction > object () const
JSReceiverRef bound_target_function (JSHeapBroker *broker) const
ObjectRef bound_this (JSHeapBroker *broker) const
FixedArrayRef bound_arguments (JSHeapBroker *broker) const
Detailed Description
Definition at line 657 of file heap-refs.h.
Member Function Documentation
bound_arguments()
FixedArrayRef v8::internal::compiler::JSBoundFunctionRef::bound_arguments (JSHeapBroker * broker) const
Definition at line 1624 of file heap-refs.cc.
                                                                            {
  // Immutable after initialization.
  return MakeRefAssumeMemoryFence(broker, object()->bound_arguments());
}
References broker(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
bound_target_function()
JSReceiverRef v8::internal::compiler::JSBoundFunctionRef::bound_target_function (JSHeapBroker * broker) const
Definition at line 1613 of file heap-refs.cc.
                                {
  // Immutable after initialization.
  return MakeRefAssumeMemoryFence(broker, object()->bound_target_function());
}
References broker(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
bound_this()
ObjectRef v8::internal::compiler::JSBoundFunctionRef::bound_this (JSHeapBroker * broker) const
Definition at line 1619 of file heap-refs.cc.
                                                                   {
  // Immutable after initialization.
  return MakeRefAssumeMemoryFence(broker, object()->bound_this());
}
References broker(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
object()
IndirectHandle<JSBoundFunction> v8::internal::compiler::JSBoundFunctionRef::object () const
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc