v8::internal::ObjectLiteralProperty Class Reference
#include <ast.h>
Public Types
enum Kind : uint8_t {
CONSTANT
, COMPUTED
, MATERIALIZED_LITERAL
, GETTER
,
SETTER
, PROTOTYPE
, SPREAD
 }
Public Member Functions
Kind kind () const
bool IsCompileTimeValue () const
void set_emit_store (bool emit_store)
bool emit_store () const
bool IsNullPrototype () const
bool IsPrototype () const
Private Member Functions
ObjectLiteralProperty (Expression *key, Expression *value, Kind kind, bool is_computed_name)
ObjectLiteralProperty (AstValueFactory *ast_value_factory, Expression *key, Expression *value, bool is_computed_name)
Private Attributes
friend Zone
Kind kind_
bool emit_store_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 1254 of file ast.h.
Member Enumeration Documentation
Kind
enum v8::internal::ObjectLiteralProperty::Kind : uint8_t
Enumerator
CONSTANT
COMPUTED
MATERIALIZED_LITERAL
GETTER
SETTER
PROTOTYPE
SPREAD
Definition at line 1256 of file ast.h.
            : uint8_t {
    CONSTANT, // Property with constant value (compile time).
    COMPUTED, // Property with computed value (execution time).
    MATERIALIZED_LITERAL, // Property value is a materialized literal.
    GETTER,
    SETTER, // Property is an accessor function.
    PROTOTYPE, // Property is __proto__.
    SPREAD
  };
Constructor & Destructor Documentation
ObjectLiteralProperty() [1/2]
v8::internal::ObjectLiteralProperty::ObjectLiteralProperty (Expression * key, Expression * value, Kind kind, bool is_computed_name) [private]
Definition at line 277 of file ast.cc.
    : LiteralProperty(key, value, is_computed_name),
      kind_(kind),
      emit_store_(true) {}
ObjectLiteralProperty() [2/2]
v8::internal::ObjectLiteralProperty::ObjectLiteralProperty (AstValueFactory * ast_value_factory, Expression * key, Expression * value, bool is_computed_name) [private]
Definition at line 283 of file ast.cc.
    : LiteralProperty(key, value, is_computed_name), emit_store_(true) {
  if (!is_computed_name && key->AsLiteral()->IsRawString() &&
      key->AsLiteral()->AsRawString() == ast_value_factory->proto_string()) {
    kind_ = PROTOTYPE;
  } else if (value_->AsMaterializedLiteral() != nullptr) {
    kind_ = MATERIALIZED_LITERAL;
  } else if (value_->IsLiteral()) {
    kind_ = CONSTANT;
  } else {
    kind_ = COMPUTED;
  }
}
References v8::internal::AstNode::AsMaterializedLiteral(), COMPUTED, CONSTANT, v8::internal::LiteralProperty::is_computed_name(), v8::internal::LiteralProperty::key(), kind_, MATERIALIZED_LITERAL, PROTOTYPE, and v8::internal::LiteralProperty::value_.
Member Function Documentation
emit_store()
bool v8::internal::ObjectLiteral::Property::emit_store () const
Definition at line 337 of file ast.cc.
{ return emit_store_; }
References emit_store_.
Referenced by set_emit_store().
IsCompileTimeValue()
bool v8::internal::ObjectLiteral::Property::IsCompileTimeValue () const
Definition at line 328 of file ast.cc.
                                                     {
  return kind_ == CONSTANT ||
         (kind_ == MATERIALIZED_LITERAL && value_->IsCompileTimeValue());
}
References CONSTANT, v8::internal::Expression::IsCompileTimeValue(), kind_, MATERIALIZED_LITERAL, and v8::internal::LiteralProperty::value_.
IsNullPrototype()
bool v8::internal::ObjectLiteralProperty::IsNullPrototype () const [inline]
Definition at line 1273 of file ast.h.
                               {
    return IsPrototype() && value()->IsNullLiteral();
  }
References v8::internal::Expression::IsNullLiteral(), IsPrototype(), and v8::internal::LiteralProperty::value().
IsPrototype()
bool v8::internal::ObjectLiteralProperty::IsPrototype () const [inline]
Definition at line 1276 of file ast.h.
{ return kind() == PROTOTYPE; }
References kind(), and PROTOTYPE.
Referenced by IsNullPrototype(), and v8::internal::Parser::SetFunctionNameFromPropertyName().
kind()
Kind v8::internal::ObjectLiteralProperty::kind () const [inline]
Definition at line 1266 of file ast.h.
{ return kind_; }
References kind_.
Referenced by IsPrototype(), and v8::internal::Parser::SetFunctionNameFromPropertyName().
set_emit_store()
void v8::internal::ObjectLiteral::Property::set_emit_store (bool emit_store)
Definition at line 333 of file ast.cc.
                                                          {
  emit_store_ = emit_store;
}
References emit_store(), and emit_store_.
Referenced by v8::internal::ObjectLiteral::CalculateEmitStore().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 1279 of file ast.h.
Member Data Documentation
emit_store_
bool v8::internal::ObjectLiteralProperty::emit_store_ [private]
Definition at line 1288 of file ast.h.
Referenced by emit_store(), and set_emit_store().
kind_
Kind v8::internal::ObjectLiteralProperty::kind_ [private]
Definition at line 1287 of file ast.h.
Referenced by IsCompileTimeValue(), kind(), and ObjectLiteralProperty().
Zone
friend v8::internal::ObjectLiteralProperty::Zone [private]
Definition at line 1280 of file ast.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc