v8::internal::wasm::AsyncStreamingDecoder Class Reference
Classes
class DecodeFunctionBody
class DecodeFunctionLength
class DecodeModuleHeader
class DecodeNumberOfFunctions
class DecodeSectionID
class DecodeSectionLength
class DecodeSectionPayload
class DecodeVarInt32
class DecodingState
class SectionBuffer
Public Member Functions
AsyncStreamingDecoder (std::unique_ptr< StreamingProcessor > processor)
AsyncStreamingDecoder (const AsyncStreamingDecoder &)=delete
AsyncStreamingDecoder & operator= (const AsyncStreamingDecoder &)=delete
void OnBytesReceived (base::Vector< const uint8_t > bytes) override
void Finish (bool can_use_compiled_module) override
void Abort () override
void NotifyCompilationDiscarded () override
void NotifyNativeModuleCreated (const std::shared_ptr< NativeModule > &native_module) override
Private Member Functions
SectionBuffer * CreateNewBuffer (uint32_t module_offset, uint8_t section_id, size_t length, base::Vector< const uint8_t > length_bytes)
std::unique_ptr< DecodingState > ToErrorState ()
void ProcessModuleHeader ()
void ProcessSection (SectionBuffer *buffer)
void StartCodeSection (int num_functions, std::shared_ptr< WireBytesStorage > wire_bytes_storage, int code_section_start, int code_section_length)
void ProcessFunctionBody (base::Vector< const uint8_t > bytes, uint32_t module_offset)
void Fail ()
bool ok () const
uint32_t module_offset () const
Private Attributes
std::unique_ptr< StreamingProcessor > processor_
std::unique_ptr< StreamingProcessor > failed_processor_
std::unique_ptr< DecodingState > state_
std::vector< std::shared_ptr< SectionBuffer > > section_buffers_
bool code_section_processed_ = false
uint32_t module_offset_ = 0
std::vector< std::vector< uint8_t > > full_wire_bytes_ {{}}
Additional Inherited Members
Detailed Description
Definition at line 25 of file streaming-decoder.cc.
Constructor & Destructor Documentation
AsyncStreamingDecoder() [1/2]
v8::internal::wasm::AsyncStreamingDecoder::AsyncStreamingDecoder (std::unique_ptr< StreamingProcessor > processor) [explicit]
Definition at line 755 of file streaming-decoder.cc.
    : processor_(std::move(processor)),
      // A module always starts with a module header.
      state_(new DecodeModuleHeader()) {}
AsyncStreamingDecoder() [2/2]
v8::internal::wasm::AsyncStreamingDecoder::AsyncStreamingDecoder (const AsyncStreamingDecoder &) [delete]
Member Function Documentation
Abort()
void v8::internal::wasm::AsyncStreamingDecoder::Abort () [override], [virtual]
Implements v8::internal::wasm::StreamingDecoder.
Definition at line 343 of file streaming-decoder.cc.
                                  {
  TRACE_STREAMING("Abort\n");
  // Ignore {Abort} after {Finish}.
  if (!processor_ && !failed_processor_) return;
  Fail();
  failed_processor_->OnAbort();
  failed_processor_.reset();
}
References Fail(), failed_processor_, processor_, and TRACE_STREAMING.
CreateNewBuffer()
AsyncStreamingDecoder::SectionBuffer * v8::internal::wasm::AsyncStreamingDecoder::CreateNewBuffer (uint32_t module_offset, uint8_t section_id, size_t length, base::Vector< const uint8_t > length_bytes) [private]
Definition at line 761 of file streaming-decoder.cc.
                                            {
  // Section buffers are allocated in the same order they appear in the module,
  // they will be processed and later on concatenated in that same order.
  section_buffers_.emplace_back(std::make_shared<SectionBuffer>(
      module_offset, section_id, length, length_bytes));
  return section_buffers_.back().get();
}
References v8::internal::length, module_offset(), and section_buffers_.
Referenced by v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionLength::NextWithValue().
Fail()
void v8::internal::wasm::AsyncStreamingDecoder::Fail () [inline], [private]
Definition at line 198 of file streaming-decoder.cc.
              {
    // {Fail} cannot be called after {Finish}, {Abort}, or
    // {NotifyCompilationDiscarded}.
    DCHECK_EQ(processor_ == nullptr, failed_processor_ != nullptr);
    if (processor_ != nullptr) failed_processor_ = std::move(processor_);
    DCHECK_NULL(processor_);
    DCHECK_NOT_NULL(failed_processor_);
  }
References DCHECK_EQ, DCHECK_NOT_NULL, and DCHECK_NULL.
Referenced by Abort(), Finish(), and v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::ReadBytes().
Finish()
void v8::internal::wasm::AsyncStreamingDecoder::Finish (bool can_use_compiled_module) [override], [virtual]
Implements v8::internal::wasm::StreamingDecoder.
Definition at line 284 of file streaming-decoder.cc.
                                                               {
  TRACE_STREAMING("Finish\n");
  // {Finish} cannot be called after {Finish}, {Abort}, or
  // {NotifyCompilationDiscarded}.
  CHECK_EQ(processor_ == nullptr, failed_processor_ != nullptr);
  // Create a final copy of the overall wire bytes; this will finally be
  // transferred and stored in the NativeModule.
  base::OwnedVector<const uint8_t> bytes_copy;
  DCHECK_IMPLIES(full_wire_bytes_.back().empty(), full_wire_bytes_.size() == 1);
  if (!full_wire_bytes_.back().empty()) {
    size_t total_length = 0;
    for (auto& bytes : full_wire_bytes_) total_length += bytes.size();
    if (ok()) {
      // {DecodeSectionLength} enforces this with graceful error reporting.
      CHECK_LE(total_length, max_module_size());
    }
    auto all_bytes = base::OwnedVector<uint8_t>::NewForOverwrite(total_length);
    uint8_t* ptr = all_bytes.begin();
    for (auto& bytes : full_wire_bytes_) {
      memcpy(ptr, bytes.data(), bytes.size());
      ptr += bytes.size();
    }
    DCHECK_EQ(all_bytes.end(), ptr);
    bytes_copy = std::move(all_bytes);
  }
  if (ok() && deserializing()) {
    // Try to deserialize the module from wire bytes and module bytes.
    if (can_use_compiled_module &&
        processor_->Deserialize(compiled_module_bytes_,
                                base::VectorOf(bytes_copy))) {
      return;
    }
    // Compiled module bytes are invalidated by can_use_compiled_module = false
    // or the deserialization failed. Restart decoding using |bytes_copy|.
    // Reset {full_wire_bytes} to a single empty vector.
    full_wire_bytes_.assign({{}});
    compiled_module_bytes_ = {};
    DCHECK(!deserializing());
    OnBytesReceived(base::VectorOf(bytes_copy));
    // The decoder has received all wire bytes; fall through and finish.
  }
  if (ok() && !state_->is_finishing_allowed()) {
    // The byte stream ended too early, we report an error.
    Fail();
  }
  // Calling {OnFinishedStream} calls out to JS. Avoid further callbacks (by
  // aborting the stream) by resetting the processor field before calling
  // {OnFinishedStream}.
  const bool failed = !ok();
  std::unique_ptr<StreamingProcessor> processor =
      failed ? std::move(failed_processor_) : std::move(processor_);
  processor->OnFinishedStream(std::move(bytes_copy), failed);
}
References CHECK_EQ, CHECK_LE, v8::internal::wasm::StreamingDecoder::compiled_module_bytes_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::wasm::StreamingDecoder::deserializing(), Fail(), failed_processor_, full_wire_bytes_, v8::internal::wasm::max_module_size(), v8::base::OwnedVector< T >::NewForOverwrite(), ok(), OnBytesReceived(), processor_, state_, TRACE_STREAMING, and v8::base::VectorOf().
module_offset()
uint32_t v8::internal::wasm::AsyncStreamingDecoder::module_offset () const [inline], [private]
Definition at line 212 of file streaming-decoder.cc.
{ return module_offset_; }
Referenced by CreateNewBuffer(), v8::internal::wasm::AsyncStreamingDecoder::DecodeModuleHeader::Next(), v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionPayload::Next(), v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody::Next(), v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionLength::NextWithValue(), v8::internal::wasm::AsyncStreamingDecoder::DecodeNumberOfFunctions::NextWithValue(), v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionLength::NextWithValue(), and v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::ReadBytes().
NotifyCompilationDiscarded()
void v8::internal::wasm::AsyncStreamingDecoder::NotifyCompilationDiscarded () [inline], [override], [virtual]
Implements v8::internal::wasm::StreamingDecoder.
Definition at line 37 of file streaming-decoder.cc.
                                             {
    auto& active_processor = processor_ ? processor_ : failed_processor_;
    active_processor.reset();
    DCHECK_NULL(processor_);
    DCHECK_NULL(failed_processor_);
  }
References DCHECK_NULL.
NotifyNativeModuleCreated()
void v8::internal::wasm::AsyncStreamingDecoder::NotifyNativeModuleCreated (const std::shared_ptr< NativeModule > & native_module) [override], [virtual]
Implements v8::internal::wasm::StreamingDecoder.
Definition at line 391 of file streaming-decoder.cc.
                                                      {
  if (!more_functions_can_be_serialized_callback_) return;
  auto* comp_state = native_module->compilation_state();
  comp_state->AddCallback(
      std::make_unique<CallMoreFunctionsCanBeSerializedCallback>(
          native_module,
          std::move(more_functions_can_be_serialized_callback_)));
  more_functions_can_be_serialized_callback_ = {};
}
References v8::internal::wasm::StreamingDecoder::more_functions_can_be_serialized_callback_.
ok()
bool v8::internal::wasm::AsyncStreamingDecoder::ok () const [inline], [private]
Definition at line 207 of file streaming-decoder.cc.
                  {
    DCHECK_EQ(processor_ == nullptr, failed_processor_ != nullptr);
    return processor_ != nullptr;
  }
References DCHECK_EQ.
Referenced by Finish(), v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::Next(), v8::internal::wasm::AsyncStreamingDecoder::DecodeModuleHeader::Next(), v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionPayload::Next(), v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody::Next(), v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionLength::NextWithValue(), v8::internal::wasm::AsyncStreamingDecoder::DecodeNumberOfFunctions::NextWithValue(), and OnBytesReceived().
OnBytesReceived()
void v8::internal::wasm::AsyncStreamingDecoder::OnBytesReceived (base::Vector< const uint8_t > bytes) [override], [virtual]
Implements v8::internal::wasm::StreamingDecoder.
Definition at line 232 of file streaming-decoder.cc.
                                                                           {
  DCHECK(!full_wire_bytes_.empty());
  // Fill the previous vector, growing up to 16kB. After that, allocate new
  // vectors on overflow.
  size_t remaining_capacity =
      std::max(full_wire_bytes_.back().capacity(), size_t{16} * KB) -
      full_wire_bytes_.back().size();
  size_t bytes_for_existing_vector = std::min(remaining_capacity, bytes.size());
  full_wire_bytes_.back().insert(full_wire_bytes_.back().end(), bytes.data(),
                                 bytes.data() + bytes_for_existing_vector);
  if (bytes.size() > bytes_for_existing_vector) {
    // The previous vector's capacity is not enough to hold all new bytes, and
    // it's bigger than 16kB, so expensive to copy. Allocate a new vector for
    // the remaining bytes, growing exponentially.
    size_t new_capacity = std::max(bytes.size() - bytes_for_existing_vector,
                                   2 * full_wire_bytes_.back().capacity());
    full_wire_bytes_.emplace_back();
    full_wire_bytes_.back().reserve(new_capacity);
    full_wire_bytes_.back().insert(full_wire_bytes_.back().end(),
                                   bytes.data() + bytes_for_existing_vector,
                                   bytes.end());
  }
  if (deserializing()) return;
  TRACE_STREAMING("OnBytesReceived(%zu bytes)\n", bytes.size());
  size_t current = 0;
  while (ok() && current < bytes.size()) {
    size_t num_bytes =
        state_->ReadBytes(this, bytes.SubVector(current, bytes.size()));
    current += num_bytes;
    module_offset_ += num_bytes;
    if (state_->offset() == state_->buffer().size()) {
      state_ = state_->Next(this);
    }
  }
  if (ok()) {
    processor_->OnFinishedChunk();
  }
}
References v8::base::Vector< T >::data(), v8::internal::DCHECK(), v8::internal::wasm::StreamingDecoder::deserializing(), v8::base::Vector< T >::end(), full_wire_bytes_, v8::internal::KB, module_offset_, ok(), processor_, v8::base::Vector< T >::size(), state_, v8::base::Vector< T >::SubVector(), and TRACE_STREAMING.
Referenced by Finish().
operator=()
AsyncStreamingDecoder& v8::internal::wasm::AsyncStreamingDecoder::operator= (const AsyncStreamingDecoder &) [delete]
ProcessFunctionBody()
void v8::internal::wasm::AsyncStreamingDecoder::ProcessFunctionBody (base::Vector< const uint8_t > bytes, uint32_t module_offset) [inline], [private]
Definition at line 192 of file streaming-decoder.cc.
                                                   {
    if (!ok()) return;
    if (!processor_->ProcessFunctionBody(bytes, module_offset)) Fail();
  }
Referenced by v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody::Next().
ProcessModuleHeader()
void v8::internal::wasm::AsyncStreamingDecoder::ProcessModuleHeader () [inline], [private]
Definition at line 164 of file streaming-decoder.cc.
                             {
    if (!ok()) return;
    if (!processor_->ProcessModuleHeader(state_->buffer())) Fail();
  }
Referenced by v8::internal::wasm::AsyncStreamingDecoder::DecodeModuleHeader::Next().
ProcessSection()
void v8::internal::wasm::AsyncStreamingDecoder::ProcessSection (SectionBuffer * buffer) [inline], [private]
Definition at line 169 of file streaming-decoder.cc.
                                             {
    if (!ok()) return;
    if (!processor_->ProcessSection(
            buffer->section_code(), buffer->payload(),
            buffer->module_offset() +
                static_cast<uint32_t>(buffer->payload_offset()))) {
      Fail();
    }
  }
References v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::module_offset(), v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::payload(), v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::payload_offset(), and v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::section_code().
Referenced by v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionPayload::Next(), and v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionLength::NextWithValue().
StartCodeSection()
void v8::internal::wasm::AsyncStreamingDecoder::StartCodeSection (int num_functions, std::shared_ptr< WireBytesStorage > wire_bytes_storage, int code_section_start, int code_section_length) [inline], [private]
Definition at line 179 of file streaming-decoder.cc.
                                                                         {
    if (!ok()) return;
    // The offset passed to {ProcessCodeSectionHeader} is an error offset and
    // not the start offset of a buffer. Therefore we need the -1 here.
    if (!processor_->ProcessCodeSectionHeader(
            num_functions, module_offset() - 1, std::move(wire_bytes_storage),
            code_section_start, code_section_length)) {
      Fail();
    }
  }
Referenced by v8::internal::wasm::AsyncStreamingDecoder::DecodeNumberOfFunctions::NextWithValue().
ToErrorState()
std::unique_ptr<DecodingState> v8::internal::wasm::AsyncStreamingDecoder::ToErrorState () [inline], [private]
Definition at line 159 of file streaming-decoder.cc.
                                              {
    Fail();
    return nullptr;
  }
Referenced by v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::Next(), v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionID::Next(), v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody::Next(), v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionLength::NextWithValue(), v8::internal::wasm::AsyncStreamingDecoder::DecodeNumberOfFunctions::NextWithValue(), and v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionLength::NextWithValue().
Member Data Documentation
code_section_processed_
bool v8::internal::wasm::AsyncStreamingDecoder::code_section_processed_ = false [private]
Definition at line 222 of file streaming-decoder.cc.
Referenced by v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionID::Next().
failed_processor_
std::unique_ptr<StreamingProcessor> v8::internal::wasm::AsyncStreamingDecoder::failed_processor_ [private]
Definition at line 219 of file streaming-decoder.cc.
Referenced by Abort(), and Finish().
full_wire_bytes_
std::vector<std::vector<uint8_t> > v8::internal::wasm::AsyncStreamingDecoder::full_wire_bytes_ {{}} [private]
Definition at line 229 of file streaming-decoder.cc.
Referenced by Finish(), and OnBytesReceived().
module_offset_
uint32_t v8::internal::wasm::AsyncStreamingDecoder::module_offset_ = 0 [private]
Definition at line 223 of file streaming-decoder.cc.
Referenced by v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionID::Next(), v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionBody::Next(), v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionLength::NextWithValue(), and OnBytesReceived().
processor_
std::unique_ptr<StreamingProcessor> v8::internal::wasm::AsyncStreamingDecoder::processor_ [private]
Definition at line 218 of file streaming-decoder.cc.
Referenced by Abort(), Finish(), and OnBytesReceived().
section_buffers_
std::vector<std::shared_ptr<SectionBuffer> > v8::internal::wasm::AsyncStreamingDecoder::section_buffers_ [private]
Definition at line 221 of file streaming-decoder.cc.
Referenced by CreateNewBuffer(), and v8::internal::wasm::AsyncStreamingDecoder::DecodeNumberOfFunctions::NextWithValue().
state_
std::unique_ptr<DecodingState> v8::internal::wasm::AsyncStreamingDecoder::state_ [private]
Definition at line 220 of file streaming-decoder.cc.
Referenced by Finish(), and OnBytesReceived().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/streaming-decoder.cc