v8::internal::SmallOrderedNameDictionary Class Reference
#include <ordered-hash-table.h>
Public Member Functions
Tagged< Object > ValueAt (InternalIndex entry)
void ValueAtPut (InternalIndex entry, Tagged< Object > value)
PropertyDetails DetailsAt (InternalIndex entry)
void DetailsAtPut (InternalIndex entry, PropertyDetails value)
void SetHash (int hash)
int Hash ()
V8_EXPORT_PRIVATE void SetEntry (InternalIndex entry, Tagged< Object > key, Tagged< Object > value, PropertyDetails details)
OBJECT_CONSTRUCTORS (SmallOrderedNameDictionary, SmallOrderedHashTable< SmallOrderedNameDictionary >)
Static Public Member Functions
static Handle< SmallOrderedNameDictionary > Rehash (Isolate *isolate, Handle< SmallOrderedNameDictionary > table, int new_capacity)
static V8_EXPORT_PRIVATE Handle< SmallOrderedNameDictionary > DeleteEntry (Isolate *isolate, Handle< SmallOrderedNameDictionary > table, InternalIndex entry)
static V8_EXPORT_PRIVATE MaybeHandle< SmallOrderedNameDictionary > Add (Isolate *isolate, Handle< SmallOrderedNameDictionary > table, DirectHandle< Name > key, DirectHandle< Object > value, PropertyDetails details)
static DirectHandle< Map > GetMap (RootsTable &roots)
static bool Is (DirectHandle< HeapObject > table)
Static Public Attributes
static const int kKeyIndex = 0
static const int kValueIndex = 1
static const int kPropertyDetailsIndex = 2
static const int kEntrySize = 3
static const int kPrefixSize = 1
Additional Inherited Members
Detailed Description
Definition at line 905 of file ordered-hash-table.h.
Member Function Documentation
Add()
MaybeHandle< SmallOrderedNameDictionary > v8::internal::SmallOrderedNameDictionary::Add (Isolate * isolate, Handle< SmallOrderedNameDictionary > table, DirectHandle< Name > key, DirectHandle< Object > value, PropertyDetails details) [static]
Definition at line 835 of file ordered-hash-table.cc.
                             {
  DCHECK(IsUniqueName(*key));
  DCHECK(table->FindEntry(isolate, *key).is_not_found());
  if (table->UsedCapacity() >= table->Capacity()) {
    MaybeHandle<SmallOrderedNameDictionary> new_table =
        SmallOrderedNameDictionary::Grow(isolate, table);
    if (!new_table.ToHandle(&table)) {
      return MaybeHandle<SmallOrderedNameDictionary>();
    }
  }
  int nof = table->NumberOfElements();
  // Read the existing bucket values.
  int hash = key->hash();
  int bucket = table->HashToBucket(hash);
  int previous_entry = table->HashToFirstEntry(hash);
  // Insert a new entry at the end,
  int new_entry = nof + table->NumberOfDeletedElements();
  table->SetDataEntry(new_entry, SmallOrderedNameDictionary::kValueIndex,
                      *value);
  table->SetDataEntry(new_entry, SmallOrderedNameDictionary::kKeyIndex, *key);
  // TODO(gsathya): PropertyDetails should be stored as part of the
  // data table to save more memory.
  table->SetDataEntry(new_entry,
                      SmallOrderedNameDictionary::kPropertyDetailsIndex,
                      details.AsSmi());
  table->SetFirstEntry(bucket, new_entry);
  table->SetNextEntry(new_entry, previous_entry);
  // and update book keeping.
  table->SetNumberOfElements(nof + 1);
  return table;
}
References v8::internal::PropertyDetails::AsSmi(), DCHECK, cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow(), v8::internal::IsUniqueName(), v8::internal::key, v8::internal::MaybeHandle< T >::ToHandle(), and v8::internal::value.
DeleteEntry()
Handle< SmallOrderedNameDictionary > v8::internal::SmallOrderedNameDictionary::DeleteEntry (Isolate * isolate, Handle< SmallOrderedNameDictionary > table, InternalIndex entry) [static]
Definition at line 922 of file ordered-hash-table.cc.
                         {
  DCHECK(entry.is_found());
  {
    DisallowGarbageCollection no_gc;
    Tagged<Object> the_hole = ReadOnlyRoots(isolate).the_hole_value();
    PropertyDetails details = PropertyDetails::Empty();
    table->SetEntry(entry, the_hole, the_hole, details);
    int nof = table->NumberOfElements();
    table->SetNumberOfElements(nof - 1);
    int nod = table->NumberOfDeletedElements();
    table->SetNumberOfDeletedElements(nod + 1);
  }
  return Shrink(isolate, table);
}
References DCHECK, v8::internal::InternalIndex::is_found(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink().
DetailsAt()
PropertyDetails v8::internal::SmallOrderedNameDictionary::DetailsAt (InternalIndex entry) [inline]
Definition at line 142 of file ordered-hash-table-inl.h.
                         {
  // TODO(gsathya): Optimize the cast away. And store this in the data table.
  return PropertyDetails(
      Cast<Smi>(this->GetDataEntry(entry.as_int(), kPropertyDetailsIndex)));
}
References v8::internal::InternalIndex::as_int(), v8::internal::SmallOrderedHashTable< SmallOrderedNameDictionary >::GetDataEntry(), and kPropertyDetailsIndex.
DetailsAtPut()
void v8::internal::SmallOrderedNameDictionary::DetailsAtPut (InternalIndex entry, PropertyDetails value) [inline]
Definition at line 150 of file ordered-hash-table-inl.h.
                                                                            {
  // TODO(gsathya): Optimize the cast away. And store this in the data table.
  this->SetDataEntry(entry.as_int(), kPropertyDetailsIndex, value.AsSmi());
}
References v8::internal::InternalIndex::as_int(), kPropertyDetailsIndex, v8::internal::SmallOrderedHashTable< SmallOrderedNameDictionary >::SetDataEntry(), and v8::internal::value.
GetMap()
DirectHandle< Map > v8::internal::SmallOrderedNameDictionary::GetMap (RootsTable & roots) [inline], [static]
Definition at line 72 of file ordered-hash-table-inl.h.
                                                                      {
  return roots.small_ordered_name_dictionary_map();
}
Hash()
int v8::internal::SmallOrderedNameDictionary::Hash () [inline]
Definition at line 205 of file ordered-hash-table-inl.h.
                                            {
  int hash = ReadField<int>(PrefixOffset());
  DCHECK(PropertyArray::HashField::is_valid(hash));
  return hash;
}
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::is_valid(), and v8::internal::SmallOrderedHashTable< SmallOrderedNameDictionary >::PrefixOffset().
Is()
bool v8::internal::SmallOrderedNameDictionary::Is (DirectHandle< HeapObject > table) [inline], [static]
Definition at line 172 of file ordered-hash-table-inl.h.
                                                                         {
  return IsSmallOrderedNameDictionary(*table);
}
OBJECT_CONSTRUCTORS()
v8::internal::SmallOrderedNameDictionary::OBJECT_CONSTRUCTORS (SmallOrderedNameDictionary , SmallOrderedHashTable< SmallOrderedNameDictionary >)
Rehash()
Handle< SmallOrderedNameDictionary > v8::internal::SmallOrderedNameDictionary::Rehash (Isolate * isolate, Handle< SmallOrderedNameDictionary > table, int new_capacity) [static]
Definition at line 990 of file ordered-hash-table.cc.
                      {
  Handle<SmallOrderedNameDictionary> new_table =
      SmallOrderedHashTable<SmallOrderedNameDictionary>::Rehash(isolate, table,
                                                                new_capacity);
  new_table->SetHash(table->Hash());
  return new_table;
}
SetEntry()
void v8::internal::SmallOrderedNameDictionary::SetEntry (InternalIndex entry, Tagged< Object > key, Tagged< Object > value, PropertyDetails details)
Definition at line 878 of file ordered-hash-table.cc.
                                                                   {
  int raw_entry = entry.as_int();
  DCHECK_IMPLIES(!IsName(key), IsTheHole(key));
  SetDataEntry(raw_entry, SmallOrderedNameDictionary::kValueIndex, value);
  SetDataEntry(raw_entry, SmallOrderedNameDictionary::kKeyIndex, key);
  // TODO(gsathya): PropertyDetails should be stored as part of the
  // data table to save more memory.
  SetDataEntry(raw_entry, SmallOrderedNameDictionary::kPropertyDetailsIndex,
               details.AsSmi());
}
References v8::internal::InternalIndex::as_int(), v8::internal::PropertyDetails::AsSmi(), DCHECK_IMPLIES, v8::internal::key, and v8::internal::value.
SetHash()
void v8::internal::SmallOrderedNameDictionary::SetHash (int hash) [inline]
Definition at line 200 of file ordered-hash-table-inl.h.
                                                        {
  DCHECK(PropertyArray::HashField::is_valid(hash));
  WriteField<int>(PrefixOffset(), hash);
}
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::is_valid(), and v8::internal::SmallOrderedHashTable< SmallOrderedNameDictionary >::PrefixOffset().
ValueAt()
Tagged< Object > v8::internal::SmallOrderedNameDictionary::ValueAt (InternalIndex entry) [inline]
Definition at line 131 of file ordered-hash-table-inl.h.
                                                                             {
  return this->GetDataEntry(entry.as_int(), kValueIndex);
}
References v8::internal::InternalIndex::as_int(), v8::internal::SmallOrderedHashTable< SmallOrderedNameDictionary >::GetDataEntry(), and kValueIndex.
ValueAtPut()
void v8::internal::SmallOrderedNameDictionary::ValueAtPut (InternalIndex entry, Tagged< Object > value) [inline]
Definition at line 136 of file ordered-hash-table-inl.h.
                                                                         {
  this->SetDataEntry(entry.as_int(), kValueIndex, value);
}
References v8::internal::InternalIndex::as_int(), kValueIndex, v8::internal::SmallOrderedHashTable< SmallOrderedNameDictionary >::SetDataEntry(), and v8::internal::value.
Member Data Documentation
kEntrySize
const int v8::internal::SmallOrderedNameDictionary::kEntrySize = 3 [static]
Definition at line 937 of file ordered-hash-table.h.
kKeyIndex
const int v8::internal::SmallOrderedNameDictionary::kKeyIndex = 0 [static]
Definition at line 934 of file ordered-hash-table.h.
kPrefixSize
const int v8::internal::SmallOrderedNameDictionary::kPrefixSize = 1 [static]
Definition at line 938 of file ordered-hash-table.h.
kPropertyDetailsIndex
const int v8::internal::SmallOrderedNameDictionary::kPropertyDetailsIndex = 2 [static]
Definition at line 936 of file ordered-hash-table.h.
Referenced by DetailsAt(), and DetailsAtPut().
kValueIndex
const int v8::internal::SmallOrderedNameDictionary::kValueIndex = 1 [static]
Definition at line 935 of file ordered-hash-table.h.
Referenced by ValueAt(), and ValueAtPut().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/ordered-hash-table.h
/mnt/V8SourceCode/src/objects/ordered-hash-table-inl.h
/mnt/V8SourceCode/src/objects/ordered-hash-table.cc