v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever Class Reference
Public Member Functions
ScopeChainRetriever (DeclarationScope *scope, DirectHandle< JSFunction > function, int position)
DeclarationScope * ClosureScope ()
Scope * StartScope ()
Private Member Functions
void RetrieveScopes ()
bool RetrieveClosureScope (Scope *scope)
void RetrieveStartScope (Scope *scope)
bool ContainsPosition (Scope *scope)
Private Attributes
DeclarationScope * scope_
const int break_scope_start_
const int break_scope_end_
const ScopeType break_scope_type_
const int position_
DeclarationScope * closure_scope_ = nullptr
Scope * start_scope_ = nullptr
Detailed Description
Definition at line 105 of file debug-scopes.cc.
Constructor & Destructor Documentation
ScopeChainRetriever()
v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::ScopeChainRetriever (DeclarationScope * scope, DirectHandle< JSFunction > function, int position) [inline]
Definition at line 107 of file debug-scopes.cc.
      : scope_(scope),
        break_scope_start_(function->shared()->StartPosition()),
        break_scope_end_(function->shared()->EndPosition()),
        break_scope_type_(function->shared()->scope_info()->scope_type()),
        position_(position) {
    DCHECK_NOT_NULL(scope);
    RetrieveScopes();
  }
References DCHECK_NOT_NULL.
Member Function Documentation
ClosureScope()
DeclarationScope* v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::ClosureScope () [inline]
Definition at line 118 of file debug-scopes.cc.
{ return closure_scope_; }
ContainsPosition()
bool v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::ContainsPosition (Scope * scope) [inline], [private]
Definition at line 182 of file debug-scopes.cc.
                                      {
    const int start = scope->start_position();
    const int end = scope->end_position();
    // In case the closure_scope_ hasn't been found yet, we are less strict
    // about recursing downwards. This might be the case for nested arrow
    // functions that have the same end position.
    const bool position_fits_end =
        closure_scope_ ? position_ < end : position_ <= end;
    // While we're evaluating a class, the calling function will have a class
    // context on the stack with a range that starts at Token::kClass, and the
    // source position will also point to Token::kClass. To identify the
    // matching scope we include start in the accepted range for class scopes.
    //
    // Similarly "with" scopes can already have bytecodes where the source
    // position points to the closing parenthesis with the "with" context
    // already pushed.
    const bool position_fits_start =
        scope->is_class_scope() || scope->is_with_scope() ? start <= position_
                                                          : start < position_;
    return position_fits_start && position_fits_end;
  }
References v8::internal::compiler::end(), v8::internal::Scope::end_position(), v8::internal::Scope::is_class_scope(), v8::internal::Scope::is_with_scope(), and v8::internal::Scope::start_position().
RetrieveClosureScope()
bool v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::RetrieveClosureScope (Scope * scope) [inline], [private]
Definition at line 144 of file debug-scopes.cc.
                                          {
    // The closure scope is the scope that matches exactly the function we
    // paused in.
    // Note that comparing the position alone is not enough and we also need to
    // match the scope type. E.g. class member initializer have the exact same
    // scope positions as their class scope.
    if (break_scope_type_ == scope->scope_type() &&
        break_scope_start_ == scope->start_position() &&
        break_scope_end_ == scope->end_position()) {
      closure_scope_ = scope->AsDeclarationScope();
      return true;
    }
    for (Scope* inner_scope = scope->inner_scope(); inner_scope != nullptr;
         inner_scope = inner_scope->sibling()) {
      if (RetrieveClosureScope(inner_scope)) return true;
    }
    return false;
  }
References v8::internal::Scope::AsDeclarationScope(), v8::internal::Scope::end_position(), v8::internal::Scope::inner_scope(), v8::internal::Scope::scope_type(), v8::internal::Scope::sibling(), and v8::internal::Scope::start_position().
RetrieveScopes()
void v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::RetrieveScopes () [inline], [private]
Definition at line 131 of file debug-scopes.cc.
                        {
    // 1. Find the closure scope with a DFS.
    RetrieveClosureScope(scope_);
    DCHECK_NOT_NULL(closure_scope_);
    // 2. Starting from the closure scope search inwards. Given that V8's scope
    // tree doesn't guarantee that siblings don't overlap, we look at all
    // scopes and pick the one with the tightest bounds around `position_`.
    start_scope_ = closure_scope_;
    RetrieveStartScope(closure_scope_);
    DCHECK_NOT_NULL(start_scope_);
  }
References DCHECK_NOT_NULL.
RetrieveStartScope()
void v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::RetrieveStartScope (Scope * scope) [inline], [private]
Definition at line 164 of file debug-scopes.cc.
                                        {
    const int start = scope->start_position();
    const int end = scope->end_position();
    // Update start_scope_ if scope contains `position_` and scope is a tighter
    // fit than the currently set start_scope_.
    // Generators have the same source position so we also check for equality.
    if (ContainsPosition(scope) && start >= start_scope_->start_position() &&
        end <= start_scope_->end_position()) {
      start_scope_ = scope;
    }
    for (Scope* inner_scope = scope->inner_scope(); inner_scope != nullptr;
         inner_scope = inner_scope->sibling()) {
      RetrieveStartScope(inner_scope);
    }
  }
References v8::internal::compiler::end(), v8::internal::Scope::end_position(), v8::internal::Scope::inner_scope(), v8::internal::Scope::sibling(), and v8::internal::Scope::start_position().
StartScope()
Scope* v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::StartScope () [inline]
Definition at line 119 of file debug-scopes.cc.
{ return start_scope_; }
Member Data Documentation
break_scope_end_
const int v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::break_scope_end_ [private]
Definition at line 124 of file debug-scopes.cc.
break_scope_start_
const int v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::break_scope_start_ [private]
Definition at line 123 of file debug-scopes.cc.
break_scope_type_
const ScopeType v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::break_scope_type_ [private]
Definition at line 125 of file debug-scopes.cc.
closure_scope_
DeclarationScope* v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::closure_scope_ = nullptr [private]
Definition at line 128 of file debug-scopes.cc.
position_
const int v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::position_ [private]
Definition at line 126 of file debug-scopes.cc.
scope_
DeclarationScope* v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::scope_ [private]
Definition at line 122 of file debug-scopes.cc.
start_scope_
Scope* v8::internal::anonymous_namespace{debug-scopes.cc}::ScopeChainRetriever::start_scope_ = nullptr [private]
Definition at line 129 of file debug-scopes.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-scopes.cc