v8::internal::OptimizingCompileDispatcher Class Reference
#include <optimizing-compile-dispatcher.h>
Public Member Functions
OptimizingCompileDispatcher (Isolate *isolate, OptimizingCompileTaskExecutor *task_executor)
~OptimizingCompileDispatcher ()
void Flush (BlockingBehavior blocking_behavior)
bool TryQueueForOptimization (std::unique_ptr< TurbofanCompilationJob > &job)
void WaitUntilCompilationJobsDone ()
void InstallOptimizedFunctions ()
int InstallGeneratedBuiltins (int installed_count)
bool IsQueueAvailable ()
bool HasJobs ()
bool finalize () const
void set_finalize (bool finalize)
void Prioritize (Tagged< SharedFunctionInfo > function)
void StartTearDown ()
void FinishTearDown ()
void QueueFinishedJob (TurbofanCompilationJob *job)
Static Public Member Functions
static bool Enabled ()
Private Types
enum ModeFlag { COMPILE
, FLUSH
 }
Private Member Functions
void FlushQueues (BlockingBehavior blocking_behavior)
void FlushInputQueue ()
void FlushOutputQueue ()
OptimizingCompileInputQueue & input_queue ()
int recompilation_delay () const
Private Attributes
Isolate * isolate_
OptimizingCompileTaskExecutor * task_executor_
OptimizingCompileOutputQueue output_queue_
bool finalize_ = true
Detailed Description
Definition at line 176 of file optimizing-compile-dispatcher.h.
Member Enumeration Documentation
ModeFlag
enum v8::internal::OptimizingCompileDispatcher::ModeFlag [private]
Enumerator
COMPILE
FLUSH
Definition at line 229 of file optimizing-compile-dispatcher.h.
{ COMPILE, FLUSH };
Constructor & Destructor Documentation
OptimizingCompileDispatcher()
v8::internal::OptimizingCompileDispatcher::OptimizingCompileDispatcher (Isolate * isolate, OptimizingCompileTaskExecutor * task_executor) [explicit]
Definition at line 253 of file optimizing-compile-dispatcher.cc.
    : isolate_(isolate), task_executor_(task_executor) {}
 OptimizingCompileDispatcher()
v8::internal::OptimizingCompileDispatcher::~OptimizingCompileDispatcher ()
Definition at line 257 of file optimizing-compile-dispatcher.cc.
                                                          {
  DCHECK_EQ(output_queue_.size(), 0);
}
References DCHECK_EQ, output_queue_, and v8::internal::OptimizingCompileOutputQueue::size().
Member Function Documentation
Enabled()
static bool v8::internal::OptimizingCompileDispatcher::Enabled () [inline], [static]
Definition at line 205 of file optimizing-compile-dispatcher.h.
{ return v8_flags.concurrent_recompilation; }
References v8::internal::v8_flags.
Referenced by v8::internal::Isolate::Init(), and v8::internal::maglev::MaglevGraphBuilder::ShouldEmitOsrInterruptBudgetChecks().
finalize()
bool v8::internal::OptimizingCompileDispatcher::finalize () const [inline]
Definition at line 215 of file optimizing-compile-dispatcher.h.
{ return finalize_; }
Referenced by QueueFinishedJob().
FinishTearDown()
void v8::internal::OptimizingCompileDispatcher::FinishTearDown ()
Definition at line 276 of file optimizing-compile-dispatcher.cc.
                                                 {
  task_executor_->WaitUntilCompilationJobsDoneForIsolate(isolate_);
  HandleScope handle_scope(isolate_);
  FlushOutputQueue();
}
References FlushOutputQueue(), isolate_, task_executor_, and v8::internal::OptimizingCompileTaskExecutor::WaitUntilCompilationJobsDoneForIsolate().
Referenced by v8::internal::Isolate::Deinit(), and v8::Shell::RunMain().
Flush()
void v8::internal::OptimizingCompileDispatcher::Flush (BlockingBehavior blocking_behavior)
Definition at line 304 of file optimizing-compile-dispatcher.cc.
                                                                          {
  HandleScope handle_scope(isolate_);
  FlushQueues(blocking_behavior);
  if (v8_flags.trace_concurrent_recompilation) {
    PrintF(" ** Flushed concurrent recompilation queues. (mode: %s)\n",
           (blocking_behavior == BlockingBehavior::kBlock) ? "blocking"
                                                           : "non blocking");
  }
}
References FlushQueues(), isolate_, v8::internal::kBlock, v8::internal::PrintF(), and v8::internal::v8_flags.
Referenced by v8::internal::Isolate::AbortConcurrentOptimization().
FlushInputQueue()
void v8::internal::OptimizingCompileDispatcher::FlushInputQueue () [private]
Definition at line 283 of file optimizing-compile-dispatcher.cc.
                                                  {
  input_queue().FlushJobsForIsolate(isolate_);
}
References v8::internal::OptimizingCompileInputQueue::FlushJobsForIsolate(), input_queue(), and isolate_.
Referenced by FlushQueues(), and StartTearDown().
FlushOutputQueue()
void v8::internal::OptimizingCompileDispatcher::FlushOutputQueue () [private]
Definition at line 268 of file optimizing-compile-dispatcher.cc.
                                                   {
  for (;;) {
    std::unique_ptr<TurbofanCompilationJob> job = output_queue_.Dequeue();
    if (!job) break;
    Compiler::DisposeTurbofanCompilationJob(isolate_, job.get());
  }
}
References v8::internal::OptimizingCompileOutputQueue::Dequeue(), v8::internal::Compiler::DisposeTurbofanCompilationJob(), isolate_, and output_queue_.
Referenced by FinishTearDown(), and FlushQueues().
FlushQueues()
void v8::internal::OptimizingCompileDispatcher::FlushQueues (BlockingBehavior blocking_behavior) [private]
Definition at line 294 of file optimizing-compile-dispatcher.cc.
                                        {
  FlushInputQueue();
  task_executor_->CancelCompilationJobsForIsolate(isolate_);
  if (blocking_behavior == BlockingBehavior::kBlock) {
    WaitUntilCompilationJobsDone();
  }
  FlushOutputQueue();
}
References v8::internal::OptimizingCompileTaskExecutor::CancelCompilationJobsForIsolate(), FlushInputQueue(), FlushOutputQueue(), isolate_, v8::internal::kBlock, task_executor_, and WaitUntilCompilationJobsDone().
Referenced by Flush().
HasJobs()
bool v8::internal::OptimizingCompileDispatcher::HasJobs ()
Definition at line 358 of file optimizing-compile-dispatcher.cc.
                                          {
  DCHECK_EQ(ThreadId::Current(), isolate_->thread_id());
  if (task_executor_->HasCompilationJobsForIsolate(isolate_)) {
    return true;
  }
  return !output_queue_.empty();
}
References v8::internal::ThreadId::Current(), DCHECK_EQ, v8::internal::OptimizingCompileOutputQueue::empty(), v8::internal::OptimizingCompileTaskExecutor::HasCompilationJobsForIsolate(), isolate_, output_queue_, task_executor_, and v8::internal::Isolate::thread_id().
input_queue()
OptimizingCompileInputQueue& v8::internal::OptimizingCompileDispatcher::input_queue () [inline], [private]
Definition at line 235 of file optimizing-compile-dispatcher.h.
                                             {
    return task_executor_->input_queue_;
  }
Referenced by FlushInputQueue(), and Prioritize().
InstallGeneratedBuiltins()
int v8::internal::OptimizingCompileDispatcher::InstallGeneratedBuiltins (int installed_count)
Definition at line 354 of file optimizing-compile-dispatcher.cc.
                                                                             {
  return output_queue_.InstallGeneratedBuiltins(isolate_, installed_count);
}
References v8::internal::OptimizingCompileOutputQueue::InstallGeneratedBuiltins(), isolate_, and output_queue_.
InstallOptimizedFunctions()
void v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions ()
Definition at line 321 of file optimizing-compile-dispatcher.cc.
                                                            {
  HandleScope handle_scope(isolate_);
  for (;;) {
    std::unique_ptr<TurbofanCompilationJob> job = output_queue_.Dequeue();
    if (!job) break;
    OptimizedCompilationInfo* info = job->compilation_info();
    DirectHandle<JSFunction> function(*info->closure(), isolate_);
    // If another racing task has already finished compiling and installing the
    // requested code kind on the function, throw out the current job.
    if (!info->is_osr() &&
        function->HasAvailableCodeKind(isolate_, info->code_kind())) {
      if (v8_flags.trace_concurrent_recompilation) {
        PrintF(" ** Aborting compilation for ");
        ShortPrint(*function);
        PrintF(" as it has already been optimized.\n");
      }
      Compiler::DisposeTurbofanCompilationJob(isolate_, job.get());
      continue;
    }
    // Discard code compiled for a discarded native context without
    // finalization.
    if (function->native_context()->global_object()->IsDetached(isolate_)) {
      Compiler::DisposeTurbofanCompilationJob(isolate_, job.get());
      continue;
    }
    Compiler::FinalizeTurbofanCompilationJob(job.get(), isolate_);
  }
}
References v8::internal::OptimizedCompilationInfo::closure(), v8::internal::OptimizedCompilationInfo::code_kind(), v8::internal::OptimizingCompileOutputQueue::Dequeue(), v8::internal::Compiler::DisposeTurbofanCompilationJob(), v8::internal::Compiler::FinalizeTurbofanCompilationJob(), v8::internal::OptimizedCompilationInfo::is_osr(), isolate_, output_queue_, v8::internal::PrintF(), v8::internal::ShortPrint(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{runtime-test.cc}::FinalizeOptimization(), and v8::internal::StackGuard::HandleInterrupts().
IsQueueAvailable()
bool v8::internal::OptimizingCompileDispatcher::IsQueueAvailable () [inline]
Definition at line 203 of file optimizing-compile-dispatcher.h.
{ return input_queue().IsAvailable(); }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_Concurrent().
Prioritize()
void v8::internal::OptimizingCompileDispatcher::Prioritize (Tagged< SharedFunctionInfo > function)
Definition at line 372 of file optimizing-compile-dispatcher.cc.
                                         {
  input_queue().Prioritize(isolate_, function);
}
References input_queue(), isolate_, and v8::internal::OptimizingCompileInputQueue::Prioritize().
Referenced by v8::internal::Isolate::IncreaseConcurrentOptimizationPriority().
QueueFinishedJob()
void v8::internal::OptimizingCompileDispatcher::QueueFinishedJob (TurbofanCompilationJob * job)
Definition at line 261 of file optimizing-compile-dispatcher.cc.
                                 {
  DCHECK_EQ(isolate_, job->isolate());
  output_queue_.Enqueue(job);
  if (finalize()) isolate_->stack_guard()->RequestInstallCode();
}
References DCHECK_EQ, v8::internal::OptimizingCompileOutputQueue::Enqueue(), finalize(), v8::internal::TurbofanCompilationJob::isolate(), isolate_, output_queue_, and v8::internal::Isolate::stack_guard().
Referenced by v8::internal::OptimizingCompileTaskExecutor::RunCompilationJob().
recompilation_delay()
int v8::internal::OptimizingCompileDispatcher::recompilation_delay () const [inline], [private]
Definition at line 239 of file optimizing-compile-dispatcher.h.
                                  {
    return task_executor_->recompilation_delay_;
  }
set_finalize()
void v8::internal::OptimizingCompileDispatcher::set_finalize (bool finalize) [inline]
Definition at line 216 of file optimizing-compile-dispatcher.h.
                                   {
    CHECK(!HasJobs());
    finalize_ = finalize;
  }
References CHECK.
Referenced by v8::internal::anonymous_namespace{runtime-test.cc}::FinalizeOptimization(), and v8::internal::Isolate::Init().
StartTearDown()
void v8::internal::OptimizingCompileDispatcher::StartTearDown ()
Definition at line 314 of file optimizing-compile-dispatcher.cc.
                                                {
  HandleScope handle_scope(isolate_);
  FlushInputQueue();
  task_executor_->CancelCompilationJobsForIsolate(isolate_);
}
References v8::internal::OptimizingCompileTaskExecutor::CancelCompilationJobsForIsolate(), FlushInputQueue(), isolate_, and task_executor_.
Referenced by v8::internal::Isolate::Deinit(), and v8::Shell::RunMain().
TryQueueForOptimization()
bool v8::internal::OptimizingCompileDispatcher::TryQueueForOptimization (std::unique_ptr< TurbofanCompilationJob > & job)
Definition at line 367 of file optimizing-compile-dispatcher.cc.
                                                {
  return task_executor_->TryQueueForOptimization(job);
}
References task_executor_, and v8::internal::OptimizingCompileTaskExecutor::TryQueueForOptimization().
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_Concurrent().
WaitUntilCompilationJobsDone()
void v8::internal::OptimizingCompileDispatcher::WaitUntilCompilationJobsDone ()
Definition at line 287 of file optimizing-compile-dispatcher.cc.
                                                               {
  AllowGarbageCollection allow_before_parking;
  isolate_->main_thread_local_isolate()->ExecuteMainThreadWhileParked([this]() {
    task_executor_->WaitUntilCompilationJobsDoneForIsolate(isolate_);
  });
}
References v8::internal::LocalIsolate::ExecuteMainThreadWhileParked(), isolate_, v8::internal::Isolate::main_thread_local_isolate(), task_executor_, and v8::internal::OptimizingCompileTaskExecutor::WaitUntilCompilationJobsDoneForIsolate().
Referenced by v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::AwaitAndFinalizeCurrentBatch(), v8::internal::anonymous_namespace{runtime-test.cc}::FinalizeOptimization(), and FlushQueues().
Member Data Documentation
finalize_
bool v8::internal::OptimizingCompileDispatcher::finalize_ = true [private]
Definition at line 249 of file optimizing-compile-dispatcher.h.
isolate_
Isolate* v8::internal::OptimizingCompileDispatcher::isolate_ [private]
Definition at line 243 of file optimizing-compile-dispatcher.h.
Referenced by FinishTearDown(), Flush(), FlushInputQueue(), FlushOutputQueue(), FlushQueues(), HasJobs(), InstallGeneratedBuiltins(), InstallOptimizedFunctions(), Prioritize(), QueueFinishedJob(), StartTearDown(), and WaitUntilCompilationJobsDone().
output_queue_
OptimizingCompileOutputQueue v8::internal::OptimizingCompileDispatcher::output_queue_ [private]
Definition at line 247 of file optimizing-compile-dispatcher.h.
Referenced by FlushOutputQueue(), HasJobs(), InstallGeneratedBuiltins(), InstallOptimizedFunctions(), QueueFinishedJob(), and ~OptimizingCompileDispatcher().
task_executor_
OptimizingCompileTaskExecutor* v8::internal::OptimizingCompileDispatcher::task_executor_ [private]
Definition at line 245 of file optimizing-compile-dispatcher.h.
Referenced by FinishTearDown(), FlushQueues(), HasJobs(), StartTearDown(), TryQueueForOptimization(), and WaitUntilCompilationJobsDone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler-dispatcher/optimizing-compile-dispatcher.h
/mnt/V8SourceCode/src/compiler-dispatcher/optimizing-compile-dispatcher.cc