v8::internal::LogFile Class Reference
#include <log-file.h>
Classes
class MessageBuilder
Public Member Functions
LogFile (V8FileLogger *logger, std::string log_file_name)
FILE * Close ()
std::string file_name () const
std::unique_ptr< LogFile::MessageBuilder > NewMessageBuilder ()
Static Public Member Functions
static V8_EXPORT_PRIVATE bool IsLoggingToConsole (std::string file_name)
static V8_EXPORT_PRIVATE bool IsLoggingToTemporaryFile (std::string file_name)
Static Public Attributes
static const int kMessageBufferSize = 2048
static V8_EXPORT_PRIVATE const char *const kLogToTemporaryFile = `+`
static const char *const kLogToConsole = `-`
Private Member Functions
base::Mutex * mutex ()
void WriteLogHeader ()
Static Private Member Functions
static FILE * CreateOutputHandle (std::string file_name)
Private Attributes
V8FileLogger * logger_
std::string file_name_
FILE * output_handle_
OFStream os_
base::Mutex mutex_
std::unique_ptr< char[]> format_buffer_
Friends
class V8FileLogger
Detailed Description
Definition at line 36 of file log-file.h.
Constructor & Destructor Documentation
LogFile()
v8::internal::LogFile::LogFile (V8FileLogger * logger, std::string log_file_name) [explicit]
Definition at line 55 of file log-file.cc.
    : logger_(logger),
      file_name_(file_name),
      output_handle_(LogFile::CreateOutputHandle(file_name)),
      os_(output_handle_ == nullptr ? stdout : output_handle_),
      format_buffer_(NewArray<char>(kMessageBufferSize)) {
  if (output_handle_) WriteLogHeader();
}
References output_handle_, and WriteLogHeader().
Member Function Documentation
Close()
FILE * v8::internal::LogFile::Close ()
Definition at line 96 of file log-file.cc.
                     {
  FILE* result = nullptr;
  if (output_handle_ != nullptr) {
    fflush(output_handle_);
    result = output_handle_;
  }
  output_handle_ = nullptr;
  format_buffer_.reset();
  return result;
}
References format_buffer_, output_handle_, and v8::base::internal::result.
CreateOutputHandle()
FILE * v8::internal::LogFile::CreateOutputHandle (std::string file_name) [static], [private]
Definition at line 32 of file log-file.cc.
                                                     {
  // If we're logging anything, we need to open the log file.
  if (!v8_flags.log) {
    return nullptr;
  } else if (LogFile::IsLoggingToConsole(file_name)) {
    return stdout;
  } else if (LogFile::IsLoggingToTemporaryFile(file_name)) {
    return base::OS::OpenTemporaryFile();
  } else {
    return base::OS::FOpen(file_name.c_str(), base::OS::LogFileOpenMode);
  }
}
References file_name(), v8::base::OS::FOpen(), IsLoggingToConsole(), IsLoggingToTemporaryFile(), v8::base::OS::LogFileOpenMode, v8::base::OS::OpenTemporaryFile(), and v8::internal::v8_flags.
file_name()
std::string v8::internal::LogFile::file_name () const
Definition at line 107 of file log-file.cc.
{ return file_name_; }
References file_name_.
Referenced by CreateOutputHandle(), IsLoggingToConsole(), and IsLoggingToTemporaryFile().
IsLoggingToConsole()
bool v8::internal::LogFile::IsLoggingToConsole (std::string file_name) [static]
Definition at line 46 of file log-file.cc.
                                                    {
  return file_name.compare(LogFile::kLogToConsole) == 0;
}
References file_name(), and kLogToConsole.
Referenced by CreateOutputHandle().
IsLoggingToTemporaryFile()
bool v8::internal::LogFile::IsLoggingToTemporaryFile (std::string file_name) [static]
Definition at line 51 of file log-file.cc.
                                                          {
  return file_name.compare(LogFile::kLogToTemporaryFile) == 0;
}
References file_name(), and kLogToTemporaryFile.
Referenced by CreateOutputHandle(), and v8::Shell::LogGetAndStop().
mutex()
base::Mutex* v8::internal::LogFile::mutex () [inline], [private]
Definition at line 113 of file log-file.h.
{ return &mutex_; }
References mutex_.
NewMessageBuilder()
std::unique_ptr< LogFile::MessageBuilder > v8::internal::LogFile::NewMessageBuilder ()
Definition at line 79 of file log-file.cc.
                                                                {
  // Fast check of is_logging() without taking the lock. Bail out immediately if
  // logging isn't enabled.
  if (!logger_->is_logging()) return {};
  std::unique_ptr<LogFile::MessageBuilder> result(
      new LogFile::MessageBuilder(this));
  // The first invocation of is_logging() might still read an old value. It is
  // fine if a background thread starts logging a bit later, but we want to
  // avoid background threads continue logging after logging was already closed.
  if (!logger_->is_logging()) return {};
  DCHECK_NOT_NULL(format_buffer_.get());
  return result;
}
References DCHECK_NOT_NULL, format_buffer_, v8::internal::V8FileLogger::is_logging(), logger_, and v8::base::internal::result.
WriteLogHeader()
void v8::internal::LogFile::WriteLogHeader () [private]
Definition at line 64 of file log-file.cc.
                             {
  LogFile::MessageBuilder msg(this);
  LogSeparator kNext = LogSeparator::kSeparator;
  msg << "v8-version" << kNext << Version::GetMajor() << kNext
      << Version::GetMinor() << kNext << Version::GetBuild() << kNext
      << Version::GetPatch();
  if (strlen(Version::GetEmbedder()) != 0) {
    msg << kNext << Version::GetEmbedder();
  }
  msg << kNext << Version::IsCandidate();
  msg.WriteToLogFile();
  msg << "v8-platform" << kNext << V8_OS_STRING << kNext << V8_TARGET_OS_STRING;
  msg.WriteToLogFile();
}
References v8::internal::Version::GetBuild(), v8::internal::Version::GetEmbedder(), v8::internal::Version::GetMajor(), v8::internal::Version::GetMinor(), v8::internal::Version::GetPatch(), v8::internal::Version::IsCandidate(), v8::internal::kSeparator, V8_TARGET_OS_STRING, and v8::internal::LogFile::MessageBuilder::WriteToLogFile().
Referenced by LogFile().
Friends And Related Function Documentation
V8FileLogger
friend class V8FileLogger [friend]
Definition at line 135 of file log-file.h.
Member Data Documentation
file_name_
std::string v8::internal::LogFile::file_name_ [private]
Definition at line 119 of file log-file.h.
Referenced by file_name().
format_buffer_
std::unique_ptr<char[]> v8::internal::LogFile::format_buffer_ [private]
Definition at line 133 of file log-file.h.
Referenced by Close(), and NewMessageBuilder().
kLogToConsole
const char *const v8::internal::LogFile::kLogToConsole = `-` [static]
Definition at line 56 of file log-file.h.
Referenced by IsLoggingToConsole().
kLogToTemporaryFile
const char *const v8::internal::LogFile::kLogToTemporaryFile = `+` [static]
Definition at line 55 of file log-file.h.
Referenced by IsLoggingToTemporaryFile().
kMessageBufferSize
const int v8::internal::LogFile::kMessageBufferSize = 2048 [static]
Definition at line 51 of file log-file.h.
logger_
V8FileLogger* v8::internal::LogFile::logger_ [private]
Definition at line 117 of file log-file.h.
Referenced by NewMessageBuilder().
mutex_
base::Mutex v8::internal::LogFile::mutex_ [private]
Definition at line 129 of file log-file.h.
Referenced by mutex().
os_
OFStream v8::internal::LogFile::os_ [private]
Definition at line 125 of file log-file.h.
Referenced by v8::internal::LogFile::MessageBuilder::operator<<().
output_handle_
FILE* v8::internal::LogFile::output_handle_ [private]
Definition at line 123 of file log-file.h.
Referenced by Close(), and LogFile().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/logging/log-file.h
/mnt/V8SourceCode/src/logging/log-file.cc