v8::internal::RegExp Class Reference
#include <regexp.h>
Public Types
enum CallOrigin : int { kFromRuntime = 0
, kFromJs = 1
 }
enum IrregexpResult : int32_t {
RE_FAILURE = kInternalRegExpFailure
, RE_SUCCESS = kInternalRegExpSuccess
, RE_EXCEPTION = kInternalRegExpException
, RE_RETRY = kInternalRegExpRetry
,
RE_FALLBACK_TO_EXPERIMENTAL = kInternalRegExpFallbackToExperimental
 }
Static Public Member Functions
static bool CanGenerateBytecode ()
static V8_EXPORT_PRIVATE bool VerifyFlags (RegExpFlags flags)
template<class CharT >
static bool VerifySyntax (Zone *zone, uintptr_t stack_limit, const CharT *input, int input_length, RegExpFlags flags, RegExpError *regexp_error_out, const DisallowGarbageCollection &no_gc)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Compile (Isolate *isolate, DirectHandle< JSRegExp > re, DirectHandle< String > pattern, RegExpFlags flags, uint32_t backtrack_limit)
static V8_WARN_UNUSED_RESULT bool EnsureFullyCompiled (Isolate *isolate, DirectHandle< RegExpData > re_data, DirectHandle< String > subject)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT std::optional< int > Exec (Isolate *isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > subject, int index, int32_t *result_offsets_vector, uint32_t result_offsets_vector_length)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Exec_Single (Isolate *isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > subject, int index, DirectHandle< RegExpMatchInfo > last_match_info)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT std::optional< int > ExperimentalOneshotExec (Isolate *isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > subject, int index, int32_t *result_offsets_vector, uint32_t result_offsets_vector_length)
static V8_EXPORT_PRIVATE intptr_t AtomExecRaw (Isolate *isolate, Address data_address, Address subject_address, int32_t index, int32_t *result_offsets_vector, int32_t result_offsets_vector_length)
static DirectHandle< RegExpMatchInfo > SetLastMatchInfo (Isolate *isolate, DirectHandle< RegExpMatchInfo > last_match_info, DirectHandle< String > subject, int capture_count, int32_t *match)
static V8_EXPORT_PRIVATE bool CompileForTesting (Isolate *isolate, Zone *zone, RegExpCompileData *input, RegExpFlags flags, DirectHandle< String > pattern, DirectHandle< String > sample_subject, bool is_one_byte)
static V8_EXPORT_PRIVATE void DotPrintForTesting (const char *label, RegExpNode *node)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > ThrowRegExpException (Isolate *isolate, RegExpFlags flags, DirectHandle< String > pattern, RegExpError error)
static void ThrowRegExpException (Isolate *isolate, DirectHandle< RegExpData > re_data, RegExpError error_text)
static bool IsUnmodifiedRegExp (Isolate *isolate, DirectHandle< JSRegExp > regexp)
static DirectHandle< FixedArray > CreateCaptureNameMap (Isolate *isolate, ZoneVector< RegExpCapture * > *named_captures)
Static Public Attributes
static constexpr int kInternalRegExpFailure = 0
static constexpr int kInternalRegExpSuccess = 1
static constexpr int kInternalRegExpException = -1
static constexpr int kInternalRegExpRetry = -2
static constexpr int kInternalRegExpFallbackToExperimental = -3
static constexpr int kInternalRegExpSmallestResult = -3
static const int kRegExpTooLargeToOptimize = 20 * KB
Detailed Description
Definition at line 72 of file regexp.h.
Member Enumeration Documentation
CallOrigin
enum v8::internal::RegExp::CallOrigin : int
Enumerator
kFromRuntime
kFromJs
Definition at line 103 of file regexp.h.
                  : int {
    kFromRuntime = 0,
    kFromJs = 1,
  };
IrregexpResult
enum v8::internal::RegExp::IrregexpResult : int32_t
Enumerator
RE_FAILURE
RE_SUCCESS
RE_EXCEPTION
RE_RETRY
RE_FALLBACK_TO_EXPERIMENTAL
Definition at line 141 of file regexp.h.
                      : int32_t {
    RE_FAILURE = kInternalRegExpFailure,
    RE_SUCCESS = kInternalRegExpSuccess,
    RE_EXCEPTION = kInternalRegExpException,
    RE_RETRY = kInternalRegExpRetry,
    RE_FALLBACK_TO_EXPERIMENTAL = kInternalRegExpFallbackToExperimental,
  };
Member Function Documentation
AtomExecRaw()
intptr_t v8::internal::RegExp::AtomExecRaw (Isolate * isolate, Address data_address, Address subject_address, int32_t index, int32_t * result_offsets_vector, int32_t result_offsets_vector_length) [static]
Definition at line 492 of file regexp.cc.
                                                                   {
  DisallowGarbageCollection no_gc;
  SBXCHECK(Is<AtomRegExpData>(Tagged<Object>(data_address)));
  auto data = Cast<AtomRegExpData>(Tagged<Object>(data_address));
  auto subject = Cast<String>(Tagged<Object>(subject_address));
  Tagged<String> pattern = data->pattern(isolate);
  RegExpFlags flags = JSRegExp::AsRegExpFlags(data->flags());
  String::FlatContent pattern_content = pattern->GetFlatContent(no_gc);
  String::FlatContent subject_content = subject->GetFlatContent(no_gc);
  return RegExpImpl::AtomExecRaw(isolate, pattern_content, subject_content,
                                 index, flags, result_offsets_vector,
                                 result_offsets_vector_length, no_gc);
}
References v8::internal::JSRegExp::AsRegExpFlags(), v8::internal::RegExpImpl::AtomExecRaw(), v8::internal::flags, v8::internal::index, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and SBXCHECK.
CanGenerateBytecode()
bool v8::internal::RegExp::CanGenerateBytecode () [static]
Definition at line 112 of file regexp.cc.
                                 {
  return v8_flags.regexp_interpret_all || v8_flags.regexp_tier_up;
}
References v8::internal::v8_flags.
Compile()
MaybeDirectHandle< Object > v8::internal::RegExp::Compile (Isolate * isolate, DirectHandle< JSRegExp > re, DirectHandle< String > pattern, RegExpFlags flags, uint32_t backtrack_limit) [static]
Definition at line 200 of file regexp.cc.
                                                                    {
  DCHECK(pattern->IsFlat());
  // Caching is based only on the pattern and flags, but code also differs when
  // a backtrack limit is set. A present backtrack limit is very much *not* the
  // common case, so just skip the cache for these.
  const bool is_compilation_cache_enabled =
      (backtrack_limit == JSRegExp::kNoBacktrackLimit);
  Zone zone(isolate->allocator(), ZONE_NAME);
  CompilationCache* compilation_cache = nullptr;
  if (is_compilation_cache_enabled) {
    compilation_cache = isolate->compilation_cache();
    MaybeDirectHandle<RegExpData> maybe_cached =
        compilation_cache->LookupRegExp(pattern,
                                        JSRegExp::AsJSRegExpFlags(flags));
    DirectHandle<RegExpData> cached;
    if (maybe_cached.ToHandle(&cached)) {
      re->set_data(*cached);
      return re;
    }
  }
  PostponeInterruptsScope postpone(isolate);
  RegExpCompileData parse_result;
  DCHECK(!isolate->has_exception());
  if (!RegExpParser::ParseRegExpFromHeapString(isolate, &zone, pattern, flags,
                                               &parse_result)) {
    // Throw an exception if we fail to parse the pattern.
    return RegExp::ThrowRegExpException(isolate, flags, pattern,
                                        parse_result.error);
  }
  bool has_been_compiled = false;
  if (v8_flags.default_to_experimental_regexp_engine &&
      ExperimentalRegExp::CanBeHandled(parse_result.tree, pattern, flags,
                                       parse_result.capture_count)) {
    DCHECK(v8_flags.enable_experimental_regexp_engine);
    ExperimentalRegExp::Initialize(isolate, re, pattern, flags,
                                   parse_result.capture_count);
    has_been_compiled = true;
  } else if (flags & JSRegExp::kLinear) {
    DCHECK(v8_flags.enable_experimental_regexp_engine);
    if (!ExperimentalRegExp::CanBeHandled(parse_result.tree, pattern, flags,
                                          parse_result.capture_count)) {
      // TODO(mbid): The error could provide a reason for why the regexp can't
      // be executed in linear time (e.g. due to back references).
      return RegExp::ThrowRegExpException(isolate, flags, pattern,
                                          RegExpError::kNotLinear);
    }
    ExperimentalRegExp::Initialize(isolate, re, pattern, flags,
                                   parse_result.capture_count);
    has_been_compiled = true;
  } else if (parse_result.simple && !IsIgnoreCase(flags) && !IsSticky(flags) &&
             !HasFewDifferentCharacters(pattern)) {
    // Parse-tree is a single atom that is equal to the pattern.
    RegExpImpl::AtomCompile(isolate, re, pattern, flags, pattern);
    has_been_compiled = true;
  } else if (parse_result.tree->IsAtom() && !IsSticky(flags) &&
             parse_result.capture_count == 0) {
    RegExpAtom* atom = parse_result.tree->AsAtom();
    // The pattern source might (?) contain escape sequences, but they're
    // resolved in atom_string.
    base::Vector<const base::uc16> atom_pattern = atom->data();
    DirectHandle<String> atom_string;
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, atom_string,
        isolate->factory()->NewStringFromTwoByte(atom_pattern));
    if (!IsIgnoreCase(flags) && !HasFewDifferentCharacters(atom_string)) {
      RegExpImpl::AtomCompile(isolate, re, pattern, flags, atom_string);
      has_been_compiled = true;
    }
  }
  if (!has_been_compiled) {
    RegExpImpl::IrregexpInitialize(isolate, re, pattern, flags,
                                   parse_result.capture_count, backtrack_limit);
  }
  // Compilation succeeded so the data is set on the regexp
  // and we can store it in the cache.
  DirectHandle<RegExpData> data(re->data(isolate), isolate);
  if (is_compilation_cache_enabled) {
    compilation_cache->PutRegExp(pattern, JSRegExp::AsJSRegExpFlags(flags),
                                 data);
  }
  return re;
}
References v8::internal::Isolate::allocator(), v8::internal::JSRegExp::AsJSRegExpFlags(), ASSIGN_RETURN_ON_EXCEPTION, v8::internal::RegExpImpl::AtomCompile(), v8::internal::ExperimentalRegExp::CanBeHandled(), v8::internal::RegExpCompileData::capture_count, v8::internal::Isolate::compilation_cache(), v8::internal::RegExpAtom::data(), v8::internal::DCHECK(), v8::internal::RegExpCompileData::error, v8::internal::Isolate::factory(), v8::internal::flags, v8::internal::Isolate::has_exception(), v8::internal::anonymous_namespace{regexp.cc}::HasFewDifferentCharacters(), v8::internal::ExperimentalRegExp::Initialize(), v8::internal::RegExpImpl::IrregexpInitialize(), v8::internal::JSRegExp::kNoBacktrackLimit, v8::internal::CompilationCache::LookupRegExp(), v8::internal::Factory::NewStringFromTwoByte(), v8::internal::RegExpParser::ParseRegExpFromHeapString(), v8::internal::CompilationCache::PutRegExp(), v8::internal::RegExpCompileData::simple, ThrowRegExpException(), v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::internal::RegExpCompileData::tree, v8::internal::v8_flags, and ZONE_NAME.
Referenced by v8::internal::JSRegExp::Initialize().
CompileForTesting()
bool v8::internal::RegExp::CompileForTesting (Isolate * isolate, Zone * zone, RegExpCompileData * input, RegExpFlags flags, DirectHandle< String > pattern, DirectHandle< String > sample_subject, bool is_one_byte) [static]
Definition at line 952 of file regexp.cc.
                                                 {
  uint32_t backtrack_limit = JSRegExp::kNoBacktrackLimit;
  return RegExpImpl::Compile(isolate, zone, data, flags, pattern,
                             sample_subject, is_one_byte, backtrack_limit);
}
References v8::internal::RegExpImpl::Compile(), v8::internal::flags, and v8::internal::JSRegExp::kNoBacktrackLimit.
CreateCaptureNameMap()
DirectHandle< FixedArray > v8::internal::RegExp::CreateCaptureNameMap (Isolate * isolate, ZoneVector< RegExpCapture * > * named_captures) [static]
Definition at line 588 of file regexp.cc.
                                                                  {
  if (named_captures == nullptr) return DirectHandle<FixedArray>();
  DCHECK(!named_captures->empty());
  // Named captures are sorted by name (because the set is used to ensure
  // name uniqueness). But the capture name map must to be sorted by index.
  std::sort(named_captures->begin(), named_captures->end(),
            RegExpCaptureIndexLess{});
  int len = static_cast<int>(named_captures->size()) * 2;
  DirectHandle<FixedArray> array = isolate->factory()->NewFixedArray(len);
  int i = 0;
  for (const RegExpCapture* capture : *named_captures) {
    base::Vector<const base::uc16> capture_name(capture->name()->data(),
                                                capture->name()->size());
    // CSA code in ConstructNewResultFromMatchInfo requires these strings to be
    // internalized so they can be used as property names in the 'exec' results.
    DirectHandle<String> name =
        isolate->factory()->InternalizeString(capture_name);
    array->set(i * 2, *name);
    array->set(i * 2 + 1, Smi::FromInt(capture->index()));
    i++;
  }
  DCHECK_EQ(i * 2, len);
  return array;
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ZoneVector< T >::empty(), v8::internal::ZoneVector< T >::end(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::Factory::InternalizeString(), v8::internal::name, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::ZoneVector< T >::size(), and v8::base::sort().
Referenced by v8::internal::anonymous_namespace{experimental.cc}::CompileImpl(), and v8::internal::RegExpImpl::CompileIrregexp().
DotPrintForTesting()
void v8::internal::RegExp::DotPrintForTesting (const char * label, RegExpNode * node) [static]
Definition at line 926 of file regexp.cc.
                                                                   {
  DotPrinter::DotPrint(label, node);
}
References v8::internal::DotPrinter::DotPrint().
EnsureFullyCompiled()
bool v8::internal::RegExp::EnsureFullyCompiled (Isolate * isolate, DirectHandle< RegExpData > re_data, DirectHandle< String > subject) [static]
Definition at line 294 of file regexp.cc.
                                                               {
  switch (re_data->type_tag()) {
    case RegExpData::Type::ATOM:
      return true;
    case RegExpData::Type::IRREGEXP:
      if (RegExpImpl::IrregexpPrepare(isolate, Cast<IrRegExpData>(re_data),
                                      subject) == -1) {
        DCHECK(isolate->has_exception());
        return false;
      }
      return true;
    case RegExpData::Type::EXPERIMENTAL:
      if (!ExperimentalRegExp::IsCompiled(Cast<IrRegExpData>(re_data),
                                          isolate) &&
          !ExperimentalRegExp::Compile(isolate, Cast<IrRegExpData>(re_data))) {
        DCHECK(isolate->has_exception());
        return false;
      }
      return true;
  }
  UNREACHABLE();
}
References v8::internal::RegExpData::ATOM, v8::internal::ExperimentalRegExp::Compile(), v8::internal::DCHECK(), v8::internal::RegExpData::EXPERIMENTAL, v8::internal::Isolate::has_exception(), v8::internal::RegExpData::IRREGEXP, v8::internal::RegExpImpl::IrregexpPrepare(), v8::internal::ExperimentalRegExp::IsCompiled(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::StringReplaceGlobalRegExpWithString().
Exec()
std::optional< int > v8::internal::RegExp::Exec (Isolate * isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > subject, int index, int32_t * result_offsets_vector, uint32_t result_offsets_vector_length) [static]
Definition at line 332 of file regexp.cc.
                                                                       {
  DirectHandle<RegExpData> data(regexp->data(isolate), isolate);
  switch (data->type_tag()) {
    case RegExpData::Type::ATOM:
      return RegExpImpl::AtomExec(isolate, Cast<AtomRegExpData>(data), subject,
                                  index, result_offsets_vector,
                                  result_offsets_vector_length);
    case RegExpData::Type::IRREGEXP:
      return RegExpImpl::IrregexpExec(isolate, Cast<IrRegExpData>(data),
                                      subject, index, result_offsets_vector,
                                      result_offsets_vector_length);
    case RegExpData::Type::EXPERIMENTAL:
      return ExperimentalRegExp::Exec(isolate, Cast<IrRegExpData>(data),
                                      subject, index, result_offsets_vector,
                                      result_offsets_vector_length);
  }
  // This UNREACHABLE() is necessary because we don't return a value here,
  // which causes the compiler to emit potentially unsafe code for the switch
  // above. See the commit message and b/326086002 for more details.
  UNREACHABLE();
}
References v8::internal::RegExpData::ATOM, v8::internal::RegExpImpl::AtomExec(), v8::internal::ExperimentalRegExp::Exec(), v8::internal::RegExpData::EXPERIMENTAL, v8::internal::index, v8::internal::RegExpData::IRREGEXP, v8::internal::RegExpImpl::IrregexpExec(), and v8::internal::UNREACHABLE().
Referenced by Exec_Single(), and v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpExec().
Exec_Single()
MaybeDirectHandle< Object > v8::internal::RegExp::Exec_Single (Isolate * isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > subject, int index, DirectHandle< RegExpMatchInfo > last_match_info) [static]
Definition at line 358 of file regexp.cc.
                                                   {
  RegExpStackScope stack_scope(isolate);
  DirectHandle<RegExpData> data(regexp->data(isolate), isolate);
  int capture_count = data->capture_count();
  int result_offsets_vector_length =
      JSRegExp::RegistersForCaptureCount(capture_count);
  RegExpResultVectorScope result_vector_scope(isolate,
                                              result_offsets_vector_length);
  std::optional<int> result =
      RegExp::Exec(isolate, regexp, subject, index, result_vector_scope.value(),
                   result_offsets_vector_length);
  DCHECK_EQ(!result, isolate->has_exception());
  if (!result) return {};
  if (result.value() == 0) {
    return isolate->factory()->null_value();
  }
  DCHECK_EQ(result.value(), 1);
  return RegExp::SetLastMatchInfo(isolate, last_match_info, subject,
                                  capture_count, result_vector_scope.value());
}
References DCHECK_EQ, Exec(), v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), v8::internal::index, v8::internal::JSRegExp::RegistersForCaptureCount(), v8::base::internal::result, SetLastMatchInfo(), and v8::internal::RegExpResultVectorScope::value().
Referenced by v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpReplace(), and v8::internal::RUNTIME_FUNCTION().
ExperimentalOneshotExec()
std::optional< int > v8::internal::RegExp::ExperimentalOneshotExec (Isolate * isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > subject, int index, int32_t * result_offsets_vector, uint32_t result_offsets_vector_length) [static]
Definition at line 320 of file regexp.cc.
                                           {
  DirectHandle<RegExpData> data(regexp->data(isolate), isolate);
  SBXCHECK(Is<IrRegExpData>(*data));
  return ExperimentalRegExp::OneshotExec(isolate, Cast<IrRegExpData>(data),
                                         subject, index, result_offsets_vector,
                                         result_offsets_vector_length);
}
References v8::internal::index, v8::internal::ExperimentalRegExp::OneshotExec(), and SBXCHECK.
Referenced by v8::internal::anonymous_namespace{runtime-regexp.cc}::ExperimentalOneshotExec().
IsUnmodifiedRegExp()
bool v8::internal::RegExp::IsUnmodifiedRegExp (Isolate * isolate, DirectHandle< JSRegExp > regexp) [static]
Definition at line 166 of file regexp.cc.
                                                               {
  return RegExpUtils::IsUnmodifiedRegExp(isolate, regexp);
}
References v8::internal::RegExpUtils::IsUnmodifiedRegExp().
Referenced by v8::internal::RUNTIME_FUNCTION().
SetLastMatchInfo()
DirectHandle< RegExpMatchInfo > v8::internal::RegExp::SetLastMatchInfo (Isolate * isolate, DirectHandle< RegExpMatchInfo > last_match_info, DirectHandle< String > subject, int capture_count, int32_t * match) [static]
Definition at line 896 of file regexp.cc.
                                                                     {
  DirectHandle<RegExpMatchInfo> result =
      RegExpMatchInfo::ReserveCaptures(isolate, last_match_info, capture_count);
  if (*result != *last_match_info) {
    if (*last_match_info == *isolate->regexp_last_match_info()) {
      // This inner condition is only needed for special situations like the
      // regexp fuzzer, where we pass our own custom RegExpMatchInfo to
      // RegExpImpl::Exec; there actually want to bypass the Isolate's match
      // info and execute the regexp without side effects.
      isolate->native_context()->set_regexp_last_match_info(*result);
    }
  }
  int capture_register_count =
      JSRegExp::RegistersForCaptureCount(capture_count);
  DisallowGarbageCollection no_gc;
  if (match != nullptr) {
    for (int i = 0; i < capture_register_count; i += 2) {
      result->set_capture(i, match[i]);
      result->set_capture(i + 1, match[i + 1]);
    }
  }
  result->set_last_subject(*subject);
  result->set_last_input(*subject);
  return result;
}
References v8::internal::Isolate::native_context(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::JSRegExp::RegistersForCaptureCount(), v8::internal::RegExpMatchInfo::ReserveCaptures(), and v8::base::internal::result.
Referenced by Exec_Single(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple(), v8::internal::StringReplaceGlobalAtomRegExpWithString(), v8::internal::StringReplaceGlobalRegExpWithEmptyString(), and v8::internal::StringReplaceGlobalRegExpWithString().
ThrowRegExpException() [1/2]
void v8::internal::RegExp::ThrowRegExpException (Isolate * isolate, DirectHandle< RegExpData > re_data, RegExpError error_text) [static]
Definition at line 158 of file regexp.cc.
                                                          {
  USE(ThrowRegExpException(isolate, JSRegExp::AsRegExpFlags(re_data->flags()),
                           direct_handle(re_data->source(), isolate),
                           error_text));
}
References v8::internal::JSRegExp::AsRegExpFlags(), v8::internal::direct_handle(), and USE.
ThrowRegExpException() [2/2]
MaybeDirectHandle< Object > v8::internal::RegExp::ThrowRegExpException (Isolate * isolate, RegExpFlags flags, DirectHandle< String > pattern, RegExpError error) [static]
Definition at line 143 of file regexp.cc.
                       {
  base::Vector<const char> error_data =
      base::CStrVector(RegExpErrorString(error));
  DirectHandle<String> error_text =
      isolate->factory()
          ->NewStringFromOneByte(base::Vector<const uint8_t>::cast(error_data))
          .ToHandleChecked();
  DirectHandle<String> flag_string =
      JSRegExp::StringFromFlags(isolate, JSRegExp::AsJSRegExpFlags(flags));
  THROW_NEW_ERROR(isolate, NewSyntaxError(MessageTemplate::kMalformedRegExp,
                                          pattern, flag_string, error_text));
}
References v8::internal::JSRegExp::AsJSRegExpFlags(), v8::base::CStrVector(), v8::internal::Isolate::factory(), v8::internal::flags, v8::internal::FactoryBase< Impl >::NewStringFromOneByte(), v8::internal::RegExpErrorString(), v8::internal::JSRegExp::StringFromFlags(), and THROW_NEW_ERROR.
Referenced by Compile(), v8::internal::anonymous_namespace{experimental.cc}::CompileImpl(), and v8::internal::RegExpImpl::CompileIrregexp().
VerifyFlags()
bool v8::internal::RegExp::VerifyFlags (RegExpFlags flags) [static]
Definition at line 117 of file regexp.cc.
                                          {
  if (IsUnicode(flags) && IsUnicodeSets(flags)) return false;
  return true;
}
References v8::internal::flags.
Referenced by v8::internal::JSRegExp::Initialize(), v8::internal::ValueDeserializer::ReadJSRegExp(), and v8::internal::ParserBase< Impl >::ValidateRegExpFlags().
VerifySyntax()
template<class CharT >
template bool v8::internal::RegExp::VerifySyntax< uint8_t > (Zone * zone, uintptr_t stack_limit, const CharT * input, int input_length, RegExpFlags flags, RegExpError * regexp_error_out, const DisallowGarbageCollection & no_gc) [static]
Definition at line 124 of file regexp.cc.
                                                                  {
  RegExpCompileData data;
  bool pattern_is_valid = RegExpParser::VerifyRegExpSyntax(
      zone, stack_limit, input, input_length, flags, &data, no_gc);
  *regexp_error_out = data.error;
  return pattern_is_valid;
}
References v8::internal::RegExpCompileData::error, v8::internal::flags, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::RegExpParser::VerifyRegExpSyntax().
Referenced by v8::internal::ParserBase< Impl >::ValidateRegExpLiteral().
Member Data Documentation
kInternalRegExpException
constexpr int v8::internal::RegExp::kInternalRegExpException = -1 [static], [constexpr]
Definition at line 136 of file regexp.h.
Referenced by v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::CheckMemoryConsumption(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::HandleInterrupts(), v8::internal::ExperimentalRegExp::OneshotExecRaw(), and v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal().
kInternalRegExpFailure
constexpr int v8::internal::RegExp::kInternalRegExpFailure = 0 [static], [constexpr]
Definition at line 134 of file regexp.h.
Referenced by v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal().
kInternalRegExpFallbackToExperimental
constexpr int v8::internal::RegExp::kInternalRegExpFallbackToExperimental = -3 [static], [constexpr]
Definition at line 138 of file regexp.h.
Referenced by v8::internal::RegExpGlobalExecRunner::FetchNext(), and v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal().
kInternalRegExpRetry
constexpr int v8::internal::RegExp::kInternalRegExpRetry = -2 [static], [constexpr]
Definition at line 137 of file regexp.h.
Referenced by v8::internal::ExperimentalRegExp::Exec(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::HandleInterrupts(), v8::internal::ExperimentalRegExp::OneshotExec(), and v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal().
kInternalRegExpSmallestResult
constexpr int v8::internal::RegExp::kInternalRegExpSmallestResult = -3 [static], [constexpr]
Definition at line 139 of file regexp.h.
kInternalRegExpSuccess
constexpr int v8::internal::RegExp::kInternalRegExpSuccess = 1 [static], [constexpr]
Definition at line 135 of file regexp.h.
Referenced by v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::CheckMemoryConsumption(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FillLookaroundCaptures(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FillLookaroundTable(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FindMatches(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FindNextMatch(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::GetFilteredRegisters(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::HandleInterrupts(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThreads(), and v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThreadsToEnd().
kRegExpTooLargeToOptimize
const int v8::internal::RegExp::kRegExpTooLargeToOptimize = 20 * KB [static]
Definition at line 163 of file regexp.h.
Referenced by v8::internal::anonymous_namespace{regexp.cc}::TooMuchRegExpCode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp.h
/mnt/V8SourceCode/src/regexp/regexp.cc