v8::internal::SharedFunctionInfo::ScriptIterator Class Reference
#include <shared-function-info.h>
Public Member Functions
V8_EXPORT_PRIVATE ScriptIterator (Isolate *isolate, Tagged< Script > script)
ScriptIterator (Handle< WeakFixedArray > infos)
ScriptIterator (const ScriptIterator &)=delete
ScriptIterator & operator= (const ScriptIterator &)=delete
V8_EXPORT_PRIVATE Tagged< SharedFunctionInfo > Next ()
int CurrentIndex () const
void Reset (Isolate *isolate, Tagged< Script > script)
Private Attributes
Handle< WeakFixedArray > infos_
int index_
Detailed Description
Definition at line 756 of file shared-function-info.h.
Constructor & Destructor Documentation
ScriptIterator() [1/3]
v8::internal::SharedFunctionInfo::ScriptIterator::ScriptIterator (Isolate * isolate, Tagged< Script > script)
Definition at line 154 of file shared-function-info.cc.
    : ScriptIterator(handle(script->infos(), isolate)) {}
ScriptIterator() [2/3]
v8::internal::SharedFunctionInfo::ScriptIterator::ScriptIterator (Handle< WeakFixedArray > infos) [explicit]
Definition at line 158 of file shared-function-info.cc.
    : infos_(infos), index_(0) {}
ScriptIterator() [3/3]
v8::internal::SharedFunctionInfo::ScriptIterator::ScriptIterator (const ScriptIterator &) [delete]
Member Function Documentation
CurrentIndex()
int v8::internal::SharedFunctionInfo::ScriptIterator::CurrentIndex () const [inline]
Definition at line 763 of file shared-function-info.h.
{ return index_ - 1; }
References index_.
Referenced by v8::internal::LiveEdit::PatchScript().
Next()
Tagged< SharedFunctionInfo > v8::internal::SharedFunctionInfo::ScriptIterator::Next ()
Definition at line 161 of file shared-function-info.cc.
                                                                  {
  while (index_ < infos_->length()) {
    Tagged<MaybeObject> raw = infos_->get(index_++);
    Tagged<HeapObject> heap_object;
    if (!raw.GetHeapObject(&heap_object) ||
        !IsSharedFunctionInfo(heap_object)) {
      continue;
    }
    return Cast<SharedFunctionInfo>(heap_object);
  }
  return SharedFunctionInfo();
}
References v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), and v8::internal::length.
Referenced by v8::internal::Coverage::Collect(), v8::internal::anonymous_namespace{code-serializer.cc}::CreateInterpreterDataForDeserializedCode(), v8::internal::EnumerateCompiledFunctions(), v8::internal::anonymous_namespace{code-serializer.cc}::FinalizeDeserialization(), v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::FindScopeInfoForScope(), v8::internal::anonymous_namespace{debug.cc}::FindSharedFunctionInfoCandidate(), v8::internal::Debug::FindSharedFunctionInfosIntersectingRange(), v8::internal::Compiler::GetWrappedFunction(), and v8::internal::LiveEdit::PatchScript().
operator=()
ScriptIterator& v8::internal::SharedFunctionInfo::ScriptIterator::operator= (const ScriptIterator &) [delete]
Reset()
void v8::internal::SharedFunctionInfo::ScriptIterator::Reset (Isolate * isolate, Tagged< Script > script)
Definition at line 174 of file shared-function-info.cc.
                                                                      {
  infos_ = handle(script->infos(), isolate);
  index_ = 0;
}
References v8::internal::handle(), and v8::internal::SharedFunctionInfo::script().
Member Data Documentation
index_
int v8::internal::SharedFunctionInfo::ScriptIterator::index_ [private]
Definition at line 770 of file shared-function-info.h.
Referenced by CurrentIndex().
infos_
Handle<WeakFixedArray> v8::internal::SharedFunctionInfo::ScriptIterator::infos_ [private]
Definition at line 769 of file shared-function-info.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/shared-function-info.h
/mnt/V8SourceCode/src/objects/shared-function-info.cc