v8::internal::compiler::NumberOperationParameters Class Reference
#include <simplified-operator.h>
Public Member Functions
NumberOperationParameters (NumberOperationHint hint, const FeedbackSource &feedback)
NumberOperationHint hint () const
const FeedbackSource & feedback () const
Private Attributes
NumberOperationHint hint_
FeedbackSource feedback_
Detailed Description
Definition at line 613 of file simplified-operator.h.
Constructor & Destructor Documentation
NumberOperationParameters()
v8::internal::compiler::NumberOperationParameters::NumberOperationParameters (NumberOperationHint hint, const FeedbackSource & feedback) [inline]
Definition at line 615 of file simplified-operator.h.
      : hint_(hint), feedback_(feedback) {}
Member Function Documentation
feedback()
const FeedbackSource& v8::internal::compiler::NumberOperationParameters::feedback () const [inline]
Definition at line 620 of file simplified-operator.h.
{ return feedback_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::RepresentationSelector::VisitNode().
hint()
NumberOperationHint v8::internal::compiler::NumberOperationParameters::hint () const [inline]
Definition at line 619 of file simplified-operator.h.
{ return hint_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Member Data Documentation
feedback_
FeedbackSource v8::internal::compiler::NumberOperationParameters::feedback_ [private]
Definition at line 624 of file simplified-operator.h.
hint_
NumberOperationHint v8::internal::compiler::NumberOperationParameters::hint_ [private]
Definition at line 623 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h