v8::internal::Heap::ExternalMemoryAccounting Class Reference
#include <heap.h>
Public Member Functions
uint64_t total () const
uint64_t limit_for_interrupt () const
uint64_t soft_limit () const
uint64_t low_since_mark_compact () const
uint64_t UpdateAmount (int64_t delta)
void UpdateLimitForInterrupt (uint64_t amount)
void UpdateLowSinceMarkCompact (uint64_t amount)
uint64_t AllocatedSinceMarkCompact () const
Static Public Attributes
static constexpr size_t kExternalAllocationLimitForInterrupt = 128 * KB
Private Member Functions
void set_total (uint64_t value)
void set_limit_for_interrupt (uint64_t value)
void set_low_since_mark_compact (uint64_t value)
Private Attributes
std::atomic< uint64_t > total_ {0}
std::atomic< uint64_t > limit_for_interrupt_
std::atomic< uint64_t > low_since_mark_compact_ {0}
Detailed Description
Definition at line 236 of file heap.h.
Member Function Documentation
AllocatedSinceMarkCompact()
uint64_t v8::internal::Heap::ExternalMemoryAccounting::AllocatedSinceMarkCompact () const [inline]
Definition at line 267 of file heap.h.
                                               {
      uint64_t total_bytes = total();
      uint64_t low_since_mark_compact_bytes = low_since_mark_compact();
      if (total_bytes <= low_since_mark_compact_bytes) {
        return 0;
      }
      return total_bytes - low_since_mark_compact_bytes;
    }
Referenced by v8::internal::Heap::AllocatedExternalMemorySinceMarkCompact().
limit_for_interrupt()
uint64_t v8::internal::Heap::ExternalMemoryAccounting::limit_for_interrupt () const [inline]
Definition at line 241 of file heap.h.
                                         {
      return limit_for_interrupt_.load(std::memory_order_relaxed);
    }
Referenced by v8::internal::Heap::external_memory_limit_for_interrupt().
low_since_mark_compact()
uint64_t v8::internal::Heap::ExternalMemoryAccounting::low_since_mark_compact () const [inline]
Definition at line 247 of file heap.h.
                                            {
      return low_since_mark_compact_.load(std::memory_order_relaxed);
    }
Referenced by v8::internal::Heap::GlobalConsumedBytesAtLastGC(), and v8::internal::Heap::UpdateExternalMemory().
set_limit_for_interrupt()
void v8::internal::Heap::ExternalMemoryAccounting::set_limit_for_interrupt (uint64_t value) [inline], [private]
Definition at line 282 of file heap.h.
                                                 {
      limit_for_interrupt_.store(value, std::memory_order_relaxed);
    }
References v8::internal::value.
set_low_since_mark_compact()
void v8::internal::Heap::ExternalMemoryAccounting::set_low_since_mark_compact (uint64_t value) [inline], [private]
Definition at line 286 of file heap.h.
                                                    {
      low_since_mark_compact_.store(value, std::memory_order_relaxed);
    }
References v8::internal::value.
set_total()
void v8::internal::Heap::ExternalMemoryAccounting::set_total (uint64_t value) [inline], [private]
Definition at line 278 of file heap.h.
                                   {
      total_.store(value, std::memory_order_relaxed);
    }
References v8::internal::value.
soft_limit()
uint64_t v8::internal::Heap::ExternalMemoryAccounting::soft_limit () const [inline]
Definition at line 244 of file heap.h.
                                {
      return low_since_mark_compact() + kExternalAllocationSoftLimit;
    }
References v8::internal::kExternalAllocationSoftLimit.
Referenced by v8::internal::Heap::external_memory_soft_limit(), and v8::internal::Heap::HandleExternalMemoryInterrupt().
total()
uint64_t v8::internal::Heap::ExternalMemoryAccounting::total () const [inline]
Definition at line 240 of file heap.h.
{ return total_.load(std::memory_order_relaxed); }
Referenced by v8::internal::Heap::external_memory(), v8::internal::Heap::MarkCompact(), and v8::internal::Heap::RecomputeLimitsAfterLoadingIfNeeded().
UpdateAmount()
uint64_t v8::internal::Heap::ExternalMemoryAccounting::UpdateAmount (int64_t delta) [inline]
Definition at line 251 of file heap.h.
                                         {
      const uint64_t amount_before =
          total_.fetch_add(delta, std::memory_order_relaxed);
      CHECK_GE(static_cast<int64_t>(amount_before), -delta);
      return amount_before + delta;
    }
References CHECK_GE.
Referenced by v8::internal::Heap::UpdateExternalMemory().
UpdateLimitForInterrupt()
void v8::internal::Heap::ExternalMemoryAccounting::UpdateLimitForInterrupt (uint64_t amount) [inline]
Definition at line 258 of file heap.h.
                                                  {
      set_limit_for_interrupt(amount + kExternalAllocationLimitForInterrupt);
    }
Referenced by v8::internal::Heap::HandleExternalMemoryInterrupt().
UpdateLowSinceMarkCompact()
void v8::internal::Heap::ExternalMemoryAccounting::UpdateLowSinceMarkCompact (uint64_t amount) [inline]
Definition at line 262 of file heap.h.
                                                    {
      set_low_since_mark_compact(amount);
      UpdateLimitForInterrupt(amount);
    }
Referenced by v8::internal::Heap::MarkCompact(), v8::internal::Heap::RecomputeLimitsAfterLoadingIfNeeded(), and v8::internal::Heap::UpdateExternalMemory().
Member Data Documentation
kExternalAllocationLimitForInterrupt
constexpr size_t v8::internal::Heap::ExternalMemoryAccounting::kExternalAllocationLimitForInterrupt = 128 * KB [static], [constexpr]
Definition at line 238 of file heap.h.
limit_for_interrupt_
std::atomic<uint64_t> v8::internal::Heap::ExternalMemoryAccounting::limit_for_interrupt_ [private]
Initial value:
{
        kExternalAllocationLimitForInterrupt}
Definition at line 294 of file heap.h.
low_since_mark_compact_
std::atomic<uint64_t> v8::internal::Heap::ExternalMemoryAccounting::low_since_mark_compact_ {0} [private]
Definition at line 298 of file heap.h.
total_
std::atomic<uint64_t> v8::internal::Heap::ExternalMemoryAccounting::total_ {0} [private]
Definition at line 291 of file heap.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/heap.h