v8::internal::DateCache Class Reference
#include <date.h>
Classes
struct CacheItem
Public Member Functions
DateCache ()
virtual ~DateCache ()
void ResetDateCache (base::TimezoneCache::TimeZoneDetection time_zone_detection)
int Weekday (int days)
bool IsLeap (int year)
int LocalOffsetInMs (int64_t time, bool is_utc)
const char * LocalTimezone (int64_t time_ms)
int TimezoneOffset (int64_t time_ms)
int64_t ToLocal (int64_t time_ms)
int64_t ToUTC (int64_t time_ms)
int64_t EquivalentTime (int64_t time_ms)
int EquivalentYear (int year)
void YearMonthDayFromDays (int days, int *year, int *month, int *day)
int DaysFromYearMonth (int year, int month)
void BreakDownTime (int64_t time_ms, int *year, int *month, int *day, int *weekday, int *hour, int *min, int *sec, int *ms)
virtual int GetDaylightSavingsOffsetFromOS (int64_t time_sec)
virtual int GetLocalOffsetFromOS (int64_t time_ms, bool is_utc)
Static Public Member Functions
static int DaysFromTime (int64_t time_ms)
static int TimeInDay (int64_t time_ms, int days)
static bool TryTimeClip (double *time)
Static Public Attributes
static const int kMsPerMin = 60 * 1000
static const int kSecPerDay = 24 * 60 * 60
static const int64_t kMsPerDay = kSecPerDay * 1000
static const int64_t kMsPerMonth = kMsPerDay * 30
static const int kMaxEpochTimeInSec = kMaxInt
static const int64_t kMaxEpochTimeInMs = static_cast<int64_t>(kMaxInt) * 1000
static const int64_t kMaxTimeInMs
static const int64_t kMaxTimeBeforeUTCInMs = kMaxTimeInMs + kMsPerMonth
static const int kInvalidLocalOffsetInMs = kMaxInt
Private Member Functions
int DaylightSavingsOffsetInMs (int64_t time_ms)
void ProbeCache (int64_t time_ms)
CacheItem * LeastRecentlyUsedCacheItem (CacheItem *skip)
void ExtendTheAfterSegment (int64_t time_sec, int offset_ms)
void ClearSegment (CacheItem *segment)
bool InvalidSegment (CacheItem *segment)
Private Attributes
CacheItem cache_ [kCacheSize]
int cache_usage_counter_
CacheItem * before_
CacheItem * after_
int local_offset_ms_
bool ymd_valid_
int ymd_days_
int ymd_year_
int ymd_month_
int ymd_day_
const char * tz_name_
const char * dst_tz_name_
base::TimezoneCache * tz_cache_
Static Private Attributes
static const int kDefaultTimeZoneOffsetDeltaInMs = 19 * kSecPerDay * 1000
static const int kCacheSize = 32
Detailed Description
Definition at line 18 of file date.h.
Constructor & Destructor Documentation
DateCache()
v8::internal::DateCache::DateCache ()
Definition at line 31 of file date.cc.
    : tz_cache_(
#ifdef V8_INTL_SUPPORT
          Intl::CreateTimeZoneCache()
#else
          base::OS::CreateTimezoneCache()
#endif
      ) {
  ResetDateCache(base::TimezoneCache::TimeZoneDetection::kSkip);
}
References v8::base::TimezoneCache::kSkip, and ResetDateCache().
 DateCache()
virtual v8::internal::DateCache::~DateCache () [inline], [virtual]
Definition at line 42 of file date.h.
                       {
    delete tz_cache_;
    tz_cache_ = nullptr;
  }
Member Function Documentation
BreakDownTime()
void v8::internal::DateCache::BreakDownTime (int64_t time_ms, int * year, int * month, int * day, int * weekday, int * hour, int * min, int * sec, int * ms)
Definition at line 188 of file date.cc.
                                       {
  int const days = DaysFromTime(time_ms);
  int const time_in_day_ms = TimeInDay(time_ms, days);
  YearMonthDayFromDays(days, year, month, day);
  *weekday = Weekday(days);
  *hour = time_in_day_ms / (60 * 60 * 1000);
  *min = (time_in_day_ms / (60 * 1000)) % 60;
  *sec = (time_in_day_ms / 1000) % 60;
  *ms = time_in_day_ms % 1000;
}
References DaysFromTime(), TimeInDay(), Weekday(), and YearMonthDayFromDays().
Referenced by v8::internal::ToDateString().
ClearSegment()
void v8::internal::DateCache::ClearSegment (CacheItem * segment) [inline], [private]
Definition at line 63 of file date.cc.
                                               {
  segment->start_ms = 0;
  segment->end_ms = -1;
  segment->offset_ms = 0;
  segment->last_used = 0;
}
References v8::internal::DateCache::CacheItem::end_ms, v8::internal::DateCache::CacheItem::last_used, v8::internal::DateCache::CacheItem::offset_ms, and v8::internal::DateCache::CacheItem::start_ms.
Referenced by LeastRecentlyUsedCacheItem(), LocalOffsetInMs(), and ResetDateCache().
DaylightSavingsOffsetInMs()
int v8::internal::DateCache::DaylightSavingsOffsetInMs (int64_t time_ms) [inline], [private]
Definition at line 190 of file date.h.
                                                 {
    int time_sec = (time_ms >= 0 && time_ms <= kMaxEpochTimeInMs)
                       ? static_cast<int>(time_ms / 1000)
                       : static_cast<int>(EquivalentTime(time_ms) / 1000);
    return GetDaylightSavingsOffsetFromOS(time_sec);
  }
Referenced by GetLocalOffsetFromOS().
DaysFromTime()
static int v8::internal::DateCache::DaysFromTime (int64_t time_ms) [inline], [static]
Definition at line 52 of file date.h.
                                           {
    if (time_ms < 0) time_ms -= (kMsPerDay - 1);
    return static_cast<int>(time_ms / kMsPerDay);
  }
References v8::internal::anonymous_namespace{date.cc}::kMsPerDay.
Referenced by BreakDownTime(), v8::internal::JSDate::DoGetField(), v8::internal::JSDate::GetUTCField(), and v8::internal::JSDate::SetCachedFields().
DaysFromYearMonth()
int v8::internal::DateCache::DaysFromYearMonth (int year, int month)
Definition at line 149 of file date.cc.
                                                    {
  static const int day_from_month[] = {0, 31, 59, 90, 120, 151,
                                       181, 212, 243, 273, 304, 334};
  static const int day_from_month_leap[] = {0, 31, 60, 91, 121, 152,
                                            182, 213, 244, 274, 305, 335};
  year += month / 12;
  month %= 12;
  if (month < 0) {
    year--;
    month += 12;
  }
  DCHECK_GE(month, 0);
  DCHECK_LT(month, 12);
  // year_delta is an arbitrary number such that:
  // a) year_delta = -1 (mod 400)
  // b) year + year_delta > 0 for years in the range defined by
  // ECMA 262 - 15.9.1.1, i.e. upto 100,000,000 days on either side of
  // Jan 1 1970. This is required so that we don't run into integer
  // division of negative numbers.
  // c) there shouldn't be an overflow for 32-bit integers in the following
  // operations.
  static const int year_delta = 399999;
  static const int base_day =
      365 * (1970 + year_delta) + (1970 + year_delta) / 4 -
      (1970 + year_delta) / 100 + (1970 + year_delta) / 400;
  int year1 = year + year_delta;
  int day_from_year =
      365 * year1 + year1 / 4 - year1 / 100 + year1 / 400 - base_day;
  if ((year % 4 != 0) || (year % 100 == 0 && year % 400 != 0)) {
    return day_from_year + day_from_month[month];
  }
  return day_from_year + day_from_month_leap[month];
}
References DCHECK_GE, and DCHECK_LT.
Referenced by YearMonthDayFromDays().
EquivalentTime()
int64_t v8::internal::DateCache::EquivalentTime (int64_t time_ms) [inline]
Definition at line 130 of file date.h.
                                          {
    int days = DaysFromTime(time_ms);
    int time_within_day_ms = static_cast<int>(time_ms - days * kMsPerDay);
    int year, month, day;
    YearMonthDayFromDays(days, &year, &month, &day);
    int new_days = DaysFromYearMonth(EquivalentYear(year), month) + day - 1;
    return static_cast<int64_t>(new_days) * kMsPerDay + time_within_day_ms;
  }
References v8::internal::anonymous_namespace{date.cc}::kMsPerDay.
EquivalentYear()
int v8::internal::DateCache::EquivalentYear (int year) [inline]
Definition at line 143 of file date.h.
                               {
    int week_day = Weekday(DaysFromYearMonth(year, 0));
    int recent_year = (IsLeap(year) ? 1956 : 1967) + (week_day * 12) % 28;
    // Find the year in the range 2008..2037 that is equivalent mod 28.
    // Add 3*28 to give a positive argument to the modulus operator.
    return 2008 + (recent_year + 3 * 28 - 2008) % 28;
  }
ExtendTheAfterSegment()
void v8::internal::DateCache::ExtendTheAfterSegment (int64_t time_sec, int offset_ms) [inline], [private]
Definition at line 266 of file date.cc.
                                                                    {
  if (!InvalidSegment(after_) && after_->offset_ms == offset_ms &&
      after_->start_ms - kDefaultTimeZoneOffsetDeltaInMs <= time_ms &&
      time_ms <= after_->end_ms) {
    // Extend the after_ segment.
    after_->start_ms = time_ms;
  } else {
    // The after_ segment is either invalid or starts too late.
    if (!InvalidSegment(after_)) {
      // If the after_ segment is valid, replace it with a new segment.
      after_ = LeastRecentlyUsedCacheItem(before_);
    }
    after_->start_ms = time_ms;
    after_->end_ms = time_ms;
    after_->offset_ms = offset_ms;
    after_->last_used = ++cache_usage_counter_;
  }
}
References after_, before_, cache_usage_counter_, v8::internal::DateCache::CacheItem::end_ms, InvalidSegment(), kDefaultTimeZoneOffsetDeltaInMs, v8::internal::DateCache::CacheItem::last_used, LeastRecentlyUsedCacheItem(), v8::internal::DateCache::CacheItem::offset_ms, and v8::internal::DateCache::CacheItem::start_ms.
Referenced by LocalOffsetInMs().
GetDaylightSavingsOffsetFromOS()
virtual int v8::internal::DateCache::GetDaylightSavingsOffsetFromOS (int64_t time_sec) [inline], [virtual]
Definition at line 164 of file date.h.
                                                               {
    double time_ms = static_cast<double>(time_sec * 1000);
    return static_cast<int>(tz_cache_->DaylightSavingsOffset(time_ms));
  }
GetLocalOffsetFromOS()
int v8::internal::DateCache::GetLocalOffsetFromOS (int64_t time_ms, bool is_utc) [virtual]
Definition at line 203 of file date.cc.
                                                                {
  double offset;
#ifdef V8_INTL_SUPPORT
  if (v8_flags.icu_timezone_data) {
    offset = tz_cache_->LocalTimeOffset(static_cast<double>(time_ms), is_utc);
  } else {
#endif
    // When ICU timezone data is not used, we need to compute the timezone
    // offset for a given local time.
    //
    // The following shows that using DST for (t - LocalTZA - hour) produces
    // correct conversion where LocalTZA is the timezone offset in winter (no
    // DST) and the timezone offset is assumed to have no historical change.
    // Note that it does not work for the past and the future if LocalTZA (no
    // DST) is different from the current LocalTZA (no DST). For instance,
    // this will break for Europe/Moscow in 2012 ~ 2013 because LocalTZA was
    // 4h instead of the current 3h (as of 2018).
    //
    // Consider transition to DST at local time L1.
    // Let L0 = L1 - hour, L2 = L1 + hour,
    // U1 = UTC time that corresponds to L1,
    // U0 = U1 - hour.
    // Transitioning to DST moves local clock one hour forward L1 => L2, so
    // U0 = UTC time that corresponds to L0 = L0 - LocalTZA,
    // U1 = UTC time that corresponds to L1 = L1 - LocalTZA,
    // U1 = UTC time that corresponds to L2 = L2 - LocalTZA - hour.
    // Note that DST(U0 - hour) = 0, DST(U0) = 0, DST(U1) = 1.
    // U0 = L0 - LocalTZA - DST(L0 - LocalTZA - hour),
    // U1 = L1 - LocalTZA - DST(L1 - LocalTZA - hour),
    // U1 = L2 - LocalTZA - DST(L2 - LocalTZA - hour).
    //
    // Consider transition from DST at local time L1.
    // Let L0 = L1 - hour,
    // U1 = UTC time that corresponds to L1,
    // U0 = U1 - hour, U2 = U1 + hour.
    // Transitioning from DST moves local clock one hour back L1 => L0, so
    // U0 = UTC time that corresponds to L0 (before transition)
    // = L0 - LocalTZA - hour.
    // U1 = UTC time that corresponds to L0 (after transition)
    // = L0 - LocalTZA = L1 - LocalTZA - hour
    // U2 = UTC time that corresponds to L1 = L1 - LocalTZA.
    // Note that DST(U0) = 1, DST(U1) = 0, DST(U2) = 0.
    // U0 = L0 - LocalTZA - DST(L0 - LocalTZA - hour) = L0 - LocalTZA - DST(U0).
    // U2 = L1 - LocalTZA - DST(L1 - LocalTZA - hour) = L1 - LocalTZA - DST(U1).
    // It is impossible to get U1 from local time.
    if (local_offset_ms_ == kInvalidLocalOffsetInMs) {
      // This gets the constant LocalTZA (arguments are ignored).
      local_offset_ms_ =
          tz_cache_->LocalTimeOffset(static_cast<double>(time_ms), is_utc);
    }
    offset = local_offset_ms_;
    if (!is_utc) {
      const int kMsPerHour = 3600 * 1000;
      time_ms -= (offset + kMsPerHour);
    }
    offset += DaylightSavingsOffsetInMs(time_ms);
#ifdef V8_INTL_SUPPORT
  }
#endif
  DCHECK_LT(offset, kInvalidLocalOffsetInMs);
  return static_cast<int>(offset);
}
References DaylightSavingsOffsetInMs(), DCHECK_LT, kInvalidLocalOffsetInMs, v8::internal::anonymous_namespace{date.cc}::kMsPerHour, local_offset_ms_, v8::base::TimezoneCache::LocalTimeOffset(), tz_cache_, and v8::internal::v8_flags.
Referenced by LocalOffsetInMs().
InvalidSegment()
bool v8::internal::DateCache::InvalidSegment (CacheItem * segment) [inline], [private]
Definition at line 214 of file date.h.
                                          {
    return segment->start_ms > segment->end_ms;
  }
References v8::internal::DateCache::CacheItem::end_ms, and v8::internal::DateCache::CacheItem::start_ms.
Referenced by ExtendTheAfterSegment(), LocalOffsetInMs(), and ProbeCache().
IsLeap()
bool v8::internal::DateCache::IsLeap (int year) [inline]
Definition at line 84 of file date.h.
                        {
    return year % 4 == 0 && (year % 100 != 0 || year % 400 == 0);
  }
LeastRecentlyUsedCacheItem()
DateCache::CacheItem * v8::internal::DateCache::LeastRecentlyUsedCacheItem (CacheItem * skip) [private]
Definition at line 456 of file date.cc.
                                                                         {
  CacheItem* result = nullptr;
  for (int i = 0; i < kCacheSize; ++i) {
    if (&cache_[i] == skip) continue;
    if (result == nullptr || result->last_used > cache_[i].last_used) {
      result = &cache_[i];
    }
  }
  ClearSegment(result);
  return result;
}
References cache_, ClearSegment(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, kCacheSize, v8::internal::DateCache::CacheItem::last_used, and v8::base::internal::result.
Referenced by ExtendTheAfterSegment(), and ProbeCache().
LocalOffsetInMs()
int v8::internal::DateCache::LocalOffsetInMs (int64_t time, bool is_utc)
Definition at line 285 of file date.cc.
                                                           {
  if (!is_utc) {
    return GetLocalOffsetFromOS(time_ms, is_utc);
  }
#ifdef ENABLE_SLOW_DCHECKS
  int known_correct_result = 0;
  if (v8_flags.enable_slow_asserts) {
    // When slow DCHECKs are enabled, we always retrieve the known good result
    // (slow) and check that the result produced by the cache matches it.
    known_correct_result = GetLocalOffsetFromOS(time_ms, is_utc);
  }
#endif // ENABLE_SLOW_DCHECKS
  // Invalidate cache if the usage counter is close to overflow.
  // Note that cache_usage_counter is incremented less than ten times
  // in this function.
  if (cache_usage_counter_ >= kMaxInt - 10) {
    cache_usage_counter_ = 0;
    for (int i = 0; i < kCacheSize; ++i) {
      ClearSegment(&cache_[i]);
    }
  }
  // Optimistic fast check.
  if (before_->start_ms <= time_ms && time_ms <= before_->end_ms) {
    // Cache hit.
    before_->last_used = ++cache_usage_counter_;
    SLOW_DCHECK(before_->offset_ms == known_correct_result);
    return before_->offset_ms;
  }
  ProbeCache(time_ms);
  DCHECK(InvalidSegment(before_) || before_->start_ms <= time_ms);
  DCHECK(InvalidSegment(after_) || time_ms < after_->start_ms);
  if (InvalidSegment(before_)) {
    // Cache miss.
    before_->start_ms = time_ms;
    before_->end_ms = time_ms;
    before_->offset_ms = GetLocalOffsetFromOS(time_ms, is_utc);
    before_->last_used = ++cache_usage_counter_;
    SLOW_DCHECK(before_->offset_ms == known_correct_result);
    return before_->offset_ms;
  }
  if (time_ms <= before_->end_ms) {
    // Cache hit.
    before_->last_used = ++cache_usage_counter_;
    SLOW_DCHECK(before_->offset_ms == known_correct_result);
    return before_->offset_ms;
  }
  if (time_ms - kDefaultTimeZoneOffsetDeltaInMs > before_->end_ms) {
    // If the before_ segment ends too early, then just
    // query for the offset of the time_ms
    int offset_ms = GetLocalOffsetFromOS(time_ms, is_utc);
    ExtendTheAfterSegment(time_ms, offset_ms);
    // This swap helps the optimistic fast check in subsequent invocations.
    CacheItem* temp = before_;
    before_ = after_;
    after_ = temp;
    SLOW_DCHECK(offset_ms == known_correct_result);
    return offset_ms;
  }
  // Now the time_ms is between
  // before_->end_ms and before_->end_ms + default time zone offset delta.
  // Update the usage counter of before_ since it is going to be used.
  before_->last_used = ++cache_usage_counter_;
  // Check if after_ segment is invalid or starts too late.
  int64_t new_after_start_ms =
      before_->end_ms + kDefaultTimeZoneOffsetDeltaInMs;
  if (InvalidSegment(after_) || new_after_start_ms <= after_->start_ms) {
    int new_offset_ms = GetLocalOffsetFromOS(new_after_start_ms, is_utc);
    ExtendTheAfterSegment(new_after_start_ms, new_offset_ms);
  } else {
    DCHECK(!InvalidSegment(after_));
    // Update the usage counter of after_ since it is going to be used.
    after_->last_used = ++cache_usage_counter_;
  }
  // Now the time_ms is between before_->end_ms and after_->start_ms.
  // Only one daylight savings offset change can occur in this interval.
  if (before_->offset_ms == after_->offset_ms) {
    // Merge two segments if they have the same offset.
    before_->end_ms = after_->end_ms;
    ClearSegment(after_);
    SLOW_DCHECK(before_->offset_ms == known_correct_result);
    return before_->offset_ms;
  }
  // Binary search for time zone offset change point,
  // but give up if we don't find it in five iterations.
  for (int i = 4; i >= 0; --i) {
    int64_t delta = after_->start_ms - before_->end_ms;
    int64_t middle_sec = (i == 0) ? time_ms : before_->end_ms + delta / 2;
    int offset_ms = GetLocalOffsetFromOS(middle_sec, is_utc);
    if (before_->offset_ms == offset_ms) {
      before_->end_ms = middle_sec;
      if (time_ms <= before_->end_ms) {
        SLOW_DCHECK(offset_ms == known_correct_result);
        return offset_ms;
      }
      // If we didn't return, we can't be in the last iteration.
      DCHECK_GT(i, 0);
    } else {
      DCHECK(after_->offset_ms == offset_ms);
      after_->start_ms = middle_sec;
      if (time_ms >= after_->start_ms) {
        // This swap helps the optimistic fast check in subsequent invocations.
        CacheItem* temp = before_;
        before_ = after_;
        after_ = temp;
        SLOW_DCHECK(offset_ms == known_correct_result);
        return offset_ms;
      }
      // If we didn't return, we can't be in the last iteration.
      DCHECK_GT(i, 0);
    }
  }
  // During the last iteration, we set middle_sec = time_ms and return via one
  // of the two return statements above. Thus, we never end up here.
  UNREACHABLE();
}
References after_, before_, cache_, cache_usage_counter_, ClearSegment(), v8::internal::DCHECK(), DCHECK_GT, v8::internal::DateCache::CacheItem::end_ms, ExtendTheAfterSegment(), GetLocalOffsetFromOS(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, InvalidSegment(), kCacheSize, kDefaultTimeZoneOffsetDeltaInMs, v8::internal::kMaxInt, v8::internal::DateCache::CacheItem::last_used, v8::internal::DateCache::CacheItem::offset_ms, ProbeCache(), SLOW_DCHECK, v8::internal::DateCache::CacheItem::start_ms, v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
LocalTimezone()
const char* v8::internal::DateCache::LocalTimezone (int64_t time_ms) [inline]
Definition at line 91 of file date.h.
                                             {
    if (time_ms < 0 || time_ms > kMaxEpochTimeInMs) {
      time_ms = EquivalentTime(time_ms);
    }
    bool is_dst = DaylightSavingsOffsetInMs(time_ms) != 0;
    const char** name = is_dst ? &dst_tz_name_ : &tz_name_;
    if (*name == nullptr) {
      *name = tz_cache_->LocalTimezone(static_cast<double>(time_ms));
    }
    return *name;
  }
References v8::internal::name.
Referenced by v8::internal::ToDateString().
ProbeCache()
void v8::internal::DateCache::ProbeCache (int64_t time_ms) [private]
Definition at line 412 of file date.cc.
                                          {
  CacheItem* before = nullptr;
  CacheItem* after = nullptr;
  DCHECK(before_ != after_);
  for (int i = 0; i < kCacheSize; ++i) {
    if (InvalidSegment(&cache_[i])) {
      continue;
    }
    if (cache_[i].start_ms <= time_ms) {
      if (before == nullptr || before->start_ms < cache_[i].start_ms) {
        before = &cache_[i];
      }
    } else if (time_ms < cache_[i].end_ms) {
      if (after == nullptr || after->end_ms > cache_[i].end_ms) {
        after = &cache_[i];
      }
    }
  }
  // If before or after segments were not found,
  // then set them to any invalid segment.
  if (before == nullptr) {
    before =
        InvalidSegment(before_) ? before_ : LeastRecentlyUsedCacheItem(after);
  }
  if (after == nullptr) {
    after = InvalidSegment(after_) && before != after_
                ? after_
                : LeastRecentlyUsedCacheItem(before);
  }
  DCHECK_NOT_NULL(before);
  DCHECK_NOT_NULL(after);
  DCHECK(before != after);
  DCHECK(InvalidSegment(before) || before->start_ms <= time_ms);
  DCHECK(InvalidSegment(after) || time_ms < after->start_ms);
  DCHECK(InvalidSegment(before) || InvalidSegment(after) ||
         before->end_ms < after->start_ms);
  before_ = before;
  after_ = after;
}
References after_, before_, cache_, v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::DateCache::CacheItem::end_ms, v8::internal::anonymous_namespace{json-stringifier.cc}::i, InvalidSegment(), kCacheSize, LeastRecentlyUsedCacheItem(), and v8::internal::DateCache::CacheItem::start_ms.
Referenced by LocalOffsetInMs().
ResetDateCache()
void v8::internal::DateCache::ResetDateCache (base::TimezoneCache::TimeZoneDetection time_zone_detection)
Definition at line 42 of file date.cc.
                                                            {
  for (int i = 0; i < kCacheSize; ++i) {
    ClearSegment(&cache_[i]);
  }
  cache_usage_counter_ = 0;
  before_ = &cache_[0];
  after_ = &cache_[1];
  ymd_valid_ = false;
#ifdef V8_INTL_SUPPORT
  if (!v8_flags.icu_timezone_data) {
#endif
    local_offset_ms_ = kInvalidLocalOffsetInMs;
#ifdef V8_INTL_SUPPORT
  }
#endif
  tz_cache_->Clear(time_zone_detection);
  tz_name_ = nullptr;
  dst_tz_name_ = nullptr;
}
References after_, before_, cache_, cache_usage_counter_, v8::base::TimezoneCache::Clear(), ClearSegment(), dst_tz_name_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kCacheSize, kInvalidLocalOffsetInMs, local_offset_ms_, tz_cache_, tz_name_, v8::internal::v8_flags, and ymd_valid_.
Referenced by DateCache(), and v8::Isolate::DateTimeConfigurationChangeNotification().
TimeInDay()
static int v8::internal::DateCache::TimeInDay (int64_t time_ms, int days) [inline], [static]
Definition at line 59 of file date.h.
                                                  {
    return static_cast<int>(time_ms - days * kMsPerDay);
  }
References v8::internal::anonymous_namespace{date.cc}::kMsPerDay.
Referenced by BreakDownTime(), v8::internal::JSDate::DoGetField(), v8::internal::JSDate::GetUTCField(), and v8::internal::JSDate::SetCachedFields().
TimezoneOffset()
int v8::internal::DateCache::TimezoneOffset (int64_t time_ms) [inline]
Definition at line 104 of file date.h.
                                      {
    int64_t local_ms = ToLocal(time_ms);
    return static_cast<int>((time_ms - local_ms) / kMsPerMin);
  }
Referenced by v8::internal::JSDate::GetUTCField(), and v8::internal::ToDateString().
ToLocal()
int64_t v8::internal::DateCache::ToLocal (int64_t time_ms) [inline]
Definition at line 111 of file date.h.
                                   {
    return time_ms + LocalOffsetInMs(time_ms, true);
  }
Referenced by v8::internal::JSDate::DoGetField(), v8::internal::JSDate::SetValue(), v8::internal::ToDateString(), and v8::internal::JSDate::UpdateFieldsAfterDeserialization().
ToUTC()
int64_t v8::internal::DateCache::ToUTC (int64_t time_ms) [inline]
Definition at line 117 of file date.h.
                                 {
    return time_ms - LocalOffsetInMs(time_ms, false);
  }
Referenced by v8::internal::ParseDateTimeString(), and v8::internal::anonymous_namespace{builtins-date.cc}::SetLocalDateValue().
TryTimeClip()
static bool v8::internal::DateCache::TryTimeClip (double * time) [inline], [static]
Definition at line 67 of file date.h.
                                        {
    if (-kMaxTimeInMs <= *time && *time <= kMaxTimeInMs) {
      // Inline the finite part of DoubleToInteger here, since the range check
      // already covers the non-finite checks.
      *time = ((*time > 0) ? std::floor(*time) : std::ceil(*time)) + 0.0;
      return true;
    }
    return false;
  }
References v8::internal::time.
Referenced by v8::internal::BUILTIN(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatDateTime(), v8::internal::JSDateTimeFormat::FormatToParts(), v8::internal::anonymous_namespace{js-date-time-format.cc}::HandleDateTimeOthers(), v8::internal::JSDate::New(), v8::internal::ParseDateTimeString(), v8::internal::anonymous_namespace{js-date-time-format.cc}::PartitionDateTimeRangePattern(), v8::internal::anonymous_namespace{builtins-date.cc}::SetDateValue(), v8::internal::anonymous_namespace{builtins-date.cc}::SetLocalDateValue(), and v8::internal::JSDate::SetValue().
Weekday()
int v8::internal::DateCache::Weekday (int days) [inline]
Definition at line 79 of file date.h.
                        {
    int result = (days + 4) % 7;
    return result >= 0 ? result : result + 7;
  }
References v8::base::internal::result.
Referenced by BreakDownTime(), v8::internal::JSDate::GetUTCField(), and v8::internal::JSDate::SetCachedFields().
YearMonthDayFromDays()
void v8::internal::DateCache::YearMonthDayFromDays (int days, int * year, int * month, int * day)
Definition at line 70 of file date.cc.
                                               {
  if (ymd_valid_) {
    // Check conservatively if the given 'days' has
    // the same year and month as the cached 'days'.
    int new_day = ymd_day_ + (days - ymd_days_);
    if (new_day >= 1 && new_day <= 28) {
      ymd_day_ = new_day;
      ymd_days_ = days;
      *year = ymd_year_;
      *month = ymd_month_;
      *day = new_day;
      return;
    }
  }
  int save_days = days;
  days += kDaysOffset;
  *year = 400 * (days / kDaysIn400Years) - kYearsOffset;
  days %= kDaysIn400Years;
  DCHECK_EQ(save_days, DaysFromYearMonth(*year, 0) + days);
  days--;
  int yd1 = days / kDaysIn100Years;
  days %= kDaysIn100Years;
  *year += 100 * yd1;
  days++;
  int yd2 = days / kDaysIn4Years;
  days %= kDaysIn4Years;
  *year += 4 * yd2;
  days--;
  int yd3 = days / 365;
  days %= 365;
  *year += yd3;
  bool is_leap = (!yd1 || yd2) && !yd3;
  DCHECK_GE(days, -1);
  DCHECK(is_leap || (days >= 0));
  DCHECK((days < 365) || (is_leap && (days < 366)));
  DCHECK(is_leap == ((*year % 4 == 0) && (*year % 100 || (*year % 400 == 0))));
  DCHECK(is_leap || ((DaysFromYearMonth(*year, 0) + days) == save_days));
  DCHECK(!is_leap || ((DaysFromYearMonth(*year, 0) + days + 1) == save_days));
  days += is_leap;
  // Check if the date is after February.
  if (days >= 31 + 28 + (is_leap ? 1 : 0)) {
    days -= 31 + 28 + (is_leap ? 1 : 0);
    // Find the date starting from March.
    for (int i = 2; i < 12; i++) {
      if (days < kDaysInMonths[i]) {
        *month = i;
        *day = days + 1;
        break;
      }
      days -= kDaysInMonths[i];
    }
  } else {
    // Check January and February.
    if (days < 31) {
      *month = 0;
      *day = days + 1;
    } else {
      *month = 1;
      *day = days - 31 + 1;
    }
  }
  DCHECK(DaysFromYearMonth(*year, *month) + *day - 1 == save_days);
  ymd_valid_ = true;
  ymd_year_ = *year;
  ymd_month_ = *month;
  ymd_day_ = *day;
  ymd_days_ = save_days;
}
References DaysFromYearMonth(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kDaysIn100Years, v8::internal::kDaysIn400Years, v8::internal::kDaysIn4Years, v8::internal::kDaysInMonths, v8::internal::kDaysOffset, v8::internal::kYearsOffset, ymd_day_, ymd_days_, ymd_month_, ymd_valid_, and ymd_year_.
Referenced by BreakDownTime(), v8::internal::JSDate::GetUTCField(), and v8::internal::JSDate::SetCachedFields().
Member Data Documentation
after_
CacheItem* v8::internal::DateCache::after_ [private]
Definition at line 222 of file date.h.
Referenced by ExtendTheAfterSegment(), LocalOffsetInMs(), ProbeCache(), and ResetDateCache().
before_
CacheItem* v8::internal::DateCache::before_ [private]
Definition at line 221 of file date.h.
Referenced by ExtendTheAfterSegment(), LocalOffsetInMs(), ProbeCache(), and ResetDateCache().
cache_
CacheItem v8::internal::DateCache::cache_[kCacheSize] [private]
Definition at line 219 of file date.h.
Referenced by LeastRecentlyUsedCacheItem(), LocalOffsetInMs(), ProbeCache(), and ResetDateCache().
cache_usage_counter_
int v8::internal::DateCache::cache_usage_counter_ [private]
Definition at line 220 of file date.h.
Referenced by ExtendTheAfterSegment(), LocalOffsetInMs(), and ResetDateCache().
dst_tz_name_
const char* v8::internal::DateCache::dst_tz_name_ [private]
Definition at line 235 of file date.h.
Referenced by ResetDateCache().
kCacheSize
const int v8::internal::DateCache::kCacheSize = 32 [static], [private]
Definition at line 178 of file date.h.
Referenced by LeastRecentlyUsedCacheItem(), LocalOffsetInMs(), ProbeCache(), and ResetDateCache().
kDefaultTimeZoneOffsetDeltaInMs
const int v8::internal::DateCache::kDefaultTimeZoneOffsetDeltaInMs = 19 * kSecPerDay * 1000 [static], [private]
Definition at line 176 of file date.h.
Referenced by ExtendTheAfterSegment(), and LocalOffsetInMs().
kInvalidLocalOffsetInMs
const int v8::internal::DateCache::kInvalidLocalOffsetInMs = kMaxInt [static]
Definition at line 38 of file date.h.
Referenced by GetLocalOffsetFromOS(), and ResetDateCache().
kMaxEpochTimeInMs
const int64_t v8::internal::DateCache::kMaxEpochTimeInMs = static_cast<int64_t>(kMaxInt) * 1000 [static]
Definition at line 27 of file date.h.
kMaxEpochTimeInSec
const int v8::internal::DateCache::kMaxEpochTimeInSec = kMaxInt [static]
Definition at line 26 of file date.h.
kMaxTimeBeforeUTCInMs
const int64_t v8::internal::DateCache::kMaxTimeBeforeUTCInMs = kMaxTimeInMs + kMsPerMonth [static]
Definition at line 35 of file date.h.
Referenced by v8::internal::BUILTIN(), v8::internal::ParseDateTimeString(), and v8::internal::anonymous_namespace{builtins-date.cc}::SetLocalDateValue().
kMaxTimeInMs
const int64_t v8::internal::DateCache::kMaxTimeInMs [static]
Initial value:
=
      static_cast<int64_t>(864000000) * 10000000
Definition at line 30 of file date.h.
kMsPerDay
const int64_t v8::internal::DateCache::kMsPerDay = kSecPerDay * 1000 [static]
Definition at line 22 of file date.h.
kMsPerMin
const int v8::internal::DateCache::kMsPerMin = 60 * 1000 [static]
Definition at line 20 of file date.h.
kMsPerMonth
const int64_t v8::internal::DateCache::kMsPerMonth = kMsPerDay * 30 [static]
Definition at line 23 of file date.h.
kSecPerDay
const int v8::internal::DateCache::kSecPerDay = 24 * 60 * 60 [static]
Definition at line 21 of file date.h.
local_offset_ms_
int v8::internal::DateCache::local_offset_ms_ [private]
Definition at line 224 of file date.h.
Referenced by GetLocalOffsetFromOS(), and ResetDateCache().
tz_cache_
base::TimezoneCache* v8::internal::DateCache::tz_cache_ [private]
Definition at line 237 of file date.h.
Referenced by GetLocalOffsetFromOS(), and ResetDateCache().
tz_name_
const char* v8::internal::DateCache::tz_name_ [private]
Definition at line 234 of file date.h.
Referenced by ResetDateCache().
ymd_day_
int v8::internal::DateCache::ymd_day_ [private]
Definition at line 231 of file date.h.
Referenced by YearMonthDayFromDays().
ymd_days_
int v8::internal::DateCache::ymd_days_ [private]
Definition at line 228 of file date.h.
Referenced by YearMonthDayFromDays().
ymd_month_
int v8::internal::DateCache::ymd_month_ [private]
Definition at line 230 of file date.h.
Referenced by YearMonthDayFromDays().
ymd_valid_
bool v8::internal::DateCache::ymd_valid_ [private]
Definition at line 227 of file date.h.
Referenced by ResetDateCache(), and YearMonthDayFromDays().
ymd_year_
int v8::internal::DateCache::ymd_year_ [private]
Definition at line 229 of file date.h.
Referenced by YearMonthDayFromDays().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/date/date.h
/mnt/V8SourceCode/src/date/date.cc