v8::internal::torque::Symbol Class Reference
#include <earley-parser.h>
Public Member Functions
Symbol ()=default
Symbol (std::initializer_list< Rule > rules)
Symbol (const Symbol &)=delete
Symbol & operator= (const Symbol &)=delete
V8_EXPORT_PRIVATE Symbol & operator= (std::initializer_list< Rule > rules)
bool IsTerminal () const
Rule * rule (size_t index) const
size_t rule_number () const
void AddRule (const Rule &rule)
V8_EXPORT_PRIVATE std::optional< ParseResult > RunAction (const Item *item, const LexerResult &tokens)
Private Attributes
std::vector< std::unique_ptr< Rule > > rules_
Detailed Description
Definition at line 246 of file earley-parser.h.
Constructor & Destructor Documentation
Symbol() [1/3]
v8::internal::torque::Symbol::Symbol () [default]
Symbol() [2/3]
v8::internal::torque::Symbol::Symbol (std::initializer_list< Rule > rules) [inline]
Definition at line 249 of file earley-parser.h.
{ *this = rules; }
Symbol() [3/3]
v8::internal::torque::Symbol::Symbol (const Symbol &) [delete]
Member Function Documentation
AddRule()
void v8::internal::torque::Symbol::AddRule (const Rule & rule) [inline]
Definition at line 261 of file earley-parser.h.
                                 {
    rules_.push_back(std::make_unique<Rule>(rule));
    rules_.back()->SetLeftHandSide(this);
  }
References rule(), and rules_.
Referenced by operator=(), and v8::internal::torque::RunEarleyAlgorithm().
IsTerminal()
bool v8::internal::torque::Symbol::IsTerminal () const [inline]
Definition at line 257 of file earley-parser.h.
{ return rules_.empty(); }
References rules_.
Referenced by v8::internal::torque::RunEarleyAlgorithm().
operator=() [1/2]
Symbol& v8::internal::torque::Symbol::operator= (const Symbol &) [delete]
operator=() [2/2]
Symbol & v8::internal::torque::Symbol::operator= (std::initializer_list< Rule > rules)
Definition at line 63 of file earley-parser.cc.
                                                         {
  rules_.clear();
  for (const Rule& rule : rules) {
    AddRule(rule);
  }
  return *this;
}
References AddRule(), rule(), and rules_.
rule()
Rule* v8::internal::torque::Symbol::rule (size_t index) const [inline]
Definition at line 258 of file earley-parser.h.
{ return rules_[index].get(); }
References v8::internal::index, and rules_.
Referenced by AddRule(), operator=(), and v8::internal::torque::RunEarleyAlgorithm().
rule_number()
size_t v8::internal::torque::Symbol::rule_number () const [inline]
Definition at line 259 of file earley-parser.h.
{ return rules_.size(); }
References rules_.
Referenced by v8::internal::torque::RunEarleyAlgorithm().
RunAction()
std::optional< ParseResult > v8::internal::torque::Symbol::RunAction (const Item * item, const LexerResult & tokens) [inline]
Definition at line 362 of file earley-parser.h.
                                                                               {
  DCHECK(item->IsComplete());
  DCHECK_EQ(item->left(), this);
  return item->rule()->RunAction(item, tokens);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::torque::Item::IsComplete(), v8::internal::torque::Item::left(), v8::internal::torque::Item::rule(), and v8::internal::torque::Rule::RunAction().
Referenced by v8::internal::torque::ParseTokens().
Member Data Documentation
rules_
std::vector<std::unique_ptr<Rule> > v8::internal::torque::Symbol::rules_ [private]
Definition at line 270 of file earley-parser.h.
Referenced by AddRule(), IsTerminal(), operator=(), rule(), and rule_number().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/earley-parser.h
/mnt/V8SourceCode/src/torque/earley-parser.cc