v8::internal::wasm::WasmCodeAllocator Class Reference
#include <wasm-code-manager.h>
Public Member Functions
WasmCodeAllocator (std::shared_ptr< Counters > async_counters)
~WasmCodeAllocator ()
void Init (VirtualMemory code_space)
void InitializeCodeRange (NativeModule *native_module, base::AddressRegion region)
size_t committed_code_space () const
size_t generated_code_size () const
size_t freed_code_size () const
base::Vector< uint8_t > AllocateForCode (NativeModule *, size_t size)
base::Vector< uint8_t > AllocateForWrapper (size_t size)
base::Vector< uint8_t > AllocateForCodeInRegion (NativeModule *, size_t size, base::AddressRegion)
void FreeCode (base::Vector< WasmCode *const >)
size_t GetNumCodeSpaces () const
Counters * counters () const
Private Attributes
DisjointAllocationPool free_code_space_
DisjointAllocationPool freed_code_space_
std::vector< VirtualMemory > owned_code_space_
std::atomic< size_t > committed_code_space_ {0}
std::atomic< size_t > generated_code_size_ {0}
std::atomic< size_t > freed_code_size_ {0}
std::shared_ptr< Counters > async_counters_
Detailed Description
Definition at line 536 of file wasm-code-manager.h.
Constructor & Destructor Documentation
WasmCodeAllocator()
v8::internal::wasm::WasmCodeAllocator::WasmCodeAllocator (std::shared_ptr< Counters > async_counters) [explicit]
Definition at line 635 of file wasm-code-manager.cc.
    : async_counters_(std::move(async_counters)) {
  owned_code_space_.reserve(4);
}
References owned_code_space_.
 WasmCodeAllocator()
v8::internal::wasm::WasmCodeAllocator::~WasmCodeAllocator ()
Definition at line 640 of file wasm-code-manager.cc.
                                      {
  GetWasmCodeManager()->FreeNativeModule(base::VectorOf(owned_code_space_),
                                         committed_code_space());
}
References committed_code_space(), v8::internal::wasm::WasmCodeManager::FreeNativeModule(), v8::internal::wasm::GetWasmCodeManager(), owned_code_space_, and v8::base::VectorOf().
Member Function Documentation
AllocateForCode()
base::Vector< uint8_t > v8::internal::wasm::WasmCodeAllocator::AllocateForCode (NativeModule * native_module, size_t size)
Definition at line 824 of file wasm-code-manager.cc.
                                              {
  return AllocateForCodeInRegion(native_module, size, kUnrestrictedRegion);
}
References AllocateForCodeInRegion(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kUnrestrictedRegion, and size().
Referenced by v8::internal::wasm::NativeModule::AddCode(), v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::wasm::NativeModule::AddCompiledCode(), and v8::internal::wasm::NativeModule::AllocateForDeserializedCode().
AllocateForCodeInRegion()
base::Vector< uint8_t > v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion (NativeModule * native_module, size_t size, base::AddressRegion region)
Definition at line 834 of file wasm-code-manager.cc.
                                                                        {
  DCHECK_LT(0, size);
  auto* code_manager = GetWasmCodeManager();
  size = RoundUp<kCodeAlignment>(size);
  base::AddressRegion code_space =
      free_code_space_.AllocateInRegion(size, region);
  if (V8_UNLIKELY(code_space.is_empty())) {
    // Only allocations without a specific region are allowed to fail. Otherwise
    // the region must have been allocated big enough to hold all initial
    // allocations (jump tables etc).
    CHECK_EQ(kUnrestrictedRegion, region);
    size_t total_reserved = 0;
    for (auto& vmem : owned_code_space_) total_reserved += vmem.size();
    size_t reserve_size =
        native_module
            ? ReservationSizeForWasmCode(
                  size, native_module->module()->num_declared_functions,
                  total_reserved)
            : ReservationSizeForWrappers(size, total_reserved);
    if (reserve_size < size) {
      auto oom_detail = base::FormattedString{}
                        << "cannot reserve space for " << size
                        << "bytes of code (maximum reservation size is "
                        << reserve_size << ")";
      V8::FatalProcessOutOfMemory(nullptr, "Grow wasm code space",
                                  oom_detail.PrintToArray().data());
    }
    VirtualMemory new_mem = code_manager->TryAllocate(reserve_size);
    if (!new_mem.IsReserved()) {
      auto oom_detail = base::FormattedString{}
                        << "cannot allocate more code space (" << reserve_size
                        << " bytes, currently " << total_reserved << ")";
      V8::FatalProcessOutOfMemory(nullptr, "Grow wasm code space",
                                  oom_detail.PrintToArray().data());
      UNREACHABLE();
    }
    base::AddressRegion new_region = new_mem.region();
    free_code_space_.Merge(new_region);
    owned_code_space_.emplace_back(std::move(new_mem));
    InitializeCodeRange(native_module, new_region);
    if (native_module) {
      code_manager->AssignRange(new_region, native_module);
      native_module->AddCodeSpaceLocked(new_region);
      async_counters_->wasm_module_num_code_spaces()->AddSample(
          static_cast<int>(owned_code_space_.size()));
    }
    code_space = free_code_space_.Allocate(size);
    CHECK(!code_space.is_empty());
  }
  const Address commit_page_size = CommitPageSize();
  Address commit_start = RoundUp(code_space.begin(), commit_page_size);
  Address commit_end = RoundUp(code_space.end(), commit_page_size);
  // {commit_start} will be either code_space.start or the start of the next
  // page. {commit_end} will be the start of the page after the one in which
  // the allocation ends.
  // We start from an aligned start, and we know we allocated vmem in
  // page multiples.
  // We just need to commit what's not committed. The page in which we
  // start is already committed (or we start at the beginning of a page).
  // The end needs to be committed all through the end of the page.
  if (commit_start < commit_end) {
    for (base::AddressRegion split_range : SplitRangeByReservationsIfNeeded(
             {commit_start, commit_end - commit_start}, owned_code_space_)) {
      code_manager->Commit(split_range);
    }
    committed_code_space_.fetch_add(commit_end - commit_start);
    // Committed code cannot grow bigger than maximum code space size.
    DCHECK_LE(committed_code_space_.load(),
              v8_flags.wasm_max_committed_code_mb * MB);
  }
  DCHECK(IsAligned(code_space.begin(), kCodeAlignment));
  generated_code_size_.fetch_add(code_space.size(), std::memory_order_relaxed);
  TRACE_HEAP("Code alloc for %p: 0x%" PRIxPTR ",+%zu\n", this,
             code_space.begin(), size);
  return {reinterpret_cast<uint8_t*>(code_space.begin()), code_space.size()};
}
References v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), v8::internal::wasm::DisjointAllocationPool::Allocate(), v8::internal::wasm::DisjointAllocationPool::AllocateInRegion(), async_counters_, v8::base::AddressRegion::begin(), CHECK, CHECK_EQ, v8::internal::CommitPageSize(), committed_code_space_, v8::internal::DCHECK(), DCHECK_LE, DCHECK_LT, v8::base::AddressRegion::end(), v8::internal::V8::FatalProcessOutOfMemory(), free_code_space_, generated_code_size_, v8::internal::wasm::GetWasmCodeManager(), InitializeCodeRange(), v8::base::AddressRegion::is_empty(), IsAligned(), v8::internal::VirtualMemory::IsReserved(), v8::internal::kCodeAlignment, v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kUnrestrictedRegion, v8::internal::MB, v8::internal::wasm::DisjointAllocationPool::Merge(), v8::internal::wasm::NativeModule::module(), v8::internal::wasm::WasmModule::num_declared_functions, owned_code_space_, v8::internal::VirtualMemory::region(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::ReservationSizeForWasmCode(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::ReservationSizeForWrappers(), RoundUp(), v8::base::AddressRegion::size(), size(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::SplitRangeByReservationsIfNeeded(), TRACE_HEAP, v8::internal::UNREACHABLE(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by AllocateForCode(), AllocateForWrapper(), v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegionLocked(), and InitializeCodeRange().
AllocateForWrapper()
base::Vector< uint8_t > v8::internal::wasm::WasmCodeAllocator::AllocateForWrapper (size_t size)
Definition at line 829 of file wasm-code-manager.cc.
                                                                     {
  return AllocateForCodeInRegion(nullptr, size, kUnrestrictedRegion);
}
References AllocateForCodeInRegion(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kUnrestrictedRegion, and size().
committed_code_space()
size_t v8::internal::wasm::WasmCodeAllocator::committed_code_space () const [inline]
Definition at line 548 of file wasm-code-manager.h.
                                      {
    return committed_code_space_.load(std::memory_order_acquire);
  }
References committed_code_space_.
Referenced by v8::internal::wasm::NativeModule::SampleCodeSize(), and ~WasmCodeAllocator().
counters()
Counters* v8::internal::wasm::WasmCodeAllocator::counters () const [inline]
Definition at line 578 of file wasm-code-manager.h.
{ return async_counters_.get(); }
References async_counters_.
FreeCode()
void v8::internal::wasm::WasmCodeAllocator::FreeCode (base::Vector< WasmCode *const > codes)
Definition at line 917 of file wasm-code-manager.cc.
                                                                  {
  // Zap code area and collect freed code regions.
  DisjointAllocationPool freed_regions;
  size_t code_size = 0;
  for (WasmCode* code : codes) {
    code_size += code->instructions().size();
    freed_regions.Merge(base::AddressRegion{code->instruction_start(),
                                            code->instructions().size()});
    ThreadIsolation::UnregisterWasmAllocation(code->instruction_start(),
                                              code->instructions().size());
  }
  freed_code_size_.fetch_add(code_size);
  // Merge {freed_regions} into {freed_code_space_} and put all ranges of full
  // pages to decommit into {regions_to_decommit} (decommitting is expensive,
  // so try to merge regions before decommitting).
  DisjointAllocationPool regions_to_decommit;
  size_t commit_page_size = CommitPageSize();
  for (auto region : freed_regions.regions()) {
    auto merged_region = freed_code_space_.Merge(region);
    Address discard_start =
        std::max(RoundUp(merged_region.begin(), commit_page_size),
                 RoundDown(region.begin(), commit_page_size));
    Address discard_end =
        std::min(RoundDown(merged_region.end(), commit_page_size),
                 RoundUp(region.end(), commit_page_size));
    if (discard_start >= discard_end) continue;
    regions_to_decommit.Merge({discard_start, discard_end - discard_start});
  }
  auto* code_manager = GetWasmCodeManager();
  for (auto region : regions_to_decommit.regions()) {
    [[maybe_unused]] size_t old_committed =
        committed_code_space_.fetch_sub(region.size());
    DCHECK_GE(old_committed, region.size());
    for (base::AddressRegion split_range :
         SplitRangeByReservationsIfNeeded(region, owned_code_space_)) {
      code_manager->Decommit(split_range);
    }
  }
}
References code, v8::internal::CommitPageSize(), committed_code_space_, DCHECK_GE, freed_code_size_, freed_code_space_, v8::internal::wasm::GetWasmCodeManager(), v8::internal::wasm::DisjointAllocationPool::Merge(), owned_code_space_, v8::internal::wasm::DisjointAllocationPool::regions(), RoundDown(), RoundUp(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::SplitRangeByReservationsIfNeeded(), and v8::internal::ThreadIsolation::UnregisterWasmAllocation().
Referenced by v8::internal::wasm::NativeModule::FreeCode().
freed_code_size()
size_t v8::internal::wasm::WasmCodeAllocator::freed_code_size () const [inline]
Definition at line 554 of file wasm-code-manager.h.
                                 {
    return freed_code_size_.load(std::memory_order_acquire);
  }
References freed_code_size_.
Referenced by v8::internal::wasm::NativeModule::SampleCodeSize().
generated_code_size()
size_t v8::internal::wasm::WasmCodeAllocator::generated_code_size () const [inline]
Definition at line 551 of file wasm-code-manager.h.
                                     {
    return generated_code_size_.load(std::memory_order_acquire);
  }
References generated_code_size_.
Referenced by v8::internal::wasm::NativeModule::SampleCodeSize().
GetNumCodeSpaces()
size_t v8::internal::wasm::WasmCodeAllocator::GetNumCodeSpaces () const
Definition at line 959 of file wasm-code-manager.cc.
                                                 {
  return owned_code_space_.size();
}
References owned_code_space_.
Referenced by v8::internal::wasm::NativeModule::GetNumberOfCodeSpacesForTesting().
Init()
void v8::internal::wasm::WasmCodeAllocator::Init (VirtualMemory code_space)
Definition at line 645 of file wasm-code-manager.cc.
                                                     {
  DCHECK(owned_code_space_.empty());
  DCHECK(free_code_space_.IsEmpty());
  if (code_space.IsReserved()) {
    free_code_space_.Merge(code_space.region());
    owned_code_space_.emplace_back(std::move(code_space));
    async_counters_->wasm_module_num_code_spaces()->AddSample(1);
  } else {
    async_counters_->wasm_module_num_code_spaces()->AddSample(0);
  }
}
References async_counters_, v8::internal::DCHECK(), free_code_space_, v8::internal::wasm::DisjointAllocationPool::IsEmpty(), v8::internal::VirtualMemory::IsReserved(), v8::internal::wasm::DisjointAllocationPool::Merge(), owned_code_space_, and v8::internal::VirtualMemory::region().
Referenced by v8::internal::wasm::NativeModule::NativeModule().
InitializeCodeRange()
void v8::internal::wasm::WasmCodeAllocator::InitializeCodeRange (NativeModule * native_module, base::AddressRegion region)
Definition at line 804 of file wasm-code-manager.cc.
                                                                      {
#if defined(V8_OS_WIN64)
  // On some platforms, specifically Win64, we need to reserve some pages at
  // the beginning of an executable space.
  // See src/heap/spaces.cc, MemoryAllocator::InitializeCodePageAllocator() and
  // https://cs.chromium.org/chromium/src/components/crash/content/app/crashpad_win.cc?rcl=fd680447881449fba2edcf0589320e7253719212&l=204
  // for details.
  if (WasmCodeManager::CanRegisterUnwindInfoForNonABICompliantCodeRange()) {
    size_t size = Heap::GetCodeRangeReservedAreaSize();
    DCHECK_LT(0, size);
    base::Vector<uint8_t> padding =
        AllocateForCodeInRegion(native_module, size, region);
    CHECK_EQ(reinterpret_cast<Address>(padding.begin()), region.begin());
    win64_unwindinfo::RegisterNonABICompliantCodeRange(
        reinterpret_cast<void*>(region.begin()), region.size());
  }
#endif // V8_OS_WIN64
}
References AllocateForCodeInRegion(), v8::base::AddressRegion::begin(), v8::base::Vector< T >::begin(), v8::internal::win64_unwindinfo::CanRegisterUnwindInfoForNonABICompliantCodeRange(), CHECK_EQ, DCHECK_LT, v8::internal::Heap::GetCodeRangeReservedAreaSize(), v8::internal::win64_unwindinfo::RegisterNonABICompliantCodeRange(), v8::base::AddressRegion::size(), and size().
Referenced by AllocateForCodeInRegion(), and v8::internal::wasm::NativeModule::NativeModule().
Member Data Documentation
async_counters_
std::shared_ptr<Counters> v8::internal::wasm::WasmCodeAllocator::async_counters_ [private]
Definition at line 600 of file wasm-code-manager.h.
Referenced by AllocateForCodeInRegion(), counters(), and Init().
committed_code_space_
std::atomic<size_t> v8::internal::wasm::WasmCodeAllocator::committed_code_space_ {0} [private]
Definition at line 596 of file wasm-code-manager.h.
Referenced by AllocateForCodeInRegion(), committed_code_space(), and FreeCode().
free_code_space_
DisjointAllocationPool v8::internal::wasm::WasmCodeAllocator::free_code_space_ [private]
Definition at line 586 of file wasm-code-manager.h.
Referenced by AllocateForCodeInRegion(), and Init().
freed_code_size_
std::atomic<size_t> v8::internal::wasm::WasmCodeAllocator::freed_code_size_ {0} [private]
Definition at line 598 of file wasm-code-manager.h.
Referenced by FreeCode(), and freed_code_size().
freed_code_space_
DisjointAllocationPool v8::internal::wasm::WasmCodeAllocator::freed_code_space_ [private]
Definition at line 590 of file wasm-code-manager.h.
Referenced by FreeCode().
generated_code_size_
std::atomic<size_t> v8::internal::wasm::WasmCodeAllocator::generated_code_size_ {0} [private]
Definition at line 597 of file wasm-code-manager.h.
Referenced by AllocateForCodeInRegion(), and generated_code_size().
owned_code_space_
std::vector<VirtualMemory> v8::internal::wasm::WasmCodeAllocator::owned_code_space_ [private]
Definition at line 591 of file wasm-code-manager.h.
Referenced by AllocateForCodeInRegion(), FreeCode(), GetNumCodeSpaces(), Init(), WasmCodeAllocator(), and ~WasmCodeAllocator().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-code-manager.h
/mnt/V8SourceCode/src/wasm/wasm-code-manager.cc