v8::internal::NativeFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
void Iterate (RootVisitor *v) const override
Protected Member Functions
NativeFrame (StackFrameIteratorBase *iterator)
Private Member Functions
void ComputeCallerState (State *state) const override
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 832 of file frames.h.
Constructor & Destructor Documentation
NativeFrame()
v8::internal::NativeFrame::NativeFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 127 of file frames-inl.h.
    : TypedFrame(iterator) {}
Member Function Documentation
ComputeCallerState()
void v8::internal::NativeFrame::ComputeCallerState (State * state) const [override], [private], [virtual]
Reimplemented from v8::internal::CommonFrame.
Definition at line 1080 of file frames.cc.
                                                       {
  state->sp = caller_sp();
  state->fp = Memory<Address>(fp() + CommonFrameConstants::kCallerFPOffset);
  state->pc_address = ResolveReturnAddressLocation(
      reinterpret_cast<Address*>(fp() + CommonFrameConstants::kCallerPCOffset));
  state->callee_pc = kNullAddress;
  state->constant_pool_address = nullptr;
}
References v8::internal::StackFrame::State::callee_pc, v8::internal::StackFrame::caller_sp(), v8::internal::StackFrame::State::constant_pool_address, v8::internal::StackFrame::State::fp, v8::internal::StackFrame::fp(), v8::internal::CommonFrameConstants::kCallerFPOffset, v8::internal::CommonFrameConstants::kCallerPCOffset, v8::internal::kNullAddress, v8::internal::StackFrame::State::pc_address, v8::internal::StackFrame::ResolveReturnAddressLocation(), and v8::internal::StackFrame::State::sp.
Iterate()
void v8::internal::NativeFrame::Iterate (RootVisitor * v) const [inline], [override], [virtual]
Reimplemented from v8::internal::TypedFrame.
Definition at line 837 of file frames.h.
{}
type()
Type v8::internal::NativeFrame::type () const [inline], [override], [virtual]
Implements v8::internal::StackFrame.
Definition at line 834 of file frames.h.
{ return NATIVE; }
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 845 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc