v8::internal::torque::Declarable Class Reference
#include <declarable.h>
Public Types
enum Kind {
kNamespace
, kTorqueMacro
, kExternMacro
, kMethod
,
kBuiltin
, kRuntimeFunction
, kIntrinsic
, kGenericCallable
,
kGenericType
, kTypeAlias
, kExternConstant
, kNamespaceConstant
 }
Public Member Functions
virtual ~Declarable ()=default
Kind kind () const
bool IsNamespace () const
bool IsMacro () const
bool IsTorqueMacro () const
bool IsMethod () const
bool IsExternMacro () const
bool IsIntrinsic () const
bool IsBuiltin () const
bool IsRuntimeFunction () const
bool IsGenericCallable () const
bool IsGenericType () const
bool IsTypeAlias () const
bool IsExternConstant () const
bool IsNamespaceConstant () const
bool IsValue () const
bool IsScope () const
bool IsCallable () const
virtual const char * type_name () const
Scope * ParentScope () const
SourcePosition Position () const
void SetPosition (const SourcePosition &position)
SourcePosition IdentifierPosition () const
void SetIdentifierPosition (const SourcePosition &position)
bool IsUserDefined () const
void SetIsUserDefined (bool is_user_defined)
Protected Member Functions
Declarable (Kind kind)
Private Attributes
const Kind kind_
Scope *const parent_scope_ = CurrentScope::Get()
SourcePosition position_ = CurrentSourcePosition::Get()
SourcePosition identifier_position_ = SourcePosition::Invalid()
bool is_user_defined_ = true
Detailed Description
Definition at line 54 of file declarable.h.
Member Enumeration Documentation
Kind
enum v8::internal::torque::Declarable::Kind
Enumerator
kNamespace
kTorqueMacro
kExternMacro
kMethod
kBuiltin
kRuntimeFunction
kIntrinsic
kGenericCallable
kGenericType
kTypeAlias
kExternConstant
kNamespaceConstant
Definition at line 57 of file declarable.h.
            {
    kNamespace,
    kTorqueMacro,
    kExternMacro,
    kMethod,
    kBuiltin,
    kRuntimeFunction,
    kIntrinsic,
    kGenericCallable,
    kGenericType,
    kTypeAlias,
    kExternConstant,
    kNamespaceConstant
  };
Constructor & Destructor Documentation
 Declarable()
virtual v8::internal::torque::Declarable::~Declarable () [virtual], [default]
Declarable()
v8::internal::torque::Declarable::Declarable (Kind kind) [inline], [explicit], [protected]
Definition at line 117 of file declarable.h.
: kind_(kind) {}
Member Function Documentation
IdentifierPosition()
SourcePosition v8::internal::torque::Declarable::IdentifierPosition () const [inline]
Definition at line 103 of file declarable.h.
                                            {
    return identifier_position_.source.IsValid() ? identifier_position_
                                                 : position_;
  }
References identifier_position_, v8::internal::torque::SourceId::IsValid(), position_, and v8::internal::torque::SourcePosition::source.
Referenced by v8::internal::torque::KytheData::AddFunctionDefinition(), v8::internal::torque::KytheData::AddTypeDefinition(), v8::internal::torque::ReportAllUnusedMacros(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::DeclarationVisitor::Visit().
IsBuiltin()
bool v8::internal::torque::Declarable::IsBuiltin () const [inline]
Definition at line 78 of file declarable.h.
{ return kind() == kBuiltin; }
References kBuiltin, and kind().
Referenced by IsCallable(), and v8::internal::torque::ImplementationVisitor::Visit().
IsCallable()
bool v8::internal::torque::Declarable::IsCallable () const [inline]
Definition at line 87 of file declarable.h.
                          {
    return IsMacro() || IsBuiltin() || IsRuntimeFunction() || IsIntrinsic() ||
           IsMethod();
  }
References IsBuiltin(), IsIntrinsic(), IsMacro(), IsMethod(), and IsRuntimeFunction().
Referenced by IsScope().
IsExternConstant()
bool v8::internal::torque::Declarable::IsExternConstant () const [inline]
Definition at line 83 of file declarable.h.
{ return kind() == kExternConstant; }
References kExternConstant, and kind().
Referenced by v8::internal::torque::KytheData::AddConstantDefinition(), v8::internal::torque::KytheData::AddConstantUse(), and IsValue().
IsExternMacro()
bool v8::internal::torque::Declarable::IsExternMacro () const [inline]
Definition at line 76 of file declarable.h.
{ return kind() == kExternMacro; }
References kExternMacro, and kind().
Referenced by IsMacro().
IsGenericCallable()
bool v8::internal::torque::Declarable::IsGenericCallable () const [inline]
Definition at line 80 of file declarable.h.
{ return kind() == kGenericCallable; }
References kGenericCallable, and kind().
IsGenericType()
bool v8::internal::torque::Declarable::IsGenericType () const [inline]
Definition at line 81 of file declarable.h.
{ return kind() == kGenericType; }
References kGenericType, and kind().
IsIntrinsic()
bool v8::internal::torque::Declarable::IsIntrinsic () const [inline]
Definition at line 77 of file declarable.h.
{ return kind() == kIntrinsic; }
References kind(), and kIntrinsic.
Referenced by IsCallable().
IsMacro()
bool v8::internal::torque::Declarable::IsMacro () const [inline]
Definition at line 73 of file declarable.h.
{ return IsTorqueMacro() || IsExternMacro(); }
References IsExternMacro(), and IsTorqueMacro().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCall(), IsCallable(), and v8::internal::torque::ImplementationVisitor::Visit().
IsMethod()
bool v8::internal::torque::Declarable::IsMethod () const [inline]
Definition at line 75 of file declarable.h.
{ return kind() == kMethod; }
References kind(), and kMethod.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::InlineMacro(), IsCallable(), and IsTorqueMacro().
IsNamespace()
bool v8::internal::torque::Declarable::IsNamespace () const [inline]
Definition at line 72 of file declarable.h.
{ return kind() == kNamespace; }
References kind(), and kNamespace.
Referenced by IsScope().
IsNamespaceConstant()
bool v8::internal::torque::Declarable::IsNamespaceConstant () const [inline]
Definition at line 84 of file declarable.h.
{ return kind() == kNamespaceConstant; }
References kind(), and kNamespaceConstant.
Referenced by v8::internal::torque::KytheData::AddConstantDefinition(), v8::internal::torque::KytheData::AddConstantUse(), and IsValue().
IsRuntimeFunction()
bool v8::internal::torque::Declarable::IsRuntimeFunction () const [inline]
Definition at line 79 of file declarable.h.
{ return kind() == kRuntimeFunction; }
References kind(), and kRuntimeFunction.
Referenced by IsCallable().
IsScope()
bool v8::internal::torque::Declarable::IsScope () const [inline]
Definition at line 86 of file declarable.h.
{ return IsNamespace() || IsCallable(); }
References IsCallable(), and IsNamespace().
IsTorqueMacro()
bool v8::internal::torque::Declarable::IsTorqueMacro () const [inline]
Definition at line 74 of file declarable.h.
{ return kind() == kTorqueMacro || IsMethod(); }
References IsMethod(), kind(), and kTorqueMacro.
Referenced by IsMacro(), and v8::internal::torque::ReportAllUnusedMacros().
IsTypeAlias()
bool v8::internal::torque::Declarable::IsTypeAlias () const [inline]
Definition at line 82 of file declarable.h.
{ return kind() == kTypeAlias; }
References kind(), and kTypeAlias.
IsUserDefined()
bool v8::internal::torque::Declarable::IsUserDefined () const [inline]
Definition at line 111 of file declarable.h.
{ return is_user_defined_; }
References is_user_defined_.
IsValue()
bool v8::internal::torque::Declarable::IsValue () const [inline]
Definition at line 85 of file declarable.h.
{ return IsExternConstant() || IsNamespaceConstant(); }
References IsExternConstant(), and IsNamespaceConstant().
kind()
Kind v8::internal::torque::Declarable::kind () const [inline]
Definition at line 71 of file declarable.h.
{ return kind_; }
References kind_.
Referenced by IsBuiltin(), IsExternConstant(), IsExternMacro(), IsGenericCallable(), IsGenericType(), IsIntrinsic(), IsMethod(), IsNamespace(), IsNamespaceConstant(), IsRuntimeFunction(), IsTorqueMacro(), IsTypeAlias(), and v8::internal::torque::ImplementationVisitor::Visit().
ParentScope()
Scope* v8::internal::torque::Declarable::ParentScope () const [inline]
Definition at line 92 of file declarable.h.
{ return parent_scope_; }
References parent_scope_.
Referenced by v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::Constraints(), v8::internal::torque::CurrentNamespace(), v8::internal::torque::ClassType::Finalize(), v8::internal::torque::TypeOracle::GetGenericTypeInstance(), v8::internal::torque::GenericCallable::InferSpecializationTypes(), v8::internal::torque::Scope::Lookup(), v8::internal::torque::MessageBuilder::MessageBuilder(), v8::internal::torque::TypeAlias::Resolve(), v8::internal::torque::SpecializationRequester::SpecializationRequester(), and v8::internal::torque::ImplementationVisitor::Visit().
Position()
SourcePosition v8::internal::torque::Declarable::Position () const [inline]
Definition at line 96 of file declarable.h.
{ return position_; }
References position_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::GenerateExportedMacrosAssembler(), v8::internal::torque::ClassType::GenerateSliceAccessor(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleDocumentSymbolRequest(), v8::internal::torque::TypeAlias::Resolve(), and v8::internal::torque::ImplementationVisitor::Visit().
SetIdentifierPosition()
void v8::internal::torque::Declarable::SetIdentifierPosition (const SourcePosition & position) [inline]
Definition at line 107 of file declarable.h.
                                                             {
    identifier_position_ = position;
  }
References identifier_position_.
Referenced by v8::internal::torque::DeclareMethods(), v8::internal::torque::PredeclarationVisitor::Predeclare(), and v8::internal::torque::DeclarationVisitor::Visit().
SetIsUserDefined()
void v8::internal::torque::Declarable::SetIsUserDefined (bool is_user_defined) [inline]
Definition at line 112 of file declarable.h.
                                              {
    is_user_defined_ = is_user_defined;
  }
References is_user_defined_.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::DeclarationVisitor::DeclareSpecializedTypes(), and v8::internal::torque::TorqueMacro::TorqueMacro().
SetPosition()
void v8::internal::torque::Declarable::SetPosition (const SourcePosition & position) [inline]
Definition at line 97 of file declarable.h.
{ position_ = position; }
References position_.
Referenced by v8::internal::torque::DeclareMethods(), v8::internal::torque::PredeclarationVisitor::Predeclare(), and v8::internal::torque::DeclarationVisitor::Visit().
type_name()
virtual const char* v8::internal::torque::Declarable::type_name () const [inline], [virtual]
Definition at line 91 of file declarable.h.
{ return "<<unknown>>"; }
Referenced by v8::internal::torque::KytheData::AddTypeDefinition().
Member Data Documentation
identifier_position_
SourcePosition v8::internal::torque::Declarable::identifier_position_ = SourcePosition::Invalid() [private]
Definition at line 123 of file declarable.h.
Referenced by IdentifierPosition(), and SetIdentifierPosition().
is_user_defined_
bool v8::internal::torque::Declarable::is_user_defined_ = true [private]
Definition at line 124 of file declarable.h.
Referenced by IsUserDefined(), and SetIsUserDefined().
kind_
const Kind v8::internal::torque::Declarable::kind_ [private]
Definition at line 120 of file declarable.h.
Referenced by kind().
parent_scope_
Scope* const v8::internal::torque::Declarable::parent_scope_ = CurrentScope::Get() [private]
Definition at line 121 of file declarable.h.
Referenced by ParentScope().
position_
SourcePosition v8::internal::torque::Declarable::position_ = CurrentSourcePosition::Get() [private]
Definition at line 122 of file declarable.h.
Referenced by IdentifierPosition(), Position(), and SetPosition().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/declarable.h