v8::internal::interpreter::BytecodeHandlerReducer< Next > Class Template Reference
Public Member Functions
~BytecodeHandlerReducer ()
void InitializeParameters (V< Object > accumulator, V< BytecodeArray > bytecode_array, V< WordPtr > bytecode_offset, V< WordPtr > dispatch_table)
V< Object > GetAccumulator ()
void SetAccumulator (V< Object > value)
V< Context > GetContext ()
void Dispatch ()
void DispatchToBytecodeWithOptionalStarLookahead (V< WordPtr > target_bytecode)
void DispatchToBytecode (V< WordPtr > target_bytecode, V< WordPtr > new_bytecode_offset)
void DispatchToBytecodeHandlerEntry (V< WordPtr > handler_entry, V< WordPtr > bytecode_offset)
void StarDispatchLookahead (V< WordPtr > target_bytecode)
template<typename... Args>
void TailCallBytecodeDispatch (const CallInterfaceDescriptor &descriptor, V< WordPtr > target, Args... args)
V< WordPtr > Advance (ConstOrV< WordPtr > delta)
V< Object > LoadRegister (Register reg)
V< WordPtr > GetInterpretedFramePointer ()
V< WordPtr > BytecodeOffset ()
V< WordPtr > ReloadBytecodeOffset ()
V< Word32 > LoadFromBytecodeArrayAt (MemoryRepresentation loaded_rep, V< WordPtr > bytecode_offset, int additional_offset=0)
V< WordPtr > LoadBytecode (V< WordPtr > bytecode_offset)
V< WordPtr > LoadAndUntagRegister (Register reg)
V< WordPtr > DispatchTablePointer ()
V< BytecodeArray > BytecodeArrayTaggedPointer ()
V< Word32 > BytecodeOperandIdxInt32 (int operand_index)
V< Word32 > BytecodeUnsignedOperand (int operand_index, OperandSize operand_size)
V< Word32 > BytecodeOperand (int operand_index, OperandSize operand_size)
int OperandOffset (int operand_index) const
Private Types
template<typename T >
using Var = compiler::turboshaft::Var< T, assembler_t >
Private Member Functions
Bytecode bytecode () const
OperandScale operand_scale () const
int CurrentBytecodeSize () const
void TrackRegisterUse (ImplicitRegisterUse use)
Private Attributes
Isolate * isolate_ = __ data() -> isolate()
ZoneWithName< compiler::kGraphZoneName > & graph_zone_
BytecodeHandlerData & data_ = *__ data() -> bytecode_handler_data()
OpIndex bytecode_offset_parameter_
OpIndex dispatch_table_parameter_
Var< Object > accumulator_ {this}
Var< WordPtr > interpreted_frame_pointer_ {this}
Var< WordPtr > bytecode_offset_ {this}
Var< Object > bytecode_array_ {this}
Var< WordPtr > dispatch_table_ {this}
Detailed Description
template<typename Next>
class v8::internal::interpreter::BytecodeHandlerReducer< Next >
Definition at line 42 of file interpreter-generator-tsa.cc.
Member Typedef Documentation
Var
template<typename Next >
template<typename T >
using v8::internal::interpreter::BytecodeHandlerReducer< Next >::Var = compiler::turboshaft::Var<T, assembler_t> [private]
Definition at line 286 of file interpreter-generator-tsa.cc.
Constructor & Destructor Documentation
 BytecodeHandlerReducer()
template<typename Next >
v8::internal::interpreter::BytecodeHandlerReducer< Next >::~BytecodeHandlerReducer () [inline]
Definition at line 46 of file interpreter-generator-tsa.cc.
                            {
    // If the following check fails the handler does not use the
    // accumulator in the way described in the bytecode definitions in
    // bytecodes.h.
    DCHECK_EQ(data_.implicit_register_use,
              Bytecodes::GetImplicitRegisterUse(data_.bytecode));
  }
References DCHECK_EQ, and v8::internal::interpreter::Bytecodes::GetImplicitRegisterUse().
Member Function Documentation
Advance()
template<typename Next >
V<WordPtr> v8::internal::interpreter::BytecodeHandlerReducer< Next >::Advance (ConstOrV< WordPtr > delta) [inline]
Definition at line 134 of file interpreter-generator-tsa.cc.
                                              {
    V<WordPtr> next_offset = __ WordPtrAdd(BytecodeOffset(), delta);
    bytecode_offset_ = next_offset;
    return next_offset;
  }
References __.
bytecode()
template<typename Next >
Bytecode v8::internal::interpreter::BytecodeHandlerReducer< Next >::bytecode () const [inline], [private]
Definition at line 267 of file interpreter-generator-tsa.cc.
{ return data_.bytecode; }
BytecodeArrayTaggedPointer()
template<typename Next >
V<BytecodeArray> v8::internal::interpreter::BytecodeHandlerReducer< Next >::BytecodeArrayTaggedPointer () [inline]
Definition at line 216 of file interpreter-generator-tsa.cc.
                                                {
    // Force a re-load of the bytecode array after every call in case the
    // debugger has been activated.
    if (!data_.bytecode_array_valid) {
      bytecode_array_ = LoadRegister(Register::bytecode_array());
      data_.bytecode_array_valid = true;
    }
    return V<BytecodeArray>::Cast(bytecode_array_);
  }
References v8::internal::interpreter::Register::bytecode_array(), and v8::internal::compiler::turboshaft::V< T >::Cast().
BytecodeOffset()
template<typename Next >
V<WordPtr> v8::internal::interpreter::BytecodeHandlerReducer< Next >::BytecodeOffset () [inline]
Definition at line 157 of file interpreter-generator-tsa.cc.
                              {
    if (Bytecodes::MakesCallAlongCriticalPath(data_.bytecode) &&
        data_.made_call && (bytecode_offset_ == bytecode_offset_parameter_)) {
      bytecode_offset_ = ReloadBytecodeOffset();
    }
    return bytecode_offset_;
  }
References v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath().
BytecodeOperand()
template<typename Next >
V<Word32> v8::internal::interpreter::BytecodeHandlerReducer< Next >::BytecodeOperand (int operand_index, OperandSize operand_size) [inline]
Definition at line 239 of file interpreter-generator-tsa.cc.
                                                                         {
    DCHECK_LT(operand_index, Bytecodes::NumberOfOperands(bytecode()));
    DCHECK_EQ(operand_size, Bytecodes::GetOperandSize(bytecode(), operand_index,
                                                      operand_scale()));
    MemoryRepresentation loaded_rep;
    switch (operand_size) {
      case OperandSize::kByte:
        loaded_rep = MemoryRepresentation::Uint8();
        break;
      case OperandSize::kShort:
        loaded_rep = MemoryRepresentation::Uint16();
        break;
      case OperandSize::kQuad:
        loaded_rep = MemoryRepresentation::Uint32();
        break;
      case OperandSize::kNone:
        UNREACHABLE();
    }
    return LoadFromBytecodeArrayAt(loaded_rep, BytecodeOffset(),
                                   OperandOffset(operand_index));
  }
References DCHECK_EQ, DCHECK_LT, v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::interpreter::kByte, v8::internal::interpreter::kNone, v8::internal::interpreter::kQuad, v8::internal::interpreter::kShort, v8::internal::interpreter::Bytecodes::NumberOfOperands(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), and v8::internal::UNREACHABLE().
BytecodeOperandIdxInt32()
template<typename Next >
V<Word32> v8::internal::interpreter::BytecodeHandlerReducer< Next >::BytecodeOperandIdxInt32 (int operand_index) [inline]
Definition at line 226 of file interpreter-generator-tsa.cc.
                                                       {
    DCHECK_EQ(OperandType::kIdx,
              Bytecodes::GetOperandType(data_.bytecode, operand_index));
    OperandSize operand_size = Bytecodes::GetOperandSize(
        data_.bytecode, operand_index, operand_scale());
    return BytecodeUnsignedOperand(operand_index, operand_size);
  }
References DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandSize(), and v8::internal::interpreter::Bytecodes::GetOperandType().
BytecodeUnsignedOperand()
template<typename Next >
V<Word32> v8::internal::interpreter::BytecodeHandlerReducer< Next >::BytecodeUnsignedOperand (int operand_index, OperandSize operand_size) [inline]
Definition at line 234 of file interpreter-generator-tsa.cc.
                                                              {
    return BytecodeOperand(operand_index, operand_size);
  }
CurrentBytecodeSize()
template<typename Next >
int v8::internal::interpreter::BytecodeHandlerReducer< Next >::CurrentBytecodeSize () const [inline], [private]
Definition at line 270 of file interpreter-generator-tsa.cc.
                                  {
    return Bytecodes::Size(data_.bytecode, data_.operand_scale);
  }
References v8::internal::interpreter::Bytecodes::Size().
Dispatch()
template<typename Next >
void v8::internal::interpreter::BytecodeHandlerReducer< Next >::Dispatch () [inline]
Definition at line 80 of file interpreter-generator-tsa.cc.
                  {
    __ CodeComment("========= Dispatch");
    DCHECK_IMPLIES(Bytecodes::MakesCallAlongCriticalPath(data_.bytecode),
                   data_.made_call);
    V<WordPtr> target_offset = Advance(CurrentBytecodeSize());
    V<WordPtr> target_bytecode = LoadBytecode(target_offset);
    DispatchToBytecodeWithOptionalStarLookahead(target_bytecode);
  }
References __, DCHECK_IMPLIES, and v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath().
DispatchTablePointer()
template<typename Next >
V<WordPtr> v8::internal::interpreter::BytecodeHandlerReducer< Next >::DispatchTablePointer () [inline]
Definition at line 207 of file interpreter-generator-tsa.cc.
                                    {
    if (Bytecodes::MakesCallAlongCriticalPath(data_.bytecode) &&
        data_.made_call && (dispatch_table_ == dispatch_table_parameter_)) {
      dispatch_table_ = __ ExternalConstant(
          ExternalReference::interpreter_dispatch_table_address(isolate_));
    }
    return dispatch_table_;
  }
References __, and v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath().
DispatchToBytecode()
template<typename Next >
void v8::internal::interpreter::BytecodeHandlerReducer< Next >::DispatchToBytecode (V< WordPtr > target_bytecode, V< WordPtr > new_bytecode_offset) [inline]
Definition at line 96 of file interpreter-generator-tsa.cc.
                                                          {
#ifdef V8_IGNITION_DISPATCH_COUNTING
    TraceBytecodeDispatch(target_bytecode);
#endif
    static_assert(kSystemPointerSizeLog2 ==
                  MemoryRepresentation::UintPtr().SizeInBytesLog2());
    V<WordPtr> target_code_entry =
        __ LoadOffHeap(DispatchTablePointer(), target_bytecode, 0,
                       MemoryRepresentation::UintPtr());
    DispatchToBytecodeHandlerEntry(target_code_entry, new_bytecode_offset);
  }
References __, v8::internal::kSystemPointerSizeLog2, and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
DispatchToBytecodeHandlerEntry()
template<typename Next >
void v8::internal::interpreter::BytecodeHandlerReducer< Next >::DispatchToBytecodeHandlerEntry (V< WordPtr > handler_entry, V< WordPtr > bytecode_offset) [inline]
Definition at line 111 of file interpreter-generator-tsa.cc.
                                                                  {
    TailCallBytecodeDispatch(
        InterpreterDispatchDescriptor{}, handler_entry, accumulator_.Get(),
        bytecode_offset, BytecodeArrayTaggedPointer(), DispatchTablePointer());
  }
DispatchToBytecodeWithOptionalStarLookahead()
template<typename Next >
void v8::internal::interpreter::BytecodeHandlerReducer< Next >::DispatchToBytecodeWithOptionalStarLookahead (V< WordPtr > target_bytecode) [inline]
Definition at line 89 of file interpreter-generator-tsa.cc.
                                                                               {
    if (Bytecodes::IsStarLookahead(data_.bytecode, operand_scale())) {
      StarDispatchLookahead(target_bytecode);
    }
    DispatchToBytecode(target_bytecode, BytecodeOffset());
  }
References v8::internal::interpreter::Bytecodes::IsStarLookahead().
GetAccumulator()
template<typename Next >
V<Object> v8::internal::interpreter::BytecodeHandlerReducer< Next >::GetAccumulator () [inline]
Definition at line 64 of file interpreter-generator-tsa.cc.
                             {
    DCHECK(Bytecodes::ReadsAccumulator(data_.bytecode));
    TrackRegisterUse(ImplicitRegisterUse::kReadAccumulator);
    return accumulator_;
  }
References v8::internal::DCHECK(), v8::internal::interpreter::kReadAccumulator, and v8::internal::interpreter::Bytecodes::ReadsAccumulator().
GetContext()
template<typename Next >
V<Context> v8::internal::interpreter::BytecodeHandlerReducer< Next >::GetContext () [inline]
Definition at line 76 of file interpreter-generator-tsa.cc.
                          {
    return V<Context>::Cast(LoadRegister(Register::current_context()));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), and v8::internal::interpreter::Register::current_context().
GetInterpretedFramePointer()
template<typename Next >
V<WordPtr> v8::internal::interpreter::BytecodeHandlerReducer< Next >::GetInterpretedFramePointer () [inline]
Definition at line 146 of file interpreter-generator-tsa.cc.
                                          {
    if (!interpreted_frame_pointer_.Get().valid()) {
      interpreted_frame_pointer_ = __ ParentFramePointer();
    } else if (Bytecodes::MakesCallAlongCriticalPath(data_.bytecode) &&
               data_.made_call && data_.reloaded_frame_ptr) {
      interpreted_frame_pointer_ = __ ParentFramePointer();
      data_.reloaded_frame_ptr = true;
    }
    return interpreted_frame_pointer_;
  }
References __, and v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath().
InitializeParameters()
template<typename Next >
void v8::internal::interpreter::BytecodeHandlerReducer< Next >::InitializeParameters (V< Object > accumulator, V< BytecodeArray > bytecode_array, V< WordPtr > bytecode_offset, V< WordPtr > dispatch_table) [inline]
Definition at line 54 of file interpreter-generator-tsa.cc.
                                                       {
    accumulator_ = accumulator;
    bytecode_array_ = bytecode_array;
    bytecode_offset_ = bytecode_offset;
    dispatch_table_ = dispatch_table;
  }
LoadAndUntagRegister()
template<typename Next >
V<WordPtr> v8::internal::interpreter::BytecodeHandlerReducer< Next >::LoadAndUntagRegister (Register reg) [inline]
Definition at line 191 of file interpreter-generator-tsa.cc.
                                                {
    V<WordPtr> base = GetInterpretedFramePointer();
    int index = reg.ToOperand() * kSystemPointerSize;
    if (SmiValuesAre32Bits()) {
#if V8_TARGET_LITTLE_ENDIAN
      index += 4;
#endif
      return __ ChangeInt32ToIntPtr(
          __ LoadOffHeap(base, index, MemoryRepresentation::Int32()));
    } else {
      return __ ChangeInt32ToIntPtr(__ UntagSmi(
          __ LoadOffHeap(base, index, MemoryRepresentation::TaggedSigned())));
    }
  }
References __, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ChangeInt32ToIntPtr(), v8::internal::index, v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::kSystemPointerSize, v8::internal::SmiValuesAre32Bits(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedSigned(), and v8::internal::interpreter::Register::ToOperand().
LoadBytecode()
template<typename Next >
V<WordPtr> v8::internal::interpreter::BytecodeHandlerReducer< Next >::LoadBytecode (V< WordPtr > bytecode_offset) [inline]
Definition at line 184 of file interpreter-generator-tsa.cc.
                                                      {
    V<Word32> bytecode = __ Load(BytecodeArrayTaggedPointer(), bytecode_offset,
                                 LoadOp::Kind::TaggedBase(),
                                 MemoryRepresentation::Uint8(), kHeapObjectTag);
    return __ ChangeUint32ToUintPtr(bytecode);
  }
References __, v8::internal::kHeapObjectTag, v8::Load(), and v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8().
LoadFromBytecodeArrayAt()
template<typename Next >
V<Word32> v8::internal::interpreter::BytecodeHandlerReducer< Next >::LoadFromBytecodeArrayAt (MemoryRepresentation loaded_rep, V< WordPtr > bytecode_offset, int additional_offset = 0) [inline]
Definition at line 176 of file interpreter-generator-tsa.cc.
                                                               {
    return __ Load(BytecodeArrayTaggedPointer(), bytecode_offset,
                   LoadOp::Kind::TaggedBase(), loaded_rep,
                   additional_offset + kHeapObjectTag);
  }
References __, v8::internal::kHeapObjectTag, and v8::Load().
LoadRegister()
template<typename Next >
V<Object> v8::internal::interpreter::BytecodeHandlerReducer< Next >::LoadRegister (Register reg) [inline]
Definition at line 140 of file interpreter-generator-tsa.cc.
                                       {
    const int offset = reg.ToOperand() * kSystemPointerSize;
    return __ LoadOffHeap(GetInterpretedFramePointer(), offset,
                          MemoryRepresentation::AnyTagged());
  }
References __, v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::kSystemPointerSize, and v8::internal::interpreter::Register::ToOperand().
operand_scale()
template<typename Next >
OperandScale v8::internal::interpreter::BytecodeHandlerReducer< Next >::operand_scale () const [inline], [private]
Definition at line 268 of file interpreter-generator-tsa.cc.
{ return data_.operand_scale; }
OperandOffset()
template<typename Next >
int v8::internal::interpreter::BytecodeHandlerReducer< Next >::OperandOffset (int operand_index) const [inline]
Definition at line 261 of file interpreter-generator-tsa.cc.
                                             {
    return Bytecodes::GetOperandOffset(bytecode(), operand_index,
                                       operand_scale());
  }
References v8::internal::interpreter::Bytecodes::GetOperandOffset().
ReloadBytecodeOffset()
template<typename Next >
V<WordPtr> v8::internal::interpreter::BytecodeHandlerReducer< Next >::ReloadBytecodeOffset () [inline]
Definition at line 165 of file interpreter-generator-tsa.cc.
                                    {
    V<WordPtr> offset = LoadAndUntagRegister(Register::bytecode_offset());
    if (operand_scale() == OperandScale::kSingle) {
      return offset;
    }
    // Add one to the offset such that it points to the actual bytecode rather
    // than the Wide / ExtraWide prefix bytecode.
    return __ WordPtrAdd(offset, 1);
  }
References __, and v8::internal::interpreter::Register::bytecode_offset().
SetAccumulator()
template<typename Next >
void v8::internal::interpreter::BytecodeHandlerReducer< Next >::SetAccumulator (V< Object > value) [inline]
Definition at line 70 of file interpreter-generator-tsa.cc.
                                       {
    DCHECK(Bytecodes::WritesAccumulator(data_.bytecode));
    TrackRegisterUse(ImplicitRegisterUse::kWriteAccumulator);
    accumulator_ = value;
  }
References v8::internal::DCHECK(), v8::internal::interpreter::kWriteAccumulator, v8::internal::value, and v8::internal::interpreter::Bytecodes::WritesAccumulator().
StarDispatchLookahead()
template<typename Next >
void v8::internal::interpreter::BytecodeHandlerReducer< Next >::StarDispatchLookahead (V< WordPtr > target_bytecode) [inline]
Definition at line 118 of file interpreter-generator-tsa.cc.
{ UNIMPLEMENTED(); }
References v8::internal::UNIMPLEMENTED().
TailCallBytecodeDispatch()
template<typename Next >
template<typename... Args>
void v8::internal::interpreter::BytecodeHandlerReducer< Next >::TailCallBytecodeDispatch (const CallInterfaceDescriptor & descriptor, V< WordPtr > target, Args... args) [inline]
Definition at line 121 of file interpreter-generator-tsa.cc.
                                                                 {
    DCHECK_EQ(descriptor.GetParameterCount(), sizeof...(Args));
    auto call_descriptor = compiler::Linkage::GetBytecodeDispatchCallDescriptor(
        graph_zone_, descriptor, descriptor.GetStackParameterCount());
    auto ts_call_descriptor =
        TSCallDescriptor::Create(call_descriptor, compiler::CanThrow::kNo,
                                 compiler::LazyDeoptOnThrow::kNo, graph_zone_);
    std::initializer_list<const OpIndex> arguments{args...};
    __ TailCall(target, base::VectorOf(arguments), ts_call_descriptor);
  }
References __, v8::base::args, v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), DCHECK_EQ, v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), v8::internal::CallInterfaceDescriptor::GetParameterCount(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::kNo, and v8::base::VectorOf().
TrackRegisterUse()
template<typename Next >
void v8::internal::interpreter::BytecodeHandlerReducer< Next >::TrackRegisterUse (ImplicitRegisterUse use) [inline], [private]
Definition at line 274 of file interpreter-generator-tsa.cc.
                                                 {
    data_.implicit_register_use = data_.implicit_register_use | use;
  }
References use().
Member Data Documentation
accumulator_
template<typename Next >
Var<Object> v8::internal::interpreter::BytecodeHandlerReducer< Next >::accumulator_ {this} [private]
Definition at line 287 of file interpreter-generator-tsa.cc.
bytecode_array_
template<typename Next >
Var<Object> v8::internal::interpreter::BytecodeHandlerReducer< Next >::bytecode_array_ {this} [private]
Definition at line 290 of file interpreter-generator-tsa.cc.
bytecode_offset_
template<typename Next >
Var<WordPtr> v8::internal::interpreter::BytecodeHandlerReducer< Next >::bytecode_offset_ {this} [private]
Definition at line 289 of file interpreter-generator-tsa.cc.
bytecode_offset_parameter_
template<typename Next >
OpIndex v8::internal::interpreter::BytecodeHandlerReducer< Next >::bytecode_offset_parameter_ [private]
Definition at line 283 of file interpreter-generator-tsa.cc.
data_
template<typename Next >
BytecodeHandlerData& v8::internal::interpreter::BytecodeHandlerReducer< Next >::data_ = *__ data() -> bytecode_handler_data() [private]
Definition at line 281 of file interpreter-generator-tsa.cc.
dispatch_table_
template<typename Next >
Var<WordPtr> v8::internal::interpreter::BytecodeHandlerReducer< Next >::dispatch_table_ {this} [private]
Definition at line 291 of file interpreter-generator-tsa.cc.
dispatch_table_parameter_
template<typename Next >
OpIndex v8::internal::interpreter::BytecodeHandlerReducer< Next >::dispatch_table_parameter_ [private]
Definition at line 284 of file interpreter-generator-tsa.cc.
graph_zone_
template<typename Next >
ZoneWithName<compiler::kGraphZoneName>& v8::internal::interpreter::BytecodeHandlerReducer< Next >::graph_zone_ [private]
Initial value:
=
      __ data() -> graph_zone()
Definition at line 279 of file interpreter-generator-tsa.cc.
interpreted_frame_pointer_
template<typename Next >
Var<WordPtr> v8::internal::interpreter::BytecodeHandlerReducer< Next >::interpreted_frame_pointer_ {this} [private]
Definition at line 288 of file interpreter-generator-tsa.cc.
isolate_
template<typename Next >
Isolate* v8::internal::interpreter::BytecodeHandlerReducer< Next >::isolate_ = __ data() -> isolate() [private]
Definition at line 278 of file interpreter-generator-tsa.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/interpreter-generator-tsa.cc