v8::internal::torque::PredeclarationVisitor Class Reference
#include <declaration-visitor.h>
Static Public Member Functions
static void Predeclare (Ast *ast)
static void ResolvePredeclarations ()
Static Private Member Functions
static void Predeclare (Declaration *decl)
static void Predeclare (NamespaceDeclaration *decl)
static void Predeclare (TypeDeclaration *decl)
static void Predeclare (StructDeclaration *decl)
static void Predeclare (GenericTypeDeclaration *generic_decl)
static void Predeclare (GenericCallableDeclaration *generic_decl)
Detailed Description
Definition at line 22 of file declaration-visitor.h.
Member Function Documentation
Predeclare() [1/7]
static void v8::internal::torque::PredeclarationVisitor::Predeclare (Ast * ast) [inline], [static]
Definition at line 24 of file declaration-visitor.h.
                                   {
    CurrentScope::Scope current_namespace(GlobalContext::GetDefaultNamespace());
    for (Declaration* child : ast->declarations()) Predeclare(child);
  }
References v8::internal::torque::Ast::declarations(), and v8::internal::torque::GlobalContext::GetDefaultNamespace().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst(), and Predeclare().
Predeclare() [2/7]
void v8::internal::torque::PredeclarationVisitor::Predeclare (Declaration * decl) [static], [private]
Definition at line 27 of file declaration-visitor.cc.
                                                        {
  CurrentSourcePosition::Scope scope(decl->pos);
  switch (decl->kind) {
#define ENUM_ITEM(name) \
  case AstNode::Kind::k##name: \
    return Predeclare(name::cast(decl));
    AST_TYPE_DECLARATION_NODE_KIND_LIST(ENUM_ITEM)
#undef ENUM_ITEM
    case AstNode::Kind::kNamespaceDeclaration:
      return Predeclare(NamespaceDeclaration::cast(decl));
    case AstNode::Kind::kGenericCallableDeclaration:
      return Predeclare(GenericCallableDeclaration::cast(decl));
    case AstNode::Kind::kGenericTypeDeclaration:
      return Predeclare(GenericTypeDeclaration::cast(decl));
    default:
      // Only processes type declaration nodes, namespaces and generics.
      break;
  }
}
References AST_TYPE_DECLARATION_NODE_KIND_LIST, ENUM_ITEM, v8::internal::torque::AstNode::kind, v8::internal::torque::AstNode::pos, and Predeclare().
Predeclare() [3/7]
static void v8::internal::torque::PredeclarationVisitor::Predeclare (GenericCallableDeclaration * generic_decl) [inline], [static], [private]
Definition at line 58 of file declaration-visitor.h.
                                                                   {
    Declarations::DeclareGenericCallable(generic_decl->declaration->name->value,
                                         generic_decl);
  }
References v8::internal::torque::GenericCallableDeclaration::declaration, v8::internal::torque::Declarations::DeclareGenericCallable(), v8::internal::torque::CallableDeclaration::name, and v8::internal::torque::Identifier::value.
Predeclare() [4/7]
static void v8::internal::torque::PredeclarationVisitor::Predeclare (GenericTypeDeclaration * generic_decl) [inline], [static], [private]
Definition at line 54 of file declaration-visitor.h.
                                                               {
    Declarations::DeclareGenericType(generic_decl->declaration->name->value,
                                     generic_decl);
  }
References v8::internal::torque::GenericTypeDeclaration::declaration, v8::internal::torque::Declarations::DeclareGenericType(), v8::internal::torque::TypeDeclaration::name, and v8::internal::torque::Identifier::value.
Predeclare() [5/7]
static void v8::internal::torque::PredeclarationVisitor::Predeclare (NamespaceDeclaration * decl) [inline], [static], [private]
Definition at line 32 of file declaration-visitor.h.
                                                     {
    CurrentScope::Scope current_scope(GetOrCreateNamespace(decl->name));
    for (Declaration* child : decl->declarations) Predeclare(child);
  }
References v8::internal::torque::NamespaceDeclaration::declarations, v8::internal::torque::GetOrCreateNamespace(), v8::internal::torque::NamespaceDeclaration::name, and Predeclare().
Predeclare() [6/7]
static void v8::internal::torque::PredeclarationVisitor::Predeclare (StructDeclaration * decl) [inline], [static], [private]
Definition at line 45 of file declaration-visitor.h.
                                                  {
    TypeAlias* alias =
        Declarations::PredeclareTypeAlias(decl->name, decl, false);
    alias->SetPosition(decl->pos);
    alias->SetIdentifierPosition(decl->name->pos);
    if (GlobalContext::collect_kythe_data()) {
      KytheData::AddTypeDefinition(alias);
    }
  }
References v8::internal::torque::KytheData::AddTypeDefinition(), v8::internal::torque::GlobalContext::collect_kythe_data(), v8::internal::torque::TypeDeclaration::name, v8::internal::torque::AstNode::pos, v8::internal::torque::Declarations::PredeclareTypeAlias(), v8::internal::torque::Declarable::SetIdentifierPosition(), and v8::internal::torque::Declarable::SetPosition().
Predeclare() [7/7]
static void v8::internal::torque::PredeclarationVisitor::Predeclare (TypeDeclaration * decl) [inline], [static], [private]
Definition at line 36 of file declaration-visitor.h.
                                                {
    TypeAlias* alias =
        Declarations::PredeclareTypeAlias(decl->name, decl, false);
    alias->SetPosition(decl->pos);
    alias->SetIdentifierPosition(decl->name->pos);
    if (GlobalContext::collect_kythe_data()) {
      KytheData::AddTypeDefinition(alias);
    }
  }
References v8::internal::torque::KytheData::AddTypeDefinition(), v8::internal::torque::GlobalContext::collect_kythe_data(), v8::internal::torque::TypeDeclaration::name, v8::internal::torque::AstNode::pos, v8::internal::torque::Declarations::PredeclareTypeAlias(), v8::internal::torque::Declarable::SetIdentifierPosition(), and v8::internal::torque::Declarable::SetPosition().
ResolvePredeclarations()
void v8::internal::torque::PredeclarationVisitor::ResolvePredeclarations () [static]
Definition at line 458 of file declaration-visitor.cc.
                                                   {
  const auto& all_declarables = GlobalContext::AllDeclarables();
  for (size_t i = 0; i < all_declarables.size(); ++i) {
    Declarable* declarable = all_declarables[i].get();
    if (const TypeAlias* alias = TypeAlias::DynamicCast(declarable)) {
      CurrentScope::Scope scope_activator(alias->ParentScope());
      CurrentSourcePosition::Scope position_activator(alias->Position());
      alias->Resolve();
    }
  }
}
References v8::internal::torque::GlobalContext::AllDeclarables(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/declaration-visitor.h
/mnt/V8SourceCode/src/torque/declaration-visitor.cc