v8_inspector::InjectedScript Class Reference
#include <injected-script.h>
Classes
class CallFrameScope
class ContextScope
class ObjectScope
class ProtocolPromiseHandler
class Scope
Public Member Functions
InjectedScript (InspectedContext *, int sessionId)
~InjectedScript ()
InjectedScript (const InjectedScript &)=delete
InjectedScript & operator= (const InjectedScript &)=delete
InspectedContext * context () const
Response getProperties (v8::Local< v8::Object >, const String16 &groupName, bool ownProperties, bool accessorPropertiesOnly, bool nonIndexedPropertiesOnly, const WrapOptions &wrapOptions, std::unique_ptr< protocol::Array< protocol::Runtime::PropertyDescriptor >> *result, std::unique_ptr< protocol::Runtime::ExceptionDetails > *)
Response getInternalAndPrivateProperties (v8::Local< v8::Value >, const String16 &groupName, bool accessorPropertiesOnly, std::unique_ptr< protocol::Array< protocol::Runtime::InternalPropertyDescriptor >> *internalProperties, std::unique_ptr< protocol::Array< protocol::Runtime::PrivatePropertyDescriptor >> *privateProperties)
void releaseObject (const String16 &objectId)
Response wrapObject (v8::Local< v8::Value >, const String16 &groupName, const WrapOptions &wrapOptions, std::unique_ptr< protocol::Runtime::RemoteObject > *result)
Response wrapObject (v8::Local< v8::Value >, const String16 &groupName, const WrapOptions &wrapOptions, v8::MaybeLocal< v8::Value > customPreviewConfig, int maxCustomPreviewDepth, std::unique_ptr< protocol::Runtime::RemoteObject > *result)
Response wrapObjectMirror (const ValueMirror &mirror, const String16 &groupName, const WrapOptions &wrapOptions, v8::MaybeLocal< v8::Value > customPreviewConfig, int maxCustomPreviewDepth, std::unique_ptr< protocol::Runtime::RemoteObject > *result)
std::unique_ptr< protocol::Runtime::RemoteObject > wrapTable (v8::Local< v8::Object > table, v8::MaybeLocal< v8::Array > columns)
void addPromiseCallback (V8InspectorSessionImpl *session, v8::MaybeLocal< v8::Value > value, const String16 &objectGroup, std::unique_ptr< WrapOptions > wrapOptions, bool replMode, bool throwOnSideEffect, std::shared_ptr< EvaluateCallback > callback)
Response findObject (const RemoteObjectId &, v8::Local< v8::Value > *) const
String16 objectGroupName (const RemoteObjectId &) const
void releaseObjectGroup (const String16 &)
void setCustomObjectFormatterEnabled (bool)
Response resolveCallArgument (protocol::Runtime::CallArgument *, v8::Local< v8::Value > *result)
Response createExceptionDetails (const v8::TryCatch &, const String16 &groupName, std::unique_ptr< protocol::Runtime::ExceptionDetails > *result)
Response createExceptionDetails (v8::Local< v8::Message > message, v8::Local< v8::Value > exception, const String16 &groupName, std::unique_ptr< protocol::Runtime::ExceptionDetails > *result)
Response wrapEvaluateResult (v8::MaybeLocal< v8::Value > maybeResultValue, const v8::TryCatch &, const String16 &objectGroup, const WrapOptions &wrapOptions, bool throwOnSideEffect, std::unique_ptr< protocol::Runtime::RemoteObject > *result, std::unique_ptr< protocol::Runtime::ExceptionDetails > *)
v8::Local< v8::Value > lastEvaluationResult () const
void setLastEvaluationResult (v8::Local< v8::Value > result)
String16 bindObject (v8::Local< v8::Value >, const String16 &groupName)
Private Member Functions
v8::Local< v8::Object > commandLineAPI ()
void unbindObject (int id)
void discardEvaluateCallbacks ()
void deleteEvaluateCallback (std::shared_ptr< EvaluateCallback > callback)
Response addExceptionToDetails (v8::Local< v8::Value > exception, protocol::Runtime::ExceptionDetails *exceptionDetails, const String16 &objectGroup)
Static Private Member Functions
static Response bindRemoteObjectIfNeeded (int sessionId, v8::Local< v8::Context > context, v8::Local< v8::Value >, const String16 &groupName, protocol::Runtime::RemoteObject *remoteObject)
Private Attributes
InspectedContext * m_context
int m_sessionId
v8::Global< v8::Value > m_lastEvaluationResult
v8::Global< v8::Object > m_commandLineAPI
int m_lastBoundObjectId = 1
std::unordered_map< int, v8::Global< v8::Value > > m_idToWrappedObject
std::unordered_map< int, String16 > m_idToObjectGroupName
std::unordered_map< String16, std::vector< int > > m_nameToObjectGroup
std::unordered_set< std::shared_ptr< EvaluateCallback > > m_evaluateCallbacks
bool m_customPreviewEnabled = false
Friends
class EvaluateCallback
class PromiseHandlerTracker
Detailed Description
Definition at line 77 of file injected-script.h.
Constructor & Destructor Documentation
InjectedScript() [1/2]
v8_inspector::InjectedScript::InjectedScript (InspectedContext * context, int sessionId)
Definition at line 400 of file injected-script.cc.
    : m_context(context), m_sessionId(sessionId) {}
 InjectedScript()
v8_inspector::InjectedScript::~InjectedScript ()
Definition at line 403 of file injected-script.cc.
{ discardEvaluateCallbacks(); }
References discardEvaluateCallbacks().
InjectedScript() [2/2]
v8_inspector::InjectedScript::InjectedScript (const InjectedScript &) [delete]
Member Function Documentation
addExceptionToDetails()
Response v8_inspector::InjectedScript::addExceptionToDetails (v8::Local< v8::Value > exception, protocol::Runtime::ExceptionDetails * exceptionDetails, const String16 & objectGroup) [private]
Definition at line 879 of file injected-script.cc.
                                 {
  if (exception.IsEmpty()) return Response::Success();
  std::unique_ptr<protocol::Runtime::RemoteObject> wrapped;
  Response response =
      wrapObject(exception, objectGroup,
                 exception->IsNativeError() ? WrapOptions({WrapMode::kIdOnly})
                                            : WrapOptions({WrapMode::kPreview}),
                 &wrapped);
  if (!response.IsSuccess()) return response;
  exceptionDetails->setException(std::move(wrapped));
  return Response::Success();
}
References v8::api_internal::IndirectHandleBase::IsEmpty(), v8::Value::IsNativeError(), v8_inspector::kIdOnly, v8_inspector::kPreview, and wrapObject().
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), and createExceptionDetails().
addPromiseCallback()
void v8_inspector::InjectedScript::addPromiseCallback (V8InspectorSessionImpl * session, v8::MaybeLocal< v8::Value > value, const String16 & objectGroup, std::unique_ptr< WrapOptions > wrapOptions, bool replMode, bool throwOnSideEffect, std::shared_ptr< EvaluateCallback > callback)
Definition at line 746 of file injected-script.cc.
                                              {
  m_evaluateCallbacks.insert(callback);
  // After stashing the shared_ptr in `m_evaluateCallback`, we reset `callback`.
  // `ProtocolPromiseHandler:add` can take longer than the life time of this
  // `InjectedScript` and we don't want `callback` to survive that.
  std::weak_ptr<EvaluateCallback> weak_callback = callback;
  callback.reset();
  CHECK_EQ(weak_callback.use_count(), 1);
  if (value.IsEmpty()) {
    EvaluateCallback::sendFailure(weak_callback, this,
                                  Response::InternalError());
    return;
  }
  v8::MicrotasksScope microtasksScope(m_context->context(),
                                      v8::MicrotasksScope::kRunMicrotasks);
  ProtocolPromiseHandler::add(session, m_context->context(),
                              value.ToLocalChecked(), m_context->contextId(),
                              objectGroup, std::move(wrapOptions), replMode,
                              throwOnSideEffect, weak_callback);
  // Do not add any code here! `this` might be invalid.
  // `ProtocolPromiseHandler::add` calls into JS which could kill this
  // `InjectedScript`.
}
References v8_inspector::InjectedScript::ProtocolPromiseHandler::add(), CHECK_EQ, v8_inspector::InspectedContext::context(), v8_inspector::InspectedContext::contextId(), v8::MicrotasksScope::kRunMicrotasks, m_context, m_evaluateCallbacks, v8_inspector::EvaluateCallback::sendFailure(), and v8::internal::value.
Referenced by v8_inspector::V8RuntimeAgentImpl::awaitPromise(), v8_inspector::V8RuntimeAgentImpl::evaluate(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), and v8_inspector::V8RuntimeAgentImpl::runScript().
bindObject()
String16 v8_inspector::InjectedScript::bindObject (v8::Local< v8::Value > value, const String16 & groupName)
Definition at line 1142 of file injected-script.cc.
                                                               {
  if (m_lastBoundObjectId <= 0) m_lastBoundObjectId = 1;
  int id = m_lastBoundObjectId++;
  m_idToWrappedObject[id].Reset(m_context->isolate(), value);
  m_idToWrappedObject[id].AnnotateStrongRetainer(kGlobalHandleLabel);
  if (!groupName.isEmpty() && id > 0) {
    m_idToObjectGroupName[id] = groupName;
    m_nameToObjectGroup[groupName].push_back(id);
  }
  return RemoteObjectId::serialize(m_context->inspector()->isolateId(),
                                   m_context->contextId(), id);
}
References v8_inspector::InspectedContext::contextId(), v8_inspector::InspectedContext::inspector(), v8_inspector::String16::isEmpty(), v8_inspector::InspectedContext::isolate(), v8_inspector::V8InspectorImpl::isolateId(), v8_inspector::anonymous_namespace{injected-script.cc}::kGlobalHandleLabel, m_context, m_idToObjectGroupName, m_idToWrappedObject, m_lastBoundObjectId, m_nameToObjectGroup, v8_inspector::RemoteObjectId::serialize(), and v8::internal::value.
Referenced by bindRemoteObjectIfNeeded(), and v8_inspector::generateCustomPreview().
bindRemoteObjectIfNeeded()
Response v8_inspector::InjectedScript::bindRemoteObjectIfNeeded (int sessionId, v8::Local< v8::Context > context, v8::Local< v8::Value > value, const String16 & groupName, protocol::Runtime::RemoteObject * remoteObject) [static], [private]
Definition at line 1157 of file injected-script.cc.
                                                                          {
  if (!remoteObject) return Response::Success();
  if (remoteObject->hasValue()) return Response::Success();
  if (remoteObject->hasUnserializableValue()) return Response::Success();
  if (remoteObject->getType() != RemoteObject::TypeEnum::Undefined) {
    v8::Isolate* isolate = v8::Isolate::GetCurrent();
    V8InspectorImpl* inspector =
        static_cast<V8InspectorImpl*>(v8::debug::GetInspector(isolate));
    InspectedContext* inspectedContext =
        inspector->getContext(InspectedContext::contextId(context));
    InjectedScript* injectedScript =
        inspectedContext ? inspectedContext->getInjectedScript(sessionId)
                         : nullptr;
    if (!injectedScript) {
      return Response::ServerError("Cannot find context with specified id");
    }
    remoteObject->setObjectId(injectedScript->bindObject(value, groupName));
  }
  return Response::Success();
}
References bindObject(), context(), v8_inspector::InspectedContext::contextId(), v8_inspector::V8InspectorImpl::getContext(), v8::Isolate::GetCurrent(), v8_inspector::InspectedContext::getInjectedScript(), v8::debug::GetInspector(), v8::internal::compiler::Undefined, and v8::internal::value.
Referenced by getInternalAndPrivateProperties(), getProperties(), and wrapObjectMirror().
commandLineAPI()
v8::Local< v8::Object > v8_inspector::InjectedScript::commandLineAPI () [private]
Definition at line 990 of file injected-script.cc.
                                                 {
  if (m_commandLineAPI.IsEmpty()) {
    v8::debug::DisableBreakScope disable_break(m_context->isolate());
    m_commandLineAPI.Reset(
        m_context->isolate(),
        m_context->inspector()->console()->createCommandLineAPI(
            m_context->context(), m_sessionId));
    m_commandLineAPI.AnnotateStrongRetainer(kGlobalHandleLabel);
  }
  return m_commandLineAPI.Get(m_context->isolate());
}
References v8::PersistentBase< T >::AnnotateStrongRetainer(), v8_inspector::V8InspectorImpl::console(), v8_inspector::InspectedContext::context(), v8_inspector::V8Console::createCommandLineAPI(), v8::PersistentBase< T >::Get(), v8_inspector::InspectedContext::inspector(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8_inspector::InspectedContext::isolate(), v8_inspector::anonymous_namespace{injected-script.cc}::kGlobalHandleLabel, m_commandLineAPI, m_context, m_sessionId, and v8::PersistentBase< T >::Reset().
context()
InspectedContext* v8_inspector::InjectedScript::context () const [inline]
Definition at line 84 of file injected-script.h.
{ return m_context; }
References m_context.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::add(), bindRemoteObjectIfNeeded(), getInternalAndPrivateProperties(), getProperties(), v8_inspector::V8InspectorSessionImpl::unwrapObject(), wrapObject(), wrapObjectMirror(), and wrapTable().
createExceptionDetails() [1/2]
Response v8_inspector::InjectedScript::createExceptionDetails (const v8::TryCatch & tryCatch, const String16 & groupName, std::unique_ptr< protocol::Runtime::ExceptionDetails > * result)
Definition at line 895 of file injected-script.cc.
                                                            {
  if (!tryCatch.HasCaught()) return Response::InternalError();
  v8::Local<v8::Message> message = tryCatch.Message();
  v8::Local<v8::Value> exception = tryCatch.Exception();
  return createExceptionDetails(message, exception, objectGroup, result);
}
References v8::TryCatch::Exception(), v8::TryCatch::HasCaught(), v8::TryCatch::Message(), and v8::base::internal::result.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::V8RuntimeAgentImpl::compileScript(), v8_inspector::V8RuntimeAgentImpl::getExceptionDetails(), getProperties(), and wrapEvaluateResult().
createExceptionDetails() [2/2]
Response v8_inspector::InjectedScript::createExceptionDetails (v8::Local< v8::Message > message, v8::Local< v8::Value > exception, const String16 & groupName, std::unique_ptr< protocol::Runtime::ExceptionDetails > * result)
Definition at line 904 of file injected-script.cc.
                                                            {
  String16 messageText =
      message.IsEmpty()
          ? String16()
          : toProtocolString(m_context->isolate(), message->Get());
  std::unique_ptr<protocol::Runtime::ExceptionDetails> exceptionDetails =
      protocol::Runtime::ExceptionDetails::create()
          .setExceptionId(m_context->inspector()->nextExceptionId())
          .setText(exception.IsEmpty() ? messageText : String16("Uncaught"))
          .setLineNumber(
              message.IsEmpty()
                  ? 0
                  : message->GetLineNumber(m_context->context()).FromMaybe(1) -
                        1)
          .setColumnNumber(
              message.IsEmpty()
                  ? 0
                  : message->GetStartColumn(m_context->context()).FromMaybe(0))
          .build();
  if (!message.IsEmpty()) {
    exceptionDetails->setScriptId(
        String16::fromInteger(message->GetScriptOrigin().ScriptId()));
    v8::Local<v8::StackTrace> stackTrace = message->GetStackTrace();
    if (!stackTrace.IsEmpty() && stackTrace->GetFrameCount() > 0) {
      std::unique_ptr<V8StackTraceImpl> v8StackTrace =
          m_context->inspector()->debugger()->createStackTrace(stackTrace);
      if (v8StackTrace) {
        exceptionDetails->setStackTrace(v8StackTrace->buildInspectorObjectImpl(
            m_context->inspector()->debugger()));
      }
    }
  }
  Response response =
      addExceptionToDetails(exception, exceptionDetails.get(), objectGroup);
  if (!response.IsSuccess()) return response;
  *result = std::move(exceptionDetails);
  return Response::Success();
}
References addExceptionToDetails(), v8_inspector::InspectedContext::context(), v8_inspector::V8Debugger::createStackTrace(), v8_inspector::V8InspectorImpl::debugger(), v8_inspector::String16::fromInteger(), v8_inspector::InspectedContext::inspector(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8_inspector::InspectedContext::isolate(), m_context, v8_inspector::V8InspectorImpl::nextExceptionId(), v8::base::internal::result, and v8_inspector::toProtocolString().
deleteEvaluateCallback()
void v8_inspector::InjectedScript::deleteEvaluateCallback (std::shared_ptr< EvaluateCallback > callback) [private]
Definition at line 785 of file injected-script.cc.
                                              {
  auto it = m_evaluateCallbacks.find(callback);
  CHECK_NE(it, m_evaluateCallbacks.end());
  m_evaluateCallbacks.erase(it);
}
References CHECK_NE, and m_evaluateCallbacks.
Referenced by v8_inspector::EvaluateCallback::sendFailure(), and v8_inspector::EvaluateCallback::sendSuccess().
discardEvaluateCallbacks()
void v8_inspector::InjectedScript::discardEvaluateCallbacks () [private]
Definition at line 776 of file injected-script.cc.
                                              {
  while (!m_evaluateCallbacks.empty()) {
    EvaluateCallback::sendFailure(
        *m_evaluateCallbacks.begin(), this,
        Response::ServerError("Execution context was destroyed."));
  }
  CHECK(m_evaluateCallbacks.empty());
}
References CHECK, m_evaluateCallbacks, and v8_inspector::EvaluateCallback::sendFailure().
Referenced by ~InjectedScript().
findObject()
Response v8_inspector::InjectedScript::findObject (const RemoteObjectId & objectId, v8::Local< v8::Value > * outObject) const
Definition at line 792 of file injected-script.cc.
                                                                       {
  auto it = m_idToWrappedObject.find(objectId.id());
  if (it == m_idToWrappedObject.end())
    return Response::ServerError("Could not find object with given id");
  *outObject = it->second.Get(m_context->isolate());
  return Response::Success();
}
References v8_inspector::RemoteObjectId::id(), v8_inspector::InspectedContext::isolate(), m_context, and m_idToWrappedObject.
Referenced by v8_inspector::InjectedScript::ObjectScope::findInjectedScript(), resolveCallArgument(), and v8_inspector::V8InspectorSessionImpl::unwrapObject().
getInternalAndPrivateProperties()
Response v8_inspector::InjectedScript::getInternalAndPrivateProperties (v8::Local< v8::Value > , const String16 & groupName, bool accessorPropertiesOnly, std::unique_ptr< protocol::Array< protocol::Runtime::InternalPropertyDescriptor >> * internalProperties, std::unique_ptr< protocol::Array< protocol::Runtime::PrivatePropertyDescriptor >> * privateProperties)
Definition at line 503 of file injected-script.cc.
                           {
  *internalProperties = std::make_unique<Array<InternalPropertyDescriptor>>();
  *privateProperties = std::make_unique<Array<PrivatePropertyDescriptor>>();
  if (!value->IsObject()) return Response::Success();
  v8::Local<v8::Object> value_obj = value.As<v8::Object>();
  v8::Local<v8::Context> context = m_context->context();
  int sessionId = m_sessionId;
  if (!accessorPropertiesOnly) {
    std::vector<InternalPropertyMirror> internalPropertiesWrappers;
    ValueMirror::getInternalProperties(m_context->context(), value_obj,
                                       &internalPropertiesWrappers);
    for (const auto& internalProperty : internalPropertiesWrappers) {
      std::unique_ptr<RemoteObject> remoteObject;
      Response response = internalProperty.value->buildRemoteObject(
          m_context->context(), WrapOptions({WrapMode::kIdOnly}),
          &remoteObject);
      if (!response.IsSuccess()) return response;
      response = bindRemoteObjectIfNeeded(
          sessionId, context,
          internalProperty.value->v8Value(v8::Isolate::GetCurrent()), groupName,
          remoteObject.get());
      if (!response.IsSuccess()) return response;
      (*internalProperties)
          ->emplace_back(InternalPropertyDescriptor::create()
                             .setName(internalProperty.name)
                             .setValue(std::move(remoteObject))
                             .build());
    }
  }
  std::vector<PrivatePropertyMirror> privatePropertyWrappers =
      ValueMirror::getPrivateProperties(context, value_obj,
                                        accessorPropertiesOnly);
  for (const auto& privateProperty : privatePropertyWrappers) {
    std::unique_ptr<PrivatePropertyDescriptor> descriptor =
        PrivatePropertyDescriptor::create()
            .setName(privateProperty.name)
            .build();
    std::unique_ptr<RemoteObject> remoteObject;
    DCHECK((privateProperty.getter || privateProperty.setter) ^
           (!!privateProperty.value));
    if (privateProperty.value) {
      Response response = privateProperty.value->buildRemoteObject(
          context, WrapOptions({WrapMode::kIdOnly}), &remoteObject);
      if (!response.IsSuccess()) return response;
      response = bindRemoteObjectIfNeeded(
          sessionId, context,
          privateProperty.value->v8Value(v8::Isolate::GetCurrent()), groupName,
          remoteObject.get());
      if (!response.IsSuccess()) return response;
      descriptor->setValue(std::move(remoteObject));
    }
    if (privateProperty.getter) {
      Response response = privateProperty.getter->buildRemoteObject(
          context, WrapOptions({WrapMode::kIdOnly}), &remoteObject);
      if (!response.IsSuccess()) return response;
      response = bindRemoteObjectIfNeeded(
          sessionId, context,
          privateProperty.getter->v8Value(v8::Isolate::GetCurrent()), groupName,
          remoteObject.get());
      if (!response.IsSuccess()) return response;
      descriptor->setGet(std::move(remoteObject));
    }
    if (privateProperty.setter) {
      Response response = privateProperty.setter->buildRemoteObject(
          context, WrapOptions({WrapMode::kIdOnly}), &remoteObject);
      if (!response.IsSuccess()) return response;
      response = bindRemoteObjectIfNeeded(
          sessionId, context,
          privateProperty.setter->v8Value(v8::Isolate::GetCurrent()), groupName,
          remoteObject.get());
      if (!response.IsSuccess()) return response;
      descriptor->setSet(std::move(remoteObject));
    }
    (*privateProperties)->emplace_back(std::move(descriptor));
  }
  return Response::Success();
}
References bindRemoteObjectIfNeeded(), context(), v8_inspector::InspectedContext::context(), DCHECK, v8::Isolate::GetCurrent(), v8_inspector::ValueMirror::getInternalProperties(), v8_inspector::ValueMirror::getPrivateProperties(), v8_inspector::kIdOnly, m_context, m_sessionId, and v8::internal::value.
Referenced by v8_inspector::V8RuntimeAgentImpl::getProperties().
getProperties()
Response v8_inspector::InjectedScript::getProperties (v8::Local< v8::Object > , const String16 & groupName, bool ownProperties, bool accessorPropertiesOnly, bool nonIndexedPropertiesOnly, const WrapOptions & wrapOptions, std::unique_ptr< protocol::Array< protocol::Runtime::PropertyDescriptor >> * result, std::unique_ptr< protocol::Runtime::ExceptionDetails > *)
Definition at line 420 of file injected-script.cc.
                                                                      {
  v8::HandleScope handles(m_context->isolate());
  v8::Local<v8::Context> context = m_context->context();
  v8::Isolate* isolate = m_context->isolate();
  int sessionId = m_sessionId;
  v8::TryCatch tryCatch(isolate);
  *properties = std::make_unique<Array<PropertyDescriptor>>();
  std::vector<PropertyMirror> mirrors;
  PropertyAccumulator accumulator(&mirrors);
  if (!ValueMirror::getProperties(context, object, ownProperties,
                                  accessorPropertiesOnly,
                                  nonIndexedPropertiesOnly, &accumulator)) {
    return createExceptionDetails(tryCatch, groupName, exceptionDetails);
  }
  for (const PropertyMirror& mirror : mirrors) {
    std::unique_ptr<PropertyDescriptor> descriptor =
        PropertyDescriptor::create()
            .setName(mirror.name)
            .setConfigurable(mirror.configurable)
            .setEnumerable(mirror.enumerable)
            .setIsOwn(mirror.isOwn)
            .build();
    std::unique_ptr<RemoteObject> remoteObject;
    if (mirror.value) {
      Response response = wrapObjectMirror(
          *mirror.value, groupName, wrapOptions, v8::MaybeLocal<v8::Value>(),
          kMaxCustomPreviewDepth, &remoteObject);
      if (!response.IsSuccess()) return response;
      descriptor->setValue(std::move(remoteObject));
      descriptor->setWritable(mirror.writable);
    }
    if (mirror.getter) {
      Response response =
          mirror.getter->buildRemoteObject(context, wrapOptions, &remoteObject);
      if (!response.IsSuccess()) return response;
      response = bindRemoteObjectIfNeeded(sessionId, context,
                                          mirror.getter->v8Value(isolate),
                                          groupName, remoteObject.get());
      if (!response.IsSuccess()) return response;
      descriptor->setGet(std::move(remoteObject));
    }
    if (mirror.setter) {
      Response response =
          mirror.setter->buildRemoteObject(context, wrapOptions, &remoteObject);
      if (!response.IsSuccess()) return response;
      response = bindRemoteObjectIfNeeded(sessionId, context,
                                          mirror.setter->v8Value(isolate),
                                          groupName, remoteObject.get());
      if (!response.IsSuccess()) return response;
      descriptor->setSet(std::move(remoteObject));
    }
    if (mirror.symbol) {
      Response response =
          mirror.symbol->buildRemoteObject(context, wrapOptions, &remoteObject);
      if (!response.IsSuccess()) return response;
      response = bindRemoteObjectIfNeeded(sessionId, context,
                                          mirror.symbol->v8Value(isolate),
                                          groupName, remoteObject.get());
      if (!response.IsSuccess()) return response;
      descriptor->setSymbol(std::move(remoteObject));
    }
    if (mirror.exception) {
      Response response = mirror.exception->buildRemoteObject(
          context, wrapOptions, &remoteObject);
      if (!response.IsSuccess()) return response;
      response = bindRemoteObjectIfNeeded(sessionId, context,
                                          mirror.exception->v8Value(isolate),
                                          groupName, remoteObject.get());
      if (!response.IsSuccess()) return response;
      descriptor->setValue(std::move(remoteObject));
      descriptor->setWasThrown(true);
    }
    (*properties)->emplace_back(std::move(descriptor));
  }
  return Response::Success();
}
References bindRemoteObjectIfNeeded(), context(), v8_inspector::InspectedContext::context(), createExceptionDetails(), v8_inspector::ValueMirror::getProperties(), v8_inspector::InspectedContext::isolate(), v8_inspector::kMaxCustomPreviewDepth, m_context, m_sessionId, and wrapObjectMirror().
Referenced by v8_inspector::V8RuntimeAgentImpl::getProperties().
lastEvaluationResult()
v8::Local< v8::Value > v8_inspector::InjectedScript::lastEvaluationResult () const
Definition at line 820 of file injected-script.cc.
                                                            {
  if (m_lastEvaluationResult.IsEmpty())
    return v8::Undefined(m_context->isolate());
  return m_lastEvaluationResult.Get(m_context->isolate());
}
References v8::PersistentBase< T >::Get(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8_inspector::InspectedContext::isolate(), m_context, m_lastEvaluationResult, and v8::Undefined().
Referenced by v8_inspector::V8Console::lastEvaluationResultCallback().
objectGroupName()
String16 v8_inspector::InjectedScript::objectGroupName (const RemoteObjectId & objectId) const
Definition at line 801 of file injected-script.cc.
                                                                             {
  if (objectId.id() <= 0) return String16();
  auto it = m_idToObjectGroupName.find(objectId.id());
  return it != m_idToObjectGroupName.end() ? it->second : String16();
}
References v8_inspector::RemoteObjectId::id(), and m_idToObjectGroupName.
Referenced by v8_inspector::InjectedScript::ObjectScope::findInjectedScript(), and v8_inspector::V8InspectorSessionImpl::unwrapObject().
operator=()
InjectedScript& v8_inspector::InjectedScript::operator= (const InjectedScript &) [delete]
releaseObject()
void v8_inspector::InjectedScript::releaseObject (const String16 & objectId)
Definition at line 596 of file injected-script.cc.
                                                           {
  std::unique_ptr<RemoteObjectId> remoteId;
  Response response = RemoteObjectId::parse(objectId, &remoteId);
  if (response.IsSuccess()) unbindObject(remoteId->id());
}
References v8_inspector::RemoteObjectId::parse(), and unbindObject().
Referenced by v8_inspector::V8RuntimeAgentImpl::releaseObject().
releaseObjectGroup()
void v8_inspector::InjectedScript::releaseObjectGroup (const String16 & objectGroup)
Definition at line 807 of file injected-script.cc.
                                                                   {
  if (objectGroup == "console") m_lastEvaluationResult.Reset();
  if (objectGroup.isEmpty()) return;
  auto it = m_nameToObjectGroup.find(objectGroup);
  if (it == m_nameToObjectGroup.end()) return;
  for (int id : it->second) unbindObject(id);
  m_nameToObjectGroup.erase(it);
}
References v8_inspector::String16::isEmpty(), m_lastEvaluationResult, m_nameToObjectGroup, v8::PersistentBase< T >::Reset(), and unbindObject().
Referenced by v8_inspector::V8InspectorSessionImpl::releaseObjectGroup().
resolveCallArgument()
Response v8_inspector::InjectedScript::resolveCallArgument (protocol::Runtime::CallArgument * callArgument, v8::Local< v8::Value > * result)
Definition at line 831 of file injected-script.cc.
                              {
  if (callArgument->hasObjectId()) {
    std::unique_ptr<RemoteObjectId> remoteObjectId;
    Response response =
        RemoteObjectId::parse(callArgument->getObjectId(""), &remoteObjectId);
    if (!response.IsSuccess()) return response;
    if (remoteObjectId->contextId() != m_context->contextId() ||
        remoteObjectId->isolateId() != m_context->inspector()->isolateId()) {
      return Response::ServerError(
          "Argument should belong to the same JavaScript world as target "
          "object");
    }
    return findObject(*remoteObjectId, result);
  }
  if (callArgument->hasValue() || callArgument->hasUnserializableValue()) {
    String16 value;
    if (callArgument->hasValue()) {
      std::vector<uint8_t> json;
      v8_crdtp::json::ConvertCBORToJSON(
          v8_crdtp::SpanFrom(callArgument->getValue(nullptr)->Serialize()),
          &json);
      value =
          "(" +
          String16(reinterpret_cast<const char*>(json.data()), json.size()) +
          ")";
    } else {
      String16 unserializableValue = callArgument->getUnserializableValue("");
      // Protect against potential identifier resolution for NaN and Infinity.
      if (isResolvableNumberLike(unserializableValue))
        value = "Number(\"" + unserializableValue + "\")";
      else
        value = unserializableValue;
    }
    if (!m_context->inspector()
             ->compileAndRunInternalScript(
                 m_context->context(), toV8String(m_context->isolate(), value))
             .ToLocal(result)) {
      return Response::ServerError(
          "Couldn't parse value object in call argument");
    }
    return Response::Success();
  }
  *result = v8::Undefined(m_context->isolate());
  return Response::Success();
}
References v8_inspector::V8InspectorImpl::compileAndRunInternalScript(), v8_inspector::InspectedContext::context(), v8_inspector::InspectedContext::contextId(), findObject(), v8_inspector::InspectedContext::inspector(), v8_inspector::InspectedContext::isolate(), v8_inspector::V8InspectorImpl::isolateId(), v8_inspector::anonymous_namespace{injected-script.cc}::isResolvableNumberLike(), m_context, v8_inspector::RemoteObjectId::parse(), v8::base::internal::result, v8::MaybeLocal< T >::ToLocal(), v8_inspector::toV8String(), v8::Undefined(), and v8::internal::value.
Referenced by v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), v8_inspector::V8DebuggerAgentImpl::setReturnValue(), and v8_inspector::V8DebuggerAgentImpl::setVariableValue().
setCustomObjectFormatterEnabled()
void v8_inspector::InjectedScript::setCustomObjectFormatterEnabled (bool enabled)
Definition at line 816 of file injected-script.cc.
                                                                 {
  m_customPreviewEnabled = enabled;
}
References m_customPreviewEnabled.
Referenced by v8_inspector::V8InspectorSessionImpl::findInjectedScript(), and v8_inspector::V8InspectorSessionImpl::setCustomObjectFormatterEnabled().
setLastEvaluationResult()
void v8_inspector::InjectedScript::setLastEvaluationResult (v8::Local< v8::Value > result)
Definition at line 826 of file injected-script.cc.
                                                                    {
  m_lastEvaluationResult.Reset(m_context->isolate(), result);
  m_lastEvaluationResult.AnnotateStrongRetainer(kGlobalHandleLabel);
}
References v8::PersistentBase< T >::AnnotateStrongRetainer(), v8_inspector::InspectedContext::isolate(), v8_inspector::anonymous_namespace{injected-script.cc}::kGlobalHandleLabel, m_context, m_lastEvaluationResult, v8::PersistentBase< T >::Reset(), and v8::base::internal::result.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback().
unbindObject()
void v8_inspector::InjectedScript::unbindObject (int id) [private]
Definition at line 1180 of file injected-script.cc.
                                        {
  m_idToWrappedObject.erase(id);
  m_idToObjectGroupName.erase(id);
}
References m_idToObjectGroupName, and m_idToWrappedObject.
Referenced by releaseObject(), and releaseObjectGroup().
wrapEvaluateResult()
Response v8_inspector::InjectedScript::wrapEvaluateResult (v8::MaybeLocal< v8::Value > maybeResultValue, const v8::TryCatch & tryCatch, const String16 & objectGroup, const WrapOptions & wrapOptions, bool throwOnSideEffect, std::unique_ptr< protocol::Runtime::RemoteObject > * result, std::unique_ptr< protocol::Runtime::ExceptionDetails > * exceptionDetails)
Definition at line 946 of file injected-script.cc.
                                                                      {
  v8::Local<v8::Value> resultValue;
  if (!tryCatch.HasCaught()) {
    if (!maybeResultValue.ToLocal(&resultValue)) {
      if (!tryCatch.CanContinue()) {
        return Response::ServerError("Execution was terminated");
      }
      return Response::InternalError();
    }
    Response response =
        wrapObject(resultValue, objectGroup, wrapOptions, result);
    if (!response.IsSuccess()) return response;
    if (objectGroup == "console") {
      m_lastEvaluationResult.Reset(m_context->isolate(), resultValue);
      m_lastEvaluationResult.AnnotateStrongRetainer(kGlobalHandleLabel);
    }
  } else {
    if (tryCatch.HasTerminated() || !tryCatch.CanContinue()) {
      return Response::ServerError("Execution was terminated");
    }
    v8::Local<v8::Value> exception = tryCatch.Exception();
    if (!throwOnSideEffect) {
      m_context->inspector()->client()->dispatchError(
          m_context->context(), tryCatch.Message(), exception);
    }
    Response response = wrapObject(exception, objectGroup,
                                   exception->IsNativeError()
                                       ? WrapOptions({WrapMode::kIdOnly})
                                       : WrapOptions({WrapMode::kPreview}),
                                   result);
    if (!response.IsSuccess()) return response;
    // We send exception in result for compatibility reasons, even though it's
    // accessible through exceptionDetails.exception.
    response = createExceptionDetails(tryCatch, objectGroup, exceptionDetails);
    if (!response.IsSuccess()) return response;
  }
  return Response::Success();
}
References v8::PersistentBase< T >::AnnotateStrongRetainer(), v8::TryCatch::CanContinue(), v8_inspector::V8InspectorImpl::client(), v8_inspector::InspectedContext::context(), createExceptionDetails(), v8_inspector::V8InspectorClient::dispatchError(), v8::TryCatch::Exception(), v8::TryCatch::HasCaught(), v8::TryCatch::HasTerminated(), v8_inspector::InspectedContext::inspector(), v8::Value::IsNativeError(), v8_inspector::InspectedContext::isolate(), v8_inspector::anonymous_namespace{injected-script.cc}::kGlobalHandleLabel, v8_inspector::kIdOnly, v8_inspector::kPreview, m_context, m_lastEvaluationResult, v8::TryCatch::Message(), v8::PersistentBase< T >::Reset(), v8::base::internal::result, v8::MaybeLocal< T >::ToLocal(), and wrapObject().
Referenced by v8_inspector::V8DebuggerAgentImpl::evaluateOnCallFrame(), and v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::wrapEvaluateResultAsync().
wrapObject() [1/2]
Response v8_inspector::InjectedScript::wrapObject (v8::Local< v8::Value > value, const String16 & groupName, const WrapOptions & wrapOptions, std::unique_ptr< protocol::Runtime::RemoteObject > * result)
Definition at line 602 of file injected-script.cc.
                                                        {
  return wrapObject(value, groupName, wrapOptions, v8::MaybeLocal<v8::Value>(),
                    kMaxCustomPreviewDepth, result);
}
References v8_inspector::kMaxCustomPreviewDepth, v8::base::internal::result, and v8::internal::value.
Referenced by addExceptionToDetails(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::V8DebuggerAgentImpl::currentCallFrames(), v8_inspector::V8DebuggerAgentImpl::didPause(), v8_inspector::inspectImpl(), v8_inspector::V8RuntimeAgentImpl::queryObjects(), v8_inspector::anonymous_namespace{custom-preview.cc}::substituteObjectTags(), v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback(), wrapEvaluateResult(), v8_inspector::V8InspectorSessionImpl::wrapObject(), and wrapTable().
wrapObject() [2/2]
Response v8_inspector::InjectedScript::wrapObject (v8::Local< v8::Value > value, const String16 & groupName, const WrapOptions & wrapOptions, v8::MaybeLocal< v8::Value > customPreviewConfig, int maxCustomPreviewDepth, std::unique_ptr< protocol::Runtime::RemoteObject > * result)
Definition at line 610 of file injected-script.cc.
                                                        {
  v8::Local<v8::Context> context = m_context->context();
  v8::Context::Scope contextScope(context);
  std::unique_ptr<ValueMirror> mirror = ValueMirror::create(context, value);
  if (!mirror) return Response::InternalError();
  return wrapObjectMirror(*mirror, groupName, wrapOptions, customPreviewConfig,
                          maxCustomPreviewDepth, result);
}
References context(), v8_inspector::InspectedContext::context(), v8_inspector::ValueMirror::create(), m_context, v8::base::internal::result, v8::internal::value, and wrapObjectMirror().
wrapObjectMirror()
Response v8_inspector::InjectedScript::wrapObjectMirror (const ValueMirror & mirror, const String16 & groupName, const WrapOptions & wrapOptions, v8::MaybeLocal< v8::Value > customPreviewConfig, int maxCustomPreviewDepth, std::unique_ptr< protocol::Runtime::RemoteObject > * result)
Definition at line 623 of file injected-script.cc.
                                                        {
  int customPreviewEnabled = m_customPreviewEnabled;
  int sessionId = m_sessionId;
  v8::Local<v8::Context> context = m_context->context();
  v8::Context::Scope contextScope(context);
  Response response = mirror.buildRemoteObject(context, wrapOptions, result);
  if (!response.IsSuccess()) return response;
  v8::Local<v8::Value> value = mirror.v8Value(v8::Isolate::GetCurrent());
  response = bindRemoteObjectIfNeeded(sessionId, context, value, groupName,
                                      result->get());
  if (!response.IsSuccess()) return response;
  if (customPreviewEnabled && value->IsObject()) {
    std::unique_ptr<protocol::Runtime::CustomPreview> customPreview;
    generateCustomPreview(m_context->isolate(), sessionId, groupName,
                          value.As<v8::Object>(), customPreviewConfig,
                          maxCustomPreviewDepth, &customPreview);
    if (customPreview) (*result)->setCustomPreview(std::move(customPreview));
  }
  if (wrapOptions.mode == WrapMode::kDeep) {
    V8SerializationDuplicateTracker duplicateTracker{context};
    std::unique_ptr<protocol::DictionaryValue> deepSerializedValueDict;
    response = mirror.buildDeepSerializedValue(
        context, wrapOptions.serializationOptions.maxDepth,
        wrapOptions.serializationOptions.additionalParameters.Get(
            m_context->isolate()),
        duplicateTracker, &deepSerializedValueDict);
    if (!response.IsSuccess()) return response;
    String16 type;
    deepSerializedValueDict->getString("type", &type);
    std::unique_ptr<protocol::Runtime::DeepSerializedValue>
        deepSerializedValue = protocol::Runtime::DeepSerializedValue::create()
                                  .setType(type)
                                  .build();
    protocol::Value* maybeValue = deepSerializedValueDict->get("value");
    if (maybeValue != nullptr) {
      deepSerializedValue->setValue(maybeValue->clone());
    }
    int weakLocalObjectReference;
    if (deepSerializedValueDict->getInteger("weakLocalObjectReference",
                                            &weakLocalObjectReference)) {
      deepSerializedValue->setWeakLocalObjectReference(
          weakLocalObjectReference);
    }
    if (!response.IsSuccess()) return response;
    (*result)->setDeepSerializedValue(std::move(deepSerializedValue));
  }
  return Response::Success();
}
References v8_inspector::WrapSerializationOptions::additionalParameters, bindRemoteObjectIfNeeded(), v8_inspector::ValueMirror::buildDeepSerializedValue(), v8_inspector::ValueMirror::buildRemoteObject(), context(), v8_inspector::InspectedContext::context(), v8_inspector::generateCustomPreview(), v8::PersistentBase< T >::Get(), v8::Isolate::GetCurrent(), v8_inspector::InspectedContext::isolate(), v8_inspector::kDeep, m_context, m_customPreviewEnabled, m_sessionId, v8_inspector::WrapSerializationOptions::maxDepth, v8_inspector::WrapOptions::mode, v8::base::internal::result, v8_inspector::WrapOptions::serializationOptions, v8::internal::tracing::type, v8_inspector::ValueMirror::v8Value(), and v8::internal::value.
Referenced by getProperties(), and wrapObject().
wrapTable()
std::unique_ptr< protocol::Runtime::RemoteObject > v8_inspector::InjectedScript::wrapTable (v8::Local< v8::Object > table, v8::MaybeLocal< v8::Array > columns)
Definition at line 683 of file injected-script.cc.
                                                                 {
  using protocol::Array;
  using protocol::Runtime::ObjectPreview;
  using protocol::Runtime::PropertyPreview;
  using protocol::Runtime::RemoteObject;
  v8::Isolate* isolate = m_context->isolate();
  v8::HandleScope handles(isolate);
  v8::Local<v8::Context> context = m_context->context();
  std::unique_ptr<RemoteObject> remoteObject;
  Response response = wrapObject(
      table, "console", WrapOptions({WrapMode::kIdOnly}), &remoteObject);
  if (!remoteObject || !response.IsSuccess()) return nullptr;
  auto mirror = ValueMirror::create(context, table);
  std::unique_ptr<ObjectPreview> preview;
  int limit = 1000;
  mirror->buildObjectPreview(context, true /* generatePreviewForTable */,
                             &limit, &limit, &preview);
  if (!preview) return nullptr;
  std::vector<String16> selectedColumns;
  std::unordered_set<String16> columnSet;
  v8::Local<v8::Array> v8Columns;
  if (maybeColumns.ToLocal(&v8Columns)) {
    for (uint32_t i = 0; i < v8Columns->Length(); ++i) {
      v8::Local<v8::Value> column;
      if (v8Columns->Get(context, i).ToLocal(&column) && column->IsString()) {
        String16 name = toProtocolString(isolate, column.As<v8::String>());
        if (columnSet.find(name) == columnSet.end()) {
          columnSet.insert(name);
          selectedColumns.push_back(name);
        }
      }
    }
  }
  if (!selectedColumns.empty()) {
    for (const std::unique_ptr<PropertyPreview>& prop :
         *preview->getProperties()) {
      ObjectPreview* columnPreview = prop->getValuePreview(nullptr);
      if (!columnPreview) continue;
      // Use raw pointer here since the lifetime of each PropertyPreview is
      // ensured by columnPreview. This saves an additional clone.
      std::unordered_map<String16, PropertyPreview*> columnMap;
      for (const std::unique_ptr<PropertyPreview>& property :
           *columnPreview->getProperties()) {
        if (columnSet.find(property->getName()) == columnSet.end()) continue;
        columnMap[property->getName()] = property.get();
      }
      auto filtered = std::make_unique<Array<PropertyPreview>>();
      for (const String16& column : selectedColumns) {
        if (columnMap.find(column) == columnMap.end()) continue;
        filtered->push_back(columnMap[column]->Clone());
      }
      columnPreview->setProperties(std::move(filtered));
    }
  }
  remoteObject->setPreview(std::move(preview));
  return remoteObject;
}
References v8::Local< T >::As(), context(), v8_inspector::InspectedContext::context(), v8_inspector::ValueMirror::create(), v8::Object::Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8_inspector::InspectedContext::isolate(), v8::Value::IsString(), v8_inspector::kIdOnly, v8::Array::Length(), m_context, name, v8::MaybeLocal< T >::ToLocal(), v8_inspector::toProtocolString(), and wrapObject().
Referenced by v8_inspector::V8InspectorSessionImpl::wrapTable().
Friends And Related Function Documentation
EvaluateCallback
friend class EvaluateCallback [friend]
Definition at line 235 of file injected-script.h.
PromiseHandlerTracker
friend class PromiseHandlerTracker [friend]
Definition at line 236 of file injected-script.h.
Member Data Documentation
m_commandLineAPI
v8::Global<v8::Object> v8_inspector::InjectedScript::m_commandLineAPI [private]
Definition at line 256 of file injected-script.h.
Referenced by commandLineAPI().
m_context
InspectedContext* v8_inspector::InjectedScript::m_context [private]
Definition at line 253 of file injected-script.h.
Referenced by addPromiseCallback(), v8_inspector::InjectedScript::Scope::allowCodeGenerationFromStrings(), bindObject(), v8_inspector::InjectedScript::Scope::cleanup(), commandLineAPI(), context(), createExceptionDetails(), findObject(), getInternalAndPrivateProperties(), getProperties(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::installCommandLineAPI(), lastEvaluationResult(), resolveCallArgument(), setLastEvaluationResult(), wrapEvaluateResult(), wrapObject(), wrapObjectMirror(), and wrapTable().
m_customPreviewEnabled
bool v8_inspector::InjectedScript::m_customPreviewEnabled = false [private]
Definition at line 262 of file injected-script.h.
Referenced by setCustomObjectFormatterEnabled(), and wrapObjectMirror().
m_evaluateCallbacks
std::unordered_set<std::shared_ptr<EvaluateCallback> > v8_inspector::InjectedScript::m_evaluateCallbacks [private]
Definition at line 261 of file injected-script.h.
Referenced by addPromiseCallback(), deleteEvaluateCallback(), and discardEvaluateCallbacks().
m_idToObjectGroupName
std::unordered_map<int, String16> v8_inspector::InjectedScript::m_idToObjectGroupName [private]
Definition at line 259 of file injected-script.h.
Referenced by bindObject(), objectGroupName(), and unbindObject().
m_idToWrappedObject
std::unordered_map<int, v8::Global<v8::Value> > v8_inspector::InjectedScript::m_idToWrappedObject [private]
Definition at line 258 of file injected-script.h.
Referenced by bindObject(), findObject(), and unbindObject().
m_lastBoundObjectId
int v8_inspector::InjectedScript::m_lastBoundObjectId = 1 [private]
Definition at line 257 of file injected-script.h.
Referenced by bindObject().
m_lastEvaluationResult
v8::Global<v8::Value> v8_inspector::InjectedScript::m_lastEvaluationResult [private]
Definition at line 255 of file injected-script.h.
Referenced by lastEvaluationResult(), releaseObjectGroup(), setLastEvaluationResult(), and wrapEvaluateResult().
m_nameToObjectGroup
std::unordered_map<String16, std::vector<int> > v8_inspector::InjectedScript::m_nameToObjectGroup [private]
Definition at line 260 of file injected-script.h.
Referenced by bindObject(), and releaseObjectGroup().
m_sessionId
int v8_inspector::InjectedScript::m_sessionId [private]
Definition at line 254 of file injected-script.h.
Referenced by commandLineAPI(), getInternalAndPrivateProperties(), getProperties(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::installCommandLineAPI(), and wrapObjectMirror().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/injected-script.h
/mnt/V8SourceCode/src/inspector/injected-script.cc