v8::internal::RegExpTree Class Reference
#include <regexp-ast.h>
Public Member Functions
virtual ~RegExpTree ()=default
virtual void * Accept (RegExpVisitor *visitor, void *data)=0
virtual RegExpNode * ToNode (RegExpCompiler *compiler, RegExpNode *on_success)=0
virtual bool IsTextElement ()
virtual bool IsAnchoredAtStart ()
virtual bool IsAnchoredAtEnd ()
virtual int min_match ()=0
virtual int max_match ()=0
virtual Interval CaptureRegisters ()
virtual void AppendToText (RegExpText *text, Zone *zone)
V8_EXPORT_PRIVATE std::ostream & Print (std::ostream &os, Zone *zone)
Static Public Attributes
static const int kInfinity = kMaxInt
Detailed Description
Definition at line 194 of file regexp-ast.h.
Constructor & Destructor Documentation
 RegExpTree()
virtual v8::internal::RegExpTree::~RegExpTree () [virtual], [default]
Member Function Documentation
Accept()
virtual void* v8::internal::RegExpTree::Accept (RegExpVisitor * visitor, void * data) [pure virtual]
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::Check(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::Compile(), v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::CompileFilter(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileLookaround(), Print(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitCapture(), v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitCapture(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitCapture(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitGroup(), v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitGroup(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitGroup(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitLookaround(), v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitLookaround(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitQuantifier(), v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitQuantifier(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitQuantifier().
AppendToText()
void v8::internal::RegExpTree::AppendToText (RegExpText * text, Zone * zone) [virtual]
Reimplemented in v8::internal::RegExpText, v8::internal::RegExpAtom, and v8::internal::RegExpClassRanges.
Definition at line 195 of file regexp-compiler.cc.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
CaptureRegisters()
virtual Interval v8::internal::RegExpTree::CaptureRegisters () [inline], [virtual]
Reimplemented in v8::internal::RegExpLookaround, v8::internal::RegExpGroup, v8::internal::RegExpCapture, v8::internal::RegExpQuantifier, v8::internal::RegExpAlternative, and v8::internal::RegExpDisjunction.
Definition at line 208 of file regexp-ast.h.
{ return Interval::Empty(); }
References v8::internal::Interval::Empty().
Referenced by v8::internal::RegExpQuantifier::CaptureRegisters(), v8::internal::RegExpCapture::CaptureRegisters(), v8::internal::RegExpGroup::CaptureRegisters(), v8::internal::RegExpLookaround::CaptureRegisters(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitQuantifier().
IsAnchoredAtEnd()
virtual bool v8::internal::RegExpTree::IsAnchoredAtEnd () [inline], [virtual]
Reimplemented in v8::internal::RegExpGroup, v8::internal::RegExpCapture, v8::internal::RegExpAssertion, v8::internal::RegExpAlternative, and v8::internal::RegExpDisjunction.
Definition at line 203 of file regexp-ast.h.
{ return false; }
Referenced by v8::internal::RegExpImpl::Compile(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileLookaround(), v8::internal::RegExpAlternative::IsAnchoredAtEnd(), v8::internal::RegExpCapture::IsAnchoredAtEnd(), and v8::internal::RegExpGroup::IsAnchoredAtEnd().
IsAnchoredAtStart()
virtual bool v8::internal::RegExpTree::IsAnchoredAtStart () [inline], [virtual]
Reimplemented in v8::internal::RegExpLookaround, v8::internal::RegExpGroup, v8::internal::RegExpCapture, v8::internal::RegExpAssertion, v8::internal::RegExpAlternative, and v8::internal::RegExpDisjunction.
Definition at line 202 of file regexp-ast.h.
{ return false; }
Referenced by v8::internal::RegExpImpl::Compile(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::Compile(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileLookaround(), v8::internal::RegExpAlternative::IsAnchoredAtStart(), v8::internal::RegExpCapture::IsAnchoredAtStart(), v8::internal::RegExpGroup::IsAnchoredAtStart(), v8::internal::RegExpLookaround::IsAnchoredAtStart(), and v8::internal::RegExpCompiler::PreprocessRegExp().
IsTextElement()
virtual bool v8::internal::RegExpTree::IsTextElement () [inline], [virtual]
Reimplemented in v8::internal::RegExpText, v8::internal::RegExpAtom, v8::internal::RegExpClassSetExpression, v8::internal::RegExpClassSetOperand, and v8::internal::RegExpClassRanges.
Definition at line 201 of file regexp-ast.h.
{ return false; }
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddAtom(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddAtom(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddTerm(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddTerm().
max_match()
virtual int v8::internal::RegExpTree::max_match () [pure virtual]
Implemented in v8::internal::RegExpEmpty, v8::internal::RegExpBackReference, v8::internal::RegExpLookaround, v8::internal::RegExpGroup, v8::internal::RegExpCapture, v8::internal::RegExpQuantifier, v8::internal::RegExpText, v8::internal::RegExpAtom, v8::internal::RegExpClassSetExpression, v8::internal::RegExpClassSetOperand, v8::internal::RegExpClassRanges, v8::internal::RegExpAssertion, v8::internal::RegExpAlternative, and v8::internal::RegExpDisjunction.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddQuantifierToAtom(), v8::internal::RegExpImpl::Compile(), v8::internal::RegExpAlternative::IsAnchoredAtEnd(), v8::internal::RegExpAlternative::IsAnchoredAtStart(), v8::internal::RegExpAlternative::RegExpAlternative(), v8::internal::RegExpDisjunction::RegExpDisjunction(), v8::internal::RegExpQuantifier::RegExpQuantifier(), and v8::internal::RegExpCapture::set_body().
min_match()
virtual int v8::internal::RegExpTree::min_match () [pure virtual]
Implemented in v8::internal::RegExpEmpty, v8::internal::RegExpBackReference, v8::internal::RegExpLookaround, v8::internal::RegExpGroup, v8::internal::RegExpCapture, v8::internal::RegExpQuantifier, v8::internal::RegExpText, v8::internal::RegExpAtom, v8::internal::RegExpClassSetExpression, v8::internal::RegExpClassSetOperand, v8::internal::RegExpClassRanges, v8::internal::RegExpAssertion, v8::internal::RegExpAlternative, and v8::internal::RegExpDisjunction.
Referenced by v8::internal::RegExpImpl::Compile(), v8::internal::RegExpAlternative::RegExpAlternative(), v8::internal::RegExpDisjunction::RegExpDisjunction(), v8::internal::RegExpQuantifier::RegExpQuantifier(), and v8::internal::RegExpCapture::set_body().
Print()
std::ostream & v8::internal::RegExpTree::Print (std::ostream & os, Zone * zone)
Definition at line 344 of file regexp-ast.cc.
                                                        {
  RegExpUnparser unparser(os, zone);
  Accept(&unparser, nullptr);
  return os;
}
References Accept().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::Parse().
ToNode()
virtual RegExpNode* v8::internal::RegExpTree::ToNode (RegExpCompiler * compiler, RegExpNode * on_success) [pure virtual]
Referenced by v8::internal::RegExpCapture::ToNode().
Member Data Documentation
kInfinity
const int v8::internal::RegExpTree::kInfinity = kMaxInt [static]
Definition at line 196 of file regexp-ast.h.
Referenced by v8::internal::anonymous_namespace{regexp-ast.cc}::IncreaseBy(), v8::internal::RegExpBackReference::max_match(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseIntervalQuantifier(), v8::internal::RegExpCompiler::PreprocessRegExp(), v8::internal::RegExpQuantifier::RegExpQuantifier(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitQuantifier(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitQuantifier().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-ast.cc
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc