v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ResultWriter Class Reference
Public Member Functions
ResultWriter (Comparator::Output *output)
void RecordNoModification (const Point &from)
void RecordInsertionOrDeletion (const Point &from)
Private Attributes
Comparator::Output * output_
bool change_is_ongoing_ = false
std::optional< Point > change_start_
Detailed Description
Definition at line 330 of file liveedit-diff.cc.
Constructor & Destructor Documentation
ResultWriter()
v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ResultWriter::ResultWriter (Comparator::Output * output) [inline], [explicit]
Definition at line 332 of file liveedit-diff.cc.
: output_(output) {}
Member Function Documentation
RecordInsertionOrDeletion()
void v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ResultWriter::RecordInsertionOrDeletion (const Point & from) [inline]
Definition at line 344 of file liveedit-diff.cc.
                                                      {
      if (change_is_ongoing_) return;
      // We start a new chunk beginning at `from`.
      change_start_ = from;
      change_is_ongoing_ = true;
    }
Referenced by v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::WriteResult().
RecordNoModification()
void v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ResultWriter::RecordNoModification (const Point & from) [inline]
Definition at line 334 of file liveedit-diff.cc.
                                                 {
      if (!change_is_ongoing_) return;
      // We close the current chunk, going from `change_start_` to `from`.
      CHECK(change_start_);
      output_->AddChunk(change_start_->x, change_start_->y,
                        from.x - change_start_->x, from.y - change_start_->y);
      change_is_ongoing_ = false;
    }
References v8::internal::Comparator::Output::AddChunk(), CHECK, v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::Point::x, and v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::Point::y.
Referenced by v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::WalkDiagonal(), and v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::WriteResult().
Member Data Documentation
change_is_ongoing_
bool v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ResultWriter::change_is_ongoing_ = false [private]
Definition at line 354 of file liveedit-diff.cc.
change_start_
std::optional<Point> v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ResultWriter::change_start_ [private]
Definition at line 355 of file liveedit-diff.cc.
output_
Comparator::Output* v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ResultWriter::output_ [private]
Definition at line 353 of file liveedit-diff.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/liveedit-diff.cc