v8::internal::NegativeLookaroundChoiceNode Class Reference
#include <regexp-nodes.h>
Public Member Functions
NegativeLookaroundChoiceNode (GuardedAlternative this_must_fail, GuardedAlternative then_do_this, Zone *zone)
void GetQuickCheckDetails (QuickCheckDetails *details, RegExpCompiler *compiler, int characters_filled_in, bool not_at_start) override
void FillInBMInfo (Isolate *isolate, int offset, int budget, BoyerMooreLookahead *bm, bool not_at_start) override
RegExpNode * lookaround_node ()
RegExpNode * continue_node ()
bool try_to_emit_quick_check_for_alternative (bool is_first) override
NegativeLookaroundChoiceNode * AsNegativeLookaroundChoiceNode () override
void Accept (NodeVisitor *visitor) override
RegExpNode * FilterOneByte (int depth, RegExpCompiler *compiler) override
Static Public Attributes
static constexpr int kLookaroundIndex = 0
static constexpr int kContinueIndex = 1
Additional Inherited Members
Detailed Description
Definition at line 723 of file regexp-nodes.h.
Constructor & Destructor Documentation
NegativeLookaroundChoiceNode()
v8::internal::NegativeLookaroundChoiceNode::NegativeLookaroundChoiceNode (GuardedAlternative this_must_fail, GuardedAlternative then_do_this, Zone * zone) [inline], [explicit]
Definition at line 725 of file regexp-nodes.h.
      : ChoiceNode(2, zone) {
    AddAlternative(this_must_fail);
    AddAlternative(then_do_this);
  }
Member Function Documentation
Accept()
void v8::internal::NegativeLookaroundChoiceNode::Accept (NodeVisitor * visitor) [override], [virtual]
Reimplemented from v8::internal::ChoiceNode.
AsNegativeLookaroundChoiceNode()
NegativeLookaroundChoiceNode* v8::internal::NegativeLookaroundChoiceNode::AsNegativeLookaroundChoiceNode () [inline], [override]
Definition at line 757 of file regexp-nodes.h.
                                                                          {
    return this;
  }
continue_node()
RegExpNode* v8::internal::NegativeLookaroundChoiceNode::continue_node () [inline]
Definition at line 746 of file regexp-nodes.h.
                              {
    return alternatives()->at(kContinueIndex).node();
  }
Referenced by FilterOneByte(), GetQuickCheckDetails(), v8::internal::Analysis< Propagators >::VisitNegativeLookaroundChoice(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitNegativeLookaroundChoiceContinueNode().
FillInBMInfo()
void v8::internal::NegativeLookaroundChoiceNode::FillInBMInfo (Isolate * isolate, int offset, int budget, BoyerMooreLookahead * bm, bool not_at_start) [inline], [override], [virtual]
Reimplemented from v8::internal::ChoiceNode.
Definition at line 735 of file regexp-nodes.h.
                                                                         {
    continue_node()->FillInBMInfo(isolate, offset, budget - 1, bm,
                                  not_at_start);
    if (offset == 0) set_bm_info(not_at_start, bm);
  }
FilterOneByte()
RegExpNode * v8::internal::NegativeLookaroundChoiceNode::FilterOneByte (int depth, RegExpCompiler * compiler) [override], [virtual]
Reimplemented from v8::internal::ChoiceNode.
Definition at line 2070 of file regexp-compiler.cc.
                                         {
  if (info()->replacement_calculated) return replacement();
  if (depth < 0) return this;
  if (info()->visited) return this;
  VisitMarker marker(info());
  // Alternative 0 is the negative lookahead, alternative 1 is what comes
  // afterwards.
  RegExpNode* node = continue_node();
  RegExpNode* replacement = node->FilterOneByte(depth - 1, compiler);
  if (replacement == nullptr) return set_replacement(nullptr);
  alternatives_->at(kContinueIndex).set_node(replacement);
  RegExpNode* neg_node = lookaround_node();
  RegExpNode* neg_replacement = neg_node->FilterOneByte(depth - 1, compiler);
  // If the negative lookahead is always going to fail then
  // we don't need to check it.
  if (neg_replacement == nullptr) return set_replacement(replacement);
  alternatives_->at(kLookaroundIndex).set_node(neg_replacement);
  return set_replacement(this);
}
References v8::internal::ChoiceNode::alternatives_, continue_node(), v8::internal::RegExpNode::FilterOneByte(), v8::internal::RegExpNode::info(), kContinueIndex, kLookaroundIndex, lookaround_node(), v8::internal::RegExpNode::replacement(), and v8::internal::RegExpNode::set_replacement().
GetQuickCheckDetails()
void v8::internal::NegativeLookaroundChoiceNode::GetQuickCheckDetails (QuickCheckDetails * details, RegExpCompiler * compiler, int characters_filled_in, bool not_at_start) [override], [virtual]
Reimplemented from v8::internal::ChoiceNode.
Definition at line 1465 of file regexp-compiler.cc.
                       {
  RegExpNode* node = continue_node();
  return node->GetQuickCheckDetails(details, compiler, filled_in, not_at_start);
}
References continue_node(), v8::internal::RegExpNode::GetQuickCheckDetails(), and v8::internal::ChoiceNode::not_at_start().
lookaround_node()
RegExpNode* v8::internal::NegativeLookaroundChoiceNode::lookaround_node () [inline]
Definition at line 743 of file regexp-nodes.h.
                                {
    return alternatives()->at(kLookaroundIndex).node();
  }
Referenced by FilterOneByte(), and v8::internal::Analysis< Propagators >::VisitNegativeLookaroundChoice().
try_to_emit_quick_check_for_alternative()
bool v8::internal::NegativeLookaroundChoiceNode::try_to_emit_quick_check_for_alternative (bool is_first) [inline], [override], [virtual]
Reimplemented from v8::internal::ChoiceNode.
Definition at line 754 of file regexp-nodes.h.
                                                                       {
    return !is_first;
  }
Member Data Documentation
kContinueIndex
constexpr int v8::internal::NegativeLookaroundChoiceNode::kContinueIndex = 1 [static], [constexpr]
Definition at line 742 of file regexp-nodes.h.
Referenced by FilterOneByte(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitNegativeLookaroundChoiceContinueNode().
kLookaroundIndex
constexpr int v8::internal::NegativeLookaroundChoiceNode::kLookaroundIndex = 0 [static], [constexpr]
Definition at line 741 of file regexp-nodes.h.
Referenced by FilterOneByte(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitNegativeLookaroundChoiceLookaroundNode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-nodes.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc