v8::internal::MemoryChunk Class Reference
#include <memory-chunk.h>
Public Types
enum Flag : uintptr_t {
NO_FLAGS = 0u
, IN_WRITABLE_SHARED_SPACE = 1u << 0
, POINTERS_TO_HERE_ARE_INTERESTING = 1u << 1
, POINTERS_FROM_HERE_ARE_INTERESTING = 1u << 2
,
FROM_PAGE = 1u << 3
, TO_PAGE = 1u << 4
, INCREMENTAL_MARKING = 1u << 5
, READ_ONLY_HEAP = 1u << 6
,
IS_MAJOR_GC_IN_PROGRESS = 1u << 7
, CONTAINS_ONLY_OLD = 1u << 8
, BLACK_ALLOCATED = 1u << 9
, LARGE_PAGE = 1u << 10
,
EVACUATION_CANDIDATE = 1u << 11
, NEVER_EVACUATE = 1u << 12
, PAGE_NEW_OLD_PROMOTION = 1u << 13
, FORCE_EVACUATION_CANDIDATE_FOR_TESTING = 1u << 14
,
NEVER_ALLOCATE_ON_PAGE = 1u << 15
, PRE_FREED = 1u << 16
, COMPACTION_WAS_ABORTED = 1u << 17
, NEW_SPACE_BELOW_AGE_MARK = 1u << 18
,
UNREGISTERED = 1u << 19
, PINNED = 1u << 20
, IS_EXECUTABLE = 1u << 21
, IS_TRUSTED = 1u << 22
,
IS_QUARANTINED = 1u << 23
, WILL_BE_PROMOTED = 1u << 24
 }
using MainThreadFlags = base::Flags< Flag, uintptr_t >
Public Member Functions
MemoryChunk (MainThreadFlags flags, MemoryChunkMetadata *metadata)
Address address () const
MemoryChunkMetadata * Metadata ()
const MemoryChunkMetadata * Metadata () const
bool IsFlagSet (Flag flag) const
bool IsMarking () const
bool InWritableSharedSpace () const
bool InYoungGeneration () const
bool IsYoungOrSharedChunk () const
void SetFlagSlow (Flag flag)
void ClearFlagSlow (Flag flag)
MainThreadFlags GetFlags () const
void SetFlagUnlocked (Flag flag)
void ClearFlagUnlocked (Flag flag)
void ClearFlagsUnlocked (MainThreadFlags flags)
void SetFlagsUnlocked (MainThreadFlags flags, MainThreadFlags mask=kAllFlagsMask)
void SetFlagNonExecutable (Flag flag)
void ClearFlagNonExecutable (Flag flag)
void SetFlagsNonExecutable (MainThreadFlags flags, MainThreadFlags mask=kAllFlagsMask)
void ClearFlagsNonExecutable (MainThreadFlags flags)
void SetMajorGCInProgress ()
void ResetMajorGCInProgress ()
Heap * GetHeap ()
void InitializationMemoryFence ()
bool InReadOnlySpace () const
bool InCodeSpace () const
bool InTrustedSpace () const
bool NeverEvacuate () const
void MarkNeverEvacuate ()
bool CanAllocate () const
bool IsEvacuationCandidate () const
bool ShouldSkipEvacuationSlotRecording () const
Executability executable () const
bool IsFromPage () const
bool IsToPage () const
bool IsLargePage () const
bool InNewSpace () const
bool InNewLargeObjectSpace () const
bool IsPinned () const
bool IsOnlyOldOrMajorMarkingOn () const
bool IsQuarantined () const
void SetOldGenerationPageFlags (MarkingMode marking_mode, AllocationSpace space)
void SetYoungGenerationPageFlags (MarkingMode marking_mode)
bool IsTrusted () const
size_t Offset (Address addr) const
size_t OffsetMaybeOutOfRange (Address addr) const
Static Public Member Functions
static constexpr Address BaseAddress (Address a)
static MemoryChunk * FromAddress (Address addr)
template<typename HeapObject >
static MemoryChunk * FromHeapObject (Tagged< HeapObject > object)
static constexpr bool IsAligned (Address address)
static MainThreadFlags OldGenerationPageFlags (MarkingMode marking_mode, AllocationSpace space)
static MainThreadFlags YoungGenerationPageFlags (MarkingMode marking_mode)
static intptr_t GetAlignmentForAllocation ()
static constexpr intptr_t GetAlignmentMaskForAssembler ()
static constexpr uint32_t AddressToOffset (Address address)
Static Public Attributes
static constexpr MainThreadFlags kAllFlagsMask = ~MainThreadFlags(NO_FLAGS)
static constexpr MainThreadFlags kPointersToHereAreInterestingMask
static constexpr MainThreadFlags kPointersFromHereAreInterestingMask
static constexpr MainThreadFlags kEvacuationCandidateMask
static constexpr MainThreadFlags kIsInYoungGenerationMask
static constexpr MainThreadFlags kIsInReadOnlyHeapMask = READ_ONLY_HEAP
static constexpr MainThreadFlags kIsLargePageMask = LARGE_PAGE
static constexpr MainThreadFlags kInSharedHeap = IN_WRITABLE_SHARED_SPACE
static constexpr MainThreadFlags kIncrementalMarking = INCREMENTAL_MARKING
static constexpr MainThreadFlags kSkipEvacuationSlotsRecordingMask
static constexpr MainThreadFlags kIsOnlyOldOrMajorGCInProgressMask
Static Private Member Functions
static constexpr intptr_t FlagsOffset ()
static constexpr intptr_t MetadataOffset ()
Private Attributes
MainThreadFlags main_thread_flags_
MemoryChunkMetadata * metadata_
Static Private Attributes
static constexpr intptr_t kAlignment
static constexpr intptr_t kAlignmentMask = kAlignment - 1
Friends
class CodeStubAssembler
class MacroAssembler
template<typename Next >
class compiler::turboshaft::TurboshaftAssemblerOpInterface
Detailed Description
Definition at line 45 of file memory-chunk.h.
Member Typedef Documentation
MainThreadFlags
using v8::internal::MemoryChunk::MainThreadFlags = base::Flags<Flag, uintptr_t>
Definition at line 147 of file memory-chunk.h.
Member Enumeration Documentation
Flag
enum v8::internal::MemoryChunk::Flag : uintptr_t
Enumerator
NO_FLAGS
IN_WRITABLE_SHARED_SPACE
POINTERS_TO_HERE_ARE_INTERESTING
POINTERS_FROM_HERE_ARE_INTERESTING
FROM_PAGE
TO_PAGE
INCREMENTAL_MARKING
READ_ONLY_HEAP
IS_MAJOR_GC_IN_PROGRESS
CONTAINS_ONLY_OLD
BLACK_ALLOCATED
LARGE_PAGE
EVACUATION_CANDIDATE
NEVER_EVACUATE
PAGE_NEW_OLD_PROMOTION
FORCE_EVACUATION_CANDIDATE_FOR_TESTING
NEVER_ALLOCATE_ON_PAGE
PRE_FREED
COMPACTION_WAS_ABORTED
NEW_SPACE_BELOW_AGE_MARK
UNREGISTERED
PINNED
IS_EXECUTABLE
IS_TRUSTED
IS_QUARANTINED
WILL_BE_PROMOTED
Definition at line 50 of file memory-chunk.h.
            : uintptr_t {
    NO_FLAGS = 0u,
    // This page belongs to a shared heap.
    IN_WRITABLE_SHARED_SPACE = 1u << 0,
    // These two flags are used in the write barrier to catch "interesting"
    // references.
    POINTERS_TO_HERE_ARE_INTERESTING = 1u << 1,
    POINTERS_FROM_HERE_ARE_INTERESTING = 1u << 2,
    // A page in the from-space or a young large page that was not scavenged
    // yet.
    FROM_PAGE = 1u << 3,
    // A page in the to-space or a young large page that was scavenged.
    TO_PAGE = 1u << 4,
    // |INCREMENTAL_MARKING|: Indicates whether incremental marking is currently
    // enabled.
    INCREMENTAL_MARKING = 1u << 5,
    // The memory chunk belongs to the read-only heap and does not participate
    // in garbage collection. This is used instead of owner for identity
    // checking since read-only chunks have no owner once they are detached.
    READ_ONLY_HEAP = 1u << 6,
    // Used in young generation checks. When sticky mark-bits are enabled and
    // major GC in progress, treat all objects as old.
    IS_MAJOR_GC_IN_PROGRESS = 1u << 7,
    // Used to mark chunks belonging to spaces that do not suppor young gen
    // allocations. Such chunks can never contain any young objects.
    CONTAINS_ONLY_OLD = 1u << 8,
    // Page was allocated during major incremental marking. May only contain old
    // objects.
    BLACK_ALLOCATED = 1u << 9,
    // ----------------------------------------------------------------
    // Values below here are not critical for the heap write barrier.
    LARGE_PAGE = 1u << 10,
    EVACUATION_CANDIDATE = 1u << 11,
    NEVER_EVACUATE = 1u << 12,
    // |PAGE_NEW_OLD_PROMOTION|: A page tagged with this flag has been promoted
    // from new to old space during evacuation.
    PAGE_NEW_OLD_PROMOTION = 1u << 13,
    // This flag is intended to be used for testing. Works only when both
    // v8_flags.stress_compaction and
    // v8_flags.manual_evacuation_candidates_selection are set. It forces the
    // page to become an evacuation candidate at next candidates selection
    // cycle.
    FORCE_EVACUATION_CANDIDATE_FOR_TESTING = 1u << 14,
    // This flag is intended to be used for testing.
    NEVER_ALLOCATE_ON_PAGE = 1u << 15,
    // The memory chunk is already logically freed, however the actual freeing
    // still has to be performed.
    PRE_FREED = 1u << 16,
    // |COMPACTION_WAS_ABORTED|: Indicates that the compaction in this page
    // has been aborted and needs special handling by the sweeper.
    COMPACTION_WAS_ABORTED = 1u << 17,
    NEW_SPACE_BELOW_AGE_MARK = 1u << 18,
    // The memory chunk freeing bookkeeping has been performed but the chunk has
    // not yet been freed.
    UNREGISTERED = 1u << 19,
    // The memory chunk is pinned in memory and can't be moved. This is likely
    // because there exists a potential pointer to somewhere in the chunk which
    // can't be updated.
    PINNED = 1u << 20,
    // A Page with code objects.
    IS_EXECUTABLE = 1u << 21,
    // The memory chunk belongs to the trusted space. When the sandbox is
    // enabled, the trusted space is located outside of the sandbox and so its
    // content cannot be corrupted by an attacker.
    IS_TRUSTED = 1u << 22,
    // A quarantined page that contains objects reachable from stack during a
    // scavenge. Quarantined pages are not used for further allocations in new
    // space (to make it easier to keep track of the intermediate generation).
    // This flag should only ever be set during a scavenge cycle.
    IS_QUARANTINED = 1u << 23,
    // A new space page that will be promoted to old space by the end of the GC.
    // This flag should only ever be set during a scavenge cycle.
    WILL_BE_PROMOTED = 1u << 24,
  };
Constructor & Destructor Documentation
MemoryChunk()
v8::internal::MemoryChunk::MemoryChunk (MainThreadFlags flags, MemoryChunkMetadata * metadata)
Definition at line 43 of file memory-chunk.cc.
    : main_thread_flags_(flags)
#ifndef V8_ENABLE_SANDBOX
      ,
      metadata_(metadata)
#endif
{
#ifdef V8_ENABLE_SANDBOX
  auto metadata_index = MetadataTableIndex(address());
  MemoryChunkMetadata** metadata_pointer_table = MetadataTableAddress();
  DCHECK_IMPLIES(metadata_pointer_table[metadata_index] != nullptr,
                 metadata_pointer_table[metadata_index] == metadata);
  metadata_pointer_table[metadata_index] = metadata;
  metadata_index_ = metadata_index;
#endif
}
References address(), and DCHECK_IMPLIES.
Member Function Documentation
address()
Address v8::internal::MemoryChunk::address () const [inline]
Definition at line 171 of file memory-chunk.h.
{ return reinterpret_cast<Address>(this); }
Referenced by v8::internal::SemiSpace::AddRangeToActiveSystemPages(), v8::internal::PagedSpaceBase::AddRangeToActiveSystemPages(), v8::internal::LiveObjectRange::iterator::AdvanceToNextMarkedObject(), v8::internal::RememberedSetOperations::CheckNoneInRange(), v8::internal::MemoryChunkMetadata::ChunkAddress(), v8::internal::MarkingBitmap::FindPreviousValidObject(), v8::internal::SemiSpaceNewSpace::IsAddressBelowAgeMark(), MemoryChunk(), v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlot(), v8::internal::MarkCompactCollector::RecordSlot(), v8::internal::LargeObjectSpace::ShrinkPageToObjectSize(), and v8::internal::MemoryAllocator::UnregisterMemoryChunk().
AddressToOffset()
static constexpr uint32_t v8::internal::MemoryChunk::AddressToOffset (Address address) [inline], [static], [constexpr]
Definition at line 353 of file memory-chunk.h.
                                                             {
    return static_cast<uint32_t>(address) & kAlignmentMask;
  }
References v8::kAlignmentMask.
Referenced by v8::internal::MarkingBitmap::AddressToIndex(), v8::internal::Scavenger::HandleLargeObject(), and v8::internal::ObjectAddressForHashing().
BaseAddress()
static constexpr Address v8::internal::MemoryChunk::BaseAddress (Address a) [inline], [static], [constexpr]
Definition at line 173 of file memory-chunk.h.
                                                  {
    // LINT.IfChange
    // If this changes, we also need to update
    // - CodeStubAssembler::MemoryChunkFromAddress
    // - MacroAssembler::MemoryChunkHeaderFromObject
    // - TurboshaftAssemblerOpInterface::MemoryChunkFromAddress
    return a & ~kAlignmentMask;
    // clang-format off
    // LINT.ThenChange(src/codegen/code-stub-assembler.cc, src/codegen/ia32/macro-assembler-ia32.cc, src/codegen/x64/macro-assembler-x64.cc, src/compiler/turboshaft/assembler.h)
    // clang-format on
  }
References v8::kAlignmentMask.
CanAllocate()
bool v8::internal::MemoryChunk::CanAllocate () const [inline]
Definition at line 287 of file memory-chunk.h.
                           {
    return !IsEvacuationCandidate() && !IsFlagSet(NEVER_ALLOCATE_ON_PAGE);
  }
Referenced by v8::internal::MarkCompactCollector::CollectEvacuationCandidates().
ClearFlagNonExecutable()
void v8::internal::MemoryChunk::ClearFlagNonExecutable (Flag flag) [inline]
Definition at line 243 of file memory-chunk.h.
                                                   {
    return ClearFlagUnlocked(flag);
  }
Referenced by ClearFlagSlow(), v8::internal::MarkCompactCollector::Evacuate(), v8::internal::SemiSpace::FixPagesFlags(), v8::internal::NewLargeObjectSpace::Flip(), v8::internal::SemiSpace::MoveQuarantinedPage(), v8::internal::OldLargeObjectSpace::PromoteNewLargeObject(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), and v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace().
ClearFlagSlow()
void v8::internal::MemoryChunk::ClearFlagSlow (Flag flag)
Definition at line 189 of file memory-chunk.cc.
                                         {
  if (executable()) {
    RwxMemoryWriteScope scope("Clear a MemoryChunk flag in executable memory.");
    ClearFlagUnlocked(flag);
  } else {
    ClearFlagNonExecutable(flag);
  }
}
References ClearFlagNonExecutable(), ClearFlagUnlocked(), and executable().
Referenced by v8::internal::PageMetadata::ClearEvacuationCandidate(), v8::internal::MarkCompactCollector::CollectEvacuationCandidates(), and v8::internal::MarkCompactCollector::Evacuate().
ClearFlagsNonExecutable()
void v8::internal::MemoryChunk::ClearFlagsNonExecutable (MainThreadFlags flags) [inline]
Definition at line 250 of file memory-chunk.h.
                                                                {
    return ClearFlagsUnlocked(flags);
  }
References v8::internal::flags.
Referenced by v8::internal::PageMetadata::ConvertNewToOld(), and SetYoungGenerationPageFlags().
ClearFlagsUnlocked()
void v8::internal::MemoryChunk::ClearFlagsUnlocked (MainThreadFlags flags) [inline]
Definition at line 232 of file memory-chunk.h.
                                                           {
    main_thread_flags_ &= ~flags;
  }
References v8::internal::flags.
Referenced by SetOldGenerationPageFlags().
ClearFlagUnlocked()
void v8::internal::MemoryChunk::ClearFlagUnlocked (Flag flag) [inline]
Definition at line 227 of file memory-chunk.h.
                                              {
    main_thread_flags_ = main_thread_flags_.without(flag);
  }
Referenced by ClearFlagSlow(), and v8::internal::MarkCompactCollector::ResetAndRelinkBlackAllocatedPage().
executable()
Executability v8::internal::MemoryChunk::executable () const [inline]
Definition at line 302 of file memory-chunk.h.
                                   {
    return IsFlagSet(IS_EXECUTABLE) ? EXECUTABLE : NOT_EXECUTABLE;
  }
References v8::internal::EXECUTABLE, and v8::internal::NOT_EXECUTABLE.
Referenced by v8::internal::PagePool::Add(), v8::internal::MemoryAllocator::AllocateLargePage(), v8::internal::MemoryAllocator::AllocatePage(), ClearFlagSlow(), v8::internal::MemoryAllocator::Free(), v8::internal::Scavenger::ScavengePage(), SetFlagSlow(), v8::internal::LargeObjectSpace::ShrinkPageToObjectSize(), v8::internal::MemoryAllocator::UnregisterMutableMemoryChunk(), v8::internal::MemoryAllocator::UnregisterReadOnlyPage(), v8::internal::MarkCompactCollector::UpdatePointersInClientHeap(), and v8::internal::Sweeper::ZeroOrDiscardUnusedMemory().
FlagsOffset()
static constexpr intptr_t v8::internal::MemoryChunk::FlagsOffset () [inline], [static], [constexpr], [private]
Definition at line 374 of file memory-chunk.h.
                                          {
    return offsetof(MemoryChunk, main_thread_flags_);
  }
Referenced by v8::internal::MacroAssembler::CheckPageFlag(), v8::internal::CodeStubAssembler::ExtractToFixedArray(), v8::internal::CodeStubAssembler::IsPageFlagReset(), v8::internal::CodeStubAssembler::IsPageFlagSet(), v8::internal::CodeStubAssembler::LoadMemoryChunkFlags(), and v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadPageFlags().
FromAddress()
static MemoryChunk* v8::internal::MemoryChunk::FromAddress (Address addr) [inline], [static]
Definition at line 185 of file memory-chunk.h.
                                                          {
    return reinterpret_cast<MemoryChunk*>(BaseAddress(addr));
  }
Referenced by v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::Heap::ClearRecordedSlotRange(), v8::internal::ReadOnlyHeap::Contains(), v8::internal::LargeObjectSpace::ContainsSlow(), v8::internal::PagedSpaceBase::ContainsSlow(), v8::internal::ReadOnlySpace::ContainsSlow(), v8::internal::Heap::CreateFillerObjectAt(), v8::internal::PretenuringHandler::FindAllocationMemento(), v8::internal::MemoryChunkMetadata::FromAddress(), v8::internal::PageMetadata::FromAddress(), v8::internal::SemiSpaceNewSpace::IsAddressBelowAgeMark(), v8::internal::MarkCompactCollector::IsOnEvacuationCandidate(), v8::internal::MemoryAllocator::LookupChunkContainingAddressInSafepoint(), v8::internal::PageMetadata::OnSamePage(), v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlot(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::ShouldFlushBaselineCode(), and v8::internal::Heap::AllocationTrackerForDebugging::UpdateAllocationsHash().
FromHeapObject()
template<typename HeapObject >
static MemoryChunk* v8::internal::MemoryChunk::FromHeapObject (Tagged< HeapObject > object) [inline], [static]
Definition at line 190 of file memory-chunk.h.
                                                                          {
    return FromAddress(object.ptr());
  }
Referenced by v8::internal::Heap::CanReferenceHeapObject(), v8::internal::Scavenger::CheckAndScavengeObject(), v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::CheckForSharedObject(), v8::internal::WriteBarrier::CombinedGenerationalAndSharedBarrierSlow(), v8::internal::WriteBarrier::CombinedGenerationalAndSharedEphemeronBarrierSlow(), v8::internal::WriteBarrier::CombinedWriteBarrierInternal(), v8::internal::SemiSpace::Contains(), v8::internal::NewSpace::Contains(), v8::internal::anonymous_namespace{heap.cc}::CopyOrMoveRangeImpl(), v8::internal::Heap::EnsureSweepingCompletedForObject(), v8::internal::WriteBarrier::ForEphemeronHashTable(), v8::internal::WriteBarrier::ForIndirectPointer(), v8::internal::WriteBarrier::ForProtectedPointer(), v8::internal::WriteBarrier::ForRange(), v8::internal::WriteBarrier::GenerationalBarrierForCppHeapPointer(), v8::internal::WriteBarrier::GenerationalBarrierSlow(), v8::internal::GetHeapFromWritableObject(), v8::internal::GetIsolateFromHeapObject(), v8::internal::MarkingHelper::GetLivenessMode(), v8::internal::HeapUtils::GetOwnerHeap(), v8::internal::V8HeapExplorer::GetSystemEntryType(), v8::internal::WriteBarrier::GetWriteBarrierModeForObject(), v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::HandleHeapObject(), v8::internal::Scavenger::HandleLargeObject(), v8::internal::anonymous_namespace{scavenger.cc}::PreciseObjectPinningVisitor::HandlePointer(), v8::internal::IterateAndScavengePromotedObjectsVisitor::HandleSlot(), v8::internal::HeapLayout::InBlackAllocatedPage(), v8::internal::HeapLayout::InCodeSpace(), v8::internal::Heap::InFromPage(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::Heap::InToPage(), v8::internal::HeapLayout::InTrustedSpace(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::Heap::IsImmovable(), v8::internal::Heap::IsLargeObject(), v8::internal::WriteBarrier::IsMarking(), v8::internal::HeapLayout::IsOwnedByAnyHeap(), v8::internal::Heap::IsPendingAllocationInternal(), v8::internal::V8HeapExplorer::IterateAndExtractReferences(), v8::internal::Scavenger::IterateAndScavengePromotedObject(), v8::internal::WriteBarrier::MarkingSlow(), v8::internal::MarkingBarrier::MarkRange(), v8::internal::MarkCompactCollector::MarkRootObject(), v8::internal::MarkingBarrier::MarkValue(), v8::internal::OutsideSandboxOrInReadonlySpace(), v8::internal::WriteBarrier::PageFlagsAreConsistent(), v8::internal::FreeListCategory::PickNodeFromList(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::ProcessStrongHeapObject(), v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlot(), v8::internal::MarkCompactCollector::RecordSlot(), v8::internal::anonymous_namespace{scavenger.cc}::RestorePinnedObjects(), v8::internal::ReadOnlyHeap::SandboxSafeContains(), v8::internal::Scavenger::ScavengeObject(), v8::internal::FreeListCategory::SearchForNodeInList(), v8::internal::WriteBarrier::SharedForRelocInfo(), v8::internal::WriteBarrier::SharedHeapBarrierSlow(), v8::internal::WriteBarrier::SharedSlow(), v8::internal::MarkingHelper::ShouldMarkObject(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::SynchronizePageAccess(), v8::internal::Scavenger::SynchronizePageAccess(), v8::internal::PretenuringHandler::UpdateAllocationSite(), v8::internal::anonymous_namespace{scavenger.cc}::GlobalHandlesWeakRootsUpdatingVisitor::UpdatePointer(), v8::internal::HeapEntry::VerifyReference(), v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitEphemeronHashTable(), v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitObjectImpl(), v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitObjectViaSlot(), v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlot(), and v8::internal::MarkingBarrier::Write().
GetAlignmentForAllocation()
static intptr_t v8::internal::MemoryChunk::GetAlignmentForAllocation () [inline], [static]
Definition at line 344 of file memory-chunk.h.
{ return kAlignment; }
Referenced by v8::internal::MemoryAllocator::AllocateUninitializedChunkAt().
GetAlignmentMaskForAssembler()
static constexpr intptr_t v8::internal::MemoryChunk::GetAlignmentMaskForAssembler () [inline], [static], [constexpr]
Definition at line 349 of file memory-chunk.h.
                                                           {
    return kAlignmentMask;
  }
References v8::kAlignmentMask.
Referenced by v8::internal::MacroAssembler::CheckPageFlag(), v8::internal::CodeStubAssembler::GetMarkBit(), and v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::MemoryChunkFromAddress().
GetFlags()
MainThreadFlags v8::internal::MemoryChunk::GetFlags () const [inline]
Definition at line 224 of file memory-chunk.h.
{ return main_thread_flags_; }
Referenced by v8::internal::HeapLayout::InBlackAllocatedPage().
GetHeap()
Heap * v8::internal::MemoryChunk::GetHeap () [inline]
Definition at line 40 of file memory-chunk-inl.h.
{ return Metadata()->heap(); }
References v8::internal::MemoryChunkMetadata::heap(), and Metadata().
Referenced by v8::internal::Heap::CanReferenceHeapObject(), v8::internal::GetHeapFromWritableObject(), v8::internal::GetIsolateFromHeapObject(), v8::internal::HeapUtils::GetOwnerHeap(), v8::internal::HeapLayout::IsOwnedByAnyHeap(), and v8::internal::MarkCompactCollector::RecordSlot().
InCodeSpace()
bool v8::internal::MemoryChunk::InCodeSpace () const [inline]
Definition at line 280 of file memory-chunk.h.
{ return IsFlagSet(IS_EXECUTABLE); }
Referenced by v8::internal::HeapLayout::InCodeSpace(), and v8::internal::MarkCompactCollector::ResetAndRelinkBlackAllocatedPage().
InitializationMemoryFence()
void v8::internal::MemoryChunk::InitializationMemoryFence ()
Definition at line 100 of file memory-chunk.cc.
                                            {
  base::SeqCst_MemoryFence();
#ifdef THREAD_SANITIZER
  // Since TSAN does not process memory fences, we use the following annotation
  // to tell TSAN that there is no data race when emitting a
  // InitializationMemoryFence. Note that the other thread still needs to
  // perform MutablePageMetadata::synchronized_heap().
  Metadata()->SynchronizedHeapStore();
#ifndef V8_ENABLE_SANDBOX
  base::Release_Store(reinterpret_cast<base::AtomicWord*>(&metadata_),
                      reinterpret_cast<base::AtomicWord>(metadata_));
#else
  MemoryChunkMetadata** metadata_pointer_table = MetadataTableAddress();
  static_assert(sizeof(base::AtomicWord) == sizeof(metadata_pointer_table[0]));
  static_assert(sizeof(base::Atomic32) == sizeof(metadata_index_));
  base::Release_Store(reinterpret_cast<base::AtomicWord*>(
                          &metadata_pointer_table[metadata_index_]),
                      reinterpret_cast<base::AtomicWord>(
                          metadata_pointer_table[metadata_index_]));
  base::Release_Store(reinterpret_cast<base::Atomic32*>(&metadata_index_),
                      metadata_index_);
#endif
#endif
}
References Metadata(), metadata_, v8::base::Release_Store(), and v8::base::SeqCst_MemoryFence().
Referenced by v8::internal::NewLargeObjectSpace::AllocateRaw(), v8::internal::OldLargeObjectSpace::AllocateRaw(), v8::internal::SemiSpace::InitializePage(), v8::internal::PagedSpaceForNewSpace::InitializePage(), v8::internal::PagedSpaceBase::InitializePage(), and v8::internal::PagedSpaceBase::MergeCompactionSpace().
InNewLargeObjectSpace()
bool v8::internal::MemoryChunk::InNewLargeObjectSpace () const [inline]
Definition at line 316 of file memory-chunk.h.
                                     {
    return InYoungGeneration() && IsLargePage();
  }
InNewSpace()
bool v8::internal::MemoryChunk::InNewSpace () const [inline]
Definition at line 315 of file memory-chunk.h.
{ return InYoungGeneration() && !IsLargePage(); }
Referenced by v8::internal::NewSpace::Contains(), v8::internal::PageMetadata::ConvertNewToOld(), and v8::internal::Evacuator::EvacuatePage().
InReadOnlySpace()
bool v8::internal::MemoryChunk::InReadOnlySpace () const [inline]
Definition at line 270 of file memory-chunk.h.
{ return IsFlagSet(READ_ONLY_HEAP); }
Referenced by v8::internal::Heap::CanReferenceHeapObject(), v8::internal::ReadOnlyHeap::Contains(), v8::internal::MemoryAllocator::DeleteMemoryChunk(), v8::internal::Heap::EnsureSweepingCompletedForObject(), v8::internal::GetIsolateFromHeapObject(), v8::internal::PrecisePagePinningVisitor::HandlePointer(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::Heap::IsPendingAllocationInternal(), v8::internal::MemoryChunkMetadata::IsWritable(), v8::internal::V8HeapExplorer::IterateAndExtractReferences(), and v8::internal::MemoryAllocator::PerformFreeMemory().
InTrustedSpace()
bool v8::internal::MemoryChunk::InTrustedSpace () const [inline]
Definition at line 282 of file memory-chunk.h.
{ return IsFlagSet(IS_TRUSTED); }
Referenced by v8::internal::HeapLayout::InTrustedSpace().
InWritableSharedSpace()
bool v8::internal::MemoryChunk::InWritableSharedSpace () const [inline]
Definition at line 204 of file memory-chunk.h.
                                               {
    return IsFlagSet(IN_WRITABLE_SHARED_SPACE);
  }
Referenced by v8::internal::Heap::CanReferenceHeapObject(), v8::internal::WriteBarrier::ForRange(), v8::internal::GetHeapFromWritableObject(), v8::internal::PrecisePagePinningVisitor::HandlePointer(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::WriteBarrier::PageFlagsAreConsistent(), v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlot(), v8::internal::MarkCompactCollector::RecordSlot(), v8::internal::WriteBarrier::SharedForRelocInfo(), v8::internal::WriteBarrier::SharedHeapBarrierSlow(), and v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitObjectImpl().
InYoungGeneration()
bool v8::internal::MemoryChunk::InYoungGeneration () const [inline]
Definition at line 208 of file memory-chunk.h.
                                           {
    UNREACHABLE_WITH_STICKY_MARK_BITS();
    constexpr uintptr_t kYoungGenerationMask = FROM_PAGE | TO_PAGE;
    return GetFlags() & kYoungGenerationMask;
  }
References UNREACHABLE_WITH_STICKY_MARK_BITS.
Referenced by v8::internal::Heap::ClearRecordedSlotRange(), v8::internal::Evacuator::ComputeEvacuationMode(), v8::internal::SemiSpace::FixPagesFlags(), v8::internal::WriteBarrier::ForProtectedPointer(), v8::internal::PrecisePagePinningVisitor::HandlePointer(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::SemiSpaceNewSpace::IsAddressBelowAgeMark(), v8::internal::MarkCompactCollector::MarkRootObject(), v8::internal::WriteBarrier::PageFlagsAreConsistent(), v8::internal::NewSpace::PromotePageToOldSpace(), v8::internal::anonymous_namespace{scavenger.cc}::QuarantinePinnedPages(), v8::internal::Scavenger::ScavengeObject(), v8::internal::MarkCompactCollector::UpdatePointersInClientHeap(), v8::internal::Heap::ExternalStringTable::Verify(), v8::internal::Heap::ExternalStringTable::VerifyYoung(), and v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitObjectImpl().
IsAligned()
static constexpr bool v8::internal::MemoryChunk::IsAligned (Address address) [inline], [static], [constexpr]
Definition at line 326 of file memory-chunk.h.
                                                             {
    return (address & kAlignmentMask) == 0;
  }
References v8::kAlignmentMask.
Referenced by v8::internal::LiveObjectRange::iterator::AdvanceToNextMarkedObject(), v8::internal::SemiSpaceNewSpace::Grow(), v8::internal::PageMetadata::IsAlignedToPageSize(), v8::internal::MarkingBitmap::LimitAddressToIndex(), and v8::internal::SemiSpaceNewSpace::Shrink().
IsEvacuationCandidate()
bool v8::internal::MemoryChunk::IsEvacuationCandidate () const [inline]
Definition at line 291 of file memory-chunk.h.
                                     {
    DCHECK(!(IsFlagSet(NEVER_EVACUATE) && IsFlagSet(EVACUATION_CANDIDATE)));
    return IsFlagSet(EVACUATION_CANDIDATE);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::MarkCompactCollector::CollectEvacuationCandidates(), v8::internal::MarkCompactCollector::IsOnEvacuationCandidate(), v8::internal::MarkCompactCollector::MarkRootObject(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), v8::internal::MarkCompactCollector::PostProcessAbortedEvacuationCandidates(), v8::internal::MemoryAllocator::PreFreeMemory(), v8::internal::Sweeper::RawSweep(), v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlot(), v8::internal::MarkCompactCollector::RecordSlot(), v8::internal::MarkCompactCollector::ShouldRecordRelocSlot(), and v8::internal::MarkCompactCollector::StartSweepSpace().
IsFlagSet()
bool v8::internal::MemoryChunk::IsFlagSet (Flag flag) const [inline]
Definition at line 198 of file memory-chunk.h.
                                            {
    return main_thread_flags_ & flag;
  }
Referenced by v8::internal::MarkCompactCollector::AddEvacuationCandidate(), v8::internal::Sweeper::AddPageImpl(), v8::internal::PagedSpaceBase::AddPageImpl(), v8::internal::Scavenger::CheckAndScavengeObject(), v8::internal::HeapLayout::CheckYoungGenerationConsistency(), v8::internal::PageMetadata::ClearEvacuationCandidate(), v8::internal::MarkCompactCollector::CollectEvacuationCandidates(), v8::internal::anonymous_namespace{sweeper.cc}::ComparePagesForSweepingOrder(), v8::internal::Evacuator::ComputeEvacuationMode(), v8::internal::anonymous_namespace{heap.cc}::CopyOrMoveRangeImpl(), v8::internal::MarkCompactCollector::Evacuate(), v8::internal::Evacuator::EvacuatePage(), v8::internal::MarkCompactCollector::EvacuatePagesInParallel(), v8::internal::anonymous_namespace{minor-mark-sweep.cc}::MinorMSConservativeStackVisitor::FilterPage(), v8::internal::MemoryAllocator::FreeReadOnlyPage(), v8::internal::PrecisePagePinningVisitor::HandlePointer(), v8::internal::SemiSpaceNewSpace::IsAddressBelowAgeMark(), v8::internal::PageMetadata::MarkNeverAllocateForTesting(), v8::internal::PagedSpaceBase::MergeCompactionSpace(), v8::internal::SemiSpace::MoveQuarantinedPage(), v8::internal::CompactionSpace::NotifyNewPage(), v8::internal::WriteBarrier::PageFlagsAreConsistent(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), v8::internal::Sweeper::LocalSweeper::ParallelSweepSpace(), v8::internal::MemoryAllocator::PartialFreeMemory(), v8::internal::MemoryAllocator::PerformFreeMemory(), v8::internal::Scavenger::PinAndPushObject(), v8::internal::MarkCompactCollector::PostProcessAbortedEvacuationCandidates(), v8::internal::MemoryAllocator::PreFreeMemory(), v8::internal::Sweeper::PrepareToBeIteratedPromotedPage(), v8::internal::OldLargeObjectSpace::PromoteNewLargeObject(), v8::internal::NewSpace::PromotePageToOldSpace(), v8::internal::anonymous_namespace{scavenger.cc}::QuarantinePinnedPages(), v8::internal::Sweeper::RawSweep(), v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlot(), v8::internal::MarkCompactCollector::RecordSlot(), v8::internal::CompactionSpace::RefillFreeList(), v8::internal::PagedSpaceAllocatorPolicy::RefillLab(), v8::internal::PagedSpaceBase::RelinkFreeListCategories(), v8::internal::PagedSpaceBase::RemovePage(), v8::internal::PagedSpaceBase::RemovePageFromSpaceImpl(), v8::internal::MarkCompactCollector::ReportAbortedEvacuationCandidateDueToFlags(), v8::internal::anonymous_namespace{mark-compact.cc}::ReRecordPage(), v8::internal::MarkCompactCollector::ResetAndRelinkBlackAllocatedPage(), v8::internal::anonymous_namespace{scavenger.cc}::RestorePinnedObjects(), v8::internal::Scavenger::ScavengeObject(), v8::internal::SemiSpaceNewSpace::ShouldPageBePromoted(), v8::internal::MarkCompactCollector::StartSweepNewSpace(), v8::internal::MarkCompactCollector::StartSweepSpace(), v8::internal::MarkCompactCollector::SweepLargeSpace(), v8::internal::MemoryAllocator::UnregisterMemoryChunk(), and v8::internal::PretenuringHandler::UpdateAllocationSite().
IsFromPage()
bool v8::internal::MemoryChunk::IsFromPage () const [inline]
Definition at line 306 of file memory-chunk.h.
                          {
    UNREACHABLE_WITH_STICKY_MARK_BITS();
    return IsFlagSet(FROM_PAGE);
  }
References UNREACHABLE_WITH_STICKY_MARK_BITS.
Referenced by v8::internal::SemiSpace::Contains(), v8::internal::ConservativeStackVisitor::FilterPage(), v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::FilterPage(), v8::internal::PrecisePagePinningVisitor::HandlePointer(), v8::internal::Heap::InFromPage(), v8::internal::SemiSpace::MoveQuarantinedPage(), v8::internal::anonymous_namespace{scavenger.cc}::QuarantinePinnedPages(), v8::internal::SemiSpaceNewSpace::RemovePage(), and v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run().
IsLargePage()
bool v8::internal::MemoryChunk::IsLargePage () const [inline]
Definition at line 314 of file memory-chunk.h.
{ return IsFlagSet(LARGE_PAGE); }
Referenced by v8::internal::PagePool::Add(), v8::internal::Sweeper::AddPromotedPage(), v8::internal::NewLargeObjectSpace::AllocateRaw(), v8::internal::LargePageMetadata::cast(), v8::internal::PageMetadata::cast(), v8::internal::Scavenger::CheckAndScavengeObject(), v8::internal::Heap::ClearRecordedSlotRange(), v8::internal::SemiSpace::Contains(), v8::internal::Heap::EnsureSweepingCompletedForObject(), v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::FindBasePtr(), v8::internal::PrecisePagePinningVisitor::HandlePointer(), v8::internal::SemiSpaceNewSpace::IsAddressBelowAgeMark(), v8::internal::Heap::IsImmovable(), v8::internal::Heap::IsLargeObject(), v8::internal::MarkCompactCollector::MarkRootObject(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), v8::internal::OldLargeObjectSpace::PromoteNewLargeObject(), v8::internal::Evacuator::RawEvacuatePage(), v8::internal::MemoryAllocator::RecordMemoryChunkCreated(), v8::internal::MemoryAllocator::RecordMemoryChunkDestroyed(), v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlot(), and v8::internal::Scavenger::ScavengeObject().
IsMarking()
bool v8::internal::MemoryChunk::IsMarking () const [inline]
Definition at line 202 of file memory-chunk.h.
{ return IsFlagSet(INCREMENTAL_MARKING); }
Referenced by v8::internal::WriteBarrier::CombinedWriteBarrierInternal(), v8::internal::WriteBarrier::ForEphemeronHashTable(), v8::internal::WriteBarrier::GetWriteBarrierModeForObject(), v8::internal::WriteBarrier::IsMarking(), and v8::internal::WriteBarrier::PageFlagsAreConsistent().
IsOnlyOldOrMajorMarkingOn()
bool v8::internal::MemoryChunk::IsOnlyOldOrMajorMarkingOn () const [inline]
Definition at line 320 of file memory-chunk.h.
                                         {
    return GetFlags() & kIsOnlyOldOrMajorGCInProgressMask;
  }
Referenced by v8::internal::HeapLayout::InYoungGenerationForStickyMarkbits().
IsPinned()
bool v8::internal::MemoryChunk::IsPinned () const [inline]
Definition at line 319 of file memory-chunk.h.
{ return IsFlagSet(PINNED); }
Referenced by v8::internal::MarkCompactCollector::CollectEvacuationCandidates().
IsQuarantined()
bool v8::internal::MemoryChunk::IsQuarantined () const [inline]
Definition at line 324 of file memory-chunk.h.
{ return IsFlagSet(IS_QUARANTINED); }
Referenced by v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::HandleHeapObject(), v8::internal::PrecisePagePinningVisitor::HandlePointer(), v8::internal::MarkCompactCollector::MarkRootObject(), v8::internal::SemiSpace::MoveQuarantinedPage(), v8::internal::anonymous_namespace{scavenger.cc}::QuarantinePinnedPages(), v8::internal::anonymous_namespace{scavenger.cc}::RestorePinnedObjects(), and v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run().
IsToPage()
bool v8::internal::MemoryChunk::IsToPage () const [inline]
Definition at line 310 of file memory-chunk.h.
                        {
    UNREACHABLE_WITH_STICKY_MARK_BITS();
    return IsFlagSet(TO_PAGE);
  }
References UNREACHABLE_WITH_STICKY_MARK_BITS.
Referenced by v8::internal::SemiSpace::Contains(), v8::internal::anonymous_namespace{minor-mark-sweep.cc}::MinorMSConservativeStackVisitor::FilterPage(), v8::internal::PrecisePagePinningVisitor::HandlePointer(), v8::internal::Heap::InToPage(), v8::internal::MarkCompactCollector::MarkRootObject(), v8::internal::anonymous_namespace{scavenger.cc}::QuarantinePinnedPages(), v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlot(), v8::internal::SemiSpaceNewSpace::RemovePage(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), and v8::internal::PretenuringHandler::UpdateAllocationSite().
IsTrusted()
bool v8::internal::MemoryChunk::IsTrusted () const [inline]
Definition at line 341 of file memory-chunk.h.
{ return IsFlagSet(IS_TRUSTED); }
Referenced by v8::internal::PagePool::Add().
IsYoungOrSharedChunk()
bool v8::internal::MemoryChunk::IsYoungOrSharedChunk () const [inline]
Definition at line 215 of file memory-chunk.h.
                                              {
    constexpr uintptr_t kYoungOrSharedChunkMask =
        FROM_PAGE | TO_PAGE | IN_WRITABLE_SHARED_SPACE;
    return GetFlags() & kYoungOrSharedChunkMask;
  }
Referenced by v8::internal::WriteBarrier::CombinedWriteBarrierInternal(), and v8::internal::WriteBarrier::ForEphemeronHashTable().
MarkNeverEvacuate()
void v8::internal::MemoryChunk::MarkNeverEvacuate () [inline]
Definition at line 285 of file memory-chunk.h.
{ SetFlagSlow(NEVER_EVACUATE); }
Referenced by v8::internal::Heap::NotifyOldGenerationExpansion().
Metadata() [1/2]
MemoryChunkMetadata * v8::internal::MemoryChunk::Metadata () [inline]
Definition at line 17 of file memory-chunk-inl.h.
                                           {
  // If this changes, we also need to update
  // CodeStubAssembler::PageMetadataFromMemoryChunk
#ifdef V8_ENABLE_SANDBOX
  DCHECK_LT(metadata_index_,
            MemoryChunkConstants::kMetadataPointerTableSizeMask);
  MemoryChunkMetadata** metadata_pointer_table =
      IsolateGroup::current()->metadata_pointer_table();
  MemoryChunkMetadata* metadata = metadata_pointer_table
      [metadata_index_ & MemoryChunkConstants::kMetadataPointerTableSizeMask];
  // Check that the Metadata belongs to this Chunk, since an attacker with write
  // inside the sandbox could've swapped the index.
  SBXCHECK_EQ(metadata->Chunk(), this);
  return metadata;
#else
  return metadata_;
#endif
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::IsolateGroup::current(), DCHECK_LT, metadata_, and SBXCHECK_EQ.
Referenced by v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::CheckForSharedObject(), v8::internal::HeapLayout::CheckYoungGenerationConsistency(), v8::internal::Heap::ClearRecordedSlotRange(), v8::internal::Heap::EnsureSweepingCompletedForObject(), v8::internal::PretenuringHandler::FindAllocationMemento(), v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::FindBasePtr(), v8::internal::anonymous_namespace{heap-write-barrier.cc}::ForRangeImpl(), v8::internal::MemoryChunkMetadata::FromAddress(), v8::internal::PageMetadata::FromAddress(), v8::internal::WriteBarrier::GenerationalBarrierSlow(), GetHeap(), v8::internal::PrecisePagePinningVisitor::HandlePointer(), v8::internal::IterateAndScavengePromotedObjectsVisitor::HandleSlot(), InitializationMemoryFence(), v8::internal::SemiSpaceNewSpace::IsAddressBelowAgeMark(), v8::internal::Heap::IsPendingAllocationInternal(), v8::internal::MemoryAllocator::LookupChunkContainingAddressInSafepoint(), v8::internal::MarkCompactCollector::MarkRootObject(), Metadata(), v8::internal::SemiSpace::MoveQuarantinedPage(), v8::internal::Scavenger::PinAndPushObject(), v8::internal::MarkCompactCollector::ProcessRelocInfo(), v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlot(), v8::internal::MarkCompactCollector::RecordSlot(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), v8::internal::WriteBarrier::SharedHeapBarrierSlow(), v8::internal::SemiSpaceNewSpace::ShouldPageBePromoted(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::SweepPage(), and v8::internal::Heap::AllocationTrackerForDebugging::UpdateAllocationsHash().
Metadata() [2/2]
const MemoryChunkMetadata * v8::internal::MemoryChunk::Metadata () const [inline]
Definition at line 36 of file memory-chunk-inl.h.
                                                       {
  return const_cast<MemoryChunk*>(this)->Metadata();
}
References Metadata().
MetadataOffset()
static constexpr intptr_t v8::internal::MemoryChunk::MetadataOffset () [inline], [static], [constexpr], [private]
Definition at line 406 of file memory-chunk.h.
                                             {
    return offsetof(MemoryChunk, metadata_);
  }
NeverEvacuate()
bool v8::internal::MemoryChunk::NeverEvacuate () const [inline]
Definition at line 284 of file memory-chunk.h.
{ return IsFlagSet(NEVER_EVACUATE); }
Referenced by v8::internal::MarkCompactCollector::AddEvacuationCandidate(), v8::internal::MarkCompactCollector::CollectEvacuationCandidates(), v8::internal::Heap::IsImmovable(), v8::internal::anonymous_namespace{minor-mark-sweep.cc}::ShouldMovePage(), and v8::internal::anonymous_namespace{mark-compact.cc}::ShouldMovePage().
Offset()
size_t v8::internal::MemoryChunk::Offset (Address addr) const [inline]
Definition at line 363 of file memory-chunk.h.
{ return addr - address(); }
Referenced by v8::internal::SemiSpace::AddRangeToActiveSystemPages(), v8::internal::PagedSpaceBase::AddRangeToActiveSystemPages(), v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::CheckForSharedObject(), v8::internal::RememberedSetOperations::CheckNoneInRange(), v8::internal::Scavenger::CheckOldToNewSlotForSharedTyped(), v8::internal::Scavenger::CheckOldToNewSlotForSharedUntyped(), v8::internal::Sweeper::CleanupRememberedSetEntriesForFreedMemory(), v8::internal::anonymous_namespace{heap-write-barrier.cc}::ForRangeImpl(), v8::internal::WriteBarrier::GenerationalBarrierSlow(), v8::internal::IterateAndScavengePromotedObjectsVisitor::HandleSlot(), v8::internal::MemoryChunkMetadata::Offset(), v8::internal::MarkCompactCollector::ProcessRelocInfo(), v8::internal::Sweeper::RawSweep(), v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlot(), v8::internal::MarkCompactCollector::RecordSlot(), v8::internal::RememberedSetOperations::RemoveRange(), v8::internal::WriteBarrier::SharedHeapBarrierSlow(), v8::internal::LargeObjectSpace::ShrinkPageToObjectSize(), and v8::internal::Heap::AllocationTrackerForDebugging::UpdateAllocationsHash().
OffsetMaybeOutOfRange()
size_t v8::internal::MemoryChunk::OffsetMaybeOutOfRange (Address addr) const [inline]
Definition at line 364 of file memory-chunk.h.
{ return Offset(addr); }
References v8::internal::Offset.
Referenced by v8::internal::RememberedSetOperations::CheckNoneInRange(), and v8::internal::RememberedSetOperations::RemoveRange().
OldGenerationPageFlags()
MemoryChunk::MainThreadFlags v8::internal::MemoryChunk::OldGenerationPageFlags (MarkingMode marking_mode, AllocationSpace space) [static]
Definition at line 199 of file memory-chunk.cc.
                                                     {
  MainThreadFlags flags_to_set = NO_FLAGS;
  if (!v8_flags.sticky_mark_bits || (space != OLD_SPACE)) {
    flags_to_set |= MemoryChunk::CONTAINS_ONLY_OLD;
  }
  if (marking_mode == MarkingMode::kMajorMarking) {
    flags_to_set |= MemoryChunk::POINTERS_TO_HERE_ARE_INTERESTING |
                    MemoryChunk::POINTERS_FROM_HERE_ARE_INTERESTING |
                    MemoryChunk::INCREMENTAL_MARKING |
                    MemoryChunk::IS_MAJOR_GC_IN_PROGRESS;
  } else if (IsAnySharedSpace(space)) {
    // We need to track pointers into the SHARED_SPACE for OLD_TO_SHARED.
    flags_to_set |= MemoryChunk::POINTERS_TO_HERE_ARE_INTERESTING;
  } else {
    flags_to_set |= MemoryChunk::POINTERS_FROM_HERE_ARE_INTERESTING;
    if (marking_mode == MarkingMode::kMinorMarking) {
      flags_to_set |= MemoryChunk::INCREMENTAL_MARKING;
    }
  }
  return flags_to_set;
}
References CONTAINS_ONLY_OLD, INCREMENTAL_MARKING, IS_MAJOR_GC_IN_PROGRESS, v8::internal::IsAnySharedSpace(), v8::internal::kMajorMarking, v8::internal::kMinorMarking, NO_FLAGS, v8::internal::OLD_SPACE, POINTERS_FROM_HERE_ARE_INTERESTING, POINTERS_TO_HERE_ARE_INTERESTING, space, and v8::internal::v8_flags.
Referenced by v8::internal::MutablePageMetadata::InitialFlags(), and SetOldGenerationPageFlags().
ResetMajorGCInProgress()
void v8::internal::MemoryChunk::ResetMajorGCInProgress () [inline]
Definition at line 256 of file memory-chunk.h.
                                          {
    ClearFlagUnlocked(IS_MAJOR_GC_IN_PROGRESS);
  }
SetFlagNonExecutable()
void v8::internal::MemoryChunk::SetFlagNonExecutable (Flag flag) [inline]
Definition at line 240 of file memory-chunk.h.
                                                 {
    return SetFlagUnlocked(flag);
  }
Referenced by v8::internal::NewLargeObjectSpace::AllocateRaw(), v8::internal::MarkCompactCollector::EvacuatePagesInParallel(), v8::internal::SemiSpace::FixPagesFlags(), v8::internal::NewLargeObjectSpace::Flip(), v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::HandleHeapObject(), v8::internal::PrecisePagePinningVisitor::HandlePointer(), v8::internal::SemiSpace::InitializePage(), v8::internal::PagedSpaceForNewSpace::InitializePage(), v8::internal::MarkCompactCollector::MarkRootObject(), v8::internal::SemiSpace::MoveQuarantinedPage(), v8::internal::SemiSpaceNewSpace::SetAgeMarkAndBelowAgeMarkPageFlags(), SetFlagSlow(), v8::internal::anonymous_namespace{minor-mark-sweep.cc}::ShouldMovePage(), and v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace().
SetFlagSlow()
void v8::internal::MemoryChunk::SetFlagSlow (Flag flag)
Definition at line 180 of file memory-chunk.cc.
                                       {
  if (executable()) {
    RwxMemoryWriteScope scope("Set a MemoryChunk flag in executable memory.");
    SetFlagUnlocked(flag);
  } else {
    SetFlagNonExecutable(flag);
  }
}
References executable(), SetFlagNonExecutable(), and SetFlagUnlocked().
Referenced by v8::internal::PageMetadata::MarkEvacuationCandidate(), v8::internal::PageMetadata::MarkNeverAllocateForTesting(), v8::internal::MarkCompactCollector::PostProcessAbortedEvacuationCandidates(), v8::internal::MemoryAllocator::PreFreeMemory(), v8::internal::MarkCompactCollector::ReportAbortedEvacuationCandidateDueToFlags(), and v8::internal::MemoryAllocator::UnregisterMemoryChunk().
SetFlagsNonExecutable()
void v8::internal::MemoryChunk::SetFlagsNonExecutable (MainThreadFlags flags, MainThreadFlags mask = kAllFlagsMask) [inline]
Definition at line 246 of file memory-chunk.h.
                                                                             {
    return SetFlagsUnlocked(flags, mask);
  }
References v8::internal::flags.
Referenced by v8::internal::SemiSpace::FixPagesFlags(), and SetYoungGenerationPageFlags().
SetFlagsUnlocked()
void v8::internal::MemoryChunk::SetFlagsUnlocked (MainThreadFlags flags, MainThreadFlags mask = kAllFlagsMask) [inline]
Definition at line 235 of file memory-chunk.h.
                                                                        {
    main_thread_flags_ = (main_thread_flags_ & ~mask) | (flags & mask);
  }
References v8::internal::flags.
Referenced by SetOldGenerationPageFlags().
SetFlagUnlocked()
void v8::internal::MemoryChunk::SetFlagUnlocked (Flag flag) [inline]
Definition at line 226 of file memory-chunk.h.
{ main_thread_flags_ |= flag; }
Referenced by SetFlagSlow().
SetMajorGCInProgress()
void v8::internal::MemoryChunk::SetMajorGCInProgress () [inline]
Definition at line 253 of file memory-chunk.h.
                                        {
    SetFlagUnlocked(IS_MAJOR_GC_IN_PROGRESS);
  }
SetOldGenerationPageFlags()
void v8::internal::MemoryChunk::SetOldGenerationPageFlags (MarkingMode marking_mode, AllocationSpace space)
Definition at line 239 of file memory-chunk.cc.
                                                                   {
  MainThreadFlags flags_to_set = OldGenerationPageFlags(marking_mode, space);
  MainThreadFlags flags_to_clear = NO_FLAGS;
  if (marking_mode != MarkingMode::kMajorMarking) {
    if (IsAnySharedSpace(space)) {
      // No need to track OLD_TO_NEW or OLD_TO_SHARED within the shared space.
      flags_to_clear |= MemoryChunk::POINTERS_FROM_HERE_ARE_INTERESTING |
                        MemoryChunk::INCREMENTAL_MARKING;
    } else {
      flags_to_clear |= MemoryChunk::POINTERS_TO_HERE_ARE_INTERESTING;
      if (marking_mode != MarkingMode::kMinorMarking) {
        flags_to_clear |= MemoryChunk::INCREMENTAL_MARKING;
      }
    }
  }
  SetFlagsUnlocked(flags_to_set, flags_to_set);
  ClearFlagsUnlocked(flags_to_clear);
}
References ClearFlagsUnlocked(), INCREMENTAL_MARKING, v8::internal::IsAnySharedSpace(), v8::internal::kMajorMarking, v8::internal::kMinorMarking, NO_FLAGS, OldGenerationPageFlags(), POINTERS_FROM_HERE_ARE_INTERESTING, POINTERS_TO_HERE_ARE_INTERESTING, SetFlagsUnlocked(), and space.
Referenced by v8::internal::PageMetadata::ConvertNewToOld(), v8::internal::OldLargeObjectSpace::PromoteNewLargeObject(), and v8::internal::MutablePageMetadata::SetOldGenerationPageFlags().
SetYoungGenerationPageFlags()
void v8::internal::MemoryChunk::SetYoungGenerationPageFlags (MarkingMode marking_mode)
Definition at line 261 of file memory-chunk.cc.
                                                                      {
  MainThreadFlags flags_to_set = YoungGenerationPageFlags(marking_mode);
  MainThreadFlags flags_to_clear = NO_FLAGS;
  if (marking_mode == MarkingMode::kNoMarking) {
    flags_to_clear |= MemoryChunk::POINTERS_FROM_HERE_ARE_INTERESTING;
    flags_to_clear |= MemoryChunk::INCREMENTAL_MARKING;
  }
  SetFlagsNonExecutable(flags_to_set, flags_to_set);
  ClearFlagsNonExecutable(flags_to_clear);
}
References ClearFlagsNonExecutable(), INCREMENTAL_MARKING, v8::internal::kNoMarking, NO_FLAGS, POINTERS_FROM_HERE_ARE_INTERESTING, SetFlagsNonExecutable(), and YoungGenerationPageFlags().
Referenced by v8::internal::MutablePageMetadata::SetYoungGenerationPageFlags().
ShouldSkipEvacuationSlotRecording()
bool v8::internal::MemoryChunk::ShouldSkipEvacuationSlotRecording () const [inline]
Definition at line 296 of file memory-chunk.h.
                                                 {
    MainThreadFlags flags = GetFlags();
    return ((flags & kSkipEvacuationSlotsRecordingMask) != 0) &&
           ((flags & COMPACTION_WAS_ABORTED) == 0);
  }
References v8::internal::flags.
Referenced by v8::internal::WriteBarrier::ForRange(), v8::internal::MarkingBarrier::MarkRange(), v8::internal::MarkCompactCollector::RecordSlot(), and v8::internal::MarkCompactCollector::ShouldRecordRelocSlot().
YoungGenerationPageFlags()
MemoryChunk::MainThreadFlags v8::internal::MemoryChunk::YoungGenerationPageFlags (MarkingMode marking_mode) [static]
Definition at line 226 of file memory-chunk.cc.
                              {
  MainThreadFlags flags = MemoryChunk::POINTERS_TO_HERE_ARE_INTERESTING;
  if (marking_mode != MarkingMode::kNoMarking) {
    flags |= MemoryChunk::POINTERS_FROM_HERE_ARE_INTERESTING;
    flags |= MemoryChunk::INCREMENTAL_MARKING;
    if (marking_mode == MarkingMode::kMajorMarking) {
      flags |= MemoryChunk::IS_MAJOR_GC_IN_PROGRESS;
    }
  }
  return flags;
}
References v8::internal::flags, INCREMENTAL_MARKING, IS_MAJOR_GC_IN_PROGRESS, v8::internal::kMajorMarking, v8::internal::kNoMarking, POINTERS_FROM_HERE_ARE_INTERESTING, and POINTERS_TO_HERE_ARE_INTERESTING.
Referenced by v8::internal::SemiSpace::FixPagesFlags(), v8::internal::MutablePageMetadata::InitialFlags(), and SetYoungGenerationPageFlags().
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 424 of file memory-chunk.h.
compiler::turboshaft::TurboshaftAssemblerOpInterface
template<typename Next >
friend class compiler::turboshaft::TurboshaftAssemblerOpInterface [friend]
Definition at line 427 of file memory-chunk.h.
MacroAssembler
friend class MacroAssembler [friend]
Definition at line 425 of file memory-chunk.h.
Member Data Documentation
kAlignment
constexpr intptr_t v8::internal::MemoryChunk::kAlignment [static], [constexpr], [private]
Initial value:
=
      (static_cast<uintptr_t>(1) << kPageSizeBits)
Definition at line 378 of file memory-chunk.h.
kAlignmentMask
constexpr intptr_t v8::internal::MemoryChunk::kAlignmentMask = kAlignment - 1 [static], [constexpr], [private]
Definition at line 380 of file memory-chunk.h.
kAllFlagsMask
constexpr MemoryChunk::MainThreadFlags v8::internal::MemoryChunk::kAllFlagsMask = ~MainThreadFlags(NO_FLAGS) [static], [constexpr]
Definition at line 149 of file memory-chunk.h.
Referenced by v8::internal::PageMetadata::ConvertNewToOld().
kEvacuationCandidateMask
constexpr MemoryChunk::MainThreadFlags v8::internal::MemoryChunk::kEvacuationCandidateMask [static], [constexpr]
Initial value:
=
      EVACUATION_CANDIDATE
Definition at line 154 of file memory-chunk.h.
Referenced by v8::internal::WriteBarrierCodeStubAssembler::IsValueUnmarkedOrRecordSlot().
kIncrementalMarking
constexpr MainThreadFlags v8::internal::MemoryChunk::kIncrementalMarking = INCREMENTAL_MARKING [static], [constexpr]
Definition at line 161 of file memory-chunk.h.
Referenced by v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrier().
kInSharedHeap
constexpr MainThreadFlags v8::internal::MemoryChunk::kInSharedHeap = IN_WRITABLE_SHARED_SPACE [static], [constexpr]
Definition at line 160 of file memory-chunk.h.
Referenced by v8::internal::WriteBarrierCodeStubAssembler::GenerationalOrSharedBarrierSlow(), v8::internal::WriteBarrierCodeStubAssembler::InSharedHeap(), and v8::internal::WasmBuiltinsAssembler::InSharedSpace().
kIsInReadOnlyHeapMask
constexpr MainThreadFlags v8::internal::MemoryChunk::kIsInReadOnlyHeapMask = READ_ONLY_HEAP [static], [constexpr]
Definition at line 158 of file memory-chunk.h.
Referenced by v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::OutOfLineRecordWrite::Generate().
kIsInYoungGenerationMask
constexpr MemoryChunk::MainThreadFlags v8::internal::MemoryChunk::kIsInYoungGenerationMask [static], [constexpr]
Initial value:
=
      MainThreadFlags(FROM_PAGE) | MainThreadFlags(TO_PAGE)
Definition at line 156 of file memory-chunk.h.
Referenced by v8::internal::CodeStubAssembler::ExtractToFixedArray(), v8::internal::WriteBarrierCodeStubAssembler::GenerationalOrSharedBarrierSlow(), v8::internal::WriteBarrierCodeStubAssembler::InYoungGeneration(), and v8::internal::MarkingHelper::ShouldMarkObject().
kIsLargePageMask
constexpr MemoryChunk::MainThreadFlags v8::internal::MemoryChunk::kIsLargePageMask = LARGE_PAGE [static], [constexpr]
Definition at line 159 of file memory-chunk.h.
kIsOnlyOldOrMajorGCInProgressMask
constexpr MainThreadFlags v8::internal::MemoryChunk::kIsOnlyOldOrMajorGCInProgressMask [static], [constexpr]
Initial value:
=
      MainThreadFlags(CONTAINS_ONLY_OLD) |
      MainThreadFlags(IS_MAJOR_GC_IN_PROGRESS)
Definition at line 165 of file memory-chunk.h.
Referenced by v8::internal::WriteBarrierCodeStubAssembler::InYoungGeneration().
kPointersFromHereAreInterestingMask
constexpr MemoryChunk::MainThreadFlags v8::internal::MemoryChunk::kPointersFromHereAreInterestingMask [static], [constexpr]
Initial value:
=
      POINTERS_FROM_HERE_ARE_INTERESTING
Definition at line 152 of file memory-chunk.h.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::wasm::LiftoffAssembler::AtomicExchangeTaggedPointer(), v8::internal::maglev::MaglevAssembler::CheckAndEmitDeferredWriteBarrier(), v8::internal::WriteBarrier::CombinedGenerationalAndSharedEphemeronBarrierSlow(), v8::internal::wasm::LiftoffAssembler::EmitWriteBarrier(), v8::internal::WriteBarrier::MarkingSlow(), v8::internal::MacroAssembler::RecordWrite(), v8::internal::wasm::LiftoffAssembler::StoreTaggedPointer(), and v8::internal::CodeStubAssembler::TrySkipWriteBarrier().
kPointersToHereAreInterestingMask
constexpr MemoryChunk::MainThreadFlags v8::internal::MemoryChunk::kPointersToHereAreInterestingMask [static], [constexpr]
Initial value:
=
      POINTERS_TO_HERE_ARE_INTERESTING
Definition at line 150 of file memory-chunk.h.
Referenced by v8::internal::wasm::LiftoffAssembler::AtomicExchangeTaggedPointer(), v8::internal::maglev::MaglevAssembler::CheckAndEmitDeferredWriteBarrier(), v8::internal::wasm::LiftoffAssembler::EmitWriteBarrier(), v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::OutOfLineRecordWrite::Generate(), v8::internal::compiler::anonymous_namespace{code-generator-arm64.cc}::OutOfLineRecordWrite::Generate(), v8::internal::compiler::anonymous_namespace{code-generator-ia32.cc}::OutOfLineRecordWrite::Generate(), v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::OutOfLineRecordWrite::Generate(), v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::OutOfLineRecordWrite::Generate(), v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::OutOfLineRecordWrite::Generate(), v8::internal::compiler::anonymous_namespace{code-generator-riscv.cc}::OutOfLineRecordWrite::Generate(), v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::OutOfLineRecordWrite::Generate(), v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::OutOfLineRecordWrite::Generate(), v8::internal::MacroAssembler::RecordWrite(), and v8::internal::wasm::LiftoffAssembler::StoreTaggedPointer().
kSkipEvacuationSlotsRecordingMask
constexpr MemoryChunk::MainThreadFlags v8::internal::MemoryChunk::kSkipEvacuationSlotsRecordingMask [static], [constexpr]
Initial value:
=
      MainThreadFlags(kEvacuationCandidateMask) |
      MainThreadFlags(kIsInYoungGenerationMask)
Definition at line 162 of file memory-chunk.h.
Referenced by v8::internal::WriteBarrierCodeStubAssembler::IsValueUnmarkedOrRecordSlot().
main_thread_flags_
MainThreadFlags v8::internal::MemoryChunk::main_thread_flags_ [private]
Definition at line 414 of file memory-chunk.h.
metadata_
MemoryChunkMetadata* v8::internal::MemoryChunk::metadata_ [private]
Definition at line 419 of file memory-chunk.h.
Referenced by InitializationMemoryFence(), and Metadata().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/memory-chunk.h
/mnt/V8SourceCode/src/heap/memory-chunk-inl.h
/mnt/V8SourceCode/src/heap/memory-chunk.cc