v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier Class Reference
#include <maglev-ir.h>
Public Member Functions
StoreTrustedPointerFieldWithWriteBarrier (uint64_t bitfield, int offset, IndirectPointerTag tag, StoreTaggedMode store_mode)
int offset () const
IndirectPointerTag tag () const
bool initializing_or_transitioning () const
Input & object_input ()
Input & value_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes
static constexpr int kObjectIndex = 0
static constexpr int kValueIndex = 1
Private Types
using Base = FixedInputNodeT< 2, StoreTrustedPointerFieldWithWriteBarrier >
using InitializingOrTransitioningField = NextBitField< bool, 1 >
Private Attributes
const int offset_
const IndirectPointerTag tag_
Additional Inherited Members
Detailed Description
Definition at line 9184 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::Base = FixedInputNodeT<2, StoreTrustedPointerFieldWithWriteBarrier> [private]
Definition at line 9186 of file maglev-ir.h.
InitializingOrTransitioningField
using v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::InitializingOrTransitioningField = NextBitField<bool, 1> [private]
Definition at line 9227 of file maglev-ir.h.
Constructor & Destructor Documentation
StoreTrustedPointerFieldWithWriteBarrier()
v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::StoreTrustedPointerFieldWithWriteBarrier (uint64_t bitfield, int offset, IndirectPointerTag tag, StoreTaggedMode store_mode) [inline], [explicit]
Definition at line 9189 of file maglev-ir.h.
      : Base(bitfield | InitializingOrTransitioningField::encode(
                            IsInitializingOrTransitioning(store_mode))),
        offset_(offset),
        tag_(tag) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::GenerateCode (MaglevAssembler * , const ProcessingState &)
initializing_or_transitioning()
bool v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::initializing_or_transitioning () const [inline]
Definition at line 9205 of file maglev-ir.h.
                                             {
    return InitializingOrTransitioningField::decode(bitfield());
  }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::MaxCallStackArgs () const
object_input()
Input& v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::object_input () [inline]
Definition at line 9211 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
offset()
int v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::offset () const [inline]
Definition at line 9203 of file maglev-ir.h.
{ return offset_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8264 of file maglev-ir.cc.
                                                               {
  os << "(0x" << std::hex << offset() << std::dec << ")";
}
References offset().
SetValueLocationConstraints()
void v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::SetValueLocationConstraints ()
tag()
IndirectPointerTag v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::tag () const [inline]
Definition at line 9204 of file maglev-ir.h.
{ return tag_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
value_input()
Input& v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::value_input () [inline]
Definition at line 9212 of file maglev-ir.h.
{ return input(kValueIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 9200 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::kObjectIndex = 0 [static], [constexpr]
Definition at line 9209 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::CanWrite() | OpProperties::DeferredCall()
Definition at line 9198 of file maglev-ir.h.
kValueIndex
constexpr int v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::kValueIndex = 1 [static], [constexpr]
Definition at line 9210 of file maglev-ir.h.
offset_
const int v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::offset_ [private]
Definition at line 9229 of file maglev-ir.h.
tag_
const IndirectPointerTag v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::tag_ [private]
Definition at line 9230 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc