v8::internal::heap::ListNode< T > Class Template Reference
#include <list.h>
Public Member Functions
ListNode ()
T * next ()
T * prev ()
const T * next () const
const T * prev () const
void Initialize ()
Private Member Functions
void set_next (T *next)
void set_prev (T *prev)
Private Attributes
T * next_
T * prev_
Friends
class List< T >
Detailed Description
template<class T>
class v8::internal::heap::ListNode< T >
Definition at line 135 of file list.h.
Constructor & Destructor Documentation
ListNode()
template<class T >
v8::internal::heap::ListNode< T >::ListNode () [inline]
Definition at line 137 of file list.h.
{ Initialize(); }
References v8::internal::heap::ListNode< T >::Initialize().
Member Function Documentation
Initialize()
template<class T >
void v8::internal::heap::ListNode< T >::Initialize () [inline]
Definition at line 145 of file list.h.
                    {
    next_ = nullptr;
    prev_ = nullptr;
  }
References v8::internal::heap::ListNode< T >::next_, and v8::internal::heap::ListNode< T >::prev_.
Referenced by v8::internal::heap::ListNode< T >::ListNode().
next() [1/2]
template<class T >
T* v8::internal::heap::ListNode< T >::next () [inline]
Definition at line 139 of file list.h.
{ return next_; }
References v8::internal::heap::ListNode< T >::next_.
Referenced by v8::internal::heap::ListNode< T >::set_next().
next() [2/2]
template<class T >
const T* v8::internal::heap::ListNode< T >::next () const [inline]
Definition at line 142 of file list.h.
{ return next_; }
References v8::internal::heap::ListNode< T >::next_.
prev() [1/2]
template<class T >
T* v8::internal::heap::ListNode< T >::prev () [inline]
Definition at line 140 of file list.h.
{ return prev_; }
References v8::internal::heap::ListNode< T >::prev_.
Referenced by v8::internal::heap::ListNode< T >::set_prev().
prev() [2/2]
template<class T >
const T* v8::internal::heap::ListNode< T >::prev () const [inline]
Definition at line 143 of file list.h.
{ return prev_; }
References v8::internal::heap::ListNode< T >::prev_.
set_next()
template<class T >
void v8::internal::heap::ListNode< T >::set_next (T * next) [inline], [private]
Definition at line 151 of file list.h.
{ next_ = next; }
References v8::internal::heap::ListNode< T >::next(), and v8::internal::heap::ListNode< T >::next_.
set_prev()
template<class T >
void v8::internal::heap::ListNode< T >::set_prev (T * prev) [inline], [private]
Definition at line 152 of file list.h.
{ prev_ = prev; }
References v8::internal::heap::ListNode< T >::prev(), and v8::internal::heap::ListNode< T >::prev_.
Friends And Related Function Documentation
List< T >
template<class T >
friend class List< T > [friend]
Definition at line 155 of file list.h.
Member Data Documentation
next_
template<class T >
T* v8::internal::heap::ListNode< T >::next_ [private]
Definition at line 154 of file list.h.
Referenced by v8::internal::heap::ListNode< T >::Initialize(), v8::internal::heap::ListNode< T >::next(), and v8::internal::heap::ListNode< T >::set_next().
prev_
template<class T >
T* v8::internal::heap::ListNode< T >::prev_ [private]
Definition at line 155 of file list.h.
Referenced by v8::internal::heap::ListNode< T >::Initialize(), v8::internal::heap::ListNode< T >::prev(), and v8::internal::heap::ListNode< T >::set_prev().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/list.h