v8::internal::wasm::DebugInfoImpl Class Reference
Classes
struct CachedDebuggingCode
struct FrameInspectionScope
struct PerIsolateDebugData
Public Member Functions
DebugInfoImpl (NativeModule *native_module)
DebugInfoImpl (const DebugInfoImpl &)=delete
DebugInfoImpl & operator= (const DebugInfoImpl &)=delete
int GetNumLocals (Address pc, Isolate *isolate)
WasmValue GetLocalValue (int local, Address pc, Address fp, Address debug_break_fp, Isolate *isolate)
int GetStackDepth (Address pc, Isolate *isolate)
WasmValue GetStackValue (int index, Address pc, Address fp, Address debug_break_fp, Isolate *isolate)
const WasmFunction & GetFunctionAtAddress (Address pc, Isolate *isolate)
int DeadBreakpoint (WasmFrame *frame, base::Vector< const int > breakpoints)
int DeadBreakpoint (int func_index, base::Vector< const int > breakpoints, Isolate *isolate)
WasmCode * RecompileLiftoffWithBreakpoints (int func_index, base::Vector< const int > offsets, int dead_breakpoint)
void SetBreakpoint (int func_index, int offset, Isolate *isolate)
std::vector< int > FindAllBreakpoints (int func_index)
void UpdateBreakpoints (int func_index, base::Vector< int > breakpoints, Isolate *isolate, StackFrameId stepping_frame, int dead_breakpoint)
void FloodWithBreakpoints (WasmFrame *frame, ReturnLocation return_location)
bool IsFrameBlackboxed (WasmFrame *frame)
bool PrepareStep (WasmFrame *frame)
void PrepareStepOutTo (WasmFrame *frame)
void ClearStepping (WasmFrame *frame)
void ClearStepping (Isolate *isolate)
bool IsStepping (WasmFrame *frame)
void RemoveBreakpoint (int func_index, int position, Isolate *isolate)
void RemoveDebugSideTables (base::Vector< WasmCode *const > codes)
DebugSideTable * GetDebugSideTableIfExists (const WasmCode *code) const
void RemoveIsolate (Isolate *isolate)
size_t EstimateCurrentMemoryConsumption () const
Static Public Member Functions
static bool HasRemovedBreakpoints (const std::vector< int > &removed, const std::vector< int > &remaining)
Private Member Functions
const DebugSideTable * GetDebugSideTable (WasmCode *code)
WasmValue GetValue (const DebugSideTable *debug_side_table, const DebugSideTable::Entry *debug_side_table_entry, int index, Address stack_frame_base, Address debug_break_fp, Isolate *isolate) const
void UpdateReturnAddresses (Isolate *isolate, WasmCode *new_code, StackFrameId stepping_frame)
void UpdateReturnAddress (WasmFrame *frame, WasmCode *new_code, ReturnLocation return_location)
bool IsAtReturn (WasmFrame *frame)
Private Attributes
NativeModule *const native_module_
base::Mutex debug_side_tables_mutex_
std::unordered_map< const WasmCode *, std::unique_ptr< DebugSideTable > > debug_side_tables_
base::Mutex mutex_
std::vector< CachedDebuggingCode > cached_debugging_code_
std::unordered_map< Isolate *, PerIsolateDebugData > per_isolate_data_
Static Private Attributes
static constexpr size_t kMaxCachedDebuggingCode = 3
Detailed Description
Definition at line 130 of file wasm-debug.cc.
Constructor & Destructor Documentation
DebugInfoImpl() [1/2]
v8::internal::wasm::DebugInfoImpl::DebugInfoImpl (NativeModule * native_module) [inline], [explicit]
Definition at line 132 of file wasm-debug.cc.
      : native_module_(native_module) {}
DebugInfoImpl() [2/2]
v8::internal::wasm::DebugInfoImpl::DebugInfoImpl (const DebugInfoImpl &) [delete]
Member Function Documentation
ClearStepping() [1/2]
void v8::internal::wasm::DebugInfoImpl::ClearStepping (Isolate * isolate) [inline]
Definition at line 441 of file wasm-debug.cc.
                                       {
    base::MutexGuard guard(&mutex_);
    auto it = per_isolate_data_.find(isolate);
    if (it != per_isolate_data_.end()) it->second.stepping_frame = NO_ID;
  }
References v8::internal::NO_ID.
ClearStepping() [2/2]
void v8::internal::wasm::DebugInfoImpl::ClearStepping (WasmFrame * frame) [inline]
Definition at line 425 of file wasm-debug.cc.
                                       {
    // TODO(paolosev@microsoft.com) - Add support for breakpoints in Wasm
    // interpreter.
    if (v8_flags.wasm_jitless) return;
    WasmCodeRefScope wasm_code_ref_scope;
    base::MutexGuard guard(&mutex_);
    auto* code = frame->wasm_code();
    if (code->for_debugging() != kForStepping) return;
    int func_index = code->index();
    std::vector<int> breakpoints = FindAllBreakpoints(func_index);
    int dead_breakpoint = DeadBreakpoint(frame, base::VectorOf(breakpoints));
    WasmCode* new_code = RecompileLiftoffWithBreakpoints(
        func_index, base::VectorOf(breakpoints), dead_breakpoint);
    UpdateReturnAddress(frame, new_code, kAfterBreakpoint);
  }
References code, v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::kAfterBreakpoint, v8::internal::wasm::kForStepping, v8::internal::v8_flags, and v8::base::VectorOf().
DeadBreakpoint() [1/2]
int v8::internal::wasm::DebugInfoImpl::DeadBreakpoint (int func_index, base::Vector< const int > breakpoints, Isolate * isolate) [inline]
Definition at line 191 of file wasm-debug.cc.
                                       {
    DebuggableStackFrameIterator it(isolate);
#if !V8_ENABLE_DRUMBRAKE
    if (it.done() || !it.is_wasm()) return 0;
#else // !V8_ENABLE_DRUMBRAKE
    // TODO(paolosev@microsoft.com) - Implement for Wasm interpreter.
    if (it.done() || !it.is_wasm() || it.is_wasm_interpreter_entry()) {
      return 0;
    }
#endif // !V8_ENABLE_DRUMBRAKE
    auto* wasm_frame = WasmFrame::cast(it.frame());
    if (static_cast<int>(wasm_frame->function_index()) != func_index) return 0;
    return DeadBreakpoint(wasm_frame, breakpoints);
  }
References v8::internal::DebuggableStackFrameIterator::done(), and v8::internal::DebuggableStackFrameIterator::frame().
DeadBreakpoint() [2/2]
int v8::internal::wasm::DebugInfoImpl::DeadBreakpoint (WasmFrame * frame, base::Vector< const int > breakpoints) [inline]
Definition at line 179 of file wasm-debug.cc.
                                                                          {
    const auto& function =
        native_module_->module()->functions[frame->function_index()];
    int offset = frame->position() - function.code.offset();
    if (std::binary_search(breakpoints.begin(), breakpoints.end(), offset)) {
      return 0;
    }
    return offset;
  }
References v8::base::Vector< T >::begin(), and v8::base::Vector< T >::end().
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::DebugInfoImpl::EstimateCurrentMemoryConsumption () const [inline]
Definition at line 535 of file wasm-debug.cc.
                                                  {
    UPDATE_WHEN_CLASS_CHANGES(DebugInfoImpl, 144);
    UPDATE_WHEN_CLASS_CHANGES(CachedDebuggingCode, 40);
    UPDATE_WHEN_CLASS_CHANGES(PerIsolateDebugData, 48);
    size_t result = sizeof(DebugInfoImpl);
    {
      base::MutexGuard lock(&debug_side_tables_mutex_);
      result += ContentSize(debug_side_tables_);
      for (const auto& [code, table] : debug_side_tables_) {
        result += table->EstimateCurrentMemoryConsumption();
      }
    }
    {
      base::MutexGuard lock(&mutex_);
      result += ContentSize(cached_debugging_code_);
      for (const CachedDebuggingCode& code : cached_debugging_code_) {
        result += code.breakpoint_offsets.size() * sizeof(int);
      }
      result += ContentSize(per_isolate_data_);
      for (const auto& [isolate, data] : per_isolate_data_) {
        // Inlined handling of {PerIsolateDebugData}.
        result += ContentSize(data.breakpoints_per_function);
        for (const auto& [idx, breakpoints] : data.breakpoints_per_function) {
          result += ContentSize(breakpoints);
        }
      }
    }
    if (v8_flags.trace_wasm_offheap_memory) {
      PrintF("DebugInfo: %zu\n", result);
    }
    return result;
  }
References code, v8::internal::wasm::ContentSize(), v8::internal::PrintF(), v8::base::internal::result, UPDATE_WHEN_CLASS_CHANGES, and v8::internal::v8_flags.
FindAllBreakpoints()
std::vector<int> v8::internal::wasm::DebugInfoImpl::FindAllBreakpoints (int func_index) [inline]
Definition at line 359 of file wasm-debug.cc.
                                                    {
    mutex_.AssertHeld(); // Mutex must be held externally.
    std::set<int> breakpoints;
    for (auto& data : per_isolate_data_) {
      auto it = data.second.breakpoints_per_function.find(func_index);
      if (it == data.second.breakpoints_per_function.end()) continue;
      for (int offset : it->second) breakpoints.insert(offset);
    }
    return {breakpoints.begin(), breakpoints.end()};
  }
FloodWithBreakpoints()
void v8::internal::wasm::DebugInfoImpl::FloodWithBreakpoints (WasmFrame * frame, ReturnLocation return_location) [inline]
Definition at line 382 of file wasm-debug.cc.
                                                                              {
    // TODO(paolosev@microsoft.com) - Add support for breakpoints in Wasm
    // interpreter.
    if (v8_flags.wasm_jitless) return;
    // 0 is an invalid offset used to indicate flooding.
    constexpr int kFloodingBreakpoints[] = {0};
    DCHECK(frame->wasm_code()->is_liftoff());
    // Generate an additional source position for the current byte offset.
    base::MutexGuard guard(&mutex_);
    WasmCode* new_code = RecompileLiftoffWithBreakpoints(
        frame->function_index(), base::ArrayVector(kFloodingBreakpoints), 0);
    UpdateReturnAddress(frame, new_code, return_location);
    per_isolate_data_[frame->isolate()].stepping_frame = frame->id();
  }
References v8::base::ArrayVector(), v8::internal::DCHECK(), and v8::internal::v8_flags.
GetDebugSideTable()
const DebugSideTable* v8::internal::wasm::DebugInfoImpl::GetDebugSideTable (WasmCode * code) [inline], [private]
Definition at line 592 of file wasm-debug.cc.
                                                          {
    DCHECK(code->is_inspectable());
    {
      // Only hold the mutex temporarily. We can't hold it while generating the
      // debug side table, because compilation takes the {NativeModule} lock.
      base::MutexGuard guard(&debug_side_tables_mutex_);
      auto it = debug_side_tables_.find(code);
      if (it != debug_side_tables_.end()) return it->second.get();
    }
    // Otherwise create the debug side table now.
    std::unique_ptr<DebugSideTable> debug_side_table =
        GenerateLiftoffDebugSideTable(code);
    DebugSideTable* ret = debug_side_table.get();
    // Check cache again, maybe another thread concurrently generated a debug
    // side table already.
    {
      base::MutexGuard guard(&debug_side_tables_mutex_);
      auto& slot = debug_side_tables_[code];
      if (slot != nullptr) return slot.get();
      slot = std::move(debug_side_table);
    }
    // Print the code together with the debug table, if requested.
    code->MaybePrint();
    return ret;
  }
References code, v8::internal::DCHECK(), and v8::internal::wasm::GenerateLiftoffDebugSideTable().
GetDebugSideTableIfExists()
DebugSideTable* v8::internal::wasm::DebugInfoImpl::GetDebugSideTableIfExists (const WasmCode * code) const [inline]
Definition at line 495 of file wasm-debug.cc.
                                                                        {
    base::MutexGuard guard(&debug_side_tables_mutex_);
    auto it = debug_side_tables_.find(code);
    return it == debug_side_tables_.end() ? nullptr : it->second.get();
  }
References code, and nullptr.
GetFunctionAtAddress()
const WasmFunction& v8::internal::wasm::DebugInfoImpl::GetFunctionAtAddress (Address pc, Isolate * isolate) [inline]
Definition at line 169 of file wasm-debug.cc.
                                                                         {
    FrameInspectionScope scope(this, pc, isolate);
    auto* module = native_module_->module();
    return module->functions[scope.code->index()];
  }
References v8::internal::wasm::DebugInfoImpl::FrameInspectionScope::code, and v8::internal::wasm::WasmCode::index().
GetLocalValue()
WasmValue v8::internal::wasm::DebugInfoImpl::GetLocalValue (int local, Address pc, Address fp, Address debug_break_fp, Isolate * isolate) [inline]
Definition at line 144 of file wasm-debug.cc.
                                                                    {
    FrameInspectionScope scope(this, pc, isolate);
    return GetValue(scope.debug_side_table, scope.debug_side_table_entry, local,
                    fp, debug_break_fp, isolate);
  }
References v8::internal::wasm::DebugInfoImpl::FrameInspectionScope::debug_side_table, v8::internal::wasm::DebugInfoImpl::FrameInspectionScope::debug_side_table_entry, and v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::GetValue().
GetNumLocals()
int v8::internal::wasm::DebugInfoImpl::GetNumLocals (Address pc, Isolate * isolate) [inline]
Definition at line 138 of file wasm-debug.cc.
                                                 {
    FrameInspectionScope scope(this, pc, isolate);
    if (!scope.is_inspectable()) return 0;
    return scope.debug_side_table->num_locals();
  }
References v8::internal::wasm::DebugInfoImpl::FrameInspectionScope::debug_side_table, v8::internal::wasm::DebugInfoImpl::FrameInspectionScope::is_inspectable(), and v8::internal::wasm::DebugSideTable::num_locals().
GetStackDepth()
int v8::internal::wasm::DebugInfoImpl::GetStackDepth (Address pc, Isolate * isolate) [inline]
Definition at line 151 of file wasm-debug.cc.
                                                  {
    FrameInspectionScope scope(this, pc, isolate);
    if (!scope.is_inspectable()) return 0;
    int num_locals = scope.debug_side_table->num_locals();
    int stack_height = scope.debug_side_table_entry->stack_height();
    return stack_height - num_locals;
  }
References v8::internal::wasm::DebugInfoImpl::FrameInspectionScope::debug_side_table, v8::internal::wasm::DebugInfoImpl::FrameInspectionScope::debug_side_table_entry, v8::internal::wasm::DebugInfoImpl::FrameInspectionScope::is_inspectable(), v8::internal::wasm::DebugSideTable::num_locals(), and v8::internal::wasm::DebugSideTable::Entry::stack_height().
GetStackValue()
WasmValue v8::internal::wasm::DebugInfoImpl::GetStackValue (int index, Address pc, Address fp, Address debug_break_fp, Isolate * isolate) [inline]
Definition at line 159 of file wasm-debug.cc.
                                                                    {
    FrameInspectionScope scope(this, pc, isolate);
    int num_locals = scope.debug_side_table->num_locals();
    int value_count = scope.debug_side_table_entry->stack_height();
    if (num_locals + index >= value_count) return {};
    return GetValue(scope.debug_side_table, scope.debug_side_table_entry,
                    num_locals + index, fp, debug_break_fp, isolate);
  }
References v8::internal::wasm::DebugInfoImpl::FrameInspectionScope::debug_side_table, v8::internal::wasm::DebugInfoImpl::FrameInspectionScope::debug_side_table_entry, v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::GetValue(), v8::internal::index, v8::internal::wasm::DebugSideTable::num_locals(), and v8::internal::wasm::DebugSideTable::Entry::stack_height().
GetValue()
WasmValue v8::internal::wasm::DebugInfoImpl::GetValue (const DebugSideTable * debug_side_table, const DebugSideTable::Entry * debug_side_table_entry, int index, Address stack_frame_base, Address debug_break_fp, Isolate * isolate) const [inline], [private]
Definition at line 623 of file wasm-debug.cc.
                                                                     {
    const DebugSideTable::Entry::Value* value =
        debug_side_table->FindValue(debug_side_table_entry, index);
    if (value->is_constant()) {
      DCHECK(value->type == kWasmI32 || value->type == kWasmI64);
      return value->type == kWasmI32 ? WasmValue(value->i32_const)
                                     : WasmValue(int64_t{value->i32_const});
    }
    if (value->is_register()) {
      auto reg = LiftoffRegister::from_liftoff_code(value->reg_code);
      auto gp_addr = [debug_break_fp](Register reg) {
        return debug_break_fp +
               WasmDebugBreakFrameConstants::GetPushedGpRegisterOffset(
                   reg.code());
      };
      if (reg.is_gp_pair()) {
        DCHECK_EQ(kWasmI64, value->type);
        uint32_t low_word = ReadUnalignedValue<uint32_t>(gp_addr(reg.low_gp()));
        uint32_t high_word =
            ReadUnalignedValue<uint32_t>(gp_addr(reg.high_gp()));
        return WasmValue((uint64_t{high_word} << 32) | low_word);
      }
      if (reg.is_gp()) {
        if (value->type == kWasmI32) {
          return WasmValue(ReadUnalignedValue<uint32_t>(gp_addr(reg.gp())));
        } else if (value->type == kWasmI64) {
          return WasmValue(ReadUnalignedValue<uint64_t>(gp_addr(reg.gp())));
        } else if (value->type.is_reference()) {
          DirectHandle<Object> obj(
              Tagged<Object>(ReadUnalignedValue<Address>(gp_addr(reg.gp()))),
              isolate);
          // TODO(jkummerow): Consider changing {value->type} to be a
          // CanonicalValueType.
          return WasmValue(obj, value->module->canonical_type(value->type));
        } else {
          UNREACHABLE();
        }
      }
      DCHECK(reg.is_fp() || reg.is_fp_pair());
      // ifdef here to workaround unreachable code for is_fp_pair.
#ifdef V8_TARGET_ARCH_ARM
      int code = reg.is_fp_pair() ? reg.low_fp().code() : reg.fp().code();
#else
      int code = reg.fp().code();
#endif
      Address spilled_addr =
          debug_break_fp +
          WasmDebugBreakFrameConstants::GetPushedFpRegisterOffset(code);
      if (value->type == kWasmF32) {
        return WasmValue(ReadUnalignedValue<float>(spilled_addr));
      } else if (value->type == kWasmF64) {
        return WasmValue(ReadUnalignedValue<double>(spilled_addr));
      } else if (value->type == kWasmS128) {
        return WasmValue(Simd128(ReadUnalignedValue<int8x16>(spilled_addr)));
      } else {
        // All other cases should have been handled above.
        UNREACHABLE();
      }
    }
    // Otherwise load the value from the stack.
    Address stack_address = stack_frame_base - value->stack_offset;
    switch (value->type.kind()) {
      case kI32:
        return WasmValue(ReadUnalignedValue<int32_t>(stack_address));
      case kI64:
        return WasmValue(ReadUnalignedValue<int64_t>(stack_address));
      case kF32:
        return WasmValue(ReadUnalignedValue<float>(stack_address));
      case kF64:
        return WasmValue(ReadUnalignedValue<double>(stack_address));
      case kS128:
        return WasmValue(Simd128(ReadUnalignedValue<int8x16>(stack_address)));
      case kRef:
      case kRefNull: {
        DirectHandle<Object> obj(
            Tagged<Object>(ReadUnalignedValue<Address>(stack_address)),
            isolate);
        return WasmValue(obj, value->module->canonical_type(value->type));
      }
      case kI8:
      case kI16:
      case kF16:
      case kVoid:
      case kTop:
      case kBottom:
        UNREACHABLE();
    }
  }
References code, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::DebugSideTable::FindValue(), v8::internal::wasm::LiftoffRegister::from_liftoff_code(), v8::internal::WasmDebugBreakFrameConstants::GetPushedFpRegisterOffset(), v8::internal::WasmDebugBreakFrameConstants::GetPushedGpRegisterOffset(), v8::internal::index, v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::kWasmF32, v8::internal::wasm::kWasmF64, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, v8::internal::wasm::kWasmS128, v8::internal::UNREACHABLE(), and v8::internal::value.
HasRemovedBreakpoints()
static bool v8::internal::wasm::DebugInfoImpl::HasRemovedBreakpoints (const std::vector< int > & removed, const std::vector< int > & remaining) [inline], [static]
Definition at line 501 of file wasm-debug.cc.
                                                                     {
    DCHECK(std::is_sorted(remaining.begin(), remaining.end()));
    for (int offset : removed) {
      // Return true if we removed a breakpoint which is not part of remaining.
      if (!std::binary_search(remaining.begin(), remaining.end(), offset)) {
        return true;
      }
    }
    return false;
  }
References v8::internal::DCHECK().
IsAtReturn()
bool v8::internal::wasm::DebugInfoImpl::IsAtReturn (WasmFrame * frame) [inline], [private]
Definition at line 766 of file wasm-debug.cc.
                                    {
    DisallowGarbageCollection no_gc;
    int position = frame->position();
    NativeModule* native_module = frame->native_module();
    uint8_t opcode = native_module->wire_bytes()[position];
    if (opcode == kExprReturn) return true;
    // Another implicit return is at the last kExprEnd in the function body.
    int func_index = frame->function_index();
    WireBytesRef code = native_module->module()->functions[func_index].code;
    return static_cast<size_t>(position) == code.end_offset() - 1;
  }
References code, v8::internal::wasm::WasmModule::functions, v8::internal::wasm::NativeModule::module(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::wasm::NativeModule::wire_bytes().
IsFrameBlackboxed()
bool v8::internal::wasm::DebugInfoImpl::IsFrameBlackboxed (WasmFrame * frame) [inline]
Definition at line 398 of file wasm-debug.cc.
                                           {
    NativeModule* native_module = frame->native_module();
    int func_index = frame->function_index();
    WireBytesRef func_code =
        native_module->module()->functions[func_index].code;
    Isolate* isolate = frame->isolate();
    DirectHandle<Script> script(Cast<Script>(frame->script()), isolate);
    return isolate->debug()->IsFunctionBlackboxed(script, func_code.offset(),
                                                  func_code.end_offset());
  }
References v8::internal::Isolate::debug(), v8::internal::wasm::WireBytesRef::end_offset(), v8::internal::wasm::WasmModule::functions, v8::internal::Debug::IsFunctionBlackboxed(), v8::internal::Factory::isolate(), v8::internal::wasm::NativeModule::module(), v8::internal::wasm::WireBytesRef::offset(), and v8::internal::script.
IsStepping()
bool v8::internal::wasm::DebugInfoImpl::IsStepping (WasmFrame * frame) [inline]
Definition at line 447 of file wasm-debug.cc.
                                    {
    Isolate* isolate = frame->isolate();
    if (isolate->debug()->last_step_action() == StepInto) return true;
    base::MutexGuard guard(&mutex_);
    auto it = per_isolate_data_.find(isolate);
    return it != per_isolate_data_.end() &&
           it->second.stepping_frame == frame->id();
  }
References v8::internal::Isolate::debug(), v8::internal::Factory::isolate(), v8::internal::Debug::last_step_action(), and v8::internal::StepInto.
operator=()
DebugInfoImpl& v8::internal::wasm::DebugInfoImpl::operator= (const DebugInfoImpl &) [delete]
PrepareStep()
bool v8::internal::wasm::DebugInfoImpl::PrepareStep (WasmFrame * frame) [inline]
Definition at line 409 of file wasm-debug.cc.
                                     {
    WasmCodeRefScope wasm_code_ref_scope;
    wasm::WasmCode* code = frame->wasm_code();
    if (!code->is_liftoff()) return false; // Cannot step in TurboFan code.
    if (IsAtReturn(frame)) return false; // Will return after this step.
    FloodWithBreakpoints(frame, kAfterBreakpoint);
    return true;
  }
References code, and v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::kAfterBreakpoint.
PrepareStepOutTo()
void v8::internal::wasm::DebugInfoImpl::PrepareStepOutTo (WasmFrame * frame) [inline]
Definition at line 418 of file wasm-debug.cc.
                                          {
    WasmCodeRefScope wasm_code_ref_scope;
    wasm::WasmCode* code = frame->wasm_code();
    if (!code->is_liftoff()) return; // Cannot step out to TurboFan code.
    FloodWithBreakpoints(frame, kAfterWasmCall);
  }
References code, and v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::kAfterWasmCall.
RecompileLiftoffWithBreakpoints()
WasmCode* v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints (int func_index, base::Vector< const int > offsets, int dead_breakpoint) [inline]
Definition at line 207 of file wasm-debug.cc.
                                                                 {
    mutex_.AssertHeld(); // Mutex is held externally.
    DCHECK(!v8_flags.wasm_jitless);
    ForDebugging for_debugging = offsets.size() == 1 && offsets[0] == 0
                                     ? kForStepping
                                     : kWithBreakpoints;
    // Check the cache first.
    for (auto begin = cached_debugging_code_.begin(), it = begin,
              end = cached_debugging_code_.end();
         it != end; ++it) {
      if (it->func_index == func_index &&
          it->breakpoint_offsets.as_vector() == offsets &&
          it->dead_breakpoint == dead_breakpoint) {
        // Rotate the cache entry to the front (for LRU).
        for (; it != begin; --it) std::iter_swap(it, it - 1);
        if (for_debugging == kWithBreakpoints) {
          // Re-install the code, in case it was replaced in the meantime.
          native_module_->ReinstallDebugCode(it->code);
        }
        return it->code;
      }
    }
    // Recompile the function with Liftoff, setting the new breakpoints.
    // Not thread-safe. The caller is responsible for locking {mutex_}.
    CompilationEnv env = CompilationEnv::ForModule(native_module_);
    const WasmFunction* function = &env.module->functions[func_index];
    base::Vector<const uint8_t> wire_bytes = native_module_->wire_bytes();
    bool is_shared = env.module->type(function->sig_index).is_shared;
    FunctionBody body{function->sig, function->code.offset(),
                      wire_bytes.begin() + function->code.offset(),
                      wire_bytes.begin() + function->code.end_offset(),
                      is_shared};
    std::unique_ptr<DebugSideTable> debug_sidetable;
    // Debug side tables for stepping are generated lazily.
    bool generate_debug_sidetable = for_debugging == kWithBreakpoints;
    // If lazy validation is on, we might need to lazily validate here.
    if (V8_UNLIKELY(!env.module->function_was_validated(func_index))) {
      WasmDetectedFeatures unused_detected_features;
      Zone validation_zone(wasm::GetWasmEngine()->allocator(), ZONE_NAME);
      DecodeResult validation_result =
          ValidateFunctionBody(&validation_zone, env.enabled_features,
                               env.module, &unused_detected_features, body);
      // Handling illegal modules here is tricky. As lazy validation is off by
      // default anyway and this is for debugging only, we just crash for now.
      CHECK_WITH_MSG(validation_result.ok(),
                     validation_result.error().message().c_str());
      env.module->set_function_validated(func_index);
    }
    WasmCompilationResult result = ExecuteLiftoffCompilation(
        &env, body,
        LiftoffOptions{}
            .set_func_index(func_index)
            .set_for_debugging(for_debugging)
            .set_breakpoints(offsets)
            .set_dead_breakpoint(dead_breakpoint)
            .set_debug_sidetable(generate_debug_sidetable ? &debug_sidetable
                                                          : nullptr));
    // Liftoff compilation failure is a FATAL error. We rely on complete Liftoff
    // support for debugging.
    if (!result.succeeded()) FATAL("Liftoff compilation failed");
    DCHECK_EQ(generate_debug_sidetable, debug_sidetable != nullptr);
    DCHECK_NULL(result.assumptions);
    WasmCode* new_code =
        native_module_->PublishCode(native_module_->AddCompiledCode(result));
    DCHECK(new_code->is_inspectable());
    if (generate_debug_sidetable) {
      base::MutexGuard lock(&debug_side_tables_mutex_);
      DCHECK_EQ(0, debug_side_tables_.count(new_code));
      debug_side_tables_.emplace(new_code, std::move(debug_sidetable));
    }
    // Insert new code into the cache. Insert before existing elements for LRU.
    cached_debugging_code_.insert(
        cached_debugging_code_.begin(),
        CachedDebuggingCode{func_index, base::OwnedCopyOf(offsets),
                            dead_breakpoint, new_code});
    // Increase the ref count (for the cache entry).
    new_code->IncRef();
    // Remove exceeding element.
    if (cached_debugging_code_.size() > kMaxCachedDebuggingCode) {
      // Put the code in the surrounding CodeRefScope to delay deletion until
      // after the mutex is released.
      WasmCodeRefScope::AddRef(cached_debugging_code_.back().code);
      cached_debugging_code_.back().code->DecRefOnLiveCode();
      cached_debugging_code_.pop_back();
    }
    DCHECK_GE(kMaxCachedDebuggingCode, cached_debugging_code_.size());
    return new_code;
  }
References v8::internal::wasm::WasmCodeRefScope::AddRef(), v8::base::Vector< T >::begin(), v8::internal::compiler::begin(), CHECK_WITH_MSG, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_NULL, v8::internal::wasm::CompilationEnv::enabled_features, v8::internal::compiler::end(), v8::internal::wasm::Result< T >::error(), v8::internal::wasm::ExecuteLiftoffCompilation(), FATAL, v8::internal::wasm::CompilationEnv::ForModule(), v8::internal::wasm::WasmModule::function_was_validated(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::GetWasmEngine(), v8::internal::wasm::WasmCode::IncRef(), v8::internal::wasm::WasmCode::is_inspectable(), v8::internal::is_shared, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::kForStepping, v8::internal::wasm::kWithBreakpoints, v8::internal::wasm::WasmError::message(), v8::internal::wasm::CompilationEnv::module, v8::internal::wasm::Result< T >::ok(), v8::base::internal::result, v8::internal::wasm::WasmModule::set_function_validated(), v8::internal::wasm::FunctionBody::sig, v8::base::Vector< T >::size(), v8::internal::wasm::WasmModule::type(), v8::internal::v8_flags, V8_UNLIKELY, v8::internal::wasm::ValidateFunctionBody(), and ZONE_NAME.
RemoveBreakpoint()
void v8::internal::wasm::DebugInfoImpl::RemoveBreakpoint (int func_index, int position, Isolate * isolate) [inline]
Definition at line 456 of file wasm-debug.cc.
                                                                        {
    // Put the code ref scope outside of the mutex, so we don't unnecessarily
    // hold the mutex while freeing code.
    WasmCodeRefScope wasm_code_ref_scope;
    // Hold the mutex while modifying breakpoints, to ensure consistency when
    // multiple isolates set/remove breakpoints at the same time.
    base::MutexGuard guard(&mutex_);
    const auto& function = native_module_->module()->functions[func_index];
    int offset = position - function.code.offset();
    auto& isolate_data = per_isolate_data_[isolate];
    std::vector<int>& breakpoints =
        isolate_data.breakpoints_per_function[func_index];
    DCHECK_LT(0, offset);
    auto insertion_point =
        std::lower_bound(breakpoints.begin(), breakpoints.end(), offset);
    if (insertion_point == breakpoints.end()) return;
    if (*insertion_point != offset) return;
    breakpoints.erase(insertion_point);
    std::vector<int> remaining = FindAllBreakpoints(func_index);
    // If the breakpoint is still set in another isolate, don't remove it.
    DCHECK(std::is_sorted(remaining.begin(), remaining.end()));
    if (std::binary_search(remaining.begin(), remaining.end(), offset)) return;
    int dead_breakpoint =
        DeadBreakpoint(func_index, base::VectorOf(remaining), isolate);
    UpdateBreakpoints(func_index, base::VectorOf(remaining), isolate,
                      isolate_data.stepping_frame, dead_breakpoint);
  }
References v8::internal::DCHECK(), DCHECK_LT, and v8::base::VectorOf().
RemoveDebugSideTables()
void v8::internal::wasm::DebugInfoImpl::RemoveDebugSideTables (base::Vector< WasmCode *const > codes) [inline]
Definition at line 488 of file wasm-debug.cc.
                                                                {
    base::MutexGuard guard(&debug_side_tables_mutex_);
    for (auto* code : codes) {
      debug_side_tables_.erase(code);
    }
  }
References code.
RemoveIsolate()
void v8::internal::wasm::DebugInfoImpl::RemoveIsolate (Isolate * isolate) [inline]
Definition at line 513 of file wasm-debug.cc.
                                       {
    // Put the code ref scope outside of the mutex, so we don't unnecessarily
    // hold the mutex while freeing code.
    WasmCodeRefScope wasm_code_ref_scope;
    base::MutexGuard guard(&mutex_);
    auto per_isolate_data_it = per_isolate_data_.find(isolate);
    if (per_isolate_data_it == per_isolate_data_.end()) return;
    std::unordered_map<int, std::vector<int>> removed_per_function =
        std::move(per_isolate_data_it->second.breakpoints_per_function);
    per_isolate_data_.erase(per_isolate_data_it);
    for (auto& entry : removed_per_function) {
      int func_index = entry.first;
      std::vector<int>& removed = entry.second;
      std::vector<int> remaining = FindAllBreakpoints(func_index);
      if (HasRemovedBreakpoints(removed, remaining)) {
        RecompileLiftoffWithBreakpoints(func_index, base::VectorOf(remaining),
                                        0);
      }
    }
  }
References v8::base::VectorOf().
SetBreakpoint()
void v8::internal::wasm::DebugInfoImpl::SetBreakpoint (int func_index, int offset, Isolate * isolate) [inline]
Definition at line 306 of file wasm-debug.cc.
                                                                   {
    // TODO(paolosev@microsoft.com) - Add support for breakpoints in Wasm
    // interpreter.
    if (v8_flags.wasm_jitless) return;
    // Put the code ref scope outside of the mutex, so we don't unnecessarily
    // hold the mutex while freeing code.
    WasmCodeRefScope wasm_code_ref_scope;
    // Hold the mutex while modifying breakpoints, to ensure consistency when
    // multiple isolates set/remove breakpoints at the same time.
    base::MutexGuard guard(&mutex_);
    // offset == 0 indicates flooding and should not happen here.
    DCHECK_NE(0, offset);
    // Get the set of previously set breakpoints, to check later whether a new
    // breakpoint was actually added.
    std::vector<int> all_breakpoints = FindAllBreakpoints(func_index);
    auto& isolate_data = per_isolate_data_[isolate];
    std::vector<int>& breakpoints =
        isolate_data.breakpoints_per_function[func_index];
    auto insertion_point =
        std::lower_bound(breakpoints.begin(), breakpoints.end(), offset);
    if (insertion_point != breakpoints.end() && *insertion_point == offset) {
      // The breakpoint is already set for this isolate.
      return;
    }
    breakpoints.insert(insertion_point, offset);
    DCHECK(std::is_sorted(all_breakpoints.begin(), all_breakpoints.end()));
    // Find the insertion position within {all_breakpoints}.
    insertion_point = std::lower_bound(all_breakpoints.begin(),
                                       all_breakpoints.end(), offset);
    bool breakpoint_exists =
        insertion_point != all_breakpoints.end() && *insertion_point == offset;
    // If the breakpoint was already set before, then we can just reuse the old
    // code. Otherwise, recompile it. In any case, rewrite this isolate's stack
    // to make sure that it uses up-to-date code containing the breakpoint.
    WasmCode* new_code;
    if (breakpoint_exists) {
      new_code = native_module_->GetCode(func_index);
    } else {
      all_breakpoints.insert(insertion_point, offset);
      int dead_breakpoint =
          DeadBreakpoint(func_index, base::VectorOf(all_breakpoints), isolate);
      new_code = RecompileLiftoffWithBreakpoints(
          func_index, base::VectorOf(all_breakpoints), dead_breakpoint);
    }
    UpdateReturnAddresses(isolate, new_code, isolate_data.stepping_frame);
  }
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::v8_flags, and v8::base::VectorOf().
UpdateBreakpoints()
void v8::internal::wasm::DebugInfoImpl::UpdateBreakpoints (int func_index, base::Vector< int > breakpoints, Isolate * isolate, StackFrameId stepping_frame, int dead_breakpoint) [inline]
Definition at line 370 of file wasm-debug.cc.
                                              {
    // TODO(paolosev@microsoft.com) - Add support for breakpoints in Wasm
    // interpreter.
    if (v8_flags.wasm_jitless) return;
    mutex_.AssertHeld(); // Mutex is held externally.
    WasmCode* new_code = RecompileLiftoffWithBreakpoints(
        func_index, breakpoints, dead_breakpoint);
    UpdateReturnAddresses(isolate, new_code, stepping_frame);
  }
References v8::internal::v8_flags.
UpdateReturnAddress()
void v8::internal::wasm::DebugInfoImpl::UpdateReturnAddress (WasmFrame * frame, WasmCode * new_code, ReturnLocation return_location) [inline], [private]
Definition at line 743 of file wasm-debug.cc.
                                                           {
    DCHECK(new_code->is_liftoff());
    DCHECK_EQ(frame->function_index(), new_code->index());
    DCHECK_EQ(frame->native_module(), new_code->native_module());
    DCHECK(frame->wasm_code()->is_liftoff());
    Address new_pc = FindNewPC(frame, new_code, frame->generated_code_offset(),
                               return_location);
#ifdef DEBUG
    int old_position = frame->position();
#endif
#if V8_TARGET_ARCH_X64
    if (frame->wasm_code()->for_debugging()) {
      base::Memory<Address>(frame->fp() - kOSRTargetOffset) = new_pc;
    }
#else
    PointerAuthentication::ReplacePC(frame->pc_address(), new_pc,
                                     kSystemPointerSize);
#endif
    // The frame position should still be the same after OSR.
    DCHECK_EQ(old_position, frame->position());
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::FindNewPC(), v8::internal::wasm::WasmCode::index(), v8::internal::wasm::WasmCode::is_liftoff(), v8::internal::kSystemPointerSize, v8::internal::wasm::WasmCode::native_module(), and v8::internal::PointerAuthentication::ReplacePC().
UpdateReturnAddresses()
void v8::internal::wasm::DebugInfoImpl::UpdateReturnAddresses (Isolate * isolate, WasmCode * new_code, StackFrameId stepping_frame) [inline], [private]
Definition at line 720 of file wasm-debug.cc.
                                                          {
    // The first return location is after the breakpoint, others are after wasm
    // calls.
    ReturnLocation return_location = kAfterBreakpoint;
    for (DebuggableStackFrameIterator it(isolate); !it.done();
         it.Advance(), return_location = kAfterWasmCall) {
      // We still need the flooded function for stepping.
      if (it.frame()->id() == stepping_frame) continue;
#if !V8_ENABLE_DRUMBRAKE
      if (!it.is_wasm()) continue;
#else // !V8_ENABLE_DRUMBRAKE
      // TODO(paolosev@microsoft.com) - Implement for Wasm interpreter.
      if (!it.is_wasm() || it.is_wasm_interpreter_entry()) continue;
#endif // !V8_ENABLE_DRUMBRAKE
      WasmFrame* frame = WasmFrame::cast(it.frame());
      if (frame->native_module() != new_code->native_module()) continue;
      if (frame->function_index() != new_code->index()) continue;
      if (!frame->wasm_code()->is_liftoff()) continue;
      UpdateReturnAddress(frame, new_code, return_location);
    }
  }
References v8::internal::DebuggableStackFrameIterator::done(), v8::internal::wasm::WasmCode::index(), v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::kAfterBreakpoint, v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::kAfterWasmCall, and v8::internal::wasm::WasmCode::native_module().
Member Data Documentation
cached_debugging_code_
std::vector<CachedDebuggingCode> v8::internal::wasm::DebugInfoImpl::cached_debugging_code_ [private]
Definition at line 812 of file wasm-debug.cc.
debug_side_tables_
std::unordered_map<const WasmCode*, std::unique_ptr<DebugSideTable> > v8::internal::wasm::DebugInfoImpl::debug_side_tables_ [private]
Definition at line 796 of file wasm-debug.cc.
debug_side_tables_mutex_
base::Mutex v8::internal::wasm::DebugInfoImpl::debug_side_tables_mutex_ [mutable], [private]
Definition at line 792 of file wasm-debug.cc.
kMaxCachedDebuggingCode
constexpr size_t v8::internal::wasm::DebugInfoImpl::kMaxCachedDebuggingCode = 3 [static], [constexpr], [private]
Definition at line 805 of file wasm-debug.cc.
mutex_
base::Mutex v8::internal::wasm::DebugInfoImpl::mutex_ [mutable], [private]
Definition at line 799 of file wasm-debug.cc.
native_module_
NativeModule* const v8::internal::wasm::DebugInfoImpl::native_module_ [private]
Definition at line 790 of file wasm-debug.cc.
per_isolate_data_
std::unordered_map<Isolate*, PerIsolateDebugData> v8::internal::wasm::DebugInfoImpl::per_isolate_data_ [private]
Definition at line 815 of file wasm-debug.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-debug.cc