v8::internal::torque::Macro Class Reference
#include <declarable.h>
Public Member Functions
bool ShouldBeInlined (OutputType output_type) const override
void SetUsed ()
bool IsUsed () const
Protected Member Functions
Macro (Declarable::Kind kind, std::string external_name, std::string readable_name, const Signature &signature, std::optional< Statement * > body)
Private Attributes
bool used_
Additional Inherited Members
Detailed Description
Definition at line 373 of file declarable.h.
Constructor & Destructor Documentation
Macro()
v8::internal::torque::Macro::Macro (Declarable::Kind kind, std::string external_name, std::string readable_name, const Signature & signature, std::optional< Statement * > body) [inline], [protected]
Definition at line 392 of file declarable.h.
      : Callable(kind, std::move(external_name), std::move(readable_name),
                 signature, body),
        used_(false) {
    if (signature.parameter_types.var_args) {
      ReportError("Varargs are not supported for macros.");
    }
  }
References v8::internal::torque::Signature::parameter_types, v8::internal::torque::ReportError(), v8::internal::torque::Callable::signature(), and v8::internal::torque::ParameterTypes::var_args.
Member Function Documentation
IsUsed()
bool v8::internal::torque::Macro::IsUsed () const [inline]
Definition at line 389 of file declarable.h.
{ return used_; }
References used_.
Referenced by v8::internal::torque::ReportAllUnusedMacros().
SetUsed()
void v8::internal::torque::Macro::SetUsed () [inline]
Definition at line 388 of file declarable.h.
{ used_ = true; }
References used_.
ShouldBeInlined()
bool v8::internal::torque::Macro::ShouldBeInlined (OutputType output_type) const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Callable.
Reimplemented in v8::internal::torque::Method.
Definition at line 376 of file declarable.h.
                                                              {
    for (const LabelDeclaration& label : signature().labels) {
      for (const Type* type : label.types) {
        if (type->StructSupertype()) return true;
      }
    }
    // Intrinsics that are used internally in Torque and implemented as torque
    // code should be inlined and not generate C++ definitions.
    if (ReadableName()[0] == '%') return true;
    return Callable::ShouldBeInlined(output_type);
  }
References v8::internal::torque::Callable::ReadableName(), v8::internal::torque::Callable::ShouldBeInlined(), v8::internal::torque::Callable::signature(), and v8::internal::tracing::type.
Referenced by v8::internal::torque::Method::ShouldBeInlined().
Member Data Documentation
used_
bool v8::internal::torque::Macro::used_ [private]
Definition at line 404 of file declarable.h.
Referenced by IsUsed(), and SetUsed().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/declarable.h