v8::internal::SourcePositionTable Class Reference
#include <profile-generator.h>
Classes
struct SourcePositionTuple
Public Member Functions
SourcePositionTable ()=default
SourcePositionTable (const SourcePositionTable &)=delete
SourcePositionTable & operator= (const SourcePositionTable &)=delete
void SetPosition (int pc_offset, LineAndColumn line_and_column, int inlining_id)
int GetSourceLineNumber (int pc_offset) const
int GetSourceColumnNumber (int pc_offset) const
LineAndColumn GetSourceLineAndColumn (int pc_offset) const
int GetInliningId (int pc_offset) const
size_t Size () const
void print () const
Private Member Functions
const SourcePositionTuple & GetTuple (int pc_offset) const
Private Attributes
std::vector< SourcePositionTuple > pc_offsets_to_lines_
Additional Inherited Members
Detailed Description
Definition at line 39 of file profile-generator.h.
Constructor & Destructor Documentation
SourcePositionTable() [1/2]
v8::internal::SourcePositionTable::SourcePositionTable () [default]
SourcePositionTable() [2/2]
v8::internal::SourcePositionTable::SourcePositionTable (const SourcePositionTable &) [delete]
Member Function Documentation
GetInliningId()
int v8::internal::SourcePositionTable::GetInliningId (int pc_offset) const
Definition at line 63 of file profile-generator.cc.
                                                          {
  return GetTuple(pc_offset).inlining_id;
}
References GetTuple(), and v8::internal::SourcePositionTable::SourcePositionTuple::inlining_id.
GetSourceColumnNumber()
int v8::internal::SourcePositionTable::GetSourceColumnNumber (int pc_offset) const
Definition at line 54 of file profile-generator.cc.
                                                                  {
  return GetTuple(pc_offset).column_number;
}
References v8::internal::SourcePositionTable::SourcePositionTuple::column_number, and GetTuple().
GetSourceLineAndColumn()
LineAndColumn v8::internal::SourcePositionTable::GetSourceLineAndColumn (int pc_offset) const
Definition at line 58 of file profile-generator.cc.
                                                                             {
  auto& tuple = GetTuple(pc_offset);
  return {tuple.line_number, tuple.column_number};
}
References GetTuple().
GetSourceLineNumber()
int v8::internal::SourcePositionTable::GetSourceLineNumber (int pc_offset) const
Definition at line 50 of file profile-generator.cc.
                                                                {
  return GetTuple(pc_offset).line_number;
}
References GetTuple(), and v8::internal::SourcePositionTable::SourcePositionTuple::line_number.
GetTuple()
const SourcePositionTable::SourcePositionTuple & v8::internal::SourcePositionTable::GetTuple (int pc_offset) const [private]
Definition at line 67 of file profile-generator.cc.
                         {
  if (pc_offsets_to_lines_.empty()) {
    static constexpr SourcePositionTuple kEmptyTuple = {
        -1, v8::CpuProfileNode::kNoLineNumberInfo,
        v8::CpuProfileNode::kNoColumnNumberInfo, SourcePosition::kNotInlined};
    return kEmptyTuple;
  }
  auto it = std::lower_bound(
      pc_offsets_to_lines_.begin(), pc_offsets_to_lines_.end(),
      SourcePositionTuple{pc_offset, 0, 0, SourcePosition::kNotInlined});
  if (it != pc_offsets_to_lines_.begin()) --it;
  return *it;
}
References v8::CpuProfileNode::kNoColumnNumberInfo, v8::CpuProfileNode::kNoLineNumberInfo, v8::internal::SourcePosition::kNotInlined, and pc_offsets_to_lines_.
Referenced by GetInliningId(), GetSourceColumnNumber(), GetSourceLineAndColumn(), and GetSourceLineNumber().
operator=()
SourcePositionTable& v8::internal::SourcePositionTable::operator= (const SourcePositionTable &) [delete]
print()
void v8::internal::SourcePositionTable::print () const
Definition at line 87 of file profile-generator.cc.
                                      {
  base::OS::Print(" - source position table at %p\n", this);
  for (const SourcePositionTuple& pos_info : pc_offsets_to_lines_) {
    base::OS::Print(" %d --> line_number: %d inlining_id: %d\n",
                    pos_info.pc_offset, pos_info.line_number,
                    pos_info.inlining_id);
  }
}
References pc_offsets_to_lines_, and v8::internal::Print().
SetPosition()
void v8::internal::SourcePositionTable::SetPosition (int pc_offset, LineAndColumn line_and_column, int inlining_id)
Definition at line 25 of file profile-generator.cc.
                                                       {
  DCHECK_GE(pc_offset, 0);
  DCHECK_GT(pos.line, 0); // The 1-based number of the source line.
  // It's possible that we map multiple source positions to a pc_offset in
  // optimized code. Usually these map to the same line, so there is no
  // difference here as we only store line number and not line/col in the form
  // of a script offset. Ignore any subsequent sets to the same offset.
  if (!pc_offsets_to_lines_.empty() &&
      pc_offsets_to_lines_.back().pc_offset == pc_offset) {
    return;
  }
  // Check that we are inserting in ascending order, so that the vector remains
  // sorted.
  DCHECK(pc_offsets_to_lines_.empty() ||
         pc_offsets_to_lines_.back().pc_offset < pc_offset);
  if (pc_offsets_to_lines_.empty() ||
      pc_offsets_to_lines_.back().line_number != pos.line ||
      pc_offsets_to_lines_.back().column_number != pos.column ||
      pc_offsets_to_lines_.back().inlining_id != inlining_id) {
    pc_offsets_to_lines_.push_back(
        {pc_offset, pos.line, pos.column, inlining_id});
  }
}
References v8::internal::LineAndColumn::column, v8::internal::DCHECK(), DCHECK_GE, DCHECK_GT, v8::internal::LineAndColumn::line, and pc_offsets_to_lines_.
Size()
size_t v8::internal::SourcePositionTable::Size () const
Definition at line 82 of file profile-generator.cc.
                                       {
  return sizeof(*this) + pc_offsets_to_lines_.capacity() *
                             sizeof(decltype(pc_offsets_to_lines_)::value_type);
}
References pc_offsets_to_lines_, and v8::internal::wasm::value_type().
Member Data Documentation
pc_offsets_to_lines_
std::vector<SourcePositionTuple> v8::internal::SourcePositionTable::pc_offsets_to_lines_ [private]
Definition at line 71 of file profile-generator.h.
Referenced by GetTuple(), print(), SetPosition(), and Size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/profile-generator.h
/mnt/V8SourceCode/src/profiler/profile-generator.cc