v8::internal::ArrayBuiltinsAssembler Class Reference
#include <builtins-array-gen.h>
Public Types
using BuiltinResultGenerator = std::function< void(ArrayBuiltinsAssembler *masm)>
using CallResultProcessor = std::function< TNode< JSAny >(ArrayBuiltinsAssembler *masm, TNode< Object > k_value, TNode< UintPtrT > k)>
Public Member Functions
ArrayBuiltinsAssembler (compiler::CodeAssemblerState *state)
void TypedArrayMapResultGenerator ()
TNode< JSAny > TypedArrayMapProcessor (TNode< Object > k_value, TNode< UintPtrT > k)
TNode< String > CallJSArrayArrayJoinConcatToSequentialString (TNode< FixedArray > fixed_array, TNode< IntPtrT > length, TNode< String > sep, TNode< String > dest)
Protected Member Functions
TNode< Context > context ()
TNode< JSAny > receiver ()
TNode< IntPtrT > argc ()
TNode< JSReceiver > o ()
TNode< UintPtrT > len ()
TNode< Object > callbackfn ()
TNode< JSAny > this_arg ()
TNode< UintPtrT > k ()
TNode< JSAny > a ()
void ReturnFromBuiltin (TNode< Object > value)
void InitIteratingArrayBuiltinBody (TNode< Context > context, TNode< JSAny > receiver, TNode< Object > callbackfn, TNode< JSAny > this_arg, TNode< IntPtrT > argc)
void GenerateIteratingTypedArrayBuiltinBody (const char *name, const BuiltinResultGenerator &generator, const CallResultProcessor &processor, ForEachDirection direction=ForEachDirection::kForward)
void TailCallArrayConstructorStub (const Callable &callable, TNode< Context > context, TNode< JSFunction > target, TNode< HeapObject > allocation_site_or_undefined, TNode< Int32T > argc)
void GenerateDispatchToArrayStub (TNode< Context > context, TNode< JSFunction > target, TNode< Int32T > argc, AllocationSiteOverrideMode mode, std::optional< TNode< AllocationSite >> allocation_site=std::nullopt)
void CreateArrayDispatchNoArgument (TNode< Context > context, TNode< JSFunction > target, TNode< Int32T > argc, AllocationSiteOverrideMode mode, std::optional< TNode< AllocationSite >> allocation_site)
void CreateArrayDispatchSingleArgument (TNode< Context > context, TNode< JSFunction > target, TNode< Int32T > argc, AllocationSiteOverrideMode mode, std::optional< TNode< AllocationSite >> allocation_site)
void GenerateConstructor (TNode< Context > context, TNode< JSAnyNotSmi > array_function, TNode< Map > array_map, TNode< Object > array_size, TNode< HeapObject > allocation_site, ElementsKind elements_kind, AllocationSiteMode mode)
void GenerateArrayNoArgumentConstructor (ElementsKind kind, AllocationSiteOverrideMode mode)
void GenerateArraySingleArgumentConstructor (ElementsKind kind, AllocationSiteOverrideMode mode)
void GenerateArrayNArgumentsConstructor (TNode< Context > context, TNode< JSFunction > target, TNode< Object > new_target, TNode< Int32T > argc, TNode< HeapObject > maybe_allocation_site)
Private Member Functions
void VisitAllTypedArrayElements (TNode< JSArrayBuffer > array_buffer, const CallResultProcessor &processor, ForEachDirection direction, TNode< JSTypedArray > typed_array)
Private Attributes
TNode< Object > callbackfn_
TNode< JSReceiver > o_
TNode< JSAny > this_arg_
TNode< UintPtrT > len_
TNode< Context > context_
TNode< JSAny > receiver_
TNode< IntPtrT > argc_
TNode< BoolT > fast_typed_array_target_
const char * name_ = nullptr
TVariable< UintPtrT > k_
TVariable< JSAny > a_
Label fully_spec_compliant_
ElementsKind source_elements_kind_ = ElementsKind::NO_ELEMENTS
Additional Inherited Members
Detailed Description
Definition at line 16 of file builtins-array-gen.h.
Member Typedef Documentation
BuiltinResultGenerator
using v8::internal::ArrayBuiltinsAssembler::BuiltinResultGenerator = std::function<void(ArrayBuiltinsAssembler* masm)>
Definition at line 20 of file builtins-array-gen.h.
CallResultProcessor
using v8::internal::ArrayBuiltinsAssembler::CallResultProcessor = std::function<TNode<JSAny>(ArrayBuiltinsAssembler* masm, TNode<Object> k_value, TNode<UintPtrT> k)>
Definition at line 23 of file builtins-array-gen.h.
Constructor & Destructor Documentation
ArrayBuiltinsAssembler()
v8::internal::ArrayBuiltinsAssembler::ArrayBuiltinsAssembler (compiler::CodeAssemblerState * state) [explicit]
Definition at line 32 of file builtins-array-gen.cc.
    : CodeStubAssembler(state),
      k_(this),
      a_(this),
      fully_spec_compliant_(this, {&k_, &a_}) {}
References a_, and k_.
Member Function Documentation
a()
TNode<JSAny> v8::internal::ArrayBuiltinsAssembler::a () [inline], [protected]
Definition at line 57 of file builtins-array-gen.h.
{ return a_.value(); }
References a_.
Referenced by TypedArrayMapProcessor(), and TypedArrayMapResultGenerator().
argc()
TNode<IntPtrT> v8::internal::ArrayBuiltinsAssembler::argc () [inline], [protected]
Definition at line 51 of file builtins-array-gen.h.
{ return argc_; }
References argc_.
Referenced by CreateArrayDispatchNoArgument(), CreateArrayDispatchSingleArgument(), GenerateArrayNArgumentsConstructor(), GenerateDispatchToArrayStub(), InitIteratingArrayBuiltinBody(), ReturnFromBuiltin(), and TailCallArrayConstructorStub().
callbackfn()
TNode<Object> v8::internal::ArrayBuiltinsAssembler::callbackfn () [inline], [protected]
Definition at line 54 of file builtins-array-gen.h.
{ return callbackfn_; }
References callbackfn_.
Referenced by InitIteratingArrayBuiltinBody(), and TypedArrayMapProcessor().
CallJSArrayArrayJoinConcatToSequentialString()
TNode<String> v8::internal::ArrayBuiltinsAssembler::CallJSArrayArrayJoinConcatToSequentialString (TNode< FixedArray > fixed_array, TNode< IntPtrT > length, TNode< String > sep, TNode< String > dest) [inline]
Definition at line 31 of file builtins-array-gen.h.
                          {
    TNode<ExternalReference> func = ExternalConstant(
        ExternalReference::jsarray_array_join_concat_to_sequential_string());
    TNode<ExternalReference> isolate_ptr =
        ExternalConstant(ExternalReference::isolate_address());
    return UncheckedCast<String>(
        CallCFunction(func,
                      MachineType::AnyTagged(), // <return> String
                      std::make_pair(MachineType::Pointer(), isolate_ptr),
                      std::make_pair(MachineType::AnyTagged(), fixed_array),
                      std::make_pair(MachineType::IntPtr(), length),
                      std::make_pair(MachineType::AnyTagged(), sep),
                      std::make_pair(MachineType::AnyTagged(), dest)));
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::MachineType::IntPtr(), v8::internal::ExternalReference::isolate_address(), v8::internal::length, and v8::internal::MachineType::Pointer().
context()
TNode<Context> v8::internal::ArrayBuiltinsAssembler::context () [inline], [protected]
Definition at line 49 of file builtins-array-gen.h.
{ return context_; }
References context_.
Referenced by CreateArrayDispatchNoArgument(), CreateArrayDispatchSingleArgument(), GenerateArrayNArgumentsConstructor(), GenerateArraySingleArgumentConstructor(), GenerateConstructor(), GenerateDispatchToArrayStub(), InitIteratingArrayBuiltinBody(), TailCallArrayConstructorStub(), TypedArrayMapProcessor(), and TypedArrayMapResultGenerator().
CreateArrayDispatchNoArgument()
void v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchNoArgument (TNode< Context > context, TNode< JSFunction > target, TNode< Int32T > argc, AllocationSiteOverrideMode mode, std::optional< TNode< AllocationSite >> allocation_site) [protected]
Definition at line 1670 of file builtins-array-gen.cc.
                                                        {
  if (mode == DISABLE_ALLOCATION_SITES) {
    Callable callable = CodeFactory::ArrayNoArgumentConstructor(
        isolate(), GetInitialFastElementsKind(), mode);
    TailCallArrayConstructorStub(callable, context, target, UndefinedConstant(),
                                 argc);
  } else {
    DCHECK_EQ(mode, DONT_OVERRIDE);
    DCHECK(allocation_site);
    TNode<Int32T> elements_kind = LoadElementsKind(*allocation_site);
    // TODO(ishell): Compute the builtin index dynamically instead of
    // iterating over all expected elements kinds.
    int last_index =
        GetSequenceIndexFromFastElementsKind(TERMINAL_FAST_ELEMENTS_KIND);
    for (int i = 0; i <= last_index; ++i) {
      Label next(this);
      ElementsKind kind = GetFastElementsKindFromSequenceIndex(i);
      GotoIfNot(Word32Equal(elements_kind, Int32Constant(kind)), &next);
      Callable callable =
          CodeFactory::ArrayNoArgumentConstructor(isolate(), kind, mode);
      TailCallArrayConstructorStub(callable, context, target, *allocation_site,
                                   argc);
      BIND(&next);
    }
    // If we reached this point there is a problem.
    Abort(AbortReason::kUnexpectedElementsKindInArrayConstructor);
  }
}
References v8::internal::CodeStubAssembler::Abort(), argc(), v8::internal::CodeFactory::ArrayNoArgumentConstructor(), context(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::DISABLE_ALLOCATION_SITES, v8::internal::DONT_OVERRIDE, v8::internal::GetFastElementsKindFromSequenceIndex(), v8::internal::GetInitialFastElementsKind(), v8::internal::GetSequenceIndexFromFastElementsKind(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::CodeStubAssembler::LoadElementsKind(), mode(), TailCallArrayConstructorStub(), v8::internal::TERMINAL_FAST_ELEMENTS_KIND, v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by GenerateDispatchToArrayStub().
CreateArrayDispatchSingleArgument()
void v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchSingleArgument (TNode< Context > context, TNode< JSFunction > target, TNode< Int32T > argc, AllocationSiteOverrideMode mode, std::optional< TNode< AllocationSite >> allocation_site) [protected]
Definition at line 1708 of file builtins-array-gen.cc.
                                                        {
  if (mode == DISABLE_ALLOCATION_SITES) {
    ElementsKind initial = GetInitialFastElementsKind();
    ElementsKind holey_initial = GetHoleyElementsKind(initial);
    Callable callable = CodeFactory::ArraySingleArgumentConstructor(
        isolate(), holey_initial, mode);
    TailCallArrayConstructorStub(callable, context, target, UndefinedConstant(),
                                 argc);
  } else {
    DCHECK_EQ(mode, DONT_OVERRIDE);
    DCHECK(allocation_site);
    TNode<Smi> transition_info = LoadTransitionInfo(*allocation_site);
    // Least significant bit in fast array elements kind means holeyness.
    static_assert(PACKED_SMI_ELEMENTS == 0);
    static_assert(HOLEY_SMI_ELEMENTS == 1);
    static_assert(PACKED_ELEMENTS == 2);
    static_assert(HOLEY_ELEMENTS == 3);
    static_assert(PACKED_DOUBLE_ELEMENTS == 4);
    static_assert(HOLEY_DOUBLE_ELEMENTS == 5);
    Label normal_sequence(this);
    TVARIABLE(Int32T, var_elements_kind,
              Signed(DecodeWord32<AllocationSite::ElementsKindBits>(
                  SmiToInt32(transition_info))));
    // Is the low bit set? If so, we are holey and that is good.
    int fast_elements_kind_holey_mask =
        AllocationSite::ElementsKindBits::encode(static_cast<ElementsKind>(1));
    GotoIf(IsSetSmi(transition_info, fast_elements_kind_holey_mask),
           &normal_sequence);
    {
      // Make elements kind holey and update elements kind in the type info.
      var_elements_kind = Word32Or(var_elements_kind.value(), Int32Constant(1));
      StoreObjectFieldNoWriteBarrier(
          *allocation_site,
          offsetof(AllocationSite, transition_info_or_boilerplate_),
          SmiOr(transition_info, SmiConstant(fast_elements_kind_holey_mask)));
      Goto(&normal_sequence);
    }
    BIND(&normal_sequence);
    // TODO(ishell): Compute the builtin index dynamically instead of
    // iterating over all expected elements kinds.
    // TODO(ishell): Given that the code above ensures that the elements kind
    // is holey we can skip checking with non-holey elements kinds.
    int last_index =
        GetSequenceIndexFromFastElementsKind(TERMINAL_FAST_ELEMENTS_KIND);
    for (int i = 0; i <= last_index; ++i) {
      Label next(this);
      ElementsKind kind = GetFastElementsKindFromSequenceIndex(i);
      GotoIfNot(Word32Equal(var_elements_kind.value(), Int32Constant(kind)),
                &next);
      Callable callable =
          CodeFactory::ArraySingleArgumentConstructor(isolate(), kind, mode);
      TailCallArrayConstructorStub(callable, context, target, *allocation_site,
                                   argc);
      BIND(&next);
    }
    // If we reached this point there is a problem.
    Abort(AbortReason::kUnexpectedElementsKindInArrayConstructor);
  }
}
References v8::internal::CodeStubAssembler::Abort(), argc(), v8::internal::CodeFactory::ArraySingleArgumentConstructor(), context(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::DISABLE_ALLOCATION_SITES, v8::internal::DONT_OVERRIDE, v8::base::BitField< T, shift, size, U >::encode(), v8::internal::GetFastElementsKindFromSequenceIndex(), v8::internal::GetHoleyElementsKind(), v8::internal::GetInitialFastElementsKind(), v8::internal::GetSequenceIndexFromFastElementsKind(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::CodeStubAssembler::IsSetSmi(), v8::internal::CodeStubAssembler::LoadTransitionInfo(), mode(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, v8::internal::compiler::CodeAssembler::Signed(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::SmiToInt32(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), TailCallArrayConstructorStub(), v8::internal::TERMINAL_FAST_ELEMENTS_KIND, v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), v8::internal::compiler::CodeAssembler::Word32Equal(), and v8::internal::compiler::CodeAssembler::Word32Or().
Referenced by GenerateDispatchToArrayStub().
GenerateArrayNArgumentsConstructor()
void v8::internal::ArrayBuiltinsAssembler::GenerateArrayNArgumentsConstructor (TNode< Context > context, TNode< JSFunction > target, TNode< Object > new_target, TNode< Int32T > argc, TNode< HeapObject > maybe_allocation_site) [protected]
Definition at line 1928 of file builtins-array-gen.cc.
                                                                 {
  // Replace incoming JS receiver argument with the target.
  // TODO(ishell): Avoid replacing the target on the stack and just add it
  // as another additional parameter for Runtime::kNewArray.
  CodeStubArguments args(this, argc);
  args.SetReceiver(target);
  // Adjust arguments count for the runtime call:
  // +2 for new_target and maybe_allocation_site.
  argc = Int32Add(TruncateIntPtrToInt32(args.GetLengthWithReceiver()),
                  Int32Constant(2));
  TailCallRuntime(Runtime::kNewArray, argc, context, new_target,
                  maybe_allocation_site);
}
References argc(), v8::base::args, context(), v8::internal::compiler::CodeAssembler::Int32Add(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::TailCallRuntime(), and v8::internal::CodeStubAssembler::TruncateIntPtrToInt32().
GenerateArrayNoArgumentConstructor()
void v8::internal::ArrayBuiltinsAssembler::GenerateArrayNoArgumentConstructor (ElementsKind kind, AllocationSiteOverrideMode mode) [protected]
Definition at line 1886 of file builtins-array-gen.cc.
                                                        {
  using Descriptor = ArrayNoArgumentConstructorDescriptor;
  TNode<NativeContext> native_context = LoadObjectField<NativeContext>(
      Parameter<HeapObject>(Descriptor::kFunction), JSFunction::kContextOffset);
  bool track_allocation_site =
      AllocationSite::ShouldTrack(kind) && mode != DISABLE_ALLOCATION_SITES;
  std::optional<TNode<AllocationSite>> allocation_site =
      track_allocation_site
          ? Parameter<AllocationSite>(Descriptor::kAllocationSite)
          : std::optional<TNode<AllocationSite>>(std::nullopt);
  TNode<Map> array_map = LoadJSArrayElementsMap(kind, native_context);
  TNode<JSArray> array = AllocateJSArray(
      kind, array_map, IntPtrConstant(JSArray::kPreallocatedArrayElements),
      SmiConstant(0), allocation_site);
  Return(array);
}
References v8::internal::CodeStubAssembler::AllocateJSArray(), v8::internal::DISABLE_ALLOCATION_SITES, v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::torque::ls::kFunction, v8::internal::JSArray::kPreallocatedArrayElements, v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), mode(), v8::internal::native_context, v8::internal::compiler::CodeAssembler::Return(), v8::internal::AllocationSite::ShouldTrack(), and v8::internal::compiler::CodeAssembler::SmiConstant().
GenerateArraySingleArgumentConstructor()
void v8::internal::ArrayBuiltinsAssembler::GenerateArraySingleArgumentConstructor (ElementsKind kind, AllocationSiteOverrideMode mode) [protected]
Definition at line 1904 of file builtins-array-gen.cc.
                                                        {
  using Descriptor = ArraySingleArgumentConstructorDescriptor;
  auto context = Parameter<Context>(Descriptor::kContext);
  auto function = Parameter<JSAnyNotSmi>(Descriptor::kFunction);
  TNode<NativeContext> native_context =
      CAST(LoadObjectField(function, JSFunction::kContextOffset));
  TNode<Map> array_map = LoadJSArrayElementsMap(kind, native_context);
  AllocationSiteMode allocation_site_mode = DONT_TRACK_ALLOCATION_SITE;
  if (mode == DONT_OVERRIDE) {
    allocation_site_mode = AllocationSite::ShouldTrack(kind)
                               ? TRACK_ALLOCATION_SITE
                               : DONT_TRACK_ALLOCATION_SITE;
  }
  auto array_size = Parameter<Object>(Descriptor::kArraySizeSmiParameter);
  // allocation_site can be Undefined or an AllocationSite
  auto allocation_site = Parameter<HeapObject>(Descriptor::kAllocationSite);
  GenerateConstructor(context, function, array_map, array_size, allocation_site,
                      kind, allocation_site_mode);
}
References CAST, context(), v8::internal::DONT_OVERRIDE, v8::internal::DONT_TRACK_ALLOCATION_SITE, GenerateConstructor(), v8::internal::torque::ls::kFunction, v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), v8::internal::CodeStubAssembler::LoadObjectField(), mode(), v8::internal::native_context, v8::internal::AllocationSite::ShouldTrack(), and v8::internal::TRACK_ALLOCATION_SITE.
GenerateConstructor()
void v8::internal::ArrayBuiltinsAssembler::GenerateConstructor (TNode< Context > context, TNode< JSAnyNotSmi > array_function, TNode< Map > array_map, TNode< Object > array_size, TNode< HeapObject > allocation_site, ElementsKind elements_kind, AllocationSiteMode mode) [protected]
Definition at line 1838 of file builtins-array-gen.cc.
                             {
  Label ok(this);
  Label smi_size(this);
  Label small_smi_size(this);
  Label call_runtime(this, Label::kDeferred);
  Branch(TaggedIsSmi(array_size), &smi_size, &call_runtime);
  BIND(&smi_size);
  {
    TNode<Smi> array_size_smi = CAST(array_size);
    if (IsFastPackedElementsKind(elements_kind)) {
      Label abort(this, Label::kDeferred);
      Branch(SmiEqual(array_size_smi, SmiConstant(0)), &small_smi_size, &abort);
      BIND(&abort);
      TNode<Smi> reason =
          SmiConstant(AbortReason::kAllocatingNonEmptyPackedArray);
      TailCallRuntime(Runtime::kAbort, context, reason);
    } else {
      Branch(SmiAboveOrEqual(array_size_smi,
                             SmiConstant(JSArray::kInitialMaxFastElementArray)),
             &call_runtime, &small_smi_size);
    }
    BIND(&small_smi_size);
    {
      TNode<JSArray> array = AllocateJSArray(
          elements_kind, array_map, array_size_smi, array_size_smi,
          mode == DONT_TRACK_ALLOCATION_SITE
              ? std::optional<TNode<AllocationSite>>(std::nullopt)
              : CAST(allocation_site));
      Return(array);
    }
  }
  BIND(&call_runtime);
  {
    TailCallRuntimeNewArray(context, array_function, array_size, array_function,
                            allocation_site);
  }
}
References v8::internal::CodeStubAssembler::AllocateJSArray(), v8::internal::compiler::CodeAssembler::Branch(), CAST, context(), v8::internal::DONT_TRACK_ALLOCATION_SITE, v8::internal::CodeStubAssembler::IsFastPackedElementsKind(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::JSArray::kInitialMaxFastElementArray, mode(), v8::internal::compiler::CodeAssembler::Return(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::compiler::CodeAssembler::TailCallRuntime(), and v8::internal::CodeStubAssembler::TailCallRuntimeNewArray().
Referenced by GenerateArraySingleArgumentConstructor().
GenerateDispatchToArrayStub()
void v8::internal::ArrayBuiltinsAssembler::GenerateDispatchToArrayStub (TNode< Context > context, TNode< JSFunction > target, TNode< Int32T > argc, AllocationSiteOverrideMode mode, std::optional< TNode< AllocationSite >> allocation_site = std::nullopt) [protected]
Definition at line 1779 of file builtins-array-gen.cc.
                                                        {
  CodeStubArguments args(this, argc);
  Label check_one_case(this), fallthrough(this);
  GotoIfNot(IntPtrEqual(args.GetLengthWithoutReceiver(), IntPtrConstant(0)),
            &check_one_case);
  CreateArrayDispatchNoArgument(context, target, argc, mode, allocation_site);
  BIND(&check_one_case);
  GotoIfNot(IntPtrEqual(args.GetLengthWithoutReceiver(), IntPtrConstant(1)),
            &fallthrough);
  CreateArrayDispatchSingleArgument(context, target, argc, mode,
                                    allocation_site);
  BIND(&fallthrough);
}
References argc(), v8::base::args, context(), CreateArrayDispatchNoArgument(), CreateArrayDispatchSingleArgument(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), and mode().
GenerateIteratingTypedArrayBuiltinBody()
void v8::internal::ArrayBuiltinsAssembler::GenerateIteratingTypedArrayBuiltinBody (const char * name, const BuiltinResultGenerator & generator, const CallResultProcessor & processor, ForEachDirection direction = ForEachDirection::kForward) [protected]
Definition at line 140 of file builtins-array-gen.cc.
                                                                      {
  name_ = name;
  // ValidateTypedArray: tc39.github.io/ecma262/#sec-validatetypedarray
  Label throw_not_typed_array(this, Label::kDeferred);
  GotoIf(TaggedIsSmi(receiver_), &throw_not_typed_array);
  TNode<Map> typed_array_map = LoadMap(CAST(receiver_));
  GotoIfNot(IsJSTypedArrayMap(typed_array_map), &throw_not_typed_array);
  TNode<JSTypedArray> typed_array = CAST(receiver_);
  o_ = typed_array;
  Label throw_detached(this, Label::kDeferred);
  len_ = LoadJSTypedArrayLengthAndCheckDetached(typed_array, &throw_detached);
  Label throw_not_callable(this, Label::kDeferred);
  Label distinguish_types(this);
  GotoIf(TaggedIsSmi(callbackfn_), &throw_not_callable);
  Branch(IsCallableMap(LoadMap(CAST(callbackfn_))), &distinguish_types,
         &throw_not_callable);
  BIND(&throw_not_typed_array);
  ThrowTypeError(context_, MessageTemplate::kNotTypedArray);
  BIND(&throw_not_callable);
  ThrowTypeError(context_, MessageTemplate::kCalledNonCallable, callbackfn_);
  BIND(&throw_detached);
  ThrowTypeError(context_, MessageTemplate::kDetachedOperation, name_);
  Label unexpected_instance_type(this);
  BIND(&unexpected_instance_type);
  Unreachable();
  std::vector<int32_t> elements_kinds = {
#define ELEMENTS_KIND(Type, type, TYPE, ctype) TYPE##_ELEMENTS,
      TYPED_ARRAYS(ELEMENTS_KIND) RAB_GSAB_TYPED_ARRAYS(ELEMENTS_KIND)
#undef ELEMENTS_KIND
  };
  std::list<Label> labels;
  for (size_t i = 0; i < elements_kinds.size(); ++i) {
    labels.emplace_back(this);
  }
  std::vector<Label*> label_ptrs;
  for (Label& label : labels) {
    label_ptrs.push_back(&label);
  }
  BIND(&distinguish_types);
  generator(this);
  TNode<JSArrayBuffer> array_buffer = LoadJSArrayBufferViewBuffer(typed_array);
  TNode<Int32T> elements_kind = LoadMapElementsKind(typed_array_map);
  Switch(elements_kind, &unexpected_instance_type, elements_kinds.data(),
         label_ptrs.data(), labels.size());
  size_t i = 0;
  for (auto it = labels.begin(); it != labels.end(); ++i, ++it) {
    BIND(&*it);
    source_elements_kind_ = static_cast<ElementsKind>(elements_kinds[i]);
    VisitAllTypedArrayElements(array_buffer, processor, direction, typed_array);
    ReturnFromBuiltin(a_.value());
  }
}
References a_, v8::internal::compiler::CodeAssembler::Branch(), callbackfn_, CAST, context_, ELEMENTS_KIND, v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::CodeStubAssembler::IsCallableMap(), v8::internal::CodeStubAssembler::IsJSTypedArrayMap(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, len_, v8::internal::CodeStubAssembler::LoadJSArrayBufferViewBuffer(), v8::internal::CodeStubAssembler::LoadJSTypedArrayLengthAndCheckDetached(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapElementsKind(), v8::internal::name, name_, o_, RAB_GSAB_TYPED_ARRAYS, receiver_, ReturnFromBuiltin(), source_elements_kind_, v8::internal::compiler::CodeAssembler::Switch(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::CodeStubAssembler::ThrowTypeError(), TYPED_ARRAYS, v8::internal::compiler::CodeAssembler::Unreachable(), and VisitAllTypedArrayElements().
InitIteratingArrayBuiltinBody()
void v8::internal::ArrayBuiltinsAssembler::InitIteratingArrayBuiltinBody (TNode< Context > context, TNode< JSAny > receiver, TNode< Object > callbackfn, TNode< JSAny > this_arg, TNode< IntPtrT > argc) [protected]
Definition at line 130 of file builtins-array-gen.cc.
                                                {
  context_ = context;
  receiver_ = receiver;
  callbackfn_ = callbackfn;
  this_arg_ = this_arg;
  argc_ = argc;
}
References argc(), argc_, callbackfn(), callbackfn_, context(), context_, receiver(), receiver_, this_arg(), and this_arg_.
k()
TNode<UintPtrT> v8::internal::ArrayBuiltinsAssembler::k () [inline], [protected]
Definition at line 56 of file builtins-array-gen.h.
{ return k_.value(); }
References k_.
Referenced by TypedArrayMapProcessor().
len()
TNode<UintPtrT> v8::internal::ArrayBuiltinsAssembler::len () [inline], [protected]
Definition at line 53 of file builtins-array-gen.h.
{ return len_; }
References len_.
Referenced by TypedArrayMapResultGenerator().
o()
TNode<JSReceiver> v8::internal::ArrayBuiltinsAssembler::o () [inline], [protected]
Definition at line 52 of file builtins-array-gen.h.
{ return o_; }
References o_.
Referenced by TypedArrayMapProcessor(), and TypedArrayMapResultGenerator().
receiver()
TNode<JSAny> v8::internal::ArrayBuiltinsAssembler::receiver () [inline], [protected]
Definition at line 50 of file builtins-array-gen.h.
{ return receiver_; }
References receiver_.
Referenced by InitIteratingArrayBuiltinBody().
ReturnFromBuiltin()
void v8::internal::ArrayBuiltinsAssembler::ReturnFromBuiltin (TNode< Object > value) [protected]
Definition at line 121 of file builtins-array-gen.cc.
                                                                  {
  if (argc_ == nullptr) {
    Return(value);
  } else {
    CodeStubArguments args(this, argc());
    PopAndReturn(args.GetLengthWithReceiver(), value);
  }
}
References argc(), argc_, v8::base::args, v8::internal::compiler::CodeAssembler::PopAndReturn(), v8::internal::compiler::CodeAssembler::Return(), and v8::internal::value.
Referenced by GenerateIteratingTypedArrayBuiltinBody().
TailCallArrayConstructorStub()
void v8::internal::ArrayBuiltinsAssembler::TailCallArrayConstructorStub (const Callable & callable, TNode< Context > context, TNode< JSFunction > target, TNode< HeapObject > allocation_site_or_undefined, TNode< Int32T > argc) [protected]
Definition at line 1647 of file builtins-array-gen.cc.
                                                                        {
  TNode<Code> code = HeapConstantNoHole(callable.code());
  // We are going to call here ArrayNoArgumentsConstructor or
  // ArraySingleArgumentsConstructor which in addition to the register arguments
  // also expect some number of arguments on the expression stack.
  // Since
  // 1) incoming JS arguments are still on the stack,
  // 2) the ArrayNoArgumentsConstructor, ArraySingleArgumentsConstructor and
  // ArrayNArgumentsConstructor are defined so that the register arguments
  // are passed on the same registers,
  // in order to be able to generate a tail call to those builtins we do the
  // following trick here: we tail call to the constructor builtin using
  // ArrayNArgumentsConstructorDescriptor, so the tail call instruction
  // pops the current frame but leaves all the incoming JS arguments on the
  // expression stack so that the target builtin can still find them where it
  // expects.
  TailCallStub(ArrayNArgumentsConstructorDescriptor{}, code, context, target,
               allocation_site_or_undefined, argc);
}
References argc(), v8::internal::Callable::code(), code, context(), v8::internal::compiler::CodeAssembler::HeapConstantNoHole(), and v8::internal::compiler::CodeAssembler::TailCallStub().
Referenced by CreateArrayDispatchNoArgument(), and CreateArrayDispatchSingleArgument().
this_arg()
TNode<JSAny> v8::internal::ArrayBuiltinsAssembler::this_arg () [inline], [protected]
Definition at line 55 of file builtins-array-gen.h.
{ return this_arg_; }
References this_arg_.
Referenced by InitIteratingArrayBuiltinBody(), and TypedArrayMapProcessor().
TypedArrayMapProcessor()
TNode< JSAny > v8::internal::ArrayBuiltinsAssembler::TypedArrayMapProcessor (TNode< Object > k_value, TNode< UintPtrT > k)
Definition at line 67 of file builtins-array-gen.cc.
                                              {
  // 7c. Let mapped_value be ? Call(callbackfn, T, kValue, k, O).
  TNode<Number> k_number = ChangeUintPtrToTagged(k);
  TNode<JSAny> mapped_value =
      Call(context(), callbackfn(), this_arg(), k_value, k_number, o());
  Label fast(this), slow(this), done(this), detached(this, Label::kDeferred);
  // 7d. Perform ? Set(A, Pk, mapped_value, true).
  // Since we know that A is a TypedArray, this always ends up in
  // #sec-integer-indexed-exotic-objects-set-p-v-receiver and then
  // tc39.github.io/ecma262/#sec-integerindexedelementset .
  Branch(fast_typed_array_target_, &fast, &slow);
  BIND(&fast);
  // #sec-integerindexedelementset
  // 2. If arrayTypeName is "BigUint64Array" or "BigInt64Array", let
  // numValue be ? ToBigInt(v).
  // 3. Otherwise, let numValue be ? ToNumber(value).
  TNode<Object> num_value;
  if (IsBigIntTypedArrayElementsKind(source_elements_kind_)) {
    num_value = ToBigInt(context(), mapped_value);
  } else {
    num_value = ToNumber_Inline(context(), mapped_value);
  }
  // The only way how this can bailout is because of a detached or out of bounds
  // buffer.
  // TODO(v8:4153): Consider checking IsDetachedBuffer() and calling
  // TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromNumeric() here
  // instead to avoid converting k_number back to UintPtrT.
  // Using source_elements_kind_ (not "target elements kind") is correct here,
  // because the fast branch is taken only when the source and the target
  // elements kinds match.
  EmitElementStore(CAST(a()), k_number, num_value, source_elements_kind_,
                   KeyedAccessStoreMode::kInBounds, &detached, context());
  Goto(&done);
  BIND(&slow);
  {
    SetPropertyStrict(context(), a(), k_number, mapped_value);
    Goto(&done);
  }
  BIND(&detached);
  // tc39.github.io/ecma262/#sec-integerindexedelementset
  // 8. If IsDetachedBuffer(buffer) is true, throw a TypeError exception.
  ThrowTypeError(context_, MessageTemplate::kDetachedOperation, name_);
  BIND(&done);
  return a();
}
References a(), v8::internal::compiler::CodeAssembler::Branch(), v8::internal::CodeStubAssembler::Call(), callbackfn(), CAST, v8::internal::CodeStubAssembler::ChangeUintPtrToTagged(), context(), context_, v8::internal::CodeStubAssembler::EmitElementStore(), fast_typed_array_target_, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::IsBigIntTypedArrayElementsKind(), k(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::kInBounds, name_, o(), v8::internal::CodeStubAssembler::SetPropertyStrict(), source_elements_kind_, this_arg(), v8::internal::CodeStubAssembler::ThrowTypeError(), v8::internal::CodeStubAssembler::ToBigInt(), and v8::internal::CodeStubAssembler::ToNumber_Inline().
Referenced by v8::internal::TF_BUILTIN().
TypedArrayMapResultGenerator()
void v8::internal::ArrayBuiltinsAssembler::TypedArrayMapResultGenerator ()
Definition at line 39 of file builtins-array-gen.cc.
                                                          {
  // 6. Let A be ? TypedArraySpeciesCreate(O, len).
  TNode<JSTypedArray> original_array = CAST(o());
  const char* method_name = "%TypedArray%.prototype.map";
  TNode<JSTypedArray> a = TypedArraySpeciesCreateByLength(
      context(), method_name, original_array, len());
  // In the Spec and our current implementation, the length check is already
  // performed in TypedArraySpeciesCreate.
#ifdef DEBUG
  Label detached_or_out_of_bounds(this), done(this);
  CSA_DCHECK(this, UintPtrLessThanOrEqual(
                       len(), LoadJSTypedArrayLengthAndCheckDetached(
                                  a, &detached_or_out_of_bounds)));
  Goto(&done);
  BIND(&detached_or_out_of_bounds);
  Unreachable();
  BIND(&done);
#endif // DEBUG
  // TODO(v8:11111): Make storing fast when the elements kinds only differ
  // because of their RAB/GSABness.
  fast_typed_array_target_ =
      Word32Equal(LoadElementsKind(original_array), LoadElementsKind(a));
  a_ = a;
}
References a(), a_, CAST, context(), fast_typed_array_target_, v8::internal::compiler::CodeAssembler::Goto(), len(), v8::internal::CodeStubAssembler::LoadElementsKind(), v8::internal::CodeStubAssembler::LoadJSTypedArrayLengthAndCheckDetached(), o(), v8::internal::CodeStubAssembler::UintPtrLessThanOrEqual, v8::internal::compiler::CodeAssembler::Unreachable(), and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by v8::internal::TF_BUILTIN().
VisitAllTypedArrayElements()
void v8::internal::ArrayBuiltinsAssembler::VisitAllTypedArrayElements (TNode< JSArrayBuffer > array_buffer, const CallResultProcessor & processor, ForEachDirection direction, TNode< JSTypedArray > typed_array) [private]
Definition at line 210 of file builtins-array-gen.cc.
                                                                 {
  VariableList list({&a_, &k_}, zone());
  TNode<UintPtrT> start = UintPtrConstant(0);
  TNode<UintPtrT> end = len_;
  IndexAdvanceMode advance_mode = IndexAdvanceMode::kPost;
  int incr = 1;
  if (direction == ForEachDirection::kReverse) {
    std::swap(start, end);
    advance_mode = IndexAdvanceMode::kPre;
    incr = -1;
  }
  k_ = start;
  // TODO(v8:11111): Only RAB-backed TAs need special handling here since the
  // backing store can shrink mid-iteration. This implementation has an
  // overzealous check for GSAB-backed length-tracking TAs. Then again, the
  // non-RAB/GSAB code also has an overzealous detached check for SABs.
  ElementsKind effective_elements_kind = source_elements_kind_;
  bool is_rab_gsab = IsRabGsabTypedArrayElementsKind(effective_elements_kind);
  if (is_rab_gsab) {
    effective_elements_kind =
        GetCorrespondingNonRabGsabElementsKind(effective_elements_kind);
  }
  BuildFastLoop<UintPtrT>(
      list, start, end,
      [&](TNode<UintPtrT> index) {
        TVARIABLE(Object, value);
        Label detached(this, Label::kDeferred);
        Label process(this);
        if (is_rab_gsab) {
          // If `index` is out of bounds, Get returns undefined.
          CheckJSTypedArrayIndex(typed_array, index, &detached);
        } else {
          GotoIf(IsDetachedBuffer(array_buffer), &detached);
        }
        {
          TNode<RawPtrT> data_ptr = LoadJSTypedArrayDataPtr(typed_array);
          value = LoadFixedTypedArrayElementAsTagged(data_ptr, index,
                                                     effective_elements_kind);
          Goto(&process);
        }
        BIND(&detached);
        {
          value = UndefinedConstant();
          Goto(&process);
        }
        BIND(&process);
        {
          k_ = index;
          a_ = processor(this, value.value(), index);
        }
      },
      incr, LoopUnrollingMode::kNo, advance_mode);
}
References a_, v8::internal::CodeStubAssembler::CheckJSTypedArrayIndex(), v8::internal::compiler::end(), v8::internal::GetCorrespondingNonRabGsabElementsKind(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::index, v8::internal::IsRabGsabTypedArrayElementsKind(), k_, v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::kNo, v8::internal::CodeStubAssembler::kPost, v8::internal::CodeStubAssembler::kPre, v8::internal::CodeStubAssembler::kReverse, len_, v8::internal::CodeStubAssembler::LoadFixedTypedArrayElementAsTagged(), v8::internal::CodeStubAssembler::LoadJSTypedArrayDataPtr(), source_elements_kind_, v8::internal::compiler::CodeAssembler::UintPtrConstant(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), v8::internal::value, and v8::internal::compiler::CodeAssembler::zone().
Referenced by GenerateIteratingTypedArrayBuiltinBody().
Member Data Documentation
a_
TVariable<JSAny> v8::internal::ArrayBuiltinsAssembler::a_ [private]
Definition at line 122 of file builtins-array-gen.h.
Referenced by a(), ArrayBuiltinsAssembler(), GenerateIteratingTypedArrayBuiltinBody(), TypedArrayMapResultGenerator(), and VisitAllTypedArrayElements().
argc_
TNode<IntPtrT> v8::internal::ArrayBuiltinsAssembler::argc_ [private]
Definition at line 118 of file builtins-array-gen.h.
Referenced by argc(), InitIteratingArrayBuiltinBody(), and ReturnFromBuiltin().
callbackfn_
TNode<Object> v8::internal::ArrayBuiltinsAssembler::callbackfn_ [private]
Definition at line 112 of file builtins-array-gen.h.
Referenced by callbackfn(), GenerateIteratingTypedArrayBuiltinBody(), and InitIteratingArrayBuiltinBody().
context_
TNode<Context> v8::internal::ArrayBuiltinsAssembler::context_ [private]
Definition at line 116 of file builtins-array-gen.h.
Referenced by context(), GenerateIteratingTypedArrayBuiltinBody(), InitIteratingArrayBuiltinBody(), and TypedArrayMapProcessor().
fast_typed_array_target_
TNode<BoolT> v8::internal::ArrayBuiltinsAssembler::fast_typed_array_target_ [private]
Definition at line 119 of file builtins-array-gen.h.
Referenced by TypedArrayMapProcessor(), and TypedArrayMapResultGenerator().
fully_spec_compliant_
Label v8::internal::ArrayBuiltinsAssembler::fully_spec_compliant_ [private]
Definition at line 123 of file builtins-array-gen.h.
k_
TVariable<UintPtrT> v8::internal::ArrayBuiltinsAssembler::k_ [private]
Definition at line 121 of file builtins-array-gen.h.
Referenced by ArrayBuiltinsAssembler(), k(), and VisitAllTypedArrayElements().
len_
TNode<UintPtrT> v8::internal::ArrayBuiltinsAssembler::len_ [private]
Definition at line 115 of file builtins-array-gen.h.
Referenced by GenerateIteratingTypedArrayBuiltinBody(), len(), and VisitAllTypedArrayElements().
name_
const char* v8::internal::ArrayBuiltinsAssembler::name_ = nullptr [private]
Definition at line 120 of file builtins-array-gen.h.
Referenced by GenerateIteratingTypedArrayBuiltinBody(), and TypedArrayMapProcessor().
o_
TNode<JSReceiver> v8::internal::ArrayBuiltinsAssembler::o_ [private]
Definition at line 113 of file builtins-array-gen.h.
Referenced by GenerateIteratingTypedArrayBuiltinBody(), and o().
receiver_
TNode<JSAny> v8::internal::ArrayBuiltinsAssembler::receiver_ [private]
Definition at line 117 of file builtins-array-gen.h.
Referenced by GenerateIteratingTypedArrayBuiltinBody(), InitIteratingArrayBuiltinBody(), and receiver().
source_elements_kind_
ElementsKind v8::internal::ArrayBuiltinsAssembler::source_elements_kind_ = ElementsKind::NO_ELEMENTS [private]
Definition at line 124 of file builtins-array-gen.h.
Referenced by GenerateIteratingTypedArrayBuiltinBody(), TypedArrayMapProcessor(), and VisitAllTypedArrayElements().
this_arg_
TNode<JSAny> v8::internal::ArrayBuiltinsAssembler::this_arg_ [private]
Definition at line 114 of file builtins-array-gen.h.
Referenced by InitIteratingArrayBuiltinBody(), and this_arg().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-array-gen.h
/mnt/V8SourceCode/src/builtins/builtins-array-gen.cc