v8::StreamerThread Class Reference
Public Member Functions
StreamerThread (v8::ScriptCompiler::ScriptStreamingTask *task)
void Run () override
Static Public Member Functions
static void StartThreadForTaskAndJoin (v8::ScriptCompiler::ScriptStreamingTask *task)
Private Attributes
v8::ScriptCompiler::ScriptStreamingTask * task_
Additional Inherited Members
Detailed Description
Definition at line 625 of file d8.cc.
Constructor & Destructor Documentation
StreamerThread()
v8::StreamerThread::StreamerThread (v8::ScriptCompiler::ScriptStreamingTask * task) [inline], [explicit]
Definition at line 634 of file d8.cc.
      : Thread(Thread::Options()), task_(task) {}
Member Function Documentation
Run()
void v8::StreamerThread::Run () [inline], [override], [virtual]
Implements v8::base::Thread.
Definition at line 637 of file d8.cc.
{ task_->Run(); }
References v8::ScriptCompiler::ScriptStreamingTask::Run(), and task_.
StartThreadForTaskAndJoin()
static void v8::StreamerThread::StartThreadForTaskAndJoin (v8::ScriptCompiler::ScriptStreamingTask * task) [inline], [static]
Definition at line 627 of file d8.cc.
                                                 {
    StreamerThread thread(task);
    CHECK(thread.Start());
    thread.Join();
  }
References CHECK, v8::base::Thread::Join(), and v8::base::Thread::Start().
Referenced by v8::Shell::CompileString().
Member Data Documentation
task_
v8::ScriptCompiler::ScriptStreamingTask* v8::StreamerThread::task_ [private]
Definition at line 640 of file d8.cc.
Referenced by Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/d8/d8.cc