v8::internal::maglev::UnconditionalControlNode Class Reference
#include <maglev-ir.h>
Public Member Functions
BasicBlock * target () const
int predecessor_id () const
void set_predecessor_id (int id)
void set_target (BasicBlock *block)
Protected Member Functions
UnconditionalControlNode (uint64_t bitfield, BasicBlockRef *target_refs)
UnconditionalControlNode (uint64_t bitfield, BasicBlock *target)
Private Attributes
BasicBlockRef target_
int predecessor_id_ = 0
Additional Inherited Members
Detailed Description
Definition at line 11218 of file maglev-ir.h.
Constructor & Destructor Documentation
UnconditionalControlNode() [1/2]
v8::internal::maglev::UnconditionalControlNode::UnconditionalControlNode (uint64_t bitfield, BasicBlockRef * target_refs) [inline], [explicit], [protected]
Definition at line 11227 of file maglev-ir.h.
      : ControlNode(bitfield), target_(target_refs) {}
UnconditionalControlNode() [2/2]
v8::internal::maglev::UnconditionalControlNode::UnconditionalControlNode (uint64_t bitfield, BasicBlock * target) [inline], [explicit], [protected]
Definition at line 11230 of file maglev-ir.h.
      : ControlNode(bitfield), target_(target) {}
Member Function Documentation
predecessor_id()
int v8::internal::maglev::UnconditionalControlNode::predecessor_id () const [inline]
Definition at line 11221 of file maglev-ir.h.
{ return predecessor_id_; }
set_predecessor_id()
void v8::internal::maglev::UnconditionalControlNode::set_predecessor_id (int id) [inline]
Definition at line 11222 of file maglev-ir.h.
{ predecessor_id_ = id; }
set_target()
void v8::internal::maglev::UnconditionalControlNode::set_target (BasicBlock * block) [inline]
Definition at line 11224 of file maglev-ir.h.
{ target_.set_block_ptr(block); }
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PatchJumps().
target()
BasicBlock* v8::internal::maglev::UnconditionalControlNode::target () const [inline]
Definition at line 11220 of file maglev-ir.h.
{ return target_.block_ptr(); }
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PatchJumps(), and v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintTargets().
Member Data Documentation
predecessor_id_
int v8::internal::maglev::UnconditionalControlNode::predecessor_id_ = 0 [private]
Definition at line 11235 of file maglev-ir.h.
target_
BasicBlockRef v8::internal::maglev::UnconditionalControlNode::target_ [private]
Definition at line 11234 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h