v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen Class Reference
Classes
class BlockScope
struct CatchCase
struct GeneratorRecursionScope
struct Var
Public Member Functions
BodyGen (WasmModuleGenerationOptions options, WasmFunctionBuilder *fn, const std::vector< ModuleTypeIndex > &functions, const std::vector< ValueType > &globals, const std::vector< uint8_t > &mutable_globals, const std::vector< ModuleTypeIndex > &structs, const std::vector< ModuleTypeIndex > &arrays, const StringImports &strings, DataRange *data)
int NumImportedFunctions ()
size_t all_locals_count () const
ValueType local_type (uint32_t index) const
void GenerateVoid (DataRange *data)
void GenerateI32 (DataRange *data)
void GenerateI64 (DataRange *data)
void GenerateF32 (DataRange *data)
void GenerateF64 (DataRange *data)
void GenerateS128 (DataRange *data)
void Generate (ValueType type, DataRange *data)
template<ValueKind kind>
constexpr void Generate (DataRange *data)
template<ValueKind T1, ValueKind T2, ValueKind... Ts>
void Generate (DataRange *data)
void GenerateRef (HeapType type, DataRange *data, Nullability nullability=kNullable)
void GenerateRef (DataRange *data)
std::vector< ValueType > GenerateTypes (DataRange *data)
void Generate (base::Vector< const ValueType > types, DataRange *data)
void Generate (std::initializer_list< ValueTypeBase > types, DataRange *data)
void Consume (ValueType type)
void ConsumeAndGenerate (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, DataRange *data)
void InitializeNonDefaultableLocals (DataRange *data)
Private Types
enum IfType { kIf
, kIfElse
 }
enum CallKind { kCallDirect
, kCallIndirect
, kCallRef
 }
Private Member Functions
template<WasmOpcode Op, ValueKind... Args>
void op (DataRange *data)
void block (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, DataRange *data)
template<ValueKind T>
void block (DataRange *data)
void loop (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, DataRange *data)
template<ValueKind T>
void loop (DataRange *data)
void finite_loop (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, DataRange *data)
template<ValueKind T>
void finite_loop (DataRange *data)
void if_ (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, IfType type, DataRange *data)
template<ValueKind T, IfType type>
void if_ (DataRange *data)
void try_block_helper (ValueType return_type, DataRange *data)
template<ValueKind T>
void try_block (DataRange *data)
void try_table_rec (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, base::Vector< CatchCase > catch_cases, size_t i, DataRange *data)
void try_table_block_helper (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, DataRange *data)
template<ValueKind T>
void try_table_block (DataRange *data)
void any_block (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, DataRange *data)
void br (DataRange *data)
template<ValueKind wanted_kind>
void br_if (DataRange *data)
template<ValueKind wanted_kind>
void br_on_null (DataRange *data)
template<ValueKind wanted_kind>
void br_on_non_null (DataRange *data)
void br_table (ValueType result_type, DataRange *data)
template<ValueKind wanted_kind>
void br_table (DataRange *data)
void return_op (DataRange *data)
template<WasmOpcode memory_op, ValueKind... arg_kinds>
void memop (DataRange *data)
template<WasmOpcode Op, ValueKind... Args>
void op_with_prefix (DataRange *data)
void simd_const (DataRange *data)
template<WasmOpcode Op, int lanes, ValueKind... Args>
void simd_lane_op (DataRange *data)
template<WasmOpcode Op, int lanes, ValueKind... Args>
void simd_lane_memop (DataRange *data)
void simd_shuffle (DataRange *data)
void drop (DataRange *data)
template<ValueKind wanted_kind>
void call (DataRange *data)
template<ValueKind wanted_kind>
void call_indirect (DataRange *data)
template<ValueKind wanted_kind>
void call_ref (DataRange *data)
void Convert (ValueType src, ValueType dst)
int choose_function_table_index (DataRange *data)
void call (DataRange *data, ValueType wanted_kind, CallKind call_kind)
ValueType AsNullable (ValueType original)
Var GetRandomLocal (DataRange *data, ValueType type=kWasmTop)
template<ValueKind wanted_kind>
void local_op (DataRange *data, WasmOpcode opcode)
template<ValueKind wanted_kind>
void get_local (DataRange *data)
void set_local (DataRange *data)
template<ValueKind wanted_kind>
void tee_local (DataRange *data)
void shift_locals_to (DataRange *data, Var start_local)
void shift_locals (DataRange *data)
template<size_t num_bytes>
void i32_const (DataRange *data)
template<size_t num_bytes>
void i64_const (DataRange *data)
Var GetRandomGlobal (DataRange *data, bool ensure_mutable)
template<ValueKind wanted_kind>
void global_op (DataRange *data)
template<ValueKind wanted_kind>
void get_global (DataRange *data)
template<ValueKind select_kind>
void select_with_type (DataRange *data)
void set_global (DataRange *data)
void throw_or_rethrow (DataRange *data)
template<ValueKind... Types>
void sequence (DataRange *data)
void memory_size (DataRange *data)
void grow_memory (DataRange *data)
void ref_null (HeapType type, DataRange *data)
bool get_local_ref (HeapType type, DataRange *data, Nullability nullable)
bool new_object (HeapType type, DataRange *data, Nullability nullable)
void table_op (uint32_t index, std::vector< ValueType > types, DataRange *data, WasmOpcode opcode)
ValueType table_address_type (int table_index)
std::pair< int, ValueType > select_random_table (DataRange *data)
bool table_get (HeapType type, DataRange *data, Nullability nullable)
void table_set (DataRange *data)
void table_size (DataRange *data)
void table_grow (DataRange *data)
void table_fill (DataRange *data)
void table_copy (DataRange *data)
bool array_get_helper (ValueType value_type, DataRange *data)
template<ValueKind wanted_kind>
void array_get (DataRange *data)
bool array_get_ref (HeapType type, DataRange *data, Nullability nullable)
void i31_get (DataRange *data)
void array_len (DataRange *data)
void array_copy (DataRange *data)
void array_fill (DataRange *data)
void array_init_data (DataRange *data)
void array_init_elem (DataRange *data)
void array_set (DataRange *data)
bool struct_get_helper (ValueType value_type, DataRange *data)
template<ValueKind wanted_kind>
void struct_get (DataRange *data)
bool struct_get_ref (HeapType type, DataRange *data, Nullability nullable)
bool ref_cast (HeapType type, DataRange *data, Nullability nullable)
HeapType top_type (HeapType type)
HeapType choose_sub_type (HeapType type, DataRange *data)
bool br_on_cast (HeapType type, DataRange *data, Nullability nullable)
bool any_convert_extern (HeapType type, DataRange *data, Nullability nullable)
bool ref_as_non_null (HeapType type, DataRange *data, Nullability nullable)
void struct_set (DataRange *data)
void ref_is_null (DataRange *data)
template<WasmOpcode opcode>
void ref_test (DataRange *data)
void ref_eq (DataRange *data)
void call_string_import (uint32_t index)
void string_cast (DataRange *data)
void string_test (DataRange *data)
void string_fromcharcode (DataRange *data)
void string_fromcodepoint (DataRange *data)
void string_charcodeat (DataRange *data)
void string_codepointat (DataRange *data)
void string_length (DataRange *data)
void string_concat (DataRange *data)
void string_substring (DataRange *data)
void string_equals (DataRange *data)
void string_compare (DataRange *data)
void string_fromcharcodearray (DataRange *data)
void string_intocharcodearray (DataRange *data)
void string_measureutf8 (DataRange *data)
void string_intoutf8array (DataRange *data)
void string_toutf8array (DataRange *data)
void string_fromutf8array (DataRange *data)
template<typename Arr >
requires requires (const Arr &arr)
void GenerateOneOf (const Arr &alternatives, DataRange *data)
template<size_t... kAlternativesSizes>
void GenerateOneOf (const GeneratorAlternativesPerOption< kAlternativesSizes... > &alternatives_per_option, DataRange *data)
template<typename Arr >
requires requires (const Arr &arr)
bool GenerateOneOf (const Arr &alternatives, HeapType type, DataRange *data, Nullability nullability)
bool recursion_limit_reached ()
Static Private Member Functions
constexpr static uint8_t max_alignment (WasmOpcode memop)
constexpr static bool is_convertible_kind (ValueKind kind)
Private Attributes
const WasmModuleGenerationOptions options_
WasmFunctionBuilder *const builder_
std::vector< std::vector< ValueType > > blocks_
const std::vector< ModuleTypeIndex > & functions_
std::vector< ValueType > locals_
std::vector< ValueType > globals_
std::vector< uint8_t > mutable_globals_
uint32_t recursion_depth = 0
std::vector< int > catch_blocks_
const std::vector< ModuleTypeIndex > & structs_
const std::vector< ModuleTypeIndex > & arrays_
const StringImports & string_imports_
bool locals_initialized_ = false
Detailed Description
Definition at line 412 of file random-module-generation.cc.
Member Enumeration Documentation
CallKind
enum v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::CallKind [private]
Enumerator
kCallDirect
kCallIndirect
kCallRef
Definition at line 1066 of file random-module-generation.cc.
{ kCallDirect, kCallIndirect, kCallRef };
IfType
enum v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::IfType [private]
Enumerator
kIf
kIfElse
Definition at line 550 of file random-module-generation.cc.
{ kIf, kIfElse };
Constructor & Destructor Documentation
BodyGen()
v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BodyGen (WasmModuleGenerationOptions options, WasmFunctionBuilder * fn, const std::vector< ModuleTypeIndex > & functions, const std::vector< ValueType > & globals, const std::vector< uint8_t > & mutable_globals, const std::vector< ModuleTypeIndex > & structs, const std::vector< ModuleTypeIndex > & arrays, const StringImports & strings, DataRange * data) [inline]
Definition at line 2370 of file random-module-generation.cc.
      : options_(options),
        builder_(fn),
        functions_(functions),
        globals_(globals),
        mutable_globals_(mutable_globals),
        structs_(structs),
        arrays_(arrays),
        string_imports_(strings) {
    const FunctionSig* sig = fn->signature();
    blocks_.emplace_back();
    for (size_t i = 0; i < sig->return_count(); ++i) {
      blocks_.back().push_back(sig->GetReturn(i));
    }
    locals_.resize(data->get<uint8_t>() % kMaxLocals);
    uint32_t num_types = static_cast<uint32_t>(
        functions_.size() + structs_.size() + arrays_.size());
    for (ValueType& local : locals_) {
      local = GetValueType(options, data, num_types);
      fn->AddLocal(local);
    }
  }
References v8::internal::wasm::WasmFunctionBuilder::AddLocal(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxLocals, v8::internal::sig, and v8::internal::wasm::WasmFunctionBuilder::signature().
Member Function Documentation
all_locals_count()
size_t v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::all_locals_count () const [inline]
Definition at line 2404 of file random-module-generation.cc.
                                  {
    return builder_->signature()->parameter_count() + locals_.size();
  }
any_block()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::any_block (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, DataRange * data) [inline], [private]
Definition at line 716 of file random-module-generation.cc.
                                                                            {
    uint8_t available_cases = v8_flags.experimental_wasm_exnref ? 6 : 5;
    uint8_t block_type = data->get<uint8_t>() % available_cases;
    switch (block_type) {
      case 0:
        block(param_types, return_types, data);
        return;
      case 1:
        loop(param_types, return_types, data);
        return;
      case 2:
        finite_loop(param_types, return_types, data);
        return;
      case 3:
        if (param_types == return_types) {
          if_({}, {}, kIf, data);
          return;
        }
        [[fallthrough]];
      case 4:
        if_(param_types, return_types, kIfElse, data);
        return;
      case 5:
        try_table_block_helper(param_types, return_types, data);
        return;
    }
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), and v8::internal::v8_flags.
any_convert_extern()
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::any_convert_extern (HeapType type, DataRange * data, Nullability nullable) [inline], [private]
Definition at line 2108 of file random-module-generation.cc.
                                                {
    if (type.representation() != HeapType::kAny) {
      return false;
    }
    GenerateRef(kWasmExternRef, data);
    builder_->EmitWithPrefix(kExprAnyConvertExtern);
    if (nullable == kNonNullable) {
      builder_->Emit(kExprRefAsNonNull);
    }
    return true;
  }
References v8::internal::wasm::HeapType::kAny, v8::internal::wasm::kNonNullable, v8::internal::wasm::kWasmExternRef, and v8::internal::tracing::type.
array_copy()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_copy (DataRange * data) [inline], [private]
Definition at line 1726 of file random-module-generation.cc.
                                   {
    DCHECK_NE(0, arrays_.size()); // We always emit at least one array type.
    // TODO(14034): The source element type only has to be a subtype of the
    // destination element type. Currently this only generates copy from same
    // typed arrays.
    ModuleTypeIndex array_index =
        arrays_[data->get<uint8_t>() % arrays_.size()];
    DCHECK(builder_->builder()->IsArrayType(array_index));
    GenerateRef(HeapType::Index(array_index, kNotShared, RefTypeKind::kArray),
                data); // destination
    Generate(kWasmI32, data); // destination index
    GenerateRef(HeapType::Index(array_index, kNotShared, RefTypeKind::kArray),
                data); // source
    Generate(kWasmI32, data); // source index
    Generate(kWasmI32, data); // length
    builder_->EmitWithPrefix(kExprArrayCopy);
    builder_->EmitU32V(array_index); // destination array type index
    builder_->EmitU32V(array_index); // source array type index
  }
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::HeapType::Index(), v8::internal::wasm::kArray, v8::internal::kNotShared, and v8::internal::wasm::kWasmI32.
array_fill()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_fill (DataRange * data) [inline], [private]
Definition at line 1746 of file random-module-generation.cc.
                                   {
    DCHECK_NE(0, arrays_.size()); // We always emit at least one array type.
    ModuleTypeIndex array_index =
        arrays_[data->get<uint8_t>() % arrays_.size()];
    DCHECK(builder_->builder()->IsArrayType(array_index));
    ValueType element_type = builder_->builder()
                                 ->GetArrayType(array_index)
                                 ->element_type()
                                 .Unpacked();
    GenerateRef(HeapType::Index(array_index, kNotShared, RefTypeKind::kArray),
                data); // array
    Generate(kWasmI32, data); // offset
    Generate(element_type, data); // value
    Generate(kWasmI32, data); // length
    builder_->EmitWithPrefix(kExprArrayFill);
    builder_->EmitU32V(array_index);
  }
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::HeapType::Index(), v8::internal::wasm::kArray, v8::internal::kNotShared, v8::internal::wasm::kWasmI32, and v8::internal::wasm::ValueType::Unpacked().
array_get()
template<ValueKind wanted_kind>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get (DataRange * data) [inline], [private]
Definition at line 1699 of file random-module-generation.cc.
                                  {
    bool got_array_value =
        array_get_helper(ValueType::Primitive(wanted_kind), data);
    if (!got_array_value) {
      Generate<wanted_kind>(data);
    }
  }
References v8::internal::wasm::ValueType::Primitive().
array_get_helper()
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_helper (ValueType value_type, DataRange * data) [inline], [private]
Definition at line 1665 of file random-module-generation.cc.
                                                               {
    WasmModuleBuilder* builder = builder_->builder();
    ZoneVector<ModuleTypeIndex> array_indices(builder->zone());
    for (ModuleTypeIndex i : arrays_) {
      DCHECK(builder->IsArrayType(i));
      if (builder->GetArrayType(i)->element_type().Unpacked() == value_type) {
        array_indices.push_back(i);
      }
    }
    if (!array_indices.empty()) {
      int index = data->get<uint8_t>() % static_cast<int>(array_indices.size());
      GenerateRef(HeapType::Index(array_indices[index], kNotShared,
                                  RefTypeKind::kArray),
                  data, kNullable);
      Generate(kWasmI32, data);
      if (builder->GetArrayType(array_indices[index])
              ->element_type()
              .is_packed()) {
        builder_->EmitWithPrefix(data->get<bool>() ? kExprArrayGetS
                                                   : kExprArrayGetU);
      } else {
        builder_->EmitWithPrefix(kExprArrayGet);
      }
      builder_->EmitU32V(array_indices[index]);
      return true;
    }
    return false;
  }
References v8::internal::DCHECK(), v8::internal::wasm::ArrayType::element_type(), v8::internal::ZoneVector< T >::empty(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::WasmModuleBuilder::GetArrayType(), v8::internal::index, v8::internal::wasm::HeapType::Index(), v8::internal::wasm::ValueTypeBase::is_packed(), v8::internal::wasm::WasmModuleBuilder::IsArrayType(), v8::internal::wasm::kArray, v8::internal::kNotShared, v8::internal::wasm::kNullable, v8::internal::wasm::kWasmI32, v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::size(), v8::internal::wasm::ValueType::Unpacked(), v8::internal::wasm::value_type(), and v8::internal::wasm::WasmModuleBuilder::zone().
array_get_ref()
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_ref (HeapType type, DataRange * data, Nullability nullable) [inline], [private]
Definition at line 1706 of file random-module-generation.cc.
                                                                           {
    ValueType needed_type = ValueType::RefMaybeNull(type, nullable);
    return array_get_helper(needed_type, data);
  }
References v8::internal::wasm::ValueType::RefMaybeNull(), and v8::internal::tracing::type.
array_init_data()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_data (DataRange * data) [inline], [private]
Definition at line 1764 of file random-module-generation.cc.
                                        {
    DCHECK_NE(0, arrays_.size()); // We always emit at least one array type.
    ModuleTypeIndex array_index =
        arrays_[data->get<uint8_t>() % arrays_.size()];
    DCHECK(builder_->builder()->IsArrayType(array_index));
    const ArrayType* array_type =
        builder_->builder()->GetArrayType(array_index);
    DCHECK(array_type->mutability());
    ValueType element_type = array_type->element_type().Unpacked();
    if (element_type.is_reference()) {
      return;
    }
    if (builder_->builder()->NumDataSegments() == 0) {
      GeneratePassiveDataSegment(data, builder_->builder());
    }
    int data_index =
        data->get<uint8_t>() % builder_->builder()->NumDataSegments();
    // Generate array, index, data_offset, length.
    Generate({ValueType::RefNull(array_index, kNotShared, RefTypeKind::kArray),
              kWasmI32, kWasmI32, kWasmI32},
             data);
    builder_->EmitWithPrefix(kExprArrayInitData);
    builder_->EmitU32V(array_index);
    builder_->EmitU32V(data_index);
  }
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::wasm::ArrayType::element_type(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GeneratePassiveDataSegment(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::wasm::kArray, v8::internal::kNotShared, v8::internal::wasm::kWasmI32, v8::internal::wasm::ArrayTypeBase::mutability(), v8::internal::wasm::ValueType::RefNull(), and v8::internal::wasm::ValueType::Unpacked().
array_init_elem()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_elem (DataRange * data) [inline], [private]
Definition at line 1791 of file random-module-generation.cc.
                                        {
    DCHECK_NE(0, arrays_.size()); // We always emit at least one array type.
    ModuleTypeIndex array_index =
        arrays_[data->get<uint8_t>() % arrays_.size()];
    DCHECK(builder_->builder()->IsArrayType(array_index));
    const ArrayType* array_type =
        builder_->builder()->GetArrayType(array_index);
    DCHECK(array_type->mutability());
    ValueType element_type = array_type->element_type().Unpacked();
    // This is more restrictive than it has to be.
    // TODO(14034): Also support nonnullable and non-index reference
    // types.
    if (!element_type.is_reference() || element_type.is_non_nullable() ||
        !element_type.has_index()) {
      return;
    }
    // Add a new element segment with the corresponding type.
    uint32_t element_segment =
        GenerateRefTypeElementSegment(data, builder_->builder(), element_type);
    // Generate array, index, elem_offset, length.
    // TODO(14034): Change the distribution here to make it more likely
    // that the numbers are in range.
    Generate({ValueType::RefNull(array_index, kNotShared, RefTypeKind::kArray),
              kWasmI32, kWasmI32, kWasmI32},
             data);
    // Generate array.new_elem instruction.
    builder_->EmitWithPrefix(kExprArrayInitElem);
    builder_->EmitU32V(array_index);
    builder_->EmitU32V(element_segment);
  }
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::wasm::ArrayType::element_type(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateRefTypeElementSegment(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::ValueTypeBase::is_non_nullable(), v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::wasm::kArray, v8::internal::kNotShared, v8::internal::wasm::kWasmI32, v8::internal::wasm::ArrayTypeBase::mutability(), v8::internal::wasm::ValueType::RefNull(), and v8::internal::wasm::ValueType::Unpacked().
array_len()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_len (DataRange * data) [inline], [private]
Definition at line 1720 of file random-module-generation.cc.
                                  {
    DCHECK_NE(0, arrays_.size()); // We always emit at least one array type.
    GenerateRef(kWasmArrayRef, data);
    builder_->EmitWithPrefix(kExprArrayLen);
  }
References DCHECK_NE, and v8::internal::wasm::kWasmArrayRef.
array_set()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_set (DataRange * data) [inline], [private]
Definition at line 1822 of file random-module-generation.cc.
                                  {
    WasmModuleBuilder* builder = builder_->builder();
    ZoneVector<ModuleTypeIndex> array_indices(builder->zone());
    for (ModuleTypeIndex i : arrays_) {
      DCHECK(builder->IsArrayType(i));
      if (builder->GetArrayType(i)->mutability()) {
        array_indices.push_back(i);
      }
    }
    if (array_indices.empty()) {
      return;
    }
    int index = data->get<uint8_t>() % static_cast<int>(array_indices.size());
    GenerateRef(
        HeapType::Index(array_indices[index], kNotShared, RefTypeKind::kArray),
        data);
    Generate(kWasmI32, data);
    Generate(
        builder->GetArrayType(array_indices[index])->element_type().Unpacked(),
        data);
    builder_->EmitWithPrefix(kExprArraySet);
    builder_->EmitU32V(array_indices[index]);
  }
References v8::internal::DCHECK(), v8::internal::wasm::ArrayType::element_type(), v8::internal::ZoneVector< T >::empty(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::WasmModuleBuilder::GetArrayType(), v8::internal::index, v8::internal::wasm::HeapType::Index(), v8::internal::wasm::WasmModuleBuilder::IsArrayType(), v8::internal::wasm::kArray, v8::internal::kNotShared, v8::internal::wasm::kWasmI32, v8::internal::wasm::ArrayTypeBase::mutability(), v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::size(), v8::internal::wasm::ValueType::Unpacked(), and v8::internal::wasm::WasmModuleBuilder::zone().
AsNullable()
ValueType v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::AsNullable (ValueType original) [inline], [private]
Definition at line 1205 of file random-module-generation.cc.
                                           {
    if (!original.is_ref()) return original;
    return original.AsNullable();
  }
References v8::internal::wasm::ValueType::AsNullable(), and v8::internal::wasm::ValueTypeBase::is_ref().
block() [1/2]
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::block (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, DataRange * data) [inline], [private]
Definition at line 466 of file random-module-generation.cc.
                                                                        {
    BlockScope block_scope(this, kExprBlock, param_types, return_types,
                           return_types);
    ConsumeAndGenerate(param_types, return_types, data);
  }
block() [2/2]
template<ValueKind T>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::block (DataRange * data) [inline], [private]
Definition at line 474 of file random-module-generation.cc.
                              {
    if constexpr (T == kVoid) {
      block({}, {}, data);
    } else {
      block({}, base::VectorOf({ValueType::Primitive(T)}), data);
    }
  }
References v8::internal::wasm::ValueType::Primitive(), and v8::base::VectorOf().
br()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br (DataRange * data) [inline], [private]
Definition at line 745 of file random-module-generation.cc.
                           {
    // There is always at least the block representing the function body.
    DCHECK(!blocks_.empty());
    const uint32_t target_block = data->get<uint8_t>() % blocks_.size();
    const auto break_types = base::VectorOf(blocks_[target_block]);
    Generate(break_types, data);
    builder_->EmitWithI32V(
        kExprBr, static_cast<uint32_t>(blocks_.size()) - 1 - target_block);
  }
References v8::internal::DCHECK(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), and v8::base::VectorOf().
br_if()
template<ValueKind wanted_kind>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_if (DataRange * data) [inline], [private]
Definition at line 757 of file random-module-generation.cc.
                              {
    // There is always at least the block representing the function body.
    DCHECK(!blocks_.empty());
    const uint32_t target_block = data->get<uint8_t>() % blocks_.size();
    const auto break_types = base::VectorOf(blocks_[target_block]);
    Generate(break_types, data);
    Generate(kWasmI32, data);
    builder_->EmitWithI32V(
        kExprBrIf, static_cast<uint32_t>(blocks_.size()) - 1 - target_block);
    ConsumeAndGenerate(
        break_types,
        wanted_kind == kVoid
            ? base::Vector<ValueType>{}
            : base::VectorOf({ValueType::Primitive(wanted_kind)}),
        data);
  }
References v8::internal::DCHECK(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::kWasmI32, v8::internal::wasm::ValueType::Primitive(), and v8::base::VectorOf().
br_on_cast()
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_on_cast (HeapType type, DataRange * data, Nullability nullable) [inline], [private]
Definition at line 2044 of file random-module-generation.cc.
                                                                        {
    DCHECK(!blocks_.empty());
    const uint32_t target_block = data->get<uint8_t>() % blocks_.size();
    const uint32_t block_index =
        static_cast<uint32_t>(blocks_.size()) - 1 - target_block;
    const auto break_types = base::VectorOf(blocks_[target_block]);
    if (break_types.empty()) {
      return false;
    }
    ValueType break_type = break_types.last();
    if (!break_type.is_reference()) {
      return false;
    }
    Generate(break_types.SubVector(0, break_types.size() - 1), data);
    if (data->get<bool>()) {
      // br_on_cast
      HeapType source_type = top_type(break_type.heap_type());
      const bool source_is_nullable = data->get<bool>();
      GenerateRef(source_type, data,
                  source_is_nullable ? kNullable : kNonNullable);
      const bool target_is_nullable =
          source_is_nullable && break_type.is_nullable() && data->get<bool>();
      builder_->EmitWithPrefix(kExprBrOnCast);
      builder_->EmitU32V(source_is_nullable + (target_is_nullable << 1));
      builder_->EmitU32V(block_index);
      builder_->EmitHeapType(source_type); // source type
      builder_->EmitHeapType(break_type.heap_type()); // target type
      // Fallthrough: The type has been up-cast to the source type of the
      // br_on_cast instruction! (If the type on the stack was more specific,
      // this loses type information.)
      base::SmallVector<ValueType, 32> fallthrough_types(break_types);
      fallthrough_types.back() = ValueType::RefMaybeNull(
          source_type, source_is_nullable ? kNullable : kNonNullable);
      ConsumeAndGenerate(base::VectorOf(fallthrough_types), {}, data);
      // Generate the actually desired ref type.
      GenerateRef(type, data, nullable);
    } else {
      // br_on_cast_fail
      HeapType source_type = break_type.heap_type();
      const bool source_is_nullable = data->get<bool>();
      GenerateRef(source_type, data,
                  source_is_nullable ? kNullable : kNonNullable);
      const bool target_is_nullable =
          source_is_nullable &&
          (!break_type.is_nullable() || data->get<bool>());
      HeapType target_type = choose_sub_type(source_type, data);
      builder_->EmitWithPrefix(kExprBrOnCastFail);
      builder_->EmitU32V(source_is_nullable + (target_is_nullable << 1));
      builder_->EmitU32V(block_index);
      builder_->EmitHeapType(source_type);
      builder_->EmitHeapType(target_type);
      // Fallthrough: The type has been cast to the target type.
      base::SmallVector<ValueType, 32> fallthrough_types(break_types);
      fallthrough_types.back() = ValueType::RefMaybeNull(
          target_type, target_is_nullable ? kNullable : kNonNullable);
      ConsumeAndGenerate(base::VectorOf(fallthrough_types), {}, data);
      // Generate the actually desired ref type.
      GenerateRef(type, data, nullable);
    }
    return true;
  }
References v8::base::SmallVector< T, kSize, Allocator >::back(), v8::internal::DCHECK(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::ValueType::heap_type(), v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::wasm::kNonNullable, v8::internal::wasm::kNullable, v8::internal::wasm::ValueType::RefMaybeNull(), v8::internal::tracing::type, and v8::base::VectorOf().
br_on_non_null()
template<ValueKind wanted_kind>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_on_non_null (DataRange * data) [inline], [private]
Definition at line 795 of file random-module-generation.cc.
                                       {
    DCHECK(!blocks_.empty());
    const uint32_t target_block = data->get<uint8_t>() % blocks_.size();
    const auto break_types = base::VectorOf(blocks_[target_block]);
    if (break_types.empty() ||
        !break_types[break_types.size() - 1].is_reference()) {
      // Invalid break_types for br_on_non_null.
      Generate<wanted_kind>(data);
      return;
    }
    Generate(break_types, data);
    builder_->EmitWithI32V(
        kExprBrOnNonNull,
        static_cast<uint32_t>(blocks_.size()) - 1 - target_block);
    ConsumeAndGenerate(
        break_types.SubVector(0, break_types.size() - 1),
        wanted_kind == kVoid
            ? base::Vector<ValueType>{}
            : base::VectorOf({ValueType::Primitive(wanted_kind)}),
        data);
  }
References v8::internal::DCHECK(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), and v8::base::VectorOf().
br_on_null()
template<ValueKind wanted_kind>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_on_null (DataRange * data) [inline], [private]
Definition at line 776 of file random-module-generation.cc.
                                   {
    DCHECK(!blocks_.empty());
    const uint32_t target_block = data->get<uint8_t>() % blocks_.size();
    const auto break_types = base::VectorOf(blocks_[target_block]);
    Generate(break_types, data);
    GenerateRef(data);
    builder_->EmitWithI32V(
        kExprBrOnNull,
        static_cast<uint32_t>(blocks_.size()) - 1 - target_block);
    builder_->Emit(kExprDrop);
    ConsumeAndGenerate(
        break_types,
        wanted_kind == kVoid
            ? base::Vector<ValueType>{}
            : base::VectorOf({ValueType::Primitive(wanted_kind)}),
        data);
  }
References v8::internal::DCHECK(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::ValueType::Primitive(), and v8::base::VectorOf().
br_table() [1/2]
template<ValueKind wanted_kind>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_table (DataRange * data) [inline], [private]
Definition at line 861 of file random-module-generation.cc.
                                 {
    br_table(
        wanted_kind == kVoid ? kWasmVoid : ValueType::Primitive(wanted_kind),
        data);
  }
References v8::internal::wasm::kWasmVoid, and v8::internal::wasm::ValueType::Primitive().
br_table() [2/2]
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_table (ValueType result_type, DataRange * data) [inline], [private]
Definition at line 817 of file random-module-generation.cc.
                                                        {
    const uint8_t block_count = 1 + data->get<uint8_t>() % 8;
    // Generate the block entries.
    uint16_t entry_bits =
        block_count > 4 ? data->get<uint16_t>() : data->get<uint8_t>();
    for (size_t i = 0; i < block_count; ++i) {
      builder_->Emit(kExprBlock);
      builder_->EmitValueType(result_type);
      blocks_.emplace_back();
      if (result_type != kWasmVoid) {
        blocks_.back().push_back(result_type);
      }
      // There can be additional instructions in each block.
      // Only generate it with a 25% chance as it's otherwise quite unlikely to
      // have enough random bytes left for the br_table instruction.
      if ((entry_bits & 3) == 3) {
        Generate(kWasmVoid, data);
      }
      entry_bits >>= 2;
    }
    // Generate the br_table.
    Generate(result_type, data);
    Generate(kWasmI32, data);
    builder_->Emit(kExprBrTable);
    uint32_t entry_count = 1 + data->get<uint8_t>() % 8;
    builder_->EmitU32V(entry_count);
    for (size_t i = 0; i < entry_count + 1; ++i) {
      builder_->EmitU32V(data->get<uint8_t>() % block_count);
    }
    // Generate the block ends.
    uint8_t exit_bits = result_type == kWasmVoid ? 0 : data->get<uint8_t>();
    for (size_t i = 0; i < block_count; ++i) {
      if (exit_bits & 1) {
        // Drop and generate new value.
        builder_->Emit(kExprDrop);
        Generate(result_type, data);
      }
      exit_bits >>= 1;
      builder_->Emit(kExprEnd);
      blocks_.pop_back();
    }
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::kWasmI32, and v8::internal::wasm::kWasmVoid.
call() [1/2]
template<ValueKind wanted_kind>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::call (DataRange * data) [inline], [private]
Definition at line 1069 of file random-module-generation.cc.
                             {
    call(data, ValueType::Primitive(wanted_kind), kCallDirect);
  }
References v8::internal::wasm::ValueType::Primitive().
call() [2/2]
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::call (DataRange * data, ValueType wanted_kind, CallKind call_kind) [inline], [private]
Definition at line 1124 of file random-module-generation.cc.
                                                                        {
    uint8_t random_byte = data->get<uint8_t>();
    int func_index = random_byte % functions_.size();
    ModuleTypeIndex sig_index = functions_[func_index];
    const FunctionSig* sig = builder_->builder()->GetSignature(sig_index);
    // Generate arguments.
    for (size_t i = 0; i < sig->parameter_count(); ++i) {
      Generate(sig->GetParam(i), data);
    }
    // Emit call.
    // If the return types of the callee happen to match the return types of the
    // caller, generate a tail call.
    bool use_return_call = random_byte > 127;
    if (use_return_call &&
        std::equal(sig->returns().begin(), sig->returns().end(),
                   builder_->signature()->returns().begin(),
                   builder_->signature()->returns().end())) {
      if (call_kind == kCallDirect) {
        builder_->EmitWithU32V(kExprReturnCall,
                               NumImportedFunctions() + func_index);
      } else if (call_kind == kCallIndirect) {
        // This will not trap because table[func_index] always contains function
        // func_index.
        uint32_t table_index = choose_function_table_index(data);
        builder_->builder()->IsTable64(table_index)
            ? builder_->EmitI64Const(func_index)
            : builder_->EmitI32Const(func_index);
        builder_->EmitWithU32V(kExprReturnCallIndirect, sig_index);
        builder_->EmitByte(table_index);
      } else {
        GenerateRef(
            HeapType::Index(sig_index, kNotShared, RefTypeKind::kFunction),
            data);
        builder_->EmitWithU32V(kExprReturnCallRef, sig_index);
      }
      return;
    } else {
      if (call_kind == kCallDirect) {
        builder_->EmitWithU32V(kExprCallFunction,
                               NumImportedFunctions() + func_index);
      } else if (call_kind == kCallIndirect) {
        // This will not trap because table[func_index] always contains function
        // func_index.
        uint32_t table_index = choose_function_table_index(data);
        builder_->builder()->IsTable64(table_index)
            ? builder_->EmitI64Const(func_index)
            : builder_->EmitI32Const(func_index);
        builder_->EmitWithU32V(kExprCallIndirect, sig_index);
        builder_->EmitByte(table_index);
      } else {
        GenerateRef(
            HeapType::Index(sig_index, kNotShared, RefTypeKind::kFunction),
            data);
        builder_->EmitWithU32V(kExprCallRef, sig_index);
      }
    }
    if (sig->return_count() == 0 && wanted_kind != kWasmVoid) {
      // The call did not generate a value. Thus just generate it here.
      Generate(wanted_kind, data);
      return;
    }
    if (wanted_kind == kWasmVoid) {
      // The call did generate values, but we did not want one.
      for (size_t i = 0; i < sig->return_count(); ++i) {
        builder_->Emit(kExprDrop);
      }
      return;
    }
    auto wanted_types =
        base::VectorOf(&wanted_kind, wanted_kind == kWasmVoid ? 0 : 1);
    ConsumeAndGenerate(sig->returns(), wanted_types, data);
  }
References v8::internal::equal, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::HeapType::Index(), v8::internal::wasm::kFunction, v8::internal::kNotShared, v8::internal::wasm::kWasmVoid, v8::internal::sig, and v8::base::VectorOf().
call_indirect()
template<ValueKind wanted_kind>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::call_indirect (DataRange * data) [inline], [private]
Definition at line 1074 of file random-module-generation.cc.
                                      {
    call(data, ValueType::Primitive(wanted_kind), kCallIndirect);
  }
References v8::internal::wasm::ValueType::Primitive().
call_ref()
template<ValueKind wanted_kind>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::call_ref (DataRange * data) [inline], [private]
Definition at line 1079 of file random-module-generation.cc.
                                 {
    call(data, ValueType::Primitive(wanted_kind), kCallRef);
  }
References v8::internal::wasm::ValueType::Primitive().
call_string_import()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::call_string_import (uint32_t index) [inline], [private]
Definition at line 2186 of file random-module-generation.cc.
                                          {
    builder_->EmitWithU32V(kExprCallFunction, index);
  }
References v8::internal::index.
choose_function_table_index()
int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::choose_function_table_index (DataRange * data) [inline], [private]
Definition at line 1111 of file random-module-generation.cc.
                                                   {
    int table_count = builder_->builder()->NumTables();
    int start = data->get<uint8_t>() % table_count;
    for (int i = 0; i < table_count; ++i) {
      int index = (start + i) % table_count;
      if (builder_->builder()->GetTableType(index).is_reference_to(
              HeapType::kFunc)) {
        return index;
      }
    }
    FATAL("No funcref table found; table index 0 is expected to be funcref");
  }
References FATAL, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, and v8::internal::wasm::HeapType::kFunc.
choose_sub_type()
HeapType v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::choose_sub_type (HeapType type, DataRange * data) [inline], [private]
Definition at line 1934 of file random-module-generation.cc.
                                                           {
    switch (type.representation()) {
      case HeapType::kAny: {
        constexpr GenericKind generic_types[] = {
            GenericKind::kAny, GenericKind::kEq, GenericKind::kArray,
            GenericKind::kStruct, GenericKind::kI31, GenericKind::kNone,
        };
        size_t choice =
            data->get<uint8_t>() %
            (arrays_.size() + structs_.size() + arraysize(generic_types));
        if (choice < arrays_.size()) {
          return HeapType::Index(arrays_[choice], kNotShared,
                                 RefTypeKind::kArray);
        }
        choice -= arrays_.size();
        if (choice < structs_.size()) {
          return HeapType::Index(structs_[choice], kNotShared,
                                 RefTypeKind::kStruct);
        }
        choice -= structs_.size();
        return HeapType::Generic(generic_types[choice], kNotShared);
      }
      case HeapType::kEq: {
        constexpr GenericKind generic_types[] = {
            GenericKind::kEq, GenericKind::kArray, GenericKind::kStruct,
            GenericKind::kI31, GenericKind::kNone,
        };
        size_t choice =
            data->get<uint8_t>() %
            (arrays_.size() + structs_.size() + arraysize(generic_types));
        if (choice < arrays_.size()) {
          return HeapType::Index(arrays_[choice], kNotShared,
                                 RefTypeKind::kArray);
        }
        choice -= arrays_.size();
        if (choice < structs_.size()) {
          return HeapType::Index(structs_[choice], kNotShared,
                                 RefTypeKind::kStruct);
        }
        choice -= structs_.size();
        return HeapType::Generic(generic_types[choice], kNotShared);
      }
      case HeapType::kStruct: {
        constexpr GenericKind generic_types[] = {
            GenericKind::kStruct,
            GenericKind::kNone,
        };
        const size_t type_count = structs_.size();
        const size_t choice =
            data->get<uint8_t>() % (type_count + arraysize(generic_types));
        return choice >= type_count
                   ? HeapType::Generic(generic_types[choice - type_count],
                                       kNotShared)
                   : HeapType::Index(structs_[choice], kNotShared,
                                     RefTypeKind::kStruct);
      }
      case HeapType::kArray: {
        constexpr GenericKind generic_types[] = {
            GenericKind::kArray,
            GenericKind::kNone,
        };
        const size_t type_count = arrays_.size();
        const size_t choice =
            data->get<uint8_t>() % (type_count + arraysize(generic_types));
        return choice >= type_count
                   ? HeapType::Generic(generic_types[choice - type_count],
                                       kNotShared)
                   : HeapType::Index(arrays_[choice], kNotShared,
                                     RefTypeKind::kArray);
      }
      case HeapType::kFunc: {
        constexpr GenericKind generic_types[] = {GenericKind::kFunc,
                                                 GenericKind::kNoFunc};
        const size_t type_count = functions_.size();
        const size_t choice =
            data->get<uint8_t>() % (type_count + arraysize(generic_types));
        return choice >= type_count
                   ? HeapType::Generic(generic_types[choice - type_count],
                                       kNotShared)
                   : HeapType::Index(functions_[choice], kNotShared,
                                     RefTypeKind::kFunction);
      }
      case HeapType::kExtern:
        // About 10% of chosen subtypes will be kNoExtern.
        return HeapType::Generic(data->get<uint8_t>() > 25
                                     ? GenericKind::kExtern
                                     : GenericKind::kNoExtern,
                                 kNotShared);
      default:
        if (!type.is_index()) {
          // No logic implemented to find a sub-type.
          return type;
        }
        // Collect all (direct) sub types.
        // TODO(14034): Also collect indirect sub types.
        std::vector<ModuleTypeIndex> subtypes;
        uint32_t type_count = builder_->builder()->NumTypes();
        for (uint32_t i = 0; i < type_count; ++i) {
          if (builder_->builder()->GetSuperType(i) == type.ref_index()) {
            subtypes.push_back(ModuleTypeIndex{i});
          }
        }
        if (subtypes.empty()) return type; // No downcast possible.
        return HeapType::Index(subtypes[data->get<uint8_t>() % subtypes.size()],
                               kNotShared, type.ref_type_kind());
    }
  }
References arraysize, v8::internal::wasm::HeapType::Generic(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::HeapType::Index(), v8::internal::wasm::HeapType::kAny, v8::internal::wasm::kArray, v8::internal::wasm::HeapType::kArray, v8::internal::wasm::HeapType::kEq, v8::internal::wasm::HeapType::kExtern, v8::internal::wasm::HeapType::kFunc, v8::internal::wasm::kFunction, v8::internal::kNotShared, v8::internal::torque::ls::kStruct, v8::internal::wasm::kStruct, v8::internal::wasm::HeapType::kStruct, and v8::internal::tracing::type.
Consume()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Consume (ValueType type) [inline]
Definition at line 3564 of file random-module-generation.cc.
                               {
    // Try to store the value in a local if there is a local with the same
    // type. TODO(14034): For reference types a local with a super type
    // would also be fine.
    size_t num_params = builder_->signature()->parameter_count();
    for (uint32_t local_offset = 0; local_offset < locals_.size();
         ++local_offset) {
      if (locals_[local_offset] == type) {
        uint32_t local_index = static_cast<uint32_t>(local_offset + num_params);
        builder_->EmitWithU32V(kExprLocalSet, local_index);
        return;
      }
    }
    for (uint32_t param_index = 0; param_index < num_params; ++param_index) {
      if (builder_->signature()->GetParam(param_index) == type) {
        builder_->EmitWithU32V(kExprLocalSet, param_index);
        return;
      }
    }
    // No opportunity found to use the value, so just drop it.
    builder_->Emit(kExprDrop);
  }
References v8::internal::tracing::type.
ConsumeAndGenerate()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ConsumeAndGenerate (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, DataRange * data) [inline]
Definition at line 3589 of file random-module-generation.cc.
                                           {
    // This numeric conversion logic consists of picking exactly one
    // index in the return values and dropping all the values that come
    // before that index. Then we convert the value from that index to the
    // wanted type. If we don't find any value we generate it.
    auto primitive = [](ValueType t) -> bool {
      switch (t.kind()) {
        case kI32:
        case kI64:
        case kF32:
        case kF64:
          return true;
        default:
          return false;
      }
    };
    if (return_types.size() == 0 || param_types.size() == 0 ||
        !primitive(return_types[0])) {
      for (auto iter = param_types.rbegin(); iter != param_types.rend();
           ++iter) {
        Consume(*iter);
      }
      Generate(return_types, data);
      return;
    }
    int bottom_primitives = 0;
    while (static_cast<int>(param_types.size()) > bottom_primitives &&
           primitive(param_types[bottom_primitives])) {
      bottom_primitives++;
    }
    int return_index =
        bottom_primitives > 0 ? (data->get<uint8_t>() % bottom_primitives) : -1;
    for (int i = static_cast<int>(param_types.size() - 1); i > return_index;
         --i) {
      Consume(param_types[i]);
    }
    for (int i = return_index; i > 0; --i) {
      Convert(param_types[i], param_types[i - 1]);
      builder_->EmitI32Const(0);
      builder_->Emit(kExprSelect);
    }
    DCHECK(!return_types.empty());
    if (return_index >= 0) {
      Convert(param_types[0], return_types[0]);
      Generate(return_types + 1, data);
    } else {
      Generate(return_types, data);
    }
  }
References v8::internal::DCHECK(), v8::base::Vector< T >::empty(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::base::Vector< T >::rbegin(), v8::base::Vector< T >::rend(), and v8::base::Vector< T >::size().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues().
Convert()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Convert (ValueType src, ValueType dst) [inline], [private]
Definition at line 1083 of file random-module-generation.cc.
                                             {
    auto idx = [](ValueType t) -> int {
      switch (t.kind()) {
        case kI32:
          return 0;
        case kI64:
          return 1;
        case kF32:
          return 2;
        case kF64:
          return 3;
        default:
          UNREACHABLE();
      }
    };
    static constexpr WasmOpcode kConvertOpcodes[] = {
        // {i32, i64, f32, f64} -> i32
        kExprNop, kExprI32ConvertI64, kExprI32SConvertF32, kExprI32SConvertF64,
        // {i32, i64, f32, f64} -> i64
        kExprI64SConvertI32, kExprNop, kExprI64SConvertF32, kExprI64SConvertF64,
        // {i32, i64, f32, f64} -> f32
        kExprF32SConvertI32, kExprF32SConvertI64, kExprNop, kExprF32ConvertF64,
        // {i32, i64, f32, f64} -> f64
        kExprF64SConvertI32, kExprF64SConvertI64, kExprF64ConvertF32, kExprNop};
    int arr_idx = idx(dst) << 2 | idx(src);
    builder_->Emit(kConvertOpcodes[arr_idx]);
  }
References v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, and v8::internal::UNREACHABLE().
drop()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::drop (DataRange * data) [inline], [private]
Definition at line 1057 of file random-module-generation.cc.
                             {
    Generate(
        GetValueType(options_, data,
                     static_cast<uint32_t>(functions_.size() + structs_.size() +
                                           arrays_.size())),
        data);
    builder_->Emit(kExprDrop);
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueType().
finite_loop() [1/2]
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::finite_loop (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, DataRange * data) [inline], [private]
Definition at line 498 of file random-module-generation.cc.
                                    {
    // int counter = `kLoopConstant`;
    int kLoopConstant = data->get<uint8_t>() % 8 + 1;
    uint32_t counter = builder_->AddLocal(kWasmI32);
    builder_->EmitI32Const(kLoopConstant);
    builder_->EmitSetLocal(counter);
    // begin loop {
    BlockScope loop_scope(this, kExprLoop, param_types, return_types,
                          param_types);
    // Consume the parameters:
    // Resetting locals in each iteration can create interesting loop-phis.
    // TODO(evih): Iterate through existing locals and try to reuse them instead
    // of creating new locals.
    for (auto it = param_types.rbegin(); it != param_types.rend(); it++) {
      uint32_t local = builder_->AddLocal(*it);
      builder_->EmitSetLocal(local);
    }
    // Loop body.
    Generate(kWasmVoid, data);
    // Decrement the counter.
    builder_->EmitGetLocal(counter);
    builder_->EmitI32Const(1);
    builder_->Emit(kExprI32Sub);
    builder_->EmitTeeLocal(counter);
    // If there is another iteration, generate new parameters for the loop and
    // go to the beginning of the loop.
    {
      BlockScope if_scope(this, kExprIf, {}, {}, {});
      Generate(param_types, data);
      builder_->EmitWithI32V(kExprBr, 1);
    }
    // Otherwise, generate the return types.
    Generate(return_types, data);
    // } end loop
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmVoid, v8::base::Vector< T >::rbegin(), and v8::base::Vector< T >::rend().
finite_loop() [2/2]
template<ValueKind T>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::finite_loop (DataRange * data) [inline], [private]
Definition at line 542 of file random-module-generation.cc.
                                    {
    if constexpr (T == kVoid) {
      finite_loop({}, {}, data);
    } else {
      finite_loop({}, base::VectorOf({ValueType::Primitive(T)}), data);
    }
  }
References v8::internal::wasm::ValueType::Primitive(), and v8::base::VectorOf().
Generate() [1/5]
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Generate (base::Vector< const ValueType > types, DataRange * data) [inline]
Definition at line 3524 of file random-module-generation.cc.
                                                                    {
    // Maybe emit a multi-value block with the expected return type. Use a
    // non-default value to indicate block generation to avoid recursion when we
    // reach the end of the data.
    bool generate_block = data->get<uint8_t>() % 32 == 1;
    if (generate_block) {
      GeneratorRecursionScope rec_scope(this);
      if (!recursion_limit_reached()) {
        const auto param_types = GenerateTypes(data);
        Generate(base::VectorOf(param_types), data);
        any_block(base::VectorOf(param_types), types, data);
        return;
      }
    }
    if (types.size() == 0) {
      Generate(kWasmVoid, data);
      return;
    }
    if (types.size() == 1) {
      Generate(types[0], data);
      return;
    }
    // Split the types in two halves and recursively generate each half.
    // Each half is non empty to ensure termination.
    size_t split_index = data->get<uint8_t>() % (types.size() - 1) + 1;
    base::Vector<const ValueType> lower_half = types.SubVector(0, split_index);
    base::Vector<const ValueType> upper_half =
        types.SubVector(split_index, types.size());
    DataRange first_range = data->split();
    Generate(lower_half, &first_range);
    Generate(upper_half, data);
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateTypes(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::kWasmVoid, v8::base::Vector< T >::size(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::split(), v8::base::Vector< T >::SubVector(), and v8::base::VectorOf().
Generate() [2/5]
template<ValueKind kind>
constexpr void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Generate (DataRange * data) [inline], [constexpr]
Definition at line 3240 of file random-module-generation.cc.
                                           {
    switch (kind) {
      case kVoid:
        return GenerateVoid(data);
      case kI32:
        return GenerateI32(data);
      case kI64:
        return GenerateI64(data);
      case kF32:
        return GenerateF32(data);
      case kF64:
        return GenerateF64(data);
      case kS128:
        return GenerateS128(data);
      default:
        // For kRefNull and kRef we need the HeapType which we can get from the
        // ValueType.
        UNREACHABLE();
    }
  }
References v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::kS128, and v8::internal::UNREACHABLE().
Generate() [3/5]
template<ValueKind T1, ValueKind T2, ValueKind... Ts>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Generate (DataRange * data) [inline]
Definition at line 3262 of file random-module-generation.cc.
                                 {
    // TODO(clemensb): Implement a more even split.
    auto first_data = data->split();
    Generate<T1>(&first_data);
    Generate<T2, Ts...>(data);
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::split(), and T2.
Generate() [4/5]
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Generate (std::initializer_list< ValueTypeBase > types, DataRange * data) [inline]
Definition at line 3558 of file random-module-generation.cc.
                                                                           {
    base::Vector<const ValueType> cast_types = base::VectorOf<const ValueType>(
        static_cast<const ValueType*>(types.begin()), types.size());
    return Generate(cast_types, data);
  }
Generate() [5/5]
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Generate (ValueType type, DataRange * data) [inline]
Definition at line 3216 of file random-module-generation.cc.
                                                 {
    switch (type.kind()) {
      case kVoid:
        return GenerateVoid(data);
      case kI32:
        return GenerateI32(data);
      case kI64:
        return GenerateI64(data);
      case kF32:
        return GenerateF32(data);
      case kF64:
        return GenerateF64(data);
      case kS128:
        return GenerateS128(data);
      case kRefNull:
        return GenerateRef(type.heap_type(), data, kNullable);
      case kRef:
        return GenerateRef(type.heap_type(), data, kNonNullable);
      default:
        UNREACHABLE();
    }
  }
References v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::wasm::kNonNullable, v8::internal::wasm::kNullable, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues().
GenerateF32()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateF32 (DataRange * data) [inline]
Definition at line 2809 of file random-module-generation.cc.
                                    {
    GeneratorRecursionScope rec_scope(this);
    if (recursion_limit_reached() || data->size() <= sizeof(float)) {
      builder_->EmitF32Const(data->getPseudoRandom<float>());
      return;
    }
    static constexpr auto kMvpAlternatives = CreateArray(
        &BodyGen::sequence<kF32, kVoid>, &BodyGen::sequence<kVoid, kF32>,
        &BodyGen::sequence<kVoid, kF32, kVoid>,
        &BodyGen::op<kExprF32Abs, kF32>, //
        &BodyGen::op<kExprF32Neg, kF32>, //
        &BodyGen::op<kExprF32Ceil, kF32>, //
        &BodyGen::op<kExprF32Floor, kF32>, //
        &BodyGen::op<kExprF32Trunc, kF32>, //
        &BodyGen::op<kExprF32NearestInt, kF32>, //
        &BodyGen::op<kExprF32Sqrt, kF32>, //
        &BodyGen::op<kExprF32Add, kF32, kF32>, //
        &BodyGen::op<kExprF32Sub, kF32, kF32>, //
        &BodyGen::op<kExprF32Mul, kF32, kF32>, //
        &BodyGen::op<kExprF32Div, kF32, kF32>, //
        &BodyGen::op<kExprF32Min, kF32, kF32>, //
        &BodyGen::op<kExprF32Max, kF32, kF32>, //
        &BodyGen::op<kExprF32CopySign, kF32, kF32>, //
        &BodyGen::op<kExprF32SConvertI32, kI32>,
        &BodyGen::op<kExprF32UConvertI32, kI32>,
        &BodyGen::op<kExprF32SConvertI64, kI64>,
        &BodyGen::op<kExprF32UConvertI64, kI64>,
        &BodyGen::op<kExprF32ConvertF64, kF64>,
        &BodyGen::op<kExprF32ReinterpretI32, kI32>,
        &BodyGen::block<kF32>, //
        &BodyGen::loop<kF32>, //
        &BodyGen::finite_loop<kF32>, //
        &BodyGen::if_<kF32, kIfElse>, //
        &BodyGen::br_if<kF32>, //
        &BodyGen::br_on_null<kF32>, //
        &BodyGen::br_on_non_null<kF32>, //
        &BodyGen::br_table<kF32>, //
        &BodyGen::try_table_block<kF32>, //
        &BodyGen::memop<kExprF32LoadMem>,
        &BodyGen::get_local<kF32>, //
        &BodyGen::tee_local<kF32>, //
        &BodyGen::get_global<kF32>, //
        &BodyGen::op<kExprSelect, kF32, kF32, kI32>, //
        &BodyGen::select_with_type<kF32>, //
        &BodyGen::call<kF32>, //
        &BodyGen::call_indirect<kF32>, //
        &BodyGen::call_ref<kF32>, //
        &BodyGen::try_block<kF32>);
    static constexpr auto kSimdAlternatives =
        CreateArray(&BodyGen::simd_lane_op<kExprF32x4ExtractLane, 4, kS128>);
    static constexpr auto kWasmGCAlternatives =
        CreateArray(&BodyGen::struct_get<kF32>, //
                    &BodyGen::array_get<kF32>);
    static constexpr GeneratorAlternativesPerOption kAlternativesPerOptions{
        kMvpAlternatives, kSimdAlternatives, kWasmGCAlternatives};
    GenerateOneOf(kAlternativesPerOptions, data);
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateArray(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::getPseudoRandom(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::size().
GenerateF64()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateF64 (DataRange * data) [inline]
Definition at line 2878 of file random-module-generation.cc.
                                    {
    GeneratorRecursionScope rec_scope(this);
    if (recursion_limit_reached() || data->size() <= sizeof(double)) {
      builder_->EmitF64Const(data->getPseudoRandom<double>());
      return;
    }
    static constexpr auto kMvpAlternatives = CreateArray(
        &BodyGen::sequence<kF64, kVoid>, &BodyGen::sequence<kVoid, kF64>,
        &BodyGen::sequence<kVoid, kF64, kVoid>,
        &BodyGen::op<kExprF64Abs, kF64>, //
        &BodyGen::op<kExprF64Neg, kF64>, //
        &BodyGen::op<kExprF64Ceil, kF64>, //
        &BodyGen::op<kExprF64Floor, kF64>, //
        &BodyGen::op<kExprF64Trunc, kF64>, //
        &BodyGen::op<kExprF64NearestInt, kF64>, //
        &BodyGen::op<kExprF64Sqrt, kF64>, //
        &BodyGen::op<kExprF64Add, kF64, kF64>, //
        &BodyGen::op<kExprF64Sub, kF64, kF64>, //
        &BodyGen::op<kExprF64Mul, kF64, kF64>, //
        &BodyGen::op<kExprF64Div, kF64, kF64>, //
        &BodyGen::op<kExprF64Min, kF64, kF64>, //
        &BodyGen::op<kExprF64Max, kF64, kF64>, //
        &BodyGen::op<kExprF64CopySign, kF64, kF64>, //
        &BodyGen::op<kExprF64SConvertI32, kI32>,
        &BodyGen::op<kExprF64UConvertI32, kI32>,
        &BodyGen::op<kExprF64SConvertI64, kI64>,
        &BodyGen::op<kExprF64UConvertI64, kI64>,
        &BodyGen::op<kExprF64ConvertF32, kF32>,
        &BodyGen::op<kExprF64ReinterpretI64, kI64>,
        &BodyGen::block<kF64>, //
        &BodyGen::loop<kF64>, //
        &BodyGen::finite_loop<kF64>, //
        &BodyGen::if_<kF64, kIfElse>, //
        &BodyGen::br_if<kF64>, //
        &BodyGen::br_on_null<kF64>, //
        &BodyGen::br_on_non_null<kF64>, //
        &BodyGen::br_table<kF64>, //
        &BodyGen::try_table_block<kF64>, //
        &BodyGen::memop<kExprF64LoadMem>,
        &BodyGen::get_local<kF64>, //
        &BodyGen::tee_local<kF64>, //
        &BodyGen::get_global<kF64>, //
        &BodyGen::op<kExprSelect, kF64, kF64, kI32>, //
        &BodyGen::select_with_type<kF64>, //
        &BodyGen::call<kF64>, //
        &BodyGen::call_indirect<kF64>, //
        &BodyGen::call_ref<kF64>, //
        &BodyGen::try_block<kF64>);
    static constexpr auto kSimdAlternatives =
        CreateArray(&BodyGen::simd_lane_op<kExprF64x2ExtractLane, 2, kS128>);
    static constexpr auto kWasmGCAlternatives =
        CreateArray(&BodyGen::struct_get<kF64>, //
                    &BodyGen::array_get<kF64>);
    static constexpr GeneratorAlternativesPerOption kAlternativesPerOptions{
        kMvpAlternatives, kSimdAlternatives, kWasmGCAlternatives};
    GenerateOneOf(kAlternativesPerOptions, data);
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateArray(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::getPseudoRandom(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::size().
GenerateI32()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateI32 (DataRange * data) [inline]
Definition at line 2501 of file random-module-generation.cc.
                                    {
    GeneratorRecursionScope rec_scope(this);
    if (recursion_limit_reached() || data->size() <= 1) {
      // Rather than evenly distributing values across the full 32-bit range,
      // distribute them evenly over the possible bit lengths. In particular,
      // for values used as indices into something else, smaller values are
      // more likely to be useful.
      uint8_t size = 1 + (data->getPseudoRandom<uint8_t>() & 31);
      uint32_t mask = kMaxUInt32 >> (32 - size);
      builder_->EmitI32Const(data->getPseudoRandom<uint32_t>() & mask);
      return;
    }
    static constexpr auto kMvpAlternatives = CreateArray(
        &BodyGen::i32_const<1>, //
        &BodyGen::i32_const<2>, //
        &BodyGen::i32_const<3>, //
        &BodyGen::i32_const<4>, //
        &BodyGen::sequence<kI32, kVoid>, //
        &BodyGen::sequence<kVoid, kI32>, //
        &BodyGen::sequence<kVoid, kI32, kVoid>, //
        &BodyGen::op<kExprI32Eqz, kI32>, //
        &BodyGen::op<kExprI32Eq, kI32, kI32>, //
        &BodyGen::op<kExprI32Ne, kI32, kI32>, //
        &BodyGen::op<kExprI32LtS, kI32, kI32>, //
        &BodyGen::op<kExprI32LtU, kI32, kI32>, //
        &BodyGen::op<kExprI32GeS, kI32, kI32>, //
        &BodyGen::op<kExprI32GeU, kI32, kI32>, //
        &BodyGen::op<kExprI64Eqz, kI64>, //
        &BodyGen::op<kExprI64Eq, kI64, kI64>, //
        &BodyGen::op<kExprI64Ne, kI64, kI64>, //
        &BodyGen::op<kExprI64LtS, kI64, kI64>, //
        &BodyGen::op<kExprI64LtU, kI64, kI64>, //
        &BodyGen::op<kExprI64GeS, kI64, kI64>, //
        &BodyGen::op<kExprI64GeU, kI64, kI64>, //
        &BodyGen::op<kExprF32Eq, kF32, kF32>,
        &BodyGen::op<kExprF32Ne, kF32, kF32>,
        &BodyGen::op<kExprF32Lt, kF32, kF32>,
        &BodyGen::op<kExprF32Ge, kF32, kF32>,
        &BodyGen::op<kExprF64Eq, kF64, kF64>,
        &BodyGen::op<kExprF64Ne, kF64, kF64>,
        &BodyGen::op<kExprF64Lt, kF64, kF64>,
        &BodyGen::op<kExprF64Ge, kF64, kF64>,
        &BodyGen::op<kExprI32Add, kI32, kI32>,
        &BodyGen::op<kExprI32Sub, kI32, kI32>,
        &BodyGen::op<kExprI32Mul, kI32, kI32>,
        &BodyGen::op<kExprI32DivS, kI32, kI32>,
        &BodyGen::op<kExprI32DivU, kI32, kI32>,
        &BodyGen::op<kExprI32RemS, kI32, kI32>,
        &BodyGen::op<kExprI32RemU, kI32, kI32>,
        &BodyGen::op<kExprI32And, kI32, kI32>,
        &BodyGen::op<kExprI32Ior, kI32, kI32>,
        &BodyGen::op<kExprI32Xor, kI32, kI32>,
        &BodyGen::op<kExprI32Shl, kI32, kI32>,
        &BodyGen::op<kExprI32ShrU, kI32, kI32>,
        &BodyGen::op<kExprI32ShrS, kI32, kI32>,
        &BodyGen::op<kExprI32Ror, kI32, kI32>,
        &BodyGen::op<kExprI32Rol, kI32, kI32>,
        &BodyGen::op<kExprI32Clz, kI32>, //
        &BodyGen::op<kExprI32Ctz, kI32>, //
        &BodyGen::op<kExprI32Popcnt, kI32>, //
        &BodyGen::op<kExprI32ConvertI64, kI64>,
        &BodyGen::op<kExprI32SConvertF32, kF32>,
        &BodyGen::op<kExprI32UConvertF32, kF32>,
        &BodyGen::op<kExprI32SConvertF64, kF64>,
        &BodyGen::op<kExprI32UConvertF64, kF64>,
        &BodyGen::op<kExprI32ReinterpretF32, kF32>,
        &BodyGen::op_with_prefix<kExprI32SConvertSatF32, kF32>,
        &BodyGen::op_with_prefix<kExprI32UConvertSatF32, kF32>,
        &BodyGen::op_with_prefix<kExprI32SConvertSatF64, kF64>,
        &BodyGen::op_with_prefix<kExprI32UConvertSatF64, kF64>,
        &BodyGen::block<kI32>, //
        &BodyGen::loop<kI32>, //
        &BodyGen::finite_loop<kI32>, //
        &BodyGen::if_<kI32, kIfElse>, //
        &BodyGen::br_if<kI32>, //
        &BodyGen::br_on_null<kI32>, //
        &BodyGen::br_on_non_null<kI32>, //
        &BodyGen::br_table<kI32>, //
        &BodyGen::try_table_block<kI32>, //
        &BodyGen::memop<kExprI32LoadMem>, //
        &BodyGen::memop<kExprI32LoadMem8S>, //
        &BodyGen::memop<kExprI32LoadMem8U>, //
        &BodyGen::memop<kExprI32LoadMem16S>, //
        &BodyGen::memop<kExprI32LoadMem16U>, //
                                                                        //
        &BodyGen::memop<kExprI32AtomicLoad>, //
        &BodyGen::memop<kExprI32AtomicLoad8U>, //
        &BodyGen::memop<kExprI32AtomicLoad16U>, //
        &BodyGen::memop<kExprI32AtomicAdd, kI32>, //
        &BodyGen::memop<kExprI32AtomicSub, kI32>, //
        &BodyGen::memop<kExprI32AtomicAnd, kI32>, //
        &BodyGen::memop<kExprI32AtomicOr, kI32>, //
        &BodyGen::memop<kExprI32AtomicXor, kI32>, //
        &BodyGen::memop<kExprI32AtomicExchange, kI32>, //
        &BodyGen::memop<kExprI32AtomicCompareExchange, kI32, kI32>, //
        &BodyGen::memop<kExprI32AtomicAdd8U, kI32>, //
        &BodyGen::memop<kExprI32AtomicSub8U, kI32>, //
        &BodyGen::memop<kExprI32AtomicAnd8U, kI32>, //
        &BodyGen::memop<kExprI32AtomicOr8U, kI32>, //
        &BodyGen::memop<kExprI32AtomicXor8U, kI32>, //
        &BodyGen::memop<kExprI32AtomicExchange8U, kI32>, //
        &BodyGen::memop<kExprI32AtomicCompareExchange8U, kI32, kI32>, //
        &BodyGen::memop<kExprI32AtomicAdd16U, kI32>, //
        &BodyGen::memop<kExprI32AtomicSub16U, kI32>, //
        &BodyGen::memop<kExprI32AtomicAnd16U, kI32>, //
        &BodyGen::memop<kExprI32AtomicOr16U, kI32>, //
        &BodyGen::memop<kExprI32AtomicXor16U, kI32>, //
        &BodyGen::memop<kExprI32AtomicExchange16U, kI32>, //
        &BodyGen::memop<kExprI32AtomicCompareExchange16U, kI32, kI32>, //
        &BodyGen::memory_size, //
        &BodyGen::grow_memory, //
        &BodyGen::get_local<kI32>, //
        &BodyGen::tee_local<kI32>, //
        &BodyGen::get_global<kI32>, //
        &BodyGen::op<kExprSelect, kI32, kI32, kI32>, //
        &BodyGen::select_with_type<kI32>, //
        &BodyGen::call<kI32>, //
        &BodyGen::call_indirect<kI32>, //
        &BodyGen::call_ref<kI32>, //
        &BodyGen::try_block<kI32>, //
        &BodyGen::table_size, //
        &BodyGen::table_grow);
    static constexpr auto kSimdAlternatives =
        CreateArray(&BodyGen::op_with_prefix<kExprV128AnyTrue, kS128>,
                    &BodyGen::op_with_prefix<kExprI8x16AllTrue, kS128>,
                    &BodyGen::op_with_prefix<kExprI8x16BitMask, kS128>,
                    &BodyGen::op_with_prefix<kExprI16x8AllTrue, kS128>,
                    &BodyGen::op_with_prefix<kExprI16x8BitMask, kS128>,
                    &BodyGen::op_with_prefix<kExprI32x4AllTrue, kS128>,
                    &BodyGen::op_with_prefix<kExprI32x4BitMask, kS128>,
                    &BodyGen::op_with_prefix<kExprI64x2AllTrue, kS128>,
                    &BodyGen::op_with_prefix<kExprI64x2BitMask, kS128>,
                    &BodyGen::simd_lane_op<kExprI8x16ExtractLaneS, 16, kS128>,
                    &BodyGen::simd_lane_op<kExprI8x16ExtractLaneU, 16, kS128>,
                    &BodyGen::simd_lane_op<kExprI16x8ExtractLaneS, 8, kS128>,
                    &BodyGen::simd_lane_op<kExprI16x8ExtractLaneU, 8, kS128>,
                    &BodyGen::simd_lane_op<kExprI32x4ExtractLane, 4, kS128>);
    static constexpr auto kWasmGCAlternatives =
        CreateArray(&BodyGen::i31_get, //
                                                           //
                    &BodyGen::struct_get<kI32>, //
                    &BodyGen::array_get<kI32>, //
                    &BodyGen::array_len, //
                                                           //
                    &BodyGen::ref_is_null, //
                    &BodyGen::ref_eq, //
                    &BodyGen::ref_test<kExprRefTest>, //
                    &BodyGen::ref_test<kExprRefTestNull>, //
                                                           //
                    &BodyGen::string_test, //
                    &BodyGen::string_charcodeat, //
                    &BodyGen::string_codepointat, //
                    &BodyGen::string_length, //
                    &BodyGen::string_equals, //
                    &BodyGen::string_compare, //
                    &BodyGen::string_intocharcodearray, //
                    &BodyGen::string_intoutf8array, //
                    &BodyGen::string_measureutf8);
    static constexpr GeneratorAlternativesPerOption kAlternativesPerOptions{
        kMvpAlternatives, kSimdAlternatives, kWasmGCAlternatives};
    GenerateOneOf(kAlternativesPerOptions, data);
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateArray(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::getPseudoRandom(), v8::internal::kMaxUInt32, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::size(), and size().
GenerateI64()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateI64 (DataRange * data) [inline]
Definition at line 2686 of file random-module-generation.cc.
                                    {
    GeneratorRecursionScope rec_scope(this);
    if (recursion_limit_reached() || data->size() <= 1) {
      builder_->EmitI64Const(data->getPseudoRandom<int64_t>());
      return;
    }
    static constexpr auto kMvpAlternatives = CreateArray(
        &BodyGen::i64_const<1>, //
        &BodyGen::i64_const<2>, //
        &BodyGen::i64_const<3>, //
        &BodyGen::i64_const<4>, //
        &BodyGen::i64_const<5>, //
        &BodyGen::i64_const<6>, //
        &BodyGen::i64_const<7>, //
        &BodyGen::i64_const<8>, //
        &BodyGen::sequence<kI64, kVoid>, //
        &BodyGen::sequence<kVoid, kI64>, //
        &BodyGen::sequence<kVoid, kI64, kVoid>, //
        &BodyGen::op<kExprI64Add, kI64, kI64>,
        &BodyGen::op<kExprI64Sub, kI64, kI64>,
        &BodyGen::op<kExprI64Mul, kI64, kI64>,
        &BodyGen::op<kExprI64DivS, kI64, kI64>,
        &BodyGen::op<kExprI64DivU, kI64, kI64>,
        &BodyGen::op<kExprI64RemS, kI64, kI64>,
        &BodyGen::op<kExprI64RemU, kI64, kI64>,
        &BodyGen::op<kExprI64And, kI64, kI64>,
        &BodyGen::op<kExprI64Ior, kI64, kI64>,
        &BodyGen::op<kExprI64Xor, kI64, kI64>,
        &BodyGen::op<kExprI64Shl, kI64, kI64>,
        &BodyGen::op<kExprI64ShrU, kI64, kI64>,
        &BodyGen::op<kExprI64ShrS, kI64, kI64>,
        &BodyGen::op<kExprI64Ror, kI64, kI64>,
        &BodyGen::op<kExprI64Rol, kI64, kI64>,
        &BodyGen::op<kExprI64Clz, kI64>, //
        &BodyGen::op<kExprI64Ctz, kI64>, //
        &BodyGen::op<kExprI64Popcnt, kI64>, //
        &BodyGen::op_with_prefix<kExprI64SConvertSatF32, kF32>,
        &BodyGen::op_with_prefix<kExprI64UConvertSatF32, kF32>,
        &BodyGen::op_with_prefix<kExprI64SConvertSatF64, kF64>,
        &BodyGen::op_with_prefix<kExprI64UConvertSatF64, kF64>,
        &BodyGen::block<kI64>, //
        &BodyGen::loop<kI64>, //
        &BodyGen::finite_loop<kI64>, //
        &BodyGen::if_<kI64, kIfElse>, //
        &BodyGen::br_if<kI64>, //
        &BodyGen::br_on_null<kI64>, //
        &BodyGen::br_on_non_null<kI64>, //
        &BodyGen::br_table<kI64>, //
        &BodyGen::try_table_block<kI64>, //
        &BodyGen::memop<kExprI64LoadMem>, //
        &BodyGen::memop<kExprI64LoadMem8S>, //
        &BodyGen::memop<kExprI64LoadMem8U>, //
        &BodyGen::memop<kExprI64LoadMem16S>, //
        &BodyGen::memop<kExprI64LoadMem16U>, //
        &BodyGen::memop<kExprI64LoadMem32S>, //
        &BodyGen::memop<kExprI64LoadMem32U>, //
                                                                        //
        &BodyGen::memop<kExprI64AtomicLoad>, //
        &BodyGen::memop<kExprI64AtomicLoad8U>, //
        &BodyGen::memop<kExprI64AtomicLoad16U>, //
        &BodyGen::memop<kExprI64AtomicLoad32U>, //
        &BodyGen::memop<kExprI64AtomicAdd, kI64>, //
        &BodyGen::memop<kExprI64AtomicSub, kI64>, //
        &BodyGen::memop<kExprI64AtomicAnd, kI64>, //
        &BodyGen::memop<kExprI64AtomicOr, kI64>, //
        &BodyGen::memop<kExprI64AtomicXor, kI64>, //
        &BodyGen::memop<kExprI64AtomicExchange, kI64>, //
        &BodyGen::memop<kExprI64AtomicCompareExchange, kI64, kI64>, //
        &BodyGen::memop<kExprI64AtomicAdd8U, kI64>, //
        &BodyGen::memop<kExprI64AtomicSub8U, kI64>, //
        &BodyGen::memop<kExprI64AtomicAnd8U, kI64>, //
        &BodyGen::memop<kExprI64AtomicOr8U, kI64>, //
        &BodyGen::memop<kExprI64AtomicXor8U, kI64>, //
        &BodyGen::memop<kExprI64AtomicExchange8U, kI64>, //
        &BodyGen::memop<kExprI64AtomicCompareExchange8U, kI64, kI64>, //
        &BodyGen::memop<kExprI64AtomicAdd16U, kI64>, //
        &BodyGen::memop<kExprI64AtomicSub16U, kI64>, //
        &BodyGen::memop<kExprI64AtomicAnd16U, kI64>, //
        &BodyGen::memop<kExprI64AtomicOr16U, kI64>, //
        &BodyGen::memop<kExprI64AtomicXor16U, kI64>, //
        &BodyGen::memop<kExprI64AtomicExchange16U, kI64>, //
        &BodyGen::memop<kExprI64AtomicCompareExchange16U, kI64, kI64>, //
        &BodyGen::memop<kExprI64AtomicAdd32U, kI64>, //
        &BodyGen::memop<kExprI64AtomicSub32U, kI64>, //
        &BodyGen::memop<kExprI64AtomicAnd32U, kI64>, //
        &BodyGen::memop<kExprI64AtomicOr32U, kI64>, //
        &BodyGen::memop<kExprI64AtomicXor32U, kI64>, //
        &BodyGen::memop<kExprI64AtomicExchange32U, kI64>, //
        &BodyGen::memop<kExprI64AtomicCompareExchange32U, kI64, kI64>, //
        &BodyGen::get_local<kI64>, //
        &BodyGen::tee_local<kI64>, //
        &BodyGen::get_global<kI64>, //
        &BodyGen::op<kExprSelect, kI64, kI64, kI32>, //
        &BodyGen::select_with_type<kI64>, //
        &BodyGen::call<kI64>, //
        &BodyGen::call_indirect<kI64>, //
        &BodyGen::call_ref<kI64>, //
        &BodyGen::try_block<kI64>);
    static constexpr auto kSimdAlternatives =
        CreateArray(&BodyGen::simd_lane_op<kExprI64x2ExtractLane, 2, kS128>);
    static constexpr auto kWasmGCAlternatives =
        CreateArray(&BodyGen::struct_get<kI64>, //
                    &BodyGen::array_get<kI64>);
    static constexpr GeneratorAlternativesPerOption kAlternativesPerOptions{
        kMvpAlternatives, kSimdAlternatives, kWasmGCAlternatives};
    GenerateOneOf(kAlternativesPerOptions, data);
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateArray(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::getPseudoRandom(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::size().
GenerateOneOf() [1/3]
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateOneOf (const Arr & alternatives, DataRange * data) [inline], [private]
Definition at line 2303 of file random-module-generation.cc.
                                                               {
    DCHECK_LT(alternatives.size(), std::numeric_limits<uint8_t>::max());
    const auto which = data->get<uint8_t>();
    GenerateFn alternate = alternatives[which % alternatives.size()];
    (this->*alternate)(data);
  }
References DCHECK_LT, and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get().
GenerateOneOf() [2/3]
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateOneOf (const Arr & alternatives, HeapType type, DataRange * data, Nullability nullability) [inline], [private]
Definition at line 2326 of file random-module-generation.cc.
                                              {
    DCHECK_LT(alternatives.size(), std::numeric_limits<uint8_t>::max());
    size_t index = data->get<uint8_t>() % (alternatives.size() + 1);
    if (nullability && index == alternatives.size()) {
      ref_null(type, data);
      return true;
    }
    for (size_t i = index; i < alternatives.size(); i++) {
      if ((this->*alternatives[i])(type, data, nullability)) {
        return true;
      }
    }
    for (size_t i = 0; i < index; i++) {
      if ((this->*alternatives[i])(type, data, nullability)) {
        return true;
      }
    }
    if (nullability == kNullable) {
      ref_null(type, data);
      return true;
    }
    return false;
  }
References DCHECK_LT, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::index, v8::internal::wasm::kNullable, and v8::internal::tracing::type.
GenerateOneOf() [3/3]
template<size_t... kAlternativesSizes>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateOneOf (const GeneratorAlternativesPerOption< kAlternativesSizes... > & alternatives_per_option, DataRange * data) [inline], [private]
Definition at line 2312 of file random-module-generation.cc.
                                      {
    return GenerateOneOf(alternatives_per_option.GetAlternatives(options_),
                         data);
  }
GenerateRef() [1/2]
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateRef (DataRange * data) [inline]
Definition at line 3507 of file random-module-generation.cc.
                                    {
    constexpr HeapType top_types[] = {
        kWasmAnyRef,
        kWasmFuncRef,
        kWasmExternRef,
    };
    HeapType type = top_types[data->get<uint8_t>() % arraysize(top_types)];
    GenerateRef(type, data);
  }
References arraysize, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::kWasmAnyRef, v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmFuncRef, and v8::internal::tracing::type.
GenerateRef() [2/2]
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateRef (HeapType type, DataRange * data, Nullability nullability = kNullable) [inline]
Try generating one of the alternatives
Definition at line 3269 of file random-module-generation.cc.
                                                        {
    std::optional<GeneratorRecursionScope> rec_scope;
    if (nullability) {
      rec_scope.emplace(this);
    }
    if (recursion_limit_reached() || data->size() == 0) {
      if (nullability == kNullable) {
        ref_null(type, data);
        return;
      }
      // It is ok not to return here because the non-nullable types are not
      // recursive by construction, so the depth is limited already.
    }
    constexpr auto alternatives_indexed_type =
        CreateArray(&BodyGen::new_object, //
                    &BodyGen::get_local_ref, //
                    &BodyGen::array_get_ref, //
                    &BodyGen::struct_get_ref, //
                    &BodyGen::ref_cast, //
                    &BodyGen::ref_as_non_null, //
                    &BodyGen::br_on_cast); //
    constexpr auto alternatives_func_any =
        CreateArray(&BodyGen::table_get, //
                    &BodyGen::get_local_ref, //
                    &BodyGen::array_get_ref, //
                    &BodyGen::struct_get_ref, //
                    &BodyGen::ref_cast, //
                    &BodyGen::any_convert_extern, //
                    &BodyGen::ref_as_non_null, //
                    &BodyGen::br_on_cast); //
    constexpr auto alternatives_other =
        CreateArray(&BodyGen::array_get_ref, //
                    &BodyGen::get_local_ref, //
                    &BodyGen::struct_get_ref, //
                    &BodyGen::ref_cast, //
                    &BodyGen::ref_as_non_null, //
                    &BodyGen::br_on_cast); //
    switch (type.representation()) {
      // For abstract types, sometimes generate one of their subtypes.
      case HeapType::kAny: {
        // Weighted according to the types in the module:
        // If there are D data types and F function types, the relative
        // frequencies for dataref is D, for funcref F, and for i31ref and
        // falling back to anyref 2.
        const uint8_t num_data_types =
            static_cast<uint8_t>(structs_.size() + arrays_.size());
        const uint8_t emit_i31ref = 2;
        const uint8_t fallback_to_anyref = 2;
        uint8_t random = data->get<uint8_t>() %
                         (num_data_types + emit_i31ref + fallback_to_anyref);
        // We have to compute this first so in case GenerateOneOf fails
        // we will continue to fall back on an alternative that is guaranteed
        // to generate a value of the wanted type.
        // In order to know which alternative to fall back to in case
        // GenerateOneOf failed, the random variable is recomputed.
        if (random >= num_data_types + emit_i31ref) {
          if (GenerateOneOf(alternatives_func_any, type, data, nullability)) {
            return;
          }
          random = data->get<uint8_t>() % (num_data_types + emit_i31ref);
        }
        if (random < structs_.size()) {
          GenerateRef(kWasmStructRef, data, nullability);
        } else if (random < num_data_types) {
          GenerateRef(kWasmArrayRef, data, nullability);
        } else {
          GenerateRef(kWasmI31Ref, data, nullability);
        }
        return;
      }
      case HeapType::kArray: {
        constexpr uint8_t fallback_to_dataref = 1;
        uint8_t random =
            data->get<uint8_t>() % (arrays_.size() + fallback_to_dataref);
        // Try generating one of the alternatives and continue to the rest of
        // the methods in case it fails.
        if (random >= arrays_.size()) {
          if (GenerateOneOf(alternatives_other, type, data, nullability))
            return;
          random = data->get<uint8_t>() % arrays_.size();
        }
        ModuleTypeIndex index = arrays_[random];
        DCHECK(builder_->builder()->IsArrayType(index));
        GenerateRef(HeapType::Index(index, kNotShared, RefTypeKind::kArray),
                    data, nullability);
        return;
      }
      case HeapType::kStruct: {
        constexpr uint8_t fallback_to_dataref = 2;
        uint8_t random =
            data->get<uint8_t>() % (structs_.size() + fallback_to_dataref);
        // Try generating one of the alternatives
        // and continue to the rest of the methods in case it fails.
        if (random >= structs_.size()) {
          if (GenerateOneOf(alternatives_other, type, data, nullability)) {
            return;
          }
          random = data->get<uint8_t>() % structs_.size();
        }
        ModuleTypeIndex index = structs_[random];
        DCHECK(builder_->builder()->IsStructType(index));
        GenerateRef(HeapType::Index(index, kNotShared, RefTypeKind::kStruct),
                    data, nullability);
        return;
      }
      case HeapType::kEq: {
        const uint8_t num_types = arrays_.size() + structs_.size();
        const uint8_t emit_i31ref = 2;
        constexpr uint8_t fallback_to_eqref = 1;
        uint8_t random = data->get<uint8_t>() %
                         (num_types + emit_i31ref + fallback_to_eqref);
        // Try generating one of the alternatives
        // and continue to the rest of the methods in case it fails.
        if (random >= num_types + emit_i31ref) {
          if (GenerateOneOf(alternatives_other, type, data, nullability)) {
            return;
          }
          random = data->get<uint8_t>() % (num_types + emit_i31ref);
        }
        if (random < num_types) {
          // Using `HeapType(random)` here relies on the assumption that struct
          // and array types come before signatures.
          RefTypeKind kind = RefTypeKind::kOther;
          if (builder_->builder()->IsArrayType(random)) {
            kind = RefTypeKind::kArray;
          } else if (builder_->builder()->IsStructType(random)) {
            kind = RefTypeKind::kStruct;
          } else {
            UNREACHABLE();
          }
          GenerateRef(
              HeapType::Index(ModuleTypeIndex{random}, kNotShared, kind), data,
              nullability);
        } else {
          GenerateRef(kWasmI31Ref, data, nullability);
        }
        return;
      }
      case HeapType::kFunc: {
        uint32_t random = data->get<uint8_t>() % (functions_.size() + 1);
        /// Try generating one of the alternatives
        // and continue to the rest of the methods in case it fails.
        if (random >= functions_.size()) {
          if (GenerateOneOf(alternatives_func_any, type, data, nullability)) {
            return;
          }
          random = data->get<uint8_t>() % functions_.size();
        }
        ModuleTypeIndex signature_index = functions_[random];
        DCHECK(builder_->builder()->IsSignature(signature_index));
        GenerateRef(HeapType::Index(signature_index, kNotShared,
                                    RefTypeKind::kFunction),
                    data, nullability);
        return;
      }
      case HeapType::kI31: {
        // Try generating one of the alternatives
        // and continue to the rest of the methods in case it fails.
        if (data->get<bool>() &&
            GenerateOneOf(alternatives_other, type, data, nullability)) {
          return;
        }
        Generate(kWasmI32, data);
        builder_->EmitWithPrefix(kExprRefI31);
        return;
      }
      case HeapType::kExn: {
        // TODO(manoskouk): Can we somehow come up with a nontrivial exnref?
        ref_null(type, data);
        if (nullability == kNonNullable) {
          builder_->Emit(kExprRefAsNonNull);
        }
        return;
      }
      case HeapType::kExtern: {
        uint8_t choice = data->get<uint8_t>();
        if (choice < 25) {
          // ~10% chance of extern.convert_any.
          GenerateRef(kWasmAnyRef, data);
          builder_->EmitWithPrefix(kExprExternConvertAny);
          if (nullability == kNonNullable) {
            builder_->Emit(kExprRefAsNonNull);
          }
          return;
        }
        // ~80% chance of string.
        if (choice < 230 && options_.generate_wasm_gc()) {
          uint8_t subchoice = choice % 7;
          switch (subchoice) {
            case 0:
              return string_cast(data);
            case 1:
              return string_fromcharcode(data);
            case 2:
              return string_fromcodepoint(data);
            case 3:
              return string_concat(data);
            case 4:
              return string_substring(data);
            case 5:
              return string_fromcharcodearray(data);
            case 6:
              return string_fromutf8array(data);
          }
        }
        // ~10% chance of fallthrough.
        [[fallthrough]];
      }
      case HeapType::kNoExtern:
      case HeapType::kNoFunc:
      case HeapType::kNone:
      case HeapType::kNoExn:
        ref_null(type, data);
        if (nullability == kNonNullable) {
          builder_->Emit(kExprRefAsNonNull);
        }
        return;
      default:
        // Indexed type (i.e. user-defined type).
        DCHECK(type.is_index());
        if (options_.generate_wasm_gc() &&
            type.ref_index() == string_imports_.array_i8 &&
            data->get<uint8_t>() < 32) {
          // 1/8th chance, fits the number of remaining alternatives (7) well.
          return string_toutf8array(data);
        }
        GenerateOneOf(alternatives_indexed_type, type, data, nullability);
        return;
    }
    UNREACHABLE();
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateArray(), v8::internal::DCHECK(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::index, v8::internal::wasm::HeapType::Index(), v8::internal::wasm::HeapType::kAny, v8::internal::wasm::kArray, v8::internal::wasm::HeapType::kArray, v8::internal::wasm::HeapType::kEq, v8::internal::wasm::HeapType::kExn, v8::internal::wasm::HeapType::kExtern, v8::internal::wasm::HeapType::kFunc, v8::internal::wasm::kFunction, v8::internal::wasm::HeapType::kI31, v8::internal::wasm::HeapType::kNoExn, v8::internal::wasm::HeapType::kNoExtern, v8::internal::wasm::HeapType::kNoFunc, v8::internal::wasm::HeapType::kNone, v8::internal::wasm::kNonNullable, v8::internal::kNotShared, v8::internal::wasm::kNullable, v8::internal::wasm::kOther, v8::internal::wasm::kStruct, v8::internal::wasm::HeapType::kStruct, v8::internal::wasm::kWasmAnyRef, v8::internal::wasm::kWasmArrayRef, v8::internal::wasm::kWasmI31Ref, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmStructRef, random(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::size(), v8::internal::tracing::type, and v8::internal::UNREACHABLE().
GenerateS128()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateS128 (DataRange * data) [inline]
Definition at line 2947 of file random-module-generation.cc.
                                     {
    CHECK(options_.generate_simd());
    GeneratorRecursionScope rec_scope(this);
    if (recursion_limit_reached() || data->size() <= sizeof(int32_t)) {
      // TODO(v8:8460): v128.const is not implemented yet, and we need a way to
      // "bottom-out", so use a splat to generate this.
      builder_->EmitI32Const(0);
      builder_->EmitWithPrefix(kExprI8x16Splat);
      return;
    }
    constexpr auto alternatives = CreateArray(
        &BodyGen::simd_const,
        &BodyGen::simd_lane_op<kExprI8x16ReplaceLane, 16, kS128, kI32>,
        &BodyGen::simd_lane_op<kExprI16x8ReplaceLane, 8, kS128, kI32>,
        &BodyGen::simd_lane_op<kExprI32x4ReplaceLane, 4, kS128, kI32>,
        &BodyGen::simd_lane_op<kExprI64x2ReplaceLane, 2, kS128, kI64>,
        &BodyGen::simd_lane_op<kExprF32x4ReplaceLane, 4, kS128, kF32>,
        &BodyGen::simd_lane_op<kExprF64x2ReplaceLane, 2, kS128, kF64>,
        &BodyGen::op_with_prefix<kExprI8x16Splat, kI32>,
        &BodyGen::op_with_prefix<kExprI8x16Eq, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16Ne, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16LtS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16LtU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16GtS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16GtU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16LeS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16LeU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16GeS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16GeU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16Abs, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16Neg, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16Shl, kS128, kI32>,
        &BodyGen::op_with_prefix<kExprI8x16ShrS, kS128, kI32>,
        &BodyGen::op_with_prefix<kExprI8x16ShrU, kS128, kI32>,
        &BodyGen::op_with_prefix<kExprI8x16Add, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16AddSatS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16AddSatU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16Sub, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16SubSatS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16SubSatU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16MinS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16MinU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16MaxS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16MaxU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16RoundingAverageU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16Popcnt, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8Splat, kI32>,
        &BodyGen::op_with_prefix<kExprI16x8Eq, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8Ne, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8LtS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8LtU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8GtS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8GtU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8LeS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8LeU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8GeS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8GeU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8Abs, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8Neg, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8Shl, kS128, kI32>,
        &BodyGen::op_with_prefix<kExprI16x8ShrS, kS128, kI32>,
        &BodyGen::op_with_prefix<kExprI16x8ShrU, kS128, kI32>,
        &BodyGen::op_with_prefix<kExprI16x8Add, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8AddSatS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8AddSatU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8Sub, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8SubSatS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8SubSatU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8Mul, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8MinS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8MinU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8MaxS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8MaxU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8RoundingAverageU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8ExtMulLowI8x16S, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8ExtMulLowI8x16U, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8ExtMulHighI8x16S, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8ExtMulHighI8x16U, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8Q15MulRSatS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8ExtAddPairwiseI8x16S, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8ExtAddPairwiseI8x16U, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4Splat, kI32>,
        &BodyGen::op_with_prefix<kExprI32x4Eq, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4Ne, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4LtS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4LtU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4GtS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4GtU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4LeS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4LeU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4GeS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4GeU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4Abs, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4Neg, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4Shl, kS128, kI32>,
        &BodyGen::op_with_prefix<kExprI32x4ShrS, kS128, kI32>,
        &BodyGen::op_with_prefix<kExprI32x4ShrU, kS128, kI32>,
        &BodyGen::op_with_prefix<kExprI32x4Add, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4Sub, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4Mul, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4MinS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4MinU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4MaxS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4MaxU, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4DotI16x8S, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4ExtMulLowI16x8S, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4ExtMulLowI16x8U, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4ExtMulHighI16x8S, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4ExtMulHighI16x8U, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4ExtAddPairwiseI16x8S, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4ExtAddPairwiseI16x8U, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2Splat, kI64>,
        &BodyGen::op_with_prefix<kExprI64x2Eq, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2Ne, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2LtS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2GtS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2LeS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2GeS, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2Abs, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2Neg, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2Shl, kS128, kI32>,
        &BodyGen::op_with_prefix<kExprI64x2ShrS, kS128, kI32>,
        &BodyGen::op_with_prefix<kExprI64x2ShrU, kS128, kI32>,
        &BodyGen::op_with_prefix<kExprI64x2Add, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2Sub, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2Mul, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2ExtMulLowI32x4S, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2ExtMulLowI32x4U, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2ExtMulHighI32x4S, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2ExtMulHighI32x4U, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Splat, kF32>,
        &BodyGen::op_with_prefix<kExprF32x4Eq, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Ne, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Lt, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Gt, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Le, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Ge, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Abs, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Neg, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Sqrt, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Add, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Sub, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Mul, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Div, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Min, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Max, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Pmin, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Pmax, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Ceil, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Floor, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Trunc, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4NearestInt, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Splat, kF64>,
        &BodyGen::op_with_prefix<kExprF64x2Eq, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Ne, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Lt, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Gt, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Le, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Ge, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Abs, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Neg, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Sqrt, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Add, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Sub, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Mul, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Div, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Min, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Max, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Pmin, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Pmax, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Ceil, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Floor, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Trunc, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2NearestInt, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2PromoteLowF32x4, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2ConvertLowI32x4S, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2ConvertLowI32x4U, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4DemoteF64x2Zero, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4TruncSatF64x2SZero, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4TruncSatF64x2UZero, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2SConvertI32x4Low, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2SConvertI32x4High, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2UConvertI32x4Low, kS128>,
        &BodyGen::op_with_prefix<kExprI64x2UConvertI32x4High, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4SConvertF32x4, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4UConvertF32x4, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4SConvertI32x4, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4UConvertI32x4, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16SConvertI16x8, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16UConvertI16x8, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8SConvertI32x4, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8UConvertI32x4, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8SConvertI8x16Low, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8SConvertI8x16High, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8UConvertI8x16Low, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8UConvertI8x16High, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4SConvertI16x8Low, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4SConvertI16x8High, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4UConvertI16x8Low, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4UConvertI16x8High, kS128>,
        &BodyGen::op_with_prefix<kExprS128Not, kS128>,
        &BodyGen::op_with_prefix<kExprS128And, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprS128AndNot, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprS128Or, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprS128Xor, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprS128Select, kS128, kS128, kS128>,
        &BodyGen::simd_shuffle,
        &BodyGen::op_with_prefix<kExprI8x16Swizzle, kS128, kS128>,
        &BodyGen::memop<kExprS128LoadMem>, //
        &BodyGen::memop<kExprS128Load8x8S>, //
        &BodyGen::memop<kExprS128Load8x8U>, //
        &BodyGen::memop<kExprS128Load16x4S>, //
        &BodyGen::memop<kExprS128Load16x4U>, //
        &BodyGen::memop<kExprS128Load32x2S>, //
        &BodyGen::memop<kExprS128Load32x2U>, //
        &BodyGen::memop<kExprS128Load8Splat>, //
        &BodyGen::memop<kExprS128Load16Splat>, //
        &BodyGen::memop<kExprS128Load32Splat>, //
        &BodyGen::memop<kExprS128Load64Splat>, //
        &BodyGen::memop<kExprS128Load32Zero>, //
        &BodyGen::memop<kExprS128Load64Zero>, //
        &BodyGen::simd_lane_memop<kExprS128Load8Lane, 16, kS128>, //
        &BodyGen::simd_lane_memop<kExprS128Load16Lane, 8, kS128>, //
        &BodyGen::simd_lane_memop<kExprS128Load32Lane, 4, kS128>, //
        &BodyGen::simd_lane_memop<kExprS128Load64Lane, 2, kS128>, //
        &BodyGen::op_with_prefix<kExprI8x16RelaxedSwizzle, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI8x16RelaxedLaneSelect, kS128, kS128,
                                 kS128>,
        &BodyGen::op_with_prefix<kExprI16x8RelaxedLaneSelect, kS128, kS128,
                                 kS128>,
        &BodyGen::op_with_prefix<kExprI32x4RelaxedLaneSelect, kS128, kS128,
                                 kS128>,
        &BodyGen::op_with_prefix<kExprI64x2RelaxedLaneSelect, kS128, kS128,
                                 kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Qfma, kS128, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4Qfms, kS128, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Qfma, kS128, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2Qfms, kS128, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4RelaxedMin, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF32x4RelaxedMax, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2RelaxedMin, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprF64x2RelaxedMax, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4RelaxedTruncF32x4S, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4RelaxedTruncF32x4U, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4RelaxedTruncF64x2SZero, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4RelaxedTruncF64x2UZero, kS128>,
        &BodyGen::op_with_prefix<kExprI16x8DotI8x16I7x16S, kS128, kS128>,
        &BodyGen::op_with_prefix<kExprI32x4DotI8x16I7x16AddS, kS128, kS128,
                                 kS128>);
    GenerateOneOf(alternatives, data);
  }
References CHECK, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateArray(), v8::internal::kS128, and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::size().
GenerateTypes()
std::vector<ValueType> v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateTypes (DataRange * data) [inline]
Definition at line 3517 of file random-module-generation.cc.
                                                      {
    return fuzzing::GenerateTypes(
        options_, data,
        static_cast<uint32_t>(functions_.size() + structs_.size() +
                              arrays_.size()));
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateTypes().
GenerateVoid()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateVoid (DataRange * data) [inline]
Definition at line 2424 of file random-module-generation.cc.
                                     {
    GeneratorRecursionScope rec_scope(this);
    if (recursion_limit_reached() || data->size() == 0) return;
    static constexpr auto kMvpAlternatives =
        CreateArray(&BodyGen::sequence<kVoid, kVoid>,
                    &BodyGen::sequence<kVoid, kVoid, kVoid, kVoid>,
                    &BodyGen::sequence<kVoid, kVoid, kVoid, kVoid, kVoid, kVoid,
                                       kVoid, kVoid>,
                    &BodyGen::block<kVoid>, //
                    &BodyGen::loop<kVoid>, //
                    &BodyGen::finite_loop<kVoid>, //
                    &BodyGen::if_<kVoid, kIf>, //
                    &BodyGen::if_<kVoid, kIfElse>, //
                    &BodyGen::br, //
                    &BodyGen::br_if<kVoid>, //
                    &BodyGen::br_on_null<kVoid>, //
                    &BodyGen::br_on_non_null<kVoid>, //
                    &BodyGen::br_table<kVoid>, //
                    &BodyGen::try_table_block<kVoid>, //
                    &BodyGen::return_op, //
                    &BodyGen::memop<kExprI32StoreMem, kI32>,
                    &BodyGen::memop<kExprI32StoreMem8, kI32>,
                    &BodyGen::memop<kExprI32StoreMem16, kI32>,
                    &BodyGen::memop<kExprI64StoreMem, kI64>,
                    &BodyGen::memop<kExprI64StoreMem8, kI64>,
                    &BodyGen::memop<kExprI64StoreMem16, kI64>,
                    &BodyGen::memop<kExprI64StoreMem32, kI64>,
                    &BodyGen::memop<kExprF32StoreMem, kF32>,
                    &BodyGen::memop<kExprF64StoreMem, kF64>,
                    &BodyGen::memop<kExprI32AtomicStore, kI32>,
                    &BodyGen::memop<kExprI32AtomicStore8U, kI32>,
                    &BodyGen::memop<kExprI32AtomicStore16U, kI32>,
                    &BodyGen::memop<kExprI64AtomicStore, kI64>,
                    &BodyGen::memop<kExprI64AtomicStore8U, kI64>,
                    &BodyGen::memop<kExprI64AtomicStore16U, kI64>,
                    &BodyGen::memop<kExprI64AtomicStore32U, kI64>,
                    &BodyGen::drop,
                    &BodyGen::call<kVoid>, //
                    &BodyGen::call_indirect<kVoid>, //
                    &BodyGen::call_ref<kVoid>, //
                    &BodyGen::set_local, //
                    &BodyGen::set_global, //
                    &BodyGen::throw_or_rethrow, //
                    &BodyGen::try_block<kVoid>, //
                    &BodyGen::shift_locals, //
                    &BodyGen::table_set, //
                    &BodyGen::table_fill, //
                    &BodyGen::table_copy);
    static constexpr auto kSimdAlternatives =
        CreateArray(&BodyGen::memop<kExprS128StoreMem, kS128>,
                    &BodyGen::simd_lane_memop<kExprS128Store8Lane, 16, kS128>,
                    &BodyGen::simd_lane_memop<kExprS128Store16Lane, 8, kS128>,
                    &BodyGen::simd_lane_memop<kExprS128Store32Lane, 4, kS128>,
                    &BodyGen::simd_lane_memop<kExprS128Store64Lane, 2, kS128>);
    static constexpr auto kWasmGCAlternatives =
        CreateArray(&BodyGen::struct_set, //
                    &BodyGen::array_set, //
                    &BodyGen::array_copy, //
                    &BodyGen::array_fill, //
                    &BodyGen::array_init_data, //
                    &BodyGen::array_init_elem);
    static constexpr GeneratorAlternativesPerOption kAlternativesPerOptions{
        kMvpAlternatives, kSimdAlternatives, kWasmGCAlternatives};
    GenerateOneOf(kAlternativesPerOptions, data);
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateArray(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::size().
get_global()
template<ValueKind wanted_kind>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::get_global (DataRange * data) [inline], [private]
Definition at line 1340 of file random-module-generation.cc.
                                   {
    static_assert(wanted_kind != kVoid, "illegal type");
    global_op<wanted_kind>(data);
  }
get_local()
template<ValueKind wanted_kind>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::get_local (DataRange * data) [inline], [private]
Definition at line 1248 of file random-module-generation.cc.
                                  {
    static_assert(wanted_kind != kVoid, "illegal type");
    local_op<wanted_kind>(data, kExprLocalGet);
  }
get_local_ref()
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::get_local_ref (HeapType type, DataRange * data, Nullability nullable) [inline], [private]
Definition at line 1410 of file random-module-generation.cc.
                                                                           {
    Var local = GetRandomLocal(data, ValueType::RefMaybeNull(type, nullable));
    if (local.is_valid() && (local.type.is_nullable() || locals_initialized_)) {
      // With a small chance don't only get the local but first "shift" local
      // values around. This creates more interesting patterns for the typed
      // optimizations.
      if (data->get<uint8_t>() % 8 == 1) {
        shift_locals_to(data, local);
      }
      builder_->EmitWithU32V(kExprLocalGet, local.index);
      return true;
    }
    return false;
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Var::index, v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Var::is_valid(), v8::internal::wasm::ValueType::RefMaybeNull(), v8::internal::tracing::type, and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Var::type.
GetRandomGlobal()
Var v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GetRandomGlobal (DataRange * data, bool ensure_mutable) [inline], [private]
Definition at line 1306 of file random-module-generation.cc.
                                                            {
    uint32_t index;
    if (ensure_mutable) {
      if (mutable_globals_.empty()) return {};
      index = mutable_globals_[data->get<uint8_t>() % mutable_globals_.size()];
    } else {
      if (globals_.empty()) return {};
      index = data->get<uint8_t>() % globals_.size();
    }
    ValueType type = globals_[index];
    return {index, type};
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::index, and v8::internal::tracing::type.
GetRandomLocal()
Var v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GetRandomLocal (DataRange * data, ValueType type = kWasmTop) [inline], [private]
Definition at line 1210 of file random-module-generation.cc.
                                                                 {
    const size_t locals_count = all_locals_count();
    if (locals_count == 0) return {};
    uint32_t start_index = data->get<uint8_t>() % locals_count;
    uint32_t index = start_index;
    // TODO(14034): Ideally we would check for subtyping here over type
    // equality, but we don't have a module.
    while (type != kWasmTop && local_type(index) != type &&
           AsNullable(local_type(index)) != type) {
      index = (index + 1) % locals_count;
      if (index == start_index) return {};
    }
    return {index, local_type(index)};
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::index, v8::internal::wasm::kWasmTop, and v8::internal::tracing::type.
global_op()
template<ValueKind wanted_kind>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::global_op (DataRange * data) [inline], [private]
Definition at line 1320 of file random-module-generation.cc.
                                  {
    static_assert(wanted_kind == kVoid || is_convertible_kind(wanted_kind));
    constexpr bool is_set = wanted_kind == kVoid;
    Var global = GetRandomGlobal(data, is_set);
    // If there are no globals, just generate any value (if a value is needed),
    // or do nothing.
    if (!global.is_valid() || !is_convertible_kind(global.type.kind())) {
      if (wanted_kind == kVoid) return;
      return Generate<wanted_kind>(data);
    }
    if (is_set) Generate(global.type, data);
    builder_->EmitWithU32V(is_set ? kExprGlobalSet : kExprGlobalGet,
                           global.index);
    if (!is_set && global.type.kind() != wanted_kind) {
      Convert(global.type, ValueType::Primitive(wanted_kind));
    }
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Var::index, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Var::is_valid(), v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::ValueType::Primitive(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Var::type.
grow_memory()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::grow_memory (DataRange * data) [inline], [private]
Definition at line 1390 of file random-module-generation.cc.
                                    {
    uint8_t memory_index =
        data->get<uint8_t>() % builder_->builder()->NumMemories();
    // Generate the index and the arguments, if any.
    builder_->builder()->IsMemory64(memory_index) ? Generate<kI64>(data)
                                                  : Generate<kI32>(data);
    builder_->EmitWithU8(kExprMemoryGrow, memory_index);
    // The `grow_memory` returns an I32. However, `kExprMemoryGrow` for memory64
    // returns an I64, so we should convert it.
    if (builder_->builder()->IsMemory64(memory_index)) {
      builder_->Emit(kExprI32ConvertI64);
    }
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get().
i31_get()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::i31_get (DataRange * data) [inline], [private]
Definition at line 1711 of file random-module-generation.cc.
                                {
    GenerateRef(kWasmI31Ref, data);
    if (data->get<bool>()) {
      builder_->EmitWithPrefix(kExprI31GetS);
    } else {
      builder_->EmitWithPrefix(kExprI31GetU);
    }
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), and v8::internal::wasm::kWasmI31Ref.
i32_const()
template<size_t num_bytes>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::i32_const (DataRange * data) [inline], [private]
Definition at line 1297 of file random-module-generation.cc.
                                  {
    builder_->EmitI32Const(data->getPseudoRandom<int32_t, num_bytes>());
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::getPseudoRandom().
i64_const()
template<size_t num_bytes>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::i64_const (DataRange * data) [inline], [private]
Definition at line 1302 of file random-module-generation.cc.
                                  {
    builder_->EmitI64Const(data->getPseudoRandom<int64_t, num_bytes>());
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::getPseudoRandom().
if_() [1/2]
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::if_ (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, IfType type, DataRange * data) [inline], [private]
Definition at line 552 of file random-module-generation.cc.
                            {
    // One-armed "if" are only valid if the input and output types are the same.
    DCHECK_IMPLIES(type == kIf, param_types == return_types);
    Generate(kWasmI32, data);
    BlockScope block_scope(this, kExprIf, param_types, return_types,
                           return_types);
    ConsumeAndGenerate(param_types, return_types, data);
    if (type == kIfElse) {
      builder_->Emit(kExprElse);
      ConsumeAndGenerate(param_types, return_types, data);
    }
  }
References DCHECK_IMPLIES, v8::internal::wasm::kWasmI32, and v8::internal::tracing::type.
if_() [2/2]
template<ValueKind T, IfType type>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::if_ (DataRange * data) [inline], [private]
Definition at line 568 of file random-module-generation.cc.
                            {
    static_assert(T == kVoid || type == kIfElse,
                  "if without else cannot produce a value");
    if_({},
        T == kVoid ? base::Vector<ValueType>{}
                   : base::VectorOf({ValueType::Primitive(T)}),
        type, data);
  }
References v8::internal::wasm::ValueType::Primitive(), v8::internal::tracing::type, and v8::base::VectorOf().
InitializeNonDefaultableLocals()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::InitializeNonDefaultableLocals (DataRange * data) [inline]
Definition at line 3644 of file random-module-generation.cc.
                                                       {
    for (uint32_t i = 0; i < locals_.size(); i++) {
      if (!locals_[i].is_defaultable()) {
        GenerateRef(locals_[i].heap_type(), data, kNonNullable);
        builder_->EmitWithU32V(
            kExprLocalSet, i + static_cast<uint32_t>(
                                   builder_->signature()->parameter_count()));
      }
    }
    locals_initialized_ = true;
  }
References v8::internal::wasm::kNonNullable.
is_convertible_kind()
constexpr static bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::is_convertible_kind (ValueKind kind) [inline], [static], [constexpr], [private]
Definition at line 1225 of file random-module-generation.cc.
                                                            {
    return kind == kI32 || kind == kI64 || kind == kF32 || kind == kF64;
  }
References v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, and v8::internal::kI64.
local_op()
template<ValueKind wanted_kind>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::local_op (DataRange * data, WasmOpcode opcode) [inline], [private]
Definition at line 1230 of file random-module-generation.cc.
                                                    {
    static_assert(wanted_kind == kVoid || is_convertible_kind(wanted_kind));
    Var local = GetRandomLocal(data);
    // If there are no locals and no parameters, just generate any value (if a
    // value is needed), or do nothing.
    if (!local.is_valid() || !is_convertible_kind(local.type.kind())) {
      if (wanted_kind == kVoid) return;
      return Generate<wanted_kind>(data);
    }
    if (opcode != kExprLocalGet) Generate(local.type, data);
    builder_->EmitWithU32V(opcode, local.index);
    if (wanted_kind != kVoid && local.type.kind() != wanted_kind) {
      Convert(local.type, ValueType::Primitive(wanted_kind));
    }
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Var::index, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Var::is_valid(), v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::ValueType::Primitive(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Var::type.
local_type()
ValueType v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::local_type (uint32_t index) const [inline]
Definition at line 2409 of file random-module-generation.cc.
                                             {
    size_t num_params = builder_->signature()->parameter_count();
    return index < num_params ? builder_->signature()->GetParam(index)
                              : locals_[index - num_params];
  }
References v8::internal::index.
loop() [1/2]
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::loop (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, DataRange * data) [inline], [private]
Definition at line 482 of file random-module-generation.cc.
                                                                       {
    BlockScope block_scope(this, kExprLoop, param_types, return_types,
                           param_types);
    ConsumeAndGenerate(param_types, return_types, data);
  }
loop() [2/2]
template<ValueKind T>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::loop (DataRange * data) [inline], [private]
Definition at line 490 of file random-module-generation.cc.
                             {
    if constexpr (T == kVoid) {
      loop({}, {}, data);
    } else {
      loop({}, base::VectorOf({ValueType::Primitive(T)}), data);
    }
  }
References v8::internal::wasm::ValueType::Primitive(), and v8::base::VectorOf().
max_alignment()
constexpr static uint8_t v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::max_alignment (WasmOpcode memop) [inline], [static], [constexpr], [private]
Definition at line 873 of file random-module-generation.cc.
                                                           {
    switch (memop) {
      case kExprS128LoadMem:
      case kExprS128StoreMem:
        return 4;
      case kExprI64LoadMem:
      case kExprF64LoadMem:
      case kExprI64StoreMem:
      case kExprF64StoreMem:
      case kExprI64AtomicStore:
      case kExprI64AtomicLoad:
      case kExprI64AtomicAdd:
      case kExprI64AtomicSub:
      case kExprI64AtomicAnd:
      case kExprI64AtomicOr:
      case kExprI64AtomicXor:
      case kExprI64AtomicExchange:
      case kExprI64AtomicCompareExchange:
      case kExprS128Load8x8S:
      case kExprS128Load8x8U:
      case kExprS128Load16x4S:
      case kExprS128Load16x4U:
      case kExprS128Load32x2S:
      case kExprS128Load32x2U:
      case kExprS128Load64Splat:
      case kExprS128Load64Zero:
        return 3;
      case kExprI32LoadMem:
      case kExprI64LoadMem32S:
      case kExprI64LoadMem32U:
      case kExprF32LoadMem:
      case kExprI32StoreMem:
      case kExprI64StoreMem32:
      case kExprF32StoreMem:
      case kExprI32AtomicStore:
      case kExprI64AtomicStore32U:
      case kExprI32AtomicLoad:
      case kExprI64AtomicLoad32U:
      case kExprI32AtomicAdd:
      case kExprI32AtomicSub:
      case kExprI32AtomicAnd:
      case kExprI32AtomicOr:
      case kExprI32AtomicXor:
      case kExprI32AtomicExchange:
      case kExprI32AtomicCompareExchange:
      case kExprI64AtomicAdd32U:
      case kExprI64AtomicSub32U:
      case kExprI64AtomicAnd32U:
      case kExprI64AtomicOr32U:
      case kExprI64AtomicXor32U:
      case kExprI64AtomicExchange32U:
      case kExprI64AtomicCompareExchange32U:
      case kExprS128Load32Splat:
      case kExprS128Load32Zero:
        return 2;
      case kExprI32LoadMem16S:
      case kExprI32LoadMem16U:
      case kExprI64LoadMem16S:
      case kExprI64LoadMem16U:
      case kExprI32StoreMem16:
      case kExprI64StoreMem16:
      case kExprI32AtomicStore16U:
      case kExprI64AtomicStore16U:
      case kExprI32AtomicLoad16U:
      case kExprI64AtomicLoad16U:
      case kExprI32AtomicAdd16U:
      case kExprI32AtomicSub16U:
      case kExprI32AtomicAnd16U:
      case kExprI32AtomicOr16U:
      case kExprI32AtomicXor16U:
      case kExprI32AtomicExchange16U:
      case kExprI32AtomicCompareExchange16U:
      case kExprI64AtomicAdd16U:
      case kExprI64AtomicSub16U:
      case kExprI64AtomicAnd16U:
      case kExprI64AtomicOr16U:
      case kExprI64AtomicXor16U:
      case kExprI64AtomicExchange16U:
      case kExprI64AtomicCompareExchange16U:
      case kExprS128Load16Splat:
        return 1;
      case kExprI32LoadMem8S:
      case kExprI32LoadMem8U:
      case kExprI64LoadMem8S:
      case kExprI64LoadMem8U:
      case kExprI32StoreMem8:
      case kExprI64StoreMem8:
      case kExprI32AtomicStore8U:
      case kExprI64AtomicStore8U:
      case kExprI32AtomicLoad8U:
      case kExprI64AtomicLoad8U:
      case kExprI32AtomicAdd8U:
      case kExprI32AtomicSub8U:
      case kExprI32AtomicAnd8U:
      case kExprI32AtomicOr8U:
      case kExprI32AtomicXor8U:
      case kExprI32AtomicExchange8U:
      case kExprI32AtomicCompareExchange8U:
      case kExprI64AtomicAdd8U:
      case kExprI64AtomicSub8U:
      case kExprI64AtomicAnd8U:
      case kExprI64AtomicOr8U:
      case kExprI64AtomicXor8U:
      case kExprI64AtomicExchange8U:
      case kExprI64AtomicCompareExchange8U:
      case kExprS128Load8Splat:
        return 0;
      default:
        return 0;
    }
  }
memop()
template<WasmOpcode memory_op, ValueKind... arg_kinds>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::memop (DataRange * data) [inline], [private]
Definition at line 986 of file random-module-generation.cc.
                              {
    // Atomic operations need to be aligned exactly to their max alignment.
    const bool is_atomic = memory_op >> 8 == kAtomicPrefix;
    const uint8_t align = is_atomic ? max_alignment(memory_op)
                                    : data->getPseudoRandom<uint8_t>() %
                                          (max_alignment(memory_op) + 1);
    uint8_t memory_index =
        data->get<uint8_t>() % builder_->builder()->NumMemories();
    uint64_t offset = data->get<uint16_t>();
    // With a 1/256 chance generate potentially very large offsets.
    if ((offset & 0xff) == 0xff) {
      offset = builder_->builder()->IsMemory64(memory_index)
                   ? data->getPseudoRandom<uint64_t>() & 0x1ffffffff
                   : data->getPseudoRandom<uint32_t>();
    }
    // Generate the index and the arguments, if any.
    builder_->builder()->IsMemory64(memory_index)
        ? Generate<kI64, arg_kinds...>(data)
        : Generate<kI32, arg_kinds...>(data);
    // Format of the instruction (supports multi-memory):
    // memory_op (align | 0x40) memory_index offset
    if (WasmOpcodes::IsPrefixOpcode(static_cast<WasmOpcode>(memory_op >> 8))) {
      DCHECK(memory_op >> 8 == kAtomicPrefix || memory_op >> 8 == kSimdPrefix);
      builder_->EmitWithPrefix(memory_op);
    } else {
      builder_->Emit(memory_op);
    }
    builder_->EmitU32V(align | 0x40);
    builder_->EmitU32V(memory_index);
    builder_->EmitU64V(offset);
  }
References v8::internal::DCHECK(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::getPseudoRandom(), v8::internal::wasm::WasmOpcodes::IsPrefixOpcode(), and v8::internal::kI64.
memory_size()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::memory_size (DataRange * data) [inline], [private]
Definition at line 1378 of file random-module-generation.cc.
                                    {
    uint8_t memory_index =
        data->get<uint8_t>() % builder_->builder()->NumMemories();
    builder_->EmitWithU8(kExprMemorySize, memory_index);
    // The `memory_size` returns an I32. However, `kExprMemorySize` for memory64
    // returns an I64, so we should convert it.
    if (builder_->builder()->IsMemory64(memory_index)) {
      builder_->Emit(kExprI32ConvertI64);
    }
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get().
new_object()
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object (HeapType type, DataRange * data, Nullability nullable) [inline], [private]
Definition at line 1426 of file random-module-generation.cc.
                                                                        {
    DCHECK(type.is_index());
    ModuleTypeIndex index = type.ref_index();
    bool new_default = data->get<bool>();
    if (builder_->builder()->IsStructType(index)) {
      const StructType* struct_gen = builder_->builder()->GetStructType(index);
      int field_count = struct_gen->field_count();
      bool can_be_defaultable = std::all_of(
          struct_gen->fields().begin(), struct_gen->fields().end(),
          [](ValueType type) -> bool { return type.is_defaultable(); });
      if (new_default && can_be_defaultable) {
        builder_->EmitWithPrefix(kExprStructNewDefault);
        builder_->EmitU32V(index);
      } else {
        for (int i = 0; i < field_count; i++) {
          Generate(struct_gen->field(i).Unpacked(), data);
        }
        builder_->EmitWithPrefix(kExprStructNew);
        builder_->EmitU32V(index);
      }
    } else if (builder_->builder()->IsArrayType(index)) {
      ValueType element_type =
          builder_->builder()->GetArrayType(index)->element_type();
      bool can_be_defaultable = element_type.is_defaultable();
      WasmOpcode array_new_op[] = {
          kExprArrayNew, kExprArrayNewFixed,
          kExprArrayNewData, kExprArrayNewElem,
          kExprArrayNewDefault, // default op has to be at the end of the list.
      };
      size_t op_size = arraysize(array_new_op);
      if (!can_be_defaultable) --op_size;
      switch (array_new_op[data->get<uint8_t>() % op_size]) {
        case kExprArrayNewElem:
        case kExprArrayNewData: {
          // This is more restrictive than it has to be.
          // TODO(14034): Also support nonnullable and non-index reference
          // types.
          if (element_type.is_reference() && element_type.is_nullable() &&
              element_type.has_index()) {
            // Add a new element segment with the corresponding type.
            uint32_t element_segment = GenerateRefTypeElementSegment(
                data, builder_->builder(), element_type);
            // Generate offset, length.
            // TODO(14034): Change the distribution here to make it more likely
            // that the numbers are in range.
            Generate({kWasmI32, kWasmI32}, data);
            // Generate array.new_elem instruction.
            builder_->EmitWithPrefix(kExprArrayNewElem);
            builder_->EmitU32V(index);
            builder_->EmitU32V(element_segment);
            break;
          } else if (!element_type.is_reference()) {
            // Lazily create a data segment if the module doesn't have one yet.
            if (builder_->builder()->NumDataSegments() == 0) {
              GeneratePassiveDataSegment(data, builder_->builder());
            }
            int data_index =
                data->get<uint8_t>() % builder_->builder()->NumDataSegments();
            // Generate offset, length.
            Generate({kWasmI32, kWasmI32}, data);
            builder_->EmitWithPrefix(kExprArrayNewData);
            builder_->EmitU32V(index);
            builder_->EmitU32V(data_index);
            break;
          }
          [[fallthrough]]; // To array.new.
        }
        case kExprArrayNew:
          Generate(element_type.Unpacked(), data);
          Generate(kWasmI32, data);
          builder_->EmitI32Const(kMaxArraySize);
          builder_->Emit(kExprI32RemS);
          builder_->EmitWithPrefix(kExprArrayNew);
          builder_->EmitU32V(index);
          break;
        case kExprArrayNewFixed: {
          size_t element_count =
              std::min(static_cast<size_t>(data->get<uint8_t>()), data->size());
          for (size_t i = 0; i < element_count; ++i) {
            Generate(element_type.Unpacked(), data);
          }
          builder_->EmitWithPrefix(kExprArrayNewFixed);
          builder_->EmitU32V(index);
          builder_->EmitU32V(static_cast<uint32_t>(element_count));
          break;
        }
        case kExprArrayNewDefault:
          Generate(kWasmI32, data);
          builder_->EmitI32Const(kMaxArraySize);
          builder_->Emit(kExprI32RemS);
          builder_->EmitWithPrefix(kExprArrayNewDefault);
          builder_->EmitU32V(index);
          break;
        default:
          FATAL("Unimplemented opcode");
      }
    } else {
      CHECK(builder_->builder()->IsSignature(index));
      // Map the type index to a function index.
      // TODO(11954. 7748): Once we have type canonicalization, choose a random
      // function from among those matching the signature (consider function
      // subtyping?).
      uint32_t declared_func_index =
          index.index - static_cast<uint32_t>(arrays_.size() + structs_.size());
      size_t num_functions = builder_->builder()->NumDeclaredFunctions();
      const FunctionSig* sig = builder_->builder()->GetSignature(index);
      for (size_t i = 0; i < num_functions; ++i) {
        if (sig == builder_->builder()
                       ->GetFunction(declared_func_index)
                       ->signature()) {
          uint32_t absolute_func_index =
              NumImportedFunctions() + declared_func_index;
          builder_->EmitWithU32V(kExprRefFunc, absolute_func_index);
          return true;
        }
        declared_func_index = (declared_func_index + 1) % num_functions;
      }
      // We did not find a function matching the requested signature.
      builder_->EmitWithI32V(kExprRefNull, index.index);
      if (!nullable) {
        builder_->Emit(kExprRefAsNonNull);
      }
    }
    return true;
  }
References v8::base::all_of(), arraysize, CHECK, v8::internal::DCHECK(), FATAL, v8::internal::wasm::StructType::field(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::StructType::fields(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GeneratePassiveDataSegment(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateRefTypeElementSegment(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::wasm::ValueTypeBase::is_defaultable(), v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxArraySize, v8::internal::wasm::kWasmI32, v8::internal::sig, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::size(), v8::internal::tracing::type, and v8::internal::wasm::ValueType::Unpacked().
NumImportedFunctions()
int v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::NumImportedFunctions () [inline]
Definition at line 2399 of file random-module-generation.cc.
                             {
    return builder_->builder()->NumImportedFunctions();
  }
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues().
op()
template<WasmOpcode Op, ValueKind... Args>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::op (DataRange * data) [inline], [private]
Definition at line 414 of file random-module-generation.cc.
                           {
    Generate<Args...>(data);
    builder_->Emit(Op);
  }
op_with_prefix()
template<WasmOpcode Op, ValueKind... Args>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::op_with_prefix (DataRange * data) [inline], [private]
Definition at line 1023 of file random-module-generation.cc.
                                       {
    Generate<Args...>(data);
    builder_->EmitWithPrefix(Op);
  }
recursion_limit_reached()
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::recursion_limit_reached () [inline], [private]
Definition at line 3657 of file random-module-generation.cc.
                                 {
    return recursion_depth >= kMaxRecursionDepth;
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxRecursionDepth.
ref_as_non_null()
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ref_as_non_null (HeapType type, DataRange * data, Nullability nullable) [inline], [private]
Definition at line 2121 of file random-module-generation.cc.
                                                                             {
    GenerateRef(type, data, kNullable);
    builder_->Emit(kExprRefAsNonNull);
    return true;
  }
References v8::internal::wasm::kNullable, and v8::internal::tracing::type.
ref_cast()
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ref_cast (HeapType type, DataRange * data, Nullability nullable) [inline], [private]
Definition at line 1897 of file random-module-generation.cc.
                                                                      {
    HeapType input_type = top_type(type);
    GenerateRef(input_type, data);
    builder_->EmitWithPrefix(nullable ? kExprRefCastNull : kExprRefCast);
    builder_->EmitHeapType(type);
    return true; // It always produces the desired result type.
  }
References v8::internal::tracing::type.
ref_eq()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ref_eq (DataRange * data) [inline], [private]
Definition at line 2180 of file random-module-generation.cc.
                               {
    GenerateRef(kWasmEqRef, data);
    GenerateRef(kWasmEqRef, data);
    builder_->Emit(kExprRefEq);
  }
References v8::internal::wasm::kWasmEqRef.
ref_is_null()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ref_is_null (DataRange * data) [inline], [private]
Definition at line 2153 of file random-module-generation.cc.
                                    {
    GenerateRef(kWasmAnyRef, data);
    builder_->Emit(kExprRefIsNull);
  }
References v8::internal::wasm::kWasmAnyRef.
ref_null()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ref_null (HeapType type, DataRange * data) [inline], [private]
Definition at line 1405 of file random-module-generation.cc.
                                                {
    builder_->Emit(kExprRefNull);
    builder_->EmitHeapType(type);
  }
References v8::internal::tracing::type.
ref_test()
template<WasmOpcode opcode>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::ref_test (DataRange * data) [inline], [private]
Definition at line 2159 of file random-module-generation.cc.
                                 {
    GenerateRef(kWasmAnyRef, data);
    constexpr int generic_types[] = {kAnyRefCode, kEqRefCode, kArrayRefCode,
                                     kStructRefCode, kNoneCode, kI31RefCode};
    size_t num_types = structs_.size() + arrays_.size();
    size_t num_all_types = num_types + arraysize(generic_types);
    size_t type_choice = data->get<uint8_t>() % num_all_types;
    builder_->EmitWithPrefix(opcode);
    if (type_choice < structs_.size()) {
      builder_->EmitU32V(structs_[type_choice]);
      return;
    }
    type_choice -= structs_.size();
    if (type_choice < arrays_.size()) {
      builder_->EmitU32V(arrays_[type_choice]);
      return;
    }
    type_choice -= arrays_.size();
    builder_->EmitU32V(generic_types[type_choice]);
  }
References arraysize, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::kAnyRefCode, v8::internal::wasm::kArrayRefCode, v8::internal::wasm::kEqRefCode, v8::internal::wasm::kI31RefCode, v8::internal::wasm::kNoneCode, v8::internal::wasm::kStructRefCode, and v8::internal::wasm::kWasmAnyRef.
requires() [1/2]
template<typename Arr >
requires v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::requires (const Arr & arr) [inline], [private]
Definition at line 2299 of file random-module-generation.cc.
                                      {
      { arr.size() } -> std::convertible_to<std::size_t>;
      { arr.data()[0] } -> std::convertible_to<GenerateFn>;
    }
requires() [2/2]
template<typename Arr >
requires v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::requires (const Arr & arr) [inline], [private]
Definition at line 2322 of file random-module-generation.cc.
                                      {
      { arr.size() } -> std::convertible_to<std::size_t>;
      { arr.data()[0] } -> std::convertible_to<GenerateFnWithHeap>;
    }
return_op()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::return_op (DataRange * data) [inline], [private]
Definition at line 867 of file random-module-generation.cc.
                                  {
    auto returns = builder_->signature()->returns();
    Generate(returns, data);
    builder_->Emit(kExprReturn);
  }
select_random_table()
std::pair<int, ValueType> v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::select_random_table (DataRange * data) [inline], [private]
Definition at line 1587 of file random-module-generation.cc.
                                                               {
    int num_tables = builder_->builder()->NumTables();
    DCHECK_GT(num_tables, 0);
    int index = data->get<uint8_t>() % num_tables;
    ValueType address_type = table_address_type(index);
    return {index, address_type};
  }
References DCHECK_GT, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), and v8::internal::index.
select_with_type()
template<ValueKind select_kind>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::select_with_type (DataRange * data) [inline], [private]
Definition at line 1346 of file random-module-generation.cc.
                                         {
    static_assert(select_kind != kVoid, "illegal kind for select");
    Generate<select_kind, select_kind, kI32>(data);
    // num_types is always 1.
    uint8_t num_types = 1;
    builder_->EmitWithU8U8(kExprSelectWithType, num_types,
                           ValueType::Primitive(select_kind).value_type_code());
  }
References v8::internal::wasm::ValueType::Primitive().
sequence()
template<ValueKind... Types>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::sequence (DataRange * data) [inline], [private]
Definition at line 1374 of file random-module-generation.cc.
                                 {
    Generate<Types...>(data);
  }
set_global()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::set_global (DataRange * data) [inline], [private]
Definition at line 1355 of file random-module-generation.cc.
{ global_op<kVoid>(data); }
set_local()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::set_local (DataRange * data) [inline], [private]
Definition at line 1253 of file random-module-generation.cc.
{ local_op<kVoid>(data, kExprLocalSet); }
shift_locals()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::shift_locals (DataRange * data) [inline], [private]
Definition at line 1287 of file random-module-generation.cc.
                                     {
    const Var local = GetRandomLocal(data);
    if (local.type == kWasmVoid ||
        (local.type.is_non_nullable() && !locals_initialized_)) {
      return;
    }
    shift_locals_to(data, local);
  }
References v8::internal::wasm::ValueTypeBase::is_non_nullable(), v8::internal::wasm::kWasmVoid, and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::Var::type.
shift_locals_to()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::shift_locals_to (DataRange * data, Var start_local) [inline], [private]
Definition at line 1268 of file random-module-generation.cc.
                                                         {
    const uint32_t max_shift = data->get<uint8_t>() % 8 + 2;
    const auto [start_index, type] = start_local;
    const size_t locals_count = all_locals_count();
    uint32_t previous_index = start_index;
    uint32_t index = start_index;
    for (uint32_t i = 0; i < max_shift; ++i) {
      do {
        index = (index + 1) % locals_count;
      } while (local_type(index) != type);
      // Never emit more than one shift over all same-typed locals.
      // (In many cases we might end up with only one local with the same type.)
      if (index == start_index) break;
      builder_->EmitGetLocal(index);
      builder_->EmitSetLocal(previous_index);
      previous_index = index;
    }
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, and v8::internal::tracing::type.
simd_const()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::simd_const (DataRange * data) [inline], [private]
Definition at line 1028 of file random-module-generation.cc.
                                   {
    builder_->EmitWithPrefix(kExprS128Const);
    for (int i = 0; i < kSimd128Size; i++) {
      builder_->EmitByte(data->getPseudoRandom<uint8_t>());
    }
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::getPseudoRandom(), and v8::internal::kSimd128Size.
simd_lane_memop()
template<WasmOpcode Op, int lanes, ValueKind... Args>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::simd_lane_memop (DataRange * data) [inline], [private]
Definition at line 1043 of file random-module-generation.cc.
                                        {
    // Simd load/store instructions that have a lane immediate.
    memop<Op, Args...>(data);
    builder_->EmitByte(data->get<uint8_t>() % lanes);
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get().
simd_lane_op()
template<WasmOpcode Op, int lanes, ValueKind... Args>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::simd_lane_op (DataRange * data) [inline], [private]
Definition at line 1036 of file random-module-generation.cc.
                                     {
    Generate<Args...>(data);
    builder_->EmitWithPrefix(Op);
    builder_->EmitByte(data->get<uint8_t>() % lanes);
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get().
simd_shuffle()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::simd_shuffle (DataRange * data) [inline], [private]
Definition at line 1049 of file random-module-generation.cc.
                                     {
    Generate<kS128, kS128>(data);
    builder_->EmitWithPrefix(kExprI8x16Shuffle);
    for (int i = 0; i < kSimd128Size; i++) {
      builder_->EmitByte(static_cast<uint8_t>(data->get<uint8_t>() % 32));
    }
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), and v8::internal::kSimd128Size.
string_cast()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_cast (DataRange * data) [inline], [private]
Definition at line 2190 of file random-module-generation.cc.
                                    {
    GenerateRef(kWasmExternRef, data);
    call_string_import(string_imports_.cast);
  }
References v8::internal::wasm::kWasmExternRef.
string_charcodeat()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_charcodeat (DataRange * data) [inline], [private]
Definition at line 2210 of file random-module-generation.cc.
                                          {
    GenerateRef(kWasmExternRef, data);
    Generate(kWasmI32, data);
    call_string_import(string_imports_.charCodeAt);
  }
References v8::internal::wasm::kWasmExternRef, and v8::internal::wasm::kWasmI32.
string_codepointat()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_codepointat (DataRange * data) [inline], [private]
Definition at line 2216 of file random-module-generation.cc.
                                           {
    GenerateRef(kWasmExternRef, data);
    Generate(kWasmI32, data);
    call_string_import(string_imports_.codePointAt);
  }
References v8::internal::wasm::kWasmExternRef, and v8::internal::wasm::kWasmI32.
string_compare()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_compare (DataRange * data) [inline], [private]
Definition at line 2246 of file random-module-generation.cc.
                                       {
    GenerateRef(kWasmExternRef, data);
    GenerateRef(kWasmExternRef, data);
    call_string_import(string_imports_.compare);
  }
References v8::internal::wasm::kWasmExternRef.
string_concat()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_concat (DataRange * data) [inline], [private]
Definition at line 2227 of file random-module-generation.cc.
                                      {
    GenerateRef(kWasmExternRef, data);
    GenerateRef(kWasmExternRef, data);
    call_string_import(string_imports_.concat);
  }
References v8::internal::wasm::kWasmExternRef.
string_equals()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_equals (DataRange * data) [inline], [private]
Definition at line 2240 of file random-module-generation.cc.
                                      {
    GenerateRef(kWasmExternRef, data);
    GenerateRef(kWasmExternRef, data);
    call_string_import(string_imports_.equals);
  }
References v8::internal::wasm::kWasmExternRef.
string_fromcharcode()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_fromcharcode (DataRange * data) [inline], [private]
Definition at line 2200 of file random-module-generation.cc.
                                            {
    Generate(kWasmI32, data);
    call_string_import(string_imports_.fromCharCode);
  }
References v8::internal::wasm::kWasmI32.
string_fromcharcodearray()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_fromcharcodearray (DataRange * data) [inline], [private]
Definition at line 2252 of file random-module-generation.cc.
                                                 {
    GenerateRef(HeapType::Index(string_imports_.array_i16, kNotShared,
                                RefTypeKind::kArray),
                data);
    Generate(kWasmI32, data);
    Generate(kWasmI32, data);
    call_string_import(string_imports_.fromCharCodeArray);
  }
References v8::internal::wasm::HeapType::Index(), v8::internal::wasm::kArray, v8::internal::kNotShared, and v8::internal::wasm::kWasmI32.
string_fromcodepoint()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_fromcodepoint (DataRange * data) [inline], [private]
Definition at line 2205 of file random-module-generation.cc.
                                             {
    Generate(kWasmI32, data);
    call_string_import(string_imports_.fromCodePoint);
  }
References v8::internal::wasm::kWasmI32.
string_fromutf8array()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_fromutf8array (DataRange * data) [inline], [private]
Definition at line 2289 of file random-module-generation.cc.
                                             {
    GenerateRef(HeapType::Index(string_imports_.array_i8, kNotShared,
                                RefTypeKind::kArray),
                data);
    Generate(kWasmI32, data);
    Generate(kWasmI32, data);
    call_string_import(string_imports_.decodeStringFromUTF8Array);
  }
References v8::internal::wasm::HeapType::Index(), v8::internal::wasm::kArray, v8::internal::kNotShared, and v8::internal::wasm::kWasmI32.
string_intocharcodearray()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_intocharcodearray (DataRange * data) [inline], [private]
Definition at line 2261 of file random-module-generation.cc.
                                                 {
    GenerateRef(kWasmExternRef, data);
    GenerateRef(HeapType::Index(string_imports_.array_i16, kNotShared,
                                RefTypeKind::kArray),
                data);
    Generate(kWasmI32, data);
    call_string_import(string_imports_.intoCharCodeArray);
  }
References v8::internal::wasm::HeapType::Index(), v8::internal::wasm::kArray, v8::internal::kNotShared, v8::internal::wasm::kWasmExternRef, and v8::internal::wasm::kWasmI32.
string_intoutf8array()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_intoutf8array (DataRange * data) [inline], [private]
Definition at line 2275 of file random-module-generation.cc.
                                             {
    GenerateRef(kWasmExternRef, data);
    GenerateRef(HeapType::Index(string_imports_.array_i8, kNotShared,
                                RefTypeKind::kArray),
                data);
    Generate(kWasmI32, data);
    call_string_import(string_imports_.encodeStringIntoUTF8Array);
  }
References v8::internal::wasm::HeapType::Index(), v8::internal::wasm::kArray, v8::internal::kNotShared, v8::internal::wasm::kWasmExternRef, and v8::internal::wasm::kWasmI32.
string_length()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_length (DataRange * data) [inline], [private]
Definition at line 2222 of file random-module-generation.cc.
                                      {
    GenerateRef(kWasmExternRef, data);
    call_string_import(string_imports_.length);
  }
References v8::internal::wasm::kWasmExternRef.
string_measureutf8()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_measureutf8 (DataRange * data) [inline], [private]
Definition at line 2270 of file random-module-generation.cc.
                                           {
    GenerateRef(kWasmExternRef, data);
    call_string_import(string_imports_.measureStringAsUTF8);
  }
References v8::internal::wasm::kWasmExternRef.
string_substring()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_substring (DataRange * data) [inline], [private]
Definition at line 2233 of file random-module-generation.cc.
                                         {
    GenerateRef(kWasmExternRef, data);
    Generate(kWasmI32, data);
    Generate(kWasmI32, data);
    call_string_import(string_imports_.substring);
  }
References v8::internal::wasm::kWasmExternRef, and v8::internal::wasm::kWasmI32.
string_test()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_test (DataRange * data) [inline], [private]
Definition at line 2195 of file random-module-generation.cc.
                                    {
    GenerateRef(kWasmExternRef, data);
    call_string_import(string_imports_.test);
  }
References v8::internal::wasm::kWasmExternRef.
string_toutf8array()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_toutf8array (DataRange * data) [inline], [private]
Definition at line 2284 of file random-module-generation.cc.
                                           {
    GenerateRef(kWasmExternRef, data);
    call_string_import(string_imports_.encodeStringToUTF8Array);
  }
References v8::internal::wasm::kWasmExternRef.
struct_get()
template<ValueKind wanted_kind>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get (DataRange * data) [inline], [private]
Definition at line 1884 of file random-module-generation.cc.
                                   {
    bool got_struct_value =
        struct_get_helper(ValueType::Primitive(wanted_kind), data);
    if (!got_struct_value) {
      Generate<wanted_kind>(data);
    }
  }
References v8::internal::wasm::ValueType::Primitive().
struct_get_helper()
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get_helper (ValueType value_type, DataRange * data) [inline], [private]
Definition at line 1848 of file random-module-generation.cc.
                                                                {
    WasmModuleBuilder* builder = builder_->builder();
    ZoneVector<uint32_t> field_index(builder->zone());
    ZoneVector<ModuleTypeIndex> struct_index(builder->zone());
    for (ModuleTypeIndex i : structs_) {
      DCHECK(builder->IsStructType(i));
      int field_count = builder->GetStructType(i)->field_count();
      for (int index = 0; index < field_count; index++) {
        // TODO(14034): This should be a subtype check!
        if (builder->GetStructType(i)->field(index) == value_type) {
          field_index.push_back(index);
          struct_index.push_back(i);
        }
      }
    }
    if (!field_index.empty()) {
      int index = data->get<uint8_t>() % static_cast<int>(field_index.size());
      GenerateRef(HeapType::Index(struct_index[index], kNotShared,
                                  RefTypeKind::kStruct),
                  data, kNullable);
      if (builder->GetStructType(struct_index[index])
              ->field(field_index[index])
              .is_packed()) {
        builder_->EmitWithPrefix(data->get<bool>() ? kExprStructGetS
                                                   : kExprStructGetU);
      } else {
        builder_->EmitWithPrefix(kExprStructGet);
      }
      builder_->EmitU32V(struct_index[index]);
      builder_->EmitU32V(field_index[index]);
      return true;
    }
    return false;
  }
References v8::internal::DCHECK(), v8::internal::ZoneVector< T >::empty(), v8::internal::wasm::StructType::field(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::WasmModuleBuilder::GetStructType(), v8::internal::index, v8::internal::wasm::HeapType::Index(), v8::internal::wasm::ValueTypeBase::is_packed(), v8::internal::wasm::WasmModuleBuilder::IsStructType(), v8::internal::kNotShared, v8::internal::wasm::kNullable, v8::internal::wasm::kStruct, v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::size(), v8::internal::wasm::value_type(), and v8::internal::wasm::WasmModuleBuilder::zone().
struct_get_ref()
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get_ref (HeapType type, DataRange * data, Nullability nullable) [inline], [private]
Definition at line 1892 of file random-module-generation.cc.
                                                                            {
    ValueType needed_type = ValueType::RefMaybeNull(type, nullable);
    return struct_get_helper(needed_type, data);
  }
References v8::internal::wasm::ValueType::RefMaybeNull(), and v8::internal::tracing::type.
struct_set()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_set (DataRange * data) [inline], [private]
Definition at line 2127 of file random-module-generation.cc.
                                   {
    WasmModuleBuilder* builder = builder_->builder();
    DCHECK_NE(0, structs_.size()); // We always emit at least one struct type.
    ModuleTypeIndex struct_index =
        structs_[data->get<uint8_t>() % structs_.size()];
    DCHECK(builder->IsStructType(struct_index));
    const StructType* struct_type = builder->GetStructType(struct_index);
    ZoneVector<uint32_t> field_indices(builder->zone());
    for (uint32_t i = 0; i < struct_type->field_count(); i++) {
      if (struct_type->mutability(i)) {
        field_indices.push_back(i);
      }
    }
    if (field_indices.empty()) {
      return;
    }
    int field_index =
        field_indices[data->get<uint8_t>() % field_indices.size()];
    GenerateRef(HeapType::Index(struct_index, kNotShared, RefTypeKind::kStruct),
                data);
    Generate(struct_type->field(field_index).Unpacked(), data);
    builder_->EmitWithPrefix(kExprStructSet);
    builder_->EmitU32V(struct_index);
    builder_->EmitU32V(field_index);
  }
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::ZoneVector< T >::empty(), v8::internal::wasm::StructType::field(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::WasmModuleBuilder::GetStructType(), v8::internal::wasm::HeapType::Index(), v8::internal::wasm::WasmModuleBuilder::IsStructType(), v8::internal::kNotShared, v8::internal::wasm::kStruct, v8::internal::wasm::StructTypeBase::mutability(), v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::size(), v8::internal::wasm::ValueType::Unpacked(), and v8::internal::wasm::WasmModuleBuilder::zone().
table_address_type()
ValueType v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_address_type (int table_index) [inline], [private]
Definition at line 1583 of file random-module-generation.cc.
                                                {
    return builder_->builder()->IsTable64(table_index) ? kWasmI64 : kWasmI32;
  }
References v8::internal::wasm::kWasmI32, and v8::internal::wasm::kWasmI64.
table_copy()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_copy (DataRange * data) [inline], [private]
Definition at line 1639 of file random-module-generation.cc.
                                   {
    ValueType needed_type = data->get<bool>() ? kWasmFuncRef : kWasmExternRef;
    int table_count = builder_->builder()->NumTables();
    ZoneVector<uint32_t> table(builder_->builder()->zone());
    for (int i = 0; i < table_count; i++) {
      if (builder_->builder()->GetTableType(i) == needed_type) {
        table.push_back(i);
      }
    }
    if (table.empty()) {
      return;
    }
    int first_index = data->get<uint8_t>() % static_cast<int>(table.size());
    int second_index = data->get<uint8_t>() % static_cast<int>(table.size());
    ValueType first_addrtype = table_address_type(table[first_index]);
    ValueType second_addrtype = table_address_type(table[second_index]);
    ValueType result_addrtype =
        first_addrtype == kWasmI32 ? kWasmI32 : second_addrtype;
    Generate(first_addrtype, data);
    Generate(second_addrtype, data);
    Generate(result_addrtype, data);
    builder_->EmitWithPrefix(kExprTableCopy);
    builder_->EmitU32V(table[first_index]);
    builder_->EmitU32V(table[second_index]);
  }
References v8::internal::ZoneVector< T >::empty(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmFuncRef, v8::internal::wasm::kWasmI32, v8::internal::ZoneVector< T >::push_back(), and v8::internal::ZoneVector< T >::size().
table_fill()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_fill (DataRange * data) [inline], [private]
Definition at line 1633 of file random-module-generation.cc.
                                   {
    auto [table_index, address_type] = select_random_table(data);
    table_op(table_index, {address_type, kWasmFuncRef, address_type}, data,
             kExprTableFill);
  }
References v8::internal::wasm::kWasmFuncRef.
table_get()
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_get (HeapType type, DataRange * data, Nullability nullable) [inline], [private]
Definition at line 1596 of file random-module-generation.cc.
                                                                       {
    ValueType needed_type = ValueType::RefMaybeNull(type, nullable);
    int table_count = builder_->builder()->NumTables();
    DCHECK_GT(table_count, 0);
    ZoneVector<uint32_t> table(builder_->builder()->zone());
    for (int i = 0; i < table_count; i++) {
      if (builder_->builder()->GetTableType(i) == needed_type) {
        table.push_back(i);
      }
    }
    if (table.empty()) {
      return false;
    }
    int table_index =
        table[data->get<uint8_t>() % static_cast<int>(table.size())];
    ValueType address_type = table_address_type(table_index);
    Generate(address_type, data);
    builder_->Emit(kExprTableGet);
    builder_->EmitU32V(table_index);
    return true;
  }
References DCHECK_GT, v8::internal::ZoneVector< T >::empty(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::ZoneVector< T >::push_back(), v8::internal::wasm::ValueType::RefMaybeNull(), v8::internal::ZoneVector< T >::size(), and v8::internal::tracing::type.
table_grow()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_grow (DataRange * data) [inline], [private]
Definition at line 1628 of file random-module-generation.cc.
                                   {
    auto [table_index, address_type] = select_random_table(data);
    table_op(table_index, {kWasmFuncRef, address_type}, data, kExprTableGrow);
  }
References v8::internal::wasm::kWasmFuncRef.
table_op()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_op (uint32_t index, std::vector< ValueType > types, DataRange * data, WasmOpcode opcode) [inline], [private]
Definition at line 1556 of file random-module-generation.cc.
                                   {
    DCHECK(opcode == kExprTableSet || opcode == kExprTableSize ||
           opcode == kExprTableGrow || opcode == kExprTableFill);
    for (size_t i = 0; i < types.size(); i++) {
      // When passing the reftype by default kWasmFuncRef is used.
      // Then the type is changed according to its table type.
      if (types[i] == kWasmFuncRef) {
        types[i] = builder_->builder()->GetTableType(index);
      }
    }
    Generate(base::VectorOf(types), data);
    if (opcode == kExprTableSet) {
      builder_->Emit(opcode);
    } else {
      builder_->EmitWithPrefix(opcode);
    }
    builder_->EmitU32V(index);
    // The `table_size` and `table_grow` should return an I32. However, the Wasm
    // instruction for table64 returns an I64, so it should be converted.
    if ((opcode == kExprTableSize || opcode == kExprTableGrow) &&
        builder_->builder()->IsTable64(index)) {
      builder_->Emit(kExprI32ConvertI64);
    }
  }
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::wasm::kWasmFuncRef, and v8::base::VectorOf().
table_set()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_set (DataRange * data) [inline], [private]
Definition at line 1618 of file random-module-generation.cc.
                                  {
    auto [table_index, address_type] = select_random_table(data);
    table_op(table_index, {address_type, kWasmFuncRef}, data, kExprTableSet);
  }
References v8::internal::wasm::kWasmFuncRef.
table_size()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_size (DataRange * data) [inline], [private]
Definition at line 1623 of file random-module-generation.cc.
                                   {
    auto [table_index, _] = select_random_table(data);
    table_op(table_index, {}, data, kExprTableSize);
  }
References _.
tee_local()
template<ValueKind wanted_kind>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::tee_local (DataRange * data) [inline], [private]
Definition at line 1256 of file random-module-generation.cc.
                                  {
    local_op<wanted_kind>(data, kExprLocalTee);
  }
throw_or_rethrow()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::throw_or_rethrow (DataRange * data) [inline], [private]
Definition at line 1357 of file random-module-generation.cc.
                                         {
    bool rethrow = data->get<bool>();
    if (rethrow && !catch_blocks_.empty()) {
      int control_depth = static_cast<int>(blocks_.size() - 1);
      int catch_index =
          data->get<uint8_t>() % static_cast<int>(catch_blocks_.size());
      builder_->EmitWithU32V(kExprRethrow,
                             control_depth - catch_blocks_[catch_index]);
    } else {
      int tag = data->get<uint8_t>() % builder_->builder()->NumTags();
      const FunctionSig* exception_sig = builder_->builder()->GetTagType(tag);
      Generate(exception_sig->parameters(), data);
      builder_->EmitWithU32V(kExprThrow, tag);
    }
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), and v8::internal::Signature< T >::parameters().
top_type()
HeapType v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::top_type (HeapType type) [inline], [private]
Definition at line 1905 of file random-module-generation.cc.
                                   {
    switch (type.representation()) {
      case HeapType::kAny:
      case HeapType::kEq:
      case HeapType::kArray:
      case HeapType::kStruct:
      case HeapType::kI31:
      case HeapType::kNone:
        return kWasmAnyRef;
      case HeapType::kExtern:
      case HeapType::kNoExtern:
        return kWasmExternRef;
      case HeapType::kExn:
      case HeapType::kNoExn:
        return kWasmExnRef;
      case HeapType::kFunc:
      case HeapType::kNoFunc:
        return kWasmFuncRef;
      default:
        DCHECK(type.is_index());
        if (builder_->builder()->IsSignature(type.ref_index())) {
          return kWasmFuncRef;
        }
        DCHECK(builder_->builder()->IsStructType(type.ref_index()) ||
               builder_->builder()->IsArrayType(type.ref_index()));
        return kWasmAnyRef;
    }
  }
References v8::internal::DCHECK(), v8::internal::wasm::HeapType::kAny, v8::internal::wasm::HeapType::kArray, v8::internal::wasm::HeapType::kEq, v8::internal::wasm::HeapType::kExn, v8::internal::wasm::HeapType::kExtern, v8::internal::wasm::HeapType::kFunc, v8::internal::wasm::HeapType::kI31, v8::internal::wasm::HeapType::kNoExn, v8::internal::wasm::HeapType::kNoExtern, v8::internal::wasm::HeapType::kNoFunc, v8::internal::wasm::HeapType::kNone, v8::internal::wasm::HeapType::kStruct, v8::internal::wasm::kWasmAnyRef, v8::internal::wasm::kWasmExnRef, v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmFuncRef, and v8::internal::tracing::type.
try_block()
template<ValueKind T>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_block (DataRange * data) [inline], [private]
Definition at line 613 of file random-module-generation.cc.
                                  {
    try_block_helper(ValueType::Primitive(T), data);
  }
References v8::internal::wasm::ValueType::Primitive().
try_block_helper()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_block_helper (ValueType return_type, DataRange * data) [inline], [private]
Definition at line 577 of file random-module-generation.cc.
                                                                {
    bool has_catch_all = data->get<bool>();
    uint8_t num_catch =
        data->get<uint8_t>() % (builder_->builder()->NumTags() + 1);
    bool is_delegate = num_catch == 0 && !has_catch_all && data->get<bool>();
    // Allow one more target than there are enclosing try blocks, for delegating
    // to the caller.
    base::Vector<const ValueType> return_type_vec =
        return_type.kind() == kVoid ? base::Vector<ValueType>{}
                                    : base::VectorOf(&return_type, 1);
    BlockScope block_scope(this, kExprTry, {}, return_type_vec, return_type_vec,
                           !is_delegate);
    int control_depth = static_cast<int>(blocks_.size()) - 1;
    Generate(return_type, data);
    catch_blocks_.push_back(control_depth);
    for (int i = 0; i < num_catch; ++i) {
      const FunctionSig* exception_type = builder_->builder()->GetTagType(i);
      builder_->EmitWithU32V(kExprCatch, i);
      ConsumeAndGenerate(exception_type->parameters(), return_type_vec, data);
    }
    if (has_catch_all) {
      builder_->Emit(kExprCatchAll);
      Generate(return_type, data);
    }
    if (is_delegate) {
      // The delegate target depth does not include the current try block,
      // because 'delegate' closes this scope. However it is still in the
      // {blocks_} list, so remove one to get the correct size.
      int delegate_depth = data->get<uint8_t>() % (blocks_.size() - 1);
      builder_->EmitWithU32V(kExprDelegate, delegate_depth);
    }
    catch_blocks_.pop_back();
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::Signature< T >::parameters(), and v8::base::VectorOf().
try_table_block()
template<ValueKind T>
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_table_block (DataRange * data) [inline], [private]
Definition at line 705 of file random-module-generation.cc.
                                        {
    ValueType return_types_arr[1] = {ValueType::Primitive(T)};
    auto return_types = base::VectorOf(return_types_arr, T == kVoid ? 0 : 1);
    if (!v8_flags.experimental_wasm_exnref) {
      // Can't generate a try_table block. Just generate something else.
      any_block({}, return_types, data);
      return;
    }
    try_table_block_helper({}, return_types, data);
  }
References v8::internal::wasm::ValueType::Primitive(), v8::internal::v8_flags, and v8::base::VectorOf().
try_table_block_helper()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_table_block_helper (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, DataRange * data) [inline], [private]
Definition at line 686 of file random-module-generation.cc.
                                               {
    uint8_t num_catch = data->get<uint8_t>() % kMaxCatchCases;
    auto catch_cases =
        builder_->builder()->zone()->AllocateVector<CatchCase>(num_catch);
    for (int i = 0; i < num_catch; ++i) {
      catch_cases[i].tag_index =
          data->get<uint8_t>() % builder_->builder()->NumTags();
      catch_cases[i].kind =
          static_cast<CatchKind>(data->get<uint8_t>() % (kLastCatchKind + 1));
    }
    BlockScope block_scope(this, kExprBlock, param_types, return_types,
                           return_types);
    try_table_rec(param_types, return_types, catch_cases, 0, data);
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::DataRange::get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::kLastCatchKind, v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::kMaxCatchCases, and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::CatchCase::tag_index.
try_table_rec()
void v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_table_rec (base::Vector< const ValueType > param_types, base::Vector< const ValueType > return_types, base::Vector< CatchCase > catch_cases, size_t i, DataRange * data) [inline], [private]
Definition at line 624 of file random-module-generation.cc.
                                      {
    DCHECK(v8_flags.experimental_wasm_exnref);
    if (i == catch_cases.size()) {
      // Base case: emit the try-table itself.
      builder_->Emit(kExprTryTable);
      blocks_.emplace_back(return_types.begin(), return_types.end());
      const bool is_final = true;
      ModuleTypeIndex try_sig_index = builder_->builder()->AddSignature(
          CreateSignature(builder_->builder()->zone(), param_types,
                          return_types),
          is_final);
      builder_->EmitI32V(try_sig_index);
      builder_->EmitU32V(static_cast<uint32_t>(catch_cases.size()));
      for (size_t j = 0; j < catch_cases.size(); ++j) {
        builder_->EmitByte(catch_cases[j].kind);
        if (catch_cases[j].kind == kCatch || catch_cases[j].kind == kCatchRef) {
          builder_->EmitByte(catch_cases[j].tag_index);
        }
        builder_->EmitByte(catch_cases.size() - j - 1);
      }
      ConsumeAndGenerate(param_types, return_types, data);
      builder_->Emit(kExprEnd);
      blocks_.pop_back();
      builder_->EmitWithI32V(kExprBr, static_cast<int32_t>(catch_cases.size()));
      return;
    }
    // Enter the i-th nested block. The signature of the block is built as
    // follows:
    // - The input types are the same for each block, the operands are forwarded
    // as-is to the inner try-table.
    // - The output types can be empty, or contain the tag types and/or an
    // exnref depending on the catch kind
    const FunctionSig* type =
        builder_->builder()->GetTagType(catch_cases[i].tag_index);
    int has_tag =
        catch_cases[i].kind == kCatchRef || catch_cases[i].kind == kCatch;
    int has_ref =
        catch_cases[i].kind == kCatchAllRef || catch_cases[i].kind == kCatchRef;
    size_t return_count =
        (has_tag ? type->parameter_count() : 0) + (has_ref ? 1 : 0);
    auto block_returns =
        builder_->builder()->zone()->AllocateVector<ValueType>(return_count);
    if (has_tag) {
      std::copy_n(type->parameters().begin(), type->parameter_count(),
                  block_returns.begin());
    }
    if (has_ref) block_returns.last() = kWasmExnRef;
    {
      BlockScope block(this, kExprBlock, param_types, block_returns,
                       block_returns);
      try_table_rec(param_types, return_types, catch_cases, i + 1, data);
    }
    // Catch label. Consume the unpacked values and exnref (if any), produce
    // values that match the outer scope, and branch to it.
    ConsumeAndGenerate(block_returns, return_types, data);
    builder_->EmitWithU32V(kExprBr, static_cast<uint32_t>(i));
  }
References v8::base::Vector< T >::begin(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateSignature(), v8::internal::DCHECK(), v8::base::Vector< T >::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::kCatchAllRef, v8::internal::wasm::kCatchRef, v8::internal::wasm::kWasmExnRef, v8::base::Vector< T >::size(), v8::internal::tracing::type, and v8::internal::v8_flags.
Member Data Documentation
arrays_
const std::vector<ModuleTypeIndex>& v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::arrays_ [private]
Definition at line 3671 of file random-module-generation.cc.
blocks_
std::vector<std::vector<ValueType> > v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::blocks_ [private]
Definition at line 3663 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope().
builder_
WasmFunctionBuilder* const v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::builder_ [private]
Definition at line 3662 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope().
catch_blocks_
std::vector<int> v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::catch_blocks_ [private]
Definition at line 3669 of file random-module-generation.cc.
functions_
const std::vector<ModuleTypeIndex>& v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::functions_ [private]
Definition at line 3664 of file random-module-generation.cc.
globals_
std::vector<ValueType> v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::globals_ [private]
Definition at line 3666 of file random-module-generation.cc.
locals_
std::vector<ValueType> v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::locals_ [private]
Definition at line 3665 of file random-module-generation.cc.
locals_initialized_
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::locals_initialized_ = false [private]
Definition at line 3673 of file random-module-generation.cc.
mutable_globals_
std::vector<uint8_t> v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::mutable_globals_ [private]
Definition at line 3667 of file random-module-generation.cc.
options_
const WasmModuleGenerationOptions v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::options_ [private]
Definition at line 3661 of file random-module-generation.cc.
recursion_depth
uint32_t v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::recursion_depth = 0 [private]
Definition at line 3668 of file random-module-generation.cc.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GeneratorRecursionScope::GeneratorRecursionScope().
string_imports_
const StringImports& v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_imports_ [private]
Definition at line 3672 of file random-module-generation.cc.
structs_
const std::vector<ModuleTypeIndex>& v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::structs_ [private]
Definition at line 3670 of file random-module-generation.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/fuzzing/random-module-generation.cc