v8::internal::compiler::ScopedExceptionHandler Class Reference
#include <code-assembler.h>
Public Member Functions
ScopedExceptionHandler (CodeAssembler *assembler, CodeAssemblerExceptionHandlerLabel *label)
ScopedExceptionHandler (CodeAssembler *assembler, CodeAssemblerLabel *label, TypedCodeAssemblerVariable< Object > *exception)
~ScopedExceptionHandler ()
Private Attributes
bool has_handler_
CodeAssembler * assembler_
CodeAssemblerLabel * compatibility_label_
std::unique_ptr< CodeAssemblerExceptionHandlerLabel > label_
TypedCodeAssemblerVariable< Object > * exception_
Detailed Description
Definition at line 1936 of file code-assembler.h.
Constructor & Destructor Documentation
ScopedExceptionHandler() [1/2]
v8::internal::compiler::ScopedExceptionHandler::ScopedExceptionHandler (CodeAssembler * assembler, CodeAssemblerExceptionHandlerLabel * label)
Definition at line 2018 of file code-assembler.cc.
    : has_handler_(label != nullptr),
      assembler_(assembler),
      compatibility_label_(nullptr),
      exception_(nullptr) {
  if (has_handler_) {
    assembler_->state()->PushExceptionHandler(label);
  }
}
References assembler_, has_handler_, v8::internal::compiler::CodeAssemblerState::PushExceptionHandler(), and v8::internal::compiler::CodeAssembler::state().
ScopedExceptionHandler() [2/2]
v8::internal::compiler::ScopedExceptionHandler::ScopedExceptionHandler (CodeAssembler * assembler, CodeAssemblerLabel * label, TypedCodeAssemblerVariable< Object > * exception)
Definition at line 2029 of file code-assembler.cc.
    : has_handler_(label != nullptr),
      assembler_(assembler),
      compatibility_label_(label),
      exception_(exception) {
  if (has_handler_) {
    label_ = std::make_unique<CodeAssemblerExceptionHandlerLabel>(
        assembler, CodeAssemblerLabel::kDeferred);
    assembler_->state()->PushExceptionHandler(label_.get());
  }
}
References assembler_, has_handler_, v8::internal::compiler::CodeAssemblerLabel::kDeferred, label_, v8::internal::compiler::CodeAssemblerState::PushExceptionHandler(), and v8::internal::compiler::CodeAssembler::state().
 ScopedExceptionHandler()
v8::internal::compiler::ScopedExceptionHandler::~ScopedExceptionHandler ()
Definition at line 2043 of file code-assembler.cc.
                                                {
  if (has_handler_) {
    assembler_->state()->PopExceptionHandler();
  }
  if (label_ && label_->is_used()) {
    CodeAssembler::Label skip(assembler_);
    bool inside_block = assembler_->state()->InsideBlock();
    if (inside_block) {
      assembler_->Goto(&skip);
    }
    TNode<JSAny> e;
    assembler_->Bind(label_.get(), &e);
    if (exception_ != nullptr) *exception_ = e;
    assembler_->Goto(compatibility_label_);
    if (inside_block) {
      assembler_->Bind(&skip);
    }
  }
}
References assembler_, v8::internal::compiler::CodeAssembler::Bind(), compatibility_label_, exception_, v8::internal::compiler::CodeAssembler::Goto(), has_handler_, v8::internal::compiler::CodeAssemblerState::InsideBlock(), label_, v8::internal::compiler::CodeAssemblerState::PopExceptionHandler(), and v8::internal::compiler::CodeAssembler::state().
Member Data Documentation
assembler_
CodeAssembler* v8::internal::compiler::ScopedExceptionHandler::assembler_ [private]
Definition at line 1950 of file code-assembler.h.
Referenced by ScopedExceptionHandler(), and ~ScopedExceptionHandler().
compatibility_label_
CodeAssemblerLabel* v8::internal::compiler::ScopedExceptionHandler::compatibility_label_ [private]
Definition at line 1951 of file code-assembler.h.
Referenced by ~ScopedExceptionHandler().
exception_
TypedCodeAssemblerVariable<Object>* v8::internal::compiler::ScopedExceptionHandler::exception_ [private]
Definition at line 1953 of file code-assembler.h.
Referenced by ~ScopedExceptionHandler().
has_handler_
bool v8::internal::compiler::ScopedExceptionHandler::has_handler_ [private]
Definition at line 1949 of file code-assembler.h.
Referenced by ScopedExceptionHandler(), and ~ScopedExceptionHandler().
label_
std::unique_ptr<CodeAssemblerExceptionHandlerLabel> v8::internal::compiler::ScopedExceptionHandler::label_ [private]
Definition at line 1952 of file code-assembler.h.
Referenced by ScopedExceptionHandler(), and ~ScopedExceptionHandler().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/code-assembler.h
/mnt/V8SourceCode/src/compiler/code-assembler.cc