v8::internal::compiler::AllocationBuilder Class Reference
#include <allocation-builder.h>
Public Member Functions
AllocationBuilder (JSGraph *jsgraph, JSHeapBroker *broker, Node *effect, Node *control)
void Allocate (int size, AllocationType allocation=AllocationType::kYoung, Type type=Type::Any())
void Store (const FieldAccess &access, Node *value)
void Store (ElementAccess const &access, Node *index, Node *value)
void AllocateContext (int variadic_part_length, MapRef map)
bool CanAllocateArray (int length, MapRef map, AllocationType allocation=AllocationType::kYoung)
void AllocateArray (int length, MapRef map, AllocationType allocation=AllocationType::kYoung)
bool CanAllocateSloppyArgumentElements (int length, MapRef map, AllocationType allocation=AllocationType::kYoung)
void AllocateSloppyArgumentElements (int length, MapRef map, AllocationType allocation=AllocationType::kYoung)
void Store (const FieldAccess &access, ObjectRef value)
void FinishAndChange (Node *node)
Node * Finish ()
Protected Member Functions
JSGraph * jsgraph ()
Isolate * isolate () const
TFGraph * graph ()
CommonOperatorBuilder * common ()
SimplifiedOperatorBuilder * simplified ()
Private Attributes
JSGraph *const jsgraph_
JSHeapBroker *const broker_
Node * allocation_
Node * effect_
Node * control_
Detailed Description
Definition at line 19 of file allocation-builder.h.
Constructor & Destructor Documentation
AllocationBuilder()
v8::internal::compiler::AllocationBuilder::AllocationBuilder (JSGraph * jsgraph, JSHeapBroker * broker, Node * effect, Node * control) [inline]
Definition at line 21 of file allocation-builder.h.
      : jsgraph_(jsgraph),
        broker_(broker),
        allocation_(nullptr),
        effect_(effect),
        control_(control) {}
Member Function Documentation
Allocate()
void v8::internal::compiler::AllocationBuilder::Allocate (int size, AllocationType allocation = AllocationType::kYoung, Type type = Type::Any()) [inline]
Definition at line 19 of file allocation-builder-inl.h.
                                            {
  CHECK_GT(size, 0);
  DCHECK_LE(size, isolate()->heap()->MaxRegularHeapObjectSize(allocation));
  effect_ = graph()->NewNode(
      common()->BeginRegion(RegionObservability::kNotObservable), effect_);
  allocation_ =
      graph()->NewNode(simplified()->Allocate(type, allocation),
                       jsgraph()->ConstantNoHole(size), effect_, control_);
  effect_ = allocation_;
}
References allocation_, CHECK_GT, common(), control_, DCHECK_LE, effect_, graph(), heap(), isolate(), jsgraph(), v8::internal::compiler::kNotObservable, v8::internal::compiler::TFGraph::NewNode(), simplified(), size(), and v8::internal::tracing::type.
Referenced by AllocateArray(), AllocateContext(), v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp(), AllocateSloppyArgumentElements(), v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateIterResultObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateKeyValueArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreatePromise(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringWrapper(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral().
AllocateArray()
void v8::internal::compiler::AllocationBuilder::AllocateArray (int length, MapRef map, AllocationType allocation = AllocationType::kYoung) [inline]
Definition at line 55 of file allocation-builder-inl.h.
                                                                 {
  DCHECK(CanAllocateArray(length, map, allocation));
  int size = (map.instance_type() == FIXED_ARRAY_TYPE)
                 ? FixedArray::SizeFor(length)
                 : FixedDoubleArray::SizeFor(length);
  Allocate(size, allocation, Type::OtherInternal());
  Store(AccessBuilder::ForMap(), map);
  Store(AccessBuilder::ForFixedArrayLength(),
        jsgraph()->ConstantNoHole(length));
}
References Allocate(), CanAllocateArray(), v8::internal::DCHECK(), v8::internal::compiler::AccessBuilder::ForFixedArrayLength(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::MapRef::instance_type(), jsgraph(), v8::internal::length, size(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor(), v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::SizeFor(), and Store().
Referenced by v8::internal::compiler::JSCreateLowering::AllocateElements(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateKeyValueArray(), v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements(), and v8::internal::compiler::JSCreateLowering::TryAllocateRestArguments().
AllocateContext()
void v8::internal::compiler::AllocationBuilder::AllocateContext (int variadic_part_length, MapRef map) [inline]
Definition at line 31 of file allocation-builder-inl.h.
                                                                            {
  DCHECK(base::IsInRange(map.instance_type(), FIRST_CONTEXT_TYPE,
                         LAST_CONTEXT_TYPE));
  DCHECK_NE(NATIVE_CONTEXT_TYPE, map.instance_type());
  int size = Context::SizeFor(variadic_part_length);
  Allocate(size, AllocationType::kYoung, Type::OtherInternal());
  Store(AccessBuilder::ForMap(), map);
  static_assert(static_cast<int>(Context::kLengthOffset) ==
                static_cast<int>(offsetof(FixedArray, length_)));
  Store(AccessBuilder::ForFixedArrayLength(),
        jsgraph()->ConstantNoHole(variadic_part_length));
}
References Allocate(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::compiler::AccessBuilder::ForFixedArrayLength(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::MapRef::instance_type(), jsgraph(), v8::internal::kYoung, size(), v8::internal::Context::SizeFor(), and Store().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateBlockContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCatchContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateFunctionContext(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateWithContext().
AllocateSloppyArgumentElements()
void v8::internal::compiler::AllocationBuilder::AllocateSloppyArgumentElements (int length, MapRef map, AllocationType allocation = AllocationType::kYoung) [inline]
Definition at line 73 of file allocation-builder-inl.h.
                                                       {
  DCHECK(CanAllocateSloppyArgumentElements(length, map, allocation));
  int size = SloppyArgumentsElements::SizeFor(length);
  Allocate(size, allocation, Type::OtherInternal());
  Store(AccessBuilder::ForMap(), map);
  Store(AccessBuilder::ForFixedArrayLength(),
        jsgraph()->ConstantNoHole(length));
}
References Allocate(), CanAllocateSloppyArgumentElements(), v8::internal::DCHECK(), v8::internal::compiler::AccessBuilder::ForFixedArrayLength(), v8::internal::compiler::AccessBuilder::ForMap(), jsgraph(), v8::internal::length, size(), v8::internal::TaggedArrayBase< SloppyArgumentsElements, SloppyArgumentsElementsShape >::SizeFor(), and Store().
Referenced by v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments().
CanAllocateArray()
bool v8::internal::compiler::AllocationBuilder::CanAllocateArray (int length, MapRef map, AllocationType allocation = AllocationType::kYoung) [inline]
Definition at line 44 of file allocation-builder-inl.h.
                                                                    {
  DCHECK(map.instance_type() == FIXED_ARRAY_TYPE ||
         map.instance_type() == FIXED_DOUBLE_ARRAY_TYPE);
  int const size = (map.instance_type() == FIXED_ARRAY_TYPE)
                       ? FixedArray::SizeFor(length)
                       : FixedDoubleArray::SizeFor(length);
  return size <= isolate()->heap()->MaxRegularHeapObjectSize(allocation);
}
References v8::internal::DCHECK(), v8::internal::Isolate::heap(), v8::internal::compiler::MapRef::instance_type(), isolate(), v8::internal::length, v8::internal::Heap::MaxRegularHeapObjectSize(), size(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor(), and v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::SizeFor().
Referenced by AllocateArray(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionEnter(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements(), and v8::internal::compiler::JSCreateLowering::TryAllocateRestArguments().
CanAllocateSloppyArgumentElements()
bool v8::internal::compiler::AllocationBuilder::CanAllocateSloppyArgumentElements (int length, MapRef map, AllocationType allocation = AllocationType::kYoung) [inline]
Definition at line 67 of file allocation-builder-inl.h.
                                                       {
  int const size = SloppyArgumentsElements::SizeFor(length);
  return size <= isolate()->heap()->MaxRegularHeapObjectSize(allocation);
}
References v8::internal::Isolate::heap(), isolate(), v8::internal::length, v8::internal::Heap::MaxRegularHeapObjectSize(), size(), and v8::internal::TaggedArrayBase< SloppyArgumentsElements, SloppyArgumentsElementsShape >::SizeFor().
Referenced by AllocateSloppyArgumentElements(), and v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments().
common()
CommonOperatorBuilder* v8::internal::compiler::AllocationBuilder::common () [inline], [protected]
Definition at line 90 of file allocation-builder.h.
{ return jsgraph_->common(); }
References v8::internal::compiler::MachineGraph::common(), and jsgraph_.
Referenced by Allocate(), Finish(), and FinishAndChange().
Finish()
Node* v8::internal::compiler::AllocationBuilder::Finish () [inline]
Definition at line 82 of file allocation-builder.h.
                 {
    return graph()->NewNode(common()->FinishRegion(), allocation_, effect_);
  }
References allocation_, common(), effect_, graph(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by v8::internal::compiler::JSCreateLowering::AllocateElements(), v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp(), v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateKeyValueArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements(), and v8::internal::compiler::JSCreateLowering::TryAllocateRestArguments().
FinishAndChange()
void v8::internal::compiler::AllocationBuilder::FinishAndChange (Node * node) [inline]
Definition at line 74 of file allocation-builder.h.
                                   {
    NodeProperties::SetType(allocation_, NodeProperties::GetType(node));
    node->ReplaceInput(0, allocation_);
    node->ReplaceInput(1, effect_);
    node->TrimInputCount(2);
    NodeProperties::ChangeOp(node, common()->FinishRegion());
  }
References allocation_, v8::internal::compiler::NodeProperties::ChangeOp(), common(), effect_, v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::NodeProperties::SetType(), and v8::internal::compiler::Node::TrimInputCount().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBlockContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCatchContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateFunctionContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateIterResultObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateKeyValueArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreatePromise(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringWrapper(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateWithContext(), and v8::internal::compiler::JSCreateLowering::ReduceNewArray().
graph()
TFGraph* v8::internal::compiler::AllocationBuilder::graph () [inline], [protected]
Definition at line 89 of file allocation-builder.h.
{ return jsgraph_->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph_.
Referenced by Allocate(), Finish(), and Store().
isolate()
Isolate* v8::internal::compiler::AllocationBuilder::isolate () const [inline], [protected]
Definition at line 88 of file allocation-builder.h.
{ return jsgraph_->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph_.
Referenced by Allocate(), CanAllocateArray(), and CanAllocateSloppyArgumentElements().
jsgraph()
JSGraph* v8::internal::compiler::AllocationBuilder::jsgraph () [inline], [protected]
Definition at line 87 of file allocation-builder.h.
{ return jsgraph_; }
References jsgraph_.
Referenced by Allocate(), AllocateArray(), AllocateContext(), AllocateSloppyArgumentElements(), and Store().
simplified()
SimplifiedOperatorBuilder* v8::internal::compiler::AllocationBuilder::simplified () [inline], [protected]
Definition at line 91 of file allocation-builder.h.
{ return jsgraph_->simplified(); }
References jsgraph_, and v8::internal::compiler::JSGraph::simplified().
Referenced by Allocate(), and Store().
Store() [1/3]
void v8::internal::compiler::AllocationBuilder::Store (const FieldAccess & access, Node * value) [inline]
Definition at line 35 of file allocation-builder.h.
                                                     {
    effect_ = graph()->NewNode(simplified()->StoreField(access), allocation_,
                               value, effect_, control_);
  }
References allocation_, control_, effect_, graph(), v8::internal::compiler::TFGraph::NewNode(), simplified(), and v8::internal::value.
Referenced by AllocateArray(), AllocateContext(), v8::internal::compiler::JSCreateLowering::AllocateElements(), v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp(), AllocateSloppyArgumentElements(), v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBlockContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCatchContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateFunctionContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateIterResultObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateKeyValueArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreatePromise(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringWrapper(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateWithContext(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), Store(), v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements(), and v8::internal::compiler::JSCreateLowering::TryAllocateRestArguments().
Store() [2/3]
void v8::internal::compiler::AllocationBuilder::Store (const FieldAccess & access, ObjectRef value) [inline]
Definition at line 65 of file allocation-builder.h.
                                                         {
    if (access.machine_type == MachineType::IndirectPointer()) {
      Store(access,
            jsgraph()->TrustedHeapConstant(value.AsHeapObject().object()));
    } else {
      Store(access, jsgraph()->ConstantNoHole(value, broker_));
    }
  }
References broker_, v8::internal::MachineType::IndirectPointer(), jsgraph(), v8::internal::compiler::FieldAccess::machine_type, Store(), and v8::internal::value.
Store() [3/3]
void v8::internal::compiler::AllocationBuilder::Store (ElementAccess const & access, Node * index, Node * value) [inline]
Definition at line 41 of file allocation-builder.h.
                                                                    {
    effect_ = graph()->NewNode(simplified()->StoreElement(access), allocation_,
                               index, value, effect_, control_);
  }
References allocation_, control_, effect_, graph(), v8::internal::index, v8::internal::compiler::TFGraph::NewNode(), simplified(), and v8::internal::value.
Member Data Documentation
allocation_
Node* v8::internal::compiler::AllocationBuilder::allocation_ [private]
Definition at line 96 of file allocation-builder.h.
Referenced by Allocate(), Finish(), FinishAndChange(), and Store().
broker_
JSHeapBroker* const v8::internal::compiler::AllocationBuilder::broker_ [private]
Definition at line 95 of file allocation-builder.h.
Referenced by Store().
control_
Node* v8::internal::compiler::AllocationBuilder::control_ [private]
Definition at line 98 of file allocation-builder.h.
Referenced by Allocate(), and Store().
effect_
Node* v8::internal::compiler::AllocationBuilder::effect_ [private]
Definition at line 97 of file allocation-builder.h.
Referenced by Allocate(), Finish(), FinishAndChange(), and Store().
jsgraph_
JSGraph* const v8::internal::compiler::AllocationBuilder::jsgraph_ [private]
Definition at line 94 of file allocation-builder.h.
Referenced by common(), graph(), isolate(), jsgraph(), and simplified().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/allocation-builder.h
/mnt/V8SourceCode/src/compiler/allocation-builder-inl.h