v8::internal::CharacterSet Class Reference
#include <regexp-ast.h>
Public Member Functions
CharacterSet (StandardCharacterSet standard_set_type)
CharacterSet (ZoneList< CharacterRange > *ranges)
ZoneList< CharacterRange > * ranges (Zone *zone)
StandardCharacterSet standard_set_type () const
void set_standard_set_type (StandardCharacterSet standard_set_type)
bool is_standard () const
V8_EXPORT_PRIVATE void Canonicalize ()
Private Attributes
ZoneList< CharacterRange > * ranges_ = nullptr
std::optional< StandardCharacterSet > standard_set_type_
Detailed Description
Definition at line 284 of file regexp-ast.h.
Constructor & Destructor Documentation
CharacterSet() [1/2]
v8::internal::CharacterSet::CharacterSet (StandardCharacterSet standard_set_type) [inline], [explicit]
Definition at line 286 of file regexp-ast.h.
      : standard_set_type_(standard_set_type) {}
CharacterSet() [2/2]
v8::internal::CharacterSet::CharacterSet (ZoneList< CharacterRange > * ranges) [inline], [explicit]
Definition at line 288 of file regexp-ast.h.
: ranges_(ranges) {}
Member Function Documentation
Canonicalize()
void v8::internal::CharacterSet::Canonicalize ()
Definition at line 1708 of file regexp-compiler-tonode.cc.
                                {
  // Special/default classes are always considered canonical. The result
  // of calling ranges() will be sorted.
  if (ranges_ == nullptr) return;
  CharacterRange::Canonicalize(ranges_);
}
References v8::internal::CharacterRange::Canonicalize().
is_standard()
bool v8::internal::CharacterSet::is_standard () const [inline]
Definition at line 297 of file regexp-ast.h.
{ return standard_set_type_.has_value(); }
References standard_set_type_.
ranges()
ZoneList< CharacterRange > * v8::internal::CharacterSet::ranges (Zone * zone)
Definition at line 1624 of file regexp-compiler-tonode.cc.
                                                         {
  if (ranges_ == nullptr) {
    ranges_ = zone->New<ZoneList<CharacterRange>>(2, zone);
    CharacterRange::AddClassEscape(standard_set_type_.value(), ranges_, false,
                                   zone);
  }
  return ranges_;
}
References v8::internal::CharacterRange::AddClassEscape(), and v8::internal::Zone::New().
Referenced by v8::internal::RegExpClassRanges::ranges().
set_standard_set_type()
void v8::internal::CharacterSet::set_standard_set_type (StandardCharacterSet standard_set_type) [inline]
Definition at line 294 of file regexp-ast.h.
                                                                     {
    standard_set_type_ = standard_set_type;
  }
References standard_set_type(), and standard_set_type_.
standard_set_type()
StandardCharacterSet v8::internal::CharacterSet::standard_set_type () const [inline]
Definition at line 291 of file regexp-ast.h.
                                                 {
    return standard_set_type_.value();
  }
References standard_set_type_.
Referenced by set_standard_set_type(), and v8::internal::RegExpClassRanges::standard_type().
Member Data Documentation
ranges_
ZoneList<CharacterRange>* v8::internal::CharacterSet::ranges_ = nullptr [private]
Definition at line 301 of file regexp-ast.h.
standard_set_type_
std::optional<StandardCharacterSet> v8::internal::CharacterSet::standard_set_type_ [private]
Definition at line 302 of file regexp-ast.h.
Referenced by is_standard(), set_standard_set_type(), and standard_set_type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-compiler-tonode.cc