v8::internal::WasmExceptionPackage Class Reference
#include <wasm-objects.h>
Public Types
enum { kTagIndex
, kValuesIndex
, kInObjectFieldCount
 }
Public Member Functions
OBJECT_CONSTRUCTORS (WasmExceptionPackage, JSObject)
Static Public Member Functions
static DirectHandle< WasmExceptionPackage > New (Isolate *isolate, DirectHandle< WasmExceptionTag > exception_tag, int encoded_size)
static DirectHandle< WasmExceptionPackage > New (Isolate *isolate, DirectHandle< WasmExceptionTag > exception_tag, DirectHandle< FixedArray > values)
static DirectHandle< Object > GetExceptionTag (Isolate *isolate, DirectHandle< WasmExceptionPackage > exception_package)
static DirectHandle< Object > GetExceptionValues (Isolate *isolate, DirectHandle< WasmExceptionPackage > exception_package)
static uint32_t GetEncodedSize (const wasm::WasmTagSig *tag)
static uint32_t GetEncodedSize (const wasm::WasmTag *tag)
Static Public Attributes
static constexpr int kSize
Detailed Description
Definition at line 946 of file wasm-objects.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kTagIndex
kValuesIndex
kInObjectFieldCount
Definition at line 968 of file wasm-objects.h.
{ kTagIndex, kValuesIndex, kInObjectFieldCount };
Member Function Documentation
GetEncodedSize() [1/2]
uint32_t v8::internal::WasmExceptionPackage::GetEncodedSize (const wasm::WasmTag * tag) [static]
Definition at line 2860 of file wasm-objects.cc.
                                                                    {
  return GetEncodedSize(tag->sig);
}
References GetEncodedSize(), and v8::internal::wasm::WasmTag::sig.
GetEncodedSize() [2/2]
uint32_t v8::internal::WasmExceptionPackage::GetEncodedSize (const wasm::WasmTagSig * tag) [static]
Definition at line 2865 of file wasm-objects.cc.
                                                                       {
  uint32_t encoded_size = 0;
  for (size_t i = 0; i < sig->parameter_count(); ++i) {
    switch (sig->GetParam(i).kind()) {
      case wasm::kI32:
      case wasm::kF32:
        DCHECK_EQ(2, ComputeEncodedElementSize(sig->GetParam(i)));
        encoded_size += 2;
        break;
      case wasm::kI64:
      case wasm::kF64:
        DCHECK_EQ(4, ComputeEncodedElementSize(sig->GetParam(i)));
        encoded_size += 4;
        break;
      case wasm::kS128:
        DCHECK_EQ(8, ComputeEncodedElementSize(sig->GetParam(i)));
        encoded_size += 8;
        break;
      case wasm::kRef:
      case wasm::kRefNull:
        encoded_size += 1;
        break;
      case wasm::kVoid:
      case wasm::kTop:
      case wasm::kBottom:
      case wasm::kI8:
      case wasm::kI16:
      case wasm::kF16:
        UNREACHABLE();
    }
  }
  return encoded_size;
}
References DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::sig, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CreateWasmExceptionPackage(), GetEncodedSize(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetEncodedSize(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetExceptionValues(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Throw(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Throw(), and v8::internal::wasm::WasmInterpreterRuntime::UnpackException().
GetExceptionTag()
DirectHandle< Object > v8::internal::WasmExceptionPackage::GetExceptionTag (Isolate * isolate, DirectHandle< WasmExceptionPackage > exception_package) [static]
Definition at line 2769 of file wasm-objects.cc.
                                                                            {
  DirectHandle<Object> tag;
  if (JSReceiver::GetProperty(isolate, exception_package,
                              isolate->factory()->wasm_exception_tag_symbol())
          .ToHandle(&tag)) {
    return tag;
  }
  return isolate->factory()->undefined_value();
}
References v8::internal::Isolate::factory(), and v8::internal::JSReceiver::GetProperty().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::HandleException(), v8::internal::RUNTIME_FUNCTION(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionGetArgImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionIsImpl().
GetExceptionValues()
DirectHandle< Object > v8::internal::WasmExceptionPackage::GetExceptionValues (Isolate * isolate, DirectHandle< WasmExceptionPackage > exception_package) [static]
Definition at line 2781 of file wasm-objects.cc.
                                                                            {
  DirectHandle<Object> values;
  if (JSReceiver::GetProperty(
          isolate, exception_package,
          isolate->factory()->wasm_exception_values_symbol())
          .ToHandle(&values)) {
    DCHECK_IMPLIES(!IsUndefined(*values), IsFixedArray(*values));
    return values;
  }
  return isolate->factory()->undefined_value();
}
References DCHECK_IMPLIES, v8::internal::Isolate::factory(), and v8::internal::JSReceiver::GetProperty().
Referenced by v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::Handlers< Compressed >::s2s_Throw(), v8::internal::wasm::WasmInterpreterRuntime::UnpackException(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionGetArgImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl().
New() [1/2]
DirectHandle< WasmExceptionPackage > v8::internal::WasmExceptionPackage::New (Isolate * isolate, DirectHandle< WasmExceptionTag > exception_tag, DirectHandle< FixedArray > values) [static]
Definition at line 2756 of file wasm-objects.cc.
                                     {
  DirectHandle<JSFunction> exception_cons(
      isolate->native_context()->wasm_exception_constructor(), isolate);
  DirectHandle<JSObject> exception =
      isolate->factory()->NewJSObject(exception_cons);
  exception->InObjectPropertyAtPut(kTagIndex, *exception_tag);
  exception->InObjectPropertyAtPut(kValuesIndex, *values);
  return Cast<WasmExceptionPackage>(exception);
}
References v8::internal::Isolate::factory(), kTagIndex, kValuesIndex, v8::internal::Isolate::native_context(), and v8::internal::Factory::NewJSObject().
New() [2/2]
DirectHandle< WasmExceptionPackage > v8::internal::WasmExceptionPackage::New (Isolate * isolate, DirectHandle< WasmExceptionTag > exception_tag, int encoded_size) [static]
Definition at line 2750 of file wasm-objects.cc.
                                                                              {
  DirectHandle<FixedArray> values = isolate->factory()->NewFixedArray(size);
  return New(isolate, exception_tag, values);
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewFixedArray(), and size().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CreateWasmExceptionPackage(), v8::internal::RUNTIME_FUNCTION(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl().
OBJECT_CONSTRUCTORS()
v8::internal::WasmExceptionPackage::OBJECT_CONSTRUCTORS (WasmExceptionPackage , JSObject)
Member Data Documentation
kSize
constexpr int v8::internal::WasmExceptionPackage::kSize [static], [constexpr]
Initial value:
=
      kHeaderSize + (kTaggedSize * kInObjectFieldCount)
Definition at line 969 of file wasm-objects.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc