v8::internal::maglev::MergePointInterpreterFrameState Class Reference
#include <maglev-interpreter-frame-state.h>
Classes
class Alternatives
struct LoopMetadata
Public Types
enum class BasicBlockType { kDefault
, kLoopHeader
, kExceptionHandlerStart
, kUnusedExceptionHandlerStart
 }
Public Member Functions
void Merge (MaglevGraphBuilder *graph_builder, InterpreterFrameState &unmerged, BasicBlock *predecessor)
void Merge (MaglevGraphBuilder *graph_builder, MaglevCompilationUnit &compilation_unit, InterpreterFrameState &unmerged, BasicBlock *predecessor)
void InitializeLoop (MaglevGraphBuilder *graph_builder, MaglevCompilationUnit &compilation_unit, InterpreterFrameState &unmerged, BasicBlock *predecessor, bool optimistic_initial_state=false, LoopEffects *loop_effects=nullptr)
void InitializeWithBasicBlock (BasicBlock *current_block)
void MergeLoop (MaglevGraphBuilder *graph_builder, InterpreterFrameState &loop_end_state, BasicBlock *loop_end_block)
void MergeLoop (MaglevGraphBuilder *graph_builder, MaglevCompilationUnit &compilation_unit, InterpreterFrameState &loop_end_state, BasicBlock *loop_end_block)
void set_loop_effects (LoopEffects *loop_effects)
const LoopEffects * loop_effects ()
bool TryMergeLoop (MaglevGraphBuilder *graph_builder, InterpreterFrameState &loop_end_state, const std::function< BasicBlock *()> &FinishBlock)
void MergeThrow (MaglevGraphBuilder *handler_builder, const MaglevCompilationUnit *handler_unit, const KnownNodeAspects &known_node_aspects, const VirtualObjectList virtual_objects)
void MergeDead (const MaglevCompilationUnit &compilation_unit, unsigned num=1)
void clear_is_loop ()
void MergeDeadLoop (const MaglevCompilationUnit &compilation_unit)
void TurnLoopIntoRegularBlock ()
void RemovePredecessorAt (int predecessor_id)
KnownNodeAspects * TakeKnownNodeAspects ()
KnownNodeAspects * CloneKnownNodeAspects (Zone *zone)
const CompactInterpreterFrameState & frame_state () const
MergePointRegisterState & register_state ()
bool has_phi () const
Phi::List * phis ()
uint32_t predecessor_count () const
uint32_t predecessors_so_far () const
BasicBlock * predecessor_at (int i) const
void set_predecessor_at (int i, BasicBlock *val)
void set_virtual_objects (const VirtualObjectList &vos)
void PrintVirtualObjects (MaglevGraphLabeller *labeller, VirtualObjectList from_ifs, const char *prelude=nullptr)
bool is_loop () const
bool exception_handler_was_used () const
bool is_exception_handler () const
bool is_unmerged_loop () const
bool is_unmerged_unreachable_loop () const
bool IsUnreachableByForwardEdge () const
bool IsUnreachable () const
BasicBlockType basic_block_type () const
bool is_resumable_loop () const
void set_is_resumable_loop (Graph *graph)
bool is_loop_with_peeled_iteration () const
int merge_offset () const
DeoptFrame * backedge_deopt_frame () const
const compiler::LoopInfo * loop_info () const
void ClearLoopInfo ()
bool HasLoopInfo () const
interpreter::Register catch_block_context_register () const
Static Public Member Functions
static MergePointInterpreterFrameState * New (const MaglevCompilationUnit &info, const InterpreterFrameState &state, int merge_offset, int predecessor_count, BasicBlock *predecessor, const compiler::BytecodeLivenessState *liveness)
static MergePointInterpreterFrameState * NewForLoop (const InterpreterFrameState &start_state, Graph *graph, const MaglevCompilationUnit &info, int merge_offset, int predecessor_count, const compiler::BytecodeLivenessState *liveness, const compiler::LoopInfo *loop_info, bool has_been_peeled=false)
static MergePointInterpreterFrameState * NewForCatchBlock (const MaglevCompilationUnit &unit, const compiler::BytecodeLivenessState *liveness, int handler_offset, bool was_used, interpreter::Register context_register, Graph *graph)
Private Types
using kBasicBlockTypeBits = base::BitField< BasicBlockType, 0, 2 >
using kIsResumableLoopBit = kBasicBlockTypeBits::Next< bool, 1 >
using kIsLoopWithPeeledIterationBit = kIsResumableLoopBit::Next< bool, 1 >
Private Member Functions
NodeType AlternativeType (const Alternatives *alt)
MergePointInterpreterFrameState (const MaglevCompilationUnit &info, int merge_offset, int predecessor_count, int predecessors_so_far, BasicBlock **predecessors, BasicBlockType type, const compiler::BytecodeLivenessState *liveness)
void MergePhis (MaglevGraphBuilder *builder, MaglevCompilationUnit &compilation_unit, InterpreterFrameState &unmerged, BasicBlock *predecessor, bool optimistic_loop_phis)
void MergeVirtualObjects (MaglevGraphBuilder *builder, MaglevCompilationUnit &compilation_unit, InterpreterFrameState &unmerged, BasicBlock *predecessor)
ValueNode * MergeValue (const MaglevGraphBuilder *graph_builder, interpreter::Register owner, const KnownNodeAspects &unmerged_aspects, ValueNode *merged, ValueNode *unmerged, Alternatives::List *per_predecessor_alternatives, bool optimistic_loop_phis=false)
void ReducePhiPredecessorCount (unsigned num)
void MergeVirtualObjects (MaglevGraphBuilder *builder, MaglevCompilationUnit &compilation_unit, const VirtualObjectList unmerged_vos, const KnownNodeAspects &unmerged_aspects)
void MergeVirtualObject (MaglevGraphBuilder *builder, const VirtualObjectList unmerged_vos, const KnownNodeAspects &unmerged_aspects, VirtualObject *merged, VirtualObject *unmerged)
std::optional< ValueNode * > MergeVirtualObjectValue (const MaglevGraphBuilder *graph_builder, const KnownNodeAspects &unmerged_aspects, ValueNode *merged, ValueNode *unmerged)
void MergeLoopValue (MaglevGraphBuilder *graph_builder, interpreter::Register owner, const KnownNodeAspects &unmerged_aspects, ValueNode *merged, ValueNode *unmerged)
ValueNode * NewLoopPhi (Zone *zone, interpreter::Register reg)
ValueNode * NewExceptionPhi (Zone *zone, interpreter::Register reg)
Private Attributes
int merge_offset_
uint32_t predecessor_count_
uint32_t predecessors_so_far_
uint32_t bitfield_
BasicBlock ** predecessors_
Phi::List phis_
CompactInterpreterFrameState frame_state_
MergePointRegisterState register_state_
KnownNodeAspects * known_node_aspects_ = nullptr
xx xx xx xx xx xx xx xx xx
union {
 Alternatives::List * per_predecessor_alternatives_
 DeoptFrame * backedge_deopt_frame_
 interpreter::Register catch_block_context_register_
};
std::optional< LoopMetadata > loop_metadata_ = std::nullopt
Friends
template<typename T , typename... Args>
T * Zone::New (Args &&... args)
Detailed Description
Definition at line 878 of file maglev-interpreter-frame-state.h.
Member Typedef Documentation
kBasicBlockTypeBits
using v8::internal::maglev::MergePointInterpreterFrameState::kBasicBlockTypeBits = base::BitField<BasicBlockType, 0, 2> [private]
Definition at line 1094 of file maglev-interpreter-frame-state.h.
kIsLoopWithPeeledIterationBit
using v8::internal::maglev::MergePointInterpreterFrameState::kIsLoopWithPeeledIterationBit = kIsResumableLoopBit::Next<bool, 1> [private]
Definition at line 1096 of file maglev-interpreter-frame-state.h.
kIsResumableLoopBit
using v8::internal::maglev::MergePointInterpreterFrameState::kIsResumableLoopBit = kBasicBlockTypeBits::Next<bool, 1> [private]
Definition at line 1095 of file maglev-interpreter-frame-state.h.
Member Enumeration Documentation
BasicBlockType
enum v8::internal::maglev::MergePointInterpreterFrameState::BasicBlockType [strong]
Enumerator
kDefault
kLoopHeader
kExceptionHandlerStart
kUnusedExceptionHandlerStart
Definition at line 880 of file maglev-interpreter-frame-state.h.
                            {
    kDefault,
    kLoopHeader,
    kExceptionHandlerStart,
    kUnusedExceptionHandlerStart,
  };
Constructor & Destructor Documentation
MergePointInterpreterFrameState()
v8::internal::maglev::MergePointInterpreterFrameState::MergePointInterpreterFrameState (const MaglevCompilationUnit & info, int merge_offset, int predecessor_count, int predecessors_so_far, BasicBlock ** predecessors, BasicBlockType type, const compiler::BytecodeLivenessState * liveness) [private]
Definition at line 554 of file maglev-interpreter-frame-state.cc.
    : merge_offset_(merge_offset),
      predecessor_count_(predecessor_count),
      predecessors_so_far_(predecessors_so_far),
      bitfield_(kBasicBlockTypeBits::encode(type)),
      predecessors_(predecessors),
      frame_state_(info, liveness),
      per_predecessor_alternatives_(
          type == BasicBlockType::kExceptionHandlerStart
              ? nullptr
              : info.zone()->AllocateArray<Alternatives::List>(
                    frame_state_.size(info))) {}
Member Function Documentation
AlternativeType()
NodeType v8::internal::maglev::MergePointInterpreterFrameState::AlternativeType (const Alternatives * alt) [private]
Definition at line 1136 of file maglev-interpreter-frame-state.cc.
                             {
  if (!alt) return NodeType::kUnknown;
  return alt->node_type();
}
References v8::internal::maglev::MergePointInterpreterFrameState::Alternatives::node_type().
Referenced by MergeValue().
backedge_deopt_frame()
DeoptFrame* v8::internal::maglev::MergePointInterpreterFrameState::backedge_deopt_frame () const [inline]
Definition at line 1076 of file maglev-interpreter-frame-state.h.
{ return backedge_deopt_frame_; }
References backedge_deopt_frame_.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo().
basic_block_type()
BasicBlockType v8::internal::maglev::MergePointInterpreterFrameState::basic_block_type () const [inline]
Definition at line 1061 of file maglev-interpreter-frame-state.h.
                                          {
    return kBasicBlockTypeBits::decode(bitfield_);
  }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by exception_handler_was_used(), is_exception_handler(), and is_loop().
catch_block_context_register()
interpreter::Register v8::internal::maglev::MergePointInterpreterFrameState::catch_block_context_register () const [inline]
Definition at line 1088 of file maglev-interpreter-frame-state.h.
                                                           {
    DCHECK(is_exception_handler());
    return catch_block_context_register_;
  }
References catch_block_context_register_, v8::internal::DCHECK(), and is_exception_handler().
Referenced by MergeValue().
clear_is_loop()
void v8::internal::maglev::MergePointInterpreterFrameState::clear_is_loop () [inline]
Definition at line 952 of file maglev-interpreter-frame-state.h.
                       {
    bitfield_ =
        kBasicBlockTypeBits::update(bitfield_, BasicBlockType::kDefault);
    bitfield_ = kIsResumableLoopBit::update(bitfield_, false);
  }
References bitfield_, kDefault, and v8::base::BitField< T, shift, size, U >::update().
Referenced by MergeDeadLoop(), and TurnLoopIntoRegularBlock().
ClearLoopInfo()
void v8::internal::maglev::MergePointInterpreterFrameState::ClearLoopInfo () [inline]
Definition at line 1083 of file maglev-interpreter-frame-state.h.
{ loop_metadata_->loop_info = nullptr; }
References loop_metadata_.
Referenced by MergeLoop(), and TryMergeLoop().
CloneKnownNodeAspects()
KnownNodeAspects* v8::internal::maglev::MergePointInterpreterFrameState::CloneKnownNodeAspects (Zone * zone) [inline]
Definition at line 987 of file maglev-interpreter-frame-state.h.
                                                      {
    return known_node_aspects_->Clone(zone);
  }
References v8::internal::maglev::KnownNodeAspects::Clone(), and known_node_aspects_.
Referenced by v8::internal::maglev::InterpreterFrameState::CopyFrom().
exception_handler_was_used()
bool v8::internal::maglev::MergePointInterpreterFrameState::exception_handler_was_used () const [inline]
Definition at line 1034 of file maglev-interpreter-frame-state.h.
                                          {
    DCHECK(is_exception_handler());
    return basic_block_type() == BasicBlockType::kExceptionHandlerStart;
  }
References basic_block_type(), v8::internal::DCHECK(), is_exception_handler(), and kExceptionHandlerStart.
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetCurrentTryCatchBlock(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
frame_state()
const CompactInterpreterFrameState& v8::internal::maglev::MergePointInterpreterFrameState::frame_state () const [inline]
Definition at line 991 of file maglev-interpreter-frame-state.h.
                                                          {
    return frame_state_;
  }
References frame_state_.
Referenced by v8::internal::maglev::InterpreterFrameState::CopyFrom(), NewForCatchBlock(), and NewForLoop().
has_phi()
bool v8::internal::maglev::MergePointInterpreterFrameState::has_phi () const [inline]
Definition at line 996 of file maglev-interpreter-frame-state.h.
{ return !phis_.is_empty(); }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::is_empty(), and phis_.
Referenced by v8::internal::maglev::BasicBlock::has_phi().
HasLoopInfo()
bool v8::internal::maglev::MergePointInterpreterFrameState::HasLoopInfo () const [inline]
Definition at line 1084 of file maglev-interpreter-frame-state.h.
                           {
    return loop_metadata_.has_value() && loop_metadata_->loop_info;
  }
References loop_metadata_.
InitializeLoop()
void v8::internal::maglev::MergePointInterpreterFrameState::InitializeLoop (MaglevGraphBuilder * graph_builder, MaglevCompilationUnit & compilation_unit, InterpreterFrameState & unmerged, BasicBlock * predecessor, bool optimistic_initial_state = false, LoopEffects * loop_effects = nullptr)
Definition at line 737 of file maglev-interpreter-frame-state.cc.
                                                              {
  DCHECK_IMPLIES(optimistic_initial_state,
                 v8_flags.maglev_optimistic_peeled_loops);
  DCHECK_GT(predecessor_count_, 1);
  DCHECK_EQ(predecessors_so_far_, 0);
  predecessors_[predecessors_so_far_] = predecessor;
  DCHECK_NULL(known_node_aspects_);
  DCHECK(is_unmerged_loop());
  DCHECK_EQ(predecessors_so_far_, 0);
  known_node_aspects_ = unmerged.known_node_aspects()->CloneForLoopHeader(
      optimistic_initial_state, loop_effects, builder->zone());
  unmerged.virtual_objects().Snapshot();
  frame_state_.set_virtual_objects(unmerged.virtual_objects());
  if (v8_flags.trace_maglev_graph_building) {
    std::cout << "Initializing "
              << (optimistic_initial_state ? "optimistic " : "")
              << "loop state..." << std::endl;
  }
  MergePhis(builder, compilation_unit, unmerged, predecessor,
            optimistic_initial_state);
  predecessors_so_far_ = 1;
}
References v8::internal::maglev::KnownNodeAspects::CloneForLoopHeader(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, DCHECK_IMPLIES, DCHECK_NULL, frame_state_, is_unmerged_loop(), v8::internal::maglev::InterpreterFrameState::known_node_aspects(), known_node_aspects_, loop_effects(), MergePhis(), predecessor_count_, predecessors_, predecessors_so_far_, v8::internal::maglev::CompactInterpreterFrameState::set_virtual_objects(), v8::internal::maglev::VirtualObjectList::Snapshot(), v8::internal::v8_flags, v8::internal::maglev::InterpreterFrameState::virtual_objects(), and v8::internal::maglev::MaglevGraphBuilder::zone().
Referenced by Merge().
InitializeWithBasicBlock()
void v8::internal::maglev::MergePointInterpreterFrameState::InitializeWithBasicBlock (BasicBlock * current_block)
Definition at line 766 of file maglev-interpreter-frame-state.cc.
                       {
  for (Phi* phi : phis_) {
    phi->set_owner(block);
  }
}
References phis_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::StartNewBlock().
is_exception_handler()
bool v8::internal::maglev::MergePointInterpreterFrameState::is_exception_handler () const [inline]
Definition at line 1039 of file maglev-interpreter-frame-state.h.
                                    {
    return basic_block_type() == BasicBlockType::kExceptionHandlerStart ||
           basic_block_type() == BasicBlockType::kUnusedExceptionHandlerStart;
  }
References basic_block_type(), kExceptionHandlerStart, and kUnusedExceptionHandlerStart.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), catch_block_context_register(), exception_handler_was_used(), v8::internal::maglev::BasicBlock::is_exception_handler_block(), IsUnreachable(), MergeThrow(), MergeValue(), MergeVirtualObjectValue(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
is_loop()
bool v8::internal::maglev::MergePointInterpreterFrameState::is_loop () const [inline]
Definition at line 1030 of file maglev-interpreter-frame-state.h.
                       {
    return basic_block_type() == BasicBlockType::kLoopHeader;
  }
References basic_block_type(), and kLoopHeader.
Referenced by v8::internal::maglev::BasicBlock::is_loop(), v8::internal::maglev::Phi::is_loop_phi(), is_resumable_loop(), is_unmerged_loop(), IsUnreachableByForwardEdge(), loop_effects(), MergeVirtualObjectValue(), v8::internal::maglev::LiveRangeAndNextUseProcessor::PreProcessBasicBlock(), v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointPredecessors(), set_loop_effects(), TurnLoopIntoRegularBlock(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
is_loop_with_peeled_iteration()
bool v8::internal::maglev::MergePointInterpreterFrameState::is_loop_with_peeled_iteration () const [inline]
Definition at line 1070 of file maglev-interpreter-frame-state.h.
                                             {
    return kIsLoopWithPeeledIterationBit::decode(bitfield_);
  }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), and v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi().
is_resumable_loop()
bool v8::internal::maglev::MergePointInterpreterFrameState::is_resumable_loop () const [inline]
Definition at line 1064 of file maglev-interpreter-frame-state.h.
                                 {
    bool res = kIsResumableLoopBit::decode(bitfield_);
    DCHECK_IMPLIES(res, is_loop());
    return res;
  }
References bitfield_, DCHECK_IMPLIES, v8::base::BitField< T, shift, size, U >::decode(), and is_loop().
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::CanHoistUntaggingTo(), is_unmerged_unreachable_loop(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsLiveAtTarget(), IsUnreachable(), NewForLoop(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
is_unmerged_loop()
bool v8::internal::maglev::MergePointInterpreterFrameState::is_unmerged_loop () const [inline]
Definition at line 1044 of file maglev-interpreter-frame-state.h.
                                {
    // If this is a loop and not all predecessors are set, then the loop isn't
    // merged yet.
    DCHECK_IMPLIES(is_loop(), predecessor_count_ > 0);
    return is_loop() && predecessors_so_far_ < predecessor_count_;
  }
References DCHECK_IMPLIES, is_loop(), predecessor_count_, and predecessors_so_far_.
Referenced by InitializeLoop(), v8::internal::maglev::Phi::is_unmerged_loop_phi(), is_unmerged_unreachable_loop(), MergeDeadLoop(), MergeLoop(), MergeValue(), v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointPredecessors(), and TryMergeLoop().
is_unmerged_unreachable_loop()
bool v8::internal::maglev::MergePointInterpreterFrameState::is_unmerged_unreachable_loop () const [inline]
Definition at line 1051 of file maglev-interpreter-frame-state.h.
                                            {
    // If there is only one predecessor, and it's not set, then this is a loop
    // merge with no forward control flow entering it.
    return is_unmerged_loop() && !is_resumable_loop() &&
           predecessor_count_ == 1 && predecessors_so_far_ == 0;
  }
References is_resumable_loop(), is_unmerged_loop(), predecessor_count_, and predecessors_so_far_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
IsUnreachable()
bool v8::internal::maglev::MergePointInterpreterFrameState::IsUnreachable () const
Definition at line 1481 of file maglev-interpreter-frame-state.cc.
                                                          {
  if (is_exception_handler()) return false;
  if (is_resumable_loop()) return false;
  return IsUnreachableByForwardEdge();
}
References is_exception_handler(), is_resumable_loop(), and IsUnreachableByForwardEdge().
IsUnreachableByForwardEdge()
bool v8::internal::maglev::MergePointInterpreterFrameState::IsUnreachableByForwardEdge () const
Definition at line 1463 of file maglev-interpreter-frame-state.cc.
                                                                       {
  DCHECK_EQ(predecessors_so_far_, predecessor_count_);
  DCHECK_IMPLIES(
      is_loop(),
      predecessor_at(predecessor_count_ - 1)->control_node()->Is<JumpLoop>());
  switch (predecessor_count_) {
    case 0:
      // This happens after the back-edge of a resumable loop died at which
      // point we mark it non-looping.
      DCHECK(!is_loop());
      return true;
    case 1:
      return is_loop();
    default:
      return false;
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, is_loop(), predecessor_at(), predecessor_count_, and predecessors_so_far_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), and IsUnreachable().
loop_effects()
const LoopEffects * v8::internal::maglev::MergePointInterpreterFrameState::loop_effects ()
Definition at line 926 of file maglev-interpreter-frame-state.cc.
                                                                 {
  DCHECK(is_loop());
  DCHECK(loop_metadata_.has_value());
  return loop_metadata_->loop_effects;
}
References v8::internal::DCHECK(), is_loop(), and loop_metadata_.
Referenced by InitializeLoop(), v8::internal::maglev::LoopOptimizationProcessor::PreProcessBasicBlock(), and set_loop_effects().
loop_info()
const compiler::LoopInfo* v8::internal::maglev::MergePointInterpreterFrameState::loop_info () const [inline]
Definition at line 1078 of file maglev-interpreter-frame-state.h.
                                            {
    DCHECK(loop_metadata_.has_value());
    DCHECK_NOT_NULL(loop_metadata_->loop_info);
    return loop_metadata_->loop_info;
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, and loop_metadata_.
Referenced by NewForLoop().
Merge() [1/2]
void v8::internal::maglev::MergePointInterpreterFrameState::Merge (MaglevGraphBuilder * graph_builder, InterpreterFrameState & unmerged, BasicBlock * predecessor)
Definition at line 615 of file maglev-interpreter-frame-state.cc.
                                                                     {
  Merge(builder, *builder->compilation_unit(), unmerged, predecessor);
}
References v8::internal::maglev::MaglevGraphBuilder::compilation_unit().
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::MergeIntoLabel(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
Merge() [2/2]
void v8::internal::maglev::MergePointInterpreterFrameState::Merge (MaglevGraphBuilder * graph_builder, MaglevCompilationUnit & compilation_unit, InterpreterFrameState & unmerged, BasicBlock * predecessor)
Definition at line 773 of file maglev-interpreter-frame-state.cc.
                                                              {
  DCHECK_GT(predecessor_count_, 1);
  DCHECK_LT(predecessors_so_far_, predecessor_count_);
  predecessors_[predecessors_so_far_] = predecessor;
  if (known_node_aspects_ == nullptr) {
    return InitializeLoop(builder, compilation_unit, unmerged, predecessor);
  }
  known_node_aspects_->Merge(*unmerged.known_node_aspects(), builder->zone());
  if (v8_flags.trace_maglev_graph_building) {
    std::cout << "Merging..." << std::endl;
  }
  MergeVirtualObjects(builder, compilation_unit, unmerged.virtual_objects(),
                      *unmerged.known_node_aspects());
  MergePhis(builder, compilation_unit, unmerged, predecessor, false);
  predecessors_so_far_++;
  DCHECK_LE(predecessors_so_far_, predecessor_count_);
}
References DCHECK_GT, DCHECK_LE, DCHECK_LT, InitializeLoop(), v8::internal::maglev::InterpreterFrameState::known_node_aspects(), known_node_aspects_, v8::internal::maglev::KnownNodeAspects::Merge(), MergePhis(), MergeVirtualObjects(), predecessor_count_, predecessors_, predecessors_so_far_, v8::internal::v8_flags, v8::internal::maglev::InterpreterFrameState::virtual_objects(), and v8::internal::maglev::MaglevGraphBuilder::zone().
merge_offset()
int v8::internal::maglev::MergePointInterpreterFrameState::merge_offset () const [inline]
Definition at line 1074 of file maglev-interpreter-frame-state.h.
{ return merge_offset_; }
References merge_offset_.
Referenced by New(), and NewForLoop().
MergeDead()
void v8::internal::maglev::MergePointInterpreterFrameState::MergeDead (const MaglevCompilationUnit & compilation_unit, unsigned num = 1) [inline]
Definition at line 943 of file maglev-interpreter-frame-state.h.
                                   {
    DCHECK_GE(predecessor_count_, num);
    DCHECK_LT(predecessors_so_far_, predecessor_count_);
    ReducePhiPredecessorCount(num);
    predecessor_count_ -= num;
    DCHECK_LE(predecessors_so_far_, predecessor_count_);
  }
References DCHECK_GE, DCHECK_LE, DCHECK_LT, predecessor_count_, predecessors_so_far_, and ReducePhiPredecessorCount().
Referenced by v8::internal::maglev::MaglevGraphBuilder::KillPeeledLoopTargets(), MergeDeadLoop(), and v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::ReducePredecessorCount().
MergeDeadLoop()
void v8::internal::maglev::MergePointInterpreterFrameState::MergeDeadLoop (const MaglevCompilationUnit & compilation_unit) [inline]
Definition at line 960 of file maglev-interpreter-frame-state.h.
                                                                    {
    // This should be the last predecessor we try to merge.
    DCHECK_EQ(predecessors_so_far_, predecessor_count_ - 1);
    DCHECK(is_unmerged_loop());
    MergeDead(compilation_unit);
    // This means that this is no longer a loop.
    clear_is_loop();
  }
References clear_is_loop(), v8::internal::DCHECK(), DCHECK_EQ, is_unmerged_loop(), MergeDead(), predecessor_count_, and predecessors_so_far_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::EndLoop().
MergeLoop() [1/2]
void v8::internal::maglev::MergePointInterpreterFrameState::MergeLoop (MaglevGraphBuilder * graph_builder, InterpreterFrameState & loop_end_state, BasicBlock * loop_end_block)
Definition at line 797 of file maglev-interpreter-frame-state.cc.
                                {
  MergeLoop(builder, *builder->compilation_unit(), loop_end_state,
            loop_end_block);
}
References v8::internal::maglev::MaglevGraphBuilder::compilation_unit().
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::EndLoop().
MergeLoop() [2/2]
void v8::internal::maglev::MergePointInterpreterFrameState::MergeLoop (MaglevGraphBuilder * graph_builder, MaglevCompilationUnit & compilation_unit, InterpreterFrameState & loop_end_state, BasicBlock * loop_end_block)
Definition at line 804 of file maglev-interpreter-frame-state.cc.
                                                                       {
  // This should be the last predecessor we try to merge.
  DCHECK_EQ(predecessors_so_far_, predecessor_count_ - 1);
  DCHECK(is_unmerged_loop());
  predecessors_[predecessor_count_ - 1] = loop_end_block;
  backedge_deopt_frame_ =
      builder->zone()->New<DeoptFrame>(builder->GetLatestCheckpointedFrame());
  if (v8_flags.trace_maglev_graph_building) {
    std::cout << "Merging loop backedge..." << std::endl;
  }
  frame_state_.ForEachValue(
      compilation_unit, [&](ValueNode* value, interpreter::Register reg) {
        PrintBeforeMerge(builder->graph_labeller(), value,
                         loop_end_state.get(reg), reg, known_node_aspects_);
        MergeLoopValue(builder, reg, *loop_end_state.known_node_aspects(),
                       value, loop_end_state.get(reg));
        PrintAfterMerge(builder->graph_labeller(), value, known_node_aspects_);
      });
  predecessors_so_far_++;
  DCHECK_EQ(predecessors_so_far_, predecessor_count_);
  // We have to clear the LoopInfo (which is used to record more precise use
  // hints for Phis) for 2 reasons:
  //
  // - Phi::RecordUseReprHint checks if a use is inside the loop defining the
  // Phi by checking if the LoopInfo of the loop Phi "Contains" the current
  // bytecode offset, but this will be wrong if the Phi is in a function that
  // was inlined (because the LoopInfo contains the first and last bytecode
  // offset of the loop **in its own function**).
  //
  // - LoopInfo is obtained from the {header_to_info_} member of
  // BytecodeAnalysis, but the BytecodeAnalysis is a member of the
  // MaglevGraphBuilder, and thus gets destructed when the MaglevGraphBuilder
  // created for inlining is destructed. LoopInfo would then become a stale
  // pointer.
  ClearLoopInfo();
}
References backedge_deopt_frame_, ClearLoopInfo(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::CompactInterpreterFrameState::ForEachValue(), frame_state_, v8::internal::maglev::InterpreterFrameState::get(), v8::internal::maglev::MaglevGraphBuilder::GetLatestCheckpointedFrame(), v8::internal::maglev::MaglevGraphBuilder::graph_labeller(), is_unmerged_loop(), v8::internal::maglev::InterpreterFrameState::known_node_aspects(), known_node_aspects_, MergeLoopValue(), v8::internal::Zone::New(), predecessor_count_, predecessors_, predecessors_so_far_, v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::PrintAfterMerge(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::PrintBeforeMerge(), v8::internal::v8_flags, v8::internal::value, and v8::internal::maglev::MaglevGraphBuilder::zone().
MergeLoopValue()
void v8::internal::maglev::MergePointInterpreterFrameState::MergeLoopValue (MaglevGraphBuilder * graph_builder, interpreter::Register owner, const KnownNodeAspects & unmerged_aspects, ValueNode * merged, ValueNode * unmerged) [private]
Definition at line 1404 of file maglev-interpreter-frame-state.cc.
                         {
  Phi* result = merged->TryCast<Phi>();
  if (result == nullptr || result->merge_state() != this) {
    // Not a loop phi, we don't have to do anything.
    return;
  }
  DCHECK_EQ(result->owner(), owner);
  NodeType type = unmerged_aspects.GetType(builder->broker(), unmerged);
  unmerged = EnsureTagged(builder, unmerged_aspects, unmerged,
                          predecessors_[predecessors_so_far_]);
  result->set_input(predecessor_count_ - 1, unmerged);
  result->merge_post_loop_type(type);
  // We've just merged the backedge, which means that future uses of this Phi
  // will be after the loop, so we can now promote `post_loop_type` to the
  // regular `type`.
  DCHECK_EQ(predecessors_so_far_, predecessor_count_ - 1);
  result->promote_post_loop_type();
  if (Phi* unmerged_phi = unmerged->TryCast<Phi>()) {
    // Propagating the `uses_repr` from {result} to {unmerged_phi}.
    builder->RecordUseReprHint(unmerged_phi, result->get_uses_repr_hints());
    // Soundness of the loop phi Smi type relies on the back-edge static types
    // sminess.
    if (result->uses_require_31_bit_value()) {
      unmerged_phi->SetUseRequires31BitValue();
    }
  }
}
References v8::internal::maglev::MaglevGraphBuilder::broker(), DCHECK_EQ, v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::EnsureTagged(), v8::internal::maglev::KnownNodeAspects::GetType(), predecessor_count_, predecessors_, predecessors_so_far_, v8::internal::maglev::MaglevGraphBuilder::RecordUseReprHint(), v8::base::internal::result, v8::internal::maglev::NodeBase::TryCast(), and v8::internal::tracing::type.
Referenced by MergeLoop(), and TryMergeLoop().
MergePhis()
void v8::internal::maglev::MergePointInterpreterFrameState::MergePhis (MaglevGraphBuilder * builder, MaglevCompilationUnit & compilation_unit, InterpreterFrameState & unmerged, BasicBlock * predecessor, bool optimistic_loop_phis) [private]
Definition at line 621 of file maglev-interpreter-frame-state.cc.
                               {
  int i = 0;
  frame_state_.ForEachValue(
      compilation_unit, [&](ValueNode*& value, interpreter::Register reg) {
        PrintBeforeMerge(builder->graph_labeller(), value, unmerged.get(reg),
                         reg, known_node_aspects_);
        value = MergeValue(builder, reg, *unmerged.known_node_aspects(), value,
                           unmerged.get(reg), &per_predecessor_alternatives_[i],
                           optimistic_loop_phis);
        PrintAfterMerge(builder->graph_labeller(), value, known_node_aspects_);
        ++i;
      });
}
References v8::internal::maglev::CompactInterpreterFrameState::ForEachValue(), frame_state_, v8::internal::maglev::InterpreterFrameState::get(), v8::internal::maglev::MaglevGraphBuilder::graph_labeller(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::InterpreterFrameState::known_node_aspects(), known_node_aspects_, MergeValue(), per_predecessor_alternatives_, v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::PrintAfterMerge(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::PrintBeforeMerge(), and v8::internal::value.
Referenced by InitializeLoop(), and Merge().
MergeThrow()
void v8::internal::maglev::MergePointInterpreterFrameState::MergeThrow (MaglevGraphBuilder * handler_builder, const MaglevCompilationUnit * handler_unit, const KnownNodeAspects & known_node_aspects, const VirtualObjectList virtual_objects)
Definition at line 932 of file maglev-interpreter-frame-state.cc.
                                             {
  // We don't count total predecessors on exception handlers, but we do want to
  // special case the first predecessor so we do count predecessors_so_far
  DCHECK_EQ(predecessor_count_, 0);
  DCHECK(is_exception_handler());
  DCHECK_EQ(builder->compilation_unit(), handler_unit);
  const InterpreterFrameState& builder_frame =
      builder->current_interpreter_frame();
  if (v8_flags.trace_maglev_graph_building) {
    std::cout << "- Merging into exception handler @" << this << std::endl;
    PrintVirtualObjects(builder->graph_labeller(), virtual_objects);
  }
  if (known_node_aspects_ == nullptr) {
    DCHECK_EQ(predecessors_so_far_, 0);
    known_node_aspects_ = known_node_aspects.Clone(builder->zone());
    virtual_objects.Snapshot();
    frame_state_.set_virtual_objects(virtual_objects);
  } else {
    known_node_aspects_->Merge(known_node_aspects, builder->zone());
    MergeVirtualObjects(builder, *builder->compilation_unit(), virtual_objects,
                        known_node_aspects);
  }
  frame_state_.ForEachParameter(
      *handler_unit, [&](ValueNode*& value, interpreter::Register reg) {
        PrintBeforeMerge(builder->graph_labeller(), value,
                         builder_frame.get(reg), reg, known_node_aspects_);
        value = MergeValue(builder, reg, known_node_aspects, value,
                           builder_frame.get(reg), nullptr);
        PrintAfterMerge(builder->graph_labeller(), value, known_node_aspects_);
      });
  frame_state_.ForEachLocal(
      *handler_unit, [&](ValueNode*& value, interpreter::Register reg) {
        PrintBeforeMerge(builder->graph_labeller(), value,
                         builder_frame.get(reg), reg, known_node_aspects_);
        value = MergeValue(builder, reg, known_node_aspects, value,
                           builder_frame.get(reg), nullptr);
        PrintAfterMerge(builder->graph_labeller(), value, known_node_aspects_);
      });
  // Pick out the context value from the incoming registers.
  // TODO(leszeks): This should be the same for all incoming states, but we lose
  // the identity for generator-restored context. If generator value restores
  // were handled differently, we could avoid emitting a Phi here.
  ValueNode*& context = frame_state_.context(*handler_unit);
  PrintBeforeMerge(builder->graph_labeller(), context,
                   builder_frame.get(catch_block_context_register_),
                   catch_block_context_register_, known_node_aspects_);
  context = MergeValue(
      builder, catch_block_context_register_, known_node_aspects, context,
      builder_frame.get(catch_block_context_register_), nullptr);
  PrintAfterMerge(builder->graph_labeller(), context, known_node_aspects_);
  predecessors_so_far_++;
}
References catch_block_context_register_, v8::internal::maglev::KnownNodeAspects::Clone(), v8::internal::maglev::MaglevGraphBuilder::compilation_unit(), v8::internal::maglev::CompactInterpreterFrameState::context(), v8::internal::maglev::MaglevGraphBuilder::current_interpreter_frame(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::CompactInterpreterFrameState::ForEachLocal(), v8::internal::maglev::CompactInterpreterFrameState::ForEachParameter(), frame_state_, v8::internal::maglev::InterpreterFrameState::get(), v8::internal::maglev::MaglevGraphBuilder::graph_labeller(), is_exception_handler(), known_node_aspects_, v8::internal::maglev::KnownNodeAspects::Merge(), MergeValue(), MergeVirtualObjects(), predecessor_count_, predecessors_so_far_, v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::PrintAfterMerge(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::PrintBeforeMerge(), PrintVirtualObjects(), v8::internal::maglev::CompactInterpreterFrameState::set_virtual_objects(), v8::internal::maglev::VirtualObjectList::Snapshot(), v8::internal::v8_flags, v8::internal::value, and v8::internal::maglev::MaglevGraphBuilder::zone().
MergeValue()
ValueNode * v8::internal::maglev::MergePointInterpreterFrameState::MergeValue (const MaglevGraphBuilder * graph_builder, interpreter::Register owner, const KnownNodeAspects & unmerged_aspects, ValueNode * merged, ValueNode * unmerged, Alternatives::List * per_predecessor_alternatives, bool optimistic_loop_phis = false) [private]
Definition at line 1142 of file maglev-interpreter-frame-state.cc.
                               {
  // If the merged node is null, this is a pre-created loop header merge
  // frame will null values for anything that isn't a loop Phi.
  if (merged == nullptr) {
    DCHECK(is_exception_handler() || is_unmerged_loop());
    DCHECK_EQ(predecessors_so_far_, 0);
    // Initialise the alternatives list and cache the alternative
    // representations of the node.
    if (per_predecessor_alternatives) {
      new (per_predecessor_alternatives) Alternatives::List();
      per_predecessor_alternatives->Add(builder->zone()->New<Alternatives>(
          unmerged_aspects.TryGetInfoFor(unmerged)));
    } else {
      DCHECK(is_exception_handler());
    }
    return unmerged;
  }
  auto UpdateLoopPhiType = [&](Phi* result, NodeType unmerged_type) {
    DCHECK(result->is_loop_phi());
    if (predecessors_so_far_ == 0) {
      // For loop Phis, `type` is always Unknown until the backedge has been
      // bound, so there is no point in updating it here.
      result->set_post_loop_type(unmerged_type);
      if (optimistic_loop_phis) {
        // In the case of optimistic loop headers we try to speculatively use
        // the type of the incomming argument as the phi type. We verify if that
        // happened to be true before allowing the loop to conclude in
        // `TryMergeLoop`. Some types which are known to cause issues are
        // generalized here.
        NodeType initial_optimistic_type = unmerged_type;
        if (!IsEmptyNodeType(IntersectType(unmerged_type, NodeType::kString))) {
          // Make sure we don't depend on something being an internalized string
          // in particular, by making the type cover all String subtypes.
          initial_optimistic_type = UnionType(unmerged_type, NodeType::kString);
        }
        result->set_type(initial_optimistic_type);
      }
    } else {
      if (optimistic_loop_phis) {
        if (NodeInfo* node_info = known_node_aspects_->TryGetInfoFor(result)) {
          node_info->UnionType(unmerged_type);
        }
        result->merge_type(unmerged_type);
      }
      result->merge_post_loop_type(unmerged_type);
    }
  };
  Phi* result = merged->TryCast<Phi>();
  if (result != nullptr && result->merge_state() == this) {
    // It's possible that merged == unmerged at this point since loop-phis are
    // not dropped if they are only assigned to themselves in the loop.
    DCHECK_EQ(result->owner(), owner);
    // Don't set inputs on exception phis.
    DCHECK_EQ(result->is_exception_phi(), is_exception_handler());
    if (is_exception_handler()) {
      // If an inlined allocation flows to an exception phi, we should consider
      // as an use.
      if (unmerged->Is<InlinedAllocation>()) {
        unmerged->add_use();
      }
      return result;
    }
    NodeType unmerged_type =
        unmerged_aspects.GetType(builder->broker(), unmerged);
    if (result->is_loop_phi()) {
      UpdateLoopPhiType(result, unmerged_type);
    } else {
      result->merge_type(unmerged_type);
    }
    unmerged = EnsureTagged(builder, unmerged_aspects, unmerged,
                            predecessors_[predecessors_so_far_]);
    result->set_input(predecessors_so_far_, unmerged);
    return result;
  }
  if (merged == unmerged) {
    // Cache the alternative representations of the unmerged node.
    if (per_predecessor_alternatives) {
      DCHECK_EQ(per_predecessor_alternatives->LengthForTest(),
                predecessors_so_far_);
      per_predecessor_alternatives->Add(builder->zone()->New<Alternatives>(
          unmerged_aspects.TryGetInfoFor(unmerged)));
    } else {
      DCHECK(is_exception_handler());
    }
    return merged;
  }
  // We should always statically know what the context is, so we should never
  // create Phis for it. The exception is resumable functions and OSR, where the
  // context should be statically known but we lose that static information
  // across the resume / OSR entry.
  DCHECK_IMPLIES(
      owner == interpreter::Register::current_context() ||
          (is_exception_handler() && owner == catch_block_context_register()),
      IsResumableFunction(builder->compilation_unit()
                              ->info()
                              ->toplevel_compilation_unit()
                              ->shared_function_info()
                              .kind()) ||
          builder->compilation_unit()->info()->toplevel_is_osr());
  // Up to this point all predecessors had the same value for this interpreter
  // frame slot. Now that we find a distinct value, insert a copy of the first
  // value for each predecessor seen so far, in addition to the new value.
  // TODO(verwaest): Unclear whether we want this for Maglev: Instead of
  // letting the register allocator remove phis, we could always merge through
  // the frame slot. In that case we only need the inputs for representation
  // selection, and hence could remove duplicate inputs. We'd likely need to
  // attach the interpreter register to the phi in that case?
  // For exception phis, just allocate exception handlers.
  if (is_exception_handler()) {
    // ... and add an use if inputs are inlined allocation.
    if (merged->Is<InlinedAllocation>()) {
      merged->add_use();
    }
    if (unmerged->Is<InlinedAllocation>()) {
      unmerged->add_use();
    }
    return NewExceptionPhi(builder->zone(), owner);
  }
  result = Node::New<Phi>(builder->zone(), predecessor_count_, this, owner);
  if (v8_flags.trace_maglev_graph_building) {
    for (uint32_t i = 0; i < predecessor_count_; i++) {
      result->initialize_input_null(i);
    }
  }
  NodeType merged_type = merged->GetStaticType(builder->broker());
  bool is_tagged = merged->properties().value_representation() ==
                   ValueRepresentation::kTagged;
  NodeType type = merged_type != NodeType::kUnknown
                      ? merged_type
                      : AlternativeType(per_predecessor_alternatives->first());
  int i = 0;
  for (const Alternatives* alt : *per_predecessor_alternatives) {
    ValueNode* tagged = is_tagged ? merged : alt->tagged_alternative();
    if (tagged == nullptr) {
      DCHECK_NOT_NULL(alt);
      tagged = NonTaggedToTagged(builder, alt->node_type(), merged,
                                 predecessors_[i]);
    }
    result->set_input(i, tagged);
    type = UnionType(type, merged_type != NodeType::kUnknown
                               ? merged_type
                               : AlternativeType(alt));
    i++;
  }
  DCHECK_EQ(i, predecessors_so_far_);
  // Note: it's better to call GetType on {unmerged} before updating it with
  // EnsureTagged, since untagged nodes have a higher chance of having a
  // StaticType.
  NodeType unmerged_type =
      unmerged_aspects.GetType(builder->broker(), unmerged);
  unmerged = EnsureTagged(builder, unmerged_aspects, unmerged,
                          predecessors_[predecessors_so_far_]);
  result->set_input(predecessors_so_far_, unmerged);
  if (result->is_loop_phi()) {
    DCHECK(result->is_unmerged_loop_phi());
    UpdateLoopPhiType(result, type);
  } else {
    result->set_type(UnionType(type, unmerged_type));
  }
  phis_.Add(result);
  return result;
}
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Add(), v8::internal::maglev::ValueNode::add_use(), AlternativeType(), v8::internal::maglev::MaglevGraphBuilder::broker(), catch_block_context_register(), v8::internal::maglev::MaglevGraphBuilder::compilation_unit(), v8::internal::interpreter::Register::current_context(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NOT_NULL, v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::EnsureTagged(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::first(), v8::internal::maglev::ValueNode::GetStaticType(), v8::internal::maglev::KnownNodeAspects::GetType(), v8::internal::maglev::MaglevCompilationUnit::info(), v8::internal::maglev::IntersectType(), v8::internal::maglev::NodeBase::Is(), is_exception_handler(), is_unmerged_loop(), v8::internal::maglev::IsEmptyNodeType(), v8::internal::IsResumableFunction(), known_node_aspects_, v8::internal::maglev::kTagged, v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::LengthForTest(), v8::internal::Zone::New(), NewExceptionPhi(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NonTaggedToTagged(), phis_, predecessor_count_, predecessors_, predecessors_so_far_, v8::internal::maglev::NodeBase::properties(), v8::base::internal::result, v8::internal::maglev::MaglevCompilationUnit::shared_function_info(), v8::internal::maglev::MaglevCompilationInfo::toplevel_compilation_unit(), v8::internal::maglev::MaglevCompilationInfo::toplevel_is_osr(), v8::internal::maglev::NodeBase::TryCast(), v8::internal::maglev::KnownNodeAspects::TryGetInfoFor(), v8::internal::tracing::type, v8::internal::maglev::UnionType(), v8::internal::v8_flags, v8::internal::maglev::OpProperties::value_representation(), and v8::internal::maglev::MaglevGraphBuilder::zone().
Referenced by MergePhis(), and MergeThrow().
MergeVirtualObject()
void v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObject (MaglevGraphBuilder * builder, const VirtualObjectList unmerged_vos, const KnownNodeAspects & unmerged_aspects, VirtualObject * merged, VirtualObject * unmerged) [private]
Definition at line 638 of file maglev-interpreter-frame-state.cc.
                             {
  if (merged == unmerged) {
    // No need to merge.
    return;
  }
  DCHECK(unmerged->compatible_for_merge(merged));
  if (v8_flags.trace_maglev_graph_building) {
    std::cout << " - Merging VOS: "
              << PrintNodeLabel(builder->graph_labeller(), merged)
              << "(merged) and "
              << PrintNodeLabel(builder->graph_labeller(), unmerged)
              << "(unmerged)" << std::endl;
  }
  auto maybe_result = merged->Merge(
      unmerged, builder->NewObjectId(), builder->zone(),
      [&](ValueNode* a, ValueNode* b) {
        return MergeVirtualObjectValue(builder, unmerged_aspects, a, b);
      });
  if (!maybe_result) {
    return unmerged->allocation()->ForceEscaping();
  }
  VirtualObject* result = *maybe_result;
  result->set_allocation(unmerged->allocation());
  result->Snapshot();
  unmerged->allocation()->UpdateObject(result);
  frame_state_.virtual_objects().Add(result);
}
References v8::internal::maglev::VirtualObjectList::Add(), v8::internal::maglev::VirtualObject::allocation(), v8::internal::maglev::VirtualObject::compatible_for_merge(), v8::internal::DCHECK(), v8::internal::maglev::InlinedAllocation::ForceEscaping(), frame_state_, v8::internal::maglev::MaglevGraphBuilder::graph_labeller(), v8::internal::maglev::VirtualObject::Merge(), v8::internal::maglev::MaglevGraphBuilder::NewObjectId(), v8::base::internal::result, v8::internal::maglev::InlinedAllocation::UpdateObject(), v8::internal::v8_flags, v8::internal::maglev::CompactInterpreterFrameState::virtual_objects(), and v8::internal::maglev::MaglevGraphBuilder::zone().
Referenced by MergeVirtualObjects().
MergeVirtualObjects() [1/2]
void v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjects (MaglevGraphBuilder * builder, MaglevCompilationUnit & compilation_unit, const VirtualObjectList unmerged_vos, const KnownNodeAspects & unmerged_aspects) [private]
Definition at line 671 of file maglev-interpreter-frame-state.cc.
                                              {
  if (frame_state_.virtual_objects().is_empty()) return;
  if (unmerged_vos.is_empty()) return;
  frame_state_.virtual_objects().Snapshot();
  PrintVirtualObjects(builder->graph_labeller(), unmerged_vos,
                      "VOs before merge:");
  SmallZoneMap<InlinedAllocation*, VirtualObject*, 10> unmerged_map(
      builder->zone());
  SmallZoneMap<InlinedAllocation*, VirtualObject*, 10> merged_map(
      builder->zone());
  // We iterate both list in reversed order of ids collecting the umerged
  // objects into the map, until we find a common virtual object.
  VirtualObjectList::WalkUntilCommon(
      frame_state_.virtual_objects(), unmerged_vos,
      [&](VirtualObject* vo, VirtualObjectList vos) {
        // If we have a version in the map, it should be the most up-to-date,
        // since the list is in reverse order.
        auto& map = unmerged_vos == vos ? unmerged_map : merged_map;
        map.emplace(vo->allocation(), vo);
      });
  // Walk the merged map (values from the merged state) and merge values.
  for (auto [_, merged] : merged_map) {
    VirtualObject* unmerged = nullptr;
    auto it = unmerged_map.find(merged->allocation());
    if (it != unmerged_map.end()) {
      unmerged = it->second;
      unmerged_map.erase(it);
    } else {
      unmerged = unmerged_vos.FindAllocatedWith(merged->allocation());
    }
    if (unmerged != nullptr) {
      MergeVirtualObject(builder, unmerged_vos, unmerged_aspects, merged,
                         unmerged);
    }
  }
  // Walk the unmerged map (values from the interpreter frame state) and merge
  // values. If the value was already merged, we would have removed from the
  // unmerged_map.
  for (auto [_, unmerged] : unmerged_map) {
    VirtualObject* merged = nullptr;
    auto it = merged_map.find(unmerged->allocation());
    if (it != merged_map.end()) {
      merged = it->second;
    } else {
      merged = frame_state_.virtual_objects().FindAllocatedWith(
          unmerged->allocation());
    }
    if (merged != nullptr) {
      MergeVirtualObject(builder, unmerged_vos, unmerged_aspects, merged,
                         unmerged);
    }
  }
  PrintVirtualObjects(builder->graph_labeller(), unmerged_vos,
                      "VOs after merge:");
}
References _, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::end(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::erase(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::find(), v8::internal::maglev::VirtualObjectList::FindAllocatedWith(), frame_state_, v8::internal::maglev::MaglevGraphBuilder::graph_labeller(), v8::internal::maglev::VirtualObjectList::is_empty(), MergeVirtualObject(), PrintVirtualObjects(), v8::internal::maglev::VirtualObjectList::Snapshot(), v8::internal::maglev::CompactInterpreterFrameState::virtual_objects(), v8::internal::maglev::VirtualObjectList::WalkUntilCommon(), and v8::internal::maglev::MaglevGraphBuilder::zone().
MergeVirtualObjects() [2/2]
void v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjects (MaglevGraphBuilder * builder, MaglevCompilationUnit & compilation_unit, InterpreterFrameState & unmerged, BasicBlock * predecessor) [private]
Referenced by Merge(), and MergeThrow().
MergeVirtualObjectValue()
std::optional< ValueNode * > v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjectValue (const MaglevGraphBuilder * graph_builder, const KnownNodeAspects & unmerged_aspects, ValueNode * merged, ValueNode * unmerged) [private]
Definition at line 1324 of file maglev-interpreter-frame-state.cc.
                                            {
  DCHECK_NOT_NULL(merged);
  DCHECK_NOT_NULL(unmerged);
  Phi* result = merged->TryCast<Phi>();
  if (result != nullptr && result->merge_state() == this) {
    NodeType unmerged_type =
        unmerged_aspects.GetType(builder->broker(), unmerged);
    unmerged = EnsureTagged(builder, unmerged_aspects, unmerged,
                            predecessors_[predecessors_so_far_]);
    for (uint32_t i = predecessors_so_far_; i < predecessor_count_; i++) {
      result->change_input(i, unmerged);
    }
    DCHECK_GT(predecessors_so_far_, 0);
    result->merge_type(unmerged_type);
    result->merge_post_loop_type(unmerged_type);
    return result;
  }
  if (merged == unmerged) {
    return merged;
  }
  if (InlinedAllocation* merged_nested_alloc =
          merged->TryCast<InlinedAllocation>()) {
    if (InlinedAllocation* unmerged_nested_alloc =
            unmerged->TryCast<InlinedAllocation>()) {
      // If a nested allocation doesn't point to the same object in both
      // objects, then we currently give up merging them and escape the
      // allocation.
      if (merged_nested_alloc != unmerged_nested_alloc) {
        return {};
      }
    }
  }
  // We don't support exception phis inside a virtual object.
  if (is_exception_handler()) {
    return {};
  }
  // We don't have LoopPhis inside a VirtualObject, but this can happen if the
  // block is a diamond-merge and a loop entry at the same time. For now, we
  // should escape.
  if (is_loop()) return {};
  result = Node::New<Phi>(builder->zone(), predecessor_count_, this,
                          interpreter::Register::invalid_value());
  if (v8_flags.trace_maglev_graph_building) {
    for (uint32_t i = 0; i < predecessor_count_; i++) {
      result->initialize_input_null(i);
    }
  }
  NodeType merged_type = merged->GetStaticType(builder->broker());
  // We must have seen the same value so far.
  DCHECK_NOT_NULL(known_node_aspects_);
  for (uint32_t i = 0; i < predecessors_so_far_; i++) {
    ValueNode* tagged_merged =
        EnsureTagged(builder, *known_node_aspects_, merged, predecessors_[i]);
    result->set_input(i, tagged_merged);
  }
  NodeType unmerged_type =
      unmerged_aspects.GetType(builder->broker(), unmerged);
  unmerged = EnsureTagged(builder, unmerged_aspects, unmerged,
                          predecessors_[predecessors_so_far_]);
  for (uint32_t i = predecessors_so_far_; i < predecessor_count_; i++) {
    result->set_input(i, unmerged);
  }
  result->set_type(UnionType(merged_type, unmerged_type));
  phis_.Add(result);
  return result;
}
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Add(), v8::internal::maglev::MaglevGraphBuilder::broker(), DCHECK_GT, DCHECK_NOT_NULL, v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::EnsureTagged(), v8::internal::maglev::ValueNode::GetStaticType(), v8::internal::maglev::KnownNodeAspects::GetType(), v8::internal::interpreter::Register::invalid_value(), is_exception_handler(), is_loop(), known_node_aspects_, phis_, predecessor_count_, predecessors_, predecessors_so_far_, v8::base::internal::result, v8::internal::maglev::NodeBase::TryCast(), v8::internal::maglev::UnionType(), v8::internal::v8_flags, and v8::internal::maglev::MaglevGraphBuilder::zone().
New()
MergePointInterpreterFrameState * v8::internal::maglev::MergePointInterpreterFrameState::New (const MaglevCompilationUnit & info, const InterpreterFrameState & state, int merge_offset, int predecessor_count, BasicBlock * predecessor, const compiler::BytecodeLivenessState * liveness) [static]
Definition at line 435 of file maglev-interpreter-frame-state.cc.
                                                   {
  MergePointInterpreterFrameState* merge_state =
      info.zone()->New<MergePointInterpreterFrameState>(
          info, merge_offset, predecessor_count, 1,
          info.zone()->AllocateArray<BasicBlock*>(predecessor_count),
          BasicBlockType::kDefault, liveness);
  int i = 0;
  merge_state->frame_state_.ForEachValue(
      info, [&](ValueNode*& entry, interpreter::Register reg) {
        entry = state.get(reg);
        // Initialise the alternatives list and cache the alternative
        // representations of the node.
        Alternatives::List* per_predecessor_alternatives =
            new (&merge_state->per_predecessor_alternatives_[i])
                Alternatives::List();
        per_predecessor_alternatives->Add(info.zone()->New<Alternatives>(
            state.known_node_aspects()->TryGetInfoFor(entry)));
        i++;
      });
  merge_state->predecessors_[0] = predecessor;
  merge_state->known_node_aspects_ =
      state.known_node_aspects()->Clone(info.zone());
  state.virtual_objects().Snapshot();
  merge_state->set_virtual_objects(state.virtual_objects());
  return merge_state;
}
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Add(), v8::internal::Zone::AllocateArray(), v8::internal::maglev::KnownNodeAspects::Clone(), v8::internal::maglev::CompactInterpreterFrameState::ForEachValue(), frame_state_, v8::internal::maglev::InterpreterFrameState::get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, kDefault, v8::internal::maglev::InterpreterFrameState::known_node_aspects(), known_node_aspects_, merge_offset(), v8::internal::Zone::New(), per_predecessor_alternatives_, predecessor_count(), predecessors_, set_virtual_objects(), v8::internal::maglev::VirtualObjectList::Snapshot(), v8::internal::maglev::KnownNodeAspects::TryGetInfoFor(), v8::internal::maglev::InterpreterFrameState::virtual_objects(), and v8::internal::maglev::MaglevCompilationUnit::zone().
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::MergeIntoLabel().
NewExceptionPhi()
ValueNode* v8::internal::maglev::MergePointInterpreterFrameState::NewExceptionPhi (Zone * zone, interpreter::Register reg) [inline], [private]
Definition at line 1171 of file maglev-interpreter-frame-state.h.
                                                                  {
    DCHECK_EQ(predecessor_count_, 0);
    DCHECK_NULL(predecessors_);
    Phi* result = Node::New<Phi>(zone, 0, this, reg);
    phis_.Add(result);
    return result;
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Add(), DCHECK_EQ, DCHECK_NULL, phis_, predecessor_count_, predecessors_, and v8::base::internal::result.
Referenced by MergeValue(), and NewForCatchBlock().
NewForCatchBlock()
MergePointInterpreterFrameState * v8::internal::maglev::MergePointInterpreterFrameState::NewForCatchBlock (const MaglevCompilationUnit & unit, const compiler::BytecodeLivenessState * liveness, int handler_offset, bool was_used, interpreter::Register context_register, Graph * graph) [static]
Definition at line 527 of file maglev-interpreter-frame-state.cc.
                                                                       {
  Zone* const zone = unit.zone();
  MergePointInterpreterFrameState* state =
      zone->New<MergePointInterpreterFrameState>(
          unit, handler_offset, 0, 0, nullptr,
          was_used ? BasicBlockType::kExceptionHandlerStart
                   : BasicBlockType::kUnusedExceptionHandlerStart,
          liveness);
  auto& frame_state = state->frame_state_;
  // If the accumulator is live, the ExceptionPhi associated to it is the
  // first one in the block. That ensures it gets kReturnValue0 in the
  // register allocator. See
  // StraightForwardRegisterAllocator::AllocateRegisters.
  if (frame_state.liveness()->AccumulatorIsLive()) {
    frame_state.accumulator(unit) = state->NewExceptionPhi(
        zone, interpreter::Register::virtual_accumulator());
  }
  frame_state.ForEachRegister(
      unit,
      [&](ValueNode*& entry, interpreter::Register reg) { entry = nullptr; });
  state->catch_block_context_register_ = context_register;
  return state;
}
References v8::internal::maglev::CompactInterpreterFrameState::accumulator(), v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), catch_block_context_register_, v8::internal::maglev::CompactInterpreterFrameState::ForEachRegister(), frame_state(), frame_state_, kExceptionHandlerStart, kUnusedExceptionHandlerStart, v8::internal::maglev::CompactInterpreterFrameState::liveness(), v8::internal::Zone::New(), NewExceptionPhi(), v8::internal::interpreter::Register::virtual_accumulator(), and v8::internal::maglev::MaglevCompilationUnit::zone().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildMergeStates().
NewForLoop()
MergePointInterpreterFrameState * v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop (const InterpreterFrameState & start_state, Graph * graph, const MaglevCompilationUnit & info, int merge_offset, int predecessor_count, const compiler::BytecodeLivenessState * liveness, const compiler::LoopInfo * loop_info, bool has_been_peeled = false) [static]
Definition at line 471 of file maglev-interpreter-frame-state.cc.
                                                             {
  MergePointInterpreterFrameState* state =
      info.zone()->New<MergePointInterpreterFrameState>(
          info, merge_offset, predecessor_count, 0,
          info.zone()->AllocateArray<BasicBlock*>(predecessor_count),
          BasicBlockType::kLoopHeader, liveness);
  state->bitfield_ =
      kIsLoopWithPeeledIterationBit::update(state->bitfield_, has_been_peeled);
  state->loop_metadata_ = LoopMetadata{loop_info, nullptr};
  if (loop_info->resumable()) {
    state->known_node_aspects_ =
        info.zone()->New<KnownNodeAspects>(info.zone());
    state->set_is_resumable_loop(graph);
  }
  auto& assignments = loop_info->assignments();
  auto& frame_state = state->frame_state_;
  int i = 0;
  frame_state.ForEachParameter(
      info, [&](ValueNode*& entry, interpreter::Register reg) {
        entry = nullptr;
        if (assignments.ContainsParameter(reg.ToParameterIndex())) {
          entry = state->NewLoopPhi(info.zone(), reg);
        } else if (state->is_resumable_loop()) {
          // Copy initial values out of the start state.
          entry = start_state.get(reg);
          // Initialise the alternatives list for this value.
          new (&state->per_predecessor_alternatives_[i]) Alternatives::List();
          DCHECK(entry->Is<InitialValue>());
        }
        ++i;
      });
  frame_state.context(info) = nullptr;
  if (state->is_resumable_loop()) {
    // While contexts are always the same at specific locations, resumable loops
    // do have different nodes to set the context across resume points. Create a
    // phi for them.
    frame_state.context(info) = state->NewLoopPhi(
        info.zone(), interpreter::Register::current_context());
  }
  frame_state.ForEachLocal(
      info, [&](ValueNode*& entry, interpreter::Register reg) {
        entry = nullptr;
        if (assignments.ContainsLocal(reg.index())) {
          entry = state->NewLoopPhi(info.zone(), reg);
        }
      });
  DCHECK(!frame_state.liveness()->AccumulatorIsLive());
  return state;
}
References v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), v8::internal::Zone::AllocateArray(), v8::internal::compiler::LoopInfo::assignments(), bitfield_, v8::internal::maglev::CompactInterpreterFrameState::context(), v8::internal::interpreter::Register::current_context(), v8::internal::DCHECK(), v8::internal::maglev::CompactInterpreterFrameState::ForEachLocal(), v8::internal::maglev::CompactInterpreterFrameState::ForEachParameter(), frame_state(), frame_state_, v8::internal::maglev::InterpreterFrameState::get(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::interpreter::Register::index(), v8::internal::maglev::NodeBase::Is(), is_resumable_loop(), kLoopHeader, known_node_aspects_, v8::internal::maglev::CompactInterpreterFrameState::liveness(), loop_info(), loop_metadata_, merge_offset(), v8::internal::Zone::New(), NewLoopPhi(), per_predecessor_alternatives_, predecessor_count(), v8::internal::compiler::LoopInfo::resumable(), set_is_resumable_loop(), v8::internal::interpreter::Register::ToParameterIndex(), v8::base::BitField< T, shift, size, U >::update(), and v8::internal::maglev::MaglevCompilationUnit::zone().
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::BeginLoop(), and v8::internal::maglev::MaglevGraphBuilder::BuildMergeStates().
NewLoopPhi()
ValueNode * v8::internal::maglev::MergePointInterpreterFrameState::NewLoopPhi (Zone * zone, interpreter::Register reg) [private]
Definition at line 1438 of file maglev-interpreter-frame-state.cc.
                                         {
  DCHECK_EQ(predecessors_so_far_, 0);
  // Create a new loop phi, which for now is empty.
  Phi* result = Node::New<Phi>(zone, predecessor_count_, this, reg);
  if (v8_flags.trace_maglev_graph_building) {
    for (uint32_t i = 0; i < predecessor_count_; i++) {
      result->initialize_input_null(i);
    }
  }
  phis_.Add(result);
  return result;
}
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Add(), DCHECK_EQ, phis_, predecessor_count_, predecessors_so_far_, v8::base::internal::result, and v8::internal::v8_flags.
Referenced by NewForLoop().
phis()
Phi::List* v8::internal::maglev::MergePointInterpreterFrameState::phis () [inline]
Definition at line 997 of file maglev-interpreter-frame-state.h.
{ return &phis_; }
References phis_.
Referenced by v8::internal::maglev::BasicBlock::AddPhi(), v8::internal::maglev::BasicBlock::phis(), v8::internal::maglev::MaglevGraphBuilder::RegisterPhisWithGraphLabeller(), and RemovePredecessorAt().
predecessor_at()
BasicBlock* v8::internal::maglev::MergePointInterpreterFrameState::predecessor_at (int i) const [inline]
Definition at line 1003 of file maglev-interpreter-frame-state.h.
                                          {
    DCHECK_LE(predecessors_so_far_, predecessor_count_);
    DCHECK_LT(i, predecessors_so_far_);
    return predecessors_[i];
  }
References DCHECK_LE, DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, predecessor_count_, predecessors_, and predecessors_so_far_.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), IsUnreachableByForwardEdge(), v8::internal::maglev::Phi::predecessor_at(), v8::internal::maglev::BasicBlock::predecessor_at(), v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointPredecessors(), and v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi().
predecessor_count()
uint32_t v8::internal::maglev::MergePointInterpreterFrameState::predecessor_count () const [inline]
Definition at line 999 of file maglev-interpreter-frame-state.h.
{ return predecessor_count_; }
References predecessor_count_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::EndLoop(), v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues(), New(), NewForLoop(), v8::internal::maglev::BasicBlock::predecessor_count(), v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointAtExceptionHandlerStart(), and v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointPredecessors().
predecessors_so_far()
uint32_t v8::internal::maglev::MergePointInterpreterFrameState::predecessors_so_far () const [inline]
Definition at line 1001 of file maglev-interpreter-frame-state.h.
{ return predecessors_so_far_; }
References predecessors_so_far_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Bind(), v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointPredecessors(), v8::internal::maglev::Phi::SetUseRequires31BitValue(), and v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::TrimPredecessorsAndBind().
PrintVirtualObjects()
void v8::internal::maglev::MergePointInterpreterFrameState::PrintVirtualObjects (MaglevGraphLabeller * labeller, VirtualObjectList from_ifs, const char * prelude = nullptr) [inline]
Definition at line 1018 of file maglev-interpreter-frame-state.h.
                                                          {
    if (!v8_flags.trace_maglev_graph_building) return;
    if (prelude) {
      std::cout << prelude << std::endl;
    }
    from_ifs.Print(std::cout, "* VOs (Interpreter Frame State): ", labeller);
    frame_state_.virtual_objects().Print(
        std::cout, "* VOs (Merge Frame State): ", labeller);
  }
References frame_state_, v8::internal::maglev::VirtualObjectList::Print(), v8::internal::v8_flags, and v8::internal::maglev::CompactInterpreterFrameState::virtual_objects().
Referenced by v8::internal::maglev::InterpreterFrameState::CopyFrom(), MergeThrow(), and MergeVirtualObjects().
ReducePhiPredecessorCount()
void v8::internal::maglev::MergePointInterpreterFrameState::ReducePhiPredecessorCount (unsigned num) [private]
Definition at line 1453 of file maglev-interpreter-frame-state.cc.
                                                                            {
  for (Phi* phi : phis_) {
    phi->reduce_input_count(num);
    if (predecessors_so_far_ == predecessor_count_ - 1 &&
        predecessor_count_ > 1 && phi->is_loop_phi()) {
      phi->promote_post_loop_type();
    }
  }
}
References phis_, predecessor_count_, and predecessors_so_far_.
Referenced by MergeDead(), and TurnLoopIntoRegularBlock().
register_state()
MergePointRegisterState& v8::internal::maglev::MergePointInterpreterFrameState::register_state () [inline]
Definition at line 994 of file maglev-interpreter-frame-state.h.
{ return register_state_; }
References register_state_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::maglev::BasicBlock::HasPhisOrRegisterMerges(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeBranchTargetRegisterValues(), and v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues().
RemovePredecessorAt()
void v8::internal::maglev::MergePointInterpreterFrameState::RemovePredecessorAt (int predecessor_id)
Definition at line 1487 of file maglev-interpreter-frame-state.cc.
                                                                            {
  // Only call this function if we have already process all merge points.
  DCHECK_EQ(predecessors_so_far_, predecessor_count_);
  DCHECK_GT(predecessor_count_, 0);
  // Shift predecessors_ by 1.
  for (uint32_t i = predecessor_id; i < predecessor_count_ - 1; i++) {
    predecessors_[i] = predecessors_[i + 1];
    // Update cache in unconditional control node.
    ControlNode* control = predecessors_[i]->control_node();
    if (auto unconditional_control =
            control->TryCast<UnconditionalControlNode>()) {
      DCHECK_EQ(unconditional_control->predecessor_id(), i + 1);
      unconditional_control->set_predecessor_id(i);
    }
  }
  // Remove Phi input of index predecessor_id.
  for (Phi* phi : *phis()) {
    DCHECK_EQ(phi->input_count(), predecessor_count_);
    // Shift phi inputs by 1.
    for (int i = predecessor_id; i < phi->input_count() - 1; i++) {
      phi->change_input(i, phi->input(i + 1).node());
    }
    phi->reduce_input_count(1);
  }
  predecessor_count_--;
  predecessors_so_far_--;
}
References v8::internal::maglev::BasicBlock::control_node(), DCHECK_EQ, DCHECK_GT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, phis(), predecessor_count_, predecessors_, predecessors_so_far_, and v8::internal::maglev::NodeBase::TryCast().
set_is_resumable_loop()
void v8::internal::maglev::MergePointInterpreterFrameState::set_is_resumable_loop (Graph * graph)
Definition at line 465 of file maglev-interpreter-frame-state.cc.
                                                                        {
  graph->set_may_have_unreachable_blocks();
  bitfield_ = kIsResumableLoopBit::update(bitfield_, true);
}
References bitfield_, graph(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by NewForLoop().
set_loop_effects()
void v8::internal::maglev::MergePointInterpreterFrameState::set_loop_effects (LoopEffects * loop_effects)
Definition at line 919 of file maglev-interpreter-frame-state.cc.
                               {
  DCHECK(is_loop());
  DCHECK(loop_metadata_.has_value());
  loop_metadata_->loop_effects = loop_effects;
}
References v8::internal::DCHECK(), is_loop(), loop_effects(), and loop_metadata_.
set_predecessor_at()
void v8::internal::maglev::MergePointInterpreterFrameState::set_predecessor_at (int i, BasicBlock * val) [inline]
Definition at line 1008 of file maglev-interpreter-frame-state.h.
                                                  {
    DCHECK_LE(predecessors_so_far_, predecessor_count_);
    DCHECK_LT(i, predecessors_so_far_);
    predecessors_[i] = val;
  }
References DCHECK_LE, DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, predecessor_count_, predecessors_, and predecessors_so_far_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointPredecessors(), and v8::internal::maglev::MaglevInliner::UpdatePredecessorsOf().
set_virtual_objects()
void v8::internal::maglev::MergePointInterpreterFrameState::set_virtual_objects (const VirtualObjectList & vos) [inline]
Definition at line 1014 of file maglev-interpreter-frame-state.h.
                                                         {
    frame_state_.set_virtual_objects(vos);
  }
References frame_state_, and v8::internal::maglev::CompactInterpreterFrameState::set_virtual_objects().
Referenced by New().
TakeKnownNodeAspects()
KnownNodeAspects* v8::internal::maglev::MergePointInterpreterFrameState::TakeKnownNodeAspects () [inline]
Definition at line 982 of file maglev-interpreter-frame-state.h.
                                           {
    DCHECK_NOT_NULL(known_node_aspects_);
    return std::exchange(known_node_aspects_, nullptr);
  }
References DCHECK_NOT_NULL, and known_node_aspects_.
Referenced by v8::internal::maglev::InterpreterFrameState::CopyFrom().
TryMergeLoop()
bool v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop (MaglevGraphBuilder * graph_builder, InterpreterFrameState & loop_end_state, const std::function< BasicBlock *()> & FinishBlock)
Definition at line 846 of file maglev-interpreter-frame-state.cc.
                                                   {
  // This should be the last predecessor we try to merge.
  DCHECK_EQ(predecessors_so_far_, predecessor_count_ - 1);
  DCHECK(is_unmerged_loop());
  backedge_deopt_frame_ =
      builder->zone()->New<DeoptFrame>(builder->GetLatestCheckpointedFrame());
  auto& compilation_unit = *builder->compilation_unit();
  DCHECK_NOT_NULL(known_node_aspects_);
  DCHECK(v8_flags.maglev_optimistic_peeled_loops);
  // TODO(olivf): This could be done faster by consulting loop_effects_
  if (!loop_end_state.known_node_aspects()->IsCompatibleWithLoopHeader(
          *known_node_aspects_)) {
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << "Merging failed, peeling loop instead... " << std::endl;
    }
    ClearLoopInfo();
    return false;
  }
  bool phis_can_merge = true;
  frame_state_.ForEachValue(compilation_unit, [&](ValueNode* value,
                                                  interpreter::Register reg) {
    if (!value->Is<Phi>()) return;
    Phi* phi = value->Cast<Phi>();
    if (!phi->is_loop_phi()) return;
    if (phi->merge_state() != this) return;
    NodeType old_type = known_node_aspects_->GetType(builder->broker(), phi);
    if (old_type != NodeType::kUnknown) {
      NodeType new_type = loop_end_state.known_node_aspects()->GetType(
          builder->broker(), loop_end_state.get(reg));
      if (!NodeTypeIs(new_type, old_type)) {
        if (v8_flags.trace_maglev_loop_speeling) {
          std::cout << "Cannot merge " << new_type << " into " << old_type
                    << " for r" << reg.index() << "\n";
        }
        phis_can_merge = false;
      }
    }
  });
  if (!phis_can_merge) {
    ClearLoopInfo();
    return false;
  }
  BasicBlock* loop_end_block = FinishBlock();
  int input = predecessor_count_ - 1;
  loop_end_block->set_predecessor_id(input);
  predecessors_[input] = loop_end_block;
  if (v8_flags.trace_maglev_graph_building) {
    std::cout << "Next peeling not needed due to compatible state" << std::endl;
  }
  frame_state_.ForEachValue(
      compilation_unit, [&](ValueNode* value, interpreter::Register reg) {
        PrintBeforeMerge(builder->graph_labeller(), value,
                         loop_end_state.get(reg), reg, known_node_aspects_);
        MergeLoopValue(builder, reg, *loop_end_state.known_node_aspects(),
                       value, loop_end_state.get(reg));
        PrintAfterMerge(builder->graph_labeller(), value, known_node_aspects_);
      });
  predecessors_so_far_++;
  DCHECK_EQ(predecessors_so_far_, predecessor_count_);
  ClearLoopInfo();
  return true;
}
References backedge_deopt_frame_, v8::internal::maglev::MaglevGraphBuilder::broker(), ClearLoopInfo(), v8::internal::maglev::MaglevGraphBuilder::compilation_unit(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::maglev::CompactInterpreterFrameState::ForEachValue(), frame_state_, v8::internal::maglev::InterpreterFrameState::get(), v8::internal::maglev::MaglevGraphBuilder::GetLatestCheckpointedFrame(), v8::internal::maglev::KnownNodeAspects::GetType(), v8::internal::maglev::MaglevGraphBuilder::graph_labeller(), v8::internal::if(), is_unmerged_loop(), v8::internal::maglev::KnownNodeAspects::IsCompatibleWithLoopHeader(), v8::internal::maglev::InterpreterFrameState::known_node_aspects(), known_node_aspects_, MergeLoopValue(), v8::internal::Zone::New(), v8::internal::maglev::NodeTypeIs(), predecessor_count_, predecessors_, predecessors_so_far_, v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::PrintAfterMerge(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::PrintBeforeMerge(), v8::internal::maglev::BasicBlock::set_predecessor_id(), v8::internal::v8_flags, v8::internal::value, and v8::internal::maglev::MaglevGraphBuilder::zone().
TurnLoopIntoRegularBlock()
void v8::internal::maglev::MergePointInterpreterFrameState::TurnLoopIntoRegularBlock () [inline]
Definition at line 970 of file maglev-interpreter-frame-state.h.
                                  {
    DCHECK(is_loop());
    predecessor_count_--;
    predecessors_so_far_--;
    ReducePhiPredecessorCount(1);
    clear_is_loop();
  }
References clear_is_loop(), v8::internal::DCHECK(), is_loop(), predecessor_count_, predecessors_so_far_, and ReducePhiPredecessorCount().
Friends And Related Function Documentation
Zone::New
template<typename T , typename... Args>
T* Zone::New (Args &&... args) [friend]
Member Data Documentation
union { ... } [private]
backedge_deopt_frame_
DeoptFrame* v8::internal::maglev::MergePointInterpreterFrameState::backedge_deopt_frame_
Definition at line 1203 of file maglev-interpreter-frame-state.h.
Referenced by backedge_deopt_frame(), MergeLoop(), and TryMergeLoop().
bitfield_
uint32_t v8::internal::maglev::MergePointInterpreterFrameState::bitfield_ [private]
Definition at line 1184 of file maglev-interpreter-frame-state.h.
Referenced by basic_block_type(), clear_is_loop(), is_loop_with_peeled_iteration(), is_resumable_loop(), NewForLoop(), and set_is_resumable_loop().
catch_block_context_register_
interpreter::Register v8::internal::maglev::MergePointInterpreterFrameState::catch_block_context_register_
Definition at line 1206 of file maglev-interpreter-frame-state.h.
Referenced by catch_block_context_register(), MergeThrow(), and NewForCatchBlock().
frame_state_
CompactInterpreterFrameState v8::internal::maglev::MergePointInterpreterFrameState::frame_state_ [private]
Definition at line 1190 of file maglev-interpreter-frame-state.h.
Referenced by frame_state(), InitializeLoop(), MergeLoop(), MergePhis(), MergeThrow(), MergeVirtualObject(), MergeVirtualObjects(), New(), NewForCatchBlock(), NewForLoop(), PrintVirtualObjects(), set_virtual_objects(), and TryMergeLoop().
known_node_aspects_
KnownNodeAspects* v8::internal::maglev::MergePointInterpreterFrameState::known_node_aspects_ = nullptr [private]
Definition at line 1192 of file maglev-interpreter-frame-state.h.
Referenced by CloneKnownNodeAspects(), InitializeLoop(), Merge(), MergeLoop(), MergePhis(), MergeThrow(), MergeValue(), MergeVirtualObjectValue(), New(), NewForLoop(), TakeKnownNodeAspects(), and TryMergeLoop().
loop_metadata_
std::optional<LoopMetadata> v8::internal::maglev::MergePointInterpreterFrameState::loop_metadata_ = std::nullopt [private]
Definition at line 1213 of file maglev-interpreter-frame-state.h.
Referenced by ClearLoopInfo(), HasLoopInfo(), loop_effects(), loop_info(), NewForLoop(), and set_loop_effects().
merge_offset_
int v8::internal::maglev::MergePointInterpreterFrameState::merge_offset_ [private]
Definition at line 1179 of file maglev-interpreter-frame-state.h.
Referenced by merge_offset().
per_predecessor_alternatives_
Alternatives::List* v8::internal::maglev::MergePointInterpreterFrameState::per_predecessor_alternatives_
Definition at line 1197 of file maglev-interpreter-frame-state.h.
Referenced by MergePhis(), New(), and NewForLoop().
phis_
Phi::List v8::internal::maglev::MergePointInterpreterFrameState::phis_ [private]
Definition at line 1188 of file maglev-interpreter-frame-state.h.
Referenced by has_phi(), InitializeWithBasicBlock(), MergeValue(), MergeVirtualObjectValue(), NewExceptionPhi(), NewLoopPhi(), phis(), and ReducePhiPredecessorCount().
predecessor_count_
uint32_t v8::internal::maglev::MergePointInterpreterFrameState::predecessor_count_ [private]
Definition at line 1181 of file maglev-interpreter-frame-state.h.
Referenced by InitializeLoop(), is_unmerged_loop(), is_unmerged_unreachable_loop(), IsUnreachableByForwardEdge(), Merge(), MergeDead(), MergeDeadLoop(), MergeLoop(), MergeLoopValue(), MergeThrow(), MergeValue(), MergeVirtualObjectValue(), NewExceptionPhi(), NewLoopPhi(), predecessor_at(), predecessor_count(), ReducePhiPredecessorCount(), RemovePredecessorAt(), set_predecessor_at(), TryMergeLoop(), and TurnLoopIntoRegularBlock().
predecessors_
BasicBlock** v8::internal::maglev::MergePointInterpreterFrameState::predecessors_ [private]
Definition at line 1186 of file maglev-interpreter-frame-state.h.
Referenced by InitializeLoop(), Merge(), MergeLoop(), MergeLoopValue(), MergeValue(), MergeVirtualObjectValue(), New(), NewExceptionPhi(), predecessor_at(), RemovePredecessorAt(), set_predecessor_at(), and TryMergeLoop().
predecessors_so_far_
uint32_t v8::internal::maglev::MergePointInterpreterFrameState::predecessors_so_far_ [private]
Definition at line 1182 of file maglev-interpreter-frame-state.h.
Referenced by InitializeLoop(), is_unmerged_loop(), is_unmerged_unreachable_loop(), IsUnreachableByForwardEdge(), Merge(), MergeDead(), MergeDeadLoop(), MergeLoop(), MergeLoopValue(), MergeThrow(), MergeValue(), MergeVirtualObjectValue(), NewLoopPhi(), predecessor_at(), predecessors_so_far(), ReducePhiPredecessorCount(), RemovePredecessorAt(), set_predecessor_at(), TryMergeLoop(), and TurnLoopIntoRegularBlock().
register_state_
MergePointRegisterState v8::internal::maglev::MergePointInterpreterFrameState::register_state_ [private]
Definition at line 1191 of file maglev-interpreter-frame-state.h.
Referenced by register_state().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-interpreter-frame-state.h
/mnt/V8SourceCode/src/maglev/maglev-interpreter-frame-state.cc