v8::internal::ValueDeserializer Class Reference
#include <value-serializer.h>
Public Member Functions
ValueDeserializer (Isolate *isolate, base::Vector< const uint8_t > data, v8::ValueDeserializer::Delegate *delegate)
ValueDeserializer (Isolate *isolate, const uint8_t *data, size_t size)
~ValueDeserializer ()
ValueDeserializer (const ValueDeserializer &)=delete
ValueDeserializer & operator= (const ValueDeserializer &)=delete
Maybe< bool > ReadHeader () V8_WARN_UNUSED_RESULT
uint32_t GetWireFormatVersion () const
MaybeDirectHandle< Object > ReadObjectWrapper () V8_WARN_UNUSED_RESULT
MaybeDirectHandle< Object > ReadObjectUsingEntireBufferForLegacyFormat () V8_WARN_UNUSED_RESULT
void TransferArrayBuffer (uint32_t transfer_id, DirectHandle< JSArrayBuffer > array_buffer)
bool ReadUint32 (uint32_t *value) V8_WARN_UNUSED_RESULT
bool ReadUint64 (uint64_t *value) V8_WARN_UNUSED_RESULT
bool ReadDouble (double *value) V8_WARN_UNUSED_RESULT
bool ReadRawBytes (size_t length, const void **data) V8_WARN_UNUSED_RESULT
bool ReadByte (uint8_t *value) V8_WARN_UNUSED_RESULT
template<typename T >
Maybe< T > ReadVarintLoop ()
Private Member Functions
Maybe< SerializationTag > PeekTag () const V8_WARN_UNUSED_RESULT
void ConsumeTag (SerializationTag peeked_tag)
Maybe< SerializationTag > ReadTag () V8_WARN_UNUSED_RESULT
template<typename T >
Maybe< T > ReadVarint () V8_WARN_UNUSED_RESULT
template<typename T >
V8_NOINLINE Maybe< T > ReadVarintLoop () V8_WARN_UNUSED_RESULT
template<typename T >
Maybe< T > ReadZigZag () V8_WARN_UNUSED_RESULT
Maybe< double > ReadDouble () V8_WARN_UNUSED_RESULT
Maybe< base::Vector< const uint8_t > > ReadRawBytes (size_t size) V8_WARN_UNUSED_RESULT
Maybe< base::Vector< const base::uc16 > > ReadRawTwoBytes (size_t size) V8_WARN_UNUSED_RESULT
MaybeDirectHandle< Object > ReadObject () V8_WARN_UNUSED_RESULT
MaybeDirectHandle< Object > ReadObjectInternal () V8_WARN_UNUSED_RESULT
MaybeDirectHandle< String > ReadString () V8_WARN_UNUSED_RESULT
MaybeDirectHandle< BigInt > ReadBigInt () V8_WARN_UNUSED_RESULT
MaybeDirectHandle< String > ReadUtf8String (AllocationType allocation=AllocationType::kYoung) V8_WARN_UNUSED_RESULT
MaybeDirectHandle< String > ReadOneByteString (AllocationType allocation=AllocationType::kYoung) V8_WARN_UNUSED_RESULT
MaybeDirectHandle< String > ReadTwoByteString (AllocationType allocation=AllocationType::kYoung) V8_WARN_UNUSED_RESULT
MaybeDirectHandle< JSObject > ReadJSObject () V8_WARN_UNUSED_RESULT
MaybeDirectHandle< JSArray > ReadSparseJSArray () V8_WARN_UNUSED_RESULT
MaybeDirectHandle< JSArray > ReadDenseJSArray () V8_WARN_UNUSED_RESULT
MaybeDirectHandle< JSDate > ReadJSDate () V8_WARN_UNUSED_RESULT
MaybeDirectHandle< JSPrimitiveWrapper > ReadJSPrimitiveWrapper (SerializationTag tag) V8_WARN_UNUSED_RESULT
MaybeDirectHandle< JSRegExp > ReadJSRegExp () V8_WARN_UNUSED_RESULT
MaybeDirectHandle< JSMap > ReadJSMap () V8_WARN_UNUSED_RESULT
MaybeDirectHandle< JSSet > ReadJSSet () V8_WARN_UNUSED_RESULT
MaybeDirectHandle< JSArrayBuffer > ReadJSArrayBuffer (bool is_shared, bool is_resizable) V8_WARN_UNUSED_RESULT
MaybeDirectHandle< JSArrayBuffer > ReadTransferredJSArrayBuffer () V8_WARN_UNUSED_RESULT
MaybeDirectHandle< JSArrayBufferView > ReadJSArrayBufferView (DirectHandle< JSArrayBuffer > buffer) V8_WARN_UNUSED_RESULT
bool ValidateJSArrayBufferViewFlags (Tagged< JSArrayBuffer > buffer, uint32_t serialized_flags, bool &is_length_tracking, bool &is_backed_by_rab) V8_WARN_UNUSED_RESULT
MaybeDirectHandle< Object > ReadJSError () V8_WARN_UNUSED_RESULT
MaybeDirectHandle< HeapObject > ReadSharedObject () V8_WARN_UNUSED_RESULT
MaybeDirectHandle< JSObject > ReadHostObject () V8_WARN_UNUSED_RESULT
Maybe< uint32_t > ReadJSObjectProperties (DirectHandle< JSObject > object, SerializationTag end_tag, bool can_use_transitions)
bool HasObjectWithID (uint32_t id)
MaybeDirectHandle< JSReceiver > GetObjectWithID (uint32_t id)
void AddObjectWithID (uint32_t id, DirectHandle< JSReceiver > object)
Private Attributes
Isolate *const isolate_
v8::ValueDeserializer::Delegate *const delegate_
const uint8_t * position_
const uint8_t *const end_
uint32_t version_ = 0
uint32_t next_id_ = 0
bool version_13_broken_data_mode_ = false
bool suppress_deserialization_errors_ = false
IndirectHandle< FixedArray > id_map_
MaybeIndirectHandle< SimpleNumberDictionary > array_buffer_transfer_map_
const SharedObjectConveyorHandles * shared_object_conveyor_ = nullptr
Detailed Description
Definition at line 203 of file value-serializer.h.
Constructor & Destructor Documentation
ValueDeserializer() [1/3]
v8::internal::ValueDeserializer::ValueDeserializer (Isolate * isolate, base::Vector< const uint8_t > data, v8::ValueDeserializer::Delegate * delegate)
Definition at line 1338 of file value-serializer.cc.
    : isolate_(isolate),
      delegate_(delegate),
      position_(data.begin()),
      end_(data.end()),
      id_map_(isolate->global_handles()->Create(
          ReadOnlyRoots(isolate_).empty_fixed_array())) {}
ValueDeserializer() [2/3]
v8::internal::ValueDeserializer::ValueDeserializer (Isolate * isolate, const uint8_t * data, size_t size)
Definition at line 1348 of file value-serializer.cc.
    : isolate_(isolate),
      delegate_(nullptr),
      position_(data),
      end_(data + size),
      id_map_(isolate->global_handles()->Create(
          ReadOnlyRoots(isolate_).empty_fixed_array())) {}
 ValueDeserializer()
v8::internal::ValueDeserializer::~ValueDeserializer ()
Definition at line 1357 of file value-serializer.cc.
                                      {
  DCHECK_LE(position_, end_);
  GlobalHandles::Destroy(id_map_.location());
  IndirectHandle<Object> transfer_map_handle;
  if (array_buffer_transfer_map_.ToHandle(&transfer_map_handle)) {
    GlobalHandles::Destroy(transfer_map_handle.location());
  }
}
References array_buffer_transfer_map_, DCHECK_LE, v8::internal::GlobalHandles::Destroy(), end_, id_map_, v8::internal::HandleBase::location(), and position_.
ValueDeserializer() [3/3]
v8::internal::ValueDeserializer::ValueDeserializer (const ValueDeserializer &) [delete]
Member Function Documentation
AddObjectWithID()
void v8::internal::ValueDeserializer::AddObjectWithID (uint32_t id, DirectHandle< JSReceiver > object) [private]
Definition at line 2734 of file value-serializer.cc.
                                                                         {
  DCHECK(!HasObjectWithID(id));
  DirectHandle<FixedArray> new_array =
      FixedArray::SetAndGrow(isolate_, id_map_, id, object);
  // If the dictionary was reallocated, update the global handle.
  if (!new_array.is_identical_to(id_map_)) {
    GlobalHandles::Destroy(id_map_.location());
    id_map_ = isolate_->global_handles()->Create(*new_array);
  }
}
References v8::internal::GlobalHandles::Create(), v8::internal::DCHECK(), v8::internal::GlobalHandles::Destroy(), v8::internal::Isolate::global_handles(), HasObjectWithID(), id_map_, v8::internal::DirectHandle< T >::is_identical_to(), and isolate_.
Referenced by ReadDenseJSArray(), ReadHostObject(), ReadJSArrayBuffer(), ReadJSArrayBufferView(), ReadJSDate(), ReadJSError(), ReadJSMap(), ReadJSObject(), ReadJSPrimitiveWrapper(), ReadJSRegExp(), ReadJSSet(), ReadSparseJSArray(), and ReadTransferredJSArrayBuffer().
ConsumeTag()
void v8::internal::ValueDeserializer::ConsumeTag (SerializationTag peeked_tag) [private]
Definition at line 1392 of file value-serializer.cc.
                                                              {
  SerializationTag actual_tag = ReadTag().ToChecked();
  DCHECK(actual_tag == peeked_tag);
  USE(actual_tag);
}
References v8::internal::DCHECK(), ReadTag(), and USE.
Referenced by ReadDenseJSArray(), ReadJSMap(), ReadJSObjectProperties(), ReadJSSet(), ReadObject(), and ReadObjectUsingEntireBufferForLegacyFormat().
GetObjectWithID()
MaybeDirectHandle< JSReceiver > v8::internal::ValueDeserializer::GetObjectWithID (uint32_t id) [private]
Definition at line 2724 of file value-serializer.cc.
                                                                            {
  if (id >= static_cast<unsigned>(id_map_->length())) {
    return MaybeDirectHandle<JSReceiver>();
  }
  Tagged<Object> value = id_map_->get(id);
  if (IsTheHole(value, isolate_)) return MaybeDirectHandle<JSReceiver>();
  DCHECK(IsJSReceiver(value));
  return DirectHandle<JSReceiver>(Cast<JSReceiver>(value), isolate_);
}
References v8::internal::DCHECK(), id_map_, isolate_, and v8::internal::value.
Referenced by ReadObjectInternal().
GetWireFormatVersion()
uint32_t v8::internal::ValueDeserializer::GetWireFormatVersion () const [inline]
Definition at line 222 of file value-serializer.h.
{ return version_; }
References version_.
Referenced by v8::ValueDeserializer::GetWireFormatVersion().
HasObjectWithID()
bool v8::internal::ValueDeserializer::HasObjectWithID (uint32_t id) [private]
Definition at line 2719 of file value-serializer.cc.
                                                   {
  return id < static_cast<unsigned>(id_map_->length()) &&
         !IsTheHole(id_map_->get(id), isolate_);
}
References id_map_, and isolate_.
Referenced by AddObjectWithID(), ReadDenseJSArray(), ReadJSMap(), ReadJSObject(), ReadJSSet(), and ReadSparseJSArray().
operator=()
ValueDeserializer& v8::internal::ValueDeserializer::operator= (const ValueDeserializer &) [delete]
PeekTag()
Maybe< SerializationTag > v8::internal::ValueDeserializer::PeekTag () const [private]
Definition at line 1381 of file value-serializer.cc.
                                                         {
  const uint8_t* peek_position = position_;
  SerializationTag tag;
  do {
    if (peek_position >= end_) return Nothing<SerializationTag>();
    tag = static_cast<SerializationTag>(*peek_position);
    peek_position++;
  } while (tag == SerializationTag::kPadding);
  return Just(tag);
}
References end_, v8::Just(), v8::internal::kPadding, and position_.
Referenced by ReadDenseJSArray(), ReadJSMap(), ReadJSObjectProperties(), ReadJSSet(), ReadObject(), and ReadObjectUsingEntireBufferForLegacyFormat().
ReadBigInt()
MaybeDirectHandle< BigInt > v8::internal::ValueDeserializer::ReadBigInt () [private]
Definition at line 1760 of file value-serializer.cc.
                                                        {
  uint32_t bitfield;
  if (!ReadVarint<uint32_t>().To(&bitfield)) return MaybeDirectHandle<BigInt>();
  size_t bytelength = BigInt::DigitsByteLengthForBitfield(bitfield);
  base::Vector<const uint8_t> digits_storage;
  if (!ReadRawBytes(bytelength).To(&digits_storage)) {
    return MaybeDirectHandle<BigInt>();
  }
  return BigInt::FromSerializedDigits(isolate_, bitfield, digits_storage);
}
References v8::internal::BigInt::DigitsByteLengthForBitfield(), v8::internal::BigInt::FromSerializedDigits(), isolate_, and ReadRawBytes().
Referenced by ReadJSPrimitiveWrapper(), and ReadObjectInternal().
ReadByte()
bool v8::internal::ValueDeserializer::ReadByte (uint8_t * value)
Definition at line 1541 of file value-serializer.cc.
                                               {
  if (static_cast<size_t>(end_ - position_) < sizeof(uint8_t)) return false;
  *value = *position_;
  position_++;
  return true;
}
References end_, position_, and v8::internal::value.
ReadDenseJSArray()
MaybeDirectHandle< JSArray > v8::internal::ValueDeserializer::ReadDenseJSArray () [private]
Definition at line 1873 of file value-serializer.cc.
                                                               {
  // If we are at the end of the stack, abort. This function may recurse.
  STACK_CHECK(isolate_, MaybeDirectHandle<JSArray>());
  // We shouldn't permit an array larger than the biggest we can request from
  // V8. As an additional sanity check, since each entry will take at least one
  // byte to encode, if there are fewer bytes than that we can also fail fast.
  uint32_t length;
  if (!ReadVarint<uint32_t>().To(&length) ||
      length > static_cast<uint32_t>(FixedArray::kMaxLength) ||
      length > static_cast<size_t>(end_ - position_)) {
    return MaybeDirectHandle<JSArray>();
  }
  uint32_t id = next_id_++;
  HandleScope scope(isolate_);
  DirectHandle<JSArray> array = isolate_->factory()->NewJSArray(
      HOLEY_ELEMENTS, length, length,
      ArrayStorageAllocationMode::INITIALIZE_ARRAY_ELEMENTS_WITH_HOLE);
  AddObjectWithID(id, array);
  DirectHandle<FixedArray> elements(Cast<FixedArray>(array->elements()),
                                    isolate_);
  auto elements_length = static_cast<uint32_t>(elements->length());
  for (uint32_t i = 0; i < length; i++) {
    SerializationTag tag;
    if (PeekTag().To(&tag) && tag == SerializationTag::kTheHole) {
      ConsumeTag(SerializationTag::kTheHole);
      continue;
    }
    DirectHandle<Object> element;
    if (!ReadObject().ToHandle(&element)) return MaybeDirectHandle<JSArray>();
    // Serialization versions less than 11 encode the hole the same as
    // undefined. For consistency with previous behavior, store these as the
    // hole. Past version 11, undefined means undefined.
    if (version_ < 11 && IsUndefined(*element, isolate_)) continue;
    // Safety check.
    if (i >= elements_length) return MaybeDirectHandle<JSArray>();
    elements->set(i, *element);
  }
  uint32_t num_properties;
  uint32_t expected_num_properties;
  uint32_t expected_length;
  if (!ReadJSObjectProperties(array, SerializationTag::kEndDenseJSArray, false)
           .To(&num_properties) ||
      !ReadVarint<uint32_t>().To(&expected_num_properties) ||
      !ReadVarint<uint32_t>().To(&expected_length) ||
      num_properties != expected_num_properties || length != expected_length) {
    return MaybeDirectHandle<JSArray>();
  }
  DCHECK(HasObjectWithID(id));
  return scope.CloseAndEscape(array);
}
References AddObjectWithID(), ConsumeTag(), v8::internal::DCHECK(), end_, v8::internal::Isolate::factory(), HasObjectWithID(), v8::internal::HOLEY_ELEMENTS, v8::internal::INITIALIZE_ARRAY_ELEMENTS_WITH_HOLE, isolate_, v8::internal::kEndDenseJSArray, v8::internal::FixedArray::kMaxLength, v8::internal::kTheHole, v8::internal::length, v8::internal::Factory::NewJSArray(), next_id_, PeekTag(), position_, ReadJSObjectProperties(), ReadObject(), STACK_CHECK, v8::anonymous_namespace{api.cc}::ToHandle(), and version_.
Referenced by ReadObjectInternal().
ReadDouble() [1/2]
Maybe<double> v8::internal::ValueDeserializer::ReadDouble () [private]
Referenced by ReadDouble(), ReadJSDate(), ReadJSPrimitiveWrapper(), and ReadObjectInternal().
ReadDouble() [2/2]
bool v8::internal::ValueDeserializer::ReadDouble (double * value)
Definition at line 1556 of file value-serializer.cc.
                                                {
  return ReadDouble().To(value);
}
References ReadDouble(), and v8::internal::value.
Referenced by v8::ValueDeserializer::ReadDouble().
ReadHeader()
Maybe< bool > v8::internal::ValueDeserializer::ReadHeader ()
Definition at line 1367 of file value-serializer.cc.
                                          {
  if (position_ < end_ &&
      *position_ == static_cast<uint8_t>(SerializationTag::kVersion)) {
    ReadTag().ToChecked();
    if (!ReadVarintLoop<uint32_t>().To(&version_) ||
        version_ > kLatestVersion) {
      isolate_->Throw(*isolate_->factory()->NewError(
          MessageTemplate::kDataCloneDeserializationVersionError));
      return Nothing<bool>();
    }
  }
  return Just(true);
}
References end_, v8::internal::Isolate::factory(), isolate_, v8::Just(), v8::internal::kLatestVersion, v8::internal::kVersion, v8::internal::Factory::NewError(), position_, ReadTag(), v8::internal::Isolate::Throw(), and version_.
Referenced by v8::ValueDeserializer::ReadHeader().
ReadHostObject()
MaybeDirectHandle< JSObject > v8::internal::ValueDeserializer::ReadHostObject () [private]
Definition at line 2503 of file value-serializer.cc.
                                                              {
  if (!delegate_) return MaybeDirectHandle<JSObject>();
  STACK_CHECK(isolate_, MaybeDirectHandle<JSObject>());
  uint32_t id = next_id_++;
  v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(isolate_);
  v8::Local<v8::Object> object;
  if (!delegate_->ReadHostObject(v8_isolate).ToLocal(&object)) {
    RETURN_EXCEPTION_IF_EXCEPTION(isolate_);
    return MaybeDirectHandle<JSObject>();
  }
  DirectHandle<JSObject> js_object =
      Cast<JSObject>(Utils::OpenDirectHandle(*object));
  AddObjectWithID(id, js_object);
  return js_object;
}
References AddObjectWithID(), delegate_, isolate_, next_id_, v8::Utils::OpenDirectHandle(), v8::ValueDeserializer::Delegate::ReadHostObject(), RETURN_EXCEPTION_IF_EXCEPTION, and STACK_CHECK.
Referenced by ReadObjectInternal().
ReadJSArrayBuffer()
MaybeDirectHandle< JSArrayBuffer > v8::internal::ValueDeserializer::ReadJSArrayBuffer (bool is_shared, bool is_resizable) [private]
Definition at line 2104 of file value-serializer.cc.
                                       {
  uint32_t id = next_id_++;
  if (is_shared) {
    uint32_t clone_id;
    Local<SharedArrayBuffer> sab_value;
    if (!ReadVarint<uint32_t>().To(&clone_id) || delegate_ == nullptr ||
        !delegate_
             ->GetSharedArrayBufferFromId(
                 reinterpret_cast<v8::Isolate*>(isolate_), clone_id)
             .ToLocal(&sab_value)) {
      RETURN_EXCEPTION_IF_EXCEPTION(isolate_);
      return MaybeDirectHandle<JSArrayBuffer>();
    }
    DirectHandle<JSArrayBuffer> array_buffer =
        Utils::OpenDirectHandle(*sab_value);
    DCHECK_EQ(is_shared, array_buffer->is_shared());
    AddObjectWithID(id, array_buffer);
#if V8_ENABLE_WEBASSEMBLY
    auto backing_store = array_buffer->GetBackingStore();
    if (backing_store && backing_store->is_wasm_memory()) {
      uint8_t resizable_subtag;
      if (!ReadVarint<uint8_t>().To(&resizable_subtag)) {
        return MaybeDirectHandle<JSArrayBuffer>();
      }
      switch (static_cast<WasmMemoryArrayBufferTag>(resizable_subtag)) {
        case WasmMemoryArrayBufferTag::kFixedLength:
          // Nothing to do.
          break;
        case WasmMemoryArrayBufferTag::kResizableNotFollowedByWasmMemory:
          // In this case we are in the middle of constructing the
          // WebAssembly.Memory.
          array_buffer->set_is_resizable_by_js(true);
          break;
        case WasmMemoryArrayBufferTag::kResizableFollowedByWasmMemory: {
          array_buffer->set_is_resizable_by_js(true);
          DirectHandle<Object> wasm_memory_obj;
          if (!ReadObject().ToHandle(&wasm_memory_obj) ||
              !IsWasmMemoryObject(*wasm_memory_obj, isolate_)) {
            return MaybeDirectHandle<JSArrayBuffer>();
          }
          break;
        }
        default:
          return MaybeDirectHandle<JSArrayBuffer>();
      }
    }
#endif // V8_ENABLE_WEBASSEMBLY
    return array_buffer;
  }
  uint32_t byte_length;
  if (!ReadVarint<uint32_t>().To(&byte_length)) {
    return MaybeDirectHandle<JSArrayBuffer>();
  }
  uint32_t max_byte_length = byte_length;
  if (is_resizable) {
    if (!ReadVarint<uint32_t>().To(&max_byte_length)) {
      return MaybeDirectHandle<JSArrayBuffer>();
    }
    if (byte_length > max_byte_length) {
      return MaybeDirectHandle<JSArrayBuffer>();
    }
  }
  if (byte_length > static_cast<size_t>(end_ - position_)) {
    return MaybeDirectHandle<JSArrayBuffer>();
  }
  MaybeDirectHandle<JSArrayBuffer> result =
      isolate_->factory()->NewJSArrayBufferAndBackingStore(
          byte_length, max_byte_length, InitializedFlag::kUninitialized,
          is_resizable ? ResizableFlag::kResizable
                       : ResizableFlag::kNotResizable);
  DirectHandle<JSArrayBuffer> array_buffer;
  if (!result.ToHandle(&array_buffer)) return result;
  if (byte_length > 0) {
    memcpy(array_buffer->backing_store(), position_, byte_length);
  }
  position_ += byte_length;
  AddObjectWithID(id, array_buffer);
  return array_buffer;
}
References AddObjectWithID(), DCHECK_EQ, delegate_, end_, v8::internal::Isolate::factory(), v8::internal::is_shared, isolate_, v8::internal::kNotResizable, v8::internal::kResizable, v8::internal::kUninitialized, v8::internal::Factory::NewJSArrayBufferAndBackingStore(), next_id_, v8::Utils::OpenDirectHandle(), position_, ReadObject(), v8::base::internal::result, RETURN_EXCEPTION_IF_EXCEPTION, and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by ReadObjectInternal().
ReadJSArrayBufferView()
MaybeDirectHandle< JSArrayBufferView > v8::internal::ValueDeserializer::ReadJSArrayBufferView (DirectHandle< JSArrayBuffer > buffer) [private]
Definition at line 2208 of file value-serializer.cc.
                                        {
  uint32_t buffer_byte_length = static_cast<uint32_t>(buffer->GetByteLength());
  uint8_t tag = 0;
  uint32_t byte_offset = 0;
  uint32_t byte_length = 0;
  uint32_t flags = 0;
  if (!ReadVarint<uint8_t>().To(&tag) ||
      !ReadVarint<uint32_t>().To(&byte_offset) ||
      !ReadVarint<uint32_t>().To(&byte_length) ||
      byte_offset > buffer_byte_length ||
      byte_length > buffer_byte_length - byte_offset) {
    return MaybeDirectHandle<JSArrayBufferView>();
  }
  const bool should_read_flags = version_ >= 14 || version_13_broken_data_mode_;
  if (should_read_flags && !ReadVarint<uint32_t>().To(&flags)) {
    return MaybeDirectHandle<JSArrayBufferView>();
  }
  uint32_t id = next_id_++;
  ExternalArrayType external_array_type = kExternalInt8Array;
  unsigned element_size = 0;
  switch (static_cast<ArrayBufferViewTag>(tag)) {
    case ArrayBufferViewTag::kDataView: {
      bool is_length_tracking = false;
      bool is_backed_by_rab = false;
      if (!ValidateJSArrayBufferViewFlags(*buffer, flags, is_length_tracking,
                                          is_backed_by_rab)) {
        return MaybeDirectHandle<JSArrayBufferView>();
      }
      DirectHandle<JSDataViewOrRabGsabDataView> data_view =
          isolate_->factory()->NewJSDataViewOrRabGsabDataView(
              buffer, byte_offset, byte_length, is_length_tracking);
      CHECK_EQ(is_backed_by_rab, data_view->is_backed_by_rab());
      CHECK_EQ(is_length_tracking, data_view->is_length_tracking());
      AddObjectWithID(id, data_view);
      return data_view;
    }
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) \
  case ArrayBufferViewTag::k##Type##Array: \
    external_array_type = kExternal##Type##Array; \
    element_size = sizeof(ctype); \
    break;
      TYPED_ARRAYS_BASE(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
    case ArrayBufferViewTag::kFloat16Array: {
      if (i::v8_flags.js_float16array) {
        external_array_type = kExternalFloat16Array;
        element_size = sizeof(uint16_t);
      }
      break;
    }
  }
  if (element_size == 0 || byte_offset % element_size != 0 ||
      byte_length % element_size != 0) {
    return MaybeDirectHandle<JSArrayBufferView>();
  }
  bool is_length_tracking = false;
  bool is_backed_by_rab = false;
  if (!ValidateJSArrayBufferViewFlags(*buffer, flags, is_length_tracking,
                                      is_backed_by_rab)) {
    return MaybeDirectHandle<JSArrayBufferView>();
  }
  DirectHandle<JSTypedArray> typed_array = isolate_->factory()->NewJSTypedArray(
      external_array_type, buffer, byte_offset, byte_length / element_size,
      is_length_tracking);
  CHECK_EQ(is_length_tracking, typed_array->is_length_tracking());
  CHECK_EQ(is_backed_by_rab, typed_array->is_backed_by_rab());
  AddObjectWithID(id, typed_array);
  return typed_array;
}
References AddObjectWithID(), CHECK_EQ, v8::internal::Isolate::factory(), v8::internal::flags, v8::internal::is_backed_by_rab, isolate_, v8::internal::kExternalFloat16Array, v8::internal::kExternalInt8Array, v8::internal::Factory::NewJSDataViewOrRabGsabDataView(), v8::internal::Factory::NewJSTypedArray(), next_id_, TYPED_ARRAY_CASE, TYPED_ARRAYS_BASE, v8::internal::v8_flags, ValidateJSArrayBufferViewFlags(), version_, and version_13_broken_data_mode_.
Referenced by ReadObject().
ReadJSDate()
MaybeDirectHandle< JSDate > v8::internal::ValueDeserializer::ReadJSDate () [private]
Definition at line 1933 of file value-serializer.cc.
                                                        {
  double value;
  if (!ReadDouble().To(&value)) return MaybeDirectHandle<JSDate>();
  uint32_t id = next_id_++;
  DirectHandle<JSDate> date;
  if (!JSDate::New(isolate_, isolate_->date_function(),
                   isolate_->date_function(), value)
           .ToHandle(&date)) {
    return MaybeDirectHandle<JSDate>();
  }
  AddObjectWithID(id, date);
  return date;
}
References AddObjectWithID(), v8::internal::date, isolate_, v8::internal::JSDate::New(), next_id_, ReadDouble(), and v8::internal::value.
Referenced by ReadObjectInternal().
ReadJSError()
MaybeDirectHandle< Object > v8::internal::ValueDeserializer::ReadJSError () [private]
Definition at line 2307 of file value-serializer.cc.
                                                         {
  uint32_t id = next_id_++;
#define READ_NEXT_ERROR_TAG() \
  do { \
    if (!ReadVarint<uint8_t>().To(&tag)) { \
      return MaybeDirectHandle<JSObject>(); \
    } \
  } while (false)
  uint8_t tag;
  READ_NEXT_ERROR_TAG();
  // Read error type constructor.
  DirectHandle<JSFunction> constructor;
  switch (static_cast<ErrorTag>(tag)) {
    case ErrorTag::kEvalErrorPrototype:
      constructor = isolate_->eval_error_function();
      READ_NEXT_ERROR_TAG();
      break;
    case ErrorTag::kRangeErrorPrototype:
      constructor = isolate_->range_error_function();
      READ_NEXT_ERROR_TAG();
      break;
    case ErrorTag::kReferenceErrorPrototype:
      constructor = isolate_->reference_error_function();
      READ_NEXT_ERROR_TAG();
      break;
    case ErrorTag::kSyntaxErrorPrototype:
      constructor = isolate_->syntax_error_function();
      READ_NEXT_ERROR_TAG();
      break;
    case ErrorTag::kTypeErrorPrototype:
      constructor = isolate_->type_error_function();
      READ_NEXT_ERROR_TAG();
      break;
    case ErrorTag::kUriErrorPrototype:
      constructor = isolate_->uri_error_function();
      READ_NEXT_ERROR_TAG();
      break;
    default:
      // The default prototype in the deserialization side is Error.prototype,
      // so we don't have to do anything here.
      constructor = isolate_->error_function();
      break;
  }
  // Check for message property.
  DirectHandle<Object> message = isolate_->factory()->undefined_value();
  if (static_cast<ErrorTag>(tag) == ErrorTag::kMessage) {
    DirectHandle<String> message_string;
    if (!ReadString().ToHandle(&message_string)) {
      return MaybeDirectHandle<JSObject>();
    }
    message = message_string;
    READ_NEXT_ERROR_TAG();
  }
  // Check for stack property.
  DirectHandle<Object> stack = isolate_->factory()->undefined_value();
  if (static_cast<ErrorTag>(tag) == ErrorTag::kStack) {
    DirectHandle<String> stack_string;
    if (!ReadString().ToHandle(&stack_string)) {
      return MaybeDirectHandle<JSObject>();
    }
    stack = stack_string;
    READ_NEXT_ERROR_TAG();
  }
  // Create error object before adding the cause property.
  DirectHandle<JSObject> error;
  DirectHandle<Object> no_caller;
  DirectHandle<Object> undefined_options =
      isolate_->factory()->undefined_value();
  if (!ErrorUtils::Construct(isolate_, constructor, constructor, message,
                             undefined_options, SKIP_NONE, no_caller,
                             ErrorUtils::StackTraceCollection::kDisabled)
           .ToHandle(&error)) {
    return MaybeDirectHandle<Object>();
  }
  ErrorUtils::SetFormattedStack(isolate_, error, stack);
  AddObjectWithID(id, error);
  // Add cause property if needed.
  if (static_cast<ErrorTag>(tag) == ErrorTag::kCause) {
    DirectHandle<Object> cause;
    if (!ReadObject().ToHandle(&cause)) {
      return MaybeDirectHandle<JSObject>();
    }
    DirectHandle<Name> cause_string = isolate_->factory()->cause_string();
    if (JSObject::SetOwnPropertyIgnoreAttributes(error, cause_string, cause,
                                                 DONT_ENUM)
            .is_null()) {
      return MaybeDirectHandle<JSObject>();
    }
    READ_NEXT_ERROR_TAG();
  }
#undef READ_NEXT_ERROR_TAG
  if (static_cast<ErrorTag>(tag) != ErrorTag::kEnd) {
    return MaybeDirectHandle<Object>();
  }
  return error;
}
References AddObjectWithID(), v8::internal::ErrorUtils::Construct(), v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), isolate_, v8::internal::ErrorUtils::kDisabled, v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::kStack, next_id_, READ_NEXT_ERROR_TAG, ReadObject(), ReadString(), v8::internal::ErrorUtils::SetFormattedStack(), v8::internal::JSObject::SetOwnPropertyIgnoreAttributes(), v8::internal::SKIP_NONE, v8::internal::stack, and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by ReadObjectInternal().
ReadJSMap()
MaybeDirectHandle< JSMap > v8::internal::ValueDeserializer::ReadJSMap () [private]
Definition at line 2025 of file value-serializer.cc.
                                                      {
  // If we are at the end of the stack, abort. This function may recurse.
  STACK_CHECK(isolate_, MaybeDirectHandle<JSMap>());
  HandleScope scope(isolate_);
  uint32_t id = next_id_++;
  DirectHandle<JSMap> map = isolate_->factory()->NewJSMap();
  AddObjectWithID(id, map);
  DirectHandle<JSFunction> map_set = isolate_->map_set();
  uint32_t length = 0;
  while (true) {
    SerializationTag tag;
    if (!PeekTag().To(&tag)) return MaybeDirectHandle<JSMap>();
    if (tag == SerializationTag::kEndJSMap) {
      ConsumeTag(SerializationTag::kEndJSMap);
      break;
    }
    DirectHandle<Object> args[2];
    if (!ReadObject().ToHandle(&args[0]) || !ReadObject().ToHandle(&args[1])) {
      return MaybeDirectHandle<JSMap>();
    }
    AllowJavascriptExecution allow_js(isolate_);
    if (Execution::Call(isolate_, map_set, map, base::VectorOf(args))
            .is_null()) {
      return MaybeDirectHandle<JSMap>();
    }
    length += 2;
  }
  uint32_t expected_length;
  if (!ReadVarint<uint32_t>().To(&expected_length) ||
      length != expected_length) {
    return MaybeDirectHandle<JSMap>();
  }
  DCHECK(HasObjectWithID(id));
  return scope.CloseAndEscape(map);
}
References AddObjectWithID(), v8::base::args, v8::internal::Execution::Call(), ConsumeTag(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), HasObjectWithID(), isolate_, v8::internal::kEndJSMap, v8::internal::length, v8::internal::Factory::NewJSMap(), next_id_, PeekTag(), ReadObject(), STACK_CHECK, v8::anonymous_namespace{api.cc}::ToHandle(), and v8::base::VectorOf().
Referenced by ReadObjectInternal().
ReadJSObject()
MaybeDirectHandle< JSObject > v8::internal::ValueDeserializer::ReadJSObject () [private]
Definition at line 1820 of file value-serializer.cc.
                                                            {
  // If we are at the end of the stack, abort. This function may recurse.
  STACK_CHECK(isolate_, MaybeDirectHandle<JSObject>());
  uint32_t id = next_id_++;
  HandleScope scope(isolate_);
  DirectHandle<JSObject> object =
      isolate_->factory()->NewJSObject(isolate_->object_function());
  AddObjectWithID(id, object);
  uint32_t num_properties;
  uint32_t expected_num_properties;
  if (!ReadJSObjectProperties(object, SerializationTag::kEndJSObject, true)
           .To(&num_properties) ||
      !ReadVarint<uint32_t>().To(&expected_num_properties) ||
      num_properties != expected_num_properties) {
    return MaybeDirectHandle<JSObject>();
  }
  DCHECK(HasObjectWithID(id));
  return scope.CloseAndEscape(object);
}
References AddObjectWithID(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), HasObjectWithID(), isolate_, v8::internal::kEndJSObject, v8::internal::Factory::NewJSObject(), next_id_, ReadJSObjectProperties(), and STACK_CHECK.
Referenced by ReadObjectInternal().
ReadJSObjectProperties()
Maybe< uint32_t > v8::internal::ValueDeserializer::ReadJSObjectProperties (DirectHandle< JSObject > object, SerializationTag end_tag, bool can_use_transitions) [private]
Definition at line 2543 of file value-serializer.cc.
                              {
  uint32_t num_properties = 0;
  // Fast path (following map transitions).
  if (can_use_transitions) {
    bool transitioning = true;
    DirectHandle<Map> map(object->map(), isolate_);
    DCHECK(!map->is_dictionary_map());
    DCHECK_EQ(0, map->instance_descriptors(isolate_)->number_of_descriptors());
    DirectHandleVector<Object> properties(isolate_);
    properties.reserve(8);
    while (transitioning) {
      // If there are no more properties, finish.
      SerializationTag tag;
      if (!PeekTag().To(&tag)) return Nothing<uint32_t>();
      if (tag == end_tag) {
        ConsumeTag(end_tag);
        CommitProperties(isolate_, object, map, base::VectorOf(properties));
        CHECK_LT(properties.size(), std::numeric_limits<uint32_t>::max());
        return Just(static_cast<uint32_t>(properties.size()));
      }
      // Determine the key to be used and the target map to transition to, if
      // possible. Transitioning may abort if the key is not a string, or if no
      // transition was found.
      DirectHandle<Object> key;
      DirectHandle<Map> target;
      bool transition_was_found = false;
      const uint8_t* start_position = position_;
      uint32_t byte_length;
      if (!ReadTag().To(&tag) || !ReadVarint<uint32_t>().To(&byte_length)) {
        return Nothing<uint32_t>();
      }
      // Length is also checked in ReadRawBytes.
#ifdef V8_VALUE_DESERIALIZER_HARD_FAIL
      CHECK_LE(byte_length,
               static_cast<uint32_t>(std::numeric_limits<int32_t>::max()));
#endif // V8_VALUE_DESERIALIZER_HARD_FAIL
      std::pair<DirectHandle<String>, DirectHandle<Map>> expected_transition;
      {
        TransitionsAccessor transitions(isolate_, *map);
        if (tag == SerializationTag::kOneByteString) {
          base::Vector<const uint8_t> key_chars;
          if (ReadRawBytes(byte_length).To(&key_chars)) {
            expected_transition = transitions.ExpectedTransition(key_chars);
          }
        } else if (tag == SerializationTag::kTwoByteString) {
          base::Vector<const base::uc16> key_chars;
          if (ReadRawTwoBytes(byte_length).To(&key_chars)) {
            expected_transition = transitions.ExpectedTransition(key_chars);
          }
        } else if (tag == SerializationTag::kUtf8String) {
          base::Vector<const uint8_t> key_chars;
          if (ReadRawBytes(byte_length).To(&key_chars) &&
              String::IsAscii(key_chars.begin(), key_chars.length())) {
            expected_transition = transitions.ExpectedTransition(key_chars);
          }
        }
        if (!expected_transition.first.is_null()) {
          transition_was_found = true;
          key = expected_transition.first;
          target = expected_transition.second;
        }
      }
      if (!transition_was_found) {
        position_ = start_position;
        if (!ReadObject().ToHandle(&key) || !IsValidObjectKey(*key, isolate_)) {
          return Nothing<uint32_t>();
        }
        if (IsString(*key, isolate_)) {
          key = isolate_->factory()->InternalizeString(Cast<String>(key));
          // Don't reuse |transitions| because it could be stale.
          transitioning = TransitionsAccessor(isolate_, *map)
                              .FindTransitionToField(Cast<String>(key))
                              .ToHandle(&target);
        } else {
          transitioning = false;
        }
      }
      // Read the value that corresponds to it.
      DirectHandle<Object> value;
      if (!ReadObject().ToHandle(&value)) return Nothing<uint32_t>();
      // If still transitioning and the value fits the field representation
      // (though generalization may be required), store the property value so
      // that we can copy them all at once. Otherwise, stop transitioning.
      if (transitioning) {
        // Deserializaton of |value| might have deprecated current |target|,
        // ensure we are working with the up-to-date version.
        target = Map::Update(isolate_, target);
        if (!target->is_dictionary_map()) {
          InternalIndex descriptor(properties.size());
          PropertyDetails details =
              target->instance_descriptors(isolate_)->GetDetails(descriptor);
          Representation expected_representation = details.representation();
          if (Object::FitsRepresentation(*value, expected_representation)) {
            if (expected_representation.IsHeapObject() &&
                !FieldType::NowContains(
                    target->instance_descriptors(isolate_)->GetFieldType(
                        descriptor),
                    value)) {
              DirectHandle<FieldType> value_type = Object::OptimalType(
                  *value, isolate_, expected_representation);
              MapUpdater::GeneralizeField(isolate_, target, descriptor,
                                          details.constness(),
                                          expected_representation, value_type);
            }
            DCHECK(FieldType::NowContains(
                target->instance_descriptors(isolate_)->GetFieldType(
                    descriptor),
                value));
            properties.push_back(value);
            map = target;
            continue;
          }
        }
        transitioning = false;
      }
      // Fell out of transitioning fast path. Commit the properties gathered so
      // far, and then start setting properties slowly instead.
      DCHECK(!transitioning);
      CHECK_LT(properties.size(), std::numeric_limits<uint32_t>::max());
      CHECK(!map->is_dictionary_map());
      CommitProperties(isolate_, object, map, base::VectorOf(properties));
      num_properties = static_cast<uint32_t>(properties.size());
      // We checked earlier that IsValidObjectKey(key).
      PropertyKey lookup_key(isolate_, key);
      LookupIterator it(isolate_, object, lookup_key, LookupIterator::OWN);
      if (it.state() != LookupIterator::NOT_FOUND ||
          JSObject::DefineOwnPropertyIgnoreAttributes(&it, value, NONE)
              .is_null()) {
        return Nothing<uint32_t>();
      }
      num_properties++;
    }
    // At this point, transitioning should be done, but at least one property
    // should have been written (in the zero-property case, there is an early
    // return).
    DCHECK(!transitioning);
    DCHECK_GE(num_properties, 1u);
  }
  // Slow path.
  for (;; num_properties++) {
    SerializationTag tag;
    if (!PeekTag().To(&tag)) return Nothing<uint32_t>();
    if (tag == end_tag) {
      ConsumeTag(end_tag);
      return Just(num_properties);
    }
    DirectHandle<Object> key;
    if (!ReadObject().ToHandle(&key) || !IsValidObjectKey(*key, isolate_)) {
      return Nothing<uint32_t>();
    }
    DirectHandle<Object> value;
    if (!ReadObject().ToHandle(&value)) return Nothing<uint32_t>();
    // We checked earlier that IsValidObjectKey(key).
    PropertyKey lookup_key(isolate_, key);
    LookupIterator it(isolate_, object, lookup_key, LookupIterator::OWN);
    if (it.state() != LookupIterator::NOT_FOUND ||
        JSObject::DefineOwnPropertyIgnoreAttributes(&it, value, NONE)
            .is_null()) {
      return Nothing<uint32_t>();
    }
  }
}
References v8::base::Vector< T >::begin(), CHECK, CHECK_LE, CHECK_LT, v8::internal::CommitProperties(), v8::internal::PropertyDetails::constness(), ConsumeTag(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::TransitionsAccessor::ExpectedTransition(), v8::internal::Isolate::factory(), v8::internal::TransitionsAccessor::FindTransitionToField(), v8::internal::Object::FitsRepresentation(), v8::internal::MapUpdater::GeneralizeField(), v8::internal::Factory::InternalizeString(), v8::internal::String::IsAscii(), v8::internal::Representation::IsHeapObject(), isolate_, v8::internal::IsValidObjectKey(), v8::Just(), v8::internal::key, v8::internal::kOneByteString, v8::internal::kTwoByteString, v8::internal::kUtf8String, v8::base::Vector< T >::length(), v8::internal::NONE, v8::internal::LookupIterator::NOT_FOUND, v8::internal::FieldType::NowContains(), v8::internal::Object::OptimalType(), v8::internal::LookupIterator::OWN, PeekTag(), position_, v8::internal::DirectHandleVector< T >::push_back(), ReadObject(), ReadRawBytes(), ReadRawTwoBytes(), ReadTag(), v8::internal::PropertyDetails::representation(), v8::internal::DirectHandleVector< T >::reserve(), v8::internal::DirectHandleVector< T >::size(), v8::internal::LookupIterator::state(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::Map::Update(), v8::internal::value, v8::internal::wasm::value_type(), and v8::base::VectorOf().
Referenced by ReadDenseJSArray(), ReadJSObject(), and ReadSparseJSArray().
ReadJSPrimitiveWrapper()
MaybeDirectHandle< JSPrimitiveWrapper > v8::internal::ValueDeserializer::ReadJSPrimitiveWrapper (SerializationTag tag) [private]
Definition at line 1947 of file value-serializer.cc.
                          {
  uint32_t id = next_id_++;
  DirectHandle<JSPrimitiveWrapper> value;
  switch (tag) {
    case SerializationTag::kTrueObject:
      value = Cast<JSPrimitiveWrapper>(
          isolate_->factory()->NewJSObject(isolate_->boolean_function()));
      value->set_value(ReadOnlyRoots(isolate_).true_value());
      break;
    case SerializationTag::kFalseObject:
      value = Cast<JSPrimitiveWrapper>(
          isolate_->factory()->NewJSObject(isolate_->boolean_function()));
      value->set_value(ReadOnlyRoots(isolate_).false_value());
      break;
    case SerializationTag::kNumberObject: {
      double number;
      if (!ReadDouble().To(&number))
        return MaybeDirectHandle<JSPrimitiveWrapper>();
      value = Cast<JSPrimitiveWrapper>(
          isolate_->factory()->NewJSObject(isolate_->number_function()));
      DirectHandle<Number> number_object =
          isolate_->factory()->NewNumber(number);
      value->set_value(*number_object);
      break;
    }
    case SerializationTag::kBigIntObject: {
      DirectHandle<BigInt> bigint;
      if (!ReadBigInt().ToHandle(&bigint))
        return MaybeDirectHandle<JSPrimitiveWrapper>();
      value = Cast<JSPrimitiveWrapper>(
          isolate_->factory()->NewJSObject(isolate_->bigint_function()));
      value->set_value(*bigint);
      break;
    }
    case SerializationTag::kStringObject: {
      DirectHandle<String> string;
      if (!ReadString().ToHandle(&string))
        return MaybeDirectHandle<JSPrimitiveWrapper>();
      value = Cast<JSPrimitiveWrapper>(
          isolate_->factory()->NewJSObject(isolate_->string_function()));
      value->set_value(*string);
      break;
    }
    default:
      UNREACHABLE();
  }
  AddObjectWithID(id, value);
  return value;
}
References AddObjectWithID(), v8::internal::Isolate::factory(), isolate_, v8::internal::kBigIntObject, v8::internal::kFalseObject, v8::internal::kNumberObject, v8::internal::kStringObject, v8::internal::kTrueObject, v8::internal::Factory::NewJSObject(), v8::internal::FactoryBase< Impl >::NewNumber(), next_id_, ReadBigInt(), ReadDouble(), ReadString(), v8::internal::string, v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by ReadObjectInternal().
ReadJSRegExp()
MaybeDirectHandle< JSRegExp > v8::internal::ValueDeserializer::ReadJSRegExp () [private]
Definition at line 1998 of file value-serializer.cc.
                                                            {
  uint32_t id = next_id_++;
  DirectHandle<String> pattern;
  uint32_t raw_flags;
  DirectHandle<JSRegExp> regexp;
  if (!ReadString().ToHandle(&pattern) ||
      !ReadVarint<uint32_t>().To(&raw_flags)) {
    return MaybeDirectHandle<JSRegExp>();
  }
  // Ensure the deserialized flags are valid.
  uint32_t bad_flags_mask = static_cast<uint32_t>(-1) << JSRegExp::kFlagCount;
  // kLinear is accepted only with the appropriate flag.
  if (!v8_flags.enable_experimental_regexp_engine) {
    bad_flags_mask |= JSRegExp::kLinear;
  }
  if ((raw_flags & bad_flags_mask) ||
      !RegExp::VerifyFlags(static_cast<RegExpFlags>(raw_flags)) ||
      !JSRegExp::New(isolate_, pattern, static_cast<JSRegExp::Flags>(raw_flags))
           .ToHandle(&regexp)) {
    return MaybeDirectHandle<JSRegExp>();
  }
  AddObjectWithID(id, regexp);
  return regexp;
}
References AddObjectWithID(), v8::internal::Flags(), isolate_, v8::internal::JSRegExp::New(), next_id_, ReadString(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::v8_flags, and v8::internal::RegExp::VerifyFlags().
Referenced by ReadObjectInternal().
ReadJSSet()
MaybeDirectHandle< JSSet > v8::internal::ValueDeserializer::ReadJSSet () [private]
Definition at line 2066 of file value-serializer.cc.
                                                      {
  // If we are at the end of the stack, abort. This function may recurse.
  STACK_CHECK(isolate_, MaybeDirectHandle<JSSet>());
  HandleScope scope(isolate_);
  uint32_t id = next_id_++;
  DirectHandle<JSSet> set = isolate_->factory()->NewJSSet();
  AddObjectWithID(id, set);
  DirectHandle<JSFunction> set_add = isolate_->set_add();
  uint32_t length = 0;
  while (true) {
    SerializationTag tag;
    if (!PeekTag().To(&tag)) return MaybeDirectHandle<JSSet>();
    if (tag == SerializationTag::kEndJSSet) {
      ConsumeTag(SerializationTag::kEndJSSet);
      break;
    }
    DirectHandle<Object> args[1];
    if (!ReadObject().ToHandle(&args[0])) return MaybeDirectHandle<JSSet>();
    AllowJavascriptExecution allow_js(isolate_);
    if (Execution::Call(isolate_, set_add, set, base::VectorOf(args))
            .is_null()) {
      return MaybeDirectHandle<JSSet>();
    }
    length++;
  }
  uint32_t expected_length;
  if (!ReadVarint<uint32_t>().To(&expected_length) ||
      length != expected_length) {
    return MaybeDirectHandle<JSSet>();
  }
  DCHECK(HasObjectWithID(id));
  return scope.CloseAndEscape(set);
}
References AddObjectWithID(), v8::base::args, v8::internal::Execution::Call(), ConsumeTag(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), HasObjectWithID(), isolate_, v8::internal::kEndJSSet, v8::internal::length, v8::internal::Factory::NewJSSet(), next_id_, PeekTag(), ReadObject(), STACK_CHECK, v8::anonymous_namespace{api.cc}::ToHandle(), and v8::base::VectorOf().
Referenced by ReadObjectInternal().
ReadObject()
MaybeDirectHandle< Object > v8::internal::ValueDeserializer::ReadObject () [private]
Definition at line 1610 of file value-serializer.cc.
                                                        {
  DisallowJavascriptExecution no_js(isolate_);
  // If we are at the end of the stack, abort. This function may recurse.
  STACK_CHECK(isolate_, MaybeDirectHandle<Object>());
  MaybeDirectHandle<Object> result = ReadObjectInternal();
  // ArrayBufferView is special in that it consumes the value before it, even
  // after format version 0.
  DirectHandle<Object> object;
  SerializationTag tag;
  if (result.ToHandle(&object) && V8_UNLIKELY(IsJSArrayBuffer(*object)) &&
      PeekTag().To(&tag) && tag == SerializationTag::kArrayBufferView) {
    ConsumeTag(SerializationTag::kArrayBufferView);
    result = ReadJSArrayBufferView(Cast<JSArrayBuffer>(object));
  }
  if (result.is_null() && !suppress_deserialization_errors_ &&
      !isolate_->has_exception()) {
    isolate_->Throw(*isolate_->factory()->NewError(
        MessageTemplate::kDataCloneDeserializationError));
  }
#if defined(DEBUG) && defined(VERIFY_HEAP)
  if (!result.is_null() && v8_flags.enable_slow_asserts &&
      v8_flags.verify_heap) {
    Object::ObjectVerify(*object, isolate_);
  }
#endif
  return result;
}
References ConsumeTag(), v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), isolate_, v8::internal::kArrayBufferView, v8::internal::Factory::NewError(), PeekTag(), ReadJSArrayBufferView(), ReadObjectInternal(), v8::base::internal::result, STACK_CHECK, suppress_deserialization_errors_, v8::internal::Isolate::Throw(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by ReadDenseJSArray(), ReadJSArrayBuffer(), ReadJSError(), ReadJSMap(), ReadJSObjectProperties(), ReadJSSet(), ReadObjectInternal(), ReadObjectUsingEntireBufferForLegacyFormat(), ReadObjectWrapper(), and ReadString().
ReadObjectInternal()
MaybeDirectHandle< Object > v8::internal::ValueDeserializer::ReadObjectInternal () [private]
Definition at line 1642 of file value-serializer.cc.
                                                                {
  SerializationTag tag;
  if (!ReadTag().To(&tag)) return MaybeDirectHandle<Object>();
  switch (tag) {
    case SerializationTag::kVerifyObjectCount:
      // Read the count and ignore it.
      if (ReadVarint<uint32_t>().IsNothing())
        return MaybeDirectHandle<Object>();
      return ReadObject();
    case SerializationTag::kUndefined:
      return isolate_->factory()->undefined_value();
    case SerializationTag::kNull:
      return isolate_->factory()->null_value();
    case SerializationTag::kTrue:
      return isolate_->factory()->true_value();
    case SerializationTag::kFalse:
      return isolate_->factory()->false_value();
    case SerializationTag::kInt32: {
      Maybe<int32_t> number = ReadZigZag<int32_t>();
      if (number.IsNothing()) return MaybeDirectHandle<Object>();
      return isolate_->factory()->NewNumberFromInt(number.FromJust());
    }
    case SerializationTag::kUint32: {
      Maybe<uint32_t> number = ReadVarint<uint32_t>();
      if (number.IsNothing()) return MaybeDirectHandle<Object>();
      return isolate_->factory()->NewNumberFromUint(number.FromJust());
    }
    case SerializationTag::kDouble: {
      Maybe<double> number = ReadDouble();
      if (number.IsNothing()) return MaybeDirectHandle<Object>();
      return isolate_->factory()->NewNumber(number.FromJust());
    }
    case SerializationTag::kBigInt:
      return ReadBigInt();
    case SerializationTag::kUtf8String:
      return ReadUtf8String();
    case SerializationTag::kOneByteString:
      return ReadOneByteString();
    case SerializationTag::kTwoByteString:
      return ReadTwoByteString();
    case SerializationTag::kObjectReference: {
      uint32_t id;
      if (!ReadVarint<uint32_t>().To(&id)) return MaybeDirectHandle<Object>();
      return GetObjectWithID(id);
    }
    case SerializationTag::kBeginJSObject:
      return ReadJSObject();
    case SerializationTag::kBeginSparseJSArray:
      return ReadSparseJSArray();
    case SerializationTag::kBeginDenseJSArray:
      return ReadDenseJSArray();
    case SerializationTag::kDate:
      return ReadJSDate();
    case SerializationTag::kTrueObject:
    case SerializationTag::kFalseObject:
    case SerializationTag::kNumberObject:
    case SerializationTag::kBigIntObject:
    case SerializationTag::kStringObject:
      return ReadJSPrimitiveWrapper(tag);
    case SerializationTag::kRegExp:
      return ReadJSRegExp();
    case SerializationTag::kBeginJSMap:
      return ReadJSMap();
    case SerializationTag::kBeginJSSet:
      return ReadJSSet();
    case SerializationTag::kArrayBuffer: {
      constexpr bool is_shared = false;
      constexpr bool is_resizable = false;
      return ReadJSArrayBuffer(is_shared, is_resizable);
    }
    case SerializationTag::kResizableArrayBuffer: {
      constexpr bool is_shared = false;
      constexpr bool is_resizable = true;
      return ReadJSArrayBuffer(is_shared, is_resizable);
    }
    case SerializationTag::kArrayBufferTransfer: {
      return ReadTransferredJSArrayBuffer();
    }
    case SerializationTag::kSharedArrayBuffer: {
      constexpr bool is_shared = true;
      constexpr bool is_resizable = false;
      return ReadJSArrayBuffer(is_shared, is_resizable);
    }
    case SerializationTag::kError:
      return ReadJSError();
#if V8_ENABLE_WEBASSEMBLY
    case SerializationTag::kWasmModuleTransfer:
      return ReadWasmModuleTransfer();
    case SerializationTag::kWasmMemoryTransfer:
      return ReadWasmMemory();
#endif // V8_ENABLE_WEBASSEMBLY
    case SerializationTag::kHostObject:
      return ReadHostObject();
    case SerializationTag::kSharedObject:
      if (version_ >= 15) return ReadSharedObject();
      // If the data doesn't support shared values because it is from an older
      // version, treat the tag as unknown.
      [[fallthrough]];
    default:
      // Before there was an explicit tag for host objects, all unknown tags
      // were delegated to the host.
      if (version_ < 13) {
        position_--;
        return ReadHostObject();
      }
      return MaybeDirectHandle<Object>();
  }
}
References v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), GetObjectWithID(), v8::internal::is_shared, v8::Maybe< T >::IsNothing(), isolate_, v8::internal::kArrayBuffer, v8::internal::kArrayBufferTransfer, v8::internal::kBeginDenseJSArray, v8::internal::kBeginJSMap, v8::internal::kBeginJSObject, v8::internal::kBeginJSSet, v8::internal::kBeginSparseJSArray, v8::internal::kBigInt, v8::internal::kBigIntObject, v8::internal::kDate, v8::internal::kDouble, v8::internal::kError, v8::internal::kFalse, v8::internal::kFalseObject, v8::internal::kHostObject, v8::internal::kInt32, v8::internal::kNull, v8::internal::kNumberObject, v8::internal::kObjectReference, v8::internal::kOneByteString, v8::internal::kRegExp, v8::internal::kResizableArrayBuffer, v8::internal::kSharedArrayBuffer, v8::internal::kSharedObject, v8::internal::kStringObject, v8::internal::kTrue, v8::internal::kTrueObject, v8::internal::kTwoByteString, v8::internal::kUint32, v8::internal::kUndefined, v8::internal::kUtf8String, v8::internal::kVerifyObjectCount, v8::internal::kWasmMemoryTransfer, v8::internal::kWasmModuleTransfer, v8::internal::FactoryBase< Impl >::NewNumber(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), v8::internal::FactoryBase< Impl >::NewNumberFromUint(), position_, ReadBigInt(), ReadDenseJSArray(), ReadDouble(), ReadHostObject(), ReadJSArrayBuffer(), ReadJSDate(), ReadJSError(), ReadJSMap(), ReadJSObject(), ReadJSPrimitiveWrapper(), ReadJSRegExp(), ReadJSSet(), ReadObject(), ReadOneByteString(), ReadSharedObject(), ReadSparseJSArray(), ReadTag(), ReadTransferredJSArrayBuffer(), ReadTwoByteString(), ReadUtf8String(), and version_.
Referenced by ReadObject().
ReadObjectUsingEntireBufferForLegacyFormat()
MaybeDirectHandle< Object > v8::internal::ValueDeserializer::ReadObjectUsingEntireBufferForLegacyFormat ()
Definition at line 2767 of file value-serializer.cc.
                                                              {
  DCHECK_EQ(version_, 0u);
  HandleScope scope(isolate_);
  DirectHandleVector<Object> stack(isolate_);
  while (position_ < end_) {
    SerializationTag tag;
    if (!PeekTag().To(&tag)) break;
    DirectHandle<Object> new_object;
    switch (tag) {
      case SerializationTag::kEndJSObject: {
        ConsumeTag(SerializationTag::kEndJSObject);
        // JS Object: Read the last 2*n values from the stack and use them as
        // key-value pairs.
        uint32_t num_properties;
        if (!ReadVarint<uint32_t>().To(&num_properties) ||
            stack.size() / 2 < num_properties) {
          isolate_->Throw(*isolate_->factory()->NewError(
              MessageTemplate::kDataCloneDeserializationError));
          return MaybeDirectHandle<Object>();
        }
        size_t begin_properties =
            stack.size() - 2 * static_cast<size_t>(num_properties);
        DirectHandle<JSObject> js_object =
            isolate_->factory()->NewJSObject(isolate_->object_function());
        if (num_properties &&
            !SetPropertiesFromKeyValuePairs(
                 isolate_, js_object, &stack[begin_properties], num_properties)
                 .FromMaybe(false)) {
          ThrowDeserializationExceptionIfNonePending(isolate_);
          return MaybeDirectHandle<Object>();
        }
        stack.resize(begin_properties);
        new_object = js_object;
        break;
      }
      case SerializationTag::kEndSparseJSArray: {
        ConsumeTag(SerializationTag::kEndSparseJSArray);
        // Sparse JS Array: Read the last 2*|num_properties| from the stack.
        uint32_t num_properties;
        uint32_t length;
        if (!ReadVarint<uint32_t>().To(&num_properties) ||
            !ReadVarint<uint32_t>().To(&length) ||
            stack.size() / 2 < num_properties) {
          isolate_->Throw(*isolate_->factory()->NewError(
              MessageTemplate::kDataCloneDeserializationError));
          return MaybeDirectHandle<Object>();
        }
        DirectHandle<JSArray> js_array =
            isolate_->factory()->NewJSArray(0, TERMINAL_FAST_ELEMENTS_KIND);
        MAYBE_RETURN_NULL(JSArray::SetLength(isolate_, js_array, length));
        size_t begin_properties =
            stack.size() - 2 * static_cast<size_t>(num_properties);
        if (num_properties &&
            !SetPropertiesFromKeyValuePairs(
                 isolate_, js_array, &stack[begin_properties], num_properties)
                 .FromMaybe(false)) {
          ThrowDeserializationExceptionIfNonePending(isolate_);
          return MaybeDirectHandle<Object>();
        }
        stack.resize(begin_properties);
        new_object = js_array;
        break;
      }
      case SerializationTag::kEndDenseJSArray: {
        // This was already broken in Chromium, and apparently wasn't missed.
        isolate_->Throw(*isolate_->factory()->NewError(
            MessageTemplate::kDataCloneDeserializationError));
        return MaybeDirectHandle<Object>();
      }
      default:
        if (!ReadObject().ToHandle(&new_object))
          return MaybeDirectHandle<Object>();
        break;
    }
    stack.push_back(new_object);
  }
// Nothing remains but padding.
#ifdef DEBUG
  while (position_ < end_) {
    DCHECK(*position_++ == static_cast<uint8_t>(SerializationTag::kPadding));
  }
#endif
  position_ = end_;
  if (stack.size() != 1) {
    isolate_->Throw(*isolate_->factory()->NewError(
        MessageTemplate::kDataCloneDeserializationError));
    return MaybeDirectHandle<Object>();
  }
  return scope.CloseAndEscape(stack[0]);
}
References ConsumeTag(), v8::internal::DCHECK(), DCHECK_EQ, end_, v8::internal::Isolate::factory(), isolate_, v8::internal::kEndDenseJSArray, v8::internal::kEndJSObject, v8::internal::kEndSparseJSArray, v8::internal::kPadding, v8::internal::length, MAYBE_RETURN_NULL, v8::internal::Factory::NewError(), v8::internal::Factory::NewJSArray(), v8::internal::Factory::NewJSObject(), PeekTag(), position_, ReadObject(), v8::internal::JSArray::SetLength(), v8::internal::SetPropertiesFromKeyValuePairs(), v8::internal::stack, v8::internal::TERMINAL_FAST_ELEMENTS_KIND, v8::internal::Isolate::Throw(), v8::internal::anonymous_namespace{value-serializer.cc}::ThrowDeserializationExceptionIfNonePending(), v8::anonymous_namespace{api.cc}::ToHandle(), and version_.
Referenced by v8::ValueDeserializer::ReadValue().
ReadObjectWrapper()
MaybeDirectHandle< Object > v8::internal::ValueDeserializer::ReadObjectWrapper ()
Definition at line 1585 of file value-serializer.cc.
                                                               {
  // We had a bug which produced invalid version 13 data (see
  // crbug.com/1284506). This compatibility mode tries to first read the data
  // normally, and if it fails, and the version is 13, tries to read the broken
  // format.
  const uint8_t* original_position = position_;
  suppress_deserialization_errors_ = true;
  MaybeDirectHandle<Object> result = ReadObject();
  // The deserialization code doesn't throw errors for invalid data. It throws
  // errors for stack overflows, though, and in that case we won't retry.
  if (result.is_null() && version_ == 13 && !isolate_->has_exception()) {
    version_13_broken_data_mode_ = true;
    position_ = original_position;
    result = ReadObject();
  }
  if (result.is_null() && !isolate_->has_exception()) {
    isolate_->Throw(*isolate_->factory()->NewError(
        MessageTemplate::kDataCloneDeserializationError));
  }
  return result;
}
References v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), isolate_, v8::internal::Factory::NewError(), position_, ReadObject(), v8::base::internal::result, suppress_deserialization_errors_, v8::internal::Isolate::Throw(), version_, and version_13_broken_data_mode_.
Referenced by v8::ValueDeserializer::ReadValue().
ReadOneByteString()
MaybeDirectHandle< String > v8::internal::ValueDeserializer::ReadOneByteString (AllocationType allocation = AllocationType::kYoung) [private]
Definition at line 1782 of file value-serializer.cc.
                               {
  uint32_t byte_length;
  base::Vector<const uint8_t> bytes;
  if (!ReadVarint<uint32_t>().To(&byte_length)) return {};
  // byte_length is checked in ReadRawBytes.
  if (!ReadRawBytes(byte_length).To(&bytes)) return {};
  return isolate_->factory()->NewStringFromOneByte(bytes, allocation);
}
References v8::internal::Isolate::factory(), isolate_, v8::internal::FactoryBase< Impl >::NewStringFromOneByte(), and ReadRawBytes().
Referenced by ReadObjectInternal().
ReadRawBytes() [1/2]
bool v8::internal::ValueDeserializer::ReadRawBytes (size_t length, const void ** data)
Definition at line 1560 of file value-serializer.cc.
                                                                     {
  if (length > static_cast<size_t>(end_ - position_)) return false;
  *data = position_;
  position_ += length;
  return true;
}
References end_, v8::internal::length, and position_.
Referenced by ReadBigInt(), ReadJSObjectProperties(), ReadOneByteString(), v8::ValueDeserializer::ReadRawBytes(), ReadTwoByteString(), and ReadUtf8String().
ReadRawBytes() [2/2]
Maybe< base::Vector< const uint8_t > > v8::internal::ValueDeserializer::ReadRawBytes (size_t size) [private]
Definition at line 1519 of file value-serializer.cc.
                 {
  if (size > static_cast<size_t>(end_ - position_)) {
    return Nothing<base::Vector<const uint8_t>>();
  }
  const uint8_t* start = position_;
  position_ += size;
  return Just(base::Vector<const uint8_t>(start, size));
}
References end_, v8::Just(), position_, and size().
ReadRawTwoBytes()
Maybe< base::Vector< const base::uc16 > > v8::internal::ValueDeserializer::ReadRawTwoBytes (size_t size) [private]
Definition at line 1529 of file value-serializer.cc.
                 {
  if (!IsAligned(reinterpret_cast<uintptr_t>(position_), 2) ||
      size > static_cast<size_t>(end_ - position_) ||
      size % sizeof(base::uc16) != 0) {
    return Nothing<base::Vector<const base::uc16>>();
  }
  const base::uc16* start = (const base::uc16*)(position_);
  position_ += size;
  return Just(base::Vector<const base::uc16>(start, size / sizeof(base::uc16)));
}
References end_, IsAligned(), v8::Just(), position_, and size().
Referenced by ReadJSObjectProperties().
ReadSharedObject()
MaybeDirectHandle< HeapObject > v8::internal::ValueDeserializer::ReadSharedObject () [private]
Definition at line 2472 of file value-serializer.cc.
                                                                  {
  STACK_CHECK(isolate_, MaybeDirectHandle<HeapObject>());
  DCHECK_GE(version_, 15);
  uint32_t shared_object_id;
  if (!ReadVarint<uint32_t>().To(&shared_object_id)) {
    RETURN_EXCEPTION_IF_EXCEPTION(isolate_);
    return MaybeDirectHandle<HeapObject>();
  }
  if (!delegate_) {
    ThrowDeserializationExceptionIfNonePending(isolate_);
    return MaybeDirectHandle<HeapObject>();
  }
  if (shared_object_conveyor_ == nullptr) {
    const v8::SharedValueConveyor* conveyor = delegate_->GetSharedValueConveyor(
        reinterpret_cast<v8::Isolate*>(isolate_));
    if (!conveyor) {
      RETURN_EXCEPTION_IF_EXCEPTION(isolate_);
      return MaybeDirectHandle<HeapObject>();
    }
    shared_object_conveyor_ = conveyor->private_.get();
  }
  DirectHandle<HeapObject> shared_object(
      shared_object_conveyor_->GetPersisted(shared_object_id), isolate_);
  DCHECK(IsShared(*shared_object));
  return shared_object;
}
References v8::internal::DCHECK(), DCHECK_GE, delegate_, v8::internal::SharedObjectConveyorHandles::GetPersisted(), v8::ValueDeserializer::Delegate::GetSharedValueConveyor(), isolate_, v8::internal::IsShared(), v8::SharedValueConveyor::private_, RETURN_EXCEPTION_IF_EXCEPTION, shared_object_conveyor_, STACK_CHECK, v8::internal::anonymous_namespace{value-serializer.cc}::ThrowDeserializationExceptionIfNonePending(), and version_.
Referenced by ReadObjectInternal().
ReadSparseJSArray()
MaybeDirectHandle< JSArray > v8::internal::ValueDeserializer::ReadSparseJSArray () [private]
Definition at line 1843 of file value-serializer.cc.
                                                                {
  // If we are at the end of the stack, abort. This function may recurse.
  STACK_CHECK(isolate_, MaybeDirectHandle<JSArray>());
  uint32_t length;
  if (!ReadVarint<uint32_t>().To(&length)) return MaybeDirectHandle<JSArray>();
  uint32_t id = next_id_++;
  HandleScope scope(isolate_);
  DirectHandle<JSArray> array =
      isolate_->factory()->NewJSArray(0, TERMINAL_FAST_ELEMENTS_KIND);
  MAYBE_RETURN(JSArray::SetLength(isolate_, array, length),
               MaybeDirectHandle<JSArray>());
  AddObjectWithID(id, array);
  uint32_t num_properties;
  uint32_t expected_num_properties;
  uint32_t expected_length;
  if (!ReadJSObjectProperties(array, SerializationTag::kEndSparseJSArray, false)
           .To(&num_properties) ||
      !ReadVarint<uint32_t>().To(&expected_num_properties) ||
      !ReadVarint<uint32_t>().To(&expected_length) ||
      num_properties != expected_num_properties || length != expected_length) {
    return MaybeDirectHandle<JSArray>();
  }
  DCHECK(HasObjectWithID(id));
  return scope.CloseAndEscape(array);
}
References AddObjectWithID(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), HasObjectWithID(), isolate_, v8::internal::kEndSparseJSArray, v8::internal::length, MAYBE_RETURN, v8::internal::Factory::NewJSArray(), next_id_, ReadJSObjectProperties(), v8::internal::JSArray::SetLength(), STACK_CHECK, and v8::internal::TERMINAL_FAST_ELEMENTS_KIND.
Referenced by ReadObjectInternal().
ReadString()
MaybeDirectHandle< String > v8::internal::ValueDeserializer::ReadString () [private]
Definition at line 1751 of file value-serializer.cc.
                                                        {
  if (version_ < 12) return ReadUtf8String();
  DirectHandle<Object> object;
  if (!ReadObject().ToHandle(&object) || !IsString(*object, isolate_)) {
    return MaybeDirectHandle<String>();
  }
  return Cast<String>(object);
}
References isolate_, ReadObject(), ReadUtf8String(), v8::anonymous_namespace{api.cc}::ToHandle(), and version_.
Referenced by ReadJSError(), ReadJSPrimitiveWrapper(), and ReadJSRegExp().
ReadTag()
Maybe< SerializationTag > v8::internal::ValueDeserializer::ReadTag () [private]
Definition at line 1398 of file value-serializer.cc.
                                                   {
  SerializationTag tag;
  do {
    if (position_ >= end_) return Nothing<SerializationTag>();
    tag = static_cast<SerializationTag>(*position_);
    position_++;
  } while (tag == SerializationTag::kPadding);
  return Just(tag);
}
References end_, v8::Just(), v8::internal::kPadding, and position_.
Referenced by ConsumeTag(), ReadHeader(), ReadJSObjectProperties(), and ReadObjectInternal().
ReadTransferredJSArrayBuffer()
MaybeDirectHandle< JSArrayBuffer > v8::internal::ValueDeserializer::ReadTransferredJSArrayBuffer () [private]
Definition at line 2190 of file value-serializer.cc.
                                                {
  uint32_t id = next_id_++;
  uint32_t transfer_id;
  DirectHandle<SimpleNumberDictionary> transfer_map;
  if (!ReadVarint<uint32_t>().To(&transfer_id) ||
      !array_buffer_transfer_map_.ToHandle(&transfer_map)) {
    return MaybeDirectHandle<JSArrayBuffer>();
  }
  InternalIndex index = transfer_map->FindEntry(isolate_, transfer_id);
  if (index.is_not_found()) {
    return MaybeDirectHandle<JSArrayBuffer>();
  }
  DirectHandle<JSArrayBuffer> array_buffer(
      Cast<JSArrayBuffer>(transfer_map->ValueAt(index)), isolate_);
  AddObjectWithID(id, array_buffer);
  return array_buffer;
}
References AddObjectWithID(), array_buffer_transfer_map_, v8::internal::index, isolate_, and next_id_.
Referenced by ReadObjectInternal().
ReadTwoByteString()
MaybeDirectHandle< String > v8::internal::ValueDeserializer::ReadTwoByteString (AllocationType allocation = AllocationType::kYoung) [private]
Definition at line 1792 of file value-serializer.cc.
                               {
  uint32_t byte_length;
  base::Vector<const uint8_t> bytes;
  if (!ReadVarint<uint32_t>().To(&byte_length)) return {};
  // byte_length is checked in ReadRawBytes.
  if (byte_length % sizeof(base::uc16) != 0 ||
      !ReadRawBytes(byte_length).To(&bytes)) {
    return MaybeDirectHandle<String>();
  }
  // Allocate an uninitialized string so that we can do a raw memcpy into the
  // string on the heap (regardless of alignment).
  if (byte_length == 0) return isolate_->factory()->empty_string();
  DirectHandle<SeqTwoByteString> string;
  if (!isolate_->factory()
           ->NewRawTwoByteString(byte_length / sizeof(base::uc16), allocation)
           .ToHandle(&string)) {
    return MaybeDirectHandle<String>();
  }
  // Copy the bytes directly into the new string.
  // Warning: this uses host endianness.
  DisallowGarbageCollection no_gc;
  memcpy(string->GetChars(no_gc), bytes.begin(), bytes.length());
  return string;
}
References v8::base::Vector< T >::begin(), v8::internal::Isolate::factory(), isolate_, v8::base::Vector< T >::length(), v8::internal::FactoryBase< Impl >::NewRawTwoByteString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, ReadRawBytes(), and v8::internal::string.
Referenced by ReadObjectInternal().
ReadUint32()
bool v8::internal::ValueDeserializer::ReadUint32 (uint32_t * value)
Definition at line 1548 of file value-serializer.cc.
                                                  {
  return ReadVarint<uint32_t>().To(value);
}
References v8::internal::value.
Referenced by v8::ValueDeserializer::ReadUint32().
ReadUint64()
bool v8::internal::ValueDeserializer::ReadUint64 (uint64_t * value)
Definition at line 1552 of file value-serializer.cc.
                                                  {
  return ReadVarint<uint64_t>().To(value);
}
References v8::internal::value.
Referenced by v8::ValueDeserializer::ReadUint64().
ReadUtf8String()
MaybeDirectHandle< String > v8::internal::ValueDeserializer::ReadUtf8String (AllocationType allocation = AllocationType::kYoung) [private]
Definition at line 1771 of file value-serializer.cc.
                               {
  uint32_t utf8_length;
  if (!ReadVarint<uint32_t>().To(&utf8_length)) return {};
  // utf8_length is checked in ReadRawBytes.
  base::Vector<const uint8_t> utf8_bytes;
  if (!ReadRawBytes(utf8_length).To(&utf8_bytes)) return {};
  return isolate_->factory()->NewStringFromUtf8(
      base::Vector<const char>::cast(utf8_bytes), allocation);
}
References v8::internal::Isolate::factory(), isolate_, v8::internal::Factory::NewStringFromUtf8(), and ReadRawBytes().
Referenced by ReadObjectInternal(), and ReadString().
ReadVarint()
template<typename T >
Maybe< T > v8::internal::ValueDeserializer::ReadVarint [inline], [private]
Definition at line 1409 of file value-serializer.cc.
                                       {
  // Reads an unsigned integer as a base-128 varint.
  // The number is written, 7 bits at a time, from the least significant to the
  // most significant 7 bits. Each byte, except the last, has the MSB set.
  // If the varint is larger than T, any more significant bits are discarded.
  // See also https://developers.google.com/protocol-buffers/docs/encoding
  static_assert(std::is_integral_v<T> && std::is_unsigned_v<T>,
                "Only unsigned integer types can be read as varints.");
  if (sizeof(T) > 4) return ReadVarintLoop<T>();
  auto max_read_position = position_ + sizeof(T) + 1;
  if (V8_UNLIKELY(max_read_position >= end_)) return ReadVarintLoop<T>();
#ifdef DEBUG
  // DCHECK code to make sure the manually unrolled loop yields the exact
  // same end state and result.
  auto previous_position = position_;
  Maybe<T> maybe_expected_value = ReadVarintLoop<T>();
  // ReadVarintLoop can't return Nothing here; all such conditions have been
  // checked above.
  T expected_value = maybe_expected_value.ToChecked();
  auto expected_position = position_;
  position_ = previous_position;
#endif // DEBUG
#define EXIT_DCHECK() \
  DCHECK_LE(position_, end_); \
  DCHECK_EQ(position_, expected_position); \
  DCHECK_EQ(value, expected_value)
  T value = 0;
#define ITERATION_SHIFTED(shift) \
  if (shift < sizeof(T) * 8) { \
    uint8_t byte = *position_; \
    position_++; \
    if (byte < 0x80) { \
      value |= static_cast<T>(byte) << shift; \
      EXIT_DCHECK(); \
      return Just(value); \
    } else { \
      value |= static_cast<T>(byte & 0x7F) << shift; \
    } \
  }
  // Manually unroll the loop to achieve the best measured performance.
  // This is ~15% faster than ReadVarintLoop.
  ITERATION_SHIFTED(0);
  ITERATION_SHIFTED(7);
  ITERATION_SHIFTED(14);
  ITERATION_SHIFTED(21);
  ITERATION_SHIFTED(28);
  EXIT_DCHECK();
  return Just(value);
#undef ITERATION_SHIFTED
#undef EXIT_DCHECK
}
References end_, EXIT_DCHECK, ITERATION_SHIFTED, v8::Just(), position_, T, v8::Maybe< T >::ToChecked(), V8_UNLIKELY, and v8::internal::value.
ReadVarintLoop() [1/2]
template<typename T >
Maybe<T> v8::internal::ValueDeserializer::ReadVarintLoop ()
Definition at line 1464 of file value-serializer.cc.
                                           {
  static_assert(std::is_integral_v<T> && std::is_unsigned_v<T>,
                "Only unsigned integer types can be read as varints.");
  T value = 0;
  unsigned shift = 0;
  bool has_another_byte;
  do {
    if (position_ >= end_) return Nothing<T>();
    uint8_t byte = *position_;
    has_another_byte = byte & 0x80;
    if (V8_LIKELY(shift < sizeof(T) * 8)) {
      value |= static_cast<T>(byte & 0x7F) << shift;
      shift += 7;
    } else {
      // For consistency with the fast unrolled loop in ReadVarint we return
      // after we have read size(T) + 1 bytes.
#ifdef V8_VALUE_DESERIALIZER_HARD_FAIL
      CHECK(!has_another_byte);
#endif // V8_VALUE_DESERIALIZER_HARD_FAIL
      return Just(value);
    }
    position_++;
  } while (has_another_byte);
  return Just(value);
}
References CHECK, end_, v8::Just(), position_, V8_LIKELY, and v8::internal::value.
ReadVarintLoop() [2/2]
template<typename T >
V8_NOINLINE Maybe<T> v8::internal::ValueDeserializer::ReadVarintLoop () [private]
ReadZigZag()
template<typename T >
Maybe< T > v8::internal::ValueDeserializer::ReadZigZag [private]
Definition at line 1491 of file value-serializer.cc.
                                       {
  // Writes a signed integer as a varint using ZigZag encoding (i.e. 0 is
  // encoded as 0, -1 as 1, 1 as 2, -2 as 3, and so on).
  // See also https://developers.google.com/protocol-buffers/docs/encoding
  static_assert(std::is_integral_v<T> && std::is_signed_v<T>,
                "Only signed integer types can be read as zigzag.");
  using UnsignedT = std::make_unsigned_t<T>;
  UnsignedT unsigned_value;
  if (!ReadVarint<UnsignedT>().To(&unsigned_value)) return Nothing<T>();
  return Just(static_cast<T>((unsigned_value >> 1) ^
                             -static_cast<T>(unsigned_value & 1)));
}
References v8::Just().
TransferArrayBuffer()
void v8::internal::ValueDeserializer::TransferArrayBuffer (uint32_t transfer_id, DirectHandle< JSArrayBuffer > array_buffer)
Definition at line 1567 of file value-serializer.cc.
                                                                    {
  if (array_buffer_transfer_map_.is_null()) {
    array_buffer_transfer_map_ = isolate_->global_handles()->Create(
        *SimpleNumberDictionary::New(isolate_, 0));
  }
  IndirectHandle<SimpleNumberDictionary> dictionary =
      array_buffer_transfer_map_.ToHandleChecked();
  DirectHandle<SimpleNumberDictionary> new_dictionary =
      SimpleNumberDictionary::Set(isolate_, dictionary, transfer_id,
                                  array_buffer);
  if (!new_dictionary.is_identical_to(dictionary)) {
    GlobalHandles::Destroy(dictionary.location());
    array_buffer_transfer_map_ =
        isolate_->global_handles()->Create(*new_dictionary);
  }
}
References array_buffer_transfer_map_, v8::internal::GlobalHandles::Create(), v8::internal::GlobalHandles::Destroy(), v8::internal::Isolate::global_handles(), v8::internal::DirectHandle< T >::is_identical_to(), isolate_, v8::internal::HandleBase::location(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), and v8::internal::SimpleNumberDictionary::Set().
Referenced by v8::ValueDeserializer::TransferArrayBuffer(), and v8::ValueDeserializer::TransferSharedArrayBuffer().
ValidateJSArrayBufferViewFlags()
bool v8::internal::ValueDeserializer::ValidateJSArrayBufferViewFlags (Tagged< JSArrayBuffer > buffer, uint32_t serialized_flags, bool & is_length_tracking, bool & is_backed_by_rab) [private]
Definition at line 2280 of file value-serializer.cc.
                                                      {
  is_length_tracking =
      JSArrayBufferViewIsLengthTracking::decode(serialized_flags);
  is_backed_by_rab = JSArrayBufferViewIsBackedByRab::decode(serialized_flags);
  // TODO(marja): When the version number is bumped the next time, check that
  // serialized_flags doesn't contain spurious 1-bits.
  if (is_backed_by_rab || is_length_tracking) {
    if (!buffer->is_resizable_by_js()) {
      return false;
    }
    if (is_backed_by_rab && buffer->is_shared()) {
      return false;
    }
  }
  // The RAB-ness of the buffer and the TA's "is_backed_by_rab" need to be in
  // sync.
  if (buffer->is_resizable_by_js() && !buffer->is_shared() &&
      !is_backed_by_rab) {
    return false;
  }
  return true;
}
References v8::internal::is_backed_by_rab.
Referenced by ReadJSArrayBufferView().
Member Data Documentation
array_buffer_transfer_map_
MaybeIndirectHandle<SimpleNumberDictionary> v8::internal::ValueDeserializer::array_buffer_transfer_map_ [private]
Definition at line 342 of file value-serializer.h.
Referenced by ReadTransferredJSArrayBuffer(), TransferArrayBuffer(), and ~ValueDeserializer().
delegate_
v8::ValueDeserializer::Delegate* const v8::internal::ValueDeserializer::delegate_ [private]
Definition at line 332 of file value-serializer.h.
Referenced by ReadHostObject(), ReadJSArrayBuffer(), and ReadSharedObject().
end_
const uint8_t* const v8::internal::ValueDeserializer::end_ [private]
Definition at line 334 of file value-serializer.h.
Referenced by PeekTag(), ReadByte(), ReadDenseJSArray(), ReadHeader(), ReadJSArrayBuffer(), ReadObjectUsingEntireBufferForLegacyFormat(), ReadRawBytes(), ReadRawTwoBytes(), ReadTag(), ReadVarint(), ReadVarintLoop(), and ~ValueDeserializer().
id_map_
IndirectHandle<FixedArray> v8::internal::ValueDeserializer::id_map_ [private]
Definition at line 341 of file value-serializer.h.
Referenced by AddObjectWithID(), GetObjectWithID(), HasObjectWithID(), and ~ValueDeserializer().
isolate_
Isolate* const v8::internal::ValueDeserializer::isolate_ [private]
Definition at line 331 of file value-serializer.h.
Referenced by AddObjectWithID(), GetObjectWithID(), HasObjectWithID(), ReadBigInt(), ReadDenseJSArray(), ReadHeader(), ReadHostObject(), ReadJSArrayBuffer(), ReadJSArrayBufferView(), ReadJSDate(), ReadJSError(), ReadJSMap(), ReadJSObject(), ReadJSObjectProperties(), ReadJSPrimitiveWrapper(), ReadJSRegExp(), ReadJSSet(), ReadObject(), ReadObjectInternal(), ReadObjectUsingEntireBufferForLegacyFormat(), ReadObjectWrapper(), ReadOneByteString(), ReadSharedObject(), ReadSparseJSArray(), ReadString(), ReadTransferredJSArrayBuffer(), ReadTwoByteString(), ReadUtf8String(), and TransferArrayBuffer().
next_id_
uint32_t v8::internal::ValueDeserializer::next_id_ = 0 [private]
Definition at line 336 of file value-serializer.h.
Referenced by ReadDenseJSArray(), ReadHostObject(), ReadJSArrayBuffer(), ReadJSArrayBufferView(), ReadJSDate(), ReadJSError(), ReadJSMap(), ReadJSObject(), ReadJSPrimitiveWrapper(), ReadJSRegExp(), ReadJSSet(), ReadSparseJSArray(), and ReadTransferredJSArrayBuffer().
position_
const uint8_t* v8::internal::ValueDeserializer::position_ [private]
Definition at line 333 of file value-serializer.h.
Referenced by PeekTag(), ReadByte(), ReadDenseJSArray(), ReadHeader(), ReadJSArrayBuffer(), ReadJSObjectProperties(), ReadObjectInternal(), ReadObjectUsingEntireBufferForLegacyFormat(), ReadObjectWrapper(), ReadRawBytes(), ReadRawTwoBytes(), ReadTag(), ReadVarint(), ReadVarintLoop(), and ~ValueDeserializer().
shared_object_conveyor_
const SharedObjectConveyorHandles* v8::internal::ValueDeserializer::shared_object_conveyor_ = nullptr [private]
Definition at line 345 of file value-serializer.h.
Referenced by ReadSharedObject().
suppress_deserialization_errors_
bool v8::internal::ValueDeserializer::suppress_deserialization_errors_ = false [private]
Definition at line 338 of file value-serializer.h.
Referenced by ReadObject(), and ReadObjectWrapper().
version_
uint32_t v8::internal::ValueDeserializer::version_ = 0 [private]
Definition at line 335 of file value-serializer.h.
Referenced by GetWireFormatVersion(), ReadDenseJSArray(), ReadHeader(), ReadJSArrayBufferView(), ReadObjectInternal(), ReadObjectUsingEntireBufferForLegacyFormat(), ReadObjectWrapper(), ReadSharedObject(), and ReadString().
version_13_broken_data_mode_
bool v8::internal::ValueDeserializer::version_13_broken_data_mode_ = false [private]
Definition at line 337 of file value-serializer.h.
Referenced by ReadJSArrayBufferView(), and ReadObjectWrapper().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/value-serializer.h
/mnt/V8SourceCode/src/objects/value-serializer.cc