v8::internal::GCCallbacks Class Reference
#include <gc-callbacks.h>
Classes
struct CallbackData
Public Types
using CallbackType = void(*)(v8::Isolate *, GCType, GCCallbackFlags, void *)
Public Member Functions
void Add (CallbackType callback, v8::Isolate *isolate, GCType gc_type, void *data)
void Remove (CallbackType callback, void *data)
void Invoke (GCType gc_type, GCCallbackFlags gc_callback_flags) const
bool IsEmpty () const
Private Member Functions
std::vector< CallbackData >::iterator FindCallback (CallbackType callback, void *data)
Private Attributes
std::vector< CallbackData > callbacks_
Detailed Description
Definition at line 20 of file gc-callbacks.h.
Member Typedef Documentation
CallbackType
using v8::internal::GCCallbacks::CallbackType = void (*)(v8::Isolate*, GCType, GCCallbackFlags, void*)
Definition at line 22 of file gc-callbacks.h.
Member Function Documentation
Add()
void v8::internal::GCCallbacks::Add (CallbackType callback, v8::Isolate * isolate, GCType gc_type, void * data) [inline]
Definition at line 24 of file gc-callbacks.h.
                       {
    DCHECK_NOT_NULL(callback);
    DCHECK_EQ(callbacks_.end(), FindCallback(callback, data));
    callbacks_.emplace_back(callback, isolate, gc_type, data);
  }
References callbacks_, DCHECK_EQ, DCHECK_NOT_NULL, and FindCallback().
Referenced by v8::internal::Heap::AddGCEpilogueCallback(), and v8::internal::Heap::AddGCPrologueCallback().
FindCallback()
std::vector<CallbackData>::iterator v8::internal::GCCallbacks::FindCallback (CallbackType callback, void * data) [inline], [private]
Definition at line 65 of file gc-callbacks.h.
                                                               {
    return std::find_if(callbacks_.begin(), callbacks_.end(),
                        [callback, data](CallbackData& callback_data) {
                          return callback_data.callback == callback &&
                                 callback_data.user_data == data;
                        });
  }
References callbacks_.
Referenced by Add(), and Remove().
Invoke()
void v8::internal::GCCallbacks::Invoke (GCType gc_type, GCCallbackFlags gc_callback_flags) const [inline]
Definition at line 38 of file gc-callbacks.h.
                                                                       {
    AllowGarbageCollection scope;
    for (const CallbackData& callback_data : callbacks_) {
      if (gc_type & callback_data.gc_type) {
        callback_data.callback(callback_data.isolate, gc_type,
                               gc_callback_flags, callback_data.user_data);
      }
    }
  }
References callbacks_.
Referenced by v8::internal::Heap::CallGCEpilogueCallbacks(), and v8::internal::Heap::CallGCPrologueCallbacks().
IsEmpty()
bool v8::internal::GCCallbacks::IsEmpty () const [inline]
Definition at line 48 of file gc-callbacks.h.
{ return callbacks_.empty(); }
References callbacks_.
Referenced by v8::internal::Heap::CallGCEpilogueCallbacks(), and v8::internal::Heap::CallGCPrologueCallbacks().
Remove()
void v8::internal::GCCallbacks::Remove (CallbackType callback, void * data) [inline]
Definition at line 31 of file gc-callbacks.h.
                                                 {
    auto it = FindCallback(callback, data);
    DCHECK_NE(callbacks_.end(), it);
    *it = callbacks_.back();
    callbacks_.pop_back();
  }
References callbacks_, DCHECK_NE, and FindCallback().
Referenced by v8::internal::Heap::RemoveGCEpilogueCallback(), and v8::internal::Heap::RemoveGCPrologueCallback().
Member Data Documentation
callbacks_
std::vector<CallbackData> v8::internal::GCCallbacks::callbacks_ [private]
Definition at line 74 of file gc-callbacks.h.
Referenced by Add(), FindCallback(), Invoke(), IsEmpty(), and Remove().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/gc-callbacks.h