v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U > Class Template Reference
#include <bit-field.h>
Static Public Member Functions
static int word_count (int items)
static int index (int base_index, int item)
static T decode (U data, int item)
static U encode (U previous, int item, T value)
static int shift (int item)
Static Public Attributes
static const int kItemsPerWord = kBitsPerWord / kBitsPerItem
static const int kMask = (1 << kBitsPerItem) - 1
Detailed Description
template<class T, int kBitsPerItem, int kBitsPerWord, class U>
class v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >
Definition at line 141 of file bit-field.h.
Member Function Documentation
decode()
template<class T , int kBitsPerItem, int kBitsPerWord, class U >
static T v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::decode (U data, int item) [inline], [static]
Definition at line 158 of file bit-field.h.
                                    {
    return static_cast<T>((data >> shift(item)) & kMask);
  }
References v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::kMask, and v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::shift().
Referenced by v8::internal::FeedbackMetadata::GetKind().
encode()
template<class T , int kBitsPerItem, int kBitsPerWord, class U >
static U v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::encode (U previous, int item, T value) [inline], [static]
Definition at line 163 of file bit-field.h.
                                                 {
    int shift_value = shift(item);
    int set_bits = (static_cast<int>(value) << shift_value);
    return (previous & ~(kMask << shift_value)) | set_bits;
  }
References v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::kMask, v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::shift(), and v8::internal::value.
Referenced by v8::internal::FeedbackMetadata::SetKind().
index()
template<class T , int kBitsPerItem, int kBitsPerWord, class U >
static int v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::index (int base_index, int item) [inline], [static]
Definition at line 153 of file bit-field.h.
                                             {
    return base_index + item / kItemsPerWord;
  }
References v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::kItemsPerWord.
Referenced by v8::internal::FeedbackMetadata::GetKind(), and v8::internal::FeedbackMetadata::SetKind().
shift()
template<class T , int kBitsPerItem, int kBitsPerWord, class U >
static int v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::shift (int item) [inline], [static]
Definition at line 169 of file bit-field.h.
{ return (item % kItemsPerWord) * kBitsPerItem; }
References v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::kItemsPerWord.
Referenced by v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::decode(), and v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::encode().
word_count()
template<class T , int kBitsPerItem, int kBitsPerWord, class U >
static int v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::word_count (int items) [inline], [static]
Definition at line 147 of file bit-field.h.
                                   {
    if (items == 0) return 0;
    return (items - 1) / kItemsPerWord + 1;
  }
References v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::kItemsPerWord.
Referenced by v8::internal::FeedbackMetadata::word_count().
Member Data Documentation
kItemsPerWord
template<class T , int kBitsPerItem, int kBitsPerWord, class U >
const int v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::kItemsPerWord = kBitsPerWord / kBitsPerItem [static]
Definition at line 143 of file bit-field.h.
Referenced by v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::index(), v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::shift(), and v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::word_count().
kMask
template<class T , int kBitsPerItem, int kBitsPerWord, class U >
const int v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::kMask = (1 << kBitsPerItem) - 1 [static]
Definition at line 144 of file bit-field.h.
Referenced by v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::decode(), and v8::base::BitSetComputer< T, kBitsPerItem, kBitsPerWord, U >::encode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/bit-field.h