v8::internal::CppMarkingState Class Reference
#include <cpp-marking-state.h>
Public Member Functions
CppMarkingState (cppgc::internal::MarkingStateBase &main_thread_marking_state)
CppMarkingState (std::unique_ptr< cppgc::internal::MarkingStateBase > concurrent_marking_state)
CppMarkingState (const CppMarkingState &)=delete
CppMarkingState & operator= (const CppMarkingState &)=delete
void Publish ()
void MarkAndPush (void *instance)
bool IsLocalEmpty () const
Private Attributes
std::unique_ptr< cppgc::internal::MarkingStateBase > owned_marking_state_
cppgc::internal::MarkingStateBase & marking_state_
Detailed Description
Definition at line 21 of file cpp-marking-state.h.
Constructor & Destructor Documentation
CppMarkingState() [1/3]
v8::internal::CppMarkingState::CppMarkingState (cppgc::internal::MarkingStateBase & main_thread_marking_state) [inline], [explicit]
Definition at line 23 of file cpp-marking-state.h.
      : owned_marking_state_(nullptr),
        marking_state_(main_thread_marking_state) {}
CppMarkingState() [2/3]
v8::internal::CppMarkingState::CppMarkingState (std::unique_ptr< cppgc::internal::MarkingStateBase > concurrent_marking_state) [inline], [explicit]
Definition at line 28 of file cpp-marking-state.h.
      : owned_marking_state_(std::move(concurrent_marking_state)),
        marking_state_(*owned_marking_state_) {}
CppMarkingState() [3/3]
v8::internal::CppMarkingState::CppMarkingState (const CppMarkingState &) [delete]
Member Function Documentation
IsLocalEmpty()
bool v8::internal::CppMarkingState::IsLocalEmpty () const [inline]
Definition at line 39 of file cpp-marking-state.h.
                            {
    return marking_state_.marking_worklist().IsLocalEmpty();
  }
References marking_state_, and cppgc::internal::MarkingStateBase::marking_worklist().
MarkAndPush()
void v8::internal::CppMarkingState::MarkAndPush (void * instance) [inline]
Definition at line 14 of file cpp-marking-state-inl.h.
                                                {
  marking_state_.MarkAndPush(
      cppgc::internal::HeapObjectHeader::FromObject(instance));
}
References cppgc::internal::HeapObjectHeader::FromObject(), cppgc::internal::MarkingStateBase::MarkAndPush(), and marking_state_.
operator=()
CppMarkingState& v8::internal::CppMarkingState::operator= (const CppMarkingState &) [delete]
Publish()
void v8::internal::CppMarkingState::Publish () [inline]
Definition at line 35 of file cpp-marking-state.h.
{ marking_state_.Publish(); }
References marking_state_, and cppgc::internal::MarkingStateBase::Publish().
Member Data Documentation
marking_state_
cppgc::internal::MarkingStateBase& v8::internal::CppMarkingState::marking_state_ [private]
Definition at line 45 of file cpp-marking-state.h.
Referenced by IsLocalEmpty(), MarkAndPush(), and Publish().
owned_marking_state_
std::unique_ptr<cppgc::internal::MarkingStateBase> v8::internal::CppMarkingState::owned_marking_state_ [private]
Definition at line 44 of file cpp-marking-state.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc-js/cpp-marking-state.h
/mnt/V8SourceCode/src/heap/cppgc-js/cpp-marking-state-inl.h