v8::internal::EvacuateNewSpaceVisitor Class Reference
Public Member Functions
EvacuateNewSpaceVisitor (Heap *heap, EvacuationAllocator *local_allocator, RecordMigratedSlotVisitor *record_visitor, PretenuringHandler::PretenuringFeedbackMap *local_pretenuring_feedback)
bool Visit (Tagged< HeapObject > object, int size) override
intptr_t promoted_size ()
Private Member Functions
bool TryEvacuateWithoutCopy (Tagged< HeapObject > object)
AllocationSpace AllocateTargetObject (Tagged< HeapObject > old_object, int size, Tagged< HeapObject > *target_object)
AllocationResult AllocateInOldSpace (int size_in_bytes, AllocationAlignment alignment)
Private Attributes
intptr_t promoted_size_
PretenuringHandler *const pretenuring_handler_
PretenuringHandler::PretenuringFeedbackMap * local_pretenuring_feedback_
bool is_incremental_marking_
const bool shortcut_strings_
Additional Inherited Members
Detailed Description
Definition at line 1659 of file mark-compact.cc.
Constructor & Destructor Documentation
EvacuateNewSpaceVisitor()
v8::internal::EvacuateNewSpaceVisitor::EvacuateNewSpaceVisitor (Heap * heap, EvacuationAllocator * local_allocator, RecordMigratedSlotVisitor * record_visitor, PretenuringHandler::PretenuringFeedbackMap * local_pretenuring_feedback) [inline], [explicit]
Definition at line 1661 of file mark-compact.cc.
      : EvacuateVisitorBase(heap, local_allocator, record_visitor),
        promoted_size_(0),
        pretenuring_handler_(heap_->pretenuring_handler()),
        local_pretenuring_feedback_(local_pretenuring_feedback),
        is_incremental_marking_(heap->incremental_marking()->IsMarking()),
        shortcut_strings_(!heap_->IsGCWithStack() ||
                          v8_flags.shortcut_strings_with_stack) {
    DCHECK_IMPLIES(is_incremental_marking_,
                   heap->incremental_marking()->IsMajorMarking());
  }
References DCHECK_IMPLIES, and is_incremental_marking_.
Member Function Documentation
AllocateInOldSpace()
AllocationResult v8::internal::EvacuateNewSpaceVisitor::AllocateInOldSpace (int size_in_bytes, AllocationAlignment alignment) [inline], [private]
Definition at line 1734 of file mark-compact.cc.
                                                                            {
    AllocationResult allocation =
        local_allocator_->Allocate(OLD_SPACE, size_in_bytes, alignment);
    if (allocation.IsFailure()) {
      heap_->FatalProcessOutOfMemory(
          "MarkCompactCollector: semi-space copy, fallback in old gen");
    }
    return allocation;
  }
References v8::internal::EvacuationAllocator::Allocate(), v8::internal::Heap::FatalProcessOutOfMemory(), v8::internal::EvacuateVisitorBase::heap_, v8::internal::AllocationResult::IsFailure(), v8::internal::EvacuateVisitorBase::local_allocator_, and v8::internal::OLD_SPACE.
Referenced by AllocateTargetObject().
AllocateTargetObject()
AllocationSpace v8::internal::EvacuateNewSpaceVisitor::AllocateTargetObject (Tagged< HeapObject > old_object, int size, Tagged< HeapObject > * target_object) [inline], [private]
Definition at line 1714 of file mark-compact.cc.
                                         {
    AllocationSpace space_allocated_in = NEW_SPACE;
    AllocationAlignment alignment =
        HeapObject::RequiredAlignment(space_allocated_in, old_object->map());
    AllocationResult allocation =
        local_allocator_->Allocate(NEW_SPACE, size, alignment);
    if (allocation.IsFailure()) {
      space_allocated_in = OLD_SPACE;
      alignment =
          HeapObject::RequiredAlignment(space_allocated_in, old_object->map());
      allocation = AllocateInOldSpace(size, alignment);
    }
    bool ok = allocation.To(target_object);
    DCHECK(ok);
    USE(ok);
    return space_allocated_in;
  }
References v8::internal::EvacuationAllocator::Allocate(), AllocateInOldSpace(), v8::internal::DCHECK(), v8::internal::AllocationResult::IsFailure(), v8::internal::EvacuateVisitorBase::local_allocator_, v8::internal::NEW_SPACE, v8::internal::OLD_SPACE, v8::internal::HeapObject::RequiredAlignment(), size(), v8::internal::AllocationResult::To(), and USE.
promoted_size()
intptr_t v8::internal::EvacuateNewSpaceVisitor::promoted_size () [inline]
Definition at line 1692 of file mark-compact.cc.
{ return promoted_size_; }
References promoted_size_.
TryEvacuateWithoutCopy()
bool v8::internal::EvacuateNewSpaceVisitor::TryEvacuateWithoutCopy (Tagged< HeapObject > object) [inline], [private]
Definition at line 1695 of file mark-compact.cc.
                                                                {
    DCHECK(!is_incremental_marking_);
    if (!shortcut_strings_) return false;
    Tagged<Map> map = object->map();
    // Some objects can be evacuated without creating a copy.
    if (map->visitor_id() == kVisitThinString) {
      Tagged<HeapObject> actual = Cast<ThinString>(object)->unchecked_actual();
      if (MarkCompactCollector::IsOnEvacuationCandidate(actual)) return false;
      object->set_map_word_forwarded(actual, kRelaxedStore);
      return true;
    }
    // TODO(mlippautz): Handle ConsString.
    return false;
  }
References v8::internal::DCHECK(), is_incremental_marking_, v8::internal::MarkCompactCollector::IsOnEvacuationCandidate(), v8::kRelaxedStore, and shortcut_strings_.
Referenced by Visit().
Visit()
bool v8::internal::EvacuateNewSpaceVisitor::Visit (Tagged< HeapObject > object, int size) [inline], [override], [virtual]
Implements v8::internal::HeapObjectVisitor.
Definition at line 1676 of file mark-compact.cc.
                                                                  {
    if (TryEvacuateWithoutCopy(object)) return true;
    Tagged<HeapObject> target_object;
    PretenuringHandler::UpdateAllocationSite(heap_, object->map(), object, size,
                                             local_pretenuring_feedback_);
    if (!TryEvacuateObject(OLD_SPACE, object, size, &target_object)) {
      heap_->FatalProcessOutOfMemory(
          "MarkCompactCollector: young object promotion failed");
    }
    promoted_size_ += size;
    return true;
  }
References v8::internal::Heap::FatalProcessOutOfMemory(), v8::internal::EvacuateVisitorBase::heap_, local_pretenuring_feedback_, v8::internal::OLD_SPACE, promoted_size_, size(), v8::internal::EvacuateVisitorBase::TryEvacuateObject(), TryEvacuateWithoutCopy(), and v8::internal::PretenuringHandler::UpdateAllocationSite().
Member Data Documentation
is_incremental_marking_
bool v8::internal::EvacuateNewSpaceVisitor::is_incremental_marking_ [private]
Definition at line 1748 of file mark-compact.cc.
Referenced by EvacuateNewSpaceVisitor(), and TryEvacuateWithoutCopy().
local_pretenuring_feedback_
PretenuringHandler::PretenuringFeedbackMap* v8::internal::EvacuateNewSpaceVisitor::local_pretenuring_feedback_ [private]
Definition at line 1747 of file mark-compact.cc.
Referenced by Visit().
pretenuring_handler_
PretenuringHandler* const v8::internal::EvacuateNewSpaceVisitor::pretenuring_handler_ [private]
Definition at line 1746 of file mark-compact.cc.
promoted_size_
intptr_t v8::internal::EvacuateNewSpaceVisitor::promoted_size_ [private]
Definition at line 1745 of file mark-compact.cc.
Referenced by promoted_size(), and Visit().
shortcut_strings_
const bool v8::internal::EvacuateNewSpaceVisitor::shortcut_strings_ [private]
Definition at line 1749 of file mark-compact.cc.
Referenced by TryEvacuateWithoutCopy().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc