v8::internal::CppHeapExternalObject::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > object)
Additional Inherited Members
Detailed Description
Definition at line 189 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::CppHeapExternalObject::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 192 of file objects-body-descriptors-inl.h.
                                                                    {
    static_assert(CppHeapExternalObject::kCppHeapWrappableOffsetEnd + 1 ==
                  CppHeapExternalObject::kHeaderSize);
    v->VisitCppHeapPointer(obj,
                           obj->RawCppHeapPointerField(
                               CppHeapExternalObject::kCppHeapWrappableOffset));
    DCHECK_EQ(object_size, kHeaderSize);
  }
References DCHECK_EQ, and v8::internal::ObjectVisitor::VisitCppHeapPointer().
Referenced by v8::internal::ScavengeVisitor::VisitCppHeapExternalObject().
SizeOf()
static int v8::internal::CppHeapExternalObject::BodyDescriptor::SizeOf (Tagged< Map > map, Tagged< HeapObject > object) [inline], [static]
Definition at line 202 of file objects-body-descriptors-inl.h.
                                                                       {
    DCHECK_EQ(map->instance_size(), kHeaderSize);
    return kHeaderSize;
  }
References DCHECK_EQ.
Referenced by v8::internal::ScavengeVisitor::VisitCppHeapExternalObject().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h