v8::internal::Compiler Class Reference
#include <compiler.h>
Public Types
enum ClearExceptionFlag { KEEP_EXCEPTION
, CLEAR_EXCEPTION
 }
Static Public Member Functions
static bool Compile (Isolate *isolate, Handle< SharedFunctionInfo > shared, ClearExceptionFlag flag, IsCompiledScope *is_compiled_scope, CreateSourcePositions create_source_positions_flag=CreateSourcePositions::kNo)
static bool Compile (Isolate *isolate, DirectHandle< JSFunction > function, ClearExceptionFlag flag, IsCompiledScope *is_compiled_scope)
static MaybeHandle< SharedFunctionInfo > CompileToplevel (ParseInfo *parse_info, Handle< Script > script, Isolate *isolate, IsCompiledScope *is_compiled_scope)
static bool CompileSharedWithBaseline (Isolate *isolate, Handle< SharedFunctionInfo > shared, ClearExceptionFlag flag, IsCompiledScope *is_compiled_scope)
static bool CompileBaseline (Isolate *isolate, DirectHandle< JSFunction > function, ClearExceptionFlag flag, IsCompiledScope *is_compiled_scope)
static void CompileOptimized (Isolate *isolate, DirectHandle< JSFunction > function, ConcurrencyMode mode, CodeKind code_kind)
static V8_WARN_UNUSED_RESULT MaybeHandle< Code > CompileOptimizedOSR (Isolate *isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset, ConcurrencyMode mode, CodeKind code_kind)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< SharedFunctionInfo > CompileForLiveEdit (ParseInfo *parse_info, Handle< Script > script, MaybeDirectHandle< ScopeInfo > outer_scope_info, Isolate *isolate)
static bool CollectSourcePositions (Isolate *isolate, DirectHandle< SharedFunctionInfo > shared)
static bool FinalizeBackgroundCompileTask (BackgroundCompileTask *task, Isolate *isolate, ClearExceptionFlag flag)
static void DisposeTurbofanCompilationJob (Isolate *isolate, TurbofanCompilationJob *job)
static void FinalizeTurbofanCompilationJob (TurbofanCompilationJob *job, Isolate *isolate)
static void FinalizeMaglevCompilationJob (maglev::MaglevCompilationJob *job, Isolate *isolate)
static void DisposeMaglevCompilationJob (maglev::MaglevCompilationJob *job, Isolate *isolate)
static void PostInstantiation (Isolate *isolate, DirectHandle< JSFunction > function, IsCompiledScope *is_compiled_scope)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSFunction > GetFunctionFromEval (Isolate *isolate, DirectHandle< String > source, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< Context > context, LanguageMode language_mode, ParseRestriction restriction, int parameters_end_pos, int eval_position, ParsingWhileDebugging parsing_while_debugging=ParsingWhileDebugging::kNo)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSFunction > GetWrappedFunction (Isolate *isolate, Handle< String > source, DirectHandle< Context > context, const ScriptDetails &script_details, AlignedCachedData *cached_data, v8::ScriptCompiler::CompileOptions compile_options, v8::ScriptCompiler::NoCacheReason no_cache_reason)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSFunction > GetFunctionFromString (Isolate *isolate, DirectHandle< NativeContext > context, Handle< i::Object > source, int parameters_end_pos, bool is_code_like)
static V8_WARN_UNUSED_RESULT std::pair< MaybeDirectHandle< String >, bool > ValidateDynamicCompilationSource (Isolate *isolate, DirectHandle< NativeContext > context, Handle< i::Object > source_object, bool is_code_like=false)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSFunction > GetFunctionFromValidatedString (Isolate *isolate, DirectHandle< NativeContext > context, MaybeDirectHandle< String > source, ParseRestriction restriction, int parameters_end_pos)
static MaybeDirectHandle< SharedFunctionInfo > GetSharedFunctionInfoForScript (Isolate *isolate, Handle< String > source, const ScriptDetails &script_details, ScriptCompiler::CompileOptions compile_options, ScriptCompiler::NoCacheReason no_cache_reason, NativesFlag is_natives_code, ScriptCompiler::CompilationDetails *compilation_details)
static MaybeDirectHandle< SharedFunctionInfo > GetSharedFunctionInfoForScriptWithExtension (Isolate *isolate, Handle< String > source, const ScriptDetails &script_details, v8::Extension *extension, ScriptCompiler::CompileOptions compile_options, NativesFlag is_natives_code, ScriptCompiler::CompilationDetails *compilation_details)
static MaybeDirectHandle< SharedFunctionInfo > GetSharedFunctionInfoForScriptWithCachedData (Isolate *isolate, Handle< String > source, const ScriptDetails &script_details, AlignedCachedData *cached_data, ScriptCompiler::CompileOptions compile_options, ScriptCompiler::NoCacheReason no_cache_reason, NativesFlag is_natives_code, ScriptCompiler::CompilationDetails *compilation_details)
static MaybeDirectHandle< SharedFunctionInfo > GetSharedFunctionInfoForScriptWithDeserializeTask (Isolate *isolate, Handle< String > source, const ScriptDetails &script_details, BackgroundDeserializeTask *deserialize_task, ScriptCompiler::CompileOptions compile_options, ScriptCompiler::NoCacheReason no_cache_reason, NativesFlag is_natives_code, ScriptCompiler::CompilationDetails *compilation_details)
static MaybeDirectHandle< SharedFunctionInfo > GetSharedFunctionInfoForScriptWithCompileHints (Isolate *isolate, Handle< String > source, const ScriptDetails &script_details, v8::CompileHintCallback compile_hint_callback, void *compile_hint_callback_data, ScriptCompiler::CompileOptions compile_options, ScriptCompiler::NoCacheReason no_cache_reason, NativesFlag is_natives_code, ScriptCompiler::CompilationDetails *compilation_details)
static MaybeDirectHandle< SharedFunctionInfo > GetSharedFunctionInfoForStreamedScript (Isolate *isolate, Handle< String > source, const ScriptDetails &script_details, ScriptStreamingData *streaming_data, IsCompiledScope *is_compiled_scope, ScriptCompiler::CompilationDetails *compilation_details)
template<typename IsolateT >
static DirectHandle< SharedFunctionInfo > GetSharedFunctionInfo (FunctionLiteral *node, DirectHandle< Script > script, IsolateT *isolate)
static void LogFunctionCompilation (Isolate *isolate, LogEventListener::CodeTag code_type, DirectHandle< Script > script, DirectHandle< SharedFunctionInfo > shared, DirectHandle< FeedbackVector > vector, DirectHandle< AbstractCode > abstract_code, CodeKind kind, double time_taken_ms)
static void InstallInterpreterTrampolineCopy (Isolate *isolate, DirectHandle< SharedFunctionInfo > shared_info, LogEventListener::CodeTag log_tag)
Detailed Description
Definition at line 75 of file compiler.h.
Member Enumeration Documentation
ClearExceptionFlag
enum v8::internal::Compiler::ClearExceptionFlag
Enumerator
KEEP_EXCEPTION
CLEAR_EXCEPTION
Definition at line 77 of file compiler.h.
{ KEEP_EXCEPTION, CLEAR_EXCEPTION };
Member Function Documentation
CollectSourcePositions()
bool v8::internal::Compiler::CollectSourcePositions (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared) [static]
Definition at line 2814 of file compiler.cc.
                                                                    {
  DCHECK(shared_info->is_compiled());
  DCHECK(shared_info->HasBytecodeArray());
  DCHECK(!shared_info->GetBytecodeArray(isolate)->HasSourcePositionTable());
  // Source position collection should be context independent.
  NullContextScope null_context_scope(isolate);
  // Collecting source positions requires allocating a new source position
  // table.
  DCHECK(AllowHeapAllocation::IsAllowed());
  Handle<BytecodeArray> bytecode =
      handle(shared_info->GetBytecodeArray(isolate), isolate);
  // TODO(v8:8510): Push the CLEAR_EXCEPTION flag or something like it down into
  // the parser so it aborts without setting an exception, which then
  // gets thrown. This would avoid the situation where potentially we'd reparse
  // several times (running out of stack each time) before hitting this limit.
  if (GetCurrentStackPosition() < isolate->stack_guard()->real_climit()) {
    // Stack is already exhausted.
    bytecode->SetSourcePositionsFailedToCollect();
    return false;
  }
  // Unfinalized scripts don't yet have the proper source string attached and
  // thus can't be reparsed.
  if (Cast<Script>(shared_info->script())->IsMaybeUnfinalized(isolate)) {
    bytecode->SetSourcePositionsFailedToCollect();
    return false;
  }
  DCHECK(AllowCompilation::IsAllowed(isolate));
  DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
  DCHECK(!isolate->has_exception());
  VMState<BYTECODE_COMPILER> state(isolate);
  PostponeInterruptsScope postpone(isolate);
  RCS_SCOPE(isolate, RuntimeCallCounterId::kCompileCollectSourcePositions);
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "V8.CollectSourcePositions");
  NestedTimedHistogramScope timer(
      isolate->counters()->collect_source_positions());
  // Set up parse info.
  UnoptimizedCompileFlags flags =
      UnoptimizedCompileFlags::ForFunctionCompile(isolate, *shared_info);
  flags.set_collect_source_positions(true);
  flags.set_is_reparse(true);
  // Prevent parallel tasks from being spawned by this job.
  flags.set_post_parallel_compile_tasks_for_eager_toplevel(false);
  flags.set_post_parallel_compile_tasks_for_lazy(false);
  UnoptimizedCompileState compile_state;
  ReusableUnoptimizedCompileState reusable_state(isolate);
  ParseInfo parse_info(isolate, flags, &compile_state, &reusable_state);
  // Parse and update ParseInfo with the results. Don't update parsing
  // statistics since we've already parsed the code before.
  if (!parsing::ParseAny(&parse_info, shared_info, isolate,
                         parsing::ReportStatisticsMode::kNo)) {
    // Parsing failed probably as a result of stack exhaustion.
    bytecode->SetSourcePositionsFailedToCollect();
    return FailAndClearException(isolate);
  }
  // Character stream shouldn't be used again.
  parse_info.ResetCharacterStream();
  // Generate the unoptimized bytecode.
  // TODO(v8:8510): Consider forcing preparsing of inner functions to avoid
  // wasting time fully parsing them when they won't ever be used.
  std::unique_ptr<UnoptimizedCompilationJob> job;
  {
    job = interpreter::Interpreter::NewSourcePositionCollectionJob(
        &parse_info, parse_info.literal(), bytecode, isolate->allocator(),
        isolate->main_thread_local_isolate());
    if (!job || job->ExecuteJob() != CompilationJob::SUCCEEDED ||
        job->FinalizeJob(shared_info, isolate) != CompilationJob::SUCCEEDED) {
      // Recompiling failed probably as a result of stack exhaustion.
      bytecode->SetSourcePositionsFailedToCollect();
      return FailAndClearException(isolate);
    }
  }
  DCHECK(job->compilation_info()->flags().collect_source_positions());
  // If debugging, make sure that instrumented bytecode has the source position
  // table set on it as well.
  if (std::optional<Tagged<DebugInfo>> debug_info =
          shared_info->TryGetDebugInfo(isolate)) {
    if (debug_info.value()->HasInstrumentedBytecodeArray()) {
      Tagged<TrustedByteArray> source_position_table =
          job->compilation_info()->bytecode_array()->SourcePositionTable();
      shared_info->GetActiveBytecodeArray(isolate)->set_source_position_table(
          source_position_table, kReleaseStore);
    }
  }
  DCHECK(!isolate->has_exception());
  DCHECK(shared_info->is_compiled_scope(isolate).is_compiled());
  return true;
}
References v8::internal::Isolate::allocator(), v8::internal::Isolate::counters(), v8::internal::ThreadId::Current(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::anonymous_namespace{compiler.cc}::FailAndClearException(), v8::internal::flags, v8::internal::UnoptimizedCompileFlags::ForFunctionCompile(), v8::internal::GetCurrentStackPosition(), v8::internal::handle(), v8::internal::Isolate::has_exception(), v8::internal::parsing::kNo, v8::kReleaseStore, v8::internal::ParseInfo::literal(), v8::internal::Isolate::main_thread_local_isolate(), v8::internal::interpreter::Interpreter::NewSourcePositionCollectionJob(), v8::internal::parsing::ParseAny(), RCS_SCOPE, v8::internal::StackGuard::real_climit(), v8::internal::ParseInfo::ResetCharacterStream(), v8::internal::Isolate::stack_guard(), v8::internal::CompilationJob::SUCCEEDED, v8::internal::Isolate::thread_id(), TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Referenced by v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable().
Compile() [1/2]
bool v8::internal::Compiler::Compile (Isolate * isolate, DirectHandle< JSFunction > function, ClearExceptionFlag flag, IsCompiledScope * is_compiled_scope) [static]
Definition at line 3016 of file compiler.cc.
                                                           {
  // We should never reach here if the function is already compiled or
  // optimized.
  DCHECK(!function->is_compiled(isolate));
  DCHECK_IMPLIES(function->has_feedback_vector() &&
                     function->IsTieringRequestedOrInProgress(),
                 function->shared()->is_compiled());
  DCHECK_IMPLIES(function->HasAvailableOptimizedCode(isolate),
                 function->shared()->is_compiled());
  // Reset the JSFunction if we are recompiling due to the bytecode having been
  // flushed.
  function->ResetIfCodeFlushed(isolate);
  Handle<SharedFunctionInfo> shared_info(function->shared(), isolate);
  // Ensure shared function info is compiled.
  *is_compiled_scope = shared_info->is_compiled_scope(isolate);
  if (!is_compiled_scope->is_compiled() &&
      !Compile(isolate, shared_info, flag, is_compiled_scope)) {
    return false;
  }
  DCHECK(is_compiled_scope->is_compiled());
  DirectHandle<Code> code(shared_info->GetCode(isolate), isolate);
  // Initialize the feedback cell for this JSFunction and reset the interrupt
  // budget for feedback vector allocation even if there is a closure feedback
  // cell array. We are re-compiling when we have a closure feedback cell array
  // which means we are compiling after a bytecode flush.
  // TODO(verwaest/mythria): Investigate if allocating feedback vector
  // immediately after a flush would be better.
  JSFunction::InitializeFeedbackCell(isolate, function, is_compiled_scope,
                                     true);
  function->ResetTieringRequests();
  function->UpdateCode(isolate, *code);
  // Optimize now if --always-turbofan is enabled.
#if V8_ENABLE_WEBASSEMBLY
  if (v8_flags.always_turbofan && !function->shared()->HasAsmWasmData()) {
#else
  if (v8_flags.always_turbofan) {
#endif // V8_ENABLE_WEBASSEMBLY
    DCHECK(!function->tiering_in_progress());
    CompilerTracer::TraceOptimizeForAlwaysOpt(isolate, function,
                                              CodeKindForTopTier());
    const CodeKind code_kind = CodeKindForTopTier();
    const ConcurrencyMode concurrency_mode = ConcurrencyMode::kSynchronous;
    if (v8_flags.stress_concurrent_inlining &&
        isolate->concurrent_recompilation_enabled() &&
        isolate->node_observer() == nullptr) {
      SpawnDuplicateConcurrentJobForStressTesting(isolate, function,
                                                  concurrency_mode, code_kind);
    }
    DirectHandle<Code> maybe_code;
    if (GetOrCompileOptimized(isolate, function, concurrency_mode, code_kind)
            .ToHandle(&maybe_code)) {
      code = maybe_code;
      function->UpdateOptimizedCode(isolate, *code);
    }
  }
  // Install a feedback vector if necessary.
  if (code->kind() == CodeKind::BASELINE) {
    JSFunction::EnsureFeedbackVector(isolate, function, is_compiled_scope);
  }
  // Check postconditions on success.
  DCHECK(!isolate->has_exception());
  DCHECK(function->shared()->is_compiled());
  DCHECK(function->is_compiled(isolate));
  return true;
}
References code, v8::internal::CodeKindForTopTier(), Compile(), v8::internal::Isolate::concurrent_recompilation_enabled(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::JSFunction::EnsureFeedbackVector(), v8::internal::anonymous_namespace{compiler.cc}::GetOrCompileOptimized(), v8::internal::Isolate::has_exception(), v8::internal::JSFunction::InitializeFeedbackCell(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::kSynchronous, v8::internal::anonymous_namespace{compiler.cc}::SpawnDuplicateConcurrentJobForStressTesting(), v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::v8_flags.
Compile() [2/2]
bool v8::internal::Compiler::Compile (Isolate * isolate, Handle< SharedFunctionInfo > shared, ClearExceptionFlag flag, IsCompiledScope * is_compiled_scope, CreateSourcePositions create_source_positions_flag = CreateSourcePositions::kNo) [static]
Definition at line 2921 of file compiler.cc.
                                                                           {
  // We should never reach here if the function is already compiled.
  DCHECK(!shared_info->is_compiled());
  DCHECK(!is_compiled_scope->is_compiled());
  DCHECK(AllowCompilation::IsAllowed(isolate));
  DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
  DCHECK(!isolate->has_exception());
  DCHECK(!shared_info->HasBytecodeArray());
  VMState<BYTECODE_COMPILER> state(isolate);
  PostponeInterruptsScope postpone(isolate);
  TimerEventScope<TimerEventCompileCode> compile_timer(isolate);
  RCS_SCOPE(isolate, RuntimeCallCounterId::kCompileFunction);
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"), "V8.CompileCode");
  AggregatedHistogramTimerScope timer(isolate->counters()->compile_lazy());
  Handle<Script> script(Cast<Script>(shared_info->script()), isolate);
  // Set up parse info.
  UnoptimizedCompileFlags flags =
      UnoptimizedCompileFlags::ForFunctionCompile(isolate, *shared_info);
  if (create_source_positions_flag == CreateSourcePositions::kYes) {
    flags.set_collect_source_positions(true);
  }
  UnoptimizedCompileState compile_state;
  ReusableUnoptimizedCompileState reusable_state(isolate);
  ParseInfo parse_info(isolate, flags, &compile_state, &reusable_state);
  // Check if the compiler dispatcher has shared_info enqueued for compile.
  LazyCompileDispatcher* dispatcher = isolate->lazy_compile_dispatcher();
  if (dispatcher && dispatcher->IsEnqueued(shared_info)) {
    if (!dispatcher->FinishNow(shared_info)) {
      return FailWithException(isolate, script, &parse_info, flag);
    }
    *is_compiled_scope = shared_info->is_compiled_scope(isolate);
    DCHECK(is_compiled_scope->is_compiled());
    return true;
  }
  if (shared_info->HasUncompiledDataWithPreparseData(isolate)) {
    parse_info.set_consumed_preparse_data(ConsumedPreparseData::For(
        isolate, handle(shared_info->uncompiled_data_with_preparse_data(isolate)
                            ->preparse_data(),
                        isolate)));
  }
  // Parse and update ParseInfo with the results.
  if (!parsing::ParseAny(&parse_info, shared_info, isolate,
                         parsing::ReportStatisticsMode::kYes)) {
    return FailWithException(isolate, script, &parse_info, flag);
  }
  parse_info.literal()->set_shared_function_info(shared_info);
  // Generate the unoptimized bytecode or asm-js data.
  FinalizeUnoptimizedCompilationDataList
      finalize_unoptimized_compilation_data_list;
  if (!IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs(
          isolate, script, &parse_info, isolate->allocator(), is_compiled_scope,
          &finalize_unoptimized_compilation_data_list, nullptr)) {
    return FailWithException(isolate, script, &parse_info, flag);
  }
  FinalizeUnoptimizedCompilation(isolate, script, flags, &compile_state,
                                 finalize_unoptimized_compilation_data_list);
  if (v8_flags.always_sparkplug) {
    CompileAllWithBaseline(isolate, finalize_unoptimized_compilation_data_list);
  }
  if (script->produce_compile_hints()) {
    // Log lazy function compilation.
    DirectHandle<ArrayList> list;
    if (IsUndefined(script->compiled_lazy_function_positions())) {
      constexpr int kInitialLazyFunctionPositionListSize = 100;
      list = ArrayList::New(isolate, kInitialLazyFunctionPositionListSize);
    } else {
      list = direct_handle(
          Cast<ArrayList>(script->compiled_lazy_function_positions()), isolate);
    }
    list = ArrayList::Add(isolate, list,
                          Smi::FromInt(shared_info->StartPosition()));
    script->set_compiled_lazy_function_positions(*list);
  }
  DCHECK(!isolate->has_exception());
  DCHECK(is_compiled_scope->is_compiled());
  return true;
}
References v8::internal::ArrayList::Add(), v8::internal::Isolate::allocator(), v8::internal::anonymous_namespace{compiler.cc}::CompileAllWithBaseline(), v8::internal::Isolate::counters(), v8::internal::ThreadId::Current(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::anonymous_namespace{compiler.cc}::FailWithException(), v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedCompilation(), v8::internal::LazyCompileDispatcher::FinishNow(), v8::internal::flags, v8::internal::ConsumedPreparseData::For(), v8::internal::UnoptimizedCompileFlags::ForFunctionCompile(), v8::internal::Smi::FromInt(), v8::internal::handle(), v8::internal::Isolate::has_exception(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::LazyCompileDispatcher::IsEnqueued(), v8::internal::anonymous_namespace{compiler.cc}::IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs(), v8::internal::kYes, v8::internal::parsing::kYes, v8::internal::Isolate::lazy_compile_dispatcher(), v8::internal::ParseInfo::literal(), v8::internal::ArrayList::New(), v8::internal::parsing::ParseAny(), RCS_SCOPE, v8::internal::script, v8::internal::ParseInfo::set_consumed_preparse_data(), v8::internal::FunctionLiteral::set_shared_function_info(), v8::internal::Isolate::thread_id(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and v8::internal::v8_flags.
Referenced by v8::internal::JSFunction::CalculateExpectedNofProperties(), v8::internal::anonymous_namespace{runtime-test.cc}::CanOptimizeFunction(), Compile(), v8::internal::Debug::EnsureBreakInfo(), v8::internal::SharedFunctionInfo::EnsureBytecodeArrayAvailable(), v8::internal::anonymous_namespace{runtime-test.cc}::EnsureCompiledAndFeedbackVector(), v8::Function::Experimental_IsNopFunction(), v8::internal::Debug::FindInnermostContainingFunctionInfo(), v8::internal::Debug::FindSharedFunctionInfosIntersectingRange(), v8::internal::Debug::InstallDebugBreakTrampoline(), v8::internal::Debug::PerformSideEffectCheck(), and v8::internal::RUNTIME_FUNCTION().
CompileBaseline()
bool v8::internal::Compiler::CompileBaseline (Isolate * isolate, DirectHandle< JSFunction > function, ClearExceptionFlag flag, IsCompiledScope * is_compiled_scope) [static]
Definition at line 3148 of file compiler.cc.
                                                                   {
  Handle<SharedFunctionInfo> shared(function->shared(isolate), isolate);
  if (!CompileSharedWithBaseline(isolate, shared, flag, is_compiled_scope)) {
    return false;
  }
  // Baseline code needs a feedback vector.
  JSFunction::EnsureFeedbackVector(isolate, function, is_compiled_scope);
  Tagged<Code> baseline_code = shared->baseline_code(kAcquireLoad);
  DCHECK_EQ(baseline_code->kind(), CodeKind::BASELINE);
  function->UpdateCodeKeepTieringRequests(isolate, baseline_code);
  return true;
}
References CompileSharedWithBaseline(), DCHECK_EQ, v8::internal::JSFunction::EnsureFeedbackVector(), and v8::kAcquireLoad.
Referenced by v8::internal::baseline::BaselineBatchCompiler::CompileBatch(), v8::internal::baseline::BaselineBatchCompiler::EnqueueFunction(), v8::internal::JSFunction::InitializeFeedbackCell(), v8::internal::TieringManager::OnInterruptTick(), and v8::internal::RUNTIME_FUNCTION().
CompileForLiveEdit()
MaybeDirectHandle< SharedFunctionInfo > v8::internal::Compiler::CompileForLiveEdit (ParseInfo * parse_info, Handle< Script > script, MaybeDirectHandle< ScopeInfo > outer_scope_info, Isolate * isolate) [static]
Definition at line 3257 of file compiler.cc.
                                                                     {
  IsCompiledScope is_compiled_scope;
  return v8::internal::CompileToplevel(parse_info, script, outer_scope_info,
                                       isolate, &is_compiled_scope);
}
References v8::internal::anonymous_namespace{compiler.cc}::CompileToplevel(), and v8::internal::script.
Referenced by v8::internal::anonymous_namespace{liveedit.cc}::ParseScript().
CompileOptimized()
void v8::internal::Compiler::CompileOptimized (Isolate * isolate, DirectHandle< JSFunction > function, ConcurrencyMode mode, CodeKind code_kind) [static]
Definition at line 3192 of file compiler.cc.
                                                                          {
  function->TraceOptimizationStatus("^%s", CodeKindToString(code_kind));
  DCHECK(CodeKindIsOptimizedJSFunction(code_kind));
  DCHECK(AllowCompilation::IsAllowed(isolate));
  if (v8_flags.stress_concurrent_inlining &&
      isolate->concurrent_recompilation_enabled() && IsSynchronous(mode) &&
      isolate->node_observer() == nullptr) {
    SpawnDuplicateConcurrentJobForStressTesting(isolate, function, mode,
                                                code_kind);
  }
#ifdef DEBUG
  if (V8_ENABLE_LEAPTIERING_BOOL && mode == ConcurrencyMode::kConcurrent) {
    DCHECK_IMPLIES(code_kind == CodeKind::MAGLEV,
                   !function->ActiveTierIsMaglev(isolate));
    DCHECK_IMPLIES(code_kind == CodeKind::TURBOFAN_JS,
                   !function->ActiveTierIsTurbofan(isolate));
  }
  bool tiering_was_in_progress = function->tiering_in_progress();
  DCHECK_IMPLIES(tiering_was_in_progress, mode != ConcurrencyMode::kConcurrent);
#endif // DEBUG
  DirectHandle<Code> code;
  if (GetOrCompileOptimized(isolate, function, mode, code_kind)
          .ToHandle(&code)) {
    function->UpdateOptimizedCode(isolate, *code);
    DCHECK_IMPLIES(v8_flags.log_function_events,
                   function->IsLoggingRequested(isolate));
  } else {
#ifdef V8_ENABLE_LEAPTIERING
    // We can get here from CompileLazy when we have requested optimized code
    // which isn't yet ready. Without Leaptiering, we'll already have set the
    // function's code to the bytecode/baseline code on the SFI. However, in the
    // leaptiering case, we potentially need to do this now.
    if (!function->is_compiled(isolate)) {
      function->UpdateCodeKeepTieringRequests(
          isolate, function->shared()->GetCode(isolate));
    }
#endif // V8_ENABLE_LEAPTIERING
  }
#ifdef DEBUG
  DCHECK(!isolate->has_exception());
  DCHECK(function->is_compiled(isolate));
  DCHECK(function->shared()->HasBytecodeArray());
  DCHECK_IMPLIES(function->IsTieringRequestedOrInProgress() &&
                     !function->IsLoggingRequested(isolate),
                 function->tiering_in_progress());
  if (!v8_flags.always_turbofan) {
    // Before a maglev optimization job is started we might have to compile
    // bytecode. This can trigger a turbofan compilation if always_turbofan is
    // set. Therefore we need to skip this dcheck in that case.
    DCHECK_IMPLIES(!tiering_was_in_progress && function->tiering_in_progress(),
                   function->ChecksTieringState(isolate));
  }
  DCHECK_IMPLIES(!tiering_was_in_progress && function->tiering_in_progress(),
                 IsConcurrent(mode));
#endif // DEBUG
}
References code, v8::internal::CodeKindIsOptimizedJSFunction(), v8::internal::CodeKindToString(), v8::internal::Isolate::concurrent_recompilation_enabled(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::anonymous_namespace{compiler.cc}::GetOrCompileOptimized(), v8::internal::Isolate::has_exception(), v8::internal::IsConcurrent(), v8::internal::IsSynchronous(), v8::internal::kConcurrent, mode(), v8::internal::anonymous_namespace{compiler.cc}::SpawnDuplicateConcurrentJobForStressTesting(), v8::anonymous_namespace{api.cc}::ToHandle(), V8_ENABLE_LEAPTIERING_BOOL, and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION().
CompileOptimizedOSR()
MaybeHandle< Code > v8::internal::Compiler::CompileOptimizedOSR (Isolate * isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset, ConcurrencyMode mode, CodeKind code_kind) [static]
Definition at line 4386 of file compiler.cc.
                                                                         {
  DCHECK(IsOSR(osr_offset));
  if (V8_UNLIKELY(isolate->serializer_enabled())) return {};
  if (V8_UNLIKELY(function->shared()->optimization_disabled(code_kind)))
    return {};
  // TODO(chromium:1031479): Currently, OSR triggering mechanism is tied to the
  // bytecode array. So, it might be possible to mark closure in one native
  // context and optimize a closure from a different native context. So check if
  // there is a feedback vector before OSRing. We don't expect this to happen
  // often.
  if (V8_UNLIKELY(!function->has_feedback_vector())) return {};
  CompilerTracer::TraceOptimizeOSRStarted(isolate, function, osr_offset, mode);
  MaybeHandle<Code> result =
      GetOrCompileOptimized(isolate, function, mode, code_kind, osr_offset);
  if (result.is_null()) {
    CompilerTracer::TraceOptimizeOSRUnavailable(isolate, function, osr_offset,
                                                mode);
  } else {
    DCHECK_GE(result.ToHandleChecked()->kind(), CodeKind::MAGLEV);
    CompilerTracer::TraceOptimizeOSRAvailable(isolate, function, osr_offset,
                                              mode);
  }
  return result;
}
References v8::internal::DCHECK(), DCHECK_GE, v8::internal::anonymous_namespace{compiler.cc}::GetOrCompileOptimized(), v8::internal::anonymous_namespace{compiler.cc}::IsOSR(), mode(), v8::base::internal::result, v8::internal::Isolate::serializer_enabled(), and V8_UNLIKELY.
Referenced by v8::internal::RUNTIME_FUNCTION().
CompileSharedWithBaseline()
bool v8::internal::Compiler::CompileSharedWithBaseline (Isolate * isolate, Handle< SharedFunctionInfo > shared, Compiler::ClearExceptionFlag flag, IsCompiledScope * is_compiled_scope) [static]
Definition at line 3097 of file compiler.cc.
                                                                             {
  // We shouldn't be passing uncompiled functions into this function.
  DCHECK(is_compiled_scope->is_compiled());
  // Early return for already baseline-compiled functions.
  if (shared->HasBaselineCode()) return true;
  // Check if we actually can compile with baseline.
  if (!CanCompileWithBaseline(isolate, *shared)) return false;
  StackLimitCheck check(isolate);
  if (check.JsHasOverflowed(kStackSpaceRequiredForCompilation * KB)) {
    if (flag == Compiler::KEEP_EXCEPTION) {
      isolate->StackOverflow();
    }
    return false;
  }
  CompilerTracer::TraceStartBaselineCompile(isolate, shared);
  DirectHandle<Code> code;
  base::TimeDelta time_taken;
  {
    base::ScopedTimer timer(
        v8_flags.trace_baseline || v8_flags.log_function_events ? &time_taken
                                                                : nullptr);
    if (!GenerateBaselineCode(isolate, shared).ToHandle(&code)) {
      // TODO(leszeks): This can only fail because of an OOM. Do we want to
      // report these somehow, or silently ignore them?
      return false;
    }
    shared->set_baseline_code(*code, kReleaseStore);
    shared->set_age(0);
  }
  double time_taken_ms = time_taken.InMillisecondsF();
  CompilerTracer::TraceFinishBaselineCompile(isolate, shared, time_taken_ms);
  if (IsScript(shared->script())) {
    LogFunctionCompilation(
        isolate, LogEventListener::CodeTag::kFunction,
        direct_handle(Cast<Script>(shared->script()), isolate), shared,
        DirectHandle<FeedbackVector>(), Cast<AbstractCode>(code),
        CodeKind::BASELINE, time_taken_ms);
  }
  return true;
}
References v8::internal::CanCompileWithBaseline(), code, v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::GenerateBaselineCode(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::StackLimitCheck::JsHasOverflowed(), v8::internal::KB, KEEP_EXCEPTION, v8::internal::torque::ls::kFunction, v8::kReleaseStore, v8::internal::kStackSpaceRequiredForCompilation, LogFunctionCompilation(), v8::internal::Isolate::StackOverflow(), v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileAllWithBaseline(), CompileBaseline(), and v8::internal::baseline::BaselineBatchCompiler::MaybeCompileFunction().
CompileToplevel()
MaybeHandle< SharedFunctionInfo > v8::internal::Compiler::CompileToplevel (ParseInfo * parse_info, Handle< Script > script, Isolate * isolate, IsCompiledScope * is_compiled_scope) [static]
Definition at line 3167 of file compiler.cc.
                                        {
  return v8::internal::CompileToplevel(parse_info, script, kNullMaybeHandle,
                                       isolate, is_compiled_scope);
}
References v8::internal::anonymous_namespace{compiler.cc}::CompileToplevel(), v8::internal::kNullMaybeHandle, and v8::internal::script.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnMainThread(), and v8::internal::anonymous_namespace{debug.cc}::CompileTopLevel().
DisposeMaglevCompilationJob()
void v8::internal::Compiler::DisposeMaglevCompilationJob (maglev::MaglevCompilationJob * job, Isolate * isolate) [static]
Definition at line 4496 of file compiler.cc.
                                                             {
#ifdef V8_ENABLE_MAGLEV
  DirectHandle<JSFunction> function = job->function();
  function->SetTieringInProgress(isolate, false, job->osr_offset());
#endif // V8_ENABLE_MAGLEV
}
DisposeTurbofanCompilationJob()
void v8::internal::Compiler::DisposeTurbofanCompilationJob (Isolate * isolate, TurbofanCompilationJob * job) [static]
Definition at line 4419 of file compiler.cc.
                                                                          {
  TRACE_EVENT_WITH_FLOW0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                         "V8.OptimizeConcurrentDispose", job->trace_id(),
                         TRACE_EVENT_FLAG_FLOW_IN);
  DirectHandle<JSFunction> function = job->compilation_info()->closure();
  function->SetTieringInProgress(isolate, false,
                                 job->compilation_info()->osr_offset());
}
References v8::internal::OptimizedCompilationInfo::closure(), v8::internal::TurbofanCompilationJob::compilation_info(), v8::internal::OptimizedCompilationInfo::osr_offset(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_WITH_FLOW0, and v8::internal::TurbofanCompilationJob::trace_id().
Referenced by v8::internal::OptimizingCompileInputQueue::FlushJobsForIsolate(), v8::internal::OptimizingCompileDispatcher::FlushOutputQueue(), and v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions().
FinalizeBackgroundCompileTask()
bool v8::internal::Compiler::FinalizeBackgroundCompileTask (BackgroundCompileTask * task, Isolate * isolate, ClearExceptionFlag flag) [static]
Definition at line 3175 of file compiler.cc.
                                                                      {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "V8.FinalizeBackgroundCompileTask");
  RCS_SCOPE(isolate,
            RuntimeCallCounterId::kCompileFinalizeBackgroundCompileTask);
  HandleScope scope(isolate);
  if (!task->FinalizeFunction(isolate, flag)) return false;
  DCHECK(!isolate->has_exception());
  return true;
}
References v8::internal::DCHECK(), v8::internal::BackgroundCompileTask::FinalizeFunction(), v8::internal::Isolate::has_exception(), RCS_SCOPE, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Referenced by v8::internal::LazyCompileDispatcher::FinalizeSingleJob(), and v8::internal::LazyCompileDispatcher::FinishNow().
FinalizeMaglevCompilationJob()
void v8::internal::Compiler::FinalizeMaglevCompilationJob (maglev::MaglevCompilationJob * job, Isolate * isolate) [static]
Definition at line 4505 of file compiler.cc.
                                                              {
#ifdef V8_ENABLE_MAGLEV
  VMState<COMPILER> state(isolate);
  DirectHandle<JSFunction> function = job->function();
  BytecodeOffset osr_offset = job->osr_offset();
  if (function->ActiveTierIsTurbofan(isolate) && !job->is_osr()) {
    function->SetTieringInProgress(isolate, false, osr_offset);
    CompilerTracer::TraceAbortedMaglevCompile(isolate, function,
                                              BailoutReason::kCancelled);
    return;
  }
  // Discard code compiled for a discarded native context without finalization.
  if (function->native_context()->global_object()->IsDetached(isolate)) {
    CompilerTracer::TraceAbortedMaglevCompile(
        isolate, function, BailoutReason::kDetachedNativeContext);
    return;
  }
  const CompilationJob::Status status = job->FinalizeJob(isolate);
  // TODO(v8:7700): Use the result and check if job succeed
  // when all the bytecodes are implemented.
  USE(status);
  if (status == CompilationJob::SUCCEEDED) {
    DirectHandle<SharedFunctionInfo> shared(function->shared(), isolate);
    DCHECK(!shared->HasBreakInfo(isolate));
    // Note the finalized InstructionStream object has already been installed on
    // the function by MaglevCompilationJob::FinalizeJobImpl.
    DirectHandle<Code> code = job->code().ToHandleChecked();
    if (!job->is_osr()) {
      job->function()->UpdateOptimizedCode(isolate, *code);
    }
    DCHECK(code->is_maglevved());
    if (!V8_ENABLE_LEAPTIERING_BOOL || IsOSR(osr_offset)) {
      OptimizedCodeCache::Insert(isolate, *function, osr_offset, *code,
                                 job->specialize_to_function_context());
    }
    RecordMaglevFunctionCompilation(isolate, function,
                                    Cast<AbstractCode>(code));
    job->RecordCompilationStats(isolate);
    if (v8_flags.profile_guided_optimization &&
        shared->cached_tiering_decision() <=
            CachedTieringDecision::kEarlySparkplug) {
      shared->set_cached_tiering_decision(CachedTieringDecision::kEarlyMaglev);
    }
    CompilerTracer::TraceFinishMaglevCompile(
        isolate, function, job->is_osr(), job->prepare_in_ms(),
        job->execute_in_ms(), job->finalize_in_ms());
  } else {
    CompilerTracer::TraceAbortedMaglevCompile(isolate, function,
                                              job->bailout_reason_);
  }
  function->SetTieringInProgress(isolate, false, osr_offset);
#endif
}
References code, v8::internal::DCHECK(), v8::internal::anonymous_namespace{compiler.cc}::IsOSR(), v8::internal::kEarlyMaglev, v8::internal::kEarlySparkplug, v8::internal::status, v8::internal::CompilationJob::SUCCEEDED, USE, V8_ENABLE_LEAPTIERING_BOOL, and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileMaglev().
FinalizeTurbofanCompilationJob()
void v8::internal::Compiler::FinalizeTurbofanCompilationJob (TurbofanCompilationJob * job, Isolate * isolate) [static]
Definition at line 4430 of file compiler.cc.
                                                                {
  VMState<COMPILER> state(isolate);
  OptimizedCompilationInfo* compilation_info = job->compilation_info();
  TimerEventScope<TimerEventRecompileSynchronous> timer(isolate);
  RCS_SCOPE(isolate, RuntimeCallCounterId::kOptimizeConcurrentFinalize);
  TRACE_EVENT_WITH_FLOW0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                         "V8.OptimizeConcurrentFinalize", job->trace_id(),
                         TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
  DirectHandle<JSFunction> function = compilation_info->closure();
  DirectHandle<SharedFunctionInfo> shared = compilation_info->shared_info();
  const bool use_result = !compilation_info->discard_result_for_testing();
  const BytecodeOffset osr_offset = compilation_info->osr_offset();
  DCHECK(!shared->HasBreakInfo(isolate));
  // 1) Optimization on the concurrent thread may have failed.
  // 2) The function may have already been optimized by OSR. Simply continue.
  // Except when OSR already disabled optimization for some reason.
  // 3) The code may have already been invalidated due to dependency change.
  // 4) InstructionStream generation may have failed.
  if (job->state() == CompilationJob::State::kReadyToFinalize) {
    if (shared->optimization_disabled(CodeKind::TURBOFAN_JS)) {
      job->RetryOptimization(shared->disabled_optimization_reason());
    } else if (job->FinalizeJob(isolate) == CompilationJob::SUCCEEDED) {
      job->RecordCompilationStats(ConcurrencyMode::kConcurrent, isolate);
      job->RecordFunctionCompilation(LogEventListener::CodeTag::kFunction,
                                     isolate);
      if (V8_LIKELY(use_result)) {
        function->SetTieringInProgress(isolate, false,
                                       job->compilation_info()->osr_offset());
        if (!V8_ENABLE_LEAPTIERING_BOOL || IsOSR(osr_offset)) {
          OptimizedCodeCache::Insert(
              isolate, *compilation_info->closure(),
              compilation_info->osr_offset(), *compilation_info->code(),
              compilation_info->function_context_specializing());
        }
        CompilerTracer::TraceCompletedJob(isolate, compilation_info);
        if (IsOSR(osr_offset)) {
          CompilerTracer::TraceOptimizeOSRFinished(isolate, function,
                                                   osr_offset);
        } else {
          function->UpdateOptimizedCode(isolate, *compilation_info->code());
        }
      }
      return;
    }
  }
  DCHECK_EQ(job->state(), CompilationJob::State::kFailed);
  CompilerTracer::TraceAbortedJob(isolate, compilation_info,
                                  job->prepare_in_ms(), job->execute_in_ms(),
                                  job->finalize_in_ms());
  if (V8_LIKELY(use_result)) {
    function->SetTieringInProgress(isolate, false,
                                   job->compilation_info()->osr_offset());
    if (!IsOSR(osr_offset)) {
      function->UpdateCode(isolate, shared->GetCode(isolate));
    }
  }
}
References v8::internal::OptimizedCompilationInfo::closure(), v8::internal::OptimizedCompilationInfo::code(), v8::internal::TurbofanCompilationJob::compilation_info(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::OptimizedCompilationJob::execute_in_ms(), v8::internal::OptimizedCompilationJob::finalize_in_ms(), v8::internal::OptimizedCompilationJob::FinalizeJob(), v8::internal::anonymous_namespace{compiler.cc}::IsOSR(), v8::internal::kConcurrent, v8::internal::CompilationJob::kFailed, v8::internal::torque::ls::kFunction, v8::internal::CompilationJob::kReadyToFinalize, v8::internal::OptimizedCompilationInfo::osr_offset(), v8::internal::OptimizedCompilationJob::prepare_in_ms(), RCS_SCOPE, v8::internal::TurbofanCompilationJob::RecordCompilationStats(), v8::internal::TurbofanCompilationJob::RecordFunctionCompilation(), v8::internal::TurbofanCompilationJob::RetryOptimization(), v8::internal::OptimizedCompilationInfo::shared_info(), v8::internal::CompilationJob::state(), v8::internal::CompilationJob::SUCCEEDED, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_EVENT_WITH_FLOW0, v8::internal::TurbofanCompilationJob::trace_id(), V8_ENABLE_LEAPTIERING_BOOL, and V8_LIKELY.
Referenced by v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions().
GetFunctionFromEval()
MaybeDirectHandle< JSFunction > v8::internal::Compiler::GetFunctionFromEval (Isolate * isolate, DirectHandle< String > source, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< Context > context, LanguageMode language_mode, ParseRestriction restriction, int parameters_end_pos, int eval_position, ParsingWhileDebugging parsing_while_debugging = ParsingWhileDebugging::kNo) [static]
Definition at line 3266 of file compiler.cc.
                                                   {
  // The cache lookup key needs to be aware of the separation between the
  // parameters and the body to prevent this valid invocation:
  // Function("", "function anonymous(\n/**/) {\n}");
  // from adding an entry that falsely approves this invalid invocation:
  // Function("\n/**/) {\nfunction anonymous(", "}");
  // The actual eval_position for indirect eval and CreateDynamicFunction
  // is unused (just 0), which means it's an available field to use to indicate
  // this separation. But to make sure we're not causing other false hits, we
  // negate the scope position.
  int eval_cache_position = eval_position;
  if (restriction == ONLY_SINGLE_FUNCTION_LITERAL &&
      parameters_end_pos != kNoSourcePosition) {
    // use the parameters_end_pos as the eval_position in the eval cache.
    DCHECK_EQ(eval_position, kNoSourcePosition);
    eval_cache_position = -parameters_end_pos;
  }
  CompilationCache* compilation_cache = isolate->compilation_cache();
  InfoCellPair eval_result = compilation_cache->LookupEval(
      source, outer_info, context, language_mode, eval_cache_position);
  if (eval_result.has_js_function()) {
    DirectHandle<JSFunction> result =
        direct_handle(eval_result.js_function(), isolate);
    if (v8_flags.reuse_scope_infos) {
      CHECK_EQ(result->context()->scope_info(), context->scope_info());
    }
    Tagged<FeedbackCell> feedback_cell = result->raw_feedback_cell();
    FeedbackCell::ClosureCountTransition cell_transition =
        feedback_cell->IncrementClosureCount(isolate);
    if (cell_transition == FeedbackCell::kOneToMany &&
        result->code(isolate)->is_context_specialized()) {
      result->UpdateCode(isolate, *BUILTIN_CODE(isolate, CompileLazy));
    }
    result->set_context(*context, kReleaseStore);
    return result;
  }
  DirectHandle<SharedFunctionInfo> shared_info;
  Handle<Script> script;
  IsCompiledScope is_compiled_scope;
  bool allow_eval_cache;
  if (eval_result.has_shared()) {
    // Make sure that the scope_info of the context we're eval-ing in matches
    // the scope_info we compiled the code for.
    CHECK_IMPLIES(
        !IsNativeContext(*context),
        eval_result.shared()->GetOuterScopeInfo() == context->scope_info());
    shared_info =
        DirectHandle<SharedFunctionInfo>(eval_result.shared(), isolate);
    script = Handle<Script>(Cast<Script>(shared_info->script()), isolate);
    is_compiled_scope = shared_info->is_compiled_scope(isolate);
    allow_eval_cache = true;
  } else {
    UnoptimizedCompileFlags flags = UnoptimizedCompileFlags::ForToplevelCompile(
        isolate, true, language_mode, REPLMode::kNo, ScriptType::kClassic,
        v8_flags.lazy_eval);
    flags.set_is_eval(true);
    flags.set_parsing_while_debugging(parsing_while_debugging);
    DCHECK(!flags.is_module());
    flags.set_parse_restriction(restriction);
    UnoptimizedCompileState compile_state;
    ReusableUnoptimizedCompileState reusable_state(isolate);
    ParseInfo parse_info(isolate, flags, &compile_state, &reusable_state);
    parse_info.set_parameters_end_pos(parameters_end_pos);
    MaybeDirectHandle<ScopeInfo> maybe_outer_scope_info;
    if (!IsNativeContext(*context)) {
      maybe_outer_scope_info = direct_handle(context->scope_info(), isolate);
    }
    script = parse_info.CreateScript(
        isolate, source, kNullMaybeHandle,
        OriginOptionsForEval(outer_info->script(), parsing_while_debugging));
    script->set_eval_from_shared(*outer_info);
    if (eval_position == kNoSourcePosition) {
      // If the position is missing, attempt to get the code offset by
      // walking the stack. Do not translate the code offset into source
      // position, but store it as negative value for lazy translation.
      DebuggableStackFrameIterator it(isolate);
      if (!it.done() && it.is_javascript()) {
        FrameSummary summary = it.GetTopValidFrame();
        script->set_eval_from_shared(
            summary.AsJavaScript().function()->shared());
        script->set_origin_options(
            OriginOptionsForEval(*summary.script(), parsing_while_debugging));
        eval_position = -summary.code_offset();
      } else {
        eval_position = 0;
      }
    }
    script->set_eval_from_position(eval_position);
    if (!v8::internal::CompileToplevel(&parse_info, script,
                                       maybe_outer_scope_info, isolate,
                                       &is_compiled_scope)
             .ToHandle(&shared_info)) {
      return MaybeDirectHandle<JSFunction>();
    }
    allow_eval_cache = parse_info.allow_eval_cache();
  }
  // If caller is strict mode, the result must be in strict mode as well.
  DCHECK(is_sloppy(language_mode) || is_strict(shared_info->language_mode()));
  DirectHandle<JSFunction> result;
  if (eval_result.has_shared()) {
    result = Factory::JSFunctionBuilder{isolate, shared_info, context}
                 .set_allocation_type(AllocationType::kYoung)
                 .Build();
    // TODO(mythria): I don't think we need this here. PostInstantiation
    // already initializes feedback cell.
    JSFunction::InitializeFeedbackCell(isolate, result, &is_compiled_scope,
                                       true);
    if (allow_eval_cache) {
      // Make sure to cache this result.
      DirectHandle<FeedbackCell> new_feedback_cell(result->raw_feedback_cell(),
                                                   isolate);
      compilation_cache->UpdateEval(source, outer_info, result, language_mode,
                                    eval_cache_position);
    }
  } else {
    result = Factory::JSFunctionBuilder{isolate, shared_info, context}
                 .set_allocation_type(AllocationType::kYoung)
                 .Build();
    // TODO(mythria): I don't think we need this here. PostInstantiation
    // already initializes feedback cell.
    JSFunction::InitializeFeedbackCell(isolate, result, &is_compiled_scope,
                                       true);
    if (allow_eval_cache) {
      compilation_cache->PutEval(source, outer_info, result,
                                 eval_cache_position);
    }
  }
  CHECK(is_compiled_scope.is_compiled());
  return result;
}
References v8::internal::ParseInfo::allow_eval_cache(), BUILTIN_CODE, CHECK, CHECK_EQ, CHECK_IMPLIES, v8::internal::FrameSummary::code_offset(), v8::internal::Isolate::compilation_cache(), v8::internal::wasm::CompileLazy(), v8::internal::anonymous_namespace{compiler.cc}::CompileToplevel(), v8::internal::ParseInfo::CreateScript(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::DebuggableStackFrameIterator::done(), v8::internal::flags, v8::internal::UnoptimizedCompileFlags::ForToplevelCompile(), v8::internal::DebuggableStackFrameIterator::GetTopValidFrame(), v8::internal::InfoCellPair::has_js_function(), v8::internal::InfoCellPair::has_shared(), v8::internal::JSFunction::InitializeFeedbackCell(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::DebuggableStackFrameIterator::is_javascript(), v8::internal::is_sloppy(), v8::internal::is_strict(), v8::internal::InfoCellPair::js_function(), v8::kClassic, v8::internal::kNo, v8::internal::kNoSourcePosition, v8::internal::kNullMaybeHandle, v8::internal::FeedbackCell::kOneToMany, v8::kReleaseStore, v8::internal::kYoung, v8::internal::CompilationCache::LookupEval(), v8::internal::ONLY_SINGLE_FUNCTION_LITERAL, v8::internal::anonymous_namespace{compiler.cc}::OriginOptionsForEval(), v8::internal::CompilationCache::PutEval(), v8::base::internal::result, v8::internal::FrameSummary::script(), v8::internal::script, v8::internal::ParseInfo::set_parameters_end_pos(), v8::internal::InfoCellPair::shared(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::CompilationCache::UpdateEval(), and v8::internal::v8_flags.
Referenced by v8::internal::DebugEvaluate::Evaluate(), and GetFunctionFromValidatedString().
GetFunctionFromString()
MaybeDirectHandle< JSFunction > v8::internal::Compiler::GetFunctionFromString (Isolate * isolate, DirectHandle< NativeContext > context, Handle< i::Object > source, int parameters_end_pos, bool is_code_like) [static]
Definition at line 3515 of file compiler.cc.
                                                                      {
  MaybeDirectHandle<String> validated_source =
      ValidateDynamicCompilationSource(isolate, context, source, is_code_like)
          .first;
  return GetFunctionFromValidatedString(isolate, context, validated_source,
                                        ONLY_SINGLE_FUNCTION_LITERAL,
                                        parameters_end_pos);
}
References GetFunctionFromValidatedString(), v8::internal::ONLY_SINGLE_FUNCTION_LITERAL, and ValidateDynamicCompilationSource().
Referenced by v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction().
GetFunctionFromValidatedString()
MaybeDirectHandle< JSFunction > v8::internal::Compiler::GetFunctionFromValidatedString (Isolate * isolate, DirectHandle< NativeContext > context, MaybeDirectHandle< String > source, ParseRestriction restriction, int parameters_end_pos) [static]
Definition at line 3493 of file compiler.cc.
                            {
  // Raise an EvalError if we did not receive a string.
  if (source.is_null()) {
    Handle<Object> error_message =
        native_context->ErrorMessageForCodeGenerationFromStrings();
    THROW_NEW_ERROR(isolate, NewEvalError(MessageTemplate::kCodeGenFromStrings,
                                          error_message));
  }
  // Compile source string in the native context.
  int eval_position = kNoSourcePosition;
  DirectHandle<SharedFunctionInfo> outer_info(
      native_context->empty_function()->shared(), isolate);
  return Compiler::GetFunctionFromEval(
      isolate, source.ToHandleChecked(), outer_info, native_context,
      LanguageMode::kSloppy, restriction, parameters_end_pos, eval_position);
}
References GetFunctionFromEval(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::kNoSourcePosition, v8::internal::kSloppy, v8::internal::native_context, THROW_NEW_ERROR, and v8::internal::MaybeDirectHandle< T >::ToHandleChecked().
Referenced by v8::internal::BUILTIN(), and GetFunctionFromString().
GetSharedFunctionInfo()
template<typename IsolateT >
template DirectHandle< SharedFunctionInfo > v8::internal::Compiler::GetSharedFunctionInfo (FunctionLiteral * node, DirectHandle< Script > script, IsolateT * isolate) [static]
Definition at line 4330 of file compiler.cc.
                                                                              {
  // If we're parallel compiling functions, we might already have attached a SFI
  // to this literal.
  if (!literal->shared_function_info().is_null()) {
    return literal->shared_function_info();
  }
  // Precondition: code has been parsed and scopes have been analyzed.
  MaybeDirectHandle<SharedFunctionInfo> maybe_existing;
  // Find any previously allocated shared function info for the given literal.
  maybe_existing = Script::FindSharedFunctionInfo(script, isolate, literal);
  // If we found an existing shared function info, return it.
  DirectHandle<SharedFunctionInfo> existing;
  if (maybe_existing.ToHandle(&existing)) {
    // If the function has been uncompiled (bytecode flushed) it will have lost
    // any preparsed data. If we produced preparsed data during this compile for
    // this function, replace the uncompiled data with one that includes it.
    if (literal->produced_preparse_data() != nullptr &&
        existing->HasUncompiledDataWithoutPreparseData(isolate)) {
      DirectHandle<UncompiledData> existing_uncompiled_data(
          existing->uncompiled_data(isolate), isolate);
      DCHECK_EQ(literal->start_position(),
                existing_uncompiled_data->start_position());
      DCHECK_EQ(literal->end_position(),
                existing_uncompiled_data->end_position());
      // Use existing uncompiled data's inferred name as it may be more
      // accurate than the literal we preparsed.
      Handle<String> inferred_name =
          handle(existing_uncompiled_data->inferred_name(), isolate);
      Handle<PreparseData> preparse_data =
          literal->produced_preparse_data()->Serialize(isolate);
      DirectHandle<UncompiledData> new_uncompiled_data =
          isolate->factory()->NewUncompiledDataWithPreparseData(
              inferred_name, existing_uncompiled_data->start_position(),
              existing_uncompiled_data->end_position(), preparse_data);
      existing->set_uncompiled_data(*new_uncompiled_data);
    }
    return existing;
  }
  // Allocate a shared function info object which will be compiled lazily.
  DirectHandle<SharedFunctionInfo> result =
      isolate->factory()->NewSharedFunctionInfoForLiteral(literal, script,
                                                          false);
  return result;
}
References DCHECK_EQ, v8::internal::FunctionLiteral::end_position(), v8::internal::Script::FindSharedFunctionInfo(), v8::internal::handle(), v8::internal::FunctionLiteral::produced_preparse_data(), v8::base::internal::result, v8::internal::script, v8::internal::ProducedPreparseData::Serialize(), v8::internal::FunctionLiteral::shared_function_info(), v8::internal::FunctionLiteral::start_position(), and v8::internal::MaybeDirectHandle< T >::ToHandle().
Referenced by v8::internal::interpreter::BytecodeGenerator::AddToEagerLiteralsIfEager(), v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::AllocateDeclarations(), and v8::internal::interpreter::BytecodeGenerator::AllocateDeferredConstants().
GetSharedFunctionInfoForScript()
MaybeDirectHandle< SharedFunctionInfo > v8::internal::Compiler::GetSharedFunctionInfoForScript (Isolate * isolate, Handle< String > source, const ScriptDetails & script_details, ScriptCompiler::CompileOptions compile_options, ScriptCompiler::NoCacheReason no_cache_reason, NativesFlag is_natives_code, ScriptCompiler::CompilationDetails * compilation_details) [static]
Definition at line 4074 of file compiler.cc.
                                                           {
  return GetSharedFunctionInfoForScriptImpl(
      isolate, source, script_details, nullptr, nullptr, nullptr, nullptr,
      nullptr, compile_options, no_cache_reason, natives, compilation_details);
}
References v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl().
Referenced by v8::ScriptCompiler::CompileUnboundInternal(), and v8::internal::anonymous_namespace{debug-evaluate.cc}::GetFunctionInfo().
GetSharedFunctionInfoForScriptWithCachedData()
MaybeDirectHandle< SharedFunctionInfo > v8::internal::Compiler::GetSharedFunctionInfoForScriptWithCachedData (Isolate * isolate, Handle< String > source, const ScriptDetails & script_details, AlignedCachedData * cached_data, ScriptCompiler::CompileOptions compile_options, ScriptCompiler::NoCacheReason no_cache_reason, NativesFlag is_natives_code, ScriptCompiler::CompilationDetails * compilation_details) [static]
Definition at line 4098 of file compiler.cc.
                                                           {
  return GetSharedFunctionInfoForScriptImpl(
      isolate, source, script_details, nullptr, cached_data, nullptr, nullptr,
      nullptr, compile_options, no_cache_reason, natives, compilation_details);
}
References v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl().
Referenced by v8::debug::CompileInspectorScript(), and v8::ScriptCompiler::CompileUnboundInternal().
GetSharedFunctionInfoForScriptWithCompileHints()
MaybeDirectHandle< SharedFunctionInfo > v8::internal::Compiler::GetSharedFunctionInfoForScriptWithCompileHints (Isolate * isolate, Handle< String > source, const ScriptDetails & script_details, v8::CompileHintCallback compile_hint_callback, void * compile_hint_callback_data, ScriptCompiler::CompileOptions compile_options, ScriptCompiler::NoCacheReason no_cache_reason, NativesFlag is_natives_code, ScriptCompiler::CompilationDetails * compilation_details) [static]
Definition at line 4124 of file compiler.cc.
                                                           {
  return GetSharedFunctionInfoForScriptImpl(
      isolate, source, script_details, nullptr, nullptr, nullptr,
      compile_hint_callback, compile_hint_callback_data, compile_options,
      no_cache_reason, natives, compilation_details);
}
References v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl().
Referenced by v8::ScriptCompiler::CompileUnboundInternal().
GetSharedFunctionInfoForScriptWithDeserializeTask()
MaybeDirectHandle< SharedFunctionInfo > v8::internal::Compiler::GetSharedFunctionInfoForScriptWithDeserializeTask (Isolate * isolate, Handle< String > source, const ScriptDetails & script_details, BackgroundDeserializeTask * deserialize_task, ScriptCompiler::CompileOptions compile_options, ScriptCompiler::NoCacheReason no_cache_reason, NativesFlag is_natives_code, ScriptCompiler::CompilationDetails * compilation_details) [static]
Definition at line 4110 of file compiler.cc.
                                                           {
  return GetSharedFunctionInfoForScriptImpl(
      isolate, source, script_details, nullptr, nullptr, deserialize_task,
      nullptr, nullptr, compile_options, no_cache_reason, natives,
      compilation_details);
}
References v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl().
Referenced by v8::ScriptCompiler::CompileUnboundInternal().
GetSharedFunctionInfoForScriptWithExtension()
MaybeDirectHandle< SharedFunctionInfo > v8::internal::Compiler::GetSharedFunctionInfoForScriptWithExtension (Isolate * isolate, Handle< String > source, const ScriptDetails & script_details, v8::Extension * extension, ScriptCompiler::CompileOptions compile_options, NativesFlag is_natives_code, ScriptCompiler::CompilationDetails * compilation_details) [static]
Definition at line 4086 of file compiler.cc.
                                                           {
  return GetSharedFunctionInfoForScriptImpl(
      isolate, source, script_details, extension, nullptr, nullptr, nullptr,
      nullptr, compile_options, ScriptCompiler::kNoCacheBecauseV8Extension,
      natives, compilation_details);
}
References v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), and v8::ScriptCompiler::kNoCacheBecauseV8Extension.
Referenced by v8::internal::Genesis::CompileExtension().
GetSharedFunctionInfoForStreamedScript()
MaybeDirectHandle< SharedFunctionInfo > v8::internal::Compiler::GetSharedFunctionInfoForStreamedScript (Isolate * isolate, Handle< String > source, const ScriptDetails & script_details, ScriptStreamingData * streaming_data, IsCompiledScope * is_compiled_scope, ScriptCompiler::CompilationDetails * compilation_details) [static]
Definition at line 4252 of file compiler.cc.
                                                           {
  DCHECK(!script_details.origin_options.IsWasm());
  ScriptCompileTimerScope compile_timer(
      isolate, ScriptCompiler::kNoCacheBecauseStreamingSource,
      compilation_details);
  PostponeInterruptsScope postpone(isolate);
  BackgroundCompileTask* task = streaming_data->task.get();
  MaybeDirectHandle<SharedFunctionInfo> maybe_result;
  MaybeDirectHandle<Script> maybe_cached_script;
  // Check if compile cache already holds the SFI, if so no need to finalize
  // the code compiled on the background thread.
  CompilationCache* compilation_cache = isolate->compilation_cache();
  {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                 "V8.StreamingFinalization.CheckCache");
    CompilationCacheScript::LookupResult lookup_result =
        compilation_cache->LookupScript(source, script_details,
                                        task->flags().outer_language_mode());
    compilation_details->in_memory_cache_result =
        CategorizeLookupResult(lookup_result);
    *is_compiled_scope = lookup_result.is_compiled_scope();
    if (!lookup_result.toplevel_sfi().is_null()) {
      maybe_result = lookup_result.toplevel_sfi();
    }
    if (!maybe_result.is_null()) {
      compile_timer.set_hit_isolate_cache();
    } else {
      maybe_cached_script = lookup_result.script();
    }
  }
  if (maybe_result.is_null()) {
    // No cache entry found, finalize compilation of the script and add it to
    // the isolate cache.
    RCS_SCOPE(isolate,
              RuntimeCallCounterId::kCompilePublishBackgroundFinalization);
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                 "V8.OffThreadFinalization.Publish");
    maybe_result = task->FinalizeScript(isolate, source, script_details,
                                        maybe_cached_script);
    DirectHandle<SharedFunctionInfo> result;
    if (maybe_result.ToHandle(&result)) {
      // Get a new is_compiled_scope off the result before the task's data
      // (including the persistent handles owned by its IsCompiledScope) are
      // released.
      *is_compiled_scope = result->is_compiled_scope(isolate);
      if (task->flags().produce_compile_hints()) {
        Cast<Script>(result->script())->set_produce_compile_hints(true);
      }
      // Add compiled code to the isolate cache.
      TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                   "V8.StreamingFinalization.AddToCache");
      compilation_cache->PutScript(source, task->flags().outer_language_mode(),
                                   result);
    }
  }
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "V8.StreamingFinalization.Release");
  streaming_data->Release();
  return maybe_result;
} // namespace internal
References v8::internal::anonymous_namespace{compiler.cc}::anonymous_namespace{compiler.cc}::CategorizeLookupResult(), v8::internal::Isolate::compilation_cache(), v8::internal::DCHECK(), v8::internal::BackgroundCompileTask::FinalizeScript(), v8::internal::BackgroundCompileTask::flags(), v8::ScriptCompiler::CompilationDetails::in_memory_cache_result, v8::internal::CompilationCacheScriptLookupResult::is_compiled_scope(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::ScriptOriginOptions::IsWasm(), v8::ScriptCompiler::kNoCacheBecauseStreamingSource, v8::internal::CompilationCache::LookupScript(), v8::internal::ScriptDetails::origin_options, v8::internal::CompilationCache::PutScript(), RCS_SCOPE, v8::internal::ScriptStreamingData::Release(), v8::base::internal::result, v8::internal::CompilationCacheScriptLookupResult::script(), v8::internal::ScriptStreamingData::task, v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::internal::CompilationCacheScriptLookupResult::toplevel_sfi(), TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnBothBackgroundAndMainThread(), and v8::anonymous_namespace{api.cc}::CompileStreamedSource().
GetWrappedFunction()
MaybeDirectHandle< JSFunction > v8::internal::Compiler::GetWrappedFunction (Isolate * isolate, Handle< String > source, DirectHandle< Context > context, const ScriptDetails & script_details, AlignedCachedData * cached_data, v8::ScriptCompiler::CompileOptions compile_options, v8::ScriptCompiler::NoCacheReason no_cache_reason) [static]
Definition at line 4139 of file compiler.cc.
                                                   {
  ScriptCompiler::CompilationDetails compilation_details;
  ScriptCompileTimerScope compile_timer(isolate, no_cache_reason,
                                        &compilation_details);
  if (compile_options & ScriptCompiler::kConsumeCodeCache) {
    DCHECK(cached_data);
    DCHECK_EQ(script_details.repl_mode, REPLMode::kNo);
  } else {
    DCHECK_NULL(cached_data);
  }
  LanguageMode language_mode = construct_language_mode(v8_flags.use_strict);
  DCHECK(!script_details.wrapped_arguments.is_null());
  MaybeDirectHandle<SharedFunctionInfo> maybe_result;
  DirectHandle<SharedFunctionInfo> result;
  Handle<Script> script;
  IsCompiledScope is_compiled_scope;
  bool can_consume_code_cache =
      compile_options & ScriptCompiler::kConsumeCodeCache;
  CompilationCache* compilation_cache = isolate->compilation_cache();
  // First check per-isolate compilation cache.
  CompilationCacheScript::LookupResult lookup_result =
      compilation_cache->LookupScript(source, script_details, language_mode);
  maybe_result = lookup_result.toplevel_sfi();
  if (maybe_result.ToHandle(&result)) {
    is_compiled_scope = result->is_compiled_scope(isolate);
    compile_timer.set_hit_isolate_cache();
  } else if (can_consume_code_cache) {
    compile_timer.set_consuming_code_cache();
    // Then check cached code provided by embedder.
    NestedTimedHistogramScope timer(isolate->counters()->compile_deserialize());
    RCS_SCOPE(isolate, RuntimeCallCounterId::kCompileDeserialize);
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                 "V8.CompileDeserialize");
    maybe_result = CodeSerializer::Deserialize(isolate, cached_data, source,
                                               script_details);
    bool consuming_code_cache_succeeded = false;
    if (maybe_result.ToHandle(&result)) {
      is_compiled_scope = result->is_compiled_scope(isolate);
      if (is_compiled_scope.is_compiled()) {
        consuming_code_cache_succeeded = true;
        // Promote to per-isolate compilation cache.
        compilation_cache->PutScript(source, language_mode, result);
      }
    }
    if (!consuming_code_cache_succeeded) {
      // Deserializer failed. Fall through to compile.
      compile_timer.set_consuming_code_cache_failed();
    }
  }
  if (maybe_result.is_null()) {
    UnoptimizedCompileFlags flags = UnoptimizedCompileFlags::ForToplevelCompile(
        isolate, true, language_mode, script_details.repl_mode,
        ScriptType::kClassic, v8_flags.lazy);
    flags.set_is_eval(true); // Use an eval scope as declaration scope.
    flags.set_function_syntax_kind(FunctionSyntaxKind::kWrapped);
    // TODO(delphick): Remove this and instead make the wrapped and wrapper
    // functions fully non-lazy instead thus preventing source positions from
    // being omitted.
    flags.set_collect_source_positions(true);
    flags.set_is_eager(compile_options & ScriptCompiler::kEagerCompile);
    UnoptimizedCompileState compile_state;
    ReusableUnoptimizedCompileState reusable_state(isolate);
    ParseInfo parse_info(isolate, flags, &compile_state, &reusable_state);
    MaybeDirectHandle<ScopeInfo> maybe_outer_scope_info;
    if (!IsNativeContext(*context)) {
      maybe_outer_scope_info = direct_handle(context->scope_info(), isolate);
    }
    script = NewScript(isolate, &parse_info, source, script_details,
                       NOT_NATIVES_CODE);
    DirectHandle<SharedFunctionInfo> top_level;
    maybe_result = v8::internal::CompileToplevel(&parse_info, script,
                                                 maybe_outer_scope_info,
                                                 isolate, &is_compiled_scope);
    if (maybe_result.is_null()) isolate->ReportPendingMessages();
    ASSIGN_RETURN_ON_EXCEPTION(isolate, top_level, maybe_result);
    SharedFunctionInfo::ScriptIterator infos(isolate, *script);
    for (Tagged<SharedFunctionInfo> info = infos.Next(); !info.is_null();
         info = infos.Next()) {
      if (info->is_wrapped()) {
        result = direct_handle(info, isolate);
        break;
      }
    }
    DCHECK(!result.is_null());
    is_compiled_scope = result->is_compiled_scope(isolate);
    script = Handle<Script>(Cast<Script>(result->script()), isolate);
    // Add the result to the isolate cache if there's no context extension.
    if (maybe_outer_scope_info.is_null()) {
      compilation_cache->PutScript(source, language_mode, result);
    }
  }
  DCHECK(is_compiled_scope.is_compiled());
  return Factory::JSFunctionBuilder{isolate, result, context}
      .set_allocation_type(AllocationType::kYoung)
      .Build();
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::compilation_cache(), v8::internal::anonymous_namespace{compiler.cc}::CompileToplevel(), v8::internal::construct_language_mode(), v8::internal::Isolate::counters(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, v8::internal::CodeSerializer::Deserialize(), v8::internal::direct_handle(), v8::internal::flags, v8::internal::UnoptimizedCompileFlags::ForToplevelCompile(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::kClassic, v8::ScriptCompiler::kConsumeCodeCache, v8::ScriptCompiler::kEagerCompile, v8::internal::kNo, v8::internal::kWrapped, v8::internal::kYoung, v8::internal::CompilationCache::LookupScript(), v8::internal::anonymous_namespace{compiler.cc}::NewScript(), v8::internal::SharedFunctionInfo::ScriptIterator::Next(), v8::internal::NOT_NATIVES_CODE, v8::internal::CompilationCache::PutScript(), RCS_SCOPE, v8::internal::ScriptDetails::repl_mode, v8::internal::Isolate::ReportPendingMessages(), v8::base::internal::result, v8::internal::script, v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::internal::CompilationCacheScriptLookupResult::toplevel_sfi(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, v8::internal::v8_flags, and v8::internal::ScriptDetails::wrapped_arguments.
Referenced by v8::ScriptCompiler::CompileFunction().
InstallInterpreterTrampolineCopy()
void v8::internal::Compiler::InstallInterpreterTrampolineCopy (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared_info, LogEventListener::CodeTag log_tag) [static]
Definition at line 683 of file compiler.cc.
                                     {
  DCHECK(isolate->interpreted_frames_native_stack());
  if (!IsBytecodeArray(shared_info->GetTrustedData(isolate))) {
    DCHECK(!shared_info->HasInterpreterData(isolate));
    return;
  }
  DirectHandle<BytecodeArray> bytecode_array(
      shared_info->GetBytecodeArray(isolate), isolate);
  DirectHandle<Code> code =
      Builtins::CreateInterpreterEntryTrampolineForProfiling(isolate);
  DirectHandle<InterpreterData> interpreter_data =
      isolate->factory()->NewInterpreterData(bytecode_array, code);
  if (shared_info->HasBaselineCode()) {
    shared_info->baseline_code(kAcquireLoad)
        ->set_bytecode_or_interpreter_data(*interpreter_data);
  } else {
    // IsBytecodeArray
    shared_info->set_interpreter_data(isolate, *interpreter_data);
  }
  DirectHandle<Script> script(Cast<Script>(shared_info->script()), isolate);
  DirectHandle<AbstractCode> abstract_code = Cast<AbstractCode>(code);
  Script::PositionInfo info;
  Script::GetPositionInfo(script, shared_info->StartPosition(), &info);
  int line_num = info.line + 1;
  int column_num = info.column + 1;
  DirectHandle<String> script_name(IsString(script->name())
                                       ? Cast<String>(script->name())
                                       : ReadOnlyRoots(isolate).empty_string(),
                                   isolate);
  PROFILE(isolate, CodeCreateEvent(log_tag, abstract_code, shared_info,
                                   script_name, line_num, column_num));
}
References code, v8::internal::Script::PositionInfo::column, v8::internal::Builtins::CreateInterpreterEntryTrampolineForProfiling(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::Script::GetPositionInfo(), v8::internal::Isolate::interpreted_frames_native_stack(), v8::kAcquireLoad, v8::internal::Script::PositionInfo::line, v8::internal::Factory::NewInterpreterData(), PROFILE, and v8::internal::script.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedCompilation().
LogFunctionCompilation()
void v8::internal::Compiler::LogFunctionCompilation (Isolate * isolate, LogEventListener::CodeTag code_type, DirectHandle< Script > script, DirectHandle< SharedFunctionInfo > shared, DirectHandle< FeedbackVector > vector, DirectHandle< AbstractCode > abstract_code, CodeKind kind, double time_taken_ms) [static]
Definition at line 300 of file compiler.cc.
                                                                           {
  DCHECK_NE(*abstract_code,
            Cast<AbstractCode>(*BUILTIN_CODE(isolate, CompileLazy)));
  // Log the code generation. If source information is available include
  // script name and line number. Check explicitly whether logging is
  // enabled as finding the line number is not free.
  if (!isolate->IsLoggingCodeCreation()) return;
  Script::PositionInfo info;
  Script::GetPositionInfo(script, shared->StartPosition(), &info);
  int line_num = info.line + 1;
  int column_num = info.column + 1;
  DirectHandle<String> script_name(IsString(script->name())
                                       ? Cast<String>(script->name())
                                       : ReadOnlyRoots(isolate).empty_string(),
                                   isolate);
  LogEventListener::CodeTag log_tag =
      V8FileLogger::ToNativeByScript(code_type, *script);
  PROFILE(isolate, CodeCreateEvent(log_tag, abstract_code, shared, script_name,
                                   line_num, column_num));
  if (!vector.is_null()) {
    LOG(isolate, FeedbackVectorEvent(*vector, *abstract_code));
  }
  if (!v8_flags.log_function_events) return;
  std::string name;
  switch (kind) {
    case CodeKind::INTERPRETED_FUNCTION:
      name = "interpreter";
      break;
    case CodeKind::BASELINE:
      name = "baseline";
      break;
    case CodeKind::MAGLEV:
      name = "maglev";
      break;
    case CodeKind::TURBOFAN_JS:
      name = "turbofan";
      break;
    default:
      UNREACHABLE();
  }
  switch (code_type) {
    case LogEventListener::CodeTag::kEval:
      name += "-eval";
      break;
    case LogEventListener::CodeTag::kScript:
    case LogEventListener::CodeTag::kFunction:
      break;
    default:
      UNREACHABLE();
  }
  DirectHandle<String> debug_name =
      SharedFunctionInfo::DebugName(isolate, shared);
  DisallowGarbageCollection no_gc;
  LOG(isolate, FunctionEvent(name.c_str(), script->id(), time_taken_ms,
                             shared->StartPosition(), shared->EndPosition(),
                             *debug_name));
}
References BUILTIN_CODE, v8::internal::Script::PositionInfo::column, v8::internal::wasm::CompileLazy(), DCHECK_NE, v8::internal::SharedFunctionInfo::DebugName(), v8::internal::Script::GetPositionInfo(), v8::internal::DirectHandle< T >::is_null(), v8::internal::Isolate::IsLoggingCodeCreation(), v8::internal::torque::ls::kFunction, v8::internal::Script::PositionInfo::line, LOG, v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, PROFILE, v8::internal::script, v8::internal::string, v8::internal::V8FileLogger::ToNativeByScript(), v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
Referenced by CompileSharedWithBaseline(), v8::internal::baseline::BaselineCompilerTask::Install(), v8::internal::anonymous_namespace{compiler.cc}::LogUnoptimizedCompilation(), and v8::internal::TurbofanCompilationJob::RecordFunctionCompilation().
PostInstantiation()
void v8::internal::Compiler::PostInstantiation (Isolate * isolate, DirectHandle< JSFunction > function, IsCompiledScope * is_compiled_scope) [static]
Definition at line 4570 of file compiler.cc.
                                                                     {
  DirectHandle<SharedFunctionInfo> shared(function->shared(), isolate);
  // If code is compiled to bytecode (i.e., isn't asm.js), then allocate a
  // feedback and check for optimized code.
  if (is_compiled_scope->is_compiled() && shared->HasBytecodeArray()) {
    // Don't reset budget if there is a closure feedback cell array already. We
    // are just creating a new closure that shares the same feedback cell.
    JSFunction::InitializeFeedbackCell(isolate, function, is_compiled_scope,
                                       false);
#ifndef V8_ENABLE_LEAPTIERING
    if (function->has_feedback_vector()) {
      // Evict any deoptimized code on feedback vector. We need to do this after
      // creating the closure, since any heap allocations could trigger a GC and
      // deoptimized the code on the feedback vector. So check for any
      // deoptimized code just before installing it on the function.
      function->feedback_vector()->EvictOptimizedCodeMarkedForDeoptimization(
          isolate, *shared, "new function from shared function info");
      Tagged<Code> code = function->feedback_vector()->optimized_code(isolate);
      if (!code.is_null()) {
        // Caching of optimized code enabled and optimized code found.
        DCHECK(!code->marked_for_deoptimization());
        DCHECK(function->shared()->is_compiled());
        function->UpdateOptimizedCode(isolate, code);
      }
    }
#endif // !V8_ENABLE_LEAPTIERING
    if (v8_flags.always_turbofan && shared->allows_lazy_compilation() &&
        !shared->optimization_disabled(CodeKind::TURBOFAN_JS) &&
        !function->HasAvailableOptimizedCode(isolate)) {
      CompilerTracer::TraceMarkForAlwaysOpt(isolate, function);
      JSFunction::EnsureFeedbackVector(isolate, function, is_compiled_scope);
      function->RequestOptimization(isolate, CodeKind::TURBOFAN_JS,
                                    ConcurrencyMode::kSynchronous);
    }
  }
  if (shared->is_toplevel() || shared->is_wrapped()) {
    // If it's a top-level script, report compilation to the debugger.
    DirectHandle<Script> script(Cast<Script>(shared->script()), isolate);
    isolate->debug()->OnAfterCompile(script);
    bool source_rundown_enabled;
    TRACE_EVENT_CATEGORY_GROUP_ENABLED(
        TRACE_DISABLED_BY_DEFAULT("devtools.v8-source-rundown"),
        &source_rundown_enabled);
    if (source_rundown_enabled) {
      script->TraceScriptRundown();
    }
    bool source_rundown_sources_enabled;
    TRACE_EVENT_CATEGORY_GROUP_ENABLED(
        TRACE_DISABLED_BY_DEFAULT("devtools.v8-source-rundown-sources"),
        &source_rundown_sources_enabled);
    if (source_rundown_sources_enabled) {
      script->TraceScriptRundownSources();
    }
  }
}
References code, v8::internal::DCHECK(), v8::internal::Isolate::debug(), v8::internal::JSFunction::EnsureFeedbackVector(), v8::internal::JSFunction::InitializeFeedbackCell(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::kSynchronous, v8::internal::Debug::OnAfterCompile(), v8::internal::script, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_CATEGORY_GROUP_ENABLED, and v8::internal::v8_flags.
Referenced by v8::internal::Factory::JSFunctionBuilder::Build().
ValidateDynamicCompilationSource()
std::pair< MaybeDirectHandle< String >, bool > v8::internal::Compiler::ValidateDynamicCompilationSource (Isolate * isolate, DirectHandle< NativeContext > context, Handle< i::Object > source_object, bool is_code_like = false) [static]
Definition at line 3450 of file compiler.cc.
                                                              {
  // Check if the context unconditionally allows code gen from strings.
  // allow_code_gen_from_strings can be many things, so we'll always check
  // against the 'false' literal, so that e.g. undefined and 'true' are treated
  // the same.
  if (!IsFalse(context->allow_code_gen_from_strings(), isolate) &&
      IsString(*original_source)) {
    return {Cast<String>(original_source), false};
  }
  // Check if the context wants to block or modify this source object.
  // Double-check that we really have a string now.
  // (Let modify_code_gen_callback decide, if it's been set.)
  if (isolate->modify_code_gen_callback()) {
    Handle<i::Object> modified_source = original_source;
    if (!ModifyCodeGenerationFromStrings(isolate, context, &modified_source,
                                         is_code_like)) {
      return {MaybeHandle<String>(), false};
    }
    if (!IsString(*modified_source)) {
      return {MaybeHandle<String>(), true};
    }
    return {Cast<String>(modified_source), false};
  }
  if (!IsFalse(context->allow_code_gen_from_strings(), isolate) &&
      Object::IsCodeLike(*original_source, isolate)) {
    // Codegen is unconditionally allowed, and we're been given a CodeLike
    // object. Stringify.
    MaybeHandle<String> stringified_source =
        Object::ToString(isolate, original_source);
    return {stringified_source, stringified_source.is_null()};
  }
  // If unconditional codegen was disabled, and no callback defined, we block
  // strings and allow all other objects.
  return {MaybeHandle<String>(), !IsString(*original_source)};
}
References v8::internal::MaybeHandle< T >::is_null(), v8::internal::Object::IsCodeLike(), v8::internal::ModifyCodeGenerationFromStrings(), and v8::Value::ToString().
Referenced by v8::internal::BUILTIN(), and GetFunctionFromString().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/compiler.h
/mnt/V8SourceCode/src/codegen/compiler.cc