v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT > Class Template Reference
#include <maglev-deopt-frame-visitor.h>
Static Public Member Functions
template<typename Function >
static void ForEager (DeoptInfoT *deopt_info, Function &&f)
template<typename Function >
static void ForLazy (DeoptInfoT *deopt_info, Function &&f)
Private Types
using DeoptFrameT = std::conditional_t< std::is_const_v< DeoptInfoT >, const DeoptFrame, DeoptFrame >
using ValueNodeT = std::conditional_t< std::is_const_v< DeoptInfoT >, ValueNode *, ValueNode *& >
Private Member Functions
DeoptInfoVisitor (DeoptInfoT *deopt_info)
template<typename Function >
void Visit (DeoptFrameT &frame, Function &&f)
template<bool skip_frame_result = false, typename Function >
void VisitSingleFrame (DeoptFrameT &frame, Function &&f)
Private Attributes
const DeoptInfoT * deopt_info_
const VirtualObjectList virtual_objects_
Detailed Description
template<typename DeoptInfoT>
class v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >
Definition at line 18 of file maglev-deopt-frame-visitor.h.
Member Typedef Documentation
DeoptFrameT
template<typename DeoptInfoT >
using v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::DeoptFrameT = std::conditional_t<std::is_const_v<DeoptInfoT>, const DeoptFrame, DeoptFrame> [private]
Definition at line 40 of file maglev-deopt-frame-visitor.h.
ValueNodeT
template<typename DeoptInfoT >
using v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::ValueNodeT = std::conditional_t<std::is_const_v<DeoptInfoT>, ValueNode*, ValueNode*&> [private]
Definition at line 42 of file maglev-deopt-frame-visitor.h.
Constructor & Destructor Documentation
DeoptInfoVisitor()
template<typename DeoptInfoT >
v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::DeoptInfoVisitor (DeoptInfoT * deopt_info) [inline], [explicit], [private]
Definition at line 45 of file maglev-deopt-frame-visitor.h.
      : deopt_info_(deopt_info),
        virtual_objects_(deopt_info->top_frame().GetVirtualObjects()) {}
Member Function Documentation
ForEager()
template<typename DeoptInfoT >
template<typename Function >
static void v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::ForEager (DeoptInfoT * deopt_info, Function && f) [inline], [static]
Definition at line 21 of file maglev-deopt-frame-visitor.h.
                                                             {
    DeoptInfoVisitor<DeoptInfoT> visitor(deopt_info);
    visitor.Visit(deopt_info->top_frame(), f);
  }
References v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::Visit().
ForLazy()
template<typename DeoptInfoT >
template<typename Function >
static void v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::ForLazy (DeoptInfoT * deopt_info, Function && f) [inline], [static]
Definition at line 27 of file maglev-deopt-frame-visitor.h.
                                                            {
    DeoptInfoVisitor<DeoptInfoT> visitor(deopt_info);
    if (deopt_info->top_frame().parent()) {
      visitor.Visit(*deopt_info->top_frame().parent(), f);
    }
    const bool kSkipResultLocation = true;
    visitor.VisitSingleFrame<kSkipResultLocation>(deopt_info->top_frame(), f);
  }
References v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::Visit(), and v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::VisitSingleFrame().
Visit()
template<typename DeoptInfoT >
template<typename Function >
void v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::Visit (DeoptFrameT & frame, Function && f) [inline], [private]
Definition at line 50 of file maglev-deopt-frame-visitor.h.
                                               {
    if (frame.parent()) {
      Visit(*frame.parent(), f);
    }
    VisitSingleFrame(frame, f);
  }
References v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::VisitSingleFrame().
Referenced by v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::ForEager(), and v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::ForLazy().
VisitSingleFrame()
template<typename DeoptInfoT >
template<bool skip_frame_result = false, typename Function >
void v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::VisitSingleFrame (DeoptFrameT & frame, Function && f) [inline], [private]
Definition at line 58 of file maglev-deopt-frame-visitor.h.
                                                          {
    auto updated_f = [&](ValueNodeT node) {
      DCHECK(!node->template Is<VirtualObject>());
      if (node->template Is<Identity>()) {
        node = node->input(0).node();
      }
      if (auto alloc = node->template TryCast<InlinedAllocation>()) {
        VirtualObject* vobject = virtual_objects_.FindAllocatedWith(alloc);
        if (vobject && (!alloc->HasBeenAnalysed() || alloc->HasBeenElided())) {
          return vobject->ForEachNestedRuntimeInput(virtual_objects_, f);
        }
      }
      f(node);
    };
    switch (frame.type()) {
      case DeoptFrame::FrameType::kInterpretedFrame:
        updated_f(frame.as_interpreted().closure());
        frame.as_interpreted().frame_state()->ForEachValue(
            frame.as_interpreted().unit(),
            [&](ValueNode*& node, interpreter::Register reg) {
              if constexpr (std::is_same_v<DeoptInfoT, LazyDeoptInfo>) {
                // Skip over the result location for lazy deopts, since it is
                // irrelevant for lazy deopts (unoptimized code will recreate
                // the result).
                if (skip_frame_result && deopt_info_->IsResultRegister(reg)) {
                  return;
                }
              }
              updated_f(node);
            });
        break;
      case DeoptFrame::FrameType::kInlinedArgumentsFrame: {
        // The inlined arguments frame can never be the top frame.
        updated_f(frame.as_inlined_arguments().closure());
        for (ValueNode*& node : frame.as_inlined_arguments().arguments()) {
          updated_f(node);
        }
        break;
      }
      case DeoptFrame::FrameType::kConstructInvokeStubFrame: {
        updated_f(frame.as_construct_stub().receiver());
        updated_f(frame.as_construct_stub().context());
        break;
      }
      case DeoptFrame::FrameType::kBuiltinContinuationFrame:
        for (ValueNode*& node : frame.as_builtin_continuation().parameters()) {
          updated_f(node);
        }
        updated_f(frame.as_builtin_continuation().context());
        break;
    }
  }
References v8::internal::DCHECK(), v8::internal::maglev::VirtualObjectList::FindAllocatedWith(), v8::internal::maglev::VirtualObject::ForEachNestedRuntimeInput(), v8::internal::maglev::DeoptFrame::kBuiltinContinuationFrame, v8::internal::maglev::DeoptFrame::kConstructInvokeStubFrame, v8::internal::maglev::DeoptFrame::kInlinedArgumentsFrame, v8::internal::maglev::DeoptFrame::kInterpretedFrame, and v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::virtual_objects_.
Referenced by v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::ForLazy(), and v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::Visit().
Member Data Documentation
deopt_info_
template<typename DeoptInfoT >
const DeoptInfoT* v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::deopt_info_ [private]
Definition at line 37 of file maglev-deopt-frame-visitor.h.
virtual_objects_
template<typename DeoptInfoT >
const VirtualObjectList v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::virtual_objects_ [private]
Definition at line 38 of file maglev-deopt-frame-visitor.h.
Referenced by v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::VisitSingleFrame().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-deopt-frame-visitor.h