v8::internal::NodeBase< Child > Class Template Reference
Public Member Functions
NodeBase ()
void Free (Child *free_list)
IndirectHandle< Object > Publish (Tagged< Object > object)
void Release (Child *free_list)
Tagged< Object > object () const
FullObjectSlot location ()
IndirectHandle< Object > handle ()
Address raw_object () const
uint8_t index () const
void set_index (uint8_t value)
uint16_t wrapper_class_id () const
bool has_wrapper_class_id () const
Child * next_free ()
void set_parameter (void *parameter)
void * parameter () const
void CheckNodeIsFreeNode () const
Static Public Member Functions
static const Child * FromLocation (const Address *location)
static Child * FromLocation (Address *location)
Protected Member Functions
Child * AsChild ()
const Child * AsChild () const
void ClearFields ()
Protected Attributes
Address object_ = kNullAddress
uint16_t class_id_ = 0
uint8_t index_ = 0
uint8_t flags_ = 0
xx xx xx xx xx xx xx xx xx
union {
 Child * next_free = nullptr
 void * parameter
} data_
Detailed Description
template<class Child>
class v8::internal::NodeBase< Child >
Definition at line 291 of file global-handles.cc.
Constructor & Destructor Documentation
NodeBase()
template<class Child >
v8::internal::NodeBase< Child >::NodeBase () [inline]
Definition at line 301 of file global-handles.cc.
             {
    DCHECK_EQ(offsetof(NodeBase, object_), 0);
    DCHECK_EQ(offsetof(NodeBase, class_id_), Internals::kNodeClassIdOffset);
    DCHECK_EQ(offsetof(NodeBase, flags_), Internals::kNodeFlagsOffset);
  }
References v8::internal::NodeBase< Child >::class_id_, DCHECK_EQ, v8::internal::NodeBase< Child >::flags_, v8::internal::Internals::kNodeClassIdOffset, v8::internal::Internals::kNodeFlagsOffset, and v8::internal::NodeBase< Child >::object_.
Member Function Documentation
AsChild() [1/2]
template<class Child >
Child* v8::internal::NodeBase< Child >::AsChild () [inline], [protected]
Definition at line 373 of file global-handles.cc.
{ return reinterpret_cast<Child*>(this); }
Referenced by v8::internal::NodeBase< Child >::CheckNodeIsFreeNode(), v8::internal::NodeBase< Child >::ClearFields(), v8::internal::NodeBase< Child >::Free(), v8::internal::NodeBase< Child >::next_free(), v8::internal::NodeBase< Child >::parameter(), v8::internal::NodeBase< Child >::Publish(), v8::internal::NodeBase< Child >::Release(), and v8::internal::NodeBase< Child >::set_parameter().
AsChild() [2/2]
template<class Child >
const Child* v8::internal::NodeBase< Child >::AsChild () const [inline], [protected]
Definition at line 374 of file global-handles.cc.
{ return reinterpret_cast<const Child*>(this); }
CheckNodeIsFreeNode()
template<class Child >
void v8::internal::NodeBase< Child >::CheckNodeIsFreeNode () const [inline]
Definition at line 366 of file global-handles.cc.
                                   {
    DCHECK_EQ(kGlobalHandleZapValue, object_);
    DCHECK_EQ(v8::HeapProfiler::kPersistentHandleNoClassId, class_id_);
    AsChild()->CheckNodeIsFreeNodeImpl();
  }
References v8::internal::NodeBase< Child >::AsChild(), v8::internal::NodeBase< Child >::class_id_, DCHECK_EQ, v8::internal::kGlobalHandleZapValue, v8::HeapProfiler::kPersistentHandleNoClassId, and v8::internal::NodeBase< Child >::object_.
ClearFields()
template<class Child >
void v8::internal::NodeBase< Child >::ClearFields () [inline], [protected]
Definition at line 376 of file global-handles.cc.
                     {
    // Zap the values for eager trapping.
    object_ = kGlobalHandleZapValue;
    class_id_ = v8::HeapProfiler::kPersistentHandleNoClassId;
    AsChild()->ClearImplFields();
  }
References v8::internal::NodeBase< Child >::AsChild(), v8::internal::NodeBase< Child >::class_id_, v8::internal::kGlobalHandleZapValue, v8::HeapProfiler::kPersistentHandleNoClassId, and v8::internal::NodeBase< Child >::object_.
Referenced by v8::internal::NodeBase< Child >::Free().
Free()
template<class Child >
void v8::internal::NodeBase< Child >::Free (Child * free_list) [inline]
Definition at line 315 of file global-handles.cc.
                              {
    ClearFields();
    AsChild()->MarkAsFree();
    data_.next_free = free_list;
  }
References v8::internal::NodeBase< Child >::AsChild(), v8::internal::NodeBase< Child >::ClearFields(), and v8::internal::NodeBase< Child >::data_.
Referenced by v8::internal::NodeBase< Child >::Release().
FromLocation() [1/2]
template<class Child >
static Child* v8::internal::NodeBase< Child >::FromLocation (Address * location) [inline], [static]
Definition at line 297 of file global-handles.cc.
                                                {
    return reinterpret_cast<Child*>(location);
  }
References v8::internal::NodeBase< Child >::location().
FromLocation() [2/2]
template<class Child >
static const Child* v8::internal::NodeBase< Child >::FromLocation (const Address * location) [inline], [static]
Definition at line 293 of file global-handles.cc.
                                                            {
    return reinterpret_cast<const Child*>(location);
  }
References v8::internal::NodeBase< Child >::location().
handle()
template<class Child >
IndirectHandle<Object> v8::internal::NodeBase< Child >::handle () [inline]
Definition at line 340 of file global-handles.cc.
{ return IndirectHandle<Object>(&object_); }
References v8::internal::NodeBase< Child >::object_.
Referenced by v8::internal::GlobalHandles::ApplyPersistentHandleVisitor(), and v8::internal::NodeBase< Child >::Publish().
has_wrapper_class_id()
template<class Child >
bool v8::internal::NodeBase< Child >::has_wrapper_class_id () const [inline]
Definition at line 347 of file global-handles.cc.
                                    {
    return class_id_ != v8::HeapProfiler::kPersistentHandleNoClassId;
  }
References v8::internal::NodeBase< Child >::class_id_, and v8::HeapProfiler::kPersistentHandleNoClassId.
index()
template<class Child >
uint8_t v8::internal::NodeBase< Child >::index () const [inline]
Definition at line 343 of file global-handles.cc.
{ return index_; }
References v8::internal::NodeBase< Child >::index_.
location()
template<class Child >
FullObjectSlot v8::internal::NodeBase< Child >::location () [inline]
Definition at line 339 of file global-handles.cc.
{ return FullObjectSlot(&object_); }
References v8::internal::NodeBase< Child >::object_.
Referenced by v8::internal::NodeBase< Child >::FromLocation(), and v8::internal::GlobalHandles::ResetWeakNodeIfDead().
next_free()
template<class Child >
Child* v8::internal::NodeBase< Child >::next_free () [inline]
Definition at line 352 of file global-handles.cc.
                     {
    DCHECK(!AsChild()->IsInUse());
    return data_.next_free;
  }
References v8::internal::NodeBase< Child >::AsChild(), v8::internal::NodeBase< Child >::data_, and v8::internal::DCHECK().
object()
template<class Child >
Tagged<Object> v8::internal::NodeBase< Child >::object () const [inline]
Definition at line 338 of file global-handles.cc.
{ return Tagged<Object>(object_); }
References v8::internal::NodeBase< Child >::object_, and v8::internal::Tagged< Object >.
parameter()
template<class Child >
void* v8::internal::NodeBase< Child >::parameter () const [inline]
Definition at line 361 of file global-handles.cc.
                          {
    DCHECK(AsChild()->IsInUse());
    return data_.parameter;
  }
References v8::internal::NodeBase< Child >::AsChild(), v8::internal::NodeBase< Child >::data_, and v8::internal::DCHECK().
Publish()
template<class Child >
IndirectHandle<Object> v8::internal::NodeBase< Child >::Publish (Tagged< Object > object) [inline]
Definition at line 322 of file global-handles.cc.
                                                        {
    DCHECK(!AsChild()->IsInUse());
    data_.parameter = nullptr;
    AsChild()->MarkAsUsed();
    reinterpret_cast<std::atomic<Address>*>(&object_)->store(
        object.ptr(), std::memory_order_release);
    DCHECK(AsChild()->IsInUse());
    return handle();
  }
References v8::internal::NodeBase< Child >::AsChild(), v8::internal::NodeBase< Child >::data_, v8::internal::DCHECK(), v8::internal::NodeBase< Child >::handle(), v8::internal::NodeBase< Child >::object_, and store().
Referenced by v8::internal::GlobalHandles::Create().
raw_object()
template<class Child >
Address v8::internal::NodeBase< Child >::raw_object () const [inline]
Definition at line 341 of file global-handles.cc.
{ return object_; }
References v8::internal::NodeBase< Child >::object_.
Release()
template<class Child >
void v8::internal::NodeBase< Child >::Release (Child * free_list) [inline]
Definition at line 332 of file global-handles.cc.
                                 {
    DCHECK(AsChild()->IsInUse());
    Free(free_list);
    DCHECK(!AsChild()->IsInUse());
  }
References v8::internal::NodeBase< Child >::AsChild(), v8::internal::DCHECK(), and v8::internal::NodeBase< Child >::Free().
set_index()
template<class Child >
void v8::internal::NodeBase< Child >::set_index (uint8_t value) [inline]
Definition at line 344 of file global-handles.cc.
{ index_ = value; }
References v8::internal::NodeBase< Child >::index_, and v8::internal::value.
set_parameter()
template<class Child >
void v8::internal::NodeBase< Child >::set_parameter (void * parameter) [inline]
Definition at line 357 of file global-handles.cc.
                                      {
    DCHECK(AsChild()->IsInUse());
    data_.parameter = parameter;
  }
References v8::internal::NodeBase< Child >::AsChild(), v8::internal::NodeBase< Child >::data_, v8::internal::DCHECK(), and v8::internal::NodeBase< Child >::parameter.
Referenced by v8::internal::GlobalHandles::MoveGlobal().
wrapper_class_id()
template<class Child >
uint16_t v8::internal::NodeBase< Child >::wrapper_class_id () const [inline]
Definition at line 346 of file global-handles.cc.
{ return class_id_; }
References v8::internal::NodeBase< Child >::class_id_.
Referenced by v8::internal::GlobalHandles::ApplyPersistentHandleVisitor().
Member Data Documentation
class_id_
template<class Child >
uint16_t v8::internal::NodeBase< Child >::class_id_ = 0 [protected]
Definition at line 392 of file global-handles.cc.
Referenced by v8::internal::NodeBase< Child >::CheckNodeIsFreeNode(), v8::internal::NodeBase< Child >::ClearFields(), v8::internal::NodeBase< Child >::has_wrapper_class_id(), v8::internal::NodeBase< Child >::NodeBase(), and v8::internal::NodeBase< Child >::wrapper_class_id().
union { ... } v8::internal::NodeBase< Child >::data_ [protected]
Referenced by v8::internal::NodeBase< Child >::Free(), v8::internal::NodeBase< Child >::next_free(), v8::internal::NodeBase< Child >::parameter(), v8::internal::NodeBase< Child >::Publish(), and v8::internal::NodeBase< Child >::set_parameter().
flags_
template<class Child >
uint8_t v8::internal::NodeBase< Child >::flags_ = 0 [protected]
Definition at line 397 of file global-handles.cc.
Referenced by v8::internal::NodeBase< Child >::NodeBase().
index_
template<class Child >
uint8_t v8::internal::NodeBase< Child >::index_ = 0 [protected]
Definition at line 395 of file global-handles.cc.
Referenced by v8::internal::NodeBase< Child >::index(), and v8::internal::NodeBase< Child >::set_index().
next_free
template<class Child >
Child* v8::internal::NodeBase< Child >::next_free = nullptr
Definition at line 403 of file global-handles.cc.
object_
template<class Child >
Address v8::internal::NodeBase< Child >::object_ = kNullAddress [protected]
Definition at line 389 of file global-handles.cc.
Referenced by v8::internal::NodeBase< Child >::CheckNodeIsFreeNode(), v8::internal::NodeBase< Child >::ClearFields(), v8::internal::NodeBase< Child >::handle(), v8::internal::NodeBase< Child >::location(), v8::internal::NodeBase< Child >::NodeBase(), v8::internal::NodeBase< Child >::object(), v8::internal::NodeBase< Child >::Publish(), and v8::internal::NodeBase< Child >::raw_object().
parameter
template<class Child >
void* v8::internal::NodeBase< Child >::parameter
Definition at line 404 of file global-handles.cc.
Referenced by v8::internal::NodeBase< Child >::set_parameter().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/handles/global-handles.cc