v8::internal::HeapObjectIterator Class Reference
#include <heap.h>
Public Types
enum HeapObjectsFiltering { kNoFiltering
, kFilterUnreachable
 }
Public Member Functions
HeapObjectIterator (Heap *heap, HeapObjectsFiltering filtering=kNoFiltering)
HeapObjectIterator (Heap *heap, const SafepointScope &safepoint_scope, HeapObjectsFiltering filtering=kNoFiltering)
~HeapObjectIterator ()
Tagged< HeapObject > Next ()
Private Member Functions
HeapObjectIterator (Heap *heap, SafepointScope *safepoint_scope_or_nullptr, HeapObjectsFiltering filtering)
Tagged< HeapObject > NextObject ()
Private Attributes
Heap * heap_
std::unique_ptr< SafepointScope > safepoint_scope_
std::unique_ptr< HeapObjectsFilter > filter_
SpaceIterator space_iterator_
std::unique_ptr< ObjectIterator > object_iterator_
Detailed Description
Definition at line 2687 of file heap.h.
Member Enumeration Documentation
HeapObjectsFiltering
enum v8::internal::HeapObjectIterator::HeapObjectsFiltering
Enumerator
kNoFiltering
kFilterUnreachable
Definition at line 2689 of file heap.h.
{ kNoFiltering, kFilterUnreachable };
Constructor & Destructor Documentation
HeapObjectIterator() [1/3]
v8::internal::HeapObjectIterator::HeapObjectIterator (Heap * heap, HeapObjectIterator::HeapObjectsFiltering filtering = kNoFiltering) [explicit]
Definition at line 6823 of file heap.cc.
    : HeapObjectIterator(
          heap,
          new SafepointScope(heap->isolate(),
                             kGlobalSafepointForSharedSpaceIsolate),
          filtering) {}
HeapObjectIterator() [2/3]
v8::internal::HeapObjectIterator::HeapObjectIterator (Heap * heap, const SafepointScope & safepoint_scope, HeapObjectsFiltering filtering = kNoFiltering)
Definition at line 6831 of file heap.cc.
    : HeapObjectIterator(heap, nullptr, filtering) {}
 HeapObjectIterator()
v8::internal::HeapObjectIterator::~HeapObjectIterator () [default]
HeapObjectIterator() [3/3]
v8::internal::HeapObjectIterator::HeapObjectIterator (Heap * heap, SafepointScope * safepoint_scope_or_nullptr, HeapObjectsFiltering filtering) [private]
Definition at line 6836 of file heap.cc.
    : heap_(heap),
      safepoint_scope_(safepoint_scope_or_nullptr),
      space_iterator_(heap_) {
  heap_->MakeHeapIterable();
  switch (filtering) {
    case kFilterUnreachable:
      filter_ = std::make_unique<UnreachableObjectsFilter>(heap_);
      break;
    default:
      break;
  }
  // Start the iteration.
  CHECK(space_iterator_.HasNext());
  object_iterator_ = space_iterator_.Next()->GetObjectIterator(heap_);
}
References CHECK, filter_, v8::internal::Space::GetObjectIterator(), v8::internal::SpaceIterator::HasNext(), heap_, kFilterUnreachable, v8::internal::Heap::MakeHeapIterable(), v8::internal::SpaceIterator::Next(), object_iterator_, and space_iterator_.
Member Function Documentation
Next()
Tagged< HeapObject > v8::internal::HeapObjectIterator::Next ()
Definition at line 6857 of file heap.cc.
                                            {
  if (!filter_) return NextObject();
  Tagged<HeapObject> obj = NextObject();
  while (!obj.is_null() && filter_->SkipObject(obj)) obj = NextObject();
  return obj;
}
References filter_, v8::internal::Tagged< HeapObject >::is_null(), and NextObject().
Referenced by v8::internal::Snapshot::ClearReconstructableDataForSerialization(), v8::internal::anonymous_namespace{debug-coverage.cc}::CollectAndMaybeResetCounts(), v8::internal::Isolate::CollectSourcePositionsForAllBytecodeArrays(), v8::internal::Heap::CompactWeakArrayLists(), v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::DeterminePromotees(), v8::internal::Debug::DiscardAllBaselineCode(), v8::internal::Debug::DiscardBaselineCode(), v8::internal::EnumerateCompiledFunctions(), v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::Fill(), v8::internal::StatisticsExtension::GetCounters(), v8::internal::HeapProfiler::GetDetachedJSWrapperObjects(), v8::internal::Debug::InstallDebugBreakTrampoline(), v8::internal::V8FileLogger::LogAccessorCallbacks(), v8::internal::ExistingCodeLogger::LogCompiledFunctions(), v8::internal::Isolate::MaybeInitializeVectorListFromHeap(), v8::internal::CombinedHeapObjectIterator::Next(), v8::internal::Coverage::SelectMode(), and v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointers().
NextObject()
Tagged< HeapObject > v8::internal::HeapObjectIterator::NextObject () [private]
Definition at line 6865 of file heap.cc.
                                                  {
  // No iterator means we are done.
  if (!object_iterator_) return Tagged<HeapObject>();
  Tagged<HeapObject> obj = object_iterator_->Next();
  // If the current iterator has more objects we are fine.
  if (!obj.is_null()) return obj;
  // Go though the spaces looking for one that has objects.
  while (space_iterator_.HasNext()) {
    object_iterator_ = space_iterator_.Next()->GetObjectIterator(heap_);
    obj = object_iterator_->Next();
    if (!obj.is_null()) return obj;
  }
  // Done with the last space.
  object_iterator_.reset();
  return Tagged<HeapObject>();
}
References v8::internal::Space::GetObjectIterator(), v8::internal::SpaceIterator::HasNext(), heap_, v8::internal::Tagged< HeapObject >::is_null(), v8::internal::SpaceIterator::Next(), object_iterator_, space_iterator_, and v8::internal::Tagged< HeapObject >.
Referenced by Next().
Member Data Documentation
filter_
std::unique_ptr<HeapObjectsFilter> v8::internal::HeapObjectIterator::filter_ [private]
Definition at line 2713 of file heap.h.
Referenced by HeapObjectIterator(), and Next().
heap_
Heap* v8::internal::HeapObjectIterator::heap_ [private]
Definition at line 2706 of file heap.h.
Referenced by HeapObjectIterator(), and NextObject().
object_iterator_
std::unique_ptr<ObjectIterator> v8::internal::HeapObjectIterator::object_iterator_ [private]
Definition at line 2717 of file heap.h.
Referenced by HeapObjectIterator(), and NextObject().
safepoint_scope_
std::unique_ptr<SafepointScope> v8::internal::HeapObjectIterator::safepoint_scope_ [private]
Definition at line 2712 of file heap.h.
space_iterator_
SpaceIterator v8::internal::HeapObjectIterator::space_iterator_ [private]
Definition at line 2715 of file heap.h.
Referenced by HeapObjectIterator(), and NextObject().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/heap.h
/mnt/V8SourceCode/src/heap/heap.cc