v8::internal::compiler::RepresentationSelector::NodeInfo Class Reference
Public Member Functions
bool AddUse (UseInfo info)
void set_queued ()
void set_visited ()
void set_pushed ()
void reset_state ()
bool visited () const
bool queued () const
bool pushed () const
bool unvisited () const
Truncation truncation () const
void set_output (MachineRepresentation output)
MachineRepresentation representation () const
void set_feedback_type (Type type)
Type feedback_type () const
void set_weakened ()
bool weakened () const
void set_restriction_type (Type type)
Type restriction_type () const
Private Types
enum State : uint8_t { kUnvisited
, kPushed
, kVisited
, kQueued
 }
Private Attributes
State state_ = kUnvisited
MachineRepresentation representation_
Truncation truncation_ = Truncation::None()
bool weakened_ = false
Type restriction_type_ = Type::Any()
Type feedback_type_
Detailed Description
Definition at line 316 of file simplified-lowering.cc.
Member Enumeration Documentation
State
enum v8::internal::compiler::RepresentationSelector::NodeInfo::State : uint8_t [private]
Enumerator
kUnvisited
kPushed
kVisited
kQueued
Definition at line 350 of file simplified-lowering.cc.
: uint8_t { kUnvisited, kPushed, kVisited, kQueued };
Member Function Documentation
AddUse()
bool v8::internal::compiler::RepresentationSelector::NodeInfo::AddUse (UseInfo info) [inline]
Definition at line 320 of file simplified-lowering.cc.
                              {
      Truncation old_truncation = truncation_;
      truncation_ = Truncation::Generalize(truncation_, info.truncation());
      return truncation_ != old_truncation;
    }
References v8::internal::compiler::Truncation::Generalize(), v8::internal::compiler::UseInfo::truncation(), and truncation_.
Referenced by v8::internal::compiler::RepresentationSelector::EnqueueInput().
feedback_type()
Type v8::internal::compiler::RepresentationSelector::NodeInfo::feedback_type () const [inline]
Definition at line 341 of file simplified-lowering.cc.
{ return feedback_type_; }
References feedback_type_.
Referenced by v8::internal::compiler::RepresentationSelector::FeedbackTypeOf(), v8::internal::compiler::RepresentationSelector::PrintNodeFeedbackType(), v8::internal::compiler::RepresentationSelector::RunVerifyPhase(), v8::internal::compiler::RepresentationSelector::TypeOf(), and v8::internal::compiler::RepresentationSelector::UpdateFeedbackType().
pushed()
bool v8::internal::compiler::RepresentationSelector::NodeInfo::pushed () const [inline]
Definition at line 332 of file simplified-lowering.cc.
{ return state_ == kPushed; }
References kPushed, and state_.
Referenced by v8::internal::compiler::RepresentationSelector::GenerateTraversal().
queued()
bool v8::internal::compiler::RepresentationSelector::NodeInfo::queued () const [inline]
Definition at line 331 of file simplified-lowering.cc.
{ return state_ == kQueued; }
References kQueued, and state_.
Referenced by v8::internal::compiler::RepresentationSelector::EnqueueInput().
representation()
MachineRepresentation v8::internal::compiler::RepresentationSelector::NodeInfo::representation () const [inline]
Definition at line 337 of file simplified-lowering.cc.
{ return representation_; }
References representation_.
Referenced by v8::internal::compiler::RepresentationSelector::ConvertInput(), v8::internal::compiler::RepresentationSelector::IsNodeRepresentationTagged(), v8::internal::compiler::RepresentationSelector::RetypeNode(), v8::internal::compiler::RepresentationSelector::SetOutput(), v8::internal::compiler::RepresentationSelector::VisitFrameState(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitObjectState(), and v8::internal::compiler::RepresentationSelector::VisitStateValues().
reset_state()
void v8::internal::compiler::RepresentationSelector::NodeInfo::reset_state () [inline]
Definition at line 329 of file simplified-lowering.cc.
{ state_ = kUnvisited; }
References kUnvisited, and state_.
restriction_type()
Type v8::internal::compiler::RepresentationSelector::NodeInfo::restriction_type () const [inline]
Definition at line 345 of file simplified-lowering.cc.
{ return restriction_type_; }
References restriction_type_.
Referenced by v8::internal::compiler::RepresentationSelector::SetOutput(), and v8::internal::compiler::RepresentationSelector::UpdateFeedbackType().
set_feedback_type()
void v8::internal::compiler::RepresentationSelector::NodeInfo::set_feedback_type (Type type) [inline]
Definition at line 340 of file simplified-lowering.cc.
{ feedback_type_ = type; }
References feedback_type_, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::RepresentationSelector::UpdateFeedbackType(), and v8::internal::compiler::RepresentationSelector::VisitNode().
set_output()
void v8::internal::compiler::RepresentationSelector::NodeInfo::set_output (MachineRepresentation output) [inline]
Definition at line 335 of file simplified-lowering.cc.
{ representation_ = output; }
References representation_.
Referenced by v8::internal::compiler::RepresentationSelector::SetOutput().
set_pushed()
void v8::internal::compiler::RepresentationSelector::NodeInfo::set_pushed () [inline]
Definition at line 328 of file simplified-lowering.cc.
{ state_ = kPushed; }
References kPushed, and state_.
Referenced by v8::internal::compiler::RepresentationSelector::GenerateTraversal().
set_queued()
void v8::internal::compiler::RepresentationSelector::NodeInfo::set_queued () [inline]
Definition at line 326 of file simplified-lowering.cc.
{ state_ = kQueued; }
References kQueued, and state_.
Referenced by v8::internal::compiler::RepresentationSelector::EnqueueInput(), and v8::internal::compiler::RepresentationSelector::PushNodeToRevisitIfVisited().
set_restriction_type()
void v8::internal::compiler::RepresentationSelector::NodeInfo::set_restriction_type (Type type) [inline]
Definition at line 344 of file simplified-lowering.cc.
{ restriction_type_ = type; }
References restriction_type_, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::RepresentationSelector::SetOutput().
set_visited()
void v8::internal::compiler::RepresentationSelector::NodeInfo::set_visited () [inline]
Definition at line 327 of file simplified-lowering.cc.
{ state_ = kVisited; }
References kVisited, and state_.
Referenced by v8::internal::compiler::RepresentationSelector::GenerateTraversal(), v8::internal::compiler::RepresentationSelector::PropagateTruncation(), and v8::internal::compiler::RepresentationSelector::RetypeNode().
set_weakened()
void v8::internal::compiler::RepresentationSelector::NodeInfo::set_weakened () [inline]
Definition at line 342 of file simplified-lowering.cc.
{ weakened_ = true; }
References weakened_.
Referenced by v8::internal::compiler::RepresentationSelector::Weaken().
truncation()
Truncation v8::internal::compiler::RepresentationSelector::NodeInfo::truncation () const [inline]
Definition at line 334 of file simplified-lowering.cc.
{ return truncation_; }
References truncation_.
Referenced by v8::internal::compiler::RepresentationSelector::EnqueueInput(), v8::internal::compiler::RepresentationSelector::PropagateTruncation(), v8::internal::compiler::RepresentationSelector::RetypeNode(), and v8::internal::compiler::RepresentationSelector::RunLowerPhase().
unvisited()
bool v8::internal::compiler::RepresentationSelector::NodeInfo::unvisited () const [inline]
Definition at line 333 of file simplified-lowering.cc.
{ return state_ == kUnvisited; }
References kUnvisited, and state_.
Referenced by v8::internal::compiler::RepresentationSelector::EnqueueInput(), and v8::internal::compiler::RepresentationSelector::GenerateTraversal().
visited()
bool v8::internal::compiler::RepresentationSelector::NodeInfo::visited () const [inline]
Definition at line 330 of file simplified-lowering.cc.
{ return state_ == kVisited; }
References kVisited, and state_.
Referenced by v8::internal::compiler::RepresentationSelector::EnqueueInput(), and v8::internal::compiler::RepresentationSelector::PushNodeToRevisitIfVisited().
weakened()
bool v8::internal::compiler::RepresentationSelector::NodeInfo::weakened () const [inline]
Definition at line 343 of file simplified-lowering.cc.
{ return weakened_; }
References weakened_.
Member Data Documentation
feedback_type_
Type v8::internal::compiler::RepresentationSelector::NodeInfo::feedback_type_ [private]
Definition at line 358 of file simplified-lowering.cc.
Referenced by feedback_type(), and set_feedback_type().
representation_
MachineRepresentation v8::internal::compiler::RepresentationSelector::NodeInfo::representation_ [private]
Initial value:
=
        MachineRepresentation::kNone
Definition at line 352 of file simplified-lowering.cc.
Referenced by representation(), and set_output().
restriction_type_
Type v8::internal::compiler::RepresentationSelector::NodeInfo::restriction_type_ = Type::Any() [private]
Definition at line 357 of file simplified-lowering.cc.
Referenced by restriction_type(), and set_restriction_type().
state_
State v8::internal::compiler::RepresentationSelector::NodeInfo::state_ = kUnvisited [private]
Definition at line 351 of file simplified-lowering.cc.
Referenced by pushed(), queued(), reset_state(), set_pushed(), set_queued(), set_visited(), unvisited(), and visited().
truncation_
Truncation v8::internal::compiler::RepresentationSelector::NodeInfo::truncation_ = Truncation::None() [private]
Definition at line 354 of file simplified-lowering.cc.
Referenced by AddUse(), and truncation().
weakened_
bool v8::internal::compiler::RepresentationSelector::NodeInfo::weakened_ = false [private]
Definition at line 355 of file simplified-lowering.cc.
Referenced by set_weakened(), and weakened().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-lowering.cc