v8::internal::compiler::turboshaft::Typer Class Reference
#include <typer.h>
Classes
class BranchRefinements
Static Public Member Functions
static Type TypeForRepresentation (RegisterRepresentation rep)
static Type TypeForRepresentation (base::Vector< const RegisterRepresentation > reps, Zone *zone)
static Type TypeConstant (ConstantOp::Kind kind, ConstantOp::Storage value)
static Type TypeProjection (const Type &input, uint16_t idx)
static Type TypeWordBinop (Type left_type, Type right_type, WordBinopOp::Kind kind, WordRepresentation rep, Zone *zone)
static Type TypeWord32Add (const Type &lhs, const Type &rhs, Zone *zone)
static Type TypeWord32Sub (const Type &lhs, const Type &rhs, Zone *zone)
static Type TypeWord64Add (const Type &lhs, const Type &rhs, Zone *zone)
static Type TypeWord64Sub (const Type &lhs, const Type &rhs, Zone *zone)
static Type TypeFloatBinop (Type left_type, Type right_type, FloatBinopOp::Kind kind, FloatRepresentation rep, Zone *zone)
static Type TypeOverflowCheckedBinop (const Type &left_type, const Type &right_type, OverflowCheckedBinopOp::Kind kind, WordRepresentation rep, Zone *zone)
static Type TypeWord32OverflowCheckedAdd (const Type &lhs, const Type &rhs, Zone *zone)
static Type TypeComparison (const Type &lhs, const Type &rhs, RegisterRepresentation rep, ComparisonOp::Kind kind, Zone *zone)
static Type TypeWord32Comparison (const Type &lhs, const Type &rhs, ComparisonOp::Kind kind, Zone *zone)
static Type TypeWord64Comparison (const Type &lhs, const Type &rhs, ComparisonOp::Kind kind, Zone *zone)
static Type TypeFloat32Comparison (const Type &lhs, const Type &rhs, ComparisonOp::Kind kind, Zone *zone)
static Type TypeFloat64Comparison (const Type &lhs, const Type &rhs, ComparisonOp::Kind kind, Zone *zone)
static Word64Type ExtendWord32ToWord64 (const Word32Type &t, Zone *zone)
static Word32Type TruncateWord32Input (const Type &input, bool implicit_word64_narrowing, Zone *zone)
static bool InputIs (const Type &input, Type::Kind expected)
static bool allow_invalid_inputs ()
Detailed Description
Definition at line 1142 of file typer.h.
Member Function Documentation
allow_invalid_inputs()
static bool v8::internal::compiler::turboshaft::Typer::allow_invalid_inputs () [inline], [static]
Definition at line 1619 of file typer.h.
{ return true; }
Referenced by InputIs(), and TruncateWord32Input().
ExtendWord32ToWord64()
static Word64Type v8::internal::compiler::turboshaft::Typer::ExtendWord32ToWord64 (const Word32Type & t, Zone * zone) [inline], [static]
Definition at line 1507 of file typer.h.
                                                                          {
    // We cannot infer much, but the lower bound of the word32 is also the lower
    // bound of the word64 type.
    if (t.is_wrapping()) return Word64Type::Any();
    return Word64Type::Range(static_cast<uint64_t>(t.unsigned_min()),
                             std::numeric_limits<uint64_t>::max(), zone);
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Any(), v8::internal::compiler::turboshaft::WordType< Bits >::is_wrapping(), v8::internal::compiler::turboshaft::WordType< Bits >::Range(), and v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_min().
Referenced by v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineWord32Type().
InputIs()
static bool v8::internal::compiler::turboshaft::Typer::InputIs (const Type & input, Type::Kind expected) [inline], [static]
Definition at line 1602 of file typer.h.
                                                            {
    if (input.IsInvalid()) {
      if (allow_invalid_inputs()) return false;
    } else if (input.kind() == expected) {
      return true;
    } else if (input.IsAny()) {
      if (allow_invalid_inputs()) return false;
    }
    std::stringstream s;
    s << expected;
    FATAL("Missing proper type (%s). Type is: %s", s.str().c_str(),
          input.ToString().c_str());
  }
References allow_invalid_inputs(), FATAL, v8::internal::compiler::turboshaft::Type::IsAny(), v8::internal::compiler::turboshaft::Type::IsInvalid(), v8::internal::compiler::turboshaft::Type::kind(), and v8::internal::compiler::turboshaft::Type::ToString().
Referenced by TypeWord64Add(), and TypeWord64Sub().
TruncateWord32Input()
static Word32Type v8::internal::compiler::turboshaft::Typer::TruncateWord32Input (const Type & input, bool implicit_word64_narrowing, Zone * zone) [inline], [static]
Definition at line 1515 of file typer.h.
                                                    {
    DCHECK(!input.IsInvalid());
    DCHECK(!input.IsNone());
    if (input.IsAny()) {
      if (allow_invalid_inputs()) return Word32Type::Any();
    } else if (input.IsWord32()) {
      return input.AsWord32();
    } else if (input.IsWord64() && implicit_word64_narrowing) {
      // The input is implicitly converted to word32.
      const auto& w64 = input.AsWord64();
      if (w64.is_set()) {
        WordOperationTyper<32>::ElementsVector elements;
        for (uint64_t e : w64.set_elements()) {
          elements.push_back(static_cast<uint32_t>(e));
        }
        return WordOperationTyper<32>::FromElements(std::move(elements), zone);
      }
      if (w64.is_any() || w64.is_wrapping()) return Word32Type::Any();
      if (w64.range_to() <= std::numeric_limits<uint32_t>::max()) {
        DCHECK_LE(w64.range_from(), std::numeric_limits<uint32_t>::max());
        return Word32Type::Range(static_cast<uint32_t>(w64.range_from()),
                                 static_cast<uint32_t>(w64.range_to()), zone);
      }
      // TODO(nicohartmann@): Might compute a more precise range here.
      return Word32Type::Any();
    }
    FATAL("Missing proper type for TruncateWord32Input. Type is: %s",
          input.ToString().c_str());
  }
References allow_invalid_inputs(), v8::internal::compiler::turboshaft::WordType< Bits >::Any(), v8::internal::compiler::turboshaft::Type::AsWord32(), v8::internal::compiler::turboshaft::Type::AsWord64(), v8::internal::DCHECK(), DCHECK_LE, FATAL, v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements(), v8::internal::compiler::turboshaft::Type::IsAny(), v8::internal::compiler::turboshaft::Type::IsInvalid(), v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::Type::IsWord32(), v8::internal::compiler::turboshaft::Type::IsWord64(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::turboshaft::WordType< Bits >::Range(), and v8::internal::compiler::turboshaft::Type::ToString().
Referenced by v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ComputeTypeForPhi(), v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineTypes(), TypeWord32Add(), TypeWord32Comparison(), TypeWord32OverflowCheckedAdd(), and TypeWord32Sub().
TypeComparison()
static Type v8::internal::compiler::turboshaft::Typer::TypeComparison (const Type & lhs, const Type & rhs, RegisterRepresentation rep, ComparisonOp::Kind kind, Zone * zone) [inline], [static]
Definition at line 1409 of file typer.h.
                                                                {
    switch (rep.value()) {
      case RegisterRepresentation::Word32():
        return TypeWord32Comparison(lhs, rhs, kind, zone);
      case RegisterRepresentation::Word64():
        return TypeWord64Comparison(lhs, rhs, kind, zone);
      case RegisterRepresentation::Float32():
        return TypeFloat32Comparison(lhs, rhs, kind, zone);
      case RegisterRepresentation::Float64():
        return TypeFloat64Comparison(lhs, rhs, kind, zone);
      case RegisterRepresentation::Tagged():
      case RegisterRepresentation::Compressed():
      case RegisterRepresentation::Simd128():
      case RegisterRepresentation::Simd256():
        if (lhs.IsNone() || rhs.IsNone()) return Type::None();
        // TODO(nicohartmann@): Support those cases.
        return Word32Type::Set({0, 1}, zone);
    }
  }
References v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::turboshaft::WordType< Bits >::Set(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd128(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd256(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), TypeFloat32Comparison(), TypeFloat64Comparison(), TypeWord32Comparison(), TypeWord64Comparison(), v8::internal::compiler::turboshaft::RegisterRepresentation::value(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Comparison(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessComparison().
TypeConstant()
static Type v8::internal::compiler::turboshaft::Typer::TypeConstant (ConstantOp::Kind kind, ConstantOp::Storage value) [inline], [static]
Definition at line 1173 of file typer.h.
                                                                         {
    switch (kind) {
      case ConstantOp::Kind::kFloat32:
        if (value.float32.is_nan()) return Float32Type::NaN();
        if (IsMinusZero(value.float32.get_scalar()))
          return Float32Type::MinusZero();
        return Float32Type::Constant(value.float32.get_scalar());
      case ConstantOp::Kind::kFloat64:
        if (value.float64.is_nan()) return Float64Type::NaN();
        if (IsMinusZero(value.float64.get_scalar()))
          return Float64Type::MinusZero();
        return Float64Type::Constant(value.float64.get_scalar());
      case ConstantOp::Kind::kWord32:
        return Word32Type::Constant(static_cast<uint32_t>(value.integral));
      case ConstantOp::Kind::kWord64:
        return Word64Type::Constant(static_cast<uint64_t>(value.integral));
      default:
        // TODO(nicohartmann@): Support remaining {kind}s.
        return Type::Any();
    }
  }
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::turboshaft::FloatType< Bits >::Constant(), v8::internal::compiler::turboshaft::WordType< Bits >::Constant(), v8::internal::IsMinusZero(), v8::internal::compiler::turboshaft::ConstantOp::kFloat32, v8::internal::compiler::turboshaft::ConstantOp::kFloat64, v8::internal::compiler::turboshaft::ConstantOp::kWord32, v8::internal::compiler::turboshaft::ConstantOp::kWord64, v8::internal::compiler::turboshaft::FloatType< Bits >::MinusZero(), v8::internal::compiler::turboshaft::FloatType< Bits >::NaN(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Constant(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessConstant().
TypeFloat32Comparison()
static Type v8::internal::compiler::turboshaft::Typer::TypeFloat32Comparison (const Type & lhs, const Type & rhs, ComparisonOp::Kind kind, Zone * zone) [inline], [static]
Definition at line 1469 of file typer.h.
                                                                       {
    if (lhs.IsNone() || rhs.IsNone()) return Type::None();
    switch (kind) {
      case ComparisonOp::Kind::kEqual:
        // TODO(nicohartmann@): Support this.
        return Word32Type::Set({0, 1}, zone);
      case ComparisonOp::Kind::kSignedLessThan:
        return FloatOperationTyper<32>::LessThan(lhs.AsFloat32(),
                                                 rhs.AsFloat32(), zone);
      case ComparisonOp::Kind::kSignedLessThanOrEqual:
        return FloatOperationTyper<32>::LessThanOrEqual(lhs.AsFloat32(),
                                                        rhs.AsFloat32(), zone);
      case ComparisonOp::Kind::kUnsignedLessThan:
      case ComparisonOp::Kind::kUnsignedLessThanOrEqual:
        UNREACHABLE();
    }
  }
References v8::internal::compiler::turboshaft::Type::AsFloat32(), v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::ComparisonOp::kEqual, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThanOrEqual, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThanOrEqual, v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThan(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThanOrEqual(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::turboshaft::WordType< Bits >::Set(), and v8::internal::UNREACHABLE().
Referenced by TypeComparison().
TypeFloat64Comparison()
static Type v8::internal::compiler::turboshaft::Typer::TypeFloat64Comparison (const Type & lhs, const Type & rhs, ComparisonOp::Kind kind, Zone * zone) [inline], [static]
Definition at line 1488 of file typer.h.
                                                                       {
    if (lhs.IsNone() || rhs.IsNone()) return Type::None();
    switch (kind) {
      case ComparisonOp::Kind::kEqual:
        // TODO(nicohartmann@): Support this.
        return Word32Type::Set({0, 1}, zone);
      case ComparisonOp::Kind::kSignedLessThan:
        return FloatOperationTyper<64>::LessThan(lhs.AsFloat64(),
                                                 rhs.AsFloat64(), zone);
      case ComparisonOp::Kind::kSignedLessThanOrEqual:
        return FloatOperationTyper<64>::LessThanOrEqual(lhs.AsFloat64(),
                                                        rhs.AsFloat64(), zone);
      case ComparisonOp::Kind::kUnsignedLessThan:
      case ComparisonOp::Kind::kUnsignedLessThanOrEqual:
        UNREACHABLE();
    }
  }
References v8::internal::compiler::turboshaft::Type::AsFloat64(), v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::ComparisonOp::kEqual, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThanOrEqual, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThanOrEqual, v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThan(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThanOrEqual(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::turboshaft::WordType< Bits >::Set(), and v8::internal::UNREACHABLE().
Referenced by TypeComparison().
TypeFloatBinop()
static Type v8::internal::compiler::turboshaft::Typer::TypeFloatBinop (Type left_type, Type right_type, FloatBinopOp::Kind kind, FloatRepresentation rep, Zone * zone) [inline], [static]
Definition at line 1272 of file typer.h.
                                         {
    DCHECK(!left_type.IsInvalid());
    DCHECK(!right_type.IsInvalid());
#define FLOAT_BINOP(op, bits) \
  case FloatBinopOp::Kind::k##op: \
    return TypeFloat##bits##op(left_type, right_type, zone);
    if (rep == FloatRepresentation::Float32()) {
      switch (kind) {
        FLOAT_BINOP(Add, 32)
        FLOAT_BINOP(Sub, 32)
        FLOAT_BINOP(Mul, 32)
        FLOAT_BINOP(Div, 32)
        FLOAT_BINOP(Mod, 32)
        FLOAT_BINOP(Min, 32)
        FLOAT_BINOP(Max, 32)
        FLOAT_BINOP(Power, 32)
        FLOAT_BINOP(Atan2, 32)
      }
    } else {
      DCHECK_EQ(rep, FloatRepresentation::Float64());
      switch (kind) {
        FLOAT_BINOP(Add, 64)
        FLOAT_BINOP(Sub, 64)
        FLOAT_BINOP(Mul, 64)
        FLOAT_BINOP(Div, 64)
        FLOAT_BINOP(Mod, 64)
        FLOAT_BINOP(Min, 64)
        FLOAT_BINOP(Max, 64)
        FLOAT_BINOP(Power, 64)
        FLOAT_BINOP(Atan2, 64)
      }
    }
#undef FLOAT_BINOP
  }
References v8::bigint::Add(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::FloatRepresentation::Float32(), v8::internal::compiler::turboshaft::FloatRepresentation::Float64(), FLOAT_BINOP, v8::internal::compiler::turboshaft::Type::IsInvalid(), and v8::internal::wasm::liftoff::Sub().
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::FloatBinop(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessFloatBinop().
TypeForRepresentation() [1/2]
static Type v8::internal::compiler::turboshaft::Typer::TypeForRepresentation (base::Vector< const RegisterRepresentation > reps, Zone * zone) [inline], [static]
Definition at line 1164 of file typer.h.
                                                                 {
    DCHECK_LT(0, reps.size());
    if (reps.size() == 1) return TypeForRepresentation(reps[0]);
    base::SmallVector<Type, 4> tuple_types;
    for (auto rep : reps) tuple_types.push_back(TypeForRepresentation(rep));
    return TupleType::Tuple(base::VectorOf(tuple_types), zone);
  }
References DCHECK_LT, v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::base::Vector< T >::size(), v8::internal::compiler::turboshaft::TupleType::Tuple(), TypeForRepresentation(), and v8::base::VectorOf().
TypeForRepresentation() [2/2]
static Type v8::internal::compiler::turboshaft::Typer::TypeForRepresentation (RegisterRepresentation rep) [inline], [static]
Definition at line 1144 of file typer.h.
                                                                {
    switch (rep.value()) {
      case RegisterRepresentation::Word32():
        return Word32Type::Any();
      case RegisterRepresentation::Word64():
        return Word64Type::Any();
      case RegisterRepresentation::Float32():
        return Float32Type::Any();
      case RegisterRepresentation::Float64():
        return Float64Type::Any();
      case RegisterRepresentation::Tagged():
      case RegisterRepresentation::Compressed():
      case RegisterRepresentation::Simd128():
      case RegisterRepresentation::Simd256():
        // TODO(nicohartmann@): Support these representations.
        return Type::Any();
    }
  }
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::turboshaft::WordType< Bits >::Any(), v8::internal::compiler::turboshaft::RegisterRepresentation::Compressed(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd128(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd256(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::RegisterRepresentation::value(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Referenced by v8::internal::compiler::turboshaft::TypeInferenceAnalysis::GetType(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetType(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::PendingLoopPhi(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessProjection(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceOperation(), and TypeForRepresentation().
TypeOverflowCheckedBinop()
static Type v8::internal::compiler::turboshaft::Typer::TypeOverflowCheckedBinop (const Type & left_type, const Type & right_type, OverflowCheckedBinopOp::Kind kind, WordRepresentation rep, Zone * zone) [inline], [static]
Definition at line 1347 of file typer.h.
                                                                           {
    DCHECK(!left_type.IsInvalid());
    DCHECK(!right_type.IsInvalid());
    if (rep == WordRepresentation::Word32()) {
      switch (kind) {
        case OverflowCheckedBinopOp::Kind::kSignedAdd:
          return TypeWord32OverflowCheckedAdd(left_type, right_type, zone);
        case OverflowCheckedBinopOp::Kind::kSignedSub:
        case OverflowCheckedBinopOp::Kind::kSignedMul:
          // TODO(nicohartmann@): Support these.
          return TupleType::Tuple(Word32Type::Any(),
                                  Word32Type::Set({0, 1}, zone), zone);
      }
    } else {
      DCHECK_EQ(rep, WordRepresentation::Word64());
      switch (kind) {
        case OverflowCheckedBinopOp::Kind::kSignedAdd:
        case OverflowCheckedBinopOp::Kind::kSignedSub:
        case OverflowCheckedBinopOp::Kind::kSignedMul:
          // TODO(nicohartmann@): Support these.
          return TupleType::Tuple(Word64Type::Any(),
                                  Word32Type::Set({0, 1}, zone), zone);
      }
    }
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Any(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::Type::IsInvalid(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kSignedAdd, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kSignedMul, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kSignedSub, v8::internal::compiler::turboshaft::WordType< Bits >::Set(), v8::internal::compiler::turboshaft::TupleType::Tuple(), TypeWord32OverflowCheckedAdd(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::OverflowCheckedBinop(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessOverflowCheckedBinop().
TypeProjection()
static Type v8::internal::compiler::turboshaft::Typer::TypeProjection (const Type & input, uint16_t idx) [inline], [static]
Definition at line 1195 of file typer.h.
                                                              {
    if (input.IsNone()) return Type::None();
    if (!input.IsTuple()) return Type::Any();
    const TupleType& tuple = input.AsTuple();
    DCHECK_LT(idx, tuple.size());
    return tuple.element(idx);
  }
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::turboshaft::Type::AsTuple(), DCHECK_LT, v8::internal::compiler::turboshaft::TupleType::element(), v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::Type::IsTuple(), v8::internal::compiler::turboshaft::Type::None(), and v8::internal::compiler::turboshaft::TupleType::size().
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Projection().
TypeWord32Add()
static Type v8::internal::compiler::turboshaft::Typer::TypeWord32Add (const Type & lhs, const Type & rhs, Zone * zone) [inline], [static]
Definition at line 1233 of file typer.h.
                                                                          {
    if (lhs.IsNone() || rhs.IsNone()) return Type::None();
    auto l = TruncateWord32Input(lhs, true, zone);
    auto r = TruncateWord32Input(rhs, true, zone);
    return WordOperationTyper<32>::Add(l, r, zone);
  }
References v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::Type::None(), and TruncateWord32Input().
Referenced by TypeWordBinop().
TypeWord32Comparison()
static Type v8::internal::compiler::turboshaft::Typer::TypeWord32Comparison (const Type & lhs, const Type & rhs, ComparisonOp::Kind kind, Zone * zone) [inline], [static]
Definition at line 1431 of file typer.h.
                                                                      {
    if (lhs.IsNone() || rhs.IsNone()) return Type::None();
    auto l = TruncateWord32Input(lhs, true, zone);
    auto r = TruncateWord32Input(rhs, true, zone);
    switch (kind) {
      case ComparisonOp::Kind::kEqual:
      case ComparisonOp::Kind::kSignedLessThan:
      case ComparisonOp::Kind::kSignedLessThanOrEqual:
        // TODO(nicohartmann@): Support this.
        return Word32Type::Set({0, 1}, zone);
      case ComparisonOp::Kind::kUnsignedLessThan:
        return WordOperationTyper<32>::UnsignedLessThan(l, r, zone);
      case ComparisonOp::Kind::kUnsignedLessThanOrEqual:
        return WordOperationTyper<32>::UnsignedLessThanOrEqual(l, r, zone);
    }
    UNREACHABLE();
  }
References v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::ComparisonOp::kEqual, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThanOrEqual, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThanOrEqual, v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::turboshaft::WordType< Bits >::Set(), TruncateWord32Input(), v8::internal::UNREACHABLE(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::UnsignedLessThan(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::UnsignedLessThanOrEqual().
Referenced by TypeComparison().
TypeWord32OverflowCheckedAdd()
static Type v8::internal::compiler::turboshaft::Typer::TypeWord32OverflowCheckedAdd (const Type & lhs, const Type & rhs, Zone * zone) [inline], [static]
Definition at line 1377 of file typer.h.
                                                       {
    if (lhs.IsNone() || rhs.IsNone()) return Type::None();
    auto l = TruncateWord32Input(lhs, true, zone);
    auto r = TruncateWord32Input(rhs, true, zone);
    auto value = WordOperationTyper<32>::Add(l, r, zone);
    // We check for signed overflow and if the topmost bits of both opperands
    // are 0, we know that the result cannot overflow.
    if ((0xC0000000 & l.unsigned_max()) == 0 &&
        (0xC0000000 & r.unsigned_max()) == 0) {
      // Cannot overflow.
      return TupleType::Tuple(value, Word32Type::Constant(0), zone);
    }
    // Special case for two constant inputs to figure out the overflow.
    if (l.is_constant() && r.is_constant()) {
      constexpr uint32_t msb_mask = 0x80000000;
      DCHECK(value.is_constant());
      uint32_t l_msb = (*l.try_get_constant()) & msb_mask;
      uint32_t r_msb = (*r.try_get_constant()) & msb_mask;
      if (l_msb != r_msb) {
        // Different sign bits can never lead to an overflow.
        return TupleType::Tuple(value, Word32Type::Constant(0), zone);
      }
      uint32_t value_msb = (*value.try_get_constant()) & msb_mask;
      const uint32_t overflow = value_msb == l_msb ? 0 : 1;
      return TupleType::Tuple(value, Word32Type::Constant(overflow), zone);
    }
    // Otherwise we accept some imprecision.
    return TupleType::Tuple(value, Word32Type::Set({0, 1}, zone), zone);
  }
References v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::WordType< Bits >::Constant(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::Type::None(), v8::internal::overflow, v8::internal::compiler::turboshaft::WordType< Bits >::Set(), TruncateWord32Input(), v8::internal::compiler::turboshaft::TupleType::Tuple(), and v8::internal::value.
Referenced by TypeOverflowCheckedBinop().
TypeWord32Sub()
static Type v8::internal::compiler::turboshaft::Typer::TypeWord32Sub (const Type & lhs, const Type & rhs, Zone * zone) [inline], [static]
Definition at line 1240 of file typer.h.
                                                                          {
    if (lhs.IsNone() || rhs.IsNone()) return Type::None();
    auto l = TruncateWord32Input(lhs, true, zone);
    auto r = TruncateWord32Input(rhs, true, zone);
    return WordOperationTyper<32>::Subtract(l, r, zone);
  }
References v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Subtract(), and TruncateWord32Input().
Referenced by TypeWordBinop().
TypeWord64Add()
static Type v8::internal::compiler::turboshaft::Typer::TypeWord64Add (const Type & lhs, const Type & rhs, Zone * zone) [inline], [static]
Definition at line 1247 of file typer.h.
                                                                          {
    if (lhs.IsNone() || rhs.IsNone()) return Type::None();
    if (!InputIs(lhs, Type::Kind::kWord64) ||
        !InputIs(rhs, Type::Kind::kWord64)) {
      return Word64Type::Any();
    }
    const auto& l = lhs.AsWord64();
    const auto& r = rhs.AsWord64();
    return WordOperationTyper<64>::Add(l, r, zone);
  }
References v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::WordType< Bits >::Any(), v8::internal::compiler::turboshaft::Type::AsWord64(), InputIs(), v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::Type::kWord64, v8::internal::compiler::turboshaft::l, and v8::internal::compiler::turboshaft::Type::None().
Referenced by TypeWordBinop().
TypeWord64Comparison()
static Type v8::internal::compiler::turboshaft::Typer::TypeWord64Comparison (const Type & lhs, const Type & rhs, ComparisonOp::Kind kind, Zone * zone) [inline], [static]
Definition at line 1450 of file typer.h.
                                                                      {
    if (lhs.IsNone() || rhs.IsNone()) return Type::None();
    switch (kind) {
      case ComparisonOp::Kind::kEqual:
      case ComparisonOp::Kind::kSignedLessThan:
      case ComparisonOp::Kind::kSignedLessThanOrEqual:
        // TODO(nicohartmann@): Support this.
        return Word32Type::Set({0, 1}, zone);
      case ComparisonOp::Kind::kUnsignedLessThan:
        return WordOperationTyper<64>::UnsignedLessThan(lhs.AsWord64(),
                                                        rhs.AsWord64(), zone);
      case ComparisonOp::Kind::kUnsignedLessThanOrEqual:
        return WordOperationTyper<64>::UnsignedLessThanOrEqual(
            lhs.AsWord64(), rhs.AsWord64(), zone);
    }
    UNREACHABLE();
  }
References v8::internal::compiler::turboshaft::Type::AsWord64(), v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::ComparisonOp::kEqual, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThanOrEqual, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThanOrEqual, v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::turboshaft::WordType< Bits >::Set(), v8::internal::UNREACHABLE(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::UnsignedLessThan(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::UnsignedLessThanOrEqual().
Referenced by TypeComparison().
TypeWord64Sub()
static Type v8::internal::compiler::turboshaft::Typer::TypeWord64Sub (const Type & lhs, const Type & rhs, Zone * zone) [inline], [static]
Definition at line 1259 of file typer.h.
                                                                          {
    if (lhs.IsNone() || rhs.IsNone()) return Type::None();
    if (!InputIs(lhs, Type::Kind::kWord64) ||
        !InputIs(rhs, Type::Kind::kWord64)) {
      return Word64Type::Any();
    }
    const auto& l = lhs.AsWord64();
    const auto& r = rhs.AsWord64();
    return WordOperationTyper<64>::Subtract(l, r, zone);
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Any(), v8::internal::compiler::turboshaft::Type::AsWord64(), InputIs(), v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::Type::kWord64, v8::internal::compiler::turboshaft::l, v8::internal::compiler::turboshaft::Type::None(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Subtract().
Referenced by TypeWordBinop().
TypeWordBinop()
static Type v8::internal::compiler::turboshaft::Typer::TypeWordBinop (Type left_type, Type right_type, WordBinopOp::Kind kind, WordRepresentation rep, Zone * zone) [inline], [static]
Definition at line 1203 of file typer.h.
                                        {
    DCHECK(!left_type.IsInvalid());
    DCHECK(!right_type.IsInvalid());
    if (rep == WordRepresentation::Word32()) {
      switch (kind) {
        case WordBinopOp::Kind::kAdd:
          return TypeWord32Add(left_type, right_type, zone);
        case WordBinopOp::Kind::kSub:
          return TypeWord32Sub(left_type, right_type, zone);
        default:
          // TODO(nicohartmann@): Support remaining {kind}s.
          return Word32Type::Any();
      }
    } else {
      DCHECK_EQ(rep, WordRepresentation::Word64());
      switch (kind) {
        case WordBinopOp::Kind::kAdd:
          return TypeWord64Add(left_type, right_type, zone);
        case WordBinopOp::Kind::kSub:
          return TypeWord64Sub(left_type, right_type, zone);
        default:
          // TODO(nicohartmann@): Support remaining {kind}s.
          return Word64Type::Any();
      }
    }
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Any(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::Type::IsInvalid(), v8::internal::compiler::turboshaft::WordBinopOp::kAdd, v8::internal::compiler::turboshaft::WordBinopOp::kSub, TypeWord32Add(), TypeWord32Sub(), TypeWord64Add(), TypeWord64Sub(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Referenced by v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessWordBinop(), and v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::WordBinop().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/typer.h