v8::internal::FreeListManyCached Class Reference
#include <free-list.h>
Public Member Functions
FreeListManyCached ()
V8_WARN_UNUSED_RESULT Tagged< FreeSpace > Allocate (size_t size_in_bytes, size_t *node_size, AllocationOrigin origin) override
size_t Free (const WritableFreeSpace &free_space, FreeMode mode) override
void Reset () override
void ResetForNonBlackAllocatedPages () override
bool AddCategory (FreeListCategory *category) override
void RemoveCategory (FreeListCategory *category) override
Protected Member Functions
void UpdateCacheAfterAddition (FreeListCategoryType cat)
void UpdateCacheAfterRemoval (FreeListCategoryType cat)
Protected Attributes
int next_nonempty_category [kNumberOfCategories+1]
Private Member Functions
void ResetCache ()
Additional Inherited Members
Detailed Description
Definition at line 354 of file free-list.h.
Constructor & Destructor Documentation
FreeListManyCached()
v8::internal::FreeListManyCached::FreeListManyCached ()
Definition at line 250 of file free-list.cc.
{ ResetCache(); }
References ResetCache().
Member Function Documentation
AddCategory()
bool v8::internal::FreeListManyCached::AddCategory (FreeListCategory * category) [override], [virtual]
Reimplemented from v8::internal::FreeList.
Definition at line 262 of file free-list.cc.
                                                               {
  bool was_added = FreeList::AddCategory(category);
  // Updating cache
  if (was_added) {
    UpdateCacheAfterAddition(category->type_);
  }
#ifdef DEBUG
  CheckCacheIntegrity();
#endif
  return was_added;
}
References v8::internal::FreeList::AddCategory(), v8::internal::FreeListCategory::type_, and UpdateCacheAfterAddition().
Allocate()
Tagged< FreeSpace > v8::internal::FreeListManyCached::Allocate (size_t size_in_bytes, size_t * node_size, AllocationOrigin origin) [override], [virtual]
Reimplemented from v8::internal::FreeListMany.
Reimplemented in v8::internal::FreeListManyCachedOrigin, and v8::internal::FreeListManyCachedFastPathBase.
Definition at line 323 of file free-list.cc.
                                                                        {
  USE(origin);
  DCHECK_GE(kMaxBlockSize, size_in_bytes);
  Tagged<FreeSpace> node;
  FreeListCategoryType type = SelectFreeListCategoryType(size_in_bytes);
  type = next_nonempty_category[type];
  for (; type < last_category_; type = next_nonempty_category[type + 1]) {
    node = TryFindNodeIn(type, size_in_bytes, node_size);
    if (!node.is_null()) break;
  }
  if (node.is_null()) {
    // Searching each element of the last category.
    type = last_category_;
    node = SearchForNodeInList(type, size_in_bytes, node_size);
  }
  // Updating cache
  if (!node.is_null() && categories_[type] == nullptr) {
    UpdateCacheAfterRemoval(type);
  }
#ifdef DEBUG
  CheckCacheIntegrity();
#endif
  if (!node.is_null()) {
    PageMetadata::FromHeapObject(node)->IncreaseAllocatedBytes(*node_size);
  }
  VerifyAvailable();
  return node;
}
References v8::internal::FreeList::categories_, DCHECK_GE, v8::internal::PageMetadata::FromHeapObject(), v8::internal::MemoryChunkMetadata::IncreaseAllocatedBytes(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::FreeListMany::kMaxBlockSize, v8::internal::FreeList::last_category_, next_nonempty_category, v8::internal::FreeList::SearchForNodeInList(), v8::internal::FreeListMany::SelectFreeListCategoryType(), v8::internal::FreeList::TryFindNodeIn(), v8::internal::tracing::type, UpdateCacheAfterRemoval(), USE, and v8::internal::FreeList::VerifyAvailable().
Referenced by v8::internal::FreeListManyCachedOrigin::Allocate().
Free()
size_t v8::internal::FreeListManyCached::Free (const WritableFreeSpace & free_space, FreeMode mode) [override], [virtual]
Reimplemented from v8::internal::FreeList.
Definition at line 291 of file free-list.cc.
                                               {
  Address start = free_space.Address();
  size_t size_in_bytes = free_space.Size();
  PageMetadata* page = PageMetadata::FromAddress(start);
  page->DecreaseAllocatedBytes(size_in_bytes);
  // Blocks have to be a minimum size to hold free list items.
  if (size_in_bytes < min_block_size_) {
    page->add_wasted_memory(size_in_bytes);
    return size_in_bytes;
  }
  // Insert other blocks at the head of a free list of the appropriate
  // magnitude.
  FreeListCategoryType type = SelectFreeListCategoryType(size_in_bytes);
  page->free_list_category(type)->Free(free_space, mode, this);
  // Updating cache
  if (mode == kLinkCategory) {
    UpdateCacheAfterAddition(type);
#ifdef DEBUG
    CheckCacheIntegrity();
#endif
  }
  DCHECK_EQ(page->AvailableInFreeList(),
            page->AvailableInFreeListFromAllocatedBytes());
  return 0;
}
References v8::internal::MemoryChunkMetadata::add_wasted_memory(), v8::internal::WritableFreeSpace::Address(), v8::internal::PageMetadata::AvailableInFreeList(), v8::internal::PageMetadata::AvailableInFreeListFromAllocatedBytes(), DCHECK_EQ, v8::internal::MemoryChunkMetadata::DecreaseAllocatedBytes(), v8::internal::FreeListCategory::Free(), v8::internal::PageMetadata::free_list_category(), v8::internal::PageMetadata::FromAddress(), v8::internal::kLinkCategory, v8::internal::FreeList::min_block_size_, mode(), v8::internal::FreeListMany::SelectFreeListCategoryType(), v8::internal::WritableFreeSpace::Size(), v8::internal::tracing::type, and UpdateCacheAfterAddition().
RemoveCategory()
void v8::internal::FreeListManyCached::RemoveCategory (FreeListCategory * category) [override], [virtual]
Reimplemented from v8::internal::FreeList.
Definition at line 277 of file free-list.cc.
                                                                  {
  FreeList::RemoveCategory(category);
  // Updating cache
  int type = category->type_;
  if (categories_[type] == nullptr) {
    UpdateCacheAfterRemoval(type);
  }
#ifdef DEBUG
  CheckCacheIntegrity();
#endif
}
References v8::internal::FreeList::categories_, v8::internal::FreeList::RemoveCategory(), v8::internal::tracing::type, v8::internal::FreeListCategory::type_, and UpdateCacheAfterRemoval().
Reset()
void v8::internal::FreeListManyCached::Reset () [override], [virtual]
Reimplemented from v8::internal::FreeList.
Definition at line 252 of file free-list.cc.
                               {
  ResetCache();
  FreeListMany::Reset();
}
References v8::internal::FreeList::Reset(), and ResetCache().
ResetCache()
void v8::internal::FreeListManyCached::ResetCache () [inline], [private]
Definition at line 405 of file free-list.h.
                    {
    for (int i = 0; i < kNumberOfCategories; i++) {
      next_nonempty_category[i] = kNumberOfCategories;
    }
    // Setting the after-last element as well, as explained in the cache's
    // declaration.
    next_nonempty_category[kNumberOfCategories] = kNumberOfCategories;
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by FreeListManyCached(), Reset(), and ResetForNonBlackAllocatedPages().
ResetForNonBlackAllocatedPages()
void v8::internal::FreeListManyCached::ResetForNonBlackAllocatedPages () [override], [virtual]
Reimplemented from v8::internal::FreeList.
Definition at line 257 of file free-list.cc.
                                                        {
  ResetCache();
  FreeListMany::ResetForNonBlackAllocatedPages();
}
References ResetCache(), and v8::internal::FreeList::ResetForNonBlackAllocatedPages().
UpdateCacheAfterAddition()
void v8::internal::FreeListManyCached::UpdateCacheAfterAddition (FreeListCategoryType cat) [inline], [protected]
Definition at line 372 of file free-list.h.
                                                          {
    for (int i = cat; i >= kFirstCategory && next_nonempty_category[i] > cat;
         i--) {
      next_nonempty_category[i] = cat;
    }
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::kFirstCategory.
Referenced by AddCategory(), and Free().
UpdateCacheAfterRemoval()
void v8::internal::FreeListManyCached::UpdateCacheAfterRemoval (FreeListCategoryType cat) [inline], [protected]
Definition at line 380 of file free-list.h.
                                                         {
    for (int i = cat; i >= kFirstCategory && next_nonempty_category[i] == cat;
         i--) {
      next_nonempty_category[i] = next_nonempty_category[cat + 1];
    }
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::kFirstCategory.
Referenced by Allocate(), v8::internal::FreeListManyCachedFastPathBase::Allocate(), and RemoveCategory().
Member Data Documentation
next_nonempty_category
int v8::internal::FreeListManyCached::next_nonempty_category[kNumberOfCategories+1] [protected]
Definition at line 402 of file free-list.h.
Referenced by Allocate(), and v8::internal::FreeListManyCachedFastPathBase::Allocate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/free-list.h
/mnt/V8SourceCode/src/heap/free-list.cc