v8::internal::anonymous_namespace{marking.cc}::CellPrinter Class Reference
Public Member Functions
CellPrinter ()=default
void Print (size_t pos, MarkBit::CellType cell)
void Flush ()
Static Public Member Functions
static bool IsSeq (MarkBit::CellType cell)
Private Attributes
size_t seq_start = 0
MarkBit::CellType seq_type = 0
size_t seq_length = 0
Detailed Description
Definition at line 79 of file marking.cc.
Constructor & Destructor Documentation
CellPrinter()
v8::internal::anonymous_namespace{marking.cc}::CellPrinter::CellPrinter () [default]
Member Function Documentation
Flush()
void v8::internal::anonymous_namespace{marking.cc}::CellPrinter::Flush () [inline]
Definition at line 103 of file marking.cc.
               {
    if (seq_length > 0) {
      PrintF("%zu: %dx%zu\n", seq_start, seq_type == 0 ? 0 : 1,
             seq_length * MarkingBitmap::kBitsPerCell);
      seq_length = 0;
    }
  }
References v8::internal::MarkingBitmap::kBitsPerCell, and v8::internal::PrintF().
IsSeq()
static bool v8::internal::anonymous_namespace{marking.cc}::CellPrinter::IsSeq (MarkBit::CellType cell) [inline], [static]
Definition at line 111 of file marking.cc.
                                          {
    return cell == 0 || cell == kAllBitsSetInCellValue;
  }
References v8::internal::anonymous_namespace{marking.cc}::kAllBitsSetInCellValue.
Print()
void v8::internal::anonymous_namespace{marking.cc}::CellPrinter::Print (size_t pos, MarkBit::CellType cell) [inline]
Definition at line 83 of file marking.cc.
                                               {
    if (cell == seq_type) {
      seq_length++;
      return;
    }
    Flush();
    if (IsSeq(cell)) {
      seq_start = pos;
      seq_length = 0;
      seq_type = cell;
      return;
    }
    PrintF("%zu: ", pos);
    PrintWord(cell);
    PrintF("\n");
  }
References v8::internal::PrintF(), and v8::internal::anonymous_namespace{marking.cc}::PrintWord().
Member Data Documentation
seq_length
size_t v8::internal::anonymous_namespace{marking.cc}::CellPrinter::seq_length = 0 [private]
Definition at line 118 of file marking.cc.
seq_start
size_t v8::internal::anonymous_namespace{marking.cc}::CellPrinter::seq_start = 0 [private]
Definition at line 116 of file marking.cc.
seq_type
MarkBit::CellType v8::internal::anonymous_namespace{marking.cc}::CellPrinter::seq_type = 0 [private]
Definition at line 117 of file marking.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/marking.cc