v8::internal::wasm::TypeCanonicalizer Class Reference
#include <canonical-types.h>
Classes
struct CanonicalEquality
struct CanonicalGroup
struct CanonicalHashing
struct CanonicalSingletonGroup
struct CanonicalType
class CanonicalTypeVector
struct RecursionGroupRange
Public Member Functions
TypeCanonicalizer ()
TypeCanonicalizer (const TypeCanonicalizer &other)=delete
TypeCanonicalizer & operator= (const TypeCanonicalizer &other)=delete
TypeCanonicalizer (TypeCanonicalizer &&other)=delete
TypeCanonicalizer & operator= (TypeCanonicalizer &&other)=delete
V8_EXPORT_PRIVATE void AddRecursiveGroup (WasmModule *module, uint32_t size)
V8_EXPORT_PRIVATE void AddRecursiveSingletonGroup (WasmModule *module)
V8_EXPORT_PRIVATE CanonicalTypeIndex AddRecursiveGroup (const FunctionSig *sig)
V8_EXPORT_PRIVATE const CanonicalSig * LookupFunctionSignature (CanonicalTypeIndex index) const
V8_EXPORT_PRIVATE const CanonicalStructType * LookupStruct (CanonicalTypeIndex index) const
V8_EXPORT_PRIVATE const CanonicalArrayType * LookupArray (CanonicalTypeIndex index) const
V8_EXPORT_PRIVATE bool IsCanonicalSubtype (CanonicalTypeIndex sub_index, CanonicalTypeIndex super_index)
V8_EXPORT_PRIVATE bool IsCanonicalSubtype (ModuleTypeIndex sub_index, ModuleTypeIndex super_index, const WasmModule *sub_module, const WasmModule *super_module)
V8_EXPORT_PRIVATE void EmptyStorageForTesting ()
size_t EstimateCurrentMemoryConsumption () const
V8_EXPORT_PRIVATE size_t GetCurrentNumberOfTypes () const
V8_EXPORT_PRIVATE bool IsFunctionSignature (CanonicalTypeIndex index) const
V8_EXPORT_PRIVATE bool IsStruct (CanonicalTypeIndex index) const
V8_EXPORT_PRIVATE bool IsArray (CanonicalTypeIndex index) const
V8_EXPORT_PRIVATE bool IsShared (CanonicalTypeIndex index) const
bool IsHeapSubtype (CanonicalTypeIndex sub, CanonicalTypeIndex super) const
bool IsCanonicalSubtype_Locked (CanonicalTypeIndex sub_index, CanonicalTypeIndex super_index) const
CanonicalTypeIndex FindIndex_Slow (const CanonicalSig *sig) const
Static Public Member Functions
static V8_EXPORT_PRIVATE void PrepareForCanonicalTypeId (Isolate *isolate, CanonicalTypeIndex id)
static V8_EXPORT_PRIVATE void ClearWasmCanonicalTypesForTesting (Isolate *isolate)
Static Public Attributes
static constexpr CanonicalTypeIndex kPredefinedArrayI8Index {0}
static constexpr CanonicalTypeIndex kPredefinedArrayI16Index {1}
static constexpr uint32_t kNumberOfPredefinedTypes = 2
Private Member Functions
void AddPredefinedArrayTypes ()
CanonicalTypeIndex FindCanonicalGroup (const CanonicalGroup &) const
CanonicalTypeIndex FindCanonicalGroup (const CanonicalSingletonGroup &) const
CanonicalType CanonicalizeTypeDef (const WasmModule *module, ModuleTypeIndex module_type_idx, ModuleTypeIndex recgroup_start, CanonicalTypeIndex canonical_recgroup_start)
void CheckMaxCanonicalIndex () const
Private Attributes
std::vector< CanonicalTypeIndex > canonical_supertypes_
std::unordered_set< CanonicalGroup > canonical_groups_
std::unordered_set< CanonicalSingletonGroup > canonical_singleton_groups_
CanonicalTypeVector canonical_types_
AccountingAllocator allocator_
Zone zone_ {&allocator_, `canonical type zone`}
base::Mutex mutex_
Detailed Description
Definition at line 49 of file canonical-types.h.
Constructor & Destructor Documentation
TypeCanonicalizer() [1/3]
v8::internal::wasm::TypeCanonicalizer::TypeCanonicalizer ()
Definition at line 24 of file canonical-types.cc.
{ AddPredefinedArrayTypes(); }
References AddPredefinedArrayTypes().
TypeCanonicalizer() [2/3]
v8::internal::wasm::TypeCanonicalizer::TypeCanonicalizer (const TypeCanonicalizer & other) [delete]
TypeCanonicalizer() [3/3]
v8::internal::wasm::TypeCanonicalizer::TypeCanonicalizer (TypeCanonicalizer && other) [delete]
Member Function Documentation
AddPredefinedArrayTypes()
void v8::internal::wasm::TypeCanonicalizer::AddPredefinedArrayTypes () [private]
Definition at line 211 of file canonical-types.cc.
                                                {
  static constexpr std::pair<CanonicalTypeIndex, CanonicalValueType>
      kPredefinedArrayTypes[] = {{kPredefinedArrayI8Index, {kWasmI8}},
                                 {kPredefinedArrayI16Index, {kWasmI16}}};
  canonical_types_.reserve(kNumberOfPredefinedTypes, &zone_);
  for (auto [index, element_type] : kPredefinedArrayTypes) {
    DCHECK_GT(kNumberOfPredefinedTypes, index.index);
    DCHECK_EQ(index.index, canonical_singleton_groups_.size());
    static constexpr bool kMutable = true;
    static constexpr bool kFinal = true;
    static constexpr bool kShared = false; // TODO(14616): Fix this.
    CanonicalArrayType* type =
        zone_.New<CanonicalArrayType>(element_type, kMutable);
    CanonicalSingletonGroup group{
        .type = CanonicalType(type, CanonicalTypeIndex{kNoSuperType}, kFinal,
                              kShared),
        .index = index};
    const CanonicalSingletonGroup& stored_group =
        *canonical_singleton_groups_.emplace(group).first;
    canonical_types_.set(index, &stored_group.type);
    canonical_supertypes_.emplace_back(CanonicalTypeIndex{kNoSuperType});
    DCHECK_LE(canonical_supertypes_.size(), kMaxCanonicalTypes);
  }
}
References canonical_singleton_groups_, canonical_supertypes_, canonical_types_, DCHECK_EQ, DCHECK_GT, DCHECK_LE, v8::internal::index, v8::internal::wasm::kMaxCanonicalTypes, v8::internal::kMutable, v8::internal::wasm::kNoSuperType, kNumberOfPredefinedTypes, kPredefinedArrayI16Index, kPredefinedArrayI8Index, v8::internal::wasm::kWasmI16, v8::internal::wasm::kWasmI8, v8::internal::Zone::New(), v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::reserve(), v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::set(), v8::internal::tracing::type, v8::internal::wasm::TypeCanonicalizer::CanonicalSingletonGroup::type, and zone_.
Referenced by EmptyStorageForTesting(), and TypeCanonicalizer().
AddRecursiveGroup() [1/2]
CanonicalTypeIndex v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup (const FunctionSig * sig)
Definition at line 132 of file canonical-types.cc.
                            {
// Types in the signature must be module-independent.
#if DEBUG
  for (ValueType type : sig->all()) DCHECK(!type.has_index());
#endif
  const bool kFinal = true;
  // Because of the checks above, we can treat the type_def as canonical.
  // TODO(366180605): It would be nice to not have to rely on a cast here.
  // Is there a way to avoid it? In the meantime, these asserts provide at
  // least partial assurances that the cast is safe:
  static_assert(sizeof(CanonicalValueType) == sizeof(ValueType));
  static_assert(
      CanonicalValueType::Primitive(NumericKind::kI32).raw_bit_field() ==
      ValueType::Primitive(kI32).raw_bit_field());
  CanonicalType canonical{reinterpret_cast<const CanonicalSig*>(sig),
                          CanonicalTypeIndex{kNoSuperType}, kFinal, kNotShared};
  base::MutexGuard guard(&mutex_);
  // Fast path lookup before canonicalizing (== copying into the
  // TypeCanonicalizer's zone) the function signature.
  CanonicalTypeIndex new_canonical_index{
      static_cast<uint32_t>(canonical_supertypes_.size())};
  CanonicalTypeIndex index = FindCanonicalGroup(
      CanonicalSingletonGroup{canonical, new_canonical_index});
  if (index.valid()) return index;
  // Copy into this class's zone to store this as a new canonical function type.
  CanonicalSig::Builder builder(&zone_, sig->return_count(),
                                sig->parameter_count());
  for (ValueType ret : sig->returns()) {
    builder.AddReturn(CanonicalValueType{ret});
  }
  for (ValueType param : sig->parameters()) {
    builder.AddParam(CanonicalValueType{param});
  }
  canonical.function_sig = builder.Get();
  CanonicalSingletonGroup group{canonical, new_canonical_index};
  // Copying the signature shouldn't make a difference: There is no match.
  DCHECK(!FindCanonicalGroup(group).valid());
  // Check that the new canonical ID is not used yet.
  DCHECK(std::none_of(
      canonical_singleton_groups_.begin(), canonical_singleton_groups_.end(),
      [=](auto& entry) { return entry.index == new_canonical_index; }));
  DCHECK(std::none_of(
      canonical_groups_.begin(), canonical_groups_.end(),
      [=](auto& entry) { return entry.first == new_canonical_index; }));
  // {group.type} is stack-allocated, whereas {canonical_singleton_groups_}
  // creates a long-lived zone-allocated copy of it.
  const CanonicalSingletonGroup& stored_group =
      *canonical_singleton_groups_.emplace(group).first;
  canonical_supertypes_.push_back(CanonicalTypeIndex{kNoSuperType});
  CheckMaxCanonicalIndex();
  canonical_types_.reserve(new_canonical_index.index + 1, &zone_);
  canonical_types_.set(new_canonical_index, &stored_group.type);
  return new_canonical_index;
}
References v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), canonical_groups_, canonical_singleton_groups_, canonical_supertypes_, canonical_types_, CheckMaxCanonicalIndex(), v8::internal::DCHECK(), FindCanonicalGroup(), v8::internal::wasm::CanonicalSig::Builder::Get(), v8::internal::index, v8::internal::kI32, v8::internal::wasm::kNoSuperType, v8::internal::wasm::kNotShared, mutex_, v8::base::none_of(), v8::internal::wasm::ValueType::Primitive(), v8::internal::wasm::CanonicalValueType::Primitive(), v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::reserve(), v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::set(), v8::internal::sig, v8::internal::tracing::type, v8::internal::wasm::TypeCanonicalizer::CanonicalSingletonGroup::type, and zone_.
AddRecursiveGroup() [2/2]
void v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup (WasmModule * module, uint32_t size)
Definition at line 32 of file canonical-types.cc.
                                                                           {
  if (size == 0) return;
  // If the caller knows statically that {size == 1}, it should have called
  // {AddRecursiveSingletonGroup} directly. For cases where this is not
  // statically determined we add this dispatch here.
  if (size == 1) return AddRecursiveSingletonGroup(module);
  uint32_t start_index = static_cast<uint32_t>(module->types.size() - size);
  // Multiple threads could try to register recursive groups concurrently.
  // TODO(manoskouk): Investigate if we can fine-grain the synchronization.
  base::MutexGuard mutex_guard(&mutex_);
  // Compute the first canonical index in the recgroup in the case that it does
  // not already exist.
  CanonicalTypeIndex first_new_canonical_index{
      static_cast<uint32_t>(canonical_supertypes_.size())};
  // Create a snapshot of the zone; this will be restored in case we find a
  // matching recursion group.
  ZoneSnapshot zone_snapshot = zone_.Snapshot();
  DCHECK_GE(module->types.size(), start_index + size);
  CanonicalGroup group{&zone_, size, first_new_canonical_index};
  for (uint32_t i = 0; i < size; i++) {
    group.types[i] = CanonicalizeTypeDef(
        module, ModuleTypeIndex{start_index + i}, ModuleTypeIndex{start_index},
        first_new_canonical_index);
  }
  if (CanonicalTypeIndex canonical_index = FindCanonicalGroup(group);
      canonical_index.valid()) {
    // Delete zone memory from {CanonicalizeTypeDef} and {CanonicalGroup}.
    zone_snapshot.Restore(&zone_);
    // Identical group found. Map new types to the old types's canonical
    // representatives.
    for (uint32_t i = 0; i < size; i++) {
      CanonicalTypeIndex existing_type_index =
          CanonicalTypeIndex{canonical_index.index + i};
      module->isorecursive_canonical_type_ids[start_index + i] =
          existing_type_index;
    }
    return;
  }
  canonical_supertypes_.resize(first_new_canonical_index.index + size);
  CheckMaxCanonicalIndex();
  canonical_types_.reserve(first_new_canonical_index.index + size, &zone_);
  for (uint32_t i = 0; i < size; i++) {
    CanonicalType& canonical_type = group.types[i];
    CanonicalTypeIndex canonical_id{first_new_canonical_index.index + i};
    // {CanonicalGroup} allocates types in the Zone.
    DCHECK(zone_.Contains(&canonical_type));
    canonical_types_.set(canonical_id, &canonical_type);
    canonical_supertypes_[canonical_id.index] = canonical_type.supertype;
    module->isorecursive_canonical_type_ids[start_index + i] = canonical_id;
  }
  // Check that this canonical ID is not used yet.
  DCHECK(std::none_of(
      canonical_singleton_groups_.begin(), canonical_singleton_groups_.end(),
      [=](auto& entry) { return entry.index == first_new_canonical_index; }));
  DCHECK(std::none_of(
      canonical_groups_.begin(), canonical_groups_.end(),
      [=](auto& entry) { return entry.first == first_new_canonical_index; }));
  canonical_groups_.emplace(group);
}
References AddRecursiveSingletonGroup(), canonical_groups_, canonical_singleton_groups_, canonical_supertypes_, canonical_types_, CanonicalizeTypeDef(), CheckMaxCanonicalIndex(), v8::internal::DCHECK(), DCHECK_GE, FindCanonicalGroup(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::WasmModule::isorecursive_canonical_type_ids, mutex_, v8::base::none_of(), v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::reserve(), v8::internal::ZoneSnapshot::Restore(), v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::set(), size(), v8::internal::Zone::Snapshot(), v8::internal::wasm::TypeCanonicalizer::CanonicalType::supertype, v8::internal::wasm::WasmModule::types, v8::internal::wasm::TypeIndex::valid(), and zone_.
Referenced by wasm::anonymous_namespace{c-api.cc}::SignatureHelper::Canonicalize(), v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup(), v8::internal::WasmJSFunction::New(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl().
AddRecursiveSingletonGroup()
void v8::internal::wasm::TypeCanonicalizer::AddRecursiveSingletonGroup (WasmModule * module)
Definition at line 97 of file canonical-types.cc.
                                                                     {
  DCHECK(!module->types.empty());
  uint32_t type_index = static_cast<uint32_t>(module->types.size() - 1);
  base::MutexGuard guard(&mutex_);
  CanonicalTypeIndex new_canonical_index{
      static_cast<uint32_t>(canonical_supertypes_.size())};
  // Snapshot the zone before allocating the new type; the zone will be reset if
  // we find an identical type.
  ZoneSnapshot zone_snapshot = zone_.Snapshot();
  CanonicalType type =
      CanonicalizeTypeDef(module, ModuleTypeIndex{type_index},
                          ModuleTypeIndex{type_index}, new_canonical_index);
  CanonicalSingletonGroup group{type, new_canonical_index};
  if (CanonicalTypeIndex index = FindCanonicalGroup(group); index.valid()) {
    zone_snapshot.Restore(&zone_);
    module->isorecursive_canonical_type_ids[type_index] = index;
    return;
  }
  // Check that the new canonical ID is not used yet.
  DCHECK(std::none_of(
      canonical_singleton_groups_.begin(), canonical_singleton_groups_.end(),
      [=](auto& entry) { return entry.index == new_canonical_index; }));
  DCHECK(std::none_of(
      canonical_groups_.begin(), canonical_groups_.end(),
      [=](auto& entry) { return entry.first == new_canonical_index; }));
  // {group.type} is stack-allocated, whereas {canonical_singleton_groups_}
  // creates a long-lived zone-allocated copy of it.
  auto stored_group = canonical_singleton_groups_.emplace(group).first;
  canonical_supertypes_.push_back(type.supertype);
  CheckMaxCanonicalIndex();
  canonical_types_.reserve(new_canonical_index.index + 1, &zone_);
  canonical_types_.set(new_canonical_index, &stored_group->type);
  module->isorecursive_canonical_type_ids[type_index] = new_canonical_index;
}
References canonical_groups_, canonical_singleton_groups_, canonical_supertypes_, canonical_types_, CanonicalizeTypeDef(), CheckMaxCanonicalIndex(), v8::internal::DCHECK(), FindCanonicalGroup(), v8::internal::index, v8::internal::wasm::WasmModule::isorecursive_canonical_type_ids, mutex_, v8::base::none_of(), v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::reserve(), v8::internal::ZoneSnapshot::Restore(), v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::set(), v8::internal::Zone::Snapshot(), v8::internal::tracing::type, v8::internal::wasm::WasmModule::types, and zone_.
Referenced by AddRecursiveGroup().
CanonicalizeTypeDef()
TypeCanonicalizer::CanonicalType v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef (const WasmModule * module, ModuleTypeIndex module_type_idx, ModuleTypeIndex recgroup_start, CanonicalTypeIndex canonical_recgroup_start) [private]
Definition at line 291 of file canonical-types.cc.
                                                 {
  mutex_.AssertHeld(); // The caller must hold the mutex.
  auto CanonicalizeTypeIndex = [=](ModuleTypeIndex type_index) {
    if (!type_index.valid()) return CanonicalTypeIndex::Invalid();
    DCHECK(type_index.valid());
    if (type_index < recgroup_start) {
      // This references a type from an earlier recgroup; use the
      // already-canonicalized type index.
      return module->canonical_type_id(type_index);
    }
    // For types within the same recgroup, generate indexes assuming that this
    // is a new canonical recgroup. To prevent truncation in the
    // CanonicalValueType's bit field, we must check the range here.
    uint32_t new_index = canonical_recgroup_start.index +
                         (type_index.index - recgroup_start.index);
    if (V8_UNLIKELY(new_index >= kMaxCanonicalTypes)) {
      V8::FatalProcessOutOfMemory(nullptr, "too many canonicalized types");
    }
    return CanonicalTypeIndex{new_index};
  };
  auto CanonicalizeValueType = [=](ValueType type) {
    if (!type.has_index()) return CanonicalValueType{type};
    static_assert(kMaxCanonicalTypes <=
                  (1 << CanonicalValueType::kNumIndexBits));
    return type.Canonicalize(CanonicalizeTypeIndex(type.ref_index()));
  };
  TypeDefinition type = module->type(module_type_idx);
  CanonicalTypeIndex supertype = CanonicalizeTypeIndex(type.supertype);
  switch (type.kind) {
    case TypeDefinition::kFunction: {
      const FunctionSig* original_sig = type.function_sig;
      CanonicalSig::Builder builder(&zone_, original_sig->return_count(),
                                    original_sig->parameter_count());
      for (ValueType ret : original_sig->returns()) {
        builder.AddReturn(CanonicalizeValueType(ret));
      }
      for (ValueType param : original_sig->parameters()) {
        builder.AddParam(CanonicalizeValueType(param));
      }
      return CanonicalType(builder.Get(), supertype, type.is_final,
                           type.is_shared);
    }
    case TypeDefinition::kStruct: {
      const StructType* original_type = type.struct_type;
      CanonicalStructType::Builder builder(&zone_, original_type->field_count(),
                                           original_type->is_descriptor(),
                                           original_type->is_shared());
      for (uint32_t i = 0; i < original_type->field_count(); i++) {
        builder.AddField(CanonicalizeValueType(original_type->field(i)),
                         original_type->mutability(i),
                         original_type->field_offset(i));
      }
      builder.set_total_fields_size(original_type->total_fields_size());
      return CanonicalType(
          builder.Build(CanonicalStructType::Builder::kUseProvidedOffsets),
          supertype, CanonicalizeTypeIndex(type.descriptor),
          CanonicalizeTypeIndex(type.describes), type.is_final, type.is_shared);
    }
    case TypeDefinition::kArray: {
      CanonicalValueType element_type =
          CanonicalizeValueType(type.array_type->element_type());
      CanonicalArrayType* array_type = zone_.New<CanonicalArrayType>(
          element_type, type.array_type->mutability());
      return CanonicalType(array_type, supertype, type.is_final,
                           type.is_shared);
    }
    case TypeDefinition::kCont: {
      CanonicalTypeIndex canonical_index =
          CanonicalizeTypeIndex(type.cont_type->contfun_typeindex());
      CanonicalContType* canonical_cont =
          zone_.New<CanonicalContType>(canonical_index);
      return CanonicalType(canonical_cont, supertype, type.is_final,
                           type.is_shared);
    }
  }
}
References v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::AddField(), v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::base::Mutex::AssertHeld(), v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::Build(), v8::internal::wasm::WasmModule::canonical_type_id(), v8::internal::DCHECK(), v8::internal::V8::FatalProcessOutOfMemory(), v8::internal::wasm::StructType::field(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::StructTypeBase::field_offset(), v8::internal::wasm::CanonicalSig::Builder::Get(), v8::internal::wasm::TypeIndex::index, v8::internal::wasm::CanonicalTypeIndex::Invalid(), v8::internal::wasm::StructTypeBase::is_descriptor(), v8::internal::wasm::StructTypeBase::is_shared(), v8::internal::wasm::TypeDefinition::kArray, v8::internal::wasm::TypeDefinition::kCont, v8::internal::wasm::TypeDefinition::kFunction, v8::internal::wasm::kMaxCanonicalTypes, v8::internal::wasm::ValueTypeBase::kNumIndexBits, v8::internal::wasm::TypeDefinition::kStruct, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::kUseProvidedOffsets, v8::internal::wasm::StructTypeBase::mutability(), mutex_, v8::internal::Zone::New(), v8::internal::Signature< T >::parameter_count(), v8::internal::Signature< T >::parameters(), v8::internal::Signature< T >::return_count(), v8::internal::Signature< T >::returns(), v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::set_total_fields_size(), v8::internal::wasm::StructTypeBase::total_fields_size(), v8::internal::tracing::type, v8::internal::wasm::WasmModule::type(), V8_UNLIKELY, and zone_.
Referenced by AddRecursiveGroup(), and AddRecursiveSingletonGroup().
CheckMaxCanonicalIndex()
void v8::internal::wasm::TypeCanonicalizer::CheckMaxCanonicalIndex () const [private]
Definition at line 26 of file canonical-types.cc.
                                                     {
  if (V8_UNLIKELY(canonical_supertypes_.size() > kMaxCanonicalTypes)) {
    V8::FatalProcessOutOfMemory(nullptr, "too many canonicalized types");
  }
}
References canonical_supertypes_, v8::internal::V8::FatalProcessOutOfMemory(), v8::internal::wasm::kMaxCanonicalTypes, and V8_UNLIKELY.
Referenced by AddRecursiveGroup(), and AddRecursiveSingletonGroup().
ClearWasmCanonicalTypesForTesting()
void v8::internal::wasm::TypeCanonicalizer::ClearWasmCanonicalTypesForTesting (Isolate * isolate) [static]
Definition at line 452 of file canonical-types.cc.
                                                                          {
  ReadOnlyRoots roots(isolate);
  isolate->heap()->SetWasmCanonicalRtts(roots.empty_weak_fixed_array());
  isolate->heap()->SetJSToWasmWrappers(roots.empty_weak_fixed_array());
}
References v8::internal::Isolate::heap().
EmptyStorageForTesting()
void v8::internal::wasm::TypeCanonicalizer::EmptyStorageForTesting ()
Definition at line 277 of file canonical-types.cc.
                                               {
  // Any remaining native modules might reference the types we're about to
  // clear.
  CHECK_EQ(GetWasmEngine()->NativeModuleCount(), 0);
  base::MutexGuard mutex_guard(&mutex_);
  canonical_types_.ClearForTesting();
  canonical_supertypes_.clear();
  canonical_groups_.clear();
  canonical_singleton_groups_.clear();
  zone_.Reset();
  AddPredefinedArrayTypes();
}
References AddPredefinedArrayTypes(), canonical_groups_, canonical_singleton_groups_, canonical_supertypes_, canonical_types_, CHECK_EQ, v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::ClearForTesting(), v8::internal::wasm::GetWasmEngine(), mutex_, v8::internal::Zone::Reset(), and zone_.
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::TypeCanonicalizer::EstimateCurrentMemoryConsumption () const
Definition at line 395 of file canonical-types.cc.
                                                                 {
  UPDATE_WHEN_CLASS_CHANGES(TypeCanonicalizer, 8032);
  // The storage of the canonical group's types is accounted for via the
  // allocator below (which tracks the zone memory).
  base::MutexGuard mutex_guard(&mutex_);
  size_t result = ContentSize(canonical_supertypes_);
  result += ContentSize(canonical_groups_);
  result += ContentSize(canonical_singleton_groups_);
  // Note: the allocator also tracks zone allocations of `canonical_types_`.
  result += allocator_.GetCurrentMemoryUsage();
  if (v8_flags.trace_wasm_offheap_memory) {
    PrintF("TypeCanonicalizer: %zu\n", result);
  }
  return result;
}
References allocator_, canonical_groups_, canonical_singleton_groups_, canonical_supertypes_, v8::internal::wasm::ContentSize(), v8::internal::AccountingAllocator::GetCurrentMemoryUsage(), mutex_, v8::internal::PrintF(), v8::base::internal::result, UPDATE_WHEN_CLASS_CHANGES, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmEngine::EstimateCurrentMemoryConsumption().
FindCanonicalGroup() [1/2]
CanonicalTypeIndex v8::internal::wasm::TypeCanonicalizer::FindCanonicalGroup (const CanonicalGroup & group) const [private]
Definition at line 376 of file canonical-types.cc.
                                       {
  // Groups of size 0 do not make sense here; groups of size 1 should use
  // {CanonicalSingletonGroup} (see below).
  DCHECK_LT(1, group.types.size());
  auto it = canonical_groups_.find(group);
  return it == canonical_groups_.end() ? CanonicalTypeIndex::Invalid()
                                       : it->first;
}
References canonical_groups_, DCHECK_LT, v8::internal::wasm::CanonicalTypeIndex::Invalid(), and v8::internal::wasm::TypeCanonicalizer::CanonicalGroup::types.
Referenced by AddRecursiveGroup(), and AddRecursiveSingletonGroup().
FindCanonicalGroup() [2/2]
CanonicalTypeIndex v8::internal::wasm::TypeCanonicalizer::FindCanonicalGroup (const CanonicalSingletonGroup & group) const [private]
Definition at line 387 of file canonical-types.cc.
                                                {
  auto it = canonical_singleton_groups_.find(group);
  static_assert(kMaxCanonicalTypes <= kMaxInt);
  return it == canonical_singleton_groups_.end() ? CanonicalTypeIndex::Invalid()
                                                 : it->index;
}
References canonical_singleton_groups_, v8::internal::wasm::CanonicalTypeIndex::Invalid(), v8::internal::wasm::kMaxCanonicalTypes, and v8::internal::kMaxInt.
FindIndex_Slow()
CanonicalTypeIndex v8::internal::wasm::TypeCanonicalizer::FindIndex_Slow (const CanonicalSig * sig) const
Definition at line 471 of file canonical-types.cc.
                                   {
  // TODO(397489547): Make this faster. The plan is to allocate an extra
  // slot in the Zone immediately preceding each CanonicalSig, so we can
  // get from the sig's address to that slot's address via pointer arithmetic.
  // For now, just search through all known signatures, which is acceptable
  // as long as only the type-reflection proposal needs this.
  // TODO(42210967): Improve this before shipping Type Reflection.
  return canonical_types_.FindIndex_Slow(sig);
}
References canonical_types_, v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::FindIndex_Slow(), and v8::internal::sig.
Referenced by v8::internal::RUNTIME_FUNCTION().
GetCurrentNumberOfTypes()
size_t v8::internal::wasm::TypeCanonicalizer::GetCurrentNumberOfTypes () const
Definition at line 411 of file canonical-types.cc.
                                                        {
  base::MutexGuard mutex_guard(&mutex_);
  return canonical_supertypes_.size();
}
References canonical_supertypes_, and mutex_.
IsArray()
bool v8::internal::wasm::TypeCanonicalizer::IsArray (CanonicalTypeIndex index) const
Definition at line 464 of file canonical-types.cc.
                                                              {
  return canonical_types_[index]->kind == CanonicalType::kArray;
}
References canonical_types_, v8::internal::index, and v8::internal::wasm::TypeCanonicalizer::CanonicalType::kArray.
IsCanonicalSubtype() [1/2]
bool v8::internal::wasm::TypeCanonicalizer::IsCanonicalSubtype (CanonicalTypeIndex sub_index, CanonicalTypeIndex super_index)
Definition at line 236 of file canonical-types.cc.
                                                                           {
  // Fast path without synchronization:
  if (sub_index == super_index) return true;
  // Multiple threads could try to register and access recursive groups
  // concurrently.
  // TODO(manoskouk): Investigate if we can improve this synchronization.
  base::MutexGuard mutex_guard(&mutex_);
  return IsCanonicalSubtype_Locked(sub_index, super_index);
}
References IsCanonicalSubtype_Locked(), and mutex_.
Referenced by IsCanonicalSubtype(), and v8::internal::WasmExportedFunctionData::MatchesSignature().
IsCanonicalSubtype() [2/2]
bool v8::internal::wasm::TypeCanonicalizer::IsCanonicalSubtype (ModuleTypeIndex sub_index, ModuleTypeIndex super_index, const WasmModule * sub_module, const WasmModule * super_module)
Definition at line 260 of file canonical-types.cc.
                                                                           {
  CanonicalTypeIndex canonical_super =
      super_module->canonical_type_id(super_index);
  CanonicalTypeIndex canonical_sub = sub_module->canonical_type_id(sub_index);
  return IsCanonicalSubtype(canonical_sub, canonical_super);
}
References v8::internal::wasm::WasmModule::canonical_type_id(), and IsCanonicalSubtype().
IsCanonicalSubtype_Locked()
bool v8::internal::wasm::TypeCanonicalizer::IsCanonicalSubtype_Locked (CanonicalTypeIndex sub_index, CanonicalTypeIndex super_index) const
Definition at line 247 of file canonical-types.cc.
                                                                        {
  while (sub_index.valid()) {
    if (sub_index == super_index) return true;
    // TODO(jkummerow): Investigate if replacing this with
    // `sub_index = canonical_types_[sub_index].supertype;`
    // has acceptable performance, which would allow us to save the memory
    // cost of storing {canonical_supertypes_}.
    sub_index = canonical_supertypes_[sub_index.index];
  }
  return false;
}
References canonical_supertypes_, v8::internal::wasm::TypeIndex::index, and v8::internal::wasm::TypeIndex::valid().
Referenced by IsCanonicalSubtype(), and IsHeapSubtype().
IsFunctionSignature()
bool v8::internal::wasm::TypeCanonicalizer::IsFunctionSignature (CanonicalTypeIndex index) const
Definition at line 458 of file canonical-types.cc.
                                                                          {
  return canonical_types_[index]->kind == CanonicalType::kFunction;
}
References canonical_types_, v8::internal::index, and v8::internal::wasm::TypeCanonicalizer::CanonicalType::kFunction.
IsHeapSubtype()
bool v8::internal::wasm::TypeCanonicalizer::IsHeapSubtype (CanonicalTypeIndex sub, CanonicalTypeIndex super) const
Definition at line 270 of file canonical-types.cc.
                                                                      {
  DCHECK_NE(sub, super);
  base::MutexGuard mutex_guard(&mutex_);
  return IsCanonicalSubtype_Locked(sub, super);
}
References DCHECK_NE, IsCanonicalSubtype_Locked(), and mutex_.
Referenced by v8::internal::wasm::IsSubtypeOfImpl().
IsShared()
bool v8::internal::wasm::TypeCanonicalizer::IsShared (CanonicalTypeIndex index) const
Definition at line 467 of file canonical-types.cc.
                                                               {
  return canonical_types_[index]->is_shared;
}
References canonical_types_, and v8::internal::index.
Referenced by v8::internal::CreateArrayMap(), and v8::internal::CreateStructMap().
IsStruct()
bool v8::internal::wasm::TypeCanonicalizer::IsStruct (CanonicalTypeIndex index) const
Definition at line 461 of file canonical-types.cc.
                                                               {
  return canonical_types_[index]->kind == CanonicalType::kStruct;
}
References canonical_types_, v8::internal::index, and v8::internal::wasm::TypeCanonicalizer::CanonicalType::kStruct.
LookupArray()
const CanonicalArrayType * v8::internal::wasm::TypeCanonicalizer::LookupArray (CanonicalTypeIndex index) const
Definition at line 204 of file canonical-types.cc.
                                    {
  const CanonicalType* type = canonical_types_[index];
  SBXCHECK_EQ(type->kind, CanonicalType::kArray);
  return type->array_type;
}
References canonical_types_, v8::internal::index, v8::internal::wasm::TypeCanonicalizer::CanonicalType::kArray, SBXCHECK_EQ, and v8::internal::tracing::type.
Referenced by v8::internal::CreateArrayMap().
LookupFunctionSignature()
const CanonicalSig * v8::internal::wasm::TypeCanonicalizer::LookupFunctionSignature (CanonicalTypeIndex index) const
Definition at line 190 of file canonical-types.cc.
                                    {
  const CanonicalType* type = canonical_types_[index];
  SBXCHECK_EQ(type->kind, CanonicalType::kFunction);
  return type->function_sig;
}
References canonical_types_, v8::internal::index, v8::internal::wasm::TypeCanonicalizer::CanonicalType::kFunction, SBXCHECK_EQ, and v8::internal::tracing::type.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution(), v8::internal::wasm::WasmBytecodeGenerator::GenerateBytecode(), v8::internal::WasmInternalFunction::GetOrCreateExternal(), v8::internal::WasmJSFunctionData::GetSignature(), wasm::anonymous_namespace{c-api.cc}::make_func(), v8::internal::WasmJSFunction::New(), v8::internal::WasmExportedFunction::New(), v8::anonymous_namespace{wasm-js.cc}::NewPromisingWasmExportedFunction(), v8::internal::wasm::InstanceBuilder::ProcessImportedFunction(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::WasmModule::signature_hash(), v8::internal::WasmTableObject::UpdateDispatchTable(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl().
LookupStruct()
const CanonicalStructType * v8::internal::wasm::TypeCanonicalizer::LookupStruct (CanonicalTypeIndex index) const
Definition at line 197 of file canonical-types.cc.
                                    {
  const CanonicalType* type = canonical_types_[index];
  SBXCHECK_EQ(type->kind, CanonicalType::kStruct);
  return type->struct_type;
}
References canonical_types_, v8::internal::index, v8::internal::wasm::TypeCanonicalizer::CanonicalType::kStruct, SBXCHECK_EQ, and v8::internal::tracing::type.
Referenced by v8::internal::StructProxy::Count(), v8::internal::CreateStructMap(), v8::internal::wasm::DecodeCanonicalTypeNames(), v8::internal::WasmStruct::GcSafeType(), and v8::internal::WasmStruct::GetFieldValue().
operator=() [1/2]
TypeCanonicalizer& v8::internal::wasm::TypeCanonicalizer::operator= (const TypeCanonicalizer & other) [delete]
operator=() [2/2]
TypeCanonicalizer& v8::internal::wasm::TypeCanonicalizer::operator= (TypeCanonicalizer && other) [delete]
PrepareForCanonicalTypeId()
void v8::internal::wasm::TypeCanonicalizer::PrepareForCanonicalTypeId (Isolate * isolate, CanonicalTypeIndex id) [static]
Definition at line 417 of file canonical-types.cc.
                                                                         {
  if (!id.valid()) return;
  Heap* heap = isolate->heap();
  // {2 * (id + 1)} needs to fit in an int.
  CHECK_LE(id.index, kMaxInt / 2 - 1);
  // Canonical types are zero-indexed.
  const int length = id.index + 1;
  // The fast path is non-handlified.
  Tagged<WeakFixedArray> old_rtts_raw = heap->wasm_canonical_rtts();
  // Fast path: length is sufficient.
  int old_length = old_rtts_raw->length();
  if (old_length >= length) return;
  // Allocate a bigger WeakFixedArray, growing exponentially.
  const int new_length = std::max(old_length * 3 / 2, length);
  CHECK_LT(old_length, new_length);
  // Allocation can invalidate previous unhandled pointers.
  DirectHandle<WeakFixedArray> old_rtts{old_rtts_raw, isolate};
  old_rtts_raw = {};
  // We allocate the WeakFixedArray filled with undefined values, as we cannot
  // pass the cleared value in a handle (see https://crbug.com/364591622). We
  // overwrite the new entries via {MemsetTagged} afterwards.
  DirectHandle<WeakFixedArray> new_rtts =
      WeakFixedArray::New(isolate, new_length, AllocationType::kOld);
  WeakFixedArray::CopyElements(isolate, *new_rtts, 0, *old_rtts, 0, old_length);
  MemsetTagged(new_rtts->RawFieldOfFirstElement() + old_length,
               ClearedValue(isolate), new_length - old_length);
  heap->SetWasmCanonicalRtts(*new_rtts);
}
References CHECK_LE, CHECK_LT, v8::internal::ClearedValue(), v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::CopyElements(), v8::internal::Isolate::heap(), v8::internal::index, v8::internal::kMaxInt, v8::internal::kOld, v8::internal::length, v8::internal::MemsetTagged(), and v8::internal::WeakFixedArray::New().
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::WasmInternalFunction::GetOrCreateExternal(), and v8::internal::WasmJSFunction::New().
Member Data Documentation
allocator_
AccountingAllocator v8::internal::wasm::TypeCanonicalizer::allocator_ [private]
Definition at line 568 of file canonical-types.h.
Referenced by EstimateCurrentMemoryConsumption().
canonical_groups_
std::unordered_set<CanonicalGroup> v8::internal::wasm::TypeCanonicalizer::canonical_groups_ [private]
Definition at line 563 of file canonical-types.h.
Referenced by AddRecursiveGroup(), AddRecursiveSingletonGroup(), EmptyStorageForTesting(), EstimateCurrentMemoryConsumption(), and FindCanonicalGroup().
canonical_singleton_groups_
std::unordered_set<CanonicalSingletonGroup> v8::internal::wasm::TypeCanonicalizer::canonical_singleton_groups_ [private]
Definition at line 565 of file canonical-types.h.
Referenced by AddPredefinedArrayTypes(), AddRecursiveGroup(), AddRecursiveSingletonGroup(), EmptyStorageForTesting(), EstimateCurrentMemoryConsumption(), and FindCanonicalGroup().
canonical_supertypes_
std::vector<CanonicalTypeIndex> v8::internal::wasm::TypeCanonicalizer::canonical_supertypes_ [private]
Definition at line 561 of file canonical-types.h.
Referenced by AddPredefinedArrayTypes(), AddRecursiveGroup(), AddRecursiveSingletonGroup(), CheckMaxCanonicalIndex(), EmptyStorageForTesting(), EstimateCurrentMemoryConsumption(), GetCurrentNumberOfTypes(), and IsCanonicalSubtype_Locked().
canonical_types_
CanonicalTypeVector v8::internal::wasm::TypeCanonicalizer::canonical_types_ [private]
Definition at line 567 of file canonical-types.h.
Referenced by AddPredefinedArrayTypes(), AddRecursiveGroup(), AddRecursiveSingletonGroup(), EmptyStorageForTesting(), FindIndex_Slow(), IsArray(), IsFunctionSignature(), IsShared(), IsStruct(), LookupArray(), LookupFunctionSignature(), and LookupStruct().
kNumberOfPredefinedTypes
constexpr uint32_t v8::internal::wasm::TypeCanonicalizer::kNumberOfPredefinedTypes = 2 [static], [constexpr]
Definition at line 53 of file canonical-types.h.
Referenced by AddPredefinedArrayTypes().
kPredefinedArrayI16Index
constexpr CanonicalTypeIndex v8::internal::wasm::TypeCanonicalizer::kPredefinedArrayI16Index {1} [static], [constexpr]
Definition at line 52 of file canonical-types.h.
Referenced by AddPredefinedArrayTypes(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::IsI16Array(), and v8::internal::RUNTIME_FUNCTION().
kPredefinedArrayI8Index
constexpr CanonicalTypeIndex v8::internal::wasm::TypeCanonicalizer::kPredefinedArrayI8Index {0} [static], [constexpr]
Definition at line 51 of file canonical-types.h.
Referenced by AddPredefinedArrayTypes(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::IsI8Array(), and v8::internal::RUNTIME_FUNCTION().
mutex_
base::Mutex v8::internal::wasm::TypeCanonicalizer::mutex_ [mutable], [private]
Definition at line 570 of file canonical-types.h.
Referenced by AddRecursiveGroup(), AddRecursiveSingletonGroup(), CanonicalizeTypeDef(), EmptyStorageForTesting(), EstimateCurrentMemoryConsumption(), GetCurrentNumberOfTypes(), IsCanonicalSubtype(), and IsHeapSubtype().
zone_
Zone v8::internal::wasm::TypeCanonicalizer::zone_ {&allocator_, `canonical type zone`} [private]
Definition at line 569 of file canonical-types.h.
Referenced by AddPredefinedArrayTypes(), AddRecursiveGroup(), AddRecursiveSingletonGroup(), CanonicalizeTypeDef(), and EmptyStorageForTesting().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/canonical-types.h
/mnt/V8SourceCode/src/wasm/canonical-types.cc