v8::internal::FixedAddressArrayBase< Base > Class Template Reference
#include <fixed-array.h>
Public Member Functions
Address get_sandboxed_pointer (int index) const
void set_sandboxed_pointer (int index, Address value)
template<typename... MoreArgs>
DirectHandle< FixedAddressArrayBase< Base > > New (Isolate *isolate, int length, MoreArgs &&... more_args)
Static Public Member Functions
template<typename... MoreArgs>
static DirectHandle< FixedAddressArrayBase > New (Isolate *isolate, int length, MoreArgs &&... more_args)
Private Types
using Underlying = FixedIntegerArrayBase< Address, Base >
Additional Inherited Members
Detailed Description
template<typename Base>
class v8::internal::FixedAddressArrayBase< Base >
Definition at line 877 of file fixed-array.h.
Member Typedef Documentation
Underlying
template<typename Base >
using v8::internal::FixedAddressArrayBase< Base >::Underlying = FixedIntegerArrayBase<Address, Base> [private]
Definition at line 878 of file fixed-array.h.
Member Function Documentation
get_sandboxed_pointer()
template<typename Base >
Address v8::internal::FixedAddressArrayBase< Base >::get_sandboxed_pointer (int index) const [inline]
Definition at line 863 of file fixed-array-inl.h.
                                                                          {
  PtrComprCageBase sandbox_base = GetPtrComprCageBase(this);
  return ReadSandboxedPointerField(this->get_element_address(index),
                                   sandbox_base);
}
References v8::internal::GetPtrComprCageBase(), v8::internal::index, and v8::internal::ReadSandboxedPointerField().
New() [1/2]
template<typename Base >
template<typename... MoreArgs>
DirectHandle<FixedAddressArrayBase<Base> > v8::internal::FixedAddressArrayBase< Base >::New (Isolate * isolate, int length, MoreArgs &&... more_args)
Definition at line 820 of file fixed-array-inl.h.
                                                           {
  return Cast<FixedAddressArrayBase>(
      Underlying::New(isolate, length, std::forward<MoreArgs>(more_args)...));
}
References v8::internal::length, and v8::internal::anonymous_namespace{intl-objects.cc}::New().
New() [2/2]
template<typename Base >
template<typename... MoreArgs>
static DirectHandle<FixedAddressArrayBase> v8::internal::FixedAddressArrayBase< Base >::New (Isolate * isolate, int length, MoreArgs &&... more_args) [inline], [static]
Referenced by v8::internal::WasmTrustedInstanceData::New().
set_sandboxed_pointer()
template<typename Base >
void v8::internal::FixedAddressArrayBase< Base >::set_sandboxed_pointer (int index, Address value) [inline]
Definition at line 870 of file fixed-array-inl.h.
                                                                       {
  PtrComprCageBase sandbox_base = GetPtrComprCageBase(this);
  WriteSandboxedPointerField(this->get_element_address(index), sandbox_base,
                             value);
}
References v8::internal::GetPtrComprCageBase(), v8::internal::index, v8::internal::value, and v8::internal::WriteSandboxedPointerField().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h