v8::internal::compiler::RegExpBoilerplateDescriptionRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< RegExpBoilerplateDescription > object () const
HeapObjectRef data (JSHeapBroker *broker) const
StringRef source (JSHeapBroker *broker) const
int flags () const
Detailed Description
Definition at line 697 of file heap-refs.h.
Member Function Documentation
data()
HeapObjectRef v8::internal::compiler::RegExpBoilerplateDescriptionRef::data (JSHeapBroker * broker) const
Definition at line 1667 of file heap-refs.cc.
                                {
  // Immutable after initialization.
  return MakeRefAssumeMemoryFence(
      broker, Cast<HeapObject>(object()->data(broker->isolate())));
}
References broker(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
Referenced by v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp(), and v8::internal::maglev::MaglevGraphBuilder::CreateRegExpLiteralObject().
flags()
int v8::internal::compiler::RegExpBoilerplateDescriptionRef::flags () const
Definition at line 1679 of file heap-refs.cc.
{ return object()->flags(); }
References object().
Referenced by v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp(), and v8::internal::maglev::MaglevGraphBuilder::CreateRegExpLiteralObject().
object()
IndirectHandle<RegExpBoilerplateDescription> v8::internal::compiler::RegExpBoilerplateDescriptionRef::object () const
Referenced by flags().
source()
StringRef v8::internal::compiler::RegExpBoilerplateDescriptionRef::source (JSHeapBroker * broker) const
Definition at line 1674 of file heap-refs.cc.
                                                                            {
  // Immutable after initialization.
  return MakeRefAssumeMemoryFence(broker, object()->source());
}
References broker(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
Referenced by v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp(), and v8::internal::maglev::MaglevGraphBuilder::CreateRegExpLiteralObject().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc