v8::internal::compiler::BasicBlockCallGraphProfiler Class Reference
#include <basic-block-instrumentor.h>
Static Public Member Functions
static void StoreCallGraph (OptimizedCompilationInfo *info, Schedule *schedule)
static void StoreCallGraph (OptimizedCompilationInfo *info, const turboshaft::Graph &graph)
Detailed Description
Definition at line 35 of file basic-block-instrumentor.h.
Member Function Documentation
StoreCallGraph() [1/2]
void v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph (OptimizedCompilationInfo * info, const turboshaft::Graph & graph) [static]
Definition at line 252 of file basic-block-instrumentor.cc.
                                                                  {
  using namespace turboshaft; // NOLINT(build/namespaces)
  CHECK(Builtins::IsBuiltinId(info->builtin()));
  BuiltinsCallGraph* profiler = BuiltinsCallGraph::Get();
  for (const Block* block : graph.blocks_vector()) {
    const int block_id = block->index().id();
    for (const auto& op : graph.operations(*block)) {
      Builtin called_builtin;
      if (IsBuiltinCall(op, graph, &called_builtin)) {
        profiler->AddBuiltinCall(info->builtin(), called_builtin, block_id);
      }
    }
  }
}
References v8::internal::BuiltinsCallGraph::AddBuiltinCall(), v8::internal::OptimizedCompilationInfo::builtin(), CHECK, v8::internal::BuiltinsCallGraph::Get(), graph(), v8::internal::compiler::IsBuiltinCall(), and v8::internal::Builtins::IsBuiltinId().
StoreCallGraph() [2/2]
void v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph (OptimizedCompilationInfo * info, Schedule * schedule) [static]
Definition at line 192 of file basic-block-instrumentor.cc.
                                                                     {
  CHECK(Builtins::IsBuiltinId(info->builtin()));
  BasicBlockVector* blocks = schedule->rpo_order();
  size_t block_number = 0;
  size_t n_blocks = schedule->RpoBlockCount();
  for (BasicBlockVector::iterator it = blocks->begin(); block_number < n_blocks;
       ++it, ++block_number) {
    BasicBlock* block = (*it);
    if (block == schedule->end()) continue;
    // Iteration is already in reverse post-order.
    DCHECK_EQ(block->rpo_number(), block_number);
    int block_id = block->id().ToInt();
    BuiltinsCallGraph* profiler = BuiltinsCallGraph::Get();
    for (Node* node : *block) {
      StoreBuiltinCallForNode(node, info->builtin(), block_id, profiler);
    }
    BasicBlock::Control control = block->control();
    if (control != BasicBlock::kNone) {
      Node* cnt_node = block->control_input();
      StoreBuiltinCallForNode(cnt_node, info->builtin(), block_id, profiler);
    }
  }
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::OptimizedCompilationInfo::builtin(), CHECK, v8::internal::compiler::BasicBlock::control(), v8::internal::compiler::BasicBlock::control_input(), DCHECK_EQ, v8::internal::compiler::Schedule::end(), v8::internal::BuiltinsCallGraph::Get(), v8::internal::compiler::BasicBlock::id(), v8::internal::Builtins::IsBuiltinId(), v8::internal::compiler::BasicBlock::kNone, v8::internal::compiler::BasicBlock::rpo_number(), v8::internal::compiler::Schedule::rpo_order(), v8::internal::compiler::Schedule::RpoBlockCount(), v8::internal::compiler::anonymous_namespace{basic-block-instrumentor.cc}::StoreBuiltinCallForNode(), and v8::internal::compiler::BasicBlock::Id::ToInt().
Referenced by v8::internal::compiler::turboshaft::Pipeline::PrepareForInstructionSelection().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/basic-block-instrumentor.h
/mnt/V8SourceCode/src/compiler/basic-block-instrumentor.cc