v8::internal::RegExpDisjunction Class Reference
#include <regexp-ast.h>
Public Member Functions
RegExpDisjunction (ZoneList< RegExpTree * > *alternatives)
DECL_BOILERPLATE (Disjunction)
Interval CaptureRegisters () override
bool IsAnchoredAtStart () override
bool IsAnchoredAtEnd () override
int min_match () override
int max_match () override
ZoneList< RegExpTree * > * alternatives () const
Private Member Functions
bool SortConsecutiveAtoms (RegExpCompiler *compiler)
void RationalizeConsecutiveAtoms (RegExpCompiler *compiler)
void FixSingleCharacterDisjunctions (RegExpCompiler *compiler)
Private Attributes
ZoneList< RegExpTree * > * alternatives_
int min_match_
int max_match_
Additional Inherited Members
Detailed Description
Definition at line 218 of file regexp-ast.h.
Constructor & Destructor Documentation
RegExpDisjunction()
v8::internal::RegExpDisjunction::RegExpDisjunction (ZoneList< RegExpTree * > * alternatives) [explicit]
Definition at line 350 of file regexp-ast.cc.
    : alternatives_(alternatives) {
  DCHECK_LT(1, alternatives->length());
  RegExpTree* first_alternative = alternatives->at(0);
  min_match_ = first_alternative->min_match();
  max_match_ = first_alternative->max_match();
  for (int i = 1; i < alternatives->length(); i++) {
    RegExpTree* alternative = alternatives->at(i);
    min_match_ = std::min(min_match_, alternative->min_match());
    max_match_ = std::max(max_match_, alternative->max_match());
  }
}
References alternatives(), DCHECK_LT, v8::internal::RegExpTree::max_match(), max_match_, v8::internal::RegExpTree::min_match(), and min_match_.
Member Function Documentation
alternatives()
ZoneList<RegExpTree*>* v8::internal::RegExpDisjunction::alternatives () const [inline]
Definition at line 229 of file regexp-ast.h.
{ return alternatives_; }
References alternatives_.
Referenced by CaptureRegisters(), IsAnchoredAtEnd(), IsAnchoredAtStart(), RegExpDisjunction(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitDisjunction(), v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitDisjunction(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitDisjunction().
CaptureRegisters()
Interval v8::internal::RegExpDisjunction::CaptureRegisters () [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 48 of file regexp-ast.cc.
                                             {
  return ListCaptureRegisters(alternatives());
}
References alternatives(), and v8::internal::anonymous_namespace{regexp-ast.cc}::ListCaptureRegisters().
DECL_BOILERPLATE()
v8::internal::RegExpDisjunction::DECL_BOILERPLATE (Disjunction)
FixSingleCharacterDisjunctions()
void v8::internal::RegExpDisjunction::FixSingleCharacterDisjunctions (RegExpCompiler * compiler) [private]
Definition at line 959 of file regexp-compiler-tonode.cc.
                              {
  Zone* zone = compiler->zone();
  ZoneList<RegExpTree*>* alternatives = this->alternatives();
  int length = alternatives->length();
  int write_posn = 0;
  int i = 0;
  while (i < length) {
    RegExpTree* alternative = alternatives->at(i);
    if (!alternative->IsAtom()) {
      alternatives->at(write_posn++) = alternatives->at(i);
      i++;
      continue;
    }
    RegExpAtom* const atom = alternative->AsAtom();
    if (atom->length() != 1) {
      alternatives->at(write_posn++) = alternatives->at(i);
      i++;
      continue;
    }
    const RegExpFlags flags = compiler->flags();
    DCHECK_IMPLIES(IsEitherUnicode(flags),
                   !unibrow::Utf16::IsLeadSurrogate(atom->data().at(0)));
    bool contains_trail_surrogate =
        unibrow::Utf16::IsTrailSurrogate(atom->data().at(0));
    int first_in_run = i;
    i++;
    // Find a run of single-character atom alternatives that have identical
    // flags (case independence and unicode-ness).
    while (i < length) {
      alternative = alternatives->at(i);
      if (!alternative->IsAtom()) break;
      RegExpAtom* const alt_atom = alternative->AsAtom();
      if (alt_atom->length() != 1) break;
      DCHECK_IMPLIES(IsEitherUnicode(flags),
                     !unibrow::Utf16::IsLeadSurrogate(alt_atom->data().at(0)));
      contains_trail_surrogate |=
          unibrow::Utf16::IsTrailSurrogate(alt_atom->data().at(0));
      i++;
    }
    if (i > first_in_run + 1) {
      // Found non-trivial run of single-character alternatives.
      int run_length = i - first_in_run;
      ZoneList<CharacterRange>* ranges =
          zone->New<ZoneList<CharacterRange>>(2, zone);
      for (int j = 0; j < run_length; j++) {
        RegExpAtom* old_atom = alternatives->at(j + first_in_run)->AsAtom();
        DCHECK_EQ(old_atom->length(), 1);
        ranges->Add(CharacterRange::Singleton(old_atom->data().at(0)), zone);
      }
      RegExpClassRanges::ClassRangesFlags class_ranges_flags;
      if (IsEitherUnicode(flags) && contains_trail_surrogate) {
        class_ranges_flags = RegExpClassRanges::CONTAINS_SPLIT_SURROGATE;
      }
      alternatives->at(write_posn++) =
          zone->New<RegExpClassRanges>(zone, ranges, class_ranges_flags);
    } else {
      // Just copy any trivial alternatives.
      for (int j = first_in_run; j < i; j++) {
        alternatives->at(write_posn++) = alternatives->at(j);
      }
    }
  }
  alternatives->Rewind(write_posn); // Trim end of array.
}
References v8::internal::ZoneList< T >::Add(), v8::internal::ZoneList< T >::at(), v8::base::Vector< T >::at(), v8::internal::RegExpClassRanges::CONTAINS_SPLIT_SURROGATE, v8::internal::RegExpAtom::data(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::RegExpCompiler::flags(), v8::internal::flags, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsEitherUnicode(), unibrow::Utf16::IsLeadSurrogate(), unibrow::Utf16::IsTrailSurrogate(), v8::internal::length, v8::internal::RegExpAtom::length(), v8::internal::ZoneList< T >::length(), v8::internal::Zone::New(), v8::internal::ZoneList< T >::Rewind(), v8::internal::CharacterRange::Singleton(), and v8::internal::RegExpCompiler::zone().
IsAnchoredAtEnd()
bool v8::internal::RegExpDisjunction::IsAnchoredAtEnd () [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 118 of file regexp-ast.cc.
                                        {
  ZoneList<RegExpTree*>* alternatives = this->alternatives();
  for (int i = 0; i < alternatives->length(); i++) {
    if (!alternatives->at(i)->IsAnchoredAtEnd()) return false;
  }
  return true;
}
References alternatives(), and v8::internal::ZoneList< T >::length().
IsAnchoredAtStart()
bool v8::internal::RegExpDisjunction::IsAnchoredAtStart () [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 109 of file regexp-ast.cc.
                                          {
  ZoneList<RegExpTree*>* alternatives = this->alternatives();
  for (int i = 0; i < alternatives->length(); i++) {
    if (!alternatives->at(i)->IsAnchoredAtStart()) return false;
  }
  return true;
}
References alternatives(), and v8::internal::ZoneList< T >::length().
max_match()
int v8::internal::RegExpDisjunction::max_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 228 of file regexp-ast.h.
{ return max_match_; }
References max_match_.
min_match()
int v8::internal::RegExpDisjunction::min_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 227 of file regexp-ast.h.
{ return min_match_; }
References min_match_.
RationalizeConsecutiveAtoms()
void v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms (RegExpCompiler * compiler) [private]
Definition at line 839 of file regexp-compiler-tonode.cc.
                                                                            {
  Zone* zone = compiler->zone();
  ZoneList<RegExpTree*>* alternatives = this->alternatives();
  int length = alternatives->length();
  const bool ignore_case = IsIgnoreCase(compiler->flags());
  int write_posn = 0;
  int i = 0;
  while (i < length) {
    RegExpTree* alternative = alternatives->at(i);
    if (!StartsWithAtom(alternative)) {
      alternatives->at(write_posn++) = alternatives->at(i);
      i++;
      continue;
    }
    RegExpAtom* const atom = FirstAtom(alternative);
#ifdef V8_INTL_SUPPORT
    icu::UnicodeString common_prefix(atom->data().at(0));
#else
    unibrow::Mapping<unibrow::Ecma262Canonicalize>* const canonicalize =
        compiler->isolate()->regexp_macro_assembler_canonicalize();
    unibrow::uchar common_prefix = atom->data().at(0);
    if (ignore_case) {
      common_prefix = Canonical(canonicalize, common_prefix);
    }
#endif // V8_INTL_SUPPORT
    int first_with_prefix = i;
    int prefix_length = atom->length();
    i++;
    while (i < length) {
      alternative = alternatives->at(i);
      if (!StartsWithAtom(alternative)) break;
      RegExpAtom* const alt_atom = FirstAtom(alternative);
#ifdef V8_INTL_SUPPORT
      icu::UnicodeString new_prefix(alt_atom->data().at(0));
      if (!Equals(ignore_case, new_prefix, common_prefix)) break;
#else
      unibrow::uchar new_prefix = alt_atom->data().at(0);
      if (!Equals(ignore_case, canonicalize, new_prefix, common_prefix)) break;
#endif // V8_INTL_SUPPORT
      prefix_length = std::min(prefix_length, alt_atom->length());
      i++;
    }
    if (i > first_with_prefix + 2) {
      // Found worthwhile run of alternatives with common prefix of at least one
      // character. The sorting function above did not sort on more than one
      // character for reasons of correctness, but there may still be a longer
      // common prefix if the terms were similar or presorted in the input.
      // Find out how long the common prefix is.
      int run_length = i - first_with_prefix;
      RegExpAtom* const alt_atom =
          FirstAtom(alternatives->at(first_with_prefix));
      alternatives->at(first_with_prefix)->AsAtom();
      for (int j = 1; j < run_length && prefix_length > 1; j++) {
        RegExpAtom* old_atom =
            FirstAtom(alternatives->at(j + first_with_prefix));
        for (int k = 1; k < prefix_length; k++) {
#ifdef V8_INTL_SUPPORT
          if (!CharAtEquals(ignore_case, k, alt_atom, old_atom)) {
#else
          if (!CharAtEquals(ignore_case, canonicalize, k, alt_atom, old_atom)) {
#endif // V8_INTL_SUPPORT
            prefix_length = k;
            break;
          }
        }
      }
      RegExpAtom* prefix =
          zone->New<RegExpAtom>(alt_atom->data().SubVector(0, prefix_length));
      ZoneList<RegExpTree*>* pair = zone->New<ZoneList<RegExpTree*>>(2, zone);
      pair->Add(prefix, zone);
      ZoneList<RegExpTree*>* suffixes =
          zone->New<ZoneList<RegExpTree*>>(run_length, zone);
      for (int j = 0; j < run_length; j++) {
        if (alternatives->at(j + first_with_prefix)->IsAtom()) {
          RegExpAtom* old_atom =
              alternatives->at(j + first_with_prefix)->AsAtom();
          int len = old_atom->length();
          if (len == prefix_length) {
            suffixes->Add(zone->New<RegExpEmpty>(), zone);
          } else {
            RegExpTree* suffix = zone->New<RegExpAtom>(
                old_atom->data().SubVector(prefix_length, len));
            suffixes->Add(suffix, zone);
          }
        } else {
          RegExpText* new_text = zone->New<RegExpText>(zone);
          RegExpText* old_text =
              alternatives->at(j + first_with_prefix)->AsText();
          RegExpAtom* old_atom = old_text->FirstAtom();
          int len = old_atom->length();
          if (len != prefix_length) {
            RegExpAtom* suffix = zone->New<RegExpAtom>(
                old_atom->data().SubVector(prefix_length, len));
            new_text->AddElement(TextElement::Atom(suffix), zone);
          }
          for (int k = 1; k < old_text->elements()->length(); k++) {
            new_text->AddElement(old_text->elements()->at(k), zone);
          }
          if (new_text->elements()->length() != 0) {
            suffixes->Add(new_text, zone);
          } else {
            suffixes->Add(zone->New<RegExpEmpty>(), zone);
          }
        }
      }
      pair->Add(zone->New<RegExpDisjunction>(suffixes), zone);
      alternatives->at(write_posn++) = zone->New<RegExpAlternative>(pair);
    } else {
      // Just copy any non-worthwhile alternatives.
      for (int j = first_with_prefix; j < i; j++) {
        alternatives->at(write_posn++) = alternatives->at(j);
      }
    }
  }
  alternatives->Rewind(write_posn); // Trim end of array.
}
References v8::internal::ZoneList< T >::Add(), v8::internal::RegExpText::AddElement(), v8::internal::ZoneList< T >::at(), v8::base::Vector< T >::at(), v8::internal::TextElement::Atom(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Canonical(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CharAtEquals(), v8::internal::RegExpAtom::data(), v8::internal::RegExpText::elements(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Equals(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::FirstAtom(), v8::internal::RegExpCompiler::flags(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::RegExpCompiler::isolate(), v8::internal::length, v8::internal::RegExpAtom::length(), v8::internal::ZoneList< T >::length(), v8::internal::Zone::New(), v8::internal::Isolate::regexp_macro_assembler_canonicalize(), v8::internal::ZoneList< T >::Rewind(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::StartsWithAtom(), v8::base::Vector< T >::SubVector(), and v8::internal::RegExpCompiler::zone().
SortConsecutiveAtoms()
bool v8::internal::RegExpDisjunction::SortConsecutiveAtoms (RegExpCompiler * compiler) [private]
Definition at line 789 of file regexp-compiler-tonode.cc.
                                                                     {
  ZoneList<RegExpTree*>* alternatives = this->alternatives();
  int length = alternatives->length();
  bool found_consecutive_atoms = false;
  for (int i = 0; i < length; i++) {
    while (i < length) {
      RegExpTree* alternative = alternatives->at(i);
      if (StartsWithAtom(alternative)) break;
      i++;
    }
    // i is length or it is the index of an atom.
    if (i == length) break;
    int first_atom = i;
    i++;
    while (i < length) {
      RegExpTree* alternative = alternatives->at(i);
      if (!StartsWithAtom(alternative)) break;
      i++;
    }
    // Sort atoms to get ones with common prefixes together.
    // This step is more tricky if we are in a case-independent regexp,
    // because it would change /is|I/ to /I|is/, and order matters when
    // the regexp parts don't match only disjoint starting points. To fix
    // this we have a version of CompareFirstChar that uses case-
    // independent character classes for comparison.
    DCHECK_LT(first_atom, alternatives->length());
    DCHECK_LE(i, alternatives->length());
    DCHECK_LE(first_atom, i);
    if (IsIgnoreCase(compiler->flags())) {
#ifdef V8_INTL_SUPPORT
      alternatives->StableSort(CompareFirstCharCaseInsensitive, first_atom,
                               i - first_atom);
#else
      unibrow::Mapping<unibrow::Ecma262Canonicalize>* canonicalize =
          compiler->isolate()->regexp_macro_assembler_canonicalize();
      auto compare_closure = [canonicalize](RegExpTree* const* a,
                                            RegExpTree* const* b) {
        return CompareFirstCharCaseInsensitive(canonicalize, a, b);
      };
      alternatives->StableSort(compare_closure, first_atom, i - first_atom);
#endif // V8_INTL_SUPPORT
    } else {
      alternatives->StableSort(CompareFirstChar, first_atom, i - first_atom);
    }
    if (i - first_atom > 1) found_consecutive_atoms = true;
  }
  return found_consecutive_atoms;
}
References v8::internal::ZoneList< T >::at(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareFirstChar(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareFirstCharCaseInsensitive(), DCHECK_LE, DCHECK_LT, v8::internal::RegExpCompiler::flags(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::RegExpCompiler::isolate(), v8::internal::length, v8::internal::ZoneList< T >::length(), v8::internal::Isolate::regexp_macro_assembler_canonicalize(), v8::internal::ZoneList< T >::StableSort(), and v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::StartsWithAtom().
Member Data Documentation
alternatives_
ZoneList<RegExpTree*>* v8::internal::RegExpDisjunction::alternatives_ [private]
Definition at line 235 of file regexp-ast.h.
Referenced by alternatives().
max_match_
int v8::internal::RegExpDisjunction::max_match_ [private]
Definition at line 237 of file regexp-ast.h.
Referenced by max_match(), and RegExpDisjunction().
min_match_
int v8::internal::RegExpDisjunction::min_match_ [private]
Definition at line 236 of file regexp-ast.h.
Referenced by min_match(), and RegExpDisjunction().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-ast.cc
/mnt/V8SourceCode/src/regexp/regexp-compiler-tonode.cc