v8::internal::maglev::TaggedNotEqual Class Reference
#include <maglev-ir.h>
Public Member Functions
TaggedNotEqual (uint64_t bitfield)
Input & lhs ()
Input & rhs ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputValueNodeT< 2, TaggedNotEqual >
Additional Inherited Members
Detailed Description
Definition at line 5018 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::TaggedNotEqual::Base = FixedInputValueNodeT<2, TaggedNotEqual> [private]
Definition at line 5019 of file maglev-ir.h.
Constructor & Destructor Documentation
TaggedNotEqual()
v8::internal::maglev::TaggedNotEqual::TaggedNotEqual (uint64_t bitfield) [inline], [explicit]
Definition at line 5022 of file maglev-ir.h.
: Base(bitfield) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::TaggedNotEqual::GenerateCode (MaglevAssembler * , const ProcessingState &)
lhs()
Input& v8::internal::maglev::TaggedNotEqual::lhs () [inline]
Definition at line 5027 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::TaggedNotEqual::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 5038 of file maglev-ir.h.
{}
rhs()
Input& v8::internal::maglev::TaggedNotEqual::rhs () [inline]
Definition at line 5028 of file maglev-ir.h.
{ return Node::input(1); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::TaggedNotEqual::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::TaggedNotEqual::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 5024 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h