v8::internal::interpreter::BytecodeRegisterAllocator::Observer Class Reference
#include <bytecode-register-allocator.h>
Public Member Functions
virtual ~Observer ()=default
virtual void RegisterAllocateEvent (Register reg)=0
virtual void RegisterListAllocateEvent (RegisterList reg_list)=0
virtual void RegisterListFreeEvent (RegisterList reg_list)=0
virtual void RegisterFreeEvent (Register reg_list)=0
Detailed Description
Definition at line 18 of file bytecode-register-allocator.h.
Constructor & Destructor Documentation
 Observer()
virtual v8::internal::interpreter::BytecodeRegisterAllocator::Observer::~Observer () [virtual], [default]
Member Function Documentation
RegisterAllocateEvent()
virtual void v8::internal::interpreter::BytecodeRegisterAllocator::Observer::RegisterAllocateEvent (Register reg) [pure virtual]
Referenced by v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister().
RegisterFreeEvent()
virtual void v8::internal::interpreter::BytecodeRegisterAllocator::Observer::RegisterFreeEvent (Register reg_list) [pure virtual]
Referenced by v8::internal::interpreter::BytecodeRegisterAllocator::ReleaseRegister().
RegisterListAllocateEvent()
virtual void v8::internal::interpreter::BytecodeRegisterAllocator::Observer::RegisterListAllocateEvent (RegisterList reg_list) [pure virtual]
Referenced by v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList().
RegisterListFreeEvent()
virtual void v8::internal::interpreter::BytecodeRegisterAllocator::Observer::RegisterListFreeEvent (RegisterList reg_list) [pure virtual]
Referenced by v8::internal::interpreter::BytecodeRegisterAllocator::ReleaseRegisters().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-register-allocator.h