v8::internal::JSObject Class Reference
#include <js-objects.h>
Classes
class BodyDescriptor
class FastBodyDescriptor
Public Types
enum AccessorInfoHandling { FORCE_FIELD
, DONT_FORCE_FIELD
 }
Public Member Functions
Tagged< FixedArrayBase > elements (PtrComprCageBase cage_base, AcquireLoadTag tag) const =delete
void set_elements (Tagged< FixedArrayBase > value, ReleaseStoreTag tag, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)=delete
void initialize_elements ()
bool HasEnumerableElements ()
bool WouldConvertToSlowElements (uint32_t index)
bool MayHaveEmbedderFields () const
int GetEmbedderFieldsStartOffset ()
int GetEmbedderFieldCount () const
int GetEmbedderFieldOffset (int index)
Tagged< Object > GetEmbedderField (int index)
void SetEmbedderField (int index, Tagged< Object > value)
void SetEmbedderField (int index, Tagged< Smi > value)
bool IsDroppableApiObject () const
void RequireSlowElements (Tagged< NumberDictionary > dictionary)
Tagged< JSAny > RawFastPropertyAt (FieldIndex index) const
Tagged< JSAny > RawFastPropertyAt (PtrComprCageBase cage_base, FieldIndex index) const
Tagged< JSAny > RawFastPropertyAt (FieldIndex index, SeqCstAccessTag tag) const
Tagged< JSAny > RawFastPropertyAt (PtrComprCageBase cage_base, FieldIndex index, SeqCstAccessTag tag) const
std::optional< Tagged< Object > > RawInobjectPropertyAt (PtrComprCageBase cage_base, Tagged< Map > original_map, FieldIndex index) const
void FastPropertyAtPut (FieldIndex index, Tagged< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void FastPropertyAtPut (FieldIndex index, Tagged< Object > value, SeqCstAccessTag tag)
void RawFastInobjectPropertyAtPut (FieldIndex index, Tagged< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void RawFastInobjectPropertyAtPut (FieldIndex index, Tagged< Object > value, SeqCstAccessTag tag)
void WriteToField (InternalIndex descriptor, PropertyDetails details, Tagged< Object > value)
Tagged< Object > RawFastInobjectPropertyAtSwap (FieldIndex index, Tagged< Object > value, SeqCstAccessTag tag)
Tagged< Object > RawFastPropertyAtSwap (FieldIndex index, Tagged< Object > value, SeqCstAccessTag tag)
Tagged< Object > RawFastPropertyAtCompareAndSwap (FieldIndex index, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag)
Tagged< Object > RawFastInobjectPropertyAtCompareAndSwap (FieldIndex index, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag)
int GetInObjectPropertyOffset (int index)
Tagged< Object > InObjectPropertyAt (int index)
Tagged< Object > InObjectPropertyAtPut (int index, Tagged< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void InitializeBody (Tagged< Map > map, int start_offset, bool is_slack_tracking_in_progress, MapWord filler_map, Tagged< Object > undefined_value)
bool ReferencesObject (Tagged< Object > obj)
void JSObjectShortPrint (StringStream *accumulator)
void PrintInstanceMigration (FILE *file, Tagged< Map > original_map, Tagged< Map > new_map)
Tagged< Object > SlowReverseLookup (Tagged< Object > value)
int GetFastElementsUsage ()
template<PropertyAttributes attrs>
Maybe< bool > PreventExtensionsWithTransition (Isolate *isolate, DirectHandle< JSObject > object, ShouldThrow should_throw)
Static Public Member Functions
static bool IsUnmodifiedApiObject (FullObjectSlot o)
static V8_EXPORT_PRIVATE V8_WARN_UNUSED_RESULT MaybeHandle< JSObject > New (DirectHandle< JSFunction > constructor, DirectHandle< JSReceiver > new_target, DirectHandle< AllocationSite > site, NewJSObjectType=NewJSObjectType::kNoAPIWrapper)
static MaybeDirectHandle< JSObject > NewWithMap (Isolate *isolate, DirectHandle< Map > initial_map, DirectHandle< AllocationSite > site, NewJSObjectType=NewJSObjectType::kNoAPIWrapper)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSObject > ObjectCreate (Isolate *isolate, DirectHandle< JSPrototype > prototype)
static void SetMapAndElements (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Map > map, DirectHandle< FixedArrayBase > elements)
static void EnsureWritableFastElements (Isolate *isolate, DirectHandle< JSObject > object)
V8_NOINLINE static V8_PRESERVE_MOST void MakeElementsWritable (Isolate *isolate, DirectHandle< JSObject > object)
static V8_WARN_UNUSED_RESULT Maybe< InterceptorResult > SetPropertyWithInterceptor (LookupIterator *it, Maybe< ShouldThrow > should_throw, DirectHandle< Object > value)
template<typename T , template< typename > typename HandleType>
requires(std::is_convertible_v< HandleType< T >, DirectHandle< T >>) V8_WARN_UNUSED_RESULT static inline typename HandleType< Object > static V8_WARN_UNUSED_RESULT Maybe< bool > DefineOwnPropertyIgnoreAttributes (LookupIterator *it, DirectHandle< Object > value, PropertyAttributes attributes, Maybe< ShouldThrow > should_throw, AccessorInfoHandling handling=DONT_FORCE_FIELD, EnforceDefineSemantics semantics=EnforceDefineSemantics::kSet, StoreOrigin store_origin=StoreOrigin::kNamed)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > V8_EXPORT_PRIVATE SetOwnPropertyIgnoreAttributes (DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > value, PropertyAttributes attributes)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > SetOwnElementIgnoreAttributes (DirectHandle< JSObject > object, size_t index, DirectHandle< Object > value, PropertyAttributes attributes)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > DefinePropertyOrElementIgnoreAttributes (DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > value, PropertyAttributes attributes=NONE)
static V8_WARN_UNUSED_RESULT Maybe< bool > CreateDataProperty (Isolate *isolate, DirectHandle< JSObject > object, PropertyKey key, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw=Just(kDontThrow))
static V8_EXPORT_PRIVATE void AddProperty (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > value, PropertyAttributes attributes)
static void AddProperty (Isolate *isolate, DirectHandle< JSObject > object, const char *name, DirectHandle< Object > value, PropertyAttributes attributes)
static V8_EXPORT_PRIVATE Maybe< bool > AddDataElement (Isolate *isolate, DirectHandle< JSObject > receiver, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes)
static void AllocateStorageForMap (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Map > map)
static void MigrateInstance (Isolate *isolate, DirectHandle< JSObject > instance)
static bool TryMigrateInstance (Isolate *isolate, DirectHandle< JSObject > instance)
static void SetNormalizedProperty (DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > value, PropertyDetails details)
static void SetNormalizedElement (DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyDetails details)
static void OptimizeAsPrototype (DirectHandle< JSObject > object, bool enable_setup_mode=true)
static void ReoptimizeIfPrototype (DirectHandle< JSObject > object)
static void MakePrototypesFast (DirectHandle< Object > receiver, WhereToStart where_to_start, Isolate *isolate)
static void LazyRegisterPrototypeUser (DirectHandle< Map > user, Isolate *isolate)
static void UpdatePrototypeUserRegistration (DirectHandle< Map > old_map, DirectHandle< Map > new_map, Isolate *isolate)
static bool UnregisterPrototypeUser (DirectHandle< Map > user, Isolate *isolate)
static Tagged< Map > InvalidatePrototypeChains (Tagged< Map > map)
static void InvalidatePrototypeValidityCell (Tagged< JSGlobalObject > global)
static void NotifyMapChange (DirectHandle< Map > old_map, DirectHandle< Map > new_map, Isolate *isolate)
static bool PrototypeHasNoElements (Isolate *isolate, Tagged< JSObject > object)
static void PrototypeRegistryCompactionCallback (Tagged< HeapObject > value, int old_index, int new_index)
static V8_WARN_UNUSED_RESULT Maybe< PropertyAttributes > GetPropertyAttributesWithInterceptor (LookupIterator *it)
static V8_WARN_UNUSED_RESULT Maybe< PropertyAttributes > GetPropertyAttributesWithFailedAccessCheck (LookupIterator *it)
static V8_EXPORT_PRIVATE MaybeDirectHandle< Object > DefineOwnAccessorIgnoreAttributes (DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > getter, DirectHandle< Object > setter, PropertyAttributes attributes)
static MaybeDirectHandle< Object > DefineOwnAccessorIgnoreAttributes (LookupIterator *it, DirectHandle< Object > getter, DirectHandle< Object > setter, PropertyAttributes attributes)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > SetAccessor (DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< AccessorInfo > info, PropertyAttributes attributes)
static V8_WARN_UNUSED_RESULT Maybe< bool > CheckIfCanDefineAsConfigurable (Isolate *isolate, LookupIterator *it, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT MaybeHandle< JSAny > GetPropertyWithInterceptor (LookupIterator *it, bool *done)
static void ValidateElements (Isolate *isolate, Tagged< JSObject > object)
static void EnsureCanContainHeapObjectElements (Isolate *isolate, DirectHandle< JSObject > obj)
template<typename TSlot >
static void EnsureCanContainElements (Isolate *isolate, DirectHandle< JSObject > object, TSlot elements, uint32_t count, EnsureElementsMode mode)
static void EnsureCanContainElements (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > elements, uint32_t length, EnsureElementsMode mode)
static void EnsureCanContainElements (Isolate *isolate, DirectHandle< JSObject > object, JavaScriptArguments *arguments, uint32_t arg_count, EnsureElementsMode mode)
static constexpr uint32_t NewElementsCapacity (uint32_t old_capacity)
template<AllocationSiteUpdateMode update_or_check = AllocationSiteUpdateMode::kUpdate>
static bool UpdateAllocationSite (Isolate *isolate, DirectHandle< JSObject > object, ElementsKind to_kind)
static V8_WARN_UNUSED_RESULT Maybe< bool > HasRealNamedProperty (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Name > name)
static V8_WARN_UNUSED_RESULT Maybe< bool > HasRealElementProperty (Isolate *isolate, DirectHandle< JSObject > object, uint32_t index)
static V8_WARN_UNUSED_RESULT Maybe< bool > HasRealNamedCallbackProperty (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Name > name)
static V8_EXPORT_PRIVATE int GetHeaderSize (InstanceType instance_type, bool function_has_prototype_slot=false)
static int GetHeaderSize (Tagged< Map > map)
static bool MayHaveEmbedderFields (Tagged< Map > map)
static int GetEmbedderFieldsStartOffset (Tagged< Map > map)
static int GetEmbedderFieldCount (Tagged< Map > map)
static bool IsDroppableApiObject (Tagged< Map >)
static DirectHandle< Map > GetElementsTransitionMap (Isolate *isolate, DirectHandle< JSObject > object, ElementsKind to_kind)
static V8_EXPORT_PRIVATE void TransitionElementsKind (Isolate *isolate, DirectHandle< JSObject > object, ElementsKind to_kind)
static V8_EXPORT_PRIVATE void MigrateToMap (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Map > new_map, int expected_additional_properties=0)
static void ForceSetPrototype (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< JSPrototype > proto)
static V8_EXPORT_PRIVATE void NormalizeProperties (Isolate *isolate, DirectHandle< JSObject > object, PropertyNormalizationMode mode, int expected_additional_properties, bool use_cache, const char *reason)
static V8_EXPORT_PRIVATE void NormalizeProperties (Isolate *isolate, DirectHandle< JSObject > object, PropertyNormalizationMode mode, int expected_additional_properties, const char *reason)
static V8_EXPORT_PRIVATE DirectHandle< NumberDictionary > NormalizeElements (Isolate *isolate, DirectHandle< JSObject > object)
static V8_EXPORT_PRIVATE void MigrateSlowToFast (DirectHandle< JSObject > object, int unused_property_fields, const char *reason)
static Handle< Object > DictionaryPropertyAt (Isolate *isolate, DirectHandle< JSObject > object, InternalIndex dict_index)
static std::optional< Tagged< Object > > DictionaryPropertyAt (DirectHandle< JSObject > object, InternalIndex dict_index, Heap *heap)
static Handle< JSAny > FastPropertyAt (Isolate *isolate, DirectHandle< JSObject > object, Representation representation, FieldIndex index)
static DirectHandle< JSAny > FastPropertyAt (Isolate *isolate, DirectHandle< JSObject > object, Representation representation, FieldIndex index, SeqCstAccessTag tag)
static V8_WARN_UNUSED_RESULT Maybe< bool > SetPrototype (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Object > value, bool from_javascript, ShouldThrow should_throw)
static void SetImmutableProto (Isolate *isolate, DirectHandle< JSObject > object)
static V8_WARN_UNUSED_RESULT Maybe< bool > TestIntegrityLevel (Isolate *isolate, DirectHandle< JSObject > object, IntegrityLevel lvl)
static V8_WARN_UNUSED_RESULT Maybe< bool > PreventExtensions (Isolate *isolate, DirectHandle< JSObject > object, ShouldThrow should_throw)
static bool IsExtensible (Isolate *isolate, DirectHandle< JSObject > object)
static MaybeDirectHandle< Object > ReadFromOptionsBag (DirectHandle< Object > options, DirectHandle< String > option_name, Isolate *isolate)
static void PrintElementsTransition (FILE *file, DirectHandle< JSObject > object, ElementsKind from_kind, DirectHandle< FixedArrayBase > from_elements, ElementsKind to_kind, DirectHandle< FixedArrayBase > to_elements)
template<typename Dictionary >
static void ApplyAttributesToDictionary (Isolate *isolate, ReadOnlyRoots roots, DirectHandle< Dictionary > dictionary, const PropertyAttributes attributes)
Static Public Attributes
static const uint32_t kMinAddedElementsCapacity = 16
static constexpr uint32_t kMaxElementCount = kMaxUInt32
static constexpr uint32_t kMaxElementIndex = kMaxElementCount - 1
static const uint32_t kMaxGap = 1024
static const int kMaxUncheckedFastElementsLength = 5000
static const int kMaxUncheckedOldFastElementsLength = 500
static const int kInitialGlobalObjectUnusedPropertiesCount = 4
static const int kMaxInstanceSize = 255 * kTaggedSize
static const int kMapCacheSize = 128
static const int kFieldsAdded = 3
static const int kMaxInObjectProperties
static const int kMaxFirstInobjectPropertyOffset
static const int kMaxEmbedderFields
static constexpr int kMaxJSApiObjectInObjectProperties
static constexpr int kMaxJSApiObjectEmbedderFields
Private Member Functions
bool ReferencesObjectFromElements (Tagged< FixedArray > elements, ElementsKind kind, Tagged< Object > object)
Tagged< Object > RawFastPropertyAtCompareAndSwapInternal (FieldIndex index, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag)
Static Private Member Functions
static V8_WARN_UNUSED_RESULT MaybeHandle< JSAny > GetPropertyWithFailedAccessCheck (LookupIterator *it)
static V8_WARN_UNUSED_RESULT Maybe< bool > SetPropertyWithFailedAccessCheck (LookupIterator *it, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT Maybe< InterceptorResult > DeletePropertyWithInterceptor (LookupIterator *it, ShouldThrow should_throw)
template<PropertyAttributes attrs>
static V8_WARN_UNUSED_RESULT Maybe< bool > PreventExtensionsWithTransition (Isolate *isolate, DirectHandle< JSObject > object, ShouldThrow should_throw)
Friends
class JSReceiver
class Object
Detailed Description
Definition at line 371 of file js-objects.h.
Member Enumeration Documentation
AccessorInfoHandling
enum v8::internal::JSObject::AccessorInfoHandling
Enumerator
FORCE_FIELD
DONT_FORCE_FIELD
Definition at line 480 of file js-objects.h.
{ FORCE_FIELD, DONT_FORCE_FIELD };
Member Function Documentation
AddDataElement()
Maybe< bool > v8::internal::JSObject::AddDataElement (Isolate * isolate, DirectHandle< JSObject > receiver, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes) [static]
Definition at line 5450 of file js-objects.cc.
                                                                    {
  DCHECK(object->map(isolate)->is_extensible());
  uint32_t old_length = 0;
  uint32_t new_capacity = 0;
  if (IsJSArray(*object, isolate)) {
    CHECK(Object::ToArrayLength(Cast<JSArray>(*object)->length(), &old_length));
  }
  ElementsKind kind = object->GetElementsKind(isolate);
  Tagged<FixedArrayBase> elements = object->elements(isolate);
  ElementsKind dictionary_kind = DICTIONARY_ELEMENTS;
  if (IsSloppyArgumentsElementsKind(kind)) {
    elements = Cast<SloppyArgumentsElements>(elements)->arguments();
    dictionary_kind = SLOW_SLOPPY_ARGUMENTS_ELEMENTS;
  } else if (IsStringWrapperElementsKind(kind)) {
    dictionary_kind = SLOW_STRING_WRAPPER_ELEMENTS;
  }
  if (attributes != NONE) {
    kind = dictionary_kind;
  } else if (IsNumberDictionary(elements, isolate)) {
    kind = ShouldConvertToFastElements(
               *object, Cast<NumberDictionary>(elements), index, &new_capacity)
               ? BestFittingFastElementsKind(*object)
               : dictionary_kind;
  } else if (ShouldConvertToSlowElements(
                 *object, static_cast<uint32_t>(elements->length()), index,
                 &new_capacity)) {
    kind = dictionary_kind;
  }
  ElementsKind to = Object::OptimalElementsKind(*value, isolate);
  if (IsHoleyElementsKind(kind) || !IsJSArray(*object, isolate) ||
      index > old_length) {
    to = GetHoleyElementsKind(to);
    kind = GetHoleyElementsKind(kind);
  }
  to = GetMoreGeneralElementsKind(kind, to);
  ElementsAccessor* accessor = ElementsAccessor::ForKind(to);
  MAYBE_RETURN(
      accessor->Add(isolate, object, index, value, attributes, new_capacity),
      Nothing<bool>());
  if (IsJSArray(*object, isolate) && index >= old_length) {
    DirectHandle<Number> new_length =
        isolate->factory()->NewNumberFromUint(index + 1);
    Cast<JSArray>(*object)->set_length(*new_length);
  }
  return Just(true);
}
References v8::internal::ElementsAccessor::Add(), v8::internal::BestFittingFastElementsKind(), v8::internal::Cast< NumberDictionary >(), CHECK, v8::internal::DCHECK(), v8::internal::DICTIONARY_ELEMENTS, elements(), v8::internal::Isolate::factory(), v8::internal::ElementsAccessor::ForKind(), v8::internal::GetHoleyElementsKind(), v8::internal::GetMoreGeneralElementsKind(), v8::internal::index, v8::internal::IsHoleyElementsKind(), v8::internal::IsSloppyArgumentsElementsKind(), v8::internal::IsStringWrapperElementsKind(), v8::Just(), MAYBE_RETURN, v8::internal::FactoryBase< Impl >::NewNumberFromUint(), v8::internal::NONE, v8::internal::Object::OptimalElementsKind(), v8::internal::ShouldConvertToFastElements(), v8::internal::ShouldConvertToSlowElements(), v8::internal::SLOW_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, v8::internal::Object::ToArrayLength(), and v8::internal::value.
Referenced by v8::internal::Object::AddDataProperty(), v8::internal::anonymous_namespace{intl-objects.cc}::CreateArrayFromList(), v8::internal::anonymous_namespace{intl-objects.cc}::InnerAddElement(), v8::internal::wasm::JSPrototypesSetup::InstallExport(), and v8::internal::wasm::InstanceBuilder::ProcessExports().
AddProperty() [1/2]
void v8::internal::JSObject::AddProperty (Isolate * isolate, DirectHandle< JSObject > object, const char * name, DirectHandle< Object > value, PropertyAttributes attributes) [static]
Definition at line 3661 of file js-objects.cc.
                                                          {
  JSObject::AddProperty(isolate, object,
                        isolate->factory()->InternalizeUtf8String(name), value,
                        attributes);
}
References AddProperty(), v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::name, and v8::internal::value.
AddProperty() [2/2]
void v8::internal::JSObject::AddProperty (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > value, PropertyAttributes attributes) [static]
Definition at line 3634 of file js-objects.cc.
                                                          {
  name = isolate->factory()->InternalizeName(name);
  if (TryFastAddDataProperty(isolate, object, name, value, attributes)) {
    return;
  }
  LookupIterator it(isolate, object, name, object,
                    LookupIterator::OWN_SKIP_INTERCEPTOR);
  CHECK_NE(LookupIterator::ACCESS_CHECK, it.state());
#ifdef DEBUG
  uint32_t index;
  DCHECK(!IsJSProxy(*object));
  DCHECK(!IsWasmObject(*object));
  DCHECK(!name->AsArrayIndex(&index));
  Maybe<PropertyAttributes> maybe = GetPropertyAttributes(&it);
  DCHECK(maybe.IsJust());
  DCHECK(!it.IsFound());
  DCHECK(object->map()->is_extensible() || name->IsPrivate());
#endif
  CHECK(Object::AddDataProperty(&it, value, attributes,
                                Just(ShouldThrow::kThrowOnError),
                                StoreOrigin::kNamed)
            .IsJust());
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::Object::AddDataProperty(), CHECK, CHECK_NE, v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::index, v8::internal::LookupIterator::IsFound(), v8::Maybe< T >::IsJust(), v8::internal::IsWasmObject(), v8::Just(), v8::internal::kNamed, v8::internal::kThrowOnError, v8::internal::name, v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR, v8::internal::LookupIterator::state(), v8::internal::anonymous_namespace{js-objects.cc}::TryFastAddDataProperty(), and v8::internal::value.
Referenced by v8::internal::Intl::AddElement(), v8::internal::anonymous_namespace{memory-measurement.cc}::MemoryMeasurementResultBuilder::AddProperty(), AddProperty(), v8::internal::BUILTIN(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxy::Create(), v8::internal::ApiNatives::CreateApiFunction(), v8::internal::Genesis::CreateArrayBuffer(), v8::internal::Genesis::CreateAsyncIteratorMaps(), v8::internal::Genesis::CreateIteratorMaps(), v8::internal::JSAtomicsMutex::CreateResultObject(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateSharedObjectConstructor(), v8::internal::JsonStringifier::CurrentHolder(), v8::internal::interpreter::Interpreter::GetDispatchCountersObject(), v8::internal::wasm::GetExports(), v8::internal::wasm::GetImports(), v8::internal::anonymous_namespace{runtime-debug.cc}::GetJSPositionInfo(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::GetObject(), v8::internal::wasm::GetTypeForFunction(), v8::internal::wasm::GetTypeForGlobal(), v8::internal::wasm::GetTypeForTable(), v8::internal::Genesis::InitializeConsole(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InitializeGlobal_sharedarraybuffer(), v8::internal::Genesis::InitializeIteratorFunctions(), v8::internal::anonymous_namespace{intl-objects.cc}::InnerAddElement(), v8::internal::Isolate::InstallConditionalFeatures(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallConstant(), v8::internal::anonymous_namespace{builtins-console.cc}::InstallContextFunction(), v8::internal::InstallError(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunction(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunctionAtSymbol(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunctionWithBuiltinId(), v8::internal::Genesis::InstallSpecialObjects(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallToStringTag(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallTrueValuedProperty(), v8::internal::InstallWithIntrinsicDefaultProto(), v8::internal::JsonParseInternalizer::Internalize(), v8::internal::anonymous_namespace{runtime-debug.cc}::MakeRangeObject(), v8::internal::Factory::NewFunctionPrototype(), v8::internal::wasm::WasmInterpreterThread::RaiseException(), v8::internal::JSListFormat::ResolvedOptions(), v8::internal::JSRelativeTimeFormat::ResolvedOptions(), v8::internal::JSSegmenter::ResolvedOptions(), v8::internal::JSV8BreakIterator::ResolvedOptions(), v8::internal::RUNTIME_FUNCTION(), v8::internal::SimpleInstallFunction(), v8::internal::Isolate::StackOverflow(), v8::internal::anonymous_namespace{factory.cc}::ThrowInvalidEncodedStringBytes(), and v8::internal::Genesis::TransferNamedProperties().
AllocateStorageForMap()
void v8::internal::JSObject::AllocateStorageForMap (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Map > map) [static]
Definition at line 3507 of file js-objects.cc.
                                                            {
  DCHECK(object->map()->GetInObjectProperties() ==
         map->GetInObjectProperties());
  ElementsKind obj_kind = object->map()->elements_kind();
  ElementsKind map_kind = map->elements_kind();
  if (map_kind != obj_kind) {
    ElementsKind to_kind = GetMoreGeneralElementsKind(map_kind, obj_kind);
    if (IsDictionaryElementsKind(obj_kind)) {
      to_kind = obj_kind;
    }
    if (IsDictionaryElementsKind(to_kind)) {
      NormalizeElements(isolate, object);
    } else {
      TransitionElementsKind(isolate, object, to_kind);
    }
    map = MapUpdater{isolate, map}.ReconfigureElementsKind(to_kind);
  }
  int number_of_fields = map->NumberOfFields(ConcurrencyMode::kSynchronous);
  int inobject = map->GetInObjectProperties();
  int unused = map->UnusedPropertyFields();
  int total_size = number_of_fields + unused;
  int external = total_size - inobject;
  // Allocate mutable double boxes if necessary. It is always necessary if we
  // have external properties, but is also necessary if we only have inobject
  // properties but don't unbox double fields.
  DirectHandle<DescriptorArray> descriptors(map->instance_descriptors(isolate),
                                            isolate);
  DirectHandle<FixedArray> storage =
      isolate->factory()->NewFixedArray(inobject);
  DirectHandle<PropertyArray> array =
      isolate->factory()->NewPropertyArray(external);
  for (InternalIndex i : map->IterateOwnDescriptors()) {
    PropertyDetails details = descriptors->GetDetails(i);
    Representation representation = details.representation();
    if (!representation.IsDouble()) continue;
    FieldIndex index = FieldIndex::ForDetails(*map, details);
    auto box = isolate->factory()->NewHeapNumberWithHoleNaN();
    if (index.is_inobject()) {
      storage->set(index.property_index(), *box);
    } else {
      array->set(index.outobject_array_index(), *box);
    }
  }
  object->SetProperties(*array);
  for (int i = 0; i < inobject; i++) {
    FieldIndex index = FieldIndex::ForPropertyIndex(*map, i);
    Tagged<Object> value = storage->get(i);
    object->FastPropertyAtPut(index, value);
  }
  object->set_map(isolate, *map, kReleaseStore);
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::FieldIndex::ForDetails(), v8::internal::FieldIndex::ForPropertyIndex(), v8::internal::GetMoreGeneralElementsKind(), v8::internal::index, v8::internal::IsDictionaryElementsKind(), v8::internal::Representation::IsDouble(), v8::kReleaseStore, v8::internal::kSynchronous, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::FactoryBase< Impl >::NewHeapNumberWithHoleNaN(), v8::internal::Factory::NewPropertyArray(), NormalizeElements(), v8::internal::PropertyDetails::representation(), TransitionElementsKind(), and v8::internal::value.
Referenced by v8::internal::CommitProperties().
ApplyAttributesToDictionary()
template<typename Dictionary >
template void v8::internal::JSObject::ApplyAttributesToDictionary (Isolate * isolate, ReadOnlyRoots roots, DirectHandle< Dictionary > dictionary, const PropertyAttributes attributes) [static]
Definition at line 4380 of file js-objects.cc.
                                         {
  for (InternalIndex i : dictionary->IterateEntries()) {
    Tagged<Object> k;
    if (!dictionary->ToKey(roots, i, &k)) continue;
    if (Object::FilterKey(k, ALL_PROPERTIES)) continue;
    PropertyDetails details = dictionary->DetailsAt(i);
    int attrs = attributes;
    // READ_ONLY is an invalid attribute for JS setters/getters.
    if ((attributes & READ_ONLY) && details.kind() == PropertyKind::kAccessor) {
      Tagged<Object> v = dictionary->ValueAt(i);
      if (IsAccessorPair(v)) attrs &= ~READ_ONLY;
    }
    details = details.CopyAddAttributes(PropertyAttributesFromInt(attrs));
    dictionary->DetailsAtPut(i, details);
  }
}
References v8::internal::ALL_PROPERTIES, v8::internal::PropertyDetails::CopyAddAttributes(), v8::internal::Object::FilterKey(), v8::internal::kAccessor, v8::internal::PropertyDetails::kind(), v8::internal::PropertyAttributesFromInt(), and v8::internal::READ_ONLY.
Referenced by PreventExtensionsWithTransition(), v8::internal::anonymous_namespace{elements.cc}::FastNonextensibleObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl(), and v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl().
CheckIfCanDefineAsConfigurable()
Maybe< bool > v8::internal::JSObject::CheckIfCanDefineAsConfigurable (Isolate * isolate, LookupIterator * it, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw) [static]
Definition at line 4837 of file js-objects.cc.
                                     {
  DCHECK(IsJSObject(*it->GetReceiver()));
  if (it->IsFound()) {
    Maybe<PropertyAttributes> attributes = GetPropertyAttributes(it);
    MAYBE_RETURN(attributes, Nothing<bool>());
    if (attributes.FromJust() != ABSENT) {
      if ((attributes.FromJust() & DONT_DELETE) != 0) {
        RETURN_FAILURE(
            isolate, GetShouldThrow(isolate, should_throw),
            NewTypeError(MessageTemplate::kRedefineDisallowed, it->GetName()));
      }
      return Just(true);
    }
    // Property does not exist, check object extensibility.
  }
  if (!JSObject::IsExtensible(isolate, Cast<JSObject>(it->GetReceiver()))) {
    RETURN_FAILURE(
        isolate, GetShouldThrow(isolate, should_throw),
        NewTypeError(MessageTemplate::kDefineDisallowed, it->GetName()));
  }
  return Just(true);
}
References v8::internal::ABSENT, v8::internal::DCHECK(), v8::internal::DONT_DELETE, v8::Maybe< T >::FromJust(), v8::internal::LookupIterator::GetName(), v8::internal::LookupIterator::GetReceiver(), v8::internal::GetShouldThrow(), IsExtensible(), v8::internal::LookupIterator::IsFound(), v8::Just(), MAYBE_RETURN, and RETURN_FAILURE.
Referenced by CreateDataProperty(), DefineOwnPropertyIgnoreAttributes(), SetAccessor(), and v8::internal::StoreIC::Store().
CreateDataProperty()
Maybe< bool > v8::internal::JSObject::CreateDataProperty (Isolate * isolate, DirectHandle< JSObject > object, PropertyKey key, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw = Just(kDontThrow)) [static]
Definition at line 4169 of file js-objects.cc.
                                                                          {
  if (!key.is_element()) {
    if (TryFastAddDataProperty(isolate, object, key.name(), value, NONE)) {
      return Just(true);
    }
  }
  LookupIterator it(isolate, object, key, LookupIterator::OWN);
  Maybe<bool> can_define = JSObject::CheckIfCanDefineAsConfigurable(
      isolate, &it, value, should_throw);
  if (can_define.IsNothing() || !can_define.FromJust()) {
    return can_define;
  }
  RETURN_ON_EXCEPTION_VALUE(isolate,
                            DefineOwnPropertyIgnoreAttributes(&it, value, NONE),
                            Nothing<bool>());
  return Just(true);
}
References CheckIfCanDefineAsConfigurable(), DefineOwnPropertyIgnoreAttributes(), v8::Maybe< T >::FromJust(), v8::Maybe< T >::IsNothing(), v8::Just(), v8::internal::key, v8::internal::NONE, v8::internal::LookupIterator::OWN, RETURN_ON_EXCEPTION_VALUE, v8::internal::anonymous_namespace{js-objects.cc}::TryFastAddDataProperty(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{property-descriptor.cc}::CreateDataProperty(), v8::internal::JSReceiver::CreateDataProperty(), and v8::Object::CreateDataProperty().
DefineOwnAccessorIgnoreAttributes() [1/2]
MaybeDirectHandle< Object > v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes (DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > getter, DirectHandle< Object > setter, PropertyAttributes attributes) [static]
Definition at line 4760 of file js-objects.cc.
                                   {
  Isolate* isolate = Isolate::Current();
  PropertyKey key(isolate, name);
  LookupIterator it(isolate, object, key, LookupIterator::OWN_SKIP_INTERCEPTOR);
  return DefineOwnAccessorIgnoreAttributes(&it, getter, setter, attributes);
}
References v8::internal::Isolate::Current(), v8::internal::key, v8::internal::name, v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR, and v8::internal::setter.
Referenced by v8::internal::anonymous_namespace{api-natives.cc}::DefineAccessorProperty(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleInstallGetter(), v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleInstallGetterSetter(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
DefineOwnAccessorIgnoreAttributes() [2/2]
MaybeDirectHandle< Object > v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes (LookupIterator * it, DirectHandle< Object > getter, DirectHandle< Object > setter, PropertyAttributes attributes) [static]
Definition at line 4771 of file js-objects.cc.
                                                                {
  Isolate* isolate = it->isolate();
  it->UpdateProtector();
  while (it->state() == LookupIterator::ACCESS_CHECK) {
    if (!it->HasAccess()) {
      RETURN_ON_EXCEPTION(
          isolate, isolate->ReportFailedAccessCheck(it->GetHolder<JSObject>()));
      UNREACHABLE();
    }
    it->Next();
  }
  auto object = Cast<JSObject>(it->GetReceiver());
  // Ignore accessors on typed arrays.
  if (it->IsElement() && object->HasTypedArrayOrRabGsabTypedArrayElements()) {
    return it->factory()->undefined_value();
  }
  DCHECK(IsCallable(*getter) || IsUndefined(*getter, isolate) ||
         IsNull(*getter, isolate) || IsFunctionTemplateInfo(*getter));
  DCHECK(IsCallable(*setter) || IsUndefined(*setter, isolate) ||
         IsNull(*setter, isolate) || IsFunctionTemplateInfo(*setter));
  it->TransitionToAccessorProperty(getter, setter, attributes);
  return isolate->factory()->undefined_value();
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::LookupIterator::factory(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetReceiver(), v8::internal::LookupIterator::HasAccess(), v8::internal::LookupIterator::IsElement(), v8::internal::IsNull(), v8::internal::LookupIterator::isolate(), v8::internal::LookupIterator::Next(), v8::internal::Isolate::ReportFailedAccessCheck(), RETURN_ON_EXCEPTION, v8::internal::setter, v8::internal::LookupIterator::state(), v8::internal::LookupIterator::TransitionToAccessorProperty(), v8::internal::UNREACHABLE(), and v8::internal::LookupIterator::UpdateProtector().
DefineOwnPropertyIgnoreAttributes()
template<typename T , template< typename > typename HandleType>
Maybe< bool > v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes (LookupIterator * it, DirectHandle< Object > value, PropertyAttributes attributes, Maybe< ShouldThrow > should_throw, AccessorInfoHandling handling = DONT_FORCE_FIELD, EnforceDefineSemantics semantics = EnforceDefineSemantics::kSet, StoreOrigin store_origin = StoreOrigin::kNamed) [static]
Definition at line 3673 of file js-objects.cc.
                              {
  it->UpdateProtector();
  for (;; it->Next()) {
    switch (it->state()) {
      case LookupIterator::JSPROXY:
      case LookupIterator::TRANSITION:
      case LookupIterator::STRING_LOOKUP_START_OBJECT:
        UNREACHABLE();
      case LookupIterator::WASM_OBJECT:
        continue; // {AddDataProperty} will throw if no other case is hit.
      case LookupIterator::ACCESS_CHECK:
        if (!it->HasAccess()) {
          Isolate* isolate = it->isolate();
          RETURN_ON_EXCEPTION_VALUE(
              isolate,
              isolate->ReportFailedAccessCheck(it->GetHolder<JSObject>()),
              Nothing<bool>());
          UNREACHABLE();
        }
        continue;
      // If there's an interceptor, try to store the property with the
      // interceptor.
      // In case of success, the attributes will have been reset to the default
      // attributes of the interceptor, rather than the incoming attributes.
      //
      // TODO(verwaest): JSProxy afterwards verify the attributes that the
      // JSProxy claims it has, and verifies that they are compatible. If not,
      // they throw. Here we should do the same.
      case LookupIterator::INTERCEPTOR: {
        InterceptorResult result;
        if (semantics == EnforceDefineSemantics::kDefine) {
          PropertyDescriptor descriptor;
          descriptor.set_configurable((attributes & DONT_DELETE) != 0);
          descriptor.set_enumerable((attributes & DONT_ENUM) != 0);
          descriptor.set_writable((attributes & READ_ONLY) != 0);
          descriptor.set_value(Cast<JSAny>(value));
          if (!DefinePropertyWithInterceptorInternal(it, it->GetInterceptor(),
                                                     should_throw, &descriptor)
                   .To(&result)) {
            // An exception was thrown in the interceptor. Propagate.
            return Nothing<bool>();
          }
        } else {
          DCHECK_EQ(semantics, EnforceDefineSemantics::kSet);
          if (handling == DONT_FORCE_FIELD) {
            if (!JSObject::SetPropertyWithInterceptor(it, should_throw, value)
                     .To(&result)) {
              // An exception was thrown in the interceptor. Propagate.
              return Nothing<bool>();
            }
          } else {
            result = InterceptorResult::kNotIntercepted;
          }
        }
        switch (result) {
          case InterceptorResult::kFalse:
            return Just(false);
          case InterceptorResult::kTrue:
            return Just(true);
          case InterceptorResult::kNotIntercepted:
            // Proceed lookup.
            break;
        }
        if (semantics == EnforceDefineSemantics::kDefine) {
          it->Restart();
          Maybe<bool> can_define = JSObject::CheckIfCanDefineAsConfigurable(
              it->isolate(), it, value, should_throw);
          if (can_define.IsNothing() || !can_define.FromJust()) {
            return can_define;
          }
        }
        // The interceptor declined to handle the operation, so proceed defining
        // own property without the interceptor.
        Isolate* isolate = it->isolate();
        DirectHandle<JSAny> receiver = it->GetReceiver();
        LookupIterator own_lookup(isolate, receiver, it->GetKey(),
                                  LookupIterator::OWN_SKIP_INTERCEPTOR);
        return JSObject::DefineOwnPropertyIgnoreAttributes(
            &own_lookup, value, attributes, should_throw, handling, semantics,
            store_origin);
      }
      case LookupIterator::ACCESSOR: {
        DirectHandle<Object> accessors = it->GetAccessors();
        // Special handling for AccessorInfo, which behaves like a data
        // property.
        if (IsAccessorInfo(*accessors) && handling == DONT_FORCE_FIELD) {
          PropertyAttributes current_attributes = it->property_attributes();
          // Ensure the context isn't changed after calling into accessors.
          AssertNoContextChange ncc(it->isolate());
          // Update the attributes before calling the setter. The setter may
          // later change the shape of the property.
          if (current_attributes != attributes) {
            it->TransitionToAccessorPair(accessors, attributes);
          }
          return Object::SetPropertyWithAccessor(it, value, should_throw);
        }
        it->ReconfigureDataProperty(value, attributes);
        return Just(true);
      }
      case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
        return Object::RedefineIncompatibleProperty(
            it->isolate(), it->GetName(), value, should_throw);
      case LookupIterator::DATA: {
        // Regular property update if the attributes match.
        if (it->property_attributes() == attributes) {
          return Object::SetDataProperty(it, value);
        }
        // The non-matching attribute case for JSTypedArrays has already been
        // handled by JSTypedArray::DefineOwnProperty.
        DCHECK(!it->IsElement() ||
               !Cast<JSObject>(it->GetReceiver())
                    ->HasTypedArrayOrRabGsabTypedArrayElements());
        // Reconfigure the data property if the attributes mismatch.
        it->ReconfigureDataProperty(value, attributes);
        return Just(true);
      }
      case LookupIterator::NOT_FOUND:
        return Object::AddDataProperty(it, value, attributes, should_throw,
                                       store_origin, semantics);
    }
    UNREACHABLE();
  }
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, v8::internal::Object::AddDataProperty(), CheckIfCanDefineAsConfigurable(), v8::internal::LookupIterator::DATA, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::DONT_DELETE, v8::internal::DONT_ENUM, DONT_FORCE_FIELD, v8::Maybe< T >::FromJust(), v8::internal::LookupIterator::GetAccessors(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetInterceptor(), v8::internal::LookupIterator::GetKey(), v8::internal::LookupIterator::GetName(), v8::internal::LookupIterator::GetReceiver(), v8::internal::LookupIterator::HasAccess(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::LookupIterator::IsElement(), v8::Maybe< T >::IsNothing(), v8::internal::LookupIterator::isolate(), v8::internal::LookupIterator::JSPROXY, v8::Just(), v8::internal::kDefine, v8::internal::kFalse, v8::internal::kNotIntercepted, v8::internal::kSet, v8::internal::kTrue, v8::internal::LookupIterator::Next(), v8::internal::LookupIterator::NOT_FOUND, v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR, v8::internal::LookupIterator::property_attributes(), v8::internal::READ_ONLY, v8::internal::LookupIterator::ReconfigureDataProperty(), v8::internal::Object::RedefineIncompatibleProperty(), v8::internal::Isolate::ReportFailedAccessCheck(), v8::internal::LookupIterator::Restart(), v8::base::internal::result, RETURN_ON_EXCEPTION_VALUE, v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), v8::internal::Object::SetDataProperty(), v8::internal::Object::SetPropertyWithAccessor(), SetPropertyWithInterceptor(), v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TransitionToAccessorPair(), v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), v8::internal::LookupIterator::UpdateProtector(), v8::internal::value, and v8::internal::LookupIterator::WASM_OBJECT.
Referenced by v8::internal::JSDataObjectBuilder::AddSlowProperty(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), CreateDataProperty(), v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareGlobal(), v8::internal::anonymous_namespace{ic.cc}::DefineOwnDataProperty(), DefinePropertyOrElementIgnoreAttributes(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), v8::internal::RUNTIME_FUNCTION(), SetOwnElementIgnoreAttributes(), SetOwnPropertyIgnoreAttributes(), v8::Object::SetPrivate(), v8::internal::SetPropertiesFromKeyValuePairs(), v8::internal::anonymous_namespace{ic.cc}::StoreOwnElement(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
DefinePropertyOrElementIgnoreAttributes()
MaybeDirectHandle< Object > v8::internal::JSObject::DefinePropertyOrElementIgnoreAttributes (DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > value, PropertyAttributes attributes = NONE) [static]
Definition at line 3833 of file js-objects.cc.
                                                               {
  Isolate* isolate = Isolate::Current();
  PropertyKey key(isolate, name);
  LookupIterator it(isolate, object, key, object, LookupIterator::OWN);
  return DefineOwnPropertyIgnoreAttributes(&it, value, attributes);
}
References v8::internal::Isolate::Current(), DefineOwnPropertyIgnoreAttributes(), v8::internal::key, v8::internal::name, v8::internal::LookupIterator::OWN, and v8::internal::value.
Referenced by v8::internal::JSFunction::SetName().
DeletePropertyWithInterceptor()
Maybe< InterceptorResult > v8::internal::JSObject::DeletePropertyWithInterceptor (LookupIterator * it, ShouldThrow should_throw) [static], [private]
Definition at line 4138 of file js-objects.cc.
                                                  {
  Isolate* isolate = it->isolate();
  // Make sure that the top context does not change when doing callbacks or
  // interceptor calls.
  AssertNoContextChange ncc(isolate);
  DCHECK_EQ(LookupIterator::INTERCEPTOR, it->state());
  DirectHandle<InterceptorInfo> interceptor(it->GetInterceptor());
  if (!interceptor->has_deleter()) {
    return Just(InterceptorResult::kNotIntercepted);
  }
  DirectHandle<JSObject> holder = it->GetHolder<JSObject>();
  DirectHandle<Object> receiver = it->GetReceiver();
  if (!IsJSReceiver(*receiver)) {
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, receiver,
                                     Object::ConvertReceiver(isolate, receiver),
                                     Nothing<InterceptorResult>());
  }
  PropertyCallbackArguments args(isolate, interceptor->data(), *receiver,
                                 *holder, Just(should_throw));
  v8::Intercepted intercepted =
      it->IsElement(*holder)
          ? args.CallIndexedDeleter(interceptor, it->array_index())
          : args.CallNamedDeleter(interceptor, it->name());
  return args.GetBooleanReturnValue(intercepted, "Deleter");
}
References v8::base::args, v8::internal::LookupIterator::array_index(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Object::ConvertReceiver(), DCHECK_EQ, v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetInterceptor(), v8::internal::LookupIterator::GetReceiver(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::LookupIterator::IsElement(), v8::internal::LookupIterator::isolate(), v8::Just(), v8::internal::kNotIntercepted, v8::internal::LookupIterator::name(), and v8::internal::LookupIterator::state().
Referenced by v8::internal::JSReceiver::DeleteProperty().
DictionaryPropertyAt() [1/2]
std::optional< Tagged< Object > > v8::internal::JSObject::DictionaryPropertyAt (DirectHandle< JSObject > object, InternalIndex dict_index, Heap * heap) [static]
Definition at line 4662 of file js-objects.cc.
                                                                         {
  Tagged<Object> backing_store = object->raw_properties_or_hash(kRelaxedLoad);
  if (!IsHeapObject(backing_store)) return {};
  if (heap->IsPendingAllocation(Cast<HeapObject>(backing_store))) return {};
  if (!IsPropertyDictionary(backing_store)) return {};
  std::optional<Tagged<Object>> maybe_obj =
      Cast<PropertyDictionary>(backing_store)->TryValueAt(dict_index);
  if (!maybe_obj) return {};
  return maybe_obj.value();
}
References v8::internal::IsHeapObject(), v8::internal::InstanceTypeChecker::IsPropertyDictionary(), and v8::kRelaxedLoad.
DictionaryPropertyAt() [2/2]
Handle< Object > v8::internal::JSObject::DictionaryPropertyAt (Isolate * isolate, DirectHandle< JSObject > object, InternalIndex dict_index) [static]
Definition at line 4648 of file js-objects.cc.
                                                                        {
  DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
  if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    Tagged<SwissNameDictionary> dict = object->property_dictionary_swiss();
    return handle(dict->ValueAt(dict_index), isolate);
  } else {
    Tagged<NameDictionary> dict = object->property_dictionary();
    return handle(dict->ValueAt(dict_index), isolate);
  }
}
References v8::internal::ThreadId::Current(), DCHECK_EQ, v8::internal::handle(), v8::internal::Isolate::thread_id(), and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeDictionaryProtoAccessInfo(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnDictionaryPropertyFromHeap(), and v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency::IsValid().
elements()
Tagged< FixedArrayBase > v8::internal::JSObject::elements (PtrComprCageBase cage_base, AcquireLoadTag tag) const [delete]
Definition at line 67 of file js-objects-inl.h.
                                                                  {
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  return elements(cage_base, tag);
}
References v8::internal::GetPtrComprCageBase().
Referenced by AddDataElement(), GetFastElementsUsage(), HasEnumerableElements(), NormalizeElements(), and WouldConvertToSlowElements().
EnsureCanContainElements() [1/3]
void v8::internal::JSObject::EnsureCanContainElements (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > elements, uint32_t length, EnsureElementsMode mode) [inline], [static]
Definition at line 243 of file js-objects-inl.h.
                                                                 {
  ReadOnlyRoots roots = GetReadOnlyRoots();
  if (elements->map() != roots.fixed_double_array_map()) {
    DCHECK(elements->map() == roots.fixed_array_map() ||
           elements->map() == roots.fixed_cow_array_map());
    if (mode == ALLOW_COPIED_DOUBLE_ELEMENTS) {
      mode = DONT_ALLOW_DOUBLE_ELEMENTS;
    }
    ObjectSlot objects = Cast<FixedArray>(elements)->RawFieldOfFirstElement();
    EnsureCanContainElements(isolate, object, objects, length, mode);
    return;
  }
  DCHECK(mode == ALLOW_COPIED_DOUBLE_ELEMENTS);
  if (object->GetElementsKind() == HOLEY_SMI_ELEMENTS) {
    TransitionElementsKind(isolate, object, HOLEY_DOUBLE_ELEMENTS);
  } else if (object->GetElementsKind() == PACKED_SMI_ELEMENTS) {
    auto double_array = Cast<FixedDoubleArray>(elements);
    for (uint32_t i = 0; i < length; ++i) {
      if (double_array->is_the_hole(i)) {
        TransitionElementsKind(isolate, object, HOLEY_DOUBLE_ELEMENTS);
        return;
      }
    }
    TransitionElementsKind(isolate, object, PACKED_DOUBLE_ELEMENTS);
  }
}
References v8::internal::ALLOW_COPIED_DOUBLE_ELEMENTS, DCHECK, v8::internal::DONT_ALLOW_DOUBLE_ELEMENTS, v8::internal::GetReadOnlyRoots(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, mode(), v8::internal::PACKED_DOUBLE_ELEMENTS, and v8::internal::PACKED_SMI_ELEMENTS.
EnsureCanContainElements() [2/3]
void v8::internal::JSObject::EnsureCanContainElements (Isolate * isolate, DirectHandle< JSObject > object, JavaScriptArguments * arguments, uint32_t arg_count, EnsureElementsMode mode) [static]
Definition at line 5368 of file js-objects.cc.
                                                                 {
  return EnsureCanContainElements(isolate, object,
                                  FullObjectSlot(args->address_of_arg_at(0)),
                                  arg_count, mode);
}
References v8::base::args, EnsureCanContainElements(), and mode().
EnsureCanContainElements() [3/3]
template<typename TSlot >
void v8::internal::JSObject::EnsureCanContainElements (Isolate * isolate, DirectHandle< JSObject > object, TSlot elements, uint32_t count, EnsureElementsMode mode) [inline], [static]
Definition at line 179 of file js-objects-inl.h.
                                                                 {
  static_assert(std::is_same_v<TSlot, FullObjectSlot> ||
                    std::is_same_v<TSlot, ObjectSlot>,
                "Only ObjectSlot and FullObjectSlot are expected here");
  ElementsKind current_kind = object->GetElementsKind();
  ElementsKind target_kind = current_kind;
  {
    DisallowGarbageCollection no_gc;
    DCHECK(mode != ALLOW_COPIED_DOUBLE_ELEMENTS);
    bool is_holey = IsHoleyElementsKind(current_kind);
    if (current_kind == HOLEY_ELEMENTS) return;
    Tagged<Object> the_hole = GetReadOnlyRoots().the_hole_value();
    for (uint32_t i = 0; i < count; ++i, ++objects) {
      Tagged<Object> current = *objects;
      if (current == the_hole) {
        is_holey = true;
        target_kind = GetHoleyElementsKind(target_kind);
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      } else if (IsUndefined(current)) {
        if (mode == ALLOW_CONVERTED_DOUBLE_ELEMENTS) {
          if (IsSmiElementsKind(target_kind)) {
            target_kind = HOLEY_DOUBLE_ELEMENTS;
          } else if (target_kind == PACKED_DOUBLE_ELEMENTS) {
            target_kind = HOLEY_DOUBLE_ELEMENTS;
          } else {
            DCHECK(target_kind == PACKED_ELEMENTS ||
                   target_kind == HOLEY_ELEMENTS ||
                   target_kind == HOLEY_DOUBLE_ELEMENTS);
          }
        } else if (is_holey) {
          if (IsSmiElementsKind(target_kind)) {
            target_kind = HOLEY_ELEMENTS;
            break;
          }
        } else {
          target_kind = PACKED_ELEMENTS;
        }
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      } else if (!IsSmi(current)) {
        if (mode == ALLOW_CONVERTED_DOUBLE_ELEMENTS && IsNumber(current)) {
          if (IsSmiElementsKind(target_kind)) {
            if (is_holey) {
              target_kind = HOLEY_DOUBLE_ELEMENTS;
            } else {
              target_kind = PACKED_DOUBLE_ELEMENTS;
            }
          }
        } else if (is_holey) {
          target_kind = HOLEY_ELEMENTS;
          break;
        } else {
          target_kind = PACKED_ELEMENTS;
        }
      }
    }
  }
  if (target_kind != current_kind) {
    TransitionElementsKind(isolate, object, target_kind);
  }
}
References v8::internal::ALLOW_CONVERTED_DOUBLE_ELEMENTS, v8::internal::ALLOW_COPIED_DOUBLE_ELEMENTS, DCHECK, v8::internal::GetHoleyElementsKind(), v8::internal::GetReadOnlyRoots(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsHoleyElementsKind(), v8::internal::IsNumber(), v8::internal::IsSmi(), v8::internal::IsSmiElementsKind(), mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PACKED_DOUBLE_ELEMENTS, and v8::internal::PACKED_ELEMENTS.
Referenced by v8::internal::ArrayConstructInitializeElements(), and EnsureCanContainElements().
EnsureCanContainHeapObjectElements()
kPropertiesOrHashOffset void v8::internal::JSObject::EnsureCanContainHeapObjectElements (Isolate * isolate, DirectHandle< JSObject > obj) [inline], [static]
Definition at line 165 of file js-objects-inl.h.
                                                     {
  JSObject::ValidateElements(isolate, *object);
  ElementsKind elements_kind = object->map()->elements_kind();
  if (!IsObjectElementsKind(elements_kind)) {
    if (IsHoleyElementsKind(elements_kind)) {
      TransitionElementsKind(isolate, object, HOLEY_ELEMENTS);
    } else {
      TransitionElementsKind(isolate, object, PACKED_ELEMENTS);
    }
  }
}
References v8::internal::HOLEY_ELEMENTS, v8::internal::IsHoleyElementsKind(), v8::internal::IsObjectElementsKind(), and v8::internal::PACKED_ELEMENTS.
EnsureWritableFastElements()
void v8::internal::JSObject::EnsureWritableFastElements (Isolate * isolate, DirectHandle< JSObject > object) [inline], [static]
Definition at line 911 of file js-objects-inl.h.
                                                                         {
  DCHECK(object->HasSmiOrObjectElements() ||
         object->HasFastStringWrapperElements() ||
         object->HasAnyNonextensibleElements());
  Tagged<FixedArray> raw_elems = Cast<FixedArray>(object->elements());
  if (V8_UNLIKELY(raw_elems->map() ==
                  ReadOnlyRoots(isolate).fixed_cow_array_map())) {
    MakeElementsWritable(isolate, object);
  }
}
References DCHECK, and V8_UNLIKELY.
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::AddImpl(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::DeleteImpl(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::FillImpl(), v8::internal::LookupIterator::PrepareForDataProperty(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::RemoveElement(), and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::SetLengthImpl().
FastPropertyAt() [1/2]
Handle< JSAny > v8::internal::JSObject::FastPropertyAt (Isolate * isolate, DirectHandle< JSObject > object, Representation representation, FieldIndex index) [static]
Definition at line 4630 of file js-objects.cc.
                                                         {
  Handle<JSAny> raw_value(object->RawFastPropertyAt(index), isolate);
  return Object::WrapForRead(isolate, raw_value, representation);
}
References v8::internal::index, and v8::internal::Object::WrapForRead().
Referenced by v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::internal::FastGetOwnValuesOrEntries(), v8::internal::LookupIterator::FetchValue(), v8::internal::LookupIterator::GetDataValue(), v8::internal::JsonStringifier::SerializeJSObject(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), and v8::internal::Genesis::TransferNamedProperties().
FastPropertyAt() [2/2]
DirectHandle< JSAny > v8::internal::JSObject::FastPropertyAt (Isolate * isolate, DirectHandle< JSObject > object, Representation representation, FieldIndex index, SeqCstAccessTag tag) [static]
Definition at line 4638 of file js-objects.cc.
                                                                  {
  Handle<JSAny> raw_value(object->RawFastPropertyAt(index, tag), isolate);
  return Object::WrapForRead(isolate, raw_value, representation);
}
References v8::internal::index, and v8::internal::Object::WrapForRead().
FastPropertyAtPut() [1/2]
void v8::internal::JSObject::FastPropertyAtPut (FieldIndex index, Tagged< Object > value, SeqCstAccessTag tag) [inline]
Definition at line 489 of file js-objects-inl.h.
                                                      {
  if (index.is_inobject()) {
    RawFastInobjectPropertyAtPut(index, value, tag);
  } else {
    property_array()->set(index.outobject_array_index(), value, tag);
  }
}
References v8::internal::index, and v8::internal::value.
FastPropertyAtPut() [2/2]
void v8::internal::JSObject::FastPropertyAtPut (FieldIndex index, Tagged< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 479 of file js-objects-inl.h.
                                                        {
  if (index.is_inobject()) {
    RawFastInobjectPropertyAtPut(index, value, mode);
  } else {
    DCHECK_EQ(UPDATE_WRITE_BARRIER, mode);
    property_array()->set(index.outobject_array_index(), value);
  }
}
References DCHECK_EQ, v8::internal::index, mode(), v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
ForceSetPrototype()
void v8::internal::JSObject::ForceSetPrototype (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< JSPrototype > proto) [static]
Definition at line 3483 of file js-objects.cc.
                                                                  {
  // object.__proto__ = proto;
  DirectHandle<Map> old_map(object->map(), isolate);
  DirectHandle<Map> new_map = Map::Copy(isolate, old_map, "ForceSetPrototype");
  Map::SetPrototype(isolate, new_map, proto);
  JSObject::MigrateToMap(isolate, object, new_map);
}
References v8::internal::Map::Copy(), MigrateToMap(), and v8::internal::Map::SetPrototype().
Referenced by v8::internal::Genesis::ConfigureGlobalObject(), v8::internal::Genesis::CreateAsyncFunctionMaps(), v8::internal::Genesis::CreateAsyncIteratorMaps(), v8::internal::Genesis::CreateIteratorMaps(), v8::internal::Isolate::DetachGlobal(), v8::internal::Genesis::Genesis(), v8::internal::Genesis::HookUpGlobalProxy(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InitializeIteratorFunctions(), v8::internal::anonymous_namespace{api-natives.cc}::InstantiateFunction(), v8::internal::ApiNatives::InstantiateRemoteObject(), and v8::internal::Genesis::TransferObject().
GetElementsTransitionMap()
DirectHandle< Map > v8::internal::JSObject::GetElementsTransitionMap (Isolate * isolate, DirectHandle< JSObject > object, ElementsKind to_kind) [static]
Definition at line 3501 of file js-objects.cc.
                                                                           {
  DirectHandle<Map> map(object->map(), isolate);
  return Map::TransitionElementsTo(isolate, map, to_kind);
}
References v8::internal::Map::TransitionElementsTo().
Referenced by v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::BasicGrowCapacityAndConvertImpl(), v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::GrowCapacityAndConvertImpl(), v8::internal::Factory::NewSlowJSObjectWithPropertiesAndElements(), NormalizeElements(), v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::ToArray(), and TransitionElementsKind().
GetEmbedderField()
Tagged< Object > v8::internal::JSObject::GetEmbedderField (int index) [inline]
Definition at line 365 of file js-objects-inl.h.
                                                   {
  return EmbedderDataSlot(Tagged(*this), index).load_tagged();
}
References v8::internal::index, v8::internal::EmbedderDataSlot::load_tagged(), and v8::internal::Tagged().
GetEmbedderFieldCount() [1/2]
int v8::internal::JSObject::GetEmbedderFieldCount () const [inline]
Definition at line 355 of file js-objects-inl.h.
                                          {
  return GetEmbedderFieldCount(map());
}
Referenced by v8::internal::Map::EquivalentToForNormalization(), v8::internal::anonymous_namespace{js-function.cc}::FastInitializeDerivedMap(), v8::internal::FieldStatsCollector::GetInobjectFieldStats(), v8::internal::Map::GetVisitorId(), v8::internal::ValueSerializer::IsHostObject(), and v8::ValueSerializer::Delegate::IsHostObject().
GetEmbedderFieldCount() [2/2]
int v8::internal::JSObject::GetEmbedderFieldCount (Tagged< Map > map) [inline], [static]
Definition at line 341 of file js-objects-inl.h.
                                                   {
  int instance_size = map->instance_size();
  if (instance_size == kVariableSizeSentinel) return 0;
  // Embedder fields are located after the object header, whereas in-object
  // properties are located at the end of the object. We don't have to round up
  // the header size here because division by kEmbedderDataSlotSizeInTaggedSlots
  // will swallow potential padding in case of (kTaggedSize !=
  // kSystemPointerSize) anyway.
  return (((instance_size - GetEmbedderFieldsStartOffset(map)) >>
           kTaggedSizeLog2) -
          map->GetInObjectProperties()) /
         kEmbedderDataSlotSizeInTaggedSlots;
}
References v8::internal::kEmbedderDataSlotSizeInTaggedSlots, v8::internal::kTaggedSizeLog2, and v8::internal::kVariableSizeSentinel.
GetEmbedderFieldOffset()
int v8::internal::JSObject::GetEmbedderFieldOffset (int index) [inline]
Definition at line 359 of file js-objects-inl.h.
                                              {
  DCHECK_LT(static_cast<unsigned>(index),
            static_cast<unsigned>(GetEmbedderFieldCount()));
  return GetEmbedderFieldsStartOffset() + (kEmbedderDataSlotSize * index);
}
References DCHECK_LT, v8::internal::index, and v8::internal::kEmbedderDataSlotSize.
GetEmbedderFieldsStartOffset() [1/2]
int v8::internal::JSObject::GetEmbedderFieldsStartOffset () [inline]
Definition at line 321 of file js-objects-inl.h.
                                           {
  return GetEmbedderFieldsStartOffset(map());
}
Referenced by v8::internal::BodyDescriptorBase::IterateJSObjectBodyImpl().
GetEmbedderFieldsStartOffset() [2/2]
int v8::internal::JSObject::GetEmbedderFieldsStartOffset (Tagged< Map > map) [inline], [static]
Definition at line 316 of file js-objects-inl.h.
                                                          {
  // Embedder fields are located after the object header.
  return GetHeaderSize(map);
}
GetFastElementsUsage()
int v8::internal::JSObject::GetFastElementsUsage ()
Definition at line 5600 of file js-objects.cc.
                                   {
  Tagged<FixedArrayBase> store = elements();
  switch (GetElementsKind()) {
    case PACKED_SMI_ELEMENTS:
    case PACKED_DOUBLE_ELEMENTS:
    case PACKED_ELEMENTS:
    case PACKED_FROZEN_ELEMENTS:
    case PACKED_SEALED_ELEMENTS:
    case PACKED_NONEXTENSIBLE_ELEMENTS:
    case SHARED_ARRAY_ELEMENTS:
      return IsJSArray(*this) ? Smi::ToInt(Cast<JSArray>(*this)->length())
                              : store->length();
    case FAST_SLOPPY_ARGUMENTS_ELEMENTS:
      store = Cast<SloppyArgumentsElements>(store)->arguments();
      [[fallthrough]];
    case HOLEY_SMI_ELEMENTS:
    case HOLEY_ELEMENTS:
    case HOLEY_FROZEN_ELEMENTS:
    case HOLEY_SEALED_ELEMENTS:
    case HOLEY_NONEXTENSIBLE_ELEMENTS:
    case FAST_STRING_WRAPPER_ELEMENTS:
      return HoleyElementsUsage(*this, Cast<FixedArray>(store));
    case HOLEY_DOUBLE_ELEMENTS:
      if (elements()->length() == 0) return 0;
      return HoleyElementsUsage(*this, Cast<FixedDoubleArray>(store));
    case SLOW_SLOPPY_ARGUMENTS_ELEMENTS:
    case SLOW_STRING_WRAPPER_ELEMENTS:
    case DICTIONARY_ELEMENTS:
    case WASM_ARRAY_ELEMENTS:
    case NO_ELEMENTS:
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) case TYPE##_ELEMENTS:
      TYPED_ARRAYS(TYPED_ARRAY_CASE)
      RAB_GSAB_TYPED_ARRAYS(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
      UNREACHABLE();
  }
  return 0;
}
References v8::internal::DICTIONARY_ELEMENTS, elements(), v8::internal::FAST_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::FAST_STRING_WRAPPER_ELEMENTS, v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_FROZEN_ELEMENTS, v8::internal::HOLEY_NONEXTENSIBLE_ELEMENTS, v8::internal::HOLEY_SEALED_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::HoleyElementsUsage(), v8::internal::length, v8::internal::NO_ELEMENTS, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_FROZEN_ELEMENTS, v8::internal::PACKED_NONEXTENSIBLE_ELEMENTS, v8::internal::PACKED_SEALED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, RAB_GSAB_TYPED_ARRAYS, v8::internal::SHARED_ARRAY_ELEMENTS, v8::internal::SLOW_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, store(), v8::internal::Smi::ToInt(), TYPED_ARRAY_CASE, TYPED_ARRAYS, v8::internal::UNREACHABLE(), and v8::internal::WASM_ARRAY_ELEMENTS.
GetHeaderSize() [1/2]
int v8::internal::JSObject::GetHeaderSize (InstanceType instance_type, bool function_has_prototype_slot = false) [static]
Definition at line 2477 of file js-objects.cc.
                                                              {
  switch (type) {
    case JS_SPECIAL_API_OBJECT_TYPE:
    case JS_API_OBJECT_TYPE:
      return JSAPIObjectWithEmbedderSlots::BodyDescriptor::kHeaderSize;
    case JS_ITERATOR_PROTOTYPE_TYPE:
    case JS_MAP_ITERATOR_PROTOTYPE_TYPE:
    case JS_OBJECT_PROTOTYPE_TYPE:
    case JS_OBJECT_TYPE:
    case JS_PROMISE_PROTOTYPE_TYPE:
    case JS_REG_EXP_PROTOTYPE_TYPE:
    case JS_SET_ITERATOR_PROTOTYPE_TYPE:
    case JS_SET_PROTOTYPE_TYPE:
    case JS_STRING_ITERATOR_PROTOTYPE_TYPE:
    case JS_ARRAY_ITERATOR_PROTOTYPE_TYPE:
    case JS_TYPED_ARRAY_PROTOTYPE_TYPE:
    case JS_CONTEXT_EXTENSION_OBJECT_TYPE:
    case JS_ARGUMENTS_OBJECT_TYPE:
    case JS_ERROR_TYPE:
      return JSObject::kHeaderSize;
    case JS_GENERATOR_OBJECT_TYPE:
      return JSGeneratorObject::kHeaderSize;
    case JS_ASYNC_FUNCTION_OBJECT_TYPE:
      return JSAsyncFunctionObject::kHeaderSize;
    case JS_ASYNC_GENERATOR_OBJECT_TYPE:
      return JSAsyncGeneratorObject::kHeaderSize;
    case JS_ASYNC_FROM_SYNC_ITERATOR_TYPE:
      return JSAsyncFromSyncIterator::kHeaderSize;
    case JS_GLOBAL_PROXY_TYPE:
      return JSGlobalProxy::kHeaderSize;
    case JS_GLOBAL_OBJECT_TYPE:
      return JSGlobalObject::kHeaderSize;
    case JS_BOUND_FUNCTION_TYPE:
      return JSBoundFunction::kHeaderSize;
    case JS_FUNCTION_TYPE:
    case JS_CLASS_CONSTRUCTOR_TYPE:
    case JS_PROMISE_CONSTRUCTOR_TYPE:
    case JS_REG_EXP_CONSTRUCTOR_TYPE:
    case JS_ARRAY_CONSTRUCTOR_TYPE:
#define TYPED_ARRAY_CONSTRUCTORS_SWITCH(Type, type, TYPE, Ctype) \
  case TYPE##_TYPED_ARRAY_CONSTRUCTOR_TYPE:
      TYPED_ARRAYS(TYPED_ARRAY_CONSTRUCTORS_SWITCH)
#undef TYPED_ARRAY_CONSTRUCTORS_SWITCH
      return JSFunction::GetHeaderSize(function_has_prototype_slot);
    case JS_PRIMITIVE_WRAPPER_TYPE:
      return JSPrimitiveWrapper::kHeaderSize;
    case JS_DATE_TYPE:
      return JSDate::kHeaderSize;
    case JS_DISPOSABLE_STACK_BASE_TYPE:
      return JSDisposableStackBase::kHeaderSize;
    case JS_ASYNC_DISPOSABLE_STACK_TYPE:
      return JSAsyncDisposableStack::kHeaderSize;
    case JS_SYNC_DISPOSABLE_STACK_TYPE:
      return JSSyncDisposableStack::kHeaderSize;
    case JS_ARRAY_TYPE:
      return JSArray::kHeaderSize;
    case JS_ARRAY_BUFFER_TYPE:
      return JSArrayBuffer::kHeaderSize;
    case JS_ARRAY_ITERATOR_TYPE:
      return JSArrayIterator::kHeaderSize;
    case JS_TYPED_ARRAY_TYPE:
      return JSTypedArray::kHeaderSize;
    case JS_DATA_VIEW_TYPE:
      return JSDataView::kHeaderSize;
    case JS_RAB_GSAB_DATA_VIEW_TYPE:
      return JSRabGsabDataView::kHeaderSize;
    case JS_SET_TYPE:
      return JSSet::kHeaderSize;
    case JS_MAP_TYPE:
      return JSMap::kHeaderSize;
    case JS_SET_KEY_VALUE_ITERATOR_TYPE:
    case JS_SET_VALUE_ITERATOR_TYPE:
      return JSSetIterator::kHeaderSize;
    case JS_MAP_KEY_ITERATOR_TYPE:
    case JS_MAP_KEY_VALUE_ITERATOR_TYPE:
    case JS_MAP_VALUE_ITERATOR_TYPE:
      return JSMapIterator::kHeaderSize;
    case JS_WEAK_REF_TYPE:
      return JSWeakRef::kHeaderSize;
    case JS_FINALIZATION_REGISTRY_TYPE:
      return JSFinalizationRegistry::kHeaderSize;
    case JS_WEAK_MAP_TYPE:
      return JSWeakMap::kHeaderSize;
    case JS_WEAK_SET_TYPE:
      return JSWeakSet::kHeaderSize;
    case JS_PROMISE_TYPE:
      return JSPromise::kHeaderSize;
    case JS_REG_EXP_TYPE:
      return JSRegExp::kHeaderSize;
    case JS_REG_EXP_STRING_ITERATOR_TYPE:
      return JSRegExpStringIterator::kHeaderSize;
    case JS_MESSAGE_OBJECT_TYPE:
      return JSMessageObject::kHeaderSize;
    case JS_EXTERNAL_OBJECT_TYPE:
      return JSExternalObject::kHeaderSize;
    case JS_SHADOW_REALM_TYPE:
      return JSShadowRealm::kHeaderSize;
    case JS_STRING_ITERATOR_TYPE:
      return JSStringIterator::kHeaderSize;
    case JS_ITERATOR_MAP_HELPER_TYPE:
      return JSIteratorMapHelper::kHeaderSize;
    case JS_ITERATOR_FILTER_HELPER_TYPE:
      return JSIteratorFilterHelper::kHeaderSize;
    case JS_ITERATOR_TAKE_HELPER_TYPE:
      return JSIteratorTakeHelper::kHeaderSize;
    case JS_ITERATOR_DROP_HELPER_TYPE:
      return JSIteratorDropHelper::kHeaderSize;
    case JS_ITERATOR_FLAT_MAP_HELPER_TYPE:
      return JSIteratorFlatMapHelper::kHeaderSize;
    case JS_MODULE_NAMESPACE_TYPE:
      return JSModuleNamespace::kHeaderSize;
    case JS_SHARED_ARRAY_TYPE:
      return JSSharedArray::kHeaderSize;
    case JS_SHARED_STRUCT_TYPE:
      return JSSharedStruct::kHeaderSize;
    case JS_ATOMICS_MUTEX_TYPE:
      return JSAtomicsMutex::kHeaderSize;
    case JS_ATOMICS_CONDITION_TYPE:
      return JSAtomicsCondition::kHeaderSize;
#ifdef V8_TEMPORAL_SUPPORT
    case JS_TEMPORAL_DURATION_TYPE:
      return JSTemporalDuration::kHeaderSize;
    case JS_TEMPORAL_INSTANT_TYPE:
      return JSTemporalInstant::kHeaderSize;
    case JS_TEMPORAL_PLAIN_DATE_TYPE:
      return JSTemporalPlainDate::kHeaderSize;
    case JS_TEMPORAL_PLAIN_DATE_TIME_TYPE:
      return JSTemporalPlainDateTime::kHeaderSize;
    case JS_TEMPORAL_PLAIN_MONTH_DAY_TYPE:
      return JSTemporalPlainMonthDay::kHeaderSize;
    case JS_TEMPORAL_PLAIN_TIME_TYPE:
      return JSTemporalPlainTime::kHeaderSize;
    case JS_TEMPORAL_PLAIN_YEAR_MONTH_TYPE:
      return JSTemporalPlainYearMonth::kHeaderSize;
    case JS_TEMPORAL_ZONED_DATE_TIME_TYPE:
      return JSTemporalZonedDateTime::kHeaderSize;
#endif // V8_TEMPORAL_SUPPORT
    case JS_VALID_ITERATOR_WRAPPER_TYPE:
      return JSValidIteratorWrapper::kHeaderSize;
    case JS_WRAPPED_FUNCTION_TYPE:
      return JSWrappedFunction::kHeaderSize;
    case JS_RAW_JSON_TYPE:
      return JSRawJson::kHeaderSize;
#ifdef V8_INTL_SUPPORT
    case JS_V8_BREAK_ITERATOR_TYPE:
      return JSV8BreakIterator::kHeaderSize;
    case JS_COLLATOR_TYPE:
      return JSCollator::kHeaderSize;
    case JS_DATE_TIME_FORMAT_TYPE:
      return JSDateTimeFormat::kHeaderSize;
    case JS_DISPLAY_NAMES_TYPE:
      return JSDisplayNames::kHeaderSize;
    case JS_DURATION_FORMAT_TYPE:
      return JSDurationFormat::kHeaderSize;
    case JS_LIST_FORMAT_TYPE:
      return JSListFormat::kHeaderSize;
    case JS_LOCALE_TYPE:
      return JSLocale::kHeaderSize;
    case JS_NUMBER_FORMAT_TYPE:
      return JSNumberFormat::kHeaderSize;
    case JS_PLURAL_RULES_TYPE:
      return JSPluralRules::kHeaderSize;
    case JS_RELATIVE_TIME_FORMAT_TYPE:
      return JSRelativeTimeFormat::kHeaderSize;
    case JS_SEGMENT_ITERATOR_TYPE:
      return JSSegmentIterator::kHeaderSize;
    case JS_SEGMENTER_TYPE:
      return JSSegmenter::kHeaderSize;
    case JS_SEGMENTS_TYPE:
      return JSSegments::kHeaderSize;
#endif // V8_INTL_SUPPORT
#if V8_ENABLE_WEBASSEMBLY
    case WASM_GLOBAL_OBJECT_TYPE:
      return WasmGlobalObject::kHeaderSize;
    case WASM_INSTANCE_OBJECT_TYPE:
      return WasmInstanceObject::kHeaderSize;
    case WASM_MEMORY_OBJECT_TYPE:
      return WasmMemoryObject::kHeaderSize;
    case WASM_MEMORY_MAP_DESCRIPTOR_TYPE:
      return WasmMemoryMapDescriptor::kHeaderSize;
    case WASM_MODULE_OBJECT_TYPE:
      return WasmModuleObject::kHeaderSize;
    case WASM_TABLE_OBJECT_TYPE:
      return WasmTableObject::kHeaderSize;
    case WASM_VALUE_OBJECT_TYPE:
      return WasmValueObject::kHeaderSize;
    case WASM_TAG_OBJECT_TYPE:
      return WasmTagObject::kHeaderSize;
    case WASM_EXCEPTION_PACKAGE_TYPE:
      return WasmExceptionPackage::kHeaderSize;
    case WASM_SUSPENDING_OBJECT_TYPE:
      return WasmSuspendingObject::kHeaderSize;
    case WASM_DESCRIPTOR_OPTIONS_TYPE:
      return WasmDescriptorOptions::kHeaderSize;
#endif // V8_ENABLE_WEBASSEMBLY
    default: {
      // Special type check for API Objects because they are in a large variable
      // instance type range.
      if (InstanceTypeChecker::IsJSApiObject(type)) {
        return JSAPIObjectWithEmbedderSlots::BodyDescriptor::kHeaderSize;
      }
      FATAL("unexpected instance type: %s\n", NonAPIInstanceTypeToString(type));
    }
  }
}
References FATAL, v8::internal::JSFunction::GetHeaderSize(), v8::internal::JSAPIObjectWithEmbedderSlotsOrJSSpecialObjectBodyDescriptor::kHeaderSize, v8::internal::NonAPIInstanceTypeToString(), v8::internal::tracing::type, TYPED_ARRAY_CONSTRUCTORS_SWITCH, and TYPED_ARRAYS.
Referenced by v8::internal::JSFunction::CalculateInstanceSizeHelper(), v8::internal::ApiNatives::CreateApiFunction(), and v8::internal::BodyDescriptorBase::IterateJSObjectBodyImpl().
GetHeaderSize() [2/2]
int v8::internal::JSObject::GetHeaderSize (Tagged< Map > map) [inline], [static]
Definition at line 305 of file js-objects-inl.h.
                                           {
  // Check for the most common kind of JavaScript object before
  // falling into the generic switch. This speeds up the internal
  // field operations considerably on average.
  InstanceType instance_type = map->instance_type();
  return instance_type == JS_OBJECT_TYPE
             ? JSObject::kHeaderSize
             : GetHeaderSize(instance_type, map->has_prototype_slot());
}
GetInObjectPropertyOffset()
int v8::internal::JSObject::GetInObjectPropertyOffset (int index) [inline]
Definition at line 570 of file js-objects-inl.h.
                                                 {
  return map()->GetInObjectPropertyOffset(index);
}
References v8::internal::index.
GetPropertyAttributesWithFailedAccessCheck()
Maybe< PropertyAttributes > v8::internal::JSObject::GetPropertyAttributesWithFailedAccessCheck (LookupIterator * it) [static]
Definition at line 2710 of file js-objects.cc.
                        {
  Isolate* isolate = it->isolate();
  DirectHandle<JSObject> checked = it->GetHolder<JSObject>();
  DirectHandle<InterceptorInfo> interceptor =
      it->GetInterceptorForFailedAccessCheck();
  if (!interceptor.is_null()) {
    Maybe<PropertyAttributes> result =
        GetPropertyAttributesWithInterceptorInternal(it, interceptor);
    if (isolate->has_exception()) return Nothing<PropertyAttributes>();
    if (result.FromMaybe(ABSENT) != ABSENT) return result;
  }
  RETURN_ON_EXCEPTION_VALUE(isolate, isolate->ReportFailedAccessCheck(checked),
                            Nothing<PropertyAttributes>());
  UNREACHABLE();
}
References v8::internal::ABSENT, v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetInterceptorForFailedAccessCheck(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyAttributesWithInterceptorInternal(), v8::internal::Isolate::has_exception(), v8::internal::LookupIterator::isolate(), v8::internal::Isolate::ReportFailedAccessCheck(), v8::base::internal::result, RETURN_ON_EXCEPTION_VALUE, and v8::internal::UNREACHABLE().
Referenced by v8::internal::JSReceiver::GetPropertyAttributes(), v8::internal::anonymous_namespace{runtime-forin.cc}::HasEnumerableProperty(), and v8::internal::JSReceiver::HasProperty().
GetPropertyAttributesWithInterceptor()
Maybe< PropertyAttributes > v8::internal::JSObject::GetPropertyAttributesWithInterceptor (LookupIterator * it) [static]
Definition at line 3842 of file js-objects.cc.
                        {
  return GetPropertyAttributesWithInterceptorInternal(it, it->GetInterceptor());
}
References v8::internal::LookupIterator::GetInterceptor(), and v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyAttributesWithInterceptorInternal().
Referenced by v8::internal::JSReceiver::GetPropertyAttributes(), v8::internal::anonymous_namespace{runtime-forin.cc}::HasEnumerableProperty(), v8::internal::JSReceiver::HasProperty(), and v8::internal::Object::SetPropertyInternal().
GetPropertyWithFailedAccessCheck()
MaybeHandle< JSAny > v8::internal::JSObject::GetPropertyWithFailedAccessCheck (LookupIterator * it) [static], [private]
Definition at line 2684 of file js-objects.cc.
                        {
  Isolate* isolate = it->isolate();
  DirectHandle<JSObject> checked = it->GetHolder<JSObject>();
  DirectHandle<InterceptorInfo> interceptor =
      it->GetInterceptorForFailedAccessCheck();
  if (!interceptor.is_null()) {
    Handle<JSAny> result;
    bool done;
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, result,
        GetPropertyWithInterceptorInternal(it, interceptor, &done));
    if (done) return result;
  }
  // Cross-Origin [[Get]] of Well-Known Symbols does not throw, and returns
  // undefined.
  DirectHandle<Name> name = it->GetName();
  if (IsSymbol(*name) && Cast<Symbol>(*name)->is_well_known_symbol()) {
    return it->factory()->undefined_value();
  }
  RETURN_ON_EXCEPTION(isolate, isolate->ReportFailedAccessCheck(checked));
  UNREACHABLE();
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::LookupIterator::factory(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetInterceptorForFailedAccessCheck(), v8::internal::LookupIterator::GetName(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyWithInterceptorInternal(), v8::internal::LookupIterator::isolate(), v8::internal::name, v8::internal::Isolate::ReportFailedAccessCheck(), v8::base::internal::result, RETURN_ON_EXCEPTION, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Object::GetProperty().
GetPropertyWithInterceptor()
MaybeHandle< JSAny > v8::internal::JSObject::GetPropertyWithInterceptor (LookupIterator * it, bool * done) [static]
Definition at line 5641 of file js-objects.cc.
                                                                    {
  DCHECK_EQ(LookupIterator::INTERCEPTOR, it->state());
  return GetPropertyWithInterceptorInternal(it, it->GetInterceptor(), done);
}
References DCHECK_EQ, v8::internal::LookupIterator::GetInterceptor(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyWithInterceptorInternal(), v8::internal::LookupIterator::INTERCEPTOR, and v8::internal::LookupIterator::state().
Referenced by v8::internal::Object::GetProperty().
HasEnumerableElements()
bool v8::internal::JSObject::HasEnumerableElements ()
Definition at line 4677 of file js-objects.cc.
                                     {
  // TODO(cbruni): cleanup
  Tagged<JSObject> object = *this;
  switch (object->GetElementsKind()) {
    case PACKED_SMI_ELEMENTS:
    case PACKED_ELEMENTS:
    case PACKED_FROZEN_ELEMENTS:
    case PACKED_SEALED_ELEMENTS:
    case PACKED_NONEXTENSIBLE_ELEMENTS:
    case PACKED_DOUBLE_ELEMENTS:
    case SHARED_ARRAY_ELEMENTS: {
      int length = IsJSArray(object)
                       ? Smi::ToInt(Cast<JSArray>(object)->length())
                       : object->elements()->length();
      return length > 0;
    }
    case HOLEY_SMI_ELEMENTS:
    case HOLEY_FROZEN_ELEMENTS:
    case HOLEY_SEALED_ELEMENTS:
    case HOLEY_NONEXTENSIBLE_ELEMENTS:
    case HOLEY_ELEMENTS: {
      Tagged<FixedArray> elements = Cast<FixedArray>(object->elements());
      int length = IsJSArray(object)
                       ? Smi::ToInt(Cast<JSArray>(object)->length())
                       : elements->length();
      Isolate* isolate = Isolate::Current();
      for (int i = 0; i < length; i++) {
        if (!elements->is_the_hole(isolate, i)) return true;
      }
      return false;
    }
    case HOLEY_DOUBLE_ELEMENTS: {
      int length = IsJSArray(object)
                       ? Smi::ToInt(Cast<JSArray>(object)->length())
                       : object->elements()->length();
      // Zero-length arrays would use the empty FixedArray...
      if (length == 0) return false;
      // ...so only cast to FixedDoubleArray otherwise.
      Tagged<FixedDoubleArray> elements =
          Cast<FixedDoubleArray>(object->elements());
      for (int i = 0; i < length; i++) {
        if (!elements->is_the_hole(i)) return true;
      }
      return false;
    }
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) case TYPE##_ELEMENTS:
      TYPED_ARRAYS(TYPED_ARRAY_CASE) {
        size_t byte_length = Cast<JSTypedArray>(object)->byte_length();
        return byte_length > 0;
      }
      RAB_GSAB_TYPED_ARRAYS(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
      {
        size_t length = Cast<JSTypedArray>(object)->GetLength();
        return length > 0;
      }
    case DICTIONARY_ELEMENTS: {
      Tagged<NumberDictionary> elements =
          Cast<NumberDictionary>(object->elements());
      return elements->NumberOfEnumerableProperties() > 0;
    }
    case FAST_SLOPPY_ARGUMENTS_ELEMENTS:
    case SLOW_SLOPPY_ARGUMENTS_ELEMENTS:
      // We're approximating non-empty arguments objects here.
      return true;
    case FAST_STRING_WRAPPER_ELEMENTS:
    case SLOW_STRING_WRAPPER_ELEMENTS:
      if (Cast<String>(Cast<JSPrimitiveWrapper>(object)->value())->length() >
          0) {
        return true;
      }
      return object->elements()->length() > 0;
    case WASM_ARRAY_ELEMENTS:
      UNIMPLEMENTED();
    case NO_ELEMENTS:
      return false;
  }
  UNREACHABLE();
}
References v8::internal::Cast< NumberDictionary >(), v8::internal::Isolate::Current(), v8::internal::DICTIONARY_ELEMENTS, elements(), v8::internal::FAST_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::FAST_STRING_WRAPPER_ELEMENTS, v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_FROZEN_ELEMENTS, v8::internal::HOLEY_NONEXTENSIBLE_ELEMENTS, v8::internal::HOLEY_SEALED_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::length, v8::internal::NO_ELEMENTS, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_FROZEN_ELEMENTS, v8::internal::PACKED_NONEXTENSIBLE_ELEMENTS, v8::internal::PACKED_SEALED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, RAB_GSAB_TYPED_ARRAYS, v8::internal::SHARED_ARRAY_ELEMENTS, v8::internal::SLOW_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, v8::internal::Smi::ToInt(), TYPED_ARRAY_CASE, TYPED_ARRAYS, v8::internal::UNIMPLEMENTED(), v8::internal::UNREACHABLE(), v8::internal::value, and v8::internal::WASM_ARRAY_ELEMENTS.
HasRealElementProperty()
Maybe< bool > v8::internal::JSObject::HasRealElementProperty (Isolate * isolate, DirectHandle< JSObject > object, uint32_t index) [static]
Definition at line 5655 of file js-objects.cc.
                                                             {
  LookupIterator it(isolate, object, index, object,
                    LookupIterator::OWN_SKIP_INTERCEPTOR);
  return HasProperty(&it);
}
References v8::internal::index, and v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR.
Referenced by v8::Object::HasRealIndexedProperty().
HasRealNamedCallbackProperty()
Maybe< bool > v8::internal::JSObject::HasRealNamedCallbackProperty (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Name > name) [static]
Definition at line 5663 of file js-objects.cc.
                                                                              {
  PropertyKey key(isolate, name);
  LookupIterator it(isolate, object, key, LookupIterator::OWN_SKIP_INTERCEPTOR);
  Maybe<PropertyAttributes> maybe_result = GetPropertyAttributes(&it);
  return maybe_result.IsJust() ? Just(it.state() == LookupIterator::ACCESSOR)
                               : Nothing<bool>();
}
References v8::internal::LookupIterator::ACCESSOR, v8::Maybe< T >::IsJust(), v8::Just(), v8::internal::key, v8::internal::name, v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR, and v8::internal::LookupIterator::state().
Referenced by v8::Object::HasRealNamedCallbackProperty().
HasRealNamedProperty()
Maybe< bool > v8::internal::JSObject::HasRealNamedProperty (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Name > name) [static]
Definition at line 5647 of file js-objects.cc.
                                                                    {
  PropertyKey key(isolate, name);
  LookupIterator it(isolate, object, key, LookupIterator::OWN_SKIP_INTERCEPTOR);
  return HasProperty(&it);
}
References v8::internal::key, v8::internal::name, and v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR.
Referenced by v8::Object::HasRealNamedProperty(), and v8::internal::Isolate::InstallConditionalFeatures().
initialize_elements()
void v8::internal::JSObject::initialize_elements () [inline]
Definition at line 291 of file js-objects-inl.h.
                                   {
  Tagged<FixedArrayBase> elements = map()->GetInitialElements();
  set_elements(elements, SKIP_WRITE_BARRIER);
}
References v8::internal::SKIP_WRITE_BARRIER.
InitializeBody()
void v8::internal::JSObject::InitializeBody (Tagged< Map > map, int start_offset, bool is_slack_tracking_in_progress, MapWord filler_map, Tagged< Object > undefined_value) [inline]
Definition at line 588 of file js-objects-inl.h.
                                                               {
  int size = map->instance_size();
  int offset = start_offset;
  // embedder data slots need to be initialized separately
  if (MayHaveEmbedderFields(map)) {
    int embedder_field_start = GetEmbedderFieldsStartOffset(map);
    int embedder_field_count = GetEmbedderFieldCount(map);
    // fill start with references to the undefined value object
    DCHECK_LE(offset, embedder_field_start);
    while (offset < embedder_field_start) {
      WRITE_FIELD(*this, offset, undefined_filler);
      offset += kTaggedSize;
    }
    // initialize embedder data slots
    DCHECK_EQ(offset, embedder_field_start);
    for (int i = 0; i < embedder_field_count; i++) {
      // TODO(v8): consider initializing embedded data slots with Smi::zero().
      EmbedderDataSlot(Tagged<JSObject>(*this), i).Initialize(undefined_filler);
      offset += kEmbedderDataSlotSize;
    }
  } else {
    DCHECK_EQ(0, GetEmbedderFieldCount(map));
  }
  DCHECK_LE(offset, size);
  if (is_slack_tracking_in_progress) {
    int end_of_pre_allocated_offset =
        size - (map->UnusedPropertyFields() * kTaggedSize);
    DCHECK_LE(kHeaderSize, end_of_pre_allocated_offset);
    DCHECK_LE(offset, end_of_pre_allocated_offset);
    // fill pre allocated slots with references to the undefined value object
    while (offset < end_of_pre_allocated_offset) {
      WRITE_FIELD(*this, offset, undefined_filler);
      offset += kTaggedSize;
    }
    // fill the remainder with one word filler objects (ie just a map word)
    while (offset < size) {
      Tagged<Object> fm = Tagged<Object>(filler_map.ptr());
      WRITE_FIELD(*this, offset, fm);
      offset += kTaggedSize;
    }
  } else {
    while (offset < size) {
      // fill everything with references to the undefined value object
      WRITE_FIELD(*this, offset, undefined_filler);
      offset += kTaggedSize;
    }
  }
}
References DCHECK_EQ, DCHECK_LE, v8::internal::EmbedderDataSlot::Initialize(), v8::internal::kEmbedderDataSlotSize, v8::internal::kTaggedSize, v8::internal::MapWord::ptr(), size(), v8::internal::Tagged< Object >, and WRITE_FIELD.
InObjectPropertyAt()
Tagged< Object > v8::internal::JSObject::InObjectPropertyAt (int index) [inline]
Definition at line 574 of file js-objects-inl.h.
                                                     {
  int offset = GetInObjectPropertyOffset(index);
  return TaggedField<Object>::load(*this, offset);
}
References v8::internal::index.
InObjectPropertyAtPut()
Tagged< Object > v8::internal::JSObject::InObjectPropertyAtPut (int index, Tagged< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 579 of file js-objects-inl.h.
                                                                      {
  // Adjust for the number of properties stored in the object.
  int offset = GetInObjectPropertyOffset(index);
  WRITE_FIELD(*this, offset, value);
  CONDITIONAL_WRITE_BARRIER(*this, offset, value, mode);
  return value;
}
References CONDITIONAL_WRITE_BARRIER, v8::internal::index, mode(), v8::internal::value, and WRITE_FIELD.
InvalidatePrototypeChains()
Tagged< Map > v8::internal::JSObject::InvalidatePrototypeChains (Tagged< Map > map) [static]
Definition at line 5236 of file js-objects.cc.
                                                               {
  DisallowGarbageCollection no_gc;
  InvalidatePrototypeChainsInternal(map);
  return map;
}
References v8::internal::anonymous_namespace{js-objects.cc}::InvalidatePrototypeChainsInternal(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::LookupIterator::ApplyTransitionToDataProperty(), v8::internal::JSReceiver::DeleteNormalizedProperty(), v8::internal::InvalidatePrototypeChainsWrapper(), NotifyMapChange(), v8::internal::LookupIterator::PrepareForDataProperty(), v8::internal::LookupIterator::ReconfigureDataProperty(), RequireSlowElements(), v8::internal::LookupIterator::TransitionToAccessorPair(), and v8::internal::MapUpdater::UpdateFieldType().
InvalidatePrototypeValidityCell()
void v8::internal::JSObject::InvalidatePrototypeValidityCell (Tagged< JSGlobalObject > global) [static]
Definition at line 5250 of file js-objects.cc.
                                                                            {
  DisallowGarbageCollection no_gc;
  InvalidateOnePrototypeValidityCellInternal(global->map());
}
References v8::internal::anonymous_namespace{js-objects.cc}::InvalidateOnePrototypeValidityCellInternal(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::JSGlobalObject::InvalidatePropertyCell().
IsDroppableApiObject() [1/2]
bool v8::internal::JSObject::IsDroppableApiObject () const [inline]
Definition at line 384 of file js-objects-inl.h.
                                          {
  return IsDroppableApiObject(map());
}
Referenced by IsUnmodifiedApiObject().
IsDroppableApiObject() [2/2]
bool v8::internal::JSObject::IsDroppableApiObject (Tagged< Map > map) [inline], [static]
Definition at line 378 of file js-objects-inl.h.
                                                         {
  auto instance_type = map->instance_type();
  return InstanceTypeChecker::IsJSApiObject(instance_type) ||
         instance_type == JS_SPECIAL_API_OBJECT_TYPE;
}
IsExtensible()
bool v8::internal::JSObject::IsExtensible (Isolate * isolate, DirectHandle< JSObject > object) [static]
Definition at line 4354 of file js-objects.cc.
                                                                           {
  if (IsAccessCheckNeeded(*object) &&
      !isolate->MayAccess(isolate->native_context(), object)) {
    return true;
  }
  if (IsJSGlobalProxy(*object)) {
    PrototypeIterator iter(isolate, *object);
    if (iter.IsAtEnd()) return false;
    DCHECK(IsJSGlobalObject(iter.GetCurrent()));
    return iter.GetCurrent<JSObject>()->map()->is_extensible();
  }
  return object->map()->is_extensible();
}
References v8::internal::DCHECK(), v8::internal::PrototypeIterator::GetCurrent(), v8::internal::PrototypeIterator::IsAtEnd(), v8::internal::Isolate::MayAccess(), and v8::internal::Isolate::native_context().
Referenced by v8::internal::ErrorUtils::CaptureStackTrace(), CheckIfCanDefineAsConfigurable(), v8::internal::JSReceiver::IsExtensible(), and v8::internal::JSReceiver::OrdinaryDefineOwnProperty().
IsUnmodifiedApiObject()
bool v8::internal::JSObject::IsUnmodifiedApiObject (FullObjectSlot o) [static]
Definition at line 3042 of file js-objects.cc.
                                                     {
  Tagged<Object> object = *o;
  if (IsSmi(object)) return false;
  Tagged<HeapObject> heap_object = Cast<HeapObject>(object);
  Tagged<Map> map = heap_object->map();
  if (!InstanceTypeChecker::IsJSObject(map)) return false;
  if (!JSObject::IsDroppableApiObject(map)) return false;
  Tagged<Object> maybe_constructor = map->GetConstructor();
  if (!IsJSFunction(maybe_constructor)) return false;
  Tagged<JSObject> js_object = Cast<JSObject>(object);
  if (js_object->elements()->length() != 0) return false;
  // Check that the object is not a key in a WeakMap (over-approximation).
  if (!IsUndefined(js_object->GetIdentityHash())) return false;
  Tagged<JSFunction> constructor = Cast<JSFunction>(maybe_constructor);
  return constructor->initial_map() == map;
}
References IsDroppableApiObject(), and v8::internal::IsSmi().
Referenced by v8::internal::anonymous_namespace{traced-handles.cc}::ComputeWeaknessProcessor::ProcessBlock().
JSObjectShortPrint()
void v8::internal::JSObject::JSObjectShortPrint (StringStream * accumulator)
Definition at line 2843 of file js-objects.cc.
                                                           {
  switch (map()->instance_type()) {
    case JS_ARRAY_TYPE: {
      double length = IsUndefined(Cast<JSArray>(*this)->length())
                          ? 0
                          : Object::NumberValue(Cast<JSArray>(*this)->length());
      accumulator->Add("<JSArray[%u]>", static_cast<uint32_t>(length));
      break;
    }
    case JS_BOUND_FUNCTION_TYPE: {
      Tagged<JSBoundFunction> bound_function = Cast<JSBoundFunction>(*this);
      accumulator->Add("<JSBoundFunction");
      accumulator->Add(" (BoundTargetFunction %p)>",
                       reinterpret_cast<void*>(
                           bound_function->bound_target_function().ptr()));
      break;
    }
    case JS_WEAK_MAP_TYPE: {
      accumulator->Add("<JSWeakMap>");
      break;
    }
    case JS_WEAK_SET_TYPE: {
      accumulator->Add("<JSWeakSet>");
      break;
    }
    case JS_REG_EXP_TYPE: {
      accumulator->Add("<JSRegExp");
      Tagged<JSRegExp> regexp = Cast<JSRegExp>(*this);
      if (IsString(regexp->source())) {
        accumulator->Add(" ");
        Cast<String>(regexp->source())->StringShortPrint(accumulator);
      }
      accumulator->Add(">");
      break;
    }
    case JS_PROMISE_CONSTRUCTOR_TYPE:
    case JS_REG_EXP_CONSTRUCTOR_TYPE:
    case JS_ARRAY_CONSTRUCTOR_TYPE:
#define TYPED_ARRAY_CONSTRUCTORS_SWITCH(Type, type, TYPE, Ctype) \
  case TYPE##_TYPED_ARRAY_CONSTRUCTOR_TYPE:
      TYPED_ARRAYS(TYPED_ARRAY_CONSTRUCTORS_SWITCH)
#undef TYPED_ARRAY_CONSTRUCTORS_SWITCH
    case JS_CLASS_CONSTRUCTOR_TYPE:
    case JS_FUNCTION_TYPE: {
      Tagged<JSFunction> function = Cast<JSFunction>(*this);
      std::unique_ptr<char[]> fun_name = function->shared()->DebugNameCStr();
      if (fun_name[0] != '\0') {
        accumulator->Add("<JSFunction ");
        accumulator->Add(fun_name.get());
      } else {
        accumulator->Add("<JSFunction");
      }
      if (v8_flags.trace_file_names) {
        Tagged<Object> source_name =
            Cast<Script>(function->shared()->script())->name();
        if (IsString(source_name)) {
          Tagged<String> str = Cast<String>(source_name);
          if (str->length() > 0) {
            accumulator->Add(" <");
            accumulator->Put(str);
            accumulator->Add(">");
          }
        }
      }
      accumulator->Add(" (sfi = %p)",
                       reinterpret_cast<void*>(function->shared().ptr()));
      accumulator->Put('>');
      break;
    }
    case JS_GENERATOR_OBJECT_TYPE: {
      accumulator->Add("<JSGenerator>");
      break;
    }
    case JS_ASYNC_FUNCTION_OBJECT_TYPE: {
      accumulator->Add("<JSAsyncFunctionObject>");
      break;
    }
    case JS_ASYNC_GENERATOR_OBJECT_TYPE: {
      accumulator->Add("<JS AsyncGenerator>");
      break;
    }
    case JS_SHARED_ARRAY_TYPE:
      accumulator->Add("<JSSharedArray>");
      break;
    case JS_SHARED_STRUCT_TYPE:
      accumulator->Add("<JSSharedStruct>");
      break;
    case JS_ATOMICS_MUTEX_TYPE:
      accumulator->Add("<JSAtomicsMutex>");
      break;
    case JS_ATOMICS_CONDITION_TYPE:
      accumulator->Add("<JSAtomicsCondition>");
      break;
    case JS_MESSAGE_OBJECT_TYPE:
      accumulator->Add("<JSMessageObject>");
      break;
    case JS_EXTERNAL_OBJECT_TYPE:
      accumulator->Add("<JSExternalObject>");
      break;
    case CPP_HEAP_EXTERNAL_OBJECT_TYPE:
      accumulator->Add("<CppHeapExternalObject>");
      break;
    default: {
      Tagged<Map> map_of_this = map();
      Tagged<Object> constructor = map_of_this->GetConstructor();
      bool printed = false;
      bool is_global_proxy = IsJSGlobalProxy(*this);
      if (IsJSFunction(constructor)) {
        Tagged<SharedFunctionInfo> sfi =
            Cast<JSFunction>(constructor)->shared();
        Tagged<String> constructor_name = sfi->Name();
        if (constructor_name->length() > 0) {
          accumulator->Add(is_global_proxy ? "<GlobalObject " : "<");
          accumulator->Put(constructor_name);
          accumulator->Add(" %smap = %p",
                           map_of_this->is_deprecated() ? "deprecated-" : "",
                           map_of_this);
          printed = true;
        }
      } else if (IsFunctionTemplateInfo(constructor)) {
        accumulator->Add("<RemoteObject>");
        printed = true;
      }
      if (!printed) {
        accumulator->Add("<JS");
        if (is_global_proxy) {
          accumulator->Add("GlobalProxy");
        } else if (IsJSGlobalObject(*this)) {
          accumulator->Add("GlobalObject");
        } else {
          accumulator->Add("Object");
        }
      }
      if (IsJSPrimitiveWrapper(*this)) {
        accumulator->Add(" value = ");
        ShortPrint(Cast<JSPrimitiveWrapper>(*this)->value(), accumulator);
      }
      accumulator->Put('>');
      break;
    }
  }
}
References v8::internal::StringStream::Add(), v8::internal::length, v8::internal::Object::NumberValue(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::StringStream::Put(), v8::internal::ShortPrint(), TYPED_ARRAY_CONSTRUCTORS_SWITCH, TYPED_ARRAYS, and v8::internal::v8_flags.
LazyRegisterPrototypeUser()
void v8::internal::JSObject::LazyRegisterPrototypeUser (DirectHandle< Map > user, Isolate * isolate) [static]
Definition at line 5058 of file js-objects.cc.
                                                           {
  // Contract: In line with InvalidatePrototypeChains()'s requirements,
  // leaf maps don't need to register as users, only prototypes do.
  DCHECK(user->is_prototype_map());
  DirectHandle<Map> current_user = user;
  DirectHandle<PrototypeInfo> current_user_info =
      Map::GetOrCreatePrototypeInfo(user, isolate);
  for (PrototypeIterator iter(isolate, user); !iter.IsAtEnd(); iter.Advance()) {
    // Walk up the prototype chain as far as links haven't been registered yet.
    if (current_user_info->registry_slot() != PrototypeInfo::UNREGISTERED) {
      break;
    }
    DirectHandle<Object> maybe_proto = PrototypeIterator::GetCurrent(iter);
    // This checks for both proxies and shared objects.
    //
    // Proxies on the prototype chain are not supported. They make it
    // impossible to make any assumptions about the prototype chain anyway.
    //
    // Objects in the shared heap have fixed layouts and their maps never
    // change, so they don't need to be tracked as prototypes
    // anyway. Additionally, registering users of shared objects is not
    // threadsafe.
    if (!IsJSObjectThatCanBeTrackedAsPrototype(*maybe_proto)) continue;
    auto proto = Cast<JSObject>(maybe_proto);
    DirectHandle<PrototypeInfo> proto_info =
        Map::GetOrCreatePrototypeInfo(proto, isolate);
    Handle<Object> maybe_registry(proto_info->prototype_users(), isolate);
    Handle<WeakArrayList> registry =
        IsSmi(*maybe_registry)
            ? handle(ReadOnlyRoots(isolate->heap()).empty_weak_array_list(),
                     isolate)
            : Cast<WeakArrayList>(maybe_registry);
    int slot = 0;
    Handle<WeakArrayList> new_array =
        PrototypeUsers::Add(isolate, registry, current_user, &slot);
    current_user_info->set_registry_slot(slot);
    if (!maybe_registry.is_identical_to(new_array)) {
      proto_info->set_prototype_users(*new_array);
    }
    if (v8_flags.trace_prototype_users) {
      PrintF("Registering %p as a user of prototype %p (map=%p).\n",
             reinterpret_cast<void*>(current_user->ptr()),
             reinterpret_cast<void*>(proto->ptr()),
             reinterpret_cast<void*>(proto->map().ptr()));
    }
    current_user = direct_handle(proto->map(), isolate);
    current_user_info = proto_info;
  }
}
References v8::internal::PrototypeUsers::Add(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::PrototypeIterator::GetCurrent(), v8::internal::Map::GetOrCreatePrototypeInfo(), v8::internal::handle(), v8::internal::Isolate::heap(), v8::internal::HandleBase::is_identical_to(), v8::internal::PrototypeIterator::IsAtEnd(), v8::internal::IsJSObjectThatCanBeTrackedAsPrototype(), v8::internal::IsSmi(), v8::internal::PrintF(), v8::internal::PrototypeInfo::UNREGISTERED, and v8::internal::v8_flags.
Referenced by v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), and UpdatePrototypeUserRegistration().
MakeElementsWritable()
void v8::internal::JSObject::MakeElementsWritable (Isolate * isolate, DirectHandle< JSObject > object) [static]
Definition at line 2454 of file js-objects.cc.
                                                                   {
  Tagged<FixedArray> raw_elems = Cast<FixedArray>(object->elements());
  DirectHandle<FixedArray> elems(raw_elems, isolate);
  DirectHandle<FixedArray> writable_elems =
      isolate->factory()->CopyFixedArrayWithMap(
          elems, isolate->factory()->fixed_array_map());
  object->set_elements(*writable_elems);
}
References v8::internal::Factory::CopyFixedArrayWithMap(), and v8::internal::Isolate::factory().
MakePrototypesFast()
void v8::internal::JSObject::MakePrototypesFast (DirectHandle< Object > receiver, WhereToStart where_to_start, Isolate * isolate) [static]
Definition at line 4915 of file js-objects.cc.
                                                    {
  if (!IsJSReceiver(*receiver)) return;
  if (IsWasmObject(*receiver)) where_to_start = kStartAtPrototype;
  for (PrototypeIterator iter(isolate, Cast<JSReceiver>(receiver),
                              where_to_start);
       !iter.IsAtEnd(); iter.Advance()) {
    DirectHandle<Object> current = PrototypeIterator::GetCurrent(iter);
    if (!IsJSObjectThatCanBeTrackedAsPrototype(*current)) return;
    DirectHandle<JSObject> current_obj = Cast<JSObject>(current);
    Tagged<Map> current_map = current_obj->map();
    if (current_map->is_prototype_map()) {
      // If the map is already marked as should be fast, we're done. Its
      // prototypes will have been marked already as well.
      if (current_map->should_be_fast_prototype_map()) return;
      DirectHandle<Map> map(current_map, isolate);
      Map::SetShouldBeFastPrototypeMap(map, true, isolate);
      JSObject::OptimizeAsPrototype(current_obj);
    }
  }
}
References v8::internal::PrototypeIterator::GetCurrent(), v8::internal::PrototypeIterator::IsAtEnd(), v8::internal::IsJSObjectThatCanBeTrackedAsPrototype(), v8::internal::IsWasmObject(), v8::internal::kStartAtPrototype, OptimizeAsPrototype(), and v8::internal::Map::SetShouldBeFastPrototypeMap().
Referenced by v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunction(), v8::internal::anonymous_namespace{runtime-forin.cc}::Enumerate(), v8::internal::anonymous_namespace{runtime-classes.cc}::InitClassConstructor(), v8::internal::LoadIC::Load(), v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleCreateFunction(), v8::internal::StoreIC::Store(), and v8::internal::KeyedStoreIC::Store().
MayHaveEmbedderFields() [1/2]
bool v8::internal::JSObject::MayHaveEmbedderFields () const [inline]
Definition at line 336 of file js-objects-inl.h.
                                           {
  return MayHaveEmbedderFields(map());
}
Referenced by v8::internal::BodyDescriptorBase::IterateJSObjectBodyWithoutEmbedderFieldsImpl().
MayHaveEmbedderFields() [2/2]
bool v8::internal::JSObject::MayHaveEmbedderFields (Tagged< Map > map) [inline], [static]
Definition at line 326 of file js-objects-inl.h.
                                                    {
  InstanceType instance_type = map->instance_type();
  // TODO(v8) It'd be nice if all objects with embedder data slots inherited
  // from JSObjectJSAPIObjectWithEmbedderSlotsWithEmbedderSlots, but this is
  // currently not possible due to instance_type constraints.
  return InstanceTypeChecker::IsJSObjectWithEmbedderSlots(instance_type) ||
         InstanceTypeChecker::IsJSAPIObjectWithEmbedderSlots(instance_type) ||
         InstanceTypeChecker::IsJSSpecialObject(instance_type);
}
MigrateInstance()
void v8::internal::JSObject::MigrateInstance (Isolate * isolate, DirectHandle< JSObject > instance) [static]
Definition at line 3565 of file js-objects.cc.
                                                              {
  Handle<Map> original_map(object->map(), isolate);
  DirectHandle<Map> map = Map::Update(isolate, original_map);
  map->set_is_migration_target(true);
  JSObject::MigrateToMap(isolate, object, map);
  if (v8_flags.trace_migration) {
    object->PrintInstanceMigration(stdout, *original_map, *map);
  }
#if VERIFY_HEAP
  if (v8_flags.verify_heap) {
    object->JSObjectVerify(isolate);
  }
#endif
}
References MigrateToMap(), v8::internal::Map::Update(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::internal::anonymous_namespace{ic.cc}::MigrateDeprecated(), and v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk().
MigrateSlowToFast()
void v8::internal::JSObject::MigrateSlowToFast (DirectHandle< JSObject > object, int unused_property_fields, const char * reason) [static]
Definition at line 3862 of file js-objects.cc.
                                                     {
  if (object->HasFastProperties()) return;
  DCHECK(!IsJSGlobalObject(*object));
  Isolate* isolate = Isolate::Current();
  Factory* factory = isolate->factory();
  DirectHandle<NameDictionary> dictionary;
  DirectHandle<SwissNameDictionary> swiss_dictionary;
  int number_of_elements;
  if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    swiss_dictionary =
        direct_handle(object->property_dictionary_swiss(), isolate);
    number_of_elements = swiss_dictionary->NumberOfElements();
  } else {
    dictionary = direct_handle(object->property_dictionary(), isolate);
    number_of_elements = dictionary->NumberOfElements();
  }
  // Make sure we preserve dictionary representation if there are too many
  // descriptors.
  if (number_of_elements > kMaxNumberOfDescriptors) return;
  DirectHandle<FixedArray> iteration_order;
  int iteration_length;
  if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    // |iteration_order| remains empty handle, we don't need it.
    iteration_length = swiss_dictionary->UsedCapacity();
  } else {
    iteration_order = NameDictionary::IterationIndices(isolate, dictionary);
    iteration_length = dictionary->NumberOfElements();
  }
  int number_of_fields = 0;
  // Compute the length of the instance descriptor.
  ReadOnlyRoots roots(isolate);
  for (int i = 0; i < iteration_length; i++) {
    PropertyKind kind;
    if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      InternalIndex index(swiss_dictionary->EntryForEnumerationIndex(i));
      Tagged<Object> key = swiss_dictionary->KeyAt(index);
      if (!SwissNameDictionary::IsKey(roots, key)) {
        // Ignore deleted entries.
        continue;
      }
      kind = swiss_dictionary->DetailsAt(index).kind();
    } else {
      InternalIndex index(Smi::ToInt(iteration_order->get(i)));
      DCHECK(dictionary->IsKey(roots, dictionary->KeyAt(isolate, index)));
      kind = dictionary->DetailsAt(index).kind();
    }
    if (kind == PropertyKind::kData) {
      number_of_fields += 1;
    }
  }
  DirectHandle<Map> old_map(object->map(), isolate);
  int inobject_props = old_map->GetInObjectProperties();
  // Allocate new map.
  DirectHandle<Map> new_map = Map::CopyDropDescriptors(isolate, old_map);
  // We should not only set this bit if we need to. We should not retain the
  // old bit because turning a map into dictionary always sets this bit.
  new_map->set_may_have_interesting_properties(
      new_map->has_named_interceptor() || new_map->is_access_check_needed());
  new_map->set_is_dictionary_map(false);
  NotifyMapChange(old_map, new_map, isolate);
  if (number_of_elements == 0) {
    DisallowGarbageCollection no_gc;
    DCHECK_LE(unused_property_fields, inobject_props);
    // Transform the object.
    new_map->SetInObjectUnusedPropertyFields(inobject_props);
    object->set_map(isolate, *new_map, kReleaseStore);
    object->SetProperties(ReadOnlyRoots(isolate).empty_fixed_array());
    // Check that it really works.
    DCHECK(object->HasFastProperties());
    if (v8_flags.log_maps) {
      LOG(isolate, MapEvent("SlowToFast", old_map, new_map, reason));
    }
    return;
  }
  // Allocate the instance descriptor.
  DirectHandle<DescriptorArray> descriptors =
      DescriptorArray::Allocate(isolate, number_of_elements, 0);
  int number_of_allocated_fields =
      number_of_fields + unused_property_fields - inobject_props;
  if (number_of_allocated_fields < 0) {
    // There is enough inobject space for all fields (including unused).
    number_of_allocated_fields = 0;
    unused_property_fields = inobject_props - number_of_fields;
  }
  // Allocate the property array for the fields.
  DirectHandle<PropertyArray> fields =
      factory->NewPropertyArray(number_of_allocated_fields);
  bool is_transitionable_elements_kind =
      IsTransitionableFastElementsKind(old_map->elements_kind());
  // Fill in the instance descriptor and the fields.
  int current_offset = 0;
  int descriptor_index = 0;
  for (int i = 0; i < iteration_length; i++) {
    Tagged<Name> k;
    Tagged<Object> value;
    PropertyDetails details = PropertyDetails::Empty();
    if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      InternalIndex index(swiss_dictionary->EntryForEnumerationIndex(i));
      Tagged<Object> key_obj = swiss_dictionary->KeyAt(index);
      if (!SwissNameDictionary::IsKey(roots, key_obj)) {
        continue;
      }
      k = Cast<Name>(key_obj);
      value = swiss_dictionary->ValueAt(index);
      details = swiss_dictionary->DetailsAt(index);
    } else {
      InternalIndex index(Smi::ToInt(iteration_order->get(i)));
      k = dictionary->NameAt(index);
      value = dictionary->ValueAt(index);
      details = dictionary->DetailsAt(index);
    }
    // Dictionary keys are internalized upon insertion.
    // TODO(jkummerow): Turn this into a DCHECK if it's not hit in the wild.
    CHECK(IsUniqueName(k));
    DirectHandle<Name> key(k, isolate);
    // Properly mark the {new_map} if the {key} is an "interesting symbol".
    if (key->IsInteresting(isolate)) {
      new_map->set_may_have_interesting_properties(true);
    }
    DCHECK_EQ(PropertyLocation::kField, details.location());
    DCHECK_IMPLIES(!V8_DICT_PROPERTY_CONST_TRACKING_BOOL,
                   details.constness() == PropertyConstness::kMutable);
    Descriptor d;
    if (details.kind() == PropertyKind::kData) {
      // Ensure that we make constant field only when elements kind is not
      // transitionable.
      PropertyConstness constness = is_transitionable_elements_kind
                                        ? PropertyConstness::kMutable
                                        : PropertyConstness::kConst;
      // TODO(v8:11248): Consider always setting constness to kMutable
      // once all prototypes stay in dictionary mode and we are not interested
      // in tracking constness for fast mode properties anymore.
      d = Descriptor::DataField(
          key, current_offset, details.attributes(), constness,
          // TODO(verwaest): value->OptimalRepresentation();
          Representation::Tagged(),
          MaybeObjectDirectHandle(FieldType::Any(isolate)));
    } else {
      DCHECK_EQ(PropertyKind::kAccessor, details.kind());
      d = Descriptor::AccessorConstant(key, direct_handle(value, isolate),
                                       details.attributes());
    }
    details = d.GetDetails();
    if (details.location() == PropertyLocation::kField) {
      if (current_offset < inobject_props) {
        object->InObjectPropertyAtPut(current_offset, value,
                                      UPDATE_WRITE_BARRIER);
      } else {
        int offset = current_offset - inobject_props;
        fields->set(offset, value);
      }
      current_offset += details.field_width_in_words();
    }
    descriptors->Set(InternalIndex(descriptor_index++), &d);
  }
  DCHECK_EQ(current_offset, number_of_fields);
  DCHECK_EQ(descriptor_index, number_of_elements);
  descriptors->Sort();
  DisallowGarbageCollection no_gc;
  new_map->InitializeDescriptors(isolate, *descriptors);
  if (number_of_allocated_fields == 0) {
    new_map->SetInObjectUnusedPropertyFields(unused_property_fields);
  } else {
    new_map->SetOutOfObjectUnusedPropertyFields(unused_property_fields);
  }
  if (v8_flags.log_maps) {
    LOG(isolate, MapEvent("SlowToFast", old_map, new_map, reason));
  }
  // Transform the object.
  object->set_map(isolate, *new_map, kReleaseStore);
  object->SetProperties(*fields);
  DCHECK(IsJSObject(*object));
  // Check that it really works.
  DCHECK(object->HasFastProperties());
}
References v8::internal::Descriptor::AccessorConstant(), v8::internal::DescriptorArray::Allocate(), v8::internal::FieldType::Any(), v8::internal::PropertyDetails::attributes(), CHECK, v8::internal::PropertyDetails::constness(), v8::internal::Map::CopyDropDescriptors(), v8::internal::Isolate::Current(), v8::internal::Descriptor::DataField(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_LE, v8::internal::direct_handle(), v8::internal::PropertyDetails::Empty(), v8::internal::Isolate::factory(), v8::internal::PropertyDetails::field_width_in_words(), v8::internal::Descriptor::GetDetails(), v8::internal::index, v8::internal::SwissNameDictionary::IsKey(), v8::internal::IsTransitionableFastElementsKind(), v8::internal::IsUniqueName(), v8::internal::kAccessor, v8::internal::kConst, v8::internal::kData, v8::internal::key, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::kMaxNumberOfDescriptors, v8::internal::kMutable, v8::kReleaseStore, v8::internal::PropertyDetails::location(), LOG, v8::internal::Factory::NewPropertyArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, NotifyMapChange(), v8::internal::Representation::Tagged(), v8::internal::Smi::ToInt(), v8::internal::UPDATE_WRITE_BARRIER, V8_DICT_PROPERTY_CONST_TRACKING_BOOL, V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, v8::internal::v8_flags, and v8::internal::value.
Referenced by v8::internal::wasm::InstanceBuilder::FinalizeExportsObject(), v8::internal::Genesis::GetThrowTypeErrorIntrinsic(), v8::internal::Genesis::InitializeGlobal(), v8::internal::anonymous_namespace{api-natives.cc}::InstantiateObject(), v8::ObjectSetAccessor(), OptimizeAsPrototype(), and v8::internal::RUNTIME_FUNCTION().
MigrateToMap()
void v8::internal::JSObject::MigrateToMap (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Map > new_map, int expected_additional_properties = 0) [static]
Definition at line 3439 of file js-objects.cc.
                                                                {
  if (object->map(isolate) == *new_map) return;
  DirectHandle<Map> old_map(object->map(isolate), isolate);
  NotifyMapChange(old_map, new_map, isolate);
  if (old_map->is_dictionary_map()) {
    // For slow-to-fast migrations JSObject::MigrateSlowToFast()
    // must be used instead.
    CHECK(new_map->is_dictionary_map());
    // Slow-to-slow migration is trivial.
    object->set_map(isolate, *new_map, kReleaseStore);
  } else if (!new_map->is_dictionary_map()) {
    MigrateFastToFast(isolate, object, new_map);
    if (old_map->is_prototype_map()) {
      DCHECK(!old_map->is_stable());
      DCHECK(new_map->is_stable());
      DCHECK(new_map->owns_descriptors());
      DCHECK(old_map->owns_descriptors());
      // Transfer ownership to the new map. Keep the descriptor pointer of the
      // old map intact because the concurrent marker might be iterating the
      // object with the old map.
      old_map->set_owns_descriptors(false);
      DCHECK(old_map->is_abandoned_prototype_map());
      // Ensure that no transition was inserted for prototype migrations.
      DCHECK_EQ(0,
                TransitionsAccessor(isolate, *old_map).NumberOfTransitions());
      DCHECK(IsUndefined(new_map->GetBackPointer(isolate), isolate));
      DCHECK(object->map(isolate) != *old_map);
    }
  } else {
    MigrateFastToSlow(isolate, object, new_map, expected_additional_properties);
  }
  // Careful: Don't allocate here!
  // For some callers of this method, |object| might be in an inconsistent
  // state now: the new map might have a new elements_kind, but the object's
  // elements pointer hasn't been updated yet. Callers will fix this, but in
  // the meantime, (indirectly) calling JSObjectVerify() must be avoided.
  // When adding code here, add a DisallowGarbageCollection too.
}
References CHECK, v8::internal::DCHECK(), DCHECK_EQ, v8::kReleaseStore, v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), and NotifyMapChange().
Referenced by v8::internal::LookupIterator::ApplyTransitionToDataProperty(), v8::internal::anonymous_namespace{api-natives.cc}::DisableAccessChecks(), v8::internal::anonymous_namespace{api-natives.cc}::EnableAccessChecks(), ForceSetPrototype(), v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::GrowCapacityAndConvertImpl(), MigrateInstance(), v8::internal::DictionaryTemplateInfo::NewInstance(), v8::internal::Factory::NewSlowJSObjectWithPropertiesAndElements(), NormalizeElements(), NormalizeProperties(), OptimizeAsPrototype(), v8::internal::LookupIterator::PrepareForDataProperty(), PreventExtensions(), PreventExtensionsWithTransition(), v8::internal::LookupIterator::ReconfigureDataProperty(), v8::internal::anonymous_namespace{elements.cc}::FastNonextensibleObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl(), v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl(), v8::internal::JSFunction::SetPrototype(), SetPrototype(), TransitionElementsKind(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::TransitionElementsKindImpl(), v8::internal::LookupIterator::TransitionToAccessorProperty(), v8::internal::anonymous_namespace{js-objects.cc}::TryFastAddDataProperty(), and TryMigrateInstance().
New()
MaybeHandle< JSObject > v8::internal::JSObject::New (DirectHandle< JSFunction > constructor, DirectHandle< JSReceiver > new_target, DirectHandle< AllocationSite > site, NewJSObjectType new_js_object_type = NewJSObjectType::kNoAPIWrapper) [static]
Definition at line 2392 of file js-objects.cc.
                                                                        {
  // If called through new, new.target can be:
  // - a subclass of constructor,
  // - a proxy wrapper around constructor, or
  // - the constructor itself.
  // If called through Reflect.construct, it's guaranteed to be a constructor.
  Isolate* const isolate = Isolate::Current();
  DCHECK(IsConstructor(*constructor));
  DCHECK(IsConstructor(*new_target));
  DCHECK(!constructor->has_initial_map() ||
         !InstanceTypeChecker::IsJSFunction(
             constructor->initial_map()->instance_type()));
  DirectHandle<Map> initial_map;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, initial_map,
      JSFunction::GetDerivedMap(isolate, constructor, new_target));
  constexpr int initial_capacity = PropertyDictionary::kInitialCapacity;
  Handle<JSObject> result = isolate->factory()->NewFastOrSlowJSObjectFromMap(
      initial_map, initial_capacity, AllocationType::kYoung, site,
      new_js_object_type);
  return result;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::JSFunction::GetDerivedMap(), v8::internal::compiler::initial_map, v8::internal::NameDictionary::kInitialCapacity, v8::internal::kYoung, v8::internal::Factory::NewFastOrSlowJSObjectFromMap(), and v8::base::internal::result.
Referenced by v8::internal::BUILTIN(), v8::internal::ErrorUtils::Construct(), v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::ConstructBuffer(), v8::internal::anonymous_namespace{messages.cc}::GetStackFrames(), v8::internal::anonymous_namespace{api-natives.cc}::InstantiateObject(), v8::internal::JSDate::New(), and v8::internal::RUNTIME_FUNCTION().
NewElementsCapacity()
static constexpr uint32_t v8::internal::JSObject::NewElementsCapacity (uint32_t old_capacity) [inline], [static], [constexpr]
Definition at line 659 of file js-objects.h.
                                                                       {
    // (old_capacity + 50%) + kMinAddedElementsCapacity
    uint32_t new_capacity =
        old_capacity + (old_capacity >> 1) + kMinAddedElementsCapacity;
    // If we go past kMaxFixedArrayCapacity, but kMaxFixedArrayCapacity is still
    // more than the old_capacity plus the minimum growth amount, limit the
    // capacity to kMinAddedElementsCapacity.
    if (new_capacity > kMaxFixedArrayCapacity &&
        old_capacity + kMinAddedElementsCapacity <= kMaxFixedArrayCapacity) {
      return kMaxFixedArrayCapacity;
    }
    return new_capacity;
  }
References v8::internal::kMaxFixedArrayCapacity, and kMinAddedElementsCapacity.
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::AddArguments(), and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GrowCapacity().
NewWithMap()
MaybeDirectHandle< JSObject > v8::internal::JSObject::NewWithMap (Isolate * isolate, DirectHandle< Map > initial_map, DirectHandle< AllocationSite > site, NewJSObjectType new_js_object_type = NewJSObjectType::kNoAPIWrapper) [static]
Definition at line 2420 of file js-objects.cc.
                                                                           {
  constexpr int initial_capacity = PropertyDictionary::kInitialCapacity;
  DirectHandle<JSObject> result =
      isolate->factory()->NewFastOrSlowJSObjectFromMap(
          initial_map, initial_capacity, AllocationType::kYoung, site,
          new_js_object_type);
  return result;
}
References v8::internal::Isolate::factory(), v8::internal::compiler::initial_map, v8::internal::NameDictionary::kInitialCapacity, v8::internal::kYoung, v8::internal::Factory::NewFastOrSlowJSObjectFromMap(), and v8::base::internal::result.
Referenced by v8::internal::BUILTIN().
NormalizeElements()
DirectHandle< NumberDictionary > v8::internal::JSObject::NormalizeElements (Isolate * isolate, DirectHandle< JSObject > object) [static]
Definition at line 4081 of file js-objects.cc.
                                                     {
  DCHECK(!object->HasTypedArrayOrRabGsabTypedArrayElements());
  bool is_sloppy_arguments = object->HasSloppyArgumentsElements();
  {
    DisallowGarbageCollection no_gc;
    Tagged<FixedArrayBase> elements = object->elements();
    if (is_sloppy_arguments) {
      elements = Cast<SloppyArgumentsElements>(elements)->arguments();
    }
    if (IsNumberDictionary(elements)) {
      return direct_handle(Cast<NumberDictionary>(elements), isolate);
    }
  }
  DCHECK(object->HasSmiOrObjectElements() || object->HasDoubleElements() ||
         object->HasFastArgumentsElements() ||
         object->HasFastStringWrapperElements() ||
         object->HasSealedElements() || object->HasNonextensibleElements());
  DirectHandle<NumberDictionary> dictionary =
      object->GetElementsAccessor()->Normalize(isolate, object);
  // Switch to using the dictionary as the backing storage for elements.
  ElementsKind target_kind =
      is_sloppy_arguments ? SLOW_SLOPPY_ARGUMENTS_ELEMENTS
      : object->HasFastStringWrapperElements() ? SLOW_STRING_WRAPPER_ELEMENTS
                                               : DICTIONARY_ELEMENTS;
  DirectHandle<Map> new_map =
      JSObject::GetElementsTransitionMap(isolate, object, target_kind);
  // Set the new map first to satisfy the elements type assert in
  // set_elements().
  JSObject::MigrateToMap(isolate, object, new_map);
  if (is_sloppy_arguments) {
    Cast<SloppyArgumentsElements>(object->elements())
        ->set_arguments(*dictionary);
  } else {
    object->set_elements(*dictionary);
  }
#ifdef DEBUG
  if (v8_flags.trace_normalization) {
    StdoutStream os;
    os << "Object elements have been normalized:\n";
    Print(*object, os);
  }
#endif
  DCHECK(object->HasDictionaryElements() ||
         object->HasSlowArgumentsElements() ||
         object->HasSlowStringWrapperElements());
  return dictionary;
}
References v8::internal::Cast< NumberDictionary >(), v8::internal::DCHECK(), v8::internal::DICTIONARY_ELEMENTS, v8::internal::direct_handle(), elements(), GetElementsTransitionMap(), MigrateToMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Print(), v8::internal::SLOW_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::AddImpl(), v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::AddImpl(), AllocateStorageForMap(), v8::internal::anonymous_namespace{runtime-literals.cc}::CreateObjectLiteral(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::DeleteCommon(), v8::internal::Module::GetModuleNamespace(), v8::internal::Genesis::HookUpGlobalObject(), v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::NormalizeArgumentsElements(), PreventExtensions(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::ReconfigureImpl(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JSArray::SetLength(), and v8::internal::LookupIterator::TransitionToAccessorPair().
NormalizeProperties() [1/2]
void v8::internal::JSObject::NormalizeProperties (Isolate * isolate, DirectHandle< JSObject > object, PropertyNormalizationMode mode, int expected_additional_properties, bool use_cache, const char * reason) [static]
Definition at line 3847 of file js-objects.cc.
                                                                       {
  if (!object->HasFastProperties()) return;
  DirectHandle<Map> map(object->map(), isolate);
  DirectHandle<Map> new_map = Map::Normalize(isolate, map, map->elements_kind(),
                                             {}, mode, use_cache, reason);
  JSObject::MigrateToMap(isolate, object, new_map,
                         expected_additional_properties);
}
References MigrateToMap(), mode(), and v8::internal::Map::Normalize().
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl(), v8::internal::LookupIterator::Delete(), v8::internal::Module::GetModuleNamespace(), NormalizeProperties(), OptimizeAsPrototype(), PreventExtensionsWithTransition(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JSReceiver::SetOrCopyDataProperties(), v8::internal::wasm::JSPrototypesSetup::ToDictionaryMode(), and v8::internal::LookupIterator::TransitionToAccessorPair().
NormalizeProperties() [2/2]
static V8_EXPORT_PRIVATE void v8::internal::JSObject::NormalizeProperties (Isolate * isolate, DirectHandle< JSObject > object, PropertyNormalizationMode mode, int expected_additional_properties, const char * reason) [inline], [static]
Definition at line 748 of file js-objects.h.
                          {
    const bool kUseCache = true;
    NormalizeProperties(isolate, object, mode, expected_additional_properties,
                        kUseCache, reason);
  }
References mode(), and NormalizeProperties().
NotifyMapChange()
void v8::internal::JSObject::NotifyMapChange (DirectHandle< Map > old_map, DirectHandle< Map > new_map, Isolate * isolate) [static]
Definition at line 3087 of file js-objects.cc.
                                                                            {
  if (!old_map->is_prototype_map()) return;
  InvalidatePrototypeChains(*old_map);
  // If the map was registered with its prototype before, ensure that it
  // registers with its new prototype now. This preserves the invariant that
  // when a map on a prototype chain is registered with its prototype, then
  // all prototypes further up the chain are also registered with their
  // respective prototypes.
  UpdatePrototypeUserRegistration(old_map, new_map, isolate);
}
References InvalidatePrototypeChains(), and UpdatePrototypeUserRegistration().
Referenced by MigrateSlowToFast(), MigrateToMap(), and v8::internal::Factory::ReinitializeJSGlobalProxy().
ObjectCreate()
MaybeDirectHandle< JSObject > v8::internal::JSObject::ObjectCreate (Isolate * isolate, DirectHandle< JSPrototype > prototype) [static]
Definition at line 2433 of file js-objects.cc.
                                                           {
  // Generate the map with the specified {prototype} based on the Object
  // function's initial map from the current native context.
  // TODO(bmeurer): Use a dedicated cache for Object.create; think about
  // slack tracking for Object.create.
  DirectHandle<Map> map = Map::GetObjectCreateMap(isolate, prototype);
  // Actually allocate the object.
  return isolate->factory()->NewFastOrSlowJSObjectFromMap(map);
}
References v8::internal::Isolate::factory(), v8::internal::Map::GetObjectCreateMap(), v8::internal::Factory::NewFastOrSlowJSObjectFromMap(), and v8::internal::prototype.
Referenced by v8::internal::RUNTIME_FUNCTION().
OptimizeAsPrototype()
void v8::internal::JSObject::OptimizeAsPrototype (DirectHandle< JSObject > object, bool enable_setup_mode = true) [static]
Definition at line 4950 of file js-objects.cc.
                                                           {
  DCHECK(IsJSObjectThatCanBeTrackedAsPrototype(*object));
  if (IsJSGlobalObject(*object)) return;
  Isolate* isolate = Isolate::Current();
  if (object->map()->is_prototype_map()) {
    if (enable_setup_mode && PrototypeBenefitsFromNormalization(*object)) {
      // This is the only way PrototypeBenefitsFromNormalization can be true:
      DCHECK(!object->map()->should_be_fast_prototype_map());
      // First normalize to ensure all JSFunctions are DATA_CONSTANT.
      constexpr bool kUseCache = true;
      JSObject::NormalizeProperties(isolate, object, KEEP_INOBJECT_PROPERTIES,
                                    0, kUseCache, "NormalizeAsPrototype");
    }
    if (!V8_DICT_PROPERTY_CONST_TRACKING_BOOL &&
        object->map()->should_be_fast_prototype_map() &&
        !object->HasFastProperties()) {
      JSObject::MigrateSlowToFast(object, 0, "OptimizeAsPrototype");
    }
  } else {
    DirectHandle<Map> new_map;
    if (enable_setup_mode && PrototypeBenefitsFromNormalization(*object)) {
#if DEBUG
      DirectHandle<Map> old_map(object->map(isolate), isolate);
#endif // DEBUG
      // First normalize to ensure all JSFunctions are DATA_CONSTANT. Don't use
      // the cache, since we're going to use the normalized version directly,
      // without making a copy.
      constexpr bool kUseCache = false;
      JSObject::NormalizeProperties(isolate, object, KEEP_INOBJECT_PROPERTIES,
                                    0, kUseCache,
                                    "NormalizeAndCopyAsPrototype");
      // A new map was created.
      DCHECK_NE(*old_map, object->map(isolate));
      new_map = direct_handle(object->map(isolate), isolate);
    } else {
      new_map = Map::Copy(isolate, direct_handle(object->map(), isolate),
                          "CopyAsPrototype");
    }
    new_map->set_is_prototype_map(true);
    // Replace the pointer to the exact constructor with the Object function
    // from the same context if undetectable from JS. This is to avoid keeping
    // memory alive unnecessarily.
    Tagged<Object> maybe_constructor = new_map->GetConstructorRaw();
    Tagged<Tuple2> tuple;
    if (IsTuple2(maybe_constructor)) {
      // Handle the {constructor, non-instance_prototype} tuple case if the map
      // has non-instance prototype.
      tuple = Cast<Tuple2>(maybe_constructor);
      maybe_constructor = tuple->value1();
    }
    if (IsJSFunction(maybe_constructor)) {
      Tagged<JSFunction> constructor = Cast<JSFunction>(maybe_constructor);
      if (!constructor->shared()->IsApiFunction()) {
        Tagged<NativeContext> context = constructor->native_context();
        Tagged<JSFunction> object_function = context->object_function();
        if (!tuple.is_null()) {
          tuple->set_value1(object_function);
        } else {
          new_map->SetConstructor(object_function);
        }
      }
    }
    JSObject::MigrateToMap(isolate, object, new_map);
    if (V8_DICT_PROPERTY_CONST_TRACKING_BOOL && !object->HasFastProperties()) {
      ReadOnlyRoots roots(isolate);
      DisallowHeapAllocation no_gc;
      auto make_constant = [&](auto dict) {
        for (InternalIndex index : dict->IterateEntries()) {
          Tagged<Object> k;
          if (!dict->ToKey(roots, index, &k)) continue;
          PropertyDetails details = dict->DetailsAt(index);
          details = details.CopyWithConstness(PropertyConstness::kConst);
          dict->DetailsAtPut(index, details);
        }
      };
      if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
        make_constant(object->property_dictionary_swiss());
      } else {
        make_constant(object->property_dictionary());
      }
    }
  }
#ifdef DEBUG
  bool should_be_dictionary = V8_DICT_PROPERTY_CONST_TRACKING_BOOL &&
                              enable_setup_mode && !IsJSGlobalProxy(*object) &&
                              !isolate->bootstrapper()->IsActive();
  DCHECK_IMPLIES(should_be_dictionary,
                 object->map(isolate)->is_dictionary_map());
#endif
}
References v8::internal::Isolate::bootstrapper(), v8::internal::Map::Copy(), v8::internal::PropertyDetails::CopyWithConstness(), v8::internal::Isolate::Current(), v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_NE, v8::internal::direct_handle(), v8::internal::index, v8::internal::Tagged< HeapObject >::is_null(), v8::internal::Bootstrapper::IsActive(), v8::internal::IsJSObjectThatCanBeTrackedAsPrototype(), v8::internal::kConst, v8::internal::KEEP_INOBJECT_PROPERTIES, MigrateSlowToFast(), MigrateToMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, NormalizeProperties(), v8::internal::PrototypeBenefitsFromNormalization(), V8_DICT_PROPERTY_CONST_TRACKING_BOOL, and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by v8::internal::Map::GetDerivedMap(), v8::internal::Module::GetModuleNamespace(), v8::internal::Map::GetObjectCreateMap(), v8::internal::anonymous_namespace{api-natives.cc}::InstantiateObject(), MakePrototypesFast(), ReoptimizeIfPrototype(), v8::internal::anonymous_namespace{js-function.cc}::SetInstancePrototype(), and v8::internal::Map::SetPrototype().
PreventExtensions()
Maybe< bool > v8::internal::JSObject::PreventExtensions (Isolate * isolate, DirectHandle< JSObject > object, ShouldThrow should_throw) [static]
Definition at line 4299 of file js-objects.cc.
                                                                  {
  if (!object->HasSloppyArgumentsElements()) {
    return PreventExtensionsWithTransition<NONE>(isolate, object, should_throw);
  }
  if (IsAccessCheckNeeded(*object) &&
      !isolate->MayAccess(isolate->native_context(), object)) {
    RETURN_ON_EXCEPTION_VALUE(isolate, isolate->ReportFailedAccessCheck(object),
                              Nothing<bool>());
    UNREACHABLE();
  }
  if (!object->map()->is_extensible()) return Just(true);
  if (IsJSGlobalProxy(*object)) {
    PrototypeIterator iter(isolate, object);
    if (iter.IsAtEnd()) return Just(true);
    DCHECK(IsJSGlobalObject(*PrototypeIterator::GetCurrent(iter)));
    return PreventExtensions(
        isolate, PrototypeIterator::GetCurrent<JSObject>(iter), should_throw);
  }
  if (object->map()->has_named_interceptor() ||
      object->map()->has_indexed_interceptor()) {
    RETURN_FAILURE(isolate, should_throw,
                   NewTypeError(MessageTemplate::kCannotPreventExt));
  }
  DCHECK(!object->HasTypedArrayOrRabGsabTypedArrayElements());
  // Normalize fast elements.
  DirectHandle<NumberDictionary> dictionary =
      NormalizeElements(isolate, object);
  DCHECK(object->HasDictionaryElements() || object->HasSlowArgumentsElements());
  // Make sure that we never go back to fast case.
  if (*dictionary != ReadOnlyRoots(isolate).empty_slow_element_dictionary()) {
    object->RequireSlowElements(*dictionary);
  }
  // Do a map transition, other objects with this map may still
  // be extensible.
  // TODO(adamk): Extend the NormalizedMapCache to handle non-extensible maps.
  DirectHandle<Map> new_map = Map::Copy(
      isolate, direct_handle(object->map(), isolate), "PreventExtensions");
  new_map->set_is_extensible(false);
  JSObject::MigrateToMap(isolate, object, new_map);
  DCHECK(!object->map()->is_extensible());
  return Just(true);
}
References v8::internal::Map::Copy(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::PrototypeIterator::GetCurrent(), v8::internal::PrototypeIterator::IsAtEnd(), v8::Just(), v8::internal::Isolate::MayAccess(), MigrateToMap(), v8::internal::Isolate::native_context(), NormalizeElements(), v8::internal::Isolate::ReportFailedAccessCheck(), RETURN_FAILURE, RETURN_ON_EXCEPTION_VALUE, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Module::GetModuleNamespace(), v8::internal::Genesis::GetThrowTypeErrorIntrinsic(), and v8::internal::JSReceiver::PreventExtensions().
PreventExtensionsWithTransition() [1/2]
template<PropertyAttributes attrs>
Maybe<bool> v8::internal::JSObject::PreventExtensionsWithTransition (Isolate * isolate, DirectHandle< JSObject > object, ShouldThrow should_throw)
Definition at line 4421 of file js-objects.cc.
                                                                               {
  static_assert(attrs == NONE || attrs == SEALED || attrs == FROZEN);
  // Sealing/freezing sloppy arguments or namespace objects should be handled
  // elsewhere.
  DCHECK(!object->HasSloppyArgumentsElements());
  DCHECK_IMPLIES(IsJSModuleNamespace(*object), attrs == NONE);
  if (IsAccessCheckNeeded(*object) &&
      !isolate->MayAccess(isolate->native_context(), object)) {
    RETURN_ON_EXCEPTION_VALUE(isolate, isolate->ReportFailedAccessCheck(object),
                              Nothing<bool>());
    UNREACHABLE();
  }
  if (attrs == NONE && !object->map()->is_extensible()) {
    return Just(true);
  }
  {
    ElementsKind old_elements_kind = object->map()->elements_kind();
    if (IsFrozenElementsKind(old_elements_kind)) return Just(true);
    if (attrs != FROZEN && IsSealedElementsKind(old_elements_kind)) {
      return Just(true);
    }
  }
  if (IsJSGlobalProxy(*object)) {
    PrototypeIterator iter(isolate, object);
    if (iter.IsAtEnd()) return Just(true);
    DCHECK(IsJSGlobalObject(*PrototypeIterator::GetCurrent(iter)));
    return PreventExtensionsWithTransition<attrs>(
        isolate, PrototypeIterator::GetCurrent<JSObject>(iter), should_throw);
  }
  // Shared objects are designed to have fixed layout, i.e. their maps are
  // effectively immutable. They are constructed seal, but the semantics of
  // ordinary ECMAScript objects allow sealed to be upgraded to frozen. This
  // upgrade violates the fixed layout invariant and is disallowed.
  if (IsAlwaysSharedSpaceJSObject(*object)) {
    DCHECK(FastTestIntegrityLevel(isolate, *object, SEALED));
    if (attrs != FROZEN) return Just(true);
    RETURN_FAILURE(isolate, should_throw,
                   NewTypeError(MessageTemplate::kCannotFreeze));
  }
  if (object->map()->has_named_interceptor() ||
      object->map()->has_indexed_interceptor() ||
      (object->HasTypedArrayOrRabGsabTypedArrayElements() &&
       Cast<JSTypedArray>(*object)->IsVariableLength())) {
    MessageTemplate message = MessageTemplate::kNone;
    switch (attrs) {
      case NONE:
        message = MessageTemplate::kCannotPreventExt;
        break;
      case SEALED:
        message = MessageTemplate::kCannotSeal;
        break;
      case FROZEN:
        message = MessageTemplate::kCannotFreeze;
        break;
    }
    RETURN_FAILURE(isolate, should_throw, NewTypeError(message));
  }
  DirectHandle<Symbol> transition_marker;
  if (attrs == NONE) {
    transition_marker = isolate->factory()->nonextensible_symbol();
  } else if (attrs == SEALED) {
    transition_marker = isolate->factory()->sealed_symbol();
  } else {
    DCHECK(attrs == FROZEN);
    transition_marker = isolate->factory()->frozen_symbol();
  }
  // Currently, there are only have sealed/frozen Object element kinds and
  // Map::MigrateToMap doesn't handle properties' attributes reconfiguring and
  // elements kind change in one go. If seal or freeze with Smi or Double
  // elements kind, we will transition to Object elements kind first to make
  // sure of valid element access.
  switch (object->map()->elements_kind()) {
    case PACKED_SMI_ELEMENTS:
    case PACKED_DOUBLE_ELEMENTS:
      JSObject::TransitionElementsKind(isolate, object, PACKED_ELEMENTS);
      break;
    case HOLEY_SMI_ELEMENTS:
    case HOLEY_DOUBLE_ELEMENTS:
      JSObject::TransitionElementsKind(isolate, object, HOLEY_ELEMENTS);
      break;
    default:
      break;
  }
  // Make sure we only use this element dictionary in case we can't transition
  // to sealed, frozen elements kind.
  DirectHandle<NumberDictionary> new_element_dictionary;
  DirectHandle<Map> old_map(object->map(), isolate);
  old_map = Map::Update(isolate, old_map);
  DirectHandle<Map> transition_map;
  MaybeDirectHandle<Map> maybe_transition_map =
      TransitionsAccessor::SearchSpecial(isolate, old_map, *transition_marker);
  if (maybe_transition_map.ToHandle(&transition_map)) {
    DCHECK(transition_map->has_dictionary_elements() ||
           transition_map->has_typed_array_or_rab_gsab_typed_array_elements() ||
           transition_map->elements_kind() == SLOW_STRING_WRAPPER_ELEMENTS ||
           transition_map->has_any_nonextensible_elements());
    DCHECK(!transition_map->is_extensible());
    if (!transition_map->has_any_nonextensible_elements()) {
      new_element_dictionary = CreateElementDictionary(isolate, object);
    }
    JSObject::MigrateToMap(isolate, object, transition_map);
  } else if (TransitionsAccessor::CanHaveMoreTransitions(isolate, old_map)) {
    // Create a new descriptor array with the appropriate property attributes
    DirectHandle<Map> new_map = Map::CopyForPreventExtensions(
        isolate, old_map, attrs, transition_marker, "CopyForPreventExtensions");
    if (!new_map->has_any_nonextensible_elements()) {
      new_element_dictionary = CreateElementDictionary(isolate, object);
    }
    JSObject::MigrateToMap(isolate, object, new_map);
  } else {
    DCHECK(old_map->is_dictionary_map() || !old_map->is_prototype_map());
    // Slow path: need to normalize properties for safety
    NormalizeProperties(isolate, object, CLEAR_INOBJECT_PROPERTIES, 0,
                        "SlowPreventExtensions");
    // Create a new map, since other objects with this map may be extensible.
    // TODO(adamk): Extend the NormalizedMapCache to handle non-extensible maps.
    DirectHandle<Map> new_map =
        Map::Copy(isolate, direct_handle(object->map(), isolate),
                  "SlowCopyForPreventExtensions");
    new_map->set_is_extensible(false);
    new_element_dictionary = CreateElementDictionary(isolate, object);
    if (!new_element_dictionary.is_null()) {
      ElementsKind new_kind =
          IsStringWrapperElementsKind(old_map->elements_kind())
              ? SLOW_STRING_WRAPPER_ELEMENTS
              : DICTIONARY_ELEMENTS;
      new_map->set_elements_kind(new_kind);
    }
    JSObject::MigrateToMap(isolate, object, new_map);
    if (attrs != NONE) {
      ReadOnlyRoots roots(isolate);
      if (IsJSGlobalObject(*object)) {
        DirectHandle<GlobalDictionary> dictionary(
            Cast<JSGlobalObject>(*object)->global_dictionary(kAcquireLoad),
            isolate);
        JSObject::ApplyAttributesToDictionary(isolate, roots, dictionary,
                                              attrs);
      } else if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
        DirectHandle<SwissNameDictionary> dictionary(
            object->property_dictionary_swiss(), isolate);
        JSObject::ApplyAttributesToDictionary(isolate, roots, dictionary,
                                              attrs);
      } else {
        DirectHandle<NameDictionary> dictionary(object->property_dictionary(),
                                                isolate);
        JSObject::ApplyAttributesToDictionary(isolate, roots, dictionary,
                                              attrs);
      }
    }
  }
  if (object->map()->has_any_nonextensible_elements()) {
    DCHECK(new_element_dictionary.is_null());
    return Just(true);
  }
  // PreventExtensions works without modifications to typed array elements if
  // the typed array is fixed length; see #sec-typedarray-preventextensions.
  // Seal and freeze work only if there are no actual elements, because
  // TypedArray elements cannot be reconfigured; see
  // #sec-typedarray-defineownproperty.
  if (object->HasTypedArrayOrRabGsabTypedArrayElements()) {
    DCHECK(new_element_dictionary.is_null());
    if (attrs != NONE && Cast<JSTypedArray>(*object)->GetLength() > 0) {
      isolate->Throw(*isolate->factory()->NewTypeError(
          attrs == SEALED ? MessageTemplate::kCannotSealArrayBufferView
                          : MessageTemplate::kCannotFreezeArrayBufferView));
      return Nothing<bool>();
    }
    return Just(true);
  }
  DCHECK(object->map()->has_dictionary_elements() ||
         object->map()->elements_kind() == SLOW_STRING_WRAPPER_ELEMENTS);
  if (!new_element_dictionary.is_null()) {
    object->set_elements(*new_element_dictionary);
  }
  if (object->elements() !=
      ReadOnlyRoots(isolate).empty_slow_element_dictionary()) {
    DirectHandle<NumberDictionary> dictionary(object->element_dictionary(),
                                              isolate);
    // Make sure we never go back to the fast case
    object->RequireSlowElements(*dictionary);
    if (attrs != NONE) {
      JSObject::ApplyAttributesToDictionary(isolate, ReadOnlyRoots(isolate),
                                            dictionary, attrs);
    }
  }
  return Just(true);
}
References ApplyAttributesToDictionary(), v8::internal::TransitionsAccessor::CanHaveMoreTransitions(), v8::internal::CLEAR_INOBJECT_PROPERTIES, v8::internal::Map::Copy(), v8::internal::Map::CopyForPreventExtensions(), v8::internal::CreateElementDictionary(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::DICTIONARY_ELEMENTS, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{js-objects.cc}::FastTestIntegrityLevel(), v8::internal::FROZEN, v8::internal::PrototypeIterator::GetCurrent(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::DirectHandle< T >::is_null(), v8::internal::PrototypeIterator::IsAtEnd(), v8::internal::IsFrozenElementsKind(), v8::internal::IsSealedElementsKind(), v8::internal::IsStringWrapperElementsKind(), v8::Just(), v8::kAcquireLoad, v8::internal::Isolate::MayAccess(), MigrateToMap(), v8::internal::Isolate::native_context(), v8::internal::NONE, NormalizeProperties(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, v8::internal::Isolate::ReportFailedAccessCheck(), RETURN_FAILURE, RETURN_ON_EXCEPTION_VALUE, v8::internal::SEALED, v8::internal::TransitionsAccessor::SearchSpecial(), v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, v8::internal::Isolate::Throw(), v8::internal::MaybeDirectHandle< T >::ToHandle(), TransitionElementsKind(), v8::internal::UNREACHABLE(), v8::internal::Map::Update(), and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
PreventExtensionsWithTransition() [2/2]
template<PropertyAttributes attrs>
static V8_WARN_UNUSED_RESULT Maybe<bool> v8::internal::JSObject::PreventExtensionsWithTransition (Isolate * isolate, DirectHandle< JSObject > object, ShouldThrow should_throw) [static], [private]
PrintElementsTransition()
void v8::internal::JSObject::PrintElementsTransition (FILE * file, DirectHandle< JSObject > object, ElementsKind from_kind, DirectHandle< FixedArrayBase > from_elements, ElementsKind to_kind, DirectHandle< FixedArrayBase > to_elements) [static]
Definition at line 2988 of file js-objects.cc.
                                              {
  if (from_kind != to_kind) {
    OFStream os(file);
    os << "elements transition [" << ElementsKindToString(from_kind) << " -> "
       << ElementsKindToString(to_kind) << "] in ";
    JavaScriptFrame::PrintTop(Isolate::Current(), file, false, true);
    PrintF(file, " for ");
    ShortPrint(*object, file);
    PrintF(file, " from ");
    ShortPrint(*from_elements, file);
    PrintF(file, " to ");
    ShortPrint(*to_elements, file);
    PrintF(file, "\n");
  }
}
References v8::internal::Isolate::Current(), v8::internal::ElementsKindToString(), file(), v8::internal::PrintF(), v8::internal::JavaScriptFrame::PrintTop(), and v8::internal::ShortPrint().
Referenced by v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::BasicGrowCapacityAndConvertImpl(), TransitionElementsKind(), and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::TransitionElementsKindImpl().
PrintInstanceMigration()
void v8::internal::JSObject::PrintInstanceMigration (FILE * file, Tagged< Map > original_map, Tagged< Map > new_map)
Definition at line 3007 of file js-objects.cc.
                                                           {
  if (new_map->is_dictionary_map()) {
    PrintF(file, "[migrating to slow]\n");
    return;
  }
  PrintF(file, "[migrating]");
  Isolate* isolate = Isolate::Current();
  Tagged<DescriptorArray> o = original_map->instance_descriptors(isolate);
  Tagged<DescriptorArray> n = new_map->instance_descriptors(isolate);
  for (InternalIndex i : original_map->IterateOwnDescriptors()) {
    Representation o_r = o->GetDetails(i).representation();
    Representation n_r = n->GetDetails(i).representation();
    if (!o_r.Equals(n_r)) {
      Cast<String>(o->GetKey(i))->PrintOn(file);
      PrintF(file, ":%s->%s ", o_r.Mnemonic(), n_r.Mnemonic());
    } else if (o->GetDetails(i).location() == PropertyLocation::kDescriptor &&
               n->GetDetails(i).location() == PropertyLocation::kField) {
      Tagged<Name> name = o->GetKey(i);
      if (IsString(name)) {
        Cast<String>(name)->PrintOn(file);
      } else {
        PrintF(file, "{symbol %p}", reinterpret_cast<void*>(name.ptr()));
      }
      PrintF(file, " ");
    }
  }
  if (original_map->elements_kind() != new_map->elements_kind()) {
    PrintF(file, "elements_kind[%i->%i]", original_map->elements_kind(),
           new_map->elements_kind());
  }
  PrintF(file, "\n");
}
References v8::internal::Isolate::Current(), v8::internal::Representation::Equals(), file(), v8::internal::kDescriptor, v8::internal::kField, v8::internal::Representation::Mnemonic(), v8::internal::name, and v8::internal::PrintF().
PrototypeHasNoElements()
bool v8::internal::JSObject::PrototypeHasNoElements (Isolate * isolate, Tagged< JSObject > object) [inline], [static]
Definition at line 138 of file js-objects-inl.h.
                                                               {
  DisallowGarbageCollection no_gc;
  Tagged<HeapObject> prototype = Cast<HeapObject>(object->map()->prototype());
  ReadOnlyRoots roots(isolate);
  Tagged<HeapObject> null = roots.null_value();
  Tagged<FixedArrayBase> empty_fixed_array = roots.empty_fixed_array();
  Tagged<FixedArrayBase> empty_slow_element_dictionary =
      roots.empty_slow_element_dictionary();
  while (prototype != null) {
    Tagged<Map> map = prototype->map();
    if (IsCustomElementsReceiverMap(map)) return false;
    Tagged<FixedArrayBase> elements = Cast<JSObject>(prototype)->elements();
    if (elements != empty_fixed_array &&
        elements != empty_slow_element_dictionary) {
      return false;
    }
    prototype = Cast<HeapObject>(map->prototype());
  }
  return true;
}
References v8::internal::IsCustomElementsReceiverMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::prototype.
Referenced by v8::internal::anonymous_namespace{objects.cc}::CreateListFromArrayLikeFastPath(), v8::internal::anonymous_namespace{builtins-array.cc}::HasOnlySimpleReceiverElements(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IndexOfValueImpl(), v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::IndexOfValueImpl(), v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::IndexOfValueImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IndexOfValueImpl(), v8::internal::anonymous_namespace{builtins-array.cc}::IsJSArrayFastElementMovingAllowed(), and v8::internal::RUNTIME_FUNCTION().
PrototypeRegistryCompactionCallback()
void v8::internal::JSObject::PrototypeRegistryCompactionCallback (Tagged< HeapObject > value, int old_index, int new_index) [static]
Definition at line 4903 of file js-objects.cc.
                                                                  {
  DCHECK(IsMap(value) && Cast<Map>(value)->is_prototype_map());
  Tagged<Map> map = Cast<Map>(value);
  DCHECK(IsPrototypeInfo(map->prototype_info()));
  Tagged<PrototypeInfo> proto_info = Cast<PrototypeInfo>(map->prototype_info());
  DCHECK_EQ(old_index, proto_info->registry_slot());
  proto_info->set_registry_slot(new_index);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::is_prototype_map, and v8::internal::value.
Referenced by v8::internal::Heap::CompactWeakArrayLists().
RawFastInobjectPropertyAtCompareAndSwap()
Tagged< Object > v8::internal::JSObject::RawFastInobjectPropertyAtCompareAndSwap (FieldIndex index, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag) [inline]
Definition at line 546 of file js-objects-inl.h.
                         {
  DCHECK(index.is_inobject());
  DCHECK(IsShared(value));
  Tagged<Object> previous_value =
      SEQ_CST_COMPARE_AND_SWAP_FIELD(*this, index.offset(), expected, value);
  if (previous_value == expected) {
    CONDITIONAL_WRITE_BARRIER(*this, index.offset(), value,
                              UPDATE_WRITE_BARRIER);
  }
  return previous_value;
}
References CONDITIONAL_WRITE_BARRIER, DCHECK, v8::internal::index, v8::internal::IsShared(), SEQ_CST_COMPARE_AND_SWAP_FIELD, v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
RawFastInobjectPropertyAtPut() [1/2]
void v8::internal::JSObject::RawFastInobjectPropertyAtPut (FieldIndex index, Tagged< Object > value, SeqCstAccessTag tag) [inline]
Definition at line 470 of file js-objects-inl.h.
                                                                 {
  DCHECK(index.is_inobject());
  DCHECK(IsShared(value));
  SEQ_CST_WRITE_FIELD(*this, index.offset(), value);
  CONDITIONAL_WRITE_BARRIER(*this, index.offset(), value, UPDATE_WRITE_BARRIER);
}
References CONDITIONAL_WRITE_BARRIER, DCHECK, v8::internal::index, v8::internal::IsShared(), SEQ_CST_WRITE_FIELD, v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
RawFastInobjectPropertyAtPut() [2/2]
void v8::internal::JSObject::RawFastInobjectPropertyAtPut (FieldIndex index, Tagged< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 461 of file js-objects-inl.h.
                                                                   {
  DCHECK(index.is_inobject());
  int offset = index.offset();
  RELAXED_WRITE_FIELD(*this, offset, value);
  CONDITIONAL_WRITE_BARRIER(*this, offset, value, mode);
}
References CONDITIONAL_WRITE_BARRIER, DCHECK, v8::internal::index, mode(), RELAXED_WRITE_FIELD, and v8::internal::value.
RawFastInobjectPropertyAtSwap()
Tagged< Object > v8::internal::JSObject::RawFastInobjectPropertyAtSwap (FieldIndex index, Tagged< Object > value, SeqCstAccessTag tag) [inline]
Definition at line 526 of file js-objects-inl.h.
                                                                            {
  DCHECK(index.is_inobject());
  DCHECK(IsShared(value));
  int offset = index.offset();
  Tagged<Object> old_value = SEQ_CST_SWAP_FIELD(*this, offset, value);
  CONDITIONAL_WRITE_BARRIER(*this, offset, value, UPDATE_WRITE_BARRIER);
  return old_value;
}
References CONDITIONAL_WRITE_BARRIER, DCHECK, v8::internal::index, v8::internal::IsShared(), SEQ_CST_SWAP_FIELD, v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
RawFastPropertyAt() [1/4]
Tagged< JSAny > v8::internal::JSObject::RawFastPropertyAt (FieldIndex index) const [inline]
Definition at line 391 of file js-objects-inl.h.
                                                                {
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  return RawFastPropertyAt(cage_base, index);
}
References v8::internal::GetPtrComprCageBase(), and v8::internal::index.
Referenced by SlowReverseLookup().
RawFastPropertyAt() [2/4]
Tagged< JSAny > v8::internal::JSObject::RawFastPropertyAt (FieldIndex index, SeqCstAccessTag tag) const [inline]
Definition at line 408 of file js-objects-inl.h.
                                                                     {
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  return RawFastPropertyAt(cage_base, index, tag);
}
References v8::internal::GetPtrComprCageBase(), and v8::internal::index.
RawFastPropertyAt() [3/4]
Tagged< JSAny > v8::internal::JSObject::RawFastPropertyAt (PtrComprCageBase cage_base, FieldIndex index) const [inline]
Definition at line 396 of file js-objects-inl.h.
                                                                  {
  if (index.is_inobject()) {
    return TaggedField<JSAny>::Relaxed_Load(cage_base, *this, index.offset());
  } else {
    return property_array(cage_base)->get(cage_base,
                                          index.outobject_array_index());
  }
}
References v8::internal::index, and v8::base::Relaxed_Load().
RawFastPropertyAt() [4/4]
Tagged< JSAny > v8::internal::JSObject::RawFastPropertyAt (PtrComprCageBase cage_base, FieldIndex index, SeqCstAccessTag tag) const [inline]
Definition at line 414 of file js-objects-inl.h.
                                                                     {
  if (index.is_inobject()) {
    return TaggedField<JSAny>::SeqCst_Load(cage_base, *this, index.offset());
  } else {
    return property_array(cage_base)->get(cage_base,
                                          index.outobject_array_index(), tag);
  }
}
References v8::internal::index, and v8::base::SeqCst_Load().
RawFastPropertyAtCompareAndSwap()
Tagged< Object > v8::internal::JSObject::RawFastPropertyAtCompareAndSwap (FieldIndex index, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag)
Definition at line 5672 of file js-objects.cc.
                         {
  return HeapObject::SeqCst_CompareAndSwapField(
      expected, value,
      [=, this](Tagged<Object> expected_value, Tagged<Object> new_value) {
        return RawFastPropertyAtCompareAndSwapInternal(index, expected_value,
                                                       new_value, tag);
      });
}
References v8::internal::index, RawFastPropertyAtCompareAndSwapInternal(), and v8::internal::value.
RawFastPropertyAtCompareAndSwapInternal()
Tagged< Object > v8::internal::JSObject::RawFastPropertyAtCompareAndSwapInternal (FieldIndex index, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag) [inline], [private]
Definition at line 560 of file js-objects-inl.h.
                         {
  if (index.is_inobject()) {
    return RawFastInobjectPropertyAtCompareAndSwap(index, expected, value, tag);
  }
  return property_array()->CompareAndSwap(index.outobject_array_index(),
                                          expected, value, tag);
}
References v8::internal::index, and v8::internal::value.
Referenced by RawFastPropertyAtCompareAndSwap().
RawFastPropertyAtSwap()
Tagged< Object > v8::internal::JSObject::RawFastPropertyAtSwap (FieldIndex index, Tagged< Object > value, SeqCstAccessTag tag) [inline]
Definition at line 537 of file js-objects-inl.h.
                                                                    {
  if (index.is_inobject()) {
    return RawFastInobjectPropertyAtSwap(index, value, tag);
  }
  return property_array()->Swap(index.outobject_array_index(), value, tag);
}
References v8::internal::index, and v8::internal::value.
RawInobjectPropertyAt()
std::optional< Tagged< Object > > v8::internal::JSObject::RawInobjectPropertyAt (PtrComprCageBase cage_base, Tagged< Map > original_map, FieldIndex index) const [inline]
Definition at line 425 of file js-objects-inl.h.
                            {
  CHECK(index.is_inobject());
  // This method implements a "snapshot" protocol to protect against reading out
  // of bounds of an object. It's used to access a fast in-object property from
  // a background thread with no locking. That caller does have the guarantee
  // that a garbage collection cannot happen during its query. However, it must
  // contend with the main thread altering the object in heavy ways through
  // object migration. Specifically, the object can get smaller. Initially, this
  // may seem benign, because object migration fills the freed-up space with
  // FillerMap words which, even though they offer wrong values, are at
  // least tagged values.
  // However, there is an additional danger. Sweeper threads may discover the
  // filler words and offer that space to the main thread for allocation. Should
  // a HeapNumber be allocated into that space while we're reading a property at
  // that location (from our out-of-date information), we risk interpreting a
  // double value as a pointer. This must be prevented.
  //
  // We do this by:
  //
  // a) Reading the map first
  // b) Reading the property with acquire semantics (but do not inspect it!)
  // c) Re-read the map with acquire semantics.
  //
  // Only if the maps match can the property be inspected. It may have a "wrong"
  // value, but it will be within the bounds of the objects instance size as
  // given by the map and it will be a valid Smi or object pointer.
  Tagged<Object> maybe_tagged_object =
      TaggedField<Object>::Acquire_Load(cage_base, *this, index.offset());
  if (original_map != map(cage_base, kAcquireLoad)) return {};
  return maybe_tagged_object;
}
References v8::base::Acquire_Load(), CHECK, v8::internal::index, and v8::kAcquireLoad.
ReadFromOptionsBag()
MaybeDirectHandle< Object > v8::internal::JSObject::ReadFromOptionsBag (DirectHandle< Object > options, DirectHandle< String > option_name, Isolate * isolate) [static]
Definition at line 4369 of file js-objects.cc.
                      {
  if (IsJSReceiver(*options)) {
    DirectHandle<JSReceiver> js_options = Cast<JSReceiver>(options);
    return JSObject::GetProperty(isolate, js_options, option_name);
  }
  return MaybeDirectHandle<Object>(isolate->factory()->undefined_value());
}
References v8::internal::Isolate::factory().
Referenced by v8::internal::BUILTIN(), and v8::internal::anonymous_namespace{builtins-typed-array.cc}::HandleOptionsBag().
ReferencesObject()
bool v8::internal::JSObject::ReferencesObject (Tagged< Object > obj)
ReferencesObjectFromElements()
bool v8::internal::JSObject::ReferencesObjectFromElements (Tagged< FixedArray > elements, ElementsKind kind, Tagged< Object > object) [private]
ReoptimizeIfPrototype()
void v8::internal::JSObject::ReoptimizeIfPrototype (DirectHandle< JSObject > object) [static]
Definition at line 5048 of file js-objects.cc.
                                                                  {
  {
    Tagged<Map> map = object->map();
    if (!map->is_prototype_map()) return;
    if (!map->should_be_fast_prototype_map()) return;
  }
  OptimizeAsPrototype(object);
}
References OptimizeAsPrototype().
Referenced by v8::internal::LookupIterator::Delete(), v8::internal::LookupIterator::TransitionToAccessorPair(), and v8::internal::LookupIterator::TransitionToAccessorProperty().
RequireSlowElements()
void v8::internal::JSObject::RequireSlowElements (Tagged< NumberDictionary > dictionary)
Definition at line 4069 of file js-objects.cc.
                                                                      {
  DCHECK_NE(dictionary,
            ReadOnlyRoots(Isolate::Current()).empty_slow_element_dictionary());
  if (dictionary->requires_slow_elements()) return;
  dictionary->set_requires_slow_elements();
  if (map()->is_prototype_map()) {
    // If this object is a prototype (the callee will check), invalidate any
    // prototype chains involving it.
    InvalidatePrototypeChains(map());
  }
}
References v8::internal::Isolate::Current(), DCHECK_NE, InvalidatePrototypeChains(), and v8::internal::is_prototype_map.
set_elements()
void v8::internal::JSObject::set_elements (Tagged< FixedArrayBase > value, ReleaseStoreTag tag, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [delete]
Definition at line 78 of file js-objects-inl.h.
                                                   {
  // Note the relaxed atomic store.
  TaggedField<FixedArrayBase, kElementsOffset>::Relaxed_Store(*this, value);
  CONDITIONAL_WRITE_BARRIER(*this, kElementsOffset, value, mode);
}
References CONDITIONAL_WRITE_BARRIER, mode(), v8::base::Relaxed_Store(), and v8::internal::value.
SetAccessor()
MaybeDirectHandle< Object > v8::internal::JSObject::SetAccessor (DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< AccessorInfo > info, PropertyAttributes attributes) [static]
Definition at line 4802 of file js-objects.cc.
                                                                               {
  Isolate* isolate = Isolate::Current();
  PropertyKey key(isolate, name);
  LookupIterator it(isolate, object, key, LookupIterator::OWN_SKIP_INTERCEPTOR);
  // Duplicate ACCESS_CHECK outside of GetPropertyAttributes for the case that
  // the FailedAccessCheckCallbackFunction doesn't throw an exception.
  while (it.state() == LookupIterator::ACCESS_CHECK) {
    if (!it.HasAccess()) {
      RETURN_ON_EXCEPTION(isolate, isolate->ReportFailedAccessCheck(object));
      UNREACHABLE();
    }
    it.Next();
  }
  // Ignore accessors on typed arrays.
  if (it.IsElement() && object->HasTypedArrayOrRabGsabTypedArrayElements()) {
    return it.factory()->undefined_value();
  }
  Maybe<bool> can_define = JSObject::CheckIfCanDefineAsConfigurable(
      isolate, &it, info, Nothing<ShouldThrow>());
  MAYBE_RETURN_NULL(can_define);
  if (!can_define.FromJust()) return it.factory()->undefined_value();
  it.TransitionToAccessorPair(info, attributes);
  return object;
}
References v8::internal::LookupIterator::ACCESS_CHECK, CheckIfCanDefineAsConfigurable(), v8::internal::Isolate::Current(), v8::internal::LookupIterator::factory(), v8::Maybe< T >::FromJust(), v8::internal::LookupIterator::HasAccess(), v8::internal::LookupIterator::IsElement(), v8::internal::key, MAYBE_RETURN_NULL, v8::internal::name, v8::internal::LookupIterator::Next(), v8::internal::LookupIterator::OWN_SKIP_INTERCEPTOR, v8::internal::Isolate::ReportFailedAccessCheck(), RETURN_ON_EXCEPTION, v8::internal::LookupIterator::state(), v8::internal::LookupIterator::TransitionToAccessorPair(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::anonymous_namespace{api-natives.cc}::ConfigureInstance(), v8::ObjectSetAccessor(), and v8::internal::ScopeIterator::ScopeObject().
SetEmbedderField() [1/2]
void v8::internal::JSObject::SetEmbedderField (int index, Tagged< Object > value) [inline]
Definition at line 369 of file js-objects-inl.h.
                                                               {
  EmbedderDataSlot::store_tagged(Tagged(*this), index, value);
}
References v8::internal::index, v8::internal::Tagged(), and v8::internal::value.
SetEmbedderField() [2/2]
void v8::internal::JSObject::SetEmbedderField (int index, Tagged< Smi > value) [inline]
Definition at line 373 of file js-objects-inl.h.
                                                            {
  EmbedderDataSlot(Tagged(*this), index).store_smi(value);
}
References v8::internal::index, v8::internal::EmbedderDataSlot::store_smi(), v8::internal::Tagged(), and v8::internal::value.
SetImmutableProto()
void v8::internal::JSObject::SetImmutableProto (Isolate * isolate, DirectHandle< JSObject > object) [static]
Definition at line 5357 of file js-objects.cc.
                                                                {
  DirectHandle<Map> map(object->map(), isolate);
  // Nothing to do if prototype is already set.
  if (map->is_immutable_proto()) return;
  DirectHandle<Map> new_map = Map::TransitionToImmutableProto(isolate, map);
  object->set_map(isolate, *new_map, kReleaseStore);
}
References v8::kReleaseStore, and v8::internal::Map::TransitionToImmutableProto().
Referenced by v8::internal::anonymous_namespace{api-natives.cc}::InstantiateObject().
SetMapAndElements()
void v8::internal::JSObject::SetMapAndElements (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Map > map, DirectHandle< FixedArrayBase > elements) [inline], [static]
Definition at line 275 of file js-objects-inl.h.
                                                                     {
  JSObject::MigrateToMap(isolate, object, new_map);
  DCHECK((object->map()->has_fast_smi_or_object_elements() ||
          (*value == ReadOnlyRoots(isolate).empty_fixed_array()) ||
          object->map()->has_fast_string_wrapper_elements()) ==
         (value->map() == ReadOnlyRoots(isolate).fixed_array_map() ||
          value->map() == ReadOnlyRoots(isolate).fixed_cow_array_map()));
  DCHECK((*value == ReadOnlyRoots(isolate).empty_fixed_array()) ||
         (object->map()->has_fast_double_elements() ==
          IsFixedDoubleArray(*value)));
  object->set_elements(*value);
}
References DCHECK, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::BasicGrowCapacityAndConvertImpl(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::TransitionElementsKindImpl(), and v8::internal::anonymous_namespace{builtins-array.cc}::TryFastArrayFill().
SetNormalizedElement()
void v8::internal::JSObject::SetNormalizedElement (DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyDetails details) [static]
Definition at line 2829 of file js-objects.cc.
                                                             {
  DCHECK_EQ(object->GetElementsKind(), DICTIONARY_ELEMENTS);
  Isolate* isolate = Isolate::Current();
  DirectHandle<NumberDictionary> dictionary(
      Cast<NumberDictionary>(object->elements()), isolate);
  dictionary =
      NumberDictionary::Set(isolate, dictionary, index, value, object, details);
  object->set_elements(*dictionary);
}
References v8::internal::Cast< NumberDictionary >(), v8::internal::Isolate::Current(), DCHECK_EQ, v8::internal::DICTIONARY_ELEMENTS, v8::internal::index, and v8::internal::value.
Referenced by v8::internal::Module::GetModuleNamespace().
SetNormalizedProperty()
void v8::internal::JSObject::SetNormalizedProperty (DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > value, PropertyDetails details) [static]
Definition at line 2757 of file js-objects.cc.
                                                              {
  DCHECK(!object->HasFastProperties());
  DCHECK(IsUniqueName(*name));
  Isolate* isolate = Isolate::Current();
  uint32_t hash = name->hash();
  if (IsJSGlobalObject(*object)) {
    auto global_obj = Cast<JSGlobalObject>(object);
    DirectHandle<GlobalDictionary> dictionary(
        global_obj->global_dictionary(kAcquireLoad), isolate);
    ReadOnlyRoots roots(isolate);
    InternalIndex entry = dictionary->FindEntry(isolate, roots, name, hash);
    if (entry.is_not_found()) {
      DCHECK_IMPLIES(global_obj->map()->is_prototype_map(),
                     Map::IsPrototypeChainInvalidated(global_obj->map()));
      auto cell_type = IsUndefined(*value, roots) ? PropertyCellType::kUndefined
                                                  : PropertyCellType::kConstant;
      details = details.set_cell_type(cell_type);
      auto cell = isolate->factory()->NewPropertyCell(name, details, value);
      dictionary =
          GlobalDictionary::Add(isolate, dictionary, name, cell, details);
      global_obj->set_global_dictionary(*dictionary, kReleaseStore);
    } else {
      PropertyCell::PrepareForAndSetValue(isolate, dictionary, entry, value,
                                          details);
      DCHECK_EQ(dictionary->CellAt(entry)->value(), *value);
    }
  } else {
    if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      DirectHandle<SwissNameDictionary> dictionary(
          object->property_dictionary_swiss(), isolate);
      InternalIndex entry = dictionary->FindEntry(isolate, *name);
      if (entry.is_not_found()) {
        DCHECK_IMPLIES(object->map()->is_prototype_map(),
                       Map::IsPrototypeChainInvalidated(object->map()));
        dictionary =
            SwissNameDictionary::Add(isolate, dictionary, name, value, details);
        object->SetProperties(*dictionary);
      } else {
        dictionary->ValueAtPut(entry, *value);
        dictionary->DetailsAtPut(entry, details);
      }
    } else {
      DirectHandle<NameDictionary> dictionary(object->property_dictionary(),
                                              isolate);
      InternalIndex entry = dictionary->FindEntry(isolate, name);
      if (entry.is_not_found()) {
        DCHECK_IMPLIES(object->map()->is_prototype_map(),
                       Map::IsPrototypeChainInvalidated(object->map()));
        dictionary =
            NameDictionary::Add(isolate, dictionary, name, value, details);
        object->SetProperties(*dictionary);
      } else {
        PropertyDetails original_details = dictionary->DetailsAt(entry);
        int enumeration_index = original_details.dictionary_index();
        DCHECK_GT(enumeration_index, 0);
        details = details.set_index(enumeration_index);
        dictionary->SetEntry(entry, *name, *value, details);
      }
      // TODO(pthier): Add flags to swiss dictionaries.
      if (name->IsInteresting(isolate)) {
        dictionary->set_may_have_interesting_properties(true);
      }
    }
  }
}
References v8::bigint::Add(), v8::internal::Isolate::Current(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, DCHECK_IMPLIES, v8::internal::PropertyDetails::dictionary_index(), v8::internal::Isolate::factory(), v8::internal::InternalIndex::is_not_found(), v8::internal::Map::IsPrototypeChainInvalidated(), v8::internal::IsUniqueName(), v8::kAcquireLoad, v8::internal::kConstant, v8::kReleaseStore, v8::internal::kUndefined, v8::internal::name, v8::internal::Factory::NewPropertyCell(), v8::internal::PropertyCell::PrepareForAndSetValue(), v8::internal::PropertyDetails::set_cell_type(), v8::internal::PropertyDetails::set_index(), V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, and v8::internal::value.
Referenced by v8::internal::Module::GetModuleNamespace(), v8::internal::wasm::JSPrototypesSetup::InstallExport(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::Genesis::TransferNamedProperties(), and v8::internal::LookupIterator::TransitionToAccessorPair().
SetOwnElementIgnoreAttributes()
MaybeDirectHandle< Object > v8::internal::JSObject::SetOwnElementIgnoreAttributes (DirectHandle< JSObject > object, size_t index, DirectHandle< Object > value, PropertyAttributes attributes) [static]
Definition at line 3824 of file js-objects.cc.
                                   {
  DCHECK(!IsJSTypedArray(*object));
  Isolate* isolate = Isolate::Current();
  LookupIterator it(isolate, object, index, object, LookupIterator::OWN);
  return DefineOwnPropertyIgnoreAttributes(&it, value, attributes);
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), DefineOwnPropertyIgnoreAttributes(), v8::internal::index, v8::internal::LookupIterator::OWN, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{runtime-literals.cc}::CreateObjectLiteral().
SetOwnPropertyIgnoreAttributes()
MaybeDirectHandle< Object > v8::internal::JSObject::SetOwnPropertyIgnoreAttributes (DirectHandle< JSObject > object, DirectHandle< Name > name, DirectHandle< Object > value, PropertyAttributes attributes) [static]
Definition at line 3815 of file js-objects.cc.
                                                               {
  DCHECK(!IsTheHole(*value));
  LookupIterator it(Isolate::Current(), object, name, object,
                    LookupIterator::OWN);
  return DefineOwnPropertyIgnoreAttributes(&it, value, attributes);
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), DefineOwnPropertyIgnoreAttributes(), v8::internal::name, v8::internal::LookupIterator::OWN, and v8::internal::value.
Referenced by v8::internal::ErrorUtils::Construct(), v8::internal::anonymous_namespace{runtime-literals.cc}::CreateObjectLiteral(), v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareEvalHelper(), v8::internal::anonymous_namespace{messages.cc}::GetStackFrames(), v8::internal::Genesis::GetThrowTypeErrorIntrinsic(), v8::internal::Factory::NewSuppressedErrorAtDisposal(), v8::internal::ValueDeserializer::ReadJSError(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::DebugEvaluate::WithTopmostArguments().
SetPropertyWithFailedAccessCheck()
Maybe< bool > v8::internal::JSObject::SetPropertyWithFailedAccessCheck (LookupIterator * it, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw) [static], [private]
Definition at line 2727 of file js-objects.cc.
                                     {
  Isolate* isolate = it->isolate();
  DirectHandle<JSObject> checked = it->GetHolder<JSObject>();
  DirectHandle<InterceptorInfo> interceptor =
      it->GetInterceptorForFailedAccessCheck();
  if (!interceptor.is_null()) {
    InterceptorResult result;
    if (!SetPropertyWithInterceptorInternal(it, interceptor, should_throw,
                                            value)
             .To(&result)) {
      // An exception was thrown in the interceptor. Propagate.
      return Nothing<bool>();
    }
    switch (result) {
      case InterceptorResult::kFalse:
        return Just(false);
      case InterceptorResult::kTrue:
        return Just(true);
      case InterceptorResult::kNotIntercepted:
        // Fall through to report failed access check.
        break;
    }
  }
  RETURN_ON_EXCEPTION_VALUE(isolate, isolate->ReportFailedAccessCheck(checked),
                            Nothing<bool>());
  UNREACHABLE();
}
References v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetInterceptorForFailedAccessCheck(), v8::internal::LookupIterator::isolate(), v8::Just(), v8::internal::kFalse, v8::internal::kNotIntercepted, v8::internal::kTrue, v8::internal::Isolate::ReportFailedAccessCheck(), v8::base::internal::result, RETURN_ON_EXCEPTION_VALUE, v8::internal::anonymous_namespace{js-objects.cc}::SetPropertyWithInterceptorInternal(), v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by v8::internal::Object::SetPropertyInternal(), and v8::internal::Object::SetSuperProperty().
SetPropertyWithInterceptor()
Maybe< InterceptorResult > v8::internal::JSObject::SetPropertyWithInterceptor (LookupIterator * it, Maybe< ShouldThrow > should_throw, DirectHandle< Object > value) [static]
Definition at line 3493 of file js-objects.cc.
                                {
  DCHECK_EQ(LookupIterator::INTERCEPTOR, it->state());
  return SetPropertyWithInterceptorInternal(it, it->GetInterceptor(),
                                            should_throw, value);
}
References DCHECK_EQ, v8::internal::LookupIterator::GetInterceptor(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::anonymous_namespace{js-objects.cc}::SetPropertyWithInterceptorInternal(), v8::internal::LookupIterator::state(), and v8::internal::value.
Referenced by DefineOwnPropertyIgnoreAttributes(), and v8::internal::Object::SetPropertyInternal().
SetPrototype()
Maybe< bool > v8::internal::JSObject::SetPrototype (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Object > value, bool from_javascript, ShouldThrow should_throw) [static]
Definition at line 5255 of file js-objects.cc.
                                                             {
#ifdef DEBUG
  int size = object->Size();
#endif
  if (from_javascript) {
    if (IsAccessCheckNeeded(*object) &&
        !isolate->MayAccess(isolate->native_context(), object)) {
      RETURN_ON_EXCEPTION_VALUE(
          isolate, isolate->ReportFailedAccessCheck(object), Nothing<bool>());
      UNREACHABLE();
    }
  } else {
    DCHECK(!IsAccessCheckNeeded(*object));
  }
  // Silently ignore the change if value is not a JSReceiver or null.
  // SpiderMonkey behaves this way.
  DirectHandle<JSPrototype> value;
  if (!TryCast(value_obj, &value)) return Just(true);
  bool all_extensible = object->map()->is_extensible();
  DirectHandle<JSObject> real_receiver = object;
  if (from_javascript) {
    // Find the first object in the chain whose prototype object is not
    // hidden.
    PrototypeIterator iter(isolate, real_receiver, kStartAtPrototype,
                           PrototypeIterator::END_AT_NON_HIDDEN);
    while (!iter.IsAtEnd()) {
      // Casting to JSObject is fine because hidden prototypes are never
      // JSProxies.
      real_receiver = PrototypeIterator::GetCurrent<JSObject>(iter);
      iter.Advance();
      all_extensible = all_extensible && real_receiver->map()->is_extensible();
    }
  }
  DirectHandle<Map> map(real_receiver->map(), isolate);
  // Nothing to do if prototype is already set.
  if (map->prototype() == *value) return Just(true);
  bool immutable_proto = map->is_immutable_proto();
  if (immutable_proto) {
    DirectHandle<Object> msg;
    if (IsJSObjectPrototype(*object)) { // is [[Object.prototype]]
      msg = isolate->factory()->Object_prototype_string();
    } else {
      msg = object;
    }
    RETURN_FAILURE(isolate, should_throw,
                   NewTypeError(MessageTemplate::kImmutablePrototypeSet, msg));
  }
  // From 6.1.7.3 Invariants of the Essential Internal Methods
  //
  // [[SetPrototypeOf]] (V)
  // * ...
  // * If target is non-extensible, [[SetPrototypeOf]] must return false,
  // unless V is the SameValue as the target's observed [[GetPrototypeOf]]
  // value.
  if (!all_extensible) {
    RETURN_FAILURE(isolate, should_throw,
                   NewTypeError(MessageTemplate::kNonExtensibleProto, object));
  }
  // Before we can set the prototype we need to be sure prototype cycles are
  // prevented. It is sufficient to validate that the receiver is not in the
  // new prototype chain.
  if (Tagged<JSReceiver> receiver; TryCast<JSReceiver>(*value, &receiver)) {
    for (PrototypeIterator iter(isolate, receiver, kStartAtReceiver);
         !iter.IsAtEnd(); iter.Advance()) {
      if (iter.GetCurrent<JSReceiver>() == *object) {
        // Cycle detected.
        RETURN_FAILURE(isolate, should_throw,
                       NewTypeError(MessageTemplate::kCyclicProto));
      }
    }
  }
  // Set the new prototype of the object.
  isolate->UpdateProtectorsOnSetPrototype(real_receiver, value);
  DirectHandle<Map> new_map =
      v8_flags.move_prototype_transitions_first
          ? MapUpdater(isolate, map).ApplyPrototypeTransition(value)
          : Map::TransitionToUpdatePrototype(isolate, map, value);
  DCHECK(new_map->prototype() == *value);
  JSObject::MigrateToMap(isolate, real_receiver, new_map);
  DCHECK_IMPLIES(!new_map->is_dictionary_map() && !map->is_deprecated() &&
                     !IsUndefined(new_map->GetBackPointer()),
                 size == object->Size());
  return Just(true);
}
References v8::internal::PrototypeIterator::Advance(), v8::internal::MapUpdater::ApplyPrototypeTransition(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::PrototypeIterator::END_AT_NON_HIDDEN, v8::internal::Isolate::factory(), v8::internal::PrototypeIterator::IsAtEnd(), v8::Just(), v8::internal::kStartAtPrototype, v8::internal::kStartAtReceiver, v8::internal::Isolate::MayAccess(), MigrateToMap(), v8::internal::Isolate::native_context(), v8::internal::Isolate::ReportFailedAccessCheck(), RETURN_FAILURE, RETURN_ON_EXCEPTION_VALUE, size(), v8::internal::Map::TransitionToUpdatePrototype(), v8::internal::TryCast(), v8::internal::UNREACHABLE(), v8::internal::Isolate::UpdateProtectorsOnSetPrototype(), v8::internal::v8_flags, and v8::internal::value.
Referenced by v8::internal::AddWasmTableObjectInternalProperties(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxy::Create(), v8::internal::Genesis::InstallTypedArray(), v8::internal::JSReceiver::SetPrototype(), v8::anonymous_namespace{api.cc}::SetPrototypeImpl(), and v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::TransferPrototype().
SlowReverseLookup()
Tagged< Object > v8::internal::JSObject::SlowReverseLookup (Tagged< Object > value)
Definition at line 4862 of file js-objects.cc.
                                                               {
  if (HasFastProperties()) {
    Tagged<DescriptorArray> descs = map()->instance_descriptors();
    bool value_is_number = IsNumber(value);
    for (InternalIndex i : map()->IterateOwnDescriptors()) {
      PropertyDetails details = descs->GetDetails(i);
      if (details.location() == PropertyLocation::kField) {
        DCHECK_EQ(PropertyKind::kData, details.kind());
        FieldIndex field_index = FieldIndex::ForDetails(map(), details);
        Tagged<Object> property = RawFastPropertyAt(field_index);
        if (field_index.is_double()) {
          DCHECK(IsHeapNumber(property));
          if (value_is_number && Cast<HeapNumber>(property)->value() ==
                                     Object::NumberValue(Cast<Number>(value))) {
            return descs->GetKey(i);
          }
        } else if (property == value) {
          return descs->GetKey(i);
        }
      } else {
        DCHECK_EQ(PropertyLocation::kDescriptor, details.location());
        if (details.kind() == PropertyKind::kData) {
          if (descs->GetStrongValue(i) == value) {
            return descs->GetKey(i);
          }
        }
      }
    }
    return GetReadOnlyRoots().undefined_value();
  } else if (IsJSGlobalObject(*this)) {
    return Cast<JSGlobalObject>(*this)
        ->global_dictionary(kAcquireLoad)
        ->SlowReverseLookup(value);
  } else if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    return property_dictionary_swiss()->SlowReverseLookup(Isolate::Current(),
                                                          value);
  } else {
    return property_dictionary()->SlowReverseLookup(value);
  }
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::FieldIndex::ForDetails(), v8::internal::GetReadOnlyRoots(), v8::internal::FieldIndex::is_double(), v8::internal::IsNumber(), v8::kAcquireLoad, v8::internal::kData, v8::internal::kDescriptor, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), v8::internal::Object::NumberValue(), RawFastPropertyAt(), V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, and v8::internal::value.
TestIntegrityLevel()
Maybe< bool > v8::internal::JSObject::TestIntegrityLevel (Isolate * isolate, DirectHandle< JSObject > object, IntegrityLevel lvl) [static]
Definition at line 4289 of file js-objects.cc.
                                                               {
  if (!IsCustomElementsReceiverMap(object->map()) &&
      !object->HasSloppyArgumentsElements()) {
    return Just(FastTestIntegrityLevel(isolate, *object, level));
  }
  return GenericTestIntegrityLevel(isolate, Cast<JSReceiver>(object), level);
}
References v8::internal::anonymous_namespace{js-objects.cc}::FastTestIntegrityLevel(), v8::internal::anonymous_namespace{js-objects.cc}::GenericTestIntegrityLevel(), v8::internal::IsCustomElementsReceiverMap(), and v8::Just().
Referenced by v8::internal::JSReceiver::SetIntegrityLevel(), and v8::internal::JSReceiver::TestIntegrityLevel().
TransitionElementsKind()
void v8::internal::JSObject::TransitionElementsKind (Isolate * isolate, DirectHandle< JSObject > object, ElementsKind to_kind) [static]
Definition at line 5540 of file js-objects.cc.
                                                            {
  ElementsKind from_kind = object->GetElementsKind();
  if (IsHoleyElementsKind(from_kind)) {
    to_kind = GetHoleyElementsKind(to_kind);
  }
  if (from_kind == to_kind) return;
  // This method should never be called for any other case.
  DCHECK(IsFastElementsKind(from_kind) ||
         IsNonextensibleElementsKind(from_kind));
  DCHECK(IsFastElementsKind(to_kind) || IsNonextensibleElementsKind(to_kind));
  DCHECK_NE(TERMINAL_FAST_ELEMENTS_KIND, from_kind);
  UpdateAllocationSite(isolate, object, to_kind);
  if (object->elements() == ReadOnlyRoots(isolate).empty_fixed_array() ||
      IsDoubleElementsKind(from_kind) == IsDoubleElementsKind(to_kind)) {
    // No change is needed to the elements() buffer, the transition
    // only requires a map change.
    DirectHandle<Map> new_map =
        GetElementsTransitionMap(isolate, object, to_kind);
    JSObject::MigrateToMap(isolate, object, new_map);
    if (v8_flags.trace_elements_transitions) {
      DirectHandle<FixedArrayBase> elms(object->elements(), isolate);
      PrintElementsTransition(stdout, object, from_kind, elms, to_kind, elms);
    }
  } else {
    DCHECK((IsSmiElementsKind(from_kind) && IsDoubleElementsKind(to_kind)) ||
           (IsDoubleElementsKind(from_kind) && IsObjectElementsKind(to_kind)));
    uint32_t c = static_cast<uint32_t>(object->elements()->length());
    if (ElementsAccessor::ForKind(to_kind)
            ->GrowCapacityAndConvert(isolate, object, c)
            .IsNothing()) {
      // TODO(victorgomes): Temporarily forcing a fatal error here in case of
      // overflow, until all users of TransitionElementsKind can handle
      // exceptions.
      FATAL(
          "Fatal JavaScript invalid size error when transitioning elements "
          "kind");
      UNREACHABLE();
    }
  }
}
References v8::internal::DCHECK(), DCHECK_NE, FATAL, v8::internal::ElementsAccessor::ForKind(), GetElementsTransitionMap(), v8::internal::GetHoleyElementsKind(), v8::internal::ElementsAccessor::GrowCapacityAndConvert(), v8::internal::IsDoubleElementsKind(), v8::internal::IsFastElementsKind(), v8::internal::IsHoleyElementsKind(), v8::internal::IsNonextensibleElementsKind(), v8::internal::IsObjectElementsKind(), v8::internal::IsSmiElementsKind(), MigrateToMap(), PrintElementsTransition(), v8::internal::TERMINAL_FAST_ELEMENTS_KIND, v8::internal::UNREACHABLE(), UpdateAllocationSite(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::AddImpl(), AllocateStorageForMap(), v8::internal::ArrayConstructInitializeElements(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::DeleteImpl(), v8::internal::AllocationSite::DigestTransitionFeedback(), v8::internal::anonymous_namespace{builtins-array.cc}::MatchArrayElementsKindToArguments(), v8::internal::LookupIterator::PrepareForDataProperty(), PreventExtensionsWithTransition(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::SetLengthImpl(), and v8::internal::anonymous_namespace{builtins-array.cc}::TryFastArrayFill().
TryMigrateInstance()
bool v8::internal::JSObject::TryMigrateInstance (Isolate * isolate, DirectHandle< JSObject > instance) [static]
Definition at line 3582 of file js-objects.cc.
                                                                 {
  DisallowDeoptimization no_deoptimization(isolate);
  Handle<Map> original_map(object->map(), isolate);
  DirectHandle<Map> new_map;
  if (!Map::TryUpdate(isolate, original_map).ToHandle(&new_map)) {
    return false;
  }
  JSObject::MigrateToMap(isolate, object, new_map);
  if (v8_flags.trace_migration && *original_map != object->map()) {
    object->PrintInstanceMigration(stdout, *original_map, object->map());
  }
#if VERIFY_HEAP
  if (v8_flags.verify_heap) {
    object->JSObjectVerify(isolate);
  }
#endif
  return true;
}
References MigrateToMap(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::Map::TryUpdate(), and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION().
UnregisterPrototypeUser()
bool v8::internal::JSObject::UnregisterPrototypeUser (DirectHandle< Map > user, Isolate * isolate) [static]
Definition at line 5114 of file js-objects.cc.
                                                         {
  DCHECK(user->is_prototype_map());
  // If it doesn't have a PrototypeInfo, it was never registered.
  if (!user->has_prototype_info()) return false;
  DCHECK(IsPrototypeInfo(user->prototype_info()));
  // If it had no prototype before, see if it had users that might expect
  // registration.
  if (!IsJSObject(user->prototype())) {
    Tagged<Object> users =
        Cast<PrototypeInfo>(user->prototype_info())->prototype_users();
    return IsWeakArrayList(users);
  }
  DirectHandle<JSObject> prototype(Cast<JSObject>(user->prototype()), isolate);
  DirectHandle<PrototypeInfo> user_info =
      Map::GetOrCreatePrototypeInfo(user, isolate);
  int slot = user_info->registry_slot();
  if (slot == PrototypeInfo::UNREGISTERED) return false;
  DCHECK(prototype->map()->is_prototype_map());
  Tagged<Object> maybe_proto_info = prototype->map()->prototype_info();
  // User knows its registry slot, prototype info and user registry must exist.
  DCHECK(IsPrototypeInfo(maybe_proto_info));
  DirectHandle<PrototypeInfo> proto_info(Cast<PrototypeInfo>(maybe_proto_info),
                                         isolate);
  DirectHandle<WeakArrayList> prototype_users(
      Cast<WeakArrayList>(proto_info->prototype_users()), isolate);
  DCHECK_EQ(prototype_users->Get(slot), MakeWeak(*user));
  PrototypeUsers::MarkSlotEmpty(*prototype_users, slot);
  if (v8_flags.trace_prototype_users) {
    PrintF("Unregistering %p as a user of prototype %p.\n",
           reinterpret_cast<void*>(user->ptr()),
           reinterpret_cast<void*>(prototype->ptr()));
  }
  return true;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Map::GetOrCreatePrototypeInfo(), v8::internal::MakeWeak(), v8::internal::PrototypeUsers::MarkSlotEmpty(), v8::internal::PrintF(), v8::internal::prototype, v8::internal::PrototypeInfo::UNREGISTERED, and v8::internal::v8_flags.
Referenced by UpdatePrototypeUserRegistration().
UpdateAllocationSite()
template<AllocationSiteUpdateMode update_or_check>
bool v8::internal::JSObject::UpdateAllocationSite (Isolate * isolate, DirectHandle< JSObject > object, ElementsKind to_kind) [static]
Definition at line 5507 of file js-objects.cc.
                                                          {
  if (!IsJSArray(*object)) return false;
  if (!HeapLayout::InYoungGeneration(*object)) return false;
  if (Heap::IsLargeObject(*object)) return false;
  DirectHandle<AllocationSite> site;
  {
    DisallowGarbageCollection no_gc;
    Heap* heap = isolate->heap();
    Tagged<AllocationMemento> memento =
        PretenuringHandler::FindAllocationMemento<
            PretenuringHandler::kForRuntime>(heap, object->map(), *object);
    if (memento.is_null()) return false;
    // Walk through to the Allocation Site
    site = direct_handle(memento->GetAllocationSite(), heap->isolate());
  }
  return AllocationSite::DigestTransitionFeedback<update_or_check>(
      isolate, site, to_kind);
}
References v8::internal::direct_handle(), v8::internal::PretenuringHandler::FindAllocationMemento(), v8::internal::Isolate::heap(), heap(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::Heap::IsLargeObject(), v8::internal::PretenuringHandler::kForRuntime, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::BasicGrowCapacityAndConvertImpl(), TransitionElementsKind(), and v8::internal::anonymous_namespace{builtins-array.cc}::TryFastArrayFill().
UpdatePrototypeUserRegistration()
void v8::internal::JSObject::UpdatePrototypeUserRegistration (DirectHandle< Map > old_map, DirectHandle< Map > new_map, Isolate * isolate) [static]
Definition at line 3061 of file js-objects.cc.
                                                                 {
  DCHECK(old_map->is_prototype_map());
  DCHECK(new_map->is_prototype_map());
  bool was_registered = JSObject::UnregisterPrototypeUser(old_map, isolate);
  new_map->set_prototype_info(old_map->prototype_info(), kReleaseStore);
  old_map->set_prototype_info(Smi::zero(), kReleaseStore);
  if (v8_flags.trace_prototype_users) {
    PrintF("Moving prototype_info %p from map %p to map %p.\n",
           reinterpret_cast<void*>(new_map->prototype_info().ptr()),
           reinterpret_cast<void*>(old_map->ptr()),
           reinterpret_cast<void*>(new_map->ptr()));
  }
  if (was_registered) {
    if (new_map->has_prototype_info()) {
      // The new map isn't registered with its prototype yet; reflect this fact
      // in the PrototypeInfo it just inherited from the old map.
      Cast<PrototypeInfo>(new_map->prototype_info())
          ->set_registry_slot(PrototypeInfo::UNREGISTERED);
    }
    JSObject::LazyRegisterPrototypeUser(new_map, isolate);
  }
}
References v8::internal::DCHECK(), v8::kReleaseStore, LazyRegisterPrototypeUser(), v8::internal::PrintF(), v8::internal::PrototypeInfo::UNREGISTERED, UnregisterPrototypeUser(), v8::internal::v8_flags, and v8::internal::Smi::zero().
Referenced by NotifyMapChange().
ValidateElements()
void v8::internal::JSObject::ValidateElements (Isolate * isolate, Tagged< JSObject > object) [static]
Definition at line 5378 of file js-objects.cc.
                                                                         {
#ifdef ENABLE_SLOW_DCHECKS
  if (v8_flags.enable_slow_asserts) {
    object->GetElementsAccessor()->Validate(isolate, object);
  }
#endif
}
References v8::internal::v8_flags.
Referenced by v8::internal::Object::AddDataProperty(), v8::internal::anonymous_namespace{js-number-format.cc}::ConstructParts(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FieldPositionIteratorToArray(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormattedDateIntervalToJSArray(), v8::internal::anonymous_namespace{js-list-format.cc}::FormattedListToJSArray(), v8::internal::FormattedListToJSArray(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::FormatToJSArray(), v8::internal::wasm::GetCustomSections(), v8::internal::wasm::GetExports(), v8::internal::wasm::GetImports(), v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::GrowCapacityAndConvertImpl(), v8::internal::Factory::NewJSArrayWithElements(), and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::SetLengthImpl().
WouldConvertToSlowElements()
bool v8::internal::JSObject::WouldConvertToSlowElements (uint32_t index)
Definition at line 5386 of file js-objects.cc.
                                                        {
  if (!HasFastElements()) return false;
  uint32_t capacity = static_cast<uint32_t>(elements()->length());
  uint32_t new_capacity;
  return ShouldConvertToSlowElements(*this, capacity, index, &new_capacity);
}
References elements(), v8::internal::index, and v8::internal::ShouldConvertToSlowElements().
WriteToField()
void v8::internal::JSObject::WriteToField (InternalIndex descriptor, PropertyDetails details, Tagged< Object > value) [inline]
Definition at line 498 of file js-objects-inl.h.
                                                  {
  DCHECK_EQ(PropertyLocation::kField, details.location());
  DCHECK_EQ(PropertyKind::kData, details.kind());
  DisallowGarbageCollection no_gc;
  FieldIndex index = FieldIndex::ForDetails(map(), details);
  if (details.representation().IsDouble()) {
    // Manipulating the signaling NaN used for the hole and uninitialized
    // double field sentinel in C++, e.g. with base::bit_cast or
    // value()/set_value(), will change its value on ia32 (the x87 stack is used
    // to return values and stores to the stack silently clear the signalling
    // bit).
    uint64_t bits;
    if (IsSmi(value)) {
      bits = base::bit_cast<uint64_t>(static_cast<double>(Smi::ToInt(value)));
    } else if (IsUninitialized(value)) {
      bits = kHoleNanInt64;
    } else {
      DCHECK(IsHeapNumber(value));
      bits = Cast<HeapNumber>(value)->value_as_bits();
    }
    auto box = Cast<HeapNumber>(RawFastPropertyAt(index));
    box->set_value_as_bits(bits);
  } else {
    FastPropertyAtPut(index, value);
  }
}
References DCHECK, DCHECK_EQ, v8::internal::index, v8::internal::Representation::IsDouble(), v8::internal::IsSmi(), v8::internal::torque::ls::kField, v8::internal::kHoleNanInt64, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PropertyDetails::representation(), v8::internal::anonymous_namespace{temporal-parser.cc}::ToInt(), and v8::internal::value.
Friends And Related Function Documentation
JSReceiver
friend class JSReceiver [friend]
Definition at line 1000 of file js-objects.h.
Object
friend class Object [friend]
Definition at line 1001 of file js-objects.h.
Member Data Documentation
kFieldsAdded
const int v8::internal::JSObject::kFieldsAdded = 3 [static]
Definition at line 962 of file js-objects.h.
Referenced by v8::internal::Map::AccountAddedOutOfObjectPropertyField(), v8::internal::Map::AccountAddedPropertyField(), v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), v8::internal::AccessorAssembler::ExtendPropertiesBackingStore(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::ExtendPropertiesBackingStore(), v8::internal::Map::HasOutOfObjectProperties(), v8::internal::CodeStubAssembler::MapUsedInstanceSizeInWords(), v8::internal::Map::SetInObjectUnusedPropertyFields(), v8::internal::Map::SetOutOfObjectUnusedPropertyFields(), v8::internal::Map::UnusedInObjectProperties(), v8::internal::Map::UnusedPropertyFields(), and v8::internal::Map::UsedInstanceSize().
kInitialGlobalObjectUnusedPropertiesCount
const int v8::internal::JSObject::kInitialGlobalObjectUnusedPropertiesCount = 4 [static]
Definition at line 951 of file js-objects.h.
Referenced by v8::internal::Genesis::CreateObjectFunction().
kMapCacheSize
const int v8::internal::JSObject::kMapCacheSize = 128 [static]
Definition at line 957 of file js-objects.h.
Referenced by v8::internal::AccessorAssembler::GenerateCloneObjectIC_Slow(), v8::internal::Genesis::InitializeMapCaches(), v8::internal::CodeStubAssembler::LoadCachedMap(), and v8::internal::Factory::ObjectLiteralMapFromCache().
kMaxElementCount
constexpr uint32_t v8::internal::JSObject::kMaxElementCount = kMaxUInt32 [static], [constexpr]
Definition at line 931 of file js-objects.h.
Referenced by v8::internal::RUNTIME_FUNCTION().
kMaxElementIndex
constexpr uint32_t v8::internal::JSObject::kMaxElementIndex = kMaxElementCount - 1 [static], [constexpr]
Definition at line 932 of file js-objects.h.
Referenced by v8::internal::anonymous_namespace{builtins-struct.cc}::CollectFieldsAndElements(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPush(), v8::internal::AccessorAssembler::GenericElementLoad(), v8::internal::LookupIterator::GetInterceptor(), v8::internal::compiler::JSObjectRef::GetOwnConstantElementFromHeap(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::anonymous_namespace{lookup.cc}::HasInterceptor(), v8::internal::anonymous_namespace{ic.cc}::IntPtrKeyToSize(), v8::internal::LookupIterator::IsElement(), v8::internal::LookupIterator::LookupIterator(), v8::internal::PropertyKey::PropertyKey(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeCharAt(), v8::internal::requires(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::ConcurrentLookupIterator::TryGetOwnConstantElement().
kMaxEmbedderFields
const int v8::internal::JSObject::kMaxEmbedderFields [static]
Initial value:
=
      (kMaxFirstInobjectPropertyOffset - kHeaderSize) / kEmbedderDataSlotSize
Definition at line 973 of file js-objects.h.
Referenced by v8::internal::JSFunction::CalculateInstanceSizeHelper().
kMaxFirstInobjectPropertyOffset
const int v8::internal::JSObject::kMaxFirstInobjectPropertyOffset [static]
Initial value:
=
      (1 << kFirstInobjectPropertyOffsetBitCount) - 1
Definition at line 971 of file js-objects.h.
kMaxGap
const uint32_t v8::internal::JSObject::kMaxGap = 1024 [static]
Definition at line 939 of file js-objects.h.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementStoreOnJSArrayOrJSObject(), and v8::internal::CodeStubAssembler::TryGrowElementsCapacity().
kMaxInObjectProperties
const int v8::internal::JSObject::kMaxInObjectProperties [static]
Initial value:
=
      (kMaxInstanceSize - kHeaderSize) >> kTaggedSizeLog2
Definition at line 967 of file js-objects.h.
Referenced by v8::internal::JSFunction::CalculateExpectedNofProperties(), v8::internal::JSFunction::CalculateInstanceSizeHelper(), v8::internal::Map::Create(), v8::internal::DictionaryTemplateInfo::NewInstance(), v8::internal::SharedFunctionInfo::UpdateAndFinalizeExpectedNofPropertiesFromEstimate(), and v8::internal::SharedFunctionInfo::UpdateExpectedNofPropertiesFromEstimate().
kMaxInstanceSize
const int v8::internal::JSObject::kMaxInstanceSize = 255 * kTaggedSize [static]
Definition at line 953 of file js-objects.h.
Referenced by v8::internal::JSFunction::CalculateInstanceSizeHelper(), and v8::internal::ConstructorBuiltinsAssembler::CreateShallowObjectLiteral().
kMaxJSApiObjectEmbedderFields
constexpr int v8::internal::JSObject::kMaxJSApiObjectEmbedderFields [static], [constexpr]
Initial value:
=
      (kMaxFirstInobjectPropertyOffset - kHeaderSize -
       kCppHeapPointerSlotSize) /
      kEmbedderDataSlotSize
Definition at line 982 of file js-objects.h.
kMaxJSApiObjectInObjectProperties
constexpr int v8::internal::JSObject::kMaxJSApiObjectInObjectProperties [static], [constexpr]
Initial value:
=
      (kMaxInstanceSize - kHeaderSize - kCppHeapPointerSlotSize) >>
      kTaggedSizeLog2
Definition at line 979 of file js-objects.h.
kMaxUncheckedFastElementsLength
const int v8::internal::JSObject::kMaxUncheckedFastElementsLength = 5000 [static]
Definition at line 943 of file js-objects.h.
kMaxUncheckedOldFastElementsLength
const int v8::internal::JSObject::kMaxUncheckedOldFastElementsLength = 500 [static]
Definition at line 947 of file js-objects.h.
kMinAddedElementsCapacity
const uint32_t v8::internal::JSObject::kMinAddedElementsCapacity = 16 [static]
Definition at line 656 of file js-objects.h.
Referenced by v8::internal::CodeStubAssembler::CalculateNewElementsCapacity(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::DecreaseLength(), NewElementsCapacity(), and v8::internal::TF_BUILTIN().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-objects.h
/mnt/V8SourceCode/src/objects/js-objects-inl.h
/mnt/V8SourceCode/src/objects/js-objects.cc