v8::internal::DebugInfoCollection Class Reference
#include <debug.h>
Classes
class Iterator
Public Member Functions
DebugInfoCollection (Isolate *isolate)
void Insert (Tagged< SharedFunctionInfo > sfi, Tagged< DebugInfo > debug_info)
bool Contains (Tagged< SharedFunctionInfo > sfi) const
std::optional< Tagged< DebugInfo > > Find (Tagged< SharedFunctionInfo > sfi) const
void DeleteSlow (Tagged< SharedFunctionInfo > sfi)
size_t Size () const
Private Types
using HandleLocation = Address *
using SFIUniqueId = uint32_t
Private Member Functions
V8_EXPORT_PRIVATE Tagged< DebugInfo > EntryAsDebugInfo (size_t index) const
void DeleteIndex (size_t index)
Private Attributes
Isolate *const isolate_
std::vector< HandleLocation > list_
std::unordered_map< SFIUniqueId, HandleLocation > map_
Detailed Description
Definition at line 184 of file debug.h.
Member Typedef Documentation
HandleLocation
using v8::internal::DebugInfoCollection::HandleLocation = Address* [private]
Definition at line 185 of file debug.h.
SFIUniqueId
using v8::internal::DebugInfoCollection::SFIUniqueId = uint32_t [private]
Definition at line 186 of file debug.h.
Constructor & Destructor Documentation
DebugInfoCollection()
v8::internal::DebugInfoCollection::DebugInfoCollection (Isolate * isolate) [inline], [explicit]
Definition at line 189 of file debug.h.
: isolate_(isolate) {}
Member Function Documentation
Contains()
bool v8::internal::DebugInfoCollection::Contains (Tagged< SharedFunctionInfo > sfi) const
Definition at line 563 of file debug.cc.
                                                                       {
  auto it = map_.find(sfi->unique_id());
  if (it == map_.end()) return false;
  DCHECK_EQ(Cast<DebugInfo>(Tagged<Object>(*it->second))->shared(), sfi);
  return true;
}
References DCHECK_EQ, and map_.
Referenced by DeleteIndex(), and Insert().
DeleteIndex()
void v8::internal::DebugInfoCollection::DeleteIndex (size_t index) [private]
Definition at line 595 of file debug.cc.
                                                  {
  base::MutexGuard mutex_guard(isolate_->shared_function_info_access());
  Tagged<DebugInfo> debug_info = EntryAsDebugInfo(index);
  Tagged<SharedFunctionInfo> sfi = debug_info->shared();
  DCHECK(Contains(sfi));
  auto it = map_.find(sfi->unique_id());
  HandleLocation location = it->second;
  DCHECK_EQ(location, list_[index]);
  map_.erase(it);
  list_[index] = list_.back();
  list_.pop_back();
  GlobalHandles::Destroy(location);
  DCHECK(!Contains(sfi));
  DCHECK_EQ(list_.size(), map_.size());
}
References Contains(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::GlobalHandles::Destroy(), EntryAsDebugInfo(), v8::internal::index, isolate_, list_, map_, and v8::internal::Isolate::shared_function_info_access().
Referenced by v8::internal::DebugInfoCollection::Iterator::DeleteNext().
DeleteSlow()
void v8::internal::DebugInfoCollection::DeleteSlow (Tagged< SharedFunctionInfo > sfi)
Definition at line 579 of file debug.cc.
                                                                   {
  DebugInfoCollection::Iterator it(this);
  for (; it.HasNext(); it.Advance()) {
    Tagged<DebugInfo> debug_info = it.Next();
    if (debug_info->shared() != sfi) continue;
    it.DeleteNext();
    return;
  }
  UNREACHABLE();
}
References v8::internal::DebugInfoCollection::Iterator::Advance(), v8::internal::DebugInfoCollection::Iterator::DeleteNext(), v8::internal::DebugInfoCollection::Iterator::HasNext(), v8::internal::DebugInfoCollection::Iterator::Next(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::Debug::RemoveBreakInfoAndMaybeFree().
EntryAsDebugInfo()
Tagged< DebugInfo > v8::internal::DebugInfoCollection::EntryAsDebugInfo (size_t index) const [private]
Definition at line 590 of file debug.cc.
                                                                          {
  DCHECK_LT(index, list_.size());
  return Cast<DebugInfo>(Tagged<Object>(*list_[index]));
}
References DCHECK_LT, v8::internal::index, and list_.
Referenced by DeleteIndex(), and v8::internal::DebugInfoCollection::Iterator::Next().
Find()
std::optional< Tagged< DebugInfo > > v8::internal::DebugInfoCollection::Find (Tagged< SharedFunctionInfo > sfi) const
Definition at line 570 of file debug.cc.
                                          {
  auto it = map_.find(sfi->unique_id());
  if (it == map_.end()) return {};
  Tagged<DebugInfo> di = Cast<DebugInfo>(Tagged<Object>(*it->second));
  DCHECK_EQ(di->shared(), sfi);
  return di;
}
References DCHECK_EQ, and map_.
Referenced by v8::internal::Debug::GetOrCreateDebugInfo(), and v8::internal::Debug::TryGetDebugInfo().
Insert()
void v8::internal::DebugInfoCollection::Insert (Tagged< SharedFunctionInfo > sfi, Tagged< DebugInfo > debug_info)
Definition at line 548 of file debug.cc.
                                                               {
  DisallowGarbageCollection no_gc;
  base::MutexGuard mutex_guard(isolate_->shared_function_info_access());
  DCHECK_EQ(sfi, debug_info->shared());
  DCHECK(!Contains(sfi));
  HandleLocation location =
      isolate_->global_handles()->Create(debug_info).location();
  list_.push_back(location);
  map_.emplace(sfi->unique_id(), location);
  DCHECK(Contains(sfi));
  DCHECK_EQ(list_.size(), map_.size());
}
References Contains(), v8::internal::GlobalHandles::Create(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::global_handles(), isolate_, list_, map_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Isolate::shared_function_info_access().
Referenced by v8::internal::Debug::GetOrCreateDebugInfo().
Size()
size_t v8::internal::DebugInfoCollection::Size () const [inline]
Definition at line 198 of file debug.h.
{ return list_.size(); }
References list_.
Member Data Documentation
isolate_
Isolate* const v8::internal::DebugInfoCollection::isolate_ [private]
Definition at line 237 of file debug.h.
Referenced by DeleteIndex(), and Insert().
list_
std::vector<HandleLocation> v8::internal::DebugInfoCollection::list_ [private]
Definition at line 238 of file debug.h.
Referenced by DeleteIndex(), EntryAsDebugInfo(), v8::internal::DebugInfoCollection::Iterator::HasNext(), Insert(), and Size().
map_
std::unordered_map<SFIUniqueId, HandleLocation> v8::internal::DebugInfoCollection::map_ [private]
Definition at line 239 of file debug.h.
Referenced by Contains(), DeleteIndex(), Find(), and Insert().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug.h
/mnt/V8SourceCode/src/debug/debug.cc