v8::internal::anonymous_namespace{perfetto-logger.cc}::IsolateRegistry Class Reference
Public Member Functions
void Register (Isolate *isolate)
void Unregister (Isolate *isolate)
void OnCodeDataSourceStart ()
void OnCodeDataSourceStop ()
Static Public Member Functions
static IsolateRegistry & GetInstance ()
Private Member Functions
void StartLogging (const base::MutexGuard &)
void StopLogging (const base::MutexGuard &)
void LogExistingCodeForAllIsolates (const base::MutexGuard &)
Private Attributes
base::Mutex mutex_
int num_active_data_sources_ = 0
absl::flat_hash_map< Isolate *, std::unique_ptr< PerfettoLogger > > isolates_
Detailed Description
Definition at line 76 of file perfetto-logger.cc.
Member Function Documentation
GetInstance()
static IsolateRegistry& v8::internal::anonymous_namespace{perfetto-logger.cc}::IsolateRegistry::GetInstance () [inline], [static]
Definition at line 78 of file perfetto-logger.cc.
                                        {
    static IsolateRegistry* g_instance = new IsolateRegistry();
    return *g_instance;
  }
LogExistingCodeForAllIsolates()
void v8::internal::anonymous_namespace{perfetto-logger.cc}::IsolateRegistry::LogExistingCodeForAllIsolates (const base::MutexGuard &) [inline], [private]
Definition at line 133 of file perfetto-logger.cc.
                                                            {
    for (const auto& [isolate, listener] : isolates_) {
      isolate->RequestInterrupt(
          [](v8::Isolate*, void* data) {
            PerfettoLogger* logger = reinterpret_cast<PerfettoLogger*>(data);
            logger->LogExistingCode();
          },
          listener.get());
    }
  }
References v8::internal::PerfettoLogger::LogExistingCode().
OnCodeDataSourceStart()
void v8::internal::anonymous_namespace{perfetto-logger.cc}::IsolateRegistry::OnCodeDataSourceStart () [inline]
Definition at line 102 of file perfetto-logger.cc.
                               {
    base::MutexGuard lock(&mutex_);
    ++num_active_data_sources_;
    if (num_active_data_sources_ == 1) {
      StartLogging(lock);
    }
    LogExistingCodeForAllIsolates(lock);
  }
OnCodeDataSourceStop()
void v8::internal::anonymous_namespace{perfetto-logger.cc}::IsolateRegistry::OnCodeDataSourceStop () [inline]
Definition at line 111 of file perfetto-logger.cc.
                              {
    base::MutexGuard lock(&mutex_);
    DCHECK_LT(0, num_active_data_sources_);
    --num_active_data_sources_;
    if (num_active_data_sources_ == 0) {
      StopLogging(lock);
    }
  }
References DCHECK_LT.
Register()
void v8::internal::anonymous_namespace{perfetto-logger.cc}::IsolateRegistry::Register (Isolate * isolate) [inline]
Definition at line 83 of file perfetto-logger.cc.
                                  {
    auto logger = std::make_unique<PerfettoLogger>(isolate);
    base::MutexGuard lock(&mutex_);
    if (num_active_data_sources_ != 0) {
      isolate->logger()->AddListener(logger.get());
    }
    CHECK(isolates_.emplace(isolate, std::move(logger)).second);
  }
References v8::internal::Logger::AddListener(), CHECK, and v8::internal::Isolate::logger().
StartLogging()
void v8::internal::anonymous_namespace{perfetto-logger.cc}::IsolateRegistry::StartLogging (const base::MutexGuard &) [inline], [private]
Definition at line 121 of file perfetto-logger.cc.
                                           {
    for (const auto& [isolate, logger] : isolates_) {
      isolate->logger()->AddListener(logger.get());
    }
  }
StopLogging()
void v8::internal::anonymous_namespace{perfetto-logger.cc}::IsolateRegistry::StopLogging (const base::MutexGuard &) [inline], [private]
Definition at line 127 of file perfetto-logger.cc.
                                          {
    for (const auto& [isolate, logger] : isolates_) {
      isolate->logger()->RemoveListener(logger.get());
    }
  }
Unregister()
void v8::internal::anonymous_namespace{perfetto-logger.cc}::IsolateRegistry::Unregister (Isolate * isolate) [inline]
Definition at line 92 of file perfetto-logger.cc.
                                    {
    base::MutexGuard lock(&mutex_);
    auto it = isolates_.find(isolate);
    CHECK(it != isolates_.end());
    if (num_active_data_sources_ != 0) {
      isolate->logger()->RemoveListener(it->second.get());
    }
    isolates_.erase(it);
  }
References CHECK, v8::internal::Isolate::logger(), and v8::internal::Logger::RemoveListener().
Member Data Documentation
isolates_
absl::flat_hash_map<Isolate*, std::unique_ptr<PerfettoLogger> > v8::internal::anonymous_namespace{perfetto-logger.cc}::IsolateRegistry::isolates_ [private]
Definition at line 146 of file perfetto-logger.cc.
mutex_
base::Mutex v8::internal::anonymous_namespace{perfetto-logger.cc}::IsolateRegistry::mutex_ [private]
Definition at line 144 of file perfetto-logger.cc.
num_active_data_sources_
int v8::internal::anonymous_namespace{perfetto-logger.cc}::IsolateRegistry::num_active_data_sources_ = 0 [private]
Definition at line 145 of file perfetto-logger.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/tracing/perfetto-logger.cc