v8::internal::compiler::JSInliner Class Reference
#include <js-inlining.h>
Public Member Functions
JSInliner (Editor *editor, Zone *local_zone, OptimizedCompilationInfo *info, JSGraph *jsgraph, JSHeapBroker *broker, SourcePositionTable *source_positions, NodeOriginTable *node_origins, const wasm::WasmModule *wasm_module, JsWasmCallsSidetable *js_wasm_calls_sidetable, bool inline_wasm_fct_if_supported)
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Reduction ReduceJSCall (Node *node)
Private Member Functions
Zone * zone () const
CommonOperatorBuilder * common () const
JSOperatorBuilder * javascript () const
SimplifiedOperatorBuilder * simplified () const
TFGraph * graph () const
JSGraph * jsgraph () const
JSHeapBroker * broker () const
Isolate * isolate () const
OptionalSharedFunctionInfoRef DetermineCallTarget (Node *node)
FeedbackCellRef DetermineCallContext (Node *node, Node **context_out)
FrameState CreateArtificialFrameState (Node *node, FrameState outer_frame_state, int parameter_count, FrameStateType frame_state_type, SharedFunctionInfoRef shared, OptionalBytecodeArrayRef maybe_bytecode_array, Node *context=nullptr, Node *callee=nullptr)
Reduction InlineCall (Node *call, Node *new_target, Node *context, Node *frame_state, StartNode start, Node *end, Node *exception_target, const NodeVector &uncaught_subcalls, int argument_count)
Private Attributes
Zone *const local_zone_
OptimizedCompilationInfo * info_
JSGraph *const jsgraph_
JSHeapBroker *const broker_
SourcePositionTable *const source_positions_
NodeOriginTable *const node_origins_
const wasm::WasmModule * wasm_module_
JsWasmCallsSidetable * js_wasm_calls_sidetable_
bool inline_wasm_fct_if_supported_
Additional Inherited Members
Detailed Description
Definition at line 33 of file js-inlining.h.
Constructor & Destructor Documentation
JSInliner()
v8::internal::compiler::JSInliner::JSInliner (Editor * editor, Zone * local_zone, OptimizedCompilationInfo * info, JSGraph * jsgraph, JSHeapBroker * broker, SourcePositionTable * source_positions, NodeOriginTable * node_origins, const wasm::WasmModule * wasm_module, JsWasmCallsSidetable * js_wasm_calls_sidetable, bool inline_wasm_fct_if_supported) [inline]
Definition at line 35 of file js-inlining.h.
      : AdvancedReducer(editor),
        local_zone_(local_zone),
        info_(info),
        jsgraph_(jsgraph),
        broker_(broker),
        source_positions_(source_positions),
        node_origins_(node_origins),
        wasm_module_(wasm_module),
        js_wasm_calls_sidetable_(js_wasm_calls_sidetable),
        inline_wasm_fct_if_supported_(inline_wasm_fct_if_supported) {
    // In case WebAssembly is disabled.
    USE(wasm_module_);
    USE(inline_wasm_fct_if_supported_);
    USE(js_wasm_calls_sidetable_);
    DCHECK_IMPLIES(inline_wasm_fct_if_supported_, wasm_module_ != nullptr);
  }
References DCHECK_IMPLIES, inline_wasm_fct_if_supported_, js_wasm_calls_sidetable_, USE, and wasm_module_.
Member Function Documentation
broker()
JSHeapBroker* v8::internal::compiler::JSInliner::broker () const [inline], [private]
Definition at line 89 of file js-inlining.h.
{ return broker_; }
References broker_.
Referenced by DetermineCallContext(), DetermineCallTarget(), and ReduceJSCall().
common()
CommonOperatorBuilder * v8::internal::compiler::JSInliner::common () const [private]
Definition at line 974 of file js-inlining.cc.
{ return jsgraph()->common(); }
References v8::internal::compiler::MachineGraph::common(), and jsgraph().
Referenced by CreateArtificialFrameState(), InlineCall(), and ReduceJSCall().
CreateArtificialFrameState()
FrameState v8::internal::compiler::JSInliner::CreateArtificialFrameState (Node * node, FrameState outer_frame_state, int parameter_count, FrameStateType frame_state_type, SharedFunctionInfoRef shared, OptionalBytecodeArrayRef maybe_bytecode_array, Node * context = nullptr, Node * callee = nullptr) [private]
Definition at line 251 of file js-inlining.cc.
                  {
  const int argument_count_with_receiver =
      argument_count + JSCallOrConstructNode::kReceiverOrNewTargetInputCount;
  CHECK_LE(argument_count_with_receiver, kMaxUInt16);
  IndirectHandle<BytecodeArray> bytecode_array_handle = {};
  if (maybe_bytecode_array.has_value()) {
    bytecode_array_handle = maybe_bytecode_array->object();
  }
  const FrameStateFunctionInfo* state_info =
      common()->CreateFrameStateFunctionInfo(
          frame_state_type, argument_count_with_receiver, 0, 0, shared.object(),
          bytecode_array_handle);
  const Operator* op = common()->FrameState(
      BytecodeOffset::None(), OutputFrameStateCombine::Ignore(), state_info);
  const Operator* op0 = common()->StateValues(0, SparseInputMask::Dense());
  Node* node0 = graph()->NewNode(op0);
  Node* params_node = nullptr;
#if V8_ENABLE_WEBASSEMBLY
  const bool skip_params =
      frame_state_type == FrameStateType::kWasmInlinedIntoJS;
#else
  const bool skip_params = false;
#endif
  if (skip_params) {
    // For wasm inlined into JS the frame state doesn't need to be used for
    // deopts. Also, due to different calling conventions, there isn't a
    // receiver at input 1. We still need to store an undefined node here as the
    // code requires this state values to have at least 1 entry.
    // TODO(mliedtke): Can we clean up the FrameState handling, so that wasm
    // inline FrameStates are closer to JS FrameStates without affecting
    // performance?
    const Operator* op_param =
        common()->StateValues(1, SparseInputMask::Dense());
    params_node = graph()->NewNode(op_param, jsgraph()->UndefinedConstant());
  } else {
    NodeVector params(local_zone_);
    params.push_back(
        node->InputAt(JSCallOrConstructNode::ReceiverOrNewTargetIndex()));
    for (int i = 0; i < argument_count; i++) {
      params.push_back(node->InputAt(JSCallOrConstructNode::ArgumentIndex(i)));
    }
    const Operator* op_param = common()->StateValues(
        static_cast<int>(params.size()), SparseInputMask::Dense());
    params_node = graph()->NewNode(op_param, static_cast<int>(params.size()),
                                   &params.front());
  }
  if (context == nullptr) context = jsgraph()->UndefinedConstant();
  if (callee == nullptr) {
    callee = node->InputAt(JSCallOrConstructNode::TargetIndex());
  }
  return FrameState{graph()->NewNode(op, params_node, node0, node0, context,
                                     callee, outer_frame_state)};
}
References v8::internal::compiler::JSCallOrConstructNode::ArgumentIndex(), CHECK_LE, common(), v8::internal::compiler::CommonOperatorBuilder::CreateFrameStateFunctionInfo(), v8::internal::compiler::SparseInputMask::Dense(), v8::internal::compiler::CommonOperatorBuilder::FrameState(), v8::internal::ZoneVector< T >::front(), graph(), v8::internal::compiler::OutputFrameStateCombine::Ignore(), v8::internal::compiler::Node::InputAt(), jsgraph(), v8::internal::kMaxUInt16, v8::internal::compiler::JSCallOrConstructNode::kReceiverOrNewTargetInputCount, local_zone_, v8::internal::compiler::TFGraph::NewNode(), v8::internal::BytecodeOffset::None(), v8::internal::compiler::SharedFunctionInfoRef::object(), v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::CommonOperatorBuilder::StateValues(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by ReduceJSCall().
DetermineCallContext()
FeedbackCellRef v8::internal::compiler::JSInliner::DetermineCallContext (Node * node, Node ** context_out) [private]
Definition at line 379 of file js-inlining.cc.
                                                                    {
  DCHECK(IrOpcode::IsInlineeOpcode(node->opcode()));
  Node* target = node->InputAt(JSCallOrConstructNode::TargetIndex());
  HeapObjectMatcher match(target);
  if (match.HasResolvedValue() && match.Ref(broker()).IsJSFunction()) {
    JSFunctionRef function = match.Ref(broker()).AsJSFunction();
    // This was already ensured by DetermineCallTarget
    CHECK(function.feedback_vector(broker()).has_value());
    // The inlinee specializes to the context from the JSFunction object.
    *context_out =
        jsgraph()->ConstantNoHole(function.context(broker()), broker());
    return function.raw_feedback_cell(broker());
  }
  if (match.IsJSCreateClosure()) {
    // Load the feedback vector of the target by looking up its vector cell at
    // the instantiation site (we only decide to inline if it's populated).
    JSCreateClosureNode n(target);
    FeedbackCellRef cell = n.GetFeedbackCellRefChecked(broker());
    // The inlinee uses the locally provided context at instantiation.
    *context_out = NodeProperties::GetContextInput(match.node());
    return cell;
  } else if (match.IsCheckClosure()) {
    FeedbackCellRef cell = MakeRef(broker(), FeedbackCellOf(match.op()));
    Node* effect = NodeProperties::GetEffectInput(node);
    Node* control = NodeProperties::GetControlInput(node);
    *context_out = effect = graph()->NewNode(
        simplified()->LoadField(AccessBuilder::ForJSFunctionContext()),
        match.node(), effect, control);
    NodeProperties::ReplaceEffectInput(node, effect);
    return cell;
  }
  // Must succeed.
  UNREACHABLE();
}
References broker(), CHECK, v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::DCHECK(), v8::internal::compiler::FeedbackCellOf(), v8::internal::compiler::AccessBuilder::ForJSFunctionContext(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::JSCreateClosureNode::GetFeedbackCellRefChecked(), graph(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::IrOpcode::IsInlineeOpcode(), jsgraph(), v8::internal::compiler::MakeRef(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::NodeMatcher::node(), v8::internal::compiler::NodeMatcher::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), simplified(), and v8::internal::UNREACHABLE().
Referenced by ReduceJSCall().
DetermineCallTarget()
OptionalSharedFunctionInfoRef v8::internal::compiler::JSInliner::DetermineCallTarget (Node * node) [private]
Definition at line 324 of file js-inlining.cc.
                                                                       {
  DCHECK(IrOpcode::IsInlineeOpcode(node->opcode()));
  Node* target = node->InputAt(JSCallOrConstructNode::TargetIndex());
  HeapObjectMatcher match(target);
  // This reducer can handle both normal function calls as well a constructor
  // calls whenever the target is a constant function object, as follows:
  // - JSCall(target:constant, receiver, args..., vector)
  // - JSConstruct(target:constant, new.target, args..., vector)
  if (match.HasResolvedValue() && match.Ref(broker()).IsJSFunction()) {
    JSFunctionRef function = match.Ref(broker()).AsJSFunction();
    // The function might have not been called yet.
    if (!function.feedback_vector(broker()).has_value()) {
      return std::nullopt;
    }
    // Disallow cross native-context inlining for now. This means that all parts
    // of the resulting code will operate on the same global object. This also
    // prevents cross context leaks, where we could inline functions from a
    // different context and hold on to that context (and closure) from the code
    // object.
    // TODO(turbofan): We might want to revisit this restriction later when we
    // have a need for this, and we know how to model different native contexts
    // in the same graph in a compositional way.
    if (!function.native_context(broker()).equals(
            broker()->target_native_context())) {
      return std::nullopt;
    }
    return function.shared(broker());
  }
  // This reducer can also handle calls where the target is statically known to
  // be the result of a closure instantiation operation, as follows:
  // - JSCall(JSCreateClosure[shared](context), receiver, args..., vector)
  // - JSConstruct(JSCreateClosure[shared](context),
  // new.target, args..., vector)
  if (match.IsJSCreateClosure()) {
    JSCreateClosureNode n(target);
    FeedbackCellRef cell = n.GetFeedbackCellRefChecked(broker());
    return cell.shared_function_info(broker());
  } else if (match.IsCheckClosure()) {
    FeedbackCellRef cell = MakeRef(broker(), FeedbackCellOf(match.op()));
    return cell.shared_function_info(broker());
  }
  return std::nullopt;
}
References broker(), v8::internal::DCHECK(), v8::internal::compiler::FeedbackCellOf(), v8::internal::compiler::JSCreateClosureNode::GetFeedbackCellRefChecked(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::IrOpcode::IsInlineeOpcode(), v8::internal::compiler::MakeRef(), v8::internal::native_context, v8::internal::compiler::NodeMatcher::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), and v8::internal::compiler::FeedbackCellRef::shared_function_info().
Referenced by ReduceJSCall().
graph()
TFGraph * v8::internal::compiler::JSInliner::graph () const [private]
Definition at line 968 of file js-inlining.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
Referenced by CreateArtificialFrameState(), DetermineCallContext(), InlineCall(), and ReduceJSCall().
InlineCall()
Reduction v8::internal::compiler::JSInliner::InlineCall (Node * call, Node * new_target, Node * context, Node * frame_state, StartNode start, Node * end, Node * exception_target, const NodeVector & uncaught_subcalls, int argument_count) [private]
Definition at line 99 of file js-inlining.cc.
                                                    {
  DCHECK_IMPLIES(IrOpcode::IsInlineeOpcode(call->opcode()),
                 argument_count == JSCallAccessor(call).argument_count());
  // The scheduler is smart enough to place our code; we just ensure {control}
  // becomes the control input of the start of the inlinee, and {effect} becomes
  // the effect input of the start of the inlinee.
  Node* control = NodeProperties::GetControlInput(call);
  Node* effect = NodeProperties::GetEffectInput(call);
  int const inlinee_new_target_index = start.NewTargetOutputIndex();
  int const inlinee_arity_index = start.ArgCountOutputIndex();
  int const inlinee_context_index = start.ContextOutputIndex();
  // {inliner_inputs} counts the target, receiver/new_target, and arguments; but
  // not feedback vector, context, effect or control.
  const int inliner_inputs = argument_count +
                             JSCallOrConstructNode::kExtraInputCount -
                             JSCallOrConstructNode::kFeedbackVectorInputCount;
  // Iterate over all uses of the start node.
  for (Edge edge : start->use_edges()) {
    Node* use = edge.from();
    switch (use->opcode()) {
      case IrOpcode::kParameter: {
        int index = 1 + ParameterIndexOf(use->op());
        DCHECK_LE(index, inlinee_context_index);
        if (index < inliner_inputs && index < inlinee_new_target_index) {
          // There is an input from the call, and the index is a value
          // projection but not the context, so rewire the input.
          Replace(use, call->InputAt(index));
        } else if (index == inlinee_new_target_index) {
          // The projection is requesting the new target value.
          Replace(use, new_target);
        } else if (index == inlinee_arity_index) {
          // The projection is requesting the number of arguments.
          Replace(use, jsgraph()->ConstantNoHole(argument_count));
        } else if (index == inlinee_context_index) {
          // The projection is requesting the inlinee function context.
          Replace(use, context);
        } else {
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
          // Using the dispatch handle here isn't currently supported.
          DCHECK_NE(index, start.DispatchHandleOutputIndex());
#endif
          // Call has fewer arguments than required, fill with undefined.
          Replace(use, jsgraph()->UndefinedConstant());
        }
        break;
      }
      default:
        if (NodeProperties::IsEffectEdge(edge)) {
          edge.UpdateTo(effect);
        } else if (NodeProperties::IsControlEdge(edge)) {
          edge.UpdateTo(control);
        } else if (NodeProperties::IsFrameStateEdge(edge)) {
          edge.UpdateTo(frame_state);
        } else {
          UNREACHABLE();
        }
        break;
    }
  }
  if (exception_target != nullptr) {
    // Link uncaught calls in the inlinee to {exception_target}
    int subcall_count = static_cast<int>(uncaught_subcalls.size());
    if (subcall_count > 0) {
      TRACE("Inlinee contains " << subcall_count
                                << " calls without local exception handler; "
                                << "linking to surrounding exception handler.");
    }
    NodeVector on_exception_nodes(local_zone_);
    for (Node* subcall : uncaught_subcalls) {
      Node* on_success = graph()->NewNode(common()->IfSuccess(), subcall);
      NodeProperties::ReplaceUses(subcall, subcall, subcall, on_success);
      NodeProperties::ReplaceControlInput(on_success, subcall);
      Node* on_exception =
          graph()->NewNode(common()->IfException(), subcall, subcall);
      on_exception_nodes.push_back(on_exception);
    }
    DCHECK_EQ(subcall_count, static_cast<int>(on_exception_nodes.size()));
    if (subcall_count > 0) {
      Node* control_output =
          graph()->NewNode(common()->Merge(subcall_count), subcall_count,
                           &on_exception_nodes.front());
      NodeVector values_effects(local_zone_);
      values_effects = on_exception_nodes;
      values_effects.push_back(control_output);
      Node* value_output = graph()->NewNode(
          common()->Phi(MachineRepresentation::kTagged, subcall_count),
          subcall_count + 1, &values_effects.front());
      Node* effect_output =
          graph()->NewNode(common()->EffectPhi(subcall_count),
                           subcall_count + 1, &values_effects.front());
      ReplaceWithValue(exception_target, value_output, effect_output,
                       control_output);
    } else {
      ReplaceWithValue(exception_target, exception_target, exception_target,
                       jsgraph()->Dead());
    }
  }
  NodeVector values(local_zone_);
  NodeVector effects(local_zone_);
  NodeVector controls(local_zone_);
  for (Node* const input : end->inputs()) {
    switch (input->opcode()) {
      case IrOpcode::kReturn:
        values.push_back(NodeProperties::GetValueInput(input, 1));
        effects.push_back(NodeProperties::GetEffectInput(input));
        controls.push_back(NodeProperties::GetControlInput(input));
        break;
      case IrOpcode::kDeoptimize:
      case IrOpcode::kTerminate:
      case IrOpcode::kThrow:
        MergeControlToEnd(graph(), common(), input);
        break;
      default:
        UNREACHABLE();
    }
  }
  DCHECK_EQ(values.size(), effects.size());
  DCHECK_EQ(values.size(), controls.size());
  // Depending on whether the inlinee produces a value, we either replace value
  // uses with said value or kill value uses if no value can be returned.
  if (!values.empty()) {
    int const input_count = static_cast<int>(controls.size());
    Node* control_output = graph()->NewNode(common()->Merge(input_count),
                                            input_count, &controls.front());
    values.push_back(control_output);
    effects.push_back(control_output);
    Node* value_output = graph()->NewNode(
        common()->Phi(MachineRepresentation::kTagged, input_count),
        static_cast<int>(values.size()), &values.front());
    Node* effect_output =
        graph()->NewNode(common()->EffectPhi(input_count),
                         static_cast<int>(effects.size()), &effects.front());
    ReplaceWithValue(call, value_output, effect_output, control_output);
    return Changed(value_output);
  } else {
    ReplaceWithValue(call, jsgraph()->Dead(), jsgraph()->Dead(),
                     jsgraph()->Dead());
    return Changed(call);
  }
}
References v8::internal::compiler::StartNode::ArgCountOutputIndex(), v8::internal::compiler::Reducer::Changed(), common(), v8::internal::compiler::StartNode::ContextOutputIndex(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_LE, DCHECK_NE, v8::internal::ZoneVector< T >::empty(), v8::internal::compiler::end(), v8::internal::ZoneVector< T >::front(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::NodeProperties::IsControlEdge(), v8::internal::compiler::NodeProperties::IsEffectEdge(), v8::internal::compiler::NodeProperties::IsFrameStateEdge(), v8::internal::compiler::IrOpcode::IsInlineeOpcode(), jsgraph(), v8::internal::compiler::JSCallOrConstructNode::kExtraInputCount, v8::internal::compiler::JSCallOrConstructNode::kFeedbackVectorInputCount, v8::internal::kTagged, local_zone_, v8::internal::compiler::AdvancedReducer::MergeControlToEnd(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::StartNode::NewTargetOutputIndex(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::ParameterIndexOf(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::NodeProperties::ReplaceUses(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::ZoneVector< T >::size(), v8::internal::TRACE(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), v8::internal::UNREACHABLE(), and use().
Referenced by ReduceJSCall().
isolate()
Isolate* v8::internal::compiler::JSInliner::isolate () const [inline], [private]
Definition at line 90 of file js-inlining.h.
{ return jsgraph_->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph_.
javascript()
JSOperatorBuilder * v8::internal::compiler::JSInliner::javascript () const [private]
Definition at line 970 of file js-inlining.cc.
                                               {
  return jsgraph()->javascript();
}
References v8::internal::compiler::JSGraph::javascript(), and jsgraph().
Referenced by ReduceJSCall().
jsgraph()
JSGraph* v8::internal::compiler::JSInliner::jsgraph () const [inline], [private]
Definition at line 87 of file js-inlining.h.
{ return jsgraph_; }
References jsgraph_.
Referenced by common(), CreateArtificialFrameState(), DetermineCallContext(), graph(), InlineCall(), javascript(), ReduceJSCall(), and simplified().
Reduce()
Reduction v8::internal::compiler::JSInliner::Reduce (Node * node) [inline], [final], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 60 of file js-inlining.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
ReduceJSCall()
Reduction v8::internal::compiler::JSInliner::ReduceJSCall (Node * node)
Definition at line 680 of file js-inlining.cc.
                                            {
  DCHECK(IrOpcode::IsInlineeOpcode(node->opcode()));
#if V8_ENABLE_WEBASSEMBLY
  DCHECK_NE(node->opcode(), IrOpcode::kJSWasmCall);
#endif // V8_ENABLE_WEBASSEMBLY
  JSCallAccessor call(node);
  // Determine the call target.
  OptionalSharedFunctionInfoRef shared_info(DetermineCallTarget(node));
  if (!shared_info.has_value()) return NoChange();
  SharedFunctionInfoRef outer_shared_info =
      MakeRef(broker(), info_->shared_info());
  SharedFunctionInfo::Inlineability inlineability =
      shared_info->GetInlineability(CodeKind::TURBOFAN_JS, broker());
  if (inlineability != SharedFunctionInfo::kIsInlineable) {
    // The function is no longer inlineable. The only way this can happen is if
    // the function had its optimization disabled in the meantime, e.g. because
    // another optimization job failed too often.
    CHECK_EQ(inlineability, SharedFunctionInfo::kHasOptimizationDisabled);
    TRACE("Not inlining " << *shared_info << " into " << outer_shared_info
                          << " because it had its optimization disabled.");
    return NoChange();
  }
  // NOTE: Even though we bailout in the kHasOptimizationDisabled case above, we
  // won't notice if the function's optimization is disabled after this point.
  // Constructor must be constructable.
  if (node->opcode() == IrOpcode::kJSConstruct &&
      !IsConstructable(shared_info->kind())) {
    TRACE("Not inlining " << *shared_info << " into " << outer_shared_info
                          << " because constructor is not constructable.");
    return NoChange();
  }
  // Class constructors are callable, but [[Call]] will raise an exception.
  // See ES6 section 9.2.1 [[Call]] (thisArgument, argumentsList).
  if (node->opcode() == IrOpcode::kJSCall &&
      IsClassConstructor(shared_info->kind())) {
    TRACE("Not inlining " << *shared_info << " into " << outer_shared_info
                          << " because callee is a class constructor.");
    return NoChange();
  }
  // To ensure inlining always terminates, we have an upper limit on inlining
  // the nested calls.
  int nesting_level = 0;
  for (Node* frame_state = call.frame_state();
       frame_state->opcode() == IrOpcode::kFrameState;
       frame_state = FrameState{frame_state}.outer_frame_state()) {
    nesting_level++;
    if (nesting_level > kMaxDepthForInlining) {
      TRACE("Not inlining "
            << *shared_info << " into " << outer_shared_info
            << " because call has exceeded the maximum depth for function "
               "inlining.");
      return NoChange();
    }
  }
  Node* exception_target = nullptr;
  NodeProperties::IsExceptionalCall(node, &exception_target);
  // JSInliningHeuristic has already filtered candidates without a BytecodeArray
  // based on SharedFunctionInfoRef::GetInlineability. For the inlineable ones
  // (kIsInlineable), the broker holds a reference to the bytecode array, which
  // prevents it from getting flushed. Therefore, the following check should
  // always hold true.
  CHECK(shared_info->is_compiled());
  if (info_->source_positions() &&
      !shared_info->object()->AreSourcePositionsAvailable(
          broker()->local_isolate_or_isolate())) {
    // This case is expected to be very rare, since we generate source
    // positions for all functions when debugging or profiling are turned
    // on (see Isolate::NeedsDetailedOptimizedCodeLineInfo). Source
    // positions should only be missing here if there is a race between 1)
    // enabling/disabling the debugger/profiler, and 2) this compile job.
    // In that case, we simply don't inline.
    TRACE("Not inlining " << *shared_info << " into " << outer_shared_info
                          << " because source positions are missing.");
    return NoChange();
  }
  // Determine the target's feedback vector and its context.
  Node* context;
  FeedbackCellRef feedback_cell = DetermineCallContext(node, &context);
  TRACE("Inlining " << *shared_info << " into " << outer_shared_info
                    << ((exception_target != nullptr) ? " (inside try-block)"
                                                      : ""));
  // ----------------------------------------------------------------
  // After this point, we've made a decision to inline this function.
  // We shall not bailout from inlining if we got here.
  BytecodeArrayRef bytecode_array = shared_info->GetBytecodeArray(broker());
  // Remember that we inlined this function.
  int inlining_id =
      info_->AddInlinedFunction(shared_info->object(), bytecode_array.object(),
                                source_positions_->GetSourcePosition(node));
  if (v8_flags.profile_guided_optimization &&
      feedback_cell.feedback_vector(broker()).has_value() &&
      feedback_cell.feedback_vector(broker())
              .value()
              .object()
              ->invocation_count_before_stable(kRelaxedLoad) >
          v8_flags.invocation_count_for_early_optimization) {
    info_->set_could_not_inline_all_candidates();
  }
  // Create the subgraph for the inlinee.
  Node* start_node;
  Node* end;
  {
    // Run the BytecodeGraphBuilder to create the subgraph.
    TFGraph::SubgraphScope scope(graph());
    BytecodeGraphBuilderFlags flags(
        BytecodeGraphBuilderFlag::kSkipFirstStackAndTierupCheck);
    if (info_->analyze_environment_liveness()) {
      flags |= BytecodeGraphBuilderFlag::kAnalyzeEnvironmentLiveness;
    }
    if (info_->bailout_on_uninitialized()) {
      flags |= BytecodeGraphBuilderFlag::kBailoutOnUninitialized;
    }
    {
      CallFrequency frequency = call.frequency();
      BuildGraphFromBytecode(broker(), zone(), *shared_info, bytecode_array,
                             feedback_cell, BytecodeOffset::None(), jsgraph(),
                             frequency, source_positions_, node_origins_,
                             inlining_id, info_->code_kind(), flags,
                             &info_->tick_counter());
    }
    // Extract the inlinee start/end nodes.
    start_node = graph()->start();
    end = graph()->end();
  }
  StartNode start{start_node};
  // If we are inlining into a surrounding exception handler, we collect all
  // potentially throwing nodes within the inlinee that are not handled locally
  // by the inlinee itself. They are later wired into the surrounding handler.
  NodeVector uncaught_subcalls(local_zone_);
  if (exception_target != nullptr) {
    // Find all uncaught 'calls' in the inlinee.
    AllNodes inlined_nodes(local_zone_, end, graph());
    for (Node* subnode : inlined_nodes.reachable) {
      // Every possibly throwing node should get {IfSuccess} and {IfException}
      // projections, unless there already is local exception handling.
      if (subnode->op()->HasProperty(Operator::kNoThrow)) continue;
      if (!NodeProperties::IsExceptionalCall(subnode)) {
        DCHECK_EQ(2, subnode->op()->ControlOutputCount());
        uncaught_subcalls.push_back(subnode);
      }
    }
  }
  FrameState frame_state = call.frame_state();
  Node* new_target = jsgraph()->UndefinedConstant();
  // Inline {JSConstruct} requires some additional magic.
  if (node->opcode() == IrOpcode::kJSConstruct) {
    static_assert(JSCallOrConstructNode::kHaveIdenticalLayouts);
    JSConstructNode n(node);
    new_target = n.new_target();
    // Insert nodes around the call that model the behavior required for a
    // constructor dispatch (allocate implicit receiver and check return value).
    // This models the behavior usually accomplished by our {JSConstructStub}.
    // Note that the context has to be the callers context (input to call node).
    // Also note that by splitting off the {JSCreate} piece of the constructor
    // call, we create an observable deoptimization point after the receiver
    // instantiation but before the invocation (i.e. inside {JSConstructStub}
    // where execution continues at {construct_stub_create_deopt_pc_offset}).
    Node* receiver = jsgraph()->TheHoleConstant(); // Implicit receiver.
    Node* caller_context = NodeProperties::GetContextInput(node);
    if (NeedsImplicitReceiver(*shared_info)) {
      Effect effect = n.effect();
      Control control = n.control();
      Node* frame_state_inside;
      HeapObjectMatcher m(new_target);
      if (m.HasResolvedValue() && m.Ref(broker()).IsJSFunction()) {
        // If {new_target} is a JSFunction, then we cannot deopt in the
        // NewObject call. Therefore we do not need the artificial frame state.
        frame_state_inside = frame_state;
      } else {
        frame_state_inside = CreateArtificialFrameState(
            node, frame_state, n.ArgumentCount(),
            FrameStateType::kConstructCreateStub, *shared_info, bytecode_array,
            caller_context);
      }
      Node* create =
          graph()->NewNode(javascript()->Create(), call.target(), new_target,
                           caller_context, frame_state_inside, effect, control);
      uncaught_subcalls.push_back(create); // Adds {IfSuccess} & {IfException}.
      NodeProperties::ReplaceControlInput(node, create);
      NodeProperties::ReplaceEffectInput(node, create);
      // Placeholder to hold {node}'s value dependencies while {node} is
      // replaced.
      Node* dummy = graph()->NewNode(common()->Dead());
      NodeProperties::ReplaceUses(node, dummy, node, node, node);
      Node* result;
      // Insert a check of the return value to determine whether the return
      // value or the implicit receiver should be selected as a result of the
      // call.
      Node* check = graph()->NewNode(simplified()->ObjectIsReceiver(), node);
      result =
          graph()->NewNode(common()->Select(MachineRepresentation::kTagged),
                           check, node, create);
      receiver = create; // The implicit receiver.
      ReplaceWithValue(dummy, result);
    } else if (IsDerivedConstructor(shared_info->kind())) {
      Node* node_success =
          NodeProperties::FindSuccessfulControlProjection(node);
      Node* is_receiver =
          graph()->NewNode(simplified()->ObjectIsReceiver(), node);
      Node* branch_is_receiver =
          graph()->NewNode(common()->Branch(), is_receiver, node_success);
      Node* branch_is_receiver_true =
          graph()->NewNode(common()->IfTrue(), branch_is_receiver);
      Node* branch_is_receiver_false =
          graph()->NewNode(common()->IfFalse(), branch_is_receiver);
      branch_is_receiver_false = graph()->NewNode(
          javascript()->CallRuntime(
              Runtime::kThrowConstructorReturnedNonObject),
          caller_context, NodeProperties::GetFrameStateInput(node), node,
          branch_is_receiver_false);
      uncaught_subcalls.push_back(branch_is_receiver_false);
      branch_is_receiver_false =
          graph()->NewNode(common()->Throw(), branch_is_receiver_false,
                           branch_is_receiver_false);
      MergeControlToEnd(graph(), common(), branch_is_receiver_false);
      ReplaceWithValue(node_success, node_success, node_success,
                       branch_is_receiver_true);
      // Fix input destroyed by the above {ReplaceWithValue} call.
      NodeProperties::ReplaceControlInput(branch_is_receiver, node_success, 0);
    }
    node->ReplaceInput(JSCallNode::ReceiverIndex(), receiver);
    // Insert a construct stub frame into the chain of frame states. This will
    // reconstruct the proper frame when deoptimizing within the constructor.
    frame_state = CreateArtificialFrameState(
        node, frame_state, 0, FrameStateType::kConstructInvokeStub,
        *shared_info, bytecode_array, caller_context);
  }
  // Insert a JSConvertReceiver node for sloppy callees. Note that the context
  // passed into this node has to be the callees context (loaded above).
  if (node->opcode() == IrOpcode::kJSCall &&
      is_sloppy(shared_info->language_mode()) && !shared_info->native()) {
    Effect effect{NodeProperties::GetEffectInput(node)};
    if (NodeProperties::CanBePrimitive(broker(), call.receiver(), effect)) {
      CallParameters const& p = CallParametersOf(node->op());
      Node* global_proxy = jsgraph()->ConstantNoHole(
          broker()->target_native_context().global_proxy_object(broker()),
          broker());
      Node* receiver = effect = graph()->NewNode(
          simplified()->ConvertReceiver(p.convert_mode()), call.receiver(),
          jsgraph()->ConstantNoHole(broker()->target_native_context(),
                                    broker()),
          global_proxy, effect, start);
      NodeProperties::ReplaceValueInput(node, receiver,
                                        JSCallNode::ReceiverIndex());
      NodeProperties::ReplaceEffectInput(node, effect);
    }
  }
  // Insert inlined extra arguments if required. The callees formal parameter
  // count have to match the number of arguments passed to the call.
  int parameter_count = bytecode_array.parameter_count_without_receiver();
  DCHECK_EQ(
      parameter_count,
      shared_info
          ->internal_formal_parameter_count_without_receiver_deprecated());
  DCHECK_EQ(parameter_count, start.FormalParameterCountWithoutReceiver());
  if (call.argument_count() != parameter_count) {
    frame_state = CreateArtificialFrameState(
        node, frame_state, call.argument_count(),
        FrameStateType::kInlinedExtraArguments, *shared_info, bytecode_array);
  }
  return InlineCall(node, new_target, context, frame_state, start, end,
                    exception_target, uncaught_subcalls, call.argument_count());
}
References v8::internal::OptimizedCompilationInfo::AddInlinedFunction(), v8::internal::compiler::JSCallAccessor::argument_count(), v8::internal::compiler::JSConstructNodeBase< kOpcode >::ArgumentCount(), broker(), v8::internal::compiler::BuildGraphFromBytecode(), v8::internal::compiler::CallParametersOf(), v8::internal::compiler::NodeProperties::CanBePrimitive(), CHECK, CHECK_EQ, v8::internal::OptimizedCompilationInfo::code_kind(), common(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::Operator::ControlOutputCount(), v8::internal::compiler::CallParameters::convert_mode(), CreateArtificialFrameState(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, DetermineCallContext(), DetermineCallTarget(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::TFGraph::end(), v8::internal::compiler::end(), v8::internal::compiler::FeedbackCellRef::feedback_vector(), v8::internal::compiler::NodeProperties::FindSuccessfulControlProjection(), v8::internal::flags, v8::internal::compiler::JSCallAccessor::frame_state(), v8::internal::compiler::JSCallAccessor::frequency(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetFrameStateInput(), v8::internal::compiler::SourcePositionTable::GetSourcePosition(), graph(), v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), info_, InlineCall(), v8::internal::is_sloppy(), v8::internal::IsClassConstructor(), v8::internal::IsConstructable(), v8::internal::IsDerivedConstructor(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), v8::internal::compiler::IrOpcode::IsInlineeOpcode(), javascript(), jsgraph(), v8::internal::compiler::kAnalyzeEnvironmentLiveness, v8::internal::compiler::kBailoutOnUninitialized, v8::internal::compiler::kConstructCreateStub, v8::internal::compiler::kConstructInvokeStub, v8::internal::SharedFunctionInfo::kHasOptimizationDisabled, v8::internal::compiler::JSCallOrConstructNode::kHaveIdenticalLayouts, v8::internal::compiler::kInlinedExtraArguments, v8::internal::SharedFunctionInfo::kIsInlineable, v8::internal::compiler::anonymous_namespace{js-inlining.cc}::kMaxDepthForInlining, v8::internal::compiler::Operator::kNoThrow, v8::kRelaxedLoad, v8::internal::compiler::kSkipFirstStackAndTierupCheck, v8::internal::kTagged, local_zone_, v8::internal::compiler::MakeRef(), v8::internal::compiler::AdvancedReducer::MergeControlToEnd(), v8::internal::compiler::anonymous_namespace{js-inlining.cc}::NeedsImplicitReceiver(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Reducer::NoChange(), node_origins_, v8::internal::BytecodeOffset::None(), v8::internal::compiler::BytecodeArrayRef::object(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::FrameState::outer_frame_state(), v8::internal::compiler::BytecodeArrayRef::parameter_count_without_receiver(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::AllNodes::reachable, v8::internal::compiler::JSCallAccessor::receiver(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::NodeProperties::ReplaceUses(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::base::internal::result, v8::internal::OptimizedCompilationInfo::shared_info(), simplified(), source_positions_, v8::internal::compiler::TFGraph::start(), v8::internal::compiler::JSCallAccessor::target(), v8::internal::OptimizedCompilationInfo::tick_counter(), v8::internal::TRACE(), v8::internal::v8_flags, v8::internal::value, and zone().
Referenced by v8::internal::compiler::JSInliningHeuristic::InlineCandidate().
reducer_name()
const char* v8::internal::compiler::JSInliner::reducer_name () const [inline], [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 58 of file js-inlining.h.
{ return "JSInliner"; }
simplified()
SimplifiedOperatorBuilder * v8::internal::compiler::JSInliner::simplified () const [private]
Definition at line 976 of file js-inlining.cc.
                                                       {
  return jsgraph()->simplified();
}
References jsgraph(), and v8::internal::compiler::JSGraph::simplified().
Referenced by DetermineCallContext(), and ReduceJSCall().
zone()
Zone* v8::internal::compiler::JSInliner::zone () const [inline], [private]
Definition at line 82 of file js-inlining.h.
{ return local_zone_; }
References local_zone_.
Referenced by ReduceJSCall().
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::JSInliner::broker_ [private]
Definition at line 95 of file js-inlining.h.
Referenced by broker().
info_
OptimizedCompilationInfo* v8::internal::compiler::JSInliner::info_ [private]
Definition at line 93 of file js-inlining.h.
Referenced by ReduceJSCall().
inline_wasm_fct_if_supported_
bool v8::internal::compiler::JSInliner::inline_wasm_fct_if_supported_ [private]
Definition at line 103 of file js-inlining.h.
Referenced by JSInliner().
js_wasm_calls_sidetable_
JsWasmCallsSidetable* v8::internal::compiler::JSInliner::js_wasm_calls_sidetable_ [private]
Definition at line 99 of file js-inlining.h.
Referenced by JSInliner().
jsgraph_
JSGraph* const v8::internal::compiler::JSInliner::jsgraph_ [private]
Definition at line 94 of file js-inlining.h.
Referenced by isolate(), and jsgraph().
local_zone_
Zone* const v8::internal::compiler::JSInliner::local_zone_ [private]
Definition at line 92 of file js-inlining.h.
Referenced by CreateArtificialFrameState(), InlineCall(), ReduceJSCall(), and zone().
node_origins_
NodeOriginTable* const v8::internal::compiler::JSInliner::node_origins_ [private]
Definition at line 97 of file js-inlining.h.
Referenced by ReduceJSCall().
source_positions_
SourcePositionTable* const v8::internal::compiler::JSInliner::source_positions_ [private]
Definition at line 96 of file js-inlining.h.
Referenced by ReduceJSCall().
wasm_module_
const wasm::WasmModule* v8::internal::compiler::JSInliner::wasm_module_ [private]
Definition at line 98 of file js-inlining.h.
Referenced by JSInliner().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/js-inlining.h
/mnt/V8SourceCode/src/compiler/js-inlining.cc