v8::internal::compiler::JSTypeHintLowering Class Reference
#include <js-type-hint-lowering.h>
Classes
class LoweringResult
Public Types
enum Flag { kNoFlags = 0u
, kBailoutOnUninitialized = 1u << 1
 }
using Flags = base::Flags< Flag >
Public Member Functions
JSTypeHintLowering (JSHeapBroker *broker, JSGraph *jsgraph, FeedbackVectorRef feedback_vector, Flags flags)
JSTypeHintLowering (const JSTypeHintLowering &)=delete
JSTypeHintLowering & operator= (const JSTypeHintLowering &)=delete
LoweringResult ReduceUnaryOperation (const Operator *op, Node *operand, Node *effect, Node *control, FeedbackSlot slot) const
LoweringResult ReduceBinaryOperation (const Operator *op, Node *left, Node *right, Node *effect, Node *control, FeedbackSlot slot) const
LoweringResult ReduceForInNextOperation (Node *receiver, Node *cache_array, Node *cache_type, Node *index, Node *effect, Node *control, FeedbackSlot slot) const
LoweringResult ReduceForInPrepareOperation (Node *enumerator, Node *effect, Node *control, FeedbackSlot slot) const
LoweringResult ReduceToNumberOperation (Node *value, Node *effect, Node *control, FeedbackSlot slot) const
LoweringResult ReduceConstructOperation (const Operator *op, Node *const *args, int arg_count, Node *effect, Node *control, FeedbackSlot slot) const
LoweringResult ReduceGetIteratorOperation (const Operator *op, Node *obj, Node *effect, Node *control, FeedbackSlot load_slot, FeedbackSlot call_slot) const
LoweringResult ReduceLoadNamedOperation (const Operator *op, Node *effect, Node *control, FeedbackSlot slot) const
LoweringResult ReduceLoadKeyedOperation (const Operator *op, Node *obj, Node *key, Node *effect, Node *control, FeedbackSlot slot) const
LoweringResult ReduceStoreNamedOperation (const Operator *op, Node *obj, Node *val, Node *effect, Node *control, FeedbackSlot slot) const
LoweringResult ReduceStoreKeyedOperation (const Operator *op, Node *obj, Node *key, Node *val, Node *effect, Node *control, FeedbackSlot slot) const
Private Member Functions
BinaryOperationHint GetBinaryOperationHint (FeedbackSlot slot) const
CompareOperationHint GetCompareOperationHint (FeedbackSlot slot) const
Node * BuildDeoptIfFeedbackIsInsufficient (FeedbackSlot slot, Node *effect, Node *control, DeoptimizeReason reson) const
JSHeapBroker * broker () const
JSGraph * jsgraph () const
Isolate * isolate () const
Flags flags () const
FeedbackVectorRef feedback_vector () const
Private Attributes
JSHeapBroker *const broker_
JSGraph *const jsgraph_
Flags const flags_
FeedbackVectorRef const feedback_vector_
Friends
class JSSpeculativeBinopBuilder
Detailed Description
Definition at line 36 of file js-type-hint-lowering.h.
Member Typedef Documentation
Flags
using v8::internal::compiler::JSTypeHintLowering::Flags = base::Flags<Flag>
Definition at line 40 of file js-type-hint-lowering.h.
Member Enumeration Documentation
Flag
enum v8::internal::compiler::JSTypeHintLowering::Flag
Enumerator
kNoFlags
kBailoutOnUninitialized
Definition at line 39 of file js-type-hint-lowering.h.
{ kNoFlags = 0u, kBailoutOnUninitialized = 1u << 1 };
Constructor & Destructor Documentation
JSTypeHintLowering() [1/2]
v8::internal::compiler::JSTypeHintLowering::JSTypeHintLowering (JSHeapBroker * broker, JSGraph * jsgraph, FeedbackVectorRef feedback_vector, Flags flags)
Definition at line 344 of file js-type-hint-lowering.cc.
    : broker_(broker),
      jsgraph_(jsgraph),
      flags_(flags),
      feedback_vector_(feedback_vector) {}
JSTypeHintLowering() [2/2]
v8::internal::compiler::JSTypeHintLowering::JSTypeHintLowering (const JSTypeHintLowering &) [delete]
Member Function Documentation
broker()
JSHeapBroker* v8::internal::compiler::JSTypeHintLowering::broker () const [inline], [private]
Definition at line 166 of file js-type-hint-lowering.h.
{ return broker_; }
References broker_.
Referenced by BuildDeoptIfFeedbackIsInsufficient(), GetBinaryOperationHint(), GetCompareOperationHint(), and ReduceUnaryOperation().
BuildDeoptIfFeedbackIsInsufficient()
Node * v8::internal::compiler::JSTypeHintLowering::BuildDeoptIfFeedbackIsInsufficient (FeedbackSlot slot, Node * effect, Node * control, DeoptimizeReason reson) const [private]
Definition at line 669 of file js-type-hint-lowering.cc.
                                   {
  if (!(flags() & kBailoutOnUninitialized)) return nullptr;
  FeedbackSource source(feedback_vector(), slot);
  if (!broker()->FeedbackIsInsufficient(source)) return nullptr;
  Node* deoptimize = jsgraph()->graph()->NewNode(
      jsgraph()->common()->Deoptimize(reason, FeedbackSource()),
      jsgraph()->Dead(), effect, control);
  Node* frame_state =
      NodeProperties::FindFrameStateBefore(deoptimize, jsgraph()->Dead());
  deoptimize->ReplaceInput(0, frame_state);
  return deoptimize;
}
References broker(), feedback_vector(), v8::internal::compiler::NodeProperties::FindFrameStateBefore(), flags(), v8::internal::compiler::MachineGraph::graph(), jsgraph(), kBailoutOnUninitialized, v8::internal::compiler::TFGraph::NewNode(), and v8::internal::compiler::Node::ReplaceInput().
Referenced by ReduceBinaryOperation(), ReduceConstructOperation(), ReduceForInNextOperation(), ReduceForInPrepareOperation(), ReduceGetIteratorOperation(), ReduceLoadKeyedOperation(), ReduceLoadNamedOperation(), ReduceStoreKeyedOperation(), ReduceStoreNamedOperation(), and ReduceUnaryOperation().
feedback_vector()
FeedbackVectorRef v8::internal::compiler::JSTypeHintLowering::feedback_vector () const [inline], [private]
Definition at line 170 of file js-type-hint-lowering.h.
{ return feedback_vector_; }
References feedback_vector_.
Referenced by BuildDeoptIfFeedbackIsInsufficient(), GetBinaryOperationHint(), GetCompareOperationHint(), and ReduceUnaryOperation().
flags()
Flags v8::internal::compiler::JSTypeHintLowering::flags () const [inline], [private]
Definition at line 169 of file js-type-hint-lowering.h.
{ return flags_; }
References flags_.
Referenced by BuildDeoptIfFeedbackIsInsufficient().
GetBinaryOperationHint()
BinaryOperationHint v8::internal::compiler::JSTypeHintLowering::GetBinaryOperationHint (FeedbackSlot slot) const [private]
Definition at line 354 of file js-type-hint-lowering.cc.
                             {
  FeedbackSource source(feedback_vector(), slot);
  return broker()->GetFeedbackForBinaryOperation(source);
}
References broker(), feedback_vector(), and v8::internal::compiler::JSHeapBroker::GetFeedbackForBinaryOperation().
Referenced by v8::internal::compiler::JSSpeculativeBinopBuilder::GetBinaryOperationHint(), ReduceToNumberOperation(), and ReduceUnaryOperation().
GetCompareOperationHint()
CompareOperationHint v8::internal::compiler::JSTypeHintLowering::GetCompareOperationHint (FeedbackSlot slot) const [private]
Definition at line 360 of file js-type-hint-lowering.cc.
                             {
  FeedbackSource source(feedback_vector(), slot);
  return broker()->GetFeedbackForCompareOperation(source);
}
References broker(), feedback_vector(), and v8::internal::compiler::JSHeapBroker::GetFeedbackForCompareOperation().
Referenced by v8::internal::compiler::JSSpeculativeBinopBuilder::GetCompareOperationHint().
isolate()
Isolate * v8::internal::compiler::JSTypeHintLowering::isolate () const [private]
Definition at line 352 of file js-type-hint-lowering.cc.
{ return jsgraph()->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph().
jsgraph()
JSGraph* v8::internal::compiler::JSTypeHintLowering::jsgraph () const [inline], [private]
Definition at line 167 of file js-type-hint-lowering.h.
{ return jsgraph_; }
References jsgraph_.
Referenced by BuildDeoptIfFeedbackIsInsufficient(), isolate(), v8::internal::compiler::JSSpeculativeBinopBuilder::jsgraph(), ReduceToNumberOperation(), and ReduceUnaryOperation().
operator=()
JSTypeHintLowering& v8::internal::compiler::JSTypeHintLowering::operator= (const JSTypeHintLowering &) [delete]
ReduceBinaryOperation()
JSTypeHintLowering::LoweringResult v8::internal::compiler::JSTypeHintLowering::ReduceBinaryOperation (const Operator * op, Node * left, Node * right, Node * effect, Node * control, FeedbackSlot slot) const
Definition at line 469 of file js-type-hint-lowering.cc.
                             {
  switch (op->opcode()) {
    case IrOpcode::kJSStrictEqual: {
      if (Node* node = BuildDeoptIfFeedbackIsInsufficient(
              slot, effect, control,
              DeoptimizeReason::kInsufficientTypeFeedbackForCompareOperation)) {
        return LoweringResult::Exit(node);
      }
      // TODO(turbofan): Should we generally support early lowering of
      // JSStrictEqual operators here?
      break;
    }
    case IrOpcode::kJSEqual:
    case IrOpcode::kJSLessThan:
    case IrOpcode::kJSGreaterThan:
    case IrOpcode::kJSLessThanOrEqual:
    case IrOpcode::kJSGreaterThanOrEqual: {
      if (Node* node = BuildDeoptIfFeedbackIsInsufficient(
              slot, effect, control,
              DeoptimizeReason::kInsufficientTypeFeedbackForCompareOperation)) {
        return LoweringResult::Exit(node);
      }
      JSSpeculativeBinopBuilder b(this, op, left, right, effect, control, slot);
      if (Node* node = b.TryBuildNumberCompare()) {
        return LoweringResult::SideEffectFree(node, node, control);
      }
      if (Node* node = b.TryBuildBigIntCompare()) {
        return LoweringResult::SideEffectFree(node, node, control);
      }
      break;
    }
    case IrOpcode::kJSInstanceOf: {
      if (Node* node = BuildDeoptIfFeedbackIsInsufficient(
              slot, effect, control,
              DeoptimizeReason::kInsufficientTypeFeedbackForCompareOperation)) {
        return LoweringResult::Exit(node);
      }
      // TODO(turbofan): Should we generally support early lowering of
      // JSInstanceOf operators here?
      break;
    }
    case IrOpcode::kJSBitwiseOr:
    case IrOpcode::kJSBitwiseXor:
    case IrOpcode::kJSBitwiseAnd:
    case IrOpcode::kJSShiftLeft:
    case IrOpcode::kJSShiftRight:
    case IrOpcode::kJSShiftRightLogical:
    case IrOpcode::kJSAdd:
    case IrOpcode::kJSSubtract:
    case IrOpcode::kJSMultiply:
    case IrOpcode::kJSDivide:
    case IrOpcode::kJSModulus:
    case IrOpcode::kJSExponentiate: {
      if (Node* node = BuildDeoptIfFeedbackIsInsufficient(
              slot, effect, control,
              DeoptimizeReason::kInsufficientTypeFeedbackForBinaryOperation)) {
        return LoweringResult::Exit(node);
      }
      JSSpeculativeBinopBuilder b(this, op, left, right, effect, control, slot);
      if (Node* node = b.TryBuildNumberBinop()) {
        return LoweringResult::SideEffectFree(node, node, control);
      }
      if (op->opcode() != IrOpcode::kJSShiftRightLogical &&
          op->opcode() != IrOpcode::kJSExponentiate) {
        if (Node* node = b.TryBuildBigIntBinop()) {
          return LoweringResult::SideEffectFree(node, node, control);
        }
      }
      break;
    }
    default:
      UNREACHABLE();
  }
  return LoweringResult::NoChange();
}
References BuildDeoptIfFeedbackIsInsufficient(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::Exit(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::NoChange(), v8::internal::compiler::Operator::opcode(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::SideEffectFree(), v8::internal::compiler::JSSpeculativeBinopBuilder::TryBuildBigIntBinop(), v8::internal::compiler::JSSpeculativeBinopBuilder::TryBuildBigIntCompare(), v8::internal::compiler::JSSpeculativeBinopBuilder::TryBuildNumberBinop(), v8::internal::compiler::JSSpeculativeBinopBuilder::TryBuildNumberCompare(), and v8::internal::UNREACHABLE().
ReduceConstructOperation()
JSTypeHintLowering::LoweringResult v8::internal::compiler::JSTypeHintLowering::ReduceConstructOperation (const Operator * op, Node *const * args, int arg_count, Node * effect, Node * control, FeedbackSlot slot) const
Definition at line 584 of file js-type-hint-lowering.cc.
                                            {
  DCHECK(op->opcode() == IrOpcode::kJSConstruct ||
         op->opcode() == IrOpcode::kJSConstructWithSpread ||
         op->opcode() == IrOpcode::kJSConstructForwardAllArgs);
  if (Node* node = BuildDeoptIfFeedbackIsInsufficient(
          slot, effect, control,
          DeoptimizeReason::kInsufficientTypeFeedbackForConstruct)) {
    return LoweringResult::Exit(node);
  }
  return LoweringResult::NoChange();
}
References BuildDeoptIfFeedbackIsInsufficient(), v8::internal::DCHECK(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::Exit(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::NoChange(), and v8::internal::compiler::Operator::opcode().
ReduceForInNextOperation()
JSTypeHintLowering::LoweringResult v8::internal::compiler::JSTypeHintLowering::ReduceForInNextOperation (Node * receiver, Node * cache_array, Node * cache_type, Node * index, Node * effect, Node * control, FeedbackSlot slot) const
Definition at line 547 of file js-type-hint-lowering.cc.
                                                          {
  if (Node* node = BuildDeoptIfFeedbackIsInsufficient(
          slot, effect, control,
          DeoptimizeReason::kInsufficientTypeFeedbackForForIn)) {
    return LoweringResult::Exit(node);
  }
  return LoweringResult::NoChange();
}
References BuildDeoptIfFeedbackIsInsufficient(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::Exit(), and v8::internal::compiler::JSTypeHintLowering::LoweringResult::NoChange().
ReduceForInPrepareOperation()
JSTypeHintLowering::LoweringResult v8::internal::compiler::JSTypeHintLowering::ReduceForInPrepareOperation (Node * enumerator, Node * effect, Node * control, FeedbackSlot slot) const
Definition at line 559 of file js-type-hint-lowering.cc.
                                                                         {
  if (Node* node = BuildDeoptIfFeedbackIsInsufficient(
          slot, effect, control,
          DeoptimizeReason::kInsufficientTypeFeedbackForForIn)) {
    return LoweringResult::Exit(node);
  }
  return LoweringResult::NoChange();
}
References BuildDeoptIfFeedbackIsInsufficient(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::Exit(), and v8::internal::compiler::JSTypeHintLowering::LoweringResult::NoChange().
ReduceGetIteratorOperation()
JSTypeHintLowering::LoweringResult v8::internal::compiler::JSTypeHintLowering::ReduceGetIteratorOperation (const Operator * op, Node * obj, Node * effect, Node * control, FeedbackSlot load_slot, FeedbackSlot call_slot) const
Definition at line 599 of file js-type-hint-lowering.cc.
                                                                             {
  DCHECK_EQ(IrOpcode::kJSGetIterator, op->opcode());
  if (Node* node = BuildDeoptIfFeedbackIsInsufficient(
          load_slot, effect, control,
          DeoptimizeReason::kInsufficientTypeFeedbackForGenericNamedAccess)) {
    return LoweringResult::Exit(node);
  }
  return LoweringResult::NoChange();
}
References BuildDeoptIfFeedbackIsInsufficient(), DCHECK_EQ, v8::internal::compiler::JSTypeHintLowering::LoweringResult::Exit(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::NoChange(), and v8::internal::compiler::Operator::opcode().
ReduceLoadKeyedOperation()
JSTypeHintLowering::LoweringResult v8::internal::compiler::JSTypeHintLowering::ReduceLoadKeyedOperation (const Operator * op, Node * obj, Node * key, Node * effect, Node * control, FeedbackSlot slot) const
Definition at line 625 of file js-type-hint-lowering.cc.
                             {
  DCHECK_EQ(IrOpcode::kJSLoadProperty, op->opcode());
  if (Node* node = BuildDeoptIfFeedbackIsInsufficient(
          slot, effect, control,
          DeoptimizeReason::kInsufficientTypeFeedbackForGenericKeyedAccess)) {
    return LoweringResult::Exit(node);
  }
  return LoweringResult::NoChange();
}
References BuildDeoptIfFeedbackIsInsufficient(), DCHECK_EQ, v8::internal::compiler::JSTypeHintLowering::LoweringResult::Exit(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::NoChange(), and v8::internal::compiler::Operator::opcode().
ReduceLoadNamedOperation()
JSTypeHintLowering::LoweringResult v8::internal::compiler::JSTypeHintLowering::ReduceLoadNamedOperation (const Operator * op, Node * effect, Node * control, FeedbackSlot slot) const
Definition at line 613 of file js-type-hint-lowering.cc.
                                                                              {
  DCHECK(op->opcode() == IrOpcode::kJSLoadNamed ||
         op->opcode() == IrOpcode::kJSLoadNamedFromSuper);
  if (Node* node = BuildDeoptIfFeedbackIsInsufficient(
          slot, effect, control,
          DeoptimizeReason::kInsufficientTypeFeedbackForGenericNamedAccess)) {
    return LoweringResult::Exit(node);
  }
  return LoweringResult::NoChange();
}
References BuildDeoptIfFeedbackIsInsufficient(), v8::internal::DCHECK(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::Exit(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::NoChange(), and v8::internal::compiler::Operator::opcode().
ReduceStoreKeyedOperation()
JSTypeHintLowering::LoweringResult v8::internal::compiler::JSTypeHintLowering::ReduceStoreKeyedOperation (const Operator * op, Node * obj, Node * key, Node * val, Node * effect, Node * control, FeedbackSlot slot) const
Definition at line 653 of file js-type-hint-lowering.cc.
                                                                       {
  DCHECK(op->opcode() == IrOpcode::kJSSetKeyedProperty ||
         op->opcode() == IrOpcode::kJSStoreInArrayLiteral ||
         op->opcode() == IrOpcode::kJSDefineKeyedOwnPropertyInLiteral ||
         op->opcode() == IrOpcode::kJSDefineKeyedOwnProperty);
  if (Node* node = BuildDeoptIfFeedbackIsInsufficient(
          slot, effect, control,
          DeoptimizeReason::kInsufficientTypeFeedbackForGenericKeyedAccess)) {
    return LoweringResult::Exit(node);
  }
  return LoweringResult::NoChange();
}
References BuildDeoptIfFeedbackIsInsufficient(), v8::internal::DCHECK(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::Exit(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::NoChange(), and v8::internal::compiler::Operator::opcode().
ReduceStoreNamedOperation()
JSTypeHintLowering::LoweringResult v8::internal::compiler::JSTypeHintLowering::ReduceStoreNamedOperation (const Operator * op, Node * obj, Node * val, Node * effect, Node * control, FeedbackSlot slot) const
Definition at line 638 of file js-type-hint-lowering.cc.
                                                                       {
  DCHECK(op->opcode() == IrOpcode::kJSSetNamedProperty ||
         op->opcode() == IrOpcode::kJSDefineNamedOwnProperty);
  if (Node* node = BuildDeoptIfFeedbackIsInsufficient(
          slot, effect, control,
          DeoptimizeReason::kInsufficientTypeFeedbackForGenericNamedAccess)) {
    return LoweringResult::Exit(node);
  }
  return LoweringResult::NoChange();
}
References BuildDeoptIfFeedbackIsInsufficient(), v8::internal::DCHECK(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::Exit(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::NoChange(), and v8::internal::compiler::Operator::opcode().
ReduceToNumberOperation()
JSTypeHintLowering::LoweringResult v8::internal::compiler::JSTypeHintLowering::ReduceToNumberOperation (Node * value, Node * effect, Node * control, FeedbackSlot slot) const
Definition at line 570 of file js-type-hint-lowering.cc.
                                                                       {
  DCHECK(!slot.IsInvalid());
  NumberOperationHint hint;
  if (BinaryOperationHintToNumberOperationHint(GetBinaryOperationHint(slot),
                                               &hint)) {
    Node* node = jsgraph()->graph()->NewNode(
        jsgraph()->simplified()->SpeculativeToNumber(hint, FeedbackSource()),
        input, effect, control);
    return LoweringResult::SideEffectFree(node, node, control);
  }
  return LoweringResult::NoChange();
}
References v8::internal::compiler::anonymous_namespace{js-type-hint-lowering.cc}::BinaryOperationHintToNumberOperationHint(), v8::internal::DCHECK(), GetBinaryOperationHint(), v8::internal::compiler::MachineGraph::graph(), v8::internal::FeedbackSlot::IsInvalid(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::NoChange(), and v8::internal::compiler::JSTypeHintLowering::LoweringResult::SideEffectFree().
ReduceUnaryOperation()
JSTypeHintLowering::LoweringResult v8::internal::compiler::JSTypeHintLowering::ReduceUnaryOperation (const Operator * op, Node * operand, Node * effect, Node * control, FeedbackSlot slot) const
Definition at line 366 of file js-type-hint-lowering.cc.
                             {
  if (Node* node = BuildDeoptIfFeedbackIsInsufficient(
          slot, effect, control,
          DeoptimizeReason::kInsufficientTypeFeedbackForUnaryOperation)) {
    return LoweringResult::Exit(node);
  }
  // Note: Unary and binary operations collect the same kind of feedback.
  FeedbackSource feedback(feedback_vector(), slot);
  Node* node;
  Node* check = nullptr;
  switch (op->opcode()) {
    case IrOpcode::kJSBitwiseNot: {
      // Lower to a speculative xor with -1 if we have some kind of Number
      // feedback.
      JSSpeculativeBinopBuilder b(
          this, jsgraph()->javascript()->BitwiseXor(feedback), operand,
          jsgraph()->SmiConstant(-1), effect, control, slot);
      node = b.TryBuildNumberBinop();
      break;
    }
    case IrOpcode::kJSDecrement: {
      // Lower to a speculative subtraction of 1 if we have some kind of Number
      // feedback.
      JSSpeculativeBinopBuilder b(
          this, jsgraph()->javascript()->Subtract(feedback), operand,
          jsgraph()->SmiConstant(1), effect, control, slot);
      node = b.TryBuildNumberBinop();
      break;
    }
    case IrOpcode::kJSIncrement: {
      // Lower to a speculative addition of 1 if we have some kind of Number
      // feedback.
      JSSpeculativeBinopBuilder b(this, jsgraph()->javascript()->Add(feedback),
                                  operand, jsgraph()->SmiConstant(1), effect,
                                  control, slot);
      node = b.TryBuildNumberBinop();
      break;
    }
    case IrOpcode::kJSNegate: {
      // Lower to a speculative multiplication with -1 if we have some kind of
      // Number feedback.
      JSSpeculativeBinopBuilder b(
          this, jsgraph()->javascript()->Multiply(feedback), operand,
          jsgraph()->SmiConstant(-1), effect, control, slot);
      node = b.TryBuildNumberBinop();
      if (!node) {
        if (jsgraph()->machine()->Is64()) {
          if (GetBinaryOperationHint(slot) == BinaryOperationHint::kBigInt) {
            op = jsgraph()->simplified()->SpeculativeBigIntNegate(
                BigIntOperationHint::kBigInt);
            node = jsgraph()->graph()->NewNode(op, operand, effect, control);
          }
        }
      }
      break;
    }
    case IrOpcode::kTypeOf: {
      TypeOfFeedback::Result hint = broker()->GetFeedbackForTypeOf(feedback);
      switch (hint) {
        case TypeOfFeedback::kNumber:
          check = jsgraph()->graph()->NewNode(
              jsgraph()->simplified()->CheckNumber(FeedbackSource()), operand,
              effect, control);
          node = jsgraph()->ConstantNoHole(broker()->number_string(), broker());
          break;
        case TypeOfFeedback::kString:
          check = jsgraph()->graph()->NewNode(
              jsgraph()->simplified()->CheckString(FeedbackSource()), operand,
              effect, control);
          node = jsgraph()->ConstantNoHole(broker()->string_string(), broker());
          break;
        case TypeOfFeedback::kFunction: {
          Node* condition = jsgraph()->graph()->NewNode(
              jsgraph()->simplified()->ObjectIsDetectableCallable(), operand);
          check = jsgraph()->graph()->NewNode(
              jsgraph()->simplified()->CheckIf(
                  DeoptimizeReason::kNotDetectableReceiver, FeedbackSource()),
              condition, effect, control);
          node =
              jsgraph()->ConstantNoHole(broker()->function_string(), broker());
          break;
        }
        default:
          node = nullptr;
          break;
      }
      break;
    }
    default:
      UNREACHABLE();
  }
  if (node != nullptr) {
    return LoweringResult::SideEffectFree(node, check ? check : node, control);
  } else {
    return LoweringResult::NoChange();
  }
}
References v8::bigint::Add(), broker(), BuildDeoptIfFeedbackIsInsufficient(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::Exit(), feedback_vector(), GetBinaryOperationHint(), v8::internal::compiler::JSHeapBroker::GetFeedbackForTypeOf(), v8::internal::compiler::MachineGraph::graph(), v8::internal::Is64(), jsgraph(), v8::internal::compiler::kBigInt, v8::internal::kBigInt, v8::internal::TypeOfFeedback::kFunction, v8::internal::TypeOfFeedback::kNumber, v8::internal::TypeOfFeedback::kString, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::NoChange(), v8::internal::compiler::Operator::opcode(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::SideEffectFree(), v8::internal::compiler::JSGraph::simplified(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntNegate(), v8::bigint::Subtract(), v8::internal::compiler::JSSpeculativeBinopBuilder::TryBuildNumberBinop(), and v8::internal::UNREACHABLE().
Friends And Related Function Documentation
JSSpeculativeBinopBuilder
friend class JSSpeculativeBinopBuilder [friend]
Definition at line 158 of file js-type-hint-lowering.h.
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::JSTypeHintLowering::broker_ [private]
Definition at line 172 of file js-type-hint-lowering.h.
Referenced by broker().
feedback_vector_
FeedbackVectorRef const v8::internal::compiler::JSTypeHintLowering::feedback_vector_ [private]
Definition at line 175 of file js-type-hint-lowering.h.
Referenced by feedback_vector().
flags_
Flags const v8::internal::compiler::JSTypeHintLowering::flags_ [private]
Definition at line 174 of file js-type-hint-lowering.h.
Referenced by flags().
jsgraph_
JSGraph* const v8::internal::compiler::JSTypeHintLowering::jsgraph_ [private]
Definition at line 173 of file js-type-hint-lowering.h.
Referenced by jsgraph().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/js-type-hint-lowering.h
/mnt/V8SourceCode/src/compiler/js-type-hint-lowering.cc