v8::base::RegionAllocator::Region Class Reference
Public Member Functions
Region (Address address, size_t size, RegionState state)
bool is_free () const
bool is_allocated () const
bool is_excluded () const
RegionState state ()
void set_state (RegionState state)
void Print (std::ostream &os) const
Private Attributes
RegionState state_
Additional Inherited Members
Detailed Description
Definition at line 150 of file region-allocator.h.
Constructor & Destructor Documentation
Region()
v8::base::RegionAllocator::Region::Region (Address address, size_t size, RegionState state) [inline]
Definition at line 152 of file region-allocator.h.
        : AddressRegion(address, size), state_(state) {}
Member Function Documentation
is_allocated()
bool v8::base::RegionAllocator::Region::is_allocated () const [inline]
Definition at line 156 of file region-allocator.h.
{ return state_ == RegionState::kAllocated; }
Referenced by v8::base::RegionAllocator::TrimRegion(), and v8::base::RegionAllocator::TryGrowRegion().
is_excluded()
bool v8::base::RegionAllocator::Region::is_excluded () const [inline]
Definition at line 157 of file region-allocator.h.
{ return state_ == RegionState::kExcluded; }
Referenced by v8::base::RegionAllocator::Split().
is_free()
bool v8::base::RegionAllocator::Region::is_free () const [inline]
Definition at line 155 of file region-allocator.h.
{ return state_ == RegionState::kFree; }
Referenced by v8::base::RegionAllocator::AllocateRegionAt(), v8::base::RegionAllocator::CheckRegion(), v8::base::RegionAllocator::FreeListRemoveRegion(), and v8::base::RegionAllocator::IsFree().
Print()
void v8::base::RegionAllocator::Region::Print (std::ostream & os) const
Definition at line 415 of file region-allocator.cc.
                                                      {
  std::ios::fmtflags flags = os.flags(std::ios::hex | std::ios::showbase);
  os << "[" << begin() << ", " << end() << "), size: " << size();
  os << ", " << RegionStateToString(state_);
  os.flags(flags);
}
References v8::base::AddressRegion::begin(), v8::base::AddressRegion::end(), flags(), v8::base::anonymous_namespace{region-allocator.cc}::RegionStateToString(), v8::base::AddressRegion::size(), and state_.
set_state()
void v8::base::RegionAllocator::Region::set_state (RegionState state) [inline]
Definition at line 160 of file region-allocator.h.
{ state_ = state; }
Referenced by v8::base::RegionAllocator::AllocateAlignedRegion(), v8::base::RegionAllocator::AllocateRegion(), v8::base::RegionAllocator::AllocateRegionAt(), and v8::base::RegionAllocator::TrimRegion().
state()
RegionState v8::base::RegionAllocator::Region::state () [inline]
Definition at line 159 of file region-allocator.h.
{ return state_; }
Referenced by v8::base::RegionAllocator::Split().
Member Data Documentation
state_
RegionState v8::base::RegionAllocator::Region::state_ [private]
Definition at line 165 of file region-allocator.h.
Referenced by Print().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/region-allocator.h
/mnt/V8SourceCode/src/base/region-allocator.cc