v8::internal::BuilderProducedPreparseData Class Reference
Public Member Functions
BuilderProducedPreparseData (PreparseDataBuilder *builder)
Handle< PreparseData > Serialize (Isolate *isolate) final
Handle< PreparseData > Serialize (LocalIsolate *isolate) final
ZonePreparseData * Serialize (Zone *zone) final
Private Attributes
PreparseDataBuilder * builder_
Additional Inherited Members
Detailed Description
Definition at line 498 of file preparse-data.cc.
Constructor & Destructor Documentation
BuilderProducedPreparseData()
v8::internal::BuilderProducedPreparseData::BuilderProducedPreparseData (PreparseDataBuilder * builder) [inline], [explicit]
Definition at line 500 of file preparse-data.cc.
      : builder_(builder) {
    DCHECK(builder->HasData());
  }
References v8::internal::DCHECK(), and v8::internal::PreparseDataBuilder::HasData().
Member Function Documentation
Serialize() [1/3]
Handle<PreparseData> v8::internal::BuilderProducedPreparseData::Serialize (Isolate * isolate) [inline], [final], [virtual]
Implements v8::internal::ProducedPreparseData.
Definition at line 505 of file preparse-data.cc.
                                                         {
    return builder_->Serialize(isolate);
  }
Serialize() [2/3]
Handle<PreparseData> v8::internal::BuilderProducedPreparseData::Serialize (LocalIsolate * isolate) [inline], [final], [virtual]
Implements v8::internal::ProducedPreparseData.
Definition at line 509 of file preparse-data.cc.
                                                              {
    return builder_->Serialize(isolate);
  }
Serialize() [3/3]
ZonePreparseData* v8::internal::BuilderProducedPreparseData::Serialize (Zone * zone) [inline], [final], [virtual]
Implements v8::internal::ProducedPreparseData.
Definition at line 513 of file preparse-data.cc.
                                                {
    return builder_->Serialize(zone);
  }
References v8::internal::ZonePreparseData::Serialize().
Member Data Documentation
builder_
PreparseDataBuilder* v8::internal::BuilderProducedPreparseData::builder_ [private]
Definition at line 518 of file preparse-data.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/preparse-data.cc