v8::internal::CompilationCacheTable Class Reference
#include <compilation-cache-table.h>
Public Member Functions
DirectHandle< Object > LookupRegExp (DirectHandle< String > source, JSRegExp::Flags flags)
void Remove (Tagged< Object > value)
void RemoveEntry (InternalIndex entry)
Tagged< Object > PrimaryValueAt (InternalIndex entry)
void SetPrimaryValueAt (InternalIndex entry, Tagged< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< Object > EvalJSFunctionsValueAt (InternalIndex entry)
void SetEvalJSFunctionsValueAt (InternalIndex entry, Tagged< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Static Public Member Functions
static CompilationCacheScriptLookupResult LookupScript (DirectHandle< CompilationCacheTable > table, Handle< String > src, const ScriptDetails &script_details, Isolate *isolate)
static DirectHandle< CompilationCacheTable > PutScript (Handle< CompilationCacheTable > cache, Handle< String > src, MaybeHandle< FixedArray > maybe_wrapped_arguments, DirectHandle< SharedFunctionInfo > value, Isolate *isolate)
static InfoCellPair LookupEval (DirectHandle< CompilationCacheTable > table, DirectHandle< String > src, DirectHandle< SharedFunctionInfo > shared, DirectHandle< NativeContext > native_context, LanguageMode language_mode, int position)
static void UpdateEval (DirectHandle< CompilationCacheTable > table, DirectHandle< String > src, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< JSFunction > js_function, LanguageMode language_mode, int position)
static DirectHandle< CompilationCacheTable > PutEval (DirectHandle< CompilationCacheTable > cache, DirectHandle< String > src, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< JSFunction > js_function, int position)
static DirectHandle< CompilationCacheTable > PutRegExp (Isolate *isolate, DirectHandle< CompilationCacheTable > cache, DirectHandle< String > src, JSRegExp::Flags flags, DirectHandle< RegExpData > value)
Static Public Attributes
static constexpr int kHashGenerations = 10
Static Private Member Functions
static Handle< CompilationCacheTable > EnsureScriptTableCapacity (Isolate *isolate, Handle< CompilationCacheTable > cache)
Detailed Description
Definition at line 113 of file compilation-cache-table.h.
Member Function Documentation
EnsureScriptTableCapacity()
Handle< CompilationCacheTable > v8::internal::CompilationCacheTable::EnsureScriptTableCapacity (Isolate * isolate, Handle< CompilationCacheTable > cache) [static], [private]
Definition at line 451 of file compilation-cache-table.cc.
                                                           {
  if (cache->HasSufficientCapacityToAdd(1)) return cache;
  // Before resizing, delete are any entries whose keys contain cleared weak
  // pointers.
  {
    DisallowGarbageCollection no_gc;
    for (InternalIndex entry : cache->IterateEntries()) {
      Tagged<Object> key;
      if (!cache->ToKey(isolate, entry, &key)) continue;
      if (Cast<WeakFixedArray>(key)
              ->get(ScriptCacheKey::kWeakScript)
              .IsCleared()) {
        DCHECK(IsUndefined(cache->PrimaryValueAt(entry)));
        cache->RemoveEntry(entry);
      }
    }
  }
  return EnsureCapacity(isolate, cache);
}
References v8::internal::DCHECK(), v8::internal::key, v8::internal::ScriptCacheKey::kWeakScript, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by PutScript().
EvalJSFunctionsValueAt()
Tagged< Object > v8::internal::CompilationCacheTable::EvalJSFunctionsValueAt (InternalIndex entry) [inline]
Definition at line 34 of file compilation-cache-table-inl.h.
                         {
  static_assert(CompilationCacheShape::kEntrySize == 3);
  return get(EntryToIndex(entry) + 2);
}
References v8::internal::CompilationCacheShape::kEntrySize.
LookupEval()
InfoCellPair v8::internal::CompilationCacheTable::LookupEval (DirectHandle< CompilationCacheTable > table, DirectHandle< String > src, DirectHandle< SharedFunctionInfo > shared, DirectHandle< NativeContext > native_context, LanguageMode language_mode, int position) [static]
Definition at line 418 of file compilation-cache-table.cc.
                  {
  InfoCellPair empty_result;
  Isolate* isolate = Isolate::Current();
  src = String::Flatten(isolate, src);
  EvalCacheKey key(src, outer_info, language_mode, position);
  InternalIndex entry = table->FindEntry(isolate, &key);
  if (entry.is_not_found()) return empty_result;
  if (!IsFixedArray(table->KeyAt(entry))) return empty_result;
  Tagged<Object> obj = table->PrimaryValueAt(entry);
  if (!IsSharedFunctionInfo(obj)) return empty_result;
  static_assert(CompilationCacheShape::kEntrySize == 3);
  Tagged<JSFunction> js_function =
      SearchLiteralsMap(*table, entry, *native_context);
  return InfoCellPair(isolate, Cast<SharedFunctionInfo>(obj), js_function);
}
References v8::internal::Isolate::Current(), v8::internal::InternalIndex::is_not_found(), v8::internal::CompilationCacheShape::kEntrySize, v8::internal::key, v8::internal::native_context, and v8::internal::anonymous_namespace{compilation-cache-table.cc}::SearchLiteralsMap().
Referenced by v8::internal::CompilationCacheEval::Lookup().
LookupRegExp()
DirectHandle< Object > v8::internal::CompilationCacheTable::LookupRegExp (DirectHandle< String > source, JSRegExp::Flags flags)
Definition at line 441 of file compilation-cache-table.cc.
                                                   {
  Isolate* isolate = Isolate::Current();
  DisallowGarbageCollection no_gc;
  RegExpKey key(isolate, src, flags);
  InternalIndex entry = FindEntry(isolate, &key);
  if (entry.is_not_found()) return isolate->factory()->undefined_value();
  return DirectHandle<Object>(PrimaryValueAt(entry), isolate);
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::flags, v8::internal::InternalIndex::is_not_found(), v8::internal::key, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and PrimaryValueAt().
LookupScript()
CompilationCacheScriptLookupResult v8::internal::CompilationCacheTable::LookupScript (DirectHandle< CompilationCacheTable > table, Handle< String > src, const ScriptDetails & script_details, Isolate * isolate) [static]
Definition at line 393 of file compilation-cache-table.cc.
                                                           {
  src = String::Flatten(isolate, src);
  ScriptCacheKey key(src, &script_details, isolate);
  InternalIndex entry = table->FindEntry(isolate, &key);
  if (entry.is_not_found()) return {};
  DisallowGarbageCollection no_gc;
  Tagged<Object> key_in_table = table->KeyAt(entry);
  Tagged<Script> script = Cast<Script>(Cast<WeakFixedArray>(key_in_table)
                                           ->get(ScriptCacheKey::kWeakScript)
                                           .GetHeapObjectAssumeWeak());
  Tagged<Object> obj = table->PrimaryValueAt(entry);
  Tagged<SharedFunctionInfo> toplevel_sfi;
  if (!IsUndefined(obj, isolate)) {
    toplevel_sfi = Cast<SharedFunctionInfo>(obj);
    DCHECK_EQ(toplevel_sfi->script(), script);
  }
  return CompilationCacheScriptLookupResult::FromRawObjects(
      std::make_pair(script, toplevel_sfi), isolate);
}
References DCHECK_EQ, v8::internal::CompilationCacheScriptLookupResult::FromRawObjects(), v8::internal::InternalIndex::is_not_found(), v8::internal::key, v8::internal::ScriptCacheKey::kWeakScript, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::script.
Referenced by v8::internal::CompilationCacheScript::Lookup().
PrimaryValueAt()
Tagged< Object > v8::internal::CompilationCacheTable::PrimaryValueAt (InternalIndex entry) [inline]
Definition at line 24 of file compilation-cache-table-inl.h.
                                                                        {
  return get(EntryToIndex(entry) + 1);
}
Referenced by LookupRegExp(), and Remove().
PutEval()
DirectHandle< CompilationCacheTable > v8::internal::CompilationCacheTable::PutEval (DirectHandle< CompilationCacheTable > cache, DirectHandle< String > src, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< JSFunction > js_function, int position) [static]
Definition at line 536 of file compilation-cache-table.cc.
                                                        {
  Isolate* isolate = Isolate::Current();
  src = String::Flatten(isolate, src);
  EvalCacheKey key(src, outer_info, js_function->shared()->language_mode(),
                   position);
  // Create a dummy entry to mark that this key has already been inserted once.
  cache = EnsureCapacity(isolate, cache);
  InternalIndex entry = cache->FindInsertionEntry(isolate, key.Hash());
  DirectHandle<Object> k = key.AsHandle(isolate);
  cache->SetKeyAt(entry, *k);
  cache->SetPrimaryValueAt(entry, js_function->shared());
  cache->SetEvalJSFunctionsValueAt(entry,
                                   ReadOnlyRoots(isolate).the_hole_value());
  // AddToFeedbackCellsMap may allocate a new sub-array to live in the
  // entry, but it won't change the cache array. Therefore EntryToIndex
  // and entry remains correct.
  AddToJSFunctionMap(cache, entry, js_function);
  cache->ElementAdded();
  return cache;
}
References v8::internal::anonymous_namespace{compilation-cache-table.cc}::AddToJSFunctionMap(), v8::internal::Isolate::Current(), and v8::internal::key.
Referenced by v8::internal::CompilationCacheEval::Put().
PutRegExp()
DirectHandle< CompilationCacheTable > v8::internal::CompilationCacheTable::PutRegExp (Isolate * isolate, DirectHandle< CompilationCacheTable > cache, DirectHandle< String > src, JSRegExp::Flags flags, DirectHandle< RegExpData > value) [static]
Definition at line 561 of file compilation-cache-table.cc.
                                    {
  RegExpKey key(isolate, src, flags);
  cache = EnsureCapacity(isolate, cache);
  InternalIndex entry = cache->FindInsertionEntry(isolate, key.Hash());
  // We store the value in the key slot, and compare the search key
  // to the stored value with a custom IsMatch function during lookups.
  cache->SetKeyAt(entry, value->wrapper());
  cache->SetPrimaryValueAt(entry, value->wrapper());
  cache->ElementAdded();
  return cache;
}
References v8::internal::flags, v8::internal::key, and v8::internal::value.
Referenced by v8::internal::CompilationCacheRegExp::Put().
PutScript()
DirectHandle< CompilationCacheTable > v8::internal::CompilationCacheTable::PutScript (Handle< CompilationCacheTable > cache, Handle< String > src, MaybeHandle< FixedArray > maybe_wrapped_arguments, DirectHandle< SharedFunctionInfo > value, Isolate * isolate) [static]
Definition at line 474 of file compilation-cache-table.cc.
                                                              {
  src = String::Flatten(isolate, src);
  DirectHandle<Script> script(Cast<Script>(value->script()), isolate);
  MaybeHandle<Object> script_name;
  if (IsString(script->name(), isolate)) {
    script_name = handle(script->name(), isolate);
  }
  Handle<FixedArray> host_defined_options(script->host_defined_options(),
                                          isolate);
  ScriptCacheKey key(src, script_name, script->line_offset(),
                     script->column_offset(), script->origin_options(),
                     host_defined_options, maybe_wrapped_arguments, isolate);
  DirectHandle<Object> k = key.AsHandle(isolate, value);
  // Check whether there is already a matching entry. If so, we must overwrite
  // it. This allows an entry whose value is undefined to upgrade to contain a
  // SharedFunctionInfo.
  InternalIndex entry = cache->FindEntry(isolate, &key);
  bool found_existing = entry.is_found();
  if (!found_existing) {
    cache = EnsureScriptTableCapacity(isolate, cache);
    entry = cache->FindInsertionEntry(isolate, key.Hash());
  }
  // We might be tempted to DCHECK here that the Script in the existing entry
  // matches the Script in the new key. However, replacing an existing Script
  // can still happen in some edge cases that aren't common enough to be worth
  // fixing. Consider the following unlikely sequence of events:
  // 1. BackgroundMergeTask::SetUpOnMainThread finds a script S1 in the cache.
  // 2. DevTools is attached and clears the cache.
  // 3. DevTools is detached; the cache is re-enabled.
  // 4. A new instance of the script, S2, is compiled and placed into the cache.
  // 5. The merge from step 1 finishes on the main thread, still using S1, and
  // places S1 into the cache, replacing S2.
  cache->SetKeyAt(entry, *k);
  cache->SetPrimaryValueAt(entry, *value);
  if (!found_existing) {
    cache->ElementAdded();
  }
  return cache;
}
References EnsureScriptTableCapacity(), v8::internal::handle(), v8::internal::InternalIndex::is_found(), v8::internal::key, v8::internal::script, and v8::internal::value.
Referenced by v8::internal::CompilationCacheScript::Put().
Remove()
void v8::internal::CompilationCacheTable::Remove (Tagged< Object > value)
Definition at line 576 of file compilation-cache-table.cc.
                                                       {
  DisallowGarbageCollection no_gc;
  for (InternalIndex entry : IterateEntries()) {
    if (PrimaryValueAt(entry) == value) {
      RemoveEntry(entry);
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, PrimaryValueAt(), RemoveEntry(), and v8::internal::value.
RemoveEntry()
void v8::internal::CompilationCacheTable::RemoveEntry (InternalIndex entry)
Definition at line 585 of file compilation-cache-table.cc.
                                                           {
  int entry_index = EntryToIndex(entry);
  Tagged<Object> the_hole_value = GetReadOnlyRoots().the_hole_value();
  for (int i = 0; i < kEntrySize; i++) {
    this->set(entry_index + i, the_hole_value, SKIP_WRITE_BARRIER);
  }
  ElementRemoved();
  // This table does not shrink upon deletion. The script cache depends on that
  // fact, because EnsureScriptTableCapacity calls RemoveEntry at a time when
  // shrinking the table would be counterproductive.
}
References v8::internal::GetReadOnlyRoots(), cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by Remove().
SetEvalJSFunctionsValueAt()
void v8::internal::CompilationCacheTable::SetEvalJSFunctionsValueAt (InternalIndex entry, Tagged< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 40 of file compilation-cache-table-inl.h.
                                                                             {
  set(EntryToIndex(entry) + 2, value, mode);
}
References mode(), and v8::internal::value.
SetPrimaryValueAt()
void v8::internal::CompilationCacheTable::SetPrimaryValueAt (InternalIndex entry, Tagged< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 28 of file compilation-cache-table-inl.h.
                                                                     {
  set(EntryToIndex(entry) + 1, value, mode);
}
References mode(), and v8::internal::value.
UpdateEval()
void v8::internal::CompilationCacheTable::UpdateEval (DirectHandle< CompilationCacheTable > table, DirectHandle< String > src, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< JSFunction > js_function, LanguageMode language_mode, int position) [static]
Definition at line 518 of file compilation-cache-table.cc.
                  {
  Isolate* isolate = Isolate::Current();
  src = String::Flatten(isolate, src);
  EvalCacheKey key(src, outer_info, language_mode, position);
  InternalIndex entry = table->FindEntry(isolate, &key);
  if (entry.is_not_found()) return;
  if (!IsFixedArray(table->KeyAt(entry))) return;
  Tagged<Object> obj = table->PrimaryValueAt(entry);
  if (!IsSharedFunctionInfo(obj)) return;
  AddToJSFunctionMap(table, entry, js_function);
}
References v8::internal::anonymous_namespace{compilation-cache-table.cc}::AddToJSFunctionMap(), v8::internal::Isolate::Current(), v8::internal::InternalIndex::is_not_found(), and v8::internal::key.
Referenced by v8::internal::CompilationCacheEval::UpdateEval().
Member Data Documentation
kHashGenerations
constexpr int v8::internal::CompilationCacheTable::kHashGenerations = 10 [static], [constexpr]
Definition at line 175 of file compilation-cache-table.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/compilation-cache-table.h
/mnt/V8SourceCode/src/objects/compilation-cache-table-inl.h
/mnt/V8SourceCode/src/objects/compilation-cache-table.cc