v8::internal::wasm::DisjointAllocationPool Class Reference
#include <wasm-code-manager.h>
Public Member Functions
MOVE_ONLY_WITH_DEFAULT_CONSTRUCTORS (DisjointAllocationPool)
DisjointAllocationPool (base::AddressRegion region)
base::AddressRegion Merge (base::AddressRegion)
base::AddressRegion Allocate (size_t size)
base::AddressRegion AllocateInRegion (size_t size, base::AddressRegion)
bool IsEmpty () const
const auto & regions () const
Private Attributes
std::set< base::AddressRegion, base::AddressRegion::StartAddressLess > regions_
Detailed Description
Definition at line 61 of file wasm-code-manager.h.
Constructor & Destructor Documentation
DisjointAllocationPool()
v8::internal::wasm::DisjointAllocationPool::DisjointAllocationPool (base::AddressRegion region) [inline], [explicit]
Definition at line 64 of file wasm-code-manager.h.
      : regions_({region}) {}
Member Function Documentation
Allocate()
base::AddressRegion v8::internal::wasm::DisjointAllocationPool::Allocate (size_t size)
Definition at line 137 of file wasm-code-manager.cc.
                                                              {
  return AllocateInRegion(size,
                          {kNullAddress, std::numeric_limits<size_t>::max()});
}
References AllocateInRegion(), v8::internal::kNullAddress, and size().
Referenced by v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion().
AllocateInRegion()
base::AddressRegion v8::internal::wasm::DisjointAllocationPool::AllocateInRegion (size_t size, base::AddressRegion region)
Definition at line 142 of file wasm-code-manager.cc.
                                           {
  // Get an iterator to the first contained region whose start address is not
  // smaller than the start address of {region}. Start the search from the
  // region one before that (the last one whose start address is smaller).
  auto it = regions_.lower_bound(region);
  if (it != regions_.begin()) --it;
  for (auto end = regions_.end(); it != end; ++it) {
    base::AddressRegion overlap = it->GetOverlap(region);
    if (size > overlap.size()) continue;
    base::AddressRegion ret{overlap.begin(), size};
    base::AddressRegion old = *it;
    auto insert_pos = regions_.erase(it);
    if (size == old.size()) {
      // We use the full region --> nothing to add back.
    } else if (ret.begin() == old.begin()) {
      // We return a region at the start --> shrink old region from front.
      regions_.insert(insert_pos, {old.begin() + size, old.size() - size});
    } else if (ret.end() == old.end()) {
      // We return a region at the end --> shrink remaining region.
      regions_.insert(insert_pos, {old.begin(), old.size() - size});
    } else {
      // We return something in the middle --> split the remaining region
      // (insert the region with smaller address first).
      regions_.insert(insert_pos, {old.begin(), ret.begin() - old.begin()});
      regions_.insert(insert_pos, {ret.end(), old.end() - ret.end()});
    }
    return ret;
  }
  return {};
}
References v8::base::AddressRegion::begin(), v8::base::AddressRegion::end(), v8::internal::compiler::end(), v8::base::AddressRegion::GetOverlap(), regions_, v8::base::AddressRegion::size(), and size().
Referenced by Allocate(), and v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion().
IsEmpty()
bool v8::internal::wasm::DisjointAllocationPool::IsEmpty () const [inline]
Definition at line 80 of file wasm-code-manager.h.
{ return regions_.empty(); }
Referenced by v8::internal::wasm::WasmCodeAllocator::Init().
Merge()
base::AddressRegion v8::internal::wasm::DisjointAllocationPool::Merge (base::AddressRegion new_region)
Definition at line 82 of file wasm-code-manager.cc.
                                  {
  // Find the possible insertion position by identifying the first region whose
  // start address is not less than that of {new_region}. Since there cannot be
  // any overlap between regions, this also means that the start of {above} is
  // bigger or equal than the *end* of {new_region}.
  auto above = regions_.lower_bound(new_region);
  DCHECK(above == regions_.end() || above->begin() >= new_region.end());
  // Check whether to merge with {above}.
  if (above != regions_.end() && new_region.end() == above->begin()) {
    base::AddressRegion merged_region{new_region.begin(),
                                      new_region.size() + above->size()};
    DCHECK_EQ(merged_region.end(), above->end());
    // Check whether to also merge with the region below.
    if (above != regions_.begin()) {
      auto below = above;
      --below;
      if (below->end() == new_region.begin()) {
        merged_region = {below->begin(), below->size() + merged_region.size()};
        regions_.erase(below);
      }
    }
    auto insert_pos = regions_.erase(above);
    regions_.insert(insert_pos, merged_region);
    return merged_region;
  }
  // No element below, and not adjavent to {above}: insert and done.
  if (above == regions_.begin()) {
    regions_.insert(above, new_region);
    return new_region;
  }
  auto below = above;
  --below;
  // Consistency check:
  DCHECK(above == regions_.end() || below->end() < above->begin());
  // Adjacent to {below}: merge and done.
  if (below->end() == new_region.begin()) {
    base::AddressRegion merged_region{below->begin(),
                                      below->size() + new_region.size()};
    DCHECK_EQ(merged_region.end(), new_region.end());
    regions_.erase(below);
    regions_.insert(above, merged_region);
    return merged_region;
  }
  // Not adjacent to any existing region: insert between {below} and {above}.
  DCHECK_LT(below->end(), new_region.begin());
  regions_.insert(above, new_region);
  return new_region;
}
References v8::internal::above, v8::base::AddressRegion::begin(), v8::internal::below, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, v8::base::AddressRegion::end(), regions_, and v8::base::AddressRegion::size().
Referenced by v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), v8::internal::wasm::WasmCodeAllocator::FreeCode(), and v8::internal::wasm::WasmCodeAllocator::Init().
MOVE_ONLY_WITH_DEFAULT_CONSTRUCTORS()
v8::internal::wasm::DisjointAllocationPool::MOVE_ONLY_WITH_DEFAULT_CONSTRUCTORS (DisjointAllocationPool)
regions()
const auto& v8::internal::wasm::DisjointAllocationPool::regions () const [inline]
Definition at line 82 of file wasm-code-manager.h.
{ return regions_; }
Referenced by v8::internal::wasm::WasmCodeAllocator::FreeCode().
Member Data Documentation
regions_
std::set<base::AddressRegion, base::AddressRegion::StartAddressLess> v8::internal::wasm::DisjointAllocationPool::regions_ [private]
Definition at line 85 of file wasm-code-manager.h.
Referenced by AllocateInRegion(), and Merge().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-code-manager.h
/mnt/V8SourceCode/src/wasm/wasm-code-manager.cc