v8::internal::AccountingAllocator Class Reference
#include <accounting-allocator.h>
Public Member Functions
AccountingAllocator ()
AccountingAllocator (Isolate *isolate)
AccountingAllocator (const AccountingAllocator &)=delete
AccountingAllocator & operator= (const AccountingAllocator &)=delete
virtual ~AccountingAllocator ()
Segment * AllocateSegment (size_t bytes)
void ReturnSegment (Segment *memory)
size_t GetCurrentMemoryUsage () const
size_t GetMaxMemoryUsage () const
void TraceZoneCreation (const Zone *zone)
void TraceZoneDestruction (const Zone *zone)
void TraceAllocateSegment (Segment *segment)
Protected Member Functions
virtual void TraceZoneCreationImpl (const Zone *zone)
virtual void TraceZoneDestructionImpl (const Zone *zone)
virtual void TraceAllocateSegmentImpl (Segment *segment)
Isolate * isolate () const
Private Attributes
Isolate *const isolate_ = nullptr
std::atomic< size_t > current_memory_usage_ {0}
std::atomic< size_t > max_memory_usage_ {0}
Detailed Description
Definition at line 28 of file accounting-allocator.h.
Constructor & Destructor Documentation
AccountingAllocator() [1/3]
v8::internal::AccountingAllocator::AccountingAllocator ()
Definition at line 88 of file accounting-allocator.cc.
: AccountingAllocator(nullptr) {}
AccountingAllocator() [2/3]
v8::internal::AccountingAllocator::AccountingAllocator (Isolate * isolate) [explicit]
Definition at line 90 of file accounting-allocator.cc.
    : isolate_(isolate) {}
AccountingAllocator() [3/3]
v8::internal::AccountingAllocator::AccountingAllocator (const AccountingAllocator &) [delete]
 AccountingAllocator()
v8::internal::AccountingAllocator::~AccountingAllocator () [virtual], [default]
Member Function Documentation
AllocateSegment()
Segment * v8::internal::AccountingAllocator::AllocateSegment (size_t bytes)
Definition at line 95 of file accounting-allocator.cc.
                                                                    {
  base::AllocationResult<void*> memory;
  if (v8_flags.managed_zone_memory && isolate_) {
    memory = ManagedZones::AllocateSegment(isolate_, requested_bytes);
  } else {
    memory = AllocAtLeastWithRetry(requested_bytes);
  }
  if (V8_UNLIKELY(memory.ptr == nullptr)) {
    return nullptr;
  }
  size_t current =
      current_memory_usage_.fetch_add(memory.count, std::memory_order_relaxed) +
      memory.count;
  size_t max = max_memory_usage_.load(std::memory_order_relaxed);
  while (current > max && !max_memory_usage_.compare_exchange_weak(
                              max, current, std::memory_order_relaxed)) {
    // {max} was updated by {compare_exchange_weak}; retry.
  }
  DCHECK_LE(sizeof(Segment), memory.count);
  return new (memory.ptr) Segment(memory.count);
}
References v8::internal::AllocAtLeastWithRetry(), v8::base::AllocationResult< Pointer >::count, current_memory_usage_, DCHECK_LE, isolate_, max_memory_usage_, v8::base::AllocationResult< Pointer >::ptr, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::Zone::Expand().
GetCurrentMemoryUsage()
size_t v8::internal::AccountingAllocator::GetCurrentMemoryUsage () const [inline]
Definition at line 43 of file accounting-allocator.h.
                                       {
    return current_memory_usage_.load(std::memory_order_relaxed);
  }
Referenced by v8::internal::wasm::TypeCanonicalizer::EstimateCurrentMemoryConsumption(), v8::Isolate::GetHeapStatistics(), and v8::internal::Heap::RecordStats().
GetMaxMemoryUsage()
size_t v8::internal::AccountingAllocator::GetMaxMemoryUsage () const [inline]
Definition at line 47 of file accounting-allocator.h.
                                   {
    return max_memory_usage_.load(std::memory_order_relaxed);
  }
Referenced by v8::Isolate::GetHeapStatistics(), and v8::internal::Heap::RecordStats().
isolate()
Isolate* v8::internal::AccountingAllocator::isolate () const [inline], [protected]
Definition at line 71 of file accounting-allocator.h.
{ return isolate_; }
operator=()
AccountingAllocator& v8::internal::AccountingAllocator::operator= (const AccountingAllocator &) [delete]
ReturnSegment()
void v8::internal::AccountingAllocator::ReturnSegment (Segment * memory)
Definition at line 118 of file accounting-allocator.cc.
                                                        {
  segment->ZapContents();
  size_t segment_size = segment->total_size();
  current_memory_usage_.fetch_sub(segment_size, std::memory_order_relaxed);
  segment->ZapHeader();
  if (isolate_ && v8_flags.managed_zone_memory) {
    ManagedZones::ReturnSegment(isolate_, segment, segment_size);
  } else {
    free(segment);
  }
}
References current_memory_usage_, isolate_, v8::internal::Segment::total_size(), v8::internal::v8_flags, v8::internal::Segment::ZapContents(), and v8::internal::Segment::ZapHeader().
Referenced by v8::internal::Zone::ReleaseSegment().
TraceAllocateSegment()
void v8::internal::AccountingAllocator::TraceAllocateSegment (Segment * segment) [inline]
Definition at line 61 of file accounting-allocator.h.
                                              {
    if (V8_LIKELY(!TracingFlags::is_zone_stats_enabled())) return;
    TraceAllocateSegmentImpl(segment);
  }
References v8::internal::TracingFlags::is_zone_stats_enabled(), and V8_LIKELY.
Referenced by v8::internal::Zone::Expand().
TraceAllocateSegmentImpl()
virtual void v8::internal::AccountingAllocator::TraceAllocateSegmentImpl (Segment * segment) [inline], [protected], [virtual]
Reimplemented in v8::internal::TracingAccountingAllocator.
Definition at line 69 of file accounting-allocator.h.
{}
TraceZoneCreation()
void v8::internal::AccountingAllocator::TraceZoneCreation (const Zone * zone) [inline]
Definition at line 51 of file accounting-allocator.h.
                                           {
    if (V8_LIKELY(!TracingFlags::is_zone_stats_enabled())) return;
    TraceZoneCreationImpl(zone);
  }
References v8::internal::TracingFlags::is_zone_stats_enabled(), and V8_LIKELY.
Referenced by v8::internal::Zone::Reset(), and v8::internal::Zone::Zone().
TraceZoneCreationImpl()
virtual void v8::internal::AccountingAllocator::TraceZoneCreationImpl (const Zone * zone) [inline], [protected], [virtual]
Reimplemented in v8::internal::TracingAccountingAllocator.
Definition at line 67 of file accounting-allocator.h.
{}
TraceZoneDestruction()
void v8::internal::AccountingAllocator::TraceZoneDestruction (const Zone * zone) [inline]
Definition at line 56 of file accounting-allocator.h.
                                              {
    if (V8_LIKELY(!TracingFlags::is_zone_stats_enabled())) return;
    TraceZoneDestructionImpl(zone);
  }
References v8::internal::TracingFlags::is_zone_stats_enabled(), and V8_LIKELY.
Referenced by v8::internal::Zone::DeleteAll().
TraceZoneDestructionImpl()
virtual void v8::internal::AccountingAllocator::TraceZoneDestructionImpl (const Zone * zone) [inline], [protected], [virtual]
Reimplemented in v8::internal::TracingAccountingAllocator.
Definition at line 68 of file accounting-allocator.h.
{}
Member Data Documentation
current_memory_usage_
std::atomic<size_t> v8::internal::AccountingAllocator::current_memory_usage_ {0} [private]
Definition at line 75 of file accounting-allocator.h.
Referenced by AllocateSegment(), and ReturnSegment().
isolate_
Isolate* const v8::internal::AccountingAllocator::isolate_ = nullptr [private]
Definition at line 74 of file accounting-allocator.h.
Referenced by AllocateSegment(), and ReturnSegment().
max_memory_usage_
std::atomic<size_t> v8::internal::AccountingAllocator::max_memory_usage_ {0} [private]
Definition at line 76 of file accounting-allocator.h.
Referenced by AllocateSegment().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/zone/accounting-allocator.h
/mnt/V8SourceCode/src/zone/accounting-allocator.cc