v8::internal::CrossHeapRememberedSet Class Reference
#include <cross-heap-remembered-set.h>
Public Member Functions
CrossHeapRememberedSet (cppgc::internal::HeapBase &heap_base)
CrossHeapRememberedSet (const CrossHeapRememberedSet &)=delete
CrossHeapRememberedSet (CrossHeapRememberedSet &&)=delete
void RememberReferenceIfNeeded (Isolate &isolate, Tagged< CppHeapPointerWrapperObjectT > host_obj, void *cppgc_object)
void Reset (Isolate &isolate)
template<typename F >
void Visit (Isolate &, F)
bool IsEmpty () const
Private Attributes
cppgc::internal::HeapBase & heap_base_
std::vector< IndirectHandle< CppHeapPointerWrapperObjectT > > remembered_v8_to_cppgc_references_
Detailed Description
Definition at line 22 of file cross-heap-remembered-set.h.
Constructor & Destructor Documentation
CrossHeapRememberedSet() [1/3]
v8::internal::CrossHeapRememberedSet::CrossHeapRememberedSet (cppgc::internal::HeapBase & heap_base) [inline], [explicit]
Definition at line 24 of file cross-heap-remembered-set.h.
      : heap_base_(heap_base) {}
CrossHeapRememberedSet() [2/3]
v8::internal::CrossHeapRememberedSet::CrossHeapRememberedSet (const CrossHeapRememberedSet &) [delete]
CrossHeapRememberedSet() [3/3]
v8::internal::CrossHeapRememberedSet::CrossHeapRememberedSet (CrossHeapRememberedSet &&) [delete]
Member Function Documentation
IsEmpty()
bool v8::internal::CrossHeapRememberedSet::IsEmpty () const [inline]
Definition at line 38 of file cross-heap-remembered-set.h.
{ return remembered_v8_to_cppgc_references_.empty(); }
Referenced by v8::internal::CppHeap::ResetCrossHeapRememberedSet().
RememberReferenceIfNeeded()
void v8::internal::CrossHeapRememberedSet::RememberReferenceIfNeeded (Isolate & isolate, Tagged< CppHeapPointerWrapperObjectT > host_obj, void * cppgc_object)
Definition at line 13 of file cross-heap-remembered-set.cc.
                        {
  DCHECK_NOT_NULL(cppgc_object);
  // Any in-cage pointer must point to a vaild, not freed cppgc object.
  auto* page =
      cppgc::internal::BasePage::FromInnerAddress(&heap_base_, cppgc_object);
  // TODO(v8:13475): Better filter with on-cage check.
  if (!page) return;
  auto& value_hoh = page->ObjectHeaderFromInnerAddress(cppgc_object);
  if (!value_hoh.IsYoung()) return;
  remembered_v8_to_cppgc_references_.push_back(
      isolate.global_handles()->Create(host_obj));
}
References v8::internal::GlobalHandles::Create(), DCHECK_NOT_NULL, cppgc::internal::BasePage::FromInnerAddress(), v8::internal::Isolate::global_handles(), heap_base_, and remembered_v8_to_cppgc_references_.
Referenced by v8::internal::CppHeap::RememberCrossHeapReferenceIfNeeded().
Reset()
void v8::internal::CrossHeapRememberedSet::Reset (Isolate & isolate)
Definition at line 28 of file cross-heap-remembered-set.cc.
                                                   {
  for (auto& h : remembered_v8_to_cppgc_references_) {
    isolate.global_handles()->Destroy(h.location());
  }
  remembered_v8_to_cppgc_references_.clear();
  remembered_v8_to_cppgc_references_.shrink_to_fit();
}
References v8::internal::GlobalHandles::Destroy(), v8::internal::Isolate::global_handles(), h(), and remembered_v8_to_cppgc_references_.
Referenced by v8::internal::CppHeap::ResetCrossHeapRememberedSet().
Visit()
template<typename F >
void v8::internal::CrossHeapRememberedSet::Visit (Isolate & isolate, F f)
Definition at line 49 of file cross-heap-remembered-set.h.
                                                        {
  for (auto& obj : remembered_v8_to_cppgc_references_) {
    f(*obj);
  }
}
References remembered_v8_to_cppgc_references_.
Referenced by v8::internal::CppHeap::VisitCrossHeapRememberedSetIfNeeded().
Member Data Documentation
heap_base_
cppgc::internal::HeapBase& v8::internal::CrossHeapRememberedSet::heap_base_ [private]
Definition at line 41 of file cross-heap-remembered-set.h.
Referenced by RememberReferenceIfNeeded().
remembered_v8_to_cppgc_references_
std::vector<IndirectHandle<CppHeapPointerWrapperObjectT> > v8::internal::CrossHeapRememberedSet::remembered_v8_to_cppgc_references_ [private]
Definition at line 45 of file cross-heap-remembered-set.h.
Referenced by RememberReferenceIfNeeded(), Reset(), and Visit().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc-js/cross-heap-remembered-set.h
/mnt/V8SourceCode/src/heap/cppgc-js/cross-heap-remembered-set.cc