v8::internal::FullHeapObjectSlot Class Reference
#include <slots.h>
Public Member Functions
FullHeapObjectSlot ()
FullHeapObjectSlot (Address ptr)
FullHeapObjectSlot (TaggedBase *ptr)
template<typename T >
FullHeapObjectSlot (SlotBase< T, TData, kSlotDataAlignment > slot)
Tagged< HeapObjectReference > operator* () const
Tagged< HeapObjectReference > load (PtrComprCageBase cage_base) const
void store (Tagged< HeapObjectReference > value) const
Tagged< HeapObject > ToHeapObject () const
void StoreHeapObject (Tagged< HeapObject > value) const
Additional Inherited Members
Detailed Description
Definition at line 198 of file slots.h.
Constructor & Destructor Documentation
FullHeapObjectSlot() [1/4]
v8::internal::FullHeapObjectSlot::FullHeapObjectSlot () [inline]
Definition at line 200 of file slots.h.
: SlotBase(kNullAddress) {}
FullHeapObjectSlot() [2/4]
v8::internal::FullHeapObjectSlot::FullHeapObjectSlot (Address ptr) [inline], [explicit]
Definition at line 201 of file slots.h.
: SlotBase(ptr) {}
FullHeapObjectSlot() [3/4]
v8::internal::FullHeapObjectSlot::FullHeapObjectSlot (TaggedBase * ptr) [inline], [explicit]
Definition at line 202 of file slots.h.
      : SlotBase(reinterpret_cast<Address>(ptr)) {}
FullHeapObjectSlot() [4/4]
template<typename T >
v8::internal::FullHeapObjectSlot::FullHeapObjectSlot (SlotBase< T, TData, kSlotDataAlignment > slot) [inline], [explicit]
Definition at line 210 of file slots.h.
      : SlotBase(slot.address()) {}
Member Function Documentation
load()
Tagged< HeapObjectReference > v8::internal::FullHeapObjectSlot::load (PtrComprCageBase cage_base) const [inline]
Definition at line 178 of file slots-inl.h.
                                      {
  return **this;
}
operator*()
Tagged< HeapObjectReference > v8::internal::FullHeapObjectSlot::operator* () const [inline]
Definition at line 174 of file slots-inl.h.
                                                                {
  return Cast<HeapObjectReference>(Tagged<MaybeObject>(*location()));
}
References v8::internal::SlotBase< FullHeapObjectSlot, Address >::location().
store()
void v8::internal::FullHeapObjectSlot::store (Tagged< HeapObjectReference > value) const [inline]
Definition at line 183 of file slots-inl.h.
                                                                      {
  *location() = value.ptr();
}
References v8::internal::SlotBase< FullHeapObjectSlot, Address >::location(), and v8::internal::value.
StoreHeapObject()
void v8::internal::FullHeapObjectSlot::StoreHeapObject (Tagged< HeapObject > value) const [inline]
Definition at line 193 of file slots-inl.h.
                                                                       {
  *location() = value.ptr();
}
References v8::internal::SlotBase< FullHeapObjectSlot, Address >::location(), and v8::internal::value.
Referenced by v8::internal::ScavengerCollector::ClearOldEphemerons().
ToHeapObject()
Tagged< HeapObject > v8::internal::FullHeapObjectSlot::ToHeapObject () const [inline]
Definition at line 187 of file slots-inl.h.
                                                          {
  TData value = *location();
  DCHECK(HAS_STRONG_HEAP_OBJECT_TAG(value));
  return Cast<HeapObject>(Tagged<Object>(value));
}
References v8::internal::DCHECK(), HAS_STRONG_HEAP_OBJECT_TAG, v8::internal::SlotBase< FullHeapObjectSlot, Address >::location(), and v8::internal::value.
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences(), and v8::internal::ScavengerCollector::ClearOldEphemerons().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/slots.h
/mnt/V8SourceCode/src/objects/slots-inl.h