v8::internal::GlobalHandles::NodeSpace< NodeType > Class Template Reference
Public Types
using BlockType = NodeBlock< NodeType >
using iterator = NodeIterator< BlockType >
Public Member Functions
NodeSpace (GlobalHandles *global_handles) V8_NOEXCEPT
~NodeSpace ()
NodeType * Allocate ()
iterator begin ()
iterator end ()
size_t TotalSize () const
size_t handles_count () const
Static Public Member Functions
static NodeSpace * From (NodeType *node)
static void Release (NodeType *node)
Private Member Functions
void PutNodesOnFreeList (BlockType *block)
void Free (NodeType *node)
Private Attributes
GlobalHandles *const global_handles_
BlockType * first_block_ = nullptr
BlockType * first_used_block_ = nullptr
NodeType * first_free_ = nullptr
size_t blocks_ = 0
size_t handles_count_ = 0
Detailed Description
template<class NodeType>
class v8::internal::GlobalHandles::NodeSpace< NodeType >
Definition at line 197 of file global-handles.cc.
Member Typedef Documentation
BlockType
template<class NodeType >
using v8::internal::GlobalHandles::NodeSpace< NodeType >::BlockType = NodeBlock<NodeType>
Definition at line 199 of file global-handles.cc.
iterator
template<class NodeType >
using v8::internal::GlobalHandles::NodeSpace< NodeType >::iterator = NodeIterator<BlockType>
Definition at line 200 of file global-handles.cc.
Constructor & Destructor Documentation
NodeSpace()
template<class NodeType >
v8::internal::GlobalHandles::NodeSpace< NodeType >::NodeSpace (GlobalHandles * global_handles) [inline], [explicit]
Definition at line 205 of file global-handles.cc.
      : global_handles_(global_handles) {}
 NodeSpace()
template<class NodeType >
v8::internal::GlobalHandles::NodeSpace< NodeType >::~NodeSpace ()
Definition at line 230 of file global-handles.cc.
                                             {
  auto* block = first_block_;
  while (block != nullptr) {
    auto* tmp = block->next();
    delete block;
    block = tmp;
  }
}
Member Function Documentation
Allocate()
template<class NodeType >
NodeType * v8::internal::GlobalHandles::NodeSpace< NodeType >::Allocate () [inline]
Definition at line 240 of file global-handles.cc.
                                                     {
  if (first_free_ == nullptr) {
    first_block_ = new BlockType(global_handles_, this, first_block_);
    blocks_++;
    PutNodesOnFreeList(first_block_);
  }
  DCHECK_NOT_NULL(first_free_);
  NodeType* node = first_free_;
  first_free_ = first_free_->next_free();
  BlockType* block = BlockType::From(node);
  if (block->IncreaseUsage()) {
    block->ListAdd(&first_used_block_);
  }
  global_handles_->isolate()->counters()->global_handles()->Increment();
  handles_count_++;
  node->CheckNodeIsFreeNode();
  return node;
}
References DCHECK_NOT_NULL, v8::internal::GlobalHandles::NodeBlock< _NodeType >::IncreaseUsage(), and v8::internal::GlobalHandles::NodeBlock< _NodeType >::ListAdd().
begin()
template<class NodeType >
iterator v8::internal::GlobalHandles::NodeSpace< NodeType >::begin () [inline]
Definition at line 211 of file global-handles.cc.
{ return iterator(first_used_block_); }
References v8::internal::GlobalHandles::NodeSpace< NodeType >::first_used_block_.
end()
template<class NodeType >
iterator v8::internal::GlobalHandles::NodeSpace< NodeType >::end () [inline]
Definition at line 212 of file global-handles.cc.
{ return iterator(nullptr); }
Free()
template<class NodeType >
void v8::internal::GlobalHandles::NodeSpace< NodeType >::Free (NodeType * node) [inline], [private]
Definition at line 278 of file global-handles.cc.
                                                          {
  CHECK(node->IsInUse());
  node->Release(first_free_);
  first_free_ = node;
  BlockType* block = BlockType::From(node);
  if (block->DecreaseUsage()) {
    block->ListRemove(&first_used_block_);
  }
  global_handles_->isolate()->counters()->global_handles()->Decrement();
  handles_count_--;
}
References CHECK, v8::internal::GlobalHandles::NodeBlock< _NodeType >::DecreaseUsage(), and v8::internal::GlobalHandles::NodeBlock< _NodeType >::ListRemove().
From()
template<class NodeType >
static NodeSpace* v8::internal::GlobalHandles::NodeSpace< NodeType >::From (NodeType * node) [static]
handles_count()
template<class NodeType >
size_t v8::internal::GlobalHandles::NodeSpace< NodeType >::handles_count () const [inline]
Definition at line 215 of file global-handles.cc.
{ return handles_count_; }
References v8::internal::GlobalHandles::NodeSpace< NodeType >::handles_count_.
PutNodesOnFreeList()
template<class NodeType >
void v8::internal::GlobalHandles::NodeSpace< NodeType >::PutNodesOnFreeList (BlockType * block) [private]
Definition at line 260 of file global-handles.cc.
                                                                          {
  for (int32_t i = kBlockSize - 1; i >= 0; --i) {
    NodeType* node = block->at(i);
    const uint8_t index = static_cast<uint8_t>(i);
    DCHECK_EQ(i, index);
    node->set_index(index);
    node->Free(first_free_);
    first_free_ = node;
  }
}
References v8::internal::GlobalHandles::NodeBlock< _NodeType >::at(), DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, and v8::internal::anonymous_namespace{global-handles.cc}::kBlockSize.
Release()
template<class NodeType >
void v8::internal::GlobalHandles::NodeSpace< NodeType >::Release (NodeType * node) [static]
Definition at line 272 of file global-handles.cc.
                                                             {
  BlockType* block = BlockType::From(node);
  block->space()->Free(node);
}
References v8::internal::GlobalHandles::NodeBlock< _NodeType >::space().
Referenced by v8::internal::GlobalHandles::Destroy(), and v8::internal::GlobalHandles::Node::ResetPhantomHandle().
TotalSize()
template<class NodeType >
size_t v8::internal::GlobalHandles::NodeSpace< NodeType >::TotalSize () const [inline]
Definition at line 214 of file global-handles.cc.
{ return blocks_ * sizeof(NodeType) * kBlockSize; }
References v8::internal::GlobalHandles::NodeSpace< NodeType >::blocks_, and v8::internal::anonymous_namespace{global-handles.cc}::kBlockSize.
Member Data Documentation
blocks_
template<class NodeType >
size_t v8::internal::GlobalHandles::NodeSpace< NodeType >::blocks_ = 0 [private]
Definition at line 225 of file global-handles.cc.
Referenced by v8::internal::GlobalHandles::NodeSpace< NodeType >::TotalSize().
first_block_
template<class NodeType >
BlockType* v8::internal::GlobalHandles::NodeSpace< NodeType >::first_block_ = nullptr [private]
Definition at line 222 of file global-handles.cc.
first_free_
template<class NodeType >
NodeType* v8::internal::GlobalHandles::NodeSpace< NodeType >::first_free_ = nullptr [private]
Definition at line 224 of file global-handles.cc.
first_used_block_
template<class NodeType >
BlockType* v8::internal::GlobalHandles::NodeSpace< NodeType >::first_used_block_ = nullptr [private]
Definition at line 223 of file global-handles.cc.
Referenced by v8::internal::GlobalHandles::NodeSpace< NodeType >::begin().
global_handles_
template<class NodeType >
GlobalHandles* const v8::internal::GlobalHandles::NodeSpace< NodeType >::global_handles_ [private]
Definition at line 221 of file global-handles.cc.
handles_count_
template<class NodeType >
size_t v8::internal::GlobalHandles::NodeSpace< NodeType >::handles_count_ = 0 [private]
Definition at line 226 of file global-handles.cc.
Referenced by v8::internal::GlobalHandles::NodeSpace< NodeType >::handles_count().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/handles/global-handles.cc