v8::TypecheckWitness Class Reference
Can be used to avoid repeated expensive type checks for groups of objects that are expected to be similar (e.g.
#include <v8-value.h>
Public Member Functions
TypecheckWitness (Isolate *isolate)
bool Matches (Local< Value > candidate) const
Checks whether {candidate} can cheaply be identified as being `similar` to the {baseline} that was passed to {Update} earlier.
void Update (Local< Value > baseline)
Remembers a new baseline for future {Matches} queries.
Private Attributes
Local< Data > cached_map_
Detailed Description
Can be used to avoid repeated expensive type checks for groups of objects that are expected to be similar (e.g.
when Blink converts a bunch of JavaScript objects to `ScriptWrappable` after a `HasInstance` check) by making use of V8-internal `hidden classes`. An object that has passed the full check can be remembered via {Update}; further objects can be queried using {Matches}. Note that the answer will be conservative/`best-effort`: when {Matches} returns true, then the {candidate} can be relied upon to have the same shape/constructor/prototype/etc. as the {baseline}. Otherwise, no reliable statement can be made (the objects might still have indistinguishable shapes for all intents and purposes, but this mechanism, being optimized for speed, couldn't determine that quickly).
Definition at line 515 of file v8-value.h.
Constructor & Destructor Documentation
TypecheckWitness()
v8::TypecheckWitness::TypecheckWitness (Isolate * isolate) [explicit]
Definition at line 8343 of file api.cc.
    : cached_map_()
#else
    // We need to reserve a handle that we can patch later.
    // We initialize it with something that cannot compare equal to any map.
    : cached_map_(v8::Number::New(isolate, 1))
#endif
{
}
Member Function Documentation
Matches()
bool v8::TypecheckWitness::Matches (Local< Value > candidate) const [inline]
Checks whether {candidate} can cheaply be identified as being `similar` to the {baseline} that was passed to {Update} earlier.
It's safe to call this on an uninitialized {TypecheckWitness} instance: it will then return {false} for any input.
Definition at line 664 of file v8-value.h.
                                                           {
  internal::Address obj = internal::ValueHelper::ValueAsAddress(*candidate);
  internal::Address obj_map = internal::Internals::LoadMap(obj);
  internal::Address cached =
      internal::ValueHelper::ValueAsAddress(*cached_map_);
  return obj_map == cached;
}
References cached_map_, v8::internal::Internals::LoadMap(), and v8::internal::ValueHelper::ValueAsAddress().
Update()
void v8::TypecheckWitness::Update (Local< Value > baseline)
Remembers a new baseline for future {Matches} queries.
Definition at line 8355 of file api.cc.
                                                     {
  i::Tagged<i::Object> obj = *Utils::OpenDirectHandle(*baseline);
#ifdef V8_ENABLE_DIRECT_HANDLE
  if (IsSmi(obj)) {
    cached_map_ = Local<Data>();
  } else {
    i::Tagged<i::HeapObject> map = i::Cast<i::HeapObject>(obj)->map();
    cached_map_ = Local<Data>::FromAddress(map->ptr());
  }
#else
  i::Tagged<i::Object> map = i::Smi::zero();
  if (!IsSmi(obj)) map = i::Cast<i::HeapObject>(obj)->map();
  // Design overview: in the {TypecheckWitness} constructor, we create
  // a single handle for the witness value. Whenever {Update} is called, we
  // make this handle point at the fresh baseline/witness; the intention is
  // to allow having short-lived HandleScopes (e.g. in {FastIterateArray}
  // above) while a {TypecheckWitness} is alive: it therefore cannot hold
  // on to one of the short-lived handles.
  // Calling {OpenIndirectHandle} on the {cached_map_} only serves to
  // "reinterpret_cast" it to an {i::IndirectHandle} on which we can call
  // {PatchValue}.
  auto cache = Utils::OpenIndirectHandle(*cached_map_);
  cache.PatchValue(map);
#endif
}
References v8::internal::IsSmi(), v8::Utils::OpenDirectHandle(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::Smi::zero().
Member Data Documentation
cached_map_
Local<Data> v8::TypecheckWitness::cached_map_ [private]
Definition at line 533 of file v8-value.h.
Referenced by Matches().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-value.h
/mnt/V8SourceCode/src/api/api.cc