v8::internal::CodeTracer::StreamScope Class Reference
#include <code-tracer.h>
Public Member Functions
StreamScope (CodeTracer *tracer)
std::ostream & stream ()
Private Attributes
std::optional< StdoutStream > stdout_stream_
std::optional< OFStream > file_stream_
Detailed Description
Definition at line 54 of file code-tracer.h.
Constructor & Destructor Documentation
StreamScope()
v8::internal::CodeTracer::StreamScope::StreamScope (CodeTracer * tracer) [inline], [explicit]
Definition at line 56 of file code-tracer.h.
                                             : Scope(tracer) {
      FILE* file = this->file();
      if (file == stdout) {
        stdout_stream_.emplace();
      } else {
        file_stream_.emplace(file);
      }
    }
References v8::internal::CodeTracer::file().
Member Function Documentation
stream()
std::ostream& v8::internal::CodeTracer::StreamScope::stream () [inline]
Definition at line 65 of file code-tracer.h.
                         {
      if (stdout_stream_.has_value()) return stdout_stream_.value();
      return file_stream_.value();
    }
Referenced by v8::internal::compiler::turboshaft::Pipeline::FinalizeCode(), v8::internal::maglev::MaglevCompiler::GenerateCode(), v8::internal::compiler::PipelineImpl::InitializeHeapBroker(), v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl(), v8::internal::compiler::PrintCode(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintFunctionSource(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintInlinedFunctionInfo(), v8::internal::compiler::turboshaft::PrintTurboshaftGraph(), v8::internal::compiler::PrintGraphPhase::Run(), v8::internal::compiler::TraceSchedule(), v8::internal::compiler::turboshaft::Pipeline::TraceSequence(), and v8::internal::compiler::turboshaft::anonymous_namespace{instruction-selection-phase.cc}::TraceSequence().
Member Data Documentation
file_stream_
std::optional<OFStream> v8::internal::CodeTracer::StreamScope::file_stream_ [private]
Definition at line 73 of file code-tracer.h.
stdout_stream_
std::optional<StdoutStream> v8::internal::CodeTracer::StreamScope::stdout_stream_ [private]
Definition at line 72 of file code-tracer.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/diagnostics/code-tracer.h