v8::internal::MemOperand Class Reference
#include <assembler-arm.h>
Public Types
enum OffsetAddend { offset_minus_one = -1
, offset_zero = 0
, offset_minus_one = -1
, offset_zero = 0
 }
enum OffsetAddend { offset_minus_one = -1
, offset_zero = 0
, offset_minus_one = -1
, offset_zero = 0
 }
Public Member Functions
MemOperand (Register rn, int32_t offset=0, AddrMode am=Offset)
MemOperand (Register rn, Register rm, AddrMode am=Offset)
MemOperand (Register rn, Register rm, ShiftOp shift_op, int shift_imm, AddrMode am=Offset)
bool IsImmediateOffset () const
void set_offset (int32_t offset)
int32_t offset () const
Register rn () const
Register rm () const
AddrMode am () const
bool OffsetIsUint12Encodable () const
MemOperand ()
MemOperand (Register base, int64_t offset=0, AddrMode addrmode=Offset)
MemOperand (Register base, Register regoffset, Shift shift=LSL, unsigned shift_amount=0)
MemOperand (Register base, Register regoffset, Extend extend, unsigned shift_amount=0)
MemOperand (Register base, const Operand &offset, AddrMode addrmode=Offset)
const Register & base () const
const Register & regoffset () const
int64_t offset () const
AddrMode addrmode () const
Shift shift () const
Extend extend () const
unsigned shift_amount () const
bool IsImmediateOffset () const
bool IsRegisterOffset () const
bool IsPreIndex () const
bool IsPostIndex () const
MemOperand (Register rj, int32_t offset=0)
MemOperand (Register rj, Register offset=no_reg)
Register base () const
Register index () const
int32_t offset () const
bool hasIndexReg () const
MemOperand (Register rn, int32_t offset=0)
MemOperand (Register rn, int32_t unit, int32_t multiplier, OffsetAddend offset_addend=offset_zero)
int32_t offset () const
bool OffsetIsInt16Encodable () const
MemOperand (Register rn, int64_t offset=0)
MemOperand (Register ra, Register rb)
MemOperand (Register ra, Register rb, int64_t offset)
int64_t offset () const
Register ra () const
Register rb () const
MemOperand (Register rn, int32_t offset=0)
MemOperand (Register rn, int32_t unit, int32_t multiplier, OffsetAddend offset_addend=offset_zero)
int32_t offset () const
void set_offset (int32_t offset)
bool OffsetIsInt12Encodable () const
MemOperand (Register rx, Disp offset=0)
MemOperand (Register rx, Register rb, Disp offset=0)
int32_t offset () const
uint32_t getDisplacement () const
Register rb () const
Register getBaseRegister () const
Register rx () const
Register getIndexRegister () const
Static Public Member Functions
static MemOperand PointerAddressFromSmiKey (Register array, Register key, AddrMode am=Offset)
Private Attributes
Register rn_
Register rm_
int32_t offset_
ShiftOp shift_op_
int shift_imm_
AddrMode am_
Register base_
Register regoffset_
int64_t offset_
AddrMode addrmode_
Shift shift_
Extend extend_
unsigned shift_amount_
Register index_
Register ra_
Register rb_
Register baseRegister
Register indexRegister
Friends
class Assembler
Detailed Description
Definition at line 187 of file assembler-arm.h.
Member Enumeration Documentation
OffsetAddend [1/2]
enum v8::internal::MemOperand::OffsetAddend
Enumerator
offset_minus_one
offset_zero
offset_minus_one
offset_zero
Definition at line 127 of file assembler-mips64.h.
{ offset_minus_one = -1, offset_zero = 0 };
OffsetAddend [2/2]
enum v8::internal::MemOperand::OffsetAddend
Enumerator
offset_minus_one
offset_zero
offset_minus_one
offset_zero
Definition at line 159 of file assembler-riscv.h.
{ offset_minus_one = -1, offset_zero = 0 };
Constructor & Destructor Documentation
MemOperand() [1/19]
v8::internal::MemOperand::MemOperand (Register rn, int32_t offset = 0, AddrMode am = Offset) [explicit]
MemOperand() [2/19]
v8::internal::MemOperand::MemOperand (Register rn, Register rm, AddrMode am = Offset) [explicit]
MemOperand() [3/19]
v8::internal::MemOperand::MemOperand (Register rn, Register rm, ShiftOp shift_op, int shift_imm, AddrMode am = Offset) [explicit]
MemOperand() [4/19]
v8::internal::MemOperand::MemOperand () [inline]
Definition at line 369 of file assembler-arm64-inl.h.
    : base_(NoReg),
      regoffset_(NoReg),
      offset_(0),
      addrmode_(Offset),
      shift_(NO_SHIFT),
      extend_(NO_EXTEND),
      shift_amount_(0) {}
MemOperand() [5/19]
v8::internal::MemOperand::MemOperand (Register base, int64_t offset = 0, AddrMode addrmode = Offset) [inline], [explicit]
Definition at line 378 of file assembler-arm64-inl.h.
    : base_(base),
      regoffset_(NoReg),
      offset_(offset),
      addrmode_(addrmode),
      shift_(NO_SHIFT),
      extend_(NO_EXTEND),
      shift_amount_(0) {
  DCHECK(base.Is64Bits() && !base.IsZero());
}
References base(), v8::internal::DCHECK(), v8::internal::CPURegister::Is64Bits(), and v8::internal::CPURegister::IsZero().
MemOperand() [6/19]
v8::internal::MemOperand::MemOperand (Register base, Register regoffset, Shift shift = LSL, unsigned shift_amount = 0) [inline], [explicit]
Definition at line 406 of file assembler-arm64-inl.h.
    : base_(base),
      regoffset_(regoffset),
      offset_(0),
      addrmode_(Offset),
      shift_(shift),
      extend_(NO_EXTEND),
      shift_amount_(shift_amount) {
  DCHECK(base.Is64Bits() && !base.IsZero());
  DCHECK(regoffset.Is64Bits() && !regoffset.IsSP());
  DCHECK(shift == LSL);
}
References base(), v8::internal::DCHECK(), v8::internal::CPURegister::Is64Bits(), v8::internal::CPURegister::IsSP(), v8::internal::CPURegister::IsZero(), v8::internal::LSL, regoffset(), and shift().
MemOperand() [7/19]
v8::internal::MemOperand::MemOperand (Register base, Register regoffset, Extend extend, unsigned shift_amount = 0) [inline], [explicit]
Definition at line 389 of file assembler-arm64-inl.h.
    : base_(base),
      regoffset_(regoffset),
      offset_(0),
      addrmode_(Offset),
      shift_(NO_SHIFT),
      extend_(extend),
      shift_amount_(shift_amount) {
  DCHECK(base.Is64Bits() && !base.IsZero());
  DCHECK(!regoffset.IsSP());
  DCHECK((extend == UXTW) || (extend == SXTW) || (extend == SXTX));
  // SXTX extend mode requires a 64-bit offset register.
  DCHECK(regoffset.Is64Bits() || (extend != SXTX));
}
References base(), v8::internal::DCHECK(), extend(), v8::internal::CPURegister::Is64Bits(), v8::internal::CPURegister::IsSP(), v8::internal::CPURegister::IsZero(), regoffset(), v8::internal::SXTW, v8::internal::SXTX, and v8::internal::UXTW.
MemOperand() [8/19]
v8::internal::MemOperand::MemOperand (Register base, const Operand & offset, AddrMode addrmode = Offset) [inline], [explicit]
Definition at line 420 of file assembler-arm64-inl.h.
    : base_(base), regoffset_(NoReg), addrmode_(addrmode) {
  DCHECK(base.Is64Bits() && !base.IsZero());
  if (offset.IsImmediate()) {
    offset_ = offset.ImmediateValue();
  } else if (offset.IsShiftedRegister()) {
    DCHECK((addrmode == Offset) || (addrmode == PostIndex));
    regoffset_ = offset.reg();
    shift_ = offset.shift();
    shift_amount_ = offset.shift_amount();
    extend_ = NO_EXTEND;
    offset_ = 0;
    // These assertions match those in the shifted-register constructor.
    DCHECK(regoffset_.Is64Bits() && !regoffset_.IsSP());
    DCHECK(shift_ == LSL);
  } else {
    DCHECK(offset.IsExtendedRegister());
    DCHECK(addrmode == Offset);
    regoffset_ = offset.reg();
    extend_ = offset.extend();
    shift_amount_ = offset.shift_amount();
    shift_ = NO_SHIFT;
    offset_ = 0;
    // These assertions match those in the extended-register constructor.
    DCHECK(!regoffset_.IsSP());
    DCHECK((extend_ == UXTW) || (extend_ == SXTW) || (extend_ == SXTX));
    DCHECK((regoffset_.Is64Bits() || (extend_ != SXTX)));
  }
}
References addrmode(), base(), v8::internal::DCHECK(), extend_, v8::internal::CPURegister::Is64Bits(), v8::internal::CPURegister::IsSP(), v8::internal::CPURegister::IsZero(), v8::internal::LSL, v8::internal::NO_EXTEND, v8::internal::NO_SHIFT, offset(), v8::internal::Offset, offset_, v8::internal::PostIndex, regoffset_, shift_, shift_amount_, v8::internal::SXTW, v8::internal::SXTX, and v8::internal::UXTW.
MemOperand() [9/19]
v8::internal::MemOperand::MemOperand (Register rj, int32_t offset = 0) [explicit]
Definition at line 235 of file assembler-riscv.cc.
                                                  : Operand(rm) {
  offset_ = offset;
}
References offset(), and offset_.
MemOperand() [10/19]
v8::internal::MemOperand::MemOperand (Register rj, Register offset = no_reg) [explicit]
MemOperand() [11/19]
v8::internal::MemOperand::MemOperand (Register rn, int32_t offset = 0) [explicit]
MemOperand() [12/19]
v8::internal::MemOperand::MemOperand (Register rn, int32_t unit, int32_t multiplier, OffsetAddend offset_addend = offset_zero) [explicit]
Definition at line 239 of file assembler-riscv.cc.
    : Operand(rm) {
  offset_ = unit * multiplier + offset_addend;
}
References offset_.
MemOperand() [13/19]
v8::internal::MemOperand::MemOperand (Register rn, int64_t offset = 0) [explicit]
MemOperand() [14/19]
v8::internal::MemOperand::MemOperand (Register ra, Register rb) [explicit]
MemOperand() [15/19]
v8::internal::MemOperand::MemOperand (Register ra, Register rb, int64_t offset) [explicit]
MemOperand() [16/19]
v8::internal::MemOperand::MemOperand (Register rn, int32_t offset = 0) [explicit]
MemOperand() [17/19]
v8::internal::MemOperand::MemOperand (Register rn, int32_t unit, int32_t multiplier, OffsetAddend offset_addend = offset_zero) [explicit]
MemOperand() [18/19]
v8::internal::MemOperand::MemOperand (Register rx, Disp offset = 0) [explicit]
MemOperand() [19/19]
v8::internal::MemOperand::MemOperand (Register rx, Register rb, Disp offset = 0) [explicit]
Member Function Documentation
addrmode()
AddrMode v8::internal::MemOperand::addrmode () const [inline]
Definition at line 149 of file assembler-arm64.h.
{ return addrmode_; }
References addrmode_.
Referenced by MemOperand(), and v8::internal::MacroAssembler::SmiUntag().
am()
AddrMode v8::internal::MemOperand::am () const [inline]
Definition at line 228 of file assembler-arm.h.
{ return am_; }
Referenced by v8::internal::maglev::MaglevAssembler::JumpIfNotHoleNan(), and v8::internal::maglev::MaglevAssembler::LoadAddress().
base() [1/2]
const Register& v8::internal::MemOperand::base () const [inline]
Definition at line 146 of file assembler-arm64.h.
{ return base_; }
References base_.
Referenced by MemOperand(), and v8::internal::MacroAssembler::SmiUntag().
base() [2/2]
Register v8::internal::MemOperand::base () const [inline]
Definition at line 99 of file assembler-loong64.h.
{ return base_; }
extend()
Extend v8::internal::MemOperand::extend () const [inline]
Definition at line 151 of file assembler-arm64.h.
{ return extend_; }
References extend_.
Referenced by MemOperand().
getBaseRegister()
Register v8::internal::MemOperand::getBaseRegister () const [inline]
Definition at line 164 of file assembler-s390.h.
{ return rb(); }
getDisplacement()
uint32_t v8::internal::MemOperand::getDisplacement () const [inline]
Definition at line 156 of file assembler-s390.h.
{ return offset(); }
getIndexRegister()
Register v8::internal::MemOperand::getIndexRegister () const [inline]
Definition at line 171 of file assembler-s390.h.
{ return rx(); }
hasIndexReg()
bool v8::internal::MemOperand::hasIndexReg () const [inline]
Definition at line 103 of file assembler-loong64.h.
{ return index_ != no_reg; }
References v8::internal::no_reg.
index()
Register v8::internal::MemOperand::index () const [inline]
Definition at line 100 of file assembler-loong64.h.
{ return index_; }
IsImmediateOffset() [1/2]
bool v8::internal::MemOperand::IsImmediateOffset () const [inline]
Definition at line 214 of file assembler-arm.h.
{ return rm_ == no_reg; }
References v8::internal::no_reg.
Referenced by v8::internal::maglev::MaglevAssembler::JumpIfNotHoleNan(), and v8::internal::MacroAssembler::SmiUntag().
IsImmediateOffset() [2/2]
bool v8::internal::MemOperand::IsImmediateOffset () const [inline]
IsPostIndex()
bool v8::internal::MemOperand::IsPostIndex () const [inline]
Definition at line 467 of file assembler-arm64-inl.h.
{ return addrmode_ == PostIndex; }
References addrmode_, and v8::internal::PostIndex.
IsPreIndex()
bool v8::internal::MemOperand::IsPreIndex () const [inline]
Definition at line 465 of file assembler-arm64-inl.h.
{ return addrmode_ == PreIndex; }
References addrmode_, and v8::internal::PreIndex.
IsRegisterOffset()
bool v8::internal::MemOperand::IsRegisterOffset () const [inline]
Definition at line 461 of file assembler-arm64-inl.h.
                                        {
  return (addrmode_ == Offset) && regoffset_ != NoReg;
}
References addrmode_, v8::internal::NoReg, v8::internal::Offset, and regoffset_.
offset() [1/7]
int32_t v8::internal::MemOperand::offset () const [inline]
Definition at line 221 of file assembler-arm.h.
                         {
    DCHECK(IsImmediateOffset());
    return offset_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::Assembler::AdjustBaseAndOffset(), v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::wasm::LiftoffAssembler::CallCWithStackBuffer(), v8::internal::wasm::LiftoffStackSlots::Construct(), v8::internal::compiler::S390OperandConverter::InputStackSlot32(), v8::internal::maglev::MaglevAssembler::JumpIfNotHoleNan(), v8::internal::MacroAssembler::Ll(), v8::internal::wasm::liftoff::Load(), v8::internal::maglev::MaglevAssembler::LoadAddress(), v8::internal::MacroAssembler::LoadNBytes(), v8::internal::MacroAssembler::LoadNBytesOverwritingBaseReg(), MemOperand(), v8::internal::Assembler::NeedAdjustBaseAndOffset(), v8::internal::MacroAssembler::Sc(), v8::internal::MacroAssembler::SmiUntag(), v8::internal::wasm::LiftoffAssembler::Spill(), v8::internal::wasm::liftoff::Store(), and v8::internal::MacroAssembler::UnalignedStoreHelper().
offset() [2/7]
int64_t v8::internal::MemOperand::offset () const [inline]
Definition at line 148 of file assembler-arm64.h.
{ return offset_; }
References offset_.
offset() [3/7]
int32_t v8::internal::MemOperand::offset () const [inline]
Definition at line 101 of file assembler-loong64.h.
{ return offset_; }
offset() [4/7]
int32_t v8::internal::MemOperand::offset () const [inline]
Definition at line 132 of file assembler-mips64.h.
{ return offset_; }
offset() [5/7]
int64_t v8::internal::MemOperand::offset () const [inline]
Definition at line 140 of file assembler-ppc.h.
{ return offset_; }
offset() [6/7]
int32_t v8::internal::MemOperand::offset () const [inline]
Definition at line 164 of file assembler-riscv.h.
{ return offset_; }
offset() [7/7]
int32_t v8::internal::MemOperand::offset () const [inline]
Definition at line 155 of file assembler-s390.h.
{ return offset_; }
OffsetIsInt12Encodable()
bool v8::internal::MemOperand::OffsetIsInt12Encodable () const [inline]
Definition at line 168 of file assembler-riscv.h.
{ return is_int12(offset_); }
OffsetIsInt16Encodable()
bool v8::internal::MemOperand::OffsetIsInt16Encodable () const [inline]
Definition at line 134 of file assembler-mips64.h.
{ return is_int16(offset_); }
OffsetIsUint12Encodable()
bool v8::internal::MemOperand::OffsetIsUint12Encodable () const [inline]
Definition at line 230 of file assembler-arm.h.
                                       {
    return offset_ >= 0 ? is_uint12(offset_) : is_uint12(-offset_);
  }
PointerAddressFromSmiKey()
static MemOperand v8::internal::MemOperand::PointerAddressFromSmiKey (Register array, Register key, AddrMode am = Offset) [inline], [static]
Definition at line 207 of file assembler-arm.h.
                                                                             {
    static_assert(kSmiTag == 0 && kSmiTagSize < kPointerSizeLog2);
    return MemOperand(array, key, LSL, kPointerSizeLog2 - kSmiTagSize, am);
  }
References v8::internal::key, v8::internal::kPointerSizeLog2, v8::internal::kSmiTag, v8::internal::kSmiTagSize, and v8::internal::LSL.
ra()
Register v8::internal::MemOperand::ra () const [inline]
Definition at line 143 of file assembler-ppc.h.
{ return ra_; }
Referenced by v8::internal::Assembler::lwax().
rb() [1/2]
Register v8::internal::MemOperand::rb () const [inline]
Definition at line 145 of file assembler-ppc.h.
{ return rb_; }
Referenced by v8::internal::compiler::S390OperandConverter::InputStackSlot32(), and v8::internal::Assembler::lwax().
rb() [2/2]
Register v8::internal::MemOperand::rb () const [inline]
Definition at line 159 of file assembler-s390.h.
                      {
    DCHECK(baseRegister != no_reg);
    return baseRegister;
  }
References v8::internal::DCHECK(), and v8::internal::no_reg.
regoffset()
const Register& v8::internal::MemOperand::regoffset () const [inline]
Definition at line 147 of file assembler-arm64.h.
{ return regoffset_; }
References regoffset_.
Referenced by MemOperand().
rm()
Register v8::internal::MemOperand::rm () const [inline]
Definition at line 227 of file assembler-arm.h.
{ return rm_; }
Referenced by v8::internal::Assembler::AdjustBaseAndOffset(), v8::internal::MacroAssembler::AlignedLoadHelper(), v8::internal::MacroAssembler::AlignedStoreHelper(), v8::internal::MacroAssembler::Ll(), v8::internal::wasm::liftoff::LoadInternal(), v8::internal::MacroAssembler::LoadLane(), v8::internal::MacroAssembler::LoadNBytes(), v8::internal::MacroAssembler::LoadNBytesOverwritingBaseReg(), v8::internal::MacroAssembler::Sc(), v8::internal::wasm::LiftoffAssembler::Store(), v8::internal::MacroAssembler::StoreLane(), v8::internal::MacroAssembler::UnalignedLoadHelper(), and v8::internal::MacroAssembler::UnalignedStoreHelper().
rn()
Register v8::internal::MemOperand::rn () const [inline]
Definition at line 226 of file assembler-arm.h.
{ return rn_; }
Referenced by v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::wasm::LiftoffStackSlots::Construct(), v8::internal::maglev::MaglevAssembler::JumpIfNotHoleNan(), v8::internal::wasm::liftoff::Load(), v8::internal::maglev::MaglevAssembler::LoadAddress(), and v8::internal::wasm::liftoff::Store().
rx()
Register v8::internal::MemOperand::rx () const [inline]
Definition at line 167 of file assembler-s390.h.
                      {
    DCHECK(indexRegister != no_reg);
    return indexRegister;
  }
References v8::internal::DCHECK(), and v8::internal::no_reg.
Referenced by v8::internal::compiler::S390OperandConverter::InputStackSlot32().
set_offset() [1/2]
void v8::internal::MemOperand::set_offset (int32_t offset) [inline]
Definition at line 216 of file assembler-arm.h.
                                  {
    DCHECK(IsImmediateOffset());
    offset_ = offset;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::LiftoffAssembler::CallCWithStackBuffer().
set_offset() [2/2]
void v8::internal::MemOperand::set_offset (int32_t offset) [inline]
Definition at line 166 of file assembler-riscv.h.
{ offset_ = offset; }
shift()
Shift v8::internal::MemOperand::shift () const [inline]
Definition at line 150 of file assembler-arm64.h.
{ return shift_; }
References shift_.
Referenced by MemOperand().
shift_amount()
unsigned v8::internal::MemOperand::shift_amount () const [inline]
Definition at line 152 of file assembler-arm64.h.
{ return shift_amount_; }
References shift_amount_.
Referenced by v8::internal::MacroAssembler::SmiUntag().
Friends And Related Function Documentation
Assembler
Assembler [friend]
Definition at line 242 of file assembler-arm.h.
Member Data Documentation
addrmode_
AddrMode v8::internal::MemOperand::addrmode_ [private]
Definition at line 162 of file assembler-arm64.h.
Referenced by addrmode(), IsPostIndex(), IsPreIndex(), and IsRegisterOffset().
am_
AddrMode v8::internal::MemOperand::am_ [private]
Definition at line 240 of file assembler-arm.h.
base_
Register v8::internal::MemOperand::base_ [private]
Definition at line 159 of file assembler-arm64.h.
Referenced by base().
baseRegister
Register v8::internal::MemOperand::baseRegister [private]
Definition at line 174 of file assembler-s390.h.
extend_
Extend v8::internal::MemOperand::extend_ [private]
Definition at line 164 of file assembler-arm64.h.
Referenced by extend(), and MemOperand().
index_
Register v8::internal::MemOperand::index_ [private]
Definition at line 107 of file assembler-loong64.h.
indexRegister
Register v8::internal::MemOperand::indexRegister [private]
Definition at line 175 of file assembler-s390.h.
offset_ [1/2]
int32_t v8::internal::MemOperand::offset_ [private]
Definition at line 237 of file assembler-arm.h.
Referenced by v8::internal::Assembler::AdjustBaseAndOffset(), MemOperand(), and offset().
offset_ [2/2]
int64_t v8::internal::MemOperand::offset_ [private]
Definition at line 161 of file assembler-arm64.h.
ra_
Register v8::internal::MemOperand::ra_ [private]
Definition at line 148 of file assembler-ppc.h.
rb_
Register v8::internal::MemOperand::rb_ [private]
Definition at line 150 of file assembler-ppc.h.
regoffset_
Register v8::internal::MemOperand::regoffset_ [private]
Definition at line 160 of file assembler-arm64.h.
Referenced by IsRegisterOffset(), MemOperand(), and regoffset().
rm_
Register v8::internal::MemOperand::rm_ [private]
Definition at line 236 of file assembler-arm.h.
Referenced by v8::internal::Assembler::AdjustBaseAndOffset().
rn_
Register v8::internal::MemOperand::rn_ [private]
Definition at line 235 of file assembler-arm.h.
shift_
Shift v8::internal::MemOperand::shift_ [private]
Definition at line 163 of file assembler-arm64.h.
Referenced by MemOperand(), and shift().
shift_amount_
unsigned v8::internal::MemOperand::shift_amount_ [private]
Definition at line 165 of file assembler-arm64.h.
Referenced by MemOperand(), and shift_amount().
shift_imm_
int v8::internal::MemOperand::shift_imm_ [private]
Definition at line 239 of file assembler-arm.h.
shift_op_
ShiftOp v8::internal::MemOperand::shift_op_ [private]
Definition at line 238 of file assembler-arm.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/arm/assembler-arm.h
/mnt/V8SourceCode/src/codegen/arm64/assembler-arm64.h
/mnt/V8SourceCode/src/codegen/loong64/assembler-loong64.h
/mnt/V8SourceCode/src/codegen/mips64/assembler-mips64.h
/mnt/V8SourceCode/src/codegen/ppc/assembler-ppc.h
/mnt/V8SourceCode/src/codegen/riscv/assembler-riscv.h
/mnt/V8SourceCode/src/codegen/s390/assembler-s390.h
/mnt/V8SourceCode/src/codegen/arm64/assembler-arm64-inl.h
/mnt/V8SourceCode/src/codegen/riscv/assembler-riscv.cc