v8::internal::PersistentHandlesList Class Reference
#include <persistent-handles.h>
Public Member Functions
PersistentHandlesList ()
void Iterate (RootVisitor *visitor, Isolate *isolate)
Private Member Functions
void Add (PersistentHandles *persistent_handles)
void Remove (PersistentHandles *persistent_handles)
Private Attributes
base::Mutex persistent_handles_mutex_
PersistentHandles * persistent_handles_head_
Friends
class PersistentHandles
Detailed Description
Definition at line 101 of file persistent-handles.h.
Constructor & Destructor Documentation
PersistentHandlesList()
v8::internal::PersistentHandlesList::PersistentHandlesList () [inline]
Definition at line 103 of file persistent-handles.h.
: persistent_handles_head_(nullptr) {}
Member Function Documentation
Add()
void v8::internal::PersistentHandlesList::Add (PersistentHandles * persistent_handles) [private]
Definition at line 106 of file persistent-handles.cc.
                                                                     {
  base::MutexGuard guard(&persistent_handles_mutex_);
  if (persistent_handles_head_)
    persistent_handles_head_->prev_ = persistent_handles;
  persistent_handles->prev_ = nullptr;
  persistent_handles->next_ = persistent_handles_head_;
  persistent_handles_head_ = persistent_handles;
}
References v8::internal::PersistentHandles::next_, persistent_handles_head_, persistent_handles_mutex_, and v8::internal::PersistentHandles::prev_.
Referenced by v8::internal::PersistentHandles::PersistentHandles().
Iterate()
void v8::internal::PersistentHandlesList::Iterate (RootVisitor * visitor, Isolate * isolate)
Definition at line 125 of file persistent-handles.cc.
                                                                          {
  isolate->heap()->safepoint()->AssertActive();
  for (PersistentHandles* current = persistent_handles_head_; current;
       current = current->next_) {
    current->Iterate(visitor);
  }
}
References v8::internal::IsolateSafepoint::AssertActive(), v8::internal::Isolate::heap(), v8::internal::PersistentHandles::next_, persistent_handles_head_, and v8::internal::Heap::safepoint().
Referenced by v8::internal::Heap::IterateRoots().
Remove()
void v8::internal::PersistentHandlesList::Remove (PersistentHandles * persistent_handles) [private]
Definition at line 115 of file persistent-handles.cc.
                                                                        {
  base::MutexGuard guard(&persistent_handles_mutex_);
  if (persistent_handles->next_)
    persistent_handles->next_->prev_ = persistent_handles->prev_;
  if (persistent_handles->prev_)
    persistent_handles->prev_->next_ = persistent_handles->next_;
  else
    persistent_handles_head_ = persistent_handles->next_;
}
References v8::internal::PersistentHandles::next_, persistent_handles_head_, persistent_handles_mutex_, and v8::internal::PersistentHandles::prev_.
Referenced by v8::internal::PersistentHandles::~PersistentHandles().
Friends And Related Function Documentation
PersistentHandles
friend class PersistentHandles [friend]
Definition at line 114 of file persistent-handles.h.
Member Data Documentation
persistent_handles_head_
PersistentHandles* v8::internal::PersistentHandlesList::persistent_handles_head_ [private]
Definition at line 112 of file persistent-handles.h.
Referenced by Add(), Iterate(), and Remove().
persistent_handles_mutex_
base::Mutex v8::internal::PersistentHandlesList::persistent_handles_mutex_ [private]
Definition at line 111 of file persistent-handles.h.
Referenced by Add(), and Remove().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/persistent-handles.h
/mnt/V8SourceCode/src/handles/persistent-handles.cc