v8::internal::wasm::Indentation Class Reference
#include <wasm-disassembler-impl.h>
Public Member Functions
Indentation (int current, int delta)
Indentation Extra (int extra)
void increase ()
void decrease ()
int current ()
Private Attributes
int current_
int delta_
Detailed Description
Definition at line 37 of file wasm-disassembler-impl.h.
Constructor & Destructor Documentation
Indentation()
v8::internal::wasm::Indentation::Indentation (int current, int delta) [inline]
Definition at line 39 of file wasm-disassembler-impl.h.
                                      : current_(current), delta_(delta) {
    DCHECK_GE(current, 0);
    DCHECK_GE(delta, 0);
  }
References current(), and DCHECK_GE.
Member Function Documentation
current()
int v8::internal::wasm::Indentation::current () [inline]
Definition at line 51 of file wasm-disassembler-impl.h.
{ return current_; }
References current_.
Referenced by v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), Indentation(), and v8::internal::wasm::operator<<().
decrease()
void v8::internal::wasm::Indentation::decrease () [inline]
Definition at line 47 of file wasm-disassembler-impl.h.
                  {
    DCHECK_GE(current_, delta_);
    current_ -= delta_;
  }
References current_, DCHECK_GE, and delta_.
Referenced by v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
Extra()
Indentation v8::internal::wasm::Indentation::Extra (int extra) [inline]
Definition at line 44 of file wasm-disassembler-impl.h.
{ return {current_ + extra, delta_}; }
References current_, and delta_.
Referenced by v8::internal::wasm::ModuleDisassembler::LineBreakOrSpace().
increase()
void v8::internal::wasm::Indentation::increase () [inline]
Definition at line 46 of file wasm-disassembler-impl.h.
{ current_ += delta_; }
References current_, and delta_.
Referenced by v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
Member Data Documentation
current_
int v8::internal::wasm::Indentation::current_ [private]
Definition at line 54 of file wasm-disassembler-impl.h.
Referenced by current(), decrease(), Extra(), and increase().
delta_
int v8::internal::wasm::Indentation::delta_ [private]
Definition at line 55 of file wasm-disassembler-impl.h.
Referenced by decrease(), Extra(), and increase().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-disassembler-impl.h