v8::internal::compiler::ForInParameters Class Reference
#include <js-operator.h>
Public Member Functions
ForInParameters (const FeedbackSource &feedback, ForInMode mode)
const FeedbackSource & feedback () const
ForInMode mode () const
Private Attributes
const FeedbackSource feedback_
const ForInMode mode_
Detailed Description
Definition at line 825 of file js-operator.h.
Constructor & Destructor Documentation
ForInParameters()
v8::internal::compiler::ForInParameters::ForInParameters (const FeedbackSource & feedback, ForInMode mode) [inline]
Definition at line 827 of file js-operator.h.
      : feedback_(feedback), mode_(mode) {}
Member Function Documentation
feedback()
const FeedbackSource& v8::internal::compiler::ForInParameters::feedback () const [inline]
Definition at line 830 of file js-operator.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
mode()
ForInMode v8::internal::compiler::ForInParameters::mode () const [inline]
Definition at line 831 of file js-operator.h.
{ return mode_; }
References mode_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare(), and v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty().
Member Data Documentation
feedback_
const FeedbackSource v8::internal::compiler::ForInParameters::feedback_ [private]
Definition at line 834 of file js-operator.h.
Referenced by feedback().
mode_
const ForInMode v8::internal::compiler::ForInParameters::mode_ [private]
Definition at line 835 of file js-operator.h.
Referenced by mode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h