v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType > Class Template Reference
Public Types
using BackingStore = typename ElementsKindTraits< Kind >::BackingStore
using AccessorClass = TypedElementsAccessor< Kind, ElementType >
Public Member Functions
Handle< Object > ToHandle (Isolate *isolate, int8_t value)
Handle< Object > ToHandle (Isolate *isolate, uint8_t value)
Handle< Object > ToHandle (Isolate *isolate, int16_t value)
Handle< Object > ToHandle (Isolate *isolate, uint16_t value)
Handle< Object > ToHandle (Isolate *isolate, int32_t value)
Handle< Object > ToHandle (Isolate *isolate, uint32_t value)
uint16_t FromScalar (double value)
float FromScalar (double value)
uint16_t FromScalar (int value)
uint16_t FromScalar (uint32_t value)
Handle< Object > ToHandle (Isolate *isolate, uint16_t value)
Handle< Object > ToHandle (Isolate *isolate, float value)
double FromScalar (double value)
Handle< Object > ToHandle (Isolate *isolate, double value)
uint8_t FromScalar (int value)
uint8_t FromScalar (uint32_t value)
uint8_t FromScalar (double value)
Handle< Object > ToHandle (Isolate *isolate, uint8_t value)
int64_t FromScalar (int value)
int64_t FromScalar (uint32_t value)
int64_t FromScalar (double value)
int64_t FromScalar (int64_t value)
int64_t FromScalar (uint64_t value)
int64_t FromObject (Tagged< Object > value, bool *lossless)
Handle< Object > ToHandle (Isolate *isolate, int64_t value)
uint64_t FromScalar (int value)
uint64_t FromScalar (uint32_t value)
uint64_t FromScalar (double value)
uint64_t FromScalar (int64_t value)
uint64_t FromScalar (uint64_t value)
uint64_t FromObject (Tagged< Object > value, bool *lossless)
Handle< Object > ToHandle (Isolate *isolate, uint64_t value)
Handle< Object > ToHandle (Isolate *isolate, int8_t value)
Handle< Object > ToHandle (Isolate *isolate, uint8_t value)
Handle< Object > ToHandle (Isolate *isolate, int16_t value)
Handle< Object > ToHandle (Isolate *isolate, uint16_t value)
Handle< Object > ToHandle (Isolate *isolate, int32_t value)
Handle< Object > ToHandle (Isolate *isolate, uint32_t value)
uint16_t FromScalar (double value)
uint16_t FromScalar (int value)
uint16_t FromScalar (uint32_t value)
Handle< Object > ToHandle (Isolate *isolate, uint16_t value)
float FromScalar (double value)
Handle< Object > ToHandle (Isolate *isolate, float value)
double FromScalar (double value)
Handle< Object > ToHandle (Isolate *isolate, double value)
uint8_t FromScalar (int value)
uint8_t FromScalar (uint32_t value)
uint8_t FromScalar (double value)
Handle< Object > ToHandle (Isolate *isolate, uint8_t value)
int64_t FromScalar (int value)
int64_t FromScalar (uint32_t value)
int64_t FromScalar (double value)
int64_t FromScalar (int64_t value)
int64_t FromScalar (uint64_t value)
int64_t FromObject (Tagged< Object > value, bool *lossless)
Handle< Object > ToHandle (Isolate *isolate, int64_t value)
uint64_t FromScalar (int value)
uint64_t FromScalar (uint32_t value)
uint64_t FromScalar (double value)
uint64_t FromScalar (int64_t value)
uint64_t FromScalar (uint64_t value)
uint64_t FromObject (Tagged< Object > value, bool *lossless)
Handle< Object > ToHandle (Isolate *isolate, uint64_t value)
Static Public Member Functions
static ElementType FromScalar (int value)
static ElementType FromScalar (uint32_t value)
static ElementType FromScalar (double value)
static ElementType FromScalar (int64_t value)
static ElementType FromScalar (uint64_t value)
static ElementType FromObject (Tagged< Object > value, bool *lossless=nullptr)
static ElementType FromHandle (DirectHandle< Object > value, bool *lossless=nullptr)
static Handle< Object > ToHandle (Isolate *isolate, ElementType value)
static void SetImpl (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value)
static void SetImpl (ElementType *data_ptr, ElementType value, IsSharedBuffer is_shared)
static Handle< Object > GetInternalImpl (Isolate *isolate, DirectHandle< JSObject > holder, InternalIndex entry)
static DirectHandle< Object > GetImpl (Isolate *isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry)
static ElementType GetImpl (ElementType *data_ptr, IsSharedBuffer is_shared)
static PropertyDetails GetDetailsImpl (Tagged< JSObject > holder, InternalIndex entry)
static PropertyDetails GetDetailsImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry)
static bool HasElementImpl (Isolate *isolate, Tagged< JSObject > holder, size_t index, Tagged< FixedArrayBase > backing_store, PropertyFilter filter)
static bool HasAccessorsImpl (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store)
static Maybe< bool > SetLengthImpl (Isolate *isolate, DirectHandle< JSArray > array, uint32_t length, DirectHandle< FixedArrayBase > backing_store)
static void DeleteImpl (Isolate *isolate, DirectHandle< JSObject > obj, InternalIndex entry)
static InternalIndex GetEntryForIndexImpl (Isolate *isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store, size_t index, PropertyFilter filter)
static size_t GetCapacityImpl (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store)
static size_t NumberOfElementsImpl (Isolate *isolate, Tagged< JSObject > receiver, Tagged< FixedArrayBase > backing_store)
static V8_WARN_UNUSED_RESULT ExceptionStatus AddElementsToKeyAccumulatorImpl (DirectHandle< JSObject > receiver, KeyAccumulator *accumulator, AddKeyConversion convert)
static Maybe< bool > CollectValuesOrEntriesImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArray > values_or_entries, bool get_entries, int *nof_items, PropertyFilter filter)
static bool ToTypedSearchValue (double search_value, ElementType *typed_search_value)
static MaybeDirectHandle< Object > FillImpl (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start, size_t end)
static Maybe< bool > IncludesValueImpl (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length)
static Maybe< int64_t > IndexOfValueImpl (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length)
static Maybe< int64_t > LastIndexOfValueImpl (DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from)
static void ReverseImpl (Tagged< JSObject > receiver)
static Handle< FixedArray > CreateListFromArrayLikeImpl (Isolate *isolate, DirectHandle< JSObject > object, uint32_t length)
static void CopyTypedArrayElementsSliceImpl (Tagged< JSTypedArray > source, Tagged< JSTypedArray > destination, size_t start, size_t end)
static bool HasSimpleRepresentation (ExternalArrayType type)
template<ElementsKind SourceKind, typename SourceElementType >
static void CopyBetweenBackingStores (SourceElementType *source_data_ptr, ElementType *dest_data_ptr, size_t length, IsSharedBuffer is_shared)
static void CopyElementsFromTypedArray (Tagged< JSTypedArray > source, Tagged< JSTypedArray > destination, size_t length, size_t offset)
static bool HoleyPrototypeLookupRequired (Isolate *isolate, Tagged< Context > context, Tagged< JSArray > source)
static bool TryCopyElementsFastNumber (Tagged< Context > context, Tagged< JSArray > source, Tagged< JSTypedArray > destination, size_t length, size_t offset)
static Tagged< Object > CopyElementsHandleSlow (DirectHandle< JSAny > source, DirectHandle< JSTypedArray > destination, size_t length, size_t offset)
static Tagged< Object > CopyElementsHandleImpl (Isolate *isolate, DirectHandle< JSAny > source, DirectHandle< JSObject > destination, size_t length, size_t offset)
Additional Inherited Members
Detailed Description
template<ElementsKind Kind, typename ElementType>
class v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >
Definition at line 3374 of file elements.cc.
Member Typedef Documentation
AccessorClass
template<ElementsKind Kind, typename ElementType >
using v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::AccessorClass = TypedElementsAccessor<Kind, ElementType>
Definition at line 3379 of file elements.cc.
BackingStore
template<ElementsKind Kind, typename ElementType >
using v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::BackingStore = typename ElementsKindTraits<Kind>::BackingStore
Definition at line 3378 of file elements.cc.
Member Function Documentation
AddElementsToKeyAccumulatorImpl()
template<ElementsKind Kind, typename ElementType >
static V8_WARN_UNUSED_RESULT ExceptionStatus v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::AddElementsToKeyAccumulatorImpl (DirectHandle< JSObject > receiver, KeyAccumulator * accumulator, AddKeyConversion convert) [inline], [static]
Definition at line 3601 of file elements.cc.
                                {
    Isolate* isolate = accumulator->isolate();
    DirectHandle<FixedArrayBase> elements(receiver->elements(), isolate);
    size_t length = AccessorClass::GetCapacityImpl(*receiver, *elements);
    for (size_t i = 0; i < length; i++) {
      DirectHandle<Object> value =
          AccessorClass::GetInternalImpl(isolate, receiver, InternalIndex(i));
      RETURN_FAILURE_IF_NOT_SUCCESSFUL(accumulator->AddKey(value, convert));
    }
    return ExceptionStatus::kSuccess;
  }
References v8::internal::KeyAccumulator::AddKey(), v8::internal::KeyAccumulator::isolate(), v8::internal::kSuccess, v8::internal::length, RETURN_FAILURE_IF_NOT_SUCCESSFUL, and v8::internal::value.
CollectValuesOrEntriesImpl()
template<ElementsKind Kind, typename ElementType >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CollectValuesOrEntriesImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArray > values_or_entries, bool get_entries, int * nof_items, PropertyFilter filter) [inline], [static]
Definition at line 3615 of file elements.cc.
                                             {
    int count = 0;
    if ((filter & ONLY_CONFIGURABLE) == 0) {
      DirectHandle<FixedArrayBase> elements(object->elements(), isolate);
      size_t length = AccessorClass::GetCapacityImpl(*object, *elements);
      for (size_t index = 0; index < length; ++index) {
        DirectHandle<Object> value = AccessorClass::GetInternalImpl(
            isolate, object, InternalIndex(index));
        if (get_entries) {
          value = MakeEntryPair(isolate, index, value);
        }
        values_or_entries->set(count++, *value);
      }
    }
    *nof_items = count;
    return Just(true);
  }
References v8::internal::index, v8::Just(), v8::internal::length, v8::internal::MakeEntryPair(), v8::internal::ONLY_CONFIGURABLE, and v8::internal::value.
CopyBetweenBackingStores()
template<ElementsKind Kind, typename ElementType >
template<ElementsKind SourceKind, typename SourceElementType >
static void v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CopyBetweenBackingStores (SourceElementType * source_data_ptr, ElementType * dest_data_ptr, size_t length, IsSharedBuffer is_shared) [inline], [static]
Definition at line 3993 of file elements.cc.
                                                                 {
    CopyBetweenBackingStoresImpl<Kind, ElementType, SourceKind,
                                 SourceElementType>::Copy(source_data_ptr,
                                                          dest_data_ptr, length,
                                                          is_shared);
  }
References v8::bigint::anonymous_namespace{div-helpers.cc}::Copy(), v8::internal::is_shared, and v8::internal::length.
CopyElementsFromTypedArray()
template<ElementsKind Kind, typename ElementType >
static void v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CopyElementsFromTypedArray (Tagged< JSTypedArray > source, Tagged< JSTypedArray > destination, size_t length, size_t offset) [inline], [static]
Definition at line 4003 of file elements.cc.
                                                                       {
    // The source is a typed array, so we know we don't need to do ToNumber
    // side-effects, as the source elements will always be a number.
    DisallowGarbageCollection no_gc;
    CHECK(!source->IsDetachedOrOutOfBounds());
    CHECK(!destination->IsDetachedOrOutOfBounds());
    DCHECK_LE(offset, destination->GetLength());
    DCHECK_LE(length, destination->GetLength() - offset);
    DCHECK_LE(length, source->GetLength());
    ExternalArrayType source_type = source->type();
    ExternalArrayType destination_type = destination->type();
    bool same_type = source_type == destination_type;
    bool same_size = source->element_size() == destination->element_size();
    bool both_are_simple = HasSimpleRepresentation(source_type) &&
                           HasSimpleRepresentation(destination_type);
    uint8_t* source_data = static_cast<uint8_t*>(source->DataPtr());
    uint8_t* dest_data = static_cast<uint8_t*>(destination->DataPtr());
    size_t source_byte_length = source->GetByteLength();
    size_t dest_byte_length = destination->GetByteLength();
    bool source_shared = source->buffer()->is_shared();
    bool destination_shared = destination->buffer()->is_shared();
    // We can simply copy the backing store if the types are the same, or if
    // we are converting e.g. Uint8 <-> Int8, as the binary representation
    // will be the same. This is not the case for floats or clamped Uint8,
    // which have special conversion operations.
    if (same_type || (same_size && both_are_simple)) {
      size_t element_size = source->element_size();
      if (source_shared || destination_shared) {
        base::Relaxed_Memcpy(
            reinterpret_cast<base::Atomic8*>(dest_data + offset * element_size),
            reinterpret_cast<base::Atomic8*>(source_data),
            length * element_size);
      } else {
        std::memmove(dest_data + offset * element_size, source_data,
                     length * element_size);
      }
    } else {
      std::unique_ptr<uint8_t[]> cloned_source_elements;
      // If the typedarrays are overlapped, clone the source.
      if (dest_data + dest_byte_length > source_data &&
          source_data + source_byte_length > dest_data) {
        cloned_source_elements.reset(new uint8_t[source_byte_length]);
        if (source_shared) {
          base::Relaxed_Memcpy(
              reinterpret_cast<base::Atomic8*>(cloned_source_elements.get()),
              reinterpret_cast<base::Atomic8*>(source_data),
              source_byte_length);
        } else {
          std::memcpy(cloned_source_elements.get(), source_data,
                      source_byte_length);
        }
        source_data = cloned_source_elements.get();
      }
      switch (source->GetElementsKind()) {
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) \
  case TYPE##_ELEMENTS: \
    CopyBetweenBackingStores<TYPE##_ELEMENTS, ctype>(\
        reinterpret_cast<ctype*>(source_data), \
        reinterpret_cast<ElementType*>(dest_data) + offset, length, \
        source_shared || destination_shared ? kShared : kUnshared); \
    break;
        TYPED_ARRAYS(TYPED_ARRAY_CASE)
        RAB_GSAB_TYPED_ARRAYS(TYPED_ARRAY_CASE)
        default:
          UNREACHABLE();
          break;
      }
#undef TYPED_ARRAY_CASE
    }
  }
References CHECK, DCHECK_LE, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, RAB_GSAB_TYPED_ARRAYS, v8::base::Relaxed_Memcpy(), TYPED_ARRAY_CASE, TYPED_ARRAYS, and v8::internal::UNREACHABLE().
CopyElementsHandleImpl()
template<ElementsKind Kind, typename ElementType >
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CopyElementsHandleImpl (Isolate * isolate, DirectHandle< JSAny > source, DirectHandle< JSObject > destination, size_t length, size_t offset) [inline], [static]
Definition at line 4267 of file elements.cc.
                                                                        {
    if (length == 0) return *isolate->factory()->undefined_value();
    DirectHandle<JSTypedArray> destination_ta = Cast<JSTypedArray>(destination);
    // All conversions from TypedArrays can be done without allocation.
    if (IsJSTypedArray(*source)) {
      CHECK(!destination_ta->WasDetached());
      bool out_of_bounds = false;
      CHECK_LE(offset + length,
               destination_ta->GetLengthOrOutOfBounds(out_of_bounds));
      CHECK(!out_of_bounds);
      auto source_ta = Cast<JSTypedArray>(source);
      ElementsKind source_kind = source_ta->GetElementsKind();
      bool source_is_bigint = IsBigIntTypedArrayElementsKind(source_kind);
      bool target_is_bigint = IsBigIntTypedArrayElementsKind(Kind);
      // If we have to copy more elements than we have in the source, we need to
      // do special handling and conversion; that happens in the slow case.
      if (source_is_bigint == target_is_bigint && !source_ta->WasDetached() &&
          length + offset <= source_ta->GetLength()) {
        CopyElementsFromTypedArray(*source_ta, *destination_ta, length, offset);
        return *isolate->factory()->undefined_value();
      }
    } else if (IsJSArray(*source)) {
      CHECK(!destination_ta->WasDetached());
      bool out_of_bounds = false;
      CHECK_LE(offset + length,
               destination_ta->GetLengthOrOutOfBounds(out_of_bounds));
      CHECK(!out_of_bounds);
      // Fast cases for packed numbers kinds where we don't need to allocate.
      auto source_js_array = Cast<JSArray>(source);
      size_t current_length;
      DCHECK(IsNumber(source_js_array->length()));
      if (TryNumberToSize(source_js_array->length(), &current_length) &&
          length <= current_length) {
        auto source_array = Cast<JSArray>(source);
        if (TryCopyElementsFastNumber(isolate->context(), *source_array,
                                      *destination_ta, length, offset)) {
          return *isolate->factory()->undefined_value();
        }
      }
    }
    // Final generic case that handles prototype chain lookups, getters, proxies
    // and observable side effects via valueOf, etc. In this case, it's possible
    // that the length getter detached / resized the underlying buffer.
    return CopyElementsHandleSlow(source, destination_ta, length, offset);
  }
References CHECK, CHECK_LE, v8::internal::Isolate::context(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::GetLength(), v8::internal::IsBigIntTypedArrayElementsKind(), v8::internal::IsNumber(), v8::internal::length, and v8::internal::TryNumberToSize().
CopyElementsHandleSlow()
template<ElementsKind Kind, typename ElementType >
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CopyElementsHandleSlow (DirectHandle< JSAny > source, DirectHandle< JSTypedArray > destination, size_t length, size_t offset) [inline], [static]
Definition at line 4216 of file elements.cc.
                                    {
    Isolate* isolate = Isolate::Current();
    // 8. Let k be 0.
    // 9. Repeat, while k < srcLength,
    for (size_t i = 0; i < length; i++) {
      DirectHandle<Object> elem;
      // a. Let Pk be ! ToString((k)).
      // b. Let value be ? Get(src, Pk).
      LookupIterator it(isolate, source, i);
      ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, elem,
                                         Object::GetProperty(&it));
      // c. Let targetIndex be (targetOffset + k).
      // d. Perform ? IntegerIndexedElementSet(target, targetIndex, value).
      //
      // Rest of loop body inlines ES#IntegerIndexedElementSet
      if (IsBigIntTypedArrayElementsKind(Kind)) {
        // 1. If O.[[ContentType]] is BigInt, let numValue be ? ToBigInt(value).
        ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, elem,
                                           BigInt::FromObject(isolate, elem));
      } else {
        // 2. Otherwise, let numValue be ? ToNumber(value).
        ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, elem,
                                           Object::ToNumber(isolate, elem));
      }
      // 3. If IsValidIntegerIndex(O, index) is true, then
      // a. Let offset be O.[[ByteOffset]].
      // b. Let elementSize be TypedArrayElementSize(O).
      // c. Let indexedPosition be ((index) elementSize) + offset.
      // d. Let elementType be TypedArrayElementType(O).
      // e. Perform SetValueInBuffer(O.[[ViewedArrayBuffer]],
      // indexedPosition, elementType, numValue, true, Unordered).
      bool out_of_bounds = false;
      size_t new_length = destination->GetLengthOrOutOfBounds(out_of_bounds);
      if (V8_UNLIKELY(out_of_bounds || destination->WasDetached() ||
                      new_length <= offset + i)) {
        // Proceed with the loop so that we call get getters for the source even
        // though we don't set the values in the target.
        continue;
      }
      SetImpl(destination, InternalIndex(offset + i), *elem);
      // e. Set k to k + 1.
    }
    // 10. Return unused.
    return *isolate->factory()->undefined_value();
  }
References ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::Object::GetProperty(), v8::internal::IsBigIntTypedArrayElementsKind(), v8::internal::length, v8::Value::ToNumber(), and V8_UNLIKELY.
CopyTypedArrayElementsSliceImpl()
template<ElementsKind Kind, typename ElementType >
static void v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CopyTypedArrayElementsSliceImpl (Tagged< JSTypedArray > source, Tagged< JSTypedArray > destination, size_t start, size_t end) [inline], [static]
Definition at line 3943 of file elements.cc.
                                                                        {
    DisallowGarbageCollection no_gc;
    DCHECK_EQ(destination->GetElementsKind(), AccessorClass::kind());
    CHECK(!source->IsDetachedOrOutOfBounds());
    CHECK(!destination->IsDetachedOrOutOfBounds());
    DCHECK_LE(start, end);
    DCHECK_LE(end, source->GetLength());
    size_t count = end - start;
    DCHECK_LE(count, destination->GetLength());
    ElementType* dest_data = static_cast<ElementType*>(destination->DataPtr());
    auto is_shared =
        source->buffer()->is_shared() || destination->buffer()->is_shared()
            ? kShared
            : kUnshared;
    switch (source->GetElementsKind()) {
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) \
  case TYPE##_ELEMENTS: { \
    ctype* source_data = reinterpret_cast<ctype*>(source->DataPtr()) + start; \
    CopyBetweenBackingStores<TYPE##_ELEMENTS, ctype>(source_data, dest_data, \
                                                     count, is_shared); \
    break; \
  }
      TYPED_ARRAYS(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype, NON_RAB_GSAB_TYPE) \
  case TYPE##_ELEMENTS: { \
    ctype* source_data = reinterpret_cast<ctype*>(source->DataPtr()) + start; \
    CopyBetweenBackingStores<NON_RAB_GSAB_TYPE##_ELEMENTS, ctype>(\
        source_data, dest_data, count, is_shared); \
    break; \
  }
      RAB_GSAB_TYPED_ARRAYS_WITH_NON_RAB_GSAB_ELEMENTS_KIND(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
      default:
        UNREACHABLE();
        break;
    }
  }
References CHECK, DCHECK_EQ, DCHECK_LE, v8::internal::compiler::end(), v8::internal::is_shared, v8::internal::anonymous_namespace{elements.cc}::kShared, v8::internal::anonymous_namespace{elements.cc}::kUnshared, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, RAB_GSAB_TYPED_ARRAYS_WITH_NON_RAB_GSAB_ELEMENTS_KIND, TYPED_ARRAY_CASE, TYPED_ARRAYS, and v8::internal::UNREACHABLE().
CreateListFromArrayLikeImpl()
template<ElementsKind Kind, typename ElementType >
static Handle<FixedArray> v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CreateListFromArrayLikeImpl (Isolate * isolate, DirectHandle< JSObject > object, uint32_t length) [inline], [static]
Definition at line 3931 of file elements.cc.
                                                                        {
    DirectHandle<JSTypedArray> typed_array = Cast<JSTypedArray>(object);
    Handle<FixedArray> result = isolate->factory()->NewFixedArray(length);
    for (uint32_t i = 0; i < length; i++) {
      DirectHandle<Object> value = AccessorClass::GetInternalImpl(
          isolate, typed_array, InternalIndex(i));
      result->set(i, *value);
    }
    return result;
  }
References v8::internal::Isolate::factory(), v8::internal::length, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::base::internal::result, and v8::internal::value.
DeleteImpl()
template<ElementsKind Kind, typename ElementType >
static void v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::DeleteImpl (Isolate * isolate, DirectHandle< JSObject > obj, InternalIndex entry) [inline], [static]
Definition at line 3572 of file elements.cc.
                                              {
    // Do nothing.
    //
    // TypedArray elements are configurable to explain detaching, but cannot be
    // deleted otherwise.
  }
FillImpl()
template<ElementsKind Kind, typename ElementType >
static MaybeDirectHandle<Object> v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::FillImpl (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start, size_t end) [inline], [static]
Definition at line 3656 of file elements.cc.
                                                                      {
    DirectHandle<JSTypedArray> typed_array = Cast<JSTypedArray>(receiver);
    DCHECK(!typed_array->IsDetachedOrOutOfBounds());
    DCHECK_LE(start, end);
    DCHECK_LE(end, typed_array->GetLength());
    DisallowGarbageCollection no_gc;
    ElementType scalar = FromHandle(value);
    ElementType* data = static_cast<ElementType*>(typed_array->DataPtr());
    ElementType* first = data + start;
    ElementType* last = data + end;
    if (typed_array->buffer()->is_shared()) {
      // TypedArrays backed by shared buffers need to be filled using atomic
      // operations. Since 8-byte data are not currently always 8-byte aligned,
      // manually fill using SetImpl, which abstracts over alignment and atomic
      // complexities.
      for (; first != last; ++first) {
        AccessorClass::SetImpl(first, scalar, kShared);
      }
    } else if ((scalar == 0 && !(std::is_floating_point_v<ElementType> &&
                                 IsMinusZero(scalar))) ||
               (std::is_integral_v<ElementType> &&
                scalar == static_cast<ElementType>(-1))) {
      // As of 2022-06, this is faster than {std::fill}.
      // We could extend this to any {scalar} that's a pattern of repeating
      // bytes, but patterns other than 0 and -1 are probably rare.
      size_t num_bytes = static_cast<size_t>(reinterpret_cast<int8_t*>(last) -
                                             reinterpret_cast<int8_t*>(first));
      memset(first, static_cast<int8_t>(scalar), num_bytes);
    } else if (COMPRESS_POINTERS_BOOL && alignof(ElementType) > kTaggedSize) {
      // TODO(ishell, v8:8875): See UnalignedSlot<T> for details.
      std::fill(UnalignedSlot<ElementType>(first),
                UnalignedSlot<ElementType>(last), scalar);
    } else {
      std::fill(first, last, scalar);
    }
    return MaybeDirectHandle<Object>(typed_array);
  }
References COMPRESS_POINTERS_BOOL, v8::internal::DCHECK(), DCHECK_LE, v8::internal::compiler::end(), v8::internal::IsMinusZero(), v8::internal::anonymous_namespace{elements.cc}::kShared, v8::internal::kTaggedSize, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::value.
FromHandle()
template<ElementsKind Kind, typename ElementType >
static ElementType v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::FromHandle (DirectHandle< Object > value, bool * lossless = nullptr) [inline], [static]
Definition at line 3408 of file elements.cc.
                                                          {
    return FromObject(*value, lossless);
  }
References v8::internal::value.
FromObject() [1/5]
int64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< BIGINT64_ELEMENTS, int64_t >::FromObject (Tagged< Object > value, bool * lossless)
Definition at line 4558 of file elements.cc.
                                          {
  return Cast<BigInt>(value)->AsInt64(lossless);
}
References v8::internal::value.
FromObject() [2/5]
uint64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< BIGUINT64_ELEMENTS, uint64_t >::FromObject (Tagged< Object > value, bool * lossless)
Definition at line 4607 of file elements.cc.
                                          {
  return Cast<BigInt>(value)->AsUint64(lossless);
}
References v8::internal::value.
FromObject() [3/5]
int64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_BIGINT64_ELEMENTS, int64_t >::FromObject (Tagged< Object > value, bool * lossless)
Definition at line 4799 of file elements.cc.
                                          {
  return Cast<BigInt>(value)->AsInt64(lossless);
}
References v8::internal::value.
FromObject() [4/5]
uint64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_BIGUINT64_ELEMENTS, uint64_t >::FromObject (Tagged< Object > value, bool * lossless)
Definition at line 4850 of file elements.cc.
                                                                     {
  return Cast<BigInt>(value)->AsUint64(lossless);
}
References v8::internal::value.
FromObject() [5/5]
template<ElementsKind Kind, typename ElementType >
static ElementType v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::FromObject (Tagged< Object > value, bool * lossless = nullptr) [inline], [static]
Definition at line 3395 of file elements.cc.
                                                          {
    if (IsSmi(value)) {
      return FromScalar(Smi::ToInt(value));
    } else if (IsHeapNumber(value)) {
      return FromScalar(Cast<HeapNumber>(value)->value());
    } else {
      // Clamp undefined here as well. All other types have been
      // converted to a number type further up in the call chain.
      DCHECK(IsUndefined(value));
      return FromScalar(Cast<Oddball>(value)->to_number_raw());
    }
  }
References v8::internal::DCHECK(), v8::internal::IsSmi(), v8::internal::Smi::ToInt(), and v8::internal::value.
FromScalar() [1/41]
template<ElementsKind Kind, typename ElementType >
static ElementType v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::FromScalar (double value) [inline], [static]
Definition at line 3388 of file elements.cc.
                                              {
    return FromScalar(DoubleToInt32(value));
  }
References v8::internal::DoubleToInt32(), and v8::internal::value.
FromScalar() [2/41]
uint16_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< FLOAT16_ELEMENTS, uint16_t >::FromScalar (double value)
Definition at line 4432 of file elements.cc.
                  {
  return DoubleToFloat16(value);
}
References v8::internal::DoubleToFloat16(), and v8::internal::value.
FromScalar() [3/41]
float v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< FLOAT32_ELEMENTS, float >::FromScalar (double value)
Definition at line 4439 of file elements.cc.
                                                                             {
  return DoubleToFloat32(value);
}
References v8::internal::DoubleToFloat32(), and v8::internal::value.
FromScalar() [4/41]
double v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< FLOAT64_ELEMENTS, double >::FromScalar (double value)
Definition at line 4473 of file elements.cc.
                  {
  return value;
}
References v8::internal::value.
FromScalar() [5/41]
uint8_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< UINT8_CLAMPED_ELEMENTS, uint8_t >::FromScalar (double value)
Definition at line 4506 of file elements.cc.
                  {
  // Handle NaNs and less than zero values which clamp to zero.
  if (!(value > 0)) return 0;
  if (value > 0xFF) return 0xFF;
  return static_cast<uint8_t>(lrint(value));
}
References v8::internal::value.
FromScalar() [6/41]
int64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< BIGINT64_ELEMENTS, int64_t >::FromScalar (double value)
Definition at line 4537 of file elements.cc.
                  {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
FromScalar() [7/41]
uint64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< BIGUINT64_ELEMENTS, uint64_t >::FromScalar (double value)
Definition at line 4586 of file elements.cc.
                  {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
FromScalar() [8/41]
uint16_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_FLOAT16_ELEMENTS, uint16_t >::FromScalar (double value)
Definition at line 4668 of file elements.cc.
                  {
  return DoubleToFloat16(value);
}
References v8::internal::DoubleToFloat16(), and v8::internal::value.
FromScalar() [9/41]
float v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_FLOAT32_ELEMENTS, float >::FromScalar (double value)
Definition at line 4697 of file elements.cc.
                  {
  return DoubleToFloat32(value);
}
References v8::internal::DoubleToFloat32(), and v8::internal::value.
FromScalar() [10/41]
double v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_FLOAT64_ELEMENTS, double >::FromScalar (double value)
Definition at line 4712 of file elements.cc.
                  {
  return value;
}
References v8::internal::value.
FromScalar() [11/41]
uint8_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_UINT8_CLAMPED_ELEMENTS, uint8_t >::FromScalar (double value)
Definition at line 4747 of file elements.cc.
                                                               {
  // Handle NaNs and less than zero values which clamp to zero.
  if (!(value > 0)) return 0;
  if (value > 0xFF) return 0xFF;
  return static_cast<uint8_t>(lrint(value));
}
References v8::internal::value.
FromScalar() [12/41]
int64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_BIGINT64_ELEMENTS, int64_t >::FromScalar (double value)
Definition at line 4778 of file elements.cc.
                  {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
FromScalar() [13/41]
uint64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_BIGUINT64_ELEMENTS, uint64_t >::FromScalar (double value)
Definition at line 4829 of file elements.cc.
                                                                 {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
FromScalar() [14/41]
template<ElementsKind Kind, typename ElementType >
static ElementType v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::FromScalar (int value) [inline], [static]
Definition at line 3382 of file elements.cc.
                                           {
    return static_cast<ElementType>(value);
  }
References v8::internal::value.
FromScalar() [15/41]
uint16_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< FLOAT16_ELEMENTS, uint16_t >::FromScalar (int value)
Definition at line 4445 of file elements.cc.
               {
  return fp16_ieee_from_fp32_value(value);
}
References v8::internal::value.
FromScalar() [16/41]
uint8_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< UINT8_CLAMPED_ELEMENTS, uint8_t >::FromScalar (int value)
Definition at line 4487 of file elements.cc.
               {
  if (value < 0x00) return 0x00;
  if (value > 0xFF) return 0xFF;
  return static_cast<uint8_t>(value);
}
References v8::internal::value.
FromScalar() [17/41]
int64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< BIGINT64_ELEMENTS, int64_t >::FromScalar (int value)
Definition at line 4523 of file elements.cc.
               {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
FromScalar() [18/41]
uint64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< BIGUINT64_ELEMENTS, uint64_t >::FromScalar (int value)
Definition at line 4572 of file elements.cc.
               {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
FromScalar() [19/41]
uint16_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_FLOAT16_ELEMENTS, uint16_t >::FromScalar (int value)
Definition at line 4675 of file elements.cc.
               {
  return fp16_ieee_from_fp32_value(value);
}
References v8::internal::value.
FromScalar() [20/41]
uint8_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_UINT8_CLAMPED_ELEMENTS, uint8_t >::FromScalar (int value)
Definition at line 4728 of file elements.cc.
                                                            {
  if (value < 0x00) return 0x00;
  if (value > 0xFF) return 0xFF;
  return static_cast<uint8_t>(value);
}
References v8::internal::value.
FromScalar() [21/41]
int64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_BIGINT64_ELEMENTS, int64_t >::FromScalar (int value)
Definition at line 4764 of file elements.cc.
               {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
FromScalar() [22/41]
uint64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_BIGUINT64_ELEMENTS, uint64_t >::FromScalar (int value)
Definition at line 4815 of file elements.cc.
                                                              {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
FromScalar() [23/41]
template<ElementsKind Kind, typename ElementType >
static ElementType v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::FromScalar (int64_t value) [inline], [static]
Definition at line 3391 of file elements.cc.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
FromScalar() [24/41]
int64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< BIGINT64_ELEMENTS, int64_t >::FromScalar (int64_t value)
Definition at line 4544 of file elements.cc.
                   {
  return value;
}
References v8::internal::value.
FromScalar() [25/41]
uint64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< BIGUINT64_ELEMENTS, uint64_t >::FromScalar (int64_t value)
Definition at line 4593 of file elements.cc.
                   {
  return static_cast<uint64_t>(value);
}
References v8::internal::value.
FromScalar() [26/41]
int64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_BIGINT64_ELEMENTS, int64_t >::FromScalar (int64_t value)
Definition at line 4785 of file elements.cc.
                   {
  return value;
}
References v8::internal::value.
FromScalar() [27/41]
uint64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_BIGUINT64_ELEMENTS, uint64_t >::FromScalar (int64_t value)
Definition at line 4836 of file elements.cc.
                                                                  {
  return static_cast<uint64_t>(value);
}
References v8::internal::value.
FromScalar() [28/41]
template<ElementsKind Kind, typename ElementType >
static ElementType v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::FromScalar (uint32_t value) [inline], [static]
Definition at line 3385 of file elements.cc.
                                                {
    return static_cast<ElementType>(value);
  }
References v8::internal::value.
FromScalar() [29/41]
uint16_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< FLOAT16_ELEMENTS, uint16_t >::FromScalar (uint32_t value)
Definition at line 4452 of file elements.cc.
                    {
  return fp16_ieee_from_fp32_value(value);
}
References v8::internal::value.
FromScalar() [30/41]
uint8_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< UINT8_CLAMPED_ELEMENTS, uint8_t >::FromScalar (uint32_t value)
Definition at line 4496 of file elements.cc.
                    {
  // We need this special case for Uint32 -> Uint8Clamped, because the highest
  // Uint32 values will be negative as an int, clamping to 0, rather than 255.
  if (value > 0xFF) return 0xFF;
  return static_cast<uint8_t>(value);
}
References v8::internal::value.
FromScalar() [31/41]
int64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< BIGINT64_ELEMENTS, int64_t >::FromScalar (uint32_t value)
Definition at line 4530 of file elements.cc.
                    {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
FromScalar() [32/41]
uint64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< BIGUINT64_ELEMENTS, uint64_t >::FromScalar (uint32_t value)
Definition at line 4579 of file elements.cc.
                    {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
FromScalar() [33/41]
uint16_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_FLOAT16_ELEMENTS, uint16_t >::FromScalar (uint32_t value)
Definition at line 4682 of file elements.cc.
                    {
  return fp16_ieee_from_fp32_value(value);
}
References v8::internal::value.
FromScalar() [34/41]
uint8_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_UINT8_CLAMPED_ELEMENTS, uint8_t >::FromScalar (uint32_t value)
Definition at line 4737 of file elements.cc.
                                                                 {
  // We need this special case for Uint32 -> Uint8Clamped, because the highest
  // Uint32 values will be negative as an int, clamping to 0, rather than 255.
  if (value > 0xFF) return 0xFF;
  return static_cast<uint8_t>(value);
}
References v8::internal::value.
FromScalar() [35/41]
int64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_BIGINT64_ELEMENTS, int64_t >::FromScalar (uint32_t value)
Definition at line 4771 of file elements.cc.
                    {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
FromScalar() [36/41]
uint64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_BIGUINT64_ELEMENTS, uint64_t >::FromScalar (uint32_t value)
Definition at line 4822 of file elements.cc.
                                                                   {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
FromScalar() [37/41]
template<ElementsKind Kind, typename ElementType >
static ElementType v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::FromScalar (uint64_t value) [inline], [static]
Definition at line 3392 of file elements.cc.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
FromScalar() [38/41]
int64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< BIGINT64_ELEMENTS, int64_t >::FromScalar (uint64_t value)
Definition at line 4551 of file elements.cc.
                    {
  return static_cast<int64_t>(value);
}
References v8::internal::value.
FromScalar() [39/41]
uint64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< BIGUINT64_ELEMENTS, uint64_t >::FromScalar (uint64_t value)
Definition at line 4600 of file elements.cc.
                    {
  return value;
}
References v8::internal::value.
FromScalar() [40/41]
int64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_BIGINT64_ELEMENTS, int64_t >::FromScalar (uint64_t value)
Definition at line 4792 of file elements.cc.
                    {
  return static_cast<int64_t>(value);
}
References v8::internal::value.
FromScalar() [41/41]
uint64_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_BIGUINT64_ELEMENTS, uint64_t >::FromScalar (uint64_t value)
Definition at line 4843 of file elements.cc.
                                                                   {
  return value;
}
References v8::internal::value.
GetCapacityImpl()
template<ElementsKind Kind, typename ElementType >
static size_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::GetCapacityImpl (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store) [inline], [static]
Definition at line 3589 of file elements.cc.
                                                                      {
    Tagged<JSTypedArray> typed_array = Cast<JSTypedArray>(holder);
    return typed_array->GetLength();
  }
GetDetailsImpl() [1/2]
template<ElementsKind Kind, typename ElementType >
static PropertyDetails v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::GetDetailsImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry) [inline], [static]
Definition at line 3548 of file elements.cc.
                                                             {
    return PropertyDetails(PropertyKind::kData, NONE,
                           PropertyCellType::kNoCell);
  }
References v8::internal::kData, v8::internal::kNoCell, and v8::internal::NONE.
GetDetailsImpl() [2/2]
template<ElementsKind Kind, typename ElementType >
static PropertyDetails v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::GetDetailsImpl (Tagged< JSObject > holder, InternalIndex entry) [inline], [static]
Definition at line 3542 of file elements.cc.
                                                             {
    return PropertyDetails(PropertyKind::kData, NONE,
                           PropertyCellType::kNoCell);
  }
References v8::internal::kData, v8::internal::kNoCell, and v8::internal::NONE.
GetEntryForIndexImpl()
template<ElementsKind Kind, typename ElementType >
static InternalIndex v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::GetEntryForIndexImpl (Isolate * isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store, size_t index, PropertyFilter filter) [inline], [static]
Definition at line 3580 of file elements.cc.
                             {
    return index < AccessorClass::GetCapacityImpl(holder, backing_store)
               ? InternalIndex(index)
               : InternalIndex::NotFound();
  }
References v8::internal::index, and v8::internal::InternalIndex::NotFound().
GetImpl() [1/2]
template<ElementsKind Kind, typename ElementType >
static ElementType v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::GetImpl (ElementType * data_ptr, IsSharedBuffer is_shared) [inline], [static]
Definition at line 3492 of file elements.cc.
                                                                              {
    // TODO(ishell, v8:8875): Independent of pointer compression, 8-byte size
    // fields (external pointers, doubles and BigInt data) are not always
    // 8-byte aligned.
    if (!is_shared) {
      return base::ReadUnalignedValue<ElementType>(
          reinterpret_cast<Address>(data_ptr));
    }
    // The JavaScript memory model allows for racy reads and writes to a
    // SharedArrayBuffer's backing store. Using relaxed atomics is not strictly
    // required for JavaScript, but will avoid undefined behaviour in C++ and is
    // unlikely to introduce noticeable overhead.
    if (IsAligned(reinterpret_cast<uintptr_t>(data_ptr),
                  alignof(std::atomic<ElementType>))) {
      // Use a single relaxed atomic load.
      static_assert(sizeof(std::atomic<ElementType>) == sizeof(ElementType));
      // Note: acquire semantics are not needed here, but clang seems to merge
      // this atomic load with the non-atomic load above if we use relaxed
      // semantics. This will result in TSan failures.
      return reinterpret_cast<std::atomic<ElementType>*>(data_ptr)->load(
          std::memory_order_acquire);
    }
    // Some static CHECKs (are optimized out if succeeding) to ensure that
    // {data_ptr} is at least four byte aligned, and {std::atomic<uint32_t>}
    // has size and alignment of four bytes, such that we can cast the
    // {data_ptr} to it.
    CHECK_LE(kInt32Size, alignof(ElementType));
    CHECK_EQ(kInt32Size, alignof(std::atomic<uint32_t>));
    CHECK_EQ(kInt32Size, sizeof(std::atomic<uint32_t>));
    // And dynamically check that we indeed have at least four byte alignment.
    DCHECK(IsAligned(reinterpret_cast<uintptr_t>(data_ptr), kInt32Size));
    // Load in multiple 32-bit words. Make {kNumWords} >= 1 to avoid compiler
    // warnings for the empty array or memcpy to an empty object.
    constexpr size_t kNumWords =
        std::max(size_t{1}, sizeof(ElementType) / kInt32Size);
    uint32_t words[kNumWords];
    for (size_t word = 0; word < kNumWords; ++word) {
      static_assert(sizeof(std::atomic<uint32_t>) == sizeof(uint32_t));
      words[word] =
          reinterpret_cast<std::atomic<uint32_t>*>(data_ptr)[word].load(
              std::memory_order_relaxed);
    }
    ElementType result;
    CHECK_EQ(sizeof(words), sizeof(result));
    memcpy(&result, words, sizeof(result));
    return result;
  }
References CHECK_EQ, CHECK_LE, v8::internal::DCHECK(), v8::internal::is_shared, IsAligned(), v8::internal::kInt32Size, and v8::base::internal::result.
GetImpl() [2/2]
template<ElementsKind Kind, typename ElementType >
static DirectHandle<Object> v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::GetImpl (Isolate * isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry) [inline], [static]
Definition at line 3486 of file elements.cc.
                                                           {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
GetInternalImpl()
template<ElementsKind Kind, typename ElementType >
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::GetInternalImpl (Isolate * isolate, DirectHandle< JSObject > holder, InternalIndex entry) [inline], [static]
Definition at line 3473 of file elements.cc.
                                                             {
    auto typed_array = Cast<JSTypedArray>(holder);
    DCHECK_LT(entry.raw_value(), typed_array->GetLength());
    DCHECK(!typed_array->IsDetachedOrOutOfBounds());
    auto* element_ptr =
        static_cast<ElementType*>(typed_array->DataPtr()) + entry.raw_value();
    auto is_shared = typed_array->buffer()->is_shared() ? kShared : kUnshared;
    ElementType elem = GetImpl(element_ptr, is_shared);
    return ToHandle(isolate, elem);
  }
References v8::internal::DCHECK(), DCHECK_LT, v8::internal::is_shared, v8::internal::anonymous_namespace{elements.cc}::kShared, v8::internal::anonymous_namespace{elements.cc}::kUnshared, v8::internal::InternalIndex::raw_value(), and v8::anonymous_namespace{api.cc}::ToHandle().
HasAccessorsImpl()
template<ElementsKind Kind, typename ElementType >
static bool v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::HasAccessorsImpl (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store) [inline], [static]
Definition at line 3560 of file elements.cc.
                                                                     {
    return false;
  }
HasElementImpl()
template<ElementsKind Kind, typename ElementType >
static bool v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::HasElementImpl (Isolate * isolate, Tagged< JSObject > holder, size_t index, Tagged< FixedArrayBase > backing_store, PropertyFilter filter) [inline], [static]
Definition at line 3554 of file elements.cc.
                                                    {
    return index < AccessorClass::GetCapacityImpl(holder, backing_store);
  }
References v8::internal::index.
HasSimpleRepresentation()
template<ElementsKind Kind, typename ElementType >
static bool v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::HasSimpleRepresentation (ExternalArrayType type) [inline], [static]
Definition at line 3986 of file elements.cc.
                                                              {
    return !(type == kExternalFloat32Array || type == kExternalFloat64Array ||
             type == kExternalUint8ClampedArray ||
             type == kExternalFloat16Array);
  }
References v8::internal::kExternalFloat16Array, v8::internal::kExternalFloat32Array, v8::internal::kExternalFloat64Array, v8::internal::kExternalUint8ClampedArray, and v8::internal::tracing::type.
HoleyPrototypeLookupRequired()
template<ElementsKind Kind, typename ElementType >
static bool v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::HoleyPrototypeLookupRequired (Isolate * isolate, Tagged< Context > context, Tagged< JSArray > source) [inline], [static]
Definition at line 4085 of file elements.cc.
                                                                   {
    DisallowGarbageCollection no_gc;
    DisallowJavascriptExecution no_js(isolate);
#ifdef V8_ENABLE_FORCE_SLOW_PATH
    if (isolate->force_slow_path()) return true;
#endif
    Tagged<Object> source_proto = source->map()->prototype();
    // Null prototypes are OK - we don't need to do prototype chain lookups on
    // them.
    if (IsNull(source_proto, isolate)) return false;
    if (IsJSProxy(source_proto)) return true;
    if (IsJSObject(source_proto) &&
        !context->native_context()->is_initial_array_prototype(
            Cast<JSObject>(source_proto))) {
      return true;
    }
    return !Protectors::IsNoElementsIntact(isolate);
  }
References v8::internal::Isolate::force_slow_path(), v8::internal::IsNull(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
IncludesValueImpl()
template<ElementsKind Kind, typename ElementType >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::IncludesValueImpl (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length) [inline], [static]
Definition at line 3697 of file elements.cc.
                                                                         {
    DisallowGarbageCollection no_gc;
    Tagged<JSTypedArray> typed_array = Cast<JSTypedArray>(*receiver);
    bool out_of_bounds = false;
    size_t new_length = typed_array->GetLengthOrOutOfBounds(out_of_bounds);
    if (V8_UNLIKELY(out_of_bounds)) {
      return Just(IsUndefined(*value, isolate) && length > start_from);
    }
    // Prototype has no elements, and not searching for the hole --- limit
    // search to backing store length.
    if (new_length < length) {
      if (IsUndefined(*value, isolate) && length > start_from) {
        return Just(true);
      }
      length = new_length;
    }
    ElementType typed_search_value;
    ElementType* data_ptr =
        reinterpret_cast<ElementType*>(typed_array->DataPtr());
    auto is_shared = typed_array->buffer()->is_shared() ? kShared : kUnshared;
    if (Kind == BIGINT64_ELEMENTS || Kind == BIGUINT64_ELEMENTS ||
        Kind == RAB_GSAB_BIGINT64_ELEMENTS ||
        Kind == RAB_GSAB_BIGUINT64_ELEMENTS) {
      if (!IsBigInt(*value)) return Just(false);
      bool lossless;
      typed_search_value = FromHandle(value, &lossless);
      if (!lossless) return Just(false);
    } else {
      if (!IsNumber(*value)) return Just(false);
      double search_value = Object::NumberValue(*value);
      if (!std::isfinite(search_value)) {
        // Integral types cannot represent +Inf or NaN.
        if (!IsFloatTypedArrayElementsKind(Kind)) {
          return Just(false);
        }
        if (std::isnan(search_value)) {
          for (size_t k = start_from; k < length; ++k) {
            if (IsFloat16TypedArrayElementsKind(Kind)) {
              float elem_k = fp16_ieee_to_fp32_value(
                  AccessorClass::GetImpl(data_ptr + k, is_shared));
              if (std::isnan(elem_k)) return Just(true);
            } else {
              double elem_k = static_cast<double>(
                  AccessorClass::GetImpl(data_ptr + k, is_shared));
              if (std::isnan(elem_k)) return Just(true);
            }
          }
          return Just(false);
        }
      } else if (IsFloat16TypedArrayElementsKind(Kind) && search_value == 0) {
        for (size_t k = start_from; k < length; ++k) {
          ElementType elem_k = AccessorClass::GetImpl(data_ptr + k, is_shared);
          if (IsFloat16RawBitsZero(elem_k)) return Just(true);
        }
        return Just(false);
      }
      if (AccessorClass::ToTypedSearchValue(search_value,
                                            &typed_search_value)) {
        return Just(false);
      }
    }
    for (size_t k = start_from; k < length; ++k) {
      ElementType elem_k = AccessorClass::GetImpl(data_ptr + k, is_shared);
      if (elem_k == typed_search_value) return Just(true);
    }
    return Just(false);
  }
References v8::internal::is_shared, v8::internal::anonymous_namespace{elements.cc}::IsFloat16RawBitsZero(), v8::internal::IsFloat16TypedArrayElementsKind(), v8::internal::IsFloatTypedArrayElementsKind(), v8::internal::IsNumber(), v8::Just(), v8::internal::anonymous_namespace{elements.cc}::kShared, v8::internal::anonymous_namespace{elements.cc}::kUnshared, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::NumberValue(), V8_UNLIKELY, and v8::internal::value.
IndexOfValueImpl()
template<ElementsKind Kind, typename ElementType >
static Maybe<int64_t> v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::IndexOfValueImpl (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length) [inline], [static]
Definition at line 3773 of file elements.cc.
                                                                           {
    DisallowGarbageCollection no_gc;
    Tagged<JSTypedArray> typed_array = Cast<JSTypedArray>(*receiver);
    // If this is called via Array.prototype.indexOf (not
    // TypedArray.prototype.indexOf), it's possible that the TypedArray is
    // detached / out of bounds here.
    if (V8_UNLIKELY(typed_array->WasDetached())) return Just<int64_t>(-1);
    bool out_of_bounds = false;
    size_t typed_array_length =
        typed_array->GetLengthOrOutOfBounds(out_of_bounds);
    if (V8_UNLIKELY(out_of_bounds)) {
      return Just<int64_t>(-1);
    }
    // Prototype has no elements, and not searching for the hole --- limit
    // search to backing store length.
    if (typed_array_length < length) {
      length = typed_array_length;
    }
    auto is_shared = typed_array->buffer()->is_shared() ? kShared : kUnshared;
    ElementType typed_search_value;
    ElementType* data_ptr =
        reinterpret_cast<ElementType*>(typed_array->DataPtr());
    if (IsBigIntTypedArrayElementsKind(Kind)) {
      if (!IsBigInt(*value)) return Just<int64_t>(-1);
      bool lossless;
      typed_search_value = FromHandle(value, &lossless);
      if (!lossless) return Just<int64_t>(-1);
    } else {
      if (!IsNumber(*value)) return Just<int64_t>(-1);
      double search_value = Object::NumberValue(*value);
      if (!std::isfinite(search_value)) {
        // Integral types cannot represent +Inf or NaN.
        if (!IsFloatTypedArrayElementsKind(Kind)) {
          return Just<int64_t>(-1);
        }
        if (std::isnan(search_value)) {
          return Just<int64_t>(-1);
        }
      } else if (IsFloat16TypedArrayElementsKind(Kind) && search_value == 0) {
        for (size_t k = start_from; k < length; ++k) {
          ElementType elem_k = AccessorClass::GetImpl(data_ptr + k, is_shared);
          if (IsFloat16RawBitsZero(elem_k)) return Just<int64_t>(k);
        }
        return Just<int64_t>(-1);
      }
      if (AccessorClass::ToTypedSearchValue(search_value,
                                            &typed_search_value)) {
        return Just<int64_t>(-1);
      }
    }
    for (size_t k = start_from; k < length; ++k) {
      ElementType elem_k = AccessorClass::GetImpl(data_ptr + k, is_shared);
      if (elem_k == typed_search_value) return Just<int64_t>(k);
    }
    return Just<int64_t>(-1);
  }
References v8::internal::is_shared, v8::internal::IsBigIntTypedArrayElementsKind(), v8::internal::anonymous_namespace{elements.cc}::IsFloat16RawBitsZero(), v8::internal::IsFloat16TypedArrayElementsKind(), v8::internal::IsFloatTypedArrayElementsKind(), v8::internal::IsNumber(), v8::internal::anonymous_namespace{elements.cc}::kShared, v8::internal::anonymous_namespace{elements.cc}::kUnshared, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::NumberValue(), V8_UNLIKELY, and v8::internal::value.
LastIndexOfValueImpl()
template<ElementsKind Kind, typename ElementType >
static Maybe<int64_t> v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::LastIndexOfValueImpl (DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from) [inline], [static]
Definition at line 3838 of file elements.cc.
                                                                {
    DisallowGarbageCollection no_gc;
    Tagged<JSTypedArray> typed_array = Cast<JSTypedArray>(*receiver);
    auto is_shared = typed_array->buffer()->is_shared() ? kShared : kUnshared;
    DCHECK(!typed_array->IsDetachedOrOutOfBounds());
    ElementType typed_search_value;
    ElementType* data_ptr =
        reinterpret_cast<ElementType*>(typed_array->DataPtr());
    if (IsBigIntTypedArrayElementsKind(Kind)) {
      if (!IsBigInt(*value)) return Just<int64_t>(-1);
      bool lossless;
      typed_search_value = FromHandle(value, &lossless);
      if (!lossless) return Just<int64_t>(-1);
    } else {
      if (!IsNumber(*value)) return Just<int64_t>(-1);
      double search_value = Object::NumberValue(*value);
      if (!std::isfinite(search_value)) {
        if (!IsFloat16TypedArrayElementsKind(Kind) &&
            std::is_integral_v<ElementType>) {
          // Integral types cannot represent +Inf or NaN.
          return Just<int64_t>(-1);
        } else if (std::isnan(search_value)) {
          // Strict Equality Comparison of NaN is always false.
          return Just<int64_t>(-1);
        }
      }
      if (AccessorClass::ToTypedSearchValue(search_value,
                                            &typed_search_value)) {
        return Just<int64_t>(-1);
      }
    }
    size_t typed_array_length = typed_array->GetLength();
    if (V8_UNLIKELY(start_from >= typed_array_length)) {
      // This can happen if the TypedArray got resized when we did ToInteger
      // on the last parameter of lastIndexOf.
      DCHECK(typed_array->IsVariableLength());
      if (typed_array_length == 0) {
        return Just<int64_t>(-1);
      }
      start_from = typed_array_length - 1;
    }
    size_t k = start_from;
    do {
      ElementType elem_k = AccessorClass::GetImpl(data_ptr + k, is_shared);
      if constexpr (IsFloat16TypedArrayElementsKind(Kind)) {
        if (IsFloat16RawBitsZero(typed_search_value) &&
            IsFloat16RawBitsZero(elem_k)) {
          return Just<int64_t>(k);
        }
      }
      if (elem_k == typed_search_value) return Just<int64_t>(k);
    } while (k-- != 0);
    return Just<int64_t>(-1);
  }
References v8::internal::DCHECK(), v8::internal::is_shared, v8::internal::IsBigIntTypedArrayElementsKind(), v8::internal::anonymous_namespace{elements.cc}::IsFloat16RawBitsZero(), v8::internal::IsFloat16TypedArrayElementsKind(), v8::internal::IsNumber(), v8::internal::anonymous_namespace{elements.cc}::kShared, v8::internal::anonymous_namespace{elements.cc}::kUnshared, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::NumberValue(), V8_UNLIKELY, and v8::internal::value.
NumberOfElementsImpl()
template<ElementsKind Kind, typename ElementType >
static size_t v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::NumberOfElementsImpl (Isolate * isolate, Tagged< JSObject > receiver, Tagged< FixedArrayBase > backing_store) [inline], [static]
Definition at line 3595 of file elements.cc.
                                                                           {
    return AccessorClass::GetCapacityImpl(receiver, backing_store);
  }
ReverseImpl()
template<ElementsKind Kind, typename ElementType >
static void v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::ReverseImpl (Tagged< JSObject > receiver) [inline], [static]
Definition at line 3900 of file elements.cc.
                                                     {
    DisallowGarbageCollection no_gc;
    Tagged<JSTypedArray> typed_array = Cast<JSTypedArray>(receiver);
    DCHECK(!typed_array->IsDetachedOrOutOfBounds());
    size_t len = typed_array->GetLength();
    if (len == 0) return;
    ElementType* data = static_cast<ElementType*>(typed_array->DataPtr());
    if (typed_array->buffer()->is_shared()) {
      // TypedArrays backed by shared buffers need to be reversed using atomic
      // operations. Since 8-byte data are not currently always 8-byte aligned,
      // manually reverse using GetImpl and SetImpl, which abstract over
      // alignment and atomic complexities.
      for (ElementType *first = data, *last = data + len - 1; first < last;
           ++first, --last) {
        ElementType first_value = AccessorClass::GetImpl(first, kShared);
        ElementType last_value = AccessorClass::GetImpl(last, kShared);
        AccessorClass::SetImpl(first, last_value, kShared);
        AccessorClass::SetImpl(last, first_value, kShared);
      }
    } else if (COMPRESS_POINTERS_BOOL && alignof(ElementType) > kTaggedSize) {
      // TODO(ishell, v8:8875): See UnalignedSlot<T> for details.
      std::reverse(UnalignedSlot<ElementType>(data),
                   UnalignedSlot<ElementType>(data + len));
    } else {
      std::reverse(data, data + len);
    }
  }
References COMPRESS_POINTERS_BOOL, v8::internal::DCHECK(), v8::internal::anonymous_namespace{elements.cc}::kShared, v8::internal::kTaggedSize, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
SetImpl() [1/2]
template<ElementsKind Kind, typename ElementType >
static void v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::SetImpl (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value) [inline], [static]
Definition at line 3416 of file elements.cc.
                                            {
    auto typed_array = Cast<JSTypedArray>(holder);
    DCHECK_LE(entry.raw_value(), typed_array->GetLength());
    auto* entry_ptr =
        static_cast<ElementType*>(typed_array->DataPtr()) + entry.raw_value();
    auto is_shared = typed_array->buffer()->is_shared() ? kShared : kUnshared;
    SetImpl(entry_ptr, FromObject(value), is_shared);
  }
References DCHECK_LE, v8::internal::is_shared, v8::internal::anonymous_namespace{elements.cc}::kShared, v8::internal::anonymous_namespace{elements.cc}::kUnshared, v8::internal::InternalIndex::raw_value(), and v8::internal::value.
SetImpl() [2/2]
template<ElementsKind Kind, typename ElementType >
static void v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::SetImpl (ElementType * data_ptr, ElementType value, IsSharedBuffer is_shared) [inline], [static]
Definition at line 3426 of file elements.cc.
                                                {
    // TODO(ishell, v8:8875): Independent of pointer compression, 8-byte size
    // fields (external pointers, doubles and BigInt data) are not always 8-byte
    // aligned. This is relying on undefined behaviour in C++, since {data_ptr}
    // is not aligned to {alignof(ElementType)}.
    if (!is_shared) {
      base::WriteUnalignedValue(reinterpret_cast<Address>(data_ptr), value);
      return;
    }
    // The JavaScript memory model allows for racy reads and writes to a
    // SharedArrayBuffer's backing store. Using relaxed atomics is not strictly
    // required for JavaScript, but will avoid undefined behaviour in C++ and is
    // unlikely to introduce noticeable overhead.
    if (IsAligned(reinterpret_cast<uintptr_t>(data_ptr),
                  alignof(std::atomic<ElementType>))) {
      // Use a single relaxed atomic store.
      static_assert(sizeof(std::atomic<ElementType>) == sizeof(ElementType));
      reinterpret_cast<std::atomic<ElementType>*>(data_ptr)->store(
          value, std::memory_order_relaxed);
      return;
    }
    // Some static CHECKs (are optimized out if succeeding) to ensure that
    // {data_ptr} is at least four byte aligned, and {std::atomic<uint32_t>}
    // has size and alignment of four bytes, such that we can cast the
    // {data_ptr} to it.
    CHECK_LE(kInt32Size, alignof(ElementType));
    CHECK_EQ(kInt32Size, alignof(std::atomic<uint32_t>));
    CHECK_EQ(kInt32Size, sizeof(std::atomic<uint32_t>));
    // And dynamically check that we indeed have at least four byte alignment.
    DCHECK(IsAligned(reinterpret_cast<uintptr_t>(data_ptr), kInt32Size));
    // Store as multiple 32-bit words. Make {kNumWords} >= 1 to avoid compiler
    // warnings for the empty array or memcpy to an empty object.
    constexpr size_t kNumWords =
        std::max(size_t{1}, sizeof(ElementType) / kInt32Size);
    uint32_t words[kNumWords];
    CHECK_EQ(sizeof(words), sizeof(value));
    memcpy(words, &value, sizeof(value));
    for (size_t word = 0; word < kNumWords; ++word) {
      static_assert(sizeof(std::atomic<uint32_t>) == sizeof(uint32_t));
      reinterpret_cast<std::atomic<uint32_t>*>(data_ptr)[word].store(
          words[word], std::memory_order_relaxed);
    }
  }
References CHECK_EQ, CHECK_LE, v8::internal::DCHECK(), v8::internal::is_shared, IsAligned(), v8::internal::kInt32Size, store(), v8::internal::value, and v8::base::WriteUnalignedValue().
SetLengthImpl()
template<ElementsKind Kind, typename ElementType >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::SetLengthImpl (Isolate * isolate, DirectHandle< JSArray > array, uint32_t length, DirectHandle< FixedArrayBase > backing_store) [inline], [static]
Definition at line 3565 of file elements.cc.
                                                                               {
    // External arrays do not support changing their length.
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
ToHandle() [1/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< FLOAT64_ELEMENTS, double >::ToHandle (Isolate * isolate, double value)
Definition at line 4480 of file elements.cc.
                                    {
  return isolate->factory()->NewNumber(value);
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewNumber(), and v8::internal::value.
ToHandle() [2/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_FLOAT64_ELEMENTS, double >::ToHandle (Isolate * isolate, double value)
Definition at line 4720 of file elements.cc.
                                                                     {
  return isolate->factory()->NewNumber(value);
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewNumber(), and v8::internal::value.
ToHandle() [3/25]
template<ElementsKind Kind, typename ElementType >
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::ToHandle (Isolate * isolate, ElementType value) [static]
ToHandle() [4/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< FLOAT32_ELEMENTS, float >::ToHandle (Isolate * isolate, float value)
Definition at line 4466 of file elements.cc.
                                   {
  return isolate->factory()->NewNumber(value);
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewNumber(), and v8::internal::value.
ToHandle() [5/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_FLOAT32_ELEMENTS, float >::ToHandle (Isolate * isolate, float value)
Definition at line 4705 of file elements.cc.
                                                                   {
  return isolate->factory()->NewNumber(value);
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewNumber(), and v8::internal::value.
ToHandle() [6/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< INT16_ELEMENTS, int16_t >::ToHandle (Isolate * isolate, int16_t value)
Definition at line 4404 of file elements.cc.
                                     {
  return handle(Smi::FromInt(value), isolate);
}
References v8::internal::Smi::FromInt(), v8::internal::handle(), and v8::internal::value.
ToHandle() [7/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_INT16_ELEMENTS, int16_t >::ToHandle (Isolate * isolate, int16_t value)
Definition at line 4637 of file elements.cc.
                                                                       {
  return handle(Smi::FromInt(value), isolate);
}
References v8::internal::Smi::FromInt(), v8::internal::handle(), and v8::internal::value.
ToHandle() [8/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< INT32_ELEMENTS, int32_t >::ToHandle (Isolate * isolate, int32_t value)
Definition at line 4418 of file elements.cc.
                                     {
  return isolate->factory()->NewNumberFromInt(value);
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), and v8::internal::value.
ToHandle() [9/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_INT32_ELEMENTS, int32_t >::ToHandle (Isolate * isolate, int32_t value)
Definition at line 4653 of file elements.cc.
                                                                       {
  return isolate->factory()->NewNumberFromInt(value);
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), and v8::internal::value.
ToHandle() [10/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< BIGINT64_ELEMENTS, int64_t >::ToHandle (Isolate * isolate, int64_t value)
Definition at line 4565 of file elements.cc.
                                     {
  return BigInt::FromInt64(isolate, value);
}
References v8::internal::BigInt::FromInt64(), and v8::internal::value.
ToHandle() [11/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_BIGINT64_ELEMENTS, int64_t >::ToHandle (Isolate * isolate, int64_t value)
Definition at line 4807 of file elements.cc.
                                                                       {
  return BigInt::FromInt64(isolate, value);
}
References v8::internal::BigInt::FromInt64(), and v8::internal::value.
ToHandle() [12/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< INT8_ELEMENTS, int8_t >::ToHandle (Isolate * isolate, int8_t value)
Definition at line 4390 of file elements.cc.
                                    {
  return handle(Smi::FromInt(value), isolate);
}
References v8::internal::Smi::FromInt(), v8::internal::handle(), and v8::internal::value.
ToHandle() [13/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_INT8_ELEMENTS, int8_t >::ToHandle (Isolate * isolate, int8_t value)
Definition at line 4621 of file elements.cc.
                                    {
  return handle(Smi::FromInt(value), isolate);
}
References v8::internal::Smi::FromInt(), v8::internal::handle(), and v8::internal::value.
ToHandle() [14/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< UINT16_ELEMENTS, uint16_t >::ToHandle (Isolate * isolate, uint16_t value)
Definition at line 4411 of file elements.cc.
                                      {
  return handle(Smi::FromInt(value), isolate);
}
References v8::internal::Smi::FromInt(), v8::internal::handle(), and v8::internal::value.
ToHandle() [15/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< FLOAT16_ELEMENTS, uint16_t >::ToHandle (Isolate * isolate, uint16_t value)
Definition at line 4459 of file elements.cc.
                                      {
  return isolate->factory()->NewNumber(fp16_ieee_to_fp32_value(value));
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewNumber(), and v8::internal::value.
ToHandle() [16/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_UINT16_ELEMENTS, uint16_t >::ToHandle (Isolate * isolate, uint16_t value)
Definition at line 4645 of file elements.cc.
                                                                         {
  return handle(Smi::FromInt(value), isolate);
}
References v8::internal::Smi::FromInt(), v8::internal::handle(), and v8::internal::value.
ToHandle() [17/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_FLOAT16_ELEMENTS, uint16_t >::ToHandle (Isolate * isolate, uint16_t value)
Definition at line 4690 of file elements.cc.
                                                                         {
  return isolate->factory()->NewHeapNumber(fp16_ieee_to_fp32_value(value));
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewHeapNumber(), and v8::internal::value.
ToHandle() [18/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< UINT32_ELEMENTS, uint32_t >::ToHandle (Isolate * isolate, uint32_t value)
Definition at line 4425 of file elements.cc.
                                      {
  return isolate->factory()->NewNumberFromUint(value);
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewNumberFromUint(), and v8::internal::value.
ToHandle() [19/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_UINT32_ELEMENTS, uint32_t >::ToHandle (Isolate * isolate, uint32_t value)
Definition at line 4661 of file elements.cc.
                                                                         {
  return isolate->factory()->NewNumberFromUint(value);
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewNumberFromUint(), and v8::internal::value.
ToHandle() [20/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< BIGUINT64_ELEMENTS, uint64_t >::ToHandle (Isolate * isolate, uint64_t value)
Definition at line 4614 of file elements.cc.
                                      {
  return BigInt::FromUint64(isolate, value);
}
References v8::internal::BigInt::FromUint64(), and v8::internal::value.
ToHandle() [21/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_BIGUINT64_ELEMENTS, uint64_t >::ToHandle (Isolate * isolate, uint64_t value)
Definition at line 4858 of file elements.cc.
                                                                         {
  return BigInt::FromUint64(isolate, value);
}
References v8::internal::BigInt::FromUint64(), and v8::internal::value.
ToHandle() [22/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< UINT8_ELEMENTS, uint8_t >::ToHandle (Isolate * isolate, uint8_t value)
Definition at line 4397 of file elements.cc.
                                     {
  return handle(Smi::FromInt(value), isolate);
}
References v8::internal::Smi::FromInt(), v8::internal::handle(), and v8::internal::value.
ToHandle() [23/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< UINT8_CLAMPED_ELEMENTS, uint8_t >::ToHandle (Isolate * isolate, uint8_t value)
Definition at line 4516 of file elements.cc.
                                     {
  return handle(Smi::FromInt(value), isolate);
}
References v8::internal::Smi::FromInt(), v8::internal::handle(), and v8::internal::value.
ToHandle() [24/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_UINT8_ELEMENTS, uint8_t >::ToHandle (Isolate * isolate, uint8_t value)
Definition at line 4629 of file elements.cc.
                                                                       {
  return handle(Smi::FromInt(value), isolate);
}
References v8::internal::Smi::FromInt(), v8::internal::handle(), and v8::internal::value.
ToHandle() [25/25]
Handle< Object > v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< RAB_GSAB_UINT8_CLAMPED_ELEMENTS, uint8_t >::ToHandle (Isolate * isolate, uint8_t value)
Definition at line 4757 of file elements.cc.
                                                                       {
  return handle(Smi::FromInt(value), isolate);
}
References v8::internal::Smi::FromInt(), v8::internal::handle(), and v8::internal::value.
ToTypedSearchValue()
template<ElementsKind Kind, typename ElementType >
static bool v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::ToTypedSearchValue (double search_value, ElementType * typed_search_value) [inline], [static]
Definition at line 3636 of file elements.cc.
                                                                  {
    if (!base::IsValueInRangeForNumericType<ElementType>(search_value) &&
        std::isfinite(search_value)) {
      // Return true if value can't be represented in this space.
      return true;
    }
    ElementType typed_value;
    if (IsFloat16TypedArrayElementsKind(Kind)) {
      typed_value = fp16_ieee_from_fp32_value(static_cast<float>(search_value));
      *typed_search_value = typed_value;
      return (static_cast<double>(fp16_ieee_to_fp32_value(typed_value)) !=
              search_value); // Loss of precision.
    }
    typed_value = static_cast<ElementType>(search_value);
    *typed_search_value = typed_value;
    return static_cast<double>(typed_value) !=
           search_value; // Loss of precision.
  }
References v8::internal::IsFloat16TypedArrayElementsKind().
TryCopyElementsFastNumber()
template<ElementsKind Kind, typename ElementType >
static bool v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::TryCopyElementsFastNumber (Tagged< Context > context, Tagged< JSArray > source, Tagged< JSTypedArray > destination, size_t length, size_t offset) [inline], [static]
Definition at line 4110 of file elements.cc.
                                                                      {
    if (IsBigIntTypedArrayElementsKind(Kind)) return false;
    Isolate* isolate = Isolate::Current();
    DisallowGarbageCollection no_gc;
    DisallowJavascriptExecution no_js(isolate);
    CHECK(!destination->WasDetached());
    bool out_of_bounds = false;
    CHECK_GE(destination->GetLengthOrOutOfBounds(out_of_bounds), length);
    CHECK(!out_of_bounds);
    size_t current_length;
    DCHECK(IsNumber(source->length()) &&
           TryNumberToSize(source->length(), &current_length) &&
           length <= current_length);
    USE(current_length);
    size_t dest_length = destination->GetLength();
    DCHECK(length + offset <= dest_length);
    USE(dest_length);
    ElementsKind kind = source->GetElementsKind();
    auto destination_shared =
        destination->buffer()->is_shared() ? kShared : kUnshared;
    // When we find the hole, we normally have to look up the element on the
    // prototype chain, which is not handled here and we return false instead.
    // When the array has the original array prototype, and that prototype has
    // not been changed in a way that would affect lookups, we can just convert
    // the hole into undefined.
    if (HoleyPrototypeLookupRequired(isolate, context, source)) return false;
    Tagged<Oddball> undefined = ReadOnlyRoots(isolate).undefined_value();
    ElementType* dest_data =
        reinterpret_cast<ElementType*>(destination->DataPtr()) + offset;
    // Fast-path for packed Smi kind.
    if (kind == PACKED_SMI_ELEMENTS) {
      Tagged<FixedArray> source_store = Cast<FixedArray>(source->elements());
      for (size_t i = 0; i < length; i++) {
        Tagged<Object> elem = source_store->get(static_cast<int>(i));
        ElementType elem_k;
        if (IsFloat16TypedArrayElementsKind(Kind)) {
          elem_k = fp16_ieee_from_fp32_value(Smi::ToInt(elem));
        } else {
          elem_k = FromScalar(Smi::ToInt(elem));
        }
        SetImpl(dest_data + i, elem_k, destination_shared);
      }
      return true;
    } else if (kind == HOLEY_SMI_ELEMENTS) {
      Tagged<FixedArray> source_store = Cast<FixedArray>(source->elements());
      for (size_t i = 0; i < length; i++) {
        if (source_store->is_the_hole(isolate, static_cast<int>(i))) {
          SetImpl(dest_data + i, FromObject(undefined), destination_shared);
        } else {
          Tagged<Object> elem = source_store->get(static_cast<int>(i));
          ElementType elem_k;
          if (IsFloat16TypedArrayElementsKind(Kind)) {
            elem_k = fp16_ieee_from_fp32_value(Smi::ToInt(elem));
          } else {
            elem_k = FromScalar(Smi::ToInt(elem));
          }
          SetImpl(dest_data + i, elem_k, destination_shared);
        }
      }
      return true;
    } else if (kind == PACKED_DOUBLE_ELEMENTS) {
      // Fast-path for packed double kind. We avoid boxing and then immediately
      // unboxing the double here by using get_scalar.
      Tagged<FixedDoubleArray> source_store =
          Cast<FixedDoubleArray>(source->elements());
      for (size_t i = 0; i < length; i++) {
        // Use the from_double conversion for this specific TypedArray type,
        // rather than relying on C++ to convert elem.
        double elem = source_store->get_scalar(static_cast<int>(i));
        SetImpl(dest_data + i, FromScalar(elem), destination_shared);
      }
      return true;
    } else if (kind == HOLEY_DOUBLE_ELEMENTS) {
      Tagged<FixedDoubleArray> source_store =
          Cast<FixedDoubleArray>(source->elements());
      for (size_t i = 0; i < length; i++) {
        if (source_store->is_the_hole(static_cast<int>(i))
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
            || source_store->is_undefined(static_cast<int>(i))
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
        ) {
          SetImpl(dest_data + i, FromObject(undefined), destination_shared);
        } else {
          double elem = source_store->get_scalar(static_cast<int>(i));
          SetImpl(dest_data + i, FromScalar(elem), destination_shared);
        }
      }
      return true;
    }
    return false;
  }
References CHECK, CHECK_GE, v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::IsBigIntTypedArrayElementsKind(), v8::internal::IsFloat16TypedArrayElementsKind(), v8::internal::IsNumber(), v8::internal::anonymous_namespace{elements.cc}::kShared, v8::internal::anonymous_namespace{elements.cc}::kUnshared, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, v8::internal::Smi::ToInt(), v8::internal::TryNumberToSize(), v8::internal::undefined, and USE.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/elements.cc