v8::internal::ObjectBoilerplateDescription Class Reference
#include <literal-objects.h>
Classes
class BodyDescriptor
Public Types
using Shape = ObjectBoilerplateDescriptionShape
Public Member Functions
int flags () const
void set_flags (int value)
int backing_store_size () const
void set_backing_store_size (int backing_store_size)
int boilerplate_properties_count () const
Tagged< Object > name (int index) const
Tagged< Object > value (int index) const
void set_key_value (int index, Tagged< Object > key, Tagged< Object > value)
Static Public Member Functions
template<class IsolateT >
static Handle< ObjectBoilerplateDescription > New (IsolateT *isolate, int boilerplate, int all_properties, int index_keys, bool has_seen_proto, AllocationType allocation=AllocationType::kYoung)
Private Types
using Super = TaggedArrayBase< ObjectBoilerplateDescription, ObjectBoilerplateDescriptionShape >
Static Private Member Functions
static constexpr int NameIndex (int i)
static constexpr int ValueIndex (int i)
Static Private Attributes
static constexpr int kElementsPerEntry = 2
Additional Inherited Members
Detailed Description
Definition at line 42 of file literal-objects.h.
Member Typedef Documentation
Shape
using v8::internal::ObjectBoilerplateDescription::Shape = ObjectBoilerplateDescriptionShape
Definition at line 48 of file literal-objects.h.
Super
using v8::internal::ObjectBoilerplateDescription::Super = TaggedArrayBase<ObjectBoilerplateDescription, ObjectBoilerplateDescriptionShape> [private]
Definition at line 45 of file literal-objects.h.
Member Function Documentation
backing_store_size()
int v8::internal::ObjectBoilerplateDescription::backing_store_size () const [inline]
Definition at line 56 of file literal-objects-inl.h.
                                                           {
  return backing_store_size_.load().value();
}
Referenced by New().
boilerplate_properties_count()
int v8::internal::ObjectBoilerplateDescription::boilerplate_properties_count () const [inline]
Definition at line 84 of file literal-objects-inl.h.
                                                                     {
  DCHECK_EQ(0, capacity() % kElementsPerEntry);
  return capacity() / kElementsPerEntry;
}
References DCHECK_EQ, and kElementsPerEntry.
Referenced by set_key_value().
flags()
int v8::internal::ObjectBoilerplateDescription::flags () const [inline]
Definition at line 62 of file literal-objects-inl.h.
                                              {
  return flags_.load().value();
}
name()
Tagged< Object > v8::internal::ObjectBoilerplateDescription::name (int index) const [inline]
Definition at line 69 of file literal-objects-inl.h.
                                                                 {
  return get(NameIndex(index));
}
References v8::internal::TaggedArrayBase< ObjectBoilerplateDescription, ObjectBoilerplateDescriptionShape >::get(), v8::internal::index, and NameIndex().
NameIndex()
static constexpr int v8::internal::ObjectBoilerplateDescription::NameIndex (int i) [inline], [static], [constexpr], [private]
Definition at line 78 of file literal-objects.h.
{ return i * kElementsPerEntry; }
References kElementsPerEntry.
Referenced by name(), and set_key_value().
New()
template<class IsolateT >
Handle< ObjectBoilerplateDescription > v8::internal::ObjectBoilerplateDescription::New (IsolateT * isolate, int boilerplate, int all_properties, int index_keys, bool has_seen_proto, AllocationType allocation = AllocationType::kYoung) [inline], [static]
Definition at line 28 of file literal-objects-inl.h.
                                                    {
  DCHECK_GE(boilerplate, 0);
  DCHECK_GE(all_properties, index_keys);
  DCHECK_GE(index_keys, 0);
  int capacity = boilerplate * kElementsPerEntry;
  CHECK_LE(static_cast<unsigned>(capacity), kMaxCapacity);
  int backing_store_size =
      all_properties - index_keys - (has_seen_proto ? 1 : 0);
  DCHECK_GE(backing_store_size, 0);
  // Note we explicitly do NOT canonicalize to the
  // empty_object_boilerplate_description here since `flags` may be modified
  // even on empty descriptions.
  std::optional<DisallowGarbageCollection> no_gc;
  auto result = Cast<ObjectBoilerplateDescription>(
      Allocate(isolate, capacity, &no_gc, allocation));
  result->set_flags(0);
  result->set_backing_store_size(backing_store_size);
  MemsetTagged((*result)->RawFieldOfFirstElement(),
               ReadOnlyRoots{isolate}.undefined_value(), capacity);
  return result;
}
References v8::internal::TaggedArrayBase< ObjectBoilerplateDescription, ObjectBoilerplateDescriptionShape >::Allocate(), backing_store_size(), CHECK_LE, DCHECK_GE, kElementsPerEntry, v8::internal::TaggedArrayBase< ObjectBoilerplateDescription, ObjectBoilerplateDescriptionShape >::kMaxCapacity, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
Referenced by v8::internal::FactoryBase< Impl >::NewObjectBoilerplateDescription().
set_backing_store_size()
void v8::internal::ObjectBoilerplateDescription::set_backing_store_size (int backing_store_size) [inline]
Definition at line 59 of file literal-objects-inl.h.
                                                                   {
  backing_store_size_.store(this, Smi::FromInt(value));
}
References v8::internal::Smi::FromInt(), and value().
set_flags()
void v8::internal::ObjectBoilerplateDescription::set_flags (int value) [inline]
Definition at line 65 of file literal-objects-inl.h.
                                                      {
  flags_.store(this, Smi::FromInt(value));
}
References v8::internal::Smi::FromInt(), and value().
set_key_value()
void v8::internal::ObjectBoilerplateDescription::set_key_value (int index, Tagged< Object > key, Tagged< Object > value) [inline]
Definition at line 77 of file literal-objects-inl.h.
                                                                       {
  DCHECK_LT(static_cast<unsigned>(index), boilerplate_properties_count());
  set(NameIndex(index), key);
  set(ValueIndex(index), value);
}
References boilerplate_properties_count(), DCHECK_LT, v8::internal::index, v8::internal::key, NameIndex(), v8::internal::TaggedArrayBase< ObjectBoilerplateDescription, ObjectBoilerplateDescriptionShape >::set(), value(), and ValueIndex().
value()
Tagged< Object > v8::internal::ObjectBoilerplateDescription::value (int index) const [inline]
Definition at line 73 of file literal-objects-inl.h.
                                                                  {
  return get(ValueIndex(index));
}
References v8::internal::TaggedArrayBase< ObjectBoilerplateDescription, ObjectBoilerplateDescriptionShape >::get(), v8::internal::index, and ValueIndex().
Referenced by set_backing_store_size(), set_flags(), and set_key_value().
ValueIndex()
static constexpr int v8::internal::ObjectBoilerplateDescription::ValueIndex (int i) [inline], [static], [constexpr], [private]
Definition at line 79 of file literal-objects.h.
{ return i * kElementsPerEntry + 1; }
References kElementsPerEntry.
Referenced by set_key_value(), and value().
Member Data Documentation
kElementsPerEntry
constexpr int v8::internal::ObjectBoilerplateDescription::kElementsPerEntry = 2 [static], [constexpr], [private]
Definition at line 77 of file literal-objects.h.
Referenced by boilerplate_properties_count(), NameIndex(), New(), and ValueIndex().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/literal-objects.h
/mnt/V8SourceCode/src/objects/literal-objects-inl.h