v8::ArrayBuffer::Allocator Class Reference
A thread-safe allocator that V8 uses to allocate |ArrayBuffer|'s memory.
#include <v8-array-buffer.h>
Public Types
enum class AllocationMode { kNormal
, kReservation
 }
ArrayBuffer allocation mode.
Public Member Functions
virtual ~Allocator ()=default
virtual void * Allocate (size_t length)=0
Allocate |length| bytes.
virtual void * AllocateUninitialized (size_t length)=0
Allocate |length| bytes.
virtual void Free (void *data, size_t length)=0
Free the memory block of size |length|, pointed to by |data|.
virtual size_t MaxAllocationSize () const
Returns a size_t that determines the largest ArrayBuffer that can be allocated.
virtual PageAllocator * GetPageAllocator ()
Returns page allocator used by this Allocator instance.
Static Public Member Functions
static Allocator * NewDefaultAllocator ()
Convenience allocator.
Detailed Description
A thread-safe allocator that V8 uses to allocate |ArrayBuffer|'s memory.
The allocator is a global V8 setting. It has to be set via Isolate::CreateParams.
Memory allocated through this allocator by V8 is accounted for as external memory by V8. Note that V8 keeps track of the memory for all internalized |ArrayBuffer|s. Responsibility for tracking external memory (using Isolate::AdjustAmountOfExternalAllocatedMemory) is handed over to the embedder upon externalization and taken over upon internalization (creating an internalized buffer from an existing buffer).
Note that it is unsafe to call back into V8 from any of the allocator functions.
Definition at line 148 of file v8-array-buffer.h.
Member Enumeration Documentation
AllocationMode
enum v8::ArrayBuffer::Allocator::AllocationMode [strong]
ArrayBuffer allocation mode.
kNormal is a malloc/free style allocation, while kReservation is for larger allocations with the ability to set access permissions.
Enumerator
kNormal
kReservation
Definition at line 184 of file v8-array-buffer.h.
{ kNormal, kReservation };
Constructor & Destructor Documentation
 Allocator()
virtual v8::ArrayBuffer::Allocator::~Allocator () [virtual], [default]
Member Function Documentation
Allocate()
virtual void* v8::ArrayBuffer::Allocator::Allocate (size_t length) [pure virtual]
Allocate |length| bytes.
Return nullptr if allocation is not successful. Memory should be initialized to zeroes.
Implemented in v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocatiorWithLimit, v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocator, v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator, v8::anonymous_namespace{d8.cc}::ArrayBufferAllocatorBase, and v8::anonymous_namespace{api.cc}::ArrayBufferAllocator.
AllocateUninitialized()
virtual void* v8::ArrayBuffer::Allocator::AllocateUninitialized (size_t length) [pure virtual]
Allocate |length| bytes.
Return nullptr if allocation is not successful. Memory does not have to be initialized.
Implemented in v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocatiorWithLimit, v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocator, v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator, v8::anonymous_namespace{d8.cc}::ArrayBufferAllocatorBase, and v8::anonymous_namespace{api.cc}::ArrayBufferAllocator.
Free()
virtual void v8::ArrayBuffer::Allocator::Free (void * data, size_t length) [pure virtual]
Free the memory block of size |length|, pointed to by |data|.
That memory is guaranteed to be previously allocated by |Allocate|.
Implemented in v8::anonymous_namespace{api.cc}::ArrayBufferAllocator, v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocatiorWithLimit, v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocator, v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator, and v8::anonymous_namespace{d8.cc}::ArrayBufferAllocatorBase.
GetPageAllocator()
virtual PageAllocator* v8::ArrayBuffer::Allocator::GetPageAllocator () [inline], [virtual]
Returns page allocator used by this Allocator instance.
When the sandbox used by Allocator it is expected that this returns sandbox's page allocator. Otherwise, it should return system page allocator.
Reimplemented in v8::anonymous_namespace{d8.cc}::ArrayBufferAllocatorBase, and v8::anonymous_namespace{api.cc}::ArrayBufferAllocator.
Definition at line 193 of file v8-array-buffer.h.
{ return nullptr; }
MaxAllocationSize()
virtual size_t v8::ArrayBuffer::Allocator::MaxAllocationSize () const [inline], [virtual]
Returns a size_t that determines the largest ArrayBuffer that can be allocated.
Override if your Allocator is more restrictive than the default. Will only be called once, and the value returned will be cached. Should not return a value that is larger than kMaxByteLength.
Reimplemented in v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocatiorWithLimit.
Definition at line 177 of file v8-array-buffer.h.
{ return kMaxByteLength; }
Referenced by v8::internal::Heap::AllocateExternalBackingStore(), v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::ArrayBufferTransfer(), v8::ArrayBuffer::MaybeNew(), and v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::TryAllocateBackingStore().
NewDefaultAllocator()
v8::ArrayBuffer::Allocator * v8::ArrayBuffer::Allocator::NewDefaultAllocator () [static]
Convenience allocator.
When the sandbox is enabled, this allocator will allocate its backing memory inside the default global sandbox. Otherwise, it will rely on malloc/free.
Caller takes ownership, i.e. the returned object needs to be freed using |delete allocator| once it is no longer in use.
Definition at line 8889 of file api.cc.
                                                                    {
#ifdef V8_ENABLE_SANDBOX
  return new ArrayBufferAllocator(i::IsolateGroup::GetDefault());
#else
  return new ArrayBufferAllocator();
#endif
}
References v8::internal::IsolateGroup::GetDefault().
Referenced by v8::internal::CreateSnapshotDataBlobInternal(), main(), v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting(), and v8::internal::WarmUpSnapshotDataBlobInternal().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-array-buffer.h
/mnt/V8SourceCode/src/api/api.cc