v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next > Class Template Reference
#include <loop-unrolling-reducer.h>
Public Member Functions
V< None > REDUCE_INPUT_GRAPH() Goto (V< None > ig_idx, const GotoOp &gto)
V< None > REDUCE_INPUT_GRAPH() Branch (V< None > ig_idx, const BranchOp &branch)
V< None > REDUCE_INPUT_GRAPH() JSStackCheck (V< None > ig_idx, const JSStackCheckOp &check)
Private Types
enum class UnrollingStatus { kNotUnrolling
, kUnrolling
, kRemoveLoop
 }
Private Member Functions
void RemoveLoop (const Block *header)
void FullyUnrollLoop (const Block *header)
void PartiallyUnrollLoop (const Block *header)
void FixLoopPhis (const Block *input_graph_loop, Block *output_graph_loop, const Block *backedge_block)
bool IsRunningBuiltinPipeline ()
bool StopUnrollingIfUnreachable (std::optional< Block * > output_graph_header=std::nullopt)
Private Attributes
LoopUnrollingAnalyzer & analyzer_
UnrollingStatus unrolling_ = UnrollingStatus::kNotUnrolling
bool skip_next_stack_check_ = false
const Block * current_loop_header_ = nullptr
JSHeapBroker * broker_ = __ data() -> broker()
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >
Definition at line 358 of file loop-unrolling-reducer.h.
Member Enumeration Documentation
UnrollingStatus
template<class Next >
enum v8::internal::compiler::turboshaft::LoopUnrollingReducer::UnrollingStatus [strong], [private]
Enumerator
kNotUnrolling
kUnrolling
kRemoveLoop
Definition at line 456 of file loop-unrolling-reducer.h.
                             {
    // Not currently unrolling a loop.
    kNotUnrolling,
    // Currently unrolling a loop.
    kUnrolling,
    // We use kRemoveLoop in 2 cases:
    // - When unrolling is finished and we are currently emitting the header
    // one last time, and should change its final branch into a Goto.
    // - We decided to remove a loop and will just emit its header.
    // Both cases are fairly similar: we are currently emitting a loop header,
    // and would like to not emit the loop body that follows.
    kRemoveLoop,
  };
Member Function Documentation
Branch()
template<class Next >
V<None> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Branch (V< None > ig_idx, const BranchOp & branch) [inline]
Definition at line 404 of file loop-unrolling-reducer.h.
                                                                             {
    LABEL_BLOCK(no_change) {
      return Next::ReduceInputGraphBranch(ig_idx, branch);
    }
    if (unrolling_ == UnrollingStatus::kRemoveLoop) {
      // We know that the branch of the final inlined header of a fully unrolled
      // loop never actually goes to the loop, so we can replace it by a Goto
      // (so that the non-unrolled loop doesn't get emitted). We still need to
      // figure out if we should Goto to the true or false side of the BranchOp.
      const Block* header = __ current_block()->OriginForBlockEnd();
      bool is_true_in_loop = analyzer_.GetLoopHeader(branch.if_true) == header;
      bool is_false_in_loop =
          analyzer_.GetLoopHeader(branch.if_false) == header;
      if (is_true_in_loop && !is_false_in_loop) {
        __ Goto(__ MapToNewGraph(branch.if_false));
        return OpIndex::Invalid();
      } else if (is_false_in_loop && !is_true_in_loop) {
        __ Goto(__ MapToNewGraph(branch.if_true));
        return OpIndex::Invalid();
      } else {
        // Both the true and false destinations of this block are in the loop,
        // which means that the exit of the loop is later down the graph. We
        // thus still emit the branch, which will lead to the loop being emitted
        // (unless some other reducers in the stack manage to get rid of the
        // loop).
        DCHECK(is_true_in_loop && is_false_in_loop);
      }
    }
    goto no_change;
  }
References __, v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::analyzer_, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetLoopHeader(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Goto(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::kRemoveLoop, LABEL_BLOCK, and v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::unrolling_.
FixLoopPhis()
template<class Next >
void v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::FixLoopPhis (const Block * input_graph_loop, Block * output_graph_loop, const Block * backedge_block) [private]
Definition at line 572 of file loop-unrolling-reducer.h.
                                                                          {
  // FixLoopPhis for partially unrolled loops is a bit tricky: the mapping from
  // input Loop Phis to output Loop Phis is in the Variable Snapshot of the
  // header (`output_graph_loop`), but the mapping from the 2nd input of the
  // input graph loop phis to the 2nd input of the output graph loop phis is in
  // the snapshot of the backedge (`backedge_block`).
  // VariableReducer::ReduceGotoOp (which was called right before this function
  // because we emitted the backedge Goto) already set the current snapshot to
  // be at the loop header. So, we start by computing the mapping input loop
  // phis -> output loop phis (using the loop header's snapshot). Then, we
  // restore the backedge snapshot to compute the mapping input graph 2nd phi
  // input to output graph 2nd phi input.
  DCHECK(input_graph_loop->IsLoop());
  DCHECK(output_graph_loop->IsLoop());
  // The mapping InputGraphPhi -> OutputGraphPendingPhi should be retrieved from
  // `output_graph_loop`'s snapshot (the current mapping is for the latest
  // folded loop iteration, not for the loop header).
  __ SealAndSaveVariableSnapshot();
  __ RestoreTemporaryVariableSnapshotAfter(output_graph_loop);
  base::SmallVector<std::pair<const PhiOp*, const OpIndex>, 16> phis;
  for (const Operation& op : __ input_graph().operations(
           input_graph_loop->begin(), input_graph_loop->end())) {
    if (auto* input_phi = op.TryCast<PhiOp>()) {
      OpIndex phi_index =
          __ template MapToNewGraph<true>(__ input_graph().Index(*input_phi));
      if (!phi_index.valid() || !output_graph_loop->Contains(phi_index)) {
        // Unused phis are skipped, so they are not be mapped to anything in
        // the new graph. If the phi is reduced to an operation from a
        // different block, then there is no loop phi in the current loop
        // header to take care of.
        continue;
      }
      phis.push_back({input_phi, phi_index});
    }
  }
  // The mapping for the InputGraphPhi 2nd input should however be retrieved
  // from the last block of the loop.
  __ CloseTemporaryVariableSnapshot();
  __ RestoreTemporaryVariableSnapshotAfter(backedge_block);
  for (auto [input_phi, output_phi_index] : phis) {
    __ FixLoopPhi(*input_phi, output_phi_index, output_graph_loop);
  }
  __ CloseTemporaryVariableSnapshot();
}
References __, v8::internal::compiler::turboshaft::Block::begin(), v8::internal::compiler::turboshaft::Block::Contains(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Block::end(), v8::internal::compiler::turboshaft::Block::IsLoop(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), and v8::internal::compiler::turboshaft::OpIndex::valid().
FullyUnrollLoop()
template<class Next >
void v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::FullyUnrollLoop (const Block * header) [private]
Definition at line 638 of file loop-unrolling-reducer.h.
                                                                    {
  TRACE("LoopUnrolling: fully unrolling loop at " << header->index().id());
  DCHECK_EQ(unrolling_, UnrollingStatus::kNotUnrolling);
  DCHECK(!skip_next_stack_check_);
  ScopedModification<bool> skip_stack_checks(&skip_next_stack_check_, true);
  size_t iter_count = analyzer_.GetIterationCount(header).exact_count();
  TRACE("> iter_count: " << iter_count);
  auto loop_body = analyzer_.GetLoopBody(header);
  current_loop_header_ = header;
  unrolling_ = UnrollingStatus::kUnrolling;
  for (size_t i = 0; i < iter_count; i++) {
    TRACE("> Emitting iteration " << i);
    __ CloneSubGraph(loop_body, /* keep_loop_kinds */ false);
    if (StopUnrollingIfUnreachable()) {
      TRACE("> Next iteration is unreachable, stopping unrolling");
      return;
    }
  }
  // The loop actually finishes on the header rather than its last block. We
  // thus inline the header, and we'll replace its final BranchOp by a GotoOp to
  // outside of the loop.
  TRACE("> Emitting the final header");
  unrolling_ = UnrollingStatus::kRemoveLoop;
  __ CloneAndInlineBlock(header);
  unrolling_ = UnrollingStatus::kNotUnrolling;
  TRACE("> Finished fully unrolling loop " << header->index().id());
}
References __, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::IterationCount::exact_count(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetIterationCount(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetLoopBody(), v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), and v8::internal::TRACE().
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Goto().
Goto()
template<class Next >
V<None> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Goto (V< None > ig_idx, const GotoOp & gto) [inline]
Definition at line 371 of file loop-unrolling-reducer.h.
                                                                      {
    // Note that the "ShouldSkipOptimizationStep" are placed in the parts of
    // this Reduce method triggering the unrolling rather than at the begining.
    // This is because the backedge skipping is not an optimization but a
    // mandatory lowering when unrolling is being performed.
    LABEL_BLOCK(no_change) { return Next::ReduceInputGraphGoto(ig_idx, gto); }
    const Block* dst = gto.destination;
    if (unrolling_ == UnrollingStatus::kNotUnrolling && dst->IsLoop() &&
        !gto.is_backedge) {
      // We trigger unrolling when reaching the GotoOp that jumps to the loop
      // header (note that loop headers only have 2 predecessor, including the
      // backedge), and that isn't the backedge.
      if (ShouldSkipOptimizationStep()) goto no_change;
      if (analyzer_.ShouldRemoveLoop(dst)) {
        RemoveLoop(dst);
        return {};
      } else if (analyzer_.ShouldFullyUnrollLoop(dst)) {
        FullyUnrollLoop(dst);
        return {};
      } else if (analyzer_.ShouldPartiallyUnrollLoop(dst)) {
        PartiallyUnrollLoop(dst);
        return {};
      }
    } else if ((unrolling_ == UnrollingStatus::kUnrolling) &&
               dst == current_loop_header_) {
      // Skipping the backedge of the loop: FullyUnrollLoop and
      // PartiallyUnrollLoop will emit a Goto to the next unrolled iteration.
      return {};
    }
    goto no_change;
  }
References v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::current_loop_header_, v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::FullyUnrollLoop(), v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::kNotUnrolling, v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::kUnrolling, LABEL_BLOCK, v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::PartiallyUnrollLoop(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::RemoveLoop(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::ShouldFullyUnrollLoop(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::ShouldPartiallyUnrollLoop(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::ShouldRemoveLoop(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), and v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::unrolling_.
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Branch().
IsRunningBuiltinPipeline()
template<class Next >
bool v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::IsRunningBuiltinPipeline () [inline], [private]
Definition at line 474 of file loop-unrolling-reducer.h.
                                  {
    return __ data() -> pipeline_kind() == TurboshaftPipelineKind::kCSA;
  }
References __, and v8::internal::compiler::turboshaft::kCSA.
JSStackCheck()
template<class Next >
V<None> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::JSStackCheck (V< None > ig_idx, const JSStackCheckOp & check) [inline]
Definition at line 437 of file loop-unrolling-reducer.h.
                                                                        {
    if (ShouldSkipOptimizationStep() || !skip_next_stack_check_) {
      return Next::ReduceInputGraphJSStackCheck(ig_idx, check);
    }
    return V<None>::Invalid();
  }
References v8::internal::compiler::turboshaft::V< T >::Invalid(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), and v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::skip_next_stack_check_.
PartiallyUnrollLoop()
template<class Next >
void v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::PartiallyUnrollLoop (const Block * header) [private]
Definition at line 510 of file loop-unrolling-reducer.h.
                                                                        {
  TRACE("LoopUnrolling: partially unrolling loop at " << header->index().id());
  DCHECK_EQ(unrolling_, UnrollingStatus::kNotUnrolling);
  DCHECK(!skip_next_stack_check_);
  unrolling_ = UnrollingStatus::kUnrolling;
  auto loop_body = analyzer_.GetLoopBody(header);
  current_loop_header_ = header;
  size_t unroll_count = analyzer_.GetPartialUnrollCount(header);
  DCHECK_GT(unroll_count, 0);
  TRACE("> UnrollCount: " << unroll_count);
  ScopedModification<bool> set_true(__ turn_loop_without_backedge_into_merge(),
                                    false);
  // We remove the stack check of all iterations but the last one.
  // Emitting the 1st iteration of the loop (with a proper loop header). We
  // remove the stack check of all iterations except the last one.
  ScopedModification<bool> skip_stack_checks(&skip_next_stack_check_, true);
  TRACE("> Emitting first iteraton (with header)");
  Block* output_graph_header =
      __ CloneSubGraph(loop_body, /* keep_loop_kinds */ true);
  if (StopUnrollingIfUnreachable(output_graph_header)) {
    TRACE("> Next iteration is unreachable, stopping unrolling");
    return;
  }
  // Emitting the subsequent folded iterations. We set `unrolling_` to
  // kUnrolling so that stack checks are skipped.
  unrolling_ = UnrollingStatus::kUnrolling;
  for (size_t i = 0; i < unroll_count - 1; i++) {
    // We remove the stack check of all iterations but the last one.
    TRACE("> Emitting iteration " << i);
    bool is_last_iteration = i == unroll_count - 2;
    ScopedModification<bool> inner_skip_stack_checks(&skip_next_stack_check_,
                                                     !is_last_iteration);
    __ CloneSubGraph(loop_body, /* keep_loop_kinds */ false);
    if (StopUnrollingIfUnreachable(output_graph_header)) {
      TRACE("> Next iteration is unreachable, stopping unrolling");
      return;
    }
  }
  // ReduceInputGraphGoto ignores backedge Gotos while kUnrolling is true, which
  // means that we are still missing the loop's backedge, which we thus emit
  // now.
  DCHECK(output_graph_header->IsLoop());
  Block* backedge_block = __ current_block();
  __ Goto(output_graph_header);
  // We use a custom `FixLoopPhis` because the mapping from old->new is a bit
  // "messed up" by having emitted multiple times the same block. See the
  // comments in `FixLoopPhis` for more details.
  TRACE("> Patching loop phis");
  FixLoopPhis(header, output_graph_header, backedge_block);
  unrolling_ = UnrollingStatus::kNotUnrolling;
  TRACE("> Finished partially unrolling loop " << header->index().id());
}
References __, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetLoopBody(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetPartialUnrollCount(), v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Block::IsLoop(), and v8::internal::TRACE().
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Goto().
RemoveLoop()
template<class Next >
void v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::RemoveLoop (const Block * header) [private]
Definition at line 624 of file loop-unrolling-reducer.h.
                                                               {
  TRACE("LoopUnrolling: removing loop at " << header->index().id());
  DCHECK_EQ(unrolling_, UnrollingStatus::kNotUnrolling);
  DCHECK(!skip_next_stack_check_);
  // When removing a loop, we still need to emit the header (since it has to
  // always be executed before the 1st iteration anyways), but by setting
  // {unrolling_} to `kRemoveLoop`, the final Branch of the loop will become a
  // Goto to outside the loop.
  unrolling_ = UnrollingStatus::kRemoveLoop;
  __ CloneAndInlineBlock(header);
  unrolling_ = UnrollingStatus::kNotUnrolling;
}
References __, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), and v8::internal::TRACE().
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Goto().
StopUnrollingIfUnreachable()
template<class Next >
bool v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::StopUnrollingIfUnreachable (std::optional< Block * > output_graph_header = std::nullopt) [inline], [private]
Definition at line 477 of file loop-unrolling-reducer.h.
                                                            {
    if (__ generating_unreachable_operations()) {
      // By unrolling the loop, we realized that it was actually exiting early
      // (probably because a Branch inside the loop was using a loop Phi in a
      // condition, and unrolling showed that this loop Phi became true or
      // false), and that lasts iterations were unreachable. We thus don't both
      // unrolling the next iterations of the loop.
      unrolling_ = UnrollingStatus::kNotUnrolling;
      if (output_graph_header.has_value()) {
        // The loop that we're unrolling has a header (which means that we're
        // only partially unrolling), which needs to be turned into a Merge (and
        // its PendingLoopPhis into regular Phis).
        __ FinalizeLoop(*output_graph_header);
      }
      return true;
    }
    return false;
  }
References __, v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::kNotUnrolling, and v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::unrolling_.
Member Data Documentation
analyzer_
template<class Next >
LoopUnrollingAnalyzer& v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::analyzer_ [private]
Initial value:
=
      *__ input_graph().loop_unrolling_analyzer()
Definition at line 499 of file loop-unrolling-reducer.h.
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Branch(), and v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Goto().
broker_
template<class Next >
JSHeapBroker* v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::broker_ = __ data() -> broker() [private]
Definition at line 506 of file loop-unrolling-reducer.h.
current_loop_header_
template<class Next >
const Block* v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::current_loop_header_ = nullptr [private]
Definition at line 505 of file loop-unrolling-reducer.h.
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Goto().
skip_next_stack_check_
template<class Next >
bool v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::skip_next_stack_check_ = false [private]
Definition at line 503 of file loop-unrolling-reducer.h.
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::JSStackCheck().
unrolling_
template<class Next >
UnrollingStatus v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::unrolling_ = UnrollingStatus::kNotUnrolling [private]
Definition at line 502 of file loop-unrolling-reducer.h.
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Branch(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Goto(), and v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::StopUnrollingIfUnreachable().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/loop-peeling-reducer.h
/mnt/V8SourceCode/src/compiler/turboshaft/loop-unrolling-reducer.h