v8::internal::SlowBoilerplateCloneAssembler Class Reference
Public Member Functions
SlowBoilerplateCloneAssembler (compiler::CodeAssemblerState *state)
void CloneIfObjectOrArray (TNode< Object > item, TVariable< Object > &clone, TVariable< Object > &current_allocation_site, TNode< Context > context, Label *cloned, Label *not_cloned, Label *bailout)
void CloneElementsOfFixedArray (TNode< FixedArrayBase > elements, TNode< Smi > length, TNode< Int32T > elements_kind, TVariable< Object > &current_allocation_site, TNode< Context > context, Label *done, Label *bailout)
Additional Inherited Members
Detailed Description
Definition at line 2001 of file builtins-array-gen.cc.
Constructor & Destructor Documentation
SlowBoilerplateCloneAssembler()
v8::internal::SlowBoilerplateCloneAssembler::SlowBoilerplateCloneAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 2003 of file builtins-array-gen.cc.
      : CodeStubAssembler(state) {}
Member Function Documentation
CloneElementsOfFixedArray()
void v8::internal::SlowBoilerplateCloneAssembler::CloneElementsOfFixedArray (TNode< FixedArrayBase > elements, TNode< Smi > length, TNode< Int32T > elements_kind, TVariable< Object > & current_allocation_site, TNode< Context > context, Label * done, Label * bailout) [inline]
Definition at line 2059 of file builtins-array-gen.cc.
                                                 {
    CSA_DCHECK(this, SmiNotEqual(length, SmiConstant(0)));
    auto loop_body = [&](TNode<IntPtrT> index) {
      TVARIABLE(Object, clone);
      Label cloned(this, &clone),
          done_with_element(this, &current_allocation_site);
      TNode<Object> element = LoadFixedArrayElement(CAST(elements), index);
      CloneIfObjectOrArray(element, clone, current_allocation_site, context,
                           &cloned, &done_with_element, bailout);
      BIND(&cloned);
      {
        StoreFixedArrayElement(CAST(elements), index, clone.value());
        Goto(&done_with_element);
      }
      BIND(&done_with_element);
    };
    VariableList loop_vars({&current_allocation_site}, zone());
    BuildFastLoop<IntPtrT>(loop_vars, IntPtrConstant(0),
                           PositiveSmiUntag(length), loop_body, 1,
                           LoopUnrollingMode::kYes, IndexAdvanceMode::kPost);
    Goto(done);
  }
References CAST, CloneIfObjectOrArray(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::index, v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::CodeStubAssembler::kPost, v8::internal::CodeStubAssembler::kYes, v8::internal::length, v8::internal::CodeStubAssembler::LoadFixedArrayElement(), v8::internal::CodeStubAssembler::PositiveSmiUntag(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::StoreFixedArrayElement(), and v8::internal::compiler::CodeAssembler::zone().
CloneIfObjectOrArray()
void v8::internal::SlowBoilerplateCloneAssembler::CloneIfObjectOrArray (TNode< Object > item, TVariable< Object > & clone, TVariable< Object > & current_allocation_site, TNode< Context > context, Label * cloned, Label * not_cloned, Label * bailout) [inline]
Definition at line 2007 of file builtins-array-gen.cc.
                                                               {
    Label is_object(this, &current_allocation_site),
        is_array(this, &current_allocation_site);
    GotoIf(TaggedIsSmi(item), not_cloned);
    GotoIf(IsJSArray(CAST(item)), &is_array);
    GotoIf(IsJSObject(CAST(item)), &is_object);
    Goto(not_cloned);
    BIND(&is_array);
    {
      // Consume the next AllocationSite. All objects inside this array, as well
      // as all sibling objects (until a new array is encountered) will use this
      // AllocationSite. E.g., in [1, 2, {a: 3}, [4, 5], {b: 6}], the object {a:
      // 3} uses the topmost AllocationSite, and the object {b: 6} uses the
      // AllocationSite of [4, 5].
      if (V8_ALLOCATION_SITE_TRACKING_BOOL) {
        current_allocation_site =
            LoadNestedAllocationSite(CAST(current_allocation_site.value()));
        // Ensure we're consuming the AllocationSites in the correct order.
        CSA_DCHECK(
            this,
            TaggedEqual(LoadBoilerplate(CAST(current_allocation_site.value())),
                        item));
      }
      auto clone_and_next_allocation_site = CallBuiltin<PairT<Object, Object>>(
          Builtin::kCreateArrayFromSlowBoilerplateHelper, context,
          current_allocation_site.value(), item);
      clone = Projection<0>(clone_and_next_allocation_site);
      GotoIf(IsUndefined(clone.value()), bailout);
      current_allocation_site = Projection<1>(clone_and_next_allocation_site);
      Goto(cloned);
    }
    BIND(&is_object);
    {
      auto clone_and_next_allocation_site = CallBuiltin<PairT<Object, Object>>(
          Builtin::kCreateObjectFromSlowBoilerplateHelper, context,
          current_allocation_site.value(), item);
      clone = Projection<0>(clone_and_next_allocation_site);
      GotoIf(IsUndefined(clone.value()), bailout);
      current_allocation_site = Projection<1>(clone_and_next_allocation_site);
      Goto(cloned);
    }
  }
References CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::IsJSArray(), v8::internal::CodeStubAssembler::IsJSObject(), v8::internal::CodeStubAssembler::LoadBoilerplate(), v8::internal::CodeStubAssembler::LoadNestedAllocationSite(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::CodeStubAssembler::TaggedIsSmi(), V8_ALLOCATION_SITE_TRACKING_BOOL, and v8::internal::compiler::TypedCodeAssemblerVariable< T >::value().
Referenced by CloneElementsOfFixedArray().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-array-gen.cc