v8::internal::FullMaybeObjectSlot Class Reference
#include <slots.h>
Public Types
using TObject = Tagged< MaybeObject >
using THeapObjectSlot = FullHeapObjectSlot
Public Member Functions
FullMaybeObjectSlot ()
FullMaybeObjectSlot (Address ptr)
FullMaybeObjectSlot (TaggedBase *ptr)
FullMaybeObjectSlot (Tagged< MaybeObject > *ptr)
template<typename T >
FullMaybeObjectSlot (SlotBase< T, TData, kSlotDataAlignment > slot)
Tagged< MaybeObject > operator* () const
Tagged< MaybeObject > load () const
Tagged< MaybeObject > load (PtrComprCageBase cage_base) const
void store (Tagged< MaybeObject > value) const
Tagged< MaybeObject > Relaxed_Load () const
Tagged< MaybeObject > Relaxed_Load (PtrComprCageBase cage_base) const
Address Relaxed_Load_Raw () const
void Relaxed_Store (Tagged< MaybeObject > value) const
void Release_CompareAndSwap (Tagged< MaybeObject > old, Tagged< MaybeObject > target) const
Static Public Member Functions
static Tagged< Object > RawToTagged (PtrComprCageBase cage_base, Address raw)
Static Public Attributes
static constexpr bool kCanBeWeak = true
Additional Inherited Members
Detailed Description
Definition at line 152 of file slots.h.
Member Typedef Documentation
THeapObjectSlot
using v8::internal::FullMaybeObjectSlot::THeapObjectSlot = FullHeapObjectSlot
Definition at line 156 of file slots.h.
TObject
using v8::internal::FullMaybeObjectSlot::TObject = Tagged<MaybeObject>
Definition at line 155 of file slots.h.
Constructor & Destructor Documentation
FullMaybeObjectSlot() [1/5]
v8::internal::FullMaybeObjectSlot::FullMaybeObjectSlot () [inline]
Definition at line 161 of file slots.h.
: SlotBase(kNullAddress) {}
FullMaybeObjectSlot() [2/5]
v8::internal::FullMaybeObjectSlot::FullMaybeObjectSlot (Address ptr) [inline], [explicit]
Definition at line 162 of file slots.h.
: SlotBase(ptr) {}
FullMaybeObjectSlot() [3/5]
v8::internal::FullMaybeObjectSlot::FullMaybeObjectSlot (TaggedBase * ptr) [inline], [explicit]
Definition at line 163 of file slots.h.
      : SlotBase(reinterpret_cast<Address>(ptr)) {}
FullMaybeObjectSlot() [4/5]
v8::internal::FullMaybeObjectSlot::FullMaybeObjectSlot (Tagged< MaybeObject > * ptr) [inline], [explicit]
Definition at line 170 of file slots.h.
      : SlotBase(reinterpret_cast<Address>(ptr)) {}
FullMaybeObjectSlot() [5/5]
template<typename T >
v8::internal::FullMaybeObjectSlot::FullMaybeObjectSlot (SlotBase< T, TData, kSlotDataAlignment > slot) [inline], [explicit]
Definition at line 173 of file slots.h.
      : SlotBase(slot.address()) {}
Member Function Documentation
load() [1/2]
Tagged< MaybeObject > v8::internal::FullMaybeObjectSlot::load () const [inline]
Definition at line 130 of file slots-inl.h.
{ return **this; }
Referenced by v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::LogRejectedPromotionForInvalidSubgraph(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::ProcessSlot(), v8::internal::Serializer::ObjectSerializer::VisitPointers(), and v8::internal::Serializer::ObjectSerializer::VisitProtectedPointer().
load() [2/2]
Tagged< MaybeObject > v8::internal::FullMaybeObjectSlot::load (PtrComprCageBase cage_base) const [inline]
Definition at line 132 of file slots-inl.h.
                                      {
  return **this;
}
operator*()
Tagged< MaybeObject > v8::internal::FullMaybeObjectSlot::operator* () const [inline]
Definition at line 126 of file slots-inl.h.
                                                         {
  return Tagged<MaybeObject>(*location());
}
References v8::internal::SlotBase< FullMaybeObjectSlot, Address, kSystemPointerSize >::location().
RawToTagged()
Tagged< Object > v8::internal::FullMaybeObjectSlot::RawToTagged (PtrComprCageBase cage_base, Address raw) [inline], [static]
Definition at line 155 of file slots-inl.h.
                                                             {
  return Tagged<Object>(raw);
}
References v8::internal::Tagged< Object >.
Relaxed_Load() [1/2]
Tagged< MaybeObject > v8::internal::FullMaybeObjectSlot::Relaxed_Load () const [inline]
Definition at line 141 of file slots-inl.h.
                                                            {
  return Tagged<MaybeObject>(base::AsAtomicPointer::Relaxed_Load(location()));
}
References v8::internal::SlotBase< FullMaybeObjectSlot, Address, kSystemPointerSize >::location(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load().
Referenced by v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), Relaxed_Load(), and v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongOldToSharedSlot().
Relaxed_Load() [2/2]
Tagged< MaybeObject > v8::internal::FullMaybeObjectSlot::Relaxed_Load (PtrComprCageBase cage_base) const [inline]
Definition at line 145 of file slots-inl.h.
                                      {
  return Relaxed_Load();
}
References Relaxed_Load().
Relaxed_Load_Raw()
Address v8::internal::FullMaybeObjectSlot::Relaxed_Load_Raw () const [inline]
Definition at line 150 of file slots-inl.h.
                                                    {
  return static_cast<Address>(base::AsAtomicPointer::Relaxed_Load(location()));
}
References v8::internal::SlotBase< FullMaybeObjectSlot, Address, kSystemPointerSize >::location(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load().
Relaxed_Store()
void v8::internal::FullMaybeObjectSlot::Relaxed_Store (Tagged< MaybeObject > value) const [inline]
Definition at line 160 of file slots-inl.h.
                                                                       {
  base::AsAtomicPointer::Relaxed_Store(location(), value.ptr());
}
References v8::internal::SlotBase< FullMaybeObjectSlot, Address, kSystemPointerSize >::location(), v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store(), and v8::internal::value.
Referenced by v8::internal::SlotAccessorForHeapObject::Write(), and v8::internal::SlotAccessorForRootSlots::Write().
Release_CompareAndSwap()
void v8::internal::FullMaybeObjectSlot::Release_CompareAndSwap (Tagged< MaybeObject > old, Tagged< MaybeObject > target) const [inline]
Definition at line 164 of file slots-inl.h.
                                                               {
  base::AsAtomicPointer::Release_CompareAndSwap(location(), old.ptr(),
                                                target.ptr());
}
References v8::internal::SlotBase< FullMaybeObjectSlot, Address, kSystemPointerSize >::location(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Release_CompareAndSwap().
store()
void v8::internal::FullMaybeObjectSlot::store (Tagged< MaybeObject > value) const [inline]
Definition at line 137 of file slots-inl.h.
                                                               {
  *location() = value.ptr();
}
References v8::internal::SlotBase< FullMaybeObjectSlot, Address, kSystemPointerSize >::location(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::ProcessSlot(), v8::internal::Scavenger::ScavengePage(), and v8::internal::MarkCompactCollector::SpecialClearMapSlot().
Member Data Documentation
kCanBeWeak
constexpr bool v8::internal::FullMaybeObjectSlot::kCanBeWeak = true [static], [constexpr]
Definition at line 159 of file slots.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/slots.h
/mnt/V8SourceCode/src/objects/slots-inl.h