v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope Class Reference
Public Member Functions
DeoptFrameScope (MaglevGraphBuilder *builder, Builtin continuation, compiler::OptionalJSFunctionRef maybe_js_target={})
DeoptFrameScope (MaglevGraphBuilder *builder, Builtin continuation, compiler::OptionalJSFunctionRef maybe_js_target, base::Vector< ValueNode *const > parameters)
DeoptFrameScope (MaglevGraphBuilder *builder, ValueNode *receiver)
~DeoptFrameScope ()
DeoptFrameScope * parent () const
bool IsLazyDeoptContinuationFrame () const
DeoptFrame::FrameData & data ()
const DeoptFrame::FrameData & data () const
Private Attributes
MaglevGraphBuilder * builder_
DeoptFrameScope * parent_
DeoptFrame::FrameData data_
Detailed Description
Definition at line 384 of file maglev-graph-builder.cc.
Constructor & Destructor Documentation
DeoptFrameScope() [1/3]
v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::DeoptFrameScope (MaglevGraphBuilder * builder, Builtin continuation, compiler::OptionalJSFunctionRef maybe_js_target = {}) [inline]
Definition at line 386 of file maglev-graph-builder.cc.
                                                                  {})
      : builder_(builder),
        parent_(builder->current_deopt_scope_),
        data_(DeoptFrame::BuiltinContinuationFrameData{
            continuation, {}, builder->GetContext(), maybe_js_target}) {
    builder_->current_interpreter_frame().virtual_objects().Snapshot();
    builder_->current_deopt_scope_ = this;
    builder_->AddDeoptUse(
        data_.get<DeoptFrame::BuiltinContinuationFrameData>().context);
    DCHECK(data_.get<DeoptFrame::BuiltinContinuationFrameData>()
               .parameters.empty());
  }
DeoptFrameScope() [2/3]
v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::DeoptFrameScope (MaglevGraphBuilder * builder, Builtin continuation, compiler::OptionalJSFunctionRef maybe_js_target, base::Vector< ValueNode *const > parameters) [inline]
Definition at line 400 of file maglev-graph-builder.cc.
      : builder_(builder),
        parent_(builder->current_deopt_scope_),
        data_(DeoptFrame::BuiltinContinuationFrameData{
            continuation, builder->zone()->CloneVector(parameters),
            builder->GetContext(), maybe_js_target}) {
    builder_->current_interpreter_frame().virtual_objects().Snapshot();
    builder_->current_deopt_scope_ = this;
    builder_->AddDeoptUse(
        data_.get<DeoptFrame::BuiltinContinuationFrameData>().context);
    if (parameters.size() > 0) {
      if (InlinedAllocation* receiver =
              parameters[0]->TryCast<InlinedAllocation>()) {
        // We escape the first argument, since the builtin continuation call can
        // trigger a stack iteration, which expects the receiver to be a
        // meterialized object.
        receiver->ForceEscaping();
      }
    }
    for (ValueNode* node :
         data_.get<DeoptFrame::BuiltinContinuationFrameData>().parameters) {
      builder_->AddDeoptUse(node);
    }
  }
References v8::internal::maglev::DeoptFrame::BuiltinContinuationFrameData::context, v8::internal::maglev::DeoptFrame::BuiltinContinuationFrameData::parameters, and v8::base::Vector< T >::size().
DeoptFrameScope() [3/3]
v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::DeoptFrameScope (MaglevGraphBuilder * builder, ValueNode * receiver) [inline]
Definition at line 427 of file maglev-graph-builder.cc.
      : builder_(builder),
        parent_(builder->current_deopt_scope_),
        data_(DeoptFrame::ConstructInvokeStubFrameData{
            *builder->compilation_unit(), builder->current_source_position_,
            receiver, builder->GetContext()}) {
    builder_->current_interpreter_frame().virtual_objects().Snapshot();
    builder_->current_deopt_scope_ = this;
    builder_->AddDeoptUse(
        data_.get<DeoptFrame::ConstructInvokeStubFrameData>().receiver);
    builder_->AddDeoptUse(
        data_.get<DeoptFrame::ConstructInvokeStubFrameData>().context);
  }
References v8::internal::maglev::DeoptFrame::ConstructInvokeStubFrameData::context, and v8::internal::maglev::DeoptFrame::ConstructInvokeStubFrameData::receiver.
 DeoptFrameScope()
v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::~DeoptFrameScope () [inline]
Definition at line 441 of file maglev-graph-builder.cc.
                     {
    builder_->current_deopt_scope_ = parent_;
    // We might have cached a checkpointed frame which includes this scope;
    // reset it just in case.
    builder_->latest_checkpointed_frame_.reset();
  }
Member Function Documentation
data() [1/2]
DeoptFrame::FrameData& v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::data () [inline]
Definition at line 468 of file maglev-graph-builder.cc.
{ return data_; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), and v8::internal::maglev::MaglevGraphBuilder::GetLatestCheckpointedFrame().
data() [2/2]
const DeoptFrame::FrameData& v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::data () const [inline]
Definition at line 469 of file maglev-graph-builder.cc.
{ return data_; }
IsLazyDeoptContinuationFrame()
bool v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::IsLazyDeoptContinuationFrame () const [inline]
Definition at line 450 of file maglev-graph-builder.cc.
                                            {
    if (data_.tag() != DeoptFrame::FrameType::kBuiltinContinuationFrame) {
      return false;
    }
    switch (data_.get<DeoptFrame::FrameType::kBuiltinContinuationFrame>()
                .builtin_id) {
      case Builtin::kGetIteratorWithFeedbackLazyDeoptContinuation:
      case Builtin::kCallIteratorWithFeedbackLazyDeoptContinuation:
      case Builtin::kArrayForEachLoopLazyDeoptContinuation:
      case Builtin::kArrayMapLoopLazyDeoptContinuation:
      case Builtin::kGenericLazyDeoptContinuation:
      case Builtin::kToBooleanLazyDeoptContinuation:
        return true;
      default:
        return false;
    }
  }
References v8::internal::maglev::DeoptFrame::kBuiltinContinuationFrame.
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetLatestCheckpointedFrame().
parent()
DeoptFrameScope* v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::parent () const [inline]
Definition at line 448 of file maglev-graph-builder.cc.
{ return parent_; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), and v8::internal::maglev::MaglevGraphBuilder::GetLatestCheckpointedFrame().
Member Data Documentation
builder_
MaglevGraphBuilder* v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::builder_ [private]
Definition at line 472 of file maglev-graph-builder.cc.
data_
DeoptFrame::FrameData v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::data_ [private]
Definition at line 474 of file maglev-graph-builder.cc.
parent_
DeoptFrameScope* v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::parent_ [private]
Definition at line 473 of file maglev-graph-builder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-graph-builder.cc