v8::internal::InternalIndex Class Reference
#include <internal-index.h>
Classes
class Range
Public Member Functions
constexpr InternalIndex (size_t raw)
V8_WARN_UNUSED_RESULT InternalIndex adjust_down (size_t subtract) const
V8_WARN_UNUSED_RESULT InternalIndex adjust_up (size_t add) const
bool is_found () const
bool is_not_found () const
size_t raw_value () const
uint32_t as_uint32 () const
constexpr int as_int () const
bool operator== (const InternalIndex &other) const
InternalIndex operator* ()
bool operator!= (const InternalIndex &other) const
InternalIndex & operator++ ()
bool operator< (const InternalIndex &other) const
Static Public Member Functions
static InternalIndex NotFound ()
Private Attributes
size_t entry_
Static Private Attributes
static const size_t kNotFound = std::numeric_limits<size_t>::max()
Detailed Description
Definition at line 20 of file internal-index.h.
Constructor & Destructor Documentation
InternalIndex()
constexpr v8::internal::InternalIndex::InternalIndex (size_t raw) [inline], [explicit], [constexpr]
Definition at line 22 of file internal-index.h.
: entry_(raw) {}
Referenced by adjust_down(), adjust_up(), v8::internal::InternalIndex::Range::begin(), v8::internal::InternalIndex::Range::end(), and NotFound().
Member Function Documentation
adjust_down()
V8_WARN_UNUSED_RESULT InternalIndex v8::internal::InternalIndex::adjust_down (size_t subtract) const [inline]
Definition at line 25 of file internal-index.h.
                                                                         {
    DCHECK_GE(entry_, subtract);
    return InternalIndex(entry_ - subtract);
  }
References DCHECK_GE, entry_, and InternalIndex().
Referenced by v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::DeleteImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::GetDetailsImpl(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GetDetailsImpl(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GetImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::GetImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::HasEntryImpl(), v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::ReconfigureImpl(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::ReconfigureImpl(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::SetImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::SetImpl(), and v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::SloppyDeleteImpl().
adjust_up()
V8_WARN_UNUSED_RESULT InternalIndex v8::internal::InternalIndex::adjust_up (size_t add) const [inline]
Definition at line 29 of file internal-index.h.
                                                                  {
    DCHECK_LT(entry_, std::numeric_limits<size_t>::max() - add);
    return InternalIndex(entry_ + add);
  }
References DCHECK_LT, entry_, and InternalIndex().
Referenced by v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GetEntryForIndexImpl(), and v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::GetEntryForIndexImpl().
as_int()
constexpr int v8::internal::InternalIndex::as_int () const [inline], [constexpr]
Definition at line 42 of file internal-index.h.
                               {
    DCHECK_GE(std::numeric_limits<int>::max(), entry_);
    return static_cast<int>(entry_);
  }
References DCHECK_GE, and entry_.
Referenced by v8::internal::anonymous_namespace{elements.cc}::SharedArrayElementsAccessor::CompareAndSwapAtomicInternalImpl(), v8::internal::Map::CopyReplaceDescriptor(), v8::internal::OrderedNameDictionary::DetailsAt(), v8::internal::SmallOrderedNameDictionary::DetailsAt(), v8::internal::SwissNameDictionary::DetailsAt(), v8::internal::OrderedNameDictionary::DetailsAtPut(), v8::internal::SmallOrderedNameDictionary::DetailsAtPut(), v8::internal::SwissNameDictionary::DetailsAtPut(), v8::internal::OrderedHashTable< Derived, entrysize >::EntryToIndex(), v8::internal::compiler::MapRef::FindFieldOwner(), v8::internal::Map::FindFieldOwner(), v8::internal::MapUpdater::FindRootMap(), v8::internal::LookupIterator::GetAccessorIndex(), v8::internal::anonymous_namespace{elements.cc}::SharedArrayElementsAccessor::GetAtomicInternalImpl(), v8::internal::DescriptorArray::GetDetails(), v8::internal::LookupIterator::GetFieldDescriptorIndex(), v8::internal::compiler::MapRef::GetFieldIndexFor(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GetImpl(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetImpl(), v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::GetImpl(), v8::internal::DescriptorArray::GetKey(), v8::internal::compiler::MapRef::GetPropertyDetails(), v8::internal::compiler::MapRef::GetPropertyKey(), v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::GetRaw(), v8::internal::anonymous_namespace{js-struct.cc}::GetSpecialSlotValue(), v8::internal::compiler::MapRef::GetStrongValue(), v8::internal::DescriptorArray::GetValue(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::HasEntryImpl(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::index(), v8::internal::Map::InstallDescriptors(), v8::internal::DescriptorArray::IsInitializedDescriptor(), v8::internal::OrderedHashTable< Derived, entrysize >::KeyAt(), v8::internal::SwissNameDictionary::KeyAt(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::name(), v8::internal::EphemeronRememberedSet::RecordEphemeronKeyWrite(), v8::internal::DescriptorArray::Set(), v8::internal::anonymous_namespace{elements.cc}::SharedArrayElementsAccessor::SetAtomicInternalImpl(), v8::internal::DescriptorArray::SetDetails(), v8::internal::SmallOrderedNameDictionary::SetEntry(), v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::SetImpl(), v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::SetImpl(), v8::internal::DescriptorArray::SetKey(), v8::internal::DescriptorArray::SetValue(), v8::internal::anonymous_namespace{elements.cc}::SharedArrayElementsAccessor::SwapAtomicInternalImpl(), v8::internal::wasm::WasmExportWrapperCache::ToArraySlot(), v8::internal::SwissNameDictionary::ToKey(), v8::internal::LookupIterator::TransitionToAccessorPair(), v8::internal::SwissNameDictionary::TryValueAt(), v8::internal::OrderedHashMap::ValueAt(), v8::internal::OrderedNameDictionary::ValueAt(), v8::internal::SmallOrderedNameDictionary::ValueAt(), v8::internal::SwissNameDictionary::ValueAt(), v8::internal::OrderedNameDictionary::ValueAtPut(), v8::internal::SmallOrderedNameDictionary::ValueAtPut(), and v8::internal::SwissNameDictionary::ValueAtPut().
as_uint32()
uint32_t v8::internal::InternalIndex::as_uint32 () const [inline]
Definition at line 38 of file internal-index.h.
                             {
    DCHECK_LE(entry_, std::numeric_limits<uint32_t>::max());
    return static_cast<uint32_t>(entry_);
  }
References DCHECK_LE, and entry_.
Referenced by v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::DeleteImpl(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::DeleteImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::DeleteImpl(), v8::internal::SmiStringCache::Get(), v8::internal::DoubleStringCache::Get(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::GetDetailsImpl(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GetDetailsImpl(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GetImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::GetImpl(), v8::internal::wasm::WasmExportWrapperCache::NextProbe(), v8::internal::HashTableBase::NextProbe(), v8::internal::OffHeapHashTableBase< Derived >::NextProbe(), v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::NormalizeArgumentsElements(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::ReconfigureImpl(), v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::ReconfigureImpl(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::ReconfigureImpl(), v8::internal::SmiStringCache::Set(), v8::internal::DoubleStringCache::Set(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::SetImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::SetImpl(), and v8::internal::LookupIterator::TransitionToAccessorPair().
is_found()
bool v8::internal::InternalIndex::is_found () const [inline]
Definition at line 34 of file internal-index.h.
{ return entry_ != kNotFound; }
References entry_, and kNotFound.
Referenced by v8::internal::BIT_FIELD_ACCESSORS(), v8::internal::JSRegExpResultIndices::BuildIndices(), v8::internal::compiler::AccessInfoFactory::ComputeAccessorDescriptorAccessInfo(), v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::LoadIC::ComputeHandler(), v8::internal::MapUpdater::ConstructNewMap(), v8::internal::anonymous_namespace{elements.cc}::CopyDictionaryToDoubleElements(), v8::internal::anonymous_namespace{elements.cc}::CopyDictionaryToObjectElements(), v8::internal::Genesis::CreateInitialMapForArraySubclass(), v8::internal::OrderedNameDictionary::DeleteEntry(), v8::internal::SmallOrderedNameDictionary::DeleteEntry(), v8::internal::JSReceiver::DeleteNormalizedProperty(), v8::internal::BaseDictionaryShape< Key >::DetailsAt(), v8::internal::GlobalDictionaryShape::DetailsAt(), v8::internal::GlobalDictionaryShape::DetailsAtPut(), v8::internal::MapUpdater::FindRootMap(), v8::internal::MapUpdater::FindTargetMap(), v8::internal::MapUpdater::GetDetails(), v8::internal::MapUpdater::GetFieldType(), v8::internal::MapUpdater::GetOrComputeFieldType(), v8::internal::anonymous_namespace{js-struct.cc}::GetSpecialSlotValue(), v8::internal::MapUpdater::GetValue(), v8::internal::LookupIterator::HasInternalMarkerProperty(), v8::internal::OrderedHashTable< Derived, entrysize >::HasKey(), v8::internal::StringTable::LookupKey(), v8::internal::TemplateInfo::ProbeInstantiationsCache(), v8::internal::ObjectMultiHashTableBase< Derived, N >::Put(), v8::internal::CompilationCacheTable::PutScript(), v8::internal::MapUpdater::ReconfigureToDataField(), v8::internal::SharedStructTypeRegistry::RegisterNoThrow(), v8::internal::JSFinalizationRegistry::RemoveCellFromUnregisterTokenMap(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{runtime-strings.cc}::StringAdd_StringConstant_Internalize(), v8::internal::LookupIterator::TransitionToAccessorPair(), v8::internal::Map::TransitionToAccessorProperty(), v8::internal::JSDataObjectBuilder::TryAddFastPropertyForValue(), and v8::internal::compiler::AccessInfoFactory::TryLoadPropertyDetails().
is_not_found()
bool v8::internal::InternalIndex::is_not_found () const [inline]
Definition at line 35 of file internal-index.h.
{ return entry_ == kNotFound; }
References entry_, and kNotFound.
Referenced by v8::anonymous_namespace{api.cc}::AddPropertiesAndElementsToObject(), v8::internal::anonymous_namespace{literal-objects.cc}::AddToDescriptorArrayTemplate(), v8::internal::anonymous_namespace{literal-objects.cc}::AddToDictionaryTemplate(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectValuesOrEntriesImpl(), v8::internal::OrderedHashTable< Derived, entrysize >::Delete(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GetEntryForIndexImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::GetEntryForIndexImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::GetEntryForIndexImpl(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::GetHolderIfValid(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IndexOfValueImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IndexOfValueImpl(), v8::internal::JSGlobalObject::InvalidatePropertyCell(), v8::internal::ObjectMultiHashTableBase< Derived, N >::Lookup(), v8::internal::NameToIndexHashTable::Lookup(), v8::internal::CompilationCacheTable::LookupEval(), v8::internal::LookupIterator::LookupInRegularHolder(), v8::internal::LookupIterator::LookupInSpecialHolder(), v8::internal::CompilationCacheTable::LookupRegExp(), v8::internal::CompilationCacheTable::LookupScript(), v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::NormalizeArgumentsElements(), v8::internal::LookupIterator::RecheckTypedArrayBounds(), v8::internal::JSFinalizationRegistry::RemoveUnregisterToken(), v8::internal::JSObject::SetNormalizedProperty(), v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::SloppyDeleteImpl(), v8::internal::Isolate::SymbolFor(), v8::internal::LookupIterator::TransitionToAccessorProperty(), v8::internal::compiler::AccessInfoFactory::TryLoadPropertyDetails(), v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting(), and v8::internal::CompilationCacheTable::UpdateEval().
NotFound()
static InternalIndex v8::internal::InternalIndex::NotFound () [inline], [static]
Definition at line 23 of file internal-index.h.
{ return InternalIndex(kNotFound); }
References InternalIndex(), and kNotFound.
Referenced by v8::internal::DescriptorArray::BinarySearch(), v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::DeleteImpl(), v8::internal::FactoryBase< Impl >::DoubleToString(), v8::internal::OrderedHashTable< Derived, entrysize >::FindEntry(), v8::internal::OrderedNameDictionary::FindEntry(), v8::internal::SwissNameDictionary::FindEntry(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetEntryForIndexImpl(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::GetEntryForIndexImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::GetEntryForIndexImpl(), v8::internal::anonymous_namespace{js-struct.cc}::GetSpecialSlotIndex(), v8::internal::DescriptorArray::LinearSearch(), v8::internal::CodeStubAssembler::NameDictionaryLookupWithForwardIndex(), v8::internal::SwissNameDictionary::IndexIterator::operator*(), v8::internal::LookupIterator::RestartInternal(), v8::internal::DescriptorArray::Search(), v8::internal::DescriptorArray::SearchWithCache(), and v8::internal::FactoryBase< Impl >::SmiToString().
operator!=()
bool v8::internal::InternalIndex::operator!= (const InternalIndex & other) const [inline]
Definition at line 53 of file internal-index.h.
                                                    {
    return entry_ != other.entry_;
  }
References entry_.
operator*()
InternalIndex v8::internal::InternalIndex::operator* () [inline]
Definition at line 52 of file internal-index.h.
{ return *this; }
operator++()
InternalIndex& v8::internal::InternalIndex::operator++ () [inline]
Definition at line 56 of file internal-index.h.
                              {
    entry_++;
    return *this;
  }
References entry_.
operator<()
bool v8::internal::InternalIndex::operator< (const InternalIndex & other) const [inline]
Definition at line 61 of file internal-index.h.
                                                   {
    return entry_ < other.entry_;
  }
References entry_.
operator==()
bool v8::internal::InternalIndex::operator== (const InternalIndex & other) const [inline]
Definition at line 47 of file internal-index.h.
                                                    {
    return entry_ == other.entry_;
  }
References entry_.
raw_value()
size_t v8::internal::InternalIndex::raw_value () const [inline]
Definition at line 37 of file internal-index.h.
{ return entry_; }
References entry_.
Referenced by v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::GetInternalImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::HasEntryImpl(), v8::internal::NameDictionaryLookupForwardedString(), v8::internal::NameDictionaryLookupForwardedStringWithHandle(), and v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::SetImpl().
Member Data Documentation
entry_
size_t v8::internal::InternalIndex::entry_ [private]
Definition at line 81 of file internal-index.h.
Referenced by adjust_down(), adjust_up(), as_int(), as_uint32(), is_found(), is_not_found(), operator!=(), operator++(), operator<(), operator==(), and raw_value().
kNotFound
const size_t v8::internal::InternalIndex::kNotFound = std::numeric_limits<size_t>::max() [static], [private]
Definition at line 79 of file internal-index.h.
Referenced by is_found(), is_not_found(), and NotFound().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/internal-index.h