v8::base::TimeTicks Class Reference
#include <time.h>
Public Member Functions
constexpr TimeTicks ()
Static Public Member Functions
static TimeTicks Now ()
static bool IsHighResolution ()
static constexpr TimeTicks FromMsTicksForTesting (int64_t ticks)
Private Member Functions
constexpr TimeTicks (int64_t ticks)
Friends
class time_internal::TimeBase< TimeTicks >
Additional Inherited Members
Detailed Description
Definition at line 392 of file time.h.
Constructor & Destructor Documentation
TimeTicks() [1/2]
constexpr v8::base::TimeTicks::TimeTicks () [inline], [constexpr]
Definition at line 395 of file time.h.
: TimeBase(0) {}
Referenced by Now().
TimeTicks() [2/2]
constexpr v8::base::TimeTicks::TimeTicks (int64_t ticks) [inline], [explicit], [constexpr], [private]
Definition at line 416 of file time.h.
: TimeBase(ticks) {}
Member Function Documentation
FromMsTicksForTesting()
static constexpr TimeTicks v8::base::TimeTicks::FromMsTicksForTesting (int64_t ticks) [inline], [static], [constexpr]
Definition at line 407 of file time.h.
                                                                  {
    return TimeTicks(ticks * kMicrosecondsPerMillisecond);
  }
IsHighResolution()
bool v8::base::TimeTicks::IsHighResolution () [static]
Definition at line 763 of file time.cc.
                                 {
#if V8_OS_DARWIN
  return true;
#elif V8_OS_FUCHSIA
  return true;
#elif V8_OS_POSIX
  static const bool is_high_resolution = IsHighResolutionTimer(CLOCK_MONOTONIC);
  return is_high_resolution;
#else
  return true;
#endif
}
Referenced by v8::internal::wasm::InstanceBuilder::Build(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationTimeCallback::call(), v8::internal::wasm::CompileLazy(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompileNativeModule(), v8::internal::wasm::AsyncStreamingProcessor::Deserialize(), v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetOrCompileNewNativeModule(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgressAfterDeserialization(), v8::internal::wasm::WasmInterpreter::CodeMap::Preprocess(), v8::internal::TurbofanCompilationJob::RecordCompilationStats(), and v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground().
Now()
TimeTicks v8::base::TimeTicks::Now () [static]
Definition at line 736 of file time.cc.
                         {
  int64_t ticks;
#if V8_OS_DARWIN
  static struct mach_timebase_info info;
  if (info.denom == 0) {
    kern_return_t result = mach_timebase_info(&info);
    DCHECK_EQ(KERN_SUCCESS, result);
    USE(result);
  }
  ticks = (mach_absolute_time() / Time::kNanosecondsPerMicrosecond *
           info.numer / info.denom);
#elif V8_OS_SOLARIS
  ticks = (gethrtime() / Time::kNanosecondsPerMicrosecond);
#elif V8_OS_FUCHSIA
  ticks = zx_clock_get_monotonic() / Time::kNanosecondsPerMicrosecond;
#elif V8_OS_POSIX
  ticks = ClockNow(CLOCK_MONOTONIC);
#elif V8_OS_STARBOARD
  ticks = starboard::CurrentMonotonicTime();
#else
#error platform does not implement TimeTicks::Now.
#endif // V8_OS_DARWIN
  // Make sure we never return 0 here.
  return TimeTicks(ticks + 1);
}
References DCHECK_EQ, v8::base::TimeConstants::kNanosecondsPerMicrosecond, v8::base::internal::result, TimeTicks(), and USE.
Referenced by cppgc::internal::MarkerBase::AdvanceMarkingWithLimits(), v8::internal::wasm::WasmExecutionTimer::BeginInterval(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationTimeCallback::call(), cppgc::internal::anonymous_namespace{sweeper.cc}::DeadlineChecker::Check(), v8::internal::Heap::CollectGarbage(), v8::internal::compiler::CompileWasmImportCallWrapper(), v8::internal::IncrementalMarking::CppHeapStep(), v8::platform::tracing::TracingController::CurrentTimestampMicroseconds(), v8::internal::IncrementalMarkingJob::CurrentTimeToTask(), v8::platform::anonymous_namespace{default-platform.cc}::DefaultTimeFunction(), cppgc::internal::anonymous_namespace{marker.cc}::DrainWorklistWithBytesAndTimeDeadline(), v8::internal::wasm::WasmExecutionTimer::EndInterval(), v8::internal::wasm::ExecuteLiftoffCompilation(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), v8::internal::CpuProfile::FinishProfile(), heap::base::IncrementalMarkingSchedule::GetElapsedTimeSinceMarkingStart(), cppgc::internal::StatsCollector::GetRecentAllocationSpeedInBytesPerMs(), heap::base::IncrementalMarkingSchedule::GetTimeSinceLastConcurrentMarkingUpdate(), v8::Shell::GetTimestamp(), v8::internal::MemoryBalancer::HeartbeatUpdate(), cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::IncreaseScopeTime(), v8::internal::TickSample::Init(), v8::internal::anonymous_namespace{perfetto-logger.cc}::NewTracePacket(), heap::base::IncrementalMarkingSchedule::NotifyConcurrentMarkingStart(), heap::base::IncrementalMarkingSchedule::NotifyIncrementalMarkingStart(), v8::internal::GCTracer::NotifyIncrementalMarkingStart(), cppgc::internal::StatsCollector::NotifyMarkingCompleted(), v8::internal::GCTracer::NotifyMarkingStart(), v8::base::ElapsedTimer::Now(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnFinishedUnits(), v8_inspector::V8HeapProfilerAgentImpl::onTimerImpl(), v8::internal::PauseNestedTimedHistogramScope::PauseNestedTimedHistogramScope(), v8::internal::Heap::PerformGarbageCollection(), cppgc::internal::Sweeper::SweeperImpl::PerformSweepOnMutatorThread(), v8::internal::wasm::WasmInterpreter::CodeMap::Preprocess(), v8::internal::MarkCompactCollector::ProcessMarkingWorklist(), v8::base::RandomNumberGenerator::RandomNumberGenerator(), v8::internal::GCTracer::ResetForTesting(), v8::internal::SamplingEventsProcessor::Run(), v8::internal::IncrementalMarkingJob::Task::RunInternal(), v8::internal::MemoryReducer::TimerTask::RunInternal(), v8::internal::IdleTaskOnContextDispose::RunInternal(), v8::internal::IncrementalMarkingJob::ScheduleTask(), v8::internal::Heap::SetUpSpaces(), v8::internal::IncrementalMarking::ShouldWaitForTask(), v8::internal::metrics::TimedScope< T, precision >::Start(), v8::internal::IncrementalMarking::Start(), v8::internal::NestedTimedHistogramScope::StartInteral(), v8::internal::wasm::WasmExecutionTimer::StartInternal(), v8_inspector::V8ProfilerAgentImpl::startPreciseCoverage(), v8::internal::IncrementalMarking::Step(), v8::internal::metrics::TimedScope< T, precision >::Stop(), v8::internal::NestedTimedHistogramScope::StopInternal(), v8::internal::wasm::WasmExecutionTimer::StopInternal(), cppgc::internal::Sweeper::SweeperImpl::SweepForLargeAllocation(), cppgc::internal::Sweeper::SweeperImpl::SweepForNormalAllocation(), cppgc::internal::Sweeper::SweeperImpl::SweepInForegroundTaskImpl(), v8_inspector::V8ProfilerAgentImpl::takePreciseCoverage(), v8::D8Console::Time(), v8::D8Console::TimeEnd(), v8::D8Console::TimeLog(), v8::D8Console::TimeStamp(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TriggerCachingAfterTimeout(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TriggerOutstandingCallbacks(), v8_inspector::V8ProfilerAgentImpl::triggerPreciseCoverageDeltaUpdate(), v8::internal::IncrementalMarking::TryInitializeTaskTimeout(), v8::internal::FutexEmulation::WaitAsync(), v8::internal::ETWJITInterface::EtwIsolateCaptureStateMonitor::WaitFor(), v8::internal::detail::SyncWaiterQueueNode::WaitFor(), v8::internal::FutexEmulation::WaitSync(), v8::internal::wasm::WasmInterpreterRuntime::WasmStackCheck(), v8::internal::PauseNestedTimedHistogramScope::~PauseNestedTimedHistogramScope(), and v8::internal::GCTracer::Scope::~Scope().
Friends And Related Function Documentation
time_internal::TimeBase< TimeTicks >
friend class time_internal::TimeBase< TimeTicks > [friend]
Definition at line 407 of file time.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/platform/time.h
/mnt/V8SourceCode/src/base/platform/time.cc