v8::internal::compiler::turboshaft::LoadEliminationReplacement Class Reference
#include <late-load-elimination-reducer.h>
Public Types
enum class Kind {
kNone
, kLoadElimination
, kTaggedLoadToInt32Load
, kTaggedBitcastElimination
,
kInt32TruncationElimination
 }
Public Member Functions
LoadEliminationReplacement ()
bool IsNone () const
bool IsLoadElimination () const
bool IsTaggedLoadToInt32Load () const
bool IsTaggedBitcastElimination () const
bool IsInt32TruncationElimination () const
OpIndex replacement () const
Static Public Member Functions
static LoadEliminationReplacement None ()
static LoadEliminationReplacement LoadElimination (OpIndex replacement)
static LoadEliminationReplacement TaggedLoadToInt32Load ()
static LoadEliminationReplacement TaggedBitcastElimination ()
static LoadEliminationReplacement Int32TruncationElimination (OpIndex replacement)
Private Member Functions
LoadEliminationReplacement (Kind kind, OpIndex replacement)
Private Attributes
Kind kind_
OpIndex replacement_
Detailed Description
Definition at line 248 of file late-load-elimination-reducer.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::LoadEliminationReplacement::Kind [strong]
Enumerator
kNone
kLoadElimination
kTaggedLoadToInt32Load
kTaggedBitcastElimination
kInt32TruncationElimination
Definition at line 250 of file late-load-elimination-reducer.h.
                  {
    kNone, // We don't replace the operation
    kLoadElimination, // We load eliminate a load operation
    // The following replacements are used for the special case optimization:
    // TruncateWord64ToWord32(
    // BitcastTaggedToWordPtrForTagAndSmiBits(Load(x, Tagged)))
    // =>
    // Load(x, Int32)
    //
    kTaggedLoadToInt32Load, // Turn a tagged load into a direct int32 load.
    kTaggedBitcastElimination, // Remove this (now unused) bitcast.
    kInt32TruncationElimination, // Replace truncation by the updated load.
  };
Constructor & Destructor Documentation
LoadEliminationReplacement() [1/2]
v8::internal::compiler::turboshaft::LoadEliminationReplacement::LoadEliminationReplacement () [inline]
Definition at line 264 of file late-load-elimination-reducer.h.
: kind_(Kind::kNone), replacement_() {}
References v8::internal::kNone.
LoadEliminationReplacement() [2/2]
v8::internal::compiler::turboshaft::LoadEliminationReplacement::LoadEliminationReplacement (Kind kind, OpIndex replacement) [inline], [private]
Definition at line 299 of file late-load-elimination-reducer.h.
      : kind_(kind), replacement_(replacement) {}
Member Function Documentation
Int32TruncationElimination()
static LoadEliminationReplacement v8::internal::compiler::turboshaft::LoadEliminationReplacement::Int32TruncationElimination (OpIndex replacement) [inline], [static]
Definition at line 279 of file late-load-elimination-reducer.h.
                           {
    return LoadEliminationReplacement{Kind::kInt32TruncationElimination,
                                      replacement};
  }
References kInt32TruncationElimination, and replacement().
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run().
IsInt32TruncationElimination()
bool v8::internal::compiler::turboshaft::LoadEliminationReplacement::IsInt32TruncationElimination () const [inline]
Definition at line 293 of file late-load-elimination-reducer.h.
                                            {
    return kind_ == Kind::kInt32TruncationElimination;
  }
References kind_, and kInt32TruncationElimination.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::Change().
IsLoadElimination()
bool v8::internal::compiler::turboshaft::LoadEliminationReplacement::IsLoadElimination () const [inline]
Definition at line 286 of file late-load-elimination-reducer.h.
{ return kind_ == Kind::kLoadElimination; }
References kind_, and kLoadElimination.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::Load(), and v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run().
IsNone()
bool v8::internal::compiler::turboshaft::LoadEliminationReplacement::IsNone () const [inline]
Definition at line 285 of file late-load-elimination-reducer.h.
{ return kind_ == Kind::kNone; }
References kind_, and kNone.
IsTaggedBitcastElimination()
bool v8::internal::compiler::turboshaft::LoadEliminationReplacement::IsTaggedBitcastElimination () const [inline]
Definition at line 290 of file late-load-elimination-reducer.h.
                                          {
    return kind_ == Kind::kTaggedBitcastElimination;
  }
References kind_, and kTaggedBitcastElimination.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::TaggedBitcast().
IsTaggedLoadToInt32Load()
bool v8::internal::compiler::turboshaft::LoadEliminationReplacement::IsTaggedLoadToInt32Load () const [inline]
Definition at line 287 of file late-load-elimination-reducer.h.
                                       {
    return kind_ == Kind::kTaggedLoadToInt32Load;
  }
References kind_, and kTaggedLoadToInt32Load.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::Load().
LoadElimination()
static LoadEliminationReplacement v8::internal::compiler::turboshaft::LoadEliminationReplacement::LoadElimination (OpIndex replacement) [inline], [static]
Definition at line 269 of file late-load-elimination-reducer.h.
                                                                         {
    DCHECK(replacement.valid());
    return LoadEliminationReplacement{Kind::kLoadElimination, replacement};
  }
References v8::internal::DCHECK(), kLoadElimination, replacement(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad().
None()
static LoadEliminationReplacement v8::internal::compiler::turboshaft::LoadEliminationReplacement::None () [inline], [static]
Definition at line 266 of file late-load-elimination-reducer.h.
                                           {
    return LoadEliminationReplacement{};
  }
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad().
replacement()
OpIndex v8::internal::compiler::turboshaft::LoadEliminationReplacement::replacement () const [inline]
Definition at line 296 of file late-load-elimination-reducer.h.
{ return replacement_; }
References replacement_.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::Change(), Int32TruncationElimination(), v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::Load(), LoadElimination(), and v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run().
TaggedBitcastElimination()
static LoadEliminationReplacement v8::internal::compiler::turboshaft::LoadEliminationReplacement::TaggedBitcastElimination () [inline], [static]
Definition at line 276 of file late-load-elimination-reducer.h.
                                                               {
    return LoadEliminationReplacement{Kind::kTaggedBitcastElimination, {}};
  }
References kTaggedBitcastElimination.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run().
TaggedLoadToInt32Load()
static LoadEliminationReplacement v8::internal::compiler::turboshaft::LoadEliminationReplacement::TaggedLoadToInt32Load () [inline], [static]
Definition at line 273 of file late-load-elimination-reducer.h.
                                                            {
    return LoadEliminationReplacement{Kind::kTaggedLoadToInt32Load, {}};
  }
References kTaggedLoadToInt32Load.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run().
Member Data Documentation
kind_
Kind v8::internal::compiler::turboshaft::LoadEliminationReplacement::kind_ [private]
Definition at line 302 of file late-load-elimination-reducer.h.
Referenced by IsInt32TruncationElimination(), IsLoadElimination(), IsNone(), IsTaggedBitcastElimination(), and IsTaggedLoadToInt32Load().
replacement_
OpIndex v8::internal::compiler::turboshaft::LoadEliminationReplacement::replacement_ [private]
Definition at line 303 of file late-load-elimination-reducer.h.
Referenced by replacement().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/late-load-elimination-reducer.h