v8::internal::compiler::Node::Uses Class Reference
#include <node.h>
Classes
class const_iterator
Public Types
using value_type = Node *
Public Member Functions
const_iterator begin () const
const_iterator end () const
bool empty () const
Uses (Node *node)
Private Attributes
Node * node_
Detailed Description
Definition at line 128 of file node.h.
Member Typedef Documentation
value_type
using v8::internal::compiler::Node::Uses::value_type = Node*
Definition at line 130 of file node.h.
Constructor & Destructor Documentation
Uses()
v8::internal::compiler::Node::Uses::Uses (Node * node) [inline], [explicit]
Definition at line 138 of file node.h.
: node_(node) {}
Member Function Documentation
begin()
Node::Uses::const_iterator v8::internal::compiler::Node::Uses::begin () const [inline]
Definition at line 701 of file node.h.
                                             {
  return const_iterator(this->node_);
}
Referenced by v8::internal::compiler::begin().
empty()
bool v8::internal::compiler::Node::Uses::empty () const
Definition at line 500 of file node.cc.
{ return begin() == end(); }
References v8::internal::compiler::Node::InputEdges::begin(), and v8::internal::compiler::Node::InputEdges::end().
Referenced by v8::internal::compiler::Revectorizer::DecideVectorize(), and v8::internal::compiler::GraphReducer::Replace().
end()
Node::Uses::const_iterator v8::internal::compiler::Node::Uses::end () const [inline]
Definition at line 706 of file node.h.
{ return const_iterator(); }
Referenced by v8::internal::compiler::end().
Member Data Documentation
node_
Node* v8::internal::compiler::Node::Uses::node_ [private]
Definition at line 141 of file node.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/node.h
/mnt/V8SourceCode/src/compiler/node.cc