v8::internal::CppHeap::MetricRecorderAdapter Class Reference
#include <cpp-heap.h>
Public Member Functions
MetricRecorderAdapter (CppHeap &cpp_heap)
void AddMainThreadEvent (const GCCycle &cppgc_event) final
void AddMainThreadEvent (const MainThreadIncrementalMark &cppgc_event) final
void AddMainThreadEvent (const MainThreadIncrementalSweep &cppgc_event) final
void FlushBatchedIncrementalEvents ()
bool FullGCMetricsReportPending () const
bool YoungGCMetricsReportPending () const
const std::optional< cppgc::internal::MetricRecorder::GCCycle > ExtractLastFullGcEvent ()
const std::optional< cppgc::internal::MetricRecorder::GCCycle > ExtractLastYoungGcEvent ()
const std::optional< cppgc::internal::MetricRecorder::MainThreadIncrementalMark > ExtractLastIncrementalMarkEvent ()
void ClearCachedEvents ()
Static Public Attributes
static constexpr int kMaxBatchedEvents = 16
Private Member Functions
Isolate * GetIsolate () const
v8::metrics::Recorder::ContextId GetContextId () const
Private Attributes
CppHeap & cpp_heap_
v8::metrics::GarbageCollectionFullMainThreadBatchedIncrementalMark incremental_mark_batched_events_
v8::metrics::GarbageCollectionFullMainThreadBatchedIncrementalSweep incremental_sweep_batched_events_
std::optional< cppgc::internal::MetricRecorder::GCCycle > last_full_gc_event_
std::optional< cppgc::internal::MetricRecorder::GCCycle > last_young_gc_event_
std::optional< cppgc::internal::MetricRecorder::MainThreadIncrementalMark > last_incremental_mark_event_
Detailed Description
Definition at line 56 of file cpp-heap.h.
Constructor & Destructor Documentation
MetricRecorderAdapter()
v8::internal::CppHeap::MetricRecorderAdapter::MetricRecorderAdapter (CppHeap & cpp_heap) [inline], [explicit]
Definition at line 60 of file cpp-heap.h.
: cpp_heap_(cpp_heap) {}
Member Function Documentation
AddMainThreadEvent() [1/3]
void v8::internal::CppHeap::MetricRecorderAdapter::AddMainThreadEvent (const GCCycle & cppgc_event) [final], [virtual]
Reimplemented from cppgc::internal::MetricRecorder.
Definition at line 363 of file cpp-heap.cc.
                                {
  auto* tracer = GetIsolate()->heap()->tracer();
  if (cppgc_event.type == MetricRecorder::GCCycle::Type::kMinor) {
    DCHECK(!last_young_gc_event_);
    last_young_gc_event_ = cppgc_event;
    tracer->NotifyYoungCppGCCompleted();
  } else {
    DCHECK(!last_full_gc_event_);
    last_full_gc_event_ = cppgc_event;
    tracer->NotifyFullCppGCCompleted();
  }
}
References v8::internal::DCHECK(), GetIsolate(), v8::internal::Isolate::heap(), last_full_gc_event_, last_young_gc_event_, v8::internal::Heap::tracer(), and cppgc::internal::MetricRecorder::GCCycle::type.
AddMainThreadEvent() [2/3]
void v8::internal::CppHeap::MetricRecorderAdapter::AddMainThreadEvent (const MainThreadIncrementalMark & cppgc_event) [final], [virtual]
Reimplemented from cppgc::internal::MetricRecorder.
Definition at line 377 of file cpp-heap.cc.
                                                  {
  // Incremental marking steps might be nested in V8 marking steps. In such
  // cases, stash the relevant values and delegate to V8 to report them. For
  // non-nested steps, report to the Recorder directly.
  if (cpp_heap_.is_in_v8_marking_step_) {
    last_incremental_mark_event_ = cppgc_event;
    return;
  }
  // This is a standalone incremental marking step.
  const std::shared_ptr<metrics::Recorder>& recorder =
      GetIsolate()->metrics_recorder();
  DCHECK_NOT_NULL(recorder);
  if (!recorder->HasEmbedderRecorder()) return;
  incremental_mark_batched_events_.events.emplace_back();
  incremental_mark_batched_events_.events.back().cpp_wall_clock_duration_in_us =
      cppgc_event.duration_us;
  if (incremental_mark_batched_events_.events.size() == kMaxBatchedEvents) {
    recorder->AddMainThreadEvent(std::move(incremental_mark_batched_events_),
                                 GetContextId());
    incremental_mark_batched_events_ = {};
  }
}
References DCHECK_NOT_NULL, cppgc::internal::MetricRecorder::MainThreadIncrementalMark::duration_us, and v8::debug::GetContextId().
AddMainThreadEvent() [3/3]
void v8::internal::CppHeap::MetricRecorderAdapter::AddMainThreadEvent (const MainThreadIncrementalSweep & cppgc_event) [final], [virtual]
Reimplemented from cppgc::internal::MetricRecorder.
Definition at line 401 of file cpp-heap.cc.
                                                   {
  // Incremental sweeping steps are never nested inside V8 sweeping steps, so
  // report to the Recorder directly.
  const std::shared_ptr<metrics::Recorder>& recorder =
      GetIsolate()->metrics_recorder();
  DCHECK_NOT_NULL(recorder);
  if (!recorder->HasEmbedderRecorder()) return;
  incremental_sweep_batched_events_.events.emplace_back();
  incremental_sweep_batched_events_.events.back()
      .cpp_wall_clock_duration_in_us = cppgc_event.duration_us;
  if (incremental_sweep_batched_events_.events.size() == kMaxBatchedEvents) {
    recorder->AddMainThreadEvent(std::move(incremental_sweep_batched_events_),
                                 GetContextId());
    incremental_sweep_batched_events_ = {};
  }
}
References DCHECK_NOT_NULL, cppgc::internal::MetricRecorder::MainThreadIncrementalSweep::duration_us, and v8::debug::GetContextId().
ClearCachedEvents()
void v8::internal::CppHeap::MetricRecorderAdapter::ClearCachedEvents ()
Definition at line 464 of file cpp-heap.cc.
                                                     {
  incremental_mark_batched_events_.events.clear();
  incremental_sweep_batched_events_.events.clear();
  last_incremental_mark_event_.reset();
  last_full_gc_event_.reset();
  last_young_gc_event_.reset();
}
ExtractLastFullGcEvent()
const std::optional< cppgc::internal::MetricRecorder::GCCycle > v8::internal::CppHeap::MetricRecorderAdapter::ExtractLastFullGcEvent ()
Definition at line 444 of file cpp-heap.cc.
                                                     {
  auto res = std::move(last_full_gc_event_);
  last_full_gc_event_.reset();
  return res;
}
ExtractLastIncrementalMarkEvent()
const std::optional< cppgc::internal::MetricRecorder::MainThreadIncrementalMark > v8::internal::CppHeap::MetricRecorderAdapter::ExtractLastIncrementalMarkEvent ()
Definition at line 458 of file cpp-heap.cc.
                                                              {
  auto res = std::move(last_incremental_mark_event_);
  last_incremental_mark_event_.reset();
  return res;
}
Referenced by v8::internal::GCTracer::ReportIncrementalMarkingStepToRecorder().
ExtractLastYoungGcEvent()
const std::optional< cppgc::internal::MetricRecorder::GCCycle > v8::internal::CppHeap::MetricRecorderAdapter::ExtractLastYoungGcEvent ()
Definition at line 451 of file cpp-heap.cc.
                                                      {
  auto res = std::move(last_young_gc_event_);
  last_young_gc_event_.reset();
  return res;
}
FlushBatchedIncrementalEvents()
void v8::internal::CppHeap::MetricRecorderAdapter::FlushBatchedIncrementalEvents ()
Definition at line 419 of file cpp-heap.cc.
                                                                 {
  const std::shared_ptr<metrics::Recorder>& recorder =
      GetIsolate()->metrics_recorder();
  DCHECK_NOT_NULL(recorder);
  if (!incremental_mark_batched_events_.events.empty()) {
    recorder->AddMainThreadEvent(std::move(incremental_mark_batched_events_),
                                 GetContextId());
    incremental_mark_batched_events_ = {};
  }
  if (!incremental_sweep_batched_events_.events.empty()) {
    recorder->AddMainThreadEvent(std::move(incremental_sweep_batched_events_),
                                 GetContextId());
    incremental_sweep_batched_events_ = {};
  }
}
References DCHECK_NOT_NULL, and v8::debug::GetContextId().
FullGCMetricsReportPending()
bool v8::internal::CppHeap::MetricRecorderAdapter::FullGCMetricsReportPending () const
Definition at line 435 of file cpp-heap.cc.
                                                                    {
  return last_full_gc_event_.has_value();
}
GetContextId()
v8::metrics::Recorder::ContextId v8::internal::CppHeap::MetricRecorderAdapter::GetContextId () const [private]
Definition at line 477 of file cpp-heap.cc.
          {
  DCHECK_NOT_NULL(GetIsolate());
  if (GetIsolate()->context().is_null())
    return v8::metrics::Recorder::ContextId::Empty();
  HandleScope scope(GetIsolate());
  return GetIsolate()->GetOrRegisterRecorderContextId(
      GetIsolate()->native_context());
}
References DCHECK_NOT_NULL, v8::metrics::Recorder::ContextId::Empty(), and v8::internal::native_context.
GetIsolate()
Isolate * v8::internal::CppHeap::MetricRecorderAdapter::GetIsolate () const [private]
Definition at line 472 of file cpp-heap.cc.
                                                        {
  DCHECK_NOT_NULL(cpp_heap_.isolate());
  return reinterpret_cast<Isolate*>(cpp_heap_.isolate());
}
References DCHECK_NOT_NULL.
Referenced by AddMainThreadEvent().
YoungGCMetricsReportPending()
bool v8::internal::CppHeap::MetricRecorderAdapter::YoungGCMetricsReportPending () const
Definition at line 439 of file cpp-heap.cc.
                                                                     {
  return last_young_gc_event_.has_value();
}
Member Data Documentation
cpp_heap_
CppHeap& v8::internal::CppHeap::MetricRecorderAdapter::cpp_heap_ [private]
Definition at line 89 of file cpp-heap.h.
incremental_mark_batched_events_
v8::metrics::GarbageCollectionFullMainThreadBatchedIncrementalMark v8::internal::CppHeap::MetricRecorderAdapter::incremental_mark_batched_events_ [private]
Definition at line 91 of file cpp-heap.h.
incremental_sweep_batched_events_
v8::metrics::GarbageCollectionFullMainThreadBatchedIncrementalSweep v8::internal::CppHeap::MetricRecorderAdapter::incremental_sweep_batched_events_ [private]
Definition at line 93 of file cpp-heap.h.
kMaxBatchedEvents
constexpr int v8::internal::CppHeap::MetricRecorderAdapter::kMaxBatchedEvents = 16 [static], [constexpr]
Definition at line 58 of file cpp-heap.h.
Referenced by v8::internal::GCTracer::ReportIncrementalMarkingStepToRecorder(), and v8::internal::GCTracer::ReportIncrementalSweepingStepToRecorder().
last_full_gc_event_
std::optional<cppgc::internal::MetricRecorder::GCCycle> v8::internal::CppHeap::MetricRecorderAdapter::last_full_gc_event_ [private]
Definition at line 94 of file cpp-heap.h.
Referenced by AddMainThreadEvent().
last_incremental_mark_event_
std::optional<cppgc::internal::MetricRecorder::MainThreadIncrementalMark> v8::internal::CppHeap::MetricRecorderAdapter::last_incremental_mark_event_ [private]
Definition at line 98 of file cpp-heap.h.
last_young_gc_event_
std::optional<cppgc::internal::MetricRecorder::GCCycle> v8::internal::CppHeap::MetricRecorderAdapter::last_young_gc_event_ [private]
Definition at line 96 of file cpp-heap.h.
Referenced by AddMainThreadEvent().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc-js/cpp-heap.h
/mnt/V8SourceCode/src/heap/cppgc-js/cpp-heap.cc