v8::internal::maglev::CheckValueEqualsInt32 Class Reference
#include <maglev-ir.h>
Public Member Functions
CheckValueEqualsInt32 (uint64_t bitfield, int32_t value, DeoptimizeReason reason)
int32_t value () const
Input & target_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::EagerDeopt()
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kInt32}
static constexpr int kTargetIndex = 0
Private Types
using Base = FixedInputNodeT< 1, CheckValueEqualsInt32 >
Private Attributes
const int32_t value_
Additional Inherited Members
Detailed Description
Definition at line 6933 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CheckValueEqualsInt32::Base = FixedInputNodeT<1, CheckValueEqualsInt32> [private]
Definition at line 6934 of file maglev-ir.h.
Constructor & Destructor Documentation
CheckValueEqualsInt32()
v8::internal::maglev::CheckValueEqualsInt32::CheckValueEqualsInt32 (uint64_t bitfield, int32_t value, DeoptimizeReason reason) [inline], [explicit]
Definition at line 6937 of file maglev-ir.h.
      : Base(bitfield | ReasonField::encode(reason)), value_(value) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::CheckValueEqualsInt32::GenerateCode (MaglevAssembler * , const ProcessingState &)
options()
auto v8::internal::maglev::CheckValueEqualsInt32::options () const [inline]
Definition at line 6954 of file maglev-ir.h.
{ return std::tuple{value_, deoptimize_reason()}; }
PrintParams()
void v8::internal::maglev::CheckValueEqualsInt32::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8095 of file maglev-ir.cc.
                                                               {
  os << "(" << value() << ", " << DeoptimizeReasonToString(deoptimize_reason())
     << ")";
}
References v8::internal::DeoptimizeReasonToString(), and value().
SetValueLocationConstraints()
void v8::internal::maglev::CheckValueEqualsInt32::SetValueLocationConstraints ()
target_input()
Input& v8::internal::maglev::CheckValueEqualsInt32::target_input () [inline]
Definition at line 6948 of file maglev-ir.h.
{ return input(kTargetIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
value()
int32_t v8::internal::maglev::CheckValueEqualsInt32::value () const [inline]
Definition at line 6945 of file maglev-ir.h.
{ return value_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::CheckValueEqualsInt32::kInputTypes {ValueRepresentation::kInt32} [static], [constexpr]
Definition at line 6943 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CheckValueEqualsInt32::kProperties = OpProperties::EagerDeopt() [static], [constexpr]
Definition at line 6941 of file maglev-ir.h.
kTargetIndex
constexpr int v8::internal::maglev::CheckValueEqualsInt32::kTargetIndex = 0 [static], [constexpr]
Definition at line 6947 of file maglev-ir.h.
value_
const int32_t v8::internal::maglev::CheckValueEqualsInt32::value_ [private]
Definition at line 6959 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc