v8::internal::RegListBase< RegisterT > Class Template Reference
#include <reglist-base.h>
Classes
class Iterator
class ReverseIterator
Public Types
using storage_t = num_registers_sized_storage_t
Public Member Functions
constexpr RegListBase ()=default
constexpr RegListBase (std::initializer_list< RegisterT > regs)
constexpr void set (RegisterT reg)
constexpr void clear (RegisterT reg)
constexpr bool has (RegisterT reg) const
constexpr void clear (RegListBase other)
constexpr bool is_empty () const
constexpr unsigned Count () const
constexpr RegListBase operator& (const RegListBase other) const
constexpr RegListBase operator| (const RegListBase other) const
constexpr RegListBase operator^ (const RegListBase other) const
constexpr RegListBase operator- (const RegListBase other) const
constexpr RegListBase operator| (const RegisterT reg) const
constexpr RegListBase operator- (const RegisterT reg) const
constexpr RegListBase & operator&= (const RegListBase other)
constexpr RegListBase & operator|= (const RegListBase other)
constexpr bool operator== (const RegListBase other) const
constexpr bool operator!= (const RegListBase other) const
constexpr RegisterT first () const
constexpr RegisterT last () const
constexpr RegisterT PopFirst ()
constexpr storage_t bits () const
Iterator begin () const
Iterator end () const
ReverseIterator rbegin () const
ReverseIterator rend () const
Static Public Member Functions
static RegListBase FromBits (storage_t bits)
template<storage_t bits>
static constexpr RegListBase FromBits ()
Private Types
using num_registers_sized_storage_t = std::conditional_t< RegisterT::kNumRegisters<=16, uint16_t, std::conditional_t< RegisterT::kNumRegisters<=32, uint32_t, uint64_t > >
Private Member Functions
constexpr RegListBase (storage_t bits)
Private Attributes
storage_t regs_ = 0
Detailed Description
template<typename RegisterT>
class v8::internal::RegListBase< RegisterT >
Definition at line 21 of file reglist-base.h.
Member Typedef Documentation
num_registers_sized_storage_t
template<typename RegisterT >
using v8::internal::RegListBase< RegisterT >::num_registers_sized_storage_t = std::conditional_t< RegisterT::kNumRegisters <= 16, uint16_t, std::conditional_t<RegisterT::kNumRegisters <= 32, uint32_t, uint64_t> > [private]
Definition at line 22 of file reglist-base.h.
storage_t
template<typename RegisterT >
using v8::internal::RegListBase< RegisterT >::storage_t = num_registers_sized_storage_t
Definition at line 37 of file reglist-base.h.
Constructor & Destructor Documentation
RegListBase() [1/3]
template<typename RegisterT >
constexpr v8::internal::RegListBase< RegisterT >::RegListBase () [constexpr], [default]
Referenced by v8::internal::RegListBase< RegisterT >::FromBits(), v8::internal::RegListBase< RegisterT >::operator&(), v8::internal::RegListBase< RegisterT >::operator-(), v8::internal::RegListBase< RegisterT >::operator^(), and v8::internal::RegListBase< RegisterT >::operator|().
RegListBase() [2/3]
template<typename RegisterT >
constexpr v8::internal::RegListBase< RegisterT >::RegListBase (std::initializer_list< RegisterT > regs) [inline], [constexpr]
Definition at line 41 of file reglist-base.h.
                                                             {
    for (RegisterT reg : regs) {
      set(reg);
    }
  }
References v8::internal::RegListBase< RegisterT >::set().
RegListBase() [3/3]
template<typename RegisterT >
constexpr v8::internal::RegListBase< RegisterT >::RegListBase (storage_t bits) [inline], [explicit], [constexpr], [private]
Definition at line 147 of file reglist-base.h.
: regs_(bits) {}
Member Function Documentation
begin()
template<typename RegisterT >
RegListBase< RegisterT >::Iterator v8::internal::RegListBase< RegisterT >::begin [inline]
Definition at line 196 of file reglist-base.h.
          {
  return Iterator{*this};
}
bits()
template<typename RegisterT >
constexpr storage_t v8::internal::RegListBase< RegisterT >::bits () const [inline], [constexpr]
Definition at line 130 of file reglist-base.h.
{ return regs_; }
References v8::internal::RegListBase< RegisterT >::regs_.
Referenced by v8::internal::compiler::CodeGenerator::FinishFrame(), v8::internal::RegListBase< RegisterT >::FromBits(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_DeoptimizationEntry(), v8::internal::WasmDebugBreakFrameConstants::GetPushedFpRegisterOffset(), v8::internal::WasmDebugBreakFrameConstants::GetPushedGpRegisterOffset(), v8::internal::MacroAssembler::MultiPopFPU(), v8::internal::MacroAssembler::MultiPushFPU(), v8::internal::MacroAssembler::PopAll(), and v8::internal::MacroAssembler::PushAll().
clear() [1/2]
template<typename RegisterT >
constexpr void v8::internal::RegListBase< RegisterT >::clear (RegisterT reg) [inline], [constexpr]
Definition at line 52 of file reglist-base.h.
                                      {
    if (!reg.is_valid()) return;
    regs_ &= ~(storage_t{1} << reg.code());
  }
References v8::internal::RegListBase< RegisterT >::regs_.
Referenced by v8::internal::maglev::AllocateSlow(), v8::internal::maglev::MaglevAssembler::EnsureWritableFastElements(), v8::internal::operator<<(), v8::internal::RegListBase< RegisterT >::PopFirst(), v8::internal::maglev::ValueNode::RemoveRegister(), and v8::internal::maglev::StraightForwardRegisterAllocator::SaveRegisterSnapshot().
clear() [2/2]
template<typename RegisterT >
constexpr void v8::internal::RegListBase< RegisterT >::clear (RegListBase< RegisterT > other) [inline], [constexpr]
Definition at line 62 of file reglist-base.h.
{ regs_ &= ~other.regs_; }
References v8::internal::RegListBase< RegisterT >::regs_.
Count()
template<typename RegisterT >
constexpr unsigned v8::internal::RegListBase< RegisterT >::Count () const [inline], [constexpr]
Definition at line 66 of file reglist-base.h.
                                   {
    return base::bits::CountPopulation(regs_);
  }
References v8::base::bits::CountPopulation(), and v8::internal::RegListBase< RegisterT >::regs_.
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters(), v8::internal::AreAliased(), v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryTemporaries(), v8::internal::maglev::SaveRegisterStateForCall::DefineSafepoint(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitDeoptPoint(), v8::internal::compiler::CodeGenerator::FinishFrame(), v8::internal::RegExpMacroAssemblerRISCV::GetCode(), v8::internal::MacroAssembler::MultiPush(), v8::internal::MacroAssembler::MultiPushFPU(), v8::internal::maglev::ValueNode::num_registers(), v8::internal::wasm::liftoff::PadRegList(), v8::internal::wasm::liftoff::PadVRegList(), v8::internal::MacroAssembler::PopAll(), v8::internal::MacroAssembler::PopCallerSaved(), v8::internal::MacroAssembler::PushAll(), v8::internal::MacroAssembler::PushCallerSaved(), v8::internal::MacroAssembler::RequiredStackSizeForCallerSaved(), v8::internal::RegisterConfiguration::RestrictGeneralRegisters(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SpillLocalsInitially().
end()
template<typename RegisterT >
RegListBase< RegisterT >::Iterator v8::internal::RegListBase< RegisterT >::end [inline]
Definition at line 201 of file reglist-base.h.
                                                                          {
  return Iterator{RegListBase<RegisterT>{}};
}
first()
template<typename RegisterT >
constexpr RegisterT v8::internal::RegListBase< RegisterT >::first () const [inline], [constexpr]
Definition at line 111 of file reglist-base.h.
                                    {
    CHECK(!is_empty());
    int first_code = base::bits::CountTrailingZerosNonZero(regs_);
    return RegisterT::from_code(first_code);
  }
References CHECK, v8::base::bits::CountTrailingZerosNonZero(), v8::internal::RegListBase< RegisterT >::is_empty(), and v8::internal::RegListBase< RegisterT >::regs_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), v8::internal::compiler::CodeGenerator::AssembleReturn(), v8::internal::maglev::ValueNode::FirstRegisterCode(), v8::internal::operator<<(), and v8::internal::RegListBase< RegisterT >::PopFirst().
FromBits() [1/2]
template<typename RegisterT >
template<storage_t bits>
static constexpr RegListBase v8::internal::RegListBase< RegisterT >::FromBits () [inline], [static], [constexpr]
Definition at line 141 of file reglist-base.h.
                                          {
    return RegListBase{bits};
  }
References v8::internal::RegListBase< RegisterT >::bits().
FromBits() [2/2]
template<typename RegisterT >
static RegListBase v8::internal::RegListBase< RegisterT >::FromBits (storage_t bits) [inline], [static]
Definition at line 138 of file reglist-base.h.
{ return RegListBase(bits); }
References v8::internal::RegListBase< RegisterT >::bits(), and v8::internal::RegListBase< RegisterT >::RegListBase().
has()
template<typename RegisterT >
constexpr bool v8::internal::RegListBase< RegisterT >::has (RegisterT reg) const [inline], [constexpr]
Definition at line 57 of file reglist-base.h.
                                          {
    if (!reg.is_valid()) return false;
    return (regs_ & (storage_t{1} << reg.code())) != 0;
  }
References v8::internal::RegListBase< RegisterT >::regs_.
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratchDouble(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryTemporaries(), v8::internal::wasm::liftoff::AtomicBinop32(), v8::internal::maglev::MaglevAssembler::CallBuiltin(), v8::internal::maglev::MaglevAssembler::CheckAndEmitDeferredWriteBarrier(), v8::internal::maglev::SaveRegisterStateForCall::DefineSafepoint(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_shuffle(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_DeoptimizationEntry(), v8::internal::GetRegisterThatIsNotOneOf(), v8::internal::maglev::ValueNode::is_in_register(), v8::internal::wasm::LiftoffRegister::LiftoffRegister(), v8::internal::MacroAssembler::PopAll(), v8::internal::maglev::MaglevAssembler::Prologue(), v8::internal::MacroAssembler::PushAll(), v8::internal::RegisterConfiguration::RestrictGeneralRegisters(), v8::internal::maglev::MaglevAssembler::StringCharCodeOrCodePointAt(), v8::internal::maglev::MaglevAssembler::StringFromCharCode(), v8::internal::maglev::MaglevAssembler::TestTypeOf(), and v8::internal::maglev::MaglevAssembler::TryMigrateInstance().
is_empty()
template<typename RegisterT >
constexpr bool v8::internal::RegListBase< RegisterT >::is_empty () const [inline], [constexpr]
Definition at line 64 of file reglist-base.h.
{ return regs_ == 0; }
References v8::internal::RegListBase< RegisterT >::regs_.
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Acquire(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::AcquireDouble(), v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::AdjustStackPointerForTailCall(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode(), v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), v8::internal::compiler::CodeGenerator::AssembleReturn(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryTemporaries(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedTemporaries(), v8::internal::maglev::MaglevAssembler::CheckAndEmitDeferredWriteBarrier(), v8::internal::compiler::CodeGenerator::FinishFrame(), v8::internal::RegListBase< RegisterT >::first(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::turboshaft::PipelineData::InitializeInstructionComponent(), v8::internal::compiler::TFPipelineData::InitializeInstructionSequence(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::GapMoveTargets::is_empty(), v8::internal::RegListBase< RegisterT >::last(), v8::internal::MacroAssembler::MaybeRestoreRegisters(), v8::internal::MacroAssembler::MaybeSaveRegisters(), v8::internal::MacroAssembler::MultiPop(), v8::internal::MacroAssembler::MultiPush(), v8::internal::operator<<(), v8::internal::MacroAssembler::PopAll(), v8::internal::wasm::LiftoffAssembler::PopRegisters(), v8::internal::MacroAssembler::PushAll(), and v8::internal::wasm::LiftoffAssembler::PushRegisters().
last()
template<typename RegisterT >
constexpr RegisterT v8::internal::RegListBase< RegisterT >::last () const [inline], [constexpr]
Definition at line 117 of file reglist-base.h.
                                   {
    CHECK(!is_empty());
    int last_code =
        8 * sizeof(regs_) - 1 - base::bits::CountLeadingZeros(regs_);
    return RegisterT::from_code(last_code);
  }
References CHECK, v8::base::bits::CountLeadingZeros(), v8::internal::RegListBase< RegisterT >::is_empty(), and v8::internal::RegListBase< RegisterT >::regs_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), and v8::internal::compiler::CodeGenerator::AssembleReturn().
operator!=()
template<typename RegisterT >
constexpr bool v8::internal::RegListBase< RegisterT >::operator!= (const RegListBase< RegisterT > other) const [inline], [constexpr]
Definition at line 107 of file reglist-base.h.
                                                           {
    return regs_ != other.regs_;
  }
References v8::internal::RegListBase< RegisterT >::regs_.
operator&()
template<typename RegisterT >
constexpr RegListBase v8::internal::RegListBase< RegisterT >::operator& (const RegListBase< RegisterT > other) const [inline], [constexpr]
Definition at line 70 of file reglist-base.h.
                                                                 {
    return RegListBase(regs_ & other.regs_);
  }
References v8::internal::RegListBase< RegisterT >::RegListBase(), and v8::internal::RegListBase< RegisterT >::regs_.
operator&=()
template<typename RegisterT >
constexpr RegListBase& v8::internal::RegListBase< RegisterT >::operator&= (const RegListBase< RegisterT > other) [inline], [constexpr]
Definition at line 94 of file reglist-base.h.
                                                             {
    regs_ &= other.regs_;
    return *this;
  }
References v8::internal::RegListBase< RegisterT >::regs_.
operator-() [1/2]
template<typename RegisterT >
constexpr RegListBase v8::internal::RegListBase< RegisterT >::operator- (const RegisterT reg) const [inline], [constexpr]
Definition at line 90 of file reglist-base.h.
                                                             {
    return *this - RegListBase{reg};
  }
operator-() [2/2]
template<typename RegisterT >
constexpr RegListBase v8::internal::RegListBase< RegisterT >::operator- (const RegListBase< RegisterT > other) const [inline], [constexpr]
Definition at line 82 of file reglist-base.h.
                                                                 {
    return RegListBase(regs_ & ~other.regs_);
  }
References v8::internal::RegListBase< RegisterT >::RegListBase(), and v8::internal::RegListBase< RegisterT >::regs_.
operator==()
template<typename RegisterT >
constexpr bool v8::internal::RegListBase< RegisterT >::operator== (const RegListBase< RegisterT > other) const [inline], [constexpr]
Definition at line 104 of file reglist-base.h.
                                                           {
    return regs_ == other.regs_;
  }
References v8::internal::RegListBase< RegisterT >::regs_.
operator^()
template<typename RegisterT >
constexpr RegListBase v8::internal::RegListBase< RegisterT >::operator^ (const RegListBase< RegisterT > other) const [inline], [constexpr]
Definition at line 78 of file reglist-base.h.
                                                                 {
    return RegListBase(regs_ ^ other.regs_);
  }
References v8::internal::RegListBase< RegisterT >::RegListBase(), and v8::internal::RegListBase< RegisterT >::regs_.
operator|() [1/2]
template<typename RegisterT >
constexpr RegListBase v8::internal::RegListBase< RegisterT >::operator| (const RegisterT reg) const [inline], [constexpr]
Definition at line 86 of file reglist-base.h.
                                                             {
    return *this | RegListBase{reg};
  }
operator|() [2/2]
template<typename RegisterT >
constexpr RegListBase v8::internal::RegListBase< RegisterT >::operator| (const RegListBase< RegisterT > other) const [inline], [constexpr]
Definition at line 74 of file reglist-base.h.
                                                                 {
    return RegListBase(regs_ | other.regs_);
  }
References v8::internal::RegListBase< RegisterT >::RegListBase(), and v8::internal::RegListBase< RegisterT >::regs_.
operator|=()
template<typename RegisterT >
constexpr RegListBase& v8::internal::RegListBase< RegisterT >::operator|= (const RegListBase< RegisterT > other) [inline], [constexpr]
Definition at line 99 of file reglist-base.h.
                                                             {
    regs_ |= other.regs_;
    return *this;
  }
References v8::internal::RegListBase< RegisterT >::regs_.
PopFirst()
template<typename RegisterT >
constexpr RegisterT v8::internal::RegListBase< RegisterT >::PopFirst () [inline], [constexpr]
Definition at line 124 of file reglist-base.h.
                                 {
    RegisterT reg = first();
    clear(reg);
    return reg;
  }
References v8::internal::RegListBase< RegisterT >::clear(), and v8::internal::RegListBase< RegisterT >::first().
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Acquire(), v8::internal::UseScratchRegisterScope::AcquireDouble(), and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::AcquireDouble().
rbegin()
template<typename RegisterT >
RegListBase< RegisterT >::ReverseIterator v8::internal::RegListBase< RegisterT >::rbegin [inline]
Definition at line 207 of file reglist-base.h.
                                     {
  return ReverseIterator{*this};
}
rend()
template<typename RegisterT >
RegListBase< RegisterT >::ReverseIterator v8::internal::RegListBase< RegisterT >::rend [inline]
Definition at line 211 of file reglist-base.h.
          {
  return ReverseIterator{RegListBase<RegisterT>{}};
}
set()
template<typename RegisterT >
constexpr void v8::internal::RegListBase< RegisterT >::set (RegisterT reg) [inline], [constexpr]
Definition at line 47 of file reglist-base.h.
                                    {
    if (!reg.is_valid()) return;
    regs_ |= storage_t{1} << reg.code();
  }
References v8::internal::RegListBase< RegisterT >::regs_.
Referenced by v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::Acquire(), v8::internal::maglev::ValueNode::AddRegister(), v8::internal::maglev::MaglevAssembler::AllocateHeapNumber(), v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), v8::internal::compiler::CodeGenerator::AssembleReturn(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryTemporaries(), v8::internal::maglev::MaglevAssembler::CheckAndEmitDeferredWriteBarrier(), v8::internal::WriteBarrierDescriptor::ComputeSavedRegisters(), v8::internal::IndirectPointerWriteBarrierDescriptor::ComputeSavedRegisters(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::GetReservedRegisters(), v8::internal::maglev::detail::MoveArgumentsForBuiltin(), v8::internal::wasm::liftoff::PadRegList(), v8::internal::wasm::liftoff::PadVRegList(), v8::internal::MacroAssembler::PopAll(), v8::internal::MacroAssembler::PushAll(), v8::internal::RegListBase< RegisterT >::RegListBase(), v8::internal::maglev::NodeBase::RequireSpecificDoubleTemporary(), v8::internal::maglev::NodeBase::RequireSpecificTemporary(), v8::internal::maglev::MaglevAssembler::StringFromCharCode(), and v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::WithAllocatableGeneralRegisters().
Member Data Documentation
regs_
template<typename RegisterT >
storage_t v8::internal::RegListBase< RegisterT >::regs_ = 0 [private]
Definition at line 149 of file reglist-base.h.
Referenced by v8::internal::RegListBase< RegisterT >::bits(), v8::internal::RegListBase< RegisterT >::clear(), v8::internal::RegListBase< RegisterT >::Count(), v8::internal::RegListBase< RegisterT >::first(), v8::internal::RegListBase< RegisterT >::has(), v8::internal::RegListBase< RegisterT >::is_empty(), v8::internal::RegListBase< RegisterT >::last(), v8::internal::RegListBase< RegisterT >::operator!=(), v8::internal::RegListBase< RegisterT >::operator&(), v8::internal::RegListBase< RegisterT >::operator&=(), v8::internal::RegListBase< RegisterT >::operator-(), v8::internal::RegListBase< RegisterT >::operator==(), v8::internal::RegListBase< RegisterT >::operator^(), v8::internal::RegListBase< RegisterT >::operator|(), v8::internal::RegListBase< RegisterT >::operator|=(), and v8::internal::RegListBase< RegisterT >::set().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/reglist-base.h