v8::internal::compiler::JSObjectRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< JSObject > object () const
OptionalObjectRef raw_properties_or_hash (JSHeapBroker *broker) const
OptionalObjectRef RawInobjectPropertyAt (JSHeapBroker *broker, FieldIndex index) const
OptionalObjectRef GetOwnConstantElement (JSHeapBroker *broker, FixedArrayBaseRef elements_ref, uint32_t index, CompilationDependencies *dependencies) const
std::optional< Tagged< Object > > GetOwnConstantElementFromHeap (JSHeapBroker *broker, Tagged< FixedArrayBase > elements, ElementsKind elements_kind, uint32_t index) const
OptionalObjectRef GetOwnFastConstantDataProperty (JSHeapBroker *broker, Representation field_representation, FieldIndex index, CompilationDependencies *dependencies) const
std::optional< Float64 > GetOwnFastConstantDoubleProperty (JSHeapBroker *broker, FieldIndex index, CompilationDependencies *dependencies) const
OptionalObjectRef GetOwnDictionaryProperty (JSHeapBroker *broker, InternalIndex index, CompilationDependencies *dependencies) const
OptionalFixedArrayBaseRef elements (JSHeapBroker *broker, RelaxedLoadTag) const
bool IsElementsTenured (FixedArrayBaseRef elements)
OptionalMapRef GetObjectCreateMap (JSHeapBroker *broker) const
Detailed Description
Definition at line 583 of file heap-refs.h.
Member Function Documentation
elements()
OptionalFixedArrayBaseRef v8::internal::compiler::JSObjectRef::elements (JSHeapBroker * broker, RelaxedLoadTag tag) const
Definition at line 2295 of file heap-refs.cc.
                                                                          {
  return TryMakeRef(broker, object()->elements(tag));
}
References broker(), and v8::internal::compiler::TryMakeRef().
Referenced by GetOwnConstantElementFromHeap(), IsElementsTenured(), v8::internal::compiler::AccessInfoFactory::ObjectMayHaveElements(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
GetObjectCreateMap()
OptionalMapRef v8::internal::compiler::JSObjectRef::GetObjectCreateMap (JSHeapBroker * broker) const
Definition at line 2488 of file heap-refs.cc.
                                                                         {
  DirectHandle<Map> map_handle = Cast<Map>(map(broker).object());
  // Note: implemented as an acquire-load.
  if (!map_handle->is_prototype_map()) return {};
  DirectHandle<Object> maybe_proto_info = broker->CanonicalPersistentHandle(
      map_handle->prototype_info(kAcquireLoad));
  if (!IsPrototypeInfo(*maybe_proto_info)) return {};
  Tagged<MaybeObject> maybe_object_create_map =
      Cast<PrototypeInfo>(maybe_proto_info)->ObjectCreateMap(kAcquireLoad);
  if (!maybe_object_create_map.IsWeak()) return {};
  return MapRef(broker->GetOrCreateData(
      maybe_object_create_map.GetHeapObjectAssumeWeak(), kAssumeMemoryFence));
}
References broker(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak(), v8::internal::TaggedImpl< kRefType, StorageType >::IsWeak(), v8::kAcquireLoad, v8::internal::compiler::kAssumeMemoryFence, and v8::internal::compiler::HeapObjectRef::map().
GetOwnConstantElement()
OptionalObjectRef v8::internal::compiler::JSObjectRef::GetOwnConstantElement (JSHeapBroker * broker, FixedArrayBaseRef elements_ref, uint32_t index, CompilationDependencies * dependencies) const
Definition at line 2070 of file heap-refs.cc.
                                                 {
  std::optional<Tagged<Object>> maybe_element = GetOwnConstantElementFromHeap(
      broker, *elements_ref.object(), map(broker).elements_kind(), index);
  if (!maybe_element.has_value()) return {};
  OptionalObjectRef result = TryMakeRef(broker, maybe_element.value());
  if (result.has_value()) {
    dependencies->DependOnOwnConstantElement(*this, index, *result);
  }
  return result;
}
References broker(), v8::internal::index, v8::base::internal::result, and v8::internal::compiler::TryMakeRef().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant().
GetOwnConstantElementFromHeap()
std::optional< Tagged< Object > > v8::internal::compiler::JSObjectRef::GetOwnConstantElementFromHeap (JSHeapBroker * broker, Tagged< FixedArrayBase > elements, ElementsKind elements_kind, uint32_t index) const
Definition at line 2084 of file heap-refs.cc.
                                                      {
  DCHECK_LE(index, JSObject::kMaxElementIndex);
  DirectHandle<JSObject> holder = object();
  // This block is carefully constructed to avoid Ref creation and access since
  // this method may be called after the broker has retired.
  // The relaxed `length` read is safe to use in this case since:
  // - TryGetOwnConstantElement (below) only detects a constant for JSArray
  // holders if the array is frozen.
  // - Frozen arrays can't change length.
  // - We've already seen the corresponding map (when this JSObjectRef was
  // created);
  // - The release-load of that map ensures we read the newest value
  // of `length` below.
  if (i::IsJSArray(*holder)) {
    Tagged<Object> array_length_obj =
        Cast<JSArray>(*holder)->length(broker->isolate(), kRelaxedLoad);
    if (!i::IsSmi(array_length_obj)) {
      // Can't safely read into HeapNumber objects without atomic semantics
      // (relaxed would be sufficient due to the guarantees above).
      return {};
    }
    uint32_t array_length;
    if (!Object::ToArrayLength(array_length_obj, &array_length)) {
      return {};
    }
    // See also ElementsAccessorBase::GetMaxIndex.
    if (index >= array_length) return {};
  }
  Tagged<Object> maybe_element;
  auto result = ConcurrentLookupIterator::TryGetOwnConstantElement(
      &maybe_element, broker->isolate(), broker->local_isolate(), *holder,
      elements, elements_kind, index);
  if (result == ConcurrentLookupIterator::kGaveUp) {
    TRACE_BROKER_MISSING(broker, "JSObject::GetOwnConstantElement on "
                                     << *this << " at index " << index);
    return {};
  } else if (result == ConcurrentLookupIterator::kNotPresent) {
    return {};
  }
  DCHECK_EQ(result, ConcurrentLookupIterator::kPresent);
  return maybe_element;
}
References broker(), DCHECK_EQ, DCHECK_LE, elements(), v8::internal::index, v8::internal::IsSmi(), v8::internal::ConcurrentLookupIterator::kGaveUp, v8::internal::JSObject::kMaxElementIndex, v8::internal::ConcurrentLookupIterator::kNotPresent, v8::internal::ConcurrentLookupIterator::kPresent, v8::kRelaxedLoad, object(), v8::base::internal::result, v8::internal::Object::ToArrayLength(), TRACE_BROKER_MISSING, and v8::internal::ConcurrentLookupIterator::TryGetOwnConstantElement().
GetOwnDictionaryProperty()
OptionalObjectRef v8::internal::compiler::JSObjectRef::GetOwnDictionaryProperty (JSHeapBroker * broker, InternalIndex index, CompilationDependencies * dependencies) const
Definition at line 2173 of file heap-refs.cc.
                                                 {
  CHECK(index.is_found());
  OptionalObjectRef result =
      GetOwnDictionaryPropertyFromHeap(broker, object(), index);
  if (result.has_value()) {
    dependencies->DependOnOwnConstantDictionaryProperty(*this, index, *result);
  }
  return result;
}
References broker(), CHECK, v8::internal::compiler::CompilationDependencies::DependOnOwnConstantDictionaryProperty(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnDictionaryPropertyFromHeap(), v8::internal::index, and v8::base::internal::result.
GetOwnFastConstantDataProperty()
OptionalObjectRef v8::internal::compiler::JSObjectRef::GetOwnFastConstantDataProperty (JSHeapBroker * broker, Representation field_representation, FieldIndex index, CompilationDependencies * dependencies) const
Definition at line 2134 of file heap-refs.cc.
                                                 {
  // Use GetOwnFastConstantDoubleProperty for doubles.
  DCHECK(!field_representation.IsDouble());
  std::optional<Tagged<Object>> constant =
      GetOwnFastConstantDataPropertyFromHeap(broker, *this,
                                             field_representation, index);
  if (!constant) return {};
  OptionalObjectRef result =
      TryMakeRef(broker, broker->CanonicalPersistentHandle(constant.value()));
  if (!result.has_value()) return {};
  dependencies->DependOnOwnConstantDataProperty(*this, map(broker), index,
                                                *result);
  return result;
}
References broker(), v8::internal::DCHECK(), v8::internal::compiler::CompilationDependencies::DependOnOwnConstantDataProperty(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnFastConstantDataPropertyFromHeap(), v8::internal::index, v8::internal::Representation::IsDouble(), v8::internal::compiler::HeapObjectRef::map(), v8::base::internal::result, and v8::internal::compiler::TryMakeRef().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf(), and v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadConstantDataField().
GetOwnFastConstantDoubleProperty()
std::optional< Float64 > v8::internal::compiler::JSObjectRef::GetOwnFastConstantDoubleProperty (JSHeapBroker * broker, FieldIndex index, CompilationDependencies * dependencies) const
Definition at line 2155 of file heap-refs.cc.
                                                 {
  std::optional<Tagged<Object>> constant =
      GetOwnFastConstantDataPropertyFromHeap(broker, *this,
                                             Representation::Double(), index);
  if (!constant) return {};
  DCHECK(i::IsHeapNumber(constant.value()));
  Float64 unboxed_value = Float64::FromBits(
      RacyReadHeapNumberBits(Cast<HeapNumber>(constant.value())));
  dependencies->DependOnOwnConstantDoubleProperty(*this, map(broker), index,
                                                  unboxed_value);
  return unboxed_value;
}
References broker(), v8::internal::DCHECK(), v8::internal::compiler::CompilationDependencies::DependOnOwnConstantDoubleProperty(), v8::internal::Representation::Double(), v8::internal::Float64::FromBits(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnFastConstantDataPropertyFromHeap(), v8::internal::index, v8::internal::compiler::HeapObjectRef::map(), and v8::internal::compiler::anonymous_namespace{heap-refs.cc}::RacyReadHeapNumberBits().
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadConstantDoubleField().
IsElementsTenured()
bool v8::internal::compiler::JSObjectRef::IsElementsTenured (FixedArrayBaseRef elements)
Definition at line 1350 of file heap-refs.cc.
                                                              {
  return !HeapLayout::InYoungGeneration(*elements.object());
}
References elements(), and v8::internal::HeapLayout::InYoungGeneration().
Referenced by v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
object()
IndirectHandle<JSObject> v8::internal::compiler::JSObjectRef::object () const
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeDictionaryProtoAccessInfo(), GetOwnConstantElementFromHeap(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnFastConstantDataPropertyFromHeap(), v8::internal::compiler::AccessInfoFactory::ObjectMayHaveOwnProperties(), and RawInobjectPropertyAt().
raw_properties_or_hash()
OptionalObjectRef v8::internal::compiler::JSObjectRef::raw_properties_or_hash (JSHeapBroker * broker) const
Definition at line 1317 of file heap-refs.cc.
                                {
  return TryMakeRef(broker, object()->raw_properties_or_hash());
}
References broker(), and v8::internal::compiler::TryMakeRef().
Referenced by v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
RawInobjectPropertyAt()
OptionalObjectRef v8::internal::compiler::JSObjectRef::RawInobjectPropertyAt (JSHeapBroker * broker, FieldIndex index) const
Definition at line 1322 of file heap-refs.cc.
                                                                             {
  CHECK(index.is_inobject());
  Handle<Object> value;
  {
    DisallowGarbageCollection no_gc;
    PtrComprCageBase cage_base = broker->cage_base();
    Tagged<Map> current_map = object()->map(cage_base, kAcquireLoad);
    // If the map changed in some prior GC epoch, our {index} could be
    // outside the valid bounds of the cached map.
    if (*map(broker).object() != current_map) {
      TRACE_BROKER_MISSING(broker, "Map change detected in " << *this);
      return {};
    }
    std::optional<Tagged<Object>> maybe_value =
        object()->RawInobjectPropertyAt(cage_base, current_map, index);
    if (!maybe_value.has_value()) {
      TRACE_BROKER_MISSING(broker,
                           "Unable to safely read property in " << *this);
      return {};
    }
    value = broker->CanonicalPersistentHandle(maybe_value.value());
  }
  return TryMakeRef(broker, value);
}
References broker(), CHECK, v8::internal::index, v8::kAcquireLoad, v8::internal::compiler::HeapObjectRef::map(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, object(), TRACE_BROKER_MISSING, v8::internal::compiler::TryMakeRef(), and v8::internal::value.
Referenced by v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc