v8::internal::InstructionStream Class Reference
#include <instruction-stream.h>
Classes
class BodyDescriptor
class WriteBarrierPromise
Public Member Functions
Address instruction_start () const
Tagged< Code > code (AcquireLoadTag tag) const
Tagged< Object > raw_code (AcquireLoadTag tag) const
bool TryGetCode (Tagged< Code > *code_out, AcquireLoadTag tag) const
bool TryGetCodeUnchecked (Tagged< Code > *code_out, AcquireLoadTag tag) const
Address constant_pool () const
Tagged< TrustedByteArray > relocation_info () const
Tagged< TrustedByteArray > unchecked_relocation_info () const
uint8_t * relocation_start () const
uint8_t * relocation_end () const
int relocation_size () const
Address body_end () const
int Size () const
void Relocate (WritableJitAllocation &jit_allocation, intptr_t delta)
void Finalize (Tagged< Code > code, Tagged< TrustedByteArray > reloc_info, CodeDesc desc, Heap *heap)
bool IsFullyInitialized ()
Static Public Member Functions
static constexpr int TrailingPaddingSizeFor (uint32_t body_size)
static constexpr int SizeFor (int body_size)
static Tagged< InstructionStream > FromTargetAddress (Address address)
static Tagged< InstructionStream > FromEntryAddress (Address location_of_address)
static Tagged< InstructionStream > Initialize (Tagged< HeapObject > self, Tagged< Map > map, uint32_t body_size, int constant_pool_offset, Tagged< TrustedByteArray > reloc_info)
Static Public Attributes
static constexpr bool kOnHeapBodyIsContiguous = true
static constexpr bool kOffHeapBodyIsContiguous = false
static constexpr bool kBodyIsContiguous
static constexpr int kMetadataAlignment = kIntSize
static constexpr int kCodeAlignmentMinusCodeHeader
Private Member Functions
WriteBarrierPromise RelocateFromDesc (WritableJitAllocation &jit_allocation, Heap *heap, const CodeDesc &desc, Address constant_pool, const DisallowGarbageCollection &no_gc)
void RelocateFromDescWriteBarriers (Heap *heap, const CodeDesc &desc, Address constant_pool, WriteBarrierPromise &promise, const DisallowGarbageCollection &no_gc)
OBJECT_CONSTRUCTORS (InstructionStream, TrustedObject)
Static Private Member Functions
static PtrComprCageBase main_cage_base ()
Friends
class Factory
Additional Inherited Members
Detailed Description
Definition at line 34 of file instruction-stream.h.
Member Function Documentation
body_end()
Address v8::internal::InstructionStream::body_end () const [inline]
Definition at line 171 of file instruction-stream-inl.h.
                                          {
  static_assert(kOnHeapBodyIsContiguous);
  return instruction_start() + body_size();
}
References instruction_start(), and kOnHeapBodyIsContiguous.
code()
Tagged< Code > v8::internal::InstructionStream::code (AcquireLoadTag tag) const [inline]
Definition at line 183 of file instruction-stream-inl.h.
                                                             {
  return Cast<Code>(raw_code(tag));
}
References raw_code().
Referenced by Finalize(), FromEntryAddress(), FromTargetAddress(), Relocate(), and RelocateFromDescWriteBarriers().
constant_pool()
Address v8::internal::InstructionStream::constant_pool () const [inline]
Definition at line 38 of file instruction-stream-inl.h.
{ return kNullAddress; }
References v8::internal::kNullAddress.
Referenced by Relocate(), and RelocateFromDesc().
Finalize()
void v8::internal::InstructionStream::Finalize (Tagged< Code > code, Tagged< TrustedByteArray > reloc_info, CodeDesc desc, Heap * heap) [inline]
Definition at line 121 of file instruction-stream-inl.h.
                                                            {
  DisallowGarbageCollection no_gc;
  std::optional<WriteBarrierPromise> promise;
  // Copy the relocation info first before we unlock the Jit allocation.
  // TODO(sroettger): reloc info should live in protected memory.
  DCHECK_EQ(reloc_info->length(), desc.reloc_size);
  CopyBytes(reloc_info->begin(), desc.buffer + desc.reloc_offset,
            static_cast<size_t>(desc.reloc_size));
  {
    WritableJitAllocation writable_allocation =
        ThreadIsolation::LookupJitAllocation(
            address(), InstructionStream::SizeFor(body_size()),
            ThreadIsolation::JitAllocationType::kInstructionStream, true);
    // Copy code and inline metadata.
    static_assert(InstructionStream::kOnHeapBodyIsContiguous);
    writable_allocation.CopyCode(kHeaderSize, desc.buffer,
                                 static_cast<size_t>(desc.instr_size));
    writable_allocation.CopyData(kHeaderSize + desc.instr_size,
                                 desc.unwinding_info,
                                 static_cast<size_t>(desc.unwinding_info_size));
    DCHECK_EQ(desc.body_size(), desc.instr_size + desc.unwinding_info_size);
    DCHECK_EQ(code->body_size(),
              code->instruction_size() + code->metadata_size());
    promise.emplace(RelocateFromDesc(writable_allocation, heap, desc,
                                     code->constant_pool(), no_gc));
    // Publish the code pointer after the istream has been fully initialized.
    writable_allocation.WriteProtectedPointerHeaderSlot<Code, kCodeOffset>(
        code, kReleaseStore);
  }
  // Trigger the write barriers after we dropped the JIT write permissions.
  RelocateFromDescWriteBarriers(heap, desc, code->constant_pool(), *promise,
                                no_gc);
  CONDITIONAL_PROTECTED_POINTER_WRITE_BARRIER(*this, kCodeOffset, code,
                                              UPDATE_WRITE_BARRIER);
  code->FlushICache();
}
References v8::internal::HeapObject::address(), v8::internal::CodeDesc::body_size(), v8::internal::CodeDesc::buffer, code(), v8::internal::Code, CONDITIONAL_PROTECTED_POINTER_WRITE_BARRIER, v8::internal::CopyBytes(), v8::internal::WritableJitAllocation::CopyCode(), v8::internal::WritableJitAllocation::CopyData(), DCHECK_EQ, v8::internal::CodeDesc::instr_size, v8::internal::TrustedObject::kHeaderSize, v8::internal::ThreadIsolation::kInstructionStream, kOnHeapBodyIsContiguous, v8::kReleaseStore, v8::internal::ThreadIsolation::LookupJitAllocation(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::CodeDesc::reloc_offset, v8::internal::CodeDesc::reloc_size, RelocateFromDesc(), RelocateFromDescWriteBarriers(), SizeFor(), v8::internal::CodeDesc::unwinding_info, v8::internal::CodeDesc::unwinding_info_size, v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::WritableJitAllocation::WriteProtectedPointerHeaderSlot().
FromEntryAddress()
Tagged< InstructionStream > v8::internal::InstructionStream::FromEntryAddress (Address location_of_address) [inline], [static]
Definition at line 252 of file instruction-stream-inl.h.
                                 {
  Address code_entry = base::Memory<Address>(location_of_address);
  Tagged<HeapObject> code =
      HeapObject::FromAddress(code_entry - InstructionStream::kHeaderSize);
  // Unchecked cast because we can't rely on the map currently not being a
  // forwarding pointer.
  return UncheckedCast<InstructionStream>(code);
}
References code(), v8::internal::HeapObject::FromAddress(), and v8::internal::TrustedObject::kHeaderSize.
Referenced by v8::internal::UpdateTypedSlotHelper::GetTargetObject(), and v8::internal::UpdateTypedSlotHelper::UpdateCodeEntry().
FromTargetAddress()
Tagged< InstructionStream > v8::internal::InstructionStream::FromTargetAddress (Address address) [inline], [static]
Definition at line 233 of file instruction-stream-inl.h.
                     {
  {
    // TODO(jgruber,v8:6666): Support embedded builtins here. We'd need to pass
    // in the current isolate.
    Address start =
        reinterpret_cast<Address>(Isolate::CurrentEmbeddedBlobCode());
    Address end = start + Isolate::CurrentEmbeddedBlobCodeSize();
    CHECK(address < start || address >= end);
  }
  Tagged<HeapObject> code =
      HeapObject::FromAddress(address - InstructionStream::kHeaderSize);
  // Unchecked cast because we can't rely on the map currently not being a
  // forwarding pointer.
  return UncheckedCast<InstructionStream>(code);
}
References v8::internal::HeapObject::address(), CHECK, code(), v8::internal::Isolate::CurrentEmbeddedBlobCode(), v8::internal::Isolate::CurrentEmbeddedBlobCodeSize(), v8::internal::compiler::end(), v8::internal::HeapObject::FromAddress(), and v8::internal::TrustedObject::kHeaderSize.
Referenced by v8::internal::Code::FromTargetAddress(), v8::internal::UpdateTypedSlotHelper::GetTargetObject(), RelocateFromDescWriteBarriers(), v8::internal::WritableRelocInfo::set_target_address(), v8::internal::UpdateTypedSlotHelper::UpdateCodeTarget(), v8::internal::UnreachableObjectsFilter::MarkingVisitor::VisitCodeTarget(), v8::internal::ClientObjectVisitor< Visitor >::VisitCodeTarget(), v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitCodeTarget(), v8::internal::RecordMigratedSlotVisitor::VisitCodeTarget(), and v8::internal::IndexedReferencesExtractor::VisitCodeTarget().
Initialize()
Tagged< InstructionStream > v8::internal::InstructionStream::Initialize (Tagged< HeapObject > self, Tagged< Map > map, uint32_t body_size, int constant_pool_offset, Tagged< TrustedByteArray > reloc_info) [inline], [static]
Definition at line 42 of file instruction-stream-inl.h.
                                                                   {
  {
    WritableJitAllocation writable_allocation =
        ThreadIsolation::RegisterInstructionStreamAllocation(
            self.address(), InstructionStream::SizeFor(body_size));
    CHECK_EQ(InstructionStream::SizeFor(body_size), writable_allocation.size());
    writable_allocation.WriteHeaderSlot<Map, kMapOffset>(map, kRelaxedStore);
    writable_allocation.WriteHeaderSlot<uint32_t, kBodySizeOffset>(body_size);
    if constexpr (V8_EMBEDDED_CONSTANT_POOL_BOOL) {
      writable_allocation.WriteHeaderSlot<int, kConstantPoolOffsetOffset>(
          kHeaderSize + constant_pool_offset);
    }
    // During the Code initialization process, InstructionStream::code is
    // briefly unset (the Code object has not been allocated yet). In this state
    // it is only visible through heap iteration.
    writable_allocation.WriteHeaderSlot<Smi, kCodeOffset>(Smi::zero(),
                                                          kReleaseStore);
    DCHECK(!HeapLayout::InYoungGeneration(reloc_info));
    writable_allocation.WriteProtectedPointerHeaderSlot<TrustedByteArray,
                                                        kRelocationInfoOffset>(
        reloc_info, kRelaxedStore);
    // Clear header padding
    writable_allocation.ClearBytes(kUnalignedSize,
                                   kHeaderSize - kUnalignedSize);
    // Clear trailing padding.
    writable_allocation.ClearBytes(kHeaderSize + body_size,
                                   TrailingPaddingSizeFor(body_size));
  }
  Tagged<InstructionStream> istream = Cast<InstructionStream>(self);
  // We want to keep the code minimal that runs with write access to a JIT
  // allocation, so trigger the write barriers after the WritableJitAllocation
  // went out of scope.
  SLOW_DCHECK(!WriteBarrier::IsRequired(istream, map));
  CONDITIONAL_PROTECTED_POINTER_WRITE_BARRIER(*istream, kRelocationInfoOffset,
                                              reloc_info, UPDATE_WRITE_BARRIER);
  return istream;
}
References v8::internal::HeapObject::address(), CHECK_EQ, v8::internal::WritableJitAllocation::ClearBytes(), CONDITIONAL_PROTECTED_POINTER_WRITE_BARRIER, v8::internal::DCHECK(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::TrustedObject::kHeaderSize, v8::internal::HeapObject::kMapOffset, v8::kRelaxedStore, v8::kReleaseStore, v8::internal::compiler::Map, v8::internal::ThreadIsolation::RegisterInstructionStreamAllocation(), v8::internal::WritableJitAllocation::size(), SizeFor(), SLOW_DCHECK, TrailingPaddingSizeFor(), v8::internal::TrustedByteArray, v8::internal::UPDATE_WRITE_BARRIER, V8_EMBEDDED_CONSTANT_POOL_BOOL, v8::internal::WritableJitAllocation::WriteHeaderSlot(), v8::internal::WritableJitAllocation::WriteProtectedPointerHeaderSlot(), and v8::internal::Smi::zero().
Referenced by v8::internal::Factory::CodeBuilder::BuildInternal().
instruction_start()
Address v8::internal::InstructionStream::instruction_start () const [inline]
Definition at line 208 of file instruction-stream-inl.h.
                                                   {
  return field_address(kHeaderSize);
}
References v8::internal::HeapObject::field_address(), and v8::internal::TrustedObject::kHeaderSize.
Referenced by body_end(), Relocate(), and RelocateFromDesc().
IsFullyInitialized()
bool v8::internal::InstructionStream::IsFullyInitialized () [inline]
Definition at line 167 of file instruction-stream-inl.h.
                                           {
  return raw_code(kAcquireLoad) != Smi::zero();
}
References v8::kAcquireLoad, raw_code(), and v8::internal::Smi::zero().
main_cage_base()
PtrComprCageBase v8::internal::InstructionStream::main_cage_base () [inline], [static], [private]
Definition at line 263 of file instruction-stream-inl.h.
                                                   {
#ifdef V8_COMPRESS_POINTERS
  return PtrComprCageBase{V8HeapCompressionScheme::base()};
#else
  return PtrComprCageBase{};
#endif
}
References v8::internal::V8HeapCompressionSchemeImpl< Cage >::base().
OBJECT_CONSTRUCTORS()
v8::internal::InstructionStream::OBJECT_CONSTRUCTORS (InstructionStream , TrustedObject) [private]
raw_code()
Tagged< Object > v8::internal::InstructionStream::raw_code (AcquireLoadTag tag) const [inline]
Definition at line 176 of file instruction-stream-inl.h.
                                                                   {
  Tagged<Object> value = RawProtectedPointerField(kCodeOffset).Acquire_Load();
  DCHECK(!HeapLayout::InYoungGeneration(value));
  DCHECK(IsSmi(value) || HeapLayout::InTrustedSpace(Cast<HeapObject>(value)));
  return value;
}
References v8::internal::FullObjectSlot::Acquire_Load(), v8::internal::DCHECK(), v8::internal::HeapLayout::InTrustedSpace(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::IsSmi(), v8::internal::TrustedObject::RawProtectedPointerField(), and v8::internal::value.
Referenced by code(), IsFullyInitialized(), TryGetCode(), and TryGetCodeUnchecked().
Relocate()
void v8::internal::InstructionStream::Relocate (WritableJitAllocation & jit_allocation, intptr_t delta)
Definition at line 17 of file instruction-stream.cc.
                                                 {
  Tagged<Code> code;
  if (!TryGetCodeUnchecked(&code, kAcquireLoad)) return;
  // This is called during evacuation and code.instruction_stream() will point
  // to the old object. So pass *this directly to the RelocIterator.
  for (WritableRelocIterator it(jit_allocation, *this, constant_pool(),
                                RelocInfo::kApplyMask);
       !it.done(); it.next()) {
    it.rinfo()->apply(delta);
  }
  FlushInstructionCache(instruction_start(), body_size());
}
References code(), constant_pool(), v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::FlushInstructionCache(), instruction_start(), v8::kAcquireLoad, v8::internal::RelocInfo::kApplyMask, and TryGetCodeUnchecked().
RelocateFromDesc()
InstructionStream::WriteBarrierPromise v8::internal::InstructionStream::RelocateFromDesc (WritableJitAllocation & jit_allocation, Heap * heap, const CodeDesc & desc, Address constant_pool, const DisallowGarbageCollection & no_gc) [private]
Definition at line 34 of file instruction-stream.cc.
                                                                   {
  WriteBarrierPromise write_barrier_promise;
  Assembler* origin = desc.origin;
  const int mode_mask = RelocInfo::PostCodegenRelocationMask();
  for (WritableRelocIterator it(jit_allocation, *this, constant_pool,
                                mode_mask);
       !it.done(); it.next()) {
    // IMPORTANT:
    // this code needs be stay in sync with RelocateFromDescWriteBarriers below.
    RelocInfo::Mode mode = it.rinfo()->rmode();
    if (RelocInfo::IsEmbeddedObjectMode(mode)) {
      DirectHandle<HeapObject> p = it.rinfo()->target_object_handle(origin);
      it.rinfo()->set_target_object(*this, *p, UNSAFE_SKIP_WRITE_BARRIER,
                                    SKIP_ICACHE_FLUSH);
      write_barrier_promise.RegisterAddress(it.rinfo()->pc());
    } else if (RelocInfo::IsCodeTargetMode(mode)) {
      // Rewrite code handles to direct pointers to the first instruction in the
      // code object.
      DirectHandle<HeapObject> p = it.rinfo()->target_object_handle(origin);
      DCHECK(IsCode(*p));
      Tagged<InstructionStream> target_istream =
          Cast<Code>(*p)->instruction_stream();
      it.rinfo()->set_target_address(*this, target_istream->instruction_start(),
                                     UNSAFE_SKIP_WRITE_BARRIER,
                                     SKIP_ICACHE_FLUSH);
      write_barrier_promise.RegisterAddress(it.rinfo()->pc());
    } else if (RelocInfo::IsNearBuiltinEntry(mode)) {
      // Rewrite builtin IDs to PC-relative offset to the builtin entry point.
      Builtin builtin = it.rinfo()->target_builtin_at(origin);
      Address p = Builtins::EntryOf(builtin, heap->isolate());
      // This won't trigger a write barrier, but setting mode to
      // UPDATE_WRITE_BARRIER to make it clear that we didn't forget about it
      // below.
      it.rinfo()->set_target_address(*this, p, UPDATE_WRITE_BARRIER,
                                     SKIP_ICACHE_FLUSH);
      DCHECK_EQ(p, it.rinfo()->target_address());
    } else if (RelocInfo::IsWasmStubCall(mode)) {
#if V8_ENABLE_WEBASSEMBLY
      // Map wasm stub id to builtin.
      uint32_t stub_call_tag = it.rinfo()->wasm_call_tag();
      DCHECK_LT(stub_call_tag,
                static_cast<uint32_t>(Builtin::kFirstBytecodeHandler));
      Builtin builtin = static_cast<Builtin>(stub_call_tag);
      // Store the builtin address in relocation info.
      Address entry = Builtins::EntryOf(builtin, heap->isolate());
      it.rinfo()->set_wasm_stub_call_address(entry);
#else
      UNREACHABLE();
#endif
    } else {
      intptr_t delta =
          instruction_start() - reinterpret_cast<Address>(desc.buffer);
      it.rinfo()->apply(delta);
    }
  }
  return write_barrier_promise;
}
References v8::internal::CodeDesc::buffer, constant_pool(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::Builtins::EntryOf(), instruction_start(), v8::internal::RelocInfo::IsCodeTargetMode(), v8::internal::RelocInfo::IsEmbeddedObjectMode(), v8::internal::RelocInfo::IsNearBuiltinEntry(), v8::internal::RelocInfo::IsWasmStubCall(), mode(), v8::internal::CodeDesc::origin, v8::internal::RelocInfo::PostCodegenRelocationMask(), v8::internal::InstructionStream::WriteBarrierPromise::RegisterAddress(), v8::internal::SKIP_ICACHE_FLUSH, v8::internal::UNREACHABLE(), v8::internal::UNSAFE_SKIP_WRITE_BARRIER, and v8::internal::UPDATE_WRITE_BARRIER.
Referenced by Finalize().
RelocateFromDescWriteBarriers()
void v8::internal::InstructionStream::RelocateFromDescWriteBarriers (Heap * heap, const CodeDesc & desc, Address constant_pool, WriteBarrierPromise & promise, const DisallowGarbageCollection & no_gc) [private]
Definition at line 95 of file instruction-stream.cc.
                                            {
  const int mode_mask = RelocInfo::PostCodegenRelocationMask();
  for (RelocIterator it(code(kAcquireLoad), mode_mask); !it.done(); it.next()) {
    // IMPORTANT:
    // this code needs be stay in sync with RelocateFromDesc above.
    RelocInfo::Mode mode = it.rinfo()->rmode();
    if (RelocInfo::IsEmbeddedObjectMode(mode)) {
      Tagged<HeapObject> p = it.rinfo()->target_object(heap->isolate());
      WriteBarrier::ForRelocInfo(*this, it.rinfo(), p, UPDATE_WRITE_BARRIER);
      write_barrier_promise.ResolveAddress(it.rinfo()->pc());
    } else if (RelocInfo::IsCodeTargetMode(mode)) {
      Tagged<InstructionStream> target_istream =
          InstructionStream::FromTargetAddress(it.rinfo()->target_address());
      WriteBarrier::ForRelocInfo(*this, it.rinfo(), target_istream,
                                 UPDATE_WRITE_BARRIER);
      write_barrier_promise.ResolveAddress(it.rinfo()->pc());
    }
  }
}
References code(), v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::WriteBarrier::ForRelocInfo(), FromTargetAddress(), v8::internal::RelocInfo::IsCodeTargetMode(), v8::internal::RelocInfo::IsEmbeddedObjectMode(), v8::kAcquireLoad, mode(), v8::internal::RelocInfo::PostCodegenRelocationMask(), v8::internal::InstructionStream::WriteBarrierPromise::ResolveAddress(), and v8::internal::UPDATE_WRITE_BARRIER.
Referenced by Finalize().
relocation_end()
uint8_t * v8::internal::InstructionStream::relocation_end () const [inline]
Definition at line 222 of file instruction-stream-inl.h.
                                                 {
  return relocation_info()->end();
}
References relocation_info().
relocation_info()
Tagged< TrustedByteArray > v8::internal::InstructionStream::relocation_info () const [inline]
Definition at line 203 of file instruction-stream-inl.h.
                                                                  {
  return Cast<TrustedByteArray>(
      ReadProtectedPointerField(kRelocationInfoOffset));
}
References v8::internal::TrustedObject::ReadProtectedPointerField().
Referenced by relocation_end(), relocation_size(), and relocation_start().
relocation_size()
int v8::internal::InstructionStream::relocation_size () const [inline]
Definition at line 226 of file instruction-stream-inl.h.
                                             {
  return relocation_info()->length();
}
References relocation_info().
relocation_start()
uint8_t * v8::internal::InstructionStream::relocation_start () const [inline]
Definition at line 218 of file instruction-stream-inl.h.
                                                   {
  return relocation_info()->begin();
}
References relocation_info().
Size()
int v8::internal::InstructionStream::Size () const [inline]
Definition at line 230 of file instruction-stream-inl.h.
{ return SizeFor(body_size()); }
References SizeFor().
SizeFor()
static constexpr int v8::internal::InstructionStream::SizeFor (int body_size) [inline], [static], [constexpr]
Definition at line 102 of file instruction-stream.h.
                                              {
    return kHeaderSize + body_size + TrailingPaddingSizeFor(body_size);
  }
References v8::internal::TrustedObject::kHeaderSize, and TrailingPaddingSizeFor().
Referenced by v8::internal::Factory::CodeBuilder::AllocateUninitializedInstructionStream(), Finalize(), Initialize(), v8::internal::Code::InstructionStreamObjectSize(), and Size().
TrailingPaddingSizeFor()
static constexpr int v8::internal::InstructionStream::TrailingPaddingSizeFor (uint32_t body_size) [inline], [static], [constexpr]
Definition at line 98 of file instruction-stream.h.
                                                                  {
    return RoundUp<kCodeAlignment>(kHeaderSize + body_size) - kHeaderSize -
           body_size;
  }
References v8::internal::TrustedObject::kHeaderSize.
Referenced by Initialize(), and SizeFor().
TryGetCode()
bool v8::internal::InstructionStream::TryGetCode (Tagged< Code > * code_out, AcquireLoadTag tag) const [inline]
Definition at line 187 of file instruction-stream-inl.h.
                                                             {
  Tagged<Object> maybe_code = raw_code(tag);
  if (maybe_code == Smi::zero()) return false;
  *code_out = Cast<Code>(maybe_code);
  return true;
}
References raw_code(), and v8::internal::Smi::zero().
TryGetCodeUnchecked()
bool v8::internal::InstructionStream::TryGetCodeUnchecked (Tagged< Code > * code_out, AcquireLoadTag tag) const [inline]
Definition at line 195 of file instruction-stream-inl.h.
                                                                      {
  Tagged<Object> maybe_code = raw_code(tag);
  if (maybe_code == Smi::zero()) return false;
  *code_out = UncheckedCast<Code>(maybe_code);
  return true;
}
References raw_code(), and v8::internal::Smi::zero().
Referenced by Relocate().
unchecked_relocation_info()
Tagged< TrustedByteArray > v8::internal::InstructionStream::unchecked_relocation_info () const [inline]
Definition at line 212 of file instruction-stream-inl.h.
                                                                            {
  Tagged<Object> value =
      RawProtectedPointerField(kRelocationInfoOffset).Acquire_Load();
  return UncheckedCast<TrustedByteArray>(value);
}
References v8::internal::FullObjectSlot::Acquire_Load(), v8::internal::TrustedObject::RawProtectedPointerField(), and v8::internal::value.
Friends And Related Function Documentation
Factory
friend class Factory [friend]
Definition at line 152 of file instruction-stream.h.
Member Data Documentation
kBodyIsContiguous
constexpr bool v8::internal::InstructionStream::kBodyIsContiguous [static], [constexpr]
Initial value:
=
      kOnHeapBodyIsContiguous && kOffHeapBodyIsContiguous
Definition at line 63 of file instruction-stream.h.
kCodeAlignmentMinusCodeHeader
constexpr int v8::internal::InstructionStream::kCodeAlignmentMinusCodeHeader [static], [constexpr]
Initial value:
=
      kCodeAlignment - kHeaderSize
Definition at line 146 of file instruction-stream.h.
Referenced by v8::internal::Serializer::CopyCode().
kMetadataAlignment
constexpr int v8::internal::InstructionStream::kMetadataAlignment = kIntSize [static], [constexpr]
Definition at line 69 of file instruction-stream.h.
Referenced by v8::internal::PlatformEmbeddedFileWriterAIX::AlignToDataAlignment(), v8::internal::PlatformEmbeddedFileWriterGeneric::AlignToDataAlignment(), v8::internal::PlatformEmbeddedFileWriterMac::AlignToDataAlignment(), v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::SafepointTableBuilder::Emit(), v8::internal::MaglevSafepointTableBuilder::Emit(), v8::internal::maglev::MaglevCodeGenerator::EmitMetadata(), v8::internal::HandlerTable::EmitReturnTableStart(), v8::internal::Assembler::GetCode(), and v8::internal::EmbeddedData::NewFromIsolate().
kOffHeapBodyIsContiguous
constexpr bool v8::internal::InstructionStream::kOffHeapBodyIsContiguous = false [static], [constexpr]
Definition at line 62 of file instruction-stream.h.
Referenced by v8::internal::Code::metadata_start().
kOnHeapBodyIsContiguous
constexpr bool v8::internal::InstructionStream::kOnHeapBodyIsContiguous = true [static], [constexpr]
Definition at line 61 of file instruction-stream.h.
Referenced by v8::internal::wasm::NativeModule::AddCodeForTesting(), body_end(), v8::internal::Factory::CodeBuilder::BuildInternal(), Finalize(), and v8::internal::Code::metadata_start().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/instruction-stream.h
/mnt/V8SourceCode/src/objects/instruction-stream-inl.h
/mnt/V8SourceCode/src/objects/instruction-stream.cc