v8::internal::WasmBuiltinsAssembler Class Reference
#include <builtins-wasm-gen.h>
Public Member Functions
WasmBuiltinsAssembler (compiler::CodeAssemblerState *state)
TNode< WasmTrustedInstanceData > LoadInstanceDataFromFrame ()
TNode< WasmTrustedInstanceData > LoadTrustedDataFromInstance (TNode< WasmInstanceObject >)
TNode< NativeContext > LoadContextFromWasmOrJsFrame ()
TNode< NativeContext > LoadContextFromInstanceData (TNode< WasmTrustedInstanceData >)
TNode< WasmTrustedInstanceData > LoadSharedPartFromInstanceData (TNode< WasmTrustedInstanceData >)
TNode< FixedArray > LoadTablesFromInstanceData (TNode< WasmTrustedInstanceData >)
TNode< FixedArray > LoadFuncRefsFromInstanceData (TNode< WasmTrustedInstanceData >)
TNode< FixedArray > LoadManagedObjectMapsFromInstanceData (TNode< WasmTrustedInstanceData >)
TNode< Float64T > StringToFloat64 (TNode< String >)
TNode< Uint32T > ToUint (wasm::StandardType kind)
TNode< Uint32T > ToUint (wasm::RefTypeKind kind)
TNode< BoolT > InSharedSpace (TNode< HeapObject >)
Additional Inherited Members
Detailed Description
Definition at line 13 of file builtins-wasm-gen.h.
Constructor & Destructor Documentation
WasmBuiltinsAssembler()
v8::internal::WasmBuiltinsAssembler::WasmBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 15 of file builtins-wasm-gen.h.
      : CodeStubAssembler(state) {}
Member Function Documentation
InSharedSpace()
TNode< BoolT > v8::internal::WasmBuiltinsAssembler::InSharedSpace (TNode< HeapObject > object)
Definition at line 189 of file builtins-wasm-gen.cc.
                                                                          {
  TNode<IntPtrT> address = BitcastTaggedToWord(object);
  return IsPageFlagSet(address, MemoryChunk::kInSharedHeap);
}
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::CodeStubAssembler::IsPageFlagSet(), and v8::internal::MemoryChunk::kInSharedHeap.
LoadContextFromInstanceData()
TNode< NativeContext > v8::internal::WasmBuiltinsAssembler::LoadContextFromInstanceData (TNode< WasmTrustedInstanceData > trusted_data)
Definition at line 65 of file builtins-wasm-gen.cc.
                                                 {
  return CAST(
      Load(MachineType::AnyTagged(), trusted_data,
           IntPtrConstant(WasmTrustedInstanceData::kNativeContextOffset -
                          kHeapObjectTag)));
}
References v8::internal::MachineType::AnyTagged(), CAST, v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::kHeapObjectTag, and v8::internal::compiler::CodeAssembler::Load().
Referenced by LoadContextFromWasmOrJsFrame().
LoadContextFromWasmOrJsFrame()
TNode< NativeContext > v8::internal::WasmBuiltinsAssembler::LoadContextFromWasmOrJsFrame ()
Definition at line 31 of file builtins-wasm-gen.cc.
                                                                         {
  static_assert(BuiltinFrameConstants::kFunctionOffset ==
                WasmFrameConstants::kWasmInstanceDataOffset);
  TVARIABLE(NativeContext, context_result);
  TNode<HeapObject> function_or_instance =
      CAST(LoadFromParentFrame(WasmFrameConstants::kWasmInstanceDataOffset));
  Label is_js_function(this);
  Label is_import_data(this);
  Label done(this);
  TNode<Uint16T> instance_type =
      LoadMapInstanceType(LoadMap(function_or_instance));
  GotoIf(IsJSFunctionInstanceType(instance_type), &is_js_function);
  GotoIf(Word32Equal(instance_type, Int32Constant(WASM_IMPORT_DATA_TYPE)),
         &is_import_data);
  context_result = LoadContextFromInstanceData(CAST(function_or_instance));
  Goto(&done);
  BIND(&is_js_function);
  TNode<JSFunction> function = CAST(function_or_instance);
  TNode<Context> context =
      LoadObjectField<Context>(function, JSFunction::kContextOffset);
  context_result = LoadNativeContext(context);
  Goto(&done);
  BIND(&is_import_data);
  TNode<WasmImportData> import_data = CAST(function_or_instance);
  context_result = LoadObjectField<NativeContext>(
      import_data, WasmImportData::kNativeContextOffset);
  Goto(&done);
  BIND(&done);
  return context_result.value();
}
References CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::CodeStubAssembler::IsJSFunctionInstanceType(), v8::internal::BuiltinFrameConstants::kFunctionOffset, LoadContextFromInstanceData(), v8::internal::CodeStubAssembler::LoadFromParentFrame(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapInstanceType(), v8::internal::CodeStubAssembler::LoadNativeContext(), and v8::internal::compiler::CodeAssembler::Word32Equal().
LoadFuncRefsFromInstanceData()
TNode< FixedArray > v8::internal::WasmBuiltinsAssembler::LoadFuncRefsFromInstanceData (TNode< WasmTrustedInstanceData > trusted_data)
Definition at line 88 of file builtins-wasm-gen.cc.
                                                 {
  return LoadObjectField<FixedArray>(trusted_data,
                                     WasmTrustedInstanceData::kFuncRefsOffset);
}
LoadInstanceDataFromFrame()
TNode< WasmTrustedInstanceData > v8::internal::WasmBuiltinsAssembler::LoadInstanceDataFromFrame ()
Definition at line 19 of file builtins-wasm-gen.cc.
                                                 {
  return CAST(LoadFromParentFrame(WasmFrameConstants::kWasmInstanceDataOffset));
}
References CAST, and v8::internal::CodeStubAssembler::LoadFromParentFrame().
LoadManagedObjectMapsFromInstanceData()
TNode< FixedArray > v8::internal::WasmBuiltinsAssembler::LoadManagedObjectMapsFromInstanceData (TNode< WasmTrustedInstanceData > trusted_data)
Definition at line 94 of file builtins-wasm-gen.cc.
                                                 {
  return LoadObjectField<FixedArray>(
      trusted_data, WasmTrustedInstanceData::kManagedObjectMapsOffset);
}
LoadSharedPartFromInstanceData()
TNode< WasmTrustedInstanceData > v8::internal::WasmBuiltinsAssembler::LoadSharedPartFromInstanceData (TNode< WasmTrustedInstanceData > trusted_data)
Definition at line 74 of file builtins-wasm-gen.cc.
                                                 {
  return CAST(LoadProtectedPointerFromObject(
      trusted_data,
      IntPtrConstant(WasmTrustedInstanceData::kProtectedSharedPartOffset -
                     kHeapObjectTag)));
}
References CAST, v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::kHeapObjectTag, and v8::internal::compiler::CodeAssembler::LoadProtectedPointerFromObject().
LoadTablesFromInstanceData()
TNode< FixedArray > v8::internal::WasmBuiltinsAssembler::LoadTablesFromInstanceData (TNode< WasmTrustedInstanceData > trusted_data)
Definition at line 82 of file builtins-wasm-gen.cc.
                                                 {
  return LoadObjectField<FixedArray>(trusted_data,
                                     WasmTrustedInstanceData::kTablesOffset);
}
LoadTrustedDataFromInstance()
TNode< WasmTrustedInstanceData > v8::internal::WasmBuiltinsAssembler::LoadTrustedDataFromInstance (TNode< WasmInstanceObject > instance_object)
Definition at line 24 of file builtins-wasm-gen.cc.
                                               {
  return CAST(LoadTrustedPointerFromObject(
      instance_object, WasmInstanceObject::kTrustedDataOffset,
      kWasmTrustedInstanceDataIndirectPointerTag));
}
References CAST, v8::internal::instance_object, and v8::internal::CodeStubAssembler::LoadTrustedPointerFromObject().
StringToFloat64()
TNode< Float64T > v8::internal::WasmBuiltinsAssembler::StringToFloat64 (TNode< String > input)
Definition at line 100 of file builtins-wasm-gen.cc.
                                                                          {
#ifdef V8_ENABLE_FP_PARAMS_IN_C_LINKAGE
  TNode<ExternalReference> string_to_float64 =
      ExternalConstant(ExternalReference::wasm_string_to_f64());
  return TNode<Float64T>::UncheckedCast(
      CallCFunction(string_to_float64, MachineType::Float64(),
                    std::make_pair(MachineType::AnyTagged(), input)));
#else
  // We could support the fast path by passing the float via a stackslot, see
  // MachineOperatorBuilder::StackSlot.
  TNode<Object> result =
      CallRuntime(Runtime::kStringParseFloat, NoContextConstant(), input);
  return ChangeNumberToFloat64(CAST(result));
#endif
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::CodeStubAssembler::ChangeNumberToFloat64(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::MachineType::Float64(), v8::internal::CodeStubAssembler::NoContextConstant(), v8::base::internal::result, and v8::internal::TNode< T >::UncheckedCast().
ToUint() [1/2]
TNode<Uint32T> v8::internal::WasmBuiltinsAssembler::ToUint (wasm::RefTypeKind kind) [inline]
Definition at line 45 of file builtins-wasm-gen.h.
                                              {
    return Uint32Constant(static_cast<uint32_t>(kind));
  }
References v8::internal::compiler::CodeAssembler::Uint32Constant().
ToUint() [2/2]
TNode<Uint32T> v8::internal::WasmBuiltinsAssembler::ToUint (wasm::StandardType kind) [inline]
Definition at line 41 of file builtins-wasm-gen.h.
                                               {
    return Uint32Constant(static_cast<uint32_t>(kind));
  }
References v8::internal::compiler::CodeAssembler::Uint32Constant().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-wasm-gen.h
/mnt/V8SourceCode/src/builtins/builtins-wasm-gen.cc