v8::V8 Class Reference
Container class for static utility functions.
#include <v8-initialization.h>
Static Public Member Functions
static void SetSnapshotDataBlob (StartupData *startup_blob)
Hand startup data to V8, in case the embedder has chosen to build V8 with external startup data.
static void SetDcheckErrorHandler (DcheckErrorCallback that)
Set the callback to invoke in case of Dcheck failures.
static void SetFatalErrorHandler (V8FatalErrorCallback that)
Set the callback to invoke in the case of CHECK failures or fatal errors.
static void SetFlagsFromString (const char *str)
Sets V8 flags from a string.
static void SetFlagsFromString (const char *str, size_t length)
static void SetFlagsFromCommandLine (int *argc, char **argv, bool remove_flags)
Sets V8 flags from the command line.
static const char * GetVersion ()
Get the version string.
static bool Initialize ()
Initializes V8.
static void SetEntropySource (EntropySource source)
Allows the host application to provide a callback which can be used as a source of entropy for random number generators.
static void SetReturnAddressLocationResolver (ReturnAddressLocationResolver return_address_resolver)
Allows the host application to provide a callback that allows v8 to cooperate with a profiler that rewrites return addresses on stack.
static bool Dispose ()
Releases any resources used by v8 and stops any utility threads that may be running.
static bool InitializeICU (const char *icu_data_file=nullptr)
Initialize the ICU library bundled with V8.
static bool InitializeICUDefaultLocation (const char *exec_path, const char *icu_data_file=nullptr)
Initialize the ICU library bundled with V8.
static void InitializeExternalStartupData (const char *directory_path)
Initialize the external startup data.
static void InitializeExternalStartupDataFromFile (const char *snapshot_blob)
static void InitializePlatform (Platform *platform)
Sets the v8::Platform to use.
static void DisposePlatform ()
Clears all references to the v8::Platform.
static bool EnableWebAssemblyTrapHandler (bool use_v8_signal_handler)
Activate trap-based bounds checking for WebAssembly.
static void SetFatalMemoryErrorCallback (OOMErrorCallback callback)
Allows the host application to provide a callback that will be called when v8 has encountered a fatal failure to allocate memory and is about to terminate.
static void GetSharedMemoryStatistics (SharedMemoryStatistics *statistics)
Get statistics about the shared memory usage.
Private Types
enum BuildConfigurationFeatures {
kPointerCompression = 1 << 0
, k31BitSmis = 1 << 1
, kSandbox = 1 << 2
, kTargetOsIsAndroid = 1 << 3
,
kEnableChecks = 1 << 4
 }
Private Member Functions
V8 ()
Static Private Member Functions
static bool Initialize (int build_config)
Checks that the embedder build configuration is compatible with the V8 binary and if so initializes V8.
Friends
class Context
template<class K , class V , class T >
class PersistentValueMapBase
Detailed Description
Container class for static utility functions.
Definition at line 61 of file v8-initialization.h.
Member Enumeration Documentation
BuildConfigurationFeatures
enum v8::V8::BuildConfigurationFeatures [private]
Enumerator
kPointerCompression
k31BitSmis
kSandbox
kTargetOsIsAndroid
kEnableChecks
Definition at line 293 of file v8-initialization.h.
                                  {
    kPointerCompression = 1 << 0,
    k31BitSmis = 1 << 1,
    kSandbox = 1 << 2,
    kTargetOsIsAndroid = 1 << 3,
    kEnableChecks = 1 << 4,
  };
Constructor & Destructor Documentation
V8()
v8::V8::V8 () [private]
Member Function Documentation
Dispose()
bool v8::V8::Dispose () [static]
Releases any resources used by v8 and stops any utility threads that may be running.
Note that disposing v8 is permanent, it cannot be reinitialized.
It should generally not be necessary to dispose v8 before exiting a process, this should happen automatically. It is only necessary to use if the process needs the resources taken up by v8.
Definition at line 6458 of file api.cc.
                   {
  i::V8::Dispose();
  return true;
}
References v8::internal::V8::Dispose().
Referenced by main(), v8::Shell::OnExit(), and wasm::EngineImpl::~EngineImpl().
DisposePlatform()
void v8::V8::DisposePlatform () [static]
Clears all references to the v8::Platform.
This should be invoked after V8 was disposed.
Definition at line 6334 of file api.cc.
{ i::V8::DisposePlatform(); }
References v8::internal::V8::DisposePlatform().
Referenced by main(), v8::Shell::OnExit(), and wasm::EngineImpl::~EngineImpl().
EnableWebAssemblyTrapHandler()
bool v8::V8::EnableWebAssemblyTrapHandler (bool use_v8_signal_handler) [static]
Activate trap-based bounds checking for WebAssembly.
Parameters
use_v8_signal_handler Whether V8 should install its own signal handler or rely on the embedder's.
Definition at line 6424 of file api.cc.
                                                                {
#if V8_ENABLE_WEBASSEMBLY
  return i::trap_handler::EnableTrapHandler(use_v8_signal_handler);
#else
  return false;
#endif
}
References v8::internal::trap_handler::EnableTrapHandler().
Referenced by v8::Shell::Main().
GetSharedMemoryStatistics()
void v8::V8::GetSharedMemoryStatistics (SharedMemoryStatistics * statistics) [static]
Get statistics about the shared memory usage.
Definition at line 6554 of file api.cc.
                                                                     {
  i::ReadOnlyHeap::PopulateReadOnlySpaceStatistics(statistics);
}
References v8::internal::ReadOnlyHeap::PopulateReadOnlySpaceStatistics().
GetVersion()
const char * v8::V8::GetVersion () [static]
Get the version string.
Definition at line 6519 of file api.cc.
{ return i::Version::GetVersion(); }
References v8::internal::Version::GetVersion().
Referenced by v8::Shell::RunShell(), and v8::Shell::Version().
Initialize() [1/2]
static bool v8::V8::Initialize () [inline], [static]
Initializes V8.
This function needs to be called before the first Isolate is created. It always returns true.
Definition at line 108 of file v8-initialization.h.
                                     {
#ifdef V8_TARGET_OS_ANDROID
    const bool kV8TargetOsIsAndroid = true;
#else
    const bool kV8TargetOsIsAndroid = false;
#endif
#ifdef V8_ENABLE_CHECKS
    const bool kV8EnableChecks = true;
#else
    const bool kV8EnableChecks = false;
#endif
    const int kBuildConfiguration =
        (internal::PointerCompressionIsEnabled() ? kPointerCompression : 0) |
        (internal::SmiValuesAre31Bits() ? k31BitSmis : 0) |
        (internal::SandboxIsEnabled() ? kSandbox : 0) |
        (kV8TargetOsIsAndroid ? kTargetOsIsAndroid : 0) |
        (kV8EnableChecks ? kEnableChecks : 0);
    return Initialize(kBuildConfiguration);
  }
References v8::internal::PointerCompressionIsEnabled(), v8::internal::SandboxIsEnabled(), and v8::internal::SmiValuesAre31Bits().
Referenced by main(), and v8::Shell::Main().
Initialize() [2/2]
bool v8::V8::Initialize (int build_config) [static], [private]
Checks that the embedder build configuration is compatible with the V8 binary and if so initializes V8.
Definition at line 6336 of file api.cc.
                                            {
  const bool kEmbedderPointerCompression =
      (build_config & kPointerCompression) != 0;
  if (kEmbedderPointerCompression != COMPRESS_POINTERS_BOOL) {
    FATAL(
        "Embedder-vs-V8 build configuration mismatch. On embedder side "
        "pointer compression is %s while on V8 side it's %s.",
        kEmbedderPointerCompression ? "ENABLED" : "DISABLED",
        COMPRESS_POINTERS_BOOL ? "ENABLED" : "DISABLED");
  }
  const int kEmbedderSmiValueSize = (build_config & k31BitSmis) ? 31 : 32;
  if (kEmbedderSmiValueSize != internal::kSmiValueSize) {
    FATAL(
        "Embedder-vs-V8 build configuration mismatch. On embedder side "
        "Smi value size is %d while on V8 side it's %d.",
        kEmbedderSmiValueSize, internal::kSmiValueSize);
  }
  const bool kEmbedderSandbox = (build_config & kSandbox) != 0;
  if (kEmbedderSandbox != V8_ENABLE_SANDBOX_BOOL) {
    FATAL(
        "Embedder-vs-V8 build configuration mismatch. On embedder side "
        "sandbox is %s while on V8 side it's %s.",
        kEmbedderSandbox ? "ENABLED" : "DISABLED",
        V8_ENABLE_SANDBOX_BOOL ? "ENABLED" : "DISABLED");
  }
  const bool kEmbedderTargetOsIsAndroid =
      (build_config & kTargetOsIsAndroid) != 0;
#ifdef V8_TARGET_OS_ANDROID
  const bool kV8TargetOsIsAndroid = true;
#else
  const bool kV8TargetOsIsAndroid = false;
#endif
  if (kEmbedderTargetOsIsAndroid != kV8TargetOsIsAndroid) {
    FATAL(
        "Embedder-vs-V8 build configuration mismatch. On embedder side "
        "target OS is %s while on V8 side it's %s.",
        kEmbedderTargetOsIsAndroid ? "Android" : "not Android",
        kV8TargetOsIsAndroid ? "Android" : "not Android");
  }
  const bool kEmbedderEnableChecks = (build_config & kEnableChecks) != 0;
#ifdef V8_ENABLE_CHECKS
  const bool kV8EnableChecks = true;
#else
  const bool kV8EnableChecks = false;
#endif
  if (kEmbedderEnableChecks != kV8EnableChecks) {
    FATAL(
        "Embedder-vs-V8 build configuration mismatch. On embedder side "
        "V8_ENABLE_CHECKS is %s while on V8 side it's %s.",
        kEmbedderEnableChecks ? "ENABLED" : "DISABLED",
        kV8EnableChecks ? "ENABLED" : "DISABLED");
  }
  i::V8::Initialize();
  if (!cppgc::IsInitialized()) {
    // cppgc::InitializeProcess() has to becalled after V8::Initialize().
    // V8::Initialize() triggers OS::Platform initialization code that is needed
    // by the default page allocator on Fuchsia to allocate memory correctly.
    cppgc::InitializeProcess(i::V8::GetCurrentPlatform()->GetPageAllocator());
  }
  return true;
}
References COMPRESS_POINTERS_BOOL, FATAL, v8::internal::V8::GetCurrentPlatform(), v8::internal::V8::Initialize(), cppgc::InitializeProcess(), cppgc::IsInitialized(), v8::internal::kSmiValueSize, and V8_ENABLE_SANDBOX_BOOL.
InitializeExternalStartupData()
void v8::V8::InitializeExternalStartupData (const char * directory_path) [static]
Initialize the external startup data.
The embedder only needs to invoke this method when external startup data was enabled in a build.
If V8 was compiled with the startup data in an external file, then V8 needs to be given those external files during startup. There are three ways to do this:
InitializeExternalStartupData(const char*) This will look in the given directory for the file `snapshot_blob.bin`.
InitializeExternalStartupDataFromFile(const char*) As above, but will directly use the given file name.
Call SetSnapshotDataBlob. This will read the blobs from the given data structure and will not perform any file IO.
Definition at line 6510 of file api.cc.
                                                                   {
  i::InitializeExternalStartupData(directory_path);
}
References v8::internal::InitializeExternalStartupData().
Referenced by v8::Shell::Main().
InitializeExternalStartupDataFromFile()
void v8::V8::InitializeExternalStartupDataFromFile (const char * snapshot_blob) [static]
Definition at line 6515 of file api.cc.
                                                                          {
  i::InitializeExternalStartupDataFromFile(snapshot_blob);
}
References v8::internal::InitializeExternalStartupDataFromFile().
Referenced by v8::Shell::Main().
InitializeICU()
bool v8::V8::InitializeICU (const char * icu_data_file = nullptr) [static]
Initialize the ICU library bundled with V8.
The embedder should only invoke this method when using the bundled ICU. Returns true on success.
If V8 was compiled with the ICU data in an external file, the location of the data file has to be provided.
Definition at line 6501 of file api.cc.
                                                  {
  return i::InitializeICU(icu_data_file);
}
References v8::internal::InitializeICU().
InitializeICUDefaultLocation()
bool v8::V8::InitializeICUDefaultLocation (const char * exec_path, const char * icu_data_file = nullptr) [static]
Initialize the ICU library bundled with V8.
The embedder should only invoke this method when using the bundled ICU. If V8 was compiled with the ICU data in an external file and when the default location of that file should be used, a path to the executable must be provided. Returns true on success.
The default is a file called icudtl.dat side-by-side with the executable.
Optionally, the location of the data file can be provided to override the default.
Definition at line 6505 of file api.cc.
                                                                     {
  return i::InitializeICUDefaultLocation(exec_path, icu_data_file);
}
References v8::internal::InitializeICUDefaultLocation().
Referenced by main(), and v8::Shell::Main().
InitializePlatform()
void v8::V8::InitializePlatform (Platform * platform) [static]
Sets the v8::Platform to use.
This should be invoked before V8 is initialized.
Definition at line 6330 of file api.cc.
                                                {
  i::V8::InitializePlatform(platform);
}
References v8::internal::V8::InitializePlatform().
Referenced by main(), and v8::Shell::Main().
SetDcheckErrorHandler()
void v8::V8::SetDcheckErrorHandler (DcheckErrorCallback that) [static]
Set the callback to invoke in case of Dcheck failures.
Definition at line 428 of file api.cc.
                                                       {
  v8::base::SetDcheckFunction(that);
}
References v8::base::SetDcheckFunction().
SetEntropySource()
void v8::V8::SetEntropySource (EntropySource source) [static]
Allows the host application to provide a callback which can be used as a source of entropy for random number generators.
Definition at line 6449 of file api.cc.
                                                        {
  base::RandomNumberGenerator::SetEntropySource(entropy_source);
}
References v8::base::entropy_source, and v8::base::RandomNumberGenerator::SetEntropySource().
SetFatalErrorHandler()
void v8::V8::SetFatalErrorHandler (V8FatalErrorCallback that) [static]
Set the callback to invoke in the case of CHECK failures or fatal errors.
This is distinct from Isolate::SetFatalErrorHandler, which is invoked in response to API usage failures.
Definition at line 432 of file api.cc.
                                                       {
  v8::base::SetFatalFunction(that);
}
References v8::base::SetFatalFunction().
SetFatalMemoryErrorCallback()
void v8::V8::SetFatalMemoryErrorCallback (v8::OOMErrorCallback oom_error_callback) [static]
Allows the host application to provide a callback that will be called when v8 has encountered a fatal failure to allocate memory and is about to terminate.
Definition at line 6444 of file api.cc.
                                           {
  g_oom_error_callback = oom_error_callback;
}
References v8::g_oom_error_callback.
SetFlagsFromCommandLine()
void v8::V8::SetFlagsFromCommandLine (int * argc, char ** argv, bool remove_flags) [static]
Sets V8 flags from the command line.
Definition at line 444 of file api.cc.
                                                                          {
  using HelpOptions = i::FlagList::HelpOptions;
  i::FlagList::SetFlagsFromCommandLine(argc, argv, remove_flags,
                                       HelpOptions(HelpOptions::kDontExit));
}
References v8::internal::FlagList::SetFlagsFromCommandLine().
SetFlagsFromString() [1/2]
void v8::V8::SetFlagsFromString (const char * str) [static]
Sets V8 flags from a string.
Definition at line 436 of file api.cc.
                                           {
  SetFlagsFromString(str, strlen(str));
}
Referenced by v8::Shell::Main(), and v8::Shell::SetOptions().
SetFlagsFromString() [2/2]
void v8::V8::SetFlagsFromString (const char * str, size_t length) [static]
Definition at line 440 of file api.cc.
                                                          {
  i::FlagList::SetFlagsFromString(str, length);
}
References v8::internal::length, and v8::internal::FlagList::SetFlagsFromString().
SetReturnAddressLocationResolver()
void v8::V8::SetReturnAddressLocationResolver (ReturnAddressLocationResolver return_address_resolver) [static]
Allows the host application to provide a callback that allows v8 to cooperate with a profiler that rewrites return addresses on stack.
Definition at line 6453 of file api.cc.
                                                           {
  i::StackFrame::SetReturnAddressLocationResolver(return_address_resolver);
}
References v8::internal::StackFrame::SetReturnAddressLocationResolver().
SetSnapshotDataBlob()
void v8::V8::SetSnapshotDataBlob (StartupData * startup_blob) [static]
Hand startup data to V8, in case the embedder has chosen to build V8 with external startup data.
Note:
By default the startup data is linked into the V8 library, in which case this function is not meaningful.
If this needs to be called, it needs to be called before V8 tries to make use of its built-ins.
To avoid unnecessary copies of data, V8 will point directly into the given data blob, so pretty please keep it around until V8 exit.
Compression of the startup blob might be useful, but needs to handled entirely on the embedders' side.
The call will abort if the data is invalid.
Definition at line 299 of file api.cc.
                                                       {
  i::V8::SetSnapshotBlob(snapshot_blob);
}
References v8::internal::V8::SetSnapshotBlob().
Friends And Related Function Documentation
Context
friend class Context [friend]
Definition at line 307 of file v8-initialization.h.
PersistentValueMapBase
template<class K , class V , class T >
friend class PersistentValueMapBase [friend]
Definition at line 309 of file v8-initialization.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-initialization.h
/mnt/V8SourceCode/src/api/api.cc