v8::internal::WasmValueObject Class Reference
#include <debug-wasm-objects.h>
Public Member Functions
OBJECT_CONSTRUCTORS (WasmValueObject, JSObject)
Static Public Member Functions
static DirectHandle< WasmValueObject > New (Isolate *isolate, DirectHandle< String > type, DirectHandle< Object > value)
static DirectHandle< WasmValueObject > New (Isolate *isolate, const wasm::WasmValue &value)
Static Public Attributes
static constexpr int kTypeIndex = 0
static constexpr int kValueIndex = 1
Additional Inherited Members
Detailed Description
Definition at line 40 of file debug-wasm-objects.h.
Member Function Documentation
New() [1/2]
DirectHandle< WasmValueObject > v8::internal::WasmValueObject::New (Isolate * isolate, const wasm::WasmValue & value) [static]
Definition at line 978 of file debug-wasm-objects.cc.
                                                  {
  DirectHandle<String> t;
  DirectHandle<Object> v;
  switch (value.type().kind()) {
    case wasm::kI8: {
      // This can't be reached for most "top-level" things, only via nested
      // calls for struct/array fields.
      t = isolate->factory()->InternalizeString(base::StaticCharVector("i8"));
      v = isolate->factory()->NewNumber(value.to_i8_unchecked());
      break;
    }
    case wasm::kI16: {
      // This can't be reached for most "top-level" things, only via nested
      // calls for struct/array fields.
      t = isolate->factory()->InternalizeString(base::StaticCharVector("i16"));
      v = isolate->factory()->NewNumber(value.to_i16_unchecked());
      break;
    }
    case wasm::kI32: {
      t = isolate->factory()->InternalizeString(base::StaticCharVector("i32"));
      v = isolate->factory()->NewNumberFromInt(value.to_i32_unchecked());
      break;
    }
    case wasm::kI64: {
      t = isolate->factory()->InternalizeString(base::StaticCharVector("i64"));
      v = BigInt::FromInt64(isolate, value.to_i64_unchecked());
      break;
    }
    case wasm::kF16: {
      // This can't be reached for most "top-level" things, only via nested
      // calls for struct/array fields.
      t = isolate->factory()->InternalizeString(base::StaticCharVector("f16"));
      v = isolate->factory()->NewNumber(value.to_f16_unchecked());
      break;
    }
    case wasm::kF32: {
      t = isolate->factory()->InternalizeString(base::StaticCharVector("f32"));
      v = isolate->factory()->NewNumber(value.to_f32_unchecked());
      break;
    }
    case wasm::kF64: {
      t = isolate->factory()->InternalizeString(base::StaticCharVector("f64"));
      v = isolate->factory()->NewNumber(value.to_f64_unchecked());
      break;
    }
    case wasm::kS128: {
      t = isolate->factory()->InternalizeString(base::StaticCharVector("v128"));
      v = WasmSimd128ToString(isolate, value.to_s128_unchecked());
      break;
    }
    case wasm::kRefNull:
    case wasm::kRef: {
      DirectHandle<Object> ref = value.to_ref();
      if (value.type().is_reference_to(wasm::HeapType::kExn)) {
        t = isolate->factory()->InternalizeString(
            base::StaticCharVector("exnref"));
        v = ref;
      } else if (IsWasmStruct(*ref)) {
        Tagged<WasmTypeInfo> type_info =
            Cast<HeapObject>(*ref)->map()->wasm_type_info();
        t = GetRefTypeName(isolate, type_info->type());
        v = StructProxy::Create(isolate, Cast<WasmStruct>(ref));
      } else if (IsWasmArray(*ref)) {
        Tagged<WasmTypeInfo> type_info =
            Cast<HeapObject>(*ref)->map()->wasm_type_info();
        t = GetRefTypeName(isolate, type_info->type());
        v = ArrayProxy::Create(isolate, Cast<WasmArray>(ref));
      } else if (IsWasmFuncRef(*ref)) {
        DirectHandle<WasmInternalFunction> internal_fct{
            Cast<WasmFuncRef>(*ref)->internal(isolate), isolate};
        v = WasmInternalFunction::GetOrCreateExternal(internal_fct);
        t = GetRefTypeName(isolate, value.type());
      } else if (IsWasmNull(*ref)) {
        v = isolate->factory()->null_value();
        t = GetRefTypeName(isolate, value.type());
      } else if (IsJSFunction(*ref) || IsSmi(*ref) || IsNull(*ref) ||
                 IsString(*ref) ||
                 value.type().is_reference_to(wasm::HeapType::kExtern) ||
                 value.type().is_reference_to(wasm::HeapType::kAny)) {
        t = GetRefTypeName(isolate, value.type());
        v = ref;
      } else {
        // Fail gracefully.
        base::EmbeddedVector<char, 64> error;
        int len = SNPrintF(error, "unimplemented object type: %d",
                           Cast<HeapObject>(*ref)->map()->instance_type());
        t = GetRefTypeName(isolate, value.type());
        v = isolate->factory()->InternalizeString(error.SubVector(0, len));
      }
      break;
    }
    case wasm::kVoid:
    case wasm::kTop:
    case wasm::kBottom:
      UNREACHABLE();
  }
  return New(isolate, t, v);
}
References v8::internal::ArrayProxy::Create(), v8::internal::StructProxy::Create(), v8::internal::Isolate::factory(), v8::internal::BigInt::FromInt64(), v8::internal::WasmInternalFunction::GetOrCreateExternal(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetRefTypeName(), v8::internal::Factory::InternalizeString(), v8::internal::IsNull(), v8::internal::IsSmi(), v8::internal::wasm::HeapType::kAny, v8::internal::wasm::HeapType::kExn, v8::internal::wasm::HeapType::kExtern, New(), v8::internal::FactoryBase< Impl >::NewNumber(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), v8::base::SNPrintF(), v8::base::StaticCharVector(), v8::base::Vector< T >::SubVector(), v8::internal::UNREACHABLE(), v8::internal::value, and v8::internal::anonymous_namespace{debug-wasm-objects.cc}::WasmSimd128ToString().
New() [2/2]
DirectHandle< WasmValueObject > v8::internal::WasmValueObject::New (Isolate * isolate, DirectHandle< String > type, DirectHandle< Object > value) [static]
Definition at line 867 of file debug-wasm-objects.cc.
                                                                               {
  auto maps = GetOrCreateDebugMaps(isolate);
  if (maps->is_the_hole(isolate, kWasmValueMapIndex)) {
    DirectHandle<Map> map =
        isolate->factory()->NewContextfulMapForCurrentContext(
            WASM_VALUE_OBJECT_TYPE, WasmValueObject::kSize,
            TERMINAL_FAST_ELEMENTS_KIND, 2);
    Map::EnsureDescriptorSlack(isolate, map, 2);
    map->SetConstructor(*isolate->object_function());
    { // type
      Descriptor d = Descriptor::DataField(
          isolate,
          isolate->factory()->InternalizeString(base::StaticCharVector("type")),
          WasmValueObject::kTypeIndex, FROZEN, Representation::Tagged());
      map->AppendDescriptor(isolate, &d);
    }
    { // value
      Descriptor d = Descriptor::DataField(
          isolate,
          isolate->factory()->InternalizeString(
              base::StaticCharVector("value")),
          WasmValueObject::kValueIndex, FROZEN, Representation::Tagged());
      map->AppendDescriptor(isolate, &d);
    }
    map->set_is_extensible(false);
    maps->set(kWasmValueMapIndex, *map);
  }
  DirectHandle<Map> value_map(Cast<Map>(maps->get(kWasmValueMapIndex)),
                              isolate);
  auto object =
      Cast<WasmValueObject>(isolate->factory()->NewJSObjectFromMap(value_map));
  object->set_type(*type);
  object->set_value(*value);
  return object;
}
References v8::internal::Descriptor::DataField(), v8::internal::Map::EnsureDescriptorSlack(), v8::internal::Isolate::factory(), v8::internal::FROZEN, v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateDebugMaps(), v8::internal::Factory::InternalizeString(), kTypeIndex, kValueIndex, v8::internal::anonymous_namespace{debug-wasm-objects.cc}::kWasmValueMapIndex, v8::internal::Factory::NewContextfulMapForCurrentContext(), v8::internal::Factory::NewJSObjectFromMap(), v8::base::StaticCharVector(), v8::internal::Representation::Tagged(), v8::internal::TERMINAL_FAST_ELEMENTS_KIND, v8::internal::tracing::type, and v8::internal::value.
Referenced by v8::internal::AddWasmTableObjectInternalProperties(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::LocalsProxy::Create(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::StackProxy::Create(), v8::internal::ArrayProxy::Get(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GlobalsProxy::Get(), v8::internal::StructProxy::Get(), and New().
OBJECT_CONSTRUCTORS()
v8::internal::WasmValueObject::OBJECT_CONSTRUCTORS (WasmValueObject , JSObject)
Member Data Documentation
kTypeIndex
constexpr int v8::internal::WasmValueObject::kTypeIndex = 0 [static], [constexpr]
Definition at line 58 of file debug-wasm-objects.h.
Referenced by New().
kValueIndex
constexpr int v8::internal::WasmValueObject::kValueIndex = 1 [static], [constexpr]
Definition at line 59 of file debug-wasm-objects.h.
Referenced by New().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-wasm-objects.h
/mnt/V8SourceCode/src/debug/debug-wasm-objects.cc