v8::internal::Serializer Class Reference
#include <serializer.h>
Classes
class HotObjectsList
class ObjectSerializer
class RecursionScope
Public Member Functions
Serializer (Isolate *isolate, Snapshot::SerializerFlags flags)
~Serializer () override
Serializer (const Serializer &)=delete
Serializer & operator= (const Serializer &)=delete
const std::vector< uint8_t > * Payload () const
bool ReferenceMapContains (DirectHandle< HeapObject > o)
Isolate * isolate () const
PtrComprCageBase cage_base () const
int TotalAllocationSize () const
Protected Types
using PendingObjectReferences = std::vector< int > *
Protected Member Functions
bool IsNotMappedSymbol (Tagged< HeapObject > obj) const
void SerializeDeferredObjects ()
void SerializeObject (Handle< HeapObject > o, SlotType slot_type)
virtual void SerializeObjectImpl (Handle< HeapObject > o, SlotType slot_type)=0
virtual bool MustBeDeferred (Tagged< HeapObject > object)
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) override
void SerializeRootObject (FullObjectSlot slot)
void PutRoot (RootIndex root_index)
void PutSmiRoot (FullObjectSlot slot)
void PutBackReference (Tagged< HeapObject > object, SerializerReference reference)
void PutAttachedReference (SerializerReference reference)
void PutNextChunk (SnapshotSpace space)
void PutRepeatRoot (int repeat_count, RootIndex root_index)
void PutPendingForwardReference (PendingObjectReferences &ref)
void ResolvePendingForwardReference (int obj)
bool SerializeRoot (Tagged< HeapObject > obj)
bool SerializeHotObject (Tagged< HeapObject > obj)
bool SerializeBackReference (Tagged< HeapObject > obj)
bool SerializePendingObject (Tagged< HeapObject > obj)
bool ObjectIsBytecodeHandler (Tagged< HeapObject > obj) const
ExternalReferenceEncoder::Value EncodeExternalReference (Address addr)
Maybe< ExternalReferenceEncoder::Value > TryEncodeExternalReference (Address addr)
bool SerializeReadOnlyObjectReference (Tagged< HeapObject > obj, SnapshotByteSink *sink)
void Pad (int padding_offset=0)
void InitializeCodeAddressMap ()
Tagged< InstructionStream > CopyCode (Tagged< InstructionStream > istream)
void QueueDeferredObject (Tagged< HeapObject > obj)
void RegisterObjectIsPending (Tagged< HeapObject > obj)
void ResolvePendingObject (Tagged< HeapObject > obj)
void OutputStatistics (const char *name)
void CountAllocation (Tagged< Map > map, int size, SnapshotSpace space)
SerializerReferenceMap * reference_map ()
const RootIndexMap * root_index_map () const
bool allow_unknown_external_references_for_testing () const
bool allow_active_isolate_for_testing () const
bool reconstruct_read_only_and_shared_object_caches_for_testing () const
bool deferred_objects_empty ()
bool serializer_tracks_serialization_statistics () const
void set_serializer_tracks_serialization_statistics (bool v)
Protected Attributes
SnapshotByteSink sink_
Private Attributes
Isolate * isolate_
HotObjectsList hot_objects_
SerializerReferenceMap reference_map_
ExternalReferenceEncoder external_reference_encoder_
RootIndexMap root_index_map_
std::unique_ptr< CodeAddressMap > code_address_map_
std::vector< uint8_t > code_buffer_
GlobalHandleVector< HeapObject > deferred_objects_
int num_back_refs_ = 0
std::unordered_map< JSDispatchHandle, uint32_t > dispatch_handle_map_
int next_forward_ref_id_ = 0
int unresolved_forward_refs_ = 0
IdentityMap< PendingObjectReferences, base::DefaultAllocationPolicy > forward_refs_per_pending_object_
uint32_t seen_backing_stores_index_ = 1
int recursion_depth_ = 0
const Snapshot::SerializerFlags flags_
bool serializer_tracks_serialization_statistics_ = true
size_t allocation_size_ [kNumberOfSnapshotSpaces] = {0}
Additional Inherited Members
Detailed Description
Definition at line 182 of file serializer.h.
Member Typedef Documentation
PendingObjectReferences
using v8::internal::Serializer::PendingObjectReferences = std::vector<int>* [protected]
Definition at line 210 of file serializer.h.
Constructor & Destructor Documentation
Serializer() [1/2]
v8::internal::Serializer::Serializer (Isolate * isolate, Snapshot::SerializerFlags flags)
Definition at line 34 of file serializer.cc.
    : isolate_(isolate),
#if V8_COMPRESS_POINTERS
      cage_base_(isolate),
#endif // V8_COMPRESS_POINTERS
      hot_objects_(isolate->heap()),
      reference_map_(isolate),
      external_reference_encoder_(isolate),
      root_index_map_(isolate),
      deferred_objects_(isolate->heap()),
      forward_refs_per_pending_object_(isolate->heap()),
      flags_(flags)
#ifdef DEBUG
      ,
      back_refs_(isolate->heap()),
      stack_(isolate->heap())
#endif
{
#ifdef VERBOSE_SERIALIZATION_STATISTICS
  if (v8_flags.serialization_statistics) {
    for (int space = 0; space < kNumberOfSnapshotSpaces; ++space) {
      // Value-initialized to 0.
      instance_type_count_[space] = std::make_unique<int[]>(kInstanceTypes);
      instance_type_size_[space] = std::make_unique<size_t[]>(kInstanceTypes);
    }
  }
#endif // VERBOSE_SERIALIZATION_STATISTICS
}
References v8::internal::kNumberOfSnapshotSpaces, space, and v8::internal::v8_flags.
 Serializer()
v8::internal::Serializer::~Serializer () [inline], [override]
Definition at line 185 of file serializer.h.
{ DCHECK_EQ(unresolved_forward_refs_, 0); }
References DCHECK_EQ, and unresolved_forward_refs_.
Serializer() [2/2]
v8::internal::Serializer::Serializer (const Serializer &) [delete]
Member Function Documentation
allow_active_isolate_for_testing()
bool v8::internal::Serializer::allow_active_isolate_for_testing () const [inline], [protected]
Definition at line 328 of file serializer.h.
                                                {
    return (flags_ & Snapshot::kAllowActiveIsolateForTesting) != 0;
  }
References flags_, and v8::internal::Snapshot::kAllowActiveIsolateForTesting.
Referenced by v8::internal::ContextSerializer::Serialize(), v8::internal::ContextSerializer::SerializeObjectImpl(), and v8::internal::StartupSerializer::SerializeStrongReferences().
allow_unknown_external_references_for_testing()
bool v8::internal::Serializer::allow_unknown_external_references_for_testing () const [inline], [protected]
Definition at line 325 of file serializer.h.
                                                             {
    return (flags_ & Snapshot::kAllowUnknownExternalReferencesForTesting) != 0;
  }
References flags_, and v8::internal::Snapshot::kAllowUnknownExternalReferencesForTesting.
cage_base()
PtrComprCageBase v8::internal::Serializer::cage_base () const [inline]
Definition at line 199 of file serializer.h.
                                     {
#if V8_COMPRESS_POINTERS
    return cage_base_;
#else
    return PtrComprCageBase{};
#endif // V8_COMPRESS_POINTERS
  }
Referenced by v8::internal::ContextSerializer::CheckRehashability(), v8::internal::RootsSerializer::CheckRehashability(), v8::internal::Serializer::ObjectSerializer::OutputRawData(), v8::internal::Serializer::ObjectSerializer::Serialize(), v8::internal::Serializer::ObjectSerializer::SerializeExternalStringAsSequentialString(), v8::internal::CodeSerializer::SerializeObjectImpl(), v8::internal::ContextSerializer::SerializeObjectImpl(), v8::internal::StartupSerializer::SerializeObjectImpl(), v8::internal::Serializer::ObjectSerializer::VisitCppHeapPointer(), v8::internal::Serializer::ObjectSerializer::VisitExternalPointer(), and v8::internal::Serializer::ObjectSerializer::VisitPointers().
CopyCode()
Tagged< InstructionStream > v8::internal::Serializer::CopyCode (Tagged< InstructionStream > istream) [protected]
Definition at line 441 of file serializer.cc.
                                       {
  code_buffer_.clear(); // Clear buffer without deleting backing store.
  // Add InstructionStream padding which is usually added by the allocator.
  // While this doesn't guarantee the exact same alignment, it's enough to
  // fulfill the alignment requirements of writes during relocation.
  code_buffer_.resize(InstructionStream::kCodeAlignmentMinusCodeHeader);
  int size = istream->Size();
  code_buffer_.insert(code_buffer_.end(),
                      reinterpret_cast<uint8_t*>(istream.address()),
                      reinterpret_cast<uint8_t*>(istream.address() + size));
  // When pointer compression is enabled the checked cast will try to
  // decompress map field of off-heap InstructionStream object.
  return UncheckedCast<InstructionStream>(
      HeapObject::FromAddress(reinterpret_cast<Address>(
          &code_buffer_[InstructionStream::kCodeAlignmentMinusCodeHeader])));
}
References v8::internal::Tagged< HeapObject >::address(), code_buffer_, v8::internal::HeapObject::FromAddress(), v8::internal::InstructionStream::kCodeAlignmentMinusCodeHeader, and size().
CountAllocation()
void v8::internal::Serializer::CountAllocation (Tagged< Map > map, int size, SnapshotSpace space) [protected]
Definition at line 67 of file serializer.cc.
                                                      {
  DCHECK(v8_flags.serialization_statistics);
  const int space_number = static_cast<int>(space);
  allocation_size_[space_number] += size;
#ifdef VERBOSE_SERIALIZATION_STATISTICS
  int instance_type = map->instance_type();
  instance_type_count_[space_number][instance_type]++;
  instance_type_size_[space_number][instance_type] += size;
#endif // VERBOSE_SERIALIZATION_STATISTICS
}
References allocation_size_, v8::internal::DCHECK(), size(), space, and v8::internal::v8_flags.
Referenced by v8::internal::ReadOnlySerializer::Serialize(), and v8::internal::Serializer::ObjectSerializer::SerializePrologue().
deferred_objects_empty()
bool v8::internal::Serializer::deferred_objects_empty () [inline], [protected]
Definition at line 337 of file serializer.h.
{ return deferred_objects_.size() == 0; }
References deferred_objects_.
EncodeExternalReference()
ExternalReferenceEncoder::Value v8::internal::Serializer::EncodeExternalReference (Address addr) [protected]
Definition at line 374 of file serializer.cc.
                  {
  Maybe<ExternalReferenceEncoder::Value> result =
      external_reference_encoder_.TryEncode(addr);
  if (result.IsNothing()) {
#ifdef DEBUG
    PrintStack(std::cerr);
#endif
    void* addr_ptr = reinterpret_cast<void*>(addr);
    v8::base::OS::PrintError("Unknown external reference %p.\n", addr_ptr);
    v8::base::OS::PrintError("%s\n",
                             ExternalReferenceTable::ResolveSymbol(addr_ptr));
    v8::base::OS::Abort();
  }
  return result.FromJust();
}
References v8::base::OS::Abort(), external_reference_encoder_, v8::internal::ExternalReferenceTable::ResolveSymbol(), v8::base::internal::result, and v8::internal::ExternalReferenceEncoder::TryEncode().
Referenced by v8::internal::StartupSerializer::StartupSerializer().
InitializeCodeAddressMap()
void v8::internal::Serializer::InitializeCodeAddressMap () [protected]
Definition at line 436 of file serializer.cc.
                                          {
  isolate_->InitializeLoggingAndCounters();
  code_address_map_ = std::make_unique<CodeAddressMap>(isolate_);
}
References code_address_map_, v8::internal::Isolate::InitializeLoggingAndCounters(), and isolate_.
Referenced by v8::internal::ContextSerializer::ContextSerializer(), and v8::internal::StartupSerializer::StartupSerializer().
IsNotMappedSymbol()
bool v8::internal::Serializer::IsNotMappedSymbol (Tagged< HeapObject > obj) const [inline], [protected]
Definition at line 16 of file serializer-inl.h.
                                                               {
  Tagged<Object> not_mapped_symbol =
      ReadOnlyRoots(isolate()).not_mapped_symbol();
  if (V8_EXTERNAL_CODE_SPACE_BOOL) {
    // It's possible that an InstructionStream object might have the same
    // compressed value as the not_mapped_symbol, so we must compare full
    // pointers.
    // TODO(v8:11880): Avoid the need for this special case by never putting
    // InstructionStream references anywhere except the CodeDadaContainer
    // objects. In particular, the InstructionStream objects should not appear
    // in serializer's identity map. This should be possible once the
    // IsolateData::builtins table is migrated to contain Code
    // references.
    return obj.ptr() == not_mapped_symbol.ptr();
  }
  return obj == not_mapped_symbol;
}
References isolate(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and V8_EXTERNAL_CODE_SPACE_BOOL.
Referenced by RegisterObjectIsPending(), ResolvePendingObject(), and v8::internal::Serializer::ObjectSerializer::SerializePrologue().
isolate()
Isolate* v8::internal::Serializer::isolate () const [inline]
Definition at line 195 of file serializer.h.
{ return isolate_; }
References isolate_.
Referenced by v8::internal::StartupSerializer::CheckNoDirtyFinalizationRegistries(), v8::internal::CodeSerializer::Deserialize(), v8::internal::SharedHeapSerializer::FinalizeSerialization(), v8::internal::CodeSerializer::FinishOffThreadDeserialize(), IsNotMappedSymbol(), PutRoot(), v8::internal::SharedHeapSerializer::ReconstructSharedHeapObjectCacheForTesting(), v8::internal::ReadOnlySerializer::Serialize(), v8::internal::CodeSerializer::Serialize(), v8::internal::Serializer::ObjectSerializer::Serialize(), v8::internal::ContextSerializer::Serialize(), v8::internal::ContextSerializer::SerializeApiWrapperFields(), v8::internal::Serializer::ObjectSerializer::SerializeContent(), SerializeDeferredObjects(), v8::internal::Serializer::ObjectSerializer::SerializeExternalString(), v8::internal::Serializer::ObjectSerializer::SerializeExternalStringAsSequentialString(), v8::internal::Serializer::ObjectSerializer::SerializeJSArrayBuffer(), v8::internal::Serializer::ObjectSerializer::SerializeJSTypedArray(), v8::internal::Serializer::ObjectSerializer::SerializeObject(), SerializeObject(), v8::internal::CodeSerializer::SerializeObjectImpl(), v8::internal::ContextSerializer::SerializeObjectImpl(), v8::internal::StartupSerializer::SerializeObjectImpl(), v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields(), SerializeReadOnlyObjectReference(), v8::internal::SharedHeapSerializer::SerializeStringTable(), v8::internal::StartupSerializer::SerializeStrongReferences(), v8::internal::SharedHeapSerializer::SerializeUsingSharedHeapObjectCache(), v8::internal::StartupSerializer::SerializeWeakReferencesAndDeferred(), v8::internal::ContextSerializer::ShouldBeInTheStartupObjectCache(), v8::internal::SharedHeapSerializer::ShouldReconstructSharedHeapObjectCacheForTesting(), v8::internal::StartupSerializer::StartupSerializer(), v8::internal::UnlinkWeakNextScope::UnlinkWeakNextScope(), v8::internal::ObjectCacheIndexMap::Values(), v8::internal::Serializer::ObjectSerializer::VisitCppHeapPointer(), v8::internal::Serializer::ObjectSerializer::VisitExternalPointer(), v8::internal::Serializer::ObjectSerializer::VisitIndirectPointer(), v8::internal::Serializer::ObjectSerializer::VisitJSDispatchTableEntry(), v8::internal::Serializer::ObjectSerializer::VisitPointers(), v8::internal::Serializer::ObjectSerializer::VisitProtectedPointer(), v8::internal::RootsSerializer::VisitRootPointers(), and v8::internal::StartupSerializer::~StartupSerializer().
MustBeDeferred()
bool v8::internal::Serializer::MustBeDeferred (Tagged< HeapObject > object) [protected], [virtual]
Definition at line 181 of file serializer.cc.
{ return false; }
ObjectIsBytecodeHandler()
bool v8::internal::Serializer::ObjectIsBytecodeHandler (Tagged< HeapObject > obj) const [protected]
Definition at line 274 of file serializer.cc.
                                                                     {
  if (!IsCode(obj)) return false;
  return (Cast<Code>(obj)->kind() == CodeKind::BYTECODE_HANDLER);
}
Referenced by v8::internal::ContextSerializer::SerializeObjectImpl().
operator=()
Serializer& v8::internal::Serializer::operator= (const Serializer &) [delete]
OutputStatistics()
void v8::internal::Serializer::OutputStatistics (const char * name) [protected]
Definition at line 105 of file serializer.cc.
                                                  {
  if (!v8_flags.serialization_statistics) return;
  PrintF("%s:\n", name);
  if (!serializer_tracks_serialization_statistics()) {
    PrintF(" <serialization statistics are not tracked>\n");
    return;
  }
  PrintF(" Spaces (bytes):\n");
  static constexpr SnapshotSpace kAllSnapshotSpaces[] = {
      SnapshotSpace::kReadOnlyHeap,
      SnapshotSpace::kOld,
      SnapshotSpace::kCode,
  };
  for (SnapshotSpace space : kAllSnapshotSpaces) {
    PrintF("%16s", ToString(space));
  }
  PrintF("\n");
  for (SnapshotSpace space : kAllSnapshotSpaces) {
    PrintF("%16zu", allocation_size_[static_cast<int>(space)]);
  }
  PrintF("\n");
#ifdef VERBOSE_SERIALIZATION_STATISTICS
  PrintF(" Instance types (count and bytes):\n");
#define PRINT_INSTANCE_TYPE(Name) \
  for (SnapshotSpace space : kAllSnapshotSpaces) { \
    const int space_i = static_cast<int>(space); \
    if (instance_type_count_[space_i][Name]) { \
      PrintF("%10d %10zu %-10s %s\n", instance_type_count_[space_i][Name], \
             instance_type_size_[space_i][Name], ToString(space), #Name); \
    } \
  }
  INSTANCE_TYPE_LIST(PRINT_INSTANCE_TYPE)
#undef PRINT_INSTANCE_TYPE
  PrintF("\n");
#endif // VERBOSE_SERIALIZATION_STATISTICS
}
References allocation_size_, INSTANCE_TYPE_LIST, v8::internal::kCode, v8::internal::kOld, v8::internal::kReadOnlyHeap, v8::internal::name, v8::internal::PrintF(), serializer_tracks_serialization_statistics(), space, v8::internal::ToString(), and v8::internal::v8_flags.
Referenced by v8::internal::CodeSerializer::~CodeSerializer(), v8::internal::ContextSerializer::~ContextSerializer(), v8::internal::ReadOnlySerializer::~ReadOnlySerializer(), v8::internal::SharedHeapSerializer::~SharedHeapSerializer(), and v8::internal::StartupSerializer::~StartupSerializer().
Pad()
void v8::internal::Serializer::Pad (int padding_offset = 0) [protected]
Definition at line 424 of file serializer.cc.
                                       {
  // The non-branching GetInt will read up to 3 bytes too far, so we need
  // to pad the snapshot to make sure we don't read over the end.
  for (unsigned i = 0; i < sizeof(int32_t) - 1; i++) {
    sink_.Put(kNop, "Padding");
  }
  // Pad up to pointer size for checksum.
  while (!IsAligned(sink_.Position() + padding_offset, kPointerAlignment)) {
    sink_.Put(kNop, "Padding");
  }
}
References IsAligned(), v8::internal::SerializerDeserializer::kNop, v8::internal::kPointerAlignment, v8::internal::SnapshotByteSink::Position(), v8::internal::SnapshotByteSink::Put(), and sink_.
Referenced by v8::internal::SharedHeapSerializer::FinalizeSerialization(), v8::internal::ContextSerializer::Serialize(), v8::internal::CodeSerializer::SerializeSharedFunctionInfo(), and v8::internal::StartupSerializer::SerializeWeakReferencesAndDeferred().
Payload()
const std::vector<uint8_t>* v8::internal::Serializer::Payload () const [inline]
Definition at line 189 of file serializer.h.
{ return sink_.data(); }
References v8::internal::SnapshotByteSink::data(), and sink_.
Referenced by v8::internal::SnapshotData::SnapshotData().
PutAttachedReference()
void v8::internal::Serializer::PutAttachedReference (SerializerReference reference) [protected]
Definition at line 328 of file serializer.cc.
                                                                   {
  DCHECK(reference.is_attached_reference());
  sink_.Put(kAttachedReference, "AttachedRef");
  sink_.PutUint30(reference.attached_reference_index(), "AttachedRefIndex");
}
References v8::internal::SerializerReference::attached_reference_index(), v8::internal::DCHECK(), v8::internal::SerializerReference::is_attached_reference(), v8::internal::SerializerDeserializer::kAttachedReference, v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutUint30(), and sink_.
Referenced by SerializeBackReference().
PutBackReference()
void v8::internal::Serializer::PutBackReference (Tagged< HeapObject > object, SerializerReference reference) [protected]
Definition at line 321 of file serializer.cc.
                                                                 {
  DCHECK_EQ(object, *back_refs_[reference.back_ref_index()]);
  sink_.PutUint30(reference.back_ref_index(), "BackRefIndex");
  hot_objects_.Add(object);
}
References v8::internal::Serializer::HotObjectsList::Add(), v8::internal::SerializerReference::back_ref_index(), DCHECK_EQ, hot_objects_, v8::internal::SnapshotByteSink::PutUint30(), and sink_.
Referenced by SerializeBackReference().
PutNextChunk()
void v8::internal::Serializer::PutNextChunk (SnapshotSpace space) [protected]
PutPendingForwardReference()
void v8::internal::Serializer::PutPendingForwardReference (PendingObjectReferences & ref) [protected]
Definition at line 347 of file serializer.cc.
                                                                         {
  sink_.Put(kRegisterPendingForwardRef, "RegisterPendingForwardRef");
  unresolved_forward_refs_++;
  // Register the current slot with the pending object.
  int forward_ref_id = next_forward_ref_id_++;
  if (refs == nullptr) {
    // The IdentityMap holding the pending object reference vectors does not
    // support non-trivial types; in particular it doesn't support destructors
    // on values. So, we manually allocate a vector with new, and delete it when
    // resolving the pending object.
    refs = new std::vector<int>();
  }
  refs->push_back(forward_ref_id);
}
References v8::internal::SerializerDeserializer::kRegisterPendingForwardRef, next_forward_ref_id_, v8::internal::SnapshotByteSink::Put(), sink_, and unresolved_forward_refs_.
Referenced by SerializePendingObject().
PutRepeatRoot()
void v8::internal::Serializer::PutRepeatRoot (int repeat_count, RootIndex root_index) [protected]
Definition at line 334 of file serializer.cc.
                                                                     {
  if (repeat_count <= kLastEncodableFixedRepeatRootCount) {
    sink_.Put(FixedRepeatRootWithCount::Encode(repeat_count),
              "FixedRepeatRoot");
  } else {
    sink_.Put(kVariableRepeatRoot, "VariableRepeatRoot");
    sink_.PutUint30(VariableRepeatRootCount::Encode(repeat_count),
                    "repeat count");
  }
  DCHECK_LE(static_cast<uint32_t>(root_index), UINT8_MAX);
  sink_.Put(static_cast<uint8_t>(root_index), "root index");
}
References DCHECK_LE, v8::internal::SerializerDeserializer::VariableRepeatRootCount::Encode(), v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >::Encode(), v8::internal::SerializerDeserializer::kLastEncodableFixedRepeatRootCount, v8::internal::SerializerDeserializer::kVariableRepeatRoot, v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutUint30(), and sink_.
PutRoot()
void v8::internal::Serializer::PutRoot (RootIndex root_index) [protected]
Definition at line 279 of file serializer.cc.
                                       {
  DisallowGarbageCollection no_gc;
  int root_index = static_cast<int>(root);
  Tagged<HeapObject> object = Cast<HeapObject>(isolate()->root(root));
  if (v8_flags.trace_serializer) {
    PrintF(" Encoding root %d:", root_index);
    ShortPrint(object);
    PrintF("\n");
  }
  // Assert that the first 32 root array items are a conscious choice. They are
  // chosen so that the most common ones can be encoded more efficiently.
  static_assert(static_cast<int>(RootIndex::kArgumentsMarker) ==
                kRootArrayConstantsCount);
  // TODO(ulan): Check that it works with young large objects.
  if (root_index < kRootArrayConstantsCount &&
      !HeapLayout::InYoungGeneration(object)) {
    sink_.Put(RootArrayConstant::Encode(root), "RootConstant");
  } else {
    sink_.Put(kRootArray, "RootSerialization");
    sink_.PutUint30(root_index, "root_index");
    hot_objects_.Add(object);
  }
}
References v8::internal::Serializer::HotObjectsList::Add(), v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >::Encode(), hot_objects_, v8::internal::HeapLayout::InYoungGeneration(), isolate(), v8::internal::SerializerDeserializer::kRootArray, v8::internal::SerializerDeserializer::kRootArrayConstantsCount, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PrintF(), v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutUint30(), v8::internal::ShortPrint(), sink_, and v8::internal::v8_flags.
Referenced by SerializeRoot().
PutSmiRoot()
void v8::internal::Serializer::PutSmiRoot (FullObjectSlot slot) [protected]
Definition at line 305 of file serializer.cc.
                                               {
  // Serializing a smi root in compressed pointer builds will serialize the
  // full object slot (of kSystemPointerSize) to avoid complications during
  // deserialization (endianness or smi sequences).
  static_assert(decltype(slot)::kSlotDataSize == sizeof(Address));
  static_assert(decltype(slot)::kSlotDataSize == kSystemPointerSize);
  static constexpr int bytes_to_output = decltype(slot)::kSlotDataSize;
  static constexpr int size_in_tagged = bytes_to_output >> kTaggedSizeLog2;
  sink_.Put(FixedRawDataWithSize::Encode(size_in_tagged), "Smi");
  Address raw_value = Cast<Smi>(*slot).ptr();
  const uint8_t* raw_value_as_bytes =
      reinterpret_cast<const uint8_t*>(&raw_value);
  sink_.PutRaw(raw_value_as_bytes, bytes_to_output, "Bytes");
}
References v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >::Encode(), v8::internal::kSystemPointerSize, v8::internal::kTaggedSizeLog2, v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutRaw(), and sink_.
Referenced by SerializeRootObject().
QueueDeferredObject()
void v8::internal::Serializer::QueueDeferredObject (Tagged< HeapObject > obj) [inline], [protected]
Definition at line 296 of file serializer.h.
                                                   {
    DCHECK_NULL(reference_map_.LookupReference(obj));
    deferred_objects_.Push(obj);
  }
References DCHECK_NULL, deferred_objects_, v8::internal::SerializerReferenceMap::LookupReference(), and reference_map_.
Referenced by v8::internal::Serializer::ObjectSerializer::SerializePrologue().
reconstruct_read_only_and_shared_object_caches_for_testing()
bool v8::internal::Serializer::reconstruct_read_only_and_shared_object_caches_for_testing () const [inline], [protected]
Definition at line 332 of file serializer.h.
                                                                          {
    return (flags_ &
            Snapshot::kReconstructReadOnlyAndSharedObjectCachesForTesting) != 0;
  }
References flags_, and v8::internal::Snapshot::kReconstructReadOnlyAndSharedObjectCachesForTesting.
Referenced by v8::internal::SharedHeapSerializer::ShouldReconstructSharedHeapObjectCacheForTesting().
reference_map()
SerializerReferenceMap* v8::internal::Serializer::reference_map () [inline], [protected]
Definition at line 320 of file serializer.h.
{ return &reference_map_; }
References reference_map_.
Referenced by ReferenceMapContains(), v8::internal::ContextSerializer::Serialize(), v8::internal::ContextSerializer::SerializeApiWrapperFields(), v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields(), and v8::internal::Serializer::ObjectSerializer::SerializePrologue().
ReferenceMapContains()
bool v8::internal::Serializer::ReferenceMapContains (DirectHandle< HeapObject > o) [inline]
Definition at line 191 of file serializer.h.
                                                        {
    return reference_map()->LookupReference(o) != nullptr;
  }
References v8::internal::SerializerReferenceMap::LookupReference(), and reference_map().
Referenced by v8::internal::ContextSerializer::SerializeObjectImpl().
RegisterObjectIsPending()
void v8::internal::Serializer::RegisterObjectIsPending (Tagged< HeapObject > obj) [protected]
Definition at line 391 of file serializer.cc.
                                                               {
  DisallowGarbageCollection no_gc;
  if (IsNotMappedSymbol(obj)) return;
  // Add the given object to the pending objects -> forward refs map.
  auto find_result = forward_refs_per_pending_object_.FindOrInsert(obj);
  USE(find_result);
  // If the above emplace didn't actually add the object, then the object must
  // already have been registered pending by deferring. It might not be in the
  // deferred objects queue though, since it may be the very object we just
  // popped off that queue, so just check that it can be deferred.
  DCHECK_IMPLIES(find_result.already_exists, *find_result.entry != nullptr);
  DCHECK_IMPLIES(find_result.already_exists,
                 CanBeDeferred(obj, SlotType::kAnySlot));
}
References v8::internal::SerializerDeserializer::CanBeDeferred(), DCHECK_IMPLIES, forward_refs_per_pending_object_, IsNotMappedSymbol(), v8::internal::SerializerDeserializer::kAnySlot, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and USE.
Referenced by v8::internal::Serializer::ObjectSerializer::SerializePrologue().
ResolvePendingForwardReference()
void v8::internal::Serializer::ResolvePendingForwardReference (int obj) [protected]
Definition at line 362 of file serializer.cc.
                                                                        {
  sink_.Put(kResolvePendingForwardRef, "ResolvePendingForwardRef");
  sink_.PutUint30(forward_reference_id, "with this index");
  unresolved_forward_refs_--;
  // If there are no more unresolved forward refs, reset the forward ref id to
  // zero so that future forward refs compress better.
  if (unresolved_forward_refs_ == 0) {
    next_forward_ref_id_ = 0;
  }
}
References v8::internal::SerializerDeserializer::kResolvePendingForwardRef, next_forward_ref_id_, v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutUint30(), sink_, and unresolved_forward_refs_.
Referenced by ResolvePendingObject().
ResolvePendingObject()
void v8::internal::Serializer::ResolvePendingObject (Tagged< HeapObject > obj) [protected]
Definition at line 408 of file serializer.cc.
                                                            {
  DisallowGarbageCollection no_gc;
  if (IsNotMappedSymbol(obj)) return;
  std::vector<int>* refs;
  CHECK(forward_refs_per_pending_object_.Delete(obj, &refs));
  if (refs) {
    for (int index : *refs) {
      ResolvePendingForwardReference(index);
    }
    // See PutPendingForwardReference -- we have to manually manage the memory
    // of non-trivial IdentityMap values.
    delete refs;
  }
}
References CHECK, forward_refs_per_pending_object_, v8::internal::index, IsNotMappedSymbol(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and ResolvePendingForwardReference().
Referenced by v8::internal::Serializer::ObjectSerializer::SerializePrologue().
root_index_map()
const RootIndexMap* v8::internal::Serializer::root_index_map () const [inline], [protected]
Definition at line 321 of file serializer.h.
{ return &root_index_map_; }
References root_index_map_.
Referenced by SerializeRoot().
SerializeBackReference()
bool v8::internal::Serializer::SerializeBackReference (Tagged< HeapObject > obj) [protected]
Definition at line 236 of file serializer.cc.
                                                              {
  DisallowGarbageCollection no_gc;
  const SerializerReference* reference = reference_map_.LookupReference(obj);
  if (reference == nullptr) return false;
  // Encode the location of an already deserialized object in order to write
  // its location into a later object. We can encode the location as an
  // offset from the start of the deserialized objects or as an offset
  // backwards from the current allocation pointer.
  if (reference->is_attached_reference()) {
    if (v8_flags.trace_serializer) {
      PrintF(" Encoding attached reference %d\n",
             reference->attached_reference_index());
    }
    PutAttachedReference(*reference);
  } else {
    DCHECK(reference->is_back_reference());
    if (v8_flags.trace_serializer) {
      PrintF(" Encoding back reference to: ");
      ShortPrint(obj);
      PrintF("\n");
    }
    sink_.Put(kBackref, "Backref");
    PutBackReference(obj, *reference);
  }
  return true;
}
References v8::internal::SerializerReference::attached_reference_index(), v8::internal::DCHECK(), v8::internal::SerializerReference::is_attached_reference(), v8::internal::SerializerReference::is_back_reference(), v8::internal::SerializerDeserializer::kBackref, v8::internal::SerializerReferenceMap::LookupReference(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PrintF(), v8::internal::SnapshotByteSink::Put(), PutAttachedReference(), PutBackReference(), reference_map_, v8::internal::ShortPrint(), sink_, and v8::internal::v8_flags.
Referenced by v8::internal::CodeSerializer::SerializeObjectImpl(), v8::internal::ContextSerializer::SerializeObjectImpl(), v8::internal::StartupSerializer::SerializeObjectImpl(), and v8::internal::SharedHeapSerializer::SerializeObjectImpl().
SerializeDeferredObjects()
void v8::internal::Serializer::SerializeDeferredObjects () [protected]
Definition at line 148 of file serializer.cc.
                                          {
  if (v8_flags.trace_serializer) {
    PrintF("Serializing deferred objects\n");
  }
  WHILE_WITH_HANDLE_SCOPE(isolate(), !deferred_objects_.empty(), {
    Handle<HeapObject> obj = handle(deferred_objects_.Pop(), isolate());
    ObjectSerializer obj_serializer(this, obj, &sink_);
    obj_serializer.SerializeDeferred();
  });
  sink_.Put(kSynchronize, "Finished with deferred objects");
}
References deferred_objects_, isolate(), v8::internal::SerializerDeserializer::kSynchronize, v8::internal::PrintF(), v8::internal::SnapshotByteSink::Put(), sink_, v8::internal::v8_flags, and WHILE_WITH_HANDLE_SCOPE.
Referenced by v8::internal::SharedHeapSerializer::FinalizeSerialization(), v8::internal::ContextSerializer::Serialize(), v8::internal::CodeSerializer::SerializeSharedFunctionInfo(), and v8::internal::StartupSerializer::SerializeWeakReferencesAndDeferred().
SerializeHotObject()
bool v8::internal::Serializer::SerializeHotObject (Tagged< HeapObject > obj) [protected]
Definition at line 221 of file serializer.cc.
                                                          {
  DisallowGarbageCollection no_gc;
  // Encode a reference to a hot object by its index in the working set.
  int index = hot_objects_.Find(obj);
  if (index == HotObjectsList::kNotFound) return false;
  DCHECK(index >= 0 && index < kHotObjectCount);
  if (v8_flags.trace_serializer) {
    PrintF(" Encoding hot object %d:", index);
    ShortPrint(obj);
    PrintF("\n");
  }
  sink_.Put(HotObject::Encode(index), "HotObject");
  return true;
}
References v8::internal::DCHECK(), v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >::Encode(), v8::internal::Serializer::HotObjectsList::Find(), hot_objects_, v8::internal::index, v8::internal::SerializerDeserializer::kHotObjectCount, v8::internal::Serializer::HotObjectsList::kNotFound, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PrintF(), v8::internal::SnapshotByteSink::Put(), v8::internal::ShortPrint(), sink_, and v8::internal::v8_flags.
Referenced by v8::internal::CodeSerializer::SerializeObjectImpl(), v8::internal::ContextSerializer::SerializeObjectImpl(), v8::internal::StartupSerializer::SerializeObjectImpl(), and v8::internal::SharedHeapSerializer::SerializeObjectImpl().
SerializeObject()
void v8::internal::Serializer::SerializeObject (Handle< HeapObject > o, SlotType slot_type) [protected]
Definition at line 161 of file serializer.cc.
                                                                           {
  // ThinStrings are just an indirection to an internalized string, so elide the
  // indirection and serialize the actual string directly.
  if (IsThinString(*obj, isolate())) {
    obj = handle(Cast<ThinString>(*obj)->actual(), isolate());
  } else if (IsCode(*obj, isolate())) {
    Tagged<Code> code = Cast<Code>(*obj);
    // The only expected Code objects here are baseline code and builtins.
    if (code->kind() == CodeKind::BASELINE) {
      // For now just serialize the BytecodeArray instead of baseline code.
      // TODO(v8:11429,pthier): Handle Baseline code in cases we want to
      // serialize it.
      obj = handle(code->bytecode_or_interpreter_data(), isolate());
    } else {
      CHECK(code->is_builtin());
    }
  }
  SerializeObjectImpl(obj, slot_type);
}
References CHECK, code, v8::internal::handle(), isolate(), v8::internal::InstanceTypeChecker::IsThinString(), and SerializeObjectImpl().
Referenced by v8::internal::Serializer::ObjectSerializer::Serialize(), v8::internal::Serializer::ObjectSerializer::SerializeExternalString(), v8::internal::RootsSerializer::SerializeInObjectCache(), v8::internal::Serializer::ObjectSerializer::SerializeJSArrayBuffer(), v8::internal::Serializer::ObjectSerializer::SerializeJSTypedArray(), v8::internal::Serializer::ObjectSerializer::SerializePrologue(), and SerializeRootObject().
SerializeObjectImpl()
virtual void v8::internal::Serializer::SerializeObjectImpl (Handle< HeapObject > o, SlotType slot_type) [protected], [pure virtual]
Implemented in v8::internal::SharedHeapSerializer, v8::internal::StartupSerializer, v8::internal::ReadOnlySerializer, v8::internal::ContextSerializer, and v8::internal::CodeSerializer.
Referenced by SerializeObject().
SerializePendingObject()
bool v8::internal::Serializer::SerializePendingObject (Tagged< HeapObject > obj) [protected]
Definition at line 264 of file serializer.cc.
                                                              {
  PendingObjectReferences* refs_to_object =
      forward_refs_per_pending_object_.Find(obj);
  if (refs_to_object == nullptr) {
    return false;
  }
  PutPendingForwardReference(*refs_to_object);
  return true;
}
References forward_refs_per_pending_object_, and PutPendingForwardReference().
serializer_tracks_serialization_statistics()
bool v8::internal::Serializer::serializer_tracks_serialization_statistics () const [inline], [protected]
Definition at line 340 of file serializer.h.
                                                          {
    return serializer_tracks_serialization_statistics_;
  }
References serializer_tracks_serialization_statistics_.
Referenced by OutputStatistics().
SerializeReadOnlyObjectReference()
bool v8::internal::Serializer::SerializeReadOnlyObjectReference (Tagged< HeapObject > obj, SnapshotByteSink * sink) [protected]
Definition at line 1464 of file serializer.cc.
                                                                          {
  if (!ReadOnlyHeap::Contains(obj)) return false;
  // For objects on the read-only heap, never serialize the object, but instead
  // create a back reference that encodes the page number as the chunk_index and
  // the offset within the page as the chunk_offset.
  Address address = obj.address();
  MemoryChunkMetadata* chunk = MemoryChunkMetadata::FromAddress(address);
  uint32_t chunk_index = 0;
  ReadOnlySpace* const read_only_space = isolate()->heap()->read_only_space();
  DCHECK(!read_only_space->writable());
  for (ReadOnlyPageMetadata* page : read_only_space->pages()) {
    if (chunk == page) break;
    ++chunk_index;
  }
  uint32_t chunk_offset = static_cast<uint32_t>(chunk->Offset(address));
  sink->Put(kReadOnlyHeapRef, "ReadOnlyHeapRef");
  sink->PutUint30(chunk_index, "ReadOnlyHeapRefChunkIndex");
  sink->PutUint30(chunk_offset, "ReadOnlyHeapRefChunkOffset");
  return true;
}
References v8::internal::Tagged< HeapObject >::address(), v8::internal::ReadOnlyHeap::Contains(), v8::internal::DCHECK(), v8::internal::MemoryChunkMetadata::FromAddress(), v8::internal::Isolate::heap(), isolate(), v8::internal::SerializerDeserializer::kReadOnlyHeapRef, v8::internal::MemoryChunkMetadata::Offset(), v8::internal::ReadOnlySpace::pages(), v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutUint30(), v8::internal::Heap::read_only_space(), and v8::internal::ReadOnlySpace::writable().
Referenced by v8::internal::CodeSerializer::SerializeObjectImpl(), v8::internal::ContextSerializer::SerializeObjectImpl(), v8::internal::StartupSerializer::SerializeObjectImpl(), and v8::internal::SharedHeapSerializer::SerializeObjectImpl().
SerializeRoot()
bool v8::internal::Serializer::SerializeRoot (Tagged< HeapObject > obj) [protected]
Definition at line 210 of file serializer.cc.
                                                     {
  RootIndex root_index;
  // Derived serializers are responsible for determining if the root has
  // actually been serialized before calling this.
  if (root_index_map()->Lookup(obj, &root_index)) {
    PutRoot(root_index);
    return true;
  }
  return false;
}
References PutRoot(), and root_index_map().
Referenced by v8::internal::CodeSerializer::SerializeObjectImpl(), v8::internal::ContextSerializer::SerializeObjectImpl(), v8::internal::StartupSerializer::SerializeObjectImpl(), and v8::internal::SharedHeapSerializer::SerializeObjectImpl().
SerializeRootObject()
void v8::internal::Serializer::SerializeRootObject (FullObjectSlot slot) [protected]
Definition at line 190 of file serializer.cc.
                                                        {
  Tagged<Object> o = *slot;
  if (IsSmi(o)) {
    PutSmiRoot(slot);
  } else {
    SerializeObject(Handle<HeapObject>(slot.location()), SlotType::kAnySlot);
  }
}
References v8::internal::IsSmi(), v8::internal::SerializerDeserializer::kAnySlot, v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::location(), PutSmiRoot(), and SerializeObject().
Referenced by v8::internal::RootsSerializer::VisitRootPointers(), and VisitRootPointers().
set_serializer_tracks_serialization_statistics()
void v8::internal::Serializer::set_serializer_tracks_serialization_statistics (bool v) [inline], [protected]
Definition at line 343 of file serializer.h.
                                                              {
    serializer_tracks_serialization_statistics_ = v;
  }
References serializer_tracks_serialization_statistics_.
TotalAllocationSize()
int v8::internal::Serializer::TotalAllocationSize () const
Definition at line 80 of file serializer.cc.
                                          {
  int sum = 0;
  for (int space = 0; space < kNumberOfSnapshotSpaces; space++) {
    sum += allocation_size_[space];
  }
  return sum;
}
References allocation_size_, v8::internal::kNumberOfSnapshotSpaces, and space.
Referenced by v8::internal::Snapshot::Create().
TryEncodeExternalReference()
Maybe<ExternalReferenceEncoder::Value> v8::internal::Serializer::TryEncodeExternalReference (Address addr) [inline], [protected]
Definition at line 278 of file serializer.h.
                    {
    return external_reference_encoder_.TryEncode(addr);
  }
References external_reference_encoder_, and v8::internal::ExternalReferenceEncoder::TryEncode().
VisitRootPointers()
void v8::internal::Serializer::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [override], [protected], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 183 of file serializer.cc.
                                                                             {
  for (FullObjectSlot current = start; current < end; ++current) {
    SerializeRootObject(current);
  }
}
References v8::internal::compiler::end(), and SerializeRootObject().
Referenced by v8::internal::RootsSerializer::VisitRootPointers().
Member Data Documentation
allocation_size_
size_t v8::internal::Serializer::allocation_size_[kNumberOfSnapshotSpaces] = {0} [private]
Definition at line 438 of file serializer.h.
Referenced by CountAllocation(), OutputStatistics(), and TotalAllocationSize().
code_address_map_
std::unique_ptr<CodeAddressMap> v8::internal::Serializer::code_address_map_ [private]
Definition at line 402 of file serializer.h.
Referenced by InitializeCodeAddressMap(), and v8::internal::Serializer::ObjectSerializer::SerializePrologue().
code_buffer_
std::vector<uint8_t> v8::internal::Serializer::code_buffer_ [private]
Definition at line 403 of file serializer.h.
Referenced by CopyCode().
deferred_objects_
GlobalHandleVector<HeapObject> v8::internal::Serializer::deferred_objects_ [private]
Definition at line 405 of file serializer.h.
Referenced by deferred_objects_empty(), QueueDeferredObject(), and SerializeDeferredObjects().
dispatch_handle_map_
std::unordered_map<JSDispatchHandle, uint32_t> v8::internal::Serializer::dispatch_handle_map_ [private]
Definition at line 409 of file serializer.h.
external_reference_encoder_
ExternalReferenceEncoder v8::internal::Serializer::external_reference_encoder_ [private]
Definition at line 400 of file serializer.h.
Referenced by EncodeExternalReference(), and TryEncodeExternalReference().
flags_
const Snapshot::SerializerFlags v8::internal::Serializer::flags_ [private]
Definition at line 435 of file serializer.h.
Referenced by allow_active_isolate_for_testing(), allow_unknown_external_references_for_testing(), and reconstruct_read_only_and_shared_object_caches_for_testing().
forward_refs_per_pending_object_
IdentityMap<PendingObjectReferences, base::DefaultAllocationPolicy> v8::internal::Serializer::forward_refs_per_pending_object_ [private]
Definition at line 425 of file serializer.h.
Referenced by RegisterObjectIsPending(), ResolvePendingObject(), SerializePendingObject(), and v8::internal::Serializer::ObjectSerializer::SerializePrologue().
hot_objects_
HotObjectsList v8::internal::Serializer::hot_objects_ [private]
Definition at line 398 of file serializer.h.
Referenced by PutBackReference(), PutRoot(), and SerializeHotObject().
isolate_
Isolate* v8::internal::Serializer::isolate_ [private]
Definition at line 394 of file serializer.h.
Referenced by InitializeCodeAddressMap(), isolate(), v8::internal::Serializer::ObjectSerializer::OutputRawData(), and v8::internal::Serializer::ObjectSerializer::SerializePrologue().
next_forward_ref_id_
int v8::internal::Serializer::next_forward_ref_id_ = 0 [private]
Definition at line 422 of file serializer.h.
Referenced by PutPendingForwardReference(), and ResolvePendingForwardReference().
num_back_refs_
int v8::internal::Serializer::num_back_refs_ = 0 [private]
Definition at line 406 of file serializer.h.
Referenced by v8::internal::Serializer::ObjectSerializer::SerializePrologue().
recursion_depth_
int v8::internal::Serializer::recursion_depth_ = 0 [private]
Definition at line 434 of file serializer.h.
reference_map_
SerializerReferenceMap v8::internal::Serializer::reference_map_ [private]
Definition at line 399 of file serializer.h.
Referenced by QueueDeferredObject(), reference_map(), and SerializeBackReference().
root_index_map_
RootIndexMap v8::internal::Serializer::root_index_map_ [private]
Definition at line 401 of file serializer.h.
Referenced by root_index_map().
seen_backing_stores_index_
uint32_t v8::internal::Serializer::seen_backing_stores_index_ = 1 [private]
Definition at line 432 of file serializer.h.
serializer_tracks_serialization_statistics_
bool v8::internal::Serializer::serializer_tracks_serialization_statistics_ = true [private]
Definition at line 437 of file serializer.h.
Referenced by serializer_tracks_serialization_statistics(), and set_serializer_tracks_serialization_statistics().
sink_
SnapshotByteSink v8::internal::Serializer::sink_ [protected]
Definition at line 323 of file serializer.h.
Referenced by v8::internal::Serializer::ObjectSerializer::OutputExternalReference(), v8::internal::Serializer::ObjectSerializer::OutputRawData(), Pad(), Payload(), PutAttachedReference(), PutBackReference(), PutPendingForwardReference(), PutRepeatRoot(), PutRoot(), PutSmiRoot(), ResolvePendingForwardReference(), v8::internal::ReadOnlySerializer::Serialize(), v8::internal::ContextSerializer::Serialize(), v8::internal::Serializer::ObjectSerializer::SerializeBackingStore(), SerializeBackReference(), SerializeDeferredObjects(), v8::internal::Serializer::ObjectSerializer::SerializeExternalStringAsSequentialString(), v8::internal::CodeSerializer::SerializeGeneric(), SerializeHotObject(), v8::internal::CodeSerializer::SerializeObjectImpl(), v8::internal::ContextSerializer::SerializeObjectImpl(), v8::internal::StartupSerializer::SerializeObjectImpl(), v8::internal::SharedHeapSerializer::SerializeObjectImpl(), v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields(), v8::internal::CodeSerializer::SerializeSharedFunctionInfo(), v8::internal::SharedHeapSerializer::SerializeStringTable(), v8::internal::StartupSerializer::StartupSerializer(), v8::internal::RootsSerializer::Synchronize(), v8::internal::Serializer::ObjectSerializer::VisitCppHeapPointer(), v8::internal::Serializer::ObjectSerializer::VisitIndirectPointer(), v8::internal::Serializer::ObjectSerializer::VisitJSDispatchTableEntry(), v8::internal::Serializer::ObjectSerializer::VisitPointers(), and v8::internal::Serializer::ObjectSerializer::VisitProtectedPointer().
unresolved_forward_refs_
int v8::internal::Serializer::unresolved_forward_refs_ = 0 [private]
Definition at line 423 of file serializer.h.
Referenced by PutPendingForwardReference(), ResolvePendingForwardReference(), and ~Serializer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/serializer.h
/mnt/V8SourceCode/src/snapshot/serializer-inl.h
/mnt/V8SourceCode/src/snapshot/serializer.cc