v8::internal::Parser::TemplateLiteral Class Reference
Public Member Functions
TemplateLiteral (Zone *zone, int pos)
const ZonePtrList< const AstRawString > * cooked () const
const ZonePtrList< const AstRawString > * raw () const
const ZonePtrList< Expression > * expressions () const
int position () const
void AddTemplateSpan (const AstRawString *cooked, const AstRawString *raw, int end, Zone *zone)
void AddExpression (Expression *expression, Zone *zone)
Private Attributes
ZonePtrList< const AstRawString > cooked_
ZonePtrList< const AstRawString > raw_
ZonePtrList< Expression > expressions_
int pos_
Detailed Description
Definition at line 487 of file parser.h.
Constructor & Destructor Documentation
TemplateLiteral()
v8::internal::Parser::TemplateLiteral::TemplateLiteral (Zone * zone, int pos) [inline]
Definition at line 489 of file parser.h.
        : cooked_(8, zone), raw_(8, zone), expressions_(8, zone), pos_(pos) {}
Member Function Documentation
AddExpression()
void v8::internal::Parser::TemplateLiteral::AddExpression (Expression * expression, Zone * zone) [inline]
Definition at line 504 of file parser.h.
                                                           {
      expressions_.Add(expression, zone);
    }
AddTemplateSpan()
void v8::internal::Parser::TemplateLiteral::AddTemplateSpan (const AstRawString * cooked, const AstRawString * raw, int end, Zone * zone) [inline]
Definition at line 497 of file parser.h.
                                              {
      DCHECK_NOT_NULL(raw);
      cooked_.Add(cooked, zone);
      raw_.Add(raw, zone);
    }
References DCHECK_NOT_NULL.
cooked()
const ZonePtrList<const AstRawString>* v8::internal::Parser::TemplateLiteral::cooked () const [inline]
Definition at line 492 of file parser.h.
{ return &cooked_; }
Referenced by v8::internal::Parser::CloseTemplateLiteral().
expressions()
const ZonePtrList<Expression>* v8::internal::Parser::TemplateLiteral::expressions () const [inline]
Definition at line 494 of file parser.h.
{ return &expressions_; }
Referenced by v8::internal::Parser::CloseTemplateLiteral().
position()
int v8::internal::Parser::TemplateLiteral::position () const [inline]
Definition at line 495 of file parser.h.
{ return pos_; }
Referenced by v8::internal::Parser::CloseTemplateLiteral().
raw()
const ZonePtrList<const AstRawString>* v8::internal::Parser::TemplateLiteral::raw () const [inline]
Definition at line 493 of file parser.h.
{ return &raw_; }
Referenced by v8::internal::Parser::CloseTemplateLiteral().
Member Data Documentation
cooked_
ZonePtrList<const AstRawString> v8::internal::Parser::TemplateLiteral::cooked_ [private]
Definition at line 509 of file parser.h.
expressions_
ZonePtrList<Expression> v8::internal::Parser::TemplateLiteral::expressions_ [private]
Definition at line 511 of file parser.h.
pos_
int v8::internal::Parser::TemplateLiteral::pos_ [private]
Definition at line 512 of file parser.h.
raw_
ZonePtrList<const AstRawString> v8::internal::Parser::TemplateLiteral::raw_ [private]
Definition at line 510 of file parser.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/parser.h