v8::internal::StrongTaggedValue Class Reference
#include <tagged-value.h>
Public Member Functions
constexpr StrongTaggedValue ()
constexpr StrongTaggedValue (Tagged_t ptr)
StrongTaggedValue (Tagged< Object > o)
Static Public Member Functions
static Tagged< Object > ToObject (Isolate *isolate, StrongTaggedValue object)
Additional Inherited Members
Detailed Description
Definition at line 19 of file tagged-value.h.
Constructor & Destructor Documentation
StrongTaggedValue() [1/3]
constexpr v8::internal::StrongTaggedValue::StrongTaggedValue () [inline], [constexpr]
Definition at line 22 of file tagged-value.h.
: TaggedImpl() {}
StrongTaggedValue() [2/3]
constexpr v8::internal::StrongTaggedValue::StrongTaggedValue (Tagged_t ptr) [inline], [explicit], [constexpr]
Definition at line 23 of file tagged-value.h.
: TaggedImpl(ptr) {}
StrongTaggedValue() [3/3]
v8::internal::StrongTaggedValue::StrongTaggedValue (Tagged< Object > o) [inline], [explicit]
Definition at line 22 of file tagged-value-inl.h.
    :
#ifdef V8_COMPRESS_POINTERS
      TaggedImpl(V8HeapCompressionScheme::CompressObject(o.ptr()))
#else
      TaggedImpl(o.ptr())
#endif
{
}
Member Function Documentation
ToObject()
Tagged< Object > v8::internal::StrongTaggedValue::ToObject (Isolate * isolate, StrongTaggedValue object) [inline], [static]
Definition at line 32 of file tagged-value-inl.h.
                                                                     {
#ifdef V8_COMPRESS_POINTERS
  return Tagged<Object>(
      V8HeapCompressionScheme::DecompressTagged(object.ptr()));
#else
  return Tagged<Object>(object.ptr());
#endif
}
References v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTagged(), v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Tagged_t >::ptr(), and v8::internal::Tagged< Object >.
Referenced by v8::internal::StubCache::Set().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/tagged-value.h
/mnt/V8SourceCode/src/objects/tagged-value-inl.h