v8::internal::FixedRangeBodyDescriptor< start_offset, end_offset > Class Template Reference
#include <objects-body-descriptors.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, ObjectVisitor *v)
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
Static Public Attributes
static const int kStartOffset = start_offset
static const int kEndOffset = end_offset
Additional Inherited Members
Detailed Description
template<int start_offset, int end_offset>
class v8::internal::FixedRangeBodyDescriptor< start_offset, end_offset >
Definition at line 117 of file objects-body-descriptors.h.
Member Function Documentation
IterateBody() [1/2]
template<int start_offset, int end_offset>
template<typename ObjectVisitor >
static void v8::internal::FixedRangeBodyDescriptor< start_offset, end_offset >::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 129 of file objects-body-descriptors.h.
                                                                    {
    IterateBody(map, obj, v);
  }
References v8::internal::FixedRangeBodyDescriptor< start_offset, end_offset >::IterateBody().
IterateBody() [2/2]
template<int start_offset, int end_offset>
template<typename ObjectVisitor >
static void v8::internal::FixedRangeBodyDescriptor< start_offset, end_offset >::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, ObjectVisitor * v) [inline], [static]
Definition at line 123 of file objects-body-descriptors.h.
                                                   {
    IteratePointers(obj, start_offset, end_offset, v);
  }
References v8::internal::BodyDescriptorBase::IteratePointers().
Referenced by v8::internal::FixedRangeBodyDescriptor< start_offset, end_offset >::IterateBody().
Member Data Documentation
kEndOffset
template<int start_offset, int end_offset>
const int v8::internal::FixedRangeBodyDescriptor< start_offset, end_offset >::kEndOffset = end_offset [static]
Definition at line 120 of file objects-body-descriptors.h.
kStartOffset
template<int start_offset, int end_offset>
const int v8::internal::FixedRangeBodyDescriptor< start_offset, end_offset >::kStartOffset = start_offset [static]
Definition at line 119 of file objects-body-descriptors.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors.h