v8::internal::JSRegExp Class Reference
#include <js-regexp.h>
Classes
class BodyDescriptor
Public Member Functions
Tagged< String > source () const
Flags flags () const
Tagged< String > EscapedPattern ()
Static Public Member Functions
static V8_EXPORT_PRIVATE MaybeDirectHandle< JSRegExp > New (Isolate *isolate, DirectHandle< String > source, Flags flags, uint32_t backtrack_limit=kNoBacktrackLimit)
static MaybeDirectHandle< JSRegExp > Initialize (Isolate *isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > source, Flags flags, uint32_t backtrack_limit=kNoBacktrackLimit)
static MaybeDirectHandle< JSRegExp > Initialize (Isolate *isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > source, DirectHandle< String > flags_string)
static constexpr Flag AsJSRegExpFlag (RegExpFlag f)
static constexpr Flags AsJSRegExpFlags (RegExpFlags f)
static constexpr RegExpFlags AsRegExpFlags (Flags f)
static std::optional< RegExpFlag > FlagFromChar (char c)
static std::optional< Flags > FlagsFromString (Isolate *isolate, DirectHandle< String > flags)
static V8_EXPORT_PRIVATE DirectHandle< String > StringFromFlags (Isolate *isolate, Flags flags)
static constexpr int RegistersForCaptureCount (int count)
static constexpr int CaptureCountForRegisters (int register_count)
static constexpr int Size ()
Static Public Attributes
static constexpr int kAtomCaptureCount = 0
static constexpr int kAtomRegisterCount = 2
static constexpr int kLastIndexOffset = kHeaderSize
static constexpr int kInitialLastIndexValue = 0
static constexpr int kLastIndexFieldIndex = 0
static constexpr int kInObjectFieldCount = 1
static constexpr int kSize = kHeaderSize + kInObjectFieldCount * kTaggedSize
static constexpr int kExecFunctionDescriptorIndex = 1
static constexpr int kSymbolMatchFunctionDescriptorIndex = 15
static constexpr int kSymbolMatchAllFunctionDescriptorIndex = 16
static constexpr int kSymbolReplaceFunctionDescriptorIndex = 17
static constexpr int kSymbolSearchFunctionDescriptorIndex = 18
static constexpr int kSymbolSplitFunctionDescriptorIndex = 19
static constexpr int kUninitializedValue = -1
static constexpr uint32_t kNoBacktrackLimit = 0
static constexpr int kTierUpForSubjectLengthValue = 1000
static constexpr int kMaxCaptures = 1 << 16
Private Types
using FlagsBuffer = base::EmbeddedVector< char, kFlagCount+1 >
Static Private Member Functions
static const char * FlagsToString (Flags flags, FlagsBuffer *out_buffer)
Friends
class RegExpData
Detailed Description
Definition at line 28 of file js-regexp.h.
Member Typedef Documentation
FlagsBuffer
using v8::internal::JSRegExp::FlagsBuffer = base::EmbeddedVector<char, kFlagCount + 1> [private]
Definition at line 146 of file js-regexp.h.
Member Function Documentation
AsJSRegExpFlag()
static constexpr Flag v8::internal::JSRegExp::AsJSRegExpFlag (RegExpFlag f) [inline], [static], [constexpr]
Definition at line 52 of file js-regexp.h.
                                                     {
    return static_cast<Flag>(f);
  }
AsJSRegExpFlags()
static constexpr Flags v8::internal::JSRegExp::AsJSRegExpFlags (RegExpFlags f) [inline], [static], [constexpr]
Definition at line 55 of file js-regexp.h.
                                                        {
    return Flags{static_cast<int>(f)};
  }
References v8::internal::Flags().
Referenced by v8::internal::RegExpImpl::AtomCompile(), v8::internal::RegExp::Compile(), FlagsFromString(), v8::internal::RegExpMacroAssemblerTracer::GetCode(), v8::internal::ExperimentalRegExp::Initialize(), v8::internal::RegExpImpl::IrregexpInitialize(), v8::internal::CodeEventLogger::RegExpCodeCreateEvent(), and v8::internal::RegExp::ThrowRegExpException().
AsRegExpFlags()
static constexpr RegExpFlags v8::internal::JSRegExp::AsRegExpFlags (Flags f) [inline], [static], [constexpr]
Definition at line 58 of file js-regexp.h.
                                                      {
    return RegExpFlags{static_cast<int>(f)};
  }
Referenced by v8::internal::RegExpGlobalExecRunner::AdvanceZeroLength(), v8::internal::RegExp::AtomExecRaw(), v8::internal::RegExpImpl::AtomExecRaw(), v8::internal::anonymous_namespace{experimental.cc}::CompileImpl(), v8::internal::RegExpImpl::CompileIrregexp(), Initialize(), v8::internal::IrregexpInterpreter::Match(), v8::internal::RegExpGlobalExecRunner::RegExpGlobalExecRunner(), and v8::internal::RegExp::ThrowRegExpException().
CaptureCountForRegisters()
static constexpr int v8::internal::JSRegExp::CaptureCountForRegisters (int register_count) [inline], [static], [constexpr]
Definition at line 94 of file js-regexp.h.
                                                                    {
    DCHECK_EQ(register_count % 2, 0);
    DCHECK_GE(register_count, 2);
    return (register_count - 2) / 2;
  }
References DCHECK_EQ, and DCHECK_GE.
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::Debug::StartSideEffectCheckMode().
EscapedPattern()
Tagged< String > v8::internal::JSRegExp::EscapedPattern () [inline]
Definition at line 60 of file js-regexp-inl.h.
                                        {
  DCHECK(IsString(source()));
  return Cast<String>(source());
}
References v8::internal::DCHECK(), and source().
FlagFromChar()
static std::optional<RegExpFlag> v8::internal::JSRegExp::FlagFromChar (char c) [inline], [static]
Definition at line 62 of file js-regexp.h.
                                                      {
    std::optional<RegExpFlag> f = TryRegExpFlagFromChar(c);
    if (!f.has_value()) return f;
    if (f.value() == RegExpFlag::kLinear &&
        !v8_flags.enable_experimental_regexp_engine) {
      return {};
    }
    return f;
  }
References v8::internal::TryRegExpFlagFromChar(), and v8::internal::v8_flags.
Referenced by FlagsFromString(), and v8::internal::Scanner::ScanRegExpFlags().
flags()
JSRegExp::Flags v8::internal::JSRegExp::flags () const [inline]
Definition at line 40 of file js-regexp-inl.h.
                                    {
  Tagged<Smi> smi = Cast<Smi>(TorqueGeneratedClass::flags());
  return Flags(smi.value());
}
References v8::internal::Flags(), flags(), and v8::internal::Tagged< Smi >::value().
Referenced by FlagsFromString(), Initialize(), New(), and StringFromFlags().
FlagsFromString()
std::optional< JSRegExp::Flags > v8::internal::JSRegExp::FlagsFromString (Isolate * isolate, DirectHandle< String > flags) [static]
Definition at line 123 of file js-regexp.cc.
                                                  {
  const int length = flags->length();
  // A longer flags string cannot be valid.
  if (length > JSRegExp::kFlagCount) return {};
  RegExpFlags value;
  FlatStringReader reader(isolate, String::Flatten(isolate, flags));
  for (int i = 0; i < length; i++) {
    std::optional<RegExpFlag> flag = JSRegExp::FlagFromChar(reader.Get(i));
    if (!flag.has_value()) return {};
    if (value & flag.value()) return {}; // Duplicate.
    value |= flag.value();
  }
  return JSRegExp::AsJSRegExpFlags(value);
}
References AsJSRegExpFlags(), FlagFromChar(), flags(), v8::internal::FlatStringReader::Get(), v8::internal::length, and v8::internal::value.
Referenced by Initialize(), and v8::internal::RUNTIME_FUNCTION().
FlagsToString()
static const char* v8::internal::JSRegExp::FlagsToString (Flags flags, FlagsBuffer * out_buffer) [inline], [static], [private]
Referenced by StringFromFlags().
Initialize() [1/2]
MaybeDirectHandle< JSRegExp > v8::internal::JSRegExp::Initialize (Isolate * isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > source, DirectHandle< String > flags_string) [static]
Definition at line 168 of file js-regexp.cc.
                                                                    {
  std::optional<Flags> flags = JSRegExp::FlagsFromString(isolate, flags_string);
  if (!flags.has_value() ||
      !RegExp::VerifyFlags(JSRegExp::AsRegExpFlags(flags.value()))) {
    THROW_NEW_ERROR(
        isolate,
        NewSyntaxError(MessageTemplate::kInvalidRegExpFlags, flags_string));
  }
  return Initialize(isolate, regexp, source, flags.value());
}
References AsRegExpFlags(), flags(), FlagsFromString(), Initialize(), source(), THROW_NEW_ERROR, and v8::internal::RegExp::VerifyFlags().
Initialize() [2/2]
MaybeDirectHandle< JSRegExp > v8::internal::JSRegExp::Initialize (Isolate * isolate, DirectHandle< JSRegExp > regexp, DirectHandle< String > source, Flags flags, uint32_t backtrack_limit = kNoBacktrackLimit) [static]
Definition at line 333 of file js-regexp.cc.
                                                                           {
  Factory* factory = isolate->factory();
  // If source is the empty string we set it to "(?:)" instead as
  // suggested by ECMA-262, 5th, section 15.10.4.1.
  if (source->length() == 0) source = factory->query_colon_string();
  source = String::Flatten(isolate, source);
  RETURN_ON_EXCEPTION(isolate, RegExp::Compile(isolate, regexp, source,
                                               JSRegExp::AsRegExpFlags(flags),
                                               backtrack_limit));
  DirectHandle<String> escaped_source;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, escaped_source,
                             EscapeRegExpSource(isolate, source));
  regexp->set_source(*escaped_source);
  regexp->set_flags(Smi::FromInt(flags));
  Tagged<Map> map = regexp->map();
  Tagged<Object> constructor = map->GetConstructor();
  if (IsJSFunction(constructor) &&
      Cast<JSFunction>(constructor)->initial_map() == map) {
    // If we still have the original map, set in-object properties directly.
    regexp->InObjectPropertyAtPut(JSRegExp::kLastIndexFieldIndex,
                                  Smi::FromInt(kInitialLastIndexValue),
                                  SKIP_WRITE_BARRIER);
  } else {
    // Map has changed, so use generic, but slower, method.
    RETURN_ON_EXCEPTION(
        isolate,
        Object::SetProperty(
            isolate, regexp, factory->lastIndex_string(),
            DirectHandle<Smi>(Smi::FromInt(kInitialLastIndexValue), isolate)));
  }
  return regexp;
}
References AsRegExpFlags(), ASSIGN_RETURN_ON_EXCEPTION, v8::internal::RegExp::Compile(), v8::internal::anonymous_namespace{js-regexp.cc}::EscapeRegExpSource(), v8::internal::Isolate::factory(), flags(), v8::internal::Smi::FromInt(), v8::internal::compiler::initial_map, kInitialLastIndexValue, kLastIndexFieldIndex, RETURN_ON_EXCEPTION, v8::internal::Object::SetProperty(), v8::internal::SKIP_WRITE_BARRIER, and source().
Referenced by Initialize(), New(), and v8::internal::RUNTIME_FUNCTION().
New()
MaybeDirectHandle< JSRegExp > v8::internal::JSRegExp::New (Isolate * isolate, DirectHandle< String > source, Flags flags, uint32_t backtrack_limit = kNoBacktrackLimit) [static]
Definition at line 152 of file js-regexp.cc.
                                                                    {
  DirectHandle<JSFunction> constructor = isolate->regexp_function();
  DirectHandle<JSRegExp> regexp =
      Cast<JSRegExp>(isolate->factory()->NewJSObject(constructor));
  // Clear the data field, as a GC can be triggered before the field is set
  // during compilation.
  regexp->clear_data();
  return JSRegExp::Initialize(isolate, regexp, pattern, flags, backtrack_limit);
}
References v8::internal::Isolate::factory(), flags(), Initialize(), and v8::internal::Factory::NewJSObject().
Referenced by v8::RegExp::New(), v8::RegExp::NewWithBacktrackLimit(), v8::internal::ValueDeserializer::ReadJSRegExp(), and v8::internal::RUNTIME_FUNCTION().
RegistersForCaptureCount()
static constexpr int v8::internal::JSRegExp::RegistersForCaptureCount (int count) [inline], [static], [constexpr]
Definition at line 91 of file js-regexp.h.
                                                           {
    return (count + 1) * 2;
  }
Referenced by v8::internal::RegExpImpl::Compile(), v8::internal::ExperimentalRegExp::Exec(), v8::internal::RegExp::Exec_Single(), v8::internal::anonymous_namespace{experimental.cc}::ExecRawImpl(), v8::internal::anonymous_namespace{runtime-regexp.cc}::ExperimentalOneshotExec(), v8::internal::RegExpImpl::IrregexpExec(), v8::internal::RegExpImpl::IrregexpExecRaw(), v8::internal::RegExpImpl::IrregexpPrepare(), v8::internal::IrregexpInterpreter::Match(), v8::internal::RegExpMatchInfo::New(), v8::internal::ExperimentalRegExp::OneshotExec(), v8::internal::RegExpGlobalExecRunner::RegExpGlobalExecRunner(), v8::internal::RegExpMatchInfo::ReserveCaptures(), v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple(), and v8::internal::RegExp::SetLastMatchInfo().
Size()
static constexpr int v8::internal::JSRegExp::Size () [inline], [static], [constexpr]
Definition at line 120 of file js-regexp.h.
{ return kSize; }
References kSize.
Referenced by v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp(), v8::internal::ConstructorBuiltinsAssembler::CreateRegExpLiteral(), and v8::internal::maglev::MaglevGraphBuilder::CreateRegExpLiteralObject().
source()
Tagged< String > v8::internal::JSRegExp::source () const [inline]
Definition at line 36 of file js-regexp-inl.h.
                                      {
  return Cast<String>(TorqueGeneratedClass::source());
}
Referenced by EscapedPattern(), and Initialize().
StringFromFlags()
DirectHandle< String > v8::internal::JSRegExp::StringFromFlags (Isolate * isolate, Flags flags) [static]
Definition at line 144 of file js-regexp.cc.
                                                                    {
  FlagsBuffer buffer;
  return isolate->factory()->NewStringFromAsciiChecked(
      FlagsToString(flags, &buffer));
}
References v8::internal::Isolate::factory(), flags(), FlagsToString(), and v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked().
Referenced by v8::internal::RegExpMacroAssemblerTracer::GetCode(), v8::internal::CodeEventLogger::RegExpCodeCreateEvent(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::RegExp::ThrowRegExpException().
Friends And Related Function Documentation
RegExpData
friend class RegExpData [friend]
Definition at line 149 of file js-regexp.h.
Member Data Documentation
kAtomCaptureCount
constexpr int v8::internal::JSRegExp::kAtomCaptureCount = 0 [static], [constexpr]
Definition at line 100 of file js-regexp.h.
Referenced by v8::internal::RegExpBuiltinsAssembler::LoadCaptureCount().
kAtomRegisterCount
constexpr int v8::internal::JSRegExp::kAtomRegisterCount = 2 [static], [constexpr]
Definition at line 101 of file js-regexp.h.
Referenced by v8::internal::RegExpImpl::AtomExecRaw(), v8::internal::anonymous_namespace{regexp.cc}::AtomExecRawImpl(), and v8::internal::RegExpGlobalExecRunner::RegExpGlobalExecRunner().
kExecFunctionDescriptorIndex
constexpr int v8::internal::JSRegExp::kExecFunctionDescriptorIndex = 1 [static], [constexpr]
Definition at line 123 of file js-regexp.h.
Referenced by v8::internal::RegExpBuiltinsAssembler::BranchIfFastRegExp(), v8::internal::Genesis::InitializeGlobal(), and v8::internal::RegExpUtils::IsUnmodifiedRegExp().
kInitialLastIndexValue
constexpr int v8::internal::JSRegExp::kInitialLastIndexValue = 0 [static], [constexpr]
Definition at line 112 of file js-regexp.h.
Referenced by v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp(), v8::internal::ConstructorBuiltinsAssembler::CreateRegExpLiteral(), v8::internal::maglev::MaglevGraphBuilder::CreateRegExpLiteralObject(), and Initialize().
kInObjectFieldCount
constexpr int v8::internal::JSRegExp::kInObjectFieldCount = 1 [static], [constexpr]
Definition at line 116 of file js-regexp.h.
Referenced by v8::internal::Genesis::InitializeGlobal().
kLastIndexFieldIndex
constexpr int v8::internal::JSRegExp::kLastIndexFieldIndex = 0 [static], [constexpr]
Definition at line 115 of file js-regexp.h.
Referenced by v8::internal::RegExpBuiltinsAssembler::FastLoadLastIndexBeforeSmiCheck(), v8::internal::RegExpBuiltinsAssembler::FastStoreLastIndex(), Initialize(), and v8::internal::Genesis::InitializeGlobal().
kLastIndexOffset
constexpr int v8::internal::JSRegExp::kLastIndexOffset = kHeaderSize [static], [constexpr]
Definition at line 109 of file js-regexp.h.
Referenced by v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp(), v8::internal::ConstructorBuiltinsAssembler::CreateRegExpLiteral(), v8::internal::maglev::MaglevGraphBuilder::CreateRegExpLiteralObject(), and v8::internal::compiler::AccessBuilder::ForJSRegExpLastIndex().
kMaxCaptures
constexpr int v8::internal::JSRegExp::kMaxCaptures = 1 << 16 [static], [constexpr]
Definition at line 141 of file js-regexp.h.
Referenced by v8::internal::RegExpBuiltinsAssembler::RegistersForCaptureCount().
kNoBacktrackLimit
constexpr uint32_t v8::internal::JSRegExp::kNoBacktrackLimit = 0 [static], [constexpr]
Definition at line 134 of file js-regexp.h.
Referenced by v8::internal::RegExp::Compile(), v8::internal::RegExpImpl::Compile(), v8::internal::RegExp::CompileForTesting(), v8::internal::RegExpMacroAssembler::has_backtrack_limit(), v8::RegExp::NewWithBacktrackLimit(), and v8::internal::anonymous_namespace{regexp-interpreter.cc}::RawMatch().
kSize
constexpr int v8::internal::JSRegExp::kSize = kHeaderSize + kInObjectFieldCount * kTaggedSize [static], [constexpr]
Definition at line 119 of file js-regexp.h.
Referenced by Size().
kSymbolMatchAllFunctionDescriptorIndex
constexpr int v8::internal::JSRegExp::kSymbolMatchAllFunctionDescriptorIndex = 16 [static], [constexpr]
Definition at line 125 of file js-regexp.h.
Referenced by v8::internal::Genesis::InitializeGlobal(), and v8::internal::TF_BUILTIN().
kSymbolMatchFunctionDescriptorIndex
constexpr int v8::internal::JSRegExp::kSymbolMatchFunctionDescriptorIndex = 15 [static], [constexpr]
Definition at line 124 of file js-regexp.h.
Referenced by v8::internal::RegExpBuiltinsAssembler::BranchIfFastRegExpForMatch(), and v8::internal::Genesis::InitializeGlobal().
kSymbolReplaceFunctionDescriptorIndex
constexpr int v8::internal::JSRegExp::kSymbolReplaceFunctionDescriptorIndex = 17 [static], [constexpr]
Definition at line 126 of file js-regexp.h.
Referenced by v8::internal::Genesis::InitializeGlobal(), and v8::internal::TF_BUILTIN().
kSymbolSearchFunctionDescriptorIndex
constexpr int v8::internal::JSRegExp::kSymbolSearchFunctionDescriptorIndex = 18 [static], [constexpr]
Definition at line 127 of file js-regexp.h.
Referenced by v8::internal::RegExpBuiltinsAssembler::BranchIfFastRegExpForSearch(), and v8::internal::Genesis::InitializeGlobal().
kSymbolSplitFunctionDescriptorIndex
constexpr int v8::internal::JSRegExp::kSymbolSplitFunctionDescriptorIndex = 19 [static], [constexpr]
Definition at line 128 of file js-regexp.h.
Referenced by v8::internal::Genesis::InitializeGlobal(), and v8::internal::TF_BUILTIN().
kTierUpForSubjectLengthValue
constexpr int v8::internal::JSRegExp::kTierUpForSubjectLengthValue = 1000 [static], [constexpr]
Definition at line 138 of file js-regexp.h.
Referenced by v8::internal::RegExpImpl::IrregexpExec().
kUninitializedValue
constexpr int v8::internal::JSRegExp::kUninitializedValue = -1 [static], [constexpr]
Definition at line 131 of file js-regexp.h.
Referenced by v8::internal::Factory::NewExperimentalRegExpData(), and v8::internal::Factory::NewIrRegExpData().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-regexp.h
/mnt/V8SourceCode/src/objects/js-regexp-inl.h
/mnt/V8SourceCode/src/objects/js-regexp.cc