v8::internal::ThreadState Class Reference
#include <v8threads.h>
Public Types
enum List { FREE_LIST
, IN_USE_LIST
 }
Public Member Functions
ThreadState * Next ()
void LinkInto (List list)
void Unlink ()
void set_id (ThreadId id)
ThreadId id ()
char * data ()
Private Member Functions
ThreadState (ThreadManager *thread_manager)
~ThreadState ()
void AllocateSpace ()
Private Attributes
ThreadId id_
char * data_
ThreadState * next_
ThreadState * previous_
ThreadManager * thread_manager_
Friends
class ThreadManager
Detailed Description
Definition at line 18 of file v8threads.h.
Member Enumeration Documentation
List
enum v8::internal::ThreadState::List
Enumerator
FREE_LIST
IN_USE_LIST
Definition at line 23 of file v8threads.h.
{ FREE_LIST, IN_USE_LIST };
Constructor & Destructor Documentation
ThreadState()
v8::internal::ThreadState::ThreadState (ThreadManager * thread_manager) [explicit], [private]
Definition at line 169 of file v8threads.cc.
    : id_(ThreadId::Invalid()),
      data_(nullptr),
      next_(this),
      previous_(this),
      thread_manager_(thread_manager) {}
 ThreadState()
v8::internal::ThreadState::~ThreadState () [private]
Definition at line 176 of file v8threads.cc.
{ DeleteArray<char>(data_); }
References data_.
Member Function Documentation
AllocateSpace()
void v8::internal::ThreadState::AllocateSpace () [private]
Definition at line 178 of file v8threads.cc.
                                {
  data_ = NewArray<char>(ArchiveSpacePerThread());
}
References v8::internal::ArchiveSpacePerThread(), and data_.
Referenced by v8::internal::ThreadManager::GetFreeThreadState().
data()
char* v8::internal::ThreadState::data () [inline]
Definition at line 33 of file v8threads.h.
{ return data_; }
References data_.
Referenced by v8::internal::ThreadManager::EagerlyArchiveThread(), and v8::internal::ThreadManager::RestoreThread().
id()
ThreadId v8::internal::ThreadState::id () [inline]
Definition at line 30 of file v8threads.h.
{ return id_; }
References id_.
Referenced by v8::internal::ThreadManager::ArchiveThread(), and set_id().
LinkInto()
void v8::internal::ThreadState::LinkInto (List list)
Definition at line 187 of file v8threads.cc.
                                    {
  ThreadState* flying_anchor = list == FREE_LIST
                                   ? thread_manager_->free_anchor_
                                   : thread_manager_->in_use_anchor_;
  next_ = flying_anchor->next_;
  previous_ = flying_anchor;
  flying_anchor->next_ = this;
  next_->previous_ = this;
}
References v8::internal::ThreadManager::free_anchor_, FREE_LIST, v8::internal::ThreadManager::in_use_anchor_, next_, previous_, and thread_manager_.
Referenced by v8::internal::ThreadManager::EagerlyArchiveThread(), and v8::internal::ThreadManager::RestoreThread().
Next()
ThreadState * v8::internal::ThreadState::Next ()
Definition at line 212 of file v8threads.cc.
                               {
  if (next_ == thread_manager_->in_use_anchor_) return nullptr;
  return next_;
}
References v8::internal::ThreadManager::in_use_anchor_, next_, and thread_manager_.
Referenced by v8::internal::ThreadManager::FirstThreadStateInUse(), v8::internal::ThreadManager::Iterate(), and v8::internal::ThreadManager::IterateArchivedThreads().
set_id()
void v8::internal::ThreadState::set_id (ThreadId id) [inline]
Definition at line 29 of file v8threads.h.
{ id_ = id; }
References id(), and id_.
Referenced by v8::internal::ThreadManager::ArchiveThread(), and v8::internal::ThreadManager::RestoreThread().
Unlink()
void v8::internal::ThreadState::Unlink ()
Definition at line 182 of file v8threads.cc.
                         {
  next_->previous_ = previous_;
  previous_->next_ = next_;
}
References next_, and previous_.
Referenced by v8::internal::ThreadManager::ArchiveThread(), and v8::internal::ThreadManager::RestoreThread().
Friends And Related Function Documentation
ThreadManager
friend class ThreadManager [friend]
Definition at line 48 of file v8threads.h.
Member Data Documentation
data_
char* v8::internal::ThreadState::data_ [private]
Definition at line 42 of file v8threads.h.
Referenced by AllocateSpace(), data(), and ~ThreadState().
id_
ThreadId v8::internal::ThreadState::id_ [private]
Definition at line 41 of file v8threads.h.
Referenced by id(), and set_id().
next_
ThreadState* v8::internal::ThreadState::next_ [private]
Definition at line 43 of file v8threads.h.
Referenced by v8::internal::ThreadManager::DeleteThreadStateList(), v8::internal::ThreadManager::GetFreeThreadState(), LinkInto(), Next(), and Unlink().
previous_
ThreadState* v8::internal::ThreadState::previous_ [private]
Definition at line 44 of file v8threads.h.
Referenced by LinkInto(), and Unlink().
thread_manager_
ThreadManager* v8::internal::ThreadState::thread_manager_ [private]
Definition at line 46 of file v8threads.h.
Referenced by LinkInto(), and Next().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/v8threads.h
/mnt/V8SourceCode/src/execution/v8threads.cc