v8::internal::compiler::CallParameters Class Reference
#include <js-operator.h>
Public Member Functions
CallParameters (size_t arity, CallFrequency const &frequency, FeedbackSource const &feedback, ConvertReceiverMode convert_mode, SpeculationMode speculation_mode, CallFeedbackRelation feedback_relation)
size_t arity () const
int arity_without_implicit_args () const
CallFrequency const & frequency () const
ConvertReceiverMode convert_mode () const
FeedbackSource const & feedback () const
SpeculationMode speculation_mode () const
CallFeedbackRelation feedback_relation () const
bool operator== (CallParameters const &that) const
bool operator!= (CallParameters const &that) const
Static Public Attributes
static constexpr int kExtraCallInputCount = 3
Private Types
using ArityField = base::BitField< size_t, 0, 26 >
using CallFeedbackRelationField = base::BitField< CallFeedbackRelation, 26, 2 >
using SpeculationModeField = base::BitField< SpeculationMode, 28, 2 >
using ConvertReceiverModeField = base::BitField< ConvertReceiverMode, 30, 2 >
Private Attributes
uint32_t const bit_field_
CallFrequency const frequency_
FeedbackSource const feedback_
Friends
size_t hash_value (CallParameters const &p)
Detailed Description
Definition at line 231 of file js-operator.h.
Member Typedef Documentation
ArityField
using v8::internal::compiler::CallParameters::ArityField = base::BitField<size_t, 0, 26> [private]
Definition at line 292 of file js-operator.h.
CallFeedbackRelationField
using v8::internal::compiler::CallParameters::CallFeedbackRelationField = base::BitField<CallFeedbackRelation, 26, 2> [private]
Definition at line 293 of file js-operator.h.
ConvertReceiverModeField
using v8::internal::compiler::CallParameters::ConvertReceiverModeField = base::BitField<ConvertReceiverMode, 30, 2> [private]
Definition at line 295 of file js-operator.h.
SpeculationModeField
using v8::internal::compiler::CallParameters::SpeculationModeField = base::BitField<SpeculationMode, 28, 2> [private]
Definition at line 294 of file js-operator.h.
Constructor & Destructor Documentation
CallParameters()
v8::internal::compiler::CallParameters::CallParameters (size_t arity, CallFrequency const & frequency, FeedbackSource const & feedback, ConvertReceiverMode convert_mode, SpeculationMode speculation_mode, CallFeedbackRelation feedback_relation) [inline]
Definition at line 237 of file js-operator.h.
      : bit_field_(ArityField::encode(arity) |
                   CallFeedbackRelationField::encode(feedback_relation) |
                   SpeculationModeField::encode(speculation_mode) |
                   ConvertReceiverModeField::encode(convert_mode)),
        frequency_(frequency),
        feedback_(feedback) {
    // CallFeedbackRelation is ignored if the feedback slot is invalid.
    DCHECK_IMPLIES(speculation_mode == SpeculationMode::kAllowSpeculation,
                   feedback.IsValid());
    DCHECK_IMPLIES(!feedback.IsValid(),
                   feedback_relation == CallFeedbackRelation::kUnrelated);
    DCHECK_GE(arity, kExtraCallInputCount);
    DCHECK(is_int32(arity));
  }
References arity(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_IMPLIES, feedback(), feedback_relation(), v8::internal::compiler::FeedbackSource::IsValid(), v8::internal::kAllowSpeculation, kExtraCallInputCount, v8::internal::compiler::kUnrelated, and speculation_mode().
Member Function Documentation
arity()
size_t v8::internal::compiler::CallParameters::arity () const [inline]
Definition at line 259 of file js-operator.h.
{ return ArityField::decode(bit_field_); }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by arity_without_implicit_args(), v8::internal::compiler::JSOperatorBuilder::Call(), CallParameters(), v8::internal::compiler::JSOperatorBuilder::CallWithArrayLike(), v8::internal::compiler::JSOperatorBuilder::CallWithSpread(), v8::internal::compiler::operator<<(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), and v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty().
arity_without_implicit_args()
int v8::internal::compiler::CallParameters::arity_without_implicit_args () const [inline]
Definition at line 260 of file js-operator.h.
                                          {
    return static_cast<int>(arity() - kExtraCallInputCount);
  }
References arity(), and kExtraCallInputCount.
Referenced by v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::JSCallReducer::ReduceArrayConstructor(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithSpread(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReduceReflectApply(), v8::internal::compiler::JSCallReducer::ReduceReflectConstruct(), and v8::internal::compiler::JSCallReducer::ReduceReflectGet().
convert_mode()
ConvertReceiverMode v8::internal::compiler::CallParameters::convert_mode () const [inline]
Definition at line 265 of file js-operator.h.
                                           {
    return ConvertReceiverModeField::decode(bit_field_);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::compiler::operator<<(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), and v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty().
feedback()
FeedbackSource const& v8::internal::compiler::CallParameters::feedback () const [inline]
Definition at line 268 of file js-operator.h.
{ return feedback_; }
References feedback_.
Referenced by CallParameters(), v8::internal::compiler::JSCallReducerAssembler::feedback(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::IteratingArrayBuiltinHelper(), v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSCallReducerAssembler::JSCall4(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayConstructor(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceBigIntAsN(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsFinite(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsNaN(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithArrayLike(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithSpread(), v8::internal::compiler::JSCallReducer::ReduceMathClz32(), v8::internal::compiler::JSCallReducer::ReduceMathImul(), v8::internal::compiler::JSCallReducer::ReduceMathMinMax(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), v8::internal::compiler::JSCallReducer::ReduceReflectApply(), v8::internal::compiler::JSCallReducer::ReduceReflectConstruct(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::JSCallReducer::ReduceStringFromCharCode(), v8::internal::compiler::JSCallReducer::ReduceStringFromCodePoint(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeConcat(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIterator(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCodePointAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
feedback_relation()
CallFeedbackRelation v8::internal::compiler::CallParameters::feedback_relation () const [inline]
Definition at line 274 of file js-operator.h.
                                                 {
    return CallFeedbackRelationField::decode(bit_field_);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by CallParameters(), v8::internal::compiler::operator<<(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithArrayLike(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithSpread(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
frequency()
CallFrequency const& v8::internal::compiler::CallParameters::frequency () const [inline]
Definition at line 264 of file js-operator.h.
{ return frequency_; }
References frequency_.
Referenced by v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSCallReducerAssembler::JSCall4(), v8::internal::compiler::operator<<(), v8::internal::compiler::JSInliningHeuristic::Reduce(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithArrayLike(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithSpread(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReduceReflectApply(), and v8::internal::compiler::JSCallReducer::ReduceReflectConstruct().
operator!=()
bool v8::internal::compiler::CallParameters::operator!= (CallParameters const & that) const [inline]
Definition at line 283 of file js-operator.h.
{ return !(*this == that); }
operator==()
bool v8::internal::compiler::CallParameters::operator== (CallParameters const & that) const [inline]
Definition at line 278 of file js-operator.h.
                                                    {
    return this->bit_field_ == that.bit_field_ &&
           this->frequency_ == that.frequency_ &&
           this->feedback_ == that.feedback_;
  }
References bit_field_, feedback_, and frequency_.
speculation_mode()
SpeculationMode v8::internal::compiler::CallParameters::speculation_mode () const [inline]
Definition at line 270 of file js-operator.h.
                                           {
    return SpeculationModeField::decode(bit_field_);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by CallParameters(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::IteratingArrayBuiltinHelper(), v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSCallReducerAssembler::JSCall4(), v8::internal::compiler::operator<<(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayConstructor(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeAt(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceBigIntAsN(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsFinite(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsNaN(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithArrayLike(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithSpread(), v8::internal::compiler::JSCallReducer::ReduceMathBinary(), v8::internal::compiler::JSCallReducer::ReduceMathClz32(), v8::internal::compiler::JSCallReducer::ReduceMathImul(), v8::internal::compiler::JSCallReducer::ReduceMathMinMax(), v8::internal::compiler::JSCallReducer::ReduceMathUnary(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), v8::internal::compiler::JSCallReducer::ReduceReflectApply(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::JSCallReducer::ReduceStringFromCharCode(), v8::internal::compiler::JSCallReducer::ReduceStringFromCodePoint(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeConcat(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIterator(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStartsWith(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCharCodeAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCodePointAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstring(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
Friends And Related Function Documentation
hash_value
size_t hash_value (CallParameters const & p) [friend]
Definition at line 286 of file js-operator.h.
                                                    {
    FeedbackSource::Hash feedback_hash;
    return base::hash_combine(p.bit_field_, p.frequency_,
                              feedback_hash(p.feedback_));
  }
Member Data Documentation
bit_field_
uint32_t const v8::internal::compiler::CallParameters::bit_field_ [private]
Definition at line 297 of file js-operator.h.
Referenced by arity(), convert_mode(), feedback_relation(), operator==(), and speculation_mode().
feedback_
FeedbackSource const v8::internal::compiler::CallParameters::feedback_ [private]
Definition at line 299 of file js-operator.h.
Referenced by feedback(), and operator==().
frequency_
CallFrequency const v8::internal::compiler::CallParameters::frequency_ [private]
Definition at line 298 of file js-operator.h.
Referenced by frequency(), and operator==().
kExtraCallInputCount
constexpr int v8::internal::compiler::CallParameters::kExtraCallInputCount = 3 [static], [constexpr]
Definition at line 235 of file js-operator.h.
Referenced by arity_without_implicit_args(), and CallParameters().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h