v8::internal::IsolateData Class Reference
#include <isolate-data.h>
Classes
struct RawArgument
Public Member Functions
IsolateData (Isolate *isolate, IsolateGroup *group)
IsolateData (const IsolateData &)=delete
IsolateData & operator= (const IsolateData &)=delete
Address isolate_root () const
Address fast_c_call_caller_fp () const
Address fast_c_call_caller_pc () const
Address fast_api_call_target () const
Address cage_base () const
StackGuard * stack_guard ()
int32_t * regexp_static_result_offsets_vector () const
void set_regexp_static_result_offsets_vector (int32_t *value)
Address * builtin_tier0_entry_table ()
Address * builtin_tier0_table ()
RootsTable & roots ()
Address api_callback_thunk_argument () const
Address regexp_exec_vector_argument () const
Tagged< Object > continuation_preserved_embedder_data () const
void set_continuation_preserved_embedder_data (Tagged< Object > data)
const RootsTable & roots () const
ExternalReferenceTable * external_reference_table ()
ThreadLocalTop & thread_local_top ()
ThreadLocalTop const & thread_local_top () const
Address * builtin_entry_table ()
Address * builtin_table ()
wasm::StackMemory * active_stack ()
void set_active_stack (wasm::StackMemory *stack)
template<typename T >
requires (std::is_integral_v< T >||std::is_floating_point_v< T >) T GetRawArgument(uint32_t index) const
bool stack_is_iterable () const
bool is_marking () const
bool contains (Address address) const
Static Public Member Functions
static constexpr int root_slot_offset (RootIndex root_index)
static constexpr int BuiltinEntrySlotOffset (Builtin id)
static constexpr int builtin_slot_offset (int builtin_index)
static constexpr int BuiltinSlotOffset (Builtin id)
static constexpr int jslimit_offset ()
static constexpr int real_jslimit_offset ()
static constexpr int exception_offset ()
static constexpr uint32_t GetRawArgumentCount ()
static constexpr intptr_t GetOffset (IsolateFieldId id)
Static Public Attributes
static constexpr intptr_t kIsolateRootBias = kRootRegisterBias
Private Member Functions
FRIEND_TEST (HeapTest, ExternalLimitDefault)
FRIEND_TEST (HeapTest, ExternalLimitStaysAboveDefaultForExplicitHandling)
Static Private Member Functions
static void AssertPredictableLayout ()
Private Attributes
const Address cage_base_ = kNullAddress
StackGuard stack_guard_
uint8_t is_marking_flag_ = false
uint8_t is_minor_marking_flag_ = false
uint8_t is_shared_space_isolate_flag_ = false
uint8_t uses_shared_heap_flag_ = false
base::Flags< IsolateExecutionModeFlag, uint8_t, std::atomic< uint8_t > > execution_mode_ = {IsolateExecutionModeFlag::kNoFlags}
uint8_t stack_is_iterable_ = 1
uint8_t error_message_param_
V8_NO_UNIQUE_ADDRESS uint8_t tables_alignment_padding_ [kTablesAlignmentPaddingSize]
int32_t * regexp_static_result_offsets_vector_ = nullptr
Address builtin_tier0_entry_table_ [Builtins::kBuiltinTier0Count] = {}
Address builtin_tier0_table_ [Builtins::kBuiltinTier0Count] = {}
LinearAllocationArea new_allocation_info_
LinearAllocationArea old_allocation_info_
Address fast_c_call_alignment_padding_ [kFastCCallAlignmentPaddingCount]
xx xx xx xx xx xx xx xx xx
struct {
 Address fast_c_call_caller_pc_ = kNullAddress
 Address fast_c_call_caller_fp_ = kNullAddress
};
Address fast_api_call_target_ = kNullAddress
size_t long_task_stats_counter_ = 0
ThreadLocalTop thread_local_top_
HandleScopeData handle_scope_data_
void * embedder_data_ [Internals::kNumIsolateDataSlots] = {}
Address api_callback_thunk_argument_ = kNullAddress
Address js_dispatch_table_base_ = kNullAddress
Address regexp_exec_vector_argument_ = kNullAddress
Tagged< Object > continuation_preserved_embedder_data_ = Smi::zero()
RootsTable roots_table_
ExternalReferenceTable external_reference_table_
Address builtin_entry_table_ [Builtins::kBuiltinCount] = {}
Address builtin_table_ [Builtins::kBuiltinCount] = {}
wasm::StackMemory * active_stack_ = nullptr
int32_t date_cache_stamp_ = 0
uint8_t is_date_cache_used_ = false
V8_NO_UNIQUE_ADDRESS uint8_t raw_arguments_padding_ [kRawArgumentsPaddingSize]
struct v8::internal::IsolateData::RawArgument raw_arguments_ [2] = {}
V8_NO_UNIQUE_ADDRESS uint8_t trailing_padding_ [kTrailingPaddingSize]
Friends
class Isolate
class Heap
Detailed Description
Definition at line 242 of file isolate-data.h.
Constructor & Destructor Documentation
IsolateData() [1/2]
v8::internal::IsolateData::IsolateData (Isolate * isolate, IsolateGroup * group) [inline]
Definition at line 244 of file isolate-data.h.
      :
#ifdef V8_COMPRESS_POINTERS
        cage_base_(group->GetPtrComprCageBase()),
#endif
        stack_guard_(isolate)
#ifdef V8_ENABLE_SANDBOX
        ,
        trusted_cage_base_(group->GetTrustedPtrComprCageBase()),
        code_pointer_table_base_address_(
            group->code_pointer_table()->base_address())
#endif
#if V8_ENABLE_LEAPTIERING_BOOL
        ,
        js_dispatch_table_base_(group->js_dispatch_table()->base_address())
#endif
  {
  }
IsolateData() [2/2]
v8::internal::IsolateData::IsolateData (const IsolateData &) [delete]
Member Function Documentation
active_stack()
wasm::StackMemory* v8::internal::IsolateData::active_stack () [inline]
Definition at line 355 of file isolate-data.h.
{ return active_stack_; }
References active_stack_.
Referenced by v8::internal::TickSample::GetStackSample(), v8::internal::wasm::grow_stack(), v8::internal::wasm::load_old_fp(), v8::internal::StackFrameIterator::Reset(), v8::internal::wasm::return_switch(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::shrink_stack(), v8::internal::wasm::switch_from_the_central_stack_for_js(), v8::internal::wasm::switch_stacks(), v8::internal::wasm::switch_to_the_central_stack_for_js(), and v8::internal::Isolate::UnwindAndFindHandler().
api_callback_thunk_argument()
Address v8::internal::IsolateData::api_callback_thunk_argument () const [inline]
Definition at line 335 of file isolate-data.h.
                                              {
    return api_callback_thunk_argument_;
  }
References api_callback_thunk_argument_.
Referenced by v8::internal::InvokeAccessorGetterCallback().
AssertPredictableLayout()
void v8::internal::IsolateData::AssertPredictableLayout () [inline], [static], [private]
Definition at line 609 of file isolate-data.h.
                                          {
  static_assert(std::is_standard_layout_v<StackGuard>);
  static_assert(std::is_standard_layout_v<RootsTable>);
  static_assert(std::is_standard_layout_v<ThreadLocalTop>);
  static_assert(std::is_standard_layout_v<ExternalReferenceTable>);
  static_assert(std::is_standard_layout_v<IsolateData>);
  static_assert(std::is_standard_layout_v<LinearAllocationArea>);
#define V(PureName, Size, Name) \
  static_assert(std::is_standard_layout_v<decltype(IsolateData::Name##_)>); \
  static_assert(offsetof(IsolateData, Name##_) == k##PureName##Offset);
  ISOLATE_DATA_FIELDS(V)
#undef V
  static_assert(sizeof(IsolateData) == IsolateData::kSizeOffset);
}
References ISOLATE_DATA_FIELDS.
builtin_entry_table()
Address* v8::internal::IsolateData::builtin_entry_table () [inline]
Definition at line 353 of file isolate-data.h.
{ return builtin_entry_table_; }
References builtin_entry_table_.
Referenced by v8::internal::Builtins::InitializeIsolateDataTables().
builtin_slot_offset()
static constexpr int v8::internal::IsolateData::builtin_slot_offset (int builtin_index) [inline], [static], [constexpr]
Definition at line 293 of file isolate-data.h.
                                                              {
    return BuiltinSlotOffset(Builtins::FromInt(builtin_index));
  }
References BuiltinSlotOffset(), and v8::internal::Builtins::FromInt().
builtin_table()
Address* v8::internal::IsolateData::builtin_table () [inline]
Definition at line 354 of file isolate-data.h.
{ return builtin_table_; }
References builtin_table_.
Referenced by v8::internal::Builtins::InitializeIsolateDataTables().
builtin_tier0_entry_table()
Address* v8::internal::IsolateData::builtin_tier0_entry_table () [inline]
Definition at line 332 of file isolate-data.h.
{ return builtin_tier0_entry_table_; }
References builtin_tier0_entry_table_.
Referenced by v8::internal::Builtins::InitializeIsolateDataTables().
builtin_tier0_table()
Address* v8::internal::IsolateData::builtin_tier0_table () [inline]
Definition at line 333 of file isolate-data.h.
{ return builtin_tier0_table_; }
References builtin_tier0_table_.
Referenced by v8::internal::Builtins::InitializeIsolateDataTables().
BuiltinEntrySlotOffset()
static constexpr int v8::internal::IsolateData::BuiltinEntrySlotOffset (Builtin id) [inline], [static], [constexpr]
Definition at line 286 of file isolate-data.h.
                                                          {
    DCHECK(Builtins::IsBuiltinId(id));
    return (Builtins::IsTier0(id) ? builtin_tier0_entry_table_offset()
                                  : builtin_entry_table_offset()) +
           Builtins::ToInt(id) * kSystemPointerSize;
  }
References v8::internal::DCHECK(), v8::internal::Builtins::IsBuiltinId(), v8::internal::Builtins::IsTier0(), v8::internal::kSystemPointerSize, and v8::internal::Builtins::ToInt().
Referenced by v8::internal::MacroAssembler::CallForDeoptimization(), and v8::internal::MacroAssembler::EntryFromBuiltinAsOperand().
BuiltinSlotOffset()
static constexpr int v8::internal::IsolateData::BuiltinSlotOffset (Builtin id) [inline], [static], [constexpr]
Definition at line 296 of file isolate-data.h.
                                                     {
    return (Builtins::IsTier0(id) ? builtin_tier0_table_offset()
                                  : builtin_table_offset()) +
           Builtins::ToInt(id) * kSystemPointerSize;
  }
References v8::internal::Builtins::IsTier0(), v8::internal::kSystemPointerSize, and v8::internal::Builtins::ToInt().
Referenced by v8::internal::compiler::WasmGraphBuilder::BuildCallToRuntimeWithContext(), builtin_slot_offset(), v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::PropagateException(), and v8::internal::MacroAssemblerBase::RootRegisterOffsetForBuiltin().
cage_base()
Address v8::internal::IsolateData::cage_base () const [inline]
Definition at line 324 of file isolate-data.h.
{ return cage_base_; }
References cage_base_.
contains()
bool v8::internal::IsolateData::contains (Address address) const [inline]
Definition at line 385 of file isolate-data.h.
                                       {
    static_assert(std::is_unsigned_v<Address>);
    Address start = reinterpret_cast<Address>(this);
    return (address - start) < sizeof(*this);
  }
continuation_preserved_embedder_data()
Tagged<Object> v8::internal::IsolateData::continuation_preserved_embedder_data () const [inline]
Definition at line 341 of file isolate-data.h.
                                                              {
    return continuation_preserved_embedder_data_;
  }
References continuation_preserved_embedder_data_.
Referenced by v8::Isolate::GetContinuationPreservedEmbedderData(), v8::Isolate::GetContinuationPreservedEmbedderDataV2(), and v8::internal::MicrotaskQueue::RunMicrotasks().
exception_offset()
static constexpr int v8::internal::IsolateData::exception_offset () [inline], [static], [constexpr]
Definition at line 319 of file isolate-data.h.
                                          {
    return thread_local_top_offset() + ThreadLocalTop::exception_offset();
  }
References v8::internal::ThreadLocalTop::exception_offset().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
external_reference_table()
ExternalReferenceTable* v8::internal::IsolateData::external_reference_table () [inline]
Definition at line 348 of file isolate-data.h.
                                                     {
    return &external_reference_table_;
  }
References external_reference_table_.
Referenced by v8::internal::Isolate::Init().
fast_api_call_target()
Address v8::internal::IsolateData::fast_api_call_target () const [inline]
Definition at line 317 of file isolate-data.h.
{ return fast_api_call_target_; }
References fast_api_call_target_.
Referenced by v8::internal::TickSample::GetStackSample().
fast_c_call_caller_fp()
Address v8::internal::IsolateData::fast_c_call_caller_fp () const [inline]
Definition at line 315 of file isolate-data.h.
{ return fast_c_call_caller_fp_; }
References fast_c_call_caller_fp_.
Referenced by v8::internal::TickSample::GetStackSample(), v8::internal::Isolate::InFastCCall(), v8::internal::StackFrameIterator::Reset(), and v8::internal::StackFrameIteratorForProfiler::StackFrameIteratorForProfiler().
fast_c_call_caller_pc()
Address v8::internal::IsolateData::fast_c_call_caller_pc () const [inline]
Definition at line 316 of file isolate-data.h.
{ return fast_c_call_caller_pc_; }
References fast_c_call_caller_pc_.
Referenced by v8::internal::StackFrameIterator::Reset(), v8::internal::StackFrameIteratorForProfiler::StackFrameIteratorForProfiler(), and v8::internal::Isolate::UnwindAndFindHandler().
FRIEND_TEST() [1/2]
v8::internal::IsolateData::FRIEND_TEST (HeapTest , ExternalLimitDefault) [private]
FRIEND_TEST() [2/2]
v8::internal::IsolateData::FRIEND_TEST (HeapTest , ExternalLimitStaysAboveDefaultForExplicitHandling) [private]
GetOffset()
static constexpr intptr_t v8::internal::IsolateData::GetOffset (IsolateFieldId id) [inline], [static], [constexpr]
Definition at line 403 of file isolate-data.h.
                                                         {
    switch (id) {
      case IsolateFieldId::kUnknown:
        UNREACHABLE();
      case IsolateFieldId::kIsolateAddress:
        return -kIsolateRootBias;
      case IsolateFieldId::kJsLimitAddress:
        return IsolateData::jslimit_offset();
#define CASE(CamelName, size, name) \
  case IsolateFieldId::k##CamelName: \
    return IsolateData::name##_offset();
        ISOLATE_DATA_FIELDS(CASE)
#undef CASE
      default:
        UNREACHABLE();
    }
  }
References CASE, ISOLATE_DATA_FIELDS, jslimit_offset(), kIsolateRootBias, v8::internal::kUnknown, and v8::internal::UNREACHABLE().
Referenced by v8::internal::ExternalReference::offset_from_root_register().
GetRawArgumentCount()
static constexpr uint32_t v8::internal::IsolateData::GetRawArgumentCount () [inline], [static], [constexpr]
Definition at line 372 of file isolate-data.h.
                                                  {
    return arraysize(raw_arguments_);
  }
References arraysize, and raw_arguments_.
Referenced by requires(), and v8::internal::CodeStubAssembler::StoreRawArgument().
is_marking()
bool v8::internal::IsolateData::is_marking () const [inline]
Definition at line 380 of file isolate-data.h.
{ return is_marking_flag_; }
References is_marking_flag_.
Referenced by v8::internal::WriteBarrier::IndirectPointerMarkingFromCode(), and v8::internal::SemiSpace::~SemiSpace().
isolate_root()
Address v8::internal::IsolateData::isolate_root () const [inline]
Definition at line 269 of file isolate-data.h.
                               {
    return reinterpret_cast<Address>(this) + kIsolateRootBias;
  }
References kIsolateRootBias.
Referenced by v8::internal::anonymous_namespace{execution.cc}::Invoke().
jslimit_offset()
static constexpr int v8::internal::IsolateData::jslimit_offset () [inline], [static], [constexpr]
Definition at line 302 of file isolate-data.h.
                                        {
    return stack_guard_offset() + StackGuard::jslimit_offset();
  }
References v8::internal::StackGuard::jslimit_offset().
Referenced by GetOffset(), v8::internal::MacroAssembler::LoadStackLimit(), and v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::WasmStackCheck().
operator=()
IsolateData& v8::internal::IsolateData::operator= (const IsolateData &) [delete]
real_jslimit_offset()
static constexpr int v8::internal::IsolateData::real_jslimit_offset () [inline], [static], [constexpr]
Definition at line 306 of file isolate-data.h.
                                             {
    return stack_guard_offset() + StackGuard::real_jslimit_offset();
  }
References v8::internal::StackGuard::real_jslimit_offset().
Referenced by v8::internal::wasm::WasmGraphBuilderBase::BuildSetNewStackLimit(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchBackFromCentralStack(), v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStackIfNeeded(), and v8::internal::MacroAssembler::LoadStackLimit().
regexp_exec_vector_argument()
Address v8::internal::IsolateData::regexp_exec_vector_argument () const [inline]
Definition at line 338 of file isolate-data.h.
                                              {
    return regexp_exec_vector_argument_;
  }
References regexp_exec_vector_argument_.
regexp_static_result_offsets_vector()
int32_t* v8::internal::IsolateData::regexp_static_result_offsets_vector () const [inline]
Definition at line 326 of file isolate-data.h.
                                                       {
    return regexp_static_result_offsets_vector_;
  }
References regexp_static_result_offsets_vector_.
requires()
template<typename T >
v8::internal::IsolateData::requires (std::is_integral_v< T >||std::is_floating_point_v< T >) const [inline]
Definition at line 366 of file isolate-data.h.
                                         {
    static_assert(sizeof(T) <= kDoubleSize);
    DCHECK_LT(index, GetRawArgumentCount());
    return *reinterpret_cast<const T*>(&raw_arguments_[index].storage_);
  }
References DCHECK_LT, GetRawArgumentCount(), v8::internal::index, v8::internal::kDoubleSize, raw_arguments_, and v8::internal::IsolateData::RawArgument::storage_.
root_slot_offset()
static constexpr int v8::internal::IsolateData::root_slot_offset (RootIndex root_index) [inline], [static], [constexpr]
Definition at line 282 of file isolate-data.h.
                                                              {
    return roots_table_offset() + RootsTable::offset_of(root_index);
  }
References v8::internal::RootsTable::offset_of().
Referenced by v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchException(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ElemDrop(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadExceptionSymbol(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadNullValue(), v8::internal::compiler::CodeAssembler::LoadRoot(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadRoot(), v8::internal::compiler::turboshaft::LoadRootHelper(), v8::internal::compiler::WasmGCLowering::Null(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RootConstant(), v8::internal::MacroAssemblerBase::RootRegisterOffsetForRootIndex(), v8::internal::compiler::CodeAssembler::StoreRoot(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringFromSingleCharCode(), and v8::internal::CodeStubAssembler::TryMatchRootRange().
roots() [1/2]
RootsTable& v8::internal::IsolateData::roots () [inline]
Definition at line 334 of file isolate-data.h.
{ return roots_table_; }
References roots_table_.
roots() [2/2]
const RootsTable& v8::internal::IsolateData::roots () const [inline]
Definition at line 347 of file isolate-data.h.
{ return roots_table_; }
References roots_table_.
set_active_stack()
void v8::internal::IsolateData::set_active_stack (wasm::StackMemory * stack) [inline]
Definition at line 356 of file isolate-data.h.
{ active_stack_ = stack; }
References active_stack_, and v8::internal::stack.
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::Isolate::UnwindAndFindHandler().
set_continuation_preserved_embedder_data()
void v8::internal::IsolateData::set_continuation_preserved_embedder_data (Tagged< Object > data) [inline]
Definition at line 344 of file isolate-data.h.
                                                                     {
    continuation_preserved_embedder_data_ = data;
  }
References continuation_preserved_embedder_data_.
Referenced by v8::internal::MicrotaskQueue::RunMicrotasks(), v8::Isolate::SetContinuationPreservedEmbedderData(), and v8::Isolate::SetContinuationPreservedEmbedderDataV2().
set_regexp_static_result_offsets_vector()
void v8::internal::IsolateData::set_regexp_static_result_offsets_vector (int32_t * value) [inline]
Definition at line 329 of file isolate-data.h.
                                                               {
    regexp_static_result_offsets_vector_ = value;
  }
References regexp_static_result_offsets_vector_, and v8::internal::value.
Referenced by v8::internal::Isolate::Init().
stack_guard()
StackGuard* v8::internal::IsolateData::stack_guard () [inline]
Definition at line 325 of file isolate-data.h.
{ return &stack_guard_; }
References stack_guard_.
stack_is_iterable()
bool v8::internal::IsolateData::stack_is_iterable () const [inline]
Definition at line 376 of file isolate-data.h.
                                 {
    DCHECK(stack_is_iterable_ == 0 || stack_is_iterable_ == 1);
    return stack_is_iterable_ != 0;
  }
References v8::internal::DCHECK(), and stack_is_iterable_.
Referenced by v8::internal::StackFrameIteratorForProfiler::StackFrameIteratorForProfiler().
thread_local_top() [1/2]
ThreadLocalTop& v8::internal::IsolateData::thread_local_top () [inline]
Definition at line 351 of file isolate-data.h.
{ return thread_local_top_; }
References thread_local_top_.
thread_local_top() [2/2]
ThreadLocalTop const& v8::internal::IsolateData::thread_local_top () const [inline]
Definition at line 352 of file isolate-data.h.
{ return thread_local_top_; }
References thread_local_top_.
Friends And Related Function Documentation
Heap
friend class Heap [friend]
Definition at line 600 of file isolate-data.h.
Isolate
friend class Isolate [friend]
Definition at line 599 of file isolate-data.h.
Member Data Documentation
struct { ... } [private]
active_stack_
wasm::StackMemory* v8::internal::IsolateData::active_stack_ = nullptr [private]
Definition at line 567 of file isolate-data.h.
Referenced by active_stack(), and set_active_stack().
api_callback_thunk_argument_
Address v8::internal::IsolateData::api_callback_thunk_argument_ = kNullAddress [private]
Definition at line 543 of file isolate-data.h.
Referenced by api_callback_thunk_argument(), and v8::internal::Isolate::CheckIsolateLayout().
builtin_entry_table_
Address v8::internal::IsolateData::builtin_entry_table_[Builtins::kBuiltinCount] = {} [private]
Definition at line 562 of file isolate-data.h.
Referenced by builtin_entry_table().
builtin_table_
Address v8::internal::IsolateData::builtin_table_[Builtins::kBuiltinCount] = {} [private]
Definition at line 565 of file isolate-data.h.
Referenced by builtin_table().
builtin_tier0_entry_table_
Address v8::internal::IsolateData::builtin_tier0_entry_table_[Builtins::kBuiltinTier0Count] = {} [private]
Definition at line 486 of file isolate-data.h.
Referenced by builtin_tier0_entry_table(), and v8::internal::Isolate::CheckIsolateLayout().
builtin_tier0_table_
Address v8::internal::IsolateData::builtin_tier0_table_[Builtins::kBuiltinTier0Count] = {} [private]
Definition at line 487 of file isolate-data.h.
Referenced by builtin_tier0_table(), and v8::internal::Isolate::CheckIsolateLayout().
cage_base_
const Address v8::internal::IsolateData::cage_base_ = kNullAddress [private]
Definition at line 439 of file isolate-data.h.
Referenced by cage_base(), and v8::internal::Isolate::CheckIsolateLayout().
continuation_preserved_embedder_data_
Tagged<Object> v8::internal::IsolateData::continuation_preserved_embedder_data_ = Smi::zero() [private]
Definition at line 553 of file isolate-data.h.
Referenced by v8::internal::Isolate::CheckIsolateLayout(), continuation_preserved_embedder_data(), v8::internal::Isolate::Init(), and set_continuation_preserved_embedder_data().
date_cache_stamp_
int32_t v8::internal::IsolateData::date_cache_stamp_ = 0 [private]
Definition at line 571 of file isolate-data.h.
Referenced by v8::internal::Isolate::IncreaseDateCacheStampAndInvalidateProtector().
embedder_data_
void* v8::internal::IsolateData::embedder_data_[Internals::kNumIsolateDataSlots] = {} [private]
Definition at line 522 of file isolate-data.h.
Referenced by v8::internal::Isolate::CheckIsolateLayout().
error_message_param_
uint8_t v8::internal::IsolateData::error_message_param_ [private]
Definition at line 474 of file isolate-data.h.
Referenced by v8::internal::Isolate::CheckIsolateLayout().
execution_mode_
base::Flags<IsolateExecutionModeFlag, uint8_t, std::atomic<uint8_t> > v8::internal::IsolateData::execution_mode_ = {IsolateExecutionModeFlag::kNoFlags} [private]
Definition at line 459 of file isolate-data.h.
external_reference_table_
ExternalReferenceTable v8::internal::IsolateData::external_reference_table_ [private]
Definition at line 556 of file isolate-data.h.
Referenced by external_reference_table().
fast_api_call_target_
Address v8::internal::IsolateData::fast_api_call_target_ = kNullAddress [private]
Definition at line 509 of file isolate-data.h.
Referenced by fast_api_call_target().
fast_c_call_alignment_padding_
Address v8::internal::IsolateData::fast_c_call_alignment_padding_[kFastCCallAlignmentPaddingCount] [private]
Definition at line 493 of file isolate-data.h.
fast_c_call_caller_fp_
Address v8::internal::IsolateData::fast_c_call_caller_fp_ = kNullAddress
Definition at line 505 of file isolate-data.h.
Referenced by v8::internal::Isolate::CheckIsolateLayout(), and fast_c_call_caller_fp().
fast_c_call_caller_pc_
Address v8::internal::IsolateData::fast_c_call_caller_pc_ = kNullAddress
Definition at line 504 of file isolate-data.h.
Referenced by v8::internal::Isolate::CheckIsolateLayout(), and fast_c_call_caller_pc().
handle_scope_data_
HandleScopeData v8::internal::IsolateData::handle_scope_data_ [private]
Definition at line 516 of file isolate-data.h.
Referenced by v8::internal::Isolate::CheckIsolateLayout().
is_date_cache_used_
uint8_t v8::internal::IsolateData::is_date_cache_used_ = false [private]
Definition at line 574 of file isolate-data.h.
is_marking_flag_
uint8_t v8::internal::IsolateData::is_marking_flag_ = false [private]
Definition at line 451 of file isolate-data.h.
Referenced by v8::internal::Isolate::CheckIsolateLayout(), is_marking(), v8::internal::Heap::IsMarkingFlagAddress(), and v8::internal::Heap::SetIsMarkingFlag().
is_minor_marking_flag_
uint8_t v8::internal::IsolateData::is_minor_marking_flag_ = false [private]
Definition at line 452 of file isolate-data.h.
Referenced by v8::internal::Heap::IsMinorMarkingFlagAddress(), and v8::internal::Heap::SetIsMinorMarkingFlag().
is_shared_space_isolate_flag_
uint8_t v8::internal::IsolateData::is_shared_space_isolate_flag_ = false [private]
Definition at line 453 of file isolate-data.h.
Referenced by v8::internal::Isolate::Init().
js_dispatch_table_base_
Address v8::internal::IsolateData::js_dispatch_table_base_ = kNullAddress [private]
Definition at line 545 of file isolate-data.h.
Referenced by v8::internal::Isolate::CheckIsolateLayout().
kIsolateRootBias
constexpr intptr_t v8::internal::IsolateData::kIsolateRootBias = kRootRegisterBias [static], [constexpr]
Definition at line 266 of file isolate-data.h.
Referenced by GetOffset(), isolate_root(), and v8::internal::Isolate::isolate_root_bias().
long_task_stats_counter_
size_t v8::internal::IsolateData::long_task_stats_counter_ = 0 [private]
Definition at line 513 of file isolate-data.h.
Referenced by v8::internal::Isolate::CheckIsolateLayout(), and v8::internal::Isolate::UpdateLongTaskStats().
new_allocation_info_
LinearAllocationArea v8::internal::IsolateData::new_allocation_info_ [private]
Definition at line 489 of file isolate-data.h.
Referenced by v8::internal::Isolate::CheckIsolateLayout(), v8::internal::Isolate::Init(), v8::internal::Heap::NewSpaceAllocationLimitAddress(), and v8::internal::Heap::NewSpaceAllocationTopAddress().
old_allocation_info_
LinearAllocationArea v8::internal::IsolateData::old_allocation_info_ [private]
Definition at line 490 of file isolate-data.h.
Referenced by v8::internal::Isolate::CheckIsolateLayout(), and v8::internal::Isolate::Init().
raw_arguments_
struct v8::internal::IsolateData::RawArgument v8::internal::IsolateData::raw_arguments_[2] = {} [private]
Referenced by GetRawArgumentCount(), and requires().
raw_arguments_padding_
V8_NO_UNIQUE_ADDRESS uint8_t v8::internal::IsolateData::raw_arguments_padding_[kRawArgumentsPaddingSize] [private]
Definition at line 577 of file isolate-data.h.
regexp_exec_vector_argument_
Address v8::internal::IsolateData::regexp_exec_vector_argument_ = kNullAddress [private]
Definition at line 550 of file isolate-data.h.
Referenced by regexp_exec_vector_argument().
regexp_static_result_offsets_vector_
int32_t* v8::internal::IsolateData::regexp_static_result_offsets_vector_ = nullptr [private]
Definition at line 483 of file isolate-data.h.
Referenced by regexp_static_result_offsets_vector(), and set_regexp_static_result_offsets_vector().
roots_table_
RootsTable v8::internal::IsolateData::roots_table_ [private]
Definition at line 555 of file isolate-data.h.
Referenced by v8::internal::Isolate::CheckIsolateLayout(), and roots().
stack_guard_
StackGuard v8::internal::IsolateData::stack_guard_ [private]
Definition at line 443 of file isolate-data.h.
Referenced by v8::internal::Isolate::CheckIsolateLayout(), and stack_guard().
stack_is_iterable_
uint8_t v8::internal::IsolateData::stack_is_iterable_ = 1 [private]
Definition at line 469 of file isolate-data.h.
Referenced by stack_is_iterable().
tables_alignment_padding_
V8_NO_UNIQUE_ADDRESS uint8_t v8::internal::IsolateData::tables_alignment_padding_[kTablesAlignmentPaddingSize] [private]
Definition at line 478 of file isolate-data.h.
thread_local_top_
ThreadLocalTop v8::internal::IsolateData::thread_local_top_ [private]
Definition at line 515 of file isolate-data.h.
Referenced by v8::internal::Isolate::CheckIsolateLayout(), and thread_local_top().
trailing_padding_
V8_NO_UNIQUE_ADDRESS uint8_t v8::internal::IsolateData::trailing_padding_[kTrailingPaddingSize] [private]
Definition at line 595 of file isolate-data.h.
uses_shared_heap_flag_
uint8_t v8::internal::IsolateData::uses_shared_heap_flag_ = false [private]
Definition at line 454 of file isolate-data.h.
Referenced by v8::internal::Isolate::Init().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/execution/isolate-data.h