v8::internal::ProfileDataFromFile Class Reference
#include <profile-data-reader.h>
Public Member Functions
int hash () const
BranchHint GetHint (size_t true_block_id, size_t false_block_id) const
Static Public Member Functions
static const ProfileDataFromFile * TryRead (const char *name)
Protected Attributes
int hash_ = 0
std::map< std::pair< size_t, size_t >, bool > block_hints_by_id
Detailed Description
Definition at line 18 of file profile-data-reader.h.
Member Function Documentation
GetHint()
BranchHint v8::internal::ProfileDataFromFile::GetHint (size_t true_block_id, size_t false_block_id) const [inline]
Definition at line 25 of file profile-data-reader.h.
                                                                        {
    auto it =
        block_hints_by_id.find(std::make_pair(true_block_id, false_block_id));
    if (it != block_hints_by_id.end()) {
      return it->second ? BranchHint::kTrue : BranchHint::kFalse;
    }
    return BranchHint::kNone;
  }
References block_hints_by_id, v8::internal::kFalse, v8::internal::kNone, and v8::internal::kTrue.
Referenced by v8::internal::compiler::turboshaft::ProfileApplicationPhase::Run().
hash()
int v8::internal::ProfileDataFromFile::hash () const [inline]
Definition at line 22 of file profile-data-reader.h.
{ return hash_; }
References hash_.
Referenced by v8::internal::anonymous_namespace{profile-data-reader.cc}::EnsureInitProfileData(), and v8::internal::compiler::anonymous_namespace{pipeline.cc}::ValidateProfileData().
TryRead()
const ProfileDataFromFile * v8::internal::ProfileDataFromFile::TryRead (const char * name) [static]
Definition at line 165 of file profile-data-reader.cc.
                                                                        {
  const auto& data = EnsureInitProfileData();
  auto it = data.find(name);
  return it == data.end() ? nullptr : &it->second;
}
References v8::internal::anonymous_namespace{profile-data-reader.cc}::EnsureInitProfileData(), v8::internal::name, and nullptr.
Referenced by v8::internal::compiler::turboshaft::BuildWithTurboshaftAssemblerImpl(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CompileBytecodeHandler(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CompileCSLinkageCodeStubBuiltin(), and v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CompileJSLinkageCodeStubBuiltin().
Member Data Documentation
block_hints_by_id
std::map<std::pair<size_t, size_t>, bool> v8::internal::ProfileDataFromFile::block_hints_by_id [protected]
Definition at line 52 of file profile-data-reader.h.
Referenced by GetHint().
hash_
int v8::internal::ProfileDataFromFile::hash_ = 0 [protected]
Definition at line 47 of file profile-data-reader.h.
Referenced by hash().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/profile-data-reader.h
/mnt/V8SourceCode/src/builtins/profile-data-reader.cc