v8::internal::PagePool::LargePagePoolImpl Class Reference
Public Member Functions
~LargePagePoolImpl ()
bool Add (std::vector< LargePageMetadata * > &pages, InternalTime time)
LargePageMetadata * Remove (size_t chunk_size)
void ReleaseAll ()
size_t ReleaseUpTo (InternalTime release_time)
void TearDown ()
size_t ComputeTotalSize () const
Private Attributes
base::Mutex mutex_
std::vector< std::pair< InternalTime, LargePageMemory > > pages_
size_t total_size_ = 0
Detailed Description
Definition at line 117 of file page-pool.h.
Constructor & Destructor Documentation
 LargePagePoolImpl()
v8::internal::PagePool::LargePagePoolImpl::~LargePagePoolImpl () [inline]
Definition at line 119 of file page-pool.h.
{ DCHECK(pages_.empty()); }
References v8::internal::DCHECK(), and pages_.
Member Function Documentation
Add()
bool v8::internal::PagePool::LargePagePoolImpl::Add (std::vector< LargePageMetadata * > & pages, InternalTime time)
Definition at line 175 of file page-pool.cc.
                                                         {
  bool added_to_pool = false;
  base::MutexGuard guard(&mutex_);
  DCHECK_EQ(total_size_, ComputeTotalSize());
  const size_t max_total_size = v8_flags.max_large_page_pool_size * MB;
  std::erase_if(pages, [this, &added_to_pool, time,
                        max_total_size](LargePageMetadata* page) {
    if (total_size_ + page->size() > max_total_size) {
      return false;
    }
    total_size_ += page->size();
    pages_.emplace_back(time,
                        LargePageMemory(page, [](LargePageMetadata* metadata) {
                          MemoryAllocator::DeleteMemoryChunk(metadata);
                        }));
    added_to_pool = true;
    return true;
  });
  DCHECK_EQ(total_size_, ComputeTotalSize());
  return added_to_pool;
}
References ComputeTotalSize(), DCHECK_EQ, v8::internal::MemoryAllocator::DeleteMemoryChunk(), v8::base::erase_if(), v8::internal::MB, mutex_, pages_, v8::internal::MemoryChunkMetadata::size(), v8::internal::time, total_size_, and v8::internal::v8_flags.
Referenced by v8::internal::PagePool::AddLarge().
ComputeTotalSize()
size_t v8::internal::PagePool::LargePagePoolImpl::ComputeTotalSize () const
Definition at line 261 of file page-pool.cc.
                                                         {
  size_t result = 0;
  for (auto& entry : pages_) {
    result += entry.second->size();
  }
  return result;
}
References v8::base::internal::result.
Referenced by Add().
ReleaseAll()
void v8::internal::PagePool::LargePagePoolImpl::ReleaseAll ()
Definition at line 229 of file page-pool.cc.
                                           {
  std::vector<std::pair<InternalTime, LargePageMemory>> pages_to_free;
  {
    base::MutexGuard guard(&mutex_);
    pages_to_free = std::move(pages_);
    total_size_ = 0;
  }
  // Entries will be freed automatically here.
}
Referenced by v8::internal::PagePool::ReleaseImmediately(), v8::internal::PagePool::ReleaseLargeImmediately(), and v8::internal::PagePool::ReleaseOnTearDown().
ReleaseUpTo()
size_t v8::internal::PagePool::LargePagePoolImpl::ReleaseUpTo (InternalTime release_time)
Definition at line 241 of file page-pool.cc.
                                                                       {
  std::vector<LargePageMemory> entries_to_free;
  size_t freed = 0;
  {
    base::MutexGuard guard(&mutex_);
    std::erase_if(pages_, [this, &entries_to_free, release_time](auto& entry) {
      if (entry.first <= release_time) {
        total_size_ -= entry.second->size();
        entries_to_free.push_back(std::move(entry.second));
        return true;
      }
      return false;
    });
    DCHECK_EQ(total_size_, ComputeTotalSize());
  }
  // Entries will be freed automatically here.
  return freed;
}
References DCHECK_EQ, and v8::base::erase_if().
Remove()
LargePageMetadata * v8::internal::PagePool::LargePagePoolImpl::Remove (size_t chunk_size)
Definition at line 202 of file page-pool.cc.
                                                                      {
  base::MutexGuard guard(&mutex_);
  auto selected = pages_.end();
  DCHECK_EQ(total_size_, ComputeTotalSize());
  // Best-fit: Select smallest large page large with a size of at least
  // |chunk_size|. In case the page is larger than necessary, the next full GC
  // will trim down its size.
  for (auto it = pages_.begin(); it != pages_.end(); it++) {
    const size_t page_size = it->second->size();
    if (page_size < chunk_size) continue;
    if (selected == pages_.end() || page_size < selected->second->size()) {
      selected = it;
    }
  }
  if (selected == pages_.end()) {
    return nullptr;
  }
  LargePageMetadata* result = selected->second.release();
  total_size_ -= result->size();
  pages_.erase(selected);
  DCHECK_EQ(total_size_, ComputeTotalSize());
  return result;
}
References DCHECK_EQ, and v8::base::internal::result.
Referenced by v8::internal::PagePool::RemoveLarge().
TearDown()
void v8::internal::PagePool::LargePagePoolImpl::TearDown ()
Definition at line 271 of file page-pool.cc.
{ CHECK(pages_.empty()); }
References CHECK.
Referenced by v8::internal::PagePool::TearDown().
Member Data Documentation
mutex_
base::Mutex v8::internal::PagePool::LargePagePoolImpl::mutex_ [private]
Definition at line 130 of file page-pool.h.
Referenced by Add().
pages_
std::vector<std::pair<InternalTime, LargePageMemory> > v8::internal::PagePool::LargePagePoolImpl::pages_ [private]
Definition at line 131 of file page-pool.h.
Referenced by Add(), and ~LargePagePoolImpl().
total_size_
size_t v8::internal::PagePool::LargePagePoolImpl::total_size_ = 0 [private]
Definition at line 132 of file page-pool.h.
Referenced by Add().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/page-pool.h
/mnt/V8SourceCode/src/heap/page-pool.cc