v8::internal::compiler::turboshaft::PipelineData Class Reference
#include <phase.h>
Public Member Functions
PipelineData (ZoneStats *zone_stats, TurboshaftPipelineKind pipeline_kind, Isolate *isolate, OptimizedCompilationInfo *info, const AssemblerOptions &assembler_options, int start_source_position=kNoSourcePosition)
void InitializeBrokerAndDependencies (std::shared_ptr< JSHeapBroker > broker, CompilationDependencies *dependencies)
void InitializeBuiltinComponent (const CallDescriptor *call_descriptor, std::optional< BytecodeHandlerData > bytecode_handler_data={})
void InitializeGraphComponent (SourcePositionTable *source_positions)
void InitializeGraphComponentWithGraphZone (ZoneWithName< kGraphZoneName > graph_zone, ZoneWithNamePointer< SourcePositionTable, kGraphZoneName > source_positions, ZoneWithNamePointer< NodeOriginTable, kGraphZoneName > node_origins)
void ClearGraphComponent ()
void InitializeCodegenComponent (std::shared_ptr< OsrHelper > osr_helper, JumpOptimizationInfo *jump_optimization_info=nullptr)
void ClearCodegenComponent ()
void InitializeCodeGenerator (Linkage *linkage)
void InitializeInstructionComponent (const CallDescriptor *call_descriptor)
void InitializeInstructionComponentWithSequence (InstructionSequence *sequence)
void ClearInstructionComponent ()
void InitializeRegisterComponent (const RegisterConfiguration *config, CallDescriptor *call_descriptor)
void ClearRegisterComponent ()
AccountingAllocator * allocator () const
ZoneStats * zone_stats () const
TurboshaftPipelineKind pipeline_kind () const
Isolate * isolate () const
OptimizedCompilationInfo * info () const
const char * debug_name () const
JSHeapBroker * broker () const
CompilationDependencies * depedencies () const
const AssemblerOptions & assembler_options () const
JumpOptimizationInfo * jump_optimization_info ()
const CallDescriptor * builtin_call_descriptor () const
std::optional< BytecodeHandlerData > & bytecode_handler_data ()
bool has_graph () const
ZoneWithName< kGraphZoneName > & graph_zone ()
turboshaft::Graph & graph () const
GraphComponent::Pointer< SourcePositionTable > source_positions () const
GraphComponent::Pointer< NodeOriginTable > node_origins () const
RegisterAllocationData * register_allocation_data () const
ZoneWithName< kRegisterAllocationZoneName > & register_allocation_zone ()
CodeGenerator * code_generator () const
void set_code (MaybeIndirectHandle< Code > code)
MaybeIndirectHandle< Code > code () const
InstructionSequence * sequence () const
Frame * frame () const
CodeTracer * GetCodeTracer () const
size_t & max_unoptimized_frame_height ()
size_t & max_pushed_argument_count ()
RuntimeCallStats * runtime_call_stats () const
void set_runtime_call_stats (RuntimeCallStats *stats)
ZoneWithName< kCompilationZoneName > & compilation_zone ()
TurbofanPipelineStatistics * pipeline_statistics () const
void set_pipeline_statistics (TurbofanPipelineStatistics *pipeline_statistics)
bool is_wasm () const
bool is_js_to_wasm () const
void InitializeFrameData (CallDescriptor *call_descriptor)
void set_source_position_output (std::string source_position_output)
std::string source_position_output () const
bool graph_has_special_rpo () const
void set_graph_has_special_rpo ()
bool graph_has_lowered_fast_api_calls () const
void set_graph_has_lowered_fast_api_calls ()
Private Types
using BuiltinComponent = detail::BuiltinComponent
using GraphComponent = detail::GraphComponent
using CodegenComponent = detail::CodegenComponent
using InstructionComponent = detail::InstructionComponent
using RegisterComponent = detail::RegisterComponent
Private Attributes
ZoneStats * zone_stats_
ZoneWithName< kCompilationZoneName > compilation_zone_
TurboshaftPipelineKind pipeline_kind_
Isolate *const isolate_ = nullptr
OptimizedCompilationInfo * info_ = nullptr
std::unique_ptr< char[]> debug_name_
std::shared_ptr< JSHeapBroker > broker_
TurbofanPipelineStatistics * pipeline_statistics_ = nullptr
CompilationDependencies * dependencies_ = nullptr
int start_source_position_ = kNoSourcePosition
const AssemblerOptions assembler_options_
MaybeIndirectHandle< Code > code_
std::string source_position_output_
RuntimeCallStats * runtime_call_stats_ = nullptr
std::optional< BuiltinComponent > builtin_component_
std::optional< GraphComponent > graph_component_
std::optional< CodegenComponent > codegen_component_
std::optional< InstructionComponent > instruction_component_
std::optional< RegisterComponent > register_component_
Detailed Description
Definition at line 177 of file phase.h.
Member Typedef Documentation
BuiltinComponent
using v8::internal::compiler::turboshaft::PipelineData::BuiltinComponent = detail::BuiltinComponent [private]
Definition at line 178 of file phase.h.
CodegenComponent
using v8::internal::compiler::turboshaft::PipelineData::CodegenComponent = detail::CodegenComponent [private]
Definition at line 180 of file phase.h.
GraphComponent
using v8::internal::compiler::turboshaft::PipelineData::GraphComponent = detail::GraphComponent [private]
Definition at line 179 of file phase.h.
InstructionComponent
using v8::internal::compiler::turboshaft::PipelineData::InstructionComponent = detail::InstructionComponent [private]
Definition at line 181 of file phase.h.
RegisterComponent
using v8::internal::compiler::turboshaft::PipelineData::RegisterComponent = detail::RegisterComponent [private]
Definition at line 182 of file phase.h.
Constructor & Destructor Documentation
PipelineData()
v8::internal::compiler::turboshaft::PipelineData::PipelineData (ZoneStats * zone_stats, TurboshaftPipelineKind pipeline_kind, Isolate * isolate, OptimizedCompilationInfo * info, const AssemblerOptions & assembler_options, int start_source_position = kNoSourcePosition) [inline], [explicit]
Definition at line 185 of file phase.h.
      : zone_stats_(zone_stats),
        compilation_zone_(zone_stats, kCompilationZoneName),
        pipeline_kind_(pipeline_kind),
        isolate_(isolate),
        info_(info),
        debug_name_(info_ ? info_->GetDebugName() : std::unique_ptr<char[]>{}),
        start_source_position_(start_source_position),
        assembler_options_(assembler_options) {
#if V8_ENABLE_WEBASSEMBLY
    if (info != nullptr) {
      DCHECK_EQ(assembler_options_.is_wasm,
                info->IsWasm() || info->IsWasmBuiltin());
    }
#endif
  }
Member Function Documentation
allocator()
AccountingAllocator * v8::internal::compiler::turboshaft::PipelineData::allocator () const
Definition at line 29 of file phase.cc.
                                                   {
  if (isolate_) return isolate_->allocator();
#ifdef V8_ENABLE_WEBASSEMBLY
  if (auto e = wasm::GetWasmEngine()) {
    return e->allocator();
  }
#endif
  return nullptr;
}
References v8::internal::Isolate::allocator(), v8::internal::wasm::GetWasmEngine(), and isolate_.
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
assembler_options()
const AssemblerOptions& v8::internal::compiler::turboshaft::PipelineData::assembler_options () const [inline]
Definition at line 333 of file phase.h.
                                                    {
    return assembler_options_;
  }
Referenced by v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run().
broker()
JSHeapBroker* v8::internal::compiler::turboshaft::PipelineData::broker () const [inline]
Definition at line 331 of file phase.h.
{ return broker_.get(); }
Referenced by v8::internal::compiler::turboshaft::BuildGraph(), v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting(), v8::internal::compiler::turboshaft::PrintTurboshaftGraph(), v8::internal::compiler::turboshaft::CodeEliminationAndSimplificationPhase::Run(), v8::internal::compiler::turboshaft::CsaEffectsComputationPhase::Run(), v8::internal::compiler::turboshaft::CsaMemoryOptimizationPhase::Run(), v8::internal::compiler::turboshaft::OptimizePhase::Run(), v8::internal::compiler::turboshaft::StoreStoreEliminationPhase::Run(), v8::internal::compiler::turboshaft::TypeAssertionsPhase::Run(), v8::internal::compiler::turboshaft::TypedOptimizationsPhase::Run(), v8::internal::compiler::turboshaft::WasmDeadCodeEliminationPhase::Run(), v8::internal::compiler::turboshaft::WasmGCOptimizePhase::Run(), v8::internal::compiler::turboshaft::WasmInJSInliningPhase::Run(), v8::internal::compiler::turboshaft::WasmLoweringPhase::Run(), v8::internal::compiler::turboshaft::WasmOptimizePhase::Run(), v8::internal::compiler::turboshaft::WasmRevecPhase::Run(), v8::internal::compiler::turboshaft::BuildGraphPhase::Run(), and v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run().
builtin_call_descriptor()
const CallDescriptor* v8::internal::compiler::turboshaft::PipelineData::builtin_call_descriptor () const [inline]
Definition at line 340 of file phase.h.
                                                        {
    DCHECK(builtin_component_.has_value());
    return builtin_component_->call_descriptor;
  }
References v8::internal::DCHECK().
bytecode_handler_data()
std::optional<BytecodeHandlerData>& v8::internal::compiler::turboshaft::PipelineData::bytecode_handler_data () [inline]
Definition at line 344 of file phase.h.
                                                            {
    DCHECK(builtin_component_.has_value());
    return builtin_component_->bytecode_handler_data;
  }
References v8::internal::DCHECK().
ClearCodegenComponent()
void v8::internal::compiler::turboshaft::PipelineData::ClearCodegenComponent () [inline]
Definition at line 265 of file phase.h.
                               {
    DCHECK(codegen_component_.has_value());
    codegen_component_.reset();
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::Pipeline::GenerateCode().
ClearGraphComponent()
void v8::internal::compiler::turboshaft::PipelineData::ClearGraphComponent () [inline]
Definition at line 251 of file phase.h.
                             {
    DCHECK(graph_component_.has_value());
    graph_component_.reset();
  }
References v8::internal::DCHECK().
ClearInstructionComponent()
void v8::internal::compiler::turboshaft::PipelineData::ClearInstructionComponent () [inline]
Definition at line 312 of file phase.h.
                                   {
    DCHECK(instruction_component_.has_value());
    instruction_component_.reset();
  }
References v8::internal::DCHECK().
ClearRegisterComponent()
void v8::internal::compiler::turboshaft::PipelineData::ClearRegisterComponent () [inline]
Definition at line 320 of file phase.h.
                                {
    DCHECK(register_component_.has_value());
    register_component_.reset();
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
code()
MaybeIndirectHandle<Code> v8::internal::compiler::turboshaft::PipelineData::code () const [inline]
Definition at line 376 of file phase.h.
{ return code_; }
code_generator()
CodeGenerator* v8::internal::compiler::turboshaft::PipelineData::code_generator () const [inline]
Definition at line 369 of file phase.h.
                                        {
    return codegen_component_->code_generator.get();
  }
Referenced by v8::internal::compiler::turboshaft::FinalizeCodePhase::Run().
compilation_zone()
ZoneWithName<kCompilationZoneName>& v8::internal::compiler::turboshaft::PipelineData::compilation_zone () [inline]
Definition at line 396 of file phase.h.
                                                         {
    return compilation_zone_;
  }
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState().
debug_name()
const char* v8::internal::compiler::turboshaft::PipelineData::debug_name () const [inline]
Definition at line 330 of file phase.h.
{ return debug_name_.get(); }
depedencies()
CompilationDependencies* v8::internal::compiler::turboshaft::PipelineData::depedencies () const [inline]
Definition at line 332 of file phase.h.
{ return dependencies_; }
frame()
Frame* v8::internal::compiler::turboshaft::PipelineData::frame () const [inline]
Definition at line 380 of file phase.h.
{ return codegen_component_->frame; }
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters(), InitializeRegisterComponent(), and v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run().
GetCodeTracer()
CodeTracer * v8::internal::compiler::turboshaft::PipelineData::GetCodeTracer () const
Definition at line 122 of file phase.cc.
                                              {
#if V8_ENABLE_WEBASSEMBLY
  if (info_->IsWasm() || info_->IsWasmBuiltin()) {
    return wasm::GetWasmEngine()->GetCodeTracer();
  }
#endif // V8_ENABLE_WEBASSEMBLY
  DCHECK_NOT_NULL(isolate_);
  return isolate_->GetCodeTracer();
}
References DCHECK_NOT_NULL, v8::internal::Isolate::GetCodeTracer(), v8::internal::wasm::WasmEngine::GetCodeTracer(), v8::internal::wasm::GetWasmEngine(), info_, and isolate_.
graph()
turboshaft::Graph& v8::internal::compiler::turboshaft::PipelineData::graph () const [inline]
Definition at line 355 of file phase.h.
{ return *graph_component_->graph; }
Referenced by v8::internal::compiler::turboshaft::BuildGraph(), v8::internal::compiler::turboshaft::BuildWithTurboshaftAssemblerImpl(), v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin(), v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting(), v8::internal::compiler::turboshaft::PrintTurboshaftGraph(), v8::internal::compiler::turboshaft::CopyingPhase< Reducers >::Run(), v8::internal::compiler::turboshaft::CsaEffectsComputationPhase::Run(), v8::internal::compiler::turboshaft::DecompressionOptimizationPhase::Run(), v8::internal::compiler::turboshaft::SpecialRPOSchedulingPhase::Run(), v8::internal::compiler::turboshaft::LoopUnrollingPhase::Run(), v8::internal::compiler::turboshaft::WasmRevecPhase::Run(), v8::internal::compiler::turboshaft::WasmSimdPhase::Run(), v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run(), and v8::internal::compiler::turboshaft::ProfileApplicationPhase::Run().
graph_has_lowered_fast_api_calls()
bool v8::internal::compiler::turboshaft::PipelineData::graph_has_lowered_fast_api_calls () const [inline]
Definition at line 498 of file phase.h.
                                                {
    return graph_component_->graph_has_lowered_fast_api_calls;
  }
graph_has_special_rpo()
bool v8::internal::compiler::turboshaft::PipelineData::graph_has_special_rpo () const [inline]
Definition at line 492 of file phase.h.
                                     {
    return graph_component_->graph_has_special_rpo;
  }
Referenced by v8::internal::compiler::turboshaft::SpecialRPOSchedulingPhase::Run().
graph_zone()
ZoneWithName<kGraphZoneName>& v8::internal::compiler::turboshaft::PipelineData::graph_zone () [inline]
Definition at line 354 of file phase.h.
{ return graph_component_->zone; }
Referenced by v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting().
has_graph()
bool v8::internal::compiler::turboshaft::PipelineData::has_graph () const [inline]
Definition at line 349 of file phase.h.
                         {
    DCHECK_IMPLIES(graph_component_.has_value(),
                   graph_component_->graph != nullptr);
    return graph_component_.has_value();
  }
References DCHECK_IMPLIES.
info()
OptimizedCompilationInfo* v8::internal::compiler::turboshaft::PipelineData::info () const [inline]
Definition at line 329 of file phase.h.
{ return info_; }
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters(), v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin(), v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting(), InitializeRegisterComponent(), v8::internal::compiler::turboshaft::PrintTurboshaftGraph(), v8::internal::compiler::turboshaft::CopyingPhase< Reducers >::Run(), v8::internal::compiler::turboshaft::CsaEffectsComputationPhase::Run(), v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run(), and v8::internal::compiler::turboshaft::RunMaglevOptimizations().
InitializeBrokerAndDependencies()
void v8::internal::compiler::turboshaft::PipelineData::InitializeBrokerAndDependencies (std::shared_ptr< JSHeapBroker > broker, CompilationDependencies * dependencies) [inline]
Definition at line 206 of file phase.h.
                                                                              {
    DCHECK_NULL(broker_.get());
    DCHECK_NULL(dependencies_);
    DCHECK_NOT_NULL(broker);
    DCHECK_NOT_NULL(dependencies);
    broker_ = std::move(broker);
    dependencies_ = dependencies;
  }
References broker(), DCHECK_NOT_NULL, and DCHECK_NULL.
Referenced by v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(), and v8::internal::compiler::Pipeline::GenerateCodeForTesting().
InitializeBuiltinComponent()
void v8::internal::compiler::turboshaft::PipelineData::InitializeBuiltinComponent (const CallDescriptor * call_descriptor, std::optional< BytecodeHandlerData > bytecode_handler_data = {}) [inline]
Definition at line 216 of file phase.h.
                                                               {}) {
    DCHECK(!builtin_component_.has_value());
    builtin_component_.emplace(call_descriptor,
                               std::move(bytecode_handler_data));
  }
Referenced by v8::internal::compiler::turboshaft::BuildWithTurboshaftAssemblerImpl().
InitializeCodegenComponent()
void v8::internal::compiler::turboshaft::PipelineData::InitializeCodegenComponent (std::shared_ptr< OsrHelper > osr_helper, JumpOptimizationInfo * jump_optimization_info = nullptr) [inline]
Definition at line 256 of file phase.h.
                                                              {
    DCHECK(!codegen_component_.has_value());
    codegen_component_.emplace(zone_stats_);
    codegen_component_->osr_helper = std::move(osr_helper);
    codegen_component_->jump_optimization_info = jump_optimization_info;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::Pipeline::GenerateCode(), and v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting().
InitializeCodeGenerator()
void v8::internal::compiler::turboshaft::PipelineData::InitializeCodeGenerator (Linkage * linkage) [inline]
Definition at line 270 of file phase.h.
                                                 {
    DCHECK(codegen_component_.has_value());
    CodegenComponent& cg = *codegen_component_;
    DCHECK_NULL(codegen_component_->code_generator);
#if V8_ENABLE_WEBASSEMBLY
    DCHECK_EQ(assembler_options_.is_wasm,
              info()->IsWasm() || info()->IsWasmBuiltin());
#endif
    std::optional<OsrHelper> osr_helper;
    if (cg.osr_helper) osr_helper = *cg.osr_helper;
    cg.code_generator = std::make_unique<CodeGenerator>(
        cg.zone, cg.frame, linkage, sequence(), info_, isolate_,
        std::move(osr_helper), start_source_position_,
        cg.jump_optimization_info, assembler_options_, info_->builtin(),
        cg.max_unoptimized_frame_height, cg.max_pushed_argument_count,
        v8_flags.trace_turbo_stack_accesses ? debug_name_.get() : nullptr);
  }
References v8::internal::compiler::turboshaft::detail::CodegenComponent::code_generator, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, v8::internal::compiler::turboshaft::detail::CodegenComponent::frame, v8::internal::compiler::turboshaft::detail::CodegenComponent::jump_optimization_info, v8::internal::compiler::turboshaft::detail::CodegenComponent::max_pushed_argument_count, v8::internal::compiler::turboshaft::detail::CodegenComponent::max_unoptimized_frame_height, v8::internal::compiler::turboshaft::detail::CodegenComponent::osr_helper, v8::internal::v8_flags, and v8::internal::compiler::turboshaft::detail::ComponentWithZone< ZoneName >::zone.
InitializeFrameData()
void v8::internal::compiler::turboshaft::PipelineData::InitializeFrameData (CallDescriptor * call_descriptor) [inline]
Definition at line 472 of file phase.h.
                                                            {
    DCHECK(codegen_component_.has_value());
    DCHECK_NULL(codegen_component_->frame);
    int fixed_frame_size = 0;
    if (call_descriptor != nullptr) {
      fixed_frame_size =
          call_descriptor->CalculateFixedFrameSize(info()->code_kind());
    }
    codegen_component_->frame = codegen_component_->zone.New<Frame>(
        fixed_frame_size, codegen_component_->zone);
    if (codegen_component_->osr_helper) {
      codegen_component_->osr_helper->SetupFrame(codegen_component_->frame);
    }
  }
References v8::internal::compiler::CallDescriptor::CalculateFixedFrameSize(), v8::internal::DCHECK(), and DCHECK_NULL.
InitializeGraphComponent()
void v8::internal::compiler::turboshaft::PipelineData::InitializeGraphComponent (SourcePositionTable * source_positions) [inline]
Definition at line 224 of file phase.h.
                                                                       {
    DCHECK(!graph_component_.has_value());
    graph_component_.emplace(zone_stats_);
    auto& zone = graph_component_->zone;
    graph_component_->graph = zone.New<Graph>(zone);
    graph_component_->source_positions =
        GraphComponent::Pointer<SourcePositionTable>(source_positions);
    if (info_ && info_->trace_turbo_json()) {
      graph_component_->node_origins = zone.New<NodeOriginTable>(zone);
    }
  }
References v8::internal::DCHECK(), and v8::internal::compiler::turboshaft::Graph::source_positions().
Referenced by v8::internal::compiler::turboshaft::BuildWithTurboshaftAssemblerImpl().
InitializeGraphComponentWithGraphZone()
void v8::internal::compiler::turboshaft::PipelineData::InitializeGraphComponentWithGraphZone (ZoneWithName< kGraphZoneName > graph_zone, ZoneWithNamePointer< SourcePositionTable, kGraphZoneName > source_positions, ZoneWithNamePointer< NodeOriginTable, kGraphZoneName > node_origins) [inline]
Definition at line 236 of file phase.h.
                                                                         {
    DCHECK(!graph_component_.has_value());
    graph_component_.emplace(std::move(graph_zone));
    auto& zone = graph_component_->zone;
    graph_component_->graph = zone.New<Graph>(zone);
    graph_component_->source_positions = source_positions;
    graph_component_->node_origins = node_origins;
    if (!graph_component_->node_origins && info_ && info_->trace_turbo_json()) {
      graph_component_->node_origins = zone.New<NodeOriginTable>(zone);
    }
  }
References v8::internal::DCHECK(), and v8::internal::compiler::turboshaft::Graph::source_positions().
Referenced by v8::internal::compiler::turboshaft::BuildGraphPhase::Run().
InitializeInstructionComponent()
void v8::internal::compiler::turboshaft::PipelineData::InitializeInstructionComponent (const CallDescriptor * call_descriptor) [inline]
Definition at line 288 of file phase.h.
                                                                             {
    DCHECK(!instruction_component_.has_value());
    instruction_component_.emplace(zone_stats());
    auto& zone = instruction_component_->zone;
    InstructionBlocks* instruction_blocks =
        InstructionSequence::InstructionBlocksFor(zone, graph());
    instruction_component_->sequence =
        zone.New<InstructionSequence>(isolate(), zone, instruction_blocks);
    if (call_descriptor && call_descriptor->RequiresFrameAsIncoming()) {
      instruction_component_->sequence->instruction_blocks()[0]
          ->mark_needs_frame();
    } else {
      DCHECK(call_descriptor->CalleeSavedFPRegisters().is_empty());
    }
  }
References v8::internal::compiler::CallDescriptor::CalleeSavedFPRegisters(), v8::internal::DCHECK(), graph(), v8::internal::compiler::InstructionSequence::instruction_blocks(), v8::internal::compiler::InstructionSequence::InstructionBlocksFor(), v8::internal::RegListBase< RegisterT >::is_empty(), and v8::internal::compiler::CallDescriptor::RequiresFrameAsIncoming().
Referenced by v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run().
InitializeInstructionComponentWithSequence()
void v8::internal::compiler::turboshaft::PipelineData::InitializeInstructionComponentWithSequence (InstructionSequence * sequence) [inline]
Definition at line 304 of file phase.h.
                                     {
    DCHECK(!instruction_component_.has_value());
    instruction_component_.emplace(zone_stats());
    instruction_component_->sequence =
        InstructionComponent::Pointer<InstructionSequence>(sequence);
  }
References v8::internal::DCHECK().
InitializeRegisterComponent()
void v8::internal::compiler::turboshaft::PipelineData::InitializeRegisterComponent (const RegisterConfiguration * config, CallDescriptor * call_descriptor)
Definition at line 19 of file phase.cc.
                                                                          {
  DCHECK(!register_component_.has_value());
  register_component_.emplace(zone_stats());
  auto& zone = register_component_->zone;
  register_component_->allocation_data = zone.New<RegisterAllocationData>(
      config, zone, frame(), sequence(), &info()->tick_counter(),
      debug_name_.get());
}
References v8::internal::DCHECK(), debug_name_, frame(), info(), register_component_, sequence(), v8::internal::OptimizedCompilationInfo::tick_counter(), and zone_stats().
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
is_js_to_wasm()
bool v8::internal::compiler::turboshaft::PipelineData::is_js_to_wasm () const [inline]
Definition at line 468 of file phase.h.
                             {
    return pipeline_kind() == TurboshaftPipelineKind::kJSToWasm;
  }
References v8::internal::compiler::turboshaft::kJSToWasm.
is_wasm()
bool v8::internal::compiler::turboshaft::PipelineData::is_wasm () const [inline]
Definition at line 464 of file phase.h.
                       {
    return pipeline_kind() == TurboshaftPipelineKind::kWasm ||
           pipeline_kind() == TurboshaftPipelineKind::kJSToWasm;
  }
References v8::internal::compiler::turboshaft::kJSToWasm, and v8::internal::compiler::turboshaft::kWasm.
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingPhase::Run(), and v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run().
isolate()
Isolate* v8::internal::compiler::turboshaft::PipelineData::isolate () const [inline]
Definition at line 328 of file phase.h.
{ return isolate_; }
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters(), v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin(), v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting(), and v8::internal::compiler::turboshaft::CsaEffectsComputationPhase::Run().
jump_optimization_info()
JumpOptimizationInfo* v8::internal::compiler::turboshaft::PipelineData::jump_optimization_info () [inline]
Definition at line 336 of file phase.h.
                                                 {
    if (!codegen_component_.has_value()) return nullptr;
    return codegen_component_->jump_optimization_info;
  }
max_pushed_argument_count()
size_t& v8::internal::compiler::turboshaft::PipelineData::max_pushed_argument_count () [inline]
Definition at line 385 of file phase.h.
                                      {
    return codegen_component_->max_pushed_argument_count;
  }
Referenced by v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run().
max_unoptimized_frame_height()
size_t& v8::internal::compiler::turboshaft::PipelineData::max_unoptimized_frame_height () [inline]
Definition at line 382 of file phase.h.
                                         {
    return codegen_component_->max_unoptimized_frame_height;
  }
Referenced by v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run().
node_origins()
GraphComponent::Pointer<NodeOriginTable> v8::internal::compiler::turboshaft::PipelineData::node_origins () const [inline]
Definition at line 359 of file phase.h.
                                                              {
    if (!graph_component_.has_value()) return nullptr;
    return graph_component_->node_origins;
  }
Referenced by v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting(), and v8::internal::compiler::turboshaft::PrintTurboshaftGraph().
pipeline_kind()
TurboshaftPipelineKind v8::internal::compiler::turboshaft::PipelineData::pipeline_kind () const [inline]
Definition at line 327 of file phase.h.
{ return pipeline_kind_; }
pipeline_statistics()
TurbofanPipelineStatistics* v8::internal::compiler::turboshaft::PipelineData::pipeline_statistics () const [inline]
Definition at line 400 of file phase.h.
                                                          {
    return pipeline_statistics_;
  }
register_allocation_data()
RegisterAllocationData* v8::internal::compiler::turboshaft::PipelineData::register_allocation_data () const [inline]
Definition at line 363 of file phase.h.
                                                           {
    return register_component_->allocation_data;
  }
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
register_allocation_zone()
ZoneWithName<kRegisterAllocationZoneName>& v8::internal::compiler::turboshaft::PipelineData::register_allocation_zone () [inline]
Definition at line 366 of file phase.h.
                                                                        {
    return register_component_->zone;
  }
runtime_call_stats()
RuntimeCallStats* v8::internal::compiler::turboshaft::PipelineData::runtime_call_stats () const [inline]
Definition at line 388 of file phase.h.
{ return runtime_call_stats_; }
sequence()
InstructionSequence* v8::internal::compiler::turboshaft::PipelineData::sequence () const [inline]
Definition at line 377 of file phase.h.
                                        {
    return instruction_component_->sequence;
  }
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters(), InitializeRegisterComponent(), and v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run().
set_code()
void v8::internal::compiler::turboshaft::PipelineData::set_code (MaybeIndirectHandle< Code > code) [inline]
Definition at line 372 of file phase.h.
                                                {
    DCHECK(code_.is_null());
    code_ = code;
  }
References code, and v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::FinalizeCodePhase::Run().
set_graph_has_lowered_fast_api_calls()
void v8::internal::compiler::turboshaft::PipelineData::set_graph_has_lowered_fast_api_calls () [inline]
Definition at line 501 of file phase.h.
                                              {
    graph_component_->graph_has_lowered_fast_api_calls = true;
  }
set_graph_has_special_rpo()
void v8::internal::compiler::turboshaft::PipelineData::set_graph_has_special_rpo () [inline]
Definition at line 495 of file phase.h.
                                   {
    graph_component_->graph_has_special_rpo = true;
  }
Referenced by v8::internal::compiler::turboshaft::SpecialRPOSchedulingPhase::Run().
set_pipeline_statistics()
void v8::internal::compiler::turboshaft::PipelineData::set_pipeline_statistics (TurbofanPipelineStatistics * pipeline_statistics) [inline]
Definition at line 403 of file phase.h.
                                                       {
    pipeline_statistics_ = pipeline_statistics;
  }
Referenced by v8::internal::compiler::Pipeline::GenerateCodeForTesting(), and v8::internal::compiler::PipelineCompilationJob::PipelineCompilationJob().
set_runtime_call_stats()
void v8::internal::compiler::turboshaft::PipelineData::set_runtime_call_stats (RuntimeCallStats * stats) [inline]
Definition at line 389 of file phase.h.
                                                       {
    runtime_call_stats_ = stats;
  }
Referenced by v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope::PipelineJobScope(), and v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope::~PipelineJobScope().
set_source_position_output()
void v8::internal::compiler::turboshaft::PipelineData::set_source_position_output (std::string source_position_output) [inline]
Definition at line 487 of file phase.h.
                                                                    {
    source_position_output_ = std::move(source_position_output);
  }
source_position_output()
std::string v8::internal::compiler::turboshaft::PipelineData::source_position_output () const [inline]
Definition at line 490 of file phase.h.
{ return source_position_output_; }
source_positions()
GraphComponent::Pointer<SourcePositionTable> v8::internal::compiler::turboshaft::PipelineData::source_positions () const [inline]
Definition at line 356 of file phase.h.
                                                                      {
    return graph_component_->source_positions;
  }
zone_stats()
ZoneStats* v8::internal::compiler::turboshaft::PipelineData::zone_stats () const [inline]
Definition at line 326 of file phase.h.
{ return zone_stats_; }
Referenced by v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin(), v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting(), and InitializeRegisterComponent().
Member Data Documentation
assembler_options_
const AssemblerOptions v8::internal::compiler::turboshaft::PipelineData::assembler_options_ [private]
Definition at line 520 of file phase.h.
broker_
std::shared_ptr<JSHeapBroker> v8::internal::compiler::turboshaft::PipelineData::broker_ [private]
Definition at line 516 of file phase.h.
builtin_component_
std::optional<BuiltinComponent> v8::internal::compiler::turboshaft::PipelineData::builtin_component_ [private]
Definition at line 525 of file phase.h.
code_
MaybeIndirectHandle<Code> v8::internal::compiler::turboshaft::PipelineData::code_ [private]
Definition at line 521 of file phase.h.
codegen_component_
std::optional<CodegenComponent> v8::internal::compiler::turboshaft::PipelineData::codegen_component_ [private]
Definition at line 527 of file phase.h.
compilation_zone_
ZoneWithName<kCompilationZoneName> v8::internal::compiler::turboshaft::PipelineData::compilation_zone_ [private]
Definition at line 510 of file phase.h.
debug_name_
std::unique_ptr<char[]> v8::internal::compiler::turboshaft::PipelineData::debug_name_ [private]
Definition at line 514 of file phase.h.
Referenced by InitializeRegisterComponent().
dependencies_
CompilationDependencies* v8::internal::compiler::turboshaft::PipelineData::dependencies_ = nullptr [private]
Definition at line 518 of file phase.h.
graph_component_
std::optional<GraphComponent> v8::internal::compiler::turboshaft::PipelineData::graph_component_ [private]
Definition at line 526 of file phase.h.
info_
OptimizedCompilationInfo* v8::internal::compiler::turboshaft::PipelineData::info_ = nullptr [private]
Definition at line 513 of file phase.h.
Referenced by GetCodeTracer().
instruction_component_
std::optional<InstructionComponent> v8::internal::compiler::turboshaft::PipelineData::instruction_component_ [private]
Definition at line 528 of file phase.h.
isolate_
Isolate* const v8::internal::compiler::turboshaft::PipelineData::isolate_ = nullptr [private]
Definition at line 512 of file phase.h.
Referenced by allocator(), and GetCodeTracer().
pipeline_kind_
TurboshaftPipelineKind v8::internal::compiler::turboshaft::PipelineData::pipeline_kind_ [private]
Definition at line 511 of file phase.h.
pipeline_statistics_
TurbofanPipelineStatistics* v8::internal::compiler::turboshaft::PipelineData::pipeline_statistics_ = nullptr [private]
Definition at line 517 of file phase.h.
register_component_
std::optional<RegisterComponent> v8::internal::compiler::turboshaft::PipelineData::register_component_ [private]
Definition at line 529 of file phase.h.
Referenced by InitializeRegisterComponent().
runtime_call_stats_
RuntimeCallStats* v8::internal::compiler::turboshaft::PipelineData::runtime_call_stats_ = nullptr [private]
Definition at line 523 of file phase.h.
source_position_output_
std::string v8::internal::compiler::turboshaft::PipelineData::source_position_output_ [private]
Definition at line 522 of file phase.h.
start_source_position_
int v8::internal::compiler::turboshaft::PipelineData::start_source_position_ = kNoSourcePosition [private]
Definition at line 519 of file phase.h.
zone_stats_
ZoneStats* v8::internal::compiler::turboshaft::PipelineData::zone_stats_ [private]
Definition at line 506 of file phase.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/phase.h
/mnt/V8SourceCode/src/compiler/turboshaft/phase.cc