v8::ValueDeserializer Class Reference
Deserializes values from data written with ValueSerializer, or a compatible implementation.
#include <v8-value-serializer.h>
Classes
class Delegate
struct PrivateData
Public Member Functions
ValueDeserializer (Isolate *isolate, const uint8_t *data, size_t size)
ValueDeserializer (Isolate *isolate, const uint8_t *data, size_t size, Delegate *delegate)
~ValueDeserializer ()
V8_WARN_UNUSED_RESULT Maybe< bool > ReadHeader (Local< Context > context)
Reads and validates a header (including the format version).
V8_WARN_UNUSED_RESULT MaybeLocal< Value > ReadValue (Local< Context > context)
Deserializes a JavaScript value from the buffer.
void TransferArrayBuffer (uint32_t transfer_id, Local< ArrayBuffer > array_buffer)
Accepts the array buffer corresponding to the one passed previously to ValueSerializer::TransferArrayBuffer.
void TransferSharedArrayBuffer (uint32_t id, Local< SharedArrayBuffer > shared_array_buffer)
Similar to TransferArrayBuffer, but for SharedArrayBuffer.
void SetSupportsLegacyWireFormat (bool supports_legacy_wire_format)
Must be called before ReadHeader to enable support for reading the legacy wire format (i.e., which predates this being shipped).
uint32_t GetWireFormatVersion () const
Reads the underlying wire format version.
V8_WARN_UNUSED_RESULT bool ReadUint32 (uint32_t *value)
Reads raw data in various common formats to the buffer.
V8_WARN_UNUSED_RESULT bool ReadUint64 (uint64_t *value)
V8_WARN_UNUSED_RESULT bool ReadDouble (double *value)
V8_WARN_UNUSED_RESULT bool ReadRawBytes (size_t length, const void **data)
ValueDeserializer (const ValueDeserializer &)=delete
void operator= (const ValueDeserializer &)=delete
Private Attributes
PrivateData * private_
Detailed Description
Deserializes values from data written with ValueSerializer, or a compatible implementation.
Definition at line 215 of file v8-value-serializer.h.
Constructor & Destructor Documentation
ValueDeserializer() [1/3]
v8::ValueDeserializer::ValueDeserializer (Isolate * isolate, const uint8_t * data, size_t size)
Definition at line 3426 of file api.cc.
    : ValueDeserializer(v8_isolate, data, size, nullptr) {}
ValueDeserializer() [2/3]
v8::ValueDeserializer::ValueDeserializer (Isolate * isolate, const uint8_t * data, size_t size, Delegate * delegate)
Definition at line 3430 of file api.cc.
                                                                      {
  private_ = new PrivateData(reinterpret_cast<i::Isolate*>(v8_isolate),
                             base::Vector<const uint8_t>(data, size), delegate);
}
References private_, and size().
 ValueDeserializer()
v8::ValueDeserializer::~ValueDeserializer ()
Definition at line 3436 of file api.cc.
{ delete private_; }
References private_.
ValueDeserializer() [3/3]
v8::ValueDeserializer::ValueDeserializer (const ValueDeserializer &) [delete]
Member Function Documentation
GetWireFormatVersion()
uint32_t v8::ValueDeserializer::GetWireFormatVersion () const
Reads the underlying wire format version.
Likely mostly to be useful to legacy code reading old wire format versions. Must be called after ReadHeader.
Definition at line 3463 of file api.cc.
                                                       {
  return private_->deserializer.GetWireFormatVersion();
}
References v8::ValueDeserializer::PrivateData::deserializer, v8::internal::ValueDeserializer::GetWireFormatVersion(), and private_.
Referenced by ReadHeader(), and ReadValue().
operator=()
void v8::ValueDeserializer::operator= (const ValueDeserializer &) [delete]
ReadDouble()
bool v8::ValueDeserializer::ReadDouble (double * value)
Definition at line 3497 of file api.cc.
                                                {
  return private_->deserializer.ReadDouble(value);
}
References v8::ValueDeserializer::PrivateData::deserializer, private_, v8::internal::ValueDeserializer::ReadDouble(), and v8::internal::value.
ReadHeader()
Maybe< bool > v8::ValueDeserializer::ReadHeader (Local< Context > context)
Reads and validates a header (including the format version).
May, for example, reject an invalid or unsupported wire format.
Definition at line 3438 of file api.cc.
                                                                {
  auto i_isolate = i::Isolate::Current();
  EnterV8NoScriptScope<> api_scope{i_isolate, context,
                                   RCCId::kAPI_ValueDeserializer_ReadHeader};
  bool read_header = false;
  if (!private_->deserializer.ReadHeader().To(&read_header)) return {};
  DCHECK(read_header);
  static const uint32_t kMinimumNonLegacyVersion = 13;
  if (GetWireFormatVersion() < kMinimumNonLegacyVersion &&
      !private_->supports_legacy_wire_format) {
    i_isolate->Throw(*i_isolate->factory()->NewError(
        i::MessageTemplate::kDataCloneDeserializationVersionError));
    return {};
  }
  return Just(true);
}
References v8::internal::Isolate::Current(), DCHECK, v8::ValueDeserializer::PrivateData::deserializer, v8::internal::Isolate::factory(), GetWireFormatVersion(), v8::Just(), v8::internal::Factory::NewError(), private_, v8::internal::ValueDeserializer::ReadHeader(), v8::ValueDeserializer::PrivateData::supports_legacy_wire_format, and v8::internal::Isolate::Throw().
Referenced by v8::Shell::SerializerDeserialize().
ReadRawBytes()
bool v8::ValueDeserializer::ReadRawBytes (size_t length, const void ** data)
Definition at line 3501 of file api.cc.
                                                                     {
  return private_->deserializer.ReadRawBytes(length, data);
}
References v8::ValueDeserializer::PrivateData::deserializer, v8::internal::length, private_, and v8::internal::ValueDeserializer::ReadRawBytes().
ReadUint32()
bool v8::ValueDeserializer::ReadUint32 (uint32_t * value)
Reads raw data in various common formats to the buffer.
Note that integer types are read in base-128 varint format, not with a binary copy. For use during an override of Delegate::ReadHostObject.
Definition at line 3489 of file api.cc.
                                                  {
  return private_->deserializer.ReadUint32(value);
}
References v8::ValueDeserializer::PrivateData::deserializer, private_, v8::internal::ValueDeserializer::ReadUint32(), and v8::internal::value.
ReadUint64()
bool v8::ValueDeserializer::ReadUint64 (uint64_t * value)
Definition at line 3493 of file api.cc.
                                                  {
  return private_->deserializer.ReadUint64(value);
}
References v8::ValueDeserializer::PrivateData::deserializer, private_, v8::internal::ValueDeserializer::ReadUint64(), and v8::internal::value.
ReadValue()
MaybeLocal< Value > v8::ValueDeserializer::ReadValue (Local< Context > context)
Deserializes a JavaScript value from the buffer.
Definition at line 3467 of file api.cc.
                                                                     {
  PrepareForExecutionScope api_scope{context,
                                     RCCId::kAPI_ValueDeserializer_ReadValue};
  i::MaybeDirectHandle<i::Object> result =
      GetWireFormatVersion() > 0
          ? private_->deserializer.ReadObjectWrapper()
          : private_->deserializer.ReadObjectUsingEntireBufferForLegacyFormat();
  return api_scope.EscapeMaybe(result);
}
References v8::ValueDeserializer::PrivateData::deserializer, GetWireFormatVersion(), private_, v8::internal::ValueDeserializer::ReadObjectUsingEntireBufferForLegacyFormat(), v8::internal::ValueDeserializer::ReadObjectWrapper(), and v8::base::internal::result.
Referenced by v8::Shell::SerializerDeserialize().
SetSupportsLegacyWireFormat()
void v8::ValueDeserializer::SetSupportsLegacyWireFormat (bool supports_legacy_wire_format)
Must be called before ReadHeader to enable support for reading the legacy wire format (i.e., which predates this being shipped).
Don't use this unless you need to read data written by previous versions of blink::ScriptValueSerializer.
Definition at line 3458 of file api.cc.
                                      {
  private_->supports_legacy_wire_format = supports_legacy_wire_format;
}
References private_, and v8::ValueDeserializer::PrivateData::supports_legacy_wire_format.
TransferArrayBuffer()
void v8::ValueDeserializer::TransferArrayBuffer (uint32_t transfer_id, Local< ArrayBuffer > array_buffer)
Accepts the array buffer corresponding to the one passed previously to ValueSerializer::TransferArrayBuffer.
Definition at line 3477 of file api.cc.
                                                                             {
  private_->deserializer.TransferArrayBuffer(
      transfer_id, Utils::OpenDirectHandle(*array_buffer));
}
References v8::ValueDeserializer::PrivateData::deserializer, v8::Utils::OpenDirectHandle(), private_, and v8::internal::ValueDeserializer::TransferArrayBuffer().
TransferSharedArrayBuffer()
void v8::ValueDeserializer::TransferSharedArrayBuffer (uint32_t id, Local< SharedArrayBuffer > shared_array_buffer)
Similar to TransferArrayBuffer, but for SharedArrayBuffer.
The id is not necessarily in the same namespace as unshared ArrayBuffer objects.
Definition at line 3483 of file api.cc.
                                                                        {
  private_->deserializer.TransferArrayBuffer(
      transfer_id, Utils::OpenDirectHandle(*shared_array_buffer));
}
References v8::ValueDeserializer::PrivateData::deserializer, v8::Utils::OpenDirectHandle(), private_, and v8::internal::ValueDeserializer::TransferArrayBuffer().
Member Data Documentation
private_
PrivateData* v8::ValueDeserializer::private_ [private]
Definition at line 311 of file v8-value-serializer.h.
Referenced by GetWireFormatVersion(), ReadDouble(), ReadHeader(), ReadRawBytes(), ReadUint32(), ReadUint64(), ReadValue(), SetSupportsLegacyWireFormat(), TransferArrayBuffer(), TransferSharedArrayBuffer(), ValueDeserializer(), and ~ValueDeserializer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-value-serializer.h
/mnt/V8SourceCode/src/api/api.cc