v8::internal::anonymous_namespace{compilation-cache-table.cc}::EvalCacheKey Class Reference
Public Member Functions
EvalCacheKey (DirectHandle< String > source, DirectHandle< SharedFunctionInfo > shared, LanguageMode language_mode, int position)
bool IsMatch (Tagged< Object > other) override
DirectHandle< Object > AsHandle (Isolate *isolate)
Private Attributes
DirectHandle< String > source_
DirectHandle< SharedFunctionInfo > shared_
LanguageMode language_mode_
int position_
Additional Inherited Members
Detailed Description
Definition at line 95 of file compilation-cache-table.cc.
Constructor & Destructor Documentation
EvalCacheKey()
v8::internal::anonymous_namespace{compilation-cache-table.cc}::EvalCacheKey::EvalCacheKey (DirectHandle< String > source, DirectHandle< SharedFunctionInfo > shared, LanguageMode language_mode, int position) [inline]
Definition at line 107 of file compilation-cache-table.cc.
      : HashTableKey(CompilationCacheShape::EvalHash(*source, *shared,
                                                     language_mode, position)),
        source_(source),
        shared_(shared),
        language_mode_(language_mode),
        position_(position) {}
Member Function Documentation
AsHandle()
DirectHandle<Object> v8::internal::anonymous_namespace{compilation-cache-table.cc}::EvalCacheKey::AsHandle (Isolate * isolate) [inline]
Definition at line 132 of file compilation-cache-table.cc.
                                                  {
    DirectHandle<FixedArray> array = isolate->factory()->NewFixedArray(4);
    array->set(0, *shared_);
    array->set(1, *source_);
    array->set(2, Smi::FromEnum(language_mode_));
    array->set(3, Smi::FromInt(position_));
    array->set_map(isolate, ReadOnlyRoots(isolate).fixed_cow_array_map());
    return array;
  }
References v8::internal::Isolate::factory(), v8::internal::Smi::FromEnum(), v8::internal::Smi::FromInt(), and v8::internal::FactoryBase< Impl >::NewFixedArray().
IsMatch()
bool v8::internal::anonymous_namespace{compilation-cache-table.cc}::EvalCacheKey::IsMatch (Tagged< Object > other) [inline], [override], [virtual]
Implements v8::internal::HashTableKey.
Definition at line 117 of file compilation-cache-table.cc.
                                              {
    DisallowGarbageCollection no_gc;
    Tagged<FixedArray> other_array = Cast<FixedArray>(other);
    DCHECK(IsSharedFunctionInfo(other_array->get(0)));
    if (*shared_ != other_array->get(0)) return false;
    int language_unchecked = Smi::ToInt(other_array->get(2));
    DCHECK(is_valid_language_mode(language_unchecked));
    LanguageMode language_mode = static_cast<LanguageMode>(language_unchecked);
    if (language_mode != language_mode_) return false;
    int position = Smi::ToInt(other_array->get(3));
    if (position != position_) return false;
    Tagged<String> source = Cast<String>(other_array->get(1));
    return source->Equals(*source_);
  }
References v8::internal::DCHECK(), v8::internal::is_valid_language_mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Smi::ToInt().
Member Data Documentation
language_mode_
LanguageMode v8::internal::anonymous_namespace{compilation-cache-table.cc}::EvalCacheKey::language_mode_ [private]
Definition at line 145 of file compilation-cache-table.cc.
position_
int v8::internal::anonymous_namespace{compilation-cache-table.cc}::EvalCacheKey::position_ [private]
Definition at line 146 of file compilation-cache-table.cc.
shared_
DirectHandle<SharedFunctionInfo> v8::internal::anonymous_namespace{compilation-cache-table.cc}::EvalCacheKey::shared_ [private]
Definition at line 144 of file compilation-cache-table.cc.
source_
DirectHandle<String> v8::internal::anonymous_namespace{compilation-cache-table.cc}::EvalCacheKey::source_ [private]
Definition at line 143 of file compilation-cache-table.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/compilation-cache-table.cc