v8::internal::compiler::turboshaft::TypeParser Class Reference
#include <type-parser.h>
Public Member Functions
TypeParser (const std::string_view &str, Zone *zone)
std::optional< Type > Parse ()
Private Member Functions
std::optional< Type > ParseType ()
template<typename T >
std::optional< T > ParseRange ()
template<typename T >
std::optional< T > ParseSet ()
template<typename T >
std::optional< std::vector< T > > ParseSetElements ()
bool ConsumeIf (const std::string_view &prefix)
bool IsNext (const std::string_view &prefix)
template<typename T >
std::optional< T > ReadValue ()
Private Attributes
std::string_view str_
Zone * zone_
size_t pos_ = 0
Detailed Description
Definition at line 20 of file type-parser.h.
Constructor & Destructor Documentation
TypeParser()
v8::internal::compiler::turboshaft::TypeParser::TypeParser (const std::string_view & str, Zone * zone) [inline], [explicit]
Definition at line 22 of file type-parser.h.
      : str_(str), zone_(zone) {}
Member Function Documentation
ConsumeIf()
bool v8::internal::compiler::turboshaft::TypeParser::ConsumeIf (const std::string_view & prefix) [inline], [private]
Definition at line 81 of file type-parser.h.
                                               {
    if (IsNext(prefix)) {
      pos_ += prefix.length();
      return true;
    }
    return false;
  }
References IsNext(), and pos_.
Referenced by ParseRange(), ParseSet(), ParseSetElements(), and ParseType().
IsNext()
bool v8::internal::compiler::turboshaft::TypeParser::IsNext (const std::string_view & prefix) [inline], [private]
Definition at line 89 of file type-parser.h.
                                            {
    // Skip leading whitespace.
    while (pos_ < str_.length() && str_[pos_] == ' ') ++pos_;
    if (pos_ >= str_.length()) return false;
    size_t remaining_length = str_.length() - pos_;
    if (prefix.length() > remaining_length) return false;
    return str_.compare(pos_, prefix.length(), prefix, 0, prefix.length()) == 0;
  }
References pos_, and str_.
Referenced by ConsumeIf(), ParseSetElements(), and ParseType().
Parse()
std::optional<Type> v8::internal::compiler::turboshaft::TypeParser::Parse () [inline]
Definition at line 25 of file type-parser.h.
                            {
    std::optional<Type> type = ParseType();
    // Skip trailing whitespace.
    while (pos_ < str_.length() && str_[pos_] == ' ') ++pos_;
    if (pos_ < str_.length()) return std::nullopt;
    return type;
  }
References ParseType(), pos_, str_, and v8::internal::tracing::type.
ParseRange()
template<typename T >
std::optional<T> v8::internal::compiler::turboshaft::TypeParser::ParseRange () [inline], [private]
Definition at line 37 of file type-parser.h.
                              {
    if (!ConsumeIf("[")) return std::nullopt;
    auto from = ReadValue<typename T::value_type>();
    if (!from) return std::nullopt;
    if (!ConsumeIf(",")) return std::nullopt;
    auto to = ReadValue<typename T::value_type>();
    if (!to) return std::nullopt;
    if (!ConsumeIf("]")) return std::nullopt;
    if constexpr (!std::is_same_v<T, Word32Type> &&
                  !std::is_same_v<T, Word64Type>) {
      CHECK_LE(*from, *to);
    }
    return T::Range(*from, *to, zone_);
  }
References CHECK_LE, ConsumeIf(), v8::internal::compiler::turboshaft::Range(), and zone_.
ParseSet()
template<typename T >
std::optional<T> v8::internal::compiler::turboshaft::TypeParser::ParseSet () [inline], [private]
Definition at line 53 of file type-parser.h.
                            {
    if (!ConsumeIf("{")) return std::nullopt;
    auto elements = ParseSetElements<typename T::value_type>();
    if (!elements) return std::nullopt;
    if (!ConsumeIf("}")) return std::nullopt;
    CHECK_LT(0, elements->size());
    CHECK_LE(elements->size(), T::kMaxSetSize);
    return T::Set(*elements, zone_);
  }
References CHECK_LE, CHECK_LT, ConsumeIf(), and zone_.
ParseSetElements()
template<typename T >
std::optional<std::vector<T> > v8::internal::compiler::turboshaft::TypeParser::ParseSetElements () [inline], [private]
Definition at line 64 of file type-parser.h.
                                               {
    std::vector<T> elements;
    if (IsNext("}")) return elements;
    while (true) {
      auto element_opt = ReadValue<T>();
      if (!element_opt) return std::nullopt;
      elements.push_back(*element_opt);
      if (IsNext("}")) break;
      if (!ConsumeIf(",")) return std::nullopt;
    }
    base::sort(elements);
    elements.erase(std::unique(elements.begin(), elements.end()),
                   elements.end());
    return elements;
  }
References ConsumeIf(), IsNext(), and v8::base::sort().
ParseType()
std::optional< Type > v8::internal::compiler::turboshaft::TypeParser::ParseType () [private]
Definition at line 11 of file type-parser.cc.
                                        {
  if (ConsumeIf("Word32")) {
    if (IsNext("{")) return ParseSet<Word32Type>();
    if (IsNext("[")) return ParseRange<Word32Type>();
    return Word32Type::Any();
  } else if (ConsumeIf("Word64")) {
    if (IsNext("{")) return ParseSet<Word64Type>();
    if (IsNext("[")) return ParseRange<Word64Type>();
    return Word64Type::Any();
  } else if (ConsumeIf("Float32")) {
    // TODO(nicohartmann@): Handle NaN.
    if (IsNext("{")) return ParseSet<Float32Type>();
    if (IsNext("[")) return ParseRange<Float32Type>();
    return Float64Type::Any();
  } else if (ConsumeIf("Float64")) {
    // TODO(nicohartmann@): Handle NaN.
    if (IsNext("{")) return ParseSet<Float64Type>();
    if (IsNext("[")) return ParseRange<Float64Type>();
    return Float64Type::Any();
  } else {
    return std::nullopt;
  }
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::turboshaft::WordType< Bits >::Any(), ConsumeIf(), and IsNext().
Referenced by Parse().
ReadValue()
template<typename T >
std::optional<T> v8::internal::compiler::turboshaft::TypeParser::ReadValue () [inline], [private]
Definition at line 99 of file type-parser.h.
                             {
    T result;
    size_t read = 0;
    // TODO(nicohartmann@): Ideally we want to avoid this string construction
    // (e.g. using std::from_chars).
    std::string s(str_.cbegin() + pos_, str_.cend());
    if constexpr (std::is_same_v<T, uint32_t>) {
      result = static_cast<uint32_t>(std::stoul(s, &read));
    } else if constexpr (std::is_same_v<T, uint64_t>) {
      result = std::stoull(s, &read);
    } else if constexpr (std::is_same_v<T, float>) {
      result = std::stof(s, &read);
    } else if constexpr (std::is_same_v<T, double>) {
      result = std::stod(s, &read);
    }
    if (read == 0) return std::nullopt;
    pos_ += read;
    return result;
  }
References pos_, v8::base::internal::result, str_, and v8::internal::string.
Member Data Documentation
pos_
size_t v8::internal::compiler::turboshaft::TypeParser::pos_ = 0 [private]
Definition at line 121 of file type-parser.h.
Referenced by ConsumeIf(), IsNext(), Parse(), and ReadValue().
str_
std::string_view v8::internal::compiler::turboshaft::TypeParser::str_ [private]
Definition at line 119 of file type-parser.h.
Referenced by IsNext(), Parse(), and ReadValue().
zone_
Zone* v8::internal::compiler::turboshaft::TypeParser::zone_ [private]
Definition at line 120 of file type-parser.h.
Referenced by ParseRange(), and ParseSet().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/type-parser.h
/mnt/V8SourceCode/src/compiler/turboshaft/type-parser.cc