v8::internal::DeoptimizedFrameInfo Class Reference
#include <deoptimized-frame-info.h>
Public Member Functions
DeoptimizedFrameInfo (TranslatedState *state, TranslatedState::iterator frame_it, Isolate *isolate)
Handle< Object > GetContext ()
Handle< Object > GetParameter (int index)
Handle< Object > GetExpression (int index)
Private Member Functions
int parameters_count ()
int expression_count ()
void SetParameter (int index, Handle< Object > obj)
void SetExpression (int index, Handle< Object > obj)
Private Attributes
Handle< Object > context_
std::vector< Handle< Object > > parameters_
std::vector< Handle< Object > > expression_stack_
Friends
class Deoptimizer
Additional Inherited Members
Detailed Description
Definition at line 21 of file deoptimized-frame-info.h.
Constructor & Destructor Documentation
DeoptimizedFrameInfo()
v8::internal::DeoptimizedFrameInfo::DeoptimizedFrameInfo (TranslatedState * state, TranslatedState::iterator frame_it, Isolate * isolate)
Definition at line 26 of file deoptimized-frame-info.cc.
                                                             {
  int parameter_count =
      frame_it->shared_info()
          ->internal_formal_parameter_count_without_receiver();
  TranslatedFrame::iterator stack_it = frame_it->begin();
  // Get the function. Note that this might materialize the function.
  // In case the debugger mutates this value, we should deoptimize
  // the function and remember the value in the materialized value store.
  DCHECK_EQ(parameter_count,
            Cast<JSFunction>(stack_it->GetValue())
                ->shared()
                ->internal_formal_parameter_count_without_receiver());
  stack_it++; // Skip the function.
  stack_it++; // Skip the receiver.
  DCHECK_EQ(TranslatedFrame::kUnoptimizedFunction, frame_it->kind());
  parameters_.resize(static_cast<size_t>(parameter_count));
  for (int i = 0; i < parameter_count; i++) {
    Handle<Object> parameter = GetValueForDebugger(stack_it, isolate);
    SetParameter(i, parameter);
    stack_it++;
  }
  // Get the context.
  context_ = GetValueForDebugger(stack_it, isolate);
  stack_it++;
  // Get the expression stack.
  DCHECK_EQ(TranslatedFrame::kUnoptimizedFunction, frame_it->kind());
  const int stack_height = frame_it->height(); // Accumulator *not* included.
  expression_stack_.resize(static_cast<size_t>(stack_height));
  for (int i = 0; i < stack_height; i++) {
    Handle<Object> expression = GetValueForDebugger(stack_it, isolate);
    SetExpression(i, expression);
    stack_it++;
  }
  DCHECK_EQ(TranslatedFrame::kUnoptimizedFunction, frame_it->kind());
  stack_it++; // Skip the accumulator.
  CHECK(stack_it == frame_it->end());
}
References CHECK, context_, DCHECK_EQ, expression_stack_, v8::internal::TranslatedValue::GetValue(), v8::internal::anonymous_namespace{deoptimized-frame-info.cc}::GetValueForDebugger(), v8::internal::TranslatedFrame::kUnoptimizedFunction, parameters_, SetExpression(), and SetParameter().
Member Function Documentation
expression_count()
int v8::internal::DeoptimizedFrameInfo::expression_count () [inline], [private]
Definition at line 46 of file deoptimized-frame-info.h.
{ return static_cast<int>(expression_stack_.size()); }
References expression_stack_.
Referenced by GetExpression(), and SetExpression().
GetContext()
Handle<Object> v8::internal::DeoptimizedFrameInfo::GetContext () [inline]
Definition at line 27 of file deoptimized-frame-info.h.
{ return context_; }
References context_.
GetExpression()
Handle<Object> v8::internal::DeoptimizedFrameInfo::GetExpression (int index) [inline]
Definition at line 36 of file deoptimized-frame-info.h.
                                          {
    DCHECK(0 <= index && index < expression_count());
    return expression_stack_[index];
  }
References v8::internal::DCHECK(), expression_count(), expression_stack_, and v8::internal::index.
GetParameter()
Handle<Object> v8::internal::DeoptimizedFrameInfo::GetParameter (int index) [inline]
Definition at line 30 of file deoptimized-frame-info.h.
                                         {
    DCHECK(0 <= index && index < parameters_count());
    return parameters_[index];
  }
References v8::internal::DCHECK(), v8::internal::index, parameters_, and parameters_count().
parameters_count()
int v8::internal::DeoptimizedFrameInfo::parameters_count () [inline], [private]
Definition at line 43 of file deoptimized-frame-info.h.
{ return static_cast<int>(parameters_.size()); }
References parameters_.
Referenced by GetParameter(), and SetParameter().
SetExpression()
void v8::internal::DeoptimizedFrameInfo::SetExpression (int index, Handle< Object > obj) [inline], [private]
Definition at line 55 of file deoptimized-frame-info.h.
                                                    {
    DCHECK(0 <= index && index < expression_count());
    expression_stack_[index] = obj;
  }
References v8::internal::DCHECK(), expression_count(), expression_stack_, and v8::internal::index.
Referenced by DeoptimizedFrameInfo().
SetParameter()
void v8::internal::DeoptimizedFrameInfo::SetParameter (int index, Handle< Object > obj) [inline], [private]
Definition at line 49 of file deoptimized-frame-info.h.
                                                   {
    DCHECK(0 <= index && index < parameters_count());
    parameters_[index] = obj;
  }
References v8::internal::DCHECK(), v8::internal::index, parameters_, and parameters_count().
Referenced by DeoptimizedFrameInfo().
Friends And Related Function Documentation
Deoptimizer
friend class Deoptimizer [friend]
Definition at line 64 of file deoptimized-frame-info.h.
Member Data Documentation
context_
Handle<Object> v8::internal::DeoptimizedFrameInfo::context_ [private]
Definition at line 60 of file deoptimized-frame-info.h.
Referenced by DeoptimizedFrameInfo(), and GetContext().
expression_stack_
std::vector<Handle<Object> > v8::internal::DeoptimizedFrameInfo::expression_stack_ [private]
Definition at line 62 of file deoptimized-frame-info.h.
Referenced by DeoptimizedFrameInfo(), expression_count(), GetExpression(), and SetExpression().
parameters_
std::vector<Handle<Object> > v8::internal::DeoptimizedFrameInfo::parameters_ [private]
Definition at line 61 of file deoptimized-frame-info.h.
Referenced by DeoptimizedFrameInfo(), GetParameter(), parameters_count(), and SetParameter().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/deoptimizer/deoptimized-frame-info.h
/mnt/V8SourceCode/src/deoptimizer/deoptimized-frame-info.cc