v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter Class Reference
Public Member Functions
ToStringFormatter (Digits X, int radix, bool sign, char *out, uint32_t chars_available, ProcessorImpl *processor)
void Start ()
int Finish ()
void Classic ()
void BasePowerOfTwo ()
void Fast ()
char * FillWithZeros (RecursionLevel *level, char *prev_cursor, char *out, bool is_last_on_level)
char * ProcessLevel (RecursionLevel *level, Digits chunk, char *out, bool is_last_on_level)
Private Member Functions
char * BasecaseLast (digit_t digit, char *out)
char * BasecaseMiddle (digit_t digit, char *out)
Private Attributes
Digits digits_
int radix_
int max_bits_per_char_ = 0
int chunk_chars_ = 0
bool sign_
char * out_start_
char * out_end_
char * out_
digit_t chunk_divisor_ = 0
ProcessorImpl * processor_
Detailed Description
Definition at line 119 of file tostring.cc.
Constructor & Destructor Documentation
ToStringFormatter()
v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::ToStringFormatter (Digits X, int radix, bool sign, char * out, uint32_t chars_available, ProcessorImpl * processor) [inline]
Definition at line 121 of file tostring.cc.
      : digits_(X),
        radix_(radix),
        sign_(sign),
        out_start_(out),
        out_end_(out + chars_available),
        out_(out_end_),
        processor_(processor) {
    digits_.Normalize();
    DCHECK(chars_available >= ToStringResultLength(digits_, radix_, sign_));
  }
References DCHECK, and v8::bigint::ToStringResultLength().
Member Function Documentation
BasecaseLast()
char* v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::BasecaseLast (digit_t digit, char * out) [inline], [private]
Definition at line 183 of file tostring.cc.
                                               {
    if (radix_ == 10) return BasecaseFixedLast<10>(digit, out);
    do {
      DCHECK(*(out - 1) == kStringZapValue);
      *(--out) = kConversionChars[digit % radix_];
      digit /= radix_;
    } while (digit > 0);
    return out;
  }
References DCHECK, v8::bigint::anonymous_namespace{tostring.cc}::kConversionChars, and v8::bigint::kStringZapValue.
BasecaseMiddle()
char* v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::BasecaseMiddle (digit_t digit, char * out) [inline], [private]
Definition at line 195 of file tostring.cc.
                                                 {
    for (int i = 0; i < chunk_chars_; i++) {
      DCHECK(*(out - 1) == kStringZapValue);
      *(--out) = kConversionChars[digit % radix_];
      digit /= radix_;
    }
    DCHECK(digit == 0);
    return out;
  }
References DCHECK, v8::bigint::anonymous_namespace{tostring.cc}::kConversionChars, and v8::bigint::kStringZapValue.
BasePowerOfTwo()
void v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::BasePowerOfTwo ()
Definition at line 242 of file tostring.cc.
                                       {
  const int bits_per_char = CountTrailingZeros(radix_);
  const int char_mask = radix_ - 1;
  digit_t digit = 0;
  // Keeps track of how many unprocessed bits there are in {digit}.
  int available_bits = 0;
  for (int i = 0; i < digits_.len() - 1; i++) {
    digit_t new_digit = digits_[i];
    // Take any leftover bits from the last iteration into account.
    int current = (digit | (new_digit << available_bits)) & char_mask;
    *(--out_) = kConversionChars[current];
    int consumed_bits = bits_per_char - available_bits;
    digit = new_digit >> consumed_bits;
    available_bits = kDigitBits - consumed_bits;
    while (available_bits >= bits_per_char) {
      *(--out_) = kConversionChars[digit & char_mask];
      digit >>= bits_per_char;
      available_bits -= bits_per_char;
    }
  }
  // Take any leftover bits from the last iteration into account.
  digit_t msd = digits_.msd();
  int current = (digit | (msd << available_bits)) & char_mask;
  *(--out_) = kConversionChars[current];
  digit = msd >> (bits_per_char - available_bits);
  while (digit != 0) {
    *(--out_) = kConversionChars[digit & char_mask];
    digit >>= bits_per_char;
  }
}
References v8::bigint::CountTrailingZeros(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::anonymous_namespace{tostring.cc}::kConversionChars, and v8::bigint::kDigitBits.
Classic()
void v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::Classic () [inline]
Definition at line 137 of file tostring.cc.
                 {
    if (digits_.len() == 0) {
      *(--out_) = '0';
      return;
    }
    if (digits_.len() == 1) {
      out_ = BasecaseLast(digits_[0], out_);
      return;
    }
    // {rest} holds the part of the BigInt that we haven't looked at yet.
    // Not to be confused with "remainder"!
    ScratchDigits rest(digits_.len());
    // In the first round, divide the input, allocating a new BigInt for
    // the result == rest; from then on divide the rest in-place.
    Digits dividend = digits_;
    do {
      if (radix_ == 10) {
        // Faster but costs binary size, so we optimize the most common case.
        out_ = DivideByMagic<10>(rest, dividend, out_);
        MAYBE_INTERRUPT(processor_->AddWorkEstimate(rest.len() * 2));
      } else {
        digit_t chunk;
        processor_->DivideSingle(rest, &chunk, dividend, chunk_divisor_);
        out_ = BasecaseMiddle(chunk, out_);
        // Assume that a division is about ten times as expensive as a
        // multiplication.
        MAYBE_INTERRUPT(processor_->AddWorkEstimate(rest.len() * 10));
      }
      MAYBE_INTERRUPT(if (processor_->should_terminate()) return);
      rest.Normalize();
      dividend = rest;
    } while (rest.len() > 1);
    out_ = BasecaseLast(rest[0], out_);
  }
References v8::bigint::Digits::len(), MAYBE_INTERRUPT, and v8::bigint::Digits::Normalize().
Fast()
void v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::Fast ()
FillWithZeros()
char* v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::FillWithZeros (RecursionLevel * level, char * prev_cursor, char * out, bool is_last_on_level)
Finish()
int v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::Finish ()
Definition at line 228 of file tostring.cc.
                              {
  DCHECK(out_ >= out_start_);
  DCHECK(out_ < out_end_); // At least one character was written.
  while (out_ < out_end_ && *out_ == '0') out_++;
  if (sign_) *(--out_) = '-';
  int excess = 0;
  if (out_ > out_start_) {
    size_t actual_length = out_end_ - out_;
    excess = static_cast<int>(out_ - out_start_);
    std::memmove(out_start_, out_, actual_length);
  }
  return excess;
}
References DCHECK.
ProcessLevel()
char* v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::ProcessLevel (RecursionLevel * level, Digits chunk, char * out, bool is_last_on_level)
Start()
void v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::Start ()
Definition at line 220 of file tostring.cc.
                              {
  max_bits_per_char_ = kMaxBitsPerChar[radix_];
  chunk_chars_ = kDigitBits * kBitsPerCharTableMultiplier / max_bits_per_char_;
  chunk_divisor_ = digit_pow(radix_, chunk_chars_);
  // By construction of chunk_chars_, there can't have been overflow.
  DCHECK(chunk_divisor_ != 0);
}
References DCHECK, v8::bigint::anonymous_namespace{tostring.cc}::digit_pow(), v8::bigint::anonymous_namespace{tostring.cc}::kBitsPerCharTableMultiplier, v8::bigint::kDigitBits, and v8::bigint::anonymous_namespace{tostring.cc}::kMaxBitsPerChar.
Member Data Documentation
chunk_chars_
int v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::chunk_chars_ = 0 [private]
Definition at line 208 of file tostring.cc.
chunk_divisor_
digit_t v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::chunk_divisor_ = 0 [private]
Definition at line 213 of file tostring.cc.
digits_
Digits v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::digits_ [private]
Definition at line 205 of file tostring.cc.
max_bits_per_char_
int v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::max_bits_per_char_ = 0 [private]
Definition at line 207 of file tostring.cc.
out_
char* v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::out_ [private]
Definition at line 212 of file tostring.cc.
out_end_
char* v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::out_end_ [private]
Definition at line 211 of file tostring.cc.
out_start_
char* v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::out_start_ [private]
Definition at line 210 of file tostring.cc.
processor_
ProcessorImpl* v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::processor_ [private]
Definition at line 214 of file tostring.cc.
radix_
int v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::radix_ [private]
Definition at line 206 of file tostring.cc.
sign_
bool v8::bigint::anonymous_namespace{tostring.cc}::ToStringFormatter::sign_ [private]
Definition at line 209 of file tostring.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/bigint/tostring.cc