v8::internal::maglev::InlinedAllocation Class Reference
#include <maglev-ir.h>
Public Types
using List = base::ThreadedList< InlinedAllocation >
Public Member Functions
InlinedAllocation (uint64_t bitfield, VirtualObject *object)
Input & allocation_block_input ()
AllocationBlock * allocation_block ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
void VerifyInputs (MaglevGraphLabeller *graph_labeller) const
size_t size () const
VirtualObject * object () const
int offset () const
void set_offset (int offset)
int non_escaping_use_count () const
void RemoveNonEscapingUses (int n=1)
void AddNonEscapingUses (int n=1)
bool IsEscaping () const
void ForceEscaping ()
void SetElided ()
void SetEscaped ()
bool HasBeenElided () const
bool HasEscaped () const
bool HasBeenAnalysed () const
void UpdateObject (VirtualObject *object)
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::NotIdempotent()
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = FixedInputValueNodeT< 1, InlinedAllocation >
Private Member Functions
InlinedAllocation ** next ()
Private Attributes
VirtualObject * object_
EscapeAnalysisResult escape_analysis_result_
int non_escaping_use_count_ = 0
int offset_ = -1
InlinedAllocation * next_ = nullptr
friend List
Additional Inherited Members
Detailed Description
Definition at line 6264 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::InlinedAllocation::Base = FixedInputValueNodeT<1, InlinedAllocation> [private]
Definition at line 6265 of file maglev-ir.h.
List
using v8::internal::maglev::InlinedAllocation::List = base::ThreadedList<InlinedAllocation>
Definition at line 6268 of file maglev-ir.h.
Constructor & Destructor Documentation
InlinedAllocation()
v8::internal::maglev::InlinedAllocation::InlinedAllocation (uint64_t bitfield, VirtualObject * object) [inline], [explicit]
Definition at line 6270 of file maglev-ir.h.
      : Base(bitfield),
        object_(object),
        escape_analysis_result_(EscapeAnalysisResult::kUnknown) {}
References v8::internal::kUnknown.
Member Function Documentation
AddNonEscapingUses()
void v8::internal::maglev::InlinedAllocation::AddNonEscapingUses (int n = 1) [inline]
Definition at line 6303 of file maglev-ir.h.
                                     {
    DCHECK(!HasBeenAnalysed());
    non_escaping_use_count_ += n;
  }
References v8::internal::DCHECK(), HasBeenAnalysed(), and non_escaping_use_count_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddNonEscapingUses().
allocation_block()
AllocationBlock * v8::internal::maglev::InlinedAllocation::allocation_block ()
Definition at line 1150 of file maglev-ir.cc.
                                                     {
  return allocation_block_input().node()->Cast<AllocationBlock>();
}
References allocation_block_input(), v8::internal::maglev::NodeBase::Cast(), and v8::internal::maglev::Input::node().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
allocation_block_input()
Input& v8::internal::maglev::InlinedAllocation::allocation_block_input () [inline]
Definition at line 6275 of file maglev-ir.h.
{ return input(0); }
Referenced by allocation_block(), GenerateCode(), and SetValueLocationConstraints().
ForceEscaping()
void v8::internal::maglev::InlinedAllocation::ForceEscaping () [inline]
Definition at line 6311 of file maglev-ir.h.
                       {
    DCHECK(!HasBeenAnalysed());
    non_escaping_use_count_ = 0;
  }
References v8::internal::DCHECK(), HasBeenAnalysed(), and non_escaping_use_count_.
Referenced by v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObject().
GenerateCode()
void v8::internal::maglev::InlinedAllocation::GenerateCode (MaglevAssembler * masm, const ProcessingState & state)
Definition at line 132 of file maglev-ir-arm.cc.
                                                                   {
  if (offset() != 0) {
    __ add(ToRegister(result()), ToRegister(allocation_block_input()),
           Operand(offset()));
  }
}
References __, allocation_block_input(), offset(), v8::base::internal::result, and v8::internal::maglev::ToRegister().
HasBeenAnalysed()
bool v8::internal::maglev::InlinedAllocation::HasBeenAnalysed () const [inline]
Definition at line 6334 of file maglev-ir.h.
                               {
    return escape_analysis_result_ != EscapeAnalysisResult::kUnknown;
  }
References escape_analysis_result_, and v8::internal::maglev::kUnknown.
Referenced by AddNonEscapingUses(), v8::internal::maglev::AnyUseMarkingProcessor::EscapeAllocation(), ForceEscaping(), HasBeenElided(), HasEscaped(), IsEscaping(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
HasBeenElided()
bool v8::internal::maglev::InlinedAllocation::HasBeenElided () const [inline]
Definition at line 6325 of file maglev-ir.h.
                             {
    DCHECK(HasBeenAnalysed());
    DCHECK_GE(use_count_, non_escaping_use_count_);
    return escape_analysis_result_ == EscapeAnalysisResult::kElided;
  }
References v8::internal::DCHECK(), DCHECK_GE, escape_analysis_result_, HasBeenAnalysed(), v8::internal::maglev::kElided, and non_escaping_use_count_.
Referenced by v8::internal::maglev::AnyUseMarkingProcessor::DropUseOfValueInStoresToCapturedAllocations().
HasEscaped()
bool v8::internal::maglev::InlinedAllocation::HasEscaped () const [inline]
Definition at line 6330 of file maglev-ir.h.
                          {
    DCHECK(HasBeenAnalysed());
    return escape_analysis_result_ == EscapeAnalysisResult::kEscaped;
  }
References v8::internal::DCHECK(), escape_analysis_result_, HasBeenAnalysed(), and v8::internal::maglev::kEscaped.
Referenced by v8::internal::maglev::AnyUseMarkingProcessor::EscapeAllocation(), v8::internal::maglev::DeadNodeSweepingProcessor::Process(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
IsEscaping()
bool v8::internal::maglev::InlinedAllocation::IsEscaping () const [inline]
Definition at line 6307 of file maglev-ir.h.
                          {
    DCHECK(!HasBeenAnalysed());
    return use_count_ > non_escaping_use_count_;
  }
References v8::internal::DCHECK(), HasBeenAnalysed(), and non_escaping_use_count_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::CanTrackObjectChanges(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsEscaping(), and v8::internal::maglev::MaglevGraphBuilder::TryGetNonEscapingArgumentsObject().
next()
InlinedAllocation** v8::internal::maglev::InlinedAllocation::next () [inline], [private]
Definition at line 6364 of file maglev-ir.h.
{ return &next_; }
References next_.
non_escaping_use_count()
int v8::internal::maglev::InlinedAllocation::non_escaping_use_count () const [inline]
Definition at line 6298 of file maglev-ir.h.
{ return non_escaping_use_count_; }
References non_escaping_use_count_.
object()
VirtualObject* v8::internal::maglev::InlinedAllocation::object () const [inline]
Definition at line 6290 of file maglev-ir.h.
{ return object_; }
References object_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetModifiableObjectFromAllocation(), v8::internal::maglev::MaglevGraphBuilder::GetObjectFromAllocation(), PrintParams(), v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject(), v8::internal::maglev::MaglevGraphBuilder::StringLengthStaticLowerBound(), v8::internal::maglev::MaglevGraphBuilder::TryGetNonEscapingArgumentsObject(), and UpdateObject().
offset()
int v8::internal::maglev::InlinedAllocation::offset () const [inline]
Definition at line 6292 of file maglev-ir.h.
                     {
    DCHECK_NE(offset_, -1);
    return offset_;
  }
References DCHECK_NE, and offset_.
Referenced by GenerateCode(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), set_offset(), and SetValueLocationConstraints().
PrintParams()
void v8::internal::maglev::InlinedAllocation::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7993 of file maglev-ir.cc.
                                                                               {
  os << "(" << object()->type();
  if (object()->has_static_map()) {
    os << " " << *object()->map().object();
  }
  os << ")";
}
References v8::internal::maglev::VirtualObject::map(), v8::internal::compiler::MapRef::object(), object(), and v8::internal::maglev::VirtualObject::type().
RemoveNonEscapingUses()
void v8::internal::maglev::InlinedAllocation::RemoveNonEscapingUses (int n = 1) [inline]
Definition at line 6300 of file maglev-ir.h.
                                        {
    non_escaping_use_count_ = std::max(non_escaping_use_count_ - n, 0);
  }
References non_escaping_use_count_.
set_offset()
void v8::internal::maglev::InlinedAllocation::set_offset (int offset) [inline]
Definition at line 6296 of file maglev-ir.h.
{ offset_ = offset; }
References offset(), and offset_.
SetElided()
void v8::internal::maglev::InlinedAllocation::SetElided () [inline]
Definition at line 6316 of file maglev-ir.h.
                   {
    DCHECK_EQ(escape_analysis_result_, EscapeAnalysisResult::kUnknown);
    escape_analysis_result_ = EscapeAnalysisResult::kElided;
  }
References DCHECK_EQ, escape_analysis_result_, v8::internal::maglev::kElided, and v8::internal::maglev::kUnknown.
SetEscaped()
void v8::internal::maglev::InlinedAllocation::SetEscaped () [inline]
Definition at line 6320 of file maglev-ir.h.
                    {
    // We allow transitions from elided to escaped.
    DCHECK_NE(escape_analysis_result_, EscapeAnalysisResult::kEscaped);
    escape_analysis_result_ = EscapeAnalysisResult::kEscaped;
  }
References DCHECK_NE, escape_analysis_result_, and v8::internal::maglev::kEscaped.
Referenced by v8::internal::maglev::AnyUseMarkingProcessor::EscapeAllocation().
SetValueLocationConstraints()
void v8::internal::maglev::InlinedAllocation::SetValueLocationConstraints ()
Definition at line 123 of file maglev-ir-arm.cc.
                                                    {
  UseRegister(allocation_block_input());
  if (offset() == 0) {
    DefineSameAsFirst(this);
  } else {
    DefineAsRegister(this);
  }
}
References allocation_block_input(), v8::internal::maglev::DefineAsRegister(), v8::internal::maglev::DefineSameAsFirst(), offset(), and v8::internal::maglev::UseRegister().
size()
size_t v8::internal::maglev::InlinedAllocation::size () const [inline]
Definition at line 6288 of file maglev-ir.h.
{ return object_->size(); }
References object_, and v8::internal::maglev::VirtualObject::size().
Referenced by v8::internal::maglev::AllocationBlock::Add().
UpdateObject()
void v8::internal::maglev::InlinedAllocation::UpdateObject (VirtualObject * object) [inline]
Definition at line 6338 of file maglev-ir.h.
                                           {
    DCHECK_EQ(this, object->allocation());
    object_ = object;
  }
References v8::internal::maglev::VirtualObject::allocation(), DCHECK_EQ, object(), and object_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::DeepCopyVirtualObject(), and v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObject().
VerifyInputs()
void v8::internal::maglev::InlinedAllocation::VerifyInputs (MaglevGraphLabeller * graph_labeller) const
Definition at line 1143 of file maglev-ir.cc.
                                               {
  Base::VerifyInputs(graph_labeller);
  CheckValueInputIs(this, 0, Opcode::kAllocationBlock, graph_labeller);
  CHECK_LE(object()->type(), VirtualObject::Type::kLast);
}
References CHECK_LE, v8::internal::maglev::CheckValueInputIs(), v8::internal::tracing::type, and v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::VerifyInputs().
Member Data Documentation
escape_analysis_result_
EscapeAnalysisResult v8::internal::maglev::InlinedAllocation::escape_analysis_result_ [private]
Definition at line 6355 of file maglev-ir.h.
Referenced by HasBeenAnalysed(), HasBeenElided(), HasEscaped(), SetElided(), and SetEscaped().
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::InlinedAllocation::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 6280 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::InlinedAllocation::kProperties = OpProperties::NotIdempotent() [static], [constexpr]
Definition at line 6278 of file maglev-ir.h.
List
friend v8::internal::maglev::InlinedAllocation::List [private]
Definition at line 6366 of file maglev-ir.h.
next_
InlinedAllocation* v8::internal::maglev::InlinedAllocation::next_ = nullptr [private]
Definition at line 6363 of file maglev-ir.h.
Referenced by next().
non_escaping_use_count_
int v8::internal::maglev::InlinedAllocation::non_escaping_use_count_ = 0 [private]
Definition at line 6356 of file maglev-ir.h.
Referenced by AddNonEscapingUses(), ForceEscaping(), HasBeenElided(), IsEscaping(), non_escaping_use_count(), and RemoveNonEscapingUses().
object_
VirtualObject* v8::internal::maglev::InlinedAllocation::object_ [private]
Definition at line 6354 of file maglev-ir.h.
Referenced by object(), size(), and UpdateObject().
offset_
int v8::internal::maglev::InlinedAllocation::offset_ = -1 [private]
Definition at line 6357 of file maglev-ir.h.
Referenced by offset(), and set_offset().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/arm/maglev-ir-arm.cc
/mnt/V8SourceCode/src/maglev/arm64/maglev-ir-arm64.cc
/mnt/V8SourceCode/src/maglev/maglev-ir.cc
/mnt/V8SourceCode/src/maglev/riscv/maglev-ir-riscv.cc
/mnt/V8SourceCode/src/maglev/s390/maglev-ir-s390.cc
/mnt/V8SourceCode/src/maglev/x64/maglev-ir-x64.cc