v8::internal::HandleBase Class Reference
#include <handles.h>
Public Member Functions
bool is_identical_to (const HandleBase &that) const
template<typename T >
bool is_identical_to (const DirectHandle< T > &that) const
bool is_null () const
Address address () const
Address * location () const
ValueHelper::InternalRepresentationType repr () const
Protected Member Functions
HandleBase (Address *location)
HandleBase (Address object, Isolate *isolate)
HandleBase (Address object, LocalIsolate *isolate)
HandleBase (Address object, LocalHeap *local_heap)
bool IsDereferenceAllowed () const
Protected Attributes
Address * location_
Detailed Description
Definition at line 57 of file handles.h.
Constructor & Destructor Documentation
HandleBase() [1/4]
v8::internal::HandleBase::HandleBase (Address * location) [inline], [explicit], [protected]
Definition at line 120 of file handles.h.
: location_(location) {}
HandleBase() [2/4]
v8::internal::HandleBase::HandleBase (Address object, Isolate * isolate) [inline], [explicit], [protected]
Definition at line 27 of file handles-inl.h.
    : location_(HandleScope::CreateHandle(isolate, object)) {}
HandleBase() [3/4]
v8::internal::HandleBase::HandleBase (Address object, LocalIsolate * isolate) [inline], [explicit], [protected]
Definition at line 30 of file handles-inl.h.
    : location_(LocalHandleScope::GetHandle(isolate->heap(), object)) {}
HandleBase() [4/4]
v8::internal::HandleBase::HandleBase (Address object, LocalHeap * local_heap) [inline], [explicit], [protected]
Definition at line 33 of file handles-inl.h.
    : location_(LocalHandleScope::GetHandle(local_heap, object)) {}
Member Function Documentation
address()
Address v8::internal::HandleBase::address () const [inline]
Definition at line 73 of file handles.h.
                                    {
    return reinterpret_cast<Address>(location_);
  }
References location_.
Referenced by v8::internal::AssemblerBase::AddCodeTarget(), v8::internal::Factory::CodeBuilder::BuildInternal(), v8::internal::Factory::CopyFixedDoubleArray(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency::Equals(), v8::internal::Handle< T >::equals(), v8::internal::compiler::turboshaft::CheckedClosureOp::hash_value(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Is(), v8::internal::Map::Normalize(), v8::internal::compiler::turboshaft::CheckedClosureOp::operator==(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual().
is_identical_to() [1/2]
template<typename T >
bool v8::internal::HandleBase::is_identical_to (const DirectHandle< T > & that) const [inline]
Definition at line 65 of file handles.h.
                                                                    {
    return is_identical_to(that.handle_);
  }
References v8::internal::DirectHandle< T >::handle_, and is_identical_to().
is_identical_to() [2/2]
bool v8::internal::HandleBase::is_identical_to (const HandleBase & that) const [inline]
Definition at line 36 of file handles-inl.h.
                                                             {
  SLOW_DCHECK((this->location_ == nullptr || this->IsDereferenceAllowed()) &&
              (that.location_ == nullptr || that.IsDereferenceAllowed()));
  if (this->location_ == that.location_) return true;
  if (this->location_ == nullptr || that.location_ == nullptr) return false;
  return Tagged<Object>(*this->location_) == Tagged<Object>(*that.location_);
}
References IsDereferenceAllowed(), location_, SLOW_DCHECK, and v8::internal::Tagged< Object >.
Referenced by v8::internal::FastKeyAccumulator::GetKeysWithPrototypeInfoCache(), v8::internal::CallSiteInfo::GetMethodName(), is_identical_to(), v8::internal::MaybeObjectHandle::is_identical_to(), v8::internal::JSObject::LazyRegisterPrototypeUser(), v8::internal::LookupIterator::PrepareForDataProperty(), v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk(), and v8::internal::KeyedStoreIC::UpdateStoreElement().
is_null()
bool v8::internal::HandleBase::is_null () const [inline]
Definition at line 69 of file handles.h.
{ return location_ == nullptr; }
References location_.
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), v8::internal::AssemblerBase::AddCodeTarget(), v8::internal::anonymous_namespace{ic.cc}::AddOneReceiverMapIfMissing(), v8::internal::interpreter::BytecodeGenerator::AllocateDeferredConstants(), v8::internal::maglev::MaglevCodeGenerator::BuildCodeObject(), v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor(), v8::internal::anonymous_namespace{keys.cc}::CombineKeys(), v8::internal::JsonParser< Char >::DecodeString(), v8::internal::interpreter::InterpreterCompilationJob::DoFinalizeJobImpl(), v8::internal::anonymous_namespace{runtime-literals.cc}::AllocationSiteCreationContext::EnterNewScope(), v8::internal::ConsumedPreparseData::For(), v8::internal::FeedbackVector::GetOptimizedOsrCode(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmData(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmGlobal(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmLocal(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmMemory(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmModuleBytes(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmStackValue(), v8::internal::IC::IC(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::anonymous_namespace{compiler.cc}::IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs(), v8::internal::anonymous_namespace{runtime-scopes.cc}::LoadLookupSlot(), v8::internal::Context::Lookup(), v8::internal::JsonParser< Char >::MakeString(), v8::internal::JsonParser< Char >::ParseJsonObject(), v8::internal::JsonParser< Char >::ParseJsonValue(), v8::internal::Debug::PrepareStep(), v8::internal::SourceTextModule::ResolveExportUsingStarExports(), v8::internal::SamplingHeapProfiler::SampleObject(), v8::internal::JsonStringifier::SerializeProperty(), v8::internal::Factory::CodeBuilder::set_bytecode_offset_table(), v8::internal::Factory::CodeBuilder::set_deoptimization_data(), v8::internal::Factory::CodeBuilder::set_self_reference(), v8::internal::Factory::CodeBuilder::set_source_position_table(), v8::internal::RegExpMacroAssemblerTracer::SkipUntilBitInTable(), v8::internal::KeyedStoreIC::Store(), v8::internal::anonymous_namespace{runtime-scopes.cc}::StoreLookupSlot(), v8::internal::PropertyDescriptor::ToPropertyDescriptor(), v8::internal::ErrorUtils::ToString(), and v8::internal::KeyedStoreIC::UpdateStoreElement().
IsDereferenceAllowed()
bool v8::internal::HandleBase::IsDereferenceAllowed () const [inline], [protected]
Definition at line 128 of file handles.h.
{ return true; }
Referenced by is_identical_to(), location(), v8::internal::Handle< T >::operator*(), and v8::internal::Handle< T >::PatchValue().
location()
Address* v8::internal::HandleBase::location () const [inline]
Definition at line 80 of file handles.h.
                                      {
    SLOW_DCHECK(location_ == nullptr || IsDereferenceAllowed());
    return location_;
  }
References IsDereferenceAllowed(), location_, and SLOW_DCHECK.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-compilation-info.cc}::CanonicalHandle(), v8::internal::OptimizedCompilationInfo::CanonicalHandle(), v8::internal::compiler::JSHeapBroker::CanonicalPersistentHandle(), v8::internal::TrustedManaged< CppType >::From(), v8::internal::Builtins::IsBuiltinHandle(), v8::internal::wasm::anonymous_namespace{wasm-interpreter.cc}::MakeWeak(), v8::internal::Handle< T >::operator*(), v8::internal::SamplingHeapProfiler::SampleObject(), v8::internal::CodeSerializer::SerializeSharedFunctionInfo(), v8::internal::ValueDeserializer::TransferArrayBuffer(), v8::internal::ScopeIterator::VisitLocals(), and v8::internal::ValueDeserializer::~ValueDeserializer().
repr()
ValueHelper::InternalRepresentationType v8::internal::HandleBase::repr () const [inline]
Definition at line 90 of file handles.h.
                                                               {
    return location_;
  }
References location_.
Referenced by v8::anonymous_namespace{api.cc}::GetSerializedDataFromFixedArray().
Member Data Documentation
location_
Address* v8::internal::HandleBase::location_ [protected]
Definition at line 135 of file handles.h.
Referenced by address(), is_identical_to(), is_null(), location(), v8::internal::Handle< T >::PatchValue(), and repr().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/handles.h
/mnt/V8SourceCode/src/handles/handles-inl.h