v8::internal::IdleTaskOnContextDispose Class Reference
Public Member Functions
IdleTaskOnContextDispose (Isolate *isolate)
void RunInternal (double deadline_in_seconds) override
Static Public Member Functions
static void TryPostJob (Heap *heap)
Private Member Functions
void TryRunMinorGC (const base::TimeDelta idle_time)
Private Attributes
Isolate * isolate_
const base::TimeTicks creation_time_ = base::TimeTicks::Now()
Static Private Attributes
static constexpr base::TimeDelta kFrameTime
static constexpr base::TimeDelta kMaxTimeToRun = kFrameTime + kFrameTime
Additional Inherited Members
Detailed Description
Definition at line 1823 of file heap.cc.
Constructor & Destructor Documentation
IdleTaskOnContextDispose()
v8::internal::IdleTaskOnContextDispose::IdleTaskOnContextDispose (Isolate * isolate) [inline], [explicit]
Definition at line 1833 of file heap.cc.
      : CancelableIdleTask(isolate), isolate_(isolate) {}
Member Function Documentation
RunInternal()
void v8::internal::IdleTaskOnContextDispose::RunInternal (double deadline_in_seconds) [inline], [override], [virtual]
Implements v8::internal::CancelableIdleTask.
Definition at line 1836 of file heap.cc.
                                                        {
    auto* heap = isolate_->heap();
    const base::TimeDelta time_to_run = base::TimeTicks::Now() - creation_time_;
    // The provided delta uses embedder timestamps.
    const base::TimeDelta idle_time = base::TimeDelta::FromMillisecondsD(
        (deadline_in_seconds * 1000) - heap->MonotonicallyIncreasingTimeInMs());
    const bool time_to_run_exceeded = time_to_run > kMaxTimeToRun;
    if (V8_UNLIKELY(v8_flags.trace_context_disposal)) {
      isolate_->PrintWithTimestamp(
          "[context-disposal/idle task] time-to-run: %fms (max delay: %fms), "
          "idle time: %fms%s\n",
          time_to_run.InMillisecondsF(), kMaxTimeToRun.InMillisecondsF(),
          idle_time.InMillisecondsF(),
          time_to_run_exceeded ? ", not starting any action" : "");
    }
    if (time_to_run_exceeded) {
      return;
    }
    TryRunMinorGC(idle_time);
  }
References v8::base::TimeDelta::FromMillisecondsD(), v8::internal::Isolate::heap(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::Heap::isolate_, v8::base::TimeTicks::Now(), v8::internal::v8_flags, and V8_UNLIKELY.
TryPostJob()
static void v8::internal::IdleTaskOnContextDispose::TryPostJob (Heap * heap) [inline], [static]
Definition at line 1825 of file heap.cc.
                                     {
    const auto runner = heap->GetForegroundTaskRunner();
    if (runner->IdleTasksEnabled()) {
      runner->PostIdleTask(
          std::make_unique<IdleTaskOnContextDispose>(heap->isolate()));
    }
  }
Referenced by v8::internal::Heap::NotifyContextDisposed().
TryRunMinorGC()
void v8::internal::IdleTaskOnContextDispose::TryRunMinorGC (const base::TimeDelta idle_time) [inline], [private]
Definition at line 1867 of file heap.cc.
                                                    {
    // The following logic estimates whether a young generation GC would fit in
    // `idle_time.` We bail out for a young gen below 1MB to avoid executing GC
    // when the mutator is not actually active.
    static constexpr size_t kMinYounGenSize = 1 * MB;
    auto* heap = isolate_->heap();
    const std::optional<double> young_gen_gc_speed =
        heap->tracer()->YoungGenerationSpeedInBytesPerMillisecond(
            YoungGenerationSpeedMode::kUpToAndIncludingAtomicPause);
    if (!young_gen_gc_speed) {
      return;
    }
    const size_t young_gen_bytes = heap->YoungGenerationSizeOfObjects();
    const base::TimeDelta young_gen_estimate =
        base::TimeDelta::FromMillisecondsD(young_gen_bytes /
                                           *young_gen_gc_speed);
    const bool run_young_gen_gc =
        young_gen_estimate < idle_time && young_gen_bytes > kMinYounGenSize;
    if (V8_UNLIKELY(v8_flags.trace_context_disposal)) {
      isolate_->PrintWithTimestamp(
          "[context-disposal/idle task] young generation size: %zuKB (min: "
          "%zuKB), GC speed: %fKB/ms, estimated time: %fms%s\n",
          young_gen_bytes / KB, kMinYounGenSize / KB, *young_gen_gc_speed / KB,
          young_gen_estimate.InMillisecondsF(),
          run_young_gen_gc ? ", performing young gen GC"
                           : ", not starting young gen GC");
    }
    if (run_young_gen_gc) {
      heap->CollectGarbage(NEW_SPACE,
                           GarbageCollectionReason::kIdleContextDisposal);
    }
  }
References v8::base::TimeDelta::FromMillisecondsD(), v8::internal::Isolate::heap(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::Heap::isolate_, v8::internal::KB, v8::internal::kIdleContextDisposal, v8::internal::kUpToAndIncludingAtomicPause, v8::internal::MB, v8::internal::NEW_SPACE, v8::internal::v8_flags, and V8_UNLIKELY.
Member Data Documentation
creation_time_
const base::TimeTicks v8::internal::IdleTaskOnContextDispose::creation_time_ = base::TimeTicks::Now() [private]
Definition at line 1902 of file heap.cc.
isolate_
Isolate* v8::internal::IdleTaskOnContextDispose::isolate_ [private]
Definition at line 1901 of file heap.cc.
kFrameTime
constexpr base::TimeDelta v8::internal::IdleTaskOnContextDispose::kFrameTime [static], [constexpr], [private]
Initial value:
=
      base::TimeDelta::FromMillisecondsD(16)
Definition at line 1858 of file heap.cc.
kMaxTimeToRun
constexpr base::TimeDelta v8::internal::IdleTaskOnContextDispose::kMaxTimeToRun = kFrameTime + kFrameTime [static], [constexpr], [private]
Definition at line 1865 of file heap.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/heap.cc