v8::internal::AssemblerRISCVF Class Reference
#include <extension-riscv-f.h>
Public Member Functions
void flw (FPURegister rd, Register rs1, int16_t imm12)
void fsw (FPURegister source, Register base, int16_t imm12)
void fmadd_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm=RNE)
void fmsub_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm=RNE)
void fnmsub_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm=RNE)
void fnmadd_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm=RNE)
void fadd_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm=RNE)
void fsub_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm=RNE)
void fmul_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm=RNE)
void fdiv_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm=RNE)
void fsqrt_s (FPURegister rd, FPURegister rs1, FPURoundingMode frm=RNE)
void fsgnj_s (FPURegister rd, FPURegister rs1, FPURegister rs2)
void fsgnjn_s (FPURegister rd, FPURegister rs1, FPURegister rs2)
void fsgnjx_s (FPURegister rd, FPURegister rs1, FPURegister rs2)
void fmin_s (FPURegister rd, FPURegister rs1, FPURegister rs2)
void fmax_s (FPURegister rd, FPURegister rs1, FPURegister rs2)
void fcvt_w_s (Register rd, FPURegister rs1, FPURoundingMode frm=RNE)
void fcvt_wu_s (Register rd, FPURegister rs1, FPURoundingMode frm=RNE)
void fmv_x_w (Register rd, FPURegister rs1)
void feq_s (Register rd, FPURegister rs1, FPURegister rs2)
void flt_s (Register rd, FPURegister rs1, FPURegister rs2)
void fle_s (Register rd, FPURegister rs1, FPURegister rs2)
void fclass_s (Register rd, FPURegister rs1)
void fcvt_s_w (FPURegister rd, Register rs1, FPURoundingMode frm=RNE)
void fcvt_s_wu (FPURegister rd, Register rs1, FPURoundingMode frm=RNE)
void fmv_w_x (FPURegister rd, Register rs1)
void fmv_s (FPURegister rd, FPURegister rs)
void fabs_s (FPURegister rd, FPURegister rs)
void fneg_s (FPURegister rd, FPURegister rs)
Additional Inherited Members
Detailed Description
Definition at line 15 of file extension-riscv-f.h.
Member Function Documentation
fabs_s()
void v8::internal::AssemblerRISCVF::fabs_s (FPURegister rd, FPURegister rs) [inline]
Definition at line 62 of file extension-riscv-f.h.
{ fsgnjx_s(rd, rs, rs); }
References fsgnjx_s().
fadd_s()
void v8::internal::AssemblerRISCVF::fadd_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm = RNE)
Definition at line 39 of file extension-riscv-f.cc.
                                                  {
  GenInstrALUFP_rr(0b0000000, frm, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fclass_s()
void v8::internal::AssemblerRISCVF::fclass_s (Register rd, FPURegister rs1)
Definition at line 113 of file extension-riscv-f.cc.
                                                           {
  GenInstrALUFP_rr(0b1110000, 0b001, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fcvt_s_w()
void v8::internal::AssemblerRISCVF::fcvt_s_w (FPURegister rd, Register rs1, FPURoundingMode frm = RNE)
Definition at line 117 of file extension-riscv-f.cc.
                                                    {
  GenInstrALUFP_rr(0b1101000, frm, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by v8::internal::MacroAssembler::Cvt_s_w(), and v8::internal::MacroAssembler::LoadFPRImmediate().
fcvt_s_wu()
void v8::internal::AssemblerRISCVF::fcvt_s_wu (FPURegister rd, Register rs1, FPURoundingMode frm = RNE)
Definition at line 122 of file extension-riscv-f.cc.
                                                     {
  GenInstrALUFP_rr(0b1101000, frm, rd, rs1, ToRegister(1));
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr(), and v8::internal::ToRegister().
Referenced by v8::internal::MacroAssembler::Cvt_s_uw().
fcvt_w_s()
void v8::internal::AssemblerRISCVF::fcvt_w_s (Register rd, FPURegister rs1, FPURoundingMode frm = RNE)
Definition at line 87 of file extension-riscv-f.cc.
                                                    {
  GenInstrALUFP_rr(0b1100000, frm, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by v8::internal::MacroAssembler::Ceil_w_s(), v8::internal::MacroAssembler::Floor_w_s(), v8::internal::MacroAssembler::Round_w_s(), and v8::internal::MacroAssembler::Trunc_w_s().
fcvt_wu_s()
void v8::internal::AssemblerRISCVF::fcvt_wu_s (Register rd, FPURegister rs1, FPURoundingMode frm = RNE)
Definition at line 92 of file extension-riscv-f.cc.
                                                     {
  GenInstrALUFP_rr(0b1100000, frm, rd, rs1, ToRegister(1));
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr(), and v8::internal::ToRegister().
Referenced by v8::internal::MacroAssembler::Trunc_uw_s().
fdiv_s()
void v8::internal::AssemblerRISCVF::fdiv_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm = RNE)
Definition at line 54 of file extension-riscv-f.cc.
                                                  {
  GenInstrALUFP_rr(0b0001100, frm, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
feq_s()
void v8::internal::AssemblerRISCVF::feq_s (Register rd, FPURegister rs1, FPURegister rs2)
Definition at line 101 of file extension-riscv-f.cc.
                                                                         {
  GenInstrALUFP_rr(0b1010000, 0b010, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by v8::internal::MacroAssembler::Clear_if_nan_s(), v8::internal::MacroAssembler::CompareF32(), v8::internal::MacroAssembler::CompareIsNotNanF32(), and v8::internal::MacroAssembler::FaddS().
fle_s()
void v8::internal::AssemblerRISCVF::fle_s (Register rd, FPURegister rs1, FPURegister rs2)
Definition at line 109 of file extension-riscv-f.cc.
                                                                         {
  GenInstrALUFP_rr(0b1010000, 0b000, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by v8::internal::MacroAssembler::CompareF32().
flt_s()
void v8::internal::AssemblerRISCVF::flt_s (Register rd, FPURegister rs1, FPURegister rs2)
Definition at line 105 of file extension-riscv-f.cc.
                                                                         {
  GenInstrALUFP_rr(0b1010000, 0b001, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by v8::internal::MacroAssembler::CompareF32().
flw()
void v8::internal::AssemblerRISCVF::flw (FPURegister rd, Register rs1, int16_t imm12)
Definition at line 11 of file extension-riscv-f.cc.
                                                                     {
  GenInstrLoadFP_ri(0b010, rd, rs1, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrLoadFP_ri().
Referenced by v8::internal::MacroAssembler::LoadFloat().
fmadd_s()
void v8::internal::AssemblerRISCVF::fmadd_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm = RNE)
Definition at line 19 of file extension-riscv-f.cc.
                                                                    {
  GenInstrR4(0b00, MADD, rd, rs1, rs2, rs3, frm);
}
References v8::internal::AssemblerRiscvBase::GenInstrR4(), and v8::internal::MADD.
fmax_s()
void v8::internal::AssemblerRISCVF::fmax_s (FPURegister rd, FPURegister rs1, FPURegister rs2)
Definition at line 83 of file extension-riscv-f.cc.
                                                                             {
  GenInstrALUFP_rr(0b0010100, 0b001, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fmin_s()
void v8::internal::AssemblerRISCVF::fmin_s (FPURegister rd, FPURegister rs1, FPURegister rs2)
Definition at line 79 of file extension-riscv-f.cc.
                                                                             {
  GenInstrALUFP_rr(0b0010100, 0b000, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fmsub_s()
void v8::internal::AssemblerRISCVF::fmsub_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm = RNE)
Definition at line 24 of file extension-riscv-f.cc.
                                                                    {
  GenInstrR4(0b00, MSUB, rd, rs1, rs2, rs3, frm);
}
References v8::internal::AssemblerRiscvBase::GenInstrR4(), and v8::internal::MSUB.
fmul_s()
void v8::internal::AssemblerRISCVF::fmul_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm = RNE)
Definition at line 49 of file extension-riscv-f.cc.
                                                  {
  GenInstrALUFP_rr(0b0001000, frm, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fmv_s()
void v8::internal::AssemblerRISCVF::fmv_s (FPURegister rd, FPURegister rs) [inline]
Definition at line 61 of file extension-riscv-f.h.
{ fsgnj_s(rd, rs, rs); }
References fsgnj_s().
Referenced by v8::internal::MacroAssembler::FloatMinMaxHelper(), and v8::internal::MacroAssembler::LoadFPRImmediate().
fmv_w_x()
void v8::internal::AssemblerRISCVF::fmv_w_x (FPURegister rd, Register rs1)
Definition at line 127 of file extension-riscv-f.cc.
                                                          {
  GenInstrALUFP_rr(0b1111000, 0b000, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by v8::internal::MacroAssembler::FaddS(), v8::internal::MacroAssembler::LoadFPRImmediate(), and v8::internal::MacroAssembler::RoundHelper().
fmv_x_w()
void v8::internal::AssemblerRISCVF::fmv_x_w (Register rd, FPURegister rs1)
Definition at line 97 of file extension-riscv-f.cc.
                                                          {
  GenInstrALUFP_rr(0b1110000, 0b000, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by v8::internal::MacroAssembler::FaddS().
fneg_s()
void v8::internal::AssemblerRISCVF::fneg_s (FPURegister rd, FPURegister rs) [inline]
Definition at line 63 of file extension-riscv-f.h.
{ fsgnjn_s(rd, rs, rs); }
References fsgnjn_s().
fnmadd_s()
void v8::internal::AssemblerRISCVF::fnmadd_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm = RNE)
Definition at line 34 of file extension-riscv-f.cc.
                                                                     {
  GenInstrR4(0b00, NMADD, rd, rs1, rs2, rs3, frm);
}
References v8::internal::AssemblerRiscvBase::GenInstrR4(), and v8::internal::NMADD.
fnmsub_s()
void v8::internal::AssemblerRISCVF::fnmsub_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm = RNE)
Definition at line 29 of file extension-riscv-f.cc.
                                                                     {
  GenInstrR4(0b00, NMSUB, rd, rs1, rs2, rs3, frm);
}
References v8::internal::AssemblerRiscvBase::GenInstrR4(), and v8::internal::NMSUB.
fsgnj_s()
void v8::internal::AssemblerRISCVF::fsgnj_s (FPURegister rd, FPURegister rs1, FPURegister rs2)
Definition at line 64 of file extension-riscv-f.cc.
                                               {
  GenInstrALUFP_rr(0b0010000, 0b000, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by fmv_s().
fsgnjn_s()
void v8::internal::AssemblerRISCVF::fsgnjn_s (FPURegister rd, FPURegister rs1, FPURegister rs2)
Definition at line 69 of file extension-riscv-f.cc.
                                                {
  GenInstrALUFP_rr(0b0010000, 0b001, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by fneg_s().
fsgnjx_s()
void v8::internal::AssemblerRISCVF::fsgnjx_s (FPURegister rd, FPURegister rs1, FPURegister rs2)
Definition at line 74 of file extension-riscv-f.cc.
                                                {
  GenInstrALUFP_rr(0b0010000, 0b010, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by fabs_s().
fsqrt_s()
void v8::internal::AssemblerRISCVF::fsqrt_s (FPURegister rd, FPURegister rs1, FPURoundingMode frm = RNE)
Definition at line 59 of file extension-riscv-f.cc.
                                                   {
  GenInstrALUFP_rr(0b0101100, frm, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fsub_s()
void v8::internal::AssemblerRISCVF::fsub_s (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm = RNE)
Definition at line 44 of file extension-riscv-f.cc.
                                                  {
  GenInstrALUFP_rr(0b0000100, frm, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fsw()
void v8::internal::AssemblerRISCVF::fsw (FPURegister source, Register base, int16_t imm12)
Definition at line 15 of file extension-riscv-f.cc.
                                                                          {
  GenInstrStoreFP_rri(0b010, base, source, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrStoreFP_rri().
Referenced by v8::internal::MacroAssembler::StoreFloat().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-f.h
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-f.cc