v8::internal::ProfilingMigrationObserver Class Reference
Public Member Functions
ProfilingMigrationObserver (Heap *heap)
void Move (AllocationSpace dest, Tagged< HeapObject > src, Tagged< HeapObject > dst, int size) final
Additional Inherited Members
Detailed Description
Definition at line 1423 of file mark-compact.cc.
Constructor & Destructor Documentation
ProfilingMigrationObserver()
v8::internal::ProfilingMigrationObserver::ProfilingMigrationObserver (Heap * heap) [inline], [explicit]
Definition at line 1425 of file mark-compact.cc.
: MigrationObserver(heap) {}
Member Function Documentation
Move()
void v8::internal::ProfilingMigrationObserver::Move (AllocationSpace dest, Tagged< HeapObject > src, Tagged< HeapObject > dst, int size) [inline], [final], [virtual]
Implements v8::internal::MigrationObserver.
Definition at line 1427 of file mark-compact.cc.
                                                           {
    // Note this method is called in a concurrent setting. The current object
    // (src and dst) is somewhat safe to access without precautions, but other
    // objects may be subject to concurrent modification.
    if (dest == CODE_SPACE) {
      PROFILE(heap_->isolate(), CodeMoveEvent(Cast<InstructionStream>(src),
                                              Cast<InstructionStream>(dst)));
    } else if ((dest == OLD_SPACE || dest == TRUSTED_SPACE) &&
               IsBytecodeArray(dst)) {
      // TODO(saelo): remove `dest == OLD_SPACE` once BytecodeArrays are
      // allocated in trusted space.
      PROFILE(heap_->isolate(), BytecodeMoveEvent(Cast<BytecodeArray>(src),
                                                  Cast<BytecodeArray>(dst)));
    }
    heap_->OnMoveEvent(src, dst, size);
  }
References v8::internal::CODE_SPACE, v8::internal::MigrationObserver::heap_, v8::internal::Heap::isolate(), v8::internal::OLD_SPACE, v8::internal::Heap::OnMoveEvent(), PROFILE, size(), and v8::internal::TRUSTED_SPACE.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc