v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::TempRegisterScope Class Reference
Public Member Functions
LiftoffRegister Acquire (RegClass rc)
void Return (LiftoffRegister &&temp)
void Return (Register &&temp)
LiftoffRegList AddTempRegisters (int count, RegClass rc, LiftoffAssembler *lasm, LiftoffRegList pinned)
Private Attributes
LiftoffRegList free_temps_
Detailed Description
Definition at line 369 of file liftoff-compiler.cc.
Member Function Documentation
Acquire()
LiftoffRegister v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::TempRegisterScope::Acquire (RegClass rc) [inline]
Definition at line 371 of file liftoff-compiler.cc.
                                       {
    LiftoffRegList candidates = free_temps_ & GetCacheRegList(rc);
    DCHECK(!candidates.is_empty());
    return free_temps_.clear(candidates.GetFirstRegSet());
  }
References v8::internal::DCHECK(), v8::internal::wasm::GetCacheRegList(), v8::internal::wasm::LiftoffRegList::GetFirstRegSet(), and v8::internal::wasm::LiftoffRegList::is_empty().
AddTempRegisters()
LiftoffRegList v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::TempRegisterScope::AddTempRegisters (int count, RegClass rc, LiftoffAssembler * lasm, LiftoffRegList pinned) [inline]
Definition at line 387 of file liftoff-compiler.cc.
                                                         {
    LiftoffRegList temps;
    pinned |= free_temps_;
    for (int i = 0; i < count; ++i) {
      temps.set(lasm->GetUnusedRegister(rc, pinned | temps));
    }
    free_temps_ |= temps;
    return temps;
  }
References v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::wasm::LiftoffRegList::set().
Return() [1/2]
void v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::TempRegisterScope::Return (LiftoffRegister && temp) [inline]
Definition at line 377 of file liftoff-compiler.cc.
                                      {
    DCHECK(!free_temps_.has(temp));
    free_temps_.set(temp);
  }
References v8::internal::DCHECK().
Return() [2/2]
void v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::TempRegisterScope::Return (Register && temp) [inline]
Definition at line 382 of file liftoff-compiler.cc.
                               {
    Return(LiftoffRegister{temp});
    temp = no_reg;
  }
References v8::internal::no_reg.
Member Data Documentation
free_temps_
LiftoffRegList v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::TempRegisterScope::free_temps_ [private]
Definition at line 400 of file liftoff-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/baseline/liftoff-compiler.cc