v8::internal::State Class Reference
Public Member Functions
State (const HeapObjectHeader &header, size_t state_count)
~State () final=default
const HeapObjectHeader * header () const
void MarkVisited ()
void MarkPending ()
void UnmarkPending ()
void MarkVisible ()
void MarkDependentVisibility (StateBase *dependency)
void MarkAsWeakContainer ()
bool IsWeakContainer () const
void MarkVisitedFromStack ()
bool WasVisitedFromStack () const
void RecordEphemeronKey (const HeapObjectHeader &key)
void AddEphemeronEdge (const HeapObjectHeader &value)
void AddEagerEphemeronEdge (const void *value, cppgc::TraceCallback callback)
template<typename Callback >
void ForAllEphemeronKeys (Callback callback)
template<typename Callback >
void ForAllEphemeronEdges (Callback callback)
template<typename Callback >
void ForAllEagerEphemeronEdges (Callback callback)
Private Attributes
bool is_weak_container_ = false
bool was_visited_from_stack_ = false
std::unordered_set< const HeapObjectHeader * > ephemeron_keys_
std::unordered_set< const HeapObjectHeader * > ephemeron_edges_
std::unordered_map< const void *, cppgc::TraceCallback > eager_ephemeron_edges_
Additional Inherited Members
Detailed Description
Definition at line 205 of file cpp-snapshot.cc.
Constructor & Destructor Documentation
State()
v8::internal::State::State (const HeapObjectHeader & header, size_t state_count) [inline]
Definition at line 207 of file cpp-snapshot.cc.
      : StateBase(&header, state_count, Visibility::kHidden, nullptr, false) {}
 State()
v8::internal::State::~State () [final], [default]
Member Function Documentation
AddEagerEphemeronEdge()
void v8::internal::State::AddEagerEphemeronEdge (const void * value, cppgc::TraceCallback callback) [inline]
Definition at line 286 of file cpp-snapshot.cc.
                                                                             {
    eager_ephemeron_edges_.insert({value, callback});
  }
References eager_ephemeron_edges_, and v8::internal::value.
AddEphemeronEdge()
void v8::internal::State::AddEphemeronEdge (const HeapObjectHeader & value) [inline]
Definition at line 280 of file cpp-snapshot.cc.
                                                       {
    // This ignores duplicate entries (in different containers) for the same
    // Key->Value pairs. Only one edge will be emitted in this case.
    ephemeron_edges_.insert(&value);
  }
References ephemeron_edges_, and v8::internal::value.
ForAllEagerEphemeronEdges()
template<typename Callback >
void v8::internal::State::ForAllEagerEphemeronEdges (Callback callback) [inline]
Definition at line 305 of file cpp-snapshot.cc.
                                                    {
    for (const auto& pair : eager_ephemeron_edges_) {
      callback(pair.first, pair.second);
    }
  }
References eager_ephemeron_edges_.
Referenced by v8::internal::CppGraphBuilderImpl::Run().
ForAllEphemeronEdges()
template<typename Callback >
void v8::internal::State::ForAllEphemeronEdges (Callback callback) [inline]
Definition at line 298 of file cpp-snapshot.cc.
                                               {
    for (const HeapObjectHeader* value : ephemeron_edges_) {
      callback(*value);
    }
  }
References ephemeron_edges_, and v8::internal::value.
Referenced by v8::internal::CppGraphBuilderImpl::Run().
ForAllEphemeronKeys()
template<typename Callback >
void v8::internal::State::ForAllEphemeronKeys (Callback callback) [inline]
Definition at line 291 of file cpp-snapshot.cc.
                                              {
    for (const HeapObjectHeader* value : ephemeron_keys_) {
      callback(*value);
    }
  }
References ephemeron_keys_, and v8::internal::value.
header()
const HeapObjectHeader* v8::internal::State::header () const [inline]
Definition at line 211 of file cpp-snapshot.cc.
                                         {
    return static_cast<const HeapObjectHeader*>(key_);
  }
References v8::internal::StateBase::key_.
Referenced by v8::internal::CppGraphBuilderImpl::AddEdge(), v8::internal::CppGraphBuilderImpl::AddEdgeForCppHeapExternalObject(), v8::internal::CppGraphBuilderImpl::AddRootEdge(), and v8::internal::CppGraphBuilderImpl::Run().
IsWeakContainer()
bool v8::internal::State::IsWeakContainer () const [inline]
Definition at line 269 of file cpp-snapshot.cc.
{ return is_weak_container_; }
References is_weak_container_.
Referenced by v8::internal::CppGraphBuilderImpl::Run().
MarkAsWeakContainer()
void v8::internal::State::MarkAsWeakContainer () [inline]
Definition at line 268 of file cpp-snapshot.cc.
{ is_weak_container_ = true; }
References is_weak_container_.
MarkDependentVisibility()
void v8::internal::State::MarkDependentVisibility (StateBase * dependency) [inline]
Definition at line 225 of file cpp-snapshot.cc.
                                                      {
    // Follow and update dependencies as much as possible.
    dependency = dependency->FollowDependencies();
    DCHECK(dependency->IsVisited());
    if (visibility_ == StateBase::Visibility::kVisible) {
      // Already visible, no dependency needed.
      DCHECK_NULL(visibility_dependency_);
      return;
    }
    if (dependency->visibility_ == Visibility::kVisible) {
      // Simple case: Dependency is visible.
      visibility_ = Visibility::kVisible;
      visibility_dependency_ = nullptr;
      return;
    }
    if ((visibility_dependency_ &&
         (visibility_dependency_->state_count_ > dependency->state_count_)) ||
        (!visibility_dependency_ &&
         (state_count_ > dependency->state_count_))) {
      // Only update when new state_count_ < original state_count_. This
      // ensures that we pick an ancestor as dependency and not a child which
      // is guaranteed to converge to an answer.
      //
      // Dependency is now
      // a) either pending with unknown visibility (same call chain), or
      // b) not pending and has defined visibility.
      //
      // It's not possible to point to a state that is not pending but has
      // dependent visibility because dependencies are updated to the top-most
      // dependency at the beginning of method.
      if (dependency->IsPending()) {
        visibility_ = Visibility::kDependentVisibility;
        visibility_dependency_ = dependency;
      } else {
        CHECK_NE(Visibility::kDependentVisibility, dependency->visibility_);
        if (dependency->visibility_ == Visibility::kVisible) {
          visibility_ = Visibility::kVisible;
          visibility_dependency_ = nullptr;
        }
      }
    }
  }
References CHECK_NE, v8::internal::DCHECK(), DCHECK_NULL, v8::internal::StateBase::FollowDependencies(), v8::internal::StateBase::IsPending(), v8::internal::StateBase::IsVisited(), v8::internal::StateBase::kDependentVisibility, v8::internal::StateBase::kVisible, v8::internal::StateBase::state_count_, v8::internal::StateBase::visibility_, and v8::internal::StateBase::visibility_dependency_.
Referenced by v8::internal::CppGraphBuilderImpl::VisitForVisibility().
MarkPending()
void v8::internal::State::MarkPending () [inline]
Definition at line 217 of file cpp-snapshot.cc.
{ pending_ = true; }
References v8::internal::StateBase::pending_.
MarkVisible()
void v8::internal::State::MarkVisible () [inline]
Definition at line 220 of file cpp-snapshot.cc.
                     {
    visibility_ = Visibility::kVisible;
    visibility_dependency_ = nullptr;
  }
References v8::internal::StateBase::kVisible, v8::internal::StateBase::visibility_, and v8::internal::StateBase::visibility_dependency_.
Referenced by v8::internal::CppGraphBuilderImpl::VisitForVisibility().
MarkVisited()
void v8::internal::State::MarkVisited () [inline]
Definition at line 215 of file cpp-snapshot.cc.
{ visited_ = true; }
References v8::internal::StateBase::visited_.
MarkVisitedFromStack()
void v8::internal::State::MarkVisitedFromStack () [inline]
Definition at line 271 of file cpp-snapshot.cc.
{ was_visited_from_stack_ = true; }
References was_visited_from_stack_.
RecordEphemeronKey()
void v8::internal::State::RecordEphemeronKey (const HeapObjectHeader & key) [inline]
Definition at line 274 of file cpp-snapshot.cc.
                                                       {
    // This ignores duplicate entries (in different containers) for the same
    // Key->Value pairs. Only one edge will be emitted in this case.
    ephemeron_keys_.insert(&key);
  }
References ephemeron_keys_, and v8::internal::key.
UnmarkPending()
void v8::internal::State::UnmarkPending () [inline]
Definition at line 218 of file cpp-snapshot.cc.
{ pending_ = false; }
References v8::internal::StateBase::pending_.
WasVisitedFromStack()
bool v8::internal::State::WasVisitedFromStack () const [inline]
Definition at line 272 of file cpp-snapshot.cc.
{ return was_visited_from_stack_; }
References was_visited_from_stack_.
Member Data Documentation
eager_ephemeron_edges_
std::unordered_map<const void*, cppgc::TraceCallback> v8::internal::State::eager_ephemeron_edges_ [private]
Definition at line 321 of file cpp-snapshot.cc.
Referenced by AddEagerEphemeronEdge(), and ForAllEagerEphemeronEdges().
ephemeron_edges_
std::unordered_set<const HeapObjectHeader*> v8::internal::State::ephemeron_edges_ [private]
Definition at line 318 of file cpp-snapshot.cc.
Referenced by AddEphemeronEdge(), and ForAllEphemeronEdges().
ephemeron_keys_
std::unordered_set<const HeapObjectHeader*> v8::internal::State::ephemeron_keys_ [private]
Definition at line 316 of file cpp-snapshot.cc.
Referenced by ForAllEphemeronKeys(), and RecordEphemeronKey().
is_weak_container_
bool v8::internal::State::is_weak_container_ = false [private]
Definition at line 312 of file cpp-snapshot.cc.
Referenced by IsWeakContainer(), and MarkAsWeakContainer().
was_visited_from_stack_
bool v8::internal::State::was_visited_from_stack_ = false [private]
Definition at line 313 of file cpp-snapshot.cc.
Referenced by MarkVisitedFromStack(), and WasVisitedFromStack().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc-js/cpp-snapshot.cc