v8::internal::compiler::PhiInstruction Class Reference
#include <instruction.h>
Public Types
using Inputs = ZoneVector< InstructionOperand >
Public Member Functions
PhiInstruction (Zone *zone, int virtual_register, size_t input_count)
void SetInput (size_t offset, int virtual_register)
void RenameInput (size_t offset, int virtual_register)
int virtual_register () const
const IntVector & operands () const
const InstructionOperand & output () const
InstructionOperand & output ()
Private Attributes
const int virtual_register_
InstructionOperand output_
IntVector operands_
Detailed Description
Definition at line 1678 of file instruction.h.
Member Typedef Documentation
Inputs
using v8::internal::compiler::PhiInstruction::Inputs = ZoneVector<InstructionOperand>
Definition at line 1681 of file instruction.h.
Constructor & Destructor Documentation
PhiInstruction()
v8::internal::compiler::PhiInstruction::PhiInstruction (Zone * zone, int virtual_register, size_t input_count)
Definition at line 645 of file instruction.cc.
    : virtual_register_(virtual_register),
      output_(UnallocatedOperand(UnallocatedOperand::NONE, virtual_register)),
      operands_(input_count, InstructionOperand::kInvalidVirtualRegister,
                zone) {}
Member Function Documentation
operands()
const IntVector& v8::internal::compiler::PhiInstruction::operands () const [inline]
Definition at line 1689 of file instruction.h.
{ return operands_; }
Referenced by v8::internal::compiler::RegisterAllocationData::PhiMapValue::PhiMapValue(), v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi(), v8::internal::compiler::InstructionSelector::UpdateRenamesInPhi(), and v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment().
output() [1/2]
InstructionOperand& v8::internal::compiler::PhiInstruction::output () [inline]
Definition at line 1694 of file instruction.h.
{ return output_; }
output() [2/2]
const InstructionOperand& v8::internal::compiler::PhiInstruction::output () const [inline]
Definition at line 1693 of file instruction.h.
{ return output_; }
RenameInput()
void v8::internal::compiler::PhiInstruction::RenameInput (size_t offset, int virtual_register)
Definition at line 657 of file instruction.cc.
                                                                    {
  DCHECK_NE(InstructionOperand::kInvalidVirtualRegister, operands_[offset]);
  operands_[offset] = virtual_register;
}
References DCHECK_NE, v8::internal::compiler::InstructionOperand::kInvalidVirtualRegister, operands_, and virtual_register().
Referenced by v8::internal::compiler::InstructionSelector::UpdateRenamesInPhi().
SetInput()
void v8::internal::compiler::PhiInstruction::SetInput (size_t offset, int virtual_register)
Definition at line 652 of file instruction.cc.
                                                                 {
  DCHECK_EQ(InstructionOperand::kInvalidVirtualRegister, operands_[offset]);
  operands_[offset] = virtual_register;
}
References DCHECK_EQ, v8::internal::compiler::InstructionOperand::kInvalidVirtualRegister, operands_, and virtual_register().
Referenced by v8::internal::compiler::InstructionSelector::VisitPhi().
virtual_register()
int v8::internal::compiler::PhiInstruction::virtual_register () const [inline]
Definition at line 1688 of file instruction.h.
{ return virtual_register_; }
Referenced by v8::internal::compiler::RegisterAllocationData::InitializePhiMap(), RenameInput(), and SetInput().
Member Data Documentation
operands_
IntVector v8::internal::compiler::PhiInstruction::operands_ [private]
Definition at line 1699 of file instruction.h.
Referenced by RenameInput(), and SetInput().
output_
InstructionOperand v8::internal::compiler::PhiInstruction::output_ [private]
Definition at line 1698 of file instruction.h.
virtual_register_
const int v8::internal::compiler::PhiInstruction::virtual_register_ [private]
Definition at line 1697 of file instruction.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction.h
/mnt/V8SourceCode/src/compiler/backend/instruction.cc