v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction Class Reference
#include <js-function.h>
Static Public Member Functions
static Maybe< bool > CopyNameAndLength (Isolate *isolate, DirectHandle< JSFunctionOrBoundFunctionOrWrappedFunction > function, DirectHandle< JSReceiver > target, DirectHandle< String > prefix, int arg_count)
Static Public Attributes
static const int kLengthDescriptorIndex = 0
static const int kNameDescriptorIndex = 1
Detailed Description
Definition at line 26 of file js-function.h.
Member Function Documentation
CopyNameAndLength()
Maybe< bool > v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength (Isolate * isolate, DirectHandle< JSFunctionOrBoundFunctionOrWrappedFunction > function, DirectHandle< JSReceiver > target, DirectHandle< String > prefix, int arg_count) [static]
Definition at line 354 of file js-function.cc.
                   {
  // Setup the "length" property based on the "length" of the {target}.
  // If the targets length is the default JSFunction accessor, we can keep the
  // accessor that's installed by default on the
  // JSBoundFunction/JSWrappedFunction. It lazily computes the value from the
  // underlying internal length.
  DirectHandle<AccessorInfo> function_length_accessor =
      isolate->factory()->function_length_accessor();
  LookupIterator length_lookup(isolate, target,
                               isolate->factory()->length_string(), target,
                               LookupIterator::OWN);
  if (!IsJSFunction(*target) ||
      length_lookup.state() != LookupIterator::ACCESSOR ||
      !length_lookup.GetAccessors().is_identical_to(function_length_accessor)) {
    DirectHandle<Object> length(Smi::zero(), isolate);
    Maybe<PropertyAttributes> attributes =
        JSReceiver::GetPropertyAttributes(&length_lookup);
    if (attributes.IsNothing()) return Nothing<bool>();
    if (attributes.FromJust() != ABSENT) {
      DirectHandle<Object> target_length;
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, target_length,
                                       Object::GetProperty(&length_lookup),
                                       Nothing<bool>());
      if (IsNumber(*target_length)) {
        length = isolate->factory()->NewNumber(std::max(
            0.0,
            DoubleToInteger(Object::NumberValue(*target_length)) - arg_count));
      }
    }
    LookupIterator it(isolate, function, isolate->factory()->length_string(),
                      function);
    DCHECK_EQ(LookupIterator::ACCESSOR, it.state());
    RETURN_ON_EXCEPTION_VALUE(isolate,
                              JSObject::DefineOwnPropertyIgnoreAttributes(
                                  &it, length, it.property_attributes()),
                              Nothing<bool>());
  }
  // Setup the "name" property based on the "name" of the {target}.
  // If the target's name is the default JSFunction accessor, we can keep the
  // accessor that's installed by default on the
  // JSBoundFunction/JSWrappedFunction. It lazily computes the value from the
  // underlying internal name.
  DirectHandle<AccessorInfo> function_name_accessor =
      isolate->factory()->function_name_accessor();
  LookupIterator name_lookup(isolate, target, isolate->factory()->name_string(),
                             target);
  if (!IsJSFunction(*target) ||
      name_lookup.state() != LookupIterator::ACCESSOR ||
      !name_lookup.GetAccessors().is_identical_to(function_name_accessor) ||
      (name_lookup.IsFound() && !name_lookup.HolderIsReceiver())) {
    DirectHandle<Object> target_name;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, target_name,
                                     Object::GetProperty(&name_lookup),
                                     Nothing<bool>());
    DirectHandle<String> name;
    if (IsString(*target_name)) {
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(
          isolate, name,
          Name::ToFunctionName(isolate, Cast<String>(target_name)),
          Nothing<bool>());
      if (!prefix.is_null()) {
        ASSIGN_RETURN_ON_EXCEPTION_VALUE(
            isolate, name, isolate->factory()->NewConsString(prefix, name),
            Nothing<bool>());
      }
    } else if (prefix.is_null()) {
      name = isolate->factory()->empty_string();
    } else {
      name = prefix;
    }
    LookupIterator it(isolate, function, isolate->factory()->name_string());
    DCHECK_EQ(LookupIterator::ACCESSOR, it.state());
    RETURN_ON_EXCEPTION_VALUE(isolate,
                              JSObject::DefineOwnPropertyIgnoreAttributes(
                                  &it, name, it.property_attributes()),
                              Nothing<bool>());
  }
  return Just(true);
}
References v8::internal::ABSENT, v8::internal::LookupIterator::ACCESSOR, ASSIGN_RETURN_ON_EXCEPTION_VALUE, DCHECK_EQ, v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::DoubleToInteger(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::LookupIterator::GetAccessors(), v8::internal::Object::GetProperty(), v8::internal::JSReceiver::GetPropertyAttributes(), v8::internal::LookupIterator::HolderIsReceiver(), v8::internal::DirectHandle< T >::is_null(), v8::internal::LookupIterator::IsFound(), v8::Maybe< T >::IsNothing(), v8::internal::IsNumber(), v8::Just(), v8::internal::length, v8::internal::name, v8::internal::FactoryBase< Impl >::NewConsString(), v8::internal::FactoryBase< Impl >::NewNumber(), v8::internal::Object::NumberValue(), v8::internal::LookupIterator::OWN, v8::internal::LookupIterator::property_attributes(), RETURN_ON_EXCEPTION_VALUE, v8::internal::LookupIterator::state(), v8::internal::Name::ToFunctionName(), and v8::internal::Smi::zero().
Referenced by v8::internal::JSWrappedFunction::Create(), and v8::internal::anonymous_namespace{builtins-function.cc}::DoFunctionBind().
Member Data Documentation
kLengthDescriptorIndex
const int v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::kLengthDescriptorIndex = 0 [static]
Definition at line 30 of file js-function.h.
Referenced by v8::internal::Factory::CreateSloppyFunctionMap(), v8::internal::Genesis::InitializeGlobal(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), and v8::internal::TF_BUILTIN().
kNameDescriptorIndex
const int v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::kNameDescriptorIndex = 1 [static]
Definition at line 31 of file js-function.h.
Referenced by v8::internal::Factory::CreateSloppyFunctionMap(), v8::internal::Genesis::InitializeGlobal(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), and v8::internal::TF_BUILTIN().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-function.h
/mnt/V8SourceCode/src/objects/js-function.cc