v8::internal::NumberDictionaryBaseShape Class Reference
#include <dictionary.h>
Static Public Member Functions
static bool IsMatch (uint32_t key, Tagged< Object > other)
template<AllocationType allocation = AllocationType::kYoung>
static DirectHandle< Object > AsHandle (Isolate *isolate, uint32_t key)
template<AllocationType allocation = AllocationType::kOld>
static DirectHandle< Object > AsHandle (LocalIsolate *isolate, uint32_t key)
static uint32_t Hash (ReadOnlyRoots roots, uint32_t key)
static uint32_t HashForObject (ReadOnlyRoots roots, Tagged< Object > object)
Static Public Attributes
static const bool kMatchNeedsHoleCheck = true
Additional Inherited Members
Detailed Description
Definition at line 364 of file dictionary.h.
Member Function Documentation
AsHandle() [1/2]
template<AllocationType allocation>
DirectHandle< Object > v8::internal::NumberDictionaryBaseShape::AsHandle (Isolate * isolate, uint32_t key) [inline], [static]
Definition at line 303 of file dictionary-inl.h.
                                                                       {
  return isolate->factory()->NewNumberFromUint<allocation>(key);
}
References v8::internal::Isolate::factory(), v8::internal::key, and v8::internal::FactoryBase< Impl >::NewNumberFromUint().
AsHandle() [2/2]
template<AllocationType allocation>
DirectHandle< Object > v8::internal::NumberDictionaryBaseShape::AsHandle (LocalIsolate * isolate, uint32_t key) [inline], [static]
Definition at line 309 of file dictionary-inl.h.
                                                                       {
  return isolate->factory()->NewNumberFromUint<allocation>(key);
}
References v8::internal::LocalIsolate::factory(), v8::internal::key, and v8::internal::FactoryBase< Impl >::NewNumberFromUint().
Hash()
uint32_t v8::internal::NumberDictionaryBaseShape::Hash (ReadOnlyRoots roots, uint32_t key) [inline], [static]
Definition at line 290 of file dictionary-inl.h.
                                                                          {
  return ComputeSeededHash(key, HashSeed(roots));
}
References v8::internal::ComputeSeededHash(), v8::internal::HashSeed(), and v8::internal::key.
HashForObject()
uint32_t v8::internal::NumberDictionaryBaseShape::HashForObject (ReadOnlyRoots roots, Tagged< Object > object) [inline], [static]
Definition at line 294 of file dictionary-inl.h.
                                                                        {
  DCHECK(IsNumber(other));
  return ComputeSeededHash(
      static_cast<uint32_t>(Object::NumberValue(Cast<Number>(other))),
      HashSeed(roots));
}
References v8::internal::ComputeSeededHash(), v8::internal::DCHECK(), v8::internal::HashSeed(), v8::internal::IsNumber(), and v8::internal::Object::NumberValue().
IsMatch()
bool v8::internal::NumberDictionaryBaseShape::IsMatch (uint32_t key, Tagged< Object > other) [inline], [static]
Definition at line 286 of file dictionary-inl.h.
                                                                          {
  return key == static_cast<uint32_t>(Object::NumberValue(Cast<Number>(other)));
}
References v8::internal::key, and v8::internal::Object::NumberValue().
Member Data Documentation
kMatchNeedsHoleCheck
const bool v8::internal::NumberDictionaryBaseShape::kMatchNeedsHoleCheck = true [static]
Definition at line 377 of file dictionary.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/dictionary.h
/mnt/V8SourceCode/src/objects/dictionary-inl.h