v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator Class Reference
Public Member Functions
DebugWasmScopeIterator (WasmFrame *frame)
bool Done () override
void Advance () override
ScopeType GetType () override
v8::Local< v8::Object > GetObject () override
v8::Local< v8::Value > GetFunctionDebugName () override
int GetScriptId () override
bool HasLocationInfo () override
debug::Location GetStartLocation () override
debug::Location GetEndLocation () override
bool SetVariableValue (v8::Local< v8::String > name, v8::Local< v8::Value > value) override
Private Attributes
WasmFrame *const frame_
ScopeType type_
Additional Inherited Members
Detailed Description
Definition at line 648 of file debug-wasm-objects.cc.
Constructor & Destructor Documentation
DebugWasmScopeIterator()
v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::DebugWasmScopeIterator (WasmFrame * frame) [inline], [explicit]
Definition at line 650 of file debug-wasm-objects.cc.
      : frame_(frame),
        type_(debug::ScopeIterator::ScopeTypeWasmExpressionStack) {
    // Skip local scope and expression stack scope if the frame is not
    // inspectable.
    if (!frame->is_inspectable()) {
      type_ = debug::ScopeIterator::ScopeTypeModule;
    }
  }
References v8::debug::ScopeIterator::ScopeTypeModule.
Member Function Documentation
Advance()
void v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::Advance () [inline], [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 662 of file debug-wasm-objects.cc.
                          {
    DCHECK(!Done());
    switch (type_) {
      case ScopeTypeWasmExpressionStack:
        type_ = debug::ScopeIterator::ScopeTypeLocal;
        break;
      case ScopeTypeLocal:
        type_ = debug::ScopeIterator::ScopeTypeModule;
        break;
      case ScopeTypeModule:
        // We use ScopeTypeWith type as marker for done.
        type_ = debug::ScopeIterator::ScopeTypeWith;
        break;
      default:
        UNREACHABLE();
    }
  }
References v8::internal::DCHECK(), v8::debug::ScopeIterator::ScopeTypeLocal, v8::debug::ScopeIterator::ScopeTypeModule, v8::debug::ScopeIterator::ScopeTypeWith, and v8::internal::UNREACHABLE().
Done()
bool v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::Done () [inline], [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 660 of file debug-wasm-objects.cc.
{ return type_ == ScopeTypeWith; }
GetEndLocation()
debug::Location v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::GetEndLocation () [inline], [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 742 of file debug-wasm-objects.cc.
{ return {}; }
GetFunctionDebugName()
v8::Local<v8::Value> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::GetFunctionDebugName () [inline], [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 732 of file debug-wasm-objects.cc.
                                                   {
    return Utils::ToLocal(frame_->isolate()->factory()->empty_string());
  }
GetObject()
v8::Local<v8::Object> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::GetObject () [inline], [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 682 of file debug-wasm-objects.cc.
                                         {
    Isolate* isolate = frame_->isolate();
    switch (type_) {
      case debug::ScopeIterator::ScopeTypeModule: {
        DirectHandle<WasmInstanceObject> instance{frame_->wasm_instance(),
                                                  isolate};
        DirectHandle<JSObject> object =
            isolate->factory()->NewSlowJSObjectWithNullProto();
        JSObject::AddProperty(isolate, object, "instance", instance, FROZEN);
        DirectHandle<JSObject> module_object(instance->module_object(),
                                             isolate);
        JSObject::AddProperty(isolate, object, "module", module_object, FROZEN);
        if (FunctionsProxy::Count(isolate, instance) != 0) {
          JSObject::AddProperty(
              isolate, object, "functions",
              GetOrCreateInstanceProxy<FunctionsProxy>(isolate, instance),
              FROZEN);
        }
        if (GlobalsProxy::Count(isolate, instance) != 0) {
          JSObject::AddProperty(
              isolate, object, "globals",
              GetOrCreateInstanceProxy<GlobalsProxy>(isolate, instance),
              FROZEN);
        }
        if (MemoriesProxy::Count(isolate, instance) != 0) {
          JSObject::AddProperty(
              isolate, object, "memories",
              GetOrCreateInstanceProxy<MemoriesProxy>(isolate, instance),
              FROZEN);
        }
        if (TablesProxy::Count(isolate, instance) != 0) {
          JSObject::AddProperty(
              isolate, object, "tables",
              GetOrCreateInstanceProxy<TablesProxy>(isolate, instance), FROZEN);
        }
        return Utils::ToLocal(object);
      }
      case debug::ScopeIterator::ScopeTypeLocal: {
        return Utils::ToLocal(LocalsProxy::Create(frame_));
      }
      case debug::ScopeIterator::ScopeTypeWasmExpressionStack: {
        auto object = isolate->factory()->NewSlowJSObjectWithNullProto();
        auto stack = StackProxy::Create(frame_);
        JSObject::AddProperty(isolate, object, "stack", stack, FROZEN);
        return Utils::ToLocal(object);
      }
      default:
        UNREACHABLE();
    }
  }
References v8::internal::JSObject::AddProperty(), v8::internal::Isolate::factory(), v8::internal::FROZEN, v8::internal::Factory::isolate(), v8::internal::Factory::NewSlowJSObjectWithNullProto(), v8::debug::ScopeIterator::ScopeTypeLocal, v8::debug::ScopeIterator::ScopeTypeModule, v8::debug::ScopeIterator::ScopeTypeWasmExpressionStack, v8::internal::stack, and v8::internal::UNREACHABLE().
GetScriptId()
int v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::GetScriptId () [inline], [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 736 of file debug-wasm-objects.cc.
{ return -1; }
GetStartLocation()
debug::Location v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::GetStartLocation () [inline], [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 740 of file debug-wasm-objects.cc.
{ return {}; }
GetType()
ScopeType v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::GetType () [inline], [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 680 of file debug-wasm-objects.cc.
{ return type_; }
HasLocationInfo()
bool v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::HasLocationInfo () [inline], [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 738 of file debug-wasm-objects.cc.
{ return false; }
SetVariableValue()
bool v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::SetVariableValue (v8::Local< v8::String > name, v8::Local< v8::Value > value) [inline], [override], [virtual]
Implements v8::debug::ScopeIterator.
Definition at line 744 of file debug-wasm-objects.cc.
                                                         {
    return false;
  }
Member Data Documentation
frame_
WasmFrame* const v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::frame_ [private]
Definition at line 750 of file debug-wasm-objects.cc.
type_
ScopeType v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::type_ [private]
Definition at line 751 of file debug-wasm-objects.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-wasm-objects.cc