v8::internal::compiler::MapInference Class Reference
#include <map-inference.h>
Public Member Functions
MapInference (JSHeapBroker *broker, Node *object, Effect effect)
~MapInference ()
V8_WARN_UNUSED_RESULT bool HaveMaps () const
V8_WARN_UNUSED_RESULT bool AllOfInstanceTypesAreJSReceiver () const
V8_WARN_UNUSED_RESULT bool AllOfInstanceTypesAre (InstanceType type) const
V8_WARN_UNUSED_RESULT bool AnyOfInstanceTypesAre (InstanceType type) const
V8_WARN_UNUSED_RESULT ZoneRefSet< Map > const & GetMaps ()
V8_WARN_UNUSED_RESULT bool AllOfInstanceTypes (std::function< bool(InstanceType)> f)
V8_WARN_UNUSED_RESULT bool Is (MapRef expected_map)
V8_WARN_UNUSED_RESULT bool RelyOnMapsViaStability (CompilationDependencies *dependencies)
bool RelyOnMapsPreferStability (CompilationDependencies *dependencies, JSGraph *jsgraph, Effect *effect, Control control, const FeedbackSource &feedback)
void InsertMapChecks (JSGraph *jsgraph, Effect *effect, Control control, const FeedbackSource &feedback)
V8_WARN_UNUSED_RESULT Reduction NoChange ()
Private Types
enum { kReliableOrGuarded
, kUnreliableDontNeedGuard
, kUnreliableNeedGuard
 }
Private Member Functions
bool Safe () const
void SetNeedGuardIfUnreliable ()
void SetGuarded ()
V8_WARN_UNUSED_RESULT bool AllOfInstanceTypesUnsafe (std::function< bool(InstanceType)> f) const
V8_WARN_UNUSED_RESULT bool AnyOfInstanceTypesUnsafe (std::function< bool(InstanceType)> f) const
V8_WARN_UNUSED_RESULT bool RelyOnMapsHelper (CompilationDependencies *dependencies, JSGraph *jsgraph, Effect *effect, Control control, const FeedbackSource &feedback)
Private Attributes
JSHeapBroker *const broker_
Node *const object_
ZoneRefSet< Map > maps_
enum v8::internal::compiler::MapInference:: { ... } maps_state_
Detailed Description
Definition at line 33 of file map-inference.h.
Member Enumeration Documentation
anonymous enum
anonymous enum [private]
Enumerator
kReliableOrGuarded
kUnreliableDontNeedGuard
kUnreliableNeedGuard
Definition at line 85 of file map-inference.h.
       {
    kReliableOrGuarded,
    kUnreliableDontNeedGuard,
    kUnreliableNeedGuard
  } maps_state_;
Constructor & Destructor Documentation
MapInference()
v8::internal::compiler::MapInference::MapInference (JSHeapBroker * broker, Node * object, Effect effect)
Definition at line 17 of file map-inference.cc.
    : broker_(broker), object_(object) {
  auto result =
      NodeProperties::InferMapsUnsafe(broker_, object_, effect, &maps_);
  maps_state_ = (result == NodeProperties::kUnreliableMaps)
                    ? kUnreliableDontNeedGuard
                    : kReliableOrGuarded;
  DCHECK_EQ(maps_.is_empty(), result == NodeProperties::kNoMaps);
}
References broker_, DCHECK_EQ, v8::internal::compiler::NodeProperties::InferMapsUnsafe(), v8::internal::compiler::NodeProperties::kNoMaps, kReliableOrGuarded, kUnreliableDontNeedGuard, v8::internal::compiler::NodeProperties::kUnreliableMaps, maps_, maps_state_, object_, and v8::base::internal::result.
 MapInference()
v8::internal::compiler::MapInference::~MapInference ()
Definition at line 27 of file map-inference.cc.
{ CHECK(Safe()); }
References CHECK, and Safe().
Member Function Documentation
AllOfInstanceTypes()
bool v8::internal::compiler::MapInference::AllOfInstanceTypes (std::function< bool(InstanceType)> f)
Definition at line 59 of file map-inference.cc.
                                                                       {
  SetNeedGuardIfUnreliable();
  return AllOfInstanceTypesUnsafe(f);
}
References AllOfInstanceTypesUnsafe(), and SetNeedGuardIfUnreliable().
AllOfInstanceTypesAre()
bool v8::internal::compiler::MapInference::AllOfInstanceTypesAre (InstanceType type) const
Definition at line 47 of file map-inference.cc.
                                                                {
  CHECK(!InstanceTypeChecker::IsString(type));
  return AllOfInstanceTypesUnsafe(
      [type](InstanceType other) { return type == other; });
}
References AllOfInstanceTypesUnsafe(), CHECK, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteOffsetAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteration(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeHas(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeSize(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetField(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetTime(), v8::internal::compiler::JSCallReducer::ReduceMapPrototypeGet(), v8::internal::compiler::JSCallReducer::ReduceStringIteratorPrototypeNext(), and v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength().
AllOfInstanceTypesAreJSReceiver()
bool v8::internal::compiler::MapInference::AllOfInstanceTypesAreJSReceiver () const
Definition at line 42 of file map-inference.cc.
                                                         {
  return AllOfInstanceTypesUnsafe(
      static_cast<bool (*)(InstanceType)>(&InstanceTypeChecker::IsJSReceiver));
}
References AllOfInstanceTypesUnsafe().
Referenced by v8::internal::compiler::NodeProperties::CanBePrimitive(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToObject(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeIsPrototypeOf(), and v8::internal::compiler::JSCallReducer::ReducePromiseResolveTrampoline().
AllOfInstanceTypesUnsafe()
bool v8::internal::compiler::MapInference::AllOfInstanceTypesUnsafe (std::function< bool(InstanceType)> f) const [private]
Definition at line 64 of file map-inference.cc.
                                             {
  CHECK(HaveMaps());
  auto instance_type = [f](MapRef map) { return f(map.instance_type()); };
  return std::all_of(maps_.begin(), maps_.end(), instance_type);
}
References v8::base::all_of(), CHECK, HaveMaps(), and maps_.
Referenced by AllOfInstanceTypes(), AllOfInstanceTypesAre(), and AllOfInstanceTypesAreJSReceiver().
AnyOfInstanceTypesAre()
bool v8::internal::compiler::MapInference::AnyOfInstanceTypesAre (InstanceType type) const
Definition at line 53 of file map-inference.cc.
                                                                {
  CHECK(!InstanceTypeChecker::IsString(type));
  return AnyOfInstanceTypesUnsafe(
      [type](InstanceType other) { return type == other; });
}
References AnyOfInstanceTypesUnsafe(), CHECK, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSPromiseResolve().
AnyOfInstanceTypesUnsafe()
bool v8::internal::compiler::MapInference::AnyOfInstanceTypesUnsafe (std::function< bool(InstanceType)> f) const [private]
Definition at line 72 of file map-inference.cc.
                                             {
  CHECK(HaveMaps());
  auto instance_type = [f](MapRef map) { return f(map.instance_type()); };
  return std::any_of(maps_.begin(), maps_.end(), instance_type);
}
References v8::base::any_of(), CHECK, HaveMaps(), and maps_.
Referenced by AnyOfInstanceTypesAre().
GetMaps()
ZoneRefSet< Map > const & v8::internal::compiler::MapInference::GetMaps ()
Definition at line 81 of file map-inference.cc.
                                             {
  SetNeedGuardIfUnreliable();
  return maps_;
}
References maps_, and SetNeedGuardIfUnreliable().
Referenced by v8::internal::compiler::JSCallReducer::DoPromiseChecks(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteOffsetAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeAt(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototype(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), and v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength().
HaveMaps()
bool v8::internal::compiler::MapInference::HaveMaps () const
Definition at line 40 of file map-inference.cc.
{ return !maps_.is_empty(); }
References maps_.
Referenced by AllOfInstanceTypesUnsafe(), AnyOfInstanceTypesUnsafe(), v8::internal::compiler::NodeProperties::CanBePrimitive(), v8::internal::compiler::JSCallReducer::DoPromiseChecks(), InsertMapChecks(), Is(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteOffsetAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeAt(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteration(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeHas(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeSize(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetField(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetTime(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSPromiseResolve(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToObject(), v8::internal::compiler::JSCallReducer::ReduceMapPrototypeGet(), v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototype(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeIsPrototypeOf(), v8::internal::compiler::JSCallReducer::ReducePromiseResolveTrampoline(), v8::internal::compiler::JSCallReducer::ReduceStringIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength(), RelyOnMapsPreferStability(), RelyOnMapsViaStability(), and SetNeedGuardIfUnreliable().
InsertMapChecks()
void v8::internal::compiler::MapInference::InsertMapChecks (JSGraph * jsgraph, Effect * effect, Control control, const FeedbackSource & feedback)
Definition at line 92 of file map-inference.cc.
                                                                   {
  CHECK(HaveMaps());
  CHECK(feedback.IsValid());
  *effect = jsgraph->graph()->NewNode(
      jsgraph->simplified()->CheckMaps(CheckMapsFlag::kNone, maps_, feedback),
      object_, *effect, control);
  SetGuarded();
}
References CHECK, v8::internal::compiler::SimplifiedOperatorBuilder::CheckMaps(), v8::internal::compiler::MachineGraph::graph(), HaveMaps(), v8::internal::compiler::FeedbackSource::IsValid(), v8::internal::compiler::kNone, maps_, v8::internal::compiler::TFGraph::NewNode(), object_, SetGuarded(), and v8::internal::compiler::JSGraph::simplified().
Referenced by v8::internal::compiler::JSCallReducerAssembler::MaybeInsertMapChecks(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), and RelyOnMapsHelper().
Is()
bool v8::internal::compiler::MapInference::Is (MapRef expected_map)
Definition at line 86 of file map-inference.cc.
                                         {
  if (!HaveMaps()) return false;
  if (maps_.size() != 1) return false;
  return maps_.at(0).equals(expected_map);
}
References HaveMaps(), and maps_.
Referenced by v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest().
NoChange()
Reduction v8::internal::compiler::MapInference::NoChange ()
Definition at line 141 of file map-inference.cc.
                                 {
  SetGuarded();
  maps_.clear(); // Just to make some CHECKs fail if {this} gets used after.
  return Reducer::NoChange();
}
References maps_, v8::internal::compiler::Reducer::NoChange(), and SetGuarded().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteOffsetAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototype(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), and v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength().
RelyOnMapsHelper()
bool v8::internal::compiler::MapInference::RelyOnMapsHelper (CompilationDependencies * dependencies, JSGraph * jsgraph, Effect * effect, Control control, const FeedbackSource & feedback) [private]
Definition at line 119 of file map-inference.cc.
                                                                    {
  if (Safe()) return true;
  auto is_stable = [](MapRef map) { return map.is_stable(); };
  if (dependencies != nullptr &&
      std::all_of(maps_.begin(), maps_.end(), is_stable)) {
    for (MapRef map : maps_) {
      dependencies->DependOnStableMap(map);
    }
    SetGuarded();
    return true;
  } else if (feedback.IsValid()) {
    InsertMapChecks(jsgraph, effect, control, feedback);
    return true;
  } else {
    return false;
  }
}
References v8::base::all_of(), v8::internal::compiler::CompilationDependencies::DependOnStableMap(), InsertMapChecks(), v8::internal::compiler::FeedbackSource::IsValid(), maps_, Safe(), and SetGuarded().
Referenced by RelyOnMapsPreferStability(), and RelyOnMapsViaStability().
RelyOnMapsPreferStability()
bool v8::internal::compiler::MapInference::RelyOnMapsPreferStability (CompilationDependencies * dependencies, JSGraph * jsgraph, Effect * effect, Control control, const FeedbackSource & feedback)
Definition at line 109 of file map-inference.cc.
                                                     {
  CHECK(HaveMaps());
  if (Safe()) return false;
  if (RelyOnMapsViaStability(dependencies)) return true;
  CHECK(RelyOnMapsHelper(nullptr, jsgraph, effect, control, feedback));
  return false;
}
References CHECK, HaveMaps(), RelyOnMapsHelper(), RelyOnMapsViaStability(), and Safe().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeAt(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), and v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest().
RelyOnMapsViaStability()
bool v8::internal::compiler::MapInference::RelyOnMapsViaStability (CompilationDependencies * dependencies)
Definition at line 103 of file map-inference.cc.
                                           {
  CHECK(HaveMaps());
  return RelyOnMapsHelper(dependencies, nullptr, nullptr, Control{nullptr}, {});
}
References CHECK, HaveMaps(), and RelyOnMapsHelper().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototype(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength(), and RelyOnMapsPreferStability().
Safe()
bool v8::internal::compiler::MapInference::Safe () const [private]
Definition at line 29 of file map-inference.cc.
{ return maps_state_ != kUnreliableNeedGuard; }
References kUnreliableNeedGuard, and maps_state_.
Referenced by RelyOnMapsHelper(), RelyOnMapsPreferStability(), and ~MapInference().
SetGuarded()
void v8::internal::compiler::MapInference::SetGuarded () [private]
Definition at line 38 of file map-inference.cc.
{ maps_state_ = kReliableOrGuarded; }
References kReliableOrGuarded, and maps_state_.
Referenced by InsertMapChecks(), NoChange(), and RelyOnMapsHelper().
SetNeedGuardIfUnreliable()
void v8::internal::compiler::MapInference::SetNeedGuardIfUnreliable () [private]
Definition at line 31 of file map-inference.cc.
                                            {
  CHECK(HaveMaps());
  if (maps_state_ == kUnreliableDontNeedGuard) {
    maps_state_ = kUnreliableNeedGuard;
  }
}
References CHECK, HaveMaps(), kUnreliableDontNeedGuard, kUnreliableNeedGuard, and maps_state_.
Referenced by AllOfInstanceTypes(), and GetMaps().
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::MapInference::broker_ [private]
Definition at line 81 of file map-inference.h.
Referenced by MapInference().
maps_
ZoneRefSet<Map> v8::internal::compiler::MapInference::maps_ [private]
Definition at line 84 of file map-inference.h.
Referenced by AllOfInstanceTypesUnsafe(), AnyOfInstanceTypesUnsafe(), GetMaps(), HaveMaps(), InsertMapChecks(), Is(), MapInference(), NoChange(), and RelyOnMapsHelper().
enum { ... } v8::internal::compiler::MapInference::maps_state_ [private]
Referenced by MapInference(), Safe(), SetGuarded(), and SetNeedGuardIfUnreliable().
object_
Node* const v8::internal::compiler::MapInference::object_ [private]
Definition at line 82 of file map-inference.h.
Referenced by InsertMapChecks(), and MapInference().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/map-inference.h
/mnt/V8SourceCode/src/compiler/map-inference.cc