v8::internal::ProtectedWeakFixedArray Class Reference
#include <fixed-array.h>
Classes
class BodyDescriptor
Static Public Member Functions
template<class IsolateT >
static Handle< ProtectedWeakFixedArray > New (IsolateT *isolate, int capacity)
Private Types
using Super = TaggedArrayBase< ProtectedWeakFixedArray, ProtectedWeakFixedArrayShape, TrustedObjectLayout >
Additional Inherited Members
Detailed Description
Definition at line 561 of file fixed-array.h.
Member Typedef Documentation
Super
using v8::internal::ProtectedWeakFixedArray::Super = TaggedArrayBase<ProtectedWeakFixedArray, ProtectedWeakFixedArrayShape, TrustedObjectLayout> [private]
Definition at line 565 of file fixed-array.h.
Member Function Documentation
New()
template<class IsolateT >
Handle< ProtectedWeakFixedArray > v8::internal::ProtectedWeakFixedArray::New (IsolateT * isolate, int capacity) [inline], [static]
Definition at line 661 of file fixed-array-inl.h.
                                                                           {
  if (V8_UNLIKELY(static_cast<unsigned>(capacity) >
                  TrustedFixedArray::kMaxLength)) {
    FATAL("Fatal JavaScript invalid size error %d (see crbug.com/1201626)",
          capacity);
  }
  std::optional<DisallowGarbageCollection> no_gc;
  Handle<ProtectedWeakFixedArray> result = Cast<ProtectedWeakFixedArray>(
      Allocate(isolate, capacity, &no_gc, AllocationType::kTrusted));
  MemsetTagged((*result)->RawFieldOfFirstElement(), Smi::zero(), capacity);
  return result;
}
References v8::internal::TaggedArrayBase< ProtectedWeakFixedArray, ProtectedWeakFixedArrayShape, TrustedObjectLayout >::Allocate(), FATAL, v8::internal::TrustedFixedArray::kMaxLength, v8::internal::kTrusted, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, V8_UNLIKELY, and v8::internal::Smi::zero().
Referenced by v8::internal::Heap::CreateInitialMutableObjects().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h