v8::internal::torque::StructType Class Reference
#include <types.h>
Public Types
enum class ClassificationFlag { kEmpty = 0
, kStrongTagged = 1 << 0
, kWeakTagged = 1 << 1
, kUntagged = 1 << 2
 }
using Classification = base::Flags< ClassificationFlag >
Public Member Functions
std::string GetGeneratedTypeNameImpl () const override
size_t PackedSize () const
size_t AlignmentLog2 () const override
Classification ClassifyContents () const
SourcePosition GetPosition () const
Private Member Functions
StructType (Namespace *nspace, const StructDeclaration *decl, MaybeSpecializationKey specialized_from=std::nullopt)
void Finalize () const override
std::string ToExplicitString () const override
std::string SimpleNameImpl () const override
Private Attributes
const StructDeclaration * decl_
std::string generated_type_name_
Friends
class TypeOracle
Additional Inherited Members
Detailed Description
Definition at line 616 of file types.h.
Member Typedef Documentation
Classification
using v8::internal::torque::StructType::Classification = base::Flags<ClassificationFlag>
Definition at line 633 of file types.h.
Member Enumeration Documentation
ClassificationFlag
enum v8::internal::torque::StructType::ClassificationFlag [strong]
Enumerator
kEmpty
kStrongTagged
kWeakTagged
kUntagged
Definition at line 627 of file types.h.
                                {
    kEmpty = 0,
    kStrongTagged = 1 << 0,
    kWeakTagged = 1 << 1,
    kUntagged = 1 << 2,
  };
Constructor & Destructor Documentation
StructType()
v8::internal::torque::StructType::StructType (Namespace * nspace, const StructDeclaration * decl, MaybeSpecializationKey specialized_from = std::nullopt) [private]
Definition at line 504 of file types.cc.
    : AggregateType(Kind::kStructType, nullptr, nspace, decl->name->value,
                    specialized_from),
      decl_(decl) {
  if (decl->flags & StructFlag::kExport) {
    generated_type_name_ = "TorqueStruct" + name();
  } else {
    generated_type_name_ =
        GlobalContext::MakeUniqueName("TorqueStruct" + SimpleName());
  }
}
References v8::internal::torque::StructDeclaration::flags, generated_type_name_, v8::internal::torque::kExport, v8::internal::torque::GlobalContext::MakeUniqueName(), v8::internal::torque::AggregateType::name(), and v8::internal::torque::Type::SimpleName().
Member Function Documentation
AlignmentLog2()
size_t v8::internal::torque::StructType::AlignmentLog2 () const [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 1305 of file types.cc.
                                       {
  if (this == TypeOracle::GetFloat64OrUndefinedOrHoleType()) {
    return TypeOracle::GetFloat64Type()->AlignmentLog2();
  }
  size_t alignment_log_2 = 0;
  for (const Field& field : fields()) {
    alignment_log_2 =
        std::max(alignment_log_2, field.name_and_type.type->AlignmentLog2());
  }
  return alignment_log_2;
}
References v8::internal::torque::Type::AlignmentLog2(), v8::internal::torque::AggregateType::fields(), v8::internal::torque::TypeOracle::GetFloat64OrUndefinedOrHoleType(), and v8::internal::torque::TypeOracle::GetFloat64Type().
ClassifyContents()
StructType::Classification v8::internal::torque::StructType::ClassifyContents () const
Definition at line 529 of file types.cc.
                                                            {
  Classification result = ClassificationFlag::kEmpty;
  for (const Field& struct_field : fields()) {
    const Type* field_type = struct_field.name_and_type.type;
    if (field_type->IsSubtypeOf(TypeOracle::GetStrongTaggedType())) {
      result |= ClassificationFlag::kStrongTagged;
    } else if (field_type->IsSubtypeOf(TypeOracle::GetTaggedType())) {
      result |= ClassificationFlag::kWeakTagged;
    } else if (auto field_as_struct = field_type->StructSupertype()) {
      result |= (*field_as_struct)->ClassifyContents();
    } else {
      result |= ClassificationFlag::kUntagged;
    }
  }
  return result;
}
References v8::internal::torque::AggregateType::fields(), v8::internal::torque::TypeOracle::GetStrongTaggedType(), v8::internal::torque::TypeOracle::GetTaggedType(), v8::internal::torque::Type::IsSubtypeOf(), kEmpty, kStrongTagged, kUntagged, kWeakTagged, v8::base::internal::result, and v8::internal::torque::Type::StructSupertype().
Finalize()
void v8::internal::torque::StructType::Finalize () const [override], [private], [virtual]
Implements v8::internal::torque::AggregateType.
Definition at line 601 of file types.cc.
                                {
  if (is_finalized_) return;
  {
    CurrentScope::Scope scope_activator(nspace());
    CurrentSourcePosition::Scope position_activator(decl_->pos);
    TypeVisitor::VisitStructMethods(const_cast<StructType*>(this), decl_);
  }
  is_finalized_ = true;
  CheckForDuplicateFields();
}
References v8::internal::torque::AggregateType::CheckForDuplicateFields(), decl_, v8::internal::torque::AggregateType::is_finalized_, v8::internal::torque::AggregateType::nspace(), v8::internal::torque::AstNode::pos, and v8::internal::torque::TypeVisitor::VisitStructMethods().
GetGeneratedTypeNameImpl()
std::string v8::internal::torque::StructType::GetGeneratedTypeNameImpl () const [override], [virtual]
Reimplemented from v8::internal::torque::AggregateType.
Definition at line 517 of file types.cc.
                                                     {
  return generated_type_name_;
}
References generated_type_name_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCSATypes().
GetPosition()
SourcePosition v8::internal::torque::StructType::GetPosition () const [inline]
Definition at line 638 of file types.h.
{ return decl_->pos; }
References decl_, and v8::internal::torque::AstNode::pos.
PackedSize()
size_t v8::internal::torque::StructType::PackedSize () const
Definition at line 521 of file types.cc.
                                    {
  size_t result = 0;
  for (const Field& field : fields()) {
    result += std::get<0>(field.GetFieldSizeInformation());
  }
  return result;
}
References v8::internal::torque::AggregateType::fields(), and v8::base::internal::result.
SimpleNameImpl()
std::string v8::internal::torque::StructType::SimpleNameImpl () const [override], [private], [virtual]
Reimplemented from v8::internal::torque::AggregateType.
Definition at line 570 of file types.cc.
{ return decl_->name->value; }
References decl_, v8::internal::torque::TypeDeclaration::name, and v8::internal::torque::Identifier::value.
ToExplicitString()
std::string v8::internal::torque::StructType::ToExplicitString () const [override], [private], [virtual]
Implements v8::internal::torque::Type.
Definition at line 599 of file types.cc.
{ return "struct " + name(); }
References v8::internal::torque::AggregateType::name().
Friends And Related Function Documentation
TypeOracle
friend class TypeOracle [friend]
Definition at line 641 of file types.h.
Member Data Documentation
decl_
const StructDeclaration* v8::internal::torque::StructType::decl_ [private]
Definition at line 649 of file types.h.
Referenced by Finalize(), GetPosition(), and SimpleNameImpl().
generated_type_name_
std::string v8::internal::torque::StructType::generated_type_name_ [private]
Definition at line 650 of file types.h.
Referenced by GetGeneratedTypeNameImpl(), and StructType().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/types.h
/mnt/V8SourceCode/src/torque/types.cc