v8::internal::ScheduleMinorGCTaskObserver Class Reference
Public Member Functions
ScheduleMinorGCTaskObserver (MinorGCJob *job, Heap *heap)
~ScheduleMinorGCTaskObserver () final
intptr_t GetNextStepSize () final
void Step (int, Address, size_t) final
Private Member Functions
void AddToNewSpace ()
void RemoveFromNewSpace ()
Static Private Member Functions
static void GCEpilogueCallback (void *data)
Private Attributes
Heap * heap_
MinorGCJob *const job_
bool was_added_to_space_ = false
Additional Inherited Members
Detailed Description
Definition at line 55 of file minor-gc-job.cc.
Constructor & Destructor Documentation
ScheduleMinorGCTaskObserver()
v8::internal::ScheduleMinorGCTaskObserver::ScheduleMinorGCTaskObserver (MinorGCJob * job, Heap * heap) [inline]
Definition at line 57 of file minor-gc-job.cc.
      : AllocationObserver(kNotUsingFixedStepSize), heap_(heap), job_(job) {
    // Register GC callback for all atomic pause types.
    heap_->main_thread_local_heap()->AddGCEpilogueCallback(
        &GCEpilogueCallback, this, GCCallbacksInSafepoint::GCType::kLocal);
    AddToNewSpace();
  }
References v8::internal::LocalHeap::AddGCEpilogueCallback(), AddToNewSpace(), GCEpilogueCallback(), heap_, and v8::internal::Heap::main_thread_local_heap().
 ScheduleMinorGCTaskObserver()
v8::internal::ScheduleMinorGCTaskObserver::~ScheduleMinorGCTaskObserver () [inline], [final]
Definition at line 65 of file minor-gc-job.cc.
                                       {
    RemoveFromNewSpace();
    heap_->main_thread_local_heap()->RemoveGCEpilogueCallback(
        &GCEpilogueCallback, this);
  }
References GCEpilogueCallback(), heap_, v8::internal::Heap::main_thread_local_heap(), RemoveFromNewSpace(), and v8::internal::LocalHeap::RemoveGCEpilogueCallback().
Member Function Documentation
AddToNewSpace()
void v8::internal::ScheduleMinorGCTaskObserver::AddToNewSpace () [inline], [private]
Definition at line 97 of file minor-gc-job.cc.
                       {
    DCHECK(!was_added_to_space_);
    DCHECK_IMPLIES(v8_flags.minor_ms,
                   !heap_->allocator()->new_space_allocator()->IsLabValid());
    heap_->allocator()->new_space_allocator()->AddAllocationObserver(this);
    was_added_to_space_ = true;
  }
References v8::internal::MainAllocator::AddAllocationObserver(), v8::internal::Heap::allocator(), v8::internal::DCHECK(), DCHECK_IMPLIES, heap_, v8::internal::MainAllocator::IsLabValid(), v8::internal::HeapAllocator::new_space_allocator(), v8::internal::v8_flags, and was_added_to_space_.
Referenced by GCEpilogueCallback(), and ScheduleMinorGCTaskObserver().
GCEpilogueCallback()
static void v8::internal::ScheduleMinorGCTaskObserver::GCEpilogueCallback (void * data) [inline], [static], [private]
Definition at line 90 of file minor-gc-job.cc.
                                             {
    ScheduleMinorGCTaskObserver* observer =
        reinterpret_cast<ScheduleMinorGCTaskObserver*>(data);
    observer->RemoveFromNewSpace();
    observer->AddToNewSpace();
  }
References AddToNewSpace(), and RemoveFromNewSpace().
Referenced by ScheduleMinorGCTaskObserver(), and ~ScheduleMinorGCTaskObserver().
GetNextStepSize()
intptr_t v8::internal::ScheduleMinorGCTaskObserver::GetNextStepSize () [inline], [final], [virtual]
Reimplemented from v8::internal::AllocationObserver.
Definition at line 71 of file minor-gc-job.cc.
                                   {
    const size_t new_space_threshold = YoungGenerationTaskTriggerSize(heap_);
    const size_t new_space_size = YoungGenerationSize(heap_);
    if (new_space_size < new_space_threshold) {
      return new_space_threshold - new_space_size;
    }
    // Force a step on next allocation.
    return 1;
  }
References heap_, v8::internal::anonymous_namespace{minor-gc-job.cc}::YoungGenerationSize(), and v8::internal::anonymous_namespace{minor-gc-job.cc}::YoungGenerationTaskTriggerSize().
RemoveFromNewSpace()
void v8::internal::ScheduleMinorGCTaskObserver::RemoveFromNewSpace () [inline], [private]
Definition at line 105 of file minor-gc-job.cc.
                            {
    if (!was_added_to_space_) {
      return;
    }
    heap_->allocator()->new_space_allocator()->RemoveAllocationObserver(this);
    was_added_to_space_ = false;
  }
References v8::internal::Heap::allocator(), heap_, v8::internal::HeapAllocator::new_space_allocator(), v8::internal::MainAllocator::RemoveAllocationObserver(), and was_added_to_space_.
Referenced by GCEpilogueCallback(), and ~ScheduleMinorGCTaskObserver().
Step()
void v8::internal::ScheduleMinorGCTaskObserver::Step (int , Address , size_t) [inline], [final], [virtual]
Implements v8::internal::AllocationObserver.
Definition at line 81 of file minor-gc-job.cc.
                                        {
    job_->TryScheduleTask();
    // Remove this observer. It will be re-added after a GC.
    heap_->allocator()->new_space_allocator()->RemoveAllocationObserver(this);
    DCHECK(was_added_to_space_);
    was_added_to_space_ = false;
  }
References v8::internal::Heap::allocator(), v8::internal::DCHECK(), heap_, job_, v8::internal::HeapAllocator::new_space_allocator(), v8::internal::MainAllocator::RemoveAllocationObserver(), v8::internal::MinorGCJob::TryScheduleTask(), and was_added_to_space_.
Member Data Documentation
heap_
Heap* v8::internal::ScheduleMinorGCTaskObserver::heap_ [private]
Definition at line 113 of file minor-gc-job.cc.
Referenced by AddToNewSpace(), GetNextStepSize(), RemoveFromNewSpace(), ScheduleMinorGCTaskObserver(), Step(), and ~ScheduleMinorGCTaskObserver().
job_
MinorGCJob* const v8::internal::ScheduleMinorGCTaskObserver::job_ [private]
Definition at line 114 of file minor-gc-job.cc.
Referenced by Step().
was_added_to_space_
bool v8::internal::ScheduleMinorGCTaskObserver::was_added_to_space_ = false [private]
Definition at line 115 of file minor-gc-job.cc.
Referenced by AddToNewSpace(), RemoveFromNewSpace(), and Step().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/minor-gc-job.cc