v8::internal::RegExpGroup Class Reference
#include <regexp-ast.h>
Public Member Functions
RegExpGroup (RegExpTree *body, RegExpFlags flags)
DECL_BOILERPLATE (Group)
bool IsAnchoredAtStart () override
bool IsAnchoredAtEnd () override
int min_match () override
int max_match () override
Interval CaptureRegisters () override
RegExpTree * body () const
RegExpFlags flags () const
Private Attributes
RegExpTree * body_
const RegExpFlags flags_
int min_match_
int max_match_
Additional Inherited Members
Detailed Description
Definition at line 635 of file regexp-ast.h.
Constructor & Destructor Documentation
RegExpGroup()
v8::internal::RegExpGroup::RegExpGroup (RegExpTree * body, RegExpFlags flags) [inline], [explicit]
Definition at line 637 of file regexp-ast.h.
      : body_(body),
        flags_(flags),
        min_match_(body->min_match()),
        max_match_(body->max_match()) {}
Member Function Documentation
body()
RegExpTree* v8::internal::RegExpGroup::body () const [inline]
Definition at line 650 of file regexp-ast.h.
{ return body_; }
References body_.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitGroup(), v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitGroup(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitGroup().
CaptureRegisters()
Interval v8::internal::RegExpGroup::CaptureRegisters () [inline], [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 649 of file regexp-ast.h.
{ return body_->CaptureRegisters(); }
References body_, and v8::internal::RegExpTree::CaptureRegisters().
DECL_BOILERPLATE()
v8::internal::RegExpGroup::DECL_BOILERPLATE (Group)
flags()
RegExpFlags v8::internal::RegExpGroup::flags () const [inline]
Definition at line 651 of file regexp-ast.h.
{ return flags_; }
References flags_.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitGroup().
IsAnchoredAtEnd()
bool v8::internal::RegExpGroup::IsAnchoredAtEnd () [inline], [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 646 of file regexp-ast.h.
{ return body_->IsAnchoredAtEnd(); }
References body_, and v8::internal::RegExpTree::IsAnchoredAtEnd().
IsAnchoredAtStart()
bool v8::internal::RegExpGroup::IsAnchoredAtStart () [inline], [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 645 of file regexp-ast.h.
{ return body_->IsAnchoredAtStart(); }
References body_, and v8::internal::RegExpTree::IsAnchoredAtStart().
max_match()
int v8::internal::RegExpGroup::max_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 648 of file regexp-ast.h.
{ return max_match_; }
References max_match_.
min_match()
int v8::internal::RegExpGroup::min_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 647 of file regexp-ast.h.
{ return min_match_; }
References min_match_.
Member Data Documentation
body_
RegExpTree* v8::internal::RegExpGroup::body_ [private]
Definition at line 654 of file regexp-ast.h.
Referenced by body(), CaptureRegisters(), IsAnchoredAtEnd(), and IsAnchoredAtStart().
flags_
const RegExpFlags v8::internal::RegExpGroup::flags_ [private]
Definition at line 655 of file regexp-ast.h.
Referenced by flags().
max_match_
int v8::internal::RegExpGroup::max_match_ [private]
Definition at line 657 of file regexp-ast.h.
Referenced by max_match().
min_match_
int v8::internal::RegExpGroup::min_match_ [private]
Definition at line 656 of file regexp-ast.h.
Referenced by min_match().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-ast.h