v8::internal::VTuneDomainSupportExtension Class Reference
#include <vtunedomain-support-extension.h>
Public Member Functions
VTuneDomainSupportExtension (const char *fun_name=`test`)
v8::Local< v8::FunctionTemplate > GetNativeFunctionTemplate (v8::Isolate *isolate, v8::Local< v8::String > name) override
Static Private Member Functions
static void Mark (const v8::FunctionCallbackInfo< v8::Value > &info)
static const char * BuildSource (char *buf, size_t size, const char *fun_name)
Private Attributes
char buffer_ [50]
Detailed Description
Definition at line 28 of file vtunedomain-support-extension.h.
Constructor & Destructor Documentation
VTuneDomainSupportExtension()
v8::internal::VTuneDomainSupportExtension::VTuneDomainSupportExtension (const char * fun_name = `test`) [inline], [explicit]
Definition at line 30 of file vtunedomain-support-extension.h.
      : v8::Extension("v8/vtunedomain",
                      BuildSource(buffer_, sizeof(buffer_), fun_name)) {}
Member Function Documentation
BuildSource()
static const char* v8::internal::VTuneDomainSupportExtension::BuildSource (char * buf, size_t size, const char * fun_name) [inline], [static], [private]
Definition at line 40 of file vtunedomain-support-extension.h.
                                                                               {
    base::SNPrintF(base::VectorOf(buf, size), "native function %s();",
                   fun_name);
    return buf;
  }
References size(), v8::base::SNPrintF(), and v8::base::VectorOf().
GetNativeFunctionTemplate()
v8::Local< v8::FunctionTemplate > v8::internal::VTuneDomainSupportExtension::GetNativeFunctionTemplate (v8::Isolate * isolate, v8::Local< v8::String > name) [override], [virtual]
Reimplemented from v8::Extension.
Definition at line 100 of file vtunedomain-support-extension.cc.
                                               {
  return v8::FunctionTemplate::New(isolate, VTuneDomainSupportExtension::Mark);
}
References Mark(), and v8::FunctionTemplate::New().
Mark()
void v8::internal::VTuneDomainSupportExtension::Mark (const v8::FunctionCallbackInfo< v8::Value > & info) [static], [private]
Definition at line 112 of file vtunedomain-support-extension.cc.
                                                 {
  if (info.Length() != 3 || !info[0]->IsString() || !info[1]->IsString() ||
      !info[2]->IsString()) {
    info.GetIsolate()->ThrowError(
        "Parameter number should be exactly three, first domain name"
        "second task name, third start/end");
    return;
  }
  v8::Isolate* isolate = info.GetIsolate();
  v8::String::Utf8Value domainName(isolate, info[0]);
  v8::String::Utf8Value taskName(isolate, info[1]);
  v8::String::Utf8Value statName(isolate, info[2]);
  char* cdomainName = *domainName;
  char* ctaskName = *taskName;
  char* cstatName = *statName;
  std::stringstream params;
  params << cstatName << " " << cdomainName << " " << ctaskName;
  int r = 0;
  if ((r = libvtune::invoke(params.str().c_str())) != 0) {
    info.GetIsolate()->ThrowError(
        v8::String::NewFromUtf8(info.GetIsolate(), std::to_string(r).c_str())
            .ToLocalChecked());
  }
}
References v8::FunctionCallbackInfo< T >::GetIsolate(), v8::internal::libvtune::invoke(), v8::FunctionCallbackInfo< T >::Length(), v8::String::NewFromUtf8(), and v8::Isolate::ThrowError().
Referenced by GetNativeFunctionTemplate().
Member Data Documentation
buffer_
char v8::internal::VTuneDomainSupportExtension::buffer_[50] [private]
Definition at line 46 of file vtunedomain-support-extension.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/extensions/vtunedomain-support-extension.h
/mnt/V8SourceCode/src/extensions/vtunedomain-support-extension.cc