v8::internal::RegExpLookaround Class Reference
#include <regexp-ast.h>
Classes
class Builder
Public Types
enum Type { LOOKAHEAD
, LOOKBEHIND
 }
Public Member Functions
RegExpLookaround (RegExpTree *body, bool is_positive, int capture_count, int capture_from, Type type, int index)
DECL_BOILERPLATE (Lookaround)
Interval CaptureRegisters () override
bool IsAnchoredAtStart () override
int min_match () override
int max_match () override
RegExpTree * body () const
bool is_positive () const
int capture_count () const
int capture_from () const
Type type () const
int index () const
Private Attributes
RegExpTree * body_
bool is_positive_
int capture_count_
int capture_from_
Type type_
int index_
Additional Inherited Members
Detailed Description
Definition at line 660 of file regexp-ast.h.
Member Enumeration Documentation
Type
enum v8::internal::RegExpLookaround::Type
Enumerator
LOOKAHEAD
LOOKBEHIND
Definition at line 662 of file regexp-ast.h.
{ LOOKAHEAD, LOOKBEHIND };
Constructor & Destructor Documentation
RegExpLookaround()
v8::internal::RegExpLookaround::RegExpLookaround (RegExpTree * body, bool is_positive, int capture_count, int capture_from, Type type, int index) [inline]
Definition at line 664 of file regexp-ast.h.
      : body_(body),
        is_positive_(is_positive),
        capture_count_(capture_count),
        capture_from_(capture_from),
        type_(type),
        index_(index) {}
Member Function Documentation
body()
RegExpTree* v8::internal::RegExpLookaround::body () const [inline]
Definition at line 679 of file regexp-ast.h.
{ return body_; }
References body_.
Referenced by CaptureRegisters(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileLookaround(), IsAnchoredAtStart(), v8::internal::RegExpCapture::ToNode(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitLookaround(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitLookaround().
capture_count()
int v8::internal::RegExpLookaround::capture_count () const [inline]
Definition at line 681 of file regexp-ast.h.
{ return capture_count_; }
References capture_count_.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileLookaround(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitLookaround().
capture_from()
int v8::internal::RegExpLookaround::capture_from () const [inline]
Definition at line 682 of file regexp-ast.h.
{ return capture_from_; }
References capture_from_.
CaptureRegisters()
Interval v8::internal::RegExpLookaround::CaptureRegisters () [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 53 of file regexp-ast.cc.
                                            {
  return body()->CaptureRegisters();
}
References body(), and v8::internal::RegExpTree::CaptureRegisters().
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitLookaround().
DECL_BOILERPLATE()
v8::internal::RegExpLookaround::DECL_BOILERPLATE (Lookaround)
index()
int v8::internal::RegExpLookaround::index () const [inline]
Definition at line 684 of file regexp-ast.h.
{ return index_; }
References index_.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileLookaround(), v8::internal::RegExpCapture::ToNode(), v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitLookaround(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitLookaround().
is_positive()
bool v8::internal::RegExpLookaround::is_positive () const [inline]
Definition at line 680 of file regexp-ast.h.
{ return is_positive_; }
References is_positive_.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileLookaround(), IsAnchoredAtStart(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitLookaround().
IsAnchoredAtStart()
bool v8::internal::RegExpLookaround::IsAnchoredAtStart () [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 127 of file regexp-ast.cc.
                                         {
  return is_positive() && type() == LOOKAHEAD && body()->IsAnchoredAtStart();
}
References body(), is_positive(), v8::internal::RegExpTree::IsAnchoredAtStart(), LOOKAHEAD, and type().
max_match()
int v8::internal::RegExpLookaround::max_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 678 of file regexp-ast.h.
{ return 0; }
min_match()
int v8::internal::RegExpLookaround::min_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 677 of file regexp-ast.h.
{ return 0; }
type()
Type v8::internal::RegExpLookaround::type () const [inline]
Definition at line 683 of file regexp-ast.h.
{ return type_; }
References type_.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileLookaround(), IsAnchoredAtStart(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitLookaround(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitLookaround().
Member Data Documentation
body_
RegExpTree* v8::internal::RegExpLookaround::body_ [private]
Definition at line 703 of file regexp-ast.h.
Referenced by body().
capture_count_
int v8::internal::RegExpLookaround::capture_count_ [private]
Definition at line 705 of file regexp-ast.h.
Referenced by capture_count().
capture_from_
int v8::internal::RegExpLookaround::capture_from_ [private]
Definition at line 706 of file regexp-ast.h.
Referenced by capture_from().
index_
int v8::internal::RegExpLookaround::index_ [private]
Definition at line 708 of file regexp-ast.h.
Referenced by index().
is_positive_
bool v8::internal::RegExpLookaround::is_positive_ [private]
Definition at line 704 of file regexp-ast.h.
Referenced by v8::internal::RegExpLookaround::Builder::ForMatch(), and is_positive().
type_
Type v8::internal::RegExpLookaround::type_ [private]
Definition at line 707 of file regexp-ast.h.
Referenced by type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-ast.cc