v8::internal::compiler::AccessBuilder Class Reference
#include <access-builder.h>
Static Public Member Functions
static FieldAccess ForExternalIntPtr ()
static FieldAccess ForMap (WriteBarrierKind write_barrier=kMapWriteBarrier)
static FieldAccess ForHeapNumberValue ()
static FieldAccess ForContextCellState ()
static FieldAccess ForContextCellTaggedValue ()
static FieldAccess ForContextCellInt32Value ()
static FieldAccess ForContextCellFloat64Value ()
static FieldAccess ForHeapNumberOrOddballOrHoleValue ()
static FieldAccess ForBigIntBitfield ()
static FieldAccess ForBigIntLeastSignificantDigit64 ()
static FieldAccess ForJSObjectPropertiesOrHash ()
static FieldAccess ForJSObjectPropertiesOrHashKnownPointer ()
static FieldAccess ForJSObjectElements ()
static FieldAccess ForJSObjectInObjectProperty (MapRef map, int index, MachineType machine_type=MachineType::AnyTagged())
static FieldAccess ForJSObjectOffset (int offset, WriteBarrierKind write_barrier_kind=kFullWriteBarrier)
static FieldAccess ForJSCollectionTable ()
static FieldAccess ForJSCollectionIteratorTable ()
static FieldAccess ForJSCollectionIteratorIndex ()
static FieldAccess ForJSExternalObjectValue ()
static FieldAccess ForJSFunctionPrototypeOrInitialMap ()
static FieldAccess ForJSFunctionContext ()
static FieldAccess ForJSFunctionSharedFunctionInfo ()
static FieldAccess ForJSFunctionFeedbackCell ()
static FieldAccess ForJSFunctionCode ()
static FieldAccess ForJSBoundFunctionBoundTargetFunction ()
static FieldAccess ForJSBoundFunctionBoundThis ()
static FieldAccess ForJSBoundFunctionBoundArguments ()
static FieldAccess ForJSGeneratorObjectContext ()
static FieldAccess ForJSGeneratorObjectContinuation ()
static FieldAccess ForJSGeneratorObjectInputOrDebugPos ()
static FieldAccess ForJSGeneratorObjectParametersAndRegisters ()
static FieldAccess ForJSGeneratorObjectFunction ()
static FieldAccess ForJSGeneratorObjectReceiver ()
static FieldAccess ForJSGeneratorObjectResumeMode ()
static FieldAccess ForJSAsyncFunctionObjectPromise ()
static FieldAccess ForJSAsyncGeneratorObjectQueue ()
static FieldAccess ForJSAsyncGeneratorObjectIsAwaiting ()
static FieldAccess ForJSArrayLength (ElementsKind elements_kind)
static FieldAccess ForJSArrayBufferBitField ()
static FieldAccess ForJSArrayBufferByteLength ()
static FieldAccess ForJSArrayBufferViewBuffer ()
static FieldAccess ForJSArrayBufferViewByteLength ()
static FieldAccess ForJSArrayBufferViewByteOffset ()
static FieldAccess ForJSArrayBufferViewBitField ()
static FieldAccess ForJSTypedArrayByteLength ()
static FieldAccess ForJSTypedArrayBasePointer ()
static FieldAccess ForJSTypedArrayExternalPointer ()
static FieldAccess ForJSDataViewDataPointer ()
static FieldAccess ForJSDataViewByteLength ()
static FieldAccess ForJSDateValue ()
static FieldAccess ForJSDateField (JSDate::FieldIndex index)
static FieldAccess ForJSIteratorResultDone ()
static FieldAccess ForJSIteratorResultValue ()
static FieldAccess ForJSPrimitiveWrapperValue ()
static FieldAccess ForJSRegExpData ()
static FieldAccess ForJSRegExpFlags ()
static FieldAccess ForJSRegExpLastIndex ()
static FieldAccess ForJSRegExpSource ()
static FieldAccess ForFixedArrayLength ()
static FieldAccess ForWeakFixedArrayLength ()
static FieldAccess ForSloppyArgumentsElementsContext ()
static FieldAccess ForSloppyArgumentsElementsArguments ()
static FieldAccess ForPropertyArrayLengthAndHash ()
static FieldAccess ForDescriptorArrayEnumCache ()
static FieldAccess ForMapBitField ()
static FieldAccess ForMapBitField2 ()
static FieldAccess ForMapBitField3 ()
static FieldAccess ForMapDescriptors ()
static FieldAccess ForMapInstanceType ()
static FieldAccess ForMapPrototype ()
static FieldAccess ForMapNativeContext ()
static FieldAccess ForModuleRegularExports ()
static FieldAccess ForModuleRegularImports ()
static FieldAccess ForNameRawHashField ()
static FieldAccess ForStringLength ()
static FieldAccess ForConsStringFirst ()
static FieldAccess ForConsStringSecond ()
static FieldAccess ForThinStringActual ()
static FieldAccess ForSlicedStringOffset ()
static FieldAccess ForSlicedStringParent ()
static FieldAccess ForExternalStringResourceData ()
static ElementAccess ForSeqOneByteStringCharacter ()
static ElementAccess ForSeqTwoByteStringCharacter ()
static FieldAccess ForJSArrayIteratorIteratedObject ()
static FieldAccess ForJSArrayIteratorNextIndex ()
static FieldAccess ForJSArrayIteratorKind ()
static FieldAccess ForJSStringIteratorString ()
static FieldAccess ForJSStringIteratorIndex ()
static FieldAccess ForCellValue ()
static FieldAccess ForArgumentsLength ()
static FieldAccess ForArgumentsCallee ()
static FieldAccess ForFixedArraySlot (size_t index, WriteBarrierKind write_barrier_kind=kFullWriteBarrier)
static FieldAccess ForFeedbackVectorSlot (int index)
static FieldAccess ForPropertyArraySlot (int index)
static FieldAccess ForScopeInfoFlags ()
static FieldAccess ForContextSlot (size_t index)
static FieldAccess ForContextSlotKnownPointer (size_t index)
static FieldAccess ForContextSlotSmi (size_t index)
static ElementAccess ForWeakFixedArrayElement ()
static FieldAccess ForWeakFixedArraySlot (int index)
static ElementAccess ForFixedArrayElement ()
static ElementAccess ForFixedArrayElement (ElementsKind kind)
static ElementAccess ForSloppyArgumentsElementsMappedEntry ()
static ElementAccess ForFixedDoubleArrayElement ()
static FieldAccess ForEnumCacheKeys ()
static FieldAccess ForEnumCacheIndices ()
static ElementAccess ForTypedArrayElement (ExternalArrayType type, bool is_external)
static ElementAccess ForJSForInCacheArrayElement (ForInMode mode)
static FieldAccess ForHashTableBaseNumberOfElements ()
static FieldAccess ForHashTableBaseNumberOfDeletedElement ()
static FieldAccess ForHashTableBaseCapacity ()
static FieldAccess ForOrderedHashMapOrSetNextTable ()
static FieldAccess ForOrderedHashMapOrSetNumberOfBuckets ()
static FieldAccess ForOrderedHashMapOrSetNumberOfElements ()
static FieldAccess ForOrderedHashMapOrSetNumberOfDeletedElements ()
static ElementAccess ForOrderedHashMapEntryValue ()
static FieldAccess ForDictionaryNextEnumerationIndex ()
static FieldAccess ForDictionaryObjectHashIndex ()
static FieldAccess ForNameDictionaryFlagsIndex ()
static FieldAccess ForFeedbackCellInterruptBudget ()
static FieldAccess ForFeedbackVectorInvocationCount ()
static FieldAccess ForFeedbackVectorFlags ()
static FieldAccess ForFeedbackVectorClosureFeedbackCellArray ()
static FieldAccess ForContextSideProperty ()
Private Member Functions
DISALLOW_IMPLICIT_CONSTRUCTORS (AccessBuilder)
Detailed Description
Definition at line 22 of file access-builder.h.
Member Function Documentation
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::compiler::AccessBuilder::DISALLOW_IMPLICIT_CONSTRUCTORS (AccessBuilder) [private]
ForArgumentsCallee()
FieldAccess v8::internal::compiler::AccessBuilder::ForArgumentsCallee () [static]
Definition at line 1071 of file access-builder.cc.
                                              {
  FieldAccess access = {
      kTaggedBase, JSSloppyArgumentsObject::kCalleeOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::NonInternal(), MachineType::AnyTagged(),
      kFullWriteBarrier, "ArgumentsCallee"};
  return access;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments().
ForArgumentsLength()
FieldAccess v8::internal::compiler::AccessBuilder::ForArgumentsLength () [static]
Definition at line 1060 of file access-builder.cc.
                                              {
  constexpr int offset = JSStrictArgumentsObject::kLengthOffset;
  static_assert(offset == JSSloppyArgumentsObject::kLengthOffset);
  FieldAccess access = {kTaggedBase, offset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::NonInternal(), MachineType::AnyTagged(),
                        kFullWriteBarrier, "ArgumentsLength"};
  return access;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments().
ForBigIntBitfield()
FieldAccess v8::internal::compiler::AccessBuilder::ForBigIntBitfield () [static]
Definition at line 110 of file access-builder.cc.
                                             {
  FieldAccess access = {kTaggedBase,
                        offsetof(BigInt, bitfield_),
                        MaybeHandle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kInt32,
                        MachineType::Uint32(),
                        kNoWriteBarrier,
                        "BigIntBitfield"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::TypeCache::kInt32, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::Uint32().
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::AllocateBigInt(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ObjectIs(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TruncateJSPrimitiveToUntagged().
ForBigIntLeastSignificantDigit64()
FieldAccess v8::internal::compiler::AccessBuilder::ForBigIntLeastSignificantDigit64 () [static]
Definition at line 135 of file access-builder.cc.
                                                            {
  DCHECK_EQ(BigInt::SizeFor(1) - BigInt::SizeFor(0), 8);
  FieldAccess access = {
      kTaggedBase, OFFSET_OF_DATA_START(BigInt), MaybeHandle<Name>(),
      OptionalMapRef(), TypeCache::Get()->kBigUint64, MachineType::Uint64(),
      kNoWriteBarrier, "BigIntLeastSignificantDigit64"};
  return access;
}
References DCHECK_EQ, v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::TypeCache::kBigUint64, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, OFFSET_OF_DATA_START, v8::internal::BigInt::SizeFor(), and v8::internal::MachineType::Uint64().
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::AllocateBigInt(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ObjectIs(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TruncateJSPrimitiveToUntagged().
ForCellValue()
FieldAccess v8::internal::compiler::AccessBuilder::ForCellValue () [static]
Definition at line 1121 of file access-builder.cc.
                                        {
  FieldAccess access = {kTaggedBase, Cell::kValueOffset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::Any(), MachineType::AnyTagged(),
                        kFullWriteBarrier, "CellValue"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadModule(), and v8::internal::compiler::JSTypedLowering::ReduceJSStoreModule().
ForConsStringFirst()
FieldAccess v8::internal::compiler::AccessBuilder::ForConsStringFirst () [static]
Definition at line 914 of file access-builder.cc.
                                              {
  FieldAccess access = {kTaggedBase, offsetof(ConsString, first_),
                        Handle<Name>(), OptionalMapRef(),
                        Type::String(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "ConsStringFirst"};
  // Not immutable since flattening can mutate.
  access.is_immutable = false;
  return access;
}
References v8::internal::compiler::FieldAccess::is_immutable, v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::NewConsString(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StringPrepareForGetCodeUnit().
ForConsStringSecond()
FieldAccess v8::internal::compiler::AccessBuilder::ForConsStringSecond () [static]
Definition at line 925 of file access-builder.cc.
                                               {
  FieldAccess access = {kTaggedBase, offsetof(ConsString, second_),
                        Handle<Name>(), OptionalMapRef(),
                        Type::String(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "ConsStringSecond"};
  // Not immutable since flattening can mutate.
  access.is_immutable = false;
  return access;
}
References v8::internal::compiler::FieldAccess::is_immutable, v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::NewConsString(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt().
ForContextCellFloat64Value()
FieldAccess v8::internal::compiler::AccessBuilder::ForContextCellFloat64Value () [static]
Definition at line 88 of file access-builder.cc.
                                                      {
  FieldAccess access = {kTaggedBase,
                        offsetof(ContextCell, double_value_),
                        MaybeHandle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kFloat64,
                        MachineType::Float64(),
                        kNoWriteBarrier,
                        "ContextCellFloat64Value"};
  return access;
}
References v8::internal::MachineType::Float64(), v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::TypeCache::kFloat64, v8::internal::compiler::kNoWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), and v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext().
ForContextCellInt32Value()
FieldAccess v8::internal::compiler::AccessBuilder::ForContextCellInt32Value () [static]
Definition at line 75 of file access-builder.cc.
                                                    {
  FieldAccess access = {kTaggedBase,
                        offsetof(ContextCell, double_value_),
                        MaybeHandle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kInt32,
                        MachineType::Int32(),
                        kNoWriteBarrier,
                        "ForContextCellInt32Value"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::MachineType::Int32(), v8::internal::compiler::TypeCache::kInt32, v8::internal::compiler::kNoWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), and v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext().
ForContextCellState()
FieldAccess v8::internal::compiler::AccessBuilder::ForContextCellState () [static]
Definition at line 56 of file access-builder.cc.
                                               {
  FieldAccess access = {
      kTaggedBase, offsetof(ContextCell, state_), MaybeHandle<Name>(),
      OptionalMapRef(), TypeCache::Get()->kInt32, MachineType::Int32(),
      kNoWriteBarrier, "ForContextCellState"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::MachineType::Int32(), v8::internal::compiler::TypeCache::kInt32, v8::internal::compiler::kNoWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext().
ForContextCellTaggedValue()
FieldAccess v8::internal::compiler::AccessBuilder::ForContextCellTaggedValue () [static]
Definition at line 65 of file access-builder.cc.
                                                     {
  FieldAccess access = {
      kTaggedBase, offsetof(ContextCell, tagged_value_),
      MaybeHandle<Name>(), OptionalMapRef(),
      Type::Any(), MachineType::AnyTagged(),
      kFullWriteBarrier, "ForContextCellTaggedValue"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), and v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext().
ForContextSideProperty()
static FieldAccess v8::internal::compiler::AccessBuilder::ForContextSideProperty () [static]
ForContextSlot()
FieldAccess v8::internal::compiler::AccessBuilder::ForContextSlot (size_t index) [static]
Definition at line 1139 of file access-builder.cc.
                                                      {
  int offset = Context::OffsetOfElementAt(static_cast<int>(index));
  DCHECK_EQ(offset,
            Context::SlotOffset(static_cast<int>(index)) + kHeapObjectTag);
  FieldAccess access = {kTaggedBase, offset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::Any(), MachineType::AnyTagged(),
                        kFullWriteBarrier, "ContextSlot"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), DCHECK_EQ, v8::internal::index, v8::internal::compiler::kFullWriteBarrier, v8::internal::kHeapObjectTag, v8::internal::compiler::kTaggedBase, v8::internal::Context::OffsetOfElementAt(), and v8::internal::Context::SlotOffset().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateBlockContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCatchContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateFunctionContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateWithContext(), v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContextNoCell(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), and v8::internal::compiler::PromiseBuiltinReducerAssembler::StoreContextNoCellSlot().
ForContextSlotKnownPointer()
FieldAccess v8::internal::compiler::AccessBuilder::ForContextSlotKnownPointer (size_t index) [static]
Definition at line 1151 of file access-builder.cc.
                                                                  {
  int offset = Context::OffsetOfElementAt(static_cast<int>(index));
  DCHECK_EQ(offset,
            Context::SlotOffset(static_cast<int>(index)) + kHeapObjectTag);
  FieldAccess access = {kTaggedBase, offset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::Any(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "ContextSlotKnownPointer"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), DCHECK_EQ, v8::internal::index, v8::internal::kHeapObjectTag, v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::Context::OffsetOfElementAt(), v8::internal::Context::SlotOffset(), and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), and v8::internal::compiler::JSTypedLowering::ReduceJSStoreContextNoCell().
ForContextSlotSmi()
FieldAccess v8::internal::compiler::AccessBuilder::ForContextSlotSmi (size_t index) [static]
Definition at line 1163 of file access-builder.cc.
                                                         {
  int offset = Context::OffsetOfElementAt(static_cast<int>(index));
  DCHECK_EQ(offset,
            Context::SlotOffset(static_cast<int>(index)) + kHeapObjectTag);
  FieldAccess access = {kTaggedBase, offset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::SignedSmall(), MachineType::TaggedSigned(),
                        kNoWriteBarrier, "Smi"};
  return access;
}
References DCHECK_EQ, v8::internal::index, v8::internal::kHeapObjectTag, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::Context::OffsetOfElementAt(), v8::internal::compiler::Type::SignedSmall(), v8::internal::Context::SlotOffset(), and v8::internal::MachineType::TaggedSigned().
ForDescriptorArrayEnumCache()
FieldAccess v8::internal::compiler::AccessBuilder::ForDescriptorArrayEnumCache () [static]
Definition at line 784 of file access-builder.cc.
                                                       {
  FieldAccess access = {
      kTaggedBase, DescriptorArray::kEnumCacheOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::OtherInternal(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "DescriptorArrayEnumCache"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey().
ForDictionaryNextEnumerationIndex()
FieldAccess v8::internal::compiler::AccessBuilder::ForDictionaryNextEnumerationIndex () [static]
Definition at line 1461 of file access-builder.cc.
                                                             {
  FieldAccess access = {
      kTaggedBase,
      FixedArray::OffsetOfElementAt(NameDictionary::kNextEnumerationIndexIndex),
      MaybeHandle<Name>(),
      OptionalMapRef(),
      Type::SignedSmall(),
      MachineType::TaggedSigned(),
      kNoWriteBarrier,
      "DictionaryNextEnumerationIndex"};
  return access;
}
References v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), v8::internal::compiler::Type::SignedSmall(), and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject().
ForDictionaryObjectHashIndex()
FieldAccess v8::internal::compiler::AccessBuilder::ForDictionaryObjectHashIndex () [static]
Definition at line 1475 of file access-builder.cc.
                                                        {
  FieldAccess access = {
      kTaggedBase,
      FixedArray::OffsetOfElementAt(NameDictionary::kObjectHashIndex),
      MaybeHandle<Name>(),
      OptionalMapRef(),
      Type::SignedSmall(),
      MachineType::TaggedSigned(),
      kNoWriteBarrier,
      "DictionaryObjectHashIndex"};
  return access;
}
References v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), v8::internal::compiler::Type::SignedSmall(), and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject().
ForEnumCacheIndices()
FieldAccess v8::internal::compiler::AccessBuilder::ForEnumCacheIndices () [static]
Definition at line 1255 of file access-builder.cc.
                                               {
  FieldAccess access = {kTaggedBase, EnumCache::kIndicesOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::OtherInternal(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "EnumCacheIndices"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey().
ForEnumCacheKeys()
FieldAccess v8::internal::compiler::AccessBuilder::ForEnumCacheKeys () [static]
Definition at line 1246 of file access-builder.cc.
                                            {
  FieldAccess access = {kTaggedBase, EnumCache::kKeysOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::OtherInternal(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "EnumCacheKeys"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare().
ForExternalIntPtr()
FieldAccess v8::internal::compiler::AccessBuilder::ForExternalIntPtr () [static]
Definition at line 25 of file access-builder.cc.
                                             {
  FieldAccess access = {kUntaggedBase, 0,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::Any(), MachineType::IntPtr(),
                        kNoWriteBarrier, "ExternalIntPtr"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::IntPtr(), v8::internal::compiler::kNoWriteBarrier, and v8::internal::compiler::kUntaggedBase.
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadMessage(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StoreMessage().
ForExternalStringResourceData()
FieldAccess v8::internal::compiler::AccessBuilder::ForExternalStringResourceData () [static]
Definition at line 966 of file access-builder.cc.
                                                         {
  FieldAccess access = {
      kTaggedBase,
      offsetof(ExternalString, resource_data_),
      Handle<Name>(),
      OptionalMapRef(),
      Type::ExternalPointer(),
      MachineType::Pointer(),
      kNoWriteBarrier,
      "ExternalStringResourceData",
      ConstFieldInfo::None(),
      false,
      kExternalStringResourceDataTag,
  };
  return access;
}
References v8::internal::kExternalStringResourceDataTag, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::ConstFieldInfo::None(), and v8::internal::MachineType::Pointer().
Referenced by v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StringPrepareForGetCodeUnit().
ForFeedbackCellInterruptBudget()
FieldAccess v8::internal::compiler::AccessBuilder::ForFeedbackCellInterruptBudget () [static]
Definition at line 1503 of file access-builder.cc.
                                                          {
  FieldAccess access = {kTaggedBase,
                        FeedbackCell::kInterruptBudgetOffset,
                        Handle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kInt32,
                        MachineType::Int32(),
                        kNoWriteBarrier,
                        "FeedbackCellInterruptBudget"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::MachineType::Int32(), v8::internal::compiler::TypeCache::kInt32, v8::internal::compiler::kNoWriteBarrier, and v8::internal::compiler::kTaggedBase.
ForFeedbackVectorClosureFeedbackCellArray()
FieldAccess v8::internal::compiler::AccessBuilder::ForFeedbackVectorClosureFeedbackCellArray () [static]
Definition at line 1556 of file access-builder.cc.
                                                                     {
  FieldAccess access = {
      kTaggedBase, FeedbackVector::kClosureFeedbackCellArrayOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::Any(), MachineType::TaggedPointer(),
      kFullWriteBarrier, "FeedbackVectorClosureFeedbackCellArray"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
ForFeedbackVectorFlags()
FieldAccess v8::internal::compiler::AccessBuilder::ForFeedbackVectorFlags () [static]
Definition at line 1547 of file access-builder.cc.
                                                  {
  FieldAccess access = {
      kTaggedBase, FeedbackVector::kFlagsOffset, Handle<Name>(),
      OptionalMapRef(), TypeCache::Get()->kUint16, MachineType::Uint16(),
      kNoWriteBarrier, "FeedbackVectorFlags"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::TypeCache::kUint16, and v8::internal::MachineType::Uint16().
ForFeedbackVectorInvocationCount()
FieldAccess v8::internal::compiler::AccessBuilder::ForFeedbackVectorInvocationCount () [static]
Definition at line 1534 of file access-builder.cc.
                                                            {
  FieldAccess access = {kTaggedBase,
                        FeedbackVector::kInvocationCountOffset,
                        Handle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kInt32,
                        MachineType::Int32(),
                        kNoWriteBarrier,
                        "FeedbackVectorInvocationCount"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::MachineType::Int32(), v8::internal::compiler::TypeCache::kInt32, v8::internal::compiler::kNoWriteBarrier, and v8::internal::compiler::kTaggedBase.
ForFeedbackVectorSlot()
FieldAccess v8::internal::compiler::AccessBuilder::ForFeedbackVectorSlot (int index) [static]
Definition at line 1092 of file access-builder.cc.
                                                          {
  int offset = FeedbackVector::OffsetOfElementAt(index);
  FieldAccess access = {kTaggedBase, offset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::Any(), MachineType::AnyTagged(),
                        kFullWriteBarrier, "FeedbackVectorSlot"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), v8::internal::index, v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::FeedbackVector::OffsetOfElementAt().
ForFixedArrayElement() [1/2]
ElementAccess v8::internal::compiler::AccessBuilder::ForFixedArrayElement () [static]
Definition at line 1175 of file access-builder.cc.
                                                  {
  ElementAccess access = {kTaggedBase, OFFSET_OF_DATA_START(FixedArray),
                          Type::Any(), MachineType::AnyTagged(),
                          kFullWriteBarrier};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kTaggedBase, and OFFSET_OF_DATA_START.
Referenced by v8::internal::compiler::JSCreateLowering::AllocateElements(), v8::internal::compiler::turboshaft::AccessBuilderTS::ForFixedArrayElement(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateKeyValueArray(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::SafeLoadElement(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::StoreFixedArrayBaseElement(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TransitionAndStoreArrayElement(), v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements(), and v8::internal::compiler::JSCreateLowering::TryAllocateRestArguments().
ForFixedArrayElement() [2/2]
ElementAccess v8::internal::compiler::AccessBuilder::ForFixedArrayElement (ElementsKind kind) [static]
Definition at line 1199 of file access-builder.cc.
                                                                   {
  ElementAccess access = {kTaggedBase, OFFSET_OF_DATA_START(FixedArray),
                          Type::Any(), MachineType::AnyTagged(),
                          kFullWriteBarrier};
  switch (kind) {
    case PACKED_SMI_ELEMENTS:
      access.type = Type::SignedSmall();
      access.machine_type = MachineType::TaggedSigned();
      access.write_barrier_kind = kNoWriteBarrier;
      break;
    case HOLEY_SMI_ELEMENTS:
      access.type = TypeCache::Get()->kHoleySmi;
      break;
    case PACKED_ELEMENTS:
      access.type = Type::NonInternal();
      break;
    case HOLEY_ELEMENTS:
      break;
    case PACKED_DOUBLE_ELEMENTS:
      access.type = Type::Number();
      access.write_barrier_kind = kNoWriteBarrier;
      access.machine_type = MachineType::Float64();
      break;
    case HOLEY_DOUBLE_ELEMENTS:
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      access.type = Type::NumberOrUndefinedOrHole();
#else
      access.type = Type::NumberOrHole();
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      access.write_barrier_kind = kNoWriteBarrier;
      access.machine_type = MachineType::Float64();
      break;
    default:
      UNREACHABLE();
  }
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), v8::internal::MachineType::Float64(), v8::internal::compiler::TypeCache::Get(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::TypeCache::kHoleySmi, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::ElementAccess::machine_type, OFFSET_OF_DATA_START, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, v8::internal::compiler::Type::SignedSmall(), v8::internal::MachineType::TaggedSigned(), v8::internal::compiler::ElementAccess::type, v8::internal::UNREACHABLE(), and v8::internal::compiler::ElementAccess::write_barrier_kind.
ForFixedArrayLength()
FieldAccess v8::internal::compiler::AccessBuilder::ForFixedArrayLength () [static]
Definition at line 726 of file access-builder.cc.
                                               {
  FieldAccess access = {kTaggedBase,
                        offsetof(FixedArray, length_),
                        MaybeHandle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kFixedArrayLengthType,
                        MachineType::TaggedSigned(),
                        kNoWriteBarrier,
                        "FixedArrayLength"};
  access.is_immutable = true;
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::FieldAccess::is_immutable, v8::internal::compiler::TypeCache::kFixedArrayLengthType, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::AllocationBuilder::AllocateArray(), v8::internal::compiler::AllocationBuilder::AllocateContext(), v8::internal::compiler::AllocationBuilder::AllocateSloppyArgumentElements(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::LoadFixedArrayBaseLength(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::NewArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), and v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare().
ForFixedArraySlot()
FieldAccess v8::internal::compiler::AccessBuilder::ForFixedArraySlot (size_t index, WriteBarrierKind write_barrier_kind = kFullWriteBarrier) [static]
Definition at line 1081 of file access-builder.cc.
                                                       {
  int offset = FixedArray::OffsetOfElementAt(static_cast<int>(index));
  FieldAccess access = {kTaggedBase, offset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::Any(), MachineType::AnyTagged(),
                        write_barrier_kind, "FixedArraySlot"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), v8::internal::index, v8::internal::compiler::kTaggedBase, and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), v8::internal::compiler::JSTypedLowering::BuildGetModuleCell(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreRegister(), and v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorStore().
ForFixedDoubleArrayElement()
ElementAccess v8::internal::compiler::AccessBuilder::ForFixedDoubleArrayElement () [static]
Definition at line 1238 of file access-builder.cc.
                                                        {
  ElementAccess access = {kTaggedBase, OFFSET_OF_DATA_START(FixedDoubleArray),
                          TypeCache::Get()->kFloat64, MachineType::Float64(),
                          kNoWriteBarrier};
  return access;
}
References v8::internal::MachineType::Float64(), v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::TypeCache::kFloat64, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, and OFFSET_OF_DATA_START.
Referenced by v8::internal::compiler::JSCreateLowering::AllocateElements(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::DoubleArrayMinMax(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TransitionAndStoreArrayElement(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements().
ForHashTableBaseCapacity()
FieldAccess v8::internal::compiler::AccessBuilder::ForHashTableBaseCapacity () [static]
Definition at line 1372 of file access-builder.cc.
                                                    {
  FieldAccess access = {
      kTaggedBase,
      FixedArray::OffsetOfElementAt(HashTableBase::kCapacityIndex),
      MaybeHandle<Name>(),
      OptionalMapRef(),
      Type::SignedSmall(),
      MachineType::TaggedSigned(),
      kNoWriteBarrier,
      "HashTableBaseCapacity"};
  return access;
}
References v8::internal::HashTableBase::kCapacityIndex, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), v8::internal::compiler::Type::SignedSmall(), and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject().
ForHashTableBaseNumberOfDeletedElement()
FieldAccess v8::internal::compiler::AccessBuilder::ForHashTableBaseNumberOfDeletedElement () [static]
Definition at line 1358 of file access-builder.cc.
                                                                  {
  FieldAccess access = {kTaggedBase,
                        FixedArray::OffsetOfElementAt(
                            HashTableBase::kNumberOfDeletedElementsIndex),
                        MaybeHandle<Name>(),
                        OptionalMapRef(),
                        Type::SignedSmall(),
                        MachineType::TaggedSigned(),
                        kNoWriteBarrier,
                        "HashTableBaseNumberOfDeletedElement"};
  return access;
}
References v8::internal::compiler::kNoWriteBarrier, v8::internal::HashTableBase::kNumberOfDeletedElementsIndex, v8::internal::compiler::kTaggedBase, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), v8::internal::compiler::Type::SignedSmall(), and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject().
ForHashTableBaseNumberOfElements()
FieldAccess v8::internal::compiler::AccessBuilder::ForHashTableBaseNumberOfElements () [static]
Definition at line 1344 of file access-builder.cc.
                                                            {
  FieldAccess access = {
      kTaggedBase,
      FixedArray::OffsetOfElementAt(HashTableBase::kNumberOfElementsIndex),
      MaybeHandle<Name>(),
      OptionalMapRef(),
      Type::SignedSmall(),
      MachineType::TaggedSigned(),
      kNoWriteBarrier,
      "HashTableBaseNumberOfElements"};
  return access;
}
References v8::internal::compiler::kNoWriteBarrier, v8::internal::HashTableBase::kNumberOfElementsIndex, v8::internal::compiler::kTaggedBase, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), v8::internal::compiler::Type::SignedSmall(), and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject().
ForHeapNumberOrOddballOrHoleValue()
FieldAccess v8::internal::compiler::AccessBuilder::ForHeapNumberOrOddballOrHoleValue () [static]
Definition at line 101 of file access-builder.cc.
                                                             {
  STATIC_ASSERT_FIELD_OFFSETS_EQUAL(offsetof(HeapNumber, value_),
                                    offsetof(Oddball, to_number_raw_));
  STATIC_ASSERT_FIELD_OFFSETS_EQUAL(offsetof(HeapNumber, value_),
                                    Hole::kRawNumericValueOffset);
  return ForHeapNumberValue();
}
References ForHeapNumberValue(), and STATIC_ASSERT_FIELD_OFFSETS_EQUAL.
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::Convert(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertHeapObjectToFloat64OrDeopt(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertJSPrimitiveToUntagged(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::NewArray(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TruncateJSPrimitiveToUntagged().
ForHeapNumberValue()
FieldAccess v8::internal::compiler::AccessBuilder::ForHeapNumberValue () [static]
Definition at line 43 of file access-builder.cc.
                                              {
  FieldAccess access = {kTaggedBase,
                        offsetof(HeapNumber, value_),
                        MaybeHandle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kFloat64,
                        MachineType::Float64(),
                        kNoWriteBarrier,
                        "HeapNumberValue"};
  return access;
}
References v8::internal::MachineType::Float64(), v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::TypeCache::kFloat64, v8::internal::compiler::kNoWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ChangeTaggedNumberToIntPtr(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToFloat64(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToWord32(), ForHeapNumberOrOddballOrHoleValue(), v8::internal::wasm::WasmWrapperTSGraphBuilder::HeapNumberToFloat64(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral().
ForJSArrayBufferBitField()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSArrayBufferBitField () [static]
Definition at line 487 of file access-builder.cc.
                                                    {
  FieldAccess access = {
      kTaggedBase, JSArrayBuffer::kBitFieldOffset, MaybeHandle<Name>(),
      OptionalMapRef(), TypeCache::Get()->kUint8, MachineType::Uint32(),
      kNoWriteBarrier, "JSArrayBufferBitField"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::TypeCache::kUint8, and v8::internal::MachineType::Uint32().
Referenced by v8::internal::compiler::JSGraphAssembler::ArrayBufferDetachedBit(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ArrayBufferIsDetached(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), and v8::internal::compiler::JSCallReducer::ReduceDataViewAccess().
ForJSArrayBufferByteLength()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSArrayBufferByteLength () [static]
Definition at line 496 of file access-builder.cc.
                                                      {
  FieldAccess access = {kTaggedBase,
                        JSArrayBuffer::kRawByteLengthOffset,
                        MaybeHandle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kJSArrayBufferByteLengthType,
                        MachineType::UintPtr(),
                        kNoWriteBarrier,
                        "JSArrayBufferByteLength"};
#ifdef V8_ENABLE_SANDBOX
  access.is_bounded_size_access = true;
#endif
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::FieldAccess::is_bounded_size_access, v8::internal::compiler::TypeCache::kJSArrayBufferByteLengthType, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::UintPtr().
Referenced by v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildByteLength(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildDetachedOrOutOfBoundsCheck(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildLength(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::GetDataViewByteLength().
ForJSArrayBufferViewBitField()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewBitField () [static]
Definition at line 554 of file access-builder.cc.
                                                        {
  FieldAccess access = {kTaggedBase,
                        JSArrayBufferView::kBitFieldOffset,
                        MaybeHandle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kUint32,
                        MachineType::Uint32(),
                        kNoWriteBarrier,
                        "JSArrayBufferViewBitField"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::TypeCache::kUint32, and v8::internal::MachineType::Uint32().
Referenced by v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildByteLength(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildDetachedOrOutOfBoundsCheck(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildLength(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::GetDataViewByteLength().
ForJSArrayBufferViewBuffer()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewBuffer () [static]
Definition at line 512 of file access-builder.cc.
                                                      {
  FieldAccess access = {kTaggedBase, JSArrayBufferView::kBufferOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::OtherInternal(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "JSArrayBufferViewBuffer"};
  access.is_immutable = true;
  return access;
}
References v8::internal::compiler::FieldAccess::is_immutable, v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ArrayBufferIsDetached(), v8::internal::compiler::JSGraphAssembler::ArrayBufferViewDetachedBit(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildByteLength(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildDetachedOrOutOfBoundsCheck(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildLength(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetDataViewByteLength(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), and v8::internal::compiler::JSCallReducer::ReduceDataViewAccess().
ForJSArrayBufferViewByteLength()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewByteLength () [static]
Definition at line 522 of file access-builder.cc.
                                                          {
  FieldAccess access = {kTaggedBase,
                        JSArrayBufferView::kRawByteLengthOffset,
                        MaybeHandle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kJSArrayBufferViewByteLengthType,
                        MachineType::UintPtr(),
                        kNoWriteBarrier,
                        "JSArrayBufferViewByteLength"};
#ifdef V8_ENABLE_SANDBOX
  access.is_bounded_size_access = true;
#endif
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::FieldAccess::is_bounded_size_access, v8::internal::compiler::TypeCache::kJSArrayBufferViewByteLengthType, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::UintPtr().
Referenced by v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildByteLength(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildDetachedOrOutOfBoundsCheck(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildLength(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetDataViewByteLength(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor(), and v8::internal::compiler::JSCallReducer::ReduceDataViewAccess().
ForJSArrayBufferViewByteOffset()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewByteOffset () [static]
Definition at line 538 of file access-builder.cc.
                                                          {
  FieldAccess access = {kTaggedBase,
                        JSArrayBufferView::kRawByteOffsetOffset,
                        MaybeHandle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kJSArrayBufferViewByteOffsetType,
                        MachineType::UintPtr(),
                        kNoWriteBarrier,
                        "JSArrayBufferViewByteOffset"};
#ifdef V8_ENABLE_SANDBOX
  access.is_bounded_size_access = true;
#endif
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::FieldAccess::is_bounded_size_access, v8::internal::compiler::TypeCache::kJSArrayBufferViewByteOffsetType, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::UintPtr().
Referenced by v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildByteLength(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildDetachedOrOutOfBoundsCheck(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildLength(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetDataViewByteLength(), and v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteOffsetAccessor().
ForJSArrayIteratorIteratedObject()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSArrayIteratorIteratedObject () [static]
Definition at line 1000 of file access-builder.cc.
                                                            {
  FieldAccess access = {
      kTaggedBase, JSArrayIterator::kIteratedObjectOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::Receiver(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "JSArrayIteratorIteratedObject"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator().
ForJSArrayIteratorKind()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSArrayIteratorKind () [static]
Definition at line 1025 of file access-builder.cc.
                                                  {
  FieldAccess access = {kTaggedBase,
                        JSArrayIterator::kKindOffset,
                        Handle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kJSArrayIteratorKindType,
                        MachineType::TaggedSigned(),
                        kNoWriteBarrier,
                        "JSArrayIteratorKind"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::TypeCache::kJSArrayIteratorKindType, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator().
ForJSArrayIteratorNextIndex()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSArrayIteratorNextIndex () [static]
Definition at line 1010 of file access-builder.cc.
                                                       {
  // In generic case, cap to 2^53-1 (per ToLength() in spec) via
  // kPositiveSafeInteger
  FieldAccess access = {kTaggedBase,
                        JSArrayIterator::kNextIndexOffset,
                        Handle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kPositiveSafeInteger,
                        MachineType::AnyTagged(),
                        kFullWriteBarrier,
                        "JSArrayIteratorNextIndex"};
  return access;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::TypeCache::kPositiveSafeInteger, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator().
ForJSArrayLength()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSArrayLength (ElementsKind elements_kind) [static]
Definition at line 464 of file access-builder.cc.
                                                                      {
  TypeCache const* type_cache = TypeCache::Get();
  FieldAccess access = {kTaggedBase,
                        JSArray::kLengthOffset,
                        Handle<Name>(),
                        OptionalMapRef(),
                        type_cache->kJSArrayLengthType,
                        MachineType::AnyTagged(),
                        kFullWriteBarrier,
                        "JSArrayLength"};
  if (IsDoubleElementsKind(elements_kind)) {
    access.type = type_cache->kFixedDoubleArrayLengthType;
    access.machine_type = MachineType::TaggedSigned();
    access.write_barrier_kind = kNoWriteBarrier;
  } else if (IsFastElementsKind(elements_kind)) {
    access.type = type_cache->kFixedArrayLengthType;
    access.machine_type = MachineType::TaggedSigned();
    access.write_barrier_kind = kNoWriteBarrier;
  }
  return access;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::TypeCache::Get(), v8::internal::IsDoubleElementsKind(), v8::internal::IsFastElementsKind(), v8::internal::compiler::TypeCache::kFixedArrayLengthType, v8::internal::compiler::TypeCache::kFixedDoubleArrayLengthType, v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::TypeCache::kJSArrayLengthType, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::FieldAccess::machine_type, v8::internal::MachineType::TaggedSigned(), v8::internal::compiler::FieldAccess::type, and v8::internal::compiler::FieldAccess::write_barrier_kind.
Referenced by v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::compiler::JSCallReducer::CheckArrayLength(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::DoubleArrayMinMax(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::LoadJSArrayLength(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateKeyValueArray(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::StoreJSArrayLength(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral().
ForJSAsyncFunctionObjectPromise()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSAsyncFunctionObjectPromise () [static]
Definition at line 434 of file access-builder.cc.
                                                           {
  FieldAccess access = {
      kTaggedBase, JSAsyncFunctionObject::kPromiseOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::OtherObject(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "JSAsyncFunctionObjectPromise"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionReject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionResolve(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject().
ForJSAsyncGeneratorObjectIsAwaiting()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSAsyncGeneratorObjectIsAwaiting () [static]
Definition at line 454 of file access-builder.cc.
                                                               {
  FieldAccess access = {
      kTaggedBase, JSAsyncGeneratorObject::kIsAwaitingOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::SignedSmall(), MachineType::TaggedSigned(),
      kNoWriteBarrier, "JSAsyncGeneratorObjectIsAwaiting"};
  return access;
}
References v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::Type::SignedSmall(), and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject().
ForJSAsyncGeneratorObjectQueue()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSAsyncGeneratorObjectQueue () [static]
Definition at line 444 of file access-builder.cc.
                                                          {
  FieldAccess access = {
      kTaggedBase, JSAsyncGeneratorObject::kQueueOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::NonInternal(), MachineType::AnyTagged(),
      kFullWriteBarrier, "JSAsyncGeneratorObjectQueue"};
  return access;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject().
ForJSBoundFunctionBoundArguments()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSBoundFunctionBoundArguments () [static]
Definition at line 352 of file access-builder.cc.
                                                            {
  FieldAccess access = {
      kTaggedBase, JSBoundFunction::kBoundArgumentsOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::Internal(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "JSBoundFunctionBoundArguments"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction().
ForJSBoundFunctionBoundTargetFunction()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSBoundFunctionBoundTargetFunction () [static]
Definition at line 333 of file access-builder.cc.
                                                                 {
  FieldAccess access = {
      kTaggedBase, JSBoundFunction::kBoundTargetFunctionOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::Callable(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "JSBoundFunctionBoundTargetFunction"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction().
ForJSBoundFunctionBoundThis()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSBoundFunctionBoundThis () [static]
Definition at line 343 of file access-builder.cc.
                                                       {
  FieldAccess access = {kTaggedBase, JSBoundFunction::kBoundThisOffset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::NonInternal(), MachineType::AnyTagged(),
                        kFullWriteBarrier, "JSBoundFunctionBoundThis"};
  return access;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction().
ForJSCollectionIteratorIndex()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSCollectionIteratorIndex () [static]
Definition at line 213 of file access-builder.cc.
                                                        {
  FieldAccess access = {kTaggedBase,
                        JSCollectionIterator::kIndexOffset,
                        MaybeHandle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kFixedArrayLengthType,
                        MachineType::TaggedSigned(),
                        kNoWriteBarrier,
                        "JSCollectionIteratorIndex"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::TypeCache::kFixedArrayLengthType, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator().
ForJSCollectionIteratorTable()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSCollectionIteratorTable () [static]
Definition at line 203 of file access-builder.cc.
                                                        {
  FieldAccess access = {
      kTaggedBase, JSCollectionIterator::kTableOffset,
      MaybeHandle<Name>(), OptionalMapRef(),
      Type::OtherInternal(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "JSCollectionIteratorTable"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator().
ForJSCollectionTable()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSCollectionTable () [static]
Definition at line 194 of file access-builder.cc.
                                                {
  FieldAccess access = {kTaggedBase, JSCollection::kTableOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::OtherInternal(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "JSCollectionTable"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeHas(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeSize(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator(), and v8::internal::compiler::JSCallReducer::ReduceMapPrototypeGet().
ForJSDataViewByteLength()
static FieldAccess v8::internal::compiler::AccessBuilder::ForJSDataViewByteLength () [inline], [static]
Definition at line 192 of file access-builder.h.
                                               {
    return ForJSArrayBufferViewByteLength();
  }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
ForJSDataViewDataPointer()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSDataViewDataPointer () [static]
Definition at line 598 of file access-builder.cc.
                                                    {
  FieldAccess access = {
      kTaggedBase,
      JSDataView::kDataPointerOffset,
      MaybeHandle<Name>(),
      OptionalMapRef(),
#ifdef V8_ENABLE_SANDBOX
      Type::SandboxedPointer(),
      MachineType::SandboxedPointer(),
#else
      Type::ExternalPointer(),
      MachineType::Pointer(),
#endif
      kNoWriteBarrier,
      "JSDataViewDataPointer",
      ConstFieldInfo::None(),
      false,
  };
  return access;
}
References v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::ConstFieldInfo::None(), v8::internal::MachineType::Pointer(), and v8::internal::MachineType::SandboxedPointer().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::GetDataViewDataPtr(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and v8::internal::compiler::JSCallReducer::ReduceDataViewAccess().
ForJSDateField()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSDateField (JSDate::FieldIndex index) [static]
Definition at line 633 of file access-builder.cc.
                                                                {
  DCHECK_LT(index, JSDate::kFirstUncachedField);
  FieldAccess access = {kTaggedBase,
                        JSDate::kYearOffset + index * kTaggedSize,
                        MaybeHandle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kJSDateFields[index],
                        MachineType::AnyTagged(),
                        kFullWriteBarrier,
                        "JSDateField"};
  return access;
}
References v8::internal::MachineType::AnyTagged(), DCHECK_LT, v8::internal::compiler::TypeCache::Get(), v8::internal::index, v8::internal::JSDate::kFirstUncachedField, v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::TypeCache::kJSDateFields, v8::internal::compiler::kTaggedBase, and v8::internal::kTaggedSize.
Referenced by v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetField().
ForJSDateValue()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSDateValue () [static]
Definition at line 620 of file access-builder.cc.
                                          {
  FieldAccess access = {kTaggedBase,
                        JSDate::kValueOffset,
                        MaybeHandle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kJSDateValueType,
                        MachineType::Float64(),
                        kNoWriteBarrier,
                        "JSDateValue"};
  return access;
}
References v8::internal::MachineType::Float64(), v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::TypeCache::kJSDateValueType, v8::internal::compiler::kNoWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetTime().
ForJSExternalObjectValue()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSExternalObjectValue () [static]
Definition at line 226 of file access-builder.cc.
                                                    {
  FieldAccess access = {
      kTaggedBase,
      JSExternalObject::kValueOffset,
      MaybeHandle<Name>(),
      OptionalMapRef(),
      Type::ExternalPointer(),
      MachineType::Pointer(),
      kNoWriteBarrier,
      "JSExternalObjectValue",
      ConstFieldInfo::None(),
      false,
      kExternalObjectValueTag,
  };
  return access;
}
References v8::internal::kExternalObjectValueTag, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::ConstFieldInfo::None(), and v8::internal::MachineType::Pointer().
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::AdaptFastCallArgument(), and v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject().
ForJSForInCacheArrayElement()
ElementAccess v8::internal::compiler::AccessBuilder::ForJSForInCacheArrayElement (ForInMode mode) [static]
Definition at line 1334 of file access-builder.cc.
                                                                       {
  ElementAccess access = {
      kTaggedBase, OFFSET_OF_DATA_START(FixedArray),
      (mode == ForInMode::kGeneric ? Type::String()
                                   : Type::InternalizedString()),
      MachineType::AnyTagged(), kFullWriteBarrier};
  return access;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kGeneric, v8::internal::compiler::kTaggedBase, mode(), and OFFSET_OF_DATA_START.
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSForInNext().
ForJSFunctionCode()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSFunctionCode () [static]
Definition at line 322 of file access-builder.cc.
                                             {
  FieldAccess access = {kTaggedBase, JSFunction::kCodeOffset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::OtherInternal(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "JSFunctionCode"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure().
ForJSFunctionContext()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSFunctionContext () [static]
Definition at line 265 of file access-builder.cc.
                                                {
  FieldAccess access = {kTaggedBase, JSFunction::kContextOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::Internal(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "JSFunctionContext"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSInliner::DetermineCallContext(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure().
ForJSFunctionFeedbackCell()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSFunctionFeedbackCell () [static]
Definition at line 284 of file access-builder.cc.
                                                     {
  FieldAccess access = {kTaggedBase, JSFunction::kFeedbackCellOffset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::Internal(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "JSFunctionFeedbackCell"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CheckedClosure(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure().
ForJSFunctionPrototypeOrInitialMap()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSFunctionPrototypeOrInitialMap () [static]
Definition at line 255 of file access-builder.cc.
                                                              {
  FieldAccess access = {
      kTaggedBase, JSFunction::kPrototypeOrInitialMapOffset,
      MaybeHandle<Name>(), OptionalMapRef(),
      Type::Any(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "JSFunctionPrototypeOrInitialMap"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure().
ForJSFunctionSharedFunctionInfo()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSFunctionSharedFunctionInfo () [static]
Definition at line 274 of file access-builder.cc.
                                                           {
  FieldAccess access = {
      kTaggedBase, JSFunction::kSharedFunctionInfoOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::OtherInternal(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "JSFunctionSharedFunctionInfo"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure().
ForJSGeneratorObjectContext()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectContext () [static]
Definition at line 362 of file access-builder.cc.
                                                       {
  FieldAccess access = {kTaggedBase, JSGeneratorObject::kContextOffset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::Internal(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "JSGeneratorObjectContext"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContextNoCell(), and v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorStore().
ForJSGeneratorObjectContinuation()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectContinuation () [static]
Definition at line 394 of file access-builder.cc.
                                                            {
  FieldAccess access = {
      kTaggedBase, JSGeneratorObject::kContinuationOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::SignedSmall(), MachineType::TaggedSigned(),
      kNoWriteBarrier, "JSGeneratorObjectContinuation"};
  return access;
}
References v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::Type::SignedSmall(), and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::JSIntrinsicLowering::ReduceGeneratorClose(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContinuation(), and v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorStore().
ForJSGeneratorObjectFunction()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectFunction () [static]
Definition at line 371 of file access-builder.cc.
                                                        {
  FieldAccess access = {kTaggedBase,
                        JSGeneratorObject::kFunctionOffset,
                        Handle<Name>(),
                        OptionalMapRef(),
                        Type::CallableFunction(),
                        MachineType::TaggedPointer(),
                        kPointerWriteBarrier,
                        "JSGeneratorObjectFunction"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject().
ForJSGeneratorObjectInputOrDebugPos()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectInputOrDebugPos () [static]
Definition at line 404 of file access-builder.cc.
                                                               {
  FieldAccess access = {
      kTaggedBase, JSGeneratorObject::kInputOrDebugPosOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::NonInternal(), MachineType::AnyTagged(),
      kFullWriteBarrier, "JSGeneratorObjectInputOrDebugPos"};
  return access;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreInputOrDebugPos(), and v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorStore().
ForJSGeneratorObjectParametersAndRegisters()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectParametersAndRegisters () [static]
Definition at line 414 of file access-builder.cc.
                                                                      {
  FieldAccess access = {
      kTaggedBase, JSGeneratorObject::kParametersAndRegistersOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::Internal(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "JSGeneratorObjectParametersAndRegisters"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreRegister(), and v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorStore().
ForJSGeneratorObjectReceiver()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectReceiver () [static]
Definition at line 384 of file access-builder.cc.
                                                        {
  FieldAccess access = {
      kTaggedBase, JSGeneratorObject::kReceiverOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::Internal(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "JSGeneratorObjectReceiver"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject().
ForJSGeneratorObjectResumeMode()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectResumeMode () [static]
Definition at line 424 of file access-builder.cc.
                                                          {
  FieldAccess access = {
      kTaggedBase, JSGeneratorObject::kResumeModeOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::SignedSmall(), MachineType::TaggedSigned(),
      kNoWriteBarrier, "JSGeneratorObjectResumeMode"};
  return access;
}
References v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::Type::SignedSmall(), and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::JSIntrinsicLowering::ReduceGeneratorGetResumeMode(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject().
ForJSIteratorResultDone()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSIteratorResultDone () [static]
Definition at line 647 of file access-builder.cc.
                                                   {
  FieldAccess access = {kTaggedBase, JSIteratorResult::kDoneOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::NonInternal(), MachineType::AnyTagged(),
                        kFullWriteBarrier, "JSIteratorResultDone"};
  return access;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateIterResultObject().
ForJSIteratorResultValue()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSIteratorResultValue () [static]
Definition at line 656 of file access-builder.cc.
                                                    {
  FieldAccess access = {kTaggedBase, JSIteratorResult::kValueOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::NonInternal(), MachineType::AnyTagged(),
                        kFullWriteBarrier, "JSIteratorResultValue"};
  return access;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateIterResultObject().
ForJSObjectElements()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSObjectElements () [static]
Definition at line 164 of file access-builder.cc.
                                               {
  FieldAccess access = {kTaggedBase, JSObject::kElementsOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::Internal(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "JSObjectElements"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::DoubleArrayMinMax(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::LoadElements(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateIterResultObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateKeyValueArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreatePromise(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringWrapper(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::SafeLoadElement(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TransitionAndStoreArrayElement(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral().
ForJSObjectInObjectProperty()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSObjectInObjectProperty (MapRef map, int index, MachineType machine_type = MachineType::AnyTagged()) [static]
Definition at line 173 of file access-builder.cc.
                                                     {
  int const offset = map.GetInObjectPropertyOffset(index);
  FieldAccess access = {kTaggedBase, offset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::NonInternal(), machine_type,
                        kFullWriteBarrier, "JSObjectInObjectProperty"};
  return access;
}
References v8::internal::compiler::MapRef::GetInObjectPropertyOffset(), v8::internal::index, v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::wasm::machine_type().
Referenced by v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral().
ForJSObjectOffset()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSObjectOffset (int offset, WriteBarrierKind write_barrier_kind = kFullWriteBarrier) [static]
Definition at line 184 of file access-builder.cc.
                                                     {
  FieldAccess access = {kTaggedBase, offset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::NonInternal(), MachineType::AnyTagged(),
                        write_barrier_kind, "JSObjectOffset"};
  return access;
}
References v8::internal::MachineType::AnyTagged(), and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreatePromise().
ForJSObjectPropertiesOrHash()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHash () [static]
Definition at line 145 of file access-builder.cc.
                                                       {
  FieldAccess access = {kTaggedBase, JSObject::kPropertiesOrHashOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::Any(), MachineType::AnyTagged(),
                        kFullWriteBarrier, "JSObjectPropertiesOrHash"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::ExtendPropertiesBackingStore(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringWrapper(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::WasmAllocateArray(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::WasmAllocateStruct().
ForJSObjectPropertiesOrHashKnownPointer()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer () [static]
Definition at line 154 of file access-builder.cc.
                                                                   {
  FieldAccess access = {
      kTaggedBase, JSObject::kPropertiesOrHashOffset,
      MaybeHandle<Name>(), OptionalMapRef(),
      Type::Any(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "JSObjectPropertiesOrHashKnownPointer"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadFieldByIndex(), v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateIterResultObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateKeyValueArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreatePromise(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringIterator(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral().
ForJSPrimitiveWrapperValue()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSPrimitiveWrapperValue () [static]
Definition at line 665 of file access-builder.cc.
                                                      {
  FieldAccess access = {kTaggedBase, JSPrimitiveWrapper::kValueOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::NonInternal(), MachineType::AnyTagged(),
                        kFullWriteBarrier, "JSPrimitiveWrapperValue"};
  return access;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringWrapper(), and v8::internal::compiler::JSTypedLowering::UnwrapStringWrapper().
ForJSRegExpData()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSRegExpData () [static]
Definition at line 689 of file access-builder.cc.
                                           {
  FieldAccess access = {kTaggedBase, JSRegExp::kDataOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::OtherInternal(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "JSRegExpData"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp().
ForJSRegExpFlags()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSRegExpFlags () [static]
Definition at line 699 of file access-builder.cc.
                                            {
  FieldAccess access = {kTaggedBase, JSRegExp::kFlagsOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::NonInternal(), MachineType::AnyTagged(),
                        kFullWriteBarrier, "JSRegExpFlags"};
  return access;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp().
ForJSRegExpLastIndex()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSRegExpLastIndex () [static]
Definition at line 708 of file access-builder.cc.
                                                {
  FieldAccess access = {kTaggedBase, JSRegExp::kLastIndexOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::NonInternal(), MachineType::AnyTagged(),
                        kFullWriteBarrier, "JSRegExpLastIndex"};
  return access;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, v8::internal::JSRegExp::kLastIndexOffset, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp(), and v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest().
ForJSRegExpSource()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSRegExpSource () [static]
Definition at line 717 of file access-builder.cc.
                                             {
  FieldAccess access = {kTaggedBase, JSRegExp::kSourceOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::NonInternal(), MachineType::AnyTagged(),
                        kFullWriteBarrier, "JSRegExpSource"};
  return access;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp().
ForJSStringIteratorIndex()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSStringIteratorIndex () [static]
Definition at line 1047 of file access-builder.cc.
                                                    {
  FieldAccess access = {kTaggedBase,
                        JSStringIterator::kIndexOffset,
                        Handle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kStringLengthType,
                        MachineType::TaggedSigned(),
                        kNoWriteBarrier,
                        "JSStringIteratorIndex"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::TypeCache::kStringLengthType, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringIterator(), and v8::internal::compiler::JSCallReducer::ReduceStringIteratorPrototypeNext().
ForJSStringIteratorString()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSStringIteratorString () [static]
Definition at line 1038 of file access-builder.cc.
                                                     {
  FieldAccess access = {kTaggedBase, JSStringIterator::kStringOffset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::String(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "JSStringIteratorString"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringIterator(), and v8::internal::compiler::JSCallReducer::ReduceStringIteratorPrototypeNext().
ForJSTypedArrayBasePointer()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSTypedArrayBasePointer () [static]
Definition at line 567 of file access-builder.cc.
                                                      {
  FieldAccess access = {kTaggedBase, JSTypedArray::kBasePointerOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::OtherInternal(), MachineType::AnyTagged(),
                        kFullWriteBarrier, "JSTypedArrayBasePointer"};
  return access;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), and v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext().
ForJSTypedArrayByteLength()
static FieldAccess v8::internal::compiler::AccessBuilder::ForJSTypedArrayByteLength () [inline], [static]
Definition at line 179 of file access-builder.h.
                                                 {
    return ForJSArrayBufferViewByteLength();
  }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TypedArrayLength().
ForJSTypedArrayExternalPointer()
FieldAccess v8::internal::compiler::AccessBuilder::ForJSTypedArrayExternalPointer () [static]
Definition at line 576 of file access-builder.cc.
                                                          {
  FieldAccess access = {
      kTaggedBase,
      JSTypedArray::kExternalPointerOffset,
      MaybeHandle<Name>(),
      OptionalMapRef(),
#ifdef V8_ENABLE_SANDBOX
      Type::SandboxedPointer(),
      MachineType::SandboxedPointer(),
#else
      Type::ExternalPointer(),
      MachineType::Pointer(),
#endif
      kNoWriteBarrier,
      "JSTypedArrayExternalPointer",
      ConstFieldInfo::None(),
      false,
  };
  return access;
}
References v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::ConstFieldInfo::None(), v8::internal::MachineType::Pointer(), and v8::internal::MachineType::SandboxedPointer().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), and v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext().
ForMap()
FieldAccess v8::internal::compiler::AccessBuilder::ForMap (WriteBarrierKind write_barrier = kMapWriteBarrier) [static]
Definition at line 34 of file access-builder.cc.
                                                                {
  FieldAccess access = {kTaggedBase, HeapObject::kMapOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::OtherInternal(), MachineType::MapInHeader(),
                        write_barrier, "Map"};
  return access;
}
References v8::internal::HeapObject::kMapOffset, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::MapInHeader().
Referenced by v8::internal::compiler::AllocationBuilder::AllocateArray(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::AllocateBigInt(), v8::internal::compiler::AllocationBuilder::AllocateContext(), v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp(), v8::internal::compiler::AllocationBuilder::AllocateSloppyArgumentElements(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildByteLength(), v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildLength(), v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::compiler::JSNativeContextSpecialization::BuildLoadPrototypeFromObject(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::ExtendPropertiesBackingStore(), v8::internal::compiler::turboshaft::AccessBuilderTS::ForMap(), v8::internal::compiler::JSGraphAssembler::LoadMap(), v8::internal::compiler::JSCallReducer::LoadReceiverElementsKind(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::NewArray(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::NewConsString(), v8::internal::compiler::RawMachineAssembler::OptimizedStoreMap(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::JSIntrinsicLowering::ReduceIsInstanceType(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateIterResultObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateKeyValueArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreatePromise(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringWrapper(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeToStringTag(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TransitionElementsKind(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::TransitionElementsKind(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TransitionElementsKindOrCheckMap(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TransitionElementsTo(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::WasmAllocateArray(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::WasmAllocateStruct().
ForMapBitField()
FieldAccess v8::internal::compiler::AccessBuilder::ForMapBitField () [static]
Definition at line 794 of file access-builder.cc.
                                          {
  FieldAccess access = {kTaggedBase,
                        Map::kBitFieldOffset,
                        Handle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kUint8,
                        MachineType::Uint8(),
                        kNoWriteBarrier,
                        "MapBitField"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::TypeCache::kUint8, and v8::internal::MachineType::Uint8().
Referenced by v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::HasInPrototypeChain(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ObjectIs(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TruncateJSPrimitiveToUntagged().
ForMapBitField2()
FieldAccess v8::internal::compiler::AccessBuilder::ForMapBitField2 () [static]
Definition at line 807 of file access-builder.cc.
                                           {
  FieldAccess access = {kTaggedBase,
                        Map::kBitField2Offset,
                        Handle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kUint8,
                        MachineType::Uint8(),
                        kNoWriteBarrier,
                        "MapBitField2"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::TypeCache::kUint8, and v8::internal::MachineType::Uint8().
Referenced by v8::internal::compiler::JSGraphAssembler::LoadElementsKind(), v8::internal::compiler::JSCallReducerAssembler::LoadMapElementsKind(), v8::internal::compiler::JSCallReducer::LoadReceiverElementsKind(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ObjectIs(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeToStringTag(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TransitionAndStoreArrayElement().
ForMapBitField3()
FieldAccess v8::internal::compiler::AccessBuilder::ForMapBitField3 () [static]
Definition at line 820 of file access-builder.cc.
                                           {
  FieldAccess access = {kTaggedBase,
                        Map::kBitField3Offset,
                        Handle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kInt32,
                        MachineType::Int32(),
                        kNoWriteBarrier,
                        "MapBitField3"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::MachineType::Int32(), v8::internal::compiler::TypeCache::kInt32, v8::internal::compiler::kNoWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::MigrateInstanceOrDeopt(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::MigrateMapIfNeeded(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TryMigrateInstanceAndMarkMapAsMigrationTarget().
ForMapDescriptors()
FieldAccess v8::internal::compiler::AccessBuilder::ForMapDescriptors () [static]
Definition at line 833 of file access-builder.cc.
                                             {
  FieldAccess access = {kTaggedBase, Map::kInstanceDescriptorsOffset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::OtherInternal(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "MapDescriptors"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey().
ForMapInstanceType()
FieldAccess v8::internal::compiler::AccessBuilder::ForMapInstanceType () [static]
Definition at line 842 of file access-builder.cc.
                                              {
  FieldAccess access = {
      kTaggedBase, Map::kInstanceTypeOffset, Handle<Name>(),
      OptionalMapRef(), TypeCache::Get()->kUint16, MachineType::Uint16(),
      kNoWriteBarrier, "MapInstanceType"};
  access.is_immutable = true;
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::FieldAccess::is_immutable, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::TypeCache::kUint16, and v8::internal::MachineType::Uint16().
Referenced by v8::internal::compiler::JSIntrinsicLowering::ReduceIsInstanceType(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), and v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray().
ForMapNativeContext()
FieldAccess v8::internal::compiler::AccessBuilder::ForMapNativeContext () [static]
Definition at line 861 of file access-builder.cc.
                                               {
  FieldAccess access = {
      kTaggedBase, Map::kConstructorOrBackPointerOrNativeContextOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::Any(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "MapNativeContext"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::kConstructorOrBackPointerOrNativeContextOffset, v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
ForMapPrototype()
FieldAccess v8::internal::compiler::AccessBuilder::ForMapPrototype () [static]
Definition at line 852 of file access-builder.cc.
                                           {
  FieldAccess access = {kTaggedBase, Map::kPrototypeOffset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::Any(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "MapPrototype"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::kPointerWriteBarrier, v8::internal::kPrototypeOffset, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildLoadPrototypeFromObject(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::HasInPrototypeChain(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), and v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain().
ForModuleRegularExports()
FieldAccess v8::internal::compiler::AccessBuilder::ForModuleRegularExports () [static]
Definition at line 871 of file access-builder.cc.
                                                   {
  FieldAccess access = {
      kTaggedBase, SourceTextModule::kRegularExportsOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::OtherInternal(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "ModuleRegularExports"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSTypedLowering::BuildGetModuleCell().
ForModuleRegularImports()
FieldAccess v8::internal::compiler::AccessBuilder::ForModuleRegularImports () [static]
Definition at line 881 of file access-builder.cc.
                                                   {
  FieldAccess access = {
      kTaggedBase, SourceTextModule::kRegularImportsOffset,
      Handle<Name>(), OptionalMapRef(),
      Type::OtherInternal(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "ModuleRegularImports"};
  return access;
}
References v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSTypedLowering::BuildGetModuleCell().
ForNameDictionaryFlagsIndex()
FieldAccess v8::internal::compiler::AccessBuilder::ForNameDictionaryFlagsIndex () [static]
Definition at line 1489 of file access-builder.cc.
                                                       {
  FieldAccess access = {
      kTaggedBase,
      FixedArray::OffsetOfElementAt(NameDictionary::kFlagsIndex),
      MaybeHandle<Name>(),
      OptionalMapRef(),
      Type::SignedSmall(),
      MachineType::TaggedSigned(),
      kNoWriteBarrier,
      "NameDictionaryFlagsIndex"};
  return access;
}
References v8::internal::NameDictionary::kFlagsIndex, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), v8::internal::compiler::Type::SignedSmall(), and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject().
ForNameRawHashField()
FieldAccess v8::internal::compiler::AccessBuilder::ForNameRawHashField () [static]
Definition at line 891 of file access-builder.cc.
                                               {
  FieldAccess access = {kTaggedBase, offsetof(Name, raw_hash_field_),
                        Handle<Name>(), OptionalMapRef(),
                        Type::Unsigned32(), MachineType::Uint32(),
                        kNoWriteBarrier, "NameRawHashField"};
  return access;
}
References v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::Uint32().
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::NewConsString(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::StringHash().
ForOrderedHashMapEntryValue()
ElementAccess v8::internal::compiler::AccessBuilder::ForOrderedHashMapEntryValue () [static]
Definition at line 1451 of file access-builder.cc.
                                                         {
  ElementAccess const access = {kTaggedBase,
                                OrderedHashMap::HashTableStartOffset() +
                                    OrderedHashMap::kValueOffset * kTaggedSize,
                                Type::Any(), MachineType::AnyTagged(),
                                kFullWriteBarrier};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), v8::internal::OrderedHashTable< OrderedHashMap, 2 >::HashTableStartOffset(), v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::kTaggedSize, and v8::internal::OrderedHashMap::kValueOffset.
Referenced by v8::internal::compiler::JSCallReducer::ReduceMapPrototypeGet().
ForOrderedHashMapOrSetNextTable()
FieldAccess v8::internal::compiler::AccessBuilder::ForOrderedHashMapOrSetNextTable () [static]
Definition at line 1386 of file access-builder.cc.
                                                           {
  // TODO(turbofan): This will be redundant with the HashTableBase
  // methods above once the hash table unification is done.
  static_assert(OrderedHashMap::NextTableOffset() ==
                OrderedHashSet::NextTableOffset());
  FieldAccess const access = {
      kTaggedBase, OrderedHashMap::NextTableOffset(),
      MaybeHandle<Name>(), OptionalMapRef(),
      Type::Any(), MachineType::AnyTagged(),
      kFullWriteBarrier, "OrderedHashMapOrSetNextTable"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::OrderedHashTable< OrderedHashSet, 1 >::NextTableOffset(), and v8::internal::OrderedHashTable< OrderedHashMap, 2 >::NextTableOffset().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext().
ForOrderedHashMapOrSetNumberOfBuckets()
FieldAccess v8::internal::compiler::AccessBuilder::ForOrderedHashMapOrSetNumberOfBuckets () [static]
Definition at line 1400 of file access-builder.cc.
                                                                 {
  // TODO(turbofan): This will be redundant with the HashTableBase
  // methods above once the hash table unification is done.
  static_assert(OrderedHashMap::NumberOfBucketsOffset() ==
                OrderedHashSet::NumberOfBucketsOffset());
  FieldAccess const access = {kTaggedBase,
                              OrderedHashMap::NumberOfBucketsOffset(),
                              MaybeHandle<Name>(),
                              OptionalMapRef(),
                              TypeCache::Get()->kFixedArrayLengthType,
                              MachineType::TaggedSigned(),
                              kNoWriteBarrier,
                              "OrderedHashMapOrSetNumberOfBuckets"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::TypeCache::kFixedArrayLengthType, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::OrderedHashTable< OrderedHashSet, 1 >::NumberOfBucketsOffset(), v8::internal::OrderedHashTable< OrderedHashMap, 2 >::NumberOfBucketsOffset(), and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::FindOrderedHashEntry(), and v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext().
ForOrderedHashMapOrSetNumberOfDeletedElements()
FieldAccess v8::internal::compiler::AccessBuilder::ForOrderedHashMapOrSetNumberOfDeletedElements () [static]
Definition at line 1417 of file access-builder.cc.
                                                                         {
  // TODO(turbofan): This will be redundant with the HashTableBase
  // methods above once the hash table unification is done.
  static_assert(OrderedHashMap::NumberOfDeletedElementsOffset() ==
                OrderedHashSet::NumberOfDeletedElementsOffset());
  FieldAccess const access = {kTaggedBase,
                              OrderedHashMap::NumberOfDeletedElementsOffset(),
                              MaybeHandle<Name>(),
                              OptionalMapRef(),
                              TypeCache::Get()->kFixedArrayLengthType,
                              MachineType::TaggedSigned(),
                              kNoWriteBarrier,
                              "OrderedHashMapOrSetNumberOfDeletedElements"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::TypeCache::kFixedArrayLengthType, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::OrderedHashTable< OrderedHashSet, 1 >::NumberOfDeletedElementsOffset(), v8::internal::OrderedHashTable< OrderedHashMap, 2 >::NumberOfDeletedElementsOffset(), and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext().
ForOrderedHashMapOrSetNumberOfElements()
FieldAccess v8::internal::compiler::AccessBuilder::ForOrderedHashMapOrSetNumberOfElements () [static]
Definition at line 1434 of file access-builder.cc.
                                                                  {
  // TODO(turbofan): This will be redundant with the HashTableBase
  // methods above once the hash table unification is done.
  static_assert(OrderedHashMap::NumberOfElementsOffset() ==
                OrderedHashSet::NumberOfElementsOffset());
  FieldAccess const access = {kTaggedBase,
                              OrderedHashMap::NumberOfElementsOffset(),
                              MaybeHandle<Name>(),
                              OptionalMapRef(),
                              TypeCache::Get()->kFixedArrayLengthType,
                              MachineType::TaggedSigned(),
                              kNoWriteBarrier,
                              "OrderedHashMapOrSetNumberOfElements"};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::TypeCache::kFixedArrayLengthType, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::OrderedHashTable< OrderedHashSet, 1 >::NumberOfElementsOffset(), v8::internal::OrderedHashTable< OrderedHashMap, 2 >::NumberOfElementsOffset(), and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), and v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeSize().
ForPropertyArrayLengthAndHash()
FieldAccess v8::internal::compiler::AccessBuilder::ForPropertyArrayLengthAndHash () [static]
Definition at line 774 of file access-builder.cc.
                                                         {
  FieldAccess access = {
      kTaggedBase, PropertyArray::kLengthAndHashOffset,
      MaybeHandle<Name>(), OptionalMapRef(),
      Type::SignedSmall(), MachineType::TaggedSigned(),
      kNoWriteBarrier, "PropertyArrayLengthAndHash"};
  return access;
}
References v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::Type::SignedSmall(), and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), and v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::ExtendPropertiesBackingStore().
ForPropertyArraySlot()
FieldAccess v8::internal::compiler::AccessBuilder::ForPropertyArraySlot (int index) [static]
Definition at line 1102 of file access-builder.cc.
                                                         {
  int offset = PropertyArray::OffsetOfElementAt(index);
  FieldAccess access = {kTaggedBase, offset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::Any(), MachineType::AnyTagged(),
                        kFullWriteBarrier, "PropertyArraySlot"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), v8::internal::index, v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::PropertyArray::OffsetOfElementAt().
Referenced by v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::ExtendPropertiesBackingStore().
ForScopeInfoFlags()
FieldAccess v8::internal::compiler::AccessBuilder::ForScopeInfoFlags () [static]
Definition at line 1130 of file access-builder.cc.
                                             {
  FieldAccess access = {kTaggedBase, ScopeInfo::kFlagsOffset,
                        MaybeHandle<Name>(), OptionalMapRef(),
                        Type::Unsigned32(), MachineType::Uint32(),
                        kNoWriteBarrier, "ScopeInfoFlags"};
  return access;
}
References v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::Uint32().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension().
ForSeqOneByteStringCharacter()
ElementAccess v8::internal::compiler::AccessBuilder::ForSeqOneByteStringCharacter () [static]
Definition at line 984 of file access-builder.cc.
                                                          {
  ElementAccess access = {kTaggedBase, OFFSET_OF_DATA_START(SeqOneByteString),
                          TypeCache::Get()->kUint8, MachineType::Uint8(),
                          kNoWriteBarrier};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::TypeCache::kUint8, OFFSET_OF_DATA_START, and v8::internal::MachineType::Uint8().
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::AdaptFastCallArgument(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadFromSeqString(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StringPrepareForGetCodeUnit().
ForSeqTwoByteStringCharacter()
ElementAccess v8::internal::compiler::AccessBuilder::ForSeqTwoByteStringCharacter () [static]
Definition at line 992 of file access-builder.cc.
                                                          {
  ElementAccess access = {kTaggedBase, OFFSET_OF_DATA_START(SeqTwoByteString),
                          TypeCache::Get()->kUint16, MachineType::Uint16(),
                          kNoWriteBarrier};
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::TypeCache::kUint16, OFFSET_OF_DATA_START, and v8::internal::MachineType::Uint16().
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadFromSeqString(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StringPrepareForGetCodeUnit().
ForSlicedStringOffset()
FieldAccess v8::internal::compiler::AccessBuilder::ForSlicedStringOffset () [static]
Definition at line 946 of file access-builder.cc.
                                                 {
  FieldAccess access = {kTaggedBase, offsetof(SlicedString, offset_),
                        Handle<Name>(), OptionalMapRef(),
                        Type::SignedSmall(), MachineType::TaggedSigned(),
                        kNoWriteBarrier, "SlicedStringOffset"};
  access.is_immutable = true;
  return access;
}
References v8::internal::compiler::FieldAccess::is_immutable, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::Type::SignedSmall(), and v8::internal::MachineType::TaggedSigned().
Referenced by v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StringPrepareForGetCodeUnit().
ForSlicedStringParent()
FieldAccess v8::internal::compiler::AccessBuilder::ForSlicedStringParent () [static]
Definition at line 956 of file access-builder.cc.
                                                 {
  FieldAccess access = {kTaggedBase, offsetof(SlicedString, parent_),
                        Handle<Name>(), OptionalMapRef(),
                        Type::String(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "SlicedStringParent"};
  access.is_immutable = true;
  return access;
}
References v8::internal::compiler::FieldAccess::is_immutable, v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StringPrepareForGetCodeUnit().
ForSloppyArgumentsElementsArguments()
FieldAccess v8::internal::compiler::AccessBuilder::ForSloppyArgumentsElementsArguments () [static]
Definition at line 764 of file access-builder.cc.
                                                               {
  FieldAccess access = {
      kTaggedBase, offsetof(SloppyArgumentsElements, arguments_),
      MaybeHandle<Name>(), OptionalMapRef(),
      Type::Any(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "SloppyArgumentsElementsArguments"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments().
ForSloppyArgumentsElementsContext()
FieldAccess v8::internal::compiler::AccessBuilder::ForSloppyArgumentsElementsContext () [static]
Definition at line 754 of file access-builder.cc.
                                                             {
  FieldAccess access = {
      kTaggedBase, offsetof(SloppyArgumentsElements, context_),
      MaybeHandle<Name>(), OptionalMapRef(),
      Type::Any(), MachineType::TaggedPointer(),
      kPointerWriteBarrier, "SloppyArgumentsElementsContext"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments().
ForSloppyArgumentsElementsMappedEntry()
ElementAccess v8::internal::compiler::AccessBuilder::ForSloppyArgumentsElementsMappedEntry () [static]
Definition at line 1191 of file access-builder.cc.
                                                                   {
  ElementAccess access = {
      kTaggedBase, OFFSET_OF_DATA_START(SloppyArgumentsElements), Type::Any(),
      MachineType::AnyTagged(), kFullWriteBarrier};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kTaggedBase, and OFFSET_OF_DATA_START.
Referenced by v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments().
ForStringLength()
FieldAccess v8::internal::compiler::AccessBuilder::ForStringLength () [static]
Definition at line 900 of file access-builder.cc.
                                           {
  FieldAccess access = {kTaggedBase,
                        offsetof(String, length_),
                        Handle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kStringLengthType,
                        MachineType::Uint32(),
                        kNoWriteBarrier,
                        "StringLength"};
  access.is_immutable = true;
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::FieldAccess::is_immutable, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::TypeCache::kStringLengthType, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::Uint32().
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::AdaptFastCallArgument(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::GenerateStringEqualBuiltinCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetStringIndexOf(), v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), v8::internal::compiler::WasmGraphAssembler::LoadStringLength(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadStringLength(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadSurrogatePairAt(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::NewConsString(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringEqImpl(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringLength(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringMeasureWtf16().
ForThinStringActual()
FieldAccess v8::internal::compiler::AccessBuilder::ForThinStringActual () [static]
Definition at line 936 of file access-builder.cc.
                                               {
  FieldAccess access = {kTaggedBase, offsetof(ThinString, actual_),
                        Handle<Name>(), OptionalMapRef(),
                        Type::String(), MachineType::TaggedPointer(),
                        kPointerWriteBarrier, "ThinStringActual"};
  access.is_immutable = true;
  return access;
}
References v8::internal::compiler::FieldAccess::is_immutable, v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::MachineType::TaggedPointer().
Referenced by v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::CheckedInternalizedString(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CheckEqualsInternalizedString(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StringPrepareForGetCodeUnit().
ForTypedArrayElement()
ElementAccess v8::internal::compiler::AccessBuilder::ForTypedArrayElement (ExternalArrayType type, bool is_external) [static]
Definition at line 1264 of file access-builder.cc.
                                                                    {
  BaseTaggedness taggedness = is_external ? kUntaggedBase : kTaggedBase;
  int header_size = is_external ? 0 : OFFSET_OF_DATA_START(ByteArray);
  switch (type) {
    case kExternalInt8Array: {
      ElementAccess access = {taggedness, header_size, Type::Signed32(),
                              MachineType::Int8(), kNoWriteBarrier};
      return access;
    }
    case kExternalUint8Array:
    case kExternalUint8ClampedArray: {
      ElementAccess access = {taggedness, header_size, Type::Unsigned32(),
                              MachineType::Uint8(), kNoWriteBarrier};
      return access;
    }
    case kExternalInt16Array: {
      ElementAccess access = {taggedness, header_size, Type::Signed32(),
                              MachineType::Int16(), kNoWriteBarrier};
      return access;
    }
    case kExternalUint16Array: {
      ElementAccess access = {taggedness, header_size, Type::Unsigned32(),
                              MachineType::Uint16(), kNoWriteBarrier};
      return access;
    }
    case kExternalInt32Array: {
      ElementAccess access = {taggedness, header_size, Type::Signed32(),
                              MachineType::Int32(), kNoWriteBarrier};
      return access;
    }
    case kExternalUint32Array: {
      ElementAccess access = {taggedness, header_size, Type::Unsigned32(),
                              MachineType::Uint32(), kNoWriteBarrier};
      return access;
    }
    case kExternalFloat16Array: {
      // Accesses to Float16Array use float16 raw bits because spotty native
      // fp16 support across architectures. See
      // MachineRepresentation::kFloat16RawBits, which is used during simplified
      // lowering to insert the correct conversions.
      ElementAccess access = {taggedness, header_size, Type::Number(),
                              MachineType::Uint16(), kNoWriteBarrier};
      return access;
    }
    case kExternalFloat32Array: {
      ElementAccess access = {taggedness, header_size, Type::Number(),
                              MachineType::Float32(), kNoWriteBarrier};
      return access;
    }
    case kExternalFloat64Array: {
      ElementAccess access = {taggedness, header_size, Type::Number(),
                              MachineType::Float64(), kNoWriteBarrier};
      return access;
    }
    case kExternalBigInt64Array: {
      ElementAccess access = {taggedness, header_size, Type::SignedBigInt64(),
                              MachineType::Int64(), kNoWriteBarrier};
      return access;
    }
    case kExternalBigUint64Array: {
      ElementAccess access = {taggedness, header_size, Type::UnsignedBigInt64(),
                              MachineType::Uint64(), kNoWriteBarrier};
      return access;
    }
  }
  UNREACHABLE();
}
References v8::internal::MachineType::Float32(), v8::internal::MachineType::Float64(), v8::internal::MachineType::Int16(), v8::internal::MachineType::Int32(), v8::internal::MachineType::Int64(), v8::internal::MachineType::Int8(), v8::internal::kExternalBigInt64Array, v8::internal::kExternalBigUint64Array, v8::internal::kExternalFloat16Array, v8::internal::kExternalFloat32Array, v8::internal::kExternalFloat64Array, v8::internal::kExternalInt16Array, v8::internal::kExternalInt32Array, v8::internal::kExternalInt8Array, v8::internal::kExternalUint16Array, v8::internal::kExternalUint32Array, v8::internal::kExternalUint8Array, v8::internal::kExternalUint8ClampedArray, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::kUntaggedBase, OFFSET_OF_DATA_START, v8::internal::tracing::type, v8::internal::MachineType::Uint16(), v8::internal::MachineType::Uint32(), v8::internal::MachineType::Uint64(), v8::internal::MachineType::Uint8(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::LoadDataViewElement(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::LoadTypedElement(), v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::StoreDataViewElement(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StoreTypedElement().
ForWeakFixedArrayElement()
ElementAccess v8::internal::compiler::AccessBuilder::ForWeakFixedArrayElement () [static]
Definition at line 1183 of file access-builder.cc.
                                                      {
  ElementAccess const access = {
      kTaggedBase, OFFSET_OF_DATA_START(WeakFixedArray), Type::Any(),
      MachineType::AnyTagged(), kFullWriteBarrier};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kTaggedBase, and OFFSET_OF_DATA_START.
ForWeakFixedArrayLength()
FieldAccess v8::internal::compiler::AccessBuilder::ForWeakFixedArrayLength () [static]
Definition at line 740 of file access-builder.cc.
                                                   {
  FieldAccess access = {kTaggedBase,
                        offsetof(WeakFixedArray, length_),
                        MaybeHandle<Name>(),
                        OptionalMapRef(),
                        TypeCache::Get()->kWeakFixedArrayLengthType,
                        MachineType::TaggedSigned(),
                        kNoWriteBarrier,
                        "WeakFixedArrayLength"};
  access.is_immutable = true;
  return access;
}
References v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::FieldAccess::is_immutable, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::compiler::TypeCache::kWeakFixedArrayLengthType, and v8::internal::MachineType::TaggedSigned().
ForWeakFixedArraySlot()
FieldAccess v8::internal::compiler::AccessBuilder::ForWeakFixedArraySlot (int index) [static]
Definition at line 1112 of file access-builder.cc.
                                                          {
  int offset = WeakFixedArray::OffsetOfElementAt(index);
  FieldAccess access = {kTaggedBase, offset,
                        Handle<Name>(), OptionalMapRef(),
                        Type::Any(), MachineType::AnyTagged(),
                        kFullWriteBarrier, "WeakFixedArraySlot"};
  return access;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), v8::internal::index, v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::OffsetOfElementAt().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/access-builder.h
/mnt/V8SourceCode/src/compiler/access-builder.cc