v8::internal::compiler::JSCloneObjectNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSCloneObjectNode (Node *node)
const CloneObjectParameters & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1220 of file js-operator.h.
Constructor & Destructor Documentation
JSCloneObjectNode()
constexpr v8::internal::compiler::JSCloneObjectNode::JSCloneObjectNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1222 of file js-operator.h.
                                                   : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSCloneObject, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const CloneObjectParameters& v8::internal::compiler::JSCloneObjectNode::Parameters () const [inline]
Definition at line 1226 of file js-operator.h.
                                                  {
    return CloneObjectParametersOf(node()->op());
  }
References v8::internal::compiler::CloneObjectParametersOf(), and v8::internal::compiler::NodeWrapper::node().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h