v8::internal::SmallOrderedHashMap Class Reference
#include <ordered-hash-table.h>
Public Member Functions
V8_EXPORT_PRIVATE bool HasKey (Isolate *isolate, DirectHandle< Object > key)
OBJECT_CONSTRUCTORS (SmallOrderedHashMap, SmallOrderedHashTable< SmallOrderedHashMap >)
Static Public Member Functions
static V8_EXPORT_PRIVATE MaybeHandle< SmallOrderedHashMap > Add (Isolate *isolate, Handle< SmallOrderedHashMap > table, DirectHandle< Object > key, DirectHandle< Object > value)
static V8_EXPORT_PRIVATE bool Delete (Isolate *isolate, Tagged< SmallOrderedHashMap > table, Tagged< Object > key)
static bool Is (DirectHandle< HeapObject > table)
static DirectHandle< Map > GetMap (RootsTable &roots)
static Handle< SmallOrderedHashMap > Rehash (Isolate *isolate, Handle< SmallOrderedHashMap > table, int new_capacity)
Static Public Attributes
static const int kKeyIndex = 0
static const int kValueIndex = 1
static const int kEntrySize = 2
static const int kPrefixSize = 0
Additional Inherited Members
Detailed Description
Definition at line 698 of file ordered-hash-table.h.
Member Function Documentation
Add()
MaybeHandle< SmallOrderedHashMap > v8::internal::SmallOrderedHashMap::Add (Isolate * isolate, Handle< SmallOrderedHashMap > table, DirectHandle< Object > key, DirectHandle< Object > value) [static]
Definition at line 768 of file ordered-hash-table.cc.
                                                          {
  if (table->HasKey(isolate, key)) return table;
  if (table->UsedCapacity() >= table->Capacity()) {
    MaybeHandle<SmallOrderedHashMap> new_table =
        SmallOrderedHashMap::Grow(isolate, table);
    if (!new_table.ToHandle(&table)) {
      return MaybeHandle<SmallOrderedHashMap>();
    }
  }
  DisallowGarbageCollection no_gc;
  Tagged<SmallOrderedHashMap> raw_table = *table;
  int hash = Object::GetOrCreateHash(*key, isolate).value();
  int nof = raw_table->NumberOfElements();
  // Read the existing bucket values.
  int bucket = raw_table->HashToBucket(hash);
  int previous_entry = raw_table->HashToFirstEntry(hash);
  // Insert a new entry at the end,
  int new_entry = nof + raw_table->NumberOfDeletedElements();
  raw_table->SetDataEntry(new_entry, SmallOrderedHashMap::kValueIndex, *value);
  raw_table->SetDataEntry(new_entry, SmallOrderedHashMap::kKeyIndex, *key);
  raw_table->SetFirstEntry(bucket, new_entry);
  raw_table->SetNextEntry(new_entry, previous_entry);
  // and update book keeping.
  raw_table->SetNumberOfElements(nof + 1);
  return table;
}
References v8::internal::GetOrCreateHash(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow(), v8::internal::key, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::MaybeHandle< T >::ToHandle(), and v8::internal::value.
Delete()
bool v8::internal::SmallOrderedHashMap::Delete (Isolate * isolate, Tagged< SmallOrderedHashMap > table, Tagged< Object > key) [static]
Definition at line 803 of file ordered-hash-table.cc.
                                                     {
  return SmallOrderedHashTable<SmallOrderedHashMap>::Delete(isolate, table,
                                                            key);
}
References v8::internal::key.
GetMap()
DirectHandle< Map > v8::internal::SmallOrderedHashMap::GetMap (RootsTable & roots) [inline], [static]
Definition at line 76 of file ordered-hash-table-inl.h.
                                                               {
  return roots.small_ordered_hash_map_map();
}
HasKey()
bool v8::internal::SmallOrderedHashMap::HasKey (Isolate * isolate, DirectHandle< Object > key)
Definition at line 810 of file ordered-hash-table.cc.
                                                                           {
  return SmallOrderedHashTable<SmallOrderedHashMap>::HasKey(isolate, key);
}
References v8::internal::key.
Is()
bool v8::internal::SmallOrderedHashMap::Is (DirectHandle< HeapObject > table) [inline], [static]
Definition at line 176 of file ordered-hash-table-inl.h.
                                                                  {
  return IsSmallOrderedHashMap(*table);
}
OBJECT_CONSTRUCTORS()
v8::internal::SmallOrderedHashMap::OBJECT_CONSTRUCTORS (SmallOrderedHashMap , SmallOrderedHashTable< SmallOrderedHashMap >)
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), and v8::internal::key.
Rehash()
Handle< SmallOrderedHashMap > v8::internal::SmallOrderedHashMap::Rehash (Isolate * isolate, Handle< SmallOrderedHashMap > table, int new_capacity) [static]
Definition at line 984 of file ordered-hash-table.cc.
                                                                           {
  return SmallOrderedHashTable<SmallOrderedHashMap>::Rehash(isolate, table,
                                                            new_capacity);
}
Member Data Documentation
kEntrySize
const int v8::internal::SmallOrderedHashMap::kEntrySize = 2 [static]
Definition at line 705 of file ordered-hash-table.h.
kKeyIndex
const int v8::internal::SmallOrderedHashMap::kKeyIndex = 0 [static]
Definition at line 703 of file ordered-hash-table.h.
kPrefixSize
const int v8::internal::SmallOrderedHashMap::kPrefixSize = 0 [static]
Definition at line 706 of file ordered-hash-table.h.
kValueIndex
const int v8::internal::SmallOrderedHashMap::kValueIndex = 1 [static]
Definition at line 704 of file ordered-hash-table.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/ordered-hash-table.h
/mnt/V8SourceCode/src/objects/ordered-hash-table-inl.h
/mnt/V8SourceCode/src/objects/ordered-hash-table.cc