v8::internal::wasm::JSPrototypesSetup Class Reference
Public Member Functions
JSPrototypesSetup (Isolate *isolate, base::Vector< const uint8_t > wire_bytes, const WasmModule *module, ErrorThrower *thrower, DirectHandleVector< Object > &sanitized_imports)
void SetInstanceData (DirectHandle< WasmTrustedInstanceData > instance_data, DirectHandle< WasmTrustedInstanceData > shared_instance_data)
void MaterializeDescriptorOptions (MaybeDirectHandle< JSReceiver > ffi)
void ConfigurePrototypes_Modular ()
void ConfigurePrototypes_Direct ()
Private Types
using ImportEntry = DescriptorsSectionIterator::ImportEntry
using DeclEntry = DescriptorsSectionIterator::DeclEntry
using GlobalEntry = DescriptorsSectionIterator::GlobalEntry
using ProtoConfig = DescriptorsSectionIterator::ProtoConfig
using Method = DescriptorsSectionIterator::Method
Private Member Functions
void MaterializeDescriptorOptionsImpl (MaybeDirectHandle< JSReceiver > ffi)
void ConfigurePrototypes_Modular_Impl ()
void ConfigurePrototypes_Direct_Impl ()
DirectHandle< String > GetString (WireBytesRef ref)
bool GetImportedObject (DirectHandle< JSReceiver > holder, DirectHandle< String > name, const char *description_for_error, DirectHandle< JSReceiver > *out)
MaybeDirectHandle< WasmExportedFunction > GetExportedFunction (uint32_t export_index)
DirectHandle< WasmExportedFunction > GetFunction (uint32_t index)
Tagged< Map > GetRttInGlobal (uint32_t global_index, const char *description_for_error)
bool IsDescriptorGlobal (const WasmGlobal &global)
DirectHandle< JSFunction > MakeConstructor (WireBytesRef name_ref, DirectHandle< JSFunction > wasm_function, DirectHandle< JSPrototype > prototype)
void ToDictionaryMode (DirectHandle< JSReceiver > prototype, int num_methods)
bool InstallMethodByExportIndex (DirectHandle< JSReceiver > object, const Method &method)
bool InstallMethodByFunctionIndex (DirectHandle< JSReceiver > object, const Method &method)
bool InstallMethodImpl (DirectHandle< JSReceiver > object, const Method &method, DirectHandle< WasmExportedFunction > function)
void InstallExport (DirectHandle< String > name, DirectHandle< Object > value)
Private Attributes
Isolate * isolate_
base::Vector< const uint8_t > wire_bytes_
const WasmModule * module_
ErrorThrower * thrower_
DirectHandle< WasmTrustedInstanceData > trusted_instance_data_
DirectHandle< WasmTrustedInstanceData > shared_instance_data_
DirectHandle< JSObject > exports_object_
DirectHandleVector< Object > & sanitized_imports_
DescriptorsSectionIterator it_
uint32_t max_import_index_
uint32_t max_export_index_ {0}
Detailed Description
Definition at line 796 of file module-instantiate.cc.
Member Typedef Documentation
DeclEntry
using v8::internal::wasm::JSPrototypesSetup::DeclEntry = DescriptorsSectionIterator::DeclEntry [private]
Definition at line 851 of file module-instantiate.cc.
GlobalEntry
using v8::internal::wasm::JSPrototypesSetup::GlobalEntry = DescriptorsSectionIterator::GlobalEntry [private]
Definition at line 852 of file module-instantiate.cc.
ImportEntry
using v8::internal::wasm::JSPrototypesSetup::ImportEntry = DescriptorsSectionIterator::ImportEntry [private]
Definition at line 850 of file module-instantiate.cc.
Method
using v8::internal::wasm::JSPrototypesSetup::Method = DescriptorsSectionIterator::Method [private]
Definition at line 854 of file module-instantiate.cc.
ProtoConfig
using v8::internal::wasm::JSPrototypesSetup::ProtoConfig = DescriptorsSectionIterator::ProtoConfig [private]
Definition at line 853 of file module-instantiate.cc.
Constructor & Destructor Documentation
JSPrototypesSetup()
v8::internal::wasm::JSPrototypesSetup::JSPrototypesSetup (Isolate * isolate, base::Vector< const uint8_t > wire_bytes, const WasmModule * module, ErrorThrower * thrower, DirectHandleVector< Object > & sanitized_imports) [inline]
Definition at line 798 of file module-instantiate.cc.
      : isolate_(isolate),
        wire_bytes_(wire_bytes),
        module_(module),
        thrower_(thrower),
        sanitized_imports_(sanitized_imports),
        it_(wire_bytes, module->descriptors_section.offset(),
            module->descriptors_section.end_offset()),
        max_import_index_(static_cast<uint32_t>(sanitized_imports.size())),
        max_export_index_(static_cast<uint32_t>(module_->export_table.size())) {
  }
Member Function Documentation
ConfigurePrototypes_Direct()
void v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct () [inline]
Definition at line 842 of file module-instantiate.cc.
                                    {
    if (!v8_flags.wasm_implicit_prototypes) return;
    if (!it_.ok()) return;
    ConfigurePrototypes_Direct_Impl();
    if (!it_.ok()) thrower_->CompileFailed(it_.error());
  }
References v8::internal::wasm::ErrorThrower::CompileFailed(), ConfigurePrototypes_Direct_Impl(), v8::internal::wasm::Decoder::error(), it_, v8::internal::wasm::Decoder::ok(), thrower_, and v8::internal::v8_flags.
ConfigurePrototypes_Direct_Impl()
void v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl () [inline], [private]
Definition at line 972 of file module-instantiate.cc.
                                         {
    DCHECK(!trusted_instance_data_.is_null());
    if (!v8_flags.wasm_explicit_prototypes) it_.SkipToGlobalEntries();
    uint32_t max_global_index = static_cast<uint32_t>(module_->globals.size());
    uint32_t max_function_index =
        static_cast<uint32_t>(module_->functions.size());
    while (it_.has_global_entry()) {
      // Fetch the descriptor from the global and extract its RTT.
      GlobalEntry global_entry = it_.NextGlobalEntry(max_global_index);
      if (!it_.ok()) return;
      Tagged<Map> rtt =
          GetRttInGlobal(global_entry.global_index(), "installing a prototype");
      if (rtt.is_null()) return;
      DirectHandle<Map> described_rtt(rtt, isolate_);
      DirectHandle<JSPrototype> parent = isolate_->initial_object_prototype();
      if (global_entry.has_parent()) {
        uint32_t parent_index = global_entry.Parent();
        if (!it_.ok()) return;
        Tagged<Map> parent_rtt =
            GetRttInGlobal(parent_index, "being a prototype parent");
        if (parent_rtt.is_null()) return;
        parent = direct_handle(parent_rtt->prototype(), isolate_);
      }
      // Allocate, install, and populate the prototype as requested.
      DirectHandle<JSObject> prototype =
          WasmStruct::AllocatePrototype(isolate_, parent);
      Map::SetPrototype(isolate_, described_rtt, prototype);
      if (global_entry.has_method()) {
        ToDictionaryMode(prototype, global_entry.estimated_number_of_methods());
      }
      while (global_entry.has_method()) {
        Method method = global_entry.NextMethod(max_function_index);
        if (!it_.ok()) return;
        if (!InstallMethodByFunctionIndex(prototype, method)) return;
      }
      // Constructor function, if any.
      if (!global_entry.has_constructor()) continue;
      auto [constructor_name_ref, constructor_index] =
          global_entry.Constructor(max_function_index);
      if (!it_.ok()) return;
      DirectHandle<JSFunction> function = GetFunction(constructor_index);
      DCHECK_EQ(function->length(),
                module_->functions[constructor_index].sig->parameter_count());
      DirectHandle<JSFunction> constructor =
          MakeConstructor(constructor_name_ref, function, prototype);
      // Static methods/accessors on the constructor, if any.
      if (!global_entry.has_static()) continue;
      ToDictionaryMode(constructor, global_entry.estimated_number_of_statics());
      do {
        Method staticmethod = global_entry.NextStatic(max_function_index);
        if (!it_.ok()) return;
        if (!InstallMethodByFunctionIndex(constructor, staticmethod)) return;
      } while (global_entry.has_static());
    }
  }
References v8::internal::WasmStruct::AllocatePrototype(), v8::internal::wasm::DescriptorsSectionIterator::Entry::Constructor(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::wasm::DescriptorsSectionIterator::Entry::estimated_number_of_methods(), v8::internal::wasm::DescriptorsSectionIterator::Entry::estimated_number_of_statics(), v8::internal::wasm::WasmModule::functions, GetFunction(), GetRttInGlobal(), v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::global_index(), v8::internal::wasm::WasmModule::globals, v8::internal::wasm::DescriptorsSectionIterator::Entry::has_constructor(), v8::internal::wasm::DescriptorsSectionIterator::has_global_entry(), v8::internal::wasm::DescriptorsSectionIterator::Entry::has_method(), v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::has_parent(), v8::internal::wasm::DescriptorsSectionIterator::Entry::has_static(), InstallMethodByFunctionIndex(), v8::internal::Tagged< HeapObject >::is_null(), isolate_, it_, MakeConstructor(), module_, v8::internal::wasm::DescriptorsSectionIterator::NextGlobalEntry(), v8::internal::wasm::DescriptorsSectionIterator::Entry::NextMethod(), v8::internal::wasm::DescriptorsSectionIterator::Entry::NextStatic(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::Parent(), v8::internal::prototype, v8::internal::Map::SetPrototype(), v8::internal::wasm::DescriptorsSectionIterator::SkipToGlobalEntries(), ToDictionaryMode(), trusted_instance_data_, and v8::internal::v8_flags.
Referenced by ConfigurePrototypes_Direct().
ConfigurePrototypes_Modular()
void v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular () [inline]
Definition at line 831 of file module-instantiate.cc.
                                     {
    if (!it_.ok()) return;
    ConfigurePrototypes_Modular_Impl();
    if (!it_.ok()) thrower_->CompileFailed(it_.error());
  }
References v8::internal::wasm::ErrorThrower::CompileFailed(), ConfigurePrototypes_Modular_Impl(), v8::internal::wasm::Decoder::error(), it_, v8::internal::wasm::Decoder::ok(), and thrower_.
ConfigurePrototypes_Modular_Impl()
void v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl () [inline], [private]
Definition at line 922 of file module-instantiate.cc.
                                          {
    DCHECK(!trusted_instance_data_.is_null());
    if (!v8_flags.wasm_implicit_prototypes) it_.SkipToProtoConfigs();
    while (it_.has_proto_config()) {
      ProtoConfig proto_config = it_.NextProtoConfig(max_import_index_);
      if (!it_.ok()) return;
      uint32_t import_index = proto_config.import_index();
      if (!IsWasmDescriptorOptions(*sanitized_imports_[import_index])) {
        thrower_->LinkError("import %u must be a descriptor", import_index);
        return;
      }
      DirectHandle<WasmDescriptorOptions> desc =
          Cast<WasmDescriptorOptions>(sanitized_imports_[import_index]);
      DirectHandle<JSReceiver> prototype(Cast<JSReceiver>(desc->prototype()),
                                         isolate_);
      if (proto_config.has_method()) {
        ToDictionaryMode(prototype, proto_config.estimated_number_of_methods());
      }
      while (proto_config.has_method()) {
        Method method = proto_config.NextMethod(max_export_index_);
        if (!it_.ok()) return;
        if (!InstallMethodByExportIndex(prototype, method)) return;
      }
      // Constructor function, if any.
      if (!proto_config.has_constructor()) continue;
      auto [constructor_name_ref, constructor_index] =
          proto_config.Constructor(max_export_index_);
      if (!it_.ok()) return;
      DirectHandle<JSFunction> function;
      if (!GetExportedFunction(constructor_index).ToHandle(&function)) return;
      DirectHandle<JSFunction> constructor =
          MakeConstructor(constructor_name_ref, function, prototype);
      // Static methods/accessors on the constructor, if any.
      if (!proto_config.has_static()) continue;
      int num_methods = proto_config.estimated_number_of_statics();
      JSObject::NormalizeProperties(isolate_, constructor,
                                    KEEP_INOBJECT_PROPERTIES, num_methods,
                                    "Wasm constructor setup");
      do {
        Method staticmethod = proto_config.NextStatic(max_export_index_);
        if (!it_.ok()) return;
        if (!InstallMethodByExportIndex(constructor, staticmethod)) return;
      } while (proto_config.has_static());
    }
  }
References v8::internal::wasm::DescriptorsSectionIterator::Entry::Constructor(), v8::internal::DCHECK(), v8::internal::wasm::DescriptorsSectionIterator::Entry::estimated_number_of_methods(), v8::internal::wasm::DescriptorsSectionIterator::Entry::estimated_number_of_statics(), GetExportedFunction(), v8::internal::wasm::DescriptorsSectionIterator::Entry::has_constructor(), v8::internal::wasm::DescriptorsSectionIterator::Entry::has_method(), v8::internal::wasm::DescriptorsSectionIterator::has_proto_config(), v8::internal::wasm::DescriptorsSectionIterator::Entry::has_static(), v8::internal::wasm::DescriptorsSectionIterator::ProtoConfig::import_index(), InstallMethodByExportIndex(), isolate_, it_, v8::internal::KEEP_INOBJECT_PROPERTIES, MakeConstructor(), max_export_index_, max_import_index_, v8::internal::wasm::DescriptorsSectionIterator::Entry::NextMethod(), v8::internal::wasm::DescriptorsSectionIterator::NextProtoConfig(), v8::internal::wasm::DescriptorsSectionIterator::Entry::NextStatic(), v8::internal::JSObject::NormalizeProperties(), v8::internal::wasm::Decoder::ok(), v8::internal::prototype, sanitized_imports_, v8::internal::wasm::DescriptorsSectionIterator::SkipToProtoConfigs(), thrower_, ToDictionaryMode(), v8::anonymous_namespace{api.cc}::ToHandle(), trusted_instance_data_, and v8::internal::v8_flags.
Referenced by ConfigurePrototypes_Modular().
GetExportedFunction()
MaybeDirectHandle<WasmExportedFunction> v8::internal::wasm::JSPrototypesSetup::GetExportedFunction (uint32_t export_index) [inline], [private]
Definition at line 1055 of file module-instantiate.cc.
                             {
    const WasmExport& exp = module_->export_table[export_index];
    if (exp.kind != kExternalFunction) {
      thrower_->LinkError("export %u must be a function", export_index);
      return {};
    }
    bool shared = module_->function_is_shared(exp.index);
    Tagged<Object> funcref =
        (shared ? shared_instance_data_ : trusted_instance_data_)
            ->func_refs()
            ->get(exp.index);
    DCHECK(IsWasmFuncRef(funcref));
    Tagged<WasmInternalFunction> internal_func =
        Cast<WasmFuncRef>(funcref)->internal(isolate_);
    return direct_handle(Cast<WasmExportedFunction>(internal_func->external()),
                         isolate_);
  }
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::base::ieee754::exp(), v8::internal::wasm::WasmModule::export_table, v8::internal::func_refs, v8::internal::wasm::WasmModule::function_is_shared(), isolate_, v8::internal::wasm::kExternalFunction, module_, shared_instance_data_, thrower_, and trusted_instance_data_.
Referenced by ConfigurePrototypes_Modular_Impl(), and InstallMethodByExportIndex().
GetFunction()
DirectHandle<WasmExportedFunction> v8::internal::wasm::JSPrototypesSetup::GetFunction (uint32_t index) [inline], [private]
Definition at line 1074 of file module-instantiate.cc.
                                                                 {
    bool shared = module_->function_is_shared(index);
    DirectHandle<WasmFuncRef> funcref =
        WasmTrustedInstanceData::GetOrCreateFuncRef(
            isolate_, shared ? shared_instance_data_ : trusted_instance_data_,
            index);
    DirectHandle<WasmInternalFunction> internal_function(
        funcref->internal(isolate_), isolate_);
    return Cast<WasmExportedFunction>(
        WasmInternalFunction::GetOrCreateExternal(internal_function));
  }
References v8::internal::wasm::WasmModule::function_is_shared(), v8::internal::WasmInternalFunction::GetOrCreateExternal(), v8::internal::WasmTrustedInstanceData::GetOrCreateFuncRef(), v8::internal::index, isolate_, module_, shared_instance_data_, and trusted_instance_data_.
Referenced by ConfigurePrototypes_Direct_Impl(), and InstallMethodByFunctionIndex().
GetImportedObject()
bool v8::internal::wasm::JSPrototypesSetup::GetImportedObject (DirectHandle< JSReceiver > holder, DirectHandle< String > name, const char * description_for_error, DirectHandle< JSReceiver > * out) [inline], [private]
Definition at line 1039 of file module-instantiate.cc.
                                                        {
    DirectHandle<Object> value;
    if (!Object::GetPropertyOrElement(isolate_, holder, name)
             .ToHandle(&value) ||
        !TryCast<JSReceiver>(value, out)) {
      thrower_->LinkError("%s: %s not found or not an object",
                          name->ToCString().get(), description_for_error);
      return false;
    }
    return true;
  }
References v8::internal::Object::GetPropertyOrElement(), isolate_, v8::internal::wasm::name(), thrower_, v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::value.
Referenced by MaterializeDescriptorOptionsImpl().
GetRttInGlobal()
Tagged<Map> v8::internal::wasm::JSPrototypesSetup::GetRttInGlobal (uint32_t global_index, const char * description_for_error) [inline], [private]
Definition at line 1086 of file module-instantiate.cc.
                                                                {
    const WasmGlobal& global = module_->globals[global_index];
    if (!IsDescriptorGlobal(global)) {
      thrower_->CompileError("global %u has unsuitable type for %s",
                             global_index, description_for_error);
      return {};
    }
    auto data = global.shared ? shared_instance_data_ : trusted_instance_data_;
    Tagged<Object> value = data->tagged_globals_buffer()->get(global.offset);
    return Cast<WasmStruct>(value)->described_rtt();
  }
References v8::internal::wasm::WasmModule::globals, IsDescriptorGlobal(), module_, v8::internal::wasm::WasmGlobal::offset, v8::internal::wasm::WasmGlobal::shared, shared_instance_data_, thrower_, trusted_instance_data_, and v8::internal::value.
Referenced by ConfigurePrototypes_Direct_Impl().
GetString()
DirectHandle<String> v8::internal::wasm::JSPrototypesSetup::GetString (WireBytesRef ref) [inline], [private]
Definition at line 1034 of file module-instantiate.cc.
                                                   {
    return WasmModuleObject::ExtractUtf8StringFromModuleBytes(
        isolate_, wire_bytes_, ref, kInternalize);
  }
References v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes(), isolate_, v8::internal::kInternalize, and wire_bytes_.
Referenced by InstallMethodImpl(), MakeConstructor(), and MaterializeDescriptorOptionsImpl().
InstallExport()
void v8::internal::wasm::JSPrototypesSetup::InstallExport (DirectHandle< String > name, DirectHandle< Object > value) [inline], [private]
Definition at line 1179 of file module-instantiate.cc.
                                                                            {
    PropertyDetails details(
        PropertyKind::kData,
        static_cast<PropertyAttributes>(READ_ONLY | DONT_DELETE),
        PropertyConstness::kMutable);
    uint32_t array_index;
    if (V8_UNLIKELY(name->AsArrayIndex(&array_index))) {
      JSObject::AddDataElement(isolate_, exports_object_, array_index, value,
                               details.attributes());
    } else {
      JSObject::SetNormalizedProperty(exports_object_, name, value, details);
    }
  }
References v8::internal::JSObject::AddDataElement(), v8::internal::PropertyDetails::attributes(), v8::internal::DONT_DELETE, exports_object_, isolate_, v8::internal::kData, v8::internal::kMutable, v8::internal::wasm::name(), v8::internal::READ_ONLY, v8::internal::JSObject::SetNormalizedProperty(), V8_UNLIKELY, and v8::internal::value.
Referenced by MakeConstructor().
InstallMethodByExportIndex()
bool v8::internal::wasm::JSPrototypesSetup::InstallMethodByExportIndex (DirectHandle< JSReceiver > object, const Method & method) [inline], [private]
Definition at line 1140 of file module-instantiate.cc.
                                                        {
    DirectHandle<WasmExportedFunction> function;
    if (!GetExportedFunction(method.index).ToHandle(&function)) return false;
    return InstallMethodImpl(object, method, function);
  }
References GetExportedFunction(), v8::internal::wasm::DescriptorsSectionIterator::Method::index, and InstallMethodImpl().
Referenced by ConfigurePrototypes_Modular_Impl().
InstallMethodByFunctionIndex()
bool v8::internal::wasm::JSPrototypesSetup::InstallMethodByFunctionIndex (DirectHandle< JSReceiver > object, const Method & method) [inline], [private]
Definition at line 1146 of file module-instantiate.cc.
                                                          {
    DirectHandle<WasmExportedFunction> function = GetFunction(method.index);
    return InstallMethodImpl(object, method, function);
  }
References GetFunction(), v8::internal::wasm::DescriptorsSectionIterator::Method::index, and InstallMethodImpl().
Referenced by ConfigurePrototypes_Direct_Impl().
InstallMethodImpl()
bool v8::internal::wasm::JSPrototypesSetup::InstallMethodImpl (DirectHandle< JSReceiver > object, const Method & method, DirectHandle< WasmExportedFunction > function) [inline], [private]
Definition at line 1151 of file module-instantiate.cc.
                                                                      {
    DirectHandle<String> method_name = GetString(method.name);
    if (!method.is_static) {
      WasmExportedFunction::MarkAsReceiverIsFirstParam(isolate_, function);
    }
    PropertyDescriptor prop;
    prop.set_enumerable(false);
    prop.set_configurable(true);
    if (method.kind == Method::kMethod) {
      prop.set_writable(true);
      prop.set_value(function);
    } else if (method.kind == Method::kGetter) {
      prop.set_get(function);
    } else if (method.kind == Method::kSetter) {
      prop.set_set(function);
    } else {
      UNREACHABLE(); // Ruled out by validation.
    }
    if (!JSReceiver::DefineOwnProperty(isolate_, object, method_name, &prop,
                                       Just(ShouldThrow::kThrowOnError))
             .FromMaybe(false)) {
      DCHECK(isolate_->has_exception());
      return false;
    }
    return true;
  }
References v8::internal::DCHECK(), v8::internal::JSReceiver::DefineOwnProperty(), GetString(), v8::internal::Isolate::has_exception(), v8::internal::wasm::DescriptorsSectionIterator::Method::is_static, isolate_, v8::Just(), v8::internal::wasm::DescriptorsSectionIterator::Method::kGetter, v8::internal::wasm::DescriptorsSectionIterator::Method::kind, v8::internal::wasm::DescriptorsSectionIterator::Method::kMethod, v8::internal::wasm::DescriptorsSectionIterator::Method::kSetter, v8::internal::kThrowOnError, v8::internal::WasmExportedFunction::MarkAsReceiverIsFirstParam(), v8::internal::wasm::DescriptorsSectionIterator::Method::name, v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_get(), v8::internal::PropertyDescriptor::set_set(), v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), and v8::internal::UNREACHABLE().
Referenced by InstallMethodByExportIndex(), and InstallMethodByFunctionIndex().
IsDescriptorGlobal()
bool v8::internal::wasm::JSPrototypesSetup::IsDescriptorGlobal (const WasmGlobal & global) [inline], [private]
Definition at line 1099 of file module-instantiate.cc.
                                                    {
    return !global.mutability && global.initializer_ends_with_struct_new &&
           global.type.ref_type_kind() == RefTypeKind::kStruct &&
           global.type.has_index() &&
           module_->type(global.type.ref_index()).is_descriptor();
  }
References v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::WasmGlobal::initializer_ends_with_struct_new, v8::internal::wasm::TypeDefinition::is_descriptor(), v8::internal::wasm::kStruct, module_, v8::internal::wasm::WasmGlobal::mutability, v8::internal::wasm::ValueType::ref_index(), v8::internal::wasm::ValueTypeBase::ref_type_kind(), v8::internal::wasm::WasmGlobal::type, and v8::internal::wasm::WasmModule::type().
Referenced by GetRttInGlobal().
MakeConstructor()
DirectHandle<JSFunction> v8::internal::wasm::JSPrototypesSetup::MakeConstructor (WireBytesRef name_ref, DirectHandle< JSFunction > wasm_function, DirectHandle< JSPrototype > prototype) [inline], [private]
Definition at line 1106 of file module-instantiate.cc.
                                           {
    DirectHandle<String> name = GetString(name_ref);
    DirectHandle<Context> context = isolate_->factory()->NewBuiltinContext(
        isolate_->native_context(), kConstructorFunctionContextLength);
    context->SetNoCell(kConstructorFunctionContextSlot, *wasm_function);
    Builtin code = Builtin::kWasmConstructorWrapper;
    int length = wasm_function->length();
    DirectHandle<SharedFunctionInfo> sfi =
        isolate_->factory()->NewSharedFunctionInfoForBuiltin(name, code, length,
                                                             kDontAdapt);
    sfi->set_native(true);
    sfi->set_language_mode(LanguageMode::kStrict);
    DirectHandle<JSFunction> constructor =
        Factory::JSFunctionBuilder{isolate_, sfi, context}
            .set_map(isolate_->strict_function_with_readonly_prototype_map())
            .Build();
    constructor->set_prototype_or_initial_map(*prototype, kReleaseStore);
    prototype->map()->SetConstructor(*constructor);
    InstallExport(name, constructor);
    return constructor;
  }
References code, v8::internal::Isolate::factory(), GetString(), InstallExport(), isolate_, v8::internal::wasm::kConstructorFunctionContextLength, v8::internal::wasm::kConstructorFunctionContextSlot, v8::internal::kDontAdapt, v8::kReleaseStore, v8::internal::kStrict, v8::internal::length, v8::internal::wasm::name(), v8::internal::Isolate::native_context(), v8::internal::Factory::NewBuiltinContext(), v8::internal::Factory::NewSharedFunctionInfoForBuiltin(), and v8::internal::prototype.
Referenced by ConfigurePrototypes_Direct_Impl(), and ConfigurePrototypes_Modular_Impl().
MaterializeDescriptorOptions()
void v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptions (MaybeDirectHandle< JSReceiver > ffi) [inline]
Definition at line 821 of file module-instantiate.cc.
                                                                       {
    if (!v8_flags.wasm_explicit_prototypes) return;
    if (!it_.ok()) return;
    MaterializeDescriptorOptionsImpl(ffi);
    if (!it_.ok()) thrower_->CompileFailed(it_.error());
  }
References v8::internal::wasm::ErrorThrower::CompileFailed(), v8::internal::wasm::Decoder::error(), it_, MaterializeDescriptorOptionsImpl(), v8::internal::wasm::Decoder::ok(), thrower_, and v8::internal::v8_flags.
MaterializeDescriptorOptionsImpl()
void v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl (MaybeDirectHandle< JSReceiver > ffi) [inline], [private]
Definition at line 858 of file module-instantiate.cc.
                                                                           {
    WireBytesRef module_name_ref = it_.module_name();
    DirectHandle<String> module_name = GetString(module_name_ref);
    size_t num_entries = it_.NumImportAndDeclEntries();
    uint32_t current_entry_index = 0;
    DirectHandleVector<JSPrototype> entries(isolate_, num_entries);
    // Import entries subsection.
    if (it_.has_import_entry()) {
      // Prepare the "module" sub-object of the imports object.
      if (ffi.is_null()) {
        thrower_->TypeError(
            "Imports argument must be present and must be an object");
        return;
      }
      DirectHandle<JSReceiver> module;
      if (!GetImportedObject(ffi.ToHandleChecked(), module_name, "module",
                             &module)) {
        return;
      }
      do {
        ImportEntry import_entry = it_.NextImportEntry();
        WireBytesRef name = import_entry.name();
        if (!import_entry.ok()) return;
        DirectHandle<String> import_name = GetString(name);
        DirectHandle<JSReceiver> prototype;
        if (!GetImportedObject(module, import_name, "import", &prototype)) {
          return;
        }
        DirectHandle<WasmDescriptorOptions> descriptor_options =
            WasmDescriptorOptions::New(isolate_, prototype);
        entries[current_entry_index++] = prototype;
        while (import_entry.has_export()) {
          uint32_t export_index = import_entry.NextExport(max_import_index_);
          if (!import_entry.ok()) return;
          sanitized_imports_[export_index] = descriptor_options;
        }
      } while (it_.ok() && it_.has_import_entry());
    }
    // Decl entries subsection.
    while (it_.ok() && it_.has_decl_entry()) {
      DeclEntry decl_entry = it_.NextDeclEntry();
      if (!it_.ok()) return;
      DirectHandle<JSPrototype> parent = isolate_->initial_object_prototype();
      if (decl_entry.has_parent()) {
        uint32_t parent_index = decl_entry.Parent(current_entry_index);
        if (!it_.ok()) return;
        parent = entries[parent_index];
      }
      DirectHandle<JSObject> prototype =
          WasmStruct::AllocatePrototype(isolate_, parent);
      DirectHandle<WasmDescriptorOptions> descriptor_options =
          WasmDescriptorOptions::New(isolate_, prototype);
      entries[current_entry_index++] = descriptor_options;
      while (decl_entry.has_export()) {
        uint32_t export_index = decl_entry.NextExport(max_import_index_);
        if (!decl_entry.ok()) return;
        sanitized_imports_[export_index] = descriptor_options;
      }
    }
  }
References v8::internal::WasmStruct::AllocatePrototype(), GetImportedObject(), GetString(), v8::internal::wasm::DescriptorsSectionIterator::has_decl_entry(), v8::internal::wasm::DescriptorsSectionIterator::Entry::has_export(), v8::internal::wasm::DescriptorsSectionIterator::has_import_entry(), v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::has_parent(), v8::internal::MaybeDirectHandle< T >::is_null(), isolate_, it_, max_import_index_, v8::internal::wasm::DescriptorsSectionIterator::module_name(), v8::internal::wasm::DescriptorsSectionIterator::ImportEntry::name(), v8::internal::wasm::name(), v8::internal::WasmDescriptorOptions::New(), v8::internal::wasm::DescriptorsSectionIterator::NextDeclEntry(), v8::internal::wasm::DescriptorsSectionIterator::Entry::NextExport(), v8::internal::wasm::DescriptorsSectionIterator::NextImportEntry(), v8::internal::wasm::DescriptorsSectionIterator::NumImportAndDeclEntries(), v8::internal::wasm::DescriptorsSectionIterator::Entry::ok(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::Parent(), v8::internal::prototype, sanitized_imports_, thrower_, and v8::internal::MaybeDirectHandle< T >::ToHandleChecked().
Referenced by MaterializeDescriptorOptions().
SetInstanceData()
void v8::internal::wasm::JSPrototypesSetup::SetInstanceData (DirectHandle< WasmTrustedInstanceData > instance_data, DirectHandle< WasmTrustedInstanceData > shared_instance_data) [inline]
Definition at line 812 of file module-instantiate.cc.
                                                                  {
    trusted_instance_data_ = instance_data;
    exports_object_ = direct_handle(
        instance_data->instance_object()->exports_object(), isolate_);
    shared_instance_data_ = shared_instance_data;
  }
References v8::internal::direct_handle(), exports_object_, v8::internal::instance_data, isolate_, shared_instance_data_, and trusted_instance_data_.
ToDictionaryMode()
void v8::internal::wasm::JSPrototypesSetup::ToDictionaryMode (DirectHandle< JSReceiver > prototype, int num_methods) [inline], [private]
Definition at line 1133 of file module-instantiate.cc.
                                                                             {
    if (!IsJSObject(*prototype) || !prototype->HasFastProperties()) return;
    JSObject::NormalizeProperties(isolate_, Cast<JSObject>(prototype),
                                  KEEP_INOBJECT_PROPERTIES, num_methods,
                                  "Wasm prototype setup");
  }
References isolate_, v8::internal::KEEP_INOBJECT_PROPERTIES, v8::internal::JSObject::NormalizeProperties(), and v8::internal::prototype.
Referenced by ConfigurePrototypes_Direct_Impl(), and ConfigurePrototypes_Modular_Impl().
Member Data Documentation
exports_object_
DirectHandle<JSObject> v8::internal::wasm::JSPrototypesSetup::exports_object_ [private]
Definition at line 1199 of file module-instantiate.cc.
Referenced by InstallExport(), and SetInstanceData().
isolate_
Isolate* v8::internal::wasm::JSPrototypesSetup::isolate_ [private]
Definition at line 1193 of file module-instantiate.cc.
Referenced by ConfigurePrototypes_Direct_Impl(), ConfigurePrototypes_Modular_Impl(), GetExportedFunction(), GetFunction(), GetImportedObject(), GetString(), InstallExport(), InstallMethodImpl(), MakeConstructor(), MaterializeDescriptorOptionsImpl(), SetInstanceData(), and ToDictionaryMode().
it_
DescriptorsSectionIterator v8::internal::wasm::JSPrototypesSetup::it_ [private]
Definition at line 1201 of file module-instantiate.cc.
Referenced by ConfigurePrototypes_Direct(), ConfigurePrototypes_Direct_Impl(), ConfigurePrototypes_Modular(), ConfigurePrototypes_Modular_Impl(), MaterializeDescriptorOptions(), and MaterializeDescriptorOptionsImpl().
max_export_index_
uint32_t v8::internal::wasm::JSPrototypesSetup::max_export_index_ {0} [private]
Definition at line 1203 of file module-instantiate.cc.
Referenced by ConfigurePrototypes_Modular_Impl().
max_import_index_
uint32_t v8::internal::wasm::JSPrototypesSetup::max_import_index_ [private]
Definition at line 1202 of file module-instantiate.cc.
Referenced by ConfigurePrototypes_Modular_Impl(), and MaterializeDescriptorOptionsImpl().
module_
const WasmModule* v8::internal::wasm::JSPrototypesSetup::module_ [private]
Definition at line 1195 of file module-instantiate.cc.
Referenced by ConfigurePrototypes_Direct_Impl(), GetExportedFunction(), GetFunction(), GetRttInGlobal(), and IsDescriptorGlobal().
sanitized_imports_
DirectHandleVector<Object>& v8::internal::wasm::JSPrototypesSetup::sanitized_imports_ [private]
Definition at line 1200 of file module-instantiate.cc.
Referenced by ConfigurePrototypes_Modular_Impl(), and MaterializeDescriptorOptionsImpl().
shared_instance_data_
DirectHandle<WasmTrustedInstanceData> v8::internal::wasm::JSPrototypesSetup::shared_instance_data_ [private]
Definition at line 1198 of file module-instantiate.cc.
Referenced by GetExportedFunction(), GetFunction(), GetRttInGlobal(), and SetInstanceData().
thrower_
ErrorThrower* v8::internal::wasm::JSPrototypesSetup::thrower_ [private]
Definition at line 1196 of file module-instantiate.cc.
Referenced by ConfigurePrototypes_Direct(), ConfigurePrototypes_Modular(), ConfigurePrototypes_Modular_Impl(), GetExportedFunction(), GetImportedObject(), GetRttInGlobal(), MaterializeDescriptorOptions(), and MaterializeDescriptorOptionsImpl().
trusted_instance_data_
DirectHandle<WasmTrustedInstanceData> v8::internal::wasm::JSPrototypesSetup::trusted_instance_data_ [private]
Definition at line 1197 of file module-instantiate.cc.
Referenced by ConfigurePrototypes_Direct_Impl(), ConfigurePrototypes_Modular_Impl(), GetExportedFunction(), GetFunction(), GetRttInGlobal(), and SetInstanceData().
wire_bytes_
base::Vector<const uint8_t> v8::internal::wasm::JSPrototypesSetup::wire_bytes_ [private]
Definition at line 1194 of file module-instantiate.cc.
Referenced by GetString().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-instantiate.cc