v8::internal::ETWJITInterface::EtwIsolateOperations Class Reference
#include <etw-isolate-operations-win.h>
Public Member Functions
virtual void SetEtwCodeEventHandler (Isolate *isolate, uint32_t options)
virtual void ResetEtwCodeEventHandler (Isolate *isolate)
virtual FilterETWSessionByURLResult RunFilterETWSessionByURLCallback (Isolate *isolate, const std::string &payload)
virtual void RequestInterrupt (Isolate *isolate, InterruptCallback callback, void *data)
virtual bool HeapReadOnlySpaceWritable (Isolate *isolate)
virtual std::optional< Tagged< GcSafeCode > > HeapGcSafeTryFindCodeForInnerPointer (Isolate *isolate, Address address)
Static Public Member Functions
static EtwIsolateOperations * Instance ()
static void SetInstanceForTesting (EtwIsolateOperations *etw_isolate_operations)
Static Private Attributes
static EtwIsolateOperations * instance = nullptr
Detailed Description
Definition at line 22 of file etw-isolate-operations-win.h.
Member Function Documentation
HeapGcSafeTryFindCodeForInnerPointer()
std::optional< Tagged< GcSafeCode > > v8::internal::ETWJITInterface::EtwIsolateOperations::HeapGcSafeTryFindCodeForInnerPointer (Isolate * isolate, Address address) [virtual]
Definition at line 53 of file etw-isolate-operations-win.cc.
                                                                            {
  return isolate->heap()->GcSafeTryFindCodeForInnerPointer(address);
}
References v8::internal::Heap::GcSafeTryFindCodeForInnerPointer(), and v8::internal::Isolate::heap().
Referenced by v8::internal::ETWJITInterface::EventHandler().
HeapReadOnlySpaceWritable()
bool v8::internal::ETWJITInterface::EtwIsolateOperations::HeapReadOnlySpaceWritable (Isolate * isolate) [virtual]
Definition at line 47 of file etw-isolate-operations-win.cc.
                                                                     {
  return isolate->heap()->read_only_space()->writable();
}
References v8::internal::Isolate::heap(), v8::internal::Heap::read_only_space(), and v8::internal::ReadOnlySpace::writable().
Instance()
EtwIsolateOperations * v8::internal::ETWJITInterface::EtwIsolateOperations::Instance () [static]
Definition at line 59 of file etw-isolate-operations-win.cc.
                                                     {
  static EtwIsolateOperations etw_isolate_operations;
  if (!instance) {
    instance = &etw_isolate_operations;
  }
  return instance;
}
References instance.
Referenced by v8::internal::ETWJITInterface::EventHandler(), and v8::internal::ETWJITInterface::MaybeSetHandlerNow().
RequestInterrupt()
void v8::internal::ETWJITInterface::EtwIsolateOperations::RequestInterrupt (Isolate * isolate, InterruptCallback callback, void * data) [virtual]
Definition at line 40 of file etw-isolate-operations-win.cc.
                                                        {
  isolate->RequestInterrupt(callback, data);
}
References v8::internal::Isolate::RequestInterrupt().
ResetEtwCodeEventHandler()
void v8::internal::ETWJITInterface::EtwIsolateOperations::ResetEtwCodeEventHandler (Isolate * isolate) [virtual]
Definition at line 25 of file etw-isolate-operations-win.cc.
                                                                    {
  isolate->v8_file_logger()->ResetEtwCodeEventHandler();
}
References v8::internal::Isolate::v8_file_logger().
RunFilterETWSessionByURLCallback()
FilterETWSessionByURLResult v8::internal::ETWJITInterface::EtwIsolateOperations::RunFilterETWSessionByURLCallback (Isolate * isolate, const std::string & payload) [virtual]
Definition at line 31 of file etw-isolate-operations-win.cc.
                                                {
  // We should not call back into V8 from the RunFilterETWSessionByURLCallback
  // callback.
  DisallowJavascriptExecution no_js(isolate);
  return isolate->RunFilterETWSessionByURLCallback(payload);
}
SetEtwCodeEventHandler()
void v8::internal::ETWJITInterface::EtwIsolateOperations::SetEtwCodeEventHandler (Isolate * isolate, uint32_t options) [virtual]
Definition at line 19 of file etw-isolate-operations-win.cc.
                                                                    {
  isolate->v8_file_logger()->SetEtwCodeEventHandler(options);
}
References v8::internal::Isolate::v8_file_logger().
SetInstanceForTesting()
void v8::internal::ETWJITInterface::EtwIsolateOperations::SetInstanceForTesting (EtwIsolateOperations * etw_isolate_operations) [static]
Definition at line 69 of file etw-isolate-operations-win.cc.
                                                  {
  instance = etw_isolate_operations;
}
References instance.
Member Data Documentation
instance
EtwIsolateOperations * v8::internal::ETWJITInterface::EtwIsolateOperations::instance = nullptr [static], [private]
Definition at line 40 of file etw-isolate-operations-win.h.
Referenced by Instance(), and SetInstanceForTesting().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/diagnostics/etw-isolate-operations-win.h
/mnt/V8SourceCode/src/diagnostics/etw-isolate-operations-win.cc