v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator Class Reference
Public Member Functions
FieldOffsetsGenerator (const ClassType *type)
virtual void WriteField (const Field &f, const std::string &size_string)=0
virtual void WriteFieldOffsetGetter (const Field &f)=0
virtual void WriteMarker (const std::string &marker)=0
virtual ~FieldOffsetsGenerator ()
void RecordOffsetFor (const Field &f)
void Finish ()
Protected Attributes
const ClassType * type_
Private Member Functions
FieldSectionType GetSectionFor (const Field &f)
void UpdateSection (const Field &f)
void Begin (FieldSectionType type)
void End (FieldSectionType type)
Private Attributes
FieldSectionType current_section_ = FieldSectionType::kNoSection
FieldSections completed_sections_ = FieldSectionType::kNoSection
bool is_finished_ = false
bool header_size_emitted_ = false
Detailed Description
Definition at line 3783 of file implementation-visitor.cc.
Constructor & Destructor Documentation
FieldOffsetsGenerator()
v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::FieldOffsetsGenerator (const ClassType * type) [inline], [explicit]
Definition at line 3785 of file implementation-visitor.cc.
: type_(type) {}
 FieldOffsetsGenerator()
virtual v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::~FieldOffsetsGenerator () [inline], [virtual]
Definition at line 3791 of file implementation-visitor.cc.
{ CHECK(is_finished_); }
References CHECK.
Member Function Documentation
Begin()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::Begin (FieldSectionType type) [inline], [private]
Definition at line 3900 of file implementation-visitor.cc.
                                    {
    DCHECK(type != FieldSectionType::kNoSection);
    if (!IsPointerSection(type)) return;
    WriteMarker("kStartOf" + ToString(type) + "Offset");
  }
References v8::internal::DCHECK(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::IsPointerSection(), v8::internal::ToString(), and v8::internal::tracing::type.
End()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::End (FieldSectionType type) [inline], [private]
Definition at line 3905 of file implementation-visitor.cc.
                                  {
    if (!IsPointerSection(type)) return;
    completed_sections_ |= type;
    WriteMarker("kEndOf" + ToString(type) + "Offset");
  }
References v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::IsPointerSection(), v8::internal::ToString(), and v8::internal::tracing::type.
Finish()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::Finish () [inline]
Definition at line 3817 of file implementation-visitor.cc.
                {
    End(current_section_);
    if (!(completed_sections_ & FieldSectionType::kWeakSection)) {
      Begin(FieldSectionType::kWeakSection);
      End(FieldSectionType::kWeakSection);
    }
    if (!(completed_sections_ & FieldSectionType::kStrongSection)) {
      Begin(FieldSectionType::kStrongSection);
      End(FieldSectionType::kStrongSection);
    }
    is_finished_ = true;
    // In the presence of indexed fields, we already emitted kHeaderSize before
    // the indexed field.
    if (!type_->IsShape() && !header_size_emitted_) {
      WriteMarker("kHeaderSize");
    }
    if (!type_->IsAbstract() && type_->HasStaticSize()) {
      WriteMarker("kSize");
    }
  }
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClass(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateCppObjectDefinitionAsserts(), and v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateCppObjectLayoutDefinitionAsserts().
GetSectionFor()
FieldSectionType v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::GetSectionFor (const Field & f) [inline], [private]
Definition at line 3843 of file implementation-visitor.cc.
                                                 {
    const Type* field_type = f.name_and_type.type;
    if (field_type == TypeOracle::GetVoidType()) {
      // Allow void type for marker constants of size zero.
      return current_section_;
    }
    StructType::Classification struct_contents =
        StructType::ClassificationFlag::kEmpty;
    if (auto field_as_struct = field_type->StructSupertype()) {
      struct_contents = (*field_as_struct)->ClassifyContents();
    }
    if ((struct_contents & StructType::ClassificationFlag::kStrongTagged) &&
        (struct_contents & StructType::ClassificationFlag::kWeakTagged)) {
      // It's okay for a struct to contain both strong and weak data. We'll just
      // treat the whole thing as weak. This is required for DescriptorEntry.
      struct_contents &= ~StructType::Classification(
          StructType::ClassificationFlag::kStrongTagged);
    }
    bool struct_contains_tagged_fields =
        (struct_contents & StructType::ClassificationFlag::kStrongTagged) ||
        (struct_contents & StructType::ClassificationFlag::kWeakTagged);
    if (struct_contains_tagged_fields &&
        (struct_contents & StructType::ClassificationFlag::kUntagged)) {
      // We can't declare what section a struct goes in if it has multiple
      // categories of data within.
      Error(
          "Classes do not support fields which are structs containing both "
          "tagged and untagged data.")
          .Position(f.pos);
    }
    if ((field_type->IsSubtypeOf(TypeOracle::GetStrongTaggedType()) ||
         struct_contents == StructType::ClassificationFlag::kStrongTagged) &&
        !f.custom_weak_marking) {
      return FieldSectionType::kStrongSection;
    } else if (field_type->IsSubtypeOf(TypeOracle::GetTaggedType()) ||
               struct_contains_tagged_fields) {
      return FieldSectionType::kWeakSection;
    } else {
      return FieldSectionType::kScalarSection;
    }
  }
References v8::internal::torque::Field::custom_weak_marking, v8::internal::torque::Error(), v8::internal::torque::Type::IsSubtypeOf(), v8::internal::swiss_table::kEmpty, v8::internal::torque::Field::name_and_type, v8::internal::torque::Field::pos, v8::internal::torque::MessageBuilder::Position(), v8::internal::torque::Type::StructSupertype(), and v8::internal::torque::NameAndType::type.
RecordOffsetFor()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::RecordOffsetFor (const Field & f) [inline]
Definition at line 3793 of file implementation-visitor.cc.
                                       {
    CHECK(!is_finished_);
    UpdateSection(f);
    // Emit kHeaderSize before any indexed field.
    if (f.index.has_value() && !header_size_emitted_) {
      WriteMarker("kHeaderSize");
      header_size_emitted_ = true;
    }
    // We don't know statically how much space an indexed field takes, so report
    // it as zero.
    std::string size_string = "0";
    if (!f.index.has_value()) {
      size_t field_size;
      std::tie(field_size, size_string) = f.GetFieldSizeInformation();
    }
    if (f.offset.has_value()) {
      WriteField(f, size_string);
    } else {
      WriteFieldOffsetGetter(f);
    }
  }
References CHECK, v8::internal::torque::Field::GetFieldSizeInformation(), v8::internal::torque::Field::index, v8::internal::torque::Field::offset, and v8::internal::string.
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClass(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateCppObjectDefinitionAsserts(), and v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateCppObjectLayoutDefinitionAsserts().
UpdateSection()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::UpdateSection (const Field & f) [inline], [private]
Definition at line 3884 of file implementation-visitor.cc.
                                     {
    FieldSectionType type = GetSectionFor(f);
    if (current_section_ == type) return;
    if (IsPointerSection(type)) {
      if (completed_sections_ & type) {
        std::stringstream s;
        s << "cannot declare field " << f.name_and_type.name << " in class "
          << type_->name() << ", because section " << ToString(type)
          << " to which it belongs has already been finished.";
        Error(s.str()).Position(f.pos);
      }
    }
    End(current_section_);
    current_section_ = type;
    Begin(current_section_);
  }
References v8::internal::torque::Error(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::IsPointerSection(), v8::internal::torque::NameAndType::name, v8::internal::torque::AggregateType::name(), v8::internal::torque::Field::name_and_type, v8::internal::torque::Field::pos, v8::internal::torque::MessageBuilder::Position(), v8::internal::ToString(), and v8::internal::tracing::type.
WriteField()
virtual void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::WriteField (const Field & f, const std::string & size_string) [pure virtual]
Implemented in v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator.
WriteFieldOffsetGetter()
virtual void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::WriteFieldOffsetGetter (const Field & f) [pure virtual]
Implemented in v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator.
WriteMarker()
virtual void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::WriteMarker (const std::string & marker) [pure virtual]
Implemented in v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator.
Member Data Documentation
completed_sections_
FieldSections v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::completed_sections_ = FieldSectionType::kNoSection [private]
Definition at line 3912 of file implementation-visitor.cc.
current_section_
FieldSectionType v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::current_section_ = FieldSectionType::kNoSection [private]
Definition at line 3911 of file implementation-visitor.cc.
header_size_emitted_
bool v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::header_size_emitted_ = false [private]
Definition at line 3914 of file implementation-visitor.cc.
is_finished_
bool v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::is_finished_ = false [private]
Definition at line 3913 of file implementation-visitor.cc.
type_
const ClassType* v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::type_ [protected]
Definition at line 3840 of file implementation-visitor.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/implementation-visitor.cc