v8::internal::DebugInfo Class Reference
#include <debug-objects.h>
Classes
class BodyDescriptor
Public Types
enum ExecutionMode : uint8_t { kBreakpoints = 0
, kSideEffects = kDebugExecutionMode
 }
enum SideEffectState { kNotComputed = 0
, kHasSideEffects = 1
, kRequiresRuntimeChecks = 2
, kHasNoSideEffect = 3
 }
Public Member Functions
bool IsEmpty () const
ExecutionMode DebugExecutionMode () const
void SetDebugExecutionMode (ExecutionMode value)
bool HasInstrumentedBytecodeArray ()
Tagged< BytecodeArray > OriginalBytecodeArray (Isolate *isolate)
Tagged< BytecodeArray > DebugBytecodeArray (Isolate *isolate)
bool HasBreakInfo () const
V8_EXPORT_PRIVATE void ClearBreakInfo (Isolate *isolate)
void SetBreakAtEntry ()
void ClearBreakAtEntry ()
bool BreakAtEntry () const
bool HasBreakPoint (Isolate *isolate, int source_position)
DirectHandle< Object > GetBreakPoints (Isolate *isolate, int source_position)
int GetBreakPointCount (Isolate *isolate)
bool CanBreakAtEntry () const
SideEffectState GetSideEffectState (Isolate *isolate)
bool HasCoverageInfo () const
void ClearCoverageInfo (Isolate *isolate)
Static Public Member Functions
static bool ClearBreakPoint (Isolate *isolate, DirectHandle< DebugInfo > debug_info, DirectHandle< BreakPoint > break_point)
static void SetBreakPoint (Isolate *isolate, DirectHandle< DebugInfo > debug_info, int source_position, DirectHandle< BreakPoint > break_point)
static DirectHandle< Object > FindBreakPointInfo (Isolate *isolate, DirectHandle< DebugInfo > debug_info, DirectHandle< BreakPoint > break_point)
Static Public Attributes
static const int kNoDebuggingId = 0
static const int kEstimatedNofBreakPointsInFunction = 4
Private Member Functions
Tagged< Object > GetBreakPointInfo (Isolate *isolate, int source_position)
Detailed Description
Definition at line 30 of file debug-objects.h.
Member Enumeration Documentation
ExecutionMode
enum v8::internal::DebugInfo::ExecutionMode : uint8_t
Enumerator
kBreakpoints
kSideEffects
Definition at line 40 of file debug-objects.h.
                     : uint8_t {
    kBreakpoints = 0,
    kSideEffects = kDebugExecutionMode
  };
SideEffectState
enum v8::internal::DebugInfo::SideEffectState
Enumerator
kNotComputed
kHasSideEffects
kRequiresRuntimeChecks
kHasNoSideEffect
Definition at line 112 of file debug-objects.h.
                       {
    kNotComputed = 0,
    kHasSideEffects = 1,
    kRequiresRuntimeChecks = 2,
    kHasNoSideEffect = 3,
  };
Member Function Documentation
BreakAtEntry()
bool v8::internal::DebugInfo::BreakAtEntry () const
Definition at line 72 of file debug-objects.cc.
                                   {
  return (flags(kRelaxedLoad) & kBreakAtEntry) != 0;
}
References v8::internal::flags, and v8::kRelaxedLoad.
CanBreakAtEntry()
bool v8::internal::DebugInfo::CanBreakAtEntry () const
Definition at line 76 of file debug-objects.cc.
                                      {
  return (flags(kRelaxedLoad) & kCanBreakAtEntry) != 0;
}
References v8::internal::flags, and v8::kRelaxedLoad.
Referenced by ClearBreakAtEntry(), and SetBreakAtEntry().
ClearBreakAtEntry()
void v8::internal::DebugInfo::ClearBreakAtEntry ()
Definition at line 67 of file debug-objects.cc.
                                  {
  DCHECK(CanBreakAtEntry());
  set_flags(flags(kRelaxedLoad) & ~kBreakAtEntry, kRelaxedStore);
}
References CanBreakAtEntry(), v8::internal::DCHECK(), v8::internal::flags, v8::kRelaxedLoad, and v8::kRelaxedStore.
ClearBreakInfo()
void v8::internal::DebugInfo::ClearBreakInfo (Isolate * isolate)
Definition at line 37 of file debug-objects.cc.
                                               {
  if (HasInstrumentedBytecodeArray()) {
    // If the function is currently running on the stack, we need to update the
    // bytecode pointers on the stack so they point to the original
    // BytecodeArray before releasing that BytecodeArray from this DebugInfo.
    // Otherwise, it could be flushed and cause problems on resume. See v8:9067.
    {
      RedirectActiveFunctions redirect_visitor(
          isolate, shared(),
          RedirectActiveFunctions::Mode::kUseOriginalBytecode);
      redirect_visitor.VisitThread(isolate, isolate->thread_local_top());
      isolate->thread_manager()->IterateArchivedThreads(&redirect_visitor);
    }
    SharedFunctionInfo::UninstallDebugBytecode(shared(), isolate);
  }
  set_break_points(ReadOnlyRoots(isolate).empty_fixed_array());
  int new_flags = flags(kRelaxedLoad);
  new_flags &= ~kHasBreakInfo & ~kPreparedForDebugExecution;
  new_flags &= ~kBreakAtEntry & ~kCanBreakAtEntry;
  new_flags &= ~kDebugExecutionMode;
  set_flags(new_flags, kRelaxedStore);
}
References v8::internal::flags, HasInstrumentedBytecodeArray(), v8::internal::ThreadManager::IterateArchivedThreads(), v8::kRelaxedLoad, v8::kRelaxedStore, v8::internal::RedirectActiveFunctions::kUseOriginalBytecode, v8::internal::Isolate::thread_local_top(), v8::internal::Isolate::thread_manager(), v8::internal::SharedFunctionInfo::UninstallDebugBytecode(), and v8::internal::RedirectActiveFunctions::VisitThread().
ClearBreakPoint()
bool v8::internal::DebugInfo::ClearBreakPoint (Isolate * isolate, DirectHandle< DebugInfo > debug_info, DirectHandle< BreakPoint > break_point) [static]
Definition at line 109 of file debug-objects.cc.
                                                                      {
  DCHECK(debug_info->HasBreakInfo());
  for (int i = 0; i < debug_info->break_points()->length(); i++) {
    if (IsUndefined(debug_info->break_points()->get(i), isolate)) continue;
    DirectHandle<BreakPointInfo> break_point_info(
        Cast<BreakPointInfo>(debug_info->break_points()->get(i)), isolate);
    if (BreakPointInfo::HasBreakPoint(isolate, break_point_info, break_point)) {
      BreakPointInfo::ClearBreakPoint(isolate, break_point_info, break_point);
      return true;
    }
  }
  return false;
}
References v8::internal::BreakPointInfo::ClearBreakPoint(), v8::internal::DCHECK(), v8::internal::BreakPointInfo::HasBreakPoint(), and v8::internal::length.
Referenced by v8::internal::Debug::ClearBreakPoint().
ClearCoverageInfo()
void v8::internal::DebugInfo::ClearCoverageInfo (Isolate * isolate)
Definition at line 219 of file debug-objects.cc.
                                                  {
  if (HasCoverageInfo()) {
    set_coverage_info(ReadOnlyRoots(isolate).undefined_value());
    int new_flags = flags(kRelaxedLoad) & ~kHasCoverageInfo;
    set_flags(new_flags, kRelaxedStore);
  }
}
References v8::internal::flags, HasCoverageInfo(), v8::kRelaxedLoad, and v8::kRelaxedStore.
DebugBytecodeArray()
Tagged< BytecodeArray > v8::internal::DebugInfo::DebugBytecodeArray (Isolate * isolate) [inline]
Definition at line 52 of file debug-objects-inl.h.
                                                                    {
  DCHECK(HasInstrumentedBytecodeArray());
  Tagged<BytecodeArray> result = debug_bytecode_array(isolate, kAcquireLoad);
  DCHECK_EQ(shared()->GetActiveBytecodeArray(isolate), result);
  return result;
}
References v8::internal::DCHECK(), DCHECK_EQ, HasInstrumentedBytecodeArray(), v8::kAcquireLoad, and v8::base::internal::result.
DebugExecutionMode()
DebugInfo::ExecutionMode v8::internal::DebugInfo::DebugExecutionMode () const
Definition at line 25 of file debug-objects.cc.
                                                           {
  return (flags(kRelaxedLoad) & kDebugExecutionMode) != 0 ? kSideEffects
                                                          : kBreakpoints;
}
References v8::internal::flags, kBreakpoints, v8::kRelaxedLoad, and kSideEffects.
FindBreakPointInfo()
DirectHandle< Object > v8::internal::DebugInfo::FindBreakPointInfo (Isolate * isolate, DirectHandle< DebugInfo > debug_info, DirectHandle< BreakPoint > break_point) [static]
Definition at line 198 of file debug-objects.cc.
                                          {
  DCHECK(debug_info->HasBreakInfo());
  for (int i = 0; i < debug_info->break_points()->length(); i++) {
    if (!IsUndefined(debug_info->break_points()->get(i), isolate)) {
      DirectHandle<BreakPointInfo> break_point_info(
          Cast<BreakPointInfo>(debug_info->break_points()->get(i)), isolate);
      if (BreakPointInfo::HasBreakPoint(isolate, break_point_info,
                                        break_point)) {
        return break_point_info;
      }
    }
  }
  return isolate->factory()->undefined_value();
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::BreakPointInfo::HasBreakPoint(), and v8::internal::length.
Referenced by v8::internal::Debug::ClearBreakPoint().
GetBreakPointCount()
int v8::internal::DebugInfo::GetBreakPointCount (Isolate * isolate)
Definition at line 185 of file debug-objects.cc.
                                                  {
  DCHECK(HasBreakInfo());
  int count = 0;
  for (int i = 0; i < break_points()->length(); i++) {
    if (!IsUndefined(break_points()->get(i), isolate)) {
      Tagged<BreakPointInfo> break_point_info =
          Cast<BreakPointInfo>(break_points()->get(i));
      count += break_point_info->GetBreakPointCount(isolate);
    }
  }
  return count;
}
References v8::internal::DCHECK(), and HasBreakInfo().
GetBreakPointInfo()
Tagged< Object > v8::internal::DebugInfo::GetBreakPointInfo (Isolate * isolate, int source_position) [private]
Definition at line 94 of file debug-objects.cc.
                                                                 {
  DCHECK(HasBreakInfo());
  for (int i = 0; i < break_points()->length(); i++) {
    if (!IsUndefined(break_points()->get(i), isolate)) {
      Tagged<BreakPointInfo> break_point_info =
          Cast<BreakPointInfo>(break_points()->get(i));
      if (break_point_info->source_position() == source_position) {
        return break_point_info;
      }
    }
  }
  return ReadOnlyRoots(isolate).undefined_value();
}
References v8::internal::DCHECK(), and HasBreakInfo().
Referenced by GetBreakPoints(), and HasBreakPoint().
GetBreakPoints()
DirectHandle< Object > v8::internal::DebugInfo::GetBreakPoints (Isolate * isolate, int source_position)
Definition at line 173 of file debug-objects.cc.
                                                                    {
  DCHECK(HasBreakInfo());
  Tagged<Object> break_point_info = GetBreakPointInfo(isolate, source_position);
  if (IsUndefined(break_point_info, isolate)) {
    return isolate->factory()->undefined_value();
  }
  return DirectHandle<Object>(
      Cast<BreakPointInfo>(break_point_info)->break_points(), isolate);
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), GetBreakPointInfo(), and HasBreakInfo().
GetSideEffectState()
DebugInfo::SideEffectState v8::internal::DebugInfo::GetSideEffectState (Isolate * isolate)
Definition at line 228 of file debug-objects.cc.
                                                                       {
  if (side_effect_state() == kNotComputed) {
    SideEffectState has_no_side_effect =
        DebugEvaluate::FunctionGetSideEffectState(
            isolate, direct_handle(shared(), isolate));
    set_side_effect_state(has_no_side_effect);
  }
  return static_cast<SideEffectState>(side_effect_state());
}
References v8::internal::direct_handle(), v8::internal::DebugEvaluate::FunctionGetSideEffectState(), and kNotComputed.
HasBreakInfo()
bool v8::internal::DebugInfo::HasBreakInfo () const
Definition at line 21 of file debug-objects.cc.
                                   {
  return (flags(kRelaxedLoad) & kHasBreakInfo) != 0;
}
References v8::internal::flags, and v8::kRelaxedLoad.
Referenced by GetBreakPointCount(), GetBreakPointInfo(), GetBreakPoints(), and HasBreakPoint().
HasBreakPoint()
bool v8::internal::DebugInfo::HasBreakPoint (Isolate * isolate, int source_position)
Definition at line 81 of file debug-objects.cc.
                                                                   {
  DCHECK(HasBreakInfo());
  // Get the break point info object for this code offset.
  Tagged<Object> break_point_info = GetBreakPointInfo(isolate, source_position);
  // If there is no break point info object or no break points in the break
  // point info object there is no break point at this code offset.
  if (IsUndefined(break_point_info, isolate)) return false;
  return Cast<BreakPointInfo>(break_point_info)->GetBreakPointCount(isolate) >
         0;
}
References v8::internal::DCHECK(), GetBreakPointInfo(), and HasBreakInfo().
HasCoverageInfo()
bool v8::internal::DebugInfo::HasCoverageInfo () const
Definition at line 215 of file debug-objects.cc.
                                      {
  return (flags(kRelaxedLoad) & kHasCoverageInfo) != 0;
}
References v8::internal::flags, and v8::kRelaxedLoad.
Referenced by ClearCoverageInfo().
HasInstrumentedBytecodeArray()
DebugInfo::DebugIsBlackboxedBit DebugInfo::DebuggingIdBits bool v8::internal::DebugInfo::HasInstrumentedBytecodeArray () [inline]
Definition at line 43 of file debug-objects-inl.h.
                                             {
  return has_debug_bytecode_array();
}
Referenced by ClearBreakInfo(), DebugBytecodeArray(), and OriginalBytecodeArray().
IsEmpty()
bool v8::internal::DebugInfo::IsEmpty () const
Definition at line 17 of file debug-objects.cc.
                              {
  return flags(kRelaxedLoad) == kNone && debugger_hints() == 0;
}
References v8::internal::debugger_hints, v8::internal::flags, v8::internal::kNone, and v8::kRelaxedLoad.
OriginalBytecodeArray()
Tagged< BytecodeArray > v8::internal::DebugInfo::OriginalBytecodeArray (Isolate * isolate) [inline]
Definition at line 47 of file debug-objects-inl.h.
                                                                       {
  DCHECK(HasInstrumentedBytecodeArray());
  return original_bytecode_array(isolate, kAcquireLoad);
}
References v8::internal::DCHECK(), HasInstrumentedBytecodeArray(), v8::kAcquireLoad, and v8::internal::original_bytecode_array.
SetBreakAtEntry()
void v8::internal::DebugInfo::SetBreakAtEntry ()
Definition at line 62 of file debug-objects.cc.
                                {
  DCHECK(CanBreakAtEntry());
  set_flags(flags(kRelaxedLoad) | kBreakAtEntry, kRelaxedStore);
}
References CanBreakAtEntry(), v8::internal::DCHECK(), v8::internal::flags, v8::kRelaxedLoad, and v8::kRelaxedStore.
SetBreakPoint()
void v8::internal::DebugInfo::SetBreakPoint (Isolate * isolate, DirectHandle< DebugInfo > debug_info, int source_position, DirectHandle< BreakPoint > break_point) [static]
Definition at line 125 of file debug-objects.cc.
                                                                    {
  DCHECK(debug_info->HasBreakInfo());
  DirectHandle<Object> break_point_info(
      debug_info->GetBreakPointInfo(isolate, source_position), isolate);
  if (!IsUndefined(*break_point_info, isolate)) {
    BreakPointInfo::SetBreakPoint(
        isolate, Cast<BreakPointInfo>(break_point_info), break_point);
    return;
  }
  // Adding a new break point for a code offset which did not have any
  // break points before. Try to find a free slot.
  static const int kNoBreakPointInfo = -1;
  int index = kNoBreakPointInfo;
  for (int i = 0; i < debug_info->break_points()->length(); i++) {
    if (IsUndefined(debug_info->break_points()->get(i), isolate)) {
      index = i;
      break;
    }
  }
  if (index == kNoBreakPointInfo) {
    // No free slot - extend break point info array.
    DirectHandle<FixedArray> old_break_points(debug_info->break_points(),
                                              isolate);
    DirectHandle<FixedArray> new_break_points =
        isolate->factory()->NewFixedArray(
            old_break_points->length() +
            DebugInfo::kEstimatedNofBreakPointsInFunction);
    debug_info->set_break_points(*new_break_points);
    for (int i = 0; i < old_break_points->length(); i++) {
      new_break_points->set(i, old_break_points->get(i));
    }
    index = old_break_points->length();
  }
  DCHECK_NE(index, kNoBreakPointInfo);
  // Allocate new BreakPointInfo object and set the break point.
  DirectHandle<BreakPointInfo> new_break_point_info =
      isolate->factory()->NewBreakPointInfo(source_position);
  BreakPointInfo::SetBreakPoint(isolate, new_break_point_info, break_point);
  debug_info->break_points()->set(index, *new_break_point_info);
}
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, kEstimatedNofBreakPointsInFunction, v8::internal::length, v8::internal::Factory::NewBreakPointInfo(), v8::internal::FactoryBase< Impl >::NewFixedArray(), and v8::internal::BreakPointInfo::SetBreakPoint().
Referenced by v8::internal::Debug::SetBreakpoint().
SetDebugExecutionMode()
void v8::internal::DebugInfo::SetDebugExecutionMode (ExecutionMode value)
Definition at line 30 of file debug-objects.cc.
                                                         {
  set_flags(value == kSideEffects
                ? (flags(kRelaxedLoad) | kDebugExecutionMode)
                : (flags(kRelaxedLoad) & ~kDebugExecutionMode),
            kRelaxedStore);
}
References v8::internal::flags, v8::kRelaxedLoad, v8::kRelaxedStore, kSideEffects, and v8::internal::value.
Member Data Documentation
kEstimatedNofBreakPointsInFunction
const int v8::internal::DebugInfo::kEstimatedNofBreakPointsInFunction = 4 [static]
Definition at line 138 of file debug-objects.h.
Referenced by v8::internal::Debug::CreateBreakInfo(), and SetBreakPoint().
kNoDebuggingId
const int v8::internal::DebugInfo::kNoDebuggingId = 0 [static]
Definition at line 128 of file debug-objects.h.
Referenced by v8::internal::Heap::CreateInitialMutableObjects(), v8::debug::GetDebuggingId(), v8::internal::Debug::GetFunctionDebuggingId(), v8::internal::Factory::NewDebugInfo(), and v8::internal::Heap::NextDebuggingId().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/debug-objects.h
/mnt/V8SourceCode/src/objects/debug-objects-inl.h
/mnt/V8SourceCode/src/objects/debug-objects.cc