v8::internal::ExternalString::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > object)
Additional Inherited Members
Detailed Description
Definition at line 1275 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::ExternalString::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 1278 of file objects-body-descriptors-inl.h.
                                                                    {
    Tagged<ExternalString> string = UncheckedCast<ExternalString>(obj);
    v->VisitExternalPointer(obj, ExternalPointerSlot(&string->resource_));
    if (string->is_uncached()) return;
    v->VisitExternalPointer(obj, ExternalPointerSlot(&string->resource_data_));
  }
References v8::internal::String::string, and v8::internal::ObjectVisitor::VisitExternalPointer().
SizeOf()
static int v8::internal::ExternalString::BodyDescriptor::SizeOf (Tagged< Map > map, Tagged< HeapObject > object) [inline], [static]
Definition at line 1286 of file objects-body-descriptors-inl.h.
                                                                       {
    InstanceType type = map->instance_type();
    const auto is_uncached =
        (type & kUncachedExternalStringMask) == kUncachedExternalStringTag;
    return is_uncached ? sizeof(UncachedExternalString)
                       : sizeof(ExternalString);
  }
References v8::internal::ExternalString::is_uncached(), v8::internal::kUncachedExternalStringMask, v8::internal::kUncachedExternalStringTag, v8::internal::HeapObjectLayout::map(), and v8::internal::tracing::type.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h