v8::internal::torque::Logger Class Reference
#include <globals.h>
Public Member Functions
Logger ()
~Logger ()
Static Public Member Functions
static void Enable (std::string path)
template<class... Args>
static void Log (Args &&... args)
Static Private Member Functions
static bool Enabled ()
static std::ofstream & Stream ()
static void Flush ()
Private Attributes
bool enabled_
std::ofstream logfile_
Additional Inherited Members
Detailed Description
Definition at line 20 of file globals.h.
Constructor & Destructor Documentation
Logger()
v8::internal::torque::Logger::Logger () [inline]
Definition at line 22 of file globals.h.
: enabled_(false) {}
 Logger()
v8::internal::torque::Logger::~Logger () [inline]
Definition at line 23 of file globals.h.
            {
    if (enabled_) logfile_.close();
  }
References enabled_, and logfile_.
Member Function Documentation
Enable()
static void v8::internal::torque::Logger::Enable (std::string path) [inline], [static]
Definition at line 27 of file globals.h.
                                     {
    Get().enabled_ = true;
    Get().logfile_.open(path);
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::ls::WrappedMain().
Enabled()
static bool v8::internal::torque::Logger::Enabled () [inline], [static], [private]
Definition at line 41 of file globals.h.
{ return Get().enabled_; }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by Log().
Flush()
static void v8::internal::torque::Logger::Flush () [inline], [static], [private]
Definition at line 46 of file globals.h.
{ Get().logfile_.flush(); }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by Log().
Log()
template<class... Args>
static void v8::internal::torque::Logger::Log (Args &&... args) [inline], [static]
Definition at line 33 of file globals.h.
                                  {
    if (Enabled()) {
      USE((Stream() << std::forward<Args>(args))...);
      Flush();
    }
  }
References v8::base::args, Enabled(), Flush(), Stream(), and USE.
Referenced by v8::internal::torque::ls::HandleMessage(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleTorqueFileListNotification(), v8::internal::torque::ls::ReadMessage(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::RecompileTorque(), and v8::internal::torque::ls::WriteMessage().
Stream()
static std::ofstream& v8::internal::torque::Logger::Stream () [inline], [static], [private]
Definition at line 42 of file globals.h.
                               {
    CHECK(Get().enabled_);
    return Get().logfile_;
  }
References CHECK, enabled_, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by Log().
Member Data Documentation
enabled_
bool v8::internal::torque::Logger::enabled_ [private]
Definition at line 49 of file globals.h.
Referenced by Stream(), and ~Logger().
logfile_
std::ofstream v8::internal::torque::Logger::logfile_ [private]
Definition at line 50 of file globals.h.
Referenced by ~Logger().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/ls/globals.h