v8::internal::compiler::LifetimePosition Class Reference
#include <register-allocator.h>
Public Member Functions
int value () const
int ToInstructionIndex () const
bool IsStart () const
bool IsEnd () const
bool IsFullStart () const
bool IsGapPosition () const
bool IsInstructionPosition () const
LifetimePosition Start () const
LifetimePosition FullStart () const
LifetimePosition End () const
LifetimePosition NextStart () const
LifetimePosition NextFullStart () const
LifetimePosition PrevStart () const
LifetimePosition ()
bool IsValid () const
bool operator< (const LifetimePosition &that) const
bool operator<= (const LifetimePosition &that) const
bool operator== (const LifetimePosition &that) const
bool operator!= (const LifetimePosition &that) const
bool operator> (const LifetimePosition &that) const
bool operator>= (const LifetimePosition &that) const
void Print () const
Static Public Member Functions
static LifetimePosition GapFromInstructionIndex (int index)
static LifetimePosition InstructionFromInstructionIndex (int index)
static bool ExistsGapPositionBetween (LifetimePosition pos1, LifetimePosition pos2)
static LifetimePosition Invalid ()
static LifetimePosition MaxPosition ()
static LifetimePosition FromInt (int value)
Private Member Functions
LifetimePosition (int value)
Private Attributes
int value_
Static Private Attributes
static const int kHalfStep = 2
static const int kStep = 2 * kHalfStep
Detailed Description
Definition at line 41 of file register-allocator.h.
Constructor & Destructor Documentation
LifetimePosition() [1/2]
v8::internal::compiler::LifetimePosition::LifetimePosition () [inline]
Definition at line 121 of file register-allocator.h.
: value_(-1) {}
Referenced by End(), FromInt(), FullStart(), GapFromInstructionIndex(), InstructionFromInstructionIndex(), Invalid(), MaxPosition(), NextFullStart(), NextStart(), PrevStart(), and Start().
LifetimePosition() [2/2]
v8::internal::compiler::LifetimePosition::LifetimePosition (int value) [inline], [explicit], [private]
Definition at line 173 of file register-allocator.h.
: value_(value) {}
Member Function Documentation
End()
LifetimePosition v8::internal::compiler::LifetimePosition::End () const [inline]
Definition at line 95 of file register-allocator.h.
                               {
    DCHECK(IsValid());
    return LifetimePosition(Start().value_ + kHalfStep / 2);
  }
References v8::internal::DCHECK(), IsValid(), kHalfStep, LifetimePosition(), Start(), and value_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LiveRange::CanBeSpilled(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil(), and v8::internal::compiler::LinearScanAllocator::TryAllocateFreeReg().
ExistsGapPositionBetween()
static bool v8::internal::compiler::LifetimePosition::ExistsGapPositionBetween (LifetimePosition pos1, LifetimePosition pos2) [inline], [static]
Definition at line 54 of file register-allocator.h.
                                                              {
    if (pos1 > pos2) std::swap(pos1, pos2);
    LifetimePosition next(pos1.value_ + 1);
    if (next.IsGapPosition()) return next < pos2;
    return next.NextFullStart() < pos2;
  }
References IsGapPosition(), NextFullStart(), and value_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), and v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting().
FromInt()
static LifetimePosition v8::internal::compiler::LifetimePosition::FromInt (int value) [inline], [static]
Definition at line 162 of file register-allocator.h.
                                                    {
    return LifetimePosition(value);
  }
References LifetimePosition(), and value().
FullStart()
LifetimePosition v8::internal::compiler::LifetimePosition::FullStart () const [inline]
Definition at line 89 of file register-allocator.h.
                                     {
    DCHECK(IsValid());
    return LifetimePosition(value_ & ~(kStep - 1));
  }
References v8::internal::DCHECK(), IsValid(), kStep, LifetimePosition(), and value_.
Referenced by NextFullStart(), v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges(), and v8::internal::compiler::LinearScanAllocator::TryAllocateFreeReg().
GapFromInstructionIndex()
static LifetimePosition v8::internal::compiler::LifetimePosition::GapFromInstructionIndex (int index) [inline], [static]
Definition at line 45 of file register-allocator.h.
                                                             {
    return LifetimePosition(index * kStep);
  }
References v8::internal::index, kStep, and LifetimePosition().
Referenced by v8::internal::compiler::LiveRangeBuilder::AddInitialIntervals(), v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), v8::internal::compiler::RegisterAllocator::FindOptimalSpillingPos(), v8::internal::compiler::RegisterAllocator::FindOptimalSplitPos(), v8::internal::compiler::RegisterAllocator::GetSplitPositionForInstruction(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::PrintBlockRow(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::LiveRangeBuilder::ProcessLoopHeader(), v8::internal::compiler::LiveRangeBuilder::ProcessPhis(), and v8::internal::compiler::LiveRangeConnector::ResolveControlFlow().
InstructionFromInstructionIndex()
static LifetimePosition v8::internal::compiler::LifetimePosition::InstructionFromInstructionIndex (int index) [inline], [static]
Definition at line 50 of file register-allocator.h.
                                                                     {
    return LifetimePosition(index * kStep + kHalfStep);
  }
References v8::internal::index, kHalfStep, kStep, and LifetimePosition().
Referenced by v8::internal::compiler::LiveRangeBuilder::AddInitialIntervals(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::SpillPlacer::CommitSpill(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
Invalid()
static LifetimePosition v8::internal::compiler::LifetimePosition::Invalid () [inline], [static]
Definition at line 154 of file register-allocator.h.
{ return LifetimePosition(); }
References LifetimePosition().
Referenced by v8::internal::compiler::LiveRange::FirstIntersection(), v8::internal::compiler::RegisterAllocator::GetSplitPositionForInstruction(), and v8::internal::compiler::UseInterval::Intersect().
IsEnd()
bool v8::internal::compiler::LifetimePosition::IsEnd () const [inline]
Definition at line 75 of file register-allocator.h.
{ return (value_ & (kHalfStep - 1)) == 1; }
References kHalfStep, and value_.
IsFullStart()
bool v8::internal::compiler::LifetimePosition::IsFullStart () const [inline]
Definition at line 77 of file register-allocator.h.
{ return (value_ & (kStep - 1)) == 0; }
References kStep, and value_.
Referenced by v8::internal::compiler::RegisterAllocationData::IsBlockBoundary().
IsGapPosition()
bool v8::internal::compiler::LifetimePosition::IsGapPosition () const [inline]
Definition at line 79 of file register-allocator.h.
{ return (value_ & 0x2) == 0; }
References value_.
Referenced by v8::internal::compiler::LiveRangeConnector::ConnectRanges(), ExistsGapPositionBetween(), IsInstructionPosition(), v8::internal::compiler::UseInterval::LastGapIndex(), v8::internal::compiler::operator<<(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand(), v8::internal::compiler::RegisterAllocator::SplitRangeAt(), v8::internal::compiler::LinearScanAllocator::TryAllocateFreeReg(), and v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
IsInstructionPosition()
bool v8::internal::compiler::LifetimePosition::IsInstructionPosition () const [inline]
Definition at line 80 of file register-allocator.h.
{ return !IsGapPosition(); }
References IsGapPosition().
Referenced by v8::internal::compiler::UseInterval::FirstGapIndex(), and v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
IsStart()
bool v8::internal::compiler::LifetimePosition::IsStart () const [inline]
Definition at line 73 of file register-allocator.h.
{ return (value_ & (kHalfStep - 1)) == 0; }
References kHalfStep, and value_.
Referenced by v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::UseInterval::LastGapIndex(), v8::internal::compiler::operator<<(), and v8::internal::compiler::RegisterAllocator::SplitRangeAt().
IsValid()
bool v8::internal::compiler::LifetimePosition::IsValid () const [inline]
Definition at line 125 of file register-allocator.h.
{ return value_ != -1; }
References value_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), End(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), v8::internal::compiler::LiveRange::FirstIntersection(), FullStart(), NextFullStart(), NextStart(), PrevStart(), v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand(), Start(), ToInstructionIndex(), v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges(), and v8::internal::compiler::UsePosition::UsePosition().
MaxPosition()
static LifetimePosition v8::internal::compiler::LifetimePosition::MaxPosition () [inline], [static]
Definition at line 156 of file register-allocator.h.
                                               {
    // We have to use this kind of getter instead of static member due to
    // crash bug in GDB.
    return LifetimePosition(kMaxInt);
  }
References v8::internal::kMaxInt, and LifetimePosition().
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), v8::internal::compiler::LinearScanAllocator::ForwardStateTo(), and v8::internal::compiler::SpillRange::SpillRange().
NextFullStart()
LifetimePosition v8::internal::compiler::LifetimePosition::NextFullStart () const [inline]
Definition at line 107 of file register-allocator.h.
                                         {
    DCHECK(IsValid());
    return LifetimePosition(FullStart().value_ + kStep);
  }
References v8::internal::DCHECK(), FullStart(), IsValid(), kStep, LifetimePosition(), and value_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), ExistsGapPositionBetween(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::PrintBlockRow(), v8::internal::compiler::LiveRangeBuilder::ProcessLoopHeader(), and v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand().
NextStart()
LifetimePosition v8::internal::compiler::LifetimePosition::NextStart () const [inline]
Definition at line 101 of file register-allocator.h.
                                     {
    DCHECK(IsValid());
    return LifetimePosition(Start().value_ + kHalfStep);
  }
References v8::internal::DCHECK(), IsValid(), kHalfStep, LifetimePosition(), Start(), and value_.
Referenced by v8::internal::compiler::LiveRangeBuilder::AddInitialIntervals(), v8::internal::compiler::LiveRange::CanBeSpilled(), v8::internal::compiler::LiveRangeBuilder::Define(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand(), and v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
operator!=()
bool v8::internal::compiler::LifetimePosition::operator!= (const LifetimePosition & that) const [inline]
Definition at line 139 of file register-allocator.h.
                                                      {
    return this->value_ != that.value_;
  }
References value_.
operator<()
bool v8::internal::compiler::LifetimePosition::operator< (const LifetimePosition & that) const [inline]
Definition at line 127 of file register-allocator.h.
                                                     {
    return this->value_ < that.value_;
  }
References value_.
operator<=()
bool v8::internal::compiler::LifetimePosition::operator<= (const LifetimePosition & that) const [inline]
Definition at line 131 of file register-allocator.h.
                                                      {
    return this->value_ <= that.value_;
  }
References value_.
operator==()
bool v8::internal::compiler::LifetimePosition::operator== (const LifetimePosition & that) const [inline]
Definition at line 135 of file register-allocator.h.
                                                      {
    return this->value_ == that.value_;
  }
References value_.
operator>()
bool v8::internal::compiler::LifetimePosition::operator> (const LifetimePosition & that) const [inline]
Definition at line 143 of file register-allocator.h.
                                                     {
    return this->value_ > that.value_;
  }
References value_.
operator>=()
bool v8::internal::compiler::LifetimePosition::operator>= (const LifetimePosition & that) const [inline]
Definition at line 147 of file register-allocator.h.
                                                      {
    return this->value_ >= that.value_;
  }
References value_.
PrevStart()
LifetimePosition v8::internal::compiler::LifetimePosition::PrevStart () const [inline]
Definition at line 113 of file register-allocator.h.
                                     {
    DCHECK(IsValid());
    DCHECK_LE(kHalfStep, value_);
    return LifetimePosition(Start().value_ - kHalfStep);
  }
References v8::internal::DCHECK(), DCHECK_LE, IsValid(), kHalfStep, LifetimePosition(), Start(), and value_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), and v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges().
Print()
void v8::internal::compiler::LifetimePosition::Print () const
Definition at line 177 of file register-allocator.cc.
{ StdoutStream{} << *this << std::endl; }
Start()
LifetimePosition v8::internal::compiler::LifetimePosition::Start () const [inline]
Definition at line 83 of file register-allocator.h.
                                 {
    DCHECK(IsValid());
    return LifetimePosition(value_ & ~(kHalfStep - 1));
  }
References v8::internal::DCHECK(), IsValid(), kHalfStep, LifetimePosition(), and value_.
Referenced by v8::internal::compiler::LiveRangeConnector::ConnectRanges(), End(), v8::internal::compiler::RegisterAllocator::FindOptimalSpillingPos(), NextStart(), PrevStart(), and v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
ToInstructionIndex()
int v8::internal::compiler::LifetimePosition::ToInstructionIndex () const [inline]
Definition at line 67 of file register-allocator.h.
                                 {
    DCHECK(IsValid());
    return value_ / kStep;
  }
References v8::internal::DCHECK(), IsValid(), kStep, and value_.
Referenced by v8::internal::compiler::SpillPlacer::Add(), v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::RegisterAllocator::FindOptimalSplitPos(), v8::internal::compiler::UseInterval::FirstGapIndex(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetInstructionBlock(), v8::internal::compiler::RegisterAllocationData::IsBlockBoundary(), v8::internal::compiler::UseInterval::LastGapIndex(), v8::internal::compiler::operator<<(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand(), and v8::internal::compiler::RegisterAllocator::SplitRangeAt().
value()
int v8::internal::compiler::LifetimePosition::value () const [inline]
Definition at line 63 of file register-allocator.h.
{ return value_; }
References value_.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), v8::internal::compiler::TopLevelLiveRange::AddUsePosition(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::AssignRegisterOnReload(), v8::internal::compiler::TopLevelLiveRange::EnsureInterval(), FromInt(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::PrintBlockRow(), v8::internal::compiler::LinearScanAllocator::PrintRangeRow(), v8::internal::compiler::LinearScanAllocator::ReloadLiveRanges(), v8::internal::compiler::TopLevelLiveRange::ShortenTo(), v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges(), v8::internal::compiler::RegisterAllocator::SplitBetween(), v8::internal::compiler::RegisterAllocator::SplitRangeAt(), and v8::internal::compiler::LinearScanAllocator::TryAllocatePreferredReg().
Member Data Documentation
kHalfStep
const int v8::internal::compiler::LifetimePosition::kHalfStep = 2 [static], [private]
Definition at line 167 of file register-allocator.h.
Referenced by End(), InstructionFromInstructionIndex(), IsEnd(), IsStart(), NextStart(), PrevStart(), and Start().
kStep
const int v8::internal::compiler::LifetimePosition::kStep = 2 * kHalfStep [static], [private]
Definition at line 168 of file register-allocator.h.
Referenced by FullStart(), GapFromInstructionIndex(), InstructionFromInstructionIndex(), IsFullStart(), NextFullStart(), and ToInstructionIndex().
value_
int v8::internal::compiler::LifetimePosition::value_ [private]
Definition at line 175 of file register-allocator.h.
Referenced by End(), ExistsGapPositionBetween(), FullStart(), IsEnd(), IsFullStart(), IsGapPosition(), IsStart(), IsValid(), NextFullStart(), NextStart(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), PrevStart(), Start(), ToInstructionIndex(), and value().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc