v8::internal::torque::Value Class Reference
#include <declarable.h>
Public Member Functions
const Identifier * name () const
virtual bool IsConst () const
VisitResult value () const
const Type * type () const
void set_value (VisitResult value)
Protected Member Functions
Value (Kind kind, const Type *type, Identifier *name)
Private Attributes
const Type * type_
Identifier * name_
std::optional< VisitResult > value_
Additional Inherited Members
Detailed Description
Definition at line 240 of file declarable.h.
Constructor & Destructor Documentation
Value()
v8::internal::torque::Value::Value (Kind kind, const Type * type, Identifier * name) [inline], [protected]
Definition at line 254 of file declarable.h.
      : Declarable(kind), type_(type), name_(name) {}
Member Function Documentation
IsConst()
virtual bool v8::internal::torque::Value::IsConst () const [inline], [virtual]
Definition at line 244 of file declarable.h.
{ return true; }
name()
const Identifier* v8::internal::torque::Value::name () const [inline]
Definition at line 243 of file declarable.h.
{ return name_; }
References name_.
Referenced by v8::internal::torque::KytheData::AddConstantDefinition().
set_value()
void v8::internal::torque::Value::set_value (VisitResult value) [inline]
Definition at line 248 of file declarable.h.
                                    {
    DCHECK(!value_);
    value_ = value;
  }
References v8::internal::DCHECK(), value(), and value_.
Referenced by v8::internal::torque::ExternConstant::ExternConstant().
type()
const Type* v8::internal::torque::Value::type () const [inline]
Definition at line 246 of file declarable.h.
{ return type_; }
References type_.
Referenced by v8::internal::torque::ExternConstant::ExternConstant(), v8::internal::torque::NamespaceConstantInstruction::GetValueDefinitionCount(), and v8::internal::torque::ImplementationVisitor::Visit().
value()
VisitResult v8::internal::torque::Value::value () const [inline]
Definition at line 245 of file declarable.h.
{ return *value_; }
References value_.
Referenced by v8::internal::torque::ExternConstant::ExternConstant(), v8::internal::torque::ImplementationVisitor::GetLocationReference(), and set_value().
Member Data Documentation
name_
Identifier* v8::internal::torque::Value::name_ [private]
Definition at line 259 of file declarable.h.
Referenced by name().
type_
const Type* v8::internal::torque::Value::type_ [private]
Definition at line 258 of file declarable.h.
Referenced by type().
value_
std::optional<VisitResult> v8::internal::torque::Value::value_ [private]
Definition at line 260 of file declarable.h.
Referenced by set_value(), and value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/declarable.h