v8::internal::JSAtomicsCondition Class Reference
#include <js-atomics-synchronization.h>
Public Types
enum { kMutexAsyncContextSlot = Context::MIN_CONTEXT_SLOTS
, kConditionVariableAsyncContextSlot
, kAsyncContextLength
 }
using AsyncWaiterNodeType = WaitAsyncWaiterQueueNode
Static Public Member Functions
static V8_EXPORT_PRIVATE bool WaitFor (Isolate *requester, DirectHandle< JSAtomicsCondition > cv, DirectHandle< JSAtomicsMutex > mutex, std::optional< base::TimeDelta > timeout)
static V8_EXPORT_PRIVATE MaybeDirectHandle< JSReceiver > WaitAsync (Isolate *requester, DirectHandle< JSAtomicsCondition > cv, DirectHandle< JSAtomicsMutex > mutex, std::optional< base::TimeDelta > timeout)
static void HandleAsyncNotify (WaitAsyncWaiterQueueNode *node)
static void HandleAsyncTimeout (WaitAsyncWaiterQueueNode *node)
static V8_EXPORT_PRIVATE uint32_t Notify (Isolate *requester, DirectHandle< JSAtomicsCondition > cv, uint32_t count)
static void CleanupMatchingAsyncWaiters (Isolate *isolate, WaiterQueueNode *node, DequeueMatcher matcher)
Static Public Attributes
static constexpr uint32_t kAllWaiters = UINT32_MAX
Private Types
using DequeueAction = std::function< uint32_t(WaiterQueueNode **)>
Static Private Member Functions
static void QueueWaiter (Isolate *requester, DirectHandle< JSAtomicsCondition > cv, WaiterQueueNode *waiter)
static uint32_t DequeueExplicit (Isolate *requester, DirectHandle< JSAtomicsCondition > cv, std::atomic< StateT > *state, const DequeueAction &dequeue_action)
Friends
class Factory
Detailed Description
Definition at line 400 of file js-atomics-synchronization.h.
Member Typedef Documentation
AsyncWaiterNodeType
using v8::internal::JSAtomicsCondition::AsyncWaiterNodeType = WaitAsyncWaiterQueueNode
Definition at line 404 of file js-atomics-synchronization.h.
DequeueAction
using v8::internal::JSAtomicsCondition::DequeueAction = std::function<uint32_t(WaiterQueueNode**)> [private]
Definition at line 447 of file js-atomics-synchronization.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kMutexAsyncContextSlot
kConditionVariableAsyncContextSlot
kAsyncContextLength
Definition at line 432 of file js-atomics-synchronization.h.
       {
    kMutexAsyncContextSlot = Context::MIN_CONTEXT_SLOTS,
    kConditionVariableAsyncContextSlot,
    kAsyncContextLength
  };
Member Function Documentation
CleanupMatchingAsyncWaiters()
void v8::internal::JSAtomicsCondition::CleanupMatchingAsyncWaiters (Isolate * isolate, WaiterQueueNode * node, DequeueMatcher matcher) [static]
Definition at line 1121 of file js-atomics-synchronization.cc.
                                                                             {
  auto* async_node = static_cast<WaitAsyncWaiterQueueNode*>(node);
  if (async_node->ready_for_async_cleanup_) {
    // The node is not in the waiter queue and there is no HandleNotify task
    // for it in the event loop. So it is safe to delete it.
    return;
  }
  if (async_node->IsEmpty()) {
    // The node's underlying synchronization primitive has been collected, so
    // delete it.
    async_node->SetNotInListForVerification();
    return;
  }
  DirectHandle<JSAtomicsCondition> cv =
      async_node->GetSynchronizationPrimitive();
  std::atomic<StateT>* state = cv->AtomicStatePtr();
  StateT current_state = state->load(std::memory_order_relaxed);
  WaiterQueueLockGuard waiter_queue_lock_guard(state, current_state);
  WaiterQueueNode* waiter_head = cv->DestructivelyGetWaiterQueueHead(isolate);
  if (waiter_head) {
    WaiterQueueNode::DequeueAllMatchingForAsyncCleanup(&waiter_head, matcher);
  }
  StateT new_state =
      cv->SetWaiterQueueHead(isolate, waiter_head, current_state);
  waiter_queue_lock_guard.set_new_state(new_state);
}
References v8::internal::detail::WaiterQueueNode::DequeueAllMatchingForAsyncCleanup(), v8::internal::detail::WaiterQueueLockGuard::set_new_state(), and v8::internal::detail::WaiterQueueNode::SetNotInListForVerification().
DequeueExplicit()
uint32_t v8::internal::JSAtomicsCondition::DequeueExplicit (Isolate * requester, DirectHandle< JSAtomicsCondition > cv, std::atomic< StateT > * state, const DequeueAction & dequeue_action) [static], [private]
Definition at line 1218 of file js-atomics-synchronization.cc.
                                                                      {
  // First acquire the queue lock, which is itself a spinlock.
  StateT current_state = state->load(std::memory_order_relaxed);
  if (!HasWaitersField::decode(current_state)) return 0;
  WaiterQueueLockGuard waiter_queue_lock_guard(state, current_state);
  // Get the waiter queue head.
  WaiterQueueNode* waiter_head = cv->DestructivelyGetWaiterQueueHead(requester);
  // There's no waiter to wake up, release the queue lock by setting it to the
  // empty state.
  if (waiter_head == nullptr) {
    StateT new_state = kEmptyState;
    waiter_queue_lock_guard.set_new_state(new_state);
    return 0;
  }
  uint32_t num_dequeued_waiters = action_under_lock(&waiter_head);
  // Release the queue lock and install the new waiter queue head.
  DCHECK_EQ(state->load(),
            IsWaiterQueueLockedField::update(current_state, true));
  StateT new_state =
      cv->SetWaiterQueueHead(requester, waiter_head, current_state);
  waiter_queue_lock_guard.set_new_state(new_state);
  return num_dequeued_waiters;
}
References DCHECK_EQ, and v8::internal::detail::WaiterQueueLockGuard::set_new_state().
Referenced by HandleAsyncTimeout(), Notify(), and WaitFor().
HandleAsyncNotify()
void v8::internal::JSAtomicsCondition::HandleAsyncNotify (WaitAsyncWaiterQueueNode * node) [static]
Definition at line 1367 of file js-atomics-synchronization.cc.
                                                                           {
  Isolate* requester = waiter->requester_;
  if (V8_UNLIKELY(waiter->native_context_.IsEmpty())) {
    // The native context was destroyed so the promise was already removed
    // from the native context. Remove the node from the async unlocked waiter
    // list.
    WaitAsyncWaiterQueueNode::RemoveFromAsyncWaiterQueueList(waiter);
    return;
  }
  HandleScope scope(requester);
  if (waiter->timeout_task_id_ != CancelableTaskManager::kInvalidTaskId) {
    TryAbortResult abort_result =
        requester->cancelable_task_manager()->TryAbort(
            waiter->timeout_task_id_);
    DCHECK_EQ(abort_result, TryAbortResult::kTaskAborted);
    USE(abort_result);
  }
  v8::Context::Scope contextScope(waiter->GetNativeContext());
  DirectHandle<JSPromise> promise = waiter->GetInternalWaitingPromise();
  MaybeDirectHandle<Object> result =
      JSPromise::Resolve(promise, requester->factory()->undefined_value());
  USE(result);
  WaitAsyncWaiterQueueNode::RemoveFromAsyncWaiterQueueList(waiter);
  RemovePromiseFromNativeContext(requester, promise);
}
References v8::internal::Isolate::cancelable_task_manager(), DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::detail::AsyncWaiterQueueNode< T >::GetInternalWaitingPromise(), v8::internal::detail::AsyncWaiterQueueNode< T >::GetNativeContext(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::CancelableTaskManager::kInvalidTaskId, v8::internal::kTaskAborted, v8::internal::detail::AsyncWaiterQueueNode< T >::native_context_, v8::internal::detail::AsyncWaiterQueueNode< T >::RemoveFromAsyncWaiterQueueList(), v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::RemovePromiseFromNativeContext(), v8::internal::detail::WaiterQueueNode::requester_, v8::internal::JSPromise::Resolve(), v8::base::internal::result, v8::internal::detail::AsyncWaiterQueueNode< T >::timeout_task_id_, v8::internal::CancelableTaskManager::TryAbort(), USE, and V8_UNLIKELY.
Referenced by HandleAsyncTimeout().
HandleAsyncTimeout()
void v8::internal::JSAtomicsCondition::HandleAsyncTimeout (WaitAsyncWaiterQueueNode * node) [static]
Definition at line 1334 of file js-atomics-synchronization.cc.
                                                                            {
  Isolate* requester = waiter->requester_;
  if (V8_UNLIKELY(waiter->native_context_.IsEmpty())) {
    // The native context was destroyed so the promise was already removed
    // from the native context. Remove the node from the async unlocked waiter
    // list.
    WaitAsyncWaiterQueueNode::RemoveFromAsyncWaiterQueueList(waiter);
    return;
  }
  HandleScope scope(requester);
  DirectHandle<JSAtomicsCondition> cv = waiter->GetSynchronizationPrimitive();
  std::atomic<StateT>* state = cv->AtomicStatePtr();
  uint32_t num_dequeued =
      DequeueExplicit(requester, cv, state, [&](WaiterQueueNode** waiter_head) {
        WaiterQueueNode* dequeued = WaiterQueueNode::DequeueMatching(
            waiter_head, [&](WaiterQueueNode* node) { return node == waiter; });
        return dequeued ? 1 : 0;
      });
  // If the waiter is not in the queue, the notify task is already in the event
  // loop, so cancel the notify task.
  if (num_dequeued == 0) {
    TryAbortResult abort_result =
        requester->cancelable_task_manager()->TryAbort(waiter->notify_task_id_);
    DCHECK_EQ(abort_result, TryAbortResult::kTaskAborted);
    USE(abort_result);
  }
  // Reset the timeout task id to kInvalidTaskId, otherwise the notify task will
  // try to cancel it.
  waiter->timeout_task_id_ = CancelableTaskManager::kInvalidTaskId;
  JSAtomicsCondition::HandleAsyncNotify(waiter);
}
References v8::internal::Isolate::cancelable_task_manager(), DCHECK_EQ, DequeueExplicit(), v8::internal::detail::WaiterQueueNode::DequeueMatching(), v8::internal::detail::AsyncWaiterQueueNode< T >::GetSynchronizationPrimitive(), HandleAsyncNotify(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::CancelableTaskManager::kInvalidTaskId, v8::internal::kTaskAborted, v8::internal::detail::AsyncWaiterQueueNode< T >::native_context_, v8::internal::detail::AsyncWaiterQueueNode< T >::notify_task_id_, v8::internal::detail::AsyncWaiterQueueNode< T >::RemoveFromAsyncWaiterQueueList(), v8::internal::detail::WaiterQueueNode::requester_, v8::internal::detail::AsyncWaiterQueueNode< T >::timeout_task_id_, v8::internal::CancelableTaskManager::TryAbort(), USE, and V8_UNLIKELY.
Notify()
uint32_t v8::internal::JSAtomicsCondition::Notify (Isolate * requester, DirectHandle< JSAtomicsCondition > cv, uint32_t count) [static]
Definition at line 1251 of file js-atomics-synchronization.cc.
                                                    {
  std::atomic<StateT>* state = cv->AtomicStatePtr();
  // Dequeue count waiters.
  return DequeueExplicit(
      requester, cv, state, [=](WaiterQueueNode** waiter_head) -> uint32_t {
        WaiterQueueNode* old_head;
        if (count == 1) {
          old_head = WaiterQueueNode::Dequeue(waiter_head);
          if (!old_head) return 0;
          old_head->Notify();
          return 1;
        }
        if (count == kAllWaiters) {
          old_head = *waiter_head;
          *waiter_head = nullptr;
        } else {
          old_head = WaiterQueueNode::Split(waiter_head, count);
        }
        if (!old_head) return 0;
        // Notify while holding the queue lock to avoid notifying
        // waiters that have been deleted in other threads.
        return old_head->NotifyAllInList();
      });
}
References v8::internal::detail::WaiterQueueNode::Dequeue(), DequeueExplicit(), kAllWaiters, v8::internal::detail::WaiterQueueNode::Notify(), v8::internal::detail::WaiterQueueNode::NotifyAllInList(), and v8::internal::detail::WaiterQueueNode::Split().
Referenced by v8::internal::BUILTIN().
QueueWaiter()
void v8::internal::JSAtomicsCondition::QueueWaiter (Isolate * requester, DirectHandle< JSAtomicsCondition > cv, WaiterQueueNode * waiter) [static], [private]
Definition at line 1153 of file js-atomics-synchronization.cc.
                                                              {
  // The state pointer should not be used outside of this block as a shared GC
  // may reallocate it after waiting.
  std::atomic<StateT>* state = cv->AtomicStatePtr();
  // Try to acquire the queue lock, which is itself a spinlock.
  StateT current_state = state->load(std::memory_order_relaxed);
  WaiterQueueLockGuard waiter_queue_lock_guard(state, current_state);
  // With the queue lock held, enqueue the requester onto the waiter queue.
  WaiterQueueNode* waiter_head = cv->DestructivelyGetWaiterQueueHead(requester);
  WaiterQueueNode::Enqueue(&waiter_head, waiter);
  // Release the queue lock and install the new waiter queue head.
  DCHECK_EQ(state->load(),
            IsWaiterQueueLockedField::update(current_state, true));
  StateT new_state =
      cv->SetWaiterQueueHead(requester, waiter_head, current_state);
  waiter_queue_lock_guard.set_new_state(new_state);
}
References DCHECK_EQ, v8::internal::detail::WaiterQueueNode::Enqueue(), and v8::internal::detail::WaiterQueueLockGuard::set_new_state().
Referenced by WaitAsync(), and WaitFor().
WaitAsync()
MaybeDirectHandle< JSReceiver > v8::internal::JSAtomicsCondition::WaitAsync (Isolate * requester, DirectHandle< JSAtomicsCondition > cv, DirectHandle< JSAtomicsMutex > mutex, std::optional< base::TimeDelta > timeout) [static]
Definition at line 1287 of file js-atomics-synchronization.cc.
                                        {
  Handle<JSPromise> internal_waiting_promise =
      requester->factory()->NewJSPromise();
  DirectHandle<Context> handler_context =
      requester->factory()->NewBuiltinContext(requester->native_context(),
                                              kAsyncContextLength);
  handler_context->SetNoCell(kMutexAsyncContextSlot, *mutex);
  handler_context->SetNoCell(kConditionVariableAsyncContextSlot, *cv);
  DirectHandle<SharedFunctionInfo> info(
      requester->heap()->atomics_condition_acquire_lock_sfi(), requester);
  DirectHandle<JSFunction> lock_function =
      Factory::JSFunctionBuilder{requester, info, handler_context}
          .set_map(requester->strict_function_without_prototype_map())
          .Build();
  DirectHandle<JSReceiver> lock_promise;
  ASSIGN_RETURN_ON_EXCEPTION(
      requester, lock_promise,
      PerformPromiseThen(requester, internal_waiting_promise, lock_function));
  // Create a new async waiter node in the C++ heap. Its lifetime is managed by
  // the requester's `async_waiter_queue_nodes` list.
  WaitAsyncWaiterQueueNode* this_waiter =
      WaitAsyncWaiterQueueNode::NewAsyncWaiterStoredInIsolate(
          requester, cv, internal_waiting_promise);
  QueueWaiter(requester, cv, this_waiter);
  if (timeout) {
    TaskRunner* taks_runner = this_waiter->task_runner();
    auto task = std::make_unique<AsyncWaitTimeoutTask>(
        requester->cancelable_task_manager(), this_waiter);
    this_waiter->timeout_task_id_ = task->id();
    taks_runner->PostNonNestableDelayedTask(std::move(task),
                                            timeout->InSecondsF());
  }
  mutex->Unlock(requester);
  // Keep the wait promise alive in the native context.
  AddPromiseToNativeContext(requester, internal_waiting_promise);
  return lock_promise;
}
References v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::AddPromiseToNativeContext(), ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::cancelable_task_manager(), v8::internal::Isolate::factory(), v8::internal::Isolate::heap(), kAsyncContextLength, kConditionVariableAsyncContextSlot, kMutexAsyncContextSlot, v8::internal::Isolate::native_context(), v8::internal::detail::AsyncWaiterQueueNode< T >::NewAsyncWaiterStoredInIsolate(), v8::internal::Factory::NewBuiltinContext(), v8::internal::Factory::NewJSPromise(), v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::PerformPromiseThen(), v8::TaskRunner::PostNonNestableDelayedTask(), QueueWaiter(), v8::internal::detail::AsyncWaiterQueueNode< T >::task_runner(), and v8::internal::detail::AsyncWaiterQueueNode< T >::timeout_task_id_.
Referenced by v8::internal::BUILTIN().
WaitFor()
bool v8::internal::JSAtomicsCondition::WaitFor (Isolate * requester, DirectHandle< JSAtomicsCondition > cv, DirectHandle< JSAtomicsMutex > mutex, std::optional< base::TimeDelta > timeout) [static]
Definition at line 1177 of file js-atomics-synchronization.cc.
                                                                     {
  DisallowGarbageCollection no_gc;
  bool rv;
  {
    // Allocate a waiter queue node on-stack, since this thread is going to
    // sleep and will be blocked anyway.
    SyncWaiterQueueNode this_waiter(requester);
    JSAtomicsCondition::QueueWaiter(requester, cv, &this_waiter);
    // Release the mutex and wait for another thread to wake us up, reacquiring
    // the mutex upon wakeup.
    mutex->Unlock(requester);
    if (timeout) {
      rv = this_waiter.WaitFor(*timeout);
      if (!rv) {
        // If timed out, remove ourself from the waiter list, which is usually
        // done by the thread performing the notifying.
        std::atomic<StateT>* state = cv->AtomicStatePtr();
        DequeueExplicit(
            requester, cv, state, [&](WaiterQueueNode** waiter_head) {
              WaiterQueueNode* dequeued = WaiterQueueNode::DequeueMatching(
                  waiter_head,
                  [&](WaiterQueueNode* node) { return node == &this_waiter; });
              return dequeued ? 1 : 0;
            });
      }
    } else {
      this_waiter.Wait();
      rv = true;
    }
  }
  JSAtomicsMutex::Lock(requester, mutex);
  return rv;
}
References DequeueExplicit(), v8::internal::detail::WaiterQueueNode::DequeueMatching(), v8::internal::JSAtomicsMutex::Lock(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, QueueWaiter(), v8::internal::detail::SyncWaiterQueueNode::Wait(), and v8::internal::detail::SyncWaiterQueueNode::WaitFor().
Referenced by v8::internal::BUILTIN().
Friends And Related Function Documentation
Factory
friend class Factory [friend]
Definition at line 441 of file js-atomics-synchronization.h.
Member Data Documentation
kAllWaiters
constexpr uint32_t v8::internal::JSAtomicsCondition::kAllWaiters = UINT32_MAX [static], [constexpr]
Definition at line 421 of file js-atomics-synchronization.h.
Referenced by v8::internal::BUILTIN(), and Notify().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-atomics-synchronization.h
/mnt/V8SourceCode/src/objects/js-atomics-synchronization.cc