v8::internal::detail::SyncWaiterQueueNode Class Reference
Public Member Functions
SyncWaiterQueueNode (Isolate *requester)
void Wait ()
bool WaitFor (const base::TimeDelta &rel_time)
void Notify () override
bool IsSameIsolateForAsyncCleanup (Isolate *isolate) override
void CleanupMatchingAsyncWaiters (const DequeueMatcher &matcher) override
Private Member Functions
void SetReadyForAsyncCleanup () override
Private Attributes
base::Mutex wait_lock_
base::ConditionVariable wait_cond_var_
bool should_wait_
Additional Inherited Members
Detailed Description
Definition at line 169 of file js-atomics-synchronization.cc.
Constructor & Destructor Documentation
SyncWaiterQueueNode()
v8::internal::detail::SyncWaiterQueueNode::SyncWaiterQueueNode (Isolate * requester) [inline], [explicit]
Definition at line 171 of file js-atomics-synchronization.cc.
      : WaiterQueueNode(requester), should_wait_(true) {}
Member Function Documentation
CleanupMatchingAsyncWaiters()
void v8::internal::detail::SyncWaiterQueueNode::CleanupMatchingAsyncWaiters (const DequeueMatcher & matcher) [inline], [override], [virtual]
Implements v8::internal::detail::WaiterQueueNode.
Definition at line 226 of file js-atomics-synchronization.cc.
                                                                           {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
IsSameIsolateForAsyncCleanup()
bool v8::internal::detail::SyncWaiterQueueNode::IsSameIsolateForAsyncCleanup (Isolate * isolate) [inline], [override], [virtual]
Implements v8::internal::detail::WaiterQueueNode.
Definition at line 219 of file js-atomics-synchronization.cc.
                                                               {
    // Sync waiters are only queued while the thread is sleeping, so there
    // should not be sync nodes while cleaning up the isolate.
    DCHECK_NE(requester_, isolate);
    return false;
  }
References DCHECK_NE.
Notify()
void v8::internal::detail::SyncWaiterQueueNode::Notify () [inline], [override], [virtual]
Implements v8::internal::detail::WaiterQueueNode.
Definition at line 212 of file js-atomics-synchronization.cc.
                         {
    base::MutexGuard guard(&wait_lock_);
    should_wait_ = false;
    wait_cond_var_.NotifyOne();
    SetNotInListForVerification();
  }
SetReadyForAsyncCleanup()
void v8::internal::detail::SyncWaiterQueueNode::SetReadyForAsyncCleanup () [inline], [override], [private], [virtual]
Implements v8::internal::detail::WaiterQueueNode.
Definition at line 231 of file js-atomics-synchronization.cc.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
Wait()
void v8::internal::detail::SyncWaiterQueueNode::Wait () [inline]
Definition at line 174 of file js-atomics-synchronization.cc.
              {
    AllowGarbageCollection allow_before_parking;
    requester_->main_thread_local_heap()->ExecuteWhileParked([this]() {
      base::MutexGuard guard(&wait_lock_);
      while (should_wait_) {
        wait_cond_var_.Wait(&wait_lock_);
      }
    });
  }
Referenced by v8::internal::JSAtomicsMutex::LockSlowPath(), and v8::internal::JSAtomicsCondition::WaitFor().
WaitFor()
bool v8::internal::detail::SyncWaiterQueueNode::WaitFor (const base::TimeDelta & rel_time) [inline]
Definition at line 185 of file js-atomics-synchronization.cc.
                                              {
    bool result;
    AllowGarbageCollection allow_before_parking;
    requester_->main_thread_local_heap()->ExecuteWhileParked([this, rel_time,
                                                              &result]() {
      base::MutexGuard guard(&wait_lock_);
      base::TimeTicks current_time = base::TimeTicks::Now();
      base::TimeTicks timeout_time = current_time + rel_time;
      for (;;) {
        if (!should_wait_) {
          result = true;
          return;
        }
        current_time = base::TimeTicks::Now();
        if (current_time >= timeout_time) {
          result = false;
          return;
        }
        base::TimeDelta time_until_timeout = timeout_time - current_time;
        bool wait_res = wait_cond_var_.WaitFor(&wait_lock_, time_until_timeout);
        USE(wait_res);
        // The wake up may have been spurious, so loop again.
      }
    });
    return result;
  }
References v8::base::TimeTicks::Now(), v8::base::internal::result, and USE.
Referenced by v8::internal::JSAtomicsMutex::LockSlowPath(), and v8::internal::JSAtomicsCondition::WaitFor().
Member Data Documentation
should_wait_
bool v8::internal::detail::SyncWaiterQueueNode::should_wait_ [private]
Definition at line 235 of file js-atomics-synchronization.cc.
wait_cond_var_
base::ConditionVariable v8::internal::detail::SyncWaiterQueueNode::wait_cond_var_ [private]
Definition at line 234 of file js-atomics-synchronization.cc.
wait_lock_
base::Mutex v8::internal::detail::SyncWaiterQueueNode::wait_lock_ [private]
Definition at line 233 of file js-atomics-synchronization.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/js-atomics-synchronization.cc