cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > Class Template Reference
#include <member.h>
Public Types
using PointeeType = T
using RawStorage = typename Base::RawStorage
using AtomicInitializerTag = typename Base::AtomicInitializerTag
Public Member Functions
constexpr BasicMember ()=default
constexpr BasicMember (std::nullptr_t)
BasicMember (SentinelPointer s)
BasicMember (T *raw)
BasicMember (T &raw)
BasicMember (std::nullptr_t, AtomicInitializerTag atomic)
BasicMember (SentinelPointer s, AtomicInitializerTag atomic)
BasicMember (T *raw, AtomicInitializerTag atomic)
BasicMember (T &raw, AtomicInitializerTag atomic)
BasicMember (const BasicMember &other)
template<typename U , typename OtherBarrierPolicy , typename OtherWeaknessTag , typename OtherCheckingPolicy , std::enable_if_t< IsDecayedSameV< T, U >> * = nullptr>
BasicMember (const BasicMember< U, OtherWeaknessTag, OtherBarrierPolicy, OtherCheckingPolicy, StorageType > &other)
template<typename U , typename OtherBarrierPolicy , typename OtherWeaknessTag , typename OtherCheckingPolicy , std::enable_if_t< IsStrictlyBaseOfV< T, U >> * = nullptr>
BasicMember (const BasicMember< U, OtherWeaknessTag, OtherBarrierPolicy, OtherCheckingPolicy, StorageType > &other)
BasicMember (BasicMember &&other) noexcept
template<typename U , typename OtherBarrierPolicy , typename OtherWeaknessTag , typename OtherCheckingPolicy , std::enable_if_t< IsDecayedSameV< T, U >> * = nullptr>
BasicMember (BasicMember< U, OtherWeaknessTag, OtherBarrierPolicy, OtherCheckingPolicy, StorageType > &&other) noexcept
template<typename U , typename OtherBarrierPolicy , typename OtherWeaknessTag , typename OtherCheckingPolicy , std::enable_if_t< IsStrictlyBaseOfV< T, U >> * = nullptr>
BasicMember (BasicMember< U, OtherWeaknessTag, OtherBarrierPolicy, OtherCheckingPolicy, StorageType > &&other) noexcept
template<typename U , typename PersistentWeaknessPolicy , typename PersistentLocationPolicy , typename PersistentCheckingPolicy , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
BasicMember (const BasicPersistent< U, PersistentWeaknessPolicy, PersistentLocationPolicy, PersistentCheckingPolicy > &p)
BasicMember & operator= (const BasicMember &other)
template<typename U , typename OtherWeaknessTag , typename OtherBarrierPolicy , typename OtherCheckingPolicy >
BasicMember & operator= (const BasicMember< U, OtherWeaknessTag, OtherBarrierPolicy, OtherCheckingPolicy, StorageType > &other)
BasicMember & operator= (BasicMember &&other) noexcept
template<typename U , typename OtherWeaknessTag , typename OtherBarrierPolicy , typename OtherCheckingPolicy >
BasicMember & operator= (BasicMember< U, OtherWeaknessTag, OtherBarrierPolicy, OtherCheckingPolicy, StorageType > &&other) noexcept
template<typename U , typename PersistentWeaknessPolicy , typename PersistentLocationPolicy , typename PersistentCheckingPolicy , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
BasicMember & operator= (const BasicPersistent< U, PersistentWeaknessPolicy, PersistentLocationPolicy, PersistentCheckingPolicy > &other)
BasicMember & operator= (T *other)
BasicMember & operator= (std::nullptr_t)
BasicMember & operator= (SentinelPointer s)
template<typename OtherWeaknessTag , typename OtherBarrierPolicy , typename OtherCheckingPolicy >
void Swap (BasicMember< T, OtherWeaknessTag, OtherBarrierPolicy, OtherCheckingPolicy, StorageType > &other)
operator bool () const
operator T* () const
T * operator-> () const
T & operator* () const
V8_CLANG_NO_SANITIZE (`cfi-unrelated-cast`) T *Get() const
void Clear ()
T * Release ()
const T ** GetSlotForTesting () const
RawStorage GetRawStorage () const
Private Types
using Base = MemberBase< StorageType >
Private Member Functions
BasicMember (RawStorage raw)
BasicMember & operator= (RawStorage other)
const void * GetRawAtomic () const
const T * GetAtomic () const
void InitializingWriteBarrier (T *value) const
void InitializingWriteBarrier () const
void AssigningWriteBarrier (T *value) const
void AssigningWriteBarrier () const
void CheckPointer (T *value)
void CheckPointer ()
void ClearFromGC () const
T * GetFromGC () const
Friends
class cppgc::subtle::HeapConsistency
template<typename , typename , typename >
class cppgc::subtle::TaggedUncompressedMember
class cppgc::Visitor
template<typename U >
struct cppgc::TraceTrait
template<typename T1 , typename WeaknessTag1 , typename WriteBarrierPolicy1 , typename CheckingPolicy1 , typename StorageType1 >
class BasicMember
Detailed Description
template<typename T, typename WeaknessTag, typename WriteBarrierPolicy, typename CheckingPolicy, typename StorageType>
class cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >
Definition at line 78 of file member.h.
Member Typedef Documentation
AtomicInitializerTag
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
using cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::AtomicInitializerTag = typename Base::AtomicInitializerTag
Definition at line 99 of file member.h.
Base
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
using cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::Base = MemberBase<StorageType> [private]
Definition at line 80 of file member.h.
PointeeType
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
using cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::PointeeType = T
Definition at line 83 of file member.h.
RawStorage
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
using cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::RawStorage = typename Base::RawStorage
Definition at line 84 of file member.h.
Constructor & Destructor Documentation
BasicMember() [1/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
constexpr cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember () [inline], [constexpr], [default]
BasicMember() [2/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
constexpr cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (std::nullptr_t) [inline], [constexpr]
Definition at line 87 of file member.h.
{} // NOLINT
BasicMember() [3/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (SentinelPointer s) [inline]
Definition at line 88 of file member.h.
: Base(s) {} // NOLINT
BasicMember() [4/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (T * raw) [inline]
Definition at line 89 of file member.h.
                                : Base(raw) { // NOLINT
    InitializingWriteBarrier(raw);
    CheckPointer(raw);
  }
BasicMember() [5/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (T & raw) [inline]
Definition at line 93 of file member.h.
      : BasicMember(&raw) {}
BasicMember() [6/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (std::nullptr_t , AtomicInitializerTag atomic) [inline]
Definition at line 100 of file member.h.
      : Base(nullptr, atomic) {}
BasicMember() [7/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (SentinelPointer s, AtomicInitializerTag atomic) [inline]
Definition at line 102 of file member.h.
      : Base(s, atomic) {}
BasicMember() [8/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (T * raw, AtomicInitializerTag atomic) [inline]
Definition at line 104 of file member.h.
      : Base(raw, atomic) {
    InitializingWriteBarrier(raw);
    CheckPointer(raw);
  }
BasicMember() [9/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (T & raw, AtomicInitializerTag atomic) [inline]
Definition at line 109 of file member.h.
      : BasicMember(&raw, atomic) {}
BasicMember() [10/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > & other) [inline]
Definition at line 113 of file member.h.
      : BasicMember(other.GetRawStorage()) {}
BasicMember() [11/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
template<typename U , typename OtherBarrierPolicy , typename OtherWeaknessTag , typename OtherCheckingPolicy , std::enable_if_t< IsDecayedSameV< T, U >> * = nullptr>
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (const BasicMember< U, OtherWeaknessTag, OtherBarrierPolicy, OtherCheckingPolicy, StorageType > & other) [inline]
Definition at line 122 of file member.h.
      : BasicMember(other.GetRawStorage()) {}
BasicMember() [12/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
template<typename U , typename OtherBarrierPolicy , typename OtherWeaknessTag , typename OtherCheckingPolicy , std::enable_if_t< IsStrictlyBaseOfV< T, U >> * = nullptr>
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (const BasicMember< U, OtherWeaknessTag, OtherBarrierPolicy, OtherCheckingPolicy, StorageType > & other) [inline]
Definition at line 130 of file member.h.
      : BasicMember(other.Get()) {}
BasicMember() [13/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > && other) [inline], [noexcept]
Definition at line 136 of file member.h.
      : BasicMember(other.GetRawStorage()) {
    other.Clear();
  }
References cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::Clear().
BasicMember() [14/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
template<typename U , typename OtherBarrierPolicy , typename OtherWeaknessTag , typename OtherCheckingPolicy , std::enable_if_t< IsDecayedSameV< T, U >> * = nullptr>
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (BasicMember< U, OtherWeaknessTag, OtherBarrierPolicy, OtherCheckingPolicy, StorageType > && other) [inline], [noexcept]
Definition at line 147 of file member.h.
      : BasicMember(other.GetRawStorage()) {
    other.Clear();
  }
References cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::Clear().
BasicMember() [15/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
template<typename U , typename OtherBarrierPolicy , typename OtherWeaknessTag , typename OtherCheckingPolicy , std::enable_if_t< IsStrictlyBaseOfV< T, U >> * = nullptr>
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (BasicMember< U, OtherWeaknessTag, OtherBarrierPolicy, OtherCheckingPolicy, StorageType > && other) [inline], [noexcept]
Definition at line 157 of file member.h.
      : BasicMember(other.Get()) {
    other.Clear();
  }
References cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::Clear().
BasicMember() [16/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
template<typename U , typename PersistentWeaknessPolicy , typename PersistentLocationPolicy , typename PersistentCheckingPolicy , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (const BasicPersistent< U, PersistentWeaknessPolicy, PersistentLocationPolicy, PersistentCheckingPolicy > & p) [inline]
Definition at line 169 of file member.h.
      : BasicMember(p.Get()) {}
BasicMember() [17/17]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember (RawStorage raw) [inline], [explicit], [private]
Definition at line 289 of file member.h.
                                                 : Base(raw) {
    InitializingWriteBarrier();
    CheckPointer();
  }
Member Function Documentation
AssigningWriteBarrier() [1/2]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
void cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::AssigningWriteBarrier () const [inline], [private]
Definition at line 318 of file member.h.
                                               {
    WriteBarrierPolicy::template AssigningBarrier<
        StorageType::kWriteBarrierSlotType>(Base::GetRawSlot(),
                                            Base::GetRawStorage());
  }
AssigningWriteBarrier() [2/2]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
void cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::AssigningWriteBarrier (T * value) const [inline], [private]
Definition at line 314 of file member.h.
                                                       {
    WriteBarrierPolicy::template AssigningBarrier<
        StorageType::kWriteBarrierSlotType>(Base::GetRawSlot(), value);
  }
References v8::internal::value.
CheckPointer() [1/2]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
void cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::CheckPointer () [inline], [private]
Definition at line 326 of file member.h.
                                {
    CheckingPolicy::template CheckPointer<T>(Base::GetRawStorage());
  }
CheckPointer() [2/2]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
void cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::CheckPointer (T * value) [inline], [private]
Definition at line 323 of file member.h.
                                        {
    CheckingPolicy::template CheckPointer<T>(value);
  }
References v8::internal::value.
Clear()
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
void cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::Clear () [inline]
Definition at line 274 of file member.h.
{ Base::SetRawStorageAtomic(RawStorage{}); }
Referenced by cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::BasicMember().
ClearFromGC()
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
void cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::ClearFromGC () const [inline], [private]
Definition at line 330 of file member.h.
{ Base::ClearFromGC(); }
GetAtomic()
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
const T* cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::GetAtomic () const [inline], [private]
Definition at line 303 of file member.h.
                                       {
    return static_cast<const T*>(GetRawAtomic());
  }
Referenced by cppgc::Visitor::Trace(), cppgc::Visitor::TraceEphemeron(), and cppgc::Visitor::TraceStrongly().
GetFromGC()
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
T* cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::GetFromGC () const [inline], [private]
Definition at line 332 of file member.h.
{ return Get(); }
References v8::internal::compiler::turboshaft::Get().
GetRawAtomic()
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
const void* cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::GetRawAtomic () const [inline], [private]
Definition at line 301 of file member.h.
{ return Base::GetRawAtomic(); }
GetRawStorage()
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
RawStorage cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::GetRawStorage () const [inline]
Definition at line 286 of file member.h.
{ return Base::GetRawStorage(); }
Referenced by cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator=().
GetSlotForTesting()
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
const T** cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::GetSlotForTesting () const [inline]
Definition at line 282 of file member.h.
                                                {
    return reinterpret_cast<const T**>(Base::GetRawSlot());
  }
InitializingWriteBarrier() [1/2]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
void cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::InitializingWriteBarrier () const [inline], [private]
Definition at line 310 of file member.h.
                                                  {
    WriteBarrierPolicy::InitializingBarrier(Base::GetRawSlot(),
                                            Base::GetRawStorage());
  }
InitializingWriteBarrier() [2/2]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
void cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::InitializingWriteBarrier (T * value) const [inline], [private]
Definition at line 307 of file member.h.
                                                          {
    WriteBarrierPolicy::InitializingBarrier(Base::GetRawSlot(), value);
  }
References v8::internal::value.
operator bool()
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator bool () const [inline], [explicit]
Definition at line 257 of file member.h.
{ return !Base::IsCleared(); }
operator T*()
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator T* () const [inline]
Definition at line 258 of file member.h.
{ return Get(); }
operator*()
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
T& cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator* () const [inline]
Definition at line 260 of file member.h.
{ return *Get(); }
References v8::internal::compiler::turboshaft::Get().
operator->()
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
T* cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator-> () const [inline]
Definition at line 259 of file member.h.
{ return Get(); }
References v8::internal::compiler::turboshaft::Get().
operator=() [1/9]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
BasicMember& cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator= (BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > && other) [inline], [noexcept]
Definition at line 196 of file member.h.
                                                                 {
    operator=(other.GetRawStorage());
    other.Clear();
    return *this;
  }
operator=() [2/9]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
template<typename U , typename OtherWeaknessTag , typename OtherBarrierPolicy , typename OtherCheckingPolicy >
BasicMember& cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator= (BasicMember< U, OtherWeaknessTag, OtherBarrierPolicy, OtherCheckingPolicy, StorageType > && other) [inline], [noexcept]
Definition at line 207 of file member.h.
                                                 {
    if constexpr (IsDecayedSameV<T, U>) {
      operator=(other.GetRawStorage());
    } else {
      static_assert(IsStrictlyBaseOfV<T, U>);
      operator=(other.Get());
    }
    other.Clear();
    return *this;
  }
operator=() [3/9]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
BasicMember& cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator= (const BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType > & other) [inline]
Definition at line 175 of file member.h.
                                                             {
    return operator=(other.GetRawStorage());
  }
References cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::GetRawStorage().
operator=() [4/9]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
template<typename U , typename OtherWeaknessTag , typename OtherBarrierPolicy , typename OtherCheckingPolicy >
BasicMember& cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator= (const BasicMember< U, OtherWeaknessTag, OtherBarrierPolicy, OtherCheckingPolicy, StorageType > & other) [inline]
Definition at line 184 of file member.h.
                                                                  {
    if constexpr (IsDecayedSameV<T, U>) {
      return operator=(other.GetRawStorage());
    } else {
      static_assert(IsStrictlyBaseOfV<T, U>);
      return operator=(other.Get());
    }
  }
operator=() [5/9]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
template<typename U , typename PersistentWeaknessPolicy , typename PersistentLocationPolicy , typename PersistentCheckingPolicy , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
BasicMember& cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator= (const BasicPersistent< U, PersistentWeaknessPolicy, PersistentLocationPolicy, PersistentCheckingPolicy > & other) [inline]
Definition at line 225 of file member.h.
                 {
    return operator=(other.Get());
  }
operator=() [6/9]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
BasicMember& cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator= (RawStorage other) [inline], [private]
Definition at line 294 of file member.h.
                                                     {
    Base::SetRawStorageAtomic(other);
    AssigningWriteBarrier();
    CheckPointer();
    return *this;
  }
operator=() [7/9]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
BasicMember& cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator= (SentinelPointer s) [inline]
Definition at line 243 of file member.h.
                                                      {
    Base::SetRawAtomic(s);
    return *this;
  }
operator=() [8/9]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
BasicMember& cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator= (std::nullptr_t) [inline]
Definition at line 239 of file member.h.
                                                 {
    Clear();
    return *this;
  }
operator=() [9/9]
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
BasicMember& cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::operator= (T * other) [inline]
Definition at line 232 of file member.h.
                                             {
    Base::SetRawAtomic(other);
    AssigningWriteBarrier(other);
    CheckPointer(other);
    return *this;
  }
Release()
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
T* cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::Release () [inline]
Definition at line 276 of file member.h.
                         {
    T* result = Get();
    Clear();
    return result;
  }
References v8::internal::compiler::turboshaft::Get(), and v8::base::internal::result.
Swap()
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
template<typename OtherWeaknessTag , typename OtherBarrierPolicy , typename OtherCheckingPolicy >
void cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::Swap (BasicMember< T, OtherWeaknessTag, OtherBarrierPolicy, OtherCheckingPolicy, StorageType > & other) [inline]
Definition at line 250 of file member.h.
                                                                            {
    auto tmp = GetRawStorage();
    *this = other;
    other = tmp;
  }
V8_CLANG_NO_SANITIZE()
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::V8_CLANG_NO_SANITIZE (`cfi-unrelated-cast`) const [inline]
Definition at line 265 of file member.h.
                                                                      {
    // Executed by the mutator, hence non atomic load.
    //
    // The const_cast below removes the constness from MemberBase storage. The
    // following static_cast re-adds any constness if specified through the
    // user-visible template parameter T.
    return static_cast<T*>(const_cast<void*>(Base::GetRaw()));
  }
Friends And Related Function Documentation
BasicMember
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
template<typename T1 , typename WeaknessTag1 , typename WriteBarrierPolicy1 , typename CheckingPolicy1 , typename StorageType1 >
friend class BasicMember [friend]
Definition at line 342 of file member.h.
cppgc::subtle::HeapConsistency
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
friend class cppgc::subtle::HeapConsistency [friend]
Definition at line 334 of file member.h.
cppgc::subtle::TaggedUncompressedMember
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
template<typename , typename , typename >
friend class cppgc::subtle::TaggedUncompressedMember [friend]
Definition at line 336 of file member.h.
cppgc::TraceTrait
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
template<typename U >
friend struct cppgc::TraceTrait [friend]
Definition at line 339 of file member.h.
cppgc::Visitor
template<typename T , typename WeaknessTag , typename WriteBarrierPolicy , typename CheckingPolicy , typename StorageType >
friend class cppgc::Visitor [friend]
Definition at line 337 of file member.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/internal/pointer-policies.h
/mnt/V8SourceCode/include/cppgc/member.h