v8::internal::ZoneChunkListIterator< T, backwards, modifiable > Class Template Reference
#include <zone-chunk-list.h>
Public Member Functions
maybe_const< T > & operator* () const
maybe_const< T > * operator-> () const
bool operator== (const ZoneChunkListIterator &other) const
bool operator!= (const ZoneChunkListIterator &other) const
ZoneChunkListIterator & operator++ ()
ZoneChunkListIterator operator++ (int)
ZoneChunkListIterator & operator-- ()
ZoneChunkListIterator operator-- (int)
void Advance (uint32_t amount)
Private Types
template<typename S >
using maybe_const = std::conditional_t< modifiable, S, std::add_const_t< S > >
using Chunk = maybe_const< typename ZoneChunkList< T >::Chunk >
using ChunkList = maybe_const< ZoneChunkList< T > >
Private Member Functions
ZoneChunkListIterator (Chunk *current, uint32_t position)
template<bool move_backward>
void Move ()
Static Private Member Functions
static ZoneChunkListIterator Begin (ChunkList *list)
static ZoneChunkListIterator End (ChunkList *list)
Private Attributes
Chunk * current_
uint32_t position_
Friends
class ZoneChunkList< T >
Additional Inherited Members
Detailed Description
template<typename T, bool backwards, bool modifiable>
class v8::internal::ZoneChunkListIterator< T, backwards, modifiable >
Definition at line 188 of file zone-chunk-list.h.
Member Typedef Documentation
Chunk
template<typename T , bool backwards, bool modifiable>
using v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Chunk = maybe_const<typename ZoneChunkList<T>::Chunk> [private]
Definition at line 193 of file zone-chunk-list.h.
ChunkList
template<typename T , bool backwards, bool modifiable>
using v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::ChunkList = maybe_const<ZoneChunkList<T> > [private]
Definition at line 194 of file zone-chunk-list.h.
maybe_const
template<typename T , bool backwards, bool modifiable>
template<typename S >
using v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::maybe_const = std::conditional_t<modifiable, S, std::add_const_t<S> > [private]
Definition at line 192 of file zone-chunk-list.h.
Constructor & Destructor Documentation
ZoneChunkListIterator()
template<typename T , bool backwards, bool modifiable>
v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::ZoneChunkListIterator (Chunk * current, uint32_t position) [inline], [private]
Definition at line 279 of file zone-chunk-list.h.
      : current_(current), position_(position) {
    DCHECK(current == nullptr || position < current->capacity_);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Begin(), and v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::End().
Member Function Documentation
Advance()
template<typename T , bool backwards, bool modifiable>
void v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Advance (uint32_t amount) [inline]
Definition at line 228 of file zone-chunk-list.h.
                                {
    static_assert(!backwards, "Advance only works on forward iterators");
#ifdef DEBUG
    ZoneChunkListIterator clone(*this);
    for (uint32_t i = 0; i < amount; ++i) {
      ++clone;
    }
#endif
    CHECK(!base::bits::UnsignedAddOverflow32(position_, amount, &position_));
    while (position_ > 0 && position_ >= current_->position_) {
      auto overshoot = position_ - current_->position_;
      current_ = current_->next_;
      position_ = overshoot;
      DCHECK(position_ == 0 || current_);
    }
#ifdef DEBUG
    DCHECK_EQ(clone, *this);
#endif
  }
References CHECK, v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::current_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::position_, and v8::base::bits::UnsignedAddOverflow32().
Begin()
template<typename T , bool backwards, bool modifiable>
static ZoneChunkListIterator v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Begin (ChunkList * list) [inline], [static], [private]
Definition at line 255 of file zone-chunk-list.h.
                                                      {
    // Forward iterator:
    if (!backwards) return ZoneChunkListIterator(list->front_, 0);
    // Backward iterator:
    if (list->empty()) return End(list);
    DCHECK(!list->last_nonempty_->empty());
    return ZoneChunkListIterator(list->last_nonempty_,
                                 list->last_nonempty_->position_ - 1);
  }
References v8::internal::DCHECK(), v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::End(), and v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::ZoneChunkListIterator().
Referenced by v8::internal::ZoneChunkList< T >::begin(), v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::End(), and v8::internal::ZoneChunkList< T >::rbegin().
End()
template<typename T , bool backwards, bool modifiable>
static ZoneChunkListIterator v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::End (ChunkList * list) [inline], [static], [private]
Definition at line 267 of file zone-chunk-list.h.
                                                    {
    // Backward iterator:
    if (backwards) return ZoneChunkListIterator(nullptr, 0);
    // Forward iterator:
    if (list->empty()) return Begin(list);
    // NOTE: Decrementing `end()` is not supported if `last_nonempty_->next_`
    // is nullptr (in that case `Move` will crash on dereference).
    return ZoneChunkListIterator(list->last_nonempty_->next_, 0);
  }
References v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Begin(), and v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::ZoneChunkListIterator().
Referenced by v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Begin(), v8::internal::ZoneChunkList< T >::end(), and v8::internal::ZoneChunkList< T >::rend().
Move()
template<typename T , bool backwards, bool modifiable>
template<bool move_backward>
void v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Move () [inline], [private]
Definition at line 285 of file zone-chunk-list.h.
              {
    if (move_backward) {
      // Move backwards.
      if (position_ == 0) {
        current_ = current_->previous_;
        position_ = current_ ? current_->position_ - 1 : 0;
      } else {
        --position_;
      }
    } else {
      // Move forwards.
      ++position_;
      if (position_ >= current_->position_) {
        current_ = current_->next_;
        position_ = 0;
      }
    }
  }
References v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::current_, and v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::position_.
operator!=()
template<typename T , bool backwards, bool modifiable>
bool v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator!= (const ZoneChunkListIterator< T, backwards, modifiable > & other) const [inline]
Definition at line 202 of file zone-chunk-list.h.
                                                            {
    return !operator==(other);
  }
References v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator==().
operator*()
template<typename T , bool backwards, bool modifiable>
maybe_const<T>& v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator* () const [inline]
Definition at line 197 of file zone-chunk-list.h.
{ return current_->items()[position_]; }
References v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::current_, and v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::position_.
operator++() [1/2]
template<typename T , bool backwards, bool modifiable>
ZoneChunkListIterator& v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator++ () [inline]
Definition at line 206 of file zone-chunk-list.h.
                                      {
    Move<backwards>();
    return *this;
  }
operator++() [2/2]
template<typename T , bool backwards, bool modifiable>
ZoneChunkListIterator v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator++ (int) [inline]
Definition at line 211 of file zone-chunk-list.h.
                                        {
    ZoneChunkListIterator clone(*this);
    Move<backwards>();
    return clone;
  }
operator--() [1/2]
template<typename T , bool backwards, bool modifiable>
ZoneChunkListIterator& v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator-- () [inline]
Definition at line 217 of file zone-chunk-list.h.
                                      {
    Move<!backwards>();
    return *this;
  }
operator--() [2/2]
template<typename T , bool backwards, bool modifiable>
ZoneChunkListIterator v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator-- (int) [inline]
Definition at line 222 of file zone-chunk-list.h.
                                        {
    ZoneChunkListIterator clone(*this);
    Move<!backwards>();
    return clone;
  }
operator->()
template<typename T , bool backwards, bool modifiable>
maybe_const<T>* v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator-> () const [inline]
Definition at line 198 of file zone-chunk-list.h.
{ return &current_->items()[position_]; }
References v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::current_, and v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::position_.
operator==()
template<typename T , bool backwards, bool modifiable>
bool v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator== (const ZoneChunkListIterator< T, backwards, modifiable > & other) const [inline]
Definition at line 199 of file zone-chunk-list.h.
                                                            {
    return other.current_ == current_ && other.position_ == position_;
  }
References v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::current_, and v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::position_.
Referenced by v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator!=().
Friends And Related Function Documentation
ZoneChunkList< T >
template<typename T , bool backwards, bool modifiable>
friend class ZoneChunkList< T > [friend]
Definition at line 228 of file zone-chunk-list.h.
Member Data Documentation
current_
template<typename T , bool backwards, bool modifiable>
Chunk* v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::current_ [private]
Definition at line 304 of file zone-chunk-list.h.
Referenced by v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Advance(), v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Move(), v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator*(), v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator->(), v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator==(), and v8::internal::ZoneChunkList< T >::SplitAt().
position_
template<typename T , bool backwards, bool modifiable>
uint32_t v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::position_ [private]
Definition at line 305 of file zone-chunk-list.h.
Referenced by v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Advance(), v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Move(), v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator*(), v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator->(), v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::operator==(), and v8::internal::ZoneChunkList< T >::SplitAt().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/zone/zone-chunk-list.h