v8::internal::wasm::LiftoffStackSlots Class Reference
#include <liftoff-assembler.h>
Classes
struct Slot
Public Member Functions
LiftoffStackSlots (LiftoffAssembler *wasm_asm)
LiftoffStackSlots (const LiftoffStackSlots &)=delete
LiftoffStackSlots & operator= (const LiftoffStackSlots &)=delete
void Add (const LiftoffAssembler::VarState &src, uint32_t src_offset, RegPairHalf half, int dst_slot)
void Add (const LiftoffAssembler::VarState &src, int dst_slot)
void SortInPushOrder ()
void Construct (int param_slots)
Static Private Member Functions
static int SlotSizeInBytes (const Slot &slot)
Private Attributes
base::SmallVector< Slot, 8 > slots_
LiftoffAssembler *const asm_
Detailed Description
Definition at line 1673 of file liftoff-assembler.h.
Constructor & Destructor Documentation
LiftoffStackSlots() [1/2]
v8::internal::wasm::LiftoffStackSlots::LiftoffStackSlots (LiftoffAssembler * wasm_asm) [inline], [explicit]
Definition at line 1675 of file liftoff-assembler.h.
: asm_(wasm_asm) {}
LiftoffStackSlots() [2/2]
v8::internal::wasm::LiftoffStackSlots::LiftoffStackSlots (const LiftoffStackSlots &) [delete]
Member Function Documentation
Add() [1/2]
void v8::internal::wasm::LiftoffStackSlots::Add (const LiftoffAssembler::VarState & src, int dst_slot) [inline]
Definition at line 1685 of file liftoff-assembler.h.
                                                              {
    DCHECK_LE(0, dst_slot);
    slots_.emplace_back(src, dst_slot);
  }
References DCHECK_LE, and slots_.
Add() [2/2]
void v8::internal::wasm::LiftoffStackSlots::Add (const LiftoffAssembler::VarState & src, uint32_t src_offset, RegPairHalf half, int dst_slot) [inline]
Definition at line 1679 of file liftoff-assembler.h.
                                           {
    DCHECK_LE(0, dst_slot);
    slots_.emplace_back(src, src_offset, half, dst_slot);
  }
References DCHECK_LE, and slots_.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::PrepareStackTransfers().
Construct()
void v8::internal::wasm::LiftoffStackSlots::Construct (int param_slots) [inline]
Definition at line 5004 of file liftoff-assembler-arm-inl.h.
                                                 {
  DCHECK_LT(0, slots_.size());
  SortInPushOrder();
  int last_stack_slot = param_slots;
  for (auto& slot : slots_) {
    const int stack_slot = slot.dst_slot_;
    int stack_decrement = (last_stack_slot - stack_slot) * kSystemPointerSize;
    DCHECK_LT(0, stack_decrement);
    last_stack_slot = stack_slot;
    const LiftoffAssembler::VarState& src = slot.src_;
    switch (src.loc()) {
      case LiftoffAssembler::VarState::kStack: {
        switch (src.kind()) {
          // i32 and i64 can be treated as similar cases, i64 being previously
          // split into two i32 registers
          case kI32:
          case kI64:
          case kF32:
          case kRef:
          case kRefNull: {
            asm_->AllocateStackSpace(stack_decrement - kSystemPointerSize);
            UseScratchRegisterScope temps(asm_);
            Register scratch = temps.Acquire();
            asm_->ldr(scratch,
                      liftoff::GetHalfStackSlot(slot.src_offset_, slot.half_));
            asm_->Push(scratch);
          } break;
          case kF64: {
            asm_->AllocateStackSpace(stack_decrement - kDoubleSize);
            UseScratchRegisterScope temps(asm_);
            DwVfpRegister scratch = temps.AcquireD();
            asm_->vldr(scratch, liftoff::GetStackSlot(slot.src_offset_));
            asm_->vpush(scratch);
          } break;
          case kS128: {
            asm_->AllocateStackSpace(stack_decrement - kSimd128Size);
            MemOperand mem_op = liftoff::GetStackSlot(slot.src_offset_);
            UseScratchRegisterScope temps(asm_);
            Register addr = liftoff::CalculateActualAddress(
                asm_, &temps, mem_op.rn(), no_reg, mem_op.offset());
            QwNeonRegister scratch = temps.AcquireQ();
            asm_->vld1(Neon8, NeonListOperand(scratch), NeonMemOperand(addr));
            asm_->vpush(scratch);
            break;
          }
          default:
            UNREACHABLE();
        }
        break;
      }
      case LiftoffAssembler::VarState::kRegister: {
        int pushed_bytes = SlotSizeInBytes(slot);
        asm_->AllocateStackSpace(stack_decrement - pushed_bytes);
        switch (src.kind()) {
          case kI64: {
            LiftoffRegister reg =
                slot.half_ == kLowWord ? src.reg().low() : src.reg().high();
            asm_->push(reg.gp());
            break;
          }
          case kI32:
          case kRef:
          case kRefNull:
            asm_->push(src.reg().gp());
            break;
          case kF32:
            asm_->vpush(liftoff::GetFloatRegister(src.reg().fp()));
            break;
          case kF64:
            asm_->vpush(src.reg().fp());
            break;
          case kS128:
            asm_->vpush(liftoff::GetSimd128Register(src.reg()));
            break;
          default:
            UNREACHABLE();
        }
        break;
      }
      case LiftoffAssembler::VarState::kIntConst: {
        asm_->AllocateStackSpace(stack_decrement - kSystemPointerSize);
        DCHECK(src.kind() == kI32 || src.kind() == kI64);
        UseScratchRegisterScope temps(asm_);
        Register scratch = temps.Acquire();
        // The high word is the sign extension of the low word.
        asm_->mov(scratch,
                  Operand(slot.half_ == kLowWord ? src.i32_const()
                                                 : src.i32_const() >> 31));
        asm_->push(scratch);
        break;
      }
    }
  }
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::UseScratchRegisterScope::AcquireD(), v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::MacroAssembler::AllocateStackSpace(), asm_, v8::internal::wasm::liftoff::CalculateActualAddress(), v8::internal::DCHECK(), DCHECK_LT, v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::liftoff::GetFloatRegister(), v8::internal::wasm::liftoff::GetHalfStackSlot(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::liftoff::GetStackSlot(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high(), v8::internal::wasm::LiftoffVarState::i32_const(), v8::internal::kDoubleSize, v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::wasm::LiftoffVarState::kind(), v8::internal::wasm::LiftoffVarState::kIntConst, v8::internal::wasm::kLowWord, v8::internal::kRef, v8::internal::kRefNull, v8::internal::wasm::LiftoffVarState::kRegister, v8::internal::kS128, v8::internal::kSimd128Size, v8::internal::wasm::LiftoffVarState::kStack, v8::internal::kSystemPointerSize, v8::internal::Assembler::ldr(), v8::internal::wasm::LiftoffVarState::loc(), v8::internal::wasm::LiftoffRegister::low(), v8::internal::MacroAssembler::mov(), v8::internal::Neon8, v8::internal::no_reg, v8::internal::MemOperand::offset(), v8::internal::MacroAssembler::Push(), v8::internal::MacroAssembler::push(), v8::internal::wasm::LiftoffVarState::reg(), v8::internal::MemOperand::rn(), slots_, SlotSizeInBytes(), SortInPushOrder(), v8::internal::UNREACHABLE(), v8::internal::Assembler::vld1(), v8::internal::Assembler::vldr(), and v8::internal::Assembler::vpush().
operator=()
LiftoffStackSlots& v8::internal::wasm::LiftoffStackSlots::operator= (const LiftoffStackSlots &) [delete]
SlotSizeInBytes()
static int v8::internal::wasm::LiftoffStackSlots::SlotSizeInBytes (const Slot & slot) [inline], [static], [private]
Definition at line 1717 of file liftoff-assembler.h.
                                               {
    const ValueKind kind = slot.src_.kind();
    if (kind == kS128) return kSimd128Size;
    if (kind == kF64) return kDoubleSize;
    return kSystemPointerSize;
  }
References v8::internal::kDoubleSize, v8::internal::kF64, v8::internal::wasm::LiftoffVarState::kind(), v8::internal::kS128, v8::internal::kSimd128Size, v8::internal::kSystemPointerSize, and v8::internal::wasm::LiftoffStackSlots::Slot::src_.
Referenced by Construct().
SortInPushOrder()
void v8::internal::wasm::LiftoffStackSlots::SortInPushOrder () [inline]
Definition at line 1690 of file liftoff-assembler.h.
                         {
    std::sort(slots_.begin(), slots_.end(), [](const Slot& a, const Slot& b) {
      return a.dst_slot_ > b.dst_slot_;
    });
  }
References slots_, and v8::base::sort().
Referenced by Construct().
Member Data Documentation
asm_
LiftoffAssembler* const v8::internal::wasm::LiftoffStackSlots::asm_ [private]
Definition at line 1725 of file liftoff-assembler.h.
Referenced by Construct().
slots_
base::SmallVector<Slot, 8> v8::internal::wasm::LiftoffStackSlots::slots_ [private]
Definition at line 1724 of file liftoff-assembler.h.
Referenced by Add(), Construct(), and SortInPushOrder().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/baseline/liftoff-assembler.h
/mnt/V8SourceCode/src/wasm/baseline/arm/liftoff-assembler-arm-inl.h
/mnt/V8SourceCode/src/wasm/baseline/arm64/liftoff-assembler-arm64-inl.h
/mnt/V8SourceCode/src/wasm/baseline/ia32/liftoff-assembler-ia32-inl.h
/mnt/V8SourceCode/src/wasm/baseline/loong64/liftoff-assembler-loong64-inl.h
/mnt/V8SourceCode/src/wasm/baseline/mips64/liftoff-assembler-mips64-inl.h
/mnt/V8SourceCode/src/wasm/baseline/ppc/liftoff-assembler-ppc-inl.h
/mnt/V8SourceCode/src/wasm/baseline/riscv/liftoff-assembler-riscv32-inl.h
/mnt/V8SourceCode/src/wasm/baseline/riscv/liftoff-assembler-riscv64-inl.h
/mnt/V8SourceCode/src/wasm/baseline/s390/liftoff-assembler-s390-inl.h
/mnt/V8SourceCode/src/wasm/baseline/x64/liftoff-assembler-x64-inl.h