v8::internal::FeedbackCollectorReducer< Next > Class Template Reference
#include <turboshaft-builtins-assembler-inl.h>
Public Types
using FeedbackVectorOrUndefined = Union< FeedbackVector, Undefined >
Public Member Functions
void CombineFeedback (int additional_feedback)
void OverwriteFeedback (int new_feedback)
void CombineFeedbackOnException (int additional_feedback)
void CombineExceptionFeedback ()
V< Word32 > FeedbackIs (int checked_feedback)
V< FeedbackVectorOrUndefined > LoadFeedbackVector ()
V< WordPtr > LoadFeedbackVectorLength (V< FeedbackVector > feedback_vector)
V< MaybeObject > LoadFeedbackVectorSlot (V< FeedbackVector > feedback_vector, V< WordPtr > slot, int additional_offset=0)
void StoreFeedbackVectorSlot (V< FeedbackVector > feedback_vector, V< WordPtr > slot, V< Object > value, WriteBarrierMode barrier_mode=UPDATE_WRITE_BARRIER, int additional_offset=0)
void SetFeedbackSlot (V< WordPtr > slot_id)
void SetFeedbackVector (V< FeedbackVector > feedback_vector)
void LoadFeedbackVectorOrUndefinedIfJitless ()
void UpdateFeedback ()
V< Smi > SmiBitwiseOr (V< Smi > a, V< Smi > b)
V< Word32 > SmiEqual (V< Smi > a, V< Smi > b)
V< WordPtr > ChangePositiveInt32ToIntPtr (V< Word32 > input)
V< Word32 > IsFeedbackVector (V< HeapObject > heap_object)
V< Word32 > IsOffsetInBounds (V< WordPtr > offset, V< WordPtr > length, int header_size, ElementsKind kind=HOLEY_ELEMENTS)
Static Public Member Functions
static constexpr bool HasFeedbackCollector ()
static constexpr UpdateFeedbackMode DefaultUpdateFeedbackMode ()
Private Attributes
V< FeedbackVectorOrUndefined > maybe_feedback_vector_
V< WordPtr > slot_id_
compiler::turboshaft::Var< Smi, assembler_t > feedback_ {this}
compiler::turboshaft::Var< Smi, assembler_t > feedback_on_exception_ {this}
UpdateFeedbackMode mode_ = DefaultUpdateFeedbackMode()
Detailed Description
template<typename Next>
class v8::internal::FeedbackCollectorReducer< Next >
Definition at line 176 of file turboshaft-builtins-assembler-inl.h.
Member Typedef Documentation
FeedbackVectorOrUndefined
template<typename Next >
using v8::internal::FeedbackCollectorReducer< Next >::FeedbackVectorOrUndefined = Union<FeedbackVector, Undefined>
Definition at line 180 of file turboshaft-builtins-assembler-inl.h.
Member Function Documentation
ChangePositiveInt32ToIntPtr()
template<typename Next >
V<WordPtr> v8::internal::FeedbackCollectorReducer< Next >::ChangePositiveInt32ToIntPtr (V< Word32 > input) [inline]
Definition at line 337 of file turboshaft-builtins-assembler-inl.h.
                                                          {
    TSA_DCHECK(this, __ Int32LessThanOrEqual(0, input));
    return __ ChangeUint32ToUintPtr(input);
  }
References __.
Referenced by v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorLength().
CombineExceptionFeedback()
template<typename Next >
void v8::internal::FeedbackCollectorReducer< Next >::CombineExceptionFeedback () [inline]
Definition at line 198 of file turboshaft-builtins-assembler-inl.h.
                                  {
    feedback_ = __ SmiBitwiseOr(feedback_, feedback_on_exception_);
  }
References __, v8::internal::FeedbackCollectorReducer< Next >::feedback_, v8::internal::FeedbackCollectorReducer< Next >::feedback_on_exception_, and v8::internal::FeedbackCollectorReducer< Next >::SmiBitwiseOr().
CombineFeedback()
template<typename Next >
void v8::internal::FeedbackCollectorReducer< Next >::CombineFeedback (int additional_feedback) [inline]
Definition at line 183 of file turboshaft-builtins-assembler-inl.h.
                                                {
    __ CodeComment("CombineFeedback");
    feedback_ = __ SmiBitwiseOr(
        feedback_, __ SmiConstant(Smi::FromInt(additional_feedback)));
  }
References __, v8::internal::FeedbackCollectorReducer< Next >::feedback_, v8::internal::Smi::FromInt(), and v8::internal::FeedbackCollectorReducer< Next >::SmiBitwiseOr().
CombineFeedbackOnException()
template<typename Next >
void v8::internal::FeedbackCollectorReducer< Next >::CombineFeedbackOnException (int additional_feedback) [inline]
Definition at line 194 of file turboshaft-builtins-assembler-inl.h.
                                                           {
    feedback_on_exception_ = __ SmiConstant(Smi::FromInt(additional_feedback));
  }
References __, v8::internal::FeedbackCollectorReducer< Next >::feedback_on_exception_, and v8::internal::Smi::FromInt().
DefaultUpdateFeedbackMode()
template<typename Next >
static constexpr UpdateFeedbackMode v8::internal::FeedbackCollectorReducer< Next >::DefaultUpdateFeedbackMode () [inline], [static], [constexpr]
Definition at line 283 of file turboshaft-builtins-assembler-inl.h.
                                                                  {
#ifndef V8_JITLESS
    return UpdateFeedbackMode::kOptionalFeedback;
#else
    return UpdateFeedbackMode::kNoFeedback;
#endif // !V8_JITLESS
  }
References v8::internal::kNoFeedback, and v8::internal::kOptionalFeedback.
FeedbackIs()
template<typename Next >
V<Word32> v8::internal::FeedbackCollectorReducer< Next >::FeedbackIs (int checked_feedback) [inline]
Definition at line 202 of file turboshaft-builtins-assembler-inl.h.
                                             {
    return __ SmiEqual(feedback_,
                       __ SmiConstant(Smi::FromInt(checked_feedback)));
  }
References __, v8::internal::FeedbackCollectorReducer< Next >::feedback_, v8::internal::Smi::FromInt(), and v8::internal::FeedbackCollectorReducer< Next >::SmiEqual().
HasFeedbackCollector()
template<typename Next >
static constexpr bool v8::internal::FeedbackCollectorReducer< Next >::HasFeedbackCollector () [inline], [static], [constexpr]
Definition at line 181 of file turboshaft-builtins-assembler-inl.h.
{ return true; }
IsFeedbackVector()
template<typename Next >
V<Word32> v8::internal::FeedbackCollectorReducer< Next >::IsFeedbackVector (V< HeapObject > heap_object) [inline]
Definition at line 342 of file turboshaft-builtins-assembler-inl.h.
                                                        {
    V<Map> map = __ LoadMapField(heap_object);
    return __ IsFeedbackVectorMap(map);
  }
References __.
Referenced by v8::internal::FeedbackCollectorReducer< Next >::SetFeedbackVector().
IsOffsetInBounds()
template<typename Next >
V<Word32> v8::internal::FeedbackCollectorReducer< Next >::IsOffsetInBounds (V< WordPtr > offset, V< WordPtr > length, int header_size, ElementsKind kind = HOLEY_ELEMENTS) [inline]
Definition at line 347 of file turboshaft-builtins-assembler-inl.h.
                                                                 {
    // Make sure we point to the last field.
    int element_size = 1 << ElementsKindToShiftSize(kind);
    int correction = header_size - element_size;
    V<WordPtr> last_offset =
        __ ElementOffsetFromIndex(length, kind, correction);
    return __ IntPtrLessThanOrEqual(offset, last_offset);
  }
References __, v8::internal::ElementsKindToShiftSize(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThanOrEqual(), and v8::internal::length.
Referenced by v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorSlot(), and v8::internal::FeedbackCollectorReducer< Next >::StoreFeedbackVectorSlot().
LoadFeedbackVector()
template<typename Next >
V<FeedbackVectorOrUndefined> v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVector () [inline]
Definition at line 207 of file turboshaft-builtins-assembler-inl.h.
                                                    {
    return V<FeedbackVectorOrUndefined>::Cast(
        __ LoadRegister(interpreter::Register::feedback_vector()));
  }
References __, v8::internal::compiler::turboshaft::V< T >::Cast(), and v8::internal::interpreter::Register::feedback_vector().
Referenced by v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorOrUndefinedIfJitless().
LoadFeedbackVectorLength()
template<typename Next >
V<WordPtr> v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorLength (V< FeedbackVector > feedback_vector) [inline]
Definition at line 212 of file turboshaft-builtins-assembler-inl.h.
                                                                         {
    V<Word32> length = __ LoadField(feedback_vector,
                                    AccessBuilderTS::ForFeedbackVectorLength());
    return ChangePositiveInt32ToIntPtr(length);
  }
References __, v8::internal::FeedbackCollectorReducer< Next >::ChangePositiveInt32ToIntPtr(), v8::internal::compiler::turboshaft::AccessBuilderTS::ForFeedbackVectorLength(), and v8::internal::length.
Referenced by v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorSlot(), and v8::internal::FeedbackCollectorReducer< Next >::StoreFeedbackVectorSlot().
LoadFeedbackVectorOrUndefinedIfJitless()
template<typename Next >
void v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorOrUndefinedIfJitless () [inline]
Definition at line 273 of file turboshaft-builtins-assembler-inl.h.
                                                {
#ifndef V8_JITLESS
    maybe_feedback_vector_ = LoadFeedbackVector();
#else
    maybe_feedback_vector_ = __ UndefinedConstant();
#endif
    feedback_ = __ SmiConstant(Smi::FromInt(0));
    feedback_on_exception_ = feedback_.Get();
  }
References __, v8::internal::FeedbackCollectorReducer< Next >::feedback_, v8::internal::FeedbackCollectorReducer< Next >::feedback_on_exception_, v8::internal::Smi::FromInt(), v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVector(), v8::internal::FeedbackCollectorReducer< Next >::maybe_feedback_vector_, and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
LoadFeedbackVectorSlot()
template<typename Next >
V<MaybeObject> v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorSlot (V< FeedbackVector > feedback_vector, V< WordPtr > slot, int additional_offset = 0) [inline]
Definition at line 218 of file turboshaft-builtins-assembler-inl.h.
                                                                   {
    __ CodeComment("LoadFeedbackVectorSlot");
    int32_t header_size =
        FeedbackVector::kRawFeedbackSlotsOffset + additional_offset;
    V<WordPtr> offset =
        __ ElementOffsetFromIndex(slot, HOLEY_ELEMENTS, header_size);
    TSA_SLOW_DCHECK(this, IsOffsetInBounds(
                              offset, LoadFeedbackVectorLength(feedback_vector),
                              FeedbackVector::kHeaderSize));
    return V<MaybeObject>::Cast(
        __ Load(feedback_vector, offset,
                compiler::turboshaft::LoadOp::Kind::TaggedBase(),
                MemoryRepresentation::AnyTagged()));
  }
References __, v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::HOLEY_ELEMENTS, v8::internal::FeedbackCollectorReducer< Next >::IsOffsetInBounds(), v8::Load(), v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorLength(), and v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase().
Referenced by v8::internal::FeedbackCollectorReducer< Next >::UpdateFeedback().
OverwriteFeedback()
template<typename Next >
void v8::internal::FeedbackCollectorReducer< Next >::OverwriteFeedback (int new_feedback) [inline]
Definition at line 189 of file turboshaft-builtins-assembler-inl.h.
                                           {
    __ CodeComment("OverwriteFeedback");
    feedback_ = __ SmiConstant(Smi::FromInt(new_feedback));
  }
References __, v8::internal::FeedbackCollectorReducer< Next >::feedback_, and v8::internal::Smi::FromInt().
SetFeedbackSlot()
template<typename Next >
void v8::internal::FeedbackCollectorReducer< Next >::SetFeedbackSlot (V< WordPtr > slot_id) [inline]
Definition at line 265 of file turboshaft-builtins-assembler-inl.h.
{ slot_id_ = slot_id; }
References v8::internal::FeedbackCollectorReducer< Next >::slot_id_.
SetFeedbackVector()
template<typename Next >
void v8::internal::FeedbackCollectorReducer< Next >::SetFeedbackVector (V< FeedbackVector > feedback_vector) [inline]
Definition at line 266 of file turboshaft-builtins-assembler-inl.h.
                                                            {
    TSA_DCHECK(this, IsFeedbackVector(feedback_vector));
    maybe_feedback_vector_ = feedback_vector;
    feedback_ = __ SmiConstant(Smi::FromInt(0));
    feedback_on_exception_ = feedback_.Get();
  }
References __, v8::internal::FeedbackCollectorReducer< Next >::feedback_, v8::internal::FeedbackCollectorReducer< Next >::feedback_on_exception_, v8::internal::Smi::FromInt(), v8::internal::FeedbackCollectorReducer< Next >::IsFeedbackVector(), and v8::internal::FeedbackCollectorReducer< Next >::maybe_feedback_vector_.
SmiBitwiseOr()
template<typename Next >
V<Smi> v8::internal::FeedbackCollectorReducer< Next >::SmiBitwiseOr (V< Smi > a, V< Smi > b) [inline]
Definition at line 328 of file turboshaft-builtins-assembler-inl.h.
                                          {
    return __ BitcastWord32ToSmi(
        __ Word32BitwiseOr(__ BitcastSmiToWord32(a), __ BitcastSmiToWord32(b)));
  }
References __.
Referenced by v8::internal::FeedbackCollectorReducer< Next >::CombineExceptionFeedback(), v8::internal::FeedbackCollectorReducer< Next >::CombineFeedback(), and v8::internal::FeedbackCollectorReducer< Next >::UpdateFeedback().
SmiEqual()
template<typename Next >
V<Word32> v8::internal::FeedbackCollectorReducer< Next >::SmiEqual (V< Smi > a, V< Smi > b) [inline]
Definition at line 333 of file turboshaft-builtins-assembler-inl.h.
                                         {
    return __ Word32Equal(__ BitcastSmiToWord32(a), __ BitcastSmiToWord32(b));
  }
References __, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by v8::internal::FeedbackCollectorReducer< Next >::FeedbackIs(), and v8::internal::FeedbackCollectorReducer< Next >::UpdateFeedback().
StoreFeedbackVectorSlot()
template<typename Next >
void v8::internal::FeedbackCollectorReducer< Next >::StoreFeedbackVectorSlot (V< FeedbackVector > feedback_vector, V< WordPtr > slot, V< Object > value, WriteBarrierMode barrier_mode = UPDATE_WRITE_BARRIER, int additional_offset = 0) [inline]
Definition at line 235 of file turboshaft-builtins-assembler-inl.h.
                                 {
    __ CodeComment("StoreFeedbackVectorSlot");
    DCHECK(IsAligned(additional_offset, kTaggedSize));
    int header_size =
        FeedbackVector::kRawFeedbackSlotsOffset + additional_offset;
    V<WordPtr> offset =
        __ ElementOffsetFromIndex(slot, HOLEY_ELEMENTS, header_size);
    TSA_DCHECK(this, IsOffsetInBounds(offset,
                                      LoadFeedbackVectorLength(feedback_vector),
                                      FeedbackVector::kHeaderSize));
    switch (barrier_mode) {
      case SKIP_WRITE_BARRIER: {
        __ Store(feedback_vector, offset, value,
                 compiler::turboshaft::StoreOp::Kind::TaggedBase(),
                 MemoryRepresentation::AnyTagged(),
                 compiler::WriteBarrierKind::kNoWriteBarrier);
        return;
      }
      case UNSAFE_SKIP_WRITE_BARRIER:
        UNIMPLEMENTED();
      case UPDATE_WRITE_BARRIER:
        UNIMPLEMENTED();
      case UPDATE_EPHEMERON_KEY_WRITE_BARRIER:
        UNREACHABLE();
    }
  }
References __, v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::DCHECK(), v8::internal::HOLEY_ELEMENTS, IsAligned(), v8::internal::FeedbackCollectorReducer< Next >::IsOffsetInBounds(), v8::internal::compiler::kNoWriteBarrier, v8::internal::kTaggedSize, v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorLength(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::wasm::liftoff::Store(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), v8::internal::UNIMPLEMENTED(), v8::internal::UNREACHABLE(), v8::internal::UNSAFE_SKIP_WRITE_BARRIER, v8::internal::UPDATE_EPHEMERON_KEY_WRITE_BARRIER, v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
Referenced by v8::internal::FeedbackCollectorReducer< Next >::UpdateFeedback().
UpdateFeedback()
template<typename Next >
void v8::internal::FeedbackCollectorReducer< Next >::UpdateFeedback () [inline]
Definition at line 291 of file turboshaft-builtins-assembler-inl.h.
                        {
    __ CodeComment("UpdateFeedback");
    if (mode_ == UpdateFeedbackMode::kNoFeedback) {
#ifdef V8_JITLESS
      TSA_DCHECK(this, __ IsUndefined(maybe_feedback_vector_));
      return;
#else
      UNREACHABLE();
#endif // !V8_JITLESS
    }
    Label<> done(this);
    if (mode_ == UpdateFeedbackMode::kOptionalFeedback) {
      GOTO_IF(__ IsUndefined(maybe_feedback_vector_), done);
    } else {
      DCHECK_EQ(mode_, UpdateFeedbackMode::kGuaranteedFeedback);
    }
    V<FeedbackVector> feedback_vector =
        V<FeedbackVector>::Cast(maybe_feedback_vector_);
    V<MaybeObject> feedback_element =
        LoadFeedbackVectorSlot(feedback_vector, slot_id_);
    V<Smi> previous_feedback = V<Smi>::Cast(feedback_element);
    V<Smi> combined_feedback = __ SmiBitwiseOr(previous_feedback, feedback_);
    IF_NOT (__ SmiEqual(previous_feedback, combined_feedback)) {
      StoreFeedbackVectorSlot(feedback_vector, slot_id_, combined_feedback,
                              SKIP_WRITE_BARRIER);
      // TODO(nicohartmann):
      // ReportFeedbackUpdate(maybe_feedback_vector_, slot_id_,
      // "UpdateFeedback");
    }
    GOTO(done);
    BIND(done);
  }
References __, v8::internal::compiler::turboshaft::V< T >::Cast(), DCHECK_EQ, v8::internal::FeedbackCollectorReducer< Next >::feedback_, v8::internal::kGuaranteedFeedback, v8::internal::kNoFeedback, v8::internal::kOptionalFeedback, v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorSlot(), v8::internal::FeedbackCollectorReducer< Next >::maybe_feedback_vector_, v8::internal::FeedbackCollectorReducer< Next >::mode_, v8::internal::SKIP_WRITE_BARRIER, v8::internal::FeedbackCollectorReducer< Next >::slot_id_, v8::internal::FeedbackCollectorReducer< Next >::SmiBitwiseOr(), v8::internal::FeedbackCollectorReducer< Next >::SmiEqual(), v8::internal::FeedbackCollectorReducer< Next >::StoreFeedbackVectorSlot(), and v8::internal::UNREACHABLE().
Member Data Documentation
feedback_
template<typename Next >
compiler::turboshaft::Var<Smi, assembler_t> v8::internal::FeedbackCollectorReducer< Next >::feedback_ {this} [private]
Definition at line 361 of file turboshaft-builtins-assembler-inl.h.
Referenced by v8::internal::FeedbackCollectorReducer< Next >::CombineExceptionFeedback(), v8::internal::FeedbackCollectorReducer< Next >::CombineFeedback(), v8::internal::FeedbackCollectorReducer< Next >::FeedbackIs(), v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorOrUndefinedIfJitless(), v8::internal::FeedbackCollectorReducer< Next >::OverwriteFeedback(), v8::internal::FeedbackCollectorReducer< Next >::SetFeedbackVector(), and v8::internal::FeedbackCollectorReducer< Next >::UpdateFeedback().
feedback_on_exception_
template<typename Next >
compiler::turboshaft::Var<Smi, assembler_t> v8::internal::FeedbackCollectorReducer< Next >::feedback_on_exception_ {this} [private]
Definition at line 362 of file turboshaft-builtins-assembler-inl.h.
Referenced by v8::internal::FeedbackCollectorReducer< Next >::CombineExceptionFeedback(), v8::internal::FeedbackCollectorReducer< Next >::CombineFeedbackOnException(), v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorOrUndefinedIfJitless(), and v8::internal::FeedbackCollectorReducer< Next >::SetFeedbackVector().
maybe_feedback_vector_
template<typename Next >
V<FeedbackVectorOrUndefined> v8::internal::FeedbackCollectorReducer< Next >::maybe_feedback_vector_ [private]
Definition at line 359 of file turboshaft-builtins-assembler-inl.h.
Referenced by v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorOrUndefinedIfJitless(), v8::internal::FeedbackCollectorReducer< Next >::SetFeedbackVector(), and v8::internal::FeedbackCollectorReducer< Next >::UpdateFeedback().
mode_
template<typename Next >
UpdateFeedbackMode v8::internal::FeedbackCollectorReducer< Next >::mode_ = DefaultUpdateFeedbackMode() [private]
Definition at line 363 of file turboshaft-builtins-assembler-inl.h.
Referenced by v8::internal::FeedbackCollectorReducer< Next >::UpdateFeedback().
slot_id_
template<typename Next >
V<WordPtr> v8::internal::FeedbackCollectorReducer< Next >::slot_id_ [private]
Definition at line 360 of file turboshaft-builtins-assembler-inl.h.
Referenced by v8::internal::FeedbackCollectorReducer< Next >::SetFeedbackSlot(), and v8::internal::FeedbackCollectorReducer< Next >::UpdateFeedback().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/turboshaft-builtins-assembler-inl.h