v8::internal::maglev::TrustedConstant Class Reference
#include <maglev-ir.h>
Public Types
using OutputRegister = Register
Public Member Functions
TrustedConstant (uint64_t bitfield, compiler::HeapObjectRef object, IndirectPointerTag tag)
bool ToBoolean (LocalIsolate *local_isolate) const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
compiler::HeapObjectRef object () const
IndirectPointerTag tag () const
void DoLoadToRegister (MaglevAssembler *, OutputRegister)
DirectHandle< Object > DoReify (LocalIsolate *isolate) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::TrustedPointer()
Private Types
using Base = FixedInputValueNodeT< 0, TrustedConstant >
Private Attributes
const compiler::HeapObjectRef object_
const IndirectPointerTag tag_
Additional Inherited Members
Detailed Description
Definition at line 5636 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::TrustedConstant::Base = FixedInputValueNodeT<0, TrustedConstant> [private]
Definition at line 5637 of file maglev-ir.h.
OutputRegister
using v8::internal::maglev::TrustedConstant::OutputRegister = Register
Definition at line 5640 of file maglev-ir.h.
Constructor & Destructor Documentation
TrustedConstant()
v8::internal::maglev::TrustedConstant::TrustedConstant (uint64_t bitfield, compiler::HeapObjectRef object, IndirectPointerTag tag) [inline], [explicit]
Definition at line 5642 of file maglev-ir.h.
      : Base(bitfield), object_(object), tag_(tag) {}
Member Function Documentation
DoLoadToRegister()
void v8::internal::maglev::TrustedConstant::DoLoadToRegister (MaglevAssembler * , OutputRegister)
DoReify()
DirectHandle< Object > v8::internal::maglev::TrustedConstant::DoReify (LocalIsolate * isolate) const
Definition at line 1236 of file maglev-ir.cc.
                                                                         {
  return object_.object();
}
References v8::internal::compiler::HeapObjectRef::object(), and object_.
GenerateCode()
void v8::internal::maglev::TrustedConstant::GenerateCode (MaglevAssembler * , const ProcessingState &)
object()
compiler::HeapObjectRef v8::internal::maglev::TrustedConstant::object () const [inline]
Definition at line 5654 of file maglev-ir.h.
{ return object_; }
References object_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::TrustedConstant::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7932 of file maglev-ir.cc.
                                                                             {
  os << "(" << *object_.object() << ")";
}
References v8::internal::compiler::HeapObjectRef::object(), and object_.
SetValueLocationConstraints()
void v8::internal::maglev::TrustedConstant::SetValueLocationConstraints ()
tag()
IndirectPointerTag v8::internal::maglev::TrustedConstant::tag () const [inline]
Definition at line 5655 of file maglev-ir.h.
{ return tag_; }
References tag_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInitializeStore().
ToBoolean()
bool v8::internal::maglev::TrustedConstant::ToBoolean (LocalIsolate * local_isolate) const [inline]
Definition at line 5648 of file maglev-ir.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
Member Data Documentation
kProperties
constexpr OpProperties v8::internal::maglev::TrustedConstant::kProperties = OpProperties::TrustedPointer() [static], [constexpr]
Definition at line 5646 of file maglev-ir.h.
object_
const compiler::HeapObjectRef v8::internal::maglev::TrustedConstant::object_ [private]
Definition at line 5661 of file maglev-ir.h.
Referenced by DoReify(), object(), and PrintParams().
tag_
const IndirectPointerTag v8::internal::maglev::TrustedConstant::tag_ [private]
Definition at line 5662 of file maglev-ir.h.
Referenced by tag().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc