v8::internal::StringSearch< PatternChar, SubjectChar > Class Template Reference
#include <string-search.h>
Public Member Functions
StringSearch (Isolate *isolate, base::Vector< const PatternChar > pattern)
int Search (base::Vector< const SubjectChar > subject, int index)
Static Public Member Functions
static int AlphabetSize ()
Private Types
using SearchFunction = int(*)(StringSearch< PatternChar, SubjectChar > *, base::Vector< const SubjectChar >, int)
Private Member Functions
void PopulateBoyerMooreHorspoolTable ()
void PopulateBoyerMooreTable ()
int * bad_char_table ()
int * good_suffix_shift_table ()
int * suffix_table ()
Static Private Member Functions
static int FailSearch (StringSearch< PatternChar, SubjectChar > *, base::Vector< const SubjectChar >, int)
static int SingleCharSearch (StringSearch< PatternChar, SubjectChar > *search, base::Vector< const SubjectChar > subject, int start_index)
static int LinearSearch (StringSearch< PatternChar, SubjectChar > *search, base::Vector< const SubjectChar > subject, int start_index)
static int InitialSearch (StringSearch< PatternChar, SubjectChar > *search, base::Vector< const SubjectChar > subject, int start_index)
static int BoyerMooreHorspoolSearch (StringSearch< PatternChar, SubjectChar > *search, base::Vector< const SubjectChar > subject, int start_index)
static int BoyerMooreSearch (StringSearch< PatternChar, SubjectChar > *search, base::Vector< const SubjectChar > subject, int start_index)
static bool exceedsOneByte (uint8_t c)
static bool exceedsOneByte (uint16_t c)
static int CharOccurrence (int *bad_char_occurrence, SubjectChar char_code)
Private Attributes
Isolate * isolate_
base::Vector< const PatternChar > pattern_
SearchFunction strategy_
int start_
Additional Inherited Members
Detailed Description
template<typename PatternChar, typename SubjectChar>
class v8::internal::StringSearch< PatternChar, SubjectChar >
Definition at line 57 of file string-search.h.
Member Typedef Documentation
SearchFunction
template<typename PatternChar , typename SubjectChar >
using v8::internal::StringSearch< PatternChar, SubjectChar >::SearchFunction = int (*)(StringSearch<PatternChar, SubjectChar>*, base::Vector<const SubjectChar>, int) [private]
Definition at line 97 of file string-search.h.
Constructor & Destructor Documentation
StringSearch()
template<typename PatternChar , typename SubjectChar >
v8::internal::StringSearch< PatternChar, SubjectChar >::StringSearch (Isolate * isolate, base::Vector< const PatternChar > pattern) [inline]
Definition at line 59 of file string-search.h.
      : isolate_(isolate),
        pattern_(pattern),
        start_(std::max(0, pattern.length() - kBMMaxShift)) {
    if (sizeof(PatternChar) > sizeof(SubjectChar)) {
      if (!IsOneByteString(pattern_)) {
        strategy_ = &FailSearch;
        return;
      }
    }
    int pattern_length = pattern_.length();
    if (pattern_length < kBMMinPatternLength) {
      if (pattern_length == 1) {
        strategy_ = &SingleCharSearch;
        return;
      }
      strategy_ = &LinearSearch;
      return;
    }
    strategy_ = &InitialSearch;
  }
References v8::internal::StringSearch< PatternChar, SubjectChar >::FailSearch(), v8::internal::StringSearch< PatternChar, SubjectChar >::InitialSearch(), v8::internal::StringSearchBase::IsOneByteString(), v8::internal::StringSearchBase::kBMMinPatternLength, v8::base::Vector< T >::length(), v8::internal::StringSearch< PatternChar, SubjectChar >::LinearSearch(), v8::internal::StringSearch< PatternChar, SubjectChar >::pattern_, v8::internal::StringSearch< PatternChar, SubjectChar >::SingleCharSearch(), and v8::internal::StringSearch< PatternChar, SubjectChar >::strategy_.
Member Function Documentation
AlphabetSize()
template<typename PatternChar , typename SubjectChar >
static int v8::internal::StringSearch< PatternChar, SubjectChar >::AlphabetSize () [inline], [static]
Definition at line 85 of file string-search.h.
                                   {
    if (sizeof(PatternChar) == 1) {
      // Latin1 needle.
      return kLatin1AlphabetSize;
    } else {
      DCHECK_EQ(sizeof(PatternChar), 2);
      // UC16 needle.
      return kUC16AlphabetSize;
    }
  }
References DCHECK_EQ, v8::internal::StringSearchBase::kLatin1AlphabetSize, and v8::internal::StringSearchBase::kUC16AlphabetSize.
bad_char_table()
template<typename PatternChar , typename SubjectChar >
int* v8::internal::StringSearch< PatternChar, SubjectChar >::bad_char_table () [inline], [private]
Definition at line 159 of file string-search.h.
{ return isolate_->bad_char_shift_table(); }
References v8::internal::StringSearch< PatternChar, SubjectChar >::isolate_.
BoyerMooreHorspoolSearch()
template<typename PatternChar , typename SubjectChar >
int v8::internal::StringSearch< PatternChar, SubjectChar >::BoyerMooreHorspoolSearch (StringSearch< PatternChar, SubjectChar > * search, base::Vector< const SubjectChar > subject, int start_index) [static], [private]
Definition at line 416 of file string-search.h.
                                                            {
  base::Vector<const PatternChar> pattern = search->pattern_;
  int subject_length = subject.length();
  int pattern_length = pattern.length();
  int* char_occurrences = search->bad_char_table();
  int badness = -pattern_length;
  // How bad we are doing without a good-suffix table.
  PatternChar last_char = pattern[pattern_length - 1];
  int last_char_shift =
      pattern_length - 1 -
      CharOccurrence(char_occurrences, static_cast<SubjectChar>(last_char));
  // Perform search
  int index = start_index; // No matches found prior to this index.
  while (index <= subject_length - pattern_length) {
    int j = pattern_length - 1;
    int subject_char;
    while (last_char != (subject_char = subject[index + j])) {
      int bc_occ = CharOccurrence(char_occurrences, subject_char);
      int shift = j - bc_occ;
      index += shift;
      badness += 1 - shift; // at most zero, so badness cannot increase.
      if (index > subject_length - pattern_length) {
        return -1;
      }
    }
    j--;
    while (j >= 0 && pattern[j] == (subject[index + j])) j--;
    if (j < 0) {
      return index;
    } else {
      index += last_char_shift;
      // Badness increases by the number of characters we have
      // checked, and decreases by the number of characters we
      // can skip by shifting. It's a measure of how we are doing
      // compared to reading each character exactly once.
      badness += (pattern_length - j) - last_char_shift;
      if (badness > 0) {
        search->PopulateBoyerMooreTable();
        search->strategy_ = &BoyerMooreSearch;
        return BoyerMooreSearch(search, subject, index);
      }
    }
  }
  return -1;
}
References v8::internal::index, v8::base::Vector< T >::length(), and v8::internal::anonymous_namespace{simd.cc}::search().
BoyerMooreSearch()
template<typename PatternChar , typename SubjectChar >
int v8::internal::StringSearch< PatternChar, SubjectChar >::BoyerMooreSearch (StringSearch< PatternChar, SubjectChar > * search, base::Vector< const SubjectChar > subject, int start_index) [static], [private]
Definition at line 297 of file string-search.h.
                                                            {
  base::Vector<const PatternChar> pattern = search->pattern_;
  int subject_length = subject.length();
  int pattern_length = pattern.length();
  // Only preprocess at most kBMMaxShift last characters of pattern.
  int start = search->start_;
  int* bad_char_occurence = search->bad_char_table();
  int* good_suffix_shift = search->good_suffix_shift_table();
  PatternChar last_char = pattern[pattern_length - 1];
  int index = start_index;
  // Continue search from i.
  while (index <= subject_length - pattern_length) {
    int j = pattern_length - 1;
    int c;
    while (last_char != (c = subject[index + j])) {
      int shift = j - CharOccurrence(bad_char_occurence, c);
      index += shift;
      if (index > subject_length - pattern_length) {
        return -1;
      }
    }
    while (j >= 0 && pattern[j] == (c = subject[index + j])) j--;
    if (j < 0) {
      return index;
    } else if (j < start) {
      // we have matched more than our tables allow us to be smart about.
      // Fall back on BMH shift.
      index += pattern_length - 1 -
               CharOccurrence(bad_char_occurence,
                              static_cast<SubjectChar>(last_char));
    } else {
      int gs_shift = good_suffix_shift[j + 1];
      int bc_occ = CharOccurrence(bad_char_occurence, c);
      int shift = j - bc_occ;
      if (gs_shift > shift) {
        shift = gs_shift;
      }
      index += shift;
    }
  }
  return -1;
}
References v8::internal::index, v8::base::Vector< T >::length(), and v8::internal::anonymous_namespace{simd.cc}::search().
CharOccurrence()
template<typename PatternChar , typename SubjectChar >
static int v8::internal::StringSearch< PatternChar, SubjectChar >::CharOccurrence (int * bad_char_occurrence, SubjectChar char_code) [inline], [static], [private]
Definition at line 135 of file string-search.h.
                                                          {
    if (sizeof(SubjectChar) == 1) {
      return bad_char_occurrence[static_cast<int>(char_code)];
    }
    if (sizeof(PatternChar) == 1) {
      if (exceedsOneByte(char_code)) {
        return -1;
      }
      return bad_char_occurrence[static_cast<unsigned int>(char_code)];
    }
    // Both pattern and subject are UC16. Reduce character to equivalence
    // class.
    int equiv_class = char_code % kUC16AlphabetSize;
    return bad_char_occurrence[equiv_class];
  }
References v8::internal::StringSearch< PatternChar, SubjectChar >::exceedsOneByte(), and v8::internal::StringSearchBase::kUC16AlphabetSize.
exceedsOneByte() [1/2]
template<typename PatternChar , typename SubjectChar >
static bool v8::internal::StringSearch< PatternChar, SubjectChar >::exceedsOneByte (uint16_t c) [inline], [static], [private]
Definition at line 131 of file string-search.h.
                                                {
    return c > String::kMaxOneByteCharCodeU;
  }
References v8::internal::String::kMaxOneByteCharCodeU.
exceedsOneByte() [2/2]
template<typename PatternChar , typename SubjectChar >
static bool v8::internal::StringSearch< PatternChar, SubjectChar >::exceedsOneByte (uint8_t c) [inline], [static], [private]
Definition at line 129 of file string-search.h.
{ return false; }
Referenced by v8::internal::StringSearch< PatternChar, SubjectChar >::CharOccurrence().
FailSearch()
template<typename PatternChar , typename SubjectChar >
static int v8::internal::StringSearch< PatternChar, SubjectChar >::FailSearch (StringSearch< PatternChar, SubjectChar > * , base::Vector< const SubjectChar > , int) [inline], [static], [private]
Definition at line 100 of file string-search.h.
                                                            {
    return -1;
  }
Referenced by v8::internal::StringSearch< PatternChar, SubjectChar >::StringSearch().
good_suffix_shift_table()
template<typename PatternChar , typename SubjectChar >
int* v8::internal::StringSearch< PatternChar, SubjectChar >::good_suffix_shift_table () [inline], [private]
Definition at line 162 of file string-search.h.
                                 {
    // Return biased pointer that maps the range [start_..pattern_.length()
    // to the kGoodSuffixShiftTable array.
    return isolate_->good_suffix_shift_table() - start_;
  }
References v8::internal::StringSearch< PatternChar, SubjectChar >::isolate_, and v8::internal::StringSearch< PatternChar, SubjectChar >::start_.
InitialSearch()
template<typename PatternChar , typename SubjectChar >
int v8::internal::StringSearch< PatternChar, SubjectChar >::InitialSearch (StringSearch< PatternChar, SubjectChar > * search, base::Vector< const SubjectChar > subject, int start_index) [static], [private]
Definition at line 498 of file string-search.h.
                                                      {
  base::Vector<const PatternChar> pattern = search->pattern_;
  int pattern_length = pattern.length();
  // Badness is a count of how much work we have done. When we have
  // done enough work we decide it's probably worth switching to a better
  // algorithm.
  int badness = -10 - (pattern_length << 2);
  // We know our pattern is at least 2 characters, we cache the first so
  // the common case of the first character not matching is faster.
  for (int i = index, n = subject.length() - pattern_length; i <= n; i++) {
    badness++;
    if (badness <= 0) {
      i = FindFirstCharacter(pattern, subject, i);
      if (i == -1) return -1;
      DCHECK_LE(i, n);
      int j = 1;
      do {
        if (pattern[j] != subject[i + j]) {
          break;
        }
        j++;
      } while (j < pattern_length);
      if (j == pattern_length) {
        return i;
      }
      badness += j;
    } else {
      search->PopulateBoyerMooreHorspoolTable();
      search->strategy_ = &BoyerMooreHorspoolSearch;
      return BoyerMooreHorspoolSearch(search, subject, i);
    }
  }
  return -1;
}
References DCHECK_LE, v8::internal::FindFirstCharacter(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::base::Vector< T >::length(), and v8::internal::anonymous_namespace{simd.cc}::search().
Referenced by v8::internal::StringSearch< PatternChar, SubjectChar >::StringSearch().
LinearSearch()
template<typename PatternChar , typename SubjectChar >
int v8::internal::StringSearch< PatternChar, SubjectChar >::LinearSearch (StringSearch< PatternChar, SubjectChar > * search, base::Vector< const SubjectChar > subject, int start_index) [static], [private]
Definition at line 269 of file string-search.h.
                                                      {
  base::Vector<const PatternChar> pattern = search->pattern_;
  DCHECK_GT(pattern.length(), 1);
  int pattern_length = pattern.length();
  int i = index;
  int n = subject.length() - pattern_length;
  while (i <= n) {
    i = FindFirstCharacter(pattern, subject, i);
    if (i == -1) return -1;
    DCHECK_LE(i, n);
    i++;
    // Loop extracted to separate function to allow using return to do
    // a deeper break.
    if (CharCompare(pattern.begin() + 1, subject.begin() + i,
                    pattern_length - 1)) {
      return i - 1;
    }
  }
  return -1;
}
References v8::base::Vector< T >::begin(), v8::internal::CharCompare(), DCHECK_GT, DCHECK_LE, v8::internal::FindFirstCharacter(), v8::internal::index, v8::base::Vector< T >::length(), and v8::internal::anonymous_namespace{simd.cc}::search().
Referenced by v8::internal::StringSearch< PatternChar, SubjectChar >::StringSearch().
PopulateBoyerMooreHorspoolTable()
template<typename PatternChar , typename SubjectChar >
void v8::internal::StringSearch< PatternChar, SubjectChar >::PopulateBoyerMooreHorspoolTable [private]
Definition at line 466 of file string-search.h.
                                                                             {
  int pattern_length = pattern_.length();
  int* bad_char_occurrence = bad_char_table();
  // Only preprocess at most kBMMaxShift last characters of pattern.
  int start = start_;
  // Run forwards to populate bad_char_table, so that *last* instance
  // of character equivalence class is the one registered.
  // Notice: Doesn't include the last character.
  int table_size = AlphabetSize();
  if (start == 0) { // All patterns less than kBMMaxShift in length.
    memset(bad_char_occurrence, -1, table_size * sizeof(*bad_char_occurrence));
  } else {
    for (int i = 0; i < table_size; i++) {
      bad_char_occurrence[i] = start - 1;
    }
  }
  for (int i = start; i < pattern_length - 1; i++) {
    PatternChar c = pattern_[i];
    int bucket = (sizeof(PatternChar) == 1) ? c : c % AlphabetSize();
    bad_char_occurrence[bucket] = i;
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
PopulateBoyerMooreTable()
template<typename PatternChar , typename SubjectChar >
void v8::internal::StringSearch< PatternChar, SubjectChar >::PopulateBoyerMooreTable [private]
Definition at line 346 of file string-search.h.
                                                                     {
  int pattern_length = pattern_.length();
  const PatternChar* pattern = pattern_.begin();
  // Only look at the last kBMMaxShift characters of pattern (from start_
  // to pattern_length).
  int start = start_;
  int length = pattern_length - start;
  // Biased tables so that we can use pattern indices as table indices,
  // even if we only cover the part of the pattern from offset start.
  int* shift_table = good_suffix_shift_table();
  int* suffix_table = this->suffix_table();
  // Initialize table.
  for (int i = start; i < pattern_length; i++) {
    shift_table[i] = length;
  }
  shift_table[pattern_length] = 1;
  suffix_table[pattern_length] = pattern_length + 1;
  if (pattern_length <= start) {
    return;
  }
  // Find suffixes.
  PatternChar last_char = pattern[pattern_length - 1];
  int suffix = pattern_length + 1;
  {
    int i = pattern_length;
    while (i > start) {
      PatternChar c = pattern[i - 1];
      while (suffix <= pattern_length && c != pattern[suffix - 1]) {
        if (shift_table[suffix] == length) {
          shift_table[suffix] = suffix - i;
        }
        suffix = suffix_table[suffix];
      }
      suffix_table[--i] = --suffix;
      if (suffix == pattern_length) {
        // No suffix to extend, so we check against last_char only.
        while ((i > start) && (pattern[i - 1] != last_char)) {
          if (shift_table[pattern_length] == length) {
            shift_table[pattern_length] = pattern_length - i;
          }
          suffix_table[--i] = pattern_length;
        }
        if (i > start) {
          suffix_table[--i] = --suffix;
        }
      }
    }
  }
  // Build shift table using suffixes.
  if (suffix < pattern_length) {
    for (int i = start; i <= pattern_length; i++) {
      if (shift_table[i] == length) {
        shift_table[i] = suffix - start;
      }
      if (i == suffix) {
        suffix = suffix_table[suffix];
      }
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::length.
Search()
template<typename PatternChar , typename SubjectChar >
int v8::internal::StringSearch< PatternChar, SubjectChar >::Search (base::Vector< const SubjectChar > subject, int index) [inline]
Definition at line 81 of file string-search.h.
                                                               {
    return strategy_(this, subject, index);
  }
References v8::internal::index, and v8::internal::StringSearch< PatternChar, SubjectChar >::strategy_.
SingleCharSearch()
template<typename PatternChar , typename SubjectChar >
int v8::internal::StringSearch< PatternChar, SubjectChar >::SingleCharSearch (StringSearch< PatternChar, SubjectChar > * search, base::Vector< const SubjectChar > subject, int start_index) [static], [private]
Definition at line 236 of file string-search.h.
                                                      {
  DCHECK_EQ(1, search->pattern_.length());
  PatternChar pattern_first_char = search->pattern_[0];
  if (sizeof(PatternChar) > sizeof(SubjectChar)) {
    if (exceedsOneByte(pattern_first_char)) {
      return -1;
    }
  }
  return FindFirstCharacter(search->pattern_, subject, index);
}
References DCHECK_EQ, v8::internal::FindFirstCharacter(), v8::internal::index, and v8::internal::anonymous_namespace{simd.cc}::search().
Referenced by v8::internal::StringSearch< PatternChar, SubjectChar >::StringSearch().
suffix_table()
template<typename PatternChar , typename SubjectChar >
int* v8::internal::StringSearch< PatternChar, SubjectChar >::suffix_table () [inline], [private]
Definition at line 170 of file string-search.h.
                      {
    // Return biased pointer that maps the range [start_..pattern_.length()
    // to the kSuffixTable array.
    return isolate_->suffix_table() - start_;
  }
References v8::internal::StringSearch< PatternChar, SubjectChar >::isolate_, and v8::internal::StringSearch< PatternChar, SubjectChar >::start_.
Member Data Documentation
isolate_
template<typename PatternChar , typename SubjectChar >
Isolate* v8::internal::StringSearch< PatternChar, SubjectChar >::isolate_ [private]
Definition at line 176 of file string-search.h.
Referenced by v8::internal::StringSearch< PatternChar, SubjectChar >::bad_char_table(), v8::internal::StringSearch< PatternChar, SubjectChar >::good_suffix_shift_table(), and v8::internal::StringSearch< PatternChar, SubjectChar >::suffix_table().
pattern_
template<typename PatternChar , typename SubjectChar >
base::Vector<const PatternChar> v8::internal::StringSearch< PatternChar, SubjectChar >::pattern_ [private]
Definition at line 178 of file string-search.h.
Referenced by v8::internal::StringSearch< PatternChar, SubjectChar >::StringSearch().
start_
template<typename PatternChar , typename SubjectChar >
int v8::internal::StringSearch< PatternChar, SubjectChar >::start_ [private]
Definition at line 182 of file string-search.h.
Referenced by v8::internal::StringSearch< PatternChar, SubjectChar >::good_suffix_shift_table(), and v8::internal::StringSearch< PatternChar, SubjectChar >::suffix_table().
strategy_
template<typename PatternChar , typename SubjectChar >
SearchFunction v8::internal::StringSearch< PatternChar, SubjectChar >::strategy_ [private]
Definition at line 180 of file string-search.h.
Referenced by v8::internal::StringSearch< PatternChar, SubjectChar >::Search(), and v8::internal::StringSearch< PatternChar, SubjectChar >::StringSearch().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/strings/string-search.h