v8::internal::JSTemporalZonedDateTime Class Reference
#include <js-temporal-objects.h>
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > Constructor (Isolate *isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > epoch_nanoseconds, DirectHandle< Object > time_zone_like, DirectHandle< Object > calendar_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > From (Isolate *isolate, DirectHandle< Object > item, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Smi > Compare (Isolate *isolate, DirectHandle< Object > one, DirectHandle< Object > two)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Oddball > Equals (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > other)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > With (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > temporal_zoned_date_time_like, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > WithPlainDate (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > plain_date_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > WithPlainTime (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > plain_time_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > WithTimeZone (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > time_zone_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > HoursInDay (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > Round (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > round_to)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Until (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > date_time, DirectHandle< Object > other, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Since (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > date_time, DirectHandle< Object > other, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > Add (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > Subtract (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainYearMonth > ToPlainYearMonth (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainMonthDay > ToPlainMonthDay (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > Now (Isolate *isolate, DirectHandle< Object > calendar_like, DirectHandle< Object > temporal_time_zone_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > NowISO (Isolate *isolate, DirectHandle< Object > temporal_time_zone_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > OffsetNanoseconds (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > Offset (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > StartOfDay (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalInstant > ToInstant (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDate > ToPlainDate (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainTime > ToPlainTime (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDateTime > ToPlainDateTime (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToJSON (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToLocaleString (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > locales, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToString (Isolate *isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > options)
Detailed Description
Definition at line 712 of file js-temporal-objects.h.
Member Function Documentation
Add()
MaybeDirectHandle< JSTemporalZonedDateTime > v8::internal::JSTemporalZonedDateTime::Add (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options) [static]
Definition at line 2992 of file js-temporal-objects.cc.
                                                                               {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
Compare()
MaybeDirectHandle< Smi > v8::internal::JSTemporalZonedDateTime::Compare (Isolate * isolate, DirectHandle< Object > one, DirectHandle< Object > two) [static]
Definition at line 2880 of file js-temporal-objects.cc.
                                  {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
Constructor()
MaybeDirectHandle< JSTemporalZonedDateTime > v8::internal::JSTemporalZonedDateTime::Constructor (Isolate * isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > epoch_nanoseconds, DirectHandle< Object > time_zone_like, DirectHandle< Object > calendar_like) [static]
Definition at line 2857 of file js-temporal-objects.cc.
                                                                             {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Referenced by v8::internal::TEMPORAL_GET_RUST().
Equals()
MaybeDirectHandle< Oddball > v8::internal::JSTemporalZonedDateTime::Equals (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > other) [static]
Definition at line 2888 of file js-temporal-objects.cc.
                                    {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
From()
MaybeDirectHandle< JSTemporalZonedDateTime > v8::internal::JSTemporalZonedDateTime::From (Isolate * isolate, DirectHandle< Object > item, DirectHandle< Object > options) [static]
Definition at line 2873 of file js-temporal-objects.cc.
                                      {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
HoursInDay()
MaybeDirectHandle< Object > v8::internal::JSTemporalZonedDateTime::HoursInDay (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time) [static]
Definition at line 2866 of file js-temporal-objects.cc.
                                                                             {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
Now()
MaybeDirectHandle< JSTemporalZonedDateTime > v8::internal::JSTemporalZonedDateTime::Now (Isolate * isolate, DirectHandle< Object > calendar_like, DirectHandle< Object > temporal_time_zone_like) [static]
Definition at line 2970 of file js-temporal-objects.cc.
                                                  {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
NowISO()
MaybeDirectHandle< JSTemporalZonedDateTime > v8::internal::JSTemporalZonedDateTime::NowISO (Isolate * isolate, DirectHandle< Object > temporal_time_zone_like) [static]
Definition at line 2977 of file js-temporal-objects.cc.
                                                                    {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
Offset()
MaybeDirectHandle< String > v8::internal::JSTemporalZonedDateTime::Offset (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time) [static]
Definition at line 3039 of file js-temporal-objects.cc.
                                                                             {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
OffsetNanoseconds()
MaybeDirectHandle< Object > v8::internal::JSTemporalZonedDateTime::OffsetNanoseconds (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time) [static]
Definition at line 3032 of file js-temporal-objects.cc.
                                                                             {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
Round()
MaybeDirectHandle< JSTemporalZonedDateTime > v8::internal::JSTemporalZonedDateTime::Round (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > round_to) [static]
Definition at line 2984 of file js-temporal-objects.cc.
                                       {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Since()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalZonedDateTime::Since (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > date_time, DirectHandle< Object > other, DirectHandle< Object > options) [static]
Definition at line 3017 of file js-temporal-objects.cc.
                                                              {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
StartOfDay()
MaybeDirectHandle< JSTemporalZonedDateTime > v8::internal::JSTemporalZonedDateTime::StartOfDay (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time) [static]
Definition at line 3046 of file js-temporal-objects.cc.
                                                                             {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
Subtract()
MaybeDirectHandle< JSTemporalZonedDateTime > v8::internal::JSTemporalZonedDateTime::Subtract (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options) [static]
Definition at line 2999 of file js-temporal-objects.cc.
                                                                               {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
ToInstant()
MaybeDirectHandle< JSTemporalInstant > v8::internal::JSTemporalZonedDateTime::ToInstant (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time) [static]
Definition at line 3053 of file js-temporal-objects.cc.
                                                                             {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
ToJSON()
MaybeDirectHandle< String > v8::internal::JSTemporalZonedDateTime::ToJSON (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time) [static]
Definition at line 2949 of file js-temporal-objects.cc.
                                                                             {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
ToLocaleString()
MaybeDirectHandle< String > v8::internal::JSTemporalZonedDateTime::ToLocaleString (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > locales, DirectHandle< Object > options) [static]
Definition at line 2956 of file js-temporal-objects.cc.
                                                                {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToPlainDate()
MaybeDirectHandle< JSTemporalPlainDate > v8::internal::JSTemporalZonedDateTime::ToPlainDate (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time) [static]
Definition at line 3061 of file js-temporal-objects.cc.
                                                                             {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToPlainDateTime()
MaybeDirectHandle< JSTemporalPlainDateTime > v8::internal::JSTemporalZonedDateTime::ToPlainDateTime (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time) [static]
Definition at line 3074 of file js-temporal-objects.cc.
                                                                             {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToPlainMonthDay()
MaybeDirectHandle< JSTemporalPlainMonthDay > v8::internal::JSTemporalZonedDateTime::ToPlainMonthDay (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time) [static]
Definition at line 2943 of file js-temporal-objects.cc.
                                                                             {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToPlainTime()
MaybeDirectHandle< JSTemporalPlainTime > v8::internal::JSTemporalZonedDateTime::ToPlainTime (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time) [static]
Definition at line 3067 of file js-temporal-objects.cc.
                                                                             {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToPlainYearMonth()
MaybeDirectHandle< JSTemporalPlainYearMonth > v8::internal::JSTemporalZonedDateTime::ToPlainYearMonth (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time) [static]
Definition at line 2936 of file js-temporal-objects.cc.
                                                                             {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToString()
MaybeDirectHandle< String > v8::internal::JSTemporalZonedDateTime::ToString (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > options) [static]
Definition at line 2963 of file js-temporal-objects.cc.
                                      {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Until()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalZonedDateTime::Until (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > date_time, DirectHandle< Object > other, DirectHandle< Object > options) [static]
Definition at line 3009 of file js-temporal-objects.cc.
                                                              {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
With()
MaybeDirectHandle< JSTemporalZonedDateTime > v8::internal::JSTemporalZonedDateTime::With (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > temporal_zoned_date_time_like, DirectHandle< Object > options) [static]
Definition at line 2897 of file js-temporal-objects.cc.
                                      {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
WithPlainDate()
MaybeDirectHandle< JSTemporalZonedDateTime > v8::internal::JSTemporalZonedDateTime::WithPlainDate (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > plain_date_like) [static]
Definition at line 2908 of file js-temporal-objects.cc.
                                          {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
WithPlainTime()
MaybeDirectHandle< JSTemporalZonedDateTime > v8::internal::JSTemporalZonedDateTime::WithPlainTime (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > plain_time_like) [static]
Definition at line 2917 of file js-temporal-objects.cc.
                                          {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
WithTimeZone()
MaybeDirectHandle< JSTemporalZonedDateTime > v8::internal::JSTemporalZonedDateTime::WithTimeZone (Isolate * isolate, DirectHandle< JSTemporalZonedDateTime > zoned_date_time, DirectHandle< Object > time_zone_like) [static]
Definition at line 2926 of file js-temporal-objects.cc.
                                         {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-temporal-objects.h
/mnt/V8SourceCode/src/objects/js-temporal-objects.cc