v8::internal::GlobalHandles::PendingPhantomCallback Class Reference
#include <global-handles.h>
Public Types
enum InvocationType { kFirstPass
, kSecondPass
 }
using Data = v8::WeakCallbackInfo< void >
Public Member Functions
PendingPhantomCallback (Data::Callback callback, void *parameter, void *embedder_fields[v8::kEmbedderFieldsInWeakCallback])
void Invoke (Isolate *isolate, InvocationType type)
Data::Callback callback () const
Private Attributes
Data::Callback callback_
void * parameter_
void * embedder_fields_ [v8::kEmbedderFieldsInWeakCallback]
Detailed Description
Definition at line 167 of file global-handles.h.
Member Typedef Documentation
Data
using v8::internal::GlobalHandles::PendingPhantomCallback::Data = v8::WeakCallbackInfo<void>
Definition at line 169 of file global-handles.h.
Member Enumeration Documentation
InvocationType
enum v8::internal::GlobalHandles::PendingPhantomCallback::InvocationType
Enumerator
kFirstPass
kSecondPass
Definition at line 171 of file global-handles.h.
{ kFirstPass, kSecondPass };
Constructor & Destructor Documentation
PendingPhantomCallback()
v8::internal::GlobalHandles::PendingPhantomCallback::PendingPhantomCallback (Data::Callback callback, void * parameter, void * embedder_fields[v8::kEmbedderFieldsInWeakCallback]) [inline]
Definition at line 173 of file global-handles.h.
      : callback_(callback), parameter_(parameter) {
    for (int i = 0; i < v8::kEmbedderFieldsInWeakCallback; ++i) {
      embedder_fields_[i] = embedder_fields[i];
    }
  }
References embedder_fields_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::kEmbedderFieldsInWeakCallback.
Member Function Documentation
callback()
Data::Callback v8::internal::GlobalHandles::PendingPhantomCallback::callback () const [inline]
Definition at line 184 of file global-handles.h.
{ return callback_; }
References callback_.
Referenced by Invoke().
Invoke()
void v8::internal::GlobalHandles::PendingPhantomCallback::Invoke (Isolate * isolate, InvocationType type)
Definition at line 856 of file global-handles.cc.
                                                                        {
  Data::Callback* callback_addr = nullptr;
  if (type == kFirstPass) {
    callback_addr = &callback_;
  }
  Data data(reinterpret_cast<v8::Isolate*>(isolate), parameter_,
            embedder_fields_, callback_addr);
  Data::Callback callback = callback_;
  callback_ = nullptr;
  callback(data);
}
References callback(), callback_, embedder_fields_, v8::internal::GlobalHandles::isolate(), kFirstPass, parameter_, and v8::internal::tracing::type.
Member Data Documentation
callback_
Data::Callback v8::internal::GlobalHandles::PendingPhantomCallback::callback_ [private]
Definition at line 187 of file global-handles.h.
Referenced by callback(), and Invoke().
embedder_fields_
void* v8::internal::GlobalHandles::PendingPhantomCallback::embedder_fields_[v8::kEmbedderFieldsInWeakCallback] [private]
Definition at line 189 of file global-handles.h.
Referenced by Invoke(), and PendingPhantomCallback().
parameter_
void* v8::internal::GlobalHandles::PendingPhantomCallback::parameter_ [private]
Definition at line 188 of file global-handles.h.
Referenced by Invoke().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/global-handles.h
/mnt/V8SourceCode/src/handles/global-handles.cc