v8::internal::WasmInterpreterObject Class Reference
#include <wasm-interpreter-objects.h>
Static Public Member Functions
static Tagged< WasmInstanceObject > get_wasm_instance (Tagged< Tuple2 > interpreter_object)
static void set_wasm_instance (Tagged< Tuple2 > interpreter_object, Tagged< WasmInstanceObject > wasm_instance)
static Tagged< Object > get_interpreter_handle (Tagged< Tuple2 > interpreter_object)
static void set_interpreter_handle (Tagged< Tuple2 > interpreter_object, Tagged< Object > interpreter_handle)
static DirectHandle< Tuple2 > New (DirectHandle< WasmInstanceObject >)
static bool RunInterpreter (Isolate *isolate, Address frame_pointer, DirectHandle< WasmInstanceObject > instance, int func_index, const std::vector< wasm::WasmValue > &argument_values, std::vector< wasm::WasmValue > &return_values)
static bool RunInterpreter (Isolate *isolate, Address frame_pointer, DirectHandle< WasmInstanceObject > instance, int func_index, uint8_t *interpreter_sp)
static std::vector< WasmInterpreterStackEntry > GetInterpretedStack (Tagged< Tuple2 > interpreter_object, Address frame_pointer)
static int GetFunctionIndex (Tagged< Tuple2 > interpreter_object, Address frame_pointer, int index)
Detailed Description
Definition at line 36 of file wasm-interpreter-objects.h.
Member Function Documentation
get_interpreter_handle()
Tagged< Object > v8::internal::WasmInterpreterObject::get_interpreter_handle (Tagged< Tuple2 > interpreter_object) [inline], [static]
Definition at line 39 of file wasm-interpreter-objects-inl.h.
                                       {
  return interpreter_object->value2();
}
Referenced by GetFunctionIndex(), v8::internal::wasm::InterpreterHandle::GetInstanceObject(), GetInterpretedStack(), v8::internal::wasm::GetInterpreterHandle(), and v8::internal::wasm::GetOrCreateInterpreterHandle().
get_wasm_instance()
Tagged< WasmInstanceObject > v8::internal::WasmInterpreterObject::get_wasm_instance (Tagged< Tuple2 > interpreter_object) [inline], [static]
Definition at line 27 of file wasm-interpreter-objects-inl.h.
                                       {
  return Cast<WasmInstanceObject>(interpreter_object->value1());
}
Referenced by v8::internal::wasm::InterpreterHandle::GetBytes().
GetFunctionIndex()
int v8::internal::WasmInterpreterObject::GetFunctionIndex (Tagged< Tuple2 > interpreter_object, Address frame_pointer, int index) [static]
Definition at line 87 of file wasm-interpreter-objects.cc.
                                                                              {
  Tagged<Object> handle_obj = get_interpreter_handle(interpreter_object);
  DCHECK(!IsUndefined(handle_obj));
  return Cast<Managed<wasm::InterpreterHandle>>(handle_obj)
      ->raw()
      ->GetFunctionIndex(frame_pointer, index);
}
References v8::internal::DCHECK(), get_interpreter_handle(), and v8::internal::index.
GetInterpretedStack()
std::vector< WasmInterpreterStackEntry > v8::internal::WasmInterpreterObject::GetInterpretedStack (Tagged< Tuple2 > interpreter_object, Address frame_pointer) [static]
Definition at line 77 of file wasm-interpreter-objects.cc.
                                                                  {
  Tagged<Object> handle_obj = get_interpreter_handle(interpreter_object);
  DCHECK(!IsUndefined(handle_obj));
  return Cast<Managed<wasm::InterpreterHandle>>(handle_obj)
      ->raw()
      ->GetInterpretedStack(frame_pointer);
}
References v8::internal::DCHECK(), and get_interpreter_handle().
New()
DirectHandle< Tuple2 > v8::internal::WasmInterpreterObject::New (DirectHandle< WasmInstanceObject > instance) [static]
Definition at line 17 of file wasm-interpreter-objects.cc.
                                               {
  DCHECK(v8_flags.wasm_jitless);
  Isolate* isolate = Isolate::Current();
  Factory* factory = isolate->factory();
  DirectHandle<WasmTrustedInstanceData> trusted_data(
      instance->trusted_data(isolate), isolate);
  DCHECK(!trusted_data->has_interpreter_object());
  DirectHandle<Tuple2> interpreter_object = factory->NewTuple2(
      instance, factory->undefined_value(), AllocationType::kOld);
  trusted_data->set_interpreter_object(*interpreter_object);
  return interpreter_object;
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::kOld, v8::internal::Factory::NewTuple2(), and v8::internal::v8_flags.
RunInterpreter() [1/2]
bool v8::internal::WasmInterpreterObject::RunInterpreter (Isolate * isolate, Address frame_pointer, DirectHandle< WasmInstanceObject > instance, int func_index, const std::vector< wasm::WasmValue > & argument_values, std::vector< wasm::WasmValue > & return_values) [static]
Definition at line 32 of file wasm-interpreter-objects.cc.
                                             {
  DCHECK_LE(0, func_index);
  wasm::WasmInterpreterThread* thread =
      wasm::WasmInterpreterThread::GetCurrentInterpreterThread(isolate);
  DCHECK_NOT_NULL(thread);
  // Assume an instance can run in only one thread.
  DirectHandle<Tuple2> interpreter_object =
      WasmTrustedInstanceData::GetInterpreterObject(instance);
  wasm::InterpreterHandle* handle =
      wasm::GetOrCreateInterpreterHandle(isolate, interpreter_object);
  return handle->Execute(thread, frame_pointer,
                         static_cast<uint32_t>(func_index), argument_values,
                         return_values);
}
References DCHECK_LE, DCHECK_NOT_NULL, v8::internal::wasm::WasmInterpreterThread::GetCurrentInterpreterThread(), v8::internal::wasm::GetOrCreateInterpreterHandle(), and v8::internal::handle().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallImportedFunction(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall(), and v8::internal::RUNTIME_FUNCTION().
RunInterpreter() [2/2]
bool v8::internal::WasmInterpreterObject::RunInterpreter (Isolate * isolate, Address frame_pointer, DirectHandle< WasmInstanceObject > instance, int func_index, uint8_t * interpreter_sp) [static]
Definition at line 55 of file wasm-interpreter-objects.cc.
                             {
  DCHECK_LE(0, func_index);
  wasm::WasmInterpreterThread* thread =
      wasm::WasmInterpreterThread::GetCurrentInterpreterThread(isolate);
  DCHECK_NOT_NULL(thread);
  // Assume an instance can run in only one thread.
  DirectHandle<Tuple2> interpreter_object =
      WasmTrustedInstanceData::GetInterpreterObject(instance);
  wasm::InterpreterHandle* handle =
      wasm::GetInterpreterHandle(isolate, interpreter_object);
  return handle->Execute(thread, frame_pointer,
                         static_cast<uint32_t>(func_index), interpreter_sp);
}
References DCHECK_LE, DCHECK_NOT_NULL, v8::internal::wasm::WasmInterpreterThread::GetCurrentInterpreterThread(), v8::internal::wasm::GetInterpreterHandle(), and v8::internal::handle().
set_interpreter_handle()
void v8::internal::WasmInterpreterObject::set_interpreter_handle (Tagged< Tuple2 > interpreter_object, Tagged< Object > interpreter_handle) [inline], [static]
Definition at line 45 of file wasm-interpreter-objects-inl.h.
                                                                          {
  DCHECK(IsForeign(interpreter_handle));
  return interpreter_object->set_value2(interpreter_handle);
}
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::GetOrCreateInterpreterHandle().
set_wasm_instance()
void v8::internal::WasmInterpreterObject::set_wasm_instance (Tagged< Tuple2 > interpreter_object, Tagged< WasmInstanceObject > wasm_instance) [inline], [static]
Definition at line 32 of file wasm-interpreter-objects-inl.h.
                                              {
  return interpreter_object->set_value1(wasm_instance);
}
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-objects.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-objects-inl.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-objects.cc