v8::internal::maglev::MapCompare Class Reference
#include <maglev-assembler.h>
Public Member Functions
MapCompare (MaglevAssembler *masm, Register object, size_t map_count)
void Generate (Handle< Map > map, Condition cond, Label *if_true, Label::Distance distance=Label::kFar)
Register GetObject () const
Register GetMap ()
Static Public Member Functions
static int TemporaryCount (size_t map_count)
Private Attributes
MaglevAssembler * masm_
const Register object_
const size_t map_count_
Register map_ = Register::no_reg()
Detailed Description
Definition at line 76 of file maglev-assembler.h.
Constructor & Destructor Documentation
MapCompare()
v8::internal::maglev::MapCompare::MapCompare (MaglevAssembler * masm, Register object, size_t map_count) [inline], [explicit]
Definition at line 96 of file maglev-assembler-arm-inl.h.
    : masm_(masm), object_(object), map_count_(map_count) {
  map_ = masm_->scratch_register_scope()->Acquire();
  masm_->LoadMap(map_, object_);
  USE(map_count_);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Acquire(), v8::internal::MacroAssembler::LoadMap(), map_, map_count_, masm_, object_, v8::internal::maglev::MaglevAssembler::scratch_register_scope(), and USE.
Member Function Documentation
Generate()
void v8::internal::maglev::MapCompare::Generate (Handle< Map > map, Condition cond, Label * if_true, Label::Distance distance = Label::kFar) [inline]
Definition at line 104 of file maglev-assembler-arm-inl.h.
                                                  {
  MaglevAssembler::TemporaryRegisterScope temps(masm_);
  Register temp = temps.AcquireScratch();
  masm_->Move(temp, map);
  masm_->cmp(map_, temp);
  masm_->JumpIf(cond, if_true, distance);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::cmp(), v8::internal::maglev::MaglevAssembler::JumpIf(), map_, masm_, and v8::internal::maglev::MaglevAssembler::Move().
GetMap()
Register v8::internal::maglev::MapCompare::GetMap () [inline]
Definition at line 113 of file maglev-assembler-arm-inl.h.
{ return map_; }
References map_.
GetObject()
Register v8::internal::maglev::MapCompare::GetObject () const [inline]
Definition at line 83 of file maglev-assembler.h.
{ return object_; }
References object_.
TemporaryCount()
int v8::internal::maglev::MapCompare::TemporaryCount (size_t map_count) [inline], [static]
Definition at line 115 of file maglev-assembler-arm-inl.h.
{ return 1; }
Member Data Documentation
map_
Register v8::internal::maglev::MapCompare::map_ = Register::no_reg() [private]
Definition at line 93 of file maglev-assembler.h.
Referenced by Generate(), GetMap(), and MapCompare().
map_count_
const size_t v8::internal::maglev::MapCompare::map_count_ [private]
Definition at line 92 of file maglev-assembler.h.
Referenced by MapCompare().
masm_
MaglevAssembler* v8::internal::maglev::MapCompare::masm_ [private]
Definition at line 90 of file maglev-assembler.h.
Referenced by Generate(), and MapCompare().
object_
const Register v8::internal::maglev::MapCompare::object_ [private]
Definition at line 91 of file maglev-assembler.h.
Referenced by GetObject(), and MapCompare().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-assembler.h
/mnt/V8SourceCode/src/maglev/arm/maglev-assembler-arm-inl.h
/mnt/V8SourceCode/src/maglev/arm64/maglev-assembler-arm64-inl.h
/mnt/V8SourceCode/src/maglev/riscv/maglev-assembler-riscv-inl.h
/mnt/V8SourceCode/src/maglev/s390/maglev-assembler-s390-inl.h
/mnt/V8SourceCode/src/maglev/x64/maglev-assembler-x64-inl.h