v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationTimeCallback Class Reference
Public Types
enum CompileMode { kSynchronous
, kAsync
, kStreaming
 }
Public Member Functions
CompilationTimeCallback (std::shared_ptr< Counters > async_counters, std::shared_ptr< metrics::Recorder > metrics_recorder, v8::metrics::Recorder::ContextId context_id, std::weak_ptr< NativeModule > native_module, CompileMode compile_mode)
void call (CompilationEvent compilation_event) override
Private Attributes
base::TimeTicks start_time_
const std::shared_ptr< Counters > async_counters_
std::shared_ptr< metrics::Recorder > metrics_recorder_
v8::metrics::Recorder::ContextId context_id_
std::weak_ptr< NativeModule > native_module_
const CompileMode compile_mode_
Detailed Description
Definition at line 2184 of file module-compiler.cc.
Member Enumeration Documentation
CompileMode
enum v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationTimeCallback::CompileMode
Enumerator
kSynchronous
kAsync
kStreaming
Definition at line 2186 of file module-compiler.cc.
{ kSynchronous, kAsync, kStreaming };
Constructor & Destructor Documentation
CompilationTimeCallback()
v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationTimeCallback::CompilationTimeCallback (std::shared_ptr< Counters > async_counters, std::shared_ptr< metrics::Recorder > metrics_recorder, v8::metrics::Recorder::ContextId context_id, std::weak_ptr< NativeModule > native_module, CompileMode compile_mode) [inline], [explicit]
Definition at line 2187 of file module-compiler.cc.
      : start_time_(base::TimeTicks::Now()),
        async_counters_(std::move(async_counters)),
        metrics_recorder_(std::move(metrics_recorder)),
        context_id_(context_id),
        native_module_(std::move(native_module)),
        compile_mode_(compile_mode) {}
Member Function Documentation
call()
void v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationTimeCallback::call (CompilationEvent compilation_event) [inline], [override], [virtual]
Implements v8::internal::wasm::CompilationEventCallback.
Definition at line 2199 of file module-compiler.cc.
                                                         {
    DCHECK(base::TimeTicks::IsHighResolution());
    std::shared_ptr<NativeModule> native_module = native_module_.lock();
    if (!native_module) return;
    auto now = base::TimeTicks::Now();
    auto duration = now - start_time_;
    if (compilation_event == CompilationEvent::kFinishedBaselineCompilation) {
      // Reset {start_time_} to measure tier-up time.
      start_time_ = now;
      if (compile_mode_ != kSynchronous) {
        TimedHistogram* histogram =
            compile_mode_ == kAsync
                ? async_counters_->wasm_async_compile_wasm_module_time()
                : async_counters_->wasm_streaming_compile_wasm_module_time();
        histogram->AddSample(static_cast<int>(duration.InMicroseconds()));
      }
      v8::metrics::WasmModuleCompiled event{
          (compile_mode_ != kSynchronous), // async
          (compile_mode_ == kStreaming), // streamed
          false, // cached
          false, // deserialized
          v8_flags.wasm_lazy_compilation, // lazy
          true, // success
          native_module->liftoff_code_size(), // code_size_in_bytes
          native_module->liftoff_bailout_count(), // liftoff_bailout_count
          duration.InMicroseconds()}; // wall_clock_duration_in_us
      metrics_recorder_->DelayMainThreadEvent(event, context_id_);
    }
    if (compilation_event == CompilationEvent::kFailedCompilation) {
      v8::metrics::WasmModuleCompiled event{
          (compile_mode_ != kSynchronous), // async
          (compile_mode_ == kStreaming), // streamed
          false, // cached
          false, // deserialized
          v8_flags.wasm_lazy_compilation, // lazy
          false, // success
          native_module->liftoff_code_size(), // code_size_in_bytes
          native_module->liftoff_bailout_count(), // liftoff_bailout_count
          duration.InMicroseconds()}; // wall_clock_duration_in_us
      metrics_recorder_->DelayMainThreadEvent(event, context_id_);
    }
  }
References v8::internal::Histogram::AddSample(), v8::internal::DCHECK(), v8::internal::duration, v8::base::TimeTicks::IsHighResolution(), v8::internal::kAsync, v8::internal::wasm::kFailedCompilation, v8::internal::wasm::kFinishedBaselineCompilation, v8::internal::kSynchronous, v8::base::TimeTicks::Now(), and v8::internal::v8_flags.
Member Data Documentation
async_counters_
const std::shared_ptr<Counters> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationTimeCallback::async_counters_ [private]
Definition at line 2245 of file module-compiler.cc.
compile_mode_
const CompileMode v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationTimeCallback::compile_mode_ [private]
Definition at line 2249 of file module-compiler.cc.
context_id_
v8::metrics::Recorder::ContextId v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationTimeCallback::context_id_ [private]
Definition at line 2247 of file module-compiler.cc.
metrics_recorder_
std::shared_ptr<metrics::Recorder> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationTimeCallback::metrics_recorder_ [private]
Definition at line 2246 of file module-compiler.cc.
native_module_
std::weak_ptr<NativeModule> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationTimeCallback::native_module_ [private]
Definition at line 2248 of file module-compiler.cc.
start_time_
base::TimeTicks v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationTimeCallback::start_time_ [private]
Definition at line 2244 of file module-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc