v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch Class Reference
Public Member Functions
MatchInfoBackedMatch (Isolate *isolate, DirectHandle< JSRegExp > regexp, DirectHandle< RegExpData > regexp_data, DirectHandle< String > subject, DirectHandle< RegExpMatchInfo > match_info)
DirectHandle< String > GetMatch () override
DirectHandle< String > GetPrefix () override
DirectHandle< String > GetSuffix () override
bool HasNamedCaptures () override
int CaptureCount () override
MaybeDirectHandle< String > GetCapture (int i, bool *capture_exists) override
MaybeDirectHandle< String > GetNamedCapture (DirectHandle< String > name, CaptureState *state) override
Private Attributes
Isolate * isolate_
DirectHandle< String > subject_
DirectHandle< RegExpMatchInfo > match_info_
bool has_named_captures_
DirectHandle< FixedArray > capture_name_map_
Additional Inherited Members
Detailed Description
Definition at line 1037 of file runtime-regexp.cc.
Constructor & Destructor Documentation
MatchInfoBackedMatch()
v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::MatchInfoBackedMatch (Isolate * isolate, DirectHandle< JSRegExp > regexp, DirectHandle< RegExpData > regexp_data, DirectHandle< String > subject, DirectHandle< RegExpMatchInfo > match_info) [inline]
Definition at line 1039 of file runtime-regexp.cc.
      : isolate_(isolate), match_info_(match_info) {
    subject_ = String::Flatten(isolate, subject);
    if (RegExpData::TypeSupportsCaptures(regexp_data->type_tag())) {
      DCHECK(Is<IrRegExpData>(*regexp_data));
      Tagged<Object> o = Cast<IrRegExpData>(regexp_data)->capture_name_map();
      has_named_captures_ = IsFixedArray(o);
      if (has_named_captures_) {
        capture_name_map_ = direct_handle(Cast<FixedArray>(o), isolate);
      }
    } else {
      has_named_captures_ = false;
    }
  }
References v8::internal::DCHECK(), v8::internal::direct_handle(), and v8::internal::RegExpData::TypeSupportsCaptures().
Member Function Documentation
CaptureCount()
int v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::CaptureCount () [inline], [override], [virtual]
Implements v8::internal::String::Match.
Definition at line 1075 of file runtime-regexp.cc.
                              {
    return match_info_->number_of_capture_registers() / 2;
  }
GetCapture()
MaybeDirectHandle<String> v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::GetCapture (int i, bool * capture_exists) [inline], [override], [virtual]
Implements v8::internal::String::Match.
Definition at line 1079 of file runtime-regexp.cc.
                                                                             {
    DirectHandle<Object> capture_obj = RegExpUtils::GenericCaptureGetter(
        isolate_, match_info_, i, capture_exists);
    return (*capture_exists) ? Object::ToString(isolate_, capture_obj)
                             : isolate_->factory()->empty_string();
  }
References v8::internal::RegExpUtils::GenericCaptureGetter(), and v8::Value::ToString().
GetMatch()
DirectHandle<String> v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::GetMatch () [inline], [override], [virtual]
Implements v8::internal::String::Match.
Definition at line 1058 of file runtime-regexp.cc.
                                           {
    return RegExpUtils::GenericCaptureGetter(isolate_, match_info_, 0, nullptr);
  }
References v8::internal::RegExpUtils::GenericCaptureGetter().
GetNamedCapture()
MaybeDirectHandle<String> v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::GetNamedCapture (DirectHandle< String > name, CaptureState * state) [inline], [override], [virtual]
Implements v8::internal::String::Match.
Definition at line 1086 of file runtime-regexp.cc.
                                                                          {
    DCHECK(has_named_captures_);
    int capture_index = 0;
    int capture_name_map_index = 0;
    while (true) {
      capture_index = LookupNamedCapture(
          [=](Tagged<String> capture_name) {
            return capture_name->Equals(*name);
          },
          *capture_name_map_, &capture_name_map_index);
      if (capture_index == -1) {
        *state = UNMATCHED;
        return isolate_->factory()->empty_string();
      }
      if (RegExpUtils::IsMatchedCapture(*match_info_, capture_index)) {
        DirectHandle<String> capture_value;
        ASSIGN_RETURN_ON_EXCEPTION(
            isolate_, capture_value,
            Object::ToString(isolate_,
                             RegExpUtils::GenericCaptureGetter(
                                 isolate_, match_info_, capture_index)));
        *state = MATCHED;
        return capture_value;
      }
    }
  }
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DCHECK(), v8::internal::RegExpUtils::GenericCaptureGetter(), v8::internal::RegExpUtils::IsMatchedCapture(), v8::internal::anonymous_namespace{runtime-regexp.cc}::LookupNamedCapture(), v8::internal::name, and v8::Value::ToString().
GetPrefix()
DirectHandle<String> v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::GetPrefix () [inline], [override], [virtual]
Implements v8::internal::String::Match.
Definition at line 1062 of file runtime-regexp.cc.
                                            {
    const int match_start = match_info_->capture(0);
    return isolate_->factory()->NewSubString(subject_, 0, match_start);
  }
GetSuffix()
DirectHandle<String> v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::GetSuffix () [inline], [override], [virtual]
Implements v8::internal::String::Match.
Definition at line 1067 of file runtime-regexp.cc.
                                            {
    const int match_end = match_info_->capture(1);
    return isolate_->factory()->NewSubString(subject_, match_end,
                                             subject_->length());
  }
HasNamedCaptures()
bool v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::HasNamedCaptures () [inline], [override], [virtual]
Implements v8::internal::String::Match.
Definition at line 1073 of file runtime-regexp.cc.
{ return has_named_captures_; }
Member Data Documentation
capture_name_map_
DirectHandle<FixedArray> v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::capture_name_map_ [private]
Definition at line 1120 of file runtime-regexp.cc.
has_named_captures_
bool v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::has_named_captures_ [private]
Definition at line 1119 of file runtime-regexp.cc.
isolate_
Isolate* v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::isolate_ [private]
Definition at line 1115 of file runtime-regexp.cc.
match_info_
DirectHandle<RegExpMatchInfo> v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::match_info_ [private]
Definition at line 1117 of file runtime-regexp.cc.
subject_
DirectHandle<String> v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::subject_ [private]
Definition at line 1116 of file runtime-regexp.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/runtime/runtime-regexp.cc