v8::internal::compiler::HeapObjectType Class Reference
#include <heap-refs.h>
Public Types
enum Flag : uint8_t { kUndetectable = 1 << 0
, kCallable = 1 << 1
 }
using Flags = base::Flags< Flag >
Public Member Functions
HeapObjectType (InstanceType instance_type, ElementsKind elements_kind, Flags flags, OddballType oddball_type, HoleType hole_type)
OddballType oddball_type () const
HoleType hole_type () const
OddballType oddball_type (JSHeapBroker *broker) const
HoleType hole_type (JSHeapBroker *broker) const
InstanceType instance_type () const
Flags flags () const
ElementsKind elements_kind () const
bool is_callable () const
bool is_undetectable () const
Private Attributes
InstanceType const instance_type_
ElementsKind const elements_kind_
OddballType const oddball_type_
HoleType const hole_type_
Flags const flags_
Detailed Description
Definition at line 483 of file heap-refs.h.
Member Typedef Documentation
Flags
using v8::internal::compiler::HeapObjectType::Flags = base::Flags<Flag>
Definition at line 487 of file heap-refs.h.
Member Enumeration Documentation
Flag
enum v8::internal::compiler::HeapObjectType::Flag : uint8_t
Enumerator
kUndetectable
kCallable
Definition at line 485 of file heap-refs.h.
: uint8_t { kUndetectable = 1 << 0, kCallable = 1 << 1 };
Constructor & Destructor Documentation
HeapObjectType()
v8::internal::compiler::HeapObjectType::HeapObjectType (InstanceType instance_type, ElementsKind elements_kind, Flags flags, OddballType oddball_type, HoleType hole_type) [inline]
Definition at line 489 of file heap-refs.h.
      : instance_type_(instance_type),
        elements_kind_(elements_kind),
        oddball_type_(oddball_type),
        hole_type_(hole_type),
        flags_(flags) {
    DCHECK_EQ(instance_type == ODDBALL_TYPE,
              oddball_type != OddballType::kNone);
  }
References DCHECK_EQ, instance_type(), v8::internal::compiler::kNone, and oddball_type().
Member Function Documentation
elements_kind()
ElementsKind v8::internal::compiler::HeapObjectType::elements_kind () const [inline]
Definition at line 507 of file heap-refs.h.
{ return elements_kind_; }
References elements_kind_.
flags()
Flags v8::internal::compiler::HeapObjectType::flags () const [inline]
Definition at line 506 of file heap-refs.h.
{ return flags_; }
References flags_.
hole_type() [1/2]
HoleType v8::internal::compiler::HeapObjectType::hole_type () const [inline]
Definition at line 501 of file heap-refs.h.
{ return hole_type_; }
References hole_type_.
hole_type() [2/2]
HoleType v8::internal::compiler::HeapObjectType::hole_type (JSHeapBroker * broker) const [inline]
Definition at line 504 of file heap-refs.h.
{ return hole_type_; }
References hole_type_.
instance_type()
InstanceType v8::internal::compiler::HeapObjectType::instance_type () const [inline]
Definition at line 505 of file heap-refs.h.
{ return instance_type_; }
References instance_type_.
Referenced by HeapObjectType().
is_callable()
bool v8::internal::compiler::HeapObjectType::is_callable () const [inline]
Definition at line 509 of file heap-refs.h.
{ return flags_ & kCallable; }
References flags_, and kCallable.
is_undetectable()
bool v8::internal::compiler::HeapObjectType::is_undetectable () const [inline]
Definition at line 510 of file heap-refs.h.
{ return flags_ & kUndetectable; }
References flags_, and kUndetectable.
oddball_type() [1/2]
OddballType v8::internal::compiler::HeapObjectType::oddball_type () const [inline]
Definition at line 500 of file heap-refs.h.
{ return oddball_type_; }
References oddball_type_.
Referenced by HeapObjectType().
oddball_type() [2/2]
OddballType v8::internal::compiler::HeapObjectType::oddball_type (JSHeapBroker * broker) const [inline]
Definition at line 503 of file heap-refs.h.
{ return oddball_type_; }
References oddball_type_.
Member Data Documentation
elements_kind_
ElementsKind const v8::internal::compiler::HeapObjectType::elements_kind_ [private]
Definition at line 514 of file heap-refs.h.
Referenced by elements_kind().
flags_
Flags const v8::internal::compiler::HeapObjectType::flags_ [private]
Definition at line 517 of file heap-refs.h.
Referenced by flags(), is_callable(), and is_undetectable().
hole_type_
HoleType const v8::internal::compiler::HeapObjectType::hole_type_ [private]
Definition at line 516 of file heap-refs.h.
Referenced by hole_type().
instance_type_
InstanceType const v8::internal::compiler::HeapObjectType::instance_type_ [private]
Definition at line 513 of file heap-refs.h.
Referenced by instance_type().
oddball_type_
OddballType const v8::internal::compiler::HeapObjectType::oddball_type_ [private]
Definition at line 515 of file heap-refs.h.
Referenced by oddball_type().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/heap-refs.h