v8::internal::compiler::turboshaft::AnalyzerIterator Class Reference
#include <analyzer-iterator.h>
Classes
struct StackNode
Public Member Functions
AnalyzerIterator (Zone *phase_zone, const Graph &graph, const LoopFinder &loop_finder)
bool HasNext () const
const Block * Next ()
void MarkLoopForRevisit ()
void MarkLoopForRevisitSkipHeader ()
Private Member Functions
void PopOutdated ()
bool IsOutdated (StackNode node) const
Private Attributes
const Graph & graph_
const LoopFinder & loop_finder_
uint64_t current_generation_ = kGenerationForFirstVisit
StackNode curr_ = {nullptr, 0}
FixedBlockSidetable< uint64_t > visited_
ZoneVector< StackNode > stack_
Static Private Attributes
static constexpr uint64_t kNotVisitedGeneration = 0
static constexpr uint64_t kGenerationForFirstVisit = 1
Detailed Description
Definition at line 76 of file analyzer-iterator.h.
Constructor & Destructor Documentation
AnalyzerIterator()
v8::internal::compiler::turboshaft::AnalyzerIterator::AnalyzerIterator (Zone * phase_zone, const Graph & graph, const LoopFinder & loop_finder) [inline]
Definition at line 78 of file analyzer-iterator.h.
      : graph_(graph),
        loop_finder_(loop_finder),
        visited_(graph.block_count(), kNotVisitedGeneration, phase_zone),
        stack_(phase_zone) {
    stack_.push_back({&graph.StartBlock(), kGenerationForFirstVisit});
  }
References graph().
Member Function Documentation
HasNext()
bool v8::internal::compiler::turboshaft::AnalyzerIterator::HasNext () const [inline]
Definition at line 87 of file analyzer-iterator.h.
                       {
    DCHECK_IMPLIES(!stack_.empty(), !IsOutdated(stack_.back()));
    return !stack_.empty();
  }
References DCHECK_IMPLIES.
Referenced by Next().
IsOutdated()
bool v8::internal::compiler::turboshaft::AnalyzerIterator::IsOutdated (StackNode node) const [inline], [private]
Definition at line 108 of file analyzer-iterator.h.
                                        {
    return visited_[node.block->index()] >= node.generation;
  }
References v8::internal::compiler::turboshaft::AnalyzerIterator::StackNode::block, v8::internal::compiler::turboshaft::AnalyzerIterator::StackNode::generation, and v8::internal::compiler::turboshaft::Block::index().
Referenced by Next(), and PopOutdated().
MarkLoopForRevisit()
void v8::internal::compiler::turboshaft::AnalyzerIterator::MarkLoopForRevisit ()
Definition at line 60 of file analyzer-iterator.cc.
                                          {
  DCHECK_NOT_NULL(curr_.block);
  DCHECK_NE(curr_.generation, kNotVisitedGeneration);
  DCHECK(curr_.block->HasBackedge(graph_));
  const Block* header =
      curr_.block->LastOperation(graph_).Cast<GotoOp>().destination;
  stack_.push_back({header, ++current_generation_});
}
References v8::internal::compiler::turboshaft::AnalyzerIterator::StackNode::block, v8::internal::compiler::turboshaft::Operation::Cast(), curr_, current_generation_, v8::internal::DCHECK(), DCHECK_NE, DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::AnalyzerIterator::StackNode::generation, graph_, v8::internal::compiler::turboshaft::Block::HasBackedge(), kNotVisitedGeneration, v8::internal::compiler::turboshaft::Block::LastOperation(), and stack_.
MarkLoopForRevisitSkipHeader()
void v8::internal::compiler::turboshaft::AnalyzerIterator::MarkLoopForRevisitSkipHeader ()
Definition at line 69 of file analyzer-iterator.cc.
                                                    {
  DCHECK_NOT_NULL(curr_.block);
  DCHECK_NE(curr_.generation, kNotVisitedGeneration);
  DCHECK(curr_.block->HasBackedge(graph_));
  const Block* header =
      curr_.block->LastOperation(graph_).Cast<GotoOp>().destination;
  for (const Block* child = header->LastChild(); child != nullptr;
       child = child->NeighboringChild()) {
    stack_.push_back({child, ++current_generation_});
  }
}
References v8::internal::compiler::turboshaft::AnalyzerIterator::StackNode::block, v8::internal::compiler::turboshaft::Operation::Cast(), curr_, current_generation_, v8::internal::DCHECK(), DCHECK_NE, DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::AnalyzerIterator::StackNode::generation, graph_, v8::internal::compiler::turboshaft::Block::HasBackedge(), kNotVisitedGeneration, v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::LastChild(), v8::internal::compiler::turboshaft::Block::LastOperation(), and stack_.
Next()
const Block * v8::internal::compiler::turboshaft::AnalyzerIterator::Next ()
Definition at line 19 of file analyzer-iterator.cc.
                                    {
  DCHECK(HasNext());
  DCHECK(!IsOutdated(stack_.back()));
  curr_ = stack_.back();
  stack_.pop_back();
  const Block* curr_header = curr_.block->IsLoop()
                                 ? curr_.block
                                 : loop_finder_.GetLoopHeader(curr_.block);
  // Pushing on the stack the children that are not in the same loop as Next
  // (remember that since we're doing a DFS with a Last-In-First-Out stack,
  // pushing them first on the stack means that they will be visited last).
  for (const Block* child = curr_.block->LastChild(); child != nullptr;
       child = child->NeighboringChild()) {
    if (loop_finder_.GetLoopHeader(child) != curr_header) {
      stack_.push_back({child, current_generation_});
    }
  }
  // Pushing on the stack the children that are in the same loop as Next (they
  // are pushed last, so that they will be visited first).
  for (const Block* child = curr_.block->LastChild(); child != nullptr;
       child = child->NeighboringChild()) {
    if (loop_finder_.GetLoopHeader(child) == curr_header) {
      stack_.push_back({child, current_generation_});
    }
  }
  visited_[curr_.block->index()] = current_generation_;
  // Note that PopOutdated must be called after updating {visited_}, because
  // this way, if the stack contained initially [{Bx, 1}, {Bx, 2}] (where `Bx`
  // is the same block both time and it hasn't been visited before), then we
  // popped the second entry at the begining of this function, but if we call
  // PopOutdate before updating {visited_}, then it won't pop the first entry.
  PopOutdated();
  return curr_.block;
}
References v8::internal::compiler::turboshaft::AnalyzerIterator::StackNode::block, curr_, current_generation_, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::LoopFinder::GetLoopHeader(), HasNext(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Block::IsLoop(), IsOutdated(), v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::LastChild(), loop_finder_, PopOutdated(), stack_, and visited_.
PopOutdated()
void v8::internal::compiler::turboshaft::AnalyzerIterator::PopOutdated () [private]
Definition at line 9 of file analyzer-iterator.cc.
                                   {
  while (!stack_.empty()) {
    if (IsOutdated(stack_.back())) {
      stack_.pop_back();
    } else {
      return;
    }
  }
}
References IsOutdated(), and stack_.
Referenced by Next().
Member Data Documentation
curr_
StackNode v8::internal::compiler::turboshaft::AnalyzerIterator::curr_ = {nullptr, 0} [private]
Definition at line 118 of file analyzer-iterator.h.
Referenced by MarkLoopForRevisit(), MarkLoopForRevisitSkipHeader(), and Next().
current_generation_
uint64_t v8::internal::compiler::turboshaft::AnalyzerIterator::current_generation_ = kGenerationForFirstVisit [private]
Definition at line 115 of file analyzer-iterator.h.
Referenced by MarkLoopForRevisit(), MarkLoopForRevisitSkipHeader(), and Next().
graph_
const Graph& v8::internal::compiler::turboshaft::AnalyzerIterator::graph_ [private]
Definition at line 112 of file analyzer-iterator.h.
Referenced by MarkLoopForRevisit(), and MarkLoopForRevisitSkipHeader().
kGenerationForFirstVisit
constexpr uint64_t v8::internal::compiler::turboshaft::AnalyzerIterator::kGenerationForFirstVisit = 1 [static], [constexpr], [private]
Definition at line 105 of file analyzer-iterator.h.
kNotVisitedGeneration
constexpr uint64_t v8::internal::compiler::turboshaft::AnalyzerIterator::kNotVisitedGeneration = 0 [static], [constexpr], [private]
Definition at line 104 of file analyzer-iterator.h.
Referenced by MarkLoopForRevisit(), and MarkLoopForRevisitSkipHeader().
loop_finder_
const LoopFinder& v8::internal::compiler::turboshaft::AnalyzerIterator::loop_finder_ [private]
Definition at line 113 of file analyzer-iterator.h.
Referenced by Next().
stack_
ZoneVector<StackNode> v8::internal::compiler::turboshaft::AnalyzerIterator::stack_ [private]
Definition at line 129 of file analyzer-iterator.h.
Referenced by MarkLoopForRevisit(), MarkLoopForRevisitSkipHeader(), Next(), and PopOutdated().
visited_
FixedBlockSidetable<uint64_t> v8::internal::compiler::turboshaft::AnalyzerIterator::visited_ [private]
Definition at line 123 of file analyzer-iterator.h.
Referenced by Next().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/analyzer-iterator.h
/mnt/V8SourceCode/src/compiler/turboshaft/analyzer-iterator.cc