v8::internal::compiler::AllocatedOperand Class Reference
#include <instruction.h>
Public Member Functions
AllocatedOperand (LocationKind kind, MachineRepresentation rep, int index)
Static Public Member Functions
static AllocatedOperand * New (Zone *zone, LocationKind kind, MachineRepresentation rep, int index)
Additional Inherited Members
Detailed Description
Definition at line 620 of file instruction.h.
Constructor & Destructor Documentation
AllocatedOperand()
v8::internal::compiler::AllocatedOperand::AllocatedOperand (LocationKind kind, MachineRepresentation rep, int index) [inline]
Definition at line 622 of file instruction.h.
      : LocationOperand(ALLOCATED, kind, rep, index) {}
Member Function Documentation
New()
static AllocatedOperand* v8::internal::compiler::AllocatedOperand::New (Zone * zone, LocationKind kind, MachineRepresentation rep, int index) [inline], [static]
Definition at line 625 of file instruction.h.
                                                                     {
    return InstructionOperand::New(zone, AllocatedOperand(kind, rep, index));
  }
References v8::internal::index, v8::internal::compiler::InstructionOperand::kind(), and v8::internal::compiler::InstructionOperand::New().
Referenced by v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/instruction.h