cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask Class Reference
Public Member Functions
ConcurrentSweepTask (Platform *platform, HeapBase &heap, SpaceStates *space_states, SweepingState *empty_normal_pages, SweepingState *empty_large_pages, FreeMemoryHandling free_memory_handling)
void Run (cppgc::JobDelegate *delegate) final
size_t GetMaxConcurrency (size_t) const final
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Private Types
using FreeMemoryHandling = SweepingConfig::FreeMemoryHandling
Private Member Functions
bool SweepStateOrYield (cppgc::JobDelegate *delegate, SweepingState &state)
bool VisitNormalPage (NormalPage &page)
bool VisitLargePage (LargePage &page)
Private Attributes
HeapBase & heap_
PageAllocator & page_allocator_
SpaceStates *const space_states_
SweepingState *const empty_normal_pages_
SweepingState *const empty_large_pages_
SweepingState * current_sweeping_state_ = nullptr
std::atomic_bool is_completed_ {false}
const FreeMemoryHandling free_memory_handling_
const StickyBits sticky_bits_
Friends
class HeapVisitor< ConcurrentSweepTask >
Detailed Description
Definition at line 764 of file sweeper.cc.
Member Typedef Documentation
FreeMemoryHandling
using cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::FreeMemoryHandling = SweepingConfig::FreeMemoryHandling [private]
Definition at line 768 of file sweeper.cc.
Constructor & Destructor Documentation
ConcurrentSweepTask()
cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::ConcurrentSweepTask (Platform * platform, HeapBase & heap, SpaceStates * space_states, SweepingState * empty_normal_pages, SweepingState * empty_large_pages, FreeMemoryHandling free_memory_handling) [inline]
Definition at line 771 of file sweeper.cc.
      : heap_(heap),
        page_allocator_(*platform->GetPageAllocator()),
        space_states_(space_states),
        empty_normal_pages_(empty_normal_pages),
        empty_large_pages_(empty_large_pages),
        free_memory_handling_(free_memory_handling),
        sticky_bits_(heap.sticky_bits()) {}
Member Function Documentation
GetMaxConcurrency()
size_t cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::GetMaxConcurrency (size_t worker_count) const [inline], [final], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 802 of file sweeper.cc.
                                                 {
    return is_completed_.load(std::memory_order_relaxed) ? 0 : 1;
  }
Run()
void cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::Run (cppgc::JobDelegate * delegate) [inline], [final], [virtual]
Implements v8::JobTask.
Definition at line 784 of file sweeper.cc.
                                             {
    StatsCollector::EnabledConcurrentScope stats_scope(
        heap_.stats_collector(), StatsCollector::kConcurrentSweep);
    // Sweep empty normal pages first. These pages can be reused across all
    // regular spaces.
    if (!SweepStateOrYield(delegate, *empty_normal_pages_)) return;
    for (SweepingState& state : *space_states_) {
      if (!SweepStateOrYield(delegate, state)) return;
    }
    // Sweep empty large pages last. They generally cannot be reused.
    // TODO(mlippautz): We could split them into pages that can be split up for
    // normal pages.
    if (!SweepStateOrYield(delegate, *empty_large_pages_)) return;
    is_completed_.store(true, std::memory_order_relaxed);
  }
SweepStateOrYield()
bool cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::SweepStateOrYield (cppgc::JobDelegate * delegate, SweepingState & state) [inline], [private]
Definition at line 808 of file sweeper.cc.
                                                                           {
    current_sweeping_state_ = &state;
    while (auto page = state.unswept_pages.Pop()) {
      Traverse(**page);
      if (delegate->ShouldYield()) {
        return false;
      }
    }
    current_sweeping_state_ = nullptr;
    return true;
  }
References v8::JobDelegate::ShouldYield(), and cppgc::internal::anonymous_namespace{sweeper.cc}::SweepingState::unswept_pages.
VisitLargePage()
bool cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::VisitLargePage (LargePage & page) [inline], [private]
Definition at line 836 of file sweeper.cc.
                                       {
    HeapObjectHeader* header = page.ObjectHeader();
    CHECK(!header->IsMarked());
    DCHECK_EQ(page.marked_bytes(), 0u);
#if defined(CPPGC_CAGED_HEAP)
    HeapObjectHeader* const unfinalized_objects =
        header->IsFinalizable() ? page.ObjectHeader() : nullptr;
#else // !defined(CPPGC_CAGED_HEAP)
    std::vector<HeapObjectHeader*> unfinalized_objects;
    if (header->IsFinalizable()) {
      unfinalized_objects.push_back(page.ObjectHeader());
    }
#endif // !defined(CPPGC_CAGED_HEAP)
    // Avoid directly destroying large pages here as counter updates and
    // backend access in BasePage::Destroy() are not concurrency safe.
    current_sweeping_state_->swept_unfinalized_pages.Push(
        {&page, std::move(unfinalized_objects), {}, {}, true});
    return true;
  }
References CHECK, DCHECK_EQ, cppgc::internal::HeapObjectHeader::IsFinalizable(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::BasePage::marked_bytes(), and cppgc::internal::LargePage::ObjectHeader().
VisitNormalPage()
bool cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::VisitNormalPage (NormalPage & page) [inline], [private]
Definition at line 820 of file sweeper.cc.
                                         {
    if (free_memory_handling_ == FreeMemoryHandling::kDiscardWherePossible) {
      page.ResetDiscardedMemory();
    }
    SweepingState::SweptPageState sweep_result =
        (free_memory_handling_ == FreeMemoryHandling::kDiscardWherePossible)
            ? SweepNormalPage<
                  DeferredFinalizationBuilder<DiscardingFreeHandler>>(
                  &page, page_allocator_, sticky_bits_)
            : SweepNormalPage<DeferredFinalizationBuilder<RegularFreeHandler>>(
                  &page, page_allocator_, sticky_bits_);
    current_sweeping_state_->swept_unfinalized_pages.Push(
        std::move(sweep_result));
    return true;
  }
References cppgc::internal::kDiscardWherePossible, cppgc::internal::BasePage::ResetDiscardedMemory(), and cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage().
Friends And Related Function Documentation
HeapVisitor< ConcurrentSweepTask >
friend class HeapVisitor< ConcurrentSweepTask > [friend]
Definition at line 761 of file sweeper.cc.
Member Data Documentation
current_sweeping_state_
SweepingState* cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::current_sweeping_state_ = nullptr [private]
Definition at line 861 of file sweeper.cc.
empty_large_pages_
SweepingState* const cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::empty_large_pages_ [private]
Definition at line 860 of file sweeper.cc.
empty_normal_pages_
SweepingState* const cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::empty_normal_pages_ [private]
Definition at line 859 of file sweeper.cc.
free_memory_handling_
const FreeMemoryHandling cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::free_memory_handling_ [private]
Definition at line 863 of file sweeper.cc.
heap_
HeapBase& cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::heap_ [private]
Definition at line 856 of file sweeper.cc.
is_completed_
std::atomic_bool cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::is_completed_ {false} [private]
Definition at line 862 of file sweeper.cc.
page_allocator_
PageAllocator& cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::page_allocator_ [private]
Definition at line 857 of file sweeper.cc.
space_states_
SpaceStates* const cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::space_states_ [private]
Definition at line 858 of file sweeper.cc.
sticky_bits_
const StickyBits cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::sticky_bits_ [private]
Definition at line 864 of file sweeper.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/sweeper.cc