v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ Class Reference
Public Member Functions
BZ (ProcessorImpl *proc, int scratch_space)
void DivideBasecase (RWDigits Q, RWDigits R, Digits A, Digits B)
void D3n2n (RWDigits Q, RWDigits R, Digits A1A2, Digits A3, Digits B)
void D2n1n (RWDigits Q, RWDigits R, Digits A, Digits B)
Private Attributes
ProcessorImpl * proc_
Storage scratch_mem_
Detailed Description
Definition at line 55 of file div-burnikel.cc.
Constructor & Destructor Documentation
BZ()
v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::BZ (ProcessorImpl * proc, int scratch_space) [inline]
Definition at line 57 of file div-burnikel.cc.
      : proc_(proc),
        scratch_mem_(scratch_space >= kBurnikelThreshold ? scratch_space : 0) {}
Member Function Documentation
D2n1n()
void v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::D2n1n (RWDigits Q, RWDigits R, Digits A, Digits B)
Definition at line 159 of file div-burnikel.cc.
                                                         {
  int n = B.len();
  DCHECK(A.len() <= 2 * n);
  // A < B * 2^(kDigitsBits * n)
  DCHECK(Compare(Digits(A, n, n), B) < 0);
  DCHECK(Q.len() == n);
  DCHECK(R.len() == n);
  // 1. If n is odd or smaller than some convenient constant, compute Q and R
  // by school division and return.
  if ((n & 1) == 1 || n < kBurnikelThreshold) {
    return DivideBasecase(Q, R, A, B);
  }
  // 2. Split A into four parts A = [A1, ..., A4] with
  // Ai < 2^(kDigitBits * n / 2). Split B into two parts [B2, B1] with
  // Bi < 2^(kDigitBits * n / 2).
  Digits A1A2(A, n, n);
  Digits A3(A, n / 2, n / 2);
  Digits A4(A, 0, n / 2);
  // 3. Compute the high part Q1 of floor(A/B) as
  // Q1 = floor([A1, A2, A3] / [B1, B2]) with remainder R1 = [R11, R12],
  // using algorithm D3n2n.
  RWDigits Q1(Q, n / 2, n / 2);
  ScratchDigits R1(n);
  D3n2n(Q1, R1, A1A2, A3, B);
  if (proc_->should_terminate()) return;
  // 4. Compute the low part Q2 of floor(A/B) as
  // Q2 = floor([R11, R12, A4] / [B1, B2]) with remainder R, using
  // algorithm D3n2n.
  RWDigits Q2(Q, 0, n / 2);
  D3n2n(Q2, R, R1, A4, B);
  // 5. Return Q = [Q1, Q2] and R.
}
References v8::internal::A, v8::internal::B, v8::bigint::Compare(), DCHECK, v8::bigint::kBurnikelThreshold, and v8::bigint::Digits::len().
D3n2n()
void v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::D3n2n (RWDigits Q, RWDigits R, Digits A1A2, Digits A3, Digits B)
Definition at line 96 of file div-burnikel.cc.
                                                                       {
  DCHECK((B.len() & 1) == 0);
  int n = B.len() / 2;
  DCHECK(A1A2.len() == 2 * n);
  // Actual condition is stricter than length: A < B * 2^(kDigitBits * n)
  DCHECK(Compare(A1A2, B) < 0);
  DCHECK(A3.len() == n);
  DCHECK(Q.len() == n);
  DCHECK(R.len() == 2 * n);
  // 1. Split A into three parts A = [A1, A2, A3] with Ai < 2^(kDigitBits * n).
  Digits A1(A1A2, n, n);
  // 2. Split B into two parts B = [B1, B2] with Bi < 2^(kDigitBits * n).
  Digits B1(B, n, n);
  Digits B2(B, 0, n);
  // 3. Distinguish the cases A1 < B1 or A1 >= B1.
  RWDigits Qhat = Q;
  RWDigits R1(R, n, n);
  digit_t r1_high = 0;
  if (Compare(A1, B1) < 0) {
    // 3a. If A1 < B1, compute Qhat = floor([A1, A2] / B1) with remainder R1
    // using algorithm D2n1n.
    D2n1n(Qhat, R1, A1A2, B1);
    if (proc_->should_terminate()) return;
  } else {
    // 3b. If A1 >= B1, set Qhat = 2^(kDigitBits * n) - 1 and set
    // R1 = [A1, A2] - [B1, 0] + [0, B1]
    SetOnes(Qhat);
    // Step 1: compute A1 - B1, which can't underflow because of the comparison
    // guarding this else-branch, and always has a one-digit result because
    // of this function's preconditions.
    RWDigits temp = R1;
    Subtract(temp, A1, B1);
    temp.Normalize();
    DCHECK(temp.len() <= 1);
    if (temp.len() > 0) r1_high = temp[0];
    // Step 2: compute A2 + B1.
    Digits A2(A1A2, 0, n);
    r1_high += AddAndReturnCarry(R1, A2, B1);
  }
  // 4. Compute D = Qhat * B2 using (Karatsuba) multiplication.
  RWDigits D(scratch_mem_.get(), 2 * n);
  proc_->Multiply(D, Qhat, B2);
  if (proc_->should_terminate()) return;
  // 5. Compute Rhat = R1*2^(kDigitBits * n) + A3 - D = [R1, A3] - D.
  PutAt(R, A3, n);
  // 6. As long as Rhat < 0, repeat:
  while (SpecialCompare(r1_high, R, D) < 0) {
    // 6a. Rhat = Rhat + B
    r1_high += AddAndReturnCarry(R, R, B);
    // 6b. Qhat = Qhat - 1
    Subtract(Qhat, 1);
  }
  // 5. Compute Rhat = R1*2^(kDigitBits * n) + A3 - D = [R1, A3] - D.
  digit_t borrow = SubtractAndReturnBorrow(R, R, D);
  DCHECK(borrow == r1_high);
  DCHECK(Compare(R, B) < 0);
  (void)borrow;
  // 7. Return R = Rhat, Q = Qhat.
}
References v8::bigint::AddAndReturnCarry(), v8::internal::B, v8::internal::B1, v8::internal::B2, v8::bigint::Compare(), D, DCHECK, v8::bigint::Digits::len(), v8::bigint::Digits::Normalize(), v8::bigint::PutAt(), v8::bigint::anonymous_namespace{div-burnikel.cc}::SetOnes(), v8::bigint::anonymous_namespace{div-burnikel.cc}::SpecialCompare(), v8::bigint::Subtract(), v8::bigint::SubtractAndReturnBorrow(), and v8::internal::wasm::void().
DivideBasecase()
void v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::DivideBasecase (RWDigits Q, RWDigits R, Digits A, Digits B)
Definition at line 70 of file div-burnikel.cc.
                                                                  {
  A.Normalize();
  B.Normalize();
  DCHECK(B.len() > 0);
  int cmp = Compare(A, B);
  if (cmp <= 0) {
    Q.Clear();
    if (cmp == 0) {
      // If A == B, then Q=1, R=0.
      R.Clear();
      Q[0] = 1;
    } else {
      // If A < B, then Q=0, R=A.
      PutAt(R, A, R.len());
    }
    return;
  }
  if (B.len() == 1) {
    return proc_->DivideSingle(Q, R.digits(), A, B[0]);
  }
  return proc_->DivideSchoolbook(Q, R, A, B);
}
References v8::internal::A, v8::internal::B, v8::bigint::RWDigits::Clear(), v8::bigint::Compare(), DCHECK, v8::bigint::RWDigits::digits(), v8::bigint::Digits::len(), and v8::bigint::PutAt().
Member Data Documentation
proc_
ProcessorImpl* v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::proc_ [private]
Definition at line 66 of file div-burnikel.cc.
scratch_mem_
Storage v8::bigint::anonymous_namespace{div-burnikel.cc}::BZ::scratch_mem_ [private]
Definition at line 67 of file div-burnikel.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/bigint/div-burnikel.cc