v8::internal::compiler::CallFeedback Class Reference
#include <processed-feedback.h>
Public Member Functions
CallFeedback (OptionalHeapObjectRef target, float frequency, SpeculationMode mode, CallFeedbackContent call_feedback_content, FeedbackSlotKind slot_kind)
OptionalHeapObjectRef target () const
float frequency () const
SpeculationMode speculation_mode () const
CallFeedbackContent call_feedback_content () const
Private Attributes
OptionalHeapObjectRef const target_
float const frequency_
SpeculationMode const mode_
CallFeedbackContent const content_
Additional Inherited Members
Detailed Description
Definition at line 202 of file processed-feedback.h.
Constructor & Destructor Documentation
CallFeedback()
v8::internal::compiler::CallFeedback::CallFeedback (OptionalHeapObjectRef target, float frequency, SpeculationMode mode, CallFeedbackContent call_feedback_content, FeedbackSlotKind slot_kind) [inline]
Definition at line 204 of file processed-feedback.h.
      : ProcessedFeedback(kCall, slot_kind),
        target_(target),
        frequency_(frequency),
        mode_(mode),
        content_(call_feedback_content) {}
Member Function Documentation
call_feedback_content()
CallFeedbackContent v8::internal::compiler::CallFeedback::call_feedback_content () const [inline]
Definition at line 216 of file processed-feedback.h.
{ return content_; }
References content_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCallWithFeedback(), and v8::internal::compiler::BytecodeGraphBuilder::ComputeCallFeedbackRelation().
frequency()
float v8::internal::compiler::CallFeedback::frequency () const [inline]
Definition at line 214 of file processed-feedback.h.
{ return frequency_; }
References frequency_.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::ComputeCallFrequency(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildInlineCall().
speculation_mode()
SpeculationMode v8::internal::compiler::CallFeedback::speculation_mode () const [inline]
Definition at line 215 of file processed-feedback.h.
{ return mode_; }
References mode_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::SaveCallSpeculationScope::GetSpeculationMode(), v8::internal::compiler::BytecodeGraphBuilder::GetSpeculationMode(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator().
target()
OptionalHeapObjectRef v8::internal::compiler::CallFeedback::target () const [inline]
Definition at line 213 of file processed-feedback.h.
{ return target_; }
References target_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCallWithFeedback(), v8::internal::maglev::MaglevGraphBuilder::BuildConstruct(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
Member Data Documentation
content_
CallFeedbackContent const v8::internal::compiler::CallFeedback::content_ [private]
Definition at line 222 of file processed-feedback.h.
Referenced by call_feedback_content().
frequency_
float const v8::internal::compiler::CallFeedback::frequency_ [private]
Definition at line 220 of file processed-feedback.h.
Referenced by frequency().
mode_
SpeculationMode const v8::internal::compiler::CallFeedback::mode_ [private]
Definition at line 221 of file processed-feedback.h.
Referenced by speculation_mode().
target_
OptionalHeapObjectRef const v8::internal::compiler::CallFeedback::target_ [private]
Definition at line 219 of file processed-feedback.h.
Referenced by target().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/processed-feedback.h