v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode > Class Template Reference
#include <function-body-decoder-impl.h>
Public Member Functions
WasmDecoder (Zone *zone, const WasmModule *module, WasmEnabledFeatures enabled, WasmDetectedFeatures *detected, const FunctionSig *sig, bool is_shared, const uint8_t *start, const uint8_t *end, uint32_t buffer_offset=0)
Zone * zone () const
uint32_t num_locals () const
base::Vector< ValueType > local_types () const
ValueType local_type (uint32_t index) const
uint32_t DecodeLocals (const uint8_t *pc)
template<typename... Args>
void DecodeError (Args... args)
bool Validate (const uint8_t *pc, TagIndexImmediate &imm)
bool Validate (const uint8_t *pc, GlobalIndexImmediate &imm)
bool Validate (const uint8_t *pc, SigIndexImmediate &imm)
bool Validate (const uint8_t *pc, StructIndexImmediate &imm)
bool Validate (const uint8_t *pc, FieldImmediate &imm)
bool Validate (const uint8_t *pc, ArrayIndexImmediate &imm)
bool CanReturnCall (const FunctionSig *target_sig)
bool Validate (const uint8_t *pc, CallFunctionImmediate &imm)
bool Validate (const uint8_t *pc, CallIndirectImmediate &imm)
bool Validate (const uint8_t *pc, BranchDepthImmediate &imm, size_t control_depth)
bool Validate (const uint8_t *pc, BranchTableImmediate &imm)
bool Validate (const uint8_t *pc, WasmOpcode opcode, SimdLaneImmediate &imm)
bool Validate (const uint8_t *pc, Simd128Immediate &imm)
bool Validate (const uint8_t *pc, BlockTypeImmediate &imm)
bool Validate (const uint8_t *pc, MemoryIndexImmediate &imm)
bool Validate (const uint8_t *pc, MemoryAccessImmediate &imm)
bool Validate (const uint8_t *pc, MemoryInitImmediate &imm)
bool Validate (const uint8_t *pc, MemoryCopyImmediate &imm)
bool Validate (const uint8_t *pc, TableInitImmediate &imm)
bool Validate (const uint8_t *pc, TableCopyImmediate &imm)
bool Validate (const uint8_t *pc, StringConstImmediate &imm)
bool Validate (const uint8_t *pc, TableIndexImmediate &imm)
bool ValidateElementSegment (const uint8_t *pc, IndexImmediate &imm)
bool ValidateLocal (const uint8_t *pc, IndexImmediate &imm)
bool ValidateFunction (const uint8_t *pc, IndexImmediate &imm)
bool ValidateCont (const uint8_t *pc, ContIndexImmediate &imm)
bool ValidateDataSegment (const uint8_t *pc, IndexImmediate &imm)
bool Validate (const uint8_t *pc, SelectTypeImmediate &imm)
bool Validate (const uint8_t *pc, HeapTypeImmediate &imm)
bool ValidateValueType (const uint8_t *pc, ValueType type)
bool ValidateHeapType (const uint8_t *pc, HeapType type)
Static Public Member Functions
static BitVector * AnalyzeLoopAssignment (WasmDecoder *decoder, const uint8_t *pc, uint32_t locals_count, Zone *zone, bool *loop_is_innermost=nullptr)
template<typename... ImmediateObservers>
static uint32_t OpcodeLength (WasmDecoder *decoder, const uint8_t *pc, ImmediateObservers &... ios)
Public Attributes
Zone *const zone_
ValueType * local_types_ = nullptr
uint32_t num_locals_ = 0
const WasmModule * module_
const WasmEnabledFeatures enabled_
WasmDetectedFeatures * detected_
const FunctionSig * sig_
bool is_shared_
const std::pair< uint32_t, uint32_t > * current_inst_trace_
Static Public Attributes
static constexpr ValidationTag validate = {}
Additional Inherited Members
Detailed Description
template<typename ValidationTag, DecodingMode decoding_mode = kFunctionBody>
class v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >
Definition at line 1732 of file function-body-decoder-impl.h.
Constructor & Destructor Documentation
WasmDecoder()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::WasmDecoder (Zone * zone, const WasmModule * module, WasmEnabledFeatures enabled, WasmDetectedFeatures * detected, const FunctionSig * sig, bool is_shared, const uint8_t * start, const uint8_t * end, uint32_t buffer_offset = 0) [inline]
Definition at line 1734 of file function-body-decoder-impl.h.
      : Decoder(start, end, buffer_offset),
        zone_(zone),
        module_(module),
        enabled_(enabled),
        detected_(detected),
        sig_(sig),
        is_shared_(is_shared) {
    current_inst_trace_ = &invalid_instruction_trace;
    if (V8_UNLIKELY(module_ && !module_->inst_traces.empty())) {
      auto last_trace = module_->inst_traces.end() - 1;
      auto first_inst_trace =
          std::lower_bound(module_->inst_traces.begin(), last_trace,
                           std::make_pair(buffer_offset, 0),
                           [](const std::pair<uint32_t, uint32_t>& a,
                              const std::pair<uint32_t, uint32_t>& b) {
                             return a.first < b.first;
                           });
      if (V8_UNLIKELY(first_inst_trace != last_trace)) {
        current_inst_trace_ = &*first_inst_trace;
      }
    }
  }
References v8::internal::wasm::Decoder::buffer_offset(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::current_inst_trace_, v8::internal::wasm::WasmModule::inst_traces, v8::internal::wasm::invalid_instruction_trace, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, and V8_UNLIKELY.
Member Function Documentation
AnalyzeLoopAssignment()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
static BitVector* v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::AnalyzeLoopAssignment (WasmDecoder< ValidationTag, decoding_mode > * decoder, const uint8_t * pc, uint32_t locals_count, Zone * zone, bool * loop_is_innermost = nullptr) [inline], [static]
Definition at line 1881 of file function-body-decoder-impl.h.
                                                                             {
    if (pc >= decoder->end()) return nullptr;
    if (*pc != kExprLoop) return nullptr;
    // The number of locals_count is augmented by 1 so that the 'locals_count'
    // index can be used to track the instance cache.
    BitVector* assigned = zone->New<BitVector>(locals_count + 1, zone);
    int depth = -1; // We will increment the depth to 0 when we decode the
                     // starting 'loop' opcode.
    if (loop_is_innermost) *loop_is_innermost = true;
    // Iteratively process all AST nodes nested inside the loop.
    while (pc < decoder->end() && VALIDATE(decoder->ok())) {
      WasmOpcode opcode = static_cast<WasmOpcode>(*pc);
      switch (opcode) {
        case kExprLoop:
          if (loop_is_innermost && depth >= 0) *loop_is_innermost = false;
          [[fallthrough]];
        case kExprIf:
        case kExprBlock:
        case kExprTry:
        case kExprTryTable:
          depth++;
          break;
        case kExprLocalSet:
        case kExprLocalTee: {
          IndexImmediate imm(decoder, pc + 1, "local index", validate);
          // Unverified code might have an out-of-bounds index.
          if (imm.index < locals_count) assigned->Add(imm.index);
          break;
        }
        case kExprMemoryGrow:
        case kExprCallFunction:
        case kExprCallIndirect:
        case kExprCallRef:
          // Add instance cache to the assigned set.
          assigned->Add(locals_count);
          break;
        case kExprEnd:
          depth--;
          break;
        default:
          break;
      }
      if (depth < 0) break;
      pc += OpcodeLength(decoder, pc);
    }
    return VALIDATE(decoder->ok()) ? assigned : nullptr;
  }
References v8::internal::BitVector::Add(), v8::internal::wasm::Decoder::end(), v8::internal::wasm::IndexImmediate::index, v8::internal::Zone::New(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength(), v8::internal::wasm::Decoder::pc(), VALIDATE, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::validate, and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::zone().
Referenced by v8::internal::wasm::AnalyzeLoopAssignmentForTesting(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::Loop().
CanReturnCall()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::CanReturnCall (const FunctionSig * target_sig) [inline]
Definition at line 2014 of file function-body-decoder-impl.h.
                                                    {
    if (sig_->return_count() != target_sig->return_count()) return false;
    auto target_sig_it = target_sig->returns().begin();
    for (ValueType ret_type : sig_->returns()) {
      if (!IsSubtypeOf(*target_sig_it++, ret_type, this->module_)) return false;
    }
    return true;
  }
References v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::Signature< T >::return_count(), v8::internal::Signature< T >::returns(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::sig_.
DecodeError()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
template<typename... Args>
void v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError (Args... args) [inline]
Definition at line 1873 of file function-body-decoder-impl.h.
                                           {
    wasm::DecodeError<ValidationTag>(this, std::forward<Args>(args)...);
  }
References v8::internal::wasm::Decoder::args.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::NonConstError(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::UnknownOpcodeError(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateCont(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateDataSegment(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateElementSegment(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateFunction(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateLocal().
DecodeLocals()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
uint32_t v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals (const uint8_t * pc) [inline]
Definition at line 1777 of file function-body-decoder-impl.h.
                                           {
    DCHECK_NULL(local_types_);
    DCHECK_EQ(0, num_locals_);
    // In a first step, count the number of locals and store the decoded
    // entries.
    num_locals_ = static_cast<uint32_t>(this->sig_->parameter_count());
    // Decode local declarations, if any.
    auto [entries, entries_length] =
        read_u32v<ValidationTag>(pc, "local decls count");
    if (!VALIDATE(ok())) {
      DecodeError(pc, "invalid local decls count");
      return 0;
    }
    TRACE("local decls count: %u\n", entries);
    // Do an early validity check, to avoid allocating too much memory below.
    // Every entry needs at least two bytes (count plus type); if that many are
    // not available any more, flag that as an error.
    if (available_bytes() / 2 < entries) {
      DecodeError(pc, "local decls count bigger than remaining function size");
      return 0;
    }
    struct DecodedLocalEntry {
      uint32_t count;
      ValueType type;
    };
    base::SmallVector<DecodedLocalEntry, 8> decoded_locals(entries);
    uint32_t total_length = entries_length;
    for (uint32_t entry = 0; entry < entries; ++entry) {
      if (!VALIDATE(more())) {
        DecodeError(end(),
                    "expected more local decls but reached end of input");
        return 0;
      }
      auto [count, count_length] =
          read_u32v<ValidationTag>(pc + total_length, "local count");
      if (!VALIDATE(ok())) {
        DecodeError(pc + total_length, "invalid local count");
        return 0;
      }
      DCHECK_LE(num_locals_, kV8MaxWasmFunctionLocals);
      if (!VALIDATE(count <= kV8MaxWasmFunctionLocals - num_locals_)) {
        DecodeError(pc + total_length, "local count too large");
        return 0;
      }
      total_length += count_length;
      auto [type, type_length] =
          value_type_reader::read_value_type<ValidationTag>(
              this, pc + total_length, enabled_, detected_);
      ValidateValueType(pc + total_length, type);
      if (!VALIDATE(ok())) return 0;
      if (module_) {
        value_type_reader::Populate(&type, module_);
      } else {
        DCHECK(!ValidationTag::validate);
      }
      if (!VALIDATE(!is_shared_ || type.is_shared())) {
        DecodeError(pc + total_length, "local must have shared type");
        return 0;
      }
      total_length += type_length;
      num_locals_ += count;
      decoded_locals[entry] = DecodedLocalEntry{count, type};
    }
    DCHECK(ok());
    if (num_locals_ > 0) {
      // Now build the array of local types from the parsed entries.
      local_types_ = zone_->AllocateArray<ValueType>(num_locals_);
      ValueType* locals_ptr = local_types_;
      if (sig_->parameter_count() > 0) {
        std::copy(sig_->parameters().begin(), sig_->parameters().end(),
                  locals_ptr);
        locals_ptr += sig_->parameter_count();
      }
      for (auto& entry : decoded_locals) {
        std::fill_n(locals_ptr, entry.count, entry.type);
        locals_ptr += entry.count;
      }
      DCHECK_EQ(locals_ptr, local_types_ + num_locals_);
    }
    return total_length;
  }
References v8::internal::Zone::AllocateArray(), v8::internal::wasm::Decoder::available_bytes(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, DCHECK_NULL, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::detected_, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::enabled_, v8::internal::wasm::Decoder::end(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::is_shared_, v8::internal::wasm::kV8MaxWasmFunctionLocals, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::local_types_, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::more(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::num_locals_, v8::internal::wasm::Decoder::ok(), v8::internal::Signature< T >::parameter_count(), v8::internal::Signature< T >::parameters(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::value_type_reader::Populate(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::sig_, v8::internal::TRACE(), v8::internal::tracing::type, VALIDATE, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateValueType(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::zone_.
Referenced by v8::internal::wasm::DecodeLocalDecls().
local_type()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
ValueType v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::local_type (uint32_t index) const [inline]
Definition at line 1768 of file function-body-decoder-impl.h.
                                             {
    DCHECK_GE(num_locals_, index);
    return local_types_[index];
  }
References DCHECK_GE, v8::internal::index, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::local_types_, and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::num_locals_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Loop(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StartFunction(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StartFunction(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction().
local_types()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
base::Vector<ValueType> v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::local_types () const [inline]
Definition at line 1765 of file function-body-decoder-impl.h.
                                            {
    return base::VectorOf(local_types_, num_locals_);
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::local_types_, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::num_locals_, and v8::base::VectorOf().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::BlockPhis().
num_locals()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
uint32_t v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::num_locals () const [inline]
Definition at line 1763 of file function-body-decoder-impl.h.
{ return num_locals_; }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::num_locals_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BindBlockAndGeneratePhis(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::BlockPhis(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Loop(), v8::internal::wasm::TurboshaftGraphBuildingInterface::SetupControlFlowEdge(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StartFunction(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StartFunction(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateLocal().
OpcodeLength()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
template<typename... ImmediateObservers>
static uint32_t v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength (WasmDecoder< ValidationTag, decoding_mode > * decoder, const uint8_t * pc, ImmediateObservers &... ios) [inline], [static]
Definition at line 2366 of file function-body-decoder-impl.h.
                                                           {
    WasmOpcode opcode = static_cast<WasmOpcode>(*pc);
    switch (opcode) {
      /********** Control opcodes **********/
      case kExprUnreachable:
      case kExprNop:
      case kExprNopForTestingUnsupportedInLiftoff:
      case kExprElse:
      case kExprEnd:
      case kExprReturn:
        return 1;
      case kExprTry:
      case kExprIf:
      case kExprLoop:
      case kExprBlock: {
        BlockTypeImmediate imm(WasmEnabledFeatures::All(), decoder->detected_,
                               decoder, pc + 1, validate);
        (ios.BlockType(imm), ...);
        return 1 + imm.length;
      }
      case kExprRethrow:
      case kExprBr:
      case kExprBrIf:
      case kExprBrOnNull:
      case kExprBrOnNonNull:
      case kExprDelegate: {
        BranchDepthImmediate imm(decoder, pc + 1, validate);
        (ios.BranchDepth(imm), ...);
        return 1 + imm.length;
      }
      case kExprBrTable: {
        BranchTableImmediate imm(decoder, pc + 1, validate);
        (ios.BranchTable(imm), ...);
        BranchTableIterator<ValidationTag> iterator(decoder, imm);
        while (iterator.has_next()) iterator.next();
        return 1 + iterator.length();
      }
      case kExprTryTable: {
        BlockTypeImmediate block_type_imm(WasmEnabledFeatures::All(),
                                          decoder->detected_, decoder, pc + 1,
                                          validate);
        (ios.BlockType(block_type_imm), ...);
        TryTableImmediate try_table_imm(decoder, pc + 1 + block_type_imm.length,
                                        validate);
        (ios.TryTable(try_table_imm), ...);
        TryTableIterator<ValidationTag> iterator(decoder, try_table_imm);
        while (iterator.has_next()) iterator.next();
        return 1 + block_type_imm.length + iterator.length();
      }
      case kExprThrow:
      case kExprCatch: {
        TagIndexImmediate imm(decoder, pc + 1, validate);
        (ios.TagIndex(imm), ...);
        return 1 + imm.length;
      }
      case kExprThrowRef:
        return 1;
      /********** Core stack switching ********/
      case kExprContNew: {
        ContIndexImmediate imm(decoder, pc + 1, validate);
        (ios.TypeIndex(imm), ...);
        return 1 + imm.length;
      }
      case kExprContBind: {
        ContIndexImmediate src(decoder, pc + 1, validate);
        (ios.TypeIndex(src), ...);
        ContIndexImmediate dst(decoder, pc + 1 + src.length, validate);
        (ios.TypeIndex(dst), ...);
        return 1 + src.length + dst.length;
      }
      case kExprSuspend: {
        TagIndexImmediate imm(decoder, pc + 1, validate);
        (ios.TagIndex(imm), ...);
        return 1 + imm.length;
      }
      case kExprResume: {
        ContIndexImmediate src(decoder, pc + 1, validate);
        (ios.TypeIndex(src), ...);
        EffectHandlerTableImmediate handler_table(decoder, pc + 1 + src.length,
                                                  validate);
        (ios.EffectHandlerTable(handler_table), ...);
        EffectHandlerTableIterator<ValidationTag> iterator(decoder,
                                                           handler_table);
        while (iterator.has_next()) iterator.next();
        return 1 + src.length + iterator.length();
      }
      case kExprResumeThrow: {
        ContIndexImmediate src(decoder, pc + 1, validate);
        (ios.TypeIndex(src), ...);
        TagIndexImmediate event(decoder, pc + src.length + 1, validate);
        (ios.TagIndex(event), ...);
        EffectHandlerTableImmediate handler_table(
            decoder, pc + 1 + src.length + event.length, validate);
        (ios.EffectHandlerTable(handler_table), ...);
        EffectHandlerTableIterator<ValidationTag> iterator(decoder,
                                                           handler_table);
        while (iterator.has_next()) iterator.next();
        return 1 + src.length + event.length + iterator.length();
      }
      case kExprSwitch: {
        ContIndexImmediate src(decoder, pc + 1, validate);
        (ios.TypeIndex(src), ...);
        TagIndexImmediate tag(decoder, pc + src.length + 1, validate);
        (ios.TagIndex(tag), ...);
        return 1 + src.length + tag.length;
      }
      /********** Misc opcodes **********/
      case kExprCallFunction:
      case kExprReturnCall: {
        CallFunctionImmediate imm(decoder, pc + 1, validate);
        (ios.FunctionIndex(imm), ...);
        return 1 + imm.length;
      }
      case kExprCallIndirect:
      case kExprReturnCallIndirect: {
        CallIndirectImmediate imm(decoder, pc + 1, validate);
        (ios.CallIndirect(imm), ...);
        return 1 + imm.length;
      }
      case kExprCallRef:
      case kExprReturnCallRef: {
        SigIndexImmediate imm(decoder, pc + 1, validate);
        (ios.TypeIndex(imm), ...);
        return 1 + imm.length;
      }
      case kExprDrop:
      case kExprSelect:
      case kExprCatchAll:
      case kExprRefEq:
        return 1;
      case kExprSelectWithType: {
        SelectTypeImmediate imm(WasmEnabledFeatures::All(), decoder->detected_,
                                decoder, pc + 1, validate);
        (ios.SelectType(imm), ...);
        return 1 + imm.length;
      }
      case kExprLocalGet:
      case kExprLocalSet:
      case kExprLocalTee: {
        IndexImmediate imm(decoder, pc + 1, "local index", validate);
        (ios.LocalIndex(imm), ...);
        return 1 + imm.length;
      }
      case kExprGlobalGet:
      case kExprGlobalSet: {
        GlobalIndexImmediate imm(decoder, pc + 1, validate);
        (ios.GlobalIndex(imm), ...);
        return 1 + imm.length;
      }
      case kExprTableGet:
      case kExprTableSet: {
        TableIndexImmediate imm(decoder, pc + 1, validate);
        (ios.TableIndex(imm), ...);
        return 1 + imm.length;
      }
      case kExprI32Const: {
        ImmI32Immediate imm(decoder, pc + 1, validate);
        (ios.I32Const(imm), ...);
        return 1 + imm.length;
      }
      case kExprI64Const: {
        ImmI64Immediate imm(decoder, pc + 1, validate);
        (ios.I64Const(imm), ...);
        return 1 + imm.length;
      }
      case kExprF32Const:
        if (sizeof...(ios) > 0) {
          ImmF32Immediate imm(decoder, pc + 1, validate);
          (ios.F32Const(imm), ...);
        }
        return 5;
      case kExprF64Const:
        if (sizeof...(ios) > 0) {
          ImmF64Immediate imm(decoder, pc + 1, validate);
          (ios.F64Const(imm), ...);
        }
        return 9;
      case kExprRefNull: {
        HeapTypeImmediate imm(WasmEnabledFeatures::All(), decoder->detected_,
                              decoder, pc + 1, validate);
        (ios.HeapType(imm), ...);
        return 1 + imm.length;
      }
      case kExprRefIsNull:
      case kExprRefAsNonNull:
        return 1;
      case kExprRefFunc: {
        IndexImmediate imm(decoder, pc + 1, "function index", validate);
        (ios.FunctionIndex(imm), ...);
        return 1 + imm.length;
      }
#define DECLARE_OPCODE_CASE(name, ...) case kExpr##name:
        // clang-format off
      /********** Simple and memory opcodes **********/
      FOREACH_SIMPLE_OPCODE(DECLARE_OPCODE_CASE)
      FOREACH_SIMPLE_PROTOTYPE_OPCODE(DECLARE_OPCODE_CASE)
        return 1;
      FOREACH_LOAD_MEM_OPCODE(DECLARE_OPCODE_CASE)
      FOREACH_STORE_MEM_OPCODE(DECLARE_OPCODE_CASE) {
        MemoryAccessImmediate imm(decoder, pc + 1, UINT32_MAX,
                                  validate);
        (ios.MemoryAccess(imm), ...);
        return 1 + imm.length;
      }
      // clang-format on
      case kExprMemoryGrow:
      case kExprMemorySize: {
        MemoryIndexImmediate imm(decoder, pc + 1, validate);
        (ios.MemoryIndex(imm), ...);
        return 1 + imm.length;
      }
      /********** Prefixed opcodes **********/
      case kNumericPrefix: {
        uint32_t length;
        std::tie(opcode, length) =
            decoder->read_prefixed_opcode<ValidationTag>(pc);
        switch (opcode) {
          case kExprI32SConvertSatF32:
          case kExprI32UConvertSatF32:
          case kExprI32SConvertSatF64:
          case kExprI32UConvertSatF64:
          case kExprI64SConvertSatF32:
          case kExprI64UConvertSatF32:
          case kExprI64SConvertSatF64:
          case kExprI64UConvertSatF64:
            return length;
          case kExprMemoryInit: {
            MemoryInitImmediate imm(decoder, pc + length, validate);
            (ios.MemoryInit(imm), ...);
            return length + imm.length;
          }
          case kExprDataDrop: {
            IndexImmediate imm(decoder, pc + length, "data segment index",
                               validate);
            (ios.DataSegmentIndex(imm), ...);
            return length + imm.length;
          }
          case kExprMemoryCopy: {
            MemoryCopyImmediate imm(decoder, pc + length, validate);
            (ios.MemoryCopy(imm), ...);
            return length + imm.length;
          }
          case kExprMemoryFill: {
            MemoryIndexImmediate imm(decoder, pc + length, validate);
            (ios.MemoryIndex(imm), ...);
            return length + imm.length;
          }
          case kExprTableInit: {
            TableInitImmediate imm(decoder, pc + length, validate);
            (ios.TableInit(imm), ...);
            return length + imm.length;
          }
          case kExprElemDrop: {
            IndexImmediate imm(decoder, pc + length, "element segment index",
                               validate);
            (ios.ElemSegmentIndex(imm), ...);
            return length + imm.length;
          }
          case kExprTableCopy: {
            TableCopyImmediate imm(decoder, pc + length, validate);
            (ios.TableCopy(imm), ...);
            return length + imm.length;
          }
          case kExprTableGrow:
          case kExprTableSize:
          case kExprTableFill: {
            TableIndexImmediate imm(decoder, pc + length, validate);
            (ios.TableIndex(imm), ...);
            return length + imm.length;
          }
          case kExprF32LoadMemF16:
          case kExprF32StoreMemF16: {
            MemoryAccessImmediate imm(decoder, pc + length, UINT32_MAX,
                                      validate);
            (ios.MemoryAccess(imm), ...);
            return length + imm.length;
          }
          default:
            // This path is only possible if we are validating.
            V8_ASSUME(ValidationTag::validate);
            decoder->DecodeError(pc, "invalid numeric opcode");
            return length;
        }
      }
      case kAsmJsPrefix: {
        uint32_t length;
        std::tie(opcode, length) =
            decoder->read_prefixed_opcode<ValidationTag>(pc);
        switch (opcode) {
          FOREACH_ASMJS_COMPAT_OPCODE(DECLARE_OPCODE_CASE)
          return length;
          default:
            // This path is only possible if we are validating.
            V8_ASSUME(ValidationTag::validate);
            decoder->DecodeError(pc, "invalid opcode");
            return length;
        }
      }
      case kSimdPrefix: {
        uint32_t length;
        std::tie(opcode, length) =
            decoder->read_prefixed_opcode<ValidationTag>(pc);
        switch (opcode) {
          // clang-format off
          FOREACH_SIMD_0_OPERAND_OPCODE(DECLARE_OPCODE_CASE)
            return length;
          FOREACH_SIMD_1_OPERAND_OPCODE(DECLARE_OPCODE_CASE)
        if (sizeof...(ios) > 0) {
              SimdLaneImmediate lane_imm(decoder, pc + length, validate);
             (ios.SimdLane(lane_imm), ...);
            }
            return length + 1;
          FOREACH_SIMD_MEM_OPCODE(DECLARE_OPCODE_CASE) {
            MemoryAccessImmediate imm(decoder, pc + length, UINT32_MAX,
                                      validate);
            (ios.MemoryAccess(imm), ...);
            return length + imm.length;
          }
          FOREACH_SIMD_MEM_1_OPERAND_OPCODE(DECLARE_OPCODE_CASE) {
            MemoryAccessImmediate imm(
                decoder, pc + length, UINT32_MAX,
                validate);
        if (sizeof...(ios) > 0) {
              SimdLaneImmediate lane_imm(decoder,
                                         pc + length + imm.length, validate);
             (ios.MemoryAccess(imm), ...);
             (ios.SimdLane(lane_imm), ...);
            }
            // 1 more byte for lane index immediate.
            return length + imm.length + 1;
          }
          // clang-format on
          // Shuffles require a byte per lane, or 16 immediate bytes.
          case kExprS128Const:
          case kExprI8x16Shuffle:
            if (sizeof...(ios) > 0) {
              Simd128Immediate imm(decoder, pc + length, validate);
              (ios.S128Const(imm), ...);
            }
            return length + kSimd128Size;
          default:
            // This path is only possible if we are validating.
            V8_ASSUME(ValidationTag::validate);
            decoder->DecodeError(pc, "invalid SIMD opcode");
            return length;
        }
      }
      case kAtomicPrefix: {
        uint32_t length;
        std::tie(opcode, length) =
            decoder->read_prefixed_opcode<ValidationTag>(pc, "atomic_index");
        switch (opcode) {
          FOREACH_ATOMIC_OPCODE(DECLARE_OPCODE_CASE) {
            MemoryAccessImmediate imm(decoder, pc + length, UINT32_MAX,
                                      validate);
            (ios.MemoryAccess(imm), ...);
            return length + imm.length;
          }
          FOREACH_ATOMIC_0_OPERAND_OPCODE(DECLARE_OPCODE_CASE) {
            // One unused zero-byte.
            return length + 1;
          }
          case kExprStructAtomicGet:
          case kExprStructAtomicGetS:
          case kExprStructAtomicGetU:
          case kExprStructAtomicSet:
          case kExprStructAtomicAdd:
          case kExprStructAtomicSub:
          case kExprStructAtomicAnd:
          case kExprStructAtomicOr:
          case kExprStructAtomicXor:
          case kExprStructAtomicExchange:
          case kExprStructAtomicCompareExchange: {
            MemoryOrderImmediate memory_order(decoder, pc + length, validate);
            (ios.MemoryOrder(memory_order), ...);
            FieldImmediate field(decoder, pc + length + memory_order.length,
                                 validate);
            (ios.Field(field), ...);
            return length + memory_order.length + field.length;
          }
          case kExprArrayAtomicGet:
          case kExprArrayAtomicGetS:
          case kExprArrayAtomicGetU:
          case kExprArrayAtomicSet:
          case kExprArrayAtomicAdd:
          case kExprArrayAtomicSub:
          case kExprArrayAtomicAnd:
          case kExprArrayAtomicOr:
          case kExprArrayAtomicXor:
          case kExprArrayAtomicExchange:
          case kExprArrayAtomicCompareExchange: {
            MemoryOrderImmediate memory_order(decoder, pc + length, validate);
            (ios.MemoryOrder(memory_order), ...);
            ArrayIndexImmediate array(decoder, pc + length, validate);
            (ios.TypeIndex(array), ...);
            return length + memory_order.length + array.length;
          }
          default:
            // This path is only possible if we are validating.
            V8_ASSUME(ValidationTag::validate);
            decoder->DecodeError(pc, "invalid Atomics opcode");
            return length;
        }
      }
      case kGCPrefix: {
        uint32_t length;
        std::tie(opcode, length) =
            decoder->read_prefixed_opcode<ValidationTag>(pc, "gc_index");
        switch (opcode) {
          case kExprStructNew:
          case kExprStructNewDefault:
          case kExprRefGetDesc: {
            StructIndexImmediate imm(decoder, pc + length, validate);
            (ios.TypeIndex(imm), ...);
            return length + imm.length;
          }
          case kExprStructGet:
          case kExprStructGetS:
          case kExprStructGetU:
          case kExprStructSet: {
            FieldImmediate imm(decoder, pc + length, validate);
            (ios.Field(imm), ...);
            return length + imm.length;
          }
          case kExprArrayNew:
          case kExprArrayNewDefault:
          case kExprArrayGet:
          case kExprArrayGetS:
          case kExprArrayGetU:
          case kExprArraySet: {
            ArrayIndexImmediate imm(decoder, pc + length, validate);
            (ios.TypeIndex(imm), ...);
            return length + imm.length;
          }
          case kExprArrayNewFixed: {
            ArrayIndexImmediate array_imm(decoder, pc + length, validate);
            IndexImmediate length_imm(decoder, pc + length + array_imm.length,
                                      "array length", validate);
            (ios.TypeIndex(array_imm), ...);
            (ios.Length(length_imm), ...);
            return length + array_imm.length + length_imm.length;
          }
          case kExprArrayCopy: {
            ArrayIndexImmediate dst_imm(decoder, pc + length, validate);
            ArrayIndexImmediate src_imm(decoder, pc + length + dst_imm.length,
                                        validate);
            (ios.ArrayCopy(dst_imm, src_imm), ...);
            return length + dst_imm.length + src_imm.length;
          }
          case kExprArrayFill: {
            ArrayIndexImmediate imm(decoder, pc + length, validate);
            (ios.TypeIndex(imm), ...);
            return length + imm.length;
          }
          case kExprArrayNewData:
          case kExprArrayNewElem:
          case kExprArrayInitData:
          case kExprArrayInitElem: {
            ArrayIndexImmediate array_imm(decoder, pc + length, validate);
            IndexImmediate data_imm(decoder, pc + length + array_imm.length,
                                    "segment index", validate);
            (ios.TypeIndex(array_imm), ...);
            (ios.DataSegmentIndex(data_imm), ...);
            return length + array_imm.length + data_imm.length;
          }
          case kExprRefCast:
          case kExprRefCastNull:
          case kExprRefCastNop:
          case kExprRefCastDesc:
          case kExprRefCastDescNull:
          case kExprRefTest:
          case kExprRefTestNull: {
            HeapTypeImmediate imm(WasmEnabledFeatures::All(),
                                  decoder->detected_, decoder, pc + length,
                                  validate);
            (ios.HeapType(imm), ...);
            return length + imm.length;
          }
          case kExprBrOnCast:
          case kExprBrOnCastFail:
          case kExprBrOnCastDesc:
          case kExprBrOnCastDescFail: {
            BrOnCastImmediate flags_imm(decoder, pc + length, validate);
            BranchDepthImmediate branch(decoder, pc + length + flags_imm.length,
                                        validate);
            HeapTypeImmediate source_imm(
                WasmEnabledFeatures::All(), decoder->detected_, decoder,
                pc + length + flags_imm.length + branch.length, validate);
            HeapTypeImmediate target_imm(WasmEnabledFeatures::All(),
                                         decoder->detected_, decoder,
                                         pc + length + flags_imm.length +
                                             branch.length + source_imm.length,
                                         validate);
            (ios.BrOnCastFlags(flags_imm), ...);
            (ios.BranchDepth(branch), ...);
            // This code has grown historically (while the GC proposal's design
            // evolved), but it's convenient: for the text format, we want to
            // pretend that we have two ValueTypes; whereas the mjsunit
            // module builder format cares only about the encapsulated
            // HeapTypes (and the raw flags value, see callback above).
            (ios.ValueType(ValueType::RefMaybeNull(
                 source_imm.type,
                 flags_imm.flags.src_is_null ? kNullable : kNonNullable)),
             ...);
            (ios.ValueType(ValueType::RefMaybeNull(
                 target_imm.type,
                 flags_imm.flags.res_is_null ? kNullable : kNonNullable)),
             ...);
            return length + flags_imm.length + branch.length +
                   source_imm.length + target_imm.length;
          }
          case kExprRefI31:
          case kExprRefI31Shared:
          case kExprI31GetS:
          case kExprI31GetU:
          case kExprAnyConvertExtern:
          case kExprExternConvertAny:
          case kExprArrayLen:
            return length;
          case kExprStringNewUtf8:
          case kExprStringNewUtf8Try:
          case kExprStringNewLossyUtf8:
          case kExprStringNewWtf8:
          case kExprStringEncodeUtf8:
          case kExprStringEncodeLossyUtf8:
          case kExprStringEncodeWtf8:
          case kExprStringViewWtf8EncodeUtf8:
          case kExprStringViewWtf8EncodeLossyUtf8:
          case kExprStringViewWtf8EncodeWtf8:
          case kExprStringNewWtf16:
          case kExprStringEncodeWtf16:
          case kExprStringViewWtf16Encode: {
            MemoryIndexImmediate imm(decoder, pc + length, validate);
            (ios.MemoryIndex(imm), ...);
            return length + imm.length;
          }
          case kExprStringConst: {
            StringConstImmediate imm(decoder, pc + length, validate);
            (ios.StringConst(imm), ...);
            return length + imm.length;
          }
          case kExprStringMeasureUtf8:
          case kExprStringMeasureWtf8:
          case kExprStringNewUtf8Array:
          case kExprStringNewUtf8ArrayTry:
          case kExprStringNewLossyUtf8Array:
          case kExprStringNewWtf8Array:
          case kExprStringEncodeUtf8Array:
          case kExprStringEncodeLossyUtf8Array:
          case kExprStringEncodeWtf8Array:
          case kExprStringMeasureWtf16:
          case kExprStringConcat:
          case kExprStringEq:
          case kExprStringIsUSVSequence:
          case kExprStringAsWtf8:
          case kExprStringViewWtf8Advance:
          case kExprStringViewWtf8Slice:
          case kExprStringAsWtf16:
          case kExprStringViewWtf16Length:
          case kExprStringViewWtf16GetCodeunit:
          case kExprStringViewWtf16Slice:
          case kExprStringAsIter:
          case kExprStringViewIterNext:
          case kExprStringViewIterAdvance:
          case kExprStringViewIterRewind:
          case kExprStringViewIterSlice:
          case kExprStringNewWtf16Array:
          case kExprStringEncodeWtf16Array:
          case kExprStringCompare:
          case kExprStringFromCodePoint:
          case kExprStringHash:
            return length;
          default:
            // This path is only possible if we are validating.
            V8_ASSUME(ValidationTag::validate);
            decoder->DecodeError(pc, "invalid gc opcode");
            return length;
        }
      }
        // clang-format off
      // Prefixed opcodes (already handled, included here for completeness of
      // switch)
      FOREACH_SIMD_OPCODE(DECLARE_OPCODE_CASE)
      FOREACH_NUMERIC_OPCODE(DECLARE_OPCODE_CASE)
      FOREACH_ATOMIC_OPCODE(DECLARE_OPCODE_CASE)
      FOREACH_ATOMIC_0_OPERAND_OPCODE(DECLARE_OPCODE_CASE)
      FOREACH_GC_OPCODE(DECLARE_OPCODE_CASE)
      FOREACH_ATOMIC_GC_OPCODE(DECLARE_OPCODE_CASE)
      FOREACH_ASMJS_COMPAT_OPCODE(DECLARE_OPCODE_CASE)
        UNREACHABLE();
      // clang-format on
#undef DECLARE_OPCODE_CASE
    }
    // Invalid modules will reach this point.
    if (ValidationTag::validate) {
      decoder->DecodeError(pc, "invalid opcode");
    }
    return 1;
  }
References v8::internal::wasm::WasmEnabledFeatures::All(), DECLARE_OPCODE_CASE, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::detected_, v8::internal::wasm::BrOnCastImmediate::flags, FOREACH_ASMJS_COMPAT_OPCODE, FOREACH_ATOMIC_0_OPERAND_OPCODE, FOREACH_ATOMIC_GC_OPCODE, FOREACH_ATOMIC_OPCODE, FOREACH_GC_OPCODE, FOREACH_LOAD_MEM_OPCODE, FOREACH_NUMERIC_OPCODE, FOREACH_SIMD_0_OPERAND_OPCODE, FOREACH_SIMD_1_OPERAND_OPCODE, FOREACH_SIMD_MEM_1_OPERAND_OPCODE, FOREACH_SIMD_MEM_OPCODE, FOREACH_SIMD_OPCODE, FOREACH_SIMPLE_OPCODE, FOREACH_SIMPLE_PROTOTYPE_OPCODE, FOREACH_STORE_MEM_OPCODE, v8::internal::wasm::BranchTableIterator< ValidationTag >::has_next(), v8::internal::wasm::TryTableIterator< ValidationTag >::has_next(), v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::has_next(), v8::internal::wasm::kNonNullable, v8::internal::wasm::kNullable, v8::internal::kSimd128Size, v8::internal::length, v8::internal::wasm::ImmI32Immediate::length, v8::internal::wasm::ImmI64Immediate::length, v8::internal::wasm::BrOnCastImmediate::length, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::TypeIndexImmediate::length, v8::internal::wasm::SelectTypeImmediate::length, v8::internal::wasm::BlockTypeImmediate::length, v8::internal::wasm::BranchDepthImmediate::length, v8::internal::wasm::FieldImmediate::length, v8::internal::wasm::MemoryOrderImmediate::length, v8::internal::wasm::CallIndirectImmediate::length, v8::internal::wasm::BranchTableIterator< ValidationTag >::length(), v8::internal::wasm::TryTableIterator< ValidationTag >::length(), v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::length(), v8::internal::wasm::MemoryAccessImmediate::length, v8::internal::wasm::MemoryInitImmediate::length, v8::internal::wasm::MemoryCopyImmediate::length, v8::internal::wasm::TableInitImmediate::length, v8::internal::wasm::TableCopyImmediate::length, v8::internal::wasm::HeapTypeImmediate::length, v8::internal::wasm::StringConstImmediate::length, v8::internal::wasm::BranchTableIterator< ValidationTag >::next(), v8::internal::wasm::TryTableIterator< ValidationTag >::next(), v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::next(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::read_prefixed_opcode(), v8::internal::wasm::ValueType::RefMaybeNull(), v8::internal::wasm::BrOnCastFlags::res_is_null, v8::internal::wasm::BrOnCastFlags::src_is_null, v8::internal::wasm::HeapTypeImmediate::type, v8::internal::UNREACHABLE(), V8_ASSUME, and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::validate.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::AnalyzeLoopAssignment(), and v8::internal::wasm::OpcodeLength().
Validate() [1/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, ArrayIndexImmediate & imm) [inline]
Definition at line 2004 of file function-body-decoder-impl.h.
                                                             {
    if (!VALIDATE(module_->has_array(imm.index))) {
      DecodeError(pc, "invalid array index: %u", imm.index.index);
      return false;
    }
    imm.array_type = module_->array_type(imm.index);
    imm.shared = module_->type(imm.index).is_shared;
    return true;
  }
References v8::internal::wasm::ArrayIndexImmediate::array_type, v8::internal::wasm::WasmModule::array_type(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::WasmModule::has_array(), v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::ArrayIndexImmediate::shared, v8::internal::wasm::WasmModule::type(), and VALIDATE.
Validate() [2/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, BlockTypeImmediate & imm) [inline]
Definition at line 2134 of file function-body-decoder-impl.h.
                                                            {
    if (imm.sig.all().begin() == nullptr) {
      // Then use {sig_index} to initialize the signature.
      if (!VALIDATE(module_->has_signature(imm.sig_index))) {
        DecodeError(pc, "block type index %u is not a signature definition",
                    imm.sig_index);
        return false;
      }
      imm.sig = *module_->signature(imm.sig_index);
      if (imm.sig.parameter_count() > 0) {
        // Multi-value also allows blocks to return multiple values, but this
        // is already detected during signature decoding, so we don't need to
        // check again here.
        detected_->add_multi_value();
      }
    } else {
      // Then it's an MVP immediate with 0 parameters and 0-1 returns.
      DCHECK_EQ(0, imm.sig.parameter_count());
      DCHECK_GE(1, imm.sig.return_count());
      if (imm.sig.return_count()) {
        if (!ValidateValueType(pc, imm.sig.GetReturn(0))) return false;
        DCHECK_EQ(imm.sig.all().begin(), imm.single_return_sig_storage);
        value_type_reader::Populate(imm.single_return_sig_storage, module_);
      }
    }
    return true;
  }
References v8::internal::Signature< T >::all(), DCHECK_EQ, DCHECK_GE, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::detected_, v8::internal::Signature< T >::GetReturn(), v8::internal::wasm::WasmModule::has_signature(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::Signature< T >::parameter_count(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::value_type_reader::Populate(), v8::internal::Signature< T >::return_count(), v8::internal::wasm::BlockTypeImmediate::sig, v8::internal::wasm::BlockTypeImmediate::sig_index, v8::internal::wasm::WasmModule::signature(), v8::internal::wasm::BlockTypeImmediate::single_return_sig_storage, VALIDATE, and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateValueType().
Validate() [3/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, BranchDepthImmediate & imm, size_t control_depth) [inline]
Definition at line 2056 of file function-body-decoder-impl.h.
                                      {
    if (!VALIDATE(imm.depth < control_depth)) {
      DecodeError(pc, "invalid branch depth: %u", imm.depth);
      return false;
    }
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::BranchDepthImmediate::depth, v8::internal::wasm::Decoder::pc(), and VALIDATE.
Validate() [4/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, BranchTableImmediate & imm) [inline]
Definition at line 2065 of file function-body-decoder-impl.h.
                                                              {
    if (!VALIDATE(imm.table_count <= kV8MaxWasmFunctionBrTableSize)) {
      DecodeError(pc, "invalid table count (> max br_table size): %u",
                  imm.table_count);
      return false;
    }
    return checkAvailable(imm.table_count);
  }
References v8::internal::wasm::Decoder::checkAvailable(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::kV8MaxWasmFunctionBrTableSize, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::BranchTableImmediate::table_count, and VALIDATE.
Validate() [5/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, CallFunctionImmediate & imm) [inline]
Definition at line 2023 of file function-body-decoder-impl.h.
                                                               {
    size_t num_functions = module_->functions.size();
    if (!VALIDATE(imm.index < num_functions)) {
      DecodeError(pc, "function index #%u is out of bounds", imm.index);
      return false;
    }
    if (is_shared_ && !module_->function_is_shared(imm.index)) {
      DecodeError(pc, "cannot call non-shared function %u", imm.index);
      return false;
    }
    V8_ASSUME(imm.index < num_functions);
    imm.sig = module_->functions[imm.index].sig;
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::WasmModule::function_is_shared(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::is_shared_, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::CallFunctionImmediate::sig, V8_ASSUME, and VALIDATE.
Validate() [6/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, CallIndirectImmediate & imm) [inline]
Definition at line 2038 of file function-body-decoder-impl.h.
                                                               {
    if (!Validate(pc, imm.sig_imm)) return false;
    if (!Validate(pc + imm.sig_imm.length, imm.table_imm)) return false;
    ValueType table_type = imm.table_imm.table->type;
    if (!VALIDATE(table_type.ref_type_kind() == RefTypeKind::kFunction)) {
      DecodeError(
          pc, "call_indirect: immediate table #%u is not of a function type",
          imm.table_imm.index);
      return false;
    }
    // The type specified by the immediate does not need to have any static
    // relation (neither sub nor super) to the type of the table. The type
    // of the function will be checked at runtime.
    imm.sig = module_->signature(imm.sig_imm.index);
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::kFunction, v8::internal::wasm::TypeIndexImmediate::length, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::ValueTypeBase::ref_type_kind(), v8::internal::wasm::CallIndirectImmediate::sig, v8::internal::wasm::CallIndirectImmediate::sig_imm, v8::internal::wasm::WasmModule::signature(), v8::internal::wasm::TableIndexImmediate::table, v8::internal::wasm::CallIndirectImmediate::table_imm, v8::internal::wasm::WasmTable::type, VALIDATE, and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
Validate() [7/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, FieldImmediate & imm) [inline]
Definition at line 1993 of file function-body-decoder-impl.h.
                                                        {
    if (!Validate(pc, imm.struct_imm)) return false;
    if (!VALIDATE(imm.field_imm.index <
                  imm.struct_imm.struct_type->field_count())) {
      DecodeError(pc + imm.struct_imm.length, "invalid field index: %u",
                  imm.field_imm.index);
      return false;
    }
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::FieldImmediate::field_imm, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::TypeIndexImmediate::length, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::FieldImmediate::struct_imm, v8::internal::wasm::StructIndexImmediate::struct_type, VALIDATE, and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
Validate() [8/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, GlobalIndexImmediate & imm) [inline]
Definition at line 1943 of file function-body-decoder-impl.h.
                                                              {
    // We compare with the current size of the globals vector. This is important
    // if we are decoding a constant expression in the global section.
    size_t num_globals = module_->globals.size();
    if (!VALIDATE(imm.index < num_globals)) {
      DecodeError(pc, "Invalid global index: %u", imm.index);
      return false;
    }
    V8_ASSUME(imm.index < num_globals);
    imm.global = &module_->globals[imm.index];
    if (!VALIDATE(!is_shared_ || imm.global->shared)) {
      DecodeError(pc, "Cannot access non-shared global %d in a shared %s",
                  imm.index,
                  decoding_mode == kConstantExpression ? "constant expression"
                                                       : "function");
      return false;
    }
    if constexpr (decoding_mode == kConstantExpression) {
      if (!VALIDATE(!imm.global->mutability)) {
        this->DecodeError(pc,
                          "mutable globals cannot be used in constant "
                          "expressions");
        return false;
      }
    }
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::GlobalIndexImmediate::global, v8::internal::wasm::WasmModule::globals, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::is_shared_, v8::internal::wasm::kConstantExpression, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::WasmGlobal::mutability, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::WasmGlobal::shared, V8_ASSUME, and VALIDATE.
Validate() [9/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, HeapTypeImmediate & imm) [inline]
Definition at line 2348 of file function-body-decoder-impl.h.
                                                           {
    if (!VALIDATE(ValidateHeapType(pc, imm.type))) return false;
    value_type_reader::Populate(&imm.type, module_);
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::value_type_reader::Populate(), v8::internal::wasm::HeapTypeImmediate::type, VALIDATE, and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateHeapType().
Validate() [10/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, MemoryAccessImmediate & imm) [inline]
Definition at line 2185 of file function-body-decoder-impl.h.
                                                               {
    size_t num_memories = module_->memories.size();
    if (!VALIDATE(imm.mem_index < num_memories)) {
      DecodeError(pc,
                  "memory index %u exceeds number of declared memories (%zu)",
                  imm.mem_index, num_memories);
      return false;
    }
    if (!VALIDATE(this->module_->memories[imm.mem_index].is_memory64() ||
                  imm.offset <= kMaxUInt32)) {
      this->DecodeError(pc, "memory offset outside 32-bit range: %" PRIu64,
                        imm.offset);
      return false;
    }
    V8_ASSUME(imm.mem_index < num_memories);
    imm.memory = this->module_->memories.data() + imm.mem_index;
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::kMaxUInt32, v8::internal::wasm::MemoryAccessImmediate::mem_index, v8::internal::wasm::WasmModule::memories, v8::internal::wasm::MemoryAccessImmediate::memory, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::MemoryAccessImmediate::offset, v8::internal::wasm::Decoder::pc(), V8_ASSUME, and VALIDATE.
Validate() [11/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, MemoryCopyImmediate & imm) [inline]
Definition at line 2211 of file function-body-decoder-impl.h.
                                                             {
    return Validate(pc, imm.memory_src) &&
           Validate(pc + imm.memory_src.length, imm.memory_dst);
  }
References v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::MemoryCopyImmediate::memory_dst, v8::internal::wasm::MemoryCopyImmediate::memory_src, v8::internal::wasm::Decoder::pc(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
Validate() [12/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, MemoryIndexImmediate & imm) [inline]
Definition at line 2162 of file function-body-decoder-impl.h.
                                                              {
    size_t num_memories = module_->memories.size();
    if (imm.index > 0 || imm.length > 1) {
      this->detected_->add_multi_memory();
      if (v8_flags.wasm_jitless) {
        DecodeError(pc, "Multiple memories not supported in Wasm jitless mode");
        return false;
      }
    }
    if (!VALIDATE(imm.index < num_memories)) {
      DecodeError(pc,
                  "memory index %u exceeds number of declared memories (%zu)",
                  imm.index, num_memories);
      return false;
    }
    V8_ASSUME(imm.index < num_memories);
    imm.memory = this->module_->memories.data() + imm.index;
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::detected_, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::WasmModule::memories, v8::internal::wasm::MemoryIndexImmediate::memory, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), V8_ASSUME, v8::internal::v8_flags, and VALIDATE.
Validate() [13/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, MemoryInitImmediate & imm) [inline]
Definition at line 2206 of file function-body-decoder-impl.h.
                                                             {
    return ValidateDataSegment(pc, imm.data_segment) &&
           Validate(pc + imm.data_segment.length, imm.memory);
  }
References v8::internal::wasm::MemoryInitImmediate::data_segment, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::MemoryInitImmediate::memory, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateDataSegment().
Validate() [14/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, SelectTypeImmediate & imm) [inline]
Definition at line 2342 of file function-body-decoder-impl.h.
                                                             {
    if (!VALIDATE(ValidateValueType(pc, imm.type))) return false;
    value_type_reader::Populate(&imm.type, module_);
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::value_type_reader::Populate(), v8::internal::wasm::SelectTypeImmediate::type, VALIDATE, and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateValueType().
Validate() [15/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, SigIndexImmediate & imm) [inline]
Definition at line 1973 of file function-body-decoder-impl.h.
                                                           {
    if (!VALIDATE(module_->has_signature(imm.index))) {
      DecodeError(pc, "invalid signature index: %u", imm.index.index);
      return false;
    }
    imm.sig = module_->signature(imm.index);
    imm.shared = module_->type(imm.index).is_shared;
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::WasmModule::has_signature(), v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::SigIndexImmediate::shared, v8::internal::wasm::SigIndexImmediate::sig, v8::internal::wasm::WasmModule::signature(), v8::internal::wasm::WasmModule::type(), and VALIDATE.
Validate() [16/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, Simd128Immediate & imm) [inline]
Definition at line 2121 of file function-body-decoder-impl.h.
                                                          {
    uint8_t max_lane = 0;
    for (uint32_t i = 0; i < kSimd128Size; ++i) {
      max_lane = std::max(max_lane, imm.value[i]);
    }
    // Shuffle indices must be in [0..31] for a 16 lane shuffle.
    if (!VALIDATE(max_lane < 2 * kSimd128Size)) {
      DecodeError(pc, "invalid shuffle mask");
      return false;
    }
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kSimd128Size, v8::internal::wasm::Decoder::pc(), VALIDATE, and v8::internal::wasm::Simd128Immediate::value.
Validate() [17/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, StringConstImmediate & imm) [inline]
Definition at line 2243 of file function-body-decoder-impl.h.
                                                              {
    if (!VALIDATE(imm.index < module_->stringref_literals.size())) {
      DecodeError(pc, "Invalid string literal index: %u", imm.index);
      return false;
    }
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::StringConstImmediate::index, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::WasmModule::stringref_literals, and VALIDATE.
Validate() [18/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, StructIndexImmediate & imm) [inline]
Definition at line 1983 of file function-body-decoder-impl.h.
                                                              {
    if (!VALIDATE(module_->has_struct(imm.index))) {
      DecodeError(pc, "invalid struct index: %u", imm.index.index);
      return false;
    }
    imm.struct_type = module_->struct_type(imm.index);
    imm.shared = module_->type(imm.index).is_shared;
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::WasmModule::has_struct(), v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::StructIndexImmediate::shared, v8::internal::wasm::StructIndexImmediate::struct_type, v8::internal::wasm::WasmModule::struct_type(), v8::internal::wasm::WasmModule::type(), and VALIDATE.
Validate() [19/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, TableCopyImmediate & imm) [inline]
Definition at line 2231 of file function-body-decoder-impl.h.
                                                            {
    if (!Validate(pc, imm.table_src)) return false;
    if (!Validate(pc + imm.table_src.length, imm.table_dst)) return false;
    ValueType src_type = imm.table_src.table->type;
    if (!VALIDATE(IsSubtypeOf(src_type, imm.table_dst.table->type, module_))) {
      DecodeError(pc, "table %u is not a super-type of %s", imm.table_dst.index,
                  src_type.name().c_str());
      return false;
    }
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::ValueTypeBase::name(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::TableIndexImmediate::table, v8::internal::wasm::TableCopyImmediate::table_dst, v8::internal::wasm::TableCopyImmediate::table_src, v8::internal::wasm::WasmTable::type, VALIDATE, and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
Validate() [20/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, TableIndexImmediate & imm) [inline]
Definition at line 2251 of file function-body-decoder-impl.h.
                                                             {
    if (imm.index > 0 || imm.length > 1) {
      this->detected_->add_reftypes();
    }
    size_t num_tables = module_->tables.size();
    if (!VALIDATE(imm.index < num_tables)) {
      DecodeError(pc, "table index %u exceeds number of tables (%zu)",
                  imm.index, num_tables);
      return false;
    }
    imm.table = this->module_->tables.data() + imm.index;
    if (!VALIDATE(!is_shared_ || imm.table->shared)) {
      DecodeError(pc,
                  "cannot reference non-shared table %u from shared function",
                  imm.index);
      return false;
    }
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::detected_, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::is_shared_, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::WasmTable::shared, v8::internal::wasm::TableIndexImmediate::table, v8::internal::wasm::WasmModule::tables, and VALIDATE.
Validate() [21/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, TableInitImmediate & imm) [inline]
Definition at line 2216 of file function-body-decoder-impl.h.
                                                            {
    if (!ValidateElementSegment(pc, imm.element_segment)) return false;
    if (!Validate(pc + imm.element_segment.length, imm.table)) {
      return false;
    }
    ValueType elem_type =
        module_->elem_segments[imm.element_segment.index].type;
    if (!VALIDATE(IsSubtypeOf(elem_type, imm.table.table->type, module_))) {
      DecodeError(pc, "table %u is not a super-type of %s", imm.table.index,
                  elem_type.name().c_str());
      return false;
    }
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::WasmModule::elem_segments, v8::internal::wasm::TableInitImmediate::element_segment, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::ValueTypeBase::name(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::TableIndexImmediate::table, v8::internal::wasm::TableInitImmediate::table, v8::internal::wasm::WasmTable::type, VALIDATE, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateElementSegment().
Validate() [22/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, TagIndexImmediate & imm) [inline]
Definition at line 1932 of file function-body-decoder-impl.h.
                                                           {
    size_t num_tags = module_->tags.size();
    if (!VALIDATE(imm.index < num_tags)) {
      DecodeError(pc, "Invalid tag index: %u", imm.index);
      return false;
    }
    V8_ASSUME(imm.index < num_tags);
    imm.tag = &module_->tags[imm.index];
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::TagIndexImmediate::tag, v8::internal::wasm::WasmModule::tags, V8_ASSUME, and VALIDATE.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
Validate() [23/23]
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate (const uint8_t * pc, WasmOpcode opcode, SimdLaneImmediate & imm) [inline]
Definition at line 2074 of file function-body-decoder-impl.h.
                                                                              {
    uint8_t num_lanes = 0;
    switch (opcode) {
      case kExprF64x2ExtractLane:
      case kExprF64x2ReplaceLane:
      case kExprI64x2ExtractLane:
      case kExprI64x2ReplaceLane:
      case kExprS128Load64Lane:
      case kExprS128Store64Lane:
        num_lanes = 2;
        break;
      case kExprF32x4ExtractLane:
      case kExprF32x4ReplaceLane:
      case kExprI32x4ExtractLane:
      case kExprI32x4ReplaceLane:
      case kExprS128Load32Lane:
      case kExprS128Store32Lane:
        num_lanes = 4;
        break;
      case kExprF16x8ExtractLane:
      case kExprF16x8ReplaceLane:
      case kExprI16x8ExtractLaneS:
      case kExprI16x8ExtractLaneU:
      case kExprI16x8ReplaceLane:
      case kExprS128Load16Lane:
      case kExprS128Store16Lane:
        num_lanes = 8;
        break;
      case kExprI8x16ExtractLaneS:
      case kExprI8x16ExtractLaneU:
      case kExprI8x16ReplaceLane:
      case kExprS128Load8Lane:
      case kExprS128Store8Lane:
        num_lanes = 16;
        break;
      default:
        UNREACHABLE();
        break;
    }
    if (!VALIDATE(imm.lane >= 0 && imm.lane < num_lanes)) {
      DecodeError(pc, "invalid lane index");
      return false;
    } else {
      return true;
    }
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::SimdLaneImmediate::lane, v8::internal::wasm::Decoder::pc(), v8::internal::UNREACHABLE(), and VALIDATE.
ValidateCont()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateCont (const uint8_t * pc, ContIndexImmediate & imm) [inline]
Definition at line 2315 of file function-body-decoder-impl.h.
                                                                {
    if (!VALIDATE(module_->has_cont_type(imm.index))) {
      DecodeError(pc, "invalid cont index: %u", imm.index.index);
      return false;
    }
    imm.cont_type = module_->cont_type(imm.index);
    imm.shared = module_->type(imm.index).is_shared;
    return true;
  }
References v8::internal::wasm::ContIndexImmediate::cont_type, v8::internal::wasm::WasmModule::cont_type(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::WasmModule::has_cont_type(), v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::ContIndexImmediate::shared, v8::internal::wasm::WasmModule::type(), and VALIDATE.
ValidateDataSegment()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateDataSegment (const uint8_t * pc, IndexImmediate & imm) [inline]
Definition at line 2326 of file function-body-decoder-impl.h.
                                                                   {
    if (!VALIDATE(imm.index < module_->num_declared_data_segments)) {
      DecodeError(pc, "invalid data segment index: %u", imm.index);
      return false;
    }
    // TODO(14616): Data segments aren't available during eager validation.
    // Discussion: github.com/WebAssembly/shared-everything-threads/issues/83
    if (!VALIDATE(!is_shared_ || module_->data_segments[imm.index].shared)) {
      DecodeError(
          pc, "cannot refer to non-shared segment %u from a shared function",
          imm.index);
      return false;
    }
    return true;
  }
References v8::internal::wasm::WasmModule::data_segments, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::is_shared_, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::WasmModule::num_declared_data_segments, v8::internal::wasm::Decoder::pc(), and VALIDATE.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
ValidateElementSegment()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateElementSegment (const uint8_t * pc, IndexImmediate & imm) [inline]
Definition at line 2275 of file function-body-decoder-impl.h.
                                                                      {
    size_t num_elem_segments = module_->elem_segments.size();
    if (!VALIDATE(imm.index < num_elem_segments)) {
      DecodeError(pc, "invalid element segment index: %u", imm.index);
      return false;
    }
    V8_ASSUME(imm.index < num_elem_segments);
    if (!VALIDATE(!is_shared_ || module_->elem_segments[imm.index].shared)) {
      DecodeError(
          pc,
          "cannot reference non-shared element segment %u from shared function",
          imm.index);
      return false;
    }
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::WasmModule::elem_segments, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::is_shared_, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), V8_ASSUME, and VALIDATE.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
ValidateFunction()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateFunction (const uint8_t * pc, IndexImmediate & imm) [inline]
Definition at line 2300 of file function-body-decoder-impl.h.
                                                                {
    size_t num_functions = module_->functions.size();
    if (!VALIDATE(imm.index < num_functions)) {
      DecodeError(pc, "function index #%u is out of bounds", imm.index);
      return false;
    }
    V8_ASSUME(imm.index < num_functions);
    if (decoding_mode == kFunctionBody &&
        !VALIDATE(module_->functions[imm.index].declared)) {
      DecodeError(pc, "undeclared reference to function #%u", imm.index);
      return false;
    }
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::kFunctionBody, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), V8_ASSUME, and VALIDATE.
ValidateHeapType()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateHeapType (const uint8_t * pc, HeapType type) [inline]
Definition at line 2359 of file function-body-decoder-impl.h.
                                                          {
    return value_type_reader::ValidateHeapType<ValidationTag>(this, pc, module_,
                                                              type);
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
ValidateLocal()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateLocal (const uint8_t * pc, IndexImmediate & imm) [inline]
Definition at line 2292 of file function-body-decoder-impl.h.
                                                             {
    if (!VALIDATE(imm.index < num_locals())) {
      DecodeError(pc, "invalid local index: %u", imm.index);
      return false;
    }
    return true;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::num_locals(), v8::internal::wasm::Decoder::pc(), and VALIDATE.
ValidateValueType()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateValueType (const uint8_t * pc, ValueType type) [inline]
Definition at line 2354 of file function-body-decoder-impl.h.
                                                            {
    return value_type_reader::ValidateValueType<ValidationTag>(this, pc,
                                                               module_, type);
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::Decoder::pc(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
zone()
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
Zone* v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::zone () const [inline]
Definition at line 1761 of file function-body-decoder-impl.h.
{ return zone_; }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::zone_.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::AnalyzeLoopAssignment(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::BlockPhis(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildWasmCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetDataViewByteLength(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetStringIndexOf(), v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Loop(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TraceMemoryOperation(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
Member Data Documentation
current_inst_trace_
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
const std::pair<uint32_t, uint32_t>* v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::current_inst_trace_
Definition at line 2985 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::WasmDecoder().
detected_
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
WasmDetectedFeatures* v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::detected_
Definition at line 2982 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
enabled_
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
const WasmEnabledFeatures v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::enabled_
Definition at line 2981 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayInitSegment(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayNewSegment(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DataDrop(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall().
is_shared_
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::is_shared_
Definition at line 2984 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateDataSegment(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateElementSegment().
local_types_
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
ValueType* v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::local_types_ = nullptr
Definition at line 2977 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::DecodeLocalDecls(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::local_type(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::local_types(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StartFunctionBody().
module_
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
const WasmModule* v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_
Definition at line 2980 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayInitSegment(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNew(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNewFixed(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayNewFixed(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayNewImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayNewSegment(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastFailImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildImportedFunctionTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallDirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::CanReturnCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DataDrop(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ElemDrop(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetExactness(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetLiftoffFrameSize(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::GlobalGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GlobalGet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::GlobalSet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GlobalSet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintSignature(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefAsNonNull(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefCastImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefFunc(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefTest(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ReturnCallRef(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RttCanon(), v8::internal::wasm::TurboshaftGraphBuildingInterface::should_inline(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::StringConst(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructNew(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructNewImpl(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateCont(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateDataSegment(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateElementSegment(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateFunction(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateHeapType(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::ValidateValueType(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::WasmDecoder(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
num_locals_
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
uint32_t v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::num_locals_ = 0
Definition at line 2978 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::DecodeLocalDecls(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::local_type(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::local_types(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::num_locals().
sig_
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
const FunctionSig* v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::sig_
Definition at line 2983 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::CanReturnCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::DoReturn(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ReturnImpl(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StartFunction(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StartFunctionBody(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TraceFunctionExit().
validate
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
constexpr ValidationTag v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::validate = {} [static], [constexpr]
Definition at line 2973 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::AnalyzeLoopAssignment(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength().
zone_
template<typename ValidationTag , DecodingMode decoding_mode = kFunctionBody>
Zone* const v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::zone_
Definition at line 2975 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTable(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildWasmMaybeReturnCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructNew(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructNewDefault(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Throw(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::zone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/function-body-decoder-impl.h