v8::internal::maglev::GapMove Class Reference
#include <maglev-ir.h>
Public Member Functions
GapMove (uint64_t bitfield, compiler::AllocatedOperand source, compiler::AllocatedOperand target)
compiler::AllocatedOperand source () const
compiler::AllocatedOperand target () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Private Types
using Base = FixedInputNodeT< 0, GapMove >
Private Attributes
compiler::AllocatedOperand source_
compiler::AllocatedOperand target_
Additional Inherited Members
Detailed Description
Definition at line 9758 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::GapMove::Base = FixedInputNodeT<0, GapMove> [private]
Definition at line 9759 of file maglev-ir.h.
Constructor & Destructor Documentation
GapMove()
v8::internal::maglev::GapMove::GapMove (uint64_t bitfield, compiler::AllocatedOperand source, compiler::AllocatedOperand target) [inline]
Definition at line 9762 of file maglev-ir.h.
      : Base(bitfield), source_(source), target_(target) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::GapMove::GenerateCode (MaglevAssembler * , const ProcessingState &)
PrintParams()
void v8::internal::maglev::GapMove::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8294 of file maglev-ir.cc.
                                                                     {
  os << "(" << source() << " → " << target() << ")";
}
References source(), and target().
SetValueLocationConstraints()
void v8::internal::maglev::GapMove::SetValueLocationConstraints ()
source()
compiler::AllocatedOperand v8::internal::maglev::GapMove::source () const [inline]
Definition at line 9766 of file maglev-ir.h.
{ return source_; }
Referenced by PrintParams().
target()
compiler::AllocatedOperand v8::internal::maglev::GapMove::target () const [inline]
Definition at line 9767 of file maglev-ir.h.
{ return target_; }
Referenced by PrintParams().
Member Data Documentation
source_
compiler::AllocatedOperand v8::internal::maglev::GapMove::source_ [private]
Definition at line 9774 of file maglev-ir.h.
target_
compiler::AllocatedOperand v8::internal::maglev::GapMove::target_ [private]
Definition at line 9775 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc