v8::internal::wasm::WasmEHDataGenerator Class Reference
#include <wasm-interpreter.h>
Public Member Functions
WasmEHDataGenerator ()
void AddTryBlock (BlockIndex try_block_index, BlockIndex parent_or_matching_try_block_index, BlockIndex ancestor_try_block_index)
void AddCatchBlock (BlockIndex catch_block_index, int tag_index, uint32_t first_param_slot_offset, uint32_t first_param_ref_stack_index, CodeOffset code_offset)
void AddDelegatedBlock (BlockIndex delegated_try_block_index)
BlockIndex EndTryCatchBlocks (BlockIndex block_index, CodeOffset code_offset)
void RecordPotentialExceptionThrowingInstruction (WasmOpcode opcode, CodeOffset code_offset)
BlockIndex GetCurrentTryBlockIndex () const
Private Attributes
BlockIndex current_try_block_index_
Additional Inherited Members
Detailed Description
Definition at line 1320 of file wasm-interpreter.h.
Constructor & Destructor Documentation
WasmEHDataGenerator()
v8::internal::wasm::WasmEHDataGenerator::WasmEHDataGenerator () [inline]
Definition at line 1322 of file wasm-interpreter.h.
: current_try_block_index_(-1) {}
Member Function Documentation
AddCatchBlock()
void v8::internal::wasm::WasmEHDataGenerator::AddCatchBlock (BlockIndex catch_block_index, int tag_index, uint32_t first_param_slot_offset, uint32_t first_param_ref_stack_index, CodeOffset code_offset)
Definition at line 7260 of file wasm-interpreter.cc.
                                                                {
  DCHECK_EQ(catch_blocks_.find(catch_block_index), catch_blocks_.end());
  catch_blocks_.insert(
      {catch_block_index,
       CatchBlock{current_try_block_index_, first_param_slot_offset,
                  first_param_ref_stack_index}});
  auto it = try_blocks_.find(current_try_block_index_);
  DCHECK_NE(it, try_blocks_.end());
  it->second.catch_handlers.emplace_back(
      CatchHandler{catch_block_index, tag_index, code_offset});
}
References v8::internal::wasm::WasmEHData::catch_blocks_, current_try_block_index_, DCHECK_EQ, DCHECK_NE, and v8::internal::wasm::WasmEHData::try_blocks_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction().
AddDelegatedBlock()
void v8::internal::wasm::WasmEHDataGenerator::AddDelegatedBlock (BlockIndex delegated_try_block_index)
Definition at line 7277 of file wasm-interpreter.cc.
                                         {
  auto it = try_blocks_.find(current_try_block_index_);
  DCHECK_NE(it, try_blocks_.end());
  TryBlock& try_block = it->second;
  DCHECK(try_block.catch_handlers.empty());
  try_block.SetDelegated(delegate_try_block_index);
}
References v8::internal::wasm::WasmEHData::TryBlock::catch_handlers, current_try_block_index_, v8::internal::DCHECK(), DCHECK_NE, v8::internal::wasm::WasmEHData::TryBlock::SetDelegated(), and v8::internal::wasm::WasmEHData::try_blocks_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction().
AddTryBlock()
void v8::internal::wasm::WasmEHDataGenerator::AddTryBlock (BlockIndex try_block_index, BlockIndex parent_or_matching_try_block_index, BlockIndex ancestor_try_block_index)
Definition at line 7250 of file wasm-interpreter.cc.
                                         {
  DCHECK_EQ(try_blocks_.find(try_block_index), try_blocks_.end());
  try_blocks_.insert(
      {try_block_index,
       TryBlock{parent_or_matching_try_block_index, ancestor_try_block_index}});
  current_try_block_index_ = try_block_index;
}
References current_try_block_index_, DCHECK_EQ, and v8::internal::wasm::WasmEHData::try_blocks_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction().
EndTryCatchBlocks()
WasmEHData::BlockIndex v8::internal::wasm::WasmEHDataGenerator::EndTryCatchBlocks (WasmEHData::BlockIndex block_index, CodeOffset code_offset)
Definition at line 7286 of file wasm-interpreter.cc.
                                                              {
  WasmEHData::BlockIndex try_block_index = GetTryBranchOf(block_index);
  if (try_block_index < 0) {
    // No catch/catch_all blocks.
    try_block_index = block_index;
  }
  const auto& try_it = try_blocks_.find(try_block_index);
  DCHECK_NE(try_it, try_blocks_.end());
  try_it->second.end_instruction_code_offset = code_offset;
  current_try_block_index_ = try_it->second.parent_or_matching_try_block;
  return try_block_index;
}
References current_try_block_index_, DCHECK_NE, v8::internal::wasm::WasmEHData::GetTryBranchOf(), and v8::internal::wasm::WasmEHData::try_blocks_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::EndBlock().
GetCurrentTryBlockIndex()
BlockIndex v8::internal::wasm::WasmEHDataGenerator::GetCurrentTryBlockIndex () const [inline]
Definition at line 1336 of file wasm-interpreter.h.
                                             {
    return current_try_block_index_;
  }
References current_try_block_index_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::BeginBlock(), and v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction().
RecordPotentialExceptionThrowingInstruction()
void v8::internal::wasm::WasmEHDataGenerator::RecordPotentialExceptionThrowingInstruction (WasmOpcode opcode, CodeOffset code_offset)
Definition at line 7301 of file wasm-interpreter.cc.
                                               {
  if (current_try_block_index_ < 0) {
    return; // Not inside a try block.
  }
  BlockIndex try_block_index = current_try_block_index_;
  const auto& try_it = try_blocks_.find(current_try_block_index_);
  DCHECK_NE(try_it, try_blocks_.end());
  const TryBlock& try_block = try_it->second;
  bool inside_catch_handler = !try_block.catch_handlers.empty();
  if (inside_catch_handler) {
    // If we are throwing from inside a catch block, the exception should only
    // be caught by the catch handler of an ancestor try block.
    try_block_index = try_block.ancestor_try_index;
    if (try_block_index < 0) return;
  }
  code_trycatch_map_[code_offset] = try_block_index;
}
References v8::internal::wasm::WasmEHData::TryBlock::ancestor_try_index, v8::internal::wasm::WasmEHData::TryBlock::catch_handlers, v8::internal::wasm::WasmEHData::code_trycatch_map_, current_try_block_index_, DCHECK_NE, and v8::internal::wasm::WasmEHData::try_blocks_.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction().
Member Data Documentation
current_try_block_index_
BlockIndex v8::internal::wasm::WasmEHDataGenerator::current_try_block_index_ [private]
Definition at line 1341 of file wasm-interpreter.h.
Referenced by AddCatchBlock(), AddDelegatedBlock(), AddTryBlock(), EndTryCatchBlocks(), GetCurrentTryBlockIndex(), and RecordPotentialExceptionThrowingInstruction().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.cc