v8_inspector::V8ProfilerAgentImpl Class Reference
#include <v8-profiler-agent-impl.h>
Classes
class ProfileDescriptor
Public Member Functions
V8ProfilerAgentImpl (V8InspectorSessionImpl *, protocol::FrontendChannel *, protocol::DictionaryValue *state)
~V8ProfilerAgentImpl () override
V8ProfilerAgentImpl (const V8ProfilerAgentImpl &)=delete
V8ProfilerAgentImpl & operator= (const V8ProfilerAgentImpl &)=delete
bool enabled () const
void restore ()
Response enable () override
Response disable () override
Response setSamplingInterval (int) override
Response start () override
Response stop (std::unique_ptr< protocol::Profiler::Profile > *) override
Response startPreciseCoverage (std::optional< bool > binary, std::optional< bool > detailed, std::optional< bool > allow_triggered_updates, double *out_timestamp) override
Response stopPreciseCoverage () override
Response takePreciseCoverage (std::unique_ptr< protocol::Array< protocol::Profiler::ScriptCoverage >> *out_result, double *out_timestamp) override
Response getBestEffortCoverage (std::unique_ptr< protocol::Array< protocol::Profiler::ScriptCoverage >> *out_result) override
void consoleProfile (const String16 &title)
void consoleProfileEnd (const String16 &title)
void triggerPreciseCoverageDeltaUpdate (const String16 &occasion)
Private Member Functions
String16 nextProfileId ()
void startProfiling (const String16 &title)
std::unique_ptr< protocol::Profiler::Profile > stopProfiling (const String16 &title, bool serialize)
Private Attributes
V8InspectorSessionImpl * m_session
v8::Isolate * m_isolate
v8::CpuProfiler * m_profiler = nullptr
protocol::DictionaryValue * m_state
protocol::Profiler::Frontend m_frontend
bool m_enabled = false
bool m_recordingCPUProfile = false
std::vector< ProfileDescriptor > m_startedProfiles
String16 m_frontendInitiatedProfileId
int m_startedProfilesCount = 0
Detailed Description
Definition at line 26 of file v8-profiler-agent-impl.h.
Constructor & Destructor Documentation
V8ProfilerAgentImpl() [1/2]
v8_inspector::V8ProfilerAgentImpl::V8ProfilerAgentImpl (V8InspectorSessionImpl * session, protocol::FrontendChannel * frontendChannel, protocol::DictionaryValue * state)
Definition at line 169 of file v8-profiler-agent-impl.cc.
    : m_session(session),
      m_isolate(m_session->inspector()->isolate()),
      m_state(state),
      m_frontend(frontendChannel) {}
 V8ProfilerAgentImpl()
v8_inspector::V8ProfilerAgentImpl::~V8ProfilerAgentImpl () [override]
Definition at line 177 of file v8-profiler-agent-impl.cc.
                                          {
  if (m_profiler) m_profiler->Dispose();
}
References v8::CpuProfiler::Dispose(), and m_profiler.
V8ProfilerAgentImpl() [2/2]
v8_inspector::V8ProfilerAgentImpl::V8ProfilerAgentImpl (const V8ProfilerAgentImpl &) [delete]
Member Function Documentation
consoleProfile()
void v8_inspector::V8ProfilerAgentImpl::consoleProfile (const String16 & title)
Definition at line 181 of file v8-profiler-agent-impl.cc.
                                                              {
  if (!m_enabled) return;
  String16 id = nextProfileId();
  m_startedProfiles.push_back(ProfileDescriptor(id, title));
  startProfiling(id);
  m_frontend.consoleProfileStarted(
      id, currentDebugLocation(m_session->inspector()), title);
}
References v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::currentDebugLocation(), v8_inspector::V8InspectorSessionImpl::inspector(), m_enabled, m_frontend, m_session, m_startedProfiles, nextProfileId(), and startProfiling().
consoleProfileEnd()
void v8_inspector::V8ProfilerAgentImpl::consoleProfileEnd (const String16 & title)
Definition at line 190 of file v8-profiler-agent-impl.cc.
                                                                 {
  if (!m_enabled) return;
  String16 id;
  String16 resolvedTitle;
  // Take last started profile if no title was passed.
  if (title.isEmpty()) {
    if (m_startedProfiles.empty()) return;
    id = m_startedProfiles.back().m_id;
    resolvedTitle = m_startedProfiles.back().m_title;
    m_startedProfiles.pop_back();
  } else {
    for (size_t i = 0; i < m_startedProfiles.size(); i++) {
      if (m_startedProfiles[i].m_title == title) {
        resolvedTitle = title;
        id = m_startedProfiles[i].m_id;
        m_startedProfiles.erase(m_startedProfiles.begin() + i);
        break;
      }
    }
    if (id.isEmpty()) return;
  }
  std::unique_ptr<protocol::Profiler::Profile> profile =
      stopProfiling(id, true);
  if (!profile) return;
  m_frontend.consoleProfileFinished(
      id, currentDebugLocation(m_session->inspector()), std::move(profile),
      resolvedTitle);
}
References v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::currentDebugLocation(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8_inspector::V8InspectorSessionImpl::inspector(), v8_inspector::String16::isEmpty(), m_enabled, m_frontend, m_session, m_startedProfiles, and stopProfiling().
disable()
Response v8_inspector::V8ProfilerAgentImpl::disable () [override]
Definition at line 228 of file v8-profiler-agent-impl.cc.
                                      {
  if (m_enabled) {
    for (size_t i = m_startedProfiles.size(); i > 0; --i)
      stopProfiling(m_startedProfiles[i - 1].m_id, false);
    m_startedProfiles.clear();
    stop(nullptr);
    stopPreciseCoverage();
    DCHECK(!m_profiler);
    m_enabled = false;
    m_state->setBoolean(ProfilerAgentState::profilerEnabled, false);
  }
  return Response::Success();
}
References DCHECK, m_enabled, m_profiler, m_startedProfiles, m_state, v8_inspector::ProfilerAgentState::profilerEnabled, stop(), stopPreciseCoverage(), and stopProfiling().
enable()
Response v8_inspector::V8ProfilerAgentImpl::enable () [override]
Definition at line 219 of file v8-profiler-agent-impl.cc.
                                     {
  if (!m_enabled) {
    m_enabled = true;
    m_state->setBoolean(ProfilerAgentState::profilerEnabled, true);
  }
  return Response::Success();
}
References m_enabled, m_state, and v8_inspector::ProfilerAgentState::profilerEnabled.
enabled()
bool v8_inspector::V8ProfilerAgentImpl::enabled () const [inline]
Definition at line 34 of file v8-profiler-agent-impl.h.
{ return m_enabled; }
References m_enabled.
getBestEffortCoverage()
Response v8_inspector::V8ProfilerAgentImpl::getBestEffortCoverage (std::unique_ptr< protocol::Array< protocol::Profiler::ScriptCoverage >> * out_result) [override]
Definition at line 444 of file v8-profiler-agent-impl.cc.
                    {
  v8::HandleScope handle_scope(m_isolate);
  v8::debug::Coverage coverage =
      v8::debug::Coverage::CollectBestEffort(m_isolate);
  return coverageToProtocol(m_session->inspector(), coverage, out_result);
}
References v8::debug::Coverage::CollectBestEffort(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), v8_inspector::V8InspectorSessionImpl::inspector(), m_isolate, and m_session.
nextProfileId()
String16 v8_inspector::V8ProfilerAgentImpl::nextProfileId () [private]
Definition at line 453 of file v8-profiler-agent-impl.cc.
                                            {
  return String16::fromInteger(
      v8::base::Relaxed_AtomicIncrement(&s_lastProfileId, 1));
}
References v8_inspector::String16::fromInteger(), v8::base::Relaxed_AtomicIncrement(), and v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::s_lastProfileId.
Referenced by consoleProfile(), and start().
operator=()
V8ProfilerAgentImpl& v8_inspector::V8ProfilerAgentImpl::operator= (const V8ProfilerAgentImpl &) [delete]
restore()
void v8_inspector::V8ProfilerAgentImpl::restore ()
Definition at line 252 of file v8-profiler-agent-impl.cc.
                                  {
  DCHECK(!m_enabled);
  if (m_state->booleanProperty(ProfilerAgentState::profilerEnabled, false)) {
    m_enabled = true;
    DCHECK(!m_profiler);
    if (m_state->booleanProperty(ProfilerAgentState::userInitiatedProfiling,
                                 false)) {
      start();
    }
    if (m_state->booleanProperty(ProfilerAgentState::preciseCoverageStarted,
                                 false)) {
      bool callCount = m_state->booleanProperty(
          ProfilerAgentState::preciseCoverageCallCount, false);
      bool detailed = m_state->booleanProperty(
          ProfilerAgentState::preciseCoverageDetailed, false);
      bool updatesAllowed = m_state->booleanProperty(
          ProfilerAgentState::preciseCoverageAllowTriggeredUpdates, false);
      double timestamp;
      startPreciseCoverage(std::optional<bool>(callCount),
                           std::optional<bool>(detailed),
                           std::optional<bool>(updatesAllowed), &timestamp);
    }
  }
}
References DCHECK, m_enabled, m_profiler, m_state, v8_inspector::ProfilerAgentState::preciseCoverageAllowTriggeredUpdates, v8_inspector::ProfilerAgentState::preciseCoverageCallCount, v8_inspector::ProfilerAgentState::preciseCoverageDetailed, v8_inspector::ProfilerAgentState::preciseCoverageStarted, v8_inspector::ProfilerAgentState::profilerEnabled, start(), startPreciseCoverage(), and v8_inspector::ProfilerAgentState::userInitiatedProfiling.
setSamplingInterval()
Response v8_inspector::V8ProfilerAgentImpl::setSamplingInterval (int interval) [override]
Definition at line 243 of file v8-profiler-agent-impl.cc.
                                                              {
  if (m_profiler) {
    return Response::ServerError(
        "Cannot change sampling interval when profiling.");
  }
  m_state->setInteger(ProfilerAgentState::samplingInterval, interval);
  return Response::Success();
}
References m_profiler, m_state, and v8_inspector::ProfilerAgentState::samplingInterval.
start()
Response v8_inspector::V8ProfilerAgentImpl::start () [override]
Definition at line 277 of file v8-profiler-agent-impl.cc.
                                    {
  if (m_recordingCPUProfile) return Response::Success();
  if (!m_enabled) return Response::ServerError("Profiler is not enabled");
  m_recordingCPUProfile = true;
  m_frontendInitiatedProfileId = nextProfileId();
  startProfiling(m_frontendInitiatedProfileId);
  m_state->setBoolean(ProfilerAgentState::userInitiatedProfiling, true);
  return Response::Success();
}
References m_enabled, m_frontendInitiatedProfileId, m_recordingCPUProfile, m_state, nextProfileId(), startProfiling(), and v8_inspector::ProfilerAgentState::userInitiatedProfiling.
Referenced by restore().
startPreciseCoverage()
Response v8_inspector::V8ProfilerAgentImpl::startPreciseCoverage (std::optional< bool > binary, std::optional< bool > detailed, std::optional< bool > allow_triggered_updates, double * out_timestamp) [override]
Definition at line 304 of file v8-profiler-agent-impl.cc.
                                                                    {
  if (!m_enabled) return Response::ServerError("Profiler is not enabled");
  *out_timestamp = v8::base::TimeTicks::Now().since_origin().InSecondsF();
  bool callCountValue = callCount.value_or(false);
  bool detailedValue = detailed.value_or(false);
  bool allowTriggeredUpdatesValue = allowTriggeredUpdates.value_or(false);
  m_state->setBoolean(ProfilerAgentState::preciseCoverageStarted, true);
  m_state->setBoolean(ProfilerAgentState::preciseCoverageCallCount,
                      callCountValue);
  m_state->setBoolean(ProfilerAgentState::preciseCoverageDetailed,
                      detailedValue);
  m_state->setBoolean(ProfilerAgentState::preciseCoverageAllowTriggeredUpdates,
                      allowTriggeredUpdatesValue);
  // BlockCount is a superset of PreciseCount. It includes block-granularity
  // coverage data if it exists (at the time of writing, that's the case for
  // each function recompiled after the BlockCount mode has been set); and
  // function-granularity coverage data otherwise.
  using C = v8::debug::Coverage;
  using Mode = v8::debug::CoverageMode;
  Mode mode = callCountValue
                  ? (detailedValue ? Mode::kBlockCount : Mode::kPreciseCount)
                  : (detailedValue ? Mode::kBlockBinary : Mode::kPreciseBinary);
  C::SelectMode(m_isolate, mode);
  return Response::Success();
}
References v8::base::TimeDelta::InSecondsF(), m_enabled, m_isolate, m_state, mode(), v8::base::TimeTicks::Now(), v8_inspector::ProfilerAgentState::preciseCoverageAllowTriggeredUpdates, v8_inspector::ProfilerAgentState::preciseCoverageCallCount, v8_inspector::ProfilerAgentState::preciseCoverageDetailed, v8_inspector::ProfilerAgentState::preciseCoverageStarted, and v8::base::time_internal::TimeBase< TimeClass >::since_origin().
Referenced by restore().
startProfiling()
void v8_inspector::V8ProfilerAgentImpl::startProfiling (const String16 & title) [private]
Definition at line 458 of file v8-profiler-agent-impl.cc.
                                                              {
  v8::HandleScope handleScope(m_isolate);
  if (!m_startedProfilesCount) {
    DCHECK(!m_profiler);
    m_profiler = v8::CpuProfiler::New(m_isolate);
    int interval =
        m_state->integerProperty(ProfilerAgentState::samplingInterval, 0);
    if (interval) m_profiler->SetSamplingInterval(interval);
  }
  ++m_startedProfilesCount;
  m_profiler->StartProfiling(toV8String(m_isolate, title), true);
}
References DCHECK, m_isolate, m_profiler, m_startedProfilesCount, m_state, v8::CpuProfiler::New(), v8_inspector::ProfilerAgentState::samplingInterval, v8::CpuProfiler::SetSamplingInterval(), v8::CpuProfiler::StartProfiling(), and v8_inspector::toV8String().
Referenced by consoleProfile(), and start().
stop()
Response v8_inspector::V8ProfilerAgentImpl::stop (std::unique_ptr< protocol::Profiler::Profile > * profile) [override]
Definition at line 287 of file v8-profiler-agent-impl.cc.
                                                     {
  if (!m_recordingCPUProfile) {
    return Response::ServerError("No recording profiles found");
  }
  m_recordingCPUProfile = false;
  std::unique_ptr<protocol::Profiler::Profile> cpuProfile =
      stopProfiling(m_frontendInitiatedProfileId, !!profile);
  if (profile) {
    *profile = std::move(cpuProfile);
    if (!*profile) return Response::ServerError("Profile is not found");
  }
  m_frontendInitiatedProfileId = String16();
  m_state->setBoolean(ProfilerAgentState::userInitiatedProfiling, false);
  return Response::Success();
}
References m_frontendInitiatedProfileId, m_recordingCPUProfile, m_state, stopProfiling(), and v8_inspector::ProfilerAgentState::userInitiatedProfiling.
Referenced by disable().
stopPreciseCoverage()
Response v8_inspector::V8ProfilerAgentImpl::stopPreciseCoverage () [override]
Definition at line 332 of file v8-profiler-agent-impl.cc.
                                                  {
  if (!m_enabled) return Response::ServerError("Profiler is not enabled");
  m_state->setBoolean(ProfilerAgentState::preciseCoverageStarted, false);
  m_state->setBoolean(ProfilerAgentState::preciseCoverageCallCount, false);
  m_state->setBoolean(ProfilerAgentState::preciseCoverageDetailed, false);
  v8::debug::Coverage::SelectMode(m_isolate,
                                  v8::debug::CoverageMode::kBestEffort);
  return Response::Success();
}
References v8::debug::kBestEffort, m_enabled, m_isolate, m_state, v8_inspector::ProfilerAgentState::preciseCoverageCallCount, v8_inspector::ProfilerAgentState::preciseCoverageDetailed, v8_inspector::ProfilerAgentState::preciseCoverageStarted, and v8::debug::Coverage::SelectMode().
Referenced by disable().
stopProfiling()
std::unique_ptr< protocol::Profiler::Profile > v8_inspector::V8ProfilerAgentImpl::stopProfiling (const String16 & title, bool serialize) [private]
Definition at line 471 of file v8-profiler-agent-impl.cc.
                                           {
  v8::HandleScope handleScope(m_isolate);
  v8::CpuProfile* profile =
      m_profiler->StopProfiling(toV8String(m_isolate, title));
  std::unique_ptr<protocol::Profiler::Profile> result;
  if (profile) {
    if (serialize) result = createCPUProfile(m_session->inspector(), profile);
    profile->Delete();
  }
  --m_startedProfilesCount;
  if (!m_startedProfilesCount) {
    m_profiler->Dispose();
    m_profiler = nullptr;
  }
  return result;
}
References v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::createCPUProfile(), v8::CpuProfile::Delete(), v8::CpuProfiler::Dispose(), v8_inspector::V8InspectorSessionImpl::inspector(), m_isolate, m_profiler, m_session, m_startedProfilesCount, v8::base::internal::result, v8::CpuProfiler::StopProfiling(), and v8_inspector::toV8String().
Referenced by consoleProfileEnd(), disable(), and stop().
takePreciseCoverage()
Response v8_inspector::V8ProfilerAgentImpl::takePreciseCoverage (std::unique_ptr< protocol::Array< protocol::Profiler::ScriptCoverage >> * out_result, double * out_timestamp) [override]
Definition at line 411 of file v8-profiler-agent-impl.cc.
                           {
  if (!m_state->booleanProperty(ProfilerAgentState::preciseCoverageStarted,
                                false)) {
    return Response::ServerError("Precise coverage has not been started.");
  }
  v8::HandleScope handle_scope(m_isolate);
  v8::debug::Coverage coverage = v8::debug::Coverage::CollectPrecise(m_isolate);
  *out_timestamp = v8::base::TimeTicks::Now().since_origin().InSecondsF();
  return coverageToProtocol(m_session->inspector(), coverage, out_result);
}
References v8::debug::Coverage::CollectPrecise(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), v8::base::TimeDelta::InSecondsF(), v8_inspector::V8InspectorSessionImpl::inspector(), m_isolate, m_session, m_state, v8::base::TimeTicks::Now(), v8_inspector::ProfilerAgentState::preciseCoverageStarted, and v8::base::time_internal::TimeBase< TimeClass >::since_origin().
triggerPreciseCoverageDeltaUpdate()
void v8_inspector::V8ProfilerAgentImpl::triggerPreciseCoverageDeltaUpdate (const String16 & occasion)
Definition at line 425 of file v8-profiler-agent-impl.cc.
                              {
  if (!m_state->booleanProperty(ProfilerAgentState::preciseCoverageStarted,
                                false)) {
    return;
  }
  if (!m_state->booleanProperty(
          ProfilerAgentState::preciseCoverageAllowTriggeredUpdates, false)) {
    return;
  }
  v8::HandleScope handle_scope(m_isolate);
  v8::debug::Coverage coverage = v8::debug::Coverage::CollectPrecise(m_isolate);
  std::unique_ptr<protocol::Array<protocol::Profiler::ScriptCoverage>>
      out_result;
  coverageToProtocol(m_session->inspector(), coverage, &out_result);
  double now = v8::base::TimeTicks::Now().since_origin().InSecondsF();
  m_frontend.preciseCoverageDeltaUpdate(now, occasion, std::move(out_result));
}
References v8::debug::Coverage::CollectPrecise(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), v8::base::TimeDelta::InSecondsF(), v8_inspector::V8InspectorSessionImpl::inspector(), m_frontend, m_isolate, m_session, m_state, v8::base::TimeTicks::Now(), v8_inspector::ProfilerAgentState::preciseCoverageAllowTriggeredUpdates, v8_inspector::ProfilerAgentState::preciseCoverageStarted, and v8::base::time_internal::TimeBase< TimeClass >::since_origin().
Member Data Documentation
m_enabled
bool v8_inspector::V8ProfilerAgentImpl::m_enabled = false [private]
Definition at line 73 of file v8-profiler-agent-impl.h.
Referenced by consoleProfile(), consoleProfileEnd(), disable(), enable(), enabled(), restore(), start(), startPreciseCoverage(), and stopPreciseCoverage().
m_frontend
protocol::Profiler::Frontend v8_inspector::V8ProfilerAgentImpl::m_frontend [private]
Definition at line 72 of file v8-profiler-agent-impl.h.
Referenced by consoleProfile(), consoleProfileEnd(), and triggerPreciseCoverageDeltaUpdate().
m_frontendInitiatedProfileId
String16 v8_inspector::V8ProfilerAgentImpl::m_frontendInitiatedProfileId [private]
Definition at line 77 of file v8-profiler-agent-impl.h.
Referenced by start(), and stop().
m_isolate
v8::Isolate* v8_inspector::V8ProfilerAgentImpl::m_isolate [private]
Definition at line 69 of file v8-profiler-agent-impl.h.
Referenced by getBestEffortCoverage(), startPreciseCoverage(), startProfiling(), stopPreciseCoverage(), stopProfiling(), takePreciseCoverage(), and triggerPreciseCoverageDeltaUpdate().
m_profiler
v8::CpuProfiler* v8_inspector::V8ProfilerAgentImpl::m_profiler = nullptr [private]
Definition at line 70 of file v8-profiler-agent-impl.h.
Referenced by disable(), restore(), setSamplingInterval(), startProfiling(), stopProfiling(), and ~V8ProfilerAgentImpl().
m_recordingCPUProfile
bool v8_inspector::V8ProfilerAgentImpl::m_recordingCPUProfile = false [private]
Definition at line 74 of file v8-profiler-agent-impl.h.
Referenced by start(), and stop().
m_session
V8InspectorSessionImpl* v8_inspector::V8ProfilerAgentImpl::m_session [private]
Definition at line 68 of file v8-profiler-agent-impl.h.
Referenced by consoleProfile(), consoleProfileEnd(), getBestEffortCoverage(), stopProfiling(), takePreciseCoverage(), and triggerPreciseCoverageDeltaUpdate().
m_startedProfiles
std::vector<ProfileDescriptor> v8_inspector::V8ProfilerAgentImpl::m_startedProfiles [private]
Definition at line 76 of file v8-profiler-agent-impl.h.
Referenced by consoleProfile(), consoleProfileEnd(), and disable().
m_startedProfilesCount
int v8_inspector::V8ProfilerAgentImpl::m_startedProfilesCount = 0 [private]
Definition at line 78 of file v8-profiler-agent-impl.h.
Referenced by startProfiling(), and stopProfiling().
m_state
protocol::DictionaryValue* v8_inspector::V8ProfilerAgentImpl::m_state [private]
Definition at line 71 of file v8-profiler-agent-impl.h.
Referenced by disable(), enable(), restore(), setSamplingInterval(), start(), startPreciseCoverage(), startProfiling(), stop(), stopPreciseCoverage(), takePreciseCoverage(), and triggerPreciseCoverageDeltaUpdate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-profiler-agent-impl.h
/mnt/V8SourceCode/src/inspector/v8-profiler-agent-impl.cc