v8::internal::RootsSerializer Class Reference
#include <roots-serializer.h>
Public Member Functions
RootsSerializer (Isolate *isolate, Snapshot::SerializerFlags flags, RootIndex first_root_to_be_serialized)
RootsSerializer (const RootsSerializer &)=delete
RootsSerializer & operator= (const RootsSerializer &)=delete
bool can_be_rehashed () const
bool root_has_been_serialized (RootIndex root_index) const
bool IsRootAndHasBeenSerialized (Tagged< HeapObject > obj) const
Protected Member Functions
void CheckRehashability (Tagged< HeapObject > obj)
int SerializeInObjectCache (Handle< HeapObject > object)
bool object_cache_empty ()
Private Member Functions
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) override
void Synchronize (VisitorSynchronization::SyncTag tag) override
Private Attributes
const RootIndex first_root_to_be_serialized_
std::bitset< RootsTable::kEntriesCount > root_has_been_serialized_
ObjectCacheIndexMap object_cache_index_map_
bool can_be_rehashed_
Additional Inherited Members
Detailed Description
Definition at line 23 of file roots-serializer.h.
Constructor & Destructor Documentation
RootsSerializer() [1/2]
v8::internal::RootsSerializer::RootsSerializer (Isolate * isolate, Snapshot::SerializerFlags flags, RootIndex first_root_to_be_serialized)
Definition at line 14 of file roots-serializer.cc.
    : Serializer(isolate, flags),
      first_root_to_be_serialized_(first_root_to_be_serialized),
      object_cache_index_map_(isolate->heap()),
      can_be_rehashed_(true) {
  for (size_t i = 0; i < static_cast<size_t>(first_root_to_be_serialized);
       ++i) {
    root_has_been_serialized_[i] = true;
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and root_has_been_serialized_.
RootsSerializer() [2/2]
v8::internal::RootsSerializer::RootsSerializer (const RootsSerializer &) [delete]
Member Function Documentation
can_be_rehashed()
bool v8::internal::RootsSerializer::can_be_rehashed () const [inline]
Definition at line 32 of file roots-serializer.h.
{ return can_be_rehashed_; }
Referenced by v8::internal::Snapshot::Create().
CheckRehashability()
void v8::internal::RootsSerializer::CheckRehashability (Tagged< HeapObject > obj) [protected]
Definition at line 60 of file roots-serializer.cc.
                                                               {
  if (!can_be_rehashed_) return;
  if (!obj->NeedsRehashing(cage_base())) return;
  if (obj->CanBeRehashed(cage_base())) return;
  can_be_rehashed_ = false;
}
References v8::internal::Serializer::cage_base(), and can_be_rehashed_.
Referenced by v8::internal::ReadOnlySerializer::Serialize(), v8::internal::StartupSerializer::SerializeObjectImpl(), and v8::internal::SharedHeapSerializer::SerializeObjectImpl().
IsRootAndHasBeenSerialized()
bool v8::internal::RootsSerializer::IsRootAndHasBeenSerialized (Tagged< HeapObject > obj) const [inline]
Definition at line 37 of file roots-serializer.h.
                                                                {
    RootIndex root_index;
    return root_index_map()->Lookup(obj, &root_index) &&
           root_has_been_serialized(root_index);
  }
Referenced by v8::internal::StartupSerializer::SerializeObjectImpl(), and v8::internal::SharedHeapSerializer::SerializeObjectImpl().
object_cache_empty()
bool v8::internal::RootsSerializer::object_cache_empty () [inline], [protected]
Definition at line 49 of file roots-serializer.h.
{ return object_cache_index_map_.size() == 0; }
operator=()
RootsSerializer& v8::internal::RootsSerializer::operator= (const RootsSerializer &) [delete]
root_has_been_serialized()
bool v8::internal::RootsSerializer::root_has_been_serialized (RootIndex root_index) const [inline]
Definition at line 33 of file roots-serializer.h.
                                                            {
    return root_has_been_serialized_.test(static_cast<size_t>(root_index));
  }
SerializeInObjectCache()
int v8::internal::RootsSerializer::SerializeInObjectCache (Handle< HeapObject > object) [protected]
Definition at line 27 of file roots-serializer.cc.
                                                                          {
  int index;
  if (!object_cache_index_map_.LookupOrInsert(*heap_object, &index)) {
    // This object is not part of the object cache yet. Add it to the cache so
    // we can refer to it via cache index from the delegating snapshot.
    SerializeObject(heap_object, SlotType::kAnySlot);
  }
  return index;
}
References v8::internal::index, v8::internal::SerializerDeserializer::kAnySlot, v8::internal::ObjectCacheIndexMap::LookupOrInsert(), object_cache_index_map_, and v8::internal::Serializer::SerializeObject().
Referenced by v8::internal::SharedHeapSerializer::ReconstructSharedHeapObjectCacheForTesting(), v8::internal::SharedHeapSerializer::SerializeUsingSharedHeapObjectCache(), and v8::internal::StartupSerializer::SerializeUsingStartupObjectCache().
Synchronize()
void v8::internal::RootsSerializer::Synchronize (VisitorSynchronization::SyncTag tag) [override], [private], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 37 of file roots-serializer.cc.
                                                                   {
  sink_.Put(kSynchronize, "Synchronize");
}
References v8::internal::SerializerDeserializer::kSynchronize, v8::internal::SnapshotByteSink::Put(), and v8::internal::Serializer::sink_.
VisitRootPointers()
void v8::internal::RootsSerializer::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [override], [private], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 41 of file roots-serializer.cc.
                                                            {
  RootsTable& roots_table = isolate()->roots_table();
  if (start ==
      roots_table.begin() + static_cast<int>(first_root_to_be_serialized_)) {
    // Serializing the root list needs special handling:
    // - Only root list elements that have been fully serialized can be
    // referenced using kRootArray bytecodes.
    for (FullObjectSlot current = start; current < end; ++current) {
      SerializeRootObject(current);
      size_t root_index = current - roots_table.begin();
      root_has_been_serialized_.set(root_index);
    }
  } else {
    Serializer::VisitRootPointers(root, description, start, end);
  }
}
References v8::internal::RootsTable::begin(), v8::internal::compiler::end(), first_root_to_be_serialized_, v8::internal::Serializer::isolate(), root_has_been_serialized_, v8::internal::Isolate::roots_table(), v8::internal::Serializer::SerializeRootObject(), and v8::internal::Serializer::VisitRootPointers().
Referenced by v8::internal::SharedHeapSerializer::SerializeStringTable().
Member Data Documentation
can_be_rehashed_
bool v8::internal::RootsSerializer::can_be_rehashed_ [private]
Definition at line 61 of file roots-serializer.h.
Referenced by CheckRehashability().
first_root_to_be_serialized_
const RootIndex v8::internal::RootsSerializer::first_root_to_be_serialized_ [private]
Definition at line 56 of file roots-serializer.h.
Referenced by VisitRootPointers().
object_cache_index_map_
ObjectCacheIndexMap v8::internal::RootsSerializer::object_cache_index_map_ [private]
Definition at line 58 of file roots-serializer.h.
Referenced by SerializeInObjectCache().
root_has_been_serialized_
std::bitset<RootsTable::kEntriesCount> v8::internal::RootsSerializer::root_has_been_serialized_ [private]
Definition at line 57 of file roots-serializer.h.
Referenced by RootsSerializer(), and VisitRootPointers().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/roots-serializer.h
/mnt/V8SourceCode/src/snapshot/roots-serializer.cc