v8::internal::FPURegister Class Reference
#include <register-loong64.h>
Public Member Functions
FPURegister low () const
FPURegister low () const
FPURegister high () const
MSARegister toW () const
FPURegister low () const
FPURegister high () const
VRegister toV () const
Private Member Functions
constexpr FPURegister (int code)
constexpr FPURegister (int code)
constexpr FPURegister (int code)
Friends
class RegisterBase
Additional Inherited Members
Detailed Description
Definition at line 145 of file register-loong64.h.
Constructor & Destructor Documentation
FPURegister() [1/3]
constexpr v8::internal::FPURegister::FPURegister (int code) [inline], [explicit], [constexpr], [private]
Definition at line 151 of file register-loong64.h.
: RegisterBase(code) {}
FPURegister() [2/3]
constexpr v8::internal::FPURegister::FPURegister (int code) [inline], [explicit], [constexpr], [private]
Definition at line 182 of file register-mips64.h.
: RegisterBase(code) {}
FPURegister() [3/3]
constexpr v8::internal::FPURegister::FPURegister (int code) [inline], [explicit], [constexpr], [private]
Definition at line 235 of file register-riscv.h.
: RegisterBase(code) {}
Member Function Documentation
high() [1/2]
FPURegister v8::internal::FPURegister::high () const [inline]
Definition at line 171 of file register-mips64.h.
                           {
    // TODO(plind): Create DCHECK for FR=0 mode. This usage illegal in FR=1.
    // Find high reg of a Doubel-reg pair, which is reg + 1.
    DCHECK_EQ(code() % 2, 0); // Specified Double reg must be even.
    return FPURegister::from_code(code() + 1);
  }
References v8::internal::RegisterBase< FPURegister, kDoubleAfterLast >::code(), DCHECK_EQ, and v8::internal::RegisterBase< FPURegister, kDoubleAfterLast >::from_code().
high() [2/2]
FPURegister v8::internal::FPURegister::high () const [inline]
Definition at line 219 of file register-riscv.h.
                           {
    // TODO(plind): Create DCHECK for FR=0 mode. This usage illegal in FR=1.
    // Find high reg of a Doubel-reg pair, which is reg + 1.
    return FPURegister::from_code(code() + 1);
  }
References v8::internal::RegisterBase< FPURegister, kDoubleAfterLast >::code(), and v8::internal::RegisterBase< FPURegister, kDoubleAfterLast >::from_code().
low() [1/3]
FPURegister v8::internal::FPURegister::low () const [inline]
Definition at line 147 of file register-loong64.h.
{ return FPURegister::from_code(code()); }
References v8::internal::RegisterBase< FPURegister, kDoubleAfterLast >::code(), and v8::internal::RegisterBase< FPURegister, kDoubleAfterLast >::from_code().
low() [2/3]
FPURegister v8::internal::FPURegister::low () const [inline]
Definition at line 165 of file register-mips64.h.
                          {
    // TODO(plind): Create DCHECK for FR=0 mode. This usage suspect for FR=1.
    // Find low reg of a Double-reg pair, which is the reg itself.
    DCHECK_EQ(code() % 2, 0); // Specified Double reg must be even.
    return FPURegister::from_code(code());
  }
References v8::internal::RegisterBase< FPURegister, kDoubleAfterLast >::code(), DCHECK_EQ, and v8::internal::RegisterBase< FPURegister, kDoubleAfterLast >::from_code().
low() [3/3]
FPURegister v8::internal::FPURegister::low () const [inline]
Definition at line 214 of file register-riscv.h.
                          {
    // TODO(plind): Create DCHECK for FR=0 mode. This usage suspect for FR=1.
    // Find low reg of a Double-reg pair, which is the reg itself.
    return FPURegister::from_code(code());
  }
References v8::internal::RegisterBase< FPURegister, kDoubleAfterLast >::code(), and v8::internal::RegisterBase< FPURegister, kDoubleAfterLast >::from_code().
toV()
VRegister v8::internal::FPURegister::toV () const [inline]
Definition at line 228 of file register-riscv.h.
                        {
    DCHECK(base::IsInRange(static_cast<int>(code()), 0, kVRAfterLast - 1));
    return VRegister(code());
  }
References v8::internal::RegisterBase< FPURegister, kDoubleAfterLast >::code(), v8::internal::DCHECK(), and v8::internal::kVRAfterLast.
toW()
MSARegister v8::internal::FPURegister::toW () const [inline]
Definition at line 178 of file register-mips64.h.
{ return MSARegister::from_code(code()); }
References v8::internal::RegisterBase< FPURegister, kDoubleAfterLast >::code(), and v8::internal::RegisterBase< MSARegister, kMsaAfterLast >::from_code().
Friends And Related Function Documentation
RegisterBase
RegisterBase [friend]
Definition at line 150 of file register-loong64.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/loong64/register-loong64.h
/mnt/V8SourceCode/src/codegen/mips64/register-mips64.h
/mnt/V8SourceCode/src/codegen/riscv/register-riscv.h