v8::internal::Utf8DecoderBase< Decoder > Class Template Reference
#include <unicode-decoder.h>
Public Types
enum class Encoding : uint8_t { kAscii
, kLatin1
, kUtf16
, kInvalid
 }
Public Member Functions
bool is_invalid () const
bool is_ascii () const
bool is_one_byte () const
int utf16_length () const
int non_ascii_start () const
template<typename Char >
void Decode (Char *out, base::Vector< const uint8_t > data)
Protected Member Functions
Utf8DecoderBase (base::Vector< const uint8_t > data)
Protected Attributes
Encoding encoding_
int non_ascii_start_
int utf16_length_
Detailed Description
template<class Decoder>
class v8::internal::Utf8DecoderBase< Decoder >
Definition at line 52 of file unicode-decoder.h.
Member Enumeration Documentation
Encoding
template<class Decoder >
enum v8::internal::Utf8DecoderBase::Encoding : uint8_t [strong]
Enumerator
kAscii
kLatin1
kUtf16
kInvalid
Definition at line 54 of file unicode-decoder.h.
: uint8_t { kAscii, kLatin1, kUtf16, kInvalid };
Constructor & Destructor Documentation
Utf8DecoderBase()
template<class Decoder >
v8::internal::Utf8DecoderBase< Decoder >::Utf8DecoderBase (base::Vector< const uint8_t > data) [explicit], [protected]
Definition at line 60 of file unicode-decoder.cc.
    : encoding_(Encoding::kAscii),
      non_ascii_start_(NonAsciiStart(data.begin(), data.length())),
      utf16_length_(non_ascii_start_) {
  using Traits = DecoderTraits<Decoder>;
  if (non_ascii_start_ == data.length()) return;
  bool is_one_byte = true;
  auto state = Traits::DfaDecoder::kAccept;
  uint32_t current = 0;
  uint32_t previous = 0;
  const uint8_t* cursor = data.begin() + non_ascii_start_;
  const uint8_t* end = data.begin() + data.length();
  while (cursor < end) {
    if (V8_LIKELY(*cursor <= unibrow::Utf8::kMaxOneByteChar &&
                  state == Traits::DfaDecoder::kAccept)) {
      DCHECK_EQ(0u, current);
      DCHECK(!Traits::IsInvalidSurrogatePair(previous, *cursor));
      previous = *cursor;
      utf16_length_++;
      cursor++;
      continue;
    }
    auto previous_state = state;
    Traits::DfaDecoder::Decode(*cursor, &state, &current);
    if (state < Traits::DfaDecoder::kAccept) {
      DCHECK_EQ(state, Traits::DfaDecoder::kReject);
      if (Traits::kAllowIncompleteSequences) {
        state = Traits::DfaDecoder::kAccept;
        static_assert(unibrow::Utf8::kBadChar > unibrow::Latin1::kMaxChar);
        is_one_byte = false;
        utf16_length_++;
        previous = unibrow::Utf8::kBadChar;
        current = 0;
        // If we were trying to continue a multibyte sequence, try this byte
        // again.
        if (previous_state != Traits::DfaDecoder::kAccept) continue;
      } else {
        encoding_ = Encoding::kInvalid;
        return;
      }
    } else if (state == Traits::DfaDecoder::kAccept) {
      if (Traits::IsInvalidSurrogatePair(previous, current)) {
        encoding_ = Encoding::kInvalid;
        return;
      }
      is_one_byte = is_one_byte && current <= unibrow::Latin1::kMaxChar;
      utf16_length_++;
      if (current > unibrow::Utf16::kMaxNonSurrogateCharCode) utf16_length_++;
      previous = current;
      current = 0;
    }
    cursor++;
  }
  if (state == Traits::DfaDecoder::kAccept) {
    encoding_ = is_one_byte ? Encoding::kLatin1 : Encoding::kUtf16;
  } else if (Traits::kAllowIncompleteSequences) {
    static_assert(unibrow::Utf8::kBadChar > unibrow::Latin1::kMaxChar);
    encoding_ = Encoding::kUtf16;
    utf16_length_++;
  } else {
    encoding_ = Encoding::kInvalid;
  }
}
References v8::internal::Utf8DecoderBase< Decoder >::is_one_byte(), v8::base::Vector< T >::length(), and v8::internal::Utf8DecoderBase< Decoder >::non_ascii_start_.
Member Function Documentation
Decode()
template<class Decoder >
template<typename Char >
void v8::internal::Utf8DecoderBase< Decoder >::Decode (Char * out, base::Vector< const uint8_t > data)
Definition at line 130 of file unicode-decoder.cc.
                                                                      {
  using Traits = DecoderTraits<Decoder>;
  DCHECK(!is_invalid());
  CopyChars(out, data.begin(), non_ascii_start_);
  out += non_ascii_start_;
  auto state = Traits::DfaDecoder::kAccept;
  uint32_t current = 0;
  const uint8_t* cursor = data.begin() + non_ascii_start_;
  const uint8_t* end = data.begin() + data.length();
  while (cursor < end) {
    if (V8_LIKELY(*cursor <= unibrow::Utf8::kMaxOneByteChar &&
                  state == Traits::DfaDecoder::kAccept)) {
      DCHECK_EQ(0u, current);
      *(out++) = static_cast<Char>(*cursor);
      cursor++;
      continue;
    }
    auto previous_state = state;
    Traits::DfaDecoder::Decode(*cursor, &state, &current);
    if (Traits::kAllowIncompleteSequences &&
        state < Traits::DfaDecoder::kAccept) {
      state = Traits::DfaDecoder::kAccept;
      *(out++) = static_cast<Char>(unibrow::Utf8::kBadChar);
      current = 0;
      // If we were trying to continue a multibyte sequence, try this byte
      // again.
      if (previous_state != Traits::DfaDecoder::kAccept) continue;
    } else if (state == Traits::DfaDecoder::kAccept) {
      if (sizeof(Char) == 1 ||
          current <= unibrow::Utf16::kMaxNonSurrogateCharCode) {
        *(out++) = static_cast<Char>(current);
      } else {
        *(out++) = unibrow::Utf16::LeadSurrogate(current);
        *(out++) = unibrow::Utf16::TrailSurrogate(current);
      }
      current = 0;
    }
    cursor++;
  }
  if (Traits::kAllowIncompleteSequences &&
      state != Traits::DfaDecoder::kAccept) {
    *out = static_cast<Char>(unibrow::Utf8::kBadChar);
  } else {
    DCHECK_EQ(state, Traits::DfaDecoder::kAccept);
  }
}
References v8::base::Vector< T >::begin(), v8::internal::CopyChars(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::end(), unibrow::Utf8::kBadChar, unibrow::Utf16::kMaxNonSurrogateCharCode, unibrow::Utf8::kMaxOneByteChar, unibrow::Utf16::LeadSurrogate(), v8::base::Vector< T >::length(), unibrow::Utf16::TrailSurrogate(), and V8_LIKELY.
Referenced by v8::internal::Factory::InternalizeUtf8String(), v8::internal::Factory::NewStringFromUtf8SubString(), and v8::internal::wasm::anonymous_namespace{names-provider.cc}::SanitizeUnicodeName().
is_ascii()
template<class Decoder >
bool v8::internal::Utf8DecoderBase< Decoder >::is_ascii () const [inline]
Definition at line 59 of file unicode-decoder.h.
{ return encoding_ == Encoding::kAscii; }
References v8::internal::Utf8DecoderBase< Decoder >::encoding_, and v8::internal::Utf8DecoderBase< Decoder >::kAscii.
Referenced by v8::internal::Factory::InternalizeUtf8String(), and v8::internal::Factory::NewStringFromUtf8SubString().
is_invalid()
template<class Decoder >
bool v8::internal::Utf8DecoderBase< Decoder >::is_invalid () const [inline]
Definition at line 56 of file unicode-decoder.h.
                          {
    return static_cast<const Decoder&>(*this).is_invalid();
  }
Referenced by v8::internal::Utf8DecoderBase< Decoder >::non_ascii_start(), and v8::internal::Utf8DecoderBase< Decoder >::utf16_length().
is_one_byte()
template<class Decoder >
bool v8::internal::Utf8DecoderBase< Decoder >::is_one_byte () const [inline]
Definition at line 60 of file unicode-decoder.h.
{ return encoding_ <= Encoding::kLatin1; }
References v8::internal::Utf8DecoderBase< Decoder >::encoding_, and v8::internal::Utf8DecoderBase< Decoder >::kLatin1.
Referenced by v8::internal::Factory::InternalizeUtf8String(), v8::internal::Factory::NewStringFromUtf8SubString(), v8::internal::Utf8DecoderBase< Utf8Decoder >::Utf8DecoderBase(), and v8::internal::Utf8DecoderBase< Decoder >::Utf8DecoderBase().
non_ascii_start()
template<class Decoder >
int v8::internal::Utf8DecoderBase< Decoder >::non_ascii_start () const [inline]
Definition at line 65 of file unicode-decoder.h.
                              {
    DCHECK(!is_invalid());
    return non_ascii_start_;
  }
References v8::internal::DCHECK(), v8::internal::Utf8DecoderBase< Decoder >::is_invalid(), and v8::internal::Utf8DecoderBase< Decoder >::non_ascii_start_.
utf16_length()
template<class Decoder >
int v8::internal::Utf8DecoderBase< Decoder >::utf16_length () const [inline]
Definition at line 61 of file unicode-decoder.h.
                           {
    DCHECK(!is_invalid());
    return utf16_length_;
  }
References v8::internal::DCHECK(), v8::internal::Utf8DecoderBase< Decoder >::is_invalid(), and v8::internal::Utf8DecoderBase< Decoder >::utf16_length_.
Referenced by v8::internal::Factory::InternalizeUtf8String(), v8::internal::Factory::NewStringFromUtf8SubString(), and v8::internal::wasm::anonymous_namespace{names-provider.cc}::SanitizeUnicodeName().
Member Data Documentation
encoding_
template<class Decoder >
Encoding v8::internal::Utf8DecoderBase< Decoder >::encoding_ [protected]
Definition at line 75 of file unicode-decoder.h.
Referenced by v8::internal::Utf8DecoderBase< Decoder >::is_ascii(), v8::internal::Utf8DecoderBase< Decoder >::is_one_byte(), and v8::internal::Utf8DecoderBase< Utf8Decoder >::Utf8DecoderBase().
non_ascii_start_
template<class Decoder >
int v8::internal::Utf8DecoderBase< Decoder >::non_ascii_start_ [protected]
Definition at line 76 of file unicode-decoder.h.
Referenced by v8::internal::Utf8DecoderBase< Decoder >::non_ascii_start(), and v8::internal::Utf8DecoderBase< Decoder >::Utf8DecoderBase().
utf16_length_
template<class Decoder >
int v8::internal::Utf8DecoderBase< Decoder >::utf16_length_ [protected]
Definition at line 77 of file unicode-decoder.h.
Referenced by v8::internal::Utf8DecoderBase< Decoder >::utf16_length(), and v8::internal::Utf8DecoderBase< Utf8Decoder >::Utf8DecoderBase().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/strings/unicode-decoder.h
/mnt/V8SourceCode/src/strings/unicode-decoder.cc