v8::internal::compiler::CheckIfParameters Class Reference
#include <simplified-operator.h>
Public Member Functions
CheckIfParameters (DeoptimizeReason reason, const FeedbackSource &feedback)
FeedbackSource const & feedback () const
DeoptimizeReason reason () const
Private Attributes
DeoptimizeReason reason_
FeedbackSource feedback_
Detailed Description
Definition at line 317 of file simplified-operator.h.
Constructor & Destructor Documentation
CheckIfParameters()
v8::internal::compiler::CheckIfParameters::CheckIfParameters (DeoptimizeReason reason, const FeedbackSource & feedback) [inline], [explicit]
Definition at line 319 of file simplified-operator.h.
      : reason_(reason), feedback_(feedback) {}
Member Function Documentation
feedback()
FeedbackSource const& v8::internal::compiler::CheckIfParameters::feedback () const [inline]
Definition at line 323 of file simplified-operator.h.
{ return feedback_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
reason()
DeoptimizeReason v8::internal::compiler::CheckIfParameters::reason () const [inline]
Definition at line 324 of file simplified-operator.h.
{ return reason_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
Member Data Documentation
feedback_
FeedbackSource v8::internal::compiler::CheckIfParameters::feedback_ [private]
Definition at line 328 of file simplified-operator.h.
reason_
DeoptimizeReason v8::internal::compiler::CheckIfParameters::reason_ [private]
Definition at line 327 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h