v8::platform::tracing::TraceConfig Class Reference
#include <v8-tracing.h>
Public Types
typedef std::vector< std::string > StringList
Public Member Functions
TraceConfig ()
TraceRecordMode GetTraceRecordMode () const
const StringList & GetEnabledCategories () const
bool IsSystraceEnabled () const
bool IsArgumentFilterEnabled () const
void SetTraceRecordMode (TraceRecordMode mode)
void EnableSystrace ()
void EnableArgumentFilter ()
void AddIncludedCategory (const char *included_category)
bool IsCategoryGroupEnabled (const char *category_group) const
Static Public Member Functions
static TraceConfig * CreateDefaultTraceConfig ()
Private Member Functions
TraceConfig (const TraceConfig &)=delete
void operator= (const TraceConfig &)=delete
Private Attributes
TraceRecordMode record_mode_
bool enable_systrace_: 1
bool enable_argument_filter_: 1
StringList included_categories_
Detailed Description
Definition at line 194 of file v8-tracing.h.
Member Typedef Documentation
StringList
typedef std::vector<std::string> v8::platform::tracing::TraceConfig::StringList
Definition at line 196 of file v8-tracing.h.
Constructor & Destructor Documentation
TraceConfig() [1/2]
v8::platform::tracing::TraceConfig::TraceConfig () [inline]
Definition at line 200 of file v8-tracing.h.
: enable_systrace_(false), enable_argument_filter_(false) {}
Referenced by CreateDefaultTraceConfig().
TraceConfig() [2/2]
v8::platform::tracing::TraceConfig::TraceConfig (const TraceConfig &) [private], [delete]
Member Function Documentation
AddIncludedCategory()
void v8::platform::tracing::TraceConfig::AddIncludedCategory (const char * included_category)
Definition at line 35 of file trace-config.cc.
                                                                   {
  DCHECK(included_category != nullptr && strlen(included_category) > 0);
  included_categories_.push_back(included_category);
}
References DCHECK, and included_categories_.
Referenced by v8::Shell::Main(), and v8::tracing::anonymous_namespace{d8.cc}::TraceConfigParser::UpdateIncludedCategoriesList().
CreateDefaultTraceConfig()
TraceConfig * v8::platform::tracing::TraceConfig::CreateDefaultTraceConfig () [static]
Definition at line 17 of file trace-config.cc.
                                                   {
  TraceConfig* trace_config = new TraceConfig();
  trace_config->included_categories_.push_back("v8");
  return trace_config;
}
References included_categories_, and TraceConfig().
Referenced by v8::Shell::Main().
EnableArgumentFilter()
void v8::platform::tracing::TraceConfig::EnableArgumentFilter () [inline]
Definition at line 210 of file v8-tracing.h.
{ enable_argument_filter_ = true; }
EnableSystrace()
void v8::platform::tracing::TraceConfig::EnableSystrace () [inline]
Definition at line 209 of file v8-tracing.h.
{ enable_systrace_ = true; }
GetEnabledCategories()
const StringList& v8::platform::tracing::TraceConfig::GetEnabledCategories () const [inline]
Definition at line 202 of file v8-tracing.h.
                                                 {
    return included_categories_;
  }
Referenced by v8::platform::tracing::TracingController::StartTracing().
GetTraceRecordMode()
TraceRecordMode v8::platform::tracing::TraceConfig::GetTraceRecordMode () const [inline]
Definition at line 201 of file v8-tracing.h.
{ return record_mode_; }
IsArgumentFilterEnabled()
bool v8::platform::tracing::TraceConfig::IsArgumentFilterEnabled () const [inline]
Definition at line 206 of file v8-tracing.h.
{ return enable_argument_filter_; }
IsCategoryGroupEnabled()
bool v8::platform::tracing::TraceConfig::IsCategoryGroupEnabled (const char * category_group) const
Definition at line 23 of file trace-config.cc.
                                                                         {
  std::stringstream category_stream(category_group);
  while (category_stream.good()) {
    std::string category;
    getline(category_stream, category, ',');
    for (const auto& included_category : included_categories_) {
      if (category == included_category) return true;
    }
  }
  return false;
}
References included_categories_, and v8::internal::string.
IsSystraceEnabled()
bool v8::platform::tracing::TraceConfig::IsSystraceEnabled () const [inline]
Definition at line 205 of file v8-tracing.h.
{ return enable_systrace_; }
operator=()
void v8::platform::tracing::TraceConfig::operator= (const TraceConfig &) [private], [delete]
SetTraceRecordMode()
void v8::platform::tracing::TraceConfig::SetTraceRecordMode (TraceRecordMode mode) [inline]
Definition at line 208 of file v8-tracing.h.
{ record_mode_ = mode; }
References mode().
Member Data Documentation
enable_argument_filter_
bool v8::platform::tracing::TraceConfig::enable_argument_filter_ [private]
Definition at line 219 of file v8-tracing.h.
enable_systrace_
bool v8::platform::tracing::TraceConfig::enable_systrace_ [private]
Definition at line 218 of file v8-tracing.h.
included_categories_
StringList v8::platform::tracing::TraceConfig::included_categories_ [private]
Definition at line 220 of file v8-tracing.h.
Referenced by AddIncludedCategory(), CreateDefaultTraceConfig(), and IsCategoryGroupEnabled().
record_mode_
TraceRecordMode v8::platform::tracing::TraceConfig::record_mode_ [private]
Definition at line 217 of file v8-tracing.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/libplatform/v8-tracing.h
/mnt/V8SourceCode/src/libplatform/tracing/trace-config.cc