v8::internal::compiler::JSTypedLowering Class Reference
#include <js-typed-lowering.h>
Public Member Functions
JSTypedLowering (Editor *editor, JSGraph *jsgraph, JSHeapBroker *broker, Zone *zone)
~JSTypedLowering () final=default
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Member Functions
Reduction ReduceJSAdd (Node *node)
Reduction ReduceJSBitwiseNot (Node *node)
Reduction ReduceJSDecrement (Node *node)
Reduction ReduceJSIncrement (Node *node)
Reduction ReduceJSNegate (Node *node)
Reduction ReduceJSComparison (Node *node)
Reduction ReduceJSLoadNamed (Node *node)
Reduction ReduceJSHasInPrototypeChain (Node *node)
Reduction ReduceJSOrdinaryHasInstance (Node *node)
Reduction ReduceJSHasContextExtension (Node *node)
Reduction ReduceJSLoadContextNoCell (Node *node)
Reduction ReduceJSLoadContext (Node *node)
Reduction ReduceJSStoreContextNoCell (Node *node)
Reduction ReduceJSStoreContext (Node *node)
Reduction ReduceJSLoadModule (Node *node)
Reduction ReduceJSStoreModule (Node *node)
Reduction ReduceJSEqual (Node *node)
Reduction ReduceJSStrictEqual (Node *node)
Reduction ReduceJSToLength (Node *node)
Reduction ReduceJSToName (Node *node)
Reduction ReduceJSToNumberInput (Node *input)
Reduction ReduceJSToNumber (Node *node)
Reduction ReduceJSToBigInt (Node *node)
Reduction ReduceJSToBigIntConvertNumber (Node *node)
Reduction ReduceJSToNumeric (Node *node)
Reduction ReduceJSToStringInput (Node *input)
Reduction ReduceJSToString (Node *node)
Reduction ReduceJSToObject (Node *node)
Reduction ReduceJSConstructForwardVarargs (Node *node)
Reduction ReduceJSConstruct (Node *node)
Reduction ReduceJSCallForwardVarargs (Node *node)
Reduction ReduceJSCall (Node *node)
Reduction ReduceJSForInNext (Node *node)
Reduction ReduceJSForInPrepare (Node *node)
Reduction ReduceJSLoadMessage (Node *node)
Reduction ReduceJSStoreMessage (Node *node)
Reduction ReduceJSGeneratorStore (Node *node)
Reduction ReduceJSGeneratorRestoreContinuation (Node *node)
Reduction ReduceJSGeneratorRestoreContextNoCell (Node *node)
Reduction ReduceJSGeneratorRestoreRegister (Node *node)
Reduction ReduceJSGeneratorRestoreInputOrDebugPos (Node *node)
Reduction ReduceNumberBinop (Node *node)
Reduction ReduceInt32Binop (Node *node)
Reduction ReduceUI32Shift (Node *node, Signedness signedness)
Reduction ReduceObjectIsArray (Node *node)
Reduction ReduceJSParseInt (Node *node)
Reduction ReduceJSResolvePromise (Node *node)
Node * BuildGetModuleCell (Node *node)
Reduction GenerateStringAddition (Node *node, Node *left, Node *right, Node *context, Node *frame_state, Node **effect, Node **control, bool should_create_cons_string)
Node * UnwrapStringWrapper (Node *string_or_wrapper, Node **effect, Node **control)
Factory * factory () const
TFGraph * graph () const
JSGraph * jsgraph () const
JSHeapBroker * broker () const
CompilationDependencies * dependencies () const
Isolate * isolate () const
JSOperatorBuilder * javascript () const
CommonOperatorBuilder * common () const
SimplifiedOperatorBuilder * simplified () const
Private Attributes
JSGraph * jsgraph_
JSHeapBroker * broker_
Type empty_string_type_
Type pointer_comparable_type_
TypeCache const * type_cache_
Friends
class JSBinopReduction
Detailed Description
Definition at line 30 of file js-typed-lowering.h.
Constructor & Destructor Documentation
JSTypedLowering()
v8::internal::compiler::JSTypedLowering::JSTypedLowering (Editor * editor, JSGraph * jsgraph, JSHeapBroker * broker, Zone * zone)
Definition at line 546 of file js-typed-lowering.cc.
    : AdvancedReducer(editor),
      jsgraph_(jsgraph),
      broker_(broker),
      empty_string_type_(
          Type::Constant(broker, broker->empty_string(), graph()->zone())),
      pointer_comparable_type_(
          Type::Union(Type::Union(Type::BooleanOrNullOrUndefined(),
                                  Type::Hole(), graph()->zone()),
                      Type::Union(Type::SymbolOrReceiver(), empty_string_type_,
                                  graph()->zone()),
                      graph()->zone())),
      type_cache_(TypeCache::Get()) {}
 JSTypedLowering()
v8::internal::compiler::JSTypedLowering::~JSTypedLowering () [final], [default]
Member Function Documentation
broker()
JSHeapBroker* v8::internal::compiler::JSTypedLowering::broker () const [inline], [private]
Definition at line 106 of file js-typed-lowering.h.
{ return broker_; }
Referenced by BuildGetModuleCell(), dependencies(), GenerateStringAddition(), v8::internal::compiler::JSBinopReduction::GetBinaryOperationHint(), v8::internal::compiler::JSBinopReduction::GetCompareOperationHint(), ReduceJSAdd(), ReduceJSCall(), ReduceJSConstruct(), ReduceJSConstructForwardVarargs(), ReduceJSEqual(), ReduceJSForInPrepare(), ReduceJSHasContextExtension(), ReduceJSLoadContext(), ReduceJSLoadNamed(), ReduceJSStoreContext(), ReduceJSToNumberInput(), and v8::internal::compiler::JSBinopReduction::ShouldCreateConsString().
BuildGetModuleCell()
Node * v8::internal::compiler::JSTypedLowering::BuildGetModuleCell (Node * node) [private]
Definition at line 1757 of file js-typed-lowering.cc.
                                                    {
  DCHECK(node->opcode() == IrOpcode::kJSLoadModule ||
         node->opcode() == IrOpcode::kJSStoreModule);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  int32_t cell_index = OpParameter<int32_t>(node->op());
  Node* module = NodeProperties::GetValueInput(node, 0);
  Type module_type = NodeProperties::GetType(module);
  if (module_type.IsHeapConstant()) {
    SourceTextModuleRef module_constant =
        module_type.AsHeapConstant()->Ref().AsSourceTextModule();
    OptionalCellRef cell_constant =
        module_constant.GetCell(broker(), cell_index);
    if (cell_constant.has_value())
      return jsgraph()->ConstantNoHole(*cell_constant, broker());
  }
  FieldAccess field_access;
  int index;
  if (SourceTextModuleDescriptor::GetCellIndexKind(cell_index) ==
      SourceTextModuleDescriptor::kExport) {
    field_access = AccessBuilder::ForModuleRegularExports();
    index = cell_index - 1;
  } else {
    DCHECK_EQ(SourceTextModuleDescriptor::GetCellIndexKind(cell_index),
              SourceTextModuleDescriptor::kImport);
    field_access = AccessBuilder::ForModuleRegularImports();
    index = -cell_index - 1;
  }
  Node* array = effect = graph()->NewNode(simplified()->LoadField(field_access),
                                          module, effect, control);
  return graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForFixedArraySlot(index)), array,
      effect, control);
}
References v8::internal::compiler::Type::AsHeapConstant(), broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::AccessBuilder::ForFixedArraySlot(), v8::internal::compiler::AccessBuilder::ForModuleRegularExports(), v8::internal::compiler::AccessBuilder::ForModuleRegularImports(), v8::internal::compiler::SourceTextModuleRef::GetCell(), v8::internal::SourceTextModuleDescriptor::GetCellIndexKind(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::index, v8::internal::compiler::Type::IsHeapConstant(), jsgraph(), v8::internal::SourceTextModuleDescriptor::kExport, v8::internal::SourceTextModuleDescriptor::kImport, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapConstantType::Ref(), and simplified().
Referenced by ReduceJSLoadModule(), and ReduceJSStoreModule().
common()
CommonOperatorBuilder * v8::internal::compiler::JSTypedLowering::common () const [private]
Definition at line 2856 of file js-typed-lowering.cc.
                                                     {
  return jsgraph()->common();
}
References v8::internal::compiler::MachineGraph::common(), and jsgraph().
Referenced by GenerateStringAddition(), ReduceJSAdd(), ReduceJSCall(), ReduceJSCallForwardVarargs(), ReduceJSConstruct(), ReduceJSConstructForwardVarargs(), ReduceJSForInNext(), ReduceJSForInPrepare(), ReduceJSHasInPrototypeChain(), ReduceJSToObject(), ReduceJSToStringInput(), ReduceObjectIsArray(), and UnwrapStringWrapper().
dependencies()
CompilationDependencies * v8::internal::compiler::JSTypedLowering::dependencies () const [private]
Definition at line 2846 of file js-typed-lowering.cc.
                                                             {
  return broker()->dependencies();
}
References broker(), and v8::internal::compiler::JSHeapBroker::dependencies().
Referenced by ReduceJSAdd().
factory()
Factory * v8::internal::compiler::JSTypedLowering::factory () const [private]
Definition at line 2842 of file js-typed-lowering.cc.
{ return jsgraph()->factory(); }
References v8::internal::compiler::JSGraph::factory(), and jsgraph().
Referenced by GenerateStringAddition(), ReduceJSAdd(), and ReduceJSToStringInput().
GenerateStringAddition()
Reduction v8::internal::compiler::JSTypedLowering::GenerateStringAddition (Node * node, Node * left, Node * right, Node * context, Node * frame_state, Node ** effect, Node ** control, bool should_create_cons_string) [private]
Definition at line 624 of file js-typed-lowering.cc.
                                                                   {
  // Compute the resulting length.
  Node* left_length = graph()->NewNode(simplified()->StringLength(), left);
  Node* right_length = graph()->NewNode(simplified()->StringLength(), right);
  Node* length =
      graph()->NewNode(simplified()->NumberAdd(), left_length, right_length);
  PropertyCellRef string_length_protector =
      MakeRef(broker(), factory()->string_length_protector());
  string_length_protector.CacheAsProtector(broker());
  if (string_length_protector.value(broker()).AsSmi() ==
      Protectors::kProtectorValid) {
    // We can just deoptimize if the {length} is out-of-bounds. Besides
    // generating a shorter code sequence than the version below, this
    // has the additional benefit of not holding on to the lazy {frame_state}
    // and thus potentially reduces the number of live ranges and allows for
    // more truncations.
    length = *effect = graph()->NewNode(
        simplified()->CheckBounds(FeedbackSource()), length,
        jsgraph()->ConstantNoHole(String::kMaxLength + 1), *effect, *control);
  } else {
    // Check if we would overflow the allowed maximum string length.
    Node* check =
        graph()->NewNode(simplified()->NumberLessThanOrEqual(), length,
                         jsgraph()->ConstantNoHole(String::kMaxLength));
    Node* branch =
        graph()->NewNode(common()->Branch(BranchHint::kTrue), check, *control);
    Node* if_false = graph()->NewNode(common()->IfFalse(), branch);
    Node* efalse = *effect;
    {
      // Throw a RangeError in case of overflow.
      Node* vfalse = efalse = if_false = graph()->NewNode(
          javascript()->CallRuntime(Runtime::kThrowInvalidStringLength),
          context, frame_state, efalse, if_false);
      // Update potential {IfException} uses of {node} to point to the
      // %ThrowInvalidStringLength runtime call node instead.
      Node* on_exception = nullptr;
      if (NodeProperties::IsExceptionalCall(node, &on_exception)) {
        NodeProperties::ReplaceControlInput(on_exception, vfalse);
        NodeProperties::ReplaceEffectInput(on_exception, efalse);
        if_false = graph()->NewNode(common()->IfSuccess(), vfalse);
        Revisit(on_exception);
      }
      // The above %ThrowInvalidStringLength runtime call is an unconditional
      // throw, making it impossible to return a successful completion in this
      // case. We simply connect the successful completion to the graph end.
      if_false = graph()->NewNode(common()->Throw(), efalse, if_false);
      MergeControlToEnd(graph(), common(), if_false);
    }
    *control = graph()->NewNode(common()->IfTrue(), branch);
    length = *effect =
        graph()->NewNode(common()->TypeGuard(type_cache_->kStringLengthType),
                         length, *effect, *control);
  }
  // TODO(bmeurer): Ideally this should always use StringConcat and decide to
  // optimize to NewConsString later during SimplifiedLowering, but for that
  // to work we need to know that it's safe to create a ConsString.
  Operator const* const op = should_create_cons_string
                                 ? simplified()->NewConsString()
                                 : simplified()->StringConcat();
  Node* value = graph()->NewNode(op, length, left, right);
  ReplaceWithValue(node, value, *effect, *control);
  return Replace(value);
}
References broker(), v8::internal::compiler::PropertyCellRef::CacheAsProtector(), common(), factory(), graph(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), javascript(), jsgraph(), v8::internal::String::kMaxLength, v8::internal::Protectors::kProtectorValid, v8::internal::compiler::TypeCache::kStringLengthType, v8::internal::kTrue, v8::internal::length, v8::internal::compiler::MakeRef(), v8::internal::compiler::SimplifiedOperatorBuilder::NewConsString(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), simplified(), v8::internal::compiler::SimplifiedOperatorBuilder::StringConcat(), v8::anonymous_namespace{api.cc}::StringLength(), type_cache_, v8::internal::compiler::PropertyCellRef::value(), and v8::internal::value.
Referenced by ReduceJSAdd().
graph()
TFGraph * v8::internal::compiler::JSTypedLowering::graph () const [private]
Definition at line 2844 of file js-typed-lowering.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
Referenced by BuildGetModuleCell(), GenerateStringAddition(), v8::internal::compiler::JSBinopReduction::graph(), ReduceJSAdd(), ReduceJSBitwiseNot(), ReduceJSCall(), ReduceJSCallForwardVarargs(), ReduceJSConstruct(), ReduceJSConstructForwardVarargs(), ReduceJSDecrement(), ReduceJSForInNext(), ReduceJSForInPrepare(), ReduceJSGeneratorRestoreContinuation(), ReduceJSGeneratorRestoreRegister(), ReduceJSGeneratorStore(), ReduceJSHasContextExtension(), ReduceJSHasInPrototypeChain(), ReduceJSIncrement(), ReduceJSLoadContextNoCell(), ReduceJSLoadModule(), ReduceJSLoadNamed(), ReduceJSNegate(), ReduceJSStoreContextNoCell(), ReduceJSStoreModule(), ReduceJSStrictEqual(), ReduceJSToBigIntConvertNumber(), ReduceJSToLength(), ReduceJSToNumber(), ReduceJSToNumeric(), ReduceJSToObject(), ReduceJSToStringInput(), ReduceObjectIsArray(), and UnwrapStringWrapper().
isolate()
Isolate * v8::internal::compiler::JSTypedLowering::isolate () const [private]
Definition at line 2850 of file js-typed-lowering.cc.
{ return jsgraph()->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph().
Referenced by ReduceJSAdd(), ReduceJSCall(), ReduceJSCallForwardVarargs(), ReduceJSConstruct(), ReduceJSConstructForwardVarargs(), ReduceJSForInNext(), ReduceJSLoadMessage(), ReduceJSStoreMessage(), and ReduceJSToObject().
javascript()
JSOperatorBuilder * v8::internal::compiler::JSTypedLowering::javascript () const [private]
Definition at line 2852 of file js-typed-lowering.cc.
                                                     {
  return jsgraph()->javascript();
}
References v8::internal::compiler::JSGraph::javascript(), and jsgraph().
Referenced by GenerateStringAddition(), v8::internal::compiler::JSBinopReduction::javascript(), ReduceJSAdd(), ReduceJSBitwiseNot(), ReduceJSCall(), ReduceJSDecrement(), ReduceJSHasInPrototypeChain(), ReduceJSIncrement(), ReduceJSNegate(), ReduceJSResolvePromise(), ReduceJSToNumeric(), and ReduceObjectIsArray().
jsgraph()
JSGraph* v8::internal::compiler::JSTypedLowering::jsgraph () const [inline], [private]
Definition at line 105 of file js-typed-lowering.h.
{ return jsgraph_; }
Referenced by BuildGetModuleCell(), common(), factory(), GenerateStringAddition(), graph(), isolate(), javascript(), v8::internal::compiler::JSBinopReduction::jsgraph(), ReduceJSAdd(), ReduceJSBitwiseNot(), ReduceJSCall(), ReduceJSCallForwardVarargs(), ReduceJSConstruct(), ReduceJSConstructForwardVarargs(), ReduceJSDecrement(), ReduceJSEqual(), ReduceJSForInNext(), ReduceJSForInPrepare(), ReduceJSGeneratorRestoreContinuation(), ReduceJSGeneratorRestoreRegister(), ReduceJSGeneratorStore(), ReduceJSHasInPrototypeChain(), ReduceJSIncrement(), ReduceJSLoadContext(), ReduceJSLoadContextNoCell(), ReduceJSLoadMessage(), ReduceJSNegate(), ReduceJSOrdinaryHasInstance(), ReduceJSStoreContext(), ReduceJSStoreMessage(), ReduceJSToLength(), ReduceJSToNumberInput(), ReduceJSToObject(), ReduceJSToStringInput(), ReduceObjectIsArray(), and simplified().
Reduce()
Reduction v8::internal::compiler::JSTypedLowering::Reduce (Node * node) [final]
Definition at line 2731 of file js-typed-lowering.cc.
                                            {
  switch (node->opcode()) {
    case IrOpcode::kJSEqual:
      return ReduceJSEqual(node);
    case IrOpcode::kJSStrictEqual:
      return ReduceJSStrictEqual(node);
    case IrOpcode::kJSLessThan: // fall through
    case IrOpcode::kJSGreaterThan: // fall through
    case IrOpcode::kJSLessThanOrEqual: // fall through
    case IrOpcode::kJSGreaterThanOrEqual:
      return ReduceJSComparison(node);
    case IrOpcode::kJSBitwiseOr:
    case IrOpcode::kJSBitwiseXor:
    case IrOpcode::kJSBitwiseAnd:
      return ReduceInt32Binop(node);
    case IrOpcode::kJSShiftLeft:
    case IrOpcode::kJSShiftRight:
      return ReduceUI32Shift(node, kSigned);
    case IrOpcode::kJSShiftRightLogical:
      return ReduceUI32Shift(node, kUnsigned);
    case IrOpcode::kJSAdd:
      return ReduceJSAdd(node);
    case IrOpcode::kJSSubtract:
    case IrOpcode::kJSMultiply:
    case IrOpcode::kJSDivide:
    case IrOpcode::kJSModulus:
    case IrOpcode::kJSExponentiate:
      return ReduceNumberBinop(node);
    case IrOpcode::kJSBitwiseNot:
      return ReduceJSBitwiseNot(node);
    case IrOpcode::kJSDecrement:
      return ReduceJSDecrement(node);
    case IrOpcode::kJSIncrement:
      return ReduceJSIncrement(node);
    case IrOpcode::kJSNegate:
      return ReduceJSNegate(node);
    case IrOpcode::kJSHasInPrototypeChain:
      return ReduceJSHasInPrototypeChain(node);
    case IrOpcode::kJSOrdinaryHasInstance:
      return ReduceJSOrdinaryHasInstance(node);
    case IrOpcode::kJSToLength:
      return ReduceJSToLength(node);
    case IrOpcode::kJSToName:
      return ReduceJSToName(node);
    case IrOpcode::kJSToNumber:
    case IrOpcode::kJSToNumberConvertBigInt:
      return ReduceJSToNumber(node);
    case IrOpcode::kJSToBigInt:
      return ReduceJSToBigInt(node);
    case IrOpcode::kJSToBigIntConvertNumber:
      return ReduceJSToBigIntConvertNumber(node);
    case IrOpcode::kJSToNumeric:
      return ReduceJSToNumeric(node);
    case IrOpcode::kJSToString:
      return ReduceJSToString(node);
    case IrOpcode::kJSToObject:
      return ReduceJSToObject(node);
    case IrOpcode::kJSLoadNamed:
      return ReduceJSLoadNamed(node);
    case IrOpcode::kJSLoadContextNoCell:
      return ReduceJSLoadContextNoCell(node);
    case IrOpcode::kJSLoadContext:
      return ReduceJSLoadContext(node);
    case IrOpcode::kJSStoreContextNoCell:
      return ReduceJSStoreContextNoCell(node);
    case IrOpcode::kJSStoreContext:
      return ReduceJSStoreContext(node);
    case IrOpcode::kJSLoadModule:
      return ReduceJSLoadModule(node);
    case IrOpcode::kJSStoreModule:
      return ReduceJSStoreModule(node);
    case IrOpcode::kJSConstructForwardVarargs:
      return ReduceJSConstructForwardVarargs(node);
    case IrOpcode::kJSConstruct:
      return ReduceJSConstruct(node);
    case IrOpcode::kJSCallForwardVarargs:
      return ReduceJSCallForwardVarargs(node);
    case IrOpcode::kJSCall:
      return ReduceJSCall(node);
    case IrOpcode::kJSForInPrepare:
      return ReduceJSForInPrepare(node);
    case IrOpcode::kJSForInNext:
      return ReduceJSForInNext(node);
    case IrOpcode::kJSHasContextExtension:
      return ReduceJSHasContextExtension(node);
    case IrOpcode::kJSLoadMessage:
      return ReduceJSLoadMessage(node);
    case IrOpcode::kJSStoreMessage:
      return ReduceJSStoreMessage(node);
    case IrOpcode::kJSGeneratorStore:
      return ReduceJSGeneratorStore(node);
    case IrOpcode::kJSGeneratorRestoreContinuation:
      return ReduceJSGeneratorRestoreContinuation(node);
    case IrOpcode::kJSGeneratorRestoreContextNoCell:
      return ReduceJSGeneratorRestoreContextNoCell(node);
    case IrOpcode::kJSGeneratorRestoreRegister:
      return ReduceJSGeneratorRestoreRegister(node);
    case IrOpcode::kJSGeneratorRestoreInputOrDebugPos:
      return ReduceJSGeneratorRestoreInputOrDebugPos(node);
    case IrOpcode::kJSObjectIsArray:
      return ReduceObjectIsArray(node);
    case IrOpcode::kJSParseInt:
      return ReduceJSParseInt(node);
    case IrOpcode::kJSResolvePromise:
      return ReduceJSResolvePromise(node);
    default:
      break;
  }
  return NoChange();
}
References v8::internal::compiler::kSigned, v8::internal::compiler::kUnsigned, v8::internal::compiler::Node::opcode(), ReduceInt32Binop(), ReduceJSAdd(), ReduceJSBitwiseNot(), ReduceJSCall(), ReduceJSCallForwardVarargs(), ReduceJSComparison(), ReduceJSConstruct(), ReduceJSConstructForwardVarargs(), ReduceJSDecrement(), ReduceJSEqual(), ReduceJSForInNext(), ReduceJSForInPrepare(), ReduceJSGeneratorRestoreContextNoCell(), ReduceJSGeneratorRestoreContinuation(), ReduceJSGeneratorRestoreInputOrDebugPos(), ReduceJSGeneratorRestoreRegister(), ReduceJSGeneratorStore(), ReduceJSHasContextExtension(), ReduceJSHasInPrototypeChain(), ReduceJSIncrement(), ReduceJSLoadContext(), ReduceJSLoadContextNoCell(), ReduceJSLoadMessage(), ReduceJSLoadModule(), ReduceJSLoadNamed(), ReduceJSNegate(), ReduceJSOrdinaryHasInstance(), ReduceJSParseInt(), ReduceJSResolvePromise(), ReduceJSStoreContext(), ReduceJSStoreContextNoCell(), ReduceJSStoreMessage(), ReduceJSStoreModule(), ReduceJSStrictEqual(), ReduceJSToBigInt(), ReduceJSToBigIntConvertNumber(), ReduceJSToLength(), ReduceJSToName(), ReduceJSToNumber(), ReduceJSToNumeric(), ReduceJSToObject(), ReduceJSToString(), ReduceNumberBinop(), ReduceObjectIsArray(), and ReduceUI32Shift().
ReduceInt32Binop()
Reduction v8::internal::compiler::JSTypedLowering::ReduceInt32Binop (Node * node) [private]
Definition at line 858 of file js-typed-lowering.cc.
                                                      {
  JSBinopReduction r(this, node);
  if (r.BothInputsAre(Type::PlainPrimitive())) {
    r.ConvertInputsToNumber();
    r.ConvertInputsToUI32(kSigned, kSigned);
    return r.ChangeToPureOperator(r.NumberOp(), Type::Signed32());
  }
  return NoChange();
}
References v8::internal::compiler::JSBinopReduction::BothInputsAre(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ConvertInputsToNumber(), v8::internal::compiler::JSBinopReduction::ConvertInputsToUI32(), v8::internal::compiler::kSigned, and v8::internal::compiler::JSBinopReduction::NumberOp().
Referenced by Reduce().
ReduceJSAdd()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSAdd (Node * node) [private]
Definition at line 726 of file js-typed-lowering.cc.
                                                 {
  JSBinopReduction r(this, node);
  if (r.BothInputsAre(Type::Number())) {
    // JSAdd(x:number, y:number) => NumberAdd(x, y)
    return r.ChangeToPureOperator(simplified()->NumberAdd(), Type::Number());
  }
  if (r.BothInputsAre(Type::PlainPrimitive()) &&
      r.NeitherInputCanBe(Type::StringOrReceiver())) {
    // JSAdd(x:-string, y:-string) => NumberAdd(ToNumber(x), ToNumber(y))
    r.ConvertInputsToNumber();
    return r.ChangeToPureOperator(simplified()->NumberAdd(), Type::Number());
  }
  // Strength-reduce if one input is already known to be a string.
  if (r.LeftInputIs(Type::String())) {
    // JSAdd(x:string, y) => JSAdd(x, JSToString(y))
    Reduction const reduction = ReduceJSToStringInput(r.right());
    if (reduction.Changed()) {
      NodeProperties::ReplaceValueInput(node, reduction.replacement(), 1);
    }
  } else if (r.RightInputIs(Type::String())) {
    // JSAdd(x, y:string) => JSAdd(JSToString(x), y)
    Reduction const reduction = ReduceJSToStringInput(r.left());
    if (reduction.Changed()) {
      NodeProperties::ReplaceValueInput(node, reduction.replacement(), 0);
    }
  }
  PropertyCellRef to_primitive_protector =
      MakeRef(broker(), factory()->string_wrapper_to_primitive_protector());
  to_primitive_protector.CacheAsProtector(broker());
  bool can_inline_string_wrapper_add = false;
  // Always bake in String feedback into the graph.
  if (r.GetBinaryOperationHint(node) == BinaryOperationHint::kString) {
    r.CheckInputsToString();
  } else if (r.GetBinaryOperationHint(node) ==
             BinaryOperationHint::kStringOrStringWrapper) {
    can_inline_string_wrapper_add =
        dependencies()->DependOnProtector(to_primitive_protector);
    if (can_inline_string_wrapper_add) {
      r.CheckInputsToStringOrStringWrapper();
    }
  }
  // Strength-reduce concatenation of empty strings if both sides are
  // primitives, as in that case the ToPrimitive on the other side is
  // definitely going to be a no-op.
  if (r.BothInputsAre(Type::Primitive())) {
    if (r.LeftInputIs(empty_string_type_)) {
      // JSAdd("", x:primitive) => JSToString(x)
      NodeProperties::ReplaceValueInputs(node, r.right());
      NodeProperties::ChangeOp(node, javascript()->ToString());
      NodeProperties::SetType(
          node, Type::Intersect(r.type(), Type::String(), graph()->zone()));
      return Changed(node).FollowedBy(ReduceJSToString(node));
    } else if (r.RightInputIs(empty_string_type_)) {
      // JSAdd(x:primitive, "") => JSToString(x)
      NodeProperties::ReplaceValueInputs(node, r.left());
      NodeProperties::ChangeOp(node, javascript()->ToString());
      NodeProperties::SetType(
          node, Type::Intersect(r.type(), Type::String(), graph()->zone()));
      return Changed(node).FollowedBy(ReduceJSToString(node));
    }
  }
  Node* context = NodeProperties::GetContextInput(node);
  Node* frame_state = NodeProperties::GetFrameStateInput(node);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  // Lower to string addition if both inputs are known to be strings.
  if (r.BothInputsAre(Type::String())) {
    return GenerateStringAddition(node, r.left(), r.right(), context,
                                  frame_state, &effect, &control,
                                  r.ShouldCreateConsString());
  } else if (r.BothInputsAre(Type::StringOrStringWrapper()) &&
             can_inline_string_wrapper_add) {
    // If the left hand side is a string wrapper, unwrap it.
    Node* left_string = UnwrapStringWrapper(r.left(), &effect, &control);
    // If the right hand side is a string wrapper, unwrap it.
    Node* right_string = UnwrapStringWrapper(r.right(), &effect, &control);
    // Generate the string addition.
    return GenerateStringAddition(node, left_string, right_string, context,
                                  frame_state, &effect, &control, false);
  }
  // We never get here when we had String feedback.
  DCHECK_NE(BinaryOperationHint::kString, r.GetBinaryOperationHint(node));
  if (r.OneInputIs(Type::String())) {
    StringAddFlags flags = STRING_ADD_CHECK_NONE;
    if (!r.LeftInputIs(Type::String())) {
      flags = STRING_ADD_CONVERT_LEFT;
    } else if (!r.RightInputIs(Type::String())) {
      flags = STRING_ADD_CONVERT_RIGHT;
    }
    Operator::Properties properties = node->op()->properties();
    if (r.NeitherInputCanBe(Type::Receiver())) {
      // Both sides are already strings, so we know that the
      // string addition will not cause any observable side
      // effects; it can still throw obviously.
      properties = Operator::kNoWrite | Operator::kNoDeopt;
    }
    // JSAdd(x:string, y) => CallStub[StringAdd](x, y)
    // JSAdd(x, y:string) => CallStub[StringAdd](x, y)
    Callable const callable = CodeFactory::StringAdd(isolate(), flags);
    auto call_descriptor = Linkage::GetStubCallDescriptor(
        graph()->zone(), callable.descriptor(),
        callable.descriptor().GetStackParameterCount(),
        CallDescriptor::kNeedsFrameState, properties);
    DCHECK_EQ(1, OperatorProperties::GetFrameStateInputCount(node->op()));
    node->RemoveInput(JSAddNode::FeedbackVectorIndex());
    node->InsertInput(graph()->zone(), 0,
                      jsgraph()->HeapConstantNoHole(callable.code()));
    NodeProperties::ChangeOp(node, common()->Call(call_descriptor));
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::JSBinopReduction::BothInputsAre(), broker(), v8::internal::compiler::PropertyCellRef::CacheAsProtector(), v8::internal::compiler::Reduction::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::CheckInputsToString(), v8::internal::compiler::JSBinopReduction::CheckInputsToStringOrStringWrapper(), v8::internal::Callable::code(), common(), v8::internal::compiler::JSBinopReduction::ConvertInputsToNumber(), DCHECK_EQ, DCHECK_NE, dependencies(), v8::internal::compiler::CompilationDependencies::DependOnProtector(), v8::internal::Callable::descriptor(), empty_string_type_, factory(), v8::internal::flags, GenerateStringAddition(), v8::internal::compiler::JSBinopReduction::GetBinaryOperationHint(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetFrameStateInput(), v8::internal::compiler::OperatorProperties::GetFrameStateInputCount(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), graph(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::compiler::Node::InsertInput(), v8::internal::compiler::Type::Intersect(), isolate(), javascript(), jsgraph(), v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::Operator::kNoDeopt, v8::internal::compiler::Operator::kNoWrite, v8::internal::kString, v8::internal::kStringOrStringWrapper, v8::internal::compiler::JSBinopReduction::left(), v8::internal::compiler::JSBinopReduction::LeftInputIs(), v8::internal::compiler::MakeRef(), v8::internal::compiler::JSBinopReduction::NeitherInputCanBe(), v8::internal::compiler::JSBinopReduction::OneInputIs(), v8::internal::compiler::Node::op(), v8::internal::compiler::Operator::properties(), ReduceJSToString(), ReduceJSToStringInput(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::Reduction::replacement(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), v8::internal::compiler::NodeProperties::ReplaceValueInputs(), v8::internal::compiler::JSBinopReduction::right(), v8::internal::compiler::JSBinopReduction::RightInputIs(), v8::internal::compiler::NodeProperties::SetType(), v8::internal::compiler::JSBinopReduction::ShouldCreateConsString(), simplified(), v8::internal::STRING_ADD_CHECK_NONE, v8::internal::STRING_ADD_CONVERT_LEFT, v8::internal::STRING_ADD_CONVERT_RIGHT, v8::internal::CodeFactory::StringAdd(), v8::internal::compiler::ToString(), v8::internal::compiler::JSBinopReduction::type(), and UnwrapStringWrapper().
Referenced by Reduce().
ReduceJSBitwiseNot()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSBitwiseNot (Node * node) [private]
Definition at line 561 of file js-typed-lowering.cc.
                                                        {
  Node* input = NodeProperties::GetValueInput(node, 0);
  Type input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::PlainPrimitive())) {
    // JSBitwiseNot(x) => NumberBitwiseXor(ToInt32(x), -1)
    const FeedbackParameter& p = FeedbackParameterOf(node->op());
    node->InsertInput(graph()->zone(), 1, jsgraph()->SmiConstant(-1));
    NodeProperties::ChangeOp(node, javascript()->BitwiseXor(p.feedback()));
    JSBinopReduction r(this, node);
    r.ConvertInputsToNumber();
    r.ConvertInputsToUI32(kSigned, kSigned);
    return r.ChangeToPureOperator(r.NumberOp(), Type::Signed32());
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ConvertInputsToNumber(), v8::internal::compiler::JSBinopReduction::ConvertInputsToUI32(), v8::internal::compiler::FeedbackParameter::feedback(), v8::internal::compiler::FeedbackParameterOf(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::Node::InsertInput(), v8::internal::compiler::Type::Is(), javascript(), jsgraph(), v8::internal::compiler::kSigned, v8::internal::compiler::JSBinopReduction::NumberOp(), and v8::internal::compiler::Node::op().
Referenced by Reduce().
ReduceJSCall()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSCall (Node * node) [private]
Definition at line 2019 of file js-typed-lowering.cc.
                                                  {
  JSCallNode n(node);
  CallParameters const& p = n.Parameters();
  int arity = p.arity_without_implicit_args();
  ConvertReceiverMode convert_mode = p.convert_mode();
  Node* target = n.target();
  Type target_type = NodeProperties::GetType(target);
  Node* receiver = n.receiver();
  Type receiver_type = NodeProperties::GetType(receiver);
  Effect effect = n.effect();
  Control control = n.control();
  // Try to infer receiver {convert_mode} from {receiver} type.
  if (receiver_type.Is(Type::NullOrUndefined())) {
    convert_mode = ConvertReceiverMode::kNullOrUndefined;
  } else if (!receiver_type.Maybe(Type::NullOrUndefined())) {
    convert_mode = ConvertReceiverMode::kNotNullOrUndefined;
  }
  // Check if we know the SharedFunctionInfo of {target}.
  OptionalJSFunctionRef function;
  OptionalSharedFunctionInfoRef shared;
  if (target_type.IsHeapConstant() &&
      target_type.AsHeapConstant()->Ref().IsJSFunction()) {
    function = target_type.AsHeapConstant()->Ref().AsJSFunction();
    shared = function->shared(broker());
  } else if (target->opcode() == IrOpcode::kJSCreateClosure) {
    CreateClosureParameters const& ccp =
        JSCreateClosureNode{target}.Parameters();
    shared = ccp.shared_info();
  } else if (target->opcode() == IrOpcode::kCheckClosure) {
    FeedbackCellRef cell = MakeRef(broker(), FeedbackCellOf(target->op()));
    shared = cell.shared_function_info(broker());
  }
  if (shared.has_value()) {
    // Do not inline the call if we need to check whether to break at entry.
    // If this state changes during background compilation, the compilation
    // job will be aborted from the main thread (see
    // Debug::PrepareFunctionForDebugExecution()).
    if (shared->HasBreakInfo(broker())) return NoChange();
    // Class constructors are callable, but [[Call]] will raise an exception.
    // See ES6 section 9.2.1 [[Call]] (thisArgument, argumentsList).
    // We need to check here in addition to JSCallReducer for Realms.
    // TODO(pthier): Consolidate all the class constructor checks.
    if (IsClassConstructor(shared->kind())) return NoChange();
    // Check if we need to convert the {receiver}, but bailout if it would
    // require data from a foreign native context.
    if (is_sloppy(shared->language_mode()) && !shared->native() &&
        !receiver_type.Is(Type::Receiver())) {
      if (!function.has_value() || !function->native_context(broker()).equals(
                                       broker()->target_native_context())) {
        return NoChange();
      }
      NativeContextRef native_context = function->native_context(broker());
      Node* global_proxy = jsgraph()->ConstantNoHole(
          native_context.global_proxy_object(broker()), broker());
      receiver = effect = graph()->NewNode(
          simplified()->ConvertReceiver(convert_mode), receiver,
          jsgraph()->ConstantNoHole(native_context, broker()), global_proxy,
          effect, control);
      NodeProperties::ReplaceValueInput(node, receiver, 1);
    }
    // Load the context from the {target}.
    Node* context = effect = graph()->NewNode(
        simplified()->LoadField(AccessBuilder::ForJSFunctionContext()), target,
        effect, control);
    NodeProperties::ReplaceContextInput(node, context);
    // Update the effect dependency for the {node}.
    NodeProperties::ReplaceEffectInput(node, effect);
    // Compute flags for the call.
    CallDescriptor::Flags flags = CallDescriptor::kNeedsFrameState;
    Node* new_target = jsgraph()->UndefinedConstant();
    // TODO(412398354): use the dispatch handle here to avoid a runtime check.
    int formal_count =
        shared->internal_formal_parameter_count_without_receiver_deprecated();
    if (formal_count > arity) {
      node->RemoveInput(n.FeedbackVectorIndex());
      // Underapplication. Massage the arguments to match the expected number of
      // arguments.
      for (int i = arity; i < formal_count; i++) {
        node->InsertInput(graph()->zone(), arity + 2,
                          jsgraph()->UndefinedConstant());
      }
      // Patch {node} to a direct call.
      node->InsertInput(graph()->zone(), formal_count + 2, new_target);
      node->InsertInput(graph()->zone(), formal_count + 3,
                        jsgraph()->ConstantNoHole(JSParameterCount(arity)));
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
      node->InsertInput(
          graph()->zone(), formal_count + 4,
          jsgraph()->ConstantNoHole(kPlaceholderDispatchHandle.value()));
#endif
      NodeProperties::ChangeOp(node,
                               common()->Call(Linkage::GetJSCallDescriptor(
                                   graph()->zone(), false, 1 + formal_count,
                                   flags | CallDescriptor::kCanUseRoots)));
    } else if (shared->HasBuiltinId() &&
               Builtins::IsCpp(shared->builtin_id())) {
      // Patch {node} to a direct CEntry call.
      ReduceBuiltin(jsgraph(), node, shared->builtin_id(), arity, flags);
    } else if (shared->HasBuiltinId()) {
      Builtin builtin = shared->builtin_id();
      DCHECK(Builtins::HasJSLinkage(builtin));
      // This SBXCHECK is a defense-in-depth measure to ensure that we always
      // generate valid calls here (with matching signatures).
      SBXCHECK_GE(arity + kJSArgcReceiverSlots,
                  Builtins::GetFormalParameterCount(builtin));
      // Patch {node} to a direct code object call.
      Callable callable = Builtins::CallableFor(isolate(), builtin);
      const CallInterfaceDescriptor& descriptor = callable.descriptor();
      auto call_descriptor = Linkage::GetStubCallDescriptor(
          graph()->zone(), descriptor, 1 + arity, flags);
      Node* stub_code = jsgraph()->HeapConstantNoHole(callable.code());
      node->RemoveInput(n.FeedbackVectorIndex());
      node->InsertInput(graph()->zone(), 0, stub_code); // Code object.
      node->InsertInput(graph()->zone(), 2, new_target);
      node->InsertInput(graph()->zone(), 3,
                        jsgraph()->ConstantNoHole(JSParameterCount(arity)));
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
      node->InsertInput(
          graph()->zone(), 4,
          jsgraph()->ConstantNoHole(kPlaceholderDispatchHandle.value()));
#endif
      NodeProperties::ChangeOp(node, common()->Call(call_descriptor));
    } else {
      // Patch {node} to a direct call.
      node->RemoveInput(n.FeedbackVectorIndex());
      node->InsertInput(graph()->zone(), arity + 2, new_target);
      node->InsertInput(graph()->zone(), arity + 3,
                        jsgraph()->ConstantNoHole(JSParameterCount(arity)));
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
      node->InsertInput(
          graph()->zone(), arity + 4,
          jsgraph()->ConstantNoHole(kPlaceholderDispatchHandle.value()));
#endif
      NodeProperties::ChangeOp(node,
                               common()->Call(Linkage::GetJSCallDescriptor(
                                   graph()->zone(), false, 1 + arity,
                                   flags | CallDescriptor::kCanUseRoots)));
    }
    return Changed(node);
  }
  // Check if {target} is a directly callable JSFunction.
  if (target_type.Is(Type::CallableFunction())) {
    // The node will change operators, remove the feedback vector.
    node->RemoveInput(n.FeedbackVectorIndex());
    // Compute flags for the call.
    CallDescriptor::Flags flags = CallDescriptor::kNeedsFrameState;
    // Patch {node} to an indirect call via the CallFunction builtin.
    Callable callable = CodeFactory::CallFunction(isolate(), convert_mode);
    node->InsertInput(graph()->zone(), 0,
                      jsgraph()->HeapConstantNoHole(callable.code()));
    node->InsertInput(graph()->zone(), 2,
                      jsgraph()->ConstantNoHole(JSParameterCount(arity)));
    NodeProperties::ChangeOp(
        node, common()->Call(Linkage::GetStubCallDescriptor(
                  graph()->zone(), callable.descriptor(), 1 + arity, flags)));
    return Changed(node);
  }
  // Maybe we did at least learn something about the {receiver}.
  if (p.convert_mode() != convert_mode) {
    NodeProperties::ChangeOp(
        node,
        javascript()->Call(p.arity(), p.frequency(), p.feedback(), convert_mode,
                           p.speculation_mode(), p.feedback_relation()));
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::CallParameters::arity(), v8::internal::compiler::CallParameters::arity_without_implicit_args(), v8::internal::compiler::Type::AsHeapConstant(), broker(), v8::internal::Builtins::CallableFor(), v8::internal::CodeFactory::CallFunction(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::Callable::code(), common(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::CallParameters::convert_mode(), v8::internal::DCHECK(), v8::internal::Callable::descriptor(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::CallParameters::feedback_relation(), v8::internal::compiler::FeedbackCellOf(), v8::internal::compiler::JSCallOrConstructNode::FeedbackVectorIndex(), v8::internal::flags, v8::internal::compiler::AccessBuilder::ForJSFunctionContext(), v8::internal::compiler::CallParameters::frequency(), v8::internal::Builtins::GetFormalParameterCount(), v8::internal::compiler::Linkage::GetJSCallDescriptor(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::NodeProperties::GetType(), graph(), v8::internal::Builtins::HasJSLinkage(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::compiler::JSGraph::HeapConstantNoHole(), v8::internal::compiler::Node::InsertInput(), v8::internal::compiler::Type::Is(), v8::internal::is_sloppy(), v8::internal::IsClassConstructor(), v8::internal::Builtins::IsCpp(), v8::internal::compiler::Type::IsHeapConstant(), isolate(), javascript(), jsgraph(), v8::internal::JSParameterCount(), v8::internal::compiler::CallDescriptor::kCanUseRoots, v8::internal::kJSArgcReceiverSlots, v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::kNotNullOrUndefined, v8::internal::kNullOrUndefined, v8::internal::kPlaceholderDispatchHandle(), v8::internal::compiler::MakeRef(), v8::internal::compiler::Type::Maybe(), v8::internal::native_context, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), v8::internal::compiler::HeapConstantType::Ref(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::NodeProperties::ReplaceContextInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), SBXCHECK_GE, v8::internal::compiler::FeedbackCellRef::shared_function_info(), v8::internal::compiler::CreateClosureParameters::shared_info(), simplified(), v8::internal::compiler::CallParameters::speculation_mode(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::base::StrongAlias< TagType, UnderlyingType >::value().
Referenced by Reduce().
ReduceJSCallForwardVarargs()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSCallForwardVarargs (Node * node) [private]
Definition at line 1989 of file js-typed-lowering.cc.
                                                                {
  DCHECK_EQ(IrOpcode::kJSCallForwardVarargs, node->opcode());
  CallForwardVarargsParameters p = CallForwardVarargsParametersOf(node->op());
  DCHECK_LE(2u, p.arity());
  int const arity = static_cast<int>(p.arity() - 2);
  int const start_index = static_cast<int>(p.start_index());
  Node* target = NodeProperties::GetValueInput(node, 0);
  Type target_type = NodeProperties::GetType(target);
  // Check if {target} is a directly callable JSFunction.
  if (target_type.Is(Type::CallableFunction())) {
    // Compute flags for the call.
    CallDescriptor::Flags flags = CallDescriptor::kNeedsFrameState;
    // Patch {node} to an indirect call via CallFunctionForwardVarargs.
    Callable callable = CodeFactory::CallFunctionForwardVarargs(isolate());
    node->InsertInput(graph()->zone(), 0,
                      jsgraph()->HeapConstantNoHole(callable.code()));
    node->InsertInput(graph()->zone(), 2,
                      jsgraph()->ConstantNoHole(JSParameterCount(arity)));
    node->InsertInput(graph()->zone(), 3,
                      jsgraph()->ConstantNoHole(start_index));
    NodeProperties::ChangeOp(
        node, common()->Call(Linkage::GetStubCallDescriptor(
                  graph()->zone(), callable.descriptor(), arity + 1, flags)));
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::CallForwardVarargsParameters::arity(), v8::internal::compiler::CallForwardVarargsParametersOf(), v8::internal::CodeFactory::CallFunctionForwardVarargs(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::Callable::code(), common(), DCHECK_EQ, DCHECK_LE, v8::internal::Callable::descriptor(), v8::internal::flags, v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::compiler::Node::InsertInput(), v8::internal::compiler::Type::Is(), isolate(), jsgraph(), v8::internal::JSParameterCount(), v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::CallForwardVarargsParameters::start_index().
Referenced by Reduce().
ReduceJSComparison()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSComparison (Node * node) [private]
Definition at line 880 of file js-typed-lowering.cc.
                                                        {
  JSBinopReduction r(this, node);
  if (r.BothInputsAre(Type::String())) {
    // If both inputs are definitely strings, perform a string comparison.
    const Operator* stringOp;
    switch (node->opcode()) {
      case IrOpcode::kJSLessThan:
        stringOp = simplified()->StringLessThan();
        break;
      case IrOpcode::kJSGreaterThan:
        stringOp = simplified()->StringLessThan();
        r.SwapInputs(); // a > b => b < a
        break;
      case IrOpcode::kJSLessThanOrEqual:
        stringOp = simplified()->StringLessThanOrEqual();
        break;
      case IrOpcode::kJSGreaterThanOrEqual:
        stringOp = simplified()->StringLessThanOrEqual();
        r.SwapInputs(); // a >= b => b <= a
        break;
      default:
        return NoChange();
    }
    r.ChangeToPureOperator(stringOp);
    return Changed(node);
  }
  const Operator* less_than;
  const Operator* less_than_or_equal;
  if (r.BothInputsAre(Type::Signed32()) ||
      r.BothInputsAre(Type::Unsigned32())) {
    less_than = simplified()->NumberLessThan();
    less_than_or_equal = simplified()->NumberLessThanOrEqual();
  } else if (r.OneInputCannotBe(Type::StringOrReceiver()) &&
             r.BothInputsAre(Type::PlainPrimitive())) {
    r.ConvertInputsToNumber();
    less_than = simplified()->NumberLessThan();
    less_than_or_equal = simplified()->NumberLessThanOrEqual();
  } else if (r.IsStringCompareOperation()) {
    r.CheckInputsToString();
    less_than = simplified()->StringLessThan();
    less_than_or_equal = simplified()->StringLessThanOrEqual();
  } else {
    return NoChange();
  }
  const Operator* comparison;
  switch (node->opcode()) {
    case IrOpcode::kJSLessThan:
      comparison = less_than;
      break;
    case IrOpcode::kJSGreaterThan:
      comparison = less_than;
      r.SwapInputs(); // a > b => b < a
      break;
    case IrOpcode::kJSLessThanOrEqual:
      comparison = less_than_or_equal;
      break;
    case IrOpcode::kJSGreaterThanOrEqual:
      comparison = less_than_or_equal;
      r.SwapInputs(); // a >= b => b <= a
      break;
    default:
      return NoChange();
  }
  return r.ChangeToPureOperator(comparison);
}
References v8::internal::compiler::JSBinopReduction::BothInputsAre(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::CheckInputsToString(), v8::internal::compiler::JSBinopReduction::ConvertInputsToNumber(), v8::internal::compiler::JSBinopReduction::IsStringCompareOperation(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberLessThan(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberLessThanOrEqual(), v8::internal::compiler::JSBinopReduction::OneInputCannotBe(), v8::internal::compiler::Node::opcode(), simplified(), v8::internal::compiler::SimplifiedOperatorBuilder::StringLessThan(), v8::internal::compiler::SimplifiedOperatorBuilder::StringLessThanOrEqual(), and v8::internal::compiler::JSBinopReduction::SwapInputs().
Referenced by Reduce().
ReduceJSConstruct()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSConstruct (Node * node) [private]
Definition at line 1951 of file js-typed-lowering.cc.
                                                       {
  JSConstructNode n(node);
  ConstructParameters const& p = n.Parameters();
  int const arity = p.arity_without_implicit_args();
  Node* target = n.target();
  Type target_type = NodeProperties::GetType(target);
  // Check if {target} is a known JSFunction.
  if (target_type.IsHeapConstant() &&
      target_type.AsHeapConstant()->Ref().IsJSFunction()) {
    JSFunctionRef function = target_type.AsHeapConstant()->Ref().AsJSFunction();
    // Only optimize [[Construct]] here if {function} is a Constructor.
    if (!function.map(broker()).is_constructor()) return NoChange();
    // Patch {node} to an indirect call via the {function}s construct stub.
    Callable callable = Builtins::CallableFor(
        isolate(), function.shared(broker()).construct_as_builtin()
                       ? Builtin::kJSBuiltinsConstructStub
                       : Builtin::kJSConstructStubGeneric);
    static_assert(JSConstructNode::TargetIndex() == 0);
    static_assert(JSConstructNode::NewTargetIndex() == 1);
    node->RemoveInput(n.FeedbackVectorIndex());
    node->InsertInput(graph()->zone(), 0,
                      jsgraph()->HeapConstantNoHole(callable.code()));
    node->InsertInput(graph()->zone(), 3,
                      jsgraph()->ConstantNoHole(JSParameterCount(arity)));
    node->InsertInput(graph()->zone(), 4, jsgraph()->UndefinedConstant());
    NodeProperties::ChangeOp(
        node, common()->Call(Linkage::GetStubCallDescriptor(
                  graph()->zone(), callable.descriptor(), 1 + arity,
                  CallDescriptor::kNeedsFrameState)));
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::ConstructParameters::arity_without_implicit_args(), v8::internal::compiler::Type::AsHeapConstant(), broker(), v8::internal::Builtins::CallableFor(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::Callable::code(), common(), v8::internal::Callable::descriptor(), v8::internal::compiler::JSCallOrConstructNode::FeedbackVectorIndex(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::NodeProperties::GetType(), graph(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::compiler::Node::InsertInput(), v8::internal::is_constructor, v8::internal::compiler::Type::IsHeapConstant(), isolate(), jsgraph(), v8::internal::JSParameterCount(), v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::JSConstructNodeBase< kOpcode >::Parameters(), v8::internal::compiler::HeapConstantType::Ref(), v8::internal::compiler::Node::RemoveInput(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by Reduce().
ReduceJSConstructForwardVarargs()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs (Node * node) [private]
Definition at line 1916 of file js-typed-lowering.cc.
                                                                     {
  DCHECK_EQ(IrOpcode::kJSConstructForwardVarargs, node->opcode());
  ConstructForwardVarargsParameters p =
      ConstructForwardVarargsParametersOf(node->op());
  DCHECK_LE(2u, p.arity());
  int const arity = static_cast<int>(p.arity() - 2);
  int const start_index = static_cast<int>(p.start_index());
  Node* target = NodeProperties::GetValueInput(node, 0);
  Type target_type = NodeProperties::GetType(target);
  // Check if {target} is a JSFunction.
  if (target_type.IsHeapConstant() &&
      target_type.AsHeapConstant()->Ref().IsJSFunction()) {
    // Only optimize [[Construct]] here if {function} is a Constructor.
    JSFunctionRef function = target_type.AsHeapConstant()->Ref().AsJSFunction();
    if (!function.map(broker()).is_constructor()) return NoChange();
    // Patch {node} to an indirect call via ConstructFunctionForwardVarargs.
    Callable callable = CodeFactory::ConstructFunctionForwardVarargs(isolate());
    node->InsertInput(graph()->zone(), 0,
                      jsgraph()->HeapConstantNoHole(callable.code()));
    node->InsertInput(graph()->zone(), 3,
                      jsgraph()->ConstantNoHole(JSParameterCount(arity)));
    node->InsertInput(graph()->zone(), 4,
                      jsgraph()->ConstantNoHole(start_index));
    node->InsertInput(graph()->zone(), 5, jsgraph()->UndefinedConstant());
    NodeProperties::ChangeOp(
        node, common()->Call(Linkage::GetStubCallDescriptor(
                  graph()->zone(), callable.descriptor(), arity + 1,
                  CallDescriptor::kNeedsFrameState)));
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::ConstructForwardVarargsParameters::arity(), v8::internal::compiler::Type::AsHeapConstant(), broker(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::Callable::code(), common(), v8::internal::compiler::ConstructForwardVarargsParametersOf(), v8::internal::CodeFactory::ConstructFunctionForwardVarargs(), DCHECK_EQ, DCHECK_LE, v8::internal::Callable::descriptor(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::compiler::Node::InsertInput(), v8::internal::is_constructor, v8::internal::compiler::Type::IsHeapConstant(), isolate(), jsgraph(), v8::internal::JSParameterCount(), v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapConstantType::Ref(), v8::internal::compiler::ConstructForwardVarargsParameters::start_index(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by Reduce().
ReduceJSDecrement()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSDecrement (Node * node) [private]
Definition at line 577 of file js-typed-lowering.cc.
                                                       {
  Node* input = NodeProperties::GetValueInput(node, 0);
  Type input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::PlainPrimitive())) {
    // JSDecrement(x) => NumberSubtract(ToNumber(x), 1)
    const FeedbackParameter& p = FeedbackParameterOf(node->op());
    node->InsertInput(graph()->zone(), 1, jsgraph()->OneConstant());
    NodeProperties::ChangeOp(node, javascript()->Subtract(p.feedback()));
    JSBinopReduction r(this, node);
    r.ConvertInputsToNumber();
    DCHECK_EQ(simplified()->NumberSubtract(), r.NumberOp());
    return r.ChangeToPureOperator(r.NumberOp(), Type::Number());
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ConvertInputsToNumber(), DCHECK_EQ, v8::internal::compiler::FeedbackParameter::feedback(), v8::internal::compiler::FeedbackParameterOf(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::Node::InsertInput(), v8::internal::compiler::Type::Is(), javascript(), jsgraph(), v8::internal::compiler::JSBinopReduction::NumberOp(), v8::internal::compiler::Node::op(), simplified(), and v8::bigint::Subtract().
Referenced by Reduce().
ReduceJSEqual()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSEqual (Node * node) [private]
Definition at line 947 of file js-typed-lowering.cc.
                                                   {
  JSBinopReduction r(this, node);
  if (r.BothInputsAre(Type::UniqueName())) {
    return r.ChangeToPureOperator(simplified()->ReferenceEqual());
  }
  if (r.IsInternalizedStringCompareOperation()) {
    r.CheckInputsToInternalizedString();
    return r.ChangeToPureOperator(simplified()->ReferenceEqual());
  }
  if (r.BothInputsAre(Type::String())) {
    return r.ChangeToPureOperator(simplified()->StringEqual());
  }
  if (r.BothInputsAre(Type::Boolean())) {
    return r.ChangeToPureOperator(simplified()->ReferenceEqual());
  }
  if (r.BothInputsAre(Type::Receiver())) {
    return r.ChangeToPureOperator(simplified()->ReferenceEqual());
  }
  if (r.OneInputIs(Type::NullOrUndefined())) {
    RelaxEffectsAndControls(node);
    node->RemoveInput(r.LeftInputIs(Type::NullOrUndefined()) ? 0 : 1);
    node->TrimInputCount(1);
    NodeProperties::ChangeOp(node, simplified()->ObjectIsUndetectable());
    return Changed(node);
  }
  if (r.BothInputsAre(Type::Signed32()) ||
      r.BothInputsAre(Type::Unsigned32())) {
    return r.ChangeToPureOperator(simplified()->NumberEqual());
  } else if (r.BothInputsAre(Type::Number())) {
    return r.ChangeToPureOperator(simplified()->NumberEqual());
  } else if (r.IsReceiverCompareOperation()) {
    r.CheckInputsToReceiver();
    return r.ChangeToPureOperator(simplified()->ReferenceEqual());
  } else if (r.IsReceiverOrNullOrUndefinedCompareOperation()) {
    // Check that both inputs are Receiver, Null or Undefined.
    r.CheckInputsToReceiverOrNullOrUndefined();
    // If one side is known to be a detectable receiver now, we
    // can simply perform reference equality here, since this
    // known detectable receiver is going to only match itself.
    if (r.OneInputIs(Type::DetectableReceiver())) {
      return r.ChangeToPureOperator(simplified()->ReferenceEqual());
    }
    // Known that both sides are Receiver, Null or Undefined, the
    // abstract equality operation can be performed like this:
    //
    // if left == undefined || left == null
    // then ObjectIsUndetectable(right)
    // else if right == undefined || right == null
    // then ObjectIsUndetectable(left)
    // else ReferenceEqual(left, right)
#define __ gasm.
    JSGraphAssembler gasm(broker(), jsgraph(), jsgraph()->zone(),
                          BranchSemantics::kJS);
    gasm.InitializeEffectControl(r.effect(), r.control());
    auto lhs = TNode<Object>::UncheckedCast(r.left());
    auto rhs = TNode<Object>::UncheckedCast(r.right());
    auto done = __ MakeLabel(MachineRepresentation::kTagged);
    auto check_undetectable = __ MakeLabel(MachineRepresentation::kTagged);
    __ GotoIf(__ ReferenceEqual(lhs, __ UndefinedConstant()),
              &check_undetectable, rhs);
    __ GotoIf(__ ReferenceEqual(lhs, __ NullConstant()), &check_undetectable,
              rhs);
    __ GotoIf(__ ReferenceEqual(rhs, __ UndefinedConstant()),
              &check_undetectable, lhs);
    __ GotoIf(__ ReferenceEqual(rhs, __ NullConstant()), &check_undetectable,
              lhs);
    __ Goto(&done, __ ReferenceEqual(lhs, rhs));
    __ Bind(&check_undetectable);
    __ Goto(&done,
            __ ObjectIsUndetectable(check_undetectable.PhiAt<Object>(0)));
    __ Bind(&done);
    Node* value = done.PhiAt(0);
    ReplaceWithValue(node, value, gasm.effect(), gasm.control());
    return Replace(value);
#undef __
  } else if (r.IsStringCompareOperation()) {
    r.CheckInputsToString();
    return r.ChangeToPureOperator(simplified()->StringEqual());
  } else if (r.IsSymbolCompareOperation()) {
    r.CheckInputsToSymbol();
    return r.ChangeToPureOperator(simplified()->ReferenceEqual());
  }
  return NoChange();
}
References __, v8::internal::compiler::JSBinopReduction::BothInputsAre(), broker(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::CheckInputsToInternalizedString(), v8::internal::compiler::JSBinopReduction::CheckInputsToReceiver(), v8::internal::compiler::JSBinopReduction::CheckInputsToReceiverOrNullOrUndefined(), v8::internal::compiler::JSBinopReduction::CheckInputsToString(), v8::internal::compiler::JSBinopReduction::CheckInputsToSymbol(), v8::internal::compiler::JSBinopReduction::control(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::JSBinopReduction::effect(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), v8::internal::compiler::JSBinopReduction::IsInternalizedStringCompareOperation(), v8::internal::compiler::JSBinopReduction::IsReceiverCompareOperation(), v8::internal::compiler::JSBinopReduction::IsReceiverOrNullOrUndefinedCompareOperation(), v8::internal::compiler::JSBinopReduction::IsStringCompareOperation(), v8::internal::compiler::JSBinopReduction::IsSymbolCompareOperation(), jsgraph(), v8::internal::compiler::kJS, v8::internal::kTagged, v8::internal::compiler::JSBinopReduction::left(), v8::internal::compiler::JSBinopReduction::LeftInputIs(), v8::internal::compiler::JSBinopReduction::OneInputIs(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::JSBinopReduction::right(), simplified(), v8::internal::compiler::Node::TrimInputCount(), v8::internal::TNode< T >::UncheckedCast(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::value.
Referenced by Reduce().
ReduceJSForInNext()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSForInNext (Node * node) [private]
Definition at line 2204 of file js-typed-lowering.cc.
                                                       {
  JSForInNextNode n(node);
  Node* receiver = n.receiver();
  Node* cache_array = n.cache_array();
  Node* cache_type = n.cache_type();
  Node* index = n.index();
  Node* context = n.context();
  FrameState frame_state = n.frame_state();
  Effect effect = n.effect();
  Control control = n.control();
  // Load the map of the {receiver}.
  Node* receiver_map = effect =
      graph()->NewNode(simplified()->LoadField(AccessBuilder::ForMap()),
                       receiver, effect, control);
  switch (n.Parameters().mode()) {
    case ForInMode::kUseEnumCacheKeys:
    case ForInMode::kUseEnumCacheKeysAndIndices: {
      // Ensure that the expected map still matches that of the {receiver}.
      Node* check = graph()->NewNode(simplified()->ReferenceEqual(),
                                     receiver_map, cache_type);
      effect =
          graph()->NewNode(simplified()->CheckIf(DeoptimizeReason::kWrongMap),
                           check, effect, control);
      // Since the change to LoadElement() below is effectful, we connect
      // node to all effect uses.
      ReplaceWithValue(node, node, node, control);
      // Morph the {node} into a LoadElement.
      node->ReplaceInput(0, cache_array);
      node->ReplaceInput(1, index);
      node->ReplaceInput(2, effect);
      node->ReplaceInput(3, control);
      node->TrimInputCount(4);
      ElementAccess access =
          AccessBuilder::ForJSForInCacheArrayElement(n.Parameters().mode());
      NodeProperties::ChangeOp(node, simplified()->LoadElement(access));
      NodeProperties::SetType(node, access.type);
      break;
    }
    case ForInMode::kGeneric: {
      // Load the next {key} from the {cache_array}.
      Node* key = effect = graph()->NewNode(
          simplified()->LoadElement(AccessBuilder::ForJSForInCacheArrayElement(
              n.Parameters().mode())),
          cache_array, index, effect, control);
      // Check if the expected map still matches that of the {receiver}.
      Node* check = graph()->NewNode(simplified()->ReferenceEqual(),
                                     receiver_map, cache_type);
      Node* branch =
          graph()->NewNode(common()->Branch(BranchHint::kTrue), check, control);
      Node* if_true = graph()->NewNode(common()->IfTrue(), branch);
      Node* etrue;
      Node* vtrue;
      {
        // Don't need filtering since expected map still matches that of the
        // {receiver}.
        etrue = effect;
        vtrue = key;
      }
      Node* if_false = graph()->NewNode(common()->IfFalse(), branch);
      Node* efalse;
      Node* vfalse;
      {
        // Filter the {key} to check if it's still a valid property of the
        // {receiver} (does the ToName conversion implicitly).
        Callable const callable =
            Builtins::CallableFor(isolate(), Builtin::kForInFilter);
        auto call_descriptor = Linkage::GetStubCallDescriptor(
            graph()->zone(), callable.descriptor(),
            callable.descriptor().GetStackParameterCount(),
            CallDescriptor::kNeedsFrameState);
        vfalse = efalse = if_false = graph()->NewNode(
            common()->Call(call_descriptor),
            jsgraph()->HeapConstantNoHole(callable.code()), key, receiver,
            context, frame_state, effect, if_false);
        NodeProperties::SetType(
            vfalse,
            Type::Union(Type::String(), Type::Undefined(), graph()->zone()));
        // Update potential {IfException} uses of {node} to point to the above
        // ForInFilter stub call node instead.
        Node* if_exception = nullptr;
        if (NodeProperties::IsExceptionalCall(node, &if_exception)) {
          if_false = graph()->NewNode(common()->IfSuccess(), vfalse);
          NodeProperties::ReplaceControlInput(if_exception, vfalse);
          NodeProperties::ReplaceEffectInput(if_exception, efalse);
          Revisit(if_exception);
        }
      }
      control = graph()->NewNode(common()->Merge(2), if_true, if_false);
      effect = graph()->NewNode(common()->EffectPhi(2), etrue, efalse, control);
      ReplaceWithValue(node, node, effect, control);
      // Morph the {node} into a Phi.
      node->ReplaceInput(0, vtrue);
      node->ReplaceInput(1, vfalse);
      node->ReplaceInput(2, control);
      node->TrimInputCount(3);
      NodeProperties::ChangeOp(
          node, common()->Phi(MachineRepresentation::kTagged, 2));
    }
  }
  return Changed(node);
}
References v8::internal::Builtins::CallableFor(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::Callable::code(), common(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::Callable::descriptor(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::AccessBuilder::ForJSForInCacheArrayElement(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), graph(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::index, v8::internal::compiler::NodeProperties::IsExceptionalCall(), isolate(), jsgraph(), v8::internal::key, v8::internal::compiler::kGeneric, v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::kTagged, v8::internal::kTrue, v8::internal::compiler::kUseEnumCacheKeys, v8::internal::compiler::kUseEnumCacheKeysAndIndices, v8::internal::compiler::ForInParameters::mode(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::JSForInNextNode::Parameters(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::NodeProperties::SetType(), simplified(), v8::internal::compiler::Node::TrimInputCount(), v8::internal::compiler::ElementAccess::type, v8::internal::compiler::Undefined, and v8::internal::compiler::Type::Union().
Referenced by Reduce().
ReduceJSForInPrepare()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare (Node * node) [private]
Definition at line 2317 of file js-typed-lowering.cc.
                                                          {
  JSForInPrepareNode n(node);
  Node* enumerator = n.enumerator();
  Effect effect = n.effect();
  Control control = n.control();
  Node* cache_type = enumerator;
  Node* cache_array = nullptr;
  Node* cache_length = nullptr;
  switch (n.Parameters().mode()) {
    case ForInMode::kUseEnumCacheKeys:
    case ForInMode::kUseEnumCacheKeysAndIndices: {
      // Check that the {enumerator} is a Map.
      // The direct IsMap check requires reading of an instance type, so we
      // compare its map against fixed_array_map instead (by definition,
      // the {enumerator} is either the receiver's Map or a FixedArray).
      Node* check_for_fixed_array = effect =
          graph()->NewNode(simplified()->CompareMaps(
                               ZoneRefSet<Map>(broker()->fixed_array_map())),
                           enumerator, effect, control);
      Node* check_for_not_fixed_array =
          graph()->NewNode(simplified()->BooleanNot(), check_for_fixed_array);
      effect =
          graph()->NewNode(simplified()->CheckIf(DeoptimizeReason::kWrongMap),
                           check_for_not_fixed_array, effect, control);
      // Load the enum cache from the {enumerator} map.
      Node* descriptor_array = effect = graph()->NewNode(
          simplified()->LoadField(AccessBuilder::ForMapDescriptors()),
          enumerator, effect, control);
      Node* enum_cache = effect = graph()->NewNode(
          simplified()->LoadField(AccessBuilder::ForDescriptorArrayEnumCache()),
          descriptor_array, effect, control);
      cache_array = effect = graph()->NewNode(
          simplified()->LoadField(AccessBuilder::ForEnumCacheKeys()),
          enum_cache, effect, control);
      // Load the enum length of the {enumerator} map.
      Node* bit_field3 = effect = graph()->NewNode(
          simplified()->LoadField(AccessBuilder::ForMapBitField3()), enumerator,
          effect, control);
      static_assert(Map::Bits3::EnumLengthBits::kShift == 0);
      cache_length = graph()->NewNode(
          simplified()->NumberBitwiseAnd(), bit_field3,
          jsgraph()->ConstantNoHole(Map::Bits3::EnumLengthBits::kMask));
      break;
    }
    case ForInMode::kGeneric: {
      // Check if the {enumerator} is a Map or a FixedArray.
      // The direct IsMap check requires reading of an instance type, so we
      // compare against fixed array map instead (by definition,
      // the {enumerator} is either the receiver's Map or a FixedArray).
      Node* check = effect =
          graph()->NewNode(simplified()->CompareMaps(
                               ZoneRefSet<Map>(broker()->fixed_array_map())),
                           enumerator, effect, control);
      Node* branch = graph()->NewNode(common()->Branch(BranchHint::kFalse),
                                      check, control);
      Node* if_map = graph()->NewNode(common()->IfFalse(), branch);
      Node* etrue = effect;
      Node* cache_array_true;
      Node* cache_length_true;
      {
        // Load the enum cache from the {enumerator} map.
        Node* descriptor_array = etrue = graph()->NewNode(
            simplified()->LoadField(AccessBuilder::ForMapDescriptors()),
            enumerator, etrue, if_map);
        Node* enum_cache = etrue =
            graph()->NewNode(simplified()->LoadField(
                                 AccessBuilder::ForDescriptorArrayEnumCache()),
                             descriptor_array, etrue, if_map);
        cache_array_true = etrue = graph()->NewNode(
            simplified()->LoadField(AccessBuilder::ForEnumCacheKeys()),
            enum_cache, etrue, if_map);
        // Load the enum length of the {enumerator} map.
        Node* bit_field3 = etrue = graph()->NewNode(
            simplified()->LoadField(AccessBuilder::ForMapBitField3()),
            enumerator, etrue, if_map);
        static_assert(Map::Bits3::EnumLengthBits::kShift == 0);
        cache_length_true = graph()->NewNode(
            simplified()->NumberBitwiseAnd(), bit_field3,
            jsgraph()->ConstantNoHole(Map::Bits3::EnumLengthBits::kMask));
      }
      Node* if_fixed_array = graph()->NewNode(common()->IfTrue(), branch);
      Node* efalse = effect;
      Node* cache_array_false;
      Node* cache_length_false;
      {
        // The {enumerator} is the FixedArray with the keys to iterate.
        cache_array_false = enumerator;
        cache_length_false = efalse = graph()->NewNode(
            simplified()->LoadField(AccessBuilder::ForFixedArrayLength()),
            cache_array_false, efalse, if_fixed_array);
      }
      // Rewrite the uses of the {node}.
      control = graph()->NewNode(common()->Merge(2), if_map, if_fixed_array);
      effect = graph()->NewNode(common()->EffectPhi(2), etrue, efalse, control);
      cache_array =
          graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                           cache_array_true, cache_array_false, control);
      cache_length =
          graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                           cache_length_true, cache_length_false, control);
      break;
    }
  }
  // Update the uses of {node}.
  for (Edge edge : node->use_edges()) {
    Node* const user = edge.from();
    if (NodeProperties::IsEffectEdge(edge)) {
      edge.UpdateTo(effect);
      Revisit(user);
    } else if (NodeProperties::IsControlEdge(edge)) {
      edge.UpdateTo(control);
      Revisit(user);
    } else {
      DCHECK(NodeProperties::IsValueEdge(edge));
      switch (ProjectionIndexOf(user->op())) {
        case 0:
          Replace(user, cache_type);
          break;
        case 1:
          Replace(user, cache_array);
          break;
        case 2:
          Replace(user, cache_length);
          break;
        default:
          UNREACHABLE();
      }
    }
  }
  node->Kill();
  return Replace(effect);
}
References v8::internal::compiler::bit_field3, broker(), common(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::DCHECK(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::AccessBuilder::ForDescriptorArrayEnumCache(), v8::internal::compiler::AccessBuilder::ForEnumCacheKeys(), v8::internal::compiler::AccessBuilder::ForFixedArrayLength(), v8::internal::compiler::AccessBuilder::ForMapBitField3(), v8::internal::compiler::AccessBuilder::ForMapDescriptors(), graph(), v8::internal::compiler::NodeProperties::IsControlEdge(), v8::internal::compiler::NodeProperties::IsEffectEdge(), v8::internal::compiler::NodeProperties::IsValueEdge(), jsgraph(), v8::internal::kFalse, v8::internal::compiler::kGeneric, v8::internal::compiler::Node::Kill(), v8::internal::kTagged, v8::internal::compiler::kUseEnumCacheKeys, v8::internal::compiler::kUseEnumCacheKeysAndIndices, v8::internal::compiler::ForInParameters::mode(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::JSForInPrepareNode::Parameters(), v8::internal::compiler::ProjectionIndexOf(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), simplified(), v8::internal::UNREACHABLE(), and v8::internal::compiler::Node::use_edges().
Referenced by Reduce().
ReduceJSGeneratorRestoreContextNoCell()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContextNoCell (Node * node) [private]
Definition at line 2539 of file js-typed-lowering.cc.
                                                                           {
  DCHECK_EQ(IrOpcode::kJSGeneratorRestoreContextNoCell, node->opcode());
  const Operator* new_op =
      simplified()->LoadField(AccessBuilder::ForJSGeneratorObjectContext());
  // Mutate the node in-place.
  DCHECK(OperatorProperties::HasContextInput(node->op()));
  DCHECK(!OperatorProperties::HasContextInput(new_op));
  node->RemoveInput(NodeProperties::FirstContextIndex(node));
  NodeProperties::ChangeOp(node, new_op);
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::NodeProperties::FirstContextIndex(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectContext(), v8::internal::compiler::OperatorProperties::HasContextInput(), v8::internal::compiler::SimplifiedOperatorBuilder::LoadField(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::RemoveInput(), and simplified().
Referenced by Reduce().
ReduceJSGeneratorRestoreContinuation()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContinuation (Node * node) [private]
Definition at line 2519 of file js-typed-lowering.cc.
                                                                          {
  DCHECK_EQ(IrOpcode::kJSGeneratorRestoreContinuation, node->opcode());
  Node* generator = NodeProperties::GetValueInput(node, 0);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  FieldAccess continuation_field =
      AccessBuilder::ForJSGeneratorObjectContinuation();
  Node* continuation = effect = graph()->NewNode(
      simplified()->LoadField(continuation_field), generator, effect, control);
  Node* executing =
      jsgraph()->ConstantNoHole(JSGeneratorObject::kGeneratorExecuting);
  effect = graph()->NewNode(simplified()->StoreField(continuation_field),
                            generator, executing, effect, control);
  ReplaceWithValue(node, continuation, effect, control);
  return Changed(continuation);
}
References v8::internal::compiler::JSGraph::ConstantNoHole(), DCHECK_EQ, v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectContinuation(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), jsgraph(), v8::internal::JSGeneratorObject::kGeneratorExecuting, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::opcode(), and simplified().
Referenced by Reduce().
ReduceJSGeneratorRestoreInputOrDebugPos()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreInputOrDebugPos (Node * node) [private]
Definition at line 2577 of file js-typed-lowering.cc.
                                                                             {
  DCHECK_EQ(IrOpcode::kJSGeneratorRestoreInputOrDebugPos, node->opcode());
  FieldAccess input_or_debug_pos_field =
      AccessBuilder::ForJSGeneratorObjectInputOrDebugPos();
  const Operator* new_op = simplified()->LoadField(input_or_debug_pos_field);
  // Mutate the node in-place.
  DCHECK(OperatorProperties::HasContextInput(node->op()));
  DCHECK(!OperatorProperties::HasContextInput(new_op));
  node->RemoveInput(NodeProperties::FirstContextIndex(node));
  NodeProperties::ChangeOp(node, new_op);
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::NodeProperties::FirstContextIndex(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectInputOrDebugPos(), v8::internal::compiler::OperatorProperties::HasContextInput(), v8::internal::compiler::SimplifiedOperatorBuilder::LoadField(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::RemoveInput(), and simplified().
Referenced by Reduce().
ReduceJSGeneratorRestoreRegister()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreRegister (Node * node) [private]
Definition at line 2554 of file js-typed-lowering.cc.
                                                                      {
  DCHECK_EQ(IrOpcode::kJSGeneratorRestoreRegister, node->opcode());
  Node* generator = NodeProperties::GetValueInput(node, 0);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  int index = RestoreRegisterIndexOf(node->op());
  FieldAccess array_field =
      AccessBuilder::ForJSGeneratorObjectParametersAndRegisters();
  FieldAccess element_field = AccessBuilder::ForFixedArraySlot(index);
  Node* array = effect = graph()->NewNode(simplified()->LoadField(array_field),
                                          generator, effect, control);
  Node* element = effect = graph()->NewNode(
      simplified()->LoadField(element_field), array, effect, control);
  Node* stale = jsgraph()->StaleRegisterConstant();
  effect = graph()->NewNode(simplified()->StoreField(element_field), array,
                            stale, effect, control);
  ReplaceWithValue(node, element, effect, control);
  return Changed(element);
}
References DCHECK_EQ, v8::internal::compiler::AccessBuilder::ForFixedArraySlot(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectParametersAndRegisters(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::index, jsgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::RestoreRegisterIndexOf(), and simplified().
Referenced by Reduce().
ReduceJSGeneratorStore()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorStore (Node * node) [private]
Definition at line 2478 of file js-typed-lowering.cc.
                                                            {
  DCHECK_EQ(IrOpcode::kJSGeneratorStore, node->opcode());
  Node* generator = NodeProperties::GetValueInput(node, 0);
  Node* continuation = NodeProperties::GetValueInput(node, 1);
  Node* offset = NodeProperties::GetValueInput(node, 2);
  Node* context = NodeProperties::GetContextInput(node);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  int value_count = GeneratorStoreValueCountOf(node->op());
  FieldAccess array_field =
      AccessBuilder::ForJSGeneratorObjectParametersAndRegisters();
  FieldAccess context_field = AccessBuilder::ForJSGeneratorObjectContext();
  FieldAccess continuation_field =
      AccessBuilder::ForJSGeneratorObjectContinuation();
  FieldAccess input_or_debug_pos_field =
      AccessBuilder::ForJSGeneratorObjectInputOrDebugPos();
  Node* array = effect = graph()->NewNode(simplified()->LoadField(array_field),
                                          generator, effect, control);
  for (int i = 0; i < value_count; ++i) {
    Node* value = NodeProperties::GetValueInput(node, 3 + i);
    if (value != jsgraph()->OptimizedOutConstant()) {
      effect = graph()->NewNode(
          simplified()->StoreField(AccessBuilder::ForFixedArraySlot(i)), array,
          value, effect, control);
    }
  }
  effect = graph()->NewNode(simplified()->StoreField(context_field), generator,
                            context, effect, control);
  effect = graph()->NewNode(simplified()->StoreField(continuation_field),
                            generator, continuation, effect, control);
  effect = graph()->NewNode(simplified()->StoreField(input_or_debug_pos_field),
                            generator, offset, effect, control);
  ReplaceWithValue(node, effect, effect, control);
  return Changed(effect);
}
References DCHECK_EQ, v8::internal::compiler::AccessBuilder::ForFixedArraySlot(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectContext(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectContinuation(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectInputOrDebugPos(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectParametersAndRegisters(), v8::internal::compiler::GeneratorStoreValueCountOf(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, jsgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), simplified(), and v8::internal::value.
Referenced by Reduce().
ReduceJSHasContextExtension()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension (Node * node) [private]
Definition at line 1561 of file js-typed-lowering.cc.
                                                                 {
  DCHECK_EQ(IrOpcode::kJSHasContextExtension, node->opcode());
  size_t depth = OpParameter<size_t>(node->op());
  Node* effect = NodeProperties::GetEffectInput(node);
  TNode<Context> context =
      TNode<Context>::UncheckedCast(NodeProperties::GetContextInput(node));
  Node* control = graph()->start();
  JSGraphAssembler gasm(broker(), jsgraph_, jsgraph_->zone(),
                        BranchSemantics::kJS);
  gasm.InitializeEffectControl(effect, control);
  for (size_t i = 0; i < depth; ++i) {
    context = gasm.LoadField<Context>(
        AccessBuilder::ForContextSlotKnownPointer(Context::PREVIOUS_INDEX),
        context);
  }
  TNode<ScopeInfo> scope_info = gasm.LoadField<ScopeInfo>(
      AccessBuilder::ForContextSlot(Context::SCOPE_INFO_INDEX), context);
  TNode<Word32T> scope_info_flags = gasm.EnterMachineGraph<Word32T>(
      gasm.LoadField<Word32T>(AccessBuilder::ForScopeInfoFlags(), scope_info),
      UseInfo::TruncatingWord32());
  TNode<Word32T> flags_masked = gasm.Word32And(
      scope_info_flags,
      gasm.Uint32Constant(ScopeInfo::HasContextExtensionSlotBit::kMask));
  TNode<Word32T> no_extension =
      gasm.Word32Equal(flags_masked, gasm.Uint32Constant(0));
  TNode<Word32T> has_extension =
      gasm.Word32Equal(no_extension, gasm.Uint32Constant(0));
  TNode<Boolean> has_extension_boolean = gasm.ExitMachineGraph<Boolean>(
      has_extension, MachineRepresentation::kBit, Type::Boolean());
  ReplaceWithValue(node, has_extension_boolean, gasm.effect(), gasm.control());
  return Changed(node);
}
References broker(), v8::internal::compiler::GraphAssembler::control(), DCHECK_EQ, v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::JSGraphAssembler::EnterMachineGraph(), v8::internal::compiler::JSGraphAssembler::ExitMachineGraph(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::AccessBuilder::ForContextSlotKnownPointer(), v8::internal::compiler::AccessBuilder::ForScopeInfoFlags(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph_, v8::internal::kBit, v8::internal::compiler::kJS, v8::internal::compiler::JSGraphAssembler::LoadField(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::Context::PREVIOUS_INDEX, v8::internal::Context::SCOPE_INFO_INDEX, v8::internal::compiler::TFGraph::start(), v8::internal::compiler::UseInfo::TruncatingWord32(), v8::internal::compiler::GraphAssembler::Uint32Constant(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::compiler::MachineGraph::zone().
Referenced by Reduce().
ReduceJSHasInPrototypeChain()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain (Node * node) [private]
Definition at line 1391 of file js-typed-lowering.cc.
                                                                 {
  DCHECK_EQ(IrOpcode::kJSHasInPrototypeChain, node->opcode());
  Node* value = NodeProperties::GetValueInput(node, 0);
  Type value_type = NodeProperties::GetType(value);
  Node* prototype = NodeProperties::GetValueInput(node, 1);
  Node* context = NodeProperties::GetContextInput(node);
  Node* frame_state = NodeProperties::GetFrameStateInput(node);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  // If {value} cannot be a receiver, then it cannot have {prototype} in
  // it's prototype chain (all Primitive values have a null prototype).
  if (value_type.Is(Type::Primitive())) {
    value = jsgraph()->FalseConstant();
    ReplaceWithValue(node, value, effect, control);
    return Replace(value);
  }
  Node* check0 = graph()->NewNode(simplified()->ObjectIsSmi(), value);
  Node* branch0 =
      graph()->NewNode(common()->Branch(BranchHint::kFalse), check0, control);
  Node* if_true0 = graph()->NewNode(common()->IfTrue(), branch0);
  Node* etrue0 = effect;
  Node* vtrue0 = jsgraph()->FalseConstant();
  control = graph()->NewNode(common()->IfFalse(), branch0);
  // Loop through the {value}s prototype chain looking for the {prototype}.
  Node* loop = control = graph()->NewNode(common()->Loop(2), control, control);
  Node* eloop = effect =
      graph()->NewNode(common()->EffectPhi(2), effect, effect, loop);
  Node* terminate = graph()->NewNode(common()->Terminate(), eloop, loop);
  MergeControlToEnd(graph(), common(), terminate);
  Node* vloop = value = graph()->NewNode(
      common()->Phi(MachineRepresentation::kTagged, 2), value, value, loop);
  NodeProperties::SetType(vloop, Type::NonInternal());
  // Load the {value} map and instance type.
  Node* value_map = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForMap()), value, effect, control);
  Node* value_instance_type = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForMapInstanceType()), value_map,
      effect, control);
  // Check if the {value} is a special receiver, because for special
  // receivers, i.e. proxies or API values that need access checks,
  // we have to use the %HasInPrototypeChain runtime function instead.
  Node* check1 = graph()->NewNode(
      simplified()->NumberLessThanOrEqual(), value_instance_type,
      jsgraph()->ConstantNoHole(LAST_SPECIAL_RECEIVER_TYPE));
  Node* branch1 =
      graph()->NewNode(common()->Branch(BranchHint::kFalse), check1, control);
  control = graph()->NewNode(common()->IfFalse(), branch1);
  Node* if_true1 = graph()->NewNode(common()->IfTrue(), branch1);
  Node* etrue1 = effect;
  Node* vtrue1;
  // Check if the {value} is not a receiver at all.
  Node* check10 =
      graph()->NewNode(simplified()->NumberLessThan(), value_instance_type,
                       jsgraph()->ConstantNoHole(FIRST_JS_RECEIVER_TYPE));
  Node* branch10 =
      graph()->NewNode(common()->Branch(BranchHint::kTrue), check10, if_true1);
  // A primitive value cannot match the {prototype} we're looking for.
  if_true1 = graph()->NewNode(common()->IfTrue(), branch10);
  vtrue1 = jsgraph()->FalseConstant();
  Node* if_false1 = graph()->NewNode(common()->IfFalse(), branch10);
  Node* efalse1 = etrue1;
  Node* vfalse1;
  {
    // Slow path, need to call the %HasInPrototypeChain runtime function.
    vfalse1 = efalse1 = if_false1 = graph()->NewNode(
        javascript()->CallRuntime(Runtime::kHasInPrototypeChain), value,
        prototype, context, frame_state, efalse1, if_false1);
    // Replace any potential {IfException} uses of {node} to catch
    // exceptions from this %HasInPrototypeChain runtime call instead.
    Node* on_exception = nullptr;
    if (NodeProperties::IsExceptionalCall(node, &on_exception)) {
      NodeProperties::ReplaceControlInput(on_exception, vfalse1);
      NodeProperties::ReplaceEffectInput(on_exception, efalse1);
      if_false1 = graph()->NewNode(common()->IfSuccess(), vfalse1);
      Revisit(on_exception);
    }
  }
  // Load the {value} prototype.
  Node* value_prototype = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForMapPrototype()), value_map,
      effect, control);
  // Check if we reached the end of {value}s prototype chain.
  Node* check2 = graph()->NewNode(simplified()->ReferenceEqual(),
                                  value_prototype, jsgraph()->NullConstant());
  Node* branch2 = graph()->NewNode(common()->Branch(), check2, control);
  Node* if_true2 = graph()->NewNode(common()->IfTrue(), branch2);
  Node* etrue2 = effect;
  Node* vtrue2 = jsgraph()->FalseConstant();
  control = graph()->NewNode(common()->IfFalse(), branch2);
  // Check if we reached the {prototype}.
  Node* check3 = graph()->NewNode(simplified()->ReferenceEqual(),
                                  value_prototype, prototype);
  Node* branch3 = graph()->NewNode(common()->Branch(), check3, control);
  Node* if_true3 = graph()->NewNode(common()->IfTrue(), branch3);
  Node* etrue3 = effect;
  Node* vtrue3 = jsgraph()->TrueConstant();
  control = graph()->NewNode(common()->IfFalse(), branch3);
  // Close the loop.
  vloop->ReplaceInput(1, value_prototype);
  eloop->ReplaceInput(1, effect);
  loop->ReplaceInput(1, control);
  control = graph()->NewNode(common()->Merge(5), if_true0, if_true1, if_true2,
                             if_true3, if_false1);
  effect = graph()->NewNode(common()->EffectPhi(5), etrue0, etrue1, etrue2,
                            etrue3, efalse1, control);
  // Morph the {node} into an appropriate Phi.
  ReplaceWithValue(node, node, effect, control);
  node->ReplaceInput(0, vtrue0);
  node->ReplaceInput(1, vtrue1);
  node->ReplaceInput(2, vtrue2);
  node->ReplaceInput(3, vtrue3);
  node->ReplaceInput(4, vfalse1);
  node->ReplaceInput(5, control);
  node->TrimInputCount(6);
  NodeProperties::ChangeOp(node,
                           common()->Phi(MachineRepresentation::kTagged, 5));
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), common(), DCHECK_EQ, v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::AccessBuilder::ForMapInstanceType(), v8::internal::compiler::AccessBuilder::ForMapPrototype(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetFrameStateInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), javascript(), jsgraph(), v8::internal::kFalse, v8::internal::kTagged, v8::internal::kTrue, v8::internal::LAST_SPECIAL_RECEIVER_TYPE, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::opcode(), v8::internal::prototype, v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::NodeProperties::SetType(), simplified(), v8::internal::Terminate(), v8::internal::compiler::Node::TrimInputCount(), v8::internal::value, and v8::internal::wasm::value_type().
Referenced by Reduce().
ReduceJSIncrement()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSIncrement (Node * node) [private]
Definition at line 593 of file js-typed-lowering.cc.
                                                       {
  Node* input = NodeProperties::GetValueInput(node, 0);
  Type input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::PlainPrimitive())) {
    // JSIncrement(x) => NumberAdd(ToNumber(x), 1)
    const FeedbackParameter& p = FeedbackParameterOf(node->op());
    node->InsertInput(graph()->zone(), 1, jsgraph()->OneConstant());
    NodeProperties::ChangeOp(node, javascript()->Add(p.feedback()));
    JSBinopReduction r(this, node);
    r.ConvertInputsToNumber();
    DCHECK_EQ(simplified()->NumberAdd(), r.NumberOp());
    return r.ChangeToPureOperator(r.NumberOp(), Type::Number());
  }
  return NoChange();
}
References v8::bigint::Add(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ConvertInputsToNumber(), DCHECK_EQ, v8::internal::compiler::FeedbackParameter::feedback(), v8::internal::compiler::FeedbackParameterOf(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::Node::InsertInput(), v8::internal::compiler::Type::Is(), javascript(), jsgraph(), v8::internal::compiler::JSBinopReduction::NumberOp(), v8::internal::compiler::Node::op(), and simplified().
Referenced by Reduce().
ReduceJSLoadContext()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext (Node * node) [private]
Definition at line 1618 of file js-typed-lowering.cc.
                                                         {
  DCHECK_EQ(IrOpcode::kJSLoadContext, node->opcode());
  ContextAccess const& access = ContextAccessOf(node->op());
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  JSGraphAssembler gasm(broker(), jsgraph(), jsgraph()->zone(),
                        BranchSemantics::kJS);
  gasm.InitializeEffectControl(effect, control);
  TNode<Context> context =
      TNode<Context>::UncheckedCast(NodeProperties::GetContextInput(node));
  for (size_t i = 0; i < access.depth(); ++i) {
    context = gasm.LoadField<Context>(
        AccessBuilder::ForContextSlotKnownPointer(Context::PREVIOUS_INDEX),
        context);
  }
  TNode<Object> value = gasm.LoadField<Object>(
      AccessBuilder::ForContextSlot(access.index()), context);
  TNode<Object> result =
      gasm.SelectIf<Object>(gasm.ObjectIsSmi(value))
          .Then([&] { return value; })
          .Else([&] {
            TNode<Map> value_map =
                gasm.LoadMap(TNode<HeapObject>::UncheckedCast(value));
            return gasm.SelectIf<Object>(gasm.IsContextCellMap(value_map))
                .Then([&] {
                  TNode<HeapObject> heap_value =
                      TNode<HeapObject>::UncheckedCast(value);
                  TNode<Int32T> state = gasm.LoadField<Int32T>(
                      AccessBuilder::ForContextCellState(), heap_value);
                  static_assert(ContextCell::State::kConst == 0);
                  static_assert(ContextCell::State::kSmi == 1);
                  return gasm
                      .MachineSelectIf<Object>(gasm.Int32LessThanOrEqual(
                          state, gasm.Int32Constant(ContextCell::kSmi)))
                      .Then([&] {
                        return gasm.LoadField<Object>(
                            AccessBuilder::ForContextCellTaggedValue(),
                            heap_value);
                      })
                      .Else([&] {
                        return gasm
                            .MachineSelectIf<Object>(gasm.Word32Equal(
                                state, gasm.Int32Constant(ContextCell::kInt32)))
                            .Then([&] {
                              return gasm.LoadField<Number>(
                                  AccessBuilder::ForContextCellInt32Value(),
                                  heap_value);
                            })
                            .Else([&] {
                              return gasm.LoadField<Number>(
                                  AccessBuilder::ForContextCellFloat64Value(),
                                  heap_value);
                            })
                            .Value();
                      })
                      .Value();
                })
                .Else([&] { return value; })
                .ExpectFalse()
                .Value();
          })
          .Value();
  ReplaceWithValue(node, result, gasm.effect(), gasm.control());
  return Changed(node);
}
References broker(), v8::internal::compiler::ContextAccessOf(), v8::internal::compiler::GraphAssembler::control(), DCHECK_EQ, v8::internal::compiler::ContextAccess::depth(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::AccessBuilder::ForContextCellFloat64Value(), v8::internal::compiler::AccessBuilder::ForContextCellInt32Value(), v8::internal::compiler::AccessBuilder::ForContextCellState(), v8::internal::compiler::AccessBuilder::ForContextCellTaggedValue(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::AccessBuilder::ForContextSlotKnownPointer(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::ContextAccess::index(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), v8::internal::compiler::GraphAssembler::Int32Constant(), jsgraph(), v8::internal::ContextCell::kInt32, v8::internal::compiler::kJS, v8::internal::compiler::kSmi, v8::internal::ContextCell::kSmi, v8::internal::compiler::JSGraphAssembler::LoadField(), v8::internal::compiler::JSGraphAssembler::LoadMap(), v8::internal::compiler::JSGraphAssembler::MachineSelectIf(), v8::internal::compiler::JSGraphAssembler::ObjectIsSmi(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::Context::PREVIOUS_INDEX, v8::base::internal::result, v8::internal::compiler::JSGraphAssembler::SelectIf(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::value.
Referenced by Reduce().
ReduceJSLoadContextNoCell()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSLoadContextNoCell (Node * node) [private]
Definition at line 1597 of file js-typed-lowering.cc.
                                                               {
  DCHECK_EQ(IrOpcode::kJSLoadContextNoCell, node->opcode());
  ContextAccess const& access = ContextAccessOf(node->op());
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* context = NodeProperties::GetContextInput(node);
  Node* control = graph()->start();
  for (size_t i = 0; i < access.depth(); ++i) {
    context = effect = graph()->NewNode(
        simplified()->LoadField(
            AccessBuilder::ForContextSlotKnownPointer(Context::PREVIOUS_INDEX)),
        context, effect, control);
  }
  node->ReplaceInput(0, context);
  node->ReplaceInput(1, effect);
  node->AppendInput(jsgraph()->zone(), control);
  NodeProperties::ChangeOp(
      node,
      simplified()->LoadField(AccessBuilder::ForContextSlot(access.index())));
  return Changed(node);
}
References v8::internal::compiler::Node::AppendInput(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::ContextAccessOf(), DCHECK_EQ, v8::internal::compiler::ContextAccess::depth(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::AccessBuilder::ForContextSlotKnownPointer(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::ContextAccess::index(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::Context::PREVIOUS_INDEX, v8::internal::compiler::Node::ReplaceInput(), simplified(), and v8::internal::compiler::TFGraph::start().
Referenced by Reduce().
ReduceJSLoadMessage()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSLoadMessage (Node * node) [private]
Definition at line 2458 of file js-typed-lowering.cc.
                                                         {
  DCHECK_EQ(IrOpcode::kJSLoadMessage, node->opcode());
  ExternalReference const ref =
      ExternalReference::address_of_pending_message(isolate());
  node->ReplaceInput(0, jsgraph()->ExternalConstant(ref));
  NodeProperties::ChangeOp(node, simplified()->LoadMessage());
  return Changed(node);
}
References v8::internal::ExternalReference::address_of_pending_message(), v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, isolate(), jsgraph(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::ReplaceInput(), and simplified().
Referenced by Reduce().
ReduceJSLoadModule()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSLoadModule (Node * node) [private]
Definition at line 1795 of file js-typed-lowering.cc.
                                                        {
  DCHECK_EQ(IrOpcode::kJSLoadModule, node->opcode());
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  Node* cell = BuildGetModuleCell(node);
  if (cell->op()->EffectOutputCount() > 0) effect = cell;
  Node* value = effect =
      graph()->NewNode(simplified()->LoadField(AccessBuilder::ForCellValue()),
                       cell, effect, control);
  ReplaceWithValue(node, value, effect, control);
  return Changed(value);
}
References BuildGetModuleCell(), DCHECK_EQ, v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::AccessBuilder::ForCellValue(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), simplified(), and v8::internal::value.
Referenced by Reduce().
ReduceJSLoadNamed()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSLoadNamed (Node * node) [private]
Definition at line 1376 of file js-typed-lowering.cc.
                                                       {
  JSLoadNamedNode n(node);
  Node* receiver = n.object();
  Type receiver_type = NodeProperties::GetType(receiver);
  NameRef name = NamedAccessOf(node->op()).name();
  NameRef length_str = broker()->length_string();
  // Optimize "length" property of strings.
  if (name.equals(length_str) && receiver_type.Is(Type::String())) {
    Node* value = graph()->NewNode(simplified()->StringLength(), receiver);
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  return NoChange();
}
References broker(), v8::internal::compiler::NodeProperties::GetType(), graph(), v8::internal::compiler::Type::Is(), v8::internal::compiler::NamedAccess::name(), v8::internal::name, v8::internal::compiler::NamedAccessOf(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), simplified(), v8::anonymous_namespace{api.cc}::StringLength(), and v8::internal::value.
Referenced by Reduce().
ReduceJSNegate()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSNegate (Node * node) [private]
Definition at line 609 of file js-typed-lowering.cc.
                                                    {
  Node* input = NodeProperties::GetValueInput(node, 0);
  Type input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::PlainPrimitive())) {
    // JSNegate(x) => NumberMultiply(ToNumber(x), -1)
    const FeedbackParameter& p = FeedbackParameterOf(node->op());
    node->InsertInput(graph()->zone(), 1, jsgraph()->SmiConstant(-1));
    NodeProperties::ChangeOp(node, javascript()->Multiply(p.feedback()));
    JSBinopReduction r(this, node);
    r.ConvertInputsToNumber();
    return r.ChangeToPureOperator(r.NumberOp(), Type::Number());
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ConvertInputsToNumber(), v8::internal::compiler::FeedbackParameter::feedback(), v8::internal::compiler::FeedbackParameterOf(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::Node::InsertInput(), v8::internal::compiler::Type::Is(), javascript(), jsgraph(), v8::internal::compiler::JSBinopReduction::NumberOp(), and v8::internal::compiler::Node::op().
Referenced by Reduce().
ReduceJSOrdinaryHasInstance()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSOrdinaryHasInstance (Node * node) [private]
Definition at line 1533 of file js-typed-lowering.cc.
                                                                 {
  DCHECK_EQ(IrOpcode::kJSOrdinaryHasInstance, node->opcode());
  Node* constructor = NodeProperties::GetValueInput(node, 0);
  Type constructor_type = NodeProperties::GetType(constructor);
  Node* object = NodeProperties::GetValueInput(node, 1);
  Type object_type = NodeProperties::GetType(object);
  // Check if the {constructor} cannot be callable.
  // See ES6 section 7.3.19 OrdinaryHasInstance (C, O) step 1.
  if (!constructor_type.Maybe(Type::Callable())) {
    Node* value = jsgraph()->FalseConstant();
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  // If the {constructor} cannot be a JSBoundFunction and then {object}
  // cannot be a JSReceiver, then this can be constant-folded to false.
  // See ES6 section 7.3.19 OrdinaryHasInstance (C, O) step 2 and 3.
  if (!object_type.Maybe(Type::Receiver()) &&
      !constructor_type.Maybe(Type::BoundFunction())) {
    Node* value = jsgraph()->FalseConstant();
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  return NoChange();
}
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), jsgraph(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::value.
Referenced by Reduce().
ReduceJSParseInt()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSParseInt (Node * node) [private]
Definition at line 2696 of file js-typed-lowering.cc.
                                                      {
  Node* value = NodeProperties::GetValueInput(node, 0);
  Type value_type = NodeProperties::GetType(value);
  Node* radix = NodeProperties::GetValueInput(node, 1);
  Type radix_type = NodeProperties::GetType(radix);
  // We need kTenOrUndefined and kZeroOrUndefined because
  // the type representing {0,10} would become the range 1-10.
  if (value_type.Is(type_cache_->kSafeInteger) &&
      (radix_type.Is(type_cache_->kTenOrUndefined) ||
       radix_type.Is(type_cache_->kZeroOrUndefined))) {
    // Number.parseInt(a:safe-integer) -> a
    // Number.parseInt(a:safe-integer,b:#0\/undefined) -> a
    // Number.parseInt(a:safe-integer,b:#10\/undefined) -> a
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Is(), v8::internal::compiler::TypeCache::kSafeInteger, v8::internal::compiler::TypeCache::kTenOrUndefined, v8::internal::compiler::TypeCache::kZeroOrUndefined, v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), type_cache_, v8::internal::value, and v8::internal::wasm::value_type().
Referenced by Reduce().
ReduceJSResolvePromise()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSResolvePromise (Node * node) [private]
Definition at line 2715 of file js-typed-lowering.cc.
                                                            {
  DCHECK_EQ(IrOpcode::kJSResolvePromise, node->opcode());
  Node* resolution = NodeProperties::GetValueInput(node, 1);
  Type resolution_type = NodeProperties::GetType(resolution);
  // We can strength-reduce JSResolvePromise to JSFulfillPromise
  // if the {resolution} is known to be a primitive, as in that
  // case we don't perform the implicit chaining (via "then").
  if (resolution_type.Is(Type::Primitive())) {
    // JSResolvePromise(p,v:primitive) -> JSFulfillPromise(p,v)
    node->RemoveInput(3); // frame state
    NodeProperties::ChangeOp(node, javascript()->FulfillPromise());
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Is(), javascript(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::Node::RemoveInput().
Referenced by Reduce().
ReduceJSStoreContext()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext (Node * node) [private]
Definition at line 1709 of file js-typed-lowering.cc.
                                                          {
  DCHECK_EQ(IrOpcode::kJSStoreContext, node->opcode());
  ContextAccess const& access = ContextAccessOf(node->op());
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  FrameState frame_state{NodeProperties::GetFrameStateInput(node)};
  JSGraphAssembler gasm(broker(), jsgraph(), jsgraph()->zone(),
                        BranchSemantics::kJS);
  gasm.InitializeEffectControl(effect, control);
  TNode<Context> context =
      TNode<Context>::UncheckedCast(NodeProperties::GetContextInput(node));
  for (size_t i = 0; i < access.depth(); ++i) {
    context = gasm.LoadField<Context>(
        AccessBuilder::ForContextSlotKnownPointer(Context::PREVIOUS_INDEX),
        context);
  }
  TNode<Object> old_value = gasm.LoadField<Object>(
      AccessBuilder::ForContextSlot(access.index()), context);
  TNode<Object> new_value =
      TNode<Object>::UncheckedCast(NodeProperties::GetValueInput(node, 0));
  gasm.If(gasm.ObjectIsSmi(old_value))
      .Then([&] {
        gasm.StoreField(AccessBuilder::ForContextSlot(access.index()), context,
                        new_value);
      })
      .Else([&] {
        TNode<Map> old_value_map =
            gasm.LoadMap(TNode<HeapObject>::UncheckedCast(old_value));
        gasm.If(gasm.IsContextCellMap(old_value_map))
            .Then([&] {
              gasm.DetachContextCell(context, new_value,
                                     static_cast<int>(access.index()),
                                     frame_state);
            })
            .Else([&] {
              gasm.StoreField(AccessBuilder::ForContextSlot(access.index()),
                              context, new_value);
            })
            .ExpectFalse();
      });
  ReplaceWithValue(node, gasm.effect(), gasm.effect(), gasm.control());
  return Changed(node);
}
References broker(), v8::internal::compiler::ContextAccessOf(), v8::internal::compiler::GraphAssembler::control(), DCHECK_EQ, v8::internal::compiler::ContextAccess::depth(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::AccessBuilder::ForContextSlotKnownPointer(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetFrameStateInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::JSGraphAssembler::If(), v8::internal::compiler::ContextAccess::index(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), jsgraph(), v8::internal::compiler::kJS, v8::internal::compiler::JSGraphAssembler::LoadField(), v8::internal::compiler::JSGraphAssembler::LoadMap(), v8::internal::compiler::JSGraphAssembler::ObjectIsSmi(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::Context::PREVIOUS_INDEX, v8::internal::compiler::JSGraphAssembler::StoreField(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by Reduce().
ReduceJSStoreContextNoCell()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSStoreContextNoCell (Node * node) [private]
Definition at line 1687 of file js-typed-lowering.cc.
                                                                {
  DCHECK_EQ(IrOpcode::kJSStoreContextNoCell, node->opcode());
  ContextAccess const& access = ContextAccessOf(node->op());
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* context = NodeProperties::GetContextInput(node);
  Node* control = graph()->start();
  Node* value = NodeProperties::GetValueInput(node, 0);
  for (size_t i = 0; i < access.depth(); ++i) {
    context = effect = graph()->NewNode(
        simplified()->LoadField(
            AccessBuilder::ForContextSlotKnownPointer(Context::PREVIOUS_INDEX)),
        context, effect, control);
  }
  node->ReplaceInput(0, context);
  node->ReplaceInput(1, value);
  node->ReplaceInput(2, effect);
  NodeProperties::ChangeOp(
      node,
      simplified()->StoreField(AccessBuilder::ForContextSlot(access.index())));
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::ContextAccessOf(), DCHECK_EQ, v8::internal::compiler::ContextAccess::depth(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::AccessBuilder::ForContextSlotKnownPointer(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::ContextAccess::index(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::Context::PREVIOUS_INDEX, v8::internal::compiler::Node::ReplaceInput(), simplified(), v8::internal::compiler::TFGraph::start(), and v8::internal::value.
Referenced by Reduce().
ReduceJSStoreMessage()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSStoreMessage (Node * node) [private]
Definition at line 2467 of file js-typed-lowering.cc.
                                                          {
  DCHECK_EQ(IrOpcode::kJSStoreMessage, node->opcode());
  ExternalReference const ref =
      ExternalReference::address_of_pending_message(isolate());
  Node* value = NodeProperties::GetValueInput(node, 0);
  node->ReplaceInput(0, jsgraph()->ExternalConstant(ref));
  node->ReplaceInput(1, value);
  NodeProperties::ChangeOp(node, simplified()->StoreMessage());
  return Changed(node);
}
References v8::internal::ExternalReference::address_of_pending_message(), v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetValueInput(), isolate(), jsgraph(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::ReplaceInput(), simplified(), and v8::internal::value.
Referenced by Reduce().
ReduceJSStoreModule()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSStoreModule (Node * node) [private]
Definition at line 1810 of file js-typed-lowering.cc.
                                                         {
  DCHECK_EQ(IrOpcode::kJSStoreModule, node->opcode());
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  Node* value = NodeProperties::GetValueInput(node, 1);
  DCHECK_EQ(SourceTextModuleDescriptor::GetCellIndexKind(
                OpParameter<int32_t>(node->op())),
            SourceTextModuleDescriptor::kExport);
  Node* cell = BuildGetModuleCell(node);
  if (cell->op()->EffectOutputCount() > 0) effect = cell;
  effect =
      graph()->NewNode(simplified()->StoreField(AccessBuilder::ForCellValue()),
                       cell, value, effect, control);
  ReplaceWithValue(node, effect, effect, control);
  return Changed(value);
}
References BuildGetModuleCell(), DCHECK_EQ, v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::AccessBuilder::ForCellValue(), v8::internal::SourceTextModuleDescriptor::GetCellIndexKind(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::SourceTextModuleDescriptor::kExport, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), simplified(), and v8::internal::value.
Referenced by Reduce().
ReduceJSStrictEqual()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual (Node * node) [private]
Definition at line 1041 of file js-typed-lowering.cc.
                                                         {
  JSBinopReduction r(this, node);
  if (r.type().IsSingleton()) {
    // Let ConstantFoldingReducer handle this.
    return NoChange();
  }
  if (r.left() == r.right()) {
    // x === x is always true if x != NaN
    Node* replacement = graph()->NewNode(
        simplified()->BooleanNot(),
        graph()->NewNode(simplified()->ObjectIsNaN(), r.left()));
    DCHECK(NodeProperties::GetType(replacement).Is(r.type()));
    ReplaceWithValue(node, replacement);
    return Replace(replacement);
  }
  if (r.BothInputsAre(Type::Unique())) {
    return r.ChangeToPureOperator(simplified()->ReferenceEqual());
  }
  if (r.OneInputIs(pointer_comparable_type_)) {
    return r.ChangeToPureOperator(simplified()->ReferenceEqual());
  }
  if (r.IsInternalizedStringCompareOperation()) {
    r.CheckInputsToInternalizedString();
    return r.ChangeToPureOperator(simplified()->ReferenceEqual());
  }
  if (r.BothInputsAre(Type::String())) {
    return r.ChangeToPureOperator(simplified()->StringEqual());
  }
  if (r.IsStringOrOddballCompareOperation()) {
    r.CheckInputsToStringOrOddball();
    return r.ChangeToPureOperator(simplified()->StringOrOddballStrictEqual());
  }
  NumberOperationHint hint;
  BigIntOperationHint hint_bigint;
  if (r.BothInputsAre(Type::Signed32()) ||
      r.BothInputsAre(Type::Unsigned32())) {
    return r.ChangeToPureOperator(simplified()->NumberEqual());
  } else if (r.GetCompareNumberOperationHint(&hint) &&
             hint != NumberOperationHint::kNumberOrOddball &&
             hint != NumberOperationHint::kNumberOrBoolean) {
    // SpeculativeNumberEqual performs implicit conversion of oddballs to
    // numbers, so me must not generate it for strict equality with respective
    // hint.
    DCHECK(hint == NumberOperationHint::kNumber ||
           hint == NumberOperationHint::kSignedSmall);
    return r.ChangeToSpeculativeOperator(
        simplified()->SpeculativeNumberEqual(hint), Type::Boolean());
  } else if (r.BothInputsAre(Type::Number())) {
    return r.ChangeToPureOperator(simplified()->NumberEqual());
  } else if (r.GetCompareBigIntOperationHint(&hint_bigint)) {
    DCHECK(hint_bigint == BigIntOperationHint::kBigInt ||
           hint_bigint == BigIntOperationHint::kBigInt64);
    return r.ChangeToSpeculativeOperator(
        simplified()->SpeculativeBigIntEqual(hint_bigint), Type::Boolean());
  } else if (r.IsReceiverCompareOperation()) {
    // For strict equality, it's enough to know that one input is a Receiver,
    // as a strict equality comparison with a Receiver can only yield true if
    // both sides refer to the same Receiver.
    r.CheckLeftInputToReceiver();
    return r.ChangeToPureOperator(simplified()->ReferenceEqual());
  } else if (r.IsReceiverOrNullOrUndefinedCompareOperation()) {
    // For strict equality, it's enough to know that one input is a Receiver,
    // Null or Undefined, as a strict equality comparison with a Receiver,
    // Null or Undefined can only yield true if both sides refer to the same
    // instance.
    r.CheckLeftInputToReceiverOrNullOrUndefined();
    return r.ChangeToPureOperator(simplified()->ReferenceEqual());
  } else if (r.IsStringCompareOperation()) {
    r.CheckInputsToString();
    return r.ChangeToPureOperator(simplified()->StringEqual());
  } else if (r.IsSymbolCompareOperation()) {
    // For strict equality, it's enough to know that one input is a Symbol,
    // as a strict equality comparison with a Symbol can only yield true if
    // both sides refer to the same Symbol.
    r.CheckLeftInputToSymbol();
    return r.ChangeToPureOperator(simplified()->ReferenceEqual());
  }
  return NoChange();
}
References v8::internal::compiler::JSBinopReduction::BothInputsAre(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::JSBinopReduction::CheckInputsToInternalizedString(), v8::internal::compiler::JSBinopReduction::CheckInputsToString(), v8::internal::compiler::JSBinopReduction::CheckInputsToStringOrOddball(), v8::internal::compiler::JSBinopReduction::CheckLeftInputToReceiver(), v8::internal::compiler::JSBinopReduction::CheckLeftInputToReceiverOrNullOrUndefined(), v8::internal::compiler::JSBinopReduction::CheckLeftInputToSymbol(), v8::internal::DCHECK(), v8::internal::compiler::JSBinopReduction::GetCompareBigIntOperationHint(), v8::internal::compiler::JSBinopReduction::GetCompareNumberOperationHint(), v8::internal::compiler::NodeProperties::GetType(), graph(), v8::internal::Is(), v8::internal::compiler::JSBinopReduction::IsInternalizedStringCompareOperation(), v8::internal::compiler::JSBinopReduction::IsReceiverCompareOperation(), v8::internal::compiler::JSBinopReduction::IsReceiverOrNullOrUndefinedCompareOperation(), v8::internal::compiler::Type::IsSingleton(), v8::internal::compiler::JSBinopReduction::IsStringCompareOperation(), v8::internal::compiler::JSBinopReduction::IsStringOrOddballCompareOperation(), v8::internal::compiler::JSBinopReduction::IsSymbolCompareOperation(), v8::internal::compiler::kBigInt, v8::internal::compiler::kBigInt64, v8::internal::compiler::kNumber, v8::internal::compiler::kNumberOrBoolean, v8::internal::compiler::kNumberOrOddball, v8::internal::compiler::kSignedSmall, v8::internal::compiler::JSBinopReduction::left(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::JSBinopReduction::OneInputIs(), pointer_comparable_type_, v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::JSBinopReduction::right(), simplified(), and v8::internal::compiler::JSBinopReduction::type().
Referenced by Reduce().
ReduceJSToBigInt()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSToBigInt (Node * node) [private]
Definition at line 1215 of file js-typed-lowering.cc.
                                                      {
  // TODO(panq): Reduce constant inputs.
  Node* const input = node->InputAt(0);
  Type const input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::BigInt())) {
    ReplaceWithValue(node, input);
    return Changed(input);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Node::InputAt(), and v8::internal::compiler::Type::Is().
Referenced by Reduce().
ReduceJSToBigIntConvertNumber()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSToBigIntConvertNumber (Node * node) [private]
Definition at line 1226 of file js-typed-lowering.cc.
                                                                   {
  // TODO(panq): Reduce constant inputs.
  Node* const input = node->InputAt(0);
  Type const input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::BigInt())) {
    ReplaceWithValue(node, input);
    return Changed(input);
  } else if (input_type.Is(Type::Signed32OrMinusZero()) ||
             input_type.Is(Type::Unsigned32OrMinusZero())) {
    RelaxEffectsAndControls(node);
    node->TrimInputCount(1);
    Type node_type = NodeProperties::GetType(node);
    NodeProperties::SetType(
        node,
        Type::Intersect(node_type, Type::SignedBigInt64(), graph()->zone()));
    NodeProperties::ChangeOp(node,
                             simplified()->Integral32OrMinusZeroToBigInt());
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::NodeProperties::GetType(), graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::Type::Is(), v8::internal::compiler::NodeProperties::SetType(), simplified(), and v8::internal::compiler::Node::TrimInputCount().
Referenced by Reduce().
ReduceJSToLength()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSToLength (Node * node) [private]
Definition at line 1133 of file js-typed-lowering.cc.
                                                      {
  Node* input = NodeProperties::GetValueInput(node, 0);
  Type input_type = NodeProperties::GetType(input);
  if (input_type.Is(type_cache_->kIntegerOrMinusZero)) {
    if (input_type.IsNone() || input_type.Max() <= 0.0) {
      input = jsgraph()->ZeroConstant();
    } else if (input_type.Min() >= kMaxSafeInteger) {
      input = jsgraph()->ConstantNoHole(kMaxSafeInteger);
    } else {
      if (input_type.Min() <= 0.0) {
        input = graph()->NewNode(simplified()->NumberMax(),
                                 jsgraph()->ZeroConstant(), input);
      }
      if (input_type.Max() > kMaxSafeInteger) {
        input =
            graph()->NewNode(simplified()->NumberMin(),
                             jsgraph()->ConstantNoHole(kMaxSafeInteger), input);
      }
    }
    ReplaceWithValue(node, input);
    return Replace(input);
  }
  return NoChange();
}
References v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::IsNone(), jsgraph(), v8::internal::compiler::TypeCache::kIntegerOrMinusZero, v8::internal::kMaxSafeInteger, v8::internal::compiler::Type::Max(), v8::internal::compiler::Type::Min(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), simplified(), and type_cache_.
Referenced by Reduce().
ReduceJSToName()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSToName (Node * node) [private]
Definition at line 1122 of file js-typed-lowering.cc.
                                                    {
  Node* const input = NodeProperties::GetValueInput(node, 0);
  Type const input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::Name())) {
    // JSToName(x:name) => x
    ReplaceWithValue(node, input);
    return Replace(input);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Is(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by Reduce().
ReduceJSToNumber()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSToNumber (Node * node) [private]
Definition at line 1193 of file js-typed-lowering.cc.
                                                      {
  // Try to reduce the input first.
  Node* const input = node->InputAt(0);
  Reduction reduction = ReduceJSToNumberInput(input);
  if (reduction.Changed()) {
    ReplaceWithValue(node, reduction.replacement());
    return reduction;
  }
  Type const input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::PlainPrimitive())) {
    RelaxEffectsAndControls(node);
    node->TrimInputCount(1);
    // For a PlainPrimitive, ToNumeric is the same as ToNumber.
    Type node_type = NodeProperties::GetType(node);
    NodeProperties::SetType(
        node, Type::Intersect(node_type, Type::Number(), graph()->zone()));
    NodeProperties::ChangeOp(node, simplified()->PlainPrimitiveToNumber());
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::Reduction::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::NodeProperties::GetType(), graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::Type::Is(), ReduceJSToNumberInput(), v8::internal::compiler::Reduction::replacement(), v8::internal::compiler::NodeProperties::SetType(), simplified(), and v8::internal::compiler::Node::TrimInputCount().
Referenced by Reduce(), and ReduceJSToNumeric().
ReduceJSToNumberInput()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSToNumberInput (Node * input) [private]
Definition at line 1158 of file js-typed-lowering.cc.
                                                            {
  // Try constant-folding of JSToNumber with constant inputs.
  Type input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::String())) {
    HeapObjectMatcher m(input);
    if (m.HasResolvedValue() && m.Ref(broker()).IsString()) {
      StringRef input_value = m.Ref(broker()).AsString();
      std::optional<double> number = input_value.ToNumber(broker());
      if (!number.has_value()) return NoChange();
      return Replace(jsgraph()->ConstantNoHole(number.value()));
    }
  }
  if (input_type.IsHeapConstant()) {
    HeapObjectRef input_value = input_type.AsHeapConstant()->Ref();
    double value;
    if (input_value.OddballToNumber(broker()).To(&value)) {
      return Replace(jsgraph()->ConstantNoHole(value));
    }
  }
  if (input_type.Is(Type::Number())) {
    // JSToNumber(x:number) => x
    return Changed(input);
  }
  if (input_type.Is(Type::Undefined())) {
    // JSToNumber(undefined) => #NaN
    return Replace(jsgraph()->NaNConstant());
  }
  if (input_type.Is(Type::Null())) {
    // JSToNumber(null) => #0
    return Replace(jsgraph()->ZeroConstant());
  }
  return NoChange();
}
References v8::internal::compiler::Type::AsHeapConstant(), broker(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::IsHeapConstant(), jsgraph(), v8::internal::compiler::Null, v8::internal::compiler::HeapConstantType::Ref(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::StringRef::ToNumber(), v8::internal::compiler::Undefined, and v8::internal::value.
Referenced by v8::internal::compiler::JSBinopReduction::ConvertPlainPrimitiveToNumber(), and ReduceJSToNumber().
ReduceJSToNumeric()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSToNumeric (Node * node) [private]
Definition at line 1248 of file js-typed-lowering.cc.
                                                       {
  Node* const input = NodeProperties::GetValueInput(node, 0);
  Type const input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::NonBigIntPrimitive())) {
    // ToNumeric(x:primitive\bigint) => ToNumber(x)
    NodeProperties::ChangeOp(node, javascript()->ToNumber());
    Type node_type = NodeProperties::GetType(node);
    NodeProperties::SetType(
        node, Type::Intersect(node_type, Type::Number(), graph()->zone()));
    return Changed(node).FollowedBy(ReduceJSToNumber(node));
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::Type::Is(), javascript(), ReduceJSToNumber(), v8::internal::compiler::NodeProperties::SetType(), and v8::internal::ToNumber().
Referenced by Reduce().
ReduceJSToObject()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSToObject (Node * node) [private]
Definition at line 1307 of file js-typed-lowering.cc.
                                                      {
  DCHECK_EQ(IrOpcode::kJSToObject, node->opcode());
  Node* receiver = NodeProperties::GetValueInput(node, 0);
  Type receiver_type = NodeProperties::GetType(receiver);
  Node* context = NodeProperties::GetContextInput(node);
  Node* frame_state = NodeProperties::GetFrameStateInput(node);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  if (receiver_type.Is(Type::Receiver())) {
    ReplaceWithValue(node, receiver, effect, control);
    return Replace(receiver);
  }
  // Check whether {receiver} is a spec object.
  Node* check = graph()->NewNode(simplified()->ObjectIsReceiver(), receiver);
  Node* branch =
      graph()->NewNode(common()->Branch(BranchHint::kTrue), check, control);
  Node* if_true = graph()->NewNode(common()->IfTrue(), branch);
  Node* etrue = effect;
  Node* rtrue = receiver;
  Node* if_false = graph()->NewNode(common()->IfFalse(), branch);
  Node* efalse = effect;
  Node* rfalse;
  {
    // Convert {receiver} using the ToObjectStub.
    Callable callable = Builtins::CallableFor(isolate(), Builtin::kToObject);
    auto call_descriptor = Linkage::GetStubCallDescriptor(
        graph()->zone(), callable.descriptor(),
        callable.descriptor().GetStackParameterCount(),
        CallDescriptor::kNeedsFrameState, node->op()->properties());
    Node* call = rfalse = efalse = if_false =
        graph()->NewNode(common()->Call(call_descriptor),
                         jsgraph()->HeapConstantNoHole(callable.code()),
                         receiver, context, frame_state, efalse, if_false);
    // We preserve the type of {node}. This is generally useful (to enable
    // type-based optimizations), and is also required in order to help
    // verification of TypeGuards.
    NodeProperties::SetType(call, NodeProperties::GetType(node));
  }
  // Update potential {IfException} uses of {node} to point to the above
  // ToObject stub call node instead. Note that the stub can only throw on
  // receivers that can be null or undefined.
  Node* on_exception = nullptr;
  if (receiver_type.Maybe(Type::NullOrUndefined()) &&
      NodeProperties::IsExceptionalCall(node, &on_exception)) {
    NodeProperties::ReplaceControlInput(on_exception, if_false);
    NodeProperties::ReplaceEffectInput(on_exception, efalse);
    if_false = graph()->NewNode(common()->IfSuccess(), if_false);
    Revisit(on_exception);
  }
  control = graph()->NewNode(common()->Merge(2), if_true, if_false);
  effect = graph()->NewNode(common()->EffectPhi(2), etrue, efalse, control);
  // Morph the {node} into an appropriate Phi.
  ReplaceWithValue(node, node, effect, control);
  node->ReplaceInput(0, rtrue);
  node->ReplaceInput(1, rfalse);
  node->ReplaceInput(2, control);
  node->TrimInputCount(3);
  NodeProperties::ChangeOp(node,
                           common()->Phi(MachineRepresentation::kTagged, 2));
  return Changed(node);
}
References v8::internal::Builtins::CallableFor(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::Callable::code(), common(), DCHECK_EQ, v8::internal::Callable::descriptor(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetFrameStateInput(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::compiler::Type::Is(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), isolate(), jsgraph(), v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::kTagged, v8::internal::kTrue, v8::internal::compiler::Type::Maybe(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Operator::properties(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::NodeProperties::SetType(), simplified(), and v8::internal::compiler::Node::TrimInputCount().
Referenced by Reduce().
ReduceJSToString()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSToString (Node * node) [private]
Definition at line 1295 of file js-typed-lowering.cc.
                                                      {
  DCHECK_EQ(IrOpcode::kJSToString, node->opcode());
  // Try to reduce the input first.
  Node* const input = node->InputAt(0);
  Reduction reduction = ReduceJSToStringInput(input);
  if (reduction.Changed()) {
    ReplaceWithValue(node, reduction.replacement());
    return reduction;
  }
  return NoChange();
}
References v8::internal::compiler::Reduction::Changed(), DCHECK_EQ, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::opcode(), ReduceJSToStringInput(), and v8::internal::compiler::Reduction::replacement().
Referenced by Reduce(), ReduceJSAdd(), and ReduceJSToStringInput().
ReduceJSToStringInput()
Reduction v8::internal::compiler::JSTypedLowering::ReduceJSToStringInput (Node * input) [private]
Definition at line 1262 of file js-typed-lowering.cc.
                                                            {
  if (input->opcode() == IrOpcode::kJSToString) {
    // Recursively try to reduce the input first.
    Reduction result = ReduceJSToString(input);
    if (result.Changed()) return result;
    return Changed(input); // JSToString(JSToString(x)) => JSToString(x)
  }
  Type input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::String())) {
    return Changed(input); // JSToString(x:string) => x
  }
  if (input_type.Is(Type::Boolean())) {
    return Replace(graph()->NewNode(
        common()->Select(MachineRepresentation::kTagged), input,
        jsgraph()->HeapConstantNoHole(factory()->true_string()),
        jsgraph()->HeapConstantNoHole(factory()->false_string())));
  }
  if (input_type.Is(Type::Undefined())) {
    return Replace(
        jsgraph()->HeapConstantNoHole(factory()->undefined_string()));
  }
  if (input_type.Is(Type::Null())) {
    return Replace(jsgraph()->HeapConstantNoHole(factory()->null_string()));
  }
  if (input_type.Is(Type::NaN())) {
    return Replace(jsgraph()->HeapConstantNoHole(factory()->NaN_string()));
  }
  if (input_type.Is(Type::Number())) {
    return Replace(graph()->NewNode(simplified()->NumberToString(), input));
  }
  return NoChange();
}
References common(), factory(), v8::internal::compiler::NodeProperties::GetType(), graph(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::compiler::Type::Is(), jsgraph(), v8::internal::kTagged, v8::internal::compiler::Null, v8::internal::compiler::Node::opcode(), ReduceJSToString(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::base::internal::result, simplified(), and v8::internal::compiler::Undefined.
Referenced by ReduceJSAdd(), and ReduceJSToString().
ReduceNumberBinop()
Reduction v8::internal::compiler::JSTypedLowering::ReduceNumberBinop (Node * node) [private]
Definition at line 849 of file js-typed-lowering.cc.
                                                       {
  JSBinopReduction r(this, node);
  if (r.BothInputsAre(Type::PlainPrimitive())) {
    r.ConvertInputsToNumber();
    return r.ChangeToPureOperator(r.NumberOp(), Type::Number());
  }
  return NoChange();
}
References v8::internal::compiler::JSBinopReduction::BothInputsAre(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ConvertInputsToNumber(), and v8::internal::compiler::JSBinopReduction::NumberOp().
Referenced by Reduce().
ReduceObjectIsArray()
Reduction v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray (Node * node) [private]
Definition at line 2593 of file js-typed-lowering.cc.
                                                         {
  Node* value = NodeProperties::GetValueInput(node, 0);
  Type value_type = NodeProperties::GetType(value);
  Node* context = NodeProperties::GetContextInput(node);
  Node* frame_state = NodeProperties::GetFrameStateInput(node);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  // Constant-fold based on {value} type.
  if (value_type.Is(Type::Array())) {
    value = jsgraph()->TrueConstant();
    ReplaceWithValue(node, value);
    return Replace(value);
  } else if (!value_type.Maybe(Type::ArrayOrProxy())) {
    value = jsgraph()->FalseConstant();
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  int count = 0;
  Node* values[5];
  Node* effects[5];
  Node* controls[4];
  // Check if the {value} is a Smi.
  Node* check = graph()->NewNode(simplified()->ObjectIsSmi(), value);
  control =
      graph()->NewNode(common()->Branch(BranchHint::kFalse), check, control);
  // The {value} is a Smi.
  controls[count] = graph()->NewNode(common()->IfTrue(), control);
  effects[count] = effect;
  values[count] = jsgraph()->FalseConstant();
  count++;
  control = graph()->NewNode(common()->IfFalse(), control);
  // Load the {value}s instance type.
  Node* value_map = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForMap()), value, effect, control);
  Node* value_instance_type = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForMapInstanceType()), value_map,
      effect, control);
  // Check if the {value} is a JSArray.
  check = graph()->NewNode(simplified()->NumberEqual(), value_instance_type,
                           jsgraph()->ConstantNoHole(JS_ARRAY_TYPE));
  control = graph()->NewNode(common()->Branch(), check, control);
  // The {value} is a JSArray.
  controls[count] = graph()->NewNode(common()->IfTrue(), control);
  effects[count] = effect;
  values[count] = jsgraph()->TrueConstant();
  count++;
  control = graph()->NewNode(common()->IfFalse(), control);
  // Check if the {value} is a JSProxy.
  check = graph()->NewNode(simplified()->NumberEqual(), value_instance_type,
                           jsgraph()->ConstantNoHole(JS_PROXY_TYPE));
  control =
      graph()->NewNode(common()->Branch(BranchHint::kFalse), check, control);
  // The {value} is neither a JSArray nor a JSProxy.
  controls[count] = graph()->NewNode(common()->IfFalse(), control);
  effects[count] = effect;
  values[count] = jsgraph()->FalseConstant();
  count++;
  control = graph()->NewNode(common()->IfTrue(), control);
  // Let the %ArrayIsArray runtime function deal with the JSProxy {value}.
  value = effect = control =
      graph()->NewNode(javascript()->CallRuntime(Runtime::kArrayIsArray), value,
                       context, frame_state, effect, control);
  NodeProperties::SetType(value, Type::Boolean());
  // Update potential {IfException} uses of {node} to point to the above
  // %ArrayIsArray runtime call node instead.
  Node* on_exception = nullptr;
  if (NodeProperties::IsExceptionalCall(node, &on_exception)) {
    NodeProperties::ReplaceControlInput(on_exception, control);
    NodeProperties::ReplaceEffectInput(on_exception, effect);
    control = graph()->NewNode(common()->IfSuccess(), control);
    Revisit(on_exception);
  }
  // The {value} is neither a JSArray nor a JSProxy.
  controls[count] = control;
  effects[count] = effect;
  values[count] = value;
  count++;
  control = graph()->NewNode(common()->Merge(count), count, controls);
  effects[count] = control;
  values[count] = control;
  effect = graph()->NewNode(common()->EffectPhi(count), count + 1, effects);
  value = graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, count),
                           count + 1, values);
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References common(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::AccessBuilder::ForMapInstanceType(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetFrameStateInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), javascript(), jsgraph(), v8::internal::kFalse, v8::internal::kTagged, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::NodeProperties::SetType(), simplified(), v8::internal::value, and v8::internal::wasm::value_type().
Referenced by Reduce().
reducer_name()
const char* v8::internal::compiler::JSTypedLowering::reducer_name () const [inline], [override]
Definition at line 37 of file js-typed-lowering.h.
{ return "JSTypedLowering"; }
ReduceUI32Shift()
Reduction v8::internal::compiler::JSTypedLowering::ReduceUI32Shift (Node * node, Signedness signedness) [private]
Definition at line 868 of file js-typed-lowering.cc.
                                                                            {
  JSBinopReduction r(this, node);
  if (r.BothInputsAre(Type::PlainPrimitive())) {
    r.ConvertInputsToNumber();
    r.ConvertInputsToUI32(signedness, kUnsigned);
    return r.ChangeToPureOperator(r.NumberOp(), signedness == kUnsigned
                                                    ? Type::Unsigned32()
                                                    : Type::Signed32());
  }
  return NoChange();
}
References v8::internal::compiler::JSBinopReduction::BothInputsAre(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ConvertInputsToNumber(), v8::internal::compiler::JSBinopReduction::ConvertInputsToUI32(), v8::internal::compiler::kUnsigned, and v8::internal::compiler::JSBinopReduction::NumberOp().
Referenced by Reduce().
simplified()
SimplifiedOperatorBuilder * v8::internal::compiler::JSTypedLowering::simplified () const [private]
Definition at line 2860 of file js-typed-lowering.cc.
                                                             {
  return jsgraph()->simplified();
}
References jsgraph(), and v8::internal::compiler::JSGraph::simplified().
Referenced by BuildGetModuleCell(), GenerateStringAddition(), ReduceJSAdd(), ReduceJSCall(), ReduceJSComparison(), ReduceJSDecrement(), ReduceJSEqual(), ReduceJSForInNext(), ReduceJSForInPrepare(), ReduceJSGeneratorRestoreContextNoCell(), ReduceJSGeneratorRestoreContinuation(), ReduceJSGeneratorRestoreInputOrDebugPos(), ReduceJSGeneratorRestoreRegister(), ReduceJSGeneratorStore(), ReduceJSHasInPrototypeChain(), ReduceJSIncrement(), ReduceJSLoadContextNoCell(), ReduceJSLoadMessage(), ReduceJSLoadModule(), ReduceJSLoadNamed(), ReduceJSStoreContextNoCell(), ReduceJSStoreMessage(), ReduceJSStoreModule(), ReduceJSStrictEqual(), ReduceJSToBigIntConvertNumber(), ReduceJSToLength(), ReduceJSToNumber(), ReduceJSToObject(), ReduceJSToStringInput(), ReduceObjectIsArray(), v8::internal::compiler::JSBinopReduction::simplified(), and UnwrapStringWrapper().
UnwrapStringWrapper()
Node * v8::internal::compiler::JSTypedLowering::UnwrapStringWrapper (Node * string_or_wrapper, Node ** effect, Node ** control) [private]
Definition at line 694 of file js-typed-lowering.cc.
                                                                          {
  Node* check =
      graph()->NewNode(simplified()->ObjectIsString(), string_or_wrapper);
  Node* branch = graph()->NewNode(common()->Branch(), check, *control);
  Node* if_true = graph()->NewNode(common()->IfTrue(), branch);
  Node* etrue = *effect;
  Node* vtrue = string_or_wrapper;
  // We just checked that the value is a string.
  vtrue = etrue = graph()->NewNode(common()->TypeGuard(Type::String()), vtrue,
                                   etrue, if_true);
  Node* if_false = graph()->NewNode(common()->IfFalse(), branch);
  Node* efalse = *effect;
  Node* vfalse = efalse = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForJSPrimitiveWrapperValue()),
      string_or_wrapper, *effect, *control);
  // The value read from a string wrapper is a string.
  vfalse = efalse = graph()->NewNode(common()->TypeGuard(Type::String()),
                                     vfalse, efalse, if_false);
  *control = graph()->NewNode(common()->Merge(2), if_true, if_false);
  *effect = graph()->NewNode(common()->EffectPhi(2), etrue, efalse, *control);
  return graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, 2),
                          vtrue, vfalse, *control);
}
References common(), v8::internal::compiler::AccessBuilder::ForJSPrimitiveWrapperValue(), graph(), v8::internal::kTagged, v8::internal::compiler::TFGraph::NewNode(), and simplified().
Referenced by ReduceJSAdd().
Friends And Related Function Documentation
JSBinopReduction
friend class JSBinopReduction [friend]
Definition at line 42 of file js-typed-lowering.h.
Member Data Documentation
broker_
JSHeapBroker* v8::internal::compiler::JSTypedLowering::broker_ [private]
Definition at line 114 of file js-typed-lowering.h.
empty_string_type_
Type v8::internal::compiler::JSTypedLowering::empty_string_type_ [private]
Definition at line 115 of file js-typed-lowering.h.
Referenced by ReduceJSAdd().
jsgraph_
JSGraph* v8::internal::compiler::JSTypedLowering::jsgraph_ [private]
Definition at line 113 of file js-typed-lowering.h.
Referenced by ReduceJSHasContextExtension().
pointer_comparable_type_
Type v8::internal::compiler::JSTypedLowering::pointer_comparable_type_ [private]
Definition at line 116 of file js-typed-lowering.h.
Referenced by ReduceJSStrictEqual().
type_cache_
TypeCache const* v8::internal::compiler::JSTypedLowering::type_cache_ [private]
Definition at line 117 of file js-typed-lowering.h.
Referenced by GenerateStringAddition(), ReduceJSParseInt(), and ReduceJSToLength().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/js-typed-lowering.h
/mnt/V8SourceCode/src/compiler/js-typed-lowering.cc