v8::internal::Heap::ExternalStringTable Class Reference
Public Member Functions
ExternalStringTable (Heap *heap)
ExternalStringTable (const ExternalStringTable &)=delete
ExternalStringTable & operator= (const ExternalStringTable &)=delete
void AddString (Tagged< String > string)
bool Contains (Tagged< String > string)
void IterateAll (RootVisitor *v)
void IterateYoung (RootVisitor *v)
void PromoteYoung ()
void CleanUpAll ()
void CleanUpYoung ()
void TearDown ()
void UpdateYoungReferences (Heap::ExternalStringTableUpdaterCallback updater_func)
void UpdateReferences (Heap::ExternalStringTableUpdaterCallback updater_func)
bool HasYoung () const
Private Member Functions
void Verify ()
void VerifyYoung ()
Private Attributes
Heap *const heap_
std::vector< TaggedBase > young_strings_
std::vector< TaggedBase > old_strings_
base::Mutex mutex_
Detailed Description
Definition at line 1717 of file heap.h.
Constructor & Destructor Documentation
ExternalStringTable() [1/2]
v8::internal::Heap::ExternalStringTable::ExternalStringTable (Heap * heap) [inline], [explicit]
Definition at line 1719 of file heap.h.
: heap_(heap) {}
ExternalStringTable() [2/2]
v8::internal::Heap::ExternalStringTable::ExternalStringTable (const ExternalStringTable &) [delete]
Member Function Documentation
AddString()
void v8::internal::Heap::ExternalStringTable::AddString (Tagged< String > string) [inline]
Definition at line 361 of file heap-inl.h.
                                                             {
  std::optional<base::MutexGuard> guard;
  // With --shared-string-table client isolates may insert into the main
  // isolate's table concurrently.
  if (v8_flags.shared_string_table &&
      heap_->isolate()->is_shared_space_isolate()) {
    guard.emplace(&mutex_);
  }
  DCHECK(IsExternalString(string));
  DCHECK(!Contains(string));
  if (HeapLayout::InYoungGeneration(string)) {
    young_strings_.push_back(string);
  } else {
    old_strings_.push_back(string);
  }
}
References Contains(), v8::internal::DCHECK(), heap_, v8::internal::HeapLayout::InYoungGeneration(), v8::internal::Isolate::is_shared_space_isolate(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::Heap::isolate(), mutex_, old_strings_, v8::internal::v8_flags, and young_strings_.
Referenced by v8::internal::Heap::RegisterExternalString().
CleanUpAll()
void v8::internal::Heap::ExternalStringTable::CleanUpAll ()
Definition at line 6908 of file heap.cc.
                                         {
  CleanUpYoung();
  int last = 0;
  Isolate* isolate = heap_->isolate();
  for (size_t i = 0; i < old_strings_.size(); ++i) {
    Tagged<Object> o = old_strings_[i];
    if (IsTheHole(o, isolate)) {
      continue;
    }
    // The real external string is already in one of these vectors and was or
    // will be processed. Re-processing it will add a duplicate to the vector.
    if (IsThinString(o)) continue;
    DCHECK(IsExternalString(o));
    DCHECK(!HeapLayout::InYoungGeneration(o));
    old_strings_[last++] = o;
  }
  old_strings_.resize(last);
  if (v8_flags.verify_heap) {
    Verify();
  }
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::HeapLayout::InYoungGeneration(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::Factory::isolate(), v8::internal::Heap::isolate(), v8::internal::InstanceTypeChecker::IsThinString(), and v8::internal::v8_flags.
CleanUpYoung()
void v8::internal::Heap::ExternalStringTable::CleanUpYoung ()
Definition at line 6887 of file heap.cc.
                                           {
  int last = 0;
  Isolate* isolate = heap_->isolate();
  for (size_t i = 0; i < young_strings_.size(); ++i) {
    Tagged<Object> o = young_strings_[i];
    if (IsTheHole(o, isolate)) {
      continue;
    }
    // The real external string is already in one of these vectors and was or
    // will be processed. Re-processing it will add a duplicate to the vector.
    if (IsThinString(o)) continue;
    DCHECK(IsExternalString(o));
    if (HeapLayout::InYoungGeneration(o)) {
      young_strings_[last++] = o;
    } else {
      old_strings_.push_back(o);
    }
  }
  young_strings_.resize(last);
}
References v8::internal::DCHECK(), heap_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::HeapLayout::InYoungGeneration(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::Heap::isolate(), v8::internal::InstanceTypeChecker::IsThinString(), old_strings_, and young_strings_.
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences().
Contains()
bool v8::internal::Heap::ExternalStringTable::Contains (Tagged< String > string)
Definition at line 2813 of file heap.cc.
                                                            {
  for (size_t i = 0; i < young_strings_.size(); ++i) {
    if (young_strings_[i] == string) return true;
  }
  for (size_t i = 0; i < old_strings_.size(); ++i) {
    if (old_strings_[i] == string) return true;
  }
  return false;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by AddString().
HasYoung()
bool v8::internal::Heap::ExternalStringTable::HasYoung () const [inline]
Definition at line 1744 of file heap.h.
{ return !young_strings_.empty(); }
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences().
IterateAll()
void v8::internal::Heap::ExternalStringTable::IterateAll (RootVisitor * v)
Definition at line 2981 of file heap.cc.
                                                       {
  IterateYoung(v);
  if (!old_strings_.empty()) {
    v->VisitRootPointers(
        Root::kExternalStringsTable, nullptr,
        FullObjectSlot(old_strings_.data()),
        FullObjectSlot(old_strings_.data() + old_strings_.size()));
  }
}
References v8::internal::RootVisitor::VisitRootPointers().
Referenced by v8::internal::Heap::IterateWeakRoots().
IterateYoung()
void v8::internal::Heap::ExternalStringTable::IterateYoung (RootVisitor * v)
Definition at line 2972 of file heap.cc.
                                                         {
  if (!young_strings_.empty()) {
    v->VisitRootPointers(
        Root::kExternalStringsTable, nullptr,
        FullObjectSlot(young_strings_.data()),
        FullObjectSlot(young_strings_.data() + young_strings_.size()));
  }
}
References v8::internal::RootVisitor::VisitRootPointers().
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences().
operator=()
ExternalStringTable& v8::internal::Heap::ExternalStringTable::operator= (const ExternalStringTable &) [delete]
PromoteYoung()
void v8::internal::Heap::ExternalStringTable::PromoteYoung ()
Definition at line 2965 of file heap.cc.
                                           {
  old_strings_.reserve(old_strings_.size() + young_strings_.size());
  std::move(std::begin(young_strings_), std::end(young_strings_),
            std::back_inserter(old_strings_));
  young_strings_.clear();
}
References v8::internal::compiler::begin(), and v8::internal::compiler::end().
TearDown()
void v8::internal::Heap::ExternalStringTable::TearDown ()
Definition at line 6930 of file heap.cc.
                                       {
  for (size_t i = 0; i < young_strings_.size(); ++i) {
    Tagged<Object> o = young_strings_[i];
    // Dont finalize thin strings.
    if (IsThinString(o)) continue;
    heap_->FinalizeExternalString(Cast<ExternalString>(o));
  }
  young_strings_.clear();
  for (size_t i = 0; i < old_strings_.size(); ++i) {
    Tagged<Object> o = old_strings_[i];
    // Dont finalize thin strings.
    if (IsThinString(o)) continue;
    heap_->FinalizeExternalString(Cast<ExternalString>(o));
  }
  old_strings_.clear();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::InstanceTypeChecker::IsThinString().
Referenced by v8::internal::Heap::TearDownWithSharedHeap().
UpdateReferences()
void v8::internal::Heap::ExternalStringTable::UpdateReferences (Heap::ExternalStringTableUpdaterCallback updater_func)
Definition at line 2996 of file heap.cc.
                                                         {
  if (!old_strings_.empty()) {
    FullObjectSlot start(old_strings_.data());
    FullObjectSlot end(old_strings_.data() + old_strings_.size());
    for (FullObjectSlot p = start; p < end; ++p)
      p.store(updater_func(heap_, p));
  }
  UpdateYoungReferences(updater_func);
}
References v8::internal::compiler::end().
Referenced by v8::internal::Heap::UpdateReferencesInExternalStringTable().
UpdateYoungReferences()
void v8::internal::Heap::ExternalStringTable::UpdateYoungReferences (Heap::ExternalStringTableUpdaterCallback updater_func)
Definition at line 2933 of file heap.cc.
                                                         {
  if (young_strings_.empty()) return;
  FullObjectSlot start(young_strings_.data());
  FullObjectSlot end(young_strings_.data() + young_strings_.size());
  FullObjectSlot last = start;
  for (FullObjectSlot p = start; p < end; ++p) {
    Tagged<String> target = updater_func(heap_, p);
    if (target.is_null()) continue;
    DCHECK(IsExternalString(target));
    if (HeapLayout::InYoungGeneration(target)) {
      // String is still in new space. Update the table entry.
      last.store(target);
      ++last;
    } else {
      // String got promoted. Move it to the old string list.
      old_strings_.push_back(target);
    }
  }
  DCHECK(last <= end);
  young_strings_.resize(last - start);
  if (v8_flags.verify_heap) {
    VerifyYoung();
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::end(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::FullObjectSlot::store(), and v8::internal::v8_flags.
Referenced by v8::internal::Heap::UpdateYoungReferencesInExternalStringTable().
Verify()
void v8::internal::Heap::ExternalStringTable::Verify () [private]
Definition at line 2908 of file heap.cc.
                                     {
#ifdef DEBUG
  std::set<Tagged<String>> visited_map;
  std::map<MutablePageMetadata*, size_t> size_map;
  ExternalBackingStoreType type = ExternalBackingStoreType::kExternalString;
  VerifyYoung();
  for (size_t i = 0; i < old_strings_.size(); ++i) {
    Tagged<String> obj = Cast<String>(Tagged<Object>(old_strings_[i]));
    MutablePageMetadata* mc = MutablePageMetadata::FromHeapObject(obj);
    DCHECK_IMPLIES(!v8_flags.sticky_mark_bits,
                   !mc->Chunk()->InYoungGeneration());
    DCHECK(!HeapLayout::InYoungGeneration(obj));
    DCHECK(!IsTheHole(obj, heap_->isolate()));
    DCHECK(IsExternalString(obj));
    // Note: we can have repeated elements in the table.
    DCHECK_EQ(0, visited_map.count(obj));
    visited_map.insert(obj);
    size_map[mc] += Cast<ExternalString>(obj)->ExternalPayloadSize();
  }
  for (std::map<MutablePageMetadata*, size_t>::iterator it = size_map.begin();
       it != size_map.end(); it++)
    DCHECK_EQ(it->first->ExternalBackingStoreBytes(type), it->second);
#endif
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::MutablePageMetadata::FromHeapObject(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::MemoryChunk::InYoungGeneration(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::kExternalString, v8::internal::tracing::type, and v8::internal::v8_flags.
VerifyYoung()
void v8::internal::Heap::ExternalStringTable::VerifyYoung () [private]
Definition at line 2884 of file heap.cc.
                                          {
#ifdef DEBUG
  std::set<Tagged<String>> visited_map;
  std::map<MutablePageMetadata*, size_t> size_map;
  ExternalBackingStoreType type = ExternalBackingStoreType::kExternalString;
  for (size_t i = 0; i < young_strings_.size(); ++i) {
    Tagged<String> obj = Cast<String>(Tagged<Object>(young_strings_[i]));
    MutablePageMetadata* mc = MutablePageMetadata::FromHeapObject(obj);
    DCHECK_IMPLIES(!v8_flags.sticky_mark_bits,
                   mc->Chunk()->InYoungGeneration());
    DCHECK(HeapLayout::InYoungGeneration(obj));
    DCHECK(!IsTheHole(obj, heap_->isolate()));
    DCHECK(IsExternalString(obj));
    // Note: we can have repeated elements in the table.
    DCHECK_EQ(0, visited_map.count(obj));
    visited_map.insert(obj);
    size_map[mc] += Cast<ExternalString>(obj)->ExternalPayloadSize();
  }
  for (std::map<MutablePageMetadata*, size_t>::iterator it = size_map.begin();
       it != size_map.end(); it++)
    DCHECK_EQ(it->first->ExternalBackingStoreBytes(type), it->second);
#endif
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::MutablePageMetadata::FromHeapObject(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::MemoryChunk::InYoungGeneration(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::kExternalString, v8::internal::tracing::type, and v8::internal::v8_flags.
Member Data Documentation
heap_
Heap* const v8::internal::Heap::ExternalStringTable::heap_ [private]
Definition at line 1750 of file heap.h.
Referenced by AddString(), and CleanUpYoung().
mutex_
base::Mutex v8::internal::Heap::ExternalStringTable::mutex_ [private]
Definition at line 1757 of file heap.h.
Referenced by AddString().
old_strings_
std::vector<TaggedBase> v8::internal::Heap::ExternalStringTable::old_strings_ [private]
Definition at line 1755 of file heap.h.
Referenced by AddString(), and CleanUpYoung().
young_strings_
std::vector<TaggedBase> v8::internal::Heap::ExternalStringTable::young_strings_ [private]
Definition at line 1754 of file heap.h.
Referenced by AddString(), and CleanUpYoung().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/heap.h
/mnt/V8SourceCode/src/heap/heap-inl.h
/mnt/V8SourceCode/src/heap/heap.cc