v8::internal::anonymous_namespace{js-display-names.cc}::DateTimeFieldNames Class Reference
Public Member Functions
DateTimeFieldNames (const icu::Locale &locale, JSDisplayNames::Style style, bool fallback)
~DateTimeFieldNames () override=default
const char * type () const override
icu::Locale locale () const override
Maybe< icu::UnicodeString > of (Isolate *isolate, const char *code) const override
Private Attributes
icu::Locale locale_
UDateTimePGDisplayWidth width_
std::unique_ptr< icu::DateTimePatternGenerator > generator_
Additional Inherited Members
Detailed Description
Definition at line 346 of file js-display-names.cc.
Constructor & Destructor Documentation
DateTimeFieldNames()
v8::internal::anonymous_namespace{js-display-names.cc}::DateTimeFieldNames::DateTimeFieldNames (const icu::Locale & locale, JSDisplayNames::Style style, bool fallback) [inline]
Definition at line 348 of file js-display-names.cc.
      : locale_(locale), width_(StyleToUDateTimePGDisplayWidth(style)) {
    UErrorCode status = U_ZERO_ERROR;
    generator_.reset(
        icu::DateTimePatternGenerator::createInstance(locale_, status));
    DCHECK(U_SUCCESS(status));
  }
References v8::internal::DCHECK(), and v8::internal::status.
 DateTimeFieldNames()
v8::internal::anonymous_namespace{js-display-names.cc}::DateTimeFieldNames::~DateTimeFieldNames () [override], [default]
Member Function Documentation
locale()
icu::Locale v8::internal::anonymous_namespace{js-display-names.cc}::DateTimeFieldNames::locale () const [inline], [override], [virtual]
Implements v8::internal::DisplayNamesInternal.
Definition at line 361 of file js-display-names.cc.
{ return locale_; }
of()
Maybe<icu::UnicodeString> v8::internal::anonymous_namespace{js-display-names.cc}::DateTimeFieldNames::of (Isolate * isolate, const char * code) const [inline], [override], [virtual]
Implements v8::internal::DisplayNamesInternal.
Definition at line 363 of file js-display-names.cc.
                                                                {
    UDateTimePatternField field = StringToUDateTimePatternField(code);
    if (field == UDATPG_FIELD_COUNT) {
      THROW_NEW_ERROR_RETURN_VALUE(
          isolate, NewRangeError(MessageTemplate::kInvalidArgument),
          Nothing<icu::UnicodeString>());
    }
    return Just(generator_->getFieldDisplayName(field, width_));
  }
References code, v8::Just(), v8::internal::anonymous_namespace{js-display-names.cc}::StringToUDateTimePatternField(), and THROW_NEW_ERROR_RETURN_VALUE.
type()
const char* v8::internal::anonymous_namespace{js-display-names.cc}::DateTimeFieldNames::type () const [inline], [override], [virtual]
Implements v8::internal::DisplayNamesInternal.
Definition at line 359 of file js-display-names.cc.
{ return "dateTimeField"; }
Member Data Documentation
generator_
std::unique_ptr<icu::DateTimePatternGenerator> v8::internal::anonymous_namespace{js-display-names.cc}::DateTimeFieldNames::generator_ [private]
Definition at line 377 of file js-display-names.cc.
locale_
icu::Locale v8::internal::anonymous_namespace{js-display-names.cc}::DateTimeFieldNames::locale_ [private]
Definition at line 375 of file js-display-names.cc.
width_
UDateTimePGDisplayWidth v8::internal::anonymous_namespace{js-display-names.cc}::DateTimeFieldNames::width_ [private]
Definition at line 376 of file js-display-names.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/js-display-names.cc