v8::internal::PreParserSourceRange Class Reference
#include <preparser.h>
Public Member Functions
PreParserSourceRange ()=default
PreParserSourceRange (int start, int end)
Static Public Member Functions
static PreParserSourceRange Empty ()
static PreParserSourceRange OpenEnded (int32_t start)
static const PreParserSourceRange & ContinuationOf (const PreParserSourceRange &that, int end)
Detailed Description
Definition at line 783 of file preparser.h.
Constructor & Destructor Documentation
PreParserSourceRange() [1/2]
v8::internal::PreParserSourceRange::PreParserSourceRange () [default]
Referenced by Empty().
PreParserSourceRange() [2/2]
v8::internal::PreParserSourceRange::PreParserSourceRange (int start, int end) [inline]
Definition at line 786 of file preparser.h.
{}
Member Function Documentation
ContinuationOf()
static const PreParserSourceRange& v8::internal::PreParserSourceRange::ContinuationOf (const PreParserSourceRange & that, int end) [inline], [static]
Definition at line 789 of file preparser.h.
                                                 {
    return that;
  }
Empty()
static PreParserSourceRange v8::internal::PreParserSourceRange::Empty () [inline], [static]
Definition at line 787 of file preparser.h.
{ return PreParserSourceRange(); }
References PreParserSourceRange().
Referenced by OpenEnded().
OpenEnded()
static PreParserSourceRange v8::internal::PreParserSourceRange::OpenEnded (int32_t start) [inline], [static]
Definition at line 788 of file preparser.h.
{ return Empty(); }
References Empty().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/preparser.h