v8::internal::FreeSpace Class Reference
#include <free-space.h>
Classes
class BodyDescriptor
Public Member Functions
int size (RelaxedLoadTag) const
int Size ()
Tagged< FreeSpace > next () const
void SetNext (const WritableFreeSpace &writable_free_space, Tagged< FreeSpace > next)
Static Public Member Functions
static void SetSize (const WritableFreeSpace &writable_free_space, int size, RelaxedStoreTag)
Static Public Attributes
static constexpr uint32_t kMaxSizeInBytes
Private Member Functions
bool IsValid () const
Private Attributes
TaggedMember< Smi > size_in_tagged_
TaggedMember< FreeSpace > next_
Friends
class Heap
Detailed Description
Definition at line 34 of file free-space.h.
Member Function Documentation
IsValid()
bool v8::internal::FreeSpace::IsValid () const [inline], [private]
Definition at line 73 of file free-space-inl.h.
{ return Heap::IsFreeSpaceValid(this); }
References v8::internal::Heap::IsFreeSpaceValid().
Referenced by next(), and SetNext().
next()
Tagged< FreeSpace > v8::internal::FreeSpace::next () const [inline]
Definition at line 39 of file free-space-inl.h.
                                        {
  DCHECK(IsValid());
#ifdef V8_EXTERNAL_CODE_SPACE
  intptr_t diff_to_next{next_.Relaxed_Load().value()};
  if (diff_to_next == 0) {
    return {};
  }
  Address next_ptr = ptr() + diff_to_next * kObjectAlignment;
  return UncheckedCast<FreeSpace>(Tagged<Object>(next_ptr));
#else
  return next_.Relaxed_Load();
#endif // V8_EXTERNAL_CODE_SPACE
}
References v8::internal::DCHECK(), IsValid(), v8::internal::kObjectAlignment, next_, and v8::internal::HeapObjectLayout::ptr().
Referenced by SetNext().
SetNext()
void v8::internal::FreeSpace::SetNext (const WritableFreeSpace & writable_free_space, Tagged< FreeSpace > next) [inline]
Definition at line 53 of file free-space-inl.h.
                                                {
  DCHECK(IsValid());
#ifdef V8_EXTERNAL_CODE_SPACE
  if (next.is_null()) {
    writable_free_space.WriteHeaderSlot<Smi, offsetof(FreeSpace, next_)>(
        Smi::zero(), kRelaxedStore);
    return;
  }
  intptr_t diff_to_next = next.ptr() - ptr();
  DCHECK(IsAligned(diff_to_next, kObjectAlignment));
  writable_free_space.WriteHeaderSlot<Smi, offsetof(FreeSpace, next_)>(
      Smi::FromIntptr(diff_to_next / kObjectAlignment), kRelaxedStore);
#else
  writable_free_space.WriteHeaderSlot<Object, offsetof(FreeSpace, next_)>(
      next, kRelaxedStore);
#endif // V8_EXTERNAL_CODE_SPACE
}
References v8::internal::DCHECK(), v8::internal::Smi::FromIntptr(), IsAligned(), IsValid(), v8::internal::kObjectAlignment, v8::kRelaxedStore, next(), next_, v8::internal::compiler::Object, v8::internal::HeapObjectLayout::ptr(), v8::internal::WritableFreeSpace::WriteHeaderSlot(), and v8::internal::Smi::zero().
SetSize()
void v8::internal::FreeSpace::SetSize (const WritableFreeSpace & writable_free_space, int size, RelaxedStoreTag tag) [inline], [static]
Definition at line 27 of file free-space-inl.h.
                                                              {
  // For size <= 2 * kTaggedSize, we expect to use one/two pointer filler maps.
  DCHECK_GT(size, 2 * kTaggedSize);
  DCHECK_EQ(size % kTaggedSize, 0);
  writable_free_space
      .WriteHeaderSlot<Smi, offsetof(FreeSpace, size_in_tagged_)>(
          Smi::FromInt(size / kTaggedSize), tag);
}
References DCHECK_EQ, DCHECK_GT, v8::internal::Smi::FromInt(), v8::internal::kTaggedSize, size(), size_in_tagged_, and v8::internal::WritableFreeSpace::WriteHeaderSlot().
Referenced by v8::internal::anonymous_namespace{heap.cc}::CreateFillerObjectAtImpl().
Size()
int v8::internal::FreeSpace::Size () [inline]
Definition at line 37 of file free-space-inl.h.
{ return size(kRelaxedLoad); }
References v8::kRelaxedLoad, and size().
size()
int v8::internal::FreeSpace::size (RelaxedLoadTag) const [inline]
Definition at line 22 of file free-space-inl.h.
                                        {
  return size_in_tagged_.Relaxed_Load().value() * kTaggedSize;
}
References v8::internal::kTaggedSize, and size_in_tagged_.
Referenced by v8::internal::Heap::IsFreeSpaceValid(), SetSize(), and Size().
Friends And Related Function Documentation
Heap
friend class Heap [friend]
Definition at line 58 of file free-space.h.
Member Data Documentation
kMaxSizeInBytes
constexpr uint32_t v8::internal::FreeSpace::kMaxSizeInBytes [static], [constexpr]
Initial value:
=
      uint32_t{Smi::kMaxValue} * kTaggedSize
Definition at line 36 of file free-space.h.
next_
TaggedMember<FreeSpace> v8::internal::FreeSpace::next_ [private]
Definition at line 66 of file free-space.h.
Referenced by next(), and SetNext().
size_in_tagged_
TaggedMember<Smi> v8::internal::FreeSpace::size_in_tagged_ [private]
Definition at line 62 of file free-space.h.
Referenced by SetSize(), and size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/free-space.h
/mnt/V8SourceCode/src/objects/free-space-inl.h