v8::internal::RegExpResultsCache Class Reference
#include <regexp.h>
Public Types
enum ResultsCacheType { REGEXP_MULTIPLE_INDICES
, STRING_SPLIT_SUBSTRINGS
 }
Static Public Member Functions
static Tagged< Object > Lookup (Heap *heap, Tagged< String > key_string, Tagged< Object > key_pattern, Tagged< FixedArray > *last_match_out, ResultsCacheType type)
static void Enter (Isolate *isolate, DirectHandle< String > key_string, DirectHandle< Object > key_pattern, DirectHandle< FixedArray > value_array, DirectHandle< FixedArray > last_match_cache, ResultsCacheType type)
static void Clear (Tagged< FixedArray > cache)
Static Public Attributes
static constexpr int kRegExpResultsCacheSize = 0x100
Static Private Attributes
static constexpr int kStringOffset = 0
static constexpr int kPatternOffset = 1
static constexpr int kArrayOffset = 2
static constexpr int kLastMatchOffset = 3
static constexpr int kArrayEntriesPerCacheEntry = 4
Detailed Description
Definition at line 221 of file regexp.h.
Member Enumeration Documentation
ResultsCacheType
enum v8::internal::RegExpResultsCache::ResultsCacheType
Enumerator
REGEXP_MULTIPLE_INDICES
STRING_SPLIT_SUBSTRINGS
Definition at line 223 of file regexp.h.
{ REGEXP_MULTIPLE_INDICES, STRING_SPLIT_SUBSTRINGS };
Member Function Documentation
Clear()
void v8::internal::RegExpResultsCache::Clear (Tagged< FixedArray > cache) [static]
Definition at line 1396 of file regexp.cc.
                                                       {
  for (int i = 0; i < kRegExpResultsCacheSize; i++) {
    cache->set(i, Smi::zero());
  }
}
References kRegExpResultsCacheSize, and v8::internal::Smi::zero().
Referenced by v8::internal::Heap::MarkCompactPrologue().
Enter()
void v8::internal::RegExpResultsCache::Enter (Isolate * isolate, DirectHandle< String > key_string, DirectHandle< Object > key_pattern, DirectHandle< FixedArray > value_array, DirectHandle< FixedArray > last_match_cache, ResultsCacheType type) [static]
Definition at line 1335 of file regexp.cc.
                                                      {
  if (V8_UNLIKELY(!v8_flags.regexp_results_cache)) return;
  Factory* factory = isolate->factory();
  DirectHandle<FixedArray> cache;
  if (!IsInternalizedString(*key_string)) return;
  if (type == STRING_SPLIT_SUBSTRINGS) {
    DCHECK(IsString(*key_pattern));
    if (!IsInternalizedString(*key_pattern)) return;
    cache = factory->string_split_cache();
  } else {
    DCHECK(type == REGEXP_MULTIPLE_INDICES);
    DCHECK(IsRegExpDataWrapper(*key_pattern));
    cache = factory->regexp_multiple_cache();
  }
  uint32_t hash = key_string->hash();
  uint32_t index = ((hash & (kRegExpResultsCacheSize - 1)) &
                    ~(kArrayEntriesPerCacheEntry - 1));
  if (cache->get(index + kStringOffset) == Smi::zero()) {
    cache->set(index + kStringOffset, *key_string);
    cache->set(index + kPatternOffset, *key_pattern);
    cache->set(index + kArrayOffset, *value_array);
    cache->set(index + kLastMatchOffset, *last_match_cache);
  } else {
    uint32_t index2 =
        ((index + kArrayEntriesPerCacheEntry) & (kRegExpResultsCacheSize - 1));
    if (cache->get(index2 + kStringOffset) == Smi::zero()) {
      cache->set(index2 + kStringOffset, *key_string);
      cache->set(index2 + kPatternOffset, *key_pattern);
      cache->set(index2 + kArrayOffset, *value_array);
      cache->set(index2 + kLastMatchOffset, *last_match_cache);
    } else {
      cache->set(index2 + kStringOffset, Smi::zero());
      cache->set(index2 + kPatternOffset, Smi::zero());
      cache->set(index2 + kArrayOffset, Smi::zero());
      cache->set(index2 + kLastMatchOffset, Smi::zero());
      cache->set(index + kStringOffset, *key_string);
      cache->set(index + kPatternOffset, *key_pattern);
      cache->set(index + kArrayOffset, *value_array);
      cache->set(index + kLastMatchOffset, *last_match_cache);
    }
  }
  // If the array is a reasonably short list of substrings, convert it into a
  // list of internalized strings.
  if (type == STRING_SPLIT_SUBSTRINGS && value_array->length() < 100) {
    for (int i = 0; i < value_array->length(); i++) {
      DirectHandle<String> str(Cast<String>(value_array->get(i)), isolate);
      DirectHandle<String> internalized_str = factory->InternalizeString(str);
      value_array->set(i, *internalized_str);
    }
  }
  // Convert backing store to a copy-on-write array.
  value_array->set_map_no_write_barrier(
      isolate, ReadOnlyRoots(isolate).fixed_cow_array_map());
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::index, v8::internal::Factory::InternalizeString(), v8::internal::InstanceTypeChecker::IsInternalizedString(), kArrayEntriesPerCacheEntry, kArrayOffset, kLastMatchOffset, kPatternOffset, kRegExpResultsCacheSize, kStringOffset, REGEXP_MULTIPLE_INDICES, STRING_SPLIT_SUBSTRINGS, v8::internal::tracing::type, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::Smi::zero().
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple().
Lookup()
Tagged< Object > v8::internal::RegExpResultsCache::Lookup (Heap * heap, Tagged< String > key_string, Tagged< Object > key_pattern, Tagged< FixedArray > * last_match_out, ResultsCacheType type) [static]
Definition at line 1301 of file regexp.cc.
                                                                 {
  if (V8_UNLIKELY(!v8_flags.regexp_results_cache)) return Smi::zero();
  Tagged<FixedArray> cache;
  if (!IsInternalizedString(key_string)) return Smi::zero();
  if (type == STRING_SPLIT_SUBSTRINGS) {
    DCHECK(IsString(key_pattern));
    if (!IsInternalizedString(key_pattern)) return Smi::zero();
    cache = heap->string_split_cache();
  } else {
    DCHECK(type == REGEXP_MULTIPLE_INDICES);
    DCHECK(IsRegExpDataWrapper(key_pattern));
    cache = heap->regexp_multiple_cache();
  }
  uint32_t hash = key_string->hash();
  uint32_t index = ((hash & (kRegExpResultsCacheSize - 1)) &
                    ~(kArrayEntriesPerCacheEntry - 1));
  if (cache->get(index + kStringOffset) != key_string ||
      cache->get(index + kPatternOffset) != key_pattern) {
    index =
        ((index + kArrayEntriesPerCacheEntry) & (kRegExpResultsCacheSize - 1));
    if (cache->get(index + kStringOffset) != key_string ||
        cache->get(index + kPatternOffset) != key_pattern) {
      return Smi::zero();
    }
  }
  *last_match_cache = Cast<FixedArray>(cache->get(index + kLastMatchOffset));
  return cache->get(index + kArrayOffset);
}
References v8::internal::DCHECK(), v8::internal::index, v8::internal::InstanceTypeChecker::IsInternalizedString(), kArrayEntriesPerCacheEntry, kArrayOffset, kLastMatchOffset, kPatternOffset, kRegExpResultsCacheSize, kStringOffset, REGEXP_MULTIPLE_INDICES, STRING_SPLIT_SUBSTRINGS, v8::internal::tracing::type, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::Smi::zero().
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple().
Member Data Documentation
kArrayEntriesPerCacheEntry
constexpr int v8::internal::RegExpResultsCache::kArrayEntriesPerCacheEntry = 4 [static], [constexpr], [private]
Definition at line 247 of file regexp.h.
Referenced by Enter(), and Lookup().
kArrayOffset
constexpr int v8::internal::RegExpResultsCache::kArrayOffset = 2 [static], [constexpr], [private]
Definition at line 245 of file regexp.h.
Referenced by Enter(), and Lookup().
kLastMatchOffset
constexpr int v8::internal::RegExpResultsCache::kLastMatchOffset = 3 [static], [constexpr], [private]
Definition at line 246 of file regexp.h.
Referenced by Enter(), and Lookup().
kPatternOffset
constexpr int v8::internal::RegExpResultsCache::kPatternOffset = 1 [static], [constexpr], [private]
Definition at line 244 of file regexp.h.
Referenced by Enter(), and Lookup().
kRegExpResultsCacheSize
constexpr int v8::internal::RegExpResultsCache::kRegExpResultsCacheSize = 0x100 [static], [constexpr]
Definition at line 240 of file regexp.h.
Referenced by Clear(), v8::internal::Heap::CreateInitialMutableObjects(), Enter(), and Lookup().
kStringOffset
constexpr int v8::internal::RegExpResultsCache::kStringOffset = 0 [static], [constexpr], [private]
Definition at line 243 of file regexp.h.
Referenced by Enter(), and Lookup().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp.h
/mnt/V8SourceCode/src/regexp/regexp.cc