v8::internal::MemoryBalancer Class Reference
#include <memory-balancer.h>
Classes
class SmoothedBytesAndDuration
Public Member Functions
MemoryBalancer (Heap *heap, base::TimeTicks startup_time)
void UpdateAllocationRate (size_t major_allocation_bytes, base::TimeDelta major_allocation_duration)
void UpdateGCSpeed (size_t major_gc_bytes, base::TimeDelta major_gc_duration)
void HeartbeatUpdate ()
void RecomputeLimits (size_t embedder_allocation_limit, base::TimeTicks time)
Private Member Functions
void RefreshLimit ()
void PostHeartbeatTask ()
Private Attributes
Heap * heap_
size_t live_memory_after_gc_ = 0
size_t embedder_allocation_limit_ = 0
std::optional< SmoothedBytesAndDuration > major_allocation_rate_
std::optional< SmoothedBytesAndDuration > major_gc_speed_
size_t last_measured_memory_ = 0
base::TimeTicks last_measured_at_
bool heartbeat_task_started_ = false
Static Private Attributes
static constexpr double kMajorAllocationDecayRate = 0.95
static constexpr double kMajorGCDecayRate = 0.5
Detailed Description
Definition at line 23 of file memory-balancer.h.
Constructor & Destructor Documentation
MemoryBalancer()
v8::internal::MemoryBalancer::MemoryBalancer (Heap * heap, base::TimeTicks startup_time)
Definition at line 13 of file memory-balancer.cc.
    : heap_(heap), last_measured_at_(startup_time) {}
Member Function Documentation
HeartbeatUpdate()
void v8::internal::MemoryBalancer::HeartbeatUpdate ()
Definition at line 83 of file memory-balancer.cc.
                                     {
  heartbeat_task_started_ = false;
  auto time = base::TimeTicks::Now();
  auto memory = heap_->OldGenerationSizeOfObjects();
  const base::TimeDelta duration = time - last_measured_at_;
  const size_t allocated_bytes =
      memory > last_measured_memory_ ? memory - last_measured_memory_ : 0;
  UpdateAllocationRate(allocated_bytes, duration);
  last_measured_memory_ = memory;
  last_measured_at_ = time;
  RefreshLimit();
  PostHeartbeatTask();
}
References v8::internal::duration, heap_, heartbeat_task_started_, last_measured_at_, last_measured_memory_, v8::base::TimeTicks::Now(), v8::internal::Heap::OldGenerationSizeOfObjects(), PostHeartbeatTask(), RefreshLimit(), v8::internal::time, and UpdateAllocationRate().
Referenced by v8::internal::HeartbeatTask::RunInternal().
PostHeartbeatTask()
void v8::internal::MemoryBalancer::PostHeartbeatTask () [private]
Definition at line 99 of file memory-balancer.cc.
                                       {
  if (heartbeat_task_started_) return;
  heartbeat_task_started_ = true;
  heap_->GetForegroundTaskRunner()->PostDelayedTask(
      std::make_unique<HeartbeatTask>(heap_->isolate(), this), 1);
}
References v8::internal::Heap::GetForegroundTaskRunner(), heap_, heartbeat_task_started_, and v8::internal::Heap::isolate().
Referenced by HeartbeatUpdate(), and RecomputeLimits().
RecomputeLimits()
void v8::internal::MemoryBalancer::RecomputeLimits (size_t embedder_allocation_limit, base::TimeTicks time)
Definition at line 16 of file memory-balancer.cc.
                                                         {
  embedder_allocation_limit_ = embedder_allocation_limit;
  last_measured_memory_ = live_memory_after_gc_ =
      heap_->OldGenerationSizeOfObjects();
  last_measured_at_ = time;
  RefreshLimit();
  PostHeartbeatTask();
}
References embedder_allocation_limit_, heap_, last_measured_at_, last_measured_memory_, live_memory_after_gc_, v8::internal::Heap::OldGenerationSizeOfObjects(), PostHeartbeatTask(), RefreshLimit(), and v8::internal::time.
RefreshLimit()
void v8::internal::MemoryBalancer::RefreshLimit () [private]
Definition at line 26 of file memory-balancer.cc.
                                  {
  CHECK(major_allocation_rate_.has_value());
  CHECK(major_gc_speed_.has_value());
  const size_t computed_limit =
      live_memory_after_gc_ +
      sqrt(live_memory_after_gc_ * (major_allocation_rate_.value().rate()) /
           (major_gc_speed_.value().rate()) / v8_flags.memory_balancer_c_value);
  // 2 MB of extra space.
  // This allows the heap size to not decay to CurrentSizeOfObject()
  // and prevents GC from triggering if, after a long period of idleness,
  // a small allocation appears.
  constexpr size_t kMinHeapExtraSpace = 2 * MB;
  const size_t minimum_limit = live_memory_after_gc_ + kMinHeapExtraSpace;
  size_t new_limit = std::max<size_t>(minimum_limit, computed_limit);
  new_limit = std::min<size_t>(new_limit, heap_->max_old_generation_size());
  new_limit = std::max<size_t>(new_limit, heap_->min_old_generation_size());
  if (v8_flags.trace_memory_balancer) {
    heap_->isolate()->PrintWithTimestamp(
        "MemoryBalancer: allocation-rate=%.1lfKB/ms gc-speed=%.1lfKB/ms "
        "minium-limit=%.1lfM computed-limit=%.1lfM new-limit=%.1lfM\n",
        major_allocation_rate_.value().rate() / KB,
        major_gc_speed_.value().rate() / KB,
        static_cast<double>(minimum_limit) / MB,
        static_cast<double>(computed_limit) / MB,
        static_cast<double>(new_limit) / MB);
  }
  heap_->SetOldGenerationAndGlobalAllocationLimit(
      new_limit, new_limit + embedder_allocation_limit_, "MemoryBalancer");
}
References CHECK, embedder_allocation_limit_, heap_, v8::internal::Heap::isolate(), v8::internal::KB, live_memory_after_gc_, major_allocation_rate_, major_gc_speed_, v8::internal::Heap::max_old_generation_size(), v8::internal::MB, v8::internal::Heap::min_old_generation_size(), v8::internal::Heap::SetOldGenerationAndGlobalAllocationLimit(), and v8::internal::v8_flags.
Referenced by HeartbeatUpdate(), and RecomputeLimits().
UpdateAllocationRate()
void v8::internal::MemoryBalancer::UpdateAllocationRate (size_t major_allocation_bytes, base::TimeDelta major_allocation_duration)
Definition at line 71 of file memory-balancer.cc.
                                                                            {
  if (!major_allocation_rate_) {
    major_allocation_rate_ = SmoothedBytesAndDuration{
        major_allocation_bytes, major_allocation_duration.InMillisecondsF()};
  } else {
    major_allocation_rate_->Update(major_allocation_bytes,
                                   major_allocation_duration.InMillisecondsF(),
                                   kMajorAllocationDecayRate);
  }
}
References v8::base::TimeDelta::InMillisecondsF(), kMajorAllocationDecayRate, and major_allocation_rate_.
Referenced by HeartbeatUpdate().
UpdateGCSpeed()
void v8::internal::MemoryBalancer::UpdateGCSpeed (size_t major_gc_bytes, base::TimeDelta major_gc_duration)
Definition at line 60 of file memory-balancer.cc.
                                                                    {
  if (!major_gc_speed_) {
    major_gc_speed_ = SmoothedBytesAndDuration{
        major_gc_bytes, major_gc_duration.InMillisecondsF()};
  } else {
    major_gc_speed_->Update(major_gc_bytes, major_gc_duration.InMillisecondsF(),
                            kMajorGCDecayRate);
  }
}
References v8::base::TimeDelta::InMillisecondsF(), kMajorGCDecayRate, and major_gc_speed_.
Member Data Documentation
embedder_allocation_limit_
size_t v8::internal::MemoryBalancer::embedder_allocation_limit_ = 0 [private]
Definition at line 74 of file memory-balancer.h.
Referenced by RecomputeLimits(), and RefreshLimit().
heap_
Heap* v8::internal::MemoryBalancer::heap_ [private]
Definition at line 59 of file memory-balancer.h.
Referenced by HeartbeatUpdate(), PostHeartbeatTask(), RecomputeLimits(), and RefreshLimit().
heartbeat_task_started_
bool v8::internal::MemoryBalancer::heartbeat_task_started_ = false [private]
Definition at line 84 of file memory-balancer.h.
Referenced by HeartbeatUpdate(), and PostHeartbeatTask().
kMajorAllocationDecayRate
constexpr double v8::internal::MemoryBalancer::kMajorAllocationDecayRate = 0.95 [static], [constexpr], [private]
Definition at line 53 of file memory-balancer.h.
Referenced by UpdateAllocationRate().
kMajorGCDecayRate
constexpr double v8::internal::MemoryBalancer::kMajorGCDecayRate = 0.5 [static], [constexpr], [private]
Definition at line 54 of file memory-balancer.h.
Referenced by UpdateGCSpeed().
last_measured_at_
base::TimeTicks v8::internal::MemoryBalancer::last_measured_at_ [private]
Definition at line 83 of file memory-balancer.h.
Referenced by HeartbeatUpdate(), and RecomputeLimits().
last_measured_memory_
size_t v8::internal::MemoryBalancer::last_measured_memory_ = 0 [private]
Definition at line 82 of file memory-balancer.h.
Referenced by HeartbeatUpdate(), and RecomputeLimits().
live_memory_after_gc_
size_t v8::internal::MemoryBalancer::live_memory_after_gc_ = 0 [private]
Definition at line 63 of file memory-balancer.h.
Referenced by RecomputeLimits(), and RefreshLimit().
major_allocation_rate_
std::optional<SmoothedBytesAndDuration> v8::internal::MemoryBalancer::major_allocation_rate_ [private]
Definition at line 77 of file memory-balancer.h.
Referenced by RefreshLimit(), and UpdateAllocationRate().
major_gc_speed_
std::optional<SmoothedBytesAndDuration> v8::internal::MemoryBalancer::major_gc_speed_ [private]
Definition at line 78 of file memory-balancer.h.
Referenced by RefreshLimit(), and UpdateGCSpeed().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/memory-balancer.h
/mnt/V8SourceCode/src/heap/memory-balancer.cc