v8::internal::MarkBit Class Reference
#include <marking.h>
Public Types
using CellType = uintptr_t
Public Member Functions
template<AccessMode mode = AccessMode::NON_ATOMIC>
bool Set ()
template<AccessMode mode = AccessMode::NON_ATOMIC>
bool Get () const
bool Clear ()
const CellType * CellAddress () const
CellType Mask () const
Static Public Member Functions
static V8_ALLOW_UNUSED MarkBit From (Address)
static V8_ALLOW_UNUSED MarkBit From (Tagged< HeapObject >)
static V8_ALLOW_UNUSED MarkBit FromForTesting (Address)
static V8_ALLOW_UNUSED MarkBit FromForTesting (Tagged< HeapObject >)
Private Member Functions
MarkBit (CellType *cell, CellType mask)
Private Attributes
CellType *const cell_
const CellType mask_
Friends
class MarkingBitmap
Detailed Description
Definition at line 19 of file marking.h.
Member Typedef Documentation
CellType
using v8::internal::MarkBit::CellType = uintptr_t
Definition at line 21 of file marking.h.
Constructor & Destructor Documentation
MarkBit()
v8::internal::MarkBit::MarkBit (CellType * cell, CellType mask) [inline], [private]
Definition at line 54 of file marking.h.
: cell_(cell), mask_(mask) {}
Member Function Documentation
CellAddress()
const CellType* v8::internal::MarkBit::CellAddress () const [inline]
Definition at line 50 of file marking.h.
{ return cell_; }
References cell_.
Clear()
bool v8::internal::MarkBit::Clear () [inline]
Definition at line 85 of file marking.h.
                           {
  CellType old_value = *cell_;
  *cell_ = old_value & ~mask_;
  return (old_value & mask_) == mask_;
}
References cell_, and mask_.
From() [1/2]
MarkBit v8::internal::MarkBit::From (Address address) [inline], [static]
Definition at line 268 of file marking-inl.h.
                                     {
  return MarkingBitmap::MarkBitFromAddress(address);
}
References v8::internal::MarkingBitmap::MarkBitFromAddress().
Referenced by _v8_internal_Print_Object_MarkBit(), v8::internal::MarkingStateBase< ConcreteState, access_mode >::IsMarked(), v8::internal::MarkingStateBase< ConcreteState, access_mode >::TryMark(), and v8::internal::YoungGenerationMarkingVisitor< marking_mode >::TryMark().
From() [2/2]
MarkBit v8::internal::MarkBit::From (Tagged< HeapObject > heap_object) [inline], [static]
Definition at line 273 of file marking-inl.h.
                                                    {
  return MarkingBitmap::MarkBitFromAddress(heap_object.ptr());
}
References v8::internal::MarkingBitmap::MarkBitFromAddress(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
FromForTesting() [1/2]
MarkBit v8::internal::MarkBit::FromForTesting (Address address) [static]
Definition at line 142 of file marking.cc.
                                               {
  return MarkingBitmap::MarkBitFromAddress(address);
}
References v8::internal::MarkingBitmap::MarkBitFromAddress().
FromForTesting() [2/2]
MarkBit v8::internal::MarkBit::FromForTesting (Tagged< HeapObject > heap_object) [static]
Definition at line 147 of file marking.cc.
                                                              {
  return MarkingBitmap::MarkBitFromAddress(heap_object.ptr());
}
References v8::internal::MarkingBitmap::MarkBitFromAddress(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Get()
template<AccessMode mode = AccessMode::NON_ATOMIC>
bool v8::internal::MarkBit::Get () const [inline]
Referenced by v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::FilterNormalObject().
Mask()
CellType v8::internal::MarkBit::Mask () const [inline]
Definition at line 51 of file marking.h.
{ return mask_; }
References mask_.
Set()
template<AccessMode mode = AccessMode::NON_ATOMIC>
bool v8::internal::MarkBit::Set () [inline]
Referenced by v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::FilterNormalObject(), v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::HandleObjectFound(), and v8::internal::YoungGenerationMarkingVisitor< marking_mode >::TryMark().
Friends And Related Function Documentation
MarkingBitmap
friend class MarkingBitmap [friend]
Definition at line 59 of file marking.h.
Member Data Documentation
cell_
CellType* const v8::internal::MarkBit::cell_ [private]
Definition at line 56 of file marking.h.
Referenced by CellAddress(), and Clear().
mask_
const CellType v8::internal::MarkBit::mask_ [private]
Definition at line 57 of file marking.h.
Referenced by Clear(), and Mask().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/marking.h
/mnt/V8SourceCode/src/heap/marking-inl.h
/mnt/V8SourceCode/src/heap/marking.cc