v8::internal::StubFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
Tagged< HeapObject > unchecked_code () const override
int LookupExceptionHandlerInTable ()
FrameSummaries Summarize () const override
Protected Member Functions
StubFrame (StackFrameIteratorBase *iterator)
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 1048 of file frames.h.
Constructor & Destructor Documentation
StubFrame()
v8::internal::StubFrame::StubFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 300 of file frames-inl.h.
    : TypedFrame(iterator) {}
Member Function Documentation
LookupExceptionHandlerInTable()
int v8::internal::StubFrame::LookupExceptionHandlerInTable ()
Definition at line 2367 of file frames.cc.
                                             {
  Tagged<Code> code;
  int pc_offset = -1;
  std::tie(code, pc_offset) = LookupCodeAndOffset();
  DCHECK(code->is_turbofanned());
  DCHECK(code->has_handler_table());
  HandlerTable table(code);
  return table.LookupReturn(pc_offset);
}
References code, v8::internal::DCHECK(), v8::internal::StackFrame::LookupCodeAndOffset(), and v8::internal::HandlerTable::LookupReturn().
Referenced by v8::internal::Isolate::UnwindAndFindHandler().
Summarize()
FrameSummaries v8::internal::StubFrame::Summarize () const [override], [virtual]
Reimplemented from v8::internal::CommonFrame.
Definition at line 2377 of file frames.cc.
                                          {
  FrameSummaries summaries;
#if V8_ENABLE_WEBASSEMBLY
  Tagged<Code> code = LookupCode();
  if (code->kind() != CodeKind::BUILTIN) return summaries;
  // We skip most stub frames from stack traces, but a few builtins
  // specifically exist to pretend to be another builtin throwing an
  // exception.
  switch (code->builtin_id()) {
    case Builtin::kThrowDataViewTypeError:
    case Builtin::kThrowDataViewDetachedError:
    case Builtin::kThrowDataViewOutOfBounds:
    case Builtin::kThrowIndexOfCalledOnNull:
    case Builtin::kThrowToLowerCaseCalledOnNull:
    case Builtin::kWasmIntToString: {
      // When adding builtins here, also implement naming support for them.
      DCHECK_NE(nullptr,
                Builtins::NameForStackTrace(isolate(), code->builtin_id()));
      FrameSummary::BuiltinFrameSummary summary(isolate(), code->builtin_id());
      summaries.frames.push_back(summary);
      break;
    }
    default:
      break;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  return summaries;
}
References BUILTIN, code, DCHECK_NE, v8::internal::FrameSummaries::frames, v8::internal::StackFrame::isolate(), v8::internal::StackFrame::LookupCode(), and v8::internal::Builtins::NameForStackTrace().
type()
Type v8::internal::StubFrame::type () const [inline], [override], [virtual]
Implements v8::internal::StackFrame.
Definition at line 1050 of file frames.h.
{ return STUB; }
References v8::internal::STUB.
unchecked_code()
Tagged< HeapObject > v8::internal::StubFrame::unchecked_code () const [override], [virtual]
Reimplemented from v8::internal::TypedFrame.
Definition at line 2360 of file frames.cc.
                                                   {
  std::optional<Tagged<GcSafeCode>> code_lookup =
      isolate()->heap()->GcSafeTryFindCodeForInnerPointer(pc());
  if (!code_lookup.has_value()) return {};
  return code_lookup.value();
}
References v8::internal::Heap::GcSafeTryFindCodeForInnerPointer(), v8::internal::Isolate::heap(), v8::internal::StackFrame::isolate(), and v8::internal::StackFrame::pc().
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 1064 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc