v8::internal::maglev::CreateShallowObjectLiteral Class Reference
#include <maglev-ir.h>
Public Member Functions
CreateShallowObjectLiteral (uint64_t bitfield, compiler::ObjectBoilerplateDescriptionRef boilerplate_descriptor, const compiler::FeedbackSource &feedback, int flags)
compiler::ObjectBoilerplateDescriptionRef boilerplate_descriptor ()
compiler::FeedbackSource feedback () const
int flags () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
Private Types
using Base = FixedInputValueNodeT< 0, CreateShallowObjectLiteral >
Private Attributes
const compiler::ObjectBoilerplateDescriptionRef boilerplate_descriptor_
const compiler::FeedbackSource feedback_
const int flags_
Additional Inherited Members
Detailed Description
Definition at line 5769 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CreateShallowObjectLiteral::Base = FixedInputValueNodeT<0, CreateShallowObjectLiteral> [private]
Definition at line 5771 of file maglev-ir.h.
Constructor & Destructor Documentation
CreateShallowObjectLiteral()
v8::internal::maglev::CreateShallowObjectLiteral::CreateShallowObjectLiteral (uint64_t bitfield, compiler::ObjectBoilerplateDescriptionRef boilerplate_descriptor, const compiler::FeedbackSource & feedback, int flags) [inline], [explicit]
Definition at line 5774 of file maglev-ir.h.
      : Base(bitfield),
        boilerplate_descriptor_(boilerplate_descriptor),
        feedback_(feedback),
        flags_(flags) {}
Member Function Documentation
boilerplate_descriptor()
compiler::ObjectBoilerplateDescriptionRef v8::internal::maglev::CreateShallowObjectLiteral::boilerplate_descriptor () [inline]
Definition at line 5785 of file maglev-ir.h.
                                                                   {
    return boilerplate_descriptor_;
  }
References boilerplate_descriptor_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
compiler::FeedbackSource v8::internal::maglev::CreateShallowObjectLiteral::feedback () const [inline]
Definition at line 5788 of file maglev-ir.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
flags()
int v8::internal::maglev::CreateShallowObjectLiteral::flags () const [inline]
Definition at line 5789 of file maglev-ir.h.
{ return flags_; }
References flags_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::CreateShallowObjectLiteral::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::CreateShallowObjectLiteral::MaxCallStackArgs () const
PrintParams()
void v8::internal::maglev::CreateShallowObjectLiteral::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 5798 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::CreateShallowObjectLiteral::SetValueLocationConstraints ()
Member Data Documentation
boilerplate_descriptor_
const compiler::ObjectBoilerplateDescriptionRef v8::internal::maglev::CreateShallowObjectLiteral::boilerplate_descriptor_ [private]
Definition at line 5801 of file maglev-ir.h.
Referenced by boilerplate_descriptor().
feedback_
const compiler::FeedbackSource v8::internal::maglev::CreateShallowObjectLiteral::feedback_ [private]
Definition at line 5802 of file maglev-ir.h.
Referenced by feedback().
flags_
const int v8::internal::maglev::CreateShallowObjectLiteral::flags_ [private]
Definition at line 5803 of file maglev-ir.h.
Referenced by flags().
kProperties
constexpr OpProperties v8::internal::maglev::CreateShallowObjectLiteral::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::GenericRuntimeOrBuiltinCall()
Definition at line 5792 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h