v8::internal::WeakCollectionsBuiltinsAssembler Class Reference
#include <builtins-collections-gen.h>
Public Member Functions
WeakCollectionsBuiltinsAssembler (compiler::CodeAssemblerState *state)
Protected Types
using KeyComparator = std::function< void(TNode< Object > entry_key, Label *if_same)>
Protected Member Functions
void AddEntry (TNode< EphemeronHashTable > table, TNode< IntPtrT > key_index, TNode< Object > key, TNode< Object > value, TNode< Int32T > number_of_elements)
TNode< HeapObject > AllocateTable (Variant variant, TNode< IntPtrT > at_least_space_for) override
TNode< IntPtrT > GetHash (const TNode< HeapObject > key, Label *if_no_hash)
TNode< Smi > CreateIdentityHash (TNode< Object > receiver)
TNode< IntPtrT > EntryMask (TNode< IntPtrT > capacity)
TNode< IntPtrT > Coefficient (TNode< IntPtrT > capacity)
TNode< IntPtrT > FindKeyIndex (TNode< HeapObject > table, TNode< IntPtrT > key_hash, TNode< IntPtrT > capacity, const KeyComparator &key_compare)
TNode< IntPtrT > FindKeyIndexForInsertion (TNode< HeapObject > table, TNode< IntPtrT > key_hash, TNode< IntPtrT > capacity)
TNode< IntPtrT > FindKeyIndexForKey (TNode< HeapObject > table, TNode< Object > key, TNode< IntPtrT > hash, TNode< IntPtrT > capacity, Label *if_not_found)
TNode< Word32T > InsufficientCapacityToAdd (TNode< Int32T > capacity, TNode< Int32T > number_of_elements, TNode< Int32T > number_of_deleted)
TNode< IntPtrT > KeyIndexFromEntry (TNode< IntPtrT > entry)
TNode< Int32T > LoadNumberOfElements (TNode< EphemeronHashTable > table, int offset)
TNode< Int32T > LoadNumberOfDeleted (TNode< EphemeronHashTable > table, int offset=0)
TNode< EphemeronHashTable > LoadTable (TNode< JSWeakCollection > collection)
TNode< IntPtrT > LoadTableCapacity (TNode< EphemeronHashTable > table)
void RemoveEntry (TNode< EphemeronHashTable > table, TNode< IntPtrT > key_index, TNode< IntPtrT > number_of_elements)
TNode< BoolT > ShouldRehash (TNode< Int32T > number_of_elements, TNode< Int32T > number_of_deleted)
TNode< Word32T > ShouldShrink (TNode< IntPtrT > capacity, TNode< IntPtrT > number_of_elements)
TNode< IntPtrT > ValueIndexFromKeyIndex (TNode< IntPtrT > key_index)
void GetEntriesIfFastCollectionOrIterable (Variant variant, TNode< Object > initial_entries, TNode< Context > context, TVariable< HeapObject > *var_entries_table, TVariable< IntPtrT > *var_number_of_elements, Label *if_not_fast_collection) override
void AddConstructorEntriesFromFastCollection (Variant variant, TNode< HeapObject > collection, TNode< HeapObject > source_table) override
Additional Inherited Members
Detailed Description
Definition at line 502 of file builtins-collections-gen.h.
Member Typedef Documentation
KeyComparator
using v8::internal::WeakCollectionsBuiltinsAssembler::KeyComparator = std::function<void(TNode<Object> entry_key, Label* if_same)> [protected]
Definition at line 524 of file builtins-collections-gen.h.
Constructor & Destructor Documentation
WeakCollectionsBuiltinsAssembler()
v8::internal::WeakCollectionsBuiltinsAssembler::WeakCollectionsBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 504 of file builtins-collections-gen.h.
      : BaseCollectionsAssembler(state) {}
Member Function Documentation
AddConstructorEntriesFromFastCollection()
void v8::internal::WeakCollectionsBuiltinsAssembler::AddConstructorEntriesFromFastCollection (Variant variant, TNode< HeapObject > collection, TNode< HeapObject > source_table) [inline], [override], [protected], [virtual]
Implements v8::internal::BaseCollectionsAssembler.
Definition at line 572 of file builtins-collections-gen.h.
                                               {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
AddEntry()
void v8::internal::WeakCollectionsBuiltinsAssembler::AddEntry (TNode< EphemeronHashTable > table, TNode< IntPtrT > key_index, TNode< Object > key, TNode< Object > value, TNode< Int32T > number_of_elements) [protected]
Definition at line 2561 of file builtins-collections-gen.cc.
                                                                              {
  // See EphemeronHashTable::AddEntry().
  TNode<IntPtrT> value_index = ValueIndexFromKeyIndex(key_index);
  UnsafeStoreFixedArrayElement(table, key_index, key,
                               UPDATE_EPHEMERON_KEY_WRITE_BARRIER);
  UnsafeStoreFixedArrayElement(table, value_index, value);
  // See HashTableBase::ElementAdded().
  UnsafeStoreFixedArrayElement(table,
                               EphemeronHashTable::kNumberOfElementsIndex,
                               SmiFromInt32(number_of_elements));
}
References v8::internal::key, v8::internal::CodeStubAssembler::SmiFromInt32(), v8::internal::CodeStubAssembler::UnsafeStoreFixedArrayElement(), v8::internal::UPDATE_EPHEMERON_KEY_WRITE_BARRIER, v8::internal::value, and ValueIndexFromKeyIndex().
AllocateTable()
TNode< HeapObject > v8::internal::WeakCollectionsBuiltinsAssembler::AllocateTable (Variant variant, TNode< IntPtrT > at_least_space_for) [override], [protected], [virtual]
Implements v8::internal::BaseCollectionsAssembler.
Definition at line 2596 of file builtins-collections-gen.cc.
                                                        {
  // See HashTable::New().
  DCHECK(variant == kWeakSet || variant == kWeakMap);
  CSA_DCHECK(this,
             IntPtrLessThanOrEqual(IntPtrConstant(0), at_least_space_for));
  TNode<IntPtrT> capacity = HashTableComputeCapacity(at_least_space_for);
  // See HashTable::NewInternal().
  TNode<IntPtrT> length = KeyIndexFromEntry(capacity);
  TNode<FixedArray> table = CAST(AllocateFixedArray(HOLEY_ELEMENTS, length));
  TNode<Map> map =
      HeapConstantNoHole(EphemeronHashTable::GetMap(isolate()->roots_table()));
  StoreMapNoWriteBarrier(table, map);
  StoreFixedArrayElement(table, EphemeronHashTable::kNumberOfElementsIndex,
                         SmiConstant(0), SKIP_WRITE_BARRIER);
  StoreFixedArrayElement(table,
                         EphemeronHashTable::kNumberOfDeletedElementsIndex,
                         SmiConstant(0), SKIP_WRITE_BARRIER);
  StoreFixedArrayElement(table, EphemeronHashTable::kCapacityIndex,
                         SmiFromIntPtr(capacity), SKIP_WRITE_BARRIER);
  TNode<IntPtrT> start = KeyIndexFromEntry(IntPtrConstant(0));
  FillFixedArrayWithValue(HOLEY_ELEMENTS, table, start, length,
                          RootIndex::kUndefinedValue);
  return table;
}
References v8::internal::CodeStubAssembler::AllocateFixedArray(), CAST, v8::internal::DCHECK(), v8::internal::CodeStubAssembler::FillFixedArrayWithValue(), v8::internal::CodeStubAssembler::HashTableComputeCapacity(), v8::internal::compiler::CodeAssembler::HeapConstantNoHole(), v8::internal::HOLEY_ELEMENTS, v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThanOrEqual(), v8::internal::compiler::CodeAssembler::isolate(), KeyIndexFromEntry(), v8::internal::BaseCollectionsAssembler::kWeakMap, v8::internal::BaseCollectionsAssembler::kWeakSet, v8::internal::length, v8::internal::SKIP_WRITE_BARRIER, v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::SmiFromIntPtr(), v8::internal::CodeStubAssembler::StoreFixedArrayElement(), and v8::internal::CodeStubAssembler::StoreMapNoWriteBarrier().
Coefficient()
TNode< IntPtrT > v8::internal::WeakCollectionsBuiltinsAssembler::Coefficient (TNode< IntPtrT > capacity) [protected]
Definition at line 2645 of file builtins-collections-gen.cc.
                             {
  static_assert(EphemeronHashTableShape::kDoHashSpreading);
  DCHECK_GE(EphemeronHashTableShape::kHashBits, 1);
  DCHECK_LE(EphemeronHashTableShape::kHashBits, 32);
  TVARIABLE(IntPtrT, coeff, IntPtrConstant(1));
  Label done(this, &coeff);
  GotoIf(IntPtrLessThan(
             capacity, IntPtrConstant(1 << EphemeronHashTableShape::kHashBits)),
         &done);
  coeff = Signed(
      WordShr(capacity, IntPtrConstant(EphemeronHashTableShape::kHashBits)));
  Goto(&done);
  BIND(&done);
  return coeff.value();
}
References DCHECK_GE, DCHECK_LE, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThan(), v8::internal::EphemeronHashTableShape::kDoHashSpreading, v8::internal::EphemeronHashTableShape::kHashBits, v8::internal::compiler::CodeAssembler::Signed(), and v8::internal::compiler::CodeAssembler::WordShr().
Referenced by FindKeyIndex().
CreateIdentityHash()
TNode< Smi > v8::internal::WeakCollectionsBuiltinsAssembler::CreateIdentityHash (TNode< Object > receiver) [protected]
Definition at line 2625 of file builtins-collections-gen.cc.
                       {
  TNode<ExternalReference> function_addr =
      ExternalConstant(ExternalReference::jsreceiver_create_identity_hash());
  TNode<ExternalReference> isolate_ptr =
      ExternalConstant(ExternalReference::isolate_address());
  MachineType type_ptr = MachineType::Pointer();
  MachineType type_tagged = MachineType::AnyTagged();
  return CAST(CallCFunction(function_addr, type_tagged,
                            std::make_pair(type_ptr, isolate_ptr),
                            std::make_pair(type_tagged, key)));
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), CAST, v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::ExternalReference::isolate_address(), v8::internal::key, and v8::internal::MachineType::Pointer().
EntryMask()
TNode< IntPtrT > v8::internal::WeakCollectionsBuiltinsAssembler::EntryMask (TNode< IntPtrT > capacity) [protected]
Definition at line 2640 of file builtins-collections-gen.cc.
                             {
  return IntPtrSub(capacity, IntPtrConstant(1));
}
References v8::internal::compiler::CodeAssembler::IntPtrConstant(), and v8::internal::compiler::CodeAssembler::IntPtrSub().
Referenced by FindKeyIndex().
FindKeyIndex()
TNode< IntPtrT > v8::internal::WeakCollectionsBuiltinsAssembler::FindKeyIndex (TNode< HeapObject > table, TNode< IntPtrT > key_hash, TNode< IntPtrT > capacity, const KeyComparator & key_compare) [protected]
Definition at line 2662 of file builtins-collections-gen.cc.
                                      {
  // See HashTable::FirstProbe().
  TNode<IntPtrT> entry_mask = EntryMask(capacity);
  TVARIABLE(IntPtrT, var_entry,
            WordAnd(IntPtrMul(key_hash, Coefficient(capacity)), entry_mask));
  TVARIABLE(IntPtrT, var_count, IntPtrConstant(0));
  Label loop(this, {&var_count, &var_entry}), if_found(this);
  Goto(&loop);
  BIND(&loop);
  TNode<IntPtrT> key_index;
  {
    key_index = KeyIndexFromEntry(var_entry.value());
    TNode<Object> entry_key =
        UnsafeLoadFixedArrayElement(CAST(table), key_index);
    key_compare(entry_key, &if_found);
    // See HashTable::NextProbe().
    Increment(&var_count);
    var_entry =
        WordAnd(IntPtrAdd(var_entry.value(), var_count.value()), entry_mask);
    Goto(&loop);
  }
  BIND(&if_found);
  return key_index;
}
References CAST, Coefficient(), EntryMask(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::CodeStubAssembler::Increment(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrMul(), KeyIndexFromEntry(), v8::internal::CodeStubAssembler::UnsafeLoadFixedArrayElement(), and v8::internal::compiler::CodeAssembler::WordAnd().
Referenced by FindKeyIndexForInsertion(), and FindKeyIndexForKey().
FindKeyIndexForInsertion()
TNode< IntPtrT > v8::internal::WeakCollectionsBuiltinsAssembler::FindKeyIndexForInsertion (TNode< HeapObject > table, TNode< IntPtrT > key_hash, TNode< IntPtrT > capacity) [protected]
Definition at line 2693 of file builtins-collections-gen.cc.
                                                                               {
  // See HashTable::FindInsertionEntry().
  auto is_not_live = [&](TNode<Object> entry_key, Label* if_found) {
    // This is the the negative form BaseShape::IsLive().
    GotoIf(Word32Or(IsTheHole(entry_key), IsUndefined(entry_key)), if_found);
  };
  return FindKeyIndex(table, key_hash, capacity, is_not_live);
}
References FindKeyIndex(), v8::internal::compiler::CodeAssembler::GotoIf(), and v8::internal::compiler::CodeAssembler::Word32Or().
FindKeyIndexForKey()
TNode< IntPtrT > v8::internal::WeakCollectionsBuiltinsAssembler::FindKeyIndexForKey (TNode< HeapObject > table, TNode< Object > key, TNode< IntPtrT > hash, TNode< IntPtrT > capacity, Label * if_not_found) [protected]
Definition at line 2703 of file builtins-collections-gen.cc.
                                                  {
  // See HashTable::FindEntry().
  auto match_key_or_exit_on_empty = [&](TNode<Object> entry_key,
                                        Label* if_same) {
    GotoIf(IsUndefined(entry_key), if_not_found);
    GotoIf(TaggedEqual(entry_key, key), if_same);
  };
  return FindKeyIndex(table, hash, capacity, match_key_or_exit_on_empty);
}
References FindKeyIndex(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::key, and v8::internal::CodeStubAssembler::TaggedEqual().
GetEntriesIfFastCollectionOrIterable()
void v8::internal::WeakCollectionsBuiltinsAssembler::GetEntriesIfFastCollectionOrIterable (Variant variant, TNode< Object > initial_entries, TNode< Context > context, TVariable< HeapObject > * var_entries_table, TVariable< IntPtrT > * var_number_of_elements, Label * if_not_fast_collection) [inline], [override], [protected], [virtual]
Implements v8::internal::BaseCollectionsAssembler.
Definition at line 564 of file builtins-collections-gen.h.
                                              {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
GetHash()
TNode< IntPtrT > v8::internal::WeakCollectionsBuiltinsAssembler::GetHash (const TNode< HeapObject > key, Label * if_no_hash) [protected]
Definition at line 2576 of file builtins-collections-gen.cc.
                                                    {
  TVARIABLE(IntPtrT, var_hash);
  Label if_symbol(this);
  Label return_result(this);
  GotoIfNot(IsJSReceiver(key), &if_symbol);
  var_hash = Signed(
      ChangeUint32ToWord(LoadJSReceiverIdentityHash(CAST(key), if_no_hash)));
  Goto(&return_result);
  Bind(&if_symbol);
  CSA_DCHECK(this, IsSymbol(key));
  CSA_DCHECK(this, Word32BinaryNot(
                       Word32And(LoadSymbolFlags(CAST(key)),
                                 Symbol::IsInPublicSymbolTableBit::kMask)));
  var_hash = Signed(ChangeUint32ToWord(LoadNameHash(CAST(key), nullptr)));
  Goto(&return_result);
  Bind(&return_result);
  return var_hash.value();
}
References v8::internal::CodeStubAssembler::Bind(), CAST, v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::IsJSReceiver(), v8::internal::key, v8::base::BitField< T, shift, size, U >::kMask, v8::internal::CodeStubAssembler::LoadJSReceiverIdentityHash(), v8::internal::CodeStubAssembler::LoadNameHash(), v8::internal::compiler::CodeAssembler::Signed(), and v8::internal::compiler::CodeAssembler::Word32And().
InsufficientCapacityToAdd()
TNode< Word32T > v8::internal::WeakCollectionsBuiltinsAssembler::InsufficientCapacityToAdd (TNode< Int32T > capacity, TNode< Int32T > number_of_elements, TNode< Int32T > number_of_deleted) [protected]
Definition at line 2751 of file builtins-collections-gen.cc.
                                     {
  // This is the negative form of HashTable::HasSufficientCapacityToAdd().
  // Return true if:
  // - more than 50% of the available space are deleted elements
  // - less than 50% will be available
  TNode<Int32T> available = Int32Sub(capacity, number_of_elements);
  TNode<Int32T> half_available = Signed(Word32Shr(available, 1));
  TNode<Int32T> needed_available = Signed(Word32Shr(number_of_elements, 1));
  return Word32Or(
      // deleted > half
      Int32GreaterThan(number_of_deleted, half_available),
      // elements + needed available > capacity
      Int32GreaterThan(Int32Add(number_of_elements, needed_available),
                       capacity));
}
References available(), v8::internal::compiler::CodeAssembler::Int32Add(), v8::internal::compiler::CodeAssembler::Int32Sub(), v8::internal::compiler::CodeAssembler::Signed(), v8::internal::compiler::CodeAssembler::Word32Or(), and v8::internal::compiler::CodeAssembler::Word32Shr().
KeyIndexFromEntry()
TNode< IntPtrT > v8::internal::WeakCollectionsBuiltinsAssembler::KeyIndexFromEntry (TNode< IntPtrT > entry) [protected]
Definition at line 2715 of file builtins-collections-gen.cc.
                          {
  // See HashTable::KeyAt().
  // (entry * kEntrySize) + kElementsStartIndex + kEntryKeyIndex
  return IntPtrAdd(
      IntPtrMul(entry, IntPtrConstant(EphemeronHashTable::kEntrySize)),
      IntPtrConstant(EphemeronHashTable::kElementsStartIndex +
                     EphemeronHashTable::kEntryKeyIndex));
}
References v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrMul(), and cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize.
Referenced by AllocateTable(), and FindKeyIndex().
LoadNumberOfDeleted()
TNode< Int32T > v8::internal::WeakCollectionsBuiltinsAssembler::LoadNumberOfDeleted (TNode< EphemeronHashTable > table, int offset = 0) [protected]
Definition at line 2733 of file builtins-collections-gen.cc.
                                                 {
  TNode<Int32T> number_of_deleted = SmiToInt32(CAST(UnsafeLoadFixedArrayElement(
      table, EphemeronHashTable::kNumberOfDeletedElementsIndex)));
  return Int32Add(number_of_deleted, Int32Constant(offset));
}
References CAST, v8::internal::compiler::CodeAssembler::Int32Add(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::CodeStubAssembler::SmiToInt32(), and v8::internal::CodeStubAssembler::UnsafeLoadFixedArrayElement().
Referenced by RemoveEntry().
LoadNumberOfElements()
TNode< Int32T > v8::internal::WeakCollectionsBuiltinsAssembler::LoadNumberOfElements (TNode< EphemeronHashTable > table, int offset) [protected]
Definition at line 2725 of file builtins-collections-gen.cc.
                                                 {
  TNode<Int32T> number_of_elements =
      SmiToInt32(CAST(UnsafeLoadFixedArrayElement(
          table, EphemeronHashTable::kNumberOfElementsIndex)));
  return Int32Add(number_of_elements, Int32Constant(offset));
}
References CAST, v8::internal::compiler::CodeAssembler::Int32Add(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::CodeStubAssembler::SmiToInt32(), and v8::internal::CodeStubAssembler::UnsafeLoadFixedArrayElement().
LoadTable()
TNode< EphemeronHashTable > v8::internal::WeakCollectionsBuiltinsAssembler::LoadTable (TNode< JSWeakCollection > collection) [protected]
Definition at line 2740 of file builtins-collections-gen.cc.
                                        {
  return CAST(LoadObjectField(collection, JSWeakCollection::kTableOffset));
}
References CAST, and v8::internal::CodeStubAssembler::LoadObjectField().
LoadTableCapacity()
TNode< IntPtrT > v8::internal::WeakCollectionsBuiltinsAssembler::LoadTableCapacity (TNode< EphemeronHashTable > table) [protected]
Definition at line 2745 of file builtins-collections-gen.cc.
                                     {
  return PositiveSmiUntag(CAST(
      UnsafeLoadFixedArrayElement(table, EphemeronHashTable::kCapacityIndex)));
}
References CAST, v8::internal::CodeStubAssembler::PositiveSmiUntag(), and v8::internal::CodeStubAssembler::UnsafeLoadFixedArrayElement().
RemoveEntry()
void v8::internal::WeakCollectionsBuiltinsAssembler::RemoveEntry (TNode< EphemeronHashTable > table, TNode< IntPtrT > key_index, TNode< IntPtrT > number_of_elements) [protected]
Definition at line 2769 of file builtins-collections-gen.cc.
                                       {
  // See EphemeronHashTable::RemoveEntry().
  TNode<IntPtrT> value_index = ValueIndexFromKeyIndex(key_index);
  StoreFixedArrayElement(table, key_index, TheHoleConstant());
  StoreFixedArrayElement(table, value_index, TheHoleConstant());
  // See HashTableBase::ElementRemoved().
  TNode<Int32T> number_of_deleted = LoadNumberOfDeleted(table, 1);
  StoreFixedArrayElement(table, EphemeronHashTable::kNumberOfElementsIndex,
                         SmiFromIntPtr(number_of_elements), SKIP_WRITE_BARRIER);
  StoreFixedArrayElement(table,
                         EphemeronHashTable::kNumberOfDeletedElementsIndex,
                         SmiFromInt32(number_of_deleted), SKIP_WRITE_BARRIER);
}
References LoadNumberOfDeleted(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::CodeStubAssembler::SmiFromInt32(), v8::internal::CodeStubAssembler::SmiFromIntPtr(), v8::internal::CodeStubAssembler::StoreFixedArrayElement(), and ValueIndexFromKeyIndex().
ShouldRehash()
TNode< BoolT > v8::internal::WeakCollectionsBuiltinsAssembler::ShouldRehash (TNode< Int32T > number_of_elements, TNode< Int32T > number_of_deleted) [protected]
Definition at line 2786 of file builtins-collections-gen.cc.
                                                                       {
  // Rehash if more than 33% of the entries are deleted.
  return Int32GreaterThanOrEqual(Word32Shl(number_of_deleted, 1),
                                 number_of_elements);
}
References v8::internal::compiler::CodeAssembler::Word32Shl().
ShouldShrink()
TNode< Word32T > v8::internal::WeakCollectionsBuiltinsAssembler::ShouldShrink (TNode< IntPtrT > capacity, TNode< IntPtrT > number_of_elements) [protected]
Definition at line 2793 of file builtins-collections-gen.cc.
                                                                {
  // See HashTable::Shrink().
  TNode<IntPtrT> quarter_capacity = WordShr(capacity, 2);
  return Word32And(
      // Shrink to fit the number of elements if only a quarter of the
      // capacity is filled with elements.
      IntPtrLessThanOrEqual(number_of_elements, quarter_capacity),
      // Allocate a new dictionary with room for at least the current
      // number of elements. The allocation method will make sure that
      // there is extra room in the dictionary for additions. Don't go
      // lower than room for 16 elements.
      IntPtrGreaterThanOrEqual(number_of_elements, IntPtrConstant(16)));
}
References v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::CodeStubAssembler::IntPtrGreaterThanOrEqual, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThanOrEqual(), v8::internal::compiler::CodeAssembler::Word32And(), and v8::internal::compiler::CodeAssembler::WordShr().
ValueIndexFromKeyIndex()
TNode< IntPtrT > v8::internal::WeakCollectionsBuiltinsAssembler::ValueIndexFromKeyIndex (TNode< IntPtrT > key_index) [protected]
Definition at line 2809 of file builtins-collections-gen.cc.
                              {
  return IntPtrAdd(
      key_index,
      IntPtrConstant(EphemeronHashTable::TodoShape::kEntryValueIndex -
                     EphemeronHashTable::kEntryKeyIndex));
}
References v8::internal::compiler::CodeAssembler::IntPtrAdd(), and v8::internal::compiler::CodeAssembler::IntPtrConstant().
Referenced by AddEntry(), and RemoveEntry().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-collections-gen.h
/mnt/V8SourceCode/src/builtins/builtins-collections-gen.cc