v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next > Class Template Reference
#include <if-else-cascade-to-switch-reducer.h>
Public Member Functions
OpIndex ReduceInputGraphBranch (OpIndex input_index, const BranchOp &branch)
Private Member Functions
void InlineAllOperationsWithoutLast (const Block *input_block)
V< None > EmitSwitch (OpIndex switch_var, base::SmallVector< SwitchOp::Case, 16 > &cases, base::SmallVector< const Block *, 16 > &false_blocks, Block *current_if_false, BranchHint next_hint)
Static Private Member Functions
static bool ContainsOnlyPureOps (const Block *block, const Graph &graph)
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >
Definition at line 79 of file if-else-cascade-to-switch-reducer.h.
Member Function Documentation
ContainsOnlyPureOps()
template<class Next >
static bool v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ContainsOnlyPureOps (const Block * block, const Graph & graph) [inline], [static], [private]
Definition at line 269 of file if-else-cascade-to-switch-reducer.h.
                                                                          {
    for (const auto& op : base::IterateWithoutLast(graph.operations(*block))) {
      // We are moving the block content to before the switch, effectively
      // moving it before the previously existing branches.
      if (!op.Effects().hoistable_before_a_branch()) {
        return false;
      }
    }
    return true;
  }
References graph(), and v8::base::IterateWithoutLast().
Referenced by v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch().
EmitSwitch()
template<class Next >
V<None> v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::EmitSwitch (OpIndex switch_var, base::SmallVector< SwitchOp::Case, 16 > & cases, base::SmallVector< const Block *, 16 > & false_blocks, Block * current_if_false, BranchHint next_hint) [inline], [private]
Definition at line 291 of file if-else-cascade-to-switch-reducer.h.
                                                                    {
    // We're skipping the last false block, as it becomes the default block.
    for (size_t i = 0; i < false_blocks.size() - 1; ++i) {
      const Block* block = false_blocks[i];
      InlineAllOperationsWithoutLast(block);
    }
    // The last current_if_true block that ends the cascade becomes the default
    // case.
    Block* default_block = current_if_false;
    Asm().Switch(
        Asm().MapToNewGraph(switch_var),
        Asm().output_graph().graph_zone()->CloneVector(base::VectorOf(cases)),
        Asm().MapToNewGraph(default_block), next_hint);
    return OpIndex::Invalid();
  }
References v8::internal::CloneVector(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::InlineAllOperationsWithoutLast(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::base::SmallVector< T, kSize, Allocator >::size(), and v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch().
InlineAllOperationsWithoutLast()
template<class Next >
void v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::InlineAllOperationsWithoutLast (const Block * input_block) [inline], [private]
Definition at line 282 of file if-else-cascade-to-switch-reducer.h.
                                                                {
    base::iterator_range<Graph::OpIndexIterator> all_ops =
        Asm().input_graph().OperationIndices(*input_block);
    for (OpIndex op : base::IterateWithoutLast(all_ops)) {
      Asm().InlineOp(op, input_block);
    }
  }
References v8::base::IterateWithoutLast().
Referenced by v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::EmitSwitch().
ReduceInputGraphBranch()
template<class Next >
OpIndex v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch (OpIndex input_index, const BranchOp & branch) [inline]
Definition at line 83 of file if-else-cascade-to-switch-reducer.h.
                                                                              {
    LABEL_BLOCK(no_change) {
      return Next::ReduceInputGraphBranch(input_index, branch);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    TRACE("[structural] Calling ReduceInputGraphBranch for index: %u\n",
          static_cast<unsigned int>(input_index.id()));
    base::SmallVector<SwitchOp::Case, 16> cases;
    base::SmallVector<const Block*, 16> false_blocks;
    Block* current_if_true;
    Block* current_if_false;
    const BranchOp* current_branch = &branch;
    BranchHint current_branch_hint;
    BranchHint next_hint = BranchHint::kNone;
    OpIndex switch_var = OpIndex::Invalid();
    uint32_t value;
    while (true) {
      // If we encounter a condition that is not equality, we can't turn it
      // into a switch case.
      const Operation& cond =
          Asm().input_graph().Get(current_branch->condition());
      if (!cond.template Is<ComparisonOp>()) {
        // 'if(x==0)' may be optimized to 'if(x)', we should take this into
        // consideration.
        // The "false" destination will be inlined before the switch is emitted,
        // so it should only contain pure operations.
        if (!ContainsOnlyPureOps(current_branch->if_true,
                                 Asm().input_graph())) {
          TRACE("\t [break] End of only-pure-ops cascade reached.\n");
          break;
        }
        OpIndex current_var = current_branch->condition();
        if (!switch_var.valid()) {
          switch_var = current_var;
        } else if (switch_var != current_var) {
          TRACE("\t [bailout] Not all branches compare the same variable.\n");
          break;
        }
        value = 0;
        // The true/false of 'if(x)' is reversed from 'if(x==0)'
        current_if_true = current_branch->if_false;
        current_if_false = current_branch->if_true;
        const BranchHint hint = current_branch->hint;
        current_branch_hint = hint == BranchHint::kNone ? BranchHint::kNone
                              : hint == BranchHint::kTrue ? BranchHint::kFalse
                                                          : BranchHint::kTrue;
      } else {
        const ComparisonOp* equal =
            cond.template TryCast<Opmask::kWord32Equal>();
        if (!equal) {
          TRACE(
              "\t [bailout] Branch with different condition than Word32 "
              "Equal.\n");
          break;
        }
        // MachineOptimizationReducer should normalize equality to put constants
        // right.
        const Operation& right_op = Asm().input_graph().Get(equal->right());
        if (!right_op.Is<Opmask::kWord32Constant>()) {
          TRACE(
              "\t [bailout] No Word32 constant on the right side of Equal.\n");
          break;
        }
        // The "false" destination will be inlined before the switch is emitted,
        // so it should only contain pure operations.
        if (!ContainsOnlyPureOps(current_branch->if_false,
                                 Asm().input_graph())) {
          TRACE("\t [break] End of only-pure-ops cascade reached.\n");
          break;
        }
        const ConstantOp& const_op = right_op.Cast<ConstantOp>();
        value = const_op.word32();
        // If we encounter equal to a different value, we can't introduce
        // a switch.
        OpIndex current_var = equal->left();
        if (!switch_var.valid()) {
          switch_var = current_var;
        } else if (switch_var != current_var) {
          TRACE("\t [bailout] Not all branches compare the same variable.\n");
          break;
        }
        current_if_true = current_branch->if_true;
        current_if_false = current_branch->if_false;
        current_branch_hint = current_branch->hint;
      }
      DCHECK(current_if_true && current_if_false);
      // We can't just use `current_branch->hint` for every case. Consider:
      //
      // if (a) { }
      // else if (b) { }
      // else if (likely(c)) { }
      // else if (d) { }
      // else { }
      //
      // The fact that `c` is Likely doesn't tell anything about the likelyness
      // of `a` and `b` compared to `c`, which means that `c` shouldn't have the
      // Likely hint in the switch. However, since `c` is likely here, it means
      // that `d` and "default" are both unlikely, even in the switch.
      //
      // So, for the 1st case, we use `current_branch->hint`.
      // Then, when we encounter a Likely hint, we mark all of the subsequent
      // cases are Unlikely, but don't mark the current one as Likely. This is
      // done with the `next_hint` variable, which is initially kNone, but
      // because kFalse when we encounter a Likely branch.
      // We never set `next_hint` as kTrue as it would only apply to subsequent
      // cases and not to already-emitted cases. The only case that could thus
      // have a kTrue annotation is the 1st one.
      DCHECK_NE(next_hint, BranchHint::kTrue);
      BranchHint hint = next_hint;
      if (cases.size() == 0) {
        // The 1st case gets its original hint.
        hint = current_branch_hint;
      } else if (current_branch_hint == BranchHint::kFalse) {
        // For other cases, if the branch has a kFalse hint, we do use it,
        // regardless of `next_hint`.
        hint = BranchHint::kNone;
      }
      if (current_branch_hint == BranchHint::kTrue) {
        // This branch is likely true, which means that all subsequent cases are
        // unlikely.
        next_hint = BranchHint::kFalse;
      }
      // The current_if_true block becomes the corresponding switch case block.
      cases.emplace_back(value, Asm().MapToNewGraph(current_if_true), hint);
      // All pure ops from the if_false block should be executed before
      // the switch, except the last Branch operation (which we drop).
      false_blocks.push_back(current_if_false);
      // If we encounter a if_false block that doesn't end with a Branch,
      // this means we've reached the end of the cascade.
      const Operation& maybe_branch =
          current_if_false->LastOperation(Asm().input_graph());
      if (!maybe_branch.Is<BranchOp>()) {
        TRACE("\t [break] Reached end of the if-else cascade.\n");
        break;
      }
      // Iterate to the next if_false block in the cascade.
      current_branch = &maybe_branch.template Cast<BranchOp>();
    }
    // Probably better to keep short if-else cascades as they are.
    if (cases.size() <= 2) {
      TRACE("\t [bailout] Cascade with less than 2 levels of nesting.\n");
      goto no_change;
    }
    CHECK_EQ(cases.size(), false_blocks.size());
    // Sorting the cases because it will help figure out if there is a duplicate
    // case (in which case we bailout, since this is not well handled by the
    // code generator).
    // Note that this isn't wasted work: there is a good chance that the
    // instruction selector will emit a binary search for this switch, which
    // will require the cases to be sorted.
    std::stable_sort(
        cases.begin(), cases.end(),
        [](SwitchOp::Case a, SwitchOp::Case b) { return a.value < b.value; });
    auto it = std::adjacent_find(
        cases.begin(), cases.end(),
        [](SwitchOp::Case a, SwitchOp::Case b) { return a.value == b.value; });
    if (it != cases.end()) {
      TRACE("\t [bailout] Multiple cases with the value %d.\n", (*it).value);
      goto no_change;
    }
    TRACE("[reduce] Successfully emit a Switch with %zu cases.\n",
          cases.size());
    return EmitSwitch(switch_var, cases, false_blocks, current_if_false,
                      next_hint);
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin(), v8::internal::compiler::turboshaft::Operation::Cast(), CHECK_EQ, v8::internal::compiler::turboshaft::BranchOp::condition(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ContainsOnlyPureOps(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::EmitSwitch(), v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::base::SmallVector< T, kSize, Allocator >::end(), v8::internal::equal, v8::internal::compiler::turboshaft::BranchOp::hint, v8::internal::compiler::turboshaft::BranchOp::if_false, v8::internal::compiler::turboshaft::BranchOp::if_true, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::kFalse, v8::internal::kNone, v8::internal::kTrue, LABEL_BLOCK, v8::internal::compiler::turboshaft::Block::LastOperation(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::base::SmallVector< T, kSize, Allocator >::size(), v8::internal::TRACE(), v8::internal::compiler::turboshaft::OpIndex::valid(), v8::internal::value, and v8::internal::compiler::turboshaft::ConstantOp::word32().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/if-else-cascade-to-switch-reducer.h