v8::internal::GeneratorBuiltinsAssembler Class Reference
Public Member Functions
GeneratorBuiltinsAssembler (compiler::CodeAssemblerState *state)
Protected Member Functions
void InnerResume (CodeStubArguments *args, TNode< JSGeneratorObject > receiver, TNode< Object > value, TNode< Context > context, JSGeneratorObject::ResumeMode resume_mode, char const *const method_name)
void GeneratorPrototypeResume (CodeStubArguments *args, TNode< Object > receiver, TNode< Object > value, TNode< Context > context, JSGeneratorObject::ResumeMode resume_mode, char const *const method_name)
TNode< IntPtrT > LoadParameterCountWithoutReceiverFromBaseline ()
Additional Inherited Members
Detailed Description
Definition at line 17 of file builtins-generator-gen.cc.
Constructor & Destructor Documentation
GeneratorBuiltinsAssembler()
v8::internal::GeneratorBuiltinsAssembler::GeneratorBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 19 of file builtins-generator-gen.cc.
      : CodeStubAssembler(state) {}
Member Function Documentation
GeneratorPrototypeResume()
void v8::internal::GeneratorBuiltinsAssembler::GeneratorPrototypeResume (CodeStubArguments * args, TNode< Object > receiver, TNode< Object > value, TNode< Context > context, JSGeneratorObject::ResumeMode resume_mode, char const *const method_name) [protected]
Definition at line 140 of file builtins-generator-gen.cc.
                                   {
  // Check if the {receiver} is actually a JSGeneratorObject.
  ThrowIfNotInstanceType(context, receiver, JS_GENERATOR_OBJECT_TYPE,
                         method_name);
  TNode<JSGeneratorObject> generator = CAST(receiver);
  InnerResume(args, generator, value, context, resume_mode, method_name);
}
References v8::base::args, CAST, InnerResume(), v8::internal::CodeStubAssembler::ThrowIfNotInstanceType(), and v8::internal::value.
InnerResume()
void v8::internal::GeneratorBuiltinsAssembler::InnerResume (CodeStubArguments * args, TNode< JSGeneratorObject > receiver, TNode< Object > value, TNode< Context > context, JSGeneratorObject::ResumeMode resume_mode, char const *const method_name) [protected]
Definition at line 49 of file builtins-generator-gen.cc.
                                                                            {
  // Check if the {receiver} is running or already closed.
  TNode<Smi> receiver_continuation =
      LoadObjectField<Smi>(receiver, JSGeneratorObject::kContinuationOffset);
  Label if_receiverisclosed(this, Label::kDeferred),
      if_receiverisrunning(this, Label::kDeferred);
  TNode<Smi> closed = SmiConstant(JSGeneratorObject::kGeneratorClosed);
  GotoIf(SmiEqual(receiver_continuation, closed), &if_receiverisclosed);
  DCHECK_LT(JSGeneratorObject::kGeneratorExecuting,
            JSGeneratorObject::kGeneratorClosed);
  GotoIf(SmiLessThan(receiver_continuation, closed), &if_receiverisrunning);
  // Remember the {resume_mode} for the {receiver}.
  StoreObjectFieldNoWriteBarrier(receiver, JSGeneratorObject::kResumeModeOffset,
                                 SmiConstant(resume_mode));
  // Resume the {receiver} using our trampoline.
  // Close the generator if there was an exception.
  TVARIABLE(Object, var_exception);
  Label if_exception(this, Label::kDeferred), if_final_return(this);
  TNode<JSAny> result;
  {
    compiler::ScopedExceptionHandler handler(this, &if_exception,
                                             &var_exception);
    result = CallBuiltin<JSAny>(Builtin::kResumeGeneratorTrampoline, context,
                                value, receiver);
  }
  // If the generator is not suspended (i.e., its state is 'executing'),
  // close it and wrap the return value in IteratorResult.
  TNode<Smi> result_continuation =
      LoadObjectField<Smi>(receiver, JSGeneratorObject::kContinuationOffset);
  // The generator function should not close the generator by itself, let's
  // check it is indeed not closed yet.
  CSA_DCHECK(this, SmiNotEqual(result_continuation, closed));
  TNode<Smi> executing = SmiConstant(JSGeneratorObject::kGeneratorExecuting);
  GotoIf(SmiEqual(result_continuation, executing), &if_final_return);
  args->PopAndReturn(result);
  BIND(&if_final_return);
  {
    // Close the generator.
    StoreObjectFieldNoWriteBarrier(
        receiver, JSGeneratorObject::kContinuationOffset, closed);
    // Return the wrapped result.
    args->PopAndReturn(CallBuiltin<JSAny>(Builtin::kCreateIterResultObject,
                                          context, result, TrueConstant()));
  }
  BIND(&if_receiverisclosed);
  {
    // The {receiver} is closed already.
    TNode<JSAny> builtin_result;
    switch (resume_mode) {
      case JSGeneratorObject::kNext:
        builtin_result =
            CallBuiltin<JSAny>(Builtin::kCreateIterResultObject, context,
                               UndefinedConstant(), TrueConstant());
        break;
      case JSGeneratorObject::kReturn:
        builtin_result = CallBuiltin<JSAny>(Builtin::kCreateIterResultObject,
                                            context, value, TrueConstant());
        break;
      case JSGeneratorObject::kThrow:
        builtin_result = CallRuntime<JSAny>(Runtime::kThrow, context, value);
        break;
      case JSGeneratorObject::kRethrow:
        // Currently only async generators use this mode.
        UNREACHABLE();
    }
    args->PopAndReturn(builtin_result);
  }
  BIND(&if_receiverisrunning);
  { ThrowTypeError(context, MessageTemplate::kGeneratorRunning); }
  BIND(&if_exception);
  {
    StoreObjectFieldNoWriteBarrier(
        receiver, JSGeneratorObject::kContinuationOffset, closed);
    CallRuntime(Runtime::kReThrow, context, var_exception.value());
    Unreachable();
  }
}
References v8::base::args, v8::internal::compiler::CodeAssembler::CallRuntime(), DCHECK_LT, v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::JSGeneratorObject::kGeneratorClosed, v8::internal::JSGeneratorObject::kGeneratorExecuting, v8::internal::JSGeneratorObject::kNext, v8::internal::JSGeneratorObject::kRethrow, v8::internal::JSGeneratorObject::kReturn, v8::internal::JSGeneratorObject::kThrow, v8::base::internal::result, v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), v8::internal::CodeStubAssembler::ThrowTypeError(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), v8::internal::UNREACHABLE(), v8::internal::compiler::CodeAssembler::Unreachable(), and v8::internal::value.
Referenced by GeneratorPrototypeResume().
LoadParameterCountWithoutReceiverFromBaseline()
TNode< IntPtrT > v8::internal::GeneratorBuiltinsAssembler::LoadParameterCountWithoutReceiverFromBaseline () [protected]
Definition at line 43 of file builtins-generator-gen.cc.
                                                                          {
  auto parameter_count = LoadBytecodeArrayParameterCountWithoutReceiver(
      LoadBytecodeArrayFromBaseline());
  return Signed(ChangeUint32ToWord(parameter_count));
}
References v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), v8::internal::CodeStubAssembler::LoadBytecodeArrayFromBaseline(), v8::internal::CodeStubAssembler::LoadBytecodeArrayParameterCountWithoutReceiver(), and v8::internal::compiler::CodeAssembler::Signed().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-generator-gen.cc