v8::internal::compiler::ObjectData Class Reference
Public Member Functions
ObjectData (JSHeapBroker *broker, ObjectData **storage, IndirectHandle< Object > object, ObjectDataKind kind)
IndirectHandle< Object > object () const
ObjectDataKind kind () const
bool is_smi () const
bool should_access_heap () const
bool IsNull () const
Private Attributes
IndirectHandle< Object > const object_
ObjectDataKind const kind_
Detailed Description
Definition at line 76 of file heap-refs.cc.
Constructor & Destructor Documentation
ObjectData()
v8::internal::compiler::ObjectData::ObjectData (JSHeapBroker * broker, ObjectData ** storage, IndirectHandle< Object > object, ObjectDataKind kind) [inline]
Definition at line 78 of file heap-refs.cc.
      : object_(object),
        kind_(kind)
#ifdef DEBUG
        ,
        broker_(broker)
#endif // DEBUG
  {
    // This assignment ensures we don't end up inserting the same object
    // in an endless recursion.
    *storage = this;
    TRACE(broker, "Creating data " << this << " for handle " << object.address()
                                   << " (" << Brief(*object) << ")");
    // It is safe to access read only heap objects and builtins from a
    // background thread. When we read fields of these objects, we may create
    // ObjectData on the background thread.
    // This is safe too since we don't create handles but just get handles from
    // read only root table or builtins table.
    // All other objects need to be canonicalized in a persistent handle scope.
    // See CanonicalPersistentHandle().
    Isolate* isolate = broker->isolate();
    USE(isolate);
    DCHECK_IMPLIES(broker->mode() == JSHeapBroker::kDisabled ||
                       broker->mode() == JSHeapBroker::kSerializing,
                   PersistentHandlesScope::IsActive(isolate) &&
                       broker->IsCanonicalHandle(object));
    DCHECK_IMPLIES(broker->mode() == JSHeapBroker::kSerialized,
                   kind == kUnserializedReadOnlyHeapObject || kind == kSmi ||
                       kind == kNeverSerializedHeapObject ||
                       kind == kBackgroundSerializedHeapObject);
    DCHECK_IMPLIES(kind == kUnserializedReadOnlyHeapObject,
                   i::IsHeapObject(*object) &&
                       ReadOnlyHeap::Contains(Cast<HeapObject>(*object)));
  }
References broker(), v8::internal::ReadOnlyHeap::Contains(), DCHECK_IMPLIES, v8::internal::PersistentHandlesScope::IsActive(), v8::internal::InstanceTypeChecker::IsHeapObject(), v8::internal::compiler::kBackgroundSerializedHeapObject, v8::internal::compiler::JSHeapBroker::kDisabled, kind(), v8::internal::compiler::kNeverSerializedHeapObject, v8::internal::compiler::JSHeapBroker::kSerialized, v8::internal::compiler::JSHeapBroker::kSerializing, v8::internal::compiler::kSmi, v8::internal::compiler::kUnserializedReadOnlyHeapObject, v8::internal::TRACE(), and USE.
Member Function Documentation
is_smi()
bool v8::internal::compiler::ObjectData::is_smi () const [inline]
Definition at line 126 of file heap-refs.cc.
{ return kind_ == kSmi; }
References kind_, and v8::internal::compiler::kSmi.
IsNull()
bool v8::internal::compiler::ObjectData::IsNull () const [inline]
Definition at line 132 of file heap-refs.cc.
{ return i::IsNull(*object_); }
References v8::internal::IsNull(), and object_.
kind()
ObjectDataKind v8::internal::compiler::ObjectData::kind () const [inline]
Definition at line 125 of file heap-refs.cc.
{ return kind_; }
References kind_.
Referenced by v8::internal::compiler::HeapObjectData::GetMapInstanceType(), v8::internal::compiler::HeapObjectData::HeapObjectData(), and ObjectData().
object()
IndirectHandle<Object> v8::internal::compiler::ObjectData::object () const [inline]
Definition at line 124 of file heap-refs.cc.
{ return object_; }
References object_.
Referenced by v8::internal::compiler::JSFunctionData::Cache(), v8::internal::compiler::HeapObjectData::GetMapInstanceType(), v8::internal::compiler::HeapObjectData::HeapObjectData(), v8::internal::compiler::JSFunctionData::IsConsistentWithHeapState(), and v8::internal::compiler::HeapObjectData::TryGetBooleanValueImpl().
should_access_heap()
bool v8::internal::compiler::ObjectData::should_access_heap () const [inline]
Definition at line 127 of file heap-refs.cc.
                                  {
    return kind_ == kUnserializedHeapObject ||
           kind_ == kNeverSerializedHeapObject ||
           kind_ == kUnserializedReadOnlyHeapObject;
  }
References kind_, v8::internal::compiler::kNeverSerializedHeapObject, v8::internal::compiler::kUnserializedHeapObject, and v8::internal::compiler::kUnserializedReadOnlyHeapObject.
Referenced by v8::internal::compiler::HeapObjectData::GetMapInstanceType().
Member Data Documentation
kind_
ObjectDataKind const v8::internal::compiler::ObjectData::kind_ [private]
Definition at line 140 of file heap-refs.cc.
Referenced by is_smi(), kind(), and should_access_heap().
object_
IndirectHandle<Object> const v8::internal::compiler::ObjectData::object_ [private]
Definition at line 139 of file heap-refs.cc.
Referenced by IsNull(), and object().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/heap-refs.cc