v8::String::ExternalStringResourceBase Class Reference
#include <v8-primitive.h>
Classes
class SharedMemoryUsageRecorder
Public Member Functions
virtual ~ExternalStringResourceBase ()=default
virtual bool IsCacheable () const
If a string is cacheable, the value returned by ExternalStringResource::data() may be cached, otherwise it is not expected to be stable beyond the current top-level task.
virtual void Unaccount (Isolate *isolate)
Internally V8 will call this Unaccount method when the external string resource should be unaccounted for.
virtual size_t EstimateMemoryUsage () const
Returns an estimate of the memory occupied by this external string, to be used by V8 when producing a heap snapshot.
virtual void EstimateSharedMemoryUsage (SharedMemoryUsageRecorder *recorder) const
Estimates memory that this string resource may share with other string resources, to be used by V8 when producing a heap snapshot.
ExternalStringResourceBase (const ExternalStringResourceBase &)=delete
void operator= (const ExternalStringResourceBase &)=delete
Static Public Attributes
static constexpr size_t kDefaultMemoryEstimate = static_cast<size_t>(-1)
Protected Member Functions
ExternalStringResourceBase ()=default
virtual void Dispose ()
Internally V8 will call this Dispose method when the external string resource is no longer needed.
virtual void Lock () const
For a non-cacheable string, the value returned by |ExternalStringResource::data()| has to be stable between |Lock()| and |Unlock()|, that is the string must behave as is |IsCacheable()| returned true.
virtual void Unlock () const
Unlocks the string.
Friends
class internal::ExternalString
class v8::String
class internal::StringForwardingTable
class internal::ScopedExternalStringLock
Detailed Description
Definition at line 295 of file v8-primitive.h.
Constructor & Destructor Documentation
 ExternalStringResourceBase()
virtual v8::String::ExternalStringResourceBase::~ExternalStringResourceBase () [virtual], [default]
ExternalStringResourceBase() [1/2]
v8::String::ExternalStringResourceBase::ExternalStringResourceBase (const ExternalStringResourceBase &) [delete]
ExternalStringResourceBase() [2/2]
v8::String::ExternalStringResourceBase::ExternalStringResourceBase () [protected], [default]
Member Function Documentation
Dispose()
virtual void v8::String::ExternalStringResourceBase::Dispose () [inline], [protected], [virtual]
Internally V8 will call this Dispose method when the external string resource is no longer needed.
The default implementation will use the delete operator. This method can be overridden in subclasses to control how allocated external string resources are disposed.
Reimplemented in v8::anonymous_namespace{api.cc}::ExtensionResource.
Definition at line 357 of file v8-primitive.h.
{ delete this; }
Referenced by v8::internal::ExternalString::DisposeResource(), v8::String::NewExternalOneByte(), and v8::String::NewExternalTwoByte().
EstimateMemoryUsage()
virtual size_t v8::String::ExternalStringResourceBase::EstimateMemoryUsage () const [inline], [virtual]
Returns an estimate of the memory occupied by this external string, to be used by V8 when producing a heap snapshot.
If this function returns kDefaultMemoryEstimate, then V8 will estimate the external size based on the string length. This function should return only memory that is uniquely owned by this resource. If the resource has shared ownership of a secondary allocation, it can report that memory by implementing EstimateSharedMemoryUsage.
Definition at line 322 of file v8-primitive.h.
                                               {
      return kDefaultMemoryEstimate;
    }
Referenced by v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::ExternalStringSizeForSnapshot().
EstimateSharedMemoryUsage()
virtual void v8::String::ExternalStringResourceBase::EstimateSharedMemoryUsage (SharedMemoryUsageRecorder * recorder) const [inline], [virtual]
Estimates memory that this string resource may share with other string resources, to be used by V8 when producing a heap snapshot.
Definition at line 341 of file v8-primitive.h.
                                                   {}
IsCacheable()
virtual bool v8::String::ExternalStringResourceBase::IsCacheable () const [inline], [virtual]
If a string is cacheable, the value returned by ExternalStringResource::data() may be cached, otherwise it is not expected to be stable beyond the current top-level task.
Definition at line 304 of file v8-primitive.h.
{ return true; }
Referenced by v8::internal::String::MakeExternal(), v8::internal::Factory::NewExternalStringFromOneByte(), v8::internal::Factory::NewExternalStringFromTwoByte(), and v8::String::ExternalStringResource::UpdateDataCache().
Lock()
virtual void v8::String::ExternalStringResourceBase::Lock () const [inline], [protected], [virtual]
For a non-cacheable string, the value returned by |ExternalStringResource::data()| has to be stable between |Lock()| and |Unlock()|, that is the string must behave as is |IsCacheable()| returned true.
These two functions must be thread-safe, and can be called from anywhere. They also must handle lock depth, in the sense that each can be called several times, from different threads, and unlocking should only happen when the balance of Lock() and Unlock() calls is 0.
Definition at line 370 of file v8-primitive.h.
{}
operator=()
void v8::String::ExternalStringResourceBase::operator= (const ExternalStringResourceBase &) [delete]
Unaccount()
virtual void v8::String::ExternalStringResourceBase::Unaccount (Isolate * isolate) [inline], [virtual]
Internally V8 will call this Unaccount method when the external string resource should be unaccounted for.
This method can be overridden in subclasses to control how allocated external bytes are accounted.
Definition at line 311 of file v8-primitive.h.
{}
Referenced by v8::internal::ExternalString::DisposeResource(), v8::internal::String::MakeExternal(), v8::String::NewExternalOneByte(), and v8::String::NewExternalTwoByte().
Unlock()
virtual void v8::String::ExternalStringResourceBase::Unlock () const [inline], [protected], [virtual]
Unlocks the string.
Definition at line 375 of file v8-primitive.h.
{}
Friends And Related Function Documentation
internal::ExternalString
friend class internal::ExternalString [friend]
Definition at line 378 of file v8-primitive.h.
internal::ScopedExternalStringLock
friend class internal::ScopedExternalStringLock [friend]
Definition at line 381 of file v8-primitive.h.
internal::StringForwardingTable
friend class internal::StringForwardingTable [friend]
Definition at line 380 of file v8-primitive.h.
v8::String
friend class v8::String [friend]
Definition at line 379 of file v8-primitive.h.
Member Data Documentation
kDefaultMemoryEstimate
constexpr size_t v8::String::ExternalStringResourceBase::kDefaultMemoryEstimate = static_cast<size_t>(-1) [static], [constexpr]
Definition at line 325 of file v8-primitive.h.
Referenced by v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::ExternalStringSizeForSnapshot().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-primitive.h