v8::internal::maglev::MaglevAssembler Class Reference
#include <maglev-assembler.h>
Classes
class TemporaryRegisterScope
class TemporaryRegisterScopeBase
Public Types
enum StoreMode { kField
, kElement
 }
enum ValueIsCompressed { kValueIsDecompressed
, kValueIsCompressed
 }
enum ValueCanBeSmi { kValueCannotBeSmi
, kValueCanBeSmi
 }
enum class CharCodeMaskMode { kValueIsInRange
, kMustApplyMask
 }
template<StoreMode store_mode>
using OffsetTypeFor = std::conditional_t< store_mode==kField, int, Register >
Public Member Functions
MaglevAssembler (Isolate *isolate, Zone *zone, MaglevCodeGenState *code_gen_state)
MemOperand GetStackSlot (const compiler::AllocatedOperand &operand)
MemOperand ToMemOperand (const compiler::InstructionOperand &operand)
MemOperand ToMemOperand (const ValueLocation &location)
Register GetFramePointer ()
int GetFramePointerOffsetForStackSlot (const compiler::AllocatedOperand &operand)
template<typename Dest , typename Source >
void MoveRepr (MachineRepresentation repr, Dest dst, Source src)
void Allocate (RegisterSnapshot register_snapshot, Register result, int size_in_bytes, AllocationType alloc_type=AllocationType::kYoung, AllocationAlignment alignment=kTaggedAligned)
void Allocate (RegisterSnapshot register_snapshot, Register result, Register size_in_bytes, AllocationType alloc_type=AllocationType::kYoung, AllocationAlignment alignment=kTaggedAligned)
void AllocateHeapNumber (RegisterSnapshot register_snapshot, Register result, DoubleRegister value)
void AllocateTwoByteString (RegisterSnapshot register_snapshot, Register result, int length)
void LoadSingleCharacterString (Register result, int char_code)
void LoadSingleCharacterString (Register result, Register char_code, Register scratch)
void EnsureWritableFastElements (RegisterSnapshot register_snapshot, Register elements, Register object, Register scratch)
void BindJumpTarget (Label *label)
void BindBlock (BasicBlock *block)
Condition IsRootConstant (Input input, RootIndex root_index)
void Branch (Condition condition, BasicBlock *if_true, BasicBlock *if_false, BasicBlock *next_block)
void Branch (Condition condition, Label *if_true, Label::Distance true_distance, bool fallthrough_when_true, Label *if_false, Label::Distance false_distance, bool fallthrough_when_false)
Register FromAnyToRegister (const Input &input, Register scratch)
void LoadTaggedField (Register result, MemOperand operand)
void LoadTaggedField (Register result, Register object, int offset)
void LoadTaggedFieldWithoutDecompressing (Register result, Register object, int offset)
void LoadTaggedSignedField (Register result, MemOperand operand)
void LoadTaggedSignedField (Register result, Register object, int offset)
void LoadAndUntagTaggedSignedField (Register result, Register object, int offset)
void LoadTaggedFieldByIndex (Register result, Register object, Register index, int scale, int offset)
void LoadBoundedSizeFromObject (Register result, Register object, int offset)
void LoadExternalPointerField (Register result, MemOperand operand)
void LoadFixedArrayElement (Register result, Register array, Register index)
void LoadFixedArrayElementWithoutDecompressing (Register result, Register array, Register index)
void LoadFixedDoubleArrayElement (DoubleRegister result, Register array, Register index)
void StoreFixedDoubleArrayElement (Register array, Register index, DoubleRegister value)
void LoadSignedField (Register result, MemOperand operand, int element_size)
void LoadUnsignedField (Register result, MemOperand operand, int element_size)
template<typename BitField >
void LoadBitField (Register result, MemOperand operand)
void SetSlotAddressForTaggedField (Register slot_reg, Register object, int offset)
void SetSlotAddressForFixedArrayElement (Register slot_reg, Register object, Register index)
template<StoreMode store_mode>
void CheckAndEmitDeferredWriteBarrier (Register object, OffsetTypeFor< store_mode > offset, Register value, RegisterSnapshot register_snapshot, ValueIsCompressed value_is_compressed, ValueCanBeSmi value_can_be_smi)
void CheckAndEmitDeferredIndirectPointerWriteBarrier (Register object, int offset, Register value, RegisterSnapshot register_snapshot, IndirectPointerTag tag)
void StoreTaggedFieldWithWriteBarrier (Register object, int offset, Register value, RegisterSnapshot register_snapshot, ValueIsCompressed value_is_compressed, ValueCanBeSmi value_can_be_smi)
void StoreTaggedFieldNoWriteBarrier (Register object, int offset, Register value)
void StoreTaggedSignedField (Register object, int offset, Register value)
void StoreTaggedSignedField (Register object, int offset, Tagged< Smi > value)
void StoreInt32Field (Register object, int offset, int32_t value)
void AssertElidedWriteBarrier (Register object, Register value, RegisterSnapshot snapshot)
void StoreField (MemOperand operand, Register value, int element_size)
void ReverseByteOrder (Register value, int element_size)
void BuildTypedArrayDataPointer (Register data_pointer, Register object)
MemOperand TypedArrayElementOperand (Register data_pointer, Register index, int element_size)
MemOperand DataViewElementOperand (Register data_pointer, Register index)
void StringCharCodeOrCodePointAt (BuiltinStringPrototypeCharCodeOrCodePointAt::Mode mode, RegisterSnapshot &register_snapshot, Register result, Register string, Register index, Register scratch1, Register scratch2, Label *result_fits_one_byte)
void SeqOneByteStringCharCodeAt (Register result, Register string, Register index)
void StringFromCharCode (RegisterSnapshot register_snapshot, Label *char_code_fits_one_byte, Register result, Register char_code, Register scratch, CharCodeMaskMode mask_mode)
void ToBoolean (Register value, CheckType check_type, ZoneLabelRef is_true, ZoneLabelRef is_false, bool fallthrough_when_true)
void TestTypeOf (Register object, interpreter::TestTypeOfFlags::LiteralFlag literal, Label *if_true, Label::Distance true_distance, bool fallthrough_when_true, Label *if_false, Label::Distance false_distance, bool fallthrough_when_false)
void SmiTagInt32AndJumpIfFail (Register dst, Register src, Label *fail, Label::Distance distance=Label::kFar)
void SmiTagInt32AndJumpIfFail (Register reg, Label *fail, Label::Distance distance=Label::kFar)
void SmiTagInt32AndJumpIfSuccess (Register dst, Register src, Label *success, Label::Distance distance=Label::kFar)
void SmiTagInt32AndJumpIfSuccess (Register reg, Label *success, Label::Distance distance=Label::kFar)
void UncheckedSmiTagInt32 (Register dst, Register src)
void UncheckedSmiTagInt32 (Register reg)
void SmiTagUint32AndJumpIfFail (Register dst, Register src, Label *fail, Label::Distance distance=Label::kFar)
void SmiTagUint32AndJumpIfFail (Register reg, Label *fail, Label::Distance distance=Label::kFar)
void SmiTagIntPtrAndJumpIfFail (Register dst, Register src, Label *fail, Label::Distance distance=Label::kFar)
void SmiTagUint32AndJumpIfSuccess (Register dst, Register src, Label *success, Label::Distance distance=Label::kFar)
void SmiTagUint32AndJumpIfSuccess (Register reg, Label *success, Label::Distance distance=Label::kFar)
void SmiTagIntPtrAndJumpIfSuccess (Register dst, Register src, Label *success, Label::Distance distance=Label::kFar)
void UncheckedSmiTagUint32 (Register dst, Register src)
void UncheckedSmiTagUint32 (Register reg)
void CheckInt32IsSmi (Register obj, Label *fail, Register scratch=Register::no_reg())
void CheckIntPtrIsSmi (Register obj, Label *fail, Label::Distance distance=Label::kFar)
void SmiAddConstant (Register dst, Register src, int value, Label *fail, Label::Distance distance=Label::kFar)
void SmiAddConstant (Register reg, int value, Label *fail, Label::Distance distance=Label::kFar)
void SmiSubConstant (Register dst, Register src, int value, Label *fail, Label::Distance distance=Label::kFar)
void SmiSubConstant (Register reg, int value, Label *fail, Label::Distance distance=Label::kFar)
void MoveHeapNumber (Register dst, double value)
void TruncateDoubleToInt32 (Register dst, DoubleRegister src)
void TryTruncateDoubleToInt32 (Register dst, DoubleRegister src, Label *fail)
void TryTruncateDoubleToUint32 (Register dst, DoubleRegister src, Label *fail)
void TryChangeFloat64ToIndex (Register result, DoubleRegister value, Label *success, Label *fail)
void MaybeEmitPlaceHolderForDeopt ()
void DefineLazyDeoptPoint (LazyDeoptInfo *info)
void DefineExceptionHandlerPoint (NodeBase *node)
void DefineExceptionHandlerAndLazyDeoptPoint (NodeBase *node)
template<typename Function , typename... Args>
Label * MakeDeferredCode (Function &&deferred_code_gen, Args &&... args)
template<typename Function , typename... Args>
void JumpToDeferredIf (Condition cond, Function &&deferred_code_gen, Args &&... args)
void JumpIfNotCallable (Register object, Register scratch, CheckType check_type, Label *target, Label::Distance distance=Label::kFar)
void JumpIfUndetectable (Register object, Register scratch, CheckType check_type, Label *target, Label::Distance distance=Label::kFar)
void JumpIfNotUndetectable (Register object, Register scratch, CheckType, Label *target, Label::Distance distance=Label::kFar)
template<typename NodeT >
Label * GetDeoptLabel (NodeT *node, DeoptimizeReason reason)
bool IsDeoptLabel (Label *label)
void EmitEagerDeoptStress (Label *label)
template<typename NodeT >
void EmitEagerDeopt (NodeT *node, DeoptimizeReason reason)
template<typename NodeT >
void EmitEagerDeoptIf (Condition cond, DeoptimizeReason reason, NodeT *node)
template<typename NodeT >
void EmitEagerDeoptIfNotEqual (DeoptimizeReason reason, NodeT *node)
template<typename NodeT >
void EmitEagerDeoptIfSmi (NodeT *node, Register object, DeoptimizeReason reason)
template<typename NodeT >
void EmitEagerDeoptIfNotSmi (NodeT *node, Register object, DeoptimizeReason reason)
void MaterialiseValueNode (Register dst, ValueNode *value)
void IncrementInt32 (Register reg)
void DecrementInt32 (Register reg)
void AddInt32 (Register reg, int amount)
void AndInt32 (Register reg, int mask)
void OrInt32 (Register reg, int mask)
void AndInt32 (Register reg, Register other)
void OrInt32 (Register reg, Register other)
void ShiftLeft (Register reg, int amount)
void IncrementAddress (Register reg, int32_t delta)
void LoadAddress (Register dst, MemOperand location)
void Call (Label *target)
void EmitEnterExitFrame (int extra_slots, StackFrame::Type frame_type, Register c_function, Register scratch)
MemOperand StackSlotOperand (StackSlot slot)
void Move (StackSlot dst, Register src)
void Move (StackSlot dst, DoubleRegister src)
void Move (Register dst, StackSlot src)
void Move (DoubleRegister dst, StackSlot src)
void Move (MemOperand dst, Register src)
void Move (Register dst, MemOperand src)
void Move (DoubleRegister dst, DoubleRegister src)
void Move (Register dst, Tagged< Smi > src)
void Move (Register dst, ExternalReference src)
void Move (Register dst, Register src)
void Move (Register dst, Tagged< TaggedIndex > i)
void Move (Register dst, int32_t i)
void Move (Register dst, uint32_t i)
void Move (Register dst, IndirectPointerTag i)
void Move (DoubleRegister dst, double n)
void Move (DoubleRegister dst, Float64 n)
void Move (Register dst, Handle< HeapObject > obj)
void MoveTagged (Register dst, Handle< HeapObject > obj)
void LoadMapForCompare (Register dst, Register obj)
void LoadByte (Register dst, MemOperand src)
void LoadInt32 (Register dst, MemOperand src)
void StoreInt32 (MemOperand dst, Register src)
void LoadFloat32 (DoubleRegister dst, MemOperand src)
void StoreFloat32 (MemOperand dst, DoubleRegister src)
void LoadFloat64 (DoubleRegister dst, MemOperand src)
void StoreFloat64 (MemOperand dst, DoubleRegister src)
void LoadUnalignedFloat64 (DoubleRegister dst, Register base, Register index)
void LoadUnalignedFloat64AndReverseByteOrder (DoubleRegister dst, Register base, Register index)
void StoreUnalignedFloat64 (Register base, Register index, DoubleRegister src)
void ReverseByteOrderAndStoreUnalignedFloat64 (Register base, Register index, DoubleRegister src)
void SignExtend32To64Bits (Register dst, Register src)
void NegateInt32 (Register val)
void CountLeadingZerosInt32 (Register dst, Register src)
void ToUint8Clamped (Register result, DoubleRegister value, Label *min, Label *max, Label *done)
template<typename NodeT >
void DeoptIfBufferDetached (Register array, Register scratch, NodeT *node)
Condition IsCallableAndNotUndetectable (Register map, Register scratch)
Condition IsNotCallableNorUndetactable (Register map, Register scratch)
void LoadInstanceType (Register instance_type, Register heap_object)
void JumpIfObjectType (Register heap_object, InstanceType type, Label *target, Label::Distance distance=Label::kFar)
void JumpIfNotObjectType (Register heap_object, InstanceType type, Label *target, Label::Distance distance=Label::kFar)
void AssertObjectType (Register heap_object, InstanceType type, AbortReason reason)
void BranchOnObjectType (Register heap_object, InstanceType type, Label *if_true, Label::Distance true_distance, bool fallthrough_when_true, Label *if_false, Label::Distance false_distance, bool fallthrough_when_false)
void JumpIfObjectTypeInRange (Register heap_object, InstanceType lower_limit, InstanceType higher_limit, Label *target, Label::Distance distance=Label::kFar)
void JumpIfObjectTypeNotInRange (Register heap_object, InstanceType lower_limit, InstanceType higher_limit, Label *target, Label::Distance distance=Label::kFar)
void AssertObjectTypeInRange (Register heap_object, InstanceType lower_limit, InstanceType higher_limit, AbortReason reason)
void BranchOnObjectTypeInRange (Register heap_object, InstanceType lower_limit, InstanceType higher_limit, Label *if_true, Label::Distance true_distance, bool fallthrough_when_true, Label *if_false, Label::Distance false_distance, bool fallthrough_when_false)
void JumpIfJSAnyIsNotPrimitive (Register heap_object, Label *target, Label::Distance distance=Label::kFar)
void JumpIfStringMap (Register map, Label *target, Label::Distance distance=Label::kFar, bool jump_if_true=true)
void JumpIfSeqOneByteStringMap (Register map, Label *target, Label::Distance distance=Label::kFar, bool jump_if_true=true)
void JumpIfString (Register heap_object, Label *target, Label::Distance distance=Label::kFar)
void JumpIfNotString (Register heap_object, Label *target, Label::Distance distance=Label::kFar)
void JumpIfNotSeqOneByteString (Register heap_object, Label *target, Label::Distance distance=Label::kFar)
void CheckJSAnyIsStringAndBranch (Register heap_object, Label *if_true, Label::Distance true_distance, bool fallthrough_when_true, Label *if_false, Label::Distance false_distance, bool fallthrough_when_false)
void CompareMapWithRoot (Register object, RootIndex index, Register scratch)
void CompareInstanceTypeAndJumpIf (Register map, InstanceType type, Condition cond, Label *target, Label::Distance distance)
void CompareInstanceType (Register map, InstanceType instance_type)
void CompareInstanceTypeRange (Register map, InstanceType lower_limit, InstanceType higher_limit)
Condition CompareInstanceTypeRange (Register map, Register instance_type_out, InstanceType lower_limit, InstanceType higher_limit)
template<typename NodeT >
void CompareInstanceTypeRangeAndEagerDeoptIf (Register map, Register instance_type_out, InstanceType lower_limit, InstanceType higher_limit, Condition cond, DeoptimizeReason reason, NodeT *node)
template<typename NodeT >
void CompareRootAndEmitEagerDeoptIf (Register reg, RootIndex index, Condition cond, DeoptimizeReason reason, NodeT *node)
template<typename NodeT >
void CompareMapWithRootAndEmitEagerDeoptIf (Register reg, RootIndex index, Register scratch, Condition cond, DeoptimizeReason reason, NodeT *node)
template<typename NodeT >
void CompareTaggedRootAndEmitEagerDeoptIf (Register reg, RootIndex index, Condition cond, DeoptimizeReason reason, NodeT *node)
template<typename NodeT >
void CompareUInt32AndEmitEagerDeoptIf (Register reg, int imm, Condition cond, DeoptimizeReason reason, NodeT *node)
void CompareTaggedAndJumpIf (Register reg, Tagged< Smi > smi, Condition cond, Label *target, Label::Distance distance=Label::kFar)
void CompareTaggedAndJumpIf (Register reg, Handle< HeapObject > obj, Condition cond, Label *target, Label::Distance distance=Label::kFar)
void CompareTaggedAndJumpIf (Register src1, Register src2, Condition cond, Label *target, Label::Distance distance=Label::kFar)
void CompareFloat64AndJumpIf (DoubleRegister src1, DoubleRegister src2, Condition cond, Label *target, Label *nan_failed, Label::Distance distance=Label::kFar)
void CompareFloat64AndBranch (DoubleRegister src1, DoubleRegister src2, Condition cond, BasicBlock *if_true, BasicBlock *if_false, BasicBlock *next_block, BasicBlock *nan_failed)
void PrepareCallCFunction (int num_reg_arguments, int num_double_registers=0)
void CallSelf ()
void CallBuiltin (Builtin builtin)
template<Builtin kBuiltin, typename... Args>
void CallBuiltin (Args &&... args)
void CallRuntime (Runtime::FunctionId fid)
void CallRuntime (Runtime::FunctionId fid, int num_args)
void Jump (Label *target, Label::Distance distance=Label::kFar)
void JumpToDeopt (Label *target)
void JumpIf (Condition cond, Label *target, Label::Distance distance=Label::kFar)
void JumpIfRoot (Register with, RootIndex index, Label *if_equal, Label::Distance distance=Label::kFar)
void JumpIfNotRoot (Register with, RootIndex index, Label *if_not_equal, Label::Distance distance=Label::kFar)
void JumpIfSmi (Register src, Label *on_smi, Label::Distance near_jump=Label::kFar)
void JumpIfNotSmi (Register src, Label *on_not_smi, Label::Distance near_jump=Label::kFar)
void JumpIfByte (Condition cc, Register value, int32_t byte, Label *target, Label::Distance distance=Label::kFar)
void Float64SilenceNan (DoubleRegister value)
void JumpIfHoleNan (DoubleRegister value, Register scratch, Label *target, Label::Distance distance=Label::kFar)
void JumpIfNotHoleNan (DoubleRegister value, Register scratch, Label *target, Label::Distance distance=Label::kFar)
void JumpIfNan (DoubleRegister value, Label *target, Label::Distance distance=Label::kFar)
void JumpIfNotNan (DoubleRegister value, Label *target, Label::Distance distance=Label::kFar)
void JumpIfNotHoleNan (MemOperand operand, Label *target, Label::Distance distance=Label::kFar)
void CompareInt32AndJumpIf (Register r1, Register r2, Condition cond, Label *target, Label::Distance distance=Label::kFar)
void CompareIntPtrAndJumpIf (Register r1, Register r2, Condition cond, Label *target, Label::Distance distance=Label::kFar)
void CompareIntPtrAndJumpIf (Register r1, int32_t value, Condition cond, Label *target, Label::Distance distance=Label::kFar)
void CompareInt32AndJumpIf (Register r1, int32_t value, Condition cond, Label *target, Label::Distance distance=Label::kFar)
void CompareInt32AndBranch (Register r1, int32_t value, Condition cond, BasicBlock *if_true, BasicBlock *if_false, BasicBlock *next_block)
void CompareInt32AndBranch (Register r1, Register r2, Condition cond, BasicBlock *if_true, BasicBlock *if_false, BasicBlock *next_block)
void CompareInt32AndBranch (Register r1, int32_t value, Condition cond, Label *if_true, Label::Distance true_distance, bool fallthrough_when_true, Label *if_false, Label::Distance false_distance, bool fallthrough_when_false)
void CompareInt32AndBranch (Register r1, Register r2, Condition cond, Label *if_true, Label::Distance true_distance, bool fallthrough_when_true, Label *if_false, Label::Distance false_distance, bool fallthrough_when_false)
void CompareIntPtrAndBranch (Register r1, int32_t value, Condition cond, BasicBlock *if_true, BasicBlock *if_false, BasicBlock *next_block)
void CompareIntPtrAndBranch (Register r1, int32_t value, Condition cond, Label *if_true, Label::Distance true_distance, bool fallthrough_when_true, Label *if_false, Label::Distance false_distance, bool fallthrough_when_false)
void CompareInt32AndAssert (Register r1, Register r2, Condition cond, AbortReason reason)
void CompareInt32AndAssert (Register r1, int32_t value, Condition cond, AbortReason reason)
void CompareSmiAndJumpIf (Register r1, Tagged< Smi > value, Condition cond, Label *target, Label::Distance distance=Label::kFar)
void CompareSmiAndAssert (Register r1, Tagged< Smi > value, Condition cond, AbortReason reason)
void CompareByteAndJumpIf (MemOperand left, int8_t right, Condition cond, Register scratch, Label *target, Label::Distance distance=Label::kFar)
void CompareDoubleAndJumpIfZeroOrNaN (DoubleRegister reg, Label *target, Label::Distance distance=Label::kFar)
void CompareDoubleAndJumpIfZeroOrNaN (MemOperand operand, Label *target, Label::Distance distance=Label::kFar)
void TestInt32AndJumpIfAnySet (Register r1, int32_t mask, Label *target, Label::Distance distance=Label::kFar)
void TestInt32AndJumpIfAnySet (MemOperand operand, int32_t mask, Label *target, Label::Distance distance=Label::kFar)
void TestUint8AndJumpIfAnySet (MemOperand operand, uint8_t mask, Label *target, Label::Distance distance=Label::kFar)
void TestInt32AndJumpIfAllClear (Register r1, int32_t mask, Label *target, Label::Distance distance=Label::kFar)
void TestInt32AndJumpIfAllClear (MemOperand operand, int32_t mask, Label *target, Label::Distance distance=Label::kFar)
void TestUint8AndJumpIfAllClear (MemOperand operand, uint8_t mask, Label *target, Label::Distance distance=Label::kFar)
void Int32ToDouble (DoubleRegister result, Register src)
void Uint32ToDouble (DoubleRegister result, Register src)
void SmiToDouble (DoubleRegister result, Register smi)
void IntPtrToDouble (DoubleRegister result, Register src)
void StringLength (Register result, Register string)
void LoadThinStringValue (Register result, Register string)
void StoreFixedArrayElementWithWriteBarrier (Register array, Register index, Register value, RegisterSnapshot register_snapshot)
void StoreFixedArrayElementNoWriteBarrier (Register array, Register index, Register value)
void Pop (Register dst)
template<typename... T>
void Push (T... vals)
template<typename... T>
void PushReverse (T... vals)
void OSRPrologue (Graph *graph)
void Prologue (Graph *graph)
void FinishCode ()
void AssertStackSizeCorrect ()
Condition FunctionEntryStackCheck (int stack_check_offset)
void SetMapAsRoot (Register object, RootIndex map)
void AssertContextCellState (Register cell, ContextCell::State state, Condition condition=kEqual)
void LoadContextCellState (Register state, Register cell)
void LoadContextCellTaggedValue (Register value, Register cell)
void StoreContextCellSmiValue (Register cell, Register value)
void LoadContextCellInt32Value (Register value, Register cell)
void StoreContextCellInt32Value (Register cell, Register value)
void LoadContextCellFloat64Value (DoubleRegister value, Register cell)
void StoreContextCellFloat64Value (Register cell, DoubleRegister value)
void LoadHeapNumberValue (DoubleRegister result, Register heap_number)
void StoreHeapNumberValue (DoubleRegister value, Register heap_number)
void LoadHeapNumberOrOddballValue (DoubleRegister result, Register object)
void LoadDataField (const PolymorphicAccessInfo &access_info, Register result, Register object, Register scratch)
void MaybeEmitDeoptBuiltinsCall (size_t eager_deopt_count, Label *eager_deopt_entry, size_t lazy_deopt_count, Label *lazy_deopt_entry)
void TryMigrateInstance (Register object, RegisterSnapshot &register_snapshot, Label *fail)
void TryMigrateInstanceAndMarkMapAsMigrationTarget (Register object, RegisterSnapshot &register_snapshot)
compiler::NativeContextRef native_context () const
MaglevCodeGenState * code_gen_state () const
MaglevSafepointTableBuilder * safepoint_table_builder () const
MaglevCompilationInfo * compilation_info () const
TemporaryRegisterScope * scratch_register_scope () const
template<> void MoveRepr (MachineRepresentation repr, Register dst, Register src)
template<> void MoveRepr (MachineRepresentation repr, Register dst, MemOperand src)
template<> void MoveRepr (MachineRepresentation repr, MemOperand dst, Register src)
template<> void MoveRepr (MachineRepresentation repr, MemOperand dst, MemOperand src)
void Pop (Register dst)
void Pop (Register src1, Register src2, Condition cond=al)
void Pop (Register src1, Register src2, Register src3, Condition cond=al)
void Pop (Register src1, Register src2, Register src3, Register src4, Condition cond=al)
template<LoadLRMode lr_mode = kDontLoadLR>
void Pop (const CPURegister &dst0, const CPURegister &dst1=NoReg, const CPURegister &dst2=NoReg, const CPURegister &dst3=NoReg)
void Pop (const CPURegister &dst0, const CPURegister &dst1, const CPURegister &dst2, const CPURegister &dst3, const CPURegister &dst4, const CPURegister &dst5=NoReg, const CPURegister &dst6=NoReg, const CPURegister &dst7=NoReg)
void Pop (Register dst)
void Pop (Operand dst)
void Pop (XMMRegister dst, Register scratch)
void Pop (Register dst)
void Pop (Register src1, Register src2)
void Pop (Register src1, Register src2, Register src3)
void Pop (Register dst)
void Pop (Register src1, Register src2)
void Pop (Register src1, Register src2, Register src3)
void Pop (uint32_t count=1)
void Pop (Register dst)
void Pop (Register src1, Register src2)
void Pop (Register src1, Register src2, Register src3)
void Pop (Register src1, Register src2, Register src3, Register src4)
void Pop (Register src1, Register src2, Register src3, Register src4, Register src5)
void Pop (Register dst)
template<typename... Rs>
void Pop (Register r, Rs... rs)
void Pop (uint32_t count=1)
void Pop (Register dst)
void Pop (Register src1, Register src2)
void Pop (Register src1, Register src2, Register src3)
void Pop (Register src1, Register src2, Register src3, Register src4)
void Pop (Register src1, Register src2, Register src3, Register src4, Register src5)
void Pop (Register dst)
void Pop (Operand dst)
Static Public Member Functions
static constexpr RegList GetAllocatableRegisters ()
static constexpr DoubleRegList GetAllocatableDoubleRegisters ()
Private Member Functions
constexpr int GetFramePointerOffsetForStackSlot (int index)
void SmiTagInt32AndSetFlags (Register dst, Register src)
Private Attributes
MaglevCodeGenState *const code_gen_state_
TemporaryRegisterScope * scratch_register_scope_ = nullptr
Additional Inherited Members
Detailed Description
Definition at line 96 of file maglev-assembler.h.
Member Typedef Documentation
OffsetTypeFor
template<StoreMode store_mode>
using v8::internal::maglev::MaglevAssembler::OffsetTypeFor = std::conditional_t<store_mode == kField, int, Register>
Definition at line 227 of file maglev-assembler.h.
Member Enumeration Documentation
CharCodeMaskMode
enum v8::internal::maglev::MaglevAssembler::CharCodeMaskMode [strong]
Enumerator
kValueIsInRange
kMustApplyMask
Definition at line 287 of file maglev-assembler.h.
{ kValueIsInRange, kMustApplyMask };
StoreMode
enum v8::internal::maglev::MaglevAssembler::StoreMode
Enumerator
kField
kElement
Definition at line 216 of file maglev-assembler.h.
{ kField, kElement };
ValueCanBeSmi
enum v8::internal::maglev::MaglevAssembler::ValueCanBeSmi
Enumerator
kValueCannotBeSmi
kValueCanBeSmi
Definition at line 218 of file maglev-assembler.h.
{ kValueCannotBeSmi, kValueCanBeSmi };
ValueIsCompressed
enum v8::internal::maglev::MaglevAssembler::ValueIsCompressed
Enumerator
kValueIsDecompressed
kValueIsCompressed
Definition at line 217 of file maglev-assembler.h.
{ kValueIsDecompressed, kValueIsCompressed };
Constructor & Destructor Documentation
MaglevAssembler()
v8::internal::maglev::MaglevAssembler::MaglevAssembler (Isolate * isolate, Zone * zone, MaglevCodeGenState * code_gen_state) [inline]
Definition at line 100 of file maglev-assembler.h.
      : MacroAssembler(isolate, zone, CodeObjectRequired::kNo),
        code_gen_state_(code_gen_state) {}
Member Function Documentation
AddInt32()
void v8::internal::maglev::MaglevAssembler::AddInt32 (Register reg, int amount) [inline]
Definition at line 489 of file maglev-assembler-arm-inl.h.
                                                              {
  add(reg, reg, Operand(amount));
}
References v8::internal::Assembler::add().
Allocate() [1/2]
void v8::internal::maglev::MaglevAssembler::Allocate (RegisterSnapshot register_snapshot, Register result, int size_in_bytes, AllocationType alloc_type = AllocationType::kYoung, AllocationAlignment alignment = kTaggedAligned)
Definition at line 67 of file maglev-assembler-arm.cc.
                                                              {
  AllocateRaw(this, isolate_, register_snapshot, object, size_in_bytes,
              alloc_type, alignment);
}
References v8::internal::maglev::AllocateRaw(), and v8::internal::MacroAssemblerBase::isolate_.
Referenced by AllocateHeapNumber(), and AllocateTwoByteString().
Allocate() [2/2]
void v8::internal::maglev::MaglevAssembler::Allocate (RegisterSnapshot register_snapshot, Register result, Register size_in_bytes, AllocationType alloc_type = AllocationType::kYoung, AllocationAlignment alignment = kTaggedAligned)
Definition at line 75 of file maglev-assembler-arm.cc.
                                                              {
  AllocateRaw(this, isolate_, register_snapshot, object, size_in_bytes,
              alloc_type, alignment);
}
References v8::internal::maglev::AllocateRaw(), and v8::internal::MacroAssemblerBase::isolate_.
AllocateHeapNumber()
void v8::internal::maglev::MaglevAssembler::AllocateHeapNumber (RegisterSnapshot register_snapshot, Register result, DoubleRegister value)
Definition at line 19 of file maglev-assembler.cc.
                                                               {
  // In the case we need to call the runtime, we should spill the value
  // register. Even if it is not live in the next node, otherwise the
  // allocation call might trash it.
  register_snapshot.live_double_registers.set(value);
  Allocate(register_snapshot, result, sizeof(HeapNumber));
  SetMapAsRoot(result, RootIndex::kHeapNumberMap);
  StoreFloat64(FieldMemOperand(result, offsetof(HeapNumber, value_)), value);
}
References Allocate(), v8::internal::FieldMemOperand(), v8::internal::maglev::RegisterSnapshot::live_double_registers, v8::base::internal::result, v8::internal::RegListBase< RegisterT >::set(), SetMapAsRoot(), StoreFloat64(), and v8::internal::value.
AllocateTwoByteString()
void v8::internal::maglev::MaglevAssembler::AllocateTwoByteString (RegisterSnapshot register_snapshot, Register result, int length)
Definition at line 31 of file maglev-assembler.cc.
                                                                         {
  int size = SeqTwoByteString::SizeFor(length);
  Allocate(register_snapshot, result, size);
  StoreTaggedSignedField(result, size - kObjectAlignment, Smi::zero());
  SetMapAsRoot(result, RootIndex::kSeqTwoByteStringMap);
  StoreInt32Field(result, offsetof(Name, raw_hash_field_),
                  Name::kEmptyHashField);
  StoreInt32Field(result, offsetof(String, length_), length);
}
References Allocate(), v8::internal::Name::kEmptyHashField, v8::internal::kObjectAlignment, v8::internal::length, v8::base::internal::result, SetMapAsRoot(), size(), v8::internal::SeqTwoByteString::SizeFor(), StoreInt32Field(), StoreTaggedSignedField(), and v8::internal::Smi::zero().
Referenced by StringFromCharCode().
AndInt32() [1/2]
void v8::internal::maglev::MaglevAssembler::AndInt32 (Register reg, int mask) [inline]
Definition at line 493 of file maglev-assembler-arm-inl.h.
                                                            {
  and_(reg, reg, Operand(mask));
}
References v8::internal::Assembler::and_().
Referenced by JumpIfSeqOneByteStringMap(), and SeqOneByteStringCharCodeAt().
AndInt32() [2/2]
void v8::internal::maglev::MaglevAssembler::AndInt32 (Register reg, Register other) [inline]
Definition at line 501 of file maglev-assembler-arm-inl.h.
                                                                  {
  and_(reg, reg, other);
}
References v8::internal::Assembler::and_().
AssertContextCellState()
void v8::internal::maglev::MaglevAssembler::AssertContextCellState (Register cell, ContextCell::State state, Condition condition = kEqual) [inline]
Definition at line 289 of file maglev-assembler-inl.h.
                                                                         {
  if (!v8_flags.slow_debug_code) return;
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  LoadContextCellState(scratch, cell);
  CompareInt32AndAssert(scratch, static_cast<int>(state), condition,
                        AbortReason::kUnexpectedValue);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), CompareInt32AndAssert(), LoadContextCellState(), and v8::internal::v8_flags.
Referenced by LoadContextCellFloat64Value(), LoadContextCellInt32Value(), and LoadContextCellTaggedValue().
AssertElidedWriteBarrier()
void v8::internal::maglev::MaglevAssembler::AssertElidedWriteBarrier (Register object, Register value, RegisterSnapshot snapshot) [inline]
Definition at line 1109 of file maglev-assembler-inl.h.
                                                                {
#if defined(V8_ENABLE_DEBUG_CODE) && !V8_DISABLE_WRITE_BARRIERS_BOOL
  if (!v8_flags.slow_debug_code) return;
  ZoneLabelRef ok(this);
  Label* deferred_write_barrier_check = MakeDeferredCode(
      [](MaglevAssembler* masm, ZoneLabelRef ok, Register object,
         Register value, RegisterSnapshot snapshot) {
        masm->set_allow_call(true);
        {
          SaveRegisterStateForCall save_register_state(masm, snapshot);
#ifdef V8_COMPRESS_POINTERS
          masm->DecompressTagged(object, object);
          masm->DecompressTagged(value, value);
#endif
          masm->Push(object, value);
          masm->Move(kContextRegister, masm->native_context().object());
          masm->CallRuntime(Runtime::kCheckNoWriteBarrierNeeded, 2);
        }
        masm->set_allow_call(false);
        masm->Jump(*ok);
      },
      ok, object, value, snapshot);
  JumpIfNotSmi(value, deferred_write_barrier_check);
  bind(*ok);
#endif // V8_ENABLE_DEBUG_CODE && !V8_DISABLE_WRITE_BARRIERS
}
References v8::internal::Assembler::bind(), CallRuntime(), v8::internal::MacroAssembler::DecompressTagged(), Jump(), JumpIfNotSmi(), v8::internal::kContextRegister, MakeDeferredCode(), Move(), native_context(), v8::internal::compiler::NativeContextRef::object(), Push(), v8::internal::v8_flags, and v8::internal::value.
AssertObjectType()
void v8::internal::maglev::MaglevAssembler::AssertObjectType (Register heap_object, InstanceType type, AbortReason reason) [inline]
Definition at line 760 of file maglev-assembler-arm-inl.h.
                                                                  {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  AssertNotSmi(heap_object);
  CompareObjectType(heap_object, scratch, scratch, type);
  Assert(kEqual, reason);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::MacroAssembler::Assert(), v8::internal::MacroAssembler::AssertNotSmi(), v8::internal::MacroAssembler::CompareObjectType(), v8::internal::kEqual, and v8::internal::tracing::type.
Referenced by LoadFixedArrayElement(), LoadFixedDoubleArrayElement(), and StoreFixedArrayElementWithWriteBarrier().
AssertObjectTypeInRange()
void v8::internal::maglev::MaglevAssembler::AssertObjectTypeInRange (Register heap_object, InstanceType lower_limit, InstanceType higher_limit, AbortReason reason) [inline]
Definition at line 803 of file maglev-assembler-arm-inl.h.
                                                                         {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  AssertNotSmi(heap_object);
  CompareObjectTypeRange(heap_object, scratch, scratch, scratch, lower_limit,
                         higher_limit);
  Assert(kUnsignedLessThanEqual, reason);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::MacroAssembler::Assert(), v8::internal::MacroAssembler::AssertNotSmi(), v8::internal::MacroAssembler::CompareObjectTypeRange(), and v8::internal::kUnsignedLessThanEqual.
Referenced by StringCharCodeOrCodePointAt(), and StringLength().
AssertStackSizeCorrect()
void v8::internal::maglev::MaglevAssembler::AssertStackSizeCorrect () [inline]
Definition at line 1288 of file maglev-assembler-arm-inl.h.
                                                    {
  if (v8_flags.slow_debug_code) {
    TemporaryRegisterScope temps(this);
    Register scratch = temps.AcquireScratch();
    add(scratch, sp,
        Operand(code_gen_state()->stack_slots() * kSystemPointerSize +
                StandardFrameConstants::kFixedFrameSizeFromFp));
    cmp(scratch, fp);
    Assert(eq, AbortReason::kStackAccessBelowStackPointer);
  }
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::add(), v8::internal::MacroAssembler::Assert(), v8::internal::Assembler::cmp(), code_gen_state(), v8::internal::eq, v8::internal::StandardFrameConstants::kFixedFrameSizeFromFp, v8::internal::kSystemPointerSize, and v8::internal::v8_flags.
BindBlock()
void v8::internal::maglev::MaglevAssembler::BindBlock (BasicBlock * block) [inline]
Definition at line 215 of file maglev-assembler-arm-inl.h.
                                                        {
  bind(block->label());
}
References v8::internal::Assembler::bind(), and v8::internal::maglev::BasicBlock::label().
BindJumpTarget()
void v8::internal::maglev::MaglevAssembler::BindJumpTarget (Label * label) [inline]
Definition at line 213 of file maglev-assembler-arm-inl.h.
{ bind(label); }
References v8::internal::Assembler::bind().
Referenced by v8::internal::maglev::MaglevCodeGenerator::EmitCode().
Branch() [1/2]
void v8::internal::maglev::MaglevAssembler::Branch (Condition condition, BasicBlock * if_true, BasicBlock * if_false, BasicBlock * next_block) [inline]
Definition at line 395 of file maglev-assembler-inl.h.
                                                            {
  Branch(condition, if_true->label(), Label::kFar, if_true == next_block,
         if_false->label(), Label::kFar, if_false == next_block);
}
References v8::internal::Label::kFar, and v8::internal::maglev::BasicBlock::label().
Referenced by BranchOnObjectType(), BranchOnObjectTypeInRange(), CompareFloat64AndBranch(), CompareInt32AndBranch(), CompareIntPtrAndBranch(), and TestTypeOf().
Branch() [2/2]
void v8::internal::maglev::MaglevAssembler::Branch (Condition condition, Label * if_true, Label::Distance true_distance, bool fallthrough_when_true, Label * if_false, Label::Distance false_distance, bool fallthrough_when_false) [inline]
Definition at line 402 of file maglev-assembler-inl.h.
                                                                 {
  if (fallthrough_when_false) {
    if (fallthrough_when_true) {
      // If both paths are a fallthrough, do nothing.
      DCHECK_EQ(if_true, if_false);
      return;
    }
    // Jump over the false block if true, otherwise fall through into it.
    JumpIf(condition, if_true, true_distance);
  } else {
    // Jump to the false block if true.
    JumpIf(NegateCondition(condition), if_false, false_distance);
    // Jump to the true block if it's not the next block.
    if (!fallthrough_when_true) {
      Jump(if_true, true_distance);
    }
  }
}
References DCHECK_EQ, Jump(), JumpIf(), and v8::internal::NegateCondition().
BranchOnObjectType()
void v8::internal::maglev::MaglevAssembler::BranchOnObjectType (Register heap_object, InstanceType type, Label * if_true, Label::Distance true_distance, bool fallthrough_when_true, Label * if_false, Label::Distance false_distance, bool fallthrough_when_false) [inline]
Definition at line 770 of file maglev-assembler-arm-inl.h.
                                                               {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  CompareObjectType(heap_object, scratch, scratch, type);
  Branch(kEqual, if_true, true_distance, fallthrough_when_true, if_false,
         false_distance, fallthrough_when_false);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), Branch(), v8::internal::MacroAssembler::CompareObjectType(), v8::internal::kEqual, and v8::internal::tracing::type.
Referenced by TestTypeOf().
BranchOnObjectTypeInRange()
void v8::internal::maglev::MaglevAssembler::BranchOnObjectTypeInRange (Register heap_object, InstanceType lower_limit, InstanceType higher_limit, Label * if_true, Label::Distance true_distance, bool fallthrough_when_true, Label * if_false, Label::Distance false_distance, bool fallthrough_when_false) [inline]
Definition at line 815 of file maglev-assembler-arm-inl.h.
                                 {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  CompareObjectTypeRange(heap_object, scratch, scratch, scratch, lower_limit,
                         higher_limit);
  Branch(kUnsignedLessThanEqual, if_true, true_distance, fallthrough_when_true,
         if_false, false_distance, fallthrough_when_false);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), Branch(), v8::internal::MacroAssembler::CompareObjectTypeRange(), and v8::internal::kUnsignedLessThanEqual.
Referenced by CheckJSAnyIsStringAndBranch().
BuildTypedArrayDataPointer()
void v8::internal::maglev::MaglevAssembler::BuildTypedArrayDataPointer (Register data_pointer, Register object) [inline]
Definition at line 301 of file maglev-assembler-arm-inl.h.
                                                                         {
  DCHECK_NE(data_pointer, object);
  ldr(data_pointer,
      FieldMemOperand(object, JSTypedArray::kExternalPointerOffset));
  if (JSTypedArray::kMaxSizeInHeap == 0) return;
  TemporaryRegisterScope temps(this);
  Register base = temps.AcquireScratch();
  ldr(base, FieldMemOperand(object, JSTypedArray::kBasePointerOffset));
  add(data_pointer, data_pointer, base);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::add(), DCHECK_NE, v8::internal::FieldMemOperand(), v8::internal::JSTypedArray::kMaxSizeInHeap, and v8::internal::Assembler::ldr().
Call()
void v8::internal::maglev::MaglevAssembler::Call (Label * target) [inline]
Definition at line 522 of file maglev-assembler-arm-inl.h.
{ bl(target); }
References v8::internal::Assembler::bl().
CallBuiltin() [1/2]
template<Builtin kBuiltin, typename... Args>
void v8::internal::maglev::MaglevAssembler::CallBuiltin (Args &&... args) [inline]
Definition at line 779 of file maglev-assembler-inl.h.
                                                       {
  ASM_CODE_COMMENT(this);
  detail::MoveArgumentsForBuiltin<kBuiltin>(this, std::forward<Args>(args)...);
  CallBuiltin(kBuiltin);
}
References v8::base::args, ASM_CODE_COMMENT, and CallBuiltin().
CallBuiltin() [2/2]
void v8::internal::maglev::MaglevAssembler::CallBuiltin (Builtin builtin) [inline]
Definition at line 752 of file maglev-assembler-inl.h.
                                                        {
  // Special case allowing calls to DoubleToI, which takes care to preserve all
  // registers and therefore doesn't require special spill handling.
  DCHECK(allow_call() || builtin == Builtin::kDoubleToI);
  DCHECK_IMPLIES(!allow_allocate(), builtin == Builtin::kDoubleToI ||
                                        !BuiltinCanAllocate(builtin));
  // Temporaries have to be reset before calling CallBuiltin, in case it uses
  // temporaries that alias register parameters.
  TemporaryRegisterScope reset_temps(this);
  reset_temps.ResetToDefault();
  // Make sure that none of the register parameters alias the default
  // temporaries.
#ifdef DEBUG
  CallInterfaceDescriptor descriptor =
      Builtins::CallInterfaceDescriptorFor(builtin);
  for (int i = 0; i < descriptor.GetRegisterParameterCount(); ++i) {
    DCHECK(!reset_temps.Available().has(descriptor.GetRegisterParameter(i)));
  }
#endif
  MacroAssembler::CallBuiltin(builtin);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Available(), v8::internal::MacroAssemblerBase::builtin(), v8::internal::BuiltinCanAllocate(), v8::internal::MacroAssembler::CallBuiltin(), v8::internal::Builtins::CallInterfaceDescriptorFor(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::CallInterfaceDescriptor::GetRegisterParameter(), v8::internal::CallInterfaceDescriptor::GetRegisterParameterCount(), v8::internal::RegListBase< RegisterT >::has(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::ResetToDefault().
Referenced by v8::internal::maglev::AllocateSlow(), CallBuiltin(), and TruncateDoubleToInt32().
CallRuntime() [1/2]
void v8::internal::maglev::MaglevAssembler::CallRuntime (Runtime::FunctionId fid) [inline]
Definition at line 785 of file maglev-assembler-inl.h.
                                                              {
  DCHECK(allow_call());
  // Temporaries have to be reset before calling CallRuntime, in case it uses
  // temporaries that alias register parameters.
  TemporaryRegisterScope reset_temps(this);
  reset_temps.ResetToDefault();
  MacroAssembler::CallRuntime(fid);
}
References v8::internal::MacroAssembler::CallRuntime(), v8::internal::DCHECK(), and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::ResetToDefault().
Referenced by AssertElidedWriteBarrier(), StringCharCodeOrCodePointAt(), TryMigrateInstance(), and TryMigrateInstanceAndMarkMapAsMigrationTarget().
CallRuntime() [2/2]
void v8::internal::maglev::MaglevAssembler::CallRuntime (Runtime::FunctionId fid, int num_args) [inline]
Definition at line 794 of file maglev-assembler-inl.h.
                                                       {
  DCHECK(allow_call());
  // Temporaries have to be reset before calling CallRuntime, in case it uses
  // temporaries that alias register parameters.
  TemporaryRegisterScope reset_temps(this);
  reset_temps.ResetToDefault();
  MacroAssembler::CallRuntime(fid, num_args);
}
References v8::internal::MacroAssembler::CallRuntime(), v8::internal::DCHECK(), and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::ResetToDefault().
CallSelf()
void v8::internal::maglev::MaglevAssembler::CallSelf () [inline]
Definition at line 886 of file maglev-assembler-arm-inl.h.
                                      {
  DCHECK(code_gen_state()->entry_label()->is_bound());
  bl(code_gen_state()->entry_label());
}
References v8::internal::Assembler::bl(), code_gen_state(), and v8::internal::DCHECK().
CheckAndEmitDeferredIndirectPointerWriteBarrier()
void v8::internal::maglev::MaglevAssembler::CheckAndEmitDeferredIndirectPointerWriteBarrier (Register object, int offset, Register value, RegisterSnapshot register_snapshot, IndirectPointerTag tag)
CheckAndEmitDeferredWriteBarrier()
template<MaglevAssembler::StoreMode store_mode>
void v8::internal::maglev::MaglevAssembler::CheckAndEmitDeferredWriteBarrier (Register object, OffsetTypeFor< store_mode > offset, Register value, RegisterSnapshot register_snapshot, ValueIsCompressed value_is_compressed, ValueCanBeSmi value_can_be_smi)
Definition at line 486 of file maglev-assembler.cc.
                                    {
  ZoneLabelRef done(this);
  Label* deferred_write_barrier = MakeDeferredCode(
      [](MaglevAssembler* masm, ZoneLabelRef done, Register object,
         OffsetTypeFor<store_mode> offset, Register value,
         RegisterSnapshot register_snapshot, ValueIsCompressed value_type) {
        ASM_CODE_COMMENT_STRING(masm, "Write barrier slow path");
        if (PointerCompressionIsEnabled() && value_type == kValueIsCompressed) {
          __ DecompressTagged(value, value);
        }
        {
          // Use the value as the scratch register if possible, since
          // CheckPageFlag emits slightly better code when value == scratch.
          MaglevAssembler::TemporaryRegisterScope temp(masm);
          Register scratch = temp.AcquireScratch();
          if (value != object && !register_snapshot.live_registers.has(value)) {
            scratch = value;
          }
          __ CheckPageFlag(value, scratch,
                           MemoryChunk::kPointersToHereAreInterestingMask,
                           kEqual, *done);
        }
        Register stub_object_reg = WriteBarrierDescriptor::ObjectRegister();
        Register slot_reg = WriteBarrierDescriptor::SlotAddressRegister();
        RegList saved;
        // The RecordWrite stub promises to restore all allocatable registers,
        // but not necessarily non-allocatable registers like temporaries. Make
        // sure we're not trying to keep any non-allocatable registers alive.
        CHECK((register_snapshot.live_registers - kAllocatableGeneralRegisters)
                  .is_empty());
        if (object != stub_object_reg &&
            register_snapshot.live_registers.has(stub_object_reg)) {
          saved.set(stub_object_reg);
        }
        if (register_snapshot.live_registers.has(slot_reg)) {
          saved.set(slot_reg);
        }
        __ PushAll(saved);
        if (object != stub_object_reg) {
          __ Move(stub_object_reg, object);
          object = stub_object_reg;
        }
        if constexpr (store_mode == kElement) {
          __ SetSlotAddressForFixedArrayElement(slot_reg, object, offset);
        } else {
          static_assert(store_mode == kField);
          __ SetSlotAddressForTaggedField(slot_reg, object, offset);
        }
        SaveFPRegsMode const save_fp_mode =
            !register_snapshot.live_double_registers.is_empty()
                ? SaveFPRegsMode::kSave
                : SaveFPRegsMode::kIgnore;
        __ CallRecordWriteStub(object, slot_reg, save_fp_mode);
        __ PopAll(saved);
        __ Jump(*done);
      },
      done, object, offset, value, register_snapshot, value_is_compressed);
  if (!value_can_be_smi) {
    AssertNotSmi(value);
  }
#if V8_STATIC_ROOTS_BOOL
  // Quick check for Read-only and small Smi values.
  static_assert(StaticReadOnlyRoot::kLastAllocatedRoot < kRegularPageSize);
  JumpIfUnsignedLessThan(value, kRegularPageSize, *done);
#endif // V8_STATIC_ROOTS_BOOL
  if (value_can_be_smi) {
    JumpIfSmi(value, *done);
  }
  static_assert(WriteBarrier::kUninterestingPagesCanBeSkipped);
  MaglevAssembler::TemporaryRegisterScope temp(this);
  Register scratch = temp.AcquireScratch();
  CheckPageFlag(object, scratch,
                MemoryChunk::kPointersFromHereAreInterestingMask, kNotEqual,
                deferred_write_barrier);
  bind(*done);
}
References __, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), ASM_CODE_COMMENT_STRING, v8::internal::MacroAssembler::AssertNotSmi(), v8::internal::Assembler::bind(), v8::internal::MacroAssembler::CallRecordWriteStub(), CHECK, v8::internal::MacroAssembler::CheckPageFlag(), v8::internal::MacroAssembler::DecompressTagged(), v8::internal::RegListBase< RegisterT >::has(), v8::internal::RegListBase< RegisterT >::is_empty(), Jump(), JumpIfSmi(), v8::internal::MacroAssembler::JumpIfUnsignedLessThan(), v8::internal::kAllocatableGeneralRegisters, kElement, v8::internal::kEqual, kField, v8::internal::kIgnore, v8::internal::kNotEqual, v8::internal::MemoryChunk::kPointersFromHereAreInterestingMask, v8::internal::MemoryChunk::kPointersToHereAreInterestingMask, kRegularPageSize, v8::internal::kSave, v8::internal::WriteBarrier::kUninterestingPagesCanBeSkipped, kValueIsCompressed, v8::internal::maglev::RegisterSnapshot::live_double_registers, v8::internal::maglev::RegisterSnapshot::live_registers, MakeDeferredCode(), Move(), v8::internal::WriteBarrierDescriptor::ObjectRegister(), v8::internal::PointerCompressionIsEnabled(), v8::internal::MacroAssembler::PopAll(), v8::internal::MacroAssembler::PushAll(), v8::internal::RegListBase< RegisterT >::set(), SetSlotAddressForFixedArrayElement(), SetSlotAddressForTaggedField(), v8::internal::WriteBarrierDescriptor::SlotAddressRegister(), v8::internal::value, and v8::internal::wasm::value_type().
CheckInt32IsSmi()
void v8::internal::maglev::MaglevAssembler::CheckInt32IsSmi (Register obj, Label * fail, Register scratch = Register::no_reg()) [inline]
Definition at line 224 of file maglev-assembler-arm-inl.h.
                                                               {
  static_assert(!SmiValuesAre32Bits());
  TemporaryRegisterScope temps(this);
  if (scratch == Register::no_reg()) {
    scratch = temps.AcquireScratch();
  }
  add(scratch, obj, obj, SetCC);
  JumpIf(kOverflow, fail);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::add(), JumpIf(), v8::internal::kOverflow, v8::internal::Register::no_reg(), v8::internal::SetCC, and v8::internal::SmiValuesAre32Bits().
CheckIntPtrIsSmi()
void v8::internal::maglev::MaglevAssembler::CheckIntPtrIsSmi (Register obj, Label * fail, Label::Distance distance = Label::kFar) [inline]
Definition at line 913 of file maglev-assembler-inl.h.
                                                                      {
  // TODO(388844115): Optimize this per platform.
  int32_t kSmiMaxValueInt32 = static_cast<int32_t>(Smi::kMaxValue);
  int32_t kSmiMinValueInt32 = static_cast<int32_t>(Smi::kMinValue);
  CompareIntPtrAndJumpIf(obj, kSmiMaxValueInt32, kGreaterThan, fail, distance);
  CompareIntPtrAndJumpIf(obj, kSmiMinValueInt32, kLessThan, fail, distance);
}
References CompareIntPtrAndJumpIf(), v8::internal::kGreaterThan, v8::internal::kLessThan, v8::internal::Smi::kMaxValue, and v8::internal::Smi::kMinValue.
Referenced by SmiTagIntPtrAndJumpIfFail().
CheckJSAnyIsStringAndBranch()
void v8::internal::maglev::MaglevAssembler::CheckJSAnyIsStringAndBranch (Register heap_object, Label * if_true, Label::Distance true_distance, bool fallthrough_when_true, Label * if_false, Label::Distance false_distance, bool fallthrough_when_false) [inline]
Definition at line 1039 of file maglev-assembler-inl.h.
                                 {
  BranchOnObjectTypeInRange(heap_object, FIRST_STRING_TYPE, LAST_STRING_TYPE,
                            if_true, true_distance, fallthrough_when_true,
                            if_false, false_distance, fallthrough_when_false);
}
References BranchOnObjectTypeInRange(), and v8::internal::LAST_STRING_TYPE.
Referenced by TestTypeOf().
code_gen_state()
MaglevCodeGenState* v8::internal::maglev::MaglevAssembler::code_gen_state () const [inline]
Definition at line 826 of file maglev-assembler.h.
{ return code_gen_state_; }
Referenced by AssertStackSizeCorrect(), CallSelf(), DefineExceptionHandlerPoint(), DefineLazyDeoptPoint(), v8::internal::maglev::SaveRegisterStateForCall::DefineSafepointWithLazyDeopt(), GetDeoptLabel(), MakeDeferredCode(), and Prologue().
CompareByteAndJumpIf()
void v8::internal::maglev::MaglevAssembler::CompareByteAndJumpIf (MemOperand left, int8_t right, Condition cond, Register scratch, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1127 of file maglev-assembler-arm-inl.h.
                                                                          {
  LoadByte(scratch, left);
  Cmp(scratch, right);
  JumpIf(cond, target, distance);
}
References v8::internal::MacroAssembler::Cmp(), JumpIf(), and LoadByte().
CompareDoubleAndJumpIfZeroOrNaN() [1/2]
void v8::internal::maglev::MaglevAssembler::CompareDoubleAndJumpIfZeroOrNaN (DoubleRegister reg, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1164 of file maglev-assembler-arm-inl.h.
                                                               {
  VFPCompareAndSetFlags(reg, 0.0);
  JumpIf(eq, target);
  JumpIf(vs, target); // NaN check
}
References v8::internal::eq, JumpIf(), v8::internal::MacroAssembler::VFPCompareAndSetFlags(), and v8::internal::AssemblerRISCVV::vs().
Referenced by CompareDoubleAndJumpIfZeroOrNaN(), and ToBoolean().
CompareDoubleAndJumpIfZeroOrNaN() [2/2]
void v8::internal::maglev::MaglevAssembler::CompareDoubleAndJumpIfZeroOrNaN (MemOperand operand, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1171 of file maglev-assembler-arm-inl.h.
                                                               {
  TemporaryRegisterScope temps(this);
  DoubleRegister value_double = temps.AcquireScratchDouble();
  vldr(value_double, operand);
  CompareDoubleAndJumpIfZeroOrNaN(value_double, target, distance);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratchDouble(), CompareDoubleAndJumpIfZeroOrNaN(), and v8::internal::Assembler::vldr().
CompareFloat64AndBranch()
void v8::internal::maglev::MaglevAssembler::CompareFloat64AndBranch (DoubleRegister src1, DoubleRegister src2, Condition cond, BasicBlock * if_true, BasicBlock * if_false, BasicBlock * next_block, BasicBlock * nan_failed) [inline]
Definition at line 872 of file maglev-assembler-arm-inl.h.
                            {
  VFPCompareAndSetFlags(src1, src2);
  JumpIf(ConditionForNaN(), nan_failed->label());
  Branch(cond, if_true, if_false, next_block);
}
References Branch(), v8::internal::maglev::ConditionForNaN(), JumpIf(), v8::internal::maglev::BasicBlock::label(), and v8::internal::MacroAssembler::VFPCompareAndSetFlags().
CompareFloat64AndJumpIf()
void v8::internal::maglev::MaglevAssembler::CompareFloat64AndJumpIf (DoubleRegister src1, DoubleRegister src2, Condition cond, Label * target, Label * nan_failed, Label::Distance distance = Label::kFar) [inline]
Definition at line 864 of file maglev-assembler-arm-inl.h.
                                               {
  VFPCompareAndSetFlags(src1, src2);
  JumpIf(ConditionForNaN(), nan_failed);
  JumpIf(cond, target, distance);
}
References v8::internal::maglev::ConditionForNaN(), JumpIf(), and v8::internal::MacroAssembler::VFPCompareAndSetFlags().
CompareInstanceType()
void v8::internal::maglev::MaglevAssembler::CompareInstanceType (Register map, InstanceType instance_type) [inline]
Definition at line 847 of file maglev-assembler-arm-inl.h.
                                                                             {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  MacroAssembler::CompareInstanceType(map, scratch, instance_type);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), and v8::internal::MacroAssembler::CompareInstanceType().
Referenced by CompareInstanceTypeAndJumpIf().
CompareInstanceTypeAndJumpIf()
void v8::internal::maglev::MaglevAssembler::CompareInstanceTypeAndJumpIf (Register map, InstanceType type, Condition cond, Label * target, Label::Distance distance) [inline]
Definition at line 316 of file maglev-assembler-inl.h.
                            {
  CompareInstanceType(map, type);
  JumpIf(cond, target, distance);
}
References CompareInstanceType(), JumpIf(), and v8::internal::tracing::type.
Referenced by JumpIfStringMap(), and TestTypeOf().
CompareInstanceTypeRange() [1/2]
void v8::internal::maglev::MaglevAssembler::CompareInstanceTypeRange (Register map, InstanceType lower_limit, InstanceType higher_limit) [inline]
Referenced by CompareInstanceTypeRangeAndEagerDeoptIf(), JumpIfSeqOneByteStringMap(), and SeqOneByteStringCharCodeAt().
CompareInstanceTypeRange() [2/2]
Condition v8::internal::maglev::MaglevAssembler::CompareInstanceTypeRange (Register map, Register instance_type_out, InstanceType lower_limit, InstanceType higher_limit) [inline]
Definition at line 854 of file maglev-assembler-arm-inl.h.
                               {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  MacroAssembler::CompareInstanceTypeRange(map, instance_type_out, scratch,
                                           lower_limit, higher_limit);
  return kUnsignedLessThanEqual;
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::MacroAssembler::CompareInstanceTypeRange(), and v8::internal::kUnsignedLessThanEqual.
CompareInstanceTypeRangeAndEagerDeoptIf()
template<typename NodeT >
void v8::internal::maglev::MaglevAssembler::CompareInstanceTypeRangeAndEagerDeoptIf (Register map, Register instance_type_out, InstanceType lower_limit, InstanceType higher_limit, Condition cond, DeoptimizeReason reason, NodeT * node) [inline]
Definition at line 324 of file maglev-assembler-inl.h.
                 {
  CompareInstanceTypeRange(map, instance_type_out, lower_limit, higher_limit);
  EmitEagerDeoptIf(cond, reason, node);
}
References CompareInstanceTypeRange(), and EmitEagerDeoptIf().
CompareInt32AndAssert() [1/2]
void v8::internal::maglev::MaglevAssembler::CompareInt32AndAssert (Register r1, int32_t value, Condition cond, AbortReason reason) [inline]
Definition at line 1077 of file maglev-assembler-arm-inl.h.
                                                                       {
  cmp(r1, Operand(value));
  Assert(cond, reason);
}
References v8::internal::MacroAssembler::Assert(), v8::internal::Assembler::cmp(), and v8::internal::value.
CompareInt32AndAssert() [2/2]
void v8::internal::maglev::MaglevAssembler::CompareInt32AndAssert (Register r1, Register r2, Condition cond, AbortReason reason) [inline]
Definition at line 1071 of file maglev-assembler-arm-inl.h.
                                                                       {
  cmp(r1, r2);
  Assert(cond, reason);
}
References v8::internal::MacroAssembler::Assert(), and v8::internal::Assembler::cmp().
Referenced by AssertContextCellState(), LoadFixedArrayElement(), LoadFixedDoubleArrayElement(), SeqOneByteStringCharCodeAt(), StoreFixedArrayElementWithWriteBarrier(), and UncheckedSmiTagUint32().
CompareInt32AndBranch() [1/4]
void v8::internal::maglev::MaglevAssembler::CompareInt32AndBranch (Register r1, int32_t value, Condition cond, BasicBlock * if_true, BasicBlock * if_false, BasicBlock * next_block) [inline]
Definition at line 365 of file maglev-assembler-inl.h.
                                                                           {
  CompareInt32AndBranch(r1, value, cond, if_true->label(), Label::kFar,
                        if_true == next_block, if_false->label(), Label::kFar,
                        if_false == next_block);
}
References v8::internal::Label::kFar, v8::internal::maglev::BasicBlock::label(), and v8::internal::value.
Referenced by CompareInt32AndBranch().
CompareInt32AndBranch() [2/4]
void v8::internal::maglev::MaglevAssembler::CompareInt32AndBranch (Register r1, int32_t value, Condition cond, Label * if_true, Label::Distance true_distance, bool fallthrough_when_true, Label * if_false, Label::Distance false_distance, bool fallthrough_when_false) [inline]
Definition at line 1084 of file maglev-assembler-arm-inl.h.
                                                               {
  cmp(r1, Operand(value));
  Branch(cond, if_true, true_distance, fallthrough_when_true, if_false,
         false_distance, fallthrough_when_false);
}
References Branch(), v8::internal::Assembler::cmp(), and v8::internal::value.
CompareInt32AndBranch() [3/4]
void v8::internal::maglev::MaglevAssembler::CompareInt32AndBranch (Register r1, Register r2, Condition cond, BasicBlock * if_true, BasicBlock * if_false, BasicBlock * next_block) [inline]
Definition at line 375 of file maglev-assembler-inl.h.
                                                                           {
  CompareInt32AndBranch(r1, r2, cond, if_true->label(), Label::kFar,
                        if_true == next_block, if_false->label(), Label::kFar,
                        if_false == next_block);
}
References CompareInt32AndBranch(), v8::internal::Label::kFar, and v8::internal::maglev::BasicBlock::label().
CompareInt32AndBranch() [4/4]
void v8::internal::maglev::MaglevAssembler::CompareInt32AndBranch (Register r1, Register r2, Condition cond, Label * if_true, Label::Distance true_distance, bool fallthrough_when_true, Label * if_false, Label::Distance false_distance, bool fallthrough_when_false) [inline]
Definition at line 1093 of file maglev-assembler-arm-inl.h.
                                                               {
  cmp(r1, r2);
  Branch(cond, if_true, true_distance, fallthrough_when_true, if_false,
         false_distance, fallthrough_when_false);
}
References Branch(), and v8::internal::Assembler::cmp().
CompareInt32AndJumpIf() [1/2]
void v8::internal::maglev::MaglevAssembler::CompareInt32AndJumpIf (Register r1, int32_t value, Condition cond, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1063 of file maglev-assembler-arm-inl.h.
                                                                           {
  cmp(r1, Operand(value));
  JumpIf(cond, target);
}
References v8::internal::Assembler::cmp(), JumpIf(), and v8::internal::value.
CompareInt32AndJumpIf() [2/2]
void v8::internal::maglev::MaglevAssembler::CompareInt32AndJumpIf (Register r1, Register r2, Condition cond, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1039 of file maglev-assembler-arm-inl.h.
                                                                           {
  cmp(r1, r2);
  JumpIf(cond, target);
}
References v8::internal::Assembler::cmp(), and JumpIf().
Referenced by JumpIfHoleNan(), JumpIfNotHoleNan(), JumpIfSeqOneByteStringMap(), JumpIfStringMap(), SmiTagUint32AndJumpIfFail(), and ToBoolean().
CompareIntPtrAndBranch() [1/2]
void v8::internal::maglev::MaglevAssembler::CompareIntPtrAndBranch (Register r1, int32_t value, Condition cond, BasicBlock * if_true, BasicBlock * if_false, BasicBlock * next_block) [inline]
Definition at line 385 of file maglev-assembler-inl.h.
                                                                            {
  CompareIntPtrAndBranch(r1, value, cond, if_true->label(), Label::kFar,
                         if_true == next_block, if_false->label(), Label::kFar,
                         if_false == next_block);
}
References v8::internal::Label::kFar, v8::internal::maglev::BasicBlock::label(), and v8::internal::value.
CompareIntPtrAndBranch() [2/2]
void v8::internal::maglev::MaglevAssembler::CompareIntPtrAndBranch (Register r1, int32_t value, Condition cond, Label * if_true, Label::Distance true_distance, bool fallthrough_when_true, Label * if_false, Label::Distance false_distance, bool fallthrough_when_false) [inline]
Definition at line 1102 of file maglev-assembler-arm-inl.h.
                                                               {
  cmp(r1, Operand(value));
  Branch(cond, if_true, true_distance, fallthrough_when_true, if_false,
         false_distance, fallthrough_when_false);
}
References Branch(), v8::internal::Assembler::cmp(), and v8::internal::value.
CompareIntPtrAndJumpIf() [1/2]
void v8::internal::maglev::MaglevAssembler::CompareIntPtrAndJumpIf (Register r1, int32_t value, Condition cond, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1055 of file maglev-assembler-arm-inl.h.
                                                                            {
  cmp(r1, Operand(value));
  JumpIf(cond, target);
}
References v8::internal::Assembler::cmp(), JumpIf(), and v8::internal::value.
CompareIntPtrAndJumpIf() [2/2]
void v8::internal::maglev::MaglevAssembler::CompareIntPtrAndJumpIf (Register r1, Register r2, Condition cond, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1047 of file maglev-assembler-arm-inl.h.
                                                                            {
  cmp(r1, r2);
  JumpIf(cond, target);
}
References v8::internal::Assembler::cmp(), and JumpIf().
Referenced by CheckIntPtrIsSmi().
CompareMapWithRoot()
void v8::internal::maglev::MaglevAssembler::CompareMapWithRoot (Register object, RootIndex index, Register scratch) [inline]
Definition at line 840 of file maglev-assembler-arm-inl.h.
                                                                  {
  LoadMap(scratch, object);
  CompareRoot(scratch, index);
}
References v8::internal::MacroAssembler::CompareRoot(), v8::internal::index, and v8::internal::MacroAssembler::LoadMap().
Referenced by CompareMapWithRootAndEmitEagerDeoptIf(), EnsureWritableFastElements(), and TestTypeOf().
CompareMapWithRootAndEmitEagerDeoptIf()
template<typename NodeT >
void v8::internal::maglev::MaglevAssembler::CompareMapWithRootAndEmitEagerDeoptIf (Register reg, RootIndex index, Register scratch, Condition cond, DeoptimizeReason reason, NodeT * node) [inline]
Definition at line 341 of file maglev-assembler-inl.h.
                                          {
  CompareMapWithRoot(reg, index, scratch);
  EmitEagerDeoptIf(cond, reason, node);
}
References CompareMapWithRoot(), EmitEagerDeoptIf(), and v8::internal::index.
CompareRootAndEmitEagerDeoptIf()
template<typename NodeT >
void v8::internal::maglev::MaglevAssembler::CompareRootAndEmitEagerDeoptIf (Register reg, RootIndex index, Condition cond, DeoptimizeReason reason, NodeT * node) [inline]
Definition at line 333 of file maglev-assembler-inl.h.
                 {
  CompareRoot(reg, index);
  EmitEagerDeoptIf(cond, reason, node);
}
References v8::internal::MacroAssembler::CompareRoot(), EmitEagerDeoptIf(), and v8::internal::index.
CompareSmiAndAssert()
void v8::internal::maglev::MaglevAssembler::CompareSmiAndAssert (Register r1, Tagged< Smi > value, Condition cond, AbortReason reason) [inline]
Definition at line 1118 of file maglev-assembler-arm-inl.h.
                                                                     {
  if (!v8_flags.debug_code) return;
  AssertSmi(r1);
  cmp(r1, Operand(value));
  Assert(cond, reason);
}
References v8::internal::MacroAssembler::Assert(), v8::internal::MacroAssembler::AssertSmi(), v8::internal::Assembler::cmp(), v8::internal::v8_flags, and v8::internal::value.
CompareSmiAndJumpIf()
void v8::internal::maglev::MaglevAssembler::CompareSmiAndJumpIf (Register r1, Tagged< Smi > value, Condition cond, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1111 of file maglev-assembler-arm-inl.h.
                                                                         {
  cmp(r1, Operand(value));
  JumpIf(cond, target);
}
References v8::internal::Assembler::cmp(), JumpIf(), and v8::internal::value.
Referenced by ToBoolean().
CompareTaggedAndJumpIf() [1/3]
void v8::internal::maglev::MaglevAssembler::CompareTaggedAndJumpIf (Register reg, Handle< HeapObject > obj, Condition cond, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1146 of file maglev-assembler-arm-inl.h.
                                                                            {
  cmp(reg, Operand(obj));
  b(cond, target);
}
References v8::internal::Assembler::b(), and v8::internal::Assembler::cmp().
CompareTaggedAndJumpIf() [2/3]
void v8::internal::maglev::MaglevAssembler::CompareTaggedAndJumpIf (Register reg, Tagged< Smi > smi, Condition cond, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1137 of file maglev-assembler-arm-inl.h.
                                                                            {
  cmp(r1, Operand(value));
  JumpIf(cond, target);
}
References v8::internal::Assembler::cmp(), JumpIf(), and v8::internal::value.
Referenced by TryMigrateInstance().
CompareTaggedAndJumpIf() [3/3]
void v8::internal::maglev::MaglevAssembler::CompareTaggedAndJumpIf (Register src1, Register src2, Condition cond, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1155 of file maglev-assembler-arm-inl.h.
                                                                            {
  CmpTagged(src1, src2);
  JumpIf(cond, target, distance);
}
References v8::internal::MacroAssembler::CmpTagged(), and JumpIf().
CompareTaggedRootAndEmitEagerDeoptIf()
template<typename NodeT >
void v8::internal::maglev::MaglevAssembler::CompareTaggedRootAndEmitEagerDeoptIf (Register reg, RootIndex index, Condition cond, DeoptimizeReason reason, NodeT * node) [inline]
Definition at line 349 of file maglev-assembler-inl.h.
                 {
  CompareTaggedRoot(reg, index);
  EmitEagerDeoptIf(cond, reason, node);
}
References v8::internal::MacroAssembler::CompareTaggedRoot(), EmitEagerDeoptIf(), and v8::internal::index.
CompareUInt32AndEmitEagerDeoptIf()
template<typename NodeT >
void v8::internal::maglev::MaglevAssembler::CompareUInt32AndEmitEagerDeoptIf (Register reg, int imm, Condition cond, DeoptimizeReason reason, NodeT * node) [inline]
Definition at line 357 of file maglev-assembler-inl.h.
                 {
  Cmp(reg, imm);
  EmitEagerDeoptIf(cond, reason, node);
}
References v8::internal::MacroAssembler::Cmp(), and EmitEagerDeoptIf().
compilation_info()
MaglevCompilationInfo* v8::internal::maglev::MaglevAssembler::compilation_info () const [inline]
Definition at line 830 of file maglev-assembler.h.
                                                  {
    return code_gen_state()->compilation_info();
  }
Referenced by v8::internal::maglev::MaglevCodeGenerator::EmitDeopts(), JumpIfHoleNan(), MakeDeferredCode(), Prologue(), and ToBoolean().
CountLeadingZerosInt32()
void v8::internal::maglev::MaglevAssembler::CountLeadingZerosInt32 (Register dst, Register src)
Definition at line 494 of file maglev-assembler-arm.cc.
                                                                       {
  clz(dst, src);
}
References v8::internal::Assembler::clz().
DataViewElementOperand()
MemOperand v8::internal::maglev::MaglevAssembler::DataViewElementOperand (Register data_pointer, Register index) [inline]
Definition at line 320 of file maglev-assembler-arm-inl.h.
                                                                          {
  return MemOperand(data_pointer, index);
}
References v8::internal::index.
DecrementInt32()
void v8::internal::maglev::MaglevAssembler::DecrementInt32 (Register reg) [inline]
Definition at line 485 of file maglev-assembler-arm-inl.h.
                                                        {
  sub(reg, reg, Operand(1));
}
References v8::internal::Assembler::sub().
DefineExceptionHandlerAndLazyDeoptPoint()
void v8::internal::maglev::MaglevAssembler::DefineExceptionHandlerAndLazyDeoptPoint (NodeBase * node) [inline]
Definition at line 1095 of file maglev-assembler-inl.h.
                    {
  DefineExceptionHandlerPoint(node);
  DefineLazyDeoptPoint(node->lazy_deopt_info());
}
References DefineExceptionHandlerPoint(), DefineLazyDeoptPoint(), and v8::internal::maglev::NodeBase::lazy_deopt_info().
DefineExceptionHandlerPoint()
void v8::internal::maglev::MaglevAssembler::DefineExceptionHandlerPoint (NodeBase * node) [inline]
Definition at line 1088 of file maglev-assembler-inl.h.
                                                                       {
  ExceptionHandlerInfo* info = node->exception_handler_info();
  if (!info->HasExceptionHandler()) return;
  info->set_pc_offset(pc_offset_for_safepoint());
  code_gen_state()->PushHandlerInfo(node);
}
References code_gen_state(), v8::internal::maglev::NodeBase::exception_handler_info(), v8::internal::maglev::ExceptionHandlerInfo::HasExceptionHandler(), v8::internal::Assembler::pc_offset_for_safepoint(), v8::internal::maglev::MaglevCodeGenState::PushHandlerInfo(), and v8::internal::maglev::ExceptionHandlerInfo::set_pc_offset().
Referenced by DefineExceptionHandlerAndLazyDeoptPoint().
DefineLazyDeoptPoint()
void v8::internal::maglev::MaglevAssembler::DefineLazyDeoptPoint (LazyDeoptInfo * info) [inline]
Definition at line 1081 of file maglev-assembler-inl.h.
                                                                     {
  info->set_deopting_call_return_pc(pc_offset_for_safepoint());
  code_gen_state()->PushLazyDeopt(info);
  safepoint_table_builder()->DefineSafepoint(this);
  MaybeEmitPlaceHolderForDeopt();
}
References code_gen_state(), v8::internal::MaglevSafepointTableBuilder::DefineSafepoint(), MaybeEmitPlaceHolderForDeopt(), v8::internal::Assembler::pc_offset_for_safepoint(), v8::internal::maglev::MaglevCodeGenState::PushLazyDeopt(), safepoint_table_builder(), and v8::internal::maglev::LazyDeoptInfo::set_deopting_call_return_pc().
Referenced by DefineExceptionHandlerAndLazyDeoptPoint().
DeoptIfBufferDetached()
template<typename NodeT >
void v8::internal::maglev::MaglevAssembler::DeoptIfBufferDetached (Register array, Register scratch, NodeT * node) [inline]
Definition at line 700 of file maglev-assembler-arm-inl.h.
                                                                {
    // A detached buffer leads to megamorphic feedback, so we won't have a deopt
    // loop if we deopt here.
    LoadTaggedField(scratch,
                    FieldMemOperand(array, JSArrayBufferView::kBufferOffset));
    LoadTaggedField(scratch,
                    FieldMemOperand(scratch, JSArrayBuffer::kBitFieldOffset));
    tst(scratch, Operand(JSArrayBuffer::WasDetachedBit::kMask));
    EmitEagerDeoptIf(ne, DeoptimizeReason::kArrayBufferWasDetached, node);
}
References EmitEagerDeoptIf(), v8::internal::FieldMemOperand(), LoadTaggedField(), v8::internal::ne, and v8::internal::Assembler::tst().
EmitEagerDeopt()
template<typename NodeT >
void v8::internal::maglev::MaglevAssembler::EmitEagerDeopt (NodeT * node, DeoptimizeReason reason) [inline]
Definition at line 1020 of file maglev-assembler.h.
                                                                     {
  RecordComment("-- jump to eager deopt");
  JumpToDeopt(GetDeoptLabel(node, reason));
}
References GetDeoptLabel(), JumpToDeopt(), and v8::internal::AssemblerBase::RecordComment().
EmitEagerDeoptIf()
template<typename NodeT >
void v8::internal::maglev::MaglevAssembler::EmitEagerDeoptIf (Condition cond, DeoptimizeReason reason, NodeT * node) [inline]
Definition at line 1027 of file maglev-assembler.h.
                                                           {
  RecordComment("-- Jump to eager deopt");
  JumpIf(cond, GetDeoptLabel(node, reason));
}
References GetDeoptLabel(), JumpIf(), and v8::internal::AssemblerBase::RecordComment().
Referenced by CompareInstanceTypeRangeAndEagerDeoptIf(), CompareMapWithRootAndEmitEagerDeoptIf(), CompareRootAndEmitEagerDeoptIf(), CompareTaggedRootAndEmitEagerDeoptIf(), CompareUInt32AndEmitEagerDeoptIf(), DeoptIfBufferDetached(), and EmitEagerDeoptIfNotEqual().
EmitEagerDeoptIfNotEqual()
template<typename NodeT >
void v8::internal::maglev::MaglevAssembler::EmitEagerDeoptIfNotEqual (DeoptimizeReason reason, NodeT * node) [inline]
Definition at line 1317 of file maglev-assembler-arm-inl.h.
                                                                   {
  EmitEagerDeoptIf(ne, reason, node);
}
References EmitEagerDeoptIf(), and v8::internal::ne.
EmitEagerDeoptIfNotSmi()
template<typename NodeT >
void v8::internal::maglev::MaglevAssembler::EmitEagerDeoptIfNotSmi (NodeT * node, Register object, DeoptimizeReason reason) [inline]
Definition at line 1042 of file maglev-assembler.h.
                                                                      {
  RecordComment("-- Jump to eager deopt");
  JumpIfNotSmi(object, GetDeoptLabel(node, reason));
}
References GetDeoptLabel(), JumpIfNotSmi(), and v8::internal::AssemblerBase::RecordComment().
EmitEagerDeoptIfSmi()
template<typename NodeT >
void v8::internal::maglev::MaglevAssembler::EmitEagerDeoptIfSmi (NodeT * node, Register object, DeoptimizeReason reason) [inline]
Definition at line 1035 of file maglev-assembler.h.
                                                                   {
  RecordComment("-- Jump to eager deopt");
  JumpIfSmi(object, GetDeoptLabel(node, reason));
}
References GetDeoptLabel(), JumpIfSmi(), and v8::internal::AssemblerBase::RecordComment().
EmitEagerDeoptStress()
void v8::internal::maglev::MaglevAssembler::EmitEagerDeoptStress (Label * label) [inline]
Definition at line 903 of file maglev-assembler-arm-inl.h.
                                                               {
  // TODO(olivf): On arm `--deopt-every-n-times` is currently not supported.
  // Supporting it would require to implement this method, additionally handle
  // deopt branches in Cbz, and handle all cases where we fall through to the
  // deopt branch (like Int32Divide).
}
EmitEnterExitFrame()
void v8::internal::maglev::MaglevAssembler::EmitEnterExitFrame (int extra_slots, StackFrame::Type frame_type, Register c_function, Register scratch) [inline]
Definition at line 524 of file maglev-assembler-arm-inl.h.
                                                                  {
  EnterExitFrame(scratch, extra_slots, frame_type);
}
References v8::internal::MacroAssembler::EnterExitFrame().
EnsureWritableFastElements()
void v8::internal::maglev::MaglevAssembler::EnsureWritableFastElements (RegisterSnapshot register_snapshot, Register elements, Register object, Register scratch)
Definition at line 137 of file maglev-assembler.cc.
                      {
  ZoneLabelRef done(this);
  CompareMapWithRoot(elements, RootIndex::kFixedArrayMap, scratch);
  JumpToDeferredIf(
      kNotEqual,
      [](MaglevAssembler* masm, ZoneLabelRef done, Register object,
         Register result_reg, RegisterSnapshot snapshot) {
        {
          snapshot.live_registers.clear(result_reg);
          snapshot.live_tagged_registers.clear(result_reg);
          SaveRegisterStateForCall save_register_state(masm, snapshot);
          __ CallBuiltin<Builtin::kCopyFastSmiOrObjectElements>(object);
          save_register_state.DefineSafepoint();
          __ Move(result_reg, kReturnRegister0);
        }
        __ Jump(*done);
      },
      done, object, elements, register_snapshot);
  bind(*done);
}
References __, v8::internal::Assembler::bind(), v8::internal::RegListBase< RegisterT >::clear(), CompareMapWithRoot(), v8::internal::maglev::SaveRegisterStateForCall::DefineSafepoint(), Jump(), JumpToDeferredIf(), v8::internal::kNotEqual, v8::internal::kReturnRegister0, v8::internal::maglev::RegisterSnapshot::live_registers, v8::internal::maglev::RegisterSnapshot::live_tagged_registers, and Move().
FinishCode()
void v8::internal::maglev::MaglevAssembler::FinishCode () [inline]
Definition at line 1314 of file maglev-assembler-arm-inl.h.
{ CheckConstPool(true, false); }
References v8::internal::Assembler::CheckConstPool().
Float64SilenceNan()
void v8::internal::maglev::MaglevAssembler::Float64SilenceNan (DoubleRegister value) [inline]
Definition at line 943 of file maglev-assembler-arm-inl.h.
                                                            {
  VFPCanonicalizeNaN(value, value);
}
References v8::internal::value, and v8::internal::MacroAssembler::VFPCanonicalizeNaN().
FromAnyToRegister()
Register v8::internal::maglev::MaglevAssembler::FromAnyToRegister (const Input & input, Register scratch)
Definition at line 42 of file maglev-assembler.cc.
                                                              {
  if (input.operand().IsConstant()) {
    input.node()->LoadToRegister(this, scratch);
    return scratch;
  }
  const compiler::AllocatedOperand& operand =
      compiler::AllocatedOperand::cast(input.operand());
  if (operand.IsRegister()) {
    return ToRegister(input);
  } else {
    DCHECK(operand.IsStackSlot());
    Move(scratch, ToMemOperand(input));
    return scratch;
  }
}
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::maglev::ValueNode::LoadToRegister(), Move(), v8::internal::maglev::Input::node(), v8::internal::maglev::ValueLocation::operand(), ToMemOperand(), and v8::internal::maglev::ToRegister().
FunctionEntryStackCheck()
Condition v8::internal::maglev::MaglevAssembler::FunctionEntryStackCheck (int stack_check_offset) [inline]
Definition at line 1300 of file maglev-assembler-arm-inl.h.
                            {
  TemporaryRegisterScope temps(this);
  Register stack_cmp_reg = sp;
  if (stack_check_offset >= kStackLimitSlackForDeoptimizationInBytes) {
    stack_cmp_reg = temps.AcquireScratch();
    sub(stack_cmp_reg, sp, Operand(stack_check_offset));
  }
  Register interrupt_stack_limit = temps.AcquireScratch();
  LoadStackLimit(interrupt_stack_limit, StackLimitKind::kInterruptStackLimit);
  cmp(stack_cmp_reg, interrupt_stack_limit);
  return kUnsignedGreaterThanEqual;
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::cmp(), v8::internal::kInterruptStackLimit, v8::internal::kStackLimitSlackForDeoptimizationInBytes, v8::internal::kUnsignedGreaterThanEqual, v8::internal::MacroAssembler::LoadStackLimit(), and v8::internal::Assembler::sub().
GetAllocatableDoubleRegisters()
static constexpr DoubleRegList v8::internal::maglev::MaglevAssembler::GetAllocatableDoubleRegisters () [inline], [static], [constexpr]
Definition at line 120 of file maglev-assembler.h.
                                                                 {
    return kAllocatableDoubleRegisters;
  }
References v8::internal::kAllocatableDoubleRegisters.
GetAllocatableRegisters()
static constexpr RegList v8::internal::maglev::MaglevAssembler::GetAllocatableRegisters () [inline], [static], [constexpr]
Definition at line 105 of file maglev-assembler.h.
                                                     {
#if defined(V8_TARGET_ARCH_ARM)
    return kAllocatableGeneralRegisters - kMaglevExtraScratchRegister;
#elif defined(V8_TARGET_ARCH_RISCV64)
    return kAllocatableGeneralRegisters - kMaglevExtraScratchRegister -
           kMaglevFlagsRegister;
#else
    return kAllocatableGeneralRegisters;
#endif
  }
References v8::internal::kAllocatableGeneralRegisters, v8::internal::kMaglevExtraScratchRegister, and v8::internal::kMaglevFlagsRegister.
GetDeoptLabel()
template<typename NodeT >
Label * v8::internal::maglev::MaglevAssembler::GetDeoptLabel (NodeT * node, DeoptimizeReason reason) [inline]
Definition at line 1005 of file maglev-assembler.h.
                                                                      {
  static_assert(NodeT::kProperties.can_eager_deopt());
  EagerDeoptInfo* deopt_info = node->eager_deopt_info();
  if (deopt_info->reason() != DeoptimizeReason::kUnknown) {
    DCHECK_EQ(deopt_info->reason(), reason);
  }
  if (deopt_info->deopt_entry_label()->is_unused()) {
    code_gen_state()->PushEagerDeopt(deopt_info);
    deopt_info->set_reason(reason);
  }
  return node->eager_deopt_info()->deopt_entry_label();
}
References code_gen_state(), DCHECK_EQ, v8::internal::maglev::DeoptInfo::deopt_entry_label(), v8::internal::Label::is_unused(), v8::internal::maglev::MaglevCodeGenState::PushEagerDeopt(), v8::internal::maglev::EagerDeoptInfo::reason(), and v8::internal::maglev::EagerDeoptInfo::set_reason().
Referenced by EmitEagerDeopt(), EmitEagerDeoptIf(), EmitEagerDeoptIfNotSmi(), and EmitEagerDeoptIfSmi().
GetFramePointer()
Register v8::internal::maglev::MaglevAssembler::GetFramePointer () [inline]
Definition at line 284 of file maglev-assembler-arm-inl.h.
{ return fp; }
GetFramePointerOffsetForStackSlot() [1/2]
int v8::internal::maglev::MaglevAssembler::GetFramePointerOffsetForStackSlot (const compiler::AllocatedOperand & operand) [inline]
Definition at line 130 of file maglev-assembler.h.
                                               {
    int index = operand.index();
    if (operand.representation() != MachineRepresentation::kTagged) {
      index += code_gen_state()->tagged_slots();
    }
    return GetFramePointerOffsetForStackSlot(index);
  }
References v8::internal::compiler::LocationOperand::index(), v8::internal::index, v8::internal::kTagged, and v8::internal::compiler::LocationOperand::representation().
Referenced by GetStackSlot().
GetFramePointerOffsetForStackSlot() [2/2]
constexpr int v8::internal::maglev::MaglevAssembler::GetFramePointerOffsetForStackSlot (int index) [inline], [constexpr], [private]
Definition at line 853 of file maglev-assembler.h.
                                                                    {
    return StandardFrameConstants::kExpressionsOffset -
           index * kSystemPointerSize;
  }
References v8::internal::index, v8::internal::StandardFrameConstants::kExpressionsOffset, and v8::internal::kSystemPointerSize.
GetStackSlot()
MemOperand v8::internal::maglev::MaglevAssembler::GetStackSlot (const compiler::AllocatedOperand & operand) [inline]
Definition at line 287 of file maglev-assembler-arm-inl.h.
                                             {
  return MemOperand(fp, GetFramePointerOffsetForStackSlot(operand));
}
References GetFramePointerOffsetForStackSlot().
Referenced by v8::internal::maglev::detail::PushInput(), and ToMemOperand().
IncrementAddress()
void v8::internal::maglev::MaglevAssembler::IncrementAddress (Register reg, int32_t delta) [inline]
Definition at line 513 of file maglev-assembler-arm-inl.h.
                                                                         {
  add(reg, reg, Operand(delta));
}
References v8::internal::Assembler::add().
IncrementInt32()
void v8::internal::maglev::MaglevAssembler::IncrementInt32 (Register reg) [inline]
Definition at line 481 of file maglev-assembler-arm-inl.h.
                                                        {
  add(reg, reg, Operand(1));
}
References v8::internal::Assembler::add().
Int32ToDouble()
void v8::internal::maglev::MaglevAssembler::Int32ToDouble (DoubleRegister result, Register src) [inline]
Definition at line 1255 of file maglev-assembler-arm-inl.h.
                                                         {
  UseScratchRegisterScope temps(this);
  SwVfpRegister temp_vfps = SwVfpRegister::no_reg();
  if (result.code() < 16) {
    temp_vfps = LowDwVfpRegister::from_code(result.code()).low();
  } else {
    temp_vfps = temps.AcquireS();
  }
  vmov(temp_vfps, src);
  vcvt_f64_s32(result, temp_vfps);
}
References v8::internal::UseScratchRegisterScope::AcquireS(), v8::internal::RegisterBase< LowDwVfpRegister, kDoubleCode_d16 >::from_code(), v8::internal::LowDwVfpRegister::low(), v8::internal::RegisterBase< SwVfpRegister, kSwVfpAfterLast >::no_reg(), v8::base::internal::result, v8::internal::Assembler::vcvt_f64_s32(), and v8::internal::Assembler::vmov().
Referenced by IntPtrToDouble(), MaterialiseValueNode(), and SmiToDouble().
IntPtrToDouble()
void v8::internal::maglev::MaglevAssembler::IntPtrToDouble (DoubleRegister result, Register src) [inline]
Definition at line 1268 of file maglev-assembler-arm-inl.h.
                                                          {
  return Int32ToDouble(result, src);
}
References Int32ToDouble(), and v8::base::internal::result.
Referenced by MaterialiseValueNode().
IsCallableAndNotUndetectable()
Condition v8::internal::maglev::MaglevAssembler::IsCallableAndNotUndetectable (Register map, Register scratch) [inline]
Definition at line 717 of file maglev-assembler-arm-inl.h.
                                    {
  ldrb(scratch, FieldMemOperand(map, Map::kBitFieldOffset));
  and_(scratch, scratch,
       Operand(Map::Bits1::IsUndetectableBit::kMask |
               Map::Bits1::IsCallableBit::kMask));
  cmp(scratch, Operand(Map::Bits1::IsCallableBit::kMask));
  return kEqual;
}
References v8::internal::Assembler::and_(), v8::internal::Assembler::cmp(), v8::internal::FieldMemOperand(), v8::internal::kEqual, and v8::internal::Assembler::ldrb().
Referenced by TestTypeOf().
IsDeoptLabel()
bool v8::internal::maglev::MaglevAssembler::IsDeoptLabel (Label * label) [inline]
Definition at line 995 of file maglev-assembler.h.
                                                      {
  for (auto deopt : code_gen_state_->eager_deopts()) {
    if (deopt->deopt_entry_label() == label) {
      return true;
    }
  }
  return false;
}
References code_gen_state_, and v8::internal::maglev::MaglevCodeGenState::eager_deopts().
Referenced by Jump(), and JumpToDeopt().
IsNotCallableNorUndetactable()
Condition v8::internal::maglev::MaglevAssembler::IsNotCallableNorUndetactable (Register map, Register scratch) [inline]
Definition at line 727 of file maglev-assembler-arm-inl.h.
                                    {
  ldrb(scratch, FieldMemOperand(map, Map::kBitFieldOffset));
  tst(scratch, Operand(Map::Bits1::IsUndetectableBit::kMask |
                       Map::Bits1::IsCallableBit::kMask));
  return kEqual;
}
References v8::internal::FieldMemOperand(), v8::internal::kEqual, v8::internal::Assembler::ldrb(), and v8::internal::Assembler::tst().
Referenced by TestTypeOf().
IsRootConstant()
Condition v8::internal::maglev::MaglevAssembler::IsRootConstant (Input input, RootIndex root_index) [inline]
Definition at line 266 of file maglev-assembler-arm-inl.h.
                                                                       {
  if (input.operand().IsRegister()) {
    CompareRoot(ToRegister(input), root_index);
  } else {
    DCHECK(input.operand().IsStackSlot());
    TemporaryRegisterScope temps(this);
    Register scratch = temps.AcquireScratch();
    ldr(scratch, ToMemOperand(input));
    CompareRoot(scratch, root_index);
  }
  return eq;
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::MacroAssembler::CompareRoot(), v8::internal::DCHECK(), v8::internal::eq, v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::Assembler::ldr(), v8::internal::maglev::ValueLocation::operand(), ToMemOperand(), and v8::internal::maglev::ToRegister().
Jump()
void v8::internal::maglev::MaglevAssembler::Jump (Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 891 of file maglev-assembler-arm-inl.h.
                                                              {
  // Any eager deopts should go through JumpIf to enable us to support the
  // `--deopt-every-n-times` stress mode. See EmitEagerDeoptStress.
  DCHECK(!IsDeoptLabel(target));
  b(target);
}
References v8::internal::Assembler::b(), v8::internal::DCHECK(), and IsDeoptLabel().
Referenced by v8::internal::maglev::AllocateSlow(), AssertElidedWriteBarrier(), Branch(), CheckAndEmitDeferredWriteBarrier(), EnsureWritableFastElements(), JumpIfHoleNan(), MaterialiseValueNode(), SmiTagIntPtrAndJumpIfSuccess(), SmiTagUint32AndJumpIfSuccess(), TestTypeOf(), ToBoolean(), ToUint8Clamped(), TruncateDoubleToInt32(), and TryChangeFloat64ToIndex().
JumpIf()
void v8::internal::maglev::MaglevAssembler::JumpIf (Condition cond, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 910 of file maglev-assembler-arm-inl.h.
                                                   {
  b(target, cond);
}
References v8::internal::Assembler::b().
Referenced by Branch(), CheckInt32IsSmi(), CompareByteAndJumpIf(), CompareDoubleAndJumpIfZeroOrNaN(), CompareFloat64AndBranch(), CompareFloat64AndJumpIf(), CompareInstanceTypeAndJumpIf(), CompareInt32AndJumpIf(), CompareIntPtrAndJumpIf(), CompareSmiAndJumpIf(), CompareTaggedAndJumpIf(), EmitEagerDeoptIf(), v8::internal::maglev::MapCompare::Generate(), JumpIfHoleNan(), JumpIfJSAnyIsNotPrimitive(), JumpIfNan(), JumpIfNotNan(), JumpIfNotObjectType(), JumpIfObjectType(), JumpIfObjectTypeInRange(), JumpIfObjectTypeNotInRange(), JumpIfSeqOneByteStringMap(), JumpToDeferredIf(), SmiAddConstant(), SmiSubConstant(), SmiTagInt32AndJumpIfFail(), SmiTagInt32AndJumpIfSuccess(), ToBoolean(), ToUint8Clamped(), TryChangeFloat64ToIndex(), TryTruncateDoubleToInt32(), and TryTruncateDoubleToUint32().
JumpIfByte()
void v8::internal::maglev::MaglevAssembler::JumpIfByte (Condition cc, Register value, int32_t byte, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 937 of file maglev-assembler-arm-inl.h.
                                                               {
  cmp(value, Operand(byte));
  b(cc, target);
}
References v8::internal::Assembler::b(), v8::internal::cc, v8::internal::Assembler::cmp(), and v8::internal::value.
JumpIfHoleNan()
void v8::internal::maglev::MaglevAssembler::JumpIfHoleNan (DoubleRegister value, Register scratch, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 981 of file maglev-assembler-arm-inl.h.
                                                                           {
  // TODO(leszeks): Right now this only accepts Zone-allocated target labels.
  // This works because all callsites are jumping to either a deopt, deferred
  // code, or a basic block. If we ever need to jump to an on-stack label, we
  // have to add support for it here change the caller to pass a ZoneLabelRef.
  DCHECK(compilation_info()->zone()->Contains(target));
  ZoneLabelRef is_hole = ZoneLabelRef::UnsafeFromLabelPointer(target);
  ZoneLabelRef is_not_hole(this);
  VFPCompareAndSetFlags(value, value);
  JumpIf(ConditionForNaN(),
         MakeDeferredCode(
             [](MaglevAssembler* masm, DoubleRegister value, Register scratch,
                ZoneLabelRef is_hole, ZoneLabelRef is_not_hole) {
               masm->VmovHigh(scratch, value);
               masm->CompareInt32AndJumpIf(scratch, kHoleNanUpper32, kEqual,
                                           *is_hole);
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
               masm->CompareInt32AndJumpIf(scratch, kUndefinedNanUpper32,
                                           kEqual, *is_hole);
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
               masm->Jump(*is_not_hole);
             },
             value, scratch, is_hole, is_not_hole));
  bind(*is_not_hole);
}
References v8::internal::Assembler::bind(), CompareInt32AndJumpIf(), compilation_info(), v8::internal::maglev::ConditionForNaN(), v8::internal::anonymous_namespace{read-only-promotion.cc}::Contains(), v8::internal::DCHECK(), Jump(), JumpIf(), v8::internal::kEqual, v8::internal::kHoleNanUpper32, MakeDeferredCode(), v8::internal::maglev::ZoneLabelRef::UnsafeFromLabelPointer(), v8::internal::value, v8::internal::MacroAssembler::VFPCompareAndSetFlags(), v8::internal::MacroAssembler::VmovHigh(), and v8::internal::Assembler::zone().
JumpIfJSAnyIsNotPrimitive()
void v8::internal::maglev::MaglevAssembler::JumpIfJSAnyIsNotPrimitive (Register heap_object, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 828 of file maglev-assembler-arm-inl.h.
                                                                 {
  // If the type of the result (stored in its map) is less than
  // FIRST_JS_RECEIVER_TYPE, it is not an object in the ECMA sense.
  static_assert(LAST_JS_RECEIVER_TYPE == LAST_TYPE);
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  MacroAssembler::CompareObjectType(heap_object, scratch, scratch,
                                    FIRST_JS_RECEIVER_TYPE);
  JumpIf(kUnsignedGreaterThanEqual, target, distance);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::MacroAssembler::CompareObjectType(), JumpIf(), v8::internal::kUnsignedGreaterThanEqual, and v8::internal::LAST_TYPE.
JumpIfNan()
void v8::internal::maglev::MaglevAssembler::JumpIfNan (DoubleRegister value, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1027 of file maglev-assembler-arm-inl.h.
                                                        {
  VFPCompareAndSetFlags(value, value);
  JumpIf(ConditionForNaN(), target, distance);
}
References v8::internal::maglev::ConditionForNaN(), JumpIf(), v8::internal::value, and v8::internal::MacroAssembler::VFPCompareAndSetFlags().
JumpIfNotCallable()
void v8::internal::maglev::MaglevAssembler::JumpIfNotCallable (Register object, Register scratch, CheckType check_type, Label * target, Label::Distance distance = Label::kFar)
Definition at line 122 of file maglev-assembler.cc.
                                                                {
  if (check_type == CheckType::kCheckHeapObject) {
    JumpIfSmi(object, target, distance);
  } else if (v8_flags.debug_code) {
    AssertNotSmi(object);
  }
  LoadMap(scratch, object);
  static_assert(Map::kBitFieldOffsetEnd + 1 - Map::kBitFieldOffset == 1);
  TestUint8AndJumpIfAllClear(FieldMemOperand(scratch, Map::kBitFieldOffset),
                             Map::Bits1::IsCallableBit::kMask, target,
                             distance);
}
References v8::internal::MacroAssembler::AssertNotSmi(), v8::internal::FieldMemOperand(), JumpIfSmi(), v8::internal::maglev::kCheckHeapObject, v8::internal::MacroAssembler::LoadMap(), TestUint8AndJumpIfAllClear(), and v8::internal::v8_flags.
JumpIfNotHoleNan() [1/2]
void v8::internal::maglev::MaglevAssembler::JumpIfNotHoleNan (DoubleRegister value, Register scratch, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1008 of file maglev-assembler-arm-inl.h.
                                                               {
  JumpIfNotNan(value, target, distance);
  VmovHigh(scratch, value);
  CompareInt32AndJumpIf(scratch, kHoleNanUpper32, kNotEqual, target, distance);
}
References CompareInt32AndJumpIf(), JumpIfNotNan(), v8::internal::kHoleNanUpper32, v8::internal::kNotEqual, v8::internal::value, and v8::internal::MacroAssembler::VmovHigh().
Referenced by MaterialiseValueNode().
JumpIfNotHoleNan() [2/2]
void v8::internal::maglev::MaglevAssembler::JumpIfNotHoleNan (MemOperand operand, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1016 of file maglev-assembler-arm-inl.h.
                                                               {
  MaglevAssembler::TemporaryRegisterScope temps(this);
  Register upper_bits = temps.AcquireScratch();
  DCHECK(operand.IsImmediateOffset());
  ldr(upper_bits, MemOperand(operand.rn(), operand.offset() + (kDoubleSize / 2),
                             operand.am()));
  CompareInt32AndJumpIf(upper_bits, kHoleNanUpper32, kNotEqual, target,
                        distance);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::MemOperand::am(), CompareInt32AndJumpIf(), v8::internal::DCHECK(), v8::internal::MemOperand::IsImmediateOffset(), v8::internal::kDoubleSize, v8::internal::kHoleNanUpper32, v8::internal::kNotEqual, v8::internal::Assembler::ldr(), v8::internal::MemOperand::offset(), and v8::internal::MemOperand::rn().
JumpIfNotNan()
void v8::internal::maglev::MaglevAssembler::JumpIfNotNan (DoubleRegister value, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1033 of file maglev-assembler-arm-inl.h.
                                                           {
  VFPCompareAndSetFlags(value, value);
  JumpIf(NegateCondition(ConditionForNaN()), target, distance);
}
References v8::internal::maglev::ConditionForNaN(), JumpIf(), v8::internal::NegateCondition(), v8::internal::value, and v8::internal::MacroAssembler::VFPCompareAndSetFlags().
Referenced by JumpIfNotHoleNan().
JumpIfNotObjectType()
void v8::internal::maglev::MaglevAssembler::JumpIfNotObjectType (Register heap_object, InstanceType type, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 750 of file maglev-assembler-arm-inl.h.
                                                                         {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  CompareObjectType(heap_object, scratch, scratch, type);
  JumpIf(kNotEqual, target, distance);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::MacroAssembler::CompareObjectType(), JumpIf(), v8::internal::kNotEqual, and v8::internal::tracing::type.
JumpIfNotRoot()
void v8::internal::maglev::MaglevAssembler::JumpIfNotRoot (Register with, RootIndex index, Label * if_not_equal, Label::Distance distance = Label::kFar) [inline]
Definition at line 921 of file maglev-assembler-arm-inl.h.
                                                                   {
  MacroAssembler::JumpIfNotRoot(with, index, if_not_equal);
}
References v8::internal::index, and v8::internal::MacroAssembler::JumpIfNotRoot().
JumpIfNotSeqOneByteString()
void v8::internal::maglev::MaglevAssembler::JumpIfNotSeqOneByteString (Register heap_object, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1027 of file maglev-assembler-inl.h.
                                                                 {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
#ifdef V8_COMPRESS_POINTERS
  LoadCompressedMap(scratch, heap_object);
#else
  LoadMap(scratch, heap_object);
#endif
  JumpIfSeqOneByteStringMap(scratch, target, distance, false);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), JumpIfSeqOneByteStringMap(), v8::internal::MacroAssembler::LoadCompressedMap(), and v8::internal::MacroAssembler::LoadMap().
JumpIfNotSmi()
void v8::internal::maglev::MaglevAssembler::JumpIfNotSmi (Register src, Label * on_not_smi, Label::Distance near_jump = Label::kFar) [inline]
Definition at line 932 of file maglev-assembler-arm-inl.h.
                                                                  {
  MacroAssembler::JumpIfNotSmi(src, on_smi);
}
References v8::internal::MacroAssembler::JumpIfNotSmi().
Referenced by AssertElidedWriteBarrier(), and EmitEagerDeoptIfNotSmi().
JumpIfNotString()
void v8::internal::maglev::MaglevAssembler::JumpIfNotString (Register heap_object, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1014 of file maglev-assembler-inl.h.
                                                                     {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
#ifdef V8_COMPRESS_POINTERS
  LoadCompressedMap(scratch, heap_object);
#else
  LoadMap(scratch, heap_object);
#endif
  JumpIfStringMap(scratch, target, distance, false);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), JumpIfStringMap(), v8::internal::MacroAssembler::LoadCompressedMap(), and v8::internal::MacroAssembler::LoadMap().
JumpIfNotUndetectable()
void v8::internal::maglev::MaglevAssembler::JumpIfNotUndetectable (Register object, Register scratch, CheckType check_type, Label * target, Label::Distance distance = Label::kFar)
Definition at line 90 of file maglev-assembler.cc.
                                                                    {
  if (check_type == CheckType::kCheckHeapObject) {
    JumpIfSmi(object, target, distance);
  } else if (v8_flags.debug_code) {
    AssertNotSmi(object);
  }
  // For heap objects, check the map's undetectable bit.
  LoadMap(scratch, object);
  TestUint8AndJumpIfAllClear(FieldMemOperand(scratch, Map::kBitFieldOffset),
                             Map::Bits1::IsUndetectableBit::kMask, target,
                             distance);
}
References v8::internal::MacroAssembler::AssertNotSmi(), v8::internal::FieldMemOperand(), JumpIfSmi(), v8::internal::maglev::kCheckHeapObject, v8::internal::MacroAssembler::LoadMap(), TestUint8AndJumpIfAllClear(), and v8::internal::v8_flags.
JumpIfObjectType()
void v8::internal::maglev::MaglevAssembler::JumpIfObjectType (Register heap_object, InstanceType type, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 741 of file maglev-assembler-arm-inl.h.
                                                                      {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  CompareObjectType(heap_object, scratch, scratch, type);
  JumpIf(kEqual, target, distance);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::MacroAssembler::CompareObjectType(), JumpIf(), v8::internal::kEqual, and v8::internal::tracing::type.
JumpIfObjectTypeInRange()
void v8::internal::maglev::MaglevAssembler::JumpIfObjectTypeInRange (Register heap_object, InstanceType lower_limit, InstanceType higher_limit, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 781 of file maglev-assembler-arm-inl.h.
                                                                             {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  CompareObjectTypeRange(heap_object, scratch, scratch, scratch, lower_limit,
                         higher_limit);
  JumpIf(kUnsignedLessThanEqual, target, distance);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::MacroAssembler::CompareObjectTypeRange(), JumpIf(), and v8::internal::kUnsignedLessThanEqual.
JumpIfObjectTypeNotInRange()
void v8::internal::maglev::MaglevAssembler::JumpIfObjectTypeNotInRange (Register heap_object, InstanceType lower_limit, InstanceType higher_limit, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 793 of file maglev-assembler-arm-inl.h.
                                           {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  CompareObjectTypeRange(heap_object, scratch, scratch, scratch, lower_limit,
                         higher_limit);
  JumpIf(kUnsignedGreaterThan, target, distance);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::MacroAssembler::CompareObjectTypeRange(), JumpIf(), and v8::internal::kUnsignedGreaterThan.
JumpIfRoot()
void v8::internal::maglev::MaglevAssembler::JumpIfRoot (Register with, RootIndex index, Label * if_equal, Label::Distance distance = Label::kFar) [inline]
Definition at line 915 of file maglev-assembler-arm-inl.h.
                                                                {
  MacroAssembler::JumpIfRoot(with, index, if_equal);
}
References v8::internal::index, and v8::internal::MacroAssembler::JumpIfRoot().
Referenced by TestTypeOf(), and ToBoolean().
JumpIfSeqOneByteStringMap()
void v8::internal::maglev::MaglevAssembler::JumpIfSeqOneByteStringMap (Register map, Label * target, Label::Distance distance = Label::kFar, bool jump_if_true = true) [inline]
Definition at line 956 of file maglev-assembler-inl.h.
                                                                          {
  Label fallthrough;
  Label* target_if_false = jump_if_true ? &fallthrough : target;
  Label::Distance distance_if_false = jump_if_true ? Label::kNear : distance;
#if V8_STATIC_ROOTS_BOOL
  // All string maps are allocated at the start of the read only heap. Thus,
  // non-strings must have maps with larger (compressed) addresses.
  static_assert(
      InstanceTypeChecker::kUniqueMapRangeOfStringType::kSeqString.first == 0);
  CompareInt32AndJumpIf(
      map, InstanceTypeChecker::kUniqueMapRangeOfStringType::kSeqString.second,
      kUnsignedGreaterThan, target_if_false, distance_if_false);
  static_assert(base::bits::CountPopulation(
                    InstanceTypeChecker::kStringMapEncodingMask) == 1);
  static_assert(InstanceTypeChecker::kTwoByteStringMapBit ==
                InstanceTypeChecker::kStringMapEncodingMask);
  if (jump_if_true) {
    TestInt32AndJumpIfAllClear(map, InstanceTypeChecker::kStringMapEncodingMask,
                               target, distance);
  } else {
    TestInt32AndJumpIfAnySet(map, InstanceTypeChecker::kStringMapEncodingMask,
                             target, distance);
  }
#else
#ifdef V8_COMPRESS_POINTERS
  DecompressTagged(map, map);
#endif
  static_assert(FIRST_STRING_TYPE == FIRST_TYPE);
  TemporaryRegisterScope temps(this);
  Register instance_type = temps.AcquireScratch();
  Condition jump_cond = CompareInstanceTypeRange(map, instance_type, FIRST_TYPE,
                                                 LAST_STRING_TYPE);
  JumpIf(NegateCondition(jump_cond), target_if_false, distance_if_false);
  AndInt32(instance_type, kStringRepresentationAndEncodingMask);
  CompareInt32AndJumpIf(instance_type, kSeqOneByteStringTag,
                        jump_if_true ? kEqual : kNotEqual, target, distance);
#endif
  bind(&fallthrough);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), AndInt32(), v8::internal::Assembler::bind(), CompareInstanceTypeRange(), CompareInt32AndJumpIf(), v8::base::bits::CountPopulation(), v8::internal::MacroAssembler::DecompressTagged(), v8::internal::FIRST_TYPE, JumpIf(), v8::internal::kEqual, v8::internal::Label::kNear, v8::internal::kNotEqual, v8::internal::kSeqOneByteStringTag, v8::internal::kStringRepresentationAndEncodingMask, v8::internal::kUnsignedGreaterThan, v8::internal::LAST_STRING_TYPE, v8::internal::NegateCondition(), TestInt32AndJumpIfAllClear(), and TestInt32AndJumpIfAnySet().
Referenced by JumpIfNotSeqOneByteString().
JumpIfSmi()
void v8::internal::maglev::MaglevAssembler::JumpIfSmi (Register src, Label * on_smi, Label::Distance near_jump = Label::kFar) [inline]
Definition at line 927 of file maglev-assembler-arm-inl.h.
                                                               {
  MacroAssembler::JumpIfSmi(src, on_smi);
}
References v8::internal::MacroAssembler::JumpIfSmi().
Referenced by CheckAndEmitDeferredWriteBarrier(), EmitEagerDeoptIfSmi(), JumpIfNotCallable(), JumpIfNotUndetectable(), JumpIfUndetectable(), and TestTypeOf().
JumpIfString()
void v8::internal::maglev::MaglevAssembler::JumpIfString (Register heap_object, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1002 of file maglev-assembler-inl.h.
                                                                  {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
#ifdef V8_COMPRESS_POINTERS
  LoadCompressedMap(scratch, heap_object);
#else
  LoadMap(scratch, heap_object);
#endif
  JumpIfStringMap(scratch, target, distance, true);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), JumpIfStringMap(), v8::internal::MacroAssembler::LoadCompressedMap(), and v8::internal::MacroAssembler::LoadMap().
JumpIfStringMap()
void v8::internal::maglev::MaglevAssembler::JumpIfStringMap (Register map, Label * target, Label::Distance distance = Label::kFar, bool jump_if_true = true) [inline]
Definition at line 934 of file maglev-assembler-inl.h.
                                                                {
#if V8_STATIC_ROOTS_BOOL
  // All string maps are allocated at the start of the read only heap. Thus,
  // non-strings must have maps with larger (compressed) addresses.
  CompareInt32AndJumpIf(
      map, InstanceTypeChecker::kStringMapUpperBound,
      jump_if_true ? kUnsignedLessThanEqual : kUnsignedGreaterThan, target,
      distance);
#else
#ifdef V8_COMPRESS_POINTERS
  DecompressTagged(map, map);
#endif
  static_assert(FIRST_STRING_TYPE == FIRST_TYPE);
  CompareInstanceTypeAndJumpIf(
      map, LAST_STRING_TYPE,
      jump_if_true ? kUnsignedLessThanEqual : kUnsignedGreaterThan, target,
      distance);
#endif
}
References CompareInstanceTypeAndJumpIf(), CompareInt32AndJumpIf(), v8::internal::MacroAssembler::DecompressTagged(), v8::internal::FIRST_TYPE, v8::internal::kUnsignedGreaterThan, v8::internal::kUnsignedLessThanEqual, and v8::internal::LAST_STRING_TYPE.
Referenced by JumpIfNotString(), and JumpIfString().
JumpIfUndetectable()
void v8::internal::maglev::MaglevAssembler::JumpIfUndetectable (Register object, Register scratch, CheckType check_type, Label * target, Label::Distance distance = Label::kFar)
Definition at line 105 of file maglev-assembler.cc.
                                                                 {
  Label detectable;
  if (check_type == CheckType::kCheckHeapObject) {
    JumpIfSmi(object, &detectable, Label::kNear);
  } else if (v8_flags.debug_code) {
    AssertNotSmi(object);
  }
  // For heap objects, check the map's undetectable bit.
  LoadMap(scratch, object);
  TestUint8AndJumpIfAnySet(FieldMemOperand(scratch, Map::kBitFieldOffset),
                           Map::Bits1::IsUndetectableBit::kMask, target,
                           distance);
  bind(&detectable);
}
References v8::internal::MacroAssembler::AssertNotSmi(), v8::internal::Assembler::bind(), v8::internal::FieldMemOperand(), JumpIfSmi(), v8::internal::maglev::kCheckHeapObject, v8::internal::Label::kNear, v8::internal::MacroAssembler::LoadMap(), TestUint8AndJumpIfAnySet(), and v8::internal::v8_flags.
JumpToDeferredIf()
template<typename Function , typename... Args>
void v8::internal::maglev::MaglevAssembler::JumpToDeferredIf (Condition cond, Function && deferred_code_gen, Args &&... args) [inline]
Definition at line 253 of file maglev-assembler-inl.h.
                                                              {
  if (v8_flags.code_comments) {
    RecordComment("-- Jump to deferred code");
  }
  JumpIf(cond, MakeDeferredCode<Function, Args...>(
                   std::forward<Function>(deferred_code_gen),
                   std::forward<Args>(args)...));
}
References v8::base::args, JumpIf(), v8::internal::AssemblerBase::RecordComment(), and v8::internal::v8_flags.
Referenced by EnsureWritableFastElements(), Prologue(), StringFromCharCode(), and ToBoolean().
JumpToDeopt()
void v8::internal::maglev::MaglevAssembler::JumpToDeopt (Label * target) [inline]
Definition at line 898 of file maglev-assembler-arm-inl.h.
                                                      {
  DCHECK(IsDeoptLabel(target));
  b(target);
}
References v8::internal::Assembler::b(), v8::internal::DCHECK(), and IsDeoptLabel().
Referenced by EmitEagerDeopt().
LoadAddress()
void v8::internal::maglev::MaglevAssembler::LoadAddress (Register dst, MemOperand location) [inline]
Definition at line 517 of file maglev-assembler-arm-inl.h.
                                                                          {
  DCHECK_EQ(location.am(), Offset);
  add(dst, location.rn(), Operand(location.offset()));
}
References v8::internal::Assembler::add(), v8::internal::MemOperand::am(), DCHECK_EQ, v8::internal::MemOperand::offset(), v8::internal::Offset, and v8::internal::MemOperand::rn().
LoadAndUntagTaggedSignedField()
void v8::internal::maglev::MaglevAssembler::LoadAndUntagTaggedSignedField (Register result, Register object, int offset) [inline]
Definition at line 446 of file maglev-assembler-inl.h.
                                                                       {
  MacroAssembler::SmiUntagField(result, FieldMemOperand(object, offset));
}
References v8::internal::FieldMemOperand(), v8::base::internal::result, and v8::internal::MacroAssembler::SmiUntagField().
Referenced by StringCharCodeOrCodePointAt().
LoadBitField()
template<typename BitField >
void v8::internal::maglev::MaglevAssembler::LoadBitField (Register result, MemOperand operand) [inline]
Definition at line 210 of file maglev-assembler.h.
                                                                {
    static constexpr int load_size = sizeof(typename BitField::BaseType);
    LoadUnsignedField(result, operand, load_size);
    DecodeField<BitField>(result);
  }
References v8::base::internal::result.
LoadBoundedSizeFromObject()
void v8::internal::maglev::MaglevAssembler::LoadBoundedSizeFromObject (Register result, Register object, int offset) [inline]
Definition at line 333 of file maglev-assembler-arm-inl.h.
                                                                   {
  Move(result, FieldMemOperand(object, offset));
}
References v8::internal::FieldMemOperand(), Move(), and v8::base::internal::result.
LoadByte()
void v8::internal::maglev::MaglevAssembler::LoadByte (Register dst, MemOperand src) [inline]
Definition at line 713 of file maglev-assembler-arm-inl.h.
                                                                  {
  ldrb(dst, src);
}
References v8::internal::Assembler::ldrb().
Referenced by CompareByteAndJumpIf(), and TestUint8AndJumpIfAllClear().
LoadContextCellFloat64Value()
void v8::internal::maglev::MaglevAssembler::LoadContextCellFloat64Value (DoubleRegister value, Register cell) [inline]
Definition at line 1234 of file maglev-assembler-arm-inl.h.
                                                                        {
  AssertContextCellState(cell, ContextCell::kFloat64);
  vldr(value, FieldMemOperand(cell, offsetof(ContextCell, double_value_)));
}
References AssertContextCellState(), v8::internal::FieldMemOperand(), v8::internal::ContextCell::kFloat64, v8::internal::value, and v8::internal::Assembler::vldr().
LoadContextCellInt32Value()
void v8::internal::maglev::MaglevAssembler::LoadContextCellInt32Value (Register value, Register cell) [inline]
Definition at line 1228 of file maglev-assembler-arm-inl.h.
                                                                      {
  AssertContextCellState(cell, ContextCell::kInt32);
  ldr(value, FieldMemOperand(cell, offsetof(ContextCell, double_value_)));
}
References AssertContextCellState(), v8::internal::FieldMemOperand(), v8::internal::ContextCell::kInt32, v8::internal::Assembler::ldr(), and v8::internal::value.
LoadContextCellState()
void v8::internal::maglev::MaglevAssembler::LoadContextCellState (Register state, Register cell) [inline]
Definition at line 1223 of file maglev-assembler-arm-inl.h.
                                                                 {
  ldr(state, FieldMemOperand(cell, offsetof(ContextCell, state_)));
}
References v8::internal::FieldMemOperand(), and v8::internal::Assembler::ldr().
Referenced by AssertContextCellState().
LoadContextCellTaggedValue()
void v8::internal::maglev::MaglevAssembler::LoadContextCellTaggedValue (Register value, Register cell) [inline]
Definition at line 300 of file maglev-assembler-inl.h.
                                                                       {
  static_assert(ContextCell::kConst == 0);
  static_assert(ContextCell::kSmi == 1);
  AssertContextCellState(cell, ContextCell::kSmi, kLessThanEqual);
  LoadTaggedField(value, cell, offsetof(ContextCell, tagged_value_));
}
References AssertContextCellState(), v8::internal::ContextCell::kConst, v8::internal::kLessThanEqual, v8::internal::ContextCell::kSmi, LoadTaggedField(), and v8::internal::value.
LoadDataField()
void v8::internal::maglev::MaglevAssembler::LoadDataField (const PolymorphicAccessInfo & access_info, Register result, Register object, Register scratch)
Definition at line 66 of file maglev-assembler.cc.
                                                      {
  Register load_source = object;
  // Resolve property holder.
  if (access_info.holder().has_value()) {
    load_source = scratch;
    Move(load_source, access_info.holder().value().object());
  }
  FieldIndex field_index = access_info.field_index();
  if (!field_index.is_inobject()) {
    Register load_source_object = load_source;
    if (load_source == object) {
      load_source = scratch;
    }
    // The field is in the property array, first load it from there.
    AssertNotSmi(load_source_object);
    LoadTaggedField(load_source, load_source_object,
                    JSReceiver::kPropertiesOrHashOffset);
  }
  AssertNotSmi(load_source);
  LoadTaggedField(result, load_source, field_index.offset());
}
References v8::internal::MacroAssembler::AssertNotSmi(), v8::internal::maglev::PolymorphicAccessInfo::field_index(), v8::internal::maglev::PolymorphicAccessInfo::holder(), v8::internal::FieldIndex::is_inobject(), LoadTaggedField(), Move(), v8::internal::FieldIndex::offset(), and v8::base::internal::result.
LoadExternalPointerField()
void v8::internal::maglev::MaglevAssembler::LoadExternalPointerField (Register result, MemOperand operand) [inline]
Definition at line 339 of file maglev-assembler-arm-inl.h.
                                                                          {
  Move(result, operand);
}
References Move(), and v8::base::internal::result.
LoadFixedArrayElement()
void v8::internal::maglev::MaglevAssembler::LoadFixedArrayElement (Register result, Register array, Register index) [inline]
Definition at line 344 of file maglev-assembler-arm-inl.h.
                                                            {
  if (v8_flags.debug_code) {
    AssertObjectType(array, FIXED_ARRAY_TYPE, AbortReason::kUnexpectedValue);
    CompareInt32AndAssert(index, 0, kUnsignedGreaterThanEqual,
                          AbortReason::kUnexpectedNegativeValue);
  }
  LoadTaggedFieldByIndex(result, array, index, kTaggedSize,
                         OFFSET_OF_DATA_START(FixedArray));
}
References AssertObjectType(), CompareInt32AndAssert(), v8::internal::index, v8::internal::kTaggedSize, v8::internal::kUnsignedGreaterThanEqual, LoadTaggedFieldByIndex(), OFFSET_OF_DATA_START, v8::base::internal::result, and v8::internal::v8_flags.
Referenced by LoadFixedArrayElementWithoutDecompressing().
LoadFixedArrayElementWithoutDecompressing()
void v8::internal::maglev::MaglevAssembler::LoadFixedArrayElementWithoutDecompressing (Register result, Register array, Register index) [inline]
Definition at line 355 of file maglev-assembler-arm-inl.h.
                                                     {
  // No compression mode on arm.
  LoadFixedArrayElement(result, array, index);
}
References v8::internal::index, LoadFixedArrayElement(), and v8::base::internal::result.
LoadFixedDoubleArrayElement()
void v8::internal::maglev::MaglevAssembler::LoadFixedDoubleArrayElement (DoubleRegister result, Register array, Register index) [inline]
Definition at line 361 of file maglev-assembler-arm-inl.h.
                                                                  {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  if (v8_flags.debug_code) {
    AssertObjectType(array, FIXED_DOUBLE_ARRAY_TYPE,
                     AbortReason::kUnexpectedValue);
    CompareInt32AndAssert(index, 0, kUnsignedGreaterThanEqual,
                          AbortReason::kUnexpectedNegativeValue);
  }
  add(scratch, array, Operand(index, LSL, kDoubleSizeLog2));
  vldr(result, FieldMemOperand(scratch, OFFSET_OF_DATA_START(FixedArray)));
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::add(), AssertObjectType(), CompareInt32AndAssert(), v8::internal::FieldMemOperand(), v8::internal::index, v8::internal::kDoubleSizeLog2, v8::internal::kUnsignedGreaterThanEqual, v8::internal::LSL, OFFSET_OF_DATA_START, v8::base::internal::result, v8::internal::v8_flags, and v8::internal::Assembler::vldr().
LoadFloat32()
void v8::internal::maglev::MaglevAssembler::LoadFloat32 (DoubleRegister dst, MemOperand src) [inline]
Definition at line 595 of file maglev-assembler-arm-inl.h.
                                                                           {
  UseScratchRegisterScope temps(this);
  SwVfpRegister temp_vfps = SwVfpRegister::no_reg();
  if (dst.code() < 16) {
    temp_vfps = LowDwVfpRegister::from_code(dst.code()).low();
  } else {
    temp_vfps = temps.AcquireS();
  }
  vldr(temp_vfps, src);
  vcvt_f64_f32(dst, temp_vfps);
}
References v8::internal::UseScratchRegisterScope::AcquireS(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::RegisterBase< LowDwVfpRegister, kDoubleCode_d16 >::from_code(), v8::internal::LowDwVfpRegister::low(), v8::internal::RegisterBase< SwVfpRegister, kSwVfpAfterLast >::no_reg(), v8::internal::Assembler::vcvt_f64_f32(), and v8::internal::Assembler::vldr().
LoadFloat64()
void v8::internal::maglev::MaglevAssembler::LoadFloat64 (DoubleRegister dst, MemOperand src) [inline]
Definition at line 612 of file maglev-assembler-arm-inl.h.
                                                                           {
  vldr(dst, src);
}
References v8::internal::Assembler::vldr().
Referenced by MaterialiseValueNode().
LoadHeapNumberOrOddballValue()
void v8::internal::maglev::MaglevAssembler::LoadHeapNumberOrOddballValue (DoubleRegister result, Register object) [inline]
Definition at line 452 of file maglev-assembler-inl.h.
                                                                           {
  static_assert(offsetof(HeapNumber, value_) ==
                offsetof(Oddball, to_number_raw_));
  LoadHeapNumberValue(result, object);
}
References LoadHeapNumberValue(), and v8::base::internal::result.
LoadHeapNumberValue()
void v8::internal::maglev::MaglevAssembler::LoadHeapNumberValue (DoubleRegister result, Register heap_number) [inline]
Definition at line 1250 of file maglev-assembler-arm-inl.h.
                                                                       {
  vldr(result, FieldMemOperand(heap_number, offsetof(HeapNumber, value_)));
}
References v8::internal::FieldMemOperand(), v8::base::internal::result, and v8::internal::Assembler::vldr().
Referenced by LoadHeapNumberOrOddballValue().
LoadInstanceType()
void v8::internal::maglev::MaglevAssembler::LoadInstanceType (Register instance_type, Register heap_object) [inline]
Definition at line 735 of file maglev-assembler-arm-inl.h.
                                                                    {
  LoadMap(instance_type, heap_object);
  ldrh(instance_type, FieldMemOperand(instance_type, Map::kInstanceTypeOffset));
}
References v8::internal::FieldMemOperand(), v8::internal::Assembler::ldrh(), and v8::internal::MacroAssembler::LoadMap().
Referenced by LoadThinStringValue(), and StringCharCodeOrCodePointAt().
LoadInt32()
void v8::internal::maglev::MaglevAssembler::LoadInt32 (Register dst, MemOperand src) [inline]
Definition at line 587 of file maglev-assembler-arm-inl.h.
                                                                   {
  ldr(dst, src);
}
References v8::internal::Assembler::ldr().
Referenced by SeqOneByteStringCharCodeAt().
LoadMapForCompare()
void v8::internal::maglev::MaglevAssembler::LoadMapForCompare (Register dst, Register obj) [inline]
Definition at line 1073 of file maglev-assembler-inl.h.
                                                                  {
#ifdef V8_COMPRESS_POINTERS
  MacroAssembler::LoadCompressedMap(dst, obj);
#else
  MacroAssembler::LoadMap(dst, obj);
#endif
}
References v8::internal::MacroAssembler::LoadCompressedMap(), and v8::internal::MacroAssembler::LoadMap().
LoadSignedField()
void v8::internal::maglev::MaglevAssembler::LoadSignedField (Register result, MemOperand operand, int element_size) [inline]
Definition at line 384 of file maglev-assembler-arm-inl.h.
                                                                           {
  if (size == 1) {
    ldrsb(result, operand);
  } else if (size == 2) {
    ldrsh(result, operand);
  } else {
    DCHECK_EQ(size, 4);
    ldr(result, operand);
  }
}
References DCHECK_EQ, v8::internal::Assembler::ldr(), v8::internal::Assembler::ldrsb(), v8::internal::Assembler::ldrsh(), v8::base::internal::result, and size().
Referenced by StringLength().
LoadSingleCharacterString() [1/2]
void v8::internal::maglev::MaglevAssembler::LoadSingleCharacterString (Register result, int char_code)
Definition at line 59 of file maglev-assembler.cc.
                                                               {
  DCHECK_GE(char_code, 0);
  DCHECK_LT(char_code, String::kMaxOneByteCharCode);
  LoadRoot(result, RootsTable::SingleCharacterStringIndex(char_code));
}
References DCHECK_GE, DCHECK_LT, v8::internal::String::kMaxOneByteCharCode, v8::internal::MacroAssembler::LoadRoot(), v8::base::internal::result, and v8::internal::RootsTable::SingleCharacterStringIndex().
Referenced by StringFromCharCode().
LoadSingleCharacterString() [2/2]
void v8::internal::maglev::MaglevAssembler::LoadSingleCharacterString (Register result, Register char_code, Register scratch)
Definition at line 222 of file maglev-assembler-arm.cc.
                                                                  {
  DCHECK_NE(char_code, scratch);
  if (v8_flags.debug_code) {
    cmp(char_code, Operand(String::kMaxOneByteCharCode));
    Assert(kUnsignedLessThanEqual, AbortReason::kUnexpectedValue);
  }
  Register table = scratch;
  add(table, kRootRegister,
      Operand(RootRegisterOffsetForRootIndex(
          RootIndex::kFirstSingleCharacterString)));
  ldr(result, MemOperand(table, char_code, LSL, kSystemPointerSizeLog2));
}
References v8::internal::Assembler::add(), v8::internal::MacroAssembler::Assert(), v8::internal::Assembler::cmp(), DCHECK_NE, v8::internal::kFirstSingleCharacterString, v8::internal::String::kMaxOneByteCharCode, v8::internal::kRootRegister, v8::internal::kSystemPointerSizeLog2, v8::internal::kUnsignedLessThanEqual, v8::internal::Assembler::ldr(), v8::internal::LSL, v8::base::internal::result, v8::internal::MacroAssemblerBase::RootRegisterOffsetForRootIndex(), and v8::internal::v8_flags.
LoadTaggedField() [1/2]
void v8::internal::maglev::MaglevAssembler::LoadTaggedField (Register result, MemOperand operand) [inline]
Definition at line 425 of file maglev-assembler-inl.h.
                                                                 {
  MacroAssembler::LoadTaggedField(result, operand);
}
References v8::internal::MacroAssembler::LoadTaggedField(), and v8::base::internal::result.
Referenced by DeoptIfBufferDetached(), LoadContextCellTaggedValue(), LoadDataField(), LoadThinStringValue(), and StringCharCodeOrCodePointAt().
LoadTaggedField() [2/2]
void v8::internal::maglev::MaglevAssembler::LoadTaggedField (Register result, Register object, int offset) [inline]
Definition at line 430 of file maglev-assembler-inl.h.
                                                         {
  MacroAssembler::LoadTaggedField(result, FieldMemOperand(object, offset));
}
References v8::internal::FieldMemOperand(), v8::internal::MacroAssembler::LoadTaggedField(), and v8::base::internal::result.
LoadTaggedFieldByIndex()
void v8::internal::maglev::MaglevAssembler::LoadTaggedFieldByIndex (Register result, Register object, Register index, int scale, int offset) [inline]
Definition at line 325 of file maglev-assembler-arm-inl.h.
                                                                {
  add(result, object, Operand(index, LSL, ShiftFromScale(scale)));
  MacroAssembler::LoadTaggedField(result, FieldMemOperand(result, offset));
}
References v8::internal::Assembler::add(), v8::internal::FieldMemOperand(), v8::internal::index, v8::internal::MacroAssembler::LoadTaggedField(), v8::internal::LSL, v8::base::internal::result, and v8::internal::maglev::ShiftFromScale().
Referenced by LoadFixedArrayElement().
LoadTaggedFieldWithoutDecompressing()
void v8::internal::maglev::MaglevAssembler::LoadTaggedFieldWithoutDecompressing (Register result, Register object, int offset) [inline]
Definition at line 1366 of file maglev-assembler-arm-inl.h.
                                                  {
  MacroAssembler::LoadTaggedFieldWithoutDecompressing(
      result, FieldMemOperand(object, offset));
}
References v8::internal::FieldMemOperand(), v8::internal::MacroAssembler::LoadTaggedFieldWithoutDecompressing(), and v8::base::internal::result.
LoadTaggedSignedField() [1/2]
void v8::internal::maglev::MaglevAssembler::LoadTaggedSignedField (Register result, MemOperand operand) [inline]
Definition at line 435 of file maglev-assembler-inl.h.
                                                                       {
  MacroAssembler::LoadTaggedField(result, operand);
}
References v8::internal::MacroAssembler::LoadTaggedField(), and v8::base::internal::result.
LoadTaggedSignedField() [2/2]
void v8::internal::maglev::MaglevAssembler::LoadTaggedSignedField (Register result, Register object, int offset) [inline]
Definition at line 440 of file maglev-assembler-inl.h.
                                                               {
  MacroAssembler::LoadTaggedField(result, FieldMemOperand(object, offset));
}
References v8::internal::FieldMemOperand(), v8::internal::MacroAssembler::LoadTaggedField(), and v8::base::internal::result.
LoadThinStringValue()
void v8::internal::maglev::MaglevAssembler::LoadThinStringValue (Register result, Register string) [inline]
Definition at line 1058 of file maglev-assembler-inl.h.
                                                                  {
  if (v8_flags.slow_debug_code) {
    TemporaryRegisterScope temps(this);
    Register scratch = temps.AcquireScratch();
    LoadInstanceType(scratch, string);
    Label ok;
    static_assert(base::bits::CountPopulation(kThinStringTagBit) == 1);
    TestInt32AndJumpIfAnySet(scratch, kThinStringTagBit, &ok);
    Abort(AbortReason::kUnexpectedValue);
    bind(&ok);
  }
  LoadTaggedField(result, string, offsetof(ThinString, actual_));
}
References v8::internal::MacroAssembler::Abort(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::bind(), v8::base::bits::CountPopulation(), v8::internal::kThinStringTagBit, LoadInstanceType(), LoadTaggedField(), v8::base::internal::result, TestInt32AndJumpIfAnySet(), and v8::internal::v8_flags.
LoadUnalignedFloat64()
void v8::internal::maglev::MaglevAssembler::LoadUnalignedFloat64 (DoubleRegister dst, Register base, Register index) [inline]
Definition at line 619 of file maglev-assembler-arm-inl.h.
                                                                  {
  // vldr only works on 4 bytes aligned access.
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  ldr(scratch, MemOperand(base, index));
  VmovLow(dst, scratch);
  add(scratch, index, Operand(4));
  ldr(scratch, MemOperand(base, scratch));
  VmovHigh(dst, scratch);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::add(), v8::internal::index, v8::internal::Assembler::ldr(), v8::internal::MacroAssembler::VmovHigh(), and v8::internal::MacroAssembler::VmovLow().
LoadUnalignedFloat64AndReverseByteOrder()
void v8::internal::maglev::MaglevAssembler::LoadUnalignedFloat64AndReverseByteOrder (DoubleRegister dst, Register base, Register index) [inline]
Definition at line 631 of file maglev-assembler-arm-inl.h.
                                                       {
  // vldr only works on 4 bytes aligned access.
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  ldr(scratch, MemOperand(base, index));
  rev(scratch, scratch);
  VmovHigh(dst, scratch);
  add(scratch, index, Operand(4));
  ldr(scratch, MemOperand(base, scratch));
  rev(scratch, scratch);
  VmovLow(dst, scratch);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::add(), v8::internal::index, v8::internal::Assembler::ldr(), v8::internal::Assembler::rev(), v8::internal::MacroAssembler::VmovHigh(), and v8::internal::MacroAssembler::VmovLow().
LoadUnsignedField()
void v8::internal::maglev::MaglevAssembler::LoadUnsignedField (Register result, MemOperand operand, int element_size) [inline]
Definition at line 396 of file maglev-assembler-arm-inl.h.
                                                                             {
  if (size == 1) {
    ldrb(result, operand);
  } else if (size == 2) {
    ldrh(result, operand);
  } else {
    DCHECK_EQ(size, 4);
    ldr(result, operand);
  }
}
References DCHECK_EQ, v8::internal::Assembler::ldr(), v8::internal::Assembler::ldrb(), v8::internal::Assembler::ldrh(), v8::base::internal::result, and size().
MakeDeferredCode()
template<typename Function , typename... Args>
Label * v8::internal::maglev::MaglevAssembler::MakeDeferredCode (Function && deferred_code_gen, Args &&... args) [inline]
Definition at line 221 of file maglev-assembler-inl.h.
                                                                {
  using FunctionPointer =
      typename detail::FunctionArgumentsTupleHelper<Function>::FunctionPointer;
  static_assert(
      std::is_invocable_v<FunctionPointer, MaglevAssembler*,
                          decltype(detail::CopyForDeferred(
                              std::declval<MaglevCompilationInfo*>(),
                              std::declval<Args>()))...>,
      "Parameters of deferred_code_gen function should match arguments into "
      "MakeDeferredCode");
  TemporaryRegisterScope scratch_scope(this);
  using DeferredCodeInfoT = detail::DeferredCodeInfoImpl<Function>;
  DeferredCodeInfoT* deferred_code =
      compilation_info()->zone()->New<DeferredCodeInfoT>(
          compilation_info(), scratch_scope.CopyForDefer(), deferred_code_gen,
          std::forward<Args>(args)...);
#ifdef DEBUG
  deferred_code->set_allow_call(allow_deferred_call_);
  deferred_code->set_allow_allocate(allow_allocate_);
#endif // DEBUG
  code_gen_state()->PushDeferredCode(deferred_code);
  return &deferred_code->deferred_code_label;
}
References v8::base::args, code_gen_state(), compilation_info(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::CopyForDefer(), v8::internal::maglev::detail::CopyForDeferred(), v8::internal::Zone::New(), v8::internal::maglev::MaglevCodeGenState::PushDeferredCode(), and v8::internal::maglev::MaglevCompilationInfo::zone().
Referenced by AssertElidedWriteBarrier(), CheckAndEmitDeferredWriteBarrier(), JumpIfHoleNan(), StringCharCodeOrCodePointAt(), ToBoolean(), and TruncateDoubleToInt32().
MaterialiseValueNode()
void v8::internal::maglev::MaglevAssembler::MaterialiseValueNode (Register dst, ValueNode * value)
Definition at line 270 of file maglev-assembler.cc.
                                                                         {
  switch (value->opcode()) {
    case Opcode::kInt32Constant: {
      int32_t int_value = value->Cast<Int32Constant>()->value();
      if (Smi::IsValid(int_value)) {
        Move(dst, Smi::FromInt(int_value));
      } else {
        MoveHeapNumber(dst, int_value);
      }
      return;
    }
    case Opcode::kIntPtrConstant: {
      intptr_t intptr_value = value->Cast<IntPtrConstant>()->value();
      if (intptr_value <= std::numeric_limits<int>::max() &&
          Smi::IsValid(static_cast<int>(intptr_value))) {
        Move(dst, Smi::FromInt(static_cast<int>(intptr_value)));
      } else {
        MoveHeapNumber(dst, intptr_value);
      }
      return;
    }
    case Opcode::kUint32Constant: {
      uint32_t uint_value = value->Cast<Uint32Constant>()->value();
      if (Smi::IsValid(uint_value)) {
        Move(dst, Smi::FromInt(uint_value));
      } else {
        MoveHeapNumber(dst, uint_value);
      }
      return;
    }
    case Opcode::kFloat64Constant: {
      double double_value =
          value->Cast<Float64Constant>()->value().get_scalar();
      int smi_value;
      if (DoubleToSmiInteger(double_value, &smi_value)) {
        Move(dst, Smi::FromInt(smi_value));
      } else {
        MoveHeapNumber(dst, double_value);
      }
      return;
    }
    default:
      break;
  }
  DCHECK(!value->allocation().IsConstant());
  DCHECK(value->allocation().IsAnyStackSlot());
  using D = NewHeapNumberDescriptor;
  DoubleRegister builtin_input_value = D::GetDoubleRegisterParameter(D::kValue);
  MemOperand src = ToMemOperand(value->allocation());
  switch (value->properties().value_representation()) {
    case ValueRepresentation::kInt32: {
      Label done;
      TemporaryRegisterScope temps(this);
      Register scratch = temps.AcquireScratch();
      Move(scratch, src);
      SmiTagInt32AndJumpIfSuccess(dst, scratch, &done, Label::kNear);
      // If smi tagging fails, instead of bailing out (deopting), we change
      // representation to a HeapNumber.
      Int32ToDouble(builtin_input_value, scratch);
      CallBuiltin<Builtin::kNewHeapNumber>(builtin_input_value);
      Move(dst, kReturnRegister0);
      bind(&done);
      break;
    }
    case ValueRepresentation::kUint32: {
      Label done;
      TemporaryRegisterScope temps(this);
      Register scratch = temps.AcquireScratch();
      Move(scratch, src);
      SmiTagUint32AndJumpIfSuccess(dst, scratch, &done, Label::kNear);
      // If smi tagging fails, instead of bailing out (deopting), we change
      // representation to a HeapNumber.
      Uint32ToDouble(builtin_input_value, scratch);
      CallBuiltin<Builtin::kNewHeapNumber>(builtin_input_value);
      Move(dst, kReturnRegister0);
      bind(&done);
      break;
    }
    case ValueRepresentation::kFloat64:
      LoadFloat64(builtin_input_value, src);
      CallBuiltin<Builtin::kNewHeapNumber>(builtin_input_value);
      Move(dst, kReturnRegister0);
      break;
    case ValueRepresentation::kHoleyFloat64: {
      Label done, box;
      JumpIfNotHoleNan(src, &box, Label::kNear);
      LoadRoot(dst, RootIndex::kUndefinedValue);
      Jump(&done);
      bind(&box);
      LoadFloat64(builtin_input_value, src);
      CallBuiltin<Builtin::kNewHeapNumber>(builtin_input_value);
      Move(dst, kReturnRegister0);
      bind(&done);
      break;
    }
    case ValueRepresentation::kIntPtr: {
      Label done;
      TemporaryRegisterScope temps(this);
      Register scratch = temps.AcquireScratch();
      Move(scratch, src);
      SmiTagIntPtrAndJumpIfSuccess(dst, scratch, &done, Label::kNear);
      // If smi tagging fails, instead of bailing out (deopting), we change
      // representation to a HeapNumber.
      IntPtrToDouble(builtin_input_value, scratch);
      CallBuiltin<Builtin::kNewHeapNumber>(builtin_input_value);
      Move(dst, kReturnRegister0);
      bind(&done);
      break;
    }
    case ValueRepresentation::kTagged:
      UNREACHABLE();
  }
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::bind(), D, v8::internal::DCHECK(), v8::internal::DoubleToSmiInteger(), v8::internal::Smi::FromInt(), Int32ToDouble(), IntPtrToDouble(), v8::internal::Smi::IsValid(), Jump(), JumpIfNotHoleNan(), v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::Label::kNear, v8::internal::kReturnRegister0, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, LoadFloat64(), v8::internal::MacroAssembler::LoadRoot(), Move(), MoveHeapNumber(), SmiTagInt32AndJumpIfSuccess(), SmiTagIntPtrAndJumpIfSuccess(), SmiTagUint32AndJumpIfSuccess(), ToMemOperand(), Uint32ToDouble(), v8::internal::UNREACHABLE(), and v8::internal::value.
MaybeEmitDeoptBuiltinsCall()
void v8::internal::maglev::MaglevAssembler::MaybeEmitDeoptBuiltinsCall (size_t eager_deopt_count, Label * eager_deopt_entry, size_t lazy_deopt_count, Label * lazy_deopt_entry)
Definition at line 215 of file maglev-assembler-arm.cc.
                                                                          {
  CheckConstPool(true, false);
}
References v8::internal::Assembler::CheckConstPool().
MaybeEmitPlaceHolderForDeopt()
void v8::internal::maglev::MaglevAssembler::MaybeEmitPlaceHolderForDeopt () [inline]
Definition at line 1362 of file maglev-assembler-arm-inl.h.
                                                          {
  // Implemented only for x64.
}
Referenced by DefineLazyDeoptPoint(), and v8::internal::maglev::SaveRegisterStateForCall::DefineSafepointWithLazyDeopt().
Move() [1/17]
void v8::internal::maglev::MaglevAssembler::Move (DoubleRegister dst, double n) [inline]
Definition at line 574 of file maglev-assembler-arm-inl.h.
                                                              {
  vmov(dst, base::Double(n));
}
References v8::internal::Assembler::vmov().
Move() [2/17]
void v8::internal::maglev::MaglevAssembler::Move (DoubleRegister dst, DoubleRegister src) [inline]
Definition at line 549 of file maglev-assembler-arm-inl.h.
                                                                        {
  if (dst != src) {
    vmov(dst, src);
  }
}
References v8::internal::Assembler::vmov().
Move() [3/17]
void v8::internal::maglev::MaglevAssembler::Move (DoubleRegister dst, Float64 n) [inline]
Definition at line 577 of file maglev-assembler-arm-inl.h.
                                                               {
  vmov(dst, base::Double(n.get_bits()));
}
References v8::internal::Float64::get_bits(), and v8::internal::Assembler::vmov().
Move() [4/17]
void v8::internal::maglev::MaglevAssembler::Move (DoubleRegister dst, StackSlot src) [inline]
Definition at line 540 of file maglev-assembler-arm-inl.h.
                                                                   {
  vldr(dst, StackSlotOperand(src));
}
References StackSlotOperand(), and v8::internal::Assembler::vldr().
Move() [5/17]
void v8::internal::maglev::MaglevAssembler::Move (MemOperand dst, Register src) [inline]
Definition at line 543 of file maglev-assembler-arm-inl.h.
                                                              {
  str(src, dst);
}
References v8::internal::Assembler::str().
Move() [6/17]
void v8::internal::maglev::MaglevAssembler::Move (Register dst, ExternalReference src) [inline]
Definition at line 557 of file maglev-assembler-arm-inl.h.
                                                                     {
  MacroAssembler::Move(dst, src);
}
References v8::internal::MacroAssembler::Move().
Move() [7/17]
void v8::internal::maglev::MaglevAssembler::Move (Register dst, Handle< HeapObject > obj) [inline]
Definition at line 580 of file maglev-assembler-arm-inl.h.
                                                                      {
  MacroAssembler::Move(dst, obj);
}
References v8::internal::MacroAssembler::Move().
Move() [8/17]
void v8::internal::maglev::MaglevAssembler::Move (Register dst, IndirectPointerTag i) [inline]
Definition at line 771 of file maglev-assembler-arm64-inl.h.
                                                                    {
  Mov(dst, Immediate(i));
}
References v8::internal::MacroAssembler::Mov().
Move() [9/17]
void v8::internal::maglev::MaglevAssembler::Move (Register dst, int32_t i) [inline]
Definition at line 568 of file maglev-assembler-arm-inl.h.
                                                         {
  mov(dst, Operand(i));
}
References v8::internal::MacroAssembler::mov().
Move() [10/17]
void v8::internal::maglev::MaglevAssembler::Move (Register dst, MemOperand src) [inline]
Definition at line 546 of file maglev-assembler-arm-inl.h.
                                                              {
  ldr(dst, src);
}
References v8::internal::Assembler::ldr().
Move() [11/17]
void v8::internal::maglev::MaglevAssembler::Move (Register dst, Register src) [inline]
Definition at line 560 of file maglev-assembler-arm-inl.h.
                                                            {
  if (dst != src) {
    mov(dst, src);
  }
}
References v8::internal::MacroAssembler::mov().
Move() [12/17]
void v8::internal::maglev::MaglevAssembler::Move (Register dst, StackSlot src) [inline]
Definition at line 537 of file maglev-assembler-arm-inl.h.
                                                             {
  ldr(dst, StackSlotOperand(src));
}
References v8::internal::Assembler::ldr(), and StackSlotOperand().
Move() [13/17]
void v8::internal::maglev::MaglevAssembler::Move (Register dst, Tagged< Smi > src) [inline]
Definition at line 554 of file maglev-assembler-arm-inl.h.
                                                               {
  MacroAssembler::Move(dst, src);
}
References v8::internal::MacroAssembler::Move().
Move() [14/17]
void v8::internal::maglev::MaglevAssembler::Move (Register dst, Tagged< TaggedIndex > i) [inline]
Definition at line 565 of file maglev-assembler-arm-inl.h.
                                                                     {
  mov(dst, Operand(i.ptr()));
}
References v8::internal::MacroAssembler::mov().
Move() [15/17]
void v8::internal::maglev::MaglevAssembler::Move (Register dst, uint32_t i) [inline]
Definition at line 571 of file maglev-assembler-arm-inl.h.
                                                          {
  mov(dst, Operand(static_cast<int32_t>(i)));
}
References v8::internal::MacroAssembler::mov().
Move() [16/17]
void v8::internal::maglev::MaglevAssembler::Move (StackSlot dst, DoubleRegister src) [inline]
Definition at line 534 of file maglev-assembler-arm-inl.h.
                                                                   {
  vstr(src, StackSlotOperand(dst));
}
References StackSlotOperand(), and v8::internal::Assembler::vstr().
Move() [17/17]
void v8::internal::maglev::MaglevAssembler::Move (StackSlot dst, Register src) [inline]
Definition at line 531 of file maglev-assembler-arm-inl.h.
                                                             {
  str(src, StackSlotOperand(dst));
}
References StackSlotOperand(), and v8::internal::Assembler::str().
Referenced by v8::internal::maglev::AllocateSlow(), AssertElidedWriteBarrier(), CheckAndEmitDeferredWriteBarrier(), EnsureWritableFastElements(), FromAnyToRegister(), v8::internal::maglev::MapCompare::Generate(), LoadBoundedSizeFromObject(), LoadDataField(), LoadExternalPointerField(), MaterialiseValueNode(), v8::internal::maglev::detail::MoveArgumentsForBuiltin(), MoveRepr(), MoveTagged(), OSRPrologue(), Prologue(), SmiAddConstant(), SmiSubConstant(), StoreInt32Field(), StoreTaggedSignedField(), StringCharCodeOrCodePointAt(), StringFromCharCode(), v8::internal::maglev::detail::ToRegister(), ToUint8Clamped(), TryMigrateInstance(), and TryMigrateInstanceAndMarkMapAsMigrationTarget().
MoveHeapNumber()
void v8::internal::maglev::MaglevAssembler::MoveHeapNumber (Register dst, double value) [inline]
Definition at line 262 of file maglev-assembler-arm-inl.h.
                                                                      {
  mov(dst, Operand::EmbeddedNumber(value));
}
References v8::internal::Operand::EmbeddedNumber(), v8::internal::MacroAssembler::mov(), and v8::internal::value.
Referenced by MaterialiseValueNode().
MoveRepr() [1/5]
template<typename Dest , typename Source >
void v8::internal::maglev::MaglevAssembler::MoveRepr (MachineRepresentation repr, Dest dst, Source src) [inline]
Definition at line 1392 of file maglev-assembler-x64-inl.h.
                                                  {
  switch (repr) {
    case MachineRepresentation::kWord32:
      return movl(dst, src);
    case MachineRepresentation::kTagged:
    case MachineRepresentation::kTaggedPointer:
    case MachineRepresentation::kTaggedSigned:
    case MachineRepresentation::kWord64:
      return movq(dst, src);
    default:
      UNREACHABLE();
  }
}
References v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord32, v8::internal::kWord64, v8::internal::Assembler::movl(), v8::internal::Assembler::movq(), and v8::internal::UNREACHABLE().
Referenced by MoveRepr().
MoveRepr() [2/5]
template<>
void v8::internal::maglev::MaglevAssembler::MoveRepr (MachineRepresentation repr, MemOperand dst, MemOperand src) [inline]
Definition at line 1354 of file maglev-assembler-arm-inl.h.
                                                                      {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  MoveRepr(repr, scratch, src);
  MoveRepr(repr, dst, scratch);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), and MoveRepr().
MoveRepr() [3/5]
template<>
void v8::internal::maglev::MaglevAssembler::MoveRepr (MachineRepresentation repr, MemOperand dst, Register src) [inline]
Definition at line 1341 of file maglev-assembler-arm-inl.h.
                                                                    {
  switch (repr) {
    case MachineRepresentation::kWord32:
    case MachineRepresentation::kTagged:
    case MachineRepresentation::kTaggedPointer:
    case MachineRepresentation::kTaggedSigned:
      return str(src, dst);
    default:
      UNREACHABLE();
  }
}
References v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord32, v8::internal::Assembler::str(), and v8::internal::UNREACHABLE().
MoveRepr() [4/5]
template<>
void v8::internal::maglev::MaglevAssembler::MoveRepr (MachineRepresentation repr, Register dst, MemOperand src) [inline]
Definition at line 1328 of file maglev-assembler-arm-inl.h.
                                                      {
  switch (repr) {
    case MachineRepresentation::kWord32:
    case MachineRepresentation::kTagged:
    case MachineRepresentation::kTaggedPointer:
    case MachineRepresentation::kTaggedSigned:
      return ldr(dst, src);
    default:
      UNREACHABLE();
  }
}
References v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord32, v8::internal::Assembler::ldr(), and v8::internal::UNREACHABLE().
MoveRepr() [5/5]
template<>
void v8::internal::maglev::MaglevAssembler::MoveRepr (MachineRepresentation repr, Register dst, Register src) [inline]
Definition at line 1323 of file maglev-assembler-arm-inl.h.
                                                    {
  Move(dst, src);
}
References Move().
MoveTagged()
void v8::internal::maglev::MaglevAssembler::MoveTagged (Register dst, Handle< HeapObject > obj) [inline]
Definition at line 583 of file maglev-assembler-arm-inl.h.
                                                                            {
  Move(dst, obj);
}
References Move().
native_context()
compiler::NativeContextRef v8::internal::maglev::MaglevAssembler::native_context () const [inline]
Definition at line 822 of file maglev-assembler.h.
                                                  {
    return code_gen_state()->broker()->target_native_context();
  }
Referenced by AssertElidedWriteBarrier(), v8::internal::maglev::anonymous_namespace{maglev-ir-x64.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-riscv.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-s390.cc}::HandleInterruptsAndTiering(), StringCharCodeOrCodePointAt(), TryMigrateInstance(), and TryMigrateInstanceAndMarkMapAsMigrationTarget().
NegateInt32()
void v8::internal::maglev::MaglevAssembler::NegateInt32 (Register val) [inline]
Definition at line 675 of file maglev-assembler-arm-inl.h.
                                                     {
  rsb(val, val, Operand(0));
}
References v8::internal::Assembler::rsb().
OrInt32() [1/2]
void v8::internal::maglev::MaglevAssembler::OrInt32 (Register reg, int mask) [inline]
Definition at line 497 of file maglev-assembler-arm-inl.h.
                                                           {
  orr(reg, reg, Operand(mask));
}
References v8::internal::Assembler::orr().
OrInt32() [2/2]
void v8::internal::maglev::MaglevAssembler::OrInt32 (Register reg, Register other) [inline]
Definition at line 505 of file maglev-assembler-arm-inl.h.
                                                                 {
  orr(reg, reg, other);
}
References v8::internal::Assembler::orr().
OSRPrologue()
void v8::internal::maglev::MaglevAssembler::OSRPrologue (Graph * graph)
Definition at line 83 of file maglev-assembler-arm.cc.
                                              {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  DCHECK(graph->is_osr());
  CHECK(!graph->has_recursive_calls());
  uint32_t source_frame_size =
      graph->min_maglev_stackslots_for_unoptimized_frame_size();
  if (v8_flags.debug_code) {
    add(scratch, sp,
        Operand(source_frame_size * kSystemPointerSize +
                StandardFrameConstants::kFixedFrameSizeFromFp));
    cmp(scratch, fp);
    Assert(eq, AbortReason::kOsrUnexpectedStackSize);
  }
  uint32_t target_frame_size =
      graph->tagged_stack_slots() + graph->untagged_stack_slots();
  CHECK_LE(source_frame_size, target_frame_size);
  if (source_frame_size < target_frame_size) {
    ASM_CODE_COMMENT_STRING(this, "Growing frame for OSR");
    uint32_t additional_tagged =
        source_frame_size < graph->tagged_stack_slots()
            ? graph->tagged_stack_slots() - source_frame_size
            : 0;
    if (additional_tagged) {
      Move(scratch, 0);
    }
    for (size_t i = 0; i < additional_tagged; ++i) {
      Push(scratch);
    }
    uint32_t size_so_far = source_frame_size + additional_tagged;
    CHECK_LE(size_so_far, target_frame_size);
    if (size_so_far < target_frame_size) {
      sub(sp, sp,
          Operand((target_frame_size - size_so_far) * kSystemPointerSize));
    }
  }
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::add(), ASM_CODE_COMMENT_STRING, v8::internal::MacroAssembler::Assert(), CHECK, CHECK_LE, v8::internal::Assembler::cmp(), v8::internal::DCHECK(), v8::internal::eq, graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::StandardFrameConstants::kFixedFrameSizeFromFp, v8::internal::kSystemPointerSize, Move(), Push(), v8::internal::Assembler::sub(), and v8::internal::v8_flags.
Pop() [1/32]
void v8::internal::MacroAssembler::Pop
Pop() [2/32]
template<LoadLRMode lr_mode = kDontLoadLR>
void v8::internal::MacroAssembler::Pop (LoadLRMode lr_mode = kDontLoadLR)
Definition at line 928 of file macro-assembler-arm64-inl.h.
                                                                           {
  // It is not valid to pop into the same register more than once in one
  // instruction, not even into the zero register.
  DCHECK(!AreAliased(dst0, dst1, dst2, dst3));
  DCHECK(AreSameSizeAndType(dst0, dst1, dst2, dst3));
  DCHECK(dst0.is_valid());
  int count = 1 + dst1.is_valid() + dst2.is_valid() + dst3.is_valid();
  int size = dst0.SizeInBytes();
  DCHECK_EQ(0, (size * count) % 16);
  PopHelper(count, size, dst0, dst1, dst2, dst3);
  DCHECK_IMPLIES((lr_mode == kAuthLR), ((dst0 == lr) || (dst1 == lr) ||
                                        (dst2 == lr) || (dst3 == lr)));
  DCHECK_IMPLIES((lr_mode == kDontLoadLR), ((dst0 != lr) && (dst1 != lr)) &&
                                               (dst2 != lr) && (dst3 != lr));
#ifdef V8_ENABLE_CONTROL_FLOW_INTEGRITY
  if (lr_mode == kAuthLR) {
    Autibsp();
  }
#endif
}
Pop() [3/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 386 of file macro-assembler-ia32.h.
{ pop(dst); }
Pop() [4/32]
void v8::internal::MacroAssembler::Pop
Pop() [5/32]
void v8::internal::maglev::MaglevAssembler::Pop (Register dst) [inline]
Definition at line 1286 of file maglev-assembler-arm-inl.h.
{ pop(dst); }
References v8::internal::MacroAssembler::pop().
Pop() [6/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 175 of file macro-assembler-arm.h.
{ pop(dst); }
Pop() [7/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 393 of file macro-assembler-loong64.h.
                         {
    Ld_d(dst, MemOperand(sp, 0));
    Add_d(sp, sp, Operand(kSystemPointerSize));
  }
Pop() [8/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 430 of file macro-assembler-mips64.h.
{ pop(dst); }
Pop() [9/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 496 of file macro-assembler-ppc.h.
{ pop(dst); }
Pop() [10/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 542 of file macro-assembler-riscv.h.
{ pop(dst); }
Pop() [11/32]
void v8::internal::MacroAssembler::Pop
Pop() [12/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 385 of file macro-assembler-ia32.h.
{ pop(dst); }
Pop() [13/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 723 of file macro-assembler-s390.h.
{ pop(dst); }
Pop() [14/32]
template<typename... Rs>
void v8::internal::MacroAssembler::Pop (typename... Rs) [inline]
Definition at line 557 of file macro-assembler-riscv.h.
                                 {
    pop_helper(r, rs...);
    AddWord(sp, sp, (sizeof...(rs) + 1) * kSystemPointerSize);
  }
Pop() [15/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 499 of file macro-assembler-ppc.h.
                                         {
    LoadU64(src2, MemOperand(sp, 0));
    LoadU64(src1, MemOperand(sp, kSystemPointerSize));
    addi(sp, sp, Operand(2 * kSystemPointerSize));
  }
Pop() [16/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 433 of file macro-assembler-mips64.h.
                                         {
    DCHECK(src1 != src2);
    Ld(src2, MemOperand(sp, 0 * kPointerSize));
    Ld(src1, MemOperand(sp, 1 * kPointerSize));
    Daddu(sp, sp, 2 * kPointerSize);
  }
Pop() [17/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 726 of file macro-assembler-s390.h.
                                         {
    LoadU64(src2, MemOperand(sp, 0));
    LoadU64(src1, MemOperand(sp, kSystemPointerSize));
    la(sp, MemOperand(sp, 2 * kSystemPointerSize));
  }
Pop() [18/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 399 of file macro-assembler-loong64.h.
                                         {
    DCHECK(src1 != src2);
    Ld_d(src2, MemOperand(sp, 0 * kSystemPointerSize));
    Ld_d(src1, MemOperand(sp, 1 * kSystemPointerSize));
    Add_d(sp, sp, 2 * kSystemPointerSize);
  }
Pop() [19/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 178 of file macro-assembler-arm.h.
                                                              {
    DCHECK(src1 != src2);
    if (src1.code() > src2.code()) {
      ldm(ia_w, sp, {src1, src2}, cond);
    } else {
      ldr(src2, MemOperand(sp, 4, PostIndex), cond);
      ldr(src1, MemOperand(sp, 4, PostIndex), cond);
    }
  }
Pop() [20/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 733 of file macro-assembler-s390.h.
                                                        {
    LoadU64(src3, MemOperand(sp, 0));
    LoadU64(src2, MemOperand(sp, kSystemPointerSize));
    LoadU64(src1, MemOperand(sp, 2 * kSystemPointerSize));
    la(sp, MemOperand(sp, 3 * kSystemPointerSize));
  }
Pop() [21/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 506 of file macro-assembler-ppc.h.
                                                        {
    LoadU64(src3, MemOperand(sp, 0));
    LoadU64(src2, MemOperand(sp, kSystemPointerSize));
    LoadU64(src1, MemOperand(sp, 2 * kSystemPointerSize));
    addi(sp, sp, Operand(3 * kSystemPointerSize));
  }
Pop() [22/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 407 of file macro-assembler-loong64.h.
                                                        {
    Ld_d(src3, MemOperand(sp, 0 * kSystemPointerSize));
    Ld_d(src2, MemOperand(sp, 1 * kSystemPointerSize));
    Ld_d(src1, MemOperand(sp, 2 * kSystemPointerSize));
    Add_d(sp, sp, 3 * kSystemPointerSize);
  }
Pop() [23/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 441 of file macro-assembler-mips64.h.
                                                        {
    Ld(src3, MemOperand(sp, 0 * kPointerSize));
    Ld(src2, MemOperand(sp, 1 * kPointerSize));
    Ld(src1, MemOperand(sp, 2 * kPointerSize));
    Daddu(sp, sp, 3 * kPointerSize);
  }
Pop() [24/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 189 of file macro-assembler-arm.h.
                                                                             {
    DCHECK(!AreAliased(src1, src2, src3));
    if (src1.code() > src2.code()) {
      if (src2.code() > src3.code()) {
        ldm(ia_w, sp, {src1, src2, src3}, cond);
      } else {
        ldr(src3, MemOperand(sp, 4, PostIndex), cond);
        ldm(ia_w, sp, {src1, src2}, cond);
      }
    } else {
      Pop(src2, src3, cond);
      ldr(src1, MemOperand(sp, 4, PostIndex), cond);
    }
  }
Pop() [25/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 514 of file macro-assembler-ppc.h.
                                                                       {
    LoadU64(src4, MemOperand(sp, 0));
    LoadU64(src3, MemOperand(sp, kSystemPointerSize));
    LoadU64(src2, MemOperand(sp, 2 * kSystemPointerSize));
    LoadU64(src1, MemOperand(sp, 3 * kSystemPointerSize));
    addi(sp, sp, Operand(4 * kSystemPointerSize));
  }
Pop() [26/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 741 of file macro-assembler-s390.h.
                                                                       {
    LoadU64(src4, MemOperand(sp, 0));
    LoadU64(src3, MemOperand(sp, kSystemPointerSize));
    LoadU64(src2, MemOperand(sp, 2 * kSystemPointerSize));
    LoadU64(src1, MemOperand(sp, 3 * kSystemPointerSize));
    la(sp, MemOperand(sp, 4 * kSystemPointerSize));
  }
Pop() [27/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 205 of file macro-assembler-arm.h.
                                {
    DCHECK(!AreAliased(src1, src2, src3, src4));
    if (src1.code() > src2.code()) {
      if (src2.code() > src3.code()) {
        if (src3.code() > src4.code()) {
          ldm(ia_w, sp, {src1, src2, src3, src4}, cond);
        } else {
          ldr(src4, MemOperand(sp, 4, PostIndex), cond);
          ldm(ia_w, sp, {src1, src2, src3}, cond);
        }
      } else {
        Pop(src3, src4, cond);
        ldm(ia_w, sp, {src1, src2}, cond);
      }
    } else {
      Pop(src2, src3, src4, cond);
      ldr(src1, MemOperand(sp, 4, PostIndex), cond);
    }
  }
Pop() [28/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 523 of file macro-assembler-ppc.h.
                          {
    LoadU64(src5, MemOperand(sp, 0));
    LoadU64(src4, MemOperand(sp, kSystemPointerSize));
    LoadU64(src3, MemOperand(sp, 2 * kSystemPointerSize));
    LoadU64(src2, MemOperand(sp, 3 * kSystemPointerSize));
    LoadU64(src1, MemOperand(sp, 4 * kSystemPointerSize));
    addi(sp, sp, Operand(5 * kSystemPointerSize));
  }
Pop() [29/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 750 of file macro-assembler-s390.h.
                          {
    LoadU64(src5, MemOperand(sp, 0));
    LoadU64(src4, MemOperand(sp, kSystemPointerSize));
    LoadU64(src3, MemOperand(sp, 2 * kSystemPointerSize));
    LoadU64(src2, MemOperand(sp, 3 * kSystemPointerSize));
    LoadU64(src1, MemOperand(sp, 4 * kSystemPointerSize));
    la(sp, MemOperand(sp, 5 * kSystemPointerSize));
  }
Pop() [30/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 562 of file macro-assembler-riscv.h.
                               {
    AddWord(sp, sp, Operand(count * kSystemPointerSize));
  }
Pop() [31/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 448 of file macro-assembler-mips64.h.
{ Daddu(sp, sp, Operand(count * kPointerSize)); }
Pop() [32/32]
void v8::internal::MacroAssembler::Pop [inline]
Definition at line 387 of file macro-assembler-ia32.h.
                                              {
    pop(scratch);
    movd(dst, scratch);
  }
PrepareCallCFunction()
void v8::internal::maglev::MaglevAssembler::PrepareCallCFunction (int num_reg_arguments, int num_double_registers = 0) [inline]
Definition at line 881 of file maglev-assembler-arm-inl.h.
                                                                            {
  MacroAssembler::PrepareCallCFunction(num_reg_arguments, num_double_registers);
}
References v8::internal::MacroAssembler::PrepareCallCFunction().
Prologue()
void v8::internal::maglev::MaglevAssembler::Prologue (Graph * graph)
Definition at line 126 of file maglev-assembler-arm.cc.
                                           {
  TemporaryRegisterScope temps(this);
  temps.Include({r4, r8});
  DCHECK(!graph->is_osr());
  BailoutIfDeoptimized();
  if (graph->has_recursive_calls()) {
    bind(code_gen_state()->entry_label());
  }
#ifndef V8_ENABLE_LEAPTIERING
  // Tiering support.
  if (v8_flags.turbofan) {
    using D = MaglevOptimizeCodeOrTailCallOptimizedCodeSlotDescriptor;
    Register flags = D::GetRegisterParameter(D::kFlags);
    Register feedback_vector = D::GetRegisterParameter(D::kFeedbackVector);
    DCHECK(!AreAliased(flags, feedback_vector, kJavaScriptCallArgCountRegister,
                       kJSFunctionRegister, kContextRegister,
                       kJavaScriptCallNewTargetRegister));
    DCHECK(!temps.Available().has(flags));
    DCHECK(!temps.Available().has(feedback_vector));
    Move(feedback_vector,
         compilation_info()->toplevel_compilation_unit()->feedback().object());
    Condition needs_processing =
        LoadFeedbackVectorFlagsAndCheckIfNeedsProcessing(flags, feedback_vector,
                                                         CodeKind::MAGLEV);
    // Tail call on Arm produces 3 instructions, so we emit that in deferred
    // code.
    JumpToDeferredIf(needs_processing, [](MaglevAssembler* masm) {
      __ TailCallBuiltin(
          Builtin::kMaglevOptimizeCodeOrTailCallOptimizedCodeSlot);
    });
  }
#endif // !V8_ENABLE_LEAPTIERING
  EnterFrame(StackFrame::MAGLEV);
  // Save arguments in frame.
  // TODO(leszeks): Consider eliding this frame if we don't make any calls
  // that could clobber these registers.
  Push(kContextRegister);
  Push(kJSFunctionRegister); // Callee's JS function.
  Push(kJavaScriptCallArgCountRegister); // Actual argument count.
  // Initialize stack slots.
  if (graph->tagged_stack_slots() > 0) {
    ASM_CODE_COMMENT_STRING(this, "Initializing stack slots");
    TemporaryRegisterScope temps(this);
    Register scratch = temps.AcquireScratch();
    Move(scratch, 0);
    // Magic value. Experimentally, an unroll size of 8 doesn't seem any
    // worse than fully unrolled pushes.
    const int kLoopUnrollSize = 8;
    int tagged_slots = graph->tagged_stack_slots();
    if (tagged_slots < kLoopUnrollSize) {
      // If the frame is small enough, just unroll the frame fill
      // completely.
      for (int i = 0; i < tagged_slots; ++i) {
        Push(scratch);
      }
    } else {
      // Extract the first few slots to round to the unroll size.
      int first_slots = tagged_slots % kLoopUnrollSize;
      for (int i = 0; i < first_slots; ++i) {
        Push(scratch);
      }
      Register unroll_counter = temps.AcquireScratch();
      Move(unroll_counter, tagged_slots / kLoopUnrollSize);
      // We enter the loop unconditionally, so make sure we need to loop at
      // least once.
      DCHECK_GT(tagged_slots / kLoopUnrollSize, 0);
      Label loop;
      bind(&loop);
      for (int i = 0; i < kLoopUnrollSize; ++i) {
        Push(scratch);
      }
      sub(unroll_counter, unroll_counter, Operand(1), SetCC);
      b(kGreaterThan, &loop);
    }
  }
  if (graph->untagged_stack_slots() > 0) {
    // Extend rsp by the size of the remaining untagged part of the frame,
    // no need to initialise these.
    sub(sp, sp, Operand(graph->untagged_stack_slots() * kSystemPointerSize));
  }
}
References __, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::AreAliased(), ASM_CODE_COMMENT_STRING, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Available(), v8::internal::Assembler::b(), v8::internal::MacroAssembler::BailoutIfDeoptimized(), v8::internal::Assembler::bind(), code_gen_state(), compilation_info(), D, v8::internal::DCHECK(), DCHECK_GT, v8::internal::MacroAssembler::EnterFrame(), v8::internal::flags, graph(), v8::internal::RegListBase< RegisterT >::has(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Include(), JumpToDeferredIf(), v8::internal::kContextRegister, v8::internal::kGreaterThan, v8::internal::kJavaScriptCallArgCountRegister, v8::internal::kJavaScriptCallNewTargetRegister, v8::internal::kJSFunctionRegister, v8::internal::kSystemPointerSize, v8::internal::MacroAssembler::LoadFeedbackVectorFlagsAndCheckIfNeedsProcessing(), Move(), Push(), v8::internal::SetCC, v8::internal::Assembler::sub(), v8::internal::MacroAssembler::TailCallBuiltin(), and v8::internal::v8_flags.
Push()
template<typename... T>
void v8::internal::maglev::MaglevAssembler::Push (T... vals) [inline]
Definition at line 204 of file maglev-assembler-arm-inl.h.
                                    {
  detail::PushAllHelper<T...>::Push(this, vals...);
}
Referenced by AssertElidedWriteBarrier(), OSRPrologue(), Prologue(), v8::internal::maglev::detail::PushArgumentsForBuiltin(), v8::internal::maglev::detail::PushInput(), v8::internal::maglev::detail::PushIterator(), v8::internal::maglev::detail::PushIteratorReverse(), v8::internal::maglev::detail::PushAllHelper< Arg, Args... >::PushReverse(), StringCharCodeOrCodePointAt(), TryMigrateInstance(), and TryMigrateInstanceAndMarkMapAsMigrationTarget().
PushReverse()
template<typename... T>
void v8::internal::maglev::MaglevAssembler::PushReverse (T... vals) [inline]
Definition at line 209 of file maglev-assembler-arm-inl.h.
                                           {
  detail::PushAllHelper<T...>::PushReverse(this, vals...);
}
Referenced by v8::internal::maglev::detail::PushArgumentsForBuiltin().
ReverseByteOrder()
void v8::internal::maglev::MaglevAssembler::ReverseByteOrder (Register value, int element_size) [inline]
Definition at line 470 of file maglev-assembler-arm-inl.h.
                                                                      {
  if (size == 2) {
    rev(value, value);
    asr(value, value, Operand(16));
  } else if (size == 4) {
    rev(value, value);
  } else {
    DCHECK_EQ(size, 1);
  }
}
References v8::internal::Assembler::asr(), DCHECK_EQ, v8::internal::Assembler::rev(), size(), and v8::internal::value.
ReverseByteOrderAndStoreUnalignedFloat64()
void v8::internal::maglev::MaglevAssembler::ReverseByteOrderAndStoreUnalignedFloat64 (Register base, Register index, DoubleRegister src) [inline]
Definition at line 657 of file maglev-assembler-arm-inl.h.
                                                       {
  // vstr only works on 4 bytes aligned access.
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  Register index_scratch = temps.AcquireScratch();
  VmovHigh(scratch, src);
  rev(scratch, scratch);
  str(scratch, MemOperand(base, index));
  add(index_scratch, index, Operand(4));
  VmovLow(scratch, src);
  rev(scratch, scratch);
  str(scratch, MemOperand(base, index_scratch));
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::add(), v8::internal::index, v8::internal::Assembler::rev(), v8::internal::Assembler::str(), v8::internal::MacroAssembler::VmovHigh(), and v8::internal::MacroAssembler::VmovLow().
safepoint_table_builder()
MaglevSafepointTableBuilder* v8::internal::maglev::MaglevAssembler::safepoint_table_builder () const [inline]
Definition at line 827 of file maglev-assembler.h.
                                                               {
    return code_gen_state()->safepoint_table_builder();
  }
Referenced by DefineLazyDeoptPoint(), and v8::internal::maglev::SaveRegisterStateForCall::DefineSafepoint().
scratch_register_scope()
TemporaryRegisterScope* v8::internal::maglev::MaglevAssembler::scratch_register_scope () const [inline]
Definition at line 834 of file maglev-assembler.h.
                                                         {
    return scratch_register_scope_;
  }
Referenced by v8::internal::maglev::MapCompare::MapCompare().
SeqOneByteStringCharCodeAt()
void v8::internal::maglev::MaglevAssembler::SeqOneByteStringCharCodeAt (Register result, Register string, Register index)
Definition at line 462 of file maglev-assembler-arm.cc.
                                                                 {
  ASM_CODE_COMMENT(this);
  if (v8_flags.debug_code) {
    TemporaryRegisterScope scope(this);
    Register scratch = scope.AcquireScratch();
    // Check if {string} is a string.
    AssertNotSmi(string);
    LoadMap(scratch, string);
    CompareInstanceTypeRange(scratch, scratch, FIRST_STRING_TYPE,
                             LAST_STRING_TYPE);
    Check(kUnsignedLessThanEqual, AbortReason::kUnexpectedValue);
    // Check if {string} is a sequential one-byte string.
    AndInt32(scratch, kStringRepresentationAndEncodingMask);
    CompareInt32AndAssert(scratch, kSeqOneByteStringTag, kEqual,
                          AbortReason::kUnexpectedValue);
    LoadInt32(scratch, FieldMemOperand(string, offsetof(String, length_)));
    CompareInt32AndAssert(index, scratch, kUnsignedLessThan,
                          AbortReason::kUnexpectedValue);
  }
  TemporaryRegisterScope scope(this);
  Register scratch = scope.AcquireScratch();
  add(scratch, index,
      Operand(OFFSET_OF_DATA_START(SeqOneByteString) - kHeapObjectTag));
  ldrb(result, MemOperand(string, scratch));
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::add(), AndInt32(), ASM_CODE_COMMENT, v8::internal::MacroAssembler::AssertNotSmi(), v8::internal::MacroAssembler::Check(), CompareInstanceTypeRange(), CompareInt32AndAssert(), v8::internal::FieldMemOperand(), v8::internal::index, v8::internal::kEqual, v8::internal::kHeapObjectTag, v8::internal::kSeqOneByteStringTag, v8::internal::kStringRepresentationAndEncodingMask, v8::internal::kUnsignedLessThan, v8::internal::kUnsignedLessThanEqual, v8::internal::LAST_STRING_TYPE, v8::internal::Assembler::ldrb(), LoadInt32(), v8::internal::MacroAssembler::LoadMap(), OFFSET_OF_DATA_START, v8::base::internal::result, and v8::internal::v8_flags.
Referenced by StringCharCodeOrCodePointAt().
SetMapAsRoot()
void v8::internal::maglev::MaglevAssembler::SetMapAsRoot (Register object, RootIndex map) [inline]
Definition at line 804 of file maglev-assembler-inl.h.
                                                                        {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  LoadTaggedRoot(scratch, map);
  StoreTaggedFieldNoWriteBarrier(object, HeapObject::kMapOffset, scratch);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::HeapObject::kMapOffset, v8::internal::MacroAssembler::LoadTaggedRoot(), and StoreTaggedFieldNoWriteBarrier().
Referenced by AllocateHeapNumber(), and AllocateTwoByteString().
SetSlotAddressForFixedArrayElement()
void v8::internal::maglev::MaglevAssembler::SetSlotAddressForFixedArrayElement (Register slot_reg, Register object, Register index) [inline]
Definition at line 413 of file maglev-assembler-arm-inl.h.
                                                        {
  add(slot_reg, object,
      Operand(OFFSET_OF_DATA_START(FixedArray) - kHeapObjectTag));
  add(slot_reg, slot_reg, Operand(index, LSL, kTaggedSizeLog2));
}
References v8::internal::Assembler::add(), v8::internal::index, v8::internal::kHeapObjectTag, v8::internal::kTaggedSizeLog2, v8::internal::LSL, and OFFSET_OF_DATA_START.
Referenced by CheckAndEmitDeferredWriteBarrier().
SetSlotAddressForTaggedField()
void v8::internal::maglev::MaglevAssembler::SetSlotAddressForTaggedField (Register slot_reg, Register object, int offset) [inline]
Definition at line 408 of file maglev-assembler-arm-inl.h.
                                                                      {
  add(slot_reg, object, Operand(offset - kHeapObjectTag));
}
References v8::internal::Assembler::add(), and v8::internal::kHeapObjectTag.
Referenced by CheckAndEmitDeferredWriteBarrier().
ShiftLeft()
void v8::internal::maglev::MaglevAssembler::ShiftLeft (Register reg, int amount) [inline]
Definition at line 509 of file maglev-assembler-arm-inl.h.
                                                               {
  lsl(reg, reg, Operand(amount));
}
References v8::internal::Assembler::lsl().
SignExtend32To64Bits()
void v8::internal::maglev::MaglevAssembler::SignExtend32To64Bits (Register dst, Register src) [inline]
Definition at line 672 of file maglev-assembler-arm-inl.h.
                                                                            {
  // No 64-bit registers.
}
SmiAddConstant() [1/2]
void v8::internal::maglev::MaglevAssembler::SmiAddConstant (Register dst, Register src, int value, Label * fail, Label::Distance distance = Label::kFar) [inline]
Definition at line 236 of file maglev-assembler-arm-inl.h.
                                                                    {
  static_assert(!SmiValuesAre32Bits());
  AssertSmi(src);
  if (value != 0) {
    add(dst, src, Operand(Smi::FromInt(value)), SetCC);
    JumpIf(kOverflow, fail, distance);
  } else {
    Move(dst, src);
  }
}
References v8::internal::Assembler::add(), v8::internal::MacroAssembler::AssertSmi(), v8::internal::Smi::FromInt(), JumpIf(), v8::internal::kOverflow, Move(), v8::internal::SetCC, v8::internal::SmiValuesAre32Bits(), and v8::internal::value.
Referenced by SmiAddConstant().
SmiAddConstant() [2/2]
void v8::internal::maglev::MaglevAssembler::SmiAddConstant (Register reg, int value, Label * fail, Label::Distance distance = Label::kFar) [inline]
Definition at line 922 of file maglev-assembler-inl.h.
                                                                    {
  return SmiAddConstant(reg, reg, value, fail, distance);
}
References SmiAddConstant(), and v8::internal::value.
SmiSubConstant() [1/2]
void v8::internal::maglev::MaglevAssembler::SmiSubConstant (Register dst, Register src, int value, Label * fail, Label::Distance distance = Label::kFar) [inline]
Definition at line 249 of file maglev-assembler-arm-inl.h.
                                                                    {
  static_assert(!SmiValuesAre32Bits());
  AssertSmi(src);
  if (value != 0) {
    sub(dst, src, Operand(Smi::FromInt(value)), SetCC);
    JumpIf(kOverflow, fail, distance);
  } else {
    Move(dst, src);
  }
}
References v8::internal::MacroAssembler::AssertSmi(), v8::internal::Smi::FromInt(), JumpIf(), v8::internal::kOverflow, Move(), v8::internal::SetCC, v8::internal::SmiValuesAre32Bits(), v8::internal::Assembler::sub(), and v8::internal::value.
Referenced by SmiSubConstant().
SmiSubConstant() [2/2]
void v8::internal::maglev::MaglevAssembler::SmiSubConstant (Register reg, int value, Label * fail, Label::Distance distance = Label::kFar) [inline]
Definition at line 928 of file maglev-assembler-inl.h.
                                                                    {
  return SmiSubConstant(reg, reg, value, fail, distance);
}
References SmiSubConstant(), and v8::internal::value.
SmiTagInt32AndJumpIfFail() [1/2]
void v8::internal::maglev::MaglevAssembler::SmiTagInt32AndJumpIfFail (Register dst, Register src, Label * fail, Label::Distance distance = Label::kFar) [inline]
Definition at line 811 of file maglev-assembler-inl.h.
                                                                     {
  SmiTagInt32AndSetFlags(dst, src);
  if (!SmiValuesAre32Bits()) {
    JumpIf(kOverflow, fail, distance);
  }
}
References JumpIf(), v8::internal::kOverflow, SmiTagInt32AndSetFlags(), and v8::internal::SmiValuesAre32Bits().
Referenced by SmiTagInt32AndJumpIfFail().
SmiTagInt32AndJumpIfFail() [2/2]
void v8::internal::maglev::MaglevAssembler::SmiTagInt32AndJumpIfFail (Register reg, Label * fail, Label::Distance distance = Label::kFar) [inline]
Definition at line 819 of file maglev-assembler-inl.h.
                                                       {
  SmiTagInt32AndJumpIfFail(reg, reg, fail, distance);
}
References SmiTagInt32AndJumpIfFail().
SmiTagInt32AndJumpIfSuccess() [1/2]
void v8::internal::maglev::MaglevAssembler::SmiTagInt32AndJumpIfSuccess (Register dst, Register src, Label * success, Label::Distance distance = Label::kFar) [inline]
Definition at line 824 of file maglev-assembler-inl.h.
                                                                        {
  SmiTagInt32AndSetFlags(dst, src);
  if (!SmiValuesAre32Bits()) {
    JumpIf(kNoOverflow, success, distance);
  } else {
    jmp(success);
  }
}
References v8::internal::MacroAssembler::jmp(), JumpIf(), v8::internal::kNoOverflow, SmiTagInt32AndSetFlags(), and v8::internal::SmiValuesAre32Bits().
Referenced by MaterialiseValueNode(), and SmiTagInt32AndJumpIfSuccess().
SmiTagInt32AndJumpIfSuccess() [2/2]
void v8::internal::maglev::MaglevAssembler::SmiTagInt32AndJumpIfSuccess (Register reg, Label * success, Label::Distance distance = Label::kFar) [inline]
Definition at line 834 of file maglev-assembler-inl.h.
                                                          {
  SmiTagInt32AndJumpIfSuccess(reg, reg, success, distance);
}
References SmiTagInt32AndJumpIfSuccess().
SmiTagInt32AndSetFlags()
void v8::internal::maglev::MaglevAssembler::SmiTagInt32AndSetFlags (Register dst, Register src) [inline], [private]
Definition at line 219 of file maglev-assembler-arm-inl.h.
                                                                  {
  add(dst, src, src, SetCC);
}
References v8::internal::Assembler::add(), and v8::internal::SetCC.
Referenced by SmiTagInt32AndJumpIfFail(), SmiTagInt32AndJumpIfSuccess(), SmiTagIntPtrAndJumpIfFail(), SmiTagUint32AndJumpIfFail(), UncheckedSmiTagInt32(), and UncheckedSmiTagUint32().
SmiTagIntPtrAndJumpIfFail()
void v8::internal::maglev::MaglevAssembler::SmiTagIntPtrAndJumpIfFail (Register dst, Register src, Label * fail, Label::Distance distance = Label::kFar) [inline]
Definition at line 866 of file maglev-assembler-inl.h.
                                                                     {
  CheckIntPtrIsSmi(src, fail, distance);
  // If the IntPtr is in the Smi range, we can treat it as Int32.
  SmiTagInt32AndSetFlags(dst, src);
  if (!SmiValuesAre32Bits()) {
    Assert(kNoOverflow, AbortReason::kInputDoesNotFitSmi);
  }
}
References v8::internal::MacroAssembler::Assert(), CheckIntPtrIsSmi(), v8::internal::kNoOverflow, SmiTagInt32AndSetFlags(), and v8::internal::SmiValuesAre32Bits().
Referenced by SmiTagIntPtrAndJumpIfSuccess().
SmiTagIntPtrAndJumpIfSuccess()
void v8::internal::maglev::MaglevAssembler::SmiTagIntPtrAndJumpIfSuccess (Register dst, Register src, Label * success, Label::Distance distance = Label::kFar) [inline]
Definition at line 876 of file maglev-assembler-inl.h.
                                                                        {
  Label done;
  SmiTagIntPtrAndJumpIfFail(dst, src, &done);
  Jump(success, distance);
  bind(&done);
}
References v8::internal::Assembler::bind(), Jump(), and SmiTagIntPtrAndJumpIfFail().
Referenced by MaterialiseValueNode().
SmiTagUint32AndJumpIfFail() [1/2]
void v8::internal::maglev::MaglevAssembler::SmiTagUint32AndJumpIfFail (Register dst, Register src, Label * fail, Label::Distance distance = Label::kFar) [inline]
Definition at line 850 of file maglev-assembler-inl.h.
                                                                     {
  // Perform an unsigned comparison against Smi::kMaxValue.
  CompareInt32AndJumpIf(src, Smi::kMaxValue, kUnsignedGreaterThan, fail,
                        distance);
  SmiTagInt32AndSetFlags(dst, src);
  if (!SmiValuesAre32Bits()) {
    Assert(kNoOverflow, AbortReason::kInputDoesNotFitSmi);
  }
}
References v8::internal::MacroAssembler::Assert(), CompareInt32AndJumpIf(), v8::internal::Smi::kMaxValue, v8::internal::kNoOverflow, v8::internal::kUnsignedGreaterThan, SmiTagInt32AndSetFlags(), and v8::internal::SmiValuesAre32Bits().
Referenced by SmiTagUint32AndJumpIfFail(), and SmiTagUint32AndJumpIfSuccess().
SmiTagUint32AndJumpIfFail() [2/2]
void v8::internal::maglev::MaglevAssembler::SmiTagUint32AndJumpIfFail (Register reg, Label * fail, Label::Distance distance = Label::kFar) [inline]
Definition at line 861 of file maglev-assembler-inl.h.
                                                       {
  SmiTagUint32AndJumpIfFail(reg, reg, fail, distance);
}
References SmiTagUint32AndJumpIfFail().
SmiTagUint32AndJumpIfSuccess() [1/2]
void v8::internal::maglev::MaglevAssembler::SmiTagUint32AndJumpIfSuccess (Register dst, Register src, Label * success, Label::Distance distance = Label::kFar) [inline]
Definition at line 884 of file maglev-assembler-inl.h.
                                                                        {
  Label fail;
  SmiTagUint32AndJumpIfFail(dst, src, &fail, Label::Distance::kNear);
  Jump(success, distance);
  bind(&fail);
}
References v8::internal::Assembler::bind(), Jump(), and SmiTagUint32AndJumpIfFail().
Referenced by MaterialiseValueNode(), and SmiTagUint32AndJumpIfSuccess().
SmiTagUint32AndJumpIfSuccess() [2/2]
void v8::internal::maglev::MaglevAssembler::SmiTagUint32AndJumpIfSuccess (Register reg, Label * success, Label::Distance distance = Label::kFar) [inline]
Definition at line 892 of file maglev-assembler-inl.h.
                                                          {
  SmiTagUint32AndJumpIfSuccess(reg, reg, success, distance);
}
References SmiTagUint32AndJumpIfSuccess().
SmiToDouble()
void v8::internal::maglev::MaglevAssembler::SmiToDouble (DoubleRegister result, Register smi) [inline]
Definition at line 283 of file maglev-assembler-inl.h.
                                                                            {
  AssertSmi(smi);
  SmiUntag(smi);
  Int32ToDouble(result, smi);
}
References v8::internal::MacroAssembler::AssertSmi(), Int32ToDouble(), v8::base::internal::result, and v8::internal::MacroAssembler::SmiUntag().
StackSlotOperand()
MemOperand v8::internal::maglev::MaglevAssembler::StackSlotOperand (StackSlot slot) [inline]
Definition at line 280 of file maglev-assembler-arm-inl.h.
                                                                  {
  return MemOperand(fp, slot.index);
}
References v8::internal::maglev::StackSlot::index.
Referenced by Move().
StoreContextCellFloat64Value()
void v8::internal::maglev::MaglevAssembler::StoreContextCellFloat64Value (Register cell, DoubleRegister value) [inline]
Definition at line 1245 of file maglev-assembler-arm-inl.h.
                                         {
  vstr(value, FieldMemOperand(cell, offsetof(ContextCell, double_value_)));
}
References v8::internal::FieldMemOperand(), v8::internal::value, and v8::internal::Assembler::vstr().
StoreContextCellInt32Value()
void v8::internal::maglev::MaglevAssembler::StoreContextCellInt32Value (Register cell, Register value) [inline]
Definition at line 1240 of file maglev-assembler-arm-inl.h.
                                                                        {
  str(value, FieldMemOperand(cell, offsetof(ContextCell, double_value_)));
}
References v8::internal::FieldMemOperand(), v8::internal::Assembler::str(), and v8::internal::value.
StoreContextCellSmiValue()
void v8::internal::maglev::MaglevAssembler::StoreContextCellSmiValue (Register cell, Register value) [inline]
Definition at line 308 of file maglev-assembler-inl.h.
                                                                      {
  StoreTaggedFieldNoWriteBarrier(cell, offsetof(ContextCell, tagged_value_),
                                 value);
}
References StoreTaggedFieldNoWriteBarrier(), and v8::internal::value.
StoreField()
void v8::internal::maglev::MaglevAssembler::StoreField (MemOperand operand, Register value, int element_size) [inline]
Definition at line 457 of file maglev-assembler-arm-inl.h.
                                                  {
  DCHECK(size == 1 || size == 2 || size == 4);
  if (size == 1) {
    strb(value, operand);
  } else if (size == 2) {
    strh(value, operand);
  } else {
    DCHECK_EQ(size, 4);
    str(value, operand);
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, size(), v8::internal::Assembler::str(), v8::internal::Assembler::strb(), v8::internal::Assembler::strh(), and v8::internal::value.
StoreFixedArrayElementNoWriteBarrier()
void v8::internal::maglev::MaglevAssembler::StoreFixedArrayElementNoWriteBarrier (Register array, Register index, Register value) [inline]
Definition at line 426 of file maglev-assembler-arm-inl.h.
                                                    {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  add(scratch, array, Operand(index, LSL, kTaggedSizeLog2));
  MacroAssembler::StoreTaggedField(
      value, FieldMemOperand(scratch, OFFSET_OF_DATA_START(FixedArray)));
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::add(), v8::internal::FieldMemOperand(), v8::internal::index, v8::internal::kTaggedSizeLog2, v8::internal::LSL, OFFSET_OF_DATA_START, v8::internal::MacroAssembler::StoreTaggedField(), and v8::internal::value.
Referenced by StoreFixedArrayElementWithWriteBarrier().
StoreFixedArrayElementWithWriteBarrier()
void v8::internal::maglev::MaglevAssembler::StoreFixedArrayElementWithWriteBarrier (Register array, Register index, Register value, RegisterSnapshot register_snapshot)
Definition at line 663 of file maglev-assembler.cc.
                                        {
  if (v8_flags.debug_code) {
    AssertObjectType(array, FIXED_ARRAY_TYPE, AbortReason::kUnexpectedValue);
    CompareInt32AndAssert(index, 0, kGreaterThanEqual,
                          AbortReason::kUnexpectedNegativeValue);
  }
  StoreFixedArrayElementNoWriteBarrier(array, index, value);
  CheckAndEmitDeferredWriteBarrier<kElement>(
      array, index, value, register_snapshot, kValueIsDecompressed,
      kValueCanBeSmi);
}
References AssertObjectType(), CompareInt32AndAssert(), v8::internal::index, v8::internal::kGreaterThanEqual, kValueCanBeSmi, kValueIsDecompressed, StoreFixedArrayElementNoWriteBarrier(), v8::internal::v8_flags, and v8::internal::value.
StoreFixedDoubleArrayElement()
void v8::internal::maglev::MaglevAssembler::StoreFixedDoubleArrayElement (Register array, Register index, DoubleRegister value) [inline]
Definition at line 376 of file maglev-assembler-arm-inl.h.
                                                          {
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  add(scratch, array, Operand(index, LSL, kDoubleSizeLog2));
  vstr(value, FieldMemOperand(scratch, OFFSET_OF_DATA_START(FixedArray)));
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::add(), v8::internal::FieldMemOperand(), v8::internal::index, v8::internal::kDoubleSizeLog2, v8::internal::LSL, OFFSET_OF_DATA_START, v8::internal::value, and v8::internal::Assembler::vstr().
StoreFloat32()
void v8::internal::maglev::MaglevAssembler::StoreFloat32 (MemOperand dst, DoubleRegister src) [inline]
Definition at line 606 of file maglev-assembler-arm-inl.h.
                                                                            {
  UseScratchRegisterScope temps(this);
  SwVfpRegister temp_vfps = temps.AcquireS();
  vcvt_f32_f64(temp_vfps, src);
  vstr(temp_vfps, dst);
}
References v8::internal::UseScratchRegisterScope::AcquireS(), v8::internal::Assembler::vcvt_f32_f64(), and v8::internal::Assembler::vstr().
StoreFloat64()
void v8::internal::maglev::MaglevAssembler::StoreFloat64 (MemOperand dst, DoubleRegister src) [inline]
Definition at line 615 of file maglev-assembler-arm-inl.h.
                                                                            {
  vstr(src, dst);
}
References v8::internal::Assembler::vstr().
Referenced by AllocateHeapNumber(), and StoreHeapNumberValue().
StoreHeapNumberValue()
void v8::internal::maglev::MaglevAssembler::StoreHeapNumberValue (DoubleRegister value, Register heap_number) [inline]
Definition at line 459 of file maglev-assembler-inl.h.
                                                                        {
  StoreFloat64(FieldMemOperand(heap_number, offsetof(HeapNumber, value_)),
               value);
}
References v8::internal::FieldMemOperand(), StoreFloat64(), and v8::internal::value.
StoreInt32()
void v8::internal::maglev::MaglevAssembler::StoreInt32 (MemOperand dst, Register src) [inline]
Definition at line 591 of file maglev-assembler-arm-inl.h.
                                                                    {
  str(src, dst);
}
References v8::internal::Assembler::str().
StoreInt32Field()
void v8::internal::maglev::MaglevAssembler::StoreInt32Field (Register object, int offset, int32_t value) [inline]
Definition at line 449 of file maglev-assembler-arm-inl.h.
                                                            {
  TemporaryRegisterScope scope(this);
  Register scratch = scope.AcquireScratch();
  Move(scratch, value);
  str(scratch, FieldMemOperand(object, offset));
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::FieldMemOperand(), Move(), v8::internal::Assembler::str(), and v8::internal::value.
Referenced by AllocateTwoByteString().
StoreTaggedFieldNoWriteBarrier()
void v8::internal::maglev::MaglevAssembler::StoreTaggedFieldNoWriteBarrier (Register object, int offset, Register value) [inline]
Definition at line 420 of file maglev-assembler-arm-inl.h.
                                                                            {
  MacroAssembler::StoreTaggedField(value, FieldMemOperand(object, offset));
}
References v8::internal::FieldMemOperand(), v8::internal::MacroAssembler::StoreTaggedField(), and v8::internal::value.
Referenced by SetMapAsRoot(), StoreContextCellSmiValue(), and StoreTaggedFieldWithWriteBarrier().
StoreTaggedFieldWithWriteBarrier()
void v8::internal::maglev::MaglevAssembler::StoreTaggedFieldWithWriteBarrier (Register object, int offset, Register value, RegisterSnapshot register_snapshot, ValueIsCompressed value_is_compressed, ValueCanBeSmi value_can_be_smi)
Definition at line 639 of file maglev-assembler.cc.
                                    {
  AssertNotSmi(object);
  StoreTaggedFieldNoWriteBarrier(object, offset, value);
  CheckAndEmitDeferredWriteBarrier<kField>(
      object, offset, value, register_snapshot, value_is_compressed,
      value_can_be_smi);
}
References v8::internal::MacroAssembler::AssertNotSmi(), StoreTaggedFieldNoWriteBarrier(), and v8::internal::value.
StoreTaggedSignedField() [1/2]
void v8::internal::maglev::MaglevAssembler::StoreTaggedSignedField (Register object, int offset, Register value) [inline]
Definition at line 435 of file maglev-assembler-arm-inl.h.
                                                                    {
  AssertSmi(value);
  MacroAssembler::StoreTaggedField(value, FieldMemOperand(object, offset));
}
References v8::internal::MacroAssembler::AssertSmi(), v8::internal::FieldMemOperand(), v8::internal::MacroAssembler::StoreTaggedField(), and v8::internal::value.
Referenced by AllocateTwoByteString().
StoreTaggedSignedField() [2/2]
void v8::internal::maglev::MaglevAssembler::StoreTaggedSignedField (Register object, int offset, Tagged< Smi > value) [inline]
Definition at line 441 of file maglev-assembler-arm-inl.h.
                                                                       {
  TemporaryRegisterScope scope(this);
  Register scratch = scope.AcquireScratch();
  Move(scratch, value);
  MacroAssembler::StoreTaggedField(scratch, FieldMemOperand(object, offset));
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::FieldMemOperand(), Move(), v8::internal::MacroAssembler::StoreTaggedField(), and v8::internal::value.
StoreUnalignedFloat64()
void v8::internal::maglev::MaglevAssembler::StoreUnalignedFloat64 (Register base, Register index, DoubleRegister src) [inline]
Definition at line 644 of file maglev-assembler-arm-inl.h.
                                                                       {
  // vstr only works on 4 bytes aligned access.
  TemporaryRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  Register index_scratch = temps.AcquireScratch();
  VmovLow(scratch, src);
  str(scratch, MemOperand(base, index));
  add(index_scratch, index, Operand(4));
  VmovHigh(scratch, src);
  str(scratch, MemOperand(base, index_scratch));
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::add(), v8::internal::index, v8::internal::Assembler::str(), v8::internal::MacroAssembler::VmovHigh(), and v8::internal::MacroAssembler::VmovLow().
StringCharCodeOrCodePointAt()
void v8::internal::maglev::MaglevAssembler::StringCharCodeOrCodePointAt (BuiltinStringPrototypeCharCodeOrCodePointAt::Mode mode, RegisterSnapshot & register_snapshot, Register result, Register string, Register index, Register scratch1, Register scratch2, Label * result_fits_one_byte)
Definition at line 279 of file maglev-assembler-arm.cc.
                                 {
  ASM_CODE_COMMENT(this);
  ZoneLabelRef done(this);
  Label seq_string;
  Label cons_string;
  Label sliced_string;
  Label* deferred_runtime_call = MakeDeferredCode(
      [](MaglevAssembler* masm,
         BuiltinStringPrototypeCharCodeOrCodePointAt::Mode mode,
         RegisterSnapshot register_snapshot, ZoneLabelRef done, Register result,
         Register string, Register index) {
        DCHECK(!register_snapshot.live_registers.has(result));
        DCHECK(!register_snapshot.live_registers.has(string));
        DCHECK(!register_snapshot.live_registers.has(index));
        {
          SaveRegisterStateForCall save_register_state(masm, register_snapshot);
          __ SmiTag(index);
          __ Push(string, index);
          __ Move(kContextRegister, masm->native_context().object());
          // This call does not throw nor can deopt.
          if (mode ==
              BuiltinStringPrototypeCharCodeOrCodePointAt::kCodePointAt) {
            __ CallRuntime(Runtime::kStringCodePointAt);
          } else {
            DCHECK_EQ(mode,
                      BuiltinStringPrototypeCharCodeOrCodePointAt::kCharCodeAt);
            __ CallRuntime(Runtime::kStringCharCodeAt);
          }
          save_register_state.DefineSafepoint();
          __ SmiUntag(kReturnRegister0);
          __ Move(result, kReturnRegister0);
        }
        __ b(*done);
      },
      mode, register_snapshot, done, result, string, index);
  // We might need to try more than one time for ConsString, SlicedString and
  // ThinString.
  Label loop;
  bind(&loop);
  if (v8_flags.debug_code) {
    // Check if {string} is a string.
    AssertObjectTypeInRange(string, FIRST_STRING_TYPE, LAST_STRING_TYPE,
                            AbortReason::kUnexpectedValue);
    Register scratch = instance_type;
    ldr(scratch, FieldMemOperand(string, offsetof(String, length_)));
    cmp(index, scratch);
    Check(lo, AbortReason::kUnexpectedValue);
  }
  // Get instance type.
  LoadInstanceType(instance_type, string);
  {
    TemporaryRegisterScope temps(this);
    Register representation = temps.AcquireScratch();
    // TODO(victorgomes): Add fast path for external strings.
    and_(representation, instance_type, Operand(kStringRepresentationMask));
    cmp(representation, Operand(kSeqStringTag));
    b(eq, &seq_string);
    cmp(representation, Operand(kConsStringTag));
    b(eq, &cons_string);
    cmp(representation, Operand(kSlicedStringTag));
    b(eq, &sliced_string);
    cmp(representation, Operand(kThinStringTag));
    b(ne, deferred_runtime_call);
    // Fallthrough to thin string.
  }
  // Is a thin string.
  {
    ldr(string, FieldMemOperand(string, offsetof(ThinString, actual_)));
    b(&loop);
  }
  bind(&sliced_string);
  {
    TemporaryRegisterScope temps(this);
    Register offset = temps.AcquireScratch();
    LoadAndUntagTaggedSignedField(offset, string,
                                  offsetof(SlicedString, offset_));
    LoadTaggedField(string, string, offsetof(SlicedString, parent_));
    add(index, index, offset);
    b(&loop);
  }
  bind(&cons_string);
  {
    // Reuse {instance_type} register here, since CompareRoot requires a scratch
    // register as well.
    Register second_string = instance_type;
    ldr(second_string, FieldMemOperand(string, offsetof(ConsString, second_)));
    CompareRoot(second_string, RootIndex::kempty_string);
    b(ne, deferred_runtime_call);
    ldr(string, FieldMemOperand(string, offsetof(ConsString, first_)));
    b(&loop); // Try again with first string.
  }
  bind(&seq_string);
  {
    Label two_byte_string;
    tst(instance_type, Operand(kOneByteStringTag));
    b(eq, &two_byte_string);
    // The result of one-byte string will be the same for both modes
    // (CharCodeAt/CodePointAt), since it cannot be the first half of a
    // surrogate pair.
    SeqOneByteStringCharCodeAt(result, string, index);
    b(result_fits_one_byte);
    bind(&two_byte_string);
    // {instance_type} is unused from this point, so we can use as scratch.
    Register scratch = instance_type;
    lsl(scratch, index, Operand(1));
    add(scratch, scratch,
        Operand(OFFSET_OF_DATA_START(SeqTwoByteString) - kHeapObjectTag));
    if (mode == BuiltinStringPrototypeCharCodeOrCodePointAt::kCharCodeAt) {
      ldrh(result, MemOperand(string, scratch));
    } else {
      DCHECK_EQ(mode,
                BuiltinStringPrototypeCharCodeOrCodePointAt::kCodePointAt);
      Register string_backup = string;
      if (result == string) {
        string_backup = scratch2;
        Move(string_backup, string);
      }
      ldrh(result, MemOperand(string, scratch));
      Register first_code_point = scratch;
      and_(first_code_point, result, Operand(0xfc00));
      cmp(first_code_point, Operand(0xd800));
      b(ne, *done);
      Register length = scratch;
      ldr(length, FieldMemOperand(string_backup, offsetof(String, length_)));
      add(index, index, Operand(1));
      cmp(index, length);
      b(ge, *done);
      Register second_code_point = scratch;
      lsl(index, index, Operand(1));
      add(index, index,
          Operand(OFFSET_OF_DATA_START(SeqTwoByteString) - kHeapObjectTag));
      ldrh(second_code_point, MemOperand(string_backup, index));
      // {index} is not needed at this point.
      Register scratch2 = index;
      and_(scratch2, second_code_point, Operand(0xfc00));
      cmp(scratch2, Operand(0xdc00));
      b(ne, *done);
      int surrogate_offset = 0x10000 - (0xd800 << 10) - 0xdc00;
      add(second_code_point, second_code_point, Operand(surrogate_offset));
      lsl(result, result, Operand(10));
      add(result, result, second_code_point);
    }
    // Fallthrough.
  }
  bind(*done);
  if (v8_flags.debug_code) {
    // We make sure that the user of this macro is not relying in string and
    // index to not be clobbered.
    if (result != string) {
      Move(string, 0xdeadbeef);
    }
    if (result != index) {
      Move(index, 0xdeadbeef);
    }
  }
}
References __, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::add(), v8::internal::Assembler::and_(), ASM_CODE_COMMENT, AssertObjectTypeInRange(), v8::internal::Assembler::b(), v8::internal::Assembler::bind(), CallRuntime(), v8::internal::MacroAssembler::Check(), v8::internal::Assembler::cmp(), v8::internal::MacroAssembler::CompareRoot(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::SaveRegisterStateForCall::DefineSafepoint(), v8::internal::eq, v8::internal::FieldMemOperand(), v8::internal::ge, v8::internal::RegListBase< RegisterT >::has(), v8::internal::index, v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::kCharCodeAt, v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::kCodePointAt, v8::internal::kConsStringTag, v8::internal::kContextRegister, v8::internal::kHeapObjectTag, v8::internal::kOneByteStringTag, v8::internal::kReturnRegister0, v8::internal::kSeqStringTag, v8::internal::kSlicedStringTag, v8::internal::kStringRepresentationMask, v8::internal::kThinStringTag, v8::internal::LAST_STRING_TYPE, v8::internal::Assembler::ldr(), v8::internal::Assembler::ldrh(), v8::internal::length, v8::internal::maglev::RegisterSnapshot::live_registers, v8::internal::lo, LoadAndUntagTaggedSignedField(), LoadInstanceType(), LoadTaggedField(), v8::internal::Assembler::lsl(), MakeDeferredCode(), mode(), Move(), native_context(), v8::internal::ne, v8::internal::compiler::NativeContextRef::object(), OFFSET_OF_DATA_START, Push(), v8::base::internal::result, SeqOneByteStringCharCodeAt(), v8::internal::MacroAssembler::SmiTag(), v8::internal::MacroAssembler::SmiUntag(), v8::internal::string, v8::internal::Assembler::tst(), and v8::internal::v8_flags.
StringFromCharCode()
void v8::internal::maglev::MaglevAssembler::StringFromCharCode (RegisterSnapshot register_snapshot, Label * char_code_fits_one_byte, Register result, Register char_code, Register scratch, CharCodeMaskMode mask_mode)
Definition at line 237 of file maglev-assembler-arm.cc.
                                                                     {
  AssertZeroExtended(char_code);
  DCHECK_NE(char_code, scratch);
  ZoneLabelRef done(this);
  if (mask_mode == CharCodeMaskMode::kMustApplyMask) {
    and_(char_code, char_code, Operand(0xFFFF));
  }
  cmp(char_code, Operand(String::kMaxOneByteCharCode));
  JumpToDeferredIf(
      kUnsignedGreaterThan,
      [](MaglevAssembler* masm, RegisterSnapshot register_snapshot,
         ZoneLabelRef done, Register result, Register char_code,
         Register scratch) {
        // Be sure to save {char_code}. If it aliases with {result}, use
        // the scratch register.
        // TODO(victorgomes): This is probably not needed any more, because
        // we now ensure that results registers don't alias with inputs/temps.
        // Confirm, and drop this check.
        if (char_code == result) {
          __ Move(scratch, char_code);
          char_code = scratch;
        }
        DCHECK_NE(char_code, result);
        DCHECK(!register_snapshot.live_tagged_registers.has(char_code));
        register_snapshot.live_registers.set(char_code);
        __ AllocateTwoByteString(register_snapshot, result, 1);
        __ strh(char_code, FieldMemOperand(
                               result, OFFSET_OF_DATA_START(SeqTwoByteString)));
        __ b(*done);
      },
      register_snapshot, done, result, char_code, scratch);
  if (char_code_fits_one_byte != nullptr) {
    bind(char_code_fits_one_byte);
  }
  LoadSingleCharacterString(result, char_code, scratch);
  bind(*done);
}
References __, AllocateTwoByteString(), v8::internal::Assembler::and_(), v8::internal::MacroAssembler::AssertZeroExtended(), v8::internal::Assembler::b(), v8::internal::Assembler::bind(), v8::internal::Assembler::cmp(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::FieldMemOperand(), v8::internal::RegListBase< RegisterT >::has(), JumpToDeferredIf(), v8::internal::String::kMaxOneByteCharCode, kMustApplyMask, v8::internal::kUnsignedGreaterThan, v8::internal::maglev::RegisterSnapshot::live_registers, v8::internal::maglev::RegisterSnapshot::live_tagged_registers, LoadSingleCharacterString(), Move(), OFFSET_OF_DATA_START, v8::base::internal::result, v8::internal::RegListBase< RegisterT >::set(), and v8::internal::Assembler::strh().
StringLength()
void v8::internal::maglev::MaglevAssembler::StringLength (Register result, Register string) [inline]
Definition at line 1048 of file maglev-assembler-inl.h.
                                                                          {
  if (v8_flags.debug_code) {
    // Check if {string} is a string.
    AssertObjectTypeInRange(string, FIRST_STRING_TYPE, LAST_STRING_TYPE,
                            AbortReason::kUnexpectedValue);
  }
  LoadSignedField(result, FieldMemOperand(string, offsetof(String, length_)),
                  sizeof(int32_t));
}
References AssertObjectTypeInRange(), v8::internal::FieldMemOperand(), v8::internal::LAST_STRING_TYPE, LoadSignedField(), v8::base::internal::result, and v8::internal::v8_flags.
TestInt32AndJumpIfAllClear() [1/2]
void v8::internal::maglev::MaglevAssembler::TestInt32AndJumpIfAllClear (MemOperand operand, int32_t mask, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1207 of file maglev-assembler-arm-inl.h.
                                                                             {
  TemporaryRegisterScope temps(this);
  Register value = temps.AcquireScratch();
  ldr(value, operand);
  TestInt32AndJumpIfAllClear(value, mask, target);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::ldr(), TestInt32AndJumpIfAllClear(), and v8::internal::value.
TestInt32AndJumpIfAllClear() [2/2]
void v8::internal::maglev::MaglevAssembler::TestInt32AndJumpIfAllClear (Register r1, int32_t mask, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1201 of file maglev-assembler-arm-inl.h.
                                                                      {
  tst(r1, Operand(mask));
  b(eq, target);
}
References v8::internal::Assembler::b(), v8::internal::eq, and v8::internal::Assembler::tst().
Referenced by JumpIfSeqOneByteStringMap(), TestInt32AndJumpIfAllClear(), TestUint8AndJumpIfAllClear(), and ToBoolean().
TestInt32AndJumpIfAnySet() [1/2]
void v8::internal::maglev::MaglevAssembler::TestInt32AndJumpIfAnySet (MemOperand operand, int32_t mask, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1185 of file maglev-assembler-arm-inl.h.
                                                                             {
  TemporaryRegisterScope temps(this);
  Register value = temps.AcquireScratch();
  ldr(value, operand);
  TestInt32AndJumpIfAnySet(value, mask, target);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::ldr(), TestInt32AndJumpIfAnySet(), and v8::internal::value.
TestInt32AndJumpIfAnySet() [2/2]
void v8::internal::maglev::MaglevAssembler::TestInt32AndJumpIfAnySet (Register r1, int32_t mask, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1179 of file maglev-assembler-arm-inl.h.
                                                                      {
  tst(r1, Operand(mask));
  b(ne, target);
}
References v8::internal::Assembler::b(), v8::internal::ne, and v8::internal::Assembler::tst().
Referenced by JumpIfSeqOneByteStringMap(), LoadThinStringValue(), TestInt32AndJumpIfAnySet(), and TestUint8AndJumpIfAnySet().
TestTypeOf()
void v8::internal::maglev::MaglevAssembler::TestTypeOf (Register object, interpreter::TestTypeOfFlags::LiteralFlag literal, Label * if_true, Label::Distance true_distance, bool fallthrough_when_true, Label * if_false, Label::Distance false_distance, bool fallthrough_when_false)
Definition at line 384 of file maglev-assembler.cc.
                                 {
  // If both true and false are fallthroughs, we don't have to do anything.
  if (fallthrough_when_true && fallthrough_when_false) return;
  // IMPORTANT: Note that `object` could be a register that aliases registers in
  // the TemporaryRegisterScope. Make sure that all reads of `object` are before
  // any writes to scratch registers
  using LiteralFlag = interpreter::TestTypeOfFlags::LiteralFlag;
  switch (literal) {
    case LiteralFlag::kNumber: {
      MaglevAssembler::TemporaryRegisterScope temps(this);
      Register scratch = temps.AcquireScratch();
      JumpIfSmi(object, is_true, true_distance);
      CompareMapWithRoot(object, RootIndex::kHeapNumberMap, scratch);
      Branch(kEqual, is_true, true_distance, fallthrough_when_true, is_false,
             false_distance, fallthrough_when_false);
      return;
    }
    case LiteralFlag::kString: {
      JumpIfSmi(object, is_false, false_distance);
      CheckJSAnyIsStringAndBranch(object, is_true, true_distance,
                                  fallthrough_when_true, is_false,
                                  false_distance, fallthrough_when_false);
      return;
    }
    case LiteralFlag::kSymbol: {
      JumpIfSmi(object, is_false, false_distance);
      BranchOnObjectType(object, SYMBOL_TYPE, is_true, true_distance,
                         fallthrough_when_true, is_false, false_distance,
                         fallthrough_when_false);
      return;
    }
    case LiteralFlag::kBoolean:
      JumpIfRoot(object, RootIndex::kTrueValue, is_true, true_distance);
      CompareRoot(object, RootIndex::kFalseValue);
      Branch(kEqual, is_true, true_distance, fallthrough_when_true, is_false,
             false_distance, fallthrough_when_false);
      return;
    case LiteralFlag::kBigInt: {
      JumpIfSmi(object, is_false, false_distance);
      BranchOnObjectType(object, BIGINT_TYPE, is_true, true_distance,
                         fallthrough_when_true, is_false, false_distance,
                         fallthrough_when_false);
      return;
    }
    case LiteralFlag::kUndefined: {
      MaglevAssembler::TemporaryRegisterScope temps(this);
      Register map = temps.AcquireScratch();
      // Make sure `object` isn't a valid temp here, since we reuse it.
      DCHECK(!temps.Available().has(object));
      JumpIfSmi(object, is_false, false_distance);
      // Check it has the undetectable bit set and it is not null.
      LoadMap(map, object);
      TestUint8AndJumpIfAllClear(FieldMemOperand(map, Map::kBitFieldOffset),
                                 Map::Bits1::IsUndetectableBit::kMask, is_false,
                                 false_distance);
      CompareRoot(object, RootIndex::kNullValue);
      Branch(kNotEqual, is_true, true_distance, fallthrough_when_true, is_false,
             false_distance, fallthrough_when_false);
      return;
    }
    case LiteralFlag::kFunction: {
      MaglevAssembler::TemporaryRegisterScope temps(this);
      Register scratch = temps.AcquireScratch();
      JumpIfSmi(object, is_false, false_distance);
      // Check if callable bit is set and not undetectable.
      LoadMap(scratch, object);
      Branch(IsCallableAndNotUndetectable(scratch, scratch), is_true,
             true_distance, fallthrough_when_true, is_false, false_distance,
             fallthrough_when_false);
      return;
    }
    case LiteralFlag::kObject: {
      MaglevAssembler::TemporaryRegisterScope temps(this);
      Register scratch = temps.AcquireScratch();
      JumpIfSmi(object, is_false, false_distance);
      // If the object is null then return true.
      JumpIfRoot(object, RootIndex::kNullValue, is_true, true_distance);
      // Check if the object is a receiver type,
      LoadMap(scratch, object);
      CompareInstanceTypeAndJumpIf(scratch, FIRST_JS_RECEIVER_TYPE, kLessThan,
                                   is_false, false_distance);
      // ... and is not undefined (undetectable) nor callable.
      Branch(IsNotCallableNorUndetactable(scratch, scratch), is_true,
             true_distance, fallthrough_when_true, is_false, false_distance,
             fallthrough_when_false);
      return;
    }
    case LiteralFlag::kOther:
      if (!fallthrough_when_false) {
        Jump(is_false, false_distance);
      }
      return;
  }
  UNREACHABLE();
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Available(), v8::internal::BIGINT_TYPE, Branch(), BranchOnObjectType(), CheckJSAnyIsStringAndBranch(), CompareInstanceTypeAndJumpIf(), CompareMapWithRoot(), v8::internal::MacroAssembler::CompareRoot(), v8::internal::DCHECK(), v8::internal::FieldMemOperand(), v8::internal::RegListBase< RegisterT >::has(), IsCallableAndNotUndetectable(), IsNotCallableNorUndetactable(), Jump(), JumpIfRoot(), JumpIfSmi(), v8::internal::kEqual, v8::internal::torque::ls::kFunction, v8::internal::kLessThan, v8::internal::kNotEqual, v8::internal::MacroAssembler::LoadMap(), TestUint8AndJumpIfAllClear(), and v8::internal::UNREACHABLE().
TestUint8AndJumpIfAllClear()
void v8::internal::maglev::MaglevAssembler::TestUint8AndJumpIfAllClear (MemOperand operand, uint8_t mask, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1215 of file maglev-assembler-arm-inl.h.
                                                                             {
  TemporaryRegisterScope temps(this);
  Register value = temps.AcquireScratch();
  LoadByte(value, operand);
  TestInt32AndJumpIfAllClear(value, mask, target);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), LoadByte(), TestInt32AndJumpIfAllClear(), and v8::internal::value.
Referenced by JumpIfNotCallable(), JumpIfNotUndetectable(), and TestTypeOf().
TestUint8AndJumpIfAnySet()
void v8::internal::maglev::MaglevAssembler::TestUint8AndJumpIfAnySet (MemOperand operand, uint8_t mask, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 1193 of file maglev-assembler-arm-inl.h.
                                                                             {
  TemporaryRegisterScope temps(this);
  Register value = temps.AcquireScratch();
  ldrb(value, operand);
  TestInt32AndJumpIfAnySet(value, mask, target);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::Assembler::ldrb(), TestInt32AndJumpIfAnySet(), and v8::internal::value.
Referenced by JumpIfUndetectable(), and ToBoolean().
ToBoolean()
void v8::internal::maglev::MaglevAssembler::ToBoolean (Register value, CheckType check_type, ZoneLabelRef is_true, ZoneLabelRef is_false, bool fallthrough_when_true)
Definition at line 160 of file maglev-assembler.cc.
                                                            {
  TemporaryRegisterScope temps(this);
  if (check_type == CheckType::kCheckHeapObject) {
    // Check if {{value}} is Smi.
    Condition is_smi = CheckSmi(value);
    JumpToDeferredIf(
        is_smi,
        [](MaglevAssembler* masm, Register value, ZoneLabelRef is_true,
           ZoneLabelRef is_false) {
          // Check if {value} is not zero.
          __ CompareSmiAndJumpIf(value, Smi::FromInt(0), kEqual, *is_false);
          __ Jump(*is_true);
        },
        value, is_true, is_false);
  } else if (v8_flags.debug_code) {
    AssertNotSmi(value);
  }
#if V8_STATIC_ROOTS_BOOL
  // Check if {{value}} is a falsey root or the true value.
  // Undefined is the first root, so it's the smallest possible pointer
  // value, which means we don't have to subtract it for the range check.
  ReadOnlyRoots roots(isolate_);
  static_assert(StaticReadOnlyRoot::kFirstAllocatedRoot ==
                StaticReadOnlyRoot::kUndefinedValue);
  static_assert(StaticReadOnlyRoot::kUndefinedValue + sizeof(Undefined) ==
                StaticReadOnlyRoot::kNullValue);
  static_assert(StaticReadOnlyRoot::kNullValue + sizeof(Null) ==
                StaticReadOnlyRoot::kempty_string);
  static_assert(StaticReadOnlyRoot::kempty_string +
                    SeqOneByteString::SizeFor(0) ==
                StaticReadOnlyRoot::kFalseValue);
  static_assert(StaticReadOnlyRoot::kFalseValue + sizeof(False) ==
                StaticReadOnlyRoot::kTrueValue);
  CompareInt32AndJumpIf(value, StaticReadOnlyRoot::kTrueValue,
                        kUnsignedLessThan, *is_false);
  // Reuse the condition flags from the above int32 compare to also check for
  // the true value itself.
  JumpIf(kEqual, *is_true);
#else
  // Check if {{value}} is false.
  JumpIfRoot(value, RootIndex::kFalseValue, *is_false);
  // Check if {{value}} is true.
  JumpIfRoot(value, RootIndex::kTrueValue, *is_true);
  // Check if {{value}} is empty string.
  JumpIfRoot(value, RootIndex::kempty_string, *is_false);
  // Only check null and undefined if we're not going to check the
  // undetectable bit.
  if (compilation_info()
          ->broker()
          ->dependencies()
          ->DependOnNoUndetectableObjectsProtector()) {
    // Check if {{value}} is undefined.
    JumpIfRoot(value, RootIndex::kUndefinedValue, *is_false);
    // Check if {{value}} is null.
    JumpIfRoot(value, RootIndex::kNullValue, *is_false);
  }
#endif
  Register map = temps.AcquireScratch();
  LoadMap(map, value);
  if (!compilation_info()
           ->broker()
           ->dependencies()
           ->DependOnNoUndetectableObjectsProtector()) {
    // Check if {{value}} is undetectable.
    TestUint8AndJumpIfAnySet(FieldMemOperand(map, Map::kBitFieldOffset),
                             Map::Bits1::IsUndetectableBit::kMask, *is_false);
  }
  // Check if {{value}} is a HeapNumber.
  JumpIfRoot(map, RootIndex::kHeapNumberMap,
             MakeDeferredCode(
                 [](MaglevAssembler* masm, Register value, ZoneLabelRef is_true,
                    ZoneLabelRef is_false) {
                   __ CompareDoubleAndJumpIfZeroOrNaN(
                       FieldMemOperand(value, offsetof(HeapNumber, value_)),
                       *is_false);
                   __ Jump(*is_true);
                 },
                 value, is_true, is_false));
  // Check if {{value}} is a BigInt.
  // {{map}} is not needed after this check, we pass to the deferred code, so it
  // can be added to the temporary registers.
  JumpIfRoot(map, RootIndex::kBigIntMap,
             MakeDeferredCode(
                 [](MaglevAssembler* masm, Register value, Register map,
                    ZoneLabelRef is_true, ZoneLabelRef is_false) {
                   TemporaryRegisterScope temps(masm);
                   temps.IncludeScratch(map);
                   __ TestInt32AndJumpIfAllClear(
                       FieldMemOperand(value, offsetof(BigInt, bitfield_)),
                       BigInt::LengthBits::kMask, *is_false);
                   __ Jump(*is_true);
                 },
                 value, map, is_true, is_false));
  // Otherwise true.
  if (!fallthrough_when_true) {
    Jump(*is_true);
  }
}
References __, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::MacroAssembler::AssertNotSmi(), broker(), v8::internal::MacroAssembler::CheckSmi(), CompareDoubleAndJumpIfZeroOrNaN(), CompareInt32AndJumpIf(), CompareSmiAndJumpIf(), compilation_info(), v8::internal::FieldMemOperand(), v8::internal::Smi::FromInt(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::IncludeScratch(), v8::internal::MacroAssemblerBase::isolate_, Jump(), JumpIf(), JumpIfRoot(), JumpToDeferredIf(), v8::internal::maglev::kCheckHeapObject, v8::internal::kEqual, v8::base::BitField< T, shift, size, U >::kMask, v8::internal::kUnsignedLessThan, v8::internal::MacroAssembler::LoadMap(), MakeDeferredCode(), v8::internal::SeqOneByteString::SizeFor(), TestInt32AndJumpIfAllClear(), TestUint8AndJumpIfAnySet(), v8::internal::v8_flags, and v8::internal::value.
ToMemOperand() [1/2]
MemOperand v8::internal::maglev::MaglevAssembler::ToMemOperand (const compiler::InstructionOperand & operand) [inline]
Definition at line 292 of file maglev-assembler-arm-inl.h.
                                               {
  return GetStackSlot(compiler::AllocatedOperand::cast(operand));
}
References v8::internal::compiler::LocationOperand::cast(), and GetStackSlot().
Referenced by FromAnyToRegister(), IsRootConstant(), MaterialiseValueNode(), ToMemOperand(), and v8::internal::maglev::detail::ToRegister().
ToMemOperand() [2/2]
MemOperand v8::internal::maglev::MaglevAssembler::ToMemOperand (const ValueLocation & location) [inline]
Definition at line 297 of file maglev-assembler-arm-inl.h.
                                                                             {
  return ToMemOperand(location.operand());
}
References v8::internal::maglev::ValueLocation::operand(), and ToMemOperand().
ToUint8Clamped()
void v8::internal::maglev::MaglevAssembler::ToUint8Clamped (Register result, DoubleRegister value, Label * min, Label * max, Label * done) [inline]
Definition at line 679 of file maglev-assembler-arm-inl.h.
                                                                     {
  CpuFeatureScope scope(this, ARMv8);
  TemporaryRegisterScope temps(this);
  DoubleRegister scratch = temps.AcquireScratchDouble();
  Move(scratch, 0.0);
  VFPCompareAndSetFlags(scratch, value);
  // Set to 0 if NaN.
  JumpIf(kOverflow, min);
  JumpIf(kGreaterThanEqual, min);
  Move(scratch, 255.0);
  VFPCompareAndSetFlags(value, scratch);
  JumpIf(kGreaterThanEqual, max);
  // if value in [0, 255], then round up to the nearest.
  vrintn(scratch, value);
  TruncateDoubleToInt32(result, scratch);
  Jump(done);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratchDouble(), Jump(), JumpIf(), v8::internal::kGreaterThanEqual, v8::internal::kOverflow, v8::internal::Assembler::max(), v8::internal::Assembler::min(), Move(), v8::base::internal::result, TruncateDoubleToInt32(), v8::internal::value, v8::internal::MacroAssembler::VFPCompareAndSetFlags(), and v8::internal::Assembler::vrintn().
TruncateDoubleToInt32()
void v8::internal::maglev::MaglevAssembler::TruncateDoubleToInt32 (Register dst, DoubleRegister src)
Definition at line 498 of file maglev-assembler-arm.cc.
                                                                            {
  ZoneLabelRef done(this);
  Label* slow_path = MakeDeferredCode(
      [](MaglevAssembler* masm, DoubleRegister src, Register dst,
         ZoneLabelRef done) {
        __ push(lr);
        __ AllocateStackSpace(kDoubleSize);
        __ vstr(src, MemOperand(sp, 0));
        __ CallBuiltin(Builtin::kDoubleToI);
        __ ldr(dst, MemOperand(sp, 0));
        __ add(sp, sp, Operand(kDoubleSize));
        __ pop(lr);
        __ Jump(*done);
      },
      src, dst, done);
  TryInlineTruncateDoubleToI(dst, src, *done);
  Jump(slow_path);
  bind(*done);
}
References __, v8::internal::Assembler::add(), v8::internal::MacroAssembler::AllocateStackSpace(), v8::internal::Assembler::bind(), CallBuiltin(), Jump(), v8::internal::kDoubleSize, v8::internal::Assembler::ldr(), MakeDeferredCode(), v8::internal::MacroAssembler::pop(), v8::internal::MacroAssembler::push(), v8::internal::MacroAssembler::TryInlineTruncateDoubleToI(), and v8::internal::Assembler::vstr().
Referenced by ToUint8Clamped().
TryChangeFloat64ToIndex()
void v8::internal::maglev::MaglevAssembler::TryChangeFloat64ToIndex (Register result, DoubleRegister value, Label * success, Label * fail)
Definition at line 589 of file maglev-assembler-arm.cc.
                                                                           {
  UseScratchRegisterScope temps(this);
  LowDwVfpRegister low_double = temps.AcquireLowD();
  SwVfpRegister temp_vfps = low_double.low();
  DoubleRegister converted_back = low_double;
  // Convert the input float64 value to int32.
  vcvt_s32_f64(temp_vfps, value);
  vmov(result, temp_vfps);
  // Convert that int32 value back to float64.
  vcvt_f64_s32(converted_back, temp_vfps);
  // Check that the result of the float64->int32->float64 is equal to
  // the input (i.e. that the conversion didn't truncate).
  VFPCompareAndSetFlags(value, converted_back);
  JumpIf(kNotEqual, fail);
  Jump(success);
}
References v8::internal::UseScratchRegisterScope::AcquireLowD(), Jump(), JumpIf(), v8::internal::kNotEqual, v8::internal::LowDwVfpRegister::low(), v8::base::internal::result, v8::internal::value, v8::internal::Assembler::vcvt_f64_s32(), v8::internal::Assembler::vcvt_s32_f64(), v8::internal::MacroAssembler::VFPCompareAndSetFlags(), and v8::internal::Assembler::vmov().
TryMigrateInstance()
void v8::internal::maglev::MaglevAssembler::TryMigrateInstance (Register object, RegisterSnapshot & register_snapshot, Label * fail)
Definition at line 677 of file maglev-assembler.cc.
                                                      {
  Register return_val = Register::no_reg();
  {
    SaveRegisterStateForCall save_register_state(this, register_snapshot);
    Push(object);
    Move(kContextRegister, native_context().object());
    CallRuntime(Runtime::kTryMigrateInstance);
    save_register_state.DefineSafepoint();
    // Make sure the return value is preserved across the live register
    // restoring pop all.
    return_val = kReturnRegister0;
    MaglevAssembler::TemporaryRegisterScope temps(this);
    Register scratch = temps.AcquireScratch();
    if (register_snapshot.live_registers.has(return_val)) {
      DCHECK(!register_snapshot.live_registers.has(scratch));
      Move(scratch, return_val);
      return_val = scratch;
    }
  }
  // On failure, the returned value is Smi zero.
  CompareTaggedAndJumpIf(return_val, Smi::zero(), kEqual, fail);
}
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), CallRuntime(), CompareTaggedAndJumpIf(), v8::internal::DCHECK(), v8::internal::maglev::SaveRegisterStateForCall::DefineSafepoint(), v8::internal::RegListBase< RegisterT >::has(), v8::internal::kContextRegister, v8::internal::kEqual, v8::internal::kReturnRegister0, v8::internal::maglev::RegisterSnapshot::live_registers, Move(), native_context(), v8::internal::Register::no_reg(), Push(), and v8::internal::Smi::zero().
TryMigrateInstanceAndMarkMapAsMigrationTarget()
void v8::internal::maglev::MaglevAssembler::TryMigrateInstanceAndMarkMapAsMigrationTarget (Register object, RegisterSnapshot & register_snapshot)
Definition at line 705 of file maglev-assembler.cc.
                                                          {
  SaveRegisterStateForCall save_register_state(this, register_snapshot);
  Push(object);
  Move(kContextRegister, native_context().object());
  CallRuntime(Runtime::kTryMigrateInstanceAndMarkMapAsMigrationTarget);
  save_register_state.DefineSafepoint();
}
References CallRuntime(), v8::internal::maglev::SaveRegisterStateForCall::DefineSafepoint(), v8::internal::kContextRegister, Move(), native_context(), and Push().
TryTruncateDoubleToInt32()
void v8::internal::maglev::MaglevAssembler::TryTruncateDoubleToInt32 (Register dst, DoubleRegister src, Label * fail)
Definition at line 518 of file maglev-assembler-arm.cc.
                                                            {
  UseScratchRegisterScope temps(this);
  LowDwVfpRegister low_double = temps.AcquireLowD();
  SwVfpRegister temp_vfps = low_double.low();
  DoubleRegister converted_back = low_double;
  Label done;
  // Convert the input float64 value to int32.
  vcvt_s32_f64(temp_vfps, src);
  vmov(dst, temp_vfps);
  // Convert that int32 value back to float64.
  vcvt_f64_s32(converted_back, temp_vfps);
  // Check that the result of the float64->int32->float64 is equal to the input
  // (i.e. that the conversion didn't truncate.
  VFPCompareAndSetFlags(src, converted_back);
  JumpIf(kNotEqual, fail);
  // Check if {input} is -0.
  tst(dst, dst);
  JumpIf(kNotEqual, &done);
  // In case of 0, we need to check the high bits for the IEEE -0 pattern.
  {
    Register high_word32_of_input = temps.Acquire();
    VmovHigh(high_word32_of_input, src);
    cmp(high_word32_of_input, Operand(0));
    JumpIf(kLessThan, fail);
  }
  bind(&done);
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::UseScratchRegisterScope::AcquireLowD(), v8::internal::Assembler::bind(), v8::internal::Assembler::cmp(), JumpIf(), v8::internal::kLessThan, v8::internal::kNotEqual, v8::internal::LowDwVfpRegister::low(), v8::internal::Assembler::tst(), v8::internal::Assembler::vcvt_f64_s32(), v8::internal::Assembler::vcvt_s32_f64(), v8::internal::MacroAssembler::VFPCompareAndSetFlags(), v8::internal::Assembler::vmov(), and v8::internal::MacroAssembler::VmovHigh().
TryTruncateDoubleToUint32()
void v8::internal::maglev::MaglevAssembler::TryTruncateDoubleToUint32 (Register dst, DoubleRegister src, Label * fail)
Definition at line 553 of file maglev-assembler-arm.cc.
                                                             {
  UseScratchRegisterScope temps(this);
  LowDwVfpRegister low_double = temps.AcquireLowD();
  SwVfpRegister temp_vfps = low_double.low();
  DoubleRegister converted_back = low_double;
  Label done;
  // Convert the input float64 value to uint32.
  vcvt_u32_f64(temp_vfps, src);
  vmov(dst, temp_vfps);
  // Convert that uint32 value back to float64.
  vcvt_f64_u32(converted_back, temp_vfps);
  // Check that the result of the float64->uint32->float64 is equal to the input
  // (i.e. that the conversion didn't truncate.
  VFPCompareAndSetFlags(src, converted_back);
  JumpIf(kNotEqual, fail);
  // Check if {input} is -0.
  tst(dst, dst);
  JumpIf(kNotEqual, &done);
  // In case of 0, we need to check the high bits for the IEEE -0 pattern.
  {
    Register high_word32_of_input = temps.Acquire();
    VmovHigh(high_word32_of_input, src);
    cmp(high_word32_of_input, Operand(0));
    JumpIf(kLessThan, fail);
  }
  bind(&done);
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::UseScratchRegisterScope::AcquireLowD(), v8::internal::Assembler::bind(), v8::internal::Assembler::cmp(), JumpIf(), v8::internal::kLessThan, v8::internal::kNotEqual, v8::internal::LowDwVfpRegister::low(), v8::internal::Assembler::tst(), v8::internal::Assembler::vcvt_f64_u32(), v8::internal::Assembler::vcvt_u32_f64(), v8::internal::MacroAssembler::VFPCompareAndSetFlags(), v8::internal::Assembler::vmov(), and v8::internal::MacroAssembler::VmovHigh().
TypedArrayElementOperand()
MemOperand v8::internal::maglev::MaglevAssembler::TypedArrayElementOperand (Register data_pointer, Register index, int element_size) [inline]
Definition at line 313 of file maglev-assembler-arm-inl.h.
                                                             {
  add(data_pointer, data_pointer,
      Operand(index, LSL, ShiftFromScale(element_size)));
  return MemOperand(data_pointer);
}
References v8::internal::Assembler::add(), v8::internal::index, v8::internal::LSL, and v8::internal::maglev::ShiftFromScale().
Uint32ToDouble()
void v8::internal::maglev::MaglevAssembler::Uint32ToDouble (DoubleRegister result, Register src) [inline]
Definition at line 1273 of file maglev-assembler-arm-inl.h.
                                                          {
  UseScratchRegisterScope temps(this);
  SwVfpRegister temp_vfps = SwVfpRegister::no_reg();
  if (result.code() < 16) {
    temp_vfps = LowDwVfpRegister::from_code(result.code()).low();
  } else {
    temp_vfps = temps.AcquireS();
  }
  vmov(temp_vfps, src);
  vcvt_f64_u32(result, temp_vfps);
}
References v8::internal::UseScratchRegisterScope::AcquireS(), v8::internal::RegisterBase< LowDwVfpRegister, kDoubleCode_d16 >::from_code(), v8::internal::LowDwVfpRegister::low(), v8::internal::RegisterBase< SwVfpRegister, kSwVfpAfterLast >::no_reg(), v8::base::internal::result, v8::internal::Assembler::vcvt_f64_u32(), and v8::internal::Assembler::vmov().
Referenced by MaterialiseValueNode().
UncheckedSmiTagInt32() [1/2]
void v8::internal::maglev::MaglevAssembler::UncheckedSmiTagInt32 (Register dst, Register src) [inline]
Definition at line 839 of file maglev-assembler-inl.h.
                                                                            {
  SmiTagInt32AndSetFlags(dst, src);
  if (!SmiValuesAre32Bits()) {
    Assert(kNoOverflow, AbortReason::kInputDoesNotFitSmi);
  }
}
References v8::internal::MacroAssembler::Assert(), v8::internal::kNoOverflow, SmiTagInt32AndSetFlags(), and v8::internal::SmiValuesAre32Bits().
Referenced by UncheckedSmiTagInt32().
UncheckedSmiTagInt32() [2/2]
void v8::internal::maglev::MaglevAssembler::UncheckedSmiTagInt32 (Register reg) [inline]
Definition at line 846 of file maglev-assembler-inl.h.
                                                              {
  UncheckedSmiTagInt32(reg, reg);
}
References UncheckedSmiTagInt32().
UncheckedSmiTagUint32() [1/2]
void v8::internal::maglev::MaglevAssembler::UncheckedSmiTagUint32 (Register dst, Register src) [inline]
Definition at line 897 of file maglev-assembler-inl.h.
                                                                             {
  if (v8_flags.debug_code) {
    // Perform an unsigned comparison against Smi::kMaxValue.
    CompareInt32AndAssert(src, Smi::kMaxValue, kUnsignedLessThanEqual,
                          AbortReason::kInputDoesNotFitSmi);
  }
  SmiTagInt32AndSetFlags(dst, src);
  if (!SmiValuesAre32Bits()) {
    Assert(kNoOverflow, AbortReason::kInputDoesNotFitSmi);
  }
}
References v8::internal::MacroAssembler::Assert(), CompareInt32AndAssert(), v8::internal::Smi::kMaxValue, v8::internal::kNoOverflow, v8::internal::kUnsignedLessThanEqual, SmiTagInt32AndSetFlags(), v8::internal::SmiValuesAre32Bits(), and v8::internal::v8_flags.
Referenced by UncheckedSmiTagUint32().
UncheckedSmiTagUint32() [2/2]
void v8::internal::maglev::MaglevAssembler::UncheckedSmiTagUint32 (Register reg) [inline]
Definition at line 909 of file maglev-assembler-inl.h.
                                                               {
  UncheckedSmiTagUint32(reg, reg);
}
References UncheckedSmiTagUint32().
Member Data Documentation
code_gen_state_
MaglevCodeGenState* const v8::internal::maglev::MaglevAssembler::code_gen_state_ [private]
Definition at line 860 of file maglev-assembler.h.
Referenced by IsDeoptLabel().
scratch_register_scope_
TemporaryRegisterScope* v8::internal::maglev::MaglevAssembler::scratch_register_scope_ = nullptr [private]
Definition at line 861 of file maglev-assembler.h.
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::TemporaryRegisterScopeBase(), and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::~TemporaryRegisterScopeBase().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-assembler.h
/mnt/V8SourceCode/src/maglev/arm/maglev-assembler-arm-inl.h
/mnt/V8SourceCode/src/maglev/arm/maglev-assembler-arm.cc
/mnt/V8SourceCode/src/maglev/arm64/maglev-assembler-arm64-inl.h
/mnt/V8SourceCode/src/maglev/arm64/maglev-assembler-arm64.cc
/mnt/V8SourceCode/src/maglev/maglev-assembler-inl.h
/mnt/V8SourceCode/src/maglev/maglev-assembler.cc
/mnt/V8SourceCode/src/maglev/riscv/maglev-assembler-riscv-inl.h
/mnt/V8SourceCode/src/maglev/riscv/maglev-assembler-riscv.cc
/mnt/V8SourceCode/src/maglev/s390/maglev-assembler-s390-inl.h
/mnt/V8SourceCode/src/maglev/s390/maglev-assembler-s390.cc
/mnt/V8SourceCode/src/maglev/x64/maglev-assembler-x64-inl.h
/mnt/V8SourceCode/src/maglev/x64/maglev-assembler-x64.cc