v8::internal::Module Class Reference
#include <module.h>
Classes
struct Hash
class ResolveSet
Public Types
enum Status {
kUnlinked
, kPreLinking
, kLinking
, kLinked
,
kEvaluating
, kEvaluatingAsync
, kEvaluated
, kErrored
 }
using BodyDescriptor = FixedBodyDescriptor< kExportsOffset, kHeaderSize, kHeaderSize >
Public Member Functions
Tagged< Object > GetException ()
V8_WARN_UNUSED_RESULT bool IsGraphAsync (Isolate *isolate) const
Static Public Member Functions
static V8_WARN_UNUSED_RESULT bool Instantiate (Isolate *isolate, Handle< Module > module, v8::Local< v8::Context > context, v8::Module::ResolveModuleCallback module_callback, v8::Module::ResolveSourceCallback source_callback)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Evaluate (Isolate *isolate, Handle< Module > module)
static DirectHandle< JSModuleNamespace > GetModuleNamespace (Isolate *isolate, Handle< Module > module)
Protected Member Functions
void SetStatus (Status status)
void RecordError (Isolate *isolate, Tagged< Object > error)
Static Protected Member Functions
static V8_WARN_UNUSED_RESULT MaybeHandle< Cell > ResolveExport (Isolate *isolate, Handle< Module > module, DirectHandle< String > module_specifier, Handle< String > export_name, MessageLocation loc, bool must_resolve, ResolveSet *resolve_set)
static V8_WARN_UNUSED_RESULT bool PrepareInstantiate (Isolate *isolate, DirectHandle< Module > module, v8::Local< v8::Context > context, v8::Module::ResolveModuleCallback module_callback, v8::Module::ResolveSourceCallback source_callback)
static V8_WARN_UNUSED_RESULT bool FinishInstantiate (Isolate *isolate, Handle< Module > module, ZoneForwardList< Handle< SourceTextModule >> *stack, unsigned *dfs_index, Zone *zone)
static void Reset (Isolate *isolate, DirectHandle< Module > module)
static void ResetGraph (Isolate *isolate, DirectHandle< Module > module)
Friends
class Factory
Detailed Description
Definition at line 32 of file module.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::Module::BodyDescriptor = FixedBodyDescriptor<kExportsOffset, kHeaderSize, kHeaderSize>
Definition at line 78 of file module.h.
Member Enumeration Documentation
Status
enum v8::internal::Module::Status
Enumerator
kUnlinked
kPreLinking
kLinking
kLinked
kEvaluating
kEvaluatingAsync
kEvaluated
kErrored
Definition at line 37 of file module.h.
              {
    // Order matters!
    kUnlinked,
    kPreLinking,
    kLinking,
    kLinked,
    kEvaluating,
    kEvaluatingAsync,
    kEvaluated,
    kErrored
  };
Member Function Documentation
Evaluate()
MaybeDirectHandle< Object > v8::internal::Module::Evaluate (Isolate * isolate, Handle< Module > module) [static]
Definition at line 272 of file module.cc.
                                                                  {
#ifdef DEBUG
  PrintStatusMessage(*module, "Evaluating module ");
#endif // DEBUG
  int module_status = module->status();
  // In the event of errored evaluation, return a rejected promise.
  if (module_status == kErrored) {
    // If we have a top level capability we assume it has already been
    // rejected, and return it here. Otherwise create a new promise and
    // reject it with the module's exception.
    if (IsJSPromise(module->top_level_capability())) {
      DirectHandle<JSPromise> top_level_capability(
          Cast<JSPromise>(module->top_level_capability()), isolate);
      DCHECK(top_level_capability->status() == Promise::kRejected &&
             top_level_capability->result() == module->exception());
      return top_level_capability;
    }
    DirectHandle<JSPromise> capability = isolate->factory()->NewJSPromise();
    JSPromise::Reject(capability, direct_handle(module->exception(), isolate));
    return capability;
  }
  // Start of Evaluate () Concrete Method
  // 2. Assert: module.[[Status]] is one of LINKED, EVALUATING-ASYNC, or
  // EVALUATED.
  CHECK(module_status == kLinked || module_status == kEvaluatingAsync ||
        module_status == kEvaluated);
  // 3. If module.[[Status]] is either EVALUATING-ASYNC or EVALUATED, set module
  // to module.[[CycleRoot]].
  // A Synthetic Module has no children so it is its own cycle root.
  if (module_status >= kEvaluatingAsync && IsSourceTextModule(*module)) {
    module = Cast<SourceTextModule>(module)->GetCycleRoot(isolate);
  }
  // 4. If module.[[TopLevelCapability]] is not EMPTY, then
  // a. Return module.[[TopLevelCapability]].[[Promise]].
  if (IsJSPromise(module->top_level_capability())) {
    return direct_handle(Cast<JSPromise>(module->top_level_capability()),
                         isolate);
  }
  DCHECK(IsUndefined(module->top_level_capability()));
  if (IsSourceTextModule(*module)) {
    return SourceTextModule::Evaluate(isolate, Cast<SourceTextModule>(module));
  } else {
    return SyntheticModule::Evaluate(isolate, Cast<SyntheticModule>(module));
  }
}
References CHECK, v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::SyntheticModule::Evaluate(), v8::internal::SourceTextModule::Evaluate(), v8::internal::Isolate::factory(), kErrored, kEvaluated, kEvaluatingAsync, kLinked, v8::Promise::kRejected, v8::internal::Factory::NewJSPromise(), and v8::internal::JSPromise::Reject().
Referenced by v8::Module::Evaluate(), and v8::internal::SourceTextModule::InnerModuleEvaluation().
FinishInstantiate()
bool v8::internal::Module::FinishInstantiate (Isolate * isolate, Handle< Module > module, ZoneForwardList< Handle< SourceTextModule >> * stack, unsigned * dfs_index, Zone * zone) [static], [protected]
Definition at line 255 of file module.cc.
                                                                {
  DCHECK_NE(module->status(), kEvaluating);
  if (module->status() >= kLinking) return true;
  DCHECK_EQ(module->status(), kPreLinking);
  STACK_CHECK(isolate, false);
  if (IsSourceTextModule(*module)) {
    return SourceTextModule::FinishInstantiate(
        isolate, Cast<SourceTextModule>(module), stack, dfs_index, zone);
  } else {
    return SyntheticModule::FinishInstantiate(isolate,
                                              Cast<SyntheticModule>(module));
  }
}
References DCHECK_EQ, DCHECK_NE, v8::internal::SyntheticModule::FinishInstantiate(), v8::internal::SourceTextModule::FinishInstantiate(), kEvaluating, kLinking, kPreLinking, v8::internal::stack, and STACK_CHECK.
Referenced by v8::internal::SourceTextModule::FinishInstantiate(), and Instantiate().
GetException()
Tagged< Object > v8::internal::Module::GetException ()
Definition at line 180 of file module.cc.
                                    {
  DisallowGarbageCollection no_gc;
  DCHECK_EQ(status(), Module::kErrored);
  DCHECK(!IsTheHole(exception()));
  return exception();
}
References v8::internal::DCHECK(), DCHECK_EQ, kErrored, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::status.
GetModuleNamespace()
DirectHandle< JSModuleNamespace > v8::internal::Module::GetModuleNamespace (Isolate * isolate, Handle< Module > module) [static]
Definition at line 324 of file module.cc.
                                             {
  DirectHandle<HeapObject> object(module->module_namespace(), isolate);
  ReadOnlyRoots roots(isolate);
  if (!IsUndefined(*object, roots)) {
    // Namespace object already exists.
    return Cast<JSModuleNamespace>(object);
  }
  // Collect the export names.
  Zone zone(isolate->allocator(), ZONE_NAME);
  UnorderedModuleSet visited(&zone);
  if (IsSourceTextModule(*module)) {
    SourceTextModule::FetchStarExports(isolate, Cast<SourceTextModule>(module),
                                       &zone, &visited);
  }
  DirectHandle<ObjectHashTable> exports(module->exports(), isolate);
  ZoneVector<IndirectHandle<String>> names(&zone);
  names.reserve(exports->NumberOfElements());
  for (InternalIndex i : exports->IterateEntries()) {
    Tagged<Object> key;
    if (!exports->ToKey(roots, i, &key)) continue;
    names.push_back(handle(Cast<String>(key), isolate));
  }
  DCHECK_EQ(static_cast<int>(names.size()), exports->NumberOfElements());
  // Sort them alphabetically.
  std::sort(names.begin(), names.end(),
            [&isolate](IndirectHandle<String> a, IndirectHandle<String> b) {
              return String::Compare(isolate, a, b) ==
                     ComparisonResult::kLessThan;
            });
  // Create the namespace object (initially empty).
  DirectHandle<JSModuleNamespace> ns =
      isolate->factory()->NewJSModuleNamespace();
  ns->set_module(*module);
  module->set_module_namespace(*ns);
  // Create the properties in the namespace object. Transition the object
  // to dictionary mode so that property addition is faster.
  PropertyAttributes attr = DONT_DELETE;
  JSObject::NormalizeProperties(isolate, ns, CLEAR_INOBJECT_PROPERTIES,
                                static_cast<int>(names.size()),
                                "JSModuleNamespace");
  JSObject::NormalizeElements(isolate, ns);
  for (const auto& name : names) {
    uint32_t index = 0;
    if (name->AsArrayIndex(&index)) {
      JSObject::SetNormalizedElement(
          ns, index, Accessors::MakeModuleNamespaceEntryInfo(isolate, name),
          PropertyDetails(PropertyKind::kAccessor, attr,
                          PropertyCellType::kMutable));
    } else {
      JSObject::SetNormalizedProperty(
          ns, name, Accessors::MakeModuleNamespaceEntryInfo(isolate, name),
          PropertyDetails(PropertyKind::kAccessor, attr,
                          PropertyCellType::kMutable));
    }
  }
  JSObject::PreventExtensions(isolate, ns, kThrowOnError).ToChecked();
  // Optimize the namespace object as a prototype, for two reasons:
  // - The object's map is guaranteed not to be shared. ICs rely on this.
  // - We can store a pointer from the map back to the namespace object.
  // Turbofan can use this for inlining the access.
  JSObject::OptimizeAsPrototype(ns);
  DirectHandle<PrototypeInfo> proto_info =
      Map::GetOrCreatePrototypeInfo(ns, isolate);
  proto_info->set_module_namespace(*ns);
  return ns;
}
References v8::internal::Isolate::allocator(), v8::internal::ZoneVector< T >::begin(), v8::internal::CLEAR_INOBJECT_PROPERTIES, DCHECK_EQ, v8::internal::DONT_DELETE, v8::internal::ZoneVector< T >::end(), v8::internal::Isolate::factory(), v8::internal::SourceTextModule::FetchStarExports(), v8::internal::Map::GetOrCreatePrototypeInfo(), v8::internal::handle(), v8::internal::index, v8::internal::kAccessor, v8::internal::key, v8::internal::kMutable, v8::internal::kThrowOnError, v8::internal::Accessors::MakeModuleNamespaceEntryInfo(), v8::internal::name, v8::internal::Factory::NewJSModuleNamespace(), v8::internal::JSObject::NormalizeElements(), v8::internal::JSObject::NormalizeProperties(), v8::internal::JSObject::OptimizeAsPrototype(), v8::internal::JSObject::PreventExtensions(), v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::reserve(), v8::internal::JSObject::SetNormalizedElement(), v8::internal::JSObject::SetNormalizedProperty(), v8::internal::ZoneVector< T >::size(), v8::base::sort(), and ZONE_NAME.
Referenced by v8::Module::GetModuleNamespace(), and v8::internal::SourceTextModule::GetModuleNamespace().
Instantiate()
bool v8::internal::Module::Instantiate (Isolate * isolate, Handle< Module > module, v8::Local< v8::Context > context, v8::Module::ResolveModuleCallback module_callback, v8::Module::ResolveSourceCallback source_callback) [static]
Definition at line 206 of file module.cc.
                                                                        {
#ifdef DEBUG
  PrintStatusMessage(*module, "Instantiating module ");
#endif // DEBUG
  if (!PrepareInstantiate(isolate, module, context, module_callback,
                          source_callback)) {
    ResetGraph(isolate, module);
    DCHECK_EQ(module->status(), kUnlinked);
    return false;
  }
  Zone zone(isolate->allocator(), ZONE_NAME);
  ZoneForwardList<Handle<SourceTextModule>> stack(&zone);
  unsigned dfs_index = 0;
  if (!FinishInstantiate(isolate, module, &stack, &dfs_index, &zone)) {
    ResetGraph(isolate, module);
    DCHECK_EQ(module->status(), kUnlinked);
    return false;
  }
  DCHECK(module->status() == kLinked || module->status() == kEvaluated ||
         module->status() == kEvaluatingAsync || module->status() == kErrored);
  DCHECK(stack.empty());
  return true;
}
References v8::internal::Isolate::allocator(), v8::internal::DCHECK(), DCHECK_EQ, FinishInstantiate(), kErrored, kEvaluated, kEvaluatingAsync, kLinked, kUnlinked, PrepareInstantiate(), ResetGraph(), v8::internal::stack, and ZONE_NAME.
Referenced by v8::Module::InstantiateModule().
IsGraphAsync()
bool v8::internal::Module::IsGraphAsync (Isolate * isolate) const
Definition at line 490 of file module.cc.
                                                {
  DisallowGarbageCollection no_gc;
  // Only SourceTextModules may be async.
  if (!IsSourceTextModule(*this)) return false;
  Tagged<SourceTextModule> root = Cast<SourceTextModule>(*this);
  Zone zone(isolate->allocator(), ZONE_NAME);
  const size_t bucket_count = 2;
  ZoneUnorderedSet<Tagged<Module>, Module::Hash> visited(&zone, bucket_count);
  ZoneVector<Tagged<SourceTextModule>> worklist(&zone);
  visited.insert(root);
  worklist.push_back(root);
  do {
    Tagged<SourceTextModule> current = worklist.back();
    worklist.pop_back();
    DCHECK_GE(current->status(), kLinked);
    if (current->has_toplevel_await()) return true;
    Tagged<FixedArray> requested_modules = current->requested_modules();
    for (int i = 0, length = requested_modules->length(); i < length; ++i) {
      Tagged<Module> descendant = Cast<Module>(requested_modules->get(i));
      if (IsSourceTextModule(descendant)) {
        const bool cycle = !visited.insert(descendant).second;
        if (!cycle) worklist.push_back(Cast<SourceTextModule>(descendant));
      }
    }
  } while (!worklist.empty());
  return false;
}
References v8::internal::Isolate::allocator(), v8::internal::ZoneVector< T >::back(), DCHECK_GE, v8::internal::ZoneVector< T >::empty(), kLinked, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::ZoneVector< T >::pop_back(), v8::internal::ZoneVector< T >::push_back(), and ZONE_NAME.
PrepareInstantiate()
bool v8::internal::Module::PrepareInstantiate (Isolate * isolate, DirectHandle< Module > module, v8::Local< v8::Context > context, v8::Module::ResolveModuleCallback module_callback, v8::Module::ResolveSourceCallback source_callback) [static], [protected]
Definition at line 234 of file module.cc.
                                                   {
  DCHECK_NE(module->status(), kEvaluating);
  DCHECK_NE(module->status(), kLinking);
  if (module->status() >= kPreLinking) return true;
  module->SetStatus(kPreLinking);
  STACK_CHECK(isolate, false);
  if (IsSourceTextModule(*module)) {
    return SourceTextModule::PrepareInstantiate(
        isolate, Cast<SourceTextModule>(module), context, module_callback,
        source_callback);
  } else {
    return SyntheticModule::PrepareInstantiate(
        isolate, Cast<SyntheticModule>(module), context);
  }
}
References DCHECK_NE, kEvaluating, kLinking, kPreLinking, v8::internal::SourceTextModule::PrepareInstantiate(), v8::internal::SyntheticModule::PrepareInstantiate(), and STACK_CHECK.
Referenced by Instantiate(), and v8::internal::SourceTextModule::PrepareInstantiate().
RecordError()
void v8::internal::Module::RecordError (Isolate * isolate, Tagged< Object > error) [protected]
Definition at line 104 of file module.cc.
                                                               {
  DisallowGarbageCollection no_gc;
  // Allow overriding exceptions with termination exceptions.
  DCHECK_IMPLIES(isolate->is_catchable_by_javascript(error),
                 IsTheHole(exception(), isolate));
  DCHECK(!IsTheHole(error, isolate));
  if (IsSourceTextModule(*this)) {
    // Revert to minimal SFI in case we have already been instantiating or
    // evaluating.
    auto self = Cast<SourceTextModule>(*this);
    self->set_code(self->GetSharedFunctionInfo());
  }
  SetStatusInternal(*this, Module::kErrored);
  if (isolate->is_catchable_by_javascript(error)) {
    set_exception(error);
  } else {
    // v8::TryCatch uses `null` for termination exceptions.
    set_exception(ReadOnlyRoots(isolate).null_value());
  }
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::Isolate::is_catchable_by_javascript(), kErrored, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::anonymous_namespace{module.cc}::SetStatusInternal().
Reset()
void v8::internal::Module::Reset (Isolate * isolate, DirectHandle< Module > module) [static], [protected]
Definition at line 158 of file module.cc.
                                                                {
  DCHECK(module->status() == kPreLinking || module->status() == kLinking);
  DCHECK(IsTheHole(module->exception(), isolate));
  // The namespace object cannot exist, because it would have been created
  // by RunInitializationCode, which is called only after this module's SCC
  // succeeds instantiation.
  DCHECK(!IsJSModuleNamespace(module->module_namespace()));
  const int export_count =
      IsSourceTextModule(*module)
          ? Cast<SourceTextModule>(*module)->regular_exports()->length()
          : Cast<SyntheticModule>(*module)->export_names()->length();
  DirectHandle<ObjectHashTable> exports =
      ObjectHashTable::New(isolate, export_count);
  if (IsSourceTextModule(*module)) {
    SourceTextModule::Reset(isolate, Cast<SourceTextModule>(module));
  }
  module->set_exports(*exports);
  SetStatusInternal(*module, kUnlinked);
}
References v8::internal::DCHECK(), kLinking, kPreLinking, kUnlinked, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::SourceTextModule::Reset(), and v8::internal::anonymous_namespace{module.cc}::SetStatusInternal().
Referenced by ResetGraph().
ResetGraph()
void v8::internal::Module::ResetGraph (Isolate * isolate, DirectHandle< Module > module) [static], [protected]
Definition at line 125 of file module.cc.
                                                                     {
  DCHECK_NE(module->status(), kEvaluating);
  if (module->status() != kPreLinking && module->status() != kLinking) {
    return;
  }
  DirectHandle<FixedArray> requested_modules =
      IsSourceTextModule(*module)
          ? DirectHandle<FixedArray>(
                Cast<SourceTextModule>(*module)->requested_modules(), isolate)
          : DirectHandle<FixedArray>();
  Reset(isolate, module);
  if (!IsSourceTextModule(*module)) {
    DCHECK(IsSyntheticModule(*module));
    return;
  }
  for (int i = 0; i < requested_modules->length(); ++i) {
    DirectHandle<Object> descendant(requested_modules->get(i), isolate);
    if (IsModule(*descendant)) {
      ResetGraph(isolate, Cast<Module>(descendant));
    } else {
      // The requested module is either an undefined or a WasmModule object.
#if V8_ENABLE_WEBASSEMBLY
      DCHECK(IsUndefined(*descendant, isolate) ||
             IsWasmModuleObject(*descendant));
#else
      DCHECK(IsUndefined(*descendant, isolate));
#endif
    }
  }
}
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsModule(), kEvaluating, kLinking, kPreLinking, and Reset().
Referenced by Instantiate().
ResolveExport()
MaybeHandle< Cell > v8::internal::Module::ResolveExport (Isolate * isolate, Handle< Module > module, DirectHandle< String > module_specifier, Handle< String > export_name, MessageLocation loc, bool must_resolve, Module::ResolveSet * resolve_set) [static], [protected]
Definition at line 187 of file module.cc.
                                                                       {
  DCHECK_GE(module->status(), kPreLinking);
  DCHECK_NE(module->status(), kEvaluating);
  if (IsSourceTextModule(*module)) {
    return SourceTextModule::ResolveExport(
        isolate, Cast<SourceTextModule>(module), module_specifier, export_name,
        loc, must_resolve, resolve_set);
  } else {
    return SyntheticModule::ResolveExport(
        isolate, Cast<SyntheticModule>(module), module_specifier, export_name,
        loc, must_resolve);
  }
}
References DCHECK_GE, DCHECK_NE, kEvaluating, kPreLinking, v8::internal::loc, v8::internal::SyntheticModule::ResolveExport(), and v8::internal::SourceTextModule::ResolveExport().
Referenced by v8::internal::SourceTextModule::ResolveImport().
SetStatus()
void v8::internal::Module::SetStatus (Status status) [protected]
Definition at line 97 of file module.cc.
                                        {
  DisallowGarbageCollection no_gc;
  DCHECK_LE(status(), new_status);
  DCHECK_NE(new_status, Module::kErrored);
  SetStatusInternal(*this, new_status);
}
References DCHECK_LE, DCHECK_NE, kErrored, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::anonymous_namespace{module.cc}::SetStatusInternal(), and v8::internal::status.
Friends And Related Function Documentation
Factory
friend class Factory [friend]
Definition at line 84 of file module.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/module.h
/mnt/V8SourceCode/src/objects/module.cc