v8::internal::compiler::EscapeAnalysis Class Reference
#include <escape-analysis.h>
Public Member Functions
EscapeAnalysis (JSGraph *jsgraph, TickCounter *tick_counter, Zone *zone)
EscapeAnalysisResult analysis_result ()
Private Member Functions
void Reduce (Node *node, Reduction *reduction)
JSGraph * jsgraph ()
Isolate * isolate () const
Private Attributes
EscapeAnalysisTracker * tracker_
JSGraph * jsgraph_
Detailed Description
Definition at line 176 of file escape-analysis.h.
Constructor & Destructor Documentation
EscapeAnalysis()
v8::internal::compiler::EscapeAnalysis::EscapeAnalysis (JSGraph * jsgraph, TickCounter * tick_counter, Zone * zone)
Definition at line 935 of file escape-analysis.cc.
    : EffectGraphReducer(
          jsgraph->graph(),
          [this](Node* node, Reduction* reduction) { Reduce(node, reduction); },
          tick_counter, zone),
      tracker_(zone->New<EscapeAnalysisTracker>(jsgraph, this, zone)),
      jsgraph_(jsgraph) {}
References Reduce().
Member Function Documentation
analysis_result()
EscapeAnalysisResult v8::internal::compiler::EscapeAnalysis::analysis_result () [inline]
Definition at line 181 of file escape-analysis.h.
                                         {
    DCHECK(Complete());
    return EscapeAnalysisResult(tracker_);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::EscapeAnalysisPhase::Run().
isolate()
Isolate* v8::internal::compiler::EscapeAnalysis::isolate () const [inline], [private]
Definition at line 189 of file escape-analysis.h.
{ return jsgraph_->isolate(); }
References v8::internal::Factory::isolate().
jsgraph()
JSGraph* v8::internal::compiler::EscapeAnalysis::jsgraph () [inline], [private]
Definition at line 188 of file escape-analysis.h.
{ return jsgraph_; }
Reduce()
void v8::internal::compiler::EscapeAnalysis::Reduce (Node * node, Reduction * reduction) [private]
Definition at line 927 of file escape-analysis.cc.
                                                            {
  const Operator* op = node->op();
  TRACE("Reducing %s#%d\n", op->mnemonic(), node->id());
  EscapeAnalysisTracker::Scope current(this, tracker_, node, reduction);
  ReduceNode(op, &current, jsgraph());
}
References v8::internal::compiler::Node::id(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), and v8::internal::TRACE().
Referenced by EscapeAnalysis().
Member Data Documentation
jsgraph_
JSGraph* v8::internal::compiler::EscapeAnalysis::jsgraph_ [private]
Definition at line 191 of file escape-analysis.h.
tracker_
EscapeAnalysisTracker* v8::internal::compiler::EscapeAnalysis::tracker_ [private]
Definition at line 190 of file escape-analysis.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/escape-analysis.h
/mnt/V8SourceCode/src/compiler/escape-analysis.cc