v8::internal::CompilationCacheRegExp Class Reference
#include <compilation-cache.h>
Public Member Functions
CompilationCacheRegExp (Isolate *isolate)
MaybeDirectHandle< RegExpData > Lookup (DirectHandle< String > source, JSRegExp::Flags flags)
void Put (DirectHandle< String > source, JSRegExp::Flags flags, DirectHandle< RegExpData > data)
DirectHandle< CompilationCacheTable > GetTable (int generation)
void Age ()
void Iterate (RootVisitor *v)
void Clear ()
Static Public Attributes
static const int kGenerations = 2
Private Member Functions
Isolate * isolate () const
DISALLOW_IMPLICIT_CONSTRUCTORS (CompilationCacheRegExp)
Private Attributes
Isolate *const isolate_
Tagged< Object > tables_ [kGenerations]
Detailed Description
Definition at line 105 of file compilation-cache.h.
Constructor & Destructor Documentation
CompilationCacheRegExp()
v8::internal::CompilationCacheRegExp::CompilationCacheRegExp (Isolate * isolate) [inline], [explicit]
Definition at line 107 of file compilation-cache.h.
: isolate_(isolate) {}
Member Function Documentation
Age()
void v8::internal::CompilationCacheRegExp::Age ()
Definition at line 54 of file compilation-cache.cc.
                                 {
  static_assert(kGenerations > 1);
  // Age the generations implicitly killing off the oldest.
  for (int i = kGenerations - 1; i > 0; i--) {
    tables_[i] = tables_[i - 1];
  }
  // Set the first generation as unborn.
  tables_[0] = ReadOnlyRoots(isolate()).undefined_value();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate(), kGenerations, and tables_.
Referenced by v8::internal::CompilationCache::MarkCompactPrologue().
Clear()
void v8::internal::CompilationCacheRegExp::Clear ()
Definition at line 124 of file compilation-cache.cc.
                                   {
  MemsetPointer(reinterpret_cast<Address*>(tables_),
                ReadOnlyRoots(isolate()).undefined_value().ptr(), kGenerations);
}
References isolate(), kGenerations, v8::internal::MemsetPointer(), and tables_.
Referenced by v8::internal::CompilationCache::Clear().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::CompilationCacheRegExp::DISALLOW_IMPLICIT_CONSTRUCTORS (CompilationCacheRegExp) [private]
GetTable()
DirectHandle< CompilationCacheTable > v8::internal::CompilationCacheRegExp::GetTable (int generation)
Definition at line 39 of file compilation-cache.cc.
                    {
  DCHECK_LT(generation, kGenerations);
  DirectHandle<CompilationCacheTable> result;
  if (IsUndefined(tables_[generation], isolate())) {
    result = CompilationCacheTable::New(isolate(), kInitialCacheSize);
    tables_[generation] = *result;
  } else {
    Tagged<CompilationCacheTable> table =
        Cast<CompilationCacheTable>(tables_[generation]);
    result = DirectHandle<CompilationCacheTable>(table, isolate());
  }
  return result;
}
References DCHECK_LT, isolate(), kGenerations, v8::internal::kInitialCacheSize, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::base::internal::result, and tables_.
Referenced by Lookup(), and Put().
isolate()
Isolate* v8::internal::CompilationCacheRegExp::isolate () const [inline], [private]
Definition at line 133 of file compilation-cache.h.
{ return isolate_; }
References isolate_.
Referenced by Age(), Clear(), GetTable(), Lookup(), and Put().
Iterate()
void v8::internal::CompilationCacheRegExp::Iterate (RootVisitor * v)
Definition at line 114 of file compilation-cache.cc.
                                                   {
  v->VisitRootPointers(Root::kCompilationCache, nullptr,
                       FullObjectSlot(&tables_[0]),
                       FullObjectSlot(&tables_[kGenerations]));
}
References kGenerations, tables_, and v8::internal::RootVisitor::VisitRootPointers().
Referenced by v8::internal::CompilationCache::Iterate().
Lookup()
MaybeDirectHandle< RegExpData > v8::internal::CompilationCacheRegExp::Lookup (DirectHandle< String > source, JSRegExp::Flags flags)
Definition at line 197 of file compilation-cache.cc.
                                                      {
  HandleScope scope(isolate());
  // Make sure not to leak the table into the surrounding handle
  // scope. Otherwise, we risk keeping old tables around even after
  // having cleared the cache.
  DirectHandle<Object> result = isolate()->factory()->undefined_value();
  int generation;
  for (generation = 0; generation < kGenerations; generation++) {
    DirectHandle<CompilationCacheTable> table = GetTable(generation);
    result = table->LookupRegExp(source, flags);
    if (IsRegExpDataWrapper(*result)) break;
  }
  if (IsRegExpDataWrapper(*result)) {
    Handle<RegExpData> data(Cast<RegExpDataWrapper>(result)->data(isolate()),
                            isolate());
    if (generation != 0) {
      Put(source, flags, data);
    }
    isolate()->counters()->compilation_cache_hits()->Increment();
    return scope.CloseAndEscape(data);
  } else {
    isolate()->counters()->compilation_cache_misses()->Increment();
    return MaybeDirectHandle<RegExpData>();
  }
}
References v8::internal::Isolate::counters(), v8::internal::Isolate::factory(), v8::internal::flags, GetTable(), isolate(), kGenerations, Put(), and v8::base::internal::result.
Referenced by v8::internal::CompilationCache::LookupRegExp().
Put()
void v8::internal::CompilationCacheRegExp::Put (DirectHandle< String > source, JSRegExp::Flags flags, DirectHandle< RegExpData > data)
Definition at line 224 of file compilation-cache.cc.
                                                                {
  HandleScope scope(isolate());
  DirectHandle<CompilationCacheTable> table = GetTable(0);
  tables_[0] =
      *CompilationCacheTable::PutRegExp(isolate(), table, source, flags, data);
}
References v8::internal::flags, GetTable(), isolate(), v8::internal::CompilationCacheTable::PutRegExp(), and tables_.
Referenced by Lookup(), and v8::internal::CompilationCache::PutRegExp().
Member Data Documentation
isolate_
Isolate* const v8::internal::CompilationCacheRegExp::isolate_ [private]
Definition at line 135 of file compilation-cache.h.
Referenced by isolate().
kGenerations
const int v8::internal::CompilationCacheRegExp::kGenerations = 2 [static]
Definition at line 116 of file compilation-cache.h.
Referenced by Age(), Clear(), GetTable(), Iterate(), and Lookup().
tables_
Tagged<Object> v8::internal::CompilationCacheRegExp::tables_[kGenerations] [private]
Definition at line 136 of file compilation-cache.h.
Referenced by Age(), Clear(), GetTable(), Iterate(), and Put().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/compilation-cache.h
/mnt/V8SourceCode/src/codegen/compilation-cache.cc