v8::internal::wasm::HeapType Class Reference
#include <value-type.h>
Public Types
enum Representation : uint32_t {
kFunc = kV8MaxWasmTypes
, kEq
, kI31
, kStruct
,
kArray
, kAny
, kExtern
, kExternString
,
kExn
, kString
, kStringViewWtf8
, kStringViewWtf16
,
kStringViewIter
, kNone
, kNoFunc
, kNoExtern
,
kNoExn
, kCont
, kContShared
, kNoCont
,
kFuncShared
, kEqShared
, kI31Shared
, kStructShared
,
kArrayShared
, kAnyShared
, kExternShared
, kExternStringShared
,
kExnShared
, kStringShared
, kStringViewWtf8Shared
, kStringViewWtf16Shared
,
kStringViewIterShared
, kNoneShared
, kNoFuncShared
, kNoExternShared
,
kNoExnShared
, kNoContShared
, kTop
, kBottom
 }
Public Member Functions
constexpr HeapType AsExact (Exactness exact=Exactness::kExact) const
int32_t code () const
constexpr ModuleTypeIndex ref_index () const
constexpr bool operator== (HeapType other) const
std::string name () const
constexpr Representation representation () const
constexpr bool is_index () const
Static Public Member Functions
static constexpr HeapType Generic (GenericKind kind, bool shared)
static constexpr HeapType Index (ModuleTypeIndex index, bool shared, RefTypeKind kind, Exactness exact=Exactness::kAnySubtype)
static constexpr HeapType FromBits (uint32_t bits)
static constexpr HeapType from_code (uint8_t code, bool is_shared)
Private Member Functions
constexpr bool is_nullable () const
constexpr bool is_non_nullable () const
constexpr Nullability nullability () const
Additional Inherited Members
Detailed Description
Definition at line 717 of file value-type.h.
Member Enumeration Documentation
Representation
enum v8::internal::wasm::HeapType::Representation : uint32_t
Enumerator
kFunc
kEq
kI31
kStruct
kArray
kAny
kExtern
kExternString
kExn
kString
kStringViewWtf8
kStringViewWtf16
kStringViewIter
kNone
kNoFunc
kNoExtern
kNoExn
kCont
kContShared
kNoCont
kFuncShared
kEqShared
kI31Shared
kStructShared
kArrayShared
kAnyShared
kExternShared
kExternStringShared
kExnShared
kStringShared
kStringViewWtf8Shared
kStringViewWtf16Shared
kStringViewIterShared
kNoneShared
kNoFuncShared
kNoExternShared
kNoExnShared
kNoContShared
kTop
kBottom
Definition at line 790 of file value-type.h.
                      : uint32_t {
    kFunc = kV8MaxWasmTypes, // shorthand: c
    kEq, // shorthand: q
    kI31, // shorthand: j
    kStruct, // shorthand: o
    kArray, // shorthand: g
    kAny, //
    kExtern, // shorthand: a.
    kExternString, // Internal type for optimization purposes.
                              // Subtype of extern.
                              // Used by the js-builtin-strings proposal.
    kExn, //
    kString, // shorthand: w.
    kStringViewWtf8, // shorthand: x.
    kStringViewWtf16, // shorthand: y.
    kStringViewIter, // shorthand: z.
    kNone, //
    kNoFunc, //
    kNoExtern, //
    kNoExn, //
    kCont, // shorthand: k.
    kContShared,
    kNoCont, // bottom continuation type
    kFuncShared,
    kEqShared,
    kI31Shared,
    kStructShared,
    kArrayShared,
    kAnyShared,
    kExternShared,
    kExternStringShared,
    kExnShared,
    kStringShared,
    kStringViewWtf8Shared,
    kStringViewWtf16Shared,
    kStringViewIterShared,
    kNoneShared,
    kNoFuncShared,
    kNoExternShared,
    kNoExnShared,
    kNoContShared,
    // This value is an internal type (not part of the Wasm spec) that
    // is the common supertype across all type hierarchies. It should never
    // appear in validated Wasm programs, but is used to signify that we don't
    // have any information about a particular value and to prevent bugs in our
    // typed optimizations, see crbug.com/361652141. Note: kTop is the neutral
    // element wrt. to intersection (whereas kBottom is for union), and kBottom
    // is indicating unreachable code, which might be used for subsequent
    // optimizations, e.g., DCE.
    kTop,
    // This value is used to represent failures in the parsing of heap types and
    // does not correspond to a Wasm heap type. It has to be last in this list.
    kBottom
  };
Member Function Documentation
AsExact()
constexpr HeapType v8::internal::wasm::HeapType::AsExact (Exactness exact = Exactness::kExact) const [inline], [constexpr]
Definition at line 756 of file value-type.h.
                                                                      {
    DCHECK(exact == Exactness::kAnySubtype || has_index());
    return HeapType{ValueTypeBase(
        value_type_impl::IsExactField::update(raw_bit_field(), exact))};
  }
References v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::kAnySubtype, v8::internal::wasm::ValueTypeBase::raw_bit_field(), v8::base::BitField< T, shift, size, U >::update(), and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastDesc(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastDescFail().
code()
int32_t v8::internal::wasm::HeapType::code () const [inline]
Definition at line 762 of file value-type.h.
                       {
    if (has_index()) return static_cast<int32_t>(ref_index().index);
    // Value type codes represent the first byte of the LEB128 encoding. To get
    // the int32 represented by a code, we sign-extend it from 7 to 32 bits.
    return 0xFFFF'FF80 | value_type_code_generic();
  }
References v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::TypeIndex::index, ref_index(), and v8::internal::wasm::ValueTypeBase::value_type_code_generic().
Referenced by v8::internal::wasm::LocalDeclEncoder::Emit(), from_code(), and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpressionWithoutEnd().
from_code()
static constexpr HeapType v8::internal::wasm::HeapType::from_code (uint8_t code, bool is_shared) [inline], [static], [constexpr]
Definition at line 733 of file value-type.h.
                                                                    {
    constexpr uint8_t kFirst = ValueTypeCode::kFirstHeapTypeCode;
    constexpr uint8_t kLast = ValueTypeCode::kLastHeapTypeCode;
    if (code < kFirst || code > kLast) {
      return Generic(GenericKind::kBottom, false);
    }
    constexpr size_t kNumCases = kLast - kFirst + 1;
    constexpr std::array<GenericKind, kNumCases> kLookupTable =
        base::make_array<kNumCases>([](size_t i) {
          switch (i) {
#define CASE(name, code, ...) \
  case (k##code##Code - kFirst): \
    static_assert(k##code##Code >= kFirst && k##code##Code <= kLast); \
    return GenericKind::k##name;
            FOREACH_ABSTRACT_TYPE(CASE)
#undef CASE
            default:
              return GenericKind::kBottom;
          }
        });
    return Generic(kLookupTable[code - kFirst], is_shared);
  }
References CASE, code(), FOREACH_ABSTRACT_TYPE, Generic(), v8::internal::wasm::ValueTypeBase::is_shared(), v8::internal::wasm::kFirstHeapTypeCode, v8::internal::kLast, and v8::internal::wasm::kLastHeapTypeCode.
Referenced by v8::internal::wasm::value_type_reader::read_heap_type(), and v8::internal::wasm::value_type_reader::read_value_type().
FromBits()
static constexpr HeapType v8::internal::wasm::HeapType::FromBits (uint32_t bits) [inline], [static], [constexpr]
Definition at line 727 of file value-type.h.
                                                    {
    HeapType type{ValueTypeBase(bits)};
    DCHECK(!type.is_numeric());
    return type;
  }
References v8::internal::DCHECK(), v8::internal::tracing::type, and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::WasmInitExpr::heap_type(), v8::internal::wasm::Handlers< Compressed >::RefCast(), v8::internal::wasm::Handlers< Compressed >::RefTest(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCast(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCastFail(), v8::internal::wasm::ConstantExpression::type(), and v8::internal::wasm::WasmInstruction::Optional::GC_HeapTypeImmediate::type().
Generic()
static constexpr HeapType v8::internal::wasm::HeapType::Generic (GenericKind kind, bool shared) [inline], [static], [constexpr]
Definition at line 719 of file value-type.h.
                                                                   {
    return HeapType{ValueTypeBase(kind, kNullable, shared)};
  }
References v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::kNullable, and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::choose_sub_type(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestor(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestorWithAbstract(), from_code(), and v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::NullSentinelImpl().
Index()
static constexpr HeapType v8::internal::wasm::HeapType::Index (ModuleTypeIndex index, bool shared, RefTypeKind kind, Exactness exact = Exactness::kAnySubtype) [inline], [static], [constexpr]
Definition at line 722 of file value-type.h.
                                                                          {
    return HeapType{ValueTypeBase(index, kNullable, exact, shared, kind)};
  }
References v8::internal::index, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::kNullable, and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_copy(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_fill(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_set(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::call(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::choose_sub_type(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestor(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::GenerateRef(), v8::internal::wasm::SigIndexImmediate::heap_type(), v8::internal::wasm::ContIndexImmediate::heap_type(), v8::internal::wasm::StructIndexImmediate::heap_type(), v8::internal::wasm::ArrayIndexImmediate::heap_type(), v8::internal::wasm::WasmModule::heap_type(), v8::internal::wasm::ModuleDisassembler::PrintTypeDefinition(), v8::internal::wasm::value_type_reader::read_heap_type(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_fromcharcodearray(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_fromutf8array(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_intocharcodearray(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::string_intoutf8array(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get_helper(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_set().
is_index()
constexpr bool v8::internal::wasm::HeapType::is_index () const [inline], [constexpr]
Definition at line 847 of file value-type.h.
{ return has_index(); }
References v8::internal::wasm::ValueTypeBase::has_index().
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_base_type_definition(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::Handlers< Compressed >::DoRefCast(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::HeapType(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast().
is_non_nullable()
constexpr bool v8::internal::wasm::HeapType::is_non_nullable () const [constexpr], [private]
is_nullable()
constexpr bool v8::internal::wasm::HeapType::is_nullable () const [constexpr], [private]
name()
std::string v8::internal::wasm::HeapType::name () const [inline]
Definition at line 780 of file value-type.h.
                         {
    if (has_index()) {
      if (is_exact()) return "exact " + std::to_string(raw_index().index);
      return std::to_string(raw_index().index);
    }
    return generic_heaptype_name();
  }
References v8::internal::wasm::ValueTypeBase::generic_heaptype_name(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::index, v8::internal::wasm::ValueTypeBase::is_exact(), and v8::internal::wasm::ValueTypeBase::raw_index().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast().
nullability()
constexpr Nullability v8::internal::wasm::HeapType::nullability () const [constexpr], [private]
operator==()
constexpr bool v8::internal::wasm::HeapType::operator== (HeapType other) const [inline], [constexpr]
Definition at line 773 of file value-type.h.
                                                  {
    constexpr uint32_t kMask = ~value_type_impl::IsRefField::kMask &
                               ~value_type_impl::IsNullableField::kMask;
    return (bit_field_ & kMask) == (other.bit_field_ & kMask);
  }
References v8::internal::wasm::ValueTypeBase::bit_field_.
ref_index()
constexpr ModuleTypeIndex v8::internal::wasm::HeapType::ref_index () const [inline], [constexpr]
Definition at line 769 of file value-type.h.
                                              {
    return ModuleTypeIndex{raw_index()};
  }
References v8::internal::wasm::ValueTypeBase::raw_index().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCast(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOnCast(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastFail(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOnCastFail(), code(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestor(), v8::internal::wasm::ModuleDecoderImpl::consume_base_type_definition(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::Handlers< Compressed >::DoRefCast(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetExactness(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::HeapType(), v8::internal::wasm::IsSubtypeOfImpl(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast(), v8::internal::wasm::value_type_reader::Populate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefTest(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefTest(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SubtypeCheck().
representation()
constexpr Representation v8::internal::wasm::HeapType::representation () const [inline], [constexpr]
Definition at line 844 of file value-type.h.
                                                  {
    return static_cast<Representation>(raw_heap_representation(true));
  }
References v8::internal::wasm::ValueTypeBase::raw_heap_representation().
Referenced by v8::internal::wasm::Handlers< Compressed >::DoRefCast(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckAlwaysFails(), and v8::internal::wasm::WasmBytecodeGenerator::TypeCheckAlwaysFails().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/value-type.h