v8::internal::compiler::JSArrayRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< JSArray > object () const
ObjectRef GetBoilerplateLength (JSHeapBroker *broker) const
OptionalObjectRef GetOwnCowElement (JSHeapBroker *broker, FixedArrayBaseRef elements_ref, uint32_t index) const
OptionalObjectRef length_unsafe (JSHeapBroker *broker) const
Detailed Description
Definition at line 1090 of file heap-refs.h.
Member Function Documentation
GetBoilerplateLength()
ObjectRef v8::internal::compiler::JSArrayRef::GetBoilerplateLength (JSHeapBroker * broker) const
Definition at line 2185 of file heap-refs.cc.
                                                                     {
  // Safe to read concurrently because:
  // - boilerplates are immutable after initialization.
  // - boilerplates are published into the feedback vector.
  // These facts also mean we can expect a valid value.
  return length_unsafe(broker).value();
}
References broker(), and length_unsafe().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral().
GetOwnCowElement()
OptionalObjectRef v8::internal::compiler::JSArrayRef::GetOwnCowElement (JSHeapBroker * broker, FixedArrayBaseRef elements_ref, uint32_t index) const
Definition at line 2197 of file heap-refs.cc.
                                                                     {
  // Note: we'd like to check `elements_ref == elements()` here, but due to
  // concurrency this may not hold. The code below must be able to deal with
  // concurrent `elements` modifications.
  // Due to concurrency, the kind read here may not be consistent with
  // `elements_ref`. The caller has to guarantee consistency at runtime by
  // other means (e.g. through a runtime equality check or a compilation
  // dependency).
  ElementsKind elements_kind = map(broker).elements_kind();
  // We only inspect fixed COW arrays, which may only occur for fast
  // smi/objects elements kinds.
  if (!IsSmiOrObjectElementsKind(elements_kind)) return {};
  DCHECK(IsFastElementsKind(elements_kind));
  if (!elements_ref.map(broker).IsFixedCowArrayMap(broker)) return {};
  // As the name says, the `length` read here is unsafe and may not match
  // `elements`. We rely on the invariant that any `length` change will
  // also result in an `elements` change to make this safe. The `elements`
  // consistency check in the caller thus also guards the value of `length`.
  OptionalObjectRef length_ref = length_unsafe(broker);
  if (!length_ref.has_value()) return {};
  // Likewise we only deal with smi lengths.
  if (!length_ref->IsSmi()) return {};
  std::optional<Tagged<Object>> result =
      ConcurrentLookupIterator::TryGetOwnCowElement(
          broker->isolate(), *elements_ref.AsFixedArray().object(),
          elements_kind, length_ref->AsSmi(), index);
  if (!result.has_value()) return {};
  return TryMakeRef(broker, result.value());
}
References broker(), v8::internal::DCHECK(), v8::internal::compiler::MapRef::elements_kind(), v8::internal::index, v8::internal::IsFastElementsKind(), v8::internal::compiler::MapRef::IsFixedCowArrayMap(), v8::internal::IsSmiOrObjectElementsKind(), length_unsafe(), v8::internal::compiler::HeapObjectRef::map(), v8::internal::compiler::FixedArrayBaseRef::object(), v8::base::internal::result, v8::internal::ConcurrentLookupIterator::TryGetOwnCowElement(), and v8::internal::compiler::TryMakeRef().
length_unsafe()
OptionalObjectRef v8::internal::compiler::JSArrayRef::length_unsafe (JSHeapBroker * broker) const
Definition at line 2193 of file heap-refs.cc.
                                                                      {
  return TryMakeRef(broker, object()->length(broker->isolate(), kRelaxedLoad));
}
References broker(), v8::kRelaxedLoad, v8::internal::length, and v8::internal::compiler::TryMakeRef().
Referenced by GetBoilerplateLength(), and GetOwnCowElement().
object()
IndirectHandle<JSArray> v8::internal::compiler::JSArrayRef::object () const
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc