v8::internal::KeyAccumulator Class Reference
#include <keys.h>
Public Member Functions
KeyAccumulator (Isolate *isolate, KeyCollectionMode mode, PropertyFilter filter)
~KeyAccumulator ()=default
KeyAccumulator (const KeyAccumulator &)=delete
KeyAccumulator & operator= (const KeyAccumulator &)=delete
Handle< FixedArray > GetKeys (GetKeysConversion convert=GetKeysConversion::kKeepNumbers)
Maybe< bool > CollectKeys (DirectHandle< JSReceiver > receiver, DirectHandle< JSReceiver > object)
V8_WARN_UNUSED_RESULT ExceptionStatus AddKey (Tagged< Object > key, AddKeyConversion convert=DO_NOT_CONVERT)
V8_WARN_UNUSED_RESULT ExceptionStatus AddKey (DirectHandle< Object > key, AddKeyConversion convert=DO_NOT_CONVERT)
Isolate * isolate ()
PropertyFilter filter ()
KeyCollectionMode mode ()
void set_skip_indices (bool value)
void AddShadowingKey (Tagged< Object > key, AllowGarbageCollection *allow_gc)
void AddShadowingKey (DirectHandle< Object > key)
Static Public Member Functions
static MaybeHandle< FixedArray > GetKeys (Isolate *isolate, DirectHandle< JSReceiver > object, KeyCollectionMode mode, PropertyFilter filter, GetKeysConversion keys_conversion=GetKeysConversion::kKeepNumbers, bool is_for_in=false, bool skip_indices=false)
static Handle< FixedArray > GetOwnEnumPropertyKeys (Isolate *isolate, DirectHandle< JSObject > object)
Private Types
enum IndexedOrNamed { kIndexed
, kNamed
 }
Private Member Functions
V8_WARN_UNUSED_RESULT ExceptionStatus CollectPrivateNames (DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object)
Maybe< bool > CollectAccessCheckInterceptorKeys (DirectHandle< AccessCheckInfo > access_check_info, DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object)
Maybe< bool > CollectInterceptorKeysInternal (DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object, DirectHandle< InterceptorInfo > interceptor, IndexedOrNamed type)
Maybe< bool > CollectInterceptorKeys (DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object, IndexedOrNamed type)
Maybe< bool > CollectOwnElementIndices (DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object)
Maybe< bool > CollectOwnPropertyNames (DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object)
Maybe< bool > CollectOwnKeys (DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object)
Maybe< bool > CollectOwnJSProxyKeys (DirectHandle< JSReceiver > receiver, DirectHandle< JSProxy > proxy)
Maybe< bool > CollectOwnJSProxyTargetKeys (DirectHandle< JSProxy > proxy, DirectHandle< JSReceiver > target)
V8_WARN_UNUSED_RESULT ExceptionStatus FilterForEnumerableProperties (DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object, DirectHandle< InterceptorInfo > interceptor, DirectHandle< JSObject > result, IndexedOrNamed type)
Maybe< bool > AddKeysFromJSProxy (DirectHandle< JSProxy > proxy, DirectHandle< FixedArray > keys)
V8_WARN_UNUSED_RESULT ExceptionStatus AddKeys (DirectHandle< FixedArray > array, AddKeyConversion convert)
V8_WARN_UNUSED_RESULT ExceptionStatus AddKeys (DirectHandle< JSObject > array_like, AddKeyConversion convert)
bool IsShadowed (DirectHandle< Object > key)
bool HasShadowingKeys ()
Handle< OrderedHashSet > keys ()
void set_is_for_in (bool value)
void set_first_prototype_map (DirectHandle< Map > value)
void set_try_prototype_info_cache (bool value)
void set_receiver (DirectHandle< JSReceiver > object)
void set_last_non_empty_prototype (DirectHandle< JSReceiver > object)
void set_may_have_elements (bool value)
Private Attributes
Isolate * isolate_
Handle< OrderedHashSet > keys_
DirectHandle< Map > first_prototype_map_
DirectHandle< JSReceiver > receiver_
DirectHandle< JSReceiver > last_non_empty_prototype_
Handle< ObjectHashSet > shadowing_keys_
KeyCollectionMode mode_
PropertyFilter filter_
bool is_for_in_ = false
bool skip_indices_ = false
bool skip_shadow_check_ = true
bool may_have_elements_ = true
bool try_prototype_info_cache_ = false
friend FastKeyAccumulator
Detailed Description
Definition at line 50 of file keys.h.
Member Enumeration Documentation
IndexedOrNamed
enum v8::internal::KeyAccumulator::IndexedOrNamed [private]
Enumerator
kIndexed
kNamed
Definition at line 97 of file keys.h.
{ kIndexed, kNamed };
Constructor & Destructor Documentation
KeyAccumulator() [1/2]
v8::internal::KeyAccumulator::KeyAccumulator (Isolate * isolate, KeyCollectionMode mode, PropertyFilter filter) [inline]
Definition at line 52 of file keys.h.
      : isolate_(isolate), mode_(mode), filter_(filter) {}
 KeyAccumulator()
v8::internal::KeyAccumulator::~KeyAccumulator () [default]
KeyAccumulator() [2/2]
v8::internal::KeyAccumulator::KeyAccumulator (const KeyAccumulator &) [delete]
Member Function Documentation
AddKey() [1/2]
ExceptionStatus v8::internal::KeyAccumulator::AddKey (DirectHandle< Object > key, AddKeyConversion convert = DO_NOT_CONVERT)
Definition at line 134 of file keys.cc.
                                                                 {
  if (filter_ == PRIVATE_NAMES_ONLY) {
    if (!IsSymbol(*key)) return ExceptionStatus::kSuccess;
    if (!Cast<Symbol>(*key)->is_private_name())
      return ExceptionStatus::kSuccess;
  } else if (IsSymbol(*key)) {
    if (filter_ & SKIP_SYMBOLS) return ExceptionStatus::kSuccess;
    if (Cast<Symbol>(*key)->is_private()) return ExceptionStatus::kSuccess;
  } else if (filter_ & SKIP_STRINGS) {
    return ExceptionStatus::kSuccess;
  }
  if (IsShadowed(key)) return ExceptionStatus::kSuccess;
  if (keys_.is_null()) {
    keys_ = OrderedHashSet::Allocate(isolate_, 16).ToHandleChecked();
  }
  uint32_t index;
  if (convert == CONVERT_TO_ARRAY_INDEX && IsString(*key) &&
      Cast<String>(key)->AsArrayIndex(&index)) {
    key = isolate_->factory()->NewNumberFromUint(index);
  }
  MaybeHandle<OrderedHashSet> new_set_candidate =
      OrderedHashSet::Add(isolate(), keys(), key);
  Handle<OrderedHashSet> new_set;
  if (!new_set_candidate.ToHandle(&new_set)) {
    // Replace generic RangeError exception with a more descriptive one.
    DCHECK(isolate_->has_exception());
    isolate_->clear_exception();
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate_, NewRangeError(MessageTemplate::kTooManyProperties),
        ExceptionStatus::kException);
  }
  if (*new_set != *keys_) {
    // The keys_ Set is converted directly to a FixedArray in GetKeys which can
    // be left-trimmer. Hence the previous Set should not keep a pointer to the
    // new one.
    keys_->set(OrderedHashSet::NextTableIndex(), Smi::zero());
    keys_ = new_set;
  }
  return ExceptionStatus::kSuccess;
}
References v8::bigint::Add(), v8::internal::OrderedHashSet::Allocate(), v8::internal::Isolate::clear_exception(), v8::internal::CONVERT_TO_ARRAY_INDEX, v8::internal::DCHECK(), v8::internal::Isolate::factory(), filter_, v8::internal::Isolate::has_exception(), v8::internal::index, isolate(), isolate_, IsShadowed(), v8::internal::kException, v8::internal::key, keys(), keys_, v8::internal::kSuccess, v8::internal::FactoryBase< Impl >::NewNumberFromUint(), v8::internal::OrderedHashTable< OrderedHashSet, 1 >::NextTableIndex(), v8::internal::PRIVATE_NAMES_ONLY, v8::internal::SKIP_STRINGS, v8::internal::SKIP_SYMBOLS, THROW_NEW_ERROR_RETURN_VALUE, v8::internal::MaybeHandle< T >::ToHandle(), and v8::internal::Smi::zero().
AddKey() [2/2]
ExceptionStatus v8::internal::KeyAccumulator::AddKey (Tagged< Object > key, AddKeyConversion convert = DO_NOT_CONVERT)
Definition at line 129 of file keys.cc.
                                                                 {
  return AddKey(direct_handle(key, isolate_), convert);
}
References v8::internal::direct_handle(), isolate_, and v8::internal::key.
Referenced by v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::AddElementsToKeyAccumulatorImpl(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::AddElementsToKeyAccumulatorImpl(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::AddElementsToKeyAccumulatorImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::AddElementsToKeyAccumulatorImpl(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::AddElementsToKeyAccumulatorImpl(), AddKeys(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{keys.cc}::CollectKeysFromDictionary(), v8::internal::anonymous_namespace{keys.cc}::CollectOwnPropertyNamesInternal(), and FilterForEnumerableProperties().
AddKeys() [1/2]
ExceptionStatus v8::internal::KeyAccumulator::AddKeys (DirectHandle< FixedArray > array, AddKeyConversion convert) [private]
Definition at line 177 of file keys.cc.
                                                                  {
  int add_length = array->length();
  for (int i = 0; i < add_length; i++) {
    DirectHandle<Object> current(array->get(i), isolate_);
    RETURN_FAILURE_IF_NOT_SUCCESSFUL(AddKey(current, convert));
  }
  return ExceptionStatus::kSuccess;
}
References AddKey(), isolate_, v8::internal::kSuccess, and RETURN_FAILURE_IF_NOT_SUCCESSFUL.
Referenced by AddKeysFromJSProxy(), CollectInterceptorKeysInternal(), and CollectOwnPropertyNames().
AddKeys() [2/2]
ExceptionStatus v8::internal::KeyAccumulator::AddKeys (DirectHandle< JSObject > array_like, AddKeyConversion convert) [private]
Definition at line 187 of file keys.cc.
                                                                  {
  DCHECK(IsJSArray(*array_like) || array_like->HasSloppyArgumentsElements());
  ElementsAccessor* accessor = array_like->GetElementsAccessor();
  return accessor->AddElementsToKeyAccumulator(array_like, this, convert);
}
References v8::internal::ElementsAccessor::AddElementsToKeyAccumulator(), and v8::internal::DCHECK().
AddKeysFromJSProxy()
Maybe< bool > v8::internal::KeyAccumulator::AddKeysFromJSProxy (DirectHandle< JSProxy > proxy, DirectHandle< FixedArray > keys) [private]
Definition at line 233 of file keys.cc.
                                                                              {
  // Postpone the enumerable check for for-in to the ForInFilter step.
  if (!is_for_in_) {
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate_, keys,
        FilterProxyKeys(this, proxy, keys, filter_, skip_indices_),
        Nothing<bool>());
  }
  // https://tc39.es/ecma262/#sec-proxy-object-internal-methods-and-internal-slots-ownpropertykeys
  // As of 10.5.11.9 says, the keys collected from Proxy should not contain
  // any duplicates. And the order of the keys is preserved by the
  // OrderedHashTable.
  RETURN_NOTHING_IF_NOT_SUCCESSFUL(AddKeys(keys, CONVERT_TO_ARRAY_INDEX));
  return Just(true);
}
References AddKeys(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::CONVERT_TO_ARRAY_INDEX, filter_, v8::internal::FilterProxyKeys(), is_for_in_, isolate_, v8::Just(), keys(), RETURN_NOTHING_IF_NOT_SUCCESSFUL, and skip_indices_.
Referenced by CollectOwnJSProxyKeys(), and CollectOwnJSProxyTargetKeys().
AddShadowingKey() [1/2]
void v8::internal::KeyAccumulator::AddShadowingKey (DirectHandle< Object > key)
Definition at line 314 of file keys.cc.
                                                             {
  if (mode_ == KeyCollectionMode::kOwnOnly) return;
  if (shadowing_keys_.is_null()) {
    shadowing_keys_ = ObjectHashSet::New(isolate_, 16);
  }
  shadowing_keys_ = ObjectHashSet::Add(isolate(), shadowing_keys_, key);
}
References v8::internal::ObjectHashSet::Add(), isolate(), isolate_, v8::internal::key, v8::internal::kOwnOnly, mode_, v8::internal::anonymous_namespace{intl-objects.cc}::New(), and shadowing_keys_.
AddShadowingKey() [2/2]
void v8::internal::KeyAccumulator::AddShadowingKey (Tagged< Object > key, AllowGarbageCollection * allow_gc)
Definition at line 308 of file keys.cc.
                                                                       {
  if (mode_ == KeyCollectionMode::kOwnOnly) return;
  AddShadowingKey(direct_handle(key, isolate_));
}
References v8::internal::direct_handle(), isolate_, v8::internal::key, v8::internal::kOwnOnly, and mode_.
Referenced by v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{keys.cc}::CollectKeysFromDictionary(), CollectOwnPropertyNames(), v8::internal::anonymous_namespace{keys.cc}::CollectOwnPropertyNamesInternal(), v8::internal::anonymous_namespace{keys.cc}::CommonCopyEnumKeysTo(), and v8::internal::FilterProxyKeys().
CollectAccessCheckInterceptorKeys()
Maybe< bool > v8::internal::KeyAccumulator::CollectAccessCheckInterceptorKeys (DirectHandle< AccessCheckInfo > access_check_info, DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object) [private]
Definition at line 1113 of file keys.cc.
                                                                      {
  if (!skip_indices_) {
    MAYBE_RETURN(
        (CollectInterceptorKeysInternal(
            receiver, object,
            direct_handle(
                Cast<InterceptorInfo>(access_check_info->indexed_interceptor()),
                isolate_),
            kIndexed)),
        Nothing<bool>());
  }
  MAYBE_RETURN((CollectInterceptorKeysInternal(
                   receiver, object,
                   direct_handle(Cast<InterceptorInfo>(
                                     access_check_info->named_interceptor()),
                                 isolate_),
                   kNamed)),
               Nothing<bool>());
  return Just(true);
}
References CollectInterceptorKeysInternal(), v8::internal::direct_handle(), isolate_, v8::Just(), kIndexed, kNamed, MAYBE_RETURN, and skip_indices_.
Referenced by CollectOwnKeys().
CollectInterceptorKeys()
Maybe< bool > v8::internal::KeyAccumulator::CollectInterceptorKeys (DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object, IndexedOrNamed type) [private]
Definition at line 773 of file keys.cc.
                         {
  if (type == kIndexed) {
    if (!object->HasIndexedInterceptor()) return Just(true);
  } else {
    if (!object->HasNamedInterceptor()) return Just(true);
  }
  DirectHandle<InterceptorInfo> interceptor(
      type == kIndexed ? object->GetIndexedInterceptor()
                       : object->GetNamedInterceptor(),
      isolate_);
  return CollectInterceptorKeysInternal(receiver, object, interceptor, type);
}
References CollectInterceptorKeysInternal(), isolate_, v8::Just(), kIndexed, and v8::internal::tracing::type.
Referenced by CollectOwnElementIndices(), and CollectOwnPropertyNames().
CollectInterceptorKeysInternal()
Maybe< bool > v8::internal::KeyAccumulator::CollectInterceptorKeysInternal (DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object, DirectHandle< InterceptorInfo > interceptor, IndexedOrNamed type) [private]
Definition at line 736 of file keys.cc.
                                                                    {
  PropertyCallbackArguments enum_args(isolate_, interceptor->data(), *receiver,
                                      *object, Just(kDontThrow));
  DCHECK_EQ(interceptor->is_named(), type == kNamed);
  if (!interceptor->has_enumerator()) {
    return Just(true);
  }
  DirectHandle<JSObjectOrUndefined> maybe_result;
  if (type == kIndexed) {
    maybe_result = enum_args.CallIndexedEnumerator(interceptor);
  } else {
    DCHECK_EQ(type, kNamed);
    maybe_result = enum_args.CallNamedEnumerator(interceptor);
  }
  // An exception was thrown in the interceptor. Propagate.
  RETURN_VALUE_IF_EXCEPTION_DETECTOR(isolate_, enum_args, Nothing<bool>());
  if (IsUndefined(*maybe_result)) return Just(true);
  DCHECK(IsJSObject(*maybe_result));
  DirectHandle<JSObject> result = Cast<JSObject>(maybe_result);
  // Request was successfully intercepted, so accept potential side effects
  // happened up to this point.
  enum_args.AcceptSideEffects();
  if ((filter_ & ONLY_ENUMERABLE) && interceptor->has_query()) {
    RETURN_NOTHING_IF_NOT_SUCCESSFUL(FilterForEnumerableProperties(
        receiver, object, interceptor, result, type));
  } else {
    RETURN_NOTHING_IF_NOT_SUCCESSFUL(AddKeys(
        result, type == kIndexed ? CONVERT_TO_ARRAY_INDEX : DO_NOT_CONVERT));
  }
  return Just(true);
}
References v8::internal::PropertyCallbackArguments::AcceptSideEffects(), AddKeys(), v8::internal::PropertyCallbackArguments::CallIndexedEnumerator(), v8::internal::PropertyCallbackArguments::CallNamedEnumerator(), v8::internal::CONVERT_TO_ARRAY_INDEX, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::DO_NOT_CONVERT, filter_, FilterForEnumerableProperties(), isolate_, v8::Just(), v8::internal::kDontThrow, kIndexed, kNamed, v8::internal::ONLY_ENUMERABLE, v8::base::internal::result, RETURN_NOTHING_IF_NOT_SUCCESSFUL, RETURN_VALUE_IF_EXCEPTION_DETECTOR, and v8::internal::tracing::type.
Referenced by CollectAccessCheckInterceptorKeys(), and CollectInterceptorKeys().
CollectKeys()
Maybe< bool > v8::internal::KeyAccumulator::CollectKeys (DirectHandle< JSReceiver > receiver, DirectHandle< JSReceiver > object)
Definition at line 250 of file keys.cc.
                                                                         {
  // Proxies have no hidden prototype and we should not trigger the
  // [[GetPrototypeOf]] trap on the last iteration when using
  // AdvanceFollowingProxies.
  if (mode_ == KeyCollectionMode::kOwnOnly && IsJSProxy(*object)) {
    MAYBE_RETURN(CollectOwnJSProxyKeys(receiver, Cast<JSProxy>(object)),
                 Nothing<bool>());
    return Just(true);
  }
  PrototypeIterator::WhereToEnd end = mode_ == KeyCollectionMode::kOwnOnly
                                          ? PrototypeIterator::END_AT_NON_HIDDEN
                                          : PrototypeIterator::END_AT_NULL;
  for (PrototypeIterator iter(isolate_, object, kStartAtReceiver, end);
       !iter.IsAtEnd();) {
    // Start the shadow checks only after the first prototype has added
    // shadowing keys.
    if (HasShadowingKeys()) skip_shadow_check_ = false;
    DirectHandle<JSReceiver> current =
        PrototypeIterator::GetCurrent<JSReceiver>(iter);
    Maybe<bool> result = Just(false); // Dummy initialization.
    if (IsJSProxy(*current)) {
      result = CollectOwnJSProxyKeys(receiver, Cast<JSProxy>(current));
    } else if (IsWasmObject(*current)) {
      if (mode_ == KeyCollectionMode::kIncludePrototypes) {
        RETURN_FAILURE(isolate_, kThrowOnError,
                       NewTypeError(MessageTemplate::kWasmObjectsAreOpaque));
      } else {
        DCHECK_EQ(KeyCollectionMode::kOwnOnly, mode_);
        DCHECK_EQ(result, Just(false)); // Stop iterating.
      }
    } else {
      DCHECK(IsJSObject(*current));
      result = CollectOwnKeys(receiver, Cast<JSObject>(current));
    }
    MAYBE_RETURN(result, Nothing<bool>());
    if (!result.FromJust()) break; // |false| means "stop iterating".
    // Iterate through proxies but ignore access checks case on API objects for
    // OWN_ONLY keys handled in CollectOwnKeys.
    if (!iter.AdvanceFollowingProxiesIgnoringAccessChecks()) {
      return Nothing<bool>();
    }
    if (!last_non_empty_prototype_.is_null() &&
        *last_non_empty_prototype_ == *current) {
      break;
    }
  }
  return Just(true);
}
References CollectOwnJSProxyKeys(), CollectOwnKeys(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::end(), v8::internal::PrototypeIterator::END_AT_NON_HIDDEN, v8::internal::PrototypeIterator::END_AT_NULL, HasShadowingKeys(), v8::internal::PrototypeIterator::IsAtEnd(), isolate_, v8::internal::IsWasmObject(), v8::Just(), v8::internal::kIncludePrototypes, v8::internal::kOwnOnly, v8::internal::kStartAtReceiver, v8::internal::kThrowOnError, last_non_empty_prototype_, MAYBE_RETURN, mode_, v8::base::internal::result, RETURN_FAILURE, and skip_shadow_check_.
Referenced by v8::internal::FastKeyAccumulator::GetKeysSlow(), v8::internal::FastKeyAccumulator::GetKeysWithPrototypeInfoCache(), and v8::Object::GetPropertyNames().
CollectOwnElementIndices()
Maybe< bool > v8::internal::KeyAccumulator::CollectOwnElementIndices (DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object) [private]
Definition at line 788 of file keys.cc.
                                                                      {
  if (filter_ & SKIP_STRINGS || skip_indices_) return Just(true);
  ElementsAccessor* accessor = object->GetElementsAccessor();
  RETURN_NOTHING_IF_NOT_SUCCESSFUL(
      accessor->CollectElementIndices(object, this));
  return CollectInterceptorKeys(receiver, object, kIndexed);
}
References v8::internal::ElementsAccessor::CollectElementIndices(), CollectInterceptorKeys(), filter_, v8::Just(), kIndexed, RETURN_NOTHING_IF_NOT_SUCCESSFUL, skip_indices_, and v8::internal::SKIP_STRINGS.
Referenced by CollectOwnKeys().
CollectOwnJSProxyKeys()
Maybe< bool > v8::internal::KeyAccumulator::CollectOwnJSProxyKeys (DirectHandle< JSReceiver > receiver, DirectHandle< JSProxy > proxy) [private]
Definition at line 1220 of file keys.cc.
                                                                    {
  STACK_CHECK(isolate_, Nothing<bool>());
  if (filter_ == PRIVATE_NAMES_ONLY) {
    if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      RETURN_NOTHING_IF_NOT_SUCCESSFUL(CollectKeysFromDictionary(
          direct_handle(proxy->property_dictionary_swiss(), isolate_), this));
    } else {
      RETURN_NOTHING_IF_NOT_SUCCESSFUL(CollectKeysFromDictionary(
          direct_handle(proxy->property_dictionary(), isolate_), this));
    }
    return Just(true);
  }
  // 1. Let handler be the value of the [[ProxyHandler]] internal slot of O.
  DirectHandle<Object> handler(proxy->handler(), isolate_);
  // 2. If handler is null, throw a TypeError exception.
  // 3. Assert: Type(handler) is Object.
  if (proxy->IsRevoked()) {
    isolate_->Throw(*isolate_->factory()->NewTypeError(
        MessageTemplate::kProxyRevoked, isolate_->factory()->ownKeys_string()));
    return Nothing<bool>();
  }
  // 4. Let target be the value of the [[ProxyTarget]] internal slot of O.
  DirectHandle<JSReceiver> target(Cast<JSReceiver>(proxy->target()), isolate_);
  // 5. Let trap be ? GetMethod(handler, "ownKeys").
  DirectHandle<Object> trap;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate_, trap,
      Object::GetMethod(isolate_, Cast<JSReceiver>(handler),
                        isolate_->factory()->ownKeys_string()),
      Nothing<bool>());
  // 6. If trap is undefined, then
  if (IsUndefined(*trap, isolate_)) {
    // 6a. Return target.[[OwnPropertyKeys]]().
    return CollectOwnJSProxyTargetKeys(proxy, target);
  }
  // 7. Let trapResultArray be Call(trap, handler, target).
  DirectHandle<Object> trap_result_array;
  DirectHandle<Object> args[] = {target};
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate_, trap_result_array,
      Execution::Call(isolate_, trap, handler, base::VectorOf(args)),
      Nothing<bool>());
  // 8. Let trapResult be ? CreateListFromArrayLike(trapResultArray,
  // String, Symbol).
  DirectHandle<FixedArray> trap_result;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate_, trap_result,
      Object::CreateListFromArrayLike(isolate_, trap_result_array,
                                      ElementTypes::kStringAndSymbol),
      Nothing<bool>());
  // 9. If trapResult contains any duplicate entries, throw a TypeError
  // exception. Combine with step 18
  // 18. Let uncheckedResultKeys be a new List which is a copy of trapResult.
  Zone set_zone(isolate_->allocator(), ZONE_NAME);
  const int kPresent = 1;
  const int kGone = 0;
  using ZoneHashMapImpl =
      base::TemplateHashMapImpl<Handle<Name>, int, NameComparator,
                                ZoneAllocationPolicy>;
  ZoneHashMapImpl unchecked_result_keys(
      ZoneHashMapImpl::kDefaultHashMapCapacity, NameComparator(isolate_),
      ZoneAllocationPolicy(&set_zone));
  int unchecked_result_keys_size = 0;
  for (int i = 0; i < trap_result->length(); ++i) {
    Handle<Name> key(Cast<Name>(trap_result->get(i)), isolate_);
    auto entry = unchecked_result_keys.LookupOrInsert(key, key->EnsureHash());
    if (entry->value != kPresent) {
      entry->value = kPresent;
      unchecked_result_keys_size++;
    } else {
      // found dupes, throw exception
      isolate_->Throw(*isolate_->factory()->NewTypeError(
          MessageTemplate::kProxyOwnKeysDuplicateEntries));
      return Nothing<bool>();
    }
  }
  // 10. Let extensibleTarget be ? IsExtensible(target).
  Maybe<bool> maybe_extensible = JSReceiver::IsExtensible(isolate_, target);
  MAYBE_RETURN(maybe_extensible, Nothing<bool>());
  bool extensible_target = maybe_extensible.FromJust();
  // 11. Let targetKeys be ? target.[[OwnPropertyKeys]]().
  DirectHandle<FixedArray> target_keys;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate_, target_keys, JSReceiver::OwnPropertyKeys(isolate_, target),
      Nothing<bool>());
  // 12, 13. (Assert)
  // 14. Let targetConfigurableKeys be an empty List.
  // To save memory, we're reusing target_keys and will modify it in-place.
  DirectHandle<FixedArray> target_configurable_keys = target_keys;
  // 15. Let targetNonconfigurableKeys be an empty List.
  DirectHandle<FixedArray> target_nonconfigurable_keys =
      isolate_->factory()->NewFixedArray(target_keys->length());
  int nonconfigurable_keys_length = 0;
  // 16. Repeat, for each element key of targetKeys:
  for (int i = 0; i < target_keys->length(); ++i) {
    // 16a. Let desc be ? target.[[GetOwnProperty]](key).
    PropertyDescriptor desc;
    Maybe<bool> found = JSReceiver::GetOwnPropertyDescriptor(
        isolate_, target, direct_handle(target_keys->get(i), isolate_), &desc);
    MAYBE_RETURN(found, Nothing<bool>());
    // 16b. If desc is not undefined and desc.[[Configurable]] is false, then
    if (found.FromJust() && !desc.configurable()) {
      // 16b i. Append key as an element of targetNonconfigurableKeys.
      target_nonconfigurable_keys->set(nonconfigurable_keys_length,
                                       target_keys->get(i));
      nonconfigurable_keys_length++;
      // The key was moved, null it out in the original list.
      target_keys->set(i, Smi::zero());
    } else {
      // 16c. Else,
      // 16c i. Append key as an element of targetConfigurableKeys.
      // (No-op, just keep it in |target_keys|.)
    }
  }
  // 17. If extensibleTarget is true and targetNonconfigurableKeys is empty,
  // then:
  if (extensible_target && nonconfigurable_keys_length == 0) {
    // 17a. Return trapResult.
    return AddKeysFromJSProxy(proxy, trap_result);
  }
  // 18. (Done in step 9)
  // 19. Repeat, for each key that is an element of targetNonconfigurableKeys:
  for (int i = 0; i < nonconfigurable_keys_length; ++i) {
    Tagged<Object> raw_key = target_nonconfigurable_keys->get(i);
    Handle<Name> key(Cast<Name>(raw_key), isolate_);
    // 19a. If key is not an element of uncheckedResultKeys, throw a
    // TypeError exception.
    auto found = unchecked_result_keys.Lookup(key, key->hash());
    if (found == nullptr || found->value == kGone) {
      isolate_->Throw(*isolate_->factory()->NewTypeError(
          MessageTemplate::kProxyOwnKeysMissing, key));
      return Nothing<bool>();
    }
    // 19b. Remove key from uncheckedResultKeys.
    found->value = kGone;
    unchecked_result_keys_size--;
  }
  // 20. If extensibleTarget is true, return trapResult.
  if (extensible_target) {
    return AddKeysFromJSProxy(proxy, trap_result);
  }
  // 21. Repeat, for each key that is an element of targetConfigurableKeys:
  for (int i = 0; i < target_configurable_keys->length(); ++i) {
    Tagged<Object> raw_key = target_configurable_keys->get(i);
    if (IsSmi(raw_key)) continue; // Zapped entry, was nonconfigurable.
    Handle<Name> key(Cast<Name>(raw_key), isolate_);
    // 21a. If key is not an element of uncheckedResultKeys, throw a
    // TypeError exception.
    auto found = unchecked_result_keys.Lookup(key, key->hash());
    if (found == nullptr || found->value == kGone) {
      isolate_->Throw(*isolate_->factory()->NewTypeError(
          MessageTemplate::kProxyOwnKeysMissing, key));
      return Nothing<bool>();
    }
    // 21b. Remove key from uncheckedResultKeys.
    found->value = kGone;
    unchecked_result_keys_size--;
  }
  // 22. If uncheckedResultKeys is not empty, throw a TypeError exception.
  if (unchecked_result_keys_size != 0) {
    DCHECK_GT(unchecked_result_keys_size, 0);
    isolate_->Throw(*isolate_->factory()->NewTypeError(
        MessageTemplate::kProxyOwnKeysNonExtensible));
    return Nothing<bool>();
  }
  // 23. Return trapResult.
  return AddKeysFromJSProxy(proxy, trap_result);
}
References AddKeysFromJSProxy(), v8::internal::Isolate::allocator(), v8::base::args, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Execution::Call(), v8::internal::anonymous_namespace{keys.cc}::CollectKeysFromDictionary(), CollectOwnJSProxyTargetKeys(), v8::internal::PropertyDescriptor::configurable(), v8::internal::Object::CreateListFromArrayLike(), DCHECK_GT, v8::internal::direct_handle(), v8::internal::Isolate::factory(), filter_, v8::Maybe< T >::FromJust(), v8::internal::Object::GetMethod(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::JSReceiver::IsExtensible(), isolate_, v8::internal::IsSmi(), v8::Just(), v8::internal::key, v8::internal::kStringAndSymbol, MAYBE_RETURN, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::JSReceiver::OwnPropertyKeys(), v8::internal::PRIVATE_NAMES_ONLY, RETURN_NOTHING_IF_NOT_SUCCESSFUL, STACK_CHECK, v8::internal::Isolate::Throw(), V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, v8::base::VectorOf(), v8::internal::Smi::zero(), and ZONE_NAME.
Referenced by CollectKeys().
CollectOwnJSProxyTargetKeys()
Maybe< bool > v8::internal::KeyAccumulator::CollectOwnJSProxyTargetKeys (DirectHandle< JSProxy > proxy, DirectHandle< JSReceiver > target) [private]
Definition at line 1392 of file keys.cc.
                                                                  {
  // TODO(cbruni): avoid creating another KeyAccumulator
  DirectHandle<FixedArray> keys;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate_, keys,
      KeyAccumulator::GetKeys(
          isolate_, target, KeyCollectionMode::kOwnOnly, ALL_PROPERTIES,
          GetKeysConversion::kConvertToString, is_for_in_, skip_indices_),
      Nothing<bool>());
  Maybe<bool> result = AddKeysFromJSProxy(proxy, keys);
  return result;
}
References AddKeysFromJSProxy(), v8::internal::ALL_PROPERTIES, ASSIGN_RETURN_ON_EXCEPTION_VALUE, GetKeys(), is_for_in_, isolate_, v8::internal::kConvertToString, keys(), v8::internal::kOwnOnly, v8::base::internal::result, and skip_indices_.
Referenced by CollectOwnJSProxyKeys().
CollectOwnKeys()
Maybe< bool > v8::internal::KeyAccumulator::CollectOwnKeys (DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object) [private]
Definition at line 1138 of file keys.cc.
                                                                          {
  // Check access rights if required.
  if (IsAccessCheckNeeded(*object) &&
      !isolate_->MayAccess(isolate_->native_context(), object)) {
    // The cross-origin spec says that [[Enumerate]] shall return an empty
    // iterator when it doesn't have access...
    if (mode_ == KeyCollectionMode::kIncludePrototypes) {
      return Just(false);
    }
    // ...whereas [[OwnPropertyKeys]] shall return allowlisted properties.
    DCHECK_EQ(KeyCollectionMode::kOwnOnly, mode_);
    DirectHandle<AccessCheckInfo> access_check_info;
    {
      DisallowGarbageCollection no_gc;
      Tagged<AccessCheckInfo> maybe_info =
          AccessCheckInfo::Get(isolate_, object);
      if (!maybe_info.is_null()) {
        access_check_info = direct_handle(maybe_info, isolate_);
      }
    }
    // We always have both kinds of interceptors or none.
    if (!access_check_info.is_null() &&
        access_check_info->named_interceptor() != Tagged<Object>()) {
      MAYBE_RETURN(CollectAccessCheckInterceptorKeys(access_check_info,
                                                     receiver, object),
                   Nothing<bool>());
    }
    return Just(false);
  }
  if (filter_ & PRIVATE_NAMES_ONLY) {
    RETURN_NOTHING_IF_NOT_SUCCESSFUL(CollectPrivateNames(receiver, object));
    return Just(true);
  }
  if (may_have_elements_) {
    MAYBE_RETURN(CollectOwnElementIndices(receiver, object), Nothing<bool>());
  }
  MAYBE_RETURN(CollectOwnPropertyNames(receiver, object), Nothing<bool>());
  return Just(true);
}
References CollectAccessCheckInterceptorKeys(), CollectOwnElementIndices(), CollectOwnPropertyNames(), CollectPrivateNames(), DCHECK_EQ, v8::internal::direct_handle(), filter_, v8::internal::AccessCheckInfo::Get(), v8::internal::DirectHandle< T >::is_null(), v8::internal::Tagged< HeapObject >::is_null(), isolate_, v8::Just(), v8::internal::kIncludePrototypes, v8::internal::kOwnOnly, may_have_elements_, v8::internal::Isolate::MayAccess(), MAYBE_RETURN, mode_, v8::internal::Isolate::native_context(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PRIVATE_NAMES_ONLY, and RETURN_NOTHING_IF_NOT_SUCCESSFUL.
Referenced by CollectKeys().
CollectOwnPropertyNames()
Maybe< bool > v8::internal::KeyAccumulator::CollectOwnPropertyNames (DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object) [private]
Definition at line 1011 of file keys.cc.
                                                                      {
  if (filter_ == ENUMERABLE_STRINGS) {
    DirectHandle<FixedArray> enum_keys;
    if (object->HasFastProperties()) {
      enum_keys = KeyAccumulator::GetOwnEnumPropertyKeys(isolate_, object);
      // If the number of properties equals the length of enumerable properties
      // we do not have to filter out non-enumerable ones
      Tagged<Map> map = object->map();
      int nof_descriptors = map->NumberOfOwnDescriptors();
      if (enum_keys->length() != nof_descriptors) {
        if (map->prototype(isolate_) != ReadOnlyRoots(isolate_).null_value()) {
          AllowGarbageCollection allow_gc;
          DirectHandle<DescriptorArray> descs(
              map->instance_descriptors(isolate_), isolate_);
          for (InternalIndex i : InternalIndex::Range(nof_descriptors)) {
            PropertyDetails details = descs->GetDetails(i);
            if (!details.IsDontEnum()) continue;
            this->AddShadowingKey(descs->GetKey(i), &allow_gc);
          }
        }
      }
    } else if (IsJSGlobalObject(*object)) {
      enum_keys = GetOwnEnumPropertyDictionaryKeys(
          isolate_, mode_, this, object,
          Cast<JSGlobalObject>(*object)->global_dictionary(kAcquireLoad));
    } else if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      enum_keys = GetOwnEnumPropertyDictionaryKeys(
          isolate_, mode_, this, object, object->property_dictionary_swiss());
    } else {
      enum_keys = GetOwnEnumPropertyDictionaryKeys(
          isolate_, mode_, this, object, object->property_dictionary());
    }
    if (IsJSModuleNamespace(*object)) {
      // Simulate [[GetOwnProperty]] for establishing enumerability, which
      // throws for uninitialized exports.
      for (int i = 0, n = enum_keys->length(); i < n; ++i) {
        DirectHandle<String> key(Cast<String>(enum_keys->get(i)), isolate_);
        if (Cast<JSModuleNamespace>(object)
                ->GetExport(isolate(), key)
                .is_null()) {
          return Nothing<bool>();
        }
      }
    }
    RETURN_NOTHING_IF_NOT_SUCCESSFUL(AddKeys(enum_keys, DO_NOT_CONVERT));
  } else {
    if (object->HasFastProperties()) {
      int limit = object->map()->NumberOfOwnDescriptors();
      DirectHandle<DescriptorArray> descs(
          object->map()->instance_descriptors(isolate_), isolate_);
      // First collect the strings,
      std::optional<int> first_symbol =
          CollectOwnPropertyNamesInternal<true>(object, this, descs, 0, limit);
      // then the symbols.
      RETURN_NOTHING_IF_NOT_SUCCESSFUL(first_symbol);
      if (first_symbol.value() != -1) {
        RETURN_NOTHING_IF_NOT_SUCCESSFUL(CollectOwnPropertyNamesInternal<false>(
            object, this, descs, first_symbol.value(), limit));
      }
    } else if (IsJSGlobalObject(*object)) {
      RETURN_NOTHING_IF_NOT_SUCCESSFUL(CollectKeysFromDictionary(
          direct_handle(
              Cast<JSGlobalObject>(*object)->global_dictionary(kAcquireLoad),
              isolate_),
          this));
    } else if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      RETURN_NOTHING_IF_NOT_SUCCESSFUL(CollectKeysFromDictionary(
          direct_handle(object->property_dictionary_swiss(), isolate_), this));
    } else {
      RETURN_NOTHING_IF_NOT_SUCCESSFUL(CollectKeysFromDictionary(
          direct_handle(object->property_dictionary(), isolate_), this));
    }
  }
  // Add the property keys from the interceptor.
  return CollectInterceptorKeys(receiver, object, kNamed);
}
References AddKeys(), AddShadowingKey(), CollectInterceptorKeys(), v8::internal::anonymous_namespace{keys.cc}::CollectKeysFromDictionary(), v8::internal::direct_handle(), v8::internal::DO_NOT_CONVERT, v8::internal::ENUMERABLE_STRINGS, filter_, v8::internal::anonymous_namespace{keys.cc}::GetOwnEnumPropertyDictionaryKeys(), GetOwnEnumPropertyKeys(), v8::internal::PropertyDetails::IsDontEnum(), isolate(), isolate_, v8::kAcquireLoad, v8::internal::key, kNamed, mode_, RETURN_NOTHING_IF_NOT_SUCCESSFUL, and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by CollectOwnKeys().
CollectPrivateNames()
ExceptionStatus v8::internal::KeyAccumulator::CollectPrivateNames (DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object) [private]
Definition at line 1089 of file keys.cc.
                                                                      {
  DCHECK_EQ(mode_, KeyCollectionMode::kOwnOnly);
  if (object->HasFastProperties()) {
    int limit = object->map()->NumberOfOwnDescriptors();
    DirectHandle<DescriptorArray> descs(
        object->map()->instance_descriptors(isolate_), isolate_);
    CollectOwnPropertyNamesInternal<false>(object, this, descs, 0, limit);
  } else if (IsJSGlobalObject(*object)) {
    RETURN_FAILURE_IF_NOT_SUCCESSFUL(CollectKeysFromDictionary(
        direct_handle(
            Cast<JSGlobalObject>(*object)->global_dictionary(kAcquireLoad),
            isolate_),
        this));
  } else if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    RETURN_FAILURE_IF_NOT_SUCCESSFUL(CollectKeysFromDictionary(
        direct_handle(object->property_dictionary_swiss(), isolate_), this));
  } else {
    RETURN_FAILURE_IF_NOT_SUCCESSFUL(CollectKeysFromDictionary(
        direct_handle(object->property_dictionary(), isolate_), this));
  }
  return ExceptionStatus::kSuccess;
}
References v8::internal::anonymous_namespace{keys.cc}::CollectKeysFromDictionary(), DCHECK_EQ, v8::internal::direct_handle(), isolate_, v8::kAcquireLoad, v8::internal::kOwnOnly, v8::internal::kSuccess, mode_, RETURN_FAILURE_IF_NOT_SUCCESSFUL, and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by CollectOwnKeys().
filter()
PropertyFilter v8::internal::KeyAccumulator::filter () [inline]
Definition at line 86 of file keys.h.
{ return filter_; }
References filter_.
Referenced by v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{keys.cc}::CollectKeysFromDictionary(), v8::internal::anonymous_namespace{keys.cc}::CollectOwnPropertyNamesInternal(), and GetKeys().
FilterForEnumerableProperties()
V8_WARN_UNUSED_RESULT ExceptionStatus v8::internal::KeyAccumulator::FilterForEnumerableProperties (DirectHandle< JSReceiver > receiver, DirectHandle< JSObject > object, DirectHandle< InterceptorInfo > interceptor, DirectHandle< JSObject > result, IndexedOrNamed type) [private]
Definition at line 696 of file keys.cc.
                         {
  DCHECK(IsJSArray(*result) || result->HasSloppyArgumentsElements());
  ElementsAccessor* accessor = result->GetElementsAccessor();
  size_t length = accessor->GetCapacity(*result, result->elements());
  for (InternalIndex entry : InternalIndex::Range(length)) {
    if (!accessor->HasEntry(isolate(), *result, entry)) continue;
    // args are invalid after args.Call(), create a new one in every iteration.
    // Query callbacks are not expected to have side effects.
    PropertyCallbackArguments args(isolate_, interceptor->data(), *receiver,
                                   *object, Just(kDontThrow));
    DirectHandle<Object> element = accessor->Get(isolate_, result, entry);
    DirectHandle<Object> attributes;
    if (type == kIndexed) {
      uint32_t number;
      CHECK(Object::ToUint32(*element, &number));
      attributes = args.CallIndexedQuery(interceptor, number);
    } else {
      CHECK(IsName(*element));
      attributes = args.CallNamedQuery(interceptor, Cast<Name>(element));
    }
    // An exception was thrown in the interceptor. Propagate.
    RETURN_VALUE_IF_EXCEPTION(isolate_, ExceptionStatus::kException);
    if (!attributes.is_null()) {
      int32_t value;
      CHECK(Object::ToInt32(*attributes, &value));
      if ((value & DONT_ENUM) == 0) {
        RETURN_FAILURE_IF_NOT_SUCCESSFUL(AddKey(element, DO_NOT_CONVERT));
      }
    }
  }
  return ExceptionStatus::kSuccess;
}
References AddKey(), v8::base::args, CHECK, v8::internal::DCHECK(), v8::internal::DO_NOT_CONVERT, v8::internal::DONT_ENUM, v8::internal::ElementsAccessor::Get(), v8::internal::ElementsAccessor::GetCapacity(), v8::internal::ElementsAccessor::HasEntry(), v8::internal::DirectHandle< T >::is_null(), isolate(), isolate_, v8::Just(), v8::internal::kDontThrow, v8::internal::kException, kIndexed, v8::internal::kSuccess, v8::internal::length, v8::base::internal::result, RETURN_FAILURE_IF_NOT_SUCCESSFUL, RETURN_VALUE_IF_EXCEPTION, v8::internal::Object::ToInt32(), v8::internal::Object::ToUint32(), v8::internal::tracing::type, and v8::internal::value.
Referenced by CollectInterceptorKeysInternal().
GetKeys() [1/2]
Handle< FixedArray > v8::internal::KeyAccumulator::GetKeys (GetKeysConversion convert = GetKeysConversion::kKeepNumbers)
Definition at line 106 of file keys.cc.
                                                                    {
  if (keys_.is_null()) {
    return isolate_->factory()->empty_fixed_array();
  }
  USE(ContainsOnlyValidKeys);
  Handle<FixedArray> result =
      OrderedHashSet::ConvertToKeysArray(isolate(), keys(), convert);
  DCHECK(ContainsOnlyValidKeys(result));
  if (try_prototype_info_cache_ && !first_prototype_map_.is_null()) {
    DirectHandle<PrototypeInfo> prototype_info;
    Map::GetOrCreatePrototypeChainValidityCell(first_prototype_map_, isolate_,
                                               &prototype_info);
    prototype_info->set_prototype_chain_enum_cache(*result);
    DCHECK(first_prototype_map_->IsPrototypeValidityCellValid());
  }
  return result;
}
References v8::internal::anonymous_namespace{keys.cc}::ContainsOnlyValidKeys(), v8::internal::OrderedHashSet::ConvertToKeysArray(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), first_prototype_map_, v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), isolate(), isolate_, keys(), keys_, v8::base::internal::result, try_prototype_info_cache_, and USE.
GetKeys() [2/2]
MaybeHandle< FixedArray > v8::internal::KeyAccumulator::GetKeys (Isolate * isolate, DirectHandle< JSReceiver > object, KeyCollectionMode mode, PropertyFilter filter, GetKeysConversion keys_conversion = GetKeysConversion::kKeepNumbers, bool is_for_in = false, bool skip_indices = false) [static]
Definition at line 97 of file keys.cc.
                       {
  FastKeyAccumulator accumulator(isolate, object, mode, filter, is_for_in,
                                 skip_indices);
  return accumulator.GetKeys(keys_conversion);
}
References filter(), v8::internal::FastKeyAccumulator::GetKeys(), isolate(), and mode().
Referenced by v8::internal::BUILTIN(), CollectOwnJSProxyTargetKeys(), v8::internal::anonymous_namespace{runtime-object.cc}::CollectPrivateMembersFromReceiver(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectValuesOrEntriesImpl(), v8::internal::JSReceiver::DefineProperties(), v8::internal::DebugPropertyIterator::FillKeysForCurrentPrototypeAndStage(), v8::internal::Isolate::GetImportAttributesFromArgument(), v8::internal::FastKeyAccumulator::GetKeysSlow(), v8::internal::FastKeyAccumulator::GetKeysWithPrototypeInfoCache(), v8::internal::anonymous_namespace{builtins-object.cc}::GetOwnPropertyKeys(), v8::internal::GetOwnValuesOrEntries(), v8::debug::GetPrivateMembers(), v8::Object::GetPropertyNames(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::anonymous_namespace{ic.cc}::MaybeCanCloneObjectForObjectAssign(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JsonStringifier::SerializeJSReceiverSlow(), v8::internal::JSReceiver::SetOrCopyDataProperties(), v8::internal::DebugEvaluate::ContextBuilder::UpdateValues(), v8::internal::ScopeIterator::VisitLocalScope(), v8::internal::ValueSerializer::WriteJSArray(), and v8::internal::ValueSerializer::WriteJSObjectSlow().
GetOwnEnumPropertyKeys()
Handle< FixedArray > v8::internal::KeyAccumulator::GetOwnEnumPropertyKeys (Isolate * isolate, DirectHandle< JSObject > object) [static]
Definition at line 1181 of file keys.cc.
                                                     {
  if (object->HasFastProperties()) {
    return GetFastEnumPropertyKeys(isolate, object);
  } else if (IsJSGlobalObject(*object)) {
    return GetOwnEnumPropertyDictionaryKeys(
        isolate, KeyCollectionMode::kOwnOnly, nullptr, object,
        Cast<JSGlobalObject>(*object)->global_dictionary(kAcquireLoad));
  } else if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    return GetOwnEnumPropertyDictionaryKeys(
        isolate, KeyCollectionMode::kOwnOnly, nullptr, object,
        object->property_dictionary_swiss());
  } else {
    return GetOwnEnumPropertyDictionaryKeys(
        isolate, KeyCollectionMode::kOwnOnly, nullptr, object,
        object->property_dictionary());
  }
}
References v8::internal::anonymous_namespace{keys.cc}::GetFastEnumPropertyKeys(), v8::internal::anonymous_namespace{keys.cc}::GetOwnEnumPropertyDictionaryKeys(), isolate(), v8::kAcquireLoad, v8::internal::kOwnOnly, and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by CollectOwnPropertyNames(), v8::internal::FastKeyAccumulator::GetKeysWithPrototypeInfoCache(), and v8::internal::anonymous_namespace{keys.cc}::GetOwnKeysWithElements().
HasShadowingKeys()
bool v8::internal::KeyAccumulator::HasShadowingKeys () [private]
Definition at line 301 of file keys.cc.
{ return !shadowing_keys_.is_null(); }
References shadowing_keys_.
Referenced by CollectKeys(), and IsShadowed().
isolate()
Isolate* v8::internal::KeyAccumulator::isolate () [inline]
Definition at line 84 of file keys.h.
{ return isolate_; }
References isolate_.
Referenced by v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::AddElementsToKeyAccumulatorImpl(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::AddElementsToKeyAccumulatorImpl(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::AddElementsToKeyAccumulatorImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::AddElementsToKeyAccumulatorImpl(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::AddElementsToKeyAccumulatorImpl(), AddKey(), AddShadowingKey(), v8::internal::ElementsAccessor::CollectElementIndices(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{keys.cc}::CollectKeysFromDictionary(), CollectOwnPropertyNames(), FilterForEnumerableProperties(), v8::internal::FilterProxyKeys(), GetKeys(), and GetOwnEnumPropertyKeys().
IsShadowed()
bool v8::internal::KeyAccumulator::IsShadowed (DirectHandle< Object > key) [private]
Definition at line 303 of file keys.cc.
                                                        {
  if (!HasShadowingKeys() || skip_shadow_check_) return false;
  return shadowing_keys_->Has(isolate_, key);
}
References HasShadowingKeys(), isolate_, v8::internal::key, shadowing_keys_, and skip_shadow_check_.
Referenced by AddKey().
keys()
Handle< OrderedHashSet > v8::internal::KeyAccumulator::keys () [private]
Definition at line 125 of file keys.cc.
                                            {
  return Cast<OrderedHashSet>(keys_);
}
References keys_.
Referenced by AddKey(), AddKeysFromJSProxy(), CollectOwnJSProxyTargetKeys(), and GetKeys().
mode()
KeyCollectionMode v8::internal::KeyAccumulator::mode () [inline]
Definition at line 89 of file keys.h.
{ return mode_; }
References mode_.
Referenced by v8::internal::anonymous_namespace{keys.cc}::CollectOwnPropertyNamesInternal(), and GetKeys().
operator=()
KeyAccumulator& v8::internal::KeyAccumulator::operator= (const KeyAccumulator &) [delete]
set_first_prototype_map()
void v8::internal::KeyAccumulator::set_first_prototype_map (DirectHandle< Map > value) [inline], [private]
Definition at line 143 of file keys.h.
                                                        {
    first_prototype_map_ = value;
  }
References first_prototype_map_, and v8::internal::value.
Referenced by v8::internal::FastKeyAccumulator::GetKeysSlow(), and v8::internal::FastKeyAccumulator::GetKeysWithPrototypeInfoCache().
set_is_for_in()
void v8::internal::KeyAccumulator::set_is_for_in (bool value) [inline], [private]
Definition at line 142 of file keys.h.
{ is_for_in_ = value; }
References is_for_in_, and v8::internal::value.
Referenced by v8::internal::FastKeyAccumulator::GetKeysSlow(), and v8::internal::FastKeyAccumulator::GetKeysWithPrototypeInfoCache().
set_last_non_empty_prototype()
void v8::internal::KeyAccumulator::set_last_non_empty_prototype (DirectHandle< JSReceiver > object) [inline], [private]
Definition at line 153 of file keys.h.
                                                                     {
    last_non_empty_prototype_ = object;
  }
References last_non_empty_prototype_.
Referenced by v8::internal::FastKeyAccumulator::GetKeysSlow(), and v8::internal::FastKeyAccumulator::GetKeysWithPrototypeInfoCache().
set_may_have_elements()
void v8::internal::KeyAccumulator::set_may_have_elements (bool value) [inline], [private]
Definition at line 156 of file keys.h.
{ may_have_elements_ = value; }
References may_have_elements_, and v8::internal::value.
Referenced by v8::internal::FastKeyAccumulator::GetKeysSlow(), and v8::internal::FastKeyAccumulator::GetKeysWithPrototypeInfoCache().
set_receiver()
void v8::internal::KeyAccumulator::set_receiver (DirectHandle< JSReceiver > object) [inline], [private]
Definition at line 149 of file keys.h.
{ receiver_ = object; }
References receiver_.
Referenced by v8::internal::FastKeyAccumulator::GetKeysWithPrototypeInfoCache().
set_skip_indices()
void v8::internal::KeyAccumulator::set_skip_indices (bool value) [inline]
Definition at line 90 of file keys.h.
{ skip_indices_ = value; }
References skip_indices_, and v8::internal::value.
Referenced by v8::internal::FastKeyAccumulator::GetKeysSlow(), v8::internal::FastKeyAccumulator::GetKeysWithPrototypeInfoCache(), and v8::Object::GetPropertyNames().
set_try_prototype_info_cache()
void v8::internal::KeyAccumulator::set_try_prototype_info_cache (bool value) [inline], [private]
Definition at line 146 of file keys.h.
                                                {
    try_prototype_info_cache_ = value;
  }
References try_prototype_info_cache_, and v8::internal::value.
Referenced by v8::internal::FastKeyAccumulator::GetKeysSlow(), and v8::internal::FastKeyAccumulator::GetKeysWithPrototypeInfoCache().
Member Data Documentation
FastKeyAccumulator
friend v8::internal::KeyAccumulator::FastKeyAccumulator [private]
Definition at line 174 of file keys.h.
filter_
PropertyFilter v8::internal::KeyAccumulator::filter_ [private]
Definition at line 165 of file keys.h.
Referenced by AddKey(), AddKeysFromJSProxy(), CollectInterceptorKeysInternal(), CollectOwnElementIndices(), CollectOwnJSProxyKeys(), CollectOwnKeys(), CollectOwnPropertyNames(), and filter().
first_prototype_map_
DirectHandle<Map> v8::internal::KeyAccumulator::first_prototype_map_ [private]
Definition at line 160 of file keys.h.
Referenced by GetKeys(), and set_first_prototype_map().
is_for_in_
bool v8::internal::KeyAccumulator::is_for_in_ = false [private]
Definition at line 166 of file keys.h.
Referenced by AddKeysFromJSProxy(), CollectOwnJSProxyTargetKeys(), and set_is_for_in().
isolate_
Isolate* v8::internal::KeyAccumulator::isolate_ [private]
Definition at line 158 of file keys.h.
Referenced by AddKey(), AddKeys(), AddKeysFromJSProxy(), AddShadowingKey(), CollectAccessCheckInterceptorKeys(), CollectInterceptorKeys(), CollectInterceptorKeysInternal(), CollectKeys(), CollectOwnJSProxyKeys(), CollectOwnJSProxyTargetKeys(), CollectOwnKeys(), CollectOwnPropertyNames(), CollectPrivateNames(), FilterForEnumerableProperties(), GetKeys(), isolate(), and IsShadowed().
keys_
Handle<OrderedHashSet> v8::internal::KeyAccumulator::keys_ [private]
Definition at line 159 of file keys.h.
Referenced by AddKey(), GetKeys(), and keys().
last_non_empty_prototype_
DirectHandle<JSReceiver> v8::internal::KeyAccumulator::last_non_empty_prototype_ [private]
Definition at line 162 of file keys.h.
Referenced by CollectKeys(), and set_last_non_empty_prototype().
may_have_elements_
bool v8::internal::KeyAccumulator::may_have_elements_ = true [private]
Definition at line 171 of file keys.h.
Referenced by CollectOwnKeys(), and set_may_have_elements().
mode_
KeyCollectionMode v8::internal::KeyAccumulator::mode_ [private]
Definition at line 164 of file keys.h.
Referenced by AddShadowingKey(), CollectKeys(), CollectOwnKeys(), CollectOwnPropertyNames(), CollectPrivateNames(), and mode().
receiver_
DirectHandle<JSReceiver> v8::internal::KeyAccumulator::receiver_ [private]
Definition at line 161 of file keys.h.
Referenced by set_receiver().
shadowing_keys_
Handle<ObjectHashSet> v8::internal::KeyAccumulator::shadowing_keys_ [private]
Definition at line 163 of file keys.h.
Referenced by AddShadowingKey(), HasShadowingKeys(), and IsShadowed().
skip_indices_
bool v8::internal::KeyAccumulator::skip_indices_ = false [private]
Definition at line 167 of file keys.h.
Referenced by AddKeysFromJSProxy(), CollectAccessCheckInterceptorKeys(), CollectOwnElementIndices(), CollectOwnJSProxyTargetKeys(), and set_skip_indices().
skip_shadow_check_
bool v8::internal::KeyAccumulator::skip_shadow_check_ = true [private]
Definition at line 170 of file keys.h.
Referenced by CollectKeys(), and IsShadowed().
try_prototype_info_cache_
bool v8::internal::KeyAccumulator::try_prototype_info_cache_ = false [private]
Definition at line 172 of file keys.h.
Referenced by GetKeys(), and set_try_prototype_info_cache().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/keys.h
/mnt/V8SourceCode/src/objects/keys.cc