v8::internal::ConcurrentUnifiedHeapMarkingVisitor Class Reference
#include <unified-heap-marking-visitor.h>
Public Member Functions
ConcurrentUnifiedHeapMarkingVisitor (HeapBase &, Heap *, cppgc::internal::ConcurrentMarkingState &, CppHeap::CollectionType)
~ConcurrentUnifiedHeapMarkingVisitor () override
Protected Member Functions
bool DeferTraceToMutatorThreadIfConcurrent (const void *, cppgc::TraceCallback, size_t) final
Defers tracing an object from a concurrent thread to the mutator thread.
bool IsConcurrent () const final
Checks whether the visitor is running concurrently to the mutator or not.
Private Attributes
std::unique_ptr< MarkingWorklists::Local > local_marking_worklist_
UnifiedHeapMarkingState concurrent_unified_heap_marking_state_
Additional Inherited Members
Detailed Description
Definition at line 77 of file unified-heap-marking-visitor.h.
Constructor & Destructor Documentation
ConcurrentUnifiedHeapMarkingVisitor()
v8::internal::ConcurrentUnifiedHeapMarkingVisitor::ConcurrentUnifiedHeapMarkingVisitor (HeapBase & heap, Heap * v8_heap, cppgc::internal::ConcurrentMarkingState & marking_state, CppHeap::CollectionType collection_type)
Definition at line 114 of file unified-heap-marking-visitor.cc.
    : UnifiedHeapMarkingVisitorBase(heap, marking_state,
                                    concurrent_unified_heap_marking_state_),
      local_marking_worklist_(GetV8MarkingWorklists(v8_heap, collection_type)),
      concurrent_unified_heap_marking_state_(
          v8_heap, local_marking_worklist_.get(), collection_type) {
#ifdef V8_COMPRESS_POINTERS_IN_MULTIPLE_CAGES
  // This method might be called on a thread that's not bound to any Isolate
  // and thus IsolateGroup::current could be unset.
  saved_isolate_group_ = IsolateGroup::current();
  IsolateGroup::set_current(v8_heap->isolate()->isolate_group());
#endif
}
References v8::internal::IsolateGroup::current(), v8::internal::Heap::isolate(), and v8::internal::Isolate::isolate_group().
 ConcurrentUnifiedHeapMarkingVisitor()
v8::internal::ConcurrentUnifiedHeapMarkingVisitor::~ConcurrentUnifiedHeapMarkingVisitor () [override]
Definition at line 131 of file unified-heap-marking-visitor.cc.
                                                                          {
  if (local_marking_worklist_) {
    local_marking_worklist_->Publish();
  }
#ifdef V8_COMPRESS_POINTERS_IN_MULTIPLE_CAGES
  IsolateGroup::set_current(saved_isolate_group_);
#endif
}
References local_marking_worklist_.
Member Function Documentation
DeferTraceToMutatorThreadIfConcurrent()
bool v8::internal::ConcurrentUnifiedHeapMarkingVisitor::DeferTraceToMutatorThreadIfConcurrent (const void * parameter, cppgc::TraceCallback callback, size_t deferred_size) [final], [protected], [virtual]
Defers tracing an object from a concurrent thread to the mutator thread.
Should be called by Trace methods of types that are not safe to trace concurrently.
Parameters
parameter tells the trace callback which object was deferred.
callback to be invoked for tracing on the mutator thread.
deferred_size size of deferred object.
Returns
false if the object does not need to be deferred (i.e. currently traced on the mutator thread) and true otherwise (i.e. currently traced on a concurrent thread).
Reimplemented from cppgc::Visitor.
Definition at line 140 of file unified-heap-marking-visitor.cc.
                          {
  marking_state_.concurrent_marking_bailout_worklist().Push(
      {parameter, callback, deferred_size});
  static_cast<cppgc::internal::ConcurrentMarkingState&>(marking_state_)
      .AccountDeferredMarkedBytes(
          cppgc::internal::BasePage::FromPayload(const_cast<void*>(parameter)),
          deferred_size);
  return true;
}
References cppgc::internal::BasicMarkingState::concurrent_marking_bailout_worklist(), cppgc::internal::BasePage::FromPayload(), and v8::internal::UnifiedHeapMarkingVisitorBase::marking_state_.
IsConcurrent()
bool v8::internal::ConcurrentUnifiedHeapMarkingVisitor::IsConcurrent () const [inline], [final], [protected], [virtual]
Checks whether the visitor is running concurrently to the mutator or not.
Reimplemented from cppgc::Visitor.
Definition at line 88 of file unified-heap-marking-visitor.h.
{ return true; }
Member Data Documentation
concurrent_unified_heap_marking_state_
UnifiedHeapMarkingState v8::internal::ConcurrentUnifiedHeapMarkingVisitor::concurrent_unified_heap_marking_state_ [private]
Definition at line 97 of file unified-heap-marking-visitor.h.
local_marking_worklist_
std::unique_ptr<MarkingWorklists::Local> v8::internal::ConcurrentUnifiedHeapMarkingVisitor::local_marking_worklist_ [private]
Definition at line 96 of file unified-heap-marking-visitor.h.
Referenced by ~ConcurrentUnifiedHeapMarkingVisitor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc-js/unified-heap-marking-visitor.h
/mnt/V8SourceCode/src/heap/cppgc-js/unified-heap-marking-visitor.cc