v8::internal::JsonString Class Reference
#include <json-parser.h>
Public Member Functions
JsonString ()
JsonString (uint32_t index)
JsonString (uint32_t start, uint32_t length, bool needs_conversion, bool internalize, bool has_escape)
bool internalize () const
bool needs_conversion () const
bool has_escape () const
uint32_t start () const
uint32_t length () const
uint32_t index () const
bool is_index () const
Private Attributes
xx xx xx xx xx xx xx xx xx
union {
 const uint32_t start_
 const uint32_t index_
};
const uint32_t length_
const bool needs_conversion_: 1
const bool internalize_: 1
const bool has_escape_: 1
const bool is_index_: 1
Detailed Description
Definition at line 26 of file json-parser.h.
Constructor & Destructor Documentation
JsonString() [1/3]
v8::internal::JsonString::JsonString () [inline]
Definition at line 28 of file json-parser.h.
      : start_(0),
        length_(0),
        needs_conversion_(false),
        internalize_(false),
        has_escape_(false),
        is_index_(false) {}
JsonString() [2/3]
v8::internal::JsonString::JsonString (uint32_t index) [inline], [explicit]
Definition at line 36 of file json-parser.h.
      : index_(index),
        length_(0),
        needs_conversion_(false),
        internalize_(false),
        has_escape_(false),
        is_index_(true) {}
JsonString() [3/3]
v8::internal::JsonString::JsonString (uint32_t start, uint32_t length, bool needs_conversion, bool internalize, bool has_escape) [inline]
Definition at line 44 of file json-parser.h.
      : start_(start),
        length_(length),
        needs_conversion_(needs_conversion),
        internalize_(internalize),
        has_escape_(has_escape),
        is_index_(false) {}
Member Function Documentation
has_escape()
bool v8::internal::JsonString::has_escape () const [inline]
Definition at line 63 of file json-parser.h.
                          {
    DCHECK(!is_index_);
    return has_escape_;
  }
References v8::internal::DCHECK(), has_escape_, and is_index_.
index()
uint32_t v8::internal::JsonString::index () const [inline]
Definition at line 78 of file json-parser.h.
                         {
    DCHECK(is_index_);
    return index_;
  }
References v8::internal::DCHECK(), index_, and is_index_.
internalize()
bool v8::internal::JsonString::internalize () const [inline]
Definition at line 53 of file json-parser.h.
                           {
    DCHECK(!is_index_);
    return internalize_;
  }
References v8::internal::DCHECK(), internalize_, and is_index_.
is_index()
bool v8::internal::JsonString::is_index () const [inline]
Definition at line 83 of file json-parser.h.
{ return is_index_; }
References is_index_.
Referenced by v8::internal::NamedPropertyValueIterator::NamedPropertyValueIterator(), and v8::internal::NamedPropertyValueIterator::operator++().
length()
uint32_t v8::internal::JsonString::length () const [inline]
Definition at line 73 of file json-parser.h.
                          {
    DCHECK(!is_index_);
    return length_;
  }
References v8::internal::DCHECK(), is_index_, and length_.
needs_conversion()
bool v8::internal::JsonString::needs_conversion () const [inline]
Definition at line 58 of file json-parser.h.
                                {
    DCHECK(!is_index_);
    return needs_conversion_;
  }
References v8::internal::DCHECK(), is_index_, and needs_conversion_.
start()
uint32_t v8::internal::JsonString::start () const [inline]
Definition at line 68 of file json-parser.h.
                         {
    DCHECK(!is_index_);
    return start_;
  }
References v8::internal::DCHECK(), is_index_, and start_.
Member Data Documentation
union { ... } [private]
has_escape_
const bool v8::internal::JsonString::has_escape_ [private]
Definition at line 93 of file json-parser.h.
Referenced by has_escape().
index_
const uint32_t v8::internal::JsonString::index_
Definition at line 88 of file json-parser.h.
Referenced by index().
internalize_
const bool v8::internal::JsonString::internalize_ [private]
Definition at line 92 of file json-parser.h.
Referenced by internalize().
is_index_
const bool v8::internal::JsonString::is_index_ [private]
Definition at line 94 of file json-parser.h.
Referenced by has_escape(), index(), internalize(), is_index(), length(), needs_conversion(), and start().
length_
const uint32_t v8::internal::JsonString::length_ [private]
Definition at line 90 of file json-parser.h.
Referenced by length().
needs_conversion_
const bool v8::internal::JsonString::needs_conversion_ [private]
Definition at line 91 of file json-parser.h.
Referenced by needs_conversion().
start_
const uint32_t v8::internal::JsonString::start_
Definition at line 87 of file json-parser.h.
Referenced by start().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/json/json-parser.h