v8::internal::compiler::NodeMarker< State > Class Template Reference
#include <node-marker.h>
Public Member Functions
NodeMarker (TFGraph *graph, uint32_t num_states)
State Get (const Node *node)
void Set (Node *node, State state)
Detailed Description
template<typename State>
class v8::internal::compiler::NodeMarker< State >
Definition at line 60 of file node-marker.h.
Constructor & Destructor Documentation
NodeMarker()
template<typename State >
v8::internal::compiler::NodeMarker< State >::NodeMarker (TFGraph * graph, uint32_t num_states) [inline]
Definition at line 62 of file node-marker.h.
      : NodeMarkerBase(graph, num_states) {}
Member Function Documentation
Get()
template<typename State >
State v8::internal::compiler::NodeMarker< State >::Get (const Node * node) [inline]
Definition at line 65 of file node-marker.h.
                                        {
    return static_cast<State>(NodeMarkerBase::Get(node));
  }
References v8::internal::compiler::NodeMarkerBase::Get().
Referenced by v8::internal::compiler::BitcastElider::Enqueue(), v8::internal::compiler::NodeCopier::Marked(), v8::internal::compiler::LoopFinderImpl::Queue(), v8::internal::compiler::CFGBuilder::Queue(), and v8::internal::compiler::LoopVariableOptimizer::Run().
Set()
template<typename State >
void v8::internal::compiler::NodeMarker< State >::Set (Node * node, State state) [inline]
Definition at line 69 of file node-marker.h.
                                              {
    NodeMarkerBase::Set(node, static_cast<Mark>(state));
  }
References v8::internal::compiler::NodeMarkerBase::Set().
Referenced by v8::internal::compiler::NodeCopier::CopyNodes(), v8::internal::compiler::BitcastElider::Enqueue(), v8::internal::compiler::LoopFinderImpl::PropagateBackward(), v8::internal::compiler::LoopFinderImpl::PropagateForward(), v8::internal::compiler::LoopFinderImpl::Queue(), v8::internal::compiler::CFGBuilder::Queue(), and v8::internal::compiler::LoopVariableOptimizer::Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/node-marker.h