v8::base::TemplateHashMap< Key, Value, MatchFun, AllocationPolicy > Class Template Reference
#include <hashmap.h>
Classes
class Iterator
struct value_type
Public Member Functions
TemplateHashMap (MatchFun match, AllocationPolicy allocator=AllocationPolicy())
Iterator begin () const
Iterator end () const
Iterator find (Key *key, bool insert=false)
Private Types
using Base = TemplateHashMapImpl< void *, void *, HashEqualityThenKeyMatcher< void *, MatchFun >, AllocationPolicy >
Additional Inherited Members
Detailed Description
template<class Key, class Value, class MatchFun, class AllocationPolicy>
class v8::base::TemplateHashMap< Key, Value, MatchFun, AllocationPolicy >
Definition at line 535 of file hashmap.h.
Member Typedef Documentation
Base
template<class Key , class Value , class MatchFun , class AllocationPolicy >
using v8::base::TemplateHashMap< Key, Value, MatchFun, AllocationPolicy >::Base = TemplateHashMapImpl<void*, void*, HashEqualityThenKeyMatcher<void*, MatchFun>, AllocationPolicy> [private]
Definition at line 539 of file hashmap.h.
Constructor & Destructor Documentation
TemplateHashMap()
template<class Key , class Value , class MatchFun , class AllocationPolicy >
v8::base::TemplateHashMap< Key, Value, MatchFun, AllocationPolicy >::TemplateHashMap (MatchFun match, AllocationPolicy allocator = AllocationPolicy()) [inline], [explicit]
Definition at line 571 of file hashmap.h.
      : Base(Base::kDefaultHashMapCapacity,
             HashEqualityThenKeyMatcher<void*, MatchFun>(match), allocator) {}
Member Function Documentation
begin()
template<class Key , class Value , class MatchFun , class AllocationPolicy >
Iterator v8::base::TemplateHashMap< Key, Value, MatchFun, AllocationPolicy >::begin () const [inline]
Definition at line 576 of file hashmap.h.
{ return Iterator(this, this->Start()); }
References v8::base::TemplateHashMapImpl< void *, void *, HashEqualityThenKeyMatcher< void *, MatchFun >, AllocationPolicy >::Start().
end()
template<class Key , class Value , class MatchFun , class AllocationPolicy >
Iterator v8::base::TemplateHashMap< Key, Value, MatchFun, AllocationPolicy >::end () const [inline]
Definition at line 577 of file hashmap.h.
{ return Iterator(this, nullptr); }
find()
template<class Key , class Value , class MatchFun , class AllocationPolicy >
Iterator v8::base::TemplateHashMap< Key, Value, MatchFun, AllocationPolicy >::find (Key * key, bool insert = false) [inline]
Definition at line 578 of file hashmap.h.
                                               {
    if (insert) {
      return Iterator(this, this->LookupOrInsert(key, key->Hash()));
    }
    return Iterator(this, this->Lookup(key, key->Hash()));
  }
References v8::internal::key, v8::base::TemplateHashMapImpl< void *, void *, HashEqualityThenKeyMatcher< void *, MatchFun >, AllocationPolicy >::Lookup(), and v8::base::TemplateHashMapImpl< void *, void *, HashEqualityThenKeyMatcher< void *, MatchFun >, AllocationPolicy >::LookupOrInsert().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/hashmap.h