v8::internal::compiler::NewArgumentsElementsParameters Class Reference
#include <simplified-operator.h>
Public Member Functions
NewArgumentsElementsParameters (CreateArgumentsType type, int formal_parameter_count)
CreateArgumentsType arguments_type () const
int formal_parameter_count () const
Private Attributes
CreateArgumentsType type_
int formal_parameter_count_
Detailed Description
Definition at line 717 of file simplified-operator.h.
Constructor & Destructor Documentation
NewArgumentsElementsParameters()
v8::internal::compiler::NewArgumentsElementsParameters::NewArgumentsElementsParameters (CreateArgumentsType type, int formal_parameter_count) [inline]
Definition at line 719 of file simplified-operator.h.
      : type_(type), formal_parameter_count_(formal_parameter_count) {}
Member Function Documentation
arguments_type()
CreateArgumentsType v8::internal::compiler::NewArgumentsElementsParameters::arguments_type () const [inline]
Definition at line 723 of file simplified-operator.h.
{ return type_; }
Referenced by v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
formal_parameter_count()
int v8::internal::compiler::NewArgumentsElementsParameters::formal_parameter_count () const [inline]
Definition at line 724 of file simplified-operator.h.
{ return formal_parameter_count_; }
Referenced by v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
Member Data Documentation
formal_parameter_count_
int v8::internal::compiler::NewArgumentsElementsParameters::formal_parameter_count_ [private]
Definition at line 728 of file simplified-operator.h.
type_
CreateArgumentsType v8::internal::compiler::NewArgumentsElementsParameters::type_ [private]
Definition at line 727 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h