v8::internal::compiler::StackSlotRepresentation Class Reference
#include <machine-operator.h>
Public Member Functions
StackSlotRepresentation (int size, int alignment, bool is_tagged)
int size () const
int alignment () const
bool is_tagged () const
Private Attributes
int size_
int alignment_
bool is_tagged_
Detailed Description
Definition at line 270 of file machine-operator.h.
Constructor & Destructor Documentation
StackSlotRepresentation()
v8::internal::compiler::StackSlotRepresentation::StackSlotRepresentation (int size, int alignment, bool is_tagged) [inline]
Definition at line 272 of file machine-operator.h.
      : size_(size), alignment_(alignment), is_tagged_(is_tagged) {}
Member Function Documentation
alignment()
int v8::internal::compiler::StackSlotRepresentation::alignment () const [inline]
Definition at line 276 of file machine-operator.h.
{ return alignment_; }
References alignment_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
is_tagged()
bool v8::internal::compiler::StackSlotRepresentation::is_tagged () const [inline]
Definition at line 277 of file machine-operator.h.
{ return is_tagged_; }
References is_tagged_.
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
size()
int v8::internal::compiler::StackSlotRepresentation::size () const [inline]
Definition at line 275 of file machine-operator.h.
{ return size_; }
References size_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
Member Data Documentation
alignment_
int v8::internal::compiler::StackSlotRepresentation::alignment_ [private]
Definition at line 281 of file machine-operator.h.
Referenced by alignment().
is_tagged_
bool v8::internal::compiler::StackSlotRepresentation::is_tagged_ [private]
Definition at line 282 of file machine-operator.h.
Referenced by is_tagged().
size_
int v8::internal::compiler::StackSlotRepresentation::size_ [private]
Definition at line 280 of file machine-operator.h.
Referenced by size().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/machine-operator.h