v8::InspectorClient Class Reference
Public Member Functions
InspectorClient (Isolate *isolate, const Global< Context > &global_context, bool connect)
void runMessageLoopOnPause (int contextGroupId) override
void quitMessageLoopOnPause () override
Private Member Functions
Local< Context > ensureDefaultContextInGroup (int group_id) override
Static Private Member Functions
static v8_inspector::V8InspectorSession * GetSession (Local< Context > context)
static void SendInspectorMessage (const v8::FunctionCallbackInfo< v8::Value > &info)
Private Attributes
std::unique_ptr< v8_inspector::V8Inspector > inspector_
std::unique_ptr< v8_inspector::V8InspectorSession > session_
std::unique_ptr< v8_inspector::V8Inspector::Channel > channel_
bool is_paused = false
Global< Context > context_
Isolate * isolate_
Static Private Attributes
static const int kContextGroupId = 1
Additional Inherited Members
Detailed Description
Definition at line 5051 of file d8.cc.
Constructor & Destructor Documentation
InspectorClient()
v8::InspectorClient::InspectorClient (Isolate * isolate, const Global< Context > & global_context, bool connect) [inline]
Definition at line 5053 of file d8.cc.
                                {
    if (!connect) return;
    isolate_ = isolate;
    Local<Context> context = global_context.Get(isolate);
    channel_.reset(new InspectorFrontend(context));
    inspector_ = v8_inspector::V8Inspector::create(isolate_, this);
    session_ =
        inspector_->connect(1, channel_.get(), v8_inspector::StringView(),
                            v8_inspector::V8Inspector::kFullyTrusted,
                            v8_inspector::V8Inspector::kNotWaitingForDebugger);
    context->SetAlignedPointerInEmbedderData(kInspectorClientIndex, this);
    inspector_->contextCreated(v8_inspector::V8ContextInfo(
        context, kContextGroupId, v8_inspector::StringView()));
    Local<Value> function =
        FunctionTemplate::New(isolate_, SendInspectorMessage)
            ->GetFunction(context)
            .ToLocalChecked();
    Local<String> function_name = String::NewFromUtf8Literal(
        isolate_, "send", NewStringType::kInternalized);
    CHECK(context->Global()->Set(context, function_name, function).FromJust());
    context_.Reset(isolate_, global_context);
  }
References CHECK, v8_inspector::V8Inspector::create(), v8::PersistentBase< T >::Get(), v8::Context::Global(), v8::PerIsolateData::isolate_, v8_inspector::V8Inspector::kFullyTrusted, v8::anonymous_namespace{d8.cc}::kInspectorClientIndex, v8::kInternalized, v8_inspector::V8Inspector::kNotWaitingForDebugger, v8::FunctionTemplate::New(), v8::String::NewFromUtf8Literal(), v8::Object::Set(), and v8::Context::SetAlignedPointerInEmbedderData().
Member Function Documentation
ensureDefaultContextInGroup()
Local<Context> v8::InspectorClient::ensureDefaultContextInGroup (int group_id) [inline], [override], [private], [virtual]
Reimplemented from v8_inspector::V8InspectorClient.
Definition at line 5118 of file d8.cc.
                                                                    {
    DCHECK(isolate_);
    DCHECK_EQ(kContextGroupId, group_id);
    return context_.Get(isolate_);
  }
References DCHECK, DCHECK_EQ, and v8::PerIsolateData::isolate_.
GetSession()
static v8_inspector::V8InspectorSession* v8::InspectorClient::GetSession (Local< Context > context) [inline], [static], [private]
Definition at line 5112 of file d8.cc.
                                                                            {
    InspectorClient* inspector_client = static_cast<InspectorClient*>(
        context->GetAlignedPointerFromEmbedderData(kInspectorClientIndex));
    return inspector_client->session_.get();
  }
References v8::Context::GetAlignedPointerFromEmbedderData(), v8::anonymous_namespace{d8.cc}::kInspectorClientIndex, and session_.
Referenced by SendInspectorMessage().
quitMessageLoopOnPause()
void v8::InspectorClient::quitMessageLoopOnPause () [inline], [override], [virtual]
Reimplemented from v8_inspector::V8InspectorClient.
Definition at line 5109 of file d8.cc.
{ is_paused = false; }
runMessageLoopOnPause()
void v8::InspectorClient::runMessageLoopOnPause (int contextGroupId) [inline], [override], [virtual]
Reimplemented from v8_inspector::V8InspectorClient.
Definition at line 5079 of file d8.cc.
                                                          {
    v8::Isolate::AllowJavascriptExecutionScope allow_script(isolate_);
    v8::HandleScope handle_scope(isolate_);
    Local<String> callback_name = v8::String::NewFromUtf8Literal(
        isolate_, "handleInspectorMessage", NewStringType::kInternalized);
    Local<Context> context = context_.Get(isolate_);
    Local<Value> callback =
        context->Global()->Get(context, callback_name).ToLocalChecked();
    if (!callback->IsFunction()) return;
    // Running the message loop below may trigger the execution of a stackless
    // GC. We need to override the embedder stack state, to force scanning the
    // stack, if this happens.
    i::Heap* heap = reinterpret_cast<i::Isolate*>(isolate_)->heap();
    i::EmbedderStackStateScope stack_scanning_scope(
        heap, i::EmbedderStackStateOrigin::kExplicitInvocation,
        v8::StackState::kMayContainHeapPointers);
    v8::TryCatch try_catch(isolate_);
    try_catch.SetVerbose(true);
    is_paused = true;
    while (is_paused) {
      USE(callback.As<Function>()->Call(context, Undefined(isolate_), 0, {}));
      if (try_catch.HasCaught()) {
        is_paused = false;
      }
    }
  }
References v8::Local< T >::As(), v8::Function::Call(), v8::Object::Get(), v8::Context::Global(), v8::TryCatch::HasCaught(), heap(), v8::PerIsolateData::isolate_, v8::kInternalized, v8::String::NewFromUtf8Literal(), v8::TryCatch::SetVerbose(), v8::MaybeLocal< T >::ToLocalChecked(), v8::Undefined(), and USE.
SendInspectorMessage()
static void v8::InspectorClient::SendInspectorMessage (const v8::FunctionCallbackInfo< v8::Value > & info) [inline], [static], [private]
Definition at line 5124 of file d8.cc.
                                                   {
    DCHECK(i::ValidateCallbackInfo(info));
    Isolate* isolate = info.GetIsolate();
    v8::HandleScope handle_scope(isolate);
    Local<Context> context = isolate->GetCurrentContext();
    info.GetReturnValue().Set(Undefined(isolate));
    Local<String> message = info[0]->ToString(context).ToLocalChecked();
    v8_inspector::V8InspectorSession* session =
        InspectorClient::GetSession(context);
    uint32_t length = message->Length();
    std::unique_ptr<uint16_t[]> buffer(new uint16_t[length]);
    message->WriteV2(isolate, 0, length, buffer.get());
    v8_inspector::StringView message_view(buffer.get(), length);
    {
      v8::SealHandleScope seal_handle_scope(isolate);
      session->dispatchProtocolMessage(message_view);
    }
    info.GetReturnValue().Set(True(isolate));
  }
References DCHECK, v8_inspector::V8InspectorSession::dispatchProtocolMessage(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), GetSession(), v8::internal::length, v8::True(), v8::Undefined(), and v8::internal::ValidateCallbackInfo().
Member Data Documentation
channel_
std::unique_ptr<v8_inspector::V8Inspector::Channel> v8::InspectorClient::channel_ [private]
Definition at line 5149 of file d8.cc.
context_
Global<Context> v8::InspectorClient::context_ [private]
Definition at line 5151 of file d8.cc.
inspector_
std::unique_ptr<v8_inspector::V8Inspector> v8::InspectorClient::inspector_ [private]
Definition at line 5147 of file d8.cc.
is_paused
bool v8::InspectorClient::is_paused = false [private]
Definition at line 5150 of file d8.cc.
isolate_
Isolate* v8::InspectorClient::isolate_ [private]
Definition at line 5152 of file d8.cc.
kContextGroupId
const int v8::InspectorClient::kContextGroupId = 1 [static], [private]
Definition at line 5145 of file d8.cc.
session_
std::unique_ptr<v8_inspector::V8InspectorSession> v8::InspectorClient::session_ [private]
Definition at line 5148 of file d8.cc.
Referenced by GetSession().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/d8/d8.cc