v8::internal::Parser Class Reference
#include <parser.h>
Classes
struct ExportClauseData
struct NamedImport
class ParsingModeScope
class TemplateLiteral
Public Member Functions
Parser (LocalIsolate *local_isolate, ParseInfo *info)
~Parser ()
void ParseOnBackground (LocalIsolate *isolate, ParseInfo *info, DirectHandle< Script > script, int start_position, int end_position, int function_literal_id)
void InitializeEmptyScopeChain (ParseInfo *info)
template<typename IsolateT >
void DeserializeScopeChain (IsolateT *isolate, ParseInfo *info, MaybeDirectHandle< ScopeInfo > maybe_outer_scope_info, Scope::DeserializationMode mode=Scope::DeserializationMode::kScopesOnly)
void UpdateStatistics (Isolate *isolate, DirectHandle< Script > script)
void UpdateStatistics (DirectHandle< Script > script, base::SmallVector< v8::Isolate::UseCounterFeature, 8 > *use_counters, int *preparse_skipped)
template<typename IsolateT >
void HandleDebugMagicComments (IsolateT *isolate, DirectHandle< Script > script)
Static Public Member Functions
static bool IsPreParser ()
Private Types
enum Mode { PARSE_LAZILY
, PARSE_EAGERLY
 }
enum CompletionKind { kNormalCompletion
, kThrowCompletion
, kAbruptCompletion
 }
using TemplateLiteralState = TemplateLiteral *
Private Member Functions
bool AllowsLazyParsingWithoutUnresolvedVariables () const
bool parse_lazily () const
Variable * NewTemporary (const AstRawString *name)
void PrepareGeneratorVariables ()
void ParseProgram (Isolate *isolate, DirectHandle< Script > script, ParseInfo *info, MaybeDirectHandle< ScopeInfo > maybe_outer_scope_info)
void ParseFunction (Isolate *isolate, ParseInfo *info, DirectHandle< SharedFunctionInfo > shared_info)
template<typename IsolateT >
void PostProcessParseResult (IsolateT *isolate, ParseInfo *info, FunctionLiteral *literal)
FunctionLiteral * DoParseFunction (Isolate *isolate, ParseInfo *info, int start_position, int end_position, int function_literal_id, const AstRawString *raw_name)
FunctionLiteral * ParseClassForMemberInitialization (FunctionKind initializer_kind, int initializer_pos, int initializer_id, int initializer_end_pos, const AstRawString *class_name)
FunctionLiteral * DoParseProgram (Isolate *isolate, ParseInfo *info)
void ParseWrapped (Isolate *isolate, ParseInfo *info, ScopedPtrList< Statement > *body, DeclarationScope *scope, Zone *zone)
void ParseREPLProgram (ParseInfo *info, ScopedPtrList< Statement > *body, DeclarationScope *scope)
Expression * WrapREPLResult (Expression *value)
ZonePtrList< const AstRawString > * PrepareWrappedArguments (Isolate *isolate, ParseInfo *info, Zone *zone)
PreParser * reusable_preparser ()
void ParseModuleItemList (ScopedPtrList< Statement > *body)
Statement * ParseModuleItem ()
const AstRawString * ParseModuleSpecifier ()
void ParseImportDeclaration ()
Statement * ParseExportDeclaration ()
Statement * ParseExportDefault ()
void ParseExportStar ()
ZoneChunkList< ExportClauseData > * ParseExportClause (Scanner::Location *reserved_loc, Scanner::Location *string_literal_local_name_loc)
const AstRawString * ParseExportSpecifierName ()
ZonePtrList< const NamedImport > * ParseNamedImports (int pos)
ImportAttributes * ParseImportWithOrAssertClause ()
Statement * BuildInitializationBlock (DeclarationParsingResult *parsing_result)
Statement * RewriteSwitchStatement (SwitchStatement *switch_statement, Scope *scope)
Block * RewriteCatchPattern (CatchInfo *catch_info)
void ReportVarRedeclarationIn (const AstRawString *name, Scope *scope)
Statement * RewriteTryStatement (Block *try_block, Block *catch_block, const SourceRange &catch_range, Block *finally_block, const SourceRange &finally_range, const CatchInfo &catch_info, int pos)
void ParseGeneratorFunctionBody (int pos, FunctionKind kind, ScopedPtrList< Statement > *body)
void ParseAsyncGeneratorFunctionBody (int pos, FunctionKind kind, ScopedPtrList< Statement > *body)
void DeclareFunctionNameVar (const AstRawString *function_name, FunctionSyntaxKind function_syntax_kind, DeclarationScope *function_scope)
Statement * DeclareFunction (const AstRawString *variable_name, FunctionLiteral *function, VariableMode mode, VariableKind kind, int beg_pos, int end_pos, ZonePtrList< const AstRawString > *names)
VariableProxy * CreateSyntheticContextVariableProxy (ClassScope *scope, ClassInfo *class_info, const AstRawString *name, bool is_static)
VariableProxy * CreatePrivateNameVariable (ClassScope *scope, VariableMode mode, IsStaticFlag is_static_flag, const AstRawString *name)
FunctionLiteral * CreateInitializerFunction (const AstRawString *class_name, DeclarationScope *scope, int function_literal_id, Statement *initializer_stmt)
bool IdentifierEquals (const AstRawString *identifier, const AstRawString *other)
Statement * DeclareClass (const AstRawString *variable_name, Expression *value, ZonePtrList< const AstRawString > *names, int class_token_pos, int end_pos)
void DeclareClassVariable (ClassScope *scope, const AstRawString *name, ClassInfo *class_info, int class_token_pos)
void DeclareClassBrandVariable (ClassScope *scope, ClassInfo *class_info, int class_token_pos)
void AddInstanceFieldOrStaticElement (ClassLiteralProperty *property, ClassInfo *class_info, bool is_static)
void DeclarePrivateClassMember (ClassScope *scope, const AstRawString *property_name, ClassLiteralProperty *property, ClassLiteralProperty::Kind kind, bool is_static, ClassInfo *class_info)
void DeclarePublicClassMethod (const AstRawString *class_name, ClassLiteralProperty *property, bool is_constructor, ClassInfo *class_info)
void DeclarePublicClassField (ClassScope *scope, ClassLiteralProperty *property, bool is_static, bool is_computed_name, ClassInfo *class_info)
void DeclareClassProperty (ClassScope *scope, const AstRawString *class_name, ClassLiteralProperty *property, bool is_constructor, ClassInfo *class_info)
void DeclareClassField (ClassScope *scope, ClassLiteralProperty *property, const AstRawString *property_name, bool is_static, bool is_computed_name, bool is_private, ClassInfo *class_info)
void AddClassStaticBlock (Block *block, ClassInfo *class_info)
FunctionLiteral * CreateStaticElementsInitializer (const AstRawString *name, ClassInfo *class_info)
FunctionLiteral * CreateInstanceMembersInitializer (const AstRawString *name, ClassInfo *class_info)
Expression * RewriteClassLiteral (ClassScope *block_scope, const AstRawString *name, ClassInfo *class_info, int pos)
Statement * DeclareNative (const AstRawString *name, int pos)
Block * IgnoreCompletion (Statement *statement)
bool HasCheckedSyntax ()
void InitializeVariables (ScopedPtrList< Statement > *statements, VariableKind kind, const DeclarationParsingResult::Declaration *declaration)
Block * RewriteForVarInLegacy (const ForInfo &for_info)
void DesugarBindingInForEachStatement (ForInfo *for_info, Block **body_block, Expression **each_variable)
Block * CreateForEachStatementTDZ (Block *init_block, const ForInfo &for_info)
Statement * DesugarLexicalBindingsInForStatement (ForStatement *loop, Statement *init, Expression *cond, Statement *next, Statement *body, Scope *inner_scope, const ForInfo &for_info)
FunctionLiteral * ParseFunctionLiteral (const AstRawString *name, Scanner::Location function_name_location, FunctionNameValidity function_name_validity, FunctionKind kind, int function_token_position, FunctionSyntaxKind type, LanguageMode language_mode, ZonePtrList< const AstRawString > *arguments_for_wrapped_function)
ObjectLiteral * InitializeObjectLiteral (ObjectLiteral *object_literal)
void InsertShadowingVarBindingInitializers (Block *block)
void InsertSloppyBlockFunctionVarBindings (DeclarationScope *scope)
void DeclareUnboundVariable (const AstRawString *name, VariableMode mode, InitializationFlag init, int pos)
V8_WARN_UNUSED_RESULT VariableProxy * DeclareBoundVariable (const AstRawString *name, VariableMode mode, int pos)
void DeclareAndBindVariable (VariableProxy *proxy, VariableKind kind, VariableMode mode, Scope *declaration_scope, bool *was_added, int initializer_position)
V8_WARN_UNUSED_RESULT Variable * DeclareVariable (const AstRawString *name, VariableKind kind, VariableMode mode, InitializationFlag init, Scope *declaration_scope, bool *was_added, int begin, int end=kNoSourcePosition)
void Declare (Declaration *declaration, const AstRawString *name, VariableKind kind, VariableMode mode, InitializationFlag init, Scope *declaration_scope, bool *was_added, int var_begin_pos, int var_end_pos=kNoSourcePosition)
FunctionLiteral * DefaultConstructor (const AstRawString *name, bool call_super, int pos)
FunctionLiteral * MakeAutoAccessorGetter (VariableProxy *name_proxy, const AstRawString *name, bool is_static, int pos)
FunctionLiteral * MakeAutoAccessorSetter (VariableProxy *name_proxy, const AstRawString *name, bool is_static, int pos)
AutoAccessorInfo * NewAutoAccessorInfo (ClassScope *scope, ClassInfo *class_info, const AstRawString *name, bool is_static, int pos)
ClassLiteralProperty * NewClassLiteralPropertyWithAccessorInfo (ClassScope *scope, ClassInfo *class_info, const AstRawString *name, Expression *key, Expression *value, bool is_static, bool is_computed_name, bool is_private, int pos)
bool SkipFunction (const AstRawString *function_name, FunctionKind kind, FunctionSyntaxKind function_syntax_kind, DeclarationScope *function_scope, int *num_parameters, int *function_length, ProducedPreparseData **produced_preparsed_scope_data)
Block * BuildParameterInitializationBlock (const ParserFormalParameters &parameters)
void ParseFunction (ScopedPtrList< Statement > *body, const AstRawString *function_name, int pos, FunctionKind kind, FunctionSyntaxKind function_syntax_kind, DeclarationScope *function_scope, int *num_parameters, int *function_length, bool *has_duplicate_parameters, int *expected_property_count, int *suspend_count, ZonePtrList< const AstRawString > *arguments_for_wrapped_function)
void ThrowPendingError (Isolate *isolate, Handle< Script > script)
TemplateLiteralState OpenTemplateLiteral (int pos)
void AddTemplateSpan (TemplateLiteralState *state, bool should_cook, bool tail)
void AddTemplateExpression (TemplateLiteralState *state, Expression *expression)
Expression * CloseTemplateLiteral (TemplateLiteralState *state, int start, Expression *tag)
Expression * RewriteSuperCall (Expression *call_expression)
void SetLanguageMode (Scope *scope, LanguageMode mode)
Expression * RewriteSpreads (ArrayLiteral *lit)
Expression * BuildInitialYield (int pos, FunctionKind kind)
Assignment * BuildCreateJSGeneratorObject (int pos, FunctionKind kind)
Expression * NewThrowError (Runtime::FunctionId function_id, MessageTemplate message, const AstRawString *arg, int pos)
void AddArrowFunctionFormalParameters (ParserFormalParameters *parameters, Expression *params, int end_pos)
void SetFunctionName (Expression *value, const AstRawString *name, const AstRawString *prefix=nullptr)
bool IsEval (const AstRawString *identifier) const
bool IsAsync (const AstRawString *identifier) const
bool IsArguments (const AstRawString *identifier) const
bool IsEvalOrArguments (const AstRawString *identifier) const
VariableProxy * AsIdentifierExpression (Expression *expression)
bool IsConstructor (const AstRawString *identifier) const
v8::Extension * extension () const
bool ParsingExtension () const
bool IsNative (Expression *expr) const
bool IsStringLiteral (Statement *statement, const AstRawString *arg=nullptr) const
void GetDefaultStrings (const AstRawString **default_string, const AstRawString **dot_default_string)
void PushLiteralName (const AstRawString *id)
void PushVariableName (const AstRawString *id)
void PushPropertyName (Expression *expression)
void PushEnclosingName (const AstRawString *name)
void AddFunctionForNameInference (FunctionLiteral *func_to_infer)
void InferFunctionName ()
bool ShortcutLiteralBinaryExpression (Expression **x, Expression *y, Token::Value op, int pos)
bool ShortcutStringLiteralAppendExpression (Expression **x, Expression *y)
bool CollapseConditionalChain (Expression **x, Expression *cond, Expression *then_expression, Expression *else_expression, int pos, const SourceRange &then_range)
void AppendConditionalChainElse (Expression **x, const SourceRange &else_range)
bool CollapseNaryExpression (Expression **x, Expression *y, Token::Value op, int pos, const SourceRange &range)
Expression * BuildUnaryExpression (Expression *expression, Token::Value op, int pos)
Expression * NewThrowReferenceError (MessageTemplate message, int pos)
void ReportUnidentifiableError ()
const AstRawString * GetRawNameFromIdentifier (const AstRawString *arg)
const AstRawString * PreParserIdentifierToAstRawString (const PreParserIdentifier &arg)
IterationStatement * AsIterationStatement (BreakableStatement *s)
void ReportUnexpectedTokenAt (Scanner::Location location, Token::Value token, MessageTemplate message=MessageTemplate::kUnexpectedToken)
Expression * FailureExpression ()
const AstRawString * EmptyIdentifierString () const
bool IsEmptyIdentifier (const AstRawString *subject) const
const AstRawString * GetSymbol () const
const AstRawString * GetIdentifier () const
const AstRawString * GetNextSymbol () const
const AstRawString * GetNumberAsSymbol () const
const AstRawString * GetBigIntAsSymbol ()
class ThisExpression * ThisExpression ()
class ThisExpression * NewThisExpression (int pos)
Expression * NewSuperPropertyReference (int pos)
SuperCallReference * NewSuperCallReference (int pos)
Expression * NewTargetExpression (int pos)
Expression * ImportMetaExpression (int pos)
Expression * ExpressionFromLiteral (Token::Value token, int pos)
VariableProxy * ExpressionFromPrivateName (PrivateNameScopeIterator *private_name_scope, const AstRawString *name, int start_position)
VariableProxy * ExpressionFromIdentifier (const AstRawString *name, int start_position, InferName infer=InferName::kYes)
void DeclareIdentifier (const AstRawString *name, int start_position)
Variable * DeclareCatchVariableName (Scope *scope, const AstRawString *name)
ZonePtrList< ClassLiteral::Property > * NewClassPropertyList (int size) const
ZonePtrList< ClassLiteral::StaticElement > * NewClassStaticElementList (int size) const
Expression * NewV8Intrinsic (const AstRawString *name, const ScopedPtrList< Expression > &args, int pos)
Expression * NewV8RuntimeFunctionForFuzzing (const Runtime::Function *function, const ScopedPtrList< Expression > &args, int pos)
Statement * NewThrowStatement (Expression *exception, int pos)
void AddFormalParameter (ParserFormalParameters *parameters, Expression *pattern, Expression *initializer, int initializer_end_position, bool is_rest)
void DeclareFormalParameters (ParserFormalParameters *parameters)
void ReindexArrowFunctionFormalParameters (ParserFormalParameters *parameters)
void ReindexComputedMemberName (Expression *computed_name)
void DeclareArrowFunctionFormalParameters (ParserFormalParameters *parameters, Expression *params, const Scanner::Location &params_loc)
Expression * ExpressionListToExpression (const ScopedPtrList< Expression > &args)
void SetFunctionNameFromPropertyName (LiteralProperty *property, const AstRawString *name, const AstRawString *prefix=nullptr)
void SetFunctionNameFromPropertyName (ObjectLiteralProperty *property, const AstRawString *name, const AstRawString *prefix=nullptr)
void SetFunctionNameFromIdentifierRef (Expression *value, Expression *identifier)
void CountUsage (v8::Isolate::UseCounterFeature feature)
bool ParsingDynamicFunctionDeclaration () const
void ConvertBinaryToNaryOperationSourceRange (BinaryOperation *binary_op, NaryOperation *nary_op)
void AppendNaryOperationSourceRange (NaryOperation *node, const SourceRange &range)
void RecordBlockSourceRange (Block *node, int32_t continuation_position)
void RecordCaseClauseSourceRange (CaseClause *node, const SourceRange &body_range)
void AppendConditionalChainSourceRange (ConditionalChain *node, const SourceRange &range)
void AppendConditionalChainElseSourceRange (ConditionalChain *node, const SourceRange &range)
void RecordConditionalSourceRange (Expression *node, const SourceRange &then_range, const SourceRange &else_range)
void RecordFunctionLiteralSourceRange (FunctionLiteral *node)
void RecordBinaryOperationSourceRange (Expression *node, const SourceRange &right_range)
void RecordJumpStatementSourceRange (Statement *node, int32_t continuation_position)
void RecordIfStatementSourceRange (Statement *node, const SourceRange &then_range, const SourceRange &else_range)
void RecordIterationStatementSourceRange (IterationStatement *node, const SourceRange &body_range)
void RecordExpressionSourceRange (Expression *node, const SourceRange &right_range)
void RecordSuspendSourceRange (Expression *node, int32_t continuation_position)
void RecordSwitchStatementSourceRange (Statement *node, int32_t continuation_position)
void RecordThrowSourceRange (Statement *node, int32_t continuation_position)
void RecordTryCatchStatementSourceRange (TryCatchStatement *node, const SourceRange &body_range)
void RecordTryFinallyStatementSourceRange (TryFinallyStatement *node, const SourceRange &body_range)
FunctionLiteral::EagerCompileHint GetEmbedderCompileHint (FunctionLiteral::EagerCompileHint current_compile_hint, int position)
const AstRawString * NextInternalNamespaceExportName ()
ParseInfo * info () const
std::vector< uint8_t > * preparse_data_buffer ()
Static Private Member Functions
static bool IsThisProperty (Expression *expression)
static bool IsPrivateReference (Expression *expression)
static bool IsIdentifier (Expression *expression)
static const AstRawString * AsIdentifier (Expression *expression)
static bool IsBoilerplateProperty (ObjectLiteral::Property *property)
static bool IsArrayIndex (const AstRawString *string, uint32_t *index)
static void CheckAssigningFunctionLiteralToProperty (Expression *left, Expression *right)
static std::nullptr_t NullIdentifier ()
static std::nullptr_t NullExpression ()
static std::nullptr_t NullLiteralProperty ()
static ZonePtrList< Expression > * NullExpressionList ()
static ZonePtrList< Statement > * NullStatementList ()
static std::nullptr_t NullStatement ()
static std::nullptr_t NullBlock ()
template<typename T >
static bool IsNull (T subject)
static bool IsIterationStatement (Statement *subject)
Private Attributes
LocalIsolate * local_isolate_
ParseInfo * info_
Scanner scanner_
Zone preparser_zone_
PreParser * reusable_preparser_
Mode mode_
MaybeHandle< FixedArray > maybe_wrapped_arguments_
SourceRangeMap * source_range_map_ = nullptr
ScriptCompiler::CompileOptions compile_options_
int number_of_named_namespace_exports_ = 0
int use_counts_ [v8::Isolate::kUseCounterFeatureCount]
int total_preparse_skipped_
bool allow_lazy_
bool temp_zoned_
ConsumedPreparseData * consumed_preparse_data_
std::vector< uint8_t > preparse_data_buffer_
int parameters_end_pos_
Friends
class ParserBase< Parser >
struct ParserFormalParameters
class i::ExpressionScope< ParserTypes< Parser > >
class i::VariableDeclarationParsingScope< ParserTypes< Parser > >
class i::ParameterDeclarationParsingScope< ParserTypes< Parser > >
class i::ArrowHeadParsingScope< ParserTypes< Parser > >
class PreParserZoneScope
class PreparseDataBuilder
class ParserTargetScope
bool v8::internal::parsing::ParseProgram (ParseInfo *, DirectHandle< Script >, MaybeDirectHandle< ScopeInfo > maybe_outer_scope_info, Isolate *, parsing::ReportStatisticsMode stats_mode)
bool v8::internal::parsing::ParseFunction (ParseInfo *, DirectHandle< SharedFunctionInfo > shared_info, Isolate *, parsing::ReportStatisticsMode stats_mode)
Detailed Description
Definition at line 132 of file parser.h.
Member Typedef Documentation
TemplateLiteralState
using v8::internal::Parser::TemplateLiteralState = TemplateLiteral* [private]
Definition at line 515 of file parser.h.
Member Enumeration Documentation
CompletionKind
enum v8::internal::Parser::CompletionKind [private]
Enumerator
kNormalCompletion
kThrowCompletion
kAbruptCompletion
Definition at line 213 of file parser.h.
                      {
    kNormalCompletion,
    kThrowCompletion,
    kAbruptCompletion
  };
Mode
enum v8::internal::Parser::Mode [private]
Enumerator
PARSE_LAZILY
PARSE_EAGERLY
Definition at line 197 of file parser.h.
{ PARSE_LAZILY, PARSE_EAGERLY };
Constructor & Destructor Documentation
Parser()
v8::internal::Parser::Parser (LocalIsolate * local_isolate, ParseInfo * info)
Definition at line 595 of file parser.cc.
    : ParserBase<Parser>(
          info->zone(), &scanner_, info->stack_limit(),
          info->ast_value_factory(), info->pending_error_handler(),
          info->runtime_call_stats(), info->v8_file_logger(), info->flags(),
          true, info->flags().compile_hints_magic_enabled(),
          info->flags().compile_hints_per_function_magic_enabled()),
      local_isolate_(local_isolate),
      info_(info),
      scanner_(info->character_stream(), flags()),
      preparser_zone_(info->zone()->allocator(), "pre-parser-zone"),
      reusable_preparser_(nullptr),
      mode_(PARSE_EAGERLY), // Lazy mode must be set explicitly.
      source_range_map_(info->source_range_map()),
      total_preparse_skipped_(0),
      consumed_preparse_data_(info->consumed_preparse_data()),
      preparse_data_buffer_(),
      parameters_end_pos_(info->parameters_end_pos()) {
  // Even though we were passed ParseInfo, we should not store it in
  // Parser - this makes sure that Isolate is not accidentally accessed via
  // ParseInfo during background parsing.
  DCHECK_NOT_NULL(info->character_stream());
  // Determine if functions can be lazily compiled. This is necessary to
  // allow some of our builtin JS files to be lazily compiled. These
  // builtins cannot be handled lazily by the parser, since we have to know
  // if a function uses the special natives syntax, which is something the
  // parser records.
  // If the debugger requests compilation for break points, we cannot be
  // aggressive about lazy compilation, because it might trigger compilation
  // of functions without an outer context when setting a breakpoint through
  // Debug::FindSharedFunctionInfoInScript
  // We also compile eagerly for kProduceExhaustiveCodeCache.
  bool can_compile_lazily = flags().allow_lazy_compile() && !flags().is_eager();
  set_default_eager_compile_hint(can_compile_lazily
                                     ? FunctionLiteral::kShouldLazyCompile
                                     : FunctionLiteral::kShouldEagerCompile);
  allow_lazy_ = flags().allow_lazy_compile() && flags().allow_lazy_parsing() &&
                info->extension() == nullptr && can_compile_lazily;
  for (int feature = 0; feature < v8::Isolate::kUseCounterFeatureCount;
       ++feature) {
    use_counts_[feature] = 0;
  }
}
References allow_lazy_, v8::internal::ParseInfo::character_stream(), DCHECK_NOT_NULL, v8::internal::ParseInfo::extension(), v8::internal::flags, info(), v8::internal::FunctionLiteral::kShouldEagerCompile, v8::internal::FunctionLiteral::kShouldLazyCompile, v8::Isolate::kUseCounterFeatureCount, and use_counts_.
 Parser()
v8::internal::Parser::~Parser () [inline]
Definition at line 135 of file parser.h.
            {
    delete reusable_preparser_;
    reusable_preparser_ = nullptr;
  }
Member Function Documentation
AddArrowFunctionFormalParameters()
void v8::internal::Parser::AddArrowFunctionFormalParameters (ParserFormalParameters * parameters, Expression * params, int end_pos) [private]
Definition at line 2555 of file parser.cc.
                                                                       {
  // ArrowFunctionFormals ::
  // Nary(Token::kComma, VariableProxy*, Tail)
  // Binary(Token::kComma, NonTailArrowFunctionFormals, Tail)
  // Tail
  // NonTailArrowFunctionFormals ::
  // Binary(Token::kComma, NonTailArrowFunctionFormals, VariableProxy)
  // VariableProxy
  // Tail ::
  // VariableProxy
  // Spread(VariableProxy)
  //
  // We need to visit the parameters in left-to-right order
  //
  // For the Nary case, we simply visit the parameters in a loop.
  if (expr->IsNaryOperation()) {
    NaryOperation* nary = expr->AsNaryOperation();
    // The classifier has already run, so we know that the expression is a valid
    // arrow function formals production.
    DCHECK_EQ(nary->op(), Token::kComma);
    // Each op position is the end position of the *previous* expr, with the
    // second (i.e. first "subsequent") op position being the end position of
    // the first child expression.
    Expression* next = nary->first();
    for (size_t i = 0; i < nary->subsequent_length(); ++i) {
      AddArrowFunctionFormalParameters(parameters, next,
                                       nary->subsequent_op_position(i));
      next = nary->subsequent(i);
    }
    AddArrowFunctionFormalParameters(parameters, next, end_pos);
    return;
  }
  // For the binary case, we recurse on the left-hand side of binary comma
  // expressions.
  if (expr->IsBinaryOperation()) {
    BinaryOperation* binop = expr->AsBinaryOperation();
    // The classifier has already run, so we know that the expression is a valid
    // arrow function formals production.
    DCHECK_EQ(binop->op(), Token::kComma);
    Expression* left = binop->left();
    Expression* right = binop->right();
    int comma_pos = binop->position();
    AddArrowFunctionFormalParameters(parameters, left, comma_pos);
    // LHS of comma expression should be unparenthesized.
    expr = right;
  }
  // Only the right-most expression may be a rest parameter.
  DCHECK(!parameters->has_rest);
  bool is_rest = expr->IsSpread();
  if (is_rest) {
    expr = expr->AsSpread()->expression();
    parameters->has_rest = true;
  }
  DCHECK_IMPLIES(parameters->is_simple, !is_rest);
  DCHECK_IMPLIES(parameters->is_simple, expr->IsVariableProxy());
  Expression* initializer = nullptr;
  if (expr->IsAssignment()) {
    Assignment* assignment = expr->AsAssignment();
    DCHECK(!assignment->IsCompoundAssignment());
    initializer = assignment->value();
    expr = assignment->target();
  }
  AddFormalParameter(parameters, expr, initializer, end_pos, is_rest);
}
References AddFormalParameter(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::NaryOperation::first(), v8::internal::FormalParametersBase::has_rest, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::FormalParametersBase::is_simple, v8::internal::BinaryOperation::left(), v8::internal::BinaryOperation::op(), v8::internal::NaryOperation::op(), v8::internal::AstNode::position(), v8::internal::BinaryOperation::right(), v8::internal::NaryOperation::subsequent(), v8::internal::NaryOperation::subsequent_length(), v8::internal::NaryOperation::subsequent_op_position(), v8::internal::Assignment::target(), and v8::internal::Assignment::value().
Referenced by DeclareArrowFunctionFormalParameters().
AddClassStaticBlock()
void v8::internal::Parser::AddClassStaticBlock (Block * block, ClassInfo * class_info) [private]
Definition at line 3266 of file parser.cc.
                                                                    {
  DCHECK(class_info->has_static_elements());
  class_info->static_elements->Add(
      factory()->NewClassLiteralStaticElement(block), zone());
}
References v8::internal::DCHECK().
AddFormalParameter()
void v8::internal::Parser::AddFormalParameter (ParserFormalParameters * parameters, Expression * pattern, Expression * initializer, int initializer_end_position, bool is_rest) [inline], [private]
Definition at line 869 of file parser.h.
                                                  {
    parameters->UpdateArityAndFunctionLength(initializer != nullptr, is_rest);
    auto parameter =
        parameters->scope->zone()->New<ParserFormalParameters::Parameter>(
            pattern, initializer, scanner()->location().beg_pos,
            initializer_end_position, is_rest);
    parameters->params.Add(parameter);
  }
References v8::internal::Zone::New(), v8::internal::ParserFormalParameters::params, v8::internal::FormalParametersBase::scope, v8::internal::FormalParametersBase::UpdateArityAndFunctionLength(), and v8::internal::Scope::zone().
Referenced by AddArrowFunctionFormalParameters(), and ParseFunction().
AddFunctionForNameInference()
void v8::internal::Parser::AddFunctionForNameInference (FunctionLiteral * func_to_infer) [inline], [private]
Definition at line 670 of file parser.h.
                                                                             {
    fni_.AddFunction(func_to_infer);
  }
Referenced by RewriteClassLiteral().
AddInstanceFieldOrStaticElement()
void v8::internal::Parser::AddInstanceFieldOrStaticElement (ClassLiteralProperty * property, ClassInfo * class_info, bool is_static) [private]
Definition at line 3186 of file parser.cc.
                                                             {
  if (is_static) {
    class_info->static_elements->Add(
        factory()->NewClassLiteralStaticElement(property), zone());
    return;
  }
  class_info->instance_fields->Add(property, zone());
}
Referenced by DeclarePrivateClassMember(), and DeclarePublicClassField().
AddTemplateExpression()
void v8::internal::Parser::AddTemplateExpression (TemplateLiteralState * state, Expression * expression) [private]
Definition at line 3572 of file parser.cc.
                                                           {
  (*state)->AddExpression(expression, zone());
}
AddTemplateSpan()
void v8::internal::Parser::AddTemplateSpan (TemplateLiteralState * state, bool should_cook, bool tail) [private]
Definition at line 3560 of file parser.cc.
                                        {
  int end = scanner()->location().end_pos - (tail ? 1 : 2);
  const AstRawString* raw = scanner()->CurrentRawSymbol(ast_value_factory());
  if (should_cook) {
    const AstRawString* cooked = scanner()->CurrentSymbol(ast_value_factory());
    (*state)->AddTemplateSpan(cooked, raw, end, zone());
  } else {
    (*state)->AddTemplateSpan(nullptr, raw, end, zone());
  }
}
References v8::internal::compiler::end().
AllowsLazyParsingWithoutUnresolvedVariables()
bool v8::internal::Parser::AllowsLazyParsingWithoutUnresolvedVariables () const [inline], [private]
Definition at line 190 of file parser.h.
                                                           {
    return !MaybeParsingArrowhead() &&
           scope()->AllowsLazyParsingWithoutUnresolvedVariables(
               original_scope_);
  }
Referenced by ParseFunctionLiteral().
AppendConditionalChainElse()
void v8::internal::Parser::AppendConditionalChainElse (Expression ** x, const SourceRange & else_range) [private]
Definition at line 365 of file parser.cc.
                                                                       {
  if (*x && (*x)->IsConditionalChain()) {
    ConditionalChain* conditional_chain = (*x)->AsConditionalChain();
    AppendConditionalChainElseSourceRange(conditional_chain, else_range);
  }
}
References AppendConditionalChainElseSourceRange().
AppendConditionalChainElseSourceRange()
void v8::internal::Parser::AppendConditionalChainElseSourceRange (ConditionalChain * node, const SourceRange & range) [inline], [private]
Definition at line 986 of file parser.h.
                                                        {
    if (source_range_map_ == nullptr) return;
    ConditionalChainSourceRanges* ranges =
        static_cast<ConditionalChainSourceRanges*>(
            source_range_map_->Find(node));
    if (ranges == nullptr) return;
    ranges->AddElseRange(range);
  }
References v8::internal::ConditionalChainSourceRanges::AddElseRange().
Referenced by AppendConditionalChainElse().
AppendConditionalChainSourceRange()
void v8::internal::Parser::AppendConditionalChainSourceRange (ConditionalChain * node, const SourceRange & range) [inline], [private]
Definition at line 969 of file parser.h.
                                                                             {
    if (source_range_map_ == nullptr) return;
    ConditionalChainSourceRanges* ranges =
        static_cast<ConditionalChainSourceRanges*>(
            source_range_map_->Find(node));
    if (ranges == nullptr) {
      source_range_map_->Insert(
          node, zone()->New<ConditionalChainSourceRanges>(zone()));
    }
    ranges = static_cast<ConditionalChainSourceRanges*>(
        source_range_map_->Find(node));
    if (ranges == nullptr) return;
    ranges->AddThenRanges(range);
    DCHECK_EQ(node->conditional_chain_length(), ranges->RangeCount());
  }
References v8::internal::ConditionalChainSourceRanges::AddThenRanges(), v8::internal::ConditionalChain::conditional_chain_length(), DCHECK_EQ, and v8::internal::ConditionalChainSourceRanges::RangeCount().
Referenced by CollapseConditionalChain().
AppendNaryOperationSourceRange()
void v8::internal::Parser::AppendNaryOperationSourceRange (NaryOperation * node, const SourceRange & range) [inline], [private]
Definition at line 944 of file parser.h.
                                                                          {
    if (source_range_map_ == nullptr) return;
    NaryOperationSourceRanges* ranges =
        static_cast<NaryOperationSourceRanges*>(source_range_map_->Find(node));
    if (ranges == nullptr) return;
    ranges->AddRange(range);
    DCHECK_EQ(node->subsequent_length(), ranges->RangeCount());
  }
References v8::internal::NaryOperationSourceRanges::AddRange(), DCHECK_EQ, v8::internal::NaryOperationSourceRanges::RangeCount(), and v8::internal::NaryOperation::subsequent_length().
Referenced by CollapseNaryExpression().
AsIdentifier()
static const AstRawString* v8::internal::Parser::AsIdentifier (Expression * expression) [inline], [static], [private]
Definition at line 596 of file parser.h.
                                                                            {
    DCHECK(IsIdentifier(expression));
    return expression->AsVariableProxy()->raw_name();
  }
References v8::internal::DCHECK().
AsIdentifierExpression()
VariableProxy* v8::internal::Parser::AsIdentifierExpression (Expression * expression) [inline], [private]
Definition at line 601 of file parser.h.
                                                                          {
    return expression->AsVariableProxy();
  }
AsIterationStatement()
IterationStatement* v8::internal::Parser::AsIterationStatement (BreakableStatement * s) [inline], [private]
Definition at line 739 of file parser.h.
                                                                  {
    return s->AsIterationStatement();
  }
References v8::internal::AstNode::AsIterationStatement().
BuildCreateJSGeneratorObject()
Assignment* v8::internal::Parser::BuildCreateJSGeneratorObject (int pos, FunctionKind kind) [private]
BuildInitializationBlock()
Statement * v8::internal::Parser::BuildInitializationBlock (DeclarationParsingResult * parsing_result) [private]
Definition at line 1995 of file parser.cc.
                                              {
  ScopedPtrList<Statement> statements(pointer_buffer());
  for (const auto& declaration : parsing_result->declarations) {
    if (!declaration.initializer) continue;
    InitializeVariables(&statements, parsing_result->descriptor.kind,
                        &declaration);
  }
  return factory()->NewBlock(true, statements);
}
References InitializeVariables().
BuildInitialYield()
Expression * v8::internal::Parser::BuildInitialYield (int pos, FunctionKind kind) [private]
Definition at line 3042 of file parser.cc.
                                                                {
  Expression* yield_result = factory()->NewVariableProxy(
      function_state_->scope()->generator_object_var());
  // The position of the yield is important for reporting the exception
  // caused by calling the .throw method on a generator suspended at the
  // initial yield (i.e. right after generator instantiation).
  function_state_->AddSuspend();
  return factory()->NewYield(yield_result, scope()->start_position(),
                             Suspend::kOnExceptionThrow);
}
References v8::internal::Suspend::kOnExceptionThrow.
Referenced by DoParseProgram(), ParseAsyncGeneratorFunctionBody(), and ParseGeneratorFunctionBody().
BuildParameterInitializationBlock()
Block * v8::internal::Parser::BuildParameterInitializationBlock (const ParserFormalParameters & parameters) [private]
Definition at line 3010 of file parser.cc.
                                              {
  DCHECK(!parameters.is_simple);
  DCHECK(scope()->is_function_scope());
  DCHECK_EQ(scope(), parameters.scope);
  ScopedPtrList<Statement> init_statements(pointer_buffer());
  int index = 0;
  for (auto parameter : parameters.params) {
    Expression* initial_value =
        factory()->NewVariableProxy(parameters.scope->parameter(index));
    if (parameter->initializer() != nullptr) {
      // IS_UNDEFINED($param) ? initializer : $param
      auto condition = factory()->NewCompareOperation(
          Token::kEqStrict,
          factory()->NewVariableProxy(parameters.scope->parameter(index)),
          factory()->NewUndefinedLiteral(kNoSourcePosition), kNoSourcePosition);
      initial_value =
          factory()->NewConditional(condition, parameter->initializer(),
                                    initial_value, kNoSourcePosition);
    }
    BlockState block_state(&scope_, scope()->AsDeclarationScope());
    DeclarationParsingResult::Declaration decl(parameter->pattern,
                                               initial_value);
    InitializeVariables(&init_statements, PARAMETER_VARIABLE, &decl);
    ++index;
  }
  return factory()->NewParameterInitializationBlock(init_statements);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::index, InitializeVariables(), v8::internal::FormalParametersBase::is_simple, v8::internal::kNoSourcePosition, v8::internal::DeclarationScope::parameter(), v8::internal::PARAMETER_VARIABLE, v8::internal::ParserFormalParameters::params, and v8::internal::FormalParametersBase::scope.
BuildUnaryExpression()
Expression * v8::internal::Parser::BuildUnaryExpression (Expression * expression, Token::Value op, int pos) [private]
Definition at line 426 of file parser.cc.
                                                                 {
  DCHECK_NOT_NULL(expression);
  const Literal* literal = expression->AsLiteral();
  if (literal != nullptr) {
    if (op == Token::kNot) {
      // Convert the literal to a boolean condition and negate it.
      return factory()->NewBooleanLiteral(literal->ToBooleanIsFalse(), pos);
    } else if (literal->IsNumberLiteral()) {
      // Compute some expressions involving only number literals.
      double value = literal->AsNumber();
      switch (op) {
        case Token::kAdd:
          return expression;
        case Token::kSub:
          return factory()->NewNumberLiteral(-value, pos);
        case Token::kBitNot:
          return factory()->NewNumberLiteral(~DoubleToInt32(value), pos);
        default:
          break;
      }
    }
  }
  return factory()->NewUnaryOperation(op, expression, pos);
}
References v8::internal::Literal::AsNumber(), DCHECK_NOT_NULL, v8::internal::DoubleToInt32(), v8::internal::Expression::IsNumberLiteral(), v8::internal::Literal::ToBooleanIsFalse(), and v8::internal::value.
CheckAssigningFunctionLiteralToProperty()
static void v8::internal::Parser::CheckAssigningFunctionLiteralToProperty (Expression * left, Expression * right) [inline], [static], [private]
Definition at line 678 of file parser.h.
                                           {
    DCHECK_NOT_NULL(left);
    if (left->IsProperty() && right->IsFunctionLiteral()) {
      right->AsFunctionLiteral()->set_pretenure();
    }
  }
References DCHECK_NOT_NULL.
CloseTemplateLiteral()
Expression * v8::internal::Parser::CloseTemplateLiteral (TemplateLiteralState * state, int start, Expression * tag) [private]
Definition at line 3577 of file parser.cc.
                                                          {
  TemplateLiteral* lit = *state;
  int pos = lit->position();
  const ZonePtrList<const AstRawString>* cooked_strings = lit->cooked();
  const ZonePtrList<const AstRawString>* raw_strings = lit->raw();
  const ZonePtrList<Expression>* expressions = lit->expressions();
  DCHECK_EQ(cooked_strings->length(), raw_strings->length());
  DCHECK_EQ(cooked_strings->length(), expressions->length() + 1);
  if (!tag) {
    if (cooked_strings->length() == 1) {
      return factory()->NewStringLiteral(cooked_strings->first(), pos);
    }
    return factory()->NewTemplateLiteral(cooked_strings, expressions, pos);
  } else {
    // GetTemplateObject
    Expression* template_object =
        factory()->NewGetTemplateObject(cooked_strings, raw_strings, pos);
    // Call TagFn
    ScopedPtrList<Expression> call_args(pointer_buffer());
    call_args.Add(template_object);
    call_args.AddAll(expressions->ToConstVector());
    return factory()->NewTaggedTemplate(tag, call_args, pos);
  }
}
References v8::internal::ScopedList< T, TBacking >::Add(), v8::internal::ScopedList< T, TBacking >::AddAll(), v8::internal::Parser::TemplateLiteral::cooked(), DCHECK_EQ, v8::internal::Parser::TemplateLiteral::expressions(), v8::internal::ZoneList< T >::first(), v8::internal::ZoneList< T >::length(), v8::internal::Parser::TemplateLiteral::position(), v8::internal::Parser::TemplateLiteral::raw(), and v8::internal::ZoneList< T >::ToConstVector().
CollapseConditionalChain()
bool v8::internal::Parser::CollapseConditionalChain (Expression ** x, Expression * cond, Expression * then_expression, Expression * else_expression, int pos, const SourceRange & then_range) [private]
Definition at line 346 of file parser.cc.
                                                                     {
  if (*x && (*x)->IsConditionalChain()) {
    ConditionalChain* conditional_chain = (*x)->AsConditionalChain();
    if (then_expression != nullptr) {
      conditional_chain->AddChainEntry(cond, then_expression, pos);
      AppendConditionalChainSourceRange(conditional_chain, then_range);
    }
    if (else_expression != nullptr) {
      conditional_chain->set_else_expression(else_expression);
      DCHECK_GT(conditional_chain->conditional_chain_length(), 1);
    }
    return true;
  }
  return false;
}
References v8::internal::ConditionalChain::AddChainEntry(), AppendConditionalChainSourceRange(), v8::internal::ConditionalChain::conditional_chain_length(), DCHECK_GT, and v8::internal::ConditionalChain::set_else_expression().
CollapseNaryExpression()
bool v8::internal::Parser::CollapseNaryExpression (Expression ** x, Expression * y, Token::Value op, int pos, const SourceRange & range) [private]
Definition at line 373 of file parser.cc.
                                                              {
  // Filter out unsupported ops.
  if (!Token::IsBinaryOp(op) || op == Token::kExp) return false;
  // Convert *x into an nary operation with the given op, returning false if
  // this is not possible.
  NaryOperation* nary = nullptr;
  if ((*x)->IsBinaryOperation()) {
    BinaryOperation* binop = (*x)->AsBinaryOperation();
    if (binop->op() != op) return false;
    nary = factory()->NewNaryOperation(op, binop->left(), 2);
    nary->AddSubsequent(binop->right(), binop->position());
    ConvertBinaryToNaryOperationSourceRange(binop, nary);
    *x = nary;
  } else if ((*x)->IsNaryOperation()) {
    nary = (*x)->AsNaryOperation();
    if (nary->op() != op) return false;
  } else {
    return false;
  }
  Expression* last = nary->last();
  // Try to shortcut sequential string literal appends:
  // expr + "abc" + "def" -> expr + "abcdef"
  // Folding on the LHS of expr is handled by the more general
  // ShortcutLiteralBinaryExpression, this is a special case for RHS string
  // literal concatenation since this is commutative.
  if (op == Token::kAdd && ShortcutStringLiteralAppendExpression(&last, y)) {
    // Append our current expression to the nary operation.
    nary->UpdateLast(last);
  } else {
    // Otherwise append our current expression to the nary operation.
    nary->AddSubsequent(y, pos);
  }
  nary->clear_parenthesized();
  AppendNaryOperationSourceRange(nary, range);
  return true;
}
References v8::internal::NaryOperation::AddSubsequent(), AppendNaryOperationSourceRange(), v8::internal::Expression::clear_parenthesized(), ConvertBinaryToNaryOperationSourceRange(), v8::internal::Token::IsBinaryOp(), v8::internal::NaryOperation::last(), v8::internal::BinaryOperation::left(), v8::internal::BinaryOperation::op(), v8::internal::NaryOperation::op(), v8::internal::AstNode::position(), v8::internal::BinaryOperation::right(), ShortcutStringLiteralAppendExpression(), v8::internal::NaryOperation::UpdateLast(), and v8::internal::y.
ConvertBinaryToNaryOperationSourceRange()
void v8::internal::Parser::ConvertBinaryToNaryOperationSourceRange (BinaryOperation * binary_op, NaryOperation * nary_op) [inline], [private]
Definition at line 929 of file parser.h.
                                                          {
    if (source_range_map_ == nullptr) return;
    DCHECK_NULL(source_range_map_->Find(nary_op));
    BinaryOperationSourceRanges* ranges =
        static_cast<BinaryOperationSourceRanges*>(
            source_range_map_->Find(binary_op));
    if (ranges == nullptr) return;
    SourceRange range = ranges->GetRange(SourceRangeKind::kRight);
    source_range_map_->Insert(
        nary_op, zone()->New<NaryOperationSourceRanges>(zone(), range));
  }
References DCHECK_NULL, v8::internal::BinaryOperationSourceRanges::GetRange(), and v8::internal::kRight.
Referenced by CollapseNaryExpression().
CountUsage()
void v8::internal::Parser::CountUsage (v8::Isolate::UseCounterFeature feature) [inline], [private]
Definition at line 919 of file parser.h.
                                                                {
    ++use_counts_[feature];
  }
CreateForEachStatementTDZ()
Block * v8::internal::Parser::CreateForEachStatementTDZ (Block * init_block, const ForInfo & for_info) [private]
Definition at line 2288 of file parser.cc.
                                                                  {
  if (IsLexicalVariableMode(for_info.parsing_result.descriptor.mode)) {
    DCHECK_NULL(init_block);
    init_block = factory()->NewBlock(1, false);
    for (const AstRawString* bound_name : for_info.bound_names) {
      // TODO(adamk): This needs to be some sort of special
      // INTERNAL variable that's invisible to the debugger
      // but visible to everything else.
      VariableProxy* tdz_proxy = DeclareBoundVariable(
          bound_name, VariableMode::kLet, kNoSourcePosition);
      tdz_proxy->var()->set_initializer_position(position());
    }
  }
  return init_block;
}
References DCHECK_NULL, DeclareBoundVariable(), v8::internal::IsLexicalVariableMode(), v8::internal::kLet, v8::internal::kNoSourcePosition, v8::internal::Variable::set_initializer_position(), and v8::internal::VariableProxy::var().
CreateInitializerFunction()
FunctionLiteral * v8::internal::Parser::CreateInitializerFunction (const AstRawString * class_name, DeclarationScope * scope, int function_literal_id, Statement * initializer_stmt) [private]
Definition at line 3272 of file parser.cc.
                                                          {
  DCHECK(IsClassMembersInitializerFunction(scope->function_kind()));
  // function() { .. class fields initializer .. }
  ScopedPtrList<Statement> statements(pointer_buffer());
  statements.Add(initializer_stmt);
  FunctionLiteral* result = factory()->NewFunctionLiteral(
      class_name, scope, statements, 0, 0, 0,
      FunctionLiteral::kNoDuplicateParameters,
      FunctionSyntaxKind::kAccessorOrMethod,
      FunctionLiteral::kShouldEagerCompile, scope->start_position(), false,
      function_literal_id);
#ifdef DEBUG
  scope->SetScopeName(class_name);
#endif
  RecordFunctionLiteralSourceRange(result);
  return result;
}
References v8::internal::ScopedList< T, TBacking >::Add(), v8::internal::DCHECK(), v8::internal::DeclarationScope::function_kind(), v8::internal::function_literal_id, v8::internal::IsClassMembersInitializerFunction(), v8::internal::kAccessorOrMethod, v8::internal::FunctionLiteral::kNoDuplicateParameters, v8::internal::FunctionLiteral::kShouldEagerCompile, RecordFunctionLiteralSourceRange(), v8::base::internal::result, and v8::internal::Scope::start_position().
Referenced by CreateInstanceMembersInitializer(), and CreateStaticElementsInitializer().
CreateInstanceMembersInitializer()
FunctionLiteral * v8::internal::Parser::CreateInstanceMembersInitializer (const AstRawString * name, ClassInfo * class_info) [private]
Definition at line 3302 of file parser.cc.
                                                     {
  return CreateInitializerFunction(
      name, class_info->instance_members_scope,
      class_info->instance_members_function_id,
      factory()->NewInitializeClassMembersStatement(class_info->instance_fields,
                                                    kNoSourcePosition));
}
References CreateInitializerFunction(), v8::internal::kNoSourcePosition, and v8::internal::name.
Referenced by ParseClassForMemberInitialization(), and RewriteClassLiteral().
CreatePrivateNameVariable()
VariableProxy * v8::internal::Parser::CreatePrivateNameVariable (ClassScope * scope, VariableMode mode, IsStaticFlag is_static_flag, const AstRawString * name) [private]
Definition at line 3168 of file parser.cc.
                                                                           {
  DCHECK_NOT_NULL(name);
  int begin = position();
  int end = end_position();
  bool was_added = false;
  DCHECK(IsImmutableLexicalOrPrivateVariableMode(mode));
  Variable* var =
      scope->DeclarePrivateName(name, mode, is_static_flag, &was_added);
  if (!was_added) {
    Scanner::Location loc(begin, end);
    ReportMessageAt(loc, MessageTemplate::kVarRedeclaration, var->raw_name());
  }
  return factory()->NewVariableProxy(var, begin);
}
References v8::internal::compiler::begin(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::ClassScope::DeclarePrivateName(), v8::internal::compiler::end(), v8::internal::IsImmutableLexicalOrPrivateVariableMode(), v8::internal::loc, mode(), v8::internal::name, and v8::internal::Variable::raw_name().
Referenced by DeclarePrivateClassMember().
CreateStaticElementsInitializer()
FunctionLiteral * v8::internal::Parser::CreateStaticElementsInitializer (const AstRawString * name, ClassInfo * class_info) [private]
Definition at line 3293 of file parser.cc.
                                                     {
  return CreateInitializerFunction(
      name, class_info->static_elements_scope,
      class_info->static_elements_function_id,
      factory()->NewInitializeClassStaticElementsStatement(
          class_info->static_elements, kNoSourcePosition));
}
References CreateInitializerFunction(), v8::internal::kNoSourcePosition, and v8::internal::name.
Referenced by ParseClassForMemberInitialization(), and RewriteClassLiteral().
CreateSyntheticContextVariableProxy()
VariableProxy * v8::internal::Parser::CreateSyntheticContextVariableProxy (ClassScope * scope, ClassInfo * class_info, const AstRawString * name, bool is_static) [private]
Definition at line 3152 of file parser.cc.
                    {
  if (scope->is_reparsed()) {
    DeclarationScope* declaration_scope =
        is_static ? class_info->static_elements_scope
                  : class_info->instance_members_scope;
    return declaration_scope->NewUnresolved(factory()->ast_node_factory(), name,
                                            position());
  }
  VariableProxy* proxy =
      DeclareBoundVariable(name, VariableMode::kConst, kNoSourcePosition);
  proxy->var()->ForceContextAllocation();
  return proxy;
}
References DeclareBoundVariable(), v8::internal::Variable::ForceContextAllocation(), v8::internal::Scope::is_reparsed(), v8::internal::kConst, v8::internal::kNoSourcePosition, v8::internal::name, v8::internal::Scope::NewUnresolved(), and v8::internal::VariableProxy::var().
Referenced by DeclarePublicClassField(), and NewAutoAccessorInfo().
Declare()
void v8::internal::Parser::Declare (Declaration * declaration, const AstRawString * name, VariableKind kind, VariableMode mode, InitializationFlag init, Scope * declaration_scope, bool * was_added, int var_begin_pos, int var_end_pos = kNoSourcePosition) [private]
Definition at line 1968 of file parser.cc.
                                                         {
  bool local_ok = true;
  bool sloppy_mode_block_scope_function_redefinition = false;
  scope->DeclareVariable(
      declaration, name, var_begin_pos, mode, variable_kind, init, was_added,
      &sloppy_mode_block_scope_function_redefinition, &local_ok);
  if (!local_ok) {
    // If we only have the start position of a proxy, we can't highlight the
    // whole variable name. Pretend its length is 1 so that we highlight at
    // least the first character.
    Scanner::Location loc(var_begin_pos, var_end_pos != kNoSourcePosition
                                             ? var_end_pos
                                             : var_begin_pos + 1);
    if (variable_kind == PARAMETER_VARIABLE) {
      ReportMessageAt(loc, MessageTemplate::kParamDupe);
    } else {
      ReportMessageAt(loc, MessageTemplate::kVarRedeclaration,
                      declaration->var()->raw_name());
    }
  } else if (sloppy_mode_block_scope_function_redefinition) {
    ++use_counts_[v8::Isolate::kSloppyModeBlockScopedFunctionRedefinition];
  }
}
References v8::internal::Scope::DeclareVariable(), v8::internal::kNoSourcePosition, v8::Isolate::kSloppyModeBlockScopedFunctionRedefinition, v8::internal::loc, mode(), v8::internal::name, v8::internal::PARAMETER_VARIABLE, v8::internal::Variable::raw_name(), use_counts_, and v8::internal::Declaration::var().
Referenced by DeclareFunction(), and DeclareVariable().
DeclareAndBindVariable()
void v8::internal::Parser::DeclareAndBindVariable (VariableProxy * proxy, VariableKind kind, VariableMode mode, Scope * declaration_scope, bool * was_added, int initializer_position) [private]
Definition at line 1943 of file parser.cc.
                                                                               {
  Variable* var = DeclareVariable(
      proxy->raw_name(), kind, mode, Variable::DefaultInitializationFlag(mode),
      scope, was_added, proxy->position(), kNoSourcePosition);
  var->set_initializer_position(initializer_position);
  proxy->BindTo(var);
}
References v8::internal::VariableProxy::BindTo(), DeclareVariable(), v8::internal::Variable::DefaultInitializationFlag(), v8::internal::kNoSourcePosition, mode(), v8::internal::AstNode::position(), v8::internal::VariableProxy::raw_name(), and v8::internal::Variable::set_initializer_position().
DeclareArrowFunctionFormalParameters()
void v8::internal::Parser::DeclareArrowFunctionFormalParameters (ParserFormalParameters * parameters, Expression * params, const Scanner::Location & params_loc) [private]
Definition at line 2627 of file parser.cc.
                                       {
  if (expr->IsEmptyParentheses() || has_error()) return;
  AddArrowFunctionFormalParameters(parameters, expr, params_loc.end_pos);
  if (parameters->arity + 1 /* receiver */ > Code::kMaxArguments) {
    ReportMessageAt(params_loc, MessageTemplate::kMalformedArrowFunParamList);
    return;
  }
  DeclareFormalParameters(parameters);
  DCHECK_IMPLIES(parameters->is_simple,
                 parameters->scope->has_simple_parameters());
}
References AddArrowFunctionFormalParameters(), v8::internal::FormalParametersBase::arity, DCHECK_IMPLIES, DeclareFormalParameters(), v8::internal::Scanner::Location::end_pos, v8::internal::DeclarationScope::has_simple_parameters(), v8::internal::FormalParametersBase::is_simple, v8::internal::Code::kMaxArguments, and v8::internal::FormalParametersBase::scope.
DeclareBoundVariable()
VariableProxy * v8::internal::Parser::DeclareBoundVariable (const AstRawString * name, VariableMode mode, int pos) [private]
Definition at line 1930 of file parser.cc.
                                                                        {
  DCHECK_NOT_NULL(name);
  VariableProxy* proxy =
      factory()->NewVariableProxy(name, NORMAL_VARIABLE, position());
  bool was_added;
  Variable* var = DeclareVariable(name, NORMAL_VARIABLE, mode,
                                  Variable::DefaultInitializationFlag(mode),
                                  scope(), &was_added, pos, end_position());
  proxy->BindTo(var);
  return proxy;
}
References v8::internal::VariableProxy::BindTo(), DCHECK_NOT_NULL, DeclareVariable(), v8::internal::Variable::DefaultInitializationFlag(), mode(), v8::internal::name, and v8::internal::NORMAL_VARIABLE.
Referenced by CreateForEachStatementTDZ(), CreateSyntheticContextVariableProxy(), DeclareClass(), DeclareNative(), DesugarLexicalBindingsInForStatement(), and ParseExportDefault().
DeclareCatchVariableName()
Variable* v8::internal::Parser::DeclareCatchVariableName (Scope * scope, const AstRawString * name) [inline], [private]
Definition at line 843 of file parser.h.
                                                                         {
    return scope->DeclareCatchVariableName(name);
  }
References v8::internal::Scope::DeclareCatchVariableName(), and v8::internal::name.
DeclareClass()
Statement * v8::internal::Parser::DeclareClass (const AstRawString * variable_name, Expression * value, ZonePtrList< const AstRawString > * names, int class_token_pos, int end_pos) [private]
Definition at line 2033 of file parser.cc.
                                                                  {
  VariableProxy* proxy =
      DeclareBoundVariable(variable_name, VariableMode::kLet, class_token_pos);
  proxy->var()->set_initializer_position(end_pos);
  if (names) names->Add(variable_name, zone());
  Assignment* assignment =
      factory()->NewAssignment(Token::kInit, proxy, value, class_token_pos);
  return IgnoreCompletion(
      factory()->NewExpressionStatement(assignment, kNoSourcePosition));
}
References v8::internal::ZoneList< T >::Add(), DeclareBoundVariable(), IgnoreCompletion(), v8::internal::kLet, v8::internal::kNoSourcePosition, v8::internal::Variable::set_initializer_position(), v8::internal::value, and v8::internal::VariableProxy::var().
DeclareClassBrandVariable()
void v8::internal::Parser::DeclareClassBrandVariable (ClassScope * scope, ClassInfo * class_info, int class_token_pos) [private]
DeclareClassField()
void v8::internal::Parser::DeclareClassField (ClassScope * scope, ClassLiteralProperty * property, const AstRawString * property_name, bool is_static, bool is_computed_name, bool is_private, ClassInfo * class_info) [private]
DeclareClassProperty()
void v8::internal::Parser::DeclareClassProperty (ClassScope * scope, const AstRawString * class_name, ClassLiteralProperty * property, bool is_constructor, ClassInfo * class_info) [private]
DeclareClassVariable()
void v8::internal::Parser::DeclareClassVariable (ClassScope * scope, const AstRawString * name, ClassInfo * class_info, int class_token_pos) [private]
Definition at line 3136 of file parser.cc.
                                                                              {
#ifdef DEBUG
  scope->SetScopeName(name);
#endif
  DCHECK_IMPLIES(IsEmptyIdentifier(name), class_info->is_anonymous);
  // Declare a special class variable for anonymous classes with the dot
  // if we need to save it for static private method access.
  Variable* class_variable =
      scope->DeclareClassVariable(ast_value_factory(), name, class_token_pos);
  Declaration* declaration = factory()->NewVariableDeclaration(class_token_pos);
  scope->declarations()->Add(declaration);
  declaration->set_var(class_variable);
}
References DCHECK_IMPLIES, v8::internal::Scope::declarations(), v8::internal::ClassScope::DeclareClassVariable(), IsEmptyIdentifier(), v8::internal::name, and v8::internal::Declaration::set_var().
DeclareFormalParameters()
void v8::internal::Parser::DeclareFormalParameters (ParserFormalParameters * parameters) [inline], [private]
Definition at line 883 of file parser.h.
                                                                             {
    bool is_simple = parameters->is_simple;
    DeclarationScope* scope = parameters->scope;
    if (!is_simple) scope->MakeParametersNonSimple();
    for (auto parameter : parameters->params) {
      bool is_optional = parameter->initializer() != nullptr;
      // If the parameter list is simple, declare the parameters normally with
      // their names. If the parameter list is not simple, declare a temporary
      // for each parameter - the corresponding named variable is declared by
      // BuildParameterInitializationBlock.
      scope->DeclareParameter(
          is_simple ? parameter->name() : ast_value_factory()->empty_string(),
          is_simple ? VariableMode::kVar : VariableMode::kTemporary,
          is_optional, parameter->is_rest(), ast_value_factory(),
          parameter->position);
    }
  }
References v8::internal::DeclarationScope::DeclareParameter(), v8::internal::FormalParametersBase::is_simple, v8::internal::kTemporary, v8::internal::kVar, v8::internal::DeclarationScope::MakeParametersNonSimple(), v8::internal::ParserFormalParameters::params, and v8::internal::FormalParametersBase::scope.
Referenced by DeclareArrowFunctionFormalParameters(), DoParseFunction(), and ParseFunction().
DeclareFunction()
Statement * v8::internal::Parser::DeclareFunction (const AstRawString * variable_name, FunctionLiteral * function, VariableMode mode, VariableKind kind, int beg_pos, int end_pos, ZonePtrList< const AstRawString > * names) [private]
Definition at line 2006 of file parser.cc.
                                                                           {
  Declaration* declaration =
      factory()->NewFunctionDeclaration(function, beg_pos);
  bool was_added;
  Declare(declaration, variable_name, kind, mode, kCreatedInitialized, scope(),
          &was_added, beg_pos);
  if (info()->flags().coverage_enabled()) {
    // Force the function to be allocated when collecting source coverage, so
    // that even dead functions get source coverage data.
    declaration->var()->set_is_used();
  }
  if (names) names->Add(variable_name, zone());
  if (kind == SLOPPY_BLOCK_FUNCTION_VARIABLE) {
    Token::Value init =
        loop_nesting_depth() > 0 ? Token::kAssign : Token::kInit;
    SloppyBlockFunctionStatement* statement =
        factory()->NewSloppyBlockFunctionStatement(end_pos, declaration->var(),
                                                   init);
    GetDeclarationScope()->DeclareSloppyBlockFunction(statement);
    return statement;
  }
  return factory()->EmptyStatement();
}
References v8::internal::ZoneList< T >::Add(), Declare(), v8::internal::flags, info(), v8::internal::kCreatedInitialized, mode(), v8::internal::Variable::set_is_used(), v8::internal::SLOPPY_BLOCK_FUNCTION_VARIABLE, and v8::internal::Declaration::var().
DeclareFunctionNameVar()
void v8::internal::Parser::DeclareFunctionNameVar (const AstRawString * function_name, FunctionSyntaxKind function_syntax_kind, DeclarationScope * function_scope) [private]
Definition at line 2208 of file parser.cc.
                                                                      {
  if (function_syntax_kind == FunctionSyntaxKind::kNamedExpression &&
      function_scope->LookupLocal(function_name) == nullptr) {
    DCHECK_EQ(function_scope, scope());
    function_scope->DeclareFunctionVar(function_name);
  }
}
References DCHECK_EQ, v8::internal::DeclarationScope::DeclareFunctionVar(), v8::internal::kNamedExpression, and v8::internal::Scope::LookupLocal().
DeclareIdentifier()
void v8::internal::Parser::DeclareIdentifier (const AstRawString * name, int start_position) [inline], [private]
Definition at line 838 of file parser.h.
                                                       {
    expression_scope()->Declare(name, start_position);
  }
References v8::internal::name.
DeclareNative()
Statement * v8::internal::Parser::DeclareNative (const AstRawString * name, int pos) [private]
Definition at line 2048 of file parser.cc.
                                                                  {
  // Make sure that the function containing the native declaration
  // isn't lazily compiled. The extension structures are only
  // accessible while parsing the first time not when reparsing
  // because of lazy compilation.
  GetClosureScope()->ForceEagerCompilation();
  // TODO(1240846): It's weird that native function declarations are
  // introduced dynamically when we meet their declarations, whereas
  // other functions are set up when entering the surrounding scope.
  VariableProxy* proxy = DeclareBoundVariable(name, VariableMode::kVar, pos);
  NativeFunctionLiteral* lit =
      factory()->NewNativeFunctionLiteral(name, extension(), kNoSourcePosition);
  return factory()->NewExpressionStatement(
      factory()->NewAssignment(Token::kInit, proxy, lit, kNoSourcePosition),
      pos);
}
References DeclareBoundVariable(), extension(), v8::internal::kNoSourcePosition, v8::internal::kVar, and v8::internal::name.
DeclarePrivateClassMember()
void v8::internal::Parser::DeclarePrivateClassMember (ClassScope * scope, const AstRawString * property_name, ClassLiteralProperty * property, ClassLiteralProperty::Kind kind, bool is_static, ClassInfo * class_info) [private]
Definition at line 3215 of file parser.cc.
                                                                              {
  if (kind == ClassLiteralProperty::Kind::FIELD ||
      kind == ClassLiteralProperty::Kind::AUTO_ACCESSOR) {
    AddInstanceFieldOrStaticElement(property, class_info, is_static);
  }
  class_info->private_members->Add(property, zone());
  VariableProxy* proxy;
  if (scope->is_reparsed()) {
    PrivateNameScopeIterator private_name_scope_iter(scope);
    proxy = ExpressionFromPrivateName(&private_name_scope_iter, property_name,
                                      position());
  } else {
    proxy = CreatePrivateNameVariable(
        scope, GetVariableMode(kind),
        is_static ? IsStaticFlag::kStatic : IsStaticFlag::kNotStatic,
        property_name);
    int pos = property->value()->position();
    if (pos == kNoSourcePosition) {
      pos = property->key()->position();
    }
    proxy->var()->set_initializer_position(pos);
  }
  property->SetPrivateNameProxy(proxy);
}
References AddInstanceFieldOrStaticElement(), CreatePrivateNameVariable(), ExpressionFromPrivateName(), v8::internal::Scope::is_reparsed(), v8::internal::kNoSourcePosition, v8::internal::kNotStatic, v8::internal::kStatic, v8::internal::Variable::set_initializer_position(), and v8::internal::VariableProxy::var().
DeclarePublicClassField()
void v8::internal::Parser::DeclarePublicClassField (ClassScope * scope, ClassLiteralProperty * property, bool is_static, bool is_computed_name, ClassInfo * class_info) [private]
Definition at line 3197 of file parser.cc.
                                                            {
  AddInstanceFieldOrStaticElement(property, class_info, is_static);
  if (is_computed_name) {
    // We create a synthetic variable name here so that scope
    // analysis doesn't dedupe the vars.
    const AstRawString* name = ClassFieldVariableName(
        ast_value_factory(), class_info->computed_field_count);
    VariableProxy* proxy =
        CreateSyntheticContextVariableProxy(scope, class_info, name, is_static);
    property->set_computed_name_proxy(proxy);
    class_info->public_members->Add(property, zone());
  }
}
References AddInstanceFieldOrStaticElement(), CreateSyntheticContextVariableProxy(), and v8::internal::name.
DeclarePublicClassMethod()
void v8::internal::Parser::DeclarePublicClassMethod (const AstRawString * class_name, ClassLiteralProperty * property, bool is_constructor, ClassInfo * class_info) [private]
Definition at line 3249 of file parser.cc.
                                                             {
  if (is_constructor) {
    DCHECK(!class_info->constructor);
    class_info->constructor = property->value()->AsFunctionLiteral();
    DCHECK_NOT_NULL(class_info->constructor);
    class_info->constructor->set_raw_name(
        class_name != nullptr ? ast_value_factory()->NewConsString(class_name)
                              : nullptr);
    return;
  }
  class_info->public_members->Add(property, zone());
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, and v8::internal::is_constructor.
DeclareUnboundVariable()
void v8::internal::Parser::DeclareUnboundVariable (const AstRawString * name, VariableMode mode, InitializationFlag init, int pos) [private]
Definition at line 1920 of file parser.cc.
                                                                      {
  bool was_added;
  Variable* var = DeclareVariable(name, NORMAL_VARIABLE, mode, init, scope(),
                                  &was_added, pos, end_position());
  // The variable will be added to the declarations list, but since we are not
  // binding it to anything, we can simply ignore it here.
  USE(var);
}
References DeclareVariable(), mode(), v8::internal::name, v8::internal::NORMAL_VARIABLE, and USE.
Referenced by ParseExportStar(), ParseImportDeclaration(), and ParseNamedImports().
DeclareVariable()
Variable * v8::internal::Parser::DeclareVariable (const AstRawString * name, VariableKind kind, VariableMode mode, InitializationFlag init, Scope * declaration_scope, bool * was_added, int begin, int end = kNoSourcePosition) [private]
Definition at line 1953 of file parser.cc.
                                           {
  Declaration* declaration;
  if (mode == VariableMode::kVar && !scope->is_declaration_scope()) {
    DCHECK(scope->is_block_scope() || scope->is_with_scope());
    declaration = factory()->NewNestedVariableDeclaration(scope, begin);
  } else {
    declaration = factory()->NewVariableDeclaration(begin);
  }
  Declare(declaration, name, kind, mode, init, scope, was_added, begin, end);
  return declaration->var();
}
References v8::internal::compiler::begin(), v8::internal::DCHECK(), Declare(), v8::internal::compiler::end(), v8::internal::Scope::is_block_scope(), v8::internal::Scope::is_declaration_scope(), v8::internal::Scope::is_with_scope(), v8::internal::kVar, mode(), v8::internal::name, and v8::internal::Declaration::var().
Referenced by DeclareAndBindVariable(), DeclareBoundVariable(), and DeclareUnboundVariable().
DefaultConstructor()
FunctionLiteral * v8::internal::Parser::DefaultConstructor (const AstRawString * name, bool call_super, int pos) [private]
Definition at line 40 of file parser.cc.
                                                                      {
  int expected_property_count = 0;
  const int parameter_count = 0;
  FunctionKind kind = call_super ? FunctionKind::kDefaultDerivedConstructor
                                 : FunctionKind::kDefaultBaseConstructor;
  DeclarationScope* function_scope = NewFunctionScope(kind);
  SetLanguageMode(function_scope, LanguageMode::kStrict);
  // Set start and end position to the same value
  function_scope->set_start_position(pos);
  function_scope->set_end_position(pos);
  ScopedPtrList<Statement> body(pointer_buffer());
  {
    FunctionState function_state(&function_state_, &scope_, function_scope);
    // ES#sec-runtime-semantics-classdefinitionevaluation
    //
    // 14.a
    // ...
    // iv. If F.[[ConstructorKind]] is DERIVED, then
    // 1. NOTE: This branch behaves similarly to constructor(...args) {
    // super(...args); }. The most notable distinction is that while the
    // aforementioned ECMAScript source text observably calls the
    // @@iterator method on %Array.prototype%, this function does not.
    // 2. Let func be ! F.[[GetPrototypeOf]]().
    // 3. If IsConstructor(func) is false, throw a TypeError exception.
    // 4. Let result be ? Construct(func, args, NewTarget).
    // ...
    if (call_super) {
      SuperCallReference* super_call_ref = NewSuperCallReference(pos);
      Expression* call =
          factory()->NewSuperCallForwardArgs(super_call_ref, pos);
      body.Add(factory()->NewReturnStatement(call, pos));
    }
    expected_property_count = function_state.expected_property_count();
  }
  FunctionLiteral* function_literal = factory()->NewFunctionLiteral(
      name, function_scope, body, expected_property_count, parameter_count,
      parameter_count, FunctionLiteral::kNoDuplicateParameters,
      FunctionSyntaxKind::kAnonymousExpression, default_eager_compile_hint(),
      pos, true, GetNextInfoId());
  return function_literal;
}
References v8::internal::ScopedList< T, TBacking >::Add(), v8::internal::kAnonymousExpression, v8::internal::kDefaultBaseConstructor, v8::internal::kDefaultDerivedConstructor, v8::internal::FunctionLiteral::kNoDuplicateParameters, v8::internal::kStrict, v8::internal::name, NewSuperCallReference(), v8::internal::Scope::set_end_position(), v8::internal::Scope::set_start_position(), and SetLanguageMode().
Referenced by DoParseFunction(), and RewriteClassLiteral().
DeserializeScopeChain()
template<typename IsolateT >
template void v8::internal::Parser::DeserializeScopeChain (IsolateT * isolate, ParseInfo * info, MaybeDirectHandle< ScopeInfo > maybe_outer_scope_info, Scope::DeserializationMode mode = Scope::DeserializationMode::kScopesOnly)
Definition at line 650 of file parser.cc.
                                   {
  InitializeEmptyScopeChain(info);
  DirectHandle<ScopeInfo> outer_scope_info;
  if (maybe_outer_scope_info.ToHandle(&outer_scope_info)) {
    DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
    original_scope_ = Scope::DeserializeScopeChain(
        isolate, zone(), *outer_scope_info, info->script_scope(),
        ast_value_factory(), mode, info);
    DeclarationScope* receiver_scope = original_scope_->GetReceiverScope();
    if (receiver_scope->HasReceiverToDeserialize()) {
      receiver_scope->DeserializeReceiver(ast_value_factory());
    }
    if (info->has_module_in_scope_chain()) {
      set_has_module_in_scope_chain();
    }
  }
}
References v8::internal::ThreadId::Current(), DCHECK_EQ, v8::internal::DeclarationScope::DeserializeReceiver(), v8::internal::Scope::DeserializeScopeChain(), v8::internal::Scope::GetReceiverScope(), v8::internal::ParseInfo::has_module_in_scope_chain(), v8::internal::Scope::HasReceiverToDeserialize(), info(), InitializeEmptyScopeChain(), mode(), v8::internal::ParseInfo::script_scope(), and v8::internal::MaybeDirectHandle< T >::ToHandle().
Referenced by ParseFunction(), ParseProgram(), and v8::internal::BackgroundCompileTask::Run().
DesugarBindingInForEachStatement()
void v8::internal::Parser::DesugarBindingInForEachStatement (ForInfo * for_info, Block ** body_block, Expression ** each_variable) [private]
Definition at line 2268 of file parser.cc.
                                                                          {
  DCHECK_EQ(1, for_info->parsing_result.declarations.size());
  DeclarationParsingResult::Declaration& decl =
      for_info->parsing_result.declarations[0];
  Variable* temp = NewTemporary(ast_value_factory()->dot_for_string());
  ScopedPtrList<Statement> each_initialization_statements(pointer_buffer());
  DCHECK_IMPLIES(!has_error(), decl.pattern != nullptr);
  decl.initializer = factory()->NewVariableProxy(temp, for_info->position);
  InitializeVariables(&each_initialization_statements, NORMAL_VARIABLE, &decl);
  *body_block = factory()->NewBlock(3, false);
  (*body_block)
      ->statements()
      ->Add(factory()->NewBlock(true, each_initialization_statements), zone());
  *each_variable = factory()->NewVariableProxy(temp, for_info->position);
}
References DCHECK_EQ, DCHECK_IMPLIES, InitializeVariables(), NewTemporary(), v8::internal::NORMAL_VARIABLE, and v8::internal::Block::statements().
DesugarLexicalBindingsInForStatement()
Statement * v8::internal::Parser::DesugarLexicalBindingsInForStatement (ForStatement * loop, Statement * init, Expression * cond, Statement * next, Statement * body, Scope * inner_scope, const ForInfo & for_info) [private]
Definition at line 2307 of file parser.cc.
                                                                  {
  // ES6 13.7.4.8 specifies that on each loop iteration the let variables are
  // copied into a new environment. Moreover, the "next" statement must be
  // evaluated not in the environment of the just completed iteration but in
  // that of the upcoming one. We achieve this with the following desugaring.
  // Extra care is needed to preserve the completion value of the original loop.
  //
  // We are given a for statement of the form
  //
  // labels: for (let/const x = i; cond; next) body
  //
  // and rewrite it as follows. Here we write {{ ... }} for init-blocks, ie.,
  // blocks whose ignore_completion_value_ flag is set.
  //
  // {
  // let/const x = i;
  // temp_x = x;
  // first = 1;
  // undefined;
  // outer: for (;;) {
  // let/const x = temp_x;
  // {{ if (first == 1) {
  // first = 0;
  // } else {
  // next;
  // }
  // flag = 1;
  // if (!cond) break;
  // }}
  // labels: for (; flag == 1; flag = 0, temp_x = x) {
  // body
  // }
  // {{ if (flag == 1) // Body used break.
  // break;
  // }}
  // }
  // }
  DCHECK_GT(for_info.bound_names.length(), 0);
  ScopedPtrList<Variable> temps(pointer_buffer());
  Block* outer_block =
      factory()->NewBlock(for_info.bound_names.length() + 4, false);
  // Add statement: let/const x = i.
  outer_block->statements()->Add(init, zone());
  const AstRawString* temp_name = ast_value_factory()->dot_for_string();
  // For each lexical variable x:
  // make statement: temp_x = x.
  for (const AstRawString* bound_name : for_info.bound_names) {
    VariableProxy* proxy = NewUnresolved(bound_name);
    Variable* temp = NewTemporary(temp_name);
    VariableProxy* temp_proxy = factory()->NewVariableProxy(temp);
    Assignment* assignment = factory()->NewAssignment(
        Token::kAssign, temp_proxy, proxy, kNoSourcePosition);
    Statement* assignment_statement =
        factory()->NewExpressionStatement(assignment, kNoSourcePosition);
    outer_block->statements()->Add(assignment_statement, zone());
    temps.Add(temp);
  }
  Variable* first = nullptr;
  // Make statement: first = 1.
  if (next) {
    first = NewTemporary(temp_name);
    VariableProxy* first_proxy = factory()->NewVariableProxy(first);
    Expression* const1 = factory()->NewSmiLiteral(1, kNoSourcePosition);
    Assignment* assignment = factory()->NewAssignment(
        Token::kAssign, first_proxy, const1, kNoSourcePosition);
    Statement* assignment_statement =
        factory()->NewExpressionStatement(assignment, kNoSourcePosition);
    outer_block->statements()->Add(assignment_statement, zone());
  }
  // make statement: undefined;
  outer_block->statements()->Add(
      factory()->NewExpressionStatement(
          factory()->NewUndefinedLiteral(kNoSourcePosition), kNoSourcePosition),
      zone());
  // Make statement: outer: for (;;)
  // Note that we don't actually create the label, or set this loop up as an
  // explicit break target, instead handing it directly to those nodes that
  // need to know about it. This should be safe because we don't run any code
  // in this function that looks up break targets.
  ForStatement* outer_loop = factory()->NewForStatement(kNoSourcePosition);
  outer_block->statements()->Add(outer_loop, zone());
  outer_block->set_scope(scope());
  Block* inner_block = factory()->NewBlock(3, false);
  {
    BlockState block_state(&scope_, inner_scope);
    Block* ignore_completion_block =
        factory()->NewBlock(for_info.bound_names.length() + 3, true);
    ScopedPtrList<Variable> inner_vars(pointer_buffer());
    // For each let variable x:
    // make statement: let/const x = temp_x.
    for (int i = 0; i < for_info.bound_names.length(); i++) {
      VariableProxy* proxy = DeclareBoundVariable(
          for_info.bound_names[i], for_info.parsing_result.descriptor.mode,
          kNoSourcePosition);
      inner_vars.Add(proxy->var());
      VariableProxy* temp_proxy = factory()->NewVariableProxy(temps.at(i));
      Assignment* assignment = factory()->NewAssignment(
          Token::kInit, proxy, temp_proxy, kNoSourcePosition);
      Statement* assignment_statement =
          factory()->NewExpressionStatement(assignment, kNoSourcePosition);
      int declaration_pos = for_info.parsing_result.descriptor.declaration_pos;
      DCHECK_NE(declaration_pos, kNoSourcePosition);
      proxy->var()->set_initializer_position(declaration_pos);
      ignore_completion_block->statements()->Add(assignment_statement, zone());
    }
    // Make statement: if (first == 1) { first = 0; } else { next; }
    if (next) {
      DCHECK(first);
      Expression* compare = nullptr;
      // Make compare expression: first == 1.
      {
        Expression* const1 = factory()->NewSmiLiteral(1, kNoSourcePosition);
        VariableProxy* first_proxy = factory()->NewVariableProxy(first);
        compare = factory()->NewCompareOperation(Token::kEq, first_proxy,
                                                 const1, kNoSourcePosition);
      }
      Statement* clear_first = nullptr;
      // Make statement: first = 0.
      {
        VariableProxy* first_proxy = factory()->NewVariableProxy(first);
        Expression* const0 = factory()->NewSmiLiteral(0, kNoSourcePosition);
        Assignment* assignment = factory()->NewAssignment(
            Token::kAssign, first_proxy, const0, kNoSourcePosition);
        clear_first =
            factory()->NewExpressionStatement(assignment, kNoSourcePosition);
      }
      Statement* clear_first_or_next = factory()->NewIfStatement(
          compare, clear_first, next, kNoSourcePosition);
      ignore_completion_block->statements()->Add(clear_first_or_next, zone());
    }
    Variable* flag = NewTemporary(temp_name);
    // Make statement: flag = 1.
    {
      VariableProxy* flag_proxy = factory()->NewVariableProxy(flag);
      Expression* const1 = factory()->NewSmiLiteral(1, kNoSourcePosition);
      Assignment* assignment = factory()->NewAssignment(
          Token::kAssign, flag_proxy, const1, kNoSourcePosition);
      Statement* assignment_statement =
          factory()->NewExpressionStatement(assignment, kNoSourcePosition);
      ignore_completion_block->statements()->Add(assignment_statement, zone());
    }
    // Make statement: if (!cond) break.
    if (cond) {
      Statement* stop =
          factory()->NewBreakStatement(outer_loop, kNoSourcePosition);
      Statement* noop = factory()->EmptyStatement();
      ignore_completion_block->statements()->Add(
          factory()->NewIfStatement(cond, noop, stop, cond->position()),
          zone());
    }
    inner_block->statements()->Add(ignore_completion_block, zone());
    // Make cond expression for main loop: flag == 1.
    Expression* flag_cond = nullptr;
    {
      Expression* const1 = factory()->NewSmiLiteral(1, kNoSourcePosition);
      VariableProxy* flag_proxy = factory()->NewVariableProxy(flag);
      flag_cond = factory()->NewCompareOperation(Token::kEq, flag_proxy, const1,
                                                 kNoSourcePosition);
    }
    // Create chain of expressions "flag = 0, temp_x = x, ..."
    Statement* compound_next_statement = nullptr;
    {
      Expression* compound_next = nullptr;
      // Make expression: flag = 0.
      {
        VariableProxy* flag_proxy = factory()->NewVariableProxy(flag);
        Expression* const0 = factory()->NewSmiLiteral(0, kNoSourcePosition);
        compound_next = factory()->NewAssignment(Token::kAssign, flag_proxy,
                                                 const0, kNoSourcePosition);
      }
      // Make the comma-separated list of temp_x = x assignments.
      int inner_var_proxy_pos = scanner()->location().beg_pos;
      for (int i = 0; i < for_info.bound_names.length(); i++) {
        VariableProxy* temp_proxy = factory()->NewVariableProxy(temps.at(i));
        VariableProxy* proxy =
            factory()->NewVariableProxy(inner_vars.at(i), inner_var_proxy_pos);
        Assignment* assignment = factory()->NewAssignment(
            Token::kAssign, temp_proxy, proxy, kNoSourcePosition);
        compound_next = factory()->NewBinaryOperation(
            Token::kComma, compound_next, assignment, kNoSourcePosition);
      }
      compound_next_statement =
          factory()->NewExpressionStatement(compound_next, kNoSourcePosition);
    }
    // Make statement: labels: for (; flag == 1; flag = 0, temp_x = x)
    // Note that we reuse the original loop node, which retains its labels
    // and ensures that any break or continue statements in body point to
    // the right place.
    loop->Initialize(nullptr, flag_cond, compound_next_statement, body);
    inner_block->statements()->Add(loop, zone());
    // Make statement: {{if (flag == 1) break;}}
    {
      Expression* compare = nullptr;
      // Make compare expression: flag == 1.
      {
        Expression* const1 = factory()->NewSmiLiteral(1, kNoSourcePosition);
        VariableProxy* flag_proxy = factory()->NewVariableProxy(flag);
        compare = factory()->NewCompareOperation(Token::kEq, flag_proxy, const1,
                                                 kNoSourcePosition);
      }
      Statement* stop =
          factory()->NewBreakStatement(outer_loop, kNoSourcePosition);
      Statement* empty = factory()->EmptyStatement();
      Statement* if_flag_break =
          factory()->NewIfStatement(compare, stop, empty, kNoSourcePosition);
      inner_block->statements()->Add(IgnoreCompletion(if_flag_break), zone());
    }
    inner_block->set_scope(inner_scope);
  }
  outer_loop->Initialize(nullptr, nullptr, nullptr, inner_block);
  return outer_block;
}
References v8::internal::ScopedList< T, TBacking >::Add(), v8::internal::ScopedList< T, TBacking >::at(), v8::internal::DCHECK(), DCHECK_GT, DCHECK_NE, DeclareBoundVariable(), IgnoreCompletion(), v8::internal::ForStatement::Initialize(), v8::internal::kNoSourcePosition, NewTemporary(), v8::internal::AstNode::position(), v8::internal::Variable::set_initializer_position(), v8::internal::Block::set_scope(), v8::internal::Block::statements(), and v8::internal::VariableProxy::var().
DoParseFunction()
FunctionLiteral * v8::internal::Parser::DoParseFunction (Isolate * isolate, ParseInfo * info, int start_position, int end_position, int function_literal_id, const AstRawString * raw_name) [private]
Definition at line 1083 of file parser.cc.
                                                                       {
  DCHECK_EQ(parsing_on_main_thread_, isolate != nullptr);
  DCHECK_NOT_NULL(raw_name);
  DCHECK_NULL(scope_);
  DCHECK(ast_value_factory());
  fni_.PushEnclosingName(raw_name);
  ResetInfoId();
  DCHECK_LT(0, function_literal_id);
  SkipInfos(function_literal_id - 1);
  ParsingModeScope parsing_mode(this, PARSE_EAGERLY);
  // Place holder for the result.
  FunctionLiteral* result = nullptr;
  {
    // Parse the function literal.
    Scope* outer = original_scope_;
    DeclarationScope* outer_function = outer->GetClosureScope();
    DCHECK(outer);
    FunctionState function_state(&function_state_, &scope_, outer_function);
    BlockState block_state(&scope_, outer);
    DCHECK(is_sloppy(outer->language_mode()) ||
           is_strict(info->language_mode()));
    FunctionKind kind = flags().function_kind();
    DCHECK_IMPLIES(IsConciseMethod(kind) || IsAccessorFunction(kind),
                   flags().function_syntax_kind() ==
                       FunctionSyntaxKind::kAccessorOrMethod);
    if (IsArrowFunction(kind)) {
      if (IsAsyncFunction(kind)) {
        DCHECK(!scanner()->HasLineTerminatorAfterNext());
        if (!Check(Token::kAsync)) {
          CHECK(stack_overflow());
          return nullptr;
        }
        if (!(peek_any_identifier() || peek() == Token::kLeftParen)) {
          CHECK(stack_overflow());
          return nullptr;
        }
      }
      CHECK_EQ(function_literal_id, GetNextInfoId());
      // TODO(adamk): We should construct this scope from the ScopeInfo.
      DeclarationScope* scope = NewFunctionScope(kind);
      scope->set_has_checked_syntax(true);
      // This bit only needs to be explicitly set because we're
      // not passing the ScopeInfo to the Scope constructor.
      SetLanguageMode(scope, info->language_mode());
      scope->set_start_position(start_position);
      ParserFormalParameters formals(scope);
      {
        ParameterDeclarationParsingScope formals_scope(this);
        // Parsing patterns as variable reference expression creates
        // NewUnresolved references in current scope. Enter arrow function
        // scope for formal parameter parsing.
        BlockState inner_block_state(&scope_, scope);
        if (Check(Token::kLeftParen)) {
          // '(' StrictFormalParameters ')'
          ParseFormalParameterList(&formals);
          Expect(Token::kRightParen);
        } else {
          // BindingIdentifier
          ParameterParsingScope parameter_parsing_scope(impl(), &formals);
          ParseFormalParameter(&formals);
          DeclareFormalParameters(&formals);
        }
        formals.duplicate_loc = formals_scope.duplicate_location();
      }
      // It doesn't really matter what value we pass here for
      // could_be_immediately_invoked since we already introduced an eager
      // compilation scope above.
      bool could_be_immediately_invoked = false;
      Expression* expression = ParseArrowFunctionLiteral(
          formals, function_literal_id, could_be_immediately_invoked);
      // Scanning must end at the same position that was recorded
      // previously. If not, parsing has been interrupted due to a stack
      // overflow, at which point the partially parsed arrow function
      // concise body happens to be a valid expression. This is a problem
      // only for arrow functions with single expression bodies, since there
      // is no end token such as "}" for normal functions.
      if (scanner()->location().end_pos == end_position) {
        // The pre-parser saw an arrow function here, so the full parser
        // must produce a FunctionLiteral.
        DCHECK(expression->IsFunctionLiteral());
        result = expression->AsFunctionLiteral();
      }
    } else if (IsDefaultConstructor(kind)) {
      DCHECK_EQ(scope(), outer);
      result = DefaultConstructor(raw_name, IsDerivedConstructor(kind),
                                  start_position);
    } else {
      ZonePtrList<const AstRawString>* arguments_for_wrapped_function =
          info->is_wrapped_as_function()
              ? PrepareWrappedArguments(isolate, info, zone())
              : nullptr;
      result = ParseFunctionLiteral(
          raw_name, Scanner::Location::invalid(), kSkipFunctionNameCheck, kind,
          kNoSourcePosition, flags().function_syntax_kind(),
          info->language_mode(), arguments_for_wrapped_function);
    }
    if (has_error()) return nullptr;
    result->set_requires_instance_members_initializer(
        flags().requires_instance_members_initializer());
    result->set_class_scope_has_private_brand(
        flags().class_scope_has_private_brand());
    result->set_has_static_private_methods_or_accessors(
        flags().has_static_private_methods_or_accessors());
  }
  info->set_max_info_id(GetLastInfoId());
  DCHECK_IMPLIES(result, function_literal_id == result->function_literal_id());
  return result;
}
References CHECK, CHECK_EQ, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_LT, DCHECK_NOT_NULL, DCHECK_NULL, DeclareFormalParameters(), DefaultConstructor(), v8::internal::ParserFormalParameters::duplicate_loc, v8::internal::ParameterDeclarationParsingScope< Types >::duplicate_location(), v8::internal::flags, v8::internal::function_literal_id, v8::internal::Scope::GetClosureScope(), v8::internal::has_static_private_methods_or_accessors, wasm::impl(), info(), v8::internal::Scanner::Location::invalid(), v8::internal::is_sloppy(), v8::internal::is_strict(), v8::internal::ParseInfo::is_wrapped_as_function(), v8::internal::IsAccessorFunction(), v8::internal::IsArrowFunction(), v8::internal::IsAsyncFunction(), v8::internal::IsConciseMethod(), v8::internal::IsDefaultConstructor(), v8::internal::IsDerivedConstructor(), v8::internal::kAccessorOrMethod, v8::internal::kNoSourcePosition, v8::internal::kSkipFunctionNameCheck, v8::internal::Scope::language_mode(), v8::internal::ParseInfo::language_mode(), PARSE_EAGERLY, ParseFunctionLiteral(), PrepareWrappedArguments(), v8::internal::requires_instance_members_initializer, v8::base::internal::result, v8::internal::DeclarationScope::set_has_checked_syntax(), v8::internal::ParseInfo::set_max_info_id(), v8::internal::Scope::set_start_position(), and SetLanguageMode().
Referenced by ParseFunction(), and ParseOnBackground().
DoParseProgram()
FunctionLiteral * v8::internal::Parser::DoParseProgram (Isolate * isolate, ParseInfo * info) [private]
Definition at line 740 of file parser.cc.
                                                                         {
  // Note that this function can be called from the main thread or from a
  // background thread. We should not access anything Isolate / heap dependent
  // via ParseInfo, and also not pass it forward. If not on the main thread
  // isolate will be nullptr.
  DCHECK_EQ(parsing_on_main_thread_, isolate != nullptr);
  DCHECK_NULL(scope_);
  ParsingModeScope mode(this, allow_lazy_ ? PARSE_LAZILY : PARSE_EAGERLY);
  ResetInfoId();
  FunctionLiteral* result = nullptr;
  {
    Scope* outer = original_scope_;
    DCHECK_NOT_NULL(outer);
    if (flags().is_eval()) {
      outer = NewEvalScope(outer);
    } else if (flags().is_module()) {
      DCHECK_EQ(outer, info->script_scope());
      outer = NewModuleScope(info->script_scope());
    }
    DeclarationScope* scope = outer->AsDeclarationScope();
    scope->set_start_position(0);
    FunctionState function_state(&function_state_, &scope_, scope);
    ScopedPtrList<Statement> body(pointer_buffer());
    int beg_pos = scanner()->location().beg_pos;
    if (flags().is_module()) {
      DCHECK(flags().is_module());
      PrepareGeneratorVariables();
      Expression* initial_yield = BuildInitialYield(
          kNoSourcePosition, FunctionKind::kGeneratorFunction);
      body.Add(
          factory()->NewExpressionStatement(initial_yield, kNoSourcePosition));
      ParseModuleItemList(&body);
      // Modules will always have an initial yield. If there are any
      // additional suspends, they are awaits, and we treat the module as a
      // ModuleWithTopLevelAwait.
      if (function_state.suspend_count() > 1) {
        scope->set_module_has_toplevel_await();
      }
      if (!has_error() &&
          !module()->Validate(this->scope()->AsModuleScope(),
                              pending_error_handler(), zone())) {
        scanner()->set_parser_error();
      }
    } else if (info->is_wrapped_as_function()) {
      DCHECK(parsing_on_main_thread_);
      ParseWrapped(isolate, info, &body, scope, zone());
    } else if (flags().is_repl_mode()) {
      ParseREPLProgram(info, &body, scope);
    } else {
      // Don't count the mode in the use counters--give the program a chance
      // to enable script-wide strict mode below.
      this->scope()->SetLanguageMode(info->language_mode());
      ParseStatementList(&body, Token::kEos);
    }
    // The parser will peek but not consume kEos. Our scope logically goes all
    // the way to the kEos, though.
    scope->set_end_position(peek_position());
    if (is_strict(language_mode())) {
      CheckStrictOctalLiteral(beg_pos, end_position());
    }
    if (is_sloppy(language_mode())) {
      // TODO(littledan): Function bindings on the global object that modify
      // pre-existing bindings should be made writable, enumerable and
      // nonconfigurable if possible, whereas this code will leave attributes
      // unchanged if the property already exists.
      InsertSloppyBlockFunctionVarBindings(scope);
    }
    // Internalize the ast strings in the case of eval so we can check for
    // conflicting var declarations with outer scope-info-backed scopes.
    if (flags().is_eval()) {
      DCHECK(parsing_on_main_thread_);
      DCHECK(!isolate->main_thread_local_heap()->IsParked());
      info->ast_value_factory()->Internalize(isolate);
    }
    CheckConflictingVarDeclarations(scope);
    // For sloppy eval though, we clear dynamic variables created for toplevel
    // var to avoid resolving to a variable when the variable and proxy are in
    // the same eval execution. The variable is not available on subsequent lazy
    // executions of functions in the eval, so this avoids inner functions from
    // looking up different variables during eager and lazy compilation.
    if (flags().is_eval()) outer->RemoveDynamic();
    if (flags().parse_restriction() == ONLY_SINGLE_FUNCTION_LITERAL) {
      if (body.length() != 1 || !body.at(0)->IsExpressionStatement() ||
          !body.at(0)
               ->AsExpressionStatement()
               ->expression()
               ->IsFunctionLiteral()) {
        ReportMessage(MessageTemplate::kSingleFunctionLiteral);
      }
    }
    int parameter_count = 0;
    result = factory()->NewScriptOrEvalFunctionLiteral(
        scope, body, function_state.expected_property_count(), parameter_count);
    result->set_suspend_count(function_state.suspend_count());
  }
  info->set_max_info_id(GetLastInfoId());
  if (has_error()) return nullptr;
  RecordFunctionLiteralSourceRange(result);
  return result;
}
References v8::internal::ScopedList< T, TBacking >::Add(), allow_lazy_, v8::internal::Scope::AsDeclarationScope(), v8::internal::ParseInfo::ast_value_factory(), v8::internal::ScopedList< T, TBacking >::at(), BuildInitialYield(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::flags, info(), InsertSloppyBlockFunctionVarBindings(), v8::internal::AstValueFactory::Internalize(), v8::internal::is_sloppy(), v8::internal::is_strict(), v8::internal::ParseInfo::is_wrapped_as_function(), v8::internal::LocalHeap::IsParked(), v8::internal::kGeneratorFunction, v8::internal::kNoSourcePosition, v8::internal::ParseInfo::language_mode(), v8::internal::ScopedList< T, TBacking >::length(), v8::internal::Isolate::main_thread_local_heap(), mode(), v8::internal::ONLY_SINGLE_FUNCTION_LITERAL, PARSE_EAGERLY, PARSE_LAZILY, ParseModuleItemList(), ParseREPLProgram(), ParseWrapped(), PrepareGeneratorVariables(), RecordFunctionLiteralSourceRange(), v8::internal::Scope::RemoveDynamic(), v8::base::internal::result, v8::internal::ParseInfo::script_scope(), v8::internal::Scope::set_end_position(), v8::internal::ParseInfo::set_max_info_id(), v8::internal::DeclarationScope::set_module_has_toplevel_await(), v8::internal::Scope::set_start_position(), and v8::internal::Scope::SetLanguageMode().
Referenced by ParseOnBackground(), and ParseProgram().
EmptyIdentifierString()
const AstRawString* v8::internal::Parser::EmptyIdentifierString () const [inline], [private]
Definition at line 771 of file parser.h.
                                                              {
    return ast_value_factory()->empty_string();
  }
Referenced by ParseExportSpecifierName().
ExpressionFromIdentifier()
VariableProxy* v8::internal::Parser::ExpressionFromIdentifier (const AstRawString * name, int start_position, InferName infer = InferName::kYes) [inline], [private]
Definition at line 829 of file parser.h.
                                       {
    if (infer == InferName::kYes) {
      fni_.PushVariableName(name);
    }
    return expression_scope()->NewVariable(name, start_position);
  }
References v8::internal::kYes, and v8::internal::name.
Referenced by ParseFunction().
ExpressionFromLiteral()
Expression * v8::internal::Parser::ExpressionFromLiteral (Token::Value token, int pos) [private]
Definition at line 502 of file parser.cc.
                                                                   {
  switch (token) {
    case Token::kNullLiteral:
      return factory()->NewNullLiteral(pos);
    case Token::kTrueLiteral:
      return factory()->NewBooleanLiteral(true, pos);
    case Token::kFalseLiteral:
      return factory()->NewBooleanLiteral(false, pos);
    case Token::kSmi: {
      uint32_t value = scanner()->smi_value();
      return factory()->NewSmiLiteral(value, pos);
    }
    case Token::kNumber: {
      double value = scanner()->DoubleValue();
      return factory()->NewNumberLiteral(value, pos);
    }
    case Token::kBigInt:
      return factory()->NewBigIntLiteral(
          AstBigInt(scanner()->CurrentLiteralAsCString(zone())), pos);
    case Token::kString: {
      return factory()->NewStringLiteral(GetSymbol(), pos);
    }
    default:
      DCHECK(false);
  }
  return FailureExpression();
}
References v8::internal::DCHECK(), FailureExpression(), GetSymbol(), v8::internal::compiler::kSmi, and v8::internal::value.
ExpressionFromPrivateName()
VariableProxy* v8::internal::Parser::ExpressionFromPrivateName (PrivateNameScopeIterator * private_name_scope, const AstRawString * name, int start_position) [inline], [private]
Definition at line 820 of file parser.h.
                          {
    VariableProxy* proxy = factory()->ast_node_factory()->NewVariableProxy(
        name, NORMAL_VARIABLE, start_position);
    private_name_scope->AddUnresolvedPrivateName(proxy);
    return proxy;
  }
References v8::internal::PrivateNameScopeIterator::AddUnresolvedPrivateName(), v8::internal::name, and v8::internal::NORMAL_VARIABLE.
Referenced by DeclarePrivateClassMember().
ExpressionListToExpression()
Expression * v8::internal::Parser::ExpressionListToExpression (const ScopedPtrList< Expression > & args) [private]
Definition at line 3628 of file parser.cc.
                                           {
  Expression* expr = args.at(0);
  if (args.length() == 1) return expr;
  if (args.length() == 2) {
    return factory()->NewBinaryOperation(Token::kComma, expr, args.at(1),
                                         args.at(1)->position());
  }
  NaryOperation* result =
      factory()->NewNaryOperation(Token::kComma, expr, args.length() - 1);
  for (int i = 1; i < args.length(); i++) {
    result->AddSubsequent(args.at(i), args.at(i)->position());
  }
  return result;
}
References v8::base::args, and v8::base::internal::result.
extension()
v8::Extension* v8::internal::Parser::extension () const [inline], [private]
Definition at line 614 of file parser.h.
{ return info_->extension(); }
Referenced by DeclareNative(), and ParseFunctionLiteral().
FailureExpression()
Expression* v8::internal::Parser::FailureExpression () [inline], [private]
Definition at line 759 of file parser.h.
{ return factory()->FailureExpression(); }
Referenced by ExpressionFromLiteral(), and NewV8Intrinsic().
GetBigIntAsSymbol()
const AstRawString * v8::internal::Parser::GetBigIntAsSymbol () [private]
Definition at line 416 of file parser.cc.
                                              {
  base::Vector<const uint8_t> literal = scanner()->BigIntLiteral();
  if (literal[0] != '0' || literal.length() == 1) {
    return ast_value_factory()->GetOneByteString(literal);
  }
  std::unique_ptr<char[]> decimal =
      BigIntLiteralToDecimal(local_isolate_, literal);
  return ast_value_factory()->GetOneByteString(decimal.get());
}
References v8::internal::BigIntLiteralToDecimal(), v8::base::Vector< T >::length(), and local_isolate_.
GetDefaultStrings()
void v8::internal::Parser::GetDefaultStrings (const AstRawString ** default_string, const AstRawString ** dot_default_string) [inline], [private]
Definition at line 642 of file parser.h.
                                                                            {
    *default_string = ast_value_factory()->default_string();
    *dot_default_string = ast_value_factory()->dot_default_string();
  }
GetEmbedderCompileHint()
FunctionLiteral::EagerCompileHint v8::internal::Parser::GetEmbedderCompileHint (FunctionLiteral::EagerCompileHint current_compile_hint, int position) [inline], [private]
Definition at line 1089 of file parser.h.
                                                                          {
    if (current_compile_hint == FunctionLiteral::kShouldLazyCompile) {
      v8::CompileHintCallback callback = info_->compile_hint_callback();
      if (callback != nullptr &&
          callback(position, info_->compile_hint_callback_data())) {
        return FunctionLiteral::kShouldEagerCompile;
      }
    }
    return current_compile_hint;
  }
References v8::internal::FunctionLiteral::kShouldEagerCompile, and v8::internal::FunctionLiteral::kShouldLazyCompile.
Referenced by ParseFunctionLiteral().
GetIdentifier()
const AstRawString* v8::internal::Parser::GetIdentifier () const [inline], [private]
Definition at line 786 of file parser.h.
{ return GetSymbol(); }
Referenced by ReportUnexpectedTokenAt().
GetNextSymbol()
const AstRawString* v8::internal::Parser::GetNextSymbol () const [inline], [private]
Definition at line 788 of file parser.h.
                                                      {
    return scanner()->NextSymbol(ast_value_factory());
  }
GetNumberAsSymbol()
const AstRawString* v8::internal::Parser::GetNumberAsSymbol () const [inline], [private]
Definition at line 792 of file parser.h.
                                                          {
    double double_value = scanner()->DoubleValue();
    char array[100];
    std::string_view string =
        DoubleToStringView(double_value, base::ArrayVector(array));
    return ast_value_factory()->GetOneByteString(
        base::OneByteVector(string.data(), string.length()));
  }
References v8::base::ArrayVector(), v8::internal::DoubleToStringView(), v8::internal::length, and v8::base::OneByteVector().
GetRawNameFromIdentifier()
const AstRawString* v8::internal::Parser::GetRawNameFromIdentifier (const AstRawString * arg) [inline], [private]
Definition at line 728 of file parser.h.
                                                                        {
    return arg;
  }
GetSymbol()
const AstRawString* v8::internal::Parser::GetSymbol () const [inline], [private]
Definition at line 780 of file parser.h.
                                                  {
    const AstRawString* result = scanner()->CurrentSymbol(ast_value_factory());
    DCHECK_NOT_NULL(result);
    return result;
  }
References DCHECK_NOT_NULL, and v8::base::internal::result.
Referenced by ExpressionFromLiteral(), ParseExportSpecifierName(), ParseImportWithOrAssertClause(), and ParseModuleSpecifier().
HandleDebugMagicComments()
template<typename IsolateT >
template void v8::internal::Parser::HandleDebugMagicComments (IsolateT * isolate, DirectHandle< Script > script)
Definition at line 3426 of file parser.cc.
                                                                   {
  DirectHandle<String> source_url = scanner_.SourceUrl(isolate);
  if (!source_url.is_null()) {
    script->set_source_url(*source_url);
  }
  DirectHandle<String> source_mapping_url = scanner_.SourceMappingUrl(isolate);
  // The API can provide a source map URL and the API should take precedence.
  // Let's make sure we do not override the API with the magic comment.
  if (!source_mapping_url.is_null() &&
      IsUndefined(script->source_mapping_url(isolate), isolate)) {
    script->set_source_mapping_url(*source_mapping_url);
  }
  DirectHandle<String> debug_id = scanner_.DebugId(isolate);
  if (!debug_id.is_null()) {
    script->set_debug_id(*debug_id);
  }
}
References v8::internal::Scanner::DebugId(), v8::internal::DirectHandle< T >::is_null(), scanner_, v8::internal::script, v8::internal::Scanner::SourceMappingUrl(), and v8::internal::Scanner::SourceUrl().
Referenced by ParseOnBackground(), and ParseProgram().
HasCheckedSyntax()
bool v8::internal::Parser::HasCheckedSyntax () [inline], [private]
Definition at line 384 of file parser.h.
                          {
    return scope()->GetDeclarationScope()->has_checked_syntax();
  }
IdentifierEquals()
bool v8::internal::Parser::IdentifierEquals (const AstRawString * identifier, const AstRawString * other) [inline], [private]
Definition at line 340 of file parser.h.
                                                   {
    return identifier == other;
  }
IgnoreCompletion()
Block * v8::internal::Parser::IgnoreCompletion (Statement * statement) [private]
Definition at line 2066 of file parser.cc.
                                                    {
  Block* block = factory()->NewBlock(1, true);
  block->statements()->Add(statement, zone());
  return block;
}
References v8::internal::Block::statements().
Referenced by DeclareClass(), DesugarLexicalBindingsInForStatement(), ParseExportDefault(), and RewriteSwitchStatement().
ImportMetaExpression()
Expression * v8::internal::Parser::ImportMetaExpression (int pos) [private]
Definition at line 490 of file parser.cc.
                                                {
  ScopedPtrList<Expression> args(pointer_buffer());
  if (!has_module_in_scope_chain()) {
    DCHECK(IsParsingWhileDebugging());
    // When debugging, we permit import.meta invocations -- however, they will
    // never produce a non-undefined result outside of a module.
    return factory()->NewUndefinedLiteral(pos);
  }
  return factory()->NewCallRuntime(Runtime::kInlineGetImportMetaObject, args,
                                   pos);
}
References v8::base::args, and v8::internal::DCHECK().
InferFunctionName()
void v8::internal::Parser::InferFunctionName () [inline], [private]
Definition at line 674 of file parser.h.
{ fni_.Infer(); }
info()
ParseInfo* v8::internal::Parser::info () const [inline], [private]
Definition at line 1105 of file parser.h.
{ return info_; }
Referenced by DeclareFunction(), DeserializeScopeChain(), DoParseFunction(), DoParseProgram(), InitializeEmptyScopeChain(), ParseFunction(), ParseFunctionLiteral(), ParseOnBackground(), ParseProgram(), Parser(), ParseREPLProgram(), ParseWrapped(), and PostProcessParseResult().
InitializeEmptyScopeChain()
void v8::internal::Parser::InitializeEmptyScopeChain (ParseInfo * info)
Definition at line 640 of file parser.cc.
                                                      {
  DCHECK_NULL(original_scope_);
  DCHECK_NULL(info->script_scope());
  DeclarationScope* script_scope =
      NewScriptScope(flags().is_repl_mode() ? REPLMode::kYes : REPLMode::kNo);
  info->set_script_scope(script_scope);
  original_scope_ = script_scope;
}
References DCHECK_NULL, v8::internal::flags, info(), v8::internal::kNo, v8::internal::kYes, v8::internal::ParseInfo::script_scope(), and v8::internal::ParseInfo::set_script_scope().
Referenced by DeserializeScopeChain(), and v8::internal::BackgroundCompileTask::Run().
InitializeObjectLiteral()
ObjectLiteral* v8::internal::Parser::InitializeObjectLiteral (ObjectLiteral * object_literal) [inline], [private]
Definition at line 408 of file parser.h.
                                                                        {
    object_literal->CalculateEmitStore(main_zone());
    return object_literal;
  }
References v8::internal::ObjectLiteral::CalculateEmitStore().
InitializeVariables()
void v8::internal::Parser::InitializeVariables (ScopedPtrList< Statement > * statements, VariableKind kind, const DeclarationParsingResult::Declaration * declaration) [private]
Definition at line 2110 of file parser.cc.
                                                            {
  if (has_error()) return;
  DCHECK_NOT_NULL(declaration->initializer);
  int pos = declaration->value_beg_pos;
  if (pos == kNoSourcePosition) {
    pos = declaration->initializer->position();
  }
  Assignment* assignment = factory()->NewAssignment(
      Token::kInit, declaration->pattern, declaration->initializer, pos);
  statements->Add(factory()->NewExpressionStatement(assignment, pos));
}
References v8::internal::ScopedList< T, TBacking >::Add(), DCHECK_NOT_NULL, and v8::internal::kNoSourcePosition.
Referenced by BuildInitializationBlock(), BuildParameterInitializationBlock(), DesugarBindingInForEachStatement(), and RewriteCatchPattern().
InsertShadowingVarBindingInitializers()
void v8::internal::Parser::InsertShadowingVarBindingInitializers (Block * block) [private]
Definition at line 3369 of file parser.cc.
                                                                     {
  // For each var-binding that shadows a parameter, insert an assignment
  // initializing the variable with the parameter.
  Scope* inner_scope = inner_block->scope();
  DCHECK(inner_scope->is_declaration_scope());
  Scope* function_scope = inner_scope->outer_scope();
  DCHECK(function_scope->is_function_scope());
  BlockState block_state(&scope_, inner_scope);
  // According to https://tc39.es/ecma262/#sec-functiondeclarationinstantiation
  // If a variable's name conflicts with the names of both parameters and
  // functions, no bindings should be created for it. A set is used here
  // to record such variables.
  std::set<Variable*> hoisted_func_vars;
  std::vector<std::pair<Variable*, Variable*>> var_param_bindings;
  for (Declaration* decl : *inner_scope->declarations()) {
    if (!decl->IsVariableDeclaration()) {
      hoisted_func_vars.insert(decl->var());
      continue;
    } else if (decl->var()->mode() != VariableMode::kVar) {
      continue;
    }
    const AstRawString* name = decl->var()->raw_name();
    Variable* parameter = function_scope->LookupLocal(name);
    if (parameter == nullptr) continue;
    var_param_bindings.push_back(std::pair(decl->var(), parameter));
  }
  for (auto decl : var_param_bindings) {
    if (hoisted_func_vars.find(decl.first) != hoisted_func_vars.end()) {
      continue;
    }
    const AstRawString* name = decl.first->raw_name();
    VariableProxy* to = NewUnresolved(name);
    VariableProxy* from = factory()->NewVariableProxy(decl.second);
    Expression* assignment =
        factory()->NewAssignment(Token::kAssign, to, from, kNoSourcePosition);
    Statement* statement =
        factory()->NewExpressionStatement(assignment, kNoSourcePosition);
    inner_block->statements()->InsertAt(0, statement, zone());
  }
}
References v8::internal::DCHECK(), v8::internal::Scope::declarations(), v8::internal::Scope::is_declaration_scope(), v8::internal::Scope::is_function_scope(), v8::internal::kNoSourcePosition, v8::internal::kVar, v8::internal::Scope::LookupLocal(), v8::internal::name, v8::internal::Scope::outer_scope(), v8::internal::Block::scope(), and v8::internal::Block::statements().
InsertSloppyBlockFunctionVarBindings()
void v8::internal::Parser::InsertSloppyBlockFunctionVarBindings (DeclarationScope * scope) [private]
Definition at line 3411 of file parser.cc.
                                                                         {
  // For the outermost eval scope, we cannot hoist during parsing: let
  // declarations in the surrounding scope may prevent hoisting, but the
  // information is unaccessible during parsing. In this case, we hoist later in
  // DeclarationScope::Analyze.
  if (scope->is_eval_scope() && scope->outer_scope() == original_scope_) {
    return;
  }
  scope->HoistSloppyBlockFunctions(factory());
}
References v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), v8::internal::Scope::is_eval_scope(), and v8::internal::Scope::outer_scope().
Referenced by DoParseProgram().
IsArguments()
bool v8::internal::Parser::IsArguments (const AstRawString * identifier) const [inline], [private]
Definition at line 562 of file parser.h.
                                                                   {
    return identifier == ast_value_factory()->arguments_string();
  }
IsArrayIndex()
static bool v8::internal::Parser::IsArrayIndex (const AstRawString * string, uint32_t * index) [inline], [static], [private]
Definition at line 625 of file parser.h.
                                                      {
    return string->AsArrayIndex(index);
  }
References v8::internal::index.
IsAsync()
bool v8::internal::Parser::IsAsync (const AstRawString * identifier) const [inline], [private]
Definition at line 558 of file parser.h.
                                                               {
    return identifier == ast_value_factory()->async_string();
  }
IsBoilerplateProperty()
static bool v8::internal::Parser::IsBoilerplateProperty (ObjectLiteral::Property * property) [inline], [static], [private]
Definition at line 609 of file parser.h.
                                       {
    return !property->IsPrototype();
  }
IsConstructor()
bool v8::internal::Parser::IsConstructor (const AstRawString * identifier) const [inline], [private]
Definition at line 605 of file parser.h.
                                                                     {
    return identifier == ast_value_factory()->constructor_string();
  }
IsEmptyIdentifier()
bool v8::internal::Parser::IsEmptyIdentifier (const AstRawString * subject) const [inline], [private]
Definition at line 774 of file parser.h.
                                                                      {
    DCHECK_NOT_NULL(subject);
    return subject->IsEmpty();
  }
References DCHECK_NOT_NULL, and v8::internal::AstRawString::IsEmpty().
Referenced by DeclareClassVariable(), ParseClassForMemberInitialization(), and RewriteClassLiteral().
IsEval()
bool v8::internal::Parser::IsEval (const AstRawString * identifier) const [inline], [private]
Definition at line 554 of file parser.h.
                                                              {
    return identifier == ast_value_factory()->eval_string();
  }
IsEvalOrArguments()
bool v8::internal::Parser::IsEvalOrArguments (const AstRawString * identifier) const [inline], [private]
Definition at line 566 of file parser.h.
                                                                         {
    return IsEval(identifier) || IsArguments(identifier);
  }
Referenced by ParseNamedImports().
IsIdentifier()
static bool v8::internal::Parser::IsIdentifier (Expression * expression) [inline], [static], [private]
Definition at line 591 of file parser.h.
                                                             {
    VariableProxy* operand = expression->AsVariableProxy();
    return operand != nullptr && !operand->is_new_target();
  }
References v8::internal::VariableProxy::is_new_target().
IsIterationStatement()
static bool v8::internal::Parser::IsIterationStatement (Statement * subject) [inline], [static], [private]
Definition at line 766 of file parser.h.
                                                                 {
    return subject->AsIterationStatement() != nullptr;
  }
References v8::internal::AstNode::AsIterationStatement().
IsNative()
bool v8::internal::Parser::IsNative (Expression * expr) const [inline], [private]
Definition at line 618 of file parser.h.
                                                  {
    DCHECK_NOT_NULL(expr);
    return expr->IsVariableProxy() &&
           expr->AsVariableProxy()->raw_name() ==
               ast_value_factory()->native_string();
  }
References DCHECK_NOT_NULL.
IsNull()
template<typename T >
static bool v8::internal::Parser::IsNull (T subject) [inline], [static], [private]
Definition at line 762 of file parser.h.
                                          {
    return subject == nullptr;
  }
IsPreParser()
static bool v8::internal::Parser::IsPreParser () [inline], [static]
Definition at line 140 of file parser.h.
{ return false; }
IsPrivateReference()
static bool v8::internal::Parser::IsPrivateReference (Expression * expression) [inline], [static], [private]
Definition at line 578 of file parser.h.
                                                                   {
    DCHECK_NOT_NULL(expression);
    Property* property = expression->AsProperty();
    if (expression->IsOptionalChain()) {
      Expression* expr_inner = expression->AsOptionalChain()->expression();
      property = expr_inner->AsProperty();
    }
    return property != nullptr && property->IsPrivateReference();
  }
References DCHECK_NOT_NULL.
IsStringLiteral()
bool v8::internal::Parser::IsStringLiteral (Statement * statement, const AstRawString * arg = nullptr) const [inline], [private]
Definition at line 633 of file parser.h.
                                                                          {
    ExpressionStatement* e_stat = statement->AsExpressionStatement();
    if (e_stat == nullptr) return false;
    Literal* literal = e_stat->expression()->AsLiteral();
    if (literal == nullptr || !literal->IsRawString()) return false;
    return arg == nullptr || literal->AsRawString() == arg;
  }
References v8::internal::Literal::AsRawString(), v8::internal::ExpressionStatement::expression(), and v8::internal::Literal::IsRawString().
IsThisProperty()
static bool v8::internal::Parser::IsThisProperty (Expression * expression) [inline], [static], [private]
Definition at line 571 of file parser.h.
                                                               {
    DCHECK_NOT_NULL(expression);
    Property* property = expression->AsProperty();
    return property != nullptr && property->obj()->IsThisExpression();
  }
References DCHECK_NOT_NULL.
MakeAutoAccessorGetter()
FunctionLiteral * v8::internal::Parser::MakeAutoAccessorGetter (VariableProxy * name_proxy, const AstRawString * name, bool is_static, int pos) [private]
Definition at line 88 of file parser.cc.
                                                                         {
  ScopedPtrList<Statement> body(pointer_buffer());
  DeclarationScope* function_scope =
      NewFunctionScope(is_static ? FunctionKind::kGetterFunction
                                 : FunctionKind::kStaticGetterFunction);
  SetLanguageMode(function_scope, LanguageMode::kStrict);
  function_scope->set_start_position(pos);
  function_scope->set_end_position(pos);
  {
    FunctionState function_state(&function_state_, &scope_, function_scope);
    body.Add(factory()->NewAutoAccessorGetterBody(name_proxy, pos));
  }
  // TODO(42202709): Enable lazy compilation by adding custom handling in
  // `Parser::DoParseFunction`.
  FunctionLiteral* getter = factory()->NewFunctionLiteral(
      nullptr, function_scope, body, 0, 0, 0,
      FunctionLiteral::kNoDuplicateParameters,
      FunctionSyntaxKind::kAccessorOrMethod,
      FunctionLiteral::kShouldEagerCompile, pos, true, GetNextInfoId());
  const AstRawString* prefix =
      name ? ast_value_factory()->get_space_string() : nullptr;
  SetFunctionName(getter, name, prefix);
  return getter;
}
References v8::internal::ScopedList< T, TBacking >::Add(), v8::internal::kAccessorOrMethod, v8::internal::kGetterFunction, v8::internal::FunctionLiteral::kNoDuplicateParameters, v8::internal::FunctionLiteral::kShouldEagerCompile, v8::internal::kStaticGetterFunction, v8::internal::kStrict, v8::internal::name, v8::internal::Scope::set_end_position(), v8::internal::Scope::set_start_position(), SetFunctionName(), and SetLanguageMode().
Referenced by NewAutoAccessorInfo().
MakeAutoAccessorSetter()
FunctionLiteral * v8::internal::Parser::MakeAutoAccessorSetter (VariableProxy * name_proxy, const AstRawString * name, bool is_static, int pos) [private]
Definition at line 115 of file parser.cc.
                                                                         {
  ScopedPtrList<Statement> body(pointer_buffer());
  DeclarationScope* function_scope =
      NewFunctionScope(is_static ? FunctionKind::kSetterFunction
                                 : FunctionKind::kStaticSetterFunction);
  SetLanguageMode(function_scope, LanguageMode::kStrict);
  function_scope->set_start_position(pos);
  function_scope->set_end_position(pos);
  function_scope->DeclareParameter(ast_value_factory()->empty_string(),
                                   VariableMode::kTemporary, false, false,
                                   ast_value_factory(), kNoSourcePosition);
  {
    FunctionState function_state(&function_state_, &scope_, function_scope);
    body.Add(factory()->NewAutoAccessorSetterBody(name_proxy, pos));
  }
  // TODO(42202709): Enable lazy compilation by adding custom handling in
  // `Parser::DoParseFunction`.
  FunctionLiteral* setter = factory()->NewFunctionLiteral(
      nullptr, function_scope, body, 0, 1, 0,
      FunctionLiteral::kNoDuplicateParameters,
      FunctionSyntaxKind::kAccessorOrMethod,
      FunctionLiteral::kShouldEagerCompile, pos, true, GetNextInfoId());
  const AstRawString* prefix =
      name ? ast_value_factory()->set_space_string() : nullptr;
  SetFunctionName(setter, name, prefix);
  return setter;
}
References v8::internal::ScopedList< T, TBacking >::Add(), v8::internal::DeclarationScope::DeclareParameter(), v8::internal::kAccessorOrMethod, v8::internal::FunctionLiteral::kNoDuplicateParameters, v8::internal::kNoSourcePosition, v8::internal::kSetterFunction, v8::internal::FunctionLiteral::kShouldEagerCompile, v8::internal::kStaticSetterFunction, v8::internal::kStrict, v8::internal::kTemporary, v8::internal::name, v8::internal::Scope::set_end_position(), v8::internal::Scope::set_start_position(), SetFunctionName(), SetLanguageMode(), and v8::internal::setter.
Referenced by NewAutoAccessorInfo().
NewAutoAccessorInfo()
AutoAccessorInfo * v8::internal::Parser::NewAutoAccessorInfo (ClassScope * scope, ClassInfo * class_info, const AstRawString * name, bool is_static, int pos) [private]
Definition at line 145 of file parser.cc.
                                                                       {
  VariableProxy* accessor_storage_name_proxy =
      CreateSyntheticContextVariableProxy(
          scope, class_info,
          AutoAccessorVariableName(ast_value_factory(),
                                   class_info->autoaccessor_count++),
          is_static);
  // The property value position will match the beginning of the "accessor"
  // keyword, which can be the same as the start of the parent class scope, use
  // the position of the next two characters to distinguish them.
  FunctionLiteral* getter = MakeAutoAccessorGetter(accessor_storage_name_proxy,
                                                   name, is_static, pos + 1);
  FunctionLiteral* setter = MakeAutoAccessorSetter(accessor_storage_name_proxy,
                                                   name, is_static, pos + 2);
  return factory()->NewAutoAccessorInfo(getter, setter,
                                        accessor_storage_name_proxy);
}
References CreateSyntheticContextVariableProxy(), MakeAutoAccessorGetter(), MakeAutoAccessorSetter(), v8::internal::name, and v8::internal::setter.
Referenced by NewClassLiteralPropertyWithAccessorInfo().
NewClassLiteralPropertyWithAccessorInfo()
ClassLiteralProperty * v8::internal::Parser::NewClassLiteralPropertyWithAccessorInfo (ClassScope * scope, ClassInfo * class_info, const AstRawString * name, Expression * key, Expression * value, bool is_static, bool is_computed_name, bool is_private, int pos) [private]
Definition at line 166 of file parser.cc.
                              {
  AutoAccessorInfo* accessor_info =
      NewAutoAccessorInfo(scope, class_info, name, is_static, pos);
  return factory()->NewClassLiteralProperty(
      key, value, accessor_info, is_static, is_computed_name, is_private);
}
References v8::internal::key, v8::internal::name, NewAutoAccessorInfo(), and v8::internal::value.
NewClassPropertyList()
ZonePtrList<ClassLiteral::Property>* v8::internal::Parser::NewClassPropertyList (int size) const [inline], [private]
Definition at line 848 of file parser.h.
                      {
    return zone()->New<ZonePtrList<ClassLiteral::Property>>(size, zone());
  }
References size().
NewClassStaticElementList()
ZonePtrList<ClassLiteral::StaticElement>* v8::internal::Parser::NewClassStaticElementList (int size) const [inline], [private]
Definition at line 852 of file parser.h.
                      {
    return zone()->New<ZonePtrList<ClassLiteral::StaticElement>>(size, zone());
  }
References size().
NewSuperCallReference()
SuperCallReference * v8::internal::Parser::NewSuperCallReference (int pos) [private]
Definition at line 475 of file parser.cc.
                                                         {
  VariableProxy* new_target_proxy =
      NewUnresolved(ast_value_factory()->new_target_string(), pos);
  VariableProxy* this_function_proxy =
      NewUnresolved(ast_value_factory()->this_function_string(), pos);
  return factory()->NewSuperCallReference(new_target_proxy, this_function_proxy,
                                          pos);
}
Referenced by DefaultConstructor().
NewSuperPropertyReference()
Expression * v8::internal::Parser::NewSuperPropertyReference (int pos) [private]
Definition at line 462 of file parser.cc.
                                                     {
  const AstRawString* home_object_name;
  if (IsStatic(scope()->GetReceiverScope()->function_kind())) {
    home_object_name = ast_value_factory_->dot_static_home_object_string();
  } else {
    home_object_name = ast_value_factory_->dot_home_object_string();
  }
  VariableProxy* proxy = NewUnresolved(home_object_name, pos);
  proxy->set_is_home_object();
  return factory()->NewSuperPropertyReference(proxy, pos);
}
References v8::internal::IsStatic(), and v8::internal::VariableProxy::set_is_home_object().
NewTargetExpression()
Expression * v8::internal::Parser::NewTargetExpression (int pos) [private]
Definition at line 484 of file parser.cc.
                                               {
  auto proxy = NewUnresolved(ast_value_factory()->new_target_string(), pos);
  proxy->set_is_new_target();
  return proxy;
}
NewTemporary()
Variable* v8::internal::Parser::NewTemporary (const AstRawString * name) [inline], [private]
Definition at line 219 of file parser.h.
                                                   {
    return scope()->NewTemporary(name);
  }
References v8::internal::name.
Referenced by DesugarBindingInForEachStatement(), DesugarLexicalBindingsInForStatement(), and RewriteSwitchStatement().
NewThisExpression()
class ThisExpression* v8::internal::Parser::NewThisExpression (int pos) [inline], [private]
Definition at line 808 of file parser.h.
                                                   {
    UseThis();
    return factory()->NewThisExpression(pos);
  }
NewThrowError()
Expression * v8::internal::Parser::NewThrowError (Runtime::FunctionId function_id, MessageTemplate message, const AstRawString * arg, int pos) [private]
Definition at line 452 of file parser.cc.
                                                                    {
  ScopedPtrList<Expression> args(pointer_buffer());
  args.Add(factory()->NewSmiLiteral(static_cast<int>(message), pos));
  args.Add(factory()->NewStringLiteral(arg, pos));
  CallRuntime* call_constructor = factory()->NewCallRuntime(id, args, pos);
  return factory()->NewThrow(call_constructor, pos);
}
References v8::base::args.
NewThrowReferenceError()
Expression* v8::internal::Parser::NewThrowReferenceError (MessageTemplate message, int pos) [inline], [private]
Definition at line 718 of file parser.h.
                                                        {
    return NewThrowError(Runtime::kNewReferenceError, message,
                         ast_value_factory()->empty_string(), pos);
  }
NewThrowStatement()
Statement* v8::internal::Parser::NewThrowStatement (Expression * exception, int pos) [inline], [private]
Definition at line 864 of file parser.h.
                                                                         {
    return factory()->NewExpressionStatement(
        factory()->NewThrow(exception, pos), pos);
  }
NewV8Intrinsic()
Expression * v8::internal::Parser::NewV8Intrinsic (const AstRawString * name, const ScopedPtrList< Expression > & args, int pos) [private]
Definition at line 530 of file parser.cc.
                                            {
  if (ParsingExtension()) {
    // The extension structures are only accessible while parsing the
    // very first time, not when reparsing because of lazy compilation.
    GetClosureScope()->ForceEagerCompilation();
  }
  if (!name->is_one_byte()) {
    // There are no two-byte named intrinsics.
    ReportMessage(MessageTemplate::kNotDefined, name);
    return FailureExpression();
  }
  const Runtime::Function* function =
      Runtime::FunctionForName(name->raw_data(), name->length());
  // Be more permissive when fuzzing. Intrinsics are not supported.
  if (v8_flags.fuzzing) {
    return NewV8RuntimeFunctionForFuzzing(function, args, pos);
  }
  if (function == nullptr) {
    ReportMessage(MessageTemplate::kNotDefined, name);
    return FailureExpression();
  }
  // Check that the expected number of arguments are being passed.
  if (function->nargs != -1 && function->nargs != args.length()) {
    ReportMessage(MessageTemplate::kRuntimeWrongNumArgs);
    return FailureExpression();
  }
  return factory()->NewCallRuntime(function, args, pos);
}
References v8::base::args, FailureExpression(), v8::internal::Runtime::FunctionForName(), v8::internal::name, NewV8RuntimeFunctionForFuzzing(), ParsingExtension(), and v8::internal::v8_flags.
NewV8RuntimeFunctionForFuzzing()
Expression * v8::internal::Parser::NewV8RuntimeFunctionForFuzzing (const Runtime::Function * function, const ScopedPtrList< Expression > & args, int pos) [private]
Definition at line 568 of file parser.cc.
             {
  CHECK(v8_flags.fuzzing);
  // Intrinsics are not supported for fuzzing. Only allow runtime functions
  // marked as fuzzing-safe. Also prevent later errors due to too few arguments
  // and just ignore this call.
  if (function == nullptr ||
      !Runtime::IsEnabledForFuzzing(function->function_id) ||
      function->nargs > args.length()) {
    return factory()->NewUndefinedLiteral(kNoSourcePosition);
  }
  // Flexible number of arguments permitted.
  if (function->nargs == -1) {
    return factory()->NewCallRuntime(function, args, pos);
  }
  // Otherwise ignore superfluous arguments.
  ScopedPtrList<Expression> permissive_args(pointer_buffer());
  for (int i = 0; i < function->nargs; i++) {
    permissive_args.Add(args.at(i));
  }
  return factory()->NewCallRuntime(function, permissive_args, pos);
}
References v8::internal::ScopedList< T, TBacking >::Add(), v8::base::args, CHECK, v8::internal::Runtime::IsEnabledForFuzzing(), v8::internal::kNoSourcePosition, and v8::internal::v8_flags.
Referenced by NewV8Intrinsic().
NextInternalNamespaceExportName()
const AstRawString * v8::internal::Parser::NextInternalNamespaceExportName () [private]
Definition at line 1739 of file parser.cc.
                                                            {
  const char* prefix = ".ns-export";
  std::string s(prefix);
  s.append(std::to_string(number_of_named_namespace_exports_++));
  return ast_value_factory()->GetOneByteString(s.c_str());
}
References number_of_named_namespace_exports_, and v8::internal::string.
Referenced by ParseExportStar().
NullBlock()
static std::nullptr_t v8::internal::Parser::NullBlock () [inline], [static], [private]
Definition at line 758 of file parser.h.
{ return nullptr; }
NullExpression()
static std::nullptr_t v8::internal::Parser::NullExpression () [inline], [static], [private]
Definition at line 749 of file parser.h.
{ return nullptr; }
Referenced by ParseFunction().
NullExpressionList()
static ZonePtrList<Expression>* v8::internal::Parser::NullExpressionList () [inline], [static], [private]
Definition at line 751 of file parser.h.
                                                                 {
    return nullptr;
  }
NullIdentifier()
static std::nullptr_t v8::internal::Parser::NullIdentifier () [inline], [static], [private]
Definition at line 748 of file parser.h.
{ return nullptr; }
NullLiteralProperty()
static std::nullptr_t v8::internal::Parser::NullLiteralProperty () [inline], [static], [private]
Definition at line 750 of file parser.h.
{ return nullptr; }
NullStatement()
static std::nullptr_t v8::internal::Parser::NullStatement () [inline], [static], [private]
Definition at line 757 of file parser.h.
{ return nullptr; }
NullStatementList()
static ZonePtrList<Statement>* v8::internal::Parser::NullStatementList () [inline], [static], [private]
Definition at line 754 of file parser.h.
                                                               {
    return nullptr;
  }
OpenTemplateLiteral()
Parser::TemplateLiteralState v8::internal::Parser::OpenTemplateLiteral (int pos) [private]
Definition at line 3556 of file parser.cc.
                                                              {
  return zone()->New<TemplateLiteral>(zone(), pos);
}
parse_lazily()
bool v8::internal::Parser::parse_lazily () const [inline], [private]
Definition at line 196 of file parser.h.
{ return mode_ == PARSE_LAZILY; }
Referenced by ParseFunctionLiteral().
ParseAsyncGeneratorFunctionBody()
void v8::internal::Parser::ParseAsyncGeneratorFunctionBody (int pos, FunctionKind kind, ScopedPtrList< Statement > * body) [private]
Definition at line 2198 of file parser.cc.
                                                                             {
  DCHECK(IsAsyncGeneratorFunction(kind));
  Expression* initial_yield = BuildInitialYield(pos, kind);
  body->Add(
      factory()->NewExpressionStatement(initial_yield, kNoSourcePosition));
  ParseStatementList(body, Token::kRightBrace);
}
References v8::internal::ScopedList< T, TBacking >::Add(), BuildInitialYield(), v8::internal::DCHECK(), v8::internal::IsAsyncGeneratorFunction(), and v8::internal::kNoSourcePosition.
ParseClassForMemberInitialization()
FunctionLiteral * v8::internal::Parser::ParseClassForMemberInitialization (FunctionKind initializer_kind, int initializer_pos, int initializer_id, int initializer_end_pos, const AstRawString * class_name) [private]
Definition at line 1209 of file parser.cc.
                                                             {
  // When the function is a class members initializer function, we record the
  // source range of the entire class body as its positions in its SFI, so at
  // this point the scanner should be rewound to the position of the class
  // token.
  DCHECK_EQ(peek_position(), initializer_pos);
  // Insert a FunctionState with the closest outer Declaration scope
  DeclarationScope* nearest_decl_scope = original_scope_->GetDeclarationScope();
  DCHECK_NOT_NULL(nearest_decl_scope);
  FunctionState function_state(&function_state_, &scope_, nearest_decl_scope);
  // We will reindex the function literals later.
  ResetInfoId();
  SkipInfos(initializer_id - 1);
  // We preparse the class members that are not fields with initializers
  // in order to collect the function literal ids.
  ParsingModeScope mode(this, PARSE_LAZILY);
  ExpressionParsingScope no_expression_scope(impl());
  // Reparse the whole class body to build member initializer functions.
  FunctionLiteral* initializer;
  {
    bool is_anonymous = IsEmptyIdentifier(class_name);
    BlockState block_state(&scope_, original_scope_);
    RaiseLanguageMode(LanguageMode::kStrict);
    BlockState object_literal_scope_state(&object_literal_scope_, nullptr);
    ClassInfo class_info(this);
    class_info.is_anonymous = is_anonymous;
    // Create an arbitrary non-Null expression to indicate that the class
    // extends something. Doing so unconditionally is fine because:
    // - the fact whether the class extends something affects parsing of
    // 'super' expressions which cause parse-time SyntaxError if the class
    // is not a derived one. However, all such errors must have been
    // reported during initial parse of the class declaration.
    // - "extends" clause affects class constructor's FunctionKind, but here
    // we are interested only in the member initializer functions and thus
    // we can ignore the constructor function details.
    //
    // Given all the above we can simplify things and for the purpose of class
    // member initializers reparsing don't bother propagating the existence of
    // the "extends" clause through scope serialization/deserialization.
    class_info.extends = factory()->NewNullLiteral(kNoSourcePosition);
    // Note that we don't recheck class_name for strict-reserved words or eval
    // because all such checks have already been done during initial paring and
    // respective SyntaxErrors must have been thrown if necessary.
    // Class initializers don't care about position of the class token.
    int class_token_pos = kNoSourcePosition;
#ifdef DEBUG
    scope()->MarkReparsingForClassInitializer();
#endif
    ParseClassLiteralBody(class_info, class_name, class_token_pos, Token::kEos);
    if (initializer_kind == FunctionKind::kClassMembersInitializerFunction) {
      DCHECK_EQ(class_info.instance_members_function_id, initializer_id);
      initializer = CreateInstanceMembersInitializer(class_name, &class_info);
    } else {
      DCHECK_EQ(class_info.static_elements_function_id, initializer_id);
      initializer = CreateStaticElementsInitializer(class_name, &class_info);
    }
    initializer->scope()->TakeUnresolvedReferencesFromParent();
  }
  if (has_error()) return nullptr;
  DCHECK(IsClassMembersInitializerFunction(initializer_kind));
  no_expression_scope.ValidateExpression();
  DCHECK_EQ(initializer->kind(), initializer_kind);
  DCHECK_EQ(initializer->function_literal_id(), initializer_id);
  DCHECK_EQ(initializer->end_position(), initializer_end_pos);
  return initializer;
}
References CreateInstanceMembersInitializer(), CreateStaticElementsInitializer(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::FunctionLiteral::end_position(), v8::internal::FunctionLiteral::function_literal_id(), v8::internal::Scope::GetDeclarationScope(), wasm::impl(), v8::internal::IsClassMembersInitializerFunction(), IsEmptyIdentifier(), v8::internal::kClassMembersInitializerFunction, v8::internal::FunctionLiteral::kind(), v8::internal::kNoSourcePosition, v8::internal::kStrict, mode(), PARSE_LAZILY, v8::internal::FunctionLiteral::scope(), v8::internal::DeclarationScope::TakeUnresolvedReferencesFromParent(), and v8::internal::ExpressionParsingScope< Types >::ValidateExpression().
Referenced by ParseFunction().
ParseExportClause()
ZoneChunkList< Parser::ExportClauseData > * v8::internal::Parser::ParseExportClause (Scanner::Location * reserved_loc, Scanner::Location * string_literal_local_name_loc) [private]
Definition at line 1347 of file parser.cc.
                                                    {
  // ExportClause :
  // '{' '}'
  // '{' ExportsList '}'
  // '{' ExportsList ',' '}'
  //
  // ExportsList :
  // ExportSpecifier
  // ExportsList ',' ExportSpecifier
  //
  // ExportSpecifier :
  // IdentifierName
  // IdentifierName 'as' IdentifierName
  // IdentifierName 'as' ModuleExportName
  // ModuleExportName
  // ModuleExportName 'as' ModuleExportName
  //
  // ModuleExportName :
  // StringLiteral
  ZoneChunkList<ExportClauseData>* export_data =
      zone()->New<ZoneChunkList<ExportClauseData>>(zone());
  Expect(Token::kLeftBrace);
  Token::Value name_tok;
  while ((name_tok = peek()) != Token::kRightBrace) {
    const AstRawString* local_name = ParseExportSpecifierName();
    if (!string_literal_local_name_loc->IsValid() &&
        name_tok == Token::kString) {
      // Keep track of the first string literal local name exported for error
      // reporting. These must be followed by a 'from' clause.
      *string_literal_local_name_loc = scanner()->location();
    } else if (!reserved_loc->IsValid() &&
               !Token::IsValidIdentifier(name_tok, LanguageMode::kStrict, false,
                                         flags().is_module())) {
      // Keep track of the first reserved word encountered in case our
      // caller needs to report an error.
      *reserved_loc = scanner()->location();
    }
    const AstRawString* export_name;
    Scanner::Location location = scanner()->location();
    if (CheckContextualKeyword(ast_value_factory()->as_string())) {
      export_name = ParseExportSpecifierName();
      // Set the location to the whole "a as b" string, so that it makes sense
      // both for errors due to "a" and for errors due to "b".
      location.end_pos = scanner()->location().end_pos;
    } else {
      export_name = local_name;
    }
    export_data->push_back({export_name, local_name, location});
    if (peek() == Token::kRightBrace) break;
    if (V8_UNLIKELY(!Check(Token::kComma))) {
      ReportUnexpectedToken(Next());
      break;
    }
  }
  Expect(Token::kRightBrace);
  return export_data;
}
References v8::internal::Scanner::Location::end_pos, v8::internal::flags, v8::internal::Scanner::Location::IsValid(), v8::internal::Token::IsValidIdentifier(), v8::internal::kStrict, v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), ParseExportSpecifierName(), v8::internal::ZoneChunkList< T >::push_back(), and V8_UNLIKELY.
Referenced by ParseExportDeclaration().
ParseExportDeclaration()
Statement * v8::internal::Parser::ParseExportDeclaration () [private]
Definition at line 1794 of file parser.cc.
                                          {
  // ExportDeclaration:
  // 'export' '*' 'from' ModuleSpecifier ';'
  // 'export' '*' 'from' ModuleSpecifier [no LineTerminator here]
  // AssertClause ';'
  // 'export' '*' 'as' IdentifierName 'from' ModuleSpecifier ';'
  // 'export' '*' 'as' IdentifierName 'from' ModuleSpecifier
  // [no LineTerminator here] AssertClause ';'
  // 'export' '*' 'as' ModuleExportName 'from' ModuleSpecifier ';'
  // 'export' '*' 'as' ModuleExportName 'from' ModuleSpecifier ';'
  // [no LineTerminator here] AssertClause ';'
  // 'export' ExportClause ('from' ModuleSpecifier)? ';'
  // 'export' ExportClause ('from' ModuleSpecifier [no LineTerminator here]
  // AssertClause)? ';'
  // 'export' VariableStatement
  // 'export' Declaration
  // 'export' 'default' ... (handled in ParseExportDefault)
  //
  // ModuleExportName :
  // StringLiteral
  Expect(Token::kExport);
  Statement* result = nullptr;
  ZonePtrList<const AstRawString> names(1, zone());
  Scanner::Location loc = scanner()->peek_location();
  switch (peek()) {
    case Token::kDefault:
      return ParseExportDefault();
    case Token::kMul:
      ParseExportStar();
      return factory()->EmptyStatement();
    case Token::kLeftBrace: {
      // There are two cases here:
      //
      // 'export' ExportClause ';'
      // and
      // 'export' ExportClause FromClause ';'
      //
      // In the first case, the exported identifiers in ExportClause must
      // not be reserved words, while in the latter they may be. We
      // pass in a location that gets filled with the first reserved word
      // encountered, and then throw a SyntaxError if we are in the
      // non-FromClause case.
      Scanner::Location reserved_loc = Scanner::Location::invalid();
      Scanner::Location string_literal_local_name_loc =
          Scanner::Location::invalid();
      ZoneChunkList<ExportClauseData>* export_data =
          ParseExportClause(&reserved_loc, &string_literal_local_name_loc);
      if (CheckContextualKeyword(ast_value_factory()->from_string())) {
        Scanner::Location specifier_loc = scanner()->peek_location();
        const AstRawString* module_specifier = ParseModuleSpecifier();
        const ImportAttributes* import_attributes =
            ParseImportWithOrAssertClause();
        ExpectSemicolon();
        if (export_data->empty()) {
          module()->AddEmptyImport(module_specifier, import_attributes,
                                   specifier_loc, zone());
        } else {
          for (const ExportClauseData& data : *export_data) {
            module()->AddExport(data.local_name, data.export_name,
                                module_specifier, import_attributes,
                                data.location, specifier_loc, zone());
          }
        }
      } else {
        if (reserved_loc.IsValid()) {
          // No FromClause, so reserved words are invalid in ExportClause.
          ReportMessageAt(reserved_loc, MessageTemplate::kUnexpectedReserved);
          return nullptr;
        } else if (string_literal_local_name_loc.IsValid()) {
          ReportMessageAt(string_literal_local_name_loc,
                          MessageTemplate::kModuleExportNameWithoutFromClause);
          return nullptr;
        }
        ExpectSemicolon();
        for (const ExportClauseData& data : *export_data) {
          module()->AddExport(data.local_name, data.export_name, data.location,
                              zone());
        }
      }
      return factory()->EmptyStatement();
    }
    case Token::kFunction:
      result = ParseHoistableDeclaration(&names, false);
      break;
    case Token::kClass:
      Consume(Token::kClass);
      result = ParseClassDeclaration(&names, false);
      break;
    case Token::kVar:
    case Token::kLet:
    case Token::kConst:
      result = ParseVariableStatement(kStatementListItem, &names);
      break;
    case Token::kAsync:
      Consume(Token::kAsync);
      if (peek() == Token::kFunction &&
          !scanner()->HasLineTerminatorBeforeNext()) {
        result = ParseAsyncFunctionDeclaration(&names, false);
        break;
      }
      [[fallthrough]];
    default:
      ReportUnexpectedToken(scanner()->current_token());
      return nullptr;
  }
  loc.end_pos = scanner()->location().end_pos;
  SourceTextModuleDescriptor* descriptor = module();
  for (const AstRawString* name : names) {
    descriptor->AddExport(name, name, loc, zone());
  }
  return result;
}
References v8::internal::SourceTextModuleDescriptor::AddExport(), v8::internal::ZoneChunkList< T >::empty(), v8::internal::Scanner::Location::invalid(), v8::internal::Scanner::Location::IsValid(), v8::internal::torque::ls::kClass, v8::internal::torque::ls::kFunction, v8::internal::loc, v8::internal::name, ParseExportClause(), ParseExportDefault(), ParseExportStar(), ParseImportWithOrAssertClause(), ParseModuleSpecifier(), and v8::base::internal::result.
Referenced by ParseModuleItem().
ParseExportDefault()
Statement * v8::internal::Parser::ParseExportDefault () [private]
Definition at line 1673 of file parser.cc.
                                      {
  // Supports the following productions, starting after the 'default' token:
  // 'export' 'default' HoistableDeclaration
  // 'export' 'default' ClassDeclaration
  // 'export' 'default' AssignmentExpression[In] ';'
  Expect(Token::kDefault);
  Scanner::Location default_loc = scanner()->location();
  ZonePtrList<const AstRawString> local_names(1, zone());
  Statement* result = nullptr;
  switch (peek()) {
    case Token::kFunction:
      result = ParseHoistableDeclaration(&local_names, true);
      break;
    case Token::kClass:
      Consume(Token::kClass);
      result = ParseClassDeclaration(&local_names, true);
      break;
    case Token::kAsync:
      if (PeekAhead() == Token::kFunction &&
          !scanner()->HasLineTerminatorAfterNext()) {
        Consume(Token::kAsync);
        result = ParseAsyncFunctionDeclaration(&local_names, true);
        break;
      }
      [[fallthrough]];
    default: {
      int pos = position();
      AcceptINScope scope(this, true);
      Expression* value = ParseAssignmentExpression();
      SetFunctionName(value, ast_value_factory()->default_string());
      const AstRawString* local_name =
          ast_value_factory()->dot_default_string();
      local_names.Add(local_name, zone());
      // It's fine to declare this as VariableMode::kConst because the user has
      // no way of writing to it.
      VariableProxy* proxy =
          DeclareBoundVariable(local_name, VariableMode::kConst, pos);
      proxy->var()->set_initializer_position(position());
      Assignment* assignment = factory()->NewAssignment(
          Token::kInit, proxy, value, kNoSourcePosition);
      result = IgnoreCompletion(
          factory()->NewExpressionStatement(assignment, kNoSourcePosition));
      ExpectSemicolon();
      break;
    }
  }
  if (result != nullptr) {
    DCHECK_EQ(local_names.length(), 1);
    module()->AddExport(local_names.first(),
                        ast_value_factory()->default_string(), default_loc,
                        zone());
  }
  return result;
}
References v8::internal::ZoneList< T >::Add(), DCHECK_EQ, DeclareBoundVariable(), v8::internal::ZoneList< T >::first(), IgnoreCompletion(), v8::internal::torque::ls::kClass, v8::internal::kConst, v8::internal::torque::ls::kFunction, v8::internal::kNoSourcePosition, v8::internal::ZoneList< T >::length(), v8::base::internal::result, v8::internal::Variable::set_initializer_position(), SetFunctionName(), v8::internal::value, and v8::internal::VariableProxy::var().
Referenced by ParseExportDeclaration().
ParseExportSpecifierName()
const AstRawString * v8::internal::Parser::ParseExportSpecifierName () [private]
Definition at line 1410 of file parser.cc.
                                                     {
  Token::Value next = Next();
  // IdentifierName
  if (V8_LIKELY(Token::IsPropertyName(next))) {
    return GetSymbol();
  }
  // ModuleExportName
  if (next == Token::kString) {
    const AstRawString* export_name = GetSymbol();
    if (V8_LIKELY(export_name->is_one_byte())) return export_name;
    if (!unibrow::Utf16::HasUnpairedSurrogate(
            reinterpret_cast<const uint16_t*>(export_name->raw_data()),
            export_name->length())) {
      return export_name;
    }
    ReportMessage(MessageTemplate::kInvalidModuleExportName);
    return EmptyIdentifierString();
  }
  ReportUnexpectedToken(next);
  return EmptyIdentifierString();
}
References EmptyIdentifierString(), GetSymbol(), unibrow::Utf16::HasUnpairedSurrogate(), v8::internal::AstRawString::is_one_byte(), v8::internal::Token::IsPropertyName(), v8::internal::AstRawString::length(), v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), v8::internal::AstRawString::raw_data(), and V8_LIKELY.
Referenced by ParseExportClause(), ParseExportStar(), and ParseNamedImports().
ParseExportStar()
void v8::internal::Parser::ParseExportStar () [private]
Definition at line 1746 of file parser.cc.
                             {
  int pos = position();
  Consume(Token::kMul);
  if (!PeekContextualKeyword(ast_value_factory()->as_string())) {
    // 'export' '*' 'from' ModuleSpecifier ';'
    Scanner::Location loc = scanner()->location();
    ExpectContextualKeyword(ast_value_factory()->from_string());
    Scanner::Location specifier_loc = scanner()->peek_location();
    const AstRawString* module_specifier = ParseModuleSpecifier();
    const ImportAttributes* import_attributes = ParseImportWithOrAssertClause();
    ExpectSemicolon();
    module()->AddStarExport(module_specifier, import_attributes, loc,
                            specifier_loc, zone());
    return;
  }
  // 'export' '*' 'as' IdentifierName 'from' ModuleSpecifier ';'
  //
  // Desugaring:
  // export * as x from "...";
  // ~>
  // import * as .x from "..."; export {.x as x};
  //
  // Note that the desugared internal namespace export name (.x above) will
  // never conflict with a string literal export name, as literal string export
  // names in local name positions (i.e. left of 'as' or in a clause without
  // 'as') are disallowed without a following 'from' clause.
  ExpectContextualKeyword(ast_value_factory()->as_string());
  const AstRawString* export_name = ParseExportSpecifierName();
  Scanner::Location export_name_loc = scanner()->location();
  const AstRawString* local_name = NextInternalNamespaceExportName();
  Scanner::Location local_name_loc = Scanner::Location::invalid();
  DeclareUnboundVariable(local_name, VariableMode::kConst, kCreatedInitialized,
                         pos);
  ExpectContextualKeyword(ast_value_factory()->from_string());
  Scanner::Location specifier_loc = scanner()->peek_location();
  const AstRawString* module_specifier = ParseModuleSpecifier();
  const ImportAttributes* import_attributes = ParseImportWithOrAssertClause();
  ExpectSemicolon();
  module()->AddStarImport(local_name, module_specifier, import_attributes,
                          local_name_loc, specifier_loc, zone());
  module()->AddExport(local_name, export_name, export_name_loc, zone());
}
References DeclareUnboundVariable(), v8::internal::Scanner::Location::invalid(), v8::internal::kConst, v8::internal::kCreatedInitialized, v8::internal::loc, NextInternalNamespaceExportName(), ParseExportSpecifierName(), ParseImportWithOrAssertClause(), and ParseModuleSpecifier().
Referenced by ParseExportDeclaration().
ParseFunction() [1/2]
void v8::internal::Parser::ParseFunction (Isolate * isolate, ParseInfo * info, DirectHandle< SharedFunctionInfo > shared_info) [private]
Definition at line 1009 of file parser.cc.
                                                                         {
  // It's OK to use the Isolate & counters here, since this function is only
  // called in the main thread.
  DCHECK(parsing_on_main_thread_);
  RCS_SCOPE(runtime_call_stats_, RuntimeCallCounterId::kParseFunction);
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"), "V8.ParseFunction");
  base::ElapsedTimer timer;
  if (V8_UNLIKELY(v8_flags.log_function_events)) timer.Start();
  MaybeDirectHandle<ScopeInfo> maybe_outer_scope_info;
  if (shared_info->HasOuterScopeInfo()) {
    maybe_outer_scope_info =
        direct_handle(shared_info->GetOuterScopeInfo(), isolate);
  }
  int start_position = shared_info->StartPosition();
  int end_position = shared_info->EndPosition();
  DeserializeScopeChain(isolate, info, maybe_outer_scope_info,
                        Scope::DeserializationMode::kIncludingVariables);
  DCHECK_EQ(factory()->zone(), info->zone());
  DirectHandle<Script> script(Cast<Script>(shared_info->script()), isolate);
  if (shared_info->is_wrapped()) {
    maybe_wrapped_arguments_ = handle(script->wrapped_arguments(), isolate);
  }
  int function_literal_id = shared_info->function_literal_id(kRelaxedLoad);
  // Initialize parser state.
  info->set_function_name(ast_value_factory()->GetString(
      shared_info->Name(), SharedStringAccessGuardIfNeeded(isolate)));
  scanner_.Initialize();
  FunctionKind function_kind = flags().function_kind();
  FunctionLiteral* result;
  if (V8_UNLIKELY(IsClassMembersInitializerFunction(function_kind))) {
    // Reparsing of class member initializer functions has to be handled
    // specially because they require reparsing of the whole class body,
    // function start/end positions correspond to the class literal body
    // positions.
    result = ParseClassForMemberInitialization(
        function_kind, start_position, function_literal_id, end_position,
        info->function_name());
    info->set_max_info_id(GetLastInfoId());
  } else if (V8_UNLIKELY(shared_info->private_name_lookup_skips_outer_class() &&
                         original_scope_->is_class_scope())) {
    // If the function skips the outer class and the outer scope is a class, the
    // function is in heritage position. Otherwise the function scope's skip bit
    // will be correctly inherited from the outer scope.
    ClassScope::HeritageParsingScope heritage(original_scope_->AsClassScope());
    result = DoParseFunction(isolate, info, start_position, end_position,
                             function_literal_id, info->function_name());
  } else {
    result = DoParseFunction(isolate, info, start_position, end_position,
                             function_literal_id, info->function_name());
  }
  if (result == nullptr) return;
  MaybeProcessSourceRanges(info, result, stack_limit_);
  PostProcessParseResult(isolate, info, result);
  if (V8_UNLIKELY(v8_flags.log_function_events)) {
    double ms = timer.Elapsed().InMillisecondsF();
    // We should already be internalized by now, so the debug name will be
    // available.
    DeclarationScope* function_scope = result->scope();
    std::unique_ptr<char[]> function_name = shared_info->DebugNameCStr();
    LOG(isolate,
        FunctionEvent("parse-function", flags().script_id(), ms,
                      function_scope->start_position(),
                      function_scope->end_position(), function_name.get(),
                      strlen(function_name.get())));
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, DeserializeScopeChain(), v8::internal::direct_handle(), DoParseFunction(), v8::base::ElapsedTimer::Elapsed(), v8::internal::Scope::end_position(), v8::internal::flags, v8::internal::function_literal_id, v8::internal::ParseInfo::function_name(), v8::internal::handle(), info(), v8::internal::Scanner::Initialize(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::IsClassMembersInitializerFunction(), v8::internal::Scope::kIncludingVariables, v8::kRelaxedLoad, LOG, maybe_wrapped_arguments_, v8::internal::anonymous_namespace{parser.cc}::MaybeProcessSourceRanges(), ParseClassForMemberInitialization(), PostProcessParseResult(), RCS_SCOPE, v8::base::internal::result, scanner_, v8::internal::script, v8::internal::ParseInfo::set_function_name(), v8::internal::ParseInfo::set_max_info_id(), v8::base::ElapsedTimer::Start(), v8::internal::Scope::start_position(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::ParseInfo::zone().
Referenced by v8::internal::parsing::ParseFunction(), and ParseFunctionLiteral().
ParseFunction() [2/2]
void v8::internal::Parser::ParseFunction (ScopedPtrList< Statement > * body, const AstRawString * function_name, int pos, FunctionKind kind, FunctionSyntaxKind function_syntax_kind, DeclarationScope * function_scope, int * num_parameters, int * function_length, bool * has_duplicate_parameters, int * expected_property_count, int * suspend_count, ZonePtrList< const AstRawString > * arguments_for_wrapped_function) [private]
Definition at line 3053 of file parser.cc.
                                                                     {
  FunctionParsingScope function_parsing_scope(this);
  ParsingModeScope mode(this, allow_lazy_ ? PARSE_LAZILY : PARSE_EAGERLY);
  FunctionState function_state(&function_state_, &scope_, function_scope);
  bool is_wrapped = function_syntax_kind == FunctionSyntaxKind::kWrapped;
  int expected_parameters_end_pos = parameters_end_pos_;
  if (expected_parameters_end_pos != kNoSourcePosition) {
    // This is the first function encountered in a CreateDynamicFunction eval.
    parameters_end_pos_ = kNoSourcePosition;
    // The function name should have been ignored, giving us the empty string
    // here.
    DCHECK_EQ(function_name, ast_value_factory()->empty_string());
  }
  ParserFormalParameters formals(function_scope);
  {
    ParameterDeclarationParsingScope formals_scope(this);
    if (is_wrapped) {
      // For a function implicitly wrapped in function header and footer, the
      // function arguments are provided separately to the source, and are
      // declared directly here.
      for (const AstRawString* arg : *arguments_for_wrapped_function) {
        const bool is_rest = false;
        Expression* argument = ExpressionFromIdentifier(arg, kNoSourcePosition);
        AddFormalParameter(&formals, argument, NullExpression(),
                           kNoSourcePosition, is_rest);
      }
      DCHECK_EQ(arguments_for_wrapped_function->length(),
                formals.num_parameters());
      DeclareFormalParameters(&formals);
    } else {
      // For a regular function, the function arguments are parsed from source.
      DCHECK_NULL(arguments_for_wrapped_function);
      ParseFormalParameterList(&formals);
      if (expected_parameters_end_pos != kNoSourcePosition) {
        // Check for '(' or ')' shenanigans in the parameter string for dynamic
        // functions.
        int position = peek_position();
        if (position < expected_parameters_end_pos) {
          ReportMessageAt(Scanner::Location(position, position + 1),
                          MessageTemplate::kArgStringTerminatesParametersEarly);
          return;
        } else if (position > expected_parameters_end_pos) {
          ReportMessageAt(Scanner::Location(expected_parameters_end_pos - 2,
                                            expected_parameters_end_pos),
                          MessageTemplate::kUnexpectedEndOfArgString);
          return;
        }
      }
      Expect(Token::kRightParen);
      int formals_end_position = end_position();
      CheckArityRestrictions(formals.arity, kind, formals.has_rest,
                             function_scope->start_position(),
                             formals_end_position);
      Expect(Token::kLeftBrace);
    }
    formals.duplicate_loc = formals_scope.duplicate_location();
  }
  *num_parameters = formals.num_parameters();
  *function_length = formals.function_length;
  AcceptINScope scope(this, true);
  ParseFunctionBody(body, function_name, pos, formals, kind,
                    function_syntax_kind, FunctionBodyType::kBlock);
  *has_duplicate_parameters = formals.has_duplicate();
  *expected_property_count = function_state.expected_property_count();
  *suspend_count = function_state.suspend_count();
}
References AddFormalParameter(), allow_lazy_, v8::internal::FormalParametersBase::arity, DCHECK_EQ, DCHECK_NULL, DeclareFormalParameters(), v8::internal::ParserFormalParameters::duplicate_loc, v8::internal::ParameterDeclarationParsingScope< Types >::duplicate_location(), ExpressionFromIdentifier(), v8::internal::FormalParametersBase::function_length, v8::internal::ParserFormalParameters::has_duplicate(), v8::internal::has_duplicate_parameters, v8::internal::FormalParametersBase::has_rest, v8::internal::kNoSourcePosition, v8::internal::kWrapped, mode(), NullExpression(), v8::internal::FormalParametersBase::num_parameters(), parameters_end_pos_, PARSE_EAGERLY, PARSE_LAZILY, and v8::internal::Scope::start_position().
ParseFunctionLiteral()
FunctionLiteral * v8::internal::Parser::ParseFunctionLiteral (const AstRawString * name, Scanner::Location function_name_location, FunctionNameValidity function_name_validity, FunctionKind kind, int function_token_position, FunctionSyntaxKind type, LanguageMode language_mode, ZonePtrList< const AstRawString > * arguments_for_wrapped_function) [private]
Definition at line 2675 of file parser.cc.
                                                                     {
  // Function ::
  // '(' FormalParameterList? ')' '{' FunctionBody '}'
  //
  // Getter ::
  // '(' ')' '{' FunctionBody '}'
  //
  // Setter ::
  // '(' PropertySetParameterList ')' '{' FunctionBody '}'
  bool is_wrapped = function_syntax_kind == FunctionSyntaxKind::kWrapped;
  DCHECK_EQ(is_wrapped, arguments_for_wrapped_function != nullptr);
  int pos = function_token_pos == kNoSourcePosition ? peek_position()
                                                    : function_token_pos;
  DCHECK_NE(kNoSourcePosition, pos);
  // Anonymous functions were passed either the empty symbol or a null
  // handle as the function name. Remember if we were passed a non-empty
  // handle to decide whether to invoke function name inference.
  bool should_infer_name = function_name == nullptr;
  // We want a non-null handle as the function name by default. We will handle
  // the "function does not have a shared name" case later.
  if (should_infer_name) {
    function_name = ast_value_factory()->empty_string();
  }
  // This is true if we get here through CreateDynamicFunction.
  bool params_need_validation = parameters_end_pos_ != kNoSourcePosition;
  int compile_hint_position = peek_position();
  FunctionLiteral::EagerCompileHint eager_compile_hint =
      function_state_->next_function_is_likely_called() || is_wrapped ||
              params_need_validation ||
              (info()->flags().compile_hints_magic_enabled() &&
               scanner()->SawMagicCommentCompileHintsAll()) ||
              (info()->flags().compile_hints_per_function_magic_enabled() &&
               scanner()->HasPerFunctionCompileHint(compile_hint_position))
          ? FunctionLiteral::kShouldEagerCompile
          : default_eager_compile_hint();
  // Determine if the function can be parsed lazily. Lazy parsing is
  // different from lazy compilation; we need to parse more eagerly than we
  // compile.
  // We can only parse lazily if we also compile lazily. The heuristics for lazy
  // compilation are:
  // - It must not have been prohibited by the caller to Parse (some callers
  // need a full AST).
  // - The outer scope must allow lazy compilation of inner functions.
  // - The function mustn't be a function expression with an open parenthesis
  // before; we consider that a hint that the function will be called
  // immediately, and it would be a waste of time to make it lazily
  // compiled.
  // These are all things we can know at this point, without looking at the
  // function itself.
  // We separate between lazy parsing top level functions and lazy parsing inner
  // functions, because the latter needs to do more work. In particular, we need
  // to track unresolved variables to distinguish between these cases:
  // (function foo() {
  // bar = function() { return 1; }
  // })();
  // and
  // (function foo() {
  // var a = 1;
  // bar = function() { return a; }
  // })();
  // Now foo will be parsed eagerly and compiled eagerly (optimization: assume
  // parenthesis before the function means that it will be called
  // immediately). bar can be parsed lazily, but we need to parse it in a mode
  // that tracks unresolved variables.
  DCHECK_IMPLIES(parse_lazily(), info()->flags().allow_lazy_compile());
  DCHECK_IMPLIES(parse_lazily(), has_error() || allow_lazy_);
  DCHECK_IMPLIES(parse_lazily(), extension() == nullptr);
  eager_compile_hint =
      GetEmbedderCompileHint(eager_compile_hint, compile_hint_position);
  const bool is_lazy =
      eager_compile_hint == FunctionLiteral::kShouldLazyCompile;
  const bool is_top_level = AllowsLazyParsingWithoutUnresolvedVariables();
  const bool is_eager_top_level_function = !is_lazy && is_top_level;
  RCS_SCOPE(runtime_call_stats_, RuntimeCallCounterId::kParseFunctionLiteral,
            RuntimeCallStats::kThreadSpecific);
  base::ElapsedTimer timer;
  if (V8_UNLIKELY(v8_flags.log_function_events)) timer.Start();
  // Determine whether we can lazy parse the inner function. Lazy compilation
  // has to be enabled, which is either forced by overall parse flags or via a
  // ParsingModeScope.
  const bool can_preparse = parse_lazily();
  // Determine whether we can post any parallel compile tasks. Preparsing must
  // be possible, there has to be a dispatcher, and the character stream must be
  // cloneable.
  const bool can_post_parallel_task =
      can_preparse && info()->dispatcher() &&
      scanner()->stream()->can_be_cloned_for_parallel_access();
  // If parallel compile tasks are enabled, and this isn't a re-parse, enable
  // parallel compile for the subset of functions as defined by flags.
  bool should_post_parallel_task =
      can_post_parallel_task && !flags().is_reparse() &&
      ((is_eager_top_level_function &&
        flags().post_parallel_compile_tasks_for_eager_toplevel()) ||
       (is_lazy && flags().post_parallel_compile_tasks_for_lazy()));
  // Determine whether we should lazy parse the inner function. This will be
  // when either the function is lazy by inspection, or when we force it to be
  // preparsed now so that we can then post a parallel full parse & compile task
  // for it.
  const bool should_preparse =
      can_preparse && (is_lazy || should_post_parallel_task);
  ScopedPtrList<Statement> body(pointer_buffer());
  int expected_property_count = 0;
  int suspend_count = -1;
  int num_parameters = -1;
  int function_length = -1;
  bool has_duplicate_parameters = false;
  int function_literal_id = GetNextInfoId();
  ProducedPreparseData* produced_preparse_data = nullptr;
  // Inner functions will be parsed using a temporary Zone. After parsing, we
  // will migrate unresolved variable into a Scope in the main Zone.
  Zone* parse_zone = should_preparse ? &preparser_zone_ : zone();
  // This Scope lives in the main zone. We'll migrate data into that zone later.
  DeclarationScope* scope = NewFunctionScope(kind, parse_zone);
  SetLanguageMode(scope, language_mode);
  if (is_wrapped) {
    scope->set_is_wrapped_function();
  }
#ifdef DEBUG
  scope->SetScopeName(function_name);
#endif
  if (!is_wrapped && V8_UNLIKELY(!Check(Token::kLeftParen))) {
    ReportUnexpectedToken(Next());
    return nullptr;
  }
  scope->set_start_position(position());
  // Eager or lazy parse? If is_lazy_top_level_function, we'll parse
  // lazily. We'll call SkipFunction, which may decide to
  // abort lazy parsing if it suspects that wasn't a good idea. If so (in
  // which case the parser is expected to have backtracked), or if we didn't
  // try to lazy parse in the first place, we'll have to parse eagerly.
  bool did_preparse_successfully =
      should_preparse &&
      SkipFunction(function_name, kind, function_syntax_kind, scope,
                   &num_parameters, &function_length, &produced_preparse_data);
  if (!did_preparse_successfully) {
    // If skipping aborted, it rewound the scanner until before the lparen.
    // Consume it in that case.
    if (should_preparse) Consume(Token::kLeftParen);
    should_post_parallel_task = false;
    ParseFunction(&body, function_name, pos, kind, function_syntax_kind, scope,
                  &num_parameters, &function_length, &has_duplicate_parameters,
                  &expected_property_count, &suspend_count,
                  arguments_for_wrapped_function);
  }
  if (V8_UNLIKELY(v8_flags.log_function_events)) {
    double ms = timer.Elapsed().InMillisecondsF();
    const char* event_name =
        should_preparse
            ? (is_top_level ? "preparse-no-resolution" : "preparse-resolution")
            : "full-parse";
    v8_file_logger_->FunctionEvent(
        event_name, flags().script_id(), ms, scope->start_position(),
        scope->end_position(),
        reinterpret_cast<const char*>(function_name->raw_data()),
        function_name->byte_length(), function_name->is_one_byte());
  }
#ifdef V8_RUNTIME_CALL_STATS
  if (did_preparse_successfully && runtime_call_stats_ &&
      V8_UNLIKELY(TracingFlags::is_runtime_stats_enabled())) {
    runtime_call_stats_->CorrectCurrentCounterId(
        RuntimeCallCounterId::kPreParseWithVariableResolution,
        RuntimeCallStats::kThreadSpecific);
  }
#endif // V8_RUNTIME_CALL_STATS
  // Validate function name. We can do this only after parsing the function,
  // since the function can declare itself strict.
  language_mode = scope->language_mode();
  CheckFunctionName(language_mode, function_name, function_name_validity,
                    function_name_location);
  if (is_strict(language_mode)) {
    CheckStrictOctalLiteral(scope->start_position(), scope->end_position());
  }
  FunctionLiteral::ParameterFlag duplicate_parameters =
      has_duplicate_parameters ? FunctionLiteral::kHasDuplicateParameters
                               : FunctionLiteral::kNoDuplicateParameters;
  // Note that the FunctionLiteral needs to be created in the main Zone again.
  FunctionLiteral* function_literal = factory()->NewFunctionLiteral(
      function_name, scope, body, expected_property_count, num_parameters,
      function_length, duplicate_parameters, function_syntax_kind,
      eager_compile_hint, pos, true, function_literal_id,
      produced_preparse_data);
  function_literal->set_function_token_position(function_token_pos);
  function_literal->set_suspend_count(suspend_count);
  RecordFunctionLiteralSourceRange(function_literal);
  if (should_post_parallel_task && !has_error()) {
    function_literal->set_should_parallel_compile();
  }
  if (should_infer_name) {
    fni_.AddFunction(function_literal);
  }
  return function_literal;
}
References allow_lazy_, AllowsLazyParsingWithoutUnresolvedVariables(), v8::internal::AstRawString::byte_length(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NE, v8::internal::ParseInfo::dispatcher(), v8::base::ElapsedTimer::Elapsed(), v8::internal::Scope::end_position(), extension(), v8::internal::ParseInfo::flags(), v8::internal::flags, v8::internal::function_literal_id, GetEmbedderCompileHint(), v8::internal::has_duplicate_parameters, info(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::AstRawString::is_one_byte(), v8::internal::is_strict(), v8::internal::FunctionLiteral::kHasDuplicateParameters, v8::internal::FunctionLiteral::kNoDuplicateParameters, v8::internal::kNoSourcePosition, v8::internal::FunctionLiteral::kShouldEagerCompile, v8::internal::FunctionLiteral::kShouldLazyCompile, v8::internal::kWrapped, v8::internal::Scope::language_mode(), v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), parameters_end_pos_, parse_lazily(), ParseFunction(), preparser_zone_, v8::internal::AstRawString::raw_data(), RCS_SCOPE, RecordFunctionLiteralSourceRange(), v8::internal::FunctionLiteral::set_function_token_position(), v8::internal::Scope::set_is_wrapped_function(), v8::internal::FunctionLiteral::set_should_parallel_compile(), v8::internal::Scope::set_start_position(), v8::internal::FunctionLiteral::set_suspend_count(), SetLanguageMode(), SkipFunction(), v8::base::ElapsedTimer::Start(), v8::internal::Scope::start_position(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by DoParseFunction(), and ParseWrapped().
ParseGeneratorFunctionBody()
void v8::internal::Parser::ParseGeneratorFunctionBody (int pos, FunctionKind kind, ScopedPtrList< Statement > * body) [private]
Definition at line 2189 of file parser.cc.
                                                                        {
  // For ES6 Generators, we just prepend the initial yield.
  Expression* initial_yield = BuildInitialYield(pos, kind);
  body->Add(
      factory()->NewExpressionStatement(initial_yield, kNoSourcePosition));
  ParseStatementList(body, Token::kRightBrace);
}
References v8::internal::ScopedList< T, TBacking >::Add(), BuildInitialYield(), and v8::internal::kNoSourcePosition.
ParseImportDeclaration()
void v8::internal::Parser::ParseImportDeclaration () [private]
Definition at line 1543 of file parser.cc.
                                    {
  // ImportDeclaration :
  // 'import' ImportClause 'from' ModuleSpecifier ';'
  // 'import' ModuleSpecifier ';'
  // 'import' ImportClause 'from' ModuleSpecifier [no LineTerminator here]
  // AssertClause ';'
  // 'import' ModuleSpecifier [no LineTerminator here] AssertClause';'
  // 'import' 'source' ImportedBinding 'from' ModuleSpecifier ';'
  //
  // ImportClause :
  // ImportedDefaultBinding
  // NameSpaceImport
  // NamedImports
  // ImportedDefaultBinding ',' NameSpaceImport
  // ImportedDefaultBinding ',' NamedImports
  //
  // NameSpaceImport :
  // '*' 'as' ImportedBinding
  int pos = peek_position();
  Expect(Token::kImport);
  Token::Value tok = peek();
  // 'import' ModuleSpecifier ';'
  if (tok == Token::kString) {
    Scanner::Location specifier_loc = scanner()->peek_location();
    const AstRawString* module_specifier = ParseModuleSpecifier();
    const ImportAttributes* import_attributes = ParseImportWithOrAssertClause();
    ExpectSemicolon();
    module()->AddEmptyImport(module_specifier, import_attributes, specifier_loc,
                             zone());
    return;
  }
  // Parse ImportedDefaultBinding or 'source' ImportedBinding if present.
  const AstRawString* import_default_binding = nullptr;
  Scanner::Location import_default_binding_loc;
  ModuleImportPhase import_phase = ModuleImportPhase::kEvaluation;
  if (tok != Token::kMul && tok != Token::kLeftBrace) {
    if (v8_flags.js_source_phase_imports &&
        PeekContextualKeyword(ast_value_factory()->source_string()) &&
        PeekAhead() == Token::kIdentifier &&
        PeekAheadAhead() == Token::kIdentifier) {
      Consume(Token::kIdentifier);
      import_phase = ModuleImportPhase::kSource;
    }
    import_default_binding = ParseNonRestrictedIdentifier();
    import_default_binding_loc = scanner()->location();
    DeclareUnboundVariable(import_default_binding, VariableMode::kConst,
                           kNeedsInitialization, pos);
  }
  // Parse NameSpaceImport or NamedImports if present.
  const AstRawString* module_namespace_binding = nullptr;
  Scanner::Location module_namespace_binding_loc;
  const ZonePtrList<const NamedImport>* named_imports = nullptr;
  if (import_phase == ModuleImportPhase::kEvaluation &&
      (import_default_binding == nullptr || Check(Token::kComma))) {
    switch (peek()) {
      case Token::kMul: {
        Consume(Token::kMul);
        ExpectContextualKeyword(ast_value_factory()->as_string());
        module_namespace_binding = ParseNonRestrictedIdentifier();
        module_namespace_binding_loc = scanner()->location();
        DeclareUnboundVariable(module_namespace_binding, VariableMode::kConst,
                               kCreatedInitialized, pos);
        break;
      }
      case Token::kLeftBrace:
        named_imports = ParseNamedImports(pos);
        break;
      default:
        ReportUnexpectedToken(scanner()->current_token());
        return;
    }
  }
  ExpectContextualKeyword(ast_value_factory()->from_string());
  Scanner::Location specifier_loc = scanner()->peek_location();
  const AstRawString* module_specifier = ParseModuleSpecifier();
  // TODO(42204365): Enable import attributes with source phase import once
  // specified.
  const ImportAttributes* import_attributes =
      import_phase == ModuleImportPhase::kEvaluation
          ? ParseImportWithOrAssertClause()
          : zone()->New<ImportAttributes>(zone());
  ExpectSemicolon();
  // Now that we have all the information, we can make the appropriate
  // declarations.
  // TODO(neis): Would prefer to call DeclareVariable for each case below rather
  // than above and in ParseNamedImports, but then a possible error message
  // would point to the wrong location. Maybe have a DeclareAt version of
  // Declare that takes a location?
  if (module_namespace_binding != nullptr) {
    DCHECK_EQ(ModuleImportPhase::kEvaluation, import_phase);
    module()->AddStarImport(module_namespace_binding, module_specifier,
                            import_attributes, module_namespace_binding_loc,
                            specifier_loc, zone());
  }
  if (import_default_binding != nullptr) {
    DCHECK_IMPLIES(import_phase == ModuleImportPhase::kSource,
                   v8_flags.js_source_phase_imports);
    module()->AddImport(ast_value_factory()->default_string(),
                        import_default_binding, module_specifier, import_phase,
                        import_attributes, import_default_binding_loc,
                        specifier_loc, zone());
  }
  if (named_imports != nullptr) {
    DCHECK_EQ(ModuleImportPhase::kEvaluation, import_phase);
    if (named_imports->length() == 0) {
      module()->AddEmptyImport(module_specifier, import_attributes,
                               specifier_loc, zone());
    } else {
      for (const NamedImport* import : *named_imports) {
        module()->AddImport(import->import_name, import->local_name,
                            module_specifier, import_phase, import_attributes,
                            import->location, specifier_loc, zone());
      }
    }
  }
}
References DCHECK_EQ, DCHECK_IMPLIES, DeclareUnboundVariable(), v8::internal::kConst, v8::internal::kCreatedInitialized, v8::kEvaluation, v8::internal::kNeedsInitialization, v8::kSource, v8::internal::ZoneList< T >::length(), ParseImportWithOrAssertClause(), ParseModuleSpecifier(), ParseNamedImports(), and v8::internal::v8_flags.
Referenced by ParseModuleItem().
ParseImportWithOrAssertClause()
ImportAttributes * v8::internal::Parser::ParseImportWithOrAssertClause () [private]
Definition at line 1488 of file parser.cc.
                                                        {
  // WithClause :
  // with '{' '}'
  // with '{' WithEntries ','? '}'
  // WithEntries :
  // LiteralPropertyName
  // LiteralPropertyName ':' StringLiteral , WithEntries
  auto import_attributes = zone()->New<ImportAttributes>(zone());
  if (v8_flags.harmony_import_attributes && Check(Token::kWith)) {
    // 'with' keyword consumed
  } else {
    return import_attributes;
  }
  Expect(Token::kLeftBrace);
  while (peek() != Token::kRightBrace) {
    const AstRawString* attribute_key =
        Check(Token::kString) ? GetSymbol() : ParsePropertyName();
    Scanner::Location location = scanner()->location();
    Expect(Token::kColon);
    Expect(Token::kString);
    const AstRawString* attribute_value = GetSymbol();
    // Set the location to the whole "key: 'value'"" string, so that it makes
    // sense both for errors due to the key and errors due to the value.
    location.end_pos = scanner()->location().end_pos;
    auto result = import_attributes->insert(std::make_pair(
        attribute_key, std::make_pair(attribute_value, location)));
    if (!result.second) {
      // It is a syntax error if two WithEntries have the same key.
      ReportMessageAt(location, MessageTemplate::kImportAttributesDuplicateKey,
                      attribute_key);
      break;
    }
    if (peek() == Token::kRightBrace) break;
    if (V8_UNLIKELY(!Check(Token::kComma))) {
      ReportUnexpectedToken(Next());
      break;
    }
  }
  Expect(Token::kRightBrace);
  return import_attributes;
}
References v8::internal::Scanner::Location::end_pos, GetSymbol(), v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), v8::base::internal::result, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by ParseExportDeclaration(), ParseExportStar(), and ParseImportDeclaration().
ParseModuleItem()
Statement * v8::internal::Parser::ParseModuleItem () [private]
Definition at line 1295 of file parser.cc.
                                   {
  // ecma262/#prod-ModuleItem
  // ModuleItem :
  // ImportDeclaration
  // ExportDeclaration
  // StatementListItem
  Token::Value next = peek();
  if (next == Token::kExport) {
    return ParseExportDeclaration();
  }
  if (next == Token::kImport) {
    // We must be careful not to parse a dynamic import expression as an import
    // declaration. Same for import.meta expressions.
    Token::Value peek_ahead = PeekAhead();
    if (peek_ahead != Token::kLeftParen && peek_ahead != Token::kPeriod) {
      ParseImportDeclaration();
      return factory()->EmptyStatement();
    }
  }
  return ParseStatementListItem();
}
References ParseExportDeclaration(), and ParseImportDeclaration().
Referenced by ParseModuleItemList().
ParseModuleItemList()
void v8::internal::Parser::ParseModuleItemList (ScopedPtrList< Statement > * body) [private]
Definition at line 1321 of file parser.cc.
                                                               {
  // ecma262/#prod-Module
  // Module :
  // ModuleBody?
  //
  // ecma262/#prod-ModuleItemList
  // ModuleBody :
  // ModuleItem*
  DCHECK(scope()->is_module_scope());
  while (peek() != Token::kEos) {
    Statement* stat = ParseModuleItem();
    if (stat == nullptr) return;
    if (stat->IsEmptyStatement()) continue;
    body->Add(stat);
  }
}
References v8::internal::ScopedList< T, TBacking >::Add(), v8::internal::DCHECK(), and ParseModuleItem().
Referenced by DoParseProgram().
ParseModuleSpecifier()
const AstRawString * v8::internal::Parser::ParseModuleSpecifier () [private]
Definition at line 1339 of file parser.cc.
                                                 {
  // ModuleSpecifier :
  // StringLiteral
  Expect(Token::kString);
  return GetSymbol();
}
References GetSymbol().
Referenced by ParseExportDeclaration(), ParseExportStar(), and ParseImportDeclaration().
ParseNamedImports()
ZonePtrList< const Parser::NamedImport > * v8::internal::Parser::ParseNamedImports (int pos) [private]
Definition at line 1435 of file parser.cc.
                                                                       {
  // NamedImports :
  // '{' '}'
  // '{' ImportsList '}'
  // '{' ImportsList ',' '}'
  //
  // ImportsList :
  // ImportSpecifier
  // ImportsList ',' ImportSpecifier
  //
  // ImportSpecifier :
  // BindingIdentifier
  // IdentifierName 'as' BindingIdentifier
  // ModuleExportName 'as' BindingIdentifier
  Expect(Token::kLeftBrace);
  auto result = zone()->New<ZonePtrList<const NamedImport>>(1, zone());
  while (peek() != Token::kRightBrace) {
    const AstRawString* import_name = ParseExportSpecifierName();
    const AstRawString* local_name = import_name;
    Scanner::Location location = scanner()->location();
    // In the presence of 'as', the left-side of the 'as' can
    // be any IdentifierName. But without 'as', it must be a valid
    // BindingIdentifier.
    if (CheckContextualKeyword(ast_value_factory()->as_string())) {
      local_name = ParsePropertyName();
    }
    if (!Token::IsValidIdentifier(scanner()->current_token(),
                                  LanguageMode::kStrict, false,
                                  flags().is_module())) {
      ReportMessage(MessageTemplate::kUnexpectedReserved);
      return nullptr;
    } else if (IsEvalOrArguments(local_name)) {
      ReportMessage(MessageTemplate::kStrictEvalArguments);
      return nullptr;
    }
    DeclareUnboundVariable(local_name, VariableMode::kConst,
                           kNeedsInitialization, position());
    NamedImport* import =
        zone()->New<NamedImport>(import_name, local_name, location);
    result->Add(import, zone());
    if (peek() == Token::kRightBrace) break;
    Expect(Token::kComma);
  }
  Expect(Token::kRightBrace);
  return result;
}
References DeclareUnboundVariable(), v8::internal::flags, IsEvalOrArguments(), v8::internal::Token::IsValidIdentifier(), v8::internal::kConst, v8::internal::kNeedsInitialization, v8::internal::kStrict, ParseExportSpecifierName(), and v8::base::internal::result.
Referenced by ParseImportDeclaration().
ParseOnBackground()
void v8::internal::Parser::ParseOnBackground (LocalIsolate * isolate, ParseInfo * info, DirectHandle< Script > script, int start_position, int end_position, int function_literal_id)
Definition at line 3502 of file parser.cc.
                                                                          {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kParseProgram,
            RuntimeCallStats::CounterMode::kThreadSpecific);
  parsing_on_main_thread_ = false;
  DCHECK_NULL(info->literal());
  FunctionLiteral* result = nullptr;
  // We can park the isolate while parsing, it doesn't need to allocate or
  // access the main thread.
  isolate->ParkIfOnBackgroundAndExecute([this, start_position, end_position,
                                         function_literal_id, info, &result]() {
    scanner_.Initialize();
    DCHECK(original_scope_);
    // When streaming, we don't know the length of the source until we have
    // parsed it. The raw data can be UTF-8, so we wouldn't know the source
    // length until we have decoded it anyway even if we knew the raw data
    // length (which we don't). We work around this by storing all the scopes
    // which need their end position set at the end of the script (the top scope
    // and possible eval scopes) and set their end position after we know the
    // script length.
    if (flags().is_toplevel()) {
      DCHECK_EQ(start_position, 0);
      DCHECK_EQ(end_position, 0);
      DCHECK_EQ(function_literal_id, kFunctionLiteralIdTopLevel);
      result = DoParseProgram(/* isolate = */ nullptr, info);
    } else {
      std::optional<ClassScope::HeritageParsingScope> heritage;
      if (V8_UNLIKELY(flags().private_name_lookup_skips_outer_class() &&
                      original_scope_->is_class_scope())) {
        // If the function skips the outer class and the outer scope is a class,
        // the function is in heritage position. Otherwise the function scope's
        // skip bit will be correctly inherited from the outer scope.
        heritage.emplace(original_scope_->AsClassScope());
      }
      result = DoParseFunction(/* isolate = */ nullptr, info, start_position,
                               end_position, function_literal_id,
                               info->function_name());
    }
    if (result == nullptr) return;
    MaybeProcessSourceRanges(info, result, stack_limit_);
  });
  // We need to unpark by now though, to be able to internalize.
  if (flags().is_toplevel()) {
    HandleDebugMagicComments(isolate, script);
  }
  if (result == nullptr) return;
  PostProcessParseResult(isolate, info, result);
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, DoParseFunction(), DoParseProgram(), v8::internal::flags, v8::internal::function_literal_id, v8::internal::ParseInfo::function_name(), HandleDebugMagicComments(), info(), v8::internal::Scanner::Initialize(), v8::internal::kFunctionLiteralIdTopLevel, v8::internal::ParseInfo::literal(), v8::internal::anonymous_namespace{parser.cc}::MaybeProcessSourceRanges(), v8::internal::LocalIsolate::ParkIfOnBackgroundAndExecute(), PostProcessParseResult(), RCS_SCOPE, v8::base::internal::result, scanner_, v8::internal::script, and V8_UNLIKELY.
Referenced by v8::internal::BackgroundCompileTask::Run().
ParseProgram()
void v8::internal::Parser::ParseProgram (Isolate * isolate, DirectHandle< Script > script, ParseInfo * info, MaybeDirectHandle< ScopeInfo > maybe_outer_scope_info) [private]
Definition at line 694 of file parser.cc.
                                                                               {
  DCHECK_EQ(script->id(), flags().script_id());
  // It's OK to use the Isolate & counters here, since this function is only
  // called in the main thread.
  DCHECK(parsing_on_main_thread_);
  RCS_SCOPE(runtime_call_stats_, flags().is_eval()
                                     ? RuntimeCallCounterId::kParseEval
                                     : RuntimeCallCounterId::kParseProgram);
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"), "V8.ParseProgram");
  base::ElapsedTimer timer;
  if (V8_UNLIKELY(v8_flags.log_function_events)) timer.Start();
  // Initialize parser state.
  DeserializeScopeChain(isolate, info, maybe_outer_scope_info,
                        Scope::DeserializationMode::kIncludingVariables);
  DCHECK_EQ(script->is_wrapped(), info->is_wrapped_as_function());
  if (script->is_wrapped()) {
    maybe_wrapped_arguments_ = handle(script->wrapped_arguments(), isolate);
  }
  scanner_.Initialize();
  FunctionLiteral* result = DoParseProgram(isolate, info);
  HandleDebugMagicComments(isolate, script);
  if (result == nullptr) return;
  MaybeProcessSourceRanges(info, result, stack_limit_);
  PostProcessParseResult(isolate, info, result);
  if (V8_UNLIKELY(v8_flags.log_function_events)) {
    double ms = timer.Elapsed().InMillisecondsF();
    const char* event_name = "parse-eval";
    int start = -1;
    int end = -1;
    if (!flags().is_eval()) {
      event_name = "parse-script";
      start = 0;
      end = Cast<String>(script->source())->length();
    }
    LOG(isolate,
        FunctionEvent(event_name, flags().script_id(), ms, start, end, "", 0));
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, DeserializeScopeChain(), DoParseProgram(), v8::base::ElapsedTimer::Elapsed(), v8::internal::compiler::end(), v8::internal::flags, v8::internal::handle(), HandleDebugMagicComments(), info(), v8::internal::Scanner::Initialize(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::ParseInfo::is_wrapped_as_function(), v8::internal::Scope::kIncludingVariables, LOG, maybe_wrapped_arguments_, v8::internal::anonymous_namespace{parser.cc}::MaybeProcessSourceRanges(), PostProcessParseResult(), RCS_SCOPE, v8::base::internal::result, scanner_, v8::internal::script, v8::base::ElapsedTimer::Start(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::parsing::ParseProgram().
ParseREPLProgram()
void v8::internal::Parser::ParseREPLProgram (ParseInfo * info, ScopedPtrList< Statement > * body, DeclarationScope * scope) [private]
Definition at line 937 of file parser.cc.
                                                       {
  // REPL scripts are handled nearly the same way as the body of an async
  // function. The difference is the value used to resolve the async
  // promise.
  // For a REPL script this is the completion value of the
  // script instead of the expression of some "return" statement. The
  // completion value of the script is obtained by manually invoking
  // the {Rewriter} which will return a VariableProxy referencing the
  // result.
  DCHECK(flags().is_repl_mode());
  this->scope()->SetLanguageMode(info->language_mode());
  PrepareGeneratorVariables();
  BlockT block = impl()->NullBlock();
  {
    StatementListT statements(pointer_buffer());
    ParseStatementList(&statements, Token::kEos);
    block = factory()->NewBlock(true, statements);
  }
  if (has_error()) return;
  bool has_stack_overflow = false;
  std::optional<VariableProxy*> maybe_result = Rewriter::RewriteBody(
      info, scope, block->statements(), &has_stack_overflow);
  if (!maybe_result) {
    if (has_stack_overflow) {
      // Propagate stack overflow state from Rewriter to parser.
      set_stack_overflow();
    }
    return;
  }
  Expression* result_value =
      *maybe_result ? static_cast<Expression*>(*maybe_result)
                    : factory()->NewUndefinedLiteral(kNoSourcePosition);
  Expression* wrapped_result_value = WrapREPLResult(result_value);
  block->statements()->Add(factory()->NewAsyncReturnStatement(
                               wrapped_result_value, kNoSourcePosition),
                           zone());
  DCHECK(!info->pending_error_handler()->stack_overflow());
  body->Add(block);
}
References v8::internal::ScopedList< T, TBacking >::Add(), v8::internal::DCHECK(), v8::internal::flags, wasm::impl(), info(), v8::internal::kNoSourcePosition, v8::internal::ParseInfo::language_mode(), v8::internal::ParseInfo::pending_error_handler(), PrepareGeneratorVariables(), v8::internal::Rewriter::RewriteBody(), v8::internal::Scope::SetLanguageMode(), v8::internal::PendingCompilationErrorHandler::stack_overflow(), and WrapREPLResult().
Referenced by DoParseProgram().
ParseWrapped()
void v8::internal::Parser::ParseWrapped (Isolate * isolate, ParseInfo * info, ScopedPtrList< Statement > * body, DeclarationScope * scope, Zone * zone) [private]
Definition at line 909 of file parser.cc.
                                                                     {
  DCHECK(parsing_on_main_thread_);
  DCHECK(info->is_wrapped_as_function());
  ParsingModeScope parsing_mode(this, PARSE_EAGERLY);
  // Set function and block state for the outer eval scope.
  DCHECK(outer_scope->is_eval_scope());
  FunctionState function_state(&function_state_, &scope_, outer_scope);
  const AstRawString* function_name = nullptr;
  Scanner::Location location(0, 0);
  ZonePtrList<const AstRawString>* arguments_for_wrapped_function =
      PrepareWrappedArguments(isolate, info, zone);
  FunctionLiteral* function_literal =
      ParseFunctionLiteral(function_name, location, kSkipFunctionNameCheck,
                           FunctionKind::kNormalFunction, kNoSourcePosition,
                           FunctionSyntaxKind::kWrapped, LanguageMode::kSloppy,
                           arguments_for_wrapped_function);
  Statement* return_statement =
      factory()->NewReturnStatement(function_literal, kNoSourcePosition);
  body->Add(return_statement);
}
References v8::internal::ScopedList< T, TBacking >::Add(), v8::internal::DCHECK(), info(), v8::internal::Scope::is_eval_scope(), v8::internal::ParseInfo::is_wrapped_as_function(), v8::internal::kNormalFunction, v8::internal::kNoSourcePosition, v8::internal::kSkipFunctionNameCheck, v8::internal::kSloppy, v8::internal::kWrapped, PARSE_EAGERLY, ParseFunctionLiteral(), and PrepareWrappedArguments().
Referenced by DoParseProgram().
ParsingDynamicFunctionDeclaration()
bool v8::internal::Parser::ParsingDynamicFunctionDeclaration () const [inline], [private]
Definition at line 925 of file parser.h.
                                                           {
    return parameters_end_pos_ != kNoSourcePosition;
  }
References v8::internal::kNoSourcePosition.
ParsingExtension()
bool v8::internal::Parser::ParsingExtension () const [inline], [private]
Definition at line 616 of file parser.h.
{ return extension() != nullptr; }
Referenced by NewV8Intrinsic().
PostProcessParseResult()
template<typename IsolateT >
template void v8::internal::Parser::PostProcessParseResult (IsolateT * isolate, ParseInfo * info, FunctionLiteral * literal) [private]
Definition at line 856 of file parser.cc.
                                                              {
  DCHECK_NOT_NULL(literal);
  info->set_literal(literal);
  info->set_language_mode(literal->language_mode());
  if (info->flags().is_eval()) {
    info->set_allow_eval_cache(allow_eval_cache());
  }
  info->ast_value_factory()->Internalize(isolate);
  {
    RCS_SCOPE(info->runtime_call_stats(), RuntimeCallCounterId::kCompileAnalyse,
              RuntimeCallStats::kThreadSpecific);
    bool has_stack_overflow = false;
    if (!Rewriter::Rewrite(info, &has_stack_overflow) ||
        !DeclarationScope::Analyze(info)) {
      // Null out the literal to indicate that something failed.
      info->set_literal(nullptr);
      if (has_stack_overflow) {
        // Propagate stack overflow state from Rewriter to parser.
        set_stack_overflow();
      }
      return;
    }
  }
}
References v8::internal::DeclarationScope::Analyze(), v8::internal::ParseInfo::ast_value_factory(), DCHECK_NOT_NULL, v8::internal::ParseInfo::flags(), info(), v8::internal::AstValueFactory::Internalize(), v8::internal::FunctionLiteral::language_mode(), RCS_SCOPE, v8::internal::Rewriter::Rewrite(), v8::internal::ParseInfo::runtime_call_stats(), v8::internal::ParseInfo::set_allow_eval_cache(), v8::internal::ParseInfo::set_language_mode(), and v8::internal::ParseInfo::set_literal().
Referenced by ParseFunction(), ParseOnBackground(), and ParseProgram().
PrepareGeneratorVariables()
void v8::internal::Parser::PrepareGeneratorVariables () [private]
Definition at line 2667 of file parser.cc.
                                       {
  // Calling a generator returns a generator object. That object is stored
  // in a temporary variable, a definition that is used by "yield"
  // expressions.
  function_state_->scope()->DeclareGeneratorObjectVar(
      ast_value_factory()->dot_generator_object_string());
}
Referenced by DoParseProgram(), and ParseREPLProgram().
PrepareWrappedArguments()
ZonePtrList< const AstRawString > * v8::internal::Parser::PrepareWrappedArguments (Isolate * isolate, ParseInfo * info, Zone * zone) [private]
Definition at line 891 of file parser.cc.
                                                   {
  DCHECK(parsing_on_main_thread_);
  DCHECK_NOT_NULL(isolate);
  DirectHandle<FixedArray> arguments =
      maybe_wrapped_arguments_.ToHandleChecked();
  int arguments_length = arguments->length();
  ZonePtrList<const AstRawString>* arguments_for_wrapped_function =
      zone->New<ZonePtrList<const AstRawString>>(arguments_length, zone);
  for (int i = 0; i < arguments_length; i++) {
    const AstRawString* argument_string = ast_value_factory()->GetString(
        Cast<String>(arguments->get(i)),
        SharedStringAccessGuardIfNeeded(isolate));
    arguments_for_wrapped_function->Add(argument_string, zone);
  }
  return arguments_for_wrapped_function;
}
References v8::internal::ZoneList< T >::Add(), v8::internal::DCHECK(), DCHECK_NOT_NULL, maybe_wrapped_arguments_, and v8::internal::Zone::New().
Referenced by DoParseFunction(), and ParseWrapped().
preparse_data_buffer()
std::vector<uint8_t>* v8::internal::Parser::preparse_data_buffer () [inline], [private]
Definition at line 1107 of file parser.h.
                                             {
    return &preparse_data_buffer_;
  }
Referenced by v8::internal::PreparseDataBuilder::SaveScopeAllocationData().
PreParserIdentifierToAstRawString()
const AstRawString* v8::internal::Parser::PreParserIdentifierToAstRawString (const PreParserIdentifier & arg) [inline], [private]
Definition at line 732 of file parser.h.
                                      {
    // This method definition is only needed due to an MSVC oddity that
    // instantiates the method despite it being unused. See crbug.com/v8/12266 .
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
PushEnclosingName()
void v8::internal::Parser::PushEnclosingName (const AstRawString * name) [inline], [private]
Definition at line 666 of file parser.h.
                                                             {
    fni_.PushEnclosingName(name);
  }
References v8::internal::name.
PushLiteralName()
void v8::internal::Parser::PushLiteralName (const AstRawString * id) [inline], [private]
Definition at line 650 of file parser.h.
                                                         {
    fni_.PushLiteralName(id);
  }
PushPropertyName()
void v8::internal::Parser::PushPropertyName (Expression * expression) [inline], [private]
Definition at line 658 of file parser.h.
                                                          {
    if (expression->IsPropertyName()) {
      fni_.PushLiteralName(expression->AsLiteral()->AsRawPropertyName());
    } else {
      fni_.PushLiteralName(ast_value_factory()->computed_string());
    }
  }
References v8::internal::Expression::IsPropertyName().
PushVariableName()
void v8::internal::Parser::PushVariableName (const AstRawString * id) [inline], [private]
Definition at line 654 of file parser.h.
                                                          {
    fni_.PushVariableName(id);
  }
RecordBinaryOperationSourceRange()
void v8::internal::Parser::RecordBinaryOperationSourceRange (Expression * node, const SourceRange & right_range) [inline], [private]
Definition at line 1010 of file parser.h.
                                                        {
    if (source_range_map_ == nullptr) return;
    source_range_map_->Insert(
        node->AsBinaryOperation(),
        zone()->New<BinaryOperationSourceRanges>(right_range));
  }
RecordBlockSourceRange()
void v8::internal::Parser::RecordBlockSourceRange (Block * node, int32_t continuation_position) [inline], [private]
Definition at line 955 of file parser.h.
                                                                       {
    if (source_range_map_ == nullptr) return;
    source_range_map_->Insert(
        node, zone()->New<BlockSourceRanges>(continuation_position));
  }
RecordCaseClauseSourceRange()
void v8::internal::Parser::RecordCaseClauseSourceRange (CaseClause * node, const SourceRange & body_range) [inline], [private]
Definition at line 962 of file parser.h.
                                                                            {
    if (source_range_map_ == nullptr) return;
    source_range_map_->Insert(node,
                              zone()->New<CaseClauseSourceRanges>(body_range));
  }
RecordConditionalSourceRange()
void v8::internal::Parser::RecordConditionalSourceRange (Expression * node, const SourceRange & then_range, const SourceRange & else_range) [inline], [private]
Definition at line 996 of file parser.h.
                                                                             {
    if (source_range_map_ == nullptr) return;
    source_range_map_->Insert(
        node->AsConditional(),
        zone()->New<ConditionalSourceRanges>(then_range, else_range));
  }
RecordExpressionSourceRange()
void v8::internal::Parser::RecordExpressionSourceRange (Expression * node, const SourceRange & right_range) [inline], [private]
Definition at line 1043 of file parser.h.
                                                                             {
    if (source_range_map_ == nullptr) return;
    source_range_map_->Insert(node,
                              zone()->New<ExpressionSourceRanges>(right_range));
  }
RecordFunctionLiteralSourceRange()
void v8::internal::Parser::RecordFunctionLiteralSourceRange (FunctionLiteral * node) [inline], [private]
Definition at line 1005 of file parser.h.
                                                                         {
    if (source_range_map_ == nullptr) return;
    source_range_map_->Insert(node, zone()->New<FunctionLiteralSourceRanges>());
  }
Referenced by CreateInitializerFunction(), DoParseProgram(), and ParseFunctionLiteral().
RecordIfStatementSourceRange()
void v8::internal::Parser::RecordIfStatementSourceRange (Statement * node, const SourceRange & then_range, const SourceRange & else_range) [inline], [private]
Definition at line 1026 of file parser.h.
                                                                             {
    if (source_range_map_ == nullptr) return;
    source_range_map_->Insert(
        node->AsIfStatement(),
        zone()->New<IfStatementSourceRanges>(then_range, else_range));
  }
RecordIterationStatementSourceRange()
void v8::internal::Parser::RecordIterationStatementSourceRange (IterationStatement * node, const SourceRange & body_range) [inline], [private]
Definition at line 1035 of file parser.h.
                                                               {
    if (source_range_map_ == nullptr) return;
    source_range_map_->Insert(
        node, zone()->New<IterationStatementSourceRanges>(body_range));
  }
RecordJumpStatementSourceRange()
void v8::internal::Parser::RecordJumpStatementSourceRange (Statement * node, int32_t continuation_position) [inline], [private]
Definition at line 1018 of file parser.h.
                                                                               {
    if (source_range_map_ == nullptr) return;
    source_range_map_->Insert(
        static_cast<JumpStatement*>(node),
        zone()->New<JumpStatementSourceRanges>(continuation_position));
  }
RecordSuspendSourceRange()
void v8::internal::Parser::RecordSuspendSourceRange (Expression * node, int32_t continuation_position) [inline], [private]
Definition at line 1050 of file parser.h.
                                                                         {
    if (source_range_map_ == nullptr) return;
    source_range_map_->Insert(
        static_cast<Suspend*>(node),
        zone()->New<SuspendSourceRanges>(continuation_position));
  }
RecordSwitchStatementSourceRange()
void v8::internal::Parser::RecordSwitchStatementSourceRange (Statement * node, int32_t continuation_position) [inline], [private]
Definition at line 1058 of file parser.h.
                                                      {
    if (source_range_map_ == nullptr) return;
    source_range_map_->Insert(
        node->AsSwitchStatement(),
        zone()->New<SwitchStatementSourceRanges>(continuation_position));
  }
RecordThrowSourceRange()
void v8::internal::Parser::RecordThrowSourceRange (Statement * node, int32_t continuation_position) [inline], [private]
Definition at line 1066 of file parser.h.
                                                                       {
    if (source_range_map_ == nullptr) return;
    ExpressionStatement* expr_stmt = static_cast<ExpressionStatement*>(node);
    Throw* throw_expr = expr_stmt->expression()->AsThrow();
    source_range_map_->Insert(
        throw_expr, zone()->New<ThrowSourceRanges>(continuation_position));
  }
References v8::internal::ExpressionStatement::expression().
RecordTryCatchStatementSourceRange()
void v8::internal::Parser::RecordTryCatchStatementSourceRange (TryCatchStatement * node, const SourceRange & body_range) [inline], [private]
Definition at line 1075 of file parser.h.
                                                              {
    if (source_range_map_ == nullptr) return;
    source_range_map_->Insert(
        node, zone()->New<TryCatchStatementSourceRanges>(body_range));
  }
Referenced by RewriteTryStatement().
RecordTryFinallyStatementSourceRange()
void v8::internal::Parser::RecordTryFinallyStatementSourceRange (TryFinallyStatement * node, const SourceRange & body_range) [inline], [private]
Definition at line 1082 of file parser.h.
                                                                {
    if (source_range_map_ == nullptr) return;
    source_range_map_->Insert(
        node, zone()->New<TryFinallyStatementSourceRanges>(body_range));
  }
Referenced by RewriteTryStatement().
ReindexArrowFunctionFormalParameters()
void v8::internal::Parser::ReindexArrowFunctionFormalParameters (ParserFormalParameters * parameters) [private]
Definition at line 2644 of file parser.cc.
                                        {
  // Make space for the arrow function above the formal parameters.
  AstFunctionLiteralIdReindexer reindexer(stack_limit_, 1);
  for (auto p : parameters->params) {
    if (p->pattern != nullptr) reindexer.Reindex(p->pattern);
    if (p->initializer() != nullptr) {
      reindexer.Reindex(p->initializer());
    }
    if (reindexer.HasStackOverflow()) {
      set_stack_overflow();
      return;
    }
  }
}
References v8::internal::ParserFormalParameters::params, and v8::internal::AstFunctionLiteralIdReindexer::Reindex().
ReindexComputedMemberName()
void v8::internal::Parser::ReindexComputedMemberName (Expression * computed_name) [private]
Definition at line 2660 of file parser.cc.
                                                                {
  // Make space for the member initializer function above the computed property
  // name.
  AstFunctionLiteralIdReindexer reindexer(stack_limit_, 1);
  reindexer.Reindex(computed_name);
}
References v8::internal::AstFunctionLiteralIdReindexer::Reindex().
ReportUnexpectedTokenAt()
void v8::internal::Parser::ReportUnexpectedTokenAt (Scanner::Location location, Token::Value token, MessageTemplate message = MessageTemplate::kUnexpectedToken) [private]
Definition at line 176 of file parser.cc.
                                                              {
  const char* arg = nullptr;
  switch (token) {
    case Token::kEos:
      message = MessageTemplate::kUnexpectedEOS;
      break;
    case Token::kSmi:
    case Token::kNumber:
    case Token::kBigInt:
      message = MessageTemplate::kUnexpectedTokenNumber;
      break;
    case Token::kString:
      message = MessageTemplate::kUnexpectedTokenString;
      break;
    case Token::kPrivateName:
    case Token::kIdentifier:
      message = MessageTemplate::kUnexpectedTokenIdentifier;
      // Use ReportMessageAt with the AstRawString parameter; skip the
      // ReportMessageAt below.
      ReportMessageAt(location, message, GetIdentifier());
      return;
    case Token::kAwait:
    case Token::kEnum:
      message = MessageTemplate::kUnexpectedReserved;
      break;
    case Token::kLet:
    case Token::kStatic:
    case Token::kYield:
    case Token::kFutureStrictReservedWord:
      message = is_strict(language_mode())
                    ? MessageTemplate::kUnexpectedStrictReserved
                    : MessageTemplate::kUnexpectedTokenIdentifier;
      arg = Token::String(token);
      break;
    case Token::kTemplateSpan:
    case Token::kTemplateTail:
      message = MessageTemplate::kUnexpectedTemplateString;
      break;
    case Token::kEscapedStrictReservedWord:
    case Token::kEscapedKeyword:
      message = MessageTemplate::kInvalidEscapedReservedWord;
      break;
    case Token::kIllegal:
      if (scanner()->has_error()) {
        message = scanner()->error();
        location = scanner()->error_location();
      } else {
        message = MessageTemplate::kInvalidOrUnexpectedToken;
      }
      break;
    case Token::kRegExpLiteral:
      message = MessageTemplate::kUnexpectedTokenRegExp;
      break;
    default:
      const char* name = Token::String(token);
      DCHECK_NOT_NULL(name);
      arg = name;
      break;
  }
  ReportMessageAt(location, message, arg);
}
References DCHECK_NOT_NULL, GetIdentifier(), v8::internal::is_strict(), v8::internal::compiler::kSmi, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kYield, v8::internal::name, and v8::internal::Token::String().
ReportUnidentifiableError()
void v8::internal::Parser::ReportUnidentifiableError () [inline], [private]
Definition at line 726 of file parser.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
ReportVarRedeclarationIn()
void v8::internal::Parser::ReportVarRedeclarationIn (const AstRawString * name, Scope * scope) [private]
Definition at line 2137 of file parser.cc.
                                                                            {
  for (Declaration* decl : *scope->declarations()) {
    if (decl->var()->raw_name() == name) {
      int position = decl->position();
      Scanner::Location location =
          position == kNoSourcePosition
              ? Scanner::Location::invalid()
              : Scanner::Location(position, position + name->length());
      ReportMessageAt(location, MessageTemplate::kVarRedeclaration, name);
      return;
    }
  }
  UNREACHABLE();
}
References v8::internal::Scope::declarations(), v8::internal::Scanner::Location::invalid(), v8::internal::kNoSourcePosition, v8::internal::name, and v8::internal::UNREACHABLE().
reusable_preparser()
PreParser* v8::internal::Parser::reusable_preparser () [inline], [private]
Definition at line 265 of file parser.h.
                                  {
    if (reusable_preparser_ == nullptr) {
      reusable_preparser_ = new PreParser(
          &preparser_zone_, &scanner_, stack_limit_, ast_value_factory(),
          pending_error_handler(), runtime_call_stats_, v8_file_logger_,
          flags(), parsing_on_main_thread_);
      reusable_preparser_->set_allow_eval_cache(allow_eval_cache());
      preparse_data_buffer_.reserve(128);
    }
    return reusable_preparser_;
  }
References v8::internal::flags.
Referenced by SkipFunction().
RewriteCatchPattern()
Block * v8::internal::Parser::RewriteCatchPattern (CatchInfo * catch_info) [private]
Definition at line 2126 of file parser.cc.
                                                        {
  DCHECK_NOT_NULL(catch_info->pattern);
  DeclarationParsingResult::Declaration decl(
      catch_info->pattern, factory()->NewVariableProxy(catch_info->variable));
  ScopedPtrList<Statement> init_statements(pointer_buffer());
  InitializeVariables(&init_statements, NORMAL_VARIABLE, &decl);
  return factory()->NewBlock(true, init_statements);
}
References DCHECK_NOT_NULL, InitializeVariables(), and v8::internal::NORMAL_VARIABLE.
RewriteClassLiteral()
Expression * v8::internal::Parser::RewriteClassLiteral (ClassScope * block_scope, const AstRawString * name, ClassInfo * class_info, int pos) [private]
Definition at line 3318 of file parser.cc.
                                                                        {
  DCHECK_NOT_NULL(block_scope);
  DCHECK_EQ(block_scope->scope_type(), CLASS_SCOPE);
  DCHECK_EQ(block_scope->language_mode(), LanguageMode::kStrict);
  bool has_extends = class_info->extends != nullptr;
  bool has_default_constructor = class_info->constructor == nullptr;
  int end_pos = block_scope->end_position();
  if (has_default_constructor) {
    class_info->constructor = DefaultConstructor(name, has_extends, pos);
  }
  if (!IsEmptyIdentifier(name)) {
    DCHECK_NOT_NULL(block_scope->class_variable());
    block_scope->class_variable()->set_initializer_position(end_pos);
  }
  FunctionLiteral* static_initializer = nullptr;
  if (class_info->has_static_elements()) {
    static_initializer = CreateStaticElementsInitializer(name, class_info);
  }
  FunctionLiteral* instance_members_initializer_function = nullptr;
  if (class_info->has_instance_members()) {
    instance_members_initializer_function =
        CreateInstanceMembersInitializer(name, class_info);
    class_info->constructor->set_requires_instance_members_initializer(true);
    class_info->constructor->add_expected_properties(
        class_info->instance_fields->length());
  }
  if (class_info->requires_brand) {
    class_info->constructor->set_class_scope_has_private_brand(true);
  }
  if (class_info->has_static_private_methods_or_accessors) {
    class_info->constructor->set_has_static_private_methods_or_accessors(true);
  }
  ClassLiteral* class_literal = factory()->NewClassLiteral(
      block_scope, class_info->extends, class_info->constructor,
      class_info->public_members, class_info->private_members,
      static_initializer, instance_members_initializer_function, pos, end_pos,
      class_info->has_static_computed_names, class_info->is_anonymous,
      class_info->home_object_variable,
      class_info->static_home_object_variable);
  AddFunctionForNameInference(class_info->constructor);
  return class_literal;
}
References AddFunctionForNameInference(), v8::internal::CLASS_SCOPE, v8::internal::ClassScope::class_variable(), CreateInstanceMembersInitializer(), CreateStaticElementsInitializer(), DCHECK_EQ, DCHECK_NOT_NULL, DefaultConstructor(), v8::internal::Scope::end_position(), IsEmptyIdentifier(), v8::internal::kStrict, v8::internal::Scope::language_mode(), v8::internal::name, v8::internal::Scope::scope_type(), and v8::internal::Variable::set_initializer_position().
RewriteForVarInLegacy()
Block * v8::internal::Parser::RewriteForVarInLegacy (const ForInfo & for_info) [private]
Definition at line 2234 of file parser.cc.
                                                            {
  const DeclarationParsingResult::Declaration& decl =
      for_info.parsing_result.declarations[0];
  if (!IsLexicalVariableMode(for_info.parsing_result.descriptor.mode) &&
      decl.initializer != nullptr && decl.pattern->IsVariableProxy()) {
    ++use_counts_[v8::Isolate::kForInInitializer];
    const AstRawString* name = decl.pattern->AsVariableProxy()->raw_name();
    VariableProxy* single_var = NewUnresolved(name);
    Block* init_block = factory()->NewBlock(2, true);
    init_block->statements()->Add(
        factory()->NewExpressionStatement(
            factory()->NewAssignment(Token::kAssign, single_var,
                                     decl.initializer, decl.value_beg_pos),
            kNoSourcePosition),
        zone());
    return init_block;
  }
  return nullptr;
}
References v8::internal::IsLexicalVariableMode(), v8::Isolate::kForInInitializer, v8::internal::kNoSourcePosition, v8::internal::name, v8::internal::Block::statements(), and use_counts_.
RewriteSpreads()
Expression* v8::internal::Parser::RewriteSpreads (ArrayLiteral * lit) [private]
RewriteSuperCall()
Expression* v8::internal::Parser::RewriteSuperCall (Expression * call_expression) [private]
RewriteSwitchStatement()
Statement * v8::internal::Parser::RewriteSwitchStatement (SwitchStatement * switch_statement, Scope * scope) [private]
Definition at line 2072 of file parser.cc.
                                                        {
  // In order to get the CaseClauses to execute in their own lexical scope,
  // but without requiring downstream code to have special scope handling
  // code for switch statements, desugar into blocks as follows:
  // { // To group the statements--harmless to evaluate Expression in scope
  // .tag_variable = Expression;
  // { // To give CaseClauses a scope
  // switch (.tag_variable) { CaseClause* }
  // }
  // }
  DCHECK_NOT_NULL(scope);
  DCHECK(scope->is_block_scope());
  DCHECK_GE(switch_statement->position(), scope->start_position());
  DCHECK_LT(switch_statement->position(), scope->end_position());
  Block* switch_block = factory()->NewBlock(2, false);
  Expression* tag = switch_statement->tag();
  Variable* tag_variable =
      NewTemporary(ast_value_factory()->dot_switch_tag_string());
  Assignment* tag_assign = factory()->NewAssignment(
      Token::kAssign, factory()->NewVariableProxy(tag_variable), tag,
      tag->position());
  // Wrap with IgnoreCompletion so the tag isn't returned as the completion
  // value, in case the switch statements don't have a value.
  Statement* tag_statement = IgnoreCompletion(
      factory()->NewExpressionStatement(tag_assign, kNoSourcePosition));
  switch_block->statements()->Add(tag_statement, zone());
  switch_statement->set_tag(factory()->NewVariableProxy(tag_variable));
  Block* cases_block = factory()->NewBlock(1, false);
  cases_block->statements()->Add(switch_statement, zone());
  cases_block->set_scope(scope);
  switch_block->statements()->Add(cases_block, zone());
  return switch_block;
}
References v8::internal::DCHECK(), DCHECK_GE, DCHECK_LT, DCHECK_NOT_NULL, v8::internal::Scope::end_position(), IgnoreCompletion(), v8::internal::Scope::is_block_scope(), v8::internal::kNoSourcePosition, NewTemporary(), v8::internal::AstNode::position(), v8::internal::Block::set_scope(), v8::internal::SwitchStatement::set_tag(), v8::internal::Scope::start_position(), v8::internal::Block::statements(), and v8::internal::SwitchStatement::tag().
RewriteTryStatement()
Statement * v8::internal::Parser::RewriteTryStatement (Block * try_block, Block * catch_block, const SourceRange & catch_range, Block * finally_block, const SourceRange & finally_range, const CatchInfo & catch_info, int pos) [private]
Definition at line 2152 of file parser.cc.
                                                                             {
  // Simplify the AST nodes by converting:
  // 'try B0 catch B1 finally B2'
  // to:
  // 'try { try B0 catch B1 } finally B2'
  if (catch_block != nullptr && finally_block != nullptr) {
    // If we have both, create an inner try/catch.
    TryCatchStatement* statement;
    statement = factory()->NewTryCatchStatement(try_block, catch_info.scope,
                                                catch_block, kNoSourcePosition);
    RecordTryCatchStatementSourceRange(statement, catch_range);
    try_block = factory()->NewBlock(1, false);
    try_block->statements()->Add(statement, zone());
    catch_block = nullptr; // Clear to indicate it's been handled.
  }
  if (catch_block != nullptr) {
    DCHECK_NULL(finally_block);
    TryCatchStatement* stmt = factory()->NewTryCatchStatement(
        try_block, catch_info.scope, catch_block, pos);
    RecordTryCatchStatementSourceRange(stmt, catch_range);
    return stmt;
  } else {
    DCHECK_NOT_NULL(finally_block);
    TryFinallyStatement* stmt =
        factory()->NewTryFinallyStatement(try_block, finally_block, pos);
    RecordTryFinallyStatementSourceRange(stmt, finally_range);
    return stmt;
  }
}
References DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::kNoSourcePosition, RecordTryCatchStatementSourceRange(), RecordTryFinallyStatementSourceRange(), v8::internal::Block::scope(), and v8::internal::Block::statements().
SetFunctionName()
void v8::internal::Parser::SetFunctionName (Expression * value, const AstRawString * name, const AstRawString * prefix = nullptr) [private]
Definition at line 3690 of file parser.cc.
                                                         {
  if (!value->IsAnonymousFunctionDefinition() &&
      !value->IsConciseMethodDefinition() &&
      !value->IsAccessorFunctionDefinition()) {
    return;
  }
  auto function = value->AsFunctionLiteral();
  if (value->IsClassLiteral()) {
    function = value->AsClassLiteral()->constructor();
  }
  if (function != nullptr) {
    AstConsString* cons_name = nullptr;
    if (name != nullptr) {
      if (prefix != nullptr) {
        cons_name = ast_value_factory()->NewConsString(prefix, name);
      } else {
        cons_name = ast_value_factory()->NewConsString(name);
      }
    } else {
      DCHECK_NULL(prefix);
    }
    function->set_raw_name(cons_name);
  }
}
References DCHECK_NULL, v8::internal::name, and v8::internal::value.
Referenced by MakeAutoAccessorGetter(), MakeAutoAccessorSetter(), ParseExportDefault(), SetFunctionNameFromIdentifierRef(), and SetFunctionNameFromPropertyName().
SetFunctionNameFromIdentifierRef()
void v8::internal::Parser::SetFunctionNameFromIdentifierRef (Expression * value, Expression * identifier) [private]
Definition at line 3682 of file parser.cc.
                                                                      {
  if (!identifier->IsVariableProxy()) return;
  // IsIdentifierRef of parenthesized expressions is false.
  if (identifier->is_parenthesized()) return;
  SetFunctionName(value, identifier->AsVariableProxy()->raw_name());
}
References v8::internal::Expression::is_parenthesized(), SetFunctionName(), and v8::internal::value.
SetFunctionNameFromPropertyName() [1/2]
void v8::internal::Parser::SetFunctionNameFromPropertyName (LiteralProperty * property, const AstRawString * name, const AstRawString * prefix = nullptr) [private]
Definition at line 3644 of file parser.cc.
                                                                         {
  if (has_error()) return;
  // Ensure that the function we are going to create has shared name iff
  // we are not going to set it later.
  if (property->NeedsSetFunctionName()) {
    name = nullptr;
    prefix = nullptr;
  } else {
    // If the property value is an anonymous function or an anonymous class or
    // a concise method or an accessor function which doesn't require the name
    // to be set then the shared name must be provided.
    DCHECK_IMPLIES(property->value()->IsAnonymousFunctionDefinition() ||
                       property->value()->IsConciseMethodDefinition() ||
                       property->value()->IsAccessorFunctionDefinition(),
                   name != nullptr);
  }
  Expression* value = property->value();
  SetFunctionName(value, name, prefix);
}
References DCHECK_IMPLIES, v8::internal::Expression::IsAccessorFunctionDefinition(), v8::internal::Expression::IsAnonymousFunctionDefinition(), v8::internal::Expression::IsConciseMethodDefinition(), v8::internal::name, v8::internal::LiteralProperty::NeedsSetFunctionName(), SetFunctionName(), v8::internal::LiteralProperty::value(), and v8::internal::value.
Referenced by SetFunctionNameFromPropertyName().
SetFunctionNameFromPropertyName() [2/2]
void v8::internal::Parser::SetFunctionNameFromPropertyName (ObjectLiteralProperty * property, const AstRawString * name, const AstRawString * prefix = nullptr) [private]
Definition at line 3667 of file parser.cc.
                                                                         {
  // Ignore "__proto__" as a name when it's being used to set the [[Prototype]]
  // of an object literal.
  // See ES #sec-__proto__-property-names-in-object-initializers.
  if (property->IsPrototype() || has_error()) return;
  DCHECK(!property->value()->IsAnonymousFunctionDefinition() ||
         property->kind() == ObjectLiteralProperty::COMPUTED);
  SetFunctionNameFromPropertyName(static_cast<LiteralProperty*>(property), name,
                                  prefix);
}
References v8::internal::ObjectLiteralProperty::COMPUTED, v8::internal::DCHECK(), v8::internal::Expression::IsAnonymousFunctionDefinition(), v8::internal::ObjectLiteralProperty::IsPrototype(), v8::internal::ObjectLiteralProperty::kind(), v8::internal::name, SetFunctionNameFromPropertyName(), and v8::internal::LiteralProperty::value().
SetLanguageMode()
void v8::internal::Parser::SetLanguageMode (Scope * scope, LanguageMode mode) [private]
Definition at line 3605 of file parser.cc.
                                                            {
  v8::Isolate::UseCounterFeature feature;
  if (is_sloppy(mode))
    feature = v8::Isolate::kSloppyMode;
  else if (is_strict(mode))
    feature = v8::Isolate::kStrictMode;
  else
    UNREACHABLE();
  ++use_counts_[feature];
  scope->SetLanguageMode(mode);
}
References v8::internal::is_sloppy(), v8::internal::is_strict(), v8::Isolate::kSloppyMode, v8::Isolate::kStrictMode, mode(), v8::internal::Scope::SetLanguageMode(), v8::internal::UNREACHABLE(), and use_counts_.
Referenced by DefaultConstructor(), DoParseFunction(), MakeAutoAccessorGetter(), MakeAutoAccessorSetter(), ParseFunctionLiteral(), and SkipFunction().
ShortcutLiteralBinaryExpression()
bool v8::internal::Parser::ShortcutLiteralBinaryExpression (Expression ** x, Expression * y, Token::Value op, int pos) [private]
Definition at line 243 of file parser.cc.
                                                                     {
  // Constant fold numeric operations.
  if ((*x)->IsNumberLiteral() && y->IsNumberLiteral()) {
    double x_val = (*x)->AsLiteral()->AsNumber();
    double y_val = y->AsLiteral()->AsNumber();
    switch (op) {
      case Token::kAdd:
        *x = factory()->NewNumberLiteral(x_val + y_val, pos);
        return true;
      case Token::kSub:
        *x = factory()->NewNumberLiteral(x_val - y_val, pos);
        return true;
      case Token::kMul:
        *x = factory()->NewNumberLiteral(x_val * y_val, pos);
        return true;
      case Token::kDiv:
        *x = factory()->NewNumberLiteral(base::Divide(x_val, y_val), pos);
        return true;
      case Token::kMod:
        *x = factory()->NewNumberLiteral(Modulo(x_val, y_val), pos);
        return true;
      case Token::kBitOr: {
        int value = DoubleToInt32(x_val) | DoubleToInt32(y_val);
        *x = factory()->NewNumberLiteral(value, pos);
        return true;
      }
      case Token::kBitAnd: {
        int value = DoubleToInt32(x_val) & DoubleToInt32(y_val);
        *x = factory()->NewNumberLiteral(value, pos);
        return true;
      }
      case Token::kBitXor: {
        int value = DoubleToInt32(x_val) ^ DoubleToInt32(y_val);
        *x = factory()->NewNumberLiteral(value, pos);
        return true;
      }
      case Token::kShl: {
        int value =
            base::ShlWithWraparound(DoubleToInt32(x_val), DoubleToInt32(y_val));
        *x = factory()->NewNumberLiteral(value, pos);
        return true;
      }
      case Token::kShr: {
        uint32_t shift = DoubleToInt32(y_val) & 0x1F;
        uint32_t value = DoubleToUint32(x_val) >> shift;
        *x = factory()->NewNumberLiteral(value, pos);
        return true;
      }
      case Token::kSar: {
        uint32_t shift = DoubleToInt32(y_val) & 0x1F;
        int value = ArithmeticShiftRight(DoubleToInt32(x_val), shift);
        *x = factory()->NewNumberLiteral(value, pos);
        return true;
      }
      case Token::kExp:
        *x = factory()->NewNumberLiteral(math::pow(x_val, y_val), pos);
        return true;
      default:
        break;
    }
  }
  // Constant fold string concatenation:
  // "abc" + "def" -> "abcdef"
  // Note that this only works for folding into the LHS of a left-associative
  // binary expression. String concatenation folding on the RHS is handled by
  // `CollapseNaryExpression`, which can't re-use this method since non-string
  // literal concatenation is not commutative.
  if (op == Token::kAdd) {
    // TODO(leszeks): We could also eagerly convert other literals to string if
    // one side of the addition is a string.
    if (ShortcutStringLiteralAppendExpression(x, y)) {
      return true;
    }
  }
  return false;
}
References v8::internal::ArithmeticShiftRight(), v8::base::Divide(), v8::internal::DoubleToInt32(), v8::internal::DoubleToUint32(), v8::internal::math::pow(), v8::base::ShlWithWraparound(), ShortcutStringLiteralAppendExpression(), v8::internal::value, and v8::internal::y.
ShortcutStringLiteralAppendExpression()
bool v8::internal::Parser::ShortcutStringLiteralAppendExpression (Expression ** x, Expression * y) [private]
Definition at line 322 of file parser.cc.
                                                                  {
  if (!y->IsStringLiteral()) return false;
  const AstRawString* y_val = y->AsLiteral()->AsRawString();
  // Only consider string concatenation of two strings.
  // TODO(leszeks): We could also eagerly convert other literals to string if
  // one side of the addition is a string. We'd have to be careful around
  // associativity though, in case x is the RHS-most expression of an n-ary
  // addition.
  if ((*x)->IsStringLiteral()) {
    const AstRawString* x_val = (*x)->AsLiteral()->AsRawString();
    AstConsString* cons = ast_value_factory()->NewConsString(x_val, y_val);
    *x = factory()->NewConsStringLiteral(cons, (*x)->position());
    return true;
  }
  if ((*x)->IsConsStringLiteral()) {
    (*x)->AsLiteral()->AsConsString()->AddString(zone(), y_val);
    (*x)->clear_parenthesized();
    return true;
  }
  return false;
}
References v8::internal::Expression::clear_parenthesized(), and v8::internal::y.
Referenced by CollapseNaryExpression(), and ShortcutLiteralBinaryExpression().
SkipFunction()
bool v8::internal::Parser::SkipFunction (const AstRawString * function_name, FunctionKind kind, FunctionSyntaxKind function_syntax_kind, DeclarationScope * function_scope, int * num_parameters, int * function_length, ProducedPreparseData ** produced_preparsed_scope_data) [private]
Definition at line 2903 of file parser.cc.
                                                                         {
  FunctionState function_state(&function_state_, &scope_, function_scope);
  function_scope->set_zone(&preparser_zone_);
  DCHECK_NE(kNoSourcePosition, function_scope->start_position());
  DCHECK_EQ(kNoSourcePosition, parameters_end_pos_);
  DCHECK_IMPLIES(IsArrowFunction(kind),
                 scanner()->current_token() == Token::kArrow);
  // FIXME(marja): There are 2 ways to skip functions now. Unify them.
  if (consumed_preparse_data_) {
    int end_position;
    LanguageMode language_mode;
    int num_inner_infos;
    bool uses_super_property;
    if (stack_overflow()) return true;
    {
      UnparkedScopeIfOnBackground unparked_scope(local_isolate_);
      *produced_preparse_data =
          consumed_preparse_data_->GetDataForSkippableFunction(
              main_zone(), function_scope->start_position(), &end_position,
              num_parameters, function_length, &num_inner_infos,
              &uses_super_property, &language_mode);
    }
    function_scope->outer_scope()->SetMustUsePreparseData();
    function_scope->set_is_skipped_function(true);
    function_scope->set_end_position(end_position);
    scanner()->SeekForward(end_position - 1);
    Expect(Token::kRightBrace);
    SetLanguageMode(function_scope, language_mode);
    if (uses_super_property) {
      function_scope->RecordSuperPropertyUsage();
    }
    SkipInfos(num_inner_infos);
    function_scope->ResetAfterPreparsing(ast_value_factory_, false);
    return true;
  }
  Scanner::BookmarkScope bookmark(scanner());
  bookmark.Set(function_scope->start_position());
  UnresolvedList::Iterator unresolved_private_tail;
  PrivateNameScopeIterator private_name_scope_iter(function_scope);
  if (!private_name_scope_iter.Done()) {
    unresolved_private_tail =
        private_name_scope_iter.GetScope()->GetUnresolvedPrivateNameTail();
  }
  // With no cached data, we partially parse the function, without building an
  // AST. This gathers the data needed to build a lazy function.
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"), "V8.PreParse");
  PreParser::PreParseResult result = reusable_preparser()->PreParseFunction(
      function_name, kind, function_syntax_kind, function_scope, use_counts_,
      produced_preparse_data);
  if (result == PreParser::kPreParseStackOverflow) {
    // Propagate stack overflow.
    set_stack_overflow();
  } else if (pending_error_handler()->has_error_unidentifiable_by_preparser()) {
    // Make sure we don't re-preparse inner functions of the aborted function.
    // The error might be in an inner function.
    allow_lazy_ = false;
    mode_ = PARSE_EAGERLY;
    DCHECK(!pending_error_handler()->stack_overflow());
    // If we encounter an error that the preparser can not identify we reset to
    // the state before preparsing. The caller may then fully parse the function
    // to identify the actual error.
    bookmark.Apply();
    if (!private_name_scope_iter.Done()) {
      private_name_scope_iter.GetScope()->ResetUnresolvedPrivateNameTail(
          unresolved_private_tail);
    }
    function_scope->ResetAfterPreparsing(ast_value_factory_, true);
    pending_error_handler()->clear_unidentifiable_error();
    return false;
  } else if (pending_error_handler()->has_pending_error()) {
    DCHECK(!pending_error_handler()->stack_overflow());
    DCHECK(has_error());
  } else {
    DCHECK(!pending_error_handler()->stack_overflow());
    set_allow_eval_cache(reusable_preparser()->allow_eval_cache());
    PreParserLogger* logger = reusable_preparser()->logger();
    function_scope->set_end_position(logger->end());
    Expect(Token::kRightBrace);
    total_preparse_skipped_ +=
        function_scope->end_position() - function_scope->start_position();
    *num_parameters = logger->num_parameters();
    *function_length = logger->function_length();
    SkipInfos(logger->num_inner_infos());
    if (!private_name_scope_iter.Done()) {
      private_name_scope_iter.GetScope()->MigrateUnresolvedPrivateNameTail(
          factory(), unresolved_private_tail);
    }
    function_scope->AnalyzePartially(this, factory(), MaybeParsingArrowhead());
  }
  return true;
}
References allow_lazy_, v8::internal::DeclarationScope::AnalyzePartially(), v8::internal::Scanner::BookmarkScope::Apply(), consumed_preparse_data_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NE, v8::internal::PrivateNameScopeIterator::Done(), v8::internal::PreParserLogger::end(), v8::internal::Scope::end_position(), v8::internal::PreParserLogger::function_length(), v8::internal::ConsumedPreparseData::GetDataForSkippableFunction(), v8::internal::PrivateNameScopeIterator::GetScope(), v8::internal::ClassScope::GetUnresolvedPrivateNameTail(), v8::internal::IsArrowFunction(), v8::internal::kNoSourcePosition, v8::internal::PreParser::kPreParseStackOverflow, local_isolate_, v8::internal::PreParser::logger(), v8::internal::ClassScope::MigrateUnresolvedPrivateNameTail(), mode_, v8::internal::PreParserLogger::num_inner_infos(), v8::internal::PreParserLogger::num_parameters(), v8::internal::Scope::outer_scope(), parameters_end_pos_, PARSE_EAGERLY, v8::internal::PreParser::PreParseFunction(), preparser_zone_, v8::internal::DeclarationScope::RecordSuperPropertyUsage(), v8::internal::DeclarationScope::ResetAfterPreparsing(), v8::internal::ClassScope::ResetUnresolvedPrivateNameTail(), v8::base::internal::result, reusable_preparser(), v8::internal::Scanner::BookmarkScope::Set(), v8::internal::Scope::set_end_position(), v8::internal::DeclarationScope::set_is_skipped_function(), v8::internal::DeclarationScope::set_zone(), SetLanguageMode(), v8::internal::Scope::SetMustUsePreparseData(), v8::internal::Scope::start_position(), total_preparse_skipped_, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and use_counts_.
Referenced by ParseFunctionLiteral().
ThisExpression()
class ThisExpression* v8::internal::Parser::ThisExpression () [inline], [private]
Definition at line 803 of file parser.h.
                                         {
    UseThis();
    return factory()->ThisExpression();
  }
ThrowPendingError()
void v8::internal::Parser::ThrowPendingError (Isolate * isolate, Handle< Script > script) [private]
UpdateStatistics() [1/2]
void v8::internal::Parser::UpdateStatistics (DirectHandle< Script > script, base::SmallVector< v8::Isolate::UseCounterFeature, 8 > * use_counters, int * preparse_skipped)
Definition at line 3475 of file parser.cc.
                           {
  // Move statistics to Isolate.
  for (int feature = 0; feature < v8::Isolate::kUseCounterFeatureCount;
       ++feature) {
    if (use_counts_[feature] > 0) {
      use_counts->emplace_back(v8::Isolate::UseCounterFeature(feature));
    }
  }
  if (scanner_.FoundHtmlComment()) {
    use_counts->emplace_back(v8::Isolate::kHtmlComment);
    if (script->line_offset() == 0 && script->column_offset() == 0) {
      use_counts->emplace_back(v8::Isolate::kHtmlCommentInExternalScript);
    }
  }
  if (scanner_.SawMagicCommentCompileHintsAll()) {
    use_counts->emplace_back(v8::Isolate::kCompileHintsMagicAll);
  }
  if (scanner_.SawSourceMappingUrlMagicCommentAtSign()) {
    use_counts->emplace_back(v8::Isolate::kSourceMappingUrlMagicCommentAtSign);
  }
  *preparse_skipped = total_preparse_skipped_;
}
References v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::internal::Scanner::FoundHtmlComment(), v8::Isolate::kCompileHintsMagicAll, v8::Isolate::kHtmlComment, v8::Isolate::kHtmlCommentInExternalScript, v8::Isolate::kSourceMappingUrlMagicCommentAtSign, v8::Isolate::kUseCounterFeatureCount, v8::internal::Scanner::SawMagicCommentCompileHintsAll(), v8::internal::Scanner::SawSourceMappingUrlMagicCommentAtSign(), scanner_, v8::internal::script, total_preparse_skipped_, and use_counts_.
UpdateStatistics() [2/2]
void v8::internal::Parser::UpdateStatistics (Isolate * isolate, DirectHandle< Script > script)
Definition at line 3451 of file parser.cc.
                                                                           {
  CHECK_NOT_NULL(isolate);
  // Move statistics to Isolate.
  for (int feature = 0; feature < v8::Isolate::kUseCounterFeatureCount;
       ++feature) {
    if (use_counts_[feature] > 0) {
      isolate->CountUsage(v8::Isolate::UseCounterFeature(feature));
    }
  }
  if (scanner_.FoundHtmlComment()) {
    isolate->CountUsage(v8::Isolate::kHtmlComment);
    if (script->line_offset() == 0 && script->column_offset() == 0) {
      isolate->CountUsage(v8::Isolate::kHtmlCommentInExternalScript);
    }
  }
  if (scanner_.SawMagicCommentCompileHintsAll()) {
    isolate->CountUsage(v8::Isolate::kCompileHintsMagicAll);
  }
  if (scanner_.SawSourceMappingUrlMagicCommentAtSign()) {
    isolate->CountUsage(v8::Isolate::kSourceMappingUrlMagicCommentAtSign);
  }
}
References CHECK_NOT_NULL, v8::internal::Isolate::CountUsage(), v8::internal::Scanner::FoundHtmlComment(), v8::Isolate::kCompileHintsMagicAll, v8::Isolate::kHtmlComment, v8::Isolate::kHtmlCommentInExternalScript, v8::Isolate::kSourceMappingUrlMagicCommentAtSign, v8::Isolate::kUseCounterFeatureCount, v8::internal::Scanner::SawMagicCommentCompileHintsAll(), v8::internal::Scanner::SawSourceMappingUrlMagicCommentAtSign(), scanner_, v8::internal::script, and use_counts_.
Referenced by v8::internal::parsing::anonymous_namespace{parsing.cc}::MaybeReportStatistics(), and v8::internal::BackgroundCompileTask::Run().
WrapREPLResult()
Expression * v8::internal::Parser::WrapREPLResult (Expression * value) [private]
Definition at line 981 of file parser.cc.
                                                    {
  // REPL scripts additionally wrap the ".result" variable in an
  // object literal:
  //
  // return %_AsyncFunctionResolve(
  // .generator_object, {__proto__: null, .repl_result: .result});
  //
  // Should ".result" be a resolved promise itself, the async return
  // would chain the promises and return the resolve value instead of
  // the promise.
  Literal* property_name = factory()->NewStringLiteral(
      ast_value_factory()->dot_repl_result_string(), kNoSourcePosition);
  ObjectLiteralProperty* property =
      factory()->NewObjectLiteralProperty(property_name, value, true);
  Literal* proto_name = factory()->NewStringLiteral(
      ast_value_factory()->proto_string(), kNoSourcePosition);
  ObjectLiteralProperty* prototype = factory()->NewObjectLiteralProperty(
      proto_name, factory()->NewNullLiteral(kNoSourcePosition), false);
  ScopedPtrList<ObjectLiteralProperty> properties(pointer_buffer());
  properties.Add(property);
  properties.Add(prototype);
  return factory()->NewObjectLiteral(properties, false, kNoSourcePosition,
                                     false);
}
References v8::internal::ScopedList< T, TBacking >::Add(), v8::internal::kNoSourcePosition, v8::internal::prototype, and v8::internal::value.
Referenced by ParseREPLProgram().
Friends And Related Function Documentation
i::ArrowHeadParsingScope< ParserTypes< Parser > >
friend class i::ArrowHeadParsingScope< ParserTypes< Parser > > [friend]
Definition at line 177 of file parser.h.
i::ExpressionScope< ParserTypes< Parser > >
friend class i::ExpressionScope< ParserTypes< Parser > > [friend]
Definition at line 177 of file parser.h.
i::ParameterDeclarationParsingScope< ParserTypes< Parser > >
friend class i::ParameterDeclarationParsingScope< ParserTypes< Parser > > [friend]
Definition at line 177 of file parser.h.
i::VariableDeclarationParsingScope< ParserTypes< Parser > >
friend class i::VariableDeclarationParsingScope< ParserTypes< Parser > > [friend]
Definition at line 177 of file parser.h.
ParserBase< Parser >
friend class ParserBase< Parser > [friend]
Definition at line 173 of file parser.h.
ParserFormalParameters
friend struct ParserFormalParameters [friend]
Definition at line 177 of file parser.h.
ParserTargetScope
friend class ParserTargetScope [friend]
Definition at line 1126 of file parser.h.
PreparseDataBuilder
friend class PreparseDataBuilder [friend]
Definition at line 1113 of file parser.h.
PreParserZoneScope
friend class PreParserZoneScope [friend]
Definition at line 1112 of file parser.h.
v8::internal::parsing::ParseFunction
bool v8::internal::parsing::ParseFunction (ParseInfo * , DirectHandle< SharedFunctionInfo > shared_info, Isolate * , parsing::ReportStatisticsMode stats_mode) [friend]
v8::internal::parsing::ParseProgram
bool v8::internal::parsing::ParseProgram (ParseInfo * , DirectHandle< Script > , MaybeDirectHandle< ScopeInfo > maybe_outer_scope_info, Isolate * , parsing::ReportStatisticsMode stats_mode) [friend]
Member Data Documentation
allow_lazy_
bool v8::internal::Parser::allow_lazy_ [private]
Definition at line 1137 of file parser.h.
Referenced by DoParseProgram(), ParseFunction(), ParseFunctionLiteral(), Parser(), and SkipFunction().
compile_options_
ScriptCompiler::CompileOptions v8::internal::Parser::compile_options_ [private]
Definition at line 1128 of file parser.h.
consumed_preparse_data_
ConsumedPreparseData* v8::internal::Parser::consumed_preparse_data_ [private]
Definition at line 1139 of file parser.h.
Referenced by SkipFunction().
info_
ParseInfo* v8::internal::Parser::info_ [private]
Definition at line 1116 of file parser.h.
local_isolate_
LocalIsolate* v8::internal::Parser::local_isolate_ [private]
Definition at line 1115 of file parser.h.
Referenced by GetBigIntAsSymbol(), and SkipFunction().
maybe_wrapped_arguments_
MaybeHandle<FixedArray> v8::internal::Parser::maybe_wrapped_arguments_ [private]
Definition at line 1122 of file parser.h.
Referenced by ParseFunction(), ParseProgram(), and PrepareWrappedArguments().
mode_
Mode v8::internal::Parser::mode_ [private]
Definition at line 1120 of file parser.h.
Referenced by SkipFunction().
number_of_named_namespace_exports_
int v8::internal::Parser::number_of_named_namespace_exports_ = 0 [private]
Definition at line 1131 of file parser.h.
Referenced by NextInternalNamespaceExportName().
parameters_end_pos_
int v8::internal::Parser::parameters_end_pos_ [private]
Definition at line 1146 of file parser.h.
Referenced by ParseFunction(), ParseFunctionLiteral(), and SkipFunction().
preparse_data_buffer_
std::vector<uint8_t> v8::internal::Parser::preparse_data_buffer_ [private]
Definition at line 1140 of file parser.h.
preparser_zone_
Zone v8::internal::Parser::preparser_zone_ [private]
Definition at line 1118 of file parser.h.
Referenced by ParseFunctionLiteral(), and SkipFunction().
reusable_preparser_
PreParser* v8::internal::Parser::reusable_preparser_ [private]
Definition at line 1119 of file parser.h.
scanner_
Scanner v8::internal::Parser::scanner_ [private]
Definition at line 1117 of file parser.h.
Referenced by HandleDebugMagicComments(), ParseFunction(), ParseOnBackground(), ParseProgram(), and UpdateStatistics().
source_range_map_
SourceRangeMap* v8::internal::Parser::source_range_map_ = nullptr [private]
Definition at line 1124 of file parser.h.
temp_zoned_
bool v8::internal::Parser::temp_zoned_ [private]
Definition at line 1138 of file parser.h.
total_preparse_skipped_
int v8::internal::Parser::total_preparse_skipped_ [private]
Definition at line 1136 of file parser.h.
Referenced by SkipFunction(), and UpdateStatistics().
use_counts_
int v8::internal::Parser::use_counts_[v8::Isolate::kUseCounterFeatureCount] [private]
Definition at line 1135 of file parser.h.
Referenced by Declare(), Parser(), RewriteForVarInLegacy(), SetLanguageMode(), SkipFunction(), and UpdateStatistics().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/parser.h
/mnt/V8SourceCode/src/parsing/parser.cc