v8::internal::Literal Class Reference
#include <ast.h>
Public Types
enum Type {
kSmi
, kHeapNumber
, kBigInt
, kString
,
kConsString
, kBoolean
, kUndefined
, kNull
,
kTheHole
 }
Public Member Functions
Type type () const
bool IsPropertyName () const
bool AsArrayIndex (uint32_t *index) const
const AstRawString * AsRawPropertyName ()
Tagged< Smi > AsSmiLiteral () const
bool AsBooleanLiteral () const
bool IsNumber () const
double AsNumber () const
AstBigInt AsBigInt () const
bool IsRawString () const
const AstRawString * AsRawString ()
bool IsConsString () const
AstConsString * AsConsString ()
V8_EXPORT_PRIVATE bool ToBooleanIsTrue () const
bool ToBooleanIsFalse () const
bool ToUint32 (uint32_t *value) const
template<typename IsolateT >
DirectHandle< Object > BuildValue (IsolateT *isolate) const
uint32_t Hash ()
Static Public Member Functions
static bool Match (void *literal1, void *literal2)
Private Types
using TypeField = Expression::NextBitField< Type, 4 >
Private Member Functions
Literal (int smi, int position)
Literal (double number, int position)
Literal (AstBigInt bigint, int position)
Literal (const AstRawString *string, int position)
Literal (AstConsString *string, int position)
Literal (bool boolean, int position)
Literal (Type type, int position)
Private Attributes
friend Zone
xx xx xx xx xx xx xx xx xx
union {
 const AstRawString * string_
 AstConsString * cons_string_
 int smi_
 double number_
 AstBigInt bigint_
 bool boolean_
};
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 941 of file ast.h.
Member Typedef Documentation
TypeField
using v8::internal::Literal::TypeField = Expression::NextBitField<Type, 4> [private]
Definition at line 1033 of file ast.h.
Member Enumeration Documentation
Type
enum v8::internal::Literal::Type
Enumerator
kSmi
kHeapNumber
kBigInt
kString
kConsString
kBoolean
kUndefined
kNull
kTheHole
Definition at line 943 of file ast.h.
            {
    kSmi,
    kHeapNumber,
    kBigInt,
    kString,
    kConsString,
    kBoolean,
    kUndefined,
    kNull,
    kTheHole,
  };
Constructor & Destructor Documentation
Literal() [1/7]
v8::internal::Literal::Literal (int smi, int position) [inline], [private]
Definition at line 1035 of file ast.h.
                                 : Expression(position, kLiteral), smi_(smi) {
    bit_field_ = TypeField::update(bit_field_, kSmi);
  }
References v8::internal::AstNode::bit_field_, v8::internal::kLiteral, kSmi, and v8::base::BitField< T, shift, size, U >::update().
Literal() [2/7]
v8::internal::Literal::Literal (double number, int position) [inline], [private]
Definition at line 1039 of file ast.h.
      : Expression(position, kLiteral), number_(number) {
    bit_field_ = TypeField::update(bit_field_, kHeapNumber);
  }
References v8::internal::AstNode::bit_field_, kHeapNumber, v8::internal::kLiteral, and v8::base::BitField< T, shift, size, U >::update().
Literal() [3/7]
v8::internal::Literal::Literal (AstBigInt bigint, int position) [inline], [private]
Definition at line 1044 of file ast.h.
      : Expression(position, kLiteral), bigint_(bigint) {
    bit_field_ = TypeField::update(bit_field_, kBigInt);
  }
References v8::internal::AstNode::bit_field_, kBigInt, v8::internal::kLiteral, and v8::base::BitField< T, shift, size, U >::update().
Literal() [4/7]
v8::internal::Literal::Literal (const AstRawString * string, int position) [inline], [private]
Definition at line 1049 of file ast.h.
      : Expression(position, kLiteral), string_(string) {
    bit_field_ = TypeField::update(bit_field_, kString);
  }
References v8::internal::AstNode::bit_field_, v8::internal::kLiteral, kString, and v8::base::BitField< T, shift, size, U >::update().
Literal() [5/7]
v8::internal::Literal::Literal (AstConsString * string, int position) [inline], [private]
Definition at line 1054 of file ast.h.
      : Expression(position, kLiteral), cons_string_(string) {
    bit_field_ = TypeField::update(bit_field_, kConsString);
  }
References v8::internal::AstNode::bit_field_, kConsString, v8::internal::kLiteral, and v8::base::BitField< T, shift, size, U >::update().
Literal() [6/7]
v8::internal::Literal::Literal (bool boolean, int position) [inline], [private]
Definition at line 1059 of file ast.h.
      : Expression(position, kLiteral), boolean_(boolean) {
    bit_field_ = TypeField::update(bit_field_, kBoolean);
  }
References v8::internal::AstNode::bit_field_, kBoolean, v8::internal::kLiteral, and v8::base::BitField< T, shift, size, U >::update().
Literal() [7/7]
v8::internal::Literal::Literal (Type type, int position) [inline], [private]
Definition at line 1064 of file ast.h.
                                   : Expression(position, kLiteral) {
    DCHECK(type == kNull || type == kUndefined || type == kTheHole);
    bit_field_ = TypeField::update(bit_field_, type);
  }
References v8::internal::AstNode::bit_field_, v8::internal::DCHECK(), v8::internal::kLiteral, kNull, kTheHole, kUndefined, type(), and v8::base::BitField< T, shift, size, U >::update().
Member Function Documentation
AsArrayIndex()
bool v8::internal::Literal::AsArrayIndex (uint32_t * index) const
Definition at line 1047 of file ast.cc.
                                                {
  return ToUint32(value) && *value != kMaxUInt32;
}
References v8::internal::kMaxUInt32, ToUint32(), and v8::internal::value.
Referenced by v8::internal::ObjectLiteralBoilerplateBuilder::BuildBoilerplateDescription(), Hash(), Match(), and v8::internal::ClassBoilerplate::New().
AsBigInt()
AstBigInt v8::internal::Literal::AsBigInt () const [inline]
Definition at line 997 of file ast.h.
                             {
    DCHECK_EQ(type(), kBigInt);
    return bigint_;
  }
References bigint_, DCHECK_EQ, kBigInt, and type().
AsBooleanLiteral()
bool v8::internal::Literal::AsBooleanLiteral () const [inline]
Definition at line 978 of file ast.h.
                                {
    DCHECK_EQ(kBoolean, type());
    return boolean_;
  }
References boolean_, DCHECK_EQ, kBoolean, and type().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLiteralStrictCompareBoolean().
AsConsString()
AstConsString* v8::internal::Literal::AsConsString () [inline]
Definition at line 1009 of file ast.h.
                                {
    DCHECK_EQ(type(), kConsString);
    return cons_string_;
  }
References cons_string_, DCHECK_EQ, kConsString, and type().
AsNumber()
double v8::internal::Literal::AsNumber () const [inline]
Definition at line 985 of file ast.h.
                          {
    DCHECK(IsNumber());
    switch (type()) {
      case kSmi:
        return smi_;
      case kHeapNumber:
        return number_;
      default:
        UNREACHABLE();
    }
  }
References v8::internal::DCHECK(), IsNumber(), kHeapNumber, kSmi, number_, smi_, type(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::ArrayLiteralBoilerplateBuilder::BuildBoilerplateDescription(), v8::internal::Parser::BuildUnaryExpression(), Hash(), Match(), and ToUint32().
AsRawPropertyName()
const AstRawString* v8::internal::Literal::AsRawPropertyName () [inline]
Definition at line 968 of file ast.h.
                                          {
    DCHECK(IsPropertyName());
    return string_;
  }
References v8::internal::DCHECK(), IsPropertyName(), and string_.
Referenced by v8::internal::ObjectLiteralBoilerplateBuilder::BuildBoilerplateDescription(), and v8::internal::ClassBoilerplate::New().
AsRawString()
const AstRawString* v8::internal::Literal::AsRawString () [inline]
Definition at line 1003 of file ast.h.
                                    {
    DCHECK_EQ(type(), kString);
    return string_;
  }
References DCHECK_EQ, kString, string_, and type().
Referenced by v8::internal::interpreter::TestTypeOfFlags::GetFlagForLiteral(), Hash(), v8::internal::interpreter::IsLiteralCompareTypeof(), v8::internal::Parser::IsStringLiteral(), and Match().
AsSmiLiteral()
Tagged<Smi> v8::internal::Literal::AsSmiLiteral () const [inline]
Definition at line 973 of file ast.h.
                                   {
    DCHECK_EQ(kSmi, type());
    return Smi::FromInt(smi_);
  }
References DCHECK_EQ, v8::internal::Smi::FromInt(), kSmi, smi_, and type().
BuildValue()
template<typename IsolateT >
DirectHandle< Object > v8::internal::Literal::BuildValue (IsolateT * isolate) const
Definition at line 1052 of file ast.cc.
                                                                {
  switch (type()) {
    case kSmi:
      return direct_handle(Smi::FromInt(smi_), isolate);
    case kHeapNumber:
      return isolate->factory()->template NewNumber<AllocationType::kOld>(
          number_);
    case kString:
      return string_->string();
    case kConsString:
      return cons_string_->AllocateFlat(isolate);
    case kBoolean:
      return isolate->factory()->ToBoolean(boolean_);
    case kNull:
      return isolate->factory()->null_value();
    case kUndefined:
      return isolate->factory()->undefined_value();
    case kTheHole:
      return isolate->factory()->the_hole_value();
    case kBigInt:
      // This should never fail: the parser will never create a BigInt
      // literal that cannot be allocated.
      return BigIntLiteral(isolate, bigint_.c_str()).ToHandleChecked();
  }
  UNREACHABLE();
}
References v8::internal::AstConsString::AllocateFlat(), bigint_, v8::internal::BigIntLiteral(), boolean_, v8::internal::AstBigInt::c_str(), cons_string_, v8::internal::direct_handle(), v8::internal::Smi::FromInt(), kBigInt, kBoolean, kConsString, kHeapNumber, kNull, kSmi, kString, kTheHole, kUndefined, number_, smi_, v8::internal::AstRawString::string(), string_, type(), and v8::internal::UNREACHABLE().
Hash()
uint32_t v8::internal::Literal::Hash ()
Definition at line 1116 of file ast.cc.
                       {
  DCHECK(IsRawString() || IsNumber());
  uint32_t index;
  if (AsArrayIndex(&index)) {
    // Treat array indices as numbers, so that array indices are de-duped
    // correctly even if one of them is a string and the other is a number.
    return ComputeLongHash(index);
  }
  return IsRawString() ? AsRawString()->Hash()
                       : ComputeLongHash(base::double_to_uint64(AsNumber()));
}
References AsArrayIndex(), AsNumber(), AsRawString(), v8::internal::ComputeLongHash(), v8::internal::DCHECK(), v8::base::double_to_uint64(), v8::internal::AstRawString::Hash(), v8::internal::index, IsNumber(), and IsRawString().
Referenced by v8::internal::ObjectLiteral::CalculateEmitStore().
IsConsString()
bool v8::internal::Literal::IsConsString () const [inline]
Definition at line 1008 of file ast.h.
{ return type() == kConsString; }
References kConsString, and type().
IsNumber()
bool v8::internal::Literal::IsNumber () const [inline]
Definition at line 984 of file ast.h.
{ return type() == kHeapNumber || type() == kSmi; }
References kHeapNumber, kSmi, and type().
Referenced by AsNumber(), v8::internal::ArrayLiteralBoilerplateBuilder::BuildBoilerplateDescription(), Hash(), and Match().
IsPropertyName()
bool v8::internal::Literal::IsPropertyName () const
Definition at line 1026 of file ast.cc.
                                   {
  if (type() != kString) return false;
  uint32_t index;
  return !string_->AsArrayIndex(&index);
}
References v8::internal::AstRawString::AsArrayIndex(), v8::internal::index, kString, string_, and type().
Referenced by AsRawPropertyName().
IsRawString()
bool v8::internal::Literal::IsRawString () const [inline]
Definition at line 1002 of file ast.h.
{ return type() == kString; }
References kString, and type().
Referenced by Hash(), v8::internal::Parser::IsStringLiteral(), and Match().
Match()
bool v8::internal::Literal::Match (void * literal1, void * literal2) [static]
Definition at line 1129 of file ast.cc.
                                    {
  Literal* x = static_cast<Literal*>(a);
  Literal* y = static_cast<Literal*>(b);
  uint32_t index_x;
  uint32_t index_y;
  if (x->AsArrayIndex(&index_x)) {
    return y->AsArrayIndex(&index_y) && index_x == index_y;
  }
  return (x->IsRawString() && y->IsRawString() &&
          x->AsRawString() == y->AsRawString()) ||
         (x->IsNumber() && y->IsNumber() && x->AsNumber() == y->AsNumber());
}
References AsArrayIndex(), AsNumber(), AsRawString(), IsNumber(), IsRawString(), and v8::internal::y.
Referenced by v8::internal::ObjectLiteral::CalculateEmitStore().
ToBooleanIsFalse()
bool v8::internal::Literal::ToBooleanIsFalse () const [inline]
Definition at line 1015 of file ast.h.
{ return !ToBooleanIsTrue(); }
References ToBooleanIsTrue().
Referenced by v8::internal::Parser::BuildUnaryExpression().
ToBooleanIsTrue()
V8_EXPORT_PRIVATE bool v8::internal::Literal::ToBooleanIsTrue () const
Referenced by ToBooleanIsFalse().
ToUint32()
bool v8::internal::Literal::ToUint32 (uint32_t * value) const
Definition at line 1032 of file ast.cc.
                                            {
  switch (type()) {
    case kString:
      return string_->AsArrayIndex(value);
    case kSmi:
      if (smi_ < 0) return false;
      *value = static_cast<uint32_t>(smi_);
      return true;
    case kHeapNumber:
      return DoubleToUint32IfEqualToSelf(AsNumber(), value);
    default:
      return false;
  }
}
References v8::internal::AstRawString::AsArrayIndex(), AsNumber(), v8::internal::DoubleToUint32IfEqualToSelf(), kHeapNumber, kSmi, kString, smi_, string_, type(), and v8::internal::value.
Referenced by AsArrayIndex().
type()
Type v8::internal::Literal::type () const [inline]
Definition at line 955 of file ast.h.
{ return TypeField::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by AsBigInt(), AsBooleanLiteral(), AsConsString(), AsNumber(), AsRawString(), AsSmiLiteral(), v8::internal::ArrayLiteralBoilerplateBuilder::BuildBoilerplateDescription(), BuildValue(), IsConsString(), IsNumber(), IsPropertyName(), IsRawString(), Literal(), and ToUint32().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 1030 of file ast.h.
Member Data Documentation
union { ... } [private]
bigint_
AstBigInt v8::internal::Literal::bigint_
Definition at line 1074 of file ast.h.
Referenced by AsBigInt(), and BuildValue().
boolean_
bool v8::internal::Literal::boolean_
Definition at line 1075 of file ast.h.
Referenced by AsBooleanLiteral(), and BuildValue().
cons_string_
AstConsString* v8::internal::Literal::cons_string_
Definition at line 1071 of file ast.h.
Referenced by AsConsString(), and BuildValue().
number_
double v8::internal::Literal::number_
Definition at line 1073 of file ast.h.
Referenced by AsNumber(), and BuildValue().
smi_
int v8::internal::Literal::smi_
Definition at line 1072 of file ast.h.
Referenced by AsNumber(), AsSmiLiteral(), BuildValue(), and ToUint32().
string_
const AstRawString* v8::internal::Literal::string_
Definition at line 1070 of file ast.h.
Referenced by AsRawPropertyName(), AsRawString(), BuildValue(), IsPropertyName(), and ToUint32().
Zone
friend v8::internal::Literal::Zone [private]
Definition at line 1031 of file ast.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc