v8::internal::compiler::OperandGenerator Class Reference
#include <instruction-selector-impl.h>
Public Types
enum class RegisterUseKind { kUseRegister
, kUseUniqueRegister
 }
enum RegisterMode { kRegister
, kUniqueRegister
 }
Public Member Functions
OperandGenerator (InstructionSelector *selector)
InstructionOperand NoOutput ()
InstructionOperand DefineAsRegister (turboshaft::OpIndex node)
InstructionOperand DefineSameAsInput (turboshaft::OpIndex node, int input_index)
InstructionOperand DefineSameAsFirst (turboshaft::OpIndex node)
InstructionOperand DefineAsFixed (turboshaft::OpIndex node, Register reg)
template<typename FPRegType >
InstructionOperand DefineAsFixed (turboshaft::OpIndex node, FPRegType reg)
InstructionOperand DefineAsConstant (turboshaft::OpIndex node)
InstructionOperand DefineAsLocation (turboshaft::OpIndex node, LinkageLocation location)
InstructionOperand DefineAsDualLocation (turboshaft::OpIndex node, LinkageLocation primary_location, LinkageLocation secondary_location)
InstructionOperand Use (turboshaft::OpIndex node)
InstructionOperand UseAnyAtEnd (turboshaft::OpIndex node)
InstructionOperand UseAny (turboshaft::OpIndex node)
InstructionOperand UseRegisterOrSlotOrConstant (turboshaft::OpIndex node)
InstructionOperand UseUniqueRegisterOrSlotOrConstant (turboshaft::OpIndex node)
InstructionOperand UseRegister (turboshaft::OpIndex node)
InstructionOperand UseRegisterAtEnd (turboshaft::OpIndex node)
InstructionOperand UseUniqueSlot (turboshaft::OpIndex node)
InstructionOperand UseUnique (turboshaft::OpIndex node)
InstructionOperand UseUniqueRegister (turboshaft::OpIndex node)
InstructionOperand UseRegister (turboshaft::OpIndex node, RegisterUseKind unique_reg)
InstructionOperand UseFixed (turboshaft::OpIndex node, Register reg)
template<typename FPRegType >
InstructionOperand UseFixed (turboshaft::OpIndex node, FPRegType reg)
InstructionOperand UseImmediate (int immediate)
InstructionOperand UseImmediate64 (int64_t immediate)
InstructionOperand UseImmediate (turboshaft::OpIndex node)
InstructionOperand UseNegatedImmediate (turboshaft::OpIndex node)
InstructionOperand UseLocation (turboshaft::OpIndex node, LinkageLocation location)
InstructionOperand UsePointerLocation (LinkageLocation to_location, LinkageLocation from_location)
InstructionOperand TempRegister ()
int AllocateVirtualRegister ()
InstructionOperand DefineSameAsFirstForVreg (int vreg)
InstructionOperand DefineAsRegistertForVreg (int vreg)
InstructionOperand UseRegisterForVreg (int vreg)
InstructionOperand UseRegisterWithMode (turboshaft::OpIndex node, RegisterMode register_mode)
InstructionOperand TempDoubleRegister ()
InstructionOperand TempSimd128Register ()
InstructionOperand TempSimd256Register ()
InstructionOperand TempRegister (Register reg)
InstructionOperand TempRegister (int code)
template<typename FPRegType >
InstructionOperand TempFpRegister (FPRegType reg)
InstructionOperand TempImmediate (int32_t imm)
InstructionOperand TempLocation (LinkageLocation location)
InstructionOperand Label (turboshaft::Block *block)
turboshaft::Graph * turboshaft_graph () const
Protected Member Functions
InstructionSelector * selector () const
InstructionSequence * sequence () const
Zone * zone () const
Private Member Functions
int GetVReg (turboshaft::OpIndex node) const
Constant ToConstant (turboshaft::OpIndex node)
Constant ToNegatedConstant (turboshaft::OpIndex node)
UnallocatedOperand Define (turboshaft::OpIndex node, UnallocatedOperand operand)
UnallocatedOperand Use (turboshaft::OpIndex node, UnallocatedOperand operand)
UnallocatedOperand ToDualLocationUnallocatedOperand (LinkageLocation primary_location, LinkageLocation secondary_location, int virtual_register)
UnallocatedOperand ToUnallocatedOperand (LinkageLocation location, int virtual_register)
Private Attributes
InstructionSelector * selector_
Additional Inherited Members
Detailed Description
Definition at line 72 of file instruction-selector-impl.h.
Member Enumeration Documentation
RegisterMode
enum v8::internal::compiler::OperandGenerator::RegisterMode
Enumerator
kRegister
kUniqueRegister
Definition at line 268 of file instruction-selector-impl.h.
                    {
    kRegister,
    kUniqueRegister,
  };
RegisterUseKind
enum v8::internal::compiler::OperandGenerator::RegisterUseKind [strong]
Enumerator
kUseRegister
kUseUniqueRegister
Definition at line 191 of file instruction-selector-impl.h.
{ kUseRegister, kUseUniqueRegister };
Constructor & Destructor Documentation
OperandGenerator()
v8::internal::compiler::OperandGenerator::OperandGenerator (InstructionSelector * selector) [inline], [explicit]
Definition at line 74 of file instruction-selector-impl.h.
      : turboshaft::OperationMatcher(*selector->schedule()),
        selector_(selector) {}
Member Function Documentation
AllocateVirtualRegister()
int v8::internal::compiler::OperandGenerator::AllocateVirtualRegister () [inline]
Definition at line 251 of file instruction-selector-impl.h.
{ return sequence()->NextVirtualRegister(); }
References v8::internal::compiler::InstructionSequence::NextVirtualRegister(), and sequence().
Define()
UnallocatedOperand v8::internal::compiler::OperandGenerator::Define (turboshaft::OpIndex node, UnallocatedOperand operand) [inline], [private]
Definition at line 435 of file instruction-selector-impl.h.
                                                        {
    DCHECK(node.valid());
    DCHECK_EQ(operand.virtual_register(), GetVReg(node));
    selector()->MarkAsDefined(node);
    return operand;
  }
References v8::internal::DCHECK(), DCHECK_EQ, GetVReg(), v8::internal::compiler::InstructionSelector::MarkAsDefined(), selector(), v8::internal::compiler::turboshaft::OpIndex::valid(), and v8::internal::compiler::UnallocatedOperand::virtual_register().
Referenced by DefineAsDualLocation(), DefineAsFixed(), DefineAsLocation(), DefineAsRegister(), and DefineSameAsInput().
DefineAsConstant()
InstructionOperand v8::internal::compiler::OperandGenerator::DefineAsConstant (turboshaft::OpIndex node) [inline]
Definition at line 109 of file instruction-selector-impl.h.
                                                              {
    selector()->MarkAsDefined(node);
    int virtual_register = GetVReg(node);
    sequence()->AddConstant(virtual_register, ToConstant(node));
    return ConstantOperand(virtual_register);
  }
References v8::internal::compiler::InstructionSequence::AddConstant(), GetVReg(), v8::internal::compiler::InstructionSelector::MarkAsDefined(), selector(), sequence(), and ToConstant().
Referenced by v8::internal::compiler::InstructionSelector::VisitConstant().
DefineAsDualLocation()
InstructionOperand v8::internal::compiler::OperandGenerator::DefineAsDualLocation (turboshaft::OpIndex node, LinkageLocation primary_location, LinkageLocation secondary_location) [inline]
Definition at line 121 of file instruction-selector-impl.h.
                                                                              {
    return Define(node,
                  ToDualLocationUnallocatedOperand(
                      primary_location, secondary_location, GetVReg(node)));
  }
References Define(), GetVReg(), and ToDualLocationUnallocatedOperand().
Referenced by v8::internal::compiler::InstructionSelector::VisitParameter().
DefineAsFixed() [1/2]
template<typename FPRegType >
InstructionOperand v8::internal::compiler::OperandGenerator::DefineAsFixed (turboshaft::OpIndex node, FPRegType reg) [inline]
Definition at line 103 of file instruction-selector-impl.h.
                                                                          {
    return Define(node,
                  UnallocatedOperand(UnallocatedOperand::FIXED_FP_REGISTER,
                                     reg.code(), GetVReg(node)));
  }
References Define(), v8::internal::compiler::UnallocatedOperand::FIXED_FP_REGISTER, and GetVReg().
DefineAsFixed() [2/2]
InstructionOperand v8::internal::compiler::OperandGenerator::DefineAsFixed (turboshaft::OpIndex node, Register reg) [inline]
Definition at line 97 of file instruction-selector-impl.h.
                                                                         {
    return Define(node, UnallocatedOperand(UnallocatedOperand::FIXED_REGISTER,
                                           reg.code(), GetVReg(node)));
  }
References Define(), v8::internal::compiler::UnallocatedOperand::FIXED_REGISTER, and GetVReg().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitDiv(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitDiv(), v8::internal::compiler::InstructionSelector::VisitFloat64Ieee754Binop(), v8::internal::compiler::InstructionSelector::VisitFloat64Ieee754Unop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMulHigh(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMulHigh(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::VisitPairAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon(), and v8::internal::compiler::VisitWord32PairShift().
DefineAsLocation()
InstructionOperand v8::internal::compiler::OperandGenerator::DefineAsLocation (turboshaft::OpIndex node, LinkageLocation location) [inline]
Definition at line 116 of file instruction-selector-impl.h.
                                                                {
    return Define(node, ToUnallocatedOperand(location, GetVReg(node)));
  }
References Define(), GetVReg(), and ToUnallocatedOperand().
Referenced by v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::InstructionSelector::VisitIfException(), v8::internal::compiler::InstructionSelector::VisitOsrValue(), and v8::internal::compiler::InstructionSelector::VisitParameter().
DefineAsRegister()
InstructionOperand v8::internal::compiler::OperandGenerator::DefineAsRegister (turboshaft::OpIndex node) [inline]
Definition at line 82 of file instruction-selector-impl.h.
                                                              {
    return Define(node,
                  UnallocatedOperand(UnallocatedOperand::MUST_HAVE_REGISTER,
                                     GetVReg(node)));
  }
References Define(), GetVReg(), and v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitBic(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::EmitInt64MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::EmitLea(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::EmitLea(), v8::internal::compiler::InstructionSelector::EmitPrepareResults(), v8::internal::compiler::EmitS128Load(), v8::internal::compiler::EmitSignExtendWord(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitUbfx(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitBitfieldExtract32(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitExtendingLoad(), v8::internal::compiler::TryEmitExtendingLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryEmitLoadForLoadWord64AndShiftRight(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyAdd(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplySub(), v8::internal::compiler::TryMatchNegFromSub(), v8::internal::compiler::TryMatchShiftFromMul(), v8::internal::compiler::TryMatchSignExtInt16OrInt8FromWord32Sar(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAddSub(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicBinop(), v8::internal::compiler::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitBinOp(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), v8::internal::compiler::InstructionSelector::VisitBitcastWord32PairToFloat64(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBitMask(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitDiv(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitFloatUnop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatUnop(), v8::internal::compiler::VisitInt32PairBinop(), v8::internal::compiler::InstructionSelector::VisitLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitLoadAndTest(), v8::internal::compiler::VisitLoadCommon(), v8::internal::compiler::VisitLogical(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMinOrMax(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMul(), v8::internal::compiler::InstructionSelector::VisitNode(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitROWithTemp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitROWithTempSimd(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRR(), v8::internal::compiler::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRR(), v8::internal::compiler::VisitRRI(), v8::internal::compiler::VisitRRIR(), v8::internal::compiler::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRROFloat(), v8::internal::compiler::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitShift(), v8::internal::compiler::VisitSimdShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTryTruncateDouble(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitTryTruncateDouble(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitUnaryOp(), v8::internal::compiler::VisitUniqueRRR(), v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWord32PairShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitWord32PairShift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare().
DefineAsRegistertForVreg()
InstructionOperand v8::internal::compiler::OperandGenerator::DefineAsRegistertForVreg (int vreg) [inline]
Definition at line 257 of file instruction-selector-impl.h.
                                                        {
    return UnallocatedOperand(UnallocatedOperand::MUST_HAVE_REGISTER, vreg);
  }
References v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER.
DefineSameAsFirst()
InstructionOperand v8::internal::compiler::OperandGenerator::DefineSameAsFirst (turboshaft::OpIndex node) [inline]
Definition at line 93 of file instruction-selector-impl.h.
                                                               {
    return DefineSameAsInput(node, 0);
  }
References DefineSameAsInput().
Referenced by v8::internal::compiler::TryMatchNegFromSub(), v8::internal::compiler::TryMatchShiftFromMul(), v8::internal::compiler::TryMatchSignExtInt16OrInt8FromWord32Sar(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryVisitWordShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitFloatUnop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatUnop(), v8::internal::compiler::VisitInt32PairBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMinOrMax(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMul(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRROFloat(), v8::internal::compiler::VisitShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitUnaryOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32Shift(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64Shift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare().
DefineSameAsFirstForVreg()
InstructionOperand v8::internal::compiler::OperandGenerator::DefineSameAsFirstForVreg (int vreg) [inline]
Definition at line 253 of file instruction-selector-impl.h.
                                                        {
    return UnallocatedOperand(UnallocatedOperand::SAME_AS_INPUT, vreg);
  }
References v8::internal::compiler::UnallocatedOperand::SAME_AS_INPUT.
DefineSameAsInput()
InstructionOperand v8::internal::compiler::OperandGenerator::DefineSameAsInput (turboshaft::OpIndex node, int input_index) [inline]
Definition at line 88 of file instruction-selector-impl.h.
                                                        {
    return Define(node, UnallocatedOperand(GetVReg(node), input_index));
  }
References Define(), and GetVReg().
Referenced by DefineSameAsFirst(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange().
GetVReg()
int v8::internal::compiler::OperandGenerator::GetVReg (turboshaft::OpIndex node) const [inline], [private]
Definition at line 348 of file instruction-selector-impl.h.
                                            {
    return selector_->GetVirtualRegister(node);
  }
References v8::internal::compiler::InstructionSelector::GetVirtualRegister(), and selector_.
Referenced by Define(), DefineAsConstant(), DefineAsDualLocation(), DefineAsFixed(), DefineAsLocation(), DefineAsRegister(), DefineSameAsInput(), Use(), UseAny(), UseAnyAtEnd(), UseFixed(), UseLocation(), UseRegister(), UseRegisterAtEnd(), UseRegisterOrSlotOrConstant(), UseUnique(), UseUniqueRegister(), UseUniqueRegisterOrSlotOrConstant(), and UseUniqueSlot().
Label()
InstructionOperand v8::internal::compiler::OperandGenerator::Label (turboshaft::Block * block) [inline]
Definition at line 334 of file instruction-selector-impl.h.
                                                   {
    return sequence()->AddImmediate(Constant(selector_->rpo_number(block)));
  }
References v8::internal::compiler::InstructionSequence::AddImmediate(), v8::internal::compiler::InstructionSelector::rpo_number(), selector_, and sequence().
Referenced by v8::internal::compiler::InstructionSelector::EmitBinarySearchSwitch(), v8::internal::compiler::InstructionSelector::EmitTableSwitch(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::compiler::InstructionSelector::VisitCall(), and v8::internal::compiler::InstructionSelector::VisitGoto().
NoOutput()
InstructionOperand v8::internal::compiler::OperandGenerator::NoOutput () [inline]
Definition at line 78 of file instruction-selector-impl.h.
                                {
    return InstructionOperand(); // Generates an invalid operand.
  }
Referenced by v8::internal::compiler::InstructionSelector::EmitPrepareArguments(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore(), v8::internal::compiler::InstructionSelector::VisitCall(), v8::internal::compiler::InstructionSelector::VisitGoto(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitOptimizedWord32Compare(), v8::internal::compiler::InstructionSelector::VisitRetain(), v8::internal::compiler::VisitStoreCommon(), v8::internal::compiler::InstructionSelector::VisitTailCall(), and v8::internal::compiler::InstructionSelector::VisitUnreachable().
selector()
InstructionSelector* v8::internal::compiler::OperandGenerator::selector () const [inline], [protected]
Definition at line 343 of file instruction-selector-impl.h.
{ return selector_; }
References selector_.
Referenced by Define(), DefineAsConstant(), sequence(), ToNegatedConstant(), turboshaft_graph(), Use(), and zone().
sequence()
InstructionSequence* v8::internal::compiler::OperandGenerator::sequence () const [inline], [protected]
Definition at line 344 of file instruction-selector-impl.h.
{ return selector()->sequence(); }
References selector(), and v8::internal::compiler::InstructionSelector::sequence().
Referenced by AllocateVirtualRegister(), DefineAsConstant(), Label(), TempDoubleRegister(), TempFpRegister(), TempImmediate(), TempLocation(), TempRegister(), TempSimd128Register(), TempSimd256Register(), UseImmediate(), UseImmediate64(), and UseNegatedImmediate().
TempDoubleRegister()
InstructionOperand v8::internal::compiler::OperandGenerator::TempDoubleRegister () [inline]
Definition at line 279 of file instruction-selector-impl.h.
                                          {
    UnallocatedOperand op = UnallocatedOperand(
        UnallocatedOperand::MUST_HAVE_REGISTER,
        UnallocatedOperand::USED_AT_START, sequence()->NextVirtualRegister());
    sequence()->MarkAsRepresentation(MachineRepresentation::kFloat64,
                                     op.virtual_register());
    return op;
  }
References v8::internal::kFloat64, v8::internal::compiler::InstructionSequence::MarkAsRepresentation(), v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, sequence(), v8::internal::compiler::UnallocatedOperand::USED_AT_START, and v8::internal::compiler::UnallocatedOperand::virtual_register().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitDiv().
TempFpRegister()
template<typename FPRegType >
InstructionOperand v8::internal::compiler::OperandGenerator::TempFpRegister (FPRegType reg) [inline]
Definition at line 317 of file instruction-selector-impl.h.
                                                   {
    UnallocatedOperand op =
        UnallocatedOperand(UnallocatedOperand::FIXED_FP_REGISTER, reg.code(),
                           sequence()->NextVirtualRegister());
    sequence()->MarkAsRepresentation(MachineRepresentation::kSimd128,
                                     op.virtual_register());
    return op;
  }
References v8::internal::compiler::UnallocatedOperand::FIXED_FP_REGISTER, v8::internal::kSimd128, v8::internal::compiler::InstructionSequence::MarkAsRepresentation(), sequence(), and v8::internal::compiler::UnallocatedOperand::virtual_register().
TempImmediate()
InstructionOperand v8::internal::compiler::OperandGenerator::TempImmediate (int32_t imm) [inline]
Definition at line 326 of file instruction-selector-impl.h.
                                                {
    return sequence()->AddImmediate(Constant(imm));
  }
References v8::internal::compiler::InstructionSequence::AddImmediate(), and sequence().
Referenced by v8::internal::compiler::InstructionSelector::AppendDeoptimizeArguments(), v8::internal::compiler::InstructionSelector::EmitBinarySearchSwitch(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::EmitS128Load(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitUbfx(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::EmitWordCompareZero(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitBitfieldExtract32(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitExtendingLoad(), v8::internal::compiler::TryEmitExtendingLoad(), v8::internal::compiler::TryMatchNegFromSub(), v8::internal::compiler::TryMatchShiftFromMul(), v8::internal::compiler::TryMatchSignExtInt16OrInt8FromWord32Sar(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAddSub(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitBinOp(), v8::internal::compiler::InstructionSelector::VisitCall(), v8::internal::compiler::turboshaft::VisitCompareChain(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitOptimizedWord32Compare(), v8::internal::compiler::InstructionSelector::VisitSwitch(), v8::internal::compiler::InstructionSelector::VisitTailCall(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitUnaryOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32EqualImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64EqualImpl(), and v8::internal::compiler::VisitWordCompare().
TempLocation()
InstructionOperand v8::internal::compiler::OperandGenerator::TempLocation (LinkageLocation location) [inline]
Definition at line 330 of file instruction-selector-impl.h.
                                                            {
    return ToUnallocatedOperand(location, sequence()->NextVirtualRegister());
  }
References sequence(), and ToUnallocatedOperand().
Referenced by v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), and UsePointerLocation().
TempRegister() [1/3]
InstructionOperand v8::internal::compiler::OperandGenerator::TempRegister () [inline]
Definition at line 245 of file instruction-selector-impl.h.
                                    {
    return UnallocatedOperand(UnallocatedOperand::MUST_HAVE_REGISTER,
                              UnallocatedOperand::USED_AT_START,
                              sequence()->NextVirtualRegister());
  }
References v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, sequence(), and v8::internal::compiler::UnallocatedOperand::USED_AT_START.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitAddBeforeS128LoadStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::EmitS128Load(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryEmitLoadForLoadWord64AndShiftRight(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicBinop(), v8::internal::compiler::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicExchange(), v8::internal::compiler::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitCompare(), v8::internal::compiler::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitDiv(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitDiv(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitFloatUnop(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitFullWord32Compare(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMulHigh(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMulHigh(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitOptimizedWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::VisitPairAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitROWithTemp(), v8::internal::compiler::InstructionSelector::VisitStackPointerGreaterThan(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), v8::internal::compiler::VisitStoreCommon(), v8::internal::compiler::InstructionSelector::VisitSwitch(), v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWord32PairShift(), v8::internal::compiler::VisitWord32PairShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitWord32PairShift(), and v8::internal::compiler::VisitWordCompare().
TempRegister() [2/3]
InstructionOperand v8::internal::compiler::OperandGenerator::TempRegister (int code) [inline]
Definition at line 311 of file instruction-selector-impl.h.
                                            {
    return UnallocatedOperand(UnallocatedOperand::FIXED_REGISTER, code,
                              sequence()->NextVirtualRegister());
  }
References code, v8::internal::compiler::UnallocatedOperand::FIXED_REGISTER, and sequence().
TempRegister() [3/3]
InstructionOperand v8::internal::compiler::OperandGenerator::TempRegister (Register reg) [inline]
Definition at line 306 of file instruction-selector-impl.h.
                                                {
    return UnallocatedOperand(UnallocatedOperand::FIXED_REGISTER, reg.code(),
                              InstructionOperand::kInvalidVirtualRegister);
  }
References v8::internal::compiler::UnallocatedOperand::FIXED_REGISTER, and v8::internal::compiler::InstructionOperand::kInvalidVirtualRegister.
TempSimd128Register()
InstructionOperand v8::internal::compiler::OperandGenerator::TempSimd128Register () [inline]
Definition at line 288 of file instruction-selector-impl.h.
                                           {
    UnallocatedOperand op = UnallocatedOperand(
        UnallocatedOperand::MUST_HAVE_REGISTER,
        UnallocatedOperand::USED_AT_START, sequence()->NextVirtualRegister());
    sequence()->MarkAsRepresentation(MachineRepresentation::kSimd128,
                                     op.virtual_register());
    return op;
  }
References v8::internal::kSimd128, v8::internal::compiler::InstructionSequence::MarkAsRepresentation(), v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, sequence(), v8::internal::compiler::UnallocatedOperand::USED_AT_START, and v8::internal::compiler::UnallocatedOperand::virtual_register().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBitMask(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitROWithTempSimd().
TempSimd256Register()
InstructionOperand v8::internal::compiler::OperandGenerator::TempSimd256Register () [inline]
Definition at line 297 of file instruction-selector-impl.h.
                                           {
    UnallocatedOperand op = UnallocatedOperand(
        UnallocatedOperand::MUST_HAVE_REGISTER,
        UnallocatedOperand::USED_AT_START, sequence()->NextVirtualRegister());
    sequence()->MarkAsRepresentation(MachineRepresentation::kSimd256,
                                     op.virtual_register());
    return op;
  }
References v8::internal::kSimd256, v8::internal::compiler::InstructionSequence::MarkAsRepresentation(), v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, sequence(), v8::internal::compiler::UnallocatedOperand::USED_AT_START, and v8::internal::compiler::UnallocatedOperand::virtual_register().
ToConstant()
Constant v8::internal::compiler::OperandGenerator::ToConstant (turboshaft::OpIndex node) [inline], [private]
Definition at line 352 of file instruction-selector-impl.h.
                                              {
    using Kind = turboshaft::ConstantOp::Kind;
    if (const turboshaft::ConstantOp* constant =
            selector_->TryCast<turboshaft::ConstantOp>(node)) {
      switch (constant->kind) {
        case Kind::kWord32:
          return Constant(static_cast<int32_t>(constant->word32()));
        case Kind::kWord64:
          return Constant(static_cast<int64_t>(constant->word64()));
        case Kind::kSmi:
          if constexpr (Is64()) {
            return Constant(static_cast<int64_t>(constant->smi().ptr()));
          } else {
            return Constant(static_cast<int32_t>(constant->smi().ptr()));
          }
        case Kind::kHeapObject:
        case Kind::kCompressedHeapObject:
        case Kind::kTrustedHeapObject:
          return Constant(constant->handle(),
                          constant->kind == Kind::kCompressedHeapObject);
        case Kind::kExternal:
          return Constant(constant->external_reference());
        case Kind::kNumber:
          return Constant(constant->number());
        case Kind::kFloat32:
          return Constant(constant->float32());
        case Kind::kFloat64:
          return Constant(constant->float64());
        case Kind::kTaggedIndex: {
          // Unencoded index value.
          intptr_t value = static_cast<intptr_t>(constant->tagged_index());
          DCHECK(TaggedIndex::IsValid(value));
          // Generate it as 32/64-bit constant in a tagged form.
          Address tagged_index = TaggedIndex::FromIntptr(value).ptr();
          if (kSystemPointerSize == kInt32Size) {
            return Constant(static_cast<int32_t>(tagged_index));
          } else {
            return Constant(static_cast<int64_t>(tagged_index));
          }
        }
        case Kind::kRelocatableWasmCall:
        case Kind::kRelocatableWasmStubCall: {
          uint64_t value = constant->integral();
          auto mode = constant->kind == Kind::kRelocatableWasmCall
                          ? RelocInfo::WASM_CALL
                          : RelocInfo::WASM_STUB_CALL;
          using constant_type = std::conditional_t<Is64(), int64_t, int32_t>;
          return Constant(RelocatablePtrConstantInfo(
              base::checked_cast<constant_type>(value), mode));
        }
        case Kind::kRelocatableWasmCanonicalSignatureId:
          return Constant(RelocatablePtrConstantInfo(
              base::checked_cast<int32_t>(constant->integral()),
              RelocInfo::WASM_CANONICAL_SIG_ID));
        case Kind::kRelocatableWasmIndirectCallTarget:
          uint64_t value = constant->integral();
          return Constant(RelocatablePtrConstantInfo(
              base::checked_cast<int32_t>(value),
              RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY));
      }
    }
    UNREACHABLE();
  }
References v8::internal::DCHECK(), v8::internal::TaggedIndex::FromIntptr(), v8::internal::Is64(), v8::internal::TaggedIndex::IsValid(), v8::internal::kInt32Size, v8::internal::compiler::kSmi, v8::internal::kSystemPointerSize, mode(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), selector_, v8::internal::compiler::turboshaft::OperationMatcher::TryCast(), v8::internal::UNREACHABLE(), v8::internal::value, v8::internal::RelocInfo::WASM_CALL, v8::internal::RelocInfo::WASM_CANONICAL_SIG_ID, v8::internal::RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY, and v8::internal::RelocInfo::WASM_STUB_CALL.
Referenced by DefineAsConstant(), and UseImmediate().
ToDualLocationUnallocatedOperand()
UnallocatedOperand v8::internal::compiler::OperandGenerator::ToDualLocationUnallocatedOperand (LinkageLocation primary_location, LinkageLocation secondary_location, int virtual_register) [inline], [private]
Definition at line 450 of file instruction-selector-impl.h.
                            {
    // We only support the primary location being a register and the secondary
    // one a slot.
    DCHECK(primary_location.IsRegister() &&
           secondary_location.IsCalleeFrameSlot());
    int reg_id = primary_location.AsRegister();
    int slot_id = secondary_location.AsCalleeFrameSlot();
    return UnallocatedOperand(reg_id, slot_id, virtual_register);
  }
References v8::internal::LinkageLocation::AsCalleeFrameSlot(), v8::internal::LinkageLocation::AsRegister(), v8::internal::DCHECK(), v8::internal::LinkageLocation::IsCalleeFrameSlot(), and v8::internal::LinkageLocation::IsRegister().
Referenced by DefineAsDualLocation().
ToNegatedConstant()
Constant v8::internal::compiler::OperandGenerator::ToNegatedConstant (turboshaft::OpIndex node) [inline], [private]
Definition at line 416 of file instruction-selector-impl.h.
                                                     {
    const turboshaft::ConstantOp& constant =
        selector()->Cast<turboshaft::ConstantOp>(node);
    switch (constant.kind) {
      case turboshaft::ConstantOp::Kind::kWord32:
        return Constant(-static_cast<int32_t>(constant.word32()));
      case turboshaft::ConstantOp::Kind::kWord64:
        return Constant(-static_cast<int64_t>(constant.word64()));
      case turboshaft::ConstantOp::Kind::kSmi:
        if (Is64()) {
          return Constant(-static_cast<int64_t>(constant.smi().ptr()));
        } else {
          return Constant(-static_cast<int32_t>(constant.smi().ptr()));
        }
      default:
        UNREACHABLE();
    }
  }
References v8::internal::compiler::turboshaft::OperationMatcher::Cast(), v8::internal::Is64(), v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::compiler::turboshaft::ConstantOp::kSmi, v8::internal::compiler::turboshaft::ConstantOp::kWord32, v8::internal::compiler::turboshaft::ConstantOp::kWord64, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), selector(), v8::internal::compiler::turboshaft::ConstantOp::smi(), v8::internal::UNREACHABLE(), v8::internal::compiler::turboshaft::ConstantOp::word32(), and v8::internal::compiler::turboshaft::ConstantOp::word64().
Referenced by UseNegatedImmediate().
ToUnallocatedOperand()
UnallocatedOperand v8::internal::compiler::OperandGenerator::ToUnallocatedOperand (LinkageLocation location, int virtual_register) [inline], [private]
Definition at line 462 of file instruction-selector-impl.h.
                                                                {
    if (location.IsAnyRegister() || location.IsNullRegister()) {
      // any machine register.
      return UnallocatedOperand(UnallocatedOperand::MUST_HAVE_REGISTER,
                                virtual_register);
    }
    if (location.IsCallerFrameSlot()) {
      // a location on the caller frame.
      return UnallocatedOperand(UnallocatedOperand::FIXED_SLOT,
                                location.AsCallerFrameSlot(), virtual_register);
    }
    if (location.IsCalleeFrameSlot()) {
      // a spill location on this (callee) frame.
      return UnallocatedOperand(UnallocatedOperand::FIXED_SLOT,
                                location.AsCalleeFrameSlot(), virtual_register);
    }
    // a fixed register.
    if (IsFloatingPoint(location.GetType().representation())) {
      return UnallocatedOperand(UnallocatedOperand::FIXED_FP_REGISTER,
                                location.AsRegister(), virtual_register);
    }
    return UnallocatedOperand(UnallocatedOperand::FIXED_REGISTER,
                              location.AsRegister(), virtual_register);
  }
References v8::internal::LinkageLocation::AsCalleeFrameSlot(), v8::internal::LinkageLocation::AsCallerFrameSlot(), v8::internal::LinkageLocation::AsRegister(), v8::internal::compiler::UnallocatedOperand::FIXED_FP_REGISTER, v8::internal::compiler::UnallocatedOperand::FIXED_REGISTER, v8::internal::compiler::UnallocatedOperand::FIXED_SLOT, v8::internal::LinkageLocation::GetType(), v8::internal::LinkageLocation::IsAnyRegister(), v8::internal::LinkageLocation::IsCalleeFrameSlot(), v8::internal::LinkageLocation::IsCallerFrameSlot(), v8::internal::IsFloatingPoint(), v8::internal::LinkageLocation::IsNullRegister(), v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, and v8::internal::MachineType::representation().
Referenced by DefineAsLocation(), TempLocation(), UseLocation(), and UsePointerLocation().
turboshaft_graph()
turboshaft::Graph* v8::internal::compiler::OperandGenerator::turboshaft_graph () const [inline]
Definition at line 338 of file instruction-selector-impl.h.
                                            {
    return selector()->turboshaft_graph();
  }
References selector(), and v8::internal::compiler::InstructionSelector::turboshaft_graph().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt().
Use() [1/2]
InstructionOperand v8::internal::compiler::OperandGenerator::Use (turboshaft::OpIndex node) [inline]
Definition at line 129 of file instruction-selector-impl.h.
                                                 {
    return Use(node, UnallocatedOperand(UnallocatedOperand::NONE,
                                        UnallocatedOperand::USED_AT_START,
                                        GetVReg(node)));
  }
References GetVReg(), v8::internal::compiler::UnallocatedOperand::NONE, and v8::internal::compiler::UnallocatedOperand::USED_AT_START.
Referenced by UseAny(), UseAnyAtEnd(), UseFixed(), UseLocation(), UseRegister(), UseRegisterAtEnd(), UseRegisterOrSlotOrConstant(), UseUnique(), UseUniqueRegister(), UseUniqueRegisterOrSlotOrConstant(), UseUniqueSlot(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareWithMemoryOperand(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMul(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitROWithTemp(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRROFloat(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitWordCompare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWordCompare().
Use() [2/2]
UnallocatedOperand v8::internal::compiler::OperandGenerator::Use (turboshaft::OpIndex node, UnallocatedOperand operand) [inline], [private]
Definition at line 443 of file instruction-selector-impl.h.
                                                                             {
    DCHECK(node.valid());
    DCHECK_EQ(operand.virtual_register(), GetVReg(node));
    selector()->MarkAsUsed(node);
    return operand;
  }
References v8::internal::DCHECK(), DCHECK_EQ, GetVReg(), v8::internal::compiler::InstructionSelector::MarkAsUsed(), selector(), v8::internal::compiler::turboshaft::OpIndex::valid(), and v8::internal::compiler::UnallocatedOperand::virtual_register().
UseAny()
InstructionOperand v8::internal::compiler::OperandGenerator::UseAny (turboshaft::OpIndex node) [inline]
Definition at line 141 of file instruction-selector-impl.h.
                                                    {
    return Use(node, UnallocatedOperand(UnallocatedOperand::REGISTER_OR_SLOT,
                                        UnallocatedOperand::USED_AT_START,
                                        GetVReg(node)));
  }
References GetVReg(), v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT, Use(), and v8::internal::compiler::UnallocatedOperand::USED_AT_START.
Referenced by v8::internal::compiler::InstructionSelector::VisitRetain().
UseAnyAtEnd()
InstructionOperand v8::internal::compiler::OperandGenerator::UseAnyAtEnd (turboshaft::OpIndex node) [inline]
Definition at line 135 of file instruction-selector-impl.h.
                                                         {
    return Use(node, UnallocatedOperand(UnallocatedOperand::REGISTER_OR_SLOT,
                                        UnallocatedOperand::USED_AT_END,
                                        GetVReg(node)));
  }
References GetVReg(), v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT, Use(), and v8::internal::compiler::UnallocatedOperand::USED_AT_END.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt().
UseFixed() [1/2]
template<typename FPRegType >
InstructionOperand v8::internal::compiler::OperandGenerator::UseFixed (turboshaft::OpIndex node, FPRegType reg) [inline]
Definition at line 208 of file instruction-selector-impl.h.
                                                                     {
    return Use(node, UnallocatedOperand(UnallocatedOperand::FIXED_FP_REGISTER,
                                        reg.code(), GetVReg(node)));
  }
References v8::internal::compiler::UnallocatedOperand::FIXED_FP_REGISTER, GetVReg(), and Use().
UseFixed() [2/2]
InstructionOperand v8::internal::compiler::OperandGenerator::UseFixed (turboshaft::OpIndex node, Register reg) [inline]
Definition at line 202 of file instruction-selector-impl.h.
                                                                    {
    return Use(node, UnallocatedOperand(UnallocatedOperand::FIXED_REGISTER,
                                        reg.code(), GetVReg(node)));
  }
References v8::internal::compiler::UnallocatedOperand::FIXED_REGISTER, GetVReg(), and Use().
Referenced by v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitDiv(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitDiv(), v8::internal::compiler::InstructionSelector::VisitFloat64Ieee754Binop(), v8::internal::compiler::InstructionSelector::VisitFloat64Ieee754Unop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMulHigh(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMulHigh(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::VisitPairAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRO(), v8::internal::compiler::VisitShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon(), v8::internal::compiler::VisitWord32PairShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32Shift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64Shift().
UseImmediate() [1/2]
InstructionOperand v8::internal::compiler::OperandGenerator::UseImmediate (int immediate) [inline]
Definition at line 213 of file instruction-selector-impl.h.
                                                 {
    return sequence()->AddImmediate(Constant(immediate));
  }
References v8::internal::compiler::InstructionSequence::AddImmediate(), and sequence().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitLoad(), v8::internal::compiler::InstructionSelector::EmitPrepareArguments(), v8::internal::compiler::InstructionSelector::EmitPrepareResults(), v8::internal::compiler::EmitS128Load(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitStore(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateRightOperands(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt(), v8::internal::compiler::TryMatchImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchImmediateOrShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchLoadStoreShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShift(), v8::internal::compiler::TryMatchShiftFromMul(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShiftImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryVisitWordShift(), v8::internal::compiler::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), v8::internal::compiler::InstructionSelector::VisitCall(), v8::internal::compiler::turboshaft::VisitCompareChain(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFloat32Compare(), v8::internal::compiler::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFloat64Compare(), v8::internal::compiler::VisitFloat64Compare(), v8::internal::compiler::VisitLoadCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMul(), v8::internal::compiler::VisitRRI(), v8::internal::compiler::VisitRRIR(), v8::internal::compiler::VisitShift(), v8::internal::compiler::VisitSimdShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon(), v8::internal::compiler::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWord32PairShift(), v8::internal::compiler::VisitWord32PairShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitWord32PairShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32Shift(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64Shift(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitWordCompare(), v8::internal::compiler::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitWordCompare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare().
UseImmediate() [2/2]
InstructionOperand v8::internal::compiler::OperandGenerator::UseImmediate (turboshaft::OpIndex node) [inline]
Definition at line 221 of file instruction-selector-impl.h.
                                                          {
    return sequence()->AddImmediate(ToConstant(node));
  }
References v8::internal::compiler::InstructionSequence::AddImmediate(), sequence(), and ToConstant().
UseImmediate64()
InstructionOperand v8::internal::compiler::OperandGenerator::UseImmediate64 (int64_t immediate) [inline]
Definition at line 217 of file instruction-selector-impl.h.
                                                       {
    return sequence()->AddImmediate(Constant(immediate));
  }
References v8::internal::compiler::InstructionSequence::AddImmediate(), and sequence().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt(), v8::internal::compiler::InstructionSelector::VisitCall(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), and v8::internal::compiler::InstructionSelector::VisitTailCall().
UseLocation()
InstructionOperand v8::internal::compiler::OperandGenerator::UseLocation (turboshaft::OpIndex node, LinkageLocation location) [inline]
Definition at line 229 of file instruction-selector-impl.h.
                                                           {
    return Use(node, ToUnallocatedOperand(location, GetVReg(node)));
  }
References GetVReg(), ToUnallocatedOperand(), and Use().
Referenced by v8::internal::compiler::InstructionSelector::InitializeCallBuffer().
UseNegatedImmediate()
InstructionOperand v8::internal::compiler::OperandGenerator::UseNegatedImmediate (turboshaft::OpIndex node) [inline]
Definition at line 225 of file instruction-selector-impl.h.
                                                                 {
    return sequence()->AddImmediate(ToNegatedConstant(node));
  }
References v8::internal::compiler::InstructionSequence::AddImmediate(), sequence(), and ToNegatedConstant().
UsePointerLocation()
InstructionOperand v8::internal::compiler::OperandGenerator::UsePointerLocation (LinkageLocation to_location, LinkageLocation from_location) [inline]
Definition at line 236 of file instruction-selector-impl.h.
                                                                       {
    UnallocatedOperand casted_from_operand =
        UnallocatedOperand::cast(TempLocation(from_location));
    selector_->Emit(kArchNop, casted_from_operand);
    return ToUnallocatedOperand(to_location,
                                casted_from_operand.virtual_register());
  }
References v8::internal::compiler::InstructionSelector::Emit(), selector_, TempLocation(), ToUnallocatedOperand(), and v8::internal::compiler::UnallocatedOperand::virtual_register().
Referenced by v8::internal::compiler::InstructionSelector::InitializeCallBuffer().
UseRegister() [1/2]
InstructionOperand v8::internal::compiler::OperandGenerator::UseRegister (turboshaft::OpIndex node) [inline]
Definition at line 160 of file instruction-selector-impl.h.
                                                         {
    return Use(node, UnallocatedOperand(UnallocatedOperand::MUST_HAVE_REGISTER,
                                        UnallocatedOperand::USED_AT_START,
                                        GetVReg(node)));
  }
References GetVReg(), v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, Use(), and v8::internal::compiler::UnallocatedOperand::USED_AT_START.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitBic(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitLoad(), v8::internal::compiler::InstructionSelector::EmitPrepareArguments(), v8::internal::compiler::EmitS128Load(), v8::internal::compiler::EmitSignExtendWord(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitUbfx(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::EmitWordCompareZero(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateBinOpOperands(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateRightOperands(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitBitfieldExtract32(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitExtendingLoad(), v8::internal::compiler::TryEmitExtendingLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyAdd(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplySub(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchAnyExtend(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchLoadStoreShift(), v8::internal::compiler::TryMatchNegFromSub(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShift(), v8::internal::compiler::TryMatchShiftFromMul(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShiftImmediate(), v8::internal::compiler::TryMatchSignExtInt16OrInt8FromWord32Sar(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryVisitWordShift(), UseRegister(), UseRegisterWithMode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAddSub(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBinop(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), v8::internal::compiler::InstructionSelector::VisitBitcastWord32PairToFloat64(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBitMask(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitCompare(), v8::internal::compiler::turboshaft::VisitCompareChain(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareWithMemoryOperand(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitDiv(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitFloat32Compare(), v8::internal::compiler::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitFloat64Compare(), v8::internal::compiler::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitFloatUnop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatUnop(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitFullWord32Compare(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::VisitInt32PairBinop(), v8::internal::compiler::VisitLoadCommon(), v8::internal::compiler::VisitLogical(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMinOrMax(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMul(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitOptimizedWord32Compare(), v8::internal::compiler::VisitPairAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRR(), v8::internal::compiler::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRR(), v8::internal::compiler::VisitRRI(), v8::internal::compiler::VisitRRIR(), v8::internal::compiler::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRROFloat(), v8::internal::compiler::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRRR(), v8::internal::compiler::VisitShift(), v8::internal::compiler::VisitSimdShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon(), v8::internal::compiler::VisitStoreCommon(), v8::internal::compiler::InstructionSelector::VisitSwitch(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTestUnderMask(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTryTruncateDouble(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitTryTruncateDouble(), v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32EqualImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32Shift(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64EqualImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64Shift(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitWordCompare(), v8::internal::compiler::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare(), v8::internal::compiler::InstructionSelector::VisitWordCompareZero(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWordTest().
UseRegister() [2/2]
InstructionOperand v8::internal::compiler::OperandGenerator::UseRegister (turboshaft::OpIndex node, RegisterUseKind unique_reg) [inline]
Definition at line 192 of file instruction-selector-impl.h.
                                                             {
    if (V8_LIKELY(unique_reg == RegisterUseKind::kUseRegister)) {
      return UseRegister(node);
    } else {
      DCHECK_EQ(unique_reg, RegisterUseKind::kUseUniqueRegister);
      return UseUniqueRegister(node);
    }
  }
References DCHECK_EQ, kUseRegister, kUseUniqueRegister, UseRegister(), UseUniqueRegister(), and V8_LIKELY.
UseRegisterAtEnd()
InstructionOperand v8::internal::compiler::OperandGenerator::UseRegisterAtEnd (turboshaft::OpIndex node) [inline]
Definition at line 166 of file instruction-selector-impl.h.
                                                              {
    return Use(node, UnallocatedOperand(UnallocatedOperand::MUST_HAVE_REGISTER,
                                        UnallocatedOperand::USED_AT_END,
                                        GetVReg(node)));
  }
References GetVReg(), v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, Use(), and v8::internal::compiler::UnallocatedOperand::USED_AT_END.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), and v8::internal::compiler::turboshaft::VisitCompareChain().
UseRegisterForVreg()
InstructionOperand v8::internal::compiler::OperandGenerator::UseRegisterForVreg (int vreg) [inline]
Definition at line 261 of file instruction-selector-impl.h.
                                                  {
    return UnallocatedOperand(UnallocatedOperand::MUST_HAVE_REGISTER,
                              UnallocatedOperand::USED_AT_START, vreg);
  }
References v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, and v8::internal::compiler::UnallocatedOperand::USED_AT_START.
UseRegisterOrSlotOrConstant()
InstructionOperand v8::internal::compiler::OperandGenerator::UseRegisterOrSlotOrConstant (turboshaft::OpIndex node) [inline]
Definition at line 147 of file instruction-selector-impl.h.
                                                                         {
    return Use(node, UnallocatedOperand(
                         UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT,
                         UnallocatedOperand::USED_AT_START, GetVReg(node)));
  }
References GetVReg(), v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT, Use(), and v8::internal::compiler::UnallocatedOperand::USED_AT_START.
UseRegisterWithMode()
InstructionOperand v8::internal::compiler::OperandGenerator::UseRegisterWithMode (turboshaft::OpIndex node, RegisterMode register_mode) [inline]
Definition at line 273 of file instruction-selector-impl.h.
                                                                     {
    return register_mode == kRegister ? UseRegister(node)
                                      : UseUniqueRegister(node);
  }
References kRegister, UseRegister(), and UseUniqueRegister().
Referenced by v8::internal::compiler::InstructionSelector::VisitStackPointerGreaterThan().
UseUnique()
InstructionOperand v8::internal::compiler::OperandGenerator::UseUnique (turboshaft::OpIndex node) [inline]
Definition at line 179 of file instruction-selector-impl.h.
                                                       {
    return Use(node,
               UnallocatedOperand(UnallocatedOperand::NONE, GetVReg(node)));
  }
References GetVReg(), v8::internal::compiler::UnallocatedOperand::NONE, and Use().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitDiv(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMod().
UseUniqueRegister()
InstructionOperand v8::internal::compiler::OperandGenerator::UseUniqueRegister (turboshaft::OpIndex node) [inline]
Definition at line 186 of file instruction-selector-impl.h.
                                                               {
    return Use(node, UnallocatedOperand(UnallocatedOperand::MUST_HAVE_REGISTER,
                                        GetVReg(node)));
  }
References GetVReg(), v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, and Use().
Referenced by v8::internal::compiler::EmitInt64MulWithOverflow(), UseRegister(), UseRegisterWithMode(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicBinop(), v8::internal::compiler::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicBinOp(), v8::internal::compiler::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitDiv(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::VisitInt32PairBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMulHigh(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMulHigh(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitROWithTempSimd(), v8::internal::compiler::VisitRRIR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon(), v8::internal::compiler::VisitStoreCommon(), v8::internal::compiler::VisitUniqueRRR(), v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWord32PairShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitWord32PairShift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitWordCompare().
UseUniqueRegisterOrSlotOrConstant()
InstructionOperand v8::internal::compiler::OperandGenerator::UseUniqueRegisterOrSlotOrConstant (turboshaft::OpIndex node) [inline]
Definition at line 153 of file instruction-selector-impl.h.
                              {
    return Use(node, UnallocatedOperand(
                         UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT,
                         GetVReg(node)));
  }
References GetVReg(), v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT, and Use().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp().
UseUniqueSlot()
InstructionOperand v8::internal::compiler::OperandGenerator::UseUniqueSlot (turboshaft::OpIndex node) [inline]
Definition at line 172 of file instruction-selector-impl.h.
                                                           {
    return Use(node, UnallocatedOperand(UnallocatedOperand::MUST_HAVE_SLOT,
                                        GetVReg(node)));
  }
References GetVReg(), v8::internal::compiler::UnallocatedOperand::MUST_HAVE_SLOT, and Use().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt().
zone()
Zone* v8::internal::compiler::OperandGenerator::zone () const [inline], [protected]
Definition at line 345 of file instruction-selector-impl.h.
{ return selector()->instruction_zone(); }
References v8::internal::compiler::InstructionSelector::instruction_zone(), and selector().
Member Data Documentation
selector_
InstructionSelector* v8::internal::compiler::OperandGenerator::selector_ [private]
Definition at line 488 of file instruction-selector-impl.h.
Referenced by GetVReg(), Label(), selector(), ToConstant(), and UsePointerLocation().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/instruction-selector-impl.h