v8::internal::maglev::MaglevCompilationUnit Class Reference
#include <maglev-compilation-unit.h>
Public Member Functions
MaglevCompilationUnit (MaglevCompilationInfo *info, DirectHandle< JSFunction > function)
MaglevCompilationUnit (MaglevCompilationInfo *info, const MaglevCompilationUnit *caller, compiler::SharedFunctionInfoRef shared_function_info, compiler::FeedbackCellRef feedback_cell)
MaglevCompilationUnit (MaglevCompilationInfo *info, const MaglevCompilationUnit *caller, int register_count, uint16_t parameter_count, uint16_t max_arguments)
MaglevCompilationInfo * info () const
const MaglevCompilationUnit * caller () const
compiler::JSHeapBroker * broker () const
LocalIsolate * local_isolate () const
Zone * zone () const
int register_count () const
uint16_t parameter_count () const
uint16_t max_arguments () const
bool is_osr () const
BytecodeOffset osr_offset () const
int inlining_depth () const
bool is_inline () const
bool has_graph_labeller () const
MaglevGraphLabeller * graph_labeller () const
compiler::SharedFunctionInfoRef shared_function_info () const
compiler::BytecodeArrayRef bytecode () const
compiler::FeedbackCellRef feedback_cell () const
compiler::FeedbackVectorRef feedback () const
void RegisterNodeInGraphLabeller (const Node *node)
const MaglevCompilationUnit * GetTopLevelCompilationUnit () const
Static Public Member Functions
static MaglevCompilationUnit * New (Zone *zone, MaglevCompilationInfo *info, Handle< JSFunction > function)
static MaglevCompilationUnit * NewInner (Zone *zone, const MaglevCompilationUnit *caller, compiler::SharedFunctionInfoRef shared_function_info, compiler::FeedbackCellRef feedback_cell)
static MaglevCompilationUnit * NewDummy (Zone *zone, const MaglevCompilationUnit *caller, int register_count, uint16_t parameter_count, uint16_t max_arguments)
Private Attributes
MaglevCompilationInfo *const info_
const MaglevCompilationUnit *const caller_
const compiler::OptionalSharedFunctionInfoRef shared_function_info_
const compiler::OptionalBytecodeArrayRef bytecode_
const compiler::OptionalFeedbackCellRef feedback_cell_
const int register_count_
const uint16_t parameter_count_
const uint16_t max_arguments_
const int inlining_depth_
Detailed Description
Definition at line 23 of file maglev-compilation-unit.h.
Constructor & Destructor Documentation
MaglevCompilationUnit() [1/3]
v8::internal::maglev::MaglevCompilationUnit::MaglevCompilationUnit (MaglevCompilationInfo * info, DirectHandle< JSFunction > function)
Definition at line 17 of file maglev-compilation-unit.cc.
    : MaglevCompilationUnit(
          info, nullptr,
          MakeRef(info->broker(), info->broker()->CanonicalPersistentHandle(
                                      function->shared())),
          MakeRef(info->broker(), info->broker()->CanonicalPersistentHandle(
                                      function->raw_feedback_cell()))) {}
MaglevCompilationUnit() [2/3]
v8::internal::maglev::MaglevCompilationUnit::MaglevCompilationUnit (MaglevCompilationInfo * info, const MaglevCompilationUnit * caller, compiler::SharedFunctionInfoRef shared_function_info, compiler::FeedbackCellRef feedback_cell)
Definition at line 26 of file maglev-compilation-unit.cc.
    : info_(info),
      caller_(caller),
      shared_function_info_(shared_function_info),
      bytecode_(shared_function_info.GetBytecodeArray(broker())),
      feedback_cell_(feedback_cell),
      register_count_(bytecode_->register_count()),
      parameter_count_(bytecode_->parameter_count()),
      max_arguments_(bytecode_->max_arguments()),
      inlining_depth_(caller == nullptr ? 0 : caller->inlining_depth_ + 1) {
  // Check that the parameter count in the bytecode and in the shared function
  // info are consistent.
  DCHECK_EQ(bytecode_->parameter_count(),
            shared_function_info
                .internal_formal_parameter_count_with_receiver_deprecated());
}
References bytecode_, DCHECK_EQ, v8::internal::compiler::SharedFunctionInfoRef::internal_formal_parameter_count_with_receiver_deprecated(), and shared_function_info().
MaglevCompilationUnit() [3/3]
v8::internal::maglev::MaglevCompilationUnit::MaglevCompilationUnit (MaglevCompilationInfo * info, const MaglevCompilationUnit * caller, int register_count, uint16_t parameter_count, uint16_t max_arguments)
Definition at line 46 of file maglev-compilation-unit.cc.
    : info_(info),
      caller_(caller),
      register_count_(register_count),
      parameter_count_(parameter_count),
      max_arguments_(max_arguments),
      inlining_depth_(caller == nullptr ? 0 : caller->inlining_depth_ + 1) {}
Member Function Documentation
broker()
compiler::JSHeapBroker * v8::internal::maglev::MaglevCompilationUnit::broker () const
Definition at line 56 of file maglev-compilation-unit.cc.
                                                          {
  return info_->broker();
}
References v8::internal::maglev::MaglevCompilationInfo::broker(), and info_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::FunctionContextSpecialization::TryToRef().
bytecode()
compiler::BytecodeArrayRef v8::internal::maglev::MaglevCompilationUnit::bytecode () const [inline]
Definition at line 74 of file maglev-compilation-unit.h.
{ return bytecode_.value(); }
Referenced by v8::internal::maglev::MaglevCompiler::Compile(), v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData(), v8::internal::maglev::DeoptFrame::GetBytecodeArray(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessGraph(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
caller()
const MaglevCompilationUnit* v8::internal::maglev::MaglevCompilationUnit::caller () const [inline]
Definition at line 58 of file maglev-compilation-unit.h.
{ return caller_; }
Referenced by GetTopLevelCompilationUnit().
feedback()
compiler::FeedbackVectorRef v8::internal::maglev::MaglevCompilationUnit::feedback () const [inline]
Definition at line 78 of file maglev-compilation-unit.h.
                                             {
    return feedback_cell().feedback_vector((broker())).value();
  }
References broker().
Referenced by v8::internal::maglev::MaglevCompiler::Compile(), and v8::internal::maglev::LoopOptimizationProcessor::LoopOptimizationProcessor().
feedback_cell()
compiler::FeedbackCellRef v8::internal::maglev::MaglevCompilationUnit::feedback_cell () const [inline]
Definition at line 75 of file maglev-compilation-unit.h.
                                                {
    return feedback_cell_.value();
  }
References v8::internal::compiler::FeedbackCellRef::value().
GetTopLevelCompilationUnit()
const MaglevCompilationUnit * v8::internal::maglev::MaglevCompilationUnit::GetTopLevelCompilationUnit () const
Definition at line 77 of file maglev-compilation-unit.cc.
          {
  const MaglevCompilationUnit* unit = this;
  while (unit->is_inline()) {
    unit = unit->caller();
  }
  return unit;
}
References caller(), and is_inline().
graph_labeller()
MaglevGraphLabeller * v8::internal::maglev::MaglevCompilationUnit::graph_labeller () const
Definition at line 66 of file maglev-compilation-unit.cc.
                                                                 {
  DCHECK(has_graph_labeller());
  return info_->graph_labeller();
}
References v8::internal::DCHECK(), v8::internal::maglev::MaglevCompilationInfo::graph_labeller(), has_graph_labeller(), and info_.
Referenced by v8::internal::maglev::InterpreterFrameState::CopyFrom(), and RegisterNodeInGraphLabeller().
has_graph_labeller()
bool v8::internal::maglev::MaglevCompilationUnit::has_graph_labeller () const
Definition at line 62 of file maglev-compilation-unit.cc.
                                                     {
  return info_->has_graph_labeller();
}
References v8::internal::maglev::MaglevCompilationInfo::has_graph_labeller(), and info_.
Referenced by graph_labeller(), and RegisterNodeInGraphLabeller().
info()
MaglevCompilationInfo* v8::internal::maglev::MaglevCompilationUnit::info () const [inline]
Definition at line 57 of file maglev-compilation-unit.h.
{ return info_; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadContextSlot(), v8::internal::maglev::MaglevGraphBuilder::BuildRegisterFrameInitialization(), v8::internal::maglev::MaglevGraphBuilder::MaglevGraphBuilder(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), NewDummy(), NewInner(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeLoadContextSlotToFunctionContext(), and v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::FunctionContextSpecialization::TryToRef().
inlining_depth()
int v8::internal::maglev::MaglevCompilationUnit::inlining_depth () const [inline]
Definition at line 67 of file maglev-compilation-unit.h.
{ return inlining_depth_; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::inlining_depth(), and v8::internal::maglev::MaglevGraphBuilder::MaglevGraphBuilder().
is_inline()
bool v8::internal::maglev::MaglevCompilationUnit::is_inline () const [inline]
Definition at line 68 of file maglev-compilation-unit.h.
{ return inlining_depth_ != 0; }
Referenced by GetTopLevelCompilationUnit().
is_osr()
bool v8::internal::maglev::MaglevCompilationUnit::is_osr () const
Definition at line 86 of file maglev-compilation-unit.cc.
                                         {
  return inlining_depth_ == 0 && info_->toplevel_is_osr();
}
References info_, inlining_depth_, and v8::internal::maglev::MaglevCompilationInfo::toplevel_is_osr().
Referenced by v8::internal::maglev::MaglevGraphBuilder::Build(), v8::internal::maglev::MaglevGraphBuilder::BuildRegisterFrameInitialization(), v8::internal::maglev::Graph::is_osr(), v8::internal::maglev::MaglevGraphBuilder::MaglevGraphBuilder(), osr_offset(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
local_isolate()
LocalIsolate* v8::internal::maglev::MaglevCompilationUnit::local_isolate () const
max_arguments()
uint16_t v8::internal::maglev::MaglevCompilationUnit::max_arguments () const [inline]
Definition at line 64 of file maglev-compilation-unit.h.
{ return max_arguments_; }
Referenced by v8::internal::maglev::MaxCallDepthProcessor::UpdateMaxDeoptedStackSize().
New()
static MaglevCompilationUnit* v8::internal::maglev::MaglevCompilationUnit::New (Zone * zone, MaglevCompilationInfo * info, Handle< JSFunction > function) [inline], [static]
Definition at line 25 of file maglev-compilation-unit.h.
                                                                 {
    return zone->New<MaglevCompilationUnit>(info, function);
  }
References v8::internal::Zone::New().
Referenced by v8::internal::maglev::MaglevCompilationInfo::MaglevCompilationInfo().
NewDummy()
static MaglevCompilationUnit* v8::internal::maglev::MaglevCompilationUnit::NewDummy (Zone * zone, const MaglevCompilationUnit * caller, int register_count, uint16_t parameter_count, uint16_t max_arguments) [inline], [static]
Definition at line 36 of file maglev-compilation-unit.h.
                                                                 {
    return zone->New<MaglevCompilationUnit>(
        caller->info(), caller, register_count, parameter_count, max_arguments);
  }
References info(), and v8::internal::Zone::New().
NewInner()
static MaglevCompilationUnit* v8::internal::maglev::MaglevCompilationUnit::NewInner (Zone * zone, const MaglevCompilationUnit * caller, compiler::SharedFunctionInfoRef shared_function_info, compiler::FeedbackCellRef feedback_cell) [inline], [static]
Definition at line 29 of file maglev-compilation-unit.h.
                                             {
    return zone->New<MaglevCompilationUnit>(
        caller->info(), caller, shared_function_info, feedback_cell);
  }
References info(), and v8::internal::Zone::New().
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction().
osr_offset()
BytecodeOffset v8::internal::maglev::MaglevCompilationUnit::osr_offset () const
Definition at line 90 of file maglev-compilation-unit.cc.
                                                       {
  return is_osr() ? info_->toplevel_osr_offset() : BytecodeOffset::None();
}
References info_, is_osr(), v8::internal::BytecodeOffset::None(), and v8::internal::maglev::MaglevCompilationInfo::toplevel_osr_offset().
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevGraphBuilder().
parameter_count()
uint16_t v8::internal::maglev::MaglevCompilationUnit::parameter_count () const [inline]
Definition at line 63 of file maglev-compilation-unit.h.
{ return parameter_count_; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddInlinedArgumentsToDeoptFrame(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::BeginLoop(), v8::internal::maglev::InterpretedDeoptFrame::ComputeReturnOffset(), v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize(), v8::internal::maglev::CompactInterpreterFrameState::context(), v8::internal::maglev::RegisterFrameArray< T >::CopyFrom(), v8::internal::maglev::CompactInterpreterFrameState::ForEachLocal(), v8::internal::maglev::CompactInterpreterFrameState::ForEachParameter(), v8::internal::maglev::CompactInterpreterFrameState::GetValueOf(), v8::internal::maglev::MaglevCodeGenState::parameter_count(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessGraph(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::maglev::RegisterFrameArray< T >::RegisterFrameArray(), v8::internal::maglev::CompactInterpreterFrameState::SizeFor(), and v8::internal::maglev::MaglevCodeGenState::stack_check_offset().
register_count()
int v8::internal::maglev::MaglevCompilationUnit::register_count () const [inline]
Definition at line 62 of file maglev-compilation-unit.h.
{ return register_count_; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::BeginLoop(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameValues(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), v8::internal::maglev::InterpretedDeoptFrame::ComputeReturnOffset(), v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize(), v8::internal::maglev::RegisterFrameArray< T >::CopyFrom(), and v8::internal::maglev::RegisterFrameArray< T >::RegisterFrameArray().
RegisterNodeInGraphLabeller()
void v8::internal::maglev::MaglevCompilationUnit::RegisterNodeInGraphLabeller (const Node * node)
Definition at line 71 of file maglev-compilation-unit.cc.
                                                                        {
  if (has_graph_labeller()) {
    graph_labeller()->RegisterNode(node);
  }
}
References graph_labeller(), has_graph_labeller(), and v8::internal::maglev::MaglevGraphLabeller::RegisterNode().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromFloat64ToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromHoleyFloat64ToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromInt32ToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromIntPtrToTagged(), and v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromUint32ToTagged().
shared_function_info()
compiler::SharedFunctionInfoRef v8::internal::maglev::MaglevCompilationUnit::shared_function_info () const [inline]
Definition at line 71 of file maglev-compilation-unit.h.
                                                             {
    return shared_function_info_.value();
  }
Referenced by v8::internal::maglev::MaglevGraphBuilder::Build(), v8::internal::maglev::MaglevCompiler::Compile(), v8::internal::maglev::MaglevCompiler::GenerateCode(), v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData(), v8::internal::maglev::DeoptFrame::GetSharedFunctionInfo(), MaglevCompilationUnit(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
zone()
Zone * v8::internal::maglev::MaglevCompilationUnit::zone () const
Definition at line 60 of file maglev-compilation-unit.cc.
{ return info_->zone(); }
References info_, and v8::internal::maglev::MaglevCompilationInfo::zone().
Referenced by v8::internal::maglev::MergePointInterpreterFrameState::New(), v8::internal::maglev::MergePointInterpreterFrameState::NewForCatchBlock(), v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop(), v8::internal::maglev::RegisterFrameArray< T >::RegisterFrameArray(), and v8::internal::maglev::MaglevGraphBuilder::zone().
Member Data Documentation
bytecode_
const compiler::OptionalBytecodeArrayRef v8::internal::maglev::MaglevCompilationUnit::bytecode_ [private]
Definition at line 89 of file maglev-compilation-unit.h.
Referenced by MaglevCompilationUnit().
caller_
const MaglevCompilationUnit* const v8::internal::maglev::MaglevCompilationUnit::caller_ [private]
Definition at line 87 of file maglev-compilation-unit.h.
feedback_cell_
const compiler::OptionalFeedbackCellRef v8::internal::maglev::MaglevCompilationUnit::feedback_cell_ [private]
Definition at line 90 of file maglev-compilation-unit.h.
info_
MaglevCompilationInfo* const v8::internal::maglev::MaglevCompilationUnit::info_ [private]
Definition at line 86 of file maglev-compilation-unit.h.
Referenced by broker(), graph_labeller(), has_graph_labeller(), is_osr(), osr_offset(), and zone().
inlining_depth_
const int v8::internal::maglev::MaglevCompilationUnit::inlining_depth_ [private]
Definition at line 94 of file maglev-compilation-unit.h.
Referenced by is_osr().
max_arguments_
const uint16_t v8::internal::maglev::MaglevCompilationUnit::max_arguments_ [private]
Definition at line 93 of file maglev-compilation-unit.h.
parameter_count_
const uint16_t v8::internal::maglev::MaglevCompilationUnit::parameter_count_ [private]
Definition at line 92 of file maglev-compilation-unit.h.
register_count_
const int v8::internal::maglev::MaglevCompilationUnit::register_count_ [private]
Definition at line 91 of file maglev-compilation-unit.h.
shared_function_info_
const compiler::OptionalSharedFunctionInfoRef v8::internal::maglev::MaglevCompilationUnit::shared_function_info_ [private]
Definition at line 88 of file maglev-compilation-unit.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-compilation-unit.h
/mnt/V8SourceCode/src/maglev/maglev-compilation-unit.cc