v8::internal::BuiltinsEffectsAnalyzer Class Reference
#include <builtins-effects-analyzer.h>
Public Member Functions
void RegisterInitialEffects (Builtin builtin, BuiltinAllocateEffect effects, std::unordered_set< Builtin > callees)
void Finalize ()
void Write (const char *file)
bool is_finalized () const
Static Public Member Functions
static BuiltinsEffectsAnalyzer * Setup (Isolate *isolate)
static void TearDown (Isolate *isolate)
Private Attributes
std::array< BuiltinEffects, Builtins::kBuiltinCount > builtins_effects_
bool is_finalized_ = false
base::Mutex mutex_
Detailed Description
Definition at line 48 of file builtins-effects-analyzer.h.
Member Function Documentation
Finalize()
void v8::internal::BuiltinsEffectsAnalyzer::Finalize ()
Definition at line 81 of file builtins-effects-analyzer.cc.
                                       {
  CHECK(!is_finalized_);
  for (size_t i = 0; i < builtins_effects_.size(); i++) {
    FinalizeBuiltin(static_cast<Builtin>(i), builtins_effects_);
    CHECK(builtins_effects_[i].is_finalized);
  }
  is_finalized_ = true;
}
References builtins_effects_, CHECK, v8::internal::FinalizeBuiltin(), is_finalized(), and is_finalized_.
Referenced by v8::internal::SetupIsolateDelegate::SetupBuiltinsInternal().
is_finalized()
bool v8::internal::BuiltinsEffectsAnalyzer::is_finalized () const [inline]
Definition at line 57 of file builtins-effects-analyzer.h.
{ return is_finalized_; }
References is_finalized_.
Referenced by Finalize(), and TearDown().
RegisterInitialEffects()
void v8::internal::BuiltinsEffectsAnalyzer::RegisterInitialEffects (Builtin builtin, BuiltinAllocateEffect effects, std::unordered_set< Builtin > callees)
Definition at line 28 of file builtins-effects-analyzer.cc.
                                       {
  base::MutexGuard guard(&mutex_);
  size_t builtin_id = static_cast<size_t>(builtin);
  builtins_effects_[builtin_id] = {effects, callees};
}
References builtins_effects_, and mutex_.
Referenced by v8::internal::compiler::turboshaft::CsaEffectsComputationPhase::Run().
Setup()
BuiltinsEffectsAnalyzer * v8::internal::BuiltinsEffectsAnalyzer::Setup (Isolate * isolate) [static]
Definition at line 14 of file builtins-effects-analyzer.cc.
                                                                        {
  BuiltinsEffectsAnalyzer* analyzer = new BuiltinsEffectsAnalyzer();
  isolate->set_builtins_effects_analyzer(analyzer);
  return analyzer;
}
References v8::internal::Isolate::set_builtins_effects_analyzer().
Referenced by v8::internal::SetupIsolateDelegate::SetupBuiltinsInternal().
TearDown()
void v8::internal::BuiltinsEffectsAnalyzer::TearDown (Isolate * isolate) [static]
Definition at line 21 of file builtins-effects-analyzer.cc.
                                                       {
  BuiltinsEffectsAnalyzer* analyzer = isolate->builtins_effects_analyzer();
  DCHECK(analyzer->is_finalized());
  isolate->set_builtins_effects_analyzer(nullptr);
  delete analyzer;
}
References v8::internal::Isolate::builtins_effects_analyzer(), v8::internal::DCHECK(), is_finalized(), and v8::internal::Isolate::set_builtins_effects_analyzer().
Referenced by main().
Write()
void v8::internal::BuiltinsEffectsAnalyzer::Write (const char * file)
Definition at line 94 of file builtins-effects-analyzer.cc.
                                                    {
  CHECK(is_finalized_);
  CHECK_NOT_NULL(file);
  std::ofstream out(file, std::ios::out);
  out << "// Copyright 2025 the V8 project authors. All rights reserved.\n"
      << "// Use of this source code is governed by a BSD-style license "
         "that can be\n"
      << "// found in the LICENSE file.\n"
      << "\n"
      << "// This file is automatically generated by mksnapshot (more "
         "precisely, by\n"
      << "// BuiltinsEffectsState::write in builtins.cc). Do not edit "
         "manually.\n"
      << "\n"
      << "#include \"src/builtins/builtins.h\"\n"
      << "\n"
      << "namespace v8::internal {\n"
      << "\n"
      << "bool BuiltinCanAllocate(Builtin builtin) {\n"
      << " switch (builtin) {\n";
  for (size_t id = 0; id < builtins_effects_.size(); id++) {
    BuiltinEffects effects = builtins_effects_[id];
    CHECK(effects.is_finalized);
    out << " case Builtin::k" << Builtins::name(static_cast<Builtin>(id))
        << ":\n";
    switch (effects.can_allocate) {
      case BuiltinAllocateEffect::kNo:
        out << " return false;\n";
        break;
      case BuiltinAllocateEffect::kYes:
        out << " return true;\n";
        break;
      case BuiltinAllocateEffect::kMaybeWithBuiltinCall:
      case BuiltinAllocateEffect::kUninitialized:
        UNREACHABLE();
    }
  }
  out << " case Builtin::kNoBuiltinId:\n"
      << " UNREACHABLE();\n"
      << " }\n"
      << " UNREACHABLE();\n"
      << "}\n"
      << "\n"
      << "} // namespace v8::internal\n";
  out.close();
}
References builtins_effects_, v8::internal::BuiltinEffects::can_allocate, CHECK, CHECK_NOT_NULL, file(), v8::internal::BuiltinEffects::is_finalized, is_finalized_, v8::internal::kMaybeWithBuiltinCall, v8::internal::kNo, v8::internal::kUninitialized, v8::internal::kYes, v8::internal::Builtins::name(), and v8::internal::UNREACHABLE().
Referenced by main().
Member Data Documentation
builtins_effects_
std::array<BuiltinEffects, Builtins::kBuiltinCount> v8::internal::BuiltinsEffectsAnalyzer::builtins_effects_ [private]
Definition at line 63 of file builtins-effects-analyzer.h.
Referenced by Finalize(), RegisterInitialEffects(), and Write().
is_finalized_
bool v8::internal::BuiltinsEffectsAnalyzer::is_finalized_ = false [private]
Definition at line 64 of file builtins-effects-analyzer.h.
Referenced by Finalize(), is_finalized(), and Write().
mutex_
base::Mutex v8::internal::BuiltinsEffectsAnalyzer::mutex_ [private]
Definition at line 68 of file builtins-effects-analyzer.h.
Referenced by RegisterInitialEffects().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-effects-analyzer.h
/mnt/V8SourceCode/src/builtins/builtins-effects-analyzer.cc