v8::internal::AllocationSiteContext Class Reference
#include <allocation-site-scopes.h>
Public Member Functions
AllocationSiteContext (Isolate *isolate)
DirectHandle< AllocationSite > top ()
DirectHandle< AllocationSite > current ()
bool ShouldCreateMemento (DirectHandle< JSObject > object)
Isolate * isolate ()
Protected Member Functions
void update_current_site (Tagged< AllocationSite > site)
void InitializeTraversal (Handle< AllocationSite > site)
Private Attributes
Isolate * isolate_
Handle< AllocationSite > top_
Handle< AllocationSite > current_
Detailed Description
Definition at line 18 of file allocation-site-scopes.h.
Constructor & Destructor Documentation
AllocationSiteContext()
v8::internal::AllocationSiteContext::AllocationSiteContext (Isolate * isolate) [inline], [explicit]
Definition at line 20 of file allocation-site-scopes.h.
{ isolate_ = isolate; }
References isolate(), and isolate_.
Member Function Documentation
current()
DirectHandle<AllocationSite> v8::internal::AllocationSiteContext::current () [inline]
Definition at line 23 of file allocation-site-scopes.h.
{ return current_; }
References current_.
Referenced by v8::internal::AllocationSiteUsageContext::EnterNewScope().
InitializeTraversal()
void v8::internal::AllocationSiteContext::InitializeTraversal (Handle< AllocationSite > site) [inline], [protected]
Definition at line 16 of file allocation-site-scopes-inl.h.
                                                                           {
  top_ = site;
  // {current_} is updated in place to not create unnecessary Handles, hence
  // we initially need a separate handle.
  current_ = Handle<AllocationSite>::New(*top_, isolate());
}
References current_, isolate(), v8::internal::Handle< T >::New(), and top_.
Referenced by v8::internal::AllocationSiteUsageContext::EnterNewScope().
isolate()
Isolate* v8::internal::AllocationSiteContext::isolate () [inline]
Definition at line 27 of file allocation-site-scopes.h.
{ return isolate_; }
References isolate_.
Referenced by AllocationSiteContext(), v8::internal::AllocationSiteUsageContext::EnterNewScope(), and InitializeTraversal().
ShouldCreateMemento()
bool v8::internal::AllocationSiteContext::ShouldCreateMemento (DirectHandle< JSObject > object) [inline]
Definition at line 25 of file allocation-site-scopes.h.
{ return false; }
top()
DirectHandle<AllocationSite> v8::internal::AllocationSiteContext::top () [inline]
Definition at line 22 of file allocation-site-scopes.h.
{ return top_; }
References top_.
Referenced by v8::internal::AllocationSiteUsageContext::EnterNewScope().
update_current_site()
void v8::internal::AllocationSiteContext::update_current_site (Tagged< AllocationSite > site) [inline], [protected]
Definition at line 30 of file allocation-site-scopes.h.
                                                        {
    current_.PatchValue(site);
  }
References current_.
Referenced by v8::internal::AllocationSiteUsageContext::EnterNewScope().
Member Data Documentation
current_
Handle<AllocationSite> v8::internal::AllocationSiteContext::current_ [private]
Definition at line 39 of file allocation-site-scopes.h.
Referenced by current(), InitializeTraversal(), and update_current_site().
isolate_
Isolate* v8::internal::AllocationSiteContext::isolate_ [private]
Definition at line 37 of file allocation-site-scopes.h.
Referenced by AllocationSiteContext(), and isolate().
top_
Handle<AllocationSite> v8::internal::AllocationSiteContext::top_ [private]
Definition at line 38 of file allocation-site-scopes.h.
Referenced by InitializeTraversal(), and top().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/allocation-site-scopes.h
/mnt/V8SourceCode/src/objects/allocation-site-scopes-inl.h