v8::internal::MicrotaskQueue Class Reference
#include <microtask-queue.h>
Public Member Functions
~MicrotaskQueue () override
void EnqueueMicrotask (v8::Isolate *isolate, v8::Local< Function > microtask) override
Enqueues the callback to the queue.
void EnqueueMicrotask (v8::Isolate *isolate, v8::MicrotaskCallback callback, void *data) override
Enqueues the callback to the queue.
void PerformCheckpoint (v8::Isolate *isolate) override
Runs microtasks if no microtask is running on this MicrotaskQueue instance.
bool ShouldPerfomCheckpoint () const
void EnqueueMicrotask (Tagged< Microtask > microtask)
void AddMicrotasksCompletedCallback (MicrotasksCompletedCallbackWithData callback, void *data) override
Adds a callback to notify the embedder after microtasks were run.
void RemoveMicrotasksCompletedCallback (MicrotasksCompletedCallbackWithData callback, void *data) override
Removes callback that was installed by AddMicrotasksCompletedCallback.
bool IsRunningMicrotasks () const override
Returns true if a microtask is running on this MicrotaskQueue instance.
int RunMicrotasks (Isolate *isolate)
void IterateMicrotasks (RootVisitor *visitor)
void IncrementMicrotasksScopeDepth ()
void DecrementMicrotasksScopeDepth ()
int GetMicrotasksScopeDepth () const override
Returns the current depth of nested MicrotasksScope that has kRunMicrotasks.
void IncrementMicrotasksSuppressions ()
void DecrementMicrotasksSuppressions ()
bool HasMicrotasksSuppressions () const
void set_microtasks_policy (v8::MicrotasksPolicy microtasks_policy)
v8::MicrotasksPolicy microtasks_policy () const
intptr_t capacity () const
intptr_t size () const
intptr_t start () const
Tagged< Microtask > get (intptr_t index) const
MicrotaskQueue * next () const
MicrotaskQueue * prev () const
Static Public Member Functions
static void SetUpDefaultMicrotaskQueue (Isolate *isolate)
static std::unique_ptr< MicrotaskQueue > New (Isolate *isolate)
static Address CallEnqueueMicrotask (Isolate *isolate, intptr_t microtask_queue_pointer, Address raw_microtask)
Static Public Attributes
static const size_t kRingBufferOffset
static const size_t kCapacityOffset
static const size_t kSizeOffset = OFFSET_OF(MicrotaskQueue, size_)
static const size_t kStartOffset = OFFSET_OF(MicrotaskQueue, start_)
static const size_t kFinishedMicrotaskCountOffset
static const intptr_t kMinimumCapacity = 8
Private Types
using CallbackWithData = std::pair< MicrotasksCompletedCallbackWithData, void * >
Private Member Functions
void PerformCheckpointInternal (v8::Isolate *v8_isolate)
void OnCompleted (Isolate *isolate)
MicrotaskQueue ()
void ResizeBuffer (intptr_t new_capacity)
Private Attributes
intptr_t size_ = 0
intptr_t capacity_ = 0
intptr_t start_ = 0
Address * ring_buffer_ = nullptr
intptr_t finished_microtask_count_ = 0
MicrotaskQueue * next_ = nullptr
MicrotaskQueue * prev_ = nullptr
int microtasks_depth_ = 0
int microtasks_suppressions_ = 0
v8::MicrotasksPolicy microtasks_policy_ = v8::MicrotasksPolicy::kAuto
bool is_running_microtasks_ = false
bool is_running_completed_callbacks_ = false
std::vector< CallbackWithData > microtasks_completed_callbacks_
std::optional< std::vector< CallbackWithData > > microtasks_completed_callbacks_cow_
Detailed Description
Definition at line 27 of file microtask-queue.h.
Member Typedef Documentation
CallbackWithData
using v8::internal::MicrotaskQueue::CallbackWithData = std::pair<MicrotasksCompletedCallbackWithData, void*> [private]
Definition at line 152 of file microtask-queue.h.
Constructor & Destructor Documentation
 MicrotaskQueue()
v8::internal::MicrotaskQueue::~MicrotaskQueue () [override], [virtual]
Reimplemented from v8::MicrotaskQueue.
Definition at line 62 of file microtask-queue.cc.
                                {
  if (next_ != this) {
    DCHECK_NE(prev_, this);
    next_->prev_ = prev_;
    prev_->next_ = next_;
  }
  delete[] ring_buffer_;
}
References DCHECK_NE, next_, prev_, and ring_buffer_.
MicrotaskQueue()
v8::internal::MicrotaskQueue::MicrotaskQueue () [private], [default]
Referenced by SetUpDefaultMicrotaskQueue().
Member Function Documentation
AddMicrotasksCompletedCallback()
void v8::internal::MicrotaskQueue::AddMicrotasksCompletedCallback (MicrotasksCompletedCallbackWithData callback, void * data) [override], [virtual]
Adds a callback to notify the embedder after microtasks were run.
The callback is triggered by explicit RunMicrotasks call or automatic microtasks execution (see Isolate::SetMicrotasksPolicy).
Callback will trigger even if microtasks were attempted to run, but the microtasks queue was empty and no single microtask was actually executed.
Executing scripts inside the callback will not re-trigger microtasks and the callback.
Implements v8::MicrotaskQueue.
Definition at line 244 of file microtask-queue.cc.
                                                              {
  std::vector<CallbackWithData>* microtasks_completed_callbacks =
      &microtasks_completed_callbacks_;
  if (is_running_completed_callbacks_) {
    if (!microtasks_completed_callbacks_cow_.has_value()) {
      microtasks_completed_callbacks_cow_.emplace(
          microtasks_completed_callbacks_);
    }
    // Use the COW vector if we are iterating the callbacks right now.
    microtasks_completed_callbacks =
        &microtasks_completed_callbacks_cow_.value();
  }
  CallbackWithData callback_with_data(callback, data);
  const auto pos =
      std::find(microtasks_completed_callbacks->begin(),
                microtasks_completed_callbacks->end(), callback_with_data);
  if (pos != microtasks_completed_callbacks->end()) {
    return;
  }
  microtasks_completed_callbacks->push_back(callback_with_data);
}
References is_running_completed_callbacks_, microtasks_completed_callbacks_, and microtasks_completed_callbacks_cow_.
CallEnqueueMicrotask()
Address v8::internal::MicrotaskQueue::CallEnqueueMicrotask (Isolate * isolate, intptr_t microtask_queue_pointer, Address raw_microtask) [static]
Definition at line 72 of file microtask-queue.cc.
                                                                    {
  Tagged<Microtask> microtask = Cast<Microtask>(Tagged<Object>(raw_microtask));
  reinterpret_cast<MicrotaskQueue*>(microtask_queue_pointer)
      ->EnqueueMicrotask(microtask);
  return Smi::zero().ptr();
}
References EnqueueMicrotask(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::Smi::zero().
capacity()
intptr_t v8::internal::MicrotaskQueue::capacity () const [inline]
Definition at line 101 of file microtask-queue.h.
{ return capacity_; }
DecrementMicrotasksScopeDepth()
void v8::internal::MicrotaskQueue::DecrementMicrotasksScopeDepth () [inline]
Definition at line 75 of file microtask-queue.h.
{ --microtasks_depth_; }
Referenced by v8::MicrotasksScope::~MicrotasksScope().
DecrementMicrotasksSuppressions()
void v8::internal::MicrotaskQueue::DecrementMicrotasksSuppressions () [inline]
Definition at line 81 of file microtask-queue.h.
{ --microtasks_suppressions_; }
EnqueueMicrotask() [1/3]
void v8::internal::MicrotaskQueue::EnqueueMicrotask (Tagged< Microtask > microtask)
Definition at line 103 of file microtask-queue.cc.
                                                                 {
  if (size_ == capacity_) {
    // Keep the capacity of |ring_buffer_| power of 2, so that the JIT
    // implementation can calculate the modulo easily.
    intptr_t new_capacity = std::max(kMinimumCapacity, capacity_ << 1);
    ResizeBuffer(new_capacity);
  }
  DCHECK_LT(size_, capacity_);
  ring_buffer_[(start_ + size_) % capacity_] = microtask.ptr();
  ++size_;
}
References capacity_, DCHECK_LT, kMinimumCapacity, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), ResizeBuffer(), ring_buffer_, size_, and start_.
EnqueueMicrotask() [2/3]
void v8::internal::MicrotaskQueue::EnqueueMicrotask (v8::Isolate * isolate, v8::Local< Function > microtask) [override], [virtual]
Enqueues the callback to the queue.
Implements v8::MicrotaskQueue.
Definition at line 81 of file microtask-queue.cc.
                                                                  {
  Isolate* isolate = reinterpret_cast<Isolate*>(v8_isolate);
  HandleScope scope(isolate);
  DirectHandle<CallableTask> microtask = isolate->factory()->NewCallableTask(
      Utils::OpenDirectHandle(*function), isolate->native_context());
  EnqueueMicrotask(*microtask);
}
References v8::internal::Isolate::factory(), v8::internal::Isolate::native_context(), v8::internal::Factory::NewCallableTask(), and v8::Utils::OpenDirectHandle().
Referenced by CallEnqueueMicrotask(), EnqueueMicrotask(), v8::internal::JSPromise::Resolve(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::JSPromise::TriggerPromiseReactions().
EnqueueMicrotask() [3/3]
void v8::internal::MicrotaskQueue::EnqueueMicrotask (v8::Isolate * isolate, v8::MicrotaskCallback callback, void * data) [override], [virtual]
Enqueues the callback to the queue.
Implements v8::MicrotaskQueue.
Definition at line 90 of file microtask-queue.cc.
                                                  {
  Isolate* isolate = reinterpret_cast<Isolate*>(v8_isolate);
  HandleScope scope(isolate);
  DirectHandle<CallbackTask> microtask = isolate->factory()->NewCallbackTask(
      isolate->factory()->NewForeign<kMicrotaskCallbackTag>(
          reinterpret_cast<Address>(callback)),
      isolate->factory()->NewForeign<kMicrotaskCallbackDataTag>(
          reinterpret_cast<Address>(data)));
  EnqueueMicrotask(*microtask);
}
References EnqueueMicrotask(), v8::internal::Isolate::factory(), v8::internal::kMicrotaskCallbackDataTag, v8::internal::kMicrotaskCallbackTag, v8::internal::Factory::NewCallbackTask(), and v8::internal::Factory::NewForeign().
get()
Tagged< Microtask > v8::internal::MicrotaskQueue::get (intptr_t index) const
Definition at line 305 of file microtask-queue.cc.
                                                          {
  DCHECK_LT(index, size_);
  Tagged<Object> microtask(ring_buffer_[(index + start_) % capacity_]);
  return Cast<Microtask>(microtask);
}
References capacity_, DCHECK_LT, v8::internal::index, ring_buffer_, size_, and start_.
Referenced by New().
GetMicrotasksScopeDepth()
int v8::internal::MicrotaskQueue::GetMicrotasksScopeDepth () const [inline], [override], [virtual]
Returns the current depth of nested MicrotasksScope that has kRunMicrotasks.
Implements v8::MicrotaskQueue.
Definition at line 76 of file microtask-queue.h.
{ return microtasks_depth_; }
Referenced by v8::internal::anonymous_namespace{context-serializer.cc}::SanitizeNativeContextScope::SanitizeNativeContextScope(), and v8::CallDepthScope< do_callback >::~CallDepthScope().
HasMicrotasksSuppressions()
bool v8::internal::MicrotaskQueue::HasMicrotasksSuppressions () const [inline]
Definition at line 82 of file microtask-queue.h.
                                         {
    return microtasks_suppressions_ != 0;
  }
Referenced by v8::internal::anonymous_namespace{context-serializer.cc}::SanitizeNativeContextScope::SanitizeNativeContextScope().
IncrementMicrotasksScopeDepth()
void v8::internal::MicrotaskQueue::IncrementMicrotasksScopeDepth () [inline]
Definition at line 74 of file microtask-queue.h.
{ ++microtasks_depth_; }
Referenced by v8::MicrotasksScope::MicrotasksScope().
IncrementMicrotasksSuppressions()
void v8::internal::MicrotaskQueue::IncrementMicrotasksSuppressions () [inline]
Definition at line 80 of file microtask-queue.h.
{ ++microtasks_suppressions_; }
Referenced by v8::Isolate::SuppressMicrotaskExecutionScope::SuppressMicrotaskExecutionScope().
IsRunningMicrotasks()
bool v8::internal::MicrotaskQueue::IsRunningMicrotasks () const [inline], [override], [virtual]
Returns true if a microtask is running on this MicrotaskQueue instance.
Implements v8::MicrotaskQueue.
Definition at line 61 of file microtask-queue.h.
{ return is_running_microtasks_; }
IterateMicrotasks()
void v8::internal::MicrotaskQueue::IterateMicrotasks (RootVisitor * visitor)
Definition at line 217 of file microtask-queue.cc.
                                                           {
  if (size_) {
    // Iterate pending Microtasks as root objects to avoid the write barrier for
    // all single Microtask. If this hurts the GC performance, use a FixedArray.
    visitor->VisitRootPointers(
        Root::kMicroTasks, nullptr, FullObjectSlot(ring_buffer_ + start_),
        FullObjectSlot(ring_buffer_ + std::min(start_ + size_, capacity_)));
    visitor->VisitRootPointers(
        Root::kMicroTasks, nullptr, FullObjectSlot(ring_buffer_),
        FullObjectSlot(ring_buffer_ + std::max(start_ + size_ - capacity_,
                                               static_cast<intptr_t>(0))));
  }
  if (capacity_ <= kMinimumCapacity) {
    return;
  }
  intptr_t new_capacity = capacity_;
  while (new_capacity > 2 * size_) {
    new_capacity >>= 1;
  }
  new_capacity = std::max(new_capacity, kMinimumCapacity);
  if (new_capacity < capacity_) {
    ResizeBuffer(new_capacity);
  }
}
References capacity_, kMinimumCapacity, ResizeBuffer(), ring_buffer_, size_, start_, and v8::internal::RootVisitor::VisitRootPointers().
Referenced by v8::internal::Heap::IterateRoots().
microtasks_policy()
v8::MicrotasksPolicy v8::internal::MicrotaskQueue::microtasks_policy () const [inline]
Definition at line 99 of file microtask-queue.h.
{ return microtasks_policy_; }
Referenced by v8::internal::Isolate::FireCallCompletedCallbackInternal(), v8::CallDepthScope< do_callback >::operator=(), v8::internal::FinalizationRegistryCleanupTask::RunInternal(), v8::CallDepthScope< do_callback >::~CallDepthScope(), and v8::MicrotasksScope::~MicrotasksScope().
New()
std::unique_ptr< MicrotaskQueue > v8::internal::MicrotaskQueue::New (Isolate * isolate) [static]
Definition at line 45 of file microtask-queue.cc.
                                                                  {
  DCHECK_NOT_NULL(isolate->default_microtask_queue());
  std::unique_ptr<MicrotaskQueue> microtask_queue(new MicrotaskQueue);
  // Insert the new instance to the next of last MicrotaskQueue instance.
  MicrotaskQueue* last = isolate->default_microtask_queue()->prev_;
  microtask_queue->next_ = last->next_;
  microtask_queue->prev_ = last;
  last->next_->prev_ = microtask_queue.get();
  last->next_ = microtask_queue.get();
  return microtask_queue;
}
References DCHECK_NOT_NULL, get(), next_, and prev_.
Referenced by v8::MicrotaskQueue::New().
next()
MicrotaskQueue* v8::internal::MicrotaskQueue::next () const [inline]
Definition at line 107 of file microtask-queue.h.
{ return next_; }
Referenced by v8::internal::Heap::IterateRoots().
OnCompleted()
void v8::internal::MicrotaskQueue::OnCompleted (Isolate * isolate) [private]
Definition at line 292 of file microtask-queue.cc.
                                                 {
  is_running_completed_callbacks_ = true;
  for (auto& callback : microtasks_completed_callbacks_) {
    callback.first(reinterpret_cast<v8::Isolate*>(isolate), callback.second);
  }
  is_running_completed_callbacks_ = false;
  if (V8_UNLIKELY(microtasks_completed_callbacks_cow_.has_value())) {
    microtasks_completed_callbacks_ =
        std::move(microtasks_completed_callbacks_cow_.value());
    microtasks_completed_callbacks_cow_.reset();
  }
}
References is_running_completed_callbacks_, microtasks_completed_callbacks_, microtasks_completed_callbacks_cow_, and V8_UNLIKELY.
Referenced by RunMicrotasks().
PerformCheckpoint()
void v8::internal::MicrotaskQueue::PerformCheckpoint (v8::Isolate * isolate) [inline], [override], [virtual]
Runs microtasks if no microtask is running on this MicrotaskQueue instance.
Implements v8::MicrotaskQueue.
Definition at line 46 of file microtask-queue.h.
                                                      {
    if (!ShouldPerfomCheckpoint()) return;
    PerformCheckpointInternal(isolate);
  }
Referenced by v8::internal::Isolate::FireCallCompletedCallbackInternal(), and v8::MicrotasksScope::~MicrotasksScope().
PerformCheckpointInternal()
void v8::internal::MicrotaskQueue::PerformCheckpointInternal (v8::Isolate * v8_isolate) [private]
Definition at line 116 of file microtask-queue.cc.
                                                                    {
  DCHECK(ShouldPerfomCheckpoint());
  std::optional<MicrotasksScope> microtasks_scope;
  if (microtasks_policy_ == v8::MicrotasksPolicy::kScoped) {
    // If we're using microtask scopes to schedule microtask execution, V8
    // API calls will check that there's always a microtask scope on the
    // stack. As the microtasks we're about to execute could invoke embedder
    // callbacks which then calls back into V8, we create an artificial
    // microtask scope here to avoid running into the CallDepthScope check.
    microtasks_scope.emplace(v8_isolate, this,
                             v8::MicrotasksScope::kDoNotRunMicrotasks);
  }
  Isolate* isolate = reinterpret_cast<Isolate*>(v8_isolate);
  RunMicrotasks(isolate);
  isolate->ClearKeptObjects();
}
References v8::internal::Isolate::ClearKeptObjects(), v8::internal::DCHECK(), v8::MicrotasksScope::kDoNotRunMicrotasks, v8::kScoped, microtasks_policy_, RunMicrotasks(), and ShouldPerfomCheckpoint().
prev()
MicrotaskQueue* v8::internal::MicrotaskQueue::prev () const [inline]
Definition at line 108 of file microtask-queue.h.
{ return prev_; }
RemoveMicrotasksCompletedCallback()
void v8::internal::MicrotaskQueue::RemoveMicrotasksCompletedCallback (MicrotasksCompletedCallbackWithData callback, void * data) [override], [virtual]
Removes callback that was installed by AddMicrotasksCompletedCallback.
Implements v8::MicrotaskQueue.
Definition at line 268 of file microtask-queue.cc.
                                                              {
  std::vector<CallbackWithData>* microtasks_completed_callbacks =
      &microtasks_completed_callbacks_;
  if (is_running_completed_callbacks_) {
    if (!microtasks_completed_callbacks_cow_.has_value()) {
      microtasks_completed_callbacks_cow_.emplace(
          microtasks_completed_callbacks_);
    }
    // Use the COW vector if we are iterating the callbacks right now.
    microtasks_completed_callbacks =
        &microtasks_completed_callbacks_cow_.value();
  }
  CallbackWithData callback_with_data(callback, data);
  const auto pos =
      std::find(microtasks_completed_callbacks->begin(),
                microtasks_completed_callbacks->end(), callback_with_data);
  if (pos == microtasks_completed_callbacks->end()) {
    return;
  }
  microtasks_completed_callbacks->erase(pos);
}
References is_running_completed_callbacks_, microtasks_completed_callbacks_, and microtasks_completed_callbacks_cow_.
ResizeBuffer()
void v8::internal::MicrotaskQueue::ResizeBuffer (intptr_t new_capacity) [private]
Definition at line 311 of file microtask-queue.cc.
                                                       {
  DCHECK_LE(size_, new_capacity);
  Address* new_ring_buffer = new Address[new_capacity];
  for (intptr_t i = 0; i < size_; ++i) {
    new_ring_buffer[i] = ring_buffer_[(start_ + i) % capacity_];
  }
  delete[] ring_buffer_;
  ring_buffer_ = new_ring_buffer;
  capacity_ = new_capacity;
  start_ = 0;
}
References capacity_, DCHECK_LE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, ring_buffer_, size_, and start_.
Referenced by EnqueueMicrotask(), and IterateMicrotasks().
RunMicrotasks()
int v8::internal::MicrotaskQueue::RunMicrotasks (Isolate * isolate)
Definition at line 153 of file microtask-queue.cc.
                                                  {
  SetIsRunningMicrotasks scope(&is_running_microtasks_);
  v8::Isolate::SuppressMicrotaskExecutionScope suppress(
      reinterpret_cast<v8::Isolate*>(isolate), this);
  if (!size()) {
    OnCompleted(isolate);
    return 0;
  }
  // We should not enter V8 if it's marked for termination.
  DCHECK_IMPLIES(v8_flags.strict_termination_checks,
                 !isolate->is_execution_terminating());
  intptr_t base_count = finished_microtask_count_;
  HandleScope handle_scope(isolate);
  MaybeDirectHandle<Object> maybe_result;
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  DirectHandle<Object> continuation_preserved_embedder_data(
      isolate->isolate_data()->continuation_preserved_embedder_data(), isolate);
  isolate->isolate_data()->set_continuation_preserved_embedder_data(
      ReadOnlyRoots(isolate).undefined_value());
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  int processed_microtask_count;
  {
    HandleScopeImplementer::EnteredContextRewindScope rewind_scope(
        isolate->handle_scope_implementer());
    TRACE_EVENT_BEGIN0("v8.execute", "RunMicrotasks");
    {
      TRACE_EVENT_CALL_STATS_SCOPED(isolate, "v8", "V8.RunMicrotasks");
      maybe_result = Execution::TryRunMicrotasks(isolate, this);
      processed_microtask_count =
          static_cast<int>(finished_microtask_count_ - base_count);
    }
    TRACE_EVENT_END1("v8.execute", "RunMicrotasks", "microtask_count",
                     processed_microtask_count);
  }
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  isolate->isolate_data()->set_continuation_preserved_embedder_data(
      *continuation_preserved_embedder_data);
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  if (isolate->is_execution_terminating()) {
    DCHECK(isolate->has_exception());
    DCHECK(maybe_result.is_null());
    delete[] ring_buffer_;
    ring_buffer_ = nullptr;
    capacity_ = 0;
    size_ = 0;
    start_ = 0;
    isolate->OnTerminationDuringRunMicrotasks();
    OnCompleted(isolate);
    return -1;
  }
  DCHECK_EQ(0, size());
  OnCompleted(isolate);
  return processed_microtask_count;
}
References capacity_, v8::internal::IsolateData::continuation_preserved_embedder_data(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, finished_microtask_count_, v8::internal::Isolate::handle_scope_implementer(), v8::internal::Isolate::has_exception(), v8::internal::Isolate::is_execution_terminating(), v8::internal::MaybeDirectHandle< T >::is_null(), is_running_microtasks_, v8::internal::Isolate::isolate_data(), OnCompleted(), v8::internal::Isolate::OnTerminationDuringRunMicrotasks(), ring_buffer_, v8::internal::IsolateData::set_continuation_preserved_embedder_data(), size(), size_, start_, TRACE_EVENT_BEGIN0, TRACE_EVENT_CALL_STATS_SCOPED, TRACE_EVENT_END1, v8::internal::Execution::TryRunMicrotasks(), and v8::internal::v8_flags.
Referenced by PerformCheckpointInternal().
set_microtasks_policy()
void v8::internal::MicrotaskQueue::set_microtasks_policy (v8::MicrotasksPolicy microtasks_policy) [inline]
Definition at line 96 of file microtask-queue.h.
                                                                   {
    microtasks_policy_ = microtasks_policy;
  }
SetUpDefaultMicrotaskQueue()
void v8::internal::MicrotaskQueue::SetUpDefaultMicrotaskQueue (Isolate * isolate) [static]
Definition at line 35 of file microtask-queue.cc.
                                                                {
  DCHECK_NULL(isolate->default_microtask_queue());
  MicrotaskQueue* microtask_queue = new MicrotaskQueue;
  microtask_queue->next_ = microtask_queue;
  microtask_queue->prev_ = microtask_queue;
  isolate->set_default_microtask_queue(microtask_queue);
}
References DCHECK_NULL, MicrotaskQueue(), next_, and prev_.
Referenced by v8::internal::Isolate::Isolate().
ShouldPerfomCheckpoint()
bool v8::internal::MicrotaskQueue::ShouldPerfomCheckpoint () const [inline]
Definition at line 51 of file microtask-queue.h.
                                      {
    return !IsRunningMicrotasks() && !GetMicrotasksScopeDepth() &&
           !HasMicrotasksSuppressions();
  }
Referenced by PerformCheckpointInternal().
size()
intptr_t v8::internal::MicrotaskQueue::size () const [inline]
Definition at line 102 of file microtask-queue.h.
{ return size_; }
Referenced by RunMicrotasks(), and v8::internal::anonymous_namespace{context-serializer.cc}::SanitizeNativeContextScope::SanitizeNativeContextScope().
start()
intptr_t v8::internal::MicrotaskQueue::start () const [inline]
Definition at line 103 of file microtask-queue.h.
{ return start_; }
Member Data Documentation
capacity_
intptr_t v8::internal::MicrotaskQueue::capacity_ = 0 [private]
Definition at line 130 of file microtask-queue.h.
Referenced by EnqueueMicrotask(), get(), IterateMicrotasks(), ResizeBuffer(), and RunMicrotasks().
finished_microtask_count_
intptr_t v8::internal::MicrotaskQueue::finished_microtask_count_ = 0 [private]
Definition at line 135 of file microtask-queue.h.
Referenced by RunMicrotasks().
is_running_completed_callbacks_
bool v8::internal::MicrotaskQueue::is_running_completed_callbacks_ = false [private]
Definition at line 151 of file microtask-queue.h.
Referenced by AddMicrotasksCompletedCallback(), OnCompleted(), and RemoveMicrotasksCompletedCallback().
is_running_microtasks_
bool v8::internal::MicrotaskQueue::is_running_microtasks_ = false [private]
Definition at line 150 of file microtask-queue.h.
Referenced by RunMicrotasks().
kCapacityOffset
const size_t v8::internal::MicrotaskQueue::kCapacityOffset [static]
Initial value:
=
    OFFSET_OF(MicrotaskQueue, capacity_)
Definition at line 111 of file microtask-queue.h.
Referenced by v8::internal::MicrotaskQueueBuiltinsAssembler::GetMicrotaskQueueCapacity().
kFinishedMicrotaskCountOffset
const size_t v8::internal::MicrotaskQueue::kFinishedMicrotaskCountOffset [static]
Initial value:
=
    OFFSET_OF(MicrotaskQueue, finished_microtask_count_)
Definition at line 114 of file microtask-queue.h.
Referenced by v8::internal::MicrotaskQueueBuiltinsAssembler::IncrementFinishedMicrotaskCount().
kMinimumCapacity
const intptr_t v8::internal::MicrotaskQueue::kMinimumCapacity = 8 [static]
Definition at line 116 of file microtask-queue.h.
Referenced by EnqueueMicrotask(), and IterateMicrotasks().
kRingBufferOffset
const size_t v8::internal::MicrotaskQueue::kRingBufferOffset [static]
Initial value:
=
    OFFSET_OF(MicrotaskQueue, ring_buffer_)
Definition at line 110 of file microtask-queue.h.
Referenced by v8::internal::MicrotaskQueueBuiltinsAssembler::GetMicrotaskRingBuffer().
kSizeOffset
const size_t v8::internal::MicrotaskQueue::kSizeOffset = OFFSET_OF(MicrotaskQueue, size_) [static]
Definition at line 112 of file microtask-queue.h.
Referenced by v8::internal::MicrotaskQueueBuiltinsAssembler::GetMicrotaskQueueSize(), v8::internal::MicrotaskQueueBuiltinsAssembler::SetMicrotaskQueueSize(), and v8::internal::TF_BUILTIN().
kStartOffset
const size_t v8::internal::MicrotaskQueue::kStartOffset = OFFSET_OF(MicrotaskQueue, start_) [static]
Definition at line 113 of file microtask-queue.h.
Referenced by v8::internal::MicrotaskQueueBuiltinsAssembler::GetMicrotaskQueueStart(), and v8::internal::MicrotaskQueueBuiltinsAssembler::SetMicrotaskQueueStart().
microtasks_completed_callbacks_
std::vector<CallbackWithData> v8::internal::MicrotaskQueue::microtasks_completed_callbacks_ [private]
Definition at line 154 of file microtask-queue.h.
Referenced by AddMicrotasksCompletedCallback(), OnCompleted(), and RemoveMicrotasksCompletedCallback().
microtasks_completed_callbacks_cow_
std::optional<std::vector<CallbackWithData> > v8::internal::MicrotaskQueue::microtasks_completed_callbacks_cow_ [private]
Definition at line 156 of file microtask-queue.h.
Referenced by AddMicrotasksCompletedCallback(), OnCompleted(), and RemoveMicrotasksCompletedCallback().
microtasks_depth_
int v8::internal::MicrotaskQueue::microtasks_depth_ = 0 [private]
Definition at line 142 of file microtask-queue.h.
microtasks_policy_
v8::MicrotasksPolicy v8::internal::MicrotaskQueue::microtasks_policy_ = v8::MicrotasksPolicy::kAuto [private]
Definition at line 148 of file microtask-queue.h.
Referenced by PerformCheckpointInternal().
microtasks_suppressions_
int v8::internal::MicrotaskQueue::microtasks_suppressions_ = 0 [private]
Definition at line 143 of file microtask-queue.h.
next_
MicrotaskQueue* v8::internal::MicrotaskQueue::next_ = nullptr [private]
Definition at line 139 of file microtask-queue.h.
Referenced by New(), SetUpDefaultMicrotaskQueue(), and ~MicrotaskQueue().
prev_
MicrotaskQueue* v8::internal::MicrotaskQueue::prev_ = nullptr [private]
Definition at line 140 of file microtask-queue.h.
Referenced by New(), SetUpDefaultMicrotaskQueue(), and ~MicrotaskQueue().
ring_buffer_
Address* v8::internal::MicrotaskQueue::ring_buffer_ = nullptr [private]
Definition at line 132 of file microtask-queue.h.
Referenced by EnqueueMicrotask(), get(), IterateMicrotasks(), ResizeBuffer(), RunMicrotasks(), and ~MicrotaskQueue().
size_
intptr_t v8::internal::MicrotaskQueue::size_ = 0 [private]
Definition at line 129 of file microtask-queue.h.
Referenced by EnqueueMicrotask(), get(), IterateMicrotasks(), ResizeBuffer(), and RunMicrotasks().
start_
intptr_t v8::internal::MicrotaskQueue::start_ = 0 [private]
Definition at line 131 of file microtask-queue.h.
Referenced by EnqueueMicrotask(), get(), IterateMicrotasks(), ResizeBuffer(), and RunMicrotasks().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/microtask-queue.h
/mnt/V8SourceCode/src/execution/microtask-queue.cc