heap::base::BasicSlotSet< SlotGranularity >::Bucket Class Reference
#include <basic-slot-set.h>
Public Member Functions
Bucket ()=default
uint32_t * cells ()
const uint32_t * cells () const
uint32_t * cell (int cell_index)
const uint32_t * cell (int cell_index) const
template<AccessMode access_mode = AccessMode::ATOMIC>
uint32_t LoadCell (int cell_index)
template<AccessMode access_mode = AccessMode::ATOMIC>
void SetCellBits (int cell_index, uint32_t mask)
template<AccessMode access_mode = AccessMode::ATOMIC>
void ClearCellBits (int cell_index, uint32_t mask)
void StoreCell (int cell_index, uint32_t value)
bool IsEmpty () const
Private Attributes
uint32_t cells_ [kCellsPerBucket] = {0}
Detailed Description
template<size_t SlotGranularity>
class heap::base::BasicSlotSet< SlotGranularity >::Bucket
Definition at line 282 of file basic-slot-set.h.
Constructor & Destructor Documentation
Bucket()
template<size_t SlotGranularity>
heap::base::BasicSlotSet< SlotGranularity >::Bucket::Bucket () [default]
Member Function Documentation
cell() [1/2]
template<size_t SlotGranularity>
uint32_t* heap::base::BasicSlotSet< SlotGranularity >::Bucket::cell (int cell_index) [inline]
Definition at line 288 of file basic-slot-set.h.
{ return cells_ + cell_index; }
References heap::base::BasicSlotSet< SlotGranularity >::Bucket::cells_.
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Bucket::ClearCellBits(), heap::base::BasicSlotSet< SlotGranularity >::Bucket::LoadCell(), heap::base::BasicSlotSet< SlotGranularity >::Bucket::SetCellBits(), and heap::base::BasicSlotSet< SlotGranularity >::Bucket::StoreCell().
cell() [2/2]
template<size_t SlotGranularity>
const uint32_t* heap::base::BasicSlotSet< SlotGranularity >::Bucket::cell (int cell_index) const [inline]
Definition at line 289 of file basic-slot-set.h.
{ return cells_ + cell_index; }
References heap::base::BasicSlotSet< SlotGranularity >::Bucket::cells_.
cells() [1/2]
template<size_t SlotGranularity>
uint32_t* heap::base::BasicSlotSet< SlotGranularity >::Bucket::cells () [inline]
Definition at line 286 of file basic-slot-set.h.
{ return cells_; }
References heap::base::BasicSlotSet< SlotGranularity >::Bucket::cells_.
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Insert().
cells() [2/2]
template<size_t SlotGranularity>
const uint32_t* heap::base::BasicSlotSet< SlotGranularity >::Bucket::cells () const [inline]
Definition at line 287 of file basic-slot-set.h.
{ return cells_; }
References heap::base::BasicSlotSet< SlotGranularity >::Bucket::cells_.
ClearCellBits()
template<size_t SlotGranularity>
template<AccessMode access_mode = AccessMode::ATOMIC>
void heap::base::BasicSlotSet< SlotGranularity >::Bucket::ClearCellBits (int cell_index, uint32_t mask) [inline]
Definition at line 310 of file basic-slot-set.h.
                                                      {
      if constexpr (access_mode == AccessMode::ATOMIC) {
        v8::base::AsAtomic32::Release_SetBits(cell(cell_index), 0u, mask);
      } else {
        *cell(cell_index) &= ~mask;
      }
    }
References heap::base::BasicSlotSet< SlotGranularity >::Bucket::cell(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Release_SetBits().
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Remove(), and heap::base::BasicSlotSet< SlotGranularity >::RemoveRange().
IsEmpty()
template<size_t SlotGranularity>
bool heap::base::BasicSlotSet< SlotGranularity >::Bucket::IsEmpty () const [inline]
Definition at line 322 of file basic-slot-set.h.
                         {
      for (int i = 0; i < kCellsPerBucket; i++) {
        if (cells_[i] != 0) {
          return false;
        }
      }
      return true;
    }
References heap::base::BasicSlotSet< SlotGranularity >::Bucket::cells_, and heap::base::BasicSlotSet< SlotGranularity >::kCellsPerBucket.
Referenced by heap::base::BasicSlotSet< SlotGranularity >::FreeBucketIfEmpty().
LoadCell()
template<size_t SlotGranularity>
template<AccessMode access_mode = AccessMode::ATOMIC>
uint32_t heap::base::BasicSlotSet< SlotGranularity >::Bucket::LoadCell (int cell_index) [inline]
Definition at line 292 of file basic-slot-set.h.
                                      {
      DCHECK_LT(cell_index, kCellsPerBucket);
      if constexpr (access_mode == AccessMode::ATOMIC)
        return v8::base::AsAtomic32::Acquire_Load(cell(cell_index));
      return *(cell(cell_index));
    }
References v8::base::AsAtomicImpl< TAtomicStorageType >::Acquire_Load(), heap::base::BasicSlotSet< SlotGranularity >::Bucket::cell(), DCHECK_LT, and heap::base::BasicSlotSet< SlotGranularity >::kCellsPerBucket.
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Contains(), heap::base::BasicSlotSet< SlotGranularity >::Lookup(), and heap::base::BasicSlotSet< SlotGranularity >::Remove().
SetCellBits()
template<size_t SlotGranularity>
template<AccessMode access_mode = AccessMode::ATOMIC>
void heap::base::BasicSlotSet< SlotGranularity >::Bucket::SetCellBits (int cell_index, uint32_t mask) [inline]
Definition at line 300 of file basic-slot-set.h.
                                                    {
      if constexpr (access_mode == AccessMode::ATOMIC) {
        v8::base::AsAtomic32::Release_SetBits(cell(cell_index), mask, mask);
      } else {
        uint32_t* c = cell(cell_index);
        *c = (*c & ~mask) | mask;
      }
    }
References heap::base::BasicSlotSet< SlotGranularity >::Bucket::cell(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Release_SetBits().
StoreCell()
template<size_t SlotGranularity>
void heap::base::BasicSlotSet< SlotGranularity >::Bucket::StoreCell (int cell_index, uint32_t value) [inline]
Definition at line 318 of file basic-slot-set.h.
                                                   {
      v8::base::AsAtomic32::Release_Store(cell(cell_index), value);
    }
References heap::base::BasicSlotSet< SlotGranularity >::Bucket::cell(), v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store(), and v8::internal::value.
Referenced by heap::base::BasicSlotSet< SlotGranularity >::ClearBucket(), and heap::base::BasicSlotSet< SlotGranularity >::RemoveRange().
Member Data Documentation
cells_
template<size_t SlotGranularity>
uint32_t heap::base::BasicSlotSet< SlotGranularity >::Bucket::cells_[kCellsPerBucket] = {0} [private]
Definition at line 332 of file basic-slot-set.h.
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Bucket::cell(), heap::base::BasicSlotSet< SlotGranularity >::Bucket::cells(), and heap::base::BasicSlotSet< SlotGranularity >::Bucket::IsEmpty().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/base/basic-slot-set.h