v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizableCodeIterator Class Reference
Public Member Functions
DeoptimizableCodeIterator (Isolate *isolate)
DeoptimizableCodeIterator (const DeoptimizableCodeIterator &)=delete
DeoptimizableCodeIterator & operator= (const DeoptimizableCodeIterator &)=delete
Tagged< Code > Next ()
Private Types
enum { kIteratingCodeSpace
, kIteratingCodeLOSpace
, kDone
 }
Private Attributes
Isolate *const isolate_
std::unique_ptr< SafepointScope > safepoint_scope_
std::unique_ptr< ObjectIterator > object_iterator_
enum v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizableCodeIterator:: { ... } state_
Detailed Description
Definition at line 51 of file deoptimizer.cc.
Member Enumeration Documentation
anonymous enum
anonymous enum [private]
Enumerator
kIteratingCodeSpace
kIteratingCodeLOSpace
kDone
Definition at line 63 of file deoptimizer.cc.
{ kIteratingCodeSpace, kIteratingCodeLOSpace, kDone } state_;
Constructor & Destructor Documentation
DeoptimizableCodeIterator() [1/2]
v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizableCodeIterator::DeoptimizableCodeIterator (Isolate * isolate) [explicit]
Definition at line 68 of file deoptimizer.cc.
    : isolate_(isolate),
      safepoint_scope_(std::make_unique<SafepointScope>(
          isolate, isolate->is_shared_space_isolate()
                       ? SafepointKind::kGlobal
                       : SafepointKind::kIsolate)),
      object_iterator_(
          isolate->heap()->code_space()->GetObjectIterator(isolate->heap())),
      state_(kIteratingCodeSpace) {}
References v8::internal::kGlobal, and v8::internal::kIsolate.
DeoptimizableCodeIterator() [2/2]
v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizableCodeIterator::DeoptimizableCodeIterator (const DeoptimizableCodeIterator &) [delete]
Member Function Documentation
Next()
Tagged< Code > v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizableCodeIterator::Next ()
Definition at line 78 of file deoptimizer.cc.
                                             {
  while (true) {
    Tagged<HeapObject> object = object_iterator_->Next();
    if (object.is_null()) {
      // No objects left in the current iterator, try to move to the next space
      // based on the state.
      switch (state_) {
        case kIteratingCodeSpace: {
          object_iterator_ =
              isolate_->heap()->code_lo_space()->GetObjectIterator(
                  isolate_->heap());
          state_ = kIteratingCodeLOSpace;
          continue;
        }
        case kIteratingCodeLOSpace:
          // No other spaces to iterate, so clean up and we're done. Keep the
          // object iterator so that it keeps returning null on Next(), to avoid
          // needing to branch on state_ before the while loop, but drop the
          // safepoint scope since we no longer need to stop the heap from
          // moving.
          safepoint_scope_.reset();
          state_ = kDone;
          [[fallthrough]];
        case kDone:
          return Code();
      }
    }
    Tagged<InstructionStream> istream = Cast<InstructionStream>(object);
    Tagged<Code> code;
    if (!istream->TryGetCode(&code, kAcquireLoad)) continue;
    if (!CodeKindCanDeoptimize(code->kind())) continue;
    return code;
  }
}
References code, v8::internal::Code, v8::internal::Heap::code_lo_space(), v8::internal::CodeKindCanDeoptimize(), v8::internal::LargeObjectSpace::GetObjectIterator(), v8::internal::Isolate::heap(), isolate_, v8::kAcquireLoad, kDone, kIteratingCodeLOSpace, kIteratingCodeSpace, object_iterator_, safepoint_scope_, and state_.
operator=()
DeoptimizableCodeIterator& v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizableCodeIterator::operator= (const DeoptimizableCodeIterator &) [delete]
Member Data Documentation
isolate_
Isolate* const v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizableCodeIterator::isolate_ [private]
Definition at line 60 of file deoptimizer.cc.
Referenced by Next().
object_iterator_
std::unique_ptr<ObjectIterator> v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizableCodeIterator::object_iterator_ [private]
Definition at line 62 of file deoptimizer.cc.
Referenced by Next().
safepoint_scope_
std::unique_ptr<SafepointScope> v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizableCodeIterator::safepoint_scope_ [private]
Definition at line 61 of file deoptimizer.cc.
Referenced by Next().
enum { ... } v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizableCodeIterator::state_ [private]
Referenced by Next().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/deoptimizer/deoptimizer.cc