v8::internal::WasmTableObject Class Reference
#include <wasm-objects.h>
Public Member Functions
wasm::ValueType type (const wasm::WasmModule *module)
wasm::CanonicalValueType canonical_type (const wasm::WasmModule *module)
wasm::ValueType unsafe_type ()
bool is_in_bounds (uint32_t entry_index)
bool is_table64 () const
std::optional< uint64_t > maximum_length_u64 () const
void ClearDispatchTable (int index)
Static Public Member Functions
static V8_EXPORT_PRIVATE int Grow (Isolate *isolate, DirectHandle< WasmTableObject > table, uint32_t count, DirectHandle< Object > init_value)
static V8_EXPORT_PRIVATE DirectHandle< WasmTableObject > New (Isolate *isolate, DirectHandle< WasmTrustedInstanceData > trusted_data, wasm::ValueType type, wasm::CanonicalValueType canonical_type, uint32_t initial, bool has_maximum, uint64_t maximum, DirectHandle< Object > initial_value, wasm::AddressType address_type, DirectHandle< WasmDispatchTable > *out_dispatch_table=nullptr)
static MaybeDirectHandle< Object > JSToWasmElement (Isolate *isolate, DirectHandle< WasmTableObject > table, DirectHandle< Object > entry, const char **error_message)
static V8_EXPORT_PRIVATE void Set (Isolate *isolate, DirectHandle< WasmTableObject > table, uint32_t index, DirectHandle< Object > entry)
static V8_EXPORT_PRIVATE DirectHandle< Object > Get (Isolate *isolate, DirectHandle< WasmTableObject > table, uint32_t index)
static V8_EXPORT_PRIVATE void Fill (Isolate *isolate, DirectHandle< WasmTableObject > table, uint32_t start, DirectHandle< Object > entry, uint32_t count)
static void UpdateDispatchTable (Isolate *isolate, DirectHandle< WasmTableObject > table, int entry_index, const wasm::WasmFunction *func, DirectHandle< WasmTrustedInstanceData > target_instance)
static void UpdateDispatchTable (Isolate *isolate, DirectHandle< WasmTableObject > table, int entry_index, DirectHandle< WasmJSFunction > function)
static void UpdateDispatchTable (Isolate *isolate, DirectHandle< WasmTableObject > table, int entry_index, DirectHandle< WasmCapiFunction > capi_function)
static V8_EXPORT_PRIVATE void SetFunctionTablePlaceholder (Isolate *isolate, DirectHandle< WasmTableObject > table, int entry_index, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int func_index)
static void GetFunctionTableEntry (Isolate *isolate, DirectHandle< WasmTableObject > table, int entry_index, bool *is_valid, bool *is_null, MaybeDirectHandle< WasmTrustedInstanceData > *instance_data, int *function_index, MaybeDirectHandle< WasmJSFunction > *maybe_js_function)
Static Private Member Functions
static void SetFunctionTableEntry (Isolate *isolate, DirectHandle< WasmTableObject > table, int entry_index, DirectHandle< Object > entry)
Detailed Description
Definition at line 220 of file wasm-objects.h.
Member Function Documentation
canonical_type()
wasm::CanonicalValueType v8::internal::WasmTableObject::canonical_type (const wasm::WasmModule * module) [inline]
Definition at line 589 of file wasm-objects-inl.h.
                                  {
  wasm::ValueType unsafe = unsafe_type();
  if (!unsafe.has_index()) return wasm::CanonicalValueType{unsafe};
  SBXCHECK(module != nullptr && module->has_type(unsafe.ref_index()));
  return module->canonical_type(unsafe);
}
References v8::internal::wasm::WasmModule::canonical_type(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::WasmModule::has_type(), v8::internal::wasm::ValueType::ref_index(), SBXCHECK, and unsafe_type().
Referenced by New().
ClearDispatchTable()
void v8::internal::WasmTableObject::ClearDispatchTable (int index)
Definition at line 724 of file wasm-objects.cc.
                                                  {
  DisallowGarbageCollection no_gc;
  Isolate* isolate = Isolate::Current();
  Tagged<WasmDispatchTable> dispatch_table = trusted_dispatch_table(isolate);
  dispatch_table->Clear(index, WasmDispatchTable::kExistingEntry);
#if V8_ENABLE_DRUMBRAKE
  if (v8_flags.wasm_jitless) {
    Tagged<ProtectedWeakFixedArray> uses = dispatch_table->protected_uses();
    int used_length = GetUsedLength(uses);
    for (int i = kReservedSlotOffset; i < used_length; i += 2) {
      if (uses->get(i).IsCleared()) continue;
      Tagged<WasmTrustedInstanceData> non_shared_instance_data =
          GetInstance(uses, i);
      if (non_shared_instance_data->has_interpreter_object()) {
        int table_index = GetTableIndex(uses, i);
        DirectHandle<WasmInstanceObject> instance_handle(
            non_shared_instance_data->instance_object(), isolate);
        wasm::WasmInterpreterRuntime::ClearIndirectCallCacheEntry(
            isolate, instance_handle, table_index, index);
      }
    }
  }
#endif // V8_ENABLE_DRUMBRAKE
}
References v8::internal::wasm::WasmInterpreterRuntime::ClearIndirectCallCacheEntry(), v8::internal::Isolate::Current(), v8::internal::anonymous_namespace{wasm-objects.cc}::GetInstance(), v8::internal::anonymous_namespace{wasm-objects.cc}::GetTableIndex(), v8::internal::anonymous_namespace{wasm-objects.cc}::GetUsedLength(), v8::internal::index, v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::WasmDispatchTable::kExistingEntry, v8::internal::anonymous_namespace{wasm-objects.cc}::kReservedSlotOffset, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::trusted_dispatch_table, and v8::internal::v8_flags.
Fill()
void v8::internal::WasmTableObject::Fill (Isolate * isolate, DirectHandle< WasmTableObject > table, uint32_t start, DirectHandle< Object > entry, uint32_t count) [static]
Definition at line 504 of file wasm-objects.cc.
                                                                       {
  // Bounds checks must be done by the caller.
  DCHECK_LE(start, table->current_length());
  DCHECK_LE(count, table->current_length());
  DCHECK_LE(start + count, table->current_length());
  for (uint32_t i = 0; i < count; i++) {
    WasmTableObject::Set(isolate, table, start + i, entry);
  }
}
References DCHECK_LE, and Set().
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::wasm::WasmInterpreterRuntime::TableFill().
Get()
DirectHandle< Object > v8::internal::WasmTableObject::Get (Isolate * isolate, DirectHandle< WasmTableObject > table, uint32_t index) [static]
Definition at line 431 of file wasm-objects.cc.
                                                          {
  DirectHandle<FixedArray> entries(table->entries(), isolate);
  // Callers need to perform bounds checks and error handling.
  DCHECK(table->is_in_bounds(index));
  // The FixedArray is addressed with int's.
  int entry_index = static_cast<int>(index);
  DirectHandle<Object> entry(entries->get(entry_index), isolate);
  if (IsWasmNull(*entry, isolate)) return entry;
  if (IsWasmFuncRef(*entry)) return entry;
  wasm::ValueType unsafe_type = table->unsafe_type();
  if (unsafe_type.has_index()) {
    DCHECK(table->has_trusted_data());
    const WasmModule* module = table->trusted_data(isolate)->module();
    wasm::ModuleTypeIndex element_type = table->type(module).ref_index();
    if (module->has_array(element_type) || module->has_struct(element_type)) {
      return entry;
    }
    DCHECK(module->has_signature(element_type));
    // Fall through.
  } else {
    switch (unsafe_type.generic_kind()) {
      case wasm::GenericKind::kStringViewWtf8:
      case wasm::GenericKind::kStringViewWtf16:
      case wasm::GenericKind::kStringViewIter:
      case wasm::GenericKind::kExtern:
      case wasm::GenericKind::kString:
      case wasm::GenericKind::kEq:
      case wasm::GenericKind::kI31:
      case wasm::GenericKind::kStruct:
      case wasm::GenericKind::kArray:
      case wasm::GenericKind::kAny:
      case wasm::GenericKind::kNone:
      case wasm::GenericKind::kNoFunc:
      case wasm::GenericKind::kNoExtern:
      case wasm::GenericKind::kExn:
      case wasm::GenericKind::kNoExn:
      case wasm::GenericKind::kCont:
      case wasm::GenericKind::kNoCont:
        return entry;
      case wasm::GenericKind::kFunc:
        // Placeholder; handled below.
        break;
      case wasm::GenericKind::kBottom:
      case wasm::GenericKind::kTop:
      case wasm::GenericKind::kVoid:
      case wasm::GenericKind::kExternString:
        UNREACHABLE();
    }
  }
  // {entry} is not a valid entry in the table. It has to be a placeholder
  // for lazy initialization.
  DirectHandle<Tuple2> tuple = Cast<Tuple2>(entry);
  auto trusted_instance_data = direct_handle(
      Cast<WasmInstanceObject>(tuple->value1())->trusted_data(isolate),
      isolate);
  int function_index = Cast<Smi>(tuple->value2()).value();
  // Create a WasmInternalFunction and WasmFuncRef for the function if it does
  // not exist yet, and store it in the table.
  DirectHandle<WasmFuncRef> func_ref =
      WasmTrustedInstanceData::GetOrCreateFuncRef(
          isolate, trusted_instance_data, function_index);
  entries->set(entry_index, *func_ref);
  return func_ref;
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::wasm::ValueTypeBase::generic_kind(), v8::internal::WasmTrustedInstanceData::GetOrCreateFuncRef(), v8::internal::wasm::WasmModule::has_array(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::WasmModule::has_signature(), v8::internal::wasm::WasmModule::has_struct(), v8::internal::index, v8::internal::torque::ls::kStruct, v8::internal::UNREACHABLE(), and unsafe_type().
Referenced by v8::internal::AddWasmTableObjectInternalProperties(), v8::internal::WasmTrustedInstanceData::CopyTableEntries(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::WasmInterpreterRuntime::TableGet(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGetImpl().
GetFunctionTableEntry()
void v8::internal::WasmTableObject::GetFunctionTableEntry (Isolate * isolate, DirectHandle< WasmTableObject > table, int entry_index, bool * is_valid, bool * is_null, MaybeDirectHandle< WasmTrustedInstanceData > * instance_data, int * function_index, MaybeDirectHandle< WasmJSFunction > * maybe_js_function) [static]
Definition at line 768 of file wasm-objects.cc.
                                                                               {
#if DEBUG
  if (table->has_trusted_data()) {
    const wasm::WasmModule* module = table->trusted_data(isolate)->module();
    DCHECK(wasm::IsSubtypeOf(table->type(module), wasm::kWasmFuncRef, module));
  } else {
    // A function table defined outside a module may only have type exactly
    // {funcref}.
    DCHECK(table->unsafe_type() == wasm::kWasmFuncRef);
  }
  DCHECK_LT(entry_index, table->current_length());
#endif
  // We initialize {is_valid} with {true}. We may change it later.
  *is_valid = true;
  DirectHandle<Object> element(table->entries()->get(entry_index), isolate);
  *is_null = IsWasmNull(*element, isolate);
  if (*is_null) return;
  if (IsWasmFuncRef(*element)) {
    DirectHandle<WasmInternalFunction> internal{
        Cast<WasmFuncRef>(*element)->internal(isolate), isolate};
    element = WasmInternalFunction::GetOrCreateExternal(internal);
  }
  if (WasmExportedFunction::IsWasmExportedFunction(*element)) {
    auto target_func = Cast<WasmExportedFunction>(element);
    auto func_data = Cast<WasmExportedFunctionData>(
        target_func->shared()->wasm_exported_function_data());
    *instance_data = direct_handle(func_data->instance_data(), isolate);
    *function_index = func_data->function_index();
    *maybe_js_function = MaybeDirectHandle<WasmJSFunction>();
    return;
  }
  if (WasmJSFunction::IsWasmJSFunction(*element)) {
    *instance_data = MaybeDirectHandle<WasmTrustedInstanceData>();
    *maybe_js_function = Cast<WasmJSFunction>(element);
    return;
  }
  if (IsTuple2(*element)) {
    auto tuple = Cast<Tuple2>(element);
    *instance_data = direct_handle(
        Cast<WasmInstanceObject>(tuple->value1())->trusted_data(isolate),
        isolate);
    *function_index = Cast<Smi>(tuple->value2()).value();
    *maybe_js_function = MaybeDirectHandle<WasmJSFunction>();
    return;
  }
  *is_valid = false;
}
References v8::internal::DCHECK(), DCHECK_LT, v8::internal::direct_handle(), v8::internal::WasmInternalFunction::GetOrCreateExternal(), v8::internal::instance_data, v8::internal::wasm::IsSubtypeOf(), v8::internal::WasmExportedFunction::IsWasmExportedFunction(), v8::internal::WasmJSFunction::IsWasmJSFunction(), and v8::internal::wasm::kWasmFuncRef.
Grow()
int v8::internal::WasmTableObject::Grow (Isolate * isolate, DirectHandle< WasmTableObject > table, uint32_t count, DirectHandle< Object > init_value) [static]
Definition at line 259 of file wasm-objects.cc.
                                                                           {
  uint32_t old_size = table->current_length();
  if (count == 0) return old_size; // Degenerate case: nothing to do.
  // Check if growing by {count} is valid.
  static_assert(wasm::kV8MaxWasmTableSize <= kMaxUInt32);
  uint64_t static_max_size = wasm::max_table_size();
  uint32_t max_size = static_cast<uint32_t>(std::min(
      static_max_size, table->maximum_length_u64().value_or(static_max_size)));
  DCHECK_LE(old_size, max_size);
  if (count > max_size - old_size) return -1;
  uint32_t new_size = old_size + count;
  // Even with 2x over-allocation, there should not be an integer overflow.
  static_assert(wasm::kV8MaxWasmTableSize <= kMaxInt / 2);
  DCHECK_GE(kMaxInt, new_size);
  int old_capacity = table->entries()->length();
  if (new_size > static_cast<uint32_t>(old_capacity)) {
    int grow = static_cast<int>(new_size) - old_capacity;
    // Grow at least by the old capacity, to implement exponential growing.
    grow = std::max(grow, old_capacity);
    // Never grow larger than the max size.
    grow = std::min(grow, static_cast<int>(max_size - old_capacity));
    auto new_store = isolate->factory()->CopyFixedArrayAndGrow(
        direct_handle(table->entries(), isolate), grow);
    table->set_entries(*new_store, WriteBarrierMode::UPDATE_WRITE_BARRIER);
  }
  if (table->has_trusted_dispatch_table()) {
    DirectHandle<WasmDispatchTable> dispatch_table(
        table->trusted_dispatch_table(isolate), isolate);
    DCHECK_EQ(old_size, dispatch_table->length());
    DirectHandle<WasmDispatchTable> new_dispatch_table =
        WasmDispatchTable::Grow(isolate, dispatch_table, new_size);
    if (!dispatch_table.is_identical_to(new_dispatch_table)) {
      table->set_trusted_dispatch_table(*new_dispatch_table);
    }
    DCHECK_EQ(new_size, table->trusted_dispatch_table(isolate)->length());
#if V8_ENABLE_DRUMBRAKE
    if (v8_flags.wasm_jitless) {
      Tagged<ProtectedWeakFixedArray> uses = dispatch_table->protected_uses();
      int used_length = GetUsedLength(uses);
      for (int i = kReservedSlotOffset; i < used_length; i += 2) {
        if (uses->get(i).IsCleared()) continue;
        Tagged<WasmTrustedInstanceData> instance = GetInstance(uses, i);
        if (instance->has_interpreter_object()) {
          int table_index = GetTableIndex(uses, i);
          wasm::WasmInterpreterRuntime::UpdateIndirectCallTable(
              isolate, direct_handle(instance->instance_object(), isolate),
              table_index);
        }
      }
    }
#endif // V8_ENABLE_DRUMBRAKE
  }
  // Only update the current length after all allocations of sub-objects
  // (in particular: the new dispatch table) are done, so that heap verification
  // can assert that the dispatch table's length matches the table's length.
  table->set_current_length(new_size);
  for (uint32_t entry = old_size; entry < new_size; ++entry) {
    WasmTableObject::Set(isolate, table, entry, init_value);
  }
  return old_size;
}
References v8::internal::Factory::CopyFixedArrayAndGrow(), DCHECK_EQ, DCHECK_GE, DCHECK_LE, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{wasm-objects.cc}::GetInstance(), v8::internal::anonymous_namespace{wasm-objects.cc}::GetTableIndex(), v8::internal::anonymous_namespace{wasm-objects.cc}::GetUsedLength(), v8::internal::WasmDispatchTable::Grow(), v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::kMaxInt, v8::internal::kMaxUInt32, v8::internal::anonymous_namespace{wasm-objects.cc}::kReservedSlotOffset, v8::internal::wasm::kV8MaxWasmTableSize, v8::internal::wasm::max_table_size(), Set(), v8::internal::UPDATE_WRITE_BARRIER, v8::internal::wasm::WasmInterpreterRuntime::UpdateIndirectCallTable(), and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::WasmInterpreterRuntime::TableGrow(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGrowImpl().
is_in_bounds()
bool v8::internal::WasmTableObject::is_in_bounds (uint32_t entry_index) [inline]
Definition at line 609 of file wasm-objects-inl.h.
                                                       {
  return entry_index < static_cast<uint32_t>(current_length());
}
is_table64()
bool v8::internal::WasmTableObject::is_table64 () const [inline]
Definition at line 613 of file wasm-objects-inl.h.
                                       {
  return address_type() == wasm::AddressType::kI64;
}
References v8::internal::wasm::kI64.
Referenced by maximum_length_u64().
JSToWasmElement()
MaybeDirectHandle< Object > v8::internal::WasmTableObject::JSToWasmElement (Isolate * isolate, DirectHandle< WasmTableObject > table, DirectHandle< Object > entry, const char ** error_message) [static]
Definition at line 328 of file wasm-objects.cc.
                                                            {
  const WasmModule* module = !table->has_trusted_data()
                                 ? nullptr
                                 : table->trusted_data(isolate)->module();
  return wasm::JSToWasmObject(isolate, module, entry, table->type(module),
                              error_message);
}
References v8::internal::wasm::JSToWasmObject(), and nullptr.
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGrowImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableSetImpl().
maximum_length_u64()
std::optional< uint64_t > v8::internal::WasmTableObject::maximum_length_u64 () const [inline]
Definition at line 617 of file wasm-objects-inl.h.
                                                                {
  Tagged<Object> max = maximum_length();
  if (IsUndefined(max)) return std::nullopt;
  if (is_table64()) {
    DCHECK(IsBigInt(max));
#if DEBUG
    bool lossless;
    uint64_t value = Cast<BigInt>(maximum_length())->AsUint64(&lossless);
    DCHECK(lossless);
    return value;
#else
    return Cast<BigInt>(maximum_length())->AsUint64();
#endif
  }
  DCHECK(IsNumber(max));
  double value = Object::NumberValue(max);
  DCHECK_LE(0, value);
  DCHECK_GE(std::numeric_limits<uint64_t>::max(), value);
  return value;
}
References v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, is_table64(), v8::internal::IsNumber(), v8::internal::Object::NumberValue(), and v8::internal::value.
New()
DirectHandle< WasmTableObject > v8::internal::WasmTableObject::New (Isolate * isolate, DirectHandle< WasmTrustedInstanceData > trusted_data, wasm::ValueType type, wasm::CanonicalValueType canonical_type, uint32_t initial, bool has_maximum, uint64_t maximum, DirectHandle< Object > initial_value, wasm::AddressType address_type, DirectHandle< WasmDispatchTable > * out_dispatch_table = nullptr) [static]
Definition at line 196 of file wasm-objects.cc.
                                                         {
  CHECK(type.is_object_reference());
  DCHECK_LE(initial, wasm::max_table_size());
  DirectHandle<FixedArray> entries = isolate->factory()->NewFixedArray(initial);
  for (int i = 0; i < static_cast<int>(initial); ++i) {
    entries->set(i, *initial_value);
  }
  bool is_function_table = canonical_type.IsFunctionType();
  const bool shared = false;
  DirectHandle<WasmDispatchTable> dispatch_table =
      is_function_table ? isolate->factory()->NewWasmDispatchTable(
                              initial, canonical_type, shared)
                        : DirectHandle<WasmDispatchTable>{};
  DirectHandle<UnionOf<Undefined, Number, BigInt>> max =
      isolate->factory()->undefined_value();
  if (has_maximum) {
    if (address_type == wasm::AddressType::kI32) {
      DCHECK_GE(kMaxUInt32, maximum);
      max = isolate->factory()->NewNumber(maximum);
    } else {
      max = BigInt::FromUint64(isolate, maximum);
    }
  }
  DirectHandle<JSFunction> table_ctor(
      isolate->native_context()->wasm_table_constructor(), isolate);
  auto table_obj =
      Cast<WasmTableObject>(isolate->factory()->NewJSObject(table_ctor));
  DisallowGarbageCollection no_gc;
  if (!trusted_data.is_null()) {
    table_obj->set_trusted_data(*trusted_data);
  } else {
    table_obj->clear_trusted_data();
  }
  table_obj->set_entries(*entries);
  table_obj->set_current_length(initial);
  table_obj->set_maximum_length(*max);
  table_obj->set_raw_type(static_cast<int>(type.raw_bit_field()));
  table_obj->set_address_type(address_type);
  table_obj->set_padding_for_address_type_0(0);
  table_obj->set_padding_for_address_type_1(0);
#if TAGGED_SIZE_8_BYTES
  table_obj->set_padding_for_address_type_2(0);
#endif
  if (is_function_table) {
    DCHECK_EQ(table_obj->current_length(), dispatch_table->length());
    table_obj->set_trusted_dispatch_table(*dispatch_table);
    if (out_dispatch_table) *out_dispatch_table = dispatch_table;
  } else {
    table_obj->clear_trusted_dispatch_table();
  }
  return table_obj;
}
References canonical_type(), CHECK, DCHECK_EQ, DCHECK_GE, DCHECK_LE, v8::internal::Isolate::factory(), v8::internal::BigInt::FromUint64(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::DirectHandle< T >::is_null(), v8::internal::wasm::ValueTypeBase::is_object_reference(), v8::internal::wasm::CanonicalValueType::IsFunctionType(), v8::internal::wasm::kI32, v8::internal::kMaxUInt32, v8::internal::wasm::max_table_size(), v8::internal::Isolate::native_context(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSObject(), v8::internal::FactoryBase< Impl >::NewNumber(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::wasm::ValueTypeBase::raw_bit_field(), and type().
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl().
Set()
void v8::internal::WasmTableObject::Set (Isolate * isolate, DirectHandle< WasmTableObject > table, uint32_t index, DirectHandle< Object > entry) [static]
Definition at line 379 of file wasm-objects.cc.
                                                                      {
  // Callers need to perform bounds checks, type check, and error handling.
  DCHECK(table->is_in_bounds(index));
  DirectHandle<FixedArray> entries(table->entries(), isolate);
  // The FixedArray is addressed with int's.
  int entry_index = static_cast<int>(index);
  wasm::ValueType unsafe_type = table->unsafe_type();
  if (unsafe_type.has_index()) {
    DCHECK(table->has_trusted_data());
    const wasm::WasmModule* module = table->trusted_data(isolate)->module();
    if (module->has_signature(table->type(module).ref_index())) {
      SetFunctionTableEntry(isolate, table, entry_index, entry);
      return;
    }
    entries->set(entry_index, *entry);
    return;
  }
  switch (unsafe_type.generic_kind()) {
    case wasm::GenericKind::kExtern:
    case wasm::GenericKind::kString:
    case wasm::GenericKind::kStringViewWtf8:
    case wasm::GenericKind::kStringViewWtf16:
    case wasm::GenericKind::kStringViewIter:
    case wasm::GenericKind::kEq:
    case wasm::GenericKind::kStruct:
    case wasm::GenericKind::kArray:
    case wasm::GenericKind::kAny:
    case wasm::GenericKind::kI31:
    case wasm::GenericKind::kNone:
    case wasm::GenericKind::kNoFunc:
    case wasm::GenericKind::kNoExtern:
    case wasm::GenericKind::kExn:
    case wasm::GenericKind::kNoExn:
    case wasm::GenericKind::kCont:
    case wasm::GenericKind::kNoCont:
      entries->set(entry_index, *entry);
      return;
    case wasm::GenericKind::kFunc:
      SetFunctionTableEntry(isolate, table, entry_index, entry);
      return;
    case wasm::GenericKind::kBottom:
    case wasm::GenericKind::kTop:
    case wasm::GenericKind::kVoid:
    case wasm::GenericKind::kExternString:
      break;
  }
  UNREACHABLE();
}
References v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::generic_kind(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::WasmModule::has_signature(), v8::internal::index, v8::internal::torque::ls::kStruct, SetFunctionTableEntry(), v8::internal::UNREACHABLE(), and unsafe_type().
Referenced by v8::internal::WasmTrustedInstanceData::CopyTableEntries(), Fill(), Grow(), v8::internal::WasmTrustedInstanceData::InitTableEntries(), v8::internal::wasm::InstanceBuilder::LoadTableSegments(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::InstanceBuilder::SetTableInitialValues(), v8::internal::wasm::WasmInterpreterRuntime::TableSet(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableSetImpl().
SetFunctionTableEntry()
void v8::internal::WasmTableObject::SetFunctionTableEntry (Isolate * isolate, DirectHandle< WasmTableObject > table, int entry_index, DirectHandle< Object > entry) [static], [private]
Definition at line 338 of file wasm-objects.cc.
                                                                        {
  if (IsWasmNull(*entry, isolate)) {
    table->ClearDispatchTable(entry_index); // Degenerate case.
    table->entries()->set(entry_index, ReadOnlyRoots(isolate).wasm_null());
    return;
  }
  DCHECK(IsWasmFuncRef(*entry));
  DirectHandle<Object> external = WasmInternalFunction::GetOrCreateExternal(
      direct_handle(Cast<WasmFuncRef>(*entry)->internal(isolate), isolate));
  if (WasmExportedFunction::IsWasmExportedFunction(*external)) {
    auto exported_function = Cast<WasmExportedFunction>(external);
    auto func_data = exported_function->shared()->wasm_exported_function_data();
    DirectHandle<WasmTrustedInstanceData> target_instance_data(
        func_data->instance_data(), isolate);
    int func_index = func_data->function_index();
    const WasmModule* module = target_instance_data->module();
    SBXCHECK_BOUNDS(func_index, module->functions.size());
    auto* wasm_function = module->functions.data() + func_index;
    UpdateDispatchTable(isolate, table, entry_index, wasm_function,
                        target_instance_data
#if V8_ENABLE_DRUMBRAKE
                        ,
                        func_index
#endif // V8_ENABLE_DRUMBRAKE
    );
  } else if (WasmJSFunction::IsWasmJSFunction(*external)) {
    UpdateDispatchTable(isolate, table, entry_index,
                        Cast<WasmJSFunction>(external));
  } else {
    DCHECK(WasmCapiFunction::IsWasmCapiFunction(*external));
    UpdateDispatchTable(isolate, table, entry_index,
                        Cast<WasmCapiFunction>(external));
  }
  table->entries()->set(entry_index, *entry);
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::wasm::WasmModule::functions, v8::internal::WasmInternalFunction::GetOrCreateExternal(), v8::internal::WasmCapiFunction::IsWasmCapiFunction(), v8::internal::WasmExportedFunction::IsWasmExportedFunction(), v8::internal::WasmJSFunction::IsWasmJSFunction(), SBXCHECK_BOUNDS, and UpdateDispatchTable().
Referenced by Set().
SetFunctionTablePlaceholder()
void v8::internal::WasmTableObject::SetFunctionTablePlaceholder (Isolate * isolate, DirectHandle< WasmTableObject > table, int entry_index, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int func_index) [static]
Definition at line 750 of file wasm-objects.cc.
                    {
  // Put (instance, func_index) as a Tuple2 into the entry_index.
  // The {WasmExportedFunction} will be created lazily.
  // Allocate directly in old space as the tuples are typically long-lived, and
  // we create many of them, which would result in lots of GC when initializing
  // large tables.
  // TODO(42204563): Avoid crashing if the instance object is not available.
  CHECK(trusted_instance_data->has_instance_object());
  DirectHandle<Tuple2> tuple = isolate->factory()->NewTuple2(
      direct_handle(trusted_instance_data->instance_object(), isolate),
      direct_handle(Smi::FromInt(func_index), isolate), AllocationType::kOld);
  table->entries()->set(entry_index, *tuple);
}
References CHECK, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::kOld, and v8::internal::Factory::NewTuple2().
Referenced by v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::SetFunctionTablePlaceholder().
type()
kWasmDispatchTableIndirectPointerTag wasm::ValueType v8::internal::WasmTableObject::type (const wasm::WasmModule * module) [inline]
Definition at line 583 of file wasm-objects-inl.h.
                                                                {
  wasm::ValueType type = unsafe_type();
  SBXCHECK(!type.has_index() || module->has_type(type.ref_index()));
  return type;
}
References SBXCHECK, and v8::internal::tracing::type.
Referenced by New(), and unsafe_type().
unsafe_type()
wasm::ValueType v8::internal::WasmTableObject::unsafe_type () [inline]
Definition at line 597 of file wasm-objects-inl.h.
                                           {
  // Various consumers of ValueKind (e.g. ValueKind::name()) use the raw enum
  // value as index into a global array. As such, if the index is corrupted
  // (which must be assumed, as it comes from within the sandbox), this can
  // lead to out-of-bounds reads outside the sandbox. While these are not
  // technically sandbox violations, we should still try to avoid them to keep
  // fuzzers happy. This SBXCHECK accomplishes that.
  wasm::ValueType type = wasm::ValueType::FromRawBitField(raw_type());
  SBXCHECK(type.is_valid());
  return type;
}
References v8::internal::wasm::ValueType::FromRawBitField(), v8::internal::wasm::ValueTypeBase::is_valid(), SBXCHECK, and type().
Referenced by canonical_type(), Get(), and Set().
UpdateDispatchTable() [1/3]
void v8::internal::WasmTableObject::UpdateDispatchTable (Isolate * isolate, DirectHandle< WasmTableObject > table, int entry_index, const wasm::WasmFunction * func, DirectHandle< WasmTrustedInstanceData > target_instance) [static]
Definition at line 541 of file wasm-objects.cc.
  {
  DirectHandle<TrustedObject> implicit_arg =
      func->imported
          // The function in the target instance was imported. Use its imports
          // table to look up the ref.
          ? direct_handle(Cast<TrustedObject>(
                              target_instance_data->dispatch_table_for_imports()
                                  ->implicit_arg(func->func_index)),
                          isolate)
          // For wasm functions, just pass the target instance data.
          : target_instance_data;
#if V8_ENABLE_DRUMBRAKE
  if (target_func_index <
      static_cast<int>(
          target_instance_data->module()->num_imported_functions)) {
    target_func_index = target_instance_data->imported_function_indices()->get(
        target_func_index);
  }
#endif // V8_ENABLE_DRUMBRAKE
  const WasmModule* target_module = target_instance_data->module();
  wasm::CanonicalTypeIndex sig_id =
      target_module->canonical_sig_id(func->sig_index);
  DirectHandle<WasmDispatchTable> dispatch_table(
      table->trusted_dispatch_table(isolate), isolate);
  SBXCHECK(FunctionSigMatchesTable(sig_id, dispatch_table->table_type()));
  if (v8_flags.wasm_generic_wrapper && IsWasmImportData(*implicit_arg)) {
    auto import_data = Cast<WasmImportData>(implicit_arg);
    constexpr bool kShared = false;
    DirectHandle<WasmImportData> new_import_data =
        isolate->factory()->NewWasmImportData(import_data, kShared);
    new_import_data->set_call_origin(*dispatch_table);
    new_import_data->set_table_slot(entry_index);
    implicit_arg = new_import_data;
  }
  std::optional<std::shared_ptr<wasm::WasmImportWrapperHandle>> maybe_wrapper =
      target_instance_data->dispatch_table_for_imports()->MaybeGetWrapperHandle(
          func->func_index);
  if (maybe_wrapper) {
    CHECK(IsWasmImportData(*implicit_arg));
    dispatch_table->SetForWrapper(entry_index,
                                  Cast<WasmImportData>(*implicit_arg),
                                  *maybe_wrapper, sig_id,
#if V8_ENABLE_DRUMBRAKE
                                  target_func_index,
#endif
                                  WasmDispatchTable::kExistingEntry);
#if V8_ENABLE_DRUMBRAKE
  } else if (v8_flags.wasm_jitless) {
    DCHECK(v8_flags.wasm_jitless);
    if (IsWasmImportData(*implicit_arg)) {
      dispatch_table->SetForWrapper(
          entry_index, Cast<WasmImportData>(*implicit_arg), {}, sig_id,
          target_func_index, WasmDispatchTable::kExistingEntry);
    } else {
      dispatch_table->SetForNonWrapper(
          entry_index, Cast<WasmTrustedInstanceData>(*implicit_arg), {}, sig_id,
          target_func_index, WasmDispatchTable::kExistingEntry);
    }
    Tagged<ProtectedWeakFixedArray> uses = dispatch_table->protected_uses();
    int used_length = GetUsedLength(uses);
    for (int i = kReservedSlotOffset; i < used_length; i += 2) {
      if (uses->get(i).IsCleared()) continue;
      Tagged<WasmTrustedInstanceData> instance = GetInstance(uses, i);
      if (instance->has_interpreter_object()) {
        int table_index = GetTableIndex(uses, i);
        wasm::WasmInterpreterRuntime::UpdateIndirectCallTable(
            isolate, direct_handle(instance->instance_object(), isolate),
            table_index);
      }
    }
#endif // V8_ENABLE_DRUMBRAKE
  } else {
    CHECK(IsWasmTrustedInstanceData(*implicit_arg));
    dispatch_table->SetForNonWrapper(
        entry_index, Cast<WasmTrustedInstanceData>(*implicit_arg),
        target_instance_data->GetCallTarget(func->func_index), sig_id,
#if V8_ENABLE_DRUMBRAKE
        target_func_index,
#endif
        WasmDispatchTable::kExistingEntry);
  }
}
References v8::internal::wasm::WasmModule::canonical_sig_id(), CHECK, v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::wasm::WasmFunction::func_index, v8::internal::anonymous_namespace{wasm-objects.cc}::GetInstance(), v8::internal::anonymous_namespace{wasm-objects.cc}::GetTableIndex(), v8::internal::anonymous_namespace{wasm-objects.cc}::GetUsedLength(), v8::internal::wasm::WasmFunction::imported, v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::WasmDispatchTable::kExistingEntry, v8::internal::anonymous_namespace{wasm-objects.cc}::kReservedSlotOffset, SBXCHECK, v8::internal::wasm::WasmFunction::sig_index, v8::internal::wasm::WasmInterpreterRuntime::UpdateIndirectCallTable(), and v8::internal::v8_flags.
Referenced by SetFunctionTableEntry(), and v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::SetFunctionTablePlaceholder().
UpdateDispatchTable() [2/3]
void v8::internal::WasmTableObject::UpdateDispatchTable (Isolate * isolate, DirectHandle< WasmTableObject > table, int entry_index, DirectHandle< WasmCapiFunction > capi_function) [static]
Definition at line 694 of file wasm-objects.cc.
                                                  {
  DirectHandle<WasmCapiFunctionData> func_data(
      capi_function->shared()->wasm_capi_function_data(), isolate);
  const wasm::CanonicalSig* sig = func_data->sig();
  DCHECK(wasm::GetTypeCanonicalizer()->Contains(sig));
  wasm::CanonicalTypeIndex sig_index = func_data->sig_index();
  wasm::WasmImportWrapperCache* cache = wasm::GetWasmImportWrapperCache();
  auto kind = wasm::ImportCallKind::kWasmToCapi;
  int param_count = static_cast<int>(sig->parameter_count());
  std::shared_ptr<wasm::WasmImportWrapperHandle> wrapper_handle =
      cache->GetCompiled(isolate, kind, sig_index, param_count,
                         wasm::kNoSuspend, sig);
  Tagged<WasmImportData> implicit_arg =
      Cast<WasmImportData>(func_data->internal()->implicit_arg());
  Tagged<WasmDispatchTable> dispatch_table =
      table->trusted_dispatch_table(isolate);
  SBXCHECK(FunctionSigMatchesTable(sig_index, dispatch_table->table_type()));
  dispatch_table->SetForWrapper(entry_index, implicit_arg, wrapper_handle,
                                sig_index,
#if V8_ENABLE_DRUMBRAKE
                                WasmDispatchTable::kInvalidFunctionIndex,
#endif // V8_ENABLE_DRUMBRAKE
                                WasmDispatchTable::kExistingEntry);
}
References v8::internal::anonymous_namespace{read-only-promotion.cc}::Contains(), v8::internal::DCHECK(), v8::internal::wasm::WasmImportWrapperCache::GetCompiled(), v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::wasm::GetWasmImportWrapperCache(), v8::internal::WasmDispatchTable::kExistingEntry, v8::internal::wasm::kNoSuspend, v8::internal::wasm::kWasmToCapi, SBXCHECK, and v8::internal::sig.
UpdateDispatchTable() [3/3]
void v8::internal::WasmTableObject::UpdateDispatchTable (Isolate * isolate, DirectHandle< WasmTableObject > table, int entry_index, DirectHandle< WasmJSFunction > function) [static]
Definition at line 638 of file wasm-objects.cc.
                                           {
  Tagged<WasmJSFunctionData> function_data =
      function->shared()->wasm_js_function_data();
  wasm::CanonicalTypeIndex sig_id = function_data->sig_index();
  DirectHandle<WasmDispatchTable> dispatch_table(
      table->trusted_dispatch_table(isolate), isolate);
  SBXCHECK(FunctionSigMatchesTable(sig_id, dispatch_table->table_type()));
  std::shared_ptr<wasm::WasmImportWrapperHandle> wrapper_handle =
      function_data->offheap_data()->wrapper_handle();
  DirectHandle<WasmImportData> import_data(
      Cast<WasmImportData>(function_data->internal()->implicit_arg()), isolate);
#ifdef DEBUG
  Address call_target =
      wasm::GetProcessWideWasmCodePointerTable()
          ->GetEntrypointWithoutSignatureCheck(wrapper_handle->code_pointer());
#endif
  if (wrapper_handle->has_code()) {
    DCHECK_EQ(wrapper_handle->code().instruction_start(), call_target);
  } else {
    const wasm::CanonicalSig* sig =
        wasm::GetWasmEngine()->type_canonicalizer()->LookupFunctionSignature(
            sig_id);
    // We still don't have a compiled wrapper. Allocate a new import_data
    // so we can store the proper call_origin for later wrapper tier-up.
    DCHECK(call_target ==
               Builtins::EmbeddedEntryOf(Builtin::kWasmToJsWrapperAsm) ||
           call_target ==
               Builtins::EmbeddedEntryOf(Builtin::kWasmToJsWrapperInvalidSig));
    constexpr bool kShared = false;
    wasm::Suspend suspend = function_data->GetSuspend();
    import_data = isolate->factory()->NewWasmImportData(
        function, suspend, MaybeDirectHandle<WasmTrustedInstanceData>{}, sig,
        kShared);
    import_data->SetIndexInTableAsCallOrigin(*dispatch_table, entry_index);
  }
  DCHECK(wrapper_handle->has_code() ||
         call_target ==
             Builtins::EmbeddedEntryOf(Builtin::kWasmToJsWrapperAsm) ||
         call_target ==
             Builtins::EmbeddedEntryOf(Builtin::kWasmToJsWrapperInvalidSig));
  dispatch_table->SetForWrapper(entry_index, *import_data, wrapper_handle,
                                sig_id,
#if V8_ENABLE_DRUMBRAKE
                                WasmDispatchTable::kInvalidFunctionIndex,
#endif // V8_ENABLE_DRUMBRAKE
                                WasmDispatchTable::kExistingEntry);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Builtins::EmbeddedEntryOf(), v8::internal::Isolate::factory(), v8::internal::wasm::WasmCodePointerTable::GetEntrypointWithoutSignatureCheck(), v8::internal::wasm::GetProcessWideWasmCodePointerTable(), v8::internal::wasm::GetWasmEngine(), v8::internal::WasmDispatchTable::kExistingEntry, v8::internal::wasm::TypeCanonicalizer::LookupFunctionSignature(), SBXCHECK, v8::internal::sig, and v8::internal::wasm::WasmEngine::type_canonicalizer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects-inl.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc