v8::internal::IncrementalMarkingJob::Task Class Reference
Public Member Functions
Task (Isolate *isolate, IncrementalMarkingJob *job, StackState stack_state)
void RunInternal () override
Isolate * isolate () const
Private Attributes
Isolate *const isolate_
IncrementalMarkingJob *const job_
const StackState stack_state_
Additional Inherited Members
Detailed Description
Definition at line 27 of file incremental-marking-job.cc.
Constructor & Destructor Documentation
Task()
v8::internal::IncrementalMarkingJob::Task::Task (Isolate * isolate, IncrementalMarkingJob * job, StackState stack_state) [inline]
Definition at line 29 of file incremental-marking-job.cc.
      : CancelableTask(isolate),
        isolate_(isolate),
        job_(job),
        stack_state_(stack_state) {}
Member Function Documentation
isolate()
Isolate* v8::internal::IncrementalMarkingJob::Task::isolate () const [inline]
Definition at line 38 of file incremental-marking-job.cc.
{ return isolate_; }
References isolate_.
Referenced by RunInternal().
RunInternal()
void v8::internal::IncrementalMarkingJob::Task::RunInternal () [override], [virtual]
Implements v8::internal::CancelableTask.
Definition at line 89 of file incremental-marking-job.cc.
                                            {
  VMState<GC> state(isolate());
  TRACE_EVENT_CALL_STATS_SCOPED(isolate(), "v8",
                                "V8.IncrementalMarkingJob.Task");
  // Set the current isolate such that trusted pointer tables etc are
  // available and the cage base is set correctly for multi-cage mode.
  SetCurrentIsolateScope isolate_scope(isolate());
  isolate()->stack_guard()->ClearStartIncrementalMarking();
  Heap* heap = isolate()->heap();
  {
    base::MutexGuard guard(&job_->mutex_);
    heap->tracer()->RecordTimeToIncrementalMarkingTask(
        v8::base::TimeTicks::Now() - job_->scheduled_time_);
    job_->scheduled_time_ = v8::base::TimeTicks();
  }
  EmbedderStackStateScope scope(
      heap, EmbedderStackStateOrigin::kImplicitThroughTask, stack_state_);
  IncrementalMarking* incremental_marking = heap->incremental_marking();
  if (incremental_marking->IsStopped()) {
    if (heap->IncrementalMarkingLimitReached() !=
        Heap::IncrementalMarkingLimit::kNoLimit) {
      heap->StartIncrementalMarking(heap->GCFlagsForIncrementalMarking(),
                                    GarbageCollectionReason::kTask,
                                    kGCCallbackScheduleIdleGarbageCollection);
    } else if (v8_flags.minor_ms && v8_flags.concurrent_minor_ms_marking) {
      heap->StartMinorMSConcurrentMarkingIfNeeded();
    }
  }
  // Clear this flag after StartIncrementalMarking() call to avoid scheduling a
  // new task when starting incremental marking from a task.
  {
    base::MutexGuard guard(&job_->mutex_);
    if (V8_UNLIKELY(v8_flags.trace_incremental_marking)) {
      job_->heap_->isolate()->PrintWithTimestamp(
          "[IncrementalMarking] Job: Run\n");
    }
    job_->pending_task_ = false;
  }
  if (incremental_marking->IsMajorMarking()) {
    heap->incremental_marking()->AdvanceAndFinalizeIfComplete();
    if (incremental_marking->IsMajorMarking()) {
      if (V8_UNLIKELY(v8_flags.trace_incremental_marking)) {
        isolate()->PrintWithTimestamp(
            "[IncrementalMarking] Using regular task based on flags\n");
      }
      job_->ScheduleTask();
    }
  }
}
References v8::internal::Isolate::heap(), v8::internal::IncrementalMarkingJob::heap_, v8::internal::IncrementalMarking::IsMajorMarking(), v8::internal::Heap::isolate(), isolate(), v8::internal::IncrementalMarking::IsStopped(), job_, v8::kGCCallbackScheduleIdleGarbageCollection, v8::internal::kImplicitThroughTask, v8::internal::Heap::kNoLimit, v8::internal::kTask, v8::internal::IncrementalMarkingJob::mutex_, v8::base::TimeTicks::Now(), v8::internal::IncrementalMarkingJob::pending_task_, v8::internal::IncrementalMarkingJob::scheduled_time_, v8::internal::IncrementalMarkingJob::ScheduleTask(), v8::internal::Isolate::stack_guard(), stack_state_, TRACE_EVENT_CALL_STATS_SCOPED, v8::internal::v8_flags, and V8_UNLIKELY.
Member Data Documentation
isolate_
Isolate* const v8::internal::IncrementalMarkingJob::Task::isolate_ [private]
Definition at line 41 of file incremental-marking-job.cc.
Referenced by isolate().
job_
IncrementalMarkingJob* const v8::internal::IncrementalMarkingJob::Task::job_ [private]
Definition at line 42 of file incremental-marking-job.cc.
Referenced by RunInternal().
stack_state_
const StackState v8::internal::IncrementalMarkingJob::Task::stack_state_ [private]
Definition at line 43 of file incremental-marking-job.cc.
Referenced by RunInternal().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/incremental-marking-job.cc