v8::internal::ContextCell Class Reference
#include <contexts.h>
Public Types
enum State : int32_t {
kConst = 0
, kSmi = 1
, kInt32 = 2
, kFloat64 = 3
,
kDetached = 4
 }
Public Member Functions
State state () const
void set_state (State state)
Tagged< DependentCode > dependent_code () const
void set_dependent_code (Tagged< DependentCode > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< JSAny > tagged_value () const
void set_tagged_value (Tagged< JSAny > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void clear_tagged_value ()
void set_smi_value (Tagged< Smi > value)
int32_t int32_value () const
void set_int32_value (int32_t value)
double float64_value () const
void set_float64_value (double value)
void clear_padding ()
Private Attributes
TaggedMember< JSAny > tagged_value_
TaggedMember< DependentCode > dependent_code_
std::atomic< State > state_
UnalignedDoubleMember double_value_
Friends
class CodeStubAssembler
struct ObjectTraits< ContextCell >
class TorqueGeneratedContextCellAsserts
class maglev::MaglevGraphBuilder
class maglev::MaglevAssembler
class compiler::AccessBuilder
Detailed Description
Definition at line 884 of file contexts.h.
Member Enumeration Documentation
State
enum v8::internal::ContextCell::State : int32_t
Enumerator
kConst
kSmi
kInt32
kFloat64
kDetached
Definition at line 886 of file contexts.h.
             : int32_t {
    kConst = 0,
    kSmi = 1,
    kInt32 = 2,
    kFloat64 = 3,
    kDetached = 4, // The context cell is not attached to a context anymore.
  };
Member Function Documentation
clear_padding()
void v8::internal::ContextCell::clear_padding () [inline]
Definition at line 399 of file contexts-inl.h.
                                {
#if TAGGED_SIZE_8_BYTES
  optional_padding_ = 0;
#endif // TAGGED_SIZE_8_BYTES
}
clear_tagged_value()
void v8::internal::ContextCell::clear_tagged_value () [inline]
Definition at line 395 of file contexts-inl.h.
                                     {
  set_tagged_value(Smi::FromInt(0), SKIP_WRITE_BARRIER);
}
References v8::internal::Smi::FromInt(), set_tagged_value(), and v8::internal::SKIP_WRITE_BARRIER.
dependent_code()
Tagged< DependentCode > v8::internal::ContextCell::dependent_code () const [inline]
Definition at line 374 of file contexts-inl.h.
                                                        {
  return dependent_code_.load();
}
References dependent_code_.
float64_value()
double v8::internal::ContextCell::float64_value () const [inline]
Definition at line 405 of file contexts-inl.h.
                                        {
  DCHECK_EQ(state(), kFloat64);
  return double_value_.value();
}
References DCHECK_EQ, double_value_, kFloat64, state(), and v8::internal::UnalignedValueMember< T >::value().
int32_value()
int32_t v8::internal::ContextCell::int32_value () const [inline]
Definition at line 414 of file contexts-inl.h.
                                       {
  DCHECK_EQ(state(), kInt32);
  return *reinterpret_cast<const int32_t*>(&double_value_);
}
References DCHECK_EQ, double_value_, kInt32, and state().
set_dependent_code()
void v8::internal::ContextCell::set_dependent_code (Tagged< DependentCode > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 378 of file contexts-inl.h.
                                                            {
  dependent_code_.store(this, value, mode);
}
References dependent_code_, mode(), and v8::internal::value.
set_float64_value()
void v8::internal::ContextCell::set_float64_value (double value) [inline]
Definition at line 410 of file contexts-inl.h.
                                                {
  double_value_.set_value(value);
}
References double_value_, v8::internal::UnalignedValueMember< T >::set_value(), and v8::internal::value.
set_int32_value()
void v8::internal::ContextCell::set_int32_value (int32_t value) [inline]
Definition at line 419 of file contexts-inl.h.
                                               {
  *reinterpret_cast<int32_t*>(&double_value_) = value;
}
References double_value_, and v8::internal::value.
set_smi_value()
void v8::internal::ContextCell::set_smi_value (Tagged< Smi > value) [inline]
Definition at line 391 of file contexts-inl.h.
                                                 {
  tagged_value_.Relaxed_Store(this, value);
}
References tagged_value_, and v8::internal::value.
set_state()
void v8::internal::ContextCell::set_state (ContextCell::State state) [inline]
Definition at line 370 of file contexts-inl.h.
                                                  {
  return state_.store(state, std::memory_order_release);
}
References state(), and state_.
set_tagged_value()
void v8::internal::ContextCell::set_tagged_value (Tagged< JSAny > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 387 of file contexts-inl.h.
                                                                             {
  tagged_value_.Relaxed_Store(this, value, mode);
}
References mode(), tagged_value_, and v8::internal::value.
Referenced by clear_tagged_value().
state()
ContextCell::State v8::internal::ContextCell::state () const [inline]
Definition at line 366 of file contexts-inl.h.
                                          {
  return state_.load(std::memory_order_acquire);
}
References state_.
Referenced by float64_value(), int32_value(), and set_state().
tagged_value()
Tagged< JSAny > v8::internal::ContextCell::tagged_value () const [inline]
Definition at line 383 of file contexts-inl.h.
                                              {
  return tagged_value_.Relaxed_Load();
}
References tagged_value_.
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 920 of file contexts.h.
compiler::AccessBuilder
friend class compiler::AccessBuilder [friend]
Definition at line 925 of file contexts.h.
maglev::MaglevAssembler
friend class maglev::MaglevAssembler [friend]
Definition at line 924 of file contexts.h.
maglev::MaglevGraphBuilder
friend class maglev::MaglevGraphBuilder [friend]
Definition at line 923 of file contexts.h.
ObjectTraits< ContextCell >
friend struct ObjectTraits< ContextCell > [friend]
Definition at line 920 of file contexts.h.
TorqueGeneratedContextCellAsserts
friend class TorqueGeneratedContextCellAsserts [friend]
Definition at line 922 of file contexts.h.
Member Data Documentation
dependent_code_
TaggedMember<DependentCode> v8::internal::ContextCell::dependent_code_ [private]
Definition at line 928 of file contexts.h.
Referenced by dependent_code(), and set_dependent_code().
double_value_
UnalignedDoubleMember v8::internal::ContextCell::double_value_ [private]
Definition at line 933 of file contexts.h.
Referenced by float64_value(), int32_value(), set_float64_value(), and set_int32_value().
state_
std::atomic<State> v8::internal::ContextCell::state_ [private]
Definition at line 929 of file contexts.h.
Referenced by set_state(), and state().
tagged_value_
TaggedMember<JSAny> v8::internal::ContextCell::tagged_value_ [private]
Definition at line 927 of file contexts.h.
Referenced by set_smi_value(), set_tagged_value(), and tagged_value().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/contexts.h
/mnt/V8SourceCode/src/objects/contexts-inl.h