v8::internal::VRegister Class Reference
#include <register-arm64.h>
Public Member Functions
VRegister V8B () const
VRegister V16B () const
VRegister V4H () const
VRegister V8H () const
VRegister V2S () const
VRegister V4S () const
VRegister V2D () const
VRegister V1D () const
VRegister V1Q () const
VRegister Format (VectorFormat f) const
bool Is8B () const
bool Is16B () const
bool Is4H () const
bool Is8H () const
bool Is2S () const
bool Is4S () const
bool Is1D () const
bool Is2D () const
bool Is1Q () const
bool Is1B () const
bool Is1H () const
bool Is1S () const
bool IsLaneSizeB () const
bool IsLaneSizeH () const
bool IsLaneSizeS () const
bool IsLaneSizeD () const
bool IsScalar () const
bool IsVector () const
bool IsSameFormat (const VRegister &other) const
int LaneCount () const
unsigned LaneSizeInBytes () const
unsigned LaneSizeInBits () const
constexpr VRegister (int code)
Static Public Member Functions
static constexpr VRegister no_reg ()
static constexpr VRegister Create (int code, int size, int lane_count=1)
static VRegister Create (int reg_code, VectorFormat format)
static VRegister BRegFromCode (unsigned code)
static VRegister HRegFromCode (unsigned code)
static VRegister SRegFromCode (unsigned code)
static VRegister DRegFromCode (unsigned code)
static VRegister QRegFromCode (unsigned code)
static VRegister VRegFromCode (unsigned code)
static constexpr VRegister from_code (int code)
Static Public Attributes
static constexpr int kMaxNumRegisters = kNumberOfVRegisters
Private Member Functions
constexpr VRegister (const CPURegister &r, int lane_count)
Static Private Member Functions
static constexpr bool IsValidLaneCount (int lane_count)
Private Attributes
int8_t lane_count_
Friends
class RegisterBase
Additional Inherited Members
Detailed Description
Definition at line 346 of file register-arm64.h.
Constructor & Destructor Documentation
VRegister() [1/2]
constexpr v8::internal::VRegister::VRegister (const CPURegister & r, int lane_count) [inline], [explicit], [constexpr], [private]
Definition at line 458 of file register-arm64.h.
      : CPURegister(r), lane_count_(lane_count) {}
Referenced by Create(), and no_reg().
VRegister() [2/2]
constexpr v8::internal::VRegister::VRegister (int code) [inline], [explicit], [constexpr]
Definition at line 204 of file register-riscv.h.
: RegisterBase(code) {}
Member Function Documentation
BRegFromCode()
VRegister v8::internal::VRegister::BRegFromCode (unsigned code) [inline], [static]
Definition at line 117 of file assembler-arm64-inl.h.
                                                      {
  DCHECK_LT(code, static_cast<unsigned>(kNumberOfVRegisters));
  return VRegister::Create(code, kBRegSizeInBits);
}
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), DCHECK_LT, v8::internal::kBRegSizeInBits, and v8::internal::kNumberOfVRegisters.
Referenced by v8::internal::CPURegister::B().
Create() [1/2]
static constexpr VRegister v8::internal::VRegister::Create (int code, int size, int lane_count = 1) [inline], [static], [constexpr]
Definition at line 352 of file register-arm64.h.
                                                                            {
    DCHECK(IsValidLaneCount(lane_count));
    return VRegister(CPURegister::Create(code, size, CPURegister::kVRegister),
                     lane_count);
  }
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), v8::internal::CPURegister::Create(), v8::internal::DCHECK(), IsValidLaneCount(), v8::internal::CPURegister::kVRegister, size(), and VRegister().
Referenced by v8::internal::UseScratchRegisterScope::AcquireSameSizeAs(), v8::internal::UseScratchRegisterScope::AcquireV(), BRegFromCode(), Create(), DRegFromCode(), v8::internal::wasm::liftoff::EmitAllTrue(), v8::internal::compiler::anonymous_namespace{code-generator-arm64.cc}::EmitFpOrNeonUnop(), Format(), from_code(), HRegFromCode(), QRegFromCode(), v8::internal::compiler::Shuffle1Helper(), v8::internal::compiler::Shuffle2Helper(), v8::internal::compiler::Shuffle4Helper(), SRegFromCode(), V16B(), V1D(), V1Q(), V2D(), V2S(), V4H(), V4S(), V8B(), V8H(), v8::internal::CPURegister::VReg(), and VRegFromCode().
Create() [2/2]
static VRegister v8::internal::VRegister::Create (int reg_code, VectorFormat format) [inline], [static]
Definition at line 358 of file register-arm64.h.
                                                             {
    int reg_size = RegisterSizeInBitsFromFormat(format);
    int reg_count = IsVectorFormat(format) ? LaneCountFromFormat(format) : 1;
    return VRegister::Create(reg_code, reg_size, reg_count);
  }
References Create(), v8::internal::format, v8::internal::IsVectorFormat(), v8::internal::LaneCountFromFormat(), and v8::internal::RegisterSizeInBitsFromFormat().
DRegFromCode()
VRegister v8::internal::VRegister::DRegFromCode (unsigned code) [inline], [static]
Definition at line 132 of file assembler-arm64-inl.h.
                                                      {
  DCHECK_LT(code, static_cast<unsigned>(kNumberOfVRegisters));
  return VRegister::Create(code, kDRegSizeInBits);
}
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), DCHECK_LT, v8::internal::kDRegSizeInBits, and v8::internal::kNumberOfVRegisters.
Referenced by v8::internal::CPURegister::D().
Format()
VRegister v8::internal::VRegister::Format (VectorFormat f) const [inline]
Definition at line 399 of file register-arm64.h.
                                         {
    return VRegister::Create(code(), f);
  }
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), and Create().
from_code()
static constexpr VRegister v8::internal::VRegister::from_code (int code) [inline], [static], [constexpr]
Definition at line 450 of file register-arm64.h.
                                                 {
    // Always return a D register.
    return VRegister::Create(code, kDRegSizeInBits);
  }
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), and v8::internal::kDRegSizeInBits.
HRegFromCode()
VRegister v8::internal::VRegister::HRegFromCode (unsigned code) [inline], [static]
Definition at line 122 of file assembler-arm64-inl.h.
                                                      {
  DCHECK_LT(code, static_cast<unsigned>(kNumberOfVRegisters));
  return VRegister::Create(code, kHRegSizeInBits);
}
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), DCHECK_LT, v8::internal::kHRegSizeInBits, and v8::internal::kNumberOfVRegisters.
Referenced by v8::internal::CPURegister::H().
Is16B()
bool v8::internal::VRegister::Is16B () const [inline]
Definition at line 404 of file register-arm64.h.
{ return (Is128Bits() && (lane_count_ == 16)); }
References v8::internal::CPURegister::Is128Bits(), and lane_count_.
Is1B()
bool v8::internal::VRegister::Is1B () const [inline]
Definition at line 416 of file register-arm64.h.
                    {
    DCHECK(!(Is8Bits() && IsVector()));
    return Is8Bits();
  }
References v8::internal::DCHECK(), v8::internal::CPURegister::Is8Bits(), and IsVector().
Is1D()
bool v8::internal::VRegister::Is1D () const [inline]
Definition at line 409 of file register-arm64.h.
{ return (Is64Bits() && (lane_count_ == 1)); }
References v8::internal::CPURegister::Is64Bits(), and lane_count_.
Referenced by v8::internal::MacroAssembler::Fmov().
Is1H()
bool v8::internal::VRegister::Is1H () const [inline]
Definition at line 420 of file register-arm64.h.
                    {
    DCHECK(!(Is16Bits() && IsVector()));
    return Is16Bits();
  }
References v8::internal::DCHECK(), v8::internal::CPURegister::Is16Bits(), and IsVector().
Is1Q()
bool v8::internal::VRegister::Is1Q () const [inline]
Definition at line 411 of file register-arm64.h.
{ return (Is128Bits() && (lane_count_ == 1)); }
References v8::internal::CPURegister::Is128Bits(), and lane_count_.
Is1S()
bool v8::internal::VRegister::Is1S () const [inline]
Definition at line 424 of file register-arm64.h.
                    {
    DCHECK(!(Is32Bits() && IsVector()));
    return Is32Bits();
  }
References v8::internal::DCHECK(), v8::internal::CPURegister::Is32Bits(), and IsVector().
Referenced by v8::internal::MacroAssembler::Fmov().
Is2D()
bool v8::internal::VRegister::Is2D () const [inline]
Definition at line 410 of file register-arm64.h.
{ return (Is128Bits() && (lane_count_ == 2)); }
References v8::internal::CPURegister::Is128Bits(), and lane_count_.
Referenced by v8::internal::wasm::liftoff::EmitSimdShift(), and v8::internal::MacroAssembler::Fmov().
Is2S()
bool v8::internal::VRegister::Is2S () const [inline]
Definition at line 407 of file register-arm64.h.
{ return (Is64Bits() && (lane_count_ == 2)); }
References v8::internal::CPURegister::Is64Bits(), and lane_count_.
Referenced by v8::internal::MacroAssembler::Fmov().
Is4H()
bool v8::internal::VRegister::Is4H () const [inline]
Definition at line 405 of file register-arm64.h.
{ return (Is64Bits() && (lane_count_ == 4)); }
References v8::internal::CPURegister::Is64Bits(), and lane_count_.
Is4S()
bool v8::internal::VRegister::Is4S () const [inline]
Definition at line 408 of file register-arm64.h.
{ return (Is128Bits() && (lane_count_ == 4)); }
References v8::internal::CPURegister::Is128Bits(), and lane_count_.
Referenced by v8::internal::MacroAssembler::Fmov().
Is8B()
bool v8::internal::VRegister::Is8B () const [inline]
Definition at line 403 of file register-arm64.h.
{ return (Is64Bits() && (lane_count_ == 8)); }
References v8::internal::CPURegister::Is64Bits(), and lane_count_.
Is8H()
bool v8::internal::VRegister::Is8H () const [inline]
Definition at line 406 of file register-arm64.h.
{ return (Is128Bits() && (lane_count_ == 8)); }
References v8::internal::CPURegister::Is128Bits(), and lane_count_.
IsLaneSizeB()
bool v8::internal::VRegister::IsLaneSizeB () const [inline]
Definition at line 429 of file register-arm64.h.
{ return LaneSizeInBits() == kBRegSizeInBits; }
References v8::internal::kBRegSizeInBits, and LaneSizeInBits().
IsLaneSizeD()
bool v8::internal::VRegister::IsLaneSizeD () const [inline]
Definition at line 432 of file register-arm64.h.
{ return LaneSizeInBits() == kDRegSizeInBits; }
References v8::internal::kDRegSizeInBits, and LaneSizeInBits().
IsLaneSizeH()
bool v8::internal::VRegister::IsLaneSizeH () const [inline]
Definition at line 430 of file register-arm64.h.
{ return LaneSizeInBits() == kHRegSizeInBits; }
References v8::internal::kHRegSizeInBits, and LaneSizeInBits().
IsLaneSizeS()
bool v8::internal::VRegister::IsLaneSizeS () const [inline]
Definition at line 431 of file register-arm64.h.
{ return LaneSizeInBits() == kSRegSizeInBits; }
References v8::internal::kSRegSizeInBits, and LaneSizeInBits().
IsSameFormat()
bool v8::internal::VRegister::IsSameFormat (const VRegister & other) const [inline]
Definition at line 437 of file register-arm64.h.
                                                  {
    return (reg_size_ == other.reg_size_) && (lane_count_ == other.lane_count_);
  }
References lane_count_, and v8::internal::CPURegister::reg_size_.
Referenced by v8::internal::wasm::liftoff::EmitSimdShift().
IsScalar()
bool v8::internal::VRegister::IsScalar () const [inline]
Definition at line 434 of file register-arm64.h.
{ return lane_count_ == 1; }
References lane_count_.
Referenced by v8::internal::MacroAssembler::Fmov(), and v8::internal::Assembler::SFormat().
IsValidLaneCount()
static constexpr bool v8::internal::VRegister::IsValidLaneCount (int lane_count) [inline], [static], [constexpr], [private]
Definition at line 461 of file register-arm64.h.
                                                         {
    return base::bits::IsPowerOfTwo(lane_count) && lane_count <= 16;
  }
References v8::base::bits::IsPowerOfTwo().
Referenced by Create().
IsVector()
bool v8::internal::VRegister::IsVector () const [inline]
Definition at line 435 of file register-arm64.h.
{ return lane_count_ > 1; }
References lane_count_.
Referenced by Is1B(), Is1H(), and Is1S().
LaneCount()
int v8::internal::VRegister::LaneCount () const [inline]
Definition at line 441 of file register-arm64.h.
{ return lane_count_; }
References lane_count_.
Referenced by v8::internal::wasm::liftoff::EmitSimdShift(), v8::internal::Assembler::FPFormat(), v8::internal::Assembler::LSVFormat(), and v8::internal::Assembler::VFormat().
LaneSizeInBits()
unsigned v8::internal::VRegister::LaneSizeInBits () const [inline]
Definition at line 445 of file register-arm64.h.
{ return LaneSizeInBytes() * 8; }
References LaneSizeInBytes().
Referenced by IsLaneSizeB(), IsLaneSizeD(), IsLaneSizeH(), and IsLaneSizeS().
LaneSizeInBytes()
unsigned v8::internal::VRegister::LaneSizeInBytes () const [inline]
Definition at line 443 of file register-arm64.h.
{ return SizeInBytes() / lane_count_; }
References lane_count_, and v8::internal::CPURegister::SizeInBytes().
Referenced by LaneSizeInBits().
no_reg()
static constexpr VRegister v8::internal::VRegister::no_reg () [inline], [static], [constexpr]
Definition at line 348 of file register-arm64.h.
                                      {
    return VRegister(CPURegister::no_reg(), 0);
  }
References v8::internal::CPURegister::no_reg(), and VRegister().
QRegFromCode()
VRegister v8::internal::VRegister::QRegFromCode (unsigned code) [inline], [static]
Definition at line 137 of file assembler-arm64-inl.h.
                                                      {
  DCHECK_LT(code, static_cast<unsigned>(kNumberOfVRegisters));
  return VRegister::Create(code, kQRegSizeInBits);
}
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), DCHECK_LT, v8::internal::kNumberOfVRegisters, and v8::internal::kQRegSizeInBits.
Referenced by v8::internal::CPURegister::Q().
SRegFromCode()
VRegister v8::internal::VRegister::SRegFromCode (unsigned code) [inline], [static]
Definition at line 127 of file assembler-arm64-inl.h.
                                                      {
  DCHECK_LT(code, static_cast<unsigned>(kNumberOfVRegisters));
  return VRegister::Create(code, kSRegSizeInBits);
}
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), DCHECK_LT, v8::internal::kNumberOfVRegisters, and v8::internal::kSRegSizeInBits.
Referenced by v8::internal::CPURegister::S().
V16B()
VRegister v8::internal::VRegister::V16B () const [inline]
Definition at line 374 of file register-arm64.h.
                         {
    return VRegister::Create(code(), kQRegSizeInBits, 16);
  }
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), and v8::internal::kQRegSizeInBits.
V1D()
VRegister v8::internal::VRegister::V1D () const [inline]
Definition at line 392 of file register-arm64.h.
                        {
    return VRegister::Create(code(), kDRegSizeInBits, 1);
  }
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), and v8::internal::kDRegSizeInBits.
V1Q()
VRegister v8::internal::VRegister::V1Q () const [inline]
Definition at line 395 of file register-arm64.h.
                        {
    return VRegister::Create(code(), kQRegSizeInBits, 1);
  }
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), and v8::internal::kQRegSizeInBits.
V2D()
VRegister v8::internal::VRegister::V2D () const [inline]
Definition at line 389 of file register-arm64.h.
                        {
    return VRegister::Create(code(), kQRegSizeInBits, 2);
  }
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), and v8::internal::kQRegSizeInBits.
V2S()
VRegister v8::internal::VRegister::V2S () const [inline]
Definition at line 383 of file register-arm64.h.
                        {
    return VRegister::Create(code(), kDRegSizeInBits, 2);
  }
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), and v8::internal::kDRegSizeInBits.
V4H()
VRegister v8::internal::VRegister::V4H () const [inline]
Definition at line 377 of file register-arm64.h.
                        {
    return VRegister::Create(code(), kDRegSizeInBits, 4);
  }
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), and v8::internal::kDRegSizeInBits.
V4S()
VRegister v8::internal::VRegister::V4S () const [inline]
Definition at line 386 of file register-arm64.h.
                        {
    return VRegister::Create(code(), kQRegSizeInBits, 4);
  }
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), and v8::internal::kQRegSizeInBits.
V8B()
VRegister v8::internal::VRegister::V8B () const [inline]
Definition at line 371 of file register-arm64.h.
                        {
    return VRegister::Create(code(), kDRegSizeInBits, 8);
  }
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), and v8::internal::kDRegSizeInBits.
V8H()
VRegister v8::internal::VRegister::V8H () const [inline]
Definition at line 380 of file register-arm64.h.
                        {
    return VRegister::Create(code(), kQRegSizeInBits, 8);
  }
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), and v8::internal::kQRegSizeInBits.
VRegFromCode()
VRegister v8::internal::VRegister::VRegFromCode (unsigned code) [inline], [static]
Definition at line 142 of file assembler-arm64-inl.h.
                                                      {
  DCHECK_LT(code, static_cast<unsigned>(kNumberOfVRegisters));
  return VRegister::Create(code, kVRegSizeInBits);
}
References v8::internal::RegisterBase< VRegister, kVRAfterLast >::code(), Create(), DCHECK_LT, v8::internal::kNumberOfVRegisters, and v8::internal::kVRegSizeInBits.
Referenced by v8::internal::CPURegister::V().
Friends And Related Function Documentation
RegisterBase
friend class RegisterBase [friend]
Definition at line 201 of file register-riscv.h.
Member Data Documentation
kMaxNumRegisters
constexpr int v8::internal::VRegister::kMaxNumRegisters = kNumberOfVRegisters [static], [constexpr]
Definition at line 447 of file register-arm64.h.
lane_count_
int8_t v8::internal::VRegister::lane_count_ [private]
Definition at line 456 of file register-arm64.h.
Referenced by Is16B(), Is1D(), Is1Q(), Is2D(), Is2S(), Is4H(), Is4S(), Is8B(), Is8H(), IsSameFormat(), IsScalar(), IsVector(), LaneCount(), and LaneSizeInBytes().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/arm64/register-arm64.h
/mnt/V8SourceCode/src/codegen/riscv/register-riscv.h
/mnt/V8SourceCode/src/codegen/arm64/assembler-arm64-inl.h