v8::internal::DirectHandle< T > Class Template Reference
#include <handles.h>
Public Types
using MaybeType = MaybeDirectHandle< T >
Public Member Functions
DirectHandle ()=default
DirectHandle (Tagged< T > object, Isolate *isolate)
DirectHandle (Tagged< T > object, LocalIsolate *isolate)
DirectHandle (Tagged< T > object, LocalHeap *local_heap)
template<typename S >
DirectHandle (DirectHandle< S > handle) requires(is_subtype_v< S
IndirectHandle< T > operator-> () const
Tagged< T > operator* () const
bool is_null () const
Address address () const
ValueHelper::InternalRepresentationType repr () const
void SetValue (Tagged< T > new_value)
bool equals (DirectHandle< T > other) const
template<typename S >
bool is_identical_to (Handle< S > other) const
template<typename S >
bool is_identical_to (DirectHandle< S > other) const
Static Public Member Functions
static const DirectHandle null ()
static DirectHandle< T > New (Tagged< T > object, Isolate *isolate)
Public Attributes
T __pad0__: handle_(handle.handle_) {} template <typename S> inline DirectHandle(IndirectHandle<S> handle) requires(is_subtype_v<S
T T: handle_(handle) {} inline static DirectHandle FromSlot(Address* slot) { return DirectHandle(IndirectHandle<T>(slot))
Private Member Functions
DirectHandle (no_checking_tag do_not_check)
DirectHandle (const DirectHandle< T > &other, no_checking_tag do_not_check)
Private Attributes
IndirectHandle< T > handle_
Friends
class HandleBase
template<typename >
class DirectHandle
template<typename >
class MaybeDirectHandle
class DirectHandleUnchecked< T >
template<typename To , typename From >
DirectHandle< To > UncheckedCast (DirectHandle< From > value)
template<typename U >
IndirectHandle< U > indirect_handle (DirectHandle< U >)
template<typename U >
IndirectHandle< U > indirect_handle (DirectHandle< U >, Isolate *)
template<typename U >
IndirectHandle< U > indirect_handle (DirectHandle< U >, LocalIsolate *)
template<typename U >
IndirectHandle< U > indirect_handle (DirectHandle< U >, LocalHeap *)
Additional Inherited Members
Detailed Description
template<typename T>
class v8::internal::DirectHandle< T >
Definition at line 654 of file handles.h.
Member Typedef Documentation
MaybeType
template<typename T >
using v8::internal::DirectHandle< T >::MaybeType = MaybeDirectHandle<T>
Definition at line 725 of file handles.h.
Constructor & Destructor Documentation
DirectHandle() [1/7]
template<typename T >
v8::internal::DirectHandle< T >::DirectHandle () [inline], [default]
DirectHandle() [2/7]
template<typename T >
v8::internal::DirectHandle< T >::DirectHandle (Tagged< T > object, Isolate * isolate) [inline]
Definition at line 671 of file handles.h.
      : handle_(object, isolate) {}
DirectHandle() [3/7]
template<typename T >
v8::internal::DirectHandle< T >::DirectHandle (Tagged< T > object, LocalIsolate * isolate) [inline]
Definition at line 673 of file handles.h.
      : handle_(object, isolate) {}
DirectHandle() [4/7]
template<typename T >
v8::internal::DirectHandle< T >::DirectHandle (Tagged< T > object, LocalHeap * local_heap) [inline]
Definition at line 675 of file handles.h.
      : handle_(object, local_heap) {}
DirectHandle() [5/7]
template<typename T >
template<typename S >
v8::internal::DirectHandle< T >::DirectHandle (DirectHandle< S > handle) [inline]
DirectHandle() [6/7]
template<typename T >
v8::internal::DirectHandle< T >::DirectHandle (no_checking_tag do_not_check) [inline], [explicit], [private]
Definition at line 748 of file handles.h.
      : StackAllocated(do_not_check), handle_() {}
DirectHandle() [7/7]
template<typename T >
v8::internal::DirectHandle< T >::DirectHandle (const DirectHandle< T > & other, no_checking_tag do_not_check) [inline], [explicit], [private]
Definition at line 750 of file handles.h.
      : StackAllocated(do_not_check), handle_(other.handle_) {}
Member Function Documentation
address()
template<typename T >
Address v8::internal::DirectHandle< T >::address () const [inline]
Definition at line 696 of file handles.h.
{ return handle_.address(); }
Referenced by v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(), v8::internal::V8FileLogger::CodeCreateEvent(), v8::Utils::Convert(), v8::internal::Factory::CopyJSObjectWithAllocationSite(), v8::internal::Debug::TemporaryObjectsTracker::HasObject(), v8::internal::Map::Normalize(), v8::internal::Deserializer< IsolateT >::ReadAllocateJSDispatchEntry(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Heap::StaticRootsEnsureAllocatedSize(), and v8::internal::StringReplaceGlobalRegExpWithEmptyString().
equals()
template<typename T >
bool v8::internal::DirectHandle< T >::equals (DirectHandle< T > other) const [inline]
Definition at line 712 of file handles.h.
                                                     {
    return handle_.equals(other.handle_);
  }
is_identical_to() [1/2]
template<typename T >
template<typename S >
bool v8::internal::DirectHandle< T >::is_identical_to (DirectHandle< S > other) const [inline]
Definition at line 721 of file handles.h.
                                                              {
    return handle_.is_identical_to(other.handle_);
  }
is_identical_to() [2/2]
template<typename T >
template<typename S >
bool v8::internal::DirectHandle< T >::is_identical_to (Handle< S > other) const [inline]
Definition at line 717 of file handles.h.
                                                        {
    return handle_.is_identical_to(other);
  }
Referenced by v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::AddImpl(), v8::internal::ValueDeserializer::AddObjectWithID(), v8::internal::LookupIterator::ApplyTransitionToDataProperty(), v8::internal::String::Compare(), v8::internal::Intl::CompareStrings(), v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), v8::internal::FeedbackNexus::ConfigureCloneObject(), v8::internal::ErrorUtils::Construct(), v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareEvalHelper(), v8::internal::anonymous_namespace{runtime-literals.cc}::DeepCopy(), v8::internal::anonymous_namespace{runtime-literals.cc}::DeepWalk(), v8::internal::Object::Equals(), v8::internal::LookupIterator::ExtendingNonExtensible(), v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::internal::anonymous_namespace{js-objects.cc}::GetConstructorHelper(), v8::internal::WasmTableObject::Grow(), v8::internal::wasm::WasmInterpreterRuntime::HandleException(), v8::internal::AlwaysSharedSpaceJSObject::HasInstance(), v8::internal::DependentCode::InstallDependency(), v8::internal::MaybeObjectDirectHandle::is_identical_to(), v8::internal::CallOptimization::IsCompatibleReceiverMap(), v8::internal::StoreIC::LookupForWrite(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::HandleValueEqual::operator()(), v8::internal::LookupIterator::PrepareTransitionToDataProperty(), v8::internal::Accessors::ReplaceAccessorWithDataProperty(), v8::internal::JSPromise::Resolve(), v8::internal::wasm::Handlers< Compressed >::s2s_RefEq(), v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::SetDictionaryMode(), v8::internal::JSProxy::SetPrivateSymbol(), v8::internal::StoreHandler::StoreProxy(), v8::internal::ValueDeserializer::TransferArrayBuffer(), and v8::internal::IC::UpdatePolymorphicIC().
is_null()
template<typename T >
bool v8::internal::DirectHandle< T >::is_null () const [inline]
Definition at line 694 of file handles.h.
{ return handle_.is_null(); }
Referenced by v8::internal::SourceCodeCache::Add(), v8::internal::ApiNatives::AddAccessorProperty(), v8::internal::SnapshotCreatorImpl::AddContext(), v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::AllocateDeclarations(), v8::internal::interpreter::BytecodeGenerator::AllocateDeferredConstants(), v8::internal::Factory::AllocateRawWithAllocationSite(), v8::internal::Builtins::AllowDynamicFunction(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::Factory::CodeBuilder::BuildInternal(), v8::internal::JsonParser< Char >::BuildJsonObject(), v8::internal::anonymous_namespace{ic.cc}::CanFastCloneObjectToObjectLiteral(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport(), v8::internal::KeyAccumulator::CollectOwnKeys(), v8::internal::Isolate::ComputeLocationFromDetailedStackTrace(), v8::internal::Genesis::ConfigureApiObject(), v8::internal::FeedbackNexus::ConfigureCloneObject(), v8::internal::anonymous_namespace{api-natives.cc}::ConfigureInstance(), v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::ConstructBuffer(), v8::Utils::Convert(), v8::internal::Factory::CopyJSObjectWithAllocationSite(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::CreateEnvironment(), v8::internal::Bootstrapper::CreateEnvironment(), v8::internal::Isolate::CreateMessage(), v8::internal::Genesis::CreateNewGlobals(), v8::internal::CreateStructMap(), v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareEvalHelper(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::JSArrayBuffer::Detach(), v8::internal::Map::EquivalentToForTransition(), v8::internal::wasm::ErrorStringForCodegen(), v8::internal::anonymous_namespace{runtime-literals.cc}::AllocationSiteCreationContext::ExitScope(), v8::internal::KeyAccumulator::FilterForEnumerableProperties(), v8::HeapProfiler::FindObjectById(), v8::Isolate::GetEnteredOrMicrotaskContext(), v8::internal::wasm::GetExports(), v8::internal::wasm::GetImports(), v8::internal::Runtime::GetObjectProperty(), v8::internal::wasm::WasmEngine::GetOrCreateScript(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::internal::BoyerMooreLookahead::GetSkipTable(), v8::internal::HandleApiCallAsFunctionOrConstructorDelegate(), v8::internal::Parser::HandleDebugMagicComments(), v8::internal::V8FileLogger::ICEvent(), v8::internal::SwissNameDictionary::IndexIterator::IndexIterator(), v8::internal::anonymous_namespace{runtime-classes.cc}::InitClassConstructor(), v8::internal::anonymous_namespace{js-locale.cc}::InsertOptionsIntoLocale(), v8::internal::Debug::InstallCoverageInfo(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::anonymous_namespace{api-natives.cc}::InstantiateObject(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::compiler::JsonPrintFunctionSource(), v8::internal::LoadIC::Load(), v8::internal::KeyedLoadIC::LoadName(), v8::internal::Isolate::LocalsBlockListCacheSet(), v8::internal::Compiler::LogFunctionCompilation(), v8::internal::wasm::InstanceBuilder::LookupImport(), v8::internal::V8FileLogger::MapEvent(), v8::internal::WasmTagObject::New(), v8::internal::WasmGlobalObject::New(), v8::internal::WasmTableObject::New(), v8::NewContext(), v8::internal::Factory::NewDebugEvaluateContext(), v8::internal::Factory::NewError(), v8::internal::Factory::NewJSMessageObject(), v8::internal::Factory::NewJSSharedStruct(), v8::internal::Factory::NewObjectTemplateInfo(), v8::Context::NewRemoteContext(), v8::internal::Bootstrapper::NewRemoteContext(), v8::internal::Map::Normalize(), v8::ObjectSetAccessor(), v8::internal::Debug::OnDebugBreak(), v8::internal::parsing::ParseAny(), v8::internal::parsing::ParseFunction(), v8::internal::Debug::PerformSideEffectCheckForAccessor(), v8::internal::Debug::PerformSideEffectCheckForInterceptor(), v8::internal::JSObject::PreventExtensionsWithTransition(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::PerfettoLogger::RegExpCodeCreateEvent(), v8::internal::JSDateTimeFormat::ResolvedOptions(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNew(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewDefault(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewFixed(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayNew(), v8::internal::JsonStringifier::SerializeJSReceiverSlow(), v8::Object::SetAccessorProperty(), v8::internal::SnapshotCreatorImpl::SetDefaultContext(), v8::Context::SetEmbedderData(), v8::internal::anonymous_namespace{elements.cc}::FastNonextensibleObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl(), v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl(), v8::AsyncHooks::ShellPromiseHook(), v8::Context::SlowGetAlignedPointerFromEmbedderData(), v8::Context::SlowGetEmbedderData(), v8::internal::SerializedCodeData::SourceHash(), v8::internal::SourcePositionInfo::SourcePositionInfo(), v8::internal::KeyedStoreIC::Store(), v8::internal::KeyedStoreIC::StoreElementPolymorphicHandlers(), v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::StoreFunctionBlocklists(), v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt(), v8::internal::wasm::WasmInterpreterRuntime::StoreWasmRef(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), v8::internal::IC::TraceIC(), v8::internal::TranslatedState::UpdateFromPreviouslyMaterializedObjects(), v8::internal::NumberDictionary::UpdateMaxNumberKey(), v8::internal::WasmMemoryObject::UseInInstance(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
New()
template<typename T >
static DirectHandle<T> v8::internal::DirectHandle< T >::New (Tagged< T > object, Isolate * isolate) [inline], [static]
Definition at line 665 of file handles.h.
                                                                           {
    return DirectHandle(Handle<T>::New(object, isolate));
  }
Referenced by v8::internal::wasm::WasmEngine::GetOrCreateScript(), and v8::internal::IncrementalStringBuilder::IncrementalStringBuilder().
null()
template<typename T >
static const DirectHandle v8::internal::DirectHandle< T >::null () [inline], [static]
Definition at line 662 of file handles.h.
                                             {
    return DirectHandle(Handle<T>::null());
  }
Referenced by v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder(), and v8::internal::MaybeHandle< T >::ToHandle().
operator*()
template<typename T >
Tagged<T> v8::internal::DirectHandle< T >::operator* () const [inline]
Definition at line 693 of file handles.h.
{ return *handle_; }
operator->()
template<typename T >
IndirectHandle<T> v8::internal::DirectHandle< T >::operator-> () const [inline]
Definition at line 692 of file handles.h.
{ return handle_; }
repr()
template<typename T >
ValueHelper::InternalRepresentationType v8::internal::DirectHandle< T >::repr () const [inline]
Definition at line 697 of file handles.h.
                                                               {
    return handle_.repr();
  }
SetValue()
template<typename T >
void v8::internal::DirectHandle< T >::SetValue (Tagged< T > new_value) [inline]
Definition at line 708 of file handles.h.
                                               {
    handle_.PatchValue(new_value);
  }
Referenced by v8::internal::FastGetOwnValuesOrEntries().
Friends And Related Function Documentation
DirectHandle
template<typename T >
template<typename >
friend class DirectHandle [friend]
Definition at line 731 of file handles.h.
DirectHandleUnchecked< T >
template<typename T >
friend class DirectHandleUnchecked< T > [friend]
Definition at line 733 of file handles.h.
HandleBase
template<typename T >
friend class HandleBase [friend]
Definition at line 729 of file handles.h.
indirect_handle [1/4]
template<typename T >
template<typename U >
IndirectHandle<U> indirect_handle (DirectHandle< U >) [friend]
indirect_handle [2/4]
template<typename T >
template<typename U >
IndirectHandle<U> indirect_handle (DirectHandle< U > , Isolate *) [friend]
indirect_handle [3/4]
template<typename T >
template<typename U >
IndirectHandle<U> indirect_handle (DirectHandle< U > , LocalHeap *) [friend]
indirect_handle [4/4]
template<typename T >
template<typename U >
IndirectHandle<U> indirect_handle (DirectHandle< U > , LocalIsolate *) [friend]
MaybeDirectHandle
template<typename T >
template<typename >
friend class MaybeDirectHandle [friend]
Definition at line 733 of file handles.h.
UncheckedCast
template<typename T >
template<typename To , typename From >
DirectHandle<To> UncheckedCast (DirectHandle< From > value) [friend]
Definition at line 131 of file handles-inl.h.
                                                                {
  return DirectHandle<To>(UncheckedCast<To>(value.handle_));
}
Member Data Documentation
__pad0__
template<typename T >
T v8::internal::DirectHandle< T >::__pad0__
Definition at line 680 of file handles.h.
handle_
template<typename T >
IndirectHandle<T> v8::internal::DirectHandle< T >::handle_ [private]
Definition at line 754 of file handles.h.
Referenced by v8::internal::HandleBase::is_identical_to().
T
template<typename T >
T v8::internal::DirectHandle< T >::T
Definition at line 685 of file handles.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/globals.h
/mnt/V8SourceCode/src/handles/handles.h