v8::internal::CppHeap Class Reference
#include <cpp-heap.h>
Classes
class MetricRecorderAdapter
Public Types
enum GarbageCollectionFlagValues : uint8_t { kNoFlags = 0
, kReduceMemory = 1 << 1
, kForced = 1 << 2
 }
using GarbageCollectionFlags = base::Flags< GarbageCollectionFlagValues >
using StackState = cppgc::internal::StackState
using CollectionType = cppgc::internal::CollectionType
Public Member Functions
CppHeap (v8::Platform *, const std::vector< std::unique_ptr< cppgc::CustomSpaceBase >> &, cppgc::Heap::MarkingType, cppgc::Heap::SweepingType)
~CppHeap () final
CppHeap (const CppHeap &)=delete
CppHeap & operator= (const CppHeap &)=delete
HeapBase & AsBase ()
const HeapBase & AsBase () const
void AttachIsolate (Isolate *isolate)
void StartDetachingIsolate ()
void DetachIsolate ()
void Terminate ()
void CollectCustomSpaceStatisticsAtLastGC (std::vector< cppgc::CustomSpaceIndex >, std::unique_ptr< CustomSpaceStatisticsReceiver >)
void FinishSweepingIfRunning ()
void FinishAtomicSweepingIfRunning ()
void FinishSweepingIfOutOfWork ()
void InitializeMarking (CollectionType, std::shared_ptr<::heap::base::IncrementalMarkingSchedule > schedule={}, GarbageCollectionFlags=GarbageCollectionFlagValues::kNoFlags)
void StartMarking ()
bool AdvanceMarking (v8::base::TimeDelta max_duration, size_t marked_bytes_limit)
bool IsMarkingDone () const
size_t last_bytes_marked () const
void ProcessCrossThreadWeakness ()
void FinishMarkingAndProcessWeakness ()
void CompactAndSweep ()
void EnterFinalPause (cppgc::EmbedderStackState stack_state)
void EnterProcessGlobalAtomicPause ()
bool FinishConcurrentMarkingIfNeeded ()
void ReEnableConcurrentMarking ()
void WriteBarrier (void *)
bool ShouldFinalizeIncrementalMarking () const
void AllocatedObjectSizeIncreased (size_t) final
void AllocatedObjectSizeDecreased (size_t) final
void ResetAllocatedObjectSize (size_t) final
MetricRecorderAdapter * GetMetricRecorder () const
Isolate * isolate () const
size_t used_size () const
size_t allocated_size () const
::heap::base::Stack * stack () final
std::unique_ptr< CppMarkingState > CreateCppMarkingState ()
std::unique_ptr< CppMarkingState > CreateCppMarkingStateForMutatorThread ()
void CollectGarbage (cppgc::internal::GCConfig) override
std::optional< cppgc::EmbedderStackState > overridden_stack_state () const override
void set_override_stack_state (cppgc::EmbedderStackState state) override
void clear_overridden_stack_state () override
void StartIncrementalGarbageCollection (cppgc::internal::GCConfig) override
size_t epoch () const override
void RememberCrossHeapReferenceIfNeeded (v8::internal::Tagged< v8::internal::CppHeapPointerWrapperObjectT > host_obj, void *value)
template<typename F >
void VisitCrossHeapRememberedSetIfNeeded (F f)
void ResetCrossHeapRememberedSet ()
void EnableDetachedGarbageCollectionsForTesting ()
void CollectGarbageForTesting (CollectionType, StackState)
void UpdateGCCapabilitiesFromFlagsForTesting ()
bool CurrentThreadIsHeapThread () const final
Static Public Member Functions
static void InitializeOncePerProcess ()
static CppHeap * From (v8::CppHeap *heap)
static const CppHeap * From (const v8::CppHeap *heap)
Private Member Functions
void UpdateGCCapabilitiesFromFlags ()
void FinalizeIncrementalGarbageCollectionIfNeeded (cppgc::Heap::StackState) final
void ReportBufferedAllocationSizeIfPossible ()
void StartIncrementalGarbageCollectionForTesting () final
void FinalizeIncrementalGarbageCollectionForTesting (cppgc::EmbedderStackState) final
MarkingType SelectMarkingType () const
SweepingType SelectSweepingType () const
bool TracingInitialized () const
bool IsGCForbidden () const override
bool IsGCAllowed () const override
bool IsDetachedGCAllowed () const
Heap * heap () const
Private Attributes
Isolate * isolate_ = nullptr
Heap * heap_ = nullptr
bool marking_done_ = true
std::optional< CollectionType > collection_type_
GarbageCollectionFlags current_gc_flags_
std::unique_ptr< MinorGCHeapGrowing > minor_gc_heap_growing_
CrossHeapRememberedSet cross_heap_remembered_set_
std::unique_ptr< cppgc::internal::Sweeper::SweepingOnMutatorThreadObserver > sweeping_on_mutator_thread_observer_
int64_t buffered_allocated_bytes_ = 0
bool in_detached_testing_mode_ = false
bool force_incremental_marking_for_testing_ = false
bool is_in_v8_marking_step_ = false
std::atomic< size_t > used_size_ {0}
size_t allocated_size_ = 0
size_t allocated_size_limit_for_check_ = 0
std::optional< cppgc::EmbedderStackState > detached_override_stack_state_
std::unique_ptr< v8::internal::EmbedderStackStateScope > override_stack_state_scope_
bool already_terminated_ = false
bool is_detached_ = true
Friends
class MetricRecorderAdapter
Additional Inherited Members
Detailed Description
Definition at line 40 of file cpp-heap.h.
Member Typedef Documentation
CollectionType
using v8::internal::CppHeap::CollectionType = cppgc::internal::CollectionType
Definition at line 54 of file cpp-heap.h.
GarbageCollectionFlags
using v8::internal::CppHeap::GarbageCollectionFlags = base::Flags<GarbageCollectionFlagValues>
Definition at line 52 of file cpp-heap.h.
StackState
using v8::internal::CppHeap::StackState = cppgc::internal::StackState
Definition at line 53 of file cpp-heap.h.
Member Enumeration Documentation
GarbageCollectionFlagValues
enum v8::internal::CppHeap::GarbageCollectionFlagValues : uint8_t
Enumerator
kNoFlags
kReduceMemory
kForced
Definition at line 46 of file cpp-heap.h.
                                   : uint8_t {
    kNoFlags = 0,
    kReduceMemory = 1 << 1,
    kForced = 1 << 2,
  };
Constructor & Destructor Documentation
CppHeap() [1/2]
v8::internal::CppHeap::CppHeap (v8::Platform * platform, const std::vector< std::unique_ptr< cppgc::CustomSpaceBase >> & custom_spaces, cppgc::Heap::MarkingType marking_support, cppgc::Heap::SweepingType sweeping_support)
Definition at line 493 of file cpp-heap.cc.
    : cppgc::internal::HeapBase(
          std::make_shared<CppgcPlatformAdapter>(platform), custom_spaces,
          cppgc::internal::HeapBase::StackSupport::
              kSupportsConservativeStackScan,
          marking_support, sweeping_support, *this),
      minor_gc_heap_growing_(
          std::make_unique<MinorGCHeapGrowing>(*stats_collector())),
      cross_heap_remembered_set_(*this) {
  // Enter no GC scope. `AttachIsolate()` removes this and allows triggering
  // garbage collections.
  no_gc_scope_++;
  stats_collector()->RegisterObserver(this);
#ifdef V8_ENABLE_ALLOCATION_TIMEOUT
  object_allocator().UpdateAllocationTimeout();
#endif // V8_ENABLE_ALLOCATION_TIMEOUT
}
References cppgc::internal::HeapBase::no_gc_scope_, cppgc::internal::HeapBase::object_allocator(), cppgc::internal::StatsCollector::RegisterObserver(), and cppgc::internal::HeapBase::stats_collector().
 CppHeap()
v8::internal::CppHeap::~CppHeap () [final], [virtual]
Reimplemented from v8::CppHeap.
Definition at line 515 of file cpp-heap.cc.
                  {
  Terminate();
}
References Terminate().
CppHeap() [2/2]
v8::internal::CppHeap::CppHeap (const CppHeap &) [delete]
Member Function Documentation
AdvanceMarking()
bool v8::internal::CppHeap::AdvanceMarking (v8::base::TimeDelta max_duration, size_t marked_bytes_limit)
Definition at line 852 of file cpp-heap.cc.
                                                        {
  if (!TracingInitialized()) {
    return true;
  }
  is_in_v8_marking_step_ = true;
  cppgc::internal::StatsCollector::EnabledScope stats_scope(
      stats_collector(),
      in_atomic_pause_ ? cppgc::internal::StatsCollector::kAtomicMark
                       : cppgc::internal::StatsCollector::kIncrementalMark);
  DCHECK_NOT_NULL(marker_);
  if (in_atomic_pause_) {
    marker_->NotifyConcurrentMarkingOfWorkIfNeeded(
        cppgc::TaskPriority::kUserBlocking);
  }
  marking_done_ =
      marker_->AdvanceMarkingWithLimits(max_duration, marked_bytes_limit);
  DCHECK_IMPLIES(in_atomic_pause_, marking_done_);
  is_in_v8_marking_step_ = false;
  return marking_done_;
}
References DCHECK_IMPLIES, DCHECK_NOT_NULL, cppgc::internal::HeapBase::in_atomic_pause_, is_in_v8_marking_step_, v8::kUserBlocking, cppgc::internal::HeapBase::marker_, marking_done_, cppgc::internal::HeapBase::stats_collector(), and TracingInitialized().
Referenced by CollectGarbageForTesting().
allocated_size()
size_t v8::internal::CppHeap::allocated_size () const [inline]
Definition at line 173 of file cpp-heap.h.
{ return allocated_size_; }
Referenced by v8::internal::Heap::EmbedderAllocationCounter().
AllocatedObjectSizeDecreased()
void v8::internal::CppHeap::AllocatedObjectSizeDecreased (size_t bytes) [final], [virtual]
Reimplemented from cppgc::internal::StatsCollector::AllocationObserver.
Definition at line 1039 of file cpp-heap.cc.
                                                       {
  buffered_allocated_bytes_ -= static_cast<int64_t>(bytes);
  ReportBufferedAllocationSizeIfPossible();
}
References buffered_allocated_bytes_, and ReportBufferedAllocationSizeIfPossible().
AllocatedObjectSizeIncreased()
void v8::internal::CppHeap::AllocatedObjectSizeIncreased (size_t bytes) [final], [virtual]
Reimplemented from cppgc::internal::StatsCollector::AllocationObserver.
Definition at line 1034 of file cpp-heap.cc.
                                                       {
  buffered_allocated_bytes_ += static_cast<int64_t>(bytes);
  ReportBufferedAllocationSizeIfPossible();
}
References buffered_allocated_bytes_, and ReportBufferedAllocationSizeIfPossible().
AsBase() [1/2]
HeapBase& v8::internal::CppHeap::AsBase () [inline]
Definition at line 118 of file cpp-heap.h.
{ return *this; }
Referenced by CollectCustomSpaceStatisticsAtLastGC(), v8::CppHeap::CollectStatistics(), CreateCppMarkingState(), and InitializeMarking().
AsBase() [2/2]
const HeapBase& v8::internal::CppHeap::AsBase () const [inline]
Definition at line 119 of file cpp-heap.h.
{ return *this; }
AttachIsolate()
void v8::internal::CppHeap::AttachIsolate (Isolate * isolate)
Definition at line 601 of file cpp-heap.cc.
                                            {
  // Since a new isolate is attached, we are also allowed to detach it again.
  is_detached_ = false;
  CHECK(!in_detached_testing_mode_);
  CHECK_NULL(isolate_);
  isolate_ = isolate;
  heap_ = isolate->heap();
  stack_->SetScanSimulatorCallback(
      Isolate::IterateRegistersAndStackOfSimulator);
  static_cast<CppgcPlatformAdapter*>(platform())
      ->SetIsolate(reinterpret_cast<v8::Isolate*>(isolate_));
  if (auto* heap_profiler = heap()->heap_profiler()) {
    heap_profiler->SetInternalBuildEmbedderGraphCallback(&CppGraphBuilder::Run,
                                                         this);
    heap_profiler->set_native_move_listener(
        std::make_unique<MoveListenerImpl>(heap_profiler, this));
  }
  SetMetricRecorder(std::make_unique<MetricRecorderAdapter>(*this));
  oom_handler().SetCustomHandler(&FatalOutOfMemoryHandlerImpl);
  UpdateGCCapabilitiesFromFlags();
  sweeping_on_mutator_thread_observer_ =
      std::make_unique<SweepingOnMutatorThreadForGlobalHandlesObserver>(
          *this, *isolate_->traced_handles());
  no_gc_scope_--;
  // Propagate overridden stack state to the attached heap, if necessary.
  // TODO(b/326503098): This should not be required, to be removed when the
  // issue is resolved.
  CHECK(!override_stack_state_scope_);
  if (detached_override_stack_state_) {
    override_stack_state_scope_ = std::make_unique<EmbedderStackStateScope>(
        heap_, EmbedderStackStateOrigin::kExplicitInvocation,
        detached_override_stack_state_.value());
    detached_override_stack_state_.reset();
  }
}
References CHECK, CHECK_NULL, detached_override_stack_state_, v8::internal::anonymous_namespace{cpp-heap.cc}::FatalOutOfMemoryHandlerImpl(), v8::internal::Isolate::heap(), heap(), heap_, v8::internal::Heap::heap_profiler(), in_detached_testing_mode_, is_detached_, isolate(), isolate_, v8::internal::Isolate::IterateRegistersAndStackOfSimulator(), v8::internal::kExplicitInvocation, cppgc::internal::HeapBase::no_gc_scope_, cppgc::internal::HeapBase::oom_handler(), override_stack_state_scope_, cppgc::internal::HeapBase::platform(), v8::internal::CppGraphBuilder::Run(), cppgc::internal::FatalOutOfMemoryHandler::SetCustomHandler(), cppgc::internal::HeapBase::SetMetricRecorder(), cppgc::internal::HeapBase::stack_, sweeping_on_mutator_thread_observer_, v8::internal::Isolate::traced_handles(), and UpdateGCCapabilitiesFromFlags().
Referenced by v8::internal::Heap::AttachCppHeap().
clear_overridden_stack_state()
void v8::internal::CppHeap::clear_overridden_stack_state () [override], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 1307 of file cpp-heap.cc.
                                           {
  if (heap_) {
    CHECK(!detached_override_stack_state_);
    CHECK(override_stack_state_scope_);
    override_stack_state_scope_.reset();
  } else {
    CHECK(detached_override_stack_state_);
    CHECK(!override_stack_state_scope_);
    detached_override_stack_state_.reset();
  }
}
References CHECK, detached_override_stack_state_, heap_, and override_stack_state_scope_.
CollectCustomSpaceStatisticsAtLastGC()
void v8::internal::CppHeap::CollectCustomSpaceStatisticsAtLastGC (std::vector< cppgc::CustomSpaceIndex > custom_spaces, std::unique_ptr< CustomSpaceStatisticsReceiver > receiver)
Definition at line 1220 of file cpp-heap.cc.
                                                           {
  if (sweeper().IsSweepingInProgress()) {
    platform()->GetForegroundTaskRunner()->PostDelayedTask(
        std::make_unique<CollectCustomSpaceStatisticsAtLastGCTask>(
            AsBase(), std::move(custom_spaces), std::move(receiver)),
        CollectCustomSpaceStatisticsAtLastGCTask::kTaskDelayMs.InSecondsF());
    return;
  }
  ReportCustomSpaceStatistics(raw_heap(), std::move(custom_spaces),
                              std::move(receiver));
}
References AsBase(), cppgc::Platform::GetForegroundTaskRunner(), cppgc::internal::HeapBase::platform(), cppgc::internal::HeapBase::raw_heap(), v8::internal::anonymous_namespace{cpp-heap.cc}::ReportCustomSpaceStatistics(), and cppgc::internal::HeapBase::sweeper().
Referenced by v8::CppHeap::CollectCustomSpaceStatisticsAtLastGC().
CollectGarbage()
void v8::internal::CppHeap::CollectGarbage (cppgc::internal::GCConfig config) [override], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 1273 of file cpp-heap.cc.
                                                         {
  if (!IsGCAllowed()) {
    return;
  }
  // TODO(mlippautz): Respect full config.
  const auto flags =
      (config.free_memory_handling ==
       cppgc::internal::GCConfig::FreeMemoryHandling::kDiscardWherePossible)
          ? GCFlag::kReduceMemoryFootprint
          : GCFlag::kNoFlags;
  isolate_->heap()->CollectAllGarbage(
      flags, GarbageCollectionReason::kCppHeapAllocationFailure);
  DCHECK_IMPLIES(
      config.sweeping_type == cppgc::internal::GCConfig::SweepingType::kAtomic,
      !sweeper_.IsSweepingInProgress());
}
References v8::internal::Heap::CollectAllGarbage(), DCHECK_IMPLIES, v8::internal::flags, cppgc::internal::GCConfig::free_memory_handling, v8::internal::Isolate::heap(), IsGCAllowed(), isolate_, cppgc::internal::Sweeper::IsSweepingInProgress(), cppgc::Heap::kAtomic, v8::internal::kCppHeapAllocationFailure, v8::internal::kNoFlags, v8::internal::kReduceMemoryFootprint, cppgc::internal::HeapBase::sweeper_, and cppgc::internal::GCConfig::sweeping_type.
CollectGarbageForTesting()
void v8::internal::CppHeap::CollectGarbageForTesting (CollectionType collection_type, StackState stack_state)
Definition at line 1090 of file cpp-heap.cc.
                                                               {
  if (!IsDetachedGCAllowed()) {
    return;
  }
  // Finish sweeping in case it is still running.
  sweeper().FinishIfRunning();
  if (isolate_) {
    reinterpret_cast<v8::Isolate*>(isolate_)
        ->RequestGarbageCollectionForTesting(
            v8::Isolate::kFullGarbageCollection, stack_state);
    return;
  }
  stack()->SetMarkerIfNeededAndCallback([this, collection_type, stack_state]() {
    // Perform an atomic GC, with starting incremental/concurrent marking and
    // immediately finalizing the garbage collection.
    if (!IsMarking()) {
      InitializeMarking(collection_type, nullptr,
                        GarbageCollectionFlagValues::kForced);
      StartMarking();
    }
    EnterFinalPause(stack_state);
    EnterProcessGlobalAtomicPause();
    CHECK(AdvanceMarking(v8::base::TimeDelta::Max(), SIZE_MAX));
    if (FinishConcurrentMarkingIfNeeded()) {
      CHECK(AdvanceMarking(v8::base::TimeDelta::Max(), SIZE_MAX));
    }
    FinishMarkingAndProcessWeakness();
    CompactAndSweep();
    FinishAtomicSweepingIfRunning();
  });
}
References AdvanceMarking(), CHECK, CompactAndSweep(), EnterFinalPause(), EnterProcessGlobalAtomicPause(), FinishAtomicSweepingIfRunning(), FinishConcurrentMarkingIfNeeded(), cppgc::internal::Sweeper::FinishIfRunning(), FinishMarkingAndProcessWeakness(), InitializeMarking(), IsDetachedGCAllowed(), cppgc::internal::HeapBase::IsMarking(), isolate_, v8::Isolate::kFullGarbageCollection, v8::base::TimeDelta::Max(), heap::base::Stack::SetMarkerIfNeededAndCallback(), stack(), StartMarking(), and cppgc::internal::HeapBase::sweeper().
Referenced by v8::CppHeap::CollectGarbageForTesting(), v8::CppHeap::CollectGarbageInYoungGenerationForTesting(), and FinalizeIncrementalGarbageCollectionForTesting().
CompactAndSweep()
void v8::internal::CppHeap::CompactAndSweep ()
Definition at line 982 of file cpp-heap.cc.
                              {
  if (!TracingInitialized()) {
    return;
  }
  // The allocated bytes counter in v8 was reset to the current marked bytes, so
  // any pending allocated bytes updates should be discarded.
  buffered_allocated_bytes_ = 0;
  const size_t bytes_allocated_in_prefinalizers = ExecutePreFinalizers();
#if CPPGC_VERIFY_HEAP
  UnifiedHeapMarkingVerifier verifier(*this, *collection_type_);
  verifier.Run(stack_state_of_prev_gc(),
               stats_collector()->marked_bytes_on_current_cycle() +
                   bytes_allocated_in_prefinalizers);
#endif // CPPGC_VERIFY_HEAP
  USE(bytes_allocated_in_prefinalizers);
#if defined(CPPGC_YOUNG_GENERATION)
  ResetRememberedSet();
  // We can reset the remembered set on each GC because surviving Oilpan objects
  // are immediately considered old.
  ResetCrossHeapRememberedSet();
#endif // defined(CPPGC_YOUNG_GENERATION)
  {
    cppgc::subtle::NoGarbageCollectionScope no_gc(*this);
    cppgc::internal::SweepingConfig::CompactableSpaceHandling
        compactable_space_handling;
    {
      std::optional<SweepingOnMutatorThreadForGlobalHandlesScope>
          global_handles_scope;
      if (isolate_) {
        global_handles_scope.emplace(*isolate_->traced_handles());
      }
      compactable_space_handling = compactor_.CompactSpacesIfEnabled();
    }
    const cppgc::internal::SweepingConfig sweeping_config{
        SelectSweepingType(), compactable_space_handling,
        ShouldReduceMemory(current_gc_flags_)
            ? cppgc::internal::SweepingConfig::FreeMemoryHandling::
                  kDiscardWherePossible
            : cppgc::internal::SweepingConfig::FreeMemoryHandling::
                  kDoNotDiscard};
    DCHECK_IMPLIES(!isolate_,
                   SweepingType::kAtomic == sweeping_config.sweeping_type);
    sweeper().Start(sweeping_config);
  }
  in_atomic_pause_ = false;
  collection_type_.reset();
}
References buffered_allocated_bytes_, collection_type_, cppgc::internal::HeapBase::compactor_, cppgc::internal::Compactor::CompactSpacesIfEnabled(), current_gc_flags_, DCHECK_IMPLIES, cppgc::internal::HeapBase::ExecutePreFinalizers(), cppgc::internal::HeapBase::in_atomic_pause_, isolate_, cppgc::Heap::kAtomic, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, ResetCrossHeapRememberedSet(), cppgc::internal::MarkingVerifierBase::Run(), SelectSweepingType(), v8::internal::anonymous_namespace{cpp-heap.cc}::ShouldReduceMemory(), cppgc::internal::HeapBase::stack_state_of_prev_gc(), cppgc::internal::Sweeper::Start(), cppgc::internal::HeapBase::stats_collector(), cppgc::internal::HeapBase::sweeper(), v8::internal::Isolate::traced_handles(), TracingInitialized(), and USE.
Referenced by CollectGarbageForTesting(), and v8::internal::Heap::PerformGarbageCollection().
CreateCppMarkingState()
std::unique_ptr< CppMarkingState > v8::internal::CppHeap::CreateCppMarkingState ()
Definition at line 1257 of file cpp-heap.cc.
                                                              {
  if (!TracingInitialized()) return {};
  DCHECK(IsMarking());
  return std::make_unique<CppMarkingState>(
      std::make_unique<cppgc::internal::MarkingStateBase>(
          AsBase(), marker()->To<UnifiedHeapMarker>().GetMarkingWorklists()));
}
References AsBase(), v8::internal::DCHECK(), cppgc::internal::HeapBase::IsMarking(), cppgc::internal::HeapBase::marker(), and TracingInitialized().
CreateCppMarkingStateForMutatorThread()
std::unique_ptr< CppMarkingState > v8::internal::CppHeap::CreateCppMarkingStateForMutatorThread ()
Definition at line 1266 of file cpp-heap.cc.
                                               {
  if (!TracingInitialized()) return {};
  DCHECK(IsMarking());
  return std::make_unique<CppMarkingState>(
      marker()->To<UnifiedHeapMarker>().GetMutatorMarkingState());
}
References v8::internal::DCHECK(), cppgc::internal::HeapBase::IsMarking(), cppgc::internal::HeapBase::marker(), and TracingInitialized().
CurrentThreadIsHeapThread()
bool v8::internal::CppHeap::CurrentThreadIsHeapThread () const [final], [virtual]
Reimplemented from cppgc::internal::HeapBase.
Definition at line 1365 of file cpp-heap.cc.
                                              {
  if (!is_detached_ && isolate_ &&
      V8_UNLIKELY(isolate_->was_locker_ever_used())) {
    // If v8::Locker has been used, we only check if the isolate is now locked
    // by the current thread.
    return isolate_->thread_manager()->IsLockedByCurrentThread();
  }
  return HeapBase::CurrentThreadIsHeapThread();
}
References cppgc::internal::HeapBase::CurrentThreadIsHeapThread(), is_detached_, v8::internal::ThreadManager::IsLockedByCurrentThread(), isolate_, v8::internal::Isolate::thread_manager(), V8_UNLIKELY, and v8::internal::Isolate::was_locker_ever_used().
DetachIsolate()
void v8::internal::CppHeap::DetachIsolate ()
Definition at line 657 of file cpp-heap.cc.
                            {
  sweeping_on_mutator_thread_observer_.reset();
  if (auto* heap_profiler = heap()->heap_profiler()) {
    heap_profiler->SetInternalBuildEmbedderGraphCallback(nullptr, nullptr);
    heap_profiler->set_native_move_listener(nullptr);
  }
  SetMetricRecorder(nullptr);
  // Propagate overridden stack state from the attached heap, if necessary.
  // TODO(b/326503098): This should not be required, to be removed when the
  // issue is resolved.
  CHECK(!detached_override_stack_state_);
  if (override_stack_state_scope_) {
    detached_override_stack_state_ = heap_->overridden_stack_state();
    override_stack_state_scope_.reset();
  }
  isolate_ = nullptr;
  heap_ = nullptr;
  // Any future garbage collections will ignore the V8->C++ references.
  oom_handler().SetCustomHandler(nullptr);
  // Enter no GC scope.
  no_gc_scope_++;
}
References CHECK, detached_override_stack_state_, heap(), heap_, isolate_, cppgc::internal::HeapBase::no_gc_scope_, cppgc::internal::HeapBase::oom_handler(), v8::internal::Heap::overridden_stack_state(), override_stack_state_scope_, cppgc::internal::FatalOutOfMemoryHandler::SetCustomHandler(), cppgc::internal::HeapBase::SetMetricRecorder(), and sweeping_on_mutator_thread_observer_.
Referenced by v8::internal::Heap::TearDown().
EnableDetachedGarbageCollectionsForTesting()
void v8::internal::CppHeap::EnableDetachedGarbageCollectionsForTesting ()
Definition at line 1126 of file cpp-heap.cc.
                                                         {
  CHECK(!in_detached_testing_mode_);
  CHECK_NULL(isolate_);
  no_gc_scope_--;
  in_detached_testing_mode_ = true;
  static_cast<CppgcPlatformAdapter*>(platform())
      ->EnableDetachedModeForTesting();
}
References CHECK, CHECK_NULL, in_detached_testing_mode_, isolate_, cppgc::internal::HeapBase::no_gc_scope_, and cppgc::internal::HeapBase::platform().
Referenced by v8::CppHeap::EnableDetachedGarbageCollectionsForTesting().
EnterFinalPause()
void v8::internal::CppHeap::EnterFinalPause (cppgc::EmbedderStackState stack_state)
Definition at line 890 of file cpp-heap.cc.
                                                                 {
  CHECK(!IsGCForbidden());
  // Enter atomic pause even if tracing is not initialized. This is needed to
  // make sure that we always enable young generation from the atomic pause.
  in_atomic_pause_ = true;
  if (!TracingInitialized()) return;
  auto& marker = marker_->To<UnifiedHeapMarker>();
  // Scan global handles conservatively in case we are attached to an Isolate.
  // TODO(1029379): Support global handle marking visitors with minor GC.
  if (isolate_) {
    auto& heap = *isolate()->heap();
    marker.conservative_visitor().SetConservativeTracedHandlesMarkingVisitor(
        std::make_unique<ConservativeTracedHandlesMarkingVisitor>(
            heap, *GetV8MarkingWorklists(isolate_, *collection_type_),
            *collection_type_));
  }
  marker.EnterAtomicPause(stack_state);
  compactor_.CancelIfShouldNotCompact(MarkingType::kAtomic, stack_state);
}
References cppgc::internal::Compactor::CancelIfShouldNotCompact(), CHECK, collection_type_, cppgc::internal::HeapBase::compactor_, cppgc::internal::MarkerBase::conservative_visitor(), cppgc::internal::MarkerBase::EnterAtomicPause(), v8::internal::anonymous_namespace{cpp-heap.cc}::GetV8MarkingWorklists(), v8::internal::Isolate::heap(), cppgc::internal::HeapBase::in_atomic_pause_, IsGCForbidden(), isolate(), isolate_, cppgc::Heap::kAtomic, cppgc::internal::HeapBase::marker(), cppgc::internal::HeapBase::marker_, and TracingInitialized().
Referenced by CollectGarbageForTesting().
EnterProcessGlobalAtomicPause()
void v8::internal::CppHeap::EnterProcessGlobalAtomicPause ()
Definition at line 882 of file cpp-heap.cc.
                                            {
  if (!TracingInitialized()) {
    return;
  }
  DCHECK(in_atomic_pause_);
  marker_->To<UnifiedHeapMarker>().EnterProcessGlobalAtomicPause();
}
References v8::internal::DCHECK(), cppgc::internal::HeapBase::in_atomic_pause_, cppgc::internal::HeapBase::marker_, and TracingInitialized().
Referenced by CollectGarbageForTesting().
epoch()
size_t v8::internal::CppHeap::epoch () const [override], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 1323 of file cpp-heap.cc.
{ UNIMPLEMENTED(); }
References v8::internal::UNIMPLEMENTED().
FinalizeIncrementalGarbageCollectionForTesting()
void v8::internal::CppHeap::FinalizeIncrementalGarbageCollectionForTesting (cppgc::EmbedderStackState stack_state) [final], [private], [virtual]
Implements cppgc::internal::HeapBase.
Definition at line 1146 of file cpp-heap.cc.
                                         {
  DCHECK(!in_no_gc_scope());
  DCHECK_NULL(isolate_);
  DCHECK(IsMarking());
  if (IsMarking()) {
    CollectGarbageForTesting(CollectionType::kMajor, stack_state);
  }
  sweeper_.FinishIfRunning();
}
References CollectGarbageForTesting(), v8::internal::DCHECK(), DCHECK_NULL, cppgc::internal::Sweeper::FinishIfRunning(), cppgc::internal::HeapBase::in_no_gc_scope(), cppgc::internal::HeapBase::IsMarking(), isolate_, cppgc::internal::kMajor, and cppgc::internal::HeapBase::sweeper_.
FinalizeIncrementalGarbageCollectionIfNeeded()
void v8::internal::CppHeap::FinalizeIncrementalGarbageCollectionIfNeeded (cppgc::Heap::StackState) [inline], [final], [private], [virtual]
Implements cppgc::internal::HeapBase.
Definition at line 211 of file cpp-heap.h.
                                 {
    // For unified heap, CppHeap shouldn't finalize independently (i.e.
    // finalization is not needed). We only mark marking has done so that V8
    // can observe that Oilpan is finished.
    marking_done_ = true;
  }
FinishAtomicSweepingIfRunning()
void v8::internal::CppHeap::FinishAtomicSweepingIfRunning ()
Definition at line 1246 of file cpp-heap.cc.
                                            {
  // Young generation GCs are optional and as such sweeping is not necessarily
  // running.
  if (sweeper_.IsSweepingInProgress() &&
      SelectSweepingType() == SweepingType::kAtomic) {
    FinishSweepingIfRunning();
  }
}
References FinishSweepingIfRunning(), cppgc::internal::Sweeper::IsSweepingInProgress(), cppgc::Heap::kAtomic, SelectSweepingType(), and cppgc::internal::HeapBase::sweeper_.
Referenced by v8::internal::Heap::CollectGarbage(), and CollectGarbageForTesting().
FinishConcurrentMarkingIfNeeded()
bool v8::internal::CppHeap::FinishConcurrentMarkingIfNeeded ()
Definition at line 910 of file cpp-heap.cc.
                                              {
  if (!TracingInitialized()) return true;
  return marker_->JoinConcurrentMarkingIfNeeded();
}
References cppgc::internal::HeapBase::marker_, and TracingInitialized().
Referenced by CollectGarbageForTesting().
FinishMarkingAndProcessWeakness()
void v8::internal::CppHeap::FinishMarkingAndProcessWeakness ()
Definition at line 946 of file cpp-heap.cc.
                                              {
  CHECK(in_atomic_pause_);
  CHECK(marking_done_);
#if defined(CPPGC_YOUNG_GENERATION)
  // Check if the young generation was enabled via flag. We must enable young
  // generation before calling the custom weak callbacks to make sure that the
  // callbacks for old objects are registered in the remembered set.
  if (v8_flags.cppgc_young_generation) {
    EnableGenerationalGC();
  }
#endif // defined(CPPGC_YOUNG_GENERATION)
  if (!TracingInitialized()) {
    in_atomic_pause_ = false;
    return;
  }
  {
    cppgc::subtle::DisallowGarbageCollectionScope disallow_gc_scope(*this);
    marker_->LeaveAtomicPause();
  }
  marker_.reset();
  if (isolate_) {
    // The size is used for recomputing the global heap limit.
    used_size_ = stats_collector_->marked_bytes();
    // Force a check next time increased memory is reported. This allows for
    // setting limits close to actual heap sizes.
    allocated_size_limit_for_check_ = 0;
    RecordEmbedderMarkingSpeed(isolate_->heap()->tracer(),
                               stats_collector_->marking_time(), used_size_);
  }
}
References allocated_size_limit_for_check_, CHECK, v8::internal::Isolate::heap(), cppgc::internal::HeapBase::in_atomic_pause_, isolate_, cppgc::internal::HeapBase::marker_, marking_done_, v8::internal::anonymous_namespace{cpp-heap.cc}::RecordEmbedderMarkingSpeed(), cppgc::internal::HeapBase::stats_collector_, v8::internal::Heap::tracer(), TracingInitialized(), used_size_, and v8::internal::v8_flags.
Referenced by CollectGarbageForTesting().
FinishSweepingIfOutOfWork()
void v8::internal::CppHeap::FinishSweepingIfOutOfWork ()
Definition at line 1255 of file cpp-heap.cc.
{ sweeper_.FinishIfOutOfWork(); }
References cppgc::internal::Sweeper::FinishIfOutOfWork(), and cppgc::internal::HeapBase::sweeper_.
Referenced by v8::internal::Heap::FinishSweepingIfOutOfWork().
FinishSweepingIfRunning()
void v8::internal::CppHeap::FinishSweepingIfRunning ()
Definition at line 1239 of file cpp-heap.cc.
                                      {
  sweeper_.FinishIfRunning();
  if (isolate_ && ShouldReduceMemory(current_gc_flags_)) {
    isolate_->traced_handles()->DeleteEmptyBlocks();
  }
}
References current_gc_flags_, v8::internal::TracedHandles::DeleteEmptyBlocks(), cppgc::internal::Sweeper::FinishIfRunning(), isolate_, v8::internal::anonymous_namespace{cpp-heap.cc}::ShouldReduceMemory(), cppgc::internal::HeapBase::sweeper_, and v8::internal::Isolate::traced_handles().
Referenced by v8::internal::Heap::EnsureSweepingCompleted(), and FinishAtomicSweepingIfRunning().
From() [1/2]
static const CppHeap* v8::internal::CppHeap::From (const v8::CppHeap * heap) [inline], [static]
Definition at line 106 of file cpp-heap.h.
                                                    {
    return static_cast<const CppHeap*>(heap);
  }
References heap().
From() [2/2]
static CppHeap* v8::internal::CppHeap::From (v8::CppHeap * heap) [inline], [static]
Definition at line 103 of file cpp-heap.h.
                                        {
    return static_cast<CppHeap*>(heap);
  }
References heap().
Referenced by v8::internal::Heap::AttachCppHeap(), v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences(), v8::internal::Heap::CollectAllAvailableGarbage(), v8::CppHeap::CollectCustomSpaceStatisticsAtLastGC(), v8::internal::MarkCompactCollector::CollectGarbage(), v8::internal::MinorMarkSweepCollector::CollectGarbage(), v8::internal::Heap::CollectGarbage(), v8::CppHeap::CollectGarbageForTesting(), v8::CppHeap::CollectGarbageInYoungGenerationForTesting(), v8::CppHeap::CollectStatistics(), v8::internal::Heap::CompleteSweepingFull(), v8::internal::Heap::CompleteSweepingYoung(), v8::internal::Heap::ConfigureHeap(), v8::internal::IncrementalMarking::CppHeapStep(), v8::internal::Heap::EmbedderAllocationCounter(), v8::internal::Heap::EmbedderSizeOfObjects(), v8::CppHeap::EnableDetachedGarbageCollectionsForTesting(), v8::internal::Heap::EnsureSweepingCompleted(), v8::internal::MarkCompactCollector::FinishConcurrentMarking(), v8::internal::MinorMarkSweepCollector::FinishConcurrentMarking(), v8::internal::Heap::FinishSweepingIfOutOfWork(), v8::internal::WriteBarrier::GenerationalBarrierForCppHeapPointer(), v8::CppHeap::GetAllocationHandle(), v8::internal::TracedHandles::GetCppHeapIfUnifiedYoungGC(), v8::CppHeap::GetHeapHandle(), v8::internal::IncrementalMarking::GetScheduledBytes(), v8::internal::IsCppHeapMarkingFinished(), v8::internal::WriteBarrier::MarkingSlowFromCppHeapWrappable(), v8::internal::MinorMarkSweepCollector::MarkLiveObjects(), v8::internal::MinorMarkSweepCollector::MarkRootsFromTracedHandles(), v8::internal::MarkCompactCollector::MaybeEnableBackgroundThreadsInCycle(), v8::internal::GCTracer::NotifyFullCppGCCompleted(), v8::internal::GCTracer::NotifyYoungCppGCCompleted(), v8::internal::Heap::PerformGarbageCollection(), v8::internal::MinorMarkSweepCollector::PerformWrapperTracing(), v8::internal::MarkCompactCollector::Prepare(), v8::internal::TracedHandles::ProcessWeakYoungObjects(), v8::internal::GCTracer::ReportFullCycleToRecorder(), v8::internal::GCTracer::ReportIncrementalMarkingStepToRecorder(), v8::internal::GCTracer::ReportYoungCycleToRecorder(), v8::internal::ConcurrentMarking::RunMajor(), v8::internal::IncrementalMarking::ShouldFinalize(), v8::internal::MinorMarkSweepCollector::StartMarking(), v8::internal::MarkCompactCollector::StartMarking(), v8::internal::IncrementalMarking::StartMarkingMajor(), v8::internal::Heap::StartTearDown(), v8::internal::Heap::TearDown(), and v8::CppHeap::Terminate().
GetMetricRecorder()
CppHeap::MetricRecorderAdapter * v8::internal::CppHeap::GetMetricRecorder () const
Definition at line 1234 of file cpp-heap.cc.
                                                               {
  return static_cast<MetricRecorderAdapter*>(
      stats_collector_->GetMetricRecorder());
}
References cppgc::internal::HeapBase::stats_collector_.
Referenced by InitializeMarking(), v8::internal::GCTracer::NotifyFullCppGCCompleted(), v8::internal::GCTracer::NotifyYoungCppGCCompleted(), and v8::internal::GCTracer::ReportIncrementalMarkingStepToRecorder().
heap()
Heap* v8::internal::CppHeap::heap () const [inline], [private]
Definition at line 234 of file cpp-heap.h.
{ return heap_; }
Referenced by AttachIsolate(), DetachIsolate(), and InitializeMarking().
InitializeMarking()
void v8::internal::CppHeap::InitializeMarking (CollectionType collection_type, std::shared_ptr<::heap::base::IncrementalMarkingSchedule > schedule = {}, GarbageCollectionFlags gc_flags = GarbageCollectionFlagValues::kNoFlags)
Definition at line 751 of file cpp-heap.cc.
                                     {
  DCHECK(!collection_type_);
  if (collection_type == CollectionType::kMinor) {
    if (!generational_gc_supported()) return;
    // Notify GC tracer that CppGC started young GC cycle.
    isolate_->heap()->tracer()->NotifyYoungCppGCRunning();
  }
  collection_type_ = collection_type;
  CHECK(!sweeper_.IsSweepingInProgress());
  // Check that previous cycle metrics for the same collection type have been
  // reported.
  if (GetMetricRecorder()) {
    if (collection_type == CollectionType::kMajor)
      DCHECK(!GetMetricRecorder()->FullGCMetricsReportPending());
    else
      DCHECK(!GetMetricRecorder()->YoungGCMetricsReportPending());
  }
#if defined(CPPGC_YOUNG_GENERATION)
  if (generational_gc_supported() &&
      *collection_type_ == CollectionType::kMajor) {
    stats_collector()->NotifyUnmarkingStarted(*collection_type_);
    cppgc::internal::StatsCollector::EnabledScope stats_scope(
        stats_collector(), cppgc::internal::StatsCollector::kUnmark);
    cppgc::internal::SequentialUnmarker unmarker(raw_heap());
  }
#endif // defined(CPPGC_YOUNG_GENERATION)
  if (gc_flags == GarbageCollectionFlagValues::kNoFlags) {
    if (heap()->is_current_gc_forced()) {
      gc_flags |= CppHeap::GarbageCollectionFlagValues::kForced;
    }
    if (heap()->ShouldReduceMemory()) {
      gc_flags |= CppHeap::GarbageCollectionFlagValues::kReduceMemory;
    }
  }
  current_gc_flags_ = gc_flags;
  const cppgc::internal::MarkingConfig marking_config{
      *collection_type_, StackState::kNoHeapPointers, SelectMarkingType(),
      IsForceGC(current_gc_flags_)
          ? cppgc::internal::MarkingConfig::IsForcedGC::kForced
          : cppgc::internal::MarkingConfig::IsForcedGC::kNotForced};
  DCHECK_IMPLIES(!isolate_,
                 (MarkingType::kAtomic == marking_config.marking_type) ||
                     force_incremental_marking_for_testing_);
  if (ShouldReduceMemory(current_gc_flags_)) {
    // Only enable compaction when in a memory reduction garbage collection as
    // it may significantly increase the final garbage collection pause.
    compactor_.InitializeIfShouldCompact(marking_config.marking_type,
                                         marking_config.stack_state);
  }
  if (!schedule) {
    schedule =
        ::heap::base::IncrementalMarkingSchedule::Create(v8_flags.predictable);
  }
  marker_ = std::make_unique<UnifiedHeapMarker>(
      isolate_ ? isolate()->heap() : nullptr, AsBase(), schedule,
      platform_.get(), marking_config);
}
References AsBase(), CHECK, collection_type_, cppgc::internal::HeapBase::compactor_, heap::base::IncrementalMarkingSchedule::Create(), current_gc_flags_, v8::internal::DCHECK(), DCHECK_IMPLIES, force_incremental_marking_for_testing_, cppgc::internal::HeapBase::generational_gc_supported(), GetMetricRecorder(), v8::internal::Isolate::heap(), heap(), cppgc::internal::Compactor::InitializeIfShouldCompact(), v8::internal::anonymous_namespace{cpp-heap.cc}::IsForceGC(), isolate(), isolate_, cppgc::internal::Sweeper::IsSweepingInProgress(), cppgc::Heap::kAtomic, cppgc::internal::MarkingConfig::kForced, cppgc::internal::kMajor, cppgc::internal::kMinor, cppgc::internal::MarkingConfig::kNotForced, cppgc::internal::HeapBase::marker_, cppgc::internal::StatsCollector::NotifyUnmarkingStarted(), v8::internal::GCTracer::NotifyYoungCppGCRunning(), cppgc::internal::HeapBase::platform_, cppgc::internal::HeapBase::raw_heap(), SelectMarkingType(), v8::internal::anonymous_namespace{cpp-heap.cc}::ShouldReduceMemory(), cppgc::internal::HeapBase::stats_collector(), cppgc::internal::HeapBase::sweeper_, v8::internal::Heap::tracer(), and v8::internal::v8_flags.
Referenced by CollectGarbageForTesting(), and StartIncrementalGarbageCollectionForTesting().
InitializeOncePerProcess()
void v8::internal::CppHeap::InitializeOncePerProcess () [static]
Definition at line 488 of file cpp-heap.cc.
                                       {
  cppgc::internal::GetGlobalOOMHandler().SetCustomHandler(
      &GlobalFatalOutOfMemoryHandlerImpl);
}
References cppgc::internal::GetGlobalOOMHandler(), v8::internal::anonymous_namespace{cpp-heap.cc}::GlobalFatalOutOfMemoryHandlerImpl(), and cppgc::internal::FatalOutOfMemoryHandler::SetCustomHandler().
Referenced by v8::internal::V8::InitializePlatform().
IsDetachedGCAllowed()
bool v8::internal::CppHeap::IsDetachedGCAllowed () const [private]
Definition at line 1351 of file cpp-heap.cc.
                                        {
  return (isolate_ || in_detached_testing_mode_) && HeapBase::IsGCAllowed();
}
References in_detached_testing_mode_, cppgc::internal::HeapBase::IsGCAllowed(), and isolate_.
Referenced by CollectGarbageForTesting().
IsGCAllowed()
bool v8::internal::CppHeap::IsGCAllowed () const [override], [private], [virtual]
Reimplemented from cppgc::internal::HeapBase.
Definition at line 1355 of file cpp-heap.cc.
                                {
  return isolate_ && HeapBase::IsGCAllowed();
}
References cppgc::internal::HeapBase::IsGCAllowed(), and isolate_.
Referenced by CollectGarbage(), and ReportBufferedAllocationSizeIfPossible().
IsGCForbidden()
bool v8::internal::CppHeap::IsGCForbidden () const [override], [private], [virtual]
Reimplemented from cppgc::internal::HeapBase.
Definition at line 1359 of file cpp-heap.cc.
                                  {
  return (isolate_ && isolate_->InFastCCall() &&
          !v8_flags.allow_allocation_in_fast_api_call) ||
         HeapBase::IsGCForbidden();
}
References v8::internal::Isolate::InFastCCall(), cppgc::internal::HeapBase::IsGCForbidden(), isolate_, and v8::internal::v8_flags.
Referenced by EnterFinalPause().
IsMarkingDone()
bool v8::internal::CppHeap::IsMarkingDone () const
Definition at line 874 of file cpp-heap.cc.
                                  {
  return !TracingInitialized() || marking_done_;
}
References marking_done_, and TracingInitialized().
Referenced by ShouldFinalizeIncrementalMarking().
isolate()
Isolate* v8::internal::CppHeap::isolate () const [inline]
Definition at line 168 of file cpp-heap.h.
{ return isolate_; }
Referenced by AttachIsolate(), EnterFinalPause(), v8::internal::anonymous_namespace{cpp-heap.cc}::FatalOutOfMemoryHandlerImpl(), and InitializeMarking().
last_bytes_marked()
size_t v8::internal::CppHeap::last_bytes_marked () const
Definition at line 847 of file cpp-heap.cc.
                                        {
  DCHECK(TracingInitialized());
  return TracingInitialized() ? marker_->last_bytes_marked() : 0;
}
References v8::internal::DCHECK(), cppgc::internal::HeapBase::marker_, and TracingInitialized().
operator=()
CppHeap& v8::internal::CppHeap::operator= (const CppHeap &) [delete]
overridden_stack_state()
std::optional< cppgc::EmbedderStackState > v8::internal::CppHeap::overridden_stack_state () const [override], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 1290 of file cpp-heap.cc.
          {
  return heap_ ? heap_->overridden_stack_state()
               : detached_override_stack_state_;
}
References detached_override_stack_state_, heap_, and v8::internal::Heap::overridden_stack_state().
ProcessCrossThreadWeakness()
void v8::internal::CppHeap::ProcessCrossThreadWeakness ()
Definition at line 935 of file cpp-heap.cc.
                                         {
  CHECK(in_atomic_pause_);
  CHECK(marking_done_);
  if (!TracingInitialized()) {
    return;
  }
  marker_->ProcessCrossThreadWeaknessIfNeeded();
}
References CHECK, cppgc::internal::HeapBase::in_atomic_pause_, cppgc::internal::HeapBase::marker_, marking_done_, and TracingInitialized().
ReEnableConcurrentMarking()
void v8::internal::CppHeap::ReEnableConcurrentMarking ()
Definition at line 915 of file cpp-heap.cc.
                                        {
  CHECK(!in_atomic_pause_);
  marker_->ReEnableConcurrentMarking();
}
References CHECK, cppgc::internal::HeapBase::in_atomic_pause_, and cppgc::internal::HeapBase::marker_.
RememberCrossHeapReferenceIfNeeded()
void v8::internal::CppHeap::RememberCrossHeapReferenceIfNeeded (v8::internal::Tagged< v8::internal::CppHeapPointerWrapperObjectT > host_obj, void * value) [inline]
Definition at line 281 of file cpp-heap.h.
                 {
  if (!generational_gc_supported()) return;
  DCHECK(isolate_);
  cross_heap_remembered_set_.RememberReferenceIfNeeded(*isolate_, host_obj,
                                                       value);
}
References cross_heap_remembered_set_, v8::internal::DCHECK(), cppgc::internal::HeapBase::generational_gc_supported(), isolate_, v8::internal::CrossHeapRememberedSet::RememberReferenceIfNeeded(), and v8::internal::value.
Referenced by v8::internal::WriteBarrier::GenerationalBarrierForCppHeapPointer().
ReportBufferedAllocationSizeIfPossible()
void v8::internal::CppHeap::ReportBufferedAllocationSizeIfPossible () [private]
Definition at line 1044 of file cpp-heap.cc.
                                                     {
  // Reporting memory to V8 may trigger GC.
  if (!IsGCAllowed()) {
    return;
  }
  // We are in attached state.
  DCHECK_NOT_NULL(isolate_);
  // The calls below may trigger full GCs that are synchronous and also execute
  // epilogue callbacks. Since such callbacks may allocate, the counter must
  // already be zeroed by that time.
  const int64_t bytes_to_report = buffered_allocated_bytes_;
  buffered_allocated_bytes_ = 0;
  if (bytes_to_report < 0) {
    DCHECK_GE(used_size_.load(std::memory_order_relaxed), bytes_to_report);
    used_size_.fetch_sub(static_cast<size_t>(-bytes_to_report),
                         std::memory_order_relaxed);
  } else {
    used_size_.fetch_add(static_cast<size_t>(bytes_to_report),
                         std::memory_order_relaxed);
    allocated_size_ += bytes_to_report;
    if (v8_flags.incremental_marking) {
      if (allocated_size_ > allocated_size_limit_for_check_) {
        Heap* heap = isolate_->heap();
        heap->StartIncrementalMarkingIfAllocationLimitIsReached(
            heap->main_thread_local_heap(),
            heap->GCFlagsForIncrementalMarking(),
            kGCCallbackScheduleIdleGarbageCollection);
        if (heap->incremental_marking()->IsMajorMarking()) {
          if (heap->AllocationLimitOvershotByLargeMargin()) {
            heap->FinalizeIncrementalMarkingAtomically(
                i::GarbageCollectionReason::kExternalFinalize);
          } else {
            heap->incremental_marking()->AdvanceOnAllocation();
          }
        }
        allocated_size_limit_for_check_ =
            allocated_size_ + kIncrementalMarkingCheckInterval;
      }
    }
  }
}
References allocated_size_, allocated_size_limit_for_check_, buffered_allocated_bytes_, DCHECK_GE, DCHECK_NOT_NULL, v8::internal::Isolate::heap(), IsGCAllowed(), isolate_, v8::kGCCallbackScheduleIdleGarbageCollection, v8::internal::anonymous_namespace{cpp-heap.cc}::kIncrementalMarkingCheckInterval, used_size_, and v8::internal::v8_flags.
Referenced by AllocatedObjectSizeDecreased(), and AllocatedObjectSizeIncreased().
ResetAllocatedObjectSize()
void v8::internal::CppHeap::ResetAllocatedObjectSize (size_t) [inline], [final], [virtual]
Reimplemented from cppgc::internal::StatsCollector::AllocationObserver.
Definition at line 164 of file cpp-heap.h.
{}
ResetCrossHeapRememberedSet()
void v8::internal::CppHeap::ResetCrossHeapRememberedSet ()
Definition at line 1338 of file cpp-heap.cc.
                                          {
  if (!generational_gc_supported()) {
    DCHECK(cross_heap_remembered_set_.IsEmpty());
    return;
  }
  DCHECK(isolate_);
  cross_heap_remembered_set_.Reset(*isolate_);
}
References cross_heap_remembered_set_, v8::internal::DCHECK(), cppgc::internal::HeapBase::generational_gc_supported(), v8::internal::CrossHeapRememberedSet::IsEmpty(), isolate_, and v8::internal::CrossHeapRememberedSet::Reset().
Referenced by CompactAndSweep().
SelectMarkingType()
CppHeap::MarkingType v8::internal::CppHeap::SelectMarkingType () const [private]
Definition at line 704 of file cpp-heap.cc.
                                                    {
  // For now, force atomic marking for minor collections.
  if (*collection_type_ == CollectionType::kMinor) return MarkingType::kAtomic;
  if (IsForceGC(current_gc_flags_) && !force_incremental_marking_for_testing_)
    return MarkingType::kAtomic;
  const MarkingType marking_type = marking_support();
  // CollectionType is major at this point. Check the surrounding
  // MarkCompactCollector for whether we should rely on background threads in
  // this GC cycle.
  if (marking_type == MarkingType::kIncrementalAndConcurrent && heap_ &&
      !heap_->mark_compact_collector()->UseBackgroundThreadsInCycle()) {
    return MarkingType::kIncremental;
  }
  return marking_support();
}
References collection_type_, current_gc_flags_, force_incremental_marking_for_testing_, heap_, v8::internal::anonymous_namespace{cpp-heap.cc}::IsForceGC(), cppgc::Heap::kAtomic, cppgc::Heap::kIncremental, cppgc::Heap::kIncrementalAndConcurrent, cppgc::internal::kMinor, v8::internal::Heap::mark_compact_collector(), cppgc::internal::HeapBase::marking_support(), and v8::internal::MarkCompactCollector::UseBackgroundThreadsInCycle().
Referenced by InitializeMarking().
SelectSweepingType()
CppHeap::SweepingType v8::internal::CppHeap::SelectSweepingType () const [private]
Definition at line 724 of file cpp-heap.cc.
                                                      {
  if (IsForceGC(current_gc_flags_)) return SweepingType::kAtomic;
  return sweeping_support();
}
References current_gc_flags_, v8::internal::anonymous_namespace{cpp-heap.cc}::IsForceGC(), cppgc::Heap::kAtomic, and cppgc::internal::HeapBase::sweeping_support().
Referenced by CompactAndSweep(), and FinishAtomicSweepingIfRunning().
set_override_stack_state()
void v8::internal::CppHeap::set_override_stack_state (cppgc::EmbedderStackState state) [override], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 1296 of file cpp-heap.cc.
                                                                    {
  CHECK(!detached_override_stack_state_);
  CHECK(!override_stack_state_scope_);
  if (heap_) {
    override_stack_state_scope_ = std::make_unique<EmbedderStackStateScope>(
        heap_, EmbedderStackStateOrigin::kExplicitInvocation, state);
  } else {
    detached_override_stack_state_ = state;
  }
}
References CHECK, detached_override_stack_state_, heap_, v8::internal::kExplicitInvocation, and override_stack_state_scope_.
ShouldFinalizeIncrementalMarking()
bool v8::internal::CppHeap::ShouldFinalizeIncrementalMarking () const
Definition at line 878 of file cpp-heap.cc.
                                                     {
  return !incremental_marking_supported() || IsMarkingDone();
}
References cppgc::internal::HeapBase::incremental_marking_supported(), and IsMarkingDone().
stack()
heap::base::Stack * v8::internal::CppHeap::stack () [final], [virtual]
Reimplemented from cppgc::internal::HeapBase.
Definition at line 682 of file cpp-heap.cc.
                              {
  return isolate_ ? &isolate_->heap()->stack() : HeapBase::stack();
}
References v8::internal::Isolate::heap(), isolate_, cppgc::internal::HeapBase::stack(), and v8::internal::Heap::stack().
Referenced by CollectGarbageForTesting().
StartDetachingIsolate()
void v8::internal::CppHeap::StartDetachingIsolate ()
Definition at line 638 of file cpp-heap.cc.
                                    {
  DCHECK(!is_detached_);
  is_detached_ = true;
  // TODO(chromium:1056170): Investigate whether this can be enforced with a
  // CHECK across all relevant embedders and setups.
  if (!isolate_) return;
  // Store the last thread that owned the isolate, as it is the thread CppHeap
  // should also get terminated with.
  heap_thread_id_ = v8::base::OS::GetCurrentThreadId();
  // Finish any ongoing garbage collection.
  if (isolate_->heap()->incremental_marking()->IsMarking()) {
    isolate_->heap()->FinalizeIncrementalMarkingAtomically(
        i::GarbageCollectionReason::kExternalFinalize);
  }
  sweeper_.FinishIfRunning();
}
References v8::internal::DCHECK(), v8::internal::Heap::FinalizeIncrementalMarkingAtomically(), cppgc::internal::Sweeper::FinishIfRunning(), v8::base::OS::GetCurrentThreadId(), v8::internal::Isolate::heap(), cppgc::internal::HeapBase::heap_thread_id_, v8::internal::Heap::incremental_marking(), is_detached_, v8::internal::IncrementalMarking::IsMarking(), isolate_, and cppgc::internal::HeapBase::sweeper_.
Referenced by v8::internal::Heap::StartTearDown().
StartIncrementalGarbageCollection()
void v8::internal::CppHeap::StartIncrementalGarbageCollection (cppgc::internal::GCConfig) [override], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 1319 of file cpp-heap.cc.
                                                                     {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
StartIncrementalGarbageCollectionForTesting()
void v8::internal::CppHeap::StartIncrementalGarbageCollectionForTesting () [final], [private], [virtual]
Implements cppgc::internal::HeapBase.
Definition at line 1135 of file cpp-heap.cc.
                                                          {
  DCHECK(!in_no_gc_scope());
  DCHECK_NULL(isolate_);
  if (IsMarking()) return;
  force_incremental_marking_for_testing_ = true;
  InitializeMarking(CollectionType::kMajor, nullptr,
                    GarbageCollectionFlagValues::kForced);
  StartMarking();
  force_incremental_marking_for_testing_ = false;
}
References v8::internal::DCHECK(), DCHECK_NULL, force_incremental_marking_for_testing_, cppgc::internal::HeapBase::in_no_gc_scope(), InitializeMarking(), cppgc::internal::HeapBase::IsMarking(), isolate_, cppgc::internal::kMajor, and StartMarking().
StartMarking()
void v8::internal::CppHeap::StartMarking ()
Definition at line 833 of file cpp-heap.cc.
                           {
  CHECK(marking_done_);
  if (!TracingInitialized()) return;
  if (isolate_) {
    // Reuse the same local worklist for the mutator marking state which results
    // in directly processing the objects by the JS logic. Also avoids
    // publishing local objects.
    marker_->To<UnifiedHeapMarker>().GetMutatorUnifiedHeapMarkingState().Update(
        GetV8MarkingWorklists(isolate_, *collection_type_));
  }
  marker_->StartMarking();
  marking_done_ = false;
}
References CHECK, collection_type_, v8::internal::anonymous_namespace{cpp-heap.cc}::GetV8MarkingWorklists(), isolate_, cppgc::internal::HeapBase::marker_, marking_done_, and TracingInitialized().
Referenced by CollectGarbageForTesting(), v8::internal::MarkCompactCollector::Prepare(), StartIncrementalGarbageCollectionForTesting(), and v8::internal::IncrementalMarking::StartMarkingMajor().
Terminate()
void v8::internal::CppHeap::Terminate ()
Definition at line 519 of file cpp-heap.cc.
                        {
  // TODO(ahaas): Remove `already_terminated_` once the V8 API
  // CppHeap::Terminate has been removed.
  if (already_terminated_) return;
  already_terminated_ = true;
  // Must not be attached to a heap when invoking termination GCs.
  CHECK(!isolate_);
  // Gracefully terminate the C++ heap invoking destructors.
  HeapBase::Terminate();
}
References already_terminated_, CHECK, isolate_, and cppgc::internal::HeapBase::Terminate().
Referenced by v8::CppHeap::Terminate(), and ~CppHeap().
TracingInitialized()
bool v8::internal::CppHeap::TracingInitialized () const [inline], [private]
Definition at line 228 of file cpp-heap.h.
{ return collection_type_.has_value(); }
Referenced by AdvanceMarking(), CompactAndSweep(), CreateCppMarkingState(), CreateCppMarkingStateForMutatorThread(), EnterFinalPause(), EnterProcessGlobalAtomicPause(), FinishConcurrentMarkingIfNeeded(), FinishMarkingAndProcessWeakness(), IsMarkingDone(), last_bytes_marked(), ProcessCrossThreadWeakness(), and StartMarking().
UpdateGCCapabilitiesFromFlags()
void v8::internal::CppHeap::UpdateGCCapabilitiesFromFlags () [private]
Definition at line 730 of file cpp-heap.cc.
                                            {
  CHECK_IMPLIES(v8_flags.cppheap_concurrent_marking,
                v8_flags.cppheap_incremental_marking);
  if (v8_flags.cppheap_concurrent_marking) {
    marking_support_ = static_cast<MarkingType>(
        std::min(marking_support_, MarkingType::kIncrementalAndConcurrent));
  } else if (v8_flags.cppheap_incremental_marking) {
    marking_support_ = static_cast<MarkingType>(
        std::min(marking_support_, MarkingType::kIncremental));
  } else {
    marking_support_ = MarkingType::kAtomic;
  }
  sweeping_support_ = v8_flags.single_threaded_gc
                          ? CppHeap::SweepingType::kIncremental
                          : CppHeap::SweepingType::kIncrementalAndConcurrent;
  page_backend_->page_pool().SetDecommitPooledPages(
      v8_flags.decommit_pooled_pages);
}
References CHECK_IMPLIES, cppgc::Heap::kAtomic, cppgc::Heap::kIncremental, cppgc::Heap::kIncrementalAndConcurrent, cppgc::internal::HeapBase::marking_support_, cppgc::internal::HeapBase::page_backend_, cppgc::internal::HeapBase::sweeping_support_, and v8::internal::v8_flags.
Referenced by AttachIsolate(), and UpdateGCCapabilitiesFromFlagsForTesting().
UpdateGCCapabilitiesFromFlagsForTesting()
void v8::internal::CppHeap::UpdateGCCapabilitiesFromFlagsForTesting ()
Definition at line 1347 of file cpp-heap.cc.
                                                      {
  UpdateGCCapabilitiesFromFlags();
}
References UpdateGCCapabilitiesFromFlags().
used_size()
size_t v8::internal::CppHeap::used_size () const [inline]
Definition at line 170 of file cpp-heap.h.
                           {
    return used_size_.load(std::memory_order_relaxed);
  }
Referenced by v8::internal::Heap::EmbedderSizeOfObjects().
VisitCrossHeapRememberedSetIfNeeded()
template<typename F >
void v8::internal::CppHeap::VisitCrossHeapRememberedSetIfNeeded (F f) [inline]
Definition at line 291 of file cpp-heap.h.
                                                     {
  if (!generational_gc_supported()) return;
  DCHECK(isolate_);
  cross_heap_remembered_set_.Visit(*isolate_, std::move(f));
}
References cross_heap_remembered_set_, v8::internal::DCHECK(), cppgc::internal::HeapBase::generational_gc_supported(), isolate_, and v8::internal::CrossHeapRememberedSet::Visit().
WriteBarrier()
void v8::internal::CppHeap::WriteBarrier (void * object)
Definition at line 920 of file cpp-heap.cc.
                                       {
  auto& header = cppgc::internal::HeapObjectHeader::FromObject(object);
  marker_->WriteBarrierForObject<
      cppgc::internal::MarkerBase::WriteBarrierType::kDijkstra>(header);
}
References cppgc::internal::HeapObjectHeader::FromObject(), cppgc::internal::MarkerBase::kDijkstra, and cppgc::internal::HeapBase::marker_.
Referenced by v8::internal::WriteBarrier::MarkingSlowFromCppHeapWrappable().
Friends And Related Function Documentation
MetricRecorderAdapter
friend class MetricRecorderAdapter [friend]
Definition at line 278 of file cpp-heap.h.
Member Data Documentation
allocated_size_
size_t v8::internal::CppHeap::allocated_size_ = 0 [private]
Definition at line 262 of file cpp-heap.h.
Referenced by ReportBufferedAllocationSizeIfPossible().
allocated_size_limit_for_check_
size_t v8::internal::CppHeap::allocated_size_limit_for_check_ = 0 [private]
Definition at line 265 of file cpp-heap.h.
Referenced by FinishMarkingAndProcessWeakness(), and ReportBufferedAllocationSizeIfPossible().
already_terminated_
bool v8::internal::CppHeap::already_terminated_ = false [private]
Definition at line 275 of file cpp-heap.h.
Referenced by Terminate().
buffered_allocated_bytes_
int64_t v8::internal::CppHeap::buffered_allocated_bytes_ = 0 [private]
Definition at line 252 of file cpp-heap.h.
Referenced by AllocatedObjectSizeDecreased(), AllocatedObjectSizeIncreased(), CompactAndSweep(), and ReportBufferedAllocationSizeIfPossible().
collection_type_
std::optional<CollectionType> v8::internal::CppHeap::collection_type_ [private]
Definition at line 240 of file cpp-heap.h.
Referenced by CompactAndSweep(), EnterFinalPause(), InitializeMarking(), SelectMarkingType(), and StartMarking().
cross_heap_remembered_set_
CrossHeapRememberedSet v8::internal::CppHeap::cross_heap_remembered_set_ [private]
Definition at line 244 of file cpp-heap.h.
Referenced by RememberCrossHeapReferenceIfNeeded(), ResetCrossHeapRememberedSet(), and VisitCrossHeapRememberedSetIfNeeded().
current_gc_flags_
GarbageCollectionFlags v8::internal::CppHeap::current_gc_flags_ [private]
Definition at line 241 of file cpp-heap.h.
Referenced by CompactAndSweep(), FinishSweepingIfRunning(), InitializeMarking(), SelectMarkingType(), and SelectSweepingType().
detached_override_stack_state_
std::optional<cppgc::EmbedderStackState> v8::internal::CppHeap::detached_override_stack_state_ [private]
Definition at line 267 of file cpp-heap.h.
Referenced by AttachIsolate(), clear_overridden_stack_state(), DetachIsolate(), overridden_stack_state(), and set_override_stack_state().
force_incremental_marking_for_testing_
bool v8::internal::CppHeap::force_incremental_marking_for_testing_ = false [private]
Definition at line 255 of file cpp-heap.h.
Referenced by InitializeMarking(), SelectMarkingType(), and StartIncrementalGarbageCollectionForTesting().
heap_
Heap* v8::internal::CppHeap::heap_ = nullptr [private]
Definition at line 237 of file cpp-heap.h.
Referenced by AttachIsolate(), clear_overridden_stack_state(), DetachIsolate(), overridden_stack_state(), SelectMarkingType(), and set_override_stack_state().
in_detached_testing_mode_
bool v8::internal::CppHeap::in_detached_testing_mode_ = false [private]
Definition at line 254 of file cpp-heap.h.
Referenced by AttachIsolate(), EnableDetachedGarbageCollectionsForTesting(), and IsDetachedGCAllowed().
is_detached_
bool v8::internal::CppHeap::is_detached_ = true [private]
Definition at line 276 of file cpp-heap.h.
Referenced by AttachIsolate(), CurrentThreadIsHeapThread(), and StartDetachingIsolate().
is_in_v8_marking_step_
bool v8::internal::CppHeap::is_in_v8_marking_step_ = false [private]
Definition at line 256 of file cpp-heap.h.
Referenced by AdvanceMarking().
isolate_
Isolate* v8::internal::CppHeap::isolate_ = nullptr [private]
Definition at line 236 of file cpp-heap.h.
Referenced by AttachIsolate(), CollectGarbage(), CollectGarbageForTesting(), CompactAndSweep(), CurrentThreadIsHeapThread(), DetachIsolate(), EnableDetachedGarbageCollectionsForTesting(), EnterFinalPause(), FinalizeIncrementalGarbageCollectionForTesting(), FinishMarkingAndProcessWeakness(), FinishSweepingIfRunning(), InitializeMarking(), IsDetachedGCAllowed(), IsGCAllowed(), IsGCForbidden(), RememberCrossHeapReferenceIfNeeded(), ReportBufferedAllocationSizeIfPossible(), ResetCrossHeapRememberedSet(), stack(), StartDetachingIsolate(), StartIncrementalGarbageCollectionForTesting(), StartMarking(), Terminate(), and VisitCrossHeapRememberedSetIfNeeded().
marking_done_
bool v8::internal::CppHeap::marking_done_ = true [private]
Definition at line 238 of file cpp-heap.h.
Referenced by AdvanceMarking(), FinishMarkingAndProcessWeakness(), IsMarkingDone(), ProcessCrossThreadWeakness(), and StartMarking().
minor_gc_heap_growing_
std::unique_ptr<MinorGCHeapGrowing> v8::internal::CppHeap::minor_gc_heap_growing_ [private]
Definition at line 243 of file cpp-heap.h.
override_stack_state_scope_
std::unique_ptr<v8::internal::EmbedderStackStateScope> v8::internal::CppHeap::override_stack_state_scope_ [private]
Definition at line 269 of file cpp-heap.h.
Referenced by AttachIsolate(), clear_overridden_stack_state(), DetachIsolate(), and set_override_stack_state().
sweeping_on_mutator_thread_observer_
std::unique_ptr<cppgc::internal::Sweeper::SweepingOnMutatorThreadObserver> v8::internal::CppHeap::sweeping_on_mutator_thread_observer_ [private]
Definition at line 247 of file cpp-heap.h.
Referenced by AttachIsolate(), and DetachIsolate().
used_size_
std::atomic<size_t> v8::internal::CppHeap::used_size_ {0} [private]
Definition at line 259 of file cpp-heap.h.
Referenced by FinishMarkingAndProcessWeakness(), and ReportBufferedAllocationSizeIfPossible().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc-js/cpp-heap.h
/mnt/V8SourceCode/src/heap/cppgc-js/cpp-heap.cc