v8::api_internal::IndirectHandleBase Class Reference
A base class for abstract handles containing indirect pointers.
#include <v8-handle-base.h>
Public Member Functions
bool IsEmpty () const
void Clear ()
Protected Member Functions
IndirectHandleBase ()=default
IndirectHandleBase (const IndirectHandleBase &other)=default
IndirectHandleBase & operator= (const IndirectHandleBase &that)=default
IndirectHandleBase (internal::Address *location)
internal::Address ptr () const
internal::Address *const & slot () const
internal::Address *& slot ()
template<typename T , bool check_null = false>
T * value () const
internal::ValueHelper::InternalRepresentationType repr () const
Private Attributes
internal::Address * location_ = nullptr
Friends
class internal::ValueHelper
class internal::HandleHelper
Detailed Description
A base class for abstract handles containing indirect pointers.
These are useful regardless of whether direct local support is enabled.
Definition at line 57 of file v8-handle-base.h.
Constructor & Destructor Documentation
IndirectHandleBase() [1/3]
v8::api_internal::IndirectHandleBase::IndirectHandleBase () [inline], [protected], [default]
IndirectHandleBase() [2/3]
v8::api_internal::IndirectHandleBase::IndirectHandleBase (const IndirectHandleBase & other) [inline], [protected], [default]
IndirectHandleBase() [3/3]
v8::api_internal::IndirectHandleBase::IndirectHandleBase (internal::Address * location) [inline], [explicit], [protected]
Definition at line 74 of file v8-handle-base.h.
      : location_(location) {}
Member Function Documentation
Clear()
void v8::api_internal::IndirectHandleBase::Clear () [inline]
Definition at line 63 of file v8-handle-base.h.
{ location_ = nullptr; }
References location_.
Referenced by v8::PersistentValueMapBase< K, V, Traits >::ClearAndLeak().
IsEmpty()
bool v8::api_internal::IndirectHandleBase::IsEmpty () const [inline]
Definition at line 60 of file v8-handle-base.h.
{ return location_ == nullptr; }
References location_.
Referenced by v8_inspector::V8Console::CommandLineAPIScope::accessorSetterCallback(), v8::internal::CppGraphBuilderImpl::AddEdge(), v8_inspector::InjectedScript::addExceptionToDetails(), v8_inspector::V8HeapProfilerAgentImpl::addInspectedHeapObject(), v8_inspector::InspectedContext::addInternalObject(), v8::Isolate::AddMessageListenerWithErrorLevel(), v8_inspector::V8InspectorImpl::associateExceptionData(), v8::Context::BackupIncumbentScope::BackupIncumbentScope(), v8_inspector::V8Debugger::BreakpointConditionEvaluated(), v8::Persistent< T, M >::Cast(), v8::Local< T >::Cast(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8::TracedReferenceBase::CheckValue(), v8_inspector::InjectedScript::commandLineAPI(), v8::internal::Genesis::ConfigureGlobalObject(), v8::Persistent< T, M >::Copy(), v8_inspector::V8StackTraceImpl::create(), v8::Shell::CreateEvaluationContext(), v8_inspector::InjectedScript::createExceptionDetails(), v8_inspector::V8ConsoleMessage::createForException(), v8::anonymous_namespace{api.cc}::CreateInterceptorInfo(), v8::internal::Genesis::CreateNewGlobals(), v8::Shell::CreateRealm(), v8_inspector::V8DebuggerAgentImpl::currentCallFrames(), v8::ArrayBuffer::Detach(), v8::Shell::DoHostImportModuleDynamically(), v8::internal::EmbedderState::EmbedderState(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::ensureContext(), v8_inspector::V8InspectorImpl::exceptionMetaDataContext(), v8::Shell::ExecuteModule(), v8::Shell::FetchModuleSource(), v8::Shell::FetchModuleTree(), v8::Shell::FunctionAndArgumentsToString(), v8_inspector::generateCustomPreview(), v8::internal::Genesis::Genesis(), v8::TracedReferenceBase::Get(), v8_inspector::V8InspectorImpl::getAssociatedExceptionData(), v8::internal::DebugStackTraceIterator::GetFunctionLocation(), v8_inspector::InspectedContext::getInternalType(), v8_inspector::V8HeapProfilerAgentImpl::getObjectByHeapObjectId(), v8_inspector::ValueMirror::getProperties(), v8::anonymous_namespace{api.cc}::GetScriptDetails(), v8::internal::JSAtomicsMutex::HandleAsyncNotify(), v8::internal::JSAtomicsCondition::HandleAsyncNotify(), v8::internal::JSAtomicsMutex::HandleAsyncTimeout(), v8::internal::JSAtomicsCondition::HandleAsyncTimeout(), v8_inspector::V8Debugger::installTerminateExecutionCallbacks(), v8_inspector::V8Regex::isValid(), v8_inspector::InjectedScript::lastEvaluationResult(), v8::LocalBase< T >::LocalBase(), v8::anonymous_namespace{api.cc}::MakeAccessorInfo(), v8_inspector::V8Regex::match(), v8_inspector::V8Debugger::nearHeapLimitCallback(), v8::TracedReference< T >::operator=(), v8::Shell::PromiseRejectCallback(), v8_inspector::V8InspectorImpl::regexContext(), v8::Shell::ReportException(), v8_inspector::V8Debugger::reportTermination(), v8::TracedReferenceBase::Reset(), v8::PersistentBase< T >::Reset(), v8::TracedReference< T >::Reset(), v8::Shell::RunShell(), v8::ObjectTemplate::SetAccessCheckCallback(), v8::ObjectTemplate::SetAccessCheckCallbackAndHandler(), v8::Template::SetAccessorProperty(), v8::FunctionTemplate::SetCallHandler(), v8::Isolate::SetContinuationPreservedEmbedderData(), v8::Isolate::SetContinuationPreservedEmbedderDataV2(), v8::debug::SetFunctionBreakpoint(), v8::Context::SetPromiseHooks(), v8::AsyncHooks::ShellPromiseHook(), v8::JSON::Stringify(), v8_inspector::V8Console::taskInfoKey(), v8_inspector::V8Console::taskTemplate(), v8::Value::ToDetailString(), v8::TracedReference< T >::TracedReference(), v8::String::Utf8Value::Utf8Value(), v8::String::Value::Value(), v8::internal::CppGraphBuilderImpl::VisitForVisibility(), v8::Shell::WorkerOnMessageGetter(), v8_inspector::InspectedContext::~InspectedContext(), and v8_inspector::V8Debugger::~V8Debugger().
operator=()
IndirectHandleBase& v8::api_internal::IndirectHandleBase::operator= (const IndirectHandleBase & that) [inline], [protected], [default]
ptr()
internal::Address v8::api_internal::IndirectHandleBase::ptr () const [inline], [protected]
Definition at line 80 of file v8-handle-base.h.
{ return *location_; }
References location_.
repr()
internal::ValueHelper::InternalRepresentationType v8::api_internal::IndirectHandleBase::repr () const [inline], [protected]
Definition at line 98 of file v8-handle-base.h.
                                                                       {
    return location_;
  }
References location_.
Referenced by v8::LocalBase< T >::FromRepr().
slot() [1/2]
internal::Address*& v8::api_internal::IndirectHandleBase::slot () [inline], [protected]
Definition at line 84 of file v8-handle-base.h.
{ return location_; }
References location_.
slot() [2/2]
internal::Address* const& v8::api_internal::IndirectHandleBase::slot () const [inline], [protected]
Definition at line 83 of file v8-handle-base.h.
{ return location_; }
References location_.
Referenced by v8::TracedReferenceBase::CheckValue(), v8::PersistentValueMapBase< K, V, Traits >::ClearAndLeak(), v8::Persistent< T, M >::Copy(), v8::LocalBase< T >::FromSlot(), v8::Eternal< T >::Get(), v8::TracedReferenceBase::GetSlotThreadSafe(), v8::PersistentValueMapBase< K, V, Traits >::Leak(), v8::Utils::OpenPersistent(), v8::TracedReference< T >::operator=(), v8::PersistentValueMapBase< K, V, Traits >::Release(), v8::PersistentValueMapBase< K, V, Traits >::RemoveWeak(), v8::Eternal< T >::requires(), v8::TracedReferenceBase::Reset(), v8::TracedReferenceBase::SetSlotThreadSafe(), v8::TracedReference< T >::TracedReference(), and value().
value()
template<typename T , bool check_null = false>
T* v8::api_internal::IndirectHandleBase::value () const [inline], [protected]
Definition at line 89 of file v8-handle-base.h.
                             {
    return internal::ValueHelper::SlotAsValue<T, check_null>(slot());
  }
References slot().
Referenced by v8::LocalBase< T >::New().
Friends And Related Function Documentation
internal::HandleHelper
friend class internal::HandleHelper [friend]
Definition at line 67 of file v8-handle-base.h.
internal::ValueHelper
friend class internal::ValueHelper [friend]
Definition at line 66 of file v8-handle-base.h.
Member Data Documentation
location_
internal::Address* v8::api_internal::IndirectHandleBase::location_ = nullptr [private]
Definition at line 104 of file v8-handle-base.h.
Referenced by Clear(), IsEmpty(), ptr(), repr(), and slot().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-handle-base.h