v8::internal::compiler::BranchElimination Class Reference
#include <branch-elimination.h>
Public Types
enum Phase { kEARLY
, kLATE
 }
Public Member Functions
BranchElimination (Editor *editor, JSGraph *js_graph, Zone *zone, Phase phase=kLATE)
~BranchElimination () final
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Types
using ControlPathConditions = ControlPathState< BranchCondition, kUniqueInstance >
Private Member Functions
Reduction ReduceBranch (Node *node)
Reduction ReduceDeoptimizeConditional (Node *node)
Reduction ReduceIf (Node *node, bool is_true_branch)
Reduction ReduceTrapConditional (Node *node)
Reduction ReduceLoop (Node *node)
Reduction ReduceMerge (Node *node)
Reduction ReduceStart (Node *node)
Reduction ReduceOtherControl (Node *node)
void SimplifyBranchCondition (Node *branch)
bool TryEliminateBranchWithPhiCondition (Node *branch, Node *phi, Node *merge)
Reduction UpdateStatesHelper (Node *node, ControlPathConditions prev_conditions, Node *current_condition, Node *current_branch, bool is_true_branch, bool in_new_block)
Node * dead () const
TFGraph * graph () const
JSGraph * jsgraph () const
Isolate * isolate () const
CommonOperatorBuilder * common () const
Private Attributes
JSGraph *const jsgraph_
Node * dead_
Phase phase_
Detailed Description
Definition at line 42 of file branch-elimination.h.
Member Typedef Documentation
ControlPathConditions
using v8::internal::compiler::BranchElimination::ControlPathConditions = ControlPathState<BranchCondition, kUniqueInstance> [private]
Definition at line 61 of file branch-elimination.h.
Member Enumeration Documentation
Phase
enum v8::internal::compiler::BranchElimination::Phase
Enumerator
kEARLY
kLATE
Definition at line 48 of file branch-elimination.h.
             {
    kEARLY,
    kLATE,
  };
Constructor & Destructor Documentation
BranchElimination()
v8::internal::compiler::BranchElimination::BranchElimination (Editor * editor, JSGraph * js_graph, Zone * zone, Phase phase = kLATE)
Definition at line 18 of file branch-elimination.cc.
    : AdvancedReducerWithControlPathState(editor, zone, js_graph->graph()),
      jsgraph_(js_graph),
      dead_(js_graph->Dead()),
      phase_(phase) {}
 BranchElimination()
v8::internal::compiler::BranchElimination::~BranchElimination () [final], [default]
Member Function Documentation
common()
CommonOperatorBuilder * v8::internal::compiler::BranchElimination::common () const [private]
Definition at line 394 of file branch-elimination.cc.
                                                       {
  return jsgraph()->common();
}
References v8::internal::compiler::MachineGraph::common(), and jsgraph().
Referenced by ReduceDeoptimizeConditional(), ReduceTrapConditional(), and SimplifyBranchCondition().
dead()
Node* v8::internal::compiler::BranchElimination::dead () const [inline], [private]
Definition at line 84 of file branch-elimination.h.
{ return dead_; }
Referenced by ReduceBranch(), ReduceDeoptimizeConditional(), and ReduceTrapConditional().
graph()
TFGraph * v8::internal::compiler::BranchElimination::graph () const [private]
Definition at line 390 of file branch-elimination.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
Referenced by ReduceDeoptimizeConditional(), ReduceTrapConditional(), and SimplifyBranchCondition().
isolate()
Isolate * v8::internal::compiler::BranchElimination::isolate () const [private]
Definition at line 392 of file branch-elimination.cc.
{ return jsgraph()->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph().
jsgraph()
JSGraph* v8::internal::compiler::BranchElimination::jsgraph () const [inline], [private]
Definition at line 86 of file branch-elimination.h.
{ return jsgraph_; }
Referenced by common(), graph(), isolate(), and SimplifyBranchCondition().
Reduce()
Reduction v8::internal::compiler::BranchElimination::Reduce (Node * node) [final]
Definition at line 27 of file branch-elimination.cc.
                                              {
  switch (node->opcode()) {
    case IrOpcode::kDead:
      return NoChange();
    case IrOpcode::kDeoptimizeIf:
    case IrOpcode::kDeoptimizeUnless:
      return ReduceDeoptimizeConditional(node);
    case IrOpcode::kMerge:
      return ReduceMerge(node);
    case IrOpcode::kLoop:
      return ReduceLoop(node);
    case IrOpcode::kBranch:
      return ReduceBranch(node);
    case IrOpcode::kIfFalse:
      return ReduceIf(node, false);
    case IrOpcode::kIfTrue:
      return ReduceIf(node, true);
    case IrOpcode::kTrapIf:
    case IrOpcode::kTrapUnless:
      return ReduceTrapConditional(node);
    case IrOpcode::kStart:
      return ReduceStart(node);
    default:
      if (node->op()->ControlOutputCount() > 0) {
        return ReduceOtherControl(node);
      } else {
        return NoChange();
      }
  }
}
References v8::internal::compiler::Operator::ControlOutputCount(), v8::internal::compiler::turboshaft::kBranch, v8::kStart, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), ReduceBranch(), ReduceDeoptimizeConditional(), ReduceIf(), ReduceLoop(), ReduceMerge(), ReduceOtherControl(), ReduceStart(), and ReduceTrapConditional().
ReduceBranch()
Reduction v8::internal::compiler::BranchElimination::ReduceBranch (Node * node) [private]
Definition at line 221 of file branch-elimination.cc.
                                                    {
  Node* condition = node->InputAt(0);
  Node* control_input = NodeProperties::GetControlInput(node, 0);
  if (!IsReduced(control_input)) return NoChange();
  ControlPathConditions from_input = GetState(control_input);
  // If we know the condition we can discard the branch.
  BranchCondition branch_condition = from_input.LookupState(condition);
  if (branch_condition.IsSet()) {
    bool condition_value = branch_condition.is_true;
    for (Node* const use : node->uses()) {
      switch (use->opcode()) {
        case IrOpcode::kIfTrue:
          Replace(use, condition_value ? control_input : dead());
          break;
        case IrOpcode::kIfFalse:
          Replace(use, condition_value ? dead() : control_input);
          break;
        default:
          UNREACHABLE();
      }
    }
    return Replace(dead());
  }
  SimplifyBranchCondition(node);
  // Try to reduce the pattern that branch condition comes from phi node.
  if (condition->opcode() == IrOpcode::kPhi &&
      control_input->opcode() == IrOpcode::kMerge) {
    if (TryEliminateBranchWithPhiCondition(node, condition, control_input)) {
      return Replace(dead());
    }
  }
  // Trigger revisits of the IfTrue/IfFalse projections, since they depend on
  // the branch condition.
  for (Node* const use : node->uses()) {
    Revisit(use);
  }
  return TakeStatesFromFirstControl(node);
}
References dead(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::BranchCondition::is_true, v8::internal::compiler::BranchCondition::IsSet(), v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::LookupState(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), SimplifyBranchCondition(), TryEliminateBranchWithPhiCondition(), v8::internal::UNREACHABLE(), use(), and v8::internal::compiler::Node::uses().
Referenced by Reduce().
ReduceDeoptimizeConditional()
Reduction v8::internal::compiler::BranchElimination::ReduceDeoptimizeConditional (Node * node) [private]
Definition at line 295 of file branch-elimination.cc.
                                                                   {
  DCHECK(node->opcode() == IrOpcode::kDeoptimizeIf ||
         node->opcode() == IrOpcode::kDeoptimizeUnless);
  bool condition_is_true = node->opcode() == IrOpcode::kDeoptimizeUnless;
  DeoptimizeParameters p = DeoptimizeParametersOf(node->op());
  Node* condition = NodeProperties::GetValueInput(node, 0);
  Node* frame_state = NodeProperties::GetValueInput(node, 1);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  // If we do not know anything about the predecessor, do not propagate just
  // yet because we will have to recompute anyway once we compute the
  // predecessor.
  if (!IsReduced(control)) {
    return NoChange();
  }
  ControlPathConditions conditions = GetState(control);
  BranchCondition branch_condition = conditions.LookupState(condition);
  if (branch_condition.IsSet()) {
    // If we know the condition we can discard the branch.
    bool condition_value = branch_condition.is_true;
    if (condition_is_true == condition_value) {
      // We don't update the conditions here, because we're replacing {node}
      // with the {control} node that already contains the right information.
      ReplaceWithValue(node, dead(), effect, control);
    } else {
      control = graph()->NewNode(common()->Deoptimize(p.reason(), p.feedback()),
                                 frame_state, effect, control);
      MergeControlToEnd(graph(), common(), control);
    }
    return Replace(dead());
  }
  return UpdateStatesHelper(node, conditions, condition, node,
                            condition_is_true, false);
}
References common(), v8::internal::DCHECK(), dead(), v8::internal::compiler::DeoptimizeParametersOf(), v8::internal::compiler::DeoptimizeParameters::feedback(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::BranchCondition::is_true, v8::internal::compiler::BranchCondition::IsSet(), v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::LookupState(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::DeoptimizeParameters::reason(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and UpdateStatesHelper().
Referenced by Reduce().
ReduceIf()
Reduction v8::internal::compiler::BranchElimination::ReduceIf (Node * node, bool is_true_branch) [private]
Definition at line 331 of file branch-elimination.cc.
                                                                     {
  // Add the condition to the list arriving from the input branch.
  Node* branch = NodeProperties::GetControlInput(node, 0);
  ControlPathConditions from_branch = GetState(branch);
  // If we do not know anything about the predecessor, do not propagate just
  // yet because we will have to recompute anyway once we compute the
  // predecessor.
  if (!IsReduced(branch)) {
    return NoChange();
  }
  Node* condition = branch->InputAt(0);
  return UpdateStatesHelper(node, from_branch, condition, branch,
                            is_true_branch, true);
}
References v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::Node::InputAt(), and UpdateStatesHelper().
Referenced by Reduce().
ReduceLoop()
Reduction v8::internal::compiler::BranchElimination::ReduceLoop (Node * node) [private]
Definition at line 346 of file branch-elimination.cc.
                                                  {
  // Here we rely on having only reducible loops:
  // The loop entry edge always dominates the header, so we can just use
  // the information from the loop entry edge.
  return TakeStatesFromFirstControl(node);
}
Referenced by Reduce().
ReduceMerge()
Reduction v8::internal::compiler::BranchElimination::ReduceMerge (Node * node) [private]
Definition at line 353 of file branch-elimination.cc.
                                                   {
  // Shortcut for the case when we do not know anything about some
  // input.
  Node::Inputs inputs = node->inputs();
  for (Node* input : inputs) {
    if (!IsReduced(input)) {
      return NoChange();
    }
  }
  auto input_it = inputs.begin();
  DCHECK_GT(inputs.count(), 0);
  ControlPathConditions conditions = GetState(*input_it);
  ++input_it;
  // Merge the first input's conditions with the conditions from the other
  // inputs.
  auto input_end = inputs.end();
  for (; input_it != input_end; ++input_it) {
    // Change the current condition block list to a longest common tail of this
    // condition list and the other list. (The common tail should correspond to
    // the list from the common dominator.)
    conditions.ResetToCommonAncestor(GetState(*input_it));
  }
  return UpdateStates(node, conditions);
}
References DCHECK_GT, v8::internal::compiler::Node::inputs(), v8::internal::compiler::Node::Inputs(), and v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::ResetToCommonAncestor().
Referenced by Reduce().
ReduceOtherControl()
Reduction v8::internal::compiler::BranchElimination::ReduceOtherControl (Node * node) [private]
Definition at line 385 of file branch-elimination.cc.
                                                          {
  DCHECK_EQ(1, node->op()->ControlInputCount());
  return TakeStatesFromFirstControl(node);
}
References v8::internal::compiler::Operator::ControlInputCount(), DCHECK_EQ, and v8::internal::compiler::Node::op().
Referenced by Reduce().
reducer_name()
const char* v8::internal::compiler::BranchElimination::reducer_name () const [inline], [override]
Definition at line 56 of file branch-elimination.h.
{ return "BranchElimination"; }
ReduceStart()
Reduction v8::internal::compiler::BranchElimination::ReduceStart (Node * node) [private]
Definition at line 381 of file branch-elimination.cc.
                                                   {
  return UpdateStates(node, ControlPathConditions(zone()));
}
Referenced by Reduce().
ReduceTrapConditional()
Reduction v8::internal::compiler::BranchElimination::ReduceTrapConditional (Node * node) [private]
Definition at line 260 of file branch-elimination.cc.
                                                             {
  DCHECK(node->opcode() == IrOpcode::kTrapIf ||
         node->opcode() == IrOpcode::kTrapUnless);
  bool trapping_condition = node->opcode() == IrOpcode::kTrapIf;
  Node* condition = node->InputAt(0);
  Node* control_input = NodeProperties::GetControlInput(node, 0);
  // If we do not know anything about the predecessor, do not propagate just
  // yet because we will have to recompute anyway once we compute the
  // predecessor.
  if (!IsReduced(control_input)) return NoChange();
  ControlPathConditions from_input = GetState(control_input);
  BranchCondition branch_condition = from_input.LookupState(condition);
  if (branch_condition.IsSet()) {
    bool condition_value = branch_condition.is_true;
    if (condition_value == trapping_condition) {
      // This will always trap. Mark its outputs as dead and connect it to
      // graph()->end().
      ReplaceWithValue(node, dead(), dead(), dead());
      Node* control = graph()->NewNode(common()->Throw(), node, node);
      MergeControlToEnd(graph(), common(), control);
      return Changed(node);
    } else {
      // This will not trap, remove it by relaxing effect/control.
      RelaxEffectsAndControls(node);
      Node* control = NodeProperties::GetControlInput(node);
      node->Kill();
      return Replace(control); // Irrelevant argument
    }
  }
  return UpdateStatesHelper(node, from_input, condition, node,
                            !trapping_condition, false);
}
References common(), v8::internal::DCHECK(), dead(), v8::internal::compiler::NodeProperties::GetControlInput(), graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::BranchCondition::is_true, v8::internal::compiler::BranchCondition::IsSet(), v8::internal::compiler::Node::Kill(), v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::LookupState(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and UpdateStatesHelper().
Referenced by Reduce().
SimplifyBranchCondition()
void v8::internal::compiler::BranchElimination::SimplifyBranchCondition (Node * branch) [private]
Definition at line 58 of file branch-elimination.cc.
                                                            {
  // Try to use a phi as a branch condition if the control flow from the branch
  // is known from previous branches. For example, in the graph below, the
  // control flow of the second_branch is predictable because the first_branch
  // use the same branch condition. In such case, create a new phi with constant
  // inputs and let the second branch use the phi as its branch condition. From
  // this transformation, more branch folding opportunities would be exposed to
  // later passes through branch cloning in effect-control-linearizer.
  //
  // condition condition
  // | \ |
  // | first_branch first_branch
  // | / \ / \
  // | / \ / \
  // |first_true first_false first_true first_false
  // | \ / \ /
  // | \ / \ /
  // | first_merge ==> first_merge
  // | | / |
  // second_branch 1 0 / |
  // / \ \ | / |
  // / \ phi |
  // second_true second_false \ |
  // second_branch
  // / \
  // / \
  // second_true second_false
  //
  auto SemanticsOf = [phase = this->phase_](Node* branch) {
    BranchSemantics semantics = BranchSemantics::kUnspecified;
    if (branch->opcode() == IrOpcode::kBranch) {
      semantics = BranchParametersOf(branch->op()).semantics();
    }
    if (semantics == BranchSemantics::kUnspecified) {
      semantics =
          (phase == kEARLY ? BranchSemantics::kJS : BranchSemantics::kMachine);
    }
    return semantics;
  };
  DCHECK_EQ(IrOpcode::kBranch, branch->opcode());
  Node* merge = NodeProperties::GetControlInput(branch);
  if (merge->opcode() != IrOpcode::kMerge) return;
  Node* condition = branch->InputAt(0);
  BranchSemantics semantics = SemanticsOf(branch);
  TFGraph* graph = jsgraph()->graph();
  base::SmallVector<Node*, 2> phi_inputs;
  Node::Inputs inputs = merge->inputs();
  int input_count = inputs.count();
  for (int i = 0; i != input_count; ++i) {
    Node* input = inputs[i];
    ControlPathConditions from_input = GetState(input);
    BranchCondition branch_condition = from_input.LookupState(condition);
    if (!branch_condition.IsSet()) return;
    if (SemanticsOf(branch_condition.branch) != semantics) return;
    bool condition_value = branch_condition.is_true;
    if (semantics == BranchSemantics::kJS) {
      phi_inputs.emplace_back(jsgraph()->BooleanConstant(condition_value));
    } else {
      DCHECK_EQ(semantics, BranchSemantics::kMachine);
      phi_inputs.emplace_back(
          condition_value
              ? graph->NewNode(jsgraph()->common()->Int32Constant(1))
              : graph->NewNode(jsgraph()->common()->Int32Constant(0)));
    }
  }
  phi_inputs.emplace_back(merge);
  Node* new_phi =
      graph->NewNode(common()->Phi(semantics == BranchSemantics::kJS
                                       ? MachineRepresentation::kTagged
                                       : MachineRepresentation::kWord32,
                                   input_count),
                     input_count + 1, &phi_inputs.at(0));
  // Replace the branch condition with the new phi.
  NodeProperties::ReplaceValueInput(branch, new_phi, 0);
}
References v8::base::SmallVector< T, kSize, Allocator >::at(), v8::internal::compiler::BranchCondition::branch, v8::internal::compiler::BranchParametersOf(), common(), DCHECK_EQ, v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::internal::compiler::NodeProperties::GetControlInput(), graph(), v8::internal::compiler::MachineGraph::graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::inputs(), v8::internal::compiler::Node::Inputs(), v8::internal::compiler::BranchCondition::is_true, v8::internal::compiler::BranchCondition::IsSet(), jsgraph(), v8::internal::compiler::turboshaft::kBranch, kEARLY, v8::internal::compiler::kJS, v8::internal::compiler::kMachine, v8::internal::kTagged, v8::internal::compiler::kUnspecified, v8::internal::kWord32, v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::LookupState(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), phase_, v8::internal::compiler::NodeProperties::ReplaceValueInput(), and v8::internal::compiler::BranchParameters::semantics().
Referenced by ReduceBranch().
TryEliminateBranchWithPhiCondition()
bool v8::internal::compiler::BranchElimination::TryEliminateBranchWithPhiCondition (Node * branch, Node * phi, Node * merge) [private]
Definition at line 141 of file branch-elimination.cc.
                                                                        {
  // If the condition of the branch comes from two constant values,
  // then try to merge the branches successors into its predecessors,
  // and eliminate the (branch, phi, merge) nodes.
  //
  // pred0 pred1
  // \ /
  // merge 0 1
  // | \___________ | /
  // | \ | / pred0 pred1
  // | phi | |
  // | _____________/ => | |
  // | / | |
  // branch succ0 succ1
  // / \
  // false true
  // | |
  // succ0 succ1
  //
  DCHECK_EQ(branch->opcode(), IrOpcode::kBranch);
  DCHECK_EQ(phi->opcode(), IrOpcode::kPhi);
  DCHECK_EQ(merge->opcode(), IrOpcode::kMerge);
  DCHECK_EQ(NodeProperties::GetControlInput(branch, 0), merge);
  if (!phi->OwnedBy(branch)) return false;
  if (phi->InputCount() != 3) return false;
  if (phi->InputAt(2) != merge) return false;
  if (merge->UseCount() != 2) return false;
  Node::Inputs phi_inputs = phi->inputs();
  Node* first_value = phi_inputs[0];
  Node* second_value = phi_inputs[1];
  if (first_value->opcode() != IrOpcode::kInt32Constant ||
      second_value->opcode() != IrOpcode::kInt32Constant) {
    return false;
  }
  Node::Inputs merge_inputs = merge->inputs();
  Node* predecessor0 = merge_inputs[0];
  Node* predecessor1 = merge_inputs[1];
  DCHECK_EQ(branch->op()->ControlOutputCount(), 2);
  Node** projections = zone()->AllocateArray<Node*>(2);
  NodeProperties::CollectControlProjections(branch, projections, 2);
  Node* branch_true = projections[0];
  Node* branch_false = projections[1];
  DCHECK_EQ(branch_true->opcode(), IrOpcode::kIfTrue);
  DCHECK_EQ(branch_false->opcode(), IrOpcode::kIfFalse);
  // The input values of phi should be true(1) and false(0).
  Int32Matcher mfirst_value(first_value);
  Int32Matcher msecond_value(second_value);
  Node* predecessor_true = nullptr;
  Node* predecessor_false = nullptr;
  if (mfirst_value.Is(1) && msecond_value.Is(0)) {
    predecessor_true = predecessor0;
    predecessor_false = predecessor1;
  } else if (mfirst_value.Is(0) && msecond_value.Is(1)) {
    predecessor_true = predecessor1;
    predecessor_false = predecessor0;
  } else {
    return false;
  }
  // Merge the branches successors into its predecessors.
  for (Edge edge : branch_true->use_edges()) {
    edge.UpdateTo(predecessor_true);
  }
  for (Edge edge : branch_false->use_edges()) {
    edge.UpdateTo(predecessor_false);
  }
  branch_true->Kill();
  branch_false->Kill();
  branch->Kill();
  phi->Kill();
  merge->Kill();
  return true;
}
References v8::internal::compiler::NodeProperties::CollectControlProjections(), v8::internal::compiler::Operator::ControlOutputCount(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::Node::inputs(), v8::internal::compiler::Node::Inputs(), v8::internal::compiler::IntMatcher< T, kOpcode >::Is(), v8::internal::compiler::turboshaft::kBranch, v8::internal::compiler::Node::Kill(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::OwnedBy(), v8::internal::compiler::Node::use_edges(), and v8::internal::compiler::Node::UseCount().
Referenced by ReduceBranch().
UpdateStatesHelper()
Reduction v8::internal::compiler::BranchElimination::UpdateStatesHelper (Node * node, ControlPathConditions prev_conditions, Node * current_condition, Node * current_branch, bool is_true_branch, bool in_new_block) [inline], [private]
Definition at line 74 of file branch-elimination.h.
                                                                       {
    return UpdateStates(
        node, prev_conditions, current_condition,
        BranchCondition(current_condition, current_branch, is_true_branch),
        in_new_block);
  }
Referenced by ReduceDeoptimizeConditional(), ReduceIf(), and ReduceTrapConditional().
Member Data Documentation
dead_
Node* v8::internal::compiler::BranchElimination::dead_ [private]
Definition at line 92 of file branch-elimination.h.
jsgraph_
JSGraph* const v8::internal::compiler::BranchElimination::jsgraph_ [private]
Definition at line 90 of file branch-elimination.h.
phase_
Phase v8::internal::compiler::BranchElimination::phase_ [private]
Definition at line 93 of file branch-elimination.h.
Referenced by SimplifyBranchCondition().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/branch-elimination.h
/mnt/V8SourceCode/src/compiler/branch-elimination.cc