v8::internal::AllocationMemento Class Reference
#include <allocation-site.h>
Public Member Functions
void set_allocation_site (Tagged< AllocationSite > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
bool IsValid () const
Tagged< AllocationSite > GetAllocationSite () const
Address GetAllocationSiteUnchecked () const
Private Attributes
TaggedMember< AllocationSite > allocation_site_
Friends
class CodeStubAssembler
class TorqueGeneratedAllocationMementoAsserts
Additional Inherited Members
Detailed Description
Definition at line 190 of file allocation-site.h.
Member Function Documentation
GetAllocationSite()
Tagged< AllocationSite > v8::internal::AllocationMemento::GetAllocationSite () const [inline]
Definition at line 239 of file allocation-site-inl.h.
                                                                         {
  DCHECK(IsValid());
  return allocation_site_.load();
}
References allocation_site_, v8::internal::DCHECK(), and IsValid().
GetAllocationSiteUnchecked()
Address v8::internal::AllocationMemento::GetAllocationSiteUnchecked () const [inline]
Definition at line 244 of file allocation-site-inl.h.
                                                                   {
  return allocation_site_.load().ptr();
}
References allocation_site_.
IsValid()
bool v8::internal::AllocationMemento::IsValid () const [inline]
Definition at line 231 of file allocation-site-inl.h.
                                             {
  return !allocation_site_.load()->IsZombie();
}
References allocation_site_.
Referenced by GetAllocationSite().
set_allocation_site()
void v8::internal::AllocationMemento::set_allocation_site (Tagged< AllocationSite > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 235 of file allocation-site-inl.h.
                                                                   {
  allocation_site_.store(this, value, mode);
}
References allocation_site_, mode(), and v8::internal::value.
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 203 of file allocation-site.h.
TorqueGeneratedAllocationMementoAsserts
friend class TorqueGeneratedAllocationMementoAsserts [friend]
Definition at line 204 of file allocation-site.h.
Member Data Documentation
allocation_site_
TaggedMember<AllocationSite> v8::internal::AllocationMemento::allocation_site_ [private]
Definition at line 206 of file allocation-site.h.
Referenced by GetAllocationSite(), GetAllocationSiteUnchecked(), IsValid(), and set_allocation_site().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/allocation-site.h
/mnt/V8SourceCode/src/objects/allocation-site-inl.h