cppgc::internal::NormalPageMemoryPool Class Reference
#include <page-memory.h>
Classes
struct PooledPageMemoryRegion
Public Member Functions
void Add (PageMemoryRegion *)
PageMemoryRegion * Take ()
size_t pooled () const
size_t PooledMemory () const
void ReleasePooledPages (PageAllocator &allocator)
auto & get_raw_pool_for_testing ()
void SetDecommitPooledPages (bool value)
Static Public Attributes
static constexpr bool kDefaultDecommitPooledPage = false
Private Attributes
std::vector< PooledPageMemoryRegion > pool_
bool decommit_pooled_pages_ = kDefaultDecommitPooledPage
Detailed Description
Definition at line 96 of file page-memory.h.
Member Function Documentation
Add()
void cppgc::internal::NormalPageMemoryPool::Add (PageMemoryRegion * pmr)
Definition at line 115 of file page-memory.cc.
                                                    {
  DCHECK_NOT_NULL(pmr);
  DCHECK_EQ(pmr->region().size(), kPageSize);
  // Oilpan requires the pages to be zero-initialized.
  {
    void* base = pmr->region().base();
    const size_t size = pmr->region().size();
    AsanUnpoisonScope unpoison_for_memset(base, size);
    std::memset(base, 0, size);
  }
  pool_.emplace_back(PooledPageMemoryRegion(pmr));
}
References cppgc::internal::MemoryRegion::base(), DCHECK_EQ, DCHECK_NOT_NULL, cppgc::internal::kPageSize, pool_, cppgc::internal::PageMemoryRegion::region(), cppgc::internal::MemoryRegion::size(), and size().
Referenced by cppgc::internal::PageBackend::FreeNormalPageMemory().
get_raw_pool_for_testing()
auto& cppgc::internal::NormalPageMemoryPool::get_raw_pool_for_testing () [inline]
Definition at line 111 of file page-memory.h.
{ return pool_; }
pooled()
size_t cppgc::internal::NormalPageMemoryPool::pooled () const [inline]
Definition at line 104 of file page-memory.h.
{ return pool_.size(); }
Referenced by cppgc::internal::Sweeper::SweeperImpl::SweepForNormalAllocation().
PooledMemory()
size_t cppgc::internal::NormalPageMemoryPool::PooledMemory () const
Definition at line 163 of file page-memory.cc.
                                                {
  size_t total_size = 0;
  for (auto& entry : pool_) {
    if (entry.is_decommitted || entry.is_discarded) {
      continue;
    }
    total_size += entry.region->region().size();
  }
  return total_size;
}
References pool_.
ReleasePooledPages()
void cppgc::internal::NormalPageMemoryPool::ReleasePooledPages (PageAllocator & allocator)
Definition at line 174 of file page-memory.cc.
                                                                           {
  for (auto& entry : pool_) {
    DCHECK_NOT_NULL(entry.region);
    void* base = entry.region->region().base();
    size_t size = entry.region->region().size();
    // Unpoison the memory before giving back to the OS.
    ASAN_UNPOISON_MEMORY_REGION(base, size);
    if (decommit_pooled_pages_) {
      if (entry.is_decommitted) {
        continue;
      }
      CHECK(page_allocator.DecommitPages(base, size));
      entry.is_decommitted = true;
    } else {
      if (entry.is_discarded) {
        continue;
      }
      CHECK(TryDiscard(page_allocator, entry.region->region()));
      entry.is_discarded = true;
    }
  }
}
References ASAN_UNPOISON_MEMORY_REGION, CHECK, DCHECK_NOT_NULL, decommit_pooled_pages_, v8::PageAllocator::DecommitPages(), pool_, size(), and cppgc::internal::anonymous_namespace{page-memory.cc}::TryDiscard().
Referenced by cppgc::internal::PageBackend::ReleasePooledPages().
SetDecommitPooledPages()
void cppgc::internal::NormalPageMemoryPool::SetDecommitPooledPages (bool value) [inline]
Definition at line 113 of file page-memory.h.
{ decommit_pooled_pages_ = value; }
References v8::internal::value.
Take()
PageMemoryRegion * cppgc::internal::NormalPageMemoryPool::Take ()
Definition at line 128 of file page-memory.cc.
                                             {
  if (pool_.empty()) return nullptr;
  PooledPageMemoryRegion entry = pool_.back();
  DCHECK_NOT_NULL(entry.region);
  pool_.pop_back();
  void* base = entry.region->region().base();
  const size_t size = entry.region->region().size();
  ASAN_UNPOISON_MEMORY_REGION(base, size);
  DCHECK_IMPLIES(!decommit_pooled_pages_, !entry.is_decommitted);
  if (entry.is_decommitted) {
    // Also need to make the pages accessible.
    CHECK(entry.region->allocator().RecommitPages(
        base, size, v8::PageAllocator::kReadWrite));
    bool ok = entry.region->allocator().SetPermissions(
        base, size, v8::PageAllocator::kReadWrite);
    if (!ok) {
#if V8_OS_POSIX
      // Changing permissions can return ENOMEM in several cases, including
      // (since there is PROT_WRITE) when it would exceed the RLIMIT_DATA
      // resource limit, at least on Linux. Check errno in this case, and
      // declare that this is an OOM in this case.
      if (errno == ENOMEM) {
        GetGlobalOOMHandler()("Cannot change page permissions");
      }
#endif
      CHECK(false);
    }
  }
#if DEBUG
  CheckMemoryIsZero(base, size);
#endif
  return entry.region;
}
References cppgc::internal::PageMemoryRegion::allocator(), ASAN_UNPOISON_MEMORY_REGION, cppgc::internal::MemoryRegion::base(), CHECK, cppgc::internal::CheckMemoryIsZero(), DCHECK_IMPLIES, DCHECK_NOT_NULL, decommit_pooled_pages_, cppgc::internal::GetGlobalOOMHandler(), cppgc::internal::NormalPageMemoryPool::PooledPageMemoryRegion::is_decommitted, v8::PageAllocator::kReadWrite, pool_, v8::PageAllocator::RecommitPages(), cppgc::internal::PageMemoryRegion::region(), cppgc::internal::NormalPageMemoryPool::PooledPageMemoryRegion::region, v8::PageAllocator::SetPermissions(), cppgc::internal::MemoryRegion::size(), and size().
Referenced by cppgc::internal::PageBackend::TryAllocateNormalPageMemory().
Member Data Documentation
decommit_pooled_pages_
bool cppgc::internal::NormalPageMemoryPool::decommit_pooled_pages_ = kDefaultDecommitPooledPage [private]
Definition at line 129 of file page-memory.h.
Referenced by ReleasePooledPages(), and Take().
kDefaultDecommitPooledPage
constexpr bool cppgc::internal::NormalPageMemoryPool::kDefaultDecommitPooledPage = false [static], [constexpr]
Definition at line 114 of file page-memory.h.
pool_
std::vector<PooledPageMemoryRegion> cppgc::internal::NormalPageMemoryPool::pool_ [private]
Definition at line 128 of file page-memory.h.
Referenced by Add(), PooledMemory(), ReleasePooledPages(), and Take().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/page-memory.h
/mnt/V8SourceCode/src/heap/cppgc/page-memory.cc