v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next > Class Template Reference
#include <wasm-js-lowering-reducer.h>
Public Member Functions
V< None > REDUCE() TrapIf (V< Word32 > condition, OptionalV< FrameState > frame_state, bool negated, TrapId trap_id)
Private Member Functions
OpIndex CreateFrameStateWithUpdatedBailoutId (V< FrameState > frame_state)
Private Attributes
Isolate * isolate_ = __ data() -> isolate()
SourcePositionTable * source_positions_ = __ data() -> source_positions()
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >
Definition at line 27 of file wasm-js-lowering-reducer.h.
Member Function Documentation
CreateFrameStateWithUpdatedBailoutId()
template<class Next >
OpIndex v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >::CreateFrameStateWithUpdatedBailoutId (V< FrameState > frame_state) [inline], [private]
Definition at line 60 of file wasm-js-lowering-reducer.h.
                                                                          {
    // Create new FrameState with the correct source position (the position of
    // the trap location).
    const FrameStateOp& frame_state_op =
        Asm().output_graph().Get(frame_state).template Cast<FrameStateOp>();
    const FrameStateData* data = frame_state_op.data;
    const FrameStateInfo& info = data->frame_state_info;
    V<AnyOrNone> origin = Asm().current_operation_origin();
    DCHECK(origin.valid());
    int offset = __ input_graph().source_positions()[origin].ScriptOffset();
    const FrameStateInfo* new_info =
        Asm().graph_zone()->template New<FrameStateInfo>(
            BytecodeOffset(offset), info.state_combine(), info.function_info());
    FrameStateData* new_data = Asm().graph_zone()->template New<FrameStateData>(
        FrameStateData{*new_info, data->instructions, data->machine_types,
                       data->int_operands});
    return __ FrameState(frame_state_op.inputs(), frame_state_op.inlined,
                         new_data);
  }
References __, v8::internal::compiler::turboshaft::FrameStateOp::data, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::FrameStateData::frame_state_info, v8::internal::compiler::FrameStateInfo::function_info(), v8::internal::compiler::turboshaft::FrameStateOp::inlined, v8::internal::compiler::turboshaft::OperationT< Derived >::inputs(), v8::internal::compiler::turboshaft::FrameStateData::instructions, v8::internal::compiler::turboshaft::FrameStateData::int_operands, v8::internal::compiler::turboshaft::FrameStateData::machine_types, v8::internal::compiler::FrameStateInfo::state_combine(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >::TrapIf().
TrapIf()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >::TrapIf (V< Word32 > condition, OptionalV< FrameState > frame_state, bool negated, TrapId trap_id) [inline]
Definition at line 31 of file wasm-js-lowering-reducer.h.
                                                       {
    // All TrapIf nodes in JS need to have a FrameState.
    DCHECK(frame_state.valid());
    Builtin trap = static_cast<Builtin>(trap_id);
    // The call is not marked as Operator::kNoDeopt. While it cannot actually
    // deopt, deopt info based on the provided FrameState is required for stack
    // trace creation of the wasm trap.
    const bool needs_frame_state = true;
    const CallDescriptor* tf_descriptor = GetBuiltinCallDescriptor(
        trap, Asm().graph_zone(), StubCallMode::kCallBuiltinPointer,
        needs_frame_state, Operator::kNoProperties);
    const TSCallDescriptor* ts_descriptor =
        TSCallDescriptor::Create(tf_descriptor, CanThrow::kYes,
                                 LazyDeoptOnThrow::kNo, Asm().graph_zone());
    V<FrameState> new_frame_state =
        CreateFrameStateWithUpdatedBailoutId(frame_state.value());
    V<Word32> should_trap = negated ? __ Word32Equal(condition, 0) : condition;
    IF (UNLIKELY(should_trap)) {
      OpIndex call_target = __ NumberConstant(static_cast<int>(trap));
      __ Call(call_target, new_frame_state, {}, ts_descriptor);
      __ Unreachable(); // The trap builtin never returns.
    }
    return V<None>::Invalid();
  }
References __, v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >::CreateFrameStateWithUpdatedBailoutId(), v8::internal::DCHECK(), v8::internal::compiler::GetBuiltinCallDescriptor(), v8::internal::compiler::turboshaft::V< T >::Invalid(), v8::internal::kCallBuiltinPointer, v8::internal::compiler::kNo, v8::internal::compiler::Operator::kNoProperties, v8::internal::compiler::kYes, v8::internal::compiler::NumberConstant(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Member Data Documentation
isolate_
template<class Next >
Isolate* v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >::isolate_ = __ data() -> isolate() [private]
Definition at line 82 of file wasm-js-lowering-reducer.h.
source_positions_
template<class Next >
SourcePositionTable* v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >::source_positions_ = __ data() -> source_positions() [private]
Definition at line 83 of file wasm-js-lowering-reducer.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-js-lowering-reducer.h