v8::internal::FrameSummary::JavaScriptFrameSummary Class Reference
#include <frames.h>
Public Member Functions
JavaScriptFrameSummary (Isolate *isolate, Tagged< Object > receiver, Tagged< JSFunction > function, Tagged< AbstractCode > abstract_code, int code_offset, bool is_constructor, Tagged< FixedArray > parameters)
void EnsureSourcePositionsAvailable ()
bool AreSourcePositionsAvailable () const
Handle< Object > receiver () const
Handle< JSFunction > function () const
Handle< AbstractCode > abstract_code () const
int code_offset () const
bool is_constructor () const
DirectHandle< FixedArray > parameters () const
bool is_subject_to_debugging () const
int SourcePosition () const
int SourceStatementPosition () const
Handle< Object > script () const
DirectHandle< Context > native_context () const
DirectHandle< StackFrameInfo > CreateStackFrameInfo () const
Private Attributes
Handle< Object > receiver_
Handle< JSFunction > function_
Handle< AbstractCode > abstract_code_
int code_offset_
bool is_constructor_
Handle< FixedArray > parameters_
Detailed Description
Definition at line 435 of file frames.h.
Constructor & Destructor Documentation
JavaScriptFrameSummary()
v8::internal::FrameSummary::JavaScriptFrameSummary::JavaScriptFrameSummary (Isolate * isolate, Tagged< Object > receiver, Tagged< JSFunction > function, Tagged< AbstractCode > abstract_code, int code_offset, bool is_constructor, Tagged< FixedArray > parameters)
Definition at line 2688 of file frames.cc.
    : FrameSummaryBase(isolate, FrameSummary::JAVASCRIPT),
      receiver_(receiver, isolate),
      function_(function, isolate),
      abstract_code_(abstract_code, isolate),
      code_offset_(code_offset),
      is_constructor_(is_constructor),
      parameters_(parameters, isolate) {
  DCHECK_IMPLIES(CodeKindIsOptimizedJSFunction(abstract_code->kind(isolate)),
                 // It might be an ApiCallbackBuiltin inlined into optimized
                 // code generated by Maglev.
                 (v8_flags.maglev_inline_api_calls &&
                  abstract_code->kind(isolate) == CodeKind::MAGLEV &&
                  function->shared()->IsApiFunction()));
}
References abstract_code(), v8::internal::CodeKindIsOptimizedJSFunction(), DCHECK_IMPLIES, function(), v8::internal::FrameSummary::FrameSummaryBase::isolate(), v8::internal::JAVASCRIPT, and v8::internal::v8_flags.
Member Function Documentation
abstract_code()
Handle<AbstractCode> v8::internal::FrameSummary::JavaScriptFrameSummary::abstract_code () const [inline]
Definition at line 447 of file frames.h.
{ return abstract_code_; }
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendJavaScriptFrame(), and JavaScriptFrameSummary().
AreSourcePositionsAvailable()
bool v8::internal::FrameSummary::JavaScriptFrameSummary::AreSourcePositionsAvailable () const
Definition at line 2725 of file frames.cc.
                                                                           {
  return !v8_flags.enable_lazy_source_positions ||
         function()
             ->shared()
             ->GetBytecodeArray(isolate())
             ->HasSourcePositionTable();
}
References v8::internal::v8_flags.
code_offset()
int v8::internal::FrameSummary::JavaScriptFrameSummary::code_offset () const [inline]
Definition at line 448 of file frames.h.
{ return code_offset_; }
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendJavaScriptFrame(), and v8::internal::wasm::gdb_server::WasmModuleDebug::GetCallStack().
CreateStackFrameInfo()
DirectHandle< StackFrameInfo > v8::internal::FrameSummary::JavaScriptFrameSummary::CreateStackFrameInfo () const
Definition at line 2755 of file frames.cc.
                                                               {
  DirectHandle<SharedFunctionInfo> shared(function_->shared(), isolate());
  DirectHandle<Script> script(Cast<Script>(shared->script()), isolate());
  DirectHandle<String> function_name =
      JSFunction::GetDebugName(isolate(), function_);
  if (function_name->length() == 0 &&
      script->compilation_type() == Script::CompilationType::kEval) {
    function_name = isolate()->factory()->eval_string();
  }
  int bytecode_offset = code_offset();
  if (bytecode_offset == kFunctionEntryBytecodeOffset) {
    // For the special function entry bytecode offset (-1), which signals
    // that the stack trace was captured while the function entry was
    // executing (i.e. during the interrupt check), we cannot store this
    // sentinel in the bit field, so we just eagerly lookup the source
    // position within the script.
    SharedFunctionInfo::EnsureSourcePositionsAvailable(isolate(), shared);
    int source_position =
        abstract_code()->SourcePosition(isolate(), bytecode_offset);
    return isolate()->factory()->NewStackFrameInfo(
        script, source_position, function_name, is_constructor());
  }
  return isolate()->factory()->NewStackFrameInfo(
      shared, bytecode_offset, function_name, is_constructor());
}
References v8::internal::FrameSummary::code_offset(), v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), v8::internal::JSFunction::GetDebugName(), v8::internal::FrameSummary::is_constructor(), v8::internal::Script::kEval, v8::internal::kFunctionEntryBytecodeOffset, and v8::internal::FrameSummary::script().
EnsureSourcePositionsAvailable()
void v8::internal::FrameSummary::JavaScriptFrameSummary::EnsureSourcePositionsAvailable ()
Definition at line 2720 of file frames.cc.
                                                                        {
  DirectHandle<SharedFunctionInfo> shared(function()->shared(), isolate());
  SharedFunctionInfo::EnsureSourcePositionsAvailable(isolate(), shared);
}
References v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable().
function()
Handle<JSFunction> v8::internal::FrameSummary::JavaScriptFrameSummary::function () const [inline]
Definition at line 446 of file frames.h.
{ return function_; }
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendJavaScriptFrame(), and JavaScriptFrameSummary().
is_constructor()
bool v8::internal::FrameSummary::JavaScriptFrameSummary::is_constructor () const [inline]
Definition at line 449 of file frames.h.
{ return is_constructor_; }
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendJavaScriptFrame().
is_subject_to_debugging()
bool v8::internal::FrameSummary::JavaScriptFrameSummary::is_subject_to_debugging () const
Definition at line 2733 of file frames.cc.
                                                                       {
  return function()->shared()->IsSubjectToDebugging();
}
native_context()
DirectHandle< Context > v8::internal::FrameSummary::JavaScriptFrameSummary::native_context () const
Definition at line 2749 of file frames.cc.
          {
  return direct_handle(function_->native_context(), isolate());
}
References v8::internal::direct_handle().
parameters()
DirectHandle<FixedArray> v8::internal::FrameSummary::JavaScriptFrameSummary::parameters () const [inline]
Definition at line 450 of file frames.h.
{ return parameters_; }
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendJavaScriptFrame().
receiver()
Handle<Object> v8::internal::FrameSummary::JavaScriptFrameSummary::receiver () const [inline]
Definition at line 445 of file frames.h.
{ return receiver_; }
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendJavaScriptFrame().
script()
Handle< Object > v8::internal::FrameSummary::JavaScriptFrameSummary::script () const
Definition at line 2745 of file frames.cc.
                                                                {
  return handle(function_->shared()->script(), isolate());
}
References v8::internal::handle().
Referenced by v8::internal::wasm::gdb_server::WasmModuleDebug::GetCallStack().
SourcePosition()
int v8::internal::FrameSummary::JavaScriptFrameSummary::SourcePosition () const
Definition at line 2737 of file frames.cc.
                                                             {
  return abstract_code()->SourcePosition(isolate(), code_offset());
}
References v8::internal::FrameSummary::code_offset().
SourceStatementPosition()
int v8::internal::FrameSummary::JavaScriptFrameSummary::SourceStatementPosition () const
Definition at line 2741 of file frames.cc.
                                                                      {
  return abstract_code()->SourceStatementPosition(isolate(), code_offset());
}
References v8::internal::FrameSummary::code_offset().
Member Data Documentation
abstract_code_
Handle<AbstractCode> v8::internal::FrameSummary::JavaScriptFrameSummary::abstract_code_ [private]
Definition at line 461 of file frames.h.
code_offset_
int v8::internal::FrameSummary::JavaScriptFrameSummary::code_offset_ [private]
Definition at line 462 of file frames.h.
function_
Handle<JSFunction> v8::internal::FrameSummary::JavaScriptFrameSummary::function_ [private]
Definition at line 460 of file frames.h.
is_constructor_
bool v8::internal::FrameSummary::JavaScriptFrameSummary::is_constructor_ [private]
Definition at line 463 of file frames.h.
parameters_
Handle<FixedArray> v8::internal::FrameSummary::JavaScriptFrameSummary::parameters_ [private]
Definition at line 464 of file frames.h.
receiver_
Handle<Object> v8::internal::FrameSummary::JavaScriptFrameSummary::receiver_ [private]
Definition at line 459 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames.cc