v8::internal::torque::cpp::Function Class Reference
#include <cpp-builder.h>
Classes
struct Parameter
Public Types
enum FunctionFlag
Public Member Functions
Function (std::string name)
Function (Class *owning_class, std::string name)
~Function ()=default
void SetFlag (FunctionFlag flag, bool value=true)
void SetFlags (base::Flags< FunctionFlag > flags, bool value=true)
bool HasFlag (FunctionFlag flag) const
void SetDescription (std::string description)
void SetName (std::string name)
void SetReturnType (std::string return_type)
void AddParameter (std::string type, std::string name={}, std::string default_value={})
void InsertParameter (int index, std::string type, std::string name={}, std::string default_value={})
std::vector< Parameter > GetParameters () const
std::vector< std::string > GetParameterNames () const
void PrintDeclaration (std::ostream &stream, int indentation=kAutomaticIndentation) const
void PrintDefinition (std::ostream &stream, const std::function< void(std::ostream &)> &builder, int indentation=0) const
void PrintInlineDefinition (std::ostream &stream, const std::function< void(std::ostream &)> &builder, int indentation=2) const
void PrintBeginDefinition (std::ostream &stream, int indentation=0) const
void PrintEndDefinition (std::ostream &stream, int indentation=0) const
Static Public Member Functions
static Function DefaultGetter (std::string return_type, Class *owner, std::string name)
static Function DefaultSetter (Class *owner, std::string name, std::string parameter_type, std::string parameter_name)
Static Public Attributes
static constexpr int kAutomaticIndentation = -1
Protected Member Functions
void PrintDeclarationHeader (std::ostream &stream, int indentation) const
Private Attributes
SourcePosition pos_
Class * owning_class_
std::string description_
std::string name_
std::string return_type_
std::vector< Parameter > parameters_
base::Flags< FunctionFlag > flags_
Detailed Description
Definition at line 53 of file cpp-builder.h.
Member Enumeration Documentation
FunctionFlag
enum v8::internal::torque::cpp::Function::FunctionFlag
Definition at line 55 of file cpp-builder.h.
                    {
#define ENTRY(name, value) k##name = value,
    FUNCTION_FLAG_LIST(ENTRY)
#undef ENTRY
  };
Constructor & Destructor Documentation
Function() [1/2]
v8::internal::torque::cpp::Function::Function (std::string name) [inline], [explicit]
Definition at line 73 of file cpp-builder.h.
      : pos_(CurrentSourcePosition::Get()),
        owning_class_(nullptr),
        name_(std::move(name)) {}
Function() [2/2]
v8::internal::torque::cpp::Function::Function (Class * owning_class, std::string name) [inline]
Definition at line 77 of file cpp-builder.h.
      : pos_(CurrentSourcePosition::Get()),
        owning_class_(owning_class),
        name_(std::move(name)) {}
 Function()
v8::internal::torque::cpp::Function::~Function () [default]
Member Function Documentation
AddParameter()
void v8::internal::torque::cpp::Function::AddParameter (std::string type, std::string name = {}, std::string default_value = {}) [inline]
Definition at line 130 of file cpp-builder.h.
                                                     {},
                    std::string default_value = {}) {
    parameters_.emplace_back(std::move(type), std::move(name),
                             std::move(default_value));
  }
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClass(), and v8::internal::torque::ImplementationVisitor::GenerateFunction().
DefaultGetter()
static Function v8::internal::torque::cpp::Function::DefaultGetter (std::string return_type, Class * owner, std::string name) [inline], [static]
Definition at line 83 of file cpp-builder.h.
                                                {
    Function getter(owner, std::move(name));
    getter.SetReturnType(std::move(return_type));
    getter.SetInline();
    getter.SetConst();
    return getter;
  }
References v8::internal::name, and SetReturnType().
DefaultSetter()
static Function v8::internal::torque::cpp::Function::DefaultSetter (Class * owner, std::string name, std::string parameter_type, std::string parameter_name) [inline], [static]
Definition at line 92 of file cpp-builder.h.
                                                          {
    Function setter(owner, std::move(name));
    setter.SetReturnType("void");
    setter.AddParameter(std::move(parameter_type), std::move(parameter_name));
    setter.SetInline();
    return setter;
  }
References v8::internal::name, and v8::internal::setter.
GetParameterNames()
std::vector<std::string> v8::internal::torque::cpp::Function::GetParameterNames () const [inline]
Definition at line 144 of file cpp-builder.h.
                                                 {
    std::vector<std::string> names;
    std::transform(parameters_.begin(), parameters_.end(),
                   std::back_inserter(names),
                   [](const Parameter& p) { return p.name; });
    return names;
  }
References parameters_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFunction().
GetParameters()
std::vector<Parameter> v8::internal::torque::cpp::Function::GetParameters () const [inline]
Definition at line 143 of file cpp-builder.h.
{ return parameters_; }
References parameters_.
HasFlag()
bool v8::internal::torque::cpp::Function::HasFlag (FunctionFlag flag) const [inline]
Definition at line 116 of file cpp-builder.h.
{ return (flags_ & flag) == flag; }
References flags_.
InsertParameter()
void v8::internal::torque::cpp::Function::InsertParameter (int index, std::string type, std::string name = {}, std::string default_value = {}) [inline]
Definition at line 135 of file cpp-builder.h.
                                                                   {},
                       std::string default_value = {}) {
    DCHECK_GE(index, 0);
    DCHECK_LE(index, parameters_.size());
    parameters_.insert(
        parameters_.begin() + index,
        Parameter(std::move(type), std::move(name), std::move(default_value)));
  }
PrintBeginDefinition()
void v8::internal::torque::cpp::Function::PrintBeginDefinition (std::ostream & stream, int indentation = 0) const
Definition at line 68 of file cpp-builder.cc.
                                                           {
  stream << std::string(indentation, ' ') << "// " << pos_ << "\n";
  std::string scope;
  if (owning_class_) {
    scope = owning_class_->GetName();
    const auto class_template_parameters =
        owning_class_->GetTemplateParameters();
    if (!class_template_parameters.empty()) {
      stream << std::string(indentation, ' ');
      stream << "template<";
      scope += "<";
      bool first = true;
      for (const auto& p : class_template_parameters) {
        if (!first) {
          stream << ", ";
          scope += ", ";
        }
        if (p.type.empty()) {
          stream << "class " << p.name;
        } else {
          stream << p.type << " " << p.name;
        }
        scope += p.name;
        first = false;
      }
      stream << ">\n";
      scope += ">";
    }
    scope += "::";
  }
  stream << std::string(indentation, ' ') << return_type_ << " " << scope
         << name_ << "(";
  bool first = true;
  for (const auto& p : parameters_) {
    if (!first) stream << ", ";
    stream << p.type;
    if (!p.name.empty()) stream << " " << p.name;
    first = false;
  }
  stream << ")";
  if (IsConst()) {
    stream << " const";
  }
  stream << " {\n";
}
References v8::internal::torque::cpp::Class::GetName(), v8::internal::torque::cpp::Class::GetTemplateParameters(), name_, owning_class_, parameters_, pos_, return_type_, and v8::internal::string.
Referenced by PrintDefinition(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
PrintDeclaration()
void v8::internal::torque::cpp::Function::PrintDeclaration (std::ostream & stream, int indentation = kAutomaticIndentation) const
Definition at line 39 of file cpp-builder.cc.
                                                                         {
  if (indentation == kAutomaticIndentation) {
    indentation = owning_class_ ? 2 : 0;
  }
  PrintDeclarationHeader(stream, indentation);
  stream << ";\n";
}
References kAutomaticIndentation, owning_class_, and PrintDeclarationHeader().
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClass(), v8::internal::torque::ImplementationVisitor::GenerateExportedMacrosAssembler(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
PrintDeclarationHeader()
void v8::internal::torque::cpp::Function::PrintDeclarationHeader (std::ostream & stream, int indentation) const [protected]
Definition at line 12 of file cpp-builder.cc.
                                                             {
  if (!description_.empty()) {
    stream << std::string(indentation, ' ') << "// " << description_ << "\n";
  }
  stream << std::string(indentation, ' ') << "// " << pos_ << "\n";
  stream << std::string(indentation, ' ');
  if (IsExport()) stream << "V8_EXPORT_PRIVATE ";
  if (IsV8Inline())
    stream << "V8_INLINE ";
  else if (IsInline())
    stream << "inline ";
  if (IsStatic()) stream << "static ";
  if (IsConstexpr()) stream << "constexpr ";
  stream << return_type_ << " " << name_ << "(";
  bool first = true;
  for (const auto& p : parameters_) {
    if (!first) stream << ", ";
    stream << p.type;
    if (!p.name.empty()) stream << " " << p.name;
    if (!p.default_value.empty()) stream << " = " << p.default_value;
    first = false;
  }
  stream << ")";
  if (IsConst()) stream << " const";
}
References description_, v8::internal::IsStatic(), name_, parameters_, pos_, return_type_, and v8::internal::string.
Referenced by PrintDeclaration(), and PrintInlineDefinition().
PrintDefinition()
void v8::internal::torque::cpp::Function::PrintDefinition (std::ostream & stream, const std::function< void(std::ostream &)> & builder, int indentation = 0) const
Definition at line 47 of file cpp-builder.cc.
                           {
  PrintBeginDefinition(stream, indentation);
  if (builder) {
    builder(stream);
  }
  PrintEndDefinition(stream, indentation);
}
References PrintBeginDefinition(), and PrintEndDefinition().
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClass(), v8::internal::torque::ImplementationVisitor::GenerateExportedMacrosAssembler(), and v8::internal::torque::ImplementationVisitor::Visit().
PrintEndDefinition()
void v8::internal::torque::cpp::Function::PrintEndDefinition (std::ostream & stream, int indentation = 0) const
Definition at line 115 of file cpp-builder.cc.
                                                                           {
  stream << std::string(indentation, ' ');
  stream << "}\n\n";
}
References v8::internal::string.
Referenced by PrintDefinition(), PrintInlineDefinition(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
PrintInlineDefinition()
void v8::internal::torque::cpp::Function::PrintInlineDefinition (std::ostream & stream, const std::function< void(std::ostream &)> & builder, int indentation = 2) const
Definition at line 57 of file cpp-builder.cc.
                           {
  PrintDeclarationHeader(stream, indentation);
  stream << " {\n";
  if (builder) {
    builder(stream);
  }
  PrintEndDefinition(stream, indentation);
}
References PrintDeclarationHeader(), and PrintEndDefinition().
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClass().
SetDescription()
void v8::internal::torque::cpp::Function::SetDescription (std::string description) [inline]
Definition at line 123 of file cpp-builder.h.
                                             {
    description_ = std::move(description);
  }
References description_.
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClass().
SetFlag()
void v8::internal::torque::cpp::Function::SetFlag (FunctionFlag flag, bool value = true) [inline]
Definition at line 102 of file cpp-builder.h.
                                                     {
    if (value) {
      flags_ = flags_ | flag;
    } else {
      flags_ = flags_.without(flag);
    }
  }
References flags_, v8::internal::value, and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::without().
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClass().
SetFlags()
void v8::internal::torque::cpp::Function::SetFlags (base::Flags< FunctionFlag > flags, bool value = true) [inline]
Definition at line 109 of file cpp-builder.h.
                                                                  {
    if (value) {
      flags_ |= flags;
    } else {
      flags_ &= ~flags;
    }
  }
References v8::internal::flags, flags_, and v8::internal::value.
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClass().
SetName()
void v8::internal::torque::cpp::Function::SetName (std::string name) [inline]
Definition at line 126 of file cpp-builder.h.
{ name_ = std::move(name); }
References v8::internal::name, and name_.
SetReturnType()
void v8::internal::torque::cpp::Function::SetReturnType (std::string return_type) [inline]
Definition at line 127 of file cpp-builder.h.
                                            {
    return_type_ = std::move(return_type);
  }
References return_type_.
Referenced by DefaultGetter(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClass(), and v8::internal::torque::ImplementationVisitor::GenerateFunction().
Member Data Documentation
description_
std::string v8::internal::torque::cpp::Function::description_ [private]
Definition at line 170 of file cpp-builder.h.
Referenced by PrintDeclarationHeader(), and SetDescription().
flags_
base::Flags<FunctionFlag> v8::internal::torque::cpp::Function::flags_ [private]
Definition at line 174 of file cpp-builder.h.
Referenced by HasFlag(), SetFlag(), and SetFlags().
kAutomaticIndentation
constexpr int v8::internal::torque::cpp::Function::kAutomaticIndentation = -1 [static], [constexpr]
Definition at line 152 of file cpp-builder.h.
Referenced by PrintDeclaration().
name_
std::string v8::internal::torque::cpp::Function::name_ [private]
Definition at line 171 of file cpp-builder.h.
Referenced by PrintBeginDefinition(), PrintDeclarationHeader(), and SetName().
owning_class_
Class* v8::internal::torque::cpp::Function::owning_class_ [private]
Definition at line 169 of file cpp-builder.h.
Referenced by PrintBeginDefinition(), and PrintDeclaration().
parameters_
std::vector<Parameter> v8::internal::torque::cpp::Function::parameters_ [private]
Definition at line 173 of file cpp-builder.h.
Referenced by GetParameterNames(), GetParameters(), PrintBeginDefinition(), and PrintDeclarationHeader().
pos_
SourcePosition v8::internal::torque::cpp::Function::pos_ [private]
Definition at line 168 of file cpp-builder.h.
Referenced by PrintBeginDefinition(), and PrintDeclarationHeader().
return_type_
std::string v8::internal::torque::cpp::Function::return_type_ [private]
Definition at line 172 of file cpp-builder.h.
Referenced by PrintBeginDefinition(), PrintDeclarationHeader(), and SetReturnType().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/cpp-builder.h
/mnt/V8SourceCode/src/torque/cpp-builder.cc