v8::internal::BuiltinsReducer< Next > Class Template Reference
#include <turboshaft-builtins-assembler-inl.h>
Public Types
using BuiltinArgumentsTS = detail::BuiltinArgumentsTS< assembler_t >
Public Member Functions
void EmitBuiltinProlog (Builtin builtin_id)
void EmitEpilog (Block *catch_block)
V< Context > JSContextParameter ()
void PerformStackCheck (V< Context > context)
void PopAndReturn (BuiltinArgumentsTS &arguments, compiler::turboshaft::V< Object > return_value)
V< Word32 > TruncateTaggedToWord32 (V< Context > context, V< Object > value)
V< Word32 > IsBigIntInstanceType (ConstOrV< Word32 > instance_type)
V< Word32 > IsSmallBigInt (V< BigInt > value)
V< Word32 > InstanceTypeEqual (ConstOrV< Word32 > instance_type, ConstOrV< Word32 > other_instance_type)
V< WordPtr > AlignTagged (V< WordPtr > size)
V< WordPtr > ElementOffsetFromIndex (ConstOrV< WordPtr > index, ElementsKind kind, intptr_t base_size)
std::optional< intptr_t > TryToIntPtrConstant (ConstOrV< WordPtr > index)
template<Object::Conversion Conversion>
void TaggedToWord32OrBigIntImpl (V< Context > context, V< Object > value, IsKnownTaggedPointer is_known_tagged_pointer, Label< Word32 > &if_number, Label< BigInt > *if_bigint=nullptr, Label< BigInt > *if_bigint64=nullptr)
Private Member Functions
Isolate * isolate ()
Private Attributes
compiler::turboshaft::OperationMatcher matcher_ {__ data()->graph()}
Detailed Description
template<typename Next>
class v8::internal::BuiltinsReducer< Next >
Definition at line 384 of file turboshaft-builtins-assembler-inl.h.
Member Typedef Documentation
BuiltinArgumentsTS
template<typename Next >
using v8::internal::BuiltinsReducer< Next >::BuiltinArgumentsTS = detail::BuiltinArgumentsTS<assembler_t>
Definition at line 388 of file turboshaft-builtins-assembler-inl.h.
Member Function Documentation
AlignTagged()
template<typename Next >
V<WordPtr> v8::internal::BuiltinsReducer< Next >::AlignTagged (V< WordPtr > size) [inline]
Definition at line 478 of file turboshaft-builtins-assembler-inl.h.
                                          {
    return __ WordPtrBitwiseAnd(__ WordPtrAdd(size, kObjectAlignmentMask),
                                ~kObjectAlignmentMask);
  }
References __, v8::internal::kObjectAlignmentMask, and size().
ElementOffsetFromIndex()
template<typename Next >
V<WordPtr> v8::internal::BuiltinsReducer< Next >::ElementOffsetFromIndex (ConstOrV< WordPtr > index, ElementsKind kind, intptr_t base_size) [inline]
Definition at line 483 of file turboshaft-builtins-assembler-inl.h.
                                                        {
    const int element_size_shift = ElementsKindToShiftSize(kind);
    if (std::optional<intptr_t> constant_index = TryToIntPtrConstant(index)) {
      return __ WordPtrConstant(base_size +
                                (1 << element_size_shift) * (*constant_index));
    }
    if (element_size_shift == 0) {
      return __ WordPtrAdd(base_size, index);
    } else {
      DCHECK_LT(0, element_size_shift);
      return __ WordPtrAdd(base_size,
                           __ WordPtrShiftLeft(index, element_size_shift));
    }
  }
References __, DCHECK_LT, v8::internal::ElementsKindToShiftSize(), v8::internal::index, and v8::internal::BuiltinsReducer< Next >::TryToIntPtrConstant().
EmitBuiltinProlog()
template<typename Next >
void v8::internal::BuiltinsReducer< Next >::EmitBuiltinProlog (Builtin builtin_id) [inline]
Definition at line 390 of file turboshaft-builtins-assembler-inl.h.
                                             {
    // Bind the entry block.
    __ Bind(__ NewBlock());
    // Eagerly emit all parameters such that they are guaranteed to be in the
    // entry block (assembler will cache them).
    const compiler::CallDescriptor* desc =
        __ data() -> builtin_call_descriptor();
    for (int i = 0; i < static_cast<int>(desc->ParameterCount()); ++i) {
      __ Parameter(i, RegisterRepresentation::FromMachineType(
                          desc->GetParameterType(i)));
    }
    // TODO(nicohartmann): CSA tracks some debug information here.
    // Emit stack check.
    if (Builtins::KindOf(builtin_id) == Builtins::TSJ) {
      __ PerformStackCheck(__ JSContextParameter());
    }
  }
References __, v8::internal::compiler::turboshaft::RegisterRepresentation::FromMachineType(), v8::internal::compiler::CallDescriptor::GetParameterType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::BuiltinsReducer< Next >::JSContextParameter(), v8::internal::Builtins::KindOf(), v8::internal::compiler::CallDescriptor::ParameterCount(), v8::internal::BuiltinsReducer< Next >::PerformStackCheck(), and v8::internal::Builtins::TSJ.
EmitEpilog()
template<typename Next >
void v8::internal::BuiltinsReducer< Next >::EmitEpilog (Block * catch_block) [inline]
Definition at line 408 of file turboshaft-builtins-assembler-inl.h.
                                      {
    DCHECK_EQ(__ HasFeedbackCollector(), catch_block != nullptr);
    if (catch_block) {
      // If the handler can potentially throw, we catch the exception here and
      // update the feedback vector before we rethrow the exception.
      if (__ Bind(catch_block)) {
        V<Object> exception = __ CatchBlockBegin();
        __ CombineExceptionFeedback();
        __ UpdateFeedback();
        __ template CallRuntime<
            compiler::turboshaft::RuntimeCallDescriptor::ReThrow>(
            __ data()->isolate(), __ NoContextConstant(), {exception});
        __ Unreachable();
      }
    }
  }
References __, and DCHECK_EQ.
InstanceTypeEqual()
template<typename Next >
V<Word32> v8::internal::BuiltinsReducer< Next >::InstanceTypeEqual (ConstOrV< Word32 > instance_type, ConstOrV< Word32 > other_instance_type) [inline]
Definition at line 473 of file turboshaft-builtins-assembler-inl.h.
                                                                    {
    return __ Word32Equal(instance_type, other_instance_type);
  }
References __, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by v8::internal::BuiltinsReducer< Next >::IsBigIntInstanceType(), and v8::internal::BuiltinsReducer< Next >::TaggedToWord32OrBigIntImpl().
IsBigIntInstanceType()
template<typename Next >
V<Word32> v8::internal::BuiltinsReducer< Next >::IsBigIntInstanceType (ConstOrV< Word32 > instance_type) [inline]
Definition at line 469 of file turboshaft-builtins-assembler-inl.h.
                                                                 {
    return InstanceTypeEqual(instance_type, BIGINT_TYPE);
  }
References v8::internal::BIGINT_TYPE, and v8::internal::BuiltinsReducer< Next >::InstanceTypeEqual().
Referenced by v8::internal::BuiltinsReducer< Next >::TaggedToWord32OrBigIntImpl().
isolate()
template<typename Next >
Isolate* v8::internal::BuiltinsReducer< Next >::isolate () [inline], [private]
Definition at line 588 of file turboshaft-builtins-assembler-inl.h.
{ return __ data() -> isolate(); }
References __, and v8::internal::BuiltinsReducer< Next >::isolate().
Referenced by v8::internal::BuiltinsReducer< Next >::isolate(), and v8::internal::BuiltinsReducer< Next >::TaggedToWord32OrBigIntImpl().
IsSmallBigInt()
template<typename Next >
V<Word32> v8::internal::BuiltinsReducer< Next >::IsSmallBigInt (V< BigInt > value) [inline]
Definition at line 472 of file turboshaft-builtins-assembler-inl.h.
{ UNIMPLEMENTED(); }
References v8::internal::UNIMPLEMENTED().
Referenced by v8::internal::BuiltinsReducer< Next >::TaggedToWord32OrBigIntImpl().
JSContextParameter()
template<typename Next >
V<Context> v8::internal::BuiltinsReducer< Next >::JSContextParameter () [inline]
Definition at line 425 of file turboshaft-builtins-assembler-inl.h.
                                  {
    return __ template Parameter<Context>(
        compiler::Linkage::GetJSCallContextParamIndex(static_cast<int>(
            __ data()->builtin_call_descriptor()->JSParameterCount())));
  }
References __, v8::internal::compiler::Linkage::GetJSCallContextParamIndex(), and v8::internal::JSParameterCount().
Referenced by v8::internal::BuiltinsReducer< Next >::EmitBuiltinProlog().
PerformStackCheck()
template<typename Next >
void v8::internal::BuiltinsReducer< Next >::PerformStackCheck (V< Context > context) [inline]
Definition at line 431 of file turboshaft-builtins-assembler-inl.h.
                                             {
    __ JSStackCheck(context,
                    OptionalV<compiler::turboshaft::FrameState>::Nullopt(),
                    compiler::turboshaft::JSStackCheckOp::Kind::kBuiltinEntry);
  }
References __, and v8::internal::compiler::turboshaft::JSStackCheckOp::kBuiltinEntry.
Referenced by v8::internal::BuiltinsReducer< Next >::EmitBuiltinProlog().
PopAndReturn()
template<typename Next >
void v8::internal::BuiltinsReducer< Next >::PopAndReturn (BuiltinArgumentsTS & arguments, compiler::turboshaft::V< Object > return_value) [inline]
Definition at line 437 of file turboshaft-builtins-assembler-inl.h.
                                                              {
    // PopAndReturn is supposed to be using ONLY in CSA/Torque builtins for
    // dropping ALL JS arguments that are currently located on the stack.
    // The check below ensures that there are no directly accessible stack
    // parameters from current builtin, which implies that the builtin with
    // JS calling convention (TFJ) was created with kDontAdaptArgumentsSentinel.
    // This simplifies semantics of this instruction because in case of presence
    // of directly accessible stack parameters it's impossible to distinguish
    // the following cases:
    // 1) stack parameter is included in JS arguments (and therefore it will be
    // dropped as a part of 'pop' number of arguments),
    // 2) stack parameter is NOT included in JS arguments (and therefore it
    // should
    // be dropped in ADDITION to the 'pop' number of arguments).
    // Additionally, in order to simplify assembly code, PopAndReturn is also
    // not allowed in builtins with stub linkage and parameters on stack.
    CHECK_EQ(__ data()->builtin_call_descriptor()->ParameterSlotCount(), 0);
    V<WordPtr> pop_count = arguments.GetLengthWithReceiver();
    std::initializer_list<const OpIndex> temp{return_value};
    __ Return(__ TruncateWordPtrToWord32(pop_count), base::VectorOf(temp));
  }
References __, CHECK_EQ, v8::internal::detail::BuiltinArgumentsTS< Assembler >::GetLengthWithReceiver(), and v8::base::VectorOf().
TaggedToWord32OrBigIntImpl()
template<typename Next >
template<Object::Conversion Conversion>
void v8::internal::BuiltinsReducer< Next >::TaggedToWord32OrBigIntImpl (V< Context > context, V< Object > value, IsKnownTaggedPointer is_known_tagged_pointer, Label< Word32 > & if_number, Label< BigInt > * if_bigint = nullptr, Label< BigInt > * if_bigint64 = nullptr) [inline]
Definition at line 509 of file turboshaft-builtins-assembler-inl.h.
                                                                        {
    DCHECK_EQ(Conversion == Object::Conversion::kToNumeric,
              if_bigint != nullptr);
    if (is_known_tagged_pointer == IsKnownTaggedPointer::kNo) {
      IF (__ IsSmi(value)) {
        __ CombineFeedback(BinaryOperationFeedback::kSignedSmall);
        GOTO(if_number, __ UntagSmi(V<Smi>::Cast(value)));
      }
    }
    ScopedVar<HeapObject> value_heap_object(this, V<HeapObject>::Cast(value));
    WHILE(1) {
      V<Map> map = __ LoadMapField(value_heap_object);
      IF (__ IsHeapNumberMap(map)) {
        __ CombineFeedback(BinaryOperationFeedback::kNumber);
        V<Float64> value_float64 =
            __ LoadHeapNumberValue(V<HeapNumber>::Cast(value_heap_object));
        GOTO(if_number, __ JSTruncateFloat64ToWord32(value_float64));
      }
      V<Word32> instance_type = __ LoadInstanceTypeField(map);
      if (Conversion == Object::Conversion::kToNumeric) {
        IF (IsBigIntInstanceType(instance_type)) {
          V<BigInt> value_bigint = V<BigInt>::Cast(value_heap_object);
          if (Is64() && if_bigint64) {
            IF (IsSmallBigInt(value_bigint)) {
              __ CombineFeedback(BinaryOperationFeedback::kBigInt64);
              GOTO(*if_bigint64, value_bigint);
            }
          }
          __ CombineFeedback(BinaryOperationFeedback::kBigInt);
          GOTO(*if_bigint, value_bigint);
        }
      }
      // Not HeapNumber (or BigInt if conversion == kToNumeric).
      if (__ HasFeedbackCollector()) {
        // We do not require an Or with earlier feedback here because once we
        // convert the value to a Numeric, we cannot reach this path. We can
        // only reach this path on the first pass when the feedback is kNone.
        TSA_DCHECK(this, __ FeedbackIs(BinaryOperationFeedback::kNone));
      }
      IF (InstanceTypeEqual(instance_type, ODDBALL_TYPE)) {
        __ OverwriteFeedback(BinaryOperationFeedback::kNumberOrOddball);
        V<Float64> oddball_value =
            __ LoadField(V<Oddball>::Cast(value_heap_object),
                         AccessBuilderTS::ForHeapNumberOrOddballOrHoleValue());
        GOTO(if_number, __ JSTruncateFloat64ToWord32(oddball_value));
      }
      // Not an oddball either -> convert.
      V<Object> converted_value;
      // TODO(nicohartmann): We have to make sure that we store the feedback if
      // any of those calls throws an exception.
      __ OverwriteFeedback(BinaryOperationFeedback::kAny);
      using Builtin =
          std::conditional_t<Conversion == Object::Conversion::kToNumeric,
                             BuiltinCallDescriptor::NonNumberToNumeric,
                             BuiltinCallDescriptor::NonNumberToNumber>;
      converted_value = __ template CallBuiltin<Builtin>(
          isolate(), context, {V<JSAnyNotNumber>::Cast(value_heap_object)});
      GOTO_IF(__ IsSmi(converted_value), if_number,
              __ UntagSmi(V<Smi>::Cast(converted_value)));
      value_heap_object = V<HeapObject>::Cast(converted_value);
    }
    __ Unreachable();
  }
References __, v8::internal::compiler::turboshaft::V< T >::Cast(), DCHECK_EQ, v8::internal::BuiltinsReducer< Next >::InstanceTypeEqual(), v8::internal::Is64(), v8::internal::BuiltinsReducer< Next >::IsBigIntInstanceType(), v8::internal::BuiltinsReducer< Next >::isolate(), v8::internal::BuiltinsReducer< Next >::IsSmallBigInt(), v8::internal::IsSmi(), v8::internal::BinaryOperationFeedback::kAny, v8::internal::BinaryOperationFeedback::kBigInt, v8::internal::BinaryOperationFeedback::kBigInt64, v8::internal::BinaryOperationFeedback::kNone, v8::internal::BinaryOperationFeedback::kNumber, v8::internal::BinaryOperationFeedback::kNumberOrOddball, v8::internal::BinaryOperationFeedback::kSignedSmall, v8::internal::Object::kToNumeric, and v8::internal::value.
TruncateTaggedToWord32()
template<typename Next >
V<Word32> v8::internal::BuiltinsReducer< Next >::TruncateTaggedToWord32 (V< Context > context, V< Object > value) [inline]
Definition at line 460 of file turboshaft-builtins-assembler-inl.h.
                                                                        {
    Label<Word32> is_number(this);
    TaggedToWord32OrBigIntImpl<Object::Conversion::kToNumber>(
        context, value, IsKnownTaggedPointer::kNo, is_number);
    BIND(is_number, number);
    return number;
  }
References v8::internal::value.
TryToIntPtrConstant()
template<typename Next >
std::optional<intptr_t> v8::internal::BuiltinsReducer< Next >::TryToIntPtrConstant (ConstOrV< WordPtr > index) [inline]
Definition at line 499 of file turboshaft-builtins-assembler-inl.h.
                                                                     {
    if (index.is_constant()) return index.constant_value();
    intptr_t value;
    if (matcher_.MatchIntegralWordPtrConstant(index.value(), &value)) {
      return value;
    }
    return std::nullopt;
  }
References v8::internal::index, v8::internal::BuiltinsReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordPtrConstant(), and v8::internal::value.
Referenced by v8::internal::BuiltinsReducer< Next >::ElementOffsetFromIndex().
Member Data Documentation
matcher_
template<typename Next >
compiler::turboshaft::OperationMatcher v8::internal::BuiltinsReducer< Next >::matcher_ {__ data()->graph()} [private]
Definition at line 587 of file turboshaft-builtins-assembler-inl.h.
Referenced by v8::internal::BuiltinsReducer< Next >::TryToIntPtrConstant().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/turboshaft-builtins-assembler-inl.h