v8::internal::maglev::CreateFunctionContext Class Reference
#include <maglev-ir.h>
Public Member Functions
CreateFunctionContext (uint64_t bitfield, compiler::ScopeInfoRef scope_info, uint32_t slot_count, ScopeType scope_type)
compiler::ScopeInfoRef scope_info () const
uint32_t slot_count () const
ScopeType scope_type () const
Input & context ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = FixedInputValueNodeT< 1, CreateFunctionContext >
Private Attributes
const compiler::ScopeInfoRef scope_info_
const uint32_t slot_count_
ScopeType scope_type_
Additional Inherited Members
Detailed Description
Definition at line 6587 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CreateFunctionContext::Base = FixedInputValueNodeT<1, CreateFunctionContext> [private]
Definition at line 6589 of file maglev-ir.h.
Constructor & Destructor Documentation
CreateFunctionContext()
v8::internal::maglev::CreateFunctionContext::CreateFunctionContext (uint64_t bitfield, compiler::ScopeInfoRef scope_info, uint32_t slot_count, ScopeType scope_type) [inline], [explicit]
Definition at line 6592 of file maglev-ir.h.
      : Base(bitfield),
        scope_info_(scope_info),
        slot_count_(slot_count),
        scope_type_(scope_type) {}
Member Function Documentation
context()
Input& v8::internal::maglev::CreateFunctionContext::context () [inline]
Definition at line 6604 of file maglev-ir.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::CreateFunctionContext::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::CreateFunctionContext::MaxCallStackArgs () const
PrintParams()
void v8::internal::maglev::CreateFunctionContext::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7967 of file maglev-ir.cc.
                                                               {
  os << "(" << *scope_info().object() << ", " << slot_count() << ")";
}
References v8::internal::compiler::ScopeInfoRef::object(), scope_info(), and slot_count().
scope_info()
compiler::ScopeInfoRef v8::internal::maglev::CreateFunctionContext::scope_info () const [inline]
Definition at line 6600 of file maglev-ir.h.
{ return scope_info_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
scope_type()
ScopeType v8::internal::maglev::CreateFunctionContext::scope_type () const [inline]
Definition at line 6602 of file maglev-ir.h.
{ return scope_type_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::CreateFunctionContext::SetValueLocationConstraints ()
slot_count()
uint32_t v8::internal::maglev::CreateFunctionContext::slot_count () const [inline]
Definition at line 6601 of file maglev-ir.h.
{ return slot_count_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::CreateFunctionContext::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 6611 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CreateFunctionContext::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::Call() | OpProperties::CanAllocate() |
      OpProperties::LazyDeopt() | OpProperties::NotIdempotent()
Definition at line 6607 of file maglev-ir.h.
scope_info_
const compiler::ScopeInfoRef v8::internal::maglev::CreateFunctionContext::scope_info_ [private]
Definition at line 6619 of file maglev-ir.h.
scope_type_
ScopeType v8::internal::maglev::CreateFunctionContext::scope_type_ [private]
Definition at line 6621 of file maglev-ir.h.
slot_count_
const uint32_t v8::internal::maglev::CreateFunctionContext::slot_count_ [private]
Definition at line 6620 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc