v8::internal::RegisteredSymbolTable Class Reference
#include <hash-table.h>
Public Member Functions
Tagged< Object > SlowReverseLookup (Tagged< Object > value)
Tagged< Object > ValueAt (InternalIndex entry)
Static Public Member Functions
static DirectHandle< Map > GetMap (RootsTable &roots)
static Handle< RegisteredSymbolTable > Add (Isolate *isolate, Handle< RegisteredSymbolTable > table, DirectHandle< String > key, DirectHandle< Symbol >)
Static Private Member Functions
static int EntryToValueIndex (InternalIndex entry)
Detailed Description
Definition at line 584 of file hash-table.h.
Member Function Documentation
Add()
Handle< RegisteredSymbolTable > v8::internal::RegisteredSymbolTable::Add (Isolate * isolate, Handle< RegisteredSymbolTable > table, DirectHandle< String > key, DirectHandle< Symbol > symbol) [static]
Definition at line 5666 of file objects.cc.
                                                           {
  // Validate that the key is absent.
  SLOW_DCHECK(table->FindEntry(isolate, key).is_not_found());
  table = EnsureCapacity(isolate, table);
  uint32_t hash = TodoShape::Hash(ReadOnlyRoots(isolate), key);
  InternalIndex entry = table->FindInsertionEntry(isolate, hash);
  table->set(EntryToIndex(entry), *key);
  table->set(EntryToValueIndex(entry), *symbol);
  table->ElementAdded();
  return table;
}
References v8::internal::Hash(), v8::internal::key, and SLOW_DCHECK.
Referenced by v8::internal::Isolate::SymbolFor().
EntryToValueIndex()
static int v8::internal::RegisteredSymbolTable::EntryToValueIndex (InternalIndex entry) [inline], [static], [private]
Definition at line 602 of file hash-table.h.
                                                           {
    return EntryToIndex(entry) + RegisteredSymbolTableShape::kEntryValueIndex;
  }
References v8::internal::RegisteredSymbolTableShape::kEntryValueIndex.
GetMap()
DirectHandle< Map > v8::internal::RegisteredSymbolTable::GetMap (RootsTable & roots) [inline], [static]
Definition at line 119 of file hash-table-inl.h.
                                                                 {
  return roots.registered_symbol_table_map();
}
SlowReverseLookup()
Tagged< Object > v8::internal::RegisteredSymbolTable::SlowReverseLookup (Tagged< Object > value)
Definition at line 10 of file symbol-table.cc.
                                                                            {
  ReadOnlyRoots roots = GetReadOnlyRoots();
  for (InternalIndex i : this->IterateEntries()) {
    Tagged<Object> k;
    if (!this->ToKey(roots, i, &k)) continue;
    Tagged<Object> e = this->ValueAt(i);
    if (e == value) return k;
  }
  return roots.undefined_value();
}
References v8::internal::GetReadOnlyRoots(), v8::internal::value, and ValueAt().
ValueAt()
Tagged< Object > v8::internal::RegisteredSymbolTable::ValueAt (InternalIndex entry)
Definition at line 6091 of file objects.cc.
                                                                 {
  return this->get(EntryToValueIndex(entry));
}
Referenced by SlowReverseLookup().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/hash-table.h
/mnt/V8SourceCode/src/objects/hash-table-inl.h
/mnt/V8SourceCode/src/objects/objects.cc
/mnt/V8SourceCode/src/objects/symbol-table.cc