cppgc::internal::MarkingVisitorBase Class Reference
#include <marking-visitor.h>
Public Member Functions
MarkingVisitorBase (HeapBase &, BasicMarkingState &)
~MarkingVisitorBase () override=default
Protected Member Functions
void Visit (const void *, TraceDescriptor) final
void VisitMultipleUncompressedMember (const void *, size_t, TraceDescriptorCallback) final
void VisitWeak (const void *, TraceDescriptor, WeakCallback, const void *) final
void VisitEphemeron (const void *, const void *, TraceDescriptor) final
void VisitWeakContainer (const void *object, TraceDescriptor strong_desc, TraceDescriptor weak_desc, WeakCallback callback, const void *data) final
void RegisterWeakCallback (WeakCallback, const void *) final
Registers a weak callback that is invoked during garbage collection.
void HandleMovableReference (const void **) final
Protected Attributes
BasicMarkingState & marking_state_
Additional Inherited Members
Detailed Description
Definition at line 23 of file marking-visitor.h.
Constructor & Destructor Documentation
MarkingVisitorBase()
cppgc::internal::MarkingVisitorBase::MarkingVisitorBase (HeapBase & heap, BasicMarkingState & marking_state)
Definition at line 17 of file marking-visitor.cc.
    : marking_state_(marking_state) {}
 MarkingVisitorBase()
cppgc::internal::MarkingVisitorBase::~MarkingVisitorBase () [override], [default]
Member Function Documentation
HandleMovableReference()
void cppgc::internal::MarkingVisitorBase::HandleMovableReference (const void ** slot) [final], [protected], [virtual]
Reimplemented from cppgc::Visitor.
Definition at line 83 of file marking-visitor.cc.
                                                                 {
  marking_state_.RegisterMovableReference(slot);
}
References marking_state_, and cppgc::internal::BasicMarkingState::RegisterMovableReference().
RegisterWeakCallback()
void cppgc::internal::MarkingVisitorBase::RegisterWeakCallback (WeakCallback callback, const void * data) [final], [protected], [virtual]
Registers a weak callback that is invoked during garbage collection.
Parameters
callback to be invoked.
data custom data that is passed to the callback.
Reimplemented from cppgc::Visitor.
Definition at line 78 of file marking-visitor.cc.
                                                                  {
  marking_state_.RegisterWeakCustomCallback(callback, object);
}
References marking_state_, and cppgc::internal::BasicMarkingState::RegisterWeakCustomCallback().
Visit()
void cppgc::internal::MarkingVisitorBase::Visit (const void * object, TraceDescriptor desc) [final], [protected], [virtual]
Reimplemented from cppgc::Visitor.
Definition at line 21 of file marking-visitor.cc.
                                                                       {
  marking_state_.MarkAndPush(object, desc);
}
References cppgc::internal::MarkingStateBase::MarkAndPush(), and marking_state_.
VisitEphemeron()
void cppgc::internal::MarkingVisitorBase::VisitEphemeron (const void * key, const void * value, TraceDescriptor value_desc) [final], [protected], [virtual]
Reimplemented from cppgc::Visitor.
Definition at line 65 of file marking-visitor.cc.
                                                                    {
  marking_state_.ProcessEphemeron(key, value, value_desc, *this);
}
References v8::internal::key, marking_state_, cppgc::internal::BasicMarkingState::ProcessEphemeron(), and v8::internal::value.
VisitMultipleUncompressedMember()
void cppgc::internal::MarkingVisitorBase::VisitMultipleUncompressedMember (const void * start, size_t len, TraceDescriptorCallback get_trace_descriptor) [final], [protected], [virtual]
Reimplemented from cppgc::Visitor.
Definition at line 25 of file marking-visitor.cc.
                                                  {
  const char* it = static_cast<const char*>(start);
  const char* end = it + len * cppgc::internal::kSizeOfUncompressedMember;
  for (; it < end; it += cppgc::internal::kSizeOfUncompressedMember) {
    const auto* current = reinterpret_cast<const internal::RawPointer*>(it);
    const void* object = current->LoadAtomic();
    if (!object) continue;
    marking_state_.MarkAndPush(object, get_trace_descriptor(object));
  }
}
References v8::internal::compiler::end(), cppgc::internal::kSizeOfUncompressedMember, cppgc::internal::RawPointer::LoadAtomic(), cppgc::internal::MarkingStateBase::MarkAndPush(), and marking_state_.
VisitWeak()
void cppgc::internal::MarkingVisitorBase::VisitWeak (const void * object, TraceDescriptor desc, WeakCallback weak_callback, const void * weak_member) [final], [protected], [virtual]
Reimplemented from cppgc::Visitor.
Definition at line 58 of file marking-visitor.cc.
                                                            {
  marking_state_.RegisterWeakReferenceIfNeeded(object, desc, weak_callback,
                                               weak_member);
}
References marking_state_, and cppgc::internal::BasicMarkingState::RegisterWeakReferenceIfNeeded().
VisitWeakContainer()
void cppgc::internal::MarkingVisitorBase::VisitWeakContainer (const void * object, TraceDescriptor strong_desc, TraceDescriptor weak_desc, WeakCallback callback, const void * data) [final], [protected], [virtual]
Reimplemented from cppgc::Visitor.
Definition at line 70 of file marking-visitor.cc.
                                                              {
  marking_state_.ProcessWeakContainer(object, weak_desc, callback, data);
}
References marking_state_, and cppgc::internal::BasicMarkingState::ProcessWeakContainer().
Member Data Documentation
marking_state_
BasicMarkingState& cppgc::internal::MarkingVisitorBase::marking_state_ [protected]
Definition at line 44 of file marking-visitor.h.
Referenced by cppgc::internal::ConcurrentMarkingVisitor::DeferTraceToMutatorThreadIfConcurrent(), HandleMovableReference(), RegisterWeakCallback(), Visit(), VisitEphemeron(), VisitMultipleUncompressedMember(), VisitWeak(), and VisitWeakContainer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/marking-visitor.h
/mnt/V8SourceCode/src/heap/cppgc/marking-visitor.cc