v8::internal::compiler::JSNodeWrapperBase Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSNodeWrapperBase (Node *node)
TNode< Object > context () const
Effect effect () const
Control control () const
FrameState frame_state () const
Additional Inherited Members
Detailed Description
Definition at line 1128 of file js-operator.h.
Constructor & Destructor Documentation
JSNodeWrapperBase()
constexpr v8::internal::compiler::JSNodeWrapperBase::JSNodeWrapperBase (Node * node) [inline], [explicit], [constexpr]
Definition at line 1130 of file js-operator.h.
: NodeWrapper(node) {}
Member Function Documentation
context()
TNode<Object> v8::internal::compiler::JSNodeWrapperBase::context () const [inline]
Definition at line 1133 of file js-operator.h.
                                {
    // Could be a Context or NoContextConstant.
    return TNode<Object>::UncheckedCast(
        NodeProperties::GetContextInput(node()));
  }
References v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeWrapper::node(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseExecutor(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseReject(), v8::internal::compiler::JSCallReducer::CheckIfConstructor(), v8::internal::compiler::JSCallReducer::ReduceArrayIsArray(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceBigIntConstructor(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeHasInstance(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::JSCallReducer::ReduceNumberConstructor(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSCallReducer::ReduceObjectCreate(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), v8::internal::compiler::JSCallReducer::ReducePromiseResolveTrampoline(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::compiler::JSCallReducer::ReduceReflectHas(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::JSCallReducer::ReduceStringConstructor(), v8::internal::compiler::JSCallReducer::ReduceStringIteratorPrototypeNext(), and v8::internal::compiler::JSCallReducer::ReduceTypedArrayConstructor().
control()
Control v8::internal::compiler::JSNodeWrapperBase::control () const [inline]
Definition at line 1146 of file js-operator.h.
                          {
    DCHECK_EQ(node()->op()->ControlInputCount(), 1);
    return Control{NodeProperties::GetControlInput(node())};
  }
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetControlInput(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSCallReducer::CheckIfConstructor(), v8::internal::compiler::JSCallReducer::ReduceArrayIsArray(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeAt(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceBigIntAsN(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeHasInstance(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsFinite(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsNaN(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithSpread(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCallReducer::ReduceJSConstructWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceJSConstructWithSpread(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralArrayOrObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralRegExp(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::compiler::JSCallReducer::ReduceMathClz32(), v8::internal::compiler::JSCallReducer::ReduceMathImul(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSCallReducer::ReduceObjectCreate(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), v8::internal::compiler::JSCallReducer::ReducePromiseResolveTrampoline(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::compiler::JSCallReducer::ReduceReflectHas(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::JSCallReducer::ReduceStringConstructor(), v8::internal::compiler::JSCallReducer::ReduceStringFromCharCode(), v8::internal::compiler::JSCallReducer::ReduceStringFromCodePoint(), v8::internal::compiler::JSCallReducer::ReduceStringIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeConcat(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCodePointAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayConstructor(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
effect()
Effect v8::internal::compiler::JSNodeWrapperBase::effect () const [inline]
Definition at line 1140 of file js-operator.h.
                        {
    DCHECK_EQ(node()->op()->EffectInputCount(), 1);
    return Effect{NodeProperties::GetEffectInput(node())};
  }
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetEffectInput(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSCallReducer::CheckIfConstructor(), v8::internal::compiler::JSCallReducer::ReduceArrayIsArray(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeAt(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceBigIntAsN(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeHasInstance(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsFinite(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsNaN(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithSpread(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCallReducer::ReduceJSConstructWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceJSConstructWithSpread(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralArrayOrObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralRegExp(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::compiler::JSCallReducer::ReduceMathClz32(), v8::internal::compiler::JSCallReducer::ReduceMathImul(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSCallReducer::ReduceObjectConstructor(), v8::internal::compiler::JSCallReducer::ReduceObjectCreate(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeIsPrototypeOf(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), v8::internal::compiler::JSCallReducer::ReducePromiseResolveTrampoline(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::compiler::JSCallReducer::ReduceReflectHas(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::JSCallReducer::ReduceStringConstructor(), v8::internal::compiler::JSCallReducer::ReduceStringFromCharCode(), v8::internal::compiler::JSCallReducer::ReduceStringFromCodePoint(), v8::internal::compiler::JSCallReducer::ReduceStringIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeConcat(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCodePointAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayConstructor(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
frame_state()
FrameState v8::internal::compiler::JSNodeWrapperBase::frame_state () const [inline]
Definition at line 1152 of file js-operator.h.
                                 {
    return FrameState{NodeProperties::GetFrameStateInput(node())};
  }
References v8::internal::compiler::NodeProperties::GetFrameStateInput(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSCallReducer::CheckIfConstructor(), v8::internal::compiler::JSCallReducer::ReduceArrayIsArray(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceBigIntConstructor(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeHasInstance(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::compiler::JSCallReducer::ReduceNumberConstructor(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSCallReducer::ReduceObjectCreate(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), v8::internal::compiler::JSCallReducer::ReducePromiseResolveTrampoline(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::compiler::JSCallReducer::ReduceReflectHas(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::JSCallReducer::ReduceStringConstructor(), and v8::internal::compiler::JSCallReducer::ReduceTypedArrayConstructor().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h