v8::internal::OffHeapHashTableBase< Derived > Class Template Reference
#include <off-heap-hash-table.h>
Public Member Functions
int capacity () const
int number_of_elements () const
int number_of_deleted_elements () const
OffHeapObjectSlot slot (InternalIndex index, int offset=0) const
template<typename... Args>
void AddAt (PtrComprCageBase cage_base, InternalIndex entry, Args &&... args)
template<typename... Args>
void OverwriteDeletedAt (PtrComprCageBase cage_base, InternalIndex entry, Args &&... args)
void ElementsRemoved (int count)
size_t GetSizeExcludingHeader () const
template<typename IsolateT , typename FindKey >
InternalIndex FindEntry (IsolateT *isolate, FindKey key, uint32_t hash) const
InternalIndex FindInsertionEntry (PtrComprCageBase cage_base, uint32_t hash) const
template<typename IsolateT , typename FindKey >
InternalIndex FindEntryOrInsertionEntry (IsolateT *isolate, FindKey key, uint32_t hash) const
bool ShouldResizeToAdd (int number_of_additional_elements, int *new_capacity)
void RehashInto (PtrComprCageBase cage_base, Derived *new_table)
void IterateElements (Root root, RootVisitor *visitor)
Static Public Member Functions
static constexpr Tagged< Smi > empty_element ()
static constexpr Tagged< Smi > deleted_element ()
static bool IsKey (Tagged< Object > k)
Protected Member Functions
OffHeapHashTableBase (int capacity)
bool HasSufficientCapacityToAdd (int number_of_additional_elements) const
Static Protected Member Functions
static InternalIndex FirstProbe (uint32_t hash, uint32_t size)
static InternalIndex NextProbe (InternalIndex last, uint32_t number, uint32_t size)
static bool HasSufficientCapacityToAdd (int capacity, int number_of_elements, int number_of_deleted_elements, int number_of_additional_elements)
static int ComputeCapacity (int at_least_space_for)
static int ComputeCapacityWithShrink (int current_capacity, int at_least_space_for)
static size_t GetSizeExcludingHeader (int capacity)
template<typename Container , size_t OffsetOfElementsInContainer>
static void * Allocate (int capacity)
static void Free (void *container)
Protected Attributes
int number_of_elements_
int number_of_deleted_elements_
const int capacity_
Tagged_t elements_ [1]
Detailed Description
template<typename Derived>
class v8::internal::OffHeapHashTableBase< Derived >
Definition at line 68 of file off-heap-hash-table.h.
Constructor & Destructor Documentation
OffHeapHashTableBase()
template<typename Derived >
v8::internal::OffHeapHashTableBase< Derived >::OffHeapHashTableBase (int capacity) [explicit], [protected]
Definition at line 17 of file off-heap-hash-table-inl.h.
    : number_of_elements_(0),
      number_of_deleted_elements_(0),
      capacity_(capacity) {
  MemsetTagged(slot(InternalIndex(0)), empty_element(),
               capacity * Derived::kEntrySize);
}
References v8::internal::OffHeapHashTableBase< Derived >::capacity(), v8::internal::OffHeapHashTableBase< Derived >::empty_element(), cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize, v8::internal::MemsetTagged(), and v8::internal::OffHeapHashTableBase< Derived >::slot().
Member Function Documentation
AddAt()
template<typename Derived >
template<typename... Args>
void v8::internal::OffHeapHashTableBase< Derived >::AddAt (PtrComprCageBase cage_base, InternalIndex entry, Args &&... args) [inline]
Definition at line 88 of file off-heap-hash-table.h.
                                                                              {
    Derived* derived_this = static_cast<Derived*>(this);
    DCHECK_EQ(derived_this->GetKey(cage_base, entry), empty_element());
    DCHECK_LT(number_of_elements_ + 1, capacity());
    DCHECK(HasSufficientCapacityToAdd(1));
    derived_this->Set(entry, std::forward<Args>(args)...);
    number_of_elements_++;
  }
References v8::base::args, v8::internal::OffHeapHashTableBase< Derived >::capacity(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, v8::internal::OffHeapHashTableBase< Derived >::empty_element(), v8::internal::OffHeapHashTableBase< Derived >::HasSufficientCapacityToAdd(), and v8::internal::OffHeapHashTableBase< Derived >::number_of_elements_.
Referenced by v8::internal::StringTable::InsertEmptyStringForBootstrapping(), v8::internal::StringTable::InsertForIsolateDeserialization(), and v8::internal::StringTable::LookupKey().
Allocate()
template<typename Derived >
template<typename Container , size_t OffsetOfElementsInContainer>
void * v8::internal::OffHeapHashTableBase< Derived >::Allocate (int capacity) [inline], [static], [protected]
Definition at line 191 of file off-heap-hash-table-inl.h.
                                                          {
  // Make sure that the elements_ array is at the end of Container, with no
  // padding, so that subsequent elements can be accessed as offsets from
  // elements_.
  static_assert(OffsetOfElementsInContainer ==
                sizeof(Container) - sizeof(Tagged_t));
  // Make sure that elements_ is aligned when Container is aligned.
  static_assert(OffsetOfElementsInContainer % kTaggedSize == 0);
  return AlignedAllocWithRetry(
      sizeof(Container) + GetSizeExcludingHeader(capacity),
      std::max(alignof(Container), alignof(void*)));
}
References v8::internal::AlignedAllocWithRetry(), and v8::internal::kTaggedSize.
capacity()
template<typename Derived >
int v8::internal::OffHeapHashTableBase< Derived >::capacity () const [inline]
Definition at line 77 of file off-heap-hash-table.h.
{ return capacity_; }
References v8::internal::OffHeapHashTableBase< Derived >::capacity_.
Referenced by v8::internal::OffHeapHashTableBase< Derived >::AddAt(), v8::internal::OffHeapHashTableBase< Derived >::GetSizeExcludingHeader(), v8::internal::OffHeapHashTableBase< Derived >::HasSufficientCapacityToAdd(), v8::internal::OffHeapHashTableBase< Derived >::OffHeapHashTableBase(), and v8::internal::OffHeapHashTableBase< Derived >::OverwriteDeletedAt().
ComputeCapacity()
template<typename Derived >
int v8::internal::OffHeapHashTableBase< Derived >::ComputeCapacity (int at_least_space_for) [inline], [static], [protected]
Definition at line 89 of file off-heap-hash-table-inl.h.
                                                                         {
  // Add 50% slack to make slot collisions sufficiently unlikely.
  // See matching computation in HasSufficientCapacityToAdd().
  int raw_capacity = at_least_space_for + (at_least_space_for >> 1);
  int capacity = base::bits::RoundUpToPowerOfTwo32(raw_capacity);
  return std::max(capacity, Derived::kMinCapacity);
}
ComputeCapacityWithShrink()
template<typename Derived >
int v8::internal::OffHeapHashTableBase< Derived >::ComputeCapacityWithShrink (int current_capacity, int at_least_space_for) [inline], [static], [protected]
Definition at line 99 of file off-heap-hash-table-inl.h.
                                                  {
  // Only shrink if the table is very empty to avoid performance penalty.
  DCHECK_GE(current_capacity, Derived::kMinCapacity);
  if (at_least_space_for > (current_capacity / Derived::kMaxEmptyFactor)) {
    return current_capacity;
  }
  // Recalculate the smaller capacity actually needed.
  int new_capacity = ComputeCapacity(at_least_space_for);
  DCHECK_GE(new_capacity, at_least_space_for);
  // Don't go lower than room for {kMinCapacity} elements.
  if (new_capacity < Derived::kMinCapacity) return current_capacity;
  return new_capacity;
}
References DCHECK_GE.
deleted_element()
template<typename Derived >
static constexpr Tagged<Smi> v8::internal::OffHeapHashTableBase< Derived >::deleted_element () [inline], [static], [constexpr]
Definition at line 71 of file off-heap-hash-table.h.
{ return Smi::FromInt(1); }
References v8::internal::Smi::FromInt().
Referenced by v8::internal::OffHeapHashTableBase< Derived >::IsKey(), and v8::internal::OffHeapHashTableBase< Derived >::OverwriteDeletedAt().
ElementsRemoved()
template<typename Derived >
void v8::internal::OffHeapHashTableBase< Derived >::ElementsRemoved (int count) [inline]
Definition at line 114 of file off-heap-hash-table.h.
                                  {
    DCHECK_LE(count, number_of_elements_);
    number_of_elements_ -= count;
    number_of_deleted_elements_ += count;
  }
References DCHECK_LE, v8::internal::OffHeapHashTableBase< Derived >::number_of_deleted_elements_, and v8::internal::OffHeapHashTableBase< Derived >::number_of_elements_.
empty_element()
template<typename Derived >
static constexpr Tagged<Smi> v8::internal::OffHeapHashTableBase< Derived >::empty_element () [inline], [static], [constexpr]
Definition at line 70 of file off-heap-hash-table.h.
{ return Smi::FromInt(0); }
References v8::internal::Smi::FromInt().
Referenced by v8::internal::OffHeapHashTableBase< Derived >::AddAt(), v8::internal::OffHeapHashTableBase< Derived >::IsKey(), and v8::internal::OffHeapHashTableBase< Derived >::OffHeapHashTableBase().
FindEntry()
template<typename Derived >
template<typename IsolateT , typename FindKey >
InternalIndex v8::internal::OffHeapHashTableBase< Derived >::FindEntry (IsolateT * isolate, FindKey key, uint32_t hash) const [inline]
Definition at line 125 of file off-heap-hash-table-inl.h.
                                                                            {
  const Derived* derived_this = static_cast<const Derived*>(this);
  uint32_t count = 1;
  for (InternalIndex entry = FirstProbe(hash, capacity_);;
       entry = NextProbe(entry, count++, capacity_)) {
    // TODO(leszeks): Consider delaying the decompression until after the
    // comparisons against empty/deleted.
    Tagged<Object> element = derived_this->GetKey(isolate, entry);
    if (element == empty_element()) return InternalIndex::NotFound();
    if (element == deleted_element()) continue;
    if (Derived::KeyIsMatch(isolate, key, element)) return entry;
  }
}
Referenced by v8::internal::StringTable::LookupKey(), and v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting().
FindEntryOrInsertionEntry()
template<typename Derived >
template<typename IsolateT , typename FindKey >
InternalIndex v8::internal::OffHeapHashTableBase< Derived >::FindEntryOrInsertionEntry (IsolateT * isolate, FindKey key, uint32_t hash) const [inline]
Definition at line 159 of file off-heap-hash-table-inl.h.
                                                         {
  // The derived class must guarantee the hash table is never full.
  DCHECK(HasSufficientCapacityToAdd(1));
  const Derived* derived_this = static_cast<const Derived*>(this);
  InternalIndex insertion_entry = InternalIndex::NotFound();
  uint32_t count = 1;
  for (InternalIndex entry = FirstProbe(hash, capacity_);;
       entry = NextProbe(entry, count++, capacity_)) {
    // TODO(leszeks): Consider delaying the decompression until after the
    // comparisons against empty/deleted.
    Tagged<Object> element = derived_this->GetKey(isolate, entry);
    if (element == empty_element()) {
      // Empty entry, it's our insertion entry if there was no previous Hole.
      if (insertion_entry.is_not_found()) return entry;
      return insertion_entry;
    }
    if (element == deleted_element()) {
      // Holes are potential insertion candidates, but we continue the search
      // in case we find the actual matching entry.
      if (insertion_entry.is_not_found()) insertion_entry = entry;
      continue;
    }
    if (Derived::KeyIsMatch(isolate, key, element)) return entry;
  }
}
Referenced by v8::internal::StringTable::InsertForIsolateDeserialization(), and v8::internal::StringTable::LookupKey().
FindInsertionEntry()
template<typename Derived >
InternalIndex v8::internal::OffHeapHashTableBase< Derived >::FindInsertionEntry (PtrComprCageBase cage_base, uint32_t hash) const [inline]
Definition at line 142 of file off-heap-hash-table-inl.h.
                                                     {
  // The derived class must guarantee the hash table is never full.
  DCHECK(HasSufficientCapacityToAdd(1));
  const Derived* derived_this = static_cast<const Derived*>(this);
  uint32_t count = 1;
  for (InternalIndex entry = FirstProbe(hash, capacity_);;
       entry = NextProbe(entry, count++, capacity_)) {
    // TODO(leszeks): Consider delaying the decompression until after the
    // comparisons against empty/deleted.
    Tagged<Object> element = derived_this->GetKey(cage_base, entry);
    if (!IsKey(element)) return entry;
  }
}
Referenced by v8::internal::StringTable::InsertEmptyStringForBootstrapping().
FirstProbe()
template<typename Derived >
static InternalIndex v8::internal::OffHeapHashTableBase< Derived >::FirstProbe (uint32_t hash, uint32_t size) [inline], [static], [protected]
Definition at line 146 of file off-heap-hash-table.h.
                                                                       {
    return InternalIndex(hash & (size - 1));
  }
References size().
Free()
template<typename Derived >
void v8::internal::OffHeapHashTableBase< Derived >::Free (void * container) [inline], [static], [protected]
Definition at line 207 of file off-heap-hash-table-inl.h.
                                                    {
  AlignedFree(table);
}
References v8::internal::AlignedFree().
Referenced by v8::internal::SharedStructTypeRegistry::Data::operator delete().
GetSizeExcludingHeader() [1/2]
template<typename Derived >
size_t v8::internal::OffHeapHashTableBase< Derived >::GetSizeExcludingHeader () const [inline]
Definition at line 120 of file off-heap-hash-table.h.
                                        {
    return GetSizeExcludingHeader(capacity_);
  }
References v8::internal::OffHeapHashTableBase< Derived >::capacity_.
Referenced by v8::internal::StringTable::Data::GetCurrentMemoryUsage().
GetSizeExcludingHeader() [2/2]
template<typename Derived >
static size_t v8::internal::OffHeapHashTableBase< Derived >::GetSizeExcludingHeader (int capacity) [inline], [static], [protected]
Definition at line 167 of file off-heap-hash-table.h.
                                                            {
    // Subtract sizeof(Tagged_t) from the result, as the member elements_
    // already supplies the storage for the first element.
    return (capacity * sizeof(Tagged_t) * Derived::kEntrySize) -
           sizeof(Tagged_t);
  }
References v8::internal::OffHeapHashTableBase< Derived >::capacity(), and cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize.
HasSufficientCapacityToAdd() [1/2]
template<typename Derived >
bool v8::internal::OffHeapHashTableBase< Derived >::HasSufficientCapacityToAdd (int capacity, int number_of_elements, int number_of_deleted_elements, int number_of_additional_elements) [inline], [static], [protected]
Definition at line 72 of file off-heap-hash-table-inl.h.
                                       {
  int nof = number_of_elements + number_of_additional_elements;
  // Return true if:
  // 50% is still free after adding number_of_additional_elements elements and
  // at most 50% of the free elements are deleted elements.
  if ((nof < capacity) &&
      ((number_of_deleted_elements <= (capacity - nof) / 2))) {
    int needed_free = nof / 2;
    if (nof + needed_free <= capacity) return true;
  }
  return false;
}
HasSufficientCapacityToAdd() [2/2]
template<typename Derived >
bool v8::internal::OffHeapHashTableBase< Derived >::HasSufficientCapacityToAdd (int number_of_additional_elements) const [inline], [protected]
Definition at line 155 of file off-heap-hash-table.h.
                                                                           {
    return HasSufficientCapacityToAdd(capacity(), number_of_elements(),
                                      number_of_deleted_elements(),
                                      number_of_additional_elements);
  }
References v8::internal::OffHeapHashTableBase< Derived >::capacity(), v8::internal::OffHeapHashTableBase< Derived >::number_of_deleted_elements(), and v8::internal::OffHeapHashTableBase< Derived >::number_of_elements().
Referenced by v8::internal::OffHeapHashTableBase< Derived >::AddAt(), and v8::internal::OffHeapHashTableBase< Derived >::OverwriteDeletedAt().
IsKey()
template<typename Derived >
static bool v8::internal::OffHeapHashTableBase< Derived >::IsKey (Tagged< Object > k) [inline], [static]
Definition at line 73 of file off-heap-hash-table.h.
                                      {
    return k != empty_element() && k != deleted_element();
  }
References v8::internal::OffHeapHashTableBase< Derived >::deleted_element(), and v8::internal::OffHeapHashTableBase< Derived >::empty_element().
IterateElements()
template<typename Derived >
void v8::internal::OffHeapHashTableBase< Derived >::IterateElements (Root root, RootVisitor * visitor) [inline]
Definition at line 116 of file off-heap-hash-table-inl.h.
                                                                          {
  OffHeapObjectSlot first_slot = slot(InternalIndex(0));
  OffHeapObjectSlot end_slot = slot(InternalIndex(capacity_));
  visitor->VisitRootPointers(root, nullptr, first_slot, end_slot);
}
References v8::internal::RootVisitor::VisitRootPointers().
Referenced by v8::internal::StringTable::Data::IterateElements().
NextProbe()
template<typename Derived >
static InternalIndex v8::internal::OffHeapHashTableBase< Derived >::NextProbe (InternalIndex last, uint32_t number, uint32_t size) [inline], [static], [protected]
Definition at line 150 of file off-heap-hash-table.h.
                                                       {
    return InternalIndex((last.as_uint32() + number) & (size - 1));
  }
References v8::internal::InternalIndex::as_uint32(), and size().
number_of_deleted_elements()
template<typename Derived >
int v8::internal::OffHeapHashTableBase< Derived >::number_of_deleted_elements () const [inline]
Definition at line 79 of file off-heap-hash-table.h.
{ return number_of_deleted_elements_; }
References v8::internal::OffHeapHashTableBase< Derived >::number_of_deleted_elements_.
Referenced by v8::internal::OffHeapHashTableBase< Derived >::HasSufficientCapacityToAdd(), and v8::internal::OffHeapHashTableBase< Derived >::OverwriteDeletedAt().
number_of_elements()
template<typename Derived >
int v8::internal::OffHeapHashTableBase< Derived >::number_of_elements () const [inline]
Definition at line 78 of file off-heap-hash-table.h.
{ return number_of_elements_; }
References v8::internal::OffHeapHashTableBase< Derived >::number_of_elements_.
Referenced by v8::internal::OffHeapHashTableBase< Derived >::HasSufficientCapacityToAdd(), and v8::internal::OffHeapHashTableBase< Derived >::OverwriteDeletedAt().
OverwriteDeletedAt()
template<typename Derived >
template<typename... Args>
void v8::internal::OffHeapHashTableBase< Derived >::OverwriteDeletedAt (PtrComprCageBase cage_base, InternalIndex entry, Args &&... args) [inline]
Definition at line 100 of file off-heap-hash-table.h.
                                          {
    Derived* derived_this = static_cast<Derived*>(this);
    DCHECK_EQ(derived_this->GetKey(cage_base, entry), deleted_element());
    DCHECK_LT(number_of_elements_ + 1, capacity());
    DCHECK(HasSufficientCapacityToAdd(capacity(), number_of_elements(),
                                      number_of_deleted_elements() - 1, 1));
    derived_this->Set(entry, std::forward<Args>(args)...);
    number_of_elements_++;
    number_of_deleted_elements_--;
  }
References v8::base::args, v8::internal::OffHeapHashTableBase< Derived >::capacity(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, v8::internal::OffHeapHashTableBase< Derived >::deleted_element(), v8::internal::OffHeapHashTableBase< Derived >::HasSufficientCapacityToAdd(), v8::internal::OffHeapHashTableBase< Derived >::number_of_deleted_elements(), v8::internal::OffHeapHashTableBase< Derived >::number_of_deleted_elements_, v8::internal::OffHeapHashTableBase< Derived >::number_of_elements(), and v8::internal::OffHeapHashTableBase< Derived >::number_of_elements_.
Referenced by v8::internal::StringTable::LookupKey().
RehashInto()
template<typename Derived >
void v8::internal::OffHeapHashTableBase< Derived >::RehashInto (PtrComprCageBase cage_base, Derived * new_table) [inline]
Definition at line 26 of file off-heap-hash-table-inl.h.
                                                                   {
  DCHECK_LT(number_of_elements(), new_table->capacity());
  DCHECK(new_table->HasSufficientCapacityToAdd(number_of_elements()));
  Derived* derived_this = static_cast<Derived*>(this);
  // Rehash the elements and copy them into new_table.
  for (InternalIndex i : InternalIndex::Range(capacity())) {
    Tagged<Object> key = derived_this->GetKey(cage_base, i);
    if (!IsKey(key)) continue;
    uint32_t hash = Derived::Hash(cage_base, key);
    InternalIndex insertion_index =
        new_table->FindInsertionEntry(cage_base, hash);
    new_table->SetKey(insertion_index, key);
    derived_this->CopyEntryExcludingKeyInto(cage_base, i, new_table,
                                            insertion_index);
  }
  new_table->number_of_elements_ = number_of_elements();
}
References v8::internal::DCHECK(), DCHECK_LT, v8::internal::Hash(), and v8::internal::key.
ShouldResizeToAdd()
template<typename Derived >
bool v8::internal::OffHeapHashTableBase< Derived >::ShouldResizeToAdd (int number_of_additional_elements, int * new_capacity) [inline]
Definition at line 47 of file off-heap-hash-table-inl.h.
                                                {
  DCHECK_NOT_NULL(new_capacity);
  // Grow or shrink table if needed. We first try to shrink the table, if it
  // is sufficiently empty; otherwise we make sure to grow it so that it has
  // enough space.
  int capacity_after_shrinking = ComputeCapacityWithShrink(
      capacity_, number_of_elements_ + additional_elements);
  if (capacity_after_shrinking < capacity_) {
    DCHECK(HasSufficientCapacityToAdd(
        capacity_after_shrinking, number_of_elements_, 0, additional_elements));
    *new_capacity = capacity_after_shrinking;
    return true;
  } else if (!HasSufficientCapacityToAdd(additional_elements)) {
    *new_capacity = ComputeCapacity(number_of_elements_ + additional_elements);
    return true;
  } else {
    *new_capacity = -1;
    return false;
  }
}
References v8::internal::DCHECK(), and DCHECK_NOT_NULL.
Referenced by v8::internal::StringTable::EnsureCapacity().
slot()
template<typename Derived >
OffHeapObjectSlot v8::internal::OffHeapHashTableBase< Derived >::slot (InternalIndex index, int offset = 0) const [inline]
Definition at line 81 of file off-heap-hash-table.h.
                                                                    {
    DCHECK_LT(offset, Derived::kEntrySize);
    return OffHeapObjectSlot(
        &elements_[index.as_uint32() * Derived::kEntrySize + offset]);
  }
References DCHECK_LT, v8::internal::OffHeapHashTableBase< Derived >::elements_, v8::internal::index, and cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize.
Referenced by v8::internal::OffHeapHashTableBase< Derived >::OffHeapHashTableBase().
Member Data Documentation
capacity_
template<typename Derived >
const int v8::internal::OffHeapHashTableBase< Derived >::capacity_ [protected]
Definition at line 184 of file off-heap-hash-table.h.
Referenced by v8::internal::OffHeapHashTableBase< Derived >::capacity(), and v8::internal::OffHeapHashTableBase< Derived >::GetSizeExcludingHeader().
elements_
template<typename Derived >
Tagged_t v8::internal::OffHeapHashTableBase< Derived >::elements_[1] [protected]
Definition at line 185 of file off-heap-hash-table.h.
Referenced by v8::internal::OffHeapHashTableBase< Derived >::slot().
number_of_deleted_elements_
template<typename Derived >
int v8::internal::OffHeapHashTableBase< Derived >::number_of_deleted_elements_ [protected]
Definition at line 183 of file off-heap-hash-table.h.
Referenced by v8::internal::OffHeapHashTableBase< Derived >::ElementsRemoved(), v8::internal::OffHeapHashTableBase< Derived >::number_of_deleted_elements(), and v8::internal::OffHeapHashTableBase< Derived >::OverwriteDeletedAt().
number_of_elements_
template<typename Derived >
int v8::internal::OffHeapHashTableBase< Derived >::number_of_elements_ [protected]
Definition at line 182 of file off-heap-hash-table.h.
Referenced by v8::internal::OffHeapHashTableBase< Derived >::AddAt(), v8::internal::OffHeapHashTableBase< Derived >::ElementsRemoved(), v8::internal::OffHeapHashTableBase< Derived >::number_of_elements(), and v8::internal::OffHeapHashTableBase< Derived >::OverwriteDeletedAt().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/off-heap-hash-table.h
/mnt/V8SourceCode/src/objects/off-heap-hash-table-inl.h