v8::internal::compiler::UsePosition Class Reference
#include <register-allocator.h>
Classes
struct Ordering
Public Member Functions
UsePosition (LifetimePosition pos, InstructionOperand *operand, void *hint, UsePositionHintType hint_type)
UsePosition (const UsePosition &)=delete
UsePosition & operator= (const UsePosition &)=delete
InstructionOperand * operand () const
bool HasOperand () const
bool RegisterIsBeneficial () const
bool SpillDetrimental () const
UsePositionType type () const
void set_type (UsePositionType type, bool register_beneficial)
LifetimePosition pos () const
void set_assigned_register (int register_code)
void set_spill_detrimental ()
UsePositionHintType hint_type () const
bool HasHint () const
bool HintRegister (int *register_code) const
void SetHint (UsePosition *use_pos)
void ResolveHint (UsePosition *use_pos)
bool IsResolved () const
Static Public Member Functions
static UsePositionHintType HintTypeForOperand (const InstructionOperand &op)
Private Types
using TypeField = base::BitField< UsePositionType, 0, 2 >
using HintTypeField = base::BitField< UsePositionHintType, 2, 3 >
using RegisterBeneficialField = base::BitField< bool, 5, 1 >
using AssignedRegisterField = base::BitField< int32_t, 6, 6 >
using SpillDetrimentalField = base::BitField< int32_t, 12, 1 >
Private Attributes
InstructionOperand *const operand_
void * hint_
LifetimePosition const pos_
uint32_t flags_
Detailed Description
Definition at line 465 of file register-allocator.h.
Member Typedef Documentation
AssignedRegisterField
using v8::internal::compiler::UsePosition::AssignedRegisterField = base::BitField<int32_t, 6, 6> [private]
Definition at line 518 of file register-allocator.h.
HintTypeField
using v8::internal::compiler::UsePosition::HintTypeField = base::BitField<UsePositionHintType, 2, 3> [private]
Definition at line 516 of file register-allocator.h.
RegisterBeneficialField
using v8::internal::compiler::UsePosition::RegisterBeneficialField = base::BitField<bool, 5, 1> [private]
Definition at line 517 of file register-allocator.h.
SpillDetrimentalField
using v8::internal::compiler::UsePosition::SpillDetrimentalField = base::BitField<int32_t, 12, 1> [private]
Definition at line 519 of file register-allocator.h.
TypeField
using v8::internal::compiler::UsePosition::TypeField = base::BitField<UsePositionType, 0, 2> [private]
Definition at line 515 of file register-allocator.h.
Constructor & Destructor Documentation
UsePosition() [1/2]
v8::internal::compiler::UsePosition::UsePosition (LifetimePosition pos, InstructionOperand * operand, void * hint, UsePositionHintType hint_type)
Definition at line 71 of file register-allocator.cc.
    : operand_(operand), hint_(hint), pos_(pos), flags_(0) {
  DCHECK_IMPLIES(hint == nullptr, hint_type == UsePositionHintType::kNone);
  bool register_beneficial = true;
  UsePositionType type = UsePositionType::kRegisterOrSlot;
  if (operand_ != nullptr && operand_->IsUnallocated()) {
    const UnallocatedOperand* unalloc = UnallocatedOperand::cast(operand_);
    if (unalloc->HasRegisterPolicy()) {
      type = UsePositionType::kRequiresRegister;
    } else if (unalloc->HasSlotPolicy()) {
      type = UsePositionType::kRequiresSlot;
      register_beneficial = false;
    } else if (unalloc->HasRegisterOrSlotOrConstantPolicy()) {
      type = UsePositionType::kRegisterOrSlotOrConstant;
      register_beneficial = false;
    } else {
      register_beneficial = !unalloc->HasRegisterOrSlotPolicy();
    }
  }
  flags_ = TypeField::encode(type) | HintTypeField::encode(hint_type) |
           RegisterBeneficialField::encode(register_beneficial) |
           AssignedRegisterField::encode(kUnassignedRegister);
  DCHECK(pos_.IsValid());
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::base::BitField< T, shift, size, U >::encode(), flags_, v8::internal::compiler::UnallocatedOperand::HasRegisterOrSlotOrConstantPolicy(), v8::internal::compiler::UnallocatedOperand::HasRegisterOrSlotPolicy(), v8::internal::compiler::UnallocatedOperand::HasRegisterPolicy(), v8::internal::compiler::UnallocatedOperand::HasSlotPolicy(), hint_type(), v8::internal::compiler::LifetimePosition::IsValid(), v8::internal::compiler::kNone, v8::internal::compiler::kRegisterOrSlot, v8::internal::compiler::kRegisterOrSlotOrConstant, v8::internal::compiler::kRequiresRegister, v8::internal::compiler::kRequiresSlot, v8::internal::compiler::kUnassignedRegister, operand_, pos_, and type().
UsePosition() [2/2]
v8::internal::compiler::UsePosition::UsePosition (const UsePosition &) [delete]
Member Function Documentation
HasHint()
bool v8::internal::compiler::UsePosition::HasHint () const
Definition at line 97 of file register-allocator.cc.
                                {
  int hint_register;
  return HintRegister(&hint_register);
}
References HintRegister().
HasOperand()
bool v8::internal::compiler::UsePosition::HasOperand () const [inline]
Definition at line 474 of file register-allocator.h.
{ return operand_ != nullptr; }
hint_type()
UsePositionHintType v8::internal::compiler::UsePosition::hint_type () const [inline]
Definition at line 496 of file register-allocator.h.
                                        {
    return HintTypeField::decode(flags_);
  }
Referenced by UsePosition().
HintRegister()
bool v8::internal::compiler::UsePosition::HintRegister (int * register_code) const
Definition at line 102 of file register-allocator.cc.
                                                       {
  if (hint_ == nullptr) return false;
  switch (HintTypeField::decode(flags_)) {
    case UsePositionHintType::kNone:
    case UsePositionHintType::kUnresolved:
      return false;
    case UsePositionHintType::kUsePos: {
      UsePosition* use_pos = reinterpret_cast<UsePosition*>(hint_);
      int assigned_register = AssignedRegisterField::decode(use_pos->flags_);
      if (assigned_register == kUnassignedRegister) return false;
      *register_code = assigned_register;
      return true;
    }
    case UsePositionHintType::kOperand: {
      InstructionOperand* operand =
          reinterpret_cast<InstructionOperand*>(hint_);
      *register_code = LocationOperand::cast(operand)->register_code();
      return true;
    }
    case UsePositionHintType::kPhi: {
      RegisterAllocationData::PhiMapValue* phi =
          reinterpret_cast<RegisterAllocationData::PhiMapValue*>(hint_);
      int assigned_register = phi->assigned_register();
      if (assigned_register == kUnassignedRegister) return false;
      *register_code = assigned_register;
      return true;
    }
  }
  UNREACHABLE();
}
References v8::internal::compiler::RegisterAllocationData::PhiMapValue::assigned_register(), v8::internal::compiler::LocationOperand::cast(), v8::base::BitField< T, shift, size, U >::decode(), flags_, hint_, v8::internal::compiler::kNone, v8::internal::compiler::kOperand, v8::internal::compiler::kPhi, v8::internal::compiler::kUnassignedRegister, v8::internal::compiler::kUnresolved, v8::internal::compiler::kUsePos, operand(), v8::internal::compiler::LocationOperand::register_code(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), and HasHint().
HintTypeForOperand()
UsePositionHintType v8::internal::compiler::UsePosition::HintTypeForOperand (const InstructionOperand & op) [static]
Definition at line 133 of file register-allocator.cc.
                                  {
  switch (op.kind()) {
    case InstructionOperand::CONSTANT:
    case InstructionOperand::IMMEDIATE:
      return UsePositionHintType::kNone;
    case InstructionOperand::UNALLOCATED:
      return UsePositionHintType::kUnresolved;
    case InstructionOperand::ALLOCATED:
      if (op.IsRegister() || op.IsFPRegister()) {
        return UsePositionHintType::kOperand;
      } else {
        DCHECK(op.IsStackSlot() || op.IsFPStackSlot());
        return UsePositionHintType::kNone;
      }
    case InstructionOperand::PENDING:
    case InstructionOperand::INVALID:
      break;
  }
  UNREACHABLE();
}
References v8::internal::compiler::InstructionOperand::ALLOCATED, v8::internal::compiler::InstructionOperand::CONSTANT, v8::internal::DCHECK(), v8::internal::compiler::InstructionOperand::IMMEDIATE, v8::internal::compiler::InstructionOperand::INVALID, v8::internal::compiler::InstructionOperand::IsFPRegister(), v8::internal::compiler::InstructionOperand::IsFPStackSlot(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::compiler::InstructionOperand::kind(), v8::internal::compiler::kNone, v8::internal::compiler::kOperand, v8::internal::compiler::kUnresolved, v8::internal::compiler::InstructionOperand::PENDING, v8::internal::compiler::InstructionOperand::UNALLOCATED, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), and v8::internal::compiler::LiveRangeBuilder::ProcessPhis().
IsResolved()
bool v8::internal::compiler::UsePosition::IsResolved () const [inline]
Definition at line 503 of file register-allocator.h.
                          {
    return hint_type() != UsePositionHintType::kUnresolved;
  }
References v8::internal::compiler::kUnresolved.
Referenced by v8::internal::compiler::LiveRangeBuilder::MapPhiHint(), and v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
operand()
InstructionOperand* v8::internal::compiler::UsePosition::operand () const [inline]
Definition at line 473 of file register-allocator.h.
{ return operand_; }
Referenced by HintRegister().
operator=()
UsePosition& v8::internal::compiler::UsePosition::operator= (const UsePosition &) [delete]
pos()
LifetimePosition v8::internal::compiler::UsePosition::pos () const [inline]
Definition at line 486 of file register-allocator.h.
{ return pos_; }
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUsePosition(), v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LiveRange::CanBeSpilled(), v8::internal::compiler::RegisterAllocator::FindOptimalSpillingPos(), v8::internal::compiler::LiveRange::NextLifetimePositionRegisterIsBeneficial(), v8::internal::compiler::UsePosition::Ordering::operator()(), v8::internal::compiler::LiveRange::ShouldBeAllocatedBefore(), v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges(), v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand(), and v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
RegisterIsBeneficial()
bool v8::internal::compiler::UsePosition::RegisterIsBeneficial () const [inline]
Definition at line 476 of file register-allocator.h.
                                    {
    return RegisterBeneficialField::decode(flags_);
  }
ResolveHint()
void v8::internal::compiler::UsePosition::ResolveHint (UsePosition * use_pos)
Definition at line 161 of file register-allocator.cc.
                                                  {
  DCHECK_NOT_NULL(use_pos);
  if (HintTypeField::decode(flags_) != UsePositionHintType::kUnresolved) return;
  hint_ = use_pos;
  flags_ = HintTypeField::update(flags_, UsePositionHintType::kUsePos);
}
References DCHECK_NOT_NULL, v8::base::BitField< T, shift, size, U >::decode(), flags_, hint_, v8::internal::compiler::kUnresolved, v8::internal::compiler::kUsePos, and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
set_assigned_register()
void v8::internal::compiler::UsePosition::set_assigned_register (int register_code) [inline]
Definition at line 489 of file register-allocator.h.
                                                {
    flags_ = AssignedRegisterField::update(flags_, register_code);
  }
set_spill_detrimental()
void v8::internal::compiler::UsePosition::set_spill_detrimental () [inline]
Definition at line 492 of file register-allocator.h.
                               {
    flags_ = SpillDetrimentalField::update(flags_, true);
  }
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
set_type()
void v8::internal::compiler::UsePosition::set_type (UsePositionType type, bool register_beneficial)
Definition at line 168 of file register-allocator.cc.
                                                                         {
  DCHECK_IMPLIES(type == UsePositionType::kRequiresSlot, !register_beneficial);
  DCHECK_EQ(kUnassignedRegister, AssignedRegisterField::decode(flags_));
  flags_ = TypeField::encode(type) |
           RegisterBeneficialField::encode(register_beneficial) |
           HintTypeField::encode(HintTypeField::decode(flags_)) |
           AssignedRegisterField::encode(kUnassignedRegister);
}
References DCHECK_EQ, DCHECK_IMPLIES, v8::base::BitField< T, shift, size, U >::decode(), v8::base::BitField< T, shift, size, U >::encode(), flags_, v8::internal::compiler::kRequiresSlot, v8::internal::compiler::kUnassignedRegister, and type().
SetHint()
void v8::internal::compiler::UsePosition::SetHint (UsePosition * use_pos)
Definition at line 155 of file register-allocator.cc.
                                              {
  DCHECK_NOT_NULL(use_pos);
  hint_ = use_pos;
  flags_ = HintTypeField::update(flags_, UsePositionHintType::kUsePos);
}
References DCHECK_NOT_NULL, flags_, hint_, v8::internal::compiler::kUsePos, and v8::base::BitField< T, shift, size, U >::update().
SpillDetrimental()
bool v8::internal::compiler::UsePosition::SpillDetrimental () const [inline]
Definition at line 479 of file register-allocator.h.
                                {
    return SpillDetrimentalField::decode(flags_);
  }
type()
UsePositionType v8::internal::compiler::UsePosition::type () const [inline]
Definition at line 483 of file register-allocator.h.
{ return TypeField::decode(flags_); }
Referenced by set_type(), and UsePosition().
Member Data Documentation
flags_
uint32_t v8::internal::compiler::UsePosition::flags_ [private]
Definition at line 524 of file register-allocator.h.
Referenced by HintRegister(), ResolveHint(), set_type(), SetHint(), and UsePosition().
hint_
void* v8::internal::compiler::UsePosition::hint_ [private]
Definition at line 522 of file register-allocator.h.
Referenced by HintRegister(), ResolveHint(), and SetHint().
operand_
InstructionOperand* const v8::internal::compiler::UsePosition::operand_ [private]
Definition at line 521 of file register-allocator.h.
Referenced by UsePosition().
pos_
LifetimePosition const v8::internal::compiler::UsePosition::pos_ [private]
Definition at line 523 of file register-allocator.h.
Referenced by UsePosition().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc