v8::internal::compiler::DeoptimizationExit Class Reference
#include <code-generator-impl.h>
Public Member Functions
DeoptimizationExit (SourcePosition pos, BytecodeOffset bailout_id, int translation_id, int pc_offset, DeoptimizeKind kind, DeoptimizeReason reason, NodeId node_id)
bool has_deoptimization_id () const
int deoptimization_id () const
void set_deoptimization_id (int deoptimization_id)
SourcePosition pos () const
Label * label ()
Label * continue_label ()
BytecodeOffset bailout_id () const
int translation_id () const
int pc_offset () const
DeoptimizeKind kind () const
DeoptimizeReason reason () const
NodeId node_id () const
const ZoneVector< ImmediateOperand * > * immediate_args () const
void set_immediate_args (ZoneVector< ImmediateOperand * > *immediate_args)
bool emitted () const
void set_emitted ()
Private Attributes
int deoptimization_id_
const SourcePosition pos_
Label label_
Label continue_label_
const BytecodeOffset bailout_id_
const int translation_id_
const int pc_offset_
const DeoptimizeKind kind_
const DeoptimizeReason reason_
const NodeId node_id_
ZoneVector< ImmediateOperand * > * immediate_args_
bool emitted_
Static Private Attributes
static const int kNoDeoptIndex = kMaxInt16 + 1
Detailed Description
Definition at line 225 of file code-generator-impl.h.
Constructor & Destructor Documentation
DeoptimizationExit()
v8::internal::compiler::DeoptimizationExit::DeoptimizationExit (SourcePosition pos, BytecodeOffset bailout_id, int translation_id, int pc_offset, DeoptimizeKind kind, DeoptimizeReason reason, NodeId node_id) [inline], [explicit]
Definition at line 227 of file code-generator-impl.h.
      : deoptimization_id_(kNoDeoptIndex),
        pos_(pos),
        bailout_id_(bailout_id),
        translation_id_(translation_id),
        pc_offset_(pc_offset),
        kind_(kind),
        reason_(reason),
        node_id_(node_id),
        immediate_args_(nullptr),
        emitted_(false) {}
Member Function Documentation
bailout_id()
BytecodeOffset v8::internal::compiler::DeoptimizationExit::bailout_id () const [inline]
Definition at line 257 of file code-generator-impl.h.
{ return bailout_id_; }
References bailout_id_.
Referenced by v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData().
continue_label()
Label* v8::internal::compiler::DeoptimizationExit::continue_label () [inline]
Definition at line 256 of file code-generator-impl.h.
{ return &continue_label_; }
References continue_label_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleDeoptimizerCall(), and v8::internal::compiler::CodeGenerator::AssembleInstruction().
deoptimization_id()
int v8::internal::compiler::DeoptimizationExit::deoptimization_id () const [inline]
Definition at line 245 of file code-generator-impl.h.
                                {
    DCHECK(has_deoptimization_id());
    return deoptimization_id_;
  }
References v8::internal::DCHECK(), deoptimization_id_, and has_deoptimization_id().
Referenced by v8::internal::compiler::CodeGenerator::AssembleDeoptimizerCall(), v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), and set_deoptimization_id().
emitted()
bool v8::internal::compiler::DeoptimizationExit::emitted () const [inline]
Definition at line 272 of file code-generator-impl.h.
{ return emitted_; }
References emitted_.
has_deoptimization_id()
bool v8::internal::compiler::DeoptimizationExit::has_deoptimization_id () const [inline]
Definition at line 242 of file code-generator-impl.h.
                                     {
    return deoptimization_id_ != kNoDeoptIndex;
  }
References deoptimization_id_, and kNoDeoptIndex.
Referenced by deoptimization_id().
immediate_args()
const ZoneVector<ImmediateOperand*>* v8::internal::compiler::DeoptimizationExit::immediate_args () const [inline]
Definition at line 263 of file code-generator-impl.h.
                                                              {
    return immediate_args_;
  }
References immediate_args_.
Referenced by set_immediate_args().
kind()
DeoptimizeKind v8::internal::compiler::DeoptimizationExit::kind () const [inline]
Definition at line 260 of file code-generator-impl.h.
{ return kind_; }
References kind_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode(), and v8::internal::compiler::CodeGenerator::AssembleDeoptimizerCall().
label()
Label* v8::internal::compiler::DeoptimizationExit::label () [inline]
Definition at line 254 of file code-generator-impl.h.
{ return &label_; }
References label_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleDeoptimizerCall(), and v8::internal::compiler::CodeGenerator::AssembleInstruction().
node_id()
NodeId v8::internal::compiler::DeoptimizationExit::node_id () const [inline]
Definition at line 262 of file code-generator-impl.h.
{ return node_id_; }
References node_id_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleDeoptimizerCall(), and v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData().
pc_offset()
int v8::internal::compiler::DeoptimizationExit::pc_offset () const [inline]
Definition at line 259 of file code-generator-impl.h.
{ return pc_offset_; }
References pc_offset_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode(), and v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData().
pos()
SourcePosition v8::internal::compiler::DeoptimizationExit::pos () const [inline]
Definition at line 252 of file code-generator-impl.h.
{ return pos_; }
References pos_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleDeoptimizerCall().
reason()
DeoptimizeReason v8::internal::compiler::DeoptimizationExit::reason () const [inline]
Definition at line 261 of file code-generator-impl.h.
{ return reason_; }
References reason_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleDeoptimizerCall().
set_deoptimization_id()
void v8::internal::compiler::DeoptimizationExit::set_deoptimization_id (int deoptimization_id) [inline]
Definition at line 249 of file code-generator-impl.h.
                                                    {
    deoptimization_id_ = deoptimization_id;
  }
References deoptimization_id(), and deoptimization_id_.
set_emitted()
void v8::internal::compiler::DeoptimizationExit::set_emitted () [inline]
Definition at line 273 of file code-generator-impl.h.
{ emitted_ = true; }
References emitted_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleDeoptimizerCall().
set_immediate_args()
void v8::internal::compiler::DeoptimizationExit::set_immediate_args (ZoneVector< ImmediateOperand * > * immediate_args) [inline]
Definition at line 266 of file code-generator-impl.h.
                                                                         {
    immediate_args_ = immediate_args;
  }
References immediate_args(), and immediate_args_.
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslation().
translation_id()
int v8::internal::compiler::DeoptimizationExit::translation_id () const [inline]
Definition at line 258 of file code-generator-impl.h.
{ return translation_id_; }
References translation_id_.
Referenced by v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData().
Member Data Documentation
bailout_id_
const BytecodeOffset v8::internal::compiler::DeoptimizationExit::bailout_id_ [private]
Definition at line 281 of file code-generator-impl.h.
Referenced by bailout_id().
continue_label_
Label v8::internal::compiler::DeoptimizationExit::continue_label_ [private]
Definition at line 280 of file code-generator-impl.h.
Referenced by continue_label().
deoptimization_id_
int v8::internal::compiler::DeoptimizationExit::deoptimization_id_ [private]
Definition at line 277 of file code-generator-impl.h.
Referenced by deoptimization_id(), has_deoptimization_id(), and set_deoptimization_id().
emitted_
bool v8::internal::compiler::DeoptimizationExit::emitted_ [private]
Definition at line 288 of file code-generator-impl.h.
Referenced by emitted(), and set_emitted().
immediate_args_
ZoneVector<ImmediateOperand*>* v8::internal::compiler::DeoptimizationExit::immediate_args_ [private]
Definition at line 287 of file code-generator-impl.h.
Referenced by immediate_args(), and set_immediate_args().
kind_
const DeoptimizeKind v8::internal::compiler::DeoptimizationExit::kind_ [private]
Definition at line 284 of file code-generator-impl.h.
Referenced by kind().
kNoDeoptIndex
const int v8::internal::compiler::DeoptimizationExit::kNoDeoptIndex = kMaxInt16 + 1 [static], [private]
Definition at line 276 of file code-generator-impl.h.
Referenced by has_deoptimization_id().
label_
Label v8::internal::compiler::DeoptimizationExit::label_ [private]
Definition at line 279 of file code-generator-impl.h.
Referenced by label().
node_id_
const NodeId v8::internal::compiler::DeoptimizationExit::node_id_ [private]
Definition at line 286 of file code-generator-impl.h.
Referenced by node_id().
pc_offset_
const int v8::internal::compiler::DeoptimizationExit::pc_offset_ [private]
Definition at line 283 of file code-generator-impl.h.
Referenced by pc_offset().
pos_
const SourcePosition v8::internal::compiler::DeoptimizationExit::pos_ [private]
Definition at line 278 of file code-generator-impl.h.
Referenced by pos().
reason_
const DeoptimizeReason v8::internal::compiler::DeoptimizationExit::reason_ [private]
Definition at line 285 of file code-generator-impl.h.
Referenced by reason().
translation_id_
const int v8::internal::compiler::DeoptimizationExit::translation_id_ [private]
Definition at line 282 of file code-generator-impl.h.
Referenced by translation_id().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/code-generator-impl.h