v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileJob Class Reference
Public Member Functions
BackgroundCompileJob (std::weak_ptr< NativeModule > native_module, std::shared_ptr< Counters > async_counters, CompilationTier tier)
void Run (JobDelegate *delegate) override
size_t GetMaxConcurrency (size_t worker_count) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Private Attributes
std::weak_ptr< NativeModule > native_module_
std::shared_ptr< OperationsBarrier > engine_barrier_
const std::shared_ptr< Counters > async_counters_
const CompilationTier tier_
Detailed Description
Definition at line 2342 of file module-compiler.cc.
Constructor & Destructor Documentation
BackgroundCompileJob()
v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileJob::BackgroundCompileJob (std::weak_ptr< NativeModule > native_module, std::shared_ptr< Counters > async_counters, CompilationTier tier) [inline], [explicit]
Definition at line 2344 of file module-compiler.cc.
      : native_module_(std::move(native_module)),
        engine_barrier_(GetWasmEngine()->GetBarrierForBackgroundCompile()),
        async_counters_(std::move(async_counters)),
        tier_(tier) {}
Member Function Documentation
GetMaxConcurrency()
size_t v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileJob::GetMaxConcurrency (size_t worker_count) const [inline], [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 2359 of file module-compiler.cc.
                                                               {
    BackgroundCompileScope compile_scope(native_module_);
    if (compile_scope.cancelled()) return 0;
    size_t flag_limit = static_cast<size_t>(
        std::max(1, v8_flags.wasm_num_compilation_tasks.value()));
    // NumOutstandingCompilations() does not reflect the units that running
    // workers are processing, thus add the current worker count to that number.
    return std::min(flag_limit,
                    worker_count + compile_scope.compilation_state()
                                       ->NumOutstandingCompilations(tier_));
  }
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileScope::cancelled(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileScope::compilation_state(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::NumOutstandingCompilations(), and v8::internal::v8_flags.
Run()
void v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileJob::Run (JobDelegate * delegate) [inline], [override], [virtual]
Implements v8::JobTask.
Definition at line 2352 of file module-compiler.cc.
                                           {
    auto engine_scope = engine_barrier_->TryLock();
    if (!engine_scope) return;
    ExecuteCompilationUnits(native_module_, async_counters_.get(), delegate,
                            tier_);
  }
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits().
Member Data Documentation
async_counters_
const std::shared_ptr<Counters> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileJob::async_counters_ [private]
Definition at line 2374 of file module-compiler.cc.
engine_barrier_
std::shared_ptr<OperationsBarrier> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileJob::engine_barrier_ [private]
Definition at line 2373 of file module-compiler.cc.
native_module_
std::weak_ptr<NativeModule> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileJob::native_module_ [private]
Definition at line 2372 of file module-compiler.cc.
tier_
const CompilationTier v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileJob::tier_ [private]
Definition at line 2375 of file module-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc