v8::internal::baseline::BaselineCompiler Class Reference
#include <baseline-compiler.h>
Public Member Functions
BaselineCompiler (LocalIsolate *local_isolate, Handle< SharedFunctionInfo > shared_function_info, Handle< BytecodeArray > bytecode)
void GenerateCode ()
MaybeHandle< Code > Build ()
Static Public Member Functions
static int EstimateInstructionSize (Tagged< BytecodeArray > bytecode)
Private Types
enum StackCheckBehavior { kEnableStackCheck
, kDisableStackCheck
 }
enum class MarkAsIndirectJumpTarget { kNo
, kYes
 }
Private Member Functions
void Prologue ()
void PrologueFillFrame ()
void PrologueHandleOptimizationState (Register feedback_vector)
void PreVisitSingleBytecode ()
void VisitSingleBytecode ()
void VerifyFrame ()
void VerifyFrameSize ()
interpreter::Register RegisterOperand (int operand_index)
void LoadRegister (Register output, int operand_index)
void StoreRegister (int operand_index, Register value)
void StoreRegisterPair (int operand_index, Register val0, Register val1)
template<typename Type >
Handle< Type > Constant (int operand_index)
Tagged< Smi > ConstantSmi (int operand_index)
template<typename Type >
void LoadConstant (Register output, int operand_index)
uint32_t Uint (int operand_index)
int32_t Int (int operand_index)
uint32_t Index (int operand_index)
uint32_t Flag8 (int operand_index)
uint32_t Flag16 (int operand_index)
uint32_t RegisterCount (int operand_index)
Tagged< TaggedIndex > IndexAsTagged (int operand_index)
Tagged< TaggedIndex > UintAsTagged (int operand_index)
Tagged< Smi > IndexAsSmi (int operand_index)
Tagged< Smi > IntAsSmi (int operand_index)
Tagged< Smi > UintAsSmi (int operand_index)
Tagged< Smi > Flag8AsSmi (int operand_index)
Tagged< Smi > Flag16AsSmi (int operand_index)
Label * NewLabel ()
Label * BuildForwardJumpLabel ()
void UpdateInterruptBudgetAndJumpToLabel (int weight, Label *label, Label *skip_interrupt_label, StackCheckBehavior stack_check_behavior)
void JumpIfRoot (RootIndex root)
void JumpIfNotRoot (RootIndex root)
MemOperand FeedbackVector ()
void LoadFeedbackVector (Register output)
void LoadClosureFeedbackArray (Register output)
void AddPosition ()
void SelectBooleanConstant (Register output, std::function< void(Label *, Label::Distance)> jump_func)
void JumpIfToBoolean (bool do_jump_if_true, Label *label, Label::Distance distance=Label::kFar)
template<Builtin kBuiltin, typename... Args>
void CallBuiltin (Args... args)
template<typename... Args>
void CallRuntime (Runtime::FunctionId function, Args... args)
template<Builtin kBuiltin, typename... Args>
void TailCallBuiltin (Args... args)
template<ConvertReceiverMode kMode, typename... Args>
void BuildCall (uint32_t slot, uint32_t arg_count, Args... args)
const interpreter::BytecodeArrayIterator & iterator ()
Label * EnsureLabel (int offset, MarkAsIndirectJumpTarget mark=MarkAsIndirectJumpTarget::kNo)
bool IsJumpTarget (int offset) const
bool IsIndirectJumpTarget (int offset) const
void MarkIndirectJumpTarget (int offset)
Private Attributes
LocalIsolate * local_isolate_
RuntimeCallStats * stats_
Handle< SharedFunctionInfo > shared_function_info_
Handle< HeapObject > interpreter_data_
Handle< BytecodeArray > bytecode_
Zone zone_
MacroAssembler masm_
BaselineAssembler basm_
interpreter::BytecodeArrayIterator iterator_
BytecodeOffsetTableBuilder bytecode_offset_table_builder_
Label * labels_
BitVector label_tags_
Detailed Description
Definition at line 50 of file baseline-compiler.h.
Member Enumeration Documentation
MarkAsIndirectJumpTarget
enum v8::internal::baseline::BaselineCompiler::MarkAsIndirectJumpTarget [strong], [private]
Enumerator
kNo
kYes
Definition at line 174 of file baseline-compiler.h.
{ kNo, kYes };
StackCheckBehavior
enum v8::internal::baseline::BaselineCompiler::StackCheckBehavior [private]
Enumerator
kEnableStackCheck
kDisableStackCheck
Definition at line 102 of file baseline-compiler.h.
                          {
    kEnableStackCheck,
    kDisableStackCheck,
  };
Constructor & Destructor Documentation
BaselineCompiler()
v8::internal::baseline::BaselineCompiler::BaselineCompiler (LocalIsolate * local_isolate, Handle< SharedFunctionInfo > shared_function_info, Handle< BytecodeArray > bytecode) [explicit]
Definition at line 280 of file baseline-compiler.cc.
    : local_isolate_(local_isolate),
      stats_(local_isolate->runtime_call_stats()),
      shared_function_info_(shared_function_info),
      bytecode_(bytecode),
      zone_(local_isolate->allocator(), ZONE_NAME),
      masm_(
          local_isolate->GetMainThreadIsolateUnsafe(), &zone_,
          BaselineAssemblerOptions(local_isolate->GetMainThreadIsolateUnsafe()),
          CodeObjectRequired::kNo, AllocateBuffer(bytecode)),
      basm_(&masm_),
      iterator_(bytecode_),
      labels_(zone_.AllocateArray<Label>(bytecode_->length())),
      label_tags_(2 * bytecode_->length(), &zone_) {
  // Empirically determined expected size of the offset table at the 95th %ile,
  // based on the size of the bytecode, to be:
  //
  // 16 + (bytecode size) / 4
  bytecode_offset_table_builder_.Reserve(
      base::bits::RoundUpToPowerOfTwo(16 + bytecode_->Size() / 4));
}
References bytecode_, bytecode_offset_table_builder_, v8::internal::kNo, v8::internal::baseline::BytecodeOffsetTableBuilder::Reserve(), and v8::base::bits::RoundUpToPowerOfTwo().
Member Function Documentation
AddPosition()
void v8::internal::baseline::BaselineCompiler::AddPosition () [private]
Definition at line 468 of file baseline-compiler.cc.
                                   {
  bytecode_offset_table_builder_.AddPosition(__ pc_offset());
}
References __, v8::internal::baseline::BytecodeOffsetTableBuilder::AddPosition(), and bytecode_offset_table_builder_.
Referenced by GenerateCode().
Build()
MaybeHandle< Code > v8::internal::baseline::BaselineCompiler::Build ()
Definition at line 339 of file baseline-compiler.cc.
                                          {
  RCS_BASELINE_SCOPE(Build);
  CodeDesc desc;
  __ GetCode(local_isolate_, &desc);
  // Allocate the bytecode offset table.
  Handle<TrustedByteArray> bytecode_offset_table =
      bytecode_offset_table_builder_.ToBytecodeOffsetTable(local_isolate_);
  Factory::CodeBuilder code_builder(local_isolate_, desc, CodeKind::BASELINE);
  code_builder.set_bytecode_offset_table(bytecode_offset_table);
  if (shared_function_info_->HasInterpreterData(local_isolate_)) {
    code_builder.set_interpreter_data(
        handle(shared_function_info_->interpreter_data(local_isolate_),
               local_isolate_));
  } else {
    code_builder.set_interpreter_data(bytecode_);
  }
  code_builder.set_parameter_count(bytecode_->parameter_count());
  return code_builder.TryBuild();
}
References __, bytecode_, bytecode_offset_table_builder_, v8::internal::handle(), local_isolate_, RCS_BASELINE_SCOPE, v8::internal::Factory::CodeBuilder::set_bytecode_offset_table(), v8::internal::Factory::CodeBuilder::set_interpreter_data(), v8::internal::Factory::CodeBuilder::set_parameter_count(), shared_function_info_, v8::internal::baseline::BytecodeOffsetTableBuilder::ToBytecodeOffsetTable(), and v8::internal::Factory::CodeBuilder::TryBuild().
Referenced by v8::internal::baseline::BaselineCompilerTask::Compile().
BuildCall()
template<ConvertReceiverMode kMode, typename... Args>
void v8::internal::baseline::BaselineCompiler::BuildCall (uint32_t slot, uint32_t arg_count, Args... args) [private]
Definition at line 1313 of file baseline-compiler.cc.
                                               {
  uint32_t bitfield;
  if (CallTrampoline_Baseline_CompactDescriptor::EncodeBitField(arg_count, slot,
                                                                &bitfield)) {
    CallBuiltin<ConvertReceiverModeToCompactBuiltin(kMode)>(
        RegisterOperand(0), // kFunction
        bitfield, // kActualArgumentsCount | kSlot
        args...); // Arguments
  } else {
    CallBuiltin<ConvertReceiverModeToBuiltin(kMode)>(
        RegisterOperand(0), // kFunction
        arg_count, // kActualArgumentsCount
        slot, // kSlot
        args...); // Arguments
  }
}
References v8::base::args, v8::internal::CallTrampoline_Baseline_CompactDescriptor::EncodeBitField(), and RegisterOperand().
BuildForwardJumpLabel()
Label * v8::internal::baseline::BaselineCompiler::BuildForwardJumpLabel () [private]
Definition at line 617 of file baseline-compiler.cc.
                                               {
  int target_offset = iterator().GetJumpTargetOffset();
  return EnsureLabel(target_offset);
}
References EnsureLabel(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset(), and iterator().
Referenced by JumpIfNotRoot(), and JumpIfRoot().
CallBuiltin()
template<Builtin kBuiltin, typename... Args>
void v8::internal::baseline::BaselineCompiler::CallBuiltin (Args... args) [private]
Definition at line 645 of file baseline-compiler.cc.
                                               {
#ifdef DEBUG
  effect_state_.CheckEffect();
  if (BuiltinMayDeopt(kBuiltin)) {
    effect_state_.MayDeopt();
  }
#endif
  ASM_CODE_COMMENT(&masm_);
  detail::MoveArgumentsForBuiltin<kBuiltin>(&basm_, args...);
  __ CallBuiltin(kBuiltin);
#ifdef V8_ENABLE_CET_SHADOW_STACK
  if (BuiltinMayDeopt(kBuiltin)) {
    __ MaybeEmitPlaceHolderForDeopt();
  }
#endif // V8_ENABLE_CET_SHADOW_STACK
}
References __, v8::base::args, ASM_CODE_COMMENT, basm_, and masm_.
CallRuntime()
template<typename... Args>
void v8::internal::baseline::BaselineCompiler::CallRuntime (Runtime::FunctionId function, Args... args) [private]
Definition at line 672 of file baseline-compiler.cc.
                                                                           {
#ifdef DEBUG
  effect_state_.CheckEffect();
  effect_state_.MayDeopt();
#endif
  __ LoadContext(kContextRegister);
  int nargs = __ Push(args...);
  __ CallRuntime(function, nargs);
#ifdef V8_ENABLE_CET_SHADOW_STACK
  __ MaybeEmitPlaceHolderForDeopt();
#endif // V8_ENABLE_CET_SHADOW_STACK
}
References __, v8::base::args, and v8::internal::kContextRegister.
Referenced by UpdateInterruptBudgetAndJumpToLabel().
Constant()
template<typename Type >
Handle< Type > v8::internal::baseline::BaselineCompiler::Constant (int operand_index) [private]
Definition at line 391 of file baseline-compiler.cc.
                                                         {
  return Cast<Type>(
      iterator().GetConstantForIndexOperand(operand_index, local_isolate_));
}
References iterator(), and local_isolate_.
ConstantSmi()
Tagged< Smi > v8::internal::baseline::BaselineCompiler::ConstantSmi (int operand_index) [private]
Definition at line 395 of file baseline-compiler.cc.
                                                           {
  return iterator().GetConstantAtIndexAsSmi(operand_index);
}
References v8::internal::interpreter::BytecodeArrayIterator::GetConstantAtIndexAsSmi(), and iterator().
EnsureLabel()
Label* v8::internal::baseline::BaselineCompiler::EnsureLabel (int offset, MarkAsIndirectJumpTarget mark = MarkAsIndirectJumpTarget::kNo) [inline], [private]
Definition at line 176 of file baseline-compiler.h.
                                                                  {
    Label* label = &labels_[offset];
    if (!label_tags_.Contains(offset * 2)) {
      label_tags_.Add(offset * 2);
      new (label) Label();
    }
    if (mark == MarkAsIndirectJumpTarget::kYes) {
      MarkIndirectJumpTarget(offset);
    }
    return label;
  }
References v8::internal::BitVector::Add(), v8::internal::BitVector::Contains(), kYes, label_tags_, labels_, and MarkIndirectJumpTarget().
Referenced by BuildForwardJumpLabel(), and PreVisitSingleBytecode().
EstimateInstructionSize()
int v8::internal::baseline::BaselineCompiler::EstimateInstructionSize (Tagged< BytecodeArray > bytecode) [static]
Definition at line 361 of file baseline-compiler.cc.
                                                                            {
  return bytecode->length() * kAverageBytecodeToInstructionRatio;
}
References v8::internal::baseline::anonymous_namespace{baseline-compiler.cc}::kAverageBytecodeToInstructionRatio.
Referenced by v8::internal::baseline::anonymous_namespace{baseline-compiler.cc}::AllocateBuffer(), and v8::internal::baseline::BaselineBatchCompiler::ShouldCompileBatch().
FeedbackVector()
MemOperand v8::internal::baseline::BaselineCompiler::FeedbackVector () [private]
Definition at line 442 of file baseline-compiler.cc.
                                            {
  return __ FeedbackVectorOperand();
}
References __.
Flag16()
uint32_t v8::internal::baseline::BaselineCompiler::Flag16 (int operand_index) [private]
Definition at line 414 of file baseline-compiler.cc.
                                                   {
  return iterator().GetFlag16Operand(operand_index);
}
References v8::internal::interpreter::BytecodeArrayIterator::GetFlag16Operand(), and iterator().
Referenced by Flag16AsSmi().
Flag16AsSmi()
Tagged< Smi > v8::internal::baseline::BaselineCompiler::Flag16AsSmi (int operand_index) [private]
Definition at line 438 of file baseline-compiler.cc.
                                                           {
  return Smi::FromInt(Flag16(operand_index));
}
References Flag16(), and v8::internal::Smi::FromInt().
Flag8()
uint32_t v8::internal::baseline::BaselineCompiler::Flag8 (int operand_index) [private]
Definition at line 411 of file baseline-compiler.cc.
                                                  {
  return iterator().GetFlag8Operand(operand_index);
}
References v8::internal::interpreter::BytecodeArrayIterator::GetFlag8Operand(), and iterator().
Referenced by Flag8AsSmi().
Flag8AsSmi()
Tagged< Smi > v8::internal::baseline::BaselineCompiler::Flag8AsSmi (int operand_index) [private]
Definition at line 435 of file baseline-compiler.cc.
                                                          {
  return Smi::FromInt(Flag8(operand_index));
}
References Flag8(), and v8::internal::Smi::FromInt().
GenerateCode()
void v8::internal::baseline::BaselineCompiler::GenerateCode ()
Definition at line 305 of file baseline-compiler.cc.
                                    {
  {
    RCS_BASELINE_SCOPE(PreVisit);
    // Mark exception handlers as valid indirect jump targets. This is required
    // when CFI is enabled, to allow indirect jumps into baseline code.
    HandlerTable table(*bytecode_);
    for (int i = 0; i < table.NumberOfRangeEntries(); ++i) {
      MarkIndirectJumpTarget(table.GetRangeHandler(i));
    }
    for (; !iterator_.done(); iterator_.Advance()) {
      PreVisitSingleBytecode();
    }
    iterator_.Reset();
  }
  // No code generated yet.
  DCHECK_EQ(__ pc_offset(), 0);
  __ CodeEntry();
#ifdef V8_ENABLE_SANDBOX_HARDWARE_SUPPORT
  __ AssertInSandboxedExecutionMode();
#endif // V8_ENABLE_SANDBOX_HARDWARE_SUPPORT
  {
    RCS_BASELINE_SCOPE(Visit);
    Prologue();
    AddPosition();
    for (; !iterator_.done(); iterator_.Advance()) {
      VisitSingleBytecode();
      AddPosition();
    }
  }
}
References __, AddPosition(), v8::internal::interpreter::BytecodeArrayIterator::Advance(), bytecode_, DCHECK_EQ, v8::internal::interpreter::BytecodeArrayIterator::done(), v8::internal::HandlerTable::GetRangeHandler(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, iterator_, MarkIndirectJumpTarget(), v8::internal::HandlerTable::NumberOfRangeEntries(), PreVisitSingleBytecode(), Prologue(), RCS_BASELINE_SCOPE, v8::internal::interpreter::BytecodeArrayIterator::Reset(), and VisitSingleBytecode().
Referenced by v8::internal::baseline::BaselineCompilerTask::Compile().
Index()
uint32_t v8::internal::baseline::BaselineCompiler::Index (int operand_index) [private]
Definition at line 408 of file baseline-compiler.cc.
                                                  {
  return iterator().GetIndexOperand(operand_index);
}
References v8::internal::interpreter::BytecodeArrayIterator::GetIndexOperand(), and iterator().
Referenced by IndexAsSmi(), and IndexAsTagged().
IndexAsSmi()
Tagged< Smi > v8::internal::baseline::BaselineCompiler::IndexAsSmi (int operand_index) [private]
Definition at line 426 of file baseline-compiler.cc.
                                                          {
  return Smi::FromInt(Index(operand_index));
}
References v8::internal::Smi::FromInt(), and Index().
IndexAsTagged()
Tagged< TaggedIndex > v8::internal::baseline::BaselineCompiler::IndexAsTagged (int operand_index) [private]
Definition at line 420 of file baseline-compiler.cc.
                                                                     {
  return TaggedIndex::FromIntptr(Index(operand_index));
}
References v8::internal::TaggedIndex::FromIntptr(), and Index().
Int()
int32_t v8::internal::baseline::BaselineCompiler::Int (int operand_index) [private]
Definition at line 405 of file baseline-compiler.cc.
                                               {
  return iterator().GetImmediateOperand(operand_index);
}
References v8::internal::interpreter::BytecodeArrayIterator::GetImmediateOperand(), and iterator().
Referenced by IntAsSmi().
IntAsSmi()
Tagged< Smi > v8::internal::baseline::BaselineCompiler::IntAsSmi (int operand_index) [private]
Definition at line 429 of file baseline-compiler.cc.
                                                        {
  return Smi::FromInt(Int(operand_index));
}
References v8::internal::Smi::FromInt(), and Int().
IsIndirectJumpTarget()
bool v8::internal::baseline::BaselineCompiler::IsIndirectJumpTarget (int offset) const [inline], [private]
Definition at line 191 of file baseline-compiler.h.
                                              {
    return label_tags_.Contains(offset * 2 + 1);
  }
References v8::internal::BitVector::Contains(), and label_tags_.
Referenced by VisitSingleBytecode().
IsJumpTarget()
bool v8::internal::baseline::BaselineCompiler::IsJumpTarget (int offset) const [inline], [private]
Definition at line 188 of file baseline-compiler.h.
                                      {
    return label_tags_.Contains(offset * 2);
  }
References v8::internal::BitVector::Contains(), and label_tags_.
Referenced by VisitSingleBytecode().
iterator()
const interpreter::BytecodeArrayIterator& v8::internal::baseline::BaselineCompiler::iterator () [inline], [private]
Definition at line 159 of file baseline-compiler.h.
{ return iterator_; }
References iterator_.
Referenced by BuildForwardJumpLabel(), Constant(), ConstantSmi(), Flag16(), Flag8(), Index(), Int(), PreVisitSingleBytecode(), RegisterCount(), RegisterOperand(), StoreRegisterPair(), Uint(), and VisitSingleBytecode().
JumpIfNotRoot()
void v8::internal::baseline::BaselineCompiler::JumpIfNotRoot (RootIndex root) [private]
Definition at line 609 of file baseline-compiler.cc.
                                                   {
  Label dont_jump;
  __ JumpIfRoot(kInterpreterAccumulatorRegister, root, &dont_jump,
                Label::kNear);
  __ Jump(BuildForwardJumpLabel());
  __ Bind(&dont_jump);
}
References __, BuildForwardJumpLabel(), JumpIfRoot(), v8::internal::kInterpreterAccumulatorRegister, and v8::internal::Label::kNear.
Referenced by JumpIfRoot().
JumpIfRoot()
void v8::internal::baseline::BaselineCompiler::JumpIfRoot (RootIndex root) [private]
Definition at line 601 of file baseline-compiler.cc.
                                                {
  Label dont_jump;
  __ JumpIfNotRoot(kInterpreterAccumulatorRegister, root, &dont_jump,
                   Label::kNear);
  __ Jump(BuildForwardJumpLabel());
  __ Bind(&dont_jump);
}
References __, BuildForwardJumpLabel(), JumpIfNotRoot(), v8::internal::kInterpreterAccumulatorRegister, and v8::internal::Label::kNear.
Referenced by JumpIfNotRoot().
JumpIfToBoolean()
void v8::internal::baseline::BaselineCompiler::JumpIfToBoolean (bool do_jump_if_true, Label * label, Label::Distance distance = Label::kFar) [private]
Definition at line 686 of file baseline-compiler.cc.
                                                               {
  CallBuiltin<Builtin::kToBooleanForBaselineJump>(
      kInterpreterAccumulatorRegister);
  // ToBooleanForBaselineJump returns the ToBoolean value into return reg 1, and
  // the original value into kInterpreterAccumulatorRegister, so we don't have
  // to worry about it getting clobbered.
  static_assert(kReturnRegister0 == kInterpreterAccumulatorRegister);
  __ JumpIfSmi(do_jump_if_true ? kNotEqual : kEqual, kReturnRegister1,
               Smi::FromInt(0), label, distance);
}
References __, v8::internal::Smi::FromInt(), v8::internal::kEqual, v8::internal::kInterpreterAccumulatorRegister, v8::internal::kNotEqual, v8::internal::kReturnRegister0, and v8::internal::kReturnRegister1.
LoadClosureFeedbackArray()
void v8::internal::baseline::BaselineCompiler::LoadClosureFeedbackArray (Register output) [private]
Definition at line 451 of file baseline-compiler.cc.
                                                               {
  LoadFeedbackVector(output);
  __ LoadTaggedField(output, output,
                     FeedbackVector::kClosureFeedbackCellArrayOffset);
}
References __, and LoadFeedbackVector().
LoadConstant()
template<typename Type >
void v8::internal::baseline::BaselineCompiler::LoadConstant (Register output, int operand_index) [private]
Definition at line 399 of file baseline-compiler.cc.
                                                                      {
  __ Move(output, Constant<Type>(operand_index));
}
References __.
LoadFeedbackVector()
void v8::internal::baseline::BaselineCompiler::LoadFeedbackVector (Register output) [private]
Definition at line 446 of file baseline-compiler.cc.
                                                         {
  ASM_CODE_COMMENT(&masm_);
  __ Move(output, __ FeedbackVectorOperand());
}
References __, ASM_CODE_COMMENT, and masm_.
Referenced by LoadClosureFeedbackArray().
LoadRegister()
void v8::internal::baseline::BaselineCompiler::LoadRegister (Register output, int operand_index) [private]
Definition at line 369 of file baseline-compiler.cc.
                                                                      {
  __ LoadRegister(output, RegisterOperand(operand_index));
}
References __, and RegisterOperand().
MarkIndirectJumpTarget()
void v8::internal::baseline::BaselineCompiler::MarkIndirectJumpTarget (int offset) [inline], [private]
Definition at line 194 of file baseline-compiler.h.
{ label_tags_.Add(offset * 2 + 1); }
References v8::internal::BitVector::Add(), and label_tags_.
Referenced by EnsureLabel(), and GenerateCode().
NewLabel()
Label* v8::internal::baseline::BaselineCompiler::NewLabel () [private]
PreVisitSingleBytecode()
void v8::internal::baseline::BaselineCompiler::PreVisitSingleBytecode () [private]
Definition at line 472 of file baseline-compiler.cc.
                                              {
  switch (iterator().current_bytecode()) {
    case interpreter::Bytecode::kJumpLoop:
      EnsureLabel(iterator().GetJumpTargetOffset(),
                  MarkAsIndirectJumpTarget::kYes);
      break;
    default:
      break;
  }
}
References EnsureLabel(), iterator(), and kYes.
Referenced by GenerateCode().
Prologue()
void v8::internal::baseline::BaselineCompiler::Prologue () [private]
Definition at line 22 of file baseline-compiler-arm-inl.h.
                                {
  // Enter the frame here, since CallBuiltin will override lr.
  __ masm()->EnterFrame(StackFrame::BASELINE);
  DCHECK_EQ(kJSFunctionRegister, kJavaScriptCallTargetRegister);
  int max_frame_size = bytecode_->max_frame_size();
  CallBuiltin<Builtin::kBaselineOutOfLinePrologue>(
      kContextRegister, kJSFunctionRegister, kJavaScriptCallArgCountRegister,
      max_frame_size, kJavaScriptCallNewTargetRegister, bytecode_);
  PrologueFillFrame();
}
References __, bytecode_, DCHECK_EQ, v8::internal::kContextRegister, v8::internal::kJavaScriptCallArgCountRegister, v8::internal::kJavaScriptCallNewTargetRegister, v8::internal::kJavaScriptCallTargetRegister, v8::internal::kJSFunctionRegister, and PrologueFillFrame().
Referenced by GenerateCode().
PrologueFillFrame()
void v8::internal::baseline::BaselineCompiler::PrologueFillFrame () [private]
Definition at line 34 of file baseline-compiler-arm-inl.h.
                                         {
  ASM_CODE_COMMENT(&masm_);
  // Inlined register frame fill
  interpreter::Register new_target_or_generator_register =
      bytecode_->incoming_new_target_or_generator_register();
  if (v8_flags.debug_code) {
    __ masm()->CompareRoot(kInterpreterAccumulatorRegister,
                           RootIndex::kUndefinedValue);
    __ masm()->Assert(eq, AbortReason::kUnexpectedValue);
  }
  int register_count = bytecode_->register_count();
  // Magic value
  const int kLoopUnrollSize = 8;
  const int new_target_index = new_target_or_generator_register.index();
  const bool has_new_target = new_target_index != kMaxInt;
  if (has_new_target) {
    DCHECK_LE(new_target_index, register_count);
    for (int i = 0; i < new_target_index; i++) {
      __ Push(kInterpreterAccumulatorRegister);
    }
    // Push new_target_or_generator.
    __ Push(kJavaScriptCallNewTargetRegister);
    register_count -= new_target_index + 1;
  }
  if (register_count < 2 * kLoopUnrollSize) {
    // If the frame is small enough, just unroll the frame fill completely.
    for (int i = 0; i < register_count; ++i) {
      __ Push(kInterpreterAccumulatorRegister);
    }
  } else {
    // Extract the first few registers to round to the unroll size.
    int first_registers = register_count % kLoopUnrollSize;
    for (int i = 0; i < first_registers; ++i) {
      __ Push(kInterpreterAccumulatorRegister);
    }
    BaselineAssembler::ScratchRegisterScope temps(&basm_);
    Register scratch = temps.AcquireScratch();
    __ Move(scratch, register_count / kLoopUnrollSize);
    // We enter the loop unconditionally, so make sure we need to loop at least
    // once.
    DCHECK_GT(register_count / kLoopUnrollSize, 0);
    Label loop;
    __ Bind(&loop);
    for (int i = 0; i < kLoopUnrollSize; ++i) {
      __ Push(kInterpreterAccumulatorRegister);
    }
    __ masm()->sub(scratch, scratch, Operand(1), SetCC);
    __ masm()->b(gt, &loop);
  }
}
References __, v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), ASM_CODE_COMMENT, basm_, bytecode_, DCHECK_GT, DCHECK_LE, v8::internal::eq, v8::internal::gt, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::interpreter::Register::index(), v8::internal::kInterpreterAccumulatorRegister, v8::internal::kJavaScriptCallNewTargetRegister, v8::internal::kMaxInt, masm_, v8::internal::SetCC, and v8::internal::v8_flags.
Referenced by Prologue().
PrologueHandleOptimizationState()
void v8::internal::baseline::BaselineCompiler::PrologueHandleOptimizationState (Register feedback_vector) [private]
RegisterCount()
uint32_t v8::internal::baseline::BaselineCompiler::RegisterCount (int operand_index) [private]
Definition at line 417 of file baseline-compiler.cc.
                                                          {
  return iterator().GetRegisterCountOperand(operand_index);
}
References v8::internal::interpreter::BytecodeArrayIterator::GetRegisterCountOperand(), and iterator().
RegisterOperand()
interpreter::Register v8::internal::baseline::BaselineCompiler::RegisterOperand (int operand_index) [private]
Definition at line 365 of file baseline-compiler.cc.
                                                                       {
  return iterator().GetRegisterOperand(operand_index);
}
References v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperand(), and iterator().
Referenced by BuildCall(), LoadRegister(), and StoreRegister().
SelectBooleanConstant()
void v8::internal::baseline::BaselineCompiler::SelectBooleanConstant (Register output, std::function< void(Label *, Label::Distance)> jump_func) [private]
Definition at line 457 of file baseline-compiler.cc.
                                                                         {
  Label done, set_true;
  jump_func(&set_true, Label::kNear);
  __ LoadRoot(output, RootIndex::kFalseValue);
  __ Jump(&done, Label::kNear);
  __ Bind(&set_true);
  __ LoadRoot(output, RootIndex::kTrueValue);
  __ Bind(&done);
}
References __, and v8::internal::Label::kNear.
StoreRegister()
void v8::internal::baseline::BaselineCompiler::StoreRegister (int operand_index, Register value) [private]
Definition at line 373 of file baseline-compiler.cc.
                                                                      {
#ifdef DEBUG
  effect_state_.CheckEffect();
#endif
  __ Move(RegisterOperand(operand_index), value);
}
References __, RegisterOperand(), and v8::internal::value.
Referenced by StoreRegisterPair().
StoreRegisterPair()
void v8::internal::baseline::BaselineCompiler::StoreRegisterPair (int operand_index, Register val0, Register val1) [private]
Definition at line 380 of file baseline-compiler.cc.
                                                        {
#ifdef DEBUG
  effect_state_.CheckEffect();
#endif
  interpreter::Register reg0, reg1;
  std::tie(reg0, reg1) = iterator().GetRegisterPairOperand(operand_index);
  __ StoreRegister(reg0, val0);
  __ StoreRegister(reg1, val1);
}
References __, v8::internal::interpreter::BytecodeArrayIterator::GetRegisterPairOperand(), iterator(), and StoreRegister().
TailCallBuiltin()
template<Builtin kBuiltin, typename... Args>
void v8::internal::baseline::BaselineCompiler::TailCallBuiltin (Args... args) [private]
Definition at line 663 of file baseline-compiler.cc.
                                                   {
#ifdef DEBUG
  effect_state_.CheckEffect();
#endif
  detail::MoveArgumentsForBuiltin<kBuiltin>(&basm_, args...);
  __ TailCallBuiltin(kBuiltin);
}
References __, v8::base::args, and basm_.
Uint()
uint32_t v8::internal::baseline::BaselineCompiler::Uint (int operand_index) [private]
Definition at line 402 of file baseline-compiler.cc.
                                                 {
  return iterator().GetUnsignedImmediateOperand(operand_index);
}
References v8::internal::interpreter::BytecodeArrayIterator::GetUnsignedImmediateOperand(), and iterator().
Referenced by UintAsSmi(), and UintAsTagged().
UintAsSmi()
Tagged< Smi > v8::internal::baseline::BaselineCompiler::UintAsSmi (int operand_index) [private]
Definition at line 432 of file baseline-compiler.cc.
                                                         {
  return Smi::FromInt(Uint(operand_index));
}
References v8::internal::Smi::FromInt(), and Uint().
UintAsTagged()
Tagged< TaggedIndex > v8::internal::baseline::BaselineCompiler::UintAsTagged (int operand_index) [private]
Definition at line 423 of file baseline-compiler.cc.
                                                                    {
  return TaggedIndex::FromIntptr(Uint(operand_index));
}
References v8::internal::TaggedIndex::FromIntptr(), and Uint().
UpdateInterruptBudgetAndJumpToLabel()
void v8::internal::baseline::BaselineCompiler::UpdateInterruptBudgetAndJumpToLabel (int weight, Label * label, Label * skip_interrupt_label, StackCheckBehavior stack_check_behavior) [private]
Definition at line 585 of file baseline-compiler.cc.
                                             {
  if (weight != 0) {
    ASM_CODE_COMMENT(&masm_);
    __ AddToInterruptBudgetAndJumpIfNotExceeded(weight, skip_interrupt_label);
    DCHECK_LT(weight, 0);
    CallRuntime(stack_check_behavior == kEnableStackCheck
                    ? Runtime::kBytecodeBudgetInterruptWithStackCheck_Sparkplug
                    : Runtime::kBytecodeBudgetInterrupt_Sparkplug,
                __ FunctionOperand());
  }
  if (label) __ Jump(label);
}
References __, ASM_CODE_COMMENT, CallRuntime(), DCHECK_LT, kEnableStackCheck, and masm_.
VerifyFrame()
void v8::internal::baseline::BaselineCompiler::VerifyFrame () [private]
Definition at line 538 of file baseline-compiler.cc.
                                   {
  if (v8_flags.slow_debug_code) {
    ASM_CODE_COMMENT(&masm_);
    __ RecordComment(" -- Verify frame size");
    VerifyFrameSize();
    __ RecordComment(" -- Verify feedback vector");
    {
      BaselineAssembler::ScratchRegisterScope temps(&basm_);
      Register scratch = temps.AcquireScratch();
      __ Move(scratch, __ FeedbackVectorOperand());
      Label is_smi, is_ok;
      __ JumpIfSmi(scratch, &is_smi);
      __ JumpIfObjectTypeFast(kEqual, scratch, FEEDBACK_VECTOR_TYPE, &is_ok);
      __ Bind(&is_smi);
      __ masm()->Abort(AbortReason::kExpectedFeedbackVector);
      __ Bind(&is_ok);
    }
    // TODO(leszeks): More verification.
  }
}
References __, v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), ASM_CODE_COMMENT, basm_, v8::internal::kEqual, masm_, v8::internal::v8_flags, and VerifyFrameSize().
Referenced by VisitSingleBytecode().
VerifyFrameSize()
void v8::internal::baseline::BaselineCompiler::VerifyFrameSize () [private]
Definition at line 87 of file baseline-compiler-arm-inl.h.
                                       {
  BaselineAssembler::ScratchRegisterScope temps(&basm_);
  Register scratch = temps.AcquireScratch();
  __ masm()->add(scratch, sp,
                 Operand(InterpreterFrameConstants::kFixedFrameSizeFromFp +
                         bytecode_->frame_size()));
  __ masm()->cmp(scratch, fp);
  __ masm()->Assert(eq, AbortReason::kUnexpectedStackPointer);
}
References __, v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), basm_, bytecode_, v8::internal::eq, and v8::internal::StandardFrameConstants::kFixedFrameSizeFromFp.
Referenced by VerifyFrame().
VisitSingleBytecode()
void v8::internal::baseline::BaselineCompiler::VisitSingleBytecode () [private]
Definition at line 483 of file baseline-compiler.cc.
                                           {
#ifdef DEBUG
  effect_state_.clear();
#endif
  int offset = iterator().current_offset();
  if (IsJumpTarget(offset)) __ Bind(&labels_[offset]);
  // This is required when CFI is enabled.
  if (IsIndirectJumpTarget(offset)) {
    __ JumpTarget();
  }
  ASM_CODE_COMMENT_STRING(&masm_, [&]() {
    std::ostringstream str;
    iterator().PrintTo(str);
    return str.str();
  });
  VerifyFrame();
#ifdef V8_TRACE_UNOPTIMIZED
  TraceBytecode(Runtime::kTraceUnoptimizedBytecodeEntry);
#endif
  {
    interpreter::Bytecode bytecode = iterator().current_bytecode();
#ifdef DEBUG
    std::optional<EnsureAccumulatorPreservedScope> accumulator_preserved_scope;
    // We should make sure to preserve the accumulator whenever the bytecode
    // isn't registered as writing to it. We can't do this for jumps or switches
    // though, since the control flow would not match the control flow of this
    // scope.
    if (v8_flags.slow_debug_code &&
        !interpreter::Bytecodes::WritesOrClobbersAccumulator(bytecode) &&
        !interpreter::Bytecodes::IsJump(bytecode) &&
        !interpreter::Bytecodes::IsSwitch(bytecode)) {
      accumulator_preserved_scope.emplace(&basm_);
    }
#endif // DEBUG
    switch (bytecode) {
#define BYTECODE_CASE(name, ...) \
  case interpreter::Bytecode::k##name: \
    Visit##name(); \
    break;
      BYTECODE_LIST(BYTECODE_CASE, BYTECODE_CASE)
#undef BYTECODE_CASE
    }
  }
#ifdef V8_TRACE_UNOPTIMIZED
  TraceBytecode(Runtime::kTraceUnoptimizedBytecodeExit);
#endif
}
References __, ASM_CODE_COMMENT_STRING, basm_, BYTECODE_CASE, BYTECODE_LIST, v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), IsIndirectJumpTarget(), v8::internal::interpreter::Bytecodes::IsJump(), IsJumpTarget(), v8::internal::interpreter::Bytecodes::IsSwitch(), iterator(), labels_, masm_, v8::internal::interpreter::BytecodeArrayIterator::PrintTo(), v8::internal::v8_flags, VerifyFrame(), and v8::internal::interpreter::Bytecodes::WritesOrClobbersAccumulator().
Referenced by GenerateCode().
Member Data Documentation
basm_
BaselineAssembler v8::internal::baseline::BaselineCompiler::basm_ [private]
Definition at line 168 of file baseline-compiler.h.
Referenced by CallBuiltin(), PrologueFillFrame(), TailCallBuiltin(), VerifyFrame(), VerifyFrameSize(), and VisitSingleBytecode().
bytecode_
Handle<BytecodeArray> v8::internal::baseline::BaselineCompiler::bytecode_ [private]
Definition at line 165 of file baseline-compiler.h.
Referenced by BaselineCompiler(), Build(), GenerateCode(), Prologue(), PrologueFillFrame(), and VerifyFrameSize().
bytecode_offset_table_builder_
BytecodeOffsetTableBuilder v8::internal::baseline::BaselineCompiler::bytecode_offset_table_builder_ [private]
Definition at line 170 of file baseline-compiler.h.
Referenced by AddPosition(), BaselineCompiler(), and Build().
interpreter_data_
Handle<HeapObject> v8::internal::baseline::BaselineCompiler::interpreter_data_ [private]
Definition at line 164 of file baseline-compiler.h.
iterator_
interpreter::BytecodeArrayIterator v8::internal::baseline::BaselineCompiler::iterator_ [private]
Definition at line 169 of file baseline-compiler.h.
Referenced by GenerateCode(), and iterator().
label_tags_
BitVector v8::internal::baseline::BaselineCompiler::label_tags_ [private]
Definition at line 197 of file baseline-compiler.h.
Referenced by EnsureLabel(), IsIndirectJumpTarget(), IsJumpTarget(), and MarkIndirectJumpTarget().
labels_
Label* v8::internal::baseline::BaselineCompiler::labels_ [private]
Definition at line 196 of file baseline-compiler.h.
Referenced by EnsureLabel(), and VisitSingleBytecode().
local_isolate_
LocalIsolate* v8::internal::baseline::BaselineCompiler::local_isolate_ [private]
Definition at line 161 of file baseline-compiler.h.
Referenced by Build(), and Constant().
masm_
MacroAssembler v8::internal::baseline::BaselineCompiler::masm_ [private]
Definition at line 167 of file baseline-compiler.h.
Referenced by CallBuiltin(), LoadFeedbackVector(), PrologueFillFrame(), UpdateInterruptBudgetAndJumpToLabel(), VerifyFrame(), and VisitSingleBytecode().
shared_function_info_
Handle<SharedFunctionInfo> v8::internal::baseline::BaselineCompiler::shared_function_info_ [private]
Definition at line 163 of file baseline-compiler.h.
Referenced by Build().
stats_
RuntimeCallStats* v8::internal::baseline::BaselineCompiler::stats_ [private]
Definition at line 162 of file baseline-compiler.h.
zone_
Zone v8::internal::baseline::BaselineCompiler::zone_ [private]
Definition at line 166 of file baseline-compiler.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/baseline/baseline-compiler.h
/mnt/V8SourceCode/src/baseline/arm/baseline-compiler-arm-inl.h
/mnt/V8SourceCode/src/baseline/arm64/baseline-compiler-arm64-inl.h
/mnt/V8SourceCode/src/baseline/baseline-compiler.cc
/mnt/V8SourceCode/src/baseline/ia32/baseline-compiler-ia32-inl.h
/mnt/V8SourceCode/src/baseline/loong64/baseline-compiler-loong64-inl.h
/mnt/V8SourceCode/src/baseline/mips64/baseline-compiler-mips64-inl.h
/mnt/V8SourceCode/src/baseline/ppc/baseline-compiler-ppc-inl.h
/mnt/V8SourceCode/src/baseline/riscv/baseline-compiler-riscv-inl.h
/mnt/V8SourceCode/src/baseline/s390/baseline-compiler-s390-inl.h
/mnt/V8SourceCode/src/baseline/x64/baseline-compiler-x64-inl.h