v8::internal::TypeConversionDescriptor Class Reference
#include <interface-descriptors.h>
Static Public Member Functions
static constexpr Register ArgumentRegister ()
static constexpr auto registers ()
Additional Inherited Members
Detailed Description
Definition at line 1645 of file interface-descriptors.h.
Member Function Documentation
ArgumentRegister()
constexpr Register v8::internal::TypeConversionDescriptor::ArgumentRegister () [inline], [static], [constexpr]
Definition at line 159 of file interface-descriptors-riscv-inl.h.
{ return a0; }
Referenced by registers(), and v8::internal::TypeConversionNoContextDescriptor::registers().
registers()
constexpr auto v8::internal::TypeConversionDescriptor::registers () [static], [constexpr]
Definition at line 612 of file interface-descriptors-inl.h.
                                                   {
  return RegisterArray(ArgumentRegister());
}
References ArgumentRegister(), and v8::internal::RegisterArray().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h
/mnt/V8SourceCode/src/codegen/riscv/interface-descriptors-riscv-inl.h