v8::internal::interpreter::IntrinsicsHelper Class Reference
#include <interpreter-intrinsics.h>
Public Types
enum class IntrinsicId { DECLARE_INTRINSIC_ID
, kIdCount
 }
Static Public Member Functions
static V8_EXPORT_PRIVATE bool IsSupported (Runtime::FunctionId function_id)
static IntrinsicId FromRuntimeId (Runtime::FunctionId function_id)
static Runtime::FunctionId ToRuntimeId (IntrinsicId intrinsic_id)
Private Member Functions
DISALLOW_IMPLICIT_CONSTRUCTORS (IntrinsicsHelper)
Detailed Description
Definition at line 35 of file interpreter-intrinsics.h.
Member Enumeration Documentation
IntrinsicId
enum v8::internal::interpreter::IntrinsicsHelper::IntrinsicId [strong]
Enumerator
DECLARE_INTRINSIC_ID
kIdCount
Definition at line 37 of file interpreter-intrinsics.h.
                         {
#define DECLARE_INTRINSIC_ID(name, lower_case, count) k##name,
    INTRINSICS_LIST(DECLARE_INTRINSIC_ID)
#undef DECLARE_INTRINSIC_ID
        kIdCount
  };
Member Function Documentation
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::interpreter::IntrinsicsHelper::DISALLOW_IMPLICIT_CONSTRUCTORS (IntrinsicsHelper) [private]
FromRuntimeId()
IntrinsicsHelper::IntrinsicId v8::internal::interpreter::IntrinsicsHelper::FromRuntimeId (Runtime::FunctionId function_id) [static]
Definition at line 26 of file interpreter-intrinsics.cc.
                                   {
  switch (function_id) {
#define TO_RUNTIME_ID(name, lower_case, count) \
  case Runtime::kInline##name: \
    return IntrinsicId::k##name;
    INTRINSICS_LIST(TO_RUNTIME_ID)
#undef TO_RUNTIME_ID
    default:
      UNREACHABLE();
  }
}
References INTRINSICS_LIST, TO_RUNTIME_ID, and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime().
IsSupported()
bool v8::internal::interpreter::IntrinsicsHelper::IsSupported (Runtime::FunctionId function_id) [static]
Definition at line 14 of file interpreter-intrinsics.cc.
                                                                {
  switch (function_id) {
#define SUPPORTED(name, lower_case, count) case Runtime::kInline##name:
    INTRINSICS_LIST(SUPPORTED)
    return true;
#undef SUPPORTED
    default:
      return false;
  }
}
References INTRINSICS_LIST, and SUPPORTED.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime().
ToRuntimeId()
Runtime::FunctionId v8::internal::interpreter::IntrinsicsHelper::ToRuntimeId (IntrinsicsHelper::IntrinsicId intrinsic_id) [static]
Definition at line 40 of file interpreter-intrinsics.cc.
                                              {
  switch (intrinsic_id) {
#define TO_INTRINSIC_ID(name, lower_case, count) \
  case IntrinsicId::k##name: \
    return Runtime::kInline##name;
    INTRINSICS_LIST(TO_INTRINSIC_ID)
#undef TO_INTRINSIC_ID
    default:
      UNREACHABLE();
  }
}
References INTRINSICS_LIST, TO_INTRINSIC_ID, and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::BytecodeDecoder::Decode(), and v8::internal::interpreter::BytecodeArrayIterator::GetIntrinsicIdOperand().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/interpreter-intrinsics.h
/mnt/V8SourceCode/src/interpreter/interpreter-intrinsics.cc