v8::internal::SetupIsolateDelegate Class Reference
#include <setup-isolate.h>
Public Member Functions
SetupIsolateDelegate ()=default
virtual ~SetupIsolateDelegate ()=default
virtual bool SetupHeap (Isolate *isolate, bool create_heap_objects)
virtual void SetupBuiltins (Isolate *isolate, bool compile_builtins)
Static Protected Member Functions
static void SetupBuiltinsInternal (Isolate *isolate, bool compute_builtins_effects)
static void AddBuiltin (Builtins *builtins, Builtin builtin, Tagged< Code > code)
static void PopulateWithPlaceholders (Isolate *isolate)
static void ReplacePlaceholders (Isolate *isolate)
static bool SetupHeapInternal (Isolate *isolate)
Detailed Description
Definition at line 34 of file setup-isolate.h.
Constructor & Destructor Documentation
SetupIsolateDelegate()
v8::internal::SetupIsolateDelegate::SetupIsolateDelegate () [default]
 SetupIsolateDelegate()
virtual v8::internal::SetupIsolateDelegate::~SetupIsolateDelegate () [virtual], [default]
Member Function Documentation
AddBuiltin()
void v8::internal::SetupIsolateDelegate::AddBuiltin (Builtins * builtins, Builtin builtin, Tagged< Code > code) [static], [protected]
Definition at line 341 of file setup-builtins-internal.cc.
                                                         {
  DCHECK_EQ(builtin, code->builtin_id());
  builtins->set_code(builtin, code);
}
References code, DCHECK_EQ, and v8::internal::Builtins::set_code().
Referenced by PopulateWithPlaceholders(), and SetupBuiltinsInternal().
PopulateWithPlaceholders()
void v8::internal::SetupIsolateDelegate::PopulateWithPlaceholders (Isolate * isolate) [static], [protected]
Definition at line 348 of file setup-builtins-internal.cc.
                                                                    {
  // Fill the builtins list with placeholders. References to these placeholder
  // builtins are eventually replaced by the actual builtins. This is to
  // support circular references between builtins.
  Builtins* builtins = isolate->builtins();
  HandleScope scope(isolate);
  for (Builtin builtin = Builtins::kFirst; builtin <= Builtins::kLast;
       ++builtin) {
    DirectHandle<Code> placeholder = BuildPlaceholder(isolate, builtin);
    AddBuiltin(builtins, builtin, *placeholder);
  }
}
References AddBuiltin(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildPlaceholder(), v8::internal::Isolate::builtins(), v8::internal::Builtins::kFirst, and v8::internal::Builtins::kLast.
Referenced by SetupBuiltinsInternal().
ReplacePlaceholders()
void v8::internal::SetupIsolateDelegate::ReplacePlaceholders (Isolate * isolate) [static], [protected]
Definition at line 362 of file setup-builtins-internal.cc.
                                                               {
  // Replace references from all builtin code objects to placeholders.
  Builtins* builtins = isolate->builtins();
  DisallowGarbageCollection no_gc;
  static const int kRelocMask =
      RelocInfo::ModeMask(RelocInfo::CODE_TARGET) |
      RelocInfo::ModeMask(RelocInfo::FULL_EMBEDDED_OBJECT) |
      RelocInfo::ModeMask(RelocInfo::COMPRESSED_EMBEDDED_OBJECT) |
      RelocInfo::ModeMask(RelocInfo::RELATIVE_CODE_TARGET);
  PtrComprCageBase cage_base(isolate);
  for (Builtin builtin = Builtins::kFirst; builtin <= Builtins::kLast;
       ++builtin) {
    Tagged<Code> code = builtins->code(builtin);
    Tagged<InstructionStream> istream = code->instruction_stream();
    WritableJitAllocation jit_allocation = ThreadIsolation::LookupJitAllocation(
        istream.address(), istream->Size(),
        ThreadIsolation::JitAllocationType::kInstructionStream, true);
    bool flush_icache = false;
    for (WritableRelocIterator it(jit_allocation, istream,
                                  code->constant_pool(), kRelocMask);
         !it.done(); it.next()) {
      WritableRelocInfo* rinfo = it.rinfo();
      if (RelocInfo::IsCodeTargetMode(rinfo->rmode())) {
        Tagged<Code> target_code =
            Code::FromTargetAddress(rinfo->target_address());
        DCHECK_IMPLIES(
            RelocInfo::IsRelativeCodeTarget(rinfo->rmode()),
            Builtins::IsIsolateIndependent(target_code->builtin_id()));
        if (!target_code->is_builtin()) continue;
        Tagged<Code> new_target = builtins->code(target_code->builtin_id());
        rinfo->set_target_address(istream, new_target->instruction_start(),
                                  UPDATE_WRITE_BARRIER, SKIP_ICACHE_FLUSH);
      } else {
        DCHECK(RelocInfo::IsEmbeddedObjectMode(rinfo->rmode()));
        Tagged<Object> object = rinfo->target_object(cage_base);
        if (!IsCode(object, cage_base)) continue;
        Tagged<Code> target = Cast<Code>(object);
        if (!target->is_builtin()) continue;
        Tagged<Code> new_target = builtins->code(target->builtin_id());
        rinfo->set_target_object(istream, new_target, UPDATE_WRITE_BARRIER,
                                 SKIP_ICACHE_FLUSH);
      }
      flush_icache = true;
    }
    if (flush_icache) {
      FlushInstructionCache(code->instruction_start(),
                            code->instruction_size());
    }
  }
}
References v8::internal::Tagged< HeapObject >::address(), v8::internal::Isolate::builtins(), v8::internal::Builtins::code(), code, v8::internal::RelocInfo::CODE_TARGET, v8::internal::RelocInfo::COMPRESSED_EMBEDDED_OBJECT, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::FlushInstructionCache(), v8::internal::Code::FromTargetAddress(), v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT, v8::internal::RelocInfo::IsCodeTargetMode(), v8::internal::RelocInfo::IsEmbeddedObjectMode(), v8::internal::Builtins::IsIsolateIndependent(), v8::internal::RelocInfo::IsRelativeCodeTarget(), v8::internal::Builtins::kFirst, v8::internal::ThreadIsolation::kInstructionStream, v8::internal::Builtins::kLast, v8::internal::ThreadIsolation::LookupJitAllocation(), v8::internal::RelocInfo::ModeMask(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::RelocInfo::RELATIVE_CODE_TARGET, v8::internal::RelocInfo::rmode(), v8::internal::WritableRelocInfo::set_target_address(), v8::internal::WritableRelocInfo::set_target_object(), v8::internal::SKIP_ICACHE_FLUSH, v8::internal::RelocInfo::target_address(), v8::internal::RelocInfo::target_object(), and v8::internal::UPDATE_WRITE_BARRIER.
Referenced by SetupBuiltinsInternal().
SetupBuiltins()
void v8::internal::SetupIsolateDelegate::SetupBuiltins (Isolate * isolate, bool compile_builtins) [virtual]
Definition at line 20 of file setup-isolate-deserialize.cc.
                                                                {
  // No actual work to be done; builtins will be deserialized from the snapshot.
  CHECK_WITH_MSG(!compile_builtins,
                 "Builtin compilation supported only in mksnapshot");
}
References CHECK_WITH_MSG.
Referenced by v8::internal::Isolate::Init().
SetupBuiltinsInternal()
void v8::internal::SetupIsolateDelegate::SetupBuiltinsInternal (Isolate * isolate, bool compute_builtins_effects) [static], [protected]
Definition at line 414 of file setup-builtins-internal.cc.
                                                     {
  Builtins* builtins = isolate->builtins();
  DCHECK(!builtins->initialized_);
  BuiltinsEffectsAnalyzer* builtins_effects_analyzer = nullptr;
  if (compute_builtins_effects) {
    builtins_effects_analyzer = BuiltinsEffectsAnalyzer::Setup(isolate);
  }
  if (v8_flags.dump_builtins_hashes_to_file) {
    // Create an empty file.
    std::ofstream(v8_flags.dump_builtins_hashes_to_file, std::ios_base::trunc);
  }
  PopulateWithPlaceholders(isolate);
  // Create a scope for the handles in the builtins.
  HandleScope scope(isolate);
  // Generated builtins are temporarily stored in this array to avoid data races
  // on the isolate's builtin table.
  std::array<Handle<Code>, Builtins::kBuiltinCount> generated_builtins;
  auto install_generated_builtin = [&generated_builtins, isolate](
                                       Builtin builtin, Handle<Code> code) {
    DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
    USE(isolate);
    generated_builtins[Builtins::ToInt(builtin)] = code;
  };
  int builtins_built_without_job_count = 0;
  int job_creation_order = 0;
  BuiltinCompilationScheduler scheduler;
  Tagged<Code> code;
#define BUILD_CPP_WITHOUT_JOB(Name, Argc) \
  code = BuildAdaptor(isolate, Builtin::k##Name, \
                      FUNCTION_ADDR(Builtin_##Name), #Name); \
  generated_builtins[Builtins::ToInt(Builtin::k##Name)] = \
      handle(code, isolate); \
  builtins_built_without_job_count++;
#define BUILD_TSJ_WITHOUT_JOB(Name, Argc, ...) \
  code = BuildWithTurboshaftAssemblerJS(\
      isolate, Builtin::k##Name, &Builtins::Generate_##Name, Argc, #Name); \
  AddBuiltin(builtins, Builtin::k##Name, code); \
  builtins_built_without_job_count++;
#define BUILD_TFJ_WITH_JOB(Name, Argc, ...) \
  CompileJSLinkageCodeStubBuiltin(isolate, Builtin::k##Name, \
                                  &Builtins::Generate_##Name, \
                                  install_generated_builtin, Argc, #Name, \
                                  job_creation_order++, scheduler);
#define BUILD_TSC_WITHOUT_JOB(Name, InterfaceDescriptor) \
  /* Return size is from the provided CallInterfaceDescriptor. */ \
  code = BuildWithTurboshaftAssemblerCS(\
      isolate, Builtin::k##Name, &Builtins::Generate_##Name, \
      CallDescriptors::InterfaceDescriptor, #Name); \
  generated_builtins[Builtins::ToInt(Builtin::k##Name)] = \
      handle(code, isolate); \
  builtins_built_without_job_count++;
#define BUILD_TFC_WITH_JOB(Name, InterfaceDescriptor) \
  /* Return size is from the provided CallInterfaceDescriptor. */ \
  CompileCSLinkageCodeStubBuiltin(\
      isolate, Builtin::k##Name, &Builtins::Generate_##Name, \
      install_generated_builtin, CallDescriptors::InterfaceDescriptor, #Name, \
      job_creation_order++, scheduler);
#define BUILD_TFS_WITH_JOB(Name, ...) \
  /* Return size for generic TF builtins (stub linkage) is always 1. */ \
  CompileCSLinkageCodeStubBuiltin(\
      isolate, Builtin::k##Name, &Builtins::Generate_##Name, \
      install_generated_builtin, CallDescriptors::Name, #Name, \
      job_creation_order++, scheduler);
#define BUILD_TFH_WITH_JOB(Name, InterfaceDescriptor) \
  /* Return size for IC builtins/handlers is always 1. */ \
  CompileCSLinkageCodeStubBuiltin(\
      isolate, Builtin::k##Name, &Builtins::Generate_##Name, \
      install_generated_builtin, CallDescriptors::InterfaceDescriptor, #Name, \
      job_creation_order++, scheduler);
#define BUILD_BCH_WITH_JOB(Name, OperandScale, Bytecode) \
  CompileBytecodeHandler(isolate, Builtin::k##Name, OperandScale, Bytecode, \
                         install_generated_builtin, job_creation_order++, \
                         scheduler);
#define BUILD_ASM_WITHOUT_JOB(Name, InterfaceDescriptor) \
  code = BuildWithMacroAssembler(isolate, Builtin::k##Name, \
                                 Builtins::Generate_##Name, #Name); \
  generated_builtins[Builtins::ToInt(Builtin::k##Name)] = \
      handle(code, isolate); \
  builtins_built_without_job_count++;
#define NOP(...)
  // Build all builtins without jobs first. When concurrent builtin generation
  // is enabled, allocations needs to be deterministic. Having main-thread
  // generated builtins in the middle of the list breaks determinism.
  BUILTIN_LIST(BUILD_CPP_WITHOUT_JOB, BUILD_TSJ_WITHOUT_JOB, NOP,
               BUILD_TSC_WITHOUT_JOB, NOP, NOP, NOP, NOP,
               BUILD_ASM_WITHOUT_JOB);
  BUILTIN_LIST(NOP, NOP, BUILD_TFJ_WITH_JOB, NOP, BUILD_TFC_WITH_JOB,
               BUILD_TFS_WITH_JOB, BUILD_TFH_WITH_JOB, BUILD_BCH_WITH_JOB, NOP)
#undef BUILD_CPP_WITHOUT_JOB
#undef BUILD_TSJ_WITHOUT_JOB
#undef BUILD_TFJ_WITH_JOB
#undef BUILD_TSC_WITHOUT_JOB
#undef BUILD_TFC_WITH_JOB
#undef BUILD_TFS_WITH_JOB
#undef BUILD_TFH_WITH_JOB
#undef BUILD_BCH_WITH_JOB
#undef BUILD_ASM_WITHOUT_JOB
#undef NOP
  scheduler.AwaitAndFinalizeCurrentBatch(isolate);
  CHECK_EQ(Builtins::kBuiltinCount, builtins_built_without_job_count +
                                        scheduler.builtins_installed_count());
  if (compute_builtins_effects) {
    DCHECK_NOT_NULL(builtins_effects_analyzer);
    builtins_effects_analyzer->Finalize();
  }
  // Add the generated builtins to the isolate.
  for (Builtin builtin = Builtins::kFirst; builtin <= Builtins::kLast;
       ++builtin) {
    AddBuiltin(builtins, builtin,
               *generated_builtins[Builtins::ToInt(builtin)]);
  }
  ReplacePlaceholders(isolate);
  builtins->MarkInitialized();
}
References AddBuiltin(), BUILD_ASM_WITHOUT_JOB, BUILD_BCH_WITH_JOB, BUILD_CPP_WITHOUT_JOB, BUILD_TFC_WITH_JOB, BUILD_TFH_WITH_JOB, BUILD_TFJ_WITH_JOB, BUILD_TFS_WITH_JOB, BUILD_TSC_WITHOUT_JOB, BUILD_TSJ_WITHOUT_JOB, BUILTIN_LIST, v8::internal::Isolate::builtins(), CHECK_EQ, code, v8::internal::ThreadId::Current(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::BuiltinsEffectsAnalyzer::Finalize(), v8::internal::Builtins::initialized_, v8::internal::Builtins::kBuiltinCount, v8::internal::Builtins::kFirst, v8::internal::Builtins::kLast, v8::internal::Builtins::MarkInitialized(), v8::internal::NOP, PopulateWithPlaceholders(), ReplacePlaceholders(), v8::internal::BuiltinsEffectsAnalyzer::Setup(), v8::internal::Isolate::thread_id(), v8::internal::Builtins::ToInt(), USE, and v8::internal::v8_flags.
SetupHeap()
bool v8::internal::SetupIsolateDelegate::SetupHeap (Isolate * isolate, bool create_heap_objects) [virtual]
Definition at line 12 of file setup-isolate-deserialize.cc.
                                                               {
  // No actual work to be done; heap will be deserialized from the snapshot.
  CHECK_WITH_MSG(!create_heap_objects,
                 "Heap setup supported only in mksnapshot");
  return true;
}
References CHECK_WITH_MSG.
Referenced by v8::internal::Isolate::Init().
SetupHeapInternal()
bool v8::internal::SetupIsolateDelegate::SetupHeapInternal (Isolate * isolate) [static], [protected]
Definition at line 179 of file setup-heap-internal.cc.
                                                             {
  auto heap = isolate->heap();
  if (!isolate->read_only_heap()->roots_init_complete()) {
    if (!heap->CreateReadOnlyHeapObjects()) return false;
    isolate->VerifyStaticRoots();
    isolate->read_only_heap()->OnCreateRootsComplete(isolate);
  }
  // We prefer to fit all of read-only space in one page.
  CHECK_EQ(heap->read_only_space()->pages().size(), 1);
  auto ro_size = heap->read_only_space()->Size();
  DCHECK_EQ(heap->old_space()->Size(), 0);
  DCHECK_IMPLIES(heap->new_space(), heap->new_space()->Size() == 0);
  auto res = heap->CreateMutableHeapObjects();
  DCHECK_EQ(heap->read_only_space()->Size(), ro_size);
  USE(ro_size);
  return res;
}
References CHECK_EQ, DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Isolate::heap(), v8::internal::ReadOnlyHeap::OnCreateRootsComplete(), v8::internal::Isolate::read_only_heap(), v8::internal::ReadOnlyHeap::roots_init_complete(), USE, and v8::internal::Isolate::VerifyStaticRoots().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/init/setup-isolate.h
/mnt/V8SourceCode/src/builtins/setup-builtins-internal.cc
/mnt/V8SourceCode/src/heap/setup-heap-internal.cc
/mnt/V8SourceCode/src/init/setup-isolate-deserialize.cc
/mnt/V8SourceCode/src/init/setup-isolate-full.cc