v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem Class Reference
Public Types
enum class SlotsType { kRegularSlots
, kTypedSlots
 }
Public Member Functions
MarkingItem (MutablePageMetadata *chunk, SlotsType slots_type, SlotSet *slot_set, SlotSet *background_slot_set)
MarkingItem (MutablePageMetadata *chunk, SlotsType slots_type, TypedSlotSet *typed_slot_set)
~MarkingItem ()=default
template<typename Visitor >
void Process (Visitor *visitor)
void MergeAndDeleteRememberedSets ()
void DeleteRememberedSets ()
void DeleteSetsOnTearDown ()
Private Member Functions
Heap * heap ()
template<typename Visitor >
void MarkUntypedPointers (Visitor *visitor)
template<typename Visitor >
void MarkTypedPointers (Visitor *visitor)
template<typename Visitor , typename TSlot >
SlotCallbackResult CheckAndMarkObject (Visitor *visitor, TSlot slot)
Private Attributes
MutablePageMetadata *const chunk_
const SlotsType slots_type_
xx xx xx xx xx xx xx xx xx
union {
 SlotSet * slot_set_
 TypedSlotSet * typed_slot_set_
};
SlotSet * background_slot_set_ = nullptr
Detailed Description
Definition at line 66 of file minor-mark-sweep.h.
Member Enumeration Documentation
SlotsType
enum v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::SlotsType [strong]
Enumerator
kRegularSlots
kTypedSlots
Definition at line 68 of file minor-mark-sweep.h.
{ kRegularSlots, kTypedSlots };
Constructor & Destructor Documentation
MarkingItem() [1/2]
v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::MarkingItem (MutablePageMetadata * chunk, SlotsType slots_type, SlotSet * slot_set, SlotSet * background_slot_set) [inline]
Definition at line 70 of file minor-mark-sweep.h.
        : chunk_(chunk),
          slots_type_(slots_type),
          slot_set_(slot_set),
          background_slot_set_(background_slot_set) {}
MarkingItem() [2/2]
v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::MarkingItem (MutablePageMetadata * chunk, SlotsType slots_type, TypedSlotSet * typed_slot_set) [inline]
Definition at line 76 of file minor-mark-sweep.h.
        : chunk_(chunk),
          slots_type_(slots_type),
          typed_slot_set_(typed_slot_set) {}
 MarkingItem()
v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::~MarkingItem () [default]
Member Function Documentation
CheckAndMarkObject()
template<typename Visitor , typename TSlot >
SlotCallbackResult v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::CheckAndMarkObject (Visitor * visitor, TSlot slot) [inline], [private]
Definition at line 146 of file minor-mark-sweep-inl.h.
                                  {
  static_assert(
      std::is_same_v<TSlot, FullMaybeObjectSlot> ||
          std::is_same_v<TSlot, MaybeObjectSlot>,
      "Only FullMaybeObjectSlot and MaybeObjectSlot are expected here");
  return visitor->VisitObjectViaSlotInRememberedSet(slot) ? KEEP_SLOT
                                                          : REMOVE_SLOT;
}
References heap::base::KEEP_SLOT, and heap::base::REMOVE_SLOT.
DeleteRememberedSets()
void v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::DeleteRememberedSets ()
Definition at line 222 of file minor-mark-sweep.cc.
                           {
  DCHECK(IsAcquired());
  if (slots_type_ == SlotsType::kRegularSlots) {
    if (slot_set_) SlotSet::Delete(slot_set_);
    if (background_slot_set_) SlotSet::Delete(background_slot_set_);
  } else {
    DCHECK_EQ(slots_type_, SlotsType::kTypedSlots);
    DCHECK_NULL(background_slot_set_);
    if (typed_slot_set_)
      RememberedSet<OLD_TO_NEW>::DeleteTyped(std::move(*typed_slot_set_));
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, heap::base::BasicSlotSet< kTaggedSize >::Delete(), and v8::internal::RememberedSet< type >::DeleteTyped().
DeleteSetsOnTearDown()
void v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::DeleteSetsOnTearDown ()
Definition at line 236 of file minor-mark-sweep.cc.
                           {
  if (slots_type_ == SlotsType::kRegularSlots) {
    if (slot_set_) SlotSet::Delete(slot_set_);
    if (background_slot_set_) SlotSet::Delete(background_slot_set_);
  } else {
    DCHECK_EQ(slots_type_, SlotsType::kTypedSlots);
    DCHECK_NULL(background_slot_set_);
    if (typed_slot_set_) delete typed_slot_set_;
  }
}
References DCHECK_EQ, DCHECK_NULL, and heap::base::BasicSlotSet< kTaggedSize >::Delete().
heap()
Heap* v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::heap () [inline], [private]
Definition at line 91 of file minor-mark-sweep.h.
{ return chunk_->heap(); }
References chunk_, and v8::internal::MemoryChunkMetadata::heap().
MarkTypedPointers()
template<typename Visitor >
void v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::MarkTypedPointers (Visitor * visitor) [private]
Definition at line 124 of file minor-mark-sweep-inl.h.
                                        {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.gc"),
               "MarkingItem::MarkTypedPointers");
  DCHECK_NULL(background_slot_set_);
  DCHECK_NOT_NULL(typed_slot_set_);
  const auto slot_count = RememberedSet<OLD_TO_NEW>::IterateTyped(
      typed_slot_set_,
      [this, visitor](SlotType slot_type, Address slot_address) {
        Tagged<HeapObject> object = UpdateTypedSlotHelper::GetTargetObject(
            heap(), slot_type, slot_address);
        FullMaybeObjectSlot slot(&object);
        return CheckAndMarkObject(visitor, slot);
      });
  if (slot_count == 0) {
    delete typed_slot_set_;
    typed_slot_set_ = nullptr;
  }
}
References DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::UpdateTypedSlotHelper::GetTargetObject(), heap(), v8::internal::RememberedSet< type >::IterateTyped(), TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Referenced by Process().
MarkUntypedPointers()
template<typename Visitor >
void v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::MarkUntypedPointers (Visitor * visitor) [private]
Definition at line 95 of file minor-mark-sweep-inl.h.
                                          {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.gc"),
               "MarkingItem::MarkUntypedPointers");
  auto callback = [this, visitor](MaybeObjectSlot slot) {
    return CheckAndMarkObject(visitor, slot);
  };
  if (slot_set_) {
    const auto slot_count =
        RememberedSet<OLD_TO_NEW>::template Iterate<AccessMode::NON_ATOMIC>(
            slot_set_, chunk_, callback, SlotSet::FREE_EMPTY_BUCKETS);
    if (slot_count == 0) {
      SlotSet::Delete(slot_set_);
      slot_set_ = nullptr;
    }
  }
  if (background_slot_set_) {
    const auto slot_count =
        RememberedSet<OLD_TO_NEW_BACKGROUND>::template Iterate<
            AccessMode::NON_ATOMIC>(background_slot_set_, chunk_, callback,
                                    SlotSet::FREE_EMPTY_BUCKETS);
    if (slot_count == 0) {
      SlotSet::Delete(background_slot_set_);
      background_slot_set_ = nullptr;
    }
  }
}
References heap::base::BasicSlotSet< kTaggedSize >::Delete(), heap::base::BasicSlotSet< kTaggedSize >::FREE_EMPTY_BUCKETS, v8::internal::NON_ATOMIC, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Referenced by Process().
MergeAndDeleteRememberedSets()
void v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::MergeAndDeleteRememberedSets ()
Definition at line 204 of file minor-mark-sweep.cc.
                                   {
  DCHECK(IsAcquired());
  if (slots_type_ == SlotsType::kRegularSlots) {
    if (slot_set_)
      RememberedSet<OLD_TO_NEW>::MergeAndDelete(chunk_, std::move(*slot_set_));
    if (background_slot_set_)
      RememberedSet<OLD_TO_NEW_BACKGROUND>::MergeAndDelete(
          chunk_, std::move(*background_slot_set_));
  } else {
    DCHECK_EQ(slots_type_, SlotsType::kTypedSlots);
    DCHECK_NULL(background_slot_set_);
    if (typed_slot_set_)
      RememberedSet<OLD_TO_NEW>::MergeAndDeleteTyped(
          chunk_, std::move(*typed_slot_set_));
  }
}
References background_slot_set_, chunk_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, v8::internal::ParallelWorkItem::IsAcquired(), kRegularSlots, kTypedSlots, v8::internal::RememberedSet< type >::MergeAndDelete(), v8::internal::RememberedSet< type >::MergeAndDeleteTyped(), slot_set_, slots_type_, and typed_slot_set_.
Process()
template<typename Visitor >
void v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::Process (Visitor * visitor)
Definition at line 85 of file minor-mark-sweep-inl.h.
                      {
  if (slots_type_ == SlotsType::kRegularSlots) {
    MarkUntypedPointers(visitor);
  } else {
    MarkTypedPointers(visitor);
  }
}
References kRegularSlots, MarkTypedPointers(), MarkUntypedPointers(), and slots_type_.
Member Data Documentation
union { ... } [private]
background_slot_set_
SlotSet* v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::background_slot_set_ = nullptr [private]
Definition at line 107 of file minor-mark-sweep.h.
Referenced by MergeAndDeleteRememberedSets().
chunk_
MutablePageMetadata* const v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::chunk_ [private]
Definition at line 101 of file minor-mark-sweep.h.
Referenced by heap(), and MergeAndDeleteRememberedSets().
slot_set_
SlotSet* v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::slot_set_
Definition at line 104 of file minor-mark-sweep.h.
Referenced by MergeAndDeleteRememberedSets().
slots_type_
const SlotsType v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::slots_type_ [private]
Definition at line 102 of file minor-mark-sweep.h.
Referenced by MergeAndDeleteRememberedSets(), and Process().
typed_slot_set_
TypedSlotSet* v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::typed_slot_set_
Definition at line 105 of file minor-mark-sweep.h.
Referenced by MergeAndDeleteRememberedSets().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/minor-mark-sweep.h
/mnt/V8SourceCode/src/heap/minor-mark-sweep-inl.h
/mnt/V8SourceCode/src/heap/minor-mark-sweep.cc