v8_inspector::V8InspectorImpl::EvaluateScope Class Reference
#include <v8-inspector-impl.h>
Classes
struct CancelToken
class TerminateTask
Public Member Functions
EvaluateScope (const InjectedScript::Scope &scope)
~EvaluateScope ()
protocol::Response setTimeout (double timeout)
Private Attributes
const InjectedScript::Scope & m_scope
v8::Isolate * m_isolate
std::shared_ptr< CancelToken > m_cancelToken
Detailed Description
Definition at line 150 of file v8-inspector-impl.h.
Constructor & Destructor Documentation
EvaluateScope()
v8_inspector::V8InspectorImpl::EvaluateScope::EvaluateScope (const InjectedScript::Scope & scope) [explicit]
Definition at line 462 of file v8-inspector-impl.cc.
    : m_scope(scope), m_isolate(scope.inspector()->isolate()) {}
 EvaluateScope()
v8_inspector::V8InspectorImpl::EvaluateScope::~EvaluateScope ()
Definition at line 471 of file v8-inspector-impl.cc.
                                             {
  if (m_scope.tryCatch().HasTerminated()) {
    m_scope.inspector()->debugger()->reportTermination();
  }
  if (m_cancelToken) {
    v8::base::MutexGuard lock(&m_cancelToken->m_mutex);
    m_cancelToken->m_canceled = true;
    m_isolate->CancelTerminateExecution();
  }
}
References v8::Isolate::CancelTerminateExecution(), and v8_inspector::V8InspectorImpl::m_isolate.
Member Function Documentation
setTimeout()
protocol::Response v8_inspector::V8InspectorImpl::EvaluateScope::setTimeout (double timeout)
Definition at line 500 of file v8-inspector-impl.cc.
                                                                        {
  if (m_isolate->IsExecutionTerminating()) {
    return protocol::Response::ServerError("Execution was terminated");
  }
  m_cancelToken.reset(new CancelToken());
  v8::debug::GetCurrentPlatform()->PostDelayedTaskOnWorkerThread(
      v8::TaskPriority::kUserVisible,
      std::make_unique<TerminateTask>(m_isolate, m_cancelToken), timeout);
  return protocol::Response::Success();
}
References v8::debug::GetCurrentPlatform(), v8::Isolate::IsExecutionTerminating(), v8::kUserVisible, v8_inspector::V8InspectorImpl::m_isolate, and v8::Platform::PostDelayedTaskOnWorkerThread().
Referenced by v8_inspector::V8RuntimeAgentImpl::evaluate(), and v8_inspector::V8DebuggerAgentImpl::evaluateOnCallFrame().
Member Data Documentation
m_cancelToken
std::shared_ptr<CancelToken> v8_inspector::V8InspectorImpl::EvaluateScope::m_cancelToken [private]
Definition at line 163 of file v8-inspector-impl.h.
m_isolate
v8::Isolate* v8_inspector::V8InspectorImpl::EvaluateScope::m_isolate [private]
Definition at line 162 of file v8-inspector-impl.h.
m_scope
const InjectedScript::Scope& v8_inspector::V8InspectorImpl::EvaluateScope::m_scope [private]
Definition at line 161 of file v8-inspector-impl.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-inspector-impl.h
/mnt/V8SourceCode/src/inspector/v8-inspector-impl.cc