v8::internal::SnapshotCreatorImpl Class Reference
#include <snapshot.h>
Classes
struct SerializableContext
Public Member Functions
SnapshotCreatorImpl (Isolate *isolate, const intptr_t *api_external_references, const StartupData *existing_blob, bool owns_isolate)
SnapshotCreatorImpl (const v8::Isolate::CreateParams &params)
SnapshotCreatorImpl (Isolate *isolate, const v8::Isolate::CreateParams &params)
~SnapshotCreatorImpl ()
Isolate * isolate () const
void SetDefaultContext (DirectHandle< NativeContext > context, SerializeEmbedderFieldsCallback callback)
size_t AddContext (DirectHandle< NativeContext > context, SerializeEmbedderFieldsCallback callback)
size_t AddData (DirectHandle< NativeContext > context, Address object)
size_t AddData (Address object)
StartupData CreateBlob (SnapshotCreator::FunctionCodeHandling function_code_handling, Snapshot::SerializerFlags serializer_flags=Snapshot::kDefaultSerializerFlags)
Static Public Member Functions
static SnapshotCreatorImpl * FromSnapshotCreator (v8::SnapshotCreator *snapshot_creator)
Static Public Attributes
static constexpr size_t kDefaultContextIndex = 0
static constexpr size_t kFirstAddtlContextIndex = kDefaultContextIndex + 1
Private Member Functions
void InitInternal (const StartupData *)
DirectHandle< NativeContext > context_at (size_t i) const
bool created () const
Private Attributes
const bool owns_isolate_
Isolate *const isolate_
std::unique_ptr< v8::ArrayBuffer::Allocator > array_buffer_allocator_
std::vector< SerializableContext > contexts_
Detailed Description
Definition at line 152 of file snapshot.h.
Constructor & Destructor Documentation
SnapshotCreatorImpl() [1/3]
v8::internal::SnapshotCreatorImpl::SnapshotCreatorImpl (Isolate * isolate, const intptr_t * api_external_references, const StartupData * existing_blob, bool owns_isolate)
Definition at line 875 of file snapshot.cc.
    : owns_isolate_(owns_isolate),
      isolate_(isolate == nullptr ? Isolate::New() : isolate),
      array_buffer_allocator_(ArrayBuffer::Allocator::NewDefaultAllocator()) {
  DCHECK_NOT_NULL(isolate_);
  isolate_->set_array_buffer_allocator(array_buffer_allocator_.get());
  isolate_->set_api_external_references(api_external_references);
  InitInternal(existing_blob ? existing_blob : Snapshot::DefaultSnapshotBlob());
}
References array_buffer_allocator_, DCHECK_NOT_NULL, v8::internal::Snapshot::DefaultSnapshotBlob(), InitInternal(), isolate_, and v8::internal::Isolate::set_array_buffer_allocator().
SnapshotCreatorImpl() [2/3]
v8::internal::SnapshotCreatorImpl::SnapshotCreatorImpl (const v8::Isolate::CreateParams & params) [explicit]
Definition at line 889 of file snapshot.cc.
    : owns_isolate_(true), isolate_(Isolate::New()) {
  if (auto allocator = params.array_buffer_allocator_shared) {
    CHECK(params.array_buffer_allocator == nullptr ||
          params.array_buffer_allocator == allocator.get());
    isolate_->set_array_buffer_allocator(allocator.get());
    isolate_->set_array_buffer_allocator_shared(std::move(allocator));
  } else {
    CHECK_NOT_NULL(params.array_buffer_allocator);
    isolate_->set_array_buffer_allocator(params.array_buffer_allocator);
  }
  isolate_->set_api_external_references(params.external_references);
  isolate_->heap()->ConfigureHeap(params.constraints, params.cpp_heap);
  InitInternal(params.snapshot_blob ? params.snapshot_blob
                                    : Snapshot::DefaultSnapshotBlob());
}
References v8::Isolate::CreateParams::array_buffer_allocator, v8::Isolate::CreateParams::array_buffer_allocator_shared, CHECK, CHECK_NOT_NULL, v8::internal::Heap::ConfigureHeap(), v8::Isolate::CreateParams::constraints, v8::Isolate::CreateParams::cpp_heap, v8::internal::Snapshot::DefaultSnapshotBlob(), v8::Isolate::CreateParams::external_references, v8::internal::Isolate::heap(), InitInternal(), isolate_, v8::internal::Isolate::set_array_buffer_allocator(), v8::internal::Isolate::set_array_buffer_allocator_shared(), and v8::Isolate::CreateParams::snapshot_blob.
SnapshotCreatorImpl() [3/3]
v8::internal::SnapshotCreatorImpl::SnapshotCreatorImpl (Isolate * isolate, const v8::Isolate::CreateParams & params)
Definition at line 908 of file snapshot.cc.
    : owns_isolate_(false), isolate_(isolate) {
  if (auto allocator = params.array_buffer_allocator_shared) {
    CHECK(params.array_buffer_allocator == nullptr ||
          params.array_buffer_allocator == allocator.get());
    isolate_->set_array_buffer_allocator(allocator.get());
    isolate_->set_array_buffer_allocator_shared(std::move(allocator));
  } else {
    CHECK_NOT_NULL(params.array_buffer_allocator);
    isolate_->set_array_buffer_allocator(params.array_buffer_allocator);
  }
  isolate_->set_api_external_references(params.external_references);
  isolate_->heap()->ConfigureHeap(params.constraints, params.cpp_heap);
  InitInternal(params.snapshot_blob ? params.snapshot_blob
                                    : Snapshot::DefaultSnapshotBlob());
}
References v8::Isolate::CreateParams::array_buffer_allocator, v8::Isolate::CreateParams::array_buffer_allocator_shared, CHECK, CHECK_NOT_NULL, v8::internal::Heap::ConfigureHeap(), v8::Isolate::CreateParams::constraints, v8::Isolate::CreateParams::cpp_heap, v8::internal::Snapshot::DefaultSnapshotBlob(), v8::Isolate::CreateParams::external_references, v8::internal::Isolate::heap(), InitInternal(), isolate_, v8::internal::Isolate::set_array_buffer_allocator(), v8::internal::Isolate::set_array_buffer_allocator_shared(), and v8::Isolate::CreateParams::snapshot_blob.
 SnapshotCreatorImpl()
v8::internal::SnapshotCreatorImpl::~SnapshotCreatorImpl ()
Definition at line 927 of file snapshot.cc.
                                          {
  if (isolate_->heap()->read_only_space()->writable()) {
    // Finalize the RO heap in order to leave the Isolate in a consistent state.
    isolate_->read_only_heap()->OnCreateHeapObjectsComplete(isolate_);
  }
  // Destroy leftover global handles (i.e. if CreateBlob was never called).
  for (size_t i = 0; i < contexts_.size(); i++) {
    DCHECK(!created());
    GlobalHandles::Destroy(contexts_[i].handle_location);
    contexts_[i].handle_location = nullptr;
  }
  isolate_->Exit();
  if (owns_isolate_) Isolate::Delete(isolate_);
}
References contexts_, created(), v8::internal::DCHECK(), v8::internal::Isolate::Delete(), v8::internal::GlobalHandles::Destroy(), v8::internal::Isolate::Exit(), v8::internal::Isolate::heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate_, v8::internal::ReadOnlyHeap::OnCreateHeapObjectsComplete(), owns_isolate_, v8::internal::Isolate::read_only_heap(), v8::internal::Heap::read_only_space(), and v8::internal::ReadOnlySpace::writable().
Member Function Documentation
AddContext()
size_t v8::internal::SnapshotCreatorImpl::AddContext (DirectHandle< NativeContext > context, SerializeEmbedderFieldsCallback callback)
Definition at line 954 of file snapshot.cc.
                                              {
  DCHECK(!context.is_null());
  DCHECK(!created());
  CHECK(isolate_->heap()->Contains(*context));
  size_t index = contexts_.size() - kFirstAddtlContextIndex;
  contexts_.emplace_back(
      isolate_->global_handles()->Create(*context).location(), callback);
  return index;
}
References CHECK, v8::internal::Heap::Contains(), contexts_, v8::internal::GlobalHandles::Create(), created(), v8::internal::DCHECK(), v8::internal::Isolate::global_handles(), v8::internal::Isolate::heap(), v8::internal::index, v8::internal::DirectHandle< T >::is_null(), isolate_, and kFirstAddtlContextIndex.
Referenced by v8::SnapshotCreator::AddContext().
AddData() [1/2]
size_t v8::internal::SnapshotCreatorImpl::AddData (Address object)
Definition at line 986 of file snapshot.cc.
                                                  {
  DCHECK_NE(object, kNullAddress);
  DCHECK(!created());
  HandleScope scope(isolate_);
  DirectHandle<Object> obj(Tagged<Object>(object), isolate_);
  DirectHandle<ArrayList> list;
  if (!IsArrayList(isolate_->heap()->serialized_objects())) {
    list = ArrayList::New(isolate_, 1);
  } else {
    list = direct_handle(
        Cast<ArrayList>(isolate_->heap()->serialized_objects()), isolate_);
  }
  size_t index = static_cast<size_t>(list->length());
  list = ArrayList::Add(isolate_, list, obj);
  isolate_->heap()->SetSerializedObjects(*list);
  return index;
}
References v8::internal::ArrayList::Add(), created(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::direct_handle(), v8::internal::Isolate::heap(), v8::internal::index, isolate_, v8::internal::kNullAddress, v8::internal::ArrayList::New(), and v8::internal::Heap::SetSerializedObjects().
AddData() [2/2]
size_t v8::internal::SnapshotCreatorImpl::AddData (DirectHandle< NativeContext > context, Address object)
Definition at line 966 of file snapshot.cc.
                                                    {
  CHECK(isolate_->heap()->Contains(*context));
  DCHECK_NE(object, kNullAddress);
  DCHECK(!created());
  HandleScope scope(isolate_);
  DirectHandle<Object> obj(Tagged<Object>(object), isolate_);
  DirectHandle<ArrayList> list;
  if (!IsArrayList(context->serialized_objects())) {
    list = ArrayList::New(isolate_, 1);
  } else {
    list =
        direct_handle(Cast<ArrayList>(context->serialized_objects()), isolate_);
  }
  size_t index = static_cast<size_t>(list->length());
  list = ArrayList::Add(isolate_, list, obj);
  context->set_serialized_objects(*list);
  return index;
}
References v8::internal::ArrayList::Add(), CHECK, v8::internal::Heap::Contains(), created(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::direct_handle(), v8::internal::Isolate::heap(), v8::internal::index, isolate_, v8::internal::kNullAddress, and v8::internal::ArrayList::New().
Referenced by v8::SnapshotCreator::AddData().
context_at()
DirectHandle< NativeContext > v8::internal::SnapshotCreatorImpl::context_at (size_t i) const [private]
Definition at line 1004 of file snapshot.cc.
                                                                          {
  return DirectHandle<NativeContext>::FromSlot(contexts_[i].handle_location);
}
References contexts_.
Referenced by CreateBlob().
CreateBlob()
StartupData v8::internal::SnapshotCreatorImpl::CreateBlob (SnapshotCreator::FunctionCodeHandling function_code_handling, Snapshot::SerializerFlags serializer_flags = Snapshot::kDefaultSerializerFlags)
Definition at line 1037 of file snapshot.cc.
                                              {
  CHECK(!created());
  CHECK(contexts_[kDefaultContextIndex].handle_location != nullptr);
  const size_t num_contexts = contexts_.size();
  const size_t num_additional_contexts = num_contexts - 1;
  // Create and store lists of embedder-provided data needed during
  // serialization.
  {
    HandleScope scope(isolate_);
    // Convert list of context-independent data to FixedArray.
    ConvertSerializedObjectsToFixedArray(isolate_);
    // Convert lists of context-dependent data to FixedArray.
    for (size_t i = 0; i < num_contexts; i++) {
      ConvertSerializedObjectsToFixedArray(isolate_, context_at(i));
    }
    // We need to store the global proxy size upfront in case we need the
    // bootstrapper to create a global proxy before we deserialize the context.
    DirectHandle<FixedArray> global_proxy_sizes =
        isolate_->factory()->NewFixedArray(
            static_cast<int>(num_additional_contexts), AllocationType::kOld);
    for (size_t i = kFirstAddtlContextIndex; i < num_contexts; i++) {
      global_proxy_sizes->set(
          static_cast<int>(i - kFirstAddtlContextIndex),
          Smi::FromInt(context_at(i)->global_proxy()->Size()));
    }
    isolate_->heap()->SetSerializedGlobalProxySizes(*global_proxy_sizes);
  }
  // We might rehash strings and re-sort descriptors. Clear the lookup cache.
  isolate_->descriptor_lookup_cache()->Clear();
  // If we don't do this then we end up with a stray root pointing at the
  // context even after we have disposed of the context.
  {
    // Note that we need to run a garbage collection without stack at this
    // point, so that all dead objects are reclaimed. This is required to avoid
    // conservative stack scanning and guarantee deterministic behaviour.
    EmbedderStackStateScope stack_scope(
        isolate_->heap(), EmbedderStackStateOrigin::kExplicitInvocation,
        StackState::kNoHeapPointers);
    isolate_->heap()->CollectAllAvailableGarbage(
        GarbageCollectionReason::kSnapshotCreator);
  }
  {
    HandleScope scope(isolate_);
    isolate_->heap()->CompactWeakArrayLists();
  }
  Snapshot::ClearReconstructableDataForSerialization(
      isolate_,
      function_code_handling == SnapshotCreator::FunctionCodeHandling::kClear);
  SafepointKind safepoint_kind = isolate_->has_shared_space()
                                     ? SafepointKind::kGlobal
                                     : SafepointKind::kIsolate;
  SafepointScope safepoint_scope(isolate_, safepoint_kind);
  DisallowGarbageCollection no_gc_from_here_on;
  // RO space is usually writable when serializing a snapshot s.t. preceding
  // heap initialization can also extend RO space. There are notable exceptions
  // though, including --stress-snapshot and serializer cctests.
  if (isolate_->heap()->read_only_space()->writable()) {
    // Promote objects from mutable heap spaces to read-only space prior to
    // serialization. Objects can be promoted if a) they are themselves
    // immutable-after-deserialization and b) all objects in the transitive
    // object graph also satisfy condition a).
    ReadOnlyPromotion::Promote(isolate_, safepoint_scope, no_gc_from_here_on);
    // When creating the snapshot from scratch, we are responsible for sealing
    // the RO heap here. Note we cannot delegate the responsibility e.g. to
    // Isolate::Init since it should still be possible to allocate into RO
    // space after the Isolate has been initialized, for example as part of
    // Context creation.
    isolate_->read_only_heap()->OnCreateHeapObjectsComplete(isolate_);
  }
  // Create a vector with all contexts and destroy associated global handles.
  // This is important because serialization visits active global handles as
  // roots, which we don't want for our internal SnapshotCreatorImpl-related
  // data.
  // Note these contexts may be dead after calling Clear(), but will not be
  // collected until serialization completes and the DisallowGarbageCollection
  // scope above goes out of scope.
  std::vector<Tagged<Context>> raw_contexts;
  raw_contexts.reserve(num_contexts);
  {
    HandleScope scope(isolate_);
    for (size_t i = 0; i < num_contexts; i++) {
      raw_contexts.push_back(*context_at(i));
      GlobalHandles::Destroy(contexts_[i].handle_location);
      contexts_[i].handle_location = nullptr;
    }
  }
  // Check that values referenced by global/eternal handles are accounted for.
  SerializedHandleChecker handle_checker(isolate_, &raw_contexts);
  if (!handle_checker.CheckGlobalAndEternalHandles()) {
    GRACEFUL_FATAL("CheckGlobalAndEternalHandles failed");
  }
  // Create a vector with all embedder fields serializers.
  std::vector<SerializeEmbedderFieldsCallback> raw_callbacks;
  raw_callbacks.reserve(num_contexts);
  for (size_t i = 0; i < num_contexts; i++) {
    raw_callbacks.push_back(contexts_[i].callback);
  }
  contexts_.clear();
  return Snapshot::Create(isolate_, &raw_contexts, raw_callbacks,
                          safepoint_scope, no_gc_from_here_on,
                          serializer_flags);
}
References CHECK, v8::internal::SerializedHandleChecker::CheckGlobalAndEternalHandles(), v8::internal::DescriptorLookupCache::Clear(), v8::internal::Snapshot::ClearReconstructableDataForSerialization(), v8::internal::Heap::CollectAllAvailableGarbage(), v8::internal::Heap::CompactWeakArrayLists(), context_at(), contexts_, v8::internal::anonymous_namespace{snapshot.cc}::ConvertSerializedObjectsToFixedArray(), v8::internal::Snapshot::Create(), created(), v8::internal::Isolate::descriptor_lookup_cache(), v8::internal::GlobalHandles::Destroy(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), GRACEFUL_FATAL, v8::internal::Isolate::has_shared_space(), v8::internal::Isolate::heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate_, v8::SnapshotCreator::kClear, kDefaultContextIndex, v8::internal::kExplicitInvocation, kFirstAddtlContextIndex, v8::internal::kGlobal, v8::internal::kIsolate, v8::internal::kOld, v8::internal::kSnapshotCreator, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::ReadOnlyHeap::OnCreateHeapObjectsComplete(), v8::internal::ReadOnlyPromotion::Promote(), v8::internal::Isolate::read_only_heap(), v8::internal::Heap::read_only_space(), v8::internal::Heap::SetSerializedGlobalProxySizes(), and v8::internal::ReadOnlySpace::writable().
Referenced by v8::SnapshotCreator::CreateBlob(), and v8::internal::CreateSnapshotDataBlobInternal().
created()
bool v8::internal::SnapshotCreatorImpl::created () const [inline], [private]
Definition at line 203 of file snapshot.h.
{ return contexts_.size() == 0; }
References contexts_.
Referenced by AddContext(), AddData(), CreateBlob(), SetDefaultContext(), and ~SnapshotCreatorImpl().
FromSnapshotCreator()
SnapshotCreatorImpl * v8::internal::SnapshotCreatorImpl::FromSnapshotCreator (v8::SnapshotCreator * snapshot_creator) [static]
Definition at line 1156 of file snapshot.cc.
                                         {
  return snapshot_creator->impl_;
}
References v8::SnapshotCreator::impl_.
Referenced by v8::internal::CreateSnapshotDataBlobInternal().
InitInternal()
void v8::internal::SnapshotCreatorImpl::InitInternal (const StartupData * blob) [private]
Definition at line 854 of file snapshot.cc.
                                                              {
  isolate_->enable_serializer();
  isolate_->Enter();
  if (blob != nullptr && blob->raw_size > 0) {
    isolate_->set_snapshot_blob(blob);
    Snapshot::Initialize(isolate_);
  } else {
    isolate_->InitWithoutSnapshot();
  }
#ifdef V8_ENABLE_SPARKPLUG
  isolate_->baseline_batch_compiler()->set_enabled(false);
#endif // V8_ENABLE_SPARKPLUG
  // Reserve a spot for the default context s.t. the call sequence of
  // SetDefaultContext / AddContext remains independent.
  contexts_.push_back(SerializableContext{});
  DCHECK_EQ(contexts_.size(), kDefaultContextIndex + 1);
}
References contexts_, DCHECK_EQ, v8::internal::Isolate::enable_serializer(), v8::internal::Isolate::Enter(), v8::internal::Snapshot::Initialize(), v8::internal::Isolate::InitWithoutSnapshot(), isolate_, kDefaultContextIndex, and v8::StartupData::raw_size.
Referenced by SnapshotCreatorImpl().
isolate()
Isolate* v8::internal::SnapshotCreatorImpl::isolate () const [inline]
Definition at line 169 of file snapshot.h.
{ return isolate_; }
References isolate_.
Referenced by v8::internal::CreateSnapshotDataBlobInternal(), and v8::SnapshotCreator::GetIsolate().
SetDefaultContext()
void v8::internal::SnapshotCreatorImpl::SetDefaultContext (DirectHandle< NativeContext > context, SerializeEmbedderFieldsCallback callback)
Definition at line 942 of file snapshot.cc.
                                              {
  DCHECK(contexts_[kDefaultContextIndex].handle_location == nullptr);
  DCHECK(!context.is_null());
  DCHECK(!created());
  CHECK(isolate_->heap()->Contains(*context));
  contexts_[kDefaultContextIndex].handle_location =
      isolate_->global_handles()->Create(*context).location();
  contexts_[kDefaultContextIndex].callback = callback;
}
References CHECK, v8::internal::Heap::Contains(), contexts_, v8::internal::GlobalHandles::Create(), created(), v8::internal::DCHECK(), v8::internal::Isolate::global_handles(), v8::internal::Isolate::heap(), v8::internal::DirectHandle< T >::is_null(), isolate_, and kDefaultContextIndex.
Referenced by v8::internal::CreateSnapshotDataBlobInternal(), and v8::SnapshotCreator::SetDefaultContext().
Member Data Documentation
array_buffer_allocator_
std::unique_ptr<v8::ArrayBuffer::Allocator> v8::internal::SnapshotCreatorImpl::array_buffer_allocator_ [private]
Definition at line 207 of file snapshot.h.
Referenced by SnapshotCreatorImpl().
contexts_
std::vector<SerializableContext> v8::internal::SnapshotCreatorImpl::contexts_ [private]
Definition at line 208 of file snapshot.h.
Referenced by AddContext(), context_at(), CreateBlob(), created(), InitInternal(), SetDefaultContext(), and ~SnapshotCreatorImpl().
isolate_
Isolate* const v8::internal::SnapshotCreatorImpl::isolate_ [private]
Definition at line 206 of file snapshot.h.
Referenced by AddContext(), AddData(), CreateBlob(), InitInternal(), isolate(), SetDefaultContext(), SnapshotCreatorImpl(), and ~SnapshotCreatorImpl().
kDefaultContextIndex
constexpr size_t v8::internal::SnapshotCreatorImpl::kDefaultContextIndex = 0 [static], [constexpr]
Definition at line 187 of file snapshot.h.
Referenced by CreateBlob(), InitInternal(), and SetDefaultContext().
kFirstAddtlContextIndex
constexpr size_t v8::internal::SnapshotCreatorImpl::kFirstAddtlContextIndex = kDefaultContextIndex + 1 [static], [constexpr]
Definition at line 188 of file snapshot.h.
Referenced by AddContext(), CreateBlob(), and v8::internal::Genesis::Genesis().
owns_isolate_
const bool v8::internal::SnapshotCreatorImpl::owns_isolate_ [private]
Definition at line 205 of file snapshot.h.
Referenced by ~SnapshotCreatorImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/snapshot.h
/mnt/V8SourceCode/src/snapshot/snapshot.cc