v8::internal::InfoCellPair Class Reference
#include <compilation-cache-table.h>
Public Member Functions
InfoCellPair ()=default
InfoCellPair (Isolate *isolate, Tagged< SharedFunctionInfo > shared, Tagged< JSFunction > js_function)
Tagged< JSFunction > js_function () const
Tagged< SharedFunctionInfo > shared () const
bool has_js_function () const
bool has_shared () const
Private Attributes
IsCompiledScope is_compiled_scope_
Tagged< SharedFunctionInfo > shared_
Tagged< JSFunction > js_function_
Detailed Description
Definition at line 52 of file compilation-cache-table.h.
Constructor & Destructor Documentation
InfoCellPair() [1/2]
v8::internal::InfoCellPair::InfoCellPair () [default]
InfoCellPair() [2/2]
v8::internal::InfoCellPair::InfoCellPair (Isolate * isolate, Tagged< SharedFunctionInfo > shared, Tagged< JSFunction > js_function) [inline]
Definition at line 171 of file compilation-cache-table-inl.h.
    : is_compiled_scope_(!shared.is_null() ? shared->is_compiled_scope(isolate)
                                           : IsCompiledScope()),
      shared_(shared),
      js_function_(js_function) {}
Member Function Documentation
has_js_function()
bool v8::internal::InfoCellPair::has_js_function () const [inline]
Definition at line 67 of file compilation-cache-table.h.
                               {
    return !js_function_.is_null() && is_compiled_scope_.is_compiled();
  }
References v8::internal::IsCompiledScope::is_compiled(), is_compiled_scope_, and js_function_.
Referenced by v8::internal::Compiler::GetFunctionFromEval().
has_shared()
bool v8::internal::InfoCellPair::has_shared () const [inline]
Definition at line 70 of file compilation-cache-table.h.
                          {
    // Only return true if SFI is compiled - the bytecode could have been
    // flushed while it's in the compilation cache, and not yet have been
    // removed form the compilation cache.
    return !shared_.is_null() && is_compiled_scope_.is_compiled();
  }
References v8::internal::IsCompiledScope::is_compiled(), is_compiled_scope_, and shared_.
Referenced by v8::internal::Compiler::GetFunctionFromEval().
js_function()
Tagged<JSFunction> v8::internal::InfoCellPair::js_function () const [inline]
Definition at line 58 of file compilation-cache-table.h.
                                         {
    DCHECK(is_compiled_scope_.is_compiled());
    return js_function_;
  }
References v8::internal::DCHECK(), v8::internal::IsCompiledScope::is_compiled(), is_compiled_scope_, and js_function_.
Referenced by v8::internal::Compiler::GetFunctionFromEval().
shared()
Tagged<SharedFunctionInfo> v8::internal::InfoCellPair::shared () const [inline]
Definition at line 62 of file compilation-cache-table.h.
                                            {
    DCHECK(is_compiled_scope_.is_compiled());
    return shared_;
  }
References v8::internal::DCHECK(), v8::internal::IsCompiledScope::is_compiled(), is_compiled_scope_, and shared_.
Referenced by v8::internal::Compiler::GetFunctionFromEval().
Member Data Documentation
is_compiled_scope_
IsCompiledScope v8::internal::InfoCellPair::is_compiled_scope_ [private]
Definition at line 78 of file compilation-cache-table.h.
Referenced by has_js_function(), has_shared(), js_function(), and shared().
js_function_
Tagged<JSFunction> v8::internal::InfoCellPair::js_function_ [private]
Definition at line 80 of file compilation-cache-table.h.
Referenced by has_js_function(), and js_function().
shared_
Tagged<SharedFunctionInfo> v8::internal::InfoCellPair::shared_ [private]
Definition at line 79 of file compilation-cache-table.h.
Referenced by has_shared(), and shared().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/compilation-cache-table.h
/mnt/V8SourceCode/src/objects/compilation-cache-table-inl.h