v8::internal::MessageLocation Class Reference
#include <messages.h>
Public Member Functions
MessageLocation (Handle< Script > script, int start_pos, int end_pos)
MessageLocation (Handle< Script > script, int start_pos, int end_pos, Handle< SharedFunctionInfo > shared)
MessageLocation (Handle< Script > script, Handle< SharedFunctionInfo > shared, int bytecode_offset)
MessageLocation ()
Handle< Script > script () const
int start_pos () const
int end_pos () const
int bytecode_offset () const
Handle< SharedFunctionInfo > shared () const
Private Attributes
Handle< Script > script_
int start_pos_
int end_pos_
int bytecode_offset_
Handle< SharedFunctionInfo > shared_
Detailed Description
Definition at line 36 of file messages.h.
Constructor & Destructor Documentation
MessageLocation() [1/4]
v8::internal::MessageLocation::MessageLocation (Handle< Script > script, int start_pos, int end_pos)
Definition at line 32 of file messages.cc.
    : script_(script),
      start_pos_(start_pos),
      end_pos_(end_pos),
      bytecode_offset_(-1) {}
MessageLocation() [2/4]
v8::internal::MessageLocation::MessageLocation (Handle< Script > script, int start_pos, int end_pos, Handle< SharedFunctionInfo > shared)
Definition at line 39 of file messages.cc.
    : script_(script),
      start_pos_(start_pos),
      end_pos_(end_pos),
      bytecode_offset_(-1),
      shared_(shared) {}
MessageLocation() [3/4]
v8::internal::MessageLocation::MessageLocation (Handle< Script > script, Handle< SharedFunctionInfo > shared, int bytecode_offset)
Definition at line 47 of file messages.cc.
    : script_(script),
      start_pos_(-1),
      end_pos_(-1),
      bytecode_offset_(bytecode_offset),
      shared_(shared) {}
MessageLocation() [4/4]
v8::internal::MessageLocation::MessageLocation ()
Definition at line 56 of file messages.cc.
    : start_pos_(-1), end_pos_(-1), bytecode_offset_(-1) {}
Member Function Documentation
bytecode_offset()
int v8::internal::MessageLocation::bytecode_offset () const [inline]
Definition at line 53 of file messages.h.
{ return bytecode_offset_; }
Referenced by v8::internal::MessageHandler::MakeMessageObject().
end_pos()
int v8::internal::MessageLocation::end_pos () const [inline]
Definition at line 52 of file messages.h.
{ return end_pos_; }
Referenced by v8::internal::MessageHandler::MakeMessageObject(), v8::internal::Isolate::Throw(), and v8::internal::Isolate::ThrowAt().
script()
Handle<Script> v8::internal::MessageLocation::script () const [inline]
Definition at line 50 of file messages.h.
{ return script_; }
Referenced by v8::internal::MessageHandler::MakeMessageObject(), v8::internal::anonymous_namespace{isolate.cc}::ReportBootstrappingException(), v8::internal::Isolate::Throw(), v8::internal::Isolate::ThrowAt(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), and v8::internal::ErrorUtils::ThrowSpreadArgError().
shared()
Handle<SharedFunctionInfo> v8::internal::MessageLocation::shared () const [inline]
Definition at line 54 of file messages.h.
{ return shared_; }
Referenced by v8::internal::MessageHandler::MakeMessageObject(), v8::internal::anonymous_namespace{messages.cc}::RenderCallSite(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), and v8::internal::ErrorUtils::ThrowSpreadArgError().
start_pos()
int v8::internal::MessageLocation::start_pos () const [inline]
Definition at line 51 of file messages.h.
{ return start_pos_; }
Referenced by v8::internal::MessageHandler::MakeMessageObject(), v8::internal::anonymous_namespace{messages.cc}::RenderCallSite(), v8::internal::anonymous_namespace{isolate.cc}::ReportBootstrappingException(), v8::internal::Isolate::Throw(), v8::internal::Isolate::ThrowAt(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), and v8::internal::ErrorUtils::ThrowSpreadArgError().
Member Data Documentation
bytecode_offset_
int v8::internal::MessageLocation::bytecode_offset_ [private]
Definition at line 60 of file messages.h.
end_pos_
int v8::internal::MessageLocation::end_pos_ [private]
Definition at line 59 of file messages.h.
script_
Handle<Script> v8::internal::MessageLocation::script_ [private]
Definition at line 57 of file messages.h.
shared_
Handle<SharedFunctionInfo> v8::internal::MessageLocation::shared_ [private]
Definition at line 61 of file messages.h.
start_pos_
int v8::internal::MessageLocation::start_pos_ [private]
Definition at line 58 of file messages.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/messages.h
/mnt/V8SourceCode/src/execution/messages.cc