v8::internal::SignatureBuilder< SigT, T > Class Template Reference
#include <signature.h>
Public Member Functions
SignatureBuilder (Zone *zone, size_t return_count, size_t parameter_count)
void AddReturn (T val)
void AddReturnAt (size_t index, T val)
void AddParam (T val)
void AddParamAt (size_t index, T val)
SigT * Get () const
Public Attributes
const size_t return_count_
const size_t parameter_count_
Protected Attributes
size_t rcursor_
size_t pcursor_
SigT * sig_
T * buffer_
Detailed Description
template<typename SigT, typename T>
class v8::internal::SignatureBuilder< SigT, T >
Definition at line 18 of file signature.h.
Constructor & Destructor Documentation
SignatureBuilder()
template<typename SigT , typename T >
v8::internal::SignatureBuilder< SigT, T >::SignatureBuilder (Zone * zone, size_t return_count, size_t parameter_count) [inline]
Definition at line 20 of file signature.h.
      : return_count_(return_count),
        parameter_count_(parameter_count),
        rcursor_(0),
        pcursor_(0) {
    // Allocate memory for the signature plus the array backing the
    // signature.
    constexpr size_t padding = sizeof(SigT) % alignof(T);
    using AllocationTypeTag = SignatureBuilder;
    const size_t allocated_bytes =
        sizeof(SigT) + padding + sizeof(T) * (return_count + parameter_count);
    void* memory = zone->Allocate<AllocationTypeTag>(allocated_bytes);
    uint8_t* rep_buffer =
        reinterpret_cast<uint8_t*>(memory) + sizeof(SigT) + padding;
    DCHECK(IsAligned(reinterpret_cast<uintptr_t>(rep_buffer), alignof(T)));
    buffer_ = reinterpret_cast<T*>(rep_buffer);
    sig_ = new (memory) SigT{return_count, parameter_count, buffer_};
  }
References v8::internal::Zone::Allocate(), v8::internal::SignatureBuilder< SigT, T >::buffer_, v8::internal::DCHECK(), IsAligned(), and v8::internal::SignatureBuilder< SigT, T >::sig_.
Member Function Documentation
AddParam()
template<typename SigT , typename T >
void v8::internal::SignatureBuilder< SigT, T >::AddParam (T val) [inline]
Definition at line 53 of file signature.h.
                       {
    DCHECK_LT(pcursor_, parameter_count_);
    buffer_[return_count_ + pcursor_++] = val;
  }
References v8::internal::SignatureBuilder< SigT, T >::buffer_, DCHECK_LT, v8::internal::SignatureBuilder< SigT, T >::parameter_count_, v8::internal::SignatureBuilder< SigT, T >::pcursor_, and v8::internal::SignatureBuilder< SigT, T >::return_count_.
Referenced by v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::Signature< T >::Build(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject(), v8::internal::compiler::BuildParameterLocations(), v8::internal::compiler::anonymous_namespace{raw-machine-assembler.cc}::CallCFunctionImpl(), v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertJSPrimitiveToUntaggedOrDeopt(), v8::internal::wasm::AsmJsParser::ConvertSignature(), v8::internal::compiler::CreateMachineSignature(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateSignature(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateSig(), v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::GetFunctionSigForFastApiImport(), v8::internal::compiler::Linkage::GetJSCallDescriptor(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::RepresentationChanger::Ieee754Fp16RawBitsToFp32RawBitsOperator(), v8::internal::compiler::RepresentationChanger::Ieee754Fp64ToFp16RawBitsOperator(), v8::internal::wasm::anonymous_namespace{value-type.cc}::ReplaceTypeInSig(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
AddParamAt()
template<typename SigT , typename T >
void v8::internal::SignatureBuilder< SigT, T >::AddParamAt (size_t index, T val) [inline]
Definition at line 58 of file signature.h.
                                       {
    DCHECK_LT(index, parameter_count_);
    buffer_[return_count_ + index] = val;
    pcursor_ = std::max(pcursor_, index + 1);
  }
References v8::internal::SignatureBuilder< SigT, T >::buffer_, DCHECK_LT, v8::internal::index, v8::internal::SignatureBuilder< SigT, T >::parameter_count_, v8::internal::SignatureBuilder< SigT, T >::pcursor_, and v8::internal::SignatureBuilder< SigT, T >::return_count_.
AddReturn()
template<typename SigT , typename T >
void v8::internal::SignatureBuilder< SigT, T >::AddReturn (T val) [inline]
Definition at line 42 of file signature.h.
                        {
    DCHECK_LT(rcursor_, return_count_);
    buffer_[rcursor_++] = val;
  }
References v8::internal::SignatureBuilder< SigT, T >::buffer_, DCHECK_LT, v8::internal::SignatureBuilder< SigT, T >::rcursor_, and v8::internal::SignatureBuilder< SigT, T >::return_count_.
Referenced by v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::Signature< T >::Build(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject(), v8::internal::compiler::anonymous_namespace{raw-machine-assembler.cc}::CallCFunctionImpl(), v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertJSPrimitiveToUntaggedOrDeopt(), v8::internal::wasm::AsmJsParser::ConvertSignature(), v8::internal::compiler::CreateMachineSignature(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateSignature(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateSig(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::GetFunctionSigForFastApiImport(), v8::internal::compiler::Linkage::GetJSCallDescriptor(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::RepresentationChanger::Ieee754Fp16RawBitsToFp32RawBitsOperator(), v8::internal::compiler::RepresentationChanger::Ieee754Fp64ToFp16RawBitsOperator(), v8::internal::wasm::anonymous_namespace{value-type.cc}::ReplaceTypeInSig(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
AddReturnAt()
template<typename SigT , typename T >
void v8::internal::SignatureBuilder< SigT, T >::AddReturnAt (size_t index, T val) [inline]
Definition at line 47 of file signature.h.
                                        {
    DCHECK_LT(index, return_count_);
    buffer_[index] = val;
    rcursor_ = std::max(rcursor_, index + 1);
  }
References v8::internal::SignatureBuilder< SigT, T >::buffer_, DCHECK_LT, v8::internal::index, v8::internal::SignatureBuilder< SigT, T >::rcursor_, and v8::internal::SignatureBuilder< SigT, T >::return_count_.
Get()
template<typename SigT , typename T >
SigT* v8::internal::SignatureBuilder< SigT, T >::Get () const [inline]
Definition at line 64 of file signature.h.
                    {
    DCHECK_EQ(rcursor_, return_count_);
    DCHECK_EQ(pcursor_, parameter_count_);
    DCHECK_NOT_NULL(sig_);
    return sig_;
  }
References DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::SignatureBuilder< SigT, T >::parameter_count_, v8::internal::SignatureBuilder< SigT, T >::pcursor_, v8::internal::SignatureBuilder< SigT, T >::rcursor_, v8::internal::SignatureBuilder< SigT, T >::return_count_, and v8::internal::SignatureBuilder< SigT, T >::sig_.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::Signature< T >::Build(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject(), v8::internal::compiler::BuildLocations(), v8::internal::compiler::anonymous_namespace{raw-machine-assembler.cc}::CallCFunctionImpl(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertJSPrimitiveToUntaggedOrDeopt(), v8::internal::wasm::AsmJsParser::ConvertSignature(), v8::internal::compiler::CreateMachineSignature(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateSignature(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateSig(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::GetFunctionSigForFastApiImport(), v8::internal::compiler::Linkage::GetJSCallDescriptor(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::RepresentationChanger::Ieee754Fp16RawBitsToFp32RawBitsOperator(), v8::internal::compiler::RepresentationChanger::Ieee754Fp64ToFp16RawBitsOperator(), v8::internal::wasm::anonymous_namespace{value-type.cc}::ReplaceTypeInSig(), v8::internal::wasm::AsmJsParser::ValidateModule(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
Member Data Documentation
buffer_
template<typename SigT , typename T >
T* v8::internal::SignatureBuilder< SigT, T >::buffer_ [protected]
Definition at line 75 of file signature.h.
Referenced by v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddParamAt(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::SignatureBuilder< SigT, T >::AddReturnAt(), and v8::internal::SignatureBuilder< SigT, T >::SignatureBuilder().
parameter_count_
template<typename SigT , typename T >
const size_t v8::internal::SignatureBuilder< SigT, T >::parameter_count_
Definition at line 40 of file signature.h.
Referenced by v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddParamAt(), and v8::internal::SignatureBuilder< SigT, T >::Get().
pcursor_
template<typename SigT , typename T >
size_t v8::internal::SignatureBuilder< SigT, T >::pcursor_ [protected]
Definition at line 73 of file signature.h.
Referenced by v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddParamAt(), and v8::internal::SignatureBuilder< SigT, T >::Get().
rcursor_
template<typename SigT , typename T >
size_t v8::internal::SignatureBuilder< SigT, T >::rcursor_ [protected]
Definition at line 72 of file signature.h.
Referenced by v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::SignatureBuilder< SigT, T >::AddReturnAt(), and v8::internal::SignatureBuilder< SigT, T >::Get().
return_count_
template<typename SigT , typename T >
const size_t v8::internal::SignatureBuilder< SigT, T >::return_count_
Definition at line 39 of file signature.h.
Referenced by v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddParamAt(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::SignatureBuilder< SigT, T >::AddReturnAt(), v8::internal::SignatureBuilder< SigT, T >::Get(), and v8::internal::compiler::Linkage::GetSimplifiedCDescriptor().
sig_
template<typename SigT , typename T >
SigT* v8::internal::SignatureBuilder< SigT, T >::sig_ [protected]
Definition at line 74 of file signature.h.
Referenced by v8::internal::SignatureBuilder< SigT, T >::Get(), and v8::internal::SignatureBuilder< SigT, T >::SignatureBuilder().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/signature.h