v8::internal::JSDateTimeFormat Class Reference
#include <js-date-time-format.h>
Public Types
enum class RequiredOption { kDate
, kTime
, kAny
 }
enum class DefaultsOption { kDate
, kTime
, kAll
 }
enum class DateTimeStyle {
kUndefined
, kFull
, kLong
, kMedium
,
kShort
 }
enum class HourCycle {
kUndefined
, kH11
, kH12
, kH23
,
kH24
 }
Public Member Functions
Handle< String > HourCycleAsString (Isolate *isolate) const
void set_hour_cycle (HourCycle hour_cycle)
HourCycle hour_cycle () const
void set_date_style (DateTimeStyle date_style)
DateTimeStyle date_style () const
void set_time_style (DateTimeStyle time_style)
DateTimeStyle time_style () const
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSDateTimeFormat > New (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options, const char *service)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSDateTimeFormat > CreateDateTimeFormat (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options, RequiredOption required, DefaultsOption defaults, const char *service)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSObject > ResolvedOptions (Isolate *isolate, DirectHandle< JSDateTimeFormat > date_time_format)
static V8_WARN_UNUSED_RESULT DirectHandle< String > Calendar (Isolate *isolate, DirectHandle< JSDateTimeFormat > date_time_format)
static V8_WARN_UNUSED_RESULT DirectHandle< Object > TimeZone (Isolate *isolate, DirectHandle< JSDateTimeFormat > date_time_format)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSDateTimeFormat > UnwrapDateTimeFormat (Isolate *isolate, Handle< JSReceiver > format_holder)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > DateTimeFormat (Isolate *isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > date, const char *method_name)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSArray > FormatToParts (Isolate *isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > x, bool output_source, const char *method_name)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > FormatRange (Isolate *isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > x_date_value, DirectHandle< Object > y_date_value, const char *method_name)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSArray > FormatRangeToParts (Isolate *isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > x_date_value, DirectHandle< Object > y_date_value, const char *method_name)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToLocaleDateTime (Isolate *isolate, DirectHandle< Object > date, DirectHandle< Object > locales, DirectHandle< Object > options, RequiredOption required, DefaultsOption defaults, const char *method_name)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > TemporalToLocaleString (Isolate *isolate, DirectHandle< JSReceiver > temporal, DirectHandle< Object > locales, DirectHandle< Object > options, const char *method_name)
static V8_EXPORT_PRIVATE const std::set< std::string > & GetAvailableLocales ()
static DirectHandle< Object > TimeZoneId (Isolate *isolate, const icu::TimeZone &tz)
static V8_WARN_UNUSED_RESULT MaybeHandle< String > TimeZoneIdToString (Isolate *isolate, const icu::UnicodeString &id)
static std::unique_ptr< icu::TimeZone > CreateTimeZone (Isolate *isolate, DirectHandle< String > time_zone)
static V8_EXPORT_PRIVATE std::string CanonicalizeTimeZoneID (const std::string &input)
Detailed Description
Definition at line 36 of file js-date-time-format.h.
Member Enumeration Documentation
DateTimeStyle
enum v8::internal::JSDateTimeFormat::DateTimeStyle [strong]
Enumerator
kUndefined
kFull
kLong
kMedium
kShort
Definition at line 116 of file js-date-time-format.h.
{ kUndefined, kFull, kLong, kMedium, kShort };
DefaultsOption
enum v8::internal::JSDateTimeFormat::DefaultsOption [strong]
Enumerator
kDate
kTime
kAll
Definition at line 41 of file js-date-time-format.h.
{ kDate, kTime, kAll };
HourCycle
enum v8::internal::JSDateTimeFormat::HourCycle [strong]
Enumerator
kUndefined
kH11
kH12
kH23
kH24
Definition at line 119 of file js-date-time-format.h.
{ kUndefined, kH11, kH12, kH23, kH24 };
RequiredOption
enum v8::internal::JSDateTimeFormat::RequiredOption [strong]
Enumerator
kDate
kTime
kAny
Definition at line 40 of file js-date-time-format.h.
{ kDate, kTime, kAny };
Member Function Documentation
Calendar()
DirectHandle< String > v8::internal::JSDateTimeFormat::Calendar (Isolate * isolate, DirectHandle< JSDateTimeFormat > date_time_format) [static]
Definition at line 632 of file js-date-time-format.cc.
                                                                       {
  return GetCalendar(isolate,
                     *(date_time_format->icu_simple_date_format()->raw()));
}
References v8::internal::anonymous_namespace{js-date-time-format.cc}::GetCalendar().
Referenced by v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatDateTimeWithTemporalSupport(), and ResolvedOptions().
CanonicalizeTimeZoneID()
std::string v8::internal::JSDateTimeFormat::CanonicalizeTimeZoneID (const std::string & input) [static]
Definition at line 485 of file js-date-time-format.cc.
                                                                         {
  std::string upper = input;
  transform(upper.begin(), upper.end(), upper.begin(),
            LocaleIndependentAsciiToUpper);
  if (upper.length() == 3) {
    if (upper == "GMT") return "UTC";
    // For id such as "CET", return upper case.
    return upper;
  } else if (upper.length() == 7 && '0' <= upper[3] && upper[3] <= '9') {
    // For id such as "CST6CDT", return upper case.
    return upper;
  } else if (upper.length() > 3) {
    if (memcmp(upper.c_str(), "ETC", 3) == 0) {
      if (upper == "ETC/UTC" || upper == "ETC/GMT" || upper == "ETC/UCT") {
        return "UTC";
      }
      if (strncmp(upper.c_str(), "ETC/GMT", 7) == 0) {
        return GetGMTTzID(input);
      }
    } else if (memcmp(upper.c_str(), "GMT", 3) == 0) {
      if (upper == "GMT0" || upper == "GMT+0" || upper == "GMT-0") {
        return "UTC";
      }
    } else if (memcmp(upper.c_str(), "US/", 3) == 0) {
      std::string title = ToTitleCaseTimezoneLocation(input);
      if (title.length() >= 2) {
        // Change "Us/" to "US/"
        title[1] = 'S';
      }
      return title;
    } else if (strncmp(upper.c_str(), "SYSTEMV/", 8) == 0) {
      upper.replace(0, 8, "SystemV/");
      return upper;
    }
  }
  // We expect only _, '-' and / beside ASCII letters.
  static base::LazyInstance<SpecialTimeZoneMap>::type special_time_zone_map =
      LAZY_INSTANCE_INITIALIZER;
  std::string special_case = special_time_zone_map.Pointer()->Find(upper);
  if (!special_case.empty()) {
    return special_case;
  }
  return ToTitleCaseTimezoneLocation(input);
}
References v8::internal::anonymous_namespace{js-date-time-format.cc}::GetGMTTzID(), LAZY_INSTANCE_INITIALIZER, v8::internal::anonymous_namespace{js-date-time-format.cc}::LocaleIndependentAsciiToUpper(), v8::internal::string, and v8::internal::anonymous_namespace{js-date-time-format.cc}::ToTitleCaseTimezoneLocation().
Referenced by CreateTimeZone().
CreateDateTimeFormat()
MaybeDirectHandle< JSDateTimeFormat > v8::internal::JSDateTimeFormat::CreateDateTimeFormat (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options, RequiredOption required, DefaultsOption defaults, const char * service) [static]
Definition at line 1993 of file js-date-time-format.cc.
                                                  {
  Factory* factory = isolate->factory();
  // 1. Let requestedLocales be ? CanonicalizeLocaleList(locales).
  Maybe<std::vector<std::string>> maybe_requested_locales =
      Intl::CanonicalizeLocaleList(isolate, locales);
  MAYBE_RETURN(maybe_requested_locales, {});
  std::vector<std::string> requested_locales =
      maybe_requested_locales.FromJust();
  // 2. Let options be ? CoerceOptionsToObject(_options_).
  DirectHandle<JSReceiver> options;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, options, CoerceOptionsToObject(isolate, input_options, service));
  // 4. Let matcher be ? GetOption(options, "localeMatcher", "string",
  // « "lookup", "best fit" », "best fit").
  // 5. Set opt.[[localeMatcher]] to matcher.
  Maybe<Intl::MatcherOption> maybe_locale_matcher =
      Intl::GetLocaleMatcher(isolate, options, service);
  MAYBE_RETURN(maybe_locale_matcher, {});
  Intl::MatcherOption locale_matcher = maybe_locale_matcher.FromJust();
  DirectHandle<String> calendar_str;
  std::string numbering_system_str;
  // 6. Let calendar be ? GetOption(options, "calendar",
  // "string", undefined, undefined).
  Maybe<bool> maybe_calendar =
      GetStringOption(isolate, options, "calendar",
                      std::span<std::string_view>(), service, &calendar_str);
  MAYBE_RETURN(maybe_calendar, {});
  // Unfortunately needs to be a std::string because of Intl::IsValidCalendar
  std::string calendar_stdstr;
  if (maybe_calendar.FromJust()) {
    calendar_stdstr = calendar_str->ToStdString();
    icu::Locale default_locale;
    if (!Intl::IsWellFormedCalendar(calendar_stdstr)) {
      THROW_NEW_ERROR(isolate,
                      NewRangeError(MessageTemplate::kInvalid,
                                    factory->calendar_string(), calendar_str));
    }
  }
  // 8. Let numberingSystem be ? GetOption(options, "numberingSystem",
  // "string", undefined, undefined).
  Maybe<bool> maybe_numberingSystem =
      Intl::GetNumberingSystem(isolate, options, service, numbering_system_str);
  MAYBE_RETURN(maybe_numberingSystem, {});
  // 6. Let hour12 be ? GetOption(options, "hour12", "boolean", undefined,
  // undefined).
  bool hour12;
  Maybe<bool> maybe_get_hour12 =
      GetBoolOption(isolate, options, "hour12", service, &hour12);
  MAYBE_RETURN(maybe_get_hour12, {});
  // 7. Let hourCycle be ? GetOption(options, "hourCycle", "string", « "h11",
  // "h12", "h23", "h24" », undefined).
  Maybe<HourCycle> maybe_hour_cycle = GetHourCycle(isolate, options, service);
  MAYBE_RETURN(maybe_hour_cycle, {});
  HourCycle hour_cycle = maybe_hour_cycle.FromJust();
  // 8. If hour12 is not undefined, then
  if (maybe_get_hour12.FromJust()) {
    // a. Let hourCycle be null.
    hour_cycle = HourCycle::kUndefined;
  }
  // 9. Set opt.[[hc]] to hourCycle.
  // ecma402/#sec-intl.datetimeformat-internal-slots
  // The value of the [[RelevantExtensionKeys]] internal slot is
  // « "ca", "nu", "hc" ».
  // 10. Let localeData be %DateTimeFormat%.[[LocaleData]].
  // 11. Let r be ResolveLocale(%DateTimeFormat%.[[AvailableLocales]],
  // requestedLocales, opt, %DateTimeFormat%.[[RelevantExtensionKeys]],
  // localeData).
  //
  Intl::ResolvedLocale r;
  if (!Intl::ResolveLocale(isolate, JSDateTimeFormat::GetAvailableLocales(),
                           requested_locales, locale_matcher,
                           {"nu", "ca", "hc"})
           .To(&r)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  icu::Locale icu_locale = r.icu_locale;
  DCHECK(!icu_locale.isBogus());
  UErrorCode status = U_ZERO_ERROR;
  if (maybe_calendar.FromJust()) {
    auto ca_extension_it = r.extensions.find("ca");
    if (ca_extension_it != r.extensions.end() &&
        ca_extension_it->second != calendar_stdstr) {
      icu_locale.setUnicodeKeywordValue("ca", nullptr, status);
      DCHECK(U_SUCCESS(status));
    }
  }
  if (maybe_numberingSystem.FromJust()) {
    auto nu_extension_it = r.extensions.find("nu");
    if (nu_extension_it != r.extensions.end() &&
        nu_extension_it->second != numbering_system_str) {
      icu_locale.setUnicodeKeywordValue("nu", nullptr, status);
      DCHECK(U_SUCCESS(status));
    }
  }
  // Need to keep a copy of icu_locale which not changing "ca", "nu", "hc"
  // by option.
  icu::Locale resolved_locale(icu_locale);
  if (maybe_calendar.FromJust() &&
      Intl::IsValidCalendar(icu_locale, calendar_stdstr)) {
    icu_locale.setUnicodeKeywordValue("ca", calendar_stdstr, status);
    DCHECK(U_SUCCESS(status));
  }
  if (maybe_numberingSystem.FromJust() &&
      Intl::IsValidNumberingSystem(numbering_system_str)) {
    icu_locale.setUnicodeKeywordValue("nu", numbering_system_str, status);
    DCHECK(U_SUCCESS(status));
  }
  static base::LazyInstance<DateTimePatternGeneratorCache>::type
      generator_cache = LAZY_INSTANCE_INITIALIZER;
  std::unique_ptr<icu::DateTimePatternGenerator> generator(
      generator_cache.Pointer()->CreateGenerator(isolate, icu_locale));
  // 15.Let hcDefault be dataLocaleData.[[hourCycle]].
  HourCycle hc_default = ToHourCycle(generator->getDefaultHourCycle(status));
  DCHECK(U_SUCCESS(status));
  // 16.Let hc be r.[[hc]].
  HourCycle hc = HourCycle::kUndefined;
  if (hour_cycle == HourCycle::kUndefined) {
    auto hc_extension_it = r.extensions.find("hc");
    if (hc_extension_it != r.extensions.end()) {
      hc = ToHourCycle(hc_extension_it->second);
    }
  } else {
    hc = hour_cycle;
  }
  // 25. If hour12 is true, then
  if (maybe_get_hour12.FromJust()) {
    if (hour12) {
      // a. Let hc be dataLocaleData.[[hourCycle12]].
      hc = DefaultHourCycle12(icu_locale, hc_default);
      // 26. Else if hour12 is false, then
    } else {
      // a. Let hc be dataLocaleData.[[hourCycle24]].
      hc = DefaultHourCycle24(icu_locale, hc_default);
    }
  } else {
    // 27. Else,
    // a. Assert: hour12 is undefined.
    // b. Let hc be r.[[hc]].
    // c. If hc is null, set hc to dataLocaleData.[[hourCycle]].
    if (hc == HourCycle::kUndefined) {
      hc = hc_default;
    }
  }
  // 17. Let timeZone be ? Get(options, "timeZone").
  DirectHandle<Object> time_zone_obj;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, time_zone_obj,
      Object::GetPropertyOrElement(isolate, options,
                                   isolate->factory()->timeZone_string()));
  std::unique_ptr<icu::TimeZone> tz;
  if (!IsUndefined(*time_zone_obj, isolate)) {
    DirectHandle<String> time_zone;
    ASSIGN_RETURN_ON_EXCEPTION(isolate, time_zone,
                               Object::ToString(isolate, time_zone_obj));
    tz = JSDateTimeFormat::CreateTimeZone(isolate, time_zone);
  } else {
    // 19.a. Else / Let timeZone be DefaultTimeZone().
    tz.reset(icu::TimeZone::createDefault());
  }
  if (tz.get() == nullptr) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kInvalidTimeZone,
                                           time_zone_obj));
  }
  std::unique_ptr<icu::Calendar> calendar(
      CreateCalendar(isolate, icu_locale, tz.release()));
  // 18.b If the result of IsValidTimeZoneName(timeZone) is false, then
  // i. Throw a RangeError exception.
  if (calendar.get() == nullptr) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kInvalidTimeZone,
                                           time_zone_obj));
  }
  DateTimeStyle date_style = DateTimeStyle::kUndefined;
  DateTimeStyle time_style = DateTimeStyle::kUndefined;
  std::unique_ptr<icu::SimpleDateFormat> icu_date_format;
  // 35. Let hasExplicitFormatComponents be false.
  int32_t explicit_format_components =
      0; // The fields which are not undefined.
  // 36. For each row of Table 1, except the header row, do
  bool has_hour_option = false;
  std::string skeleton;
  for (const PatternData& item : GetPatternData(hc)) {
    // Need to read fractionalSecondDigits before reading the timeZoneName
    if (item.property == "timeZoneName") {
      // Let _value_ be ? GetNumberOption(options, "fractionalSecondDigits", 1,
      // 3, *undefined*). The *undefined* is represented by value 0 here.
      int fsd;
      MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
          isolate, fsd,
          GetNumberOption(isolate, options,
                          factory->fractionalSecondDigits_string(), 1, 3, 0),
          {});
      if (fsd > 0) {
        explicit_format_components =
            FractionalSecondDigits::update(explicit_format_components, true);
      }
      // Convert fractionalSecondDigits to skeleton.
      for (int i = 0; i < fsd; i++) {
        skeleton += "S";
      }
    }
    DirectHandle<String> input;
    // i. Let prop be the name given in the Property column of the row.
    // ii. Let value be ? GetOption(options, prop, "string", « the strings
    // given in the Values column of the row », undefined).
    Maybe<bool> maybe_get_option =
        GetStringOption(isolate, options, item.property.c_str(),
                        item.allowed_values, service, &input);
    MAYBE_RETURN(maybe_get_option, {});
    if (maybe_get_option.FromJust()) {
      std::string input_str = input->ToStdString();
      // Record which fields are not undefined into explicit_format_components.
      if (item.property == "hour") {
        has_hour_option = true;
      }
      // iii. Set opt.[[<prop>]] to value.
      skeleton += item.map.find(input_str)->second;
      // e. If value is not undefined, then
      // i. Set hasExplicitFormatComponents to true.
      explicit_format_components |= 1 << static_cast<int32_t>(item.bitShift);
    }
  }
  // 29. Let matcher be ? GetOption(options, "formatMatcher", "string", «
  // "basic", "best fit" », "best fit").
  // We implement only best fit algorithm, but still need to check
  // if the formatMatcher values are in range.
  // c. Let matcher be ? GetOption(options, "formatMatcher", "string",
  // « "basic", "best fit" », "best fit").
  Maybe<FormatMatcherOption> maybe_format_matcher =
      GetStringOption<FormatMatcherOption>(
          isolate, options, "formatMatcher", service,
          std::to_array<const std::string_view>({"best fit", "basic"}),
          std::array{FormatMatcherOption::kBestFit,
                     FormatMatcherOption::kBasic},
          FormatMatcherOption::kBestFit);
  MAYBE_RETURN(maybe_format_matcher, {});
  // TODO(ftang): uncomment the following line and handle format_matcher.
  // FormatMatcherOption format_matcher = maybe_format_matcher.FromJust();
  // 32. Let dateStyle be ? GetOption(options, "dateStyle", "string", «
  // "full", "long", "medium", "short" », undefined).
  Maybe<DateTimeStyle> maybe_date_style = GetStringOption<DateTimeStyle>(
      isolate, options, "dateStyle", service,
      std::to_array<const std::string_view>(
          {"full", "long", "medium", "short"}),
      std::array{DateTimeStyle::kFull, DateTimeStyle::kLong,
                 DateTimeStyle::kMedium, DateTimeStyle::kShort},
      DateTimeStyle::kUndefined);
  MAYBE_RETURN(maybe_date_style, {});
  // 33. Set dateTimeFormat.[[DateStyle]] to dateStyle.
  date_style = maybe_date_style.FromJust();
  // 34. Let timeStyle be ? GetOption(options, "timeStyle", "string", «
  // "full", "long", "medium", "short" »).
  Maybe<DateTimeStyle> maybe_time_style = GetStringOption<DateTimeStyle>(
      isolate, options, "timeStyle", service,
      std::to_array<const std::string_view>(
          {"full", "long", "medium", "short"}),
      std::array{DateTimeStyle::kFull, DateTimeStyle::kLong,
                 DateTimeStyle::kMedium, DateTimeStyle::kShort},
      DateTimeStyle::kUndefined);
  MAYBE_RETURN(maybe_time_style, {});
  // 35. Set dateTimeFormat.[[TimeStyle]] to timeStyle.
  time_style = maybe_time_style.FromJust();
  // 36. If timeStyle is not undefined, then
  HourCycle dateTimeFormatHourCycle = HourCycle::kUndefined;
  if (time_style != DateTimeStyle::kUndefined) {
    // a. Set dateTimeFormat.[[HourCycle]] to hc.
    dateTimeFormatHourCycle = hc;
  }
  // 37. If dateStyle or timeStyle are not undefined, then
  if (date_style != DateTimeStyle::kUndefined ||
      time_style != DateTimeStyle::kUndefined) {
    // a. If hasExplicitFormatComponents is true, then
    if (explicit_format_components != 0) {
      // i. Throw a TypeError exception.
      THROW_NEW_ERROR(
          isolate, NewTypeError(MessageTemplate::kInvalid,
                                factory->NewStringFromStaticChars("option"),
                                factory->NewStringFromStaticChars("option")));
    }
    // b. If required is ~date~ and timeStyle is not *undefined*, then
    if (required == RequiredOption::kDate &&
        time_style != DateTimeStyle::kUndefined) {
      // i. Throw a *TypeError* exception.
      THROW_NEW_ERROR(isolate,
                      NewTypeError(MessageTemplate::kInvalid,
                                   factory->NewStringFromStaticChars("option"),
                                   factory->timeStyle_string()));
    }
    // c. If required is ~time~ and dateStyle is not *undefined*, then
    if (required == RequiredOption::kTime &&
        date_style != DateTimeStyle::kUndefined) {
      // i. Throw a *TypeError* exception.
      THROW_NEW_ERROR(isolate,
                      NewTypeError(MessageTemplate::kInvalid,
                                   factory->NewStringFromStaticChars("option"),
                                   factory->dateStyle_string()));
    }
    // b. Let pattern be DateTimeStylePattern(dateStyle, timeStyle,
    // dataLocaleData, hc).
    isolate->CountUsage(
        v8::Isolate::UseCounterFeature::kDateTimeFormatDateTimeStyle);
    icu_date_format =
        DateTimeStylePattern(date_style, time_style, icu_locale,
                             dateTimeFormatHourCycle, generator.get());
    if (icu_date_format.get() == nullptr) {
      THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
    }
  } else {
    // a. Let needDefaults be *true*.
    bool needDefaults = true;
    // b. If required is ~date~ or ~any~, then
    if (required == RequiredOption::kDate || required == RequiredOption::kAny) {
      // 1. For each property name prop of << *"weekday"*, *"year"*, *"month"*,
      // *"day"* >>, do
      // 1. Let value be formatOptions.[[<prop>]].
      // 1. If value is not *undefined*, let needDefaults be *false*.
      needDefaults &= !Weekday::decode(explicit_format_components);
      needDefaults &= !Year::decode(explicit_format_components);
      needDefaults &= !Month::decode(explicit_format_components);
      needDefaults &= !Day::decode(explicit_format_components);
    }
    // c. If required is ~time~ or ~any~, then
    if (required == RequiredOption::kTime || required == RequiredOption::kAny) {
      // 1. For each property name prop of &laquo; *"dayPeriod"*, *"hour"*,
      // *"minute"*, *"second"*, *"fractionalSecondDigits"* &raquo;, do
      // 1. Let value be formatOptions.[[&lt;_prop_&gt;]].
      // 1. If value is not *undefined*, let _needDefaults_ be *false*.
      needDefaults &= !DayPeriod::decode(explicit_format_components);
      needDefaults &= !Hour::decode(explicit_format_components);
      needDefaults &= !Minute::decode(explicit_format_components);
      needDefaults &= !Second::decode(explicit_format_components);
      needDefaults &=
          !FractionalSecondDigits::decode(explicit_format_components);
    }
    // 1. If needDefaults is *true* and _defaults_ is either ~date~ or ~all~,
    // then
    if (needDefaults && ((DefaultsOption::kDate == defaults) ||
                         (DefaultsOption::kAll == defaults))) {
      // 1. For each property name prop of <<*"year"*, *"month"*, *"day"* >>, do
      // 1. Set formatOptions.[[<<prop>>]] to *"numeric"*.
      skeleton += "yMd";
    }
    // 1. If _needDefaults_ is *true* and defaults is either ~time~ or ~all~,
    // then
    if (needDefaults && ((DefaultsOption::kTime == defaults) ||
                         (DefaultsOption::kAll == defaults))) {
      // 1. For each property name prop of << *"hour"*, *"minute"*, *"second"*
      // >>, do
      // 1. Set _formatOptions_.[[<<prop>>]] to *"numeric"*.
      // See
      // https://unicode.org/reports/tr35/tr35.html#UnicodeHourCycleIdentifier
      switch (hc) {
        case HourCycle::kH12:
          skeleton += "hms";
          break;
        case HourCycle::kH23:
        case HourCycle::kUndefined:
          skeleton += "Hms";
          break;
        case HourCycle::kH11:
          skeleton += "Kms";
          break;
        case HourCycle::kH24:
          skeleton += "kms";
          break;
      }
    }
    // e. If dateTimeFormat.[[Hour]] is not undefined, then
    if (has_hour_option) {
      // v. Set dateTimeFormat.[[HourCycle]] to hc.
      dateTimeFormatHourCycle = hc;
    } else {
      // f. Else,
      // Set dateTimeFormat.[[HourCycle]] to undefined.
      dateTimeFormatHourCycle = HourCycle::kUndefined;
    }
    icu::UnicodeString skeleton_ustr(skeleton.c_str());
    icu_date_format = CreateICUDateFormatFromCache(
        icu_locale, skeleton_ustr, generator.get(), dateTimeFormatHourCycle);
    if (icu_date_format.get() == nullptr) {
      // Remove extensions and try again.
      icu_locale = icu::Locale(icu_locale.getBaseName());
      icu_date_format = CreateICUDateFormatFromCache(
          icu_locale, skeleton_ustr, generator.get(), dateTimeFormatHourCycle);
      if (icu_date_format.get() == nullptr) {
        THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
      }
    }
  }
  // The creation of Calendar depends on timeZone so we have to put 13 after 17.
  // Also icu_date_format is not created until here.
  // 13. Set dateTimeFormat.[[Calendar]] to r.[[ca]].
  icu_date_format->adoptCalendar(calendar.release());
  // 12.1.1 InitializeDateTimeFormat (dateTimeFormat, locales, options)
  //
  // Steps 8-9 set opt.[[hc]] to value *other than undefined*
  // if "hour12" is set or "hourCycle" is set in the option.
  //
  // 9.2.6 ResolveLocale (...)
  // Step 8.h / 8.i and 8.k
  //
  // An hour12 option always overrides an hourCycle option.
  // Additionally hour12 and hourCycle both clear out any existing Unicode
  // extension key in the input locale.
  //
  // See details in https://github.com/tc39/test262/pull/2035
  if (maybe_get_hour12.FromJust() ||
      maybe_hour_cycle.FromJust() != HourCycle::kUndefined) {
    auto hc_extension_it = r.extensions.find("hc");
    if (hc_extension_it != r.extensions.end()) {
      if (dateTimeFormatHourCycle !=
          ToHourCycle(hc_extension_it->second.c_str())) {
        // Remove -hc- if it does not agree with what we used.
        status = U_ZERO_ERROR;
        resolved_locale.setUnicodeKeywordValue("hc", nullptr, status);
        DCHECK(U_SUCCESS(status));
      }
    }
  }
  Maybe<std::string> maybe_locale_str = Intl::ToLanguageTag(resolved_locale);
  MAYBE_RETURN(maybe_locale_str, {});
  DirectHandle<String> locale_str =
      isolate->factory()->NewStringFromAsciiChecked(
          maybe_locale_str.FromJust().c_str());
  DirectHandle<Managed<icu::Locale>> managed_locale =
      Managed<icu::Locale>::From(
          isolate, 0, std::shared_ptr<icu::Locale>{icu_locale.clone()});
  DirectHandle<Managed<icu::SimpleDateFormat>> managed_format =
      Managed<icu::SimpleDateFormat>::From(isolate, 0,
                                           std::move(icu_date_format));
  DirectHandle<Managed<icu::DateIntervalFormat>> managed_interval_format =
      Managed<icu::DateIntervalFormat>::From(isolate, 0, nullptr);
  // Now all properties are ready, so we can allocate the result object.
  DirectHandle<JSDateTimeFormat> date_time_format = Cast<JSDateTimeFormat>(
      isolate->factory()->NewFastOrSlowJSObjectFromMap(map));
  DisallowGarbageCollection no_gc;
  date_time_format->set_flags(0);
  if (date_style != DateTimeStyle::kUndefined) {
    date_time_format->set_date_style(date_style);
  }
  if (time_style != DateTimeStyle::kUndefined) {
    date_time_format->set_time_style(time_style);
  }
  date_time_format->set_hour_cycle(dateTimeFormatHourCycle);
  date_time_format->set_locale(*locale_str);
  date_time_format->set_icu_locale(*managed_locale);
  date_time_format->set_icu_simple_date_format(*managed_format);
  date_time_format->set_icu_date_interval_format(*managed_interval_format);
  return date_time_format;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Intl::CanonicalizeLocaleList(), v8::internal::CoerceOptionsToObject(), v8::internal::Isolate::CountUsage(), v8::internal::anonymous_namespace{js-date-time-format.cc}::CreateCalendar(), v8::internal::anonymous_namespace{js-date-time-format.cc}::CreateICUDateFormatFromCache(), CreateTimeZone(), date_style(), v8::internal::anonymous_namespace{js-date-time-format.cc}::DateTimeStylePattern(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{js-date-time-format.cc}::DefaultHourCycle12(), v8::internal::anonymous_namespace{js-date-time-format.cc}::DefaultHourCycle24(), v8::internal::Intl::ResolvedLocale::extensions, v8::internal::Isolate::factory(), v8::internal::Managed< CppType >::From(), v8::Maybe< T >::FromJust(), GetAvailableLocales(), v8::internal::GetBoolOption(), v8::internal::anonymous_namespace{js-date-time-format.cc}::GetHourCycle(), v8::internal::Intl::GetLocaleMatcher(), v8::internal::Intl::GetNumberingSystem(), v8::internal::GetNumberOption(), v8::internal::anonymous_namespace{js-date-time-format.cc}::GetPatternData(), v8::internal::Object::GetPropertyOrElement(), v8::internal::GetStringOption(), hour_cycle(), v8::internal::Intl::ResolvedLocale::icu_locale, v8::internal::Intl::IsValidCalendar(), v8::internal::Intl::IsValidNumberingSystem(), v8::internal::Intl::IsWellFormedCalendar(), kAll, kAny, v8::internal::kBasic, v8::internal::kBestFit, kDate, kFull, kH11, kH12, kH23, kH24, v8::internal::anonymous_namespace{isolate.cc}::kInvalid, kLong, kMedium, kShort, kTime, kUndefined, LAZY_INSTANCE_INITIALIZER, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, MAYBE_RETURN, v8::internal::Factory::NewFastOrSlowJSObjectFromMap(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::Factory::NewStringFromStaticChars(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Intl::ResolveLocale(), v8::internal::status, v8::internal::string, THROW_NEW_ERROR, time_style(), v8::internal::anonymous_namespace{js-date-time-format.cc}::ToHourCycle(), v8::internal::Intl::ToLanguageTag(), and v8::Value::ToString().
Referenced by New(), and ToLocaleDateTime().
CreateTimeZone()
std::unique_ptr< icu::TimeZone > v8::internal::JSDateTimeFormat::CreateTimeZone (Isolate * isolate, DirectHandle< String > time_zone) [static]
Definition at line 1524 of file js-date-time-format.cc.
                                                             {
  // Create time zone as specified by the user. We have to re-create time zone
  // since calendar takes ownership.
  std::optional<std::string> offsetTimeZone =
      GetOffsetTimeZone(isolate, time_zone_string);
  if (offsetTimeZone.has_value()) {
    std::unique_ptr<icu::TimeZone> tz(
        icu::TimeZone::createTimeZone(offsetTimeZone->c_str()));
    return tz;
  }
  std::string time_zone = time_zone_string->ToStdString();
  std::string canonicalized = CanonicalizeTimeZoneID(time_zone);
  if (canonicalized.empty()) return std::unique_ptr<icu::TimeZone>();
  std::unique_ptr<icu::TimeZone> tz(
      icu::TimeZone::createTimeZone(canonicalized.c_str()));
  // 18.b If the result of IsValidTimeZoneName(timeZone) is false, then
  // i. Throw a RangeError exception.
  if (!Intl::IsValidTimeZoneName(*tz)) return std::unique_ptr<icu::TimeZone>();
  return tz;
}
References CanonicalizeTimeZoneID(), v8::internal::GetOffsetTimeZone(), v8::internal::Intl::IsValidTimeZoneName(), and v8::internal::string.
Referenced by CreateDateTimeFormat().
date_style()
JSDateTimeFormat::DateTimeStyle v8::internal::JSDateTimeFormat::date_style () const [inline]
Definition at line 52 of file js-date-time-format-inl.h.
                                                                        {
  return DateStyleBits::decode(flags());
}
References v8::internal::flags.
Referenced by CreateDateTimeFormat(), and set_date_style().
DateTimeFormat()
MaybeDirectHandle< String > v8::internal::JSDateTimeFormat::DateTimeFormat (Isolate * isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > date, const char * method_name) [static]
Definition at line 1309 of file js-date-time-format.cc.
                                                        {
  // 2. Assert: Type(dtf) is Object and dtf has an [[InitializedDateTimeFormat]]
  // internal slot.
  if (v8_flags.harmony_temporal) {
    return FormatDateTimeWithTemporalSupport(isolate, date_time_format, date,
                                             method_name);
  }
  // 3. If date is not provided or is undefined, then
  double x;
  if (IsUndefined(*date)) {
    // 3.a Let x be Call(%Date_now%, undefined).
    x = static_cast<double>(JSDate::CurrentTimeValue(isolate));
  } else {
    // 4. Else,
    // a. Let x be ? ToNumber(date).
    ASSIGN_RETURN_ON_EXCEPTION(isolate, date, Object::ToNumber(isolate, date));
    DCHECK(IsNumber(*date));
    x = Object::NumberValue(*date);
  }
  // 5. Return FormatDateTime(dtf, x).
  icu::SimpleDateFormat* format =
      date_time_format->icu_simple_date_format()->raw();
  return FormatDateTime(isolate, *format, x);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::JSDate::CurrentTimeValue(), v8::internal::date, v8::internal::DCHECK(), v8::internal::format, v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatDateTime(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatDateTimeWithTemporalSupport(), v8::internal::IsNumber(), v8::internal::Object::NumberValue(), v8::Value::ToNumber(), and v8::internal::v8_flags.
Referenced by v8::internal::BUILTIN().
FormatRange()
MaybeDirectHandle< String > v8::internal::JSDateTimeFormat::FormatRange (Isolate * isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > x_date_value, DirectHandle< Object > y_date_value, const char * method_name) [static]
Definition at line 2964 of file js-date-time-format.cc.
                                                                             {
  // Track newer feature formatRange and formatRangeToParts.
  isolate->CountUsage(v8::Isolate::UseCounterFeature::kDateTimeFormatRange);
  if (v8_flags.harmony_temporal) {
    // For Temporal enable support.
    return FormatRangeCommonWithTemporalSupport<
        String, FormattedToString, FormatMillisecondsByKindToString>(
        isolate, date_time_format, x, y, method_name);
  }
  // Pre Temporal implementation.
  return FormatRangeCommon<String, FormattedToString, FormatDateTime>(
      isolate, date_time_format, x, y, method_name);
}
References v8::internal::Isolate::CountUsage(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatMillisecondsByKindToString(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatRangeCommonWithTemporalSupport(), v8::internal::FormattedToString(), v8::internal::v8_flags, and v8::internal::y.
FormatRangeToParts()
MaybeDirectHandle< JSArray > v8::internal::JSDateTimeFormat::FormatRangeToParts (Isolate * isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > x_date_value, DirectHandle< Object > y_date_value, const char * method_name) [static]
Definition at line 2980 of file js-date-time-format.cc.
                                                                             {
  // Track newer feature formatRange and formatRangeToParts.
  isolate->CountUsage(v8::Isolate::UseCounterFeature::kDateTimeFormatRange);
  if (v8_flags.harmony_temporal) {
    // For Temporal enable support.
    return FormatRangeCommonWithTemporalSupport<
        JSArray, FormattedDateIntervalToJSArray,
        FormatMillisecondsByKindToArrayOutputSource>(isolate, date_time_format,
                                                     x, y, method_name);
  }
  // Pre Temporal implementation.
  return FormatRangeCommon<JSArray, FormattedDateIntervalToJSArray,
                           FormatMillisecondsToArrayOutputSource>(
      isolate, date_time_format, x, y, method_name);
}
References v8::internal::Isolate::CountUsage(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatMillisecondsByKindToArrayOutputSource(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatMillisecondsToArrayOutputSource(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatRangeCommon(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatRangeCommonWithTemporalSupport(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormattedDateIntervalToJSArray(), v8::internal::v8_flags, and v8::internal::y.
FormatToParts()
MaybeDirectHandle< JSArray > v8::internal::JSDateTimeFormat::FormatToParts (Isolate * isolate, DirectHandle< JSDateTimeFormat > date_time_format, DirectHandle< Object > x, bool output_source, const char * method_name) [static]
Definition at line 2611 of file js-date-time-format.cc.
                                                                         {
  Factory* factory = isolate->factory();
  if (v8_flags.harmony_temporal) {
    return FormatToPartsWithTemporalSupport(isolate, date_time_format, x,
                                            output_source, method_name);
  }
  if (IsUndefined(*x, isolate)) {
    x = factory->NewNumberFromInt64(JSDate::CurrentTimeValue(isolate));
  } else {
    ASSIGN_RETURN_ON_EXCEPTION(isolate, x, Object::ToNumber(isolate, x));
  }
  double date_value = Object::NumberValue(*x);
  if (!DateCache::TryTimeClip(&date_value)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kInvalidTimeValue));
  }
  return FormatMillisecondsToArray(
      isolate, *(date_time_format->icu_simple_date_format()->raw()), date_value,
      output_source);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::JSDate::CurrentTimeValue(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatMillisecondsToArray(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatToPartsWithTemporalSupport(), v8::internal::FactoryBase< Impl >::NewNumberFromInt64(), v8::internal::Object::NumberValue(), THROW_NEW_ERROR, v8::Value::ToNumber(), v8::internal::DateCache::TryTimeClip(), and v8::internal::v8_flags.
Referenced by v8::internal::BUILTIN().
GetAvailableLocales()
const std::set< std::string > & v8::internal::JSDateTimeFormat::GetAvailableLocales () [static]
Definition at line 2703 of file js-date-time-format.cc.
                                                               {
  return Intl::GetAvailableLocalesForDateFormat();
}
References v8::internal::Intl::GetAvailableLocalesForDateFormat().
Referenced by v8::internal::BUILTIN(), and CreateDateTimeFormat().
hour_cycle()
JSDateTimeFormat::HourCycle v8::internal::JSDateTimeFormat::hour_cycle () const [inline]
Definition at line 41 of file js-date-time-format-inl.h.
                                                                    {
  return HourCycleBits::decode(flags());
}
References v8::internal::flags.
Referenced by CreateDateTimeFormat(), and HourCycleAsString().
HourCycleAsString()
Handle< String > v8::internal::JSDateTimeFormat::HourCycleAsString (Isolate * isolate) const
Definition at line 2707 of file js-date-time-format.cc.
                                                                         {
  switch (hour_cycle()) {
    case HourCycle::kUndefined:
      return isolate->factory()->undefined_string();
    case HourCycle::kH11:
      return isolate->factory()->h11_string();
    case HourCycle::kH12:
      return isolate->factory()->h12_string();
    case HourCycle::kH23:
      return isolate->factory()->h23_string();
    case HourCycle::kH24:
      return isolate->factory()->h24_string();
    default:
      UNREACHABLE();
  }
}
References v8::internal::Isolate::factory(), hour_cycle(), kH11, kH12, kH23, kH24, kUndefined, and v8::internal::UNREACHABLE().
New()
MaybeDirectHandle< JSDateTimeFormat > v8::internal::JSDateTimeFormat::New (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options, const char * service) [static]
Definition at line 1985 of file js-date-time-format.cc.
                                                             {
  return JSDateTimeFormat::CreateDateTimeFormat(
      isolate, map, locales, input_options, RequiredOption::kAny,
      DefaultsOption::kDate, service);
}
References CreateDateTimeFormat(), kAny, and kDate.
Referenced by TemporalToLocaleString().
ResolvedOptions()
MaybeDirectHandle< JSObject > v8::internal::JSDateTimeFormat::ResolvedOptions (Isolate * isolate, DirectHandle< JSDateTimeFormat > date_time_format) [static]
Definition at line 645 of file js-date-time-format.cc.
                                                                       {
  Factory* factory = isolate->factory();
  // 4. Let options be ! ObjectCreate(%ObjectPrototype%).
  DirectHandle<JSObject> options =
      factory->NewJSObject(isolate->object_function());
  DirectHandle<Object> resolved_obj;
  DirectHandle<String> locale(date_time_format->locale(), isolate);
  DCHECK(!date_time_format->icu_locale().is_null());
  DCHECK_NOT_NULL(date_time_format->icu_locale()->raw());
  icu::Locale* icu_locale = date_time_format->icu_locale()->raw();
  icu::SimpleDateFormat* icu_simple_date_format =
      date_time_format->icu_simple_date_format()->raw();
  DirectHandle<Object> timezone =
      JSDateTimeFormat::TimeZone(isolate, date_time_format);
  // Ugly hack. ICU doesn't expose numbering system in any way, so we have
  // to assume that for given locale NumberingSystem constructor produces the
  // same digits as NumberFormat/Calendar would.
  // Tracked by https://unicode-org.atlassian.net/browse/ICU-13431
  std::string numbering_system = Intl::GetNumberingSystem(*icu_locale);
  icu::UnicodeString pattern_unicode;
  icu_simple_date_format->toPattern(pattern_unicode);
  std::string pattern;
  pattern_unicode.toUTF8String(pattern);
  // 5. For each row of Table 6, except the header row, in table order, do
  // Table 6: Resolved Options of DateTimeFormat Instances
  // Internal Slot Property
  // [[Locale]] "locale"
  // [[Calendar]] "calendar"
  // [[NumberingSystem]] "numberingSystem"
  // [[TimeZone]] "timeZone"
  // [[HourCycle]] "hourCycle"
  // "hour12"
  // [[Weekday]] "weekday"
  // [[Era]] "era"
  // [[Year]] "year"
  // [[Month]] "month"
  // [[Day]] "day"
  // [[Hour]] "hour"
  // [[Minute]] "minute"
  // [[Second]] "second"
  // [[FractionalSecondDigits]] "fractionalSecondDigits"
  // [[TimeZoneName]] "timeZoneName"
  Maybe<bool> maybe_create_locale = JSReceiver::CreateDataProperty(
      isolate, options, factory->locale_string(), locale, Just(kDontThrow));
  DCHECK(maybe_create_locale.FromJust());
  USE(maybe_create_locale);
  DirectHandle<String> calendar =
      JSDateTimeFormat::Calendar(isolate, date_time_format);
  Maybe<bool> maybe_create_calendar = JSReceiver::CreateDataProperty(
      isolate, options, factory->calendar_string(), calendar, Just(kDontThrow));
  DCHECK(maybe_create_calendar.FromJust());
  USE(maybe_create_calendar);
  if (!numbering_system.empty()) {
    Maybe<bool> maybe_create_numbering_system = JSReceiver::CreateDataProperty(
        isolate, options, factory->numberingSystem_string(),
        factory->NewStringFromAsciiChecked(numbering_system.c_str()),
        Just(kDontThrow));
    DCHECK(maybe_create_numbering_system.FromJust());
    USE(maybe_create_numbering_system);
  }
  Maybe<bool> maybe_create_time_zone = JSReceiver::CreateDataProperty(
      isolate, options, factory->timeZone_string(), timezone, Just(kDontThrow));
  DCHECK(maybe_create_time_zone.FromJust());
  USE(maybe_create_time_zone);
  // 5.b.i. Let hc be dtf.[[HourCycle]].
  HourCycle hc = date_time_format->hour_cycle();
  if (hc != HourCycle::kUndefined) {
    Maybe<bool> maybe_create_hour_cycle = JSReceiver::CreateDataProperty(
        isolate, options, factory->hourCycle_string(),
        date_time_format->HourCycleAsString(isolate), Just(kDontThrow));
    DCHECK(maybe_create_hour_cycle.FromJust());
    USE(maybe_create_hour_cycle);
    switch (hc) {
      // ii. If hc is "h11" or "h12", let v be true.
      case HourCycle::kH11:
      case HourCycle::kH12: {
        Maybe<bool> maybe_create_hour12 = JSReceiver::CreateDataProperty(
            isolate, options, factory->hour12_string(), factory->true_value(),
            Just(kDontThrow));
        DCHECK(maybe_create_hour12.FromJust());
        USE(maybe_create_hour12);
      } break;
      // iii. Else if, hc is "h23" or "h24", let v be false.
      case HourCycle::kH23:
      case HourCycle::kH24: {
        Maybe<bool> maybe_create_hour12 = JSReceiver::CreateDataProperty(
            isolate, options, factory->hour12_string(), factory->false_value(),
            Just(kDontThrow));
        DCHECK(maybe_create_hour12.FromJust());
        USE(maybe_create_hour12);
      } break;
      // iv. Else, let v be undefined.
      case HourCycle::kUndefined:
        break;
    }
  }
  // If dateStyle and timeStyle are undefined, then internal slots
  // listed in "Table 1: Components of date and time formats" will be set
  // in Step 33.f.iii.1 of InitializeDateTimeFormat
  if (date_time_format->date_style() == DateTimeStyle::kUndefined &&
      date_time_format->time_style() == DateTimeStyle::kUndefined) {
    for (const auto& item : GetPatternItems()) {
      // fractionalSecondsDigits need to be added before timeZoneName
      if (item.property == "timeZoneName") {
        int fsd = FractionalSecondDigitsFromPattern(pattern);
        if (fsd > 0) {
          Maybe<bool> maybe_create_fractional_seconds_digits =
              JSReceiver::CreateDataProperty(
                  isolate, options, factory->fractionalSecondDigits_string(),
                  factory->NewNumberFromInt(fsd), Just(kDontThrow));
          DCHECK(maybe_create_fractional_seconds_digits.FromJust());
          USE(maybe_create_fractional_seconds_digits);
        }
      }
      for (const auto& pair : item.pairs) {
        if (pattern.find(pair.pattern) != std::string::npos) {
          Maybe<bool> maybe_create_property = JSReceiver::CreateDataProperty(
              isolate, options,
              factory->NewStringFromAsciiChecked(item.property.c_str()),
              factory->NewStringFromAsciiChecked(pair.value.c_str()),
              Just(kDontThrow));
          DCHECK(maybe_create_property.FromJust());
          USE(maybe_create_property);
          break;
        }
      }
    }
  }
  // dateStyle
  if (date_time_format->date_style() != DateTimeStyle::kUndefined) {
    Maybe<bool> maybe_create_date_style = JSReceiver::CreateDataProperty(
        isolate, options, factory->dateStyle_string(),
        DateTimeStyleAsString(isolate, date_time_format->date_style()),
        Just(kDontThrow));
    DCHECK(maybe_create_date_style.FromJust());
    USE(maybe_create_date_style);
  }
  // timeStyle
  if (date_time_format->time_style() != DateTimeStyle::kUndefined) {
    Maybe<bool> maybe_create_time_style = JSReceiver::CreateDataProperty(
        isolate, options, factory->timeStyle_string(),
        DateTimeStyleAsString(isolate, date_time_format->time_style()),
        Just(kDontThrow));
    DCHECK(maybe_create_time_style.FromJust());
    USE(maybe_create_time_style);
  }
  return options;
}
References Calendar(), v8::internal::JSReceiver::CreateDataProperty(), v8::internal::anonymous_namespace{js-date-time-format.cc}::DateTimeStyleAsString(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FractionalSecondDigitsFromPattern(), v8::Maybe< T >::FromJust(), v8::internal::Intl::GetNumberingSystem(), v8::internal::anonymous_namespace{js-date-time-format.cc}::GetPatternItems(), v8::internal::icu_simple_date_format, v8::internal::DirectHandle< T >::is_null(), v8::Just(), v8::internal::kDontThrow, kH11, kH12, kH23, kH24, kUndefined, v8::internal::Factory::NewJSObject(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::string, TimeZone(), and USE.
Referenced by v8::internal::BUILTIN().
set_date_style()
void v8::internal::JSDateTimeFormat::set_date_style (JSDateTimeFormat::DateTimeStyle date_style) [inline]
Definition at line 45 of file js-date-time-format-inl.h.
                                              {
  int hints = flags();
  hints = DateStyleBits::update(hints, date_style);
  set_flags(hints);
}
References date_style(), and v8::internal::flags.
set_hour_cycle()
void v8::internal::JSDateTimeFormat::set_hour_cycle (HourCycle hour_cycle) [inline]
set_time_style()
void v8::internal::JSDateTimeFormat::set_time_style (JSDateTimeFormat::DateTimeStyle time_style) [inline]
Definition at line 56 of file js-date-time-format-inl.h.
                                              {
  int hints = flags();
  hints = TimeStyleBits::update(hints, time_style);
  set_flags(hints);
}
References v8::internal::flags, and time_style().
TemporalToLocaleString()
MaybeDirectHandle< String > v8::internal::JSDateTimeFormat::TemporalToLocaleString (Isolate * isolate, DirectHandle< JSReceiver > temporal, DirectHandle< Object > locales, DirectHandle< Object > options, const char * method_name) [static]
Definition at line 1413 of file js-date-time-format.cc.
                                                           {
  // 4. Let dateFormat be ? Construct(%DateTimeFormat%, « locales, options »).
  DirectHandle<JSFunction> constructor(
      isolate->context()->native_context()->intl_date_time_format_function(),
      isolate);
  DirectHandle<Map> map =
      JSFunction::GetDerivedMap(isolate, constructor, constructor)
          .ToHandleChecked();
  DirectHandle<JSDateTimeFormat> date_time_format;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, date_time_format,
      JSDateTimeFormat::New(isolate, map, locales, options, method_name));
  // 5. Return FormatDateTime(dateFormat, x).
  return FormatDateTimeWithTemporalSupport(isolate, date_time_format, x,
                                           method_name);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::context(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatDateTimeWithTemporalSupport(), v8::internal::JSFunction::GetDerivedMap(), and New().
time_style()
JSDateTimeFormat::DateTimeStyle v8::internal::JSDateTimeFormat::time_style () const [inline]
Definition at line 63 of file js-date-time-format-inl.h.
                                                                        {
  return TimeStyleBits::decode(flags());
}
References v8::internal::flags.
Referenced by CreateDateTimeFormat(), and set_time_style().
TimeZone()
DirectHandle< Object > v8::internal::JSDateTimeFormat::TimeZone (Isolate * isolate, DirectHandle< JSDateTimeFormat > date_time_format) [static]
Definition at line 638 of file js-date-time-format.cc.
                                                                       {
  return GetTimeZone(isolate,
                     *(date_time_format->icu_simple_date_format()->raw()));
}
References v8::internal::anonymous_namespace{js-date-time-format.cc}::GetTimeZone().
Referenced by ResolvedOptions().
TimeZoneId()
DirectHandle< Object > v8::internal::JSDateTimeFormat::TimeZoneId (Isolate * isolate, const icu::TimeZone & tz) [static]
Definition at line 581 of file js-date-time-format.cc.
                                                                         {
  Factory* factory = isolate->factory();
  icu::UnicodeString time_zone;
  tz.getID(time_zone);
  icu::UnicodeString canonical_time_zone;
  if (time_zone == u"GMT") {
    canonical_time_zone = u"+00:00";
  } else {
    UErrorCode status = U_ZERO_ERROR;
    icu::TimeZone::getCanonicalID(time_zone, canonical_time_zone, status);
    if (U_FAILURE(status)) {
      // When the time_zone is neither a known system time zone ID nor a
      // valid custom time zone ID, the status is a failure.
      return factory->undefined_value();
    }
  }
  DirectHandle<String> timezone_value;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, timezone_value, TimeZoneIdToString(isolate, canonical_time_zone),
      {});
  return timezone_value;
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Isolate::factory(), v8::internal::status, and TimeZoneIdToString().
Referenced by v8::internal::anonymous_namespace{js-date-time-format.cc}::GetTimeZone().
TimeZoneIdToString()
MaybeHandle< String > v8::internal::JSDateTimeFormat::TimeZoneIdToString (Isolate * isolate, const icu::UnicodeString & id) [static]
Definition at line 561 of file js-date-time-format.cc.
                                                  {
  // In CLDR (http://unicode.org/cldr/trac/ticket/9943), Etc/UTC is made
  // a separate timezone ID from Etc/GMT even though they're still the same
  // timezone. We have Etc/UTC because 'UTC', 'Etc/Universal',
  // 'Etc/Zulu' and others are turned to 'Etc/UTC' by ICU. Etc/GMT comes
  // from Etc/GMT0, Etc/GMT+0, Etc/GMT-0, Etc/Greenwich.
  // ecma402#sec-canonicalizetimezonename step 3
  if (id == UNICODE_STRING_SIMPLE("Etc/UTC") ||
      id == UNICODE_STRING_SIMPLE("Etc/GMT")) {
    return isolate->factory()->UTC_string();
  }
  // If the id is in the format of GMT[+-]hh:mm, change it to
  // [+-]hh:mm.
  if (id.startsWith(u"GMT", 3)) {
    return Intl::ToString(isolate, id.tempSubString(3));
  }
  return Intl::ToString(isolate, id);
}
References v8::internal::Isolate::factory(), and v8::internal::Intl::ToString().
Referenced by v8::internal::Intl::DefaultTimeZone(), and TimeZoneId().
ToLocaleDateTime()
MaybeDirectHandle< String > v8::internal::JSDateTimeFormat::ToLocaleDateTime (Isolate * isolate, DirectHandle< Object > date, DirectHandle< Object > locales, DirectHandle< Object > options, RequiredOption required, DefaultsOption defaults, const char * method_name) [static]
Definition at line 1352 of file js-date-time-format.cc.
                                                      {
  Isolate::ICUObjectCacheType cache_type = ConvertToCacheType(defaults);
  Factory* factory = isolate->factory();
  // 1. Let x be ? thisTimeValue(this value);
  if (!IsJSDate(*date)) {
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kMethodInvokedOnWrongType,
                                 factory->Date_string()));
  }
  double const x = Cast<JSDate>(date)->value();
  // 2. If x is NaN, return "Invalid Date"
  if (std::isnan(x)) {
    return factory->Invalid_Date_string();
  }
  // We only cache the instance when locales is a string/undefined and
  // options is undefined, as that is the only case when the specified
  // side-effects of examining those arguments are unobservable.
  bool can_cache = (IsString(*locales) || IsUndefined(*locales, isolate)) &&
                   IsUndefined(*options, isolate);
  if (can_cache) {
    // Both locales and options are undefined, check the cache.
    icu::SimpleDateFormat* cached_icu_simple_date_format =
        static_cast<icu::SimpleDateFormat*>(
            isolate->get_cached_icu_object(cache_type, locales));
    if (cached_icu_simple_date_format != nullptr) {
      return FormatDateTime(isolate, *cached_icu_simple_date_format, x);
    }
  }
  // 4. Let dateFormat be ? Construct(%DateTimeFormat%, « locales, options »).
  DirectHandle<JSFunction> constructor(
      Cast<JSFunction>(isolate->context()
                           ->native_context()
                           ->intl_date_time_format_function()),
      isolate);
  DirectHandle<Map> map;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, map,
      JSFunction::GetDerivedMap(isolate, constructor, constructor));
  DirectHandle<JSDateTimeFormat> date_time_format;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, date_time_format,
      JSDateTimeFormat::CreateDateTimeFormat(isolate, map, locales, options,
                                             required, defaults, method_name));
  if (can_cache) {
    isolate->set_icu_object_in_cache(
        cache_type, locales,
        std::static_pointer_cast<icu::UMemory>(
            date_time_format->icu_simple_date_format()->get()));
  }
  // 5. Return FormatDateTime(dateFormat, x).
  icu::SimpleDateFormat* format =
      date_time_format->icu_simple_date_format()->raw();
  return FormatDateTime(isolate, *format, x);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::context(), v8::internal::anonymous_namespace{js-date-time-format.cc}::ConvertToCacheType(), CreateDateTimeFormat(), v8::internal::date, v8::internal::Isolate::factory(), v8::internal::format, v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatDateTime(), v8::internal::JSFunction::GetDerivedMap(), and THROW_NEW_ERROR.
UnwrapDateTimeFormat()
MaybeDirectHandle< JSDateTimeFormat > v8::internal::JSDateTimeFormat::UnwrapDateTimeFormat (Isolate * isolate, Handle< JSReceiver > format_holder) [static]
Definition at line 1433 of file js-date-time-format.cc.
                                                        {
  DirectHandle<Context> native_context(isolate->context()->native_context(),
                                       isolate);
  DirectHandle<JSFunction> constructor(
      Cast<JSFunction>(native_context->intl_date_time_format_function()),
      isolate);
  DirectHandle<Object> dtf;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, dtf,
      Intl::LegacyUnwrapReceiver(isolate, format_holder, constructor,
                                 IsJSDateTimeFormat(*format_holder)));
  // 2. If Type(dtf) is not Object or dtf does not have an
  // [[InitializedDateTimeFormat]] internal slot, then
  if (!IsJSDateTimeFormat(*dtf)) {
    // a. Throw a TypeError exception.
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kIncompatibleMethodReceiver,
                                 isolate->factory()->NewStringFromAsciiChecked(
                                     "UnwrapDateTimeFormat"),
                                 format_holder));
  }
  // 3. Return dtf.
  return Cast<JSDateTimeFormat>(dtf);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::context(), v8::internal::Isolate::factory(), v8::internal::Intl::LegacyUnwrapReceiver(), v8::internal::native_context, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), and THROW_NEW_ERROR.
Referenced by v8::internal::BUILTIN().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-date-time-format.h
/mnt/V8SourceCode/src/objects/js-date-time-format-inl.h
/mnt/V8SourceCode/src/objects/js-date-time-format.cc