v8::internal::compiler::PendingAssessment Class Reference
#include <register-allocator-verifier.h>
Public Member Functions
PendingAssessment (Zone *zone, const InstructionBlock *origin, InstructionOperand operand)
PendingAssessment (const PendingAssessment &)=delete
PendingAssessment & operator= (const PendingAssessment &)=delete
const InstructionBlock * origin () const
InstructionOperand operand () const
bool IsAliasOf (int vreg) const
void AddAlias (int vreg)
Static Public Member Functions
static const PendingAssessment * cast (const Assessment *assessment)
static PendingAssessment * cast (Assessment *assessment)
Private Attributes
const InstructionBlock *const origin_
InstructionOperand operand_
ZoneSet< int > aliases_
Additional Inherited Members
Detailed Description
Definition at line 76 of file register-allocator-verifier.h.
Constructor & Destructor Documentation
PendingAssessment() [1/2]
v8::internal::compiler::PendingAssessment::PendingAssessment (Zone * zone, const InstructionBlock * origin, InstructionOperand operand) [inline], [explicit]
Definition at line 78 of file register-allocator-verifier.h.
      : Assessment(Pending),
        origin_(origin),
        operand_(operand),
        aliases_(zone) {}
PendingAssessment() [2/2]
v8::internal::compiler::PendingAssessment::PendingAssessment (const PendingAssessment &) [delete]
Member Function Documentation
AddAlias()
void v8::internal::compiler::PendingAssessment::AddAlias (int vreg) [inline]
Definition at line 101 of file register-allocator-verifier.h.
{ aliases_.insert(vreg); }
References aliases_.
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment().
cast() [1/2]
static PendingAssessment* v8::internal::compiler::PendingAssessment::cast (Assessment * assessment) [inline], [static]
Definition at line 93 of file register-allocator-verifier.h.
                                                         {
    CHECK(assessment->kind() == Pending);
    return static_cast<PendingAssessment*>(assessment);
  }
References CHECK, v8::internal::compiler::Assessment::kind(), and v8::internal::compiler::Pending.
cast() [2/2]
static const PendingAssessment* v8::internal::compiler::PendingAssessment::cast (const Assessment * assessment) [inline], [static]
Definition at line 88 of file register-allocator-verifier.h.
                                                                     {
    CHECK(assessment->kind() == Pending);
    return static_cast<const PendingAssessment*>(assessment);
  }
References CHECK, v8::internal::compiler::Assessment::kind(), and v8::internal::compiler::Pending.
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment(), v8::internal::compiler::RegisterAllocatorVerifier::ValidateUse(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
IsAliasOf()
bool v8::internal::compiler::PendingAssessment::IsAliasOf (int vreg) const [inline]
Definition at line 100 of file register-allocator-verifier.h.
{ return aliases_.count(vreg) > 0; }
References aliases_.
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment().
operand()
InstructionOperand v8::internal::compiler::PendingAssessment::operand () const [inline]
Definition at line 99 of file register-allocator-verifier.h.
{ return operand_; }
References operand_.
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment().
operator=()
PendingAssessment& v8::internal::compiler::PendingAssessment::operator= (const PendingAssessment &) [delete]
origin()
const InstructionBlock* v8::internal::compiler::PendingAssessment::origin () const [inline]
Definition at line 98 of file register-allocator-verifier.h.
{ return origin_; }
References origin_.
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment().
Member Data Documentation
aliases_
ZoneSet<int> v8::internal::compiler::PendingAssessment::aliases_ [private]
Definition at line 106 of file register-allocator-verifier.h.
Referenced by AddAlias(), and IsAliasOf().
operand_
InstructionOperand v8::internal::compiler::PendingAssessment::operand_ [private]
Definition at line 105 of file register-allocator-verifier.h.
Referenced by operand().
origin_
const InstructionBlock* const v8::internal::compiler::PendingAssessment::origin_ [private]
Definition at line 104 of file register-allocator-verifier.h.
Referenced by origin().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/register-allocator-verifier.h