v8::internal::compiler::PropertyCellData Class Reference
Public Member Functions
PropertyCellData (JSHeapBroker *broker, ObjectData **storage, IndirectHandle< PropertyCell > object, ObjectDataKind kind)
bool Cache (JSHeapBroker *broker)
PropertyDetails property_details () const
ObjectData * value () const
Private Member Functions
bool serialized () const
Private Attributes
PropertyDetails property_details_ = PropertyDetails::Empty()
ObjectData * value_ = nullptr
Detailed Description
Definition at line 161 of file heap-refs.cc.
Constructor & Destructor Documentation
PropertyCellData()
v8::internal::compiler::PropertyCellData::PropertyCellData (JSHeapBroker * broker, ObjectData ** storage, IndirectHandle< PropertyCell > object, ObjectDataKind kind)
Definition at line 216 of file heap-refs.cc.
    : HeapObjectData(broker, storage, object, kind) {}
Member Function Documentation
Cache()
bool v8::internal::compiler::PropertyCellData::Cache (JSHeapBroker * broker)
Definition at line 221 of file heap-refs.cc.
                                                 {
  if (serialized()) return true;
  TraceScope tracer(broker, this, "PropertyCellData::Serialize");
  auto cell = Cast<PropertyCell>(object());
  // While this code runs on a background thread, the property cell might
  // undergo state transitions via calls to PropertyCell::Transition. These
  // transitions follow a certain protocol on which we rely here to ensure that
  // we only report success when we can guarantee consistent data. A key
  // property is that after transitioning from cell type A to B (A != B), there
  // will never be a transition back to A, unless A is kConstant and the new
  // value is the hole (i.e. the property cell was invalidated, which is a final
  // state).
  PropertyDetails property_details = cell->property_details(kAcquireLoad);
  Handle<Object> value =
      broker->CanonicalPersistentHandle(cell->value(kAcquireLoad));
  if (broker->ObjectMayBeUninitialized(value)) {
    DCHECK(!broker->IsMainThread());
    return false;
  }
  {
    PropertyDetails property_details_again =
        cell->property_details(kAcquireLoad);
    if (property_details != property_details_again) {
      DCHECK(!broker->IsMainThread());
      return false;
    }
  }
  if (property_details.cell_type() == PropertyCellType::kInTransition) {
    DCHECK(!broker->IsMainThread());
    return false;
  }
  ObjectData* value_data = broker->TryGetOrCreateData(value);
  if (value_data == nullptr) {
    DCHECK(!broker->IsMainThread());
    return false;
  }
  PropertyCell::CheckDataIsCompatible(property_details, *value);
  DCHECK(!serialized());
  property_details_ = property_details;
  value_ = value_data;
  DCHECK(serialized());
  return true;
}
References broker(), v8::internal::PropertyDetails::cell_type(), v8::internal::PropertyCell::CheckDataIsCompatible(), v8::internal::DCHECK(), v8::kAcquireLoad, v8::internal::kInTransition, property_details(), property_details_, serialized(), value(), and value_.
property_details()
PropertyDetails v8::internal::compiler::PropertyCellData::property_details () const [inline]
Definition at line 168 of file heap-refs.cc.
                                           {
    CHECK(serialized());
    return property_details_;
  }
References CHECK, property_details_, and serialized().
Referenced by Cache().
serialized()
bool v8::internal::compiler::PropertyCellData::serialized () const [inline], [private]
Definition at line 182 of file heap-refs.cc.
{ return value_ != nullptr; }
References value_.
Referenced by Cache(), property_details(), and value().
value()
ObjectData* v8::internal::compiler::PropertyCellData::value () const [inline]
Definition at line 173 of file heap-refs.cc.
                            {
    DCHECK(serialized());
    return value_;
  }
References v8::internal::DCHECK(), serialized(), and value_.
Referenced by Cache().
Member Data Documentation
property_details_
PropertyDetails v8::internal::compiler::PropertyCellData::property_details_ = PropertyDetails::Empty() [private]
Definition at line 179 of file heap-refs.cc.
Referenced by Cache(), and property_details().
value_
ObjectData* v8::internal::compiler::PropertyCellData::value_ = nullptr [private]
Definition at line 180 of file heap-refs.cc.
Referenced by Cache(), serialized(), and value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/heap-refs.cc