v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies Class Reference
Classes
struct HandleValueEqual
Public Member Functions
PendingDependencies (Zone *zone)
void Register (Handle< HeapObject > object, DependentCode::DependencyGroup group)
void InstallAll (Isolate *isolate, Handle< Code > code)
void InstallAllPredictable (Isolate *isolate, Handle< Code > code)
Private Member Functions
uint32_t HandleValueHash (DirectHandle< HeapObject > handle)
Private Attributes
base::TemplateHashMapImpl< Handle< HeapObject >, DependentCode::DependencyGroups, HandleValueEqual, ZoneAllocationPolicy > deps_
Detailed Description
Definition at line 123 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
PendingDependencies()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::PendingDependencies (Zone * zone) [inline], [explicit]
Definition at line 125 of file compilation-dependencies.cc.
      : deps_(8, {}, ZoneAllocationPolicy(zone)) {}
Member Function Documentation
HandleValueHash()
uint32_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::HandleValueHash (DirectHandle< HeapObject > handle) [inline], [private]
Definition at line 183 of file compilation-dependencies.cc.
                                                            {
    return static_cast<uint32_t>(base::hash_value(handle->ptr()));
  }
References v8::internal::handle(), and v8::base::hash_value().
InstallAll()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::InstallAll (Isolate * isolate, Handle< Code > code) [inline]
Definition at line 141 of file compilation-dependencies.cc.
                                                       {
    if (V8_UNLIKELY(v8_flags.predictable)) {
      InstallAllPredictable(isolate, code);
      return;
    }
    // With deduplication done we no longer rely on the object address for
    // hashing.
    AllowGarbageCollection yes_gc;
    for (auto* entry = deps_.Start(); entry != nullptr;
         entry = deps_.Next(entry)) {
      DependentCode::InstallDependency(isolate, code, entry->key, entry->value);
    }
    deps_.Invalidate();
  }
References code, v8::internal::DependentCode::InstallDependency(), v8::internal::v8_flags, and V8_UNLIKELY.
InstallAllPredictable()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::InstallAllPredictable (Isolate * isolate, Handle< Code > code) [inline]
Definition at line 157 of file compilation-dependencies.cc.
                                                                  {
    CHECK(v8_flags.predictable);
    // First, guarantee predictable iteration order.
    using DepsMap = decltype(deps_);
    std::vector<const DepsMap::Entry*> entries;
    entries.reserve(deps_.occupancy());
    for (auto* entry = deps_.Start(); entry != nullptr;
         entry = deps_.Next(entry)) {
      entries.push_back(entry);
    }
    std::sort(entries.begin(), entries.end(),
              [](const DepsMap::Entry* lhs, const DepsMap::Entry* rhs) {
                return lhs->key->ptr() < rhs->key->ptr();
              });
    // With deduplication done we no longer rely on the object address for
    // hashing.
    AllowGarbageCollection yes_gc;
    for (const auto* entry : entries) {
      DependentCode::InstallDependency(isolate, code, entry->key, entry->value);
    }
    deps_.Invalidate();
  }
References CHECK, code, v8::internal::DependentCode::InstallDependency(), v8::base::sort(), and v8::internal::v8_flags.
Register()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register (Handle< HeapObject > object, DependentCode::DependencyGroup group) [inline]
Definition at line 128 of file compilation-dependencies.cc.
                                                    {
    // InstructionStream, which are per-local Isolate, cannot depend on objects
    // in the shared or RO heaps. Shared and RO heap dependencies are designed
    // to never invalidate assumptions. E.g., maps for shared structs do not
    // have transitions or change the shape of their fields. See
    // DependentCode::DeoptimizeDependencyGroups for corresponding DCHECK.
    if (HeapLayout::InWritableSharedSpace(*object) ||
        HeapLayout::InReadOnlySpace(*object))
      return;
    deps_.LookupOrInsert(object, HandleValueHash(object))->value |= group;
  }
References v8::internal::HeapLayout::InReadOnlySpace(), and v8::internal::HeapLayout::InWritableSharedSpace().
Referenced by v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::StableMapDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConstantInDictionaryPrototypeChainDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::TransitionDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PretenureModeDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldTypeDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldConstnessDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::GlobalPropertyDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ContextCellDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency::Install(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ProtectorDependency::Install(), and v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency::Install().
Member Data Documentation
deps_
base::TemplateHashMapImpl<Handle<HeapObject>, DependentCode::DependencyGroups, HandleValueEqual, ZoneAllocationPolicy> v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::deps_ [private]
Definition at line 196 of file compilation-dependencies.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc