v8::internal::Ticker Class Reference
Public Member Functions
Ticker (Isolate *isolate, int interval_microseconds)
~Ticker () override
void SetProfiler (Profiler *profiler)
void ClearProfiler ()
void SampleStack (const v8::RegisterState &state) override
Private Attributes
Profiler * profiler_ = nullptr
std::unique_ptr< SamplingThread > sampling_thread_
Isolate::PerIsolateThreadData * perThreadData_
Additional Inherited Members
Detailed Description
Definition at line 1116 of file log.cc.
Constructor & Destructor Documentation
Ticker()
v8::internal::Ticker::Ticker (Isolate * isolate, int interval_microseconds) [inline]
Definition at line 1118 of file log.cc.
      : sampler::Sampler(reinterpret_cast<v8::Isolate*>(isolate)),
        sampling_thread_(
            std::make_unique<SamplingThread>(this, interval_microseconds)),
        perThreadData_(isolate->FindPerThreadDataForThisThread()) {}
 Ticker()
v8::internal::Ticker::~Ticker () [inline], [override]
Definition at line 1124 of file log.cc.
                     {
    if (IsActive()) Stop();
  }
References v8::sampler::Sampler::IsActive(), and v8::sampler::Sampler::Stop().
Member Function Documentation
ClearProfiler()
void v8::internal::Ticker::ClearProfiler () [inline]
Definition at line 1135 of file log.cc.
                       {
    profiler_ = nullptr;
    if (IsActive()) Stop();
    sampling_thread_->Join();
  }
References v8::sampler::Sampler::IsActive(), profiler_, sampling_thread_, and v8::sampler::Sampler::Stop().
SampleStack()
void v8::internal::Ticker::SampleStack (const v8::RegisterState & state) [inline], [override], [virtual]
Implements v8::sampler::Sampler.
Definition at line 1141 of file log.cc.
                                                          {
    if (!profiler_) return;
    Isolate* isolate = reinterpret_cast<Isolate*>(this->isolate());
    if (isolate->was_locker_ever_used() &&
        (!isolate->thread_manager()->IsLockedByThread(
             perThreadData_->thread_id()) ||
         perThreadData_->thread_state() != nullptr))
      return;
    TickSample sample;
    sample.Init(isolate, state, TickSample::kIncludeCEntryFrame, true);
    profiler_->Insert(&sample);
  }
References v8::internal::TickSample::Init(), v8::internal::Profiler::Insert(), v8::sampler::Sampler::isolate(), v8::internal::TickSample::kIncludeCEntryFrame, perThreadData_, profiler_, v8::internal::Isolate::PerIsolateThreadData::thread_id(), and v8::internal::Isolate::was_locker_ever_used().
SetProfiler()
void v8::internal::Ticker::SetProfiler (Profiler * profiler) [inline]
Definition at line 1128 of file log.cc.
                                       {
    DCHECK_NULL(profiler_);
    profiler_ = profiler;
    if (!IsActive()) Start();
    sampling_thread_->StartSynchronously();
  }
References DCHECK_NULL, v8::sampler::Sampler::IsActive(), profiler_, sampling_thread_, and v8::sampler::Sampler::Start().
Member Data Documentation
perThreadData_
Isolate::PerIsolateThreadData* v8::internal::Ticker::perThreadData_ [private]
Definition at line 1157 of file log.cc.
Referenced by SampleStack().
profiler_
Profiler* v8::internal::Ticker::profiler_ = nullptr [private]
Definition at line 1155 of file log.cc.
Referenced by ClearProfiler(), SampleStack(), and SetProfiler().
sampling_thread_
std::unique_ptr<SamplingThread> v8::internal::Ticker::sampling_thread_ [private]
Definition at line 1156 of file log.cc.
Referenced by ClearProfiler(), and SetProfiler().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/logging/log.cc