v8::internal::ObjectStatsCollector Class Reference
#include <object-stats.h>
Public Member Functions
ObjectStatsCollector (Heap *heap, ObjectStats *live, ObjectStats *dead)
void Collect ()
Private Attributes
Heap *const heap_
ObjectStats *const live_
ObjectStats *const dead_
Detailed Description
Definition at line 178 of file object-stats.h.
Constructor & Destructor Documentation
ObjectStatsCollector()
v8::internal::ObjectStatsCollector::ObjectStatsCollector (Heap * heap, ObjectStats * live, ObjectStats * dead) [inline]
Definition at line 180 of file object-stats.h.
      : heap_(heap), live_(live), dead_(dead) {
    DCHECK_NOT_NULL(heap_);
    DCHECK_NOT_NULL(live_);
    DCHECK_NOT_NULL(dead_);
  }
References DCHECK_NOT_NULL, dead_, heap_, and live_.
Member Function Documentation
Collect()
void v8::internal::ObjectStatsCollector::Collect ()
Definition at line 1201 of file object-stats.cc.
                                   {
  ObjectStatsCollectorImpl live_collector(heap_, live_);
  ObjectStatsCollectorImpl dead_collector(heap_, dead_);
  live_collector.CollectGlobalStatistics();
  for (int i = 0; i < ObjectStatsCollectorImpl::kNumberOfPhases; i++) {
    ObjectStatsVisitor visitor(heap_, &live_collector, &dead_collector,
                               static_cast<ObjectStatsCollectorImpl::Phase>(i));
    IterateHeap(heap_, &visitor);
  }
}
References v8::internal::ObjectStatsCollectorImpl::CollectGlobalStatistics(), dead_, heap_, v8::internal::anonymous_namespace{object-stats.cc}::IterateHeap(), v8::internal::ObjectStatsCollectorImpl::kNumberOfPhases, and live_.
Referenced by v8::internal::MarkCompactCollector::RecordObjectStats().
Member Data Documentation
dead_
ObjectStats* const v8::internal::ObjectStatsCollector::dead_ [private]
Definition at line 194 of file object-stats.h.
Referenced by Collect(), and ObjectStatsCollector().
heap_
Heap* const v8::internal::ObjectStatsCollector::heap_ [private]
Definition at line 192 of file object-stats.h.
Referenced by Collect(), and ObjectStatsCollector().
live_
ObjectStats* const v8::internal::ObjectStatsCollector::live_ [private]
Definition at line 193 of file object-stats.h.
Referenced by Collect(), and ObjectStatsCollector().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/object-stats.h
/mnt/V8SourceCode/src/heap/object-stats.cc