v8::internal::wasm::NativeModuleCache Class Reference
#include <wasm-engine.h>
Classes
struct Key
Public Member Functions
std::shared_ptr< NativeModule > MaybeGetNativeModule (ModuleOrigin origin, base::Vector< const uint8_t > wire_bytes, const CompileTimeImports &compile_imports)
bool GetStreamingCompilationOwnership (size_t prefix_hash, const CompileTimeImports &compile_imports)
void StreamingCompilationFailed (size_t prefix_hash, const CompileTimeImports &compile_imports)
std::shared_ptr< NativeModule > Update (std::shared_ptr< NativeModule > native_module, bool error)
void Erase (NativeModule *native_module)
bool empty () const
Static Public Member Functions
static size_t PrefixHash (base::Vector< const uint8_t > wire_bytes)
Private Attributes
std::map< Key, std::optional< std::weak_ptr< NativeModule > > > map_
base::Mutex mutex_
base::ConditionVariable cache_cv_
Detailed Description
Definition at line 73 of file wasm-engine.h.
Member Function Documentation
empty()
bool v8::internal::wasm::NativeModuleCache::empty () const [inline]
Definition at line 130 of file wasm-engine.h.
{ return map_.empty(); }
References map_.
Referenced by v8::internal::wasm::WasmEngine::~WasmEngine().
Erase()
void v8::internal::wasm::NativeModuleCache::Erase (NativeModule * native_module)
Definition at line 399 of file wasm-engine.cc.
                                                         {
  if (!v8_flags.wasm_native_module_cache) return;
  if (native_module->module()->origin != kWasmOrigin) return;
  // Happens in some tests where bytes are set directly.
  if (native_module->wire_bytes().empty()) return;
  base::MutexGuard lock(&mutex_);
  size_t prefix_hash = PrefixHash(native_module->wire_bytes());
  map_.erase(Key{prefix_hash, native_module->compile_imports(),
                 native_module->wire_bytes()});
  cache_cv_.NotifyAll();
}
References cache_cv_, v8::internal::wasm::NativeModule::compile_imports(), v8::base::Vector< T >::empty(), v8::internal::wasm::kWasmOrigin, map_, v8::internal::wasm::NativeModule::module(), mutex_, v8::base::ConditionVariable::NotifyAll(), v8::internal::wasm::WasmModule::origin, PrefixHash(), v8::internal::v8_flags, and v8::internal::wasm::NativeModule::wire_bytes().
Referenced by v8::internal::wasm::WasmEngine::FreeNativeModule().
GetStreamingCompilationOwnership()
bool v8::internal::wasm::NativeModuleCache::GetStreamingCompilationOwnership (size_t prefix_hash, const CompileTimeImports & compile_imports)
Definition at line 335 of file wasm-engine.cc.
                                                                   {
  if (!v8_flags.wasm_native_module_cache) return true;
  base::MutexGuard lock(&mutex_);
  auto it = map_.lower_bound(Key{prefix_hash, compile_imports, {}});
  if (it != map_.end() && it->first.prefix_hash == prefix_hash) {
    DCHECK_IMPLIES(!it->first.bytes.empty(),
                   PrefixHash(it->first.bytes) == prefix_hash);
    return false;
  }
  Key key{prefix_hash, compile_imports, {}};
  DCHECK_EQ(0, map_.count(key));
  map_.emplace(key, std::nullopt);
  return true;
}
References DCHECK_EQ, DCHECK_IMPLIES, v8::internal::key, map_, mutex_, PrefixHash(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmEngine::GetStreamingCompilationOwnership().
MaybeGetNativeModule()
std::shared_ptr< NativeModule > v8::internal::wasm::NativeModuleCache::MaybeGetNativeModule (ModuleOrigin origin, base::Vector< const uint8_t > wire_bytes, const CompileTimeImports & compile_imports)
Definition at line 295 of file wasm-engine.cc.
                                               {
  if (!v8_flags.wasm_native_module_cache) return nullptr;
  if (origin != kWasmOrigin) return nullptr;
  base::MutexGuard lock(&mutex_);
  size_t prefix_hash = PrefixHash(wire_bytes);
  NativeModuleCache::Key key{prefix_hash, compile_imports, wire_bytes};
  while (true) {
    auto it = map_.find(key);
    if (it == map_.end()) {
      // Even though this exact key is not in the cache, there might be a
      // matching prefix hash indicating that a streaming compilation is
      // currently compiling a module with the same prefix. {OnFinishedStream}
      // happens on the main thread too, so waiting for streaming compilation to
      // finish would create a deadlock. Instead, compile the module twice and
      // handle the conflict in {UpdateNativeModuleCache}.
      // Insert a {nullopt} entry to let other threads know that this
      // {NativeModule} is already being created on another thread.
      [[maybe_unused]] auto [iterator, inserted] =
          map_.emplace(key, std::nullopt);
      DCHECK(inserted);
      return nullptr;
    }
    if (it->second.has_value()) {
      if (auto shared_native_module = it->second.value().lock()) {
        DCHECK_EQ(
            shared_native_module->compile_imports().compare(compile_imports),
            0);
        DCHECK_EQ(shared_native_module->wire_bytes(), wire_bytes);
        return shared_native_module;
      }
    }
    // TODO(11858): This deadlocks in predictable mode, because there is only a
    // single thread.
    cache_cv_.Wait(&mutex_);
  }
}
References cache_cv_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::key, v8::internal::wasm::kWasmOrigin, map_, mutex_, PrefixHash(), v8::internal::v8_flags, and v8::base::ConditionVariable::Wait().
Referenced by v8::internal::wasm::WasmEngine::MaybeGetNativeModule().
PrefixHash()
size_t v8::internal::wasm::NativeModuleCache::PrefixHash (base::Vector< const uint8_t > wire_bytes) [static]
Definition at line 412 of file wasm-engine.cc.
                                                                         {
  // Compute the hash as a combined hash of the sections up to the code section
  // header, to mirror the way streaming compilation does it.
  Decoder decoder(wire_bytes.begin(), wire_bytes.end());
  decoder.consume_bytes(8, "module header");
  SectionCode section_id = SectionCode::kUnknownSectionCode;
  base::Hasher hasher;
  while (decoder.ok() && decoder.more()) {
    section_id = static_cast<SectionCode>(decoder.consume_u8());
    uint32_t section_size = decoder.consume_u32v("section size");
    if (section_id == SectionCode::kCodeSectionCode) {
      hasher.Add(section_size);
      break;
    }
    const uint8_t* payload_start = decoder.pc();
    decoder.consume_bytes(section_size, "section payload");
    hasher.AddRange(base::VectorOf(payload_start, section_size));
  }
  return hasher.hash();
}
References v8::base::Hasher::Add(), v8::base::Hasher::AddRange(), v8::base::Vector< T >::begin(), v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u8(), v8::base::Vector< T >::end(), v8::base::Hasher::hash(), v8::internal::wasm::kCodeSectionCode, v8::internal::wasm::kUnknownSectionCode, v8::internal::wasm::Decoder::more(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc(), and v8::base::VectorOf().
Referenced by Erase(), GetStreamingCompilationOwnership(), MaybeGetNativeModule(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), and Update().
StreamingCompilationFailed()
void v8::internal::wasm::NativeModuleCache::StreamingCompilationFailed (size_t prefix_hash, const CompileTimeImports & compile_imports)
Definition at line 351 of file wasm-engine.cc.
                                                                   {
  if (!v8_flags.wasm_native_module_cache) return;
  base::MutexGuard lock(&mutex_);
  Key key{prefix_hash, compile_imports, {}};
  map_.erase(key);
  cache_cv_.NotifyAll();
}
References cache_cv_, v8::internal::key, map_, mutex_, v8::base::ConditionVariable::NotifyAll(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmEngine::StreamingCompilationFailed().
Update()
std::shared_ptr< NativeModule > v8::internal::wasm::NativeModuleCache::Update (std::shared_ptr< NativeModule > native_module, bool error)
Definition at line 360 of file wasm-engine.cc.
                                                           {
  DCHECK_NOT_NULL(native_module);
  if (!v8_flags.wasm_native_module_cache) return native_module;
  if (native_module->module()->origin != kWasmOrigin) return native_module;
  base::Vector<const uint8_t> wire_bytes = native_module->wire_bytes();
  DCHECK(!wire_bytes.empty());
  size_t prefix_hash = PrefixHash(native_module->wire_bytes());
  base::MutexGuard lock(&mutex_);
  const CompileTimeImports& compile_imports = native_module->compile_imports();
  map_.erase(Key{prefix_hash, compile_imports, {}});
  const Key key{prefix_hash, compile_imports, wire_bytes};
  auto it = map_.find(key);
  if (it != map_.end()) {
    if (it->second.has_value()) {
      auto conflicting_module = it->second.value().lock();
      if (conflicting_module != nullptr) {
        DCHECK_EQ(conflicting_module->wire_bytes(), wire_bytes);
        // This return might delete {native_module} if we were the last holder.
        // That in turn can call {NativeModuleCache::Erase}, which takes the
        // mutex. This is not a problem though, since the {MutexGuard} above is
        // released before the {native_module}, per the definition order.
        return conflicting_module;
      }
    }
    map_.erase(it);
  }
  if (!error) {
    // The key now points to the new native module's owned copy of the bytes,
    // so that it stays valid until the native module is freed and erased from
    // the map.
    [[maybe_unused]] auto [iterator, inserted] = map_.emplace(
        key, std::optional<std::weak_ptr<NativeModule>>(native_module));
    DCHECK(inserted);
  }
  cache_cv_.NotifyAll();
  return native_module;
}
References cache_cv_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::base::Vector< T >::empty(), v8::internal::key, v8::internal::wasm::kWasmOrigin, map_, mutex_, v8::base::ConditionVariable::NotifyAll(), PrefixHash(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmEngine::UpdateNativeModuleCache().
Member Data Documentation
cache_cv_
base::ConditionVariable v8::internal::wasm::NativeModuleCache::cache_cv_ [private]
Definition at line 157 of file wasm-engine.h.
Referenced by Erase(), MaybeGetNativeModule(), StreamingCompilationFailed(), and Update().
map_
std::map<Key, std::optional<std::weak_ptr<NativeModule> > > v8::internal::wasm::NativeModuleCache::map_ [private]
Definition at line 150 of file wasm-engine.h.
Referenced by empty(), Erase(), GetStreamingCompilationOwnership(), MaybeGetNativeModule(), StreamingCompilationFailed(), and Update().
mutex_
base::Mutex v8::internal::wasm::NativeModuleCache::mutex_ [private]
Definition at line 152 of file wasm-engine.h.
Referenced by Erase(), GetStreamingCompilationOwnership(), MaybeGetNativeModule(), StreamingCompilationFailed(), and Update().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-engine.h
/mnt/V8SourceCode/src/wasm/wasm-engine.cc