v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder Class Reference
Classes
struct Move
Static Public Member Functions
static void Build (MaglevAssembler *masm, NodeBase *node)
Private Types
using MoveVector = base::SmallVector< Move, 16 >
Private Member Functions
ExceptionHandlerTrampolineBuilder (MaglevAssembler *masm)
void EmitTrampolineFor (NodeBase *node)
MaglevAssembler * masm () const
void RecordMoves (const MaglevCompilationUnit &unit, BasicBlock *catch_block, const CompactInterpreterFrameState *register_frame, ParallelMoveResolver< Register, COMPRESS_POINTERS_BOOL > *direct_moves, MoveVector *materialising_moves, bool *save_accumulator)
void EmitMaterialisationsAndPushResults (const MoveVector &moves, bool save_accumulator) const
void EmitPopMaterialisedResults (const MoveVector &moves, bool save_accumulator, Register scratch) const
Private Attributes
MaglevAssembler *const masm_
Detailed Description
Definition at line 519 of file maglev-code-generator.cc.
Member Typedef Documentation
MoveVector
using v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::MoveVector = base::SmallVector<Move, 16> [private]
Definition at line 536 of file maglev-code-generator.cc.
Constructor & Destructor Documentation
ExceptionHandlerTrampolineBuilder()
v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::ExceptionHandlerTrampolineBuilder (MaglevAssembler * masm) [inline], [explicit], [private]
Definition at line 527 of file maglev-code-generator.cc.
      : masm_(masm) {}
Member Function Documentation
Build()
static void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::Build (MaglevAssembler * masm, NodeBase * node) [inline], [static]
Definition at line 521 of file maglev-code-generator.cc.
                                                           {
    ExceptionHandlerTrampolineBuilder builder(masm);
    builder.EmitTrampolineFor(node);
  }
References EmitTrampolineFor().
EmitMaterialisationsAndPushResults()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitMaterialisationsAndPushResults (const MoveVector & moves, bool save_accumulator) const [inline], [private]
Definition at line 648 of file maglev-code-generator.cc.
                                                                       {
    if (moves.empty()) return;
    // It's possible to optimize this further, at the cost of additional
    // complexity:
    //
    // - If the target location is a register, we could theoretically move the
    // materialised result there immediately, with the additional complication
    // that following calls to NewHeapNumber may clobber the register.
    //
    // - If the target location is a stack slot which is neither a source nor
    // target slot for any other moves (direct or materialising), we could move
    // the result there directly instead of pushing and later popping it. This
    // doesn't seem worth the extra code complexity though, given we are
    // talking about a presumably infrequent case for exception handlers.
    __ RecordComment("EmitMaterialisationsAndPushResults");
    if (save_accumulator) __ Push(kReturnRegister0);
#ifdef DEBUG
    // Allow calls in these materialisations.
    __ set_allow_call(true);
#endif
    for (const Move& move : moves) {
      // We consider constants after all other operations, since constants
      // don't need to call NewHeapNumber.
      if (IsConstantNode(move.source->opcode())) continue;
      __ MaterialiseValueNode(kReturnRegister0, move.source);
      __ Push(kReturnRegister0);
    }
#ifdef DEBUG
    __ set_allow_call(false);
#endif
  }
References __, v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::internal::maglev::IsConstantNode(), and v8::internal::kReturnRegister0.
EmitPopMaterialisedResults()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitPopMaterialisedResults (const MoveVector & moves, bool save_accumulator, Register scratch) const [inline], [private]
Definition at line 685 of file maglev-code-generator.cc.
                                                          {
    if (moves.empty()) return;
    __ RecordComment("EmitPopMaterialisedResults");
    for (const Move& move : base::Reversed(moves)) {
      const ValueLocation& target = move.target;
      Register target_reg = target.operand().IsAnyRegister()
                                ? target.AssignedGeneralRegister()
                                : scratch;
      if (IsConstantNode(move.source->opcode())) {
        __ MaterialiseValueNode(target_reg, move.source);
      } else {
        __ Pop(target_reg);
      }
      if (target_reg == scratch) {
        __ Move(masm_->ToMemOperand(target.operand()), scratch);
      }
    }
    if (save_accumulator) __ Pop(kReturnRegister0);
  }
References __, v8::internal::maglev::ValueLocation::AssignedGeneralRegister(), v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::maglev::IsConstantNode(), v8::internal::kReturnRegister0, v8::internal::maglev::ValueLocation::operand(), and v8::base::Reversed().
EmitTrampolineFor()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitTrampolineFor (NodeBase * node) [inline], [private]
Definition at line 538 of file maglev-code-generator.cc.
                                         {
    DCHECK(node->properties().can_throw());
    ExceptionHandlerInfo* const handler_info = node->exception_handler_info();
    if (handler_info->ShouldLazyDeopt()) return;
    DCHECK(handler_info->HasExceptionHandler());
    BasicBlock* const catch_block = handler_info->catch_block();
    LazyDeoptInfo* const deopt_info = node->lazy_deopt_info();
    // The exception handler trampoline resolves moves for exception phis and
    // then jumps to the actual catch block. There are a few points worth
    // noting:
    //
    // - All source locations are assumed to be stack slots, except the
    // accumulator which is stored in kReturnRegister0. We don't emit an
    // explicit move for it, instead it is pushed and popped at the boundaries
    // of the entire move sequence (necessary due to materialisation).
    //
    // - Some values may require materialisation, i.e. heap number construction
    // through calls to the NewHeapNumber builtin. To avoid potential conflicts
    // with other moves (which may happen due to stack slot reuse, i.e. a
    // target location of move A may equal source location of move B), we
    // materialise and push results to new temporary stack slots before the
    // main move sequence, and then pop results into their final target
    // locations afterwards. Note this is only safe because a) materialised
    // values are tagged and b) the stack walk treats unknown stack slots as
    // tagged.
    const InterpretedDeoptFrame& lazy_frame =
        deopt_info->GetFrameForExceptionHandler(handler_info);
    // TODO(v8:7700): Handle inlining.
    ParallelMoveResolver<Register, COMPRESS_POINTERS_BOOL> direct_moves(masm_);
    MoveVector materialising_moves;
    bool save_accumulator = false;
    RecordMoves(lazy_frame.unit(), catch_block, lazy_frame.frame_state(),
                &direct_moves, &materialising_moves, &save_accumulator);
    __ BindJumpTarget(&handler_info->trampoline_entry());
    __ RecordComment("-- Exception handler trampoline START");
    EmitMaterialisationsAndPushResults(materialising_moves, save_accumulator);
    __ RecordComment("EmitMoves");
    MaglevAssembler::TemporaryRegisterScope temps(masm_);
    Register scratch = temps.AcquireScratch();
    direct_moves.EmitMoves(scratch);
    EmitPopMaterialisedResults(materialising_moves, save_accumulator, scratch);
    __ Jump(catch_block->label());
    __ RecordComment("-- Exception handler trampoline END");
  }
References __, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::maglev::OpProperties::can_throw(), v8::internal::maglev::ExceptionHandlerInfo::catch_block(), v8::internal::DCHECK(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::EmitMoves(), v8::internal::maglev::NodeBase::exception_handler_info(), v8::internal::maglev::InterpretedDeoptFrame::frame_state(), v8::internal::maglev::LazyDeoptInfo::GetFrameForExceptionHandler(), v8::internal::maglev::ExceptionHandlerInfo::HasExceptionHandler(), v8::internal::maglev::BasicBlock::label(), v8::internal::maglev::NodeBase::lazy_deopt_info(), v8::internal::maglev::NodeBase::properties(), v8::internal::maglev::ExceptionHandlerInfo::ShouldLazyDeopt(), v8::internal::maglev::ExceptionHandlerInfo::trampoline_entry(), and v8::internal::maglev::InterpretedDeoptFrame::unit().
Referenced by Build().
masm()
MaglevAssembler* v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::masm () const [inline], [private]
Definition at line 588 of file maglev-code-generator.cc.
{ return masm_; }
RecordMoves()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves (const MaglevCompilationUnit & unit, BasicBlock * catch_block, const CompactInterpreterFrameState * register_frame, ParallelMoveResolver< Register, COMPRESS_POINTERS_BOOL > * direct_moves, MoveVector * materialising_moves, bool * save_accumulator) [inline], [private]
Definition at line 590 of file maglev-code-generator.cc.
                                                               {
    if (!catch_block->has_phi()) return;
    for (Phi* phi : *catch_block->phis()) {
      DCHECK(phi->is_exception_phi());
      if (!phi->has_valid_live_range()) continue;
      const ValueLocation& target = phi->result();
      if (phi->owner() == interpreter::Register::virtual_accumulator()) {
        // If the accumulator is live, then it is the exception object located
        // at kReturnRegister0. We don't emit a move for it since the value is
        // already in the right spot, but we do have to ensure it isn't
        // clobbered by calls to the NewHeapNumber builtin during
        // materialisation.
        DCHECK_EQ(target.AssignedGeneralRegister(), kReturnRegister0);
        *save_accumulator = true;
        continue;
      }
      ValueNode* source = register_frame->GetValueOf(phi->owner(), unit);
      DCHECK_NOT_NULL(source);
      if (VirtualObject* vobj = source->TryCast<VirtualObject>()) {
        DCHECK(vobj->allocation()->HasEscaped());
        source = vobj->allocation();
      }
      // All registers must have been spilled due to the call.
      // TODO(jgruber): Which call? Because any throw requires at least a call
      // to Runtime::kThrowFoo?
      DCHECK(!source->allocation().IsRegister());
      // The DeoptInfoVisitor should unwrap identity nodes in frame states.
      DCHECK(!source->Is<Identity>());
      switch (source->properties().value_representation()) {
        case ValueRepresentation::kTagged:
          direct_moves->RecordMove(
              source, source->allocation(),
              compiler::AllocatedOperand::cast(target.operand()),
              phi->decompresses_tagged_result() ? kNeedsDecompression
                                                : kDoesNotNeedDecompression);
          break;
        case ValueRepresentation::kInt32:
        case ValueRepresentation::kUint32:
        case ValueRepresentation::kIntPtr:
          materialising_moves->emplace_back(target, source);
          break;
        case ValueRepresentation::kFloat64:
        case ValueRepresentation::kHoleyFloat64:
          materialising_moves->emplace_back(target, source);
          break;
          UNREACHABLE();
      }
    }
  }
References v8::internal::maglev::ValueNode::allocation(), v8::internal::maglev::ValueLocation::AssignedGeneralRegister(), v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::internal::maglev::CompactInterpreterFrameState::GetValueOf(), v8::internal::maglev::BasicBlock::has_phi(), v8::internal::maglev::NodeBase::Is(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::kDoesNotNeedDecompression, v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::kNeedsDecompression, v8::internal::kReturnRegister0, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, v8::internal::maglev::ValueLocation::operand(), v8::internal::maglev::BasicBlock::phis(), v8::internal::maglev::NodeBase::properties(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMove(), v8::internal::maglev::NodeBase::TryCast(), v8::internal::UNREACHABLE(), v8::internal::maglev::OpProperties::value_representation(), and v8::internal::interpreter::Register::virtual_accumulator().
Member Data Documentation
masm_
MaglevAssembler* const v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::masm_ [private]
Definition at line 707 of file maglev-code-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-code-generator.cc