cppgc::internal::RootVisitor Class Reference
#include <visitor.h>
Public Member Functions
RootVisitor (Visitor::Key)
virtual ~RootVisitor ()=default
template<typename AnyStrongPersistentType , std::enable_if_t< AnyStrongPersistentType::IsStrongPersistent::value > * = nullptr>
void Trace (const AnyStrongPersistentType &p)
template<typename AnyWeakPersistentType , std::enable_if_t< !AnyWeakPersistentType::IsStrongPersistent::value > * = nullptr>
void Trace (const AnyWeakPersistentType &p)
Protected Member Functions
virtual void VisitRoot (const void *, TraceDescriptor, const SourceLocation &)
virtual void VisitWeakRoot (const void *self, TraceDescriptor, WeakCallback, const void *weak_root, const SourceLocation &)
Static Private Member Functions
template<typename AnyPersistentType >
static const void * Extract (AnyPersistentType &p)
template<typename PointerType >
static void HandleWeak (const LivenessBroker &info, const void *object)
Detailed Description
Definition at line 470 of file visitor.h.
Constructor & Destructor Documentation
RootVisitor()
cppgc::internal::RootVisitor::RootVisitor (Visitor::Key) [inline], [explicit]
Definition at line 472 of file visitor.h.
{}
 RootVisitor()
virtual cppgc::internal::RootVisitor::~RootVisitor () [virtual], [default]
Member Function Documentation
Extract()
template<typename AnyPersistentType >
static const void* cppgc::internal::RootVisitor::Extract (AnyPersistentType & p) [inline], [static], [private]
Definition at line 511 of file visitor.h.
                                                   {
    using PointeeType = typename AnyPersistentType::PointeeType;
    static_assert(sizeof(PointeeType),
                  "Persistent's pointee type must be fully defined");
    static_assert(internal::IsGarbageCollectedOrMixinType<PointeeType>::value,
                  "Persistent's pointee type must be GarbageCollected or "
                  "GarbageCollectedMixin");
    return p.GetFromGC();
  }
HandleWeak()
template<typename PointerType >
static void cppgc::internal::RootVisitor::HandleWeak (const LivenessBroker & info, const void * object) [inline], [static], [private]
Definition at line 522 of file visitor.h.
                                                                         {
    const PointerType* weak = static_cast<const PointerType*>(object);
    if (!info.IsHeapObjectAlive(weak->GetFromGC())) {
      weak->ClearFromGC();
    }
  }
References cppgc::LivenessBroker::IsHeapObjectAlive().
Trace() [1/2]
template<typename AnyStrongPersistentType , std::enable_if_t< AnyStrongPersistentType::IsStrongPersistent::value > * = nullptr>
void cppgc::internal::RootVisitor::Trace (const AnyStrongPersistentType & p) [inline]
Definition at line 479 of file visitor.h.
                                               {
    using PointeeType = typename AnyStrongPersistentType::PointeeType;
    const void* object = Extract(p);
    if (!object) {
      return;
    }
    VisitRoot(object, TraceTrait<PointeeType>::GetTraceDescriptor(object),
              p.Location());
  }
Referenced by cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::TraceAsRoot(), and cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::TraceAsRoot().
Trace() [2/2]
template<typename AnyWeakPersistentType , std::enable_if_t< !AnyWeakPersistentType::IsStrongPersistent::value > * = nullptr>
void cppgc::internal::RootVisitor::Trace (const AnyWeakPersistentType & p) [inline]
Definition at line 492 of file visitor.h.
                                             {
    using PointeeType = typename AnyWeakPersistentType::PointeeType;
    static_assert(!internal::IsAllocatedOnCompactableSpace<PointeeType>::value,
                  "Weak references to compactable objects are not allowed");
    const void* object = Extract(p);
    if (!object) {
      return;
    }
    VisitWeakRoot(object, TraceTrait<PointeeType>::GetTraceDescriptor(object),
                  &HandleWeak<AnyWeakPersistentType>, &p, p.Location());
  }
VisitRoot()
virtual void cppgc::internal::RootVisitor::VisitRoot (const void * , TraceDescriptor , const SourceLocation &) [inline], [protected], [virtual]
Reimplemented in cppgc::internal::RootMarkingVisitor, and v8::internal::GraphBuildingRootVisitor.
Definition at line 505 of file visitor.h.
{}
VisitWeakRoot()
virtual void cppgc::internal::RootVisitor::VisitWeakRoot (const void * self, TraceDescriptor , WeakCallback , const void * weak_root, const SourceLocation &) [inline], [protected], [virtual]
Reimplemented in cppgc::internal::RootMarkingVisitor.
Definition at line 506 of file visitor.h.
                                                                           {}
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/cppgc/visitor.h