v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next > Class Template Reference
#include <debug-feature-lowering-reducer.h>
Public Member Functions
OpIndex REDUCE() DebugPrint (OpIndex input, RegisterRepresentation rep)
V< None > REDUCE() StaticAssert (V< Word32 > condition, const char *source)
OpIndex REDUCE() CheckTurboshaftTypeOf (OpIndex input, RegisterRepresentation rep, Type type, bool successful)
Private Attributes
Isolate * isolate_ = __ data() -> isolate()
JSHeapBroker * broker_ = __ data() -> broker()
Detailed Description
template<typename Next>
class v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >
Definition at line 21 of file debug-feature-lowering-reducer.h.
Member Function Documentation
CheckTurboshaftTypeOf()
template<typename Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >::CheckTurboshaftTypeOf (OpIndex input, RegisterRepresentation rep, Type type, bool successful) [inline]
Definition at line 79 of file debug-feature-lowering-reducer.h.
                                                         {
    if (successful) return input;
    UnparkedScopeIfNeeded scope(broker_);
    AllowHandleDereference allow_handle_dereference;
    FATAL("Checking type %s of operation %d:%s failed!",
          type.ToString().c_str(), input.id(),
          __ output_graph().Get(input).ToString().c_str());
  }
References __, v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >::broker_, FATAL, v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::ToString(), and v8::internal::tracing::type.
DebugPrint()
template<typename Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >::DebugPrint (OpIndex input, RegisterRepresentation rep) [inline]
Definition at line 25 of file debug-feature-lowering-reducer.h.
                                                                        {
    if (isolate_ != nullptr) {
      switch (rep.value()) {
        case RegisterRepresentation::WordPtr():
          __ CallBuiltin_DebugPrintWordPtr(isolate_, __ NoContextConstant(),
                                           input);
          break;
        case RegisterRepresentation::Float64():
          __ CallBuiltin_DebugPrintFloat64(isolate_, __ NoContextConstant(),
                                           input);
          break;
        case RegisterRepresentation::Tagged():
          __ CallRuntime_DebugPrint(isolate_, input);
          break;
        default:
          // TODO(nicohartmann@): Support other representations.
          UNIMPLEMENTED();
      }
    } else {
#if V8_ENABLE_WEBASSEMBLY
      DCHECK(__ data()->is_wasm());
      switch (rep.value()) {
        case RegisterRepresentation::Float64():
          __ template WasmCallBuiltinThroughJumptable<
              BuiltinCallDescriptor::DebugPrintFloat64>(__ NoContextConstant(),
                                                        {input});
          break;
        case RegisterRepresentation::WordPtr():
          __ template WasmCallBuiltinThroughJumptable<
              BuiltinCallDescriptor::DebugPrintWordPtr>(__ NoContextConstant(),
                                                        {input});
          break;
        default:
          // TODO(mliedtke): Support other representations.
          UNIMPLEMENTED();
      }
#else
      UNREACHABLE();
#endif
    }
    return {};
  }
References __, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >::isolate_, v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::UNIMPLEMENTED(), v8::internal::UNREACHABLE(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
StaticAssert()
template<typename Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >::StaticAssert (V< Word32 > condition, const char * source) [inline]
Definition at line 68 of file debug-feature-lowering-reducer.h.
                                                                        {
    // Static asserts should be (statically asserted and) removed by turboshaft.
    UnparkedScopeIfNeeded scope(broker_);
    AllowHandleDereference allow_handle_dereference;
    std::cout << __ output_graph().Get(condition);
    FATAL(
        "Expected Turbofan static assert to hold, but got non-true input:\n "
        "%s",
        source);
  }
References __, v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >::broker_, and FATAL.
Member Data Documentation
broker_
template<typename Next >
JSHeapBroker* v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >::broker_ = __ data() -> broker() [private]
Definition at line 93 of file debug-feature-lowering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >::CheckTurboshaftTypeOf(), and v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >::StaticAssert().
isolate_
template<typename Next >
Isolate* v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >::isolate_ = __ data() -> isolate() [private]
Definition at line 92 of file debug-feature-lowering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::DebugFeatureLoweringReducer< Next >::DebugPrint().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/debug-feature-lowering-reducer.h