v8::internal::wasm::AsmValueType Class Reference
#include <asm-types.h>
Public Types
enum : uint32_t { kAsmUnknown = 0
, kAsmValueTypeTag = 1u
 }
using bitset_t = uint32_t
Private Member Functions
bitset_t Bitset () const
DISALLOW_IMPLICIT_CONSTRUCTORS (AsmValueType)
Static Private Member Functions
static AsmValueType * AsValueType (AsmType *type)
static AsmType * New (bitset_t bits)
Friends
class AsmType
Detailed Description
Definition at line 60 of file asm-types.h.
Member Typedef Documentation
bitset_t
using v8::internal::wasm::AsmValueType::bitset_t = uint32_t
Definition at line 62 of file asm-types.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : uint32_t
Enumerator
kAsmUnknown
kAsmValueTypeTag
Definition at line 64 of file asm-types.h.
       : uint32_t {
#define DEFINE_TAG(CamelName, string_name, number, parent_types) \
  kAsm##CamelName = ((1u << (number)) | (parent_types)),
    FOR_EACH_ASM_VALUE_TYPE_LIST(DEFINE_TAG)
#undef DEFINE_TAG
        kAsmUnknown = 0,
    kAsmValueTypeTag = 1u
  };
Member Function Documentation
AsValueType()
static AsmValueType* v8::internal::wasm::AsmValueType::AsValueType (AsmType * type) [inline], [static], [private]
Definition at line 76 of file asm-types.h.
                                                  {
    if ((reinterpret_cast<uintptr_t>(type) & kAsmValueTypeTag) ==
        kAsmValueTypeTag) {
      return reinterpret_cast<AsmValueType*>(type);
    }
    return nullptr;
  }
References kAsmValueTypeTag, and v8::internal::tracing::type.
Referenced by v8::internal::wasm::AsmType::AsValueType().
Bitset()
bitset_t v8::internal::wasm::AsmValueType::Bitset () const [inline], [private]
Definition at line 84 of file asm-types.h.
                          {
    DCHECK_EQ(reinterpret_cast<uintptr_t>(this) & kAsmValueTypeTag,
              kAsmValueTypeTag);
    return static_cast<bitset_t>(reinterpret_cast<uintptr_t>(this) &
                                 ~kAsmValueTypeTag);
  }
References DCHECK_EQ, and kAsmValueTypeTag.
Referenced by v8::internal::wasm::AsmType::IsExactly(), and v8::internal::wasm::AsmType::Name().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::wasm::AsmValueType::DISALLOW_IMPLICIT_CONSTRUCTORS (AsmValueType) [private]
New()
static AsmType* v8::internal::wasm::AsmValueType::New (bitset_t bits) [inline], [static], [private]
Definition at line 91 of file asm-types.h.
                                     {
    DCHECK_EQ((bits & kAsmValueTypeTag), 0u);
    return reinterpret_cast<AsmType*>(
        static_cast<uintptr_t>(bits | kAsmValueTypeTag));
  }
References DCHECK_EQ, and kAsmValueTypeTag.
Friends And Related Function Documentation
AsmType
friend class AsmType [friend]
Definition at line 74 of file asm-types.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/asmjs/asm-types.h