v8::internal::BigIntBase Class Reference
#include <bigint.h>
Public Types
using SignBits = base::BitField< bool, 0, 1 >
using LengthBits = SignBits::Next< uint32_t, kLengthFieldBits >
Public Member Functions
uint32_t length () const
uint32_t length (AcquireLoadTag) const
bigint::Digits digits () const
Static Public Attributes
static const uint32_t kMaxLengthBits = 1 << 30
static const uint32_t kMaxLength
static const uint32_t kLengthFieldBits = 30
Private Types
using digit_t = uintptr_t
Private Member Functions
bool sign () const
digit_t digit (uint32_t n) const
bool is_zero () const
FLEXIBLE_ARRAY_MEMBER (UnalignedValueMember< digit_t >, raw_digits)
Private Attributes
std::atomic_uint32_t bitfield_
Static Private Attributes
static const uint32_t kDigitSize = sizeof(digit_t)
static const uint32_t kDigitBits = kDigitSize * kBitsPerByte
static const uint32_t kHalfDigitBits = kDigitBits / 2
static const digit_t kHalfDigitMask = (1ull << kHalfDigitBits) - 1
Friends
class ::v8::internal::BigInt
class MutableBigInt
class FreshlyAllocatedBigInt
struct OffsetsForDebug
class CodeStubAssembler
class maglev::MaglevAssembler
class compiler::AccessBuilder
Detailed Description
Definition at line 88 of file bigint.h.
Member Typedef Documentation
digit_t
using v8::internal::BigIntBase::digit_t = uintptr_t [private]
Definition at line 130 of file bigint.h.
LengthBits
using v8::internal::BigIntBase::LengthBits = SignBits::Next<uint32_t, kLengthFieldBits>
Definition at line 114 of file bigint.h.
SignBits
using v8::internal::BigIntBase::SignBits = base::BitField<bool, 0, 1>
Definition at line 113 of file bigint.h.
Member Function Documentation
digit()
digit_t v8::internal::BigIntBase::digit (uint32_t n) const [inline], [private]
Definition at line 145 of file bigint.h.
                                         {
    SLOW_DCHECK(n < length());
    return raw_digits()[n].value();
  }
References length(), and SLOW_DCHECK.
Referenced by v8::internal::BigInt::BigIntShortPrint(), v8::internal::BigInt::CompareToDouble(), v8::internal::BigInt::FromSerializedDigits(), v8::internal::MutableBigInt::GetRawBits(), v8::internal::BigInt::Hash(), v8::internal::MutableBigInt::NewFromDouble(), v8::internal::BigInt::SerializeDigits(), v8::internal::BigInt::ToString(), and v8::internal::BigInt::ToWordsArray64().
digits()
bigint::Digits v8::internal::BigIntBase::digits () const
Definition at line 142 of file bigint.cc.
                                      {
  return bigint::Digits(reinterpret_cast<const digit_t*>(raw_digits()),
                        length());
}
References length().
Referenced by v8::internal::BigInt::Allocate(), v8::internal::BigInt::FromSerializedDigits(), and v8::internal::MutableBigInt::NewFromDouble().
FLEXIBLE_ARRAY_MEMBER()
v8::internal::BigIntBase::FLEXIBLE_ARRAY_MEMBER (UnalignedValueMember< digit_t > , raw_digits) [private]
is_zero()
bool v8::internal::BigIntBase::is_zero () const [inline], [private]
Definition at line 150 of file bigint.h.
{ return length() == 0; }
References length().
Referenced by v8::internal::MutableBigInt::GetRawBits(), v8::internal::BigInt::Hash(), and v8::internal::BigInt::ToBoolean().
length() [1/2]
uint32_t v8::internal::BigIntBase::length () const [inline]
Definition at line 90 of file bigint.h.
                                 {
    return LengthBits::decode(bitfield_.load(std::memory_order_relaxed));
  }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::MutableBigInt::AbsoluteSubOne(), v8::internal::BigInt::BigIntShortPrint(), v8::internal::MutableBigInt::Copy(), digit(), digits(), v8::internal::BigInt::FromInt64(), v8::internal::BigInt::FromSerializedDigits(), v8::internal::BigInt::FromUint64(), v8::internal::BigInt::FromWords64(), v8::internal::BigInt::GetBitfieldForSerialization(), v8::internal::MutableBigInt::GetRawBits(), v8::internal::BigInt::Hash(), v8::internal::MutableBigInt::initialize_bitfield(), v8::internal::MutableBigInt::InitializeDigits(), is_zero(), v8::internal::MutableBigInt::New(), v8::internal::MutableBigInt::rw_digits(), v8::internal::BigInt::SerializeDigits(), v8::internal::MutableBigInt::set_digit(), v8::internal::BigInt::SizeFor(), v8::internal::BigInt::BodyDescriptor< HandleType >::SizeOf(), v8::internal::BigInt::ToWordsArray64(), and v8::internal::BigInt::Words64Count().
length() [2/2]
uint32_t v8::internal::BigIntBase::length (AcquireLoadTag) const [inline]
Definition at line 95 of file bigint.h.
                                               {
    return LengthBits::decode(bitfield_.load(std::memory_order_acquire));
  }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
sign()
bool v8::internal::BigIntBase::sign () const [inline], [private]
Definition at line 141 of file bigint.h.
                           {
    return SignBits::decode(bitfield_.load(std::memory_order_relaxed));
  }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::MutableBigInt::AbsoluteAddOne(), v8::internal::BigInt::AsInt64(), v8::internal::BigInt::AsUint64(), v8::internal::BigInt::BigIntShortPrint(), v8::internal::BigInt::FromInt64(), v8::internal::BigInt::FromSerializedDigits(), v8::internal::BigInt::GetBitfieldForSerialization(), v8::internal::MutableBigInt::GetRawBits(), v8::internal::BigInt::Hash(), v8::internal::MutableBigInt::initialize_bitfield(), v8::internal::BigInt::IsNegative(), v8::internal::MutableBigInt::NewFromDouble(), v8::internal::MutableBigInt::NewFromInt(), v8::internal::BigInt::ToString(), and v8::internal::BigInt::ToWordsArray64().
Friends And Related Function Documentation
::v8::internal::BigInt
friend class ::v8::internal::BigInt [friend]
Definition at line 121 of file bigint.h.
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 126 of file bigint.h.
compiler::AccessBuilder
friend class compiler::AccessBuilder [friend]
Definition at line 128 of file bigint.h.
FreshlyAllocatedBigInt
friend class FreshlyAllocatedBigInt [friend]
Definition at line 123 of file bigint.h.
maglev::MaglevAssembler
friend class maglev::MaglevAssembler [friend]
Definition at line 127 of file bigint.h.
MutableBigInt
friend class MutableBigInt [friend]
Definition at line 122 of file bigint.h.
OffsetsForDebug
friend struct OffsetsForDebug [friend]
Definition at line 125 of file bigint.h.
Member Data Documentation
bitfield_
std::atomic_uint32_t v8::internal::BigIntBase::bitfield_ [private]
Definition at line 152 of file bigint.h.
Referenced by v8::internal::MutableBigInt::initialize_bitfield(), length(), v8::internal::MutableBigInt::set_length(), v8::internal::MutableBigInt::set_sign(), and sign().
kDigitBits
const uint32_t v8::internal::BigIntBase::kDigitBits = kDigitSize * kBitsPerByte [static], [private]
Definition at line 136 of file bigint.h.
Referenced by v8::internal::BigInt::CompareToDouble(), v8::internal::MutableBigInt::DecideRounding(), v8::internal::BigInt::Exponentiate(), v8::internal::BigInt::FromInt64(), v8::internal::BigInt::FromUint64(), v8::internal::BigInt::FromWords64(), v8::internal::MutableBigInt::GetRawBits(), v8::internal::MutableBigInt::NewFromDouble(), v8::internal::MutableBigInt::set_64_bits(), v8::internal::MutableBigInt::ToDouble(), v8::internal::BigInt::ToString(), v8::internal::BigInt::ToWordsArray64(), and v8::internal::BigInt::Words64Count().
kDigitSize
const uint32_t v8::internal::BigIntBase::kDigitSize = sizeof(digit_t) [static], [private]
Definition at line 132 of file bigint.h.
Referenced by v8::internal::MutableBigInt::Copy(), v8::internal::BigInt::FromSerializedDigits(), v8::internal::BigInt::GetBitfieldForSerialization(), v8::internal::MutableBigInt::InitializeDigits(), v8::internal::BigInt::SerializeDigits(), and v8::internal::BigInt::SizeFor().
kHalfDigitBits
const uint32_t v8::internal::BigIntBase::kHalfDigitBits = kDigitBits / 2 [static], [private]
Definition at line 137 of file bigint.h.
kHalfDigitMask
const digit_t v8::internal::BigIntBase::kHalfDigitMask = (1ull << kHalfDigitBits) - 1 [static], [private]
Definition at line 138 of file bigint.h.
kLengthFieldBits
const uint32_t v8::internal::BigIntBase::kLengthFieldBits = 30 [static]
Definition at line 111 of file bigint.h.
Referenced by v8::internal::RightShiftResultLength().
kMaxLength
const uint32_t v8::internal::BigIntBase::kMaxLength [static]
Initial value:
=
      kMaxLengthBits / (kSystemPointerSize * kBitsPerByte)
Definition at line 106 of file bigint.h.
Referenced by v8::internal::BigInt::Allocate(), v8::internal::BigInt::CompareToDouble(), v8::internal::BigInt::FromWords64(), v8::internal::BigInt::GetBitfieldForSerialization(), v8::internal::CodeStubAssembler::LoadBigIntDigit(), v8::internal::MutableBigInt::New(), v8::internal::FactoryBase< Impl >::NewBigInt(), v8::internal::MutableBigInt::NewFromDouble(), and v8::internal::CodeStubAssembler::StoreBigIntDigit().
kMaxLengthBits
const uint32_t v8::internal::BigIntBase::kMaxLengthBits = 1 << 30 [static]
Definition at line 105 of file bigint.h.
Referenced by v8::internal::BigInt::AsIntN(), v8::internal::BigInt::AsUintN(), v8::internal::BigInt::Exponentiate(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::Scanner::ScanNumber().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/bigint.h
/mnt/V8SourceCode/src/objects/bigint.cc