cppgc::internal::MarkingVerifierBase Class Reference
#include <marking-verifier.h>
Public Member Functions
~MarkingVerifierBase () override=default
MarkingVerifierBase (const MarkingVerifierBase &)=delete
MarkingVerifierBase & operator= (const MarkingVerifierBase &)=delete
void Run (StackState, std::optional< size_t >)
Protected Member Functions
MarkingVerifierBase (HeapBase &, CollectionType, VerificationState &, std::unique_ptr< cppgc::Visitor >)
Private Member Functions
void VisitInConstructionConservatively (HeapObjectHeader &, TraceConservativelyCallback) final
void VisitPointer (const void *) final
bool VisitNormalPage (NormalPage &)
bool VisitLargePage (LargePage &)
bool VisitHeapObjectHeader (HeapObjectHeader &)
void ReportDifferences (size_t) const
void ReportNormalPage (const NormalPage &, size_t) const
void ReportLargePage (const LargePage &, size_t) const
void ReportHeapObjectHeader (const HeapObjectHeader &) const
Private Attributes
VerificationState & verification_state_
std::unique_ptr< cppgc::Visitor > visitor_
std::unordered_set< const HeapObjectHeader * > in_construction_objects_heap_
std::unordered_set< const HeapObjectHeader * > in_construction_objects_stack_
std::unordered_set< const HeapObjectHeader * > * in_construction_objects_
size_t verifier_found_marked_bytes_ = 0
bool verifier_found_marked_bytes_are_exact_ = true
CollectionType collection_type_
size_t verifier_found_marked_bytes_in_pages_ = 0
Friends
class HeapVisitor< MarkingVerifierBase >
Additional Inherited Members
Detailed Description
Definition at line 33 of file marking-verifier.h.
Constructor & Destructor Documentation
 MarkingVerifierBase()
cppgc::internal::MarkingVerifierBase::~MarkingVerifierBase () [override], [default]
MarkingVerifierBase() [1/2]
cppgc::internal::MarkingVerifierBase::MarkingVerifierBase (const MarkingVerifierBase &) [delete]
MarkingVerifierBase() [2/2]
cppgc::internal::MarkingVerifierBase::MarkingVerifierBase (HeapBase & heap, CollectionType collection_type, VerificationState & verification_state, std::unique_ptr< cppgc::Visitor > visitor) [protected]
Definition at line 46 of file marking-verifier.cc.
    : ConservativeTracingVisitor(heap, *heap.page_backend(), *visitor),
      verification_state_(verification_state),
      visitor_(std::move(visitor)),
      collection_type_(collection_type) {}
Member Function Documentation
operator=()
MarkingVerifierBase& cppgc::internal::MarkingVerifierBase::operator= (const MarkingVerifierBase &) [delete]
ReportDifferences()
void cppgc::internal::MarkingVerifierBase::ReportDifferences (size_t expected_marked_bytes) const [private]
Definition at line 179 of file marking-verifier.cc.
                                        {
  v8::base::OS::PrintError("\n<--- Mismatch in marking verifier --->\n");
  v8::base::OS::PrintError(
      "Marked bytes: expected %zu vs. verifier found %zu, difference %zd\n",
      expected_marked_bytes, verifier_found_marked_bytes_,
      expected_marked_bytes - verifier_found_marked_bytes_);
  v8::base::OS::PrintError(
      "A list of pages with possibly mismatched marked objects follows.\n");
  for (auto& space : heap_.raw_heap()) {
    for (auto* page : *space) {
      size_t marked_bytes_on_page = 0;
      if (page->is_large()) {
        const auto& large_page = *LargePage::From(page);
        const auto& header = *large_page.ObjectHeader();
        if (header.IsMarked())
          marked_bytes_on_page +=
              ObjectView<>(header).Size() + sizeof(HeapObjectHeader);
        if (marked_bytes_on_page == large_page.marked_bytes()) continue;
        ReportLargePage(large_page, marked_bytes_on_page);
        ReportHeapObjectHeader(header);
      } else {
        const auto& normal_page = *NormalPage::From(page);
        for (const auto& header : normal_page) {
          if (header.IsMarked())
            marked_bytes_on_page +=
                ObjectView<>(header).Size() + sizeof(HeapObjectHeader);
        }
        if (marked_bytes_on_page == normal_page.marked_bytes()) continue;
        ReportNormalPage(normal_page, marked_bytes_on_page);
        for (const auto& header : normal_page) {
          ReportHeapObjectHeader(header);
        }
      }
    }
  }
}
References cppgc::internal::NormalPage::From(), cppgc::internal::LargePage::From(), cppgc::internal::ConservativeTracingVisitor::heap_, cppgc::internal::HeapBase::raw_heap(), ReportHeapObjectHeader(), ReportLargePage(), ReportNormalPage(), cppgc::internal::ObjectView< AccessMode >::Size(), space, and verifier_found_marked_bytes_.
Referenced by Run().
ReportHeapObjectHeader()
void cppgc::internal::MarkingVerifierBase::ReportHeapObjectHeader (const HeapObjectHeader & header) const [private]
Definition at line 235 of file marking-verifier.cc.
                                          {
  const char* name =
      header.IsFree()
          ? "free space"
          : header
                .GetName(
                    HeapObjectNameForUnnamedObject::kUseClassNameIfSupported)
                .value;
  v8::base::OS::PrintError("- %s at %p, size %zu, %s\n", name,
                           header.ObjectStart(), header.ObjectSize(),
                           header.IsMarked() ? "marked" : "unmarked");
}
References cppgc::internal::HeapObjectHeader::GetName(), cppgc::internal::HeapObjectHeader::IsFree(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::kUseClassNameIfSupported, name, cppgc::internal::HeapObjectHeader::ObjectSize(), cppgc::internal::HeapObjectHeader::ObjectStart(), and cppgc::internal::HeapObjectName::value.
Referenced by ReportDifferences().
ReportLargePage()
void cppgc::internal::MarkingVerifierBase::ReportLargePage (const LargePage & page, size_t marked_bytes_on_page) const [private]
Definition at line 226 of file marking-verifier.cc.
                                                                             {
  v8::base::OS::PrintError(
      "\nLarge page in space %zu:\n"
      "Marked bytes: expected %zu vs. verifier found %zu, difference %zd\n",
      page.space().index(), page.marked_bytes(), marked_bytes_on_page,
      page.marked_bytes() - marked_bytes_on_page);
}
References cppgc::internal::BaseSpace::index(), cppgc::internal::BasePage::marked_bytes(), and cppgc::internal::BasePage::space().
Referenced by ReportDifferences().
ReportNormalPage()
void cppgc::internal::MarkingVerifierBase::ReportNormalPage (const NormalPage & page, size_t marked_bytes_on_page) const [private]
Definition at line 217 of file marking-verifier.cc.
                                                                              {
  v8::base::OS::PrintError(
      "\nNormal page in space %zu:\n"
      "Marked bytes: expected %zu vs. verifier found %zu, difference %zd\n",
      page.space().index(), page.marked_bytes(), marked_bytes_on_page,
      page.marked_bytes() - marked_bytes_on_page);
}
References cppgc::internal::BaseSpace::index(), cppgc::internal::BasePage::marked_bytes(), and cppgc::internal::BasePage::space().
Referenced by ReportDifferences().
Run()
void cppgc::internal::MarkingVerifierBase::Run (StackState stack_state, std::optional< size_t > expected_marked_bytes)
Definition at line 55 of file marking-verifier.cc.
                                                                         {
  Traverse(heap_.raw_heap());
// Avoid verifying the stack when running with TSAN as the TSAN runtime changes
// stack contents when e.g. working with locks. Specifically, the marker uses
// locks in slow path operations which results in stack changes throughout
// marking. This means that the conservative iteration below may find more
// objects then the regular marker. The difference is benign as the delta of
// objects is not reachable from user code but it prevents verification.
// We also avoid verifying the stack when pointer compression is enabled.
// Currently, verification happens after compaction, V8 compaction can change
// slots on stack, which could lead to false positives in verifier. Those are
// more likely with checking compressed pointers on stack.
// TODO(chromium:1325007): Investigate if Oilpan verification can be moved
// before V8 compaction or compaction never runs with stack.
#if !defined(THREAD_SANITIZER) && !defined(CPPGC_POINTER_COMPRESSION)
  if (stack_state == StackState::kMayContainHeapPointers) {
    in_construction_objects_ = &in_construction_objects_stack_;
    heap_.stack()->IteratePointersUntilMarker(this);
    // The objects found through the unsafe iteration are only a subset of the
    // regular iteration as they miss objects held alive only from callee-saved
    // registers that are never pushed on the stack and SafeStack.
    CHECK_LE(in_construction_objects_stack_.size(),
             in_construction_objects_heap_.size());
    for (auto* header : in_construction_objects_stack_) {
      CHECK_NE(in_construction_objects_heap_.end(),
               in_construction_objects_heap_.find(header));
    }
  }
#endif // !defined(THREAD_SANITIZER)
  if (expected_marked_bytes && verifier_found_marked_bytes_are_exact_) {
    // Report differences in marked objects, if possible.
    if (V8_UNLIKELY(expected_marked_bytes.value() !=
                    verifier_found_marked_bytes_) &&
        collection_type_ != CollectionType::kMinor) {
      ReportDifferences(expected_marked_bytes.value());
    }
    CHECK_EQ(expected_marked_bytes.value(), verifier_found_marked_bytes_);
    // Minor GCs use sticky markbits and as such cannot expect that the marked
    // bytes on pages match the marked bytes accumulated by the marker.
    if (collection_type_ != CollectionType::kMinor) {
      CHECK_EQ(expected_marked_bytes.value(),
               verifier_found_marked_bytes_in_pages_);
    }
  }
}
References CHECK_EQ, CHECK_LE, CHECK_NE, collection_type_, cppgc::internal::ConservativeTracingVisitor::heap_, in_construction_objects_, in_construction_objects_heap_, in_construction_objects_stack_, heap::base::Stack::IteratePointersUntilMarker(), cppgc::internal::kMinor, cppgc::internal::HeapBase::raw_heap(), ReportDifferences(), cppgc::internal::HeapBase::stack(), cppgc::internal::HeapVisitor< MarkingVerifierBase >::Traverse(), V8_UNLIKELY, verifier_found_marked_bytes_, verifier_found_marked_bytes_are_exact_, and verifier_found_marked_bytes_in_pages_.
Referenced by v8::internal::CppHeap::CompactAndSweep(), and cppgc::internal::Heap::FinalizeGarbageCollectionImpl().
VisitHeapObjectHeader()
bool cppgc::internal::MarkingVerifierBase::VisitHeapObjectHeader (HeapObjectHeader & header) [private]
Definition at line 139 of file marking-verifier.cc.
                                                                        {
  // Verify only non-free marked objects.
  if (!header.IsMarked()) return true;
  DCHECK(!header.IsFree());
#if defined(CPPGC_YOUNG_GENERATION)
  if (collection_type_ == CollectionType::kMinor) {
    auto& caged_heap = CagedHeap::Instance();
    const auto age = CagedHeapLocalData::Get().age_table.GetAge(
        caged_heap.OffsetFromAddress(header.ObjectStart()));
    if (age == AgeTable::Age::kOld) {
      // Do not verify old objects.
      return true;
    } else if (age == AgeTable::Age::kMixed) {
      // If the age is not known, the marked bytes may not be exact as possibly
      // old objects are verified as well.
      verifier_found_marked_bytes_are_exact_ = false;
    }
    // Verify young and unknown objects.
  }
#endif // defined(CPPGC_YOUNG_GENERATION)
  verification_state_.SetCurrentParent(&header);
  if (!header.IsInConstruction()) {
    header.TraceImpl(visitor_.get());
  } else {
    // Dispatches to conservative tracing implementation.
    TraceConservativelyIfNeeded(header);
  }
  verifier_found_marked_bytes_ +=
      ObjectView<>(header).Size() + sizeof(HeapObjectHeader);
  verification_state_.SetCurrentParent(nullptr);
  return true;
}
References collection_type_, DCHECK, v8::internal::compiler::turboshaft::Get(), cppgc::internal::CagedHeap::Instance(), cppgc::internal::HeapObjectHeader::IsFree(), cppgc::internal::HeapObjectHeader::IsInConstruction(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::kMinor, cppgc::internal::HeapObjectHeader::ObjectStart(), cppgc::internal::VerificationState::SetCurrentParent(), cppgc::internal::ObjectView< AccessMode >::Size(), cppgc::internal::ConservativeTracingVisitor::TraceConservativelyIfNeeded(), cppgc::internal::HeapObjectHeader::TraceImpl(), verification_state_, verifier_found_marked_bytes_, verifier_found_marked_bytes_are_exact_, and visitor_.
VisitInConstructionConservatively()
void cppgc::internal::MarkingVerifierBase::VisitInConstructionConservatively (HeapObjectHeader & header, TraceConservativelyCallback callback) [final], [private], [virtual]
Reimplemented from cppgc::internal::ConservativeTracingVisitor.
Definition at line 102 of file marking-verifier.cc.
                                                                    {
  if (in_construction_objects_->find(&header) !=
      in_construction_objects_->end())
    return;
  in_construction_objects_->insert(&header);
  // Stack case: Parent is stack and this is merely ensuring that the object
  // itself is marked. If the object is marked, then it is being processed by
  // the on-heap phase.
  if (verification_state_.IsParentOnStack()) {
    verification_state_.VerifyMarked(header.ObjectStart());
    return;
  }
  // Heap case: Dispatching parent object that must be marked (pre-condition).
  CHECK(header.IsMarked());
  callback(this, header);
}
References CHECK, in_construction_objects_, cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::VerificationState::IsParentOnStack(), cppgc::internal::HeapObjectHeader::ObjectStart(), verification_state_, and cppgc::internal::VerificationState::VerifyMarked().
VisitLargePage()
bool cppgc::internal::MarkingVerifierBase::VisitLargePage (LargePage & page) [private]
Definition at line 134 of file marking-verifier.cc.
                                                        {
  verifier_found_marked_bytes_in_pages_ += page.marked_bytes();
  return false; // Continue visitation.
}
References cppgc::internal::BasePage::marked_bytes(), and verifier_found_marked_bytes_in_pages_.
VisitNormalPage()
bool cppgc::internal::MarkingVerifierBase::VisitNormalPage (NormalPage & page) [private]
Definition at line 129 of file marking-verifier.cc.
                                                          {
  verifier_found_marked_bytes_in_pages_ += page.marked_bytes();
  return false; // Continue visitation.
}
References cppgc::internal::BasePage::marked_bytes(), and verifier_found_marked_bytes_in_pages_.
VisitPointer()
void cppgc::internal::MarkingVerifierBase::VisitPointer (const void * address) [final], [private], [virtual]
Implements heap::base::StackVisitor.
Definition at line 122 of file marking-verifier.cc.
                                                          {
  // Entry point for stack walk. The conservative visitor dispatches as follows:
  // - Fully constructed objects: Visit()
  // - Objects in construction: VisitInConstructionConservatively()
  TraceConservativelyIfNeeded(address);
}
References cppgc::internal::ConservativeTracingVisitor::TraceConservativelyIfNeeded().
Friends And Related Function Documentation
HeapVisitor< MarkingVerifierBase >
friend class HeapVisitor< MarkingVerifierBase > [friend]
Definition at line 30 of file marking-verifier.h.
Member Data Documentation
collection_type_
CollectionType cppgc::internal::MarkingVerifierBase::collection_type_ [private]
Definition at line 74 of file marking-verifier.h.
Referenced by Run(), and VisitHeapObjectHeader().
in_construction_objects_
std::unordered_set<const HeapObjectHeader*>* cppgc::internal::MarkingVerifierBase::in_construction_objects_ [private]
Initial value:
=
      &in_construction_objects_heap_
Definition at line 70 of file marking-verifier.h.
Referenced by Run(), and VisitInConstructionConservatively().
in_construction_objects_heap_
std::unordered_set<const HeapObjectHeader*> cppgc::internal::MarkingVerifierBase::in_construction_objects_heap_ [private]
Definition at line 68 of file marking-verifier.h.
Referenced by Run().
in_construction_objects_stack_
std::unordered_set<const HeapObjectHeader*> cppgc::internal::MarkingVerifierBase::in_construction_objects_stack_ [private]
Definition at line 69 of file marking-verifier.h.
Referenced by Run().
verification_state_
VerificationState& cppgc::internal::MarkingVerifierBase::verification_state_ [private]
Definition at line 65 of file marking-verifier.h.
Referenced by VisitHeapObjectHeader(), and VisitInConstructionConservatively().
verifier_found_marked_bytes_
size_t cppgc::internal::MarkingVerifierBase::verifier_found_marked_bytes_ = 0 [private]
Definition at line 72 of file marking-verifier.h.
Referenced by ReportDifferences(), Run(), and VisitHeapObjectHeader().
verifier_found_marked_bytes_are_exact_
bool cppgc::internal::MarkingVerifierBase::verifier_found_marked_bytes_are_exact_ = true [private]
Definition at line 73 of file marking-verifier.h.
Referenced by Run(), and VisitHeapObjectHeader().
verifier_found_marked_bytes_in_pages_
size_t cppgc::internal::MarkingVerifierBase::verifier_found_marked_bytes_in_pages_ = 0 [private]
Definition at line 75 of file marking-verifier.h.
Referenced by Run(), VisitLargePage(), and VisitNormalPage().
visitor_
std::unique_ptr<cppgc::Visitor> cppgc::internal::MarkingVerifierBase::visitor_ [private]
Definition at line 66 of file marking-verifier.h.
Referenced by VisitHeapObjectHeader().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/marking-verifier.h
/mnt/V8SourceCode/src/heap/cppgc/marking-verifier.cc