v8::internal::torque::Namespace Class Reference
#include <declarable.h>
Public Member Functions
Namespace (const std::string &name)
const std::string & name () const
bool IsDefaultNamespace () const
bool IsTestNamespace () const
Private Attributes
std::string name_
Additional Inherited Members
Detailed Description
Definition at line 217 of file declarable.h.
Constructor & Destructor Documentation
Namespace()
v8::internal::torque::Namespace::Namespace (const std::string & name) [inline], [explicit]
Definition at line 220 of file declarable.h.
      : Scope(Declarable::kNamespace), name_(name) {}
Member Function Documentation
IsDefaultNamespace()
bool v8::internal::torque::Namespace::IsDefaultNamespace () const
Definition at line 174 of file declarable.cc.
                                         {
  return this == GlobalContext::GetDefaultNamespace();
}
References v8::internal::torque::GlobalContext::GetDefaultNamespace().
IsTestNamespace()
bool v8::internal::torque::Namespace::IsTestNamespace () const
Definition at line 178 of file declarable.cc.
{ return name() == kTestNamespaceName; }
References v8::internal::torque::kTestNamespaceName, and name().
name()
const std::string& v8::internal::torque::Namespace::name () const [inline]
Definition at line 222 of file declarable.h.
{ return name_; }
References name_.
Referenced by IsTestNamespace().
Member Data Documentation
name_
std::string v8::internal::torque::Namespace::name_ [private]
Definition at line 227 of file declarable.h.
Referenced by name().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/declarable.h
/mnt/V8SourceCode/src/torque/declarable.cc