cppgc::internal::LivenessBrokerFactory Class Reference
#include <liveness-broker.h>
Static Public Member Functions
static LivenessBroker Create ()
Detailed Description
Definition at line 14 of file liveness-broker.h.
Member Function Documentation
Create()
cppgc::LivenessBroker cppgc::internal::LivenessBrokerFactory::Create () [static]
Definition at line 18 of file liveness-broker.cc.
                                                  {
  return cppgc::LivenessBroker();
}
Referenced by cppgc::internal::PreFinalizerHandler::InvokePreFinalizers(), cppgc::internal::MutatorMarkingState::InvokeWeakRootsCallbackIfNeeded(), and cppgc::internal::MarkerBase::ProcessWeakness().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/liveness-broker.h
/mnt/V8SourceCode/src/heap/cppgc/liveness-broker.cc