v8::internal::WasmJSFunctionData Class Reference
#include <wasm-objects.h>
Classes
class OffheapData
Public Types
using BodyDescriptor = StackedBodyDescriptor< SubclassBodyDescriptor< WasmFunctionData::BodyDescriptor, FixedBodyDescriptorFor< WasmJSFunctionData > >, WithProtectedPointer< kProtectedOffheapDataOffset > >
Public Member Functions
DECL_PROTECTED_POINTER_ACCESSORS (protected_offheap_data, TrustedManaged< OffheapData >) inline OffheapData *offheap_data() const
Tagged< JSReceiver > GetCallable () const
wasm::Suspend GetSuspend () const
const wasm::CanonicalSig * GetSignature () const
wasm::CanonicalTypeIndex sig_index () const
bool MatchesSignature (wasm::CanonicalTypeIndex other_canonical_sig_index) const
Detailed Description
Definition at line 1209 of file wasm-objects.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::WasmJSFunctionData::BodyDescriptor = StackedBodyDescriptor< SubclassBodyDescriptor<WasmFunctionData::BodyDescriptor, FixedBodyDescriptorFor<WasmJSFunctionData> >, WithProtectedPointer<kProtectedOffheapDataOffset> >
Definition at line 1247 of file wasm-objects.h.
Member Function Documentation
DECL_PROTECTED_POINTER_ACCESSORS()
v8::internal::WasmJSFunctionData::DECL_PROTECTED_POINTER_ACCESSORS (protected_offheap_data , TrustedManaged< OffheapData >) const
GetCallable()
Tagged< JSReceiver > v8::internal::WasmJSFunctionData::GetCallable () const
Definition at line 3273 of file wasm-objects.cc.
                                                         {
  return Cast<JSReceiver>(
      Cast<WasmImportData>(internal()->implicit_arg())->callable());
}
GetSignature()
const wasm::CanonicalSig * v8::internal::WasmJSFunctionData::GetSignature () const
Definition at line 3282 of file wasm-objects.cc.
                                                               {
  return wasm::GetWasmEngine()->type_canonicalizer()->LookupFunctionSignature(
      sig_index());
}
References v8::internal::wasm::GetWasmEngine(), v8::internal::wasm::TypeCanonicalizer::LookupFunctionSignature(), sig_index(), and v8::internal::wasm::WasmEngine::type_canonicalizer().
Referenced by MatchesSignature().
GetSuspend()
wasm::Suspend v8::internal::WasmJSFunctionData::GetSuspend () const
Definition at line 3278 of file wasm-objects.cc.
                                                 {
  return Cast<WasmImportData>(internal()->implicit_arg())->suspend();
}
MatchesSignature()
bool v8::internal::WasmJSFunctionData::MatchesSignature (wasm::CanonicalTypeIndex other_canonical_sig_index) const
Definition at line 3287 of file wasm-objects.cc.
                                                            {
#if DEBUG
  // TODO(14034): Change this if indexed types are allowed.
  const wasm::CanonicalSig* sig = GetSignature();
  for (wasm::CanonicalValueType type : sig->all()) CHECK(!type.has_index());
#endif
  // TODO(14034): Check for subtyping instead if WebAssembly.Function can define
  // signature supertype.
  return sig_index() == other_canonical_sig_index;
}
References CHECK, GetSignature(), v8::internal::sig, sig_index(), and v8::internal::tracing::type.
sig_index()
wasm::CanonicalTypeIndex v8::internal::WasmJSFunctionData::sig_index () const [inline]
Definition at line 492 of file wasm-objects-inl.h.
                                                           {
  return wasm::CanonicalTypeIndex{static_cast<uint32_t>(canonical_sig_index())};
}
Referenced by GetSignature(), and MatchesSignature().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects-inl.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc