v8::internal::torque::Worklist< T > Class Template Reference
#include <utils.h>
Public Member Functions
bool IsEmpty () const
bool Enqueue (T value)
T Dequeue ()
Private Attributes
std::queue< T > queue_
std::unordered_set< T > contained_
Detailed Description
template<typename T>
class v8::internal::torque::Worklist< T >
Definition at line 496 of file utils.h.
Member Function Documentation
Dequeue()
template<typename T >
T v8::internal::torque::Worklist< T >::Dequeue () [inline]
Definition at line 511 of file utils.h.
              {
    DCHECK(!IsEmpty());
    T value = queue_.front();
    queue_.pop();
    contained_.erase(value);
    DCHECK_EQ(queue_.size(), contained_.size());
    return value;
  }
References v8::internal::torque::Worklist< T >::contained_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::torque::Worklist< T >::IsEmpty(), v8::internal::torque::Worklist< T >::queue_, and v8::internal::value.
Referenced by v8::internal::torque::CfgAssembler::ComputeInputDefinitions().
Enqueue()
template<typename T >
bool v8::internal::torque::Worklist< T >::Enqueue (T value) [inline]
Definition at line 503 of file utils.h.
                        {
    if (contained_.find(value) != contained_.end()) return false;
    queue_.push(value);
    contained_.insert(value);
    DCHECK_EQ(queue_.size(), contained_.size());
    return true;
  }
References v8::internal::torque::Worklist< T >::contained_, DCHECK_EQ, v8::internal::torque::Worklist< T >::queue_, and v8::internal::value.
Referenced by v8::internal::torque::Block::MergeInputDefinitions().
IsEmpty()
template<typename T >
bool v8::internal::torque::Worklist< T >::IsEmpty () const [inline]
Definition at line 498 of file utils.h.
                       {
    DCHECK_EQ(queue_.size(), contained_.size());
    return queue_.empty();
  }
References v8::internal::torque::Worklist< T >::contained_, DCHECK_EQ, and v8::internal::torque::Worklist< T >::queue_.
Referenced by v8::internal::torque::CfgAssembler::ComputeInputDefinitions(), and v8::internal::torque::Worklist< T >::Dequeue().
Member Data Documentation
contained_
template<typename T >
std::unordered_set<T> v8::internal::torque::Worklist< T >::contained_ [private]
Definition at line 522 of file utils.h.
Referenced by v8::internal::torque::Worklist< T >::Dequeue(), v8::internal::torque::Worklist< T >::Enqueue(), and v8::internal::torque::Worklist< T >::IsEmpty().
queue_
template<typename T >
std::queue<T> v8::internal::torque::Worklist< T >::queue_ [private]
Definition at line 521 of file utils.h.
Referenced by v8::internal::torque::Worklist< T >::Dequeue(), v8::internal::torque::Worklist< T >::Enqueue(), and v8::internal::torque::Worklist< T >::IsEmpty().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/utils.h