v8::debug::Coverage Class Reference
#include <debug-interface.h>
Classes
class BlockData
class FunctionData
class ScriptData
Public Member Functions
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (Coverage)
size_t ScriptCount () const
ScriptData GetScriptData (size_t i) const
bool IsEmpty () const
Static Public Member Functions
static Coverage CollectPrecise (Isolate *isolate)
static Coverage CollectBestEffort (Isolate *isolate)
static void SelectMode (Isolate *isolate, CoverageMode mode)
Private Member Functions
Coverage (std::shared_ptr< i::Coverage > coverage)
Private Attributes
std::shared_ptr< i::Coverage > coverage_
Detailed Description
Definition at line 393 of file debug-interface.h.
Constructor & Destructor Documentation
Coverage()
v8::debug::Coverage::Coverage (std::shared_ptr< i::Coverage > coverage) [inline], [explicit], [private]
Definition at line 474 of file debug-interface.h.
      : coverage_(std::move(coverage)) {}
Referenced by CollectBestEffort(), and CollectPrecise().
Member Function Documentation
CollectBestEffort()
Coverage v8::debug::Coverage::CollectBestEffort (Isolate * isolate) [static]
Definition at line 1385 of file debug-interface.cc.
                                                     {
  return Coverage(
      i::Coverage::CollectBestEffort(reinterpret_cast<i::Isolate*>(isolate)));
}
References v8::internal::Coverage::CollectBestEffort(), and Coverage().
Referenced by v8_inspector::V8ProfilerAgentImpl::getBestEffortCoverage().
CollectPrecise()
Coverage v8::debug::Coverage::CollectPrecise (Isolate * isolate) [static]
Definition at line 1380 of file debug-interface.cc.
                                                  {
  return Coverage(
      i::Coverage::CollectPrecise(reinterpret_cast<i::Isolate*>(isolate)));
}
References v8::internal::Coverage::CollectPrecise(), and Coverage().
Referenced by v8_inspector::V8ProfilerAgentImpl::takePreciseCoverage(), v8_inspector::V8ProfilerAgentImpl::triggerPreciseCoverageDeltaUpdate(), and v8::Shell::WriteLcovData().
GetScriptData()
Coverage::ScriptData v8::debug::Coverage::GetScriptData (size_t i) const
Definition at line 1376 of file debug-interface.cc.
                                                         {
  return ScriptData(i, coverage_);
}
References coverage_.
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), and v8::Shell::WriteLcovData().
IsEmpty()
bool v8::debug::Coverage::IsEmpty () const [inline]
Definition at line 471 of file debug-interface.h.
{ return coverage_ == nullptr; }
References coverage_.
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR()
v8::debug::Coverage::MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (Coverage)
ScriptCount()
size_t v8::debug::Coverage::ScriptCount () const
Definition at line 1374 of file debug-interface.cc.
{ return coverage_->size(); }
References coverage_.
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), and v8::Shell::WriteLcovData().
SelectMode()
void v8::debug::Coverage::SelectMode (Isolate * isolate, CoverageMode mode) [static]
Definition at line 1397 of file debug-interface.cc.
                                                             {
  i::Coverage::SelectMode(reinterpret_cast<i::Isolate*>(isolate), mode);
}
References mode(), and v8::internal::Coverage::SelectMode().
Referenced by v8::Shell::RunMainIsolate(), and v8_inspector::V8ProfilerAgentImpl::stopPreciseCoverage().
Member Data Documentation
coverage_
std::shared_ptr<i::Coverage> v8::debug::Coverage::coverage_ [private]
Definition at line 476 of file debug-interface.h.
Referenced by v8::debug::Coverage::FunctionData::GetBlockData(), v8::debug::Coverage::ScriptData::GetFunctionData(), GetScriptData(), IsEmpty(), and ScriptCount().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-interface.h
/mnt/V8SourceCode/src/debug/debug-interface.cc