v8::internal::compiler::RegisterAllocatorVerifier Class Reference
#include <register-allocator-verifier.h>
Classes
class DelayedAssessments
struct InstructionConstraint
struct OperandConstraint
Public Member Functions
RegisterAllocatorVerifier (Zone *zone, const RegisterConfiguration *config, const InstructionSequence *sequence, const Frame *frame)
RegisterAllocatorVerifier (const RegisterAllocatorVerifier &)=delete
RegisterAllocatorVerifier & operator= (const RegisterAllocatorVerifier &)=delete
void VerifyAssignment (const char *caller_info)
void VerifyGapMoves ()
Private Types
enum ConstraintType {
kConstant
, kImmediate
, kRegister
, kFixedRegister
,
kFPRegister
, kFixedFPRegister
, kSlot
, kFixedSlot
,
kRegisterOrSlot
, kRegisterOrSlotFP
, kRegisterOrSlotOrConstant
, kSameAsInput
,
kRegisterAndSlot
 }
using Constraints = ZoneVector< InstructionConstraint >
Private Member Functions
Zone * zone () const
const RegisterConfiguration * config ()
const InstructionSequence * sequence () const
Constraints * constraints ()
int spill_slot_delta () const
void BuildConstraint (const InstructionOperand *op, OperandConstraint *constraint)
void CheckConstraint (const InstructionOperand *op, const OperandConstraint *constraint)
BlockAssessments * CreateForBlock (const InstructionBlock *block)
void ValidatePendingAssessment (RpoNumber block_id, InstructionOperand op, const BlockAssessments *current_assessments, PendingAssessment *const assessment, int virtual_register)
void ValidateUse (RpoNumber block_id, BlockAssessments *current_assessments, InstructionOperand op, int virtual_register)
Static Private Member Functions
static void VerifyInput (const OperandConstraint &constraint)
static void VerifyTemp (const OperandConstraint &constraint)
static void VerifyOutput (const OperandConstraint &constraint)
Private Attributes
Zone *const zone_
const RegisterConfiguration * config_
const InstructionSequence *const sequence_
Constraints constraints_
ZoneMap< RpoNumber, BlockAssessments * > assessments_
ZoneMap< RpoNumber, DelayedAssessments * > outstanding_assessments_
int spill_slot_delta_
const char * caller_info_ = nullptr
Detailed Description
Definition at line 205 of file register-allocator-verifier.h.
Member Typedef Documentation
Constraints
using v8::internal::compiler::RegisterAllocatorVerifier::Constraints = ZoneVector<InstructionConstraint> [private]
Definition at line 249 of file register-allocator-verifier.h.
Member Enumeration Documentation
ConstraintType
enum v8::internal::compiler::RegisterAllocatorVerifier::ConstraintType [private]
Enumerator
kConstant
kImmediate
kRegister
kFixedRegister
kFPRegister
kFixedFPRegister
kSlot
kFixedSlot
kRegisterOrSlot
kRegisterOrSlotFP
kRegisterOrSlotOrConstant
kSameAsInput
kRegisterAndSlot
Definition at line 218 of file register-allocator-verifier.h.
                      {
    kConstant,
    kImmediate,
    kRegister,
    kFixedRegister,
    kFPRegister,
    kFixedFPRegister,
    kSlot,
    kFixedSlot,
    kRegisterOrSlot,
    kRegisterOrSlotFP,
    kRegisterOrSlotOrConstant,
    kSameAsInput,
    kRegisterAndSlot
  };
Constructor & Destructor Documentation
RegisterAllocatorVerifier() [1/2]
v8::internal::compiler::RegisterAllocatorVerifier::RegisterAllocatorVerifier (Zone * zone, const RegisterConfiguration * config, const InstructionSequence * sequence, const Frame * frame)
Definition at line 63 of file register-allocator-verifier.cc.
    : zone_(zone),
      config_(config),
      sequence_(sequence),
      constraints_(zone),
      assessments_(zone),
      outstanding_assessments_(zone),
      spill_slot_delta_(frame->GetTotalFrameSlotCount() -
                        frame->GetSpillSlotCount()) {
  constraints_.reserve(sequence->instructions().size());
  // TODO(dcarney): model unique constraints.
  // Construct OperandConstraints for all InstructionOperands, eliminating
  // kSameAsInput along the way.
  for (const Instruction* instr : sequence->instructions()) {
    // All gaps should be totally unallocated at this point.
    VerifyEmptyGaps(instr);
    const size_t operand_count = OperandCount(instr);
    OperandConstraint* op_constraints =
        zone->AllocateArray<OperandConstraint>(operand_count);
    size_t count = 0;
    for (size_t i = 0; i < instr->InputCount(); ++i, ++count) {
      BuildConstraint(instr->InputAt(i), &op_constraints[count]);
      VerifyInput(op_constraints[count]);
    }
    for (size_t i = 0; i < instr->TempCount(); ++i, ++count) {
      BuildConstraint(instr->TempAt(i), &op_constraints[count]);
      VerifyTemp(op_constraints[count]);
    }
    for (size_t i = 0; i < instr->OutputCount(); ++i, ++count) {
      BuildConstraint(instr->OutputAt(i), &op_constraints[count]);
      if (op_constraints[count].type_ == kSameAsInput) {
        int input_index = op_constraints[count].value_;
        CHECK_LT(input_index, instr->InputCount());
        op_constraints[count].type_ = op_constraints[input_index].type_;
        op_constraints[count].value_ = op_constraints[input_index].value_;
      }
      VerifyOutput(op_constraints[count]);
    }
    InstructionConstraint instr_constraint = {instr, operand_count,
                                              op_constraints};
    constraints()->push_back(instr_constraint);
  }
}
References v8::internal::Zone::AllocateArray(), BuildConstraint(), CHECK_LT, constraints(), constraints_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::InstructionSequence::instructions(), kSameAsInput, v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::OperandCount(), v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::reserve(), sequence(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::RegisterAllocatorVerifier::OperandConstraint::type_, v8::internal::compiler::RegisterAllocatorVerifier::OperandConstraint::value_, v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::VerifyEmptyGaps(), VerifyInput(), VerifyOutput(), VerifyTemp(), and zone().
RegisterAllocatorVerifier() [2/2]
v8::internal::compiler::RegisterAllocatorVerifier::RegisterAllocatorVerifier (const RegisterAllocatorVerifier &) [delete]
Member Function Documentation
BuildConstraint()
void v8::internal::compiler::RegisterAllocatorVerifier::BuildConstraint (const InstructionOperand * op, OperandConstraint * constraint) [private]
Definition at line 159 of file register-allocator-verifier.cc.
                                                                               {
  constraint->value_ = kMinInt;
  constraint->virtual_register_ = InstructionOperand::kInvalidVirtualRegister;
  if (op->IsConstant()) {
    constraint->type_ = kConstant;
    constraint->value_ = ConstantOperand::cast(op)->virtual_register();
    constraint->virtual_register_ = constraint->value_;
  } else if (op->IsImmediate()) {
    const ImmediateOperand* imm = ImmediateOperand::cast(op);
    constraint->type_ = kImmediate;
    constraint->value_ = GetValue(imm);
  } else {
    CHECK(op->IsUnallocated());
    const UnallocatedOperand* unallocated = UnallocatedOperand::cast(op);
    int vreg = unallocated->virtual_register();
    constraint->virtual_register_ = vreg;
    if (unallocated->basic_policy() == UnallocatedOperand::FIXED_SLOT) {
      constraint->type_ = kFixedSlot;
      constraint->value_ = unallocated->fixed_slot_index();
    } else {
      switch (unallocated->extended_policy()) {
        case UnallocatedOperand::REGISTER_OR_SLOT:
        case UnallocatedOperand::NONE:
          if (sequence()->IsFP(vreg)) {
            constraint->type_ = kRegisterOrSlotFP;
          } else {
            constraint->type_ = kRegisterOrSlot;
          }
          break;
        case UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT:
          DCHECK(!sequence()->IsFP(vreg));
          constraint->type_ = kRegisterOrSlotOrConstant;
          break;
        case UnallocatedOperand::FIXED_REGISTER:
          if (unallocated->HasSecondaryStorage()) {
            constraint->type_ = kRegisterAndSlot;
            constraint->spilled_slot_ = unallocated->GetSecondaryStorage();
          } else {
            constraint->type_ = kFixedRegister;
          }
          constraint->value_ = unallocated->fixed_register_index();
          break;
        case UnallocatedOperand::FIXED_FP_REGISTER:
          constraint->type_ = kFixedFPRegister;
          constraint->value_ = unallocated->fixed_register_index();
          break;
        case UnallocatedOperand::MUST_HAVE_REGISTER:
          if (sequence()->IsFP(vreg)) {
            constraint->type_ = kFPRegister;
          } else {
            constraint->type_ = kRegister;
          }
          break;
        case UnallocatedOperand::MUST_HAVE_SLOT:
          constraint->type_ = kSlot;
          constraint->value_ =
              ElementSizeLog2Of(sequence()->GetRepresentation(vreg));
          break;
        case UnallocatedOperand::SAME_AS_INPUT:
          constraint->type_ = kSameAsInput;
          constraint->value_ = unallocated->input_index();
          break;
      }
    }
  }
}
References v8::internal::compiler::UnallocatedOperand::basic_policy(), CHECK, v8::internal::DCHECK(), v8::internal::ElementSizeLog2Of(), v8::internal::compiler::UnallocatedOperand::extended_policy(), v8::internal::compiler::UnallocatedOperand::FIXED_FP_REGISTER, v8::internal::compiler::UnallocatedOperand::FIXED_REGISTER, v8::internal::compiler::UnallocatedOperand::fixed_register_index(), v8::internal::compiler::UnallocatedOperand::FIXED_SLOT, v8::internal::compiler::UnallocatedOperand::fixed_slot_index(), v8::internal::compiler::UnallocatedOperand::GetSecondaryStorage(), v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::GetValue(), v8::internal::compiler::UnallocatedOperand::HasSecondaryStorage(), v8::internal::compiler::UnallocatedOperand::input_index(), kConstant, kFixedFPRegister, kFixedRegister, kFixedSlot, kFPRegister, kImmediate, v8::internal::compiler::InstructionOperand::kInvalidVirtualRegister, v8::internal::kMinInt, kRegister, kRegisterAndSlot, kRegisterOrSlot, kRegisterOrSlotFP, kRegisterOrSlotOrConstant, kSameAsInput, kSlot, v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, v8::internal::compiler::UnallocatedOperand::MUST_HAVE_SLOT, v8::internal::compiler::UnallocatedOperand::NONE, v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT, v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT, v8::internal::compiler::UnallocatedOperand::SAME_AS_INPUT, sequence(), v8::internal::compiler::RegisterAllocatorVerifier::OperandConstraint::spilled_slot_, v8::internal::compiler::RegisterAllocatorVerifier::OperandConstraint::type_, v8::internal::compiler::RegisterAllocatorVerifier::OperandConstraint::value_, v8::internal::compiler::UnallocatedOperand::virtual_register(), and v8::internal::compiler::RegisterAllocatorVerifier::OperandConstraint::virtual_register_.
Referenced by RegisterAllocatorVerifier().
CheckConstraint()
void v8::internal::compiler::RegisterAllocatorVerifier::CheckConstraint (const InstructionOperand * op, const OperandConstraint * constraint) [private]
Definition at line 227 of file register-allocator-verifier.cc.
                                                                       {
  switch (constraint->type_) {
    case kConstant:
      CHECK_WITH_MSG(op->IsConstant(), caller_info_);
      CHECK_EQ(ConstantOperand::cast(op)->virtual_register(),
               constraint->value_);
      return;
    case kImmediate: {
      CHECK_WITH_MSG(op->IsImmediate(), caller_info_);
      const ImmediateOperand* imm = ImmediateOperand::cast(op);
      int value = GetValue(imm);
      CHECK_EQ(value, constraint->value_);
      return;
    }
    case kRegister:
      CHECK_WITH_MSG(op->IsRegister(), caller_info_);
      return;
    case kFPRegister:
      CHECK_WITH_MSG(op->IsFPRegister(), caller_info_);
      return;
    case kFixedRegister:
    case kRegisterAndSlot:
      CHECK_WITH_MSG(op->IsRegister(), caller_info_);
      CHECK_EQ(LocationOperand::cast(op)->register_code(), constraint->value_);
      return;
    case kFixedFPRegister:
      CHECK_WITH_MSG(op->IsFPRegister(), caller_info_);
      CHECK_EQ(LocationOperand::cast(op)->register_code(), constraint->value_);
      return;
    case kFixedSlot:
      CHECK_WITH_MSG(op->IsStackSlot() || op->IsFPStackSlot(), caller_info_);
      CHECK_EQ(LocationOperand::cast(op)->index(), constraint->value_);
      return;
    case kSlot:
      CHECK_WITH_MSG(op->IsStackSlot() || op->IsFPStackSlot(), caller_info_);
      CHECK_EQ(ElementSizeLog2Of(LocationOperand::cast(op)->representation()),
               constraint->value_);
      return;
    case kRegisterOrSlot:
      CHECK_WITH_MSG(op->IsRegister() || op->IsStackSlot(), caller_info_);
      return;
    case kRegisterOrSlotFP:
      CHECK_WITH_MSG(op->IsFPRegister() || op->IsFPStackSlot(), caller_info_);
      return;
    case kRegisterOrSlotOrConstant:
      CHECK_WITH_MSG(op->IsRegister() || op->IsStackSlot() || op->IsConstant(),
                     caller_info_);
      return;
    case kSameAsInput:
      CHECK_WITH_MSG(false, caller_info_);
      return;
  }
}
References caller_info_, v8::internal::compiler::LocationOperand::cast(), CHECK_EQ, CHECK_WITH_MSG, v8::internal::ElementSizeLog2Of(), v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::GetValue(), v8::internal::index, v8::internal::compiler::InstructionOperand::IsFPRegister(), v8::internal::compiler::InstructionOperand::IsFPStackSlot(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), kConstant, kFixedFPRegister, kFixedRegister, kFixedSlot, kFPRegister, kImmediate, kRegister, kRegisterAndSlot, kRegisterOrSlot, kRegisterOrSlotFP, kRegisterOrSlotOrConstant, kSameAsInput, kSlot, v8::internal::compiler::RegisterAllocatorVerifier::OperandConstraint::type_, v8::internal::value, and v8::internal::compiler::RegisterAllocatorVerifier::OperandConstraint::value_.
Referenced by VerifyAssignment().
config()
const RegisterConfiguration* v8::internal::compiler::RegisterAllocatorVerifier::config () [inline], [private]
Definition at line 273 of file register-allocator-verifier.h.
{ return config_; }
References config_.
constraints()
Constraints* v8::internal::compiler::RegisterAllocatorVerifier::constraints () [inline], [private]
Definition at line 275 of file register-allocator-verifier.h.
{ return &constraints_; }
References constraints_.
Referenced by RegisterAllocatorVerifier(), and VerifyAssignment().
CreateForBlock()
BlockAssessments * v8::internal::compiler::RegisterAllocatorVerifier::CreateForBlock (const InstructionBlock * block) [private]
Definition at line 388 of file register-allocator-verifier.cc.
                                   {
  RpoNumber current_block_id = block->rpo_number();
  BlockAssessments* ret =
      zone()->New<BlockAssessments>(zone(), spill_slot_delta(), sequence_);
  if (block->PredecessorCount() == 0) {
    // TODO(mtrofin): the following check should hold, however, in certain
    // unit tests it is invalidated by the last block. Investigate and
    // normalize the CFG.
    // CHECK_EQ(0, current_block_id.ToInt());
    // The phi size test below is because we can, technically, have phi
    // instructions with one argument. Some tests expose that, too.
  } else if (block->PredecessorCount() == 1 && block->phis().empty()) {
    const BlockAssessments* prev_block = assessments_[block->predecessors()[0]];
    ret->CopyFrom(prev_block);
  } else {
    for (RpoNumber pred_id : block->predecessors()) {
      // For every operand coming from any of the predecessors, create an
      // Unfinalized assessment.
      auto iterator = assessments_.find(pred_id);
      if (iterator == assessments_.end()) {
        // This block is the head of a loop, and this predecessor is the
        // loopback
        // arc.
        // Validate this is a loop case, otherwise the CFG is malformed.
        CHECK(pred_id >= current_block_id);
        CHECK(block->IsLoopHeader());
        continue;
      }
      const BlockAssessments* pred_assessments = iterator->second;
      CHECK_NOT_NULL(pred_assessments);
      for (auto pair : pred_assessments->map()) {
        InstructionOperand operand = pair.first;
        if (ret->map().find(operand) == ret->map().end()) {
          ret->map().insert(std::make_pair(
              operand, zone()->New<PendingAssessment>(zone(), block, operand)));
        }
      }
      // Any references stack slots that became stale in predecessors will be
      // stale here.
      ret->stale_ref_stack_slots().insert(
          pred_assessments->stale_ref_stack_slots().begin(),
          pred_assessments->stale_ref_stack_slots().end());
    }
  }
  return ret;
}
References assessments_, CHECK, CHECK_NOT_NULL, v8::internal::compiler::BlockAssessments::CopyFrom(), v8::internal::ZoneVector< T >::empty(), v8::internal::compiler::InstructionBlock::IsLoopHeader(), v8::internal::compiler::BlockAssessments::map(), v8::internal::Zone::New(), v8::internal::compiler::InstructionBlock::phis(), v8::internal::compiler::InstructionBlock::PredecessorCount(), v8::internal::compiler::InstructionBlock::predecessors(), v8::internal::compiler::InstructionBlock::rpo_number(), sequence_, spill_slot_delta(), v8::internal::compiler::BlockAssessments::stale_ref_stack_slots(), and zone().
Referenced by VerifyGapMoves().
operator=()
RegisterAllocatorVerifier& v8::internal::compiler::RegisterAllocatorVerifier::operator= (const RegisterAllocatorVerifier &) [delete]
sequence()
const InstructionSequence* v8::internal::compiler::RegisterAllocatorVerifier::sequence () const [inline], [private]
Definition at line 274 of file register-allocator-verifier.h.
{ return sequence_; }
References sequence_.
Referenced by BuildConstraint(), RegisterAllocatorVerifier(), VerifyAssignment(), and VerifyGapMoves().
spill_slot_delta()
int v8::internal::compiler::RegisterAllocatorVerifier::spill_slot_delta () const [inline], [private]
Definition at line 276 of file register-allocator-verifier.h.
{ return spill_slot_delta_; }
References spill_slot_delta_.
Referenced by CreateForBlock().
ValidatePendingAssessment()
void v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment (RpoNumber block_id, InstructionOperand op, const BlockAssessments * current_assessments, PendingAssessment *const assessment, int virtual_register) [private]
Definition at line 438 of file register-allocator-verifier.cc.
                                                               {
  if (assessment->IsAliasOf(virtual_register)) return;
  // When validating a pending assessment, it is possible some of the
  // assessments for the original operand (the one where the assessment was
  // created for first) are also pending. To avoid recursion, we use a work
  // list. To deal with cycles, we keep a set of seen nodes.
  Zone local_zone(zone()->allocator(), ZONE_NAME);
  ZoneQueue<std::pair<const PendingAssessment*, int>> worklist(&local_zone);
  ZoneSet<RpoNumber> seen(&local_zone);
  worklist.push(std::make_pair(assessment, virtual_register));
  seen.insert(block_id);
  while (!worklist.empty()) {
    auto work = worklist.front();
    const PendingAssessment* current_assessment = work.first;
    int current_virtual_register = work.second;
    InstructionOperand current_operand = current_assessment->operand();
    worklist.pop();
    const InstructionBlock* origin = current_assessment->origin();
    CHECK(origin->PredecessorCount() > 1 || !origin->phis().empty());
    // Check if the virtual register is a phi first, instead of relying on
    // the incoming assessments. In particular, this handles the case
    // v1 = phi v0 v0, which structurally is identical to v0 having been
    // defined at the top of a diamond, and arriving at the node joining the
    // diamond's branches.
    const PhiInstruction* phi = nullptr;
    for (const PhiInstruction* candidate : origin->phis()) {
      if (candidate->virtual_register() == current_virtual_register) {
        phi = candidate;
        break;
      }
    }
    int op_index = 0;
    for (RpoNumber pred : origin->predecessors()) {
      int expected =
          phi != nullptr ? phi->operands()[op_index] : current_virtual_register;
      ++op_index;
      auto pred_assignment = assessments_.find(pred);
      if (pred_assignment == assessments_.end()) {
        CHECK(origin->IsLoopHeader());
        auto [todo_iter, inserted] = outstanding_assessments_.try_emplace(pred);
        DelayedAssessments*& set = todo_iter->second;
        if (inserted) {
          set = zone()->New<DelayedAssessments>(zone());
        }
        set->AddDelayedAssessment(current_operand, expected);
        continue;
      }
      const BlockAssessments* pred_assessments = pred_assignment->second;
      auto found_contribution = pred_assessments->map().find(current_operand);
      CHECK(found_contribution != pred_assessments->map().end());
      Assessment* contribution = found_contribution->second;
      switch (contribution->kind()) {
        case Final:
          CHECK_EQ(FinalAssessment::cast(contribution)->virtual_register(),
                   expected);
          break;
        case Pending: {
          // This happens if we have a diamond feeding into another one, and
          // the inner one never being used - other than for carrying the value.
          const PendingAssessment* next = PendingAssessment::cast(contribution);
          auto [it, inserted] = seen.insert(pred);
          if (inserted) {
            worklist.push({next, expected});
          }
          // Note that we do not want to finalize pending assessments at the
          // beginning of a block - which is the information we'd have
          // available here. This is because this operand may be reused to
          // define duplicate phis.
          break;
        }
      }
    }
  }
  assessment->AddAlias(virtual_register);
}
References v8::internal::compiler::PendingAssessment::AddAlias(), v8::internal::compiler::RegisterAllocatorVerifier::DelayedAssessments::AddDelayedAssessment(), assessments_, v8::internal::compiler::PendingAssessment::cast(), v8::internal::compiler::FinalAssessment::cast(), CHECK, CHECK_EQ, v8::internal::ZoneVector< T >::empty(), v8::internal::compiler::Final, v8::internal::compiler::PendingAssessment::IsAliasOf(), v8::internal::compiler::InstructionBlock::IsLoopHeader(), v8::internal::compiler::Assessment::kind(), v8::internal::compiler::BlockAssessments::map(), v8::internal::Zone::New(), v8::internal::compiler::PendingAssessment::operand(), v8::internal::compiler::PhiInstruction::operands(), v8::internal::compiler::PendingAssessment::origin(), outstanding_assessments_, v8::internal::compiler::Pending, v8::internal::compiler::InstructionBlock::phis(), v8::internal::compiler::InstructionBlock::PredecessorCount(), v8::internal::compiler::InstructionBlock::predecessors(), zone(), and ZONE_NAME.
Referenced by ValidateUse(), and VerifyGapMoves().
ValidateUse()
void v8::internal::compiler::RegisterAllocatorVerifier::ValidateUse (RpoNumber block_id, BlockAssessments * current_assessments, InstructionOperand op, int virtual_register) [private]
Definition at line 525 of file register-allocator-verifier.cc.
                                                 {
  auto iterator = current_assessments->map().find(op);
  // We should have seen this operand before.
  CHECK(iterator != current_assessments->map().end());
  Assessment* assessment = iterator->second;
  // The operand shouldn't be a stale reference stack slot.
  CHECK(!current_assessments->IsStaleReferenceStackSlot(op, virtual_register));
  switch (assessment->kind()) {
    case Final:
      CHECK_EQ(FinalAssessment::cast(assessment)->virtual_register(),
               virtual_register);
      break;
    case Pending: {
      PendingAssessment* pending = PendingAssessment::cast(assessment);
      ValidatePendingAssessment(block_id, op, current_assessments, pending,
                                virtual_register);
      break;
    }
  }
}
References v8::internal::compiler::PendingAssessment::cast(), v8::internal::compiler::FinalAssessment::cast(), CHECK, CHECK_EQ, v8::internal::compiler::Final, v8::internal::compiler::BlockAssessments::IsStaleReferenceStackSlot(), v8::internal::compiler::Assessment::kind(), v8::internal::compiler::BlockAssessments::map(), v8::internal::compiler::Pending, and ValidatePendingAssessment().
Referenced by VerifyGapMoves().
VerifyAssignment()
void v8::internal::compiler::RegisterAllocatorVerifier::VerifyAssignment (const char * caller_info)
Definition at line 132 of file register-allocator-verifier.cc.
                                                                        {
  caller_info_ = caller_info;
  CHECK(sequence()->instructions().size() == constraints()->size());
  auto instr_it = sequence()->begin();
  for (const auto& instr_constraint : *constraints()) {
    const Instruction* instr = instr_constraint.instruction_;
    // All gaps should be totally allocated at this point.
    VerifyAllocatedGaps(instr, caller_info_);
    const size_t operand_count = instr_constraint.operand_constaints_size_;
    const OperandConstraint* op_constraints =
        instr_constraint.operand_constraints_;
    CHECK_EQ(instr, *instr_it);
    CHECK(operand_count == OperandCount(instr));
    size_t count = 0;
    for (size_t i = 0; i < instr->InputCount(); ++i, ++count) {
      CheckConstraint(instr->InputAt(i), &op_constraints[count]);
    }
    for (size_t i = 0; i < instr->TempCount(); ++i, ++count) {
      CheckConstraint(instr->TempAt(i), &op_constraints[count]);
    }
    for (size_t i = 0; i < instr->OutputCount(); ++i, ++count) {
      CheckConstraint(instr->OutputAt(i), &op_constraints[count]);
    }
    ++instr_it;
  }
}
References v8::internal::compiler::InstructionSequence::begin(), caller_info_, CHECK, CHECK_EQ, CheckConstraint(), constraints(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::Instruction::InputCount(), v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::OperandCount(), v8::internal::compiler::Instruction::OutputAt(), v8::internal::compiler::Instruction::OutputCount(), sequence(), size(), v8::internal::compiler::Instruction::TempAt(), v8::internal::compiler::Instruction::TempCount(), and v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::VerifyAllocatedGaps().
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
VerifyGapMoves()
void v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves ()
Definition at line 550 of file register-allocator-verifier.cc.
                                               {
  CHECK(assessments_.empty());
  CHECK(outstanding_assessments_.empty());
  const size_t block_count = sequence()->instruction_blocks().size();
  for (size_t block_index = 0; block_index < block_count; ++block_index) {
    const InstructionBlock* block =
        sequence()->instruction_blocks()[block_index];
    BlockAssessments* block_assessments = CreateForBlock(block);
    for (int instr_index = block->code_start(); instr_index < block->code_end();
         ++instr_index) {
      const InstructionConstraint& instr_constraint = constraints_[instr_index];
      const Instruction* instr = instr_constraint.instruction_;
      block_assessments->PerformMoves(instr);
      const OperandConstraint* op_constraints =
          instr_constraint.operand_constraints_;
      size_t count = 0;
      for (size_t i = 0; i < instr->InputCount(); ++i, ++count) {
        if (op_constraints[count].type_ == kImmediate) {
          continue;
        }
        int virtual_register = op_constraints[count].virtual_register_;
        InstructionOperand op = *instr->InputAt(i);
        ValidateUse(block->rpo_number(), block_assessments, op,
                    virtual_register);
      }
      for (size_t i = 0; i < instr->TempCount(); ++i, ++count) {
        block_assessments->Drop(*instr->TempAt(i));
      }
      if (instr->IsCall()) {
        block_assessments->DropRegisters();
      }
      if (instr->HasReferenceMap()) {
        block_assessments->CheckReferenceMap(instr->reference_map());
      }
      for (size_t i = 0; i < instr->OutputCount(); ++i, ++count) {
        int virtual_register = op_constraints[count].virtual_register_;
        block_assessments->AddDefinition(*instr->OutputAt(i), virtual_register);
        if (op_constraints[count].type_ == kRegisterAndSlot) {
          const AllocatedOperand* reg_op =
              AllocatedOperand::cast(instr->OutputAt(i));
          MachineRepresentation rep = reg_op->representation();
          const AllocatedOperand* stack_op = AllocatedOperand::New(
              zone(), LocationOperand::LocationKind::STACK_SLOT, rep,
              op_constraints[i].spilled_slot_);
          block_assessments->AddDefinition(*stack_op, virtual_register);
        }
      }
    }
    // Now commit the assessments for this block. If there are any delayed
    // assessments, ValidatePendingAssessment should see this block, too.
    assessments_[block->rpo_number()] = block_assessments;
    auto todo_iter = outstanding_assessments_.find(block->rpo_number());
    if (todo_iter == outstanding_assessments_.end()) continue;
    DelayedAssessments* todo = todo_iter->second;
    for (auto pair : todo->map()) {
      InstructionOperand op = pair.first;
      int vreg = pair.second;
      auto found_op = block_assessments->map().find(op);
      CHECK(found_op != block_assessments->map().end());
      // This block is a jump back to the loop header, ensure that the op hasn't
      // become a stale reference during the blocks in the loop.
      CHECK(!block_assessments->IsStaleReferenceStackSlot(op, vreg));
      switch (found_op->second->kind()) {
        case Final:
          CHECK_EQ(FinalAssessment::cast(found_op->second)->virtual_register(),
                   vreg);
          break;
        case Pending:
          ValidatePendingAssessment(block->rpo_number(), op, block_assessments,
                                    PendingAssessment::cast(found_op->second),
                                    vreg);
          break;
      }
    }
  }
}
References v8::internal::compiler::BlockAssessments::AddDefinition(), assessments_, v8::internal::compiler::PendingAssessment::cast(), v8::internal::compiler::FinalAssessment::cast(), v8::internal::compiler::LocationOperand::cast(), CHECK, CHECK_EQ, v8::internal::compiler::BlockAssessments::CheckReferenceMap(), v8::internal::compiler::InstructionBlock::code_start(), constraints_, CreateForBlock(), v8::internal::compiler::BlockAssessments::Drop(), v8::internal::compiler::BlockAssessments::DropRegisters(), v8::internal::compiler::Final, v8::internal::compiler::Instruction::HasReferenceMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::Instruction::InputCount(), v8::internal::compiler::RegisterAllocatorVerifier::InstructionConstraint::instruction_, v8::internal::compiler::InstructionSequence::instruction_blocks(), v8::internal::compiler::Instruction::IsCall(), v8::internal::compiler::BlockAssessments::IsStaleReferenceStackSlot(), kImmediate, kRegisterAndSlot, v8::internal::compiler::BlockAssessments::map(), v8::internal::compiler::RegisterAllocatorVerifier::DelayedAssessments::map(), v8::internal::compiler::AllocatedOperand::New(), v8::internal::compiler::RegisterAllocatorVerifier::InstructionConstraint::operand_constraints_, v8::internal::compiler::Instruction::OutputAt(), v8::internal::compiler::Instruction::OutputCount(), outstanding_assessments_, v8::internal::compiler::Pending, v8::internal::compiler::BlockAssessments::PerformMoves(), v8::internal::compiler::Instruction::reference_map(), v8::internal::compiler::LocationOperand::representation(), v8::internal::compiler::InstructionBlock::rpo_number(), sequence(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::Instruction::TempAt(), v8::internal::compiler::Instruction::TempCount(), ValidatePendingAssessment(), ValidateUse(), v8::internal::compiler::FinalAssessment::virtual_register(), v8::internal::compiler::RegisterAllocatorVerifier::OperandConstraint::virtual_register_, and zone().
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
VerifyInput()
void v8::internal::compiler::RegisterAllocatorVerifier::VerifyInput (const OperandConstraint & constraint) [static], [private]
Definition at line 109 of file register-allocator-verifier.cc.
                                         {
  CHECK_NE(kSameAsInput, constraint.type_);
  if (constraint.type_ != kImmediate) {
    CHECK_NE(InstructionOperand::kInvalidVirtualRegister,
             constraint.virtual_register_);
  }
}
References CHECK_NE, kImmediate, v8::internal::compiler::InstructionOperand::kInvalidVirtualRegister, kSameAsInput, v8::internal::compiler::RegisterAllocatorVerifier::OperandConstraint::type_, and v8::internal::compiler::RegisterAllocatorVerifier::OperandConstraint::virtual_register_.
Referenced by RegisterAllocatorVerifier().
VerifyOutput()
void v8::internal::compiler::RegisterAllocatorVerifier::VerifyOutput (const OperandConstraint & constraint) [static], [private]
Definition at line 125 of file register-allocator-verifier.cc.
                                         {
  CHECK_NE(kImmediate, constraint.type_);
  CHECK_NE(InstructionOperand::kInvalidVirtualRegister,
           constraint.virtual_register_);
}
References CHECK_NE, kImmediate, v8::internal::compiler::InstructionOperand::kInvalidVirtualRegister, v8::internal::compiler::RegisterAllocatorVerifier::OperandConstraint::type_, and v8::internal::compiler::RegisterAllocatorVerifier::OperandConstraint::virtual_register_.
Referenced by RegisterAllocatorVerifier().
VerifyTemp()
void v8::internal::compiler::RegisterAllocatorVerifier::VerifyTemp (const OperandConstraint & constraint) [static], [private]
Definition at line 118 of file register-allocator-verifier.cc.
                                         {
  CHECK_NE(kSameAsInput, constraint.type_);
  CHECK_NE(kImmediate, constraint.type_);
  CHECK_NE(kConstant, constraint.type_);
}
References CHECK_NE, kConstant, kImmediate, kSameAsInput, and v8::internal::compiler::RegisterAllocatorVerifier::OperandConstraint::type_.
Referenced by RegisterAllocatorVerifier().
zone()
Zone* v8::internal::compiler::RegisterAllocatorVerifier::zone () const [inline], [private]
Definition at line 272 of file register-allocator-verifier.h.
{ return zone_; }
References zone_.
Referenced by CreateForBlock(), RegisterAllocatorVerifier(), ValidatePendingAssessment(), and VerifyGapMoves().
Member Data Documentation
assessments_
ZoneMap<RpoNumber, BlockAssessments*> v8::internal::compiler::RegisterAllocatorVerifier::assessments_ [private]
Definition at line 301 of file register-allocator-verifier.h.
Referenced by CreateForBlock(), ValidatePendingAssessment(), and VerifyGapMoves().
caller_info_
const char* v8::internal::compiler::RegisterAllocatorVerifier::caller_info_ = nullptr [private]
Definition at line 305 of file register-allocator-verifier.h.
Referenced by CheckConstraint(), and VerifyAssignment().
config_
const RegisterConfiguration* v8::internal::compiler::RegisterAllocatorVerifier::config_ [private]
Definition at line 298 of file register-allocator-verifier.h.
Referenced by config().
constraints_
Constraints v8::internal::compiler::RegisterAllocatorVerifier::constraints_ [private]
Definition at line 300 of file register-allocator-verifier.h.
Referenced by constraints(), RegisterAllocatorVerifier(), and VerifyGapMoves().
outstanding_assessments_
ZoneMap<RpoNumber, DelayedAssessments*> v8::internal::compiler::RegisterAllocatorVerifier::outstanding_assessments_ [private]
Definition at line 302 of file register-allocator-verifier.h.
Referenced by ValidatePendingAssessment(), and VerifyGapMoves().
sequence_
const InstructionSequence* const v8::internal::compiler::RegisterAllocatorVerifier::sequence_ [private]
Definition at line 299 of file register-allocator-verifier.h.
Referenced by CreateForBlock(), and sequence().
spill_slot_delta_
int v8::internal::compiler::RegisterAllocatorVerifier::spill_slot_delta_ [private]
Definition at line 303 of file register-allocator-verifier.h.
Referenced by spill_slot_delta().
zone_
Zone* const v8::internal::compiler::RegisterAllocatorVerifier::zone_ [private]
Definition at line 297 of file register-allocator-verifier.h.
Referenced by zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator-verifier.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator-verifier.cc