v8::internal::compiler::JSPrimitiveWrapperRef Class Reference
#include <heap-refs.h>
Public Member Functions
bool IsStringWrapper (JSHeapBroker *broker) const
IndirectHandle< JSPrimitiveWrapper > object () const
Detailed Description
Definition at line 1242 of file heap-refs.h.
Member Function Documentation
IsStringWrapper()
bool v8::internal::compiler::JSPrimitiveWrapperRef::IsStringWrapper (JSHeapBroker * broker) const
Definition at line 1866 of file heap-refs.cc.
                                                                      {
  auto elements_kind = map(broker).elements_kind();
  return elements_kind == FAST_STRING_WRAPPER_ELEMENTS ||
         elements_kind == SLOW_STRING_WRAPPER_ELEMENTS;
}
References broker(), v8::internal::compiler::MapRef::elements_kind(), v8::internal::FAST_STRING_WRAPPER_ELEMENTS, v8::internal::compiler::HeapObjectRef::map(), and v8::internal::SLOW_STRING_WRAPPER_ELEMENTS.
object()
IndirectHandle<JSPrimitiveWrapper> v8::internal::compiler::JSPrimitiveWrapperRef::object () const
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc