v8::internal::TurbofanJSFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
int ComputeParametersCount () const override
void Iterate (RootVisitor *v) const override
int FindReturnPCForTrampoline (Tagged< Code > code, int trampoline_pc) const override
Protected Member Functions
TurbofanJSFrame (StackFrameIteratorBase *iterator)
Private Member Functions
Tagged< Object > StackSlotAt (int index) const
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 1217 of file frames.h.
Constructor & Destructor Documentation
TurbofanJSFrame()
v8::internal::TurbofanJSFrame::TurbofanJSFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 318 of file frames-inl.h.
    : OptimizedJSFrame(iterator) {}
Member Function Documentation
ComputeParametersCount()
int v8::internal::TurbofanJSFrame::ComputeParametersCount () const [override], [virtual]
Reimplemented from v8::internal::CommonFrameWithJSLinkage.
Definition at line 2418 of file frames.cc.
                                                  {
  if (GcSafeLookupCode()->kind() == CodeKind::BUILTIN) {
    return static_cast<int>(
               Memory<intptr_t>(fp() + StandardFrameConstants::kArgCOffset)) -
           kJSArgcReceiverSlots;
  } else {
    return JavaScriptFrame::ComputeParametersCount();
  }
}
References BUILTIN, v8::internal::CommonFrameWithJSLinkage::ComputeParametersCount(), v8::internal::StackFrame::fp(), v8::internal::StackFrame::GcSafeLookupCode(), v8::internal::StandardFrameConstants::kArgCOffset, and v8::internal::kJSArgcReceiverSlots.
FindReturnPCForTrampoline()
int v8::internal::TurbofanJSFrame::FindReturnPCForTrampoline (Tagged< Code > code, int trampoline_pc) const [override], [virtual]
Implements v8::internal::OptimizedJSFrame.
Definition at line 3197 of file frames.cc.
                                                                        {
  DCHECK_EQ(code->kind(), CodeKind::TURBOFAN_JS);
  DCHECK(code->marked_for_deoptimization());
  SafepointTable safepoints(isolate(), pc(), code);
  return safepoints.find_return_pc(trampoline_pc);
}
References code, v8::internal::DCHECK(), DCHECK_EQ, and v8::internal::SafepointTable::find_return_pc().
Iterate()
void v8::internal::TurbofanJSFrame::Iterate (RootVisitor * v) const [override], [virtual]
Reimplemented from v8::internal::JavaScriptFrame.
Definition at line 2356 of file frames.cc.
                                                  {
  return IterateTurbofanJSOptimizedFrame(v);
}
References v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame().
StackSlotAt()
Tagged<Object> v8::internal::TurbofanJSFrame::StackSlotAt (int index) const [private]
type()
Type v8::internal::TurbofanJSFrame::type () const [inline], [override], [virtual]
Implements v8::internal::JavaScriptFrame.
Definition at line 1219 of file frames.h.
{ return TURBOFAN_JS; }
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 1232 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc