v8::internal::Float64 Class Reference
#include <boxed-float.h>
Public Member Functions
Float64 ()=default
Float64 (double value)
Float64 (base::Double value)
uint64_t get_bits () const
double get_scalar () const
bool is_hole_nan () const
bool is_nan () const
bool is_quiet_nan () const
V8_WARN_UNUSED_RESULT Float64 to_quiet_nan () const
uint64_t * get_bits_address ()
bool operator== (const Float64 &other) const
Static Public Member Functions
static constexpr Float64 FromBits (uint64_t bits)
Private Member Functions
constexpr Float64 (uint64_t bit_pattern)
uint64_t exponent () const
uint64_t mantissa () const
Private Attributes
uint64_t bit_pattern_ = 0
Friends
size_t hash_value (internal::Float64 f64)
Detailed Description
Definition at line 78 of file boxed-float.h.
Constructor & Destructor Documentation
Float64() [1/4]
v8::internal::Float64::Float64 () [default]
Referenced by FromBits().
Float64() [2/4]
v8::internal::Float64::Float64 (double value) [inline], [explicit]
Definition at line 84 of file boxed-float.h.
      : bit_pattern_(base::bit_cast<uint64_t>(value)) {
    // Check that the provided value is not a NaN, because the bit pattern of a
    // NaN may be changed by a base::bit_cast, e.g. for signalling NaNs on
    // ia32.
    DCHECK(!std::isnan(value));
  }
References v8::internal::DCHECK(), and v8::internal::value.
Float64() [3/4]
v8::internal::Float64::Float64 (base::Double value) [inline], [explicit]
Definition at line 92 of file boxed-float.h.
: bit_pattern_(value.AsUint64()) {}
Float64() [4/4]
constexpr v8::internal::Float64::Float64 (uint64_t bit_pattern) [inline], [explicit], [constexpr], [private]
Definition at line 139 of file boxed-float.h.
      : bit_pattern_(bit_pattern) {}
Member Function Documentation
exponent()
uint64_t v8::internal::Float64::exponent () const [inline], [private]
Definition at line 142 of file boxed-float.h.
{ return (bit_pattern_ >> 52) & ((1 << 11) - 1); }
References bit_pattern_.
Referenced by is_nan().
FromBits()
static constexpr Float64 v8::internal::Float64::FromBits (uint64_t bits) [inline], [static], [constexpr]
Definition at line 124 of file boxed-float.h.
{ return Float64(bits); }
References Float64().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumericalValue(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float64Constant(), v8::internal::TranslatedState::GetDoubleSlot(), v8::internal::maglev::Graph::GetFloat64Constant(), v8::internal::compiler::FixedDoubleArrayRef::GetFromImmutableFixedDoubleArray(), v8::internal::compiler::JSObjectRef::GetOwnFastConstantDoubleProperty(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::NumberConstant(), v8::internal::maglev::MaglevGraphBuilder::TryGetFloat64Constant(), v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral(), and v8::internal::wasm::WasmInterpreterRuntime::UnpackException().
get_bits()
uint64_t v8::internal::Float64::get_bits () const [inline]
Definition at line 94 of file boxed-float.h.
{ return bit_pattern_; }
References bit_pattern_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildHeapNumber(), v8::internal::compiler::CanBeImmediate(), v8::internal::TranslatedState::CreateNextTranslatedValue(), v8::internal::maglev::Graph::GetFloat64Constant(), v8::internal::compiler::GetImmediateIntegerValue(), v8::internal::compiler::IA32OperandGenerator::GetImmediateIntegerValue(), v8::base::hash_value(), v8::internal::maglev::MaglevAssembler::Move(), v8::internal::DeoptimizationLiteral::operator==(), v8::internal::compiler::turboshaft::ConstantOp::PrintOptions(), and v8::internal::maglev::Float64Constant::PrintParams().
get_bits_address()
uint64_t* v8::internal::Float64::get_bits_address () [inline]
Definition at line 122 of file boxed-float.h.
{ return &bit_pattern_; }
References bit_pattern_.
get_scalar()
double v8::internal::Float64::get_scalar () const [inline]
Definition at line 95 of file boxed-float.h.
{ return base::bit_cast<double>(bit_pattern_); }
References bit_pattern_.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), v8::internal::maglev::Float64Constant::DoReify(), v8::internal::maglev::MaglevGraphBuilder::GetTruncatedInt32ForToNumber(), v8::internal::TranslatedValue::GetValue(), is_nan(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat(), v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat64Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), operator==(), v8::internal::compiler::turboshaft::ConstantOp::PrintOptions(), v8::internal::maglev::Float64Constant::PrintParams(), v8::internal::maglev::CheckFloat64SameValue::PrintParams(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::maglev::Float64Constant::ToBoolean(), v8::internal::maglev::MaglevGraphBuilder::TryGetInt32Constant(), v8::internal::maglev::MaglevGraphBuilder::TryGetUint32Constant(), v8::internal::wasm::WasmInterpreterRuntime::UnpackException(), and v8::internal::compiler::InstructionSelector::VisitNode().
is_hole_nan()
bool v8::internal::Float64::is_hole_nan () const [inline]
Definition at line 96 of file boxed-float.h.
{ return bit_pattern_ == kHoleNanInt64; }
References bit_pattern_, and v8::internal::kHoleNanInt64.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumericalValue(), v8::base::hash_value(), operator==(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessConstant().
is_nan()
bool v8::internal::Float64::is_nan () const [inline]
Definition at line 101 of file boxed-float.h.
                      {
    // Even though {get_scalar()} might set the quiet NaN bit, it's ok here,
    // because this does not change the is_nan property.
    bool nan = std::isnan(get_scalar());
    DCHECK_EQ(nan, exponent() == 0x7ff && mantissa() != 0);
    return nan;
  }
References DCHECK_EQ, exponent(), get_scalar(), and mantissa().
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), v8::internal::maglev::MaglevGraphBuilder::GetSilencedNaN(), v8::base::hash_value(), is_quiet_nan(), operator==(), to_quiet_nan(), and v8::internal::maglev::Float64Constant::ToBoolean().
is_quiet_nan()
bool v8::internal::Float64::is_quiet_nan () const [inline]
Definition at line 109 of file boxed-float.h.
                            {
    return is_nan() && (bit_pattern_ & (uint64_t{1} << 51));
  }
References bit_pattern_, and is_nan().
mantissa()
uint64_t v8::internal::Float64::mantissa () const [inline], [private]
Definition at line 143 of file boxed-float.h.
{ return bit_pattern_ & ((uint64_t{1} << 52) - 1); }
References bit_pattern_.
Referenced by is_nan().
operator==()
bool v8::internal::Float64::operator== (const Float64 & other) const [inline]
Definition at line 129 of file boxed-float.h.
                                              {
    if (is_nan() && other.is_nan()) {
      return is_hole_nan() == other.is_hole_nan();
    }
    return get_scalar() == other.get_scalar();
  }
References get_scalar(), is_hole_nan(), and is_nan().
to_quiet_nan()
V8_WARN_UNUSED_RESULT Float64 v8::internal::Float64::to_quiet_nan () const [inline]
Definition at line 113 of file boxed-float.h.
                                                     {
    DCHECK(is_nan());
    Float64 quiet_nan{bit_pattern_ | (uint64_t{1} << 51)};
    DCHECK(quiet_nan.is_quiet_nan());
    return quiet_nan;
  }
References bit_pattern_, v8::internal::DCHECK(), and is_nan().
Friends And Related Function Documentation
hash_value
size_t hash_value (internal::Float64 f64) [friend]
Definition at line 136 of file boxed-float.h.
{ return f64.bit_pattern_; }
Member Data Documentation
bit_pattern_
uint64_t v8::internal::Float64::bit_pattern_ = 0 [private]
Definition at line 145 of file boxed-float.h.
Referenced by exponent(), get_bits(), get_bits_address(), get_scalar(), is_hole_nan(), is_quiet_nan(), mantissa(), and to_quiet_nan().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/utils/boxed-float.h