v8::internal::compiler::MemoryOptimizer Class Reference
#include <memory-optimizer.h>
Classes
struct Token
Public Member Functions
MemoryOptimizer (JSHeapBroker *broker, JSGraph *jsgraph, Zone *zone, MemoryLowering::AllocationFolding allocation_folding, const char *function_debug_name, TickCounter *tick_counter, bool is_wasm)
~MemoryOptimizer ()=default
void Optimize ()
Private Types
using AllocationState = MemoryLowering::AllocationState
using AllocationStates = ZoneVector< AllocationState const * >
Private Member Functions
void VisitNode (Node *, AllocationState const *, NodeId)
void VisitAllocateRaw (Node *, AllocationState const *, NodeId)
void VisitCall (Node *, AllocationState const *, NodeId)
void VisitLoadFromObject (Node *, AllocationState const *, NodeId)
void VisitLoadElement (Node *, AllocationState const *, NodeId)
void VisitLoadField (Node *, AllocationState const *, NodeId)
void VisitProtectedLoad (Node *, AllocationState const *, NodeId)
void VisitProtectedStore (Node *, AllocationState const *, NodeId)
void VisitStoreToObject (Node *, AllocationState const *, NodeId)
void VisitStoreElement (Node *, AllocationState const *, NodeId)
void VisitStoreField (Node *, AllocationState const *, NodeId)
void VisitStore (Node *, AllocationState const *, NodeId)
void VisitOtherEffect (Node *, AllocationState const *, NodeId)
AllocationState const * MergeStates (AllocationStates const &states)
void EnqueueMerge (Node *, int, AllocationState const *)
void EnqueueUses (Node *, AllocationState const *, NodeId)
void EnqueueUse (Node *, int, AllocationState const *, NodeId)
void ReplaceUsesAndKillNode (Node *node, Node *replacement)
bool AllocationTypeNeedsUpdateToOld (Node *const user, const Edge edge)
AllocationState const * empty_state () const
MemoryLowering * memory_lowering ()
WasmAddressReassociation * wasm_address_reassociation ()
TFGraph * graph () const
JSGraph * jsgraph () const
Zone * zone () const
DISALLOW_IMPLICIT_CONSTRUCTORS (MemoryOptimizer)
Private Attributes
JSGraphAssembler graph_assembler_
MemoryLowering memory_lowering_
WasmAddressReassociation wasm_address_reassociation_
JSGraph * jsgraph_
AllocationState const *const empty_state_
ZoneMap< NodeId, AllocationStates > pending_
ZoneQueue< Token > tokens_
Zone *const zone_
TickCounter *const tick_counter_
Detailed Description
Definition at line 49 of file memory-optimizer.h.
Member Typedef Documentation
AllocationState
using v8::internal::compiler::MemoryOptimizer::AllocationState = MemoryLowering::AllocationState [private]
Definition at line 60 of file memory-optimizer.h.
AllocationStates
using v8::internal::compiler::MemoryOptimizer::AllocationStates = ZoneVector<AllocationState const*> [private]
Definition at line 63 of file memory-optimizer.h.
Constructor & Destructor Documentation
MemoryOptimizer()
v8::internal::compiler::MemoryOptimizer::MemoryOptimizer (JSHeapBroker * broker, JSGraph * jsgraph, Zone * zone, MemoryLowering::AllocationFolding allocation_folding, const char * function_debug_name, TickCounter * tick_counter, bool is_wasm)
Definition at line 190 of file memory-optimizer.cc.
    : graph_assembler_(broker, jsgraph, zone, BranchSemantics::kMachine),
      memory_lowering_(jsgraph, zone, &graph_assembler_, is_wasm,
                       allocation_folding, WriteBarrierAssertFailed,
                       function_debug_name),
      wasm_address_reassociation_(jsgraph, zone),
      jsgraph_(jsgraph),
      empty_state_(AllocationState::Empty(zone)),
      pending_(zone),
      tokens_(zone),
      zone_(zone),
      tick_counter_(tick_counter) {}
References v8::internal::compiler::kMachine.
 MemoryOptimizer()
v8::internal::compiler::MemoryOptimizer::~MemoryOptimizer () [default]
Member Function Documentation
AllocationTypeNeedsUpdateToOld()
bool v8::internal::compiler::MemoryOptimizer::AllocationTypeNeedsUpdateToOld (Node *const user, const Edge edge) [private]
Definition at line 266 of file memory-optimizer.cc.
                                                                      {
  // Test to see if we need to update the AllocationType.
  if (node->opcode() == IrOpcode::kStoreField && edge.index() == 1) {
    Node* parent = node->InputAt(0);
    if (parent->opcode() == IrOpcode::kAllocateRaw &&
        AllocationTypeOf(parent->op()) == AllocationType::kOld) {
      return true;
    }
  }
  return false;
}
References v8::internal::compiler::AllocationTypeOf(), v8::internal::compiler::Edge::index(), v8::internal::compiler::Node::InputAt(), v8::internal::kOld, v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::opcode().
Referenced by VisitAllocateRaw().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::compiler::MemoryOptimizer::DISALLOW_IMPLICIT_CONSTRUCTORS (MemoryOptimizer) [private]
empty_state()
AllocationState const* v8::internal::compiler::MemoryOptimizer::empty_state () const [inline], [private]
Definition at line 102 of file memory-optimizer.h.
{ return empty_state_; }
References empty_state_.
Referenced by EnqueueMerge(), MergeStates(), Optimize(), and VisitCall().
EnqueueMerge()
void v8::internal::compiler::MemoryOptimizer::EnqueueMerge (Node * node, int index, AllocationState const * state) [private]
Definition at line 465 of file memory-optimizer.cc.
                                                                 {
  DCHECK_EQ(IrOpcode::kEffectPhi, node->opcode());
  NodeId effect_chain = node->id();
  int const input_count = node->InputCount() - 1;
  DCHECK_LT(0, input_count);
  Node* const control = node->InputAt(input_count);
  if (control->opcode() == IrOpcode::kLoop) {
    if (index == 0) {
      if (CanLoopAllocate(node, zone())) {
        // If the loop can allocate, we start with an empty state at the
        // beginning.
        EnqueueUses(node, empty_state(), effect_chain);
      } else {
        // If the loop cannot allocate, we can just propagate the state from
        // before the loop.
        EnqueueUses(node, state, effect_chain);
      }
    } else {
      // Do not revisit backedges.
    }
  } else {
    DCHECK_EQ(IrOpcode::kMerge, control->opcode());
    // Check if we already know about this pending merge.
    NodeId const id = node->id();
    auto it = pending_.find(id);
    if (it == pending_.end()) {
      // Insert a new pending merge.
      it = pending_.insert(std::make_pair(id, AllocationStates(zone()))).first;
    }
    // Add the next input state.
    it->second.push_back(state);
    // Check if states for all inputs are available by now.
    if (it->second.size() == static_cast<size_t>(input_count)) {
      // All inputs to this effect merge are done, merge the states given all
      // input constraints, drop the pending merge and enqueue uses of the
      // EffectPhi {node}.
      state = MergeStates(it->second);
      EnqueueUses(node, state, effect_chain);
      pending_.erase(it);
    }
  }
}
References v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::CanLoopAllocate(), DCHECK_EQ, DCHECK_LT, empty_state(), EnqueueUses(), v8::internal::compiler::Node::id(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), MergeStates(), v8::internal::compiler::Node::opcode(), pending_, and zone().
Referenced by EnqueueUse().
EnqueueUse()
void v8::internal::compiler::MemoryOptimizer::EnqueueUse (Node * node, int index, AllocationState const * state, NodeId effect_chain) [private]
Definition at line 518 of file memory-optimizer.cc.
                                                      {
  if (node->opcode() == IrOpcode::kEffectPhi) {
    // An EffectPhi represents a merge of different effect chains, which
    // needs special handling depending on whether the merge is part of a
    // loop or just a normal control join.
    EnqueueMerge(node, index, state);
  } else {
    Token token = {node, state, effect_chain};
    tokens_.push(token);
  }
}
References EnqueueMerge(), v8::internal::index, v8::internal::compiler::Node::opcode(), and tokens_.
Referenced by EnqueueUses().
EnqueueUses()
void v8::internal::compiler::MemoryOptimizer::EnqueueUses (Node * node, AllocationState const * state, NodeId effect_chain) [private]
Definition at line 509 of file memory-optimizer.cc.
                                                       {
  for (Edge const edge : node->use_edges()) {
    if (NodeProperties::IsEffectEdge(edge)) {
      EnqueueUse(edge.from(), edge.index(), state, effect_chain);
    }
  }
}
References EnqueueUse(), v8::internal::compiler::NodeProperties::IsEffectEdge(), and v8::internal::compiler::Node::use_edges().
Referenced by EnqueueMerge(), Optimize(), VisitAllocateRaw(), VisitCall(), VisitLoadElement(), VisitLoadField(), VisitLoadFromObject(), VisitOtherEffect(), VisitProtectedLoad(), VisitProtectedStore(), VisitStore(), VisitStoreElement(), VisitStoreField(), and VisitStoreToObject().
graph()
TFGraph * v8::internal::compiler::MemoryOptimizer::graph () const [private]
Definition at line 532 of file memory-optimizer.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
Referenced by Optimize().
jsgraph()
JSGraph* v8::internal::compiler::MemoryOptimizer::jsgraph () const [inline], [private]
Definition at line 108 of file memory-optimizer.h.
{ return jsgraph_; }
References jsgraph_.
Referenced by graph().
memory_lowering()
MemoryLowering* v8::internal::compiler::MemoryOptimizer::memory_lowering () [inline], [private]
Definition at line 103 of file memory-optimizer.h.
{ return &memory_lowering_; }
References memory_lowering_.
Referenced by VisitAllocateRaw(), VisitLoadElement(), VisitLoadField(), VisitLoadFromObject(), VisitStore(), VisitStoreElement(), VisitStoreField(), and VisitStoreToObject().
MergeStates()
MemoryOptimizer::AllocationState const * v8::internal::compiler::MemoryOptimizer::MergeStates (AllocationStates const & states) [private]
Definition at line 439 of file memory-optimizer.cc.
                                    {
  // Check if all states are the same; or at least if all allocation
  // states belong to the same allocation group.
  AllocationState const* state = states.front();
  MemoryLowering::AllocationGroup* group = state->group();
  for (size_t i = 1; i < states.size(); ++i) {
    if (states[i] != state) state = nullptr;
    if (states[i]->group() != group) group = nullptr;
  }
  if (state == nullptr) {
    if (group != nullptr) {
      // We cannot fold any more allocations into this group, but we can still
      // eliminate write barriers on stores to this group.
      // TODO(bmeurer): We could potentially just create a Phi here to merge
      // the various tops; but we need to pay special attention not to create
      // an unschedulable graph.
      state = AllocationState::Closed(group, nullptr, zone());
    } else {
      // The states are from different allocation groups.
      state = empty_state();
    }
  }
  return state;
}
References v8::internal::compiler::MemoryLowering::AllocationState::Closed(), empty_state(), v8::internal::ZoneVector< T >::front(), v8::internal::compiler::MemoryLowering::AllocationState::group(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ZoneVector< T >::size(), and zone().
Referenced by EnqueueMerge().
Optimize()
void v8::internal::compiler::MemoryOptimizer::Optimize ()
Definition at line 206 of file memory-optimizer.cc.
                               {
  EnqueueUses(graph()->start(), empty_state(), graph()->start()->id());
  while (!tokens_.empty()) {
    Token const token = tokens_.front();
    tokens_.pop();
    VisitNode(token.node, token.state, token.effect_chain);
  }
  if (v8_flags.turbo_wasm_address_reassociation) {
    wasm_address_reassociation()->Optimize();
  }
  DCHECK(pending_.empty());
  DCHECK(tokens_.empty());
}
References v8::internal::DCHECK(), v8::internal::compiler::MemoryOptimizer::Token::effect_chain, empty_state(), EnqueueUses(), graph(), v8::internal::compiler::MemoryOptimizer::Token::node, v8::internal::compiler::WasmAddressReassociation::Optimize(), pending_, v8::internal::compiler::MemoryOptimizer::Token::state, tokens_, v8::internal::v8_flags, VisitNode(), and wasm_address_reassociation().
Referenced by v8::internal::compiler::MemoryOptimizationPhase::Run().
ReplaceUsesAndKillNode()
void v8::internal::compiler::MemoryOptimizer::ReplaceUsesAndKillNode (Node * node, Node * replacement) [private]
Definition at line 280 of file memory-optimizer.cc.
                                                                          {
  // Replace all uses of node and kill the node to make sure we don't leave
  // dangling dead uses.
  DCHECK_NE(replacement, node);
  NodeProperties::ReplaceUses(node, replacement, graph_assembler_.effect(),
                              graph_assembler_.control());
  node->Kill();
}
References v8::internal::compiler::GraphAssembler::control(), DCHECK_NE, v8::internal::compiler::GraphAssembler::effect(), graph_assembler_, v8::internal::compiler::Node::Kill(), and v8::internal::compiler::NodeProperties::ReplaceUses().
Referenced by VisitAllocateRaw(), VisitLoadField(), and VisitLoadFromObject().
VisitAllocateRaw()
void v8::internal::compiler::MemoryOptimizer::VisitAllocateRaw (Node * node, AllocationState const * state, NodeId effect_chain) [private]
Definition at line 289 of file memory-optimizer.cc.
                                                            {
  DCHECK_EQ(IrOpcode::kAllocateRaw, node->opcode());
  const AllocateParameters& allocation = AllocateParametersOf(node->op());
  AllocationType allocation_type = allocation.allocation_type();
  // Propagate tenuring from outer allocations to inner allocations, i.e.
  // when we allocate an object in old space and store a newly allocated
  // child object into the pretenured object, then the newly allocated
  // child object also should get pretenured to old space.
  if (allocation_type == AllocationType::kOld) {
    for (Edge const edge : node->use_edges()) {
      Node* const user = edge.from();
      if (user->opcode() == IrOpcode::kStoreField && edge.index() == 0) {
        Node* child = user->InputAt(1);
        if (child->opcode() == IrOpcode::kAllocateRaw &&
            AllocationTypeOf(child->op()) == AllocationType::kYoung) {
          NodeProperties::ChangeOp(child, node->op());
          break;
        }
      }
    }
  } else {
    DCHECK_EQ(AllocationType::kYoung, allocation_type);
    for (Edge const edge : node->use_edges()) {
      Node* const user = edge.from();
      if (AllocationTypeNeedsUpdateToOld(user, edge)) {
        allocation_type = AllocationType::kOld;
        break;
      }
    }
  }
  Reduction reduction =
      memory_lowering()->ReduceAllocateRaw(node, allocation_type, &state);
  CHECK(reduction.Changed() && reduction.replacement() != node);
  ReplaceUsesAndKillNode(node, reduction.replacement());
  EnqueueUses(state->effect(), state, effect_chain);
}
References v8::internal::compiler::AllocateParametersOf(), v8::internal::compiler::AllocateParameters::allocation_type(), AllocationTypeNeedsUpdateToOld(), v8::internal::compiler::AllocationTypeOf(), v8::internal::compiler::Reduction::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), CHECK, DCHECK_EQ, v8::internal::compiler::MemoryLowering::AllocationState::effect(), EnqueueUses(), v8::internal::compiler::Node::InputAt(), v8::internal::kOld, v8::internal::kYoung, memory_lowering(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::Reduction::replacement(), ReplaceUsesAndKillNode(), and v8::internal::compiler::Node::use_edges().
Referenced by VisitNode().
VisitCall()
void v8::internal::compiler::MemoryOptimizer::VisitCall (Node * node, AllocationState const * state, NodeId effect_chain) [private]
Definition at line 424 of file memory-optimizer.cc.
                                                     {
  DCHECK_EQ(IrOpcode::kCall, node->opcode());
  // If the call can allocate, we start with a fresh state.
  if (!(CallDescriptorOf(node->op())->flags() & CallDescriptor::kNoAllocate)) {
    state = empty_state();
  }
  EnqueueUses(node, state, effect_chain);
}
References v8::internal::compiler::CallDescriptorOf(), DCHECK_EQ, empty_state(), EnqueueUses(), v8::internal::compiler::CallDescriptor::flags(), v8::internal::compiler::CallDescriptor::kNoAllocate, v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::opcode().
Referenced by VisitNode().
VisitLoadElement()
void v8::internal::compiler::MemoryOptimizer::VisitLoadElement (Node * node, AllocationState const * state, NodeId effect_chain) [private]
Definition at line 352 of file memory-optimizer.cc.
                                                            {
  DCHECK_EQ(IrOpcode::kLoadElement, node->opcode());
  memory_lowering()->ReduceLoadElement(node);
  EnqueueUses(node, state, effect_chain);
}
References DCHECK_EQ, EnqueueUses(), memory_lowering(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::MemoryLowering::ReduceLoadElement().
Referenced by VisitNode().
VisitLoadField()
void v8::internal::compiler::MemoryOptimizer::VisitLoadField (Node * node, AllocationState const * state, NodeId effect_chain) [private]
Definition at line 359 of file memory-optimizer.cc.
                                                          {
  DCHECK_EQ(IrOpcode::kLoadField, node->opcode());
  Reduction reduction = memory_lowering()->ReduceLoadField(node);
  DCHECK(reduction.Changed());
  // In case of replacement, the replacement graph should not require futher
  // lowering, so we can proceed iterating the graph from the node uses.
  EnqueueUses(node, state, effect_chain);
  // Node can be replaced under two cases:
  // 1. V8_ENABLE_SANDBOX is true and loading an external pointer value.
  // 2. V8_MAP_PACKING_BOOL is enabled.
  DCHECK_IMPLIES(!V8_ENABLE_SANDBOX_BOOL && !V8_MAP_PACKING_BOOL,
                 reduction.replacement() == node);
  if ((V8_ENABLE_SANDBOX_BOOL || V8_MAP_PACKING_BOOL) &&
      reduction.replacement() != node) {
    ReplaceUsesAndKillNode(node, reduction.replacement());
  }
}
References v8::internal::compiler::Reduction::Changed(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, EnqueueUses(), memory_lowering(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::MemoryLowering::ReduceLoadField(), v8::internal::compiler::Reduction::replacement(), ReplaceUsesAndKillNode(), V8_ENABLE_SANDBOX_BOOL, and V8_MAP_PACKING_BOOL.
Referenced by VisitNode().
VisitLoadFromObject()
void v8::internal::compiler::MemoryOptimizer::VisitLoadFromObject (Node * node, AllocationState const * state, NodeId effect_chain) [private]
Definition at line 331 of file memory-optimizer.cc.
                                                               {
  DCHECK(node->opcode() == IrOpcode::kLoadFromObject ||
         node->opcode() == IrOpcode::kLoadImmutableFromObject);
  Reduction reduction = memory_lowering()->ReduceLoadFromObject(node);
  EnqueueUses(node, state, effect_chain);
  if (V8_MAP_PACKING_BOOL && reduction.replacement() != node) {
    ReplaceUsesAndKillNode(node, reduction.replacement());
  }
}
References v8::internal::DCHECK(), EnqueueUses(), memory_lowering(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::MemoryLowering::ReduceLoadFromObject(), v8::internal::compiler::Reduction::replacement(), ReplaceUsesAndKillNode(), and V8_MAP_PACKING_BOOL.
Referenced by VisitNode().
VisitNode()
void v8::internal::compiler::MemoryOptimizer::VisitNode (Node * node, AllocationState const * state, NodeId effect_chain) [private]
Definition at line 220 of file memory-optimizer.cc.
                                                     {
  tick_counter_->TickAndMaybeEnterSafepoint();
  DCHECK(!node->IsDead());
  DCHECK_LT(0, node->op()->EffectInputCount());
  switch (node->opcode()) {
    case IrOpcode::kAllocate:
      // Allocate nodes were purged from the graph in effect-control
      // linearization.
      UNREACHABLE();
    case IrOpcode::kAllocateRaw:
      return VisitAllocateRaw(node, state, effect_chain);
    case IrOpcode::kCall:
      return VisitCall(node, state, effect_chain);
    case IrOpcode::kLoadFromObject:
    case IrOpcode::kLoadImmutableFromObject:
      return VisitLoadFromObject(node, state, effect_chain);
    case IrOpcode::kLoadElement:
      return VisitLoadElement(node, state, effect_chain);
    case IrOpcode::kLoadField:
      return VisitLoadField(node, state, effect_chain);
    case IrOpcode::kProtectedLoad:
      return VisitProtectedLoad(node, state, effect_chain);
    case IrOpcode::kProtectedStore:
      return VisitProtectedStore(node, state, effect_chain);
    case IrOpcode::kStoreToObject:
    case IrOpcode::kInitializeImmutableInObject:
      return VisitStoreToObject(node, state, effect_chain);
    case IrOpcode::kStoreElement:
      return VisitStoreElement(node, state, effect_chain);
    case IrOpcode::kStoreField:
      return VisitStoreField(node, state, effect_chain);
    case IrOpcode::kStore:
      return VisitStore(node, state, effect_chain);
    case IrOpcode::kStorePair:
      // Store pairing should happen after this pass.
      UNREACHABLE();
    default:
      if (!CanAllocate(node)) {
        // These operations cannot trigger GC.
        return VisitOtherEffect(node, state, effect_chain);
      }
  }
  DCHECK_EQ(0, node->op()->EffectOutputCount());
}
References v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::CanAllocate(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::Node::IsDead(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), tick_counter_, v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), v8::internal::UNREACHABLE(), VisitAllocateRaw(), VisitCall(), VisitLoadElement(), VisitLoadField(), VisitLoadFromObject(), VisitOtherEffect(), VisitProtectedLoad(), VisitProtectedStore(), VisitStore(), VisitStoreElement(), VisitStoreField(), and VisitStoreToObject().
Referenced by Optimize().
VisitOtherEffect()
void v8::internal::compiler::MemoryOptimizer::VisitOtherEffect (Node * node, AllocationState const * state, NodeId effect_chain) [private]
Definition at line 434 of file memory-optimizer.cc.
                                                            {
  EnqueueUses(node, state, effect_chain);
}
References EnqueueUses().
Referenced by VisitNode(), VisitProtectedLoad(), and VisitProtectedStore().
VisitProtectedLoad()
void v8::internal::compiler::MemoryOptimizer::VisitProtectedLoad (Node * node, AllocationState const * state, NodeId effect_chain) [private]
Definition at line 379 of file memory-optimizer.cc.
                                                              {
  DCHECK_EQ(IrOpcode::kProtectedLoad, node->opcode());
  if (v8_flags.turbo_wasm_address_reassociation) {
    wasm_address_reassociation()->VisitProtectedMemOp(node, effect_chain);
    EnqueueUses(node, state, effect_chain);
  } else {
    VisitOtherEffect(node, state, effect_chain);
  }
}
References DCHECK_EQ, EnqueueUses(), v8::internal::compiler::Node::opcode(), v8::internal::v8_flags, VisitOtherEffect(), v8::internal::compiler::WasmAddressReassociation::VisitProtectedMemOp(), and wasm_address_reassociation().
Referenced by VisitNode().
VisitProtectedStore()
void v8::internal::compiler::MemoryOptimizer::VisitProtectedStore (Node * node, AllocationState const * state, NodeId effect_chain) [private]
Definition at line 391 of file memory-optimizer.cc.
                                                               {
  DCHECK_EQ(IrOpcode::kProtectedStore, node->opcode());
  if (v8_flags.turbo_wasm_address_reassociation) {
    wasm_address_reassociation()->VisitProtectedMemOp(node, effect_chain);
    EnqueueUses(node, state, effect_chain);
  } else {
    VisitOtherEffect(node, state, effect_chain);
  }
}
References DCHECK_EQ, EnqueueUses(), v8::internal::compiler::Node::opcode(), v8::internal::v8_flags, VisitOtherEffect(), v8::internal::compiler::WasmAddressReassociation::VisitProtectedMemOp(), and wasm_address_reassociation().
Referenced by VisitNode().
VisitStore()
void v8::internal::compiler::MemoryOptimizer::VisitStore (Node * node, AllocationState const * state, NodeId effect_chain) [private]
Definition at line 417 of file memory-optimizer.cc.
                                                      {
  DCHECK_EQ(IrOpcode::kStore, node->opcode());
  memory_lowering()->ReduceStore(node, state);
  EnqueueUses(node, state, effect_chain);
}
References DCHECK_EQ, EnqueueUses(), memory_lowering(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::MemoryLowering::ReduceStore().
Referenced by VisitNode().
VisitStoreElement()
void v8::internal::compiler::MemoryOptimizer::VisitStoreElement (Node * node, AllocationState const * state, NodeId effect_chain) [private]
Definition at line 403 of file memory-optimizer.cc.
                                                             {
  DCHECK_EQ(IrOpcode::kStoreElement, node->opcode());
  memory_lowering()->ReduceStoreElement(node, state);
  EnqueueUses(node, state, effect_chain);
}
References DCHECK_EQ, EnqueueUses(), memory_lowering(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::MemoryLowering::ReduceStoreElement().
Referenced by VisitNode().
VisitStoreField()
void v8::internal::compiler::MemoryOptimizer::VisitStoreField (Node * node, AllocationState const * state, NodeId effect_chain) [private]
Definition at line 411 of file memory-optimizer.cc.
                                                           {
  DCHECK_EQ(IrOpcode::kStoreField, node->opcode());
  memory_lowering()->ReduceStoreField(node, state);
  EnqueueUses(node, state, effect_chain);
}
References DCHECK_EQ, EnqueueUses(), memory_lowering(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::MemoryLowering::ReduceStoreField().
Referenced by VisitNode().
VisitStoreToObject()
void v8::internal::compiler::MemoryOptimizer::VisitStoreToObject (Node * node, AllocationState const * state, NodeId effect_chain) [private]
Definition at line 343 of file memory-optimizer.cc.
                                                              {
  DCHECK(node->opcode() == IrOpcode::kStoreToObject ||
         node->opcode() == IrOpcode::kInitializeImmutableInObject);
  memory_lowering()->ReduceStoreToObject(node, state);
  EnqueueUses(node, state, effect_chain);
}
References v8::internal::DCHECK(), EnqueueUses(), memory_lowering(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::MemoryLowering::ReduceStoreToObject().
Referenced by VisitNode().
wasm_address_reassociation()
WasmAddressReassociation* v8::internal::compiler::MemoryOptimizer::wasm_address_reassociation () [inline], [private]
Definition at line 104 of file memory-optimizer.h.
                                                         {
    return &wasm_address_reassociation_;
  }
References wasm_address_reassociation_.
Referenced by Optimize(), VisitProtectedLoad(), and VisitProtectedStore().
zone()
Zone* v8::internal::compiler::MemoryOptimizer::zone () const [inline], [private]
Definition at line 109 of file memory-optimizer.h.
{ return zone_; }
References zone_.
Referenced by EnqueueMerge(), and MergeStates().
Member Data Documentation
empty_state_
AllocationState const* const v8::internal::compiler::MemoryOptimizer::empty_state_ [private]
Definition at line 115 of file memory-optimizer.h.
Referenced by empty_state().
graph_assembler_
JSGraphAssembler v8::internal::compiler::MemoryOptimizer::graph_assembler_ [private]
Definition at line 111 of file memory-optimizer.h.
Referenced by ReplaceUsesAndKillNode().
jsgraph_
JSGraph* v8::internal::compiler::MemoryOptimizer::jsgraph_ [private]
Definition at line 114 of file memory-optimizer.h.
Referenced by jsgraph().
memory_lowering_
MemoryLowering v8::internal::compiler::MemoryOptimizer::memory_lowering_ [private]
Definition at line 112 of file memory-optimizer.h.
Referenced by memory_lowering().
pending_
ZoneMap<NodeId, AllocationStates> v8::internal::compiler::MemoryOptimizer::pending_ [private]
Definition at line 116 of file memory-optimizer.h.
Referenced by EnqueueMerge(), and Optimize().
tick_counter_
TickCounter* const v8::internal::compiler::MemoryOptimizer::tick_counter_ [private]
Definition at line 119 of file memory-optimizer.h.
Referenced by VisitNode().
tokens_
ZoneQueue<Token> v8::internal::compiler::MemoryOptimizer::tokens_ [private]
Definition at line 117 of file memory-optimizer.h.
Referenced by EnqueueUse(), and Optimize().
wasm_address_reassociation_
WasmAddressReassociation v8::internal::compiler::MemoryOptimizer::wasm_address_reassociation_ [private]
Definition at line 113 of file memory-optimizer.h.
Referenced by wasm_address_reassociation().
zone_
Zone* const v8::internal::compiler::MemoryOptimizer::zone_ [private]
Definition at line 118 of file memory-optimizer.h.
Referenced by zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/memory-optimizer.h
/mnt/V8SourceCode/src/compiler/memory-optimizer.cc