v8::internal::detail::WaiterQueueLockGuard Class Reference
Public Member Functions
WaiterQueueLockGuard (std::atomic< StateT > *state, StateT &current_state)
WaiterQueueLockGuard (std::atomic< StateT > *state, bool is_locked)
WaiterQueueLockGuard (const WaiterQueueLockGuard &)=delete
WaiterQueueLockGuard ()=delete
~WaiterQueueLockGuard ()
void set_new_state (StateT new_state)
Static Public Member Functions
static std::optional< WaiterQueueLockGuard > NewAlreadyLockedWaiterQueueLockGuard (std::atomic< StateT > *state)
Private Types
using StateT = JSSynchronizationPrimitive::StateT
Private Attributes
std::atomic< StateT > * state_
StateT new_state_
Static Private Attributes
static constexpr StateT kInvalidState
Detailed Description
Definition at line 117 of file js-atomics-synchronization.cc.
Member Typedef Documentation
StateT
using v8::internal::detail::WaiterQueueLockGuard::StateT = JSSynchronizationPrimitive::StateT [private]
Definition at line 118 of file js-atomics-synchronization.cc.
Constructor & Destructor Documentation
WaiterQueueLockGuard() [1/4]
v8::internal::detail::WaiterQueueLockGuard::WaiterQueueLockGuard (std::atomic< StateT > * state, StateT & current_state) [inline], [explicit]
Definition at line 124 of file js-atomics-synchronization.cc.
      : state_(state), new_state_(kInvalidState) {
    while (!JSSynchronizationPrimitive::TryLockWaiterQueueExplicit(
        state, current_state)) {
      YIELD_PROCESSOR;
    }
  }
References v8::internal::JSSynchronizationPrimitive::TryLockWaiterQueueExplicit(), and YIELD_PROCESSOR.
WaiterQueueLockGuard() [2/4]
v8::internal::detail::WaiterQueueLockGuard::WaiterQueueLockGuard (std::atomic< StateT > * state, bool is_locked) [inline], [explicit]
Definition at line 135 of file js-atomics-synchronization.cc.
      : state_(state), new_state_(kInvalidState) {
    CHECK(is_locked);
    DCHECK(JSSynchronizationPrimitive::IsWaiterQueueLockedField::decode(
        state->load()));
  }
References CHECK, v8::internal::DCHECK(), and v8::base::BitField< T, shift, size, U >::decode().
WaiterQueueLockGuard() [3/4]
v8::internal::detail::WaiterQueueLockGuard::WaiterQueueLockGuard (const WaiterQueueLockGuard &) [delete]
WaiterQueueLockGuard() [4/4]
v8::internal::detail::WaiterQueueLockGuard::WaiterQueueLockGuard () [delete]
 WaiterQueueLockGuard()
v8::internal::detail::WaiterQueueLockGuard::~WaiterQueueLockGuard () [inline]
Definition at line 145 of file js-atomics-synchronization.cc.
                          {
    DCHECK_NOT_NULL(state_);
    DCHECK_NE(new_state_, kInvalidState);
    DCHECK(JSSynchronizationPrimitive::IsWaiterQueueLockedField::decode(
        state_->load()));
    new_state_ = JSSynchronizationPrimitive::IsWaiterQueueLockedField::update(
        new_state_, false);
    state_->store(new_state_, std::memory_order_release);
  }
References v8::internal::DCHECK(), DCHECK_NE, DCHECK_NOT_NULL, v8::base::BitField< T, shift, size, U >::decode(), and v8::base::BitField< T, shift, size, U >::update().
Member Function Documentation
NewAlreadyLockedWaiterQueueLockGuard()
static std::optional<WaiterQueueLockGuard> v8::internal::detail::WaiterQueueLockGuard::NewAlreadyLockedWaiterQueueLockGuard (std::atomic< StateT > * state) [inline], [static]
Definition at line 158 of file js-atomics-synchronization.cc.
                                                                 {
    return std::optional<WaiterQueueLockGuard>(std::in_place, state, true);
  }
Referenced by v8::internal::JSAtomicsMutex::LockWaiterQueueOrJSMutex().
set_new_state()
void v8::internal::detail::WaiterQueueLockGuard::set_new_state (StateT new_state) [inline]
Definition at line 155 of file js-atomics-synchronization.cc.
{ new_state_ = new_state; }
Referenced by v8::internal::JSAtomicsCondition::CleanupMatchingAsyncWaiters(), v8::internal::JSAtomicsCondition::DequeueExplicit(), v8::internal::JSAtomicsCondition::QueueWaiter(), and v8::internal::JSAtomicsMutex::UnlockSlowPath().
Member Data Documentation
kInvalidState
constexpr StateT v8::internal::detail::WaiterQueueLockGuard::kInvalidState [static], [constexpr], [private]
Initial value:
=
      ~JSSynchronizationPrimitive::kEmptyState
Definition at line 163 of file js-atomics-synchronization.cc.
new_state_
StateT v8::internal::detail::WaiterQueueLockGuard::new_state_ [private]
Definition at line 166 of file js-atomics-synchronization.cc.
state_
std::atomic<StateT>* v8::internal::detail::WaiterQueueLockGuard::state_ [private]
Definition at line 165 of file js-atomics-synchronization.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/js-atomics-synchronization.cc