v8::internal::wasm::gdb_server::SocketBinding Class Reference
#include <transport.h>
Public Member Functions
SocketBinding (SocketHandle socket_handle)
bool IsValid () const
std::unique_ptr< SocketTransport > CreateTransport ()
uint16_t GetBoundPort ()
Static Public Member Functions
static SocketBinding Bind (uint16_t tcp_port)
Private Attributes
SocketHandle socket_handle_
Detailed Description
Definition at line 52 of file transport.h.
Constructor & Destructor Documentation
SocketBinding()
v8::internal::wasm::gdb_server::SocketBinding::SocketBinding (SocketHandle socket_handle) [explicit]
Definition at line 18 of file transport.cc.
    : socket_handle_(socket_handle) {}
Referenced by Bind().
Member Function Documentation
Bind()
SocketBinding v8::internal::wasm::gdb_server::SocketBinding::Bind (uint16_t tcp_port) [static]
Definition at line 22 of file transport.cc.
                                                   {
  SocketHandle socket_handle = ::socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
  if (socket_handle == InvalidSocket) {
    TRACE_GDB_REMOTE("Failed to create socket.\n");
    return SocketBinding(InvalidSocket);
  }
  struct sockaddr_in sockaddr;
  // Clearing sockaddr_in first appears to be necessary on Mac OS X.
  memset(&sockaddr, 0, sizeof(sockaddr));
  socklen_t addrlen = static_cast<socklen_t>(sizeof(sockaddr));
  sockaddr.sin_family = AF_INET;
  sockaddr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
  sockaddr.sin_port = htons(tcp_port);
#if _WIN32
  // On Windows, SO_REUSEADDR has a different meaning than on POSIX systems.
  // SO_REUSEADDR allows hijacking of an open socket by another process.
  // The SO_EXCLUSIVEADDRUSE flag prevents this behavior.
  // See:
  // http://msdn.microsoft.com/en-us/library/windows/desktop/ms740621(v=vs.85).aspx
  //
  // Additionally, unlike POSIX, TCP server sockets can be bound to
  // ports in the TIME_WAIT state, without setting SO_REUSEADDR.
  int exclusive_address = 1;
  if (setsockopt(socket_handle, SOL_SOCKET, SO_EXCLUSIVEADDRUSE,
                 reinterpret_cast<char*>(&exclusive_address),
                 sizeof(exclusive_address))) {
    TRACE_GDB_REMOTE("Failed to set SO_EXCLUSIVEADDRUSE option.\n");
  }
#else
  // On POSIX, this is necessary to ensure that the TCP port is released
  // promptly when sel_ldr exits. Without this, the TCP port might
  // only be released after a timeout, and later processes can fail
  // to bind it.
  int reuse_address = 1;
  if (setsockopt(socket_handle, SOL_SOCKET, SO_REUSEADDR,
                 reinterpret_cast<char*>(&reuse_address),
                 sizeof(reuse_address))) {
    TRACE_GDB_REMOTE("Failed to set SO_REUSEADDR option.\n");
  }
#endif
  if (bind(socket_handle, reinterpret_cast<struct sockaddr*>(&sockaddr),
           addrlen)) {
    TRACE_GDB_REMOTE("Failed to bind server.\n");
    return SocketBinding(InvalidSocket);
  }
  if (listen(socket_handle, 1)) {
    TRACE_GDB_REMOTE("Failed to listen.\n");
    return SocketBinding(InvalidSocket);
  }
  return SocketBinding(socket_handle);
}
References InvalidSocket, SocketBinding(), and TRACE_GDB_REMOTE.
Referenced by v8::internal::wasm::gdb_server::GdbServerThread::Run().
CreateTransport()
std::unique_ptr< SocketTransport > v8::internal::wasm::gdb_server::SocketBinding::CreateTransport ()
Definition at line 77 of file transport.cc.
                                                              {
  return std::make_unique<SocketTransport>(socket_handle_);
}
References socket_handle_.
Referenced by v8::internal::wasm::gdb_server::GdbServerThread::Run().
GetBoundPort()
uint16_t v8::internal::wasm::gdb_server::SocketBinding::GetBoundPort ()
Definition at line 81 of file transport.cc.
                                     {
  struct sockaddr_in saddr;
  struct sockaddr* psaddr = reinterpret_cast<struct sockaddr*>(&saddr);
  // Clearing sockaddr_in first appears to be necessary on Mac OS X.
  memset(&saddr, 0, sizeof(saddr));
  socklen_t addrlen = static_cast<socklen_t>(sizeof(saddr));
  if (::getsockname(socket_handle_, psaddr, &addrlen)) {
    TRACE_GDB_REMOTE("Failed to retrieve bound address.\n");
    return 0;
  }
  return ntohs(saddr.sin_port);
}
References socket_handle_, and TRACE_GDB_REMOTE.
Referenced by v8::internal::wasm::gdb_server::GdbServerThread::Run().
IsValid()
bool v8::internal::wasm::gdb_server::SocketBinding::IsValid () const [inline]
Definition at line 60 of file transport.h.
{ return socket_handle_ != InvalidSocket; }
References InvalidSocket, and socket_handle_.
Referenced by v8::internal::wasm::gdb_server::GdbServerThread::Run().
Member Data Documentation
socket_handle_
SocketHandle v8::internal::wasm::gdb_server::SocketBinding::socket_handle_ [private]
Definition at line 69 of file transport.h.
Referenced by CreateTransport(), GetBoundPort(), and IsValid().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/wasm/gdb-server/transport.h
/mnt/V8SourceCode/src/debug/wasm/gdb-server/transport.cc