v8::internal::anonymous_namespace{mark-compact.cc}::ClearSharedStructTypeRegistryJobItem Class Reference
Public Member Functions
ClearSharedStructTypeRegistryJobItem (Isolate *isolate)
void Run (JobDelegate *delegate) final
Private Attributes
Isolate *const isolate_
Detailed Description
Definition at line 2830 of file mark-compact.cc.
Constructor & Destructor Documentation
ClearSharedStructTypeRegistryJobItem()
v8::internal::anonymous_namespace{mark-compact.cc}::ClearSharedStructTypeRegistryJobItem::ClearSharedStructTypeRegistryJobItem (Isolate * isolate) [inline], [explicit]
Definition at line 2833 of file mark-compact.cc.
      : isolate_(isolate) {
    DCHECK(isolate->is_shared_space_isolate());
    DCHECK_NOT_NULL(isolate->shared_struct_type_registry());
  }
References DCHECK, DCHECK_NOT_NULL, v8::internal::Isolate::is_shared_space_isolate(), and v8::internal::Isolate::shared_struct_type_registry().
Member Function Documentation
Run()
void v8::internal::anonymous_namespace{mark-compact.cc}::ClearSharedStructTypeRegistryJobItem::Run (JobDelegate * delegate) [inline], [final], [virtual]
Implements v8::internal::anonymous_namespace{mark-compact.cc}::ParallelClearingJob::ClearingItem.
Definition at line 2839 of file mark-compact.cc.
                                        {
    // Set the current isolate such that trusted pointer tables etc are
    // available and the cage base is set correctly for multi-cage mode.
    SetCurrentIsolateScope isolate_scope(isolate_);
    auto* registry = isolate_->shared_struct_type_registry();
    SharedStructTypeRegistryCleaner cleaner(isolate_->heap());
    registry->IterateElements(isolate_, &cleaner);
    registry->NotifyElementsRemoved(cleaner.ElementsRemoved());
  }
References v8::internal::anonymous_namespace{mark-compact.cc}::SharedStructTypeRegistryCleaner::ElementsRemoved().
Member Data Documentation
isolate_
Isolate* const v8::internal::anonymous_namespace{mark-compact.cc}::ClearSharedStructTypeRegistryJobItem::isolate_ [private]
Definition at line 2851 of file mark-compact.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc