cppgc::internal::NormalPage Class Reference
#include <heap-page.h>
Classes
class IteratorImpl
Public Types
using iterator = IteratorImpl< HeapObjectHeader >
using const_iterator = IteratorImpl< const HeapObjectHeader >
Public Member Functions
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Address PayloadStart ()
ConstAddress PayloadStart () const
Address PayloadEnd ()
ConstAddress PayloadEnd () const
bool PayloadContains (ConstAddress address) const
size_t AllocatedBytesAtLastGC () const
void SetAllocatedBytesAtLastGC (size_t bytes)
PlatformAwareObjectStartBitmap & object_start_bitmap ()
const PlatformAwareObjectStartBitmap & object_start_bitmap () const
Static Public Member Functions
static NormalPage * TryCreate (PageBackend &, NormalPageSpace &)
static void Destroy (NormalPage *)
static NormalPage * From (BasePage *page)
static const NormalPage * From (const BasePage *page)
static constexpr size_t PayloadSize ()
Private Member Functions
NormalPage (HeapBase &heap, BaseSpace &space)
~NormalPage ()=default
Private Attributes
size_t allocated_bytes_at_last_gc_ = 0
PlatformAwareObjectStartBitmap object_start_bitmap_
Additional Inherited Members
Detailed Description
Definition at line 152 of file heap-page.h.
Member Typedef Documentation
const_iterator
using cppgc::internal::NormalPage::const_iterator = IteratorImpl<const HeapObjectHeader>
Definition at line 197 of file heap-page.h.
iterator
using cppgc::internal::NormalPage::iterator = IteratorImpl<HeapObjectHeader>
Definition at line 196 of file heap-page.h.
Constructor & Destructor Documentation
NormalPage()
cppgc::internal::NormalPage::NormalPage (HeapBase & heap, BaseSpace & space) [private]
Definition at line 207 of file heap-page.cc.
    : BasePage(heap, space, PageType::kNormal), object_start_bitmap_() {
  DCHECK_LT(kLargeObjectSizeThreshold,
            static_cast<size_t>(PayloadEnd() - PayloadStart()));
}
References DCHECK_LT, cppgc::internal::kLargeObjectSizeThreshold, PayloadEnd(), and PayloadStart().
Referenced by TryCreate().
 NormalPage()
cppgc::internal::NormalPage::~NormalPage () [private], [default]
Referenced by Destroy().
Member Function Documentation
AllocatedBytesAtLastGC()
size_t cppgc::internal::NormalPage::AllocatedBytesAtLastGC () const [inline]
Definition at line 235 of file heap-page.h.
{ return allocated_bytes_at_last_gc_; }
Referenced by cppgc::internal::BasePage::AllocatedBytesAtLastGC().
begin() [1/2]
NormalPage::iterator cppgc::internal::NormalPage::begin ()
Definition at line 213 of file heap-page.cc.
                                     {
  const auto& lab = NormalPageSpace::From(space()).linear_allocation_buffer();
  return iterator(reinterpret_cast<HeapObjectHeader*>(PayloadStart()),
                  lab.start(), lab.size());
}
References cppgc::internal::NormalPageSpace::From(), cppgc::internal::NormalPageSpace::linear_allocation_buffer(), PayloadStart(), and cppgc::internal::BasePage::space().
Referenced by TryCreate().
begin() [2/2]
NormalPage::const_iterator cppgc::internal::NormalPage::begin () const
Definition at line 219 of file heap-page.cc.
                                                 {
  const auto& lab = NormalPageSpace::From(space()).linear_allocation_buffer();
  return const_iterator(
      reinterpret_cast<const HeapObjectHeader*>(PayloadStart()), lab.start(),
      lab.size());
}
References cppgc::internal::NormalPageSpace::From(), cppgc::internal::NormalPageSpace::linear_allocation_buffer(), PayloadStart(), and cppgc::internal::BasePage::space().
Destroy()
void cppgc::internal::NormalPage::Destroy (NormalPage * page) [static]
Definition at line 195 of file heap-page.cc.
                                         {
  DCHECK(page);
  HeapBase& heap = page->heap();
  const BaseSpace& space = page->space();
  DCHECK_EQ(space.end(), std::find(space.begin(), space.end(), page));
  USE(space);
  page->~NormalPage();
  PageBackend* backend = heap.page_backend();
  heap.stats_collector()->NotifyFreedMemory(kPageSize);
  backend->FreeNormalPageMemory(reinterpret_cast<Address>(page));
}
References cppgc::internal::BaseSpace::begin(), DCHECK, DCHECK_EQ, cppgc::internal::BaseSpace::end(), cppgc::internal::PageBackend::FreeNormalPageMemory(), cppgc::internal::BasePage::heap(), cppgc::internal::kPageSize, cppgc::internal::BasePage::space(), USE, and ~NormalPage().
Referenced by cppgc::internal::BasePage::Destroy(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::FinishCompactingSpace(), and cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitNormalPage().
end() [1/2]
iterator cppgc::internal::NormalPage::end () [inline]
Definition at line 216 of file heap-page.h.
                 {
    return iterator(reinterpret_cast<HeapObjectHeader*>(PayloadEnd()));
  }
end() [2/2]
const_iterator cppgc::internal::NormalPage::end () const [inline]
Definition at line 219 of file heap-page.h.
                             {
    return const_iterator(
        reinterpret_cast<const HeapObjectHeader*>(PayloadEnd()));
  }
From() [1/2]
static NormalPage* cppgc::internal::NormalPage::From (BasePage * page) [inline], [static]
Definition at line 205 of file heap-page.h.
                                          {
    DCHECK(!page->is_large());
    return static_cast<NormalPage*>(page);
  }
References DCHECK, and cppgc::internal::BasePage::is_large().
Referenced by cppgc::internal::anonymous_namespace{object-allocator.cc}::AddToFreeList(), cppgc::internal::BasePage::AllocatedBytesAtLastGC(), cppgc::internal::BasePage::AllocatedSize(), cppgc::internal::ObjectAllocator::AllocateObjectOnSpace(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactSpace(), cppgc::internal::BasePage::Destroy(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage(), cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), cppgc::internal::ObjectHeaderFromInnerAddressImpl(), cppgc::internal::BasePage::PayloadEnd(), cppgc::internal::BasePage::PayloadStart(), cppgc::internal::anonymous_namespace{object-allocator.cc}::ReplaceLinearAllocationBuffer(), cppgc::internal::MarkingVerifierBase::ReportDifferences(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink(), cppgc::internal::HeapVisitor< Derived >::Traverse(), cppgc::internal::BasePage::TryObjectHeaderFromInnerAddress(), and cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBufferFromFreeList().
From() [2/2]
static const NormalPage* cppgc::internal::NormalPage::From (const BasePage * page) [inline], [static]
Definition at line 209 of file heap-page.h.
                                                      {
    return From(const_cast<BasePage*>(page));
  }
object_start_bitmap() [1/2]
PlatformAwareObjectStartBitmap& cppgc::internal::NormalPage::object_start_bitmap () [inline]
Definition at line 241 of file heap-page.h.
                                                        {
    return object_start_bitmap_;
  }
Referenced by cppgc::internal::anonymous_namespace{object-allocator.cc}::AddToFreeList(), cppgc::internal::ObjectAllocator::AllocateObjectOnSpace(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::FinishCompactingPage(), cppgc::internal::ObjectHeaderFromInnerAddressImpl(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage(), and cppgc::internal::anonymous_namespace{sweeper.cc}::ObjectStartBitmapVerifier::VisitNormalPage().
object_start_bitmap() [2/2]
const PlatformAwareObjectStartBitmap& cppgc::internal::NormalPage::object_start_bitmap () const [inline]
Definition at line 244 of file heap-page.h.
                                                                    {
    return object_start_bitmap_;
  }
PayloadContains()
bool cppgc::internal::NormalPage::PayloadContains (ConstAddress address) const [inline]
Definition at line 231 of file heap-page.h.
                                                   {
    return (PayloadStart() <= address) && (address < PayloadEnd());
  }
Referenced by cppgc::internal::BasePage::TryObjectHeaderFromInnerAddress().
PayloadEnd() [1/2]
Address cppgc::internal::NormalPage::PayloadEnd ()
Definition at line 235 of file heap-page.cc.
{ return PayloadStart() + PayloadSize(); }
References PayloadSize(), and PayloadStart().
Referenced by cppgc::internal::ObjectAllocator::MarkAllPagesAsYoung(), NormalPage(), cppgc::internal::BasePage::PayloadEnd(), PayloadEnd(), and cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage().
PayloadEnd() [2/2]
ConstAddress cppgc::internal::NormalPage::PayloadEnd () const
Definition at line 237 of file heap-page.cc.
                                          {
  return const_cast<NormalPage*>(this)->PayloadEnd();
}
References PayloadEnd().
PayloadSize()
constexpr size_t cppgc::internal::NormalPage::PayloadSize () [inline], [static], [constexpr]
Definition at line 368 of file heap-page.h.
                                                {
  return kPageSize - RoundUp(sizeof(NormalPage), kAllocationGranularity);
}
References cppgc::internal::kAllocationGranularity, cppgc::internal::kPageSize, and RoundUp().
Referenced by cppgc::internal::BasePage::AllocatedSize(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::FinishCompactingPage(), PayloadEnd(), and cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitNormalPage().
PayloadStart() [1/2]
Address cppgc::internal::NormalPage::PayloadStart ()
Definition at line 226 of file heap-page.cc.
                                 {
  return AlignAddress((reinterpret_cast<Address>(this + 1)),
                      kAllocationGranularity);
}
References cppgc::internal::anonymous_namespace{heap-page.cc}::AlignAddress(), and cppgc::internal::kAllocationGranularity.
Referenced by begin(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::FinishCompactingPage(), cppgc::internal::ObjectAllocator::MarkAllPagesAsYoung(), NormalPage(), PayloadEnd(), cppgc::internal::BasePage::PayloadStart(), PayloadStart(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage(), and cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitNormalPage().
PayloadStart() [2/2]
ConstAddress cppgc::internal::NormalPage::PayloadStart () const
Definition at line 231 of file heap-page.cc.
                                            {
  return const_cast<NormalPage*>(this)->PayloadStart();
}
References PayloadStart().
SetAllocatedBytesAtLastGC()
void cppgc::internal::NormalPage::SetAllocatedBytesAtLastGC (size_t bytes) [inline]
Definition at line 237 of file heap-page.h.
                                               {
    allocated_bytes_at_last_gc_ = bytes;
  }
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage().
TryCreate()
NormalPage * cppgc::internal::NormalPage::TryCreate (PageBackend & page_backend, NormalPageSpace & space) [static]
Definition at line 164 of file heap-page.cc.
                                                          {
  void* memory = page_backend.TryAllocateNormalPageMemory();
  if (!memory) return nullptr;
  auto* normal_page = new (memory) NormalPage(*space.raw_heap()->heap(), space);
  normal_page->SynchronizedStore();
  normal_page->heap().stats_collector()->NotifyAllocatedMemory(kPageSize);
  // Memory is zero initialized as
  // a) memory retrieved from the OS is zeroed;
  // b) memory retrieved from the page pool was swept and thus is zeroed except
  // for the first header which will anyways serve as header again.
  //
  // The following is a subset of SetMemoryInaccessible() to establish the
  // invariant that memory is in the same state as it would be after sweeping.
  // This allows to return newly allocated pages to go into that LAB and back
  // into the free list.
  Address begin = normal_page->PayloadStart() + sizeof(HeapObjectHeader);
  const size_t size = normal_page->PayloadSize() - sizeof(HeapObjectHeader);
#if defined(V8_USE_MEMORY_SANITIZER)
  MSAN_ALLOCATED_UNINITIALIZED_MEMORY(begin, size);
#elif defined(V8_USE_ADDRESS_SANITIZER)
  ASAN_POISON_MEMORY_REGION(begin, size);
#elif DEBUG
  cppgc::internal::ZapMemory(begin, size);
#endif // Release builds.
  CheckMemoryIsInaccessible(begin, size);
  return normal_page;
}
References ASAN_POISON_MEMORY_REGION, begin(), cppgc::internal::CheckMemoryIsInaccessible(), cppgc::internal::RawHeap::heap(), cppgc::internal::kPageSize, MSAN_ALLOCATED_UNINITIALIZED_MEMORY, NormalPage(), cppgc::internal::BaseSpace::raw_heap(), size(), cppgc::internal::BasePage::space(), cppgc::internal::PageBackend::TryAllocateNormalPageMemory(), and cppgc::internal::ZapMemory().
Referenced by cppgc::internal::ObjectAllocator::TryExpandAndRefillLinearAllocationBuffer().
Member Data Documentation
allocated_bytes_at_last_gc_
size_t cppgc::internal::NormalPage::allocated_bytes_at_last_gc_ = 0 [private]
Definition at line 252 of file heap-page.h.
object_start_bitmap_
PlatformAwareObjectStartBitmap cppgc::internal::NormalPage::object_start_bitmap_ [private]
Definition at line 253 of file heap-page.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/heap-page.h
/mnt/V8SourceCode/src/heap/cppgc/heap-page.cc