v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next > Class Template Reference
#include <late-load-elimination-reducer.h>
Public Types
using Replacement = LoadEliminationReplacement
Public Member Functions
void Analyze ()
OpIndex REDUCE_INPUT_GRAPH() Load (OpIndex ig_index, const LoadOp &load)
OpIndex REDUCE_INPUT_GRAPH() Change (OpIndex ig_index, const ChangeOp &change)
OpIndex REDUCE_INPUT_GRAPH() TaggedBitcast (OpIndex ig_index, const TaggedBitcastOp &bitcast)
V< None > REDUCE() AssumeMap (V< HeapObject >, ZoneRefSet< Map >)
Private Types
using RawBaseAssumption = LateLoadEliminationAnalyzer::RawBaseAssumption
Private Attributes
RawBaseAssumption raw_base_assumption_
LateLoadEliminationAnalyzer analyzer_
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >
Definition at line 783 of file late-load-elimination-reducer.h.
Member Typedef Documentation
RawBaseAssumption
template<class Next >
using v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::RawBaseAssumption = LateLoadEliminationAnalyzer::RawBaseAssumption [private]
Definition at line 863 of file late-load-elimination-reducer.h.
Replacement
template<class Next >
using v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::Replacement = LoadEliminationReplacement
Definition at line 786 of file late-load-elimination-reducer.h.
Member Function Documentation
Analyze()
template<class Next >
void v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::Analyze () [inline]
Definition at line 788 of file late-load-elimination-reducer.h.
                 {
    if (v8_flags.turboshaft_load_elimination) {
      analyzer_.Run();
    }
    Next::Analyze();
  }
References v8::internal::v8_flags.
AssumeMap()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::AssumeMap (V< HeapObject > , ZoneRefSet< Map >) [inline]
Definition at line 854 of file late-load-elimination-reducer.h.
                                                            {
    // AssumeMaps are currently not used after Load Elimination. We thus remove
    // them now. If they ever become needed for later optimizations, we could
    // consider leaving them in the graph and just ignoring them in the
    // Instruction Selector.
    return {};
  }
Change()
template<class Next >
OpIndex REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::Change (OpIndex ig_index, const ChangeOp & change) [inline]
Definition at line 831 of file late-load-elimination-reducer.h.
                                                                               {
    if (v8_flags.turboshaft_load_elimination) {
      Replacement replacement = analyzer_.GetReplacement(ig_index);
      if (replacement.IsInt32TruncationElimination()) {
        DCHECK(
            IsInt32TruncatedLoadPattern(Asm().input_graph(), ig_index, change));
        return Asm().MapToNewGraph(replacement.replacement());
      }
    }
    return Next::ReduceInputGraphChange(ig_index, change);
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::IsInt32TruncatedLoadPattern(), v8::internal::compiler::turboshaft::LoadEliminationReplacement::IsInt32TruncationElimination(), v8::internal::compiler::turboshaft::LoadEliminationReplacement::replacement(), and v8::internal::v8_flags.
Load()
template<class Next >
OpIndex REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::Load (OpIndex ig_index, const LoadOp & load) [inline]
Definition at line 795 of file late-load-elimination-reducer.h.
                                                                         {
    if (v8_flags.turboshaft_load_elimination) {
      Replacement replacement = analyzer_.GetReplacement(ig_index);
      if (replacement.IsLoadElimination()) {
        OpIndex replacement_ig_index = replacement.replacement();
        OpIndex replacement_idx = Asm().MapToNewGraph(replacement_ig_index);
        // The replacement might itself be a load that int32-truncated.
        if (analyzer_.GetReplacement(replacement_ig_index)
                .IsTaggedLoadToInt32Load()) {
          DCHECK_EQ(Asm().output_graph().Get(replacement_idx).outputs_rep()[0],
                    RegisterRepresentation::Word32());
        } else {
          DCHECK(Asm()
                     .output_graph()
                     .Get(replacement_idx)
                     .outputs_rep()[0]
                     .AllowImplicitRepresentationChangeTo(
                         load.outputs_rep()[0],
                         Asm().output_graph().IsCreatedFromTurbofan()));
        }
        return replacement_idx;
      } else if (replacement.IsTaggedLoadToInt32Load()) {
        auto loaded_rep = load.loaded_rep;
        auto result_rep = load.result_rep;
        DCHECK_EQ(result_rep, RegisterRepresentation::Tagged());
        loaded_rep = MemoryRepresentation::Int32();
        result_rep = RegisterRepresentation::Word32();
        return Asm().Load(Asm().MapToNewGraph(load.base()),
                          Asm().MapToNewGraph(load.index()), load.kind,
                          loaded_rep, result_rep, load.offset,
                          load.element_size_log2);
      }
    }
    return Next::ReduceInputGraphLoad(ig_index, load);
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::LoadEliminationReplacement::IsLoadElimination(), v8::internal::compiler::turboshaft::LoadEliminationReplacement::IsTaggedLoadToInt32Load(), v8::internal::compiler::turboshaft::LoadEliminationReplacement::replacement(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::v8_flags, and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
TaggedBitcast()
template<class Next >
OpIndex REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::TaggedBitcast (OpIndex ig_index, const TaggedBitcastOp & bitcast) [inline]
Definition at line 843 of file late-load-elimination-reducer.h.
                                                                            {
    if (v8_flags.turboshaft_load_elimination) {
      Replacement replacement = analyzer_.GetReplacement(ig_index);
      if (replacement.IsTaggedBitcastElimination()) {
        return OpIndex::Invalid();
      }
    }
    return Next::ReduceInputGraphTaggedBitcast(ig_index, bitcast);
  }
References v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::LoadEliminationReplacement::IsTaggedBitcastElimination(), and v8::internal::v8_flags.
Member Data Documentation
analyzer_
template<class Next >
LateLoadEliminationAnalyzer v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::analyzer_ [private]
Initial value:
{__ data(), __ modifiable_input_graph(),
                                        __ phase_zone(), __ data()->broker(),
                                        raw_base_assumption_}
Definition at line 868 of file late-load-elimination-reducer.h.
raw_base_assumption_
template<class Next >
RawBaseAssumption v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::raw_base_assumption_ [private]
Initial value:
=
      __ data() -> pipeline_kind() == TurboshaftPipelineKind::kCSA
          ? RawBaseAssumption::kMaybeInnerPointer
          : RawBaseAssumption::kNoInnerPointer
Definition at line 864 of file late-load-elimination-reducer.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/late-load-elimination-reducer.h