v8::internal::compiler::turboshaft::OutputGraphAssembler< Derived, Base > Class Template Reference
#include <copying-phase.h>
Private Member Functions
OpIndex Map (OpIndex index)
OptionalOpIndex Map (OptionalOpIndex index)
template<size_t N>
base::SmallVector< OpIndex, N > Map (base::Vector< const OpIndex > indices)
Derived * derived_this ()
Assembler< typename Base::ReducerList > * assembler ()
Friends
template<size_t I, class D >
struct FixedArityOperationT
Detailed Description
template<typename Derived, typename Base>
class v8::internal::compiler::turboshaft::OutputGraphAssembler< Derived, Base >
Definition at line 49 of file copying-phase.h.
Member Function Documentation
assembler()
template<typename Derived , typename Base >
Assembler<typename Base::ReducerList>* v8::internal::compiler::turboshaft::OutputGraphAssembler< Derived, Base >::assembler () [inline], [private]
Definition at line 81 of file copying-phase.h.
                                                   {
    return &derived_this()->Asm();
  }
References v8::internal::compiler::turboshaft::OutputGraphAssembler< Derived, Base >::derived_this().
derived_this()
template<typename Derived , typename Base >
Derived* v8::internal::compiler::turboshaft::OutputGraphAssembler< Derived, Base >::derived_this () [inline], [private]
Definition at line 80 of file copying-phase.h.
{ return static_cast<Derived*>(this); }
Referenced by v8::internal::compiler::turboshaft::OutputGraphAssembler< Derived, Base >::assembler(), and v8::internal::compiler::turboshaft::OutputGraphAssembler< Derived, Base >::Map().
Map() [1/3]
template<typename Derived , typename Base >
template<size_t N>
base::SmallVector<OpIndex, N> v8::internal::compiler::turboshaft::OutputGraphAssembler< Derived, Base >::Map (base::Vector< const OpIndex > indices) [inline], [private]
Definition at line 63 of file copying-phase.h.
                                                                     {
    return derived_this()->template MapToNewGraph<N>(indices);
  }
References v8::internal::compiler::turboshaft::OutputGraphAssembler< Derived, Base >::derived_this().
Map() [2/3]
template<typename Derived , typename Base >
OpIndex v8::internal::compiler::turboshaft::OutputGraphAssembler< Derived, Base >::Map (OpIndex index) [inline], [private]
Definition at line 56 of file copying-phase.h.
{ return derived_this()->MapToNewGraph(index); }
References v8::internal::compiler::turboshaft::OutputGraphAssembler< Derived, Base >::derived_this(), and v8::internal::index.
Map() [3/3]
template<typename Derived , typename Base >
OptionalOpIndex v8::internal::compiler::turboshaft::OutputGraphAssembler< Derived, Base >::Map (OptionalOpIndex index) [inline], [private]
Definition at line 58 of file copying-phase.h.
                                             {
    return derived_this()->MapToNewGraph(index);
  }
References v8::internal::compiler::turboshaft::OutputGraphAssembler< Derived, Base >::derived_this(), and v8::internal::index.
Friends And Related Function Documentation
FixedArityOperationT
template<typename Derived , typename Base >
template<size_t I, class D >
friend struct FixedArityOperationT [friend]
Definition at line 54 of file copying-phase.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/copying-phase.h