v8::internal::baseline::BaselineAssembler Class Reference
#include <baseline-assembler.h>
Classes
class ScratchRegisterScope
Public Types
enum class CompressionMode { kDefault
, kForceDecompression
 }
Public Member Functions
BaselineAssembler (MacroAssembler *masm)
void RegisterFrameAddress (interpreter::Register interpreter_register, Register rscratch)
MemOperand ContextOperand ()
MemOperand FunctionOperand ()
MemOperand FeedbackVectorOperand ()
MemOperand FeedbackCellOperand ()
void GetCode (LocalIsolate *isolate, CodeDesc *desc)
int pc_offset () const
void CodeEntry () const
void ExceptionHandler () const
void RecordComment (const char *string)
void Trap ()
void DebugBreak ()
template<typename Field >
void DecodeField (Register reg)
void Bind (Label *label)
void JumpTarget ()
void Jump (Label *target, Label::Distance distance=Label::kFar)
void JumpIfRoot (Register value, RootIndex index, Label *target, Label::Distance distance=Label::kFar)
void JumpIfNotRoot (Register value, RootIndex index, Label *target, Label ::Distance distance=Label::kFar)
void JumpIfSmi (Register value, Label *target, Label::Distance distance=Label::kFar)
void JumpIfNotSmi (Register value, Label *target, Label::Distance distance=Label::kFar)
void TestAndBranch (Register value, int mask, Condition cc, Label *target, Label::Distance distance=Label::kFar)
void JumpIf (Condition cc, Register lhs, const Operand &rhs, Label *target, Label::Distance distance=Label::kFar)
void JumpIfObjectType (Condition cc, Register object, InstanceType instance_type, Register map, Label *target, Label::Distance distance=Label::kFar)
void JumpIfObjectTypeFast (Condition cc, Register object, InstanceType instance_type, Label *target, Label::Distance distance=Label::kFar)
void JumpIfInstanceType (Condition cc, Register map, InstanceType instance_type, Label *target, Label::Distance distance=Label::kFar)
void JumpIfPointer (Condition cc, Register value, MemOperand operand, Label *target, Label::Distance distance=Label::kFar)
Condition CheckSmi (Register value)
void JumpIfSmi (Condition cc, Register value, Tagged< Smi > smi, Label *target, Label::Distance distance=Label::kFar)
void JumpIfSmi (Condition cc, Register lhs, Register rhs, Label *target, Label::Distance distance=Label::kFar)
void JumpIfImmediate (Condition cc, Register left, int right, Label *target, Label::Distance distance=Label::kFar)
void JumpIfTagged (Condition cc, Register value, MemOperand operand, Label *target, Label::Distance distance=Label::kFar)
void JumpIfTagged (Condition cc, MemOperand operand, Register value, Label *target, Label::Distance distance=Label::kFar)
void JumpIfByte (Condition cc, Register value, int32_t byte, Label *target, Label::Distance distance=Label::kFar)
void LoadMap (Register output, Register value)
void LoadRoot (Register output, RootIndex index)
void LoadNativeContextSlot (Register output, uint32_t index)
void Move (Register output, Register source)
void Move (Register output, MemOperand operand)
void Move (Register output, Tagged< Smi > value)
void Move (Register output, Tagged< TaggedIndex > value)
void Move (Register output, interpreter::Register source)
void Move (interpreter::Register output, Register source)
void Move (Register output, RootIndex source)
void Move (MemOperand output, Register source)
void Move (Register output, ExternalReference reference)
void Move (Register output, Handle< HeapObject > value)
void Move (Register output, int32_t immediate)
void MoveMaybeSmi (Register output, Register source)
void MoveSmi (Register output, Register source)
template<typename... T>
int Push (T... vals)
template<typename... T>
void PushReverse (T... vals)
template<typename... T>
void Pop (T... registers)
void CallBuiltin (Builtin builtin)
void TailCallBuiltin (Builtin builtin)
void CallRuntime (Runtime::FunctionId function, int nargs)
void LoadTaggedField (Register output, Register source, int offset)
void LoadTaggedSignedField (Register output, Register source, int offset)
void LoadTaggedSignedFieldAndUntag (Register output, Register source, int offset)
void LoadWord16FieldZeroExtend (Register output, Register source, int offset)
void LoadWord8Field (Register output, Register source, int offset)
void StoreTaggedSignedField (Register target, int offset, Tagged< Smi > value)
void StoreTaggedFieldWithWriteBarrier (Register target, int offset, Register value)
void StoreTaggedFieldNoWriteBarrier (Register target, int offset, Register value)
void LoadFixedArrayElement (Register output, Register array, int32_t index)
void LoadPrototype (Register prototype, Register object)
void TryLoadOptimizedOsrCode (Register scratch_and_result, Register feedback_vector, FeedbackSlot slot, Label *on_result, Label::Distance distance)
void AddToInterruptBudgetAndJumpIfNotExceeded (int32_t weight, Label *skip_interrupt_label)
void AddToInterruptBudgetAndJumpIfNotExceeded (Register weight, Label *skip_interrupt_label)
void LdaContextSlotNoCell (Register context, uint32_t index, uint32_t depth, CompressionMode compression_mode=CompressionMode::kDefault)
void StaContextSlotNoCell (Register context, Register value, uint32_t index, uint32_t depth)
void LdaModuleVariable (Register context, int cell_index, uint32_t depth)
void StaModuleVariable (Register context, Register value, int cell_index, uint32_t depth)
void IncrementSmi (MemOperand lhs)
void SmiUntag (Register value)
void SmiUntag (Register output, Register value)
void Word32And (Register output, Register lhs, int rhs)
void Switch (Register reg, int case_value_base, Label **labels, int num_labels)
void LoadRegister (Register output, interpreter::Register source)
void StoreRegister (interpreter::Register output, Register value)
void LoadFunction (Register output)
void LoadContext (Register output)
void StoreContext (Register context)
void LoadFeedbackCell (Register output)
void AssertFeedbackCell (Register object)
MacroAssembler * masm ()
Static Public Member Functions
static MemOperand RegisterFrameOperand (interpreter::Register interpreter_register)
static void EmitReturn (MacroAssembler *masm)
Private Attributes
MacroAssembler * masm_
ScratchRegisterScope * scratch_register_scope_ = nullptr
Detailed Description
Definition at line 16 of file baseline-assembler.h.
Member Enumeration Documentation
CompressionMode
enum v8::internal::baseline::BaselineAssembler::CompressionMode [strong]
Enumerator
kDefault
kForceDecompression
Definition at line 210 of file baseline-assembler.h.
                             {
    kDefault,
    kForceDecompression,
  };
Constructor & Destructor Documentation
BaselineAssembler()
v8::internal::baseline::BaselineAssembler::BaselineAssembler (MacroAssembler * masm) [inline], [explicit]
Definition at line 20 of file baseline-assembler.h.
: masm_(masm) {}
Member Function Documentation
AddToInterruptBudgetAndJumpIfNotExceeded() [1/2]
void v8::internal::baseline::BaselineAssembler::AddToInterruptBudgetAndJumpIfNotExceeded (int32_t weight, Label * skip_interrupt_label) [inline]
Definition at line 406 of file baseline-assembler-arm-inl.h.
                                                 {
  ASM_CODE_COMMENT(masm_);
  ScratchRegisterScope scratch_scope(this);
  Register feedback_cell = scratch_scope.AcquireScratch();
  LoadFeedbackCell(feedback_cell);
  Register interrupt_budget = scratch_scope.AcquireScratch();
  __ ldr(interrupt_budget,
         FieldMemOperand(feedback_cell, FeedbackCell::kInterruptBudgetOffset));
  // Remember to set flags as part of the add!
  __ add(interrupt_budget, interrupt_budget, Operand(weight), SetCC);
  __ str(interrupt_budget,
         FieldMemOperand(feedback_cell, FeedbackCell::kInterruptBudgetOffset));
  if (skip_interrupt_label) {
    // Use compare flags set by add
    DCHECK_LT(weight, 0);
    __ b(ge, skip_interrupt_label);
  }
}
References __, v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), ASM_CODE_COMMENT, DCHECK_LT, v8::internal::FieldMemOperand(), v8::internal::ge, LoadFeedbackCell(), masm_, and v8::internal::SetCC.
Referenced by EmitReturn().
AddToInterruptBudgetAndJumpIfNotExceeded() [2/2]
void v8::internal::baseline::BaselineAssembler::AddToInterruptBudgetAndJumpIfNotExceeded (Register weight, Label * skip_interrupt_label) [inline]
Definition at line 427 of file baseline-assembler-arm-inl.h.
                                                  {
  ASM_CODE_COMMENT(masm_);
  ScratchRegisterScope scratch_scope(this);
  Register feedback_cell = scratch_scope.AcquireScratch();
  LoadFeedbackCell(feedback_cell);
  Register interrupt_budget = scratch_scope.AcquireScratch();
  __ ldr(interrupt_budget,
         FieldMemOperand(feedback_cell, FeedbackCell::kInterruptBudgetOffset));
  // Remember to set flags as part of the add!
  __ add(interrupt_budget, interrupt_budget, weight, SetCC);
  __ str(interrupt_budget,
         FieldMemOperand(feedback_cell, FeedbackCell::kInterruptBudgetOffset));
  if (skip_interrupt_label) __ b(ge, skip_interrupt_label);
}
References __, v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), ASM_CODE_COMMENT, v8::internal::FieldMemOperand(), v8::internal::ge, LoadFeedbackCell(), masm_, and v8::internal::SetCC.
AssertFeedbackCell()
void v8::internal::baseline::BaselineAssembler::AssertFeedbackCell (Register object) [inline]
Referenced by LoadFeedbackCell().
Bind()
void v8::internal::baseline::BaselineAssembler::Bind (Label * label) [inline]
Definition at line 70 of file baseline-assembler-arm-inl.h.
{ __ bind(label); }
References __.
Referenced by EmitReturn().
CallBuiltin()
void v8::internal::baseline::BaselineAssembler::CallBuiltin (Builtin builtin) [inline]
Definition at line 69 of file baseline-assembler-inl.h.
                                                   {
  // BaselineAssemblerOptions defines how builtin calls are generated.
  __ CallBuiltin(builtin);
}
References __.
CallRuntime()
void v8::internal::baseline::BaselineAssembler::CallRuntime (Runtime::FunctionId function, int nargs) [inline]
Definition at line 65 of file baseline-assembler-inl.h.
                                                                         {
  __ CallRuntime(function, nargs);
}
References __.
Referenced by EmitReturn().
CheckSmi()
Condition v8::internal::baseline::BaselineAssembler::CheckSmi (Register value) [inline]
CodeEntry()
void v8::internal::baseline::BaselineAssembler::CodeEntry () const [inline]
Definition at line 52 of file baseline-assembler-inl.h.
{ __ CodeEntry(); }
References __.
ContextOperand()
MemOperand v8::internal::baseline::BaselineAssembler::ContextOperand () [inline]
Definition at line 79 of file baseline-assembler-inl.h.
                                             {
  return RegisterFrameOperand(interpreter::Register::current_context());
}
References v8::internal::interpreter::Register::current_context(), and RegisterFrameOperand().
DebugBreak()
void v8::internal::baseline::BaselineAssembler::DebugBreak () [inline]
Definition at line 59 of file baseline-assembler-inl.h.
{ __ DebugBreak(); }
References __.
DecodeField()
template<typename Field >
void v8::internal::baseline::BaselineAssembler::DecodeField (Register reg) [inline]
Definition at line 153 of file baseline-assembler-inl.h.
                                                {
  __ DecodeField<Field>(reg);
}
References __.
EmitReturn()
void v8::internal::baseline::BaselineAssembler::EmitReturn (MacroAssembler * masm) [inline], [static]
Definition at line 518 of file baseline-assembler-arm-inl.h.
                                                       {
  ASM_CODE_COMMENT(masm);
  BaselineAssembler basm(masm);
  Register weight = BaselineLeaveFrameDescriptor::WeightRegister();
  Register params_size = BaselineLeaveFrameDescriptor::ParamsSizeRegister();
  {
    ASM_CODE_COMMENT_STRING(masm, "Update Interrupt Budget");
    Label skip_interrupt_label;
    __ AddToInterruptBudgetAndJumpIfNotExceeded(weight, &skip_interrupt_label);
    {
      __ masm()->SmiTag(params_size);
      __ Push(params_size, kInterpreterAccumulatorRegister);
      __ LoadContext(kContextRegister);
      __ LoadFunction(kJSFunctionRegister);
      __ Push(kJSFunctionRegister);
      __ CallRuntime(Runtime::kBytecodeBudgetInterrupt_Sparkplug, 1);
      __ Pop(kInterpreterAccumulatorRegister, params_size);
      __ masm()->SmiUntag(params_size);
    }
    __ Bind(&skip_interrupt_label);
  }
  BaselineAssembler::ScratchRegisterScope temps(&basm);
  Register actual_params_size = temps.AcquireScratch();
  // Compute the size of the actual parameters + receiver.
  __ Move(actual_params_size,
          MemOperand(fp, StandardFrameConstants::kArgCOffset));
  // If actual is bigger than formal, then we should use it to free up the stack
  // arguments.
  __ masm()->cmp(params_size, actual_params_size);
  __ masm()->mov(params_size, actual_params_size, LeaveCC, kLessThan);
  // Leave the frame (also dropping the register file).
  __ masm()->LeaveFrame(StackFrame::BASELINE);
  // Drop receiver + arguments.
  __ masm()->DropArguments(params_size);
  __ masm()->Ret();
}
References __, v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), AddToInterruptBudgetAndJumpIfNotExceeded(), ASM_CODE_COMMENT, ASM_CODE_COMMENT_STRING, Bind(), CallRuntime(), v8::internal::Assembler::cmp(), v8::internal::MacroAssembler::DropArguments(), v8::internal::StandardFrameConstants::kArgCOffset, v8::internal::kContextRegister, v8::internal::kInterpreterAccumulatorRegister, v8::internal::kJSFunctionRegister, v8::internal::kLessThan, v8::internal::LeaveCC, v8::internal::MacroAssembler::LeaveFrame(), LoadContext(), LoadFunction(), masm(), v8::internal::MacroAssembler::mov(), Move(), Pop(), Push(), v8::internal::MacroAssembler::Ret(), v8::internal::MacroAssembler::SmiTag(), v8::internal::MacroAssembler::SmiUntag(), and v8::internal::BaselineLeaveFrameDescriptor::WeightRegister().
ExceptionHandler()
void v8::internal::baseline::BaselineAssembler::ExceptionHandler () const [inline]
Definition at line 53 of file baseline-assembler-inl.h.
{ __ ExceptionHandler(); }
References __.
FeedbackCellOperand()
MemOperand v8::internal::baseline::BaselineAssembler::FeedbackCellOperand () [inline]
Definition at line 66 of file baseline-assembler-arm-inl.h.
                                                  {
  return MemOperand(fp, BaselineFrameConstants::kFeedbackCellFromFp);
}
References v8::internal::BaselineFrameConstants::kFeedbackCellFromFp.
Referenced by LoadFeedbackCell().
FeedbackVectorOperand()
MemOperand v8::internal::baseline::BaselineAssembler::FeedbackVectorOperand () [inline]
Definition at line 63 of file baseline-assembler-arm-inl.h.
                                                    {
  return MemOperand(fp, BaselineFrameConstants::kFeedbackVectorFromFp);
}
References v8::internal::UnoptimizedFrameConstants::kFeedbackVectorFromFp.
FunctionOperand()
MemOperand v8::internal::baseline::BaselineAssembler::FunctionOperand () [inline]
Definition at line 82 of file baseline-assembler-inl.h.
                                              {
  return RegisterFrameOperand(interpreter::Register::function_closure());
}
References v8::internal::interpreter::Register::function_closure(), and RegisterFrameOperand().
GetCode()
void v8::internal::baseline::BaselineAssembler::GetCode (LocalIsolate * isolate, CodeDesc * desc) [inline]
Definition at line 48 of file baseline-assembler-inl.h.
                                                                     {
  __ GetCode(isolate, desc);
}
References __.
IncrementSmi()
void v8::internal::baseline::BaselineAssembler::IncrementSmi (MemOperand lhs) [inline]
Definition at line 496 of file baseline-assembler-arm-inl.h.
                                                   {
  BaselineAssembler::ScratchRegisterScope temps(this);
  Register tmp = temps.AcquireScratch();
  __ ldr(tmp, lhs);
  __ add(tmp, tmp, Operand(Smi::FromInt(1)));
  __ str(tmp, lhs);
}
References __, v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), and v8::internal::Smi::FromInt().
Jump()
void v8::internal::baseline::BaselineAssembler::Jump (Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 76 of file baseline-assembler-arm-inl.h.
                                                                  {
  __ b(target);
}
References __.
JumpIf()
void v8::internal::baseline::BaselineAssembler::JumpIf (Condition cc, Register lhs, const Operand & rhs, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 112 of file baseline-assembler-arm-inl.h.
                                                             {
  __ cmp(lhs, Operand(rhs));
  __ b(cc, target);
}
References __, and v8::internal::cc.
Referenced by JumpIfByte(), JumpIfImmediate(), JumpIfInstanceType(), JumpIfObjectType(), JumpIfPointer(), JumpIfSmi(), and JumpIfTagged().
JumpIfByte()
void v8::internal::baseline::BaselineAssembler::JumpIfByte (Condition cc, Register value, int32_t byte, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 183 of file baseline-assembler-arm-inl.h.
                                                                 {
  JumpIf(cc, value, Operand(byte), target);
}
References v8::internal::cc, JumpIf(), and v8::internal::value.
JumpIfImmediate()
void v8::internal::baseline::BaselineAssembler::JumpIfImmediate (Condition cc, Register left, int right, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 95 of file baseline-assembler-arm-inl.h.
                                                                {
  JumpIf(cc, left, Operand(right), target, distance);
}
References v8::internal::cc, and JumpIf().
JumpIfInstanceType()
void v8::internal::baseline::BaselineAssembler::JumpIfInstanceType (Condition cc, Register map, InstanceType instance_type, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 135 of file baseline-assembler-arm-inl.h.
                                                                         {
  ScratchRegisterScope temps(this);
  Register type = temps.AcquireScratch();
  if (v8_flags.debug_code) {
    __ AssertNotSmi(map);
    __ CompareObjectType(map, type, type, MAP_TYPE);
    __ Assert(eq, AbortReason::kUnexpectedValue);
  }
  __ ldrh(type, FieldMemOperand(map, Map::kInstanceTypeOffset));
  JumpIf(cc, type, Operand(instance_type), target);
}
References __, v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), v8::internal::cc, v8::internal::eq, v8::internal::FieldMemOperand(), JumpIf(), v8::internal::tracing::type, and v8::internal::v8_flags.
JumpIfNotRoot()
void v8::internal::baseline::BaselineAssembler::JumpIfNotRoot (Register value, RootIndex index, Label * target, Label ::Distance distance = Label::kFar) [inline]
Definition at line 85 of file baseline-assembler-arm-inl.h.
                                                                    {
  __ JumpIfNotRoot(value, index, target);
}
References __, v8::internal::index, and v8::internal::value.
JumpIfNotSmi()
void v8::internal::baseline::BaselineAssembler::JumpIfNotSmi (Register value, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 101 of file baseline-assembler-arm-inl.h.
                                                    {
  __ JumpIfNotSmi(value, target);
}
References __, and v8::internal::value.
JumpIfObjectType()
void v8::internal::baseline::BaselineAssembler::JumpIfObjectType (Condition cc, Register object, InstanceType instance_type, Register map, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 125 of file baseline-assembler-arm-inl.h.
                                                        {
  ScratchRegisterScope temps(this);
  Register type = temps.AcquireScratch();
  __ LoadMap(map, object);
  __ ldrh(type, FieldMemOperand(map, Map::kInstanceTypeOffset));
  JumpIf(cc, type, Operand(instance_type), target);
}
References __, v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), v8::internal::cc, v8::internal::FieldMemOperand(), JumpIf(), LoadMap(), and v8::internal::tracing::type.
Referenced by JumpIfObjectTypeFast().
JumpIfObjectTypeFast()
void v8::internal::baseline::BaselineAssembler::JumpIfObjectTypeFast (Condition cc, Register object, InstanceType instance_type, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 117 of file baseline-assembler-arm-inl.h.
                                                                     {
  ScratchRegisterScope temps(this);
  Register scratch = temps.AcquireScratch();
  JumpIfObjectType(cc, object, instance_type, scratch, target, distance);
}
References v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), v8::internal::cc, and JumpIfObjectType().
JumpIfPointer()
void v8::internal::baseline::BaselineAssembler::JumpIfPointer (Condition cc, Register value, MemOperand operand, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 148 of file baseline-assembler-arm-inl.h.
                                                     {
  ScratchRegisterScope temps(this);
  Register tmp = temps.AcquireScratch();
  __ ldr(tmp, operand);
  JumpIf(cc, value, Operand(tmp), target);
}
References __, v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), v8::internal::cc, JumpIf(), and v8::internal::value.
JumpIfRoot()
void v8::internal::baseline::BaselineAssembler::JumpIfRoot (Register value, RootIndex index, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 80 of file baseline-assembler-arm-inl.h.
                                                                 {
  __ JumpIfRoot(value, index, target);
}
References __, v8::internal::index, and v8::internal::value.
JumpIfSmi() [1/3]
void v8::internal::baseline::BaselineAssembler::JumpIfSmi (Condition cc, Register lhs, Register rhs, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 161 of file baseline-assembler-arm-inl.h.
                                                                {
  __ AssertSmi(lhs);
  __ AssertSmi(rhs);
  JumpIf(cc, lhs, Operand(rhs), target);
}
References __, v8::internal::cc, and JumpIf().
JumpIfSmi() [2/3]
void v8::internal::baseline::BaselineAssembler::JumpIfSmi (Condition cc, Register value, Tagged< Smi > smi, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 156 of file baseline-assembler-arm-inl.h.
                                                                {
  __ AssertSmi(value);
  JumpIf(cc, value, Operand(smi), target);
}
References __, v8::internal::cc, JumpIf(), and v8::internal::value.
JumpIfSmi() [3/3]
void v8::internal::baseline::BaselineAssembler::JumpIfSmi (Register value, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 90 of file baseline-assembler-arm-inl.h.
                                                 {
  __ JumpIfSmi(value, target);
}
References __, and v8::internal::value.
JumpIfTagged() [1/2]
void v8::internal::baseline::BaselineAssembler::JumpIfTagged (Condition cc, MemOperand operand, Register value, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 175 of file baseline-assembler-arm-inl.h.
                                                    {
  ScratchRegisterScope temps(this);
  Register tmp = temps.AcquireScratch();
  __ ldr(tmp, operand);
  JumpIf(cc, tmp, Operand(value), target);
}
References __, v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), v8::internal::cc, JumpIf(), and v8::internal::value.
JumpIfTagged() [2/2]
void v8::internal::baseline::BaselineAssembler::JumpIfTagged (Condition cc, Register value, MemOperand operand, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 167 of file baseline-assembler-arm-inl.h.
                                                    {
  ScratchRegisterScope temps(this);
  Register tmp = temps.AcquireScratch();
  __ ldr(tmp, operand);
  JumpIf(cc, value, Operand(tmp), target);
}
References __, v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), v8::internal::cc, JumpIf(), and v8::internal::value.
JumpTarget()
void v8::internal::baseline::BaselineAssembler::JumpTarget () [inline]
Definition at line 72 of file baseline-assembler-arm-inl.h.
                                   {
  // NOP on arm.
}
LdaContextSlotNoCell()
void v8::internal::baseline::BaselineAssembler::LdaContextSlotNoCell (Register context, uint32_t index, uint32_t depth, CompressionMode compression_mode = CompressionMode::kDefault) [inline]
Definition at line 444 of file baseline-assembler-arm-inl.h.
                                                                               {
  for (; depth > 0; --depth) {
    LoadTaggedField(context, context, Context::kPreviousOffset);
  }
  LoadTaggedField(kInterpreterAccumulatorRegister, context,
                  Context::OffsetOfElementAt(index));
}
References v8::internal::index, v8::internal::kInterpreterAccumulatorRegister, v8::internal::Context::kPreviousOffset, LoadTaggedField(), and v8::internal::Context::OffsetOfElementAt().
LdaModuleVariable()
void v8::internal::baseline::BaselineAssembler::LdaModuleVariable (Register context, int cell_index, uint32_t depth) [inline]
Definition at line 463 of file baseline-assembler-arm-inl.h.
                                                          {
  for (; depth > 0; --depth) {
    LoadTaggedField(context, context, Context::kPreviousOffset);
  }
  LoadTaggedField(context, context, Context::kExtensionOffset);
  if (cell_index > 0) {
    LoadTaggedField(context, context, SourceTextModule::kRegularExportsOffset);
    // The actual array index is (cell_index - 1).
    cell_index -= 1;
  } else {
    LoadTaggedField(context, context, SourceTextModule::kRegularImportsOffset);
    // The actual array index is (-cell_index - 1).
    cell_index = -cell_index - 1;
  }
  LoadFixedArrayElement(context, context, cell_index);
  LoadTaggedField(kInterpreterAccumulatorRegister, context, Cell::kValueOffset);
}
References v8::internal::Context::kExtensionOffset, v8::internal::kInterpreterAccumulatorRegister, v8::internal::Context::kPreviousOffset, LoadFixedArrayElement(), and LoadTaggedField().
LoadContext()
void v8::internal::baseline::BaselineAssembler::LoadContext (Register output) [inline]
Definition at line 127 of file baseline-assembler-inl.h.
                                                   {
  LoadRegister(output, interpreter::Register::current_context());
}
References v8::internal::interpreter::Register::current_context(), and LoadRegister().
Referenced by EmitReturn(), and v8::internal::baseline::detail::MoveArgumentsForBuiltin().
LoadFeedbackCell()
void v8::internal::baseline::BaselineAssembler::LoadFeedbackCell (Register output) [inline]
Definition at line 145 of file baseline-assembler-inl.h.
                                                        {
  Move(output, FeedbackCellOperand());
  ScratchRegisterScope scratch_scope(this);
  Register scratch = scratch_scope.AcquireScratch();
  __ AssertFeedbackCell(output, scratch);
}
References __, v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), AssertFeedbackCell(), FeedbackCellOperand(), and Move().
Referenced by AddToInterruptBudgetAndJumpIfNotExceeded().
LoadFixedArrayElement()
void v8::internal::baseline::BaselineAssembler::LoadFixedArrayElement (Register output, Register array, int32_t index) [inline]
Definition at line 117 of file baseline-assembler-inl.h.
                                                             {
  LoadTaggedField(output, array,
                  OFFSET_OF_DATA_START(FixedArray) + index * kTaggedSize);
}
References v8::internal::index, v8::internal::kTaggedSize, LoadTaggedField(), and OFFSET_OF_DATA_START.
Referenced by LdaModuleVariable(), and StaModuleVariable().
LoadFunction()
void v8::internal::baseline::BaselineAssembler::LoadFunction (Register output) [inline]
Definition at line 130 of file baseline-assembler-inl.h.
                                                    {
  LoadRegister(output, interpreter::Register::function_closure());
}
References v8::internal::interpreter::Register::function_closure(), and LoadRegister().
Referenced by EmitReturn().
LoadMap()
void v8::internal::baseline::BaselineAssembler::LoadMap (Register output, Register value) [inline]
Definition at line 86 of file baseline-assembler-inl.h.
                                                               {
  __ LoadMap(output, value);
}
References __, and v8::internal::value.
Referenced by JumpIfObjectType(), and LoadPrototype().
LoadNativeContextSlot()
void v8::internal::baseline::BaselineAssembler::LoadNativeContextSlot (Register output, uint32_t index) [inline]
Definition at line 92 of file baseline-assembler-inl.h.
                                                                             {
  __ LoadNativeContextSlot(output, index);
}
References __, and v8::internal::index.
LoadPrototype()
void v8::internal::baseline::BaselineAssembler::LoadPrototype (Register prototype, Register object) [inline]
Definition at line 123 of file baseline-assembler-inl.h.
                                                                         {
  __ LoadMap(prototype, object);
  LoadTaggedField(prototype, prototype, Map::kPrototypeOffset);
}
References __, v8::internal::kPrototypeOffset, LoadMap(), LoadTaggedField(), and v8::internal::prototype.
LoadRegister()
void v8::internal::baseline::BaselineAssembler::LoadRegister (Register output, interpreter::Register source) [inline]
Definition at line 136 of file baseline-assembler-inl.h.
                                                                 {
  Move(output, source);
}
References Move().
Referenced by LoadContext(), and LoadFunction().
LoadRoot()
void v8::internal::baseline::BaselineAssembler::LoadRoot (Register output, RootIndex index) [inline]
Definition at line 89 of file baseline-assembler-inl.h.
                                                                 {
  __ LoadRoot(output, index);
}
References __, and v8::internal::index.
Referenced by Move().
LoadTaggedField()
void v8::internal::baseline::BaselineAssembler::LoadTaggedField (Register output, Register source, int offset) [inline]
Definition at line 323 of file baseline-assembler-arm-inl.h.
                                                    {
  __ ldr(output, FieldMemOperand(source, offset));
}
References __, and v8::internal::FieldMemOperand().
Referenced by LdaContextSlotNoCell(), LdaModuleVariable(), LoadFixedArrayElement(), LoadPrototype(), StaContextSlotNoCell(), StaModuleVariable(), and TryLoadOptimizedOsrCode().
LoadTaggedSignedField()
void v8::internal::baseline::BaselineAssembler::LoadTaggedSignedField (Register output, Register source, int offset) [inline]
Definition at line 328 of file baseline-assembler-arm-inl.h.
                                                          {
  __ ldr(output, FieldMemOperand(source, offset));
}
References __, and v8::internal::FieldMemOperand().
Referenced by LoadTaggedSignedFieldAndUntag().
LoadTaggedSignedFieldAndUntag()
void v8::internal::baseline::BaselineAssembler::LoadTaggedSignedFieldAndUntag (Register output, Register source, int offset) [inline]
Definition at line 333 of file baseline-assembler-arm-inl.h.
                                                                  {
  LoadTaggedSignedField(output, source, offset);
  SmiUntag(output);
}
References LoadTaggedSignedField(), and SmiUntag().
LoadWord16FieldZeroExtend()
void v8::internal::baseline::BaselineAssembler::LoadWord16FieldZeroExtend (Register output, Register source, int offset) [inline]
Definition at line 340 of file baseline-assembler-arm-inl.h.
                                                                               {
  __ ldrh(output, FieldMemOperand(source, offset));
}
References __, and v8::internal::FieldMemOperand().
LoadWord8Field()
void v8::internal::baseline::BaselineAssembler::LoadWord8Field (Register output, Register source, int offset) [inline]
Definition at line 345 of file baseline-assembler-arm-inl.h.
                                                   {
  __ ldrb(output, FieldMemOperand(source, offset));
}
References __, and v8::internal::FieldMemOperand().
masm()
MacroAssembler* v8::internal::baseline::BaselineAssembler::masm () [inline]
Definition at line 253 of file baseline-assembler.h.
{ return masm_; }
References masm_.
Referenced by v8::internal::baseline::EnsureAccumulatorPreservedScope::AssertEqualToAccumulator(), EmitReturn(), v8::internal::baseline::detail::PopAllHelper< Register >::Pop(), v8::internal::baseline::detail::PopAllHelper< Register, Register, T... >::Pop(), v8::internal::baseline::detail::PushAllHelper< Arg >::Push(), v8::internal::baseline::detail::PushHelper< Arg >::Push(), v8::internal::baseline::detail::PushAllHelper< Arg1, Arg2, Args... >::Push(), v8::internal::baseline::detail::PushHelper< interpreter::RegisterList >::Push(), v8::internal::baseline::detail::PushAllHelper< Arg1, Arg2, Args... >::PushReverse(), v8::internal::baseline::detail::PushHelper< interpreter::RegisterList >::PushReverse(), v8::internal::baseline::SaveAccumulatorScope::SaveAccumulatorScope(), and v8::internal::baseline::SaveAccumulatorScope::~SaveAccumulatorScope().
Move() [1/11]
void v8::internal::baseline::BaselineAssembler::Move (interpreter::Register output, Register source) [inline]
Definition at line 188 of file baseline-assembler-arm-inl.h.
                                                                        {
  Move(RegisterFrameOperand(output), source);
}
References Move(), and RegisterFrameOperand().
Move() [2/11]
void v8::internal::baseline::BaselineAssembler::Move (MemOperand output, Register source) [inline]
Definition at line 194 of file baseline-assembler-arm-inl.h.
                                                               {
  __ str(source, output);
}
References __.
Move() [3/11]
void v8::internal::baseline::BaselineAssembler::Move (Register output, ExternalReference reference) [inline]
Definition at line 197 of file baseline-assembler-arm-inl.h.
                                                                         {
  __ Move32BitImmediate(output, Operand(reference));
}
References __.
Move() [4/11]
void v8::internal::baseline::BaselineAssembler::Move (Register output, Handle< HeapObject > value) [inline]
Definition at line 200 of file baseline-assembler-arm-inl.h.
                                                                      {
  __ Move32BitImmediate(output, Operand(value));
}
References __, and v8::internal::value.
Move() [5/11]
void v8::internal::baseline::BaselineAssembler::Move (Register output, int32_t immediate) [inline]
Definition at line 203 of file baseline-assembler-arm-inl.h.
                                                           {
  __ mov(output, Operand(value));
}
References __, and v8::internal::value.
Move() [6/11]
void v8::internal::baseline::BaselineAssembler::Move (Register output, interpreter::Register source) [inline]
Definition at line 96 of file baseline-assembler-inl.h.
                                                                        {
  return __ Move(output, RegisterFrameOperand(source));
}
References __, Move(), and RegisterFrameOperand().
Move() [7/11]
void v8::internal::baseline::BaselineAssembler::Move (Register output, MemOperand operand) [inline]
Definition at line 105 of file baseline-assembler-inl.h.
                                                                {
  __ Move(output, operand);
}
References __, and Move().
Referenced by Move().
Move() [8/11]
void v8::internal::baseline::BaselineAssembler::Move (Register output, Register source) [inline]
Definition at line 102 of file baseline-assembler-inl.h.
                                                             {
  __ Move(output, source);
}
References __.
Referenced by EmitReturn(), LoadFeedbackCell(), LoadRegister(), Move(), v8::internal::baseline::detail::ArgumentSettingHelper< Descriptor, ArgIndex, true, Arg, Args... >::Set(), v8::internal::baseline::detail::ArgumentSettingHelper< Descriptor, ArgIndex, true, interpreter::RegisterList >::Set(), StoreRegister(), v8::internal::baseline::detail::ToRegister(), and TryLoadOptimizedOsrCode().
Move() [9/11]
void v8::internal::baseline::BaselineAssembler::Move (Register output, RootIndex source) [inline]
Definition at line 99 of file baseline-assembler-inl.h.
                                                              {
  return __ LoadRoot(output, source);
}
References __, and LoadRoot().
Move() [10/11]
void v8::internal::baseline::BaselineAssembler::Move (Register output, Tagged< Smi > value) [inline]
Definition at line 108 of file baseline-assembler-inl.h.
                                                               {
  __ Move(output, value);
}
References __, Move(), and v8::internal::value.
Move() [11/11]
void v8::internal::baseline::BaselineAssembler::Move (Register output, Tagged< TaggedIndex > value) [inline]
Definition at line 191 of file baseline-assembler-arm-inl.h.
                                                                       {
  __ mov(output, Operand(value.ptr()));
}
References __, and v8::internal::value.
MoveMaybeSmi()
void v8::internal::baseline::BaselineAssembler::MoveMaybeSmi (Register output, Register source) [inline]
Definition at line 206 of file baseline-assembler-arm-inl.h.
                                                                     {
  __ mov(output, source);
}
References __.
MoveSmi()
void v8::internal::baseline::BaselineAssembler::MoveSmi (Register output, Register source) [inline]
Definition at line 209 of file baseline-assembler-arm-inl.h.
                                                                {
  __ mov(output, source);
}
References __.
pc_offset()
int v8::internal::baseline::BaselineAssembler::pc_offset () const [inline]
Definition at line 51 of file baseline-assembler-inl.h.
{ return __ pc_offset(); }
References __.
Pop()
template<typename... T>
void v8::internal::baseline::BaselineAssembler::Pop (T... registers) [inline]
Definition at line 319 of file baseline-assembler-arm-inl.h.
                                          {
  detail::PopAllHelper<T...>::Pop(this, registers...);
}
Referenced by EmitReturn(), v8::internal::baseline::EnsureAccumulatorPreservedScope::~EnsureAccumulatorPreservedScope(), and v8::internal::baseline::SaveAccumulatorScope::~SaveAccumulatorScope().
Push()
template<typename... T>
int v8::internal::baseline::BaselineAssembler::Push (T... vals) [inline]
Definition at line 309 of file baseline-assembler-arm-inl.h.
                                     {
  return detail::PushAllHelper<T...>::Push(this, vals...);
}
Referenced by EmitReturn(), v8::internal::baseline::EnsureAccumulatorPreservedScope::EnsureAccumulatorPreservedScope(), v8::internal::baseline::SaveAccumulatorScope::SaveAccumulatorScope(), and v8::internal::baseline::detail::ArgumentSettingHelper< Descriptor, ArgIndex, false, Arg, Args... >::Set().
PushReverse()
template<typename... T>
void v8::internal::baseline::BaselineAssembler::PushReverse (T... vals) [inline]
Definition at line 314 of file baseline-assembler-arm-inl.h.
                                             {
  detail::PushAllHelper<T...>::PushReverse(this, vals...);
}
Referenced by v8::internal::baseline::detail::ArgumentSettingHelper< Descriptor, ArgIndex, false, Arg, Args... >::Set().
RecordComment()
void v8::internal::baseline::BaselineAssembler::RecordComment (const char * string) [inline]
Definition at line 54 of file baseline-assembler-inl.h.
                                                        {
  if (!v8_flags.code_comments) return;
  __ RecordComment(string);
}
References __, and v8::internal::v8_flags.
RegisterFrameAddress()
void v8::internal::baseline::BaselineAssembler::RegisterFrameAddress (interpreter::Register interpreter_register, Register rscratch) [inline]
Definition at line 58 of file baseline-assembler-arm-inl.h.
                                                                 {
  return __ add(rscratch, fp,
                Operand(interpreter_register.ToOperand() * kSystemPointerSize));
}
References __, v8::internal::kSystemPointerSize, and v8::internal::interpreter::Register::ToOperand().
RegisterFrameOperand()
MemOperand v8::internal::baseline::BaselineAssembler::RegisterFrameOperand (interpreter::Register interpreter_register) [inline], [static]
Definition at line 54 of file baseline-assembler-arm-inl.h.
                                              {
  return MemOperand(fp, interpreter_register.ToOperand() * kSystemPointerSize);
}
References v8::internal::kSystemPointerSize, and v8::internal::interpreter::Register::ToOperand().
Referenced by ContextOperand(), FunctionOperand(), Move(), v8::internal::baseline::detail::PushSingle(), and v8::internal::baseline::detail::ArgumentSettingHelper< Descriptor, ArgIndex, true, interpreter::RegisterList >::Set().
SmiUntag() [1/2]
void v8::internal::baseline::BaselineAssembler::SmiUntag (Register output, Register value) [inline]
Definition at line 113 of file baseline-assembler-inl.h.
                                                                {
  __ SmiUntag(output, value);
}
References __, SmiUntag(), and v8::internal::value.
SmiUntag() [2/2]
void v8::internal::baseline::BaselineAssembler::SmiUntag (Register value) [inline]
Definition at line 112 of file baseline-assembler-inl.h.
{ __ SmiUntag(reg); }
References __.
Referenced by LoadTaggedSignedFieldAndUntag(), and SmiUntag().
StaContextSlotNoCell()
void v8::internal::baseline::BaselineAssembler::StaContextSlotNoCell (Register context, Register value, uint32_t index, uint32_t depth) [inline]
Definition at line 454 of file baseline-assembler-arm-inl.h.
                                                                             {
  for (; depth > 0; --depth) {
    LoadTaggedField(context, context, Context::kPreviousOffset);
  }
  StoreTaggedFieldWithWriteBarrier(context, Context::OffsetOfElementAt(index),
                                   value);
}
References v8::internal::index, v8::internal::Context::kPreviousOffset, LoadTaggedField(), v8::internal::Context::OffsetOfElementAt(), StoreTaggedFieldWithWriteBarrier(), and v8::internal::value.
StaModuleVariable()
void v8::internal::baseline::BaselineAssembler::StaModuleVariable (Register context, Register value, int cell_index, uint32_t depth) [inline]
Definition at line 482 of file baseline-assembler-arm-inl.h.
                                                                          {
  for (; depth > 0; --depth) {
    LoadTaggedField(context, context, Context::kPreviousOffset);
  }
  LoadTaggedField(context, context, Context::kExtensionOffset);
  LoadTaggedField(context, context, SourceTextModule::kRegularExportsOffset);
  // The actual array index is (cell_index - 1).
  cell_index -= 1;
  LoadFixedArrayElement(context, context, cell_index);
  StoreTaggedFieldWithWriteBarrier(context, Cell::kValueOffset, value);
}
References v8::internal::Context::kExtensionOffset, v8::internal::Context::kPreviousOffset, LoadFixedArrayElement(), LoadTaggedField(), StoreTaggedFieldWithWriteBarrier(), and v8::internal::value.
StoreContext()
void v8::internal::baseline::BaselineAssembler::StoreContext (Register context) [inline]
Definition at line 133 of file baseline-assembler-inl.h.
                                                     {
  StoreRegister(interpreter::Register::current_context(), context);
}
References v8::internal::interpreter::Register::current_context(), and StoreRegister().
StoreRegister()
void v8::internal::baseline::BaselineAssembler::StoreRegister (interpreter::Register output, Register value) [inline]
Definition at line 140 of file baseline-assembler-inl.h.
                                                      {
  Move(output, value);
}
References Move(), and v8::internal::value.
Referenced by StoreContext().
StoreTaggedFieldNoWriteBarrier()
void v8::internal::baseline::BaselineAssembler::StoreTaggedFieldNoWriteBarrier (Register target, int offset, Register value) [inline]
Definition at line 369 of file baseline-assembler-arm-inl.h.
                                                                       {
  __ str(value, FieldMemOperand(target, offset));
}
References __, v8::internal::FieldMemOperand(), and v8::internal::value.
Referenced by TryLoadOptimizedOsrCode().
StoreTaggedFieldWithWriteBarrier()
void v8::internal::baseline::BaselineAssembler::StoreTaggedFieldWithWriteBarrier (Register target, int offset, Register value) [inline]
Definition at line 359 of file baseline-assembler-arm-inl.h.
                                                                         {
  ASM_CODE_COMMENT(masm_);
  DCHECK(!AreAliased(target, value));
  __ str(value, FieldMemOperand(target, offset));
  __ RecordWriteField(target, offset, value, kLRHasNotBeenSaved,
                      SaveFPRegsMode::kIgnore);
}
References __, v8::internal::AreAliased(), ASM_CODE_COMMENT, v8::internal::DCHECK(), v8::internal::FieldMemOperand(), v8::internal::kIgnore, v8::internal::kLRHasNotBeenSaved, masm_, and v8::internal::value.
Referenced by StaContextSlotNoCell(), and StaModuleVariable().
StoreTaggedSignedField()
void v8::internal::baseline::BaselineAssembler::StoreTaggedSignedField (Register target, int offset, Tagged< Smi > value) [inline]
Definition at line 350 of file baseline-assembler-arm-inl.h.
                                                                  {
  ASM_CODE_COMMENT(masm_);
  ScratchRegisterScope temps(this);
  Register tmp = temps.AcquireScratch();
  __ mov(tmp, Operand(value));
  __ str(tmp, FieldMemOperand(target, offset));
}
References __, v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), ASM_CODE_COMMENT, v8::internal::FieldMemOperand(), masm_, and v8::internal::value.
Switch()
void v8::internal::baseline::BaselineAssembler::Switch (Register reg, int case_value_base, Label ** labels, int num_labels) [inline]
Definition at line 508 of file baseline-assembler-arm-inl.h.
                                                               {
  __ MacroAssembler::Switch(Register::no_reg(), reg, case_value_base, labels,
                            num_labels);
}
References __, v8::internal::Register::no_reg(), and v8::internal::MacroAssembler::Switch().
TailCallBuiltin()
void v8::internal::baseline::BaselineAssembler::TailCallBuiltin (Builtin builtin) [inline]
Definition at line 74 of file baseline-assembler-inl.h.
                                                       {
  // BaselineAssemblerOptions defines how builtin tail calls are generated.
  __ TailCallBuiltin(builtin);
}
References __.
TestAndBranch()
void v8::internal::baseline::BaselineAssembler::TestAndBranch (Register value, int mask, Condition cc, Label * target, Label::Distance distance = Label::kFar) [inline]
Definition at line 106 of file baseline-assembler-arm-inl.h.
                                                                    {
  __ tst(value, Operand(mask));
  __ b(cc, target);
}
References __, v8::internal::cc, and v8::internal::value.
Trap()
void v8::internal::baseline::BaselineAssembler::Trap () [inline]
Definition at line 58 of file baseline-assembler-inl.h.
{ __ Trap(); }
References __.
TryLoadOptimizedOsrCode()
void v8::internal::baseline::BaselineAssembler::TryLoadOptimizedOsrCode (Register scratch_and_result, Register feedback_vector, FeedbackSlot slot, Label * on_result, Label::Distance distance) [inline]
Definition at line 375 of file baseline-assembler-arm-inl.h.
                                                               {
  Label fallthrough;
  LoadTaggedField(scratch_and_result, feedback_vector,
                  FeedbackVector::OffsetOfElementAt(slot.ToInt()));
  __ LoadWeakValue(scratch_and_result, scratch_and_result, &fallthrough);
  // Is it marked_for_deoptimization? If yes, clear the slot.
  {
    ScratchRegisterScope temps(this);
    // The entry references a CodeWrapper object. Unwrap it now.
    __ ldr(scratch_and_result,
           FieldMemOperand(scratch_and_result, CodeWrapper::kCodeOffset));
    Register scratch = temps.AcquireScratch();
    __ TestCodeIsMarkedForDeoptimization(scratch_and_result, scratch);
    __ b(eq, on_result);
    __ mov(scratch, __ ClearedValue());
    StoreTaggedFieldNoWriteBarrier(
        feedback_vector, FeedbackVector::OffsetOfElementAt(slot.ToInt()),
        scratch);
  }
  __ bind(&fallthrough);
  Move(scratch_and_result, 0);
}
References __, v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), v8::internal::ClearedValue(), v8::internal::eq, v8::internal::FieldMemOperand(), LoadTaggedField(), Move(), v8::internal::FeedbackVector::OffsetOfElementAt(), StoreTaggedFieldNoWriteBarrier(), and v8::internal::FeedbackSlot::ToInt().
Word32And()
void v8::internal::baseline::BaselineAssembler::Word32And (Register output, Register lhs, int rhs) [inline]
Definition at line 504 of file baseline-assembler-arm-inl.h.
                                                                        {
  __ and_(output, lhs, Operand(rhs));
}
References __.
Member Data Documentation
masm_
MacroAssembler* v8::internal::baseline::BaselineAssembler::masm_ [private]
Definition at line 256 of file baseline-assembler.h.
Referenced by AddToInterruptBudgetAndJumpIfNotExceeded(), masm(), StoreTaggedFieldWithWriteBarrier(), and StoreTaggedSignedField().
scratch_register_scope_
ScratchRegisterScope* v8::internal::baseline::BaselineAssembler::scratch_register_scope_ = nullptr [private]
Definition at line 257 of file baseline-assembler.h.
Referenced by v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::ScratchRegisterScope(), and v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::~ScratchRegisterScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/baseline/baseline-assembler.h
/mnt/V8SourceCode/src/baseline/arm/baseline-assembler-arm-inl.h
/mnt/V8SourceCode/src/baseline/arm64/baseline-assembler-arm64-inl.h
/mnt/V8SourceCode/src/baseline/baseline-assembler-inl.h
/mnt/V8SourceCode/src/baseline/ia32/baseline-assembler-ia32-inl.h
/mnt/V8SourceCode/src/baseline/loong64/baseline-assembler-loong64-inl.h
/mnt/V8SourceCode/src/baseline/mips64/baseline-assembler-mips64-inl.h
/mnt/V8SourceCode/src/baseline/ppc/baseline-assembler-ppc-inl.h
/mnt/V8SourceCode/src/baseline/riscv/baseline-assembler-riscv-inl.h
/mnt/V8SourceCode/src/baseline/s390/baseline-assembler-s390-inl.h
/mnt/V8SourceCode/src/baseline/x64/baseline-assembler-x64-inl.h