v8::internal::compiler::GapResolver::Assembler Class Reference
#include <gap-resolver.h>
Public Member Functions
virtual ~Assembler ()=default
virtual void AssembleMove (InstructionOperand *source, InstructionOperand *destination)=0
virtual void AssembleSwap (InstructionOperand *source, InstructionOperand *destination)=0
virtual AllocatedOperand Push (InstructionOperand *src)=0
virtual void Pop (InstructionOperand *dest, MachineRepresentation rep)=0
virtual void PopTempStackSlots ()=0
virtual void MoveToTempLocation (InstructionOperand *src, MachineRepresentation rep)=0
virtual void MoveTempLocationTo (InstructionOperand *dst, MachineRepresentation rep)=0
virtual void SetPendingMove (MoveOperands *move)=0
Public Attributes
int temp_slots_ = 0
Detailed Description
Definition at line 17 of file gap-resolver.h.
Constructor & Destructor Documentation
 Assembler()
virtual v8::internal::compiler::GapResolver::Assembler::~Assembler () [virtual], [default]
Member Function Documentation
AssembleMove()
virtual void v8::internal::compiler::GapResolver::Assembler::AssembleMove (InstructionOperand * source, InstructionOperand * destination) [pure virtual]
Implemented in v8::internal::compiler::CodeGenerator.
Referenced by v8::internal::compiler::GapResolver::PerformCycle(), v8::internal::compiler::GapResolver::PerformMoveHelper(), and v8::internal::compiler::GapResolver::Resolve().
AssembleSwap()
virtual void v8::internal::compiler::GapResolver::Assembler::AssembleSwap (InstructionOperand * source, InstructionOperand * destination) [pure virtual]
Implemented in v8::internal::compiler::CodeGenerator.
Referenced by v8::internal::compiler::GapResolver::PerformCycle().
MoveTempLocationTo()
virtual void v8::internal::compiler::GapResolver::Assembler::MoveTempLocationTo (InstructionOperand * dst, MachineRepresentation rep) [pure virtual]
Implemented in v8::internal::compiler::CodeGenerator.
Referenced by v8::internal::compiler::GapResolver::PerformCycle().
MoveToTempLocation()
virtual void v8::internal::compiler::GapResolver::Assembler::MoveToTempLocation (InstructionOperand * src, MachineRepresentation rep) [pure virtual]
Implemented in v8::internal::compiler::CodeGenerator.
Referenced by v8::internal::compiler::GapResolver::PerformCycle().
Pop()
virtual void v8::internal::compiler::GapResolver::Assembler::Pop (InstructionOperand * dest, MachineRepresentation rep) [pure virtual]
Implemented in v8::internal::compiler::CodeGenerator.
PopTempStackSlots()
virtual void v8::internal::compiler::GapResolver::Assembler::PopTempStackSlots () [pure virtual]
Implemented in v8::internal::compiler::CodeGenerator.
Referenced by v8::internal::compiler::GapResolver::Resolve().
Push()
virtual AllocatedOperand v8::internal::compiler::GapResolver::Assembler::Push (InstructionOperand * src) [pure virtual]
Implemented in v8::internal::compiler::CodeGenerator.
Referenced by v8::internal::compiler::GapResolver::PerformMove().
SetPendingMove()
virtual void v8::internal::compiler::GapResolver::Assembler::SetPendingMove (MoveOperands * move) [pure virtual]
Implemented in v8::internal::compiler::CodeGenerator.
Referenced by v8::internal::compiler::GapResolver::PerformCycle().
Member Data Documentation
temp_slots_
int v8::internal::compiler::GapResolver::Assembler::temp_slots_ = 0
Definition at line 48 of file gap-resolver.h.
Referenced by v8::internal::compiler::CodeGenerator::Pop(), v8::internal::compiler::CodeGenerator::PopTempStackSlots(), and v8::internal::compiler::CodeGenerator::Push().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/gap-resolver.h