v8::internal::wasm::StackMemory Class Reference
#include <stacks.h>
Classes
class StackSegment
struct StackSwitchInfo
Public Member Functions
~StackMemory ()
void * jslimit () const
Address base () const
bool IsValidContinuation (Tagged< WasmContinuationObject > cont)
JumpBuffer * jmpbuf ()
bool Contains (Address addr)
int id ()
bool IsActive ()
void set_index (size_t index)
size_t index ()
size_t allocated_size ()
void FillWith (uint8_t value)
void Iterate (v8::internal::RootVisitor *v, Isolate *isolate)
Address old_fp ()
bool Grow (Address current_fp, size_t min_size)
Address Shrink ()
void ShrinkTo (Address stack_address)
void Reset ()
const StackSwitchInfo & stack_switch_info () const
void set_stack_switch_info (Address fp, Address sp)
void clear_stack_switch_info ()
Static Public Member Functions
static std::unique_ptr< StackMemory > New ()
static StackMemory * GetCentralStackView (Isolate *isolate)
static int JSStackLimitMarginKB ()
constexpr static uint32_t stack_switch_source_fp_offset ()
constexpr static uint32_t stack_switch_target_sp_offset ()
constexpr static uint32_t jmpbuf_offset ()
Private Member Functions
StackMemory ()
StackMemory (uint8_t *limit, size_t size)
Private Attributes
uint8_t * limit_
size_t size_
bool owned_
JumpBuffer jmpbuf_
int id_
size_t index_
StackSwitchInfo stack_switch_info_
StackSegment * first_segment_ = nullptr
StackSegment * active_segment_ = nullptr
Tagged< WasmContinuationObject > current_cont_ = {}
Friends
class StackPool
Detailed Description
Definition at line 56 of file stacks.h.
Constructor & Destructor Documentation
 StackMemory()
v8::internal::wasm::StackMemory::~StackMemory ()
Definition at line 20 of file stacks.cc.
                          {
  if (v8_flags.trace_wasm_stack_switching) {
    PrintF("Delete stack #%d\n", id_);
  }
  auto segment = first_segment_;
  while (segment) {
    auto next_segment = segment->next_segment_;
    delete segment;
    segment = next_segment;
  }
}
References first_segment_, id_, v8::internal::wasm::StackMemory::StackSegment::next_segment_, v8::internal::PrintF(), and v8::internal::v8_flags.
StackMemory() [1/2]
v8::internal::wasm::StackMemory::StackMemory () [private]
Definition at line 37 of file stacks.cc.
                         : owned_(true) {
  static std::atomic<int> next_id(1);
  id_ = next_id.fetch_add(1);
  size_t kJsStackSizeKB = v8_flags.wasm_stack_switching_stack_size;
  // v8_flags.stack_size is a size of the central stack and maximum
  // size of a secondary stack to grow.
  const size_t size_limit = v8_flags.stack_size;
  PageAllocator* allocator = GetPlatformPageAllocator();
  auto page_size = allocator->AllocatePageSize();
  size_t initial_size = std::min<size_t>(
      size_limit * KB,
      kJsStackSizeKB * KB + SimulatorStack::JSStackLimitMargin());
  first_segment_ =
      new StackSegment(RoundUp(initial_size, page_size) / page_size);
  active_segment_ = first_segment_;
  size_ = first_segment_->size_;
  limit_ = first_segment_->limit_;
  if (v8_flags.trace_wasm_stack_switching) {
    PrintF("Allocate stack #%d (limit: %p, base: %p, size: %zu)\n", id_, limit_,
           limit_ + size_, size_);
  }
}
References active_segment_, v8::PageAllocator::AllocatePageSize(), first_segment_, v8::internal::GetPlatformPageAllocator(), id_, v8::internal::KB, v8::internal::wasm::StackMemory::StackSegment::limit_, limit_, v8::internal::PrintF(), RoundUp(), v8::internal::wasm::StackMemory::StackSegment::size_, size_, and v8::internal::v8_flags.
Referenced by GetCentralStackView(), and New().
StackMemory() [2/2]
v8::internal::wasm::StackMemory::StackMemory (uint8_t * limit, size_t size) [private]
Definition at line 61 of file stacks.cc.
    : limit_(limit), size_(size), owned_(false) {
  id_ = 0;
}
References id_.
Member Function Documentation
allocated_size()
size_t v8::internal::wasm::StackMemory::allocated_size () [inline]
Definition at line 105 of file stacks.h.
                          {
    size_t size = 0;
    auto segment = first_segment_;
    while (segment) {
      size += segment->size_;
      segment = segment->next_segment_;
    }
    return size;
  }
References first_segment_, and size().
base()
Address v8::internal::wasm::StackMemory::base () const [inline]
Definition at line 68 of file stacks.h.
                       {
    Address memory_limit = active_segment_
                               ? active_segment_->base()
                               : reinterpret_cast<Address>(limit_ + size_);
#ifdef USE_SIMULATOR
    // To perform runtime calls with different signatures, some simulators
    // prepare a fixed number of arguments which is an upper bound of the actual
    // parameter count. The extra stack slots contain arbitrary data and are
    // never used, but with stack-switching this can happen close to the stack
    // start, so we need to reserve a safety gap to ensure that the addresses
    // are at least mapped to prevent a crash.
    constexpr int kStackBaseSafetyOffset = 20 * kSystemPointerSize;
#else
    constexpr int kStackBaseSafetyOffset = 0;
#endif
    return memory_limit - kStackBaseSafetyOffset;
  }
References active_segment_, v8::internal::wasm::StackMemory::StackSegment::base(), v8::internal::kSystemPointerSize, limit_, and size_.
Referenced by Contains(), v8::internal::wasm::grow_stack(), and ShrinkTo().
clear_stack_switch_info()
void v8::internal::wasm::StackMemory::clear_stack_switch_info () [inline]
Definition at line 163 of file stacks.h.
                                 {
    stack_switch_info_.source_fp = kNullAddress;
  }
References v8::internal::kNullAddress, v8::internal::wasm::StackMemory::StackSwitchInfo::source_fp, and stack_switch_info_.
Referenced by Reset().
Contains()
bool v8::internal::wasm::StackMemory::Contains (Address addr) [inline]
Definition at line 87 of file stacks.h.
                              {
    if (!owned_) {
      return reinterpret_cast<Address>(jslimit()) <= addr && addr < base();
    }
    for (auto segment = first_segment_; segment;
         segment = segment->next_segment_) {
      if (reinterpret_cast<Address>(segment->limit_) <= addr &&
          addr < segment->base()) {
        return true;
      }
      if (segment == active_segment_) break;
    }
    return false;
  }
References active_segment_, base(), first_segment_, jslimit(), v8::internal::wasm::StackMemory::StackSegment::next_segment_, and owned_.
FillWith()
void v8::internal::wasm::StackMemory::FillWith (uint8_t value) [inline]
Definition at line 114 of file stacks.h.
                               {
    auto segment = first_segment_;
    while (segment) {
      memset(segment->limit_, value, segment->size_);
      segment = segment->next_segment_;
    }
  }
References first_segment_, and v8::internal::value.
GetCentralStackView()
StackMemory * v8::internal::wasm::StackMemory::GetCentralStackView (Isolate * isolate) [static]
Definition at line 15 of file stacks.cc.
                                                              {
  base::Vector<uint8_t> view = SimulatorStack::GetCentralStackView(isolate);
  return new StackMemory(view.begin(), view.size());
}
References v8::base::Vector< T >::begin(), v8::base::Vector< T >::size(), and StackMemory().
Grow()
bool v8::internal::wasm::StackMemory::Grow (Address current_fp, size_t min_size)
Definition at line 100 of file stacks.cc.
                                                          {
  DCHECK(owned_);
  while (V8_UNLIKELY(active_segment_->next_segment_ != nullptr &&
                     active_segment_->next_segment_->size_ < min_size)) {
    // If the next segment is too small to fit the evicted frame, remove it.
    StackSegment* to_delete = active_segment_->next_segment_;
    active_segment_->next_segment_ =
        active_segment_->next_segment_->next_segment_;
    if (active_segment_->next_segment_ != nullptr) {
      active_segment_->next_segment_->prev_segment_ = active_segment_;
    }
    delete to_delete;
  }
  if (active_segment_->next_segment_ != nullptr) {
    active_segment_ = active_segment_->next_segment_;
  } else {
    PageAllocator* allocator = GetPlatformPageAllocator();
    auto page_size = allocator->AllocatePageSize();
    const size_t size_limit = RoundUp(v8_flags.stack_size * KB, page_size);
    DCHECK_GE(size_limit, size_);
    size_t room_to_grow = RoundDown(size_limit - size_, page_size);
    min_size = RoundUp(min_size, page_size);
    if (room_to_grow < min_size) {
      if (v8_flags.trace_wasm_stack_switching) {
        PrintF("Stack #%d reached the grow limit %zu bytes\n", id_, size_limit);
      }
      return false;
    }
    size_t new_size =
        std::clamp(2 * active_segment_->size_, min_size, room_to_grow);
    DCHECK_EQ(new_size % page_size, 0);
    auto new_segment = new StackSegment(new_size / page_size);
    new_segment->prev_segment_ = active_segment_;
    active_segment_->next_segment_ = new_segment;
    active_segment_ = new_segment;
  }
  active_segment_->old_fp = current_fp;
  size_ += active_segment_->size_;
  if (v8_flags.trace_wasm_stack_switching) {
    PrintF("Grow stack #%d by %zu bytes (limit: %p, base: %p)\n", id_,
           active_segment_->size_, active_segment_->limit_,
           active_segment_->limit_ + active_segment_->size_);
  }
  return true;
}
References active_segment_, v8::PageAllocator::AllocatePageSize(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::GetPlatformPageAllocator(), id_, v8::internal::KB, v8::internal::wasm::StackMemory::StackSegment::limit_, v8::internal::wasm::StackMemory::StackSegment::next_segment_, v8::internal::wasm::StackMemory::StackSegment::old_fp, owned_, v8::internal::wasm::StackMemory::StackSegment::prev_segment_, v8::internal::PrintF(), RoundDown(), RoundUp(), v8::internal::wasm::StackMemory::StackSegment::size_, size_, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::wasm::grow_stack().
id()
int v8::internal::wasm::StackMemory::id () [inline]
Definition at line 101 of file stacks.h.
{ return id_; }
References id_.
index()
size_t v8::internal::wasm::StackMemory::index () [inline]
Definition at line 104 of file stacks.h.
{ return index_; }
References index_.
Referenced by set_index().
IsActive()
bool v8::internal::wasm::StackMemory::IsActive () [inline]
Definition at line 102 of file stacks.h.
{ return jmpbuf_.state == JumpBuffer::Active; }
References v8::internal::wasm::JumpBuffer::Active, jmpbuf_, and v8::internal::wasm::JumpBuffer::state.
Referenced by v8::internal::wasm::grow_stack(), and v8::internal::wasm::shrink_stack().
IsValidContinuation()
bool v8::internal::wasm::StackMemory::IsValidContinuation (Tagged< WasmContinuationObject > cont)
Definition at line 180 of file stacks.cc.
                                                                         {
  return current_cont_ == cont;
}
References current_cont_.
Iterate()
void v8::internal::wasm::StackMemory::Iterate (v8::internal::RootVisitor * v, Isolate * isolate)
Definition at line 91 of file stacks.cc.
                                                                    {
  for (StackFrameIterator it(isolate, this); !it.done(); it.Advance()) {
    it.frame()->Iterate(v);
  }
  v->VisitRootPointer(
      Root::kStackRoots, nullptr,
      FullObjectSlot(reinterpret_cast<Address>(&this->current_cont_)));
}
References current_cont_, v8::internal::StackFrameIteratorBase::done(), and v8::internal::RootVisitor::VisitRootPointer().
jmpbuf()
JumpBuffer* v8::internal::wasm::StackMemory::jmpbuf () [inline]
Definition at line 86 of file stacks.h.
{ return &jmpbuf_; }
References jmpbuf_.
Referenced by v8::internal::wasm::load_old_fp(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::shrink_stack(), and v8::internal::Isolate::UnwindAndFindHandler().
jmpbuf_offset()
constexpr static uint32_t v8::internal::wasm::StackMemory::jmpbuf_offset () [inline], [static], [constexpr]
Definition at line 193 of file stacks.h.
                                            {
    return OFFSET_OF(StackMemory, jmpbuf_);
  }
References jmpbuf_, and OFFSET_OF.
jslimit()
void * v8::internal::wasm::StackMemory::jslimit () const
Definition at line 32 of file stacks.cc.
                                 {
  return (active_segment_ ? active_segment_->limit_ : limit_) +
         SimulatorStack::JSStackLimitMargin();
}
References active_segment_, v8::internal::wasm::StackMemory::StackSegment::limit_, and limit_.
Referenced by Contains(), v8::internal::wasm::grow_stack(), and v8::internal::wasm::shrink_stack().
JSStackLimitMarginKB()
static int v8::internal::wasm::StackMemory::JSStackLimitMarginKB () [inline], [static]
Definition at line 167 of file stacks.h.
                                    {
    if (v8_flags.experimental_wasm_growable_stacks) {
      // The limiting factor for this margin is the stack space used by outgoing
      // stack parameters in wasm. They can take up to 16KB (1000 simd
      // parameters, minus register parameters) and are not taken into account
      // by stack checks.
      // TODO(42204615): look into changing the stack check to take outgoing
      // stack parameters into account.
      static_assert(kMaxValueTypeSize == 16);
      static_assert(kV8MaxWasmFunctionParams == 1000);
      return 20;
    } else {
      return DEBUG_BOOL ? 80 : 40;
    }
  }
References DEBUG_BOOL, v8::internal::wasm::kMaxValueTypeSize, v8::internal::wasm::kV8MaxWasmFunctionParams, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::grow_stack().
New()
static std::unique_ptr<StackMemory> v8::internal::wasm::StackMemory::New () [inline], [static]
Definition at line 58 of file stacks.h.
                                          {
    return std::unique_ptr<StackMemory>(new StackMemory());
  }
References StackMemory().
Referenced by v8::internal::wasm::StackPool::GetOrAllocate().
old_fp()
Address v8::internal::wasm::StackMemory::old_fp () [inline]
Definition at line 123 of file stacks.h.
{ return active_segment_->old_fp; }
References active_segment_, and v8::internal::wasm::StackMemory::StackSegment::old_fp.
Referenced by v8::internal::wasm::load_old_fp(), and Shrink().
Reset()
void v8::internal::wasm::StackMemory::Reset ()
Definition at line 173 of file stacks.cc.
                        {
  active_segment_ = first_segment_;
  size_ = active_segment_->size_;
  clear_stack_switch_info();
  current_cont_ = {};
}
References active_segment_, clear_stack_switch_info(), current_cont_, first_segment_, v8::internal::wasm::StackMemory::StackSegment::size_, and size_.
set_index()
void v8::internal::wasm::StackMemory::set_index (size_t index) [inline]
Definition at line 103 of file stacks.h.
{ index_ = index; }
References index(), and index_.
set_stack_switch_info()
void v8::internal::wasm::StackMemory::set_stack_switch_info (Address fp, Address sp) [inline]
Definition at line 160 of file stacks.h.
                                                     {
    stack_switch_info_ = {fp, sp};
  }
References stack_switch_info_.
Shrink()
Address v8::internal::wasm::StackMemory::Shrink ()
Definition at line 146 of file stacks.cc.
                            {
  DCHECK(owned_);
  DCHECK_NE(active_segment_->prev_segment_, nullptr);
  Address old_fp = active_segment_->old_fp;
  size_ -= active_segment_->size_;
  active_segment_->old_fp = 0;
  active_segment_ = active_segment_->prev_segment_;
  if (v8_flags.trace_wasm_stack_switching) {
    PrintF("Shrink stack #%d (limit: %p, base: %p)\n", id_,
           active_segment_->limit_,
           active_segment_->limit_ + active_segment_->size_);
  }
  return old_fp;
}
References active_segment_, v8::internal::DCHECK(), DCHECK_NE, id_, v8::internal::wasm::StackMemory::StackSegment::limit_, old_fp(), v8::internal::wasm::StackMemory::StackSegment::old_fp, owned_, v8::internal::wasm::StackMemory::StackSegment::prev_segment_, v8::internal::PrintF(), v8::internal::wasm::StackMemory::StackSegment::size_, size_, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::shrink_stack(), and ShrinkTo().
ShrinkTo()
void v8::internal::wasm::StackMemory::ShrinkTo (Address stack_address)
Definition at line 161 of file stacks.cc.
                                                {
  DCHECK_NOT_NULL(active_segment_);
  while (active_segment_) {
    if (stack_address <= active_segment_->base() &&
        stack_address >= reinterpret_cast<Address>(active_segment_->limit_)) {
      return;
    }
    Shrink();
  }
  UNREACHABLE();
}
References active_segment_, base(), DCHECK_NOT_NULL, v8::internal::wasm::StackMemory::StackSegment::limit_, Shrink(), and v8::internal::UNREACHABLE().
stack_switch_info()
const StackSwitchInfo& v8::internal::wasm::StackMemory::stack_switch_info () const [inline]
Definition at line 157 of file stacks.h.
                                                   {
    return stack_switch_info_;
  }
References stack_switch_info_.
stack_switch_source_fp_offset()
constexpr static uint32_t v8::internal::wasm::StackMemory::stack_switch_source_fp_offset () [inline], [static], [constexpr]
Definition at line 185 of file stacks.h.
                                                            {
    return OFFSET_OF(StackMemory, stack_switch_info_) +
           OFFSET_OF(StackMemory::StackSwitchInfo, source_fp);
  }
References OFFSET_OF, and stack_switch_info_.
Referenced by v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchBackFromCentralStack(), and v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStack().
stack_switch_target_sp_offset()
constexpr static uint32_t v8::internal::wasm::StackMemory::stack_switch_target_sp_offset () [inline], [static], [constexpr]
Definition at line 189 of file stacks.h.
                                                            {
    return OFFSET_OF(StackMemory, stack_switch_info_) +
           OFFSET_OF(StackMemory::StackSwitchInfo, target_sp);
  }
References OFFSET_OF, and stack_switch_info_.
Referenced by v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStack().
Friends And Related Function Documentation
StackPool
friend class StackPool [friend]
Definition at line 183 of file stacks.h.
Member Data Documentation
active_segment_
StackSegment* v8::internal::wasm::StackMemory::active_segment_ = nullptr [private]
Definition at line 216 of file stacks.h.
Referenced by base(), Contains(), Grow(), jslimit(), old_fp(), Reset(), Shrink(), ShrinkTo(), and StackMemory().
current_cont_
Tagged<WasmContinuationObject> v8::internal::wasm::StackMemory::current_cont_ = {} [private]
Definition at line 217 of file stacks.h.
Referenced by IsValidContinuation(), Iterate(), and Reset().
first_segment_
StackSegment* v8::internal::wasm::StackMemory::first_segment_ = nullptr [private]
Definition at line 215 of file stacks.h.
Referenced by allocated_size(), Contains(), FillWith(), Reset(), StackMemory(), and ~StackMemory().
id_
int v8::internal::wasm::StackMemory::id_ [private]
Definition at line 209 of file stacks.h.
Referenced by Grow(), id(), Shrink(), StackMemory(), and ~StackMemory().
index_
size_t v8::internal::wasm::StackMemory::index_ [private]
Definition at line 213 of file stacks.h.
Referenced by index(), and set_index().
jmpbuf_
JumpBuffer v8::internal::wasm::StackMemory::jmpbuf_ [private]
Definition at line 207 of file stacks.h.
Referenced by IsActive(), jmpbuf(), and jmpbuf_offset().
limit_
uint8_t* v8::internal::wasm::StackMemory::limit_ [private]
Definition at line 204 of file stacks.h.
Referenced by base(), jslimit(), StackMemory(), and v8::internal::wasm::StackMemory::StackSegment::~StackSegment().
owned_
bool v8::internal::wasm::StackMemory::owned_ [private]
Definition at line 206 of file stacks.h.
Referenced by Contains(), Grow(), and Shrink().
size_
size_t v8::internal::wasm::StackMemory::size_ [private]
Definition at line 205 of file stacks.h.
Referenced by v8::internal::wasm::StackPool::Add(), base(), v8::internal::wasm::StackPool::GetOrAllocate(), Grow(), v8::internal::wasm::StackPool::ReleaseFinishedStacks(), Reset(), Shrink(), v8::internal::wasm::StackPool::Size(), StackMemory(), and v8::internal::wasm::StackMemory::StackSegment::~StackSegment().
stack_switch_info_
StackSwitchInfo v8::internal::wasm::StackMemory::stack_switch_info_ [private]
Definition at line 214 of file stacks.h.
Referenced by clear_stack_switch_info(), set_stack_switch_info(), stack_switch_info(), stack_switch_source_fp_offset(), and stack_switch_target_sp_offset().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/stacks.h
/mnt/V8SourceCode/src/wasm/stacks.cc