v8::internal::EphemeronHashTable::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > object)
Additional Inherited Members
Detailed Description
Definition at line 1469 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::EphemeronHashTable::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 1472 of file objects-body-descriptors-inl.h.
                                                                    {
    int entries_start = EphemeronHashTable::OffsetOfElementAt(
        EphemeronHashTable::kElementsStartIndex);
    IteratePointers(obj, OFFSET_OF_DATA_START(EphemeronHashTable),
                    entries_start, v);
    Tagged<EphemeronHashTable> table = UncheckedCast<EphemeronHashTable>(obj);
    for (InternalIndex i : table->IterateEntries()) {
      const int key_index = EphemeronHashTable::EntryToIndex(i);
      const int value_index = EphemeronHashTable::EntryToValueIndex(i);
      IterateEphemeron(obj, i.as_int(), OffsetOfElementAt(key_index),
                       OffsetOfElementAt(value_index), v);
    }
  }
References v8::internal::BodyDescriptorBase::IterateEphemeron(), v8::internal::BodyDescriptorBase::IteratePointers(), OFFSET_OF_DATA_START, and v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::OffsetOfElementAt().
SizeOf()
static int v8::internal::EphemeronHashTable::BodyDescriptor::SizeOf (Tagged< Map > map, Tagged< HeapObject > object) [inline], [static]
Definition at line 1487 of file objects-body-descriptors-inl.h.
                                                                       {
    return object->SizeFromMap(map);
  }
Referenced by v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitEphemeronHashTable(), and v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitEphemeronHashTable().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h