v8::internal::compiler::DeoptimizationEntry Class Reference
#include <instruction.h>
Public Member Functions
DeoptimizationEntry (FrameStateDescriptor *descriptor, DeoptimizeKind kind, DeoptimizeReason reason, NodeId node_id, FeedbackSource const &feedback)
FrameStateDescriptor * descriptor () const
DeoptimizeKind kind () const
DeoptimizeReason reason () const
FeedbackSource const & feedback () const
Private Attributes
FrameStateDescriptor *const descriptor_
const DeoptimizeKind kind_
const DeoptimizeReason reason_
const FeedbackSource feedback_
Detailed Description
Definition at line 1643 of file instruction.h.
Constructor & Destructor Documentation
DeoptimizationEntry()
v8::internal::compiler::DeoptimizationEntry::DeoptimizationEntry (FrameStateDescriptor * descriptor, DeoptimizeKind kind, DeoptimizeReason reason, NodeId node_id, FeedbackSource const & feedback) [inline]
Definition at line 1645 of file instruction.h.
      : descriptor_(descriptor),
        kind_(kind),
        reason_(reason),
#ifdef DEBUG
        node_id_(node_id),
#endif // DEBUG
        feedback_(feedback) {
    USE(node_id);
  }
References USE.
Member Function Documentation
descriptor()
FrameStateDescriptor* v8::internal::compiler::DeoptimizationEntry::descriptor () const [inline]
Definition at line 1658 of file instruction.h.
{ return descriptor_; }
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslation(), and v8::internal::compiler::CodeGenerator::RecordDeoptInfo().
feedback()
FeedbackSource const& v8::internal::compiler::DeoptimizationEntry::feedback () const [inline]
Definition at line 1664 of file instruction.h.
{ return feedback_; }
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslation().
kind()
DeoptimizeKind v8::internal::compiler::DeoptimizationEntry::kind () const [inline]
Definition at line 1659 of file instruction.h.
{ return kind_; }
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslation().
reason()
DeoptimizeReason v8::internal::compiler::DeoptimizationEntry::reason () const [inline]
Definition at line 1660 of file instruction.h.
{ return reason_; }
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslation().
Member Data Documentation
descriptor_
FrameStateDescriptor* const v8::internal::compiler::DeoptimizationEntry::descriptor_ [private]
Definition at line 1667 of file instruction.h.
feedback_
const FeedbackSource v8::internal::compiler::DeoptimizationEntry::feedback_ [private]
Definition at line 1673 of file instruction.h.
kind_
const DeoptimizeKind v8::internal::compiler::DeoptimizationEntry::kind_ [private]
Definition at line 1668 of file instruction.h.
reason_
const DeoptimizeReason v8::internal::compiler::DeoptimizationEntry::reason_ [private]
Definition at line 1669 of file instruction.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/instruction.h