v8::internal::Object Class Reference
#include <objects.h>
Classes
struct Comparer
struct FullPtrComparer
struct Hasher
struct KeyEqualSafe
Public Types
enum class Conversion { kToNumber
, kToNumeric
 }
Public Member Functions
template<typename T , template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< T >, DirectHandle< T >>) V8_WARN_UNUSED_RESULT static inline Maybe< double > IntegerValue(Isolate *isolate
template<typename IsolateT >
bool BooleanValue (Tagged< Object > obj, IsolateT *isolate)
Static Public Member Functions
static V8_WARN_UNUSED_RESULT Maybe< bool > IsArray (DirectHandle< Object > object)
static double NumberValue (Tagged< Number > obj)
static double NumberValue (Tagged< Object > obj)
static double NumberValue (Tagged< HeapNumber > obj)
static double NumberValue (Tagged< Smi > obj)
static V8_EXPORT_PRIVATE bool ToInt32 (Tagged< Object > obj, int32_t *value)
static bool ToUint32 (Tagged< Object > obj, uint32_t *value)
static Representation OptimalRepresentation (Tagged< Object > obj, PtrComprCageBase cage_base)
static ElementsKind OptimalElementsKind (Tagged< Object > obj, PtrComprCageBase cage_base)
static bool FitsRepresentation (Tagged< Object > obj, Representation representation, bool allow_coercion=true)
static bool FilterKey (Tagged< Object > obj, PropertyFilter filter)
static DirectHandle< FieldType > OptimalType (Tagged< Object > obj, Isolate *isolate, Representation representation)
static V8_EXPORT_PRIVATE Handle< UnionOf< JSAny, Hole > > NewStorageFor (Isolate *isolate, Handle< UnionOf< JSAny, Hole >> object, Representation representation)
template<AllocationType allocation_type = AllocationType::kYoung, typename IsolateT >
static Handle< JSAny > WrapForRead (IsolateT *isolate, Handle< JSAny > object, Representation representation)
static bool HasValidElements (Tagged< Object > obj)
template<typename IsolateT >
static V8_EXPORT_PRIVATE bool BooleanValue (Tagged< Object > obj, IsolateT *isolate)
static Tagged< Object > ToBoolean (Tagged< Object > obj, Isolate *isolate)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT Maybe< ComparisonResult > Compare (Isolate *isolate, DirectHandle< Object > x, DirectHandle< Object > y)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT Maybe< bool > Equals (Isolate *isolate, DirectHandle< Object > x, DirectHandle< Object > y)
static V8_EXPORT_PRIVATE bool StrictEquals (Tagged< Object > obj, Tagged< Object > that)
template<typename T , template< typename > typename HandleType>
requires(std::is_convertible_v< HandleType< T >, DirectHandle< T >>) V8_WARN_UNUSED_RESULT static inline typename HandleType< JSReceiver > static V8_WARN_UNUSED_RESULT MaybeHandle< JSReceiver > ToObjectImpl (Isolate *isolate, DirectHandle< Object > object, const char *method_name=nullptr)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSReceiver > ConvertReceiver (Isolate *isolate, DirectHandle< Object > object)
template<typename T , template< typename > typename HandleType>
static V8_WARN_UNUSED_RESULT HandleType< Name >::MaybeType ToName(Isolate *isolate, HandleType< Object > input) requires(std requires(std::is_convertible_v< HandleType< T >, DirectHandle< T >>) V8_WARN_UNUSED_RESULT static inline typename HandleType< Object > requires(std::is_convertible_v< HandleType< T >, DirectHandle< T >>) V8_WARN_UNUSED_RESULT static inline typename HandleType< Number > requires(std::is_convertible_v< HandleType< T >, DirectHandle< T >>) V8_WARN_UNUSED_RESULT static inline typename HandleType< Object > requires(std::is_convertible_v< HandleType< T >, DirectHandle< T >>) V8_WARN_UNUSED_RESULT static inline typename HandleType< Number > requires(std::is_convertible_v< HandleType< T >, DirectHandle< T >>) V8_WARN_UNUSED_RESULT static inline typename HandleType< Number > requires(std::is_convertible_v< HandleType< T >, DirectHandle< T >>) V8_WARN_UNUSED_RESULT static inline typename HandleType< Number > requires(std::is_convertible_v< HandleType< T >, DirectHandle< T >>) V8_WARN_UNUSED_RESULT static inline typename HandleType< String > static V8_EXPORT_PRIVATE MaybeDirectHandle< String > NoSideEffectsToMaybeString (Isolate *isolate, DirectHandle< Object > input)
static V8_EXPORT_PRIVATE DirectHandle< String > NoSideEffectsToString (Isolate *isolate, DirectHandle< Object > input)
template<typename T , template< typename > typename HandleType>
requires(std::is_convertible_v< HandleType< T >, DirectHandle< T >>) V8_WARN_UNUSED_RESULT static inline typename HandleType< Object > static V8_WARN_UNUSED_RESULT MaybeHandle< Object > ToLength (Isolate *isolate, DirectHandle< Object > input)
template<typename T , template< typename > typename HandleType>
requires(std::is_convertible_v< HandleType< T >, DirectHandle< T >>) V8_WARN_UNUSED_RESULT static inline typename HandleType< Object > static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > GetMethod (Isolate *isolate, DirectHandle< JSReceiver > receiver, DirectHandle< Name > name)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< FixedArray > CreateListFromArrayLike (Isolate *isolate, DirectHandle< Object > object, ElementTypes element_types)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > GetLengthFromArrayLike (Isolate *isolate, DirectHandle< JSReceiver > object)
static Handle< String > TypeOf (Isolate *isolate, DirectHandle< Object > object)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Add (Isolate *isolate, Handle< Object > lhs, Handle< Object > rhs)
static V8_WARN_UNUSED_RESULT Maybe< bool > GreaterThan (Isolate *isolate, DirectHandle< Object > x, DirectHandle< Object > y)
static V8_WARN_UNUSED_RESULT Maybe< bool > GreaterThanOrEqual (Isolate *isolate, DirectHandle< Object > x, DirectHandle< Object > y)
static V8_WARN_UNUSED_RESULT Maybe< bool > LessThan (Isolate *isolate, DirectHandle< Object > x, DirectHandle< Object > y)
static V8_WARN_UNUSED_RESULT Maybe< bool > LessThanOrEqual (Isolate *isolate, DirectHandle< Object > x, DirectHandle< Object > y)
static V8_WARN_UNUSED_RESULT MaybeHandle< Object > OrdinaryHasInstance (Isolate *isolate, DirectHandle< JSAny > callable, DirectHandle< JSAny > object)
static V8_WARN_UNUSED_RESULT MaybeHandle< Object > InstanceOf (Isolate *isolate, DirectHandle< JSAny > object, DirectHandle< JSAny > callable)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeHandle< Object > GetProperty (LookupIterator *it, bool is_global_reference=false)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT Maybe< bool > SetProperty (LookupIterator *it, DirectHandle< Object > value, StoreOrigin store_origin, Maybe< ShouldThrow > should_throw=Nothing< ShouldThrow >())
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeHandle< Object > SetProperty (Isolate *isolate, DirectHandle< JSAny > object, DirectHandle< Name > name, DirectHandle< Object > value, StoreOrigin store_origin=StoreOrigin::kMaybeKeyed, Maybe< ShouldThrow > should_throw=Nothing< ShouldThrow >())
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > SetPropertyOrElement (Isolate *isolate, DirectHandle< JSAny > object, DirectHandle< Name > name, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw=Nothing< ShouldThrow >(), StoreOrigin store_origin=StoreOrigin::kMaybeKeyed)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > SetPropertyOrElement (Isolate *isolate, DirectHandle< JSAny > object, PropertyKey key, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw=Nothing< ShouldThrow >(), StoreOrigin store_origin=StoreOrigin::kMaybeKeyed)
static V8_WARN_UNUSED_RESULT Maybe< bool > SetSuperProperty (LookupIterator *it, DirectHandle< Object > value, StoreOrigin store_origin, Maybe< ShouldThrow > should_throw=Nothing< ShouldThrow >())
static V8_WARN_UNUSED_RESULT Maybe< bool > CannotCreateProperty (Isolate *isolate, DirectHandle< JSAny > receiver, DirectHandle< Object > name, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > WriteToReadOnlyProperty (LookupIterator *it, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > WriteToReadOnlyProperty (Isolate *isolate, DirectHandle< JSAny > receiver, DirectHandle< Object > name, DirectHandle< Object > value, ShouldThrow should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > RedefineIncompatibleProperty (Isolate *isolate, DirectHandle< Object > name, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > SetDataProperty (LookupIterator *it, DirectHandle< Object > value)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT Maybe< bool > AddDataProperty (LookupIterator *it, DirectHandle< Object > value, PropertyAttributes attributes, Maybe< ShouldThrow > should_throw, StoreOrigin store_origin, EnforceDefineSemantics semantics=EnforceDefineSemantics::kSet)
static V8_WARN_UNUSED_RESULT Maybe< bool > TransitionAndWriteDataProperty (LookupIterator *it, DirectHandle< Object > value, PropertyAttributes attributes, Maybe< ShouldThrow > should_throw, StoreOrigin store_origin)
static V8_WARN_UNUSED_RESULT MaybeHandle< Object > GetPropertyOrElement (Isolate *isolate, DirectHandle< JSAny > object, DirectHandle< Name > name)
static V8_WARN_UNUSED_RESULT MaybeHandle< Object > GetPropertyOrElement (Isolate *isolate, DirectHandle< JSAny > object, PropertyKey key)
static V8_WARN_UNUSED_RESULT MaybeHandle< Object > GetProperty (Isolate *isolate, DirectHandle< JSAny > object, DirectHandle< Name > name)
static V8_WARN_UNUSED_RESULT MaybeHandle< JSAny > GetPropertyWithAccessor (LookupIterator *it)
static V8_WARN_UNUSED_RESULT Maybe< bool > SetPropertyWithAccessor (LookupIterator *it, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT MaybeHandle< JSAny > GetPropertyWithDefinedGetter (DirectHandle< JSAny > receiver, DirectHandle< JSReceiver > getter)
static V8_WARN_UNUSED_RESULT Maybe< bool > SetPropertyWithDefinedSetter (DirectHandle< JSAny > receiver, DirectHandle< JSReceiver > setter, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT MaybeHandle< Object > GetElement (Isolate *isolate, DirectHandle< JSAny > object, uint32_t index)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > SetElement (Isolate *isolate, DirectHandle< JSAny > object, uint32_t index, DirectHandle< Object > value, ShouldThrow should_throw)
static Tagged< Object > GetHash (Tagged< Object > obj)
static V8_EXPORT_PRIVATE Tagged< Smi > GetOrCreateHash (Tagged< Object > obj, Isolate *isolate)
static V8_EXPORT_PRIVATE bool SameValue (Tagged< Object > obj, Tagged< Object > other)
static bool SameNumberValue (double number1, double number2)
static bool SameValueZero (Tagged< Object > obj, Tagged< Object > other)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > ArraySpeciesConstructor (Isolate *isolate, DirectHandle< JSAny > original_array)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > SpeciesConstructor (Isolate *isolate, DirectHandle< JSReceiver > recv, DirectHandle< JSFunction > default_ctor)
static bool ToArrayLength (Tagged< Object > obj, uint32_t *index)
static V8_WARN_UNUSED_RESULT bool ToArrayIndex (Tagged< Object > obj, uint32_t *index)
static bool ToIntegerIndex (Tagged< Object > obj, size_t *index)
static V8_EXPORT_PRIVATE bool IterationHasObservableEffects (Tagged< Object > obj)
static bool IsCodeLike (Tagged< Object > obj, Isolate *isolate)
static bool CheckContextualStoreToJSGlobalObject (LookupIterator *it, Maybe< ShouldThrow > should_throw)
template<template< typename > typename HandleType>
requires(std::is_convertible_v< HandleType< T >, DirectHandle< T >>) static inline typename HandleType< Object > static requires(std::is_convertible_v< HandleType< Object >, DirectHandle< Object >>) static typename HandleType< Object > bool CanBeHeldWeakly (Tagged< Object > obj)
Public Attributes
HandleType< T > input
Static Public Attributes
static const int kHeaderSize = 0
Static Private Member Functions
static Tagged< Map > GetPrototypeChainRootMap (Tagged< Object > obj, Isolate *isolate)
static Tagged< Object > GetSimpleHash (Tagged< Object > object)
static V8_WARN_UNUSED_RESULT Maybe< bool > SetPropertyInternal (LookupIterator *it, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw, StoreOrigin store_origin, bool *found)
template<template< typename > typename HandleType>
requires(std::is_convertible_v< HandleType< Object >, DirectHandle< Object >>) V8_WARN_UNUSED_RESULT static typename HandleType< Name > requires(std::is_convertible_v< HandleType< Object >, DirectHandle< Object >>) V8_WARN_UNUSED_RESULT static typename HandleType< Object > requires(std::is_convertible_v< HandleType< Object >, DirectHandle< Object >>) EXPORT_TEMPLATE_DECLARE(V8_EXPORT_PRIVATE) V8_WARN_UNUSED_RESULT static typename HandleType< String > requires(std::is_convertible_v< HandleType< Object >, DirectHandle< Object >>) V8_WARN_UNUSED_RESULT static typename HandleType< Number > requires(std::is_convertible_v< HandleType< Object >, DirectHandle< Object >>) V8_WARN_UNUSED_RESULT static typename HandleType< Numeric > requires(std::is_convertible_v< HandleType< Object >, DirectHandle< Object >>) EXPORT_TEMPLATE_DECLARE(V8_EXPORT_PRIVATE) V8_WARN_UNUSED_RESULT static typename HandleType< Number > requires(std::is_convertible_v< HandleType< Object >, DirectHandle< Object >>) V8_WARN_UNUSED_RESULT static HandleType< Number > requires(std::is_convertible_v< HandleType< Object >, DirectHandle< Object >>) V8_WARN_UNUSED_RESULT static HandleType< Number > V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeHandle< Number > ConvertToLength (Isolate *isolate, DirectHandle< Object > input)
Friends
class CompressedObjectSlot
class FullObjectSlot
class LookupIterator
class StringStream
Detailed Description
Definition at line 129 of file objects.h.
Member Enumeration Documentation
Conversion
enum v8::internal::Object::Conversion [strong]
Enumerator
kToNumber
kToNumeric
Definition at line 131 of file objects.h.
                        {
    kToNumber, // Number = Smi or HeapNumber
    kToNumeric // Numeric = Smi or HeapNumber or BigInt
  };
Member Function Documentation
Add()
MaybeDirectHandle< Object > v8::internal::Object::Add (Isolate * isolate, Handle< Object > lhs, Handle< Object > rhs) [static]
Definition at line 1018 of file objects.cc.
                                                          {
  if (IsNumber(*lhs) && IsNumber(*rhs)) {
    return isolate->factory()->NewNumber(
        Object::NumberValue(Cast<Number>(*lhs)) +
        Object::NumberValue(Cast<Number>(*rhs)));
  } else if (IsString(*lhs) && IsString(*rhs)) {
    return isolate->factory()->NewConsString(Cast<String>(lhs),
                                             Cast<String>(rhs));
  }
  ASSIGN_RETURN_ON_EXCEPTION(isolate, lhs, Object::ToPrimitive(isolate, lhs));
  ASSIGN_RETURN_ON_EXCEPTION(isolate, rhs, Object::ToPrimitive(isolate, rhs));
  if (IsString(*lhs) || IsString(*rhs)) {
    ASSIGN_RETURN_ON_EXCEPTION(isolate, rhs, Object::ToString(isolate, rhs));
    ASSIGN_RETURN_ON_EXCEPTION(isolate, lhs, Object::ToString(isolate, lhs));
    return isolate->factory()->NewConsString(Cast<String>(lhs),
                                             Cast<String>(rhs));
  }
  DirectHandle<Number> lhs_number;
  DirectHandle<Number> rhs_number;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, rhs_number,
                             Object::ToNumber(isolate, rhs));
  ASSIGN_RETURN_ON_EXCEPTION(isolate, lhs_number,
                             Object::ToNumber(isolate, lhs));
  return isolate->factory()->NewNumber(Object::NumberValue(*lhs_number) +
                                       Object::NumberValue(*rhs_number));
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::factory(), v8::internal::IsNumber(), v8::internal::FactoryBase< Impl >::NewConsString(), v8::internal::FactoryBase< Impl >::NewNumber(), NumberValue(), v8::Value::ToNumber(), v8::Value::ToPrimitive(), and v8::Value::ToString().
Referenced by v8::internal::RUNTIME_FUNCTION().
AddDataProperty()
Maybe< bool > v8::internal::Object::AddDataProperty (LookupIterator * it, DirectHandle< Object > value, PropertyAttributes attributes, Maybe< ShouldThrow > should_throw, StoreOrigin store_origin, EnforceDefineSemantics semantics = EnforceDefineSemantics::kSet) [static]
Definition at line 2693 of file objects.cc.
                                                                      {
  if (!IsJSReceiver(*it->GetReceiver())) {
    return CannotCreateProperty(it->isolate(), it->GetReceiver(), it->GetName(),
                                value, should_throw);
  }
  // Private symbols should be installed on JSProxy using
  // JSProxy::SetPrivateSymbol.
  if (IsJSProxy(*it->GetReceiver()) && it->GetName()->IsPrivate() &&
      !it->GetName()->IsPrivateName()) {
    RETURN_FAILURE(it->isolate(), GetShouldThrow(it->isolate(), should_throw),
                   NewTypeError(MessageTemplate::kProxyPrivate));
  }
  DCHECK_NE(LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, it->state());
  DirectHandle<JSReceiver> receiver = it->GetStoreTarget<JSReceiver>();
  DCHECK_IMPLIES(IsJSProxy(*receiver), it->GetName()->IsPrivateName());
  DCHECK_IMPLIES(IsJSProxy(*receiver),
                 it->state() == LookupIterator::NOT_FOUND);
  // If the receiver is a JSGlobalProxy, store on the prototype (JSGlobalObject)
  // instead. If the prototype is Null, the proxy is detached.
  if (IsJSGlobalProxy(*receiver)) return Just(true);
  Isolate* isolate = it->isolate();
  if (it->ExtendingNonExtensible(receiver)) {
    if (IsWasmObject(*receiver)) {
      RETURN_FAILURE(it->isolate(), kThrowOnError,
                     NewTypeError(MessageTemplate::kWasmObjectsAreOpaque));
    }
    bool is_shared_object = IsAlwaysSharedSpaceJSObject(*receiver);
    RETURN_FAILURE(
        isolate, GetShouldThrow(it->isolate(), should_throw),
        NewTypeError(
            semantics == EnforceDefineSemantics::kDefine
                ? (is_shared_object
                       ? MessageTemplate::kDefineDisallowedFixedLayout
                       : MessageTemplate::kDefineDisallowed)
                : (is_shared_object ? MessageTemplate::kObjectFixedLayout
                                    : MessageTemplate::kObjectNotExtensible),
            it->GetName()));
  }
  if (it->IsElement(*receiver)) {
    if (IsJSArray(*receiver)) {
      DirectHandle<JSArray> array = Cast<JSArray>(receiver);
      if (JSArray::WouldChangeReadOnlyLength(array, it->array_index())) {
        RETURN_FAILURE(isolate, GetShouldThrow(isolate, should_throw),
                       NewTypeError(MessageTemplate::kStrictReadOnlyProperty,
                                    isolate->factory()->length_string(),
                                    Object::TypeOf(isolate, array), array));
      }
    }
    DirectHandle<JSObject> receiver_obj = Cast<JSObject>(receiver);
    MAYBE_RETURN(JSObject::AddDataElement(isolate, receiver_obj,
                                          it->array_index(), value, attributes),
                 Nothing<bool>());
    JSObject::ValidateElements(isolate, *receiver_obj);
    return Just(true);
  }
  return Object::TransitionAndWriteDataProperty(it, value, attributes,
                                                should_throw, store_origin);
}
References v8::internal::JSObject::AddDataElement(), v8::internal::LookupIterator::array_index(), CannotCreateProperty(), DCHECK_IMPLIES, DCHECK_NE, v8::internal::LookupIterator::ExtendingNonExtensible(), v8::internal::Isolate::factory(), v8::internal::LookupIterator::GetName(), v8::internal::LookupIterator::GetReceiver(), v8::internal::GetShouldThrow(), v8::internal::LookupIterator::GetStoreTarget(), v8::internal::LookupIterator::IsElement(), v8::internal::LookupIterator::isolate(), v8::internal::IsWasmObject(), v8::Just(), v8::internal::kDefine, v8::internal::kThrowOnError, MAYBE_RETURN, v8::internal::LookupIterator::NOT_FOUND, RETURN_FAILURE, v8::internal::LookupIterator::state(), TransitionAndWriteDataProperty(), v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, TypeOf(), v8::internal::JSObject::ValidateElements(), v8::internal::value, and v8::internal::JSArray::WouldChangeReadOnlyLength().
Referenced by v8::internal::JSObject::AddProperty(), v8::internal::anonymous_namespace{runtime-atomics.cc}::AtomicFieldWrite(), v8::internal::anonymous_namespace{runtime-regexp.cc}::ConstructNamedCaptureGroupsObject(), v8::internal::anonymous_namespace{api-natives.cc}::DefineDataProperty(), v8::internal::anonymous_namespace{ic.cc}::DefineOwnDataProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::RUNTIME_FUNCTION(), SetProperty(), and SetSuperProperty().
ArraySpeciesConstructor()
MaybeDirectHandle< Object > v8::internal::Object::ArraySpeciesConstructor (Isolate * isolate, DirectHandle< JSAny > original_array) [static]
Definition at line 1746 of file objects.cc.
                                                          {
  DirectHandle<Object> default_species = isolate->array_function();
  if (!v8_flags.builtin_subclassing) return default_species;
  if (IsJSArray(*original_array) &&
      Cast<JSArray>(original_array)->HasArrayPrototype(isolate) &&
      Protectors::IsArraySpeciesLookupChainIntact(isolate)) {
    return default_species;
  }
  DirectHandle<Object> constructor = isolate->factory()->undefined_value();
  Maybe<bool> is_array = IsArray(original_array);
  MAYBE_RETURN_NULL(is_array);
  if (is_array.FromJust()) {
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, constructor,
        Object::GetProperty(isolate, original_array,
                            isolate->factory()->constructor_string()));
    if (IsConstructor(*constructor)) {
      DirectHandle<NativeContext> constructor_context;
      ASSIGN_RETURN_ON_EXCEPTION(
          isolate, constructor_context,
          JSReceiver::GetFunctionRealm(Cast<JSReceiver>(constructor)));
      if (*constructor_context != *isolate->native_context() &&
          *constructor == constructor_context->array_function()) {
        constructor = isolate->factory()->undefined_value();
      }
    }
    if (IsJSReceiver(*constructor)) {
      ASSIGN_RETURN_ON_EXCEPTION(
          isolate, constructor,
          JSReceiver::GetProperty(isolate, Cast<JSReceiver>(constructor),
                                  isolate->factory()->species_symbol()));
      if (IsNull(*constructor, isolate)) {
        constructor = isolate->factory()->undefined_value();
      }
    }
  }
  if (IsUndefined(*constructor, isolate)) {
    return default_species;
  } else {
    if (!IsConstructor(*constructor)) {
      THROW_NEW_ERROR(isolate,
                      NewTypeError(MessageTemplate::kSpeciesNotConstructor));
    }
    return constructor;
  }
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::JSReceiver::GetProperty(), GetProperty(), IsArray(), v8::internal::IsNull(), MAYBE_RETURN_NULL, v8::internal::Isolate::native_context(), THROW_NEW_ERROR, and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION().
BooleanValue() [1/2]
template<typename IsolateT >
bool v8::internal::Object::BooleanValue (Tagged< Object > obj, IsolateT * isolate)
Definition at line 775 of file objects.cc.
                                                               {
  if (IsSmi(obj)) return Smi::ToInt(obj) != 0;
  DCHECK(IsHeapObject(obj));
  if (IsBoolean(obj)) return IsTrue(obj, isolate);
  if (IsNullOrUndefined(obj, isolate)) return false;
#ifdef V8_ENABLE_WEBASSEMBLY
  if (IsWasmNull(obj)) return false;
#endif
  if (IsUndetectable(obj)) return false; // Undetectable object is false.
  if (IsString(obj)) return Cast<String>(obj)->length() != 0;
  if (IsHeapNumber(obj)) return DoubleToBoolean(Cast<HeapNumber>(obj)->value());
  if (IsBigInt(obj)) return Cast<BigInt>(obj)->ToBoolean();
  return true;
}
References v8::internal::DCHECK(), v8::internal::DoubleToBoolean(), v8::internal::IsHeapObject(), v8::internal::IsNullOrUndefined(), v8::internal::IsSmi(), v8::internal::Smi::ToInt(), and v8::internal::value.
BooleanValue() [2/2]
template<typename IsolateT >
static V8_EXPORT_PRIVATE bool v8::internal::Object::BooleanValue (Tagged< Object > obj, IsolateT * isolate) [static]
Referenced by v8::Value::BooleanValue(), v8::internal::BUILTIN(), v8::internal::Debug::CheckBreakPoint(), v8::internal::anonymous_namespace{wasm-debug.cc}::CheckBreakPoint(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::JSProxy::DeletePropertyOrElement(), v8::internal::SourceTextModule::ExecuteModule(), v8::internal::GetBoolOption(), v8::internal::GetStringOrBooleanOption(), v8::internal::JSProxy::HasProperty(), InstanceOf(), v8::internal::anonymous_namespace{builtins-array.cc}::IsConcatSpreadable(), v8::internal::JSProxy::IsExtensible(), v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor(), v8::internal::Intl::LegacyUnwrapReceiver(), v8::internal::JSProxy::PreventExtensions(), v8::internal::requires(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JSProxy::SetProperty(), v8::internal::JSProxy::SetPrototype(), v8::internal::maglev::Constant::ToBoolean(), ToBoolean(), v8::internal::PropertyDescriptor::ToPropertyDescriptor(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), v8::internal::compiler::HeapObjectData::TryGetBooleanValue(), and v8::internal::UnscopableLookup().
CanBeHeldWeakly()
template<template< typename > typename HandleType>
bool v8::internal::Object::CanBeHeldWeakly (Tagged< Object > obj) [inline], [static]
Definition at line 2004 of file objects-inl.h.
                                               {
  if (IsJSReceiver(obj)) {
    // TODO(v8:12547) Shared structs and arrays should only be able to point
    // to shared values in weak collections. For now, disallow them as weak
    // collection keys.
#if V8_ENABLE_WEBASSEMBLY
    if (v8_flags.experimental_wasm_shared &&
        (IsWasmStruct(obj) || IsWasmArray(obj)) &&
        HeapLayout::InAnySharedSpace(Cast<HeapObject>(obj))) {
      return false;
    }
#endif
    return (!v8_flags.harmony_struct ||
            (!IsJSSharedStruct(obj) && !IsJSSharedArray(obj)));
  }
  return IsSymbol(obj) && !Cast<Symbol>(obj)->is_in_public_symbol_table();
}
References v8::internal::HeapLayout::InAnySharedSpace(), and v8::internal::v8_flags.
Referenced by v8::internal::BUILTIN(), v8::internal::WeakCell::Nullify(), v8::internal::WeakCell::RemoveFromFinalizationRegistryCells(), and v8::internal::RUNTIME_FUNCTION().
CannotCreateProperty()
Maybe< bool > v8::internal::Object::CannotCreateProperty (Isolate * isolate, DirectHandle< JSAny > receiver, DirectHandle< Object > name, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw) [static]
Definition at line 2583 of file objects.cc.
                                                                          {
  RETURN_FAILURE(
      isolate, GetShouldThrow(isolate, should_throw),
      NewTypeError(MessageTemplate::kStrictCannotCreateProperty, name,
                   Object::TypeOf(isolate, receiver), receiver));
}
References v8::internal::GetShouldThrow(), v8::internal::name, RETURN_FAILURE, and TypeOf().
Referenced by AddDataProperty(), and v8::internal::JSReceiver::CreateDataProperty().
CheckContextualStoreToJSGlobalObject()
bool v8::internal::Object::CheckContextualStoreToJSGlobalObject (LookupIterator * it, Maybe< ShouldThrow > should_throw) [static]
Definition at line 2440 of file objects.cc.
                                                         {
  Isolate* isolate = it->isolate();
  if (IsJSGlobalObject(*it->GetReceiver(), isolate) &&
      (GetShouldThrow(isolate, should_throw) == ShouldThrow::kThrowOnError)) {
    if (it->state() == LookupIterator::TRANSITION) {
      // The property cell that we have created is garbage because we are going
      // to throw now instead of putting it into the global dictionary. However,
      // the cell might already have been stored into the feedback vector, so
      // we must invalidate it nevertheless.
      it->transition_cell()->ClearAndInvalidate(isolate);
    }
    isolate->Throw(*isolate->factory()->NewReferenceError(
        MessageTemplate::kNotDefined, it->GetName()));
    return false;
  }
  return true;
}
References v8::internal::Isolate::factory(), v8::internal::LookupIterator::GetName(), v8::internal::LookupIterator::GetReceiver(), v8::internal::GetShouldThrow(), v8::internal::LookupIterator::isolate(), v8::internal::kThrowOnError, v8::internal::LookupIterator::state(), v8::internal::Isolate::Throw(), v8::internal::LookupIterator::TRANSITION, and v8::internal::LookupIterator::transition_cell().
Referenced by SetProperty(), and SetSuperProperty().
Compare()
Maybe< ComparisonResult > v8::internal::Object::Compare (Isolate * isolate, DirectHandle< Object > x, DirectHandle< Object > y) [static]
Definition at line 843 of file objects.cc.
                                                                {
  // ES6 section 7.2.11 Abstract Relational Comparison step 3 and 4.
  if (!Object::ToPrimitive(isolate, x, ToPrimitiveHint::kNumber).ToHandle(&x) ||
      !Object::ToPrimitive(isolate, y, ToPrimitiveHint::kNumber).ToHandle(&y)) {
    return Nothing<ComparisonResult>();
  }
  if (IsString(*x) && IsString(*y)) {
    // ES6 section 7.2.11 Abstract Relational Comparison step 5.
    return Just(String::Compare(isolate, Cast<String>(x), Cast<String>(y)));
  }
  if (IsBigInt(*x) && IsString(*y)) {
    return BigInt::CompareToString(isolate, Cast<BigInt>(x), Cast<String>(y));
  }
  if (IsString(*x) && IsBigInt(*y)) {
    Maybe<ComparisonResult> maybe_result =
        BigInt::CompareToString(isolate, Cast<BigInt>(y), Cast<String>(x));
    ComparisonResult result;
    if (maybe_result.To(&result)) {
      return Just(Reverse(result));
    } else {
      return Nothing<ComparisonResult>();
    }
  }
  // ES6 section 7.2.11 Abstract Relational Comparison step 6.
  if (!Object::ToNumeric(isolate, x).ToHandle(&x) ||
      !Object::ToNumeric(isolate, y).ToHandle(&y)) {
    return Nothing<ComparisonResult>();
  }
  bool x_is_number = IsNumber(*x);
  bool y_is_number = IsNumber(*y);
  if (x_is_number && y_is_number) {
    return Just(
        StrictNumberCompare(Object::NumberValue(*x), Object::NumberValue(*y)));
  } else if (!x_is_number && !y_is_number) {
    return Just(BigInt::CompareToBigInt(Cast<BigInt>(x), Cast<BigInt>(y)));
  } else if (x_is_number) {
    return Just(Reverse(BigInt::CompareToNumber(Cast<BigInt>(y), x)));
  } else {
    return Just(BigInt::CompareToNumber(Cast<BigInt>(x), y));
  }
}
References v8::internal::String::Compare(), v8::internal::BigInt::CompareToBigInt(), v8::internal::BigInt::CompareToNumber(), v8::internal::BigInt::CompareToString(), v8::internal::IsNumber(), v8::Just(), v8::internal::kNumber, NumberValue(), v8::base::internal::result, v8::internal::anonymous_namespace{objects.cc}::Reverse(), v8::internal::anonymous_namespace{objects.cc}::StrictNumberCompare(), v8::Maybe< T >::To(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::Value::ToNumeric(), v8::Value::ToPrimitive(), and v8::internal::y.
Referenced by GreaterThan(), GreaterThanOrEqual(), LessThan(), and LessThanOrEqual().
ConvertReceiver()
MaybeDirectHandle< JSReceiver > v8::internal::Object::ConvertReceiver (Isolate * isolate, DirectHandle< Object > object) [static]
Definition at line 305 of file objects.cc.
                                                   {
  if (IsJSReceiver(*object)) return Cast<JSReceiver>(object);
  if (IsNullOrUndefined(*object, isolate)) {
    return isolate->global_proxy();
  }
  return Object::ToObject(isolate, object);
}
References v8::internal::Isolate::global_proxy(), v8::internal::IsNullOrUndefined(), and v8::Value::ToObject().
Referenced by v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::JSObject::DeletePropertyWithInterceptor(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyAttributesWithInterceptorInternal(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), GetPropertyWithAccessor(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyWithInterceptorInternal(), v8::internal::Builtins::InvokeApiFunction(), v8::internal::RUNTIME_FUNCTION(), SetPropertyWithAccessor(), and v8::internal::anonymous_namespace{js-objects.cc}::SetPropertyWithInterceptorInternal().
ConvertToLength()
template<template< typename > typename HandleType>
MaybeHandle< Number > v8::internal::Object::ConvertToLength (Isolate * isolate, DirectHandle< Object > input) [static], [private]
Definition at line 734 of file objects.cc.
                                                                        {
  ASSIGN_RETURN_ON_EXCEPTION(isolate, input, ToNumber(isolate, input));
  if (IsSmi(*input)) {
    int value = std::max(Smi::ToInt(*input), 0);
    return handle(Smi::FromInt(value), isolate);
  }
  double len = DoubleToInteger(Cast<HeapNumber>(*input)->value());
  if (len <= 0.0) {
    return handle(Smi::zero(), isolate);
  } else if (len >= kMaxSafeInteger) {
    len = kMaxSafeInteger;
  }
  return isolate->factory()->NewNumber(len);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DoubleToInteger(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::handle(), input, v8::internal::IsSmi(), v8::internal::kMaxSafeInteger, v8::internal::FactoryBase< Impl >::NewNumber(), v8::internal::Smi::ToInt(), v8::internal::ToNumber(), v8::internal::value, and v8::internal::Smi::zero().
Referenced by ToLength().
CreateListFromArrayLike()
MaybeDirectHandle< FixedArray > v8::internal::Object::CreateListFromArrayLike (Isolate * isolate, DirectHandle< Object > object, ElementTypes element_types) [static]
Definition at line 1178 of file objects.cc.
                                                                               {
  // Fast-path for JSArray and JSTypedArray.
  MaybeDirectHandle<FixedArray> fast_result =
      CreateListFromArrayLikeFastPath(isolate, object, element_types);
  if (!fast_result.is_null()) return fast_result;
  // 1. ReturnIfAbrupt(object).
  // 2. (default elementTypes -- not applicable.)
  // 3. If Type(obj) is not Object, throw a TypeError exception.
  if (!IsJSReceiver(*object)) {
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kCalledOnNonObject,
                                 isolate->factory()->NewStringFromAsciiChecked(
                                     "CreateListFromArrayLike")));
  }
  // 4. Let len be ? ToLength(? Get(obj, "length")).
  DirectHandle<JSReceiver> receiver = Cast<JSReceiver>(object);
  DirectHandle<Object> raw_length_number;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, raw_length_number,
                             Object::GetLengthFromArrayLike(isolate, receiver));
  uint32_t len;
  if (!Object::ToUint32(*raw_length_number, &len) ||
      len > static_cast<uint32_t>(FixedArray::kMaxLength)) {
    THROW_NEW_ERROR(isolate,
                    NewRangeError(MessageTemplate::kInvalidArrayLength));
  }
  // 5. Let list be an empty List.
  DirectHandle<FixedArray> list = isolate->factory()->NewFixedArray(len);
  // 6. Let index be 0.
  // 7. Repeat while index < len:
  for (uint32_t index = 0; index < len; ++index) {
    // 7a. Let indexName be ToString(index).
    // 7b. Let next be ? Get(obj, indexName).
    DirectHandle<Object> next;
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, next, JSReceiver::GetElement(isolate, receiver, index));
    switch (element_types) {
      case ElementTypes::kAll:
        // Nothing to do.
        break;
      case ElementTypes::kStringAndSymbol: {
        // 7c. If Type(next) is not an element of elementTypes, throw a
        // TypeError exception.
        if (!IsName(*next)) {
          THROW_NEW_ERROR(
              isolate, NewTypeError(MessageTemplate::kNotPropertyName, next));
        }
        // 7d. Append next as the last element of list.
        // Internalize on the fly so we can use pointer identity later.
        next = isolate->factory()->InternalizeName(Cast<Name>(next));
        break;
      }
    }
    list->set(index, *next);
    // 7e. Set index to index + 1. (See loop header.)
  }
  // 8. Return list.
  return list;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::anonymous_namespace{objects.cc}::CreateListFromArrayLikeFastPath(), v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetElement(), GetLengthFromArrayLike(), v8::internal::index, v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::kAll, v8::internal::FixedArray::kMaxLength, v8::internal::kStringAndSymbol, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), THROW_NEW_ERROR, and ToUint32().
Referenced by v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), and v8::internal::RUNTIME_FUNCTION().
Equals()
Maybe< bool > v8::internal::Object::Equals (Isolate * isolate, DirectHandle< Object > x, DirectHandle< Object > y) [static]
Definition at line 888 of file objects.cc.
                                                   {
  // This is the generic version of Abstract Equality Comparison. Must be in
  // sync with CodeStubAssembler::Equal.
  while (true) {
    if (IsNumber(*x)) {
      if (IsNumber(*y)) {
        return Just(StrictNumberEquals(Cast<Number>(*x), Cast<Number>(*y)));
      } else if (IsBoolean(*y)) {
        return Just(StrictNumberEquals(Cast<Number>(*x),
                                       Cast<Oddball>(y)->to_number()));
      } else if (IsString(*y)) {
        return Just(StrictNumberEquals(
            Cast<Number>(x), String::ToNumber(isolate, Cast<String>(y))));
      } else if (IsBigInt(*y)) {
        return Just(BigInt::EqualToNumber(Cast<BigInt>(y), Cast<Number>(x)));
      } else if (IsJSReceiver(*y)) {
        if (!JSReceiver::ToPrimitive(isolate, Cast<JSReceiver>(y))
                 .ToHandle(&y)) {
          return Nothing<bool>();
        }
      } else {
        return Just(false);
      }
    } else if (IsString(*x)) {
      if (IsString(*y)) {
        return Just(String::Equals(isolate, Cast<String>(x), Cast<String>(y)));
      } else if (IsNumber(*y)) {
        x = String::ToNumber(isolate, Cast<String>(x));
        return Just(StrictNumberEquals(Cast<Number>(*x), Cast<Number>(*y)));
      } else if (IsBoolean(*y)) {
        x = String::ToNumber(isolate, Cast<String>(x));
        return Just(StrictNumberEquals(Cast<Number>(*x),
                                       Cast<Oddball>(y)->to_number()));
      } else if (IsBigInt(*y)) {
        return BigInt::EqualToString(isolate, Cast<BigInt>(y), Cast<String>(x));
      } else if (IsJSReceiver(*y)) {
        if (!JSReceiver::ToPrimitive(isolate, Cast<JSReceiver>(y))
                 .ToHandle(&y)) {
          return Nothing<bool>();
        }
      } else {
        return Just(false);
      }
    } else if (IsBoolean(*x)) {
      if (IsOddball(*y)) {
        return Just(x.is_identical_to(y));
      } else if (IsNumber(*y)) {
        return Just(StrictNumberEquals(Cast<Oddball>(x)->to_number(),
                                       Cast<Number>(*y)));
      } else if (IsString(*y)) {
        y = String::ToNumber(isolate, Cast<String>(y));
        return Just(StrictNumberEquals(Cast<Oddball>(x)->to_number(),
                                       Cast<Number>(*y)));
      } else if (IsBigInt(*y)) {
        x = Oddball::ToNumber(isolate, Cast<Oddball>(x));
        return Just(BigInt::EqualToNumber(Cast<BigInt>(y), x));
      } else if (IsJSReceiver(*y)) {
        if (!JSReceiver::ToPrimitive(isolate, Cast<JSReceiver>(y))
                 .ToHandle(&y)) {
          return Nothing<bool>();
        }
        x = Oddball::ToNumber(isolate, Cast<Oddball>(x));
      } else {
        return Just(false);
      }
    } else if (IsSymbol(*x)) {
      if (IsSymbol(*y)) {
        return Just(x.is_identical_to(y));
      } else if (IsJSReceiver(*y)) {
        if (!JSReceiver::ToPrimitive(isolate, Cast<JSReceiver>(y))
                 .ToHandle(&y)) {
          return Nothing<bool>();
        }
      } else {
        return Just(false);
      }
    } else if (IsBigInt(*x)) {
      if (IsBigInt(*y)) {
        return Just(BigInt::EqualToBigInt(Cast<BigInt>(*x), Cast<BigInt>(*y)));
      }
      return Equals(isolate, y, x);
    } else if (IsJSReceiver(*x)) {
      if (IsJSReceiver(*y)) {
        return Just(x.is_identical_to(y));
      } else if (IsUndetectable(*y)) {
        return Just(IsUndetectable(*x));
      } else if (IsBoolean(*y)) {
        y = Oddball::ToNumber(isolate, Cast<Oddball>(y));
      } else if (!JSReceiver::ToPrimitive(isolate, Cast<JSReceiver>(x))
                      .ToHandle(&x)) {
        return Nothing<bool>();
      }
    } else {
      return Just(IsUndetectable(*x) && IsUndetectable(*y));
    }
  }
}
References v8::internal::String::Equals(), v8::internal::BigInt::EqualToBigInt(), v8::internal::BigInt::EqualToNumber(), v8::internal::BigInt::EqualToString(), v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::IsNumber(), v8::Just(), v8::internal::anonymous_namespace{objects.cc}::StrictNumberEquals(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::Oddball::ToNumber(), v8::Value::ToNumber(), and v8::internal::y.
Referenced by v8::Value::Equals(), and v8::internal::RUNTIME_FUNCTION().
FilterKey()
bool v8::internal::Object::FilterKey (Tagged< Object > obj, PropertyFilter filter) [inline], [static]
Definition at line 737 of file objects-inl.h.
                                                                {
  DCHECK(!IsPropertyCell(obj));
  if (filter == PRIVATE_NAMES_ONLY) {
    if (!IsSymbol(obj)) return true;
    return !Cast<Symbol>(obj)->is_private_name();
  } else if (IsSymbol(obj)) {
    if (filter & SKIP_SYMBOLS) return true;
    if (Cast<Symbol>(obj)->is_private()) return true;
  } else {
    if (filter & SKIP_STRINGS) return true;
  }
  return false;
}
References v8::internal::DCHECK(), v8::internal::PRIVATE_NAMES_ONLY, v8::internal::SKIP_STRINGS, and v8::internal::SKIP_SYMBOLS.
Referenced by v8::internal::JSObject::ApplyAttributesToDictionary(), v8::internal::anonymous_namespace{keys.cc}::CollectKeysFromDictionary(), v8::internal::anonymous_namespace{keys.cc}::CollectOwnPropertyNamesInternal(), v8::internal::FilterProxyKeys(), v8::internal::SwissNameDictionary::NumberOfEnumerableProperties(), v8::internal::Map::NumberOfEnumerableProperties(), and v8::internal::anonymous_namespace{js-objects.cc}::TestDictionaryPropertiesIntegrityLevel().
FitsRepresentation()
bool v8::internal::Object::FitsRepresentation (Tagged< Object > obj, Representation representation, bool allow_coercion = true) [inline], [static]
Definition at line 781 of file objects-inl.h.
                                                     {
  if (representation.IsSmi()) {
    return IsSmi(obj);
  } else if (representation.IsDouble()) {
    return allow_coercion ? IsNumber(obj) : IsHeapNumber(obj);
  } else if (representation.IsHeapObject()) {
    return IsHeapObject(obj);
  } else if (representation.IsNone()) {
    return false;
  }
  return true;
}
References v8::internal::Representation::IsDouble(), v8::internal::Representation::IsHeapObject(), v8::internal::IsHeapObject(), v8::internal::Representation::IsNone(), v8::internal::IsNumber(), v8::internal::Representation::IsSmi(), and v8::internal::IsSmi().
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::anonymous_namespace{map.cc}::CanHoldValue(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnFastConstantDataPropertyFromHeap(), v8::internal::DictionaryTemplateInfo::NewInstance(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue(), and WrapForRead().
GetElement()
MaybeHandle< Object > v8::internal::Object::GetElement (Isolate * isolate, DirectHandle< JSAny > object, uint32_t index) [inline], [static]
Definition at line 932 of file objects-inl.h.
                                                       {
  LookupIterator it(isolate, object, index);
  if (!it.IsFound()) return it.factory()->undefined_value();
  return GetProperty(&it);
}
References v8::internal::LookupIterator::factory(), GetProperty(), v8::internal::index, and v8::internal::LookupIterator::IsFound().
Referenced by v8::internal::BUILTIN(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayShift(), v8::internal::JsonStringifier::InitializeReplacer(), and v8::internal::RUNTIME_FUNCTION().
GetHash()
Tagged< Object > v8::internal::Object::GetHash (Tagged< Object > obj) [inline], [static]
Definition at line 1928 of file objects-inl.h.
                                                 {
  DisallowGarbageCollection no_gc;
  Tagged<Object> hash = GetSimpleHash(obj);
  if (IsSmi(hash)) return hash;
  // Make sure that we never cast internal objects to JSReceivers.
  CHECK(IsJSReceiver(obj));
  Tagged<JSReceiver> receiver = Cast<JSReceiver>(obj);
  return receiver->GetIdentityHash();
}
References CHECK, GetSimpleHash(), v8::internal::IsSmi(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), v8::internal::LoadIC::ComputeHandler(), v8::internal::OrderedHashTable< Derived, entrysize >::FindEntry(), v8::Value::GetHash(), v8::internal::OrderedHashMap::GetHash(), v8::internal::ObjectHashSet::Has(), v8::internal::ObjectHashTableShapeBase::Hash(), v8::internal::ObjectHashTableShapeBase::HashForObject(), v8::internal::ObjectMultiHashTableBase< Derived, N >::Lookup(), v8::internal::JSFinalizationRegistry::RemoveCellFromUnregisterTokenMap(), and v8::internal::JSFinalizationRegistry::RemoveUnregisterToken().
GetLengthFromArrayLike()
MaybeDirectHandle< Object > v8::internal::Object::GetLengthFromArrayLike (Isolate * isolate, DirectHandle< JSReceiver > object) [static]
Definition at line 1240 of file objects.cc.
                                                       {
  DirectHandle<Object> val;
  DirectHandle<Name> key = isolate->factory()->length_string();
  ASSIGN_RETURN_ON_EXCEPTION(isolate, val,
                             JSReceiver::GetProperty(isolate, object, key));
  return Object::ToLength(isolate, val);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetProperty(), v8::internal::key, and ToLength().
Referenced by v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), v8::internal::BUILTIN(), v8::internal::Intl::CanonicalizeLocaleList(), CreateListFromArrayLike(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPop(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPush(), v8::internal::anonymous_namespace{builtins-array.cc}::GetLengthProperty(), v8::internal::JsonStringifier::InitializeReplacer(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::anonymous_namespace{builtins-array.cc}::IterateElements(), and v8::internal::JsonStringifier::SerializeJSProxy().
GetMethod()
template<typename T , template< typename > typename HandleType>
MaybeDirectHandle< Object > v8::internal::Object::GetMethod (Isolate * isolate, DirectHandle< JSReceiver > receiver, DirectHandle< Name > name) [static]
Definition at line 1127 of file objects.cc.
                                                                     {
  Handle<Object> func;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, func,
                             JSReceiver::GetProperty(isolate, receiver, name));
  if (IsNullOrUndefined(*func, isolate)) {
    return isolate->factory()->undefined_value();
  }
  if (!IsCallable(*func)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kPropertyNotFunction,
                                          func, name, receiver));
  }
  return func;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetProperty(), v8::internal::IsNullOrUndefined(), v8::internal::name, and THROW_NEW_ERROR.
Referenced by v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::JSProxy::DeletePropertyOrElement(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), v8::internal::JSProxy::GetProperty(), v8::internal::JSProxy::GetPrototype(), v8::internal::JSProxy::HasProperty(), InstanceOf(), v8::internal::JSProxy::IsExtensible(), v8::internal::JSProxy::PreventExtensions(), v8::internal::requires(), v8::internal::JSProxy::SetProperty(), and v8::internal::JSProxy::SetPrototype().
GetOrCreateHash()
Tagged< Smi > v8::internal::Object::GetOrCreateHash (Tagged< Object > obj, Isolate * isolate) [static]
Definition at line 1700 of file objects.cc.
                                                                        {
  DisallowGarbageCollection no_gc;
  Tagged<Object> hash = Object::GetSimpleHash(obj);
  if (IsSmi(hash)) return Cast<Smi>(hash);
  DCHECK(IsJSReceiver(obj));
  return Cast<JSReceiver>(obj)->GetOrCreateIdentityHash(isolate);
}
References v8::internal::DCHECK(), GetSimpleHash(), v8::internal::IsSmi(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::ObjectHashSet::Add(), v8::internal::OrderedHashMap::Add(), v8::internal::BIT_FIELD_ACCESSORS(), v8::internal::GetOrCreateHash(), v8::internal::ObjectMultiHashTableBase< Derived, N >::Put(), v8::internal::requires(), and wasm::StoreImpl::SetHostInfo().
GetProperty() [1/2]
MaybeHandle< Object > v8::internal::Object::GetProperty (Isolate * isolate, DirectHandle< JSAny > object, DirectHandle< Name > name) [inline], [static]
Definition at line 924 of file objects-inl.h.
                                                                 {
  LookupIterator it(isolate, object, name);
  if (!it.IsFound()) return it.factory()->undefined_value();
  return GetProperty(&it);
}
References v8::internal::LookupIterator::factory(), GetProperty(), v8::internal::LookupIterator::IsFound(), and v8::internal::name.
GetProperty() [2/2]
MaybeHandle< Object > v8::internal::Object::GetProperty (LookupIterator * it, bool is_global_reference = false) [static]
Definition at line 1250 of file objects.cc.
                                                                  {
  for (;; it->Next()) {
    switch (it->state()) {
      case LookupIterator::TRANSITION:
        UNREACHABLE();
      case LookupIterator::JSPROXY: {
        bool was_found;
        DirectHandle<JSAny> receiver = it->GetReceiver();
        // In case of global IC, the receiver is the global object. Replace by
        // the global proxy.
        if (IsJSGlobalObject(*receiver)) {
          receiver = direct_handle(
              Cast<JSGlobalObject>(*receiver)->global_proxy(), it->isolate());
        }
        if (is_global_reference) {
          Maybe<bool> maybe = JSProxy::HasProperty(
              it->isolate(), it->GetHolder<JSProxy>(), it->GetName());
          if (maybe.IsNothing()) return {};
          if (!maybe.FromJust()) {
            it->NotFound();
            return it->isolate()->factory()->undefined_value();
          }
        }
        MaybeHandle<JSAny> result =
            JSProxy::GetProperty(it->isolate(), it->GetHolder<JSProxy>(),
                                 it->GetName(), receiver, &was_found);
        if (!was_found && !is_global_reference) it->NotFound();
        return result;
      }
      case LookupIterator::WASM_OBJECT:
        continue; // Continue to the prototype, if present.
      case LookupIterator::INTERCEPTOR: {
        bool done;
        Handle<JSAny> result;
        ASSIGN_RETURN_ON_EXCEPTION(
            it->isolate(), result,
            JSObject::GetPropertyWithInterceptor(it, &done));
        if (done) return result;
        continue;
      }
      case LookupIterator::ACCESS_CHECK:
        if (it->HasAccess()) continue;
        return JSObject::GetPropertyWithFailedAccessCheck(it);
      case LookupIterator::ACCESSOR:
        return GetPropertyWithAccessor(it);
      case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
        return it->isolate()->factory()->undefined_value();
      case LookupIterator::DATA:
        return it->GetDataValue();
      case LookupIterator::STRING_LOOKUP_START_OBJECT:
        return it->GetStringPropertyValue();
      case LookupIterator::NOT_FOUND:
        if (it->IsPrivateName()) {
          auto private_symbol = Cast<Symbol>(it->name());
          DirectHandle<String> name_string(
              Cast<String>(private_symbol->description()), it->isolate());
          if (private_symbol->is_private_brand()) {
            DirectHandle<String> class_name =
                name_string->length() == 0
                    ? it->isolate()->factory()->anonymous_string()
                    : name_string;
            THROW_NEW_ERROR(
                it->isolate(),
                NewTypeError(MessageTemplate::kInvalidPrivateBrandInstance,
                             class_name));
          }
          THROW_NEW_ERROR(
              it->isolate(),
              NewTypeError(MessageTemplate::kInvalidPrivateMemberRead,
                           name_string));
        }
        return it->isolate()->factory()->undefined_value();
    }
    UNREACHABLE();
  }
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, ASSIGN_RETURN_ON_EXCEPTION, v8::internal::LookupIterator::DATA, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::LookupIterator::GetDataValue(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetName(), v8::internal::JSProxy::GetProperty(), GetPropertyWithAccessor(), v8::internal::JSObject::GetPropertyWithFailedAccessCheck(), v8::internal::JSObject::GetPropertyWithInterceptor(), v8::internal::LookupIterator::GetReceiver(), v8::internal::LookupIterator::GetStringPropertyValue(), v8::internal::LookupIterator::HasAccess(), v8::internal::JSProxy::HasProperty(), v8::internal::LookupIterator::INTERCEPTOR, v8::Maybe< T >::IsNothing(), v8::internal::LookupIterator::isolate(), v8::internal::LookupIterator::IsPrivateName(), v8::internal::LookupIterator::JSPROXY, v8::internal::LookupIterator::name(), v8::internal::LookupIterator::Next(), v8::internal::LookupIterator::NOT_FOUND, v8::internal::LookupIterator::NotFound(), v8::base::internal::result, v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, THROW_NEW_ERROR, v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), and v8::internal::LookupIterator::WASM_OBJECT.
Referenced by v8::internal::JsonStringifier::ApplyToJsonFunction(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), ArraySpeciesConstructor(), v8::internal::BUILTIN(), v8::internal::Intl::CanonicalizeLocaleList(), v8::internal::JSDisposableStackBase::CheckValueAndGetDisposeMethod(), v8::internal::anonymous_namespace{runtime-object.cc}::CollectPrivateMembersFromReceiver(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectValuesOrEntriesImpl(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CopyElementsHandleSlow(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::Genesis::CreateNewGlobals(), v8::internal::JSReceiver::DefineProperties(), v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::internal::FastGetOwnValuesOrEntries(), v8::internal::anonymous_namespace{json-stringifier.cc}::GetBuiltin(), GetElement(), v8::internal::RegExpUtils::GetLastIndex(), v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::GetNamedCapture(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxyPrototype::GetNamedProperty(), v8::internal::Runtime::GetObjectProperty(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateInstanceProxyCache(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::debug::GetPrivateMembers(), GetProperty(), v8::internal::JSProxy::GetProperty(), v8::internal::anonymous_namespace{property-descriptor.cc}::GetPropertyIfPresent(), GetPropertyOrElement(), GetPropertyWithAccessor(), v8::Object::GetRealNamedProperty(), v8::Object::GetRealNamedPropertyInPrototypeChain(), v8::internal::anonymous_namespace{elements.cc}::IncludesValueSlowPath(), v8::internal::anonymous_namespace{elements.cc}::IndexOfValueSlowPath(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::LoadIC::Load(), v8::internal::anonymous_namespace{runtime-classes.cc}::LoadFromSuper(), v8::internal::anonymous_namespace{runtime-scopes.cc}::LoadLookupSlot(), OrdinaryHasInstance(), v8::internal::RegExpUtils::RegExpExec(), v8::internal::ResizeHelper(), v8::internal::RUNTIME_FUNCTION(), v8::internal::RegExpUtils::SetAdvancedStringIndex(), v8::internal::ValueSerializer::WriteJSArray(), v8::internal::ValueSerializer::WriteJSArrayBuffer(), v8::internal::ValueSerializer::WriteJSError(), v8::internal::ValueSerializer::WriteJSObject(), and v8::internal::ValueSerializer::WriteJSObjectPropertiesSlow().
GetPropertyOrElement() [1/2]
MaybeHandle< Object > v8::internal::Object::GetPropertyOrElement (Isolate * isolate, DirectHandle< JSAny > object, DirectHandle< Name > name) [inline], [static]
Definition at line 1847 of file objects-inl.h.
                                                                          {
  return GetPropertyOrElement(isolate, object, PropertyKey(isolate, name));
}
References v8::internal::name.
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPop(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayShift(), v8::internal::GetBoolOption(), v8::internal::Isolate::GetImportAttributesFromArgument(), v8::internal::wasm::JSPrototypesSetup::GetImportedObject(), v8::internal::GetOwnValuesOrEntries(), v8::internal::GetStringOption(), v8::internal::GetStringOrBooleanOption(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::wasm::InstanceBuilder::LookupImport(), v8::internal::JsonStringifier::SerializeJSObject(), and v8::internal::JsonStringifier::SerializeJSReceiverSlow().
GetPropertyOrElement() [2/2]
MaybeHandle< Object > v8::internal::Object::GetPropertyOrElement (Isolate * isolate, DirectHandle< JSAny > object, PropertyKey key) [inline], [static]
Definition at line 1853 of file objects-inl.h.
                                                                  {
  LookupIterator it(isolate, object, key);
  return GetProperty(&it);
}
References GetProperty(), and v8::internal::key.
GetPropertyWithAccessor()
MaybeHandle< JSAny > v8::internal::Object::GetPropertyWithAccessor (LookupIterator * it) [static]
Definition at line 1517 of file objects.cc.
                                                                     {
  Isolate* isolate = it->isolate();
  DirectHandle<Object> structure = it->GetAccessors();
  DirectHandle<JSAny> receiver = it->GetReceiver();
  // In case of global IC, the receiver is the global object. Replace by the
  // global proxy.
  if (IsJSGlobalObject(*receiver)) {
    receiver =
        direct_handle(Cast<JSGlobalObject>(*receiver)->global_proxy(), isolate);
  }
  // We should never get here to initialize a const with the hole value since a
  // const declaration would conflict with the getter.
  DCHECK(!IsForeign(*structure));
  // API style callbacks.
  DirectHandle<JSObject> holder = it->GetHolder<JSObject>();
  if (IsAccessorInfo(*structure)) {
    DirectHandle<Name> name = it->GetName();
    auto info = Cast<AccessorInfo>(structure);
    if (!info->has_getter(isolate)) {
      return isolate->factory()->undefined_value();
    }
    if (info->is_sloppy() && !IsJSReceiver(*receiver)) {
      ASSIGN_RETURN_ON_EXCEPTION(isolate, receiver,
                                 Object::ConvertReceiver(isolate, receiver));
    }
    PropertyCallbackArguments args(isolate, info->data(), *receiver, *holder,
                                   Just(kDontThrow));
    DirectHandle<JSAny> result = args.CallAccessorGetter(info, name);
    RETURN_EXCEPTION_IF_EXCEPTION(isolate);
    Handle<JSAny> reboxed_result(*result, isolate);
    if (info->replace_on_access() && IsJSReceiver(*receiver)) {
      RETURN_ON_EXCEPTION(isolate,
                          Accessors::ReplaceAccessorWithDataProperty(
                              isolate, receiver, holder, name, result));
    }
    return reboxed_result;
  }
  auto accessor_pair = Cast<AccessorPair>(structure);
  // AccessorPair with 'cached' private property.
  if (it->TryLookupCachedProperty(accessor_pair)) {
    return Cast<JSAny>(Object::GetProperty(it));
  }
  // Regular accessor.
  DirectHandle<Object> getter(accessor_pair->getter(), isolate);
  if (IsFunctionTemplateInfo(*getter)) {
    SaveAndSwitchContext save(isolate, holder->GetCreationContext().value());
    return Cast<JSAny>(Builtins::InvokeApiFunction(
        isolate, false, Cast<FunctionTemplateInfo>(getter), receiver, {},
        isolate->factory()->undefined_value()));
  } else if (IsCallable(*getter)) {
    // TODO(rossberg): nicer would be to cast to some JSCallable here...
    return Object::GetPropertyWithDefinedGetter(receiver,
                                                Cast<JSReceiver>(getter));
  }
  // Getter is not a function.
  return isolate->factory()->undefined_value();
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION, ConvertReceiver(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::LookupIterator::GetAccessors(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetName(), GetProperty(), GetPropertyWithDefinedGetter(), v8::internal::LookupIterator::GetReceiver(), v8::internal::Builtins::InvokeApiFunction(), v8::internal::LookupIterator::isolate(), v8::Just(), v8::internal::kDontThrow, v8::internal::name, v8::internal::Accessors::ReplaceAccessorWithDataProperty(), v8::base::internal::result, RETURN_EXCEPTION_IF_EXCEPTION, RETURN_ON_EXCEPTION, and v8::internal::LookupIterator::TryLookupCachedProperty().
Referenced by GetProperty(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IndexOfValueImpl(), and v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IndexOfValueImpl().
GetPropertyWithDefinedGetter()
MaybeHandle< JSAny > v8::internal::Object::GetPropertyWithDefinedGetter (DirectHandle< JSAny > receiver, DirectHandle< JSReceiver > getter) [static]
Definition at line 1653 of file objects.cc.
                                                                   {
  Isolate* isolate = Isolate::Current();
  // Platforms with simulators like arm/arm64 expose a funny issue. If the
  // simulator has a separate JS stack pointer from the C++ stack pointer, it
  // can miss C++ stack overflows in the stack guard at the start of JavaScript
  // functions. It would be very expensive to check the C++ stack pointer at
  // that location. The best solution seems to be to break the impasse by
  // adding checks at possible recursion points. What's more, we don't put
  // this stack check behind the USE_SIMULATOR define in order to keep
  // behavior the same between hardware and simulators.
  StackLimitCheck check(isolate);
  if (check.JsHasOverflowed()) {
    isolate->StackOverflow();
    return kNullMaybeHandle;
  }
  return Cast<JSAny>(Execution::Call(isolate, getter, receiver, {}));
}
References v8::internal::Execution::Call(), v8::internal::Isolate::Current(), v8::internal::StackLimitCheck::JsHasOverflowed(), v8::internal::kNullMaybeHandle, and v8::internal::Isolate::StackOverflow().
Referenced by GetPropertyWithAccessor().
GetPrototypeChainRootMap()
Tagged< Map > v8::internal::Object::GetPrototypeChainRootMap (Tagged< Object > obj, Isolate * isolate) [static], [private]
Definition at line 1687 of file objects.cc.
                                                               {
  DisallowGarbageCollection no_alloc;
  if (IsSmi(obj)) {
    Tagged<Context> native_context = isolate->context()->native_context();
    return native_context->number_function()->initial_map();
  }
  const Tagged<HeapObject> heap_object = Cast<HeapObject>(obj);
  return heap_object->map()->GetPrototypeChainRootMap(isolate);
}
References v8::internal::Isolate::context(), v8::internal::IsSmi(), and v8::internal::native_context.
Referenced by v8::internal::LookupIterator::GetRootForNonJSReceiver(), and v8::internal::StringStream::PrintPrototype().
GetSimpleHash()
Tagged< Object > v8::internal::Object::GetSimpleHash (Tagged< Object > object) [inline], [static], [private]
Definition at line 1878 of file objects-inl.h.
                                                          {
  DisallowGarbageCollection no_gc;
  if (IsSmi(object)) {
    uint32_t hash = ComputeUnseededHash(Smi::ToInt(object));
    return Smi::FromInt(hash & Smi::kMaxValue);
  }
  auto instance_type = Cast<HeapObject>(object)->map()->instance_type();
  if (InstanceTypeChecker::IsHeapNumber(instance_type)) {
    double num = Cast<HeapNumber>(object)->value();
    if (std::isnan(num)) return Smi::FromInt(Smi::kMaxValue);
    // Use ComputeUnseededHash for all values in Signed32 range, including -0,
    // which is considered equal to 0 because collections use SameValueZero.
    uint32_t hash;
    // Check range before conversion to avoid undefined behavior.
    if (num >= kMinInt && num <= kMaxInt && FastI2D(FastD2I(num)) == num) {
      hash = ComputeUnseededHash(FastD2I(num));
    } else {
      hash = ComputeLongHash(base::double_to_uint64(num));
    }
    return Smi::FromInt(hash & Smi::kMaxValue);
  } else if (InstanceTypeChecker::IsName(instance_type)) {
    uint32_t hash = Cast<Name>(object)->EnsureHash();
    return Smi::FromInt(hash);
  } else if (InstanceTypeChecker::IsOddball(instance_type)) {
    uint32_t hash = Cast<Oddball>(object)->to_string()->EnsureHash();
    return Smi::FromInt(hash);
  } else if (InstanceTypeChecker::IsBigInt(instance_type)) {
    uint32_t hash = Cast<BigInt>(object)->Hash();
    return Smi::FromInt(hash & Smi::kMaxValue);
  } else if (InstanceTypeChecker::IsSharedFunctionInfo(instance_type)) {
    uint32_t hash = Cast<SharedFunctionInfo>(object)->Hash();
    return Smi::FromInt(hash & Smi::kMaxValue);
  } else if (InstanceTypeChecker::IsScopeInfo(instance_type)) {
    uint32_t hash = Cast<ScopeInfo>(object)->Hash();
    return Smi::FromInt(hash & Smi::kMaxValue);
  } else if (InstanceTypeChecker::IsScript(instance_type)) {
    int id = Cast<Script>(object)->id();
    return Smi::FromInt(ComputeUnseededHash(id) & Smi::kMaxValue);
  } else if (InstanceTypeChecker::IsTemplateInfo(instance_type)) {
    uint32_t hash = Cast<TemplateInfo>(object)->GetHash();
    DCHECK_EQ(hash, hash & Smi::kMaxValue);
    return Smi::FromInt(hash);
  }
  DCHECK(!InstanceTypeChecker::IsHole(instance_type));
  DCHECK(IsJSReceiver(object));
  return object;
}
References v8::internal::ComputeLongHash(), v8::internal::ComputeUnseededHash(), v8::internal::DCHECK(), DCHECK_EQ, v8::base::double_to_uint64(), v8::internal::FastD2I(), v8::internal::FastI2D(), v8::internal::Smi::FromInt(), v8::internal::IsSmi(), v8::internal::kMaxInt, v8::internal::Smi::kMaxValue, v8::internal::kMinInt, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Smi::ToInt().
Referenced by GetHash(), and GetOrCreateHash().
GreaterThan()
Maybe< bool > v8::internal::Object::GreaterThan (Isolate * isolate, DirectHandle< Object > x, DirectHandle< Object > y) [inline], [static]
Definition at line 1780 of file objects-inl.h.
                                                        {
  Maybe<ComparisonResult> result = Compare(isolate, x, y);
  if (result.IsJust()) {
    switch (result.FromJust()) {
      case ComparisonResult::kGreaterThan:
        return Just(true);
      case ComparisonResult::kLessThan:
      case ComparisonResult::kEqual:
      case ComparisonResult::kUndefined:
        return Just(false);
    }
  }
  return Nothing<bool>();
}
References Compare(), v8::Just(), v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kLessThan, v8::internal::kUndefined, v8::base::internal::result, and v8::internal::y.
Referenced by v8::internal::RUNTIME_FUNCTION().
GreaterThanOrEqual()
Maybe< bool > v8::internal::Object::GreaterThanOrEqual (Isolate * isolate, DirectHandle< Object > x, DirectHandle< Object > y) [inline], [static]
Definition at line 1797 of file objects-inl.h.
                                                               {
  Maybe<ComparisonResult> result = Compare(isolate, x, y);
  if (result.IsJust()) {
    switch (result.FromJust()) {
      case ComparisonResult::kEqual:
      case ComparisonResult::kGreaterThan:
        return Just(true);
      case ComparisonResult::kLessThan:
      case ComparisonResult::kUndefined:
        return Just(false);
    }
  }
  return Nothing<bool>();
}
References Compare(), v8::Just(), v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kLessThan, v8::internal::kUndefined, v8::base::internal::result, and v8::internal::y.
Referenced by v8::internal::RUNTIME_FUNCTION().
HasValidElements()
bool v8::internal::Object::HasValidElements (Tagged< Object > obj) [inline], [static]
Definition at line 730 of file objects-inl.h.
                                                {
  // Dictionary is covered under FixedArray. ByteArray is used
  // for the JSTypedArray backing stores.
  return IsFixedArray(obj) || IsFixedDoubleArray(obj) || IsByteArray(obj);
}
InstanceOf()
MaybeHandle< Object > v8::internal::Object::InstanceOf (Isolate * isolate, DirectHandle< JSAny > object, DirectHandle< JSAny > callable) [static]
Definition at line 1087 of file objects.cc.
                                                                     {
  // The {callable} must be a receiver.
  if (!IsJSReceiver(*callable)) {
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kNonObjectInInstanceOfCheck));
  }
  // Lookup the @@hasInstance method on {callable}.
  DirectHandle<Object> inst_of_handler;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, inst_of_handler,
      Object::GetMethod(isolate, Cast<JSReceiver>(callable),
                        isolate->factory()->has_instance_symbol()));
  if (!IsUndefined(*inst_of_handler, isolate)) {
    // Call the {inst_of_handler} on the {callable}.
    DirectHandle<Object> result;
    DirectHandle<Object> args[] = {object};
    ASSIGN_RETURN_ON_EXCEPTION(isolate, result,
                               Execution::Call(isolate, inst_of_handler,
                                               callable, base::VectorOf(args)));
    return isolate->factory()->ToBoolean(
        Object::BooleanValue(*result, isolate));
  }
  // The {callable} must have a [[Call]] internal method.
  if (!IsCallable(*callable)) {
    THROW_NEW_ERROR(
        isolate, NewTypeError(MessageTemplate::kNonCallableInInstanceOfCheck));
  }
  // Fall back to OrdinaryHasInstance with {callable} and {object}.
  Handle<Object> result;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, result, Object::OrdinaryHasInstance(isolate, callable, object));
  return result;
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION, BooleanValue(), v8::internal::Execution::Call(), v8::internal::Isolate::factory(), GetMethod(), OrdinaryHasInstance(), v8::base::internal::result, THROW_NEW_ERROR, v8::internal::FactoryBase< Impl >::ToBoolean(), and v8::base::VectorOf().
Referenced by v8::Value::InstanceOf(), and OrdinaryHasInstance().
IsArray()
Maybe< bool > v8::internal::Object::IsArray (DirectHandle< Object > object) [inline], [static]
Definition at line 623 of file objects-inl.h.
                                                       {
  if (IsSmi(*object)) return Just(false);
  auto heap_object = Cast<HeapObject>(object);
  if (IsJSArray(*heap_object)) return Just(true);
  if (!IsJSProxy(*heap_object)) return Just(false);
  return JSProxy::IsArray(Cast<JSProxy>(object));
}
References v8::internal::JSProxy::IsArray(), v8::internal::IsSmi(), and v8::Just().
Referenced by ArraySpeciesConstructor(), v8::internal::JsonStringifier::InitializeReplacer(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::anonymous_namespace{builtins-array.cc}::IsConcatSpreadable(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::JsonStringifier::SerializeJSProxy().
IsCodeLike()
bool v8::internal::Object::IsCodeLike (Tagged< Object > obj, Isolate * isolate) [static]
Definition at line 1864 of file objects.cc.
                                                            {
  DisallowGarbageCollection no_gc;
  return IsJSReceiver(obj) && Cast<JSReceiver>(obj)->IsCodeLike(isolate);
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), and v8::internal::Compiler::ValidateDynamicCompilationSource().
IterationHasObservableEffects()
bool v8::internal::Object::IterationHasObservableEffects (Tagged< Object > obj) [static]
Definition at line 1830 of file objects.cc.
                                                             {
  DisallowGarbageCollection no_gc;
  // Check that this object is an array.
  if (!IsJSArray(obj)) return true;
  Tagged<JSArray> array = Cast<JSArray>(obj);
  // Check that we have the original ArrayPrototype.
  Tagged<Object> array_proto = array->map()->prototype();
  if (!IsJSObject(array_proto)) return true;
  Tagged<NativeContext> native_context = array->GetCreationContext().value();
  auto initial_array_prototype = native_context->initial_array_prototype();
  if (initial_array_prototype != array_proto) return true;
  Isolate* isolate = Isolate::Current();
  // Check that the ArrayPrototype hasn't been modified in a way that would
  // affect iteration.
  if (!Protectors::IsArrayIteratorLookupChainIntact(isolate)) return true;
  // For FastPacked kinds, iteration will have the same effect as simply
  // accessing each property in order.
  ElementsKind array_kind = array->GetElementsKind();
  if (IsFastPackedElementsKind(array_kind)) return false;
  // For FastHoley kinds, an element access on a hole would cause a lookup on
  // the prototype. This could have different results if the prototype has been
  // changed.
  if (IsHoleyElementsKind(array_kind) &&
      Protectors::IsNoElementsIntact(isolate)) {
    return false;
  }
  return true;
}
References v8::internal::Isolate::Current(), v8::internal::IsFastPackedElementsKind(), v8::internal::IsHoleyElementsKind(), v8::internal::native_context, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::CopyAndConvertArrayToCppBuffer().
LessThan()
Maybe< bool > v8::internal::Object::LessThan (Isolate * isolate, DirectHandle< Object > x, DirectHandle< Object > y) [inline], [static]
Definition at line 1814 of file objects-inl.h.
                                                     {
  Maybe<ComparisonResult> result = Compare(isolate, x, y);
  if (result.IsJust()) {
    switch (result.FromJust()) {
      case ComparisonResult::kLessThan:
        return Just(true);
      case ComparisonResult::kEqual:
      case ComparisonResult::kGreaterThan:
      case ComparisonResult::kUndefined:
        return Just(false);
    }
  }
  return Nothing<bool>();
}
References Compare(), v8::Just(), v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kLessThan, v8::internal::kUndefined, v8::base::internal::result, and v8::internal::y.
Referenced by v8::internal::RUNTIME_FUNCTION().
LessThanOrEqual()
Maybe< bool > v8::internal::Object::LessThanOrEqual (Isolate * isolate, DirectHandle< Object > x, DirectHandle< Object > y) [inline], [static]
Definition at line 1831 of file objects-inl.h.
                                                            {
  Maybe<ComparisonResult> result = Compare(isolate, x, y);
  if (result.IsJust()) {
    switch (result.FromJust()) {
      case ComparisonResult::kEqual:
      case ComparisonResult::kLessThan:
        return Just(true);
      case ComparisonResult::kGreaterThan:
      case ComparisonResult::kUndefined:
        return Just(false);
    }
  }
  return Nothing<bool>();
}
References Compare(), v8::Just(), v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kLessThan, v8::internal::kUndefined, v8::base::internal::result, and v8::internal::y.
Referenced by v8::internal::RUNTIME_FUNCTION().
NewStorageFor()
Handle< UnionOf< JSAny, Hole > > v8::internal::Object::NewStorageFor (Isolate * isolate, Handle< UnionOf< JSAny, Hole >> object, Representation representation) [static]
Definition at line 240 of file objects.cc.
                                   {
  if (!representation.IsDouble()) return object;
  Handle<HeapNumber> result = isolate->factory()->NewHeapNumberWithHoleNaN();
  if (IsUninitialized(*object, isolate)) {
    result->set_value_as_bits(kHoleNanInt64);
  } else if (IsHeapNumber(*object)) {
    // Ensure that all bits of the double value are preserved.
    result->set_value_as_bits(Cast<HeapNumber>(*object)->value_as_bits());
  } else {
    result->set_value(Cast<Smi>(*object).value());
  }
  return result;
}
References v8::internal::Isolate::factory(), v8::internal::Representation::IsDouble(), v8::internal::kHoleNanInt64, v8::internal::FactoryBase< Impl >::NewHeapNumberWithHoleNaN(), and v8::base::internal::result.
Referenced by v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast().
NoSideEffectsToMaybeString()
template<typename T , template< typename > typename HandleType>
MaybeDirectHandle< String > v8::internal::Object::NoSideEffectsToMaybeString (Isolate * isolate, DirectHandle< Object > input) [inline], [static]
Definition at line 584 of file objects.cc.
                                                  {
  DisallowJavascriptExecution no_js(isolate);
  if (IsString(*input) || IsNumber(*input) || IsOddball(*input)) {
    return Object::ToString(isolate, input).ToHandleChecked();
  } else if (IsJSProxy(*input)) {
    DirectHandle<Object> currInput = input;
    do {
      Tagged<HeapObject> target = Cast<JSProxy>(currInput)->target(isolate);
      currInput = direct_handle(target, isolate);
    } while (IsJSProxy(*currInput));
    return NoSideEffectsToString(isolate, currInput);
  } else if (IsBigInt(*input)) {
    return BigInt::NoSideEffectsToString(isolate, Cast<BigInt>(input));
  } else if (IsJSFunctionOrBoundFunctionOrWrappedFunction(*input)) {
    // -- F u n c t i o n
    DirectHandle<String> fun_str;
    if (IsJSBoundFunction(*input)) {
      fun_str =
          JSBoundFunction::ToString(isolate, Cast<JSBoundFunction>(input));
    } else if (IsJSWrappedFunction(*input)) {
      fun_str =
          JSWrappedFunction::ToString(isolate, Cast<JSWrappedFunction>(input));
    } else {
      DCHECK(IsJSFunction(*input));
      fun_str = JSFunction::ToString(isolate, Cast<JSFunction>(input));
    }
    if (fun_str->length() > 128) {
      IncrementalStringBuilder builder(isolate);
      builder.AppendString(isolate->factory()->NewSubString(fun_str, 0, 111));
      builder.AppendCStringLiteral("...<omitted>...");
      builder.AppendString(isolate->factory()->NewSubString(
          fun_str, fun_str->length() - 2, fun_str->length()));
      return builder.Finish().ToHandleChecked();
    }
    return fun_str;
  } else if (IsSymbol(*input)) {
    // -- S y m b o l
    DirectHandle<Symbol> symbol = Cast<Symbol>(input);
    if (symbol->is_private_name()) {
      return DirectHandle<String>(Cast<String>(symbol->description()), isolate);
    }
    IncrementalStringBuilder builder(isolate);
    builder.AppendCStringLiteral("Symbol(");
    if (IsString(symbol->description())) {
      DirectHandle<String> description(Cast<String>(symbol->description()),
                                       isolate);
      if (description->length() > 128) {
        builder.AppendString(
            isolate->factory()->NewSubString(description, 0, 56));
        builder.AppendCStringLiteral("...<omitted>...");
        builder.AppendString(isolate->factory()->NewSubString(
            description, description->length() - 56, description->length()));
      } else {
        builder.AppendString(description);
      }
    }
    builder.AppendCharacter(')');
    return builder.Finish().ToHandleChecked();
  } else if (IsJSReceiver(*input)) {
    // -- J S R e c e i v e r
    DirectHandle<JSReceiver> receiver = Cast<JSReceiver>(input);
    DirectHandle<Object> to_string = JSReceiver::GetDataProperty(
        isolate, receiver, isolate->factory()->toString_string());
    if (IsErrorObject(isolate, input) ||
        *to_string == *isolate->error_to_string()) {
      // When internally formatting error objects, use a side-effects-free
      // version of Error.prototype.toString independent of the actually
      // installed toString method.
      return NoSideEffectsErrorToString(isolate, receiver);
    } else if (*to_string == *isolate->object_to_string()) {
      DirectHandle<Object> ctor = JSReceiver::GetDataProperty(
          isolate, receiver, isolate->factory()->constructor_string());
      if (IsJSFunctionOrBoundFunctionOrWrappedFunction(*ctor)) {
        DirectHandle<String> ctor_name;
        if (IsJSBoundFunction(*ctor)) {
          ctor_name =
              JSBoundFunction::GetName(isolate, Cast<JSBoundFunction>(ctor))
                  .ToHandleChecked();
        } else if (IsJSFunction(*ctor)) {
          ctor_name = JSFunction::GetName(isolate, Cast<JSFunction>(ctor));
        }
        if (ctor_name->length() != 0) {
          IncrementalStringBuilder builder(isolate);
          builder.AppendCStringLiteral("#<");
          builder.AppendString(ctor_name);
          builder.AppendCharacter('>');
          return builder.Finish().ToHandleChecked();
        }
      }
    }
  }
  return {};
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), v8::internal::IncrementalStringBuilder::AppendString(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::JSBoundFunction::GetName(), v8::internal::JSFunction::GetName(), input, v8::internal::anonymous_namespace{objects.cc}::IsErrorObject(), v8::internal::IsNumber(), v8::internal::anonymous_namespace{objects.cc}::NoSideEffectsErrorToString(), v8::internal::BigInt::NoSideEffectsToString(), NoSideEffectsToString(), v8::internal::JSBoundFunction::ToString(), v8::internal::JSFunction::ToString(), v8::internal::JSWrappedFunction::ToString(), and v8::Value::ToString().
Referenced by v8::internal::Runtime::DefineObjectOwnProperty(), NoSideEffectsToString(), v8::internal::Runtime::SetObjectProperty(), and v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined().
NoSideEffectsToString()
DirectHandle< String > v8::internal::Object::NoSideEffectsToString (Isolate * isolate, DirectHandle< Object > input) [static]
Definition at line 689 of file objects.cc.
                                                                               {
  DisallowJavascriptExecution no_js(isolate);
  // Try to convert input to a meaningful string.
  MaybeDirectHandle<String> maybe_string =
      NoSideEffectsToMaybeString(isolate, input);
  DirectHandle<String> string_handle;
  if (maybe_string.ToHandle(&string_handle)) {
    return string_handle;
  }
  // At this point, input is either none of the above or a JSReceiver.
  DirectHandle<JSReceiver> receiver;
  if (IsJSReceiver(*input)) {
    receiver = Cast<JSReceiver>(input);
  } else {
    // This is the only case where Object::ToObject throws.
    DCHECK(!IsSmi(*input));
    int constructor_function_index =
        Cast<HeapObject>(input)->map()->GetConstructorFunctionIndex();
    if (constructor_function_index == Map::kNoConstructorFunctionIndex) {
      return isolate->factory()->NewStringFromAsciiChecked("[object Unknown]");
    }
    receiver = Object::ToObjectImpl(isolate, input).ToHandleChecked();
  }
  DirectHandle<String> builtin_tag =
      direct_handle(receiver->class_name(), isolate);
  DirectHandle<Object> tag_obj = JSReceiver::GetDataProperty(
      isolate, receiver, isolate->factory()->to_string_tag_symbol());
  DirectHandle<String> tag =
      IsString(*tag_obj) ? Cast<String>(tag_obj) : builtin_tag;
  IncrementalStringBuilder builder(isolate);
  builder.AppendCStringLiteral("[object ");
  builder.AppendString(tag);
  builder.AppendCharacter(']');
  return builder.Finish().ToHandleChecked();
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), v8::internal::IncrementalStringBuilder::AppendString(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::JSReceiver::GetDataProperty(), input, v8::internal::IsSmi(), v8::internal::Map::kNoConstructorFunctionIndex, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), NoSideEffectsToMaybeString(), v8::internal::MaybeDirectHandle< T >::ToHandle(), and ToObjectImpl().
Referenced by v8::internal::BUILTIN(), v8::internal::JSWrappedFunction::Create(), v8::internal::wasm::ErrorStringForCodegen(), v8::internal::MessageFormatter::Format(), NoSideEffectsToMaybeString(), v8::internal::MessageHandler::ReportMessage(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ErrorUtils::ShadowRealmConstructTypeErrorCopy(), v8::internal::anonymous_namespace{runtime-classes.cc}::ThrowNotSuperConstructor(), and v8::Value::ToDetailString().
NumberValue() [1/4]
double v8::internal::Object::NumberValue (Tagged< HeapNumber > obj) [inline], [static]
Definition at line 685 of file objects-inl.h.
                                                 {
  return NumberValue(Cast<Number>(obj));
}
References NumberValue().
NumberValue() [2/4]
double v8::internal::Object::NumberValue (Tagged< Number > obj) [inline], [static]
Definition at line 675 of file objects-inl.h.
                                             {
  DCHECK(IsNumber(obj));
  return IsSmi(obj) ? static_cast<double>(UncheckedCast<Smi>(obj).value())
                    : UncheckedCast<HeapNumber>(obj)->value();
}
References v8::internal::DCHECK(), v8::internal::IsNumber(), and v8::internal::IsSmi().
Referenced by Add(), v8::internal::JSArray::AnythingToArrayLength(), v8::internal::anonymous_namespace{asm-js.cc}::AreStdlibMembersValid(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::ArrayBufferTransfer(), v8::internal::ArrayConstructInitializeElements(), v8::internal::JsonParser< Char >::BuildJsonArray(), v8::internal::BUILTIN(), v8::internal::Intl::CanonicalizeLocaleList(), v8::internal::anonymous_namespace{builtins-sharedarraybuffer.cc}::CheckAtomicsPauseIterationNumber(), v8::internal::anonymous_namespace{builtins-array.cc}::CollectElementIndices(), Compare(), v8::internal::anonymous_namespace{elements.cc}::CopyDictionaryToDoubleElements(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::anonymous_namespace{elements.cc}::CopyObjectToDoubleElements(), v8::CopySmiElementsToTypedBuffer(), v8::internal::JSDataObjectBuilder::CreateAndInitialiseObject(), v8::internal::Heap::CreateImportantReadOnlyObjects(), v8::internal::JSDateTimeFormat::DateTimeFormat(), v8::internal::DefaultNumberOption(), v8::internal::DoWait(), v8::internal::anonymous_namespace{builtins-array.cc}::EstimateElementCount(), v8::internal::V8HeapExplorer::ExtractElementReferences(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::FilterKey(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::FormatCommon(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatRangeCommon(), v8::internal::JSDateTimeFormat::FormatToParts(), v8::internal::IntlMathematicalValue::From(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPop(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPush(), v8::internal::anonymous_namespace{builtins-array.cc}::GetLengthProperty(), v8::internal::GetNumberOptionAsDouble(), v8::internal::TranslatedValue::GetRawValue(), v8::internal::Isolate::GetStackTraceLimit(), v8::internal::temporal::GetTemporalFractionalSecondDigitsOption(), v8::internal::anonymous_namespace{builtins-atomics-synchronization.cc}::GetTimeoutDelta(), v8::internal::TranslatedValue::GetValue(), v8::internal::anonymous_namespace{js-date-time-format.cc}::HandleDateTimeOthers(), v8::internal::CompilationCacheShape::HashForObject(), v8::internal::NumberDictionaryBaseShape::HashForObject(), v8::internal::V8FileLogger::ICEvent(), v8::internal::anonymous_namespace{js-number-format.cc}::IcuFormatNumber(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::IndexOfValueImpl(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::IndexOfValueImpl(), v8::internal::Oddball::Initialize(), v8::internal::JsonStringifier::InitializeGap(), v8::internal::TranslatedState::InitializeJSObjectAt(), v8::internal::TranslatedState::InitializeObjectWithTaggedFieldsAt(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::Value::IsInt32(), v8::internal::temporal::anonymous_namespace{js-temporal-helpers.cc}::IsIntegralNumber(), v8::internal::NumberDictionaryBaseShape::IsMatch(), v8::internal::anonymous_namespace{ic.cc}::IsOutOfBoundsAccess(), v8::Value::IsUint32(), v8::internal::anonymous_namespace{builtins-string.cc}::IsValidCodePoint(), v8::internal::anonymous_namespace{builtins-array.cc}::IterateElements(), v8::internal::JSObject::JSObjectShortPrint(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::LastIndexOfValueImpl(), v8::internal::TranslatedState::MaterializeFixedDoubleArray(), v8::internal::TranslatedState::MaterializeHeapNumber(), v8::internal::WasmTableObject::maximum_length_u64(), v8::internal::DictionaryTemplateInfo::NewInstance(), v8::internal::anonymous_namespace{builtins-string.cc}::NextCodePoint(), v8::internal::Arguments< arguments_type >::number_value_at(), v8::Value::NumberValue(), NumberValue(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::PrependElementIndicesImpl(), v8::internal::StringStream::PrintMentionedObjectCache(), v8::internal::wasm::InstanceBuilder::ProcessImportedGlobal(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForGlobalAccess(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualJSObjectDetails(), v8::internal::RUNTIME_FUNCTION(), SameValue(), SameValueZero(), v8::internal::FastJsonStringifier< Char >::SerializeJSArray(), v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::SetImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::SetLengthImpl(), v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat(), v8::internal::JSObject::SlowReverseLookup(), v8::internal::anonymous_namespace{elements.cc}::SortIndices(), v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt(), v8::internal::anonymous_namespace{objects.cc}::StrictNumberEquals(), v8::internal::temporal::ToIntegerIfIntegral(), v8::internal::temporal::anonymous_namespace{js-temporal-helpers.cc}::ToIntegerWithoutRounding(), v8::internal::anonymous_namespace{builtins-array.cc}::TryFastArrayFill(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::ValidateContents(), v8::Number::Value(), v8::Integer::Value(), v8::Int32::Value(), v8::Uint32::Value(), v8::NumberObject::ValueOf(), and v8::internal::ValueSerializer::WriteJSPrimitiveWrapper().
NumberValue() [3/4]
double v8::internal::Object::NumberValue (Tagged< Object > obj) [inline], [static]
Definition at line 682 of file objects-inl.h.
                                             {
  return NumberValue(Cast<Number>(obj));
}
References NumberValue().
NumberValue() [4/4]
double v8::internal::Object::NumberValue (Tagged< Smi > obj) [inline], [static]
Definition at line 688 of file objects-inl.h.
                                          {
  return NumberValue(Cast<Number>(obj));
}
References NumberValue().
OptimalElementsKind()
ElementsKind v8::internal::Object::OptimalElementsKind (Tagged< Object > obj, PtrComprCageBase cage_base) [inline], [static]
Definition at line 768 of file objects-inl.h.
                                                                     {
  if (IsSmi(obj)) return PACKED_SMI_ELEMENTS;
  if (IsHeapNumber(obj, cage_base)) return PACKED_DOUBLE_ELEMENTS;
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
  if (IsUndefined(obj, GetReadOnlyRoots())) {
    return HOLEY_DOUBLE_ELEMENTS;
  }
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
  return PACKED_ELEMENTS;
}
References v8::internal::GetReadOnlyRoots(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::IsSmi(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, and v8::internal::PACKED_SMI_ELEMENTS.
Referenced by v8::internal::JSObject::AddDataElement(), v8::internal::ArrayLiteralBoilerplateBuilder::BuildBoilerplateDescription(), v8::internal::LookupIterator::PrepareForDataProperty(), and v8::internal::anonymous_namespace{builtins-array.cc}::TryFastArrayFill().
OptimalRepresentation()
Representation v8::internal::Object::OptimalRepresentation (Tagged< Object > obj, PtrComprCageBase cage_base) [inline], [static]
Definition at line 753 of file objects-inl.h.
                                                                         {
  if (IsSmi(obj)) {
    return Representation::Smi();
  }
  Tagged<HeapObject> heap_object = Cast<HeapObject>(obj);
  if (IsHeapNumber(heap_object, cage_base)) {
    return Representation::Double();
  } else if (IsUninitialized(heap_object)) {
    return Representation::None();
  }
  return Representation::HeapObject();
}
References v8::internal::Representation::Double(), v8::internal::Representation::HeapObject(), v8::internal::IsSmi(), v8::internal::Representation::None(), and v8::internal::Representation::Smi().
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::Map::CopyWithConstant(), v8::internal::Descriptor::DataConstant(), v8::internal::Map::TransitionToDataProperty(), v8::internal::JSDataObjectBuilder::TryAddFastPropertyForValue(), v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue(), and v8::internal::anonymous_namespace{map.cc}::UpdateDescriptorForValue().
OptimalType()
DirectHandle< FieldType > v8::internal::Object::OptimalType (Tagged< Object > obj, Isolate * isolate, Representation representation) [static]
Definition at line 224 of file objects.cc.
                                                                           {
  if (representation.IsNone()) return FieldType::None(isolate);
  if (v8_flags.track_field_types) {
    if (representation.IsHeapObject() && IsHeapObject(obj)) {
      // We can track only JavaScript objects with stable maps.
      DirectHandle<Map> map(Cast<HeapObject>(obj)->map(), isolate);
      if (map->is_stable() && IsJSReceiverMap(*map)) {
        return FieldType::Class(map, isolate);
      }
    }
  }
  return FieldType::Any(isolate);
}
References v8::internal::FieldType::Any(), v8::internal::FieldType::Class(), v8::internal::Representation::IsHeapObject(), v8::internal::IsHeapObject(), v8::internal::Representation::IsNone(), v8::internal::FieldType::None(), and v8::internal::v8_flags.
Referenced by v8::internal::Map::CopyWithConstant(), v8::internal::MapUpdater::GetOrComputeFieldType(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), v8::internal::Map::TransitionToDataProperty(), v8::internal::JSDataObjectBuilder::TryAddFastPropertyForValue(), v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue(), and v8::internal::anonymous_namespace{map.cc}::UpdateDescriptorForValue().
OrdinaryHasInstance()
MaybeHandle< Object > v8::internal::Object::OrdinaryHasInstance (Isolate * isolate, DirectHandle< JSAny > callable, DirectHandle< JSAny > object) [static]
Definition at line 1047 of file objects.cc.
                                                                            {
  // The {callable} must have a [[Call]] internal method.
  if (!IsCallable(*callable)) return isolate->factory()->false_value();
  // Check if {callable} is a bound function, and if so retrieve its
  // [[BoundTargetFunction]] and use that instead of {callable}.
  if (IsJSBoundFunction(*callable)) {
    // Since there is a mutual recursion here, we might run out of stack
    // space for long chains of bound functions.
    STACK_CHECK(isolate, MaybeHandle<Object>());
    DirectHandle<JSCallable> bound_callable(
        Cast<JSBoundFunction>(callable)->bound_target_function(), isolate);
    return Object::InstanceOf(isolate, object, bound_callable);
  }
  // If {object} is not a receiver, return false.
  if (!IsJSReceiver(*object)) return isolate->factory()->false_value();
  // Get the "prototype" of {callable}; raise an error if it's not a receiver.
  DirectHandle<Object> prototype;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, prototype,
      Object::GetProperty(isolate, callable,
                          isolate->factory()->prototype_string()));
  if (!IsJSReceiver(*prototype)) {
    THROW_NEW_ERROR(
        isolate,
        NewTypeError(MessageTemplate::kInstanceofNonobjectProto, prototype));
  }
  // Return whether or not {prototype} is in the prototype chain of {object}.
  Maybe<bool> result = JSReceiver::HasInPrototypeChain(
      isolate, Cast<JSReceiver>(object), prototype);
  if (result.IsNothing()) return MaybeHandle<Object>();
  return isolate->factory()->ToBoolean(result.FromJust());
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::factory(), GetProperty(), v8::internal::JSReceiver::HasInPrototypeChain(), InstanceOf(), v8::internal::prototype, v8::base::internal::result, STACK_CHECK, THROW_NEW_ERROR, and v8::internal::FactoryBase< Impl >::ToBoolean().
Referenced by InstanceOf(), v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor(), v8::internal::Intl::LegacyUnwrapReceiver(), and v8::internal::RUNTIME_FUNCTION().
RedefineIncompatibleProperty()
Maybe< bool > v8::internal::Object::RedefineIncompatibleProperty (Isolate * isolate, DirectHandle< Object > name, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw) [static]
Definition at line 2623 of file objects.cc.
                                     {
  RETURN_FAILURE(isolate, GetShouldThrow(isolate, should_throw),
                 NewTypeError(MessageTemplate::kRedefineDisallowed, name));
}
References v8::internal::GetShouldThrow(), v8::internal::name, and RETURN_FAILURE.
Referenced by v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), and SetSuperProperty().
requires()
template<typename T , template< typename > typename HandleType>
v8::internal::Object::requires (std::is_convertible_v< HandleType< T >, DirectHandle< T >>)
SameNumberValue()
bool v8::internal::Object::SameNumberValue (double number1, double number2) [inline], [static]
Definition at line 705 of file objects-inl.h.
                                                         {
  // Compare values bitwise, to cover -0 being different from 0 -- we'd need to
  // look at sign bits anyway if we'd done a double comparison, so we may as
  // well compare bitwise immediately.
  uint64_t value1_bits = base::bit_cast<uint64_t>(value1);
  uint64_t value2_bits = base::bit_cast<uint64_t>(value2);
  if (value1_bits == value2_bits) {
    return true;
  }
  // SameNumberValue(NaN, NaN) is true even for NaNs with different bit
  // representations.
  return std::isnan(value1) && std::isnan(value2);
}
Referenced by v8::internal::BUILTIN(), and SameValue().
SameValue()
bool v8::internal::Object::SameValue (Tagged< Object > obj, Tagged< Object > other) [static]
Definition at line 1710 of file objects.cc.
                                                               {
  if (other == obj) return true;
  if (IsNumber(obj) && IsNumber(other)) {
    return SameNumberValue(Object::NumberValue(Cast<Number>(obj)),
                           Object::NumberValue(Cast<Number>(other)));
  }
  if (IsString(obj) && IsString(other)) {
    return Cast<String>(obj)->Equals(Cast<String>(other));
  }
  if (IsBigInt(obj) && IsBigInt(other)) {
    return BigInt::EqualToBigInt(Cast<BigInt>(obj), Cast<BigInt>(other));
  }
  return false;
}
References v8::internal::BigInt::EqualToBigInt(), v8::internal::IsNumber(), NumberValue(), and SameNumberValue().
Referenced by v8::internal::anonymous_namespace{js-array-buffer.cc}::CanonicalNumericIndexString(), v8::internal::JSProxy::CheckGetSetTrapResult(), v8::internal::JSModuleNamespace::DefineOwnProperty(), v8::internal::JSProxy::GetPrototype(), v8::internal::anonymous_namespace{js-objects.cc}::HasExcludedProperty(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::ObjectHashTableShapeBase::IsMatch(), v8::Value::SameValue(), v8::internal::JSProxy::SetPrototype(), v8::internal::SliceHelper(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
SameValueZero()
bool v8::internal::Object::SameValueZero (Tagged< Object > obj, Tagged< Object > other) [static]
Definition at line 1727 of file objects.cc.
                                                                   {
  if (other == obj) return true;
  if (IsNumber(obj) && IsNumber(other)) {
    double this_value = Object::NumberValue(Cast<Number>(obj));
    double other_value = Object::NumberValue(Cast<Number>(other));
    // +0 == -0 is true
    return this_value == other_value ||
           (std::isnan(this_value) && std::isnan(other_value));
  }
  if (IsString(obj) && IsString(other)) {
    return Cast<String>(obj)->Equals(Cast<String>(other));
  }
  if (IsBigInt(obj) && IsBigInt(other)) {
    return BigInt::EqualToBigInt(Cast<BigInt>(obj), Cast<BigInt>(other));
  }
  return false;
}
References v8::internal::BigInt::EqualToBigInt(), v8::internal::IsNumber(), and NumberValue().
Referenced by v8::internal::OrderedHashMap::Add(), v8::internal::OrderedHashTable< Derived, entrysize >::FindEntry(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IncludesValueFastPath(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IncludesValueImpl(), v8::internal::anonymous_namespace{elements.cc}::IncludesValueSlowPath(), v8::internal::requires(), and v8::internal::RUNTIME_FUNCTION().
SetDataProperty()
Maybe< bool > v8::internal::Object::SetDataProperty (LookupIterator * it, DirectHandle< Object > value) [static]
Definition at line 2630 of file objects.cc.
                                                                {
  Isolate* isolate = it->isolate();
  DCHECK_IMPLIES(IsJSProxy(*it->GetReceiver(), isolate),
                 it->GetName()->IsPrivateName());
  DCHECK_IMPLIES(!it->IsElement() && it->GetName()->IsPrivateName(),
                 it->state() == LookupIterator::DATA);
  DirectHandle<JSReceiver> receiver = Cast<JSReceiver>(it->GetReceiver());
  // Store on the holder which may be hidden behind the receiver.
  DCHECK(it->HolderIsReceiverOrHiddenPrototype());
  DirectHandle<Object> to_assign = value;
  // Convert the incoming value to a number for storing into typed arrays.
  if (it->IsElement() && IsJSObject(*receiver, isolate) &&
      Cast<JSObject>(*receiver)->HasTypedArrayOrRabGsabTypedArrayElements(
          isolate)) {
    auto receiver_ta = Cast<JSTypedArray>(receiver);
    ElementsKind elements_kind = Cast<JSObject>(*receiver)->GetElementsKind();
    if (IsBigIntTypedArrayElementsKind(elements_kind)) {
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, to_assign,
                                       BigInt::FromObject(isolate, value),
                                       Nothing<bool>());
      if (V8_UNLIKELY(receiver_ta->IsDetachedOrOutOfBounds() ||
                      it->index() >= receiver_ta->GetLength())) {
        return Just(true);
      }
    } else if (!IsNumber(*value) && !IsUndefined(*value, isolate)) {
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, to_assign,
                                       Object::ToNumber(isolate, value),
                                       Nothing<bool>());
      if (V8_UNLIKELY(receiver_ta->IsDetachedOrOutOfBounds() ||
                      it->index() >= receiver_ta->GetLength())) {
        return Just(true);
      }
    }
  }
  DCHECK(!IsWasmObject(*receiver, isolate));
  if (V8_UNLIKELY(IsJSSharedStruct(*receiver, isolate) ||
                  IsJSSharedArray(*receiver, isolate))) {
    // Shared structs can only point to primitives or shared values.
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, to_assign, Object::Share(isolate, to_assign, kThrowOnError),
        Nothing<bool>());
    it->WriteDataValue(to_assign, false);
  } else {
    // Possibly migrate to the most up-to-date map that will be able to store
    // |value| under it->name().
    it->PrepareForDataProperty(to_assign);
    // Write the property value.
    it->WriteDataValue(to_assign, false);
  }
#if VERIFY_HEAP
  if (v8_flags.verify_heap) {
    receiver->HeapObjectVerify(isolate);
  }
#endif
  return Just(true);
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::LookupIterator::DATA, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::LookupIterator::GetName(), v8::internal::LookupIterator::GetReceiver(), v8::internal::LookupIterator::HolderIsReceiverOrHiddenPrototype(), v8::internal::LookupIterator::index(), v8::internal::IsBigIntTypedArrayElementsKind(), v8::internal::LookupIterator::IsElement(), v8::internal::IsNumber(), v8::internal::LookupIterator::isolate(), v8::internal::IsWasmObject(), v8::Just(), v8::internal::kThrowOnError, v8::internal::LookupIterator::PrepareForDataProperty(), v8::internal::LookupIterator::state(), v8::Value::ToNumber(), v8::internal::v8_flags, V8_UNLIKELY, v8::internal::value, and v8::internal::LookupIterator::WriteDataValue().
Referenced by v8::internal::anonymous_namespace{runtime-regexp.cc}::ConstructNamedCaptureGroupsObject(), v8::internal::AlwaysSharedSpaceJSObject::DefineOwnProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::ScopeIterator::SetContextExtensionValue(), SetPropertyInternal(), and SetSuperProperty().
SetElement()
MaybeDirectHandle< Object > v8::internal::Object::SetElement (Isolate * isolate, DirectHandle< JSAny > object, uint32_t index, DirectHandle< Object > value, ShouldThrow should_throw) [inline], [static]
Definition at line 940 of file objects-inl.h.
                                                                       {
  LookupIterator it(isolate, object, index);
  MAYBE_RETURN_NULL(
      SetProperty(&it, value, StoreOrigin::kMaybeKeyed, Just(should_throw)));
  return value;
}
References v8::internal::index, v8::Just(), v8::internal::kMaybeKeyed, MAYBE_RETURN_NULL, SetProperty(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPush(), and v8::Object::Set().
SetProperty() [1/2]
MaybeHandle< Object > v8::internal::Object::SetProperty (Isolate * isolate, DirectHandle< JSAny > object, DirectHandle< Name > name, DirectHandle< Object > value, StoreOrigin store_origin = StoreOrigin::kMaybeKeyed, Maybe< ShouldThrow > should_throw = Nothing<ShouldThrow>()) [static]
Definition at line 2268 of file objects.cc.
                                                                         {
  LookupIterator it(isolate, object, name);
  MAYBE_RETURN_NULL(SetProperty(&it, value, store_origin, should_throw));
  return indirect_handle(value, isolate);
}
References v8::internal::indirect_handle(), MAYBE_RETURN_NULL, v8::internal::name, SetProperty(), and v8::internal::value.
SetProperty() [2/2]
Maybe< bool > v8::internal::Object::SetProperty (LookupIterator * it, DirectHandle< Object > value, StoreOrigin store_origin, Maybe< ShouldThrow > should_throw = Nothing<ShouldThrow>()) [static]
Definition at line 2460 of file objects.cc.
                                                                 {
  if (it->IsFound()) {
    bool found = true;
    Maybe<bool> result =
        SetPropertyInternal(it, value, should_throw, store_origin, &found);
    if (found) return result;
  }
  if (!CheckContextualStoreToJSGlobalObject(it, should_throw)) {
    return Nothing<bool>();
  }
  return AddDataProperty(it, value, NONE, should_throw, store_origin);
}
References AddDataProperty(), CheckContextualStoreToJSGlobalObject(), v8::internal::LookupIterator::IsFound(), v8::internal::NONE, v8::base::internal::result, SetPropertyInternal(), and v8::internal::value.
Referenced by v8::internal::Isolate::CaptureAndSetErrorStack(), v8::internal::ArrayProxy::Create(), v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPop(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPush(), v8::internal::ErrorUtils::GetFormattedStack(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::GetNameTable(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateInstanceProxyCache(), v8::internal::JSRegExp::Initialize(), v8::internal::MoveMessageToPromise(), v8::internal::WasmMemoryObject::New(), v8::internal::Factory::NewArgumentsObject(), v8::internal::WasmMemoryObject::RefreshBuffer(), v8::internal::WasmMemoryObject::RefreshSharedBuffer(), v8::internal::JSPromise::Resolve(), v8::internal::RUNTIME_FUNCTION(), SetElement(), v8::internal::ErrorUtils::SetFormattedStack(), v8::internal::RegExpUtils::SetLastIndex(), v8::internal::anonymous_namespace{builtins-array.cc}::SetLengthProperty(), v8::internal::Runtime::SetObjectProperty(), v8::internal::Runtime::SetPrivateMember(), SetProperty(), SetPropertyOrElement(), v8::internal::ErrorUtils::ShadowRealmConstructTypeErrorCopy(), v8::internal::StoreIC::Store(), v8::internal::anonymous_namespace{runtime-scopes.cc}::StoreLookupSlot(), v8::internal::Isolate::ThrowAt(), and v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::ToJSReceiver().
SetPropertyInternal()
Maybe< bool > v8::internal::Object::SetPropertyInternal (LookupIterator * it, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw, StoreOrigin store_origin, bool * found) [static], [private]
Definition at line 2279 of file objects.cc.
                                                                               {
  it->UpdateProtector();
  DCHECK(it->IsFound());
  // Make sure that the top context does not change when doing callbacks or
  // interceptor calls.
  AssertNoContextChange ncc(it->isolate());
  for (;; it->Next()) {
    switch (it->state()) {
      case LookupIterator::ACCESS_CHECK:
        if (it->HasAccess()) continue;
        // Check whether it makes sense to reuse the lookup iterator. Here it
        // might still call into setters up the prototype chain.
        return JSObject::SetPropertyWithFailedAccessCheck(it, value,
                                                          should_throw);
      case LookupIterator::JSPROXY: {
        DirectHandle<JSAny> receiver = it->GetReceiver();
        // In case of global IC, the receiver is the global object. Replace by
        // the global proxy.
        if (IsJSGlobalObject(*receiver)) {
          receiver = direct_handle(
              Cast<JSGlobalObject>(*receiver)->global_proxy(), it->isolate());
        }
        return JSProxy::SetProperty(it->GetHolder<JSProxy>(), it->GetName(),
                                    value, receiver, should_throw);
      }
      case LookupIterator::WASM_OBJECT:
        continue; // Continue to the prototype, if present.
      case LookupIterator::INTERCEPTOR: {
        if (it->HolderIsReceiverOrHiddenPrototype()) {
          InterceptorResult result;
          if (!JSObject::SetPropertyWithInterceptor(it, should_throw, value)
                   .To(&result)) {
            // An exception was thrown in the interceptor. Propagate.
            return Nothing<bool>();
          }
          switch (result) {
            case InterceptorResult::kFalse:
              return Just(false);
            case InterceptorResult::kTrue:
              return Just(true);
            case InterceptorResult::kNotIntercepted:
              // Proceed lookup.
              break;
          }
          // Assuming that the callback has side effects, we use
          // Object::SetSuperProperty() which works properly regardless on
          // whether the property was present on the receiver or not when
          // storing to the receiver.
          // Proceed lookup from the next state.
          it->Next();
        } else {
          Maybe<PropertyAttributes> maybe_attributes =
              JSObject::GetPropertyAttributesWithInterceptor(it);
          if (maybe_attributes.IsNothing()) return Nothing<bool>();
          if ((maybe_attributes.FromJust() & READ_ONLY) != 0) {
            return WriteToReadOnlyProperty(it, value, should_throw);
          }
          // At this point we might have called interceptor's query or getter
          // callback. Assuming that the callbacks have side effects, we use
          // Object::SetSuperProperty() which works properly regardless on
          // whether the property was present on the receiver or not when
          // storing to the receiver.
          if (maybe_attributes.FromJust() == ABSENT) {
            // Proceed lookup from the next state.
            it->Next();
          } else {
            // Finish lookup in order to make Object::SetSuperProperty() store
            // property to the receiver.
            it->NotFound();
          }
        }
        return Object::SetSuperProperty(it, value, store_origin, should_throw);
      }
      case LookupIterator::ACCESSOR: {
        if (it->IsReadOnly()) {
          return WriteToReadOnlyProperty(it, value, should_throw);
        }
        DirectHandle<Object> accessors = it->GetAccessors();
        if (IsAccessorInfo(*accessors) &&
            !it->HolderIsReceiverOrHiddenPrototype()) {
          *found = false;
          return Nothing<bool>();
        }
        return SetPropertyWithAccessor(it, value, should_throw);
      }
      case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND: {
        // IntegerIndexedElementSet converts value to a Number/BigInt prior to
        // the bounds check. The bounds check has already happened here, but
        // perform the possibly effectful ToNumber (or ToBigInt) operation
        // anyways.
        DirectHandle<JSTypedArray> holder = it->GetHolder<JSTypedArray>();
        // The index found case uses HolderIsReceiverOrHiddenPrototype()
        // in below "case LookupIterator::DATA" to check
        // "i. If SameValue(O, Receiver) is true..." of the spec.
        // https://tc39.es/ecma262/#sec-typedarray-set
        if (it->HolderIsReceiver()) {
          DirectHandle<Object> converted_value;
          if (holder->type() == kExternalBigInt64Array ||
              holder->type() == kExternalBigUint64Array) {
            ASSIGN_RETURN_ON_EXCEPTION_VALUE(
                it->isolate(), converted_value,
                BigInt::FromObject(it->isolate(), value), Nothing<bool>());
          } else {
            ASSIGN_RETURN_ON_EXCEPTION_VALUE(
                it->isolate(), converted_value,
                Object::ToNumber(it->isolate(), value), Nothing<bool>());
          }
          // For RAB/GSABs, the above conversion might grow the buffer so that
          // the index is no longer out of bounds. Redo the bounds check and try
          // again.
          it->RecheckTypedArrayBounds();
          value = converted_value;
        }
        if (it->state() != LookupIterator::DATA) {
          // Still out of bounds.
          DCHECK_EQ(it->state(), LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND);
          // FIXME: Throw a TypeError if the holder is detached here
          // (IntegerIndexedElementSet step 5).
          // TODO(verwaest): Per spec, we should return false here (steps 6-9
          // in IntegerIndexedElementSet), resulting in an exception being
          // thrown on OOB accesses in strict code. Historically, v8 has not
          // done made this change due to uncertainty about web compat.
          // (v8:4901)
          return Just(true);
        }
        [[fallthrough]];
      }
      case LookupIterator::DATA:
        if (it->IsReadOnly()) {
          return WriteToReadOnlyProperty(it, value, should_throw);
        }
        if (it->HolderIsReceiverOrHiddenPrototype()) {
          return SetDataProperty(it, value);
        }
        [[fallthrough]];
      case LookupIterator::NOT_FOUND:
      case LookupIterator::TRANSITION:
        *found = false;
        return Nothing<bool>();
      case LookupIterator::STRING_LOOKUP_START_OBJECT:
        return WriteToReadOnlyProperty(it, value, should_throw);
    }
    UNREACHABLE();
  }
}
References v8::internal::ABSENT, v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::LookupIterator::DATA, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::Maybe< T >::FromJust(), v8::internal::LookupIterator::GetAccessors(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetName(), v8::internal::JSObject::GetPropertyAttributesWithInterceptor(), v8::internal::LookupIterator::GetReceiver(), v8::internal::LookupIterator::HasAccess(), v8::internal::LookupIterator::HolderIsReceiver(), v8::internal::LookupIterator::HolderIsReceiverOrHiddenPrototype(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::LookupIterator::IsFound(), v8::Maybe< T >::IsNothing(), v8::internal::LookupIterator::isolate(), v8::internal::LookupIterator::IsReadOnly(), v8::internal::LookupIterator::JSPROXY, v8::Just(), v8::internal::kExternalBigInt64Array, v8::internal::kExternalBigUint64Array, v8::internal::kFalse, v8::internal::kNotIntercepted, v8::internal::kTrue, v8::internal::LookupIterator::Next(), v8::internal::LookupIterator::NOT_FOUND, v8::internal::LookupIterator::NotFound(), v8::internal::READ_ONLY, v8::internal::LookupIterator::RecheckTypedArrayBounds(), v8::base::internal::result, SetDataProperty(), v8::internal::JSProxy::SetProperty(), SetPropertyWithAccessor(), v8::internal::JSObject::SetPropertyWithFailedAccessCheck(), v8::internal::JSObject::SetPropertyWithInterceptor(), SetSuperProperty(), v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, v8::Value::ToNumber(), v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), v8::internal::LookupIterator::UpdateProtector(), v8::internal::value, v8::internal::LookupIterator::WASM_OBJECT, and WriteToReadOnlyProperty().
Referenced by SetProperty(), and SetSuperProperty().
SetPropertyOrElement() [1/2]
MaybeDirectHandle< Object > v8::internal::Object::SetPropertyOrElement (Isolate * isolate, DirectHandle< JSAny > object, DirectHandle< Name > name, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw = Nothing<ShouldThrow>(), StoreOrigin store_origin = StoreOrigin::kMaybeKeyed) [inline], [static]
Definition at line 1860 of file objects-inl.h.
                              {
  return SetPropertyOrElement(isolate, object, PropertyKey(isolate, name),
                              value, should_throw, store_origin);
}
References v8::internal::name, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayFill(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayShift(), and v8::internal::ScopeIterator::ScopeObject().
SetPropertyOrElement() [2/2]
MaybeDirectHandle< Object > v8::internal::Object::SetPropertyOrElement (Isolate * isolate, DirectHandle< JSAny > object, PropertyKey key, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw = Nothing<ShouldThrow>(), StoreOrigin store_origin = StoreOrigin::kMaybeKeyed) [inline], [static]
Definition at line 1868 of file objects-inl.h.
                              {
  LookupIterator it(isolate, object, key);
  MAYBE_RETURN_NULL(SetProperty(&it, value, store_origin, should_throw));
  return value;
}
References v8::internal::key, MAYBE_RETURN_NULL, SetProperty(), and v8::internal::value.
SetPropertyWithAccessor()
Maybe< bool > v8::internal::Object::SetPropertyWithAccessor (LookupIterator * it, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw) [static]
Definition at line 1582 of file objects.cc.
                                           {
  Isolate* isolate = it->isolate();
  DirectHandle<Object> structure = it->GetAccessors();
  DirectHandle<JSAny> receiver = it->GetReceiver();
  // In case of global IC, the receiver is the global object. Replace by the
  // global proxy.
  if (IsJSGlobalObject(*receiver)) {
    receiver =
        direct_handle(Cast<JSGlobalObject>(*receiver)->global_proxy(), isolate);
  }
  // We should never get here to initialize a const with the hole value since a
  // const declaration would conflict with the setter.
  DCHECK(!IsForeign(*structure));
  // API style callbacks.
  DirectHandle<JSObject> holder = it->GetHolder<JSObject>();
  if (IsAccessorInfo(*structure)) {
    DirectHandle<Name> name = it->GetName();
    auto info = Cast<AccessorInfo>(structure);
    if (!info->has_setter(isolate)) {
      // TODO(verwaest): We should not get here anymore once all AccessorInfos
      // are marked as special_data_property. They cannot both be writable and
      // not have a setter.
      return Just(true);
    }
    if (info->is_sloppy() && !IsJSReceiver(*receiver)) {
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(
          isolate, receiver, Object::ConvertReceiver(isolate, receiver),
          Nothing<bool>());
    }
    PropertyCallbackArguments args(isolate, info->data(), *receiver, *holder,
                                   maybe_should_throw);
    bool result = args.CallAccessorSetter(info, name, value);
    RETURN_VALUE_IF_EXCEPTION(isolate, Nothing<bool>());
    // Ensure the setter callback respects the "should throw" value - it's
    // allowed to fail without throwing only in case of kDontThrow.
    DCHECK_IMPLIES(!result,
                   GetShouldThrow(isolate, maybe_should_throw) == kDontThrow);
    return Just(result);
  }
  // Regular accessor.
  DirectHandle<Object> setter(Cast<AccessorPair>(*structure)->setter(),
                              isolate);
  if (IsFunctionTemplateInfo(*setter)) {
    SaveAndSwitchContext save(isolate, holder->GetCreationContext().value());
    DirectHandle<Object> args[] = {value};
    RETURN_ON_EXCEPTION_VALUE(
        isolate,
        Builtins::InvokeApiFunction(
            isolate, false, Cast<FunctionTemplateInfo>(setter), receiver,
            base::VectorOf(args), isolate->factory()->undefined_value()),
        Nothing<bool>());
    return Just(true);
  } else if (IsCallable(*setter)) {
    // TODO(rossberg): nicer would be to cast to some JSCallable here...
    return SetPropertyWithDefinedSetter(receiver, Cast<JSReceiver>(setter),
                                        value, maybe_should_throw);
  }
  RETURN_FAILURE(isolate, GetShouldThrow(isolate, maybe_should_throw),
                 NewTypeError(MessageTemplate::kNoSetterInCallback,
                              it->GetName(), it->GetHolder<JSObject>()));
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION_VALUE, ConvertReceiver(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::LookupIterator::GetAccessors(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetName(), v8::internal::LookupIterator::GetReceiver(), v8::internal::GetShouldThrow(), v8::internal::Builtins::InvokeApiFunction(), v8::internal::LookupIterator::isolate(), v8::Just(), v8::internal::kDontThrow, v8::internal::name, v8::base::internal::result, RETURN_FAILURE, RETURN_ON_EXCEPTION_VALUE, RETURN_VALUE_IF_EXCEPTION, SetPropertyWithDefinedSetter(), v8::internal::setter, v8::internal::value, and v8::base::VectorOf().
Referenced by v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), SetPropertyInternal(), and SetSuperProperty().
SetPropertyWithDefinedSetter()
Maybe< bool > v8::internal::Object::SetPropertyWithDefinedSetter (DirectHandle< JSAny > receiver, DirectHandle< JSReceiver > setter, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw) [static]
Definition at line 1674 of file objects.cc.
                                                                 {
  Isolate* isolate = Isolate::Current();
  DirectHandle<Object> args[] = {value};
  RETURN_ON_EXCEPTION_VALUE(
      isolate, Execution::Call(isolate, setter, receiver, base::VectorOf(args)),
      Nothing<bool>());
  return Just(true);
}
References v8::base::args, v8::internal::Execution::Call(), v8::internal::Isolate::Current(), v8::Just(), RETURN_ON_EXCEPTION_VALUE, v8::internal::setter, v8::internal::value, and v8::base::VectorOf().
Referenced by SetPropertyWithAccessor().
SetSuperProperty()
Maybe< bool > v8::internal::Object::SetSuperProperty (LookupIterator * it, DirectHandle< Object > value, StoreOrigin store_origin, Maybe< ShouldThrow > should_throw = Nothing<ShouldThrow>()) [static]
Definition at line 2476 of file objects.cc.
                                                                      {
  Isolate* isolate = it->isolate();
  if (it->IsFound()) {
    bool found = true;
    Maybe<bool> result =
        SetPropertyInternal(it, value, should_throw, store_origin, &found);
    if (found) return result;
  }
  it->UpdateProtector();
  // The property either doesn't exist on the holder or exists there as a data
  // property.
  if (!IsJSReceiver(*it->GetReceiver())) {
    return WriteToReadOnlyProperty(it, value, should_throw);
  }
  DirectHandle<JSReceiver> receiver = Cast<JSReceiver>(it->GetReceiver());
  // Note, the callers rely on the fact that this code is redoing the full own
  // lookup from scratch.
  LookupIterator own_lookup(isolate, receiver, it->GetKey(),
                            LookupIterator::OWN);
  for (;; own_lookup.Next()) {
    switch (own_lookup.state()) {
      case LookupIterator::ACCESS_CHECK:
        if (!own_lookup.HasAccess()) {
          return JSObject::SetPropertyWithFailedAccessCheck(&own_lookup, value,
                                                            should_throw);
        }
        continue;
      case LookupIterator::ACCESSOR:
        if (IsAccessorInfo(*own_lookup.GetAccessors())) {
          if (own_lookup.IsReadOnly()) {
            return WriteToReadOnlyProperty(&own_lookup, value, should_throw);
          }
          return Object::SetPropertyWithAccessor(&own_lookup, value,
                                                 should_throw);
        }
        [[fallthrough]];
      case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
        return RedefineIncompatibleProperty(isolate, it->GetName(), value,
                                            should_throw);
      case LookupIterator::STRING_LOOKUP_START_OBJECT:
        UNREACHABLE();
      case LookupIterator::DATA: {
        if (own_lookup.IsReadOnly()) {
          return WriteToReadOnlyProperty(&own_lookup, value, should_throw);
        }
        return SetDataProperty(&own_lookup, value);
      }
      case LookupIterator::INTERCEPTOR:
      case LookupIterator::JSPROXY: {
        PropertyDescriptor desc;
        Maybe<bool> owned =
            JSReceiver::GetOwnPropertyDescriptor(&own_lookup, &desc);
        MAYBE_RETURN(owned, Nothing<bool>());
        if (!owned.FromJust()) {
          // |own_lookup| might become outdated at this point anyway.
          // TODO(leszeks): Remove this restart since we don't really use the
          // lookup iterator after this.
          own_lookup.Restart();
          if (!CheckContextualStoreToJSGlobalObject(&own_lookup,
                                                    should_throw)) {
            return Nothing<bool>();
          }
          return JSReceiver::CreateDataProperty(isolate, receiver, it->GetKey(),
                                                value, should_throw);
        }
        if (PropertyDescriptor::IsAccessorDescriptor(&desc) ||
            !desc.writable()) {
          return RedefineIncompatibleProperty(isolate, it->GetName(), value,
                                              should_throw);
        }
        PropertyDescriptor value_desc;
        value_desc.set_value(Cast<JSAny>(value));
        return JSReceiver::DefineOwnProperty(isolate, receiver, it->GetName(),
                                             &value_desc, should_throw);
      }
      case LookupIterator::NOT_FOUND:
        if (!CheckContextualStoreToJSGlobalObject(&own_lookup, should_throw)) {
          return Nothing<bool>();
        }
        return AddDataProperty(&own_lookup, value, NONE, should_throw,
                               store_origin);
      case LookupIterator::WASM_OBJECT:
        RETURN_FAILURE(it->isolate(), kThrowOnError,
                       NewTypeError(MessageTemplate::kWasmObjectsAreOpaque));
      case LookupIterator::TRANSITION:
        UNREACHABLE();
    }
    UNREACHABLE();
  }
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, AddDataProperty(), CheckContextualStoreToJSGlobalObject(), v8::internal::JSReceiver::CreateDataProperty(), v8::internal::LookupIterator::DATA, v8::internal::JSReceiver::DefineOwnProperty(), v8::Maybe< T >::FromJust(), v8::internal::LookupIterator::GetAccessors(), v8::internal::LookupIterator::GetKey(), v8::internal::LookupIterator::GetName(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::LookupIterator::GetReceiver(), v8::internal::LookupIterator::HasAccess(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::PropertyDescriptor::IsAccessorDescriptor(), v8::internal::LookupIterator::IsFound(), v8::internal::LookupIterator::isolate(), v8::internal::LookupIterator::IsReadOnly(), v8::internal::LookupIterator::JSPROXY, v8::internal::kThrowOnError, MAYBE_RETURN, v8::internal::LookupIterator::Next(), v8::internal::NONE, v8::internal::LookupIterator::NOT_FOUND, v8::internal::LookupIterator::OWN, RedefineIncompatibleProperty(), v8::internal::LookupIterator::Restart(), v8::base::internal::result, RETURN_FAILURE, v8::internal::PropertyDescriptor::set_value(), SetDataProperty(), SetPropertyInternal(), SetPropertyWithAccessor(), v8::internal::JSObject::SetPropertyWithFailedAccessCheck(), v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), v8::internal::LookupIterator::UpdateProtector(), v8::internal::value, v8::internal::LookupIterator::WASM_OBJECT, v8::internal::PropertyDescriptor::writable(), and WriteToReadOnlyProperty().
Referenced by v8::internal::BUILTIN(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JSProxy::SetProperty(), SetPropertyInternal(), and v8::internal::anonymous_namespace{runtime-classes.cc}::StoreToSuper().
SpeciesConstructor()
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > v8::internal::Object::SpeciesConstructor (Isolate * isolate, DirectHandle< JSReceiver > recv, DirectHandle< JSFunction > default_ctor) [static]
Definition at line 1795 of file objects.cc.
                                           {
  DirectHandle<Object> ctor_obj;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, ctor_obj,
      JSObject::GetProperty(isolate, recv,
                            isolate->factory()->constructor_string()));
  if (IsUndefined(*ctor_obj, isolate)) return default_ctor;
  if (!IsJSReceiver(*ctor_obj)) {
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kConstructorNotReceiver));
  }
  DirectHandle<JSReceiver> ctor = Cast<JSReceiver>(ctor_obj);
  DirectHandle<Object> species;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, species,
      JSObject::GetProperty(isolate, ctor,
                            isolate->factory()->species_symbol()));
  if (IsNullOrUndefined(*species, isolate)) {
    return default_ctor;
  }
  if (IsConstructor(*species)) return species;
  THROW_NEW_ERROR(isolate,
                  NewTypeError(MessageTemplate::kSpeciesNotConstructor));
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::factory(), v8::internal::IsNullOrUndefined(), and THROW_NEW_ERROR.
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::SliceHelper().
StrictEquals()
bool v8::internal::Object::StrictEquals (Tagged< Object > obj, Tagged< Object > that) [static]
Definition at line 988 of file objects.cc.
                                                                 {
  if (IsNumber(obj)) {
    if (!IsNumber(that)) return false;
    return StrictNumberEquals(Cast<Number>(obj), Cast<Number>(that));
  } else if (IsString(obj)) {
    if (!IsString(that)) return false;
    return Cast<String>(obj)->Equals(Cast<String>(that));
  } else if (IsBigInt(obj)) {
    if (!IsBigInt(that)) return false;
    return BigInt::EqualToBigInt(Cast<BigInt>(obj), Cast<BigInt>(that));
  }
  return obj == that;
}
References v8::internal::BigInt::EqualToBigInt(), v8::internal::IsNumber(), and v8::internal::anonymous_namespace{objects.cc}::StrictNumberEquals().
Referenced by v8::internal::JSArrayBuffer::Detach(), v8::internal::BackgroundCompileTask::FinalizeScript(), v8::internal::CodeSerializer::FinishOffThreadDeserialize(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IndexOfValueImpl(), v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::IndexOfValueImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IndexOfValueImpl(), v8::internal::anonymous_namespace{elements.cc}::IndexOfValueSlowPath(), v8::internal::ScriptCacheKey::MatchesScript(), v8::internal::RUNTIME_FUNCTION(), and v8::Value::StrictEquals().
ToArrayIndex()
bool v8::internal::Object::ToArrayIndex (Tagged< Object > obj, uint32_t * index) [inline], [static]
Definition at line 1683 of file objects-inl.h.
                                                             {
  return Object::ToUint32(obj, index) && *index != kMaxUInt32;
}
References v8::internal::index, v8::internal::kMaxUInt32, and ToUint32().
Referenced by v8::internal::OrderedHashSet::ConvertToKeysArray(), v8::internal::anonymous_namespace{runtime-literals.cc}::CreateObjectLiteral(), v8::Object::Has(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::IncludesValueFastPath(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::SetLengthImpl(), v8::internal::anonymous_namespace{elements.cc}::FastNonextensibleObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl(), and v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl().
ToArrayLength()
bool v8::internal::Object::ToArrayLength (Tagged< Object > obj, uint32_t * index) [inline], [static]
Definition at line 1678 of file objects-inl.h.
                                                              {
  return Object::ToUint32(obj, index);
}
References v8::internal::index, and ToUint32().
Referenced by v8::internal::JSObject::AddDataElement(), v8::internal::JSArray::AnythingToArrayLength(), v8::internal::ArrayConstructInitializeElements(), v8::internal::JSArray::ArraySetLength(), v8::internal::ElementsAccessor::Concat(), v8::internal::JSArray::DefineOwnProperty(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::DeleteCommon(), v8::internal::AllocationSite::DigestTransitionFeedback(), v8::internal::anonymous_namespace{builtins-array.cc}::GetLengthProperty(), v8::internal::compiler::JSObjectRef::GetOwnConstantElementFromHeap(), v8::internal::PropertyKeyToArrayLength(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JsonStringifier::SerializeJSArray(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::SetLengthImpl(), v8::internal::JSArray::WouldChangeReadOnlyLength(), and v8::internal::ValueSerializer::WriteJSArray().
ToBoolean()
Tagged< Object > v8::internal::Object::ToBoolean (Tagged< Object > obj, Isolate * isolate) [static]
Definition at line 793 of file objects.cc.
                                                                     {
  if (IsBoolean(obj)) return obj;
  return isolate->heap()->ToBoolean(Object::BooleanValue(obj, isolate));
}
References BooleanValue(), v8::internal::Isolate::heap(), and v8::internal::Heap::ToBoolean().
Referenced by v8::internal::RUNTIME_FUNCTION().
ToInt32()
bool v8::internal::Object::ToInt32 (Tagged< Object > obj, int32_t * value) [static]
Definition at line 1442 of file objects.cc.
                                                       {
  if (IsSmi(obj)) {
    *value = Smi::ToInt(obj);
    return true;
  }
  if (IsHeapNumber(obj)) {
    double num = Cast<HeapNumber>(obj)->value();
    // Check range before conversion to avoid undefined behavior.
    if (num >= kMinInt && num <= kMaxInt && FastI2D(FastD2I(num)) == num) {
      *value = FastD2I(num);
      return true;
    }
  }
  return false;
}
References v8::internal::FastD2I(), v8::internal::FastI2D(), v8::internal::IsSmi(), v8::internal::kMaxInt, v8::internal::kMinInt, v8::internal::Smi::ToInt(), and v8::internal::value.
Referenced by v8::internal::DoWait(), v8::internal::KeyAccumulator::FilterForEnumerableProperties(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyAttributesWithInterceptorInternal(), v8::Value::Int32Value(), v8::internal::wasm::InstanceBuilder::ProcessImportedGlobal(), v8::internal::RUNTIME_FUNCTION(), v8::Value::ToInt32(), and v8::internal::anonymous_namespace{objects.cc}::WriteFixedArrayToFlat().
ToIntegerIndex()
bool v8::internal::Object::ToIntegerIndex (Tagged< Object > obj, size_t * index) [inline], [static]
Definition at line 1688 of file objects-inl.h.
                                                             {
  if (IsSmi(obj)) {
    int num = Smi::ToInt(obj);
    if (num < 0) return false;
    *index = static_cast<size_t>(num);
    return true;
  }
  if (IsHeapNumber(obj)) {
    double num = Cast<HeapNumber>(obj)->value();
    if (!(num >= 0)) return false; // Negation to catch NaNs.
    constexpr double max =
        std::min(kMaxSafeInteger,
                 // The maximum size_t is reserved as "invalid" sentinel.
                 static_cast<double>(std::numeric_limits<size_t>::max() - 1));
    if (num > max) return false;
    size_t result = static_cast<size_t>(num);
    if (num != result) return false; // Conversion lost fractional precision.
    *index = result;
    return true;
  }
  return false;
}
References v8::internal::index, v8::internal::IsSmi(), v8::internal::kMaxSafeInteger, v8::base::internal::result, and v8::internal::Smi::ToInt().
Referenced by v8::internal::RUNTIME_FUNCTION().
ToLength()
template<typename T , template< typename > typename HandleType>
MaybeHandle< Object > v8::internal::Object::ToLength (Isolate * isolate, DirectHandle< Object > input) [inline], [static]
Definition at line 906 of file objects-inl.h.
                                                                 {
  if (IsSmi(*input)) {
    int value = std::max(Smi::ToInt(*input), 0);
    return handle(Smi::FromInt(value), isolate);
  }
  return ConvertToLength(isolate, input);
}
References ConvertToLength(), v8::internal::Smi::FromInt(), v8::internal::handle(), input, v8::internal::IsSmi(), v8::internal::Smi::ToInt(), and v8::internal::value.
Referenced by v8::internal::BUILTIN(), GetLengthFromArrayLike(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpReplace(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::RegExpUtils::SetAdvancedStringIndex().
ToObjectImpl()
template<typename T , template< typename > typename HandleType>
MaybeHandle< JSReceiver > v8::internal::Object::ToObjectImpl (Isolate * isolate, DirectHandle< Object > object, const char * method_name = nullptr) [static]
Definition at line 273 of file objects.cc.
                                                                      {
  DCHECK(!IsJSReceiver(*object)); // Use ToObject() for fast path.
  DirectHandle<Context> native_context = isolate->native_context();
  DirectHandle<JSFunction> constructor;
  if (IsSmi(*object)) {
    constructor = direct_handle(native_context->number_function(), isolate);
  } else {
    int constructor_function_index =
        Cast<HeapObject>(object)->map()->GetConstructorFunctionIndex();
    if (constructor_function_index == Map::kNoConstructorFunctionIndex) {
      if (method_name != nullptr) {
        THROW_NEW_ERROR(
            isolate, NewTypeError(MessageTemplate::kCalledOnNullOrUndefined,
                                  isolate->factory()->NewStringFromAsciiChecked(
                                      method_name)));
      }
      THROW_NEW_ERROR(isolate,
                      NewTypeError(MessageTemplate::kUndefinedOrNullToObject));
    }
    constructor = direct_handle(
        Cast<JSFunction>(native_context->GetNoCell(constructor_function_index)),
        isolate);
  }
  Handle<JSObject> result = isolate->factory()->NewJSObject(constructor);
  Cast<JSPrimitiveWrapper>(result)->set_value(Cast<JSAny>(*object));
  return result;
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::IsSmi(), v8::internal::Map::kNoConstructorFunctionIndex, v8::internal::Isolate::native_context(), v8::internal::native_context, v8::internal::Factory::NewJSObject(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::base::internal::result, and THROW_NEW_ERROR.
Referenced by NoSideEffectsToString().
ToUint32()
bool v8::internal::Object::ToUint32 (Tagged< Object > obj, uint32_t * value) [inline], [static]
Definition at line 797 of file objects-inl.h.
                                                         {
  if (IsSmi(obj)) {
    int num = Smi::ToInt(obj);
    if (num < 0) return false;
    *value = static_cast<uint32_t>(num);
    return true;
  }
  if (IsHeapNumber(obj)) {
    double num = Cast<HeapNumber>(obj)->value();
    return DoubleToUint32IfEqualToSelf(num, value);
  }
  return false;
}
References v8::internal::DoubleToUint32IfEqualToSelf(), v8::internal::IsSmi(), v8::internal::Smi::ToInt(), and v8::internal::value.
Referenced by v8::internal::JSArray::AnythingToArrayLength(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectValuesOrEntriesImpl(), CreateListFromArrayLike(), v8::internal::anonymous_namespace{objects.cc}::CreateListFromArrayLikeFastPath(), v8::internal::KeyAccumulator::FilterForEnumerableProperties(), v8::internal::JsonStringifier::InitializeReplacer(), v8::internal::anonymous_namespace{builtins-array.cc}::IterateElements(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JsonStringifier::SerializeJSProxy(), ToArrayIndex(), ToArrayLength(), v8::Value::ToUint32(), and v8::Value::Uint32Value().
TransitionAndWriteDataProperty()
Maybe< bool > v8::internal::Object::TransitionAndWriteDataProperty (LookupIterator * it, DirectHandle< Object > value, PropertyAttributes attributes, Maybe< ShouldThrow > should_throw, StoreOrigin store_origin) [static]
Definition at line 2767 of file objects.cc.
                              {
  DirectHandle<JSReceiver> receiver = it->GetStoreTarget<JSReceiver>();
  it->UpdateProtector();
  // Migrate to the most up-to-date map that will be able to store |value|
  // under it->name() with |attributes|.
  it->PrepareTransitionToDataProperty(receiver, value, attributes,
                                      store_origin);
  DCHECK_EQ(LookupIterator::TRANSITION, it->state());
  it->ApplyTransitionToDataProperty(receiver);
  // Write the property value.
  it->WriteDataValue(value, true);
#if VERIFY_HEAP
  if (v8_flags.verify_heap) {
    receiver->HeapObjectVerify(it->isolate());
  }
#endif
  return Just(true);
}
References v8::internal::LookupIterator::ApplyTransitionToDataProperty(), DCHECK_EQ, v8::internal::LookupIterator::GetStoreTarget(), v8::internal::LookupIterator::isolate(), v8::Just(), v8::internal::LookupIterator::PrepareTransitionToDataProperty(), v8::internal::LookupIterator::state(), v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::UpdateProtector(), v8::internal::v8_flags, v8::internal::value, and v8::internal::LookupIterator::WriteDataValue().
Referenced by AddDataProperty(), and v8::internal::JSReceiver::AddPrivateField().
TypeOf()
Handle< String > v8::internal::Object::TypeOf (Isolate * isolate, DirectHandle< Object > object) [static]
Definition at line 1003 of file objects.cc.
                                                                           {
  if (IsNumber(*object)) return isolate->factory()->number_string();
  if (IsOddball(*object))
    return handle(Cast<Oddball>(*object)->type_of(), isolate);
  if (IsUndetectable(*object)) {
    return isolate->factory()->undefined_string();
  }
  if (IsString(*object)) return isolate->factory()->string_string();
  if (IsSymbol(*object)) return isolate->factory()->symbol_string();
  if (IsBigInt(*object)) return isolate->factory()->bigint_string();
  if (IsCallable(*object)) return isolate->factory()->function_string();
  return isolate->factory()->object_string();
}
References v8::internal::Isolate::factory(), v8::internal::handle(), and v8::internal::IsNumber().
Referenced by AddDataProperty(), v8::internal::anonymous_namespace{messages.cc}::BuildDefaultCallSite(), v8::internal::BUILTIN(), CannotCreateProperty(), v8::internal::RUNTIME_FUNCTION(), v8::Value::TypeOf(), and WriteToReadOnlyProperty().
WrapForRead()
template<AllocationType allocation_type, typename IsolateT >
Handle< JSAny > v8::internal::Object::WrapForRead (IsolateT * isolate, Handle< JSAny > object, Representation representation) [static]
Definition at line 257 of file objects.cc.
                                                                 {
  DCHECK(!IsUninitialized(*object, isolate));
  if (!representation.IsDouble()) {
    DCHECK(Object::FitsRepresentation(*object, representation));
    return object;
  }
  return isolate->factory()->template NewHeapNumberFromBits<allocation_type>(
      Cast<HeapNumber>(*object)->value_as_bits());
}
References v8::internal::DCHECK(), FitsRepresentation(), and v8::internal::Representation::IsDouble().
Referenced by v8::internal::JSObject::FastPropertyAt(), and v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast().
WriteToReadOnlyProperty() [1/2]
Maybe< bool > v8::internal::Object::WriteToReadOnlyProperty (Isolate * isolate, DirectHandle< JSAny > receiver, DirectHandle< Object > name, DirectHandle< Object > value, ShouldThrow should_throw) [static]
Definition at line 2613 of file objects.cc.
                                                                      {
  RETURN_FAILURE(isolate, should_throw,
                 NewTypeError(MessageTemplate::kStrictReadOnlyProperty, name,
                              Object::TypeOf(isolate, receiver), receiver));
}
References v8::internal::name, RETURN_FAILURE, and TypeOf().
WriteToReadOnlyProperty() [2/2]
Maybe< bool > v8::internal::Object::WriteToReadOnlyProperty (LookupIterator * it, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw) [static]
Definition at line 2594 of file objects.cc.
                                           {
  ShouldThrow should_throw = GetShouldThrow(it->isolate(), maybe_should_throw);
  if (it->IsFound() &&
      it->state() != LookupIterator::STRING_LOOKUP_START_OBJECT &&
      !it->HolderIsReceiver()) {
    // "Override mistake" attempted, record a use count to track this per
    // v8:8175
    v8::Isolate::UseCounterFeature feature =
        should_throw == kThrowOnError
            ? v8::Isolate::kAttemptOverrideReadOnlyOnPrototypeStrict
            : v8::Isolate::kAttemptOverrideReadOnlyOnPrototypeSloppy;
    it->isolate()->CountUsage(feature);
  }
  return WriteToReadOnlyProperty(it->isolate(), it->GetReceiver(),
                                 it->GetName(), value, should_throw);
}
References v8::internal::Isolate::CountUsage(), v8::internal::LookupIterator::GetName(), v8::internal::LookupIterator::GetReceiver(), v8::internal::GetShouldThrow(), v8::internal::LookupIterator::HolderIsReceiver(), v8::internal::LookupIterator::IsFound(), v8::internal::LookupIterator::isolate(), v8::Isolate::kAttemptOverrideReadOnlyOnPrototypeSloppy, v8::Isolate::kAttemptOverrideReadOnlyOnPrototypeStrict, v8::internal::kThrowOnError, v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{runtime-atomics.cc}::AtomicFieldWrite(), SetPropertyInternal(), and SetSuperProperty().
Friends And Related Function Documentation
CompressedObjectSlot
friend class CompressedObjectSlot [friend]
Definition at line 566 of file objects.h.
FullObjectSlot
friend class FullObjectSlot [friend]
Definition at line 567 of file objects.h.
LookupIterator
friend class LookupIterator [friend]
Definition at line 568 of file objects.h.
StringStream
friend class StringStream [friend]
Definition at line 569 of file objects.h.
Member Data Documentation
input
HandleType<T> v8::internal::Object::input
Definition at line 152 of file objects.h.
Referenced by ConvertToLength(), NoSideEffectsToMaybeString(), NoSideEffectsToString(), and ToLength().
kHeaderSize
const int v8::internal::Object::kHeaderSize = 0 [static]
Definition at line 505 of file objects.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/objects.h
/mnt/V8SourceCode/src/objects/objects-inl.h
/mnt/V8SourceCode/src/objects/objects.cc