v8::internal::PagedNewSpaceAllocatorPolicy Class Reference
#include <main-allocator.h>
Public Member Functions
PagedNewSpaceAllocatorPolicy (PagedNewSpace *space, MainAllocator *allocator)
bool EnsureAllocation (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin) final
void FreeLinearAllocationArea () final
bool SupportsExtendingLAB () const final
Private Member Functions
bool TryAllocatePage (int size_in_bytes, AllocationOrigin origin)
bool WaitForSweepingForAllocation (int size_in_bytes, AllocationOrigin origin)
Private Attributes
PagedNewSpace *const space_
std::unique_ptr< PagedSpaceAllocatorPolicy > paged_space_allocator_policy_
Additional Inherited Members
Detailed Description
Definition at line 101 of file main-allocator.h.
Constructor & Destructor Documentation
PagedNewSpaceAllocatorPolicy()
v8::internal::PagedNewSpaceAllocatorPolicy::PagedNewSpaceAllocatorPolicy (PagedNewSpace * space, MainAllocator * allocator)
Definition at line 531 of file main-allocator.cc.
    : AllocatorPolicy(allocator),
      space_(space),
      paged_space_allocator_policy_(
          new PagedSpaceAllocatorPolicy(space->paged_space(), allocator)) {}
Member Function Documentation
EnsureAllocation()
bool v8::internal::PagedNewSpaceAllocatorPolicy::EnsureAllocation (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin) [final], [virtual]
Implements v8::internal::AllocatorPolicy.
Definition at line 538 of file main-allocator.cc.
                                                                               {
  if (space_->paged_space()->last_lab_page_) {
    space_->paged_space()->last_lab_page_->DecreaseAllocatedLabSize(
        allocator_->limit() - allocator_->top());
    allocator_->ExtendLAB(allocator_->top());
    // No need to write a filler to the remaining lab because it will either be
    // reallocated if the lab can be extended or freed otherwise.
  }
  if (!paged_space_allocator_policy_->EnsureAllocation(size_in_bytes, alignment,
                                                       origin)) {
    if (!TryAllocatePage(size_in_bytes, origin)) {
      if (!WaitForSweepingForAllocation(size_in_bytes, origin)) {
        return false;
      }
    }
  }
  space_->paged_space()->last_lab_page_ =
      PageMetadata::FromAllocationAreaAddress(allocator_->top());
  DCHECK_NOT_NULL(space_->paged_space()->last_lab_page_);
  space_->paged_space()->last_lab_page_->IncreaseAllocatedLabSize(
      allocator_->limit() - allocator_->top());
  if (space_heap()->incremental_marking()->IsMinorMarking()) {
    space_heap()->concurrent_marking()->RescheduleJobIfNeeded(
        GarbageCollector::MINOR_MARK_SWEEPER);
  }
  return true;
}
References v8::internal::AllocatorPolicy::allocator_, v8::internal::Heap::concurrent_marking(), DCHECK_NOT_NULL, v8::internal::MutablePageMetadata::DecreaseAllocatedLabSize(), v8::internal::MainAllocator::ExtendLAB(), v8::internal::PageMetadata::FromAllocationAreaAddress(), v8::internal::MutablePageMetadata::IncreaseAllocatedLabSize(), v8::internal::PagedSpaceForNewSpace::last_lab_page_, v8::internal::MainAllocator::limit(), v8::internal::MINOR_MARK_SWEEPER, v8::internal::PagedNewSpace::paged_space(), paged_space_allocator_policy_, v8::internal::ConcurrentMarking::RescheduleJobIfNeeded(), space_, v8::internal::AllocatorPolicy::space_heap(), v8::internal::MainAllocator::top(), TryAllocatePage(), and WaitForSweepingForAllocation().
FreeLinearAllocationArea()
void v8::internal::PagedNewSpaceAllocatorPolicy::FreeLinearAllocationArea () [final], [virtual]
Implements v8::internal::AllocatorPolicy.
Definition at line 630 of file main-allocator.cc.
                                                            {
  if (!allocator_->IsLabValid()) return;
  PageMetadata::FromAllocationAreaAddress(allocator_->top())
      ->DecreaseAllocatedLabSize(allocator_->limit() - allocator_->top());
  paged_space_allocator_policy_->FreeLinearAllocationAreaUnsynchronized();
}
References v8::internal::AllocatorPolicy::allocator_, v8::internal::MutablePageMetadata::DecreaseAllocatedLabSize(), v8::internal::PageMetadata::FromAllocationAreaAddress(), v8::internal::MainAllocator::IsLabValid(), v8::internal::MainAllocator::limit(), paged_space_allocator_policy_, and v8::internal::MainAllocator::top().
SupportsExtendingLAB()
bool v8::internal::PagedNewSpaceAllocatorPolicy::SupportsExtendingLAB () const [inline], [final], [virtual]
Reimplemented from v8::internal::AllocatorPolicy.
Definition at line 109 of file main-allocator.h.
{ return true; }
TryAllocatePage()
bool v8::internal::PagedNewSpaceAllocatorPolicy::TryAllocatePage (int size_in_bytes, AllocationOrigin origin) [private]
Definition at line 619 of file main-allocator.cc.
                                                                            {
  if (IsPagedNewSpaceAtFullCapacity(space_) &&
      !space_->heap()->ShouldExpandYoungGenerationOnSlowAllocation(
          PageMetadata::kPageSize))
    return false;
  if (!space_->paged_space()->AllocatePage()) return false;
  return paged_space_allocator_policy_->TryAllocationFromFreeList(size_in_bytes,
                                                                  origin);
}
References v8::internal::PagedSpaceForNewSpace::AllocatePage(), v8::internal::anonymous_namespace{main-allocator.cc}::IsPagedNewSpaceAtFullCapacity(), v8::internal::MutablePageMetadata::kPageSize, v8::internal::PagedNewSpace::paged_space(), paged_space_allocator_policy_, and space_.
Referenced by EnsureAllocation().
WaitForSweepingForAllocation()
bool v8::internal::PagedNewSpaceAllocatorPolicy::WaitForSweepingForAllocation (int size_in_bytes, AllocationOrigin origin) [private]
Definition at line 571 of file main-allocator.cc.
                                                {
  // This method should be called only when there are no more pages for main
  // thread to sweep.
  DCHECK(space_heap()->sweeper()->IsSweepingDoneForSpace(NEW_SPACE));
  if (!v8_flags.concurrent_sweeping || !space_heap()->sweeping_in_progress())
    return false;
  Sweeper* sweeper = space_heap()->sweeper();
  if (!sweeper->AreMinorSweeperTasksRunning() &&
      !sweeper->ShouldRefillFreelistForSpace(NEW_SPACE)) {
#if DEBUG
    for (PageMetadata* p : *space_) {
      DCHECK(p->SweepingDone());
      p->ForAllFreeListCategories(
          [space = space_->paged_space()](FreeListCategory* category) {
            DCHECK_IMPLIES(!category->is_empty(),
                           category->is_linked(space->free_list()));
          });
    }
#endif // DEBUG
    // All pages are already swept and relinked to the free list
    return false;
  }
  // When getting here we know that any unswept new space page is currently
  // being handled by a concurrent sweeping thread. Rather than try to cancel
  // tasks and restart them, we wait "per page". This should be faster.
  for (PageMetadata* p : *space_) {
    if (!p->SweepingDone()) sweeper->WaitForPageToBeSwept(p);
  }
  space_->paged_space()->RefillFreeList();
  DCHECK(!sweeper->ShouldRefillFreelistForSpace(NEW_SPACE));
  return paged_space_allocator_policy_->TryAllocationFromFreeList(
      static_cast<size_t>(size_in_bytes), origin);
}
References v8::internal::Sweeper::AreMinorSweeperTasksRunning(), v8::internal::DCHECK(), v8::internal::NEW_SPACE, v8::internal::PagedNewSpace::paged_space(), paged_space_allocator_policy_, v8::internal::PagedSpaceBase::RefillFreeList(), v8::internal::Sweeper::ShouldRefillFreelistForSpace(), space, space_, v8::internal::AllocatorPolicy::space_heap(), v8::internal::Heap::sweeper(), v8::internal::v8_flags, and v8::internal::Sweeper::WaitForPageToBeSwept().
Referenced by EnsureAllocation().
Member Data Documentation
paged_space_allocator_policy_
std::unique_ptr<PagedSpaceAllocatorPolicy> v8::internal::PagedNewSpaceAllocatorPolicy::paged_space_allocator_policy_ [private]
Definition at line 116 of file main-allocator.h.
Referenced by EnsureAllocation(), FreeLinearAllocationArea(), TryAllocatePage(), and WaitForSweepingForAllocation().
space_
PagedNewSpace* const v8::internal::PagedNewSpaceAllocatorPolicy::space_ [private]
Definition at line 115 of file main-allocator.h.
Referenced by EnsureAllocation(), TryAllocatePage(), and WaitForSweepingForAllocation().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/main-allocator.h
/mnt/V8SourceCode/src/heap/main-allocator.cc