v8::internal::String::FlatContent Class Reference
#include <string.h>
Public Member Functions
~FlatContent ()
bool IsFlat () const
bool IsOneByte () const
bool IsTwoByte () const
base::Vector< const uint8_t > ToOneByteVector () const
base::Vector< const base::uc16 > ToUC16Vector () const
base::uc16 Get (uint32_t i) const
bool UsesSameString (const FlatContent &other) const
void UnsafeDisableChecksumVerification ()
uint32_t length () const
Private Types
enum State { NON_FLAT
, ONE_BYTE
, TWO_BYTE
 }
Private Member Functions
FlatContent (const uint8_t *start, uint32_t length, const DisallowGarbageCollection &no_gc)
FlatContent (const base::uc16 *start, uint32_t length, const DisallowGarbageCollection &no_gc)
FlatContent (const DisallowGarbageCollection &no_gc)
Private Attributes
xx xx xx xx xx xx xx xx xx
union {
 const uint8_t * onebyte_start
 const base::uc16 * twobyte_start
};
uint32_t length_
State state_
const DisallowGarbageCollection & no_gc_
Static Private Attributes
static constexpr uint32_t kChecksumVerificationDisabled = 0
Friends
class String
class IterableSubString
Detailed Description
Definition at line 131 of file string.h.
Member Enumeration Documentation
State
enum v8::internal::String::FlatContent::State [private]
Enumerator
NON_FLAT
ONE_BYTE
TWO_BYTE
Definition at line 180 of file string.h.
{ NON_FLAT, ONE_BYTE, TWO_BYTE };
Constructor & Destructor Documentation
 FlatContent()
v8::internal::String::FlatContent::~FlatContent () [inline]
Definition at line 1040 of file string-inl.h.
                                {
  // When ENABLE_SLOW_DCHECKS, check the string contents did not change during
  // the lifetime of the FlatContent. To avoid extra memory use, only the hash
  // is checked instead of snapshotting the full character data.
  //
  // If you crashed here, it means something changed the character data of this
  // FlatContent during its lifetime (e.g. GC relocated the string). This is
  // almost always a bug. If you are certain it is not a bug, you can disable
  // the checksum verification in the caller by calling
  // UnsafeDisableChecksumVerification().
  SLOW_DCHECK(checksum_ == kChecksumVerificationDisabled ||
              checksum_ == ComputeChecksum());
}
References SLOW_DCHECK.
FlatContent() [1/3]
v8::internal::String::FlatContent::FlatContent (const uint8_t * start, uint32_t length, const DisallowGarbageCollection & no_gc) [inline], [private]
Definition at line 1024 of file string-inl.h.
    : onebyte_start(start), length_(length), state_(ONE_BYTE), no_gc_(no_gc) {
#ifdef ENABLE_SLOW_DCHECKS
  checksum_ = ComputeChecksum();
#endif
}
FlatContent() [2/3]
v8::internal::String::FlatContent::FlatContent (const base::uc16 * start, uint32_t length, const DisallowGarbageCollection & no_gc) [inline], [private]
Definition at line 1032 of file string-inl.h.
    : twobyte_start(start), length_(length), state_(TWO_BYTE), no_gc_(no_gc) {
#ifdef ENABLE_SLOW_DCHECKS
  checksum_ = ComputeChecksum();
#endif
}
FlatContent() [3/3]
v8::internal::String::FlatContent::FlatContent (const DisallowGarbageCollection & no_gc) [inline], [explicit], [private]
Definition at line 187 of file string.h.
        : onebyte_start(nullptr), length_(0), state_(NON_FLAT), no_gc_(no_gc) {}
Member Function Documentation
Get()
base::uc16 v8::internal::String::FlatContent::Get (uint32_t i) const [inline]
Definition at line 155 of file string.h.
                                   {
      DCHECK(i < length_);
      DCHECK(state_ != NON_FLAT);
      if (state_ == ONE_BYTE) return onebyte_start[i];
      return twobyte_start[i];
    }
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, length_, NON_FLAT, ONE_BYTE, onebyte_start, state_, and twobyte_start.
Referenced by v8::internal::anonymous_namespace{uri.cc}::AddToBuffer(), v8::internal::BUILTIN(), v8::internal::Uri::Encode(), v8::internal::GetOffsetTimeZone(), v8::internal::anonymous_namespace{uri.cc}::IntoOneAndTwoByte(), v8::internal::anonymous_namespace{uri.cc}::IntoTwoByte(), and v8::internal::SubStringRange::iterator::operator*().
IsFlat()
bool v8::internal::String::FlatContent::IsFlat () const [inline]
Definition at line 136 of file string.h.
{ return state_ != NON_FLAT; }
References NON_FLAT, and state_.
Referenced by v8::internal::RegExpImpl::AtomExecRaw(), v8::internal::String::CalculateLineEndsVector(), v8::internal::CompiledReplacement::Compile(), v8::internal::anonymous_namespace{builtins-string.cc}::ConvertCase(), v8::internal::FindStringIndicesDispatch(), v8::internal::FlatStringToDouble(), v8::internal::anonymous_namespace{intl-objects.cc}::GetUCharBufferFromFlat(), v8::internal::String::IsWellFormedUnicode(), v8::internal::anonymous_namespace{runtime-wasm.cc}::MeasureWtf8(), v8::internal::FlatStringReader::PostGarbageCollection(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ToUtf8Lossy(), v8::internal::String::Utf8Length(), v8::internal::ValueSerializer::WriteString(), and v8::internal::String::WriteUtf8().
IsOneByte()
bool v8::internal::String::FlatContent::IsOneByte () const [inline]
Definition at line 138 of file string.h.
{ return state_ == ONE_BYTE; }
References ONE_BYTE, and state_.
Referenced by v8::internal::RegExpImpl::AtomExecRaw(), v8::internal::BUILTIN(), v8::internal::String::CalculateLineEndsVector(), v8::internal::String::Compare(), v8::internal::CompiledReplacement::Compile(), v8::internal::Intl::ConvertOneByteToLower(), v8::internal::Intl::ConvertToUpper(), v8::internal::anonymous_namespace{runtime-wasm.cc}::EncodeWtf8(), v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareStringFlatContent(), v8::internal::FindStringIndicesDispatch(), v8::internal::FlatStringToDouble(), v8::internal::anonymous_namespace{js-number-format.cc}::FormatDecimalString(), v8::internal::String::GetCharVector(), v8::internal::AstValueFactory::GetString(), v8::internal::anonymous_namespace{intl-objects.cc}::GetUCharBufferFromFlat(), v8::internal::anonymous_namespace{js-number-format.cc}::IcuFormatNumber(), v8::internal::String::IndexOf(), v8::internal::String::IsIdentifier(), v8::internal::String::LastIndexOf(), v8::internal::anonymous_namespace{builtins-typed-array.cc}::MapOptionToEnum(), v8::internal::IrregexpInterpreter::MatchInternal(), v8::internal::anonymous_namespace{runtime-wasm.cc}::MeasureWtf8(), v8::internal::Factory::NewCopiedSubstring(), v8::internal::ParseDateTimeString(), v8::internal::RegExpParser::ParseRegExpFromHeapString(), v8::internal::FlatStringReader::PostGarbageCollection(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpMatchGlobalAtom_Dispatch(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{string.cc}::SearchString(), v8::internal::String::SlowEquals(), v8::internal::IntlMathematicalValue::ToFormattable(), v8::internal::anonymous_namespace{intl-objects.cc}::ToICUStringPiece(), v8::internal::Intl::ToICUUnicodeString(), v8::internal::ToUtf8Lossy(), v8::internal::anonymous_namespace{js-number-format.cc}::TrimWhiteSpaceOrLineTerminator(), v8::internal::String::Utf8Length(), v8::internal::ValueSerializer::WriteString(), and v8::internal::String::WriteUtf8().
IsTwoByte()
bool v8::internal::String::FlatContent::IsTwoByte () const [inline]
Definition at line 140 of file string.h.
{ return state_ == TWO_BYTE; }
References state_, and TWO_BYTE.
Referenced by v8::internal::CompiledReplacement::Compile(), v8::internal::Intl::ConvertOneByteToLower(), v8::internal::Intl::ConvertToUpper(), v8::internal::AstValueFactory::GetString(), v8::internal::IrregexpInterpreter::MatchInternal(), v8::internal::String::SlowEquals(), and v8::internal::ValueSerializer::WriteString().
length()
uint32_t v8::internal::String::FlatContent::length () const [inline]
Definition at line 177 of file string.h.
{ return length_; }
References length_.
Referenced by v8::internal::RegExpImpl::AtomExecRaw(), v8::internal::GetOffsetTimeZone(), and v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpMatchGlobalAtom_Dispatch().
ToOneByteVector()
base::Vector<const uint8_t> v8::internal::String::FlatContent::ToOneByteVector () const [inline]
Definition at line 144 of file string.h.
                                                      {
      DCHECK_EQ(ONE_BYTE, state_);
      return base::Vector<const uint8_t>(onebyte_start, length_);
    }
References DCHECK_EQ, length_, ONE_BYTE, onebyte_start, and state_.
Referenced by v8::internal::RegExpImpl::AtomExecRaw(), v8::internal::BUILTIN(), v8::internal::String::CalculateLineEndsVector(), v8::internal::String::Compare(), v8::internal::CompiledReplacement::Compile(), v8::internal::anonymous_namespace{builtins-string.cc}::ConvertCase(), v8::internal::Intl::ConvertOneByteToLower(), v8::internal::Intl::ConvertToUpper(), v8::internal::anonymous_namespace{runtime-wasm.cc}::EncodeWtf8(), v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareStringFlatContent(), v8::internal::FindStringIndicesDispatch(), v8::internal::FlatStringToDouble(), v8::internal::anonymous_namespace{js-number-format.cc}::FormatDecimalString(), v8::internal::String::GetCharVector(), v8::internal::AstValueFactory::GetString(), v8::internal::anonymous_namespace{intl-objects.cc}::GetUCharBufferFromFlat(), v8::internal::anonymous_namespace{js-number-format.cc}::IcuFormatNumber(), v8::internal::String::IndexOf(), v8::internal::String::IsIdentifier(), v8::internal::String::LastIndexOf(), v8::internal::anonymous_namespace{builtins-typed-array.cc}::MapOptionToEnum(), v8::internal::IrregexpInterpreter::MatchInternal(), v8::internal::anonymous_namespace{runtime-wasm.cc}::MeasureWtf8(), v8::internal::ParseDateTimeString(), v8::internal::RegExpParser::ParseRegExpFromHeapString(), v8::internal::FlatStringReader::PostGarbageCollection(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpMatchGlobalAtom_Dispatch(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{string.cc}::SearchString(), v8::internal::String::SlowEquals(), v8::internal::IntlMathematicalValue::ToFormattable(), v8::internal::anonymous_namespace{intl-objects.cc}::ToICUStringPiece(), v8::internal::Intl::ToICUUnicodeString(), v8::internal::ToUtf8Lossy(), v8::internal::anonymous_namespace{js-number-format.cc}::TrimWhiteSpaceOrLineTerminator(), v8::internal::String::Utf8Length(), v8::internal::ValueSerializer::WriteString(), and v8::internal::String::WriteUtf8().
ToUC16Vector()
base::Vector<const base::uc16> v8::internal::String::FlatContent::ToUC16Vector () const [inline]
Definition at line 150 of file string.h.
                                                    {
      DCHECK_EQ(TWO_BYTE, state_);
      return base::Vector<const base::uc16>(twobyte_start, length_);
    }
References DCHECK_EQ, length_, state_, TWO_BYTE, and twobyte_start.
Referenced by v8::internal::RegExpImpl::AtomExecRaw(), v8::internal::BUILTIN(), v8::internal::String::CalculateLineEndsVector(), v8::internal::String::Compare(), v8::internal::CompiledReplacement::Compile(), v8::internal::Intl::ConvertOneByteToLower(), v8::internal::Intl::ConvertToUpper(), v8::internal::anonymous_namespace{runtime-wasm.cc}::EncodeWtf8(), v8::internal::anonymous_namespace{intl-objects.cc}::FastCompareStringFlatContent(), v8::internal::FindStringIndicesDispatch(), v8::internal::FlatStringToDouble(), v8::internal::AstValueFactory::GetString(), v8::internal::anonymous_namespace{intl-objects.cc}::GetUCharBufferFromFlat(), v8::internal::String::IndexOf(), v8::internal::String::IsIdentifier(), v8::internal::String::IsWellFormedUnicode(), v8::internal::String::LastIndexOf(), v8::internal::anonymous_namespace{builtins-typed-array.cc}::MapOptionToEnum(), v8::internal::IrregexpInterpreter::MatchInternal(), v8::internal::anonymous_namespace{runtime-wasm.cc}::MeasureWtf8(), v8::internal::Factory::NewCopiedSubstring(), v8::internal::ParseDateTimeString(), v8::internal::RegExpParser::ParseRegExpFromHeapString(), v8::internal::FlatStringReader::PostGarbageCollection(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpMatchGlobalAtom_Dispatch(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{string.cc}::SearchString(), v8::internal::String::SlowEquals(), v8::internal::ToUtf8Lossy(), v8::internal::anonymous_namespace{js-number-format.cc}::TrimWhiteSpaceOrLineTerminator(), v8::internal::String::Utf8Length(), v8::internal::ValueSerializer::WriteString(), and v8::internal::String::WriteUtf8().
UnsafeDisableChecksumVerification()
void v8::internal::String::FlatContent::UnsafeDisableChecksumVerification () [inline]
Definition at line 171 of file string.h.
                                             {
#ifdef ENABLE_SLOW_DCHECKS
      checksum_ = kChecksumVerificationDisabled;
#endif
    }
References kChecksumVerificationDisabled.
Referenced by v8::internal::IrregexpInterpreter::MatchInternal().
UsesSameString()
bool v8::internal::String::FlatContent::UsesSameString (const FlatContent & other) const [inline]
Definition at line 162 of file string.h.
                                                        {
      return onebyte_start == other.onebyte_start;
    }
References onebyte_start.
Referenced by v8::internal::SubStringRange::iterator::operator!=(), and v8::internal::SubStringRange::iterator::operator==().
Friends And Related Function Documentation
IterableSubString
friend class IterableSubString [friend]
Definition at line 207 of file string.h.
String
friend class String [friend]
Definition at line 206 of file string.h.
Member Data Documentation
union { ... } [private]
kChecksumVerificationDisabled
constexpr uint32_t v8::internal::String::FlatContent::kChecksumVerificationDisabled = 0 [static], [constexpr], [private]
Definition at line 198 of file string.h.
Referenced by UnsafeDisableChecksumVerification().
length_
uint32_t v8::internal::String::FlatContent::length_ [private]
Definition at line 194 of file string.h.
Referenced by Get(), length(), ToOneByteVector(), and ToUC16Vector().
no_gc_
const DisallowGarbageCollection& v8::internal::String::FlatContent::no_gc_ [private]
Definition at line 196 of file string.h.
onebyte_start
const uint8_t* v8::internal::String::FlatContent::onebyte_start
Definition at line 191 of file string.h.
Referenced by Get(), ToOneByteVector(), and UsesSameString().
state_
State v8::internal::String::FlatContent::state_ [private]
Definition at line 195 of file string.h.
Referenced by Get(), IsFlat(), IsOneByte(), IsTwoByte(), ToOneByteVector(), and ToUC16Vector().
twobyte_start
const base::uc16* v8::internal::String::FlatContent::twobyte_start
Definition at line 192 of file string.h.
Referenced by Get(), and ToUC16Vector().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string.h
/mnt/V8SourceCode/src/objects/string-inl.h