v8::internal::compiler::Typer::Decorator Class Reference
Public Member Functions
Decorator (Typer *typer)
void Decorate (Node *node) final
Private Attributes
Typer *const typer_
Detailed Description
Definition at line 29 of file turbofan-typer.cc.
Constructor & Destructor Documentation
Decorator()
v8::internal::compiler::Typer::Decorator::Decorator (Typer * typer) [inline], [explicit]
Definition at line 31 of file turbofan-typer.cc.
: typer_(typer) {}
Member Function Documentation
Decorate()
void v8::internal::compiler::Typer::Decorator::Decorate (Node * node) [final], [virtual]
Implements v8::internal::compiler::GraphDecorator.
Definition at line 494 of file turbofan-typer.cc.
                                        {
  if (node->op()->ValueOutputCount() > 0) {
    // Only eagerly type-decorate nodes with known input types.
    // Other cases will generally require a proper fixpoint iteration with Run.
    bool is_typed = NodeProperties::IsTyped(node);
    if (is_typed || NodeProperties::AllValueInputsAreTyped(node)) {
      Visitor typing(typer_, nullptr);
      Type type = typing.TypeNode(node);
      if (is_typed) {
        type = Type::Intersect(type, NodeProperties::GetType(node),
                               typer_->zone());
      }
      NodeProperties::SetType(node, type);
    }
  }
}
References v8::internal::compiler::NodeProperties::AllValueInputsAreTyped(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::NodeProperties::IsTyped(), v8::internal::compiler::Node::op(), v8::internal::compiler::NodeProperties::SetType(), v8::internal::tracing::type, v8::internal::compiler::Typer::Visitor::TypeNode(), typer_, v8::internal::compiler::Operator::ValueOutputCount(), and v8::internal::compiler::Typer::zone().
Member Data Documentation
typer_
Typer* const v8::internal::compiler::Typer::Decorator::typer_ [private]
Definition at line 35 of file turbofan-typer.cc.
Referenced by Decorate().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turbofan-typer.cc