v8::internal::Sweeper::LocalSweeper Class Reference
#include <sweeper.h>
Public Member Functions
LocalSweeper (Sweeper *sweeper)
~LocalSweeper ()=default
bool ParallelSweepSpace (AllocationSpace identity, SweepingMode sweeping_mode, uint32_t max_pages=std::numeric_limits< uint32_t >::max())
bool ContributeAndWaitForPromotedPagesIteration (JobDelegate *delegate)
bool ContributeAndWaitForPromotedPagesIteration ()
Private Member Functions
void ParallelSweepPage (PageMetadata *page, AllocationSpace identity, SweepingMode sweeping_mode)
bool ParallelIteratePromotedPages (JobDelegate *delegate)
bool ParallelIteratePromotedPages ()
void ParallelIteratePromotedPage (MutablePageMetadata *page)
template<typename ShouldYieldCallback >
bool ContributeAndWaitForPromotedPagesIterationImpl (ShouldYieldCallback should_yield_callback)
template<typename ShouldYieldCallback >
bool ParallelIteratePromotedPagesImpl (ShouldYieldCallback should_yield_callback)
Private Attributes
Sweeper *const sweeper_
Friends
class Sweeper
Detailed Description
Definition at line 69 of file sweeper.h.
Constructor & Destructor Documentation
LocalSweeper()
v8::internal::Sweeper::LocalSweeper::LocalSweeper (Sweeper * sweeper) [inline], [explicit]
Definition at line 71 of file sweeper.h.
                                            : sweeper_(sweeper) {
      DCHECK_NOT_NULL(sweeper_);
    }
References DCHECK_NOT_NULL, and sweeper_.
 LocalSweeper()
v8::internal::Sweeper::LocalSweeper::~LocalSweeper () [default]
Member Function Documentation
ContributeAndWaitForPromotedPagesIteration() [1/2]
bool v8::internal::Sweeper::LocalSweeper::ContributeAndWaitForPromotedPagesIteration ()
Definition at line 429 of file sweeper.cc.
                                                                     {
  return ContributeAndWaitForPromotedPagesIterationImpl([]() { return false; });
}
ContributeAndWaitForPromotedPagesIteration() [2/2]
bool v8::internal::Sweeper::LocalSweeper::ContributeAndWaitForPromotedPagesIteration (JobDelegate * delegate)
Definition at line 423 of file sweeper.cc.
                           {
  return ContributeAndWaitForPromotedPagesIterationImpl(
      [delegate]() { return delegate->ShouldYield(); });
}
References v8::JobDelegate::ShouldYield().
Referenced by v8::internal::Sweeper::ContributeAndWaitForPromotedPagesIteration(), v8::internal::Sweeper::FinishMinorJobs(), and v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::Run().
ContributeAndWaitForPromotedPagesIterationImpl()
template<typename ShouldYieldCallback >
bool v8::internal::Sweeper::LocalSweeper::ContributeAndWaitForPromotedPagesIterationImpl (ShouldYieldCallback should_yield_callback) [private]
Definition at line 344 of file sweeper.h.
                                               {
  if (!sweeper_->sweeping_in_progress()) return true;
  if (!sweeper_->IsIteratingPromotedPages()) return true;
  if (!ParallelIteratePromotedPagesImpl(should_yield_callback)) return false;
  base::MutexGuard guard(
      &sweeper_->promoted_pages_iteration_notification_mutex_);
  // Check again that iteration is not yet finished.
  if (!sweeper_->IsIteratingPromotedPages()) return true;
  if (should_yield_callback()) {
    return false;
  }
  sweeper_->promoted_pages_iteration_notification_variable_.Wait(
      &sweeper_->promoted_pages_iteration_notification_mutex_);
  return true;
}
References v8::internal::Sweeper::IsIteratingPromotedPages(), ParallelIteratePromotedPagesImpl(), v8::internal::Sweeper::promoted_pages_iteration_notification_mutex_, v8::internal::Sweeper::promoted_pages_iteration_notification_variable_, sweeper_, v8::internal::Sweeper::sweeping_in_progress(), and v8::base::ConditionVariable::Wait().
ParallelIteratePromotedPage()
void v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage (MutablePageMetadata * page) [private]
Definition at line 640 of file sweeper.cc.
                               {
  DCHECK(v8_flags.minor_ms);
  DCHECK(!page->Chunk()->IsFlagSet(MemoryChunk::BLACK_ALLOCATED));
  DCHECK_NOT_NULL(page);
  {
    base::MutexGuard guard(page->mutex());
    DCHECK(!page->SweepingDone());
    DCHECK_EQ(PageMetadata::ConcurrentSweepingState::kPendingIteration,
              page->concurrent_sweeping_state());
    page->set_concurrent_sweeping_state(
        PageMetadata::ConcurrentSweepingState::kInProgress);
    PromotedPageRecordMigratedSlotVisitor record_visitor(page);
    const bool is_large_page = page->Chunk()->IsLargePage();
    if (is_large_page) {
      DCHECK_EQ(LO_SPACE, page->owner_identity());
      record_visitor.Process(LargePageMetadata::cast(page)->GetObject());
      page->ReleaseSlotSet(SURVIVOR_TO_EXTERNAL_POINTER);
    } else {
      DCHECK_EQ(OLD_SPACE, page->owner_identity());
      DCHECK(!page->Chunk()->IsEvacuationCandidate());
      const ZappingMode zapping_mode = ShouldZapDeadObjectsOnPage();
      Address dead_start = page->area_start();
      for (auto [object, size] :
           LiveObjectRange(static_cast<PageMetadata*>(page))) {
        record_visitor.Process(object);
        if (zapping_mode != ZappingMode::kNone) {
          Address dead_end = object.address();
          ZapDeadObjectsInRange(sweeper_->heap_, dead_start, dead_end,
                                zapping_mode);
          dead_start = dead_end + size;
        }
      }
      if (zapping_mode != ZappingMode::kNone) {
        ZapDeadObjectsInRange(sweeper_->heap_, dead_start, page->area_end(),
                              zapping_mode);
      }
    }
    page->ClearLiveness();
    sweeper_->NotifyPromotedPageIterationFinished(page);
    DCHECK(page->SweepingDone());
  }
}
References v8::internal::MemoryChunkMetadata::area_end(), v8::internal::MemoryChunkMetadata::area_start(), v8::internal::MemoryChunk::BLACK_ALLOCATED, v8::internal::LargePageMetadata::cast(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MutablePageMetadata::ClearLiveness(), v8::internal::MutablePageMetadata::concurrent_sweeping_state(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::MemoryChunk::IsEvacuationCandidate(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::IsLargePage(), v8::internal::MutablePageMetadata::kInProgress, v8::internal::MutablePageMetadata::kPendingIteration, v8::internal::LO_SPACE, v8::internal::MutablePageMetadata::mutex(), v8::internal::OLD_SPACE, v8::internal::MutablePageMetadata::owner_identity(), v8::internal::MutablePageMetadata::ReleaseSlotSet(), v8::internal::MutablePageMetadata::set_concurrent_sweeping_state(), v8::internal::anonymous_namespace{sweeper.cc}::ShouldZapDeadObjectsOnPage(), size(), v8::internal::SURVIVOR_TO_EXTERNAL_POINTER, v8::internal::MutablePageMetadata::SweepingDone(), v8::internal::v8_flags, and v8::internal::anonymous_namespace{sweeper.cc}::ZapDeadObjectsInRange().
Referenced by v8::internal::Sweeper::EnsurePageIsSwept().
ParallelIteratePromotedPages() [1/2]
bool v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPages () [private]
Definition at line 439 of file sweeper.cc.
                                                       {
  return ParallelIteratePromotedPagesImpl([]() { return false; });
}
ParallelIteratePromotedPages() [2/2]
bool v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPages (JobDelegate * delegate) [private]
Definition at line 433 of file sweeper.cc.
                           {
  return ParallelIteratePromotedPagesImpl(
      [delegate]() { return delegate->ShouldYield(); });
}
References v8::JobDelegate::ShouldYield().
Referenced by v8::internal::Sweeper::ConcurrentMinorSweeper::ConcurrentSweepPromotedPages().
ParallelIteratePromotedPagesImpl()
template<typename ShouldYieldCallback >
bool v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPagesImpl (ShouldYieldCallback should_yield_callback) [private]
Definition at line 362 of file sweeper.h.
                                               {
  while (!should_yield_callback()) {
    MutablePageMetadata* chunk = sweeper_->GetPromotedPageSafe();
    if (chunk == nullptr) return true;
    ParallelIteratePromotedPage(chunk);
  }
  return false;
}
Referenced by ContributeAndWaitForPromotedPagesIterationImpl().
ParallelSweepPage()
void v8::internal::Sweeper::LocalSweeper::ParallelSweepPage (PageMetadata * page, AllocationSpace identity, SweepingMode sweeping_mode) [private]
Definition at line 394 of file sweeper.cc.
                                                                          {
  DCHECK(IsValidSweepingSpace(identity));
  DCHECK(!page->SweepingDone());
  {
    base::MutexGuard guard(page->mutex());
    DCHECK(!page->SweepingDone());
    DCHECK_EQ(PageMetadata::ConcurrentSweepingState::kPendingSweeping,
              page->concurrent_sweeping_state());
    page->set_concurrent_sweeping_state(
        PageMetadata::ConcurrentSweepingState::kInProgress);
    const FreeSpaceTreatmentMode free_space_treatment_mode =
        heap::ShouldZapGarbage() ? FreeSpaceTreatmentMode::kZapFreeSpace
                                 : FreeSpaceTreatmentMode::kIgnoreFreeSpace;
    DCHECK_IMPLIES(identity == NEW_SPACE,
                   !sweeper_->minor_sweeping_state_.should_reduce_memory());
    sweeper_->RawSweep(
        page, free_space_treatment_mode, sweeping_mode,
        identity == NEW_SPACE
            ? false
            : sweeper_->major_sweeping_state_.should_reduce_memory());
    sweeper_->AddSweptPage(page, identity);
    DCHECK(page->SweepingDone());
  }
}
References v8::internal::MutablePageMetadata::concurrent_sweeping_state(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Sweeper::IsValidSweepingSpace(), v8::internal::kIgnoreFreeSpace, v8::internal::MutablePageMetadata::kInProgress, v8::internal::MutablePageMetadata::kPendingSweeping, v8::internal::kZapFreeSpace, v8::internal::MutablePageMetadata::mutex(), v8::internal::NEW_SPACE, v8::internal::MutablePageMetadata::set_concurrent_sweeping_state(), v8::internal::heap::ShouldZapGarbage(), and v8::internal::MutablePageMetadata::SweepingDone().
Referenced by v8::internal::Sweeper::ConcurrentMajorSweeper::ConcurrentSweepSpace(), v8::internal::Sweeper::ConcurrentMinorSweeper::ConcurrentSweepSpace(), and v8::internal::Sweeper::EnsurePageIsSwept().
ParallelSweepSpace()
bool v8::internal::Sweeper::LocalSweeper::ParallelSweepSpace (AllocationSpace identity, SweepingMode sweeping_mode, uint32_t max_pages = std::numeric_limits<uint32_t>::max())
Definition at line 365 of file sweeper.cc.
                                                                   {
  uint32_t pages_swept = 0;
  bool found_usable_pages = false;
  PageMetadata* page = nullptr;
  while ((page = sweeper_->GetSweepingPageSafe(identity)) != nullptr) {
    ParallelSweepPage(page, identity, sweeping_mode);
    if (!page->Chunk()->IsFlagSet(MemoryChunk::NEVER_ALLOCATE_ON_PAGE)) {
      found_usable_pages = true;
#if DEBUG
    } else {
      // All remaining pages are also marked with NEVER_ALLOCATE_ON_PAGE.
      base::MutexGuard guard(&sweeper_->mutex_);
      int space_index = GetSweepSpaceIndex(identity);
      Sweeper::SweepingList& sweeping_list =
          sweeper_->sweeping_list_[space_index];
      DCHECK(std::all_of(sweeping_list.begin(), sweeping_list.end(),
                         [](const PageMetadata* p) {
                           return p->Chunk()->IsFlagSet(
                               MemoryChunk::NEVER_ALLOCATE_ON_PAGE);
                         }));
#endif // DEBUG
    }
    if (++pages_swept >= max_pages) break;
  }
  return found_usable_pages;
}
References v8::base::all_of(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), v8::internal::Sweeper::GetSweepSpaceIndex(), v8::internal::MemoryChunk::IsFlagSet(), and v8::internal::MemoryChunk::NEVER_ALLOCATE_ON_PAGE.
Referenced by v8::internal::Sweeper::FinishMajorJobs(), v8::internal::Sweeper::FinishMinorJobs(), and v8::internal::Sweeper::ParallelSweepSpace().
Friends And Related Function Documentation
Sweeper
friend class Sweeper [friend]
Definition at line 102 of file sweeper.h.
Member Data Documentation
sweeper_
Sweeper* const v8::internal::Sweeper::LocalSweeper::sweeper_ [private]
Definition at line 100 of file sweeper.h.
Referenced by ContributeAndWaitForPromotedPagesIterationImpl(), and LocalSweeper().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/sweeper.h
/mnt/V8SourceCode/src/heap/sweeper.cc