v8::internal::JavaScriptStackFrameIterator Class Reference
#include <frames.h>
Public Member Functions
JavaScriptStackFrameIterator (Isolate *isolate)
JavaScriptStackFrameIterator (Isolate *isolate, ThreadLocalTop *top)
JavaScriptFrame * frame () const
JavaScriptFrame * Reframe ()
bool done () const
V8_EXPORT_PRIVATE void Advance ()
Private Attributes
StackFrameIterator iterator_
Detailed Description
Definition at line 1735 of file frames.h.
Constructor & Destructor Documentation
JavaScriptStackFrameIterator() [1/2]
v8::internal::JavaScriptStackFrameIterator::JavaScriptStackFrameIterator (Isolate * isolate) [inline], [explicit]
Definition at line 1737 of file frames.h.
                                                          : iterator_(isolate) {
    if (!done()) Advance();
  }
References Advance(), and done().
JavaScriptStackFrameIterator() [2/2]
v8::internal::JavaScriptStackFrameIterator::JavaScriptStackFrameIterator (Isolate * isolate, ThreadLocalTop * top) [inline]
Definition at line 1740 of file frames.h.
      : iterator_(isolate, top) {
    if (!done()) Advance();
  }
References Advance(), and done().
Member Function Documentation
Advance()
void v8::internal::JavaScriptStackFrameIterator::Advance ()
Definition at line 356 of file frames.cc.
                                           {
  do {
    iterator_.Advance();
  } while (!iterator_.done() && !iterator_.frame()->is_javascript());
}
References v8::internal::StackFrameIterator::Advance(), v8::internal::StackFrameIteratorBase::done(), v8::internal::StackFrameIterator::frame(), v8::internal::StackFrame::is_javascript(), and iterator_.
Referenced by v8::internal::SamplingHeapProfiler::AddStack(), v8::internal::AllocationTracker::AllocationEvent(), JavaScriptStackFrameIterator(), v8::internal::FrameFunctionIterator::next(), v8::internal::Debug::PrepareStepOnThrow(), v8::internal::JavaScriptFrame::PrintTop(), and v8::internal::RUNTIME_FUNCTION().
done()
bool v8::internal::JavaScriptStackFrameIterator::done () const [inline]
Definition at line 1751 of file frames.h.
{ return iterator_.done(); }
References v8::internal::StackFrameIteratorBase::done(), and iterator_.
Referenced by v8::internal::SamplingHeapProfiler::AddStack(), v8::internal::AllocationTracker::AllocationEvent(), v8::internal::anonymous_namespace{debug-coverage.cc}::CollectAndMaybeResetCounts(), v8::internal::anonymous_namespace{messages.cc}::ComputeLocation(), v8::internal::Accessors::FunctionGetArguments(), v8::internal::Isolate::GetAbstractPC(), v8::internal::FrameFunctionIterator::GetFrames(), v8::internal::Isolate::GetIncumbentContextSlow(), v8::internal::Accessors::GetLegacyFunctionArguments(), JavaScriptStackFrameIterator(), v8::internal::FrameFunctionIterator::next(), v8::internal::Isolate::OnPromiseThen(), v8::internal::Debug::PrepareStepOnThrow(), v8::internal::JavaScriptFrame::PrintTop(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{runtime-test.cc}::StackSize(), v8::internal::RedirectActiveFunctions::VisitThread(), v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor::VisitThread(), and v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::VisitThread().
frame()
JavaScriptFrame* v8::internal::JavaScriptStackFrameIterator::frame () const [inline]
Definition at line 1745 of file frames.h.
                                 {
    return JavaScriptFrame::cast(iterator_.frame());
  }
References v8::internal::JavaScriptFrame::cast(), v8::internal::StackFrameIterator::frame(), and iterator_.
Referenced by v8::internal::SamplingHeapProfiler::AddStack(), v8::internal::AllocationTracker::AllocationEvent(), v8::internal::anonymous_namespace{messages.cc}::ComputeLocation(), v8::internal::Isolate::GetAbstractPC(), v8::internal::anonymous_namespace{runtime-scopes.cc}::GetCallerArguments(), v8::internal::anonymous_namespace{accessors.cc}::GetFrameArguments(), v8::internal::FrameFunctionIterator::GetFrames(), v8::internal::Isolate::GetIncumbentContextSlow(), v8::internal::anonymous_namespace{runtime-compiler.cc}::GetOsrOffsetAndFunctionForOSR(), v8::internal::FrameFunctionIterator::MaterializeFunction(), v8::internal::Debug::PrepareStepOnThrow(), v8::internal::JavaScriptFrame::PrintTop(), v8::internal::RUNTIME_FUNCTION(), v8::internal::RUNTIME_FUNCTION_RETURN_PAIR(), v8::internal::IC::TraceIC(), and v8::internal::DebugEvaluate::WithTopmostArguments().
Reframe()
JavaScriptFrame* v8::internal::JavaScriptStackFrameIterator::Reframe () [inline]
Definition at line 1748 of file frames.h.
                             {
    return JavaScriptFrame::cast(iterator_.Reframe());
  }
References v8::internal::JavaScriptFrame::cast(), iterator_, and v8::internal::StackFrameIterator::Reframe().
Member Data Documentation
iterator_
StackFrameIterator v8::internal::JavaScriptStackFrameIterator::iterator_ [private]
Definition at line 1756 of file frames.h.
Referenced by Advance(), done(), frame(), and Reframe().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames.cc