v8::internal::HeapSnapshotJSONSerializer Class Reference
#include <heap-snapshot-generator.h>
Public Member Functions
HeapSnapshotJSONSerializer (HeapSnapshot *snapshot)
HeapSnapshotJSONSerializer (const HeapSnapshotJSONSerializer &)=delete
HeapSnapshotJSONSerializer & operator= (const HeapSnapshotJSONSerializer &)=delete
void Serialize (v8::OutputStream *stream)
Private Member Functions
int GetStringId (const char *s)
int to_node_index (const HeapEntry *e)
int to_node_index (int entry_index)
void SerializeEdge (HeapGraphEdge *edge, bool first_edge)
void SerializeEdges ()
void SerializeImpl ()
void SerializeNode (const HeapEntry *entry)
void SerializeNodes ()
void SerializeSnapshot ()
void SerializeTraceTree ()
void SerializeTraceNode (AllocationTraceNode *node)
void SerializeTraceNodeInfos ()
void SerializeSamples ()
void SerializeString (const unsigned char *s)
void SerializeStrings ()
void SerializeLocation (const EntrySourceLocation &location)
void SerializeLocations ()
Static Private Member Functions
static bool StringsMatch (void *key1, void *key2)
static uint32_t StringHash (const void *string)
Private Attributes
HeapSnapshot * snapshot_
base::CustomMatcherHashMap strings_
int next_node_id_
int next_string_id_
OutputStreamWriter * writer_
uint32_t trace_function_count_ = 0
Static Private Attributes
static const int kEdgeFieldsCount
static const int kNodeFieldsCountWithTraceNodeId = 7
static const int kNodeFieldsCountWithoutTraceNodeId = 6
Friends
class HeapSnapshotJSONSerializerEnumerator
class HeapSnapshotJSONSerializerIterator
Detailed Description
Definition at line 751 of file heap-snapshot-generator.h.
Constructor & Destructor Documentation
HeapSnapshotJSONSerializer() [1/2]
v8::internal::HeapSnapshotJSONSerializer::HeapSnapshotJSONSerializer (HeapSnapshot * snapshot) [inline], [explicit]
Definition at line 753 of file heap-snapshot-generator.h.
      : snapshot_(snapshot),
        strings_(StringsMatch),
        next_node_id_(1),
        next_string_id_(1),
        writer_(nullptr) {}
HeapSnapshotJSONSerializer() [2/2]
v8::internal::HeapSnapshotJSONSerializer::HeapSnapshotJSONSerializer (const HeapSnapshotJSONSerializer &) [delete]
Member Function Documentation
GetStringId()
int v8::internal::HeapSnapshotJSONSerializer::GetStringId (const char * s) [private]
Definition at line 3448 of file heap-snapshot-generator.cc.
                                                         {
  base::HashMap::Entry* cache_entry =
      strings_.LookupOrInsert(const_cast<char*>(s), StringHash(s));
  if (cache_entry->value == nullptr) {
    cache_entry->value = reinterpret_cast<void*>(next_string_id_++);
  }
  return static_cast<int>(reinterpret_cast<intptr_t>(cache_entry->value));
}
References next_string_id_, StringHash(), and strings_.
Referenced by SerializeEdge(), SerializeNode(), and SerializeTraceNodeInfos().
operator=()
HeapSnapshotJSONSerializer& v8::internal::HeapSnapshotJSONSerializer::operator= (const HeapSnapshotJSONSerializer &) [delete]
Serialize()
void v8::internal::HeapSnapshotJSONSerializer::Serialize (v8::OutputStream * stream)
Definition at line 3383 of file heap-snapshot-generator.cc.
                                                                 {
  v8::base::ElapsedTimer timer;
  timer.Start();
  DCHECK_NULL(writer_);
  writer_ = new OutputStreamWriter(stream);
  trace_function_count_ = 0;
  if (AllocationTracker* tracker =
          snapshot_->profiler()->allocation_tracker()) {
    trace_function_count_ =
        static_cast<uint32_t>(tracker->function_info_list().size());
  }
  SerializeImpl();
  delete writer_;
  writer_ = nullptr;
  if (i::v8_flags.profile_heap_snapshot) {
    base::OS::PrintError("[Serialization of heap snapshot took %0.3f ms]\n",
                         timer.Elapsed().InMillisecondsF());
  }
  timer.Stop();
}
References v8::internal::HeapProfiler::allocation_tracker(), DCHECK_NULL, v8::base::ElapsedTimer::Elapsed(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::HeapSnapshot::profiler(), SerializeImpl(), snapshot_, v8::base::ElapsedTimer::Start(), v8::base::ElapsedTimer::Stop(), trace_function_count_, v8::internal::v8_flags, and writer_.
Referenced by v8::HeapSnapshot::Serialize(), v8::internal::HeapProfiler::TakeSnapshotToFile(), v8::internal::HeapProfiler::TakeSnapshotToString(), and v8::internal::HeapProfiler::WriteSnapshotToDiskAfterGC().
SerializeEdge()
void v8::internal::HeapSnapshotJSONSerializer::SerializeEdge (HeapGraphEdge * edge, bool first_edge) [private]
Definition at line 3457 of file heap-snapshot-generator.cc.
                                                                {
  int edge_name_or_index = edge->type() == HeapGraphEdge::kElement ||
                                   edge->type() == HeapGraphEdge::kHidden
                               ? edge->index()
                               : GetStringId(edge->name());
  if (!first_edge) {
    writer_->AddCharacter(',');
  }
  writer_->AddNumber(static_cast<int>(edge->type()));
  writer_->AddCharacter(',');
  writer_->AddNumber(edge_name_or_index);
  writer_->AddCharacter(',');
  writer_->AddNumber(to_node_index(edge->to()));
}
References v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::OutputStreamWriter::AddNumber(), GetStringId(), v8::internal::HeapGraphEdge::index(), v8::internal::HeapGraphEdge::kElement, v8::internal::HeapGraphEdge::kHidden, v8::internal::HeapGraphEdge::name(), v8::internal::HeapGraphEdge::to(), to_node_index(), v8::internal::HeapGraphEdge::type(), and writer_.
Referenced by SerializeEdges().
SerializeEdges()
void v8::internal::HeapSnapshotJSONSerializer::SerializeEdges () [private]
Definition at line 3473 of file heap-snapshot-generator.cc.
                                                {
  const std::vector<HeapGraphEdge*>& edges = snapshot_->children();
  for (size_t i = 0; i < edges.size(); ++i) {
    DCHECK(i == 0 ||
           edges[i - 1]->from()->index() <= edges[i]->from()->index());
    SerializeEdge(edges[i], i == 0);
    if (writer_->aborted()) return;
  }
}
References v8::internal::OutputStreamWriter::aborted(), v8::internal::HeapSnapshot::children(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, SerializeEdge(), snapshot_, and writer_.
Referenced by SerializeImpl().
SerializeImpl()
void v8::internal::HeapSnapshotJSONSerializer::SerializeImpl () [private]
Definition at line 3405 of file heap-snapshot-generator.cc.
                                               {
  DCHECK_EQ(0, snapshot_->root()->index());
  writer_->AddCharacter('{');
  writer_->AddString("\"snapshot\":{");
  SerializeSnapshot();
  if (writer_->aborted()) return;
  writer_->AddString("},\n");
  writer_->AddString("\"nodes\":[");
  SerializeNodes();
  if (writer_->aborted()) return;
  writer_->AddString("],\n");
  writer_->AddString("\"edges\":[");
  SerializeEdges();
  if (writer_->aborted()) return;
  writer_->AddString("],\n");
  writer_->AddString("\"trace_function_infos\":[");
  SerializeTraceNodeInfos();
  if (writer_->aborted()) return;
  writer_->AddString("],\n");
  writer_->AddString("\"trace_tree\":[");
  SerializeTraceTree();
  if (writer_->aborted()) return;
  writer_->AddString("],\n");
  writer_->AddString("\"samples\":[");
  SerializeSamples();
  if (writer_->aborted()) return;
  writer_->AddString("],\n");
  writer_->AddString("\"locations\":[");
  SerializeLocations();
  if (writer_->aborted()) return;
  writer_->AddString("],\n");
  writer_->AddString("\"strings\":[");
  SerializeStrings();
  if (writer_->aborted()) return;
  writer_->AddCharacter(']');
  writer_->AddCharacter('}');
  writer_->Finalize();
}
References v8::internal::OutputStreamWriter::aborted(), v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::OutputStreamWriter::AddString(), DCHECK_EQ, v8::internal::OutputStreamWriter::Finalize(), v8::internal::HeapEntry::index(), v8::internal::HeapSnapshot::root(), SerializeEdges(), SerializeLocations(), SerializeNodes(), SerializeSamples(), SerializeSnapshot(), SerializeStrings(), SerializeTraceNodeInfos(), SerializeTraceTree(), snapshot_, and writer_.
Referenced by Serialize().
SerializeLocation()
void v8::internal::HeapSnapshotJSONSerializer::SerializeLocation (const EntrySourceLocation & location) [private]
Definition at line 3749 of file heap-snapshot-generator.cc.
                                         {
  writer_->AddNumber(to_node_index(location.entry_index));
  writer_->AddCharacter(',');
  writer_->AddNumber(location.scriptId);
  writer_->AddCharacter(',');
  writer_->AddNumber(location.line);
  writer_->AddCharacter(',');
  writer_->AddNumber(location.col);
}
References v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::OutputStreamWriter::AddNumber(), v8::internal::EntrySourceLocation::col, v8::internal::EntrySourceLocation::entry_index, v8::internal::EntrySourceLocation::line, v8::internal::EntrySourceLocation::scriptId, to_node_index(), and writer_.
Referenced by SerializeLocations().
SerializeLocations()
void v8::internal::HeapSnapshotJSONSerializer::SerializeLocations () [private]
Definition at line 3760 of file heap-snapshot-generator.cc.
                                                    {
  const std::vector<EntrySourceLocation>& locations = snapshot_->locations();
  for (size_t i = 0; i < locations.size(); i++) {
    if (i > 0) writer_->AddCharacter(',');
    SerializeLocation(locations[i]);
    if (writer_->aborted()) return;
  }
}
References v8::internal::OutputStreamWriter::aborted(), v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::HeapSnapshot::locations(), SerializeLocation(), snapshot_, and writer_.
Referenced by SerializeImpl().
SerializeNode()
void v8::internal::HeapSnapshotJSONSerializer::SerializeNode (const HeapEntry * entry) [private]
Definition at line 3483 of file heap-snapshot-generator.cc.
                                                                     {
  if (to_node_index(entry) != 0) {
    writer_->AddCharacter(',');
  }
  writer_->AddNumber(static_cast<int>(entry->type()));
  writer_->AddCharacter(',');
  writer_->AddNumber(GetStringId(entry->name()));
  writer_->AddCharacter(',');
  writer_->AddNumber(entry->id());
  writer_->AddCharacter(',');
  writer_->AddNumber(entry->self_size());
  writer_->AddCharacter(',');
  writer_->AddNumber(entry->children_count());
  writer_->AddCharacter(',');
  if (trace_function_count_) {
    writer_->AddNumber(entry->trace_node_id());
    writer_->AddCharacter(',');
  } else {
    CHECK_EQ(0, entry->trace_node_id());
  }
  writer_->AddNumber(entry->detachedness());
}
References v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::OutputStreamWriter::AddNumber(), CHECK_EQ, v8::internal::HeapEntry::children_count(), v8::internal::HeapEntry::detachedness(), GetStringId(), v8::internal::HeapEntry::id(), v8::internal::HeapEntry::name(), v8::internal::HeapEntry::self_size(), to_node_index(), trace_function_count_, v8::internal::HeapEntry::trace_node_id(), v8::internal::HeapEntry::type(), and writer_.
Referenced by SerializeNodes().
SerializeNodes()
void v8::internal::HeapSnapshotJSONSerializer::SerializeNodes () [private]
Definition at line 3506 of file heap-snapshot-generator.cc.
                                                {
  const std::deque<HeapEntry>& entries = snapshot_->entries();
  for (const HeapEntry& entry : entries) {
    SerializeNode(&entry);
    if (writer_->aborted()) return;
  }
}
References v8::internal::OutputStreamWriter::aborted(), v8::internal::HeapSnapshot::entries(), SerializeNode(), snapshot_, and writer_.
Referenced by SerializeImpl().
SerializeSamples()
void v8::internal::HeapSnapshotJSONSerializer::SerializeSamples () [private]
Definition at line 3667 of file heap-snapshot-generator.cc.
                                                  {
  const std::vector<HeapObjectsMap::TimeInterval>& samples =
      snapshot_->profiler()->heap_object_map()->samples();
  if (samples.empty()) return;
  base::TimeTicks start_time = samples[0].timestamp;
  int i = 0;
  for (const HeapObjectsMap::TimeInterval& sample : samples) {
    if (i++ > 0) {
      writer_->AddCharacter(',');
    }
    base::TimeDelta time_delta = sample.timestamp - start_time;
    writer_->AddNumber(time_delta.InMicroseconds());
    writer_->AddCharacter(',');
    writer_->AddNumber(sample.last_assigned_id());
  }
}
References v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::OutputStreamWriter::AddNumber(), v8::internal::HeapProfiler::heap_object_map(), v8::base::TimeDelta::InMicroseconds(), v8::internal::HeapSnapshot::profiler(), v8::internal::HeapObjectsMap::samples(), snapshot_, and writer_.
Referenced by SerializeImpl().
SerializeSnapshot()
void v8::internal::HeapSnapshotJSONSerializer::SerializeSnapshot () [private]
Definition at line 3514 of file heap-snapshot-generator.cc.
                                                   {
  writer_->AddString("\"meta\":");
  // The object describing node serialization layout.
  // We use a set of macros to improve readability.
  // clang-format off
#define JSON_A(s) "[" s "]"
#define JSON_S(s) "\"" s "\""
  writer_->AddString("{"
    JSON_S("node_fields") ":["
        JSON_S("type") ","
        JSON_S("name") ","
        JSON_S("id") ","
        JSON_S("self_size") ","
        JSON_S("edge_count") ",");
  if (trace_function_count_) writer_->AddString(JSON_S("trace_node_id") ",");
  writer_->AddString(
        JSON_S("detachedness")
    "],"
    JSON_S("node_types") ":["
        JSON_A(
            JSON_S("hidden") ","
            JSON_S("array") ","
            JSON_S("string") ","
            JSON_S("object") ","
            JSON_S("code") ","
            JSON_S("closure") ","
            JSON_S("regexp") ","
            JSON_S("number") ","
            JSON_S("native") ","
            JSON_S("synthetic") ","
            JSON_S("concatenated string") ","
            JSON_S("sliced string") ","
            JSON_S("symbol") ","
            JSON_S("bigint") ","
            JSON_S("object shape")) ","
        JSON_S("string") ",");
  if (trace_function_count_) writer_->AddString(JSON_S("number") ",");
  writer_->AddString(
        JSON_S("number") ","
        JSON_S("number") ","
        JSON_S("number") ","
        JSON_S("number")
      "],"
    JSON_S("edge_fields") ":" JSON_A(
        JSON_S("type") ","
        JSON_S("name_or_index") ","
        JSON_S("to_node")) ","
    JSON_S("edge_types") ":" JSON_A(
        JSON_A(
            JSON_S("context") ","
            JSON_S("element") ","
            JSON_S("property") ","
            JSON_S("internal") ","
            JSON_S("hidden") ","
            JSON_S("shortcut") ","
            JSON_S("weak")) ","
        JSON_S("string_or_number") ","
        JSON_S("node")) ","
    JSON_S("trace_function_info_fields") ":" JSON_A(
        JSON_S("function_id") ","
        JSON_S("name") ","
        JSON_S("script_name") ","
        JSON_S("script_id") ","
        JSON_S("line") ","
        JSON_S("column")) ","
    JSON_S("trace_node_fields") ":" JSON_A(
        JSON_S("id") ","
        JSON_S("function_info_index") ","
        JSON_S("count") ","
        JSON_S("size") ","
        JSON_S("children")) ","
    JSON_S("sample_fields") ":" JSON_A(
        JSON_S("timestamp_us") ","
        JSON_S("last_assigned_id")) ","
    JSON_S("location_fields") ":" JSON_A(
        JSON_S("object_index") ","
        JSON_S("script_id") ","
        JSON_S("line") ","
        JSON_S("column"))
  "}");
// clang-format on
#undef JSON_S
#undef JSON_A
  writer_->AddString(",\"node_count\":");
  writer_->AddNumber(snapshot_->entries().size());
  writer_->AddString(",\"edge_count\":");
  writer_->AddNumber(snapshot_->edges().size());
  writer_->AddString(",\"trace_function_count\":");
  writer_->AddNumber(trace_function_count_);
  writer_->AddString(",\"extra_native_bytes\":");
  writer_->AddNumber(snapshot_->extra_native_bytes());
}
References v8::internal::OutputStreamWriter::AddNumber(), v8::internal::OutputStreamWriter::AddString(), v8::internal::HeapSnapshot::edges(), v8::internal::HeapSnapshot::entries(), v8::internal::HeapSnapshot::extra_native_bytes(), JSON_A, JSON_S, snapshot_, trace_function_count_, and writer_.
Referenced by SerializeImpl().
SerializeString()
void v8::internal::HeapSnapshotJSONSerializer::SerializeString (const unsigned char * s) [private]
Definition at line 3684 of file heap-snapshot-generator.cc.
                                                                       {
  writer_->AddCharacter('\"');
  for (; *s != '\0'; ++s) {
    switch (*s) {
      case '\b':
        writer_->AddString("\\b");
        continue;
      case '\f':
        writer_->AddString("\\f");
        continue;
      case '\n':
        writer_->AddString("\\n");
        continue;
      case '\r':
        writer_->AddString("\\r");
        continue;
      case '\t':
        writer_->AddString("\\t");
        continue;
      case '\"':
      case '\\':
        writer_->AddCharacter('\\');
        writer_->AddCharacter(*s);
        continue;
      default:
        if (*s > 31 && *s < 128) {
          writer_->AddCharacter(*s);
        } else if (*s <= 31) {
          // Special character with no dedicated literal.
          WriteUChar(writer_, *s);
        } else {
          // Convert UTF-8 into \u UTF-16 literal.
          size_t length = 1, cursor = 0;
          for (; length <= 4 && *(s + length) != '\0'; ++length) {
          }
          unibrow::uchar c = unibrow::Utf8::CalculateValue(s, length, &cursor);
          if (c != unibrow::Utf8::kBadChar) {
            WriteUChar(writer_, c);
            DCHECK_NE(cursor, 0);
            s += cursor - 1;
          } else {
            writer_->AddCharacter('?');
          }
        }
    }
  }
  writer_->AddCharacter('\"');
}
References v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::OutputStreamWriter::AddString(), unibrow::Utf8::CalculateValue(), DCHECK_NE, unibrow::Utf8::kBadChar, v8::internal::length, writer_, and v8::internal::WriteUChar().
Referenced by SerializeStrings().
SerializeStrings()
void v8::internal::HeapSnapshotJSONSerializer::SerializeStrings () [private]
Definition at line 3733 of file heap-snapshot-generator.cc.
                                                  {
  base::ScopedVector<const unsigned char*> sorted_strings(strings_.occupancy() +
                                                          1);
  for (base::HashMap::Entry* entry = strings_.Start(); entry != nullptr;
       entry = strings_.Next(entry)) {
    int index = static_cast<int>(reinterpret_cast<uintptr_t>(entry->value));
    sorted_strings[index] = reinterpret_cast<const unsigned char*>(entry->key);
  }
  writer_->AddString("\"<dummy>\"");
  for (int i = 1; i < sorted_strings.length(); ++i) {
    writer_->AddCharacter(',');
    SerializeString(sorted_strings[i]);
    if (writer_->aborted()) return;
  }
}
References v8::internal::OutputStreamWriter::aborted(), v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::OutputStreamWriter::AddString(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::base::Vector< T >::length(), SerializeString(), strings_, and writer_.
Referenced by SerializeImpl().
SerializeTraceNode()
void v8::internal::HeapSnapshotJSONSerializer::SerializeTraceNode (AllocationTraceNode * node) [private]
Definition at line 3624 of file heap-snapshot-generator.cc.
                                                                             {
  writer_->AddNumber(node->id());
  writer_->AddCharacter(',');
  writer_->AddNumber(node->function_info_index());
  writer_->AddCharacter(',');
  writer_->AddNumber(node->allocation_count());
  writer_->AddCharacter(',');
  writer_->AddNumber(node->allocation_size());
  writer_->AddCharacter(',');
  writer_->AddCharacter('[');
  int i = 0;
  for (AllocationTraceNode* child : node->children()) {
    if (i++ > 0) {
      writer_->AddCharacter(',');
    }
    SerializeTraceNode(child);
  }
  writer_->AddCharacter(']');
}
References v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::OutputStreamWriter::AddNumber(), v8::internal::AllocationTraceNode::allocation_count(), v8::internal::AllocationTraceNode::allocation_size(), v8::internal::AllocationTraceNode::children(), v8::internal::AllocationTraceNode::function_info_index(), v8::internal::AllocationTraceNode::id(), and writer_.
Referenced by SerializeTraceTree().
SerializeTraceNodeInfos()
void v8::internal::HeapSnapshotJSONSerializer::SerializeTraceNodeInfos () [private]
Definition at line 3644 of file heap-snapshot-generator.cc.
                                                         {
  AllocationTracker* tracker = snapshot_->profiler()->allocation_tracker();
  if (!tracker) return;
  int i = 0;
  for (AllocationTracker::FunctionInfo* info : tracker->function_info_list()) {
    if (i++ > 0) {
      writer_->AddCharacter(',');
    }
    writer_->AddNumber(info->function_id);
    writer_->AddCharacter(',');
    writer_->AddNumber(GetStringId(info->name));
    writer_->AddCharacter(',');
    writer_->AddNumber(GetStringId(info->script_name));
    writer_->AddCharacter(',');
    writer_->AddNumber(info->script_id);
    // 0-based positions are converted to 1-based during serialization.
    writer_->AddCharacter(',');
    writer_->AddNumber(info->line + 1);
    writer_->AddCharacter(',');
    writer_->AddNumber(info->column + 1);
  }
}
References v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::OutputStreamWriter::AddNumber(), v8::internal::HeapProfiler::allocation_tracker(), v8::internal::AllocationTracker::function_info_list(), GetStringId(), v8::internal::HeapSnapshot::profiler(), snapshot_, and writer_.
Referenced by SerializeImpl().
SerializeTraceTree()
void v8::internal::HeapSnapshotJSONSerializer::SerializeTraceTree () [private]
Definition at line 3617 of file heap-snapshot-generator.cc.
                                                    {
  AllocationTracker* tracker = snapshot_->profiler()->allocation_tracker();
  if (!tracker) return;
  AllocationTraceTree* traces = tracker->trace_tree();
  SerializeTraceNode(traces->root());
}
References v8::internal::HeapProfiler::allocation_tracker(), v8::internal::HeapSnapshot::profiler(), v8::internal::AllocationTraceTree::root(), SerializeTraceNode(), snapshot_, and v8::internal::AllocationTracker::trace_tree().
Referenced by SerializeImpl().
StringHash()
uint32_t v8::internal::HeapSnapshotJSONSerializer::StringHash (const void * string) [inline], [static], [private]
Definition at line 56 of file heap-snapshot-generator-inl.h.
                                                                  {
  const char* s = reinterpret_cast<const char*>(string);
  int len = static_cast<int>(strlen(s));
  return StringHasher::HashSequentialString(s, len,
                                            v8::internal::kZeroHashSeed);
}
References v8::internal::StringHasher::HashSequentialString(), v8::internal::kZeroHashSeed, and v8::internal::string.
Referenced by GetStringId().
StringsMatch()
static bool v8::internal::HeapSnapshotJSONSerializer::StringsMatch (void * key1, void * key2) [inline], [static], [private]
Definition at line 765 of file heap-snapshot-generator.h.
                                                             {
    return strcmp(reinterpret_cast<char*>(key1),
                  reinterpret_cast<char*>(key2)) == 0;
  }
to_node_index() [1/2]
int v8::internal::HeapSnapshotJSONSerializer::to_node_index (const HeapEntry * e) [inline], [private]
Definition at line 63 of file heap-snapshot-generator-inl.h.
                                                                {
  return to_node_index(e->index());
}
References v8::internal::HeapEntry::index().
Referenced by SerializeEdge(), SerializeLocation(), and SerializeNode().
to_node_index() [2/2]
int v8::internal::HeapSnapshotJSONSerializer::to_node_index (int entry_index) [inline], [private]
Definition at line 67 of file heap-snapshot-generator-inl.h.
                                                             {
  return entry_index * (trace_function_count_
                            ? kNodeFieldsCountWithTraceNodeId
                            : kNodeFieldsCountWithoutTraceNodeId);
}
References kNodeFieldsCountWithoutTraceNodeId, kNodeFieldsCountWithTraceNodeId, and trace_function_count_.
Friends And Related Function Documentation
HeapSnapshotJSONSerializerEnumerator
friend class HeapSnapshotJSONSerializerEnumerator [friend]
Definition at line 801 of file heap-snapshot-generator.h.
HeapSnapshotJSONSerializerIterator
friend class HeapSnapshotJSONSerializerIterator [friend]
Definition at line 802 of file heap-snapshot-generator.h.
Member Data Documentation
kEdgeFieldsCount
const int v8::internal::HeapSnapshotJSONSerializer::kEdgeFieldsCount [static], [private]
Definition at line 790 of file heap-snapshot-generator.h.
kNodeFieldsCountWithoutTraceNodeId
const int v8::internal::HeapSnapshotJSONSerializer::kNodeFieldsCountWithoutTraceNodeId = 6 [static], [private]
Definition at line 792 of file heap-snapshot-generator.h.
Referenced by to_node_index().
kNodeFieldsCountWithTraceNodeId
const int v8::internal::HeapSnapshotJSONSerializer::kNodeFieldsCountWithTraceNodeId = 7 [static], [private]
Definition at line 791 of file heap-snapshot-generator.h.
Referenced by to_node_index().
next_node_id_
int v8::internal::HeapSnapshotJSONSerializer::next_node_id_ [private]
Definition at line 796 of file heap-snapshot-generator.h.
next_string_id_
int v8::internal::HeapSnapshotJSONSerializer::next_string_id_ [private]
Definition at line 797 of file heap-snapshot-generator.h.
Referenced by GetStringId().
snapshot_
HeapSnapshot* v8::internal::HeapSnapshotJSONSerializer::snapshot_ [private]
Definition at line 794 of file heap-snapshot-generator.h.
Referenced by Serialize(), SerializeEdges(), SerializeImpl(), SerializeLocations(), SerializeNodes(), SerializeSamples(), SerializeSnapshot(), SerializeTraceNodeInfos(), and SerializeTraceTree().
strings_
base::CustomMatcherHashMap v8::internal::HeapSnapshotJSONSerializer::strings_ [private]
Definition at line 795 of file heap-snapshot-generator.h.
Referenced by GetStringId(), and SerializeStrings().
trace_function_count_
uint32_t v8::internal::HeapSnapshotJSONSerializer::trace_function_count_ = 0 [private]
Definition at line 799 of file heap-snapshot-generator.h.
Referenced by Serialize(), SerializeNode(), SerializeSnapshot(), and to_node_index().
writer_
OutputStreamWriter* v8::internal::HeapSnapshotJSONSerializer::writer_ [private]
Definition at line 798 of file heap-snapshot-generator.h.
Referenced by Serialize(), SerializeEdge(), SerializeEdges(), SerializeImpl(), SerializeLocation(), SerializeLocations(), SerializeNode(), SerializeNodes(), SerializeSamples(), SerializeSnapshot(), SerializeString(), SerializeStrings(), SerializeTraceNode(), and SerializeTraceNodeInfos().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.h
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator-inl.h
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.cc