v8::internal::compiler::SimplifiedOperatorReducer Class Reference
#include <simplified-operator-reducer.h>
Public Member Functions
SimplifiedOperatorReducer (Editor *editor, JSGraph *jsgraph, JSHeapBroker *broker, BranchSemantics branch_semantics)
~SimplifiedOperatorReducer () final
SimplifiedOperatorReducer (const SimplifiedOperatorReducer &)=delete
SimplifiedOperatorReducer & operator= (const SimplifiedOperatorReducer &)=delete
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Member Functions
Reduction Change (Node *node, const Operator *op, Node *a)
Reduction ReplaceBoolean (bool value)
Reduction ReplaceFloat64 (double value)
Reduction ReplaceInt32 (int32_t value)
Reduction ReplaceUint32 (uint32_t value)
Reduction ReplaceNumber (double value)
Reduction ReplaceNumber (int32_t value)
Factory * factory () const
TFGraph * graph () const
MachineOperatorBuilder * machine () const
SimplifiedOperatorBuilder * simplified () const
JSGraph * jsgraph () const
JSHeapBroker * broker () const
Private Attributes
JSGraph *const jsgraph_
JSHeapBroker *const broker_
BranchSemantics branch_semantics_
Detailed Description
Definition at line 26 of file simplified-operator-reducer.h.
Constructor & Destructor Documentation
SimplifiedOperatorReducer() [1/2]
v8::internal::compiler::SimplifiedOperatorReducer::SimplifiedOperatorReducer (Editor * editor, JSGraph * jsgraph, JSHeapBroker * broker, BranchSemantics branch_semantics)
Definition at line 39 of file simplified-operator-reducer.cc.
    : AdvancedReducer(editor),
      jsgraph_(jsgraph),
      broker_(broker),
      branch_semantics_(branch_semantics) {}
 SimplifiedOperatorReducer()
v8::internal::compiler::SimplifiedOperatorReducer::~SimplifiedOperatorReducer () [final], [default]
SimplifiedOperatorReducer() [2/2]
v8::internal::compiler::SimplifiedOperatorReducer::SimplifiedOperatorReducer (const SimplifiedOperatorReducer &) [delete]
Member Function Documentation
broker()
JSHeapBroker* v8::internal::compiler::SimplifiedOperatorReducer::broker () const [inline], [private]
Definition at line 60 of file simplified-operator-reducer.h.
{ return broker_; }
Referenced by Reduce().
Change()
Reduction v8::internal::compiler::SimplifiedOperatorReducer::Change (Node * node, const Operator * op, Node * a) [private]
Definition at line 290 of file simplified-operator-reducer.cc.
                                                     {
  DCHECK_EQ(node->InputCount(), OperatorProperties::GetTotalInputCount(op));
  DCHECK_LE(1, node->InputCount());
  node->ReplaceInput(0, a);
  NodeProperties::ChangeOp(node, op);
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, DCHECK_LE, v8::internal::compiler::OperatorProperties::GetTotalInputCount(), v8::internal::compiler::Node::InputCount(), and v8::internal::compiler::Node::ReplaceInput().
Referenced by Reduce().
factory()
Factory * v8::internal::compiler::SimplifiedOperatorReducer::factory () const [private]
Definition at line 326 of file simplified-operator-reducer.cc.
                                                  {
  return jsgraph()->isolate()->factory();
}
References v8::internal::Isolate::factory(), v8::internal::compiler::JSGraph::isolate(), and jsgraph().
Referenced by Reduce().
graph()
TFGraph * v8::internal::compiler::SimplifiedOperatorReducer::graph () const [private]
Definition at line 330 of file simplified-operator-reducer.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
jsgraph()
JSGraph* v8::internal::compiler::SimplifiedOperatorReducer::jsgraph () const [inline], [private]
Definition at line 59 of file simplified-operator-reducer.h.
{ return jsgraph_; }
Referenced by factory(), graph(), machine(), Reduce(), ReplaceBoolean(), ReplaceFloat64(), ReplaceInt32(), ReplaceNumber(), and simplified().
machine()
MachineOperatorBuilder * v8::internal::compiler::SimplifiedOperatorReducer::machine () const [private]
Definition at line 332 of file simplified-operator-reducer.cc.
                                                                 {
  return jsgraph()->machine();
}
References jsgraph(), and v8::internal::compiler::MachineGraph::machine().
Referenced by Reduce().
operator=()
SimplifiedOperatorReducer& v8::internal::compiler::SimplifiedOperatorReducer::operator= (const SimplifiedOperatorReducer &) [delete]
Reduce()
Reduction v8::internal::compiler::SimplifiedOperatorReducer::Reduce (Node * node) [final]
Definition at line 50 of file simplified-operator-reducer.cc.
                                                      {
  switch (node->opcode()) {
    case IrOpcode::kBooleanNot: {
      HeapObjectMatcher m(node->InputAt(0));
      if (m.Is(factory()->true_value())) return ReplaceBoolean(false);
      if (m.Is(factory()->false_value())) return ReplaceBoolean(true);
      if (m.IsBooleanNot()) return Replace(m.InputAt(0));
      break;
    }
    case IrOpcode::kChangeBitToTagged: {
      Int32Matcher m(node->InputAt(0));
      if (m.Is(0)) return Replace(jsgraph()->FalseConstant());
      if (m.Is(1)) return Replace(jsgraph()->TrueConstant());
      if (m.IsChangeTaggedToBit()) return Replace(m.InputAt(0));
      break;
    }
    case IrOpcode::kChangeTaggedToBit: {
      HeapObjectMatcher m(node->InputAt(0));
      if (m.HasResolvedValue()) {
        std::optional<bool> maybe_result =
            m.Ref(broker()).TryGetBooleanValue(broker());
        if (maybe_result.has_value()) return ReplaceInt32(*maybe_result);
      }
      if (m.IsChangeBitToTagged()) return Replace(m.InputAt(0));
      break;
    }
    case IrOpcode::kChangeFloat64ToTagged: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue()) return ReplaceNumber(m.ResolvedValue());
      if (m.IsChangeTaggedToFloat64()) return Replace(m.node()->InputAt(0));
      break;
    }
    case IrOpcode::kChangeFloat64OrUndefinedToTagged: {
      // TODO(385155404): Handle some constants here.
      break;
    }
    case IrOpcode::kChangeInt31ToTaggedSigned:
    case IrOpcode::kChangeInt32ToTagged: {
      Int32Matcher m(node->InputAt(0));
      if (m.HasResolvedValue()) return ReplaceNumber(m.ResolvedValue());
      if (m.IsChangeTaggedSignedToInt32()) {
        return Replace(m.InputAt(0));
      }
      break;
    }
    case IrOpcode::kChangeTaggedToFloat64:
    case IrOpcode::kTruncateTaggedToFloat64: {
      NumberMatcher m(node->InputAt(0));
      if (m.HasResolvedValue()) return ReplaceFloat64(m.ResolvedValue());
      // TODO(385155404): Consider handling ChangeFloat64OrUndefinedToTagged
      // here.
      if (m.IsChangeFloat64ToTagged() || m.IsChangeFloat64ToTaggedPointer()) {
        return Replace(m.node()->InputAt(0));
      }
      if (m.IsChangeInt31ToTaggedSigned() || m.IsChangeInt32ToTagged()) {
        return Change(node, machine()->ChangeInt32ToFloat64(), m.InputAt(0));
      }
      if (m.IsChangeUint32ToTagged()) {
        return Change(node, machine()->ChangeUint32ToFloat64(), m.InputAt(0));
      }
      break;
    }
    case IrOpcode::kChangeTaggedSignedToInt32:
    case IrOpcode::kChangeTaggedToInt32: {
      NumberMatcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceInt32(DoubleToInt32(m.ResolvedValue()));
      // TODO(385155404): Consider handling ChangeFloat64OrUndefinedToTagged
      // here.
      if (m.IsChangeFloat64ToTagged() || m.IsChangeFloat64ToTaggedPointer()) {
        return Change(node, machine()->ChangeFloat64ToInt32(), m.InputAt(0));
      }
      if (m.IsChangeInt31ToTaggedSigned() || m.IsChangeInt32ToTagged()) {
        return Replace(m.InputAt(0));
      }
      break;
    }
    case IrOpcode::kChangeTaggedToUint32: {
      NumberMatcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceUint32(DoubleToUint32(m.ResolvedValue()));
      // TODO(385155404): Consider handling ChangeFloat64OrUndefinedToTagged
      // here.
      if (m.IsChangeFloat64ToTagged() || m.IsChangeFloat64ToTaggedPointer()) {
        return Change(node, machine()->ChangeFloat64ToUint32(), m.InputAt(0));
      }
      if (m.IsChangeUint32ToTagged()) return Replace(m.InputAt(0));
      break;
    }
    case IrOpcode::kChangeUint32ToTagged: {
      Uint32Matcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceNumber(FastUI2D(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kTruncateTaggedToWord32: {
      NumberMatcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceInt32(DoubleToInt32(m.ResolvedValue()));
      if (m.IsChangeInt31ToTaggedSigned() || m.IsChangeInt32ToTagged() ||
          m.IsChangeUint32ToTagged()) {
        return Replace(m.InputAt(0));
      }
      // TODO(385155404): Consider handling ChangeFloat64OrUndefinedToTagged
      // here.
      if (m.IsChangeFloat64ToTagged() || m.IsChangeFloat64ToTaggedPointer()) {
        return Change(node, machine()->TruncateFloat64ToWord32(), m.InputAt(0));
      }
      break;
    }
    case IrOpcode::kCheckedFloat64ToInt32: {
      Float64Matcher m(node->InputAt(0));
      if (m.HasResolvedValue() && IsInt32Double(m.ResolvedValue())) {
        Node* value =
            jsgraph()->Int32Constant(static_cast<int32_t>(m.ResolvedValue()));
        ReplaceWithValue(node, value);
        return Replace(value);
      }
      break;
    }
    case IrOpcode::kCheckedTaggedToArrayIndex:
    case IrOpcode::kCheckedTaggedToInt32:
    case IrOpcode::kCheckedTaggedSignedToInt32: {
      NodeMatcher m(node->InputAt(0));
      if (m.IsConvertTaggedHoleToUndefined()) {
        node->ReplaceInput(0, m.InputAt(0));
        return Changed(node);
      }
      break;
    }
    case IrOpcode::kCheckIf: {
      HeapObjectMatcher m(node->InputAt(0));
      if (m.Is(factory()->true_value())) {
        Node* const effect = NodeProperties::GetEffectInput(node);
        return Replace(effect);
      }
      break;
    }
    case IrOpcode::kCheckNumberFitsInt32:
    case IrOpcode::kCheckNumber: {
      NodeMatcher m(node->InputAt(0));
      if (m.IsConvertTaggedHoleToUndefined()) {
        node->ReplaceInput(0, m.InputAt(0));
        return Changed(node);
      }
      break;
    }
    case IrOpcode::kCheckHeapObject: {
      Node* const input = node->InputAt(0);
      if (DecideObjectIsSmi(input) == Decision::kFalse) {
        ReplaceWithValue(node, input);
        return Replace(input);
      }
      NodeMatcher m(input);
      if (m.IsCheckHeapObject()) {
        ReplaceWithValue(node, input);
        return Replace(input);
      }
      break;
    }
    case IrOpcode::kCheckSmi: {
      Node* const input = node->InputAt(0);
      if (DecideObjectIsSmi(input) == Decision::kTrue) {
        ReplaceWithValue(node, input);
        return Replace(input);
      }
      NodeMatcher m(input);
      if (m.IsCheckSmi()) {
        ReplaceWithValue(node, input);
        return Replace(input);
      } else if (m.IsConvertTaggedHoleToUndefined()) {
        node->ReplaceInput(0, m.InputAt(0));
        return Changed(node);
      }
      break;
    }
    case IrOpcode::kObjectIsSmi: {
      Node* const input = node->InputAt(0);
      switch (DecideObjectIsSmi(input)) {
        case Decision::kTrue:
          return ReplaceBoolean(true);
        case Decision::kFalse:
          return ReplaceBoolean(false);
        case Decision::kUnknown:
          break;
      }
      break;
    }
    case IrOpcode::kNumberAbs: {
      NumberMatcher m(node->InputAt(0));
      if (m.HasResolvedValue())
        return ReplaceNumber(std::fabs(m.ResolvedValue()));
      break;
    }
    case IrOpcode::kReferenceEqual: {
      HeapObjectBinopMatcher m(node);
      if (m.left().node() == m.right().node()) return ReplaceBoolean(true);
      break;
    }
    case IrOpcode::kCheckedInt32Add: {
      // (x + a) + b => x + (a + b) where a and b are constants and have the
      // same sign.
      Int32BinopMatcher m(node);
      if (m.right().HasResolvedValue()) {
        Node* checked_int32_add = m.left().node();
        if (checked_int32_add->opcode() == IrOpcode::kCheckedInt32Add) {
          Int32BinopMatcher n(checked_int32_add);
          if (n.right().HasResolvedValue() &&
              (n.right().ResolvedValue() >= 0) ==
                  (m.right().ResolvedValue() >= 0)) {
            int32_t val;
            bool overflow = base::bits::SignedAddOverflow32(
                n.right().ResolvedValue(), m.right().ResolvedValue(), &val);
            if (!overflow) {
              bool has_no_other_uses = true;
              for (Edge edge : checked_int32_add->use_edges()) {
                if (!edge.from()->IsDead() && edge.from() != node) {
                  has_no_other_uses = false;
                  break;
                }
              }
              if (has_no_other_uses) {
                node->ReplaceInput(0, n.left().node());
                node->ReplaceInput(1, jsgraph()->Int32Constant(val));
                RelaxEffectsAndControls(checked_int32_add);
                checked_int32_add->Kill();
                return Changed(node);
              }
            }
          }
        }
      }
      break;
    }
    default:
      break;
  }
  return NoChange();
}
References broker(), Change(), v8::internal::compiler::anonymous_namespace{simplified-operator-reducer.cc}::DecideObjectIsSmi(), v8::internal::DoubleToInt32(), v8::internal::DoubleToUint32(), factory(), v8::internal::FastUI2D(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::NodeMatcher::InputAt(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::MachineGraph::Int32Constant(), v8::internal::compiler::IntMatcher< T, kOpcode >::Is(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Is(), v8::internal::IsInt32Double(), jsgraph(), v8::internal::compiler::kFalse, v8::internal::compiler::Node::Kill(), v8::internal::compiler::kTrue, v8::internal::compiler::kUnknown, v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), machine(), v8::internal::compiler::NodeMatcher::node(), v8::internal::compiler::Node::opcode(), v8::internal::overflow, v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), ReplaceBoolean(), ReplaceFloat64(), v8::internal::compiler::Node::ReplaceInput(), ReplaceInt32(), ReplaceNumber(), ReplaceUint32(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::right(), v8::base::bits::SignedAddOverflow32(), v8::internal::compiler::Node::use_edges(), and v8::internal::value.
reducer_name()
const char* v8::internal::compiler::SimplifiedOperatorReducer::reducer_name () const [inline], [override]
Definition at line 37 of file simplified-operator-reducer.h.
                                            {
    return "SimplifiedOperatorReducer";
  }
ReplaceBoolean()
Reduction v8::internal::compiler::SimplifiedOperatorReducer::ReplaceBoolean (bool value) [private]
Definition at line 299 of file simplified-operator-reducer.cc.
                                                              {
  if (branch_semantics_ == BranchSemantics::kJS) {
    return Replace(jsgraph()->BooleanConstant(value));
  } else {
    return ReplaceInt32(value);
  }
}
References branch_semantics_, jsgraph(), v8::internal::compiler::kJS, v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), ReplaceInt32(), and v8::internal::value.
Referenced by Reduce().
ReplaceFloat64()
Reduction v8::internal::compiler::SimplifiedOperatorReducer::ReplaceFloat64 (double value) [private]
Definition at line 307 of file simplified-operator-reducer.cc.
                                                                {
  return Replace(jsgraph()->Float64Constant(value));
}
References jsgraph(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::value.
Referenced by Reduce().
ReplaceInt32()
Reduction v8::internal::compiler::SimplifiedOperatorReducer::ReplaceInt32 (int32_t value) [private]
Definition at line 312 of file simplified-operator-reducer.cc.
                                                               {
  return Replace(jsgraph()->Int32Constant(value));
}
References jsgraph(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::value.
Referenced by Reduce(), and ReplaceBoolean().
ReplaceNumber() [1/2]
Reduction v8::internal::compiler::SimplifiedOperatorReducer::ReplaceNumber (double value) [private]
Definition at line 317 of file simplified-operator-reducer.cc.
                                                               {
  return Replace(jsgraph()->ConstantNoHole(value));
}
References jsgraph(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::value.
Referenced by Reduce().
ReplaceNumber() [2/2]
Reduction v8::internal::compiler::SimplifiedOperatorReducer::ReplaceNumber (int32_t value) [private]
Definition at line 322 of file simplified-operator-reducer.cc.
                                                                {
  return Replace(jsgraph()->ConstantNoHole(value));
}
References jsgraph(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::value.
ReplaceUint32()
Reduction v8::internal::compiler::SimplifiedOperatorReducer::ReplaceUint32 (uint32_t value) [inline], [private]
Definition at line 48 of file simplified-operator-reducer.h.
                                          {
    return ReplaceInt32(base::bit_cast<int32_t>(value));
  }
References v8::internal::value.
Referenced by Reduce().
simplified()
SimplifiedOperatorBuilder * v8::internal::compiler::SimplifiedOperatorReducer::simplified () const [private]
Definition at line 336 of file simplified-operator-reducer.cc.
                                                                       {
  return jsgraph()->simplified();
}
References jsgraph(), and v8::internal::compiler::JSGraph::simplified().
Member Data Documentation
branch_semantics_
BranchSemantics v8::internal::compiler::SimplifiedOperatorReducer::branch_semantics_ [private]
Definition at line 64 of file simplified-operator-reducer.h.
Referenced by ReplaceBoolean().
broker_
JSHeapBroker* const v8::internal::compiler::SimplifiedOperatorReducer::broker_ [private]
Definition at line 63 of file simplified-operator-reducer.h.
jsgraph_
JSGraph* const v8::internal::compiler::SimplifiedOperatorReducer::jsgraph_ [private]
Definition at line 62 of file simplified-operator-reducer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/simplified-operator-reducer.h
/mnt/V8SourceCode/src/compiler/simplified-operator-reducer.cc