v8::internal::ThreadIsolation::JitPageReference Class Reference
#include <code-memory-access.h>
Public Member Functions
JitPageReference (class JitPage *page, Address address)
JitPageReference (JitPageReference &&) V8_NOEXCEPT=default
JitPageReference (const JitPageReference &)=delete
JitPageReference & operator= (const JitPageReference &)=delete
base::Address Address () const
size_t Size () const
base::Address End () const
JitAllocation & RegisterAllocation (base::Address addr, size_t size, JitAllocationType type)
JitAllocation & LookupAllocation (base::Address addr, size_t size, JitAllocationType type)
bool Contains (base::Address addr, size_t size, JitAllocationType type) const
void UnregisterAllocation (base::Address addr)
void UnregisterAllocationsExcept (base::Address start, size_t size, const std::vector< base::Address > &addr)
void UnregisterRange (base::Address addr, size_t size)
base::Address StartOfAllocationAt (base::Address inner_pointer)
std::pair< base::Address, JitAllocation & > AllocationContaining (base::Address addr)
bool Empty () const
void Shrink (class JitPage *tail)
void Expand (size_t offset)
void Merge (JitPageReference &next)
class JitPage * JitPage ()
Private Attributes
base::MutexGuard page_lock_
class JitPage * jit_page_
base::Address address_
Detailed Description
Definition at line 263 of file code-memory-access.h.
Constructor & Destructor Documentation
JitPageReference() [1/3]
v8::internal::ThreadIsolation::JitPageReference::JitPageReference (class JitPage * page, base::Address address)
Definition at line 283 of file code-memory-access.cc.
    : page_lock_(&jit_page->mutex_), jit_page_(jit_page), address_(address) {}
JitPageReference() [2/3]
v8::internal::ThreadIsolation::JitPageReference::JitPageReference (JitPageReference &&) [default]
JitPageReference() [3/3]
v8::internal::ThreadIsolation::JitPageReference::JitPageReference (const JitPageReference &) [delete]
Member Function Documentation
Address()
base::Address v8::internal::ThreadIsolation::JitPageReference::Address () const [inline]
Definition at line 270 of file code-memory-access.h.
{ return address_; }
Referenced by Merge(), v8::internal::ThreadIsolation::SplitJitPageLocked(), v8::internal::ThreadIsolation::TryLookupJitPageLocked(), and v8::internal::ThreadIsolation::UnregisterJitPage().
AllocationContaining()
std::pair< base::Address, ThreadIsolation::JitAllocation & > v8::internal::ThreadIsolation::JitPageReference::AllocationContaining (base::Address addr)
Definition at line 409 of file code-memory-access.cc.
                               {
  auto it = jit_page_->allocations_.upper_bound(inner_pointer);
  CHECK_NE(it, jit_page_->allocations_.begin());
  it--;
  size_t offset = inner_pointer - it->first;
  CHECK_GT(it->second.Size(), offset);
  return {it->first, it->second};
}
References CHECK_GT, and CHECK_NE.
Referenced by v8::internal::WritableJitPage::LookupAllocationContaining().
Contains()
bool v8::internal::ThreadIsolation::JitPageReference::Contains (base::Address addr, size_t size, JitAllocationType type) const
Definition at line 344 of file code-memory-access.cc.
                                                                               {
  auto it = jit_page_->allocations_.find(addr);
  return it != jit_page_->allocations_.end() && it->second.Size() == size &&
         it->second.Type() == type;
}
References size(), and v8::internal::tracing::type.
Empty()
bool v8::internal::ThreadIsolation::JitPageReference::Empty () const [inline]
Definition at line 288 of file code-memory-access.h.
{ return jit_page_->allocations_.empty(); }
End()
base::Address v8::internal::ThreadIsolation::JitPageReference::End () const [inline]
Definition at line 272 of file code-memory-access.h.
{ return Address() + Size(); }
Referenced by v8::internal::ThreadIsolation::TryLookupJitPageLocked().
Expand()
void v8::internal::ThreadIsolation::JitPageReference::Expand (size_t offset)
Definition at line 303 of file code-memory-access.cc.
                                                          {
  jit_page_->size_ += offset;
}
JitPage()
class JitPage* v8::internal::ThreadIsolation::JitPageReference::JitPage () [inline]
Definition at line 292 of file code-memory-access.h.
{ return jit_page_; }
Referenced by v8::internal::ThreadIsolation::UnregisterJitPage().
LookupAllocation()
ThreadIsolation::JitAllocation & v8::internal::ThreadIsolation::JitPageReference::LookupAllocation (base::Address addr, size_t size, JitAllocationType type)
Definition at line 334 of file code-memory-access.cc.
                                                                            {
  auto it = jit_page_->allocations_.find(addr);
  CHECK_NE(it, jit_page_->allocations_.end());
  CHECK_EQ(it->second.Size(), size);
  CHECK_EQ(it->second.Type(), type);
  return it->second;
}
References CHECK_EQ, CHECK_NE, size(), and v8::internal::tracing::type.
Merge()
void v8::internal::ThreadIsolation::JitPageReference::Merge (JitPageReference & next)
Definition at line 307 of file code-memory-access.cc.
                                                                  {
  DCHECK_EQ(End(), next.Address());
  jit_page_->size_ += next.jit_page_->size_;
  next.jit_page_->size_ = 0;
  jit_page_->allocations_.merge(next.jit_page_->allocations_);
  DCHECK(next.jit_page_->allocations_.empty());
}
References Address(), v8::internal::ThreadIsolation::JitPage::allocations_, v8::internal::DCHECK(), DCHECK_EQ, jit_page_, and v8::internal::ThreadIsolation::JitPage::size_.
Referenced by v8::internal::ThreadIsolation::TryLookupJitPageLocked().
operator=()
JitPageReference& v8::internal::ThreadIsolation::JitPageReference::operator= (const JitPageReference &) [delete]
RegisterAllocation()
ThreadIsolation::JitAllocation & v8::internal::ThreadIsolation::JitPageReference::RegisterAllocation (base::Address addr, size_t size, JitAllocationType type)
Definition at line 316 of file code-memory-access.cc.
                                                                              {
  // The data is untrusted from the pov of CFI, so the checks are security
  // sensitive.
  CHECK_GE(addr, address_);
  base::Address offset = addr - address_;
  base::Address end_offset = offset + size;
  CHECK_GT(end_offset, offset);
  CHECK_GT(jit_page_->size_, offset);
  CHECK_GE(jit_page_->size_, end_offset);
  CheckForRegionOverlap(jit_page_->allocations_, addr, size);
  return jit_page_->allocations_.emplace(addr, JitAllocation(size, type))
      .first->second;
}
References CHECK_GE, CHECK_GT, v8::internal::anonymous_namespace{code-memory-access.cc}::CheckForRegionOverlap(), size(), and v8::internal::tracing::type.
Referenced by v8::internal::ThreadIsolation::RegisterJitAllocations().
Shrink()
void v8::internal::ThreadIsolation::JitPageReference::Shrink (class JitPage * tail)
Definition at line 295 of file code-memory-access.cc.
                                                                {
  jit_page_->size_ -= tail->size_;
  // Move all allocations that are out of bounds.
  auto it = jit_page_->allocations_.lower_bound(End());
  tail->allocations_.insert(it, jit_page_->allocations_.end());
  jit_page_->allocations_.erase(it, jit_page_->allocations_.end());
}
References v8::internal::ThreadIsolation::JitPage::allocations_, and v8::internal::ThreadIsolation::JitPage::size_.
Referenced by v8::internal::ThreadIsolation::SplitJitPageLocked(), and v8::internal::ThreadIsolation::UnregisterJitPage().
Size()
size_t v8::internal::ThreadIsolation::JitPageReference::Size () const
Definition at line 291 of file code-memory-access.cc.
                                                   {
  return jit_page_->size_;
}
Referenced by v8::internal::anonymous_namespace{code-memory-access.cc}::GetSize(), v8::internal::ThreadIsolation::SplitJitPageLocked(), and v8::internal::ThreadIsolation::UnregisterJitPage().
StartOfAllocationAt()
base::Address v8::internal::ThreadIsolation::JitPageReference::StartOfAllocationAt (base::Address inner_pointer)
Definition at line 403 of file code-memory-access.cc.
                               {
  return AllocationContaining(inner_pointer).first;
}
UnregisterAllocation()
void v8::internal::ThreadIsolation::JitPageReference::UnregisterAllocation (base::Address addr)
Definition at line 352 of file code-memory-access.cc.
                      {
  // TODO(sroettger): check that the memory is not in use (scan shadow stacks).
  CHECK_EQ(jit_page_->allocations_.erase(addr), 1);
}
References CHECK_EQ.
Referenced by v8::internal::ThreadIsolation::UnregisterJitAllocationForTesting(), and v8::internal::ThreadIsolation::UnregisterWasmAllocation().
UnregisterAllocationsExcept()
void v8::internal::ThreadIsolation::JitPageReference::UnregisterAllocationsExcept (base::Address start, size_t size, const std::vector< base::Address > & addr)
Definition at line 371 of file code-memory-access.cc.
                                                                        {
  // TODO(sroettger): check that the page is not in use (scan shadow stacks).
  JitPage::AllocationMap keep_allocations;
  auto keep_before = jit_page_->allocations_.lower_bound(start);
  auto keep_after = jit_page_->allocations_.lower_bound(start + size);
  // keep all allocations before the start address.
  if (keep_before != jit_page_->allocations_.begin()) {
    keep_before--;
    keep_allocations.insert(jit_page_->allocations_.begin(), keep_before);
  }
  // from the start address, keep only allocations passed in the vector
  auto keep_iterator = keep.begin();
  for (auto it = keep_before; it != keep_after; it++) {
    if (keep_iterator == keep.end()) break;
    if (it->first == *keep_iterator) {
      keep_allocations.emplace_hint(keep_allocations.end(), it->first,
                                    it->second);
      keep_iterator++;
    }
  }
  CHECK_EQ(keep_iterator, keep.end());
  // keep all allocations after the region
  keep_allocations.insert(keep_after, jit_page_->allocations_.end());
  jit_page_->allocations_.swap(keep_allocations);
}
References CHECK_EQ, and size().
UnregisterRange()
void v8::internal::ThreadIsolation::JitPageReference::UnregisterRange (base::Address addr, size_t size)
Definition at line 358 of file code-memory-access.cc.
                                                                     {
  auto begin = jit_page_->allocations_.lower_bound(start);
  auto end = begin;
  while (end != jit_page_->allocations_.end() &&
         !AllocationIsBehindRange(start, size, end)) {
    end++;
  }
  // TODO(sroettger): check that the memory is not in use (scan shadow stacks).
  jit_page_->allocations_.erase(begin, end);
}
References v8::internal::anonymous_namespace{code-memory-access.cc}::AllocationIsBehindRange(), v8::internal::compiler::begin(), v8::internal::compiler::end(), and size().
Referenced by v8::internal::WritableJitPage::FreeRange().
Member Data Documentation
address_
base::Address v8::internal::ThreadIsolation::JitPageReference::address_ [private]
Definition at line 299 of file code-memory-access.h.
jit_page_
class JitPage* v8::internal::ThreadIsolation::JitPageReference::jit_page_ [private]
Definition at line 296 of file code-memory-access.h.
Referenced by Merge().
page_lock_
base::MutexGuard v8::internal::ThreadIsolation::JitPageReference::page_lock_ [private]
Definition at line 295 of file code-memory-access.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/code-memory-access.h
/mnt/V8SourceCode/src/common/code-memory-access.cc