v8_inspector::V8Console::CommandLineAPIScope Class Reference
#include <v8-console.h>
Public Member Functions
CommandLineAPIScope (v8::Local< v8::Context >, v8::Local< v8::Object > commandLineAPI, v8::Local< v8::Object > global)
~CommandLineAPIScope ()
CommandLineAPIScope (const CommandLineAPIScope &)=delete
CommandLineAPIScope & operator= (const CommandLineAPIScope &)=delete
Private Member Functions
v8::Local< v8::Context > context () const
v8::Local< v8::Object > commandLineAPI () const
v8::Local< v8::Object > global () const
v8::Local< v8::PrimitiveArray > installedMethods () const
v8::Local< v8::ArrayBuffer > thisReference () const
Static Private Member Functions
static void accessorGetterCallback (v8::Local< v8::Name >, const v8::PropertyCallbackInfo< v8::Value > &)
static void accessorSetterCallback (v8::Local< v8::Name >, v8::Local< v8::Value >, const v8::PropertyCallbackInfo< void > &)
Private Attributes
v8::Isolate * m_isolate
v8::Global< v8::Context > m_context
v8::Global< v8::Object > m_commandLineAPI
v8::Global< v8::Object > m_global
v8::Global< v8::PrimitiveArray > m_installedMethods
v8::Global< v8::ArrayBuffer > m_thisReference
Detailed Description
Definition at line 43 of file v8-console.h.
Constructor & Destructor Documentation
CommandLineAPIScope() [1/2]
v8_inspector::V8Console::CommandLineAPIScope::CommandLineAPIScope (v8::Local< v8::Context > context, v8::Local< v8::Object > commandLineAPI, v8::Local< v8::Object > global)
Definition at line 1002 of file v8-console.cc.
    : m_isolate(v8::Isolate::GetCurrent()),
      m_context(m_isolate, context),
      m_commandLineAPI(m_isolate, commandLineAPI),
      m_global(m_isolate, global) {
  v8::MicrotasksScope microtasksScope(context,
                                      v8::MicrotasksScope::kDoNotRunMicrotasks);
  v8::Local<v8::Array> names;
  if (!commandLineAPI->GetOwnPropertyNames(context).ToLocal(&names)) return;
  m_installedMethods.Reset(m_isolate,
                           v8::PrimitiveArray::New(m_isolate, names->Length()));
  m_thisReference = v8::Global<v8::ArrayBuffer>(
      m_isolate, v8::ArrayBuffer::New(v8::Isolate::GetCurrent(),
                                      sizeof(CommandLineAPIScope*)));
  *static_cast<CommandLineAPIScope**>(
      thisReference()->GetBackingStore()->Data()) = this;
  v8::Local<v8::PrimitiveArray> methods = installedMethods();
  for (uint32_t i = 0; i < names->Length(); ++i) {
    v8::Local<v8::Value> name;
    if (!names->Get(context, i).ToLocal(&name) || !name->IsName()) continue;
    if (global->Has(context, name).FromMaybe(true)) continue;
    const v8::SideEffectType get_accessor_side_effect_type =
        IsUnsafeCommandLineAPIFn(name, v8::Isolate::GetCurrent())
            ? v8::SideEffectType::kHasSideEffect
            : v8::SideEffectType::kHasNoSideEffect;
    if (!global
             ->SetNativeDataProperty(
                 context, name.As<v8::Name>(),
                 CommandLineAPIScope::accessorGetterCallback,
                 CommandLineAPIScope::accessorSetterCallback, thisReference(),
                 v8::DontEnum, get_accessor_side_effect_type)
             .FromMaybe(false)) {
      continue;
    }
    methods->Set(m_isolate, i, name.As<v8::Name>());
  }
}
References accessorGetterCallback(), accessorSetterCallback(), commandLineAPI(), context(), v8::DontEnum, v8::Object::Get(), v8::Isolate::GetCurrent(), v8::Object::GetOwnPropertyNames(), global(), v8::Object::Has(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, installedMethods(), v8::MicrotasksScope::kDoNotRunMicrotasks, v8::kHasNoSideEffect, v8::kHasSideEffect, v8::Array::Length(), m_installedMethods, m_isolate, m_thisReference, name, v8::PrimitiveArray::New(), v8::ArrayBuffer::New(), v8::PersistentBase< T >::Reset(), thisReference(), and v8::MaybeLocal< T >::ToLocal().
 CommandLineAPIScope()
v8_inspector::V8Console::CommandLineAPIScope::~CommandLineAPIScope ()
Definition at line 1044 of file v8-console.cc.
                                                   {
  if (m_isolate->IsExecutionTerminating()) return;
  v8::MicrotasksScope microtasksScope(context(),
                                      v8::MicrotasksScope::kDoNotRunMicrotasks);
  *static_cast<CommandLineAPIScope**>(
      thisReference()->GetBackingStore()->Data()) = nullptr;
  v8::Local<v8::PrimitiveArray> names = installedMethods();
  for (int i = 0; i < names->Length(); ++i) {
    v8::Local<v8::Value> name = names->Get(m_isolate, i);
    if (name.IsEmpty() || !name->IsName()) continue;
    if (name->IsString()) {
      v8::Local<v8::Value> descriptor;
      bool success =
          global()
              ->GetOwnPropertyDescriptor(context(), name.As<v8::String>())
              .ToLocal(&descriptor);
      USE(success);
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::MicrotasksScope::kDoNotRunMicrotasks, name, and USE.
CommandLineAPIScope() [2/2]
v8_inspector::V8Console::CommandLineAPIScope::CommandLineAPIScope (const CommandLineAPIScope &) [delete]
Member Function Documentation
accessorGetterCallback()
void v8_inspector::V8Console::CommandLineAPIScope::accessorGetterCallback (v8::Local< v8::Name > name, const v8::PropertyCallbackInfo< v8::Value > & info) [static], [private]
Definition at line 935 of file v8-console.cc.
                                                                       {
  CommandLineAPIScope* scope = *static_cast<CommandLineAPIScope**>(
      info.Data().As<v8::ArrayBuffer>()->GetBackingStore()->Data());
  v8::Local<v8::Context> context = info.GetIsolate()->GetCurrentContext();
  if (scope == nullptr) {
    USE(info.HolderV2()->Delete(context, name).FromMaybe(false));
    return;
  }
  v8::Local<v8::Value> value;
  if (!scope->commandLineAPI()->Get(context, name).ToLocal(&value)) return;
  if (isCommandLineAPIGetter(
          toProtocolStringWithTypeCheck(info.GetIsolate(), name))) {
    DCHECK(value->IsFunction());
    v8::MicrotasksScope microtasks(context,
                                   v8::MicrotasksScope::kDoNotRunMicrotasks);
    if (value.As<v8::Function>()
            ->Call(context, scope->commandLineAPI(), 0, nullptr)
            .ToLocal(&value))
      info.GetReturnValue().Set(value);
  } else {
    info.GetReturnValue().Set(value);
  }
}
References v8::Function::Call(), commandLineAPI(), context(), v8::ArrayBuffer::Data(), v8::PropertyCallbackInfo< T >::Data(), DCHECK, v8::Object::Get(), v8::Isolate::GetCurrentContext(), v8::PropertyCallbackInfo< T >::GetIsolate(), v8::PropertyCallbackInfo< T >::GetReturnValue(), v8::PropertyCallbackInfo< T >::HolderV2(), v8_inspector::isCommandLineAPIGetter(), v8::MicrotasksScope::kDoNotRunMicrotasks, name, v8::MaybeLocal< T >::ToLocal(), v8_inspector::toProtocolStringWithTypeCheck(), USE, and v8::internal::value.
Referenced by CommandLineAPIScope().
accessorSetterCallback()
void v8_inspector::V8Console::CommandLineAPIScope::accessorSetterCallback (v8::Local< v8::Name > name, v8::Local< v8::Value > value, const v8::PropertyCallbackInfo< void > & info) [static], [private]
Definition at line 961 of file v8-console.cc.
                                              {
  CommandLineAPIScope* scope = *static_cast<CommandLineAPIScope**>(
      info.Data().As<v8::ArrayBuffer>()->GetBackingStore()->Data());
  if (scope == nullptr) return;
  v8::Local<v8::Context> context = info.GetIsolate()->GetCurrentContext();
  if (!info.HolderV2()->Delete(context, name).FromMaybe(false)) return;
  if (!info.HolderV2()
           ->CreateDataProperty(context, name, value)
           .FromMaybe(false))
    return;
  v8::Local<v8::PrimitiveArray> methods = scope->installedMethods();
  for (int i = 0; i < methods->Length(); ++i) {
    v8::Local<v8::Value> methodName = methods->Get(scope->m_isolate, i);
    if (methodName.IsEmpty() || !methodName->IsName()) continue;
    if (!name->StrictEquals(methodName)) continue;
    methods->Set(scope->m_isolate, i, v8::Undefined(scope->m_isolate));
    break;
  }
}
References v8::ArrayBuffer::Data(), v8::PropertyCallbackInfo< T >::Data(), v8::Isolate::GetCurrentContext(), v8::PropertyCallbackInfo< T >::GetIsolate(), v8::PropertyCallbackInfo< T >::HolderV2(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, installedMethods(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::Value::IsName(), m_isolate, name, v8::Undefined(), and v8::internal::value.
Referenced by CommandLineAPIScope().
commandLineAPI()
v8::Local<v8::Object> v8_inspector::V8Console::CommandLineAPIScope::commandLineAPI () const [inline], [private]
Definition at line 60 of file v8-console.h.
                                             {
      return m_commandLineAPI.Get(m_isolate);
    }
Referenced by accessorGetterCallback(), and CommandLineAPIScope().
context()
v8::Local<v8::Context> v8_inspector::V8Console::CommandLineAPIScope::context () const [inline], [private]
Definition at line 59 of file v8-console.h.
{ return m_context.Get(m_isolate); }
Referenced by accessorGetterCallback(), and CommandLineAPIScope().
global()
v8::Local<v8::Object> v8_inspector::V8Console::CommandLineAPIScope::global () const [inline], [private]
Definition at line 63 of file v8-console.h.
{ return m_global.Get(m_isolate); }
Referenced by CommandLineAPIScope().
installedMethods()
v8::Local<v8::PrimitiveArray> v8_inspector::V8Console::CommandLineAPIScope::installedMethods () const [inline], [private]
Definition at line 64 of file v8-console.h.
                                                       {
      return m_installedMethods.Get(m_isolate);
    }
Referenced by accessorSetterCallback(), and CommandLineAPIScope().
operator=()
CommandLineAPIScope& v8_inspector::V8Console::CommandLineAPIScope::operator= (const CommandLineAPIScope &) [delete]
thisReference()
v8::Local<v8::ArrayBuffer> v8_inspector::V8Console::CommandLineAPIScope::thisReference () const [inline], [private]
Definition at line 67 of file v8-console.h.
                                                 {
      return m_thisReference.Get(m_isolate);
    }
Referenced by CommandLineAPIScope().
Member Data Documentation
m_commandLineAPI
v8::Global<v8::Object> v8_inspector::V8Console::CommandLineAPIScope::m_commandLineAPI [private]
Definition at line 73 of file v8-console.h.
m_context
v8::Global<v8::Context> v8_inspector::V8Console::CommandLineAPIScope::m_context [private]
Definition at line 72 of file v8-console.h.
m_global
v8::Global<v8::Object> v8_inspector::V8Console::CommandLineAPIScope::m_global [private]
Definition at line 74 of file v8-console.h.
m_installedMethods
v8::Global<v8::PrimitiveArray> v8_inspector::V8Console::CommandLineAPIScope::m_installedMethods [private]
Definition at line 75 of file v8-console.h.
Referenced by CommandLineAPIScope().
m_isolate
v8::Isolate* v8_inspector::V8Console::CommandLineAPIScope::m_isolate [private]
Definition at line 71 of file v8-console.h.
Referenced by accessorSetterCallback(), and CommandLineAPIScope().
m_thisReference
v8::Global<v8::ArrayBuffer> v8_inspector::V8Console::CommandLineAPIScope::m_thisReference [private]
Definition at line 76 of file v8-console.h.
Referenced by CommandLineAPIScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-console.h
/mnt/V8SourceCode/src/inspector/v8-console.cc