v8::internal::BreakLocation Class Reference
#include <debug.h>
Public Member Functions
bool IsSuspend () const
bool IsReturn () const
bool IsReturnOrSuspend () const
bool IsCall () const
bool IsDebugBreakSlot () const
bool IsDebuggerStatement () const
bool IsDebugBreakAtEntry () const
bool HasBreakPoint (Isolate *isolate, Handle< DebugInfo > debug_info) const
int generator_suspend_id ()
int position () const
int code_offset () const
debug::BreakLocationType type () const
Tagged< JSGeneratorObject > GetGeneratorObjectForSuspendedFrame (JavaScriptFrame *frame) const
Static Public Member Functions
static BreakLocation Invalid ()
static BreakLocation FromFrame (Handle< DebugInfo > debug_info, JavaScriptFrame *frame)
static bool IsPausedInJsFunctionEntry (JavaScriptFrame *frame)
static void AllAtCurrentStatement (Handle< DebugInfo > debug_info, JavaScriptFrame *frame, std::vector< BreakLocation > *result_out)
Private Member Functions
BreakLocation (Handle< AbstractCode > abstract_code, DebugBreakType type, int code_offset, int position, int generator_obj_reg_index, int generator_suspend_id)
BreakLocation (int position, DebugBreakType type)
void SetDebugBreak ()
void ClearDebugBreak ()
Static Private Member Functions
static int BreakIndexFromCodeOffset (Handle< DebugInfo > debug_info, DirectHandle< AbstractCode > abstract_code, int offset)
Private Attributes
Handle< AbstractCode > abstract_code_
int code_offset_
DebugBreakType type_
int position_
int generator_obj_reg_index_
int generator_suspend_id_
Friends
class BreakIterator
Detailed Description
Definition at line 69 of file debug.h.
Constructor & Destructor Documentation
BreakLocation() [1/2]
v8::internal::BreakLocation::BreakLocation (Handle< AbstractCode > abstract_code, DebugBreakType type, int code_offset, int position, int generator_obj_reg_index, int generator_suspend_id) [inline], [private]
Definition at line 100 of file debug.h.
      : abstract_code_(abstract_code),
        code_offset_(code_offset),
        type_(type),
        position_(position),
        generator_obj_reg_index_(generator_obj_reg_index),
        generator_suspend_id_(generator_suspend_id) {
    DCHECK_NE(NOT_DEBUG_BREAK, type_);
  }
References DCHECK_NE, v8::internal::NOT_DEBUG_BREAK, and type_.
Referenced by FromFrame(), and Invalid().
BreakLocation() [2/2]
v8::internal::BreakLocation::BreakLocation (int position, DebugBreakType type) [inline], [private]
Definition at line 112 of file debug.h.
      : code_offset_(0),
        type_(type),
        position_(position),
        generator_obj_reg_index_(0),
        generator_suspend_id_(-1) {}
Member Function Documentation
AllAtCurrentStatement()
void v8::internal::BreakLocation::AllAtCurrentStatement (Handle< DebugInfo > debug_info, JavaScriptFrame * frame, std::vector< BreakLocation > * result_out) [static]
Definition at line 236 of file debug.cc.
                                          {
  DCHECK(!debug_info->CanBreakAtEntry());
  auto summary = FrameSummary::GetTop(frame).AsJavaScript();
  int offset = summary.code_offset();
  DirectHandle<AbstractCode> abstract_code = summary.abstract_code();
  PtrComprCageBase cage_base = GetPtrComprCageBase(*debug_info);
  if (IsCode(*abstract_code, cage_base)) offset = offset - 1;
  int statement_position;
  {
    BreakIterator it(debug_info);
    it.SkipTo(BreakIndexFromCodeOffset(debug_info, abstract_code, offset));
    statement_position = it.statement_position();
  }
  for (BreakIterator it(debug_info); !it.Done(); it.Next()) {
    if (it.statement_position() == statement_position) {
      result_out->push_back(it.GetBreakLocation());
    }
  }
}
References BreakIndexFromCodeOffset(), v8::internal::FrameSummary::code_offset(), v8::internal::DCHECK(), v8::internal::BreakIterator::Done(), v8::internal::GetPtrComprCageBase(), v8::internal::FrameSummary::GetTop(), v8::internal::BreakIterator::SkipTo(), and v8::internal::BreakIterator::statement_position().
Referenced by v8::internal::Debug::HandleDebugBreak(), and v8::internal::Debug::OnException().
BreakIndexFromCodeOffset()
int v8::internal::BreakLocation::BreakIndexFromCodeOffset (Handle< DebugInfo > debug_info, DirectHandle< AbstractCode > abstract_code, int offset) [static], [private]
Definition at line 270 of file debug.cc.
                {
  // Run through all break points to locate the one closest to the address.
  int closest_break = 0;
  int distance = kMaxInt;
  DCHECK(kFunctionEntryBytecodeOffset <= offset &&
         offset < abstract_code->Size());
  for (BreakIterator it(debug_info); !it.Done(); it.Next()) {
    // Check if this break point is closer that what was previously found.
    if (it.code_offset() <= offset && offset - it.code_offset() < distance) {
      closest_break = it.break_index();
      distance = offset - it.code_offset();
      // Check whether we can't get any closer.
      if (distance == 0) break;
    }
  }
  return closest_break;
}
References v8::internal::DCHECK(), v8::internal::BreakIterator::Done(), v8::internal::kFunctionEntryBytecodeOffset, and v8::internal::kMaxInt.
Referenced by AllAtCurrentStatement(), and FromFrame().
ClearDebugBreak()
void v8::internal::BreakLocation::ClearDebugBreak () [private]
code_offset()
int v8::internal::BreakLocation::code_offset () const [inline]
Definition at line 92 of file debug.h.
{ return code_offset_; }
References code_offset_.
Referenced by v8::internal::Debug::IsBreakOnDebuggerStatement().
FromFrame()
BreakLocation v8::internal::BreakLocation::FromFrame (Handle< DebugInfo > debug_info, JavaScriptFrame * frame) [static]
Definition at line 188 of file debug.cc.
                                                               {
  if (debug_info->CanBreakAtEntry()) {
    return BreakLocation(Debug::kBreakAtEntryPosition, DEBUG_BREAK_AT_ENTRY);
  }
  auto summary = FrameSummary::GetTop(frame).AsJavaScript();
  int offset = summary.code_offset();
  DirectHandle<AbstractCode> abstract_code = summary.abstract_code();
  BreakIterator it(debug_info);
  it.SkipTo(BreakIndexFromCodeOffset(debug_info, abstract_code, offset));
  return it.GetBreakLocation();
}
References BreakIndexFromCodeOffset(), BreakLocation(), v8::internal::FrameSummary::code_offset(), v8::internal::DEBUG_BREAK_AT_ENTRY, v8::internal::BreakIterator::GetBreakLocation(), v8::internal::FrameSummary::GetTop(), v8::internal::Debug::kBreakAtEntryPosition, and v8::internal::BreakIterator::SkipTo().
Referenced by v8::internal::Debug::Break(), v8::internal::Debug::IsBreakAtReturn(), v8::internal::Debug::PrepareStep(), and v8::internal::ScopeIterator::TryParseAndRetrieveScopes().
generator_suspend_id()
int v8::internal::BreakLocation::generator_suspend_id () [inline]
Definition at line 90 of file debug.h.
{ return generator_suspend_id_; }
References generator_suspend_id_.
Referenced by v8::internal::Debug::Break().
GetGeneratorObjectForSuspendedFrame()
Tagged< JSGeneratorObject > v8::internal::BreakLocation::GetGeneratorObjectForSuspendedFrame (JavaScriptFrame * frame) const
Definition at line 258 of file debug.cc.
                                  {
  DCHECK(IsSuspend());
  DCHECK_GE(generator_obj_reg_index_, 0);
  Tagged<Object> generator_obj =
      UnoptimizedJSFrame::cast(frame)->ReadInterpreterRegister(
          generator_obj_reg_index_);
  return Cast<JSGeneratorObject>(generator_obj);
}
References v8::internal::UnoptimizedJSFrame::cast(), v8::internal::DCHECK(), DCHECK_GE, generator_obj_reg_index_, IsSuspend(), and v8::internal::UnoptimizedJSFrame::ReadInterpreterRegister().
Referenced by v8::internal::Debug::Break().
HasBreakPoint()
bool v8::internal::BreakLocation::HasBreakPoint (Isolate * isolate, Handle< DebugInfo > debug_info) const
Definition at line 290 of file debug.cc.
                                                                      {
  // First check whether there is a break point with the same source position.
  if (!debug_info->HasBreakInfo() ||
      !debug_info->HasBreakPoint(isolate, position_)) {
    return false;
  }
  if (debug_info->CanBreakAtEntry()) {
    DCHECK_EQ(Debug::kBreakAtEntryPosition, position_);
    return debug_info->BreakAtEntry();
  } else {
    // Then check whether a break point at that source position would have
    // the same code offset. Otherwise it's just a break location that we can
    // step to, but not actually a location where we can put a break point.
    DCHECK(IsBytecodeArray(*abstract_code_, isolate));
    BreakIterator it(debug_info);
    it.SkipToPosition(position_);
    return it.code_offset() == code_offset_;
  }
}
References abstract_code_, v8::internal::BreakIterator::code_offset(), code_offset_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Debug::kBreakAtEntryPosition, position_, and v8::internal::BreakIterator::SkipToPosition().
Referenced by v8::internal::Debug::CheckBreakPoints(), and v8::internal::Debug::IsBreakOnInstrumentation().
Invalid()
static BreakLocation v8::internal::BreakLocation::Invalid () [inline], [static]
Definition at line 71 of file debug.h.
{ return BreakLocation(-1, NOT_DEBUG_BREAK); }
References BreakLocation(), and v8::internal::NOT_DEBUG_BREAK.
Referenced by v8::internal::Debug::PrepareStep().
IsCall()
bool v8::internal::BreakLocation::IsCall () const [inline]
Definition at line 83 of file debug.h.
{ return type_ == DEBUG_BREAK_SLOT_AT_CALL; }
References v8::internal::DEBUG_BREAK_SLOT_AT_CALL, and type_.
IsDebugBreakAtEntry()
bool v8::internal::BreakLocation::IsDebugBreakAtEntry () const [inline]
Definition at line 86 of file debug.h.
{ return type_ == DEBUG_BREAK_AT_ENTRY; }
References v8::internal::DEBUG_BREAK_AT_ENTRY, and type_.
Referenced by v8::internal::Debug::Break().
IsDebugBreakSlot()
bool v8::internal::BreakLocation::IsDebugBreakSlot () const [inline]
Definition at line 84 of file debug.h.
{ return type_ >= DEBUG_BREAK_SLOT; }
References v8::internal::DEBUG_BREAK_SLOT, and type_.
IsDebuggerStatement()
bool v8::internal::BreakLocation::IsDebuggerStatement () const [inline]
Definition at line 85 of file debug.h.
{ return type_ == DEBUGGER_STATEMENT; }
References v8::internal::DEBUGGER_STATEMENT, and type_.
IsPausedInJsFunctionEntry()
bool v8::internal::BreakLocation::IsPausedInJsFunctionEntry (JavaScriptFrame * frame) [static]
Definition at line 201 of file debug.cc.
                                                                    {
  auto summary = FrameSummary::GetTop(frame);
  return summary.code_offset() == kFunctionEntryBytecodeOffset;
}
References v8::internal::FrameSummary::GetTop(), and v8::internal::kFunctionEntryBytecodeOffset.
Referenced by v8::internal::Debug::HandleDebugBreak().
IsReturn()
bool v8::internal::BreakLocation::IsReturn () const [inline]
Definition at line 81 of file debug.h.
{ return type_ == DEBUG_BREAK_SLOT_AT_RETURN; }
References v8::internal::DEBUG_BREAK_SLOT_AT_RETURN, and type_.
Referenced by v8::internal::Debug::Break(), v8::internal::Debug::IsBreakAtReturn(), v8::internal::Debug::PrepareStep(), and v8::internal::ScopeIterator::TryParseAndRetrieveScopes().
IsReturnOrSuspend()
bool v8::internal::BreakLocation::IsReturnOrSuspend () const [inline]
Definition at line 82 of file debug.h.
{ return type_ >= DEBUG_BREAK_SLOT_AT_RETURN; }
References v8::internal::DEBUG_BREAK_SLOT_AT_RETURN, and type_.
Referenced by v8::internal::Debug::Break(), and v8::internal::Debug::PrepareStep().
IsSuspend()
bool v8::internal::BreakLocation::IsSuspend () const [inline]
Definition at line 80 of file debug.h.
{ return type_ == DEBUG_BREAK_SLOT_AT_SUSPEND; }
References v8::internal::DEBUG_BREAK_SLOT_AT_SUSPEND, and type_.
Referenced by v8::internal::Debug::Break(), GetGeneratorObjectForSuspendedFrame(), and v8::internal::Debug::PrepareStep().
position()
int v8::internal::BreakLocation::position () const [inline]
Definition at line 91 of file debug.h.
{ return position_; }
References position_.
Referenced by v8::internal::Debug::CheckBreakPoints(), v8::debug::anonymous_namespace{debug-interface.cc}::CompareBreakLocation(), v8::internal::Debug::IsBreakOnInstrumentation(), and v8::internal::Debug::SetMutedLocation().
SetDebugBreak()
void v8::internal::BreakLocation::SetDebugBreak () [private]
type()
debug::BreakLocationType v8::internal::BreakLocation::type () const
Definition at line 311 of file debug.cc.
                                                 {
  switch (type_) {
    case DEBUGGER_STATEMENT:
      return debug::kDebuggerStatementBreakLocation;
    case DEBUG_BREAK_SLOT_AT_CALL:
      return debug::kCallBreakLocation;
    case DEBUG_BREAK_SLOT_AT_RETURN:
      return debug::kReturnBreakLocation;
    // Externally, suspend breaks should look like normal breaks.
    case DEBUG_BREAK_SLOT_AT_SUSPEND:
    default:
      return debug::kCommonBreakLocation;
  }
}
References v8::internal::DEBUG_BREAK_SLOT_AT_CALL, v8::internal::DEBUG_BREAK_SLOT_AT_RETURN, v8::internal::DEBUG_BREAK_SLOT_AT_SUSPEND, v8::internal::DEBUGGER_STATEMENT, v8::debug::kCallBreakLocation, v8::debug::kCommonBreakLocation, v8::debug::kDebuggerStatementBreakLocation, v8::debug::kReturnBreakLocation, and type_.
Friends And Related Function Documentation
BreakIterator
friend class BreakIterator [friend]
Definition at line 133 of file debug.h.
Member Data Documentation
abstract_code_
Handle<AbstractCode> v8::internal::BreakLocation::abstract_code_ [private]
Definition at line 126 of file debug.h.
Referenced by HasBreakPoint().
code_offset_
int v8::internal::BreakLocation::code_offset_ [private]
Definition at line 127 of file debug.h.
Referenced by code_offset(), and HasBreakPoint().
generator_obj_reg_index_
int v8::internal::BreakLocation::generator_obj_reg_index_ [private]
Definition at line 130 of file debug.h.
Referenced by GetGeneratorObjectForSuspendedFrame().
generator_suspend_id_
int v8::internal::BreakLocation::generator_suspend_id_ [private]
Definition at line 131 of file debug.h.
Referenced by generator_suspend_id().
position_
int v8::internal::BreakLocation::position_ [private]
Definition at line 129 of file debug.h.
Referenced by HasBreakPoint(), and position().
type_
DebugBreakType v8::internal::BreakLocation::type_ [private]
Definition at line 128 of file debug.h.
Referenced by BreakLocation(), IsCall(), IsDebugBreakAtEntry(), IsDebugBreakSlot(), IsDebuggerStatement(), IsReturn(), IsReturnOrSuspend(), IsSuspend(), and type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug.h
/mnt/V8SourceCode/src/debug/debug.cc