v8::internal::StackGuard::ThreadLocal Class Reference
Public Member Functions
ThreadLocal ()
void Initialize (Isolate *isolate, const ExecutionAccess &lock)
uintptr_t jslimit ()
void set_jslimit (uintptr_t limit)
void set_interrupt_requested (InterruptLevel level, bool requested)
bool has_interrupt_requested (InterruptLevel level)
Public Attributes
uintptr_t real_jslimit_ = kIllegalLimit
uintptr_t padding1_
base::AtomicWord jslimit_ = kIllegalLimit
uintptr_t padding2_
base::Atomic8 interrupt_requested_ [kNumberOfInterruptLevels]
InterruptsScope * interrupt_scopes_ = nullptr
uint32_t interrupt_flags_ = 0
Detailed Description
Definition at line 197 of file stack-guard.h.
Constructor & Destructor Documentation
ThreadLocal()
v8::internal::StackGuard::ThreadLocal::ThreadLocal () [inline]
Definition at line 199 of file stack-guard.h.
{}
Member Function Documentation
has_interrupt_requested()
bool v8::internal::StackGuard::ThreadLocal::has_interrupt_requested (InterruptLevel level) [inline]
Definition at line 268 of file stack-guard.h.
                                                       {
      return base::Relaxed_Load(&interrupt_requested_[static_cast<int>(level)]);
    }
References v8::base::Relaxed_Load().
Referenced by v8::internal::StackGuard::HasTerminationRequest().
Initialize()
void v8::internal::StackGuard::ThreadLocal::Initialize (Isolate * isolate, const ExecutionAccess & lock)
Definition at line 247 of file stack-guard.cc.
                                                                      {
  const uintptr_t kLimitSize = v8_flags.stack_size * KB;
  DCHECK_GT(base::Stack::GetStackStart(), kLimitSize);
  uintptr_t limit = base::Stack::GetStackStart() - kLimitSize;
  real_jslimit_ = SimulatorStack::JsLimitFromCLimit(isolate, limit);
  set_jslimit(SimulatorStack::JsLimitFromCLimit(isolate, limit));
#ifdef USE_SIMULATOR
  real_climit_ = limit;
  set_climit(limit);
#endif
  interrupt_scopes_ = nullptr;
  interrupt_flags_ = 0;
}
References DCHECK_GT, v8::base::Stack::GetStackStart(), interrupt_flags_, interrupt_scopes_, v8::internal::SimulatorStack::JsLimitFromCLimit(), v8::internal::KB, real_jslimit_, set_jslimit(), and v8::internal::v8_flags.
Referenced by v8::internal::StackGuard::InitThread().
jslimit()
uintptr_t v8::internal::StackGuard::ThreadLocal::jslimit () [inline]
Definition at line 241 of file stack-guard.h.
                        {
      return base::bit_cast<uintptr_t>(base::Relaxed_Load(&jslimit_));
    }
References v8::base::Relaxed_Load().
Referenced by v8::internal::StackGuard::SetStackLimitInternal().
set_interrupt_requested()
void v8::internal::StackGuard::ThreadLocal::set_interrupt_requested (InterruptLevel level, bool requested) [inline]
Definition at line 263 of file stack-guard.h.
                                                                       {
      base::Relaxed_Store(&interrupt_requested_[static_cast<int>(level)],
                          requested);
    }
References v8::base::Relaxed_Store().
Referenced by v8::internal::StackGuard::update_interrupt_requests_and_stack_limits().
set_jslimit()
void v8::internal::StackGuard::ThreadLocal::set_jslimit (uintptr_t limit) [inline]
Definition at line 244 of file stack-guard.h.
                                      {
      return base::Relaxed_Store(&jslimit_,
                                 static_cast<base::AtomicWord>(limit));
    }
References v8::base::Relaxed_Store().
Referenced by Initialize(), v8::internal::StackGuard::SetStackLimitInternal(), and v8::internal::StackGuard::update_interrupt_requests_and_stack_limits().
Member Data Documentation
interrupt_flags_
uint32_t v8::internal::StackGuard::ThreadLocal::interrupt_flags_ = 0
Definition at line 273 of file stack-guard.h.
Referenced by v8::internal::StackGuard::CheckInterrupt(), v8::internal::StackGuard::ClearInterrupt(), v8::internal::StackGuard::FetchAndClearInterrupts(), v8::internal::StackGuard::HasTerminationRequest(), Initialize(), v8::internal::StackGuard::PopInterruptsScope(), v8::internal::StackGuard::PushInterruptsScope(), v8::internal::StackGuard::RequestInterrupt(), and v8::internal::StackGuard::update_interrupt_requests_and_stack_limits().
interrupt_requested_
base::Atomic8 v8::internal::StackGuard::ThreadLocal::interrupt_requested_[kNumberOfInterruptLevels]
Initial value:
= {
        false, false, false}
Definition at line 260 of file stack-guard.h.
interrupt_scopes_
InterruptsScope* v8::internal::StackGuard::ThreadLocal::interrupt_scopes_ = nullptr
Definition at line 272 of file stack-guard.h.
Referenced by v8::internal::StackGuard::ClearInterrupt(), Initialize(), v8::internal::StackGuard::PopInterruptsScope(), v8::internal::StackGuard::PushInterruptsScope(), and v8::internal::StackGuard::RequestInterrupt().
jslimit_
base::AtomicWord v8::internal::StackGuard::ThreadLocal::jslimit_ = kIllegalLimit
Definition at line 233 of file stack-guard.h.
Referenced by v8::internal::StackGuard::SetStackLimitForStackSwitching().
padding1_
uintptr_t v8::internal::StackGuard::ThreadLocal::padding1_
Definition at line 227 of file stack-guard.h.
padding2_
uintptr_t v8::internal::StackGuard::ThreadLocal::padding2_
Definition at line 238 of file stack-guard.h.
real_jslimit_
uintptr_t v8::internal::StackGuard::ThreadLocal::real_jslimit_ = kIllegalLimit
Definition at line 212 of file stack-guard.h.
Referenced by Initialize(), v8::internal::StackGuard::SetStackLimitForStackSwitching(), v8::internal::StackGuard::SetStackLimitInternal(), and v8::internal::StackGuard::update_interrupt_requests_and_stack_limits().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/stack-guard.h
/mnt/V8SourceCode/src/execution/stack-guard.cc