v8::internal::RegisterValues Class Reference
#include <frame-description.h>
Public Member Functions
intptr_t GetRegister (unsigned n) const
Float32 GetFloatRegister (unsigned n) const
Float64 GetDoubleRegister (unsigned n) const
void SetDoubleRegister (unsigned n, Float64 value)
Simd128 GetSimd128Register (unsigned n) const
void SetRegister (unsigned n, intptr_t value)
void SetSimd128Register (unsigned n, Simd128 value)
Public Attributes
intptr_t registers_ [Register::kNumRegisters]
Simd128 simd128_registers_ [Simd128Register::kNumRegisters]
Detailed Description
Definition at line 27 of file frame-description.h.
Member Function Documentation
GetDoubleRegister()
Float64 v8::internal::RegisterValues::GetDoubleRegister (unsigned n) const
Definition at line 48 of file deoptimizer-arm.cc.
                                                          {
  const Address start = reinterpret_cast<Address>(simd128_registers_);
  const size_t offset = n * sizeof(Float64);
  return base::ReadUnalignedValue<Float64>(start + offset);
}
References simd128_registers_.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), and v8::internal::FrameDescription::GetDoubleRegister().
GetFloatRegister()
Float32 v8::internal::RegisterValues::GetFloatRegister (unsigned n) const
Definition at line 42 of file deoptimizer-arm.cc.
                                                         {
  const Address start = reinterpret_cast<Address>(simd128_registers_);
  const size_t offset = n * sizeof(Float32);
  return base::ReadUnalignedValue<Float32>(start + offset);
}
References simd128_registers_.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue().
GetRegister()
intptr_t v8::internal::RegisterValues::GetRegister (unsigned n) const [inline]
Definition at line 29 of file frame-description.h.
                                         {
    V8_ASSUME(n < arraysize(registers_));
    return registers_[n];
  }
References arraysize, registers_, and V8_ASSUME.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), and v8::internal::FrameDescription::GetRegister().
GetSimd128Register()
Simd128 v8::internal::RegisterValues::GetSimd128Register (unsigned n) const [inline]
Definition at line 39 of file frame-description.h.
                                               {
    V8_ASSUME(n < arraysize(simd128_registers_));
    return simd128_registers_[n];
  }
References arraysize, simd128_registers_, and V8_ASSUME.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue().
SetDoubleRegister()
void v8::internal::RegisterValues::SetDoubleRegister (unsigned n, Float64 value)
Definition at line 54 of file deoptimizer-arm.cc.
                                                                {
  V8_ASSUME(n < 2 * arraysize(simd128_registers_));
  const Address start = reinterpret_cast<Address>(simd128_registers_);
  const size_t offset = n * sizeof(Float64);
  base::WriteUnalignedValue(start + offset, value);
}
References arraysize, simd128_registers_, V8_ASSUME, v8::internal::value, and v8::base::WriteUnalignedValue().
Referenced by v8::internal::FrameDescription::SetDoubleRegister().
SetRegister()
void v8::internal::RegisterValues::SetRegister (unsigned n, intptr_t value) [inline]
Definition at line 44 of file frame-description.h.
                                               {
    V8_ASSUME(n < arraysize(registers_));
    registers_[n] = value;
  }
References arraysize, registers_, V8_ASSUME, and v8::internal::value.
Referenced by v8::internal::Deoptimizer::DoComputeOutputFrames(), and v8::internal::FrameDescription::SetRegister().
SetSimd128Register()
void v8::internal::RegisterValues::SetSimd128Register (unsigned n, Simd128 value) [inline]
Definition at line 49 of file frame-description.h.
                                                     {
    V8_ASSUME(n < arraysize(simd128_registers_));
    simd128_registers_[n] = value;
  }
References arraysize, simd128_registers_, V8_ASSUME, and v8::internal::value.
Referenced by v8::internal::FrameDescription::SetSimd128Register().
Member Data Documentation
registers_
intptr_t v8::internal::RegisterValues::registers_[Register::kNumRegisters]
Definition at line 54 of file frame-description.h.
Referenced by GetRegister(), v8::internal::FrameDescription::registers_offset(), and SetRegister().
simd128_registers_
Simd128 v8::internal::RegisterValues::simd128_registers_[Simd128Register::kNumRegisters]
Definition at line 63 of file frame-description.h.
Referenced by GetDoubleRegister(), GetFloatRegister(), GetSimd128Register(), SetDoubleRegister(), SetSimd128Register(), and v8::internal::FrameDescription::simd128_registers_offset().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/deoptimizer/frame-description.h
/mnt/V8SourceCode/src/deoptimizer/arm/deoptimizer-arm.cc
/mnt/V8SourceCode/src/deoptimizer/arm64/deoptimizer-arm64.cc
/mnt/V8SourceCode/src/deoptimizer/loong64/deoptimizer-loong64.cc
/mnt/V8SourceCode/src/deoptimizer/mips64/deoptimizer-mips64.cc
/mnt/V8SourceCode/src/deoptimizer/ppc/deoptimizer-ppc.cc
/mnt/V8SourceCode/src/deoptimizer/riscv/deoptimizer-riscv.cc
/mnt/V8SourceCode/src/deoptimizer/s390/deoptimizer-s390.cc