v8::internal::YoungGenerationRootMarkingVisitor Class Reference
#include <minor-mark-sweep.h>
Public Member Functions
YoungGenerationRootMarkingVisitor (MinorMarkSweepCollector *collector)
~YoungGenerationRootMarkingVisitor ()
void VisitRootPointer (Root root, const char *description, FullObjectSlot p) final
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) final
GarbageCollector collector () const override
YoungGenerationRootMarkingVisitor (const YoungGenerationRootMarkingVisitor &)=delete
YoungGenerationRootMarkingVisitor & operator= (const YoungGenerationRootMarkingVisitor &)=delete
Private Member Functions
template<typename TSlot >
void VisitPointersImpl (Root root, TSlot start, TSlot end)
Private Attributes
YoungGenerationMainMarkingVisitor *const main_marking_visitor_
Additional Inherited Members
Detailed Description
Definition at line 118 of file minor-mark-sweep.h.
Constructor & Destructor Documentation
YoungGenerationRootMarkingVisitor() [1/2]
v8::internal::YoungGenerationRootMarkingVisitor::YoungGenerationRootMarkingVisitor (MinorMarkSweepCollector * collector) [explicit]
Definition at line 276 of file minor-mark-sweep.cc.
    : main_marking_visitor_(collector->main_marking_visitor()) {}
 YoungGenerationRootMarkingVisitor()
v8::internal::YoungGenerationRootMarkingVisitor::~YoungGenerationRootMarkingVisitor () [default]
YoungGenerationRootMarkingVisitor() [2/2]
v8::internal::YoungGenerationRootMarkingVisitor::YoungGenerationRootMarkingVisitor (const YoungGenerationRootMarkingVisitor &) [delete]
Member Function Documentation
collector()
GarbageCollector v8::internal::YoungGenerationRootMarkingVisitor::collector () const [inline], [override], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 131 of file minor-mark-sweep.h.
                                              {
    return GarbageCollector::MINOR_MARK_SWEEPER;
  }
References v8::internal::MINOR_MARK_SWEEPER.
operator=()
YoungGenerationRootMarkingVisitor& v8::internal::YoungGenerationRootMarkingVisitor::operator= (const YoungGenerationRootMarkingVisitor &) [delete]
VisitPointersImpl()
template<typename TSlot >
void v8::internal::YoungGenerationRootMarkingVisitor::VisitPointersImpl (Root root, TSlot start, TSlot end) [private]
Definition at line 39 of file minor-mark-sweep-inl.h.
                                                                     {
  if (root == Root::kStackRoots) {
    for (TSlot slot = start; slot < end; ++slot) {
      main_marking_visitor_->VisitObjectViaSlot<
          YoungGenerationMainMarkingVisitor::ObjectVisitationMode::
              kPushToWorklist,
          YoungGenerationMainMarkingVisitor::SlotTreatmentMode::kReadOnly>(
          slot);
    }
  } else {
    for (TSlot slot = start; slot < end; ++slot) {
      main_marking_visitor_->VisitObjectViaSlot<
          YoungGenerationMainMarkingVisitor::ObjectVisitationMode::
              kPushToWorklist,
          YoungGenerationMainMarkingVisitor::SlotTreatmentMode::kReadWrite>(
          slot);
    }
  }
}
References v8::internal::compiler::end(), v8::internal::YoungGenerationMarkingVisitor< marking_mode >::kPushToWorklist, v8::internal::YoungGenerationMarkingVisitor< marking_mode >::kReadOnly, v8::internal::YoungGenerationMarkingVisitor< marking_mode >::kReadWrite, main_marking_visitor_, and v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitObjectViaSlot().
Referenced by VisitRootPointer(), and VisitRootPointers().
VisitRootPointer()
void v8::internal::YoungGenerationRootMarkingVisitor::VisitRootPointer (Root root, const char * description, FullObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 27 of file minor-mark-sweep-inl.h.
                                                          {
  VisitPointersImpl(root, p, p + 1);
}
References VisitPointersImpl().
VisitRootPointers()
void v8::internal::YoungGenerationRootMarkingVisitor::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 32 of file minor-mark-sweep-inl.h.
                        {
  VisitPointersImpl(root, start, end);
}
References v8::internal::compiler::end(), and VisitPointersImpl().
Member Data Documentation
main_marking_visitor_
YoungGenerationMainMarkingVisitor* const v8::internal::YoungGenerationRootMarkingVisitor::main_marking_visitor_ [private]
Definition at line 144 of file minor-mark-sweep.h.
Referenced by VisitPointersImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/minor-mark-sweep.h
/mnt/V8SourceCode/src/heap/minor-mark-sweep-inl.h
/mnt/V8SourceCode/src/heap/minor-mark-sweep.cc