v8::internal::Tagged< Smi > Class Reference
#include <tagged.h>
Public Member Functions
constexpr Tagged ()=default
constexpr Tagged (Address ptr)
constexpr bool IsHeapObject () const
constexpr bool IsSmi () const
constexpr int32_t value () const
Additional Inherited Members
Detailed Description
Definition at line 417 of file tagged.h.
Constructor & Destructor Documentation
Tagged() [1/2]
constexpr v8::internal::Tagged< Smi >::Tagged () [inline], [constexpr], [default]
Tagged() [2/2]
constexpr v8::internal::Tagged< Smi >::Tagged (Address ptr) [inline], [explicit], [constexpr]
Definition at line 420 of file tagged.h.
: StrongTaggedBase(ptr) {}
Member Function Documentation
IsHeapObject()
constexpr bool v8::internal::Tagged< Smi >::IsHeapObject () const [inline], [constexpr]
Definition at line 424 of file tagged.h.
{ return false; }
IsSmi()
constexpr bool v8::internal::Tagged< Smi >::IsSmi () const [inline], [constexpr]
Definition at line 425 of file tagged.h.
{ return true; }
value()
constexpr int32_t v8::internal::Tagged< Smi >::value () const [inline], [constexpr]
Definition at line 427 of file tagged.h.
                                            {
    return Internals::SmiValue(ptr());
  }
References v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::ptr(), and v8::internal::Internals::SmiValue().
Referenced by v8::internal::ObjectHashSet::Add(), v8::internal::OrderedHashMap::Add(), v8::internal::wasm::FeedbackMaker::AddCallIndirectCandidate(), v8::internal::HeapSnapshotGenerator::AddEntry(), v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::CircularStructureMessageBuilder::AppendSmi(), v8::internal::interpreter::BytecodeArrayBuilder::BinaryOperationSmiLiteral(), v8::internal::BIT_FIELD_ACCESSORS(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumericalValue(), v8::internal::JSRegExpResultIndices::BuildIndices(), v8::internal::anonymous_namespace{template-objects.cc}::CachedTemplateMatches(), v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), v8::internal::CodeStubAssembler::ElementOffsetFromIndex(), v8::internal::HeapSnapshotGenerator::FindEntry(), v8::internal::JSRegExp::flags(), v8::internal::Generate_InterpreterEnterBytecode(), v8::internal::SmiStringCache::GetEntryFor(), v8::internal::interpreter::BytecodeArrayIterator::GetRelativeJumpTargetOffset(), v8::internal::maglev::MaglevGraphBuilder::GetTruncatedInt32ForToNumber(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::compiler::turboshaft::OperationMatcher::MatchSmiZero(), v8::internal::compiler::turboshaft::OperationMatcher::MatchZero(), v8::internal::Heap::NextScriptId(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt(), v8::internal::PropertyDetails::PropertyDetails(), v8::internal::ObjectMultiHashTableBase< Derived, N >::Put(), v8::internal::requires(), v8::internal::anonymous_namespace{handler-configuration.cc}::SetBitFieldValue(), wasm::StoreImpl::SetHostInfo(), v8::internal::Smi::SmiPrint(), v8::internal::FactoryBase< Impl >::SmiToString(), v8::internal::Smi::ToUint32Smi(), and v8::internal::ValueSerializer::WriteSmi().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/tagged.h