v8::internal::PointerAuthentication Class Reference
#include <pointer-authentication.h>
Static Public Member Functions
static Address AuthenticatePC (Address *pc_address, unsigned offset_from_sp)
static Address StripPAC (Address pc)
static void ReplacePC (Address *pc_address, Address new_pc, int offset_from_sp)
static Address SignAndCheckPC (Isolate *isolate, Address pc, Address sp)
static Address MoveSignedPC (Isolate *isolate, Address pc, Address new_sp, Address old_sp)
Detailed Description
Definition at line 15 of file pointer-authentication.h.
Member Function Documentation
AuthenticatePC()
Address v8::internal::PointerAuthentication::AuthenticatePC (Address * pc_address, unsigned offset_from_sp) [inline], [static]
Definition at line 68 of file pointer-authentication-arm64.h.
                                                  {
  uint64_t sp = reinterpret_cast<uint64_t>(pc_address) + offset_from_sp;
  uint64_t pc = static_cast<uint64_t>(*pc_address);
  return impl::AuthPAC(pc, sp);
}
References v8::internal::impl::AuthPAC().
Referenced by v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(), and v8::internal::StackFrame::ReadPC().
MoveSignedPC()
Address v8::internal::PointerAuthentication::MoveSignedPC (Isolate * isolate, Address pc, Address new_sp, Address old_sp) [inline], [static]
Definition at line 151 of file pointer-authentication-arm64.h.
                                                                      {
#if V8_ENABLE_WEBASSEMBLY
  // Only used by wasm deoptimizations and growable stacks.
  CHECK(v8_flags.wasm_deopt || v8_flags.experimental_wasm_growable_stacks);
  // Verify the old pc and sign it for the new sp.
  return impl::SignPC(impl::AuthPAC(pc, old_sp), new_sp);
#else
  UNREACHABLE();
#endif
}
References v8::internal::impl::AuthPAC(), CHECK, v8::internal::impl::SignPC(), v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::grow_stack().
ReplacePC()
void v8::internal::PointerAuthentication::ReplacePC (Address * pc_address, Address new_pc, int offset_from_sp) [inline], [static]
Definition at line 98 of file pointer-authentication-arm64.h.
                                                                    {
  uint64_t sp = reinterpret_cast<uint64_t>(pc_address) + offset_from_sp;
  uint64_t old_pc = static_cast<uint64_t>(*pc_address);
#ifdef USE_SIMULATOR
  uint64_t auth_old_pc = Simulator::AuthPAC(old_pc, sp, Simulator::kPACKeyIB,
                                            Simulator::kInstructionPointer);
  uint64_t raw_old_pc =
      Simulator::StripPAC(old_pc, Simulator::kInstructionPointer);
  // Verify that the old address is authenticated.
  CHECK_EQ(auth_old_pc, raw_old_pc);
  new_pc = Simulator::AddPAC(new_pc, sp, Simulator::kPACKeyIB,
                             Simulator::kInstructionPointer);
#else
  // Only store newly signed address after we have verified that the old
  // address is authenticated.
  asm volatile(
      " mov x17, %[new_pc]\n"
      " mov x16, %[sp]\n"
      " pacib1716\n"
      " mov %[new_pc], x17\n"
      " mov x17, %[old_pc]\n"
      " autib1716\n"
      // Save LR.
      " mov x16, x30\n"
      // Check if authentication was successful, otherwise crash.
      " mov x30, x17\n"
      " xpaclri\n"
      " cmp x30, x17\n"
      // Restore LR, to help with unwinding in case `brk #0` is hit below.
      " mov x30, x16\n"
      " b.eq 1f\n"
      " brk #0\n"
      "1:\n"
      : [new_pc] "+&r"(new_pc)
      : [sp] "r"(sp), [old_pc] "r"(old_pc)
      : "x16", "x17", "x30", "cc");
#endif
  *pc_address = new_pc;
}
References v8::internal::impl::AuthPAC(), and CHECK_EQ.
Referenced by v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(), v8::internal::StackFrame::IteratePc(), v8::internal::wasm::DebugInfoImpl::UpdateReturnAddress(), v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor::VisitThread(), and v8::internal::anonymous_namespace{deoptimizer.cc}::ActivationsFinder::VisitThread().
SignAndCheckPC()
Address v8::internal::PointerAuthentication::SignAndCheckPC (Isolate * isolate, Address pc, Address sp) [inline], [static]
Definition at line 141 of file pointer-authentication-arm64.h.
                                                                    {
  pc = impl::SignPC(pc, sp);
  Deoptimizer::EnsureValidReturnAddress(isolate,
                                        PointerAuthentication::StripPAC(pc));
  return pc;
}
References v8::internal::Deoptimizer::EnsureValidReturnAddress(), v8::internal::impl::SignPC(), and StripPAC().
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
StripPAC()
Address v8::internal::PointerAuthentication::StripPAC (Address pc) [inline], [static]
Definition at line 76 of file pointer-authentication-arm64.h.
                                                            {
#ifdef USE_SIMULATOR
  return Simulator::StripPAC(pc, Simulator::kInstructionPointer);
#else
  // x30 == lr, but use 'x30' instead of 'lr' below, as GCC does not accept
  // 'lr' in the clobbers list.
  asm volatile(
      " mov x16, x30\n"
      " mov x30, %[pc]\n"
      " xpaclri\n"
      " mov %[pc], x30\n"
      " mov x30, x16\n"
      : [pc] "+r"(pc)
      :
      : "x16", "x30");
  return pc;
#endif
}
Referenced by v8::internal::FrameWriter::DebugPrintOutputPc(), v8::anonymous_namespace{unwinder.cc}::GetReturnAddressFromFP(), SignAndCheckPC(), v8::internal::Deoptimizer::TraceDeoptBegin(), and v8::internal::StackFrame::unauthenticated_pc().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/pointer-authentication.h
/mnt/V8SourceCode/src/execution/arm64/pointer-authentication-arm64.h
/mnt/V8SourceCode/src/execution/pointer-authentication-dummy.h