v8::internal::torque::Type Class Reference
#include <types.h>
Public Types
enum class HandleKind { kIndirect
, kDirect
 }
Public Member Functions
Type & operator= (const Type &other)=delete
virtual bool IsSubtypeOf (const Type *supertype) const
std::string ToString () const
virtual std::string SimpleName () const
std::string GetHandleTypeName (HandleKind kind, const std::string &type_name) const
std::string TagglifiedCppTypeName () const
std::string HandlifiedCppTypeName (HandleKind kind) const
const Type * parent () const
bool IsVoid () const
bool IsNever () const
bool IsBool () const
bool IsConstexprBool () const
bool IsVoidOrNever () const
bool IsFloat32 () const
bool IsFloat64 () const
std::string GetGeneratedTypeName () const
std::string GetGeneratedTNodeTypeName () const
virtual bool IsConstexpr () const
virtual bool IsTransient () const
virtual const Type * NonConstexprVersion () const
virtual std::string GetConstexprGeneratedTypeName () const
std::optional< const ClassType * > ClassSupertype () const
std::optional< const StructType * > StructSupertype () const
std::optional< const AggregateType * > AggregateSupertype () const
virtual std::vector< TypeChecker > GetTypeCheckers () const
virtual std::string GetRuntimeType () const
virtual std::string GetDebugType () const
void AddAlias (std::string alias) const
size_t id () const
const MaybeSpecializationKey & GetSpecializedFrom () const
virtual void SetConstexprVersion (const Type *type) const
virtual const Type * ConstexprVersion () const
virtual size_t AlignmentLog2 () const
Static Public Member Functions
static const Type * CommonSupertype (const Type *a, const Type *b)
static std::optional< const Type * > MatchUnaryGeneric (const Type *type, GenericType *generic)
static std::string ComputeName (const std::string &basename, MaybeSpecializationKey specialized_from)
Protected Member Functions
Type (TypeBase::Kind kind, const Type *parent, MaybeSpecializationKey specialized_from=std::nullopt)
Type (const Type &other) V8_NOEXCEPT
void set_parent (const Type *t)
int Depth () const
virtual std::string ToExplicitString () const =0
virtual std::string GetGeneratedTypeNameImpl () const =0
virtual std::string GetGeneratedTNodeTypeNameImpl () const =0
virtual std::string SimpleNameImpl () const =0
Private Member Functions
bool IsAbstractName (const std::string &name) const
Private Attributes
const Type * parent_
std::set< std::string > aliases_
size_t id_
MaybeSpecializationKey specialized_from_
const Type * constexpr_version_ = nullptr
Detailed Description
Definition at line 105 of file types.h.
Member Enumeration Documentation
HandleKind
enum v8::internal::torque::Type::HandleKind [strong]
Enumerator
kIndirect
kDirect
Definition at line 117 of file types.h.
{ kIndirect, kDirect };
Constructor & Destructor Documentation
Type() [1/2]
v8::internal::torque::Type::Type (TypeBase::Kind kind, const Type * parent, MaybeSpecializationKey specialized_from = std::nullopt) [protected]
Type() [2/2]
v8::internal::torque::Type::Type (const Type & other) [protected]
Member Function Documentation
AddAlias()
void v8::internal::torque::Type::AddAlias (std::string alias) const [inline]
Definition at line 150 of file types.h.
{ aliases_.insert(std::move(alias)); }
AggregateSupertype()
std::optional<const AggregateType*> v8::internal::torque::Type::AggregateSupertype () const
Referenced by v8::internal::torque::AggregateType::LastField(), and v8::internal::torque::AggregateType::Methods().
AlignmentLog2()
virtual size_t v8::internal::torque::Type::AlignmentLog2 () const [virtual]
Reimplemented in v8::internal::torque::StructType, and v8::internal::torque::AbstractType.
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), v8::internal::torque::StructType::AlignmentLog2(), and v8::internal::torque::Field::ValidateAlignment().
ClassSupertype()
std::optional<const ClassType*> v8::internal::torque::Type::ClassSupertype () const
Referenced by v8::internal::torque::ImplementationVisitor::GenerateArrayLength(), and v8::internal::torque::ImplementationVisitor::GenerateFieldAccess().
CommonSupertype()
static const Type* v8::internal::torque::Type::CommonSupertype (const Type * a, const Type * b) [static]
ComputeName()
static std::string v8::internal::torque::Type::ComputeName (const std::string & basename, MaybeSpecializationKey specialized_from) [static]
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
ConstexprVersion()
virtual const Type* v8::internal::torque::Type::ConstexprVersion () const [inline], [virtual]
Reimplemented in v8::internal::torque::BitFieldStructType.
Definition at line 165 of file types.h.
                                               {
    if (constexpr_version_) return constexpr_version_;
    if (IsConstexpr()) return this;
    if (parent()) return parent()->ConstexprVersion();
    return nullptr;
  }
References ConstexprVersion().
Referenced by ConstexprVersion(), v8::internal::torque::BitFieldStructType::ConstexprVersion(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), and v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GetTypeNameForAccessor().
Depth()
int v8::internal::torque::Type::Depth () const [protected]
GetConstexprGeneratedTypeName()
virtual std::string v8::internal::torque::Type::GetConstexprGeneratedTypeName () const [virtual]
Reimplemented in v8::internal::torque::UnionType.
Referenced by v8::internal::torque::anonymous_namespace{cc-generator.cc}::GetBitFieldSpecialization(), v8::internal::torque::anonymous_namespace{csa-generator.cc}::GetBitFieldSpecialization(), and v8::internal::torque::UnionType::InsertConstexprGeneratedTypeName().
GetDebugType()
virtual std::string v8::internal::torque::Type::GetDebugType () const [virtual]
Reimplemented in v8::internal::torque::UnionType.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFunction().
GetGeneratedTNodeTypeName()
std::string v8::internal::torque::Type::GetGeneratedTNodeTypeName () const
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::TopType::GetGeneratedTNodeTypeNameImpl(), v8::internal::torque::ClassType::GetGeneratedTypeNameImpl(), and v8::internal::torque::UnionType::InsertGeneratedTNodeTypeName().
GetGeneratedTNodeTypeNameImpl()
virtual std::string v8::internal::torque::Type::GetGeneratedTNodeTypeNameImpl () const [protected], [pure virtual]
Implemented in v8::internal::torque::ClassType, v8::internal::torque::AggregateType, v8::internal::torque::BitFieldStructType, v8::internal::torque::UnionType, v8::internal::torque::BuiltinPointerType, v8::internal::torque::AbstractType, and v8::internal::torque::TopType.
GetGeneratedTypeName()
std::string v8::internal::torque::Type::GetGeneratedTypeName () const
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::GenerateFunction(), and v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GetTypeNameForAccessor().
GetGeneratedTypeNameImpl()
virtual std::string v8::internal::torque::Type::GetGeneratedTypeNameImpl () const [protected], [pure virtual]
Implemented in v8::internal::torque::ClassType, v8::internal::torque::StructType, v8::internal::torque::AggregateType, v8::internal::torque::BitFieldStructType, v8::internal::torque::UnionType, v8::internal::torque::BuiltinPointerType, v8::internal::torque::AbstractType, and v8::internal::torque::TopType.
GetHandleTypeName()
std::string v8::internal::torque::Type::GetHandleTypeName (HandleKind kind, const std::string & type_name) const
GetRuntimeType()
virtual std::string v8::internal::torque::Type::GetRuntimeType () const [virtual]
Reimplemented in v8::internal::torque::UnionType.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFunction().
GetSpecializedFrom()
const MaybeSpecializationKey& v8::internal::torque::Type::GetSpecializedFrom () const [inline]
Definition at line 152 of file types.h.
                                                           {
    return specialized_from_;
  }
Referenced by v8::internal::torque::TypeArgumentInference::MatchGeneric().
GetTypeCheckers()
virtual std::vector<TypeChecker> v8::internal::torque::Type::GetTypeCheckers () const [inline], [virtual]
Reimplemented in v8::internal::torque::AggregateType, v8::internal::torque::BitFieldStructType, v8::internal::torque::UnionType, v8::internal::torque::BuiltinPointerType, and v8::internal::torque::AbstractType.
Definition at line 146 of file types.h.
{ return {}; }
HandlifiedCppTypeName()
std::string v8::internal::torque::Type::HandlifiedCppTypeName (HandleKind kind) const
id()
size_t v8::internal::torque::Type::id () const [inline]
Definition at line 151 of file types.h.
{ return id_; }
Referenced by v8::internal::torque::operator<().
IsAbstractName()
bool v8::internal::torque::Type::IsAbstractName (const std::string & name) const [private]
IsBool()
bool v8::internal::torque::Type::IsBool () const [inline]
Definition at line 127 of file types.h.
{ return IsAbstractName(BOOL_TYPE_STRING); }
References v8::internal::torque::BOOL_TYPE_STRING.
IsConstexpr()
virtual bool v8::internal::torque::Type::IsConstexpr () const [inline], [virtual]
Reimplemented in v8::internal::torque::UnionType, and v8::internal::torque::AbstractType.
Definition at line 136 of file types.h.
                                   {
    if (parent()) DCHECK(!parent()->IsConstexpr());
    return false;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::torque::AbstractType::AbstractType(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::GenerateFunction(), v8::internal::torque::ClassType::GetGeneratedTypeNameImpl(), v8::internal::torque::ImplementationVisitor::InlineMacro(), and v8::internal::torque::VisitResult::VisitResult().
IsConstexprBool()
bool v8::internal::torque::Type::IsConstexprBool () const [inline]
Definition at line 128 of file types.h.
                               {
    return IsAbstractName(CONSTEXPR_BOOL_TYPE_STRING);
  }
References v8::internal::torque::CONSTEXPR_BOOL_TYPE_STRING.
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
IsFloat32()
bool v8::internal::torque::Type::IsFloat32 () const [inline]
Definition at line 132 of file types.h.
{ return IsAbstractName(FLOAT32_TYPE_STRING); }
References v8::internal::torque::FLOAT32_TYPE_STRING.
Referenced by v8::internal::torque::DeclarationVisitor::CreateBuiltin().
IsFloat64()
bool v8::internal::torque::Type::IsFloat64 () const [inline]
Definition at line 133 of file types.h.
{ return IsAbstractName(FLOAT64_TYPE_STRING); }
References v8::internal::torque::FLOAT64_TYPE_STRING.
Referenced by v8::internal::torque::DeclarationVisitor::CreateBuiltin().
IsNever()
bool v8::internal::torque::Type::IsNever () const [inline]
Definition at line 126 of file types.h.
{ return IsAbstractName(NEVER_TYPE_STRING); }
References v8::internal::torque::NEVER_TYPE_STRING.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::InlineMacro(), v8::internal::torque::CSAGenerator::PostCallableExceptionPreparation(), and v8::internal::torque::ImplementationVisitor::Visit().
IsSubtypeOf()
virtual bool v8::internal::torque::Type::IsSubtypeOf (const Type * supertype) const [virtual]
Reimplemented in v8::internal::torque::UnionType.
Referenced by v8::internal::torque::ParameterDifference::AddParameter(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::CanContainHeapObjects(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::anonymous_namespace{implementation-visitor.cc}::CanGenerateFieldAccessors(), v8::internal::torque::StructType::ClassifyContents(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::DeclarationVisitor::CreateBuiltin(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::EmitLoadFieldStatement(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::EmitStoreFieldStatement(), v8::internal::torque::anonymous_namespace{instructions.cc}::ExpectSubtype(), v8::internal::torque::UnionType::Extend(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GenerateClassFieldVerifier(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GenerateFieldValueVerifier(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::GetSectionFor(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GetTypeNameForAccessor(), v8::internal::torque::TypeOracle::GetUnionType(), v8::internal::torque::ClassType::HasStaticSize(), v8::internal::torque::IsAssignableFrom(), v8::internal::torque::UnionType::IsSupertypeOf(), v8::internal::torque::Block::SetInputTypes(), v8::internal::torque::DeclarationVisitor::Visit(), and v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods().
IsTransient()
virtual bool v8::internal::torque::Type::IsTransient () const [inline], [virtual]
Reimplemented in v8::internal::torque::ClassType, v8::internal::torque::UnionType, and v8::internal::torque::AbstractType.
Definition at line 140 of file types.h.
{ return false; }
IsVoid()
bool v8::internal::torque::Type::IsVoid () const [inline]
Definition at line 125 of file types.h.
{ return IsAbstractName(VOID_TYPE_STRING); }
References v8::internal::torque::VOID_TYPE_STRING.
Referenced by v8::internal::torque::ImplementationVisitor::InlineMacro(), and v8::internal::torque::ImplementationVisitor::Visit().
IsVoidOrNever()
bool v8::internal::torque::Type::IsVoidOrNever () const [inline]
Definition at line 131 of file types.h.
{ return IsVoid() || IsNever(); }
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFunction(), v8::internal::torque::Callable::HasReturnValue(), and v8::internal::torque::ImplementationVisitor::Visit().
MatchUnaryGeneric()
static std::optional<const Type*> v8::internal::torque::Type::MatchUnaryGeneric (const Type * type, GenericType * generic) [static]
Referenced by v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldsRange::end(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::anonymous_namespace{csa-generator.cc}::GetBitFieldSpecialization(), v8::internal::torque::LocationReference::HeapSlice(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldIterator::operator*(), and v8::internal::torque::LocationReference::ReferencedType().
NonConstexprVersion()
virtual const Type* v8::internal::torque::Type::NonConstexprVersion () const [inline], [virtual]
Reimplemented in v8::internal::torque::UnionType, and v8::internal::torque::AbstractType.
Definition at line 141 of file types.h.
{ return this; }
Referenced by v8::internal::torque::ImplementationVisitor::GetCommonType(), v8::internal::torque::AbstractType::NonConstexprVersion(), and v8::internal::torque::UnionType::NonConstexprVersion().
operator=()
Type& v8::internal::torque::Type::operator= (const Type & other) [delete]
parent()
const Type* v8::internal::torque::Type::parent () const [inline]
Definition at line 124 of file types.h.
{ return parent_; }
Referenced by v8::internal::torque::AbstractType::AbstractType(), v8::internal::torque::ClassType::GenerateAccessors(), v8::internal::torque::ClassType::GetFieldPreceding(), v8::internal::torque::ClassType::GetSuperClass(), v8::internal::torque::ClassType::HasIndexedFieldsIncludingInParents(), v8::internal::torque::TypeOracle::ImplicitlyConvertableFrom(), v8::internal::torque::AggregateType::Methods(), and v8::internal::torque::AbstractType::NonConstexprVersion().
set_parent()
void v8::internal::torque::Type::set_parent (const Type * t) [inline], [protected]
Definition at line 178 of file types.h.
{ parent_ = t; }
SetConstexprVersion()
virtual void v8::internal::torque::Type::SetConstexprVersion (const Type * type) const [inline], [virtual]
Reimplemented in v8::internal::torque::BitFieldStructType.
Definition at line 161 of file types.h.
                                                           {
    constexpr_version_ = type;
  }
References v8::internal::tracing::type.
Referenced by v8::internal::torque::TypeOracle::GetAbstractType().
SimpleName()
virtual std::string v8::internal::torque::Type::SimpleName () const [virtual]
Referenced by v8::internal::torque::Declarations::CreateMethod(), v8::internal::torque::AbstractType::SimpleNameImpl(), and v8::internal::torque::StructType::StructType().
SimpleNameImpl()
virtual std::string v8::internal::torque::Type::SimpleNameImpl () const [protected], [pure virtual]
Implemented in v8::internal::torque::StructType, v8::internal::torque::AggregateType, v8::internal::torque::BitFieldStructType, v8::internal::torque::UnionType, v8::internal::torque::BuiltinPointerType, v8::internal::torque::AbstractType, and v8::internal::torque::TopType.
StructSupertype()
std::optional<const StructType*> v8::internal::torque::Type::StructSupertype () const
Referenced by v8::internal::torque::Binding< T >::CheckWritten(), v8::internal::torque::StructType::ClassifyContents(), v8::internal::torque::DeclarationVisitor::CreateBuiltin(), v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateClassDefinitions(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GenerateClassFieldVerifier(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateFieldValueAccessor(), v8::internal::torque::ImplementationVisitor::GenerateReferenceToItemInHeapSlice(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::GetSectionFor(), and v8::internal::torque::ProjectStructField().
TagglifiedCppTypeName()
std::string v8::internal::torque::Type::TagglifiedCppTypeName () const
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFunction(), and v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GetTypeNameForAccessor().
ToExplicitString()
virtual std::string v8::internal::torque::Type::ToExplicitString () const [protected], [pure virtual]
Implemented in v8::internal::torque::ClassType, v8::internal::torque::StructType, v8::internal::torque::BitFieldStructType, v8::internal::torque::UnionType, v8::internal::torque::BuiltinPointerType, v8::internal::torque::AbstractType, and v8::internal::torque::TopType.
ToString()
std::string v8::internal::torque::Type::ToString () const
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateFieldAccessors(), v8::internal::torque::operator<<(), and v8::internal::torque::TopType::ToExplicitString().
Member Data Documentation
aliases_
std::set<std::string> v8::internal::torque::Type::aliases_ [mutable], [private]
Definition at line 190 of file types.h.
constexpr_version_
const Type* v8::internal::torque::Type::constexpr_version_ = nullptr [mutable], [private]
Definition at line 193 of file types.h.
id_
size_t v8::internal::torque::Type::id_ [private]
Definition at line 191 of file types.h.
parent_
const Type* v8::internal::torque::Type::parent_ [private]
Definition at line 189 of file types.h.
specialized_from_
MaybeSpecializationKey v8::internal::torque::Type::specialized_from_ [private]
Definition at line 192 of file types.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/types.h