/mnt/V8SourceCode/src/fuzzilli/cov.h File Reference
#include <cstdint>
#include <vector>
Functions
void sanitizer_cov_reset_edgeguards ()
uint32_t sanitizer_cov_count_discovered_edges ()
void cov_init_builtins_edges (uint32_t num_edges)
void cov_update_builtins_basic_block_coverage (const std::vector< bool > &cov_map)
Function Documentation
cov_init_builtins_edges()
void cov_init_builtins_edges (uint32_t num_edges)
Definition at line 112 of file cov.cc.
                                                 {
  if (num_edges + shmem->num_edges > MAX_EDGES) {
    fprintf(stderr,
            "[COV] Error: Insufficient amount of edges left for builtins "
            "coverage.\n");
    exit(-1);
  }
  builtins_edge_count = num_edges;
  builtins_start = 1 + shmem->num_edges;
  shmem->num_edges += builtins_edge_count;
  fprintf(stderr, "[COV] Additional %d edges for builtins initialized.\n",
          num_edges);
}
References builtins_edge_count, builtins_start, MAX_EDGES, shmem_data::num_edges, and shmem.
Referenced by v8::Shell::Main().
cov_update_builtins_basic_block_coverage()
void cov_update_builtins_basic_block_coverage (const std::vector< bool > & cov_map)
Definition at line 129 of file cov.cc.
                                    {
  if (cov_map.size() != builtins_edge_count) {
    fprintf(stderr, "[COV] Error: Size of builtins cov map changed.\n");
    exit(-1);
  }
  for (uint32_t i = 0; i < cov_map.size(); ++i) {
    if (cov_map[i]) {
      const uint32_t byteIndex = (i + builtins_start) >> 3;
      const uint32_t bitIndex = (i + builtins_start) & 7;
      shmem->edges[byteIndex] |= (1 << bitIndex);
    }
  }
}
References builtins_edge_count, builtins_start, shmem_data::edges, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and shmem.
Referenced by v8::Shell::Main().
sanitizer_cov_count_discovered_edges()
uint32_t sanitizer_cov_count_discovered_edges ()
Definition at line 88 of file cov.cc.
                                                {
  uint32_t on_edges_counter = 0;
  for (uint32_t i = 1; i < builtins_start; ++i) {
    const uint32_t byteIndex = i >> 3; // Divide by 8 using a shift operation
    const uint32_t bitIndex = i & 7; // Modulo 8 using a bitwise AND operation
    if (shmem->edges[byteIndex] & (1 << bitIndex)) {
      ++on_edges_counter;
    }
  }
  return on_edges_counter;
}
References builtins_start, shmem_data::edges, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and shmem.
Referenced by v8::Shell::Main().
sanitizer_cov_reset_edgeguards()
void sanitizer_cov_reset_edgeguards ()
Definition at line 33 of file cov.cc.
                                      {
  uint32_t N = 0;
  for (uint32_t* x = edges_start; x < edges_stop && N < MAX_EDGES; x++)
    *x = ++N;
}
References edges_start, edges_stop, MAX_EDGES, and v8::internal::N.
Referenced by __sanitizer_cov_trace_pc_guard_init(), and v8::Shell::Main().